### ISSUE TITLE
Tab missing icon when using darkmode

### ISSUE THREAD

**Issue by ozone10** [notepad-plus-plus/notepad-plus-plus#10000]
When using darkmode, tab is missing icon.
I does not matter if alternate icon option is enabled.

![image](https://user-images.githubusercontent.com/55940305/121814359-1ec3b080-cc60-11eb-9397-c4f434ce70eb.png)

**Comment by sasumner** [comment]
This is desired behavior moving forward.

**Comment by Suesskirsche** [comment]
Unbelievable, that you developers of Notepad++ handled 10,000 tickets already! 

Thank you so much for your constant effort creating and improving that fine piece of software!

Kind regards 

Michael 


Am 14. Juni 2021 01:25:41 MESZ schrieb sasumner ***@***.***>:
