### ISSUE TITLE
SQL type escapes \'

### ISSUE THREAD

**Issue by ZachBora** [notepad-plus-plus/notepad-plus-plus#10008]
### Description of the Issue
When I'm in language SQL it escapes apostrophe preceded by a slash. I'm using MSSQL so maybe it's different in other SQL like Mysql or postgresql. If this is how it works in other SQL languages maybe have a seperate Language style for MSSQL. I notice that in my code section below it's also the wrong escaping from markdown...

### Steps to Reproduce the Issue
Example stored procedure : 
```SQL
EXEC [dbo].[ConfigAddOrUpdate]	@ConfigName = 'Management_Top50_Export_Path', @StringValue='\\uncpath\Dept\CustomerStatus\', @IntValue='', @Description='',@ForceValue=0
```

The \' escapes the '

### Expected Behavior
I expect it not to escape it because it doesn't actually escape the apostrophe.

### Actual Behavior
It makes the apostrophe part of the string and messes with the formatting of rest of the script.

### Debug Information
Notepad++ v8   (64-bit)
Build time : Jun  6 2021 - 18:38:25
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 10 Pro (64-bit) 
OS Version : 2009
OS Build : 19042.985
Current ANSI codepage : 1252
Plugins : mimeTools.dll NppConverter.dll NppExport.dll 
![formattingissue](https://user-images.githubusercontent.com/1097596/121954342-a37c0080-cd2c-11eb-9162-eedfa115bbfb.png)

**Comment by ArkadiuszMichalski** [comment]
Try this: https://github.com/notepad-plus-plus/notepad-plus-plus/issues/8919#issuecomment-701285073
