### ISSUE TITLE
Open File dialog has "Save" button instead of "Open" button

### ISSUE THREAD

**Issue by Theoinf0** [notepad-plus-plus/notepad-plus-plus#10006]
Is this intended behaviour?

I used installation of 64bit Notepad++ v8

![open-save](https://user-images.githubusercontent.com/52457595/121920679-2f435c00-cd30-11eb-9ec2-8f3fef6b12ea.jpg)

I tested fresh installation of 32bit Notepad++ v8 in a virtual machine with same result

![Screenshot 2021-06-14 165220](https://user-images.githubusercontent.com/52457595/121921676-21420b00-cd31-11eb-9425-13e88f1b5e78.jpg)

It is not a bug as rather annoyance or graphical glitch and I am worried to press "Save" even I know it will open the file. Not a high priority. Thanks

**Comment by pablosambuco** [comment]
+1

I'm on v8 64bit for windows, with spanish localization

![image](https://user-images.githubusercontent.com/669390/121926772-aff45f00-cd14-11eb-9aa5-3438c274732e.png)

**Comment by mere-human** [comment]
This is a known issue #9966.
It has been already fixed.
The fix will be available in the upcoming version.

**Comment by mere-human** [comment]
@sasumner Could you, please, close this one?

**Comment by sasumner** [comment]
@Theoinf0 @pablosambuco Please search for existing issues before creating new ones -- thanks!
