### ISSUE TITLE
Notepad++ 8 Craches on start

### ISSUE THREAD

**Issue by deliocf** [notepad-plus-plus/notepad-plus-plus#10015]
### Description of the Issue
Notepad++ craches on start. 
More often when opening a file from explorer context menu.

### Steps to Reproduce the Issue
1.  Open a Notepad++  v8.0 normally
2.  Open a file with Notepad++ v8 from ContextMenu
3. 

### Expected Behavior
Open Notepad++

### Actual Behavior
A error message: Exception on WM_CREATE (bad alloction)

### Debug Information
Notepad++ v8   (32-bit)
Build time : Jun  6 2021 - 18:41:52
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 10 Enterprise (64-bit) 
OS Version : 2009
OS Build : 19042.1052
Current ANSI codepage : 1252
Plugins : BigFiles.dll ccc.dll Explorer.dll JsMapParser.NppPlugin.dll mimeTools.dll NppConverter.dll NppExport.dll NppFTP.dll NPPJSONViewer.dll NppSaveAsAdmin.dll NppTextFX.dll PreviewHTML.dll RegexTrainer.dll sql.dll urlPlugin.dll XMLTools.dll _CustomizeToolbar.dll 

![Captura de tela 2021-06-16 093057](https://user-images.githubusercontent.com/33035026/122220094-63c92c00-ce86-11eb-9880-3e07d50eb9e1.png)

**Comment by donho** [comment]
Could you try the latest version which was out on 17/06/2021?
https://notepad-plus-plus.org/downloads/v8.1/

One crash issue has been fixed in this release.

**Comment by deliocf** [comment]
Thanks,
I noticed that executing Notepad++ v8.0 with -noPlugins the error doesn't
ocurre. So, I've disable some of installed plugins and discovered that is
there a incompatible one between them. disabling "BigFiles - Open Very
Large Files 0.1.3"   I solved the problem.


*Délio Carvalho de Figueiredo*
***@***.***
***@***.***>
***@***.***
Fone: (31)99981-5748
***********************************
"Homem Conhece-te a Ti Mesmo"



Em qui., 17 de jun. de 2021 às 09:14, Don HO ***@***.***>
escreveu:

**Comment by deliocf** [comment]
I noticed that executing Notepad++ v8.0 with -noPlugins the error doesn't ocurre. So, I've disable some of installed plugins and discovered that is there a incompatible one between them. disabling "BigFiles - Open Very Large Files 0.1.3"   I solved the problem.

**Comment by chcg** [comment]
@deliocf You might want to report the issue here https://github.com/superolmo/BigFiles/issues
