### ISSUE TITLE
Search and Replace in Column Selection Mode in Notepad++

### ISSUE THREAD

**Issue by misc-cpu** [notepad-plus-plus/notepad-plus-plus#10012]
### Description of the Issue

**Search and Replace in Column Selection Mode in Notepad++**
### Steps to Reproduce the Issue

1. Selective Search and Replace in Column Selection Mode in Notepad++ is currently NOT Possible!
2. It is already beautifully handled in EditPad Lite 8 from year 2020 onwards!
3. Even after several requests this feature is NOT included in Notepad++!
4. I think they are unable to manage or code it properly!

### Expected Behavior

1. Selective Search and Replace in Column Selection Mode in Notepad++ is currently NOT Possible!
2. It is already beautifully handled in EditPad Lite 8 from year 2020 onwards!
3. Even after several requests this feature is NOT included in Notepad++!
4. I think they are unable to manage or code it properly!

### Actual Behavior

1. Selective Search and Replace in Column Selection Mode in Notepad++ is currently NOT Possible!
2. It is already beautifully handled in EditPad Lite 8 from year 2020 onwards!
3. Even after several requests this feature is NOT included in Notepad++!
4. I think they are unable to manage or code it properly!

**Comment by sasumner** [comment]
>Even after several requests this feature is NOT included in Notepad++!

I'm not going to bother searching for the duplicates that @misc-cpu hints at; we'll just close this request.

**Comment by sasumner** [comment]
Duplicate (by the same issue author) at #9584
