### ISSUE TITLE
XML Tag-Matching Should Be Case-Sensitive

### ISSUE THREAD

**Issue by nwehneman** [notepad-plus-plus/notepad-plus-plus#10011]
### Description of the Issue

Notepad++ identifies and color-matches XML tags based on a case-insensitive search. For example, the tag `<fileName>` will be matched to the closing tag of `</filename>.` (Note the differing capitalization of the letter "N".) However, the XML standard is case-sensitive. Additionally, C# compiled into Javascript via Unity follows the XML standard, generating a runtime exception when parsing an XML file that contains case-insensitive tag-matching.

### Steps to Reproduce the Issue

1. Create an opening tag of `<fileName>` in an XML file edited in Notepad++
2. Create a closing tag of `</filename>` in the same file
3. Observe that Notepad++ colors both tags in purple to indicate a match

### Expected Behavior

I would expect the tags to **not** be identified as a match as they do not match per the XML standard and at least one implementation of that standard.

### Actual Behavior

Notepad++ identifies the tags as a match.

### Debug Information

Notepad++ v7.9.5   (64-bit)
Build time : Mar 21 2021 - 02:13:17
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS Name : Windows 10 Pro (64-bit) 
OS Version : 1809
OS Build : 17763.1577
Current ANSI codepage : 1252
Plugins : DSpellCheck.dll mimeTools.dll NppConverter.dll NppExport.dll 

![image](https://user-images.githubusercontent.com/85947873/122074128-f4403780-cdc6-11eb-8335-b60f81bdfe07.png)

**Comment by ArkadiuszMichalski** [comment]
@nwehneman But your example is not valid XML, give some example of valid XML where highlighting doesn't work well. Remember that Notepad ++ does not perform XML validation. I mean in your example you have `<fileName>` opening tag (but not closing), and `</filename>` closing tag (without opening).

![image](https://user-images.githubusercontent.com/2730894/123798919-f7b7e080-d8e7-11eb-8b28-2093075e8c2d.png)
