### ISSUE TITLE
CTRL+F's CTRL+arrows are not smart/consistent

### ISSUE THREAD

**Issue by dylanh724** [notepad-plus-plus/notepad-plus-plus#10018]
### Description of the Issue

For example, if I have `<style=neutral>Neutral</style>`, in any editor (including N++) I can CTRL+right arrow to jump between blocks. In this case, I'd expect the following order per `CTRL+right arrow` (GIF):

![FTET7DsgZW](https://user-images.githubusercontent.com/8840024/122330570-04424d80-cf66-11eb-8a33-b038b2aefa0f.gif)

Instead, in the `CTRL+F` (or `CTRL+H`) input field, it skips over the entire thing. This happens with any kind of <> tag and probably for any special character that is similar. 

**For what serves the purpose of N++, I feel that this should be consistent with the editor.**

### Debug Information
Notepad++ v7.9.5   (32-bit)
Build time : Mar 21 2021 - 02:09:07
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS Name : Windows 10 Enterprise (64-bit) 
OS Version : 2009
OS Build : 19043.1055
Current ANSI codepage : 1252
Plugins : JSLintNpp.dll JSMinNPP.dll mimeTools.dll NppConverter.dll NppExport.dll

**Comment by dylanh724** [comment]
![9Q1o8AOFm3](https://user-images.githubusercontent.com/8840024/122331046-c7c32180-cf66-11eb-8d59-9f0b7c74a43c.gif)

Seems like edits are disabled, but here is the GIF from N++ `CTRL+F` doing the same thing.

**Comment by dylanh724** [comment]
Seems like edits are disabled, but here is the GIF from N++ `CTRL+F` doing the same thing (bottom) next to the editor (top):

![image](https://user-images.githubusercontent.com/8840024/122331111-df020f00-cf66-11eb-86f6-c9219ba780bf.png)
![9Q1o8AOFm3](https://user-images.githubusercontent.com/8840024/122331046-c7c32180-cf66-11eb-8d59-9f0b7c74a43c.gif)

**Comment by dylanh724** [comment]
Seems like edits are disabled, but here is the GIF from N++ `CTRL+F` doing the same thing:
![9Q1o8AOFm3](https://user-images.githubusercontent.com/8840024/122331046-c7c32180-cf66-11eb-8d59-9f0b7c74a43c.gif)

**Comment by sasumner** [comment]
The "editor" is a Scintilla window; the _Find what_ box is a Windows combobox.  They aren't going to have the same behaviors, sorry.

**Comment by mere-human** [comment]
It's still worth checking.
Maybe, it's possible to do.
See: https://docs.microsoft.com/en-us/windows/win32/api/winuser/nc-winuser-editwordbreakproca

**Comment by sasumner** [comment]
IMO it isn't something worth spending development effort on.
But to each his own opinion/effort on it.  :-)

**Comment by dylanh724** [comment]
> IMO it isn't something worth spending development effort on.
> But to each his own opinion/effort on it. :-)

Regex find and replace is incredibly powerful. We're also developers here. CtrlF and CtrlH should be a devs best friend. The collective amount of time lost from this is substantial over the years. For a core search field to act like regular Notepad imo is not what's expected in this fine software.
