### ISSUE TITLE
english.xml is filled with unnecessary characters &amp;

### ISSUE THREAD

**Issue by cpolychronidis** [notepad-plus-plus/notepad-plus-plus#10020]
### Description of the Issue
In english.xml entries' names are filled with `&amp;` which seem to serve no purpose since removing them seems to not affect Notepad++. 
Is there something I don't understand regarding the usefulness of `&amp;`"?

### Steps to Reproduce the Issue
1. Open english.xml with Notepad++
2. Use Ctrl + F to find the 1st `&amp;`
3. Delete it
4. Save english.xml
5. Exit Notepad++
6. Re-open Notepad++

### Expected Behavior
The UI text gets messed up.

### Actual Behavior
Nothing changes.

### Debug Information
Notepad++ v8.1   (32-bit)
Build time : Jun 17 2021 - 01:52:11
Path : C:\Users\cpoly\Desktop\Notepad++ 8.1\npp.8.1.portable\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : ON
Cloud Config : OFF
OS Name : Windows 10 Enterprise (64-bit) 
OS Version : 2004
OS Build : 19041.1052
Current ANSI codepage : 1252
Plugins : mimeTools.dll NppConverter.dll NppExport.dll

**Comment by mere-human** [comment]
Right. 
This thing is called "menu accelerators": https://docs.microsoft.com/en-us/windows/win32/menurc/using-keyboard-accelerators
It allows selecting menu entries with Alt pressed + letter.
For example, press `Alt + F` to open the File menu. Note the underline.
![image](https://user-images.githubusercontent.com/9664141/122394912-22687780-cf7f-11eb-978d-f60ff46712ec.png)

**Comment by cpolychronidis** [comment]
Thank you for enlightening me since I didn't know this. 
However, removing the &amp; from the whole file did not break `Alt + F` or any other menu accelerator.
