### ISSUE TITLE
Dark Mode: Find Dialog, Visual Glitch

### ISSUE THREAD

**Issue by MarkusBodensee** [notepad-plus-plus/notepad-plus-plus#10027]
### Description of the Issue
There is a visual glitch at the `Find what` combo box when opening the find dialog in dark mode. Does not happen in normal mode.

### Steps to Reproduce the Issue
1. Enable Dark Mode and restart Nodepad++ as recommended.
2. Open find dialog with `Ctrl + F`.
3. See visual glitch at the `Find what` combo box.

- Hovering the combo box or click on any other control --> visual glitch disappears.
- Click to edit view, which makes find dialog inactive --> visual glitch disappears.

### Expected Behavior
No visual glitch.

### Actual Behavior
![SearchReplaceV8 1](https://user-images.githubusercontent.com/82021174/122533510-f18d4e80-d021-11eb-9c6e-f768abdcd5e7.png)

### Debug Information
Notepad++ v8.1   (64-bit)
Build time : Jun 17 2021 - 01:56:07
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 10 Enterprise (64-bit) 
OS Version : 1909
OS Build : 18363.1556
Current ANSI codepage : 1252
Plugins : DSpellCheck.dll mimeTools.dll NppConverter.dll NppExport.dll

**Comment by rimrul** [comment]
> Hovering the combo box or click on any other control --> visual glitch disappears.
    Click to edit view, which makes find dialog inactive --> visual glitch disappears.

Resizing the dialog window makes it re-appear in v8.1.1
