### ISSUE TITLE
[Feature Request] Custom web browsers for file viewing

### ISSUE THREAD

**Issue by thomassmith311** [notepad-plus-plus/notepad-plus-plus#10024]
### Description of the Issue
Under "View", there is an option entitled "View Current File in", and hovering over it gives the options Firefox, Chrome, Edge, and IE. I propose that the user be able to set other web browsers that the file can be viewed in, rather than just these defaults. I use Waterfox and Chromium, neither of which are currently options.

### Expected Behavior
There should be a tab under Settings --> Preferences in which the user can select a web browser application, along with a form in which the user inputs the name of the web browser.

**Comment by sasumner** [comment]
You can set up a _Run_ menu entry to launch the current file in whatever program you'd like.  You specify the current file as `$(FULL_CURRENT_PATH)`.
