### ISSUE TITLE
[Feature Request] Improve DarkMode (TitleBar and ScrollBar)

### ISSUE THREAD

**Issue by ozone10** [notepad-plus-plus/notepad-plus-plus#10022]
### Description of the Issue

Some parts are not in darkmode
### Steps to Reproduce the Issue

1.  Open Notepad++ v8.1
2.  Enable DarkMode
3. a. Display some docked window (Project panel, Funstion list, ...) with scrollbar
b. Some dialog windows don't have dark titlebar.

### Expected Behavior

Scrollbar and titlebar are dark
### Actual Behavior

Scrollbar is sometimes light, titlebar is light

**Comment by donho** [comment]
Fixed by @ozone10
