### ISSUE TITLE
File Open dialog has "Save" button for confirmation

### ISSUE THREAD

**Issue by kalenwatermeyer** [notepad-plus-plus/notepad-plus-plus#10030]
### Description of the Issue
The **File Open** dialog has a **Save** button for confirmation. 

Surely this should say **Open** ?

![image](https://user-images.githubusercontent.com/1957266/122582304-ff44d300-d025-11eb-9bb7-8f6cabdf8879.png)

### Steps to Reproduce the Issue

1. Click **File** -> **Open**

### Expected Behavior

Expected the confirmation button to say **Open**

### Actual Behavior

Confirmation button has text: **Save**

### Debug Information

Notepad++ v8   (64-bit)
Build time : Jun  6 2021 - 18:38:25
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 10 Enterprise (64-bit) 
OS Version : 2009
OS Build : 19042.1052
Current ANSI codepage : 1252
Plugins : mimeTools.dll NppConverter.dll NppExport.dll XMLTools.dll

**Comment by sasumner** [comment]
Duplicate; fixed in 8.1. Closing.
