### ISSUE TITLE
GCC reports numerous warnings when Notepad++ is built

### ISSUE THREAD

**Issue by mere-human** [notepad-plus-plus/notepad-plus-plus#10037]
### Description of the Issue

The warnings make it harder to spot the compiler error if it's present.
Also, they could signal about a potential problem

### Steps to Reproduce the Issue

1. Build Notepad++ with MinGW using instructions in [BUILD.md](https://github.com/notepad-plus-plus/notepad-plus-plus/blob/master/BUILD.md#build-64-bits-binaries-with-gcc)

### Expected Behavior

No warnings are generated. Or the amount of warnings is minimal.

### Actual Behavior

98 warnings are reported.

### Debug Information

```
Notepad++ v8.1   (64-bit)
Build time : Jun 18 2021 - 23:34:10
Path : ...\Notepad++.exe
Command Line : -nosession -multiInst
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 10 Enterprise (64-bit) 
OS Version : 2009
OS Build : 19043.1052
Current ANSI codepage : 1252
Plugins : none
```

**Comment by ozone10** [comment]
Probably because of conversions, e.g. using `NULL`  (-Wconversion-null).

**Comment by mere-human** [comment]
> Probably because of conversions

Yes, I'm fixing the warnings right now. Just wanted to create an issue to follow the process.
