### ISSUE TITLE
Preference Regarding Warning About Deleted Files Remaining Open in Editor?

### ISSUE THREAD

**Issue by WCityMike** [notepad-plus-plus/notepad-plus-plus#10040]
If a file has been deleted that is open in Notepad++, Notepad++ will prompt and ask you if you wish to close the file in the editor.  Could a preference be created to disable this behavior?

**Comment by sasumner** [comment]
![image](https://user-images.githubusercontent.com/30118311/122657650-8af85580-d133-11eb-9621-b09427e26838.png)
