### ISSUE TITLE
[Translator Question]: What's wrong with this file?(ampersand in the middle of words)

### ISSUE THREAD

**Issue by Oymate** [notepad-plus-plus/notepad-plus-plus#10041]
https://github.com/Oymate/notepad-plus-plus/blob/master/PowerEditor/installer/nativeLang/english.xml

**Comment by sasumner** [comment]
`&amp;` in the "middle of words" is used to underline a character in a menu.  Some examples:

![image](https://user-images.githubusercontent.com/30118311/122670046-f3742080-d18d-11eb-981e-e52265480552.png)

**Comment by mere-human** [comment]
Also, it allows selecting menu items via Alt shortcut (example `Alt, E, S, Enter` - select all)

**Comment by sasumner** [comment]
@mere-human 

Well, I thought that was obvious...but maybe not! :-)
