### ISSUE TITLE
Find in Files broken when using more than 3 extensions

### ISSUE THREAD

**Issue by sanastasiou** [notepad-plus-plus/notepad-plus-plus#1004]
Using latest and greated Npp version (6.8.3) and trying following

Find in Files with this extension filter:

*.c, *.cpp, *.h

Works just fine.

Changing filter to this:

*.c, *.cpp, *.h, *.zstm, *.txt

Returns immediately and finds no results. I'd expect the same behavior regardless of the number of extensions...

Windows 10 64-bit.

Restoring the original filter produces the correct results...

**Comment by dail8859** [comment]
@sanastasiou I think you need to remove the commas. Looking at the code (and trying some tests out myself) it expects them to be separated by space characters only.

**Comment by sanastasiou** [comment]
OK, this means, that somehow with the 3 extensions only the "last" one was recognized? That's why it found some results? Otherwise I'd expect nothing to work at all. If this is the case, then feel free to close this ticket.

**Comment by dail8859** [comment]
With the 3 extensions, the first two had a comma after them, so for example it was trying to match `*.cpp,` (notice the comma at the end). So it probably would have only found a match in the `*.h` files.
