### ISSUE TITLE
[Feature Request] Use Explorer theme in list- and tree-views

### ISSUE THREAD

**Issue by ozone10** [notepad-plus-plus/notepad-plus-plus#10055]
Highlight in dark mode for list- and tree-view don't look good, too light.

![image](https://user-images.githubusercontent.com/55940305/122927861-d0e23300-d358-11eb-8cbd-8ff2669079b9.png)

**Comment by vinsworldcom** [comment]
@donho 

In NOT dark mode, the highlight looks better, but the text inverts - that is to say goes from white to black and on a dark background with a now darker highlight, it's almost unreadable:

![image](https://user-images.githubusercontent.com/9657169/123099867-946a1200-d400-11eb-9a72-8d887ec523b6.png)

When editing and the highlight is not visible in function list, it basically is unreadable:

![image](https://user-images.githubusercontent.com/9657169/123100008-b8c5ee80-d400-11eb-9355-7585d7049ecc.png)

Maybe keep the old way in NOT dark mode, and use the new way in dark mode?

Cheers.

**Comment by donho** [comment]
@vinsworldcom 
My reply: https://github.com/notepad-plus-plus/notepad-plus-plus/commit/c8be679cde9936c94782d6b02e6dae32cee9b9f8#commitcomment-52558680
