### ISSUE TITLE
Function List Pane: Missing Fluent UI Icons

### ISSUE THREAD

**Issue by WildByDesign** [notepad-plus-plus/notepad-plus-plus#10066]
### Description of the Issue
With the recent addition of Dark Mode to Npp and also recent commits in last day or so adding Dark Mode support to Function List pane has made it clear that there are some missing Fluent UI icons there.

I noticed that the Function List utilizes the older style BMP icons which uses the corner pixel trick to achieve transparency. I have tried multiple attempts to create some Fluent UI icons for Function List over the past few days with no success.

Here are my most recent failed attempts:
![NppFluentIcons-FunctionList](https://user-images.githubusercontent.com/26308319/123283579-8936e500-d4d9-11eb-99a5-6c8371586346.png)

Something seems to be going wrong with that whole corner pixel transparency trick causing this and I have tried a bunch of different icons with no success.

- Would it be possible to somehow program the Function List so that it utilizes the already existing ICO format Fluent UI set?

I believe the only icon missing from the set that we would need is a Reload icon in the Function List. I can add the icon once the coding is in place to allow ICO.

**Comment by ozone10** [comment]
Not only function panel but also folder as workplace.

**Comment by ozone10** [comment]
also docking tab icons need some update
![image](https://user-images.githubusercontent.com/55940305/123435181-cfb14000-d5bc-11eb-86e9-dedd88fc0f85.png)

**Comment by WildByDesign** [comment]
@ozone10  Thank you for pointing out the missing icons. I had no idea about many of them. So I am working on the docking tab icons right now and ran into a problem. The docking tab icons utilize ICO format which is great, however, the docking tabs don't seem to allow the transparency of the ICO format.

![NppFluentIcons-DockTabIcons](https://user-images.githubusercontent.com/26308319/123458883-8c9e9f00-d5b3-11eb-8612-8109ee098624.png)

I thought at first that it might be related just to recent Dark Mode code. However, I tested these new icons plus the original docking tab icons all within Light Mode and they also fail to show transparency there as well.

This lack of transparency will be problematic from a visual perspective. Especially in future commits with additional color themes and such. 

Do you or @donho know how to bring transparency to the docking tabs?

**Comment by ozone10** [comment]
Add ` | ILC_MASK` to 
https://github.com/notepad-plus-plus/notepad-plus-plus/blob/034666894f022c55182b5fd3f91e46a5d434439c/PowerEditor/src/WinControls/DockingWnd/DockingManager.cpp#L563
so it will look like this
`_hImageList = ::ImageList_Create(iconDpiDynamicalSize, iconDpiDynamicalSize, ILC_COLOR8 | ILC_MASK, 0, 0);`

**Comment by WildByDesign** [comment]
@ozone10 Thank you for that fix. I just compiled my binary with that fix and it works great. Now I am excited to get back into completing those docking tab icons. I should be able to have them all complete tonight. It looks great now with your fix.

By the way, I am not a programmer and therefore I don't understand much coding at all. I am also not entirely sure still how to do pull requests and such. Could you please put in a pull request with that fix?

And I will get to work on the docking tab icons right away. I've got most of them complete already until I noticed that problem. Thanks again.

**Comment by ozone10** [comment]
@WildByDesign 
This is small change so I would wait for those icons.
After you've done them you better ask @donho, I will be away from friday at least for next two weeks.

This also need some implementation for switching between icons.

**Comment by WildByDesign** [comment]
Ok sounds great. I have completed the docking tab icons. However, the problem remains for the BMP icons on the top of the Function List and Project Panel panes.

I think this old commit from @donho  may be the source of the remaining BMP issue:
https://github.com/notepad-plus-plus/notepad-plus-plus/commit/b139d878e00c1c6121e969b89846977dbb8dc0cf

That is setting a colour mask value of rgb 192 192 192. That might explain why any and all of the dark mode BMP icons that I have tried to create for Function List and Project Panel have all ended up rendering all garbled up like in my first post of this issue.

I have zero programming experience and therefore I don’t understand much other than the code is masking icon background to a dull light grey colour.

**Comment by ozone10** [comment]
nope this is for treeview, not toolbar icons

**Comment by WildByDesign** [comment]
> Here are my most recent failed attempts:
> ![NppFluentIcons-FunctionList](https://user-images.githubusercontent.com/26308319/123283579-8936e500-d4d9-11eb-99a5-6c8371586346.png)
I had one outstanding issue (above) where the BMP icons for the Function List and Project Panel toolbar panes were rendering all glitchy regardless of the dozens of attempts with various BMP settings.

I finally have figured this out. The main Npp toolbar also has a set of BMP icons as an option, however, they do not have this issue. The toolbars for Function List and Project Panel panes seem to only allow for a lower specification of colours for BMP.

So I can work around this issue by forcing the colours to less than 256 and this works in my testing. Since the icons only contain 1 or 2 colours, this will have no visible difference anyways. Now I can finish all of the missing Fluent UI icons for docking icons and panel toolbars.

**Comment by ozone10** [comment]
This is because how BMP is loaded. It should be possible to make it work with almost any type of BMP icons.

**Comment by WildByDesign** [comment]
@donho @ozone10 @chcg I have made a lot of progress recently and I am very close to being able to have these Function List, Project Panel, and docking tab icons ship in a release. But I would like some feedback and opinions if possible, please.

It took me forever because I had to manually create the Expand Folders and Collapse Folders icons in the Folder as a Workspace panel and ensure that they came out sharp. I was stuck on those two icons for weeks.

Current:
![NppFluentIcons-Panels-Docking](https://user-images.githubusercontent.com/26308319/125479671-4c3564b2-c227-43f5-acfc-746ad04238b2.png)

I tried to use icons which would be relatively neutral whether the user is using the Fluent UI Regular icons or the Filled set because I don't know if you guys want to go through the effort in coding to have both Fluent UI sets on these panels and docking tabs. But if you guys want  both sets if icons, I am prepared to do so. It's up to you.

- Do we want to have both Fluent UI icon sets (Regular and Filled) in Panels and docking tabs?

- **Opinion Question:** Regarding the Folder as a Workspace icon (top right in screenshot). I have been considering changing that icon to a plain Folder icon like in the original Notepad++ set, and then use that Desktop-like icon as the icon for the Project Panels. I am having a hard time finding a nice icons to represent the Project Panels and that icon seems like it might be a better look there. I would have to change that icon on the main toolbar and the matching docking tab icon. I would really like some opinions/feedback on this because this is the final thing right now holding me back from releasing these latest icons.

But on the other hand, that icon does look nice for Folder as a Workspace as well. So I am really stuck on this. Maybe we can keep it as it is, and simply find a better icon for the Project Panels. I'm just not happy with the Project Panels icon at the moment. So let me know what you guys think. Thank you.

**Comment by WildByDesign** [comment]
@ozone10 
> so it will look like this
> `_hImageList = ::ImageList_Create(iconDpiDynamicalSize, iconDpiDynamicalSize, ILC_COLOR8 | ILC_MASK, 0, 0);`

You figured out this fix regarding transparency of BMP icons on the docking tabs.

There is one last place where BMP icons are lacking the transparency functionality (Tab Close button):

![NppFluentIcons-TabClose](https://user-images.githubusercontent.com/26308319/126051151-ac0e3bfb-4f49-4382-9530-0d2a8cead5a3.png)

Is there a similar trick that would bring the transparency functionality to the BMP icons used for the Tab Close button?

Please keep in mind that I am not a programmer. Also, I wasn't sure if it was even worthy of a bug report.

**Comment by donho** [comment]
@WildByDesign 
Sorry for the late reply.

> I tried to use icons which would be relatively neutral whether the user is using the Fluent UI Regular icons or the Filled set because I don't know if you guys want to go through the effort in coding to have both Fluent UI sets on these panels and docking tabs. But if you guys want both sets if icons, I am prepared to do so. It's up to you.

I would said - since they look really awesome - they can replace the current ones as the default icons in light mode. And of course, we need also the icons in black mode.

**Comment by WildByDesign** [comment]
@donho Sorry for the delay on these latest update of missing icons. I have finally completed dark and light versions of the missing icons that I have been working on for several weeks now. I will provide a download archive below so that you can add the new icons because there will need to be some coding involved to switch between light mode and dark mode similar to the main toolbar icons already do.

Download: 
[FluentUI-update-2021-07-24.zip](https://github.com/notepad-plus-plus/notepad-plus-plus/files/6873313/FluentUI-update-2021-07-24.zip)


### Updated Fluent UI Icons:

![FluentUI-DockTabs](https://user-images.githubusercontent.com/26308319/126886107-fed16d95-5533-48cb-8a30-a07937a1ce5d.png)

![FluentUI-DocSwitcher](https://user-images.githubusercontent.com/26308319/126886165-65108b8b-e7fa-4052-b30b-487709d9751d.png)![FluentUI-DocSwitcher-filled](https://user-images.githubusercontent.com/26308319/126886166-cc33d203-bfea-4347-9bed-1ce3d31db1fb.png)

* updated top bar icons for Folder as Workspace and Function List panes
* updated all docking tab icons
* updated Doc Switcher / Document List icons

@Ashfaaq18 Are you OK with these updated Document List icons? I created an SVG icon for Doc Switcher docking tab icon about a week ago and shortly after you provided an awesome commit for bringing the Document List to the main toolbar as well. Great work. My assumption is that the Doc Switcher as we knew it is gone and is now renamed to Document List.

### Missing Fluent UI Icons:

![FluentUI-missing](https://user-images.githubusercontent.com/26308319/126886318-46ea7cac-00c0-4079-a392-84c9a1b90c8b.png)

* still need to update icons within Function List pane but having BMP transparency issues
* still some miscellaneous icons missing (example, Workspace icon on Project Panel pane)

It will likely take me a week or more to complete the missing icons. The BMP transparency issues within the panes have been causing me problems. 

Please @donho continue with merging the icons that I have provided today because I do not want to delay this any longer for a few more missing icons. Also, I am very tired now and need to take a break for a few days. Cheers! And thank you.

**Comment by Ashfaaq18** [comment]
hey @WildByDesign, these icons look great. And yeah, now 'Doc switcher' is no more, its renamed to 'Document List'. 
I created my icons as a temporary holder until someone else comes up with a better implementation. So yeah, can go ahead and replace it :)
