### ISSUE TITLE
[DarkMode] Splitter background – opinion

### ISSUE THREAD

**Issue by ozone10** [notepad-plus-plus/notepad-plus-plus#10069]
Question, this is more about aesthetic. What do you like more?

Currently splitter have lighter color and middle one doesn't have "dots".
![image](https://user-images.githubusercontent.com/55940305/123295156-f7dd6800-d504-11eb-87d0-16e5e1f2bdbb.png)

These splitter have same color as main GUI and "dots" are restored.
![image](https://user-images.githubusercontent.com/55940305/123294353-4a6a5480-d504-11eb-9074-7cd897634e29.png)

btw, ignore that document map has border and different colors.

**Comment by mere-human** [comment]
For me, 2nd looks better. 1st has the same color as the tab so it's harder to distinguish it.

**Comment by donho** [comment]
> For me, 2nd looks better. 1st has the same color as the tab so it's harder to distinguish it.

+1
