### ISSUE TITLE
Feature request: Option to close npp after closing the last tab

### ISSUE THREAD

**Issue by nlwillia** [notepad-plus-plus/notepad-plus-plus#1006]
Currently, when you close the last tab in notepad++, the editor stays open with a new, unsaved buffer.  In most cases, I would prefer that npp exit instead of remaining open.  This doesn't have to be the default; I'm sure the current behavior is preferable to many, but it would be nice to be able to set it as an option.

**Comment by wanderseeme** [comment]
Yeah this feature is badly needed!

**Comment by arieljannai** [comment]
yeah!

**Comment by dail8859** [comment]
I agree this would be nice. (I know at least Firefox does this and would assume most other browsers too.)
