### ISSUE TITLE
Style Configurator

### ISSUE THREAD

**Issue by AEA2002** [notepad-plus-plus/notepad-plus-plus#10072]
### Steps to Reproduce the Issue

1. click settings on menu bar
2. click Style Configurator 
3. click HTML under language column
4. change foreground color

### Expected Behavior

Color of HTML tags to change
### Actual Behavior

Color of CSS changed
### Debug Information

Notepad++ v8.1   (32-bit)
Build time : Jun 17 2021 - 01:52:11
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 10 Home (64-bit) 
OS Version : 2004
OS Build : 19041.1052
Current ANSI codepage : 1252
Plugins : mimeTools.dll NppConverter.dll NppExport.dll

**Comment by sasumner** [comment]
Suggest some screenshots showing the effects you are describing.
Not everyone is an HTML / CSS expert.

**Comment by Docteh** [comment]
I'm not able to reproduce on 8.1.4
Before (bespin theme)
![image](https://user-images.githubusercontent.com/190571/134797466-e9e46a35-48ce-48b8-aec4-abf8aa557765.png)
Change DEFAULT to white
![image](https://user-images.githubusercontent.com/190571/134797454-b96cac76-e93e-48ad-82f8-8a8b3b407570.png)
Changed TAG's foreground color to yellow, works tags are changed
![image](https://user-images.githubusercontent.com/190571/134797501-c5655421-a7da-4247-bfa3-063beac4235a.png)
