### ISSUE TITLE
Update Notepad++ option doesn't work in v8

### ISSUE THREAD

**Issue by ranjan-2209** [notepad-plus-plus/notepad-plus-plus#10073]
Update Notepad++ option doesn't work in v8
![image](https://user-images.githubusercontent.com/16834561/123504494-575b8500-d677-11eb-94de-e12cb2138ef5.png)

The latest version available is 8.1, but I get this popup when clicked on Update Notepad++
![image](https://user-images.githubusercontent.com/16834561/123504504-65110a80-d677-11eb-8494-6420ca75847d.png)

Also, I am not able capture the update traffic in Fiddler

**Comment by mere-human** [comment]
Hi @ranjan-2209,
This is expected behavior. Please, read this:
https://npp-user-manual.org/docs/upgrading/
> In order to avoid to spread a new version witch contains regression or critical bugs, we wait always for users’ feedback during one week,

This "waiting period" might be extended until all critical problems are fixed.

This issue can be closed.

**Comment by sasumner** [comment]
>Also, I am not able capture the update traffic in Fiddler

Not sure what that means, but I don't think it is a problem.

Closing per the suggestion to do so.

**Comment by ranjan-2209** [comment]
@sasumner https://en.wikipedia.org/wiki/Fiddler_(software)

**Comment by ValZapod** [comment]
> @sasumner https://en.wikipedia.org/wiki/Fiddler_(software)

I suppose the update is using https? Then without sym. keys you will not be able to decode the update.

**Comment by ranjan-2209** [comment]
@ValZapod We can even decode https using Fiddler
