### ISSUE TITLE
Fluent UI Icons Update: Fix some inconsistencies

### ISSUE THREAD

**Issue by WildByDesign** [notepad-plus-plus/notepad-plus-plus#10075]
It took me a month or two to learn how to better manipulate SVG images prior to exporting as ICO or BMP. There were (and still are) some icons that need some inconsistencies fixed.

32px Before:

![NppFluentIcons-32px-before-2021-06-26](https://user-images.githubusercontent.com/26308319/123522148-8844b580-d689-11eb-8cc3-d77cced2052e.png)

32px After:

![NppFluentIcons-32px-after-2021-06-26](https://user-images.githubusercontent.com/26308319/123522158-985c9500-d689-11eb-8486-76e86fbbc39b.png)

16px Before:

![NppFluentIcons-16px-before-2021-06-26](https://user-images.githubusercontent.com/26308319/123522121-5af80780-d689-11eb-89fd-0ac051096399.png)

16px After:

![NppFluentIcons-16px-after-2021-06-26](https://user-images.githubusercontent.com/26308319/123522133-74994f00-d689-11eb-8b1c-62ebed4de050.png)

I targeted this stretch of icons in the middle of the toolbar because some of these icons were not sharp enough before and had inconsistencies that bothered me for a while. I completed Dark Mode and Light Mode icons. The icons look sharp in Light Mode as well.

There are more icons that I plan updating soon as well. But I am going to tackle the missing docking tab icons and other missing icons first and then come back to the toolbar.

Download archive which contains only the updated icons in both Dark and Light Mode and in their respective directories with matching file names to merge with current icon set:

[FluentUI-update-2021-06-26.zip](https://github.com/notepad-plus-plus/notepad-plus-plus/files/6720527/FluentUI-update-2021-06-26.zip)

@donho  Can you please help me with merging these updated icons?

Thank you. I don't feel incredibly confident with pull requests yet.

**Comment by donho** [comment]
@WildByDesign 
Thank you. I like new Find replace button.

**Comment by WildByDesign** [comment]
You’re welcome. And thank you for pushing this change through. I had difficulties with that Replace button for months and I am finally happy with the quality and design of how it turned out.
