### ISSUE TITLE
can't style more than 2047 characters in single attempt

### ISSUE THREAD

**Issue by shachtal** [notepad-plus-plus/notepad-plus-plus#10089]
### Description of the Issue

when attempting to select more than 2047 characters, then style (rightclick on selected text>style token >Using #n style), it will only style the first 2047 characters
### Steps to Reproduce the Issue

1. open a regular text document containing many lines and characters
2. select more than 2047 characters
3. style the text, (rightclick on selected text>style token >Using #n style)

### Expected Behavior

i would expect all the selected characters to be styled according to selected style
### Actual Behavior

only the first 2047 characters are styled
### Debug Information

Notepad++ v7.9.2   (64-bit)
Build time : Dec 31 2020 - 04:01:34
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS Name : Windows 10 Pro (64-bit) 
OS Version : 2004
OS Build : 19041.1052
Current ANSI codepage : 1255
Plugins : mimeTools.dll NppConverter.dll NppExport.dll NPPJSONViewer.dll

**Comment by sasumner** [comment]
This is governed by the following in the code:

https://github.com/notepad-plus-plus/notepad-plus-plus/blob/f65f00c63f377cfbcaf8c06f582438438f88285d/PowerEditor/src/ScintillaComponent/FindReplaceDlg.h#L30

In the past, requests for increasing this size have been declined, so I will close this issue.
If @donho indicates that we now find increasing this limit acceptable, we can reopen.

**Comment by donho** [comment]
Let's keep this limit.

**Comment by sasumner** [comment]
Just a (unicode) note to say that the limit is a _byte_ limit and not a _character_ limit.
So, as a somewhat wild example, if one had a UTF-8 encoded file where all characters in a string to be searched for (or styled) were 4-bytes (a dubious prospect, but...), then the limit would be approximately 511 characters.
