### ISSUE TITLE
Installing Notepad++ from non-Admin account fails to install Themes

### ISSUE THREAD

**Issue by Stanley-G** [notepad-plus-plus/notepad-plus-plus#10081]
### Description of the Issue
Additional themes are not accessible to other users.

### Steps to Reproduce the Issue

1. On a Windows machine, log in to a non-admin user account.
2. Launch notepad++ installer.
3. When prompted by UAC, provide the credentials for an admin account.
4. Proceed with the installation.
5. Launch Notepad++
6. Attempt to switch to a non-default theme. (`Settings->Style Configurator`)

### Expected Behavior

Additional themes would be available to select.

### Actual Behavior
The `Default Style` theme was the only theme available.

NOTE: If you launch Notepad++ *as Administrator*, all the themes are available again. But the next time you launch the program with default permissions, the local user account `AppData` folder is used, which does not have the `themes` folder installed.

### Debug Information
Notepad++ v8.1   (64-bit)
Build time : Jun 17 2021 - 01:56:07
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 10 Pro (64-bit) 
OS Version : 2009
OS Build : 19043.1052
Current ANSI codepage : 1252
Plugins : mimeTools.dll NppConverter.dll NppExport.dll

**Comment by MarkusBodensee** [comment]
This issue is most likely fixed with 3347044595cae60c658ed39e4f2e1ea913eb66e2 and thus is part of next release v8.1.1.

So I think this issue can be closed.

**Comment by MarkusBodensee** [comment]
@sasumner :-)
