### ISSUE TITLE
multi line editing control text in Italian translation

### ISSUE THREAD

**Issue by Trip20** [notepad-plus-plus/notepad-plus-plus#10085]
### Description of the Issue
Hello everyone, I would kindly like to draw attention to the incorrect and non-exhaustive Italian translation used for the checkbox that refers to the enabling of the multiline mode discussed in 3d https://community.notepad-plus-plus.org/topic/21409/multi-line-editing/5

### Steps to Reproduce the Issue

I would suggest adding a function specification item regarding the "enable (Ctrl + CLICK / SELECTION)" checkbox in Configuration >> Preferences >> Display

### Expected Behavior
![cornice](https://user-images.githubusercontent.com/59014838/123870235-56a24780-d932-11eb-9e80-28dc0e7fd99d.png)

### Actual Behavior
![multilinea](https://user-images.githubusercontent.com/59014838/123869462-52295f00-d931-11eb-8c73-df432d480c23.jpg)

### Debug Information
Notepad++ v7.9.5   (64-bit)
Build time : Mar 21 2021 - 02:13:17
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS Name : Windows 7 Ultimate (64-bit) 
OS Build : 7601.0
Current ANSI codepage : 1252
Plugins : ComparePlugin.dll mimeTools.dll NppConverter.dll NppExport.dll PythonScript.dll

**Comment by sasumner** [comment]
@Trip20 

In the Community postings, you were asked to supply a suggestion for the text -- you neglected to do so. :-(

Looking at the Italian for 7.9.1 (the most-recent version to have _Multi-Editing Settings_ in a groupbox), we see:

![image](https://user-images.githubusercontent.com/30118311/123958368-f8e61d80-d97a-11eb-81b8-8c528b9dc426.png)

So a suggestion here would be to change the non-groupboxed text for this control to:

`Abilita Selezione Multipla (Ctrl+clic/selezione)`

A concern is, is this text too long to fit?

Or maybe there is a better translation for "Enable  Multi-Editing".
But an Italian speaker would have to supply this; not sure what the reluctance on the part of @Trip20 is to actually do this.

**Comment by Trip20** [comment]
hi sasumner, no reluctance on my part to do this!
In the "Expected Behavior" I have reported the picture of how it could be displayed.
The problem is that I followed the translation of my thought: in the image I translated it too and I have not reported it in Italian. I am fused!
However possible replacement items: " Abilita modifica multilinea <Ctrl+ Click>", "abilita multilinea <Ctrl+ Click>",o "abilita selezione multilinea <Ctrl+ Click>".
I do not think that the above texts can be longer than the already existing items.

**Comment by sasumner** [comment]
>In the "Expected Behavior" I have reported the picture of how it could be displayed.

It cannot be displayed that way because that way has a huge groupbox around the checkbox, and that isn't the way it is done any longer.

**Comment by Trip20** [comment]
it was an idea!
alternative: just modify the checkbox with one of the items above

**Comment by sasumner** [comment]
@conky77 seems to be a frequent maintainer of the Italian translation.  @conky do you have an opinion on what is the best text for this?

**Comment by conky77** [comment]
There are many other languages with the same bug (i.e. Spanish (all), Catalan, Furlan, etc )

I created a PullRequest for Italian


![image](https://user-images.githubusercontent.com/59116246/124182759-98a8c600-dab7-11eb-9e84-f466c887fae7.png)


and another one for Venetian 

![image](https://user-images.githubusercontent.com/59116246/124183741-f38eed00-dab8-11eb-965a-3987cfad100a.png)


@sasumner   How to fix the other languages?

**Comment by sasumner** [comment]
>There are many other languages with the same bug (i.e. Spanish (all), Catalan, Furlan, etc )
>How to fix the other languages?

I suppose we let there translators "fix" them, as needed.

The text for this control, in English used to be:  `Enable (Ctrl+Mouse click/selection)`
Unfortunately, this makes sense without specifically adding `Multi-Editing` after "Enable".
So...some translators probably thought no change was needed.
However, because the feature is called "Multi-Editing", a change IS needed.

**Comment by Trip20** [comment]
thanks conky77. but you are Venetian?

**Comment by conky77** [comment]
> thanks conky77. but you are Venetian?

@Trip20   yes, I'm Venetian (from Veneto region of Italy)
