### ISSUE TITLE
Freeze/crash when opening files that contain certain text string

### ISSUE THREAD

**Issue by Rinakles** [notepad-plus-plus/notepad-plus-plus#10098]
### Description of the Issue
Notepad++ v8.1 crashes on Windows when opening files that end in string `To be continued...`

### Steps to Reproduce the Issue
1. Open any .txt file that contains `To be continued...` on the last row.
2. Notepad++ freezes and stays frozen. The only option is to kill process and restart.

### Debug Information
Notepad++ v8.1   (64-bit)
Build time : Jun 17 2021 - 01:56:07
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : 
Admin mode : ON
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 10 Pro (64-bit) 
OS Version : 2009
OS Build : 19042.985
Current ANSI codepage : 1252
Plugins : ComparePlugin.dll mimeTools.dll NppConverter.dll NppExport.dll

**Comment by sasumner** [comment]
>Notepad++ v8.1 crashes on Windows when opening files that end in string `To be continued...`

Not for me.

**Comment by Rinakles** [comment]
Well, it crashes for me. Just because it doesn't happen to you, doesn't mean that it's not a bug.
And it's bloody annoying because I'm currently in process of editing 1000+ short stories, many of which end in that sentence.

**Comment by sasumner** [comment]
Well, if you want to post a file where it crashes for you, I can try your exact scenario.
Of course I tried making a file with `To be continued...` at its end, and it didn't crash when opening.
Such are the nature of these types of problems; it if can't be reproduced, it can't be fixed.

**Comment by Rinakles** [comment]
I have a long history of beta testing and programming, so don't give me that kind of nonsense about what 'can be fixed'.

I already told you how to reproduce it, in the first post. Even just opening a file that contains nothing but `To be continued...` causes Notepad++ to instantly freeze. Though on further testing, this does not happen on my main drive, only on secondary ones. And just 'To be' is enough. Curious.
https://user-images.githubusercontent.com/86843995/124704536-ea5cb080-defc-11eb-9a0c-feb84ec834b7.mp4

**Comment by mere-human** [comment]
@Rinakles Could you please attach the file here?
Also I have noticed you were running Notepad++ in admin mode. Can you try in non-admin mode?

**Comment by Rinakles** [comment]
No difference without admin mode.
[freeze.txt](https://github.com/notepad-plus-plus/notepad-plus-plus/files/6774642/freeze.txt)

**Comment by mere-human** [comment]
I don't see a crash with this file either.
I'm suspecting the auto-completion might be involved. Try changing/disabling it in preferences:
![image](https://user-images.githubusercontent.com/9664141/124708395-e338a100-df02-11eb-8a76-b07974dcc74a.png)

Also, you might try to reproduce the same scenario using a portable Notepad++ version.
Then we could know whether it's installation issue or an issue on your local machine.

**Comment by Rinakles** [comment]
Thanks, but it's not auto-competition either. Nor plugins, already tried without those.
Here's a debug log:
[freeze.txt](https://github.com/notepad-plus-plus/notepad-plus-plus/files/6775876/freeze.txt)
I'm not too good at interpreting those, but it seems to get stuck waiting for something...?

**Comment by Rinakles** [comment]
Ooh, I got it! This stops happening if I disable my customized Language, which I've been using for cleaning story data.
And I have this in the styler mode prefix: **[ "To be "**
Something about that makes it freeze.

**Comment by mere-human** [comment]
> Ooh, I got it! This stops happening if I disable my customized Language, which I've been using for cleaning story data.

Care to share the language file? Because, there is no symbols in the stack-trace you provided before. So it's hard to understand the problem.

**Comment by Rinakles** [comment]
Can't share the whole while, but here's the relevant settings I used: 
![language](https://user-images.githubusercontent.com/86843995/124744206-30c70500-df27-11eb-906f-048a357c77ac.jpg)
Removing the `"To be "` stopped the freezes.

**Comment by sasumner** [comment]
>I have a long history of beta testing and programming, so don't give me that kind of nonsense about what 'can be fixed'.

Sheesh.

>I already told you how to reproduce it, in the first post.

Clearly you left some information out.
