### ISSUE TITLE
[Feature Request] Implement search tabs feature

### ISSUE THREAD

**Issue by towijo** [notepad-plus-plus/notepad-plus-plus#10090]
### Description of the Issue
When a large amount of tabs are opened in Notepad++ it is very time consuming to scroll through all the tabs in order to find the one you are looking for.

### Steps to Reproduce the Issue
1. Open a large amount of documents/tabs (ex. 200+).
2. Try to locate one of them.

### Expected Behavior
To be able to use a "Search Tabs" feature (like the one available in latest Chrome) that presents an "search-as-you-type" style input-box and presents the found tabs in a list. When you found your tab you click on it and then the tab is shown to you.

### Actual Behavior
Use the left-right arrows that is available to the right of all tabs. Scroll through hundreds of tabs and hopefully find your tab before your eyes gets blurry.

**Comment by mere-human** [comment]
Take a look at _Menu > Window > Windows..._
This may help you a bit.
![image](https://user-images.githubusercontent.com/9664141/124090161-3d49ea00-da5d-11eb-86e0-bce94366061c.png)

**Comment by ArkadiuszMichalski** [comment]
You can try [nppNavigateTo](https://github.com/young-developer/nppNavigateTo/) plugin.

**Comment by sasumner** [comment]
>where you can start typing and the list of windows would filter accordingly

That is totally the NavigateTo plugin.

**Comment by towijo** [comment]
Exactly what i needed! Thanks for quick feedback and this issue can be closed. NavigateTo saved my life.
