### ISSUE TITLE
Is more than two split window/view

### ISSUE THREAD

**Issue by GuillaumeTransacts** [notepad-plus-plus/notepad-plus-plus#10107]
### Description of the Issue
This is a feature request. If possible I would like to be able to have more that two view in Notepad++, similar to emacs "Splitting window" feature. 
![example](https://user-images.githubusercontent.com/86652435/124480883-03078200-dda8-11eb-9c94-47f5b49852d6.PNG)

https://www.gnu.org/software/emacs/manual/html_node/emacs/Split-Window.html

**Comment by sasumner** [comment]
I don't think we're going to see more than 2 in Notepad++, sorry.
