### ISSUE TITLE
Style token feature seems to be broken

### ISSUE THREAD

**Issue by FerhatAkgun** [notepad-plus-plus/notepad-plus-plus#10109]
### Description of the Issue
When selecting only the part "ABC_" of one of these lines and choosing style token, all occurrences were marked in the past versions. The current version doesn't event mark a single occurrence. Not even the currently selected one.

> ABC_DEF	Hello World1
> ABC_DEF	Hello World2
> ABC_DEF	Hello World3
> ABC_DEF	Hello World4

### Steps to Reproduce the Issue
1.  Mark with curser "ABC_"
2.  Right click and choose style token

### Expected Behavior
All occurrences should be marked

### Actual Behavior
Nothing is marked at all

### Debug Information
Notepad++ v8.1.1   (64-bit)
Build time : Jul  1 2021 - 14:10:53
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 10 Enterprise (64-bit) 
OS Version : 1909
OS Build : 18363.1621
Current ANSI codepage : 1252
Plugins : mimeTools.dll NppConverter.dll NppExport.dll XMLTools.dll

**Comment by sasumner** [comment]
The way this works has been changed.  See _Preferences_ > _Highlighting_ > _Mark All_ group to set up for your need.
