### ISSUE TITLE
Windows exit window unexpected behavior 

### ISSUE THREAD

**Issue by Gibson-Ayden** [notepad-plus-plus/notepad-plus-plus#10116]
### Description of the Issue
When clicking the exit button on a secondary monitor and hitting it in the top left corner, the application does not close, but instead any window behind it is clicked instead, which can lead to closing a window open behind it 

### Steps to Reproduce the Issue

1.  open n++ in a secondary monitor will a maximized window
2. attempt to close the window by clicking as far to the top left as possible 
3. 

### Expected Behavior
n++ closes

### Actual Behavior
mouse interacts with the window behind it

### Debug Information
Notepad++ v8.1   (32-bit)
Build time : Jun 17 2021 - 01:52:11
Path : D:\Program Files (x86)\Notepad++\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 10 Enterprise (64-bit) 
OS Version : 2009
OS Build : 19043.1052
Current ANSI codepage : 1252
Plugins : mimeTools.dll NppConverter.dll NppExport.dll

**Comment by sasumner** [comment]
This is in the same "family" as https://github.com/notepad-plus-plus/notepad-plus-plus/issues/8660 so closing
