### ISSUE TITLE
"Remember last used directory" unexpected behaviour

### ISSUE THREAD

**Issue by donho** [notepad-plus-plus/notepad-plus-plus#10115]
### Description of the Issue
"Remember last used directory" unexpected behaviour:
This option doesn't only remember last **used** directory, but also remember last **browsed** directory.

### Steps to Reproduce the Issue

1. Save a file in `c:\youAreTheChosenOne\`
2. Switch to another file, choose "Save as..." command
3. Save as dialog appear with `c:\youAreTheChosenOne\`, which is good.
4. Browse to another directory `c:\tmp\` in dialog, then click Cancel
5. Switch to another file, choose "Save as..." command

### Expected Behavior

`c:\youAreTheChosenOne\` should be always the last used directory in the dialog.

### Actual Behavior

`c:\tmp\` becomes the last used directory in the dialog, even it's browsed but the file not saved in.

### Debug Information
Notepad++ v8.1.1   (32-bit)
Build time : Jul  5 2021 - 02:45:12
Path : C:\xxxxxxxx\notepad-plus-plus\PowerEditor\bin\notepad++.exe
Command Line : -udl=regexGlobalTest .\udl-regexGlobalTest\unitTest
Admin mode : ON
Local Conf mode : ON
Cloud Config : OFF
OS Name : Windows 10 Home (64-bit) 
OS Version : 2009
OS Build : 19042.1052
Current ANSI codepage : 1252
Plugins : none

**Comment by donho** [comment]
@mere-human 
Can I assign this issue to you?

**Comment by mere-human** [comment]
@donho Sure, assign it to me.
There is a fix already https://github.com/notepad-plus-plus/notepad-plus-plus/pull/10100/commits/7c1ddd00421f07e34959e83ee6856f98f5be6a7d
in this PR #10100
