### ISSUE TITLE
Appveyor build issue with Vcpkg

### ISSUE THREAD

**Issue by ozone10** [notepad-plus-plus/notepad-plus-plus#10114]
I have noticed this
```
Vcpkg is unable to link because we cannot decide between Release and Debug libraries. Please define the property VcpkgConfiguration to be 'Release' or 'Debug'
```
https://ci.appveyor.com/project/donho/notepad-plus-plus/builds/39878689/job/s2667yupokml43gx#L38
https://ci.appveyor.com/project/donho/notepad-plus-plus/builds/39878689/job/s2667yupokml43gx#L524

**Comment by chcg** [comment]
See e.g. https://github.com/appveyor/ci/issues/3549 and https://github.com/microsoft/vcpkg/issues/2790, seems to be an issue of the vcpkg tool.

**Comment by ozone10** [comment]
Hmm it seems appveyor attempt to fix it made builds slower. 

Anyway should Notepad++ drop "Unicode" part?

**Comment by mere-human** [comment]
> Hmm it seems appveyor attempt to fix it made builds slower.
> 
> Anyway should Notepad++ drop "Unicode" part?

I agree, that would be very nice.

**Comment by mere-human** [comment]
@donho Is it OK to rename `Unicode Debug` → `Debug `and `Unicode Release` → `Release`? 
Since Notepad++ isn't shipped in non-Unicode version anyway.

**Comment by donho** [comment]
Why not?
But why do we need Vcpkg?

**Comment by mere-human** [comment]
> But why do we need Vcpkg?

Probably, it's some MSBuild/Visual Studio internals that rely on vcpkg hence is the warning.


I actually ran `vcpkg integrate remove` as it was suggested here: https://github.com/microsoft/vcpkg/issues/2790
For that, I needed to install vcpkg first.
And after that, the warning had magically disappeared.

**Comment by mere-human** [comment]
I was planning to do something it after https://github.com/notepad-plus-plus/notepad-plus-plus/pull/10180 gets merged in (or rejected).
So that there are less merge conflicts.
