### ISSUE TITLE
Feature Request: Get file paths from all open tabs

### ISSUE THREAD

**Issue by mere-human** [notepad-plus-plus/notepad-plus-plus#10123]
### Description of the Issue

I want have an ability to copy paths of all opened documents.
This was discussed on a community forum: 
https://community.notepad-plus-plus.org/topic/21447/how-to-get-file-paths-from-all-open-tabs
There are other suggestion there. Please, see my suggestion below.

### Actual Behavior
This copies file path only for current document:
Edit > Copy to Clipboard > Current Full File path to Clipboard

### Expected Behavior

Add a way to copy the file path for all opened document.

**Suggestion:**
Make the text from Window > Windows copyable.
It already supports multi-select. The only thing missing is Ctrl+C and put a list of of file paths to clipboard.
![image](https://user-images.githubusercontent.com/9664141/124974379-64905080-e035-11eb-9eb0-e26e73b88106.png)

### Debug Information

Notepad++ v8   (64-bit)
Build time : May 27 2021 - 22:10:00
Path : C:\Program Files\npp-portable\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 10 Enterprise (64-bit) 
OS Version : 2009
OS Build : 19043.1052
Current ANSI codepage : 1252
Plugins : DSpellCheck.dll HexEditor.dll MarkdownViewerPlusPlus.dll mimeTools.dll NppConverter.dll NppExport.dll NppMarkdownPanel.dll XMLTools.dll

**Comment by ArkadiuszMichalski** [comment]
@mere-human 
We don't have any separator between copied names/paths. In Search Panel, when we copied paths, separator is new line (CRLF). This is probably the most sensible in the further processing of this copy.

**Comment by ArkadiuszMichalski** [comment]
> If this is really a problem, you can create a new issue and I can change the separator to CRLF.

I don't know, in general, the CRLF combination in Windows is probably the right one, and since Notepad++ is created for Windows ... 

This Window is modal, so after copying I instinctively pasted it into Notepad, and here I got merged all in one line. Since copying from Search Panel works in any program, maybe it is worth doing the same here.

**Comment by mere-human** [comment]
@ArkadiuszMichalski What version of Notepad do you use (Help > About Notepad)?
Could you place the screenshot of how it looks?
I tried it locally, and it seems like Notepad handles the LF just fine.

![image](https://user-images.githubusercontent.com/9664141/127899778-a05447c1-5b96-412a-ba15-52e2b398b61d.png)

**Comment by ArkadiuszMichalski** [comment]
Ahh sorry, on Win7, looks like Notepad in Win10 has been improved.

**Comment by mere-human** [comment]
> Ahh sorry, on Win7, looks like Notepad in Win10 has been improved.

Anyway, I've already implemented a fix for consistency.
