### ISSUE TITLE
incorrect translation

### ISSUE THREAD

**Issue by sziner** [notepad-plus-plus/notepad-plus-plus#10120]
https://github.com/notepad-plus-plus/notepad-plus-plus/blob/541b4d1c7a6a4259240d25326d26f1e7c5184ce9/PowerEditor/installer/nativeLang/hebrew.xml#L133

in the translation of: menu->View->Distraction Free Mode
instead of "תיבת שיח הגדרת משתמש"
should come: "/מצב ללא הסחות-דעת"
or: "מצב חופשי מהפרעות"
or something like that.

**Comment by donho** [comment]
@sziner 
Fixing the error is usually less easy than pointing it out, but more efficient.
I invite you to do a PR for fixing the error.

**Comment by sziner** [comment]
It honestly would be way easier to change that single line. It's just that I'm new to Github and not sure how to do that

**Comment by thomassmith311** [comment]
I just did the PR. Here's how to do it for next time. Click the link that goes to the relevant file (in this case, https://github.com/notepad-plus-plus/notepad-plus-plus/blob/master/PowerEditor/installer/nativeLang/hebrew.xml). Then go to the top left of the displayed file and find the pencil icon:
![image](https://user-images.githubusercontent.com/19561856/125002041-0d34b500-e022-11eb-8b44-edcc263ca6eb.png)
Hit that button, then scroll down to the relevant line (in this case, line 133) and edit the line accordingly. At the bottom of the screen, find the section labeled Propose changes. Give your PR a name that describes the problem you fixed (in the short dialogue box) and attach a short description (in the large dialogue box), maybe linking to this issue. Then hit the green button labeled "Propose Changes."
On the next page there should be a button labeled "Create pull request." Click that button. Then you can press "Create pull request" on the page after as well. Then just wait until someone with write access can change the master branch.

**Comment by sziner** [comment]
Thanks a lot! I'll definitly try it next time
