### ISSUE TITLE
Style Token highlight not working properly as of V8 to V8.1.1

### ISSUE THREAD

**Issue by nioxiib** [notepad-plus-plus/notepad-plus-plus#10127]
### Description of the Issue

I am trying to highlight a certain string in a xml file. When I tried to highlight small part of the string and choose any of the style, Notepad++ didn't highlight this.
I tried re-installing and few other things but still not working. The only way to get this working is by downgrading N++ to 7.9.5

Image below shows an example of what N++ 7.9.5 can do
With N++ 8 or above for now, you need to highlight the full string selection to be able to use Style Token
![image](https://user-images.githubusercontent.com/87158270/125010447-e02be500-e0a9-11eb-9390-b4df8cb97a5f.png)

**Comment by durmusk** [comment]
Have you tried unchecking "Match whole word only"? It works for me.
![np_highlight](https://user-images.githubusercontent.com/37907088/125068699-74a04280-e0be-11eb-8b47-b4e7b566a02d.png)

**Comment by nioxiib** [comment]
Perfect, that is the one.
Is this a new setting in V8 or above? I found similar setting in 7.9.5 but seems a bit different wording.

**Comment by sasumner** [comment]
>Is this a new setting in V8 or above?

It is new in 8.0 ; see release notes for v8.0:

20. Add MarkAll Preference settings for case and word. (Fix #9751 & #5148)
