### ISSUE TITLE
Automatic indentation broken (regression in 6.8.4)

### ISSUE THREAD

**Issue by Ede123** [notepad-plus-plus/notepad-plus-plus#1012]
With Notepad++ the automatic indentation of code/brackets seems to be broken.

As an example I tried to type the following code in a file highlighted as JavaScript:
```javascript
if (true) {
    var a = 1;
}
```
While Notepad++ 6.8.3. automatically inserted the closing bracket and positioned the cursor in a new line with proper indentation in between, 6.8.4 simply creates the closing bracket and does nothing else.

Also automatic indenting of brackets is broken (e.g. if you position the cursor in front of the closing bracket in the example above and insert a line break in Notepad++ 6.8.4 the bracket will be indented in error.

**Comment by sanastasiou** [comment]
Probably caused by this: https://github.com/notepad-plus-plus/notepad-plus-plus/commit/65717312369588cbe2bfe356e912ae36645d76b3

**Comment by Ede123** [comment]
Fixed in current code, probably by 14edff689243036f6986b46f83c1fef818fa47f4

Related/Duplicate: #1038
