### ISSUE TITLE
Windows 8 support ended

### ISSUE THREAD

**Issue by ozone10** [notepad-plus-plus/notepad-plus-plus#10124]
Windows 8  is not supported anymore.
https://docs.microsoft.com/en-us/lifecycle/products/windows-8

According to [SUPPORTED_SYSTEM.md](https://github.com/notepad-plus-plus/notepad-plus-plus/blob/master/SUPPORTED_SYSTEM.md) Notepad++ on Windows 8 is still supported.

Is this right?

**Comment by mere-human** [comment]
I think it is more like we don't fix bugs that are specific to Windows 7 or Windows 8. But we don't prevent Notepad++ from launching on these OS versions.

**Comment by ozone10** [comment]
> I think it is more like we don't fix bugs that are specific to Windows 7 or Windows 8. But we don't prevent Notepad++ from launching on these OS versions.

I know but according to that MD (column supported), if there is bug in Notepad++ on Windows 8, team should fix it.

**Comment by ValZapod** [comment]
Tou are wrong. That is windows 8. Windows 8.1 support will only end in 2023.

**Comment by ozone10** [comment]
> You are wrong. That is windows 8. Windows 8.1 Extended Support will only end on January 10, 2023. https://docs.microsoft.com/en-us/lifecycle/faq/windows

![image](https://user-images.githubusercontent.com/55940305/125110630-5b09f580-e0d4-11eb-85a0-701c62958192.png)

**Comment by thomassmith311** [comment]
To quote from the md file you linked,

> The column supported contains the status of Notepad++ team supporting Notepad++ under the specific OS. It means if a bug is present under an OS no more supported but not under supported OS, then this issue won't be treated by the team.

So, I think it means that if Notepad++ has a bug on Windows 8 that does *not* occur on Windows 10, then the Notepad++ team will *not* fix it. If Notepad++ has a bug on Windows 8 that does also occur on Windows 10, then the Notepad++ team may fix it.

**Comment by donho** [comment]
@ozone10 
> Should Notepad++ drop support for Windows 8.

Done:
https://github.com/notepad-plus-plus/notepad-plus-plus/commit/8d425bd4f169180579f6e3cd921e2c9f48bae7c1

The term "support" is quite ambiguous indeed. Here's the guideline under the status `Running: yes; Support: no`:
1. If a bug found in non-supported OS, but in supported OS is not reproducible, then bug could not be fixed, except it's a critical one.
2. If an added feature doesn't work correctly only under non-supported OS, it's OK - but if a small modification can make it work correctly under non-supported OS, it'll be better.
3.  If an added feature causes crash or critical bug under non-supported OS, then added feature should be modified or reverted.

**Comment by ValZapod** [comment]
Windows 8 is still supported by Microsoft, WTF.
