### ISSUE TITLE
Dark Mode Menu Bar cluttered

### ISSUE THREAD

**Issue by joseashb** [notepad-plus-plus/notepad-plus-plus#10130]
### Description of the Issue
Menu bar becomes cluttered with dark mode

### Steps to Reproduce the Issue

1.  Settings > Preferences > Dark Mode
2.  Enable and Apply
3.  Restart Notepad++

### Expected Behavior
Everything to be as normal before restarting

### Actual Behavior
The Menubar becomes cluttered
<img width="508" alt="Screenshot 2021-07-09 102711" src="https://user-images.githubusercontent.com/47283948/125033639-a1456180-e0a0-11eb-9cd6-9cfcaf424a8f.png">

### Debug Information
Notepad++ v8.1.1   (64-bit)
Build time : Jul  1 2021 - 14:10:53
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 10 Pro (64-bit) 
OS Version : 2009
OS Build : 19042.985
Current ANSI codepage : 1252
Plugins : ComparePlugin.dll mimeTools.dll NppBplistPlugin.dll NppConverter.dll NppExport.dll NppPluginDemo.dll NppPluginTemplate.dll

**Comment by mere-human** [comment]
Can you try with plugins disabled?

**Comment by joseashb** [comment]
Also having same issue as above
Tried switching HiDPI settings also, not working.
**I found that only on HiDPI display that this happens.**

Debug Info:
Notepad++ v8.4.4   (64-bit)
Build time : Jul 15 2022 - 17:54:42
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : "C:\Program Files\Notepad++\change.log" 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 10 Pro (64-bit) 
OS Version : 21H1
OS Build : 19043.1826
Current ANSI codepage : 1252
Plugins : 
    mimeTools (2.8)
    NppConverter (4.4)
    NppExport (0.4)

**Comment by SoraHjort** [comment]
This should be reopened as it is still an issue 
![image](https://github.com/user-attachments/assets/6b194171-4906-4f6c-afcd-3dbaa25359b6)

**Comment by SoraHjort** [comment]
@donho This should be re-opened, as the issue still persists, switching to dark mode still removes the separation margins from the menu items with the current version. (Yes I disabled all plugins to verify it isn't a plugin issue)
![image](https://github.com/user-attachments/assets/fb68b455-53ee-4111-9d1b-568bc3876608)

```
Notepad++ v8.6.9   (64-bit)
Build time : Jul 12 2024 - 05:09:25
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : 
Admin mode : ON
Local Conf mode : OFF
Cloud Config : OFF
Periodic Backup : ON
OS Name : Windows 10 Pro (64-bit)
OS Version : 22H2
OS Build : 19045.4529
Current ANSI codepage : 1252
Plugins : none
```

**Comment by joseashb** [comment]
Sorry was away.

Please note that the issue is still present in the latest version and the commit [#243112d](https://github.com/notepad-plus-plus/notepad-plus-plus/commit/243112d04d5e364450aa0c84de21a2574864bc19) did fix the issue.

Thanks

**Comment by SoraHjort** [comment]
In response to the edit, I was actually just coming to mention that I found that it's present in some custom themes, but not all.
The unfortunate thing I can't simply switch to the default built in themes for windows, as my main theme makes the taskbar not run into the scrollbar as quickly. So, for me, switching out of the theme isn't a viable option.

Though interesting to hear that you found an instance where it still happens without custom themes involved.

Though I wonder if we should just make a new issue since @donho who closed it hasn't taken notice to re-open the issue. Unless we can get another maintainer to do that.
