### ISSUE TITLE
Compare plugin icons not visible

### ISSUE THREAD

**Issue by durmusk** [notepad-plus-plus/notepad-plus-plus#10131]
### Description of the Issue

Compare plugin icons on the menu bar are not visible. They are there and working, just not visible.

### Steps to Reproduce the Issue

1. Upgraded to Notepad++ v8.1.1
2. Enabled Dark Mode to try and then disabled again.
3. Compare plugin icons became invisible (not sure whether they were visible before enabling Dark Mode)

### Expected Behavior

Compare plugin icons should be visible on the menu bar.

### Actual Behavior

Compare plugin icons on the menu bar are not visible.

### Debug Information

Notepad++ v8.1.1   (64-bit)
Build time : Jul  1 2021 - 14:10:53
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line :
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 10 Pro (64-bit) 
OS Version : 2009
OS Build : 19043.1083
Current ANSI codepage : 1254
Plugins : ComparePlugin.dll mimeTools.dll NppConverter.dll NppExport.dll 

![np_bug](https://user-images.githubusercontent.com/37907088/125047573-cab5bb80-e0a7-11eb-9e2c-73d155ad9ea4.png)

**Comment by Slava7572** [comment]
Подтверждаю,версия 8.1.1(Вин10х64),были нормальные значки,попробовал на свою голову темную тему и теперь вернуть прежний вид не понятно как.Не только пустые иконки плагинов,но и остальные значки хотелось бы прежние,они гораздо информативнее,да и привычка вещь упрямая.Именно из за значков я темную тему и убрал кстати.

**Comment by durmusk** [comment]
I discovered that you can actually select icon style from Preferences -> General. So my issue is resolved. I'm closing this.

![np_icons](https://user-images.githubusercontent.com/37907088/125067313-c8119100-e0bc-11eb-90ca-e71d1f10ed97.png)

**Comment by mnh48** [comment]
is there any way to also use standard icons for the plugins while still using fluent UI ?
because using the standard icons is kinda weird on dark mode, but all except one of the plugin icons had disappeared when not using standard icons
![image](https://user-images.githubusercontent.com/12217018/125092855-53fadb80-e104-11eb-9633-c8531861586f.png)

**Comment by durmusk** [comment]
> is there any way to also use standard icons for the plugins while still using fluent UI ?
> because using the standard icons is kinda weird on dark mode, but all except one of the plugin icons had disappeared when not using standard icons

I guess it is not supported yet. I suggest you create a new issue regarding this.
