### ISSUE TITLE
please make settings easy to deploy

### ISSUE THREAD

**Issue by biax** [notepad-plus-plus/notepad-plus-plus#1013]
So I install npp for the first time. Themes are in %appdata%. I add another windows user. Obviously they wont have themes.

Default configuration should be in %Programfiles%\notepad++\default_config

when theres a new version of npp, %Programfiles%\notepad++\default_config will have the new updated files.

in style configuration, it will read both global settings as well as local settings so that user can store their own themes in %appdata%. I think this should be the correct way.

I deploy notepad++ a lot so I hope to see an improvement here.

**Comment by RafaelLVX** [comment]
I have the same problem with a slightly different flavor. I use the zip version of Notepad++ stored in a Onedrive folder to open the same app with the same settings and themes from different machines, but I can't update it, otherwise customized themes are lost. Preferences are not changed when I update.

**Comment by MetaChuh** [comment]
please use portable mode if you want to have everything inside the notepad++ program folder.

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)
