### ISSUE TITLE
Search-and-replace in files has open files changed

### ISSUE THREAD

**Issue by mrandreastoth** [notepad-plus-plus/notepad-plus-plus#10132]
This is arguable, but when one perform a file-based search-and-replace, it feels as if the replacement should be happening on the file-level only and not withing Notepad++ itself; that is, if a file is open but a file-based search-and-replaced in performed from Notepad++, the displayed content of that file should remain unchanged. Then, if the user activates that tab (or it is already active when the search-and-replace takes place), Notepad++ should, as it normally would do, notify the user that the file has changed and what they wish to do. If one wanted to perform a search-and-replace that affected open tabs, then there's already options for this. The different search-and-replaces should not cross domains but remain atomic in nature, that provides the ultimate in flexibility to the user.

**Comment by sasumner** [comment]
It's design philosophy.  We like it the way it is.  Sorry.
