### ISSUE TITLE
Status line is bad when changing the encoding with shortcut.

### ISSUE THREAD

**Issue by hopalongrock** [notepad-plus-plus/notepad-plus-plus#10146]
Changing the encoding from ANSI to OEM 852 with the newly defined Ctrl+Alt+8 shortcut works well, however the status line contains OEM 852 partly overwritten with Ctrl+Alt+8.

![20210713 OEM 852](https://user-images.githubusercontent.com/6840865/125479185-0c43dc4c-8442-4cc4-b9f2-fc8583f6dcca.jpg)

See https://community.notepad-plus-plus.org/topic/21473/status-line-is-bad-when-changing-the-encoding-with-shortcut/2

**Comment by pryrt** [comment]
I have confirmed (see my post in the [linked](https://community.notepad-plus-plus.org/topic/21473/status-line-is-bad-when-changing-the-encoding-with-shortcut/2) Community discussion).

Steps to replicate:
1. Fresh unzip of v8.1.1-64bit portable
2. Use Shortcut Mapper, filter for 852, and assign keyboard shortcut `Ctrl+Alt+8` to `OEM 852` character encoding
3. On the empty file, hit `Ctrl+Alt+8` (or **Encoding > Character Sets > Central European > OEM 852**)
4. The status bar shows as @hopalongrock indicated

Desired behavior
* status bar shows `OEM 852` without showing the keyboard shortcut

Actual bad behavior
* status bar shows `OEM 852` overlapping the `Ctrl+Alt+8` shortcut

Debug Info:
```
Notepad++ v8.1.1   (64-bit)
Build time : Jul  1 2021 - 14:10:53
Path : C:\usr\local\apps\npp\npp.8.1.1.portable.x64\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : ON
Cloud Config : OFF
OS Name : Windows 10 Enterprise (64-bit) 
OS Version : 1903
OS Build : 18362.1256
Current ANSI codepage : 1252
Plugins : ComparePlugin.dll mimeTools.dll NppConverter.dll NppExport.dll 
```

**Comment by mere-human** [comment]
@sasumner Can you assign this to me, please?
