### ISSUE TITLE
Counter of selected text blocks.

### ISSUE THREAD

**Issue by megaslowpoke** [notepad-plus-plus/notepad-plus-plus#10142]
### Description of the Issue
Maybe I wasn't looking hard enough, but I couldn't find in the help what this place in the status bar means:

![screenshot](https://i.ibb.co/QKyW6zC/select-query.png)

It probably refers to "Sel: 40", and I expected that here will be the counter of allocated blocks (double click), there are just two as seen in the screenshot, since they are shown anyway - why not count them, but in the status bar at this place is always "1".

Since I did not find a description of the status bar, I do not know how to classify my question: as a bug or as a proposal to add functionality.

Yes it would be very convenient to see at once how many selected blocks, without using the search function, and without looking through the whole document with your own eyes in search of selected text. Not necessarily in this place, but it seems that the information about the number of blocks here is the best place.

### Debug Information
Notepad++ v8.1.1   (64-bit)
Build time : Jul  1 2021 - 14:10:53

**Comment by sasumner** [comment]
When you double-click you are _highlighting_, not _selecting_.  The status bar shows the number of _selected_ blocks here when there is more than one selection:

![image](https://user-images.githubusercontent.com/30118311/125623974-aaa0d910-45a0-465d-85fd-b67f6e5bd5ab.png)

The `1` that you have circled in your screen shot shows that your current _selection_ is on one line.
The "40" refers to the number of characters in that single selection.

If you want to count, the _Count_ function on the _Find_ tab of the searching dialog is the way to go.

**Comment by megaslowpoke** [comment]
Sorry, English is not my native language, I could have misspelled it:
> without using the search function

Okay, so this is a request for a new feature: to show in the interface, the number of identical with selected block.

They are already shown on the screen as a result of the background search anyway, and want to see the number of them.
