### ISSUE TITLE
SQL syntaxhighlighting: invalid after backslash character

### ISSUE THREAD

**Issue by ImperiaGP** [notepad-plus-plus/notepad-plus-plus#10154]
### Description of the Issue
The syntax highlighting for SQL text after a backslash ( \ ) character is invalid.

### Steps to Reproduce the Issue

1. Enter the following SQL text in Notepad++:
```
SELECT '\' FROM dual;
SELECT * FROM user_tables;
```

### Expected Behavior
![image](https://user-images.githubusercontent.com/6501352/125588641-a778fad1-63f3-4c88-a2d7-ac9b3208f60b.png)

### Actual Behavior
![image](https://user-images.githubusercontent.com/6501352/125588772-5707852a-49f5-4de6-aa39-9032ad8c1eb6.png)

### Debug Information
N/A

**Comment by ArkadiuszMichalski** [comment]
Try this: https://github.com/notepad-plus-plus/notepad-plus-plus/issues/8919#issuecomment-701285073. I'll add this to the FAQ a bit later because I've seen it xxx times.

**Comment by ImperiaGP** [comment]
I didn't know. Sorry for the spam 😉
