### ISSUE TITLE
"Alternate icons" feature don't works properly in dark mode

### ISSUE THREAD

**Issue by Kimpa-Tammas** [notepad-plus-plus/notepad-plus-plus#10159]
### Description of the Issue

When “Alternate icons” option in Settings > Preferences > General > Tab Bar is enabled in dark mode and I relaunch Notepad++, icons disappear. I need to switch again the option to restore icons. Note there is no issue when the dark mode is disabled.

### Steps to Reproduce the Issue

1. Switch to dark mode. 
2. Enable “Alternate icons” option in Settings > Preferences > General > Tab Bar.
3. Quit Notepad++.
4. Relaunch Notepad++.

### Expected Behavior

Check icon ✔ will be appear on tabs when Notepad++ is started.

### Actual Behavior

No icon appear, need to switch the "Alternate icons" option again.

### Debug Information

Notepad++ v8.1.1   (64-bit)
Build time : Jul  1 2021 - 14:10:53
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : 
Admin mode : ON
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 10 Home (64-bit) 
OS Version : 2009
OS Build : 19042.1083
Current ANSI codepage : 1252
Plugins : ComparePlugin.dll DSpellCheck.dll Explorer.dll HTMLTag.dll ImgTag.dll mimeTools.dll NppConverter.dll NppExport.dll NppSnippets.dll SurroundSelection.dll _CustomizeToolbar.dll 
![Clipboard 1](https://user-images.githubusercontent.com/33954530/125641853-b7c1e3b4-42ef-4e14-b65c-43519cf0c473.png)
![Clipboard 2](https://user-images.githubusercontent.com/33954530/125642328-ad40cabb-5558-4311-a4b8-26183f75f2e3.png)

**Comment by sasumner** [comment]
I'm not totally sure of the "fate" of "Alternate icons" in _Dark Mode_.

I do know that the intent in dark mode is to not have any icon when the file is saved.
So basically there is a big blank gap in front of the filename for saved tabs.
To me this seems like something that opens the door to user complaints, about a missing icon, and/or about a "big gap", even though it was a design decision to not have an icon for the saved situation.

But your issue is more about the alternate icons.
I just wanted to address the "No icon appear" portion, in general.

**Comment by pryrt** [comment]
But if it's a design decision to not have the checkmark/saved icon in Dark Mode, then
1. Why does the checkmark show up when you first change to Alternate Icons when in Dark Mode?
2. We should document the intended behavior in the usermanual.  Do you have a reference to the PR or Issue where that design decision was made?

For the alternate icons: in my experiments, I had a saved file, an edited/unsaved file, and a locked file (**Edit > Set Read Only**): when I restarted, there is no icon on saved file, the pencil icon _does_ stay there on edited-but-unsaved files, and the lock icon stayed on the read-only file.  If I change to not-alternate-icons, all three tabs have the old-fashioned icons; if I exit and return, the edited and locked icons stay, but the saved icon is black.  So it appears to be behaving as designed after a restart.  But any time you toggle the alternate icons checkbox, the saved icon (whether a disk or a checkmark) will show up until you restart.

**Comment by sasumner** [comment]
@pryrt 

All I know was what I said:  _the intent in dark mode is to not have any icon when the file is saved_
This was a @donho decision.  When I commented upon it, I was told "let's see if users complain".  Sorry, I don't have a reference link for this.

And I do agree that the way the software functions regarding this (the OP's complaint) is messed up.
And you point out more ways in which it is messed up.
For the record, I was not involved in any of it. :-)

**Comment by pryrt** [comment]
@sasumner ,

Then, I guess for this issue, should the "fix" be to make Dark Mode behave per the design decision, even when the alternate-icon checkbox is first toggled -- that is, _never_ show the saved icon in Dark Mode?

**Comment by Moonsilence** [comment]
This happens not only with the "Alternate Icons" (checks), but also with the default icons (blue floppy disk): In darkmode, they disappear at restart.

**Comment by pryrt** [comment]
> This happens not only with the "Alternate Icons" (checks), but also with the default icons (blue floppy disk): In darkmode, they disappear at restart.

Indeed.  Did you notice that @sasumner said, "the intent in dark mode is to not have any icon when the file is saved" -- notice that the statement is true regardless of whether "Alternate Icons" is checked or not.  The edited/unsaved and locked icons both still work in Dark Mode.

**Comment by Moonsilence** [comment]
Please allow the use of "alternate icons" in dark mode! Thank you!

**Comment by ArkadiuszMichalski** [comment]
They are available, the behavior is just inconsistent and gives the impression that they are not working. So if `"the intent in dark mode is to not have any icon when the file is saved"` then it should also apply immediately when we set ""alternate icons". Now showing / not showing  this pencil depending on the situation is just confusing.

**Comment by Moonsilence** [comment]
OK. The quoted "intent" is regretable in my opinion. I prepfer to have an icon showing on each tab, that shows it's state. "Alternate Icons" enables exactly that: A distinct icon is showing on every tab, indicating it's state. I find the the absence of icons for unedited/saved files, as is the case with the "default icons" to be confusing and a bit ugly.

**Comment by xnaas** [comment]
Just chiming in to say that having icons is definitely very nice and would like to see any form of them visible in dark mode. (Yes, I just toggle `Alternate icons` off and back on every time right now.)

**Comment by Moonsilence** [comment]
Yeah, people want the "Alternative Icons" in Dark Mode, so please just allow this, thank you very much!
