### ISSUE TITLE
Edit history may be comprised after editing during a compare of two edited files.

### ISSUE THREAD

**Issue by nentrium** [notepad-plus-plus/notepad-plus-plus#10155]
### Description of the Issue
As we all know you can move backwards (ctrl+z) and forwards (ctrl+y) through the edit history for open and edited files.
On occasions I may find I want to compare an edited file with another edited file or an open unedited file.
If either or both files are changed during the compare and the compare is canceled (ctrl+alt+x) the edit history for one or both files may be lost.
This seems be a bit random, may be determined as to which one is the 'first to compare'??
Have noted that sometimes only recent changes remain in history and earlier edits prior to editing during compare are lost.
The trigger for this would be to edit one or both files while in compare mode, simple entering and exiting the compare does not appear loose the edit history of either file.

### Steps to Reproduce the Issue
to save files to temp files and compare the temp files. I'm sure would work, but messy, but would leave the edit history of the original files unchanged as the have not been compared or edited during compare.

### Expected Behavior
To still have the edit history available after a compare is canceled (ctrl+alt+x) for both files and as far back as would normally be expected ( however far back that is ).

### Actual Behavior
edit history for the two files compared may be lost.
edit history for other open files remains unaffected, as far as I can be sure!

### Debug Information
Notepad++ v7.9.5   (64-bit)
Build time : Mar 21 2021 - 02:13:17
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS Name : Windows 7 Home Premium (64-bit) 
OS Build : 7601.24544
Current ANSI codepage : 1252
Plugins : ComparePlugin.dll HexEditor.dll mimeTools.dll NppConverter.dll NppExport.dll

**Comment by ArkadiuszMichalski** [comment]
This is a problem for the Compare plugin developer: https://github.com/pnedev/compare-plugin. You can report it there, but please read this comment first: https://github.com/pnedev/compare-plugin/issues/261#issuecomment-866648542
