### ISSUE TITLE
Function List not working with Java files with AutoDoc comments

### ISSUE THREAD

**Issue by Stefan1200-de** [notepad-plus-plus/notepad-plus-plus#1015]
The included function list has problems with Java files, if methods or classes have (AutoDoc) comments. If the class have an AutoDoc comment, the function list is displaying nothing. Tested all Notepad++ versions with the included function list up to the current version 6.8.4.

Here an example Java file, where the Function List is displaying nothing (I know much more, but they are quite similar to this one):
http://www.stefan1200.de/JTS3ServerQuery.java
![notepadjava](https://cloud.githubusercontent.com/assets/15168351/10557644/cdf331e8-74b4-11e5-9a0a-c4e96bc02e03.png)

Very simple Java files without any comments and other stuff working fine. But more complex Java files don’t work. There was already a forum thread where some people was testing some stuff without success, look here: https://notepad-plus-plus.org/community/topic/131/included-functionlist-is-not-compatible-with-the-most-java-files

I would be happy to see this fixed. Thank you in advance.

**Comment by AleWin32** [comment]
If you add a new line at the end of the file, it will parse the functions.
I read some .java files from a shared drive, that i only have read permissions and the files does not have the final new line, so Notepad++ does not parse the functions :-(

**Comment by AleWin32** [comment]
There is also another bug:

DOES NOT WORK:
´´´java
public void performTask (javax.servlet.http.HttpServletRequest req, javax.servlet.http.HttpServletResponse res, SessionController sessionController) throws javax.servlet.ServletException, java.io.IOException {
´´´

WORKS:
´´´java
public void performTask (javax.servlet.http.HttpServletRequest req, javax.servlet.http.HttpServletResponse res, SessionController sessionController) throws IOException {
´´´

**Comment by AleWin32** [comment]
And also

DOES NOT WORK:
	public void doGet(HttpServletRequest req, HttpServletResponse res)
		throws ServletException, IOException {
		doPost(req, res);
	}

WORKS:
	public void doGet(HttpServletRequest req, HttpServletResponse res)
		throws ServletException {
		doPost(req, res);
	}

**Comment by AleWin32** [comment]
Please, correct at least the need of having a final newline to parse the .java functions.
I only have read permissions over a network drive so i cannot modify the .java file on the fly to see the function list working.

THANKS

**Comment by dail8859** [comment]
Closed by PR #2602

**Comment by Stefan1200-de** [comment]
Tested Notepad++ 7.4.1, I still have the issue, that an empty line is needed.

**Comment by dail8859** [comment]
You may need to delete your functionList.xml file in your appdata directory.

**Comment by Stefan1200-de** [comment]
Thank you, dail8859, for your answer. I just tested it, Notepad++ created a new functionList.xml, but I still have this issue. The empty line is still needed to get the FunctionList working with my example file from the start post.

**Comment by MAPJe71** [comment]
The original issue is about Function List not correctly parsing Java files containing AutoDoc. AFAIK that issue has been solved with #2602.

The requirement for a final newline/empty line is a separate issue IMO (see #2910).

**Comment by Stefan1200-de** [comment]
Thanks MAPJe71, I understand :)

**Comment by anniew86** [comment]
I Notepad++ 7.5.4 in the Function List of Java class there are only methods which have no parameters. Methods with parameters are missing.
