### ISSUE TITLE
Print should remember preferred Landscape vs. Portrait mode

### ISSUE THREAD

**Issue by nerdfever** [notepad-plus-plus/notepad-plus-plus#10151]
### Description of the Issue

Every time I print, NP++ defaults to printing in portrait mode.

I tend to use long lines - I prefer landscape, but have to manually re-configure it on each print.

NP++ should have a Preferences setting under Print that can be configured for this.

### Steps to Reproduce the Issue

1. File>Print...
2. Click Preferences button
3. Set "Landscape" in printer driver
4. Print
5. Edit something...
6. Repeat steps 1 to 3 - now the printer is back in Portrait mode.

### Debug Information

Notepad++ v7.9.5   (32-bit)
Build time : Mar 21 2021 - 02:09:07
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS Name : Windows 10 Enterprise (64-bit) 
OS Version : 2004
OS Build : 19041.1083
Current ANSI codepage : 1252
Plugins : mimeTools.dll NppConverter.dll NppExport.dll

**Comment by donho** [comment]
It's rather OS issue than the application's one. 
This feature won't be implemented.

**Comment by nerdfever** [comment]
Understood, but it's an annoyance all the same.

Would be nice if NP++ remembered in its settings.
