### ISSUE TITLE
Opening a large file is stuck

### ISSUE THREAD

**Issue by shui-dun** [notepad-plus-plus/notepad-plus-plus#10157]
### Description of the Issue

Opening a large file is stuck

### Steps to Reproduce the Issue

1. Opening a large file is very slow, or even unresponsive
2. after opening, try to slide the page, it will also be very lagging 

### Expected Behavior

Browse and edit large files smoothly 

### Actual Behavior

lagging

### Suggest

opening a .txt file will not lagging, only open a rendered(highlighted) file (e.g. .html) will lagging. I recommend judging the size of the file before opening it. If it is too large, disable syntax highlighting

**Comment by thomassmith311** [comment]
Debug info?

**Comment by shui-dun** [comment]
### Debug info

Notepad++ v8.1.1   (64-bit)
Build time : Jul  1 2021 - 14:10:53
Path : D:\Notepad++\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : ON
Cloud Config : OFF
OS Name : Windows 10 Home China (64-bit) 
OS Version : 2009
OS Build : 19042.1052
Current ANSI codepage : 65001
Plugins : ComparePlugin.dll mimeTools.dll

**Comment by thomassmith311** [comment]
Seems like you're running the portable version of Notepad++ off a disk. Is that right? If so, could you try running it directly from the computer's storage space, opening the large file, and seeing if it lags.

Also, how many lines is your file? I've used Notepad++ with files 15,000 lines or longer with no issue (and with syntax highlighting), though not portable from disk or usb stick.

**Comment by shui-dun** [comment]
Thank you very much for your help. But in fact, I don't use the portable version, I just check the "do not use %appdata%" option when I install npp so "Local Conf mode" is on.

A file with 15,000 lines will not lagging, I encounter this problem with a 30M file or bigger. (I did get a such large html file sometimes). But a 30M file with no highlighting don't lag. That's why I recommend checking the size before opening the file and If it is too large, disable syntax highlighting.

**Comment by chcg** [comment]
Maybe you want to try to open such files with the plugin https://github.com/superolmo/BigFiles

**Comment by shui-dun** [comment]
> Perhaps it could be helpful to add a setting, something like "Disable syntax highlighting for large files" in the settings menu. The user could choose whether to have this feature or not, then. There would be a threshold, logically (like you said, maybe 30M).

I can’t agree with you more.

**Comment by aomsweet** [comment]
Open a 10M xml file, notepad++ is stuck.

**Comment by aomsweet** [comment]
> Open a 10M xml file, notepad++ is stuck.

I'm able to open the file quickly after changing the file extension to txt. Can anyone tell the principle of this? Open the xml file modified to txt can still highlight xml.
