### ISSUE TITLE
Update reference to sourceforge.net in contextMenu.xml

### ISSUE THREAD

**Issue by nerdfever** [notepad-plus-plus/notepad-plus-plus#10150]
### Description of the Issue

The contexMenu.xml that ships with NP++ (and is used as a starting point for customization) says:

> Please check "How to Customize the Context Menu" on:
> http://sourceforge.net/apps/mediawiki/notepad-plus/index.php?title=Context_Menu

That link is dead since the move to GitHub - it should be updated.

### Steps to Reproduce the Issue

1. Settings>Edit Popup ContextMenu
2. Read it.

### Expected Behavior

No references to dead links.

### Actual Behavior

Saw a reference to a dead link.

### Debug Information
Notepad++ v7.9.5   (32-bit)
Build time : Mar 21 2021 - 02:09:07
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS Name : Windows 10 Enterprise (64-bit) 
OS Version : 2004
OS Build : 19041.1083
Current ANSI codepage : 1252
Plugins : mimeTools.dll NppConverter.dll NppExport.dll

**Comment by ArkadiuszMichalski** [comment]
You have old `contextMenu.xml` file, new is correct: https://github.com/notepad-plus-plus/notepad-plus-plus/blob/master/PowerEditor/src/contextMenu.xml. Update it manually if you want to keep the added items.
