### ISSUE TITLE
Spacing inconsistency and width issue

### ISSUE THREAD

**Issue by ozone10** [notepad-plus-plus/notepad-plus-plus#10169]
Some items are not evenly spaced.  
In Dark Mode text for custom color items are too wide and can cause visual glitch, when changing color. 
In Print  Here display your variable setting go beyond groupbox.

I've included images for all settings for completeness.

![image](https://user-images.githubusercontent.com/55940305/125847684-f9ba95e8-edda-41d6-89b3-e5be38763eca.png)
![image](https://user-images.githubusercontent.com/55940305/125847946-b5a87703-6e04-431e-830d-ac300f760280.png)
![image](https://user-images.githubusercontent.com/55940305/125847983-b3073d73-145a-42f3-9838-f63069dbb114.png)
![image](https://user-images.githubusercontent.com/55940305/125848018-ae832578-2c99-4b27-9974-06ad3c8542be.png)
![image](https://user-images.githubusercontent.com/55940305/125848068-6f8d2815-2818-459a-ad6b-ea2262c2aa55.png)
![image](https://user-images.githubusercontent.com/55940305/125848102-e7d2bbdf-eeb8-4b5d-ae7f-3d538380f839.png)
![image](https://user-images.githubusercontent.com/55940305/125848127-845110f0-f233-4930-bdc2-7b4a7db67ab4.png)
![image](https://user-images.githubusercontent.com/55940305/125848152-dc782a47-9a33-4326-a7d4-8d6477ccd634.png)
![image](https://user-images.githubusercontent.com/55940305/125848179-c4ae189b-21e4-4904-afa1-e9f5f14f8cc7.png)
![image](https://user-images.githubusercontent.com/55940305/125848213-c87195be-67af-45e3-b0dd-f086ef86dfb6.png)
![image](https://user-images.githubusercontent.com/55940305/125848249-a5958a3d-e937-4eb2-b080-5c7b5ba5393d.png)
![image](https://user-images.githubusercontent.com/55940305/125848288-61c9c837-99dc-4bdf-a997-6a6edcb7bacd.png)
![image](https://user-images.githubusercontent.com/55940305/125848311-69ce6069-94b9-419b-ae7a-a8fe36267128.png)
![image](https://user-images.githubusercontent.com/55940305/125848332-7ee83582-ebb9-4f4e-b84b-75fb86347eba.png)
![image](https://user-images.githubusercontent.com/55940305/125848349-c098e47e-c573-4ee0-9902-d48abfc01eb9.png)
![image](https://user-images.githubusercontent.com/55940305/125848370-55eea9dc-3e2b-4d65-8278-ea1d97ff7f3e.png)
![image](https://user-images.githubusercontent.com/55940305/125848399-63d379af-dee6-4057-8e19-2461e21b011d.png)
![image](https://user-images.githubusercontent.com/55940305/125848422-dea666dd-f5dc-40fc-8075-62e3b923e89c.png)
![image](https://user-images.githubusercontent.com/55940305/125848460-68b69d51-7d74-45db-8a6a-2f3c1bc0c4e1.png)

**Comment by sasumner** [comment]
I'm not sure what the exact complaint is about...
Well, actually, I'm totally sure concerning what it is about. :-)

>...items are too wide...

Lest someone think that the widths are extreme on most controls, let me remind that they are this way to allow for non-English translations, which sometimes are not as "compact" as their English counterparts.

**Comment by ozone10** [comment]
> 
> Lest someone think that the widths are extreme on most controls, let me remind that they are this way to allow for non-English translations, which sometimes are not as "compact" as their English counterparts.

Well the wide issue is mainly about dark mode items (first "column" in customized tone) which are too wide so they go below color buttons and reset button.

So even for other languages, text won't be visible.

And for Print setting that is user defined.

**Comment by ozone10** [comment]
too old, too many commits since, probably fixed
