### ISSUE TITLE
Translation: v8.1.2 new localization file diff

### ISSUE THREAD

**Issue by donho** [notepad-plus-plus/notepad-plus-plus#10160]
New localization file diff v8.1.1 vs v8.1.2 is available here:

[811vs812.zip](https://github.com/notepad-plus-plus/notepad-plus-plus/files/6818131/811vs812.zip)

**Comment by GOLEM777** [comment]
"7124"  - "Tab edge" 
What is this color responsible (on what influences) for?
On Russian, I can interpret it in a very diverse way.

**Comment by donho** [comment]
@GOLEM777 
> "7124" - "Tab edge"
What is this color responsible (on what influences) for?

![image](https://user-images.githubusercontent.com/90293/125714534-9dc121b7-7bec-4223-be82-442a94d7ccd3.png)

**Comment by luxyapp** [comment]
I recommend update the original file version from 7.9.5 to 8.1.2.

**Comment by luxyapp** [comment]
Ah, if you could make the "Edit with Notepad++" button on the Windows context menu translatable, that would be nice too.

**Comment by rddim** [comment]
@donho 
Could you share more information for `Error`, `Darker text` and `Disable text` too, because the `Tab edge` color is applied only after restarted Notepad++?

**Comment by ozone10** [comment]
@rddim IRC `Error` is for wrong search in incremental search, should also apply for function panel search field (but is not, should be fixed).

`Disabled text` is text for disabled item, e.g. in find dialog checkbox for "In selection" when you don't have selection, or disabled items when you disable transparency.

`Darker text` I think it is currently only for column header in panels with listview (document list and ascii char)

**Comment by donho** [comment]
For watching the effect of `Disabled text` & `Darker text`, you can open Find dialog.
