### ISSUE TITLE
Dark mode : Plugin Icons Visibility issues

### ISSUE THREAD

**Issue by ArkB740** [notepad-plus-plus/notepad-plus-plus#10161]
### Description of the Issue
Some plugin icons are not visible iwhen Darkmode is enabled  (but are accessible as their positions are still clickable  - blindly)
Return back from Darkmode to normal: plugin icons are still not visible, those being visible are in darkmode style

### Steps to Reproduce the Issue
1. In preferences: Enable Darkmode, restart Notepad++
2. In preferences: Deselect Darkmode, restart NOtepad++

### Expected and Actual Behavior
0. Original State:
![image](https://user-images.githubusercontent.com/87438410/125698959-4fec69b3-c45b-4c4c-b6a1-7e02a5477a9e.png)

Enable Darkmode, expect all Plugin Icons visible, Actual Behavior:
1. Plugin icons are not visible when Darkmode is enabled. Only few default plugins are visible.
![image](https://user-images.githubusercontent.com/87438410/125699121-46684819-57e3-48de-aeef-7b04936400cb.png)

Deselect Darkmode, Expected: screenshot #0. Actual behavior:
2. Disable Darkmode: Plugin Icons still not visible, Those that were visible are still in Darkmode style
![image](https://user-images.githubusercontent.com/87438410/125699221-5158e5ab-8e9f-458a-910c-30f7f848c1a1.png)

3. Current solution is to uninstall and select NO to keep custom settings

### Debug Information
Notepad++ v8.1.1   (64-bit)
Build time : Jul  1 2021 - 14:10:53
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : -systemtray -nosession
Admin mode : ON
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 10 Enterprise (64-bit) 
OS Version : 1909
OS Build : 18363.1646
Current ANSI codepage : 1252
Plugins : AnalysePlugin.dll CsvQuery.dll Explorer.dll HTMLTag.dll mimeTools.dll NppConverter.dll NppEventExec.dll NppExec.dll NppExport.dll NppFTP.dll NppXmlTreeviewPlugin.dll SessionMgr.dll XMLTools.dll

**Comment by Slava7572** [comment]
Опции/Настройки/Основные/Стандартные иконки:мелкие
перезапуск и значки возвращаются

**Comment by ArkB740** [comment]
Slava7572,
Спасибо за подсказку, работает!

Thank you, Slava7572
