### ISSUE TITLE
[DarkMode] Edge Enhancement?

### ISSUE THREAD

**Issue by ozone10** [notepad-plus-plus/notepad-plus-plus#10166]
With PR https://github.com/notepad-plus-plus/notepad-plus-plus/pull/10145 it is possible to change color for edge,
but it will be applied only after restart.

@donho 
I can fix this.
Also apply edge on docking panel captions, color buttons and status bar divider.
Currently the are using color from Tab edge, should they use their own color?
![image](https://user-images.githubusercontent.com/55940305/125837334-a8c06c07-d23b-49cc-9329-025aee523113.png)

There is typo,  "Disable text" should be "Disabled text" or maybe "Disabled item text"

**Comment by donho** [comment]
@ozone10 
> I can fix this.
Also apply edge on docking panel captions, color buttons and status bar divider.

Yes, please.

> Currently the are using color from Tab edge, should they use their own color?

By "their own color" you mean?


> There is typo, "Disable text" should be "Disabled text" or maybe "Disabled item text"

Thanx. Fixed in
https://github.com/notepad-plus-plus/notepad-plus-plus/commit/93d91c3ee2dced92fd3e02a2348f05a262fc6a27

**Comment by ozone10** [comment]
> By "their own color" you mean?

I mean if I should split them from tab edge color, so they can have different color.

**Comment by donho** [comment]
> I mean if I should split them from tab edge color, so they can have different color.

It's OK. I'll rename from "Tab edge" to "Edge".
