### ISSUE TITLE
File is opened in an arbitrary instance of Notepad++

### ISSUE THREAD

**Issue by iljamaki** [notepad-plus-plus/notepad-plus-plus#10176]
### Description of the Issue
When you have more than one Notepad++ instance open, and you type `notepad++.exe <filename>` in Windows command prompt to open a new file in an existing instance, it seems to pick an arbitrary instance to open the file in. A more logical approach would be to open the file in a Notepad++ instance that at least exists in the same virtual desktop as where the command is given.

### Steps to Reproduce the Issue
1. Have more than one virtual desktops, and a Notepad++ instance open in each one of them. My Multi-instance setting is `Open session in a new instance of Notepad++` in case it matters.
2. In one of the virtual desktops, open Windows command prompt and open a new file in Notepad++ from there. Or, right click a file in Windows Explorer and select Edit with Notepad++.
3. Try the steps a few times. It seems to be arbitrary in which instance of Notepad++ the file is opened.

### Expected Behavior
The file to open consistently in the same Notepad++ instance. Most preferably one that exists in the currently active virtual desktop.

### Actual Behavior
The file opens in any random instance.

### Other info
Operating system: Windows 10 Home Edition 21H1 build 19043.1110
Notepad++ version: v8.1.1 (64-bit) build July 1, 2021

**Comment by donho** [comment]
A win32 API is used for searching an instance - so it depends on the Win32 API and I can do nothing about it, unfortunately.
