### ISSUE TITLE
Prevent automatic reload of files before shutdown

### ISSUE THREAD

**Issue by Ede123** [notepad-plus-plus/notepad-plus-plus#1018]
**Steps to reproduce:** ("File Status Auto-Detection" has to be activated, "Update silently" has to be deactivated, OS was Window 7 in the tests but I don't think it matters):
1 - Open a file in Notepad++
2 - Defocus Notepad++ and edit the file in another application
3 - Now try to close Notepad++ by clicking the close icon

**Expected behavior:**
Notepad++ closes immediately.

**Actual behavior:**
The "Reload" dialog opens ("The File has been modified by another program. Do you want to reload it").
However it does not matter what choice the user makes: Even when choosing to reload the file, Notepad++ is closed immediately afterwards. 

 &nbsp;

I had a quick look at the code but it seems the issue is harder to fix than I hoped:
- The reload (`Notepad_plus::notifyBufferChanged`) is triggered as soon as focus is restored to the Notepad++ window (which is when the mouse button is pressed over the close button)
- The `WM_CLOSE` message is however only triggered after the mouse button has been released.

Does somebody with more experience have an idea on how to fix this?

**Comment by dail8859** [comment]
:+1: I agree this should be the default behavior.

**Comment by Ede123** [comment]
In a first shot to fix this issue I tried to delay reloading by posting a `NPPM_INTERNAL_CHECKDOCSTATUS` message instead of directly reloading after receiving the `WM_ACTIVATEAPP` message (which immediately triggers the reload in the current code). See following diff:

```diff
diff --git a/PowerEditor/src/NppBigSwitch.cpp b/PowerEditor/src/NppBigSwitch.cpp
index bd6d522..23f850f 100644
--- a/PowerEditor/src/NppBigSwitch.cpp
+++ b/PowerEditor/src/NppBigSwitch.cpp
@@ -1335,13 +1335,20 @@ LRESULT Notepad_plus::process(HWND hwnd, UINT Message, WPARAM wParam, LPARAM lPa
 		{
 			if (wParam == TRUE) // if npp is about to be activated
 			{
-				const NppGUI & nppgui = pNppParam->getNppGUI();
-				if (LOWORD(wParam) && (nppgui._fileAutoDetection != cdDisabled))
+				if (Message == WM_ACTIVATEAPP)
 				{
-					_activeAppInf._isActivated = true;
-					checkModifiedDocument();
+					::PostMessage(hwnd, NPPM_INTERNAL_CHECKDOCSTATUS, wParam, lParam);
 					return FALSE;
 				}
+				else
+				{
+					const NppGUI & nppgui = pNppParam->getNppGUI();
+					if (nppgui._fileAutoDetection != cdDisabled)
+					{
+						_activeAppInf._isActivated = true;
+						checkModifiedDocument();
+					}
+				}
 			}
 			break;
 		}
```

It works in principle (e.g. I can close Notepad++ without being bothered by the reload message).
However it also causes the Notepad++ cursor to to "flicker" (it changes shape between the text entry cursor and a normal arrow pointer cursor) when reloading otherwise. Anybody has an idea what's going wrong?

**Comment by donho** [comment]
@Ede123 & @dail8859 
What should be a correct behaviour to you?

**Comment by Ede123** [comment]
Well, regarding the original issue f2cd7790669ec3867977293f5c83bdec235b81b5 would probably be sufficient. With the delayed message handling I can close Notepad++ (even if files have changed) without being asked whether I want to reload those files. Notepad++ simply closes (which is the desired behavior).

The emerging problem is the regressions caused by f2cd7790669ec3867977293f5c83bdec235b81b5 that causes the mouse cursor to start flickering.

**Comment by donho** [comment]
@Ede123 So the current behaviour is correct, but there's an issue of flickering mouse cursor, right?

**Comment by dail8859** [comment]
I haven't tried this patch out from Ede123, but I do agree that Notepad++ should close immediately. I agree with Ede123 that this patch would be nice however it does introduce regression with the mouse cursor flickering.

**Comment by Ede123** [comment]
@donho Yes exactly. The fix implemented in f2cd7790669ec3867977293f5c83bdec235b81b5 solved this issue as a side effect (it's basically doing the same as I initially suggested in [comment 3](#issuecomment-154835277)).
However it's causing the flickering issue which is why I never suggested to implement it.

**Comment by donho** [comment]
@Ede123 @dail8859 I can reproduce mouse flickering problem - it appears only on the message dialog. It's indeed a bug, but between the flickering and crash (and hanging) - I choose flickering :)

**Comment by Ede123** [comment]
It's not limited to the message dialog, it also happens in the rest of the Notepad++ GUI, for example on tabs.

By clicking certain UI elements / entering text one can stop the flickering (probably by straithening out whatever is wrong with the message queue at that point).

I hope you intend to fix it anyway?

**Comment by donho** [comment]
@Ede123 What I observe is as soon as I close the dialog, the flickering stops. Is not the case to you?

**Comment by Ede123** [comment]
No, flickering continues. How do you close the dialog? I usually choose "Yes" (i.e. reload the changed file)

**Comment by donho** [comment]
OK, now I can reproduce it.
I have no idea (yet) how to fix it.
Have you any suggestion?

**Comment by Ede123** [comment]
No, I couldn't figure it out when I last worked on it, so I wrote down my findings in the hope somebody else would be able to pin down the cause.

Now that we need the fix to prevent crashing it's obviously even more important to make it work.

**Comment by SinghRajenM** [comment]
@donho 
@Ede123 provides a work around to handle this case manually. If text area is clicked once then there is no more flickering. I have simulated the work around into code using PR #2952 .
