### ISSUE TITLE
notepad-plus-plus.org has bad link for v8.1.2 32-bit x86

### ISSUE THREAD

**Issue by ryanbarlow1** [notepad-plus-plus/notepad-plus-plus#10197]
### Description of the Issue
Hello, I hope you're doing well. Just as a heads up, there is a bad link to download the latest release.

### Steps to Reproduce the Issue
1. Navigate to https://notepad-plus-plus.org/downloads/v8.1.2/
2. Click on the image below "Download 32-bit x86"

The site sends you to
https://github.com/notepad-plus-plus/notepad-plus-plus/releases/download/v8.1.1/npp.8.1.2.Installer.exe
When it should be sending you to
https://github.com/notepad-plus-plus/notepad-plus-plus/releases/download/v8.1.2/npp.8.1.2.Installer.exe

I hope this helps!

**Comment by donho** [comment]
@ryanbarlow1 
Fixed now. Thank you for the heads up!
