### ISSUE TITLE
Mark all - add option to follow "find dialog settings"

### ISSUE THREAD

**Issue by cmeriaux** [notepad-plus-plus/notepad-plus-plus#10195]
### Description of the Issue

Version 8.0 has introduce a regression on mark all feature. It can't be configured through "find dialod settings"
It's so handy to configure that feature through find menu, instead opening Preferences/Highlighting/Mark all menu. That's why there was an option for smart highlighting, so that smar highlighting is configured through find menu
I suggest to a add a menu item to configure it: see bellow the screenshot

![image](https://user-images.githubusercontent.com/12024941/126213391-50a8f2a2-e620-4b37-a751-2d8524060a76.png)

### Steps to Reproduce the Issue

1. 
2. 
3. 

### Expected Behavior

I excpect the behavior of v7.9.5: mark all is configurable through find menu

### Actual Behavior

Mark all is only configurable through preferences.

### Debug Information

Notepad++ v8   (32-bit)
Build time : Jun  6 2021 - 18:41:52
Path : G:\dev\npp.8.0.portable\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : ON
Cloud Config : OFF
OS Name : Windows 10 Enterprise (64-bit) 
OS Version : 2009
OS Build : 19043.1110
Current ANSI codepage : 1252
Plugins : mimeTools.dll NppConverter.dll NppExport.dll 

Same issue with V8.1.1 abd V8.1.2

**Comment by mere-human** [comment]
@cmeriaux But isn't it the same?
![image](https://user-images.githubusercontent.com/9664141/126216294-3c030f09-80fb-4776-bff2-b48ab0034e19.png)

**Comment by cmeriaux** [comment]
@mere-human this is only for smart highlighting

**Comment by mere-human** [comment]
This problem is related to https://github.com/notepad-plus-plus/notepad-plus-plus/pull/9796
Just for the reference.

**Comment by ArkadiuszMichalski** [comment]
This name "Mark All" is used in two places and is confusing because represents two different mechanisms. Can't use some word other than "Mark" for one of them? In context menu we have "Style", which is more obvious.

![image](https://user-images.githubusercontent.com/2730894/128362295-aba3f0e7-07d6-407e-9939-d75cc8848224.png)

Again, I took some time to figure it out. Only for me is it confusing?

**Comment by mere-human** [comment]
> This name "Mark All" is used in two places and is confusing because represents two different mechanisms.

I know. I personally use "Mark All / Style token" sometimes. But I almost never use "Mark" search tab.
Also, here's the doc https://npp-user-manual.org/docs/searching/#mark-tab

**Comment by donho** [comment]
> This name "Mark All" is used in two places and is confusing because represents two different mechanisms.
True. But both do the same job.

So "Style All" and "Style One" sound better?

**Comment by ArkadiuszMichalski** [comment]
>So could it be better to change the left side "Mark All" & "Mark One" to "Style All" & "Style One"?

Yes, it would be more obvious (different from the Mark window) and in line with the context menu.

![image](https://user-images.githubusercontent.com/2730894/128523545-5c623984-f931-48d3-9fab-dadb2c7ff2ca.png)

And in the Preferences change "Mark All" to "Style All".

![image](https://user-images.githubusercontent.com/2730894/128524256-b69d2a48-19c6-4f9e-bdb0-13569c1df9d0.png)

**Comment by ArkadiuszMichalski** [comment]
@cmeriaux
I checked 7.9.5 version and "Mark/Style" was not controled by "Match whole world only" in Find window. There was no any control of this behavior. Although "Match case" from Find window worked for "Mark/Style" in 7.9.5 version.  There is no regression here, but adding "Use Find dialog setting" for some users may be an improvement.

**Comment by donho** [comment]
So it's not a regression and this issue is rather a feature request.
I'm not sure if it's necessary to add this option. I'll keep it opened. Let's wait & see if there are similar request coming.

**Comment by donho** [comment]
A PR for renaming is created here:
https://github.com/notepad-plus-plus/notepad-plus-plus/pull/10351

Your reviews/suggestions are welcome

**Comment by cmeriaux** [comment]
@donho thanks for the renaming. 
Here is a new screenshot of my request with the new naming.

by the way, I consider this is a regression introduced by #9796 . please reconsider your point of view and allow me to implement this feature.

![image](https://user-images.githubusercontent.com/12024941/129522614-69514fb5-aa49-40e3-97f8-0737af067220.png)

**Comment by ArkadiuszMichalski** [comment]
@donho 
> I'm not sure if it's necessary to add this option. I'll keep it opened. Let's wait & see if there are similar request coming.

Another one: https://github.com/notepad-plus-plus/notepad-plus-plus/issues/10431. 

I don't know how in earlier versions "Match whole world only" worked with Find dialog. Can someone check it out? For me it only has an effect on"Match case" https://github.com/notepad-plus-plus/notepad-plus-plus/issues/10195#issuecomment-894309604.

**Comment by donho** [comment]
@ArkadiuszMichalski 
I will consider to implement it anyway.

**Comment by donho** [comment]
https://github.com/notepad-plus-plus/notepad-plus-plus/commit/2576bf884b37a916cf5f597d87e436fb59864cec
