### ISSUE TITLE
[DarkMode] Edge/border around main window/edit zone

### ISSUE THREAD

**Issue by ozone10** [notepad-plus-plus/notepad-plus-plus#10205]
Currently in Npp v8.1.2 `No edge` has no effect in dark mode.
![image](https://user-images.githubusercontent.com/55940305/126368419-ccd30482-747c-47f2-afdf-a18e86216654.png)

What about using `WS_BORDER` style instead of `WS_EX_CLIENTEDGE` in dark mode.
![image](https://user-images.githubusercontent.com/55940305/126368739-730189ce-ce9a-40f9-81a3-42ddd87494d0.png)

**Comment by mere-human** [comment]
Shall we create a special tag for dark mode issues?

**Comment by ozone10** [comment]
I think there is already Dark mode label.
