### ISSUE TITLE
Blank Operations --> TAB to Space doesn't consider the already used space

### ISSUE THREAD

**Issue by Spamme1** [notepad-plus-plus/notepad-plus-plus#1020]
It was strange but I wanted to remove tabs and replace with spaces, so I just used the find and replace function, which work great but alas tabs can have different lengths. With a tab you jump to the next tab stop, so if you have tab length of 8 chars and you have already written 7 chars, the tab length is effectively only 1 char length. So the find and replace function doesn't considering the already used chars in a tab and replace always the tab with x white spaces. For example the following lines aligned with a tab lose the alignment after replacing with spaces:
```
	World
H	World
He	World
Hel	World
```
```
    World
H    World
He    World
Hel    World
```
So this problem can't really be solved with a simple find and replace function, it needs some logic, namely it has to calculate the already used space from a tab and replace it with the exactly remaining white spaces. So I googled it and found that there is a "TAB to Space" function in notepad++, most probably was exactly what I was looking for, because such a logic can only be implemented in a separate function. But alas with my big disappointment this function works exactly as the find and replace function. At this point I ask myself the utility of such function, because it is already covered from the find and replace function. Instead it would be a very useful function if it replaces the tabs only with the needed spaces to preserve any text alignment in the document.

**Comment by AdrianHHH** [comment]
I believe the function you want is: Menu => Edit => Blank operations => Tab to space.

Find and replace is the wrong tool.

**Comment by Spamme1** [comment]
@AdrianHHH Yes it is what I was expecting, but the "TAB to Space" function works exactly as the find and replace.

**Comment by AdrianHHH** [comment]
TAB to space is not the same as search and replace on my copy of Notepad++ version 6.8.3. TAB to space works fine for me. I have just tried the text below where T means tab and S means space. So it includes the example in the question. What version are you using and can you provide a short example that demonstrates the problem?

TTTx
TSSTTSSy
SSSSTTTz
TWorld
HTWorld
HeTWorld
HelTWorld

Notepad++ does seem to default to a tab width of 4 characters, might the be confusing you?

**Comment by Spamme1** [comment]
Strange, I had an old version installed, namely 6.6. I just update to the latest version and now it works. Normally notepad++ warns, when a new version is available, did I turned it off? If you skip one version, does notepad++ stop the notification of new versions?

Many thanks

**Comment by donho** [comment]
So there's no bug.
It'll be nice to close this issue while you realize it's rather a PEBCAK.
