### ISSUE TITLE
Proposal: Move 'Modify Shortcut' menu item to top

### ISSUE THREAD

**Issue by Mrnofish** [notepad-plus-plus/notepad-plus-plus#10201]
### Description of the Issue
Currently, the `Modify Shortcut/Delete Macro` menu item is at the bottom of the `Macro` menu.

If there is a large number of recorded macros, exceeding the vertical room available, the menu will gain arrows to scroll it.

When it is necessary to activate one of the menu items items at the top, there will be a lot of slow scrolling by clicking on arrows.

Moving `Modify Shortcut/Delete Macro` to the top, with the other items, will make this process much faster.

**Comment by donho** [comment]
The current position (to me) is an idea position.
