### ISSUE TITLE
Tab overflow buttons not affected by dark mode

### ISSUE THREAD

**Issue by mrandreastoth** [notepad-plus-plus/notepad-plus-plus#10208]
See screenshot below. Note how the tab overflow buttons are not taking on the dark mode theme when they should.

![image](https://user-images.githubusercontent.com/26897855/126390636-c4cc29fb-595a-4874-9097-c5913fdd567f.png)

**Comment by ozone10** [comment]
duplicate of https://github.com/notepad-plus-plus/notepad-plus-plus/issues/10054
