### ISSUE TITLE
Suggestion: wheel support to scroll menus

### ISSUE THREAD

**Issue by Mrnofish** [notepad-plus-plus/notepad-plus-plus#10204]
### Description of the Issue
When the length of a menu exceeds the available vertical room, the menu gains arrows in order to be scrolled.

Scrolling the menu with the wheel is currently impossible.

**Comment by ArkadiuszMichalski** [comment]
Duplicate of https://github.com/notepad-plus-plus/notepad-plus-plus/issues/8401.
