### ISSUE TITLE
Drop-down lists not affected by dark mode

### ISSUE THREAD

**Issue by mrandreastoth** [notepad-plus-plus/notepad-plus-plus#10209]
See screenshot below. Note how the drop-down list area is not taking on the dark mode theme when it should. Issue affects all drop-down controls and not just the one shown.

![image](https://user-images.githubusercontent.com/26897855/126391505-ef3bdb0f-f8f7-46bf-b99d-b6a3066d85f5.png)

**Comment by ozone10** [comment]
fixed in https://github.com/notepad-plus-plus/notepad-plus-plus/commit/81b21aae2a1d948a5f1b56cfdc1070d1835f9586
