### ISSUE TITLE
Distraction-free mode's exit buttton not affected by dark mode

### ISSUE THREAD

**Issue by mrandreastoth** [notepad-plus-plus/notepad-plus-plus#10210]
See screenshot below. Note how the distraction-free mode's exit button is not taking on the dark mode theme when it should.

![image](https://user-images.githubusercontent.com/26897855/126392239-cab5f4b1-4f3b-406f-aea8-7b10f3048132.png)

**Comment by ArkadiuszMichalski** [comment]
The same is for `Full Screen Mode (F11)` and `Post-It (F12)`.
