### ISSUE TITLE
Enable dark mode switches the Toolbar Icons

### ISSUE THREAD

**Issue by DMI-1407** [notepad-plus-plus/notepad-plus-plus#10212]
If "Standard Icons: small" is selected and then Dark Mode gets enabled the Toolbar Icons are set to "Fluent UI: small" and "Fluent UI: small" is selected.
_(This is really annoying...)_

### Steps to Reproduce the Issue
1. Disable:  Preferences -> Dark Mode -> Enable Dark Mode
2. Select:  Preferences -> General -> Toolbar -> Standard icons: small
3. Enable:  Preferences -> Dark Mode -> Enable Dark Mode

### Expected Behavior
No change in:  Preferences -> General -> Toolbar

### Actual Behavior
Sets option to:  Preferences -> General -> Toolbar -> Fluent UI: small

### Debug Information
Notepad++ v8.1.2   (32-bit)
Build time : Jul 16 2021 - 01:56:21
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 7 Professional (64-bit) 
OS Build : 7601.0
Current ANSI codepage : 1252
Plugins : none

**Comment by DMI-1407** [comment]
label:bug

**Comment by ArkadiuszMichalski** [comment]
Any reason why after turning off Dark Mode the previous icon pack is not selected? I usually use `Standard Icons: small` and I have to manually select them again after turning off Dark Mode, it's annoying.

**Comment by donho** [comment]
For simplifying UX, once user switch on/off dark mode, a lot of settings will be change.
But in v8.1.3, once you stay in dark mode, your settings will be kept while you're changing the ton or customizing your dark mode.
Such behaviour will be remained.
