### ISSUE TITLE
HEX-Editor Stability inconsistency

### ISSUE THREAD

**Issue by Jing-Aalmers** [notepad-plus-plus/notepad-plus-plus#1021]
The _Plugin Manager_ is stating the stability of the _HEX-Editor_ plug-in to be good since quite a while. Nevertheless during every new update of the Notepad Editor a pop-up claims stability issues with _HEX-Editor_ and shifts the plug-in to the \disabled folder.
I'm puzzled what causes this inconsistency.

**Comment by ariccio** [comment]
HEX-editor is full of bugs (easily spotted by compiling with `/analyze`), and it probably should be marked as "good"

**Comment by vgturtle127** [comment]
If it is full of bugs, then why would we mark it as good? Why don't we mark it as pretty broken, since most of the features are broken, and it crashes Notepad++ most of the time?

**Comment by ariccio** [comment]
> If it is full of bugs, then why would we mark it as good? Why don't we mark it as pretty broken, since most of the features are broken, and it crashes Notepad++ most of the time?


Hmm. I'm not actually sure why I said so, but I think I meant *shouldn't be marked as "good"*.

**Comment by vgturtle127** [comment]
Oh, OK. I was like, what? :laughing:

**Comment by mik2** [comment]
> I think I have the source, but honestly Hex Workshop or HxD is a way better option.

I cannot see these plugins in *Plugin Manager*. Maybe they should be included there instead of the buggy *HEX-Editor*?

**Comment by vgturtle127** [comment]
@mik2 Oh, no I meant a dedicated hex editor. As in, a seperate application as opposed to one built off of a text editor. If you Google the two hex editors I mentioned, they are both available for download.

**Comment by mik2** [comment]
A separate hex editor is useful, however having a plugin in *Notepad++* is also a good option. I use *Hex-Editor* occasionally, the only annoyance (for me) is the need to reinstall it every *Notepad++* upgrade.

**Comment by xylographe** [comment]
@mik2
If you rename the assembly in the `plugins` folder (for example, `HexEditor.dll` ==> `HexEditorOK.dll`), you won't need to reinstall after upgrading.

**Comment by vgturtle127** [comment]
@mik2 I understand what you're saying, but at least for me, the plugin crashes a lot and isn't very stable. Does it work OK for you?

@xylographe Does Notepad++ use hardcoded plugin names or something?

**Comment by xylographe** [comment]
@vgturtle127 
Yes, the assembly names of the  *“unstable plug-ins”*  are hard-coded in [`nppSetup.nsi`](https://github.com/notepad-plus-plus/notepad-plus-plus/blob/master/PowerEditor/installer/nppSetup.nsi#L555).

**Comment by vgturtle127** [comment]
@xylographe Huh, that seems like a somewhat inefficient way of doing things, maybe I will make another issue for that. :smiley: 

As for the current issue, I think the hex editor plugin needs to be updated in order for it to be considered stable. I think a hex editor should be able to handle files larger than 4MB, which this doesn't seem to handle very well in my experience. Let me take a look at it and I will see if maybe a quick update can be done to make it more stable or something... :+1:

**Comment by Borkason** [comment]
For me the Hex-Editor never crashed. I don't want to deny there may be issues with the plugin, but I would wish that I would be _asked_ whether I want to disable the plugin or not when I upgrade N++. I leave this idea here as a suggestion.

**Comment by vgturtle127** [comment]
@Borkason Huh, it always crashes Notepad++ for me. I also wish I was asked first.

**Comment by mik2** [comment]
A question used to work, but version 7.3.3 disables HexEditor.dll again without question.

**Comment by vgturtle127** [comment]
@mik2 
I have switched to using a hex editor by itself, and Notepad++ for everything else. I strongly suggest everybody else do the same, as there are better hex editors out there.

**Comment by BlackMage2** [comment]
So what happens now with the hex editor in Notepad++?
Is it rejected or further developed?

**Comment by donho** [comment]
Neither Hex-Editor plugin and nor Plugin Manager plugin is part of Notepad++ project.

**Comment by lmstearn** [comment]
There is always hope for this issue, which AFAIK goes back to at least Vista days- here's [another try](https://github.com/chcg/NPP_HexEdit/issues/1#issuecomment-456273490). :)
