### ISSUE TITLE
Feature suggestion: add a command line argument to open a new tab in current npp process

### ISSUE THREAD

**Issue by beqabeqa473** [notepad-plus-plus/notepad-plus-plus#10215]
Hello devs.

Could you please add a commandline argument to open a new tab in current npp process?
It will be good when openning a notepad++ from a shortcut if people need to open npp and start writing.

Thanks.

**Comment by mere-human** [comment]
@beqabeqa473 There is a workaround. Launch Notepad++ with a desired file name for a new document and it will create it. Like this:
`"%ProgramFiles%\Notepad++\notepad++.exe" "new 1.txt"`
![image](https://user-images.githubusercontent.com/9664141/126456150-4d7270ec-47f3-4a08-b44d-0414ad87a562.png)

**Comment by beqabeqa473** [comment]
No, it is not a case.

I don't need to create a file, I need to open a new tab, and then save it with a desired name.

with workarround you are suggesting it is not possible to make a shortcut and just run a npp when it is needed and start writing, because it will open newtext.txt every time.

**Comment by ArkadiuszMichalski** [comment]
In the meantime, you can use a plugin like PythonScript to achieve this.

**Comment by beqabeqa473** [comment]
could you give a reference?

i am not sure, that i cann pass cmdline argument to npp and triger a plugin.

On 7/21/21, ArkadiuszMichalski ***@***.***> wrote:
> In the meantime, you can use a plugin like PythonScript to achieve this.
>
> --
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/notepad-plus-plus/notepad-plus-plus/issues/10215#issuecomment-884066547


-- 
with best regards Beqa Gozalishvili
Tell: +995593454005
Email: ***@***.***
Web: https://gozaltech.org
Skype: beqabeqa473
Telegram: https://t.me/gozaltech
facebook: https://facebook.com/gozaltech
twitter: https://twitter.com/beqabeqa473
Instagram: https://instagram.com/beqa.gozalishvili

**Comment by ArkadiuszMichalski** [comment]
Simillar to this https://github.com/notepad-plus-plus/notepad-plus-plus/issues/9487#issuecomment-871681876. You can pass your arg (like `-newTab`), detect it when NPP is running and open new tab.
http://npppythonscript.sourceforge.net/docs/latest/notepad.html#Notepad.new
http://npppythonscript.sourceforge.net/docs/latest/notepad.html#Notepad.getCommandLine
http://npppythonscript.sourceforge.net/docs/latest/notepad.html#Notepad.menuCommand

On the Notepad++ forum, if you open a new topic, some Python specialist will probably help.

**Comment by donho** [comment]
I consider this issue has been solved by the suggestion  of @ArkadiuszMichalski

**Comment by beqabeqa473** [comment]
Unfortunately no, python script cannot be triggered when npp is already opened, as is the case for me, i am not closing editor and because of not reopenning startup script is not activating, so tab is not openning.

what else can be done to open a new tab from cmdline?
