### ISSUE TITLE
Changing Dark Mode switches the Toolbar Icons

### ISSUE THREAD

**Issue by DMI-1407** [notepad-plus-plus/notepad-plus-plus#10213]
If "Standard Icons: small" is selected and then Dark Mode gets changed _(or enabled)_ the Toolbar Icons are set to "Fluent UI: small" but "Standard Icons: small" is still selected.

### Steps to Reproduce the Issue
1. Disable:  Preferences -> Dark Mode -> Enable Dark Mode
2. Enable:  Preferences -> Dark Mode -> Enable Dark Mode
3. Select:  Preferences -> Dark Mode -> Black tone
4. Select:  Preferences -> General -> Toolbar -> Standard icons: small
5. Select:  Preferences -> Dark Mode -> Red tone

### Expected Behavior
No change in:  Preferences -> General -> Toolbar

### Actual Behavior
Toolbar Icons uses:  Preferences -> General -> Toolbar -> Fluent UI: small
but option is still set to:  Preferences -> General -> Toolbar -> Standard icons: small

### Debug Information
Notepad++ v8.1.2   (32-bit)
Build time : Jul 16 2021 - 01:56:21
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 7 Professional (64-bit) 
OS Build : 7601.0
Current ANSI codepage : 1252
Plugins : none

![ChangingDarkModeSwitchesTheToolbarIcons](https://user-images.githubusercontent.com/53574099/126397160-6b6ece4a-2ebc-43d3-a46e-adcf47dc9157.png)

**Comment by DMI-1407** [comment]
label:bug

**Comment by ArkadiuszMichalski** [comment]
@DMI-1407 You still have this problem in the latest Noptead++?
