### ISSUE TITLE
Docking tabs in high DPI don't look good

### ISSUE THREAD

**Issue by ozone10** [notepad-plus-plus/notepad-plus-plus#10222]
Icons in high DPI don't look good.

![image](https://user-images.githubusercontent.com/55940305/126538057-c0c4f493-0001-4dfd-9985-a1ce396bfcc4.png)

![image](https://user-images.githubusercontent.com/55940305/126538111-4e7b0a9c-f462-4432-8b1b-0b2745dae0ac.png)

**Comment by donho** [comment]
https://github.com/notepad-plus-plus/notepad-plus-plus/commit/3e69de48795ab6a11e4738da3d9b8763347c10f4

**Comment by WildByDesign** [comment]
@ozone10 Thank you for this. This fixed several of the issues that I was having with the docking tab icons that I have been working on over the past few days. My light mode docking tab icons looked like garbage and the dark mode icons were not looking as sharp as they should have displayed. This fix is did a tremendous job at fixing those. Cheers!

By the way, thank you for all of your recent dark mode efforts. Greatly appreciated.
