### ISSUE TITLE
[DarkMode] "Use Windows mode" option

### ISSUE THREAD

**Issue by Majr25** [notepad-plus-plus/notepad-plus-plus#10239]
This option would change between light and dark mode depending on the Windows 10/11 setting.
![image](https://user-images.githubusercontent.com/880296/126885504-87ac74dc-e12c-4151-8f91-0b64c9b847f0.png)

I primarily want this as I use f.lux to automatically enable dark mode at night, but otherwise use light mode during the day. Now that N++ can switch without restarting, it can automatically follow this setting like most of my other apps (and even a lot of websites nowadays!).

Also once dark mode is finalised, this could be enabled by default to automatically use dark mode for users that have already indicated in Windows that they want apps to be dark.

**Comment by japie06** [comment]
Many apps you can set to follow the windows dark/light mode or override them. Would be nice to get a setting to follow system dark/light theme. So I can toggle all my apps to light or dark with a single setting.

**Comment by guneyozsan** [comment]
I'm here to second this. Toggling the whole dev setup centrally is very convenient when adapting different light conditions.

**Comment by piotr-chylarecki** [comment]
This is a step towards automatically toggling Dark mode, which is the ultimate goal of dark mode, for me. I'm using [(https://github.com/AutoDarkMode/Windows-Auto-Night-Mode)] to automate the Windows display mode and have other apps infer it from the system (eg. Chrome).
