### ISSUE TITLE
Notepad v8 - “changing select text foreground color”

### ISSUE THREAD

**Issue by nr1995** [notepad-plus-plus/notepad-plus-plus#10232]
Hi, noob here.
I notice in Notepad++ v8+ that the changelog added,
_“changing select text foreground color”_ .

I've been waiting for this feature for a long time,
but in the Style Configurator things appear no different from v7.

Am I missing something here?
How do I activate/use this option?

**Comment by alankilborn** [comment]
RTFM (Read That Fine Manual) [HERE](https://npp-user-manual.org/docs/config-files/#:~:text=Languages%20doc.-,enableSelectFgColor,-.xml%3A%20this%20is) and if you have further questions please post them [HERE](https://community.notepad-plus-plus.org/), NOT here.

Recommend CLOSURE of this item.
