### ISSUE TITLE
(64-bit NPP 8.1.2) Multi-Line editing on files with more than (about) 1000 lines freeze the program / have terrible performance

### ISSUE THREAD

**Issue by NinjaSciurus** [notepad-plus-plus/notepad-plus-plus#10259]
### Description of the Issue

Using any multi-line editing operation on files with more than a couple of hundred lines take several dozens of seconds to complete and freezes the editor. E.g. selecting 1500 lines that start with multiple whitespace characters and pressing Shift+Tab to remove the indentation of those lines takes about 60 seconds to complete. Another example: using the "edit -> line operations -> remove empty lines" menu item on 3000 lines where every second line is empty also takes about one minute to complete.
There are more examples (sorting lines, removing duplicates) that all boil down to the same symptom of an extremely slow input processing on multiple thousands of text lines (which is the reason I use NPP 64 bit: to quickly edit large files).

There is no lexer active, no language selected.
The behaviour exists on new files as well as on files read from the disk.

### Steps to Reproduce the Issue

1. Open any simple text file with about 1500 lines (or use the attached example: [new 1.txt](https://github.com/notepad-plus-plus/notepad-plus-plus/files/6877605/new.1.txt)).
2. Mark all lines
3. Press [Tab] (or use any other multi-line operation that changes the displayed data)

### Expected Behavior

All marked lines have their indentation increased without any noticeable delay.

### Actual Behavior

The program freezes for about a minute. After about one minute the requested input has been processed and the editor becomes responsive again.

### Debug Information

Notepad++ v8.1.2   (64-bit)
Build time : Jul 16 2021 - 01:59:50
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 10 Enterprise (64-bit) 
OS Version : 2009
OS Build : 19042.746
Current ANSI codepage : 1252
Plugins : ComparePlugin.dll HTMLTag.dll IndentByFold.dll JSMinNPP.dll mimeTools.dll NppConverter.dll NppExec.dll NppExport.dll NppQrCode64.dll OpenSelection.dll XMLTools.dll

**Comment by mere-human** [comment]
Can you try again without plugins?
https://npp-user-manual.org/docs/command-prompt/

**Comment by NinjaSciurus** [comment]
OK, without plugins the performance is normal. Sorry that I forgot to check that beforehand. 🤦‍♂️
I will close the issue if none of the Npp...-Plugins turns out as the culprit.

**Comment by NinjaSciurus** [comment]
None of the Npp-Plugins had a significant impact on the performance of the described multi-line operations. Issue closed.

**Comment by NinjaSciurus** [comment]
FWIW: it's the XML Tools Plugin. I was using version 3.0.3.3. Updating it to 3.1.1.6 solved the issue.
