### ISSUE TITLE
"Save All" actions do not close its dialog first 9 times

### ISSUE THREAD

**Issue by Mafej-maker** [notepad-plus-plus/notepad-plus-plus#10267]
### Description of the Issue

    Notepad++ v8.1 (64bit)
    When you click to "Save All" (CTRL + SHIFT + S) a saving dialog is shown to the user. 
    Then if any action (Save, Cancel, clicking on X) gets pressed, it will only refresh the dialog state, but the action itself will not 
    executed.  
    Clicking on any action 9 more times, will activate it and the lastly pressed action will be executed. 
   

### Steps to Reproduce the Issue

1. Open Notepad++ v8.1, 64 bit, on windows 10
2. Open new file by clicking CTRL + N
3. Start writing some text and click on File --> Save All, or just press CTRL + SHIFT + S
4. Observe the opened dialog. 
5. Try clicking on any action (Save, Cancel, press on X)
6. Observe the screen
7. Try clicking on any action (Save, Cancel, press on X) 9 more times 
8. Observe the screen

### Expected Behavior

After step 6:

The pressed action gets executed i.e Pressing on Save will Save all text entered in the step 3, or click on Cancel button will destroy the dialog

### Actual Behavior

After step 6:
The dialog only gets refreshed and action does not get executed 

After step 8:
Pressing 9 more times on any action gets executed

### Debug Information

Notepad++ v8.1   (64-bit)
Build time : Jun 17 2021 - 01:56:07
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 10 Pro (64-bit) 
OS Version : 2004
OS Build : 19041.1083
Current ANSI codepage : 1252
Plugins : mimeTools.dll NppConverter.dll NppExport.dll

**Comment by donho** [comment]
It's not a bug but a feature.
It's Save As dialog for the prompt file, so if you have 9 new files to save, you will have 9 dialog to respond.
