### ISSUE TITLE
Maitain Indentation

### ISSUE THREAD

**Issue by grungondola** [notepad-plus-plus/notepad-plus-plus#1026]
Found a typo in the preferences window. Where it should say Maintain Indentation it says Maitain Indentation. (v3.9)
![notepad typo](https://cloud.githubusercontent.com/assets/15198565/10582219/cbe09bf6-7654-11e5-872b-f964df57e358.png)

**Comment by dail8859** [comment]
That version is **incredibly** outdated. The most recent version is [v6.8.5](https://notepad-plus-plus.org/news/notepad-6.8.5-released.html)

**Comment by grungondola** [comment]
Wow... I didn't even pay attention to that...
