### ISSUE TITLE
Clone view creates two incompatible copies of the same file

### ISSUE THREAD

**Issue by lmattcris** [notepad-plus-plus/notepad-plus-plus#10266]
### Description of the Issue
Creating the clone of a file in the second view creates a possibly different file in the two views, if changes are added to two views separately. You can't then save any of the two views, without loosing the changes in the other view.
This looks to happen when after cloning you close/reopen the application and make different changes in the left and right views: changes in the right view aren't replicated in the left one and vice versa. Adding many changes you end up with two different versions of the same file, very hard to merge.

### Steps to Reproduce the Issue
1. Open a (long) text file in the main view 
2. Right click on file name tab and "Clone to other view"
3. Make a few changes in **left** pane, you'll see them appear in right pane
4. Make a few changes in **right** pane, still they will be updated in left one
5. **Close** Notepad++ with the main window close button, **without** saving anything
6. Reopen Notepad++, changes are _apparently_ preserved
7. Any change that you'll make from now on on left or right pane won't be replicated in the other one: file name is still the same, but you're working on two different copies (not cloned, not linked anymore)

### Expected Behavior
I just expected that reopening the application the link between the two windows is preserved, while it's not, even though they claim to be the same file on-disk

### Actual Behavior
I ended up with left pane having only the changes made in it, after the restart of the application. The same happens to right pane, and I can't track anymore all the changes as they're logged separately.

### Debug Information
Notepad++ v8.1.1   (32-bit)
Build time : Jul  1 2021 - 14:04:28
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 10 Enterprise (64-bit) 
OS Version : 2009
OS Build : 19043.1110
Current ANSI codepage : 1252
Plugins : mimeTools.dll NppConverter.dll NppExport.dll

**Comment by molsonkiko** [comment]
I encountered this just now on the current master (post-8.5.4). It's a bummer that this hasn't gotten more attention.

While the (*unfortunately numerous*) other bugs with document cloning could reasonably be put on the back burner, this is a __very serious problem__ with cloning that makes it borderline unusable.

I'm inclined to try fixing this myself.

**Comment by molsonkiko** [comment]
A possible fix that occurs to me: add a `hasClone="yes/no"` attribute to the `<File>` elements in `session.xml`.

Essentially, when the current session is being saved, every document that has a clone (which can be checked easily by looking at the `Buffer._referrees` attribute for references to both edit views) will be saved to `session.xml` __only in the first `subView`__ element__ with `hasClone="yes"`. Any documents without a clone would be saved with `hasClone="no"`.

When `session.xml` is loaded on startup, if `hasClone="yes"` for a certain file, clone it into the second edit view.

**Comment by donho** [comment]
The commit https://github.com/notepad-plus-plus/notepad-plus-plus/commit/6f2e5d272c415f83031409bf1d5490920daaa232 has reverted the old commit https://github.com/notepad-plus-plus/notepad-plus-plus/commit/f4297f1a837c93e09962715c40ba932567d46aa2, which was supposed to fix this issue.
Since the old commit has been reverted, this issue is reopened.

I'll take care of this issue personally.
