### ISSUE TITLE
Style token feature no longer works reliably

### ISSUE THREAD

**Issue by WLFoster** [notepad-plus-plus/notepad-plus-plus#10262]
### Description of the Issue
Upgraded to 8.1.2 and tried to use Style Token feature.  Feature did not work for certain selected text.  I reverted back to 7.9.5 and feature now works properly.

### Steps to Reproduce the Issue

1. Select text.
2. Right click text and select "Style token" and a color.
3. Text does not become highlighted as in previous versions.
5. Text like "POST" works fine.  Text like "<space>POST<space>" does not.

### Expected Behavior

Any text selected will be highlighted throughout the document.

### Actual Behavior

Some selected text will not highlight at all.  Some other selected text highlight as normal.

### Debug Information
Notepad++ v8.1.2   (32-bit)
Build time : Jul 16 2021 - 01:56:21
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 10 Enterprise (64-bit) 
OS Version : 1909
OS Build : 18363.1256
Current ANSI codepage : 1252
Plugins : ComparePlugin.dll DSpellCheck.dll mimeTools.dll NppConverter.dll NppExport.dll

**Comment by donho** [comment]
![image](https://user-images.githubusercontent.com/90293/127682932-78e03e70-1f03-4ef6-8692-afcfc2db2bf6.png)
