### ISSUE TITLE
 Win.Trojan.Ramnit-6821 FOUND

### ISSUE THREAD

**Issue by MorenoMonga** [notepad-plus-plus/notepad-plus-plus#1028]
Hi, I installed Notepad++ 6.8.5 but my antivirus [ClamWin] (http://www.clamwin.com/) found one trojan inside it. I don't know if it is a False Positive or a really trojan.

This is the log of antivirus:
> C:\Program Files (x86)\Notepad++\plugins\PluginManager.dll: Win.Trojan.Ramnit-6821 FOUND
> C:\npp.6.8.5.Installer.exe: Win.Trojan.Ramnit-6821 FOUND

And this is the release of antivirus:
*ClamWin Free Antivirus, Engine version: 0.98.7*

Best regards
Moreno

PS: In the Net I found some discussion (without solution) like this:
http://stackoverflow.com/questions/33203373/found-trojan-in-notepad-what-shall-i-do

**Comment by psilos123** [comment]
Hi, Could i ask you something about woowsearchform?
How could i install it on my wordpress site? Can i combine it with custom fields

**Comment by donho** [comment]
I'm sure that is a false alert.
