### ISSUE TITLE
Found Indecent Phrase during Installation

### ISSUE THREAD

**Issue by biplabPati** [notepad-plus-plus/notepad-plus-plus#10282]
### Description of the Issue

Please find the highlighted Text in the attachment
![Notepad++MSG](https://user-images.githubusercontent.com/80506036/127363664-bf9ccec6-da4c-4577-8fc0-bbf403f3964e.PNG)

### Steps to Reproduce the Issue

1. Download Notepad++ 8.1.2 release
2. Start Installation and select "English" language
3. Move setup to till License Agreement as per attachment

**Comment by thomassmith311** [comment]
A large number of such quotes (including that one) can be found in the file Notepad_plus.cpp (notepad-plus-plus-8.1.2/PowerEditor/src) from lines 6890 to 7126, many of which are not appropriate. Not sure why
