### ISSUE TITLE
[Feature Request] - Update window enhancement

### ISSUE THREAD

**Issue by RunninglVlan** [notepad-plus-plus/notepad-plus-plus#10281]
Please mention which _version I’m using right now_ and what is _the version of update package_ in **Notepad++ update** window.
It would really help to know these version numbers, as it would help decide do I want this version or not. For example, someone would like to install only major version updates or only minor version updates, ignoring patch versions.
Right now to find out this information I have to go and open Notepad++ _About_ as well as _the site_ to compare the versions.
Currently I'm just seeing this:
![image](https://user-images.githubusercontent.com/11376741/127327354-ff5767c9-4b9b-45ed-a8f5-cf1e2258b7df.png)

**Comment by RunninglVlan** [comment]
Anyone?

**Comment by mere-human** [comment]
This probably should be in https://github.com/notepad-plus-plus/wingup

**Comment by mr-brunes** [comment]
Agree this would be useful info to display in the update window but when I follow the link to wingup I don't see the issue logged.
Can anyone enlighten me?

**Comment by RunninglVlan** [comment]
Here it is: https://github.com/notepad-plus-plus/wingup/issues/19

**Comment by mr-brunes** [comment]
Great tx. I'm being a dunce but when might this useful change completed in Feb'21 make it into NPP?

**Comment by RunninglVlan** [comment]
It's already in the latest NPP: https://notepad-plus-plus.org/downloads/v8.3.3/
