### ISSUE TITLE
Bug in  CustomFileDialog, when trying to close multiple of them, result in nullptr and crash

### ISSUE THREAD

**Issue by KnIfER** [notepad-plus-plus/notepad-plus-plus#10290]
### Description of the Issue
https://community.notepad-plus-plus.org/topic/21575/bug-when-double-mouse-click-run-button-in-run-a-macro-multiple-times-dialog

### Steps to Reproduce the Issue
1. Open Npp, create a new empty tab, write something in it to make it dirty.
2. In "Run a Macro Multiple Times" dialog, choose `Trailing space and save`, click the "run" btn multiple times.
3. Dismiss the Save-as dialog**s**.

### Expected Behavior
Save-as dialogs are closed one by one

### Actual Behavior
Npp crashed.

### Debug Information
Notepad++ v8.1.2   (64-bit)
Build time : Jul 16 2021 - 01:59:50
Path : D:\Code\FigureOut\Textrument\秘籍\npp.8.0.portable.x64\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : ON
Cloud Config : OFF
OS Name : Windows 10 Home (64-bit) 
OS Version : 2009
OS Build : 19042.1110
Current ANSI codepage : 65001
Plugins : MarkdownText.dll mimeTools.dll MultiClipboard.dll NppConverter.dll NppExport.dll 

### Additional Information

[video by LNT](https://drive.google.com/file/d/1R4pC3m35EgDuymZRcYIp7_s67g8YBL33/view?usp=sharing)

https://github.com/notepad-plus-plus/notepad-plus-plus/blob/fcea83ba988e9f319549d4bdfa64facfe8a7ab0b/PowerEditor/src/WinControls/OpenSaveFileDialog/CustomFileDialog.cpp#L558

```
Exception thrown: read access violation.
FileDialogEventHandler::_staticThis was nullptr.

```

**Comment by mere-human** [comment]
Thanks for report @KnIfER 
Save dialog should be modal. 
It is supposed that it prevents the access to any other dialog while it's shown.
So this should be fixed to disable such a possibility - to show multiple save dialogs at a time.

**Comment by donho** [comment]
@mere-human 
> It is supposed that it prevents the access to any other dialog while it's shown.
So this should be fixed to disable such a possibility - to show multiple save dialogs at a time.

Yes, indeed.

I tested with the old version to make sure the save dialog was the old system:
https://notepad-plus-plus.org/downloads/v7.7.1/

It has the unexpected behaviour but not harmful at all. In my opinion, it's the way to go.
