### ISSUE TITLE
"Save" button shows instead of the "Open" button

### ISSUE THREAD

**Issue by ewwerjeijoejo** [notepad-plus-plus/notepad-plus-plus#10291]
![Capture](https://user-images.githubusercontent.com/88159147/127538973-b7f4ffbc-dd3a-45c5-8f28-2ae7c35f86a8.PNG)

### Steps to Reproduce the Issue
Click the open button

### Debug Information
Notepad++ v8   (64-bit)
Build time : Jun  6 2021 - 18:38:25
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 10 Home (64-bit) 
OS Version : 2009
OS Build : 19043.1110
Current ANSI codepage : 1252
Plugins : mimeTools.dll NppConverter.dll NppExport.dll

**Comment by ArkadiuszMichalski** [comment]
Fixed in Notepad++ 8.1. Next time please follow [How to open a new issue](https://github.com/notepad-plus-plus/notepad-plus-plus/wiki/FAQ#how-to-open-a-new-issue) guidelines before open new issue.
