### ISSUE TITLE
[DarkMode] Windows 11 dialog background issue

### ISSUE THREAD

**Issue by ozone10** [notepad-plus-plus/notepad-plus-plus#10299]
On Windows 11 `WM_CTLCOLORDLG` and theme seem to work differently than on older Windows, 

![image](https://user-images.githubusercontent.com/55940305/127749055-e441b637-4d69-4593-be31-1880f6c6b1bb.png)

Edit:
because of this
https://docs.microsoft.com/en-us/windows/apps/get-started/make-apps-great-for-windows#desktop-apps-win32

**Comment by lilalien** [comment]
Yeah I still get this on the latest version in the dialogs, and on the about box. Looking forward to the fix, its coming along nicely in dark mode!
