### ISSUE TITLE
Refactor plugin-shared code into a separate header

### ISSUE THREAD

**Issue by ariccio** [notepad-plus-plus/notepad-plus-plus#103]
`Git` has a fantastic feature called a `subtree` that uses nested repositories to manage project dependencies.

Before anything, There's lots of good information about it:

- ["Understanding Git Subtree"](https://hpc.uni.lu/blog/2014/understanding-git-subtree/)
- ["Using Git subtrees for repository separation"](https://makingsoftware.wordpress.com/2013/02/16/using-git-subtrees-for-repository-separation/)
- ["Extracting Parts of Git Repository and Keeping the History"](http://ariya.ofilabs.com/2014/07/extracting-parts-of-git-repository-and-keeping-the-history.html)
- ["Using Git subtrees to split a repository"](https://lostechies.com/johnteague/2014/04/04/using-git-subtrees-to-split-a-repository/)

Refactoring some of the headers into a separate repo would make it far easier for plugin developers to build & maintain up to date plugins, as they could update their copy of the headers with a simple git shell command.

I'm not a plugin developer, but as best I can tell, the very minimal headers that a plugin dev needs to include are roughly:

- `Notepad_plus_msgs.h`
- `PluginInterface.h`
- `Scintilla.h`
- `menuCmdID.h`
- `Window.h`
- `Docking.h` (maybe)
- `DockingDlgInterface.h` (maybe)

I came up with this while studying/fixing multiple buffer overruns in HexEdit, which seems to have last updated its copy of the Notepad++ headers in ***~2009***.

**Comment by milipili** [comment]
A n++ SDK would be indeed a good thing to have

**Comment by milipili** [comment]
@donho : could you give me the list of the n++ headers currently required by any plugin ?

**Comment by donho** [comment]
@milipili 
https://github.com/npp-plugins/plugintemplate/blob/master/src/Notepad_plus_msgs.h

**Comment by donho** [comment]
I think we can close this issue because there's only one file is mandatory.
Of course @milipili please reopen it if you judge it's necessary to reopen it.
