### ISSUE TITLE
Still an issue with the naming of files created in new tabs

### ISSUE THREAD

**Issue by Eldaw** [notepad-plus-plus/notepad-plus-plus#1030]
1. Open a fresh instance of Notepad++, with just a single tab, 'new 1'
2. Save the file as 'new 1.txt'
3. Double-click the tab bar to create a second tab.
4. Notice that the new tab gets named 'new 1'.

Surely the automatic numbering system should take into account that there is already a 'new 1' open (even though it's been saved with an extension of .txt), and therefore name the new tab 'new 2'.

**Comment by donho** [comment]
the numbering system takes account into only untitled document. Once you save the document in the disk, it is no more untitled document, therefore the number is available again for numbering system.
It's a standard behaviour.
