### ISSUE TITLE
Doc Switcher -> Document List Panel

### ISSUE THREAD

**Issue by gthb1** [notepad-plus-plus/notepad-plus-plus#10307]
Would be great if someone could fix the Document List Panel
(and work through all related issues listed here):
https://stackoverflow.com/questions/6108193/notepad-show-open-files-on-the-left
https://community.notepad-plus-plus.org/topic/16358/quickly-toggle-doc-switcher-list-panel-on-off

**Comment by mere-human** [comment]
@gthb1 What exactly do you mean?
If it's about a shortcut for Document List, then it will be present in the next version.
![image](https://user-images.githubusercontent.com/9664141/127780084-2de4ac37-26ba-4f18-b67b-c1a4c8ee00e6.png)
![image](https://user-images.githubusercontent.com/9664141/127780076-bb10c937-4830-4283-bcd4-e3bb6b154581.png)
It was implemented in https://github.com/notepad-plus-plus/notepad-plus-plus/issues/9015

If this answers your question, please close the issue.

**Comment by gthb1** [comment]
Awesome, thx :)
