### ISSUE TITLE
[Feature Request] Update Context Menu for Windows 11

### ISSUE THREAD

**Issue by tyranid** [notepad-plus-plus/notepad-plus-plus#10320]
Microsoft have changed the default context menu in Windows 11 (https://blogs.windows.com/blog/2021/07/19/extending-the-context-menu-and-share-dialog-in-windows-11/) and therefore the "Edit with Notepad++" context menu entry is no longer present on the main menu and you need to go to the overflow. 

It'd be nice to be able to get the context menu entry again. Unfortunately it looks like you need a packaged identity to use the Windows 11 menu so you'd need to deploy a manifest with the application, but I guess you have a signing key so it might not be that big an issue. Also maybe it's something to wait for closer to a final release as Microsoft could easily change things if enough people complain.

**Comment by rix1337** [comment]
Their blog is pretty straightforward about this.
The 'new' context menu API has been around since win 7, they are just now enforcing it.

Old context menu is dead, we should integrate into the new one.

**Comment by luoxiao-xy** [comment]
我希望右键单击菜单能够适应 win11。在 Win 11 中，采用了新的右键单击菜单。但是，记事本尚未适应 win11，因此操作菜单（如打开文件）需要切换到旧菜单才能使用。其他应用程序已经在调整新菜单，但记事本尚未。

目前，这个问题对用户体验有很大的影响。希望能先解决。@Ashfaaq18@rimrul

**Comment by jankais3r** [comment]
+1 for this feature.

One of the very few apps I've seen already integrated in the modern context menu is [NanaZip](https://github.com/M2Team/NanaZip). Their context menu handling code is available [here](https://github.com/M2Team/NanaZip/blob/master/NanaZipShellExtension/NanaZipShellExtension.cpp).

**Comment by mortan** [comment]
Is this being worked on at all? Your Windows 11 users would be very happy about that feature! :)

**Comment by ChaosDMNS** [comment]
Would really appreciate it, thank you.. Great work btw.. 

I can change the context menu back to Win10 style. But.. I kinda like it.. was getting very cluttered. So I don't mind the double menu's. BUT... a few programs like Notepad++ and 7-zip I really want on the first page. as I use them so often.. especially notepad++

**Comment by luoxiao-xy** [comment]
Win11 has been released for half a year, and nodepad + + hasn't adapted to it yet.

**Comment by alankilborn** [comment]
@luoxiao-xy There is no adaptation to make.  Context menu support in various versions of Windows is so different that this has become a do-it-yourself type of thing.

**Comment by lilalien** [comment]
I'd still like to see the option to Edit with Notepad++ directly in the windows 11 context menu without having to double-hover or click elsewhere to view it... It's the new way going forward. I do hope you change your mind.

At least in new Windows 11 betas (full release is later this year), they're adding the ability to shift-right-click to immediately get the original longer menu that most developers have already tapped into.

https://www.neowin.net/news/microsoft-makes-context-menus-in-windows-11-a-little-less-confusing/

**Comment by luoxiao-xy** [comment]
> I'd still like to see the option to Edit with Notepad++ directly in the windows 11 context menu without having to double-hover or click elsewhere to view it... It's the new way going forward. I do hope you change your mind.
> 
> At least in new Windows 11 betas (full release is later this year), they're adding the ability to shift-right-click to immediately get the original longer menu that most developers have already tapped into.
> 
> https://www.neowin.net/news/microsoft-makes-context-menus-in-windows-11-a-little-less-confusing/

+1  Edit with Notepad + + is a more convenient way to switch between different editors.

**Comment by m4heshd** [comment]
Anybody looking for this feature can use [ContextMenuForWindows11](https://github.com/ikas-mc/ContextMenuForWindows11) for the moment.

![image](https://user-images.githubusercontent.com/6711514/169665775-64a1131f-dc82-4a41-9747-d397dd51e38e.png)

**Comment by spmsh** [comment]
+1

**Comment by hyoretsu** [comment]
Bumping again, as this is a bummer for Windows 11 users.

**Comment by Kristijan1001** [comment]
Is this that hard to be implemented ?

**Comment by maisondasilva** [comment]
+1

**Comment by P3rf3ctXZer0** [comment]
This is kind of a must.

**Comment by lilalien** [comment]
Please strongly re-consider this.

**Comment by NoahAndrews** [comment]
It's not a matter of "re-consider". As far as I know, no contributor to Notepad++ has chimed in on this issue. I think a bunch of people assumed that @alankilborn was speaking on behalf of the project, when in reality they are not listed on the [contributors page](https://github.com/notepad-plus-plus/notepad-plus-plus/graphs/contributors).

**Comment by alankilborn** [comment]
>I think a bunch of people assumed that @alankilborn was speaking on behalf of the project

Why would anybody think of my comments differently than anyone else's?

>they are not even listed on the contributors page

Good reason for that.  I'm just like everyone else.
(but thanks for giving me a very modern pronoun with the mention)

**Comment by hyoretsu** [comment]
> It's not a matter of "re-consider". As far as I know, no contributor to Notepad++ has chimed in on this issue. I think a bunch of people assumed that @alankilborn was speaking on behalf of the project, when in reality they are not even listed on the [contributors page](https://github.com/notepad-plus-plus/notepad-plus-plus/graphs/contributors).

What do you mean? The guy only posted a single comment here.

**Comment by alankilborn** [comment]
This seems to be an official Notepad++ team response (it is in THEIR user manual after all) to the subject of this issue:
https://npp-user-manual.org/docs/other-resources/#windows-11-right-click-workarounds

**Comment by Kristijan1001** [comment]
> This seems to be an official Notepad++ team response (it is in THEIR user manual after all) to the subject of this issue: https://npp-user-manual.org/docs/other-resources/#windows-11-right-click-workarounds
> 
> The fact that they are going to the trouble to document workarounds leads one to believe that they aren't going to do anything further in this regard.

Why even do this and not implement this in the normal installation. This is just breaking my mind. There is some stubborness happening here.

**Comment by Kissaki** [comment]
> The fact that they are going to the trouble to document workarounds leads one to believe that they aren't going to do anything further in this regard.

Please don’t read more into it than you see. The manual documents a workaround. Nothing more. It especially does not make *any* mention of intention, efforts, plans, or even challenges.

> Why even do this and not implement this in the normal installation. This is just breaking my mind. There is some serious stubborness happening here.

If it is so easy for you, please do implement it and send a PR. I for one looked into how it could be done, and as I expected, did not find a solution with the limited time I was able to invest.

Where do you even interpret this supposed stubbornness from? When there was no mention of intention?

I am sure they have limited time to invest and other stuff to do too. If it bothers you so much, try to fix it, or at least remain respectful to their time and efforts.

**Comment by maisondasilva** [comment]
WinRAR implemented this in Windows 11, I'll leave what the developer sent me who knows might help in some way.

Hello,
I used this one: https://github.com/microsoft/AppModelSamples/tree/master/Samples/SparsePackages
as a sample.
First, you need to implement the shell extension using IExplorerCommand interface. IContextMenu is included only to "Show more options" menu in Windows 11.
Then you need to package this shell extension to .msix file, sign this file with digital signature and install this .msix package from another app.
Overall it is complicated and troublesome. I spent about two months to implement this and still searching for workarounds for some issues.
Eugene

**Comment by Adam-Kay** [comment]
For anyone still wanting this, as a better workaround I'd highly recommend the Custom Context Menu app on the Microsoft Store: https://apps.microsoft.com/store/detail/custom-context-menu/9PC7BZZ28G0X

These are my settings, but they're really mostly default as far as it goes:
![ApplicationFrameHost_Iq82TQ5LfZ](https://user-images.githubusercontent.com/10010491/209724683-65a2bf3f-123c-4bf2-8157-483d6ffeab5e.png)

**Comment by m4heshd** [comment]
> For anyone still wanting this, as a better workaround I'd highly recommend the Custom Context Menu app on the Microsoft Store: https://apps.microsoft.com/store/detail/custom-context-menu/9PC7BZZ28G0X

Literally what I [suggested a few responses ago](https://github.com/notepad-plus-plus/notepad-plus-plus/issues/10320#issuecomment-1133753212). 😁

**Comment by donho** [comment]
Implemented in #13170
3 signed installers (x86, x64 & ARM64) are available for testing in  #13170.
Please provide your feedback in  #13170

**Comment by brz** [comment]
Overriding the "HKEY_CLASSES_ROOT\*\shell\pintohome" registry key is not the correct way to integrate with the Windows 11 context menu. It basically gets rid of the "Pin to Quick Access" context menu item.

**Comment by maisondasilva** [comment]
It would be nice to put Open With or add a new entry below

![image](https://user-images.githubusercontent.com/11423362/223146230-9276bd23-9ed8-4fbb-92e4-839feeced7f8.png)

https://blogs.windows.com/windowsdeveloper/2021/07/19/extending-the-context-menu-and-share-dialog-in-windows-11/

**Comment by m4heshd** [comment]
> It would be nice to put Open With or add a new entry below

![image](https://user-images.githubusercontent.com/6711514/223187517-2143aa28-11dc-4d8d-904d-7747838c6c66.png)

🤷🏽‍♂️

**Comment by NoahAndrews** [comment]
Thank you for implementing this!

**Comment by m4heshd** [comment]
> I am suggesting this as native without using third party programs

I know, but this is one of those rare moments where a third-party tool is a much sound option. This way, the context menu doesn't get polluted. That's why the new menu was introduced in the first place. I have the following menu items set up for directories.

![image](https://user-images.githubusercontent.com/6711514/223195725-ef96f763-12a1-46b5-ab50-687911ad3d1b.png)

Now imagine having all these as individual items on the new menu. This wouldn't be the end of it either with my use case. It would both pollute the UI and destroy the performance. These menu items are cached by the way. Practically no impact on the performance.

**Comment by dieck** [comment]
> For example, my previous PC had a Windows installation I kept clean and running since the day I bought it (5 years ago). The context menu was so polluted by random stuff that it would sometimes ramp up the CPU and freeze up or crash the Explorer just by opening up the context menu.

And you really think that hiding it in a submenu would only load on demand?
Will just be loaded anyway, and only shown if needed.

I would *really* prefer a solution where the user can decide what to have on first level of menu. 
As someone stated above, things like 7zip or Notepad++ I am using that often, that (for me!) it's a real nuisance to work through submenus, and that is why I always re-enabled the old Win10 style menu on Win11, on every single machine I touch.

**Comment by m4heshd** [comment]
> And you really think that hiding it in a submenu would only load on demand?
> Will just be loaded anyway, and only shown if needed.

Hiding? 🤣 The "submenu" is provided by a single application and it's cached by that application. Wayyyyy better performance. You should really do your own tests and research on that before firing out a conclusion because I've done my tests and I prefer to have a much better-performing, unpolluted context menu where I have the freedom of customization on every level. Simple as that.

**Comment by Maeldor** [comment]
> Overriding the "HKEY_CLASSES_ROOT*\shell\pintohome" registry key is not the correct way to integrate with the Windows 11 context menu. It basically gets rid of the "Pin to Quick Access" context menu item.

Is this why I'm seeing the pin icon instead of the Notepad++ icon?
![image](https://user-images.githubusercontent.com/4951049/223388491-2b3814bc-a779-4b85-ab58-95167faff72e.png)

Had to completely uninstall Notepad++ to get rid of it, which also removed it from the old menu, and now don't see a "Pin to Quick Access" option at all 😞

**Comment by brz** [comment]
> > Overriding the "HKEY_CLASSES_ROOT*\shell\pintohome" registry key is not the correct way to integrate with the Windows 11 context menu. It basically gets rid of the "Pin to Quick Access" context menu item.
> 
> Is this why I'm seeing the pin icon instead of the Notepad++ icon? ![image](https://user-images.githubusercontent.com/4951049/223388491-2b3814bc-a779-4b85-ab58-95167faff72e.png)
> 
> Had to completely uninstall Notepad++ to get rid of it, which also removed it from the old menu, and now don't see a "Pin to Quick Access" option at all 😞

Yes that is the reason indeed.

**Comment by donho** [comment]
@brz 
> Overriding the "HKEY_CLASSES_ROOT*\shell\pintohome" registry key is not the correct way to integrate with the Windows 11 context menu. It basically gets rid of the "Pin to Quick Access" context menu item.

If `HKEY_CLASSES_ROOT*\shell\pintohome` is taken, nothing will be written into this entry by installer and it will be kept untouched.

**Comment by FadeMind** [comment]
@donho in default key in `HKEY_CLASSES_ROOT\*\shell\pintohome` does not exists.

_Pin to Quick access_ button is handled here

```
HKEY_CLASSES_ROOT\AllFilesystemObjects\shell\pintohome
HKEY_CLASSES_ROOT\Drive\shell\pintohome
HKEY_CLASSES_ROOT\Folder\shell\pintohome
HKEY_CLASSES_ROOT\Network\shell\pintohome
```

Reference https://www.elevenforum.com/t/add-or-remove-pin-to-quick-access-context-menu-in-windows-11.2807/

Regards
