### ISSUE TITLE
Server connection issues

### ISSUE THREAD

**Issue by jorge-viramontes** [notepad-plus-plus/notepad-plus-plus#1032]
When I connect to a particular server, I am getting the following error:

An exception occurred: (first of the window popup has this last word misspelled - "occured")
Code: 0xC0000005
Type: Access violation
Exception address: 0x76A843F9

Now, to avoid this problem I have to access another server where I am not getting such error and then connect to this one.

**Comment by donho** [comment]
With what you connect to a particular server?

**Comment by jorge-viramontes** [comment]
Using Notepad++

Jorge Viramontes
Hewlett-Packard Enterprise
PA TMSIS PROMISe™

Email:   jorge.viramontes@hpe.com<mailto:jorge.viramontes@hpe.com>
Lync:     +1.915.600.1629
Mobile: +1.915.277.3868


        [cid:image002.png@01D10BD8.26B71830]

**Comment by jorge-viramontes** [comment]
When I try to connect to one of the servers (say server a) in the “profile settings” window.
In order to be able to do this, I need to connect to another server (say b) first, then server a.
If I try to connect to server a first, I received the error message included in this email.

This is what I have in the profile settings:
The ip address, port 22, connection type SFTP


Thank you.


Jorge Viramontes
Hewlett-Packard Enterprise
PA TMSIS PROMISe™

Email:   jorge.viramontes@hpe.com<mailto:jorge.viramontes@hpe.com>
Lync:     +1.915.600.1629
Mobile: +1.915.277.3868


        [cid:image003.png@01D10BED.85DB1FE0]


From: Viramontes, Jorge
Sent: Wednesday, October 21, 2015 8:12 AM
To: notepad-plus-plus/notepad-plus-plus
Cc: Viramontes, Jorge
Subject: RE: [notepad-plus-plus] Server connection issues (#1032)

Using Notepad++

Jorge Viramontes
Hewlett-Packard Enterprise
PA TMSIS PROMISe™

Email:   jorge.viramontes@hpe.com<mailto:jorge.viramontes@hpe.com>
Lync:     +1.915.600.1629
Mobile: +1.915.277.3868


        [cid:image004.png@01D10BED.85DB1FE0]

**Comment by dail8859** [comment]
NppFTP plugin related.
