### ISSUE TITLE
The show more icon in tool bar is not clearly visible in dark mode

### ISSUE THREAD

**Issue by shockergit** [notepad-plus-plus/notepad-plus-plus#10325]
![Screenshot 2021-08-04 164813](https://user-images.githubusercontent.com/63154802/128172569-bd476369-d810-4b7c-90e7-36d11d9d3f36.png)

**Comment by ozone10** [comment]
maybe duplicate of https://github.com/notepad-plus-plus/notepad-plus-plus/issues/10103
