### ISSUE TITLE
notepad++ support OS MAC

### ISSUE THREAD

**Issue by aaawuanjun** [notepad-plus-plus/notepad-plus-plus#10324]
### Description of the Issue
I use MacBook Pro, I didn't see the support os of mac, is it in the plan to build a mac version?

**Comment by aaawuanjun** [comment]
My mac info is below:
Mac OS Big Sur: 11.4
MacBook Pro(15-inch, 2019)
处理器： 2.6Ghz Intel Core i7

so it is intel X86 cpu, I dont know the key point of the code if it is, if it support different cpu arch or not.
can you guys in the plan to deploy a version of mac?

**Comment by mere-human** [comment]
There is no plan to do it in the future.
Developers are focused on stabilizing/improving the Windows version.

**Comment by aaawuanjun** [comment]
ok, I think as an excellent software, it can not be limited to windows, ^_^

**Comment by ArkadiuszMichalski** [comment]
https://github.com/notepad-plus-plus/notepad-plus-plus/wiki/FAQ#support-for-systems-other-than-the-ms-windows-family
