### ISSUE TITLE
'Find Previous' does not work with latest version (8.1.2) via hotkey or menu

### ISSUE THREAD

**Issue by dmorse76** [notepad-plus-plus/notepad-plus-plus#10333]
### Description of the Issue
Search / Find Previous does not work with latest version (8.1.2) via hotkey or menu.  I have tried both Windows x86 and x64 versions of Notepad++.

### Steps to Reproduce the Issue
1. Find a string where there are multiple instances (via Ctrl+F), and go to the second or third instance
2. Try to 'Find Previous' via either Search / Find Previous in the menu bar, or the hotkey (Shift+F3)
3. Nothing happens in Step 2 (whereas it should jump back to the previous string instance).

### Expected Behavior
The cursor should have moved to the previous instance of the string

### Actual Behavior
Nothing

### Debug Information
Notepad++ v8.1.2   (64-bit)
Build time : Jul 16 2021 - 01:59:50
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 10 Pro (64-bit) 
OS Version : 1809
OS Build : 17763.737
Current ANSI codepage : 1252
Plugins : mimeTools.dll NppConverter.dll NppExport.dll

**Comment by ArkadiuszMichalski** [comment]
Works correct for me. Maybe try with portable to eliminate configs problem: https://github.com/notepad-plus-plus/notepad-plus-plus/wiki/Testing#using-the-latest-release-portable-version-of-notepad.

**Comment by dmorse76** [comment]
@ArkadiuszMichalski Thanks for the suggestion - portable did not show the issue.  I checked my configs and I could not find a conflict in shortcuts.xml for Shift+F3, but clearly something in my configs caused the problem.

I deleted %AppData%\Notepad++, reinstalled the standard version, and Find Previous works as expected now.  Closing this issue.

**Comment by PascalRiekenberg** [comment]
-noPlugin does not solve the issue. Will try to delete %AppData%\Notepad++ and reinstall Notepad++
