### ISSUE TITLE
Disapearing search window when using regular expressions

### ISSUE THREAD

**Issue by AV-86** [notepad-plus-plus/notepad-plus-plus#10344]
### Steps to Reproduce the Issue

1. open search window with ctrl+f
2. switch to tab "search in files"
3. check "regular expressions" radio button
4. provide regular expression (i.e. "digitalWrite\((.*?),.*?LOW.*?\)")
4. provide path to folder
5. provide filter *.cpp *.h *.hpp
6. click "find all" button
### Expected Behavior

results of search is in lower window, search window stays open
### Actual Behavior
when no results of search, actual behavior is same as expected behavior:
results of search in lower window (with no results), search window stays open

when there is search results, results of search is in lower window, search window disapears.
when calling it again with ctrl+f search criteria drops to that was when prewious susseful search (without disappearing serch window) was.

### Debug Information

Notepad++ v8.1.2   (64-bit)
Build time : Jul 16 2021 - 01:59:50
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 10 Pro (64-bit) 
OS Version : 2009
OS Build : 19043.1110
Current ANSI codepage : 1251
Plugins : mimeTools.dll NppConverter.dll NppExport.dll

**Comment by ArkadiuszMichalski** [comment]
Have you tried this option?
![image](https://user-images.githubusercontent.com/2730894/128500893-eef5fca2-07e7-40f0-8a73-428e37a2b42d.png)

**Comment by AV-86** [comment]
All fine! Sorry for publishing issue. This setting changes behaivor to expected. Thanks!
