### ISSUE TITLE
[DarkMode] Static text color issue

### ISSUE THREAD

**Issue by ozone10** [notepad-plus-plus/notepad-plus-plus#10357]
from https://community.notepad-plus-plus.org/post/68671

Disabled static labels don't look good in dark mode.
![image](https://user-images.githubusercontent.com/55940305/128636939-4ba5b487-a64d-4536-8811-002334173431.png)

This is how it is implemented in Windows.
Solution would be to not disable it in dark mode and handle color with `WM_CTLCOLORSTATIC`.

@donho 
I could look into it, but it won't be soon, maybe in next week.

**Comment by donho** [comment]
> This is how it is implemented in Windows.
Solution would be to not disable it in dark mode and handle color with WM_CTLCOLORSTATIC.

It's not worth to make code more complex because of this small visual glitch.

> I could look into it, but it won't be soon, maybe in next week.

Please don't bother for this issue (which is not an issue.
