### ISSUE TITLE
Search -> Find can't handle newline escapes such as \n

### ISSUE THREAD

**Issue by LOuroboros** [notepad-plus-plus/notepad-plus-plus#10352]
### Description of the Issue
I'm trying to find a text string in a project that is written in one single line, and Notepad++ cannot find it due to its usage of `\n`.

### Steps to Reproduce the Issue

1. Write a few lines of text such as:
- Test
- 2Test
- Test\ntest
2. Without actively highlighting anything, go to Search -> Find, set Search Mode to Extended, and search for `Test\ntest`.

### Expected Behavior
I expected the string to be found.

### Actual Behavior
Notepad++ couldn't find the string.

### Debug Information
Notepad++ v8.1.2   (32-bit)
Build time : Jul 16 2021 - 01:56:21
Path : D:\Nico\Portable Programs\npp.7.8.9.bin\notepad++.exe
Command Line : 
Admin mode : ON
Local Conf mode : ON
Cloud Config : OFF
OS Name : Windows 10 Enterprise (64-bit) 
OS Version : 2004
OS Build : 19041.388
Current ANSI codepage : 1252
Plugins : ComparePlugin.dll CustomLineNumbers.dll mimeTools.dll NppConverter.dll NppExport.dll 

![notepad++_334](https://user-images.githubusercontent.com/4485172/128616557-9951c1f8-f3ef-41db-a110-f08e1ab96442.png)

**Comment by ivan-u7n** [comment]
I don't see a problem. Either use `test\\ntest` as a search string in the Extended Search mode or switch to the Normal one.

**Comment by LOuroboros** [comment]
> use `test\\ntest` as a search string in the Extended Search mode

Ah, thank you for your reply. I just didn't know I had to do that. I'll proceed to close this non-issue then.
