### ISSUE TITLE
Window Menu and Dialog: Some Thoughts

### ISSUE THREAD

**Issue by Yaron10** [notepad-plus-plus/notepad-plus-plus#10354]
**1.** Why should the Window **menu** display tabs from the current view only in _double-view_ mode?

**2.** Why do we need the Window **dialog** at all? - What does it offer that the Documents List doesn't?
- Copy **All** Names/Paths can (and should IMO) be under `Edit -> Copy To Clipboard`.
- Copy **Selected** Names/Paths can be implemented in the Documents List.
- Number of tabs can be shown under the Window **menu**: a separator after the list and then "Total: X" (disabled).
(The informative disabled entry might be a bit unconventional, but certainly more convenient). 
- "Sort by" can also be shown under the Window **menu**.

@mere-human,
Thank you for your major contribution.
What do you think?

***

Notepad++ v8.1.2.

**Comment by mere-human** [comment]
> **1.** Why should the Window **menu** display tabs from the current view only in _double-view_ mode?

No idea.



> **2.** Why do we need the Window **dialog** at all?

Maybe, just for historical reasons. 
It was a common thing for Windows MDI programs. Like this:
![1275729](https://user-images.githubusercontent.com/9664141/128767235-8e02afea-fbf0-4c3c-b6cf-e2aa224ee93f.png)

Some other programs have this kind of menu too.  For example, Visual Studio:
![image](https://user-images.githubusercontent.com/9664141/128765927-db4fceae-4b8f-4694-8204-9e71fd1be5e2.png)
But in Visual Studio, it has more functionality. For example, layout presets, document groups, etc.
Also, as you can see, there's no separate dialog. Documents are listed in the menu.


> * Copy **All** Names/Paths can (and should IMO) be under `Edit -> Copy To Clipboard`.
> * Copy **Selected** Names/Paths can be implemented in the Documents List.

This all could be done from within the Document List.
1st is only a particular case for 2nd where the selection contains all the documents.
This could be in the context menu:
![image](https://user-images.githubusercontent.com/9664141/128766545-4ac31e7c-a743-4f6a-a53a-f0fa5d99fb35.png)
We can add 2 menu items there (copy names/pathnames).

> * Number of tabs can be shown under the Window **menu**: a separator after the list and then "Total: X" (disabled).

I don't agree. Menu entries should bring some actions. It's better to use static labels for informational purposes.
I can imagine a small status-bar-like label in the bottom of the Document List, for example.


> * "Sort by" can also be shown under the Window **menu**.

Yes, it could be there.

---

I mostly agree with you @Yaron10. 
However, it's always better to ensure we're on the same page with Don before doing something.

**Comment by Yaron10** [comment]
@mere-human,

Thank you for the detailed reply. I appreciate it.

I'd like to emphasize that my suggestion was to remove the Window **dialog** only. 
The Window **menu** is useful and important.

>  1. Why should the Window menu display tabs from the current view only in double-view mode?
>> No idea.

If you frequently use the double-view mode, you would surely want to see documents from both views in the list.
Also - your recent useful addition "Copy Names/Paths" is relevant to the current view only.
(That new feature prompted me to open this issue).

> We can add 2 menu items there (copy names/pathnames).

That's what I had in mind.

> Copy All Names/Paths can (and should IMO) be under Edit -> Copy To Clipboard.
   Copy Selected Names/Paths can be implemented in the Documents List.
>> 1st is only a particular case for 2nd where the selection contains all the documents.

This can be debated. 
If "Copy Names/Paths" is important (and I think it is), the user might expect to see "Copy **All** Names/Paths" under `Edit -> Copy To Clipboard`.
But I see your point.

> I can imagine a small status-bar-like label in the bottom of the Document List, for example.

Or in the Document List title bar.

One more point:
If the Window **dialog** is removed, "Documents List" can replace the current "Window..." **menu item**.

***
> However, it's always better to ensure we're on the same page with Don before doing something.

Most certainly. I wanted it to be "more baked" first.

@donho,
We would appreciate your opinion.

Regards.

***

@dail8859,
I'm glad you agree.

Regards.

**Comment by Yaron10** [comment]
@donho,

Thanks for replying.
Thank you also for your ongoing work. Much appreciated.

I'll update my suggestion in accordance with @mere-human's comments, and try to make it clearer.

***
**Option A.**
**Remove the Window dialog and move its functionalities to more approachable/convenient places.**

**1.** The Window **menu** should look as follows:
- List of open documents from *both views*.
-------------------- (separator).
- `Sort by` (popup).
--- `Name` (menu item)
--- `Path` (menu item)
--- `Type` (menu item)
--- `Size` (menu item)
-------------------- (separator).
`Documents List` (menu item - open/activate the `Documents List`. NOT toggle)

**2.** The number of open documents (from *both views*) should be displayed in the `Documents List` *title bar*.

**3.** `Copy Names/Paths` in the `Documents List` context-menu.

***

**Option B.**
**Keep the Window dialog and the current Window menu.**

**1.** Both Window menu and dialog should display open documents from *both views*.

**2.** The number of open documents in the Window dialog should reflect *both views*.

**3.** `Copy Names/Paths` in the `Documents List` context-menu.

***

I think that option **A** is much better: the user should get all the current functionalities without the extra duplicate Window dialog.
As you understand.

***

@mere-human,

This entire discussion is based on the assumption that you should be kindly willing to implement it. :)
Is that OK?

Thank you.

**Comment by donho** [comment]
For me, "Nice to have" features:
1. Implement  `Copy All Names/Paths` under Edit -> Copy To Clipboard.
2. Implement `Copy Selected Names/Paths` in the Documents List context-menu.

And let's keep the current state, since people are using Window dialog.

**Comment by Yaron10** [comment]
And displaying open documents from both views in Window?

**Comment by mere-human** [comment]
> This entire discussion is based on the assumption that you should be kindly willing to implement it. :)
> Is that OK?

Sure, I can work on it when I have free time.
I prefer option A with the assumption that the Window dialog is kept untouched (as Don mentioned above).
Maybe, there will be some implementation adjustments.

**Comment by Yaron10** [comment]
@mere-human,

👍 
Great.
Thank you. I do appreciate it.

**Comment by donho** [comment]
> And displaying open documents from both views in Window?

No. Please keep the current behaviour in Window Menu/dialog.

> I prefer option A with the assumption that the Window dialog is kept untouched (as Don mentioned above).

Yes,  Window dialog should be kept untouched.

> Sort by (popup).
--- Name (menu item)
--- Path (menu item)
--- Type (menu item)
--- Size (menu item)

No context menu for sorting please, since columns are available for sorting.
Adding more columns (path and size) could make Document List Panel more complex for using. So I won't consider it for the moment. 

> The number of open documents (from both views) should be displayed in the Documents List title bar.

Not considering for the moment.

Once again, "Nice to have" features that I think acceptable for the moment are:

1.  Implement Copy All Names/Paths under Edit -> Copy To Clipboard.
2. Implement Copy Selected Names/Paths in the Documents List context-menu.

It's not reasonable to me to redo both Window dialog and Document list.

**Comment by Yaron10** [comment]
@mere-human,

:+1: :+1: 
Already implemented or just an illustration? :)

**Comment by mere-human** [comment]
> @mere-human,
> 
> 👍 👍
> Already implemented or just an illustration? :)

No, just a mockup in Visual Studioю

**Comment by donho** [comment]
I'm quite confused by this feature request...
So is it for Document list or for Window menu/dialog ?

**Comment by mere-human** [comment]
> I'm quite confused by this feature request...
> So is it for Document list or for Window menu/dialog ?

There are several essential parts:
1. Adding new copy path commands (Document List & Edit menu).
2. Extending Window menu with the new items.
3. Showing both views for the case when Clone to Other View was called.
4. Adding document number (Document List).

I sorted them in the descending order of importance (as for me).

Maybe, we need separate issues for these items.

**Comment by donho** [comment]
> Maybe, we need separate issues for these items.

Yes, please.
