### ISSUE TITLE
Shortcut mapper / Macros tab shows garbled/cropped text in status area

### ISSUE THREAD

**Issue by artie-finkelstein** [notepad-plus-plus/notepad-plus-plus#10358]
### Description of the Issue
Text displayed in the "Shortcut mapper" status area (e.g., "No shortcut conflicts for this item.") only shows a few of the pixels of the bottom of the string but with most of the string shifted up past the top of the proper display area.

### Steps to Reproduce the Issue
1.  Npp 8.13rc or Npp 8.13rc2
2. click on \Macro\Modify Shortcut/Delete Macro...
3. 

### Expected Behavior
I expected to be able to read the text (see attached file "macro-good status.png") 

### Actual Behavior
I got the results show in the attached file "macro-bad status.png

### Debug Information
Notepad++ v8.1.3   (32-bit)
Build time : Aug  8 2021 - 13:17:47
Path : C:\Programs\Notepad++\notepad++_8.13rc2.exe
Command Line : 
Admin mode : ON
Local Conf mode : ON
Cloud Config : OFF
OS Name : Windows 7 Professional (64-bit) 
OS Build : 7601.0
Current ANSI codepage : 1252
Plugins : none

This cropping does not occur with 8.12 or earlier releases.  It's only visible under 8.13rc & 8.13rc2 and shows up when '\Macro\Modify Shortcut/Delete Macro...' is used to initially display the 'Shortcut mapper' menu.  This cropping can also show up on the 'Plugin commands' tab, and may then show up on other tabs if they are selected after 'Plugin commands'.  (For this portion of testing I obviously had plugins enabled.)
```
Plugins : BetterMultiSelection.dll ColumnTools.dll CustomLineNumbers.dll DSpellCheck.dll Explorer.dll ExtSettings.dll FallingBricks.dll FingerText.dll Linefilter3.dll LuaScript.dll MarkdownViewerPlusPlus.dll MenuIcons.dll mimeTools.dll NavigateTo.dll NppCalc.dll NppColumnSort.dll NppEditorConfig.dll NppEventExec.dll NppExec.dll NppFavorites.dll NppHorizontalRuler.dll NPPJSONViewer.dll NppJumpList.dll NppMenuSearch.dll NppQCP.dll NppSnippets.dll NppTextFX.dll NppTextViz.dll NppUISpy.dll OpenFileInFolders.dll pork2sausage.dll PreviewHTML.dll PythonScript.dll QuickText.dll selectNLaunch.dll ZoomDisabler.dll _CustomizeToolbar.dll 
```
The 'Scintilla commands' and 'Run commands' tabs seem to be immune to this cropping.  If 'Main menu' is infected it can't be removed short of closing the entire dialog box, whereas 'Macros' can usually be temporarily "uninfected" by selecting 'Run commands' before going back to 'Macros'.  The 'Main menu' tab infection also has a slightly different view, see attached file "main-bad status.png"

![macro-good status](https://user-images.githubusercontent.com/28426654/128649182-442a3ed5-695d-454c-a672-2651cf584211.png)
![macro-bad status](https://user-images.githubusercontent.com/28426654/128649180-ae841000-8017-4d28-a553-863914a6cf05.png)
![main-bad status](https://user-images.githubusercontent.com/28426654/128649320-198c0169-462b-418b-99ab-a562b00254b4.png)

**Comment by ArkadiuszMichalski** [comment]
I can't reproduce this, at least in the standard theme in system.
![image](https://user-images.githubusercontent.com/2730894/129009604-3c933d1e-39ff-46b5-bd5b-66814699c93a.png)

**Comment by artie-finkelstein** [comment]
Unfortunately, I can, even after a system reboot will all shortcuts in
Startup moved to an alternate folder and using a newly extracted .7z
portable copy of Npp 8.13rc2.  In other words, I made the Win7 Pro SP1
system as bare as I could and the Npp as new and plain as I could.
Heck, I even tried 'dark mode'.

Note: During testing with DaveW for his CustomizeToolbar plugin v5.1,
we did notice that Npp startup is a bit different between Win7 and
Win10 systems (he's on 10, I'm on 7).

Any suggestions to further isolate things?

Notepad++ v8.1.3   (32-bit)
Build time : Aug  8 2021 - 13:17:47
Path : C:\Programs\npp.8.1.3_rc2.portable\notepad++.exe
Command Line :
Admin mode : ON
Local Conf mode : ON
Cloud Config : OFF
OS Name : Windows 7 Professional (64-bit)
OS Build : 7601.0
Current ANSI codepage : 1252
Plugins : mimeTools.dll NppConverter.dll NppExport.dll

**Comment by Yaron10** [comment]
STR (Steps To Reproduce):

Open the "Shortcut Mapper".
Resize the window vertically *from the bottom*.

Result:

At some point, the status is not fully visible.
(Both Win 7 and Win 10).

![תמונה](https://user-images.githubusercontent.com/10229320/129183189-1ccbd3a2-de0f-4ff2-898a-666def14a956.png)

***

@artie-finkelstein,

I'm also using the Classic Theme on Win 7.

I understand you encounter the problem without resizing.
Can you please list your *exact STR with a fresh portable NPP*?

**Comment by artie-finkelstein** [comment]
Sure, but it hasn't changed.

1) Extract npp.8.1.3_rc3.portable.7z to npp.8.1.3_rc3.portable (I
added the rc3 to keep them separate)
2) double click on notepad++.exe
3) click on '\Macro\Modify Shortcut/Delete Macro...' menu
4) take screen snapshot (see attached)

Notepad++ v8.1.3   (32-bit)
Build time : Aug 10 2021 - 00:32:53
Path : H:\software\Windows\Notepad++\Notepad++
v8\npp.8.1.3_rc3.portable\notepad++.exe
Command Line :
Admin mode : ON
Local Conf mode : ON
Cloud Config : OFF
OS Name : Windows 7 Professional (64-bit)
OS Build : 7601.0
Current ANSI codepage : 1252
Plugins : mimeTools.dll NppConverter.dll NppExport.dll

Nothing new, added or extra required. Open the menu, it's garbled.
Actually, it looks like the text has been scrolled up almost out of
sight (the scroll bar on the right of the status area does not respond
when clicked on, scrolling the one line in the 'Name Shortcut' area
has no effect on the garble either).

**Comment by mere-human** [comment]
I was able to reproduce the issue using these steps:

> Open the "Shortcut Mapper".
> Resize the window vertically _from the bottom_.

After resize:
![image](https://user-images.githubusercontent.com/9664141/129227299-e1cdc27d-376b-4964-b188-4a943b772f25.png)

Sometimes looks good:
![image](https://user-images.githubusercontent.com/9664141/129227534-d7503a65-b48b-4dbf-bcee-e79dcdc9bce6.png)


I'm not sure if it's the same issue or not.

```
Notepad++ v8.1.2   (32-bit)
Build time : Aug  1 2021 - 16:44:44
Path : ...\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : ON
Cloud Config : OFF
OS Name : Windows 10 Enterprise (64-bit) 
OS Version : 2009
OS Build : 19043.1110
Current ANSI codepage : 1252
Plugins : none

```

**Comment by Yaron10** [comment]
@mere-human,

Thank you for confirming.
This issue is reproducible with older NPP vesions.

@ArkadiuszMichalski,

Thank you.

I can reproduce your issue on Win 7 with Windows Classic Theme.
The cause is commit https://github.com/notepad-plus-plus/notepad-plus-plus/commit/934c9888742510d75d3830c4151394fa0e0b1f0c.

**Comment by artie-finkelstein** [comment]
I've never tried resizing the mapper window.  If I do, there is a
correlation between how much of the last row of text in the upper area
(Name, Shortcut) has been virtually covered and how much of the status
text is left visible.  [Virtually covered: the lines in the upper area
are only displayed in full increments, but if the bottom of the mapper
window is moved up only 1/2 the height of the upper  area line, the
effect on the status line is 1/2].  If I move the bottom of the window
up or down slowly I can change the amount of garbled text left
showing, and every upper area row height increment results in properly
displayed status text.  If I move very slowly, I can see the full text
of the status line faintly while the  window image is painted.  I
can't find a resting spot (window size) that ever leaves the status
text complete when displaying the 'Macro' tab (with only one line in
the upper area), but I can in tabs with many lines in the upper area.

It's almost as if floating point math was being used and not being
truncated to whole integers.  I'm not saying this is the problem, I'm
saying it looks like it IF you could do the sizing calculation in
floating point and then didn't truncate.

I tried with the 'Plugin commands' tab and got a variation of the
above behavior.  If I size the mapper window large enough to display
empty space under the text lines of the upper area, then the status
area looks garbled, but if I slowly resize the window smaller, then I
go through the garbled/clear phases as the size is slowly reduced.

Sorry, it took me awhile to figure out what your 'after resize' image
was showing.  I can reproduce it, see attached picture.  If I increase
the window size just a bit I can get rid of the garble (if I don't go
too far)

Looks like we are seeing the same issue.

**Comment by ozone10** [comment]
This seems to be issue with resizing "babygrid"
https://github.com/notepad-plus-plus/notepad-plus-plus/blob/9a3152faa287c98cfe8e4776cb678f7853707d13/PowerEditor/src/WinControls/Grid/BabyGrid.cpp#L2986
