### ISSUE TITLE
Thin gray outline surrounding the text editor since v8.1.3 RC

### ISSUE THREAD

**Issue by monkyyx** [notepad-plus-plus/notepad-plus-plus#10362]
### Description of the Issue

Since v8.1.3 RC1/RC2 there is a thin gray outline surrounding the text editor. Is this intentional or will there be an option to disable it? I haven't found anything related in the settings.
### Steps to Reproduce the Issue

1. Install v8.1.3 RC1 or RC2
2. Enable Dark Mode
### Expected Behavior

No gray outline or an option to disable it
### Actual Behavior

There is a gray outline
### Debug Information

Notepad++ v8.1.3   (64-bit)
Build time : Aug  8 2021 - 13:33:02
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 10 Pro (64-bit) 
OS Version : 2009
OS Build : 19043.1110
Current ANSI codepage : 1252
Plugins : mimeTools.dll NppConverter.dll NppExport.dll 

![npp](https://user-images.githubusercontent.com/88665772/128713190-3239a497-f028-4f64-b83f-317ffd74f170.png)

**Comment by ozone10** [comment]
@monkyyx 
use this setting
![image](https://user-images.githubusercontent.com/55940305/129401577-3af30485-e79c-4435-bad3-4b139bd340e4.png)

**Comment by monkyyx** [comment]
@ozone10 
Thank you!
