### ISSUE TITLE
File extension not displayed in the Windows jump list

### ISSUE THREAD

**Issue by egvijayanand** [notepad-plus-plus/notepad-plus-plus#10360]
### Description of the Issue

In v8.1.2, the file extension is not getting displayed in the Windows jump list

### Steps to Reproduce the Issue

1. Open and close any file in Notepad++ v8.1.2
2. Then try to access that file from the Windows jump list, only the filename is displayed there, the file extension is missing
3. It is difficult to manage in scenarios where source files having similar names but differs by extension

### Expected Behavior

The file list should contain both the filename and its extension.

### Actual Behavior

Filename without extension is getting displayed.

### Debug Information

Notepad++ v8.1.2   (32-bit)
Build time : Jul 16 2021 - 01:56:21
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 10 Home (64-bit) 
OS Version : 2009
OS Build : 22000.120
Current ANSI codepage : 1252
Plugins : CSScriptNpp.dll DSpellCheck.dll MarkdownViewerPlusPlus.dll mimeTools.dll NppConverter.dll NppEditorConfig.dll NppExport.dll NPPJSONViewer.dll NppSaveAsAdmin.dll PoorMansTSqlFormatterNppPlugin.dll XMLTools.dll 

![Npp-Issue](https://user-images.githubusercontent.com/81947404/128707601-b3f68fbd-4a77-47c5-85c4-951129671d43.png)

**Comment by dail8859** [comment]
This is controlled by Windows Explorer, not Notepad++. You need to configure Explorer to [show file extensions].(https://fileinfo.com/help/windows_10_show_file_extensions)
