### ISSUE TITLE
Please add a tick mark if the pluggin is activated

### ISSUE THREAD

**Issue by shockergit** [notepad-plus-plus/notepad-plus-plus#10377]
![Screenshot 2021-08-12 214948](https://user-images.githubusercontent.com/63154802/129232412-a733dc9e-3561-4855-86c9-1c17dc5a548b.png)

**Comment by artie-finkelstein** [comment]
@shockergit 
It does.  I think you may need to adjust your theme colors.  On my setup (no dark mode, no themes, standard button icons) the check mark appears to be shown in the same color as the chevron you clicked on to display the list of buttons no longer visible on the toolbar.
![2021-08-13_214517](https://user-images.githubusercontent.com/28426654/129432072-b8ee5728-8642-4ca4-a73a-fe9961b5f67b.png)

**Comment by ozone10** [comment]
@artie-finkelstein 
chevron and tick mark use different color

This is not because of dark mode, it is also not showing in light mode

**Comment by shockergit** [comment]
> 
> 
> @shockergit
> It does. I think you may need to adjust your theme colors. On my setup (no dark mode, no themes, standard button icons) the check mark appears to be shown in the same color as the chevron you clicked on to display the list of buttons no longer visible on the toolbar.
> ![2021-08-13_214517](https://user-images.githubusercontent.com/28426654/129432072-b8ee5728-8642-4ca4-a73a-fe9961b5f67b.png)

![Screenshot 2021-08-15 142355](https://user-images.githubusercontent.com/63154802/129472891-69786311-5d44-41e6-9618-2551dd70254c.png)
I just tried without dark mode, and It still doesn't work. Are you on Windows 10?

**Comment by artie-finkelstein** [comment]
I'm using Win7 Pro 64 bit, w Npp 8.13 32 bit. I also use Customize Toolbar 5.2 which does affect this issue.  With CT installed, tick marks ARE displayed:
![std, w- CT](https://user-images.githubusercontent.com/28426654/129486018-4f513e85-54ba-4427-a2cc-f4824aea70a4.jpg)

but keeping when CT hidden, there are NO tick marks displayed:
![std, no CT](https://user-images.githubusercontent.com/28426654/129486021-2757b6ec-cc21-4018-b295-cbb379426026.jpg)

In both situations the 'active' buttons are the plugin DSpellCheck ('Spell Check Document Automatically') and Npp's 'Word Wrap' and  'Show Indent Guide' options.  This case is also true if Fluent buttons are used.  I did not investigate 'dark mode' as I had already proved myself to have been wrong in my earlier comment.

My apologies for the misdirection.  But note:  a user could use the Customize Toolbar plugin to remedy the OP's situation if the Npp developers do not add the tick mark feature.

**Comment by shockergit** [comment]
> 
> 
> I'm using Win7 Pro 64 bit, w Npp 8.13 32 bit. I also use Customize Toolbar 5.2 which does affect this issue. With CT installed, tick marks ARE displayed:
> ![std, w- CT](https://user-images.githubusercontent.com/28426654/129486018-4f513e85-54ba-4427-a2cc-f4824aea70a4.jpg)
> 
> but keeping when CT hidden, there are NO tick marks displayed:
> ![std, no CT](https://user-images.githubusercontent.com/28426654/129486021-2757b6ec-cc21-4018-b295-cbb379426026.jpg)
> 
> In both situations the 'active' buttons are the plugin DSpellCheck ('Spell Check Document Automatically') and Npp's 'Word Wrap' and 'Show Indent Guide' options. This case is also true if Fluent buttons are used. I did not investigate 'dark mode' as I had already proved myself to have been wrong in my earlier comment.
> 
> My apologies for the misdirection. But note: a user could use the Customize Toolbar plugin to remedy the OP's situation if the Npp developers do not add the tick mark feature.

Thank you so much, the customized toolbar worked. Now the tick is showing, and I can remove unnecessary icons.
![Screenshot 2021-08-16 114121](https://user-images.githubusercontent.com/63154802/129519000-ef0b649c-469f-4102-9b5a-32c11beb8a18.png)
