### ISSUE TITLE
Invalid Syntax Highlighting

### ISSUE THREAD

**Issue by MrMyth** [notepad-plus-plus/notepad-plus-plus#10376]
Good afternoon. Below is a screenshot where you can see that the program is giving incorrect syntax highlighting. How can I fix this problem? I cannot write code otherwise. It is the program settings that need to be corrected.
![Clipboard 1](https://user-images.githubusercontent.com/20878728/129185272-b1ff8a2a-9c61-4fe5-8b4d-cb7393306547.jpg)

**Comment by dail8859** [comment]
The syntax highlighting is working properly since you are [escaping the quotes](https://en.wikipedia.org/wiki/Escape_sequences_in_C#Table_of_escape_sequences) (i.e. you are using `\"`).
