### ISSUE TITLE
Issue with dialogs window border

### ISSUE THREAD

**Issue by ozone10** [notepad-plus-plus/notepad-plus-plus#10384]
Notepad++ v8.13 (and older) on Windows 10 has issue with border for dialogs.
For example when in light mode with default theme, it is hard to distinguish where dialog ends and where editor is.
![image](https://user-images.githubusercontent.com/55940305/129469733-4e8167ff-7ca0-41b0-a0dd-027cc5b0d98c.png)

I think there was similar issue, but I cannot find it.

**Comment by mere-human** [comment]
For me it is showing a thin shadow around the dialog.
![image](https://user-images.githubusercontent.com/9664141/129470335-1a2a06a0-617b-408d-8c41-2325567025e2.png)

**Comment by ozone10** [comment]
@mere-human 
It depends on windows setting
![image](https://user-images.githubusercontent.com/55940305/129470398-01c17165-852c-4e34-b1f3-fb9408a6eb61.png)

**Comment by donho** [comment]
![image](https://user-images.githubusercontent.com/90293/129488472-a54c6ce3-40bc-471d-844a-f51e3831b952.png)

👍

**Comment by donho** [comment]
![image](https://user-images.githubusercontent.com/90293/129488501-bb56705d-9973-4ddd-9bb0-0463f9358bb9.png)

👍

**Comment by rddim** [comment]
https://github.com/notepad-plus-plus/notepad-plus-plus/issues/3508
