### ISSUE TITLE
"Remember current session for next launch" is not honored after reboot

### ISSUE THREAD

**Issue by INRIX-Mark-Gershaft** [notepad-plus-plus/notepad-plus-plus#10380]
### Remember current session for next launch is not honored after reboot
After some recent update (currently 8.1.2) the setting "Remember current session for next launch" is not always honored. It seems that when I close Notepad++ myself it is working, but when it is closed by Windows Update it is not.

As a result tabs disappear.

**Comment by donho** [comment]
Fix by https://github.com/notepad-plus-plus/notepad-plus-plus/commit/6000f3bb21a42a4d28d068617e0dc642ef739b26
