### ISSUE TITLE
NPP RTL: file wrongly saved without an extension.

### ISSUE THREAD

**Issue by Yaron10** [notepad-plus-plus/notepad-plus-plus#10397]
**STR:**
Windows RTL + NPP RTL.
Open a new file and press Save.
Append Extension is checked and the "Save As Type" field contains "Normal Text File (*.txt)".
In the "File Name" field replace "New X.txt" with "Test" (without .txt).
Save.

**Result:**
"Test" is saved without an extension.

**Expected:**
"Test" should be saved as "Test.txt".
This is the result in MS-Notepad and some other programs I've tried.
It also used to be the behavior in older Notepad++ versions.

***

Notepad++ v8.1.3   (32-bit)
Build time : Aug 10 2021 - 00:32:53
Path : C:\\notepad++ Original.exe
Command Line : 
Admin mode : ON
Local Conf mode : ON
Cloud Config : OFF
OS Name : Windows 10 Enterprise (64-bit) 
OS Version : 2009
OS Build : 19042.985
Current ANSI codepage : 1255
Plugins : ComparePlus.dll HTMLTag_unicode.dll MenuIcons.dll PythonScript.dll _CustomizeToolbar.dll

**Comment by mere-human** [comment]
I was also able to reproduce the problem locally.
Here is a short video demonstrating the problem:

https://user-images.githubusercontent.com/9664141/129677244-e989e13f-c870-4dc1-827d-e2da63b5d084.mp4


I'd like to work on this issue.
