### ISSUE TITLE
Wrong default folder in Open/Save dialog

### ISSUE THREAD

**Issue by Yaron10** [notepad-plus-plus/notepad-plus-plus#10396]
**STR:**
Settings -> Preferences -> Default Directory.
Check the third RadioButton and in the EditBox enter "C:\Users\UserName\Downloads".
Close NPP.

Restart NPP (New 1, no session).
Open a file located in any folder other than Downloads.
Settings -> Preferences -> Default Directory.
Check "Follow current document".
File -> Open (or Save As).

**Result:**
Downloads is the default folder in the dialog.
***

Notepad++ v8.1.3.
The issue existed in older NPP versions as well.

**Comment by mere-human** [comment]
I'd like to work on this one.

**Comment by donho** [comment]
Is it a regression?

**Comment by mere-human** [comment]
> Is it a regression?

Even if it is a regression, it's not from something that was done recently.
The same issue is present in 7.9.1 but not in 6.2.3.
