### ISSUE TITLE
Show open documents from both views in Window

### ISSUE THREAD

**Issue by Yaron10** [notepad-plus-plus/notepad-plus-plus#10392]
**STR:**
Open two files: A and B.
Right-click B's tab and "Move to Other View".
Menu -> Window.

**Result:**
Only B is on the list of currently open documents.

**Expected:**
Displaying the open documents should enable the user to quickly navigate between tabs.
This may be even _more important_ if you you have multiple files open in two views.

Thank you.

***

Notepad++ v8.1.3.

**Comment by mere-human** [comment]
I'd like to work on this one.

**Comment by donho** [comment]
@Yaron10 There are Window menu & Window dialog.
Which one are you talking about?

**Comment by Yaron10** [comment]
Both Window menu & Window dialog.

**Comment by donho** [comment]
@mere-human 
Will there be a lot of code to do?

**Comment by mere-human** [comment]
> Will there be a lot of code to do?

@donho 
I'm not sure. Probably not. I've not started yet.
Why do you ask?

**Comment by donho** [comment]
Because I'm not sure it's interesting to enhance Window dialog since it's for the legacy Windows' MDI.
And maybe for some users they need the current behaviour.

**Comment by Yaron10** [comment]
Removing the Window dialog would reduce the code quite significantly. :)

On a serious note: the Compare plugin is very popular and it uses the double-view mode.
Displaying open documents from one view only is contrary to the basic purpose and existence of the Window **menu**.

**Comment by donho** [comment]
@Yaron10 
> Removing the Window dialog would reduce the code quite significantly. :)

Personally I don't use Window dialog at all. If I remove this part, there'll be a lot of users crying, shouting and insulting me. So I would like to keep it as Windows legacy feature for the per-historic users and not evolve it anymore.
If we need the new features, we can add them into Document List - that's a fair enough policy I believe.

**Comment by Yaron10** [comment]
@donho,

> So I would like to keep it as Windows legacy feature for the per-historic users and not evolve it anymore.

I can understand that.

Would you like to have both views displayed in the **Window menu only**? 
Or should I close this issue? 

Thank you.

**Comment by mere-human** [comment]
> Would you like to have both views displayed in the **Window menu only**?

For me, it makes sense to do at least this.

**Comment by Yaron10** [comment]
@mere-human,

Thank you.

**Comment by Yaron10** [comment]
@mere-human,

I've implemented it for my personal use. The code changes are minor.
If and when you get back to this issue, it might save you some time. :)

Best regards.
