### ISSUE TITLE
Copy Names/Paths in Edit and Documents list

### ISSUE THREAD

**Issue by Yaron10** [notepad-plus-plus/notepad-plus-plus#10394]
**Suggestion:**
Add `Copy All Names/Paths` commands to `Edit -> Copy To Clipboard`.
Add `Copy Selected Names/Paths` commands to the Documents List context-menu.

Thank you.
***

Notepad++ v8.1.3.

**Comment by mere-human** [comment]
I'd like to work on this one.

**Comment by donho** [comment]
> Add Copy All Names/Paths commands to Edit -> Copy To Clipboard.

@mere-human @Yaron10 if the above command is implemented in `Edit -> Copy To Clipboard menu`, should we remove it from Window dialog context menu?

**Comment by mere-human** [comment]
> if the above command is implemented in `Edit -> Copy To Clipboard menu`, should we remove it from Window dialog context menu?

@donho I don't think we should restrict users. Somebody used to Window dialog, the other one is used to Document List.
Besides, Window dialog allows copying paths from the selection.
![image](https://user-images.githubusercontent.com/9664141/129980205-c401b28b-4f93-49b4-8c27-6e9e2aec3c8e.png)
Result:
```
new 1
new 3
new 5
```
