### ISSUE TITLE
CSS lexer’s support for conditional group rules

### ISSUE THREAD

**Issue by vsl7** [notepad-plus-plus/notepad-plus-plus#10423]
Of CSS conditional group rules (at-rules that can include nested statements), the CSS lexer supports only the `@media` rule. The rules `@supports`, `@document`, `@-moz-document` and possible others should also be supported. See also #3858.

**Comment by mere-human** [comment]
Does it work in SciTE?
https://www.scintilla.org/SciTE.html

**Comment by vsl7** [comment]
@mere-human No.

**Comment by mere-human** [comment]
> @mere-human No.

Then you should report your feature request to Scintilla. This is the component that is used for syntax highlighting in Notepad++.

**Comment by vsl7** [comment]
@mere-human I know it is a Scintilla bug and reported them too: https://sourceforge.net/p/scintilla/bugs/2276/

**Comment by ArkadiuszMichalski** [comment]
Fixed by https://github.com/notepad-plus-plus/notepad-plus-plus/commit/a61b03ea8887e21c6e1b7374068962f635b79b80.
