### ISSUE TITLE
Sort Lexographically Ascending: Bad Allocation

### ISSUE THREAD

**Issue by stevemk14ebr** [notepad-plus-plus/notepad-plus-plus#10435]
### Description of the Issue
With a sufficiently large text file (1.5 million lines of sha256 hashes, 64 characters each), line operation sort lexographically ascending will 100% of the time fail with a bad allocation warning and then notepad++ will crash with a data loss warning.

### Steps to Reproduce the Issue
1. Open Big file
2. Sort
3. Don't Profit

### Expected Behavior
Sorting to not crash

### Actual Behavior
Crash

### Debug Information
Notepad++ v8.1.1   (32-bit)
Build time : Jul  1 2021 - 14:04:28
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Command Line : "\\wsl$\Debian\home\steve\source\repos\Flareup2\utility_scripts\sha256.txt"
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 10 Enterprise (64-bit) 
OS Version : 2009
OS Build : 19043.1165
Current ANSI codepage : 1252
Plugins : ComparePlugin.dll mimeTools.dll NppConverter.dll NppExport.dll NPPJSONViewer.dll NppTextFX.dll

**Comment by felix-22** [comment]
I can reproduce in both `7.9.5` and `8.1.3`.
It does not crash if a file contains less than about `1 151 500` lines, once a file exceeds the limit, it will crash and N++ will close itself:
![1](https://user-images.githubusercontent.com/75935068/130586700-a5e2e158-464e-4be8-a8ae-e76cf12c3b37.png)
![2](https://user-images.githubusercontent.com/75935068/130586740-ce7051e1-0561-446c-8ca9-ffb574f697c2.png)
![3](https://user-images.githubusercontent.com/75935068/130586748-4e53c312-11ae-40a6-9cc4-ca426fff8219.png)

<hr>

There is no crash when using alternativiely  `TextFX > TextFX Tools > Sort ascending`.

**Comment by felix-22** [comment]
@chcg I've seen you attaching "performance" labels like there: https://github.com/notepad-plus-plus/notepad-plus-plus/issues/9791, what about "crash" label for issues where N++ crashes?

**Comment by mshingote** [comment]
Sharing some observations for discussion.

In following file there one virtual function `sort` which takes collection of lines as a copy.
_...notepad-plus-plus\PowerEditor\src\MISC\Common\Sorters.h:74_
`virtual std::vector<generic_string> sort(std::vector<generic_string> lines) = 0;`

One sorting case from following file
_...notepad-plus-plus\PowerEditor\src\ScintillaComponent\ScintillaEditView.cpp_

```
std::vector<generic_string> splitText = stringSplit(text, getEOLString());
...
const std::vector<generic_string> sortedText = pSort->sort(splitText);
```
Lines are passed as a copy for sorting, seems there is room for memory allocation optimization by referencing existing list of lines.

I may be wrong as I'm not fully aware of end to end flow.
