### ISSUE TITLE
Feature request - change default CTRL+F behavior

### ISSUE THREAD

**Issue by pm-inspire-dev** [notepad-plus-plus/notepad-plus-plus#10430]
### Description of the Issue
Feature request is about changing the default dialog search to modern instant search.

### Steps to Reproduce the Issue
Press CTRL+F 

### Expected Behavior
The shortcut CTRL + F should open "instant search" bar by default, instead of Dialog-based Searching dialog. Alternatively, it should be possible to change this behavior.

### Actual Behavior
The shortcut CTRL + F opens the Dialog-based Searching dialog

**Comment by mere-human** [comment]
Just change the shortcut if you want to:
![image](https://user-images.githubusercontent.com/9664141/130368226-54c6cb6c-4564-4302-a7e8-ec5097f7e74d.png)

Don't try to persuade the other users of Notepad++ to use different shortcuts.

**Comment by ArkadiuszMichalski** [comment]
@pm-inspire-dev 
You can do this as suggested above.
