### ISSUE TITLE
BUG with commit 68d293e - crash when open file

### ISSUE THREAD

**Issue by vinsworldcom** [notepad-plus-plus/notepad-plus-plus#10454]
### Description of the Issue
Using the commit 68d293e , when using File => Open and opening a file, Notepad++ crashes.  The previous commit (e12b161) does not exhibit this behavior leading me to believe the bug was introduced in the 68d293e commit.

Based on the [discussion](https://github.com/notepad-plus-plus/notepad-plus-plus/commit/68d293e7118a761aa4b6bc81fa934851480a950a#commitcomment-55542338) it may be related to #10206 since the 68d293e commit changes this value [from 30 to 38](https://github.com/notepad-plus-plus/notepad-plus-plus/commit/68d293e7118a761aa4b6bc81fa934851480a950a#diff-11356ce8679f14c3c38f087779b0625511031cdef2dab261d775c8a40af1866c).

### Steps to Reproduce the Issue

1. Download the AppVeyor Notepad++ artifact (I used 64-bit Release) for commit 68d293e 
2. Open Notepad++
3. Use File => Open and select a file to open, press the "Open" button
4. File does not open, Notepad++ crashes.

### Debug Information
Notepad++ v8.1.4   (64-bit)
Build time : Aug 25 2021 - 23:17:29
Path : C:\usr\bin\npp64\notepad++.exe
Command Line : -noPlugin
Admin mode : OFF
Local Conf mode : ON
Cloud Config : OFF
OS Name : Windows 10 Enterprise (64-bit) 
OS Version : 1909
OS Build : 18363.1734
Current ANSI codepage : 1252
Plugins : none

Windows 10, 64-bit, system-wide dark mode
Using a [custom theme](https://gist.github.com/vinsworldcom/71bba70153fc978818bf00863989b2ea) in Notepad++ (based on Obsidian), **NOT** using Notepad++ dark mode.

**Comment by donho** [comment]
I reduce the value of `SCE_STYLE_ARRAY_SIZE` from 38 to 33 - the value **33** won't cause the crash. 34 and 34+ made Notepad++ crash while opening any file.
I keep investigating this issue.

**Comment by ivan-u7n** [comment]
The strangest thing is that the mingw32 build doesn't crash even if I increase SCE_STYLE_ARRAY_SIZE to 50.

**Comment by ivan-u7n** [comment]
Although it did crash when I set `SCE_STYLE_ARRAY_SIZE` to 99.

However I think I found the culprit: `LexerStylerArray` contains a `MAX_LEXER_STYLE`-element array (currently `100`) of `LexerStyler` objects. Every one of them in turn via inheritance from `StyleArray` contains a `SCE_STYLE_ARRAY_SIZE`-element array (I tested with 99) of `Style` objects each at least 56 bytes in size. This in my test case requires over 550k of memory, and if `LexerStylerArray` is allocated on stack, the stack becomes corrupted.

As a solution here the small patch switching to `std::vector`:
```patch
--- Parameters.h~original       2021-08-29 10:42:04.000000000 +0300
+++ Parameters.h        2021-08-31 00:33:30.480601600 +0300
@@ -530,7 +530,7 @@
        }

 protected:
-       Style _styleArray[SCE_STYLE_ARRAY_SIZE];
+       std::vector<Style> _styleArray = std::vector<Style>(SCE_STYLE_ARRAY_SIZE);
        int _nbStyler = 0;
 };

@@ -618,7 +618,7 @@
        void addLexerStyler(const TCHAR *lexerName, const TCHAR *lexerDesc, const TCHAR *lexerUserExt, TiXmlNode *lexerNode);
        void eraseAll();
 private :
-       LexerStyler _lexerStylerArray[MAX_LEXER_STYLE];
+       std::vector<LexerStyler> _lexerStylerArray = std::vector<LexerStyler>(MAX_LEXER_STYLE);
        int _nbLexerStyler;
 };

```
It then will allow this (it is compiled with `SCE_STYLE_ARRAY_SIZE` set to 99, but I got tired adding more entries): 
![image](https://user-images.githubusercontent.com/81974034/131411116-5165517d-654c-42b2-b58a-49a930d807a5.png)

For the completeness sake the debug info:
```
Notepad++ v8.1.4   (64-bit)
Build time : Aug 31 2021 - 00:34:15
Built with : GCC 10.2.0
Path : F:\develop\notepad-plus-plus-master\PowerEditor\bin\NotepadPP-release.exe
Command Line : -multiInst
Admin mode : OFF
Local Conf mode : ON
Cloud Config : OFF
OS Name : Windows 10 Enterprise LTSC 2019 (64-bit) 
OS Version : 1809
OS Build : 17763.2114
Current ANSI codepage : 1251
Plugins : none
```

**Comment by ivan-u7n** [comment]
Oh, by the way I think the addition of the compiler used and its version in the Debug Info in case of non-MSVC build is a must:
```patch
--- AboutDlg.cpp~original       2021-08-25 07:38:42.000000000 +0300
+++ AboutDlg.cpp        2021-08-30 23:12:32.939552900 +0300
@@ -155,6 +155,16 @@
                        _debugInfoStr += buildTime;
                        _debugInfoStr += TEXT("\r\n");

+#if defined __GNUC__
+                       _debugInfoStr += TEXT("Built with : GCC ");
+                       _debugInfoStr += wmc.char2wchar(__VERSION__, CP_ACP);
+                       _debugInfoStr += TEXT("\r\n");
+#elif defined __clang__
+                       _debugInfoStr += TEXT("Built with : clang ");
+                       _debugInfoStr += wmc.char2wchar(__VERSION__, CP_ACP);
+                       _debugInfoStr += TEXT("\r\n");
+#endif
+
                        // Binary path
                        _debugInfoStr += TEXT("Path : ");
                        TCHAR nppFullPath[MAX_PATH];
```
However, the branch for `clang` isn't tested.

**Comment by donho** [comment]
@ivan-u7n  
> However I think I found the culprit: `LexerStylerArray` contains a `MAX_LEXER_STYLE`-element array (currently `100`) of `LexerStyler` objects. Every one of them in turn via inheritance from `StyleArray` contains a `SCE_STYLE_ARRAY_SIZE`-element array (I tested with 99) of `Style` objects each at least 56 bytes in size. This in my test case requires over 550k of memory, and if `LexerStylerArray` is allocated on stack, the stack becomes corrupted.

Bravo! Your solution fix the problem.
However, std::vector of LexerStyler contains also the base object Style in which the size increased as well. Why the stack has the enough room for the vector? Or the vector memory management in stack is used outside of stack?

**Comment by donho** [comment]
> However, the branch for clang isn't tested.

@chcg can the current makefile build build by using clang ?

**Comment by ivan-u7n** [comment]
@donho 
> Bravo! Your solution fix the problem.
> However, std::vector of LexerStyler contains also the base object Style in which the size increased as well. Why the stack has the enough room for the vector? Or the vector memory management in stack is used outside of stack?

The latter. Inline arrays are a part of an object and increase its size while `std::vector` uses memory from the heap and stores internally only a pointer to a chunk of memory, thus the size of an object with a vector is substantially smaller than the one with an inline array.

**Comment by vinsworldcom** [comment]
@donho , @ivan-u7n - just tested 88ee2ed and it works for me!  Thanks!

**Comment by chcg** [comment]
@donho llvm/clang is available by appveyor, but I'm not sure it could be used for our case as windows specific header files are just available with mingw. I will have a closer look at that.

**Comment by ivan-u7n** [comment]
@donho I don't think https://github.com/notepad-plus-plus/notepad-plus-plus/commit/88ee2eddb043193a1162957a862394dfa620781a fixes https://github.com/notepad-plus-plus/notepad-plus-plus/issues/10206 as the limit is now 31 instead of required in the feature request 50.

I added clang to Debug Info because it was mentioned in https://github.com/notepad-plus-plus/notepad-plus-plus/issues/10185 that Notepad++ can be build with it.

**Comment by donho** [comment]
@ivan-u7n 
For the moment I'll include only:
```
#if defined __GNUC__
                       _debugInfoStr += TEXT("Built with : GCC ");
                       _debugInfoStr += wmc.char2wchar(__VERSION__, CP_ACP);
                       _debugInfoStr += TEXT("\r\n");
#endif
```

**Comment by donho** [comment]
@ivan-u7n 
>  I don't think [88ee2ed](https://github.com/notepad-plus-plus/notepad-plus-plus/commit/88ee2eddb043193a1162957a862394dfa620781a) fixes #10206 as the limit is now 31 instead of required in the feature request 50.

Yes, the crash has been fixed since I've adapted your solution and I've tested by increasing the count of vector to 50 and no crash. However I keep the value 31 for not increasing all the lexerStyler's size. This value will be increased each time we add new global styler.

**Comment by ivan-u7n** [comment]
@donho
> For the moment I'll include only:

I'm fine with it, however I'd rather add a catch-all `#elif`:
```
#if defined(__GNUC__)
                       _debugInfoStr += TEXT("Built with : GCC ");
                       _debugInfoStr += wmc.char2wchar(__VERSION__, CP_ACP);
                       _debugInfoStr += TEXT("\r\n");
#elif !defined(_MSC_VER)
                       _debugInfoStr += TEXT("Built with : (unknown)\r\n");
#endif
```

**Comment by ivan-u7n** [comment]
@donho 
> Yes, the crash has been fixed since I've adapted your solution and I've tested by increasing the count of vector to 50 and no crash. However I keep the value 31 for not increasing all the lexerStylers' size. This value will be increased each time we add new global styler.

Hmm, the dynamic nature of `std::vector` should allow not to put any limit on the number of `Style`s and `LexerStyler`s. I'll look into it.

**Comment by donho** [comment]
> the dynamic nature of `std::vector` should allow not to put any limit on the number of `Style`s and `LexerStyler`s. I'll look into it.

The design decision uses StyleID as index so 30 is a reasonable number (of stylers) and not all of them are used.
I don't want to change such implementation so I think let's keep it as it now.

BTW, the non-MSC info is added: https://github.com/notepad-plus-plus/notepad-plus-plus/commit/dab02db976758f34c7c10ad9df627533a7697d95

**Comment by chcg** [comment]
@donho  See https://ci.appveyor.com/project/chcg/notepad-plus-plus/builds/40621216 about initial tests on appveyor with a LLVM/clang build from the mingw makefile. See also https://stackoverflow.com/questions/39871656/how-to-use-clang-with-mingw-w64-headers-on-windows, seems clang is used in msvc mode. Therefore probably the warnings about the usage of unsecure versions of e.g. strcpy. Linking still fails as the msvc libs are not found and maybe the link command need to be adapted for clang

So it seems to be feasible to achieve a build with clang.

@ozone10 With which configuration did you build with clang?

**Comment by ozone10** [comment]
@chcg 
I've used clang from VS2019 (Platform toolset)
![image](https://user-images.githubusercontent.com/55940305/131859836-2316d340-af93-4e47-b762-c73b41376569.png)

and disabled "Treat Warnings As Errors"
![image](https://user-images.githubusercontent.com/55940305/131859998-a66246ee-0412-4809-901c-321413381164.png)

**Comment by donho** [comment]
https://github.com/notepad-plus-plus/notepad-plus-plus/commit/e9cf428388fc4e7f927b269be081d5876abb9963

**Comment by ivan-u7n** [comment]
I'll try to give it another look. This one at least causes with a GCC-built binary a crash if I set SCE_STYLE_ARRAY_SIZE high enough.

**Comment by donho** [comment]
it's crazy, once I change from array to vector, by applying only 2 lines:
```
       std::vector<Style> _styleArray = std::vector<Style>(SCE_STYLE_ARRAY_SIZE);
...
...
       std::vector<LexerStyler> _lexerStylerArray = std::vector<LexerStyler>(MAX_LEXER_STYLE);
```

The find dialog's display mess up!

![image](https://user-images.githubusercontent.com/90293/132531930-52c42d43-fc8c-4e2d-8d2d-977af4d6efcf.png)

**Comment by ivan-u7n** [comment]
@donho can you try changing only the second line? I mean convert `_lexerStylerArray` to a vector, but leave `_styleArray` as an array.

**Comment by donho** [comment]
@ivan-u7n 
> @donho can you try changing only the second line? I mean convert `_lexerStylerArray` to a vector, but leave `_styleArray` as an array.

Hmm... It seems both bugs (open file crash via open dialog & Find dialog display issue) are fixed in both x64 & x86 release binaries. However, I'm afraid to have other side effects.
What & why that makes difference? Any idea?

**Comment by ivan-u7n** [comment]
@donho I really have no idea. The only thing it means, `LexerStylerArray` is not the culprit. But the wierd things going on with `StyleArray` should be investigated.

As it turned out the 32-bit GCC binary doesn't crash even if `SCE_STYLE_ARRAY_SIZE` is set to 99. The 32-bit MSC-compiled binary doesn't crash with `SCE_STYLE_ARRAY_SIZE` set to 38. So it seems the object size does matter.

Aha, the main bad guy was found: `Notepad_plus_Window` created on the stack in `wWinMain()`. `gdb` refused to show me its content (or inline in it `Notepad_plus`) claiming it's under 2MB of size. I created #10524 to see how MSC reacts to it.

However with the PR above applied GCC build starts exhibiting the same Find dialog glitch as MSC ones if I convert `_styleArray` from an array to a vector. I can finally try to debug it!

**Comment by ivan-u7n** [comment]
@donho I found the other culprit: uninitialized class member variable (https://github.com/ivan-u7n/notepad-plus-plus/commit/31c3bdb3ea0cfe8735cd5869052a63e878d47232). The PR #10524 now reverts what you reverted and adds the fix to the Find dialog `FindReplaceDlg` class.
