### ISSUE TITLE
Alt+Tab Causes Notepad++ To Crash

### ISSUE THREAD

**Issue by CaptainCyril** [notepad-plus-plus/notepad-plus-plus#1045]
Hi,

I noticed when I click on save and quickly do an Alt_Tab to switch to the browser, Notepad++ is crashing. When I launch Notepad++ again, the contents of the page that was last saved are gone and I have bring the file back from backup in Roaming/Notepad++ folder in AppData.

**Comment by dail8859** [comment]
Does this happen consistently for you? I can't reproduce this. Try following [these steps](https://github.com/notepad-plus-plus/notepad-plus-plus/blob/master/CONTRIBUTING.md#reporting-issues) in the CONTRIBUTING.md

**Comment by CaptainCyril** [comment]
Thanks for the suggestions. I removed most of the plugins.

It is happening quite often however I am unable to reproduce it.

I have Windows Vista. Latest version of Notepad++. It always happens when I am editing a PHP page that is running under WAMP inside FireFox. It consistently happens when I save the file, press Alt+Tab to switch to FireFox.

I have another laptop running Windows 7 with less plugins and it is not happening there at all.

**Comment by ariccio** [comment]
Try it with [Application Verifier](http://blogs.technet.com/b/askperf/archive/2009/05/22/two-minute-drill-application-verifier.aspx).

If you have WinDbg, that'll make it even easier.

**Comment by CaptainCyril** [comment]
I have removed most of the plugins. Now I am left with Compare, JSON Viewer and Speech. I am unable to remove Python Indent. After I removed plugin "Explorer" Notepad++ became smoother. However, I am not sure if that was the problem.

**Comment by ariccio** [comment]
> I am unable to remove Python Indent.

Eh? Is it fighting back?

**Comment by CaptainCyril** [comment]
I clicked on it and then Remove and it is always in the Updates. It's not in the menu anymore and almost every day it updates itself.

**Comment by MetaChuh** [comment]
not reproducible.

please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins.
if your issue still persists, and it is still of relevance to you, please feel free to file a new issue as detailed and reproducible as possible.

thank you for your help and best regards.

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)

**Comment by CaptainCyril** [comment]
I am sorry that I did not close this question. It happened to me so many times and I got tired of it so I uninstalled Notepad++ and switched to Visual Code. I am switching to Linux soon anyway. Got tired of Windows 10 mishaps as well. Thanks for all your help.
