### ISSUE TITLE
Functionlist selected item not readable

### ISSUE THREAD

**Issue by Loopbuilder** [notepad-plus-plus/notepad-plus-plus#10450]
After starting Notepad++ (since 8.1.2) with a C-File, the current function is highligted in the function list.
The color of the entry is shown: dark-gray/black background, black font color, so i can't read it.
![Functionlist](https://user-images.githubusercontent.com/16815049/131073667-17249f15-6482-46eb-9bd4-1ec301805f56.png)

I use the default stylers.xml (not the dark mode)

If i go to Settings - Style - Global Styles-Default Style and change foreground from black to (yellow for example) and change it back to black, the display-style in functionlist ist changed to gray background and black color, so i can read it from this time on.

I save the settings, but on exit and next start, it is the same problem as before:  black on black.

**Comment by Loopbuilder** [comment]
Hi ozone10.

If i use a different style (solarized-light style for example), function list is readable with the colors of the new style.
If i close and reopen notepad++ the new style (for function-list) is changed: black/gray-background, different from the selected and saved style.

If i change the style without reopen notepad, the  function list is readable with the colors of the new style.
If i restart notepad++ with default-style (function list not readable) and change the style to the same: default-style, then function-list it is readable again.

But after every new start of notepad++ the problem is there again.

Debug-Info:

Notepad++ v8.1.4   (32-bit)
Build time : Aug 21 2021 - 12:58:42
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Command Line : "D:\Projekte\Volkswagen\Passat\V2\SW\aktuell\Src\can_in_out.c"
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 10 Enterprise (64-bit) 
OS Version : 1909
OS Build : 18363.1556
Current ANSI codepage : 1252
Plugins : BigFiles.dll ComparePlugin.dll HexEditor.dll LocationNavigate.dll mimeTools.dll NppConverter.dll NppExec.dll NppExport.dll NppTextFX.dll

**Comment by ArkadiuszMichalski** [comment]
Try without plugins.

**Comment by Loopbuilder** [comment]
Ok. It was the HEX-Editor plugin v0.9.9 (32-Bit DLL).

Even after update to HEX-Editor plugin v0.9.10  (32-Bit DLL) the problem was present.

Thanks. I open a issue at the Hex-Editor plugin.
