### ISSUE TITLE
Insert Date Time Customized doesn't support some formats

### ISSUE THREAD

**Issue by mere-human** [notepad-plus-plus/notepad-plus-plus#10467]
For more context, see discussion here https://github.com/notepad-plus-plus/notepad-plus-plus/pull/10453

### Steps to Reproduce the Issue

1. Settings > Preferences > Multi-Instance & Date
2. Custom Format

### Expected Behavior

A way to specify short year, etc.

### Actual Behavior

No way to specify short year (e.g. 98), leading zeroes in month and day (01), etc.

### Debug Information

Notepad++ v8.1.4   (64-bit)
Build time : Aug 30 2021 - 20:46:31
Path : ...\Notepad++.exe
Command Line : -multiInst -nosession
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 10 Enterprise (64-bit) 
OS Version : 2009
OS Build : 19043.1165
Current ANSI codepage : 1252
Plugins : none

**Comment by donho** [comment]
if it's only for short year, it doesn't worth it.
Is there another advantage?

**Comment by mere-human** [comment]
> if it's only for short year, it doesn't worth it.
> Is there another advantage?

AM/PM, 12 or 24 hour time, day of the week, numbers with/without leading zeroes, epoch format (A.D. or B.C.), etc.
Check out the links for more info about format:
https://docs.microsoft.com/en-us/windows/win32/intl/day--month--year--and-era-format-pictures
https://docs.microsoft.com/en-us/windows/win32/api/datetimeapi/nf-datetimeapi-gettimeformatex#remarks

**Comment by donho** [comment]
@mere-human 
No, I'm not talking about all the possibilities of these Win32 API.
I'M TALKING ABOUT WHAT IS THE EASY FORMAT YOU CAN PROVIDE TO USER FOR ALL THE POSSIBILITIES.
WITHOUT THIS, IT'S NOT INTERESTING!

**Comment by mere-human** [comment]
> @mere-human
> No, I'm not talking about all the possibilities of these Win32 API.
> I'M TALKING ABOUT WHAT IS THE EASY FORMAT YOU CAN PROVIDE TO USERS FOR ALL THE POSSIBILITIES.
> WITHOUT THIS, IT'S NOT INTERESTING!

I just thought that creating own date & time format for Notepad++ is like reinventing the wheel.
It would be much easier and more powerful and less error-prone to use a well defined format from Win32 API.

**Comment by donho** [comment]
Reinventing the wheel has its goal:
I think Y M D h m s can be understood by everyone - that's my goal.
Now, I don't care to threw out my invented wheel which is not perfect, but you have to show me a wheel more round to conceiving me to use yours instead of mine.
So all I want is is a small specifications (a format simple enough for every user) upon which  you will implement.

**Comment by donho** [comment]
<html><body>


g, gg | Period/era string formatted | B.C., A.D.
-- | -- | --



</body>
</html>

`g` is for BC & `gg` is for AD, right ? Why don't users just give `AD` or `BC` ?


<html><body>


MMM | Abbreviated month | Nov
-- | -- | --



</body>
</html>

It's only in English or it'll detect the local system? If it will use the local system, I wonder how it will show in Japanese/Chinese system.


<html><body>


t | One character time marker string | A, P
-- | -- | --



</body>
</html>

I've never see such notation. Could you provide link if it does exist ?

Why not millisecond since you have provided the sophisticated format?
 
BTW, how will you process exception like `ddddd` or `yyy` ?

**Comment by mere-human** [comment]
> `g` is for BC & `gg` is for AD, right ? Why don't users just give `AD` or `BC` ?

No, it's just an alternative way of writing the same specifier. Both `g` and `gg` will result in `A.D.`.
`B.C.` will be used for pre-Christian era which is only possible by manually changing the OS time.
https://en.wikipedia.org/wiki/Anno_Domini

---

> It's only in English or it'll detect the local system? If it will use the local system, I wonder how it will show in Japanese/Chinese system.

Now it'll use the system locale. But it is possible to add a check-box to force English.
I can try this later and show it to you.

---

> t	One character time marker string	A, P
> I've never see such notation. Could you provide link if it does exist ?

https://en.wikipedia.org/wiki/12-hour_clock#Typography
> _With the advent of computer generated and printed schedules, especially airlines, the "M" character is often omitted as providing no additional information as in "9:30A" or "10:00P"._

---

> BTW, how will you process exception like `ddddd` or `yyy` ?

I simply won't. I'll let [GetDateFormatEx](https://docs.microsoft.com/en-us/windows/win32/api/datetimeapi/nf-datetimeapi-getdateformatex) handle it:
 ![image](https://user-images.githubusercontent.com/9664141/131691320-f195fa6f-9c5f-439e-b6a3-85038386bfb5.png)

**Comment by mere-human** [comment]
Some users seem to be used to the format I posted above for custom date format.
For example:
https://community.notepad-plus-plus.org/topic/13917/textfx-64-bit-binary-source-code-unavailability/31
`FormatDateTime( 'dddd, dd.MM.yyyy hh:mm:ss', now() )` using NppCalc plugin.

Also, there is another pretty popular solution using PythonScript:
https://community.notepad-plus-plus.org/topic/13792/date-time-again/2

**Comment by donho** [comment]
I guess A & P for AM & PM is managed by API. If yes, I have no objection.

> Now it'll use the system locale. But it is possible to add a check-box to force English.
I can try this later and show it to you.

It's not necessary. Let's not provide more options, just the string of formatting is enough.

**Comment by mere-human** [comment]
@donho I have a few questions about this.

### AM/PM Format

How to deal with `tt` format if AM/PM string is not defined in locale?
As it was pointed out by @rddim 
![image](https://user-images.githubusercontent.com/9664141/131746679-463e3037-d71c-4914-affc-24740cf8ff58.png)

Options:
* Format `tt` as `AM` or `PM` despite it is not defined (my preferred option)
* Ignore `tt` and format it as an empty string

### Text in Preferences

How should we change the text in preferences?
![image](https://user-images.githubusercontent.com/9664141/131747068-6eda565e-8b61-4b7e-8fd9-897049c4ba65.png)

Options:
* Adapt examples to the new format
* Add a notion like `For more information on custom format refer to the User Manual`

**Comment by mere-human** [comment]
Also, as you can see, the regional format uses the same format specifiers.
So this way Notepad++ is consistent with Windows OS.
We even might refer users to this place for examples.

**Comment by mere-human** [comment]
One more suggestion: use the current date as example output in preferences rather than 1985.

**Comment by mere-human** [comment]
> > How to deal with tt format if AM/PM string is not defined in locale?
> 
> As I said, don't deal with it, and remove it

I would still prefer to format `tt` as an empty string if it's not defined and AM/PM otherwise.
12-hour clock is widely used especially in UK, US and Australia.
But as you wish.

**Comment by donho** [comment]
@mere-human 
I'm not against `tt` or `gg`.
I just saw your initial commit in which you process `tt` apart - not only I prefer the simple thing, but also I felt that lead the bug.
I just tried the following lines and it works:
https://github.com/notepad-plus-plus/notepad-plus-plus/pull/10480/files#r700968815

If it work for any case, I'll be glad to keep `tt` or `gg`. Otherwise, let's go back to the old initial simpler system.

**Comment by donho** [comment]
@mere-human 
> I would still prefer to format `tt` as an empty string if it's not defined and AM/PM otherwise.

Or maybe there is a "better" solution:
We could NOT process `tt` before calling GetTimeFormatEx, but restore AM or PM by searching and substituer  `A1` - `A12` or `P1` - `P12` respectively.
With this solution, we have to ensure `tt` insert ONLY `AM` or `PM` but not other string.

**Comment by mere-human** [comment]
> Or maybe there is a "better" solution:

I provided an answer to this [here](https://github.com/notepad-plus-plus/notepad-plus-plus/pull/10480#issuecomment-919792254)

**Comment by donho** [comment]
@pryrt 
With the merge of #10480, could you please put the [format](https://github.com/notepad-plus-plus/notepad-plus-plus/issues/10467#issuecomment-910282705) into Notepad++ User Manual ?
