### ISSUE TITLE
Data loss after false regular search with a special symbol

### ISSUE THREAD

**Issue by mlatushko** [notepad-plus-plus/notepad-plus-plus#10460]
![2021-08-29_180128](https://user-images.githubusercontent.com/23335312/131255752-1c11e0c1-ed14-4535-9c53-d19761fc78c6.png)

### Steps to Reproduce the Issue

1. Try to search regular>> (?(◘)◘|•)
or with another symbol, like ．，／：‽…·
2. Then will be these messages:
```
(1) bad conversion
(2) Notepad++ will attempt to save any unsaved data. However, dataloss is very likely
(3) Notepad++ was able to successfully recover some unsaved documents, or nothing to be saved coulld be found.
You can find the results at :
C:\Users\NOTE\AppData\Local\Temp\\++RECOV
```

### Expected Behavior
Normal error and continue.

### Actual Behavior
Loose every temporary file in session.

### Debug Information
```
Notepad++ v8.1   (32-bit)
Build time : Jun 17 2021 - 01:52:11
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 7 Ultimate (32-bit) 
OS Build : 7601.24563
Current ANSI codepage : 1251
Plugins : combine.dll ComparePlugin.dll HTMLTag_unicode.dll mimeTools.dll NppConverter.dll NppExport.dll NppTextFX.dll PreviewHTML.dll 
```

Also, would be great to support correctly encoding changing with macros.

**Comment by ArkadiuszMichalski** [comment]
Can you try with last portable?
https://github.com/notepad-plus-plus/notepad-plus-plus/wiki/Testing#using-the-latest-release-portable-version-of-notepad

**Comment by felix-22** [comment]
> mlatushko : Plugins : combine.dll ComparePlugin.dll HTMLTag_unicode.dll mimeTools.dll NppConverter.dll NppExport.dll NppTextFX.dll PreviewHTML.dll

"Would be great" if before reporting an issue you would try on default settings, without external/additional plugins, to make sure this is not an external plugin causing it...

> mlatushko : Notepad++ v8.1 (32-bit)

"Would be great" if before reporting an issue you would try on the latest version of N++ to make sure this is not an issue which has been already fixed...

Also would be great if you would provide the file to reproduce, or at least an example file, or provide some info like size of the file or number of lines.

I'm not going to do it for you...nor I can reproduce the issue (N++ 8.1.3 32bit).

**Comment by mlatushko** [comment]
> Can you try with last portable?
> https://github.com/notepad-plus-plus/notepad-plus-plus/wiki/Testing#using-the-latest-release-portable-version-of-notepad

Thank you. Is the same, incl.
> You can find the results at :
> C:\Users\NOTE\AppData\Local\Temp\++RECOV

/
> felix
>> the file to reproduce
 - It's working just with only search string in regex:
`(?(◘)◘|•)`
 
```
Notepad++ v8.1.4   (32-bit)
Build time : Aug 21 2021 - 12:58:42
Path : S:\(INST)\(text)\npp\npp.8.1.4.portable\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : ON
Cloud Config : OFF
OS Name : Windows 7 Ultimate (32-bit) 
OS Build : 7601.24563
Current ANSI codepage : 1251
Plugins : mimeTools.dll NppConverter.dll NppExport.dll 
```


```
![2021-08-29_213234](https://user-images.githubusercontent.com/23335312/131261557-8984bc89-65e3-413b-bbcb-ed9494750aea.png)
```

**Comment by mere-human** [comment]
@mlatushko I can reproduce this problem.
Here is the full error text that I got from debugger:
`Invalid or unterminated Perl (?...) sequence.  The error occurred while parsing the regular expression: '(?>>>HERE>>>(Ø)Ø|")'.`

**Comment by mere-human** [comment]
Also, the error is show in the Find dialog as a tool tip:
![image](https://user-images.githubusercontent.com/9664141/131263565-c13154fc-690f-41e5-8ed8-a6dea91363d3.png)

**Comment by mlatushko** [comment]
> Also, the error is show in the Find dialog as a tool tip:

Yes, this is a common mistake. The behavior / reaction of the program due to the error is a problem.
Regular
`[.`
 - shows normal error
`[•`
 - this one too (Alt+7)
 `[◘`
This symbol makes the problem ( Alt + 8 )

It has to be a character that is not readable in ANSI. ◘ in UTF-8 is converting to •
**A regular expression using a character like this (．，／：‽…·) results in a special error.**

**Comment by felix-22** [comment]
This is odd...

- I still cannot reproduce in 8.1.4 32bit (the version OP uses)
- however I can reproduce in 64bit (while OP reproduced in 32bit) - N++ immediately crashes ("Program N++ has stopped working...")

Current ANSI codepage : 1250

Screenshoot:
![xxx](https://user-images.githubusercontent.com/75935068/131297768-c0da08d3-4006-4938-a971-a26d40fe1cf9.png)

@chcg (or anybody) `crash` label

**Comment by mlatushko** [comment]
Thank you. You've solved this.
