### ISSUE TITLE
the ability to change the default terminal

### ISSUE THREAD

**Issue by michal037** [notepad-plus-plus/notepad-plus-plus#10461]
### Description of the Issue
In the current version of the Notepad++ it is not possible to change the default terminal that is opened. This option would be handy as the new Windows 11 will have a [new terminal](https://github.com/microsoft/terminal) pre-installed. This terminal can now be used on previous versions of Windows. Some people use other terminals, so being able to change the default option would be great.

### Steps to Reproduce the Issue
![terminal](https://user-images.githubusercontent.com/7441419/131269618-c71cab1c-9f8e-4a3b-bcdc-aa0acb053db4.gif)

### Expected Behavior
Opening a specific terminal, defined earlier in the settings. Including the new Windows terminal `wt.exe`.

### Actual Behavior
The old `cmd.exe` terminal opens.

### Debug Information
Notepad++ 8.1.3
Windows 10

**Comment by MonstreCharmant** [comment]
Same here, any plan on improving this?
My current solution is to install another plugin, such as [PythonScript](https://github.com/bruderstein/PythonScript) which allows you to execute python scripts, and execute a command like `wt.exe`. Yeah it works, but I think this should be a built-in feature.

**Comment by amb5l** [comment]
My pull request [#13926](https://github.com/notepad-plus-plus/notepad-plus-plus/pull/13926) which adds "Windows Terminal here" to the File Browser context menu. I understand that proposed new functionality must reference an issue, so I'm mentioning this here.

**Comment by donho** [comment]
Following the User Manual, as @alankilborn has indicated:
https://npp-user-manual.org/docs/preferences/#preferences-for-advanced-users

>     Changing the command-line interpreter used: by default, File > Open Containing Folder > cmd will launch the cmd.exe command-line interpreter. If you have a preferred command-line interpreter (such as powershell), you can add another `<GUIConfig...>` tag inside the `<GUIConfigs>` section:

```xml
    <GUIConfig name="commandLineInterpreter">powershell</GUIConfig>
```

>    If your command-line interpreter is not in your path, make sure to include the drive and folder in the contents of that tag. If there are spaces, make sure to use quotes around the path:

```xml
    <GUIConfig name="commandLineInterpreter">"c:\path\with spaces\to\cli.exe"</GUIConfig>
```

**Comment by alankilborn** [comment]
@donho 

>Following the User Manual, as @alankilborn has indicated

Does that give you a PowerShell prompt from the right-click context menu in _Folder As Workspace_ ?
_FAW_ is what this issue is concerning.
