### ISSUE TITLE
crash of the program at the start

### ISSUE THREAD

**Issue by slkom** [notepad-plus-plus/notepad-plus-plus#10465]
### Description of the Issue
sudden crash of the program at the start.

### Steps to Reproduce the Issue
1. suddenly
2. crash of the program at the start

### Synopsis:
config.xml : error encoding
xml version="1.0" encoding="Windows-1252"
fixing the problem:
xml version="1.0" encoding="UTF-8"

**Comment by felix-22** [comment]
https://github.com/notepad-plus-plus/notepad-plus-plus/issues/10046#issuecomment-908202225

**Comment by dail8859** [comment]
Please provide detailed debug information as requested in the template. Feel free to reopen once more details are provided.

**Comment by mere-human** [comment]
Also try launching without plugins.
