### ISSUE TITLE
Translation for "Incremental Search panel" is not applied until language file is reloaded

### ISSUE THREAD

**Issue by yasmise** [notepad-plus-plus/notepad-plus-plus#10478]
### Description of the Issue
Translation for "Incremental Search panel" is not applied (the panel is shown in English).
To apply translation, it requires reloading the translation file every launch of Notepad++.

### Steps to Reproduce the Issue
1. Download AppVeyor's build from [here](https://ci.appveyor.com/project/donho/notepad-plus-plus/builds/40582212/job/b5ty66fibor0rukx/artifacts).
2. Move it to install directory of Notepad++.
3. Copy some new translation file to `localization` folder of install directory of Notepad++.
4. Launch `Notepad++.x64.Release.exe` and change language to apply new translation file.
5. Run Incremental Search, and the panel is translated.
6. Restart Notepad++.
7. Run Incremental Search, and the panel is shown in English.

### Expected Behavior
Translation is applied automatically.

### Actual Behavior
Translation is not applied automatically.

### Debug Information
Notepad++ v8.1.4   (64-bit)
Build time : Aug 31 2021 - 00:02:56
Path : C:\Program Files\Notepad++\Notepad++.x64.Release.exe
Command Line : 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 10 Home (64-bit) 
OS Version : 2009
OS Build : 19043.1165
Current ANSI codepage : 932
Plugins : mimeTools.dll NppConverter.dll NppExport.dll

**Comment by ArkadiuszMichalski** [comment]
@donho 
After restart "Incremental Search panel" always use english localization, regardless of the currently selected one. It would be good to fix this before release next version, because there will probably be more reports for this case.
