### ISSUE TITLE
What File Defines the Expand/Collapse Behavior for Various Extensions?

### ISSUE THREAD

**Issue by spaceman5** [notepad-plus-plus/notepad-plus-plus#10479]
Hi all

I am using Notepad++ for various code files,
among them AutoIt code files - Extension .AU3.

I noticed there's a small problem in how Notepad++ interprets the #regions in .AU3 files,
and would like to see If I can fix it and make it better.

What file defines the Expand/Collapse behavior, and defines where to put a square with a "+" inside it (to toggle Expand/Collapse)?

Thank you very much

**Comment by dail8859** [comment]
The quick answer is [here](https://github.com/notepad-plus-plus/notepad-plus-plus/blob/f6488cdc7ad4b848c971ce889398b50cf80c1d4d/scintilla/lexers/LexAU3.cxx#L675)

The longer answer is the code that actually does the parsing, folding, styling, etc is part of the [Lexilla](https://github.com/ScintillaOrg/lexilla) project (not controlled by Notepad++). So any changes to this part of the code would be best made to that project. There should be a very similar file in that project.

That being said, if you do fix a bug in Lexilla it may take a while for those changes to show up in Notepad++ as that library is not updated that often.

**Comment by spaceman5** [comment]
Hi dail8859

I see.

Thank you very much for your answer.
