### ISSUE TITLE
Shift+F3 / Search backwards is not working for some releases now.

### ISSUE THREAD

**Issue by PascalRiekenberg** [notepad-plus-plus/notepad-plus-plus#10476]
Shift+F3 / Search backwards is not working for some releases now.

Notepad++ v8.1.4   (64-bit)
Build time : Aug 21 2021 - 13:04:59
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 10 Pro (64-bit) 
OS Version : 2009
OS Build : 19043.1110
Current ANSI codepage : 1252
Plugins : mimeTools.dll NppConverter.dll NppExport.dll NPPJSONViewer.dll NppXmlTreeviewPlugin.dll

**Comment by dail8859** [comment]
As requested in the template, please provide an exact set of steps to reproduce the issue.

I tried with v8.1.4 (64-bit) and it works fine.

You can also try running notepad++ from the command line and pass in the [`-noPlugin` option](https://npp-user-manual.org/docs/command-prompt/) to see if it is a plugin interfering with this functionality.

**Comment by ArkadiuszMichalski** [comment]
Same as https://github.com/notepad-plus-plus/notepad-plus-plus/issues/10333.

**Comment by PascalRiekenberg** [comment]
-noPlugin does not solve the issue. Will try to delete %AppData%\Notepad++ and reinstall Notepad++

**Comment by mere-human** [comment]
@PascalRiekenberg Also, if you do a regular expression search, it may not work.
Please, refer to this page for more info https://npp-user-manual.org/docs/preferences/#preferences-for-advanced-users

**Comment by sicklittlemonkey** [comment]
> @PascalRiekenberg Also, if you do a regular expression search, it may not work.
> Please, refer to this page for more info https://npp-user-manual.org/docs/preferences/#preferences-for-advanced-users

That was it for me - first time I had noticed. Presumably only a problem if metacharacters are used. It would be nicer to have the option to do the search if no metacharacters are present, and either not do the search or pop up a warning if they are.

**Comment by PascalRiekenberg** [comment]
> 
> 
> @PascalRiekenberg Also, if you do a regular expression search, it may not work.
> Please, refer to this page for more info https://npp-user-manual.org/docs/preferences/#preferences-for-advanced-users

This option solves the problem. There should be a hint if the user hits Shift-F3 or selects the menu entry. Best with a button to set this option quickly.
