### ISSUE TITLE
C++ functionalities not works

### ISSUE THREAD

**Issue by akshay48-web** [notepad-plus-plus/notepad-plus-plus#10472]
1. note pad dosent work c++ functionalities
2. which changes in to use them

**Comment by rimrul** [comment]
Could you provide some information about this issue?

* What version of `Notepad++` are you using? 
* What are you trying to do?
* How does it not work? Do you get an error message? Does nothing happen when you click a button? Are you looking for a button that does the thing you want to do, but can't find it?
* Did this work in some older version of `Notepad++`?
