### ISSUE TITLE
The Caret settings doesn't seem to save. I've been stuck at block and won't go to the thin line # 3

### ISSUE THREAD

**Issue by patrikpatrik** [notepad-plus-plus/notepad-plus-plus#10481]
### Description of the Issue

I've been trying to change my blink rate caret from a Block setting to a skinny line for the past several months. But everytime I close notepad++ and come back, it defaults back to block?

### Steps to Reproduce the Issue

1. Click Settings -> Preferences -> Editing -> Caret Settings -> Width: Block -> Close. Then try line # 3 and it defaults back to block?

### Expected Behavior

I expected it to save as the line caret blinker # 3 width.

### Actual Behavior

It defaults back to width: Block which I don't want.

### Debug Information

Notepad++ v8.1.4   (32-bit)
Build time : Aug 21 2021 - 12:58:42
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : C:\Program Files (x86)\Notepad++\export
OS Name : Windows 10 Home (64-bit) 
OS Version : 2009
OS Build : 19042.1165
Current ANSI codepage : 1252
Plugins : mimeTools.dll NppConverter.dll NppExport.dll

**Comment by mere-human** [comment]
Works for me

![image](https://user-images.githubusercontent.com/9664141/131641688-fd0e4279-d0b2-430b-aa41-3a9b79ac27cc.png)

```
Notepad++ v8.1.4   (64-bit)
Build time : Sep  1 2021 - 11:13:30
Path : ...\notepad++.exe
Command Line : -multiInst -nosession
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 10 Enterprise (64-bit) 
OS Version : 2009
OS Build : 19043.1165
Current ANSI codepage : 1252
Plugins : none

```

I'd suggest you to find a config file `%AppData%\Roaming\Notepad++\config.xml`
Then open it in Notepad++ and find the value `Caret`.
Mine looks like this:
`<GUIConfig name="Caret" width="4" blinkRate="600" />`
If it is different for you, you can change it, but close Notepad++ beforehand and use Microsoft Notepad to edit.
Since this is Notepad++ config and it is overridden on app shutdown.

**Comment by ArkadiuszMichalski** [comment]
Other changes from Preferences window are remembered? Maybe something wrong with permissions in your cloud folder or the `config.xml` itself is out of date.

**Comment by mere-human** [comment]
> Maybe something wrong with permissions in your cloud folder

Right, may be due to cloud config being used which I missed somehow.

**Comment by patrikpatrik** [comment]
@ArkadiuszMichalski , @mere-human, Thank you. Yeah it's a permission problem. I had to right click on notepad++ shortcut -> run as admin and then the changes are saved upon closing the program and reopening. For whatever reason when I just normally double click on the shortcut, only that caret change defaults back. I'll close this issue and thanks again Cheers!
