### ISSUE TITLE
Be able to search for NULL bytes/characters

### ISSUE THREAD

**Issue by FcoTbArrGz** [notepad-plus-plus/notepad-plus-plus#1048]
Good afternoon.

This is a hex (if im not in a mistake) mode feature request.

Notepad++ is a very powerful tool that can display null characters as [NUL], as well as enable users enter them by pressing Alt + 2 5 6 on numeric pad as long np++ is turned on hex mode.

The problem here would ocurr that while notepad++´s file's text field is enabled on the desired mode, text bars: Find, Replace, Find in Files & Mark, they still on normal text mode, so one can´t enter null characters on them by pressing Alt + 2 5 6 to be cappable of manipulating this kind of files (massive manipulation of this type of files in my case), easily by means of the powerful tools of notepad++.

Is there any possibility of changing this behavior of this bars?

Thanks, and I ask forgiveness in advance and deletion of this message if im in a mistake -either in problems technical description too-.

**Comment by guy038** [comment]
Hello, **FcoTbArrGz**,

You can search for **NUL** characters, of Unicode code-point **`&x0`** :

- In **Extended** search mode, with the syntax **`\0`**

- In **Regular expression** search mode, with the syntaxes **`\0`** ( **Octal** ) or **`\x0`** ( **Hexa** )

Unfortunately, up to now, you **CAN'T** replace any **searched** string by a **NUL** character or a string that contains one or more **NUL** characters :-((

Best Regards,

guy038

**Comment by FcoTbArrGz** [comment]
oK, THANKS,

Wanted to change the direction of like a thousands of .lnk files without installing any other program.

PD: sorry for the **DELAY**......

**Comment by dail8859** [comment]
Closing since this is resolved.
