### ISSUE TITLE
UTF-8 character not displayed

### ISSUE THREAD

**Issue by superbonaci** [notepad-plus-plus/notepad-plus-plus#10492]
Notepad+++ 8.1.4 (64-bit)

Opening a text file with certain UTF-8 character, for example `û` does not detect it. It's recognized as Thai TIS-620, and changing Encoding to UTF-8 doesn't change to it. Example file attached below.

![](https://i.imgur.com/V27vfEH.png)

![](https://i.imgur.com/MyPAill.png)

[small-u-circumflex.zip](https://github.com/notepad-plus-plus/notepad-plus-plus/files/7101889/small-u-circumflex.zip)

**Comment by ArkadiuszMichalski** [comment]
Duplicate of several other https://github.com/notepad-plus-plus/notepad-plus-plus/search?q=TIS-620&type=issues.

**Comment by superbonaci** [comment]
The issue I have is that not only is not detected properly, but that doesn't let me change from one encoding to another. This is beyond uchardet scope.

**Comment by ArkadiuszMichalski** [comment]
These bugs mention it too.

**Comment by superbonaci** [comment]
Bug still present in `Notepad++ v8.1.9.3`.

**Comment by alankilborn** [comment]
> Bug still present in `Notepad++ v8.1.9.3`.

Nothing regarding this was fixed in 8.1.9.3.  Look at the timeline.

**Comment by superbonaci** [comment]
Working on latest build: #10960
