### ISSUE TITLE
Update CSS Keywords

### ISSUE THREAD

**Issue by Yaron10** [notepad-plus-plus/notepad-plus-plus#10517]
**STR:**
Paste `view-source:chrome://browser/skin/browser.css` in Firefox URL bar and press Enter.
Copy the content and paste it into an NPP CSS file.

**Result:**
Many words seem to be parsed as "UNKNOWN".
For example: `:is`, `:where` and `translate`.

![תמונה](https://user-images.githubusercontent.com/10229320/132353385-2bb287b9-c3db-42a4-aef1-99117410f5fb.png)

Thank you.

***
Notepad++ v8.1.4   (32-bit)
Build time : Aug 21 2021 - 12:58:42
Path : C:\Users\---\Downloads\npp.8.1.4.portable\notepad++.exe
Command Line : 
Admin mode : ON
Local Conf mode : ON
Cloud Config : OFF
OS Name : Windows 10 Enterprise (64-bit) 
OS Version : 2009
OS Build : 19042.985
Current ANSI codepage : 1255
Plugins : none

**Comment by ArkadiuszMichalski** [comment]
Actual `browser.css` file from Firefox.
[mozilla_browser.css.txt](https://github.com/notepad-plus-plus/notepad-plus-plus/files/10765586/mozilla_browser.css.txt)

Missing: `:is`, `:focus-within`. But I see there are more (could be add):
https://developer.mozilla.org/en-US/docs/Web/CSS/Pseudo-classes

These are supported by all leading browsers.
```
any-link
autofill
default
defined
focus-visible
focus-within
fullscreen
has
host
in-range
is
modal
out-of-range
placeholder-shown
scope
where
```

https://developer.mozilla.org/en-US/docs/Web/CSS/Pseudo-elements
```
backdrop
```

Also some non standard. I don't know if we should add this non standard. I see that some of them was added (like `-moz-context-properties` or `-moz-float-edge`). The easiest way would be using  a pattern for all (like `:-moz-` or `-moz-`), but then even the wrong ones (e.g. with a typo) would be colored not as unknown.
https://udn.realityripple.com/docs/Web/CSS/Mozilla_Extensions < last list with Mozilla extensions to CSS.

**Comment by Yaron10** [comment]
@ArkadiuszMichalski,

Thank you for working on this. 👍 

Firefox has split `browser.css` into several files.

> I don't know if we should add this non standard.

I don't know either.

After a _quick_ look: `scale` `translate` are still missing.

**Comment by Yaron10** [comment]
https://www.w3schools.com/cssref/index.php
