### ISSUE TITLE
Please sort language lists in preferences

### ISSUE THREAD

**Issue by pryrt** [notepad-plus-plus/notepad-plus-plus#10513]
### Description of the Issue
in the **Settings > Preferences > New Documents > Default Language** pulldown, as well as the **Settings > Preferences > Language > Available Items**, those lists are unsorted.  It makes it really hard to find the language you are looking for.  (The **... > Language > Tab Settings** is nicely sorted.)

### Steps to Reproduce the Issue

1. Look at **Settings > Preferences > New Documents > Default Language** pulldown and try to find Spice or SQL -- they are nowhere near each other
2. Look at **Settings > Preferences > Language > Available Items** listbox and try to find Spice or SQL -- they are nowhere near each other

### Expected Behavior
Sorted list -- alphabetically ignoring case would be best.  (Feel free to put `None (Normal Text)` at the beginning rather than sorted alphabetically.)
The expected behavior would be to sort in the same order used in the Tab Settings box, which is reasonably alphabetized: 
![image](https://user-images.githubusercontent.com/17455758/132251102-eb215818-bead-4cbd-a4c6-cdb333e0bf60.png)

### Actual Behavior
Random order
![image](https://user-images.githubusercontent.com/17455758/132250910-b97bf013-60da-41f0-a406-62bd40926be6.png) 
![image](https://user-images.githubusercontent.com/17455758/132250991-1c207243-01bd-4872-981c-032ea0cb3303.png)

### Debug Information
```
Notepad++ v8.1.4   (64-bit)
Build time : Aug 21 2021 - 13:04:59
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 10 Home (64-bit) 
OS Version : 2009
OS Build : 19043.1165
Current ANSI codepage : 1252
Plugins : ...
```

**Comment by ArkadiuszMichalski** [comment]
Some alternative may be [pressing keys.](https://github.com/notepad-plus-plus/notepad-plus-plus/issues/9642#issuecomment-797503587)

**Comment by Yaron10** [comment]
@donho,

👍 
Thank you.

Did you intentionally not sort `Settings > Preferences > Language > Available Items`?

**Comment by donho** [comment]
> Did you intentionally not sort `Settings > Preferences > Language > Available Items`?

@Yaron10 
Yes, it's a tough one, and it's not really need to be sorted. So let's keep it as it is.

**Comment by Yaron10** [comment]
@donho,

👍 
Thank you.

**Comment by pryrt** [comment]
Thank you
