### ISSUE TITLE
Suggestion: underline Access Keys in menus

### ISSUE THREAD

**Issue by Mrnofish** [notepad-plus-plus/notepad-plus-plus#10519]
### Description of the Issue
Notepad++ is only showing access keys (accelerators) for the top level menu.

Operating the menu items that have no shortcut, only happens through the default OS mapping (see post below for a more detailed explanation)

For instance, Word Wrap can be flipped through Alt - V - W, but the letter W is not underlined in the View menu, nor are any other items in this menu (or any others that I could see).

See screenshot: only the access keys for the top level menu are underlined, while no underlining is visible in the drop down menu.

![image](https://user-images.githubusercontent.com/28036193/132368697-00dd153c-4438-4b23-9325-43c9cba097ed.png)

### Debug Information
Notepad++ v8.1.2

**Comment by ArkadiuszMichalski** [comment]
This menu has no any access keys defined, unlike `File` or `Edit`. Your example work because this is default behavior, `W` was first on `Word wrap` command and no others command has `W`, so it was launched (not just selected). If you try with `P` you will jump through `Post-It` and `Project`.

**Comment by Mrnofish** [comment]
I see, thanks for clearing that up. I've updated the issue title and text, feel free to let me know if any other changes would be appropriate.

> This menu has no any access keys defined,

I guess NO menus have any access keys defined then, the View Menu was simply an example to illustrate the point.

**Comment by ArkadiuszMichalski** [comment]
>I guess NO menus have any access keys defined then, the View Menu was simply an example to illustrate the point.

Looks like you have an old English localization file.

![image](https://user-images.githubusercontent.com/2730894/132525649-4686e97c-ad2c-4491-976e-5e21ed79a7ba.png)

**Comment by Mrnofish** [comment]
As mentioned in the Debug info I'm on 8.1.2. I'm going to upgrade to 8.1.4 and see what happens.

**Comment by Mrnofish** [comment]
Confirmed, on 8.1.4 there's accelerators for File, Edit and Select.

**Comment by dail8859** [comment]
Sounds like this is working as expected now. Closing.

**Comment by victorel-petrovich** [comment]
> Sounds like this is working as expected now. Closing.

How come? His suggestion is not fulfilled in general; not for any other submenu commands than in File, Edit, Search.
