### ISSUE TITLE
Count in Status Bar

### ISSUE THREAD

**Issue by mapa4** [notepad-plus-plus/notepad-plus-plus#1051]
Would it be possible to add this enhancement : when double clicking on a word, having the count number displayed in the status bar ?

**Comment by Croydon** [comment]
What would be the benefit from it? You can just mark words and the number of chars are getting displayed in the bar at the bottom.

**Comment by allainsim45** [comment]
it is possible to obtain the same result with existing menus

settings >> edit popup context menu

inside ContextMenu.xml  add the two lines  juste before     </ScintillaContextMenu>

	  <Item id="0"/>
          <Item MenuEntryName="Search" MenuItemName="Incremental search"/>


save file and restart np++

go to  a word you will count

first click= insert cursor, second click = word selected,  third click = the entire line is selected

after selected text, bring up the context menu, then select "Incremental search"

above the status bar displays a search toolbar with the selected text and right exact count of items corresponding to it in the document
simply reselect another word and reuse the context menu, the count will be refreshed

**Comment by mapa4** [comment]
Well done and thank you Alainsim45, it works like a charm !

**Comment by MetaChuh** [comment]
can be done using incremental search
-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)

**Comment by sasumner** [comment]
@MetaChuh 

>incremental search

Nice workaround, never thought of that! :)
