### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by CU61** [notepad-plus-plus/notepad-plus-plus#10526]
### Description of the Issue
"Replace" feature has a bug

### Steps to Reproduce the Issue
1. I would like to replace a line with:
2. <p><a href="https://www.facebook.com/cumbucooceanview/" target="_blank"><img src="../images/facebook.png" alt="Facebook" width="16" height="16" longdesc="https://www.facebook.com/cumbucooceanview/" /></a>
                    <img src="../images/cumbuco-hotel.gif" alt="Cumbuco Hotel" width="1" height="1" />
					<a href="https://www.instagram.com/cumbucohotel/" target="_blank"><img src="../images/instagram.png" alt="Instagram Cumbuco Hotel" width="16" height="16" longdesc="https://www.instagram.com/cumbucohotel/" /></a>
                    <img src="../images/cumbuco-hotel.gif" alt="Cumbuco Hotel" width="1" height="1" />
                    <a href="https://www.twitter.com/CumbucoBrazil/" target="_blank"><img src="../images/twitter.png" alt="Twitter" width="16" height="16" longdesc="https://www.twitter.com/CumbucoBrazil/" /></a></p>
2. When I paste it into the replace with, only the first line will be pasted and not like in the past the whole string

### Expected Behavior
See above

### Actual Behavior
SAee above

### Debug Information
Notepad++ v8.1.4   (64-bit)
Build time : Aug 21 2021 - 13:04:59
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : 
Admin mode : ON
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 10 Pro (64-bit) 
OS Version : 2009
OS Build : 19042.572
Current ANSI codepage : 1252
Plugins : mimeTools.dll NppConverter.dll NppExport.dll 

Thank you, Merci

**Comment by CU61** [comment]
Mmhhh, it should show this string (several lines, only the first will be pasted):

<p><a href="https://www.facebook.com/cumbucooceanview/" target="_blank"><img src="images/facebook.png" alt="Facebook" width="16" height="16" longdesc="https://www.facebook.com/cumbucooceanview/" /></a>
                    <img src="images/cumbuco-hotel.gif" alt="Cumbuco Hotel" width="1" height="1" />
                    <a href="https://www.instagram.com/cumbucohotel/" target="_blank"><img src="images/instagram.png" alt="Instagram Cumbuco Hotel" width="16" height="16" longdesc="https://www.instagram.com/cumbucohotel/" /></a>
                    <img src="images/cumbuco-hotel.gif" alt="Cumbuco Hotel" width="1" height="1" />
                  <a href="https://www.twitter.com/CumbucoBrazil/" target="_blank"><img src="images/twitter.png" alt="Twitter" width="16" height="16" longdesc="https://www.twitter.com/CumbucoBrazil/" /></a></p>

**Comment by CU61** [comment]
Sorry, the html code is converted here automatically...

**Comment by ArkadiuszMichalski** [comment]
Put your code as [described on the wiki]( https://github.com/notepad-plus-plus/notepad-plus-plus/wiki/FAQ#how-to-open-a-new-issue).

**Comment by donho** [comment]
And please provide more explicit title instead of `Bug report`

**Comment by CU61** [comment]
Multi lines are not supported anymore when pasting these in the Replace function.
Easy enough?
How rude is that closing a threat?!

**Comment by ArkadiuszMichalski** [comment]
Duplicate of https://github.com/notepad-plus-plus/notepad-plus-plus/issues/6058.
