### ISSUE TITLE
Request : Add split window option

### ISSUE THREAD

**Issue by jmroyb** [notepad-plus-plus/notepad-plus-plus#10527]
Due "Notepad++ is a free [...] **source code editor** ...", add an split window option to facilitate the text comparison within the same file, as Visual Studio has:

![image](https://user-images.githubusercontent.com/4932314/132652980-1a81ac0a-8709-4e8b-bb77-850636b4440c.png)

Thanks

**Comment by ArkadiuszMichalski** [comment]
Try clone command:
https://npp-user-manual.org/docs/views/#move-clone

**Comment by jmroyb** [comment]
Solved. Thanks!
