### ISSUE TITLE
Disabling dark mode in preferences does not set back icon type used in light mode. When starting in light mode with "Standard icons : small"

### ISSUE THREAD

**Issue by GryXion** [notepad-plus-plus/notepad-plus-plus#10544]
### Description of the Issue
Enabling dark mode reset toolbar ui, but Disabling dark mode does not make it back to previous one for standards icons specificaly.

Hi, in notepad ++ since version 8.1.0 up to 8.1.4, in WINDOWS version 32bits and 64bits alike.

Bug tested on 8.1 up to 8.1.4 on WINDOWS 7 and WINDOWS 10 lastest update, in 32bits and 64bits version not portable, installed with installer .msi for windows.

### Steps to Reproduce the Issue
1.  open notepad++
2.  click on toolbar => "Settings"
3.  in "General" check Standard icons : small
4. then on "Dark Mode" menu in settings panel still, click on checkbox "Enable dark mode"
5. The unexpected/ might be wanted and not bothering me happen : in General, Toolbar panel is set to "Fluent UI: small"
6. The really unexpected thing is, going back to "Dark Mode" in settings, Disabling darkmode with a click on checkbox "Enable dark mode"
7. In General panel in settings, Toolbar panel is still set in "Fluent UI: small" or whatever was set in dark mode enabled, but do not revert to the setting that was set in light mode.

### Expected Behavior
1. I expected that disabling dark mode would put back on the previous settings that was present in light mode, before dark mode was enable.
In my case, it would be to show up "Standard icons : small again" that was up in light mode when dark mode is disable.
2. _And if possible un option to keep the current Tool bar icon size and type when darkmode is enable/disable. Or a way to keep light mode settings in light mode, and dark mode settings in dark mode.

i think there is a need to think about it to not impact wrongly other people expectation, as such, maybe a setting, or something to keep the current settings of light mode, and a way to get back to light mode settings would be great. I did not figure it out the best way yet, thx for your help.

### Actual Behavior
"Standard icons : small again" is not reset on when dark mode is disable, while it was on before dark mode beeing enable.

### Debug Information
Bug is present from v8.1.0 to v8.1.4 checked in WIN10 and WIN7, in both 64 and 32 bits, and both not portable version. unknown on the other versions

exemple :
Notepad++ v8.1.4   (32-bit)
Build time : Aug 21 2021 - 12:58:42
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : 
Admin mode : ON
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 7 Professional (32-bit) 
OS Build : 7601.23642
Current ANSI codepage : 1252
Plugins : CustomizeToolbar.dll mimeTools.dll NppConverter.dll NppExport.dll PluginManager.dll 

Thx for taking the time to check and correct that behavior if you can, and dimme it worth it , dark mode is awesome ;)

This is my first post on notepad++ thx for your kind awareness.

**Comment by ArkadiuszMichalski** [comment]
Was asked and rejected https://github.com/notepad-plus-plus/notepad-plus-plus/issues/10212.

**Comment by adamtheaustin** [comment]
Please review the two attached images (one where Dark Mode was Never Enabled).
I don't know what "small icons" are but this looks very different than just small icons.
![DarkModeNeverEnabled](https://user-images.githubusercontent.com/93656956/145053121-2741fe16-190e-461c-9a4b-7c33ff3c4d85.png)
![DarkModeDisabledAndToolbarIsBrokenAsInLostColor](https://user-images.githubusercontent.com/93656956/145053123-4b99f29e-3f5c-42a1-ad42-da0e108ba06e.png)
