### ISSUE TITLE
npp.8.1.4.Installer.x64.exe file is identified by VirusTotal as malicious

### ISSUE THREAD

**Issue by alexeiroz** [notepad-plus-plus/notepad-plus-plus#10543]
### Description of the Issue

npp.8.1.4.Installer.x64.exe file is identified by VirusTotal as malicious.

### Steps to Reproduce the Issue

https://www.virustotal.com/gui/file/27e6e296dbe7c5d5f069604c1f0f97a4d5e09f9c4bbb4e98f328ca0d77179e9b/detection

### Expected Behavior

No waning at https://www.virustotal.com

#### 1 match for rule FlowCloud RAT (TA410 Campaign) by Ariel Millahuel from SOC Prime Threat Detection Marketplace
RAT has the capability to take access of the keyboard, applications, mouse, screen and system processes. Also, according to ProofPoint's investigation, TA410 has a lot of similarities with APT10
#### 3 matches for rule Regsvr32 Network Activity by Dmitriy Lifanov, oscd.community from Sigma Integrated Rule Set (GitHub)
Detects network connections and DNS queries initiated by Regsvr32.exe
#### 3 matches for rule Regsvr32 Network Activity by Dmitriy Lifanov, oscd.community from Sigma Integrated Rule Set (GitHub)
Detects network connections and DNS queries initiated by Regsvr32.exe
#### 4 matches for rule File deletion via CMD (via cmdline) by Ariel Millahuel from SOC Prime Threat Detection Marketplace
Detects "cmd" utilization to self-delete files in some critical Windows destinations.
#### 1 match for rule Always Install Elevated Windows Installer by Teymur Kheirkhabarov (idea), Mangatas Tondang (rule), oscd.community from Sigma Integrated Rule Set (GitHub)
This rule will looks for Windows Installer service (msiexec.exe) when it tries to install MSI packages with SYSTEM privilege
#### 1 match for rule Non Interactive PowerShell by Roberto Rodriguez @Cyb3rWard0g (rule), oscd.community (improvements) from Sigma Integrated Rule Set (GitHub)
Detects non-interactive PowerShell activity by looking at powershell.exe with not explorer.exe as a parent
#### Matches rule MALWARE-CNC DNS Fast Flux attempt from Snort registered user ruleset
trojan-activity
#### Matches rule PROTOCOL-DNS SPOOF query response with TTL of 1 min. and no authority from Snort registered user ruleset
bad-unknown
#### Matches rule AutoIT_Script by @bartblaze from ruleset AutoIT at https://github.com/bartblaze/Yara-rules
Identifies AutoIT script.

**Comment by dail8859** [comment]
I'd guess a false positive since it is just one reporting possible issues. This happens occasionally with N++ related files. Usually within a few days you can rescan it and it reports fine. For the security-conscious users I'd suggest stay on an old version for now.

**Comment by Docteh** [comment]
@alexeiroz I'm not seeing the juicy information on that virustotal page. The worst I can see is that under Behavior, select "VirusTotal ZenBox" and you'll find that under Crowdsource IDS Rules the installed does a DNS request to 8.8.8.8 Otherwise I am not seeing the juicy information.
![image](https://user-images.githubusercontent.com/190571/134796461-bd304f69-6d8c-4401-81d2-038528222e02.png)

If you look under the Relations tab down at "Execution Parents" it seems like there is a LOT of very sketch looking programs are placing copies of this particular installer onto peoples hard drives? 
![image](https://user-images.githubusercontent.com/190571/134796825-e57473bf-36eb-45aa-8854-3e9cfd5cef6c.png)

**Comment by dail8859** [comment]
Closing since this is for an older version. The newest version (8.1.9.2) of the Notepad++ installers scan completely clean now.
