### ISSUE TITLE
Greyed out Play button

### ISSUE THREAD

**Issue by gnomontosunlight** [notepad-plus-plus/notepad-plus-plus#10554]
### Description of the Issue
<Suddenly, as of the latest version of notepad-plus-plus, the Play button (for playing macros) is greyed out. Hence, it cannot be used, even if a macro is loaded within the program. Still, recorded and saved macros can be loaded within the program, as turns out if a macro is loaded first and then exucuted through a hotkey assigned to it (I actually did this - afterwards - to overcome this problem - no hotkey was assigned to the macro before). So, it appears that the macro can still be loaded an run (and still can be used within notepad-plus-plus), though only if operated via a hotkey for that macro.>

### Steps to Reproduce the Issue

<1. Click on the Play button within the Task Bar - now greyed out.
2. To no avail, of course; in fact, that could be seen in advance, so maybe, to save a click, do not even do that, and just do nothing instead.
3. >

### Expected Behavior

<Playing of the loaded macro after clicking on that - as expected not greyed out - button .>

### Actual Behavior

<(Lack of behavior.)>

### Debug Information

<Notepad++ v8.1.4   (64-bit)
Build time : Aug 21 2021 - 13:04:59
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : 
Admin mode : ON
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 10 Pro (64-bit) 
OS Version : 2009
OS Build : 19043.1237
Current ANSI codepage : 1252
Plugins : BetterMultiSelection.dll mimeTools.dll NppConverter.dll NppExport.dll qkNppReverseLines.dll SessionMgr.dll>

<Edit: OS Version (given by notepad-plus-plus) not correct: should be 21H1>

**Comment by donho** [comment]
Cannot reproduced in v8.1.4
