### ISSUE TITLE
Document list - Selected file color is almost indistinguishable from background color

### ISSUE THREAD

**Issue by arfmach** [notepad-plus-plus/notepad-plus-plus#10555]
### Description of the Issue
In the Document List panel, without using Dark Mode, the current file should be easily distinguishable from other files, by using a color with a good contrast from the background.

### Steps to Reproduce the Issue
1. Make sure Dark Mode is off
1. Open more than one file
1. Activate the Document List panel
1. Click anywhere away from the Document List panel itself (e.g. in the file content)

### Expected Behavior
The current file indication in the Document Panel should be clearly visible.

### Actual Behavior
The current file indication color (`#1A1A1A`) is almost the same as the background color (`#1E1E1E`).

### Debug Information
Notepad++ v8.1.4   (32-bit)
Build time : Aug 21 2021 - 12:58:42
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : OFF
Dark mode : OFF
Cloud Config : c:\Users\username\Dropbox\Notepad++
OS Name : Windows 10 Enterprise (64-bit) 
OS Version : 2009
OS Build : 19043.1237
Current ANSI codepage : 1252
Plugins : LuaScript.dll mimeTools.dll NppConverter.dll NppExport.dll NppTextFX.dll NppToolBucket.dll XMLTools.dll 

![image](https://user-images.githubusercontent.com/7331118/133449857-6669ed6b-c5f0-4a7e-ac28-3794ff685de7.png)

**Comment by ArkadiuszMichalski** [comment]
Still having this problem in the latest version 8.1.9?

**Comment by arfmach** [comment]
@ArkadiuszMichalski
> 
> 
> Still having this problem in the latest version 8.1.9? You can try with [portable version](https://github.com/notepad-plus-plus/notepad-plus-plus/wiki/Testing#using-the-latest-release-portable-version-of-notepad) to eliminate configuration problem.

Yes, it is still the same. When the focus is in the Document List panel, the selection has a different color, but when the focus is in the file editor panel, the Document List selection loses contrast from background. Notice that I'm not using the new Dark Mode**¹**, I've set up stylers to show dark colors, way before N++ had dark mode. I switched to Dark Mode, and the selection color in Document List has a good contrast, but then all stylers changed (because the theme was also switched to "DarkModeDefault.xml"); if I select the previous "Default (stylers.xml)" (still using Dark Mode), then the Document List selection color goes back to the low-contrast value (but I didn't find any styler item that changes it).

**¹** You can see, in my screenshot, that the menu and toolbar are still using light mode.

**Comment by HolterPhylo** [comment]
I see the same problem, it is a bit annoying.  Please correct this color or allow us to configure it.

**Comment by brudra0** [comment]
Even I faced this problem. I'm in v8.2.1 with DarkModeDefault theme. Kindly, fix this issue.

**Comment by ozone10** [comment]
Fixed in https://github.com/notepad-plus-plus/notepad-plus-plus/commit/d3b026bfeb96eb39e0402673d68dd04e640e2e1e

**Comment by arfmach** [comment]
> Fixed in [d3b026b](https://github.com/notepad-plus-plus/notepad-plus-plus/commit/d3b026bfeb96eb39e0402673d68dd04e640e2e1e)

Notice that I'm **not** using Dark Mode… I mentioned that in [my previous comment](https://github.com/notepad-plus-plus/notepad-plus-plus/issues/10555#issuecomment-959495408).

**Comment by ozone10** [comment]
@brudra0, @arfmach 
Notice that this fix is in commit after v8.4.2 was released, so it's not in v8.4.2.
In light mode you won't be able to change color for focus or highlight, but there will be focus rectangle, which should help you to distinguish active tab.
![image](https://user-images.githubusercontent.com/55940305/173189612-6fd405b8-b16e-44f4-9efe-d91f7d99904d.png)

**Comment by Skrell** [comment]
I see this was closed but unfortunately this color is used in other sub-windows but without the focus rectangle (such as explorer plugin)  can you please give option to change this color to something more visible.

**Comment by alankilborn** [comment]
>such as explorer plugin

Plugins are not associated with Notepad++ core (what this site is for).
You'd have to request this of Explorer plugin author.
