### ISSUE TITLE
Syntax highlighter doesn't support Javascript template strings

### ISSUE THREAD

**Issue by tresdin** [notepad-plus-plus/notepad-plus-plus#1055]
Javascript syntax highlighter still can't recognize [template strings](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/template_strings) which are defined with backticks ``` `` ```. For example, this code ``` `My name is ${a}. I'm 25.;` ``` is being highlighted as `code${code}code` instead of `string${code}string`.

**Comment by dail8859** [comment]
This is also present in the latest version of Scintilla, which is what Notepad++ uses for its syntax highlighting. This bug should instead be reported to that project on [SourceForge](http://sourceforge.net/projects/scintilla/).

**Comment by linquize** [comment]
Similar problem exists for shell script syntax too!

**Comment by monk-time** [comment]
Duplicate: #661
