### ISSUE TITLE
Pasting Java code (a .json file) into Notepad++ pastes in as highlighted red with yellow characters - why?

### ISSUE THREAD

**Issue by deejay52** [notepad-plus-plus/notepad-plus-plus#10560]
### Description of the Issue
I am a newbie to Notepad++ and Java Script and when I paste a piece of java code into a blank (new) Notepad++ document, it pastes in as highlighted red with yellow characters. Before I proceed, I wanted to find out if this is intentional and if so, what does it indicate to the user?

How did I get to the problem?
1.  I am running Notepad++ V8.1.4 32bit on a PC running Windows 10 V10.0.19043.1202
2.  I am running Microsoft Edge Version 93.0.961.52 (Official build) (64-bit)
2.  I am using documentation (from this PDF: https://www.sdrplay.com/docs/ADSBpluginBeta.pdf.  
3.  Using the directions found on pages 26 & 27 of the PDF, I entered variables on the webpage delineated in the directions. The user then takes the generated Java code (by selecting CTRL-U in Edge) and pastes it into a file with the extension .json.
4. I selected the Java code, copied it, then pasted it into Notepad++ where it was presented as highlighted red with yellow characters.

What I didn't expect was the highlighting and the yellow characters and would like to know if this indicates that something is awry or if I may have misunderstood something in the process (not the process in the PDF but the process of pasting code into Notepad++ and saving it as a .json file)

Thank you ahead of time - hopefully I haven't wasted anyone's time!
//dj

Here is a screenshot of the data in Notepad++
![notepad++_screenshot](https://user-images.githubusercontent.com/56799090/133826709-7aa5240e-56a1-4668-abcf-df0302406967.jpg)

Debug Info:
Notepad++ v8.1.4   (32-bit)
Build time : Aug 21 2021 - 12:58:42
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Command Line : "C:\ProgramData\SDRplay\public_html\upintheair.json"
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 10 Home (64-bit) 
OS Version : 2009
OS Build : 19043.1202
Current ANSI codepage : 1252
Plugins : mimeTools.dll NppConverter.dll NppExport.dll

**Comment by dail8859** [comment]
Please provide a small easy-to-reproducible example. A screenshot of Notepad++ would also be helpful.

Please also provide your Notepad++ debug information as requested in the issue template.

**Comment by thomassmith311** [comment]
Can you please provide a download link to the problematic file?

**Comment by deejay52** [comment]
> Can you please provide a download link to the problematic file? And if you go to Settings (on the top bar) >> Style Configurator, and select JSON for language and then DEFAULT for style, what are the foreground and background colors? It seems like your program might be configurated such that the foreground is yellow and the background is red.

Hi Thomas... the Style Configurator shows black characters on a white background.  Here is a link to the file that I am talking about https://drive.google.com/file/d/1fdqLN8KzukMTT2K3UKlXnrhnDJ57naR8/view?usp=sharing  I apologize ahead of time - don't quite know how to use the Hyperlink tool here!  Thank you ahead of time for any help on this.

**Comment by mere-human** [comment]
What you have here looks like HTML code with pieces of JavaScript.
Try changing language to HTML:
![image](https://user-images.githubusercontent.com/9664141/133898666-b1367c4c-bd9e-4c1b-ad20-1b4e9cc794fa.png)
