### ISSUE TITLE
"Empty box" character in status bar ONLY in dark mode.

### ISSUE THREAD

**Issue by bokeron2020** [notepad-plus-plus/notepad-plus-plus#10564]
I use Windows 10 x64 + NPP v8.1.4
I'm attaching an image showing the problem I'm experiencing.
Apparently, from the screenshots I've seen from others, it's not a common issue. However, I can reproduce it easily:

- Install NPP
- Defaults to light mode > no problem
- **Change to dark mode > problem**
- Change to light mode > no problem

Might be related to the font NPP uses for its UI? Could I change it to test if that's the case?

![Compare](https://user-images.githubusercontent.com/63074669/133896856-f78babe8-2e5c-4236-8bac-c5cea5df9ab8.png)

**Comment by adzm** [comment]
While I am surprised this is not occurring everywhere if this is indeed the bug, my immediate thought is this:

```
DrawText(hdc, str.data(), static_cast<int>(str.size()), &rcPart, DT_SINGLELINE | DT_VCENTER | DT_LEFT);
```

the str was allocated as the character count + 1 to be safe with the null terminator, but this means the .size() passed to DrawText is one too many. Really we should be able to just use -1 and let DrawText calculate the text size itself since the string should be null terminated regardless.

**Comment by bokeron2020** [comment]
That's why I asked about the font NPP uses for its UI.

On a vanilla Windows 10 home/pro/... install, there's no problem.
On a modified version, the problem appears revealing this consequence of the programming choice made. Not a bug in itself though it would be nice if it was reconsidered at some point to prevent this.

Meanwhile, maybe I just need to add back some font that was removed, so I'm asking for any info that helps me prevent this behaviour happening on my side.

**Comment by adzm** [comment]
PR for this created, https://github.com/notepad-plus-plus/notepad-plus-plus/pull/10611

**Comment by donho** [comment]
@bokeron2020 
Could you try the fixed binary (of #10611): [32 bits binary](https://ci.appveyor.com/project/donho/notepad-plus-plus/builds/40976607/job/si9urn8872r504ix/artifacts) or [64 bits binary](https://ci.appveyor.com/project/donho/notepad-plus-plus/builds/40976607/job/bmo7ctuhdpvn39wr/artifacts) and confirm us it's fixed ?

**Comment by bokeron2020** [comment]
Excuse me for not answering before. Real life problems, etcetera.

I've just tried both 32 and 64 bits. The problem is solved in these binaries!

**Comment by donho** [comment]
Thank you @bokeron2020 for your confirmation!
