### ISSUE TITLE
Windows 11 Context Menu

### ISSUE THREAD

**Issue by System32-0** [notepad-plus-plus/notepad-plus-plus#10565]
### Description of the Issue
Windows 11 context menu for "Edit with Notepad++" is buried within the new context menu

### Steps to Reproduce the Issue

1. Download windows 11 beta (or dev)
2. Install NPP
3. Right click a file to "edit with notepad++"

### Expected Behavior
"Edit with notepad++" should be on the first context menu, not buried.

### Actual Behavior
Normally "Edit with Notepad++" is in the context menu when right clicking a file within windows. With windows 11 build 21H2 you now have to Right click a file > Show more options > Edit with notepad++

Its far easier to just have it in the first context menu, not buried within the menu

### Debug Information
Notepad++ v8.1.4   (32-bit)
Build time : Aug 21 2021 - 12:58:42
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Command Line : "C:\Users\my-st\Desktop\Arma\AltisLife.Altis\ZDGaming.Altis\initPlayerServer.sqf"
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 10 Enterprise (64-bit) 
OS Version : 2009
OS Build : 22000.194
Current ANSI codepage : 1252

Current Windows version is 
https://gyazo.com/dc1d62060a2ed340fbe09fc8f17b7ff7

**Comment by donho** [comment]
Implemented in #13170
