### ISSUE TITLE
[Feature Request]: Use language of installed version instead of OS language as default in updater

### ISSUE THREAD

**Issue by OliverBurgert** [notepad-plus-plus/notepad-plus-plus#10582]
### Description of the Issue

The N++ installer asks for the installation language. The default seems to be set to the OS language (or current location). For people who want their installation in a different language, it would be convenient to have the language of the installed version as a default. Since many developers in non-English speaking countries prefer English for coding, this would be beneficial for many people.

### Steps to Reproduce the Issue

1.  Open updater e.g. on a German Windows computer while having installed the English version of notepad++.

### Expected Behavior

Language of the installed version should be set as default.

### Actual Behavior

OS language is set as default.

**Comment by mere-human** [comment]
But in theory, if a user has Windows OS set in certain language then they should be able to understand it.
I can imagine if we do this change, then other part of people who prefer the OS language, would complain.

**Comment by OliverBurgert** [comment]
> But in theory, if a user has Windows OS set in certain language then they should be able to understand it.
> I can imagine if we do this change, then other part of people who prefer the OS language, would complain.

But those people would still have their native language as default since they installed the previous version in their language.

For a first-time installation, the OS language is a great default choice, but for updating an existing installation, the user-preferred option (which could be the OS language) should be the default.

**Comment by User5981** [comment]
I second this, my OS is in French but I use NP++ in English.
A good behaviour would be :   
- 1st install: Language selection list of the installer should be preset on the OS language
- Updates: Language selection list of the installer should be preset on the language selected in NP++ settings
note : The installer language can stay the OS one, all we want is the language pre-selection being set on the language we use NP++ with to save time when installing.

**Comment by User5981** [comment]
> It seems a reasonable feature request. However, I don't see the way to make NSIS memorize it. If anyone have any idea for fixing it, your PR is welcome.

Well i'm just a guitar teacher but NSIS can apparently read txt files so there maybe a way to parse the NP++ config.xml to get the language preference? 
Just my two cents.

**Comment by heatgithub** [comment]
> 

Waiting for this suggested improvement!
