### ISSUE TITLE
"Minimize to System Tray" doesn't work

### ISSUE THREAD

**Issue by Sparktank** [notepad-plus-plus/notepad-plus-plus#1058]
v6.8.5, Windows 7 SP1 (x64). Logged in as Admin, no other accounts on PC.
In preferences, "minimisze to system tray" is checked but it will not minimize to tray anymore.
I've opened it and done nothing but change settings on/off then closed it so settings get saved.
I renamed the "plugins" folder and started NP++ to confirm it wasn't any of the plugins.
The only thing I haven't done was uninstall uninstall/re-install NP++ entirely.
The icon also no longer appears in the list of "Notifications Area Icons" to customize states between "show/hide icon and nofications" and "only show notifications".

**Comment by Eldaw** [comment]
See this:
https://github.com/notepad-plus-plus/notepad-plus-plus/commit/44e9a03101e132fad856da449f422c1a515c0d36

**Comment by Sparktank** [comment]
Ah. Okay. I can live without it then.
Creating a non-Admin instance or a secondary account is too much effort than its actual worth.
I'm willing to let this close.
Thanks for the information.
