### ISSUE TITLE
The UDL dialog has no indicator whether current UDL is for Dark Mode or not

### ISSUE THREAD

**Issue by ivan-u7n** [notepad-plus-plus/notepad-plus-plus#10584]
### Description of the Issue
Currently in the UDL dialog there is neither an indicator to see whether current UDL is for Dark Mode or not, nor a way to change it. This can be done only by checking and changing the corresponding XML file.

### Steps to Reproduce the Issue
1. Open the UDL dialog.

### Expected Behavior
![image](https://user-images.githubusercontent.com/81974034/134400813-2556b2cc-8eb3-46f8-a629-0bc3f266faec.png)

### Actual Behavior
![image](https://user-images.githubusercontent.com/81974034/134400988-dab7c009-e705-43fb-8cf5-498e3d4f203d.png)

### Debug Information
```
Notepad++ v8.1.4   (64-bit)
Build time : Sep 22 2021 - 20:47:49
Built with : GCC 8.1.0
Path : F:\develop\git\notepad-plus-plus\bin.x86_64\notepad++.exe
Command Line : -multiInst
Admin mode : OFF
Local Conf mode : ON
Cloud Config : OFF
OS Name : Windows 10 Enterprise LTSC 2019 (64-bit) 
OS Version : 1809
OS Build : 17763.2183
Current ANSI codepage : 1251
Plugins : none
```

**Comment by donho** [comment]
It's rather an indicator for UDL author. Besides, this indicator (boolean) is not used (so far) in the code. So it's not necessary at all to add UI for it.
