### ISSUE TITLE
Preferences Window Rendering Lag

### ISSUE THREAD

**Issue by Lothrik** [notepad-plus-plus/notepad-plus-plus#10585]
### Description of the Issue
Dragging the Preferences window around uses an unreasonable amount of CPU (via dwm.exe and notepad++.exe) and visibly lags on modern hardware. This issue also exists with other windows (such as the Style Configurator window and Find window) to a lesser degree (high CPU utilization but below the threshold for it to lag).

### Steps to Reproduce the Issue

1. Open the Preferences window.
2. Drag the Preferences window around while monitoring dwm.exe and notepad++.exe CPU utilization.

### Expected Behavior
Minimal (<2%) CPU utilization.

### Actual Behavior
Extreme CPU utilization (20%+ on a i5-9600K).

### Debug Information
Notepad++ v8.1.4   (32-bit)
Build time : Aug 21 2021 - 12:58:42
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Command Line : 
Admin mode : ON
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 10 Enterprise (64-bit) 
OS Version : 2004
OS Build : 19041.1237
Current ANSI codepage : 1252
Plugins : DSpellCheck.dll mimeTools.dll NppConverter.dll NppExport.dll 

Example CPU utilization while dragging around the Preferences window:
![](http://puu.sh/Idldr/50930c35c7.png)
![](http://puu.sh/Idljw/524b0348cc.png)

**Comment by mere-human** [comment]
Try with x64 version of Notepad++ and see if the problem is still present.

**Comment by Lothrik** [comment]
The issue persists after switching to the x64 version.

**Comment by donho** [comment]
Dragging the dialog of any application around uses an unreasonable amount of CPU. It's not an issue to me.

**Comment by slavapv** [comment]
I have the same issue. But in my case it is even worse. It feels like you drag the mouse and after ~1 second window changes its position. It is really laggy.
