### ISSUE TITLE
`from` should not be highlighted as javascript keyword

### ISSUE THREAD

**Issue by M393** [notepad-plus-plus/notepad-plus-plus#10592]
### Description of the Issue
When javascript is selected as the language keywords are highlighted, but `from` is not a keyword, it should be treated as a normal variable / function name.

### Steps to Reproduce the Issue
1. Open new document
2.  Set language to javascript
3. type `from`

### Expected Behavior
the text should not be highlighted

### Actual Behavior
the text was highlighted as if it were a keyword

### Debug Information
Notepad++ v8.1.4   (32-bit)
Build time : Aug 21 2021 - 12:58:42
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Command Line : 
Admin mode : ON
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 7 Professional (64-bit) 
OS Build : 7601.0
Current ANSI codepage : 1252
Plugins : ComparePlugin.dll mimeTools.dll NppConverter.dll NppExport.dll NPPJSONViewer.dll XMLTools.dll 

![image](https://user-images.githubusercontent.com/56256405/134656097-9407682d-d409-469d-b195-c4a5125a9b5b.png)

**Comment by rimrul** [comment]
It does seem to be a keyword as [part of an `import` statement](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/import).

**Comment by M393** [comment]
Oh, indeed. Though it is allowed as a variable name unlike other keywords which tripped me up.
I suppose Notepad++ does not understand the syntax to differentiate.
