### ISSUE TITLE
Editing .md files in dark mode

### ISSUE THREAD

**Issue by timint** [notepad-plus-plus/notepad-plus-plus#10593]
Editing .md files in dark mode is a challenge. Maybe someone has a fix for that?
I thought I would bring this up as it's been this way for many versions now.

![image](https://user-images.githubusercontent.com/359192/134749469-eb6b3ac8-8b9a-4afa-ab2d-16abf7b6ce8c.png)

**Comment by timint** [comment]
And so I discovered a separate Language setting for dark mode markdown which feels half baked. Is it not possible to have it honouor the selected style theme instead?

![image](https://user-images.githubusercontent.com/359192/134749774-700787bd-b4dd-471c-83c1-732166b644e4.png)

**Comment by thomassmith311** [comment]
Those Markdown settings are actually "User Defined Languages" created with Edditoria: https://github.com/Edditoria/markdown-plus-plus.

You'll need to go to that link and follow the instructions.
> 
    Download the source code in latest release page. It should be a zip file.
    Open the zip file and go to <udl\> folder.
    Copy a XML file of your favorite theme, and paste in <userDefineLangs\> folder of Notepad++.
        (The directory is usually <%AppData%\Notepad++\userDefineLangs\>.)
    Restart Notepad++.
    Open and test with a Markdown file e.g. test/at-a-glance.md.

Copy the XML file of whatever theme you're using (looks look Obsidian?) into the userDefineLangs folder, close and reopen N++, and it should be there. That link also tells you how to create custom MD files for your own custom themes.

**Comment by timint** [comment]
I want to thank you for the time and effort spent in replying to me. I see the markdown support is a complete side project.

Indeed it is Obsidian. Well spotted. 😀

I copied `markdown-plus-plus-master.zip\udl\markdown.obsidian.udl.xml` to `%appdata%\Notepad++\userDefineLangs\` and that solved the problem, thank you. Is this the intended solution by design? Or is this just a workaround due to framework limitations?

Spontaneously I would have thought the most optimal implementation would be to add it as a Language like any other languages built in. Yeah, markdown is not a language, but seeing YAML in the list makes me think why not? But then I am a web developer and cpp is just not my thing. Maybe @Edditoria have some good input on this?

**Comment by rdipardo** [comment]
> I would have thought the most optimal implementation would be to add it as a Language like any other languages built in.

You're not alone; to quote from this [this related thread](https://github.com/notepad-plus-plus/notepad-plus-plus/issues/5600#issuecomment-609781469):

> [. . .] Scintilla has markdown support builtin for ages. And then suddenly markdown was implemented as a UDL instead of utilizing what was already within reach.

While N++ could just as well use [Scintilla's Markdown lexer](https://github.com/ScintillaOrg/lexilla/blob/master/lexers/LexMarkdown.cxx) (the way [Geany does](https://github.com/geany/geany/blob/master/scintilla/lexers/LexMarkdown.cxx)), I would say you're better off using @Edditoria's implementation. The Scintilla version is kind of a neglected, bit-rotten, legacy module; and UDL's are much quicker to develop and update than lexer libraries.

**Comment by timint** [comment]
I personally wouldn't mind if the syntax colors are a bit different. It's the highlight coloring of the text background that I find most critical. If it could only be transparent.

Is it not possible to just some of the colors from the global style?

![image](https://user-images.githubusercontent.com/359192/134947402-5b0351f8-5dcc-4ce1-9a62-fbce902602e6.png)

**Comment by CennoxX** [comment]
@timint This is possible with the colorStyle attribute
> The <WordsStyle> colorStyle attribute decides whether to use the defined colors from fgColor and bgColor attributes, or to use the default color setting 

https://npp-user-manual.org/docs/user-defined-language-system/

I think the WordStyles of markdown should use colorStyle="0" for DEFAULT and for most other colorStyle="1".

**Comment by thomassmith311** [comment]
> I personally wouldn't mind if the syntax colors are a bit different. It's the highlight coloring of the text background that I find most critical. If it could only be transparent.
> 
> Is it not possible to just inherit some of the colors from the global style?
> 
> ![image](https://user-images.githubusercontent.com/359192/134947402-5b0351f8-5dcc-4ce1-9a62-fbce902602e6.png)

So if we look at the actual xml file (in geany):
![image](https://user-images.githubusercontent.com/19561856/135692461-37a413d3-4fe3-4102-bd1b-8dcfa180b1b7.png)
![image](https://user-images.githubusercontent.com/19561856/135692500-60364777-b7da-446e-8973-3c75ee9028dc.png)

We can see that a "bgColor" setting is necessary, and since it is a hex code, transparency isn't possible.

**Comment by CennoxX** [comment]
@thomassmith311 Did you read my comment? As I said, it is possible, just use the colorStyle attribute.
![grafik](https://user-images.githubusercontent.com/6975881/135807220-8ea41c74-0874-4607-9bc5-641ceb36131e.png)

My changes were adding colorStyle in the Style section:
```
        <Styles>
            <WordsStyle name="DEFAULT" fgColor="DCDCCC" bgColor="3F3F3F" colorStyle="0" fontName="" fontStyle="0" nesting="0" />
            <WordsStyle name="COMMENTS" fgColor="7F9F7F" bgColor="3F3F3F" colorStyle="1" fontName="" fontStyle="2" nesting="0" />
            <WordsStyle name="LINE COMMENTS" fgColor="FF8040" bgColor="3F3F3F" colorStyle="1" fontName="" fontStyle="1" nesting="0" />
            <WordsStyle name="NUMBERS" fgColor="8CD0D3" bgColor="3F3F3F" colorStyle="0" fontName="" fontStyle="0" nesting="0" />
            <WordsStyle name="KEYWORDS1" fgColor="EDD6ED" bgColor="3F3F3F" colorStyle="1" fontName="" fontStyle="0" nesting="0" />
            <WordsStyle name="KEYWORDS2" fgColor="FF8040" bgColor="3F3F3F" colorStyle="1" fontName="" fontStyle="1" nesting="0" />
            <WordsStyle name="KEYWORDS3" fgColor="E3CEAB" bgColor="3F3F3F" colorStyle="1" fontName="" fontStyle="3" nesting="0" />
            <WordsStyle name="KEYWORDS4" fgColor="E3CEAB" bgColor="3F3F3F" colorStyle="1" fontName="" fontStyle="1" nesting="0" />
            <WordsStyle name="KEYWORDS5" fgColor="E3CEAB" bgColor="3F3F3F" colorStyle="1" fontName="" fontStyle="2" nesting="0" />
            <WordsStyle name="KEYWORDS6" fgColor="E3CEAB" bgColor="3F3F3F" colorStyle="1" fontName="" fontStyle="3" nesting="0" />
            <WordsStyle name="KEYWORDS7" fgColor="E3CEAB" bgColor="3F3F3F" colorStyle="1" fontName="" fontStyle="3" nesting="0" />
            <WordsStyle name="KEYWORDS8" fgColor="DCDCCC" bgColor="3F3F3F" colorStyle="1" fontName="" fontStyle="0" nesting="0" />
            <WordsStyle name="OPERATORS" fgColor="DFC47D" bgColor="3F3F3F" colorStyle="1" fontName="" fontStyle="1" nesting="0" />
            <WordsStyle name="FOLDER IN CODE1" fgColor="DCDCCC" bgColor="3F3F3F" colorStyle="0" fontName="" fontStyle="0" nesting="0" />
            <WordsStyle name="FOLDER IN CODE2" fgColor="DCDCCC" bgColor="3F3F3F" colorStyle="0" fontName="" fontStyle="0" nesting="0" />
            <WordsStyle name="FOLDER IN COMMENT" fgColor="DCDCCC" bgColor="3F3F3F" colorStyle="0" fontName="" fontStyle="0" nesting="0" />
            <WordsStyle name="DELIMITERS1" fgColor="EDD6ED" bgColor="3F3F3F" colorStyle="1" fontName="" fontStyle="2" nesting="0" />
            <WordsStyle name="DELIMITERS2" fgColor="CEDF99" bgColor="3F3F3F" colorStyle="1" fontName="" fontStyle="0" nesting="0" />
            <WordsStyle name="DELIMITERS3" fgColor="E3CEAB" bgColor="3F3F3F" colorStyle="1" fontName="" fontStyle="3" nesting="0" />
            <WordsStyle name="DELIMITERS4" fgColor="E3CEAB" bgColor="3F3F3F" colorStyle="1" fontName="" fontStyle="1" nesting="65600" />
            <WordsStyle name="DELIMITERS5" fgColor="E3CEAB" bgColor="3F3F3F" colorStyle="1" fontName="" fontStyle="2" nesting="32800" />
            <WordsStyle name="DELIMITERS6" fgColor="E3CEAB" bgColor="3F3F3F" colorStyle="1" fontName="" fontStyle="3" nesting="0" />
            <WordsStyle name="DELIMITERS7" fgColor="E3CEAB" bgColor="3F3F3F" colorStyle="1" fontName="" fontStyle="3" nesting="0" />
            <WordsStyle name="DELIMITERS8" fgColor="DCDCCC" bgColor="3F3F3F" colorStyle="1" fontName="" fontStyle="0" nesting="0" />
        </Styles>
```

**Comment by thomassmith311** [comment]
@CennoxX Didn't see that comment. (just hid my comment as it's unhelpful.) Yeah, I just tried that xml on all the themes and it works perfectly for all of them. We should probably get this in a pull request.

**Comment by thomassmith311** [comment]
I made a pull request with a single udl file that should work with all notepad++ themes - that way, we won't need multiple Markdown options; the user should just be able to select "Markdown" and it work with whatever theme they want, whether custom or one of the default.
https://github.com/notepad-plus-plus/notepad-plus-plus/pull/10621
