### ISSUE TITLE
Cloud still broken in 6.7.8.1

### ISSUE THREAD

**Issue by Arbitel** [notepad-plus-plus/notepad-plus-plus#106]
@donho  Hmm, apparently it is still broken in 6.7.8.1..

![image](https://cloud.githubusercontent.com/assets/2641332/7735907/ecb7c208-ff05-11e4-9ea3-b8ea2df2ae66.png)

**Comment by ariccio** [comment]
Xref: Issue #6

**Comment by milipili** [comment]
Which one does not work as expected ?

**Comment by milipili** [comment]
See 5e240147c51b6c27f1accbcfa191d9ddc4967e68
