### ISSUE TITLE
Style Configurator for JavaScript doesn't work for background (until line end)

### ISSUE THREAD

**Issue by eyeofchaos** [notepad-plus-plus/notepad-plus-plus#10603]
### Description of the Issue
I was missing the blue background color for JavaScript files, so I tried to get it back by setting the blue background in stylers.xml for "JavaScript" in all available fields, but it doesn't fill all areas (until line end).

### Steps to Reproduce the Issue

1. Open Settings - Style Configurator - JavaScript
2. Set all available fields for background color to "242, 244, 255"

### Expected Behavior
The behavior, Notepad++ worked until around 6.6.9 (the version I was using before), which means JavaScript files had a colored background.

### Actual Behavior
The background is not completely colored, as it doesn't fill all the lines until the line end.

### Note:
If I open my stylers.xml (line 618) and set the language name from "javascript.js" to simply "javascript" it works **_exactly_** as expected. So this is my workaround for the time being.

### Debug Info:
Notepad++ v8.1.5   (32-bit)
Build time : Sep 26 2021 - 15:15:32
Path : C:\Users\ds\Downloads\Notepad\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : ON
Cloud Config : OFF
OS Name : Windows 10 Home (64-bit) 
OS Version : 2009
OS Build : 19043.1237
Current ANSI codepage : 1252
Plugins : none

Best wishes
Dieter Schmitt

**Comment by ArkadiuszMichalski** [comment]
Your code exists in a separate js files or maybe embedded in html?

**Comment by eyeofchaos** [comment]
I mean a separate file (*.js)

**Comment by eyeofchaos** [comment]
As of 8.4 my temporary fix doesn't work anymore.

**Comment by eyeofchaos** [comment]
Ok, I finally managed to edit langs.xml and stylers.xml to completely suit my needs.
So, no need to change the default settings anymore, at least not for me :)

Best wishes.
