### ISSUE TITLE
[Bug] Notepad++ closes when moved to the background

### ISSUE THREAD

**Issue by IAmSurajBobade** [notepad-plus-plus/notepad-plus-plus#10605]
### Notepad++ closes when sent to the background and When reopened tabs like 'Folder as Workspace' does not render when opened again [I think this is a bug]

I am observing this issue when I started using:
- Notepad++ v8.1.4
- Enabled 'Dark mode' (Black tone)
- Installed 'Customise Toolbar' plugin

### Steps to Reproduce the Issue
1. Enable the following tabs:
![image](https://user-images.githubusercontent.com/11486375/135262036-80baf359-a6f7-43df-b210-8f665eade2bd.png)
2. Open any text file
3. Move Notepad++to background
4. Notice that Notepad++ is closed
5. Open Notepad++
6. Notice that tabs are not opened
7. Close Notepad++ manually, and relaunch again
8. Notice that tabs are now visible

### Expected Behavior
Notepad++ should keep running in the background with all configured tabs open

### Actual Behavior
Notepad++ closes

### Debug Information
Notepad++ v8.1.4   (64-bit)
Build time : Aug 21 2021 - 13:04:59
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 10 Enterprise (64-bit) 
OS Version : 1909
OS Build : 18363.1801
Current ANSI codepage : 1252
Plugins : CodeAlignmentNpp.dll DSpellCheck.dll NppEditorConfig.dll NPPJSONViewer.dll NppPluginDemo.dll XMLTools.dll _CustomizeToolbar.dll 

Before moving Notepad++ to background:
![image](https://user-images.githubusercontent.com/11486375/135262779-7e08d619-2373-44cc-a194-6f29d164eec7.png)
After opening Notepad++ manually for the first time:
![image](https://user-images.githubusercontent.com/11486375/135262872-8d87f7dc-57a7-43a7-ae91-8665a57d06eb.png)

**Comment by ArkadiuszMichalski** [comment]
What happend without plugins?

**Comment by IAmSurajBobade** [comment]
I installed , removed all related files. Then did a fresh install, now I do not see this issue is reproduced.
Please note, I had added a new plugin (not available in the plugin manager) for testing for a couple of days. I started observing this issue, after I removed it.

**Comment by IAmSurajBobade** [comment]
As I am not able to reproduce it and it may have been caused due to bad plugin usage, I am closing this issue.
