### ISSUE TITLE
enabling directwrite breaks monospace and font

### ISSUE THREAD

**Issue by KrekerInGaming-ITA** [notepad-plus-plus/notepad-plus-plus#10608]
### Description of the Issue

was trying to enable fira code font ligatures, followed the steps in the guide, but instead of that, the font changed and the style config is useless to fix it, only thing i found working was deleting the config file
### Steps to Reproduce the Issue

1. enable directwrite in preferences
2. boom, font is changed to something else
3. 

### Expected Behavior

enabled ligatures and nothing else
### Actual Behavior

major "jam-up" of the font, possibly changes fonts without style config
### Debug Information

Notepad++ v8.1.4   (64-bit)
Build time : Aug 21 2021 - 13:04:59
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 10 Pro (64-bit) 
OS Version : 2009
OS Build : 19042.1237
Current ANSI codepage : 1252
Plugins : mimeTools.dll NppConverter.dll NppExport.dll 

also, somehow adding an emoji enables ligatures on the current line, do not know why that works

**Comment by KrekerInGaming-ITA** [comment]
((may be a really stupid reason but i am stupider than it so i cannot find))

**Comment by mfaizsyahmi** [comment]
Please reopen this issue. It's not an isolated issue as I and at least one other person are having this problem, and whatever fixed the submitter's issue should be looked at for a possible fix for the issue. See: https://github.com/notepad-plus-plus/notepad-plus-plus/issues/2287#issuecomment-1062837753

**Comment by hfellner** [comment]
Yes, please reopen this issue - I am experiencing this issue also, and it did not go away across multiple updates of Notepad++. Enabling DirectWrite makes the Scintilla component revert to its default non-monospace font, regardless of what is configured in the settings. Disabling DirectWrite brings fonts back, but does not support ligatures. This problem started somewhere around version 8.4.0, until then DirectWrite worked just fine to display ligatures.

**Comment by gorodoe** [comment]
I do also have the same issue:

When DirectWrite is enabled in the settings, certain fonts will not display at all, instead some sort of fallback font is used. So far I can't tell exactly which characteristic of fonts especially will result in this. A few examples of font that's will not display when directWrite is enabled: Arial Black/Rounded/Narrow (Default from microsoft) i.e. usually font weight other than its regular weight usually won't work (when the 'regular' works, the italic, condensed, bold, etc will not; e,g. Calibri works, calibri light does not, Candara works, candara light does not, dejavu Sans work, Dejavu Sans light and condensed does not), plain Courier (not Courier New), Input Mono (all weight),
