### ISSUE TITLE
Can't find undo/redo keyboard shortcuts 

### ISSUE THREAD

**Issue by ttodua** [notepad-plus-plus/notepad-plus-plus#10617]
I use N++ 8.1.4 .
Under `Tools>Shortcut Mapper>Main menu` I no longer find a field to assign custom keyboard shortcuts to "undo/redo" actions (instead of CTRL+Z/Y).  However, on previous Windows installation I remember that I had a custom binding, but don't remember how I setup that. Any hints?

**Comment by dail8859** [comment]
They are under the `Scintilla Commands` tab.

![image](https://user-images.githubusercontent.com/3694843/135849842-17c283da-6311-49e9-b40f-65a83a3716f3.png)
