### ISSUE TITLE
[FR] Add "Open With Notepad++" to Windows 11 context menu

### ISSUE THREAD

**Issue by filimonic** [notepad-plus-plus/notepad-plus-plus#10628]
Possible dup of [10565](https://github.com/notepad-plus-plus/notepad-plus-plus/issues/10565)

Add option to register NPP for file types to make NPP be in RMB-Click menu
![image](https://user-images.githubusercontent.com/2893566/136275108-108ef813-69ee-41f6-a980-bf51462d93ae.png)

Like this:
![image](https://user-images.githubusercontent.com/2893566/136275220-8d966c8a-5dfd-4a0f-bb6c-7130c616e33c.png)

**Comment by rimrul** [comment]
> Possible dup of 10565

Also of #10300
