### ISSUE TITLE
Error message appear when 2 hyphens in comments

### ISSUE THREAD

**Issue by vligithub** [notepad-plus-plus/notepad-plus-plus#10626]
### Description of the Issue
Message "Syntaxe incorrecte utilisée dans un commentaire" / "Incorrect syntax use in a comment"
When a comment contains 2 hyphens (--) an error message appears in red color and yellow background color.

### Steps to Reproduce the Issue

1. type 
4. save then look at the message appear in the text

### Expected Behavior
Nothing instead of the error

### Actual Behavior
An error is occured in the editor only

### Debug Information
Notepad++ v8.1.4   (32-bit)
Build time : Aug 21 2021 - 12:58:42
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 10 Enterprise (64-bit) 
OS Version : 1909
OS Build : 18363.959
Current ANSI codepage : 1252
Plugins : ComparePlugin.dll mimeTools.dll NppConverter.dll NppExport.dll XMLTools.dll

**Comment by rimrul** [comment]
That error message seems to come from the XMLTools plugin.
