### ISSUE TITLE
Saving files that I don't need

### ISSUE THREAD

**Issue by zubenkovadim** [notepad-plus-plus/notepad-plus-plus#10625]
I almost always have temporary information in my open tabs that I need for something, but not for saving to a file.

I usually just close these tabs without saving the data. It is very convenient and practical.

But when I want to save some tab to a file and press ctrl + s, I get to save all the tabs in turn. And initially those tabs are saved that I do not need.

Please make sure that when you click on ctrl + s, only the tab that is currently open is saved, and the rest remain untouched.

**Comment by dail8859** [comment]
As mentioned, `Ctrl+S` is by default just to save the current file. You may need to check your shortcut mapper to see if something got modified. If the issue still persist please follow the issue template and provide a step by step example how to reproduce the issue along with your Notepad++ debug information.
