### ISSUE TITLE
Move "Normal text" language directly to the top of the Language menu

### ISSUE THREAD

**Issue by butlnor** [notepad-plus-plus/notepad-plus-plus#10630]
"Normal text" is not one of the languages, but something like a default view. It should not be hidden somewhere deep under "N". Every file can be displayed in its own language, or as a normal text. So "Normal text" is a special thing, and not equal to the other languages.

Please move "Normal text" to a separate menu item, at the top of the Language menu.

**Comment by dail8859** [comment]
Next time please follow the issue template. Closing as this is currently implemented.
