### ISSUE TITLE
Feature request: Match dark mode with the OS

### ISSUE THREAD

**Issue by leodoi3** [notepad-plus-plus/notepad-plus-plus#10644]
Could you please add an option to match dark mode with the current OS setting?

**Comment by takanuva15** [comment]
Yes please; major IDEs like IntelliJ/VSCode as well as the Chrome browser and the "Dark Reader" extension support the feature to automatically switch the theme of the app/site to match the theme of the OS. I have my computer set to automatically switch to dark theme after sunset and then switch back to light theme in the morning (using [Auto Dark Mode](https://github.com/AutoDarkMode/Windows-Auto-Night-Mode)), which naturally matches the amount of sunlight in my room during those parts of the day so I don't strain my eyes as much when using the computer.

I haven't messed around with the Windows SDK too much, but there's already an IntelliJ plugin that checks the OS theme and swaps the theme of the IDE to match when the OS theme changes. The raw implementation is located in the .cpp file here: https://github.com/weisJ/auto-dark-mode/blob/master/windows/src/main/cpp/DarkModeWindows.cpp

I imagine we could leverage some of the code in there to swap the theme in Npp too, though I'm not well-versed in the internals of Npp.

**Comment by Mennaruuk** [comment]
Yup. This feature would be a great addition to Notepad++. Chameleons change their colors, it's only fitting that Notepad++ switches to dark when it's night!

**Comment by YakovL** [comment]
Besides "me too", let me note that the dark mode is governed by `HKCU:\SOFTWARE\Microsoft\Windows\CurrentVersion\Themes\Personalize\AppsUseLightTheme .AppsUseLightTheme` registry value (I've tested that it's enough to [switch it](https://superuser.com/a/1724237/576393) to make all the apps supporting "follow system setting" feature repaint).

**Comment by CennoxX** [comment]
Duplicates of #9183
