### ISSUE TITLE
List for the tabs

### ISSUE THREAD

**Issue by snoitallicso** [notepad-plus-plus/notepad-plus-plus#10649]
I need a list for the tabs because not all tabs fits in the screen width. Team of the Mozilla Firefox solved this problem by adding additional button on the right  (V).

![Capture](https://user-images.githubusercontent.com/28826339/136802305-4ebcfca0-03b3-4705-87f1-dc2f6ac23e0e.PNG)

**Comment by ArkadiuszMichalski** [comment]
You can use Document List Panel, Document Switcher, Windows, Tab Bar...If that's not enough then write what is missing.
