### ISSUE TITLE
Shell doesn't register on ARM based systems

### ISSUE THREAD

**Issue by FlashD** [notepad-plus-plus/notepad-plus-plus#10640]
### Description of the Issue
The provided shell file NppShell_06.dll in the ARM package fails to register with Windows on ARM. The end result is the same using both the installer or registering it by hand.

### Steps to Reproduce the Issue

1. Install Notepad++ using the installer.
2. Try to open any file using the context menu
2. Notice missing "Edit with Notepad++" in context menu
3. Open CMD with elevated privileges
4. Navigate to the folder Notepad++ is installed at
5. Try to register the NppShell_6.dll with "regsvr32 /i NppShell_6.dll"

### Actual Behavior

<img width="671" alt="Error2" src="https://user-images.githubusercontent.com/5943012/136655522-4d1ed230-f704-4139-9b61-309313df9e2f.png">

### Debug Information

Notepad++ v8.1.5   (ARM 64-bit)
Build time : Sep 26 2021 - 15:10:12
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 10 Pro (Unknown-bit) 
OS Version : 2009
OS Build : 19043.1237
Current ANSI codepage : 1252
Plugins : HexEditor.dll

**Comment by donho** [comment]
could you provide me your `NppShell_06.dll` so I can make sure it's arm64 architecture ?

**Comment by jof284** [comment]
I attempted to install v8.4.4 and the installer attempts to call multiple instances of Microsoft Register Server (regsvr32) eventually locking up the machine. I tested this with Windows 11 Pro (22000.832) on a Lenovo X13s (Snapdragon (TM) 8cx Gen 3, 16 GB RAM).
