### ISSUE TITLE
"Style all occurences of token" on Highlighted text with spaces is broken.

### ISSUE THREAD

**Issue by dagordo** [notepad-plus-plus/notepad-plus-plus#10654]
### Description of the Issue
"Style all occurences of token" on Highlighted text with spaces is broken.

### Steps to Reproduce the Issue
1. highlight some text that contains spaces in an opened file
2. right click on it and then go to "Style all occurences of token" then click on "Using first style"
3. text is not colored using the selected style.

### Expected Behavior
The text string selected should be highlighted, but it's not.

### Actual Behavior
The text remains not highlighted.

### Debug Information
Notepad++ v8.1.2   (32-bit)
Build time : Jul 16 2021 - 01:56:21
Path : D:\appz\npp.8.1.2.portable\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : ON
Cloud Config : OFF
OS Name : Windows 10 Enterprise (64-bit) 
OS Version : 2009
OS Build : 19042.1237
Current ANSI codepage : 1252
Plugins : MarkdownViewerPlusPlus.dll mimeTools.dll NppConverter.dll NppExport.dll 

I disabled the MarkdownViewerPlusPlus plugin to see if it might be source of this problem, but it's not.
**I reproduced it in both 8.1.2 and 8.1.5 versions.**

**Comment by dagordo** [comment]
Hi, sorry for the delay.
Thank you guys for your answers.
@ArkadiuszMichalski that was the problem ! I can finally analyze my traces and logs again :)
May be it should be that way by default ?

**Comment by ArkadiuszMichalski** [comment]
>May be it should be that way by default?

Style All and Smart Highlighting have this enabled by default. If it was also the default in previous versions, there is no point in changing it. Anyone can change it if necessary.

**Comment by cancuengt** [comment]
Upvote this. I was looking for this a bug but the setting change fixed it. I have used Notepad++ for long time and I really do not remember having set the setting off when started using it, instead use it without the setting. This changed after the update to the version 8.1.5 (64bit).
+99.9% of the time I do not want only the whole word but the selection.
> @vertigo220 Totally agree with everything you said. I think that 99.99999% of the time I don't want the default setting, and for the other cases I just get around, doing it another way. And I'm pretty sure it's the same for everybody. But may be the devs @ArkadiuszMichalski have a good reason to let it enabled by default.

**Comment by querykuma** [comment]
Same issue occurs at the latest 8.3.1.

Here is the step.
1. Download "npp.8.3.1.portable.zip" and launch notepad++.exe. Notepad++ v8.3.1   (32-bit).
2. Write the text.
```
,aaa,
|,aaa,
,aaa,|
|,aaa,|
| ,aaa, |
,aaa,
```

3. Select the fist ",aaa,".
4. Search > Style All Occurrence of Token > Using 1st Style.
![aaa](https://user-images.githubusercontent.com/44793169/154788294-69f7f34b-70f3-42e9-bf83-96911e6a27d9.png)

**Expected Behavior**

All Occurrence of ",aaa," has the style.

**Comment by alankilborn** [comment]
@querykuma 

I guess you didn't bother to read the user manual for the styling feature, or the above discussion.

With these settings:

![image](https://user-images.githubusercontent.com/77065706/154798013-264f8f91-a27c-490a-b9c2-5d0e88b3eb48.png)

This is the result on your data:

![image](https://user-images.githubusercontent.com/77065706/154798024-44f1cb55-9003-4482-ba64-332ac69597ee.png)

**Comment by alankilborn** [comment]
OP was satisfied with resolution of this issue.
Recommend CLOSURE of this item.

**Comment by ArkadiuszMichalski** [comment]
This can be controlled with Preferences dialog.
