### ISSUE TITLE
Open With dialog for all files should include N++ in Windows 11

### ISSUE THREAD

**Issue by FadeMind** [notepad-plus-plus/notepad-plus-plus#10653]
### Description of the Issue
Windows 11 provides new UWP Notepad app.
Hack replacing notepad.exe via Debugger registry value does not work anymore here.
OFC you can set assocate all required file extensions.

Sadly Notepad++ is not seen in suggested app list for not known files.
Notepad UWP is.

### Steps to Reproduce the Issue

1. Install Notepad++
2. Try open editable file not registered with Notepad++ for seen Open with dialog.
3. Notepad++ it is not listed here. 

### Expected Behavior
Open With dialog for all files should include N++

### Actual Behavior
Notepad++ is missed in Open With dialog for not registered files. 

### Debug Information
Notepad++ v8.1.6   (64-bit)
Build time : Oct 10 2021 - 14:10:29
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 10 Pro (64-bit)
OS Version : 2009
OS Build : 22000.194
Current ANSI codepage : 1250
Plugins : mimeTools.dll NppConverter.dll NppExport.dll 

### Screenshot

![s](https://community.notepad-plus-plus.org/assets/uploads/files/1627487071513-20210728-1627487034.png)

### Reference

- https://community.notepad-plus-plus.org/topic/21570/open-with-dialog-for-all-files-should-include-n?_=1634017402297

**Comment by dbpm1** [comment]
Hey guys, below you'll find version of the .reg file for **Notepad++ x86**: 

`Windows Registry Editor Version 5.00

[HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\notepad.exe]
"Debugger"="c:\\Program Files (x86)\\Notepad++\\notepad++.exe -notepadStyleCmdline -z"
"UseFilter"="0"

[HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\notepad.exe\0]
"AppExecutionAliasRedirect"=dword:00000001
"AppExecutionAliasRedirectPackages"="*"
"FilterFullPath"="notepad++.exe"

[HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\notepad.exe\1]
"AppExecutionAliasRedirect"=dword:00000001
"AppExecutionAliasRedirectPackages"="*"
"FilterFullPath"="notepad++.exe"

[HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\notepad.exe\2]
"AppExecutionAliasRedirect"=dword:00000001
"AppExecutionAliasRedirectPackages"="*"
"FilterFullPath"="notepad++.exe"
`

**Comment by donho** [comment]
Use the new explorer context menu entry "Edit with Noteapd++" under Windows 11 : #13170
