### ISSUE TITLE
French slang in french.xml

### ISSUE THREAD

**Issue by angerized** [notepad-plus-plus/notepad-plus-plus#10656]
### Description of the Issue
As referenced in issue [2723 ](https://github.com/notepad-plus-plus/notepad-plus-plus/issues/2723) there is still slang in the French.xml translation.

### Steps to Reproduce the Issue
1. CTRL+G in French locale 
2. "Zyva !" is french slang, called "verlan". It could be translated to "Let's go, yo!", or "Come on, yo!". Absolutely not professional.
3. "Je vais nulle part" is literally "I'm not going anywhere"

### Expected Behavior
More professional translations:
"Zyva" -> "Aller à"
"Je vais nulle part" -> "Annuler"

**Comment by bermau** [comment]
Bien que cela soit assez drôle; il est totalement ridicule d'utiliser de l'argot dans une traduction. Cela ne peut que diminuer la crédibilité du logiciel auprès des utilisateurs. 

Do not use slang. Use good french !
