### ISSUE TITLE
JSON syntax highlighter colors broken

### ISSUE THREAD

**Issue by domStrazzullo** [notepad-plus-plus/notepad-plus-plus#10663]
### Description of the Issue
JSON language highlighter colors is broken

### Steps to Reproduce the Issue
1. Settings > Style Configurator > JSON language
2. Setting syntax highlighter colors
3. 

### Expected Behavior
Highlighter color changes

### Actual Behavior
The color you set for NUMBER affects the stringed properties instead
The color you set for DEFAULT affects the BOOLEAN AND NULL instead
The color you set for STRING or OPERATOR doesn't affect anything

### Debug Information
Notepad++ v8.1.4   (32-bit)
Build time : Aug 21 2021 - 12:58:42
Path : D:\APPLICATIONS\Notepad++\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : ON
Cloud Config : OFF
OS Name : Windows 10 Enterprise (64-bit) 
OS Version : 2009
OS Build : 19043.1237
Current ANSI codepage : 1252
Plugins : ColorPicker.dll combine.dll ComparePlugin.dll DSpellCheck.dll ExtSettings.dll HexEditor.dll JSLintNpp.dll JSMinNPP.dll mimeTools.dll NppConverter.dll NppExport.dll NPPJSONViewer.dll QuickText.dll _CustomizeToolbar.dll

**Comment by lokpro** [comment]
try using themes: Obsidian, DansLeRuSH-Dark, Zenburn, and DarkModeDefault.
The json styling is only defined in those four themes.

https://github.com/notepad-plus-plus/notepad-plus-plus/issues/7936#issuecomment-929083459

**Comment by donho** [comment]
Cannot reproduce with my v8.1.6:
![image](https://user-images.githubusercontent.com/90293/137364105-208d7e1c-3d96-4d10-8a64-43d1baf3540c.png)
