### ISSUE TITLE
Cannot drag and drop files in Notepad++ Administrator

### ISSUE THREAD

**Issue by Sashank999** [notepad-plus-plus/notepad-plus-plus#10665]
### Description of the Issue
Cannot drag and drop files to open in Notepad++ Administrator mode.

### Steps to Reproduce the Issue
1. Open Notepad++ as Administrator.
2. Open a folder in Windows Explorer.
3. Drag a file from that folder to Notepad++.

### Expected Behavior
The file should be opened normally.

### Actual Behavior
The cursor turns into a black "disabled" icon, something similar to this: https://images.app.goo.gl/AjFt5iZDEzfFs5256 .

### Debug Information
Notepad++ v8.1.5   (64-bit)
Build time : Sep 26 2021 - 15:23:23
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : 
Admin mode : ON
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 10 Pro (64-bit) 
OS Version : 2009
OS Build : 19043.1237
Current ANSI codepage : 1252
Plugins : Linter.dll mimeTools.dll NppConverter.dll NppExport.dll TagLEET.dll 

I first found this when opening a file in "mingw64/lib". It is a protected folder, only for Administrators. So I tried this on the files in regular desktop folders but they didn't work either.
I tried opening Notepad++ via Administrator Command Prompt but the issue persisted.

**Comment by rddim** [comment]
Confirm

```
Notepad++ v8.1.6   (64-bit)
Build time : Oct 10 2021 - 14:10:29
Path : D:\npp.8.1.6.portable.minimalist.x64\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : ON
Cloud Config : OFF
OS Name : Windows 10 Pro (64-bit) 
OS Version : 2009
OS Build : 19043.1165
Current ANSI codepage : 1251
Plugins : none
```
Also (just for the test) the same issue appear with v6.9

**Comment by dail8859** [comment]
My understanding is that this is a Windows OS security "feature" and not caused by Notepad++ itself.

Dragging from a non elevated process (explorer) is not allowed to send data to an elevated process (Notepad++).

I see the exact same behavior trying other editors such as Visual Studio or VS Code. I know there has been some discussion about this on the community forum...not sure if there was a work around or not.
