### ISSUE TITLE
.log files does not save changes

### ISSUE THREAD

**Issue by magentox** [notepad-plus-plus/notepad-plus-plus#10672]
.log files doesn't save changes

1. Open a .log file delete all logs inside
2. Save
3. All data are still here. You can **add** data or delete **some** data on a .log and save the file. In such case it saves the file. If you delete all data in the file, it doesn't save the file.

It also happens with .js and .php files

**Comment by BayerMeister** [comment]
I found the same, but have additional information:
N++ won't overwrite a file, if the new state of the file is empty.
Eg.: I have a CSV that gets filled from outside N++, I trim it to zero (Ctrl+A, Delete) and on saving it behaves as it would save, bude the file is unchanged. If however I add a space or whatever and then save, the file ends up correctly saved (though not empty, as I wanted it).
