### ISSUE TITLE
Unicode Symbol Display Issue

### ISSUE THREAD

**Issue by mruno** [notepad-plus-plus/notepad-plus-plus#10679]
Deleting or interacting with some unicode symbols changes them to blocks:
⊣ (8867) ⊢ (8866) ⊥ (8869) ⊤ (8868)
https://imgur.com/a/NQupYFK

### Steps to Reproduce the Issue
1. Copy/Paste the following characters: ⊣ ⊢ ⊥ ⊤
2.  Backspace/delete some of them. Type (test) or moving keyboard cursor

### Expected Behavior
Not change unicode symbols to empty blocks, but keep the symbols legible

### Actual Behavior
Unicode symbols change to blocks

### Debug Information
Notepad++ v8.1.5   (64-bit)
Build time : Sep 26 2021 - 15:23:23
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 10 Home (64-bit) 
OS Version : 2009
OS Build : 19042.1288
Current ANSI codepage : 1252
Plugins : DSpellCheck.dll mimeTools.dll NppConverter.dll NppExport.dll

**Comment by Docteh** [comment]
Hello, to be clear on a simplified bug reproduction example, are these steps correct? I was unable to reproduce.
1. Click New
2. Paste `⊣ ⊢ ⊥ ⊤`
3. Press backspace, deleting the last character
4. type `test`
5. output will be garbled in some way and NOT look like this
![image](https://user-images.githubusercontent.com/190571/137606786-65baafec-9f3a-4b76-a47c-b99db7de250f.png)

Notepad++ v8.1.7   (32-bit)
Build time : Oct 15 2021 - 01:17:20
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 10 Home (64-bit) 
OS Version : 2009
OS Build : 19043.1237
Current ANSI codepage : 1252
Plugins : DSpellCheck.dll mimeTools.dll NppConverter.dll NppExport.dll NppFTP.dll TopMost.dll

**Comment by Docteh** [comment]
I don't see anything in the release notes for 8.1.7 that would indicate a fix, So, I recorded this little clip, and **THEN** realized that for your imgur album, when I click on the image it shows a video, thanks for recording it.  

Would you mind saving the two boxes you get after backspacing `⊣ ⊢ ⊥ ⊤` into a text file and then just attaching it to this issue? I'm curious to see how its corrupted.

https://user-images.githubusercontent.com/190571/137653672-c0d76b6b-3aa3-4cbb-85de-0a7b142da60c.mp4

Decimal | Code point | Char | UTF-8 HEX | Name   
-- | -- | -- | -- | --
8866 | U+22A2 | ⊢ | e2 8a a2 | RIGHT TACK   
8867 | U+22A3 | ⊣ | e2 8a a3 | LEFT TACK 
8868 | U+22A4 | ⊤ | e2 8a a4 | DOWN TACK   
8869 | U+22A5 | ⊥ | e2 8a a5 | UP TACK

**Comment by ArkadiuszMichalski** [comment]
Have you tried with [DirectWrite enabled](https://github.com/notepad-plus-plus/notepad-plus-plus/wiki/FAQ#incorrect-character-rendering)?

**Comment by mruno** [comment]
> Have you tried with [DirectWrite enabled](https://github.com/notepad-plus-plus/notepad-plus-plus/wiki/FAQ#incorrect-character-rendering)?

That fixed it, thanks!
