### ISSUE TITLE
Slow saving of config files

### ISSUE THREAD

**Issue by dtfinch** [notepad-plus-plus/notepad-plus-plus#10674]
### Description of the Issue
When I exit the latest Notepad++, or save a configuration change, there's a long pause due to unbuffered writes. 

### Steps to Reproduce the Issue
1. Start Notepad++
2. Exit Notepad++

### Expected Behavior
It should exit almost instantly.

### Actual Behavior
It spent 0.7 seconds writing a 10kb config.xml in thousands of small, unbuffered increments.

I saved a log from the SysInternals Process Monitor showing the exit activity:
[NPPexit.zip](https://github.com/notepad-plus-plus/notepad-plus-plus/files/7355314/NPPexit.zip)

### Debug Information
Notepad++ v8.1.7   (32-bit)
Build time : Oct 15 2021 - 01:17:20
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Command Line : 
Admin mode : ON
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 7 Professional (64-bit) 
OS Build : 7601.0
Current ANSI codepage : 1252
Plugins : mimeTools.dll NppConverter.dll NppExport.dll NppTextFX.dll

**Comment by donho** [comment]
@dtfinch 
Could you please check #10691 and confirm me if the issue is fixed?
