### ISSUE TITLE
UDL : when creating from SQL, everything (keywords) are lost.

### ISSUE THREAD

**Issue by grauziitisos** [notepad-plus-plus/notepad-plus-plus#10682]
### Description of the Issue

When trying to create an UDL that would inherit from SQL the whole data set (everything specified for the sql language in notepad++ languages.xml file) is lost, resulting in an empty language. When I select markdown from user languages, all data for that one is there. Switching back - still empty language!

 ( In an ideal world with infinite time and immortality I would aim for sql+html+javascript+shortcodes+css+escaped chars (like \" being treated as non-escaped - like " when coloring)). But lets return to the reality, for now it will be sufficient, if shortcodes will match (and/or at least) color.
 A shortcode is like an xml tag just marker character pair is square brackets instead of greater than / less than pair ( [parenttag attribute="value here"][something]some content[/something][anothersomething attr="val" anotherattr="escapedHtmlCodeHere"]some content in this one, sometimes html code, at some instances with escaped double quotes \", at other with non-escaped double quotes " , but both variants work at the end, no noticeable difference, so have no idea why some escaped some not. And have not enough free time to research it.[/anothersomething]   [/parenttag] )
### Steps to Reproduce the Issue

1. open an empty file and paste the example sql code  from the next comment from me here, following this issue description (containing wordpress shortcodes code) in notepad++ 8.1.7 64-bit
2. you may also save the file as .sql file or simply select sql from the languages menu (language -> s -> sql)
3. further steps in video. Sorry it is 4:27 morning, I want to sleep and am tired of long typing
NB! please TURN OFF VIDEO SOUND prior to watching, annoying warning sound inside and one instance of cursing.

https://user-images.githubusercontent.com/85872382/137606722-5051da80-f330-4501-8c20-d364145a560c.mp4

### Expected Behavior

everything defined in the language selected (this case sql ) being imported to the language editor and exported to the xml file
### Actual Behavior

empty editor, blank (templated defaults) xml file 
### Debug Information

Notepad++ v8.1.7   (64-bit)
Build time : Oct 15 2021 - 01:20:46
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 10 Home (64-bit) 
OS Version : 2009
OS Build : 19042.1237
Current ANSI codepage : 1252
Plugins : HTMLTag.dll mimeTools.dll NppConverter.dll NppExport.dll NPPJSONViewer.dll XMLTools.dll

**Comment by grauziitisos** [comment]
-- Content Post
INSERT INTO `wpni_posts` (`ID`, `post_author`, `post_date`, `post_date_gmt`, `post_content`, `post_title`, `post_excerpt`, `post_status`, `comment_status`, `ping_status`, `post_password`, `post_name`, `to_ping`, `pinged`, `post_modified`, `post_modified_gmt`, `post_content_filtered`, `post_parent`, `guid`, `menu_order`, `post_type`, `post_mime_type`, `comment_count`) VALUES
(NULL, 1, '2021-08-29 15:18:11', '2021-08-29 15:18:11', '[et_pb_section fb_built=\"1\" custom_padding_last_edited=\"on|desktop\" admin_label=\"HeaderCommon\" _builder_version=\"4.4.6\" use_background_color_gradient=\"on\" background_color_gradient_start=\"#fb803e\" background_color_gradient_direction=\"45deg\" background_image=\"http://localhost/wp-content/uploads/2020/05/COMPANY-scaled.jpg\" parallax=\"on\" width=\"100%\" module_alignment=\"center\" height=\"1372px\" height_tablet=\"\" height_phone=\"2023px\" height_last_edited=\"on|phone\" custom_margin=\"0px|40px|803px|40px|false|true\" custom_margin_tablet=\"\" custom_margin_phone=\"||921px||false|true\" custom_margin_last_edited=\"on|phone\" custom_padding=\"36px|0px|25px||false|false\" custom_padding_tablet=\"40px||||false|false\" custom_padding_phone=\"\" border_radii_phone=\"on|20px|20px|20px|20px\" border_radii_last_edited=\"off|desktop\"][et_pb_code raw_content_tablet=\"\" raw_content_phone=\"\" raw_content_last_edited=\"on|desktop\" _builder_version=\"4.4.6\"]<script type="text/javascript">jQuery(document).ready(function(){addStyle(`@media only screen and (max-width: 767px){.et_pb_text_3_tb_body {    min-height: 936px !important;}}@media (min-width: 981px) and (max-device-width: 1024px) 
  and (orientation: portrait) {.et_pb_section_0_tb_body {    height: 1490px!important;} .et_pb_button_0_tb_body_wrapper {    margin-top: 100px!important;    margin-bottom: 10px!important;} .et_pb_row_3_tb_body{ min-height: 1494px!important; }.et_pb_row_6_tb_body {min-height: 1010px;}.et_pb_button_1_tb_body_wrapper{    margin-top: 86px;	}.et_pb_section_1_tb_body{height:1165px}	}`);});</script>[/et_pb_code][et_pb_row custom_padding_last_edited=\"on|tablet\" _builder_version=\"4.4.6\" background_enable_color=\"off\" background_image=\"http://localhost/wp-content/uploads/2020/05/03.jpg\" parallax=\"on\" transform_scale_tablet=\"\" transform_scale_phone=\"\" transform_scale_last_edited=\"on|desktop\" transform_translate=\"30px|0px\" transform_translate_tablet=\"0px|0px\" transform_translate_phone=\"\" transform_translate_last_edited=\"on|tablet\" transform_translate_linked=\"off\" transform_rotate_tablet=\"\" transform_rotate_phone=\"\" transform_rotate_last_edited=\"on|desktop\" transform_skew_tablet=\"\" transform_skew_phone=\"\" transform_skew_last_edited=\"on|desktop\" transform_origin_tablet=\"\" transform_origin_phone=\"\" transform_origin_last_edited=\"on|desktop\" transform_styles_last_edited=\"on|tablet\" position_origin_r=\"bottom_right\" horizontal_offset=\"30px\" position_origin_a_tablet=\"\" position_origin_a_phone=\"\" position_origin_a_last_edited=\"on|phone\" position_origin_f_tablet=\"\" position_origin_f_phone=\"\" position_origin_f_last_edited=\"on|phone\" position_origin_r_tablet=\"\" position_origin_r_phone=\"\" position_origin_r_last_edited=\"on|phone\" width_tablet=\"90%\" width_phone=\"\" width_last_edited=\"on|desktop\" max_width=\"1200px\" custom_margin=\"||30px||false|false\" custom_margin_tablet=\"\" custom_margin_phone=\"||10px||false|false\" custom_margin_last_edited=\"on|phone\" custom_padding=\"45px|60px|45px|60px|true|true\" custom_padding_tablet=\"60px||60px||true|true\" custom_padding_phone=\"0px|10px|0px|10px|true|true\" transform_styles_tablet=\"\" transform_styles_phone=\"\" positioning_tablet=\"\" positioning_phone=\"none\" positioning_last_edited=\"on|phone\" border_radii_phone=\"off|8px|8px||\" border_radii_last_edited=\"off|desktop\" box_shadow_style=\"preset3\" box_shadow_vertical=\"40px\" box_shadow_blur=\"110px\" box_shadow_spread=\"0px\" box_shadow_color=\"rgba(9,6,38,0.62)\" custom_margin__hover_enabled=\"on|desktop\"][et_pb_column type=\"4_4\" _builder_version=\"3.26\"][et_pb_text content_tablet=\"\" content_phone=\"<h1 style=%22text-align:center;%22>Some Title</h1>\r\n\" content_last_edited=\"on|phone\" _builder_version=\"4.4.6\" text_line_height=\"1.8em\" header_font=\"Taviraj||||||||\" header_text_color=\"#f15b33\" header_font_size=\"45px\" header_line_height=\"1.2em\" header_3_font_size=\"19px\" custom_margin_tablet=\"\" custom_margin_phone=\"|9px||9px|false|true\" custom_margin_last_edited=\"on|phone\" text_font_size_tablet=\"\" text_font_size_phone=\"15px\" text_font_size_last_edited=\"on|desktop\" header_font_size_tablet=\"40px\" header_font_size_phone=\"30px\" header_font_size_last_edited=\"on|desktop\"]<h1 style=\"text-align:center;\">Some Title</h1>\r[/et_pb_text][/et_pb_column][/et_pb_row][et_pb_row disabled_on=\"off|on|on\" _builder_version=\"4.4.6\"][et_pb_column type=\"4_4\" _builder_version=\"4.4.6\"][et_pb_image src=\"http://localhost/wp-content/uploads/2020/05/12778893_1008183172554353_4796930443974577085_o-300x300.jpg\" alt=\"Name Surname\" title_text=\"12778893_1008183172554353_4796930443974577085_o\" align=\"center\" _builder_version=\"4.4.6\" custom_margin=\"-385px|-30px||-30px|false|true\" custom_margin_tablet=\"0px||||false|false\" custom_margin_phone=\"\" custom_margin_last_edited=\"on|phone\" custom_padding=\"0px|||||\" box_shadow_style=\"preset4\" box_shadow_horizontal=\"0px\" box_shadow_vertical=\"200px\" box_shadow_color=\"#ffffff\"][/et_pb_image][et_pb_text _builder_version=\"4.4.6\" text_font=\"Taviraj||on||||||\" text_text_color=\"#f15b33\" text_font_size=\"16px\" text_line_height=\"1.8em\" header_5_font=\"Taviraj||||||||\" background_color=\"#ffffff\" max_width_tablet=\"100%\" max_width_phone=\"100%\" max_width_last_edited=\"on|tablet\" custom_margin=\"||-10px||false|false\" custom_padding=\"||0px|||\" custom_padding_tablet=\"\" custom_padding_phone=\"\" custom_padding_last_edited=\"on|desktop\"]<p style=\"text-align: center;\">\"<em>A long smart citation.\"</em></p><p style=\"text-align: right;\"><span style=\"color: #000000;\"><strong>Name Surname </strong></span></p><p><em><span></span></em></p>[/et_pb_text][/et_pb_column][/et_pb_row][et_pb_row column_structure=\"1_2,1_2\" custom_padding_last_edited=\"on|tablet\" _builder_version=\"4.4.6\" background_enable_color=\"off\" background_image=\"http://localhost/wp-content/uploads/2020/05/03.jpg\" parallax=\"on\" transform_scale_tablet=\"\" transform_scale_phone=\"\" transform_scale_last_edited=\"on|desktop\" transform_translate=\"30px|0px\" transform_translate_tablet=\"0px|0px\" transform_translate_phone=\"\" transform_translate_last_edited=\"on|tablet\" transform_translate_linked=\"off\" transform_rotate_tablet=\"\" transform_rotate_phone=\"\" transform_rotate_last_edited=\"on|desktop\" transform_skew_tablet=\"\" transform_skew_phone=\"\" transform_skew_last_edited=\"on|desktop\" transform_origin_tablet=\"\" transform_origin_phone=\"\" transform_origin_last_edited=\"on|desktop\" transform_styles_last_edited=\"on|tablet\" position_origin_r=\"bottom_right\" horizontal_offset=\"30px\" position_origin_a_tablet=\"\" position_origin_a_phone=\"\" position_origin_a_last_edited=\"on|phone\" position_origin_f_tablet=\"\" position_origin_f_phone=\"\" position_origin_f_last_edited=\"on|phone\" position_origin_r_tablet=\"\" position_origin_r_phone=\"\" position_origin_r_last_edited=\"on|phone\" width_tablet=\"90%\" width_phone=\"\" width_last_edited=\"on|desktop\" max_width=\"1200px\" custom_margin_tablet=\"\" custom_margin_phone=\"\" custom_margin_last_edited=\"on|phone\" custom_padding=\"109px|60px|109px|60px|true|true\" custom_padding_tablet=\"60px||60px||true|true\" custom_padding_phone=\"40px|20px|40px|20px|true|true\" hover_enabled=\"0\" transform_styles_tablet=\"\" transform_styles_phone=\"\" positioning_tablet=\"\" positioning_phone=\"none\" positioning_last_edited=\"on|phone\" border_radii_phone=\"off|8px|8px||\" border_radii_last_edited=\"off|desktop\" box_shadow_style=\"preset3\" box_shadow_vertical=\"40px\" box_shadow_blur=\"110px\" box_shadow_spread=\"0px\" box_shadow_color=\"rgba(9,6,38,0.62)\" custom_margin__hover_enabled=\"on|desktop\" custom_css_before_last_edited=\"on|phone\" custom_css_before_phone=\"@media only screen and (max-width: 767px){||.et_pb_section_0_tb_body{||    height: 2023px;||	}||	}\"][et_pb_column type=\"1_2\" _builder_version=\"3.26\"][et_pb_text content_tablet=\"\" content_phone=\"<h1>Work Title 1</h1><h2>( Work Title 2 / Work Title 3 / Work Title 4 )</h2>\r\n<p> </p>\r\n<h3>Certified Work Title 5 (Certificate No 123)</h3>\r\n<h3>Certified Work Title 6 (Certificate No 124)</h3>\r\n<h3>Certified Work Title 7 (Certificate No 125)</h3>\r\n\" content_last_edited=\"on|phone\" _builder_version=\"4.4.6\" text_line_height=\"1.8em\" header_font=\"Taviraj||||||||\" header_text_color=\"#f15b33\" header_font_size=\"45px\" header_line_height=\"1.2em\" header_3_font_size=\"19px\" max_width=\"627px\" max_width_last_edited=\"off|desktop\" custom_margin=\"|-96px||||\" custom_margin_tablet=\"\" custom_margin_phone=\"|9px||9px|false|true\" custom_margin_last_edited=\"on|phone\" text_font_size_tablet=\"\" text_font_size_phone=\"15px\" text_font_size_last_edited=\"on|desktop\" header_font_size_tablet=\"40px\" header_font_size_phone=\"30px\" header_font_size_last_edited=\"on|desktop\"]<h1></h1>\r\n<h1>Work Title 1</h1>\r\n<h2>( Work Title 2 / Work Title 3 / Work Title 4 )</h2>\r\n<p>&nbsp;</p>\r\n<h3>Certified Work Title 5 (Certificate No 123<span>)</span></h3>\r\n<h3>Certified Work Title 6 (Certificate No 124)</h3>\r\n<h3>Certified Work Title 7 (Certificate No 125)</h3>[/et_pb_text][/et_pb_column][et_pb_column type=\"1_2\" _builder_version=\"3.26\"][/et_pb_column][/et_pb_row][et_pb_row column_structure=\"3_5,2_5\" custom_padding_last_edited=\"on|desktop\" _builder_version=\"4.4.6\" background_color=\"#ffffff\" z_index=\"0\" width_tablet=\"90%\" width_phone=\"90%\" width_last_edited=\"on|desktop\" max_width=\"1200px\" min_height=\"1394px\" min_height_tablet=\"\" min_height_phone=\"\" min_height_last_edited=\"on|phone\" height_tablet=\"\" height_phone=\"\" height_last_edited=\"on|phone\" max_height_tablet=\"\" max_height_phone=\"\" max_height_last_edited=\"on|phone\" overflow-x=\"visible\" overflow-y=\"visible\" custom_margin=\"-30px|auto||auto|false|false\" custom_margin_tablet=\"\" custom_margin_phone=\"-30px|auto|6px|auto|false|false\" custom_margin_last_edited=\"on|phone\" custom_padding=\"0px|60px|0px|90px|false|false\" custom_padding_tablet=\"|||60px|false|false\" custom_padding_phone=\"0px|20px|0px|20px|false|true\" module_alignment_tablet=\"\" module_alignment_phone=\"\" module_alignment_last_edited=\"on|phone\" box_shadow_style=\"preset3\" box_shadow_vertical=\"40px\" box_shadow_blur=\"110px\" box_shadow_spread=\"0px\" box_shadow_color=\"rgba(131,146,167,0.5)\" width__hover_enabled=\"off\"][et_pb_column type=\"3_5\" _builder_version=\"3.26\" custom_padding=\"48px||||false|false\"][et_pb_text _builder_version=\"4.4.6\" text_font=\"Taviraj||||||||\" text_font_size=\"16px\" text_line_height=\"1.8em\" header_text_color=\"#f15b33\" header_font_size=\"36px\" header_2_font=\"Taviraj||||||||\" header_2_font_size=\"23px\" header_2_line_height=\"1.2em\" min_height=\"1328px\" min_height_tablet=\"956px\" min_height_phone=\"956px\" custom_margin=\"||-96px||false|false\" custom_margin_tablet=\"\" custom_margin_phone=\"||-90px||false|false\" custom_margin_last_edited=\"on|phone\" custom_padding=\"||0px||false|false\" custom_padding_tablet=\"|30px||50px|true|false\" custom_padding_phone=\"|30px|||true|false\" custom_padding_last_edited=\"off|tablet\" text_font_size_tablet=\"\" text_font_size_phone=\"15px\" text_font_size_last_edited=\"on|desktop\" header_2_font_size_tablet=\"40px\" header_2_font_size_phone=\"30px\" header_2_font_size_last_edited=\"on|phone\"]<p><strong>WORK EXPERIENCE:</strong></p>[/et_pb_text][et_pb_button button_url=\"tel:+11111111\" button_text=\"Call\" button_alignment=\"left\" button_alignment_tablet=\"left\" button_alignment_last_edited=\"off|tablet\" _builder_version=\"4.4.6\" custom_button=\"on\" button_text_size=\"16px\" button_text_color=\"#ffffff\" button_bg_color=\"#f15b33\" button_bg_color_gradient_start=\"#946ef4\" button_bg_color_gradient_end=\"#8857f2\" button_bg_color_gradient_direction=\"172deg\" button_border_width=\"0px\" button_border_color=\"rgba(0,0,0,0)\" button_border_radius=\"0px\" button_font=\"Hind|600|||||||\" custom_margin=\"36px|||||\" custom_margin_tablet=\"116px|||50px|false|false\" custom_margin_phone=\"106px|||0px|false|false\" custom_margin_last_edited=\"on|phone\" custom_padding=\"13px||10px||false|true\" box_shadow_style=\"preset1\" box_shadow_vertical=\"10px\" box_shadow_blur=\"40px\" box_shadow_spread=\"-9px\" box_shadow_color=\"#f15b33\" button_bg_color__hover_enabled=\"off\"][/et_pb_button][/et_pb_column][et_pb_column type=\"2_5\" disabled_on=\"on|off|off\" _builder_version=\"3.26\" overflow-x=\"visible\" overflow-y=\"visible\" custom_padding=\"|30px|30px|30px|false|true\" box_shadow_style=\"preset3\" box_shadow_blur=\"40px\" box_shadow_color=\"rgba(131,146,167,0.3)\"][et_pb_image src=\"http://localhost/wp-content/uploads/2020/05/12778893_1008183172554353_4796930443974577085_o-1024x1024.jpg\" alt=\"Name Surname\" title_text=\"12778893_1008183172554353_4796930443974577085_o\" align=\"center\" _builder_version=\"4.4.6\" custom_margin=\"-385px|-30px||-30px|false|true\" custom_margin_tablet=\"0px||||false|false\" custom_margin_phone=\"\" custom_margin_last_edited=\"on|phone\" custom_padding=\"0px|||||\" box_shadow_style=\"preset4\" box_shadow_horizontal=\"0px\" box_shadow_vertical=\"200px\" box_shadow_color=\"#ffffff\"][/et_pb_image][et_pb_text _builder_version=\"4.4.6\" text_font=\"Taviraj||on||||||\" text_text_color=\"#f15b33\" text_font_size=\"16px\" text_line_height=\"1.8em\" header_5_font=\"Taviraj||||||||\" background_color=\"#ffffff\" max_width_tablet=\"100%\" max_width_phone=\"100%\" max_width_last_edited=\"on|tablet\" custom_margin=\"||-10px||false|false\" custom_padding=\"||0px|||\" custom_padding_tablet=\"\" custom_padding_phone=\"\" custom_padding_last_edited=\"on|desktop\"]<p style=\"text-align: center;\">\"<em>A long smart citation.\"</em></p>\r\n<p style=\"text-align: right;\"><span style=\"color: #000000;\"><strong>Name Surname </strong></span></p>\r\n<p><em><span></span></em></p>[/et_pb_text][/et_pb_column][/et_pb_row][/et_pb_section][et_pb_section fb_built=\"1\" custom_padding_last_edited=\"on|desktop\" admin_label=\"Header\" _builder_version=\"4.4.6\" use_background_color_gradient=\"on\" background_color_gradient_start=\"#fb803e\" background_color_gradient_end=\"#e09900\" background_color_gradient_direction=\"45deg\" background_image=\"http://localhost/wp-content/uploads/2020/05/AGATE-scaled.jpg\" parallax=\"on\" width=\"100%\" module_alignment=\"center\" height=\"1095px\" height_tablet=\"1165px\" height_phone=\"1235px\" height_last_edited=\"on|phone\" custom_margin=\"0px|40px|396px|40px|false|true\" custom_margin_tablet=\"\" custom_margin_phone=\"||869px||false|true\" custom_margin_last_edited=\"on|phone\" custom_padding=\"36px|0px|25px||false|false\" custom_padding_tablet=\"40px||||false|false\" custom_padding_phone=\"\" border_radii_phone=\"on|20px|20px|20px|20px\" border_radii_last_edited=\"off|desktop\"][et_pb_row column_structure=\"1_2,1_2\" custom_padding_last_edited=\"on|tablet\" _builder_version=\"4.4.6\" background_enable_color=\"off\" background_image=\"http://localhost/wp-content/uploads/2020/05/03.jpg\" parallax=\"on\" transform_scale_tablet=\"\" transform_scale_phone=\"\" transform_scale_last_edited=\"on|desktop\" transform_translate=\"30px|0px\" transform_translate_tablet=\"0px|0px\" transform_translate_phone=\"\" transform_translate_last_edited=\"on|tablet\" transform_translate_linked=\"off\" transform_rotate_tablet=\"\" transform_rotate_phone=\"\" transform_rotate_last_edited=\"on|desktop\" transform_skew_tablet=\"\" transform_skew_phone=\"\" transform_skew_last_edited=\"on|desktop\" transform_origin_tablet=\"\" transform_origin_phone=\"\" transform_origin_last_edited=\"on|desktop\" transform_styles_last_edited=\"on|tablet\" position_origin_r=\"bottom_right\" horizontal_offset=\"30px\" position_origin_a_tablet=\"\" position_origin_a_phone=\"\" position_origin_a_last_edited=\"on|phone\" position_origin_f_tablet=\"\" position_origin_f_phone=\"\" position_origin_f_last_edited=\"on|phone\" position_origin_r_tablet=\"\" position_origin_r_phone=\"\" position_origin_r_last_edited=\"on|phone\" width_tablet=\"90%\" width_phone=\"\" width_last_edited=\"on|desktop\" max_width=\"1200px\" custom_margin_tablet=\"\" custom_margin_phone=\"\" custom_margin_last_edited=\"on|phone\" custom_padding=\"109px|60px|109px|60px|true|true\" custom_padding_tablet=\"60px||60px||true|true\" custom_padding_phone=\"40px|20px|40px|20px|true|true\" transform_styles_tablet=\"\" transform_styles_phone=\"\" positioning_tablet=\"\" positioning_phone=\"none\" positioning_last_edited=\"on|phone\" border_radii_phone=\"off|8px|8px||\" border_radii_last_edited=\"off|desktop\" box_shadow_style=\"preset3\" box_shadow_vertical=\"40px\" box_shadow_blur=\"110px\" box_shadow_spread=\"0px\" box_shadow_color=\"rgba(9,6,38,0.62)\" custom_margin__hover_enabled=\"on|desktop\"][et_pb_column type=\"1_2\" _builder_version=\"3.26\"][et_pb_text _builder_version=\"4.4.6\" text_line_height=\"1.8em\" header_font=\"Taviraj||||||||\" header_text_color=\"#f15b33\" header_font_size=\"45px\" header_line_height=\"1.2em\" header_3_font_size=\"19px\" max_width=\"627px\" max_width_last_edited=\"off|desktop\" custom_margin=\"|-96px||||\" custom_margin_tablet=\"\" custom_margin_phone=\"|9px||9px|false|true\" custom_margin_last_edited=\"on|phone\" custom_padding=\"|0px||||\" text_font_size_tablet=\"\" text_font_size_phone=\"15px\" text_font_size_last_edited=\"on|desktop\" header_font_size_tablet=\"40px\" header_font_size_phone=\"30px\" header_font_size_last_edited=\"on|desktop\"]<h1>Work Title x</h1>\r\n<h3>Certified Work Title 5  (Certificate No 1300572)</h3>\r\n<h3>Certified Work Title 6 (Certificate No 1500380)</h3>\r\n<h3>Certified Work Title y (Certificate No 1100532)</h3>[/et_pb_text][/et_pb_column][et_pb_column type=\"1_2\" _builder_version=\"3.26\"][/et_pb_column][/et_pb_row][et_pb_row disabled_on=\"off|on|on\" _builder_version=\"4.4.6\" width_phone=\"100%\" custom_margin=\"||50px||false|false\" custom_margin_phone=\"||59px||false|false\"][et_pb_column type=\"4_4\" _builder_version=\"4.4.6\"][et_pb_image src=\"http://localhost/wp-content/uploads/2020/05/22-300x300.jpg\" alt=\"Karina Gordijenko\" title_text=\"22\" align=\"center\" _builder_version=\"4.4.6\" custom_margin=\"-385px|-30px||-30px|false|true\" custom_margin_tablet=\"0px||||false|false\" custom_margin_phone=\"\" custom_margin_last_edited=\"on|phone\" custom_padding=\"0px|||||\" box_shadow_style=\"preset4\" box_shadow_horizontal=\"0px\" box_shadow_vertical=\"200px\" box_shadow_color=\"#ffffff\"][/et_pb_image][et_pb_text _builder_version=\"4.4.6\" text_font=\"Taviraj||on||||||\" text_text_color=\"#f15b33\" text_font_size=\"16px\" text_line_height=\"1.8em\" header_5_font=\"Taviraj||||||||\" background_color=\"#ffffff\" max_width_tablet=\"100%\" max_width_phone=\"100%\" max_width_last_edited=\"on|tablet\" custom_margin=\"||-10px||false|false\" custom_padding=\"||0px|||\" custom_padding_tablet=\"\" custom_padding_phone=\"\" custom_padding_last_edited=\"on|desktop\"]<p style=\"text-align: center;\">\"Another smart citation\"</p>\r\n<p style=\"text-align: right;\"><span style=\"color: #000000;\"><strong>Authornm Surnm</strong></span></p>\r\n<p><em><span></span></em></p>[/et_pb_text][/et_pb_column][/et_pb_row][et_pb_row column_structure=\"3_5,2_5\" custom_padding_last_edited=\"on|desktop\" _builder_version=\"4.4.6\" background_color=\"#ffffff\" z_index=\"0\" width_tablet=\"90%\" width_phone=\"90%\" width_last_edited=\"on|desktop\" max_width=\"1200px\" max_width_tablet=\"\" max_width_phone=\"\" max_width_last_edited=\"on|phone\" min_height=\"960px\" min_height_tablet=\"1000px\" min_height_phone=\"\" min_height_last_edited=\"on|phone\" height=\"675px\" height_tablet=\"\" height_phone=\"\" height_last_edited=\"on|phone\" max_height_tablet=\"\" max_height_phone=\"\" max_height_last_edited=\"on|phone\" overflow-x=\"visible\" overflow-y=\"visible\" custom_margin=\"-30px|auto|1px|auto|false|false\" custom_margin_tablet=\"\" custom_margin_phone=\"\" custom_margin_last_edited=\"on|phone\" custom_padding=\"0px|60px|48px|90px|false|false\" custom_padding_tablet=\"|||60px|false|false\" custom_padding_phone=\"|21px|0px|21px|false|true\" box_shadow_style=\"preset3\" box_shadow_vertical=\"40px\" box_shadow_blur=\"110px\" box_shadow_spread=\"0px\" box_shadow_color=\"rgba(131,146,167,0.5)\" width__hover_enabled=\"off\"][et_pb_column type=\"3_5\" _builder_version=\"3.26\" custom_padding=\"48px||||false|false\"][et_pb_text _builder_version=\"4.4.6\" text_font=\"Taviraj||||||||\" text_font_size=\"16px\" text_line_height=\"1.8em\" header_text_color=\"#f15b33\" header_font_size=\"36px\" header_2_font=\"Taviraj||||||||\" header_2_font_size=\"23px\" header_2_line_height=\"1.2em\" min_height=\"913px\" custom_margin=\"||-96px||false|false\" custom_margin_tablet=\"\" custom_margin_phone=\"||-90px||false|false\" custom_margin_last_edited=\"on|phone\" custom_padding=\"||0px||false|false\" custom_padding_tablet=\"|30px||50px|true|false\" custom_padding_phone=\"|30px|||true|false\" custom_padding_last_edited=\"off|tablet\" text_font_size_tablet=\"\" text_font_size_phone=\"15px\" text_font_size_last_edited=\"on|desktop\" header_2_font_size_tablet=\"40px\" header_2_font_size_phone=\"30px\" header_2_font_size_last_edited=\"on|phone\"]<p><b style=\"font-size:16px\">WORK EXPERIENCE:</b></p>\r\n<p align=\"right\" style=\"text-align:left\">2111 – Present Somewhere cool in a cool post</p>\r\n<p><b>CONTACTS:</b>&nbsp;<strong><span><a href=\"tel:+22222222\">+22222222</a>, e-mail: <a href=\"mailto:some.name@mail.who\" >some.name@mail.who</a></span></strong></p>[/et_pb_text][et_pb_button button_url=\"tel:+22222222\" button_text=\"Call\" button_alignment=\"left\" button_alignment_tablet=\"left\" button_alignment_last_edited=\"off|tablet\" _builder_version=\"4.4.6\" custom_button=\"on\" button_text_size=\"16px\" button_text_color=\"#ffffff\" button_bg_color=\"#f15b33\" button_bg_color_gradient_start=\"#946ef4\" button_bg_color_gradient_end=\"#8857f2\" button_bg_color_gradient_direction=\"172deg\" button_border_width=\"0px\" button_border_color=\"rgba(0,0,0,0)\" button_border_radius=\"0px\" button_font=\"Hind|600|||||||\" custom_margin=\"|||||\" custom_margin_tablet=\"|||50px|false|false\" custom_margin_phone=\"106px|||0px|false|false\" custom_margin_last_edited=\"on|phone\" custom_padding=\"13px||10px||false|true\" box_shadow_style=\"preset1\" box_shadow_vertical=\"10px\" box_shadow_blur=\"40px\" box_shadow_spread=\"-9px\" box_shadow_color=\"#f15b33\" button_bg_color__hover_enabled=\"off\"][/et_pb_button][/et_pb_column][et_pb_column type=\"2_5\" disabled_on=\"on|off|off\" _builder_version=\"3.26\" overflow-x=\"visible\" overflow-y=\"visible\" custom_padding=\"|30px|30px|30px|false|true\" box_shadow_style=\"preset3\" box_shadow_blur=\"40px\" box_shadow_color=\"rgba(131,146,167,0.3)\"][et_pb_image src=\"http://localhost/wp-content/uploads/2020/05/22.jpg\" alt=\"Name Surname\" title_text=\"22\" align=\"center\" _builder_version=\"4.4.6\" custom_margin=\"-385px|-30px||-30px|false|true\" custom_margin_tablet=\"0px||||false|false\" custom_margin_phone=\"\" custom_margin_last_edited=\"on|phone\" custom_padding=\"0px|||||\" box_shadow_style=\"preset4\" box_shadow_horizontal=\"0px\" box_shadow_vertical=\"200px\" box_shadow_color=\"#ffffff\"][/et_pb_image][et_pb_text _builder_version=\"4.4.6\" text_font=\"Taviraj||on||||||\" text_text_color=\"#f15b33\" text_font_size=\"16px\" text_line_height=\"1.8em\" header_5_font=\"Taviraj||||||||\" background_color=\"#ffffff\" max_width_tablet=\"100%\" max_width_phone=\"100%\" max_width_last_edited=\"on|tablet\" custom_margin=\"||-10px||false|false\" custom_padding=\"||0px|||\" custom_padding_tablet=\"\" custom_padding_phone=\"\" custom_padding_last_edited=\"on|desktop\"]<p style=\"text-align: center;\">\"Another smart citation\"</p>\r\n<p style=\"text-align: right;\"><span style=\"color: #000000;\"><strong>Authornm Surnm</strong></span></p>\r\n<p><em><span></span></em></p>[/et_pb_text][/et_pb_column][/et_pb_row][/et_pb_section]', 'Theme Builder Layout', '', 'publish', 'open', 'closed', '', 'theme-builder-layout-1213', '', '', '2021-08-29 19:48:16', '2021-08-29 19:48:16', '', 0, 'http://localhost/et_body_layout/theme-builder-layout-1213/', 0, 'et_body_layout', '', 0);

**Comment by Docteh** [comment]
Does that automatic population happen for any language? I'm not clear on how that would work in software. SQL is one of the languages handled by Scintilla, so I don't think that is easily transmuted into UDL

**Comment by grauziitisos** [comment]
> Does that automatic population happen for any language? I'm not clear on how that would work in software. SQL is one of the languages handled by Scintilla, so I don't think that is easily transmuted into UDL

Good morning here :)
Heard the first message comming, but ignored, was sleeping, sorry :) 
Turns out I missed the point.

Import results into a NEW entry in the languages list! I closed and re-open because wanted to answer your question, and voila! all the imports are there with test values populated.

So not sure is a new entry a bug or a feature?

In my opinion if I have opened something I indicate I most likely want to import in this current file. But maybe some other scenarios exist, have to think about it.

---
Thank you for answering and insight, I truly appreciate your contribution!
---
Well then for future I will have to try to look into Scintilla. For now I would like to have a quick fix so that square bracket tags [a][/a] would match. Because now only starting [ is matched with ending ]. Thank you for that, that is better than editing unicolor file. But still it takes plenty of time and concentration just to find exact place of html code / attribute I need to edit at that time. So [a][/a] matching would help a lot, and I think maybe it is a simple edit - if not UDL way, then maybe I can dive deeper and do a local modification of where Scintilla parses HTML and add a clone of that code part, just replacing < with [ and > with ]. That would be a hack for local use. Then if I will have time, it could be sorted and worked out for someone else to use as well.

**Comment by Docteh** [comment]
square tags? something like BBCode? https://github.com/notepad-plus-plus/userDefinedLanguages/blob/master/UDLs/BB_Code_by_Efrit.xml 

In this it seems to do a good job of underlining text incased in like `[u]underlined text[/u]`

**Comment by grauziitisos** [comment]
Yes, exactly, thank You very much! It is atmost ready solution for what I need! 
You made my day! When I get back from countryside, I will not have to struggle with that anymore :)) 

I have completely forgotten about bbcode, last time used like 10 years ago in moodle comments if I remember correctly.. Once again I am very happy now and thank You very much!
May God bless You completely and bountfully!

Nosūtīts no mana Sony Xperia™ viedtālruņa

---- Kyle Kienapfel rakstīja ----

**Comment by grauziitisos** [comment]
Thank you all for the insightful contributions.
Thanks to you, back then I got a somehow working version of parsing divi theme wordpress pages database markup.
now I have lost the udl file however,
and also forgotten what was the issue
therefore let me close this
thank you again and best wishes!
