### ISSUE TITLE
Html autocomplete missing

### ISSUE THREAD

**Issue by camohub** [notepad-plus-plus/notepad-plus-plus#10680]
Is it NP++ able to autocomplete the html tags like other programs like `div.container.mt-3` + tab? Its really bad.

**Comment by rdipardo** [comment]
You're talking about [Emmet](https://emmet.io)

There is ([was?](https://github.com/emmetio/npp/issues/30#issuecomment-614134181)) [a plugin for Notepad++](https://github.com/emmetio/npp), but it's only comaptible with 32-bit versions

- https://community.notepad-plus-plus.org/topic/17366/how-to-install-emmet-plugin
- https://community.notepad-plus-plus.org/topic/17375/emmet-installation
