### ISSUE TITLE
White title bar on dark mode (Windows 10)

### ISSUE THREAD

**Issue by luihabl** [notepad-plus-plus/notepad-plus-plus#10696]
### Description of the Issue

I know this issue probably is related to the OS, but I would like to report it anyway since it might help. 

After installing Notepad++ x64 (version 8.1.8) on my home computer and activating the dark mode the title bar continues to be white. 

On my work computer, which has a previous version of Windows 10, I installed the same version of Notepad++ and the title bar gets black on dark mode, behaving correctly. The only major difference between the two computers is the Windows 10 version. I am sending bellow the information from the Debug menu on both computers.

I think this bug might be related to a similar issue reported on Windows 11: https://community.notepad-plus-plus.org/topic/21438/dark-mode-title-bar-still-white-in-windows-11

### Steps to Reproduce the Issue

1. Install Notepad++ x64 8.1.8
2. Activate dark mode in preferences (Settings > Preferences > Dark mode)
3. Restart Notepad++

### Expected Behavior

![Screenshot 2021-10-20 113828](https://user-images.githubusercontent.com/20427074/138069184-0cdbba4c-934d-469c-9e6d-ed4aba6c8071.png)

### Actual Behavior

![Screenshot 2021-10-20 113357](https://user-images.githubusercontent.com/20427074/138068491-b767d374-6a18-4656-8df0-d27f94b1c1d2.png)

### Debug Information

Machine with **dark** title bar (correct behavior):

Notepad++ v8.1.8   (64-bit)
Build time : Oct 19 2021 - 17:02:51
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line :
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 10 Pro (64-bit)
OS Version : 2009
OS Build : 19043.1081
Current ANSI codepage : 1252
Plugins : mimeTools.dll NppConverter.dll NppExport.dll

Machine with **white** title bar:

Notepad++ v8.1.8   (64-bit)
Build time : Oct 19 2021 - 17:02:51
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 10 Pro (64-bit) 
OS Version : 2009
OS Build : 19044.1319
Current ANSI codepage : 1252
Plugins : mimeTools.dll NppConverter.dll NppExport.dll

**Comment by luihabl** [comment]
After updating to Windows 11 the bug is gone, so in dark mode the bar is dark as well.

**Comment by fape** [comment]
See: #10810
