### ISSUE TITLE
Windows 11 Dark Mode Navigation Menus - Odd White Dots!

### ISSUE THREAD

**Issue by lilalien** [notepad-plus-plus/notepad-plus-plus#10697]
### Description of the Issue
In Windows 11 (could also be Windows 10 but I don't know), when clicking on a navigation bar menu at the top of the app, it displays with odd white dots in the lower corners. When you click a navigation selection (such as Edit menu) and then just move your mouse over "Search" you will see that it displays correctly with no white dots in the corners. So if you've activated the menus already and move around to other menus without clicking anything it displays properly, but direct clicking a navigation menu brings up the white dots. This has been happening for at least half a dozen recent versions of Notepad++.

### Steps to Reproduce the Issue
1. Load Notepad ++ with dark mode
2. Click "Edit" menu.
3. View ugly white dots 

### Expected Behavior
No white dots!

### Actual Behavior
Shows me ugly white dots! lol

### Debug Information
Notepad++ v8.1.8   (64-bit)
Build time : Oct 19 2021 - 17:02:51
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 10 Pro (64-bit) (it's actually windows 11 final build)
OS Version : 2009
OS Build : 22000.282
Current ANSI codepage : 1252
Plugins : ComparePlugin.dll mimeTools.dll NppConverter.dll NppExport.dll 

Including a video!
![notepadplusplus-win11-dark-mode-nav-menus-bug](https://user-images.githubusercontent.com/35111972/138097058-6764ba38-ff73-43c9-9ef1-04c97c6a1906.gif)

**Comment by jmichalek-fp** [comment]
Just created an issue in Windows Feedback Hub.
You can vote and/or add additional info if you'd like.

https://aka.ms/AAf3jtt

**Comment by lilalien** [comment]
I added my comments there and upvoted.. Hopefully we'll get some movement on this, it's pretty obviousy.

**Comment by wards999** [comment]
Also added my comments. Thanks for creating the issue.

**Comment by ozone10** [comment]
Can be closed, issue with early Windows 11 builds (seems to be fixed) not Notepad++.

**Comment by ArkadiuszMichalski** [comment]
@ozone10 Which build did you check? I still see this dot on:
```
OS Name : W (64-bit) 
OS Version : 21H2
OS Build : 22000.1219
```

**Comment by lilalien** [comment]
This issue was fixed in 22H2 I believe.

**Comment by rdipardo** [comment]
> This issue was fixed in 22H2 I believe.

Confirmed:

![Screenshot 2022-12-03 190415](https://user-images.githubusercontent.com/59004801/205467926-7eaa19d4-177c-4a92-9215-6469fbdaae95.png)

It seems that versions as far back as 8.1.2 look better, too.
As this was [always a Windows 11 issue][0], it should be closed already.

[0]: https://github.com/tablacus/TablacusExplorer/issues/482#issuecomment-963774633
