### ISSUE TITLE
About box location

### ISSUE THREAD

**Issue by wards999** [notepad-plus-plus/notepad-plus-plus#10694]
### About box location

The About box cannot be moved via its title bar, so if it appears half off screen (due to parent notepad++ location) it is impossible to click the OK button
### Steps to Reproduce the Issue

1.  Move Notepad++ so that the main window is half off screen (e.g. some of the window is off the bottom of the screen)
2.  Choose ? - About Notepad++
3. See where the About box appears and possibly repeat steps 1 and 2 until the OK button in the dialog is not visible

### Expected Behavior

The About box and its OK button should be visible
### Actual Behavior

Cannot reach the OK button
The only option is to either close Notepad++ or move the main window to a better(?) location and choose ? - About Notepad++ again

**Comment by ArkadiuszMichalski** [comment]
You can press `Esc`, `Space` or `Enter` to close this dialog.

**Comment by donho** [comment]
> @donho Couldn't About be the same as Debug Info (and all other dialogs)?

I like this way personally.
Let's see if there are more such request then I may consider it.

**Comment by alankilborn** [comment]
Sometimes when wanting to do a screenshot of a point I'm trying to make (either here or on the Community), and also show the N++ version (i.e. the About box) in the same screenshot, it is really tough to get the content I want, because the About box can't be repositioned.
