### ISSUE TITLE
v6.8.6 Crash

### ISSUE THREAD

**Issue by TheArPee** [notepad-plus-plus/notepad-plus-plus#1070]
Using new version to edit a large log file (90.1 MB)
Use search/replace to bookmark a large number of lines and then try to delete those lines through menu Search->Bookmark->Remove Bookmarked Lines

Crashes every time

Windows 7 64 bit

Cannot drag dump file here so will be emailing Don direct

**Comment by TheArPee** [comment]
![notepad plugins](https://cloud.githubusercontent.com/assets/3055355/10851569/be0a8654-7f23-11e5-889d-fba97bb359c2.png)

List of plugins

**Comment by dail8859** [comment]
Do you have backups or session snapshots enabled under `Settings -> Preferences -> Backup`? If so try turning those off and see if it crashes again.

**Comment by donho** [comment]
I cannot reproduce the crash.
Could you 
1. Close your Notepad++
2. Rename your folder "plugins" to "foo" (located on *C:\Programme Files (x86)\Notepad++\plugins*) 
3. Launch Notepad++ 
to make sure the crash is not due to plugins?

**Comment by TheArPee** [comment]
OK Don - did that - still crashes every time

What I did:
Use Search/Replace dialog on Marks Tab
Bookmark Line selected - Mode Regular expression

Search for the following (without the {} braces)  {^.*CHE Not Connected.*$}

About 28000 lines Marked

From Search menu->Bookmarks select "Remove Bookmarked Lines"
Crashes after about 6 seconds

**************UPDATE*****************
I have found out the problem

As inferred by dail8859 I had backups and session snapshots enabled and the backup was set to every 7 seconds for some reason so i presume that the backup was kicking in before the remove bookmarked lines process had finished!
Disabled that backup and no crashes!

Do I get points for that? :-)

**Comment by donho** [comment]
@TheArPee Yes, you got 1 point and my thanks for testing.
@dail8859 got 3 points, and bravo!
@TheArPee  I'll provide you a binary with the fix, may I?

**Comment by TheArPee** [comment]
That would be really cool! Thank you!
Always willing to test Beta versions if you could use another tester!

**Comment by donho** [comment]
@TheArPee Could you unzip and replace your notepad++.exe here:
https://goo.gl/r3HJS6
and enable backups and session snapshots feature.
Then try it again to see if it still crashes?

**Comment by dail8859** [comment]
Side note, I filter through 200MB+ log files all the time and have found the LineFilter2 plugin to be a great tool!

**Comment by TheArPee** [comment]
@donho I would love to do that, but the link has been disabled. :-(
![2015-10-31 09_00_44-google url shortener](https://cloud.githubusercontent.com/assets/3055355/10862763/391a0970-7fae-11e5-9e00-c59f05004e00.png)

**Comment by donho** [comment]
@TheArPee just send you the binary. Please report your result here.

**Comment by TheArPee** [comment]
nothing received yet. :-(

**Comment by donho** [comment]
@TheArPee Please try https://notepad-plus-plus.org/repository/6.x/tmp/npp.zip

**Comment by TheArPee** [comment]
OK - success!
Used that version and did exactly what I was doing yesterday.
All settings were reverted to that which were in place before - so therefore exactly the same environment. 
No crashes - tried 5 times.

Even gave it a bigger task of bookmarking over 100000 lines out of 500000 and then removing - process took about 20 seconds but DID NOT CRASH! :-)

Excellent!

If there are any more tests I would be glad to help if I can

**Comment by donho** [comment]
@TheArPee Thank you for testing!

**Comment by TheArPee** [comment]
Not a problem @donho  - Thank you for the swift response! (And I did notice how late you stayed up last night fixing this issue!)
I use Notepad++ every day and it is an essential tool in my job so I have an interest in keeping it awesome!
