### ISSUE TITLE
Block and inline comments don't work right after a digit in PHP language syntax highligthing

### ISSUE THREAD

**Issue by Unchqua** [notepad-plus-plus/notepad-plus-plus#10706]
### Description of the Issue
In PHP language, block commens `/* like this */` and inline comments `// like this` aren't recognized when placed right after a digit 0-9.

### Steps to Reproduce the Issue
1. Example 1: `if (j===i-2/* || k===i-2*/) { … }`
2. Example 2 (although syntactically incorrect): `if (j===i-2//* || k===i-2) { … }`
2. Digit 2 makes the following comment not recognized.
3. If I put a space between `2` and `/`, it works as expected.

### Expected Behavior
Comments should be recognized and marked as such.

### Actual Behavior
It seems that two adjacent symbols, `2` and `/`, make Notepad++ think I want to divide 2 by something that follows it.

### Debug Information
Notepad++ v8.1.9   (64-bit)
Build time : Oct 21 2021 - 23:37:53
Path : C:\Program Files\NotepadPlusPlus-8.1.9\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 8 Single Language (64-bit) 
OS Build : 9200.0
Current ANSI codepage : 1251
Plugins : mimeTools.dll NppConverter.dll NppExport.dll 

I guess comment tokens, eg. `/*` and `*/` , should prevail over other senses of their corresponding symbols.

**Comment by ArkadiuszMichalski** [comment]
Fixed by https://github.com/notepad-plus-plus/notepad-plus-plus/commit/a61b03ea8887e21c6e1b7374068962f635b79b80.
