### ISSUE TITLE
Having a single dialog for Find in Files and Replace in Files is dangerous/stressful

### ISSUE THREAD

**Issue by mr-intj** [notepad-plus-plus/notepad-plus-plus#10704]
It just seems too easy to fill out the **Find what** field, leave whatever is in the **Replace with** field, and then accidentally click **Replace in Files**. This is especially likely when I'm alternating between searching and replacing.

 This is a rare case where I like Visual Studio's approach better: `Ctrl`+`Shift`+`F` opens/switches to a **Find in Files** dialog, and `Ctrl`+`Shift`+`H` opens/switches to a **Replace in Files** dialog.

What we have now is perfectly usable; but it seems too easy to make a simple reflexive error and potentially destroy an almost unbounded amount of work...

**Comment by donho** [comment]
There is a dialog for asking the confirmation for `Replace in Files` before the action.
