### ISSUE TITLE
Pressing the up key when at the top of a file allows you to change between open files

### ISSUE THREAD

**Issue by notepadpp27** [notepad-plus-plus/notepad-plus-plus#10709]
Suggestion:
So, if you're at the top of a file, you press the up key and it allows you to switch between the files you have open using the left and right keys. Then you press the down key and it puts you into the first line of the file you have currently chosen.

Maybe also ctrl and the up key to do the same thing from anywhere in the file.

**Comment by alankilborn** [comment]
@notepadpp27 
No other multi-document programs that I know of work this way.

Recommend REJECTION and CLOSURE of this item.

**Comment by ArkadiuszMichalski** [comment]
Notepad ++ has several mechanisms that allow you to switch between files. Additional things (as proposed here) should be done with plugins.
