### ISSUE TITLE
Scrollbar should work on the edge of the screen

### ISSUE THREAD

**Issue by pkrabbit** [notepad-plus-plus/notepad-plus-plus#1071]
There's a 2px border between scroll bar and edge of the screen, so you cannot use the scroll bar if the mouse is on the edge of the screen.

Currently, you have to aim at the scroll bar instead of just using the edge of the screen to scroll, as you can in very popular programs (Firefox, Chrome, Explorer, etc.). This would greatly improve comfort and usability.

**Comment by aaaxx** [comment]
It's been a pull request https://github.com/notepad-plus-plus/notepad-plus-plus/pull/707 for a couple of months now, but the powers that be have certain opinions.

**Comment by dail8859** [comment]
Closed by 6c7ca02fe
