### ISSUE TITLE
Want to add a feature

### ISSUE THREAD

**Issue by k9fvm** [notepad-plus-plus/notepad-plus-plus#10717]
Given a choice, use "Ctrl + click" instead of "double click" to open the link.

The point is to cancel the operation of "double click" to open the link.

Because when editing links, "double clicking" will lead to many misoperations.

In addition, "double click" is also a common physical failure of the mouse.

**Comment by ArkadiuszMichalski** [comment]
Cuplicate of https://github.com/notepad-plus-plus/notepad-plus-plus/issues/9993.
