### ISSUE TITLE
functionlist with wrong color

### ISSUE THREAD

**Issue by SirHesti** [notepad-plus-plus/notepad-plus-plus#10718]
[

### Description of the Issue

The current selection in the function list is displayed in the wrong color.

### Steps to Reproduce the Issue

1. Create new file - save them like me.sh

markone () {
	echo hallo
}
markone hallo

leave note pad an restart it. the active function ist displayed in black on darkgray.

call options->stile
do anything to save. nothing real only save must it. voil'a the active function is displayed in white on black. easy to read in darkmode.

### Debug Information

Notepad++ v8.1.7   (64-bit)
Build time : Oct 15 2021 - 01:20:46
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 10 Pro (64-bit) 
OS Version : 2009
OS Build : 19042.1288
Current ANSI codepage : 1252
Plugins : ComparePlugin.dll MarkdownViewerPlusPlus.dll mimeTools.dll NppConverter.dll NppExport.dll NppJumpList.dll NppXmlTreeviewPlugin.dll 

Start:
![grafik](https://user-images.githubusercontent.com/51073539/138918002-0f615796-40ca-4c4c-a6b2-68b670d15ad0.png)

after stile save :
![grafik](https://user-images.githubusercontent.com/51073539/138918270-19e3975d-19c9-47c0-baac-620812707dfe.png)

Thanks for the attention 
Hesti

**Comment by ArkadiuszMichalski** [comment]
Please update to latest 8.1.9 version or try with [portable version](https://github.com/notepad-plus-plus/notepad-plus-plus/wiki/Testing#using-the-latest-release-portable-version-of-notepad) to eliminate configuration problem.

**Comment by SirHesti** [comment]
OK, after many hours of searching I was able to spot the phenomenon. The problem is not directly in Notepad ++, but only occurs when the Markdownviewer ++ plugin is installed. If it is uninstalled again, the problem no longer exists. I will send an appropriate link to the author. 

Thanks for the attention
Hesti
