### ISSUE TITLE
Regression: Current document not highlighted in document list at left

### ISSUE THREAD

**Issue by niente0** [notepad-plus-plus/notepad-plus-plus#10720]
### Description of the Issue

The current active document is not highlighted in open document list at left
Screenshot: [https://ibb.co/HKTY0kn](https://ibb.co/HKTY0kn)

### Steps to Reproduce the Issue

1. open a document
2. 
3. 

### Expected Behavior

document name appears highlighted in open document list

### Actual Behavior

document name does not appear highlighted in open document list

### Debug Information

Notepad++ v8.1.5   (64-bit)
Build time : Sep 26 2021 - 15:23:23
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : "C:\inetpub\wwwroot\rheumadebates\www\admin\webinarpolls\default.asp"
Admin mode : ON
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 10 Pro (64-bit) 
OS Version : 2009
OS Build : 19042.1288
Current ANSI codepage : 1252
Plugins : ComparePlugin.dll mimeTools.dll NppConverter.dll NppExport.dll

**Comment by ArkadiuszMichalski** [comment]
Please update to latest 8.1.9 version or try with [portable version](https://github.com/notepad-plus-plus/notepad-plus-plus/wiki/Testing#using-the-latest-release-portable-version-of-notepad) to eliminate configuration problem.

**Comment by niente0** [comment]
I updated to 8.1.9.3 but the bug is still present (on 2 different computers). While on the first computer I made various changes to color s (no dark mode), on the second computer I just inverted foreground and background colors (black on white -> white on black).

**Comment by mere-human** [comment]
@niente0 Can you try disabling the dark mode (Settings > Preferences > Dark Mode) and changing to default theme (Settings > Style Configurator) and see if the problem still exists?

**Comment by ozone10** [comment]
Fixed in https://github.com/notepad-plus-plus/notepad-plus-plus/commit/d3b026bfeb96eb39e0402673d68dd04e640e2e1e
