### ISSUE TITLE
[Feature request] Match or set default extension in rename window

### ISSUE THREAD

**Issue by kiyn** [notepad-plus-plus/notepad-plus-plus#10729]
### Actual Behavior
In the rename window,  by default the "Save as" menu is always set to "All Types (\*.*)".

![rename](https://user-images.githubusercontent.com/16320965/139447005-7e1c346f-c4a4-4c12-b56b-a81d0800f401.jpg)

### Expected Behavior
In the rename window, by default the "Save as" menu match with current file extension.

### Desired Implementation
I request two items to be added in the settings:

1. Match the current file extension in rename window
2. Set default extension in rename window

I hope it's possible to do this and that it does not require too much effort.
Thanks

**Comment by termdew** [comment]
I would like to have a look into it.
