### ISSUE TITLE
Enable backup-on-save by default

### ISSUE THREAD

**Issue by pryrt** [notepad-plus-plus/notepad-plus-plus#10725]
### Description of the Issue

After years in the Forum, I have come to the conclusion that a large subset of Notepad++ users expect any application to backup their data for them without having to configure anything -- despite the fact that, in my experience, very few applications do.  Since many don't read manuals before starting to use software, and don't ever go looking at preferences to see if there is something that influences backups, then they end up losing data and getting mad at the Community Forum regulars because Notepad++ doesn't behave as they expect out-of-the-box.

The simplest way to make that subset happy would be to enable "simple backup" by default, so there's at least something to point them to.  Many ancient text editors from the linux world do that -- and while I always turn off that feature (I hate a bunch of files called `blah.ext~` or `blah.bak`, especially when I'm using real version control software, it seems to be what that vocal subset needs as the default.  And people who are annoyed by `.bak` files suddenly appearing can go looking for the setting to change (those who don't like `.bak` are more likely to be people who like to customize things, anyway).  And at least that way, if they complain, it won't be because they are blaming us for data loss.

### Desired Behavior

Could you set the **Preferences > Backup >Backup On Save** to **Simple Backup** by default?

### Actual Behavior

Currently, **Preferences > Backup >Backup On Save** is set to **None** by default.

### Debug Information

```
Notepad++ v8.1.9   (64-bit)
Build time : Oct 21 2021 - 23:37:53
Path : C:\usr\local\apps\npp\npp.8.1.9.portable.x64\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : ON
Cloud Config : OFF
OS Name : Windows 10 Enterprise (64-bit) 
OS Version : 2009
OS Build : 19042.1288
Current ANSI codepage : 1252
Plugins : mimeTools.dll NppConverter.dll NppExport.dll 
```

**Comment by donho** [comment]
@ArkadiuszMichalski 
I see your point and I do agree with you.
However, with Nul file corruption problem, I think it would be great to enable backup option by default before.
(Most of ) People won't be happy with it enabled, but if it could save valuable data of some users, it worth that other people disable manually this option.
Let's see what users say anyway.

**Comment by ArkadiuszMichalski** [comment]
>However, with Nul file corruption problem, I think it would be great to enable backup option by default before.

Recent changes have not eliminated this, or it's too early to say that?

> Let's see what users say anyway.

At least one person has the same concerns as me: https://community.notepad-plus-plus.org/topic/22055/useless-backup-system/20. When testing the portable version we can keep all the test files in the NPP directory, and then delete the whole after testing. This is also a solution for unwanted .bak files.

**Comment by donho** [comment]
It's too early to say the Nul file corruption has been fixed. The auto-update for v8.1.9 is not triggered yet.
Even it's fixed, it's not bad to make it on by default - it could save some devs' life.

> When testing the portable version we can keep all the test files in the NPP directory, and then delete the whole after testing. This is also a solution for unwanted .bak files without having to modify config.xml each time..

Sorry, I don't follow you, what do you mean by "testing" ?

**Comment by Raptor007** [comment]
This is a very annoying change, especially being enabled unexpectedly with an update.  Some git repositories are going to get messy from this.  I completely disagree with the wild and baseless assumption that editors should be expected make this kind of mess by default.

At the very least, a default "Custom Backup Directory" should be enabled so this mess doesn't get created everywhere we edit.

**Comment by donho** [comment]
@Raptor007 
It's easy to solve for git repository to add `*.bak` in .gitIgnore file.
As you have noticed, this new default behaviour shouldn't affect to the old users, only the new installation.
And activating of the backup on save have saved my life once. I believe it's a good default value.
Sorry for the inconvenience.

**Comment by Raptor007** [comment]
@donho  Sorry for my frustration, but I found this new behavior especially annoying after my settings were wiped unexpectedly.  Having used Notepad++ for years without touching the backup settings, it was not immediately apparent why these files were appearing or even that Notepad++ was the culprit.  Consider me part of the "group of frustrated people (power users) who will complain about this activated option".  And I find the story of data loss that led to this change completely amateurish user error.

**Comment by donho** [comment]
> And I find the story of data loss that led to this change completely amateurish user error.

Then please count me as one of amateurish Notedpad++ users :)
Notepad++ is used by a lot of non-power users, so it's important to find the balance.
Anyway, you can turn this feature OFF easily, so now everyone is happy (hopefully).
Sorry for the inconvenience.

**Comment by Raptor007** [comment]
Well I'm sure we've all made mistakes that lost us some data and taught us to manage important files better.  I know I have.  But I didn't get mad at my text editor for this.

**Comment by tsurutsururori** [comment]
Better to err on the side of caution, but I do agree that it's annoying that by default .bak files are placed in the same directory as the original file.  At least there's an option to change what folder they're saved in.

**Comment by mere-human** [comment]
@donho Maybe, with enabling auto-backup by default, Notepad++ should have a default backup directory set to something like user directory or documents directory?

**Comment by pryrt** [comment]
> have a default backup directory set to something like user directory

so that when a new user edits project1\main.cpp and then project2\main.cpp, the backupfolder\main.cpp file will be clobbered, so we'll get complaints about the backups being clobbered, instead of complaints about .bak showing up in every folder?  

There is, unfortunately, no way to make every user happy with this issue.

Just something to consider before making another change.

**Comment by donho** [comment]
@mere-human 
I agree with @pryrt

**Comment by razorvind** [comment]
I was frustrated with this new feature.
When I saw *.bak files - my thoughts was - why did it happen?
I found settings and thought - ok this WAS by default ALWAYS- why did I have bak files?
And just leave it as it is.

And in several weeks today I found the answer.
And turn backup off.

Because notepad keep changes all the time.
If I have not saved changes - and close notepad - and then open - I see my changes.

My personal point of view - we should not changes behavior which is used to be for ages.

**Comment by DisableBackupSetting** [comment]
Please also consider an admin deploying notepad++ to its users. How can I set to disable the "backup feature" in advance? 

Of course I can deploy a notepad++ settings file to every users with the backup disabled. But I don't like this idea. 

Could you add a parameter for the "notepad++.exe" to disable the "backup feature"? This way I could probably just change the shortcut to the "notepad++.exe" while deploying your program. 

How about using the default "config.xml" file as template basis and just copy this file to the user profiles? This way I could pre-configure "config.xml" in the portable edition and then create a windows installer .msi file. 

Of course a registry key would help me as well...

What ever you do, please consider to add a possibility to pre-configure this "backup" setting. I assume that many Admins will share my wish on this point.

**Comment by donho** [comment]
Due to many complains about this issue, the backup option will be reverted to the old value (OFF). People who need this feature can turn it ON manually.

**Comment by donho** [comment]
https://github.com/notepad-plus-plus/notepad-plus-plus/commit/f815b7057f113defc1c683b2833c05ebe244bf6c

**Comment by DisableBackupSetting** [comment]
Great news, thank you very much for your support.

**Comment by datvm** [comment]
> git users will complain about the *.bak is tracked by git every time they modify files in Notepad++

I am one of those getting "surprised" by it as well. At least maybe there should be a warning box or something when new install is detected. I know there is changelog but who actually reads them?

> > have a default backup directory set to something like user directory
> 
> so that when a new user edits project1\main.cpp and then project2\main.cpp, the backupfolder\main.cpp file will be clobbered, so we'll get complaints about the backups being clobbered, instead of complaints about .bak showing up in every folder?
> 
> There is, unfortunately, no way to make every user happy with this issue.
> 
> Just something to consider before making another change.

I believe Custom Backup Folder is the good middle ground:

- As @donho mentioned, the main purpose of this is to prevent data loss. Sure the name is messy but I believe I would be so happy there is a backup that I don't mind combing through a few file names to look for what I need.

- It also does not mess up with current developer users (as for me I got a new laptop and installed latest Notepad++ without knowing the latest change). We are talking about middle ground right? Just use Custom Backup Folder, user who want the .bak in their folder can switch it off, instead of asking all of us to switch it off after a frustrated surprise.

**Comment by kristibektashi** [comment]
I have a better idea. When you first open Notepad++ it should ask the user if they want backups to be made or not. Something like a dialog box saying "Do you want Notepad++ to automatically backup the old version of your files every time you make changes to them? The backup will have a .bak extension. You can always change this option later in Settings" with Yes and No options. Yes enables the option, No disables it

**Comment by Raptor007** [comment]
> Due to many complains about this issue, the backup option will be reverted to the old value (OFF). People who need this feature can turn it ON manually.

Thank you!  I really think this is the right call.

Not to beat a dead horse, but in case this idea is ever revisited, there's another problem with saving .bak files into the same directory by default: sometimes people manually create .bak files to retain an old version, either for comparison or archive.  They could lose that data if .bak files are overwritten unexpectedly.

**Comment by mere-human** [comment]
> I have a better idea. When you first open Notepad++ it should ask the user if they want backups to be made or not.

Theoretically, can be done through the installer.

**Comment by jimbobmcgee** [comment]
This is one of those cases where defaulting to the Custom Backup Directory&mdash;where that directory is specifically an `%APPDATA%`-rooted folder&mdash;might be the best of both worlds.

The dedicated folder would be outside of the workflow enough not to trip the *principle of least surprise* (e.g. for SCM users, on-server website editors, and any other myriad use-cases that people use N++ for), while still offering the safety that it is validly intended to provide; and the use of `%APPDATA%` would make it user-scoped, so backups did not leak information between users in a multi-user environment.

If you are at all worried about the possibility of a large, hidden cache of backup files taking up a disk, you could always introduce a feature to keep it manageable (*x* days retention, *y* number of files, *z* bytes max, etc.)
