### ISSUE TITLE
Building Notepad++ with GCC failed(Compiling Notepad++ binary)（用GCC构建失败）

### ISSUE THREAD

**Issue by sunzhangchang** [notepad-plus-plus/notepad-plus-plus#10721]
### Description of the Issue

Bug report:

```
E:/Program Files/TDM-GCC-64/bin/mingw32-make: invalid option -- O

Usage: mingw32-make [options] [target] ...

Options: ... --------------------- is omitted here.


This program built for i686-pc-mingw32

Report bugs to

makefile:193: recipe for target 'bin.x86_64.buildbscilexer.a' failed

mingw32-make: *** [bin.x86_64.buildbscilexer.a] Error 2
```

![error](https://user-images.githubusercontent.com/52880063/139063680-eb050838-e212-49b1-ad52-fe3764b38e2f.png)

I found an error with the option `-O` in the variable `SUBMAKEFLAGS`.

When I delete the option `-O`, `mingw32-make` will work successfully.

### Steps to Reproduce the Issue
1. Follow the build guide `Compiling Notepad++ binary`.
2. Run `mingw32-make`

### 问题描述

当我构建可执行文件时，发生了以下错误。
错误信息：

```
E:/Program Files/TDM-GCC-64/bin/mingw32-make: invalid option -- O

Usage: mingw32-make [options] [target] ...

Options: ... --------------------- is omitted here.


This program built for i686-pc-mingw32

Report bugs to

makefile:193: recipe for target 'bin.x86_64.buildbscilexer.a' failed

mingw32-make: *** [bin.x86_64.buildbscilexer.a] Error 2
```

![error](https://user-images.githubusercontent.com/52880063/139063680-eb050838-e212-49b1-ad52-fe3764b38e2f.png)

我发现错误是在变量 `SUBMAKEFLAGS` 中的 `-O` 选项。

当我删除 `-O` 这个选项时，`mingw32-make` 将会成功运行。

### 重现此问题的步骤
1. 跟随搭建向导，`Compiling Notepad++ binary`.
2. 运行 `mingw32-make`

**Comment by chcg** [comment]
@sunzhangchang Which version of gcc do you use? x86_64-8.1.0-release-posix-seh-rt_v6-rev0 or a different one? Could it be https://jmeubank.github.io/tdm-gcc/?

**Comment by sunzhangchang** [comment]
@chcg tdm64-gcc-10.3.0-2

**Comment by ArkadiuszMichalski** [comment]
@sunzhangchang Which version of `mingw32-make` this tool use? Check by `mingw32-make -v`. I see in above screen that option `-O` is missing. [Recommended MinGW-w64](https://github.com/notepad-plus-plus/notepad-plus-plus/blob/master/BUILD.md#building-notepad-with-gcc) has it (`mingw32-make --help`):
```
  -O[TYPE], --output-sync[=TYPE]
                              Synchronize output of parallel jobs by TYPE. 
```

**Comment by ArkadiuszMichalski** [comment]
@donho We can check if `output-sync` is supported and only then add `-O` to `SUBMAKEFLAGS`. Or close this issue and expect that people will use something newer.

**Comment by donho** [comment]
> We can check if output-sync is supported and only then add -O to SUBMAKEFLAGS.

No. It's not my goal to have the compatibility to all existing mingw or GCC versions.

> Or close this issue and expect that people will use something newer.

The scope of [Notepad++ build](https://github.com/notepad-plus-plus/notepad-plus-plus/blob/master/BUILD.md) is very clear. User can always download the suggested package to build Notepad++.

**Comment by donho** [comment]
@sunzhangchang 
Please follow [Notepad++ Build Guide](https://github.com/notepad-plus-plus/notepad-plus-plus/blob/master/BUILD.md) to download the suggested package.
