### ISSUE TITLE
Unexpected behaviour of "Undo" after "delete"

### ISSUE THREAD

**Issue by godwinstewart** [notepad-plus-plus/notepad-plus-plus#10727]
### Description of the Issue

Using "Undo" immediately after using the "Delete" key to delete the character immediately following the cursor leaves the cursor in an unexpected place.
### Steps to Reproduce the Issue

1. Place the cursor anywhere on a line.
2. Press the "Delete" key
3. Press Ctrl-Z (PC variant)

### Expected Behavior

I expected the cursor to stay where it was and to "bring back" the character after it that was deleted.
### Actual Behavior

The cursor is placed _after_ the character re-inserted.
### Debug Information

Notepad++ v8.1.5   (64-bit)
Build time : Sep 26 2021 - 15:23:23
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : "C:\Users\godwi\source\repos\mb-linux\libwebsocket\websocket.cpp"
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 10 Pro (64-bit) 
OS Version : 2009
OS Build : 19043.1288
Current ANSI codepage : 1252
Plugins : mimeTools.dll NppConverter.dll NppExport.dll

**Comment by EvanMauritzBrown** [comment]
#11559 should fix this issue

**Comment by donho** [comment]
This issue is Scintilla related. Please report your bug here: https://sourceforge.net/p/scintilla/bugs/
