### ISSUE TITLE
Single line comment not changing style for PHP

### ISSUE THREAD

**Issue by daxliniere** [notepad-plus-plus/notepad-plus-plus#10737]
Open a PHP file, add  to a line (or block) and you'll see its colour changes to green. If you add a single-line comment (// or #), the line doesn't change to green.

**Comment by ArkadiuszMichalski** [comment]
Please f[ollow the guidelines](https://github.com/notepad-plus-plus/notepad-plus-plus/wiki/FAQ#how-to-open-a-new-issue) when opening a new issue.
