### ISSUE TITLE
SCI_LINETRANSPOSE doesnt move the cursor

### ISSUE THREAD

**Issue by yashpalgoyal1304** [notepad-plus-plus/notepad-plus-plus#10735]
### Description of the Issue

`SCI_LINETRANSPOSE` doesnt move the cursor

### Steps to Reproduce the Issue

1. Open any file containing multiple lines of texts and Click on any line (say Selected_Line_S )
2. Press <kbd>Ctrl</kbd> + <kbd>T</kbd>
3. Dont change the cursor position manually
4. Redo step 2

### Expected Behavior

The Selected_Line moves up, i.e. after <kbd>Ctrl</kbd> + <kbd>T</kbd> the cursor moves to new position automatically, so that selected_line can be moved up repeatedly

### Actual Behavior

* The cursor stays in original line number, so, repeatedly pressing Ctrl T is futile, and 
* to move a line up, one has to manually move the cursor again and again.

### Debug Information

```
Notepad++ v7.9.5   (64-bit)
Build time : Mar 21 2021 - 02:13:17
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS Name : Windows 10 Home Single Language (64-bit) 
OS Version : 2009
OS Build : 19042.1165
Current ANSI codepage : 1252
Plugins : ComparePlugin.dll DSpellCheck.dll MarkdownViewerPlusPlus.dll mimeTools.dll NppConverter.dll NppExport.dll NPPJSONViewer.dll XMLTools.dll 
```

**Comment by yashpalgoyal1304** [comment]
🔍 Searches:
* issue : [ctrl t switch line](https://github.com/notepad-plus-plus/notepad-plus-plus/issues?q=is:issue+ctrl+t+switch+line)
* Shortcut name : https://keycombiner.com/collections/notepad/#row208075
* Shortcut : https://defkey.com/notepad-plus-plus-shortcuts#5155
* Shortcut : [ctrl + t in notepad](https://duckduckgo.com/?q=ctrl+++t+in+notepad&t=vivaldi&ia=web)

**Comment by yashpalgoyal1304** [comment]
example screenrecording of this huge UX papercut: 

https://user-images.githubusercontent.com/19423063/139525632-6020b932-229e-4dae-b186-681eda25b94d.mp4

https://github.com/mucommander/mucommander/issues/525

**Comment by donho** [comment]
Isn't better to use Ctrl+Shift+UpArrow ?

**Comment by donho** [comment]
In anyway, it's not a bug but the default behaviour.

**Comment by yashpalgoyal1304** [comment]
> Isn't better to use Ctrl+Shift+UpArrow ?
I wasn’t aware of that. Thanks – glad I filled it. it was my (kinda) biggest papercut in NP++

**Comment by yashpalgoyal1304** [comment]
suggested label: support/question
