### ISSUE TITLE
Enhancement: Associate the .mjs file extension with JavaScript

### ISSUE THREAD

**Issue by startrekdude** [notepad-plus-plus/notepad-plus-plus#10746]
### Description of the Issue

Associate the `.mjs` file extension, used by ECMAScript 6 module files, with JavaScript. This would enable syntax highlighting by default when opening a `.mjs` file.

The `.mjs` extension is recommended for modules by the [V8 project](https://v8.dev/features/modules#mjs).

### Steps to Reproduce the Issue

1. Open a file with the `.mjs` file extension.

### Expected Behavior

The file is displayed with JavaScript syntax highlighting.

### Actual Behavior

The file is displayed without syntax highlighting.

### Debug Information

```
Notepad++ v8.1.9   (64-bit)
Build time : Oct 21 2021 - 23:37:53
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 10 Education (64-bit) 
OS Version : 2009
OS Build : 19043.1288
Current ANSI codepage : 1252
Plugins : mimeTools.dll NppConverter.dll NppExport.dll 
```

**Comment by termdew** [comment]
I'll have a look at it.

**Comment by htho** [comment]
Until it is fixed, this is how to manually set the extension:

In the menu go to: "Settings" -> "Style Configurator"
Select "JavaScript" (not "JavaScript (embedded)")) and add the extension in the "User extension" edit box.
To add multiple extensions separate them using Space.

You then need to re-open your file to see the syntax highlighting applied.

Thanks to: https://superuser.com/questions/40876/assigning-custom-extensions-to-a-languages-syntax-highlighting-in-notepad

**Comment by ArkadiuszMichalski** [comment]
More info:
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Modules#aside_%E2%80%94_.mjs_versus_.js
