### ISSUE TITLE
Spanish and Galician translations for v8.1.9

### ISSUE THREAD

**Issue by P0rsche-911** [notepad-plus-plus/notepad-plus-plus#10742]
Hi, I'm new here.

I bring the updated Spanish and Galician language files to be included in the new version of Notepad++, if you consider it appropriate.

Sorry if I do something wrong.

Greetings from Spain

Translated by deepl.com

[Notepad++.zip](https://github.com/notepad-plus-plus/notepad-plus-plus/files/7456667/Notepad%2B%2B.zip)

Hola, soy nuevo por aquí.

Aporto los ficheros actualizados de idioma español y gallego para, si lo consideran oportuno, incluirlos en la nueva versión de Notepad++.

Perdón por si hago algo mal.

Saludos desde España

**Comment by conky77** [comment]
@m6502 , you updated galician.xml in April. Are you able to understand if these attachments are still valid (maybe Spanish not, but Galician maybe yes)

**Comment by conky77** [comment]
@P0rsche-911 do you have any updates? If you could insert a Pull request, it would be great. If you can't, it would be better to create an issue for every language.

**Comment by P0rsche-911** [comment]
Sorry.
I made the translation thinking that everything was simpler. I don't understand what you are asking. I can provide the file in .txt, .html or similar format.
I can send it to you to convert it into what you are asking for. I don't know how to do it.

 

Anyway, it would have to be updated to the latest version. I attach it as an example.

 

Thank you for your help.

 

Regards

 


Lo siento.
Hice la traducción pensando que todo era más sencillo. No entiendo lo que me pide. Puedo aportar el fichero en formato .txt, .html o similar.
Se lo puedo enviar a usted para convertirlo en lo que me pide. Yo no sé hacerlo.

 

De todas formas, habría que actualizarlo a la última versión. Lo adjunto como ejemplo.

 

Gracias por su ayuda.

 

Saludos



 
 

Enviar: sábado 1 de octubre de 2022 a las 11:01
De: "Matteo Concato" ***@***.***>
Para: "notepad-plus-plus/notepad-plus-plus" ***@***.***>
CC: "P0rsche-911" ***@***.***>, "Mention" ***@***.***>
Asunto: Re: [notepad-plus-plus/notepad-plus-plus] Spanish and Galician translations for v8.1.9 (Issue #10742)


 

@P0rsche-911 do you have any updates? If you could insert a Pull request, it would be great. If you can't, it would be better to create an issue for every language.

**Comment by P0rsche-911** [comment]
Hello
Galician.xml file updated to version 8.4.6 and thoroughly revised.
I hope it can now be used to add to the program.

Hola
Archivo galician.xml actualizado a versión 8.4.6 y revisado a fondo.
Espero que ahora pueda servir para añadir al programa.

[galician.zip](https://github.com/notepad-plus-plus/notepad-plus-plus/files/9894676/galician.zip)
