### ISSUE TITLE
Auto-indent hotkey

### ISSUE THREAD

**Issue by jairocontreras** [notepad-plus-plus/notepad-plus-plus#10744]
Add an option to use auto-indent only when ctrl is pressed

**Comment by thomassmith311** [comment]
Currently when pressing Enter while on an indented line, it makes a new line that is also indented. You are saying that you want Enter to create a new line that is not indented, while Ctrl+Enter makes a new line that is indented?

Auto-indent is extremely helpful for programmers, though, which is what Notepad++ is primarily designed for. Having to push Ctrl at the same time for this feature would be rather annoying for me

**Comment by jairocontreras** [comment]
i turned off auto-completion. i prefer to control when i indent new lines. by adding an option to enable auto-indent only when a hotkey of choice is pressed, the default setting would remain unaffected when the new option is disabled
