### ISSUE TITLE
Icons for Document List unchanged in dark mode

### ISSUE THREAD

**Issue by thomassmith311** [notepad-plus-plus/notepad-plus-plus#10740]
### Description of the Issue
![image](https://user-images.githubusercontent.com/19561856/139707323-20fdbc69-cc30-4758-a994-8f064615c460.png)
Notice that in dark mode, the pencil icon on the tab bar to the left changes to a symbolic icon, being solid white. This is something that I like a lot. Unfortunately, the document list icons do not change accordingly. I'd expect the document list icons to also look like symbolic icons of pencils, rather than red/blue save files.

**Comment by thomassmith311** [comment]
@donho Would we be able to change this?

**Comment by donho** [comment]
@thomassmith311 
I approve this feature request.
However, I have other priority to achieve and I will let other contributors work on it.
