### ISSUE TITLE
Notepad++ has a Reload false alarm / bug? "This file has been modified by another program. Do you want to reload it"? even when it hadn't been recently modified at all?!

### ISSUE THREAD

**Issue by AscendChina** [notepad-plus-plus/notepad-plus-plus#10753]
Had a weird incident recently where I had multiple text (.txt) based documents that I had written myself (basically notes, reminders, scratchpad stuff) and I'm using notepad++ and with multiple tabs open. I don't have the MS notepad open nor do I have any other editor application (such as Word etc) open/running. I only have one instance of (multi-tabbed) notepad++ open. 

I was doing something in the web browser and switched to the notepad++ application, suddenly I get the prompt about "Reload -- This file has been modified by another program. Do you want to reload it?" and out of habit/instinct I just clicked on "Yes" to get the nag dialog box out of the way, hoping then I could tab over to the text file that I had been using as a pastebin for my copy/paste clipboard of things I was copying from the firefox/chrome browser....

Immediately I'm presented with another such prompt, asking me the exact same question about if I wished to Reload this new tab/ additional text file, that is when I got a bit suspicious since I new for sure I hadn't been updating two different text files... so I took a screenshot with greenshot of it.... then to my surprise after this time clicking that No I didn't wish to reload, I'm prompted a THIRD time about if I want to reload yet ANOTHER tab/instance/textfile! I also click No....

Afterwards since each time it shows the exact path of the text file in question that is asking about reload, I go to the path on the Windows Explore (I'm using Windows 10) and right click each of the text files to check the Created, Modified, Accessed etc and they were from back in late October!

These text files are in a directory that is sync'd by MEGA (sort of like dropbox) with revisions, so I log into my MEGA account and check the revision histories to see what is going on.... Then I download a couple of prior revisions and confirmed that indeed the data looks good, no sign of data corruption or somehow a revision accidentally reverting by mistake, and indeed the MEGA revision confirmed what Windows Explorer confirmed, and that is there hadn't been any changes since October to the files....

Yet, I reboot my machine each night, and my computer hadn't been up for more than 12 hours from the last reboot, I don't do sleep or hibernation, so there is no way I could have had this notepad++ instance open for more than a few hours.... The tabs that I had open weren't edited/modified since October, and yet tonight for some strange reason I got prompted by Notepad++ stating that these files have been changed and asking me if I wish to reload?

My question **is there a bug with Notepad++ that could be doing this false alarm/alert** or is it that my computer is compromised somehow and files are changing behind the scenes without me being aware?

**Comment by AscendChina** [comment]
On slightly related note, I am surprised this bug from 2017 still not fixed in latest notepad++

https://github.com/notepad-plus-plus/notepad-plus-plus/issues/3333

**Comment by xomx** [comment]
Append please your Notepad++ debug info (main menu -> ? -> Debug Info...) and your settings for the File Status Auto-Detection in Preferences -> MISC.

**Comment by ArkadiuszMichalski** [comment]
@donho Maybe another regression due last change?

https://community.notepad-plus-plus.org/topic/22093/notepad-has-a-reload-false-alarm-bug-this-file-has-been-modified-by-another-program-do-you-want-to-reload-it-even-when-it-hadn-t-been-recently-modified-at-all/4

**Comment by donho** [comment]
@ArkadiuszMichalski 
The most important last change is the writing routine which caused a lot of regression on file saving. 
However, the file status detection should not be related to this change and Notepad++ could not be the culprit of this issue... We need more data for judging it anyway.

**Comment by monkyyx** [comment]
Same issue in thread #10688. Settings for the File Status Auto-Detection should be the default ones.

![np++](https://user-images.githubusercontent.com/88665772/141260293-edd82ee7-9b5f-400b-a231-8ea1654e3568.png)

**Comment by xomx** [comment]
I have suspected the version 8.1.5+, but I cannot reproduce it while debugging in similar scenario with DropBox and I am not going to install MEGA only for that. Any other developer with more luck?

Also I am curious how the file change status detection is connected with that (as Don already stated). Maybe the sharing network service is changing the files somehow (not the content, I know, but what about different file time)? In the mean time the ones affected by this issue can try the last N++ appveyor build with fix for file saving sharing:

https://ci.appveyor.com/project/donho/notepad-plus-plus/builds/41487708

And please report back if this build fixes also this problem.

**Comment by monkyyx** [comment]
It's for sure version 8.1.6+, 8.1.5 doesn't have this issue. Unfortunately the build above didn't fix the issue for me.

**Comment by donho** [comment]
@monkyyx 
Are you sure v8.1.6 doesn't have this issue?

**Comment by donho** [comment]
@ArkadiuszMichalski 
After reading the  #10688, you're right about it - it's another regression for sure.

**Comment by donho** [comment]
I have no Mega so I can't reproduce this issue.
However, I find some incoherent code of timestamp detection  part and did a blend fix:
http://download.notepad-plus-plus.org/repository/MISC/

@AscendChina 
Could you guys test the fixed binary (download above) and confirm me if it work (and the message you see) please?

**Comment by donho** [comment]
@AscendChina 

The fix of this issue has caused another regression, so the fix has [been revert](https://github.com/notepad-plus-plus/notepad-plus-plus/commit/bab3573be708bb908b8080e3e2007ea78a7f1932). In order to avoid this issue happening again in the next release, could you guys help us to identify the real problem, by using the following binary: [Notepad++ x86](https://ci.appveyor.com/api/buildjobs/l55mssnvg431a717/artifacts/Notepad%2B%2B.Win32.Release.exe) or [Notepad++ x64](https://ci.appveyor.com/api/buildjobs/50e43knu62r917mq/artifacts/Notepad%2B%2B.x64.Release.exe).

The binary contains the writing log ability in case of problem. To activate log, you should:

1.    Add an empty "nppLogNetworkDriveIssue.xml" file beside of notepad++.exe, or if you have no admin privilege, you can add this file into `%APPDATA%\Notepad++\`.
2.    Create `C:\temp\` directory, if it doesn't exist yet.
3.    Start notepad++.exe, and wait for the false alert happens from the network drive. If the errors occur, there should be some trace in "C:\temp\nppLogNetworkDriveIssue.log". Please provide nppLogNetworkDriveIssue.log to us.

With the information you provide, there might be better chance to fix it finally.
Thank you in advance!
