### ISSUE TITLE
Daylight saving time causing data loss if revisions overwrite and Notepad++ 'Reload' false positive?

### ISSUE THREAD

**Issue by AscendChina** [notepad-plus-plus/notepad-plus-plus#10757]
So I have a sync'd MEGA.NZ (like dropbox) folder to a local folder/directory on my harddrive. I also have set up Mega to use revisions. **I'm working on a text based document late into November 6th 2021, and I forgot that its daylight savings where the time goes BACKWARDS 1 hour at exactly 2AM back to 1AM....** so all throughout the hours of the night I'm typing and saving the text document in notepad++ and Mega is doing a good job of keeping sync'd revisions etc.... **then suddenly at around 1:59AM local time, the clock on my system goes back to 1:00AM local time.... I don't even notice it, except for the fact that I get a prompt in notepad++ saying that the text document has changed and that if I wanted to 'reload' the new version from disk.... except I only had one copy of the text file open and hadn't made any changes in the last couple minutes**, certainly not at the time I got the prompt.... so the only thing I can think of is the notepad++ got confused when it all of a sudden saw a different timestamp for last modified.... 

**Could it be possible that due to the time jump issue with daylight savings time** that Mega accidentally or inadvertently went back to an earlier revision and erased the entire hour of work I had done from 1:00am to 2:00am (when 2:00am went back to 1:00am) etc because of the time reversion due to daylight savings?

And/or is this a **bug/flaw in the way notepad++ auto detects changes? Did the going back one hour at the daylight savings time trip it up?!**

**Comment by monkyyx** [comment]
The core issue is related to #10688 & #10753 and fixed by #10774. I've tested it by manually changing the timezone back an hour.

**Comment by donho** [comment]
@AscendChina 
Please check the old issue you created instead of creating the new issue.
