### ISSUE TITLE
compatible with a new stlye of context menu offered in Windows 11

### ISSUE THREAD

**Issue by Songxwn** [notepad-plus-plus/notepad-plus-plus#10768]
### Steps to Reproduce the Issue

1. compatible with a new stlye of context menu offered in Windows 11
2. 
3. 

### Expected Behavior
<compatible with a new stlye of context menu offered in Windows 11>

**Comment by ArkadiuszMichalski** [comment]
Duplicate of https://github.com/notepad-plus-plus/notepad-plus-plus/issues/10320.
