### ISSUE TITLE
double click selection stops including added character as part of word

### ISSUE THREAD

**Issue by mbertucci47** [notepad-plus-plus/notepad-plus-plus#10760]
### Description of the Issue
I have added the backslash `\` to the word character list under the Delimiter section of Preferences so that when I double click to select text, the selection includes any `\`'s (useful for editing TeX related documents). However after some undetermined amount of time of having NP++ open, this behavior reverts to not including the `\`. Closing and reopening NP++ temporarily fixes the problem but the problem repeats.

### Steps to Reproduce the Issue
1. Add `\` to Word Character List in Preferences.
2. Use double click as expected (includes `\` in selection) for a few minutes.
3. Eventually double click stops including `\` in selection.

### Expected Behavior
<img width="50" alt="correct" src="https://user-images.githubusercontent.com/61854785/140805110-757d1317-c28e-4ce1-b0ed-f819e000ef83.png">

### Actual Behavior
<img width="50" alt="incorrect" src="https://user-images.githubusercontent.com/61854785/140805187-e0d8e09f-1db0-4d6d-8ad2-7e0523a482a8.png">

### Debug Information
Notepad++ v8.1.9   (32-bit)
Build time : Oct 21 2021 - 23:32:04
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 10 Home (64-bit) 
OS Version : 2009
OS Build : 19044.1320
Current ANSI codepage : 1252
Plugins : FingerText.dll 

The problem did not seem to occur with 64-bit NP++. It only started after switching to 32-bit so that I could use the FingerText plugin, which is not available for 64-bit.

**Comment by ArkadiuszMichalski** [comment]
@mbertucci47 What happend without `FingerText.dll` plugin and 32-bit Notepad++?

**Comment by mbertucci47** [comment]
32-bit version seems to work just fine without `Fingertext.dll`

**Comment by ArkadiuszMichalski** [comment]
So this problem should be addressed to the author of this plugin. Although it looks inactive: https://github.com/erinata/FingerText.

**Comment by alankilborn** [comment]
Recommend CLOSURE of this item.
