### ISSUE TITLE
Feature Request: Expose an event to plugins when the active view changes.

### ISSUE THREAD

**Issue by Kered13** [notepad-plus-plus/notepad-plus-plus#10772]
My current context is that I'm writing a plugin that presents autocompletion results and basically takes over the autocompletion process from Scintilla, with internal state that needs to be reset when the autocompletion closes. It would be very convenient if my plugin could be notified when the active view changes so it could cancel the autocompletion session and reset it's state. There are other potential workarounds, but this would be the simplest solution for a plugin.

I don't mind writing the code, if you approve of the change.

**Comment by dail8859** [comment]
Have you looked at [NPPN_BUFFERACTIVATED](https://npp-user-manual.org/docs/plugin-communication/#nppn-bufferactivated)? This notification will tell you when another buffer (i.e. another file) is activated within Notepad++.

**Comment by Kered13** [comment]
I tried it earlier and it didn't seem to fire on view changes, but I tried it again just now and it does fire. Not sure how I missed that earlier.

It still seems like this could be a useful notification, but NPPN_BUFFERACTIVATED is good enough for my purposes.

**Comment by dail8859** [comment]
Glad to hear. If you have more questions about plugin development feel free to start a discussion at the [plugin development](https://community.notepad-plus-plus.org/category/5/plugin-development) section of the community forum.
