### ISSUE TITLE
Why not provide a Linux or MacOS version?

### ISSUE THREAD

**Issue by yxcore** [notepad-plus-plus/notepad-plus-plus#10770]
### Steps to Reproduce the Issue

1. 
2. 
3.

**Comment by dail8859** [comment]
This topic has been [discussed](https://community.notepad-plus-plus.org/) over on the forum several times. I don't have a direct link to any of the discussions currently. The short answer is the code is written using very specific Windows API calls. There are some ways to run it on Linux (and maybe MacOS) but they take extra libraries to emulate the Windows API layer.
