### ISSUE TITLE
Move potentially destructive "Close All ..." actions away from "Close"

### ISSUE THREAD

**Issue by mr-brunes** [notepad-plus-plus/notepad-plus-plus#10776]
### Description of the Issue

When closing a document via right click in the Document List or File > Close with the document selected, the multiple destructive opposite actions of "Close All ..." are perilously near to "Close" and are very easily clicked by mistake.

This ends up being a real pain as the Recent files list is not long enough to restore all the files (and that’s if I could even recall which ones I had open).

Suggestions:
1) In the file menu, Move Close All action away from Close e.g. to be underneath Close More.
2) For the contextual right click menu, move the nearby opposite bulk file actions "Close All ..." to a nested sub menu, similarly to the File menu.  I imagine that the Close All functions are more rarely used function than Close so it would not introduce more complexity to most workflows.

### Steps to Reproduce the Issue

1. Either Right click document in Document List or use File menu
2. Move mouse pointer to the Close option, but notice that Close All options are very easy to click by mistake
3. 

### Debug Information

Notepad++ v8.1.9   (64-bit)
Build time : Oct 21 2021 - 23:37:53
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : D:\Dropbox\Apps\Notepad++
OS Name : Windows 10 Pro (64-bit) 
OS Version : 2009
OS Build : 19043.1348
Current ANSI codepage : 1252
Plugins : AutoSave.dll mimeTools.dll NppConverter.dll NppExport.dll

**Comment by thomassmith311** [comment]
Moving Close All under Close More in the file menu is a good idea, should require a change in "menuCmdID.h". Let me see what I can do when I get the time. The nested window would be more complicated, but I can see if I can figure that out.

**Comment by mr-brunes** [comment]
Tx for implementing option #2 in v8.4.6 (though I didn't spot it in the readme) i.e. a new contextual "Close Multiple Tabs" nested menu option which moves potentially destructive operations away from an easy mis-click.

**Comment by alankilborn** [comment]
@mr-brunes Can you close this issue now?
