### ISSUE TITLE
Installation message change request

### ISSUE THREAD

**Issue by poolshrk** [notepad-plus-plus/notepad-plus-plus#10778]
I hope this is the correct place for this request.

I am affiliated with a large international High School/Middle school competition.

I absolutely love Notepad++, and I like to put it on competition VMs that students use.

Unfortunately we can no longer use Notepad++ due to the installation message "Software is like sex: It's better when it's free".

It would be great if the message could be replaced with something more non-controversial for school systems.

If not, no worries, I will continue to love Notepad++. Thank you all for your time, hard work, and amazing software.

**Comment by 89z** [comment]
This is being discussed online:

https://news.ycombinator.com/item?id=30959244

I have to agree with issue poster, its kind of a dumb reason to lose users over.

**Comment by 89z** [comment]
https://github.com/notepad-plus-plus/notepad-plus-plus/pull/11503
