### ISSUE TITLE
DarkMode: File Tab Status reverting to normal icons

### ISSUE THREAD

**Issue by Ashfaaq18** [notepad-plus-plus/notepad-plus-plus#10775]
### Description of the Issue

![fileTabStatus_prob](https://user-images.githubusercontent.com/27722888/141607204-5629b1d3-a90f-42ad-9e90-60b94de74ca6.gif)

notice the icon next to the "new 1" file name. Dark mode has its own icons, but when you toggle the alternate icons option under the Tab Bar preferences, the dark mode icon set does not appear back when unticked.

### Steps to Reproduce the Issue

1.  Open Notepad++ in darkmode
2.  notice any opened file or new files tab bar icon
3.  now go to Settings->Preferences..
4.  and Tick the "Alternate icons" under the "Tab bar" section
5.  Now untick it back again

### Expected Behavior

Icons should revert back to Dark Mode icon set

### Actual Behavior

Icons revert back to Normal Mode icon set

### Debug Information
Notepad++ v8.1.9   (64-bit)
Build time : Oct 21 2021 - 23:37:53
Path : C:\...\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : ON
Cloud Config : OFF
OS Name : Windows 10 Pro (64-bit) 
OS Version : 2009
OS Build : 19042.1348
Current ANSI codepage : 1252
Plugins : mimeTools.dll NppConverter.dll NppExport.dll

**Comment by thomassmith311** [comment]
Right, I've noticed this for a while and it's pretty annoying. When closing the app while Alternate Icons are _not_ selected in settings, then reopening it, it fixes itself. But this issue really does need to be solved.
