### ISSUE TITLE
when only click Save, it Auto create a copy itself .txt.bak

### ISSUE THREAD

**Issue by SatisfactoryBug** [notepad-plus-plus/notepad-plus-plus#10788]
Notepad++ v8.1.9.1

It might be because of the version [I not sure] but after update to v8.1.9.1 everytime i click Save it make a copy New Text Document (3) - Copy.txt.bak as you see .txt.bak, i dont know why it auto make a copy after click Save as i only wanted to Save that it

**Comment by rimrul** [comment]
This is a result of #10725

**Comment by SatisfactoryBug** [comment]
Thank you and sorry i did not find that Subject "Enable backup-on-save by default"
