### ISSUE TITLE
Html Comments with Auto Insert

### ISSUE THREAD

**Issue by Oi3** [notepad-plus-plus/notepad-plus-plus#1078]
In html, if you activate auto insert for html / xml close tags, when you try to do a comment:
 , you will end up with  </!-->
You can activate the auto insert setting by going to:
settings > preferences > auto-completion > auto insert > html/xml close tag.

**Comment by dail8859** [comment]
What version are you using? v6.8.4 and up shouldn't have this issue. It was reported and closed in #957

**Comment by Oi3** [comment]
Sorry for late reply, I am using v6.8.3, but when i press the ? and then
click on update, it says there is no update available.
Thanks..

**Comment by Oi3** [comment]
I reinstalled np++ from your website and it works fine, the comment in html
with the auto complete on doesn't add the bit on the end thank you.

However, when you declare doctype in v6.8.6, when you write: <!DOCTYPE
html> you get <!DOCTYPE html></!DOCTYPE> , it is not a big issue as you
only really declare the doctype once.

**Comment by dail8859** [comment]
> when you write: you get </!DOCTYPE>

Closed by #1510
