### ISSUE TITLE
[Feature request] Possibility to set color for the TABs

### ISSUE THREAD

**Issue by recoil1992** [notepad-plus-plus/notepad-plus-plus#10786]
Hello notepad++ developers,
it would be nice to have a possibility to color the TABs for better differentiation between opened documents.
I am working with many opened documents for my projects and it many times requires opening the files with the same names, but in different folders. It would be nice to visually distinguish between them.
This could be implemented like automatic coloring of TABs of all the documents from the same folder by one color while TABs of documents from other folder by different color.
Or manually, to change TAB color as per actual need (right click the TAB, set color).

Thank you for considering this and also many thanx for the best text editor ever.

**Comment by ScythianBeastie** [comment]
I second this request. I often work on humongous projects and it would be very very useful to be able to discern different categories of files from one another. Color is the fastest way for my own brain to recognize differences in data, and there are likely other folks who have this same setup. 

I color-code tabs extensively already in other programs like MS Excel, Royal TS, etc.

Thank you very much for your consideration! Notepad++ truly is the best text editor, and I recommend it to everyone who needs one!

**Comment by alankilborn** [comment]
Released in v8.4.6.  Can be CLOSED.

**Comment by ArkadiuszMichalski** [comment]
Implemented by https://github.com/notepad-plus-plus/notepad-plus-plus/pull/12098.
