### ISSUE TITLE
FEATURE REQUEST - when there is a selection and we press ctrl-H (find and replace), set on the checkbox "in selection"  as default.

### ISSUE THREAD

**Issue by mfinky** [notepad-plus-plus/notepad-plus-plus#10793]
### Description of the Issue

FEATURE REQUEST - when there is a selection and we press ctrl-H (find and replace), set on the checkbox "in selection"  as default.
<br/>

### Steps to Reproduce the Issue

1. User selects a paragraph, 
2. uses presses ctrl-H (find and replace).
3. Suggested behaviour: notepad++ shows the "In Selection" box checked by default.  i.e. the replace and change applies to the selection only (by default).

### Expected Behavior

"in selection" is checked by default (can be cleared if needed)

### Actual Behavior

{In Selection} is not checked.

**Comment by mfinky** [comment]
I was nto bale to find a way to sbmit a feature request.  I apologize for submitting this as "issue".

**Comment by timakzver** [comment]
During the update, the program does not know its' installation location and offers a new location in program files while I install it on a different disk. Could you please make a change such that it automatically knows its location from the previous installation?

**Comment by vinsworldcom** [comment]
Interesting, but when there is a selection and I press `Ctrl+F` or `Ctrl+H` for find or replace respectively, I typically want what is highlighted to be what I'm searching for (i.e., the "Find what" text box).  Thus, searching in that selection would return just the one result already highlighted to "Find".

Obviously, others may have different workflows, but highlighted text being the "Find what" rather than the range (i.e., selection) to search in must be more common / prevalent?

Cheers.

**Comment by mfinky** [comment]
Hi Vinsworldcom,
I believe you **are** correct.  Point taken.
I will just keep pressing `Alt+I` to tick the checkbox.
Thank you!
Marcelo

**Comment by vertigo220** [comment]
Something else to consider: if the selection is small, it's almost certainly meant as a "find what" whereas if it's large, i.e. multiple lines, it's very likely the user intends it as the search range, and _not_ as a "find what." So perhaps it could be intelligent about it and auto-check the box if more than, e.g., 5 lines or 1,000 characters are selected.

**Comment by alankilborn** [comment]
>auto-check the box if more than, e.g., 5 lines or 1,000 characters are selected.

This is already done; the threshold is 1024 bytes.
