### ISSUE TITLE
reload file but the label is still red

### ISSUE THREAD

**Issue by Tvirus** [notepad-plus-plus/notepad-plus-plus#10796]
### Description of the Issue

v8.1.9 (64-bit)
### Steps to Reproduce the Issue

1. open git.c
2. Modify git.c with another software, and save file
3. back to notepad++, choose No
![image](https://user-images.githubusercontent.com/42616862/142377908-f2e4e77f-20d8-4a8c-8dac-72d1da6bfb14.png)
4. Reload from the disk (Ctrl+R) and choose Yes
5. table is still red
![image](https://user-images.githubusercontent.com/42616862/142377180-74ce672d-f774-488a-8966-4f581eb81199.png)

**Comment by thomassmith311** [comment]
Cannot reproduce; icon switches to blue for me when choosing "yes." What is your debug info? (fyi Hit Debug info... as per picture below and copy contents of window)
![image](https://user-images.githubusercontent.com/19561856/142701662-28b3b843-167f-408d-86ed-93ab09f64a8b.png)

**Comment by thomassmith311** [comment]
Hmm I did not realize you had 8.1.9 and not 8.1.9.1. 8.1.9.1 fixed a certain saving issue. Can you update your program real quick first and see if that fixes it? If not then I would need the info I asked for before.

**Comment by Tvirus** [comment]
Notepad++ v8.1.9   (64-bit)
Build time : Oct 21 2021 - 23:37:53
Path : D:\Notepad++\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 10 Pro (64-bit) 
OS Version : 2009
OS Build : 19043.1348
Current ANSI codepage : 936
Plugins : mimeTools.dll NppConverter.dll NppExport.dll NppMarkdownPanel.dll

**Comment by Tvirus** [comment]
When the icon is red after reloading, and then go to File >> Save, i can save the file, and the icon change blue

**Comment by Tvirus** [comment]
8.1.9.2 still has this problem

**Comment by Tvirus** [comment]
i use anthor computer, and i didn't install any plugins，8.1.9.2 still has this problem，（8.1.6 is ok）

**Comment by Tvirus** [comment]
1. open git.c
2. Modify git.c with another software, and save file
3. back to notepad++, **choose no**
4. Ctrl+R and **choose  yes**

table is still red

**Comment by xomx** [comment]
I can reproduce that (with the updated step No.3).
