### ISSUE TITLE
Can not view Unicode glyphs inserted by Windows 11 Emoji popup 

### ISSUE THREAD

**Issue by GwenDragon** [notepad-plus-plus/notepad-plus-plus#10804]
### Description of the Issue
Unicode glyphs from Windows Emoji popup f.ex. special interpunctation or non-latin s chars are shown as rectangles in text

### Steps to Reproduce the Issue
1. Open Notepad++
2. Have default encoding for new files UTF-8
2. Hit Win . to get Emoji popup
3. Select Symbols → Interpunctation → ⁂ and others
4. Inserted char is shown only as rectangle

### Expected Behavior
All unicocde glyphs can be inserted and displayed like Windows Editor or Komodo IDE does

### Actual Behavior
Inserted unicocde glyphs show rectangles

### Debug Information
Notepad++ v8.1.9.1   (32-bit)
Build time : Nov 13 2021 - 15:20:19
Path : P:\Notepad++\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 10 Enterprise (64-bit) 
OS Version : 2009
OS Build : 22000.318
Current ANSI codepage : 1252
Plugins : ComparePlugin.dll Explorer.dll JSLintNpp.dll JSMinNPP.dll LanguageHelp.dll mimeTools.dll NppConverter.dll NppExec.dll NppExport.dll NppFTP.dll NppTextFX.dll RegexTrainer.dll RunMe.dll Tidy2.dll 

![Animation](https://user-images.githubusercontent.com/46133149/142674007-35817922-fbc3-42ce-acd8-d2822c7c1b59.gif)

**Comment by Docteh** [comment]
Do you have DirectWrite enabled? https://github.com/notepad-plus-plus/notepad-plus-plus/issues/10790#issuecomment-972701827

**Comment by GwenDragon** [comment]
> Do you have DirectWrite enabled? [#10790 (comment)](https://github.com/notepad-plus-plus/notepad-plus-plus/issues/10790#issuecomment-972701827)

No.
Bu enabling DirectWrite helped to solve the issue.

Would be good to have it enabled by default.
