### ISSUE TITLE
Greek case conversion from lower to upper gives improper result

### ISSUE THREAD

**Issue by Bejuzoobi** [notepad-plus-plus/notepad-plus-plus#10802]
### Description of the Issue

Within a UTF8 file, selecting, for example, the text, ' έφηβος ', and applying convert to case yields a result of ' ΈΦΗΒΟς '. The correct conversion would be ' ΕΦΗΒΟΣ ', without any accent mark and with the final 'ς' converted to 'Σ'.
### Steps to Reproduce the Issue

1. Within a UTF8 file, select any Greek text containing accents or final s ('ς') character.
2. Apply convert to uppercase from the edit menu.
3. 

### Expected Behavior

One expects to see Greek uppercase without accents and final s character rendered as 'Σ'.
### Actual Behavior

One sees, instead, accented uppercase characters ( Ά, Έ, Ή, Ί, Ύ, Ό )  and the final s character ( 'ς' ) unchanged.
### Debug Information

Notepad++ v8.1.9   (32-bit)
Build time : Oct 21 2021 - 23:32:04
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 10 Enterprise (64-bit) 
OS Version : 2009
OS Build : 19043.1348
Current ANSI codepage : 1252
Plugins : ElasticTabstops.dll mimeTools.dll NppConverter.dll NppExport.dll

**Comment by thomassmith311** [comment]
I wrote every Greek character on a line in lowercase, then in uppercase, manually, to see what all would convert incorrectly:
![image](https://user-images.githubusercontent.com/19561856/142699802-2a7574a6-105b-451c-982f-407bb274edc7.png)
σ and ς are the same letter (sigma, pronounced like "s"), but ς is used when it is the last letter of a word.
Then I copied each line:
![image](https://user-images.githubusercontent.com/19561856/142699877-fda48639-b314-4b39-9e4f-cbdd2cfeccc8.png)
And case converted lines 2 and 4:
![image](https://user-images.githubusercontent.com/19561856/142699918-2d4b2bd1-633b-4051-9dc8-858b94b87b24.png)
The only issue occurs with the sigma. Σ always converts to σ. σ converts to Σ, but ς does not convert.
(And, of course, there is the issue with the accents.)

**Comment by Bejuzoobi** [comment]
Yes. Thank you for a very detailed and complete description of the problem. 

And, no, I do not think it will be easy to fix, although the conversion from ς to Σ should be much easier than the other way around. 

The accents suffer a similar problem. It should be easy enough to discard them when converting from lowercase to uppercase, but virtually impossible to recover them when converting uppercase to lowercase, unless some sort of spelling function is applied which, I think, is far beyond what a case conversion should be doing. 

My personal interest is in the lowercase to uppercase conversion. I would be very happy if that were improved. We have to live with uppercase conversion producing unaccented lowercase text. And there are some exceptions (  Ή  when it is a single letter word meaning "or"), so even dropping the accents would not be a perfect solution.

This is beyond me, but I did find traces of others struggling with the same issue: https://icu.unicode.org/design/case/greek-upper

**Comment by thomassmith311** [comment]
I don't know how the case conversion works, but if each one letter of the alphabet is set to have just one set of capital and lowercase letters, it could be tricky to assign two lowercase letters to one capital.

**Comment by Bejuzoobi** [comment]
I don't know how it works either. If it is too difficult to fix, I would understand and drop the matter. I can replace the uppercase accented characters and the ς with search and replace after a  faulty conversion. Perhaps we need to wait for someone else to solve the problem. I will wait a few days and then close the issue if nothing else turns up.

**Comment by thomassmith311** [comment]
@donho Would you be able to give a brief explanation of how the case conversion works?

**Comment by rimrul** [comment]
I think it comes down to the use of [`CharUpperW()`](https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-charupperw) in [`ScintillaEditView::changeCase()`](https://github.com/notepad-plus-plus/notepad-plus-plus/blob/master/PowerEditor/src/ScintillaComponent/ScintillaEditView.cpp#L2814) which [does weird things when upper and lower case aren't the same length](https://devblogs.microsoft.com/oldnewthing/20200804-00/?p=104040)

Microsoft recommends `LCMapStringEx()` instead.

**Comment by Bejuzoobi** [comment]
Thank you everyone who considered this. I promised not to let it hang open for too long so I am closing the issue now. I think the stage is set for making an incremental improvement, and I would not call it "resolved". But clearly making a better case converter would be a major undertaking and  is probably more properly address in Scintilla itself.
