### ISSUE TITLE
Partial inoperability of dark mode on the first launch of the application and cloud synchronization of settings

### ISSUE THREAD

**Issue by Korb** [notepad-plus-plus/notepad-plus-plus#10801]
### Steps to Reproduce the Issue
1. Enable in-app dark theme and cloud sync via Google Drive
2. Turn on the PC or restart Windows
2. Launch the application with a shortcut from the Windows Quick Launch bar

### Expected Behavior
After installing a dark theme in the application settings - the application always starts with a dark theme.

### Actual Behavior
The dark theme does not apply to all elements of the application. To fix it, I have to open "Preferences" / "General" / "Dark Mode", uncheck "Enable dark mode" (dark mode will be disabled) and set it back (dark mode will be enabled including the main text field of the application).

### Debug Information
Notepad++ v8.1.9.1   (64-bit)
Build time: Nov 13 2021 - 15:28:20
Path: C:\SW\NotepadPP\notepad++.exe
Command Line: 
Admin mode: OFF
Local Conf mode: ON
Cloud Config: J:\Мой диск\Software\Microsoft Windows\Notepad++\Settings
OS Name: Windows 10 Pro (64-bit) 
OS Version: 2009
OS Build: 19044.1379
Current ANSI codepage: 65001
Plugins: DSpellCheck.dll mimeTools.dll NppConverter.dll NppExport.dll ShtirlitzNppPlugin.dll urlPlugin.dll

This is how the application looks after the first launch:
![2021-11-19_11-07-44](https://user-images.githubusercontent.com/3509797/142588991-13ec8954-e8ad-43d9-96cf-8c917e61c08a.png)

This is how the app looks after turning the dark theme off and on again:
![2021-11-19_11-10-24](https://user-images.githubusercontent.com/3509797/142589020-4d9be20d-676b-49cd-8391-0c1bacc090ef.png)

"Settings on cloud" / "Set your cloud location path here:"
![2021-11-19_11-08-58](https://user-images.githubusercontent.com/3509797/142589084-a3430013-6b56-4d20-82dc-070a082de80b.png)

"Global Styles: Global override" screen:
![2021-11-19_11-09-56](https://user-images.githubusercontent.com/3509797/142589086-da987079-cac5-4d97-8644-41aa120def32.png)

"Global Styles: Default Style" screen:
![2021-11-19_11-10-03](https://user-images.githubusercontent.com/3509797/142589087-c7972cab-8802-4382-8d13-1d47246d3616.png)

Google Drive 52.0.6.0 about screen:
![2021-11-19_11-13-10](https://user-images.githubusercontent.com/3509797/142589089-4d3974d4-17b9-4f65-ba33-6858441d9619.png)

**Comment by thomassmith311** [comment]
Seems like it only does not apply to the main text field. The main text field is handled by Style Configuration. Checking "Enable Dark Mode" automatically changes the Style to DarkModeDefault. Are there any other parts of the application that do not become dark?

**Comment by Korb** [comment]
> Are there any other parts of the application that do not become dark?

I didn't notice. If I don’t correct this message within 24 hours, it means that the dark theme is disabled for me only for the text field. What other data can I provide to localize the problem?

**Comment by Korb** [comment]
![Notepad++ first start color bug and dark mode](https://user-images.githubusercontent.com/3509797/174434403-570c4839-775c-4277-be14-3b4fb37dc105.gif)
Notepad++ 8.2.1 (64-bit)
Microsoft Windows 10.0.19043.1766
Google Drive 59.0.3.0

**Comment by Korb** [comment]
![Notepad++ Dark Mode bug](https://user-images.githubusercontent.com/3509797/195870635-219e9520-0425-4ba0-bdbb-45976ec8ba49.gif)

Notepad++ 8.4.5 (64-bit)
Microsoft Windows 10.0.19043.2130
Google Drive 64.0.4.0

**Comment by Korb** [comment]
Perhaps this is due to the fact that on one computer I have Notepad++ **installed**, and on the other I use a **portable** version.

**Comment by ozone10** [comment]
This is not dark mode, but theme issue.
Currently cloud does not redirect themes folder and theme is not fully portable at start up.
