### ISSUE TITLE
Notepad++ shuts down when regex search for Greek text has unclosed parenthesis

### ISSUE THREAD

**Issue by JBradyK** [notepad-plus-plus/notepad-plus-plus#10803]
### Description of the Issue
The error detection on Regex searches in the find box doesn't warn the lack of a close parenthesis when the search string is Greek characters. 

### Steps to Reproduce the Issue
Select Find from Search menu
type  " (Παυσ  " [accidentally leaving out close paren] 
2. Click Find Next
3. Sudden death.

### Expected Behavior
Error message "invalid regular expression"

### Actual Behavior
Notepad shuts down, all unsaved edits lost.

### Debug Information
Notepad++ v8.1.5   (64-bit)
Build time : Sep 26 2021 - 15:23:23
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 10 Home (64-bit) 
OS Version : 1909
OS Build : 18363.1556
Current ANSI codepage : 1252
Plugins : DSpellCheck.dll mimeTools.dll NppConverter.dll NppExport.dll

**Comment by donho** [comment]
It's fixed in https://github.com/notepad-plus-plus/notepad-plus-plus/commit/c7140f279b8fd7c6b6506d4ea2a9b0778e57dc04.
The fix will be in the next release.

**Comment by ArkadiuszMichalski** [comment]
@donho Not in https://github.com/notepad-plus-plus/notepad-plus-plus/commit/f52c2b022d4906703e20c06a6b2018c960946792?

**Comment by donho** [comment]
@ArkadiuszMichalski 
You are right - I have had a bad copy-paste. Thank you for the correction!
