### ISSUE TITLE
How to remove the empty spaces after last line?

### ISSUE THREAD

**Issue by batata004** [notepad-plus-plus/notepad-plus-plus#10800]
This never happend before: when I scroll to the last line of a file, notepad++ show empty spaces below it instead of making the last line be at the bottom of the editor (as it should be). This is a freaking terrible idea to allow for this spacing and I cant find anyway to disable this strange behaviour. Check print below

![image](https://user-images.githubusercontent.com/8988923/142478809-21295624-218c-4abb-a268-1a6f16ba7af2.png)

**Comment by dail8859** [comment]
Settings > Preferences > Editing > Enable scrolling beyond last line.

See: https://npp-user-manual.org/docs/preferences/#editing

> ☐ Enable scrolling beyond last line: allows you to scroll (with scroll bar or mouse wheel) so that up to a page of blank space after the last line is visible. (Disabled, scrolling to the end will put the last line of text as the bottom line in the window, when there are more lines of text than are visible in the window)

---

![image](https://user-images.githubusercontent.com/3694843/142492591-4a9d7e6a-5273-417a-abd6-3ad92f7d5457.png)
