### ISSUE TITLE
Dark mode not working In Windows 10 21H2 

### ISSUE THREAD

**Issue by donho** [notepad-plus-plus/notepad-plus-plus#10810]
### Description of the Issue
Dark mode not working In Windows 10 **21H2** 

### Steps to Reproduce the Issue
![image](https://user-images.githubusercontent.com/90293/142747413-11e625a1-5102-4c0d-b52a-c74560d9254a.png)

### Debug Information

Notepad++ v8.1.9.1   (32-bit)
Build time : Nov 13 2021 - 15:20:19
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 10 Enterprise (64-bit) 
OS Version : 2009
OS Build : 19044.1348
Current ANSI codepage : 1252
Plugins : mimeTools.dll NppConverter.dll NppExport.dll

**Comment by Alpengreis** [comment]
It seems the fix has a false name "2H22" is not correct. That affected the changelog too. That is confusing somehow. Could you rename that to "21H2" please?

**Comment by donho** [comment]
Change log comes with release connot change anymore.
However, 3 changes has been done in the announce:
https://notepad-plus-plus.org/news/v8192-released/
https://notepad-plus-plus.org/downloads/v8.1.9.2/
https://community.notepad-plus-plus.org/topic/22169/notepad-v8-1-9-2-release

Thank you for your heads up!
