### ISSUE TITLE
Offensive 

### ISSUE THREAD

**Issue by jchesshir** [notepad-plus-plus/notepad-plus-plus#10814]
### Description of the Issue

I was not amused by the association of free software with free sex in your version 8.1.9.2 software update panel.  Any immoral sexual behavior is subject to life threatening risks.  I do NOT recommend you keep this kind of association with your product's name.  It can leave people with the idea that your software is similarly vulnerable to malware that could leave your user's computers in as bad of a state as STD's put people's bodies in.

I won't be installing this update, nor will I install any future update with Notepad++ as long as I'm seeing that quote.  If it is not removed, I will consider finding another solution altogether, which will not be easy.  I really do love working with Notepad++.

I hope you do not find this post to be disrespectful.  I apologize up front if it comes across that way.  My desire is for your good and the good of the people you interact with.  I believe such flippant thoughts are, taken to their full extent, life threatening, and I just want to encourage you not to go there.  Furthermore, I started to post this on a public forum, but I figured it would be more respectful to put it in a form that has the best chance of being seen by the people who have the best chance of effecting a change, at least initially.

Thank you for your time.

### Steps to Reproduce the Issue
![image](https://user-images.githubusercontent.com/11528004/142895398-ac1bf2fb-6250-4a9a-97eb-a799622f3391.png)

1. Install 8.1.9.2
2. Advance to the License agreement.
3. Notice the quote.

**Comment by donho** [comment]
It's your freedom to not use Notepad++, as my freedom to keep my beloved quote on this software I maintain.
Thank you for showing your viewpoint, your point has been heard but not accepted. This quote will be kept.
