### ISSUE TITLE
Add New Syntax Please 

### ISSUE THREAD

**Issue by Erghel** [notepad-plus-plus/notepad-plus-plus#10812]
Dear Notepad++ developers. Please add LOLCODE, Brainfuck, YoptaScript, Pawn, Beef, Crystal and Eiffel syntax. It will be amazing - make brainfuck (or smth else) code in Notepad++

**Comment by dail8859** [comment]
Language syntax highlight is provided by a 3rd party library called [Lexilla](https://github.com/ScintillaOrg/lexilla). It would be better to submit these types of requests for new languages to that project.
