### ISSUE TITLE
Does not sort correctly

### ISSUE THREAD

**Issue by RNR1995** [notepad-plus-plus/notepad-plus-plus#10822]
Description of the Issue

Edit\Line Operations\Sort Lines as Lexicographic Ascending
Does not sort correctly
Steps to Reproduce the Issue

    Highlight some text then go to Edit\Line Operations\Sort Lines as Lexicographic Ascending

Expected Behavior

Sorted
Actual Behavior

Sorted but not correctly
Debug Information

Notepad++ v8.1.9.2 (64-bit)
Build time : Nov 21 2021 - 04:30:20
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line :
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 7 Professional (64-bit)
OS Build : 7601.24546
Current ANSI codepage : 1252
Plugins : DSpellCheck.dll mimeTools.dll NppConverter.dll NppExport.dll

Sorted correctly
C:\Windows\System32\CMD.exe /C RD /S /Q "C:\Config.Msi"
C:\Windows\System32\CMD.exe /C RD /S /Q "C:\HP"
C:\Windows\System32\CMD.exe /C RD /S /Q "C:\Intel"
C:\Windows\System32\CMD.exe /C RD /S /Q "C:\IntelOptaneData"
C:\Windows\System32\CMD.exe /C RD /S /Q "C:\PerfLogs"
C:\Windows\System32\CMD.exe /C RD /S /Q "C:\Program Files (x86)\HP"
C:\Windows\System32\CMD.exe /C RD /S /Q "C:\Program Files\HP"
C:\Windows\System32\CMD.exe /C RD /S /Q "C:\Program Files\HPCommRecovery"
C:\Windows\System32\CMD.exe /C RD /S /Q "C:\ProgramData\Bromium"
C:\Windows\System32\CMD.exe /C RD /S /Q "C:\ProgramData\Hewlett-Packard"
C:\Windows\System32\CMD.exe /C RD /S /Q "C:\ProgramData\HP"
C:\Windows\System32\CMD.exe /C RD /S /Q "C:\ProgramData\HPQLOG"
C:\Windows\System32\CMD.exe /C RD /S /Q "C:\ProgramData\Microsoft\Windows\Start Menu\Programs\HP"
C:\Windows\System32\CMD.exe /C RD /S /Q "C:\ProgramData\Microsoft\Windows\Start Menu\Programs\Security and Protection"
C:\Windows\System32\CMD.exe /C RD /S /Q "C:\Recovery"
C:\Windows\System32\CMD.exe /C RD /S /Q "C:\swsetup"
C:\Windows\System32\CMD.exe /C RD /S /Q "C:\SYSTEM.SAV"

Notepad++
C:\Windows\System32\CMD.exe /C RD /S /Q "C:\Config.Msi"
C:\Windows\System32\CMD.exe /C RD /S /Q "C:\HP"
C:\Windows\System32\CMD.exe /C RD /S /Q "C:\Intel"
C:\Windows\System32\CMD.exe /C RD /S /Q "C:\IntelOptaneData"
C:\Windows\System32\CMD.exe /C RD /S /Q "C:\PerfLogs"
C:\Windows\System32\CMD.exe /C RD /S /Q "C:\Program Files (x86)\HP"
C:\Windows\System32\CMD.exe /C RD /S /Q "C:\Program Files\HP"
C:\Windows\System32\CMD.exe /C RD /S /Q "C:\Program Files\HPCommRecovery"
C:\Windows\System32\CMD.exe /C RD /S /Q "C:\ProgramData\Bromium"
C:\Windows\System32\CMD.exe /C RD /S /Q "C:\ProgramData\HP"
C:\Windows\System32\CMD.exe /C RD /S /Q "C:\ProgramData\HPQLOG"
C:\Windows\System32\CMD.exe /C RD /S /Q "C:\ProgramData\Hewlett-Packard"
C:\Windows\System32\CMD.exe /C RD /S /Q "C:\ProgramData\Microsoft\Windows\Start Menu\Programs\HP"
C:\Windows\System32\CMD.exe /C RD /S /Q "C:\ProgramData\Microsoft\Windows\Start Menu\Programs\Security and Protection"
C:\Windows\System32\CMD.exe /C RD /S /Q "C:\Recovery"
C:\Windows\System32\CMD.exe /C RD /S /Q "C:\SYSTEM.SAV"
C:\Windows\System32\CMD.exe /C RD /S /Q "C:\swsetup"

FWIW tried the latest portable version on another machine ( WIN10 LTSC) and same result
Thank you
RNR

**Comment by dail8859** [comment]
If I use `Edit > Line Operations > Sort Lines as Lex. Ascending Ignoring Case` then I get your 'correctly' sorted list.

**Comment by RNR1995** [comment]
YIKES

Did not even notice that one, nor did I even think case would be an issue

Thank you very much!

Ron
