### ISSUE TITLE
Let users decide to keep or not HexEdit in installer

### ISSUE THREAD

**Issue by donho** [notepad-plus-plus/notepad-plus-plus#10828]
The current installer remove Hexeditor automatically.
It might be better to let user the choice.

**Comment by Luuk34** [comment]
Just today, when installing 8.1.9.3:
![image](https://user-images.githubusercontent.com/7850737/146984421-0dc08857-6300-4a6a-94b3-2ca2f5407cd5.png)

But simply going to Plugins/Plugin Admin, and re-installing **_solved_** the problem....

So, it is very unclear why disabling on installing an update will solve anything.......

**Comment by donho** [comment]
@Luuk34 
The aim of this message & action is for giving users a warning on HexEditor plugin's crash issue, not really for preventing users from using it.

**Comment by AraHaan** [comment]
Perhaps the best thing to do is fix that plugin.

**Comment by donho** [comment]
> Perhaps the best thing to do is fix that plugin.

Yes, we all know it's the better solution.
The thing is, the original author doesn't maintain the project anymore, and the current maintainer & I tried to fix the crash without success.

Feel free to do your contribution if you want to get it fixed:
https://github.com/chcg/NPP_HexEdit/issues/51

**Comment by AraHaan** [comment]
> > Perhaps the best thing to do is fix that plugin.
> 
> Yes, we all know it's the better solution. The thing is, the original author doesn't maintain the project anymore, and the current maintainer & I tried to fix the crash without success.
> 
> Feel free to do your contribution if you want to get it fixed: [chcg/NPP_HexEdit#51](https://github.com/chcg/NPP_HexEdit/issues/51)

Perhaps the best option is to fork it and then fix it (as part of n++ then) and ship it with the fixed plugin as part of n++ itself.
