### ISSUE TITLE
Highlighting fails in Notepad++ 6.8.6 under some circunstances

### ISSUE THREAD

**Issue by AleWin32** [notepad-plus-plus/notepad-plus-plus#1082]
Having this Java code:
```java
		cod_app =((sessionController.getAttribute("XWtxtcod_app")==null) || (sessionController.getAttribute("XWtxtcod_app")==""))?"":(String)sessionController.getAttribute("XWtxtcod_app");
		idioma = ((sessionController.getAttribute("XWtxtcodidi")==null) || (sessionController.getAttribute("XWtxtcodidi")==""))?"":(String)sessionController.getAttribute("XWtxtcodidi");
```

(note there is 2 tabs before each line, not spaces. This web changed the tabs by spaces), selecting the first word "sessionController" on the first line does not highlight "sessionController" on the second line, but if you select that word on the second line it works highlighting it on the first line.

It works having only 1 tab char at the start of each line.

So the conclusion is, if each line start with 1 tab, the highlighting works, but it fails having 2 or more tabs selecting the word on the first line.

**Comment by AleWin32** [comment]
Sometimes the bug is not reproducible, sometimes it is. It's strange...

**Comment by Cyrillev91** [comment]
Hi @AleWin32 

Could you try this binary then confirm me it’s fixed the issues you reported ?

http://dl.free.fr/vSurTyhnX

**Comment by AleWin32** [comment]
Thank you for your binary Cyrillev91, but now, in Notepad 6.8.6 i'm not getting the error i posted. It's strange. The error only occurs sometimes, so i'm waiting the error to come to grab the steps i followed to reproduce it, and then, try it with your binary. I will tell you.

What have you found in the code? Because the nature of the error (it only occurs sometimes), can be an error related to pointers or some limit not properly checked that may be overwritten by another task in Notepad++...

**Comment by Cyrillev91** [comment]
Hi,
I replace an alloc dynamically buffer by an static alloc : 
replace : 
```
char *listChar = new char[listCharSize+1];
```
by : 
```
char listChar[maxChar+1] = {0}; // with maxChar = 256
```
and remove :
```
delete [] listChar;
```

maybe char *listChar = new char[listCharSize+1]; return null

if listChar = NULL ==> no highlight select text

**Comment by AleWin32** [comment]
But with yoour change, what happen if we select more than maxChar (256) characters?

**Comment by Cyrillev91** [comment]
Hi,
The max size buffer return by SCI_GETWORDCHARS scintilla function is 256 (define in scintilla\src\CharClassify.h, see also).

But if size change in scintilla, I think alloc dynamically buffer is best (unless it is causing this problem)

**Comment by Slamdunk** [comment]
Hi @Cyrillev91 , this bug is very annoying since v6.8.6, and I think it occured before v6.8.6, maybe v6.8.4:
Highlight NOT ok in selected on the first line:
![npp-highlight-ko](https://cloud.githubusercontent.com/assets/152236/11443252/bfbea850-951b-11e5-9946-081b2ad8f1fa.jpg)
Highlight ok in selected on second line:
![npp-highlight-ok](https://cloud.githubusercontent.com/assets/152236/11443250/bfa0512a-951b-11e5-9a78-0d069fc4f786.jpg)
While before, every `date` or `Date` word did work as worldwide highlight.
I hope you can fix it, because NPP is the best IDE and this is a killing feature to me :+1:

**Comment by donho** [comment]
@Slamdunk I believe this bug has been fixed in v6.8.7 ( https://notepad-plus-plus.org/news/kiss-my-app-on-black-friday.html ).
Could you check it with this version?

**Comment by Slamdunk** [comment]
@donho it seems solved :+1:

**Comment by donho** [comment]
:+1:

**Comment by Cyrillev91** [comment]
:+1:
