### ISSUE TITLE
Recognizing file changes behaviour

### ISSUE THREAD

**Issue by Alpengreis** [notepad-plus-plus/notepad-plus-plus#10839]
### Description of the Issue
I am not sure if the current behaviour of recognizing file changes behaviour is correct or not ...

### Steps to Reproduce the Issue
1.  Make sure that the file change recognition is activated in Notepad++.
2.  Open Notepad++ and write some text.
2.  Save as a.txt.
3.  Copy a.txt somewhere as backup.
4.  Change the still opened file in Notepad++ and save it again.
5.  Copy the backup file back (with explorer or so) and overwrite the opened file (a.txt).

### Expected Behavior
Should it recognize the changed file, or is this behaviour ok?

### Actual Behavior
It does not recognize the changed file without a reload.

### Debug Information
Notepad++ v8.1.9.2 (64-bit)
Build time : Nov 21 2021 - 04:30:20
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line :
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 10 Pro (64-bit)
OS Version : 2009
OS Build : 19044.1387
Current ANSI codepage : 1252
Plugins : DSpellCheck.dll mimeTools.dll NppConverter.dll NppExec.dll NppExport.dll PythonScript.dll

Note: if both, the original and the backup file are open in Notepad++ before I overwrite the file, it DOES recognize the changes!

EDITED 5. to make it more clear hopefully ...

**Comment by xomx** [comment]
I can reproduce it (8.1.9.2 x64, Win110Pro 2004).

And no, it is not ok, it should be recognized. I tried v7.9.5 x64 in the exactly same setup and it detected the change.

**Comment by xomx** [comment]
@donho 
I think that this is a regression caused by fix in v8.1.9.1 (Fix reload false alarm from the network drive).
Version 8.1.9 is the last to detect the change described above.

**Comment by donho** [comment]
@xomx 
Could you provide your instructions step by step to reproduce the bug? 
I don't follow the ones provided by the op.

**Comment by xomx** [comment]
It looks like we cannot ignore the case when CompareFileTime returns 1 in Buffer::updateTimeStamp & Buffer::checkFileState.

**Comment by donho** [comment]
The source of this regression :
https://github.com/notepad-plus-plus/notepad-plus-plus/commit/df396b9e698bbc97157113f671513c8c592e72fe

**Comment by donho** [comment]
@pnedev 
This regression comes from https://github.com/notepad-plus-plus/notepad-plus-plus/commit/df396b9e698bbc97157113f671513c8c592e72fe
It was for fixing #10688, #10753 and #10757. 
However the bug #10751 & #10787 persist. So I'm quite sure the fix for nul content file-corruption causes the regression of timestamp. Could you help me to fix it?

**Comment by xomx** [comment]
@donho @pnedev 

Now this is only a guess, but cannot be the problem in 10751 & 10787 (saving is ok when adding stuff, but not if deleting) connected somehow with the use of SetEndOfFile in Win32_IO_File::close() ?

Maybe at the time of SetEndOfFile call the file pointer is not at the expected place (at the end of the data written to the file from the N++ buffer, but at the file-end instead).

**Comment by donho** [comment]
@xomx 
According WriteFile of MS doc: 
`If lpOverlapped is NULL, the write operation starts at the current file position and WriteFile does not return until the operation is complete, and the system updates the file pointer before WriteFile returns.` ([Ref](https://docs.microsoft.com/en-us/windows/win32/api/fileapi/nf-fileapi-writefile))

So file pointer should be on the correct position on SetEndOfFile call, otherwise we would have data corruption. So far our problem is rather access and timestamp problem with network mounted drive.

**Comment by pnedev** [comment]
@donho , @xomx ,

I suspect the same as @xomx  but I think that on network shared drive `SetEndOfFile` call itself fails rather than the file pointer is not in the right position.

@donho , I will create a setup on my side and try to figure out what's happening. I'll try to do it over the weekend.

**Comment by xomx** [comment]
@donho 
Yes, I know that about WriteFile. Evidently it works so in conjunction with the SetEndOfFile for most of the users, but for some reason (maybe specific network storage) for small group of users it does not work as expected.

@pnedev 
One major difference between CRT file IO (fopen...) and WIN32 one (CreateFile...) is the CRT inherent buffering (I expect that was the reason of the problems with saving in N++ at specific circumstances as crashes, rebooting etc.). This buffering helps a lot with saving of small chunks of data on local disk and maybe it also helps with the network saving somehow. Maybe this can influence the fileptr position somehow, but if so, I still have not got it how. I hope you will able to simulate and debug the problem.

**Comment by xomx** [comment]
@donho 
Could you in the meantime release a testing version for the affected users with an error reporting possibility for the SetEndOfFile in the Win32_IO_File::close? I mean something simple like:

if (!::SetEndOfFile(_hFile))
{
	TCHAR szBuf[256];
	_stprintf_s(szBuf, _countof(szBuf), TEXT("ERROR: SetEndOfFile WINAPI failed! (ErrorCode: %u)"), ::GetLastError());
	::MessageBox(NULL, szBuf, TEXT("Notepad++ - Win32_IO_File::close"), MB_OK | MB_ICONWARNING | MB_TASKMODAL);
}

**Comment by donho** [comment]
@xomx 
> Could you in the meantime release a testing version for the affected users with an error reporting possibility for the SetEndOfFile in the Win32_IO_File::close? I mean something simple like:

OK, I'll do it after merging https://github.com/notepad-plus-plus/notepad-plus-plus/pull/10843
