### ISSUE TITLE
SQL syntax highlighter misinterprets backslash as an escaping character which is generally not present in SQL strings

### ISSUE THREAD

**Issue by bOOT-CoDe** [notepad-plus-plus/notepad-plus-plus#10835]
### Description of the Issue
Backslash in SQL is not escaping character with two exceptions:
1. in LIKE statement the escaping character may by defined by ESCAPE clause and you can choose backslash - but then is valid only for the current statement
2. in regular expression is backslash escaping character for symbols with special meaning, i.e. not all backslashes in regular expression are escaping characters

### Steps to Reproduce the Issue

1. write LIKE statement, e.g. `SELECT * FROM DB WHERE UD LIKE '%G\_TERM\_%' ESCAPE '\' ORDER BY ID`

### Expected Behavior
everything between two apostrophes (') should be threated/colored as a string

### Actual Behavior
the last apostrophe in ESCAPE clause is ignored due to precedence of a backslash so everything after ESCAPE clause is threated as a string, even line or block comment until there is another apostrophe

### Debug Information
Notepad++ v8.1.9.2   (64-bit)
Build time : Nov 21 2021 - 04:30:20
Path : C:\TEMP\npp\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 10 Enterprise (64-bit) 
OS Version : 2009
OS Build : 19042.1348
Current ANSI codepage : 1250
Plugins : none

### Screenshot
![Notepad++ SQL bug](https://user-images.githubusercontent.com/23643083/143453247-e61fff17-9d4c-4130-9c75-c6551d3c2700.png)

**Comment by ArkadiuszMichalski** [comment]
Try this: https://github.com/notepad-plus-plus/notepad-plus-plus/issues/8919#issuecomment-701285073. And in future try use the search option, by specifying "SQL backslash" you will immediately have the answer.

**Comment by bOOT-CoDe** [comment]
> Try this: [#8919 (comment)](https://github.com/notepad-plus-plus/notepad-plus-plus/issues/8919#issuecomment-701285073). And in future try use the search option, by specifying "SQL backslash" you will immediately have the answer.

The settings mentioned in [#8919 (comment)](https://github.com/notepad-plus-plus/notepad-plus-plus/issues/8919#issuecomment-701285073) doesn't solve the issue, because it is common practice to use backslash as an escaping character, when needed. So flipping the Notepad++ switch for treat backslash as an escape character for SQL solves the issue with the example I mentioned above but on the other hand it creates a new issue (in reality the same issue as before) with constructions like `SELECT * FROM DB WHERE DESCR LIKE '%Guns N\' Roses\_-\_%' ESCAPE '\'`.

**Comment by bOOT-CoDe** [comment]
I am sorry, my mistake, this  works pretty well.
