### ISSUE TITLE
Notepad++ crashes on replace-all in large files

### ISSUE THREAD

**Issue by pvdutils** [notepad-plus-plus/notepad-plus-plus#10832]
### Description of the Issue
Notepad++ crashes during  replace-all text in large file of size 50MB with 1.1 million lines.

### Steps to Reproduce the Issue

1. Searched for a text pattern
2. clicked replace all
3. it crashes

### Expected Behavior
Should replace the text pattern

### Actual Behavior
Notepad++ crashed

### Debug Information

Notepad++ v8.1.9.2   (64-bit)
Build time : Nov 21 2021 - 04:30:20
Path : D:\Program files\Notepad++\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 10 Pro (64-bit) 
OS Version : 1803
OS Build : 17134.1
Current ANSI codepage : 1252
Plugins : ComparePlugin.dll LocationNavigate.dll mimeTools.dll NewFileBrowser.dll NppAStyle.dll NppConverter.dll NppExport.dll PluginManager.dll SelectQuotedText.dll SelectToClipboard.dll

**Comment by goozak** [comment]
Just got this issue with a much smaller file (1.8 MB / 10 800 lines) with Notepad++ v8.5.8 (64-bit).
While testing around, got a quick view at an alert mentioning `LocationNavigate.dll`.
Renamed `plugins\LocationNavigate` folder (to disable this plugin) and replacement worked fine.

But now, after returning the `plugins\LocationNavigate` to its original name, the replacement works fine on the same file that crashed before, so YMMV...
