### ISSUE TITLE
Add support for LaTeX comments shortcut

### ISSUE THREAD

**Issue by jimcarst** [notepad-plus-plus/notepad-plus-plus#10836]
Currently, autocorrect, and the toggle comment shortkey are supported for TeX-files, but not for LaTeX-files.

**Comment by jimcarst** [comment]
#10837 
this would fix the comments-toggle.

**Comment by rdipardo** [comment]
@Fellow-baka

> Still doesn't work on windows with LaTeX, but works with TeX.

There are *two* bindings for the `*tex` file extension:

https://github.com/notepad-plus-plus/notepad-plus-plus/blob/caf6303896cd01c813d3954b9d8c0a0bed622c8d/PowerEditor/src/langs.model.xml#L229

https://github.com/notepad-plus-plus/notepad-plus-plus/blob/caf6303896cd01c813d3954b9d8c0a0bed622c8d/PowerEditor/src/langs.model.xml#L396

By accident of historical priory, the `L_TEX` case is handled *before* the `L_LATEX` case [when the buffer is being configured][0], so TeX is always chosen over LaTeX.

You can resolve this in the short term by simply removing a line from `%AppData%\Notepad++\langs.xml`:

~~~diff
  <!-- ... -->
- <Language name="tex" ext="tex" commentLine="%"/> 
  <!-- ... -->
~~~

It's not clear to me how the code could disambiguate files with exactly the same extension, but something like that is needed to properly support dual configurations, which the author of 567e045 naïvely overlooked.

[0]: https://github.com/notepad-plus-plus/notepad-plus-plus/blob/caf6303896cd01c813d3954b9d8c0a0bed622c8d/PowerEditor/src/ScintillaComponent/ScintillaEditView.cpp#L1670
