### ISSUE TITLE
Feature Request: Save-As Choose File Extensions

### ISSUE THREAD

**Issue by CrimsonRays** [notepad-plus-plus/notepad-plus-plus#10842]
In many programs that let you save multiple file extensions, the drop-down list in the Save-As dialogue box becomes increasingly difficult to navigate.

I would love to see an option that lets users check boxes to display or hide file extensions from the Save-As dialogue box.
I use html files for internal documentation due to its usage of tags (I can create tags for things like <story>   <items>   <armor>, etc... and easily collapse them for ease of reading.
I know I can choose "All types (*.*)" and type ".html" after my file name, but that means I have to bring up the drop-down box to change from .txt to (*.*) anyways, and it would be great to just have the few file extensions I use frequently to select from.

For example, a user that only uses a few file extensions regularly, they might choose to only have these extensions in the Save-As drop-down box: .bat, .c#, .html, and .txt

**Comment by mere-human** [comment]
Just uncheck the "Append extension"
![image](https://user-images.githubusercontent.com/9664141/146919910-7df70367-0b43-49fa-a8b1-cc9bb0d173c7.png)
Documentation: https://npp-user-manual.org/docs/preferences/#preference-toggles-in-other-dialogs

**Comment by alankilborn** [comment]
@mere-human I don't see the relevance in your response, to @CrimsonRays 's desire, but maybe I'm missing it.  Can you elaborate on what you've already said?
