### ISSUE TITLE
Extended search mode gone wrong on last update (v8.1.9.2)

### ISSUE THREAD

**Issue by Seawolf409** [notepad-plus-plus/notepad-plus-plus#10840]
### Description of the Issue
\x0a\r should find every end of line but now only finds the end of line when followed by a blank line, this means that replacing \x0a\r\x0a\r with \x0a\r no longer removes blank lines.

### Steps to Reproduce the Issue

1.  create a text file with several lines of text and a blank line.
2.  in the "Find what" box, enter \x0a\r
3. press Find Next - it only finds the blank line.

### Expected Behavior
It used to find every line end

### Actual Behavior
It only finds the blank line.

### Debug Information
Notepad++ v8.1.9.2   (64-bit)
Build time : Nov 21 2021 - 04:30:20
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : 
Admin mode : ON
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 10 Pro (64-bit) 
OS Version : 2009
OS Build : 19042.1348
Current ANSI codepage : 1252
Plugins : mimeTools.dll NppConverter.dll NppExport.dll 

I don't think you'll need any further info.  Many thanks for your excellent editor.
Best wishes, Colin Hinson  NPplusplus888@blunham.com

**Comment by dail8859** [comment]
`\x0a` is the same as `\n`

So you are searching for `\n\r` which is a very odd line ending combination. You probably mean to search for `\r\n` which is commonly used for Windows. You can also verify this by turning on line endings in your file `View > Show Symbol > Show end of line`

**Comment by Seawolf409** [comment]
Hi, 
My apologies, I got them wrong way round - brain  not in gear obviously.
Should have been \r\x0a and not \x0a\r

Sorry to have troubled you.

Best wishes,
Colin Hinson.

At 15:22 26/11/2021, you wrote:
