### ISSUE TITLE
Typo in changelog

### ISSUE THREAD

**Issue by Feriman22** [notepad-plus-plus/notepad-plus-plus#10850]
Hi,

this below Windows version doesn't exist. I found these lines in the changelog of newest version.

_Notepad++ v8.1.9.2 bug-fixes:

1.  Fix failure of erasing & saving server logs (of network drive) regression.
2.  Fix dark mode not working on **Windows 10 2H22**._

**Comment by donho** [comment]
It's too late to change the change.log which comes with the release.
OTOH, it's been fixed in the announces.
