### ISSUE TITLE
Enabling "Edit with Notepad++" context menu for OneDrive OnDemand files which are yet to download

### ISSUE THREAD

**Issue by dhruvinrsoni** [notepad-plus-plus/notepad-plus-plus#10856]
The context menu option needs to be available for "Edit with Notepad++" for the files which are yet not downloaded in the OneDrive OnDemand.

### Description of the Issue

The unavailability of the option of "Edit with Notepad++" and us not to be able to directly trigger the downloading of the content of the files via choosing the option from the context menu of explorer to "Edit with Notepad++" is very annoying. 

### Steps to Reproduce the Issue

1. Locate any file which is one the OneDrive in the Explorer. It must have empty blue cloud symbol.(which means that the contents of the files aren't downloaded yet to the local system)
2. Right click that file in order to see the option to edit with notepad++. (which you will not be able to see)
3. After selecting the option of "Always keep this on this device" the file contents will be downloaded and then only in the context menu option we will be able to see that option of "Edit with Notepad++" in the context menu. 

### Expected Behavior

Whenever we are right clicking the file there are 2 cases.
1. **Normal File** : We can see the "Edit with Notepad++" ----> **Fine**
2. **OneDrive OnDemand Not Downloaded File** : There needs to be the context menu option entry, which will trigger the explorer or OneDrive to download the file context first and then open the file in edit mode in Notepad++

### Actual Behavior

Currently when we right click a file which is in the OneDrive of the explorer and it's contents are not available then the option to "Edit with Notepad++" isn't visible. 
We need to force download first from some other workaround and once the file is available in the system then only right-click context menu shows us the option of "Edit with Notepad++"

### Debug Information

Notepad++ v8.1.9.2   (64-bit)
Build time : Nov 21 2021 - 04:30:20
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 10 Education (64-bit) 
OS Version : 2009
OS Build : 19043.1387
Current ANSI codepage : 1252
Plugins : AutoSave.dll mimeTools.dll NppConverter.dll NppExport.dll 

### Before
![image](https://user-images.githubusercontent.com/31133358/143902053-b4794ff3-11f0-48b4-8df5-cceb5c3195a2.png)

### After 
![image](https://user-images.githubusercontent.com/31133358/143902298-107bf7fa-6e5e-4e7b-b13d-f29b27d4fcbb.png)

**Comment by donho** [comment]
Tested with #13170, it works fine and solve your problem.
