### ISSUE TITLE
Style Token on partial words does not work

### ISSUE THREAD

**Issue by GittyCatPrr** [notepad-plus-plus/notepad-plus-plus#10851]
### Description of the Issue
On earlier versions, I could apply Style Tokens on partial words.  In the latest versions Style Tokens only work on a full word.
### Steps to Reproduce the Issue
1. Create a new Notepad++ Doc
2. Type the following: "Hello World"
3. Highlight the "ello" part of the word "Hello"
4. Right click and select "Style token" > "Using 1st Style"

### Expected Behavior
The partial word "ello" and all other occurrences of this phrase should be highlighted.

### Actual Behavior
Nothing is highlighted

### Debug Information
Notepad++ v8.1.9.2   (32-bit)
Build time : Nov 21 2021 - 04:27:12
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Command Line : 
Admin mode : ON
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 10 Home (64-bit) 
OS Version : 2009
OS Build : 19043.1348
Current ANSI codepage : 1252
Plugins : ComparePlugin.dll mimeTools.dll NppConverter.dll NppExport.dll XMLTools.dll

**Comment by ArkadiuszMichalski** [comment]
@GittyCatPrr Did you check `Highlighting > Style All Occurrences of Token` option in the `Preferences` dialog? Try uncheck `Match whole word` only.
