### ISSUE TITLE
put "Download 64-bit x64" on top on download page ?

### ISSUE THREAD

**Issue by btanner2** [notepad-plus-plus/notepad-plus-plus#10869]
Hi,
I love your editor, really. What is indeed a bit unlikely is the fact, “Download 32-bit x86” is on top on your download page here:

https://notepad-plus-plus.org/downloads/v8.1.9.2/

instead of “Download 64-bit x64”. I update often and frequently, and several times I just do a quick download of your new version (without reading) and I miss it to scroll down to the 64 bit download. 
So I got the 32bit version which does not work with my 64 bit plugins. 
Is there a chance to change the order an put 64 bit on top? Most download pages uses 64 bit as default.
Would be great.

If no, just close here.

Thanks brian

**Comment by CennoxX** [comment]
A 64-bit OS can run both npp versions, whereas as a 32-bit OS can only run the 32-bit npp version (although 32-bit OS should be the absolute exception by now). Another thing to consider is that there are more extensions for the 32-bit version, so this is still the preferred version by many people.

**Comment by ArkadiuszMichalski** [comment]
@donho If you don't plan to reorder then please close this issue.

**Comment by donho** [comment]
@ArkadiuszMichalski 
I'm thinking about PHP script detection of OS then put the correspondent one on the top.

**Comment by donho** [comment]
Could people test the following link:
https://notepad-plus-plus.org/downloads/v7.8.4/

Please mark your OS architecture (32 or 64) and tell me displayed on top of URL above.

**Comment by donho** [comment]
OS: Windows 10 x64
Display on top: x64 download

(I don't have x86 for testing)

**Comment by btanner2** [comment]
Hm, it still does not work for me. It seems it is not always easy to track the correct OS version as you can read here:

https://stackoverflow.com/questions/1741933/detect-64-bit-or-32-bit-windows-from-user-agent-or-javascript

I have 64 bit OS / 64 bit browser

Two short tests:

https://webkay.robinlinus.com
Result: CPU: Win32, 8 Cores -> this is wrong

https://www.cyscape.com/showbrow.aspx?bhcp=1
Result: OSBitSize 64 bits -> this is correct

That means, 32 bit is still on top of your download page for me.

**Comment by watery** [comment]
> Could people test the following link: https://notepad-plus-plus.org/downloads/v7.8.4/
> 
> Please mark your OS architecture (32 or 64) and tell me displayed on top of URL above.

I see the x64 version on top. I'm on Win 10 64 bit.

Perhaps you could also show the detected architecture on the page, just for information.

**Comment by ArkadiuszMichalski** [comment]
@donho Do you analyze UA from browser? If so, do some standard behavior when recognition fails, because now nothing is displayed. For test open Google Chrome web tools and in `Network > More condition...` change UA to other than Windows or IE10 (and belove).

**Comment by donho** [comment]
@ArkadiuszMichalski 
Yes, it's tested with UA.
For IE's fail it's not due to the UA, but due to the JS it uses I suppose.
With the following code, a browser which speak a normal js correctly will display both 32 & 64 download:

```html
<p>Release Date: 2020-01-31</p>

<p id="downloadzone"></p>

<script type="text/javascript">
var logo32 = '<p><a href="https://github.com/notepad-plus-plus/notepad-plus-plus/releases/download/v7.8.4/npp.7.8.4.Installer.exe"><img src="/downloads/images/folder_download_4.png"></a></p>';

var dlTitle32 = '<h3 id="download-32-bit-x86">Download 32-bits x86</h3>';
var dl32 = '<ul>\
<li><a href="https://github.com/notepad-plus-plus/notepad-plus-plus/releases/download/v7.8.4/npp.7.8.4.Installer.exe">Installer</a>              | <a href="https://github.com/notepad-plus-plus/notepad-plus-plus/releases/download/v7.8.4/npp.7.8.4.Installer.exe.sig">GPG Signature</a></li>\
<li><a href="https://github.com/notepad-plus-plus/notepad-plus-plus/releases/download/v7.8.4/npp.7.8.4.bin.zip">Portable (zip)</a>               | <a href="https://github.com/notepad-plus-plus/notepad-plus-plus/releases/download/v7.8.4/npp.7.8.4.bin.zip.sig">GPG Signature</a></li>\
<li><a href="https://github.com/notepad-plus-plus/notepad-plus-plus/releases/download/v7.8.4/npp.7.8.4.bin.7z">Portable (7z)</a>                 | <a href="https://github.com/notepad-plus-plus/notepad-plus-plus/releases/download/v7.8.4/npp.7.8.4.bin.7z.sig">GPG Signature</a></li>\
<li><a href="https://github.com/notepad-plus-plus/notepad-plus-plus/releases/download/v7.8.4/npp.7.8.4.bin.minimalist.7z">Mini-portable (7z)</a> | <a href="https://github.com/notepad-plus-plus/notepad-plus-plus/releases/download/v7.8.4/npp.7.8.4.bin.minimalist.7z.sig">GPG Signature</a></li>\
</ul>';

var logo64 = '<p><a href="https://github.com/notepad-plus-plus/notepad-plus-plus/releases/download/v7.8.4/npp.7.8.4.x64.Installer.exe"><img src="/downloads/images/folder_download_4.png"></a></p>';

var dlTitle64 = '<h3 id="download-64-bit-x64">Download 64-bits x64</h3>';
var dl64 = '<ul>\
<li><a href="https://github.com/notepad-plus-plus/notepad-plus-plus/releases/download/v7.8.4/npp.7.8.4.Installer.x64.exe">Installer</a>              | <a href="https://github.com/notepad-plus-plus/notepad-plus-plus/releases/download/v7.8.4/npp.7.8.4.Installer.x64.exe.sig">GPG Signature</a></li>\
<li><a href="https://github.com/notepad-plus-plus/notepad-plus-plus/releases/download/v7.8.4/npp.7.8.4.bin.x64.zip">Portable (zip)</a>               | <a href="https://github.com/notepad-plus-plus/notepad-plus-plus/releases/download/v7.8.4/npp.7.8.4.bin.x64.zip.sig">GPG Signature</a></li>\
<li><a href="https://github.com/notepad-plus-plus/notepad-plus-plus/releases/download/v7.8.4/npp.7.8.4.bin.x64.7z">Portable (7z)</a>                 | <a href="https://github.com/notepad-plus-plus/notepad-plus-plus/releases/download/v7.8.4/npp.7.8.4.bin.x64.7z.sig">GPG Signature</a></li>\
<li><a href="https://github.com/notepad-plus-plus/notepad-plus-plus/releases/download/v7.8.4/npp.7.8.4.bin.minimalist.x64.7z">Mini-portable (7z)</a> | <a href="https://github.com/notepad-plus-plus/notepad-plus-plus/releases/download/v7.8.4/npp.7.8.4.bin.minimalist.x64.7z.sig">GPG Signature</a></li>\
</ul>';

var node = document.getElementById('downloadzone');

if (navigator.userAgent.indexOf("WOW64") != -1 ||  navigator.userAgent.indexOf("Win64") != -1 )
{
    // 64-bits
    node.innerHTML = dlTitle64 + logo64 + dl64 + dlTitle32 + dl32;
}
else
{
    // 32-bits
    node.innerHTML = dlTitle32 + logo32 + dl32 + dlTitle64 + dl64s;
}
</script>
```

**Comment by ArkadiuszMichalski** [comment]
I thought you were detecting on the server side. For JS in the console it displays the error:
```
(index):412 Uncaught ReferenceError: dl64s is not defined
    at (index):412
```

So missing `dl64s` variable.

**Comment by donho** [comment]
@ArkadiuszMichalski 
Yes, you're right! It's fixed now. Could you try it again?

**Comment by ArkadiuszMichalski** [comment]
Now it is working. But it base on JS detection and if someone turns it off, they won't see download links. Without this change, it works independently to on/off JS. You can also use the `<noscript>` tag and insert the default content between it for those that do not have JS enabled.

**Comment by ArkadiuszMichalski** [comment]
>Could you indicate which one is on the top ?

I'm not testing a real 32-bit browser, just changing UA in Chrome devtools, but where it detects 64-bit it puts it at the top.

>... Now I wonder if it's better just swap their position in HTML...

If the 64-bit version is more preferred nowadays, this is probably the easiest solution.

**Comment by donho** [comment]
@CennoxX 
> A 64-bit OS can run both npp versions, whereas as a 32-bit OS can only run the 32-bit npp version (although 32-bit OS should be the absolute exception by now). Another thing to consider is that there are more extensions for the 32-bit version, so this is still the preferred version by many people.

That's the reason the 32-bits is still on the top.
But the fact that there are less & less 32-bit Windows and people who's got x64 machine want to download x64 binary (include me) make such decision is more practice for everyone.
OTOH, the promotion of x64 binary could make more plugin authors work their plugins on x64.

**Comment by donho** [comment]
https://notepad-plus-plus.org/downloads/v8.1.9.3/
and also for the future versions.
