### ISSUE TITLE
Bug: URL Encode don't converting some symbols

### ISSUE THREAD

**Issue by KidTM** [notepad-plus-plus/notepad-plus-plus#10866]
### Description of the Issue
URL Encode don't converting some symbols

### Steps to Reproduce the Issue
1. Type date in iso string format for parameter url : lastUpdateDate<date(2021-10-26T12:15:00.000+05:00)
2. Go to Plugins -> MIME Tools -> URL Encode

### Expected Behavior
Converted string
lastUpdateDate%3Cdate%282021-10-26T12%3A15%3A00.000%2B05%3A00%29

### Actual Behavior
Converted string
lastUpdateDate%3Cdate(2021-10-26T12%3A15%3A00.000+05%3A00)

### Debug Information
Notepad++ v8.1.9.2   (32-bit)
Build time : Nov 21 2021 - 04:27:12
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 10 Enterprise (64-bit) 
OS Version : 2009
OS Build : 19043.1348
Current ANSI codepage : 1251
Plugins : ComparePlugin.dll mimeTools.dll NppConverter.dll NppExport.dll NPPJSONViewer.dll

**Comment by FAIdentekit** [comment]
This still seems to be an issue.

Notepad++ v8.6 (64-bit)

**Comment by rdipardo** [comment]
There's a better place for issues like these: <https://github.com/npp-plugins/mimetools/issues>

**Comment by FAIdentekit** [comment]
> There's a better place for issues like these: https://github.com/npp-plugins/mimetools/issues

Thanks, I copied it over

**Comment by alankilborn** [comment]
> I copied it over

Now this one here is redundant if left open...
