### ISSUE TITLE
regex replace performance regression

### ISSUE THREAD

**Issue by cmeriaux** [notepad-plus-plus/notepad-plus-plus#10860]
### Description of the Issue
There is a performance regression when doing a "replace all" with regular expression option since version **8.0**.

### Steps to Reproduce the Issue

1. create a file test.txt with 8000 lines, 1.5 Mo, with 48000 match
2. open replace panel, enable regular expression option, enable wrap around option
3. Replace all  "u_(\w+)" with "u\1" 
3. It tooks 10 secondes with notepad++ v7.9.5
    It tooks 20 seconds with notepad v8.0, 
    It tooks 20 seconds with notepad v8.1.3,
    It tooks 120 seconds with notepad v8.1.4, 
    It tooks 16 seconds with notepad v8.1.5
    It tooks 90 seconds with notepad v8.1.9.2
    

### Expected Behavior
It should be as fast as possible
Notepad3 editor (https://www.rizonesoft.com/downloads/notepad3/) (based on scintilla) tooks 5 seconds 

### Actual Behavior
It's too slow since v8.0

### Debug Information
Notepad++ v8.1.9.2   (32-bit)
Build time : Nov 23 2021 - 08:27:57
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Command Line : "D:\data\download\npp.8.0.portable\test_npp.txt"
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 10 Enterprise (64-bit) 
OS Version : 2009
OS Build : 19044.1348
Current ANSI codepage : 1252
Plugins : CodeAlignmentNpp.dll Explorer.dll GitSCM.dll HexEditor.dll LightExplorer.dll mimeTools.dll NavigateTo.dll NppConverter.dll NppEditorConfig.dll NppExport.dll NppFTP.dll NppGTags.dll NPPJSONViewer.dll NppJumpList.dll NppMenuSearch.dll PythonScript.dll RegexTrainer.dll SherloXplorer.dll WindowManager.dll _CustomizeToolbar.dll

**Comment by cmeriaux** [comment]
is it related to #10398 ?

**Comment by ArkadiuszMichalski** [comment]
@cmeriaux Can you upload file for test?

**Comment by cmeriaux** [comment]
@ArkadiuszMichalski here is a test file
[test_npp.txt](https://github.com/notepad-plus-plus/notepad-plus-plus/files/7679384/test_npp.txt)

**Comment by ArkadiuszMichalski** [comment]
I don't see performance problem, try without plugin or test in [portable](https://github.com/notepad-plus-plus/notepad-plus-plus/wiki/Testing#using-the-latest-release-portable-version-of-notepad).

**Comment by chcg** [comment]
@cmeriaux Maybe you want to checkout https://github.com/notepad-plus-plus/notepad-plus-plus/pull/10912. I saw almost no change regarding performance with it, but maybe you could countercheck.
On my quite slow system it takes ~ 16 seconds as portable and ~21s for the installed version x64 8.1.9.3 .
Maybe 32bit make also difference here.

**Comment by donho** [comment]
@cmeriaux 
What makes you say it's a regression? I don't know Notepad3's regexp engine, but if it's a regression, you should compare the old version of Notepad++ and provide your result here.

**Comment by cmeriaux** [comment]
@donho 
here is my original post:

> It tooks **10** secondes with **notepad++** v7.9.5
> It tooks 20 seconds with notepad v8.0,
> It tooks 20 seconds with notepad v8.1.3,
> It tooks **120** seconds with notepad v8.1.4,
> It tooks 16 seconds with notepad v8.1.5
> It tooks **90** seconds with notepad v8.1.9.2

That's why I talked about regression.
However, after discussion on npp community website and others user, I can't reproduce anymore my issue. I think it was due to my configuration.

Let's close the issue
Cheers
