### ISSUE TITLE
Do not switch tab on file modification 

### ISSUE THREAD

**Issue by fml2** [notepad-plus-plus/notepad-plus-plus#1087]
(This is a repost of a request from the old SourceForge forum).

I have the option "File Status Auto-Detection" enabled and "Update silently" disabled -- because I want to detect file modifications in background but also want to be asked whether the file should be reloaded.

But now following happens. If I have e.g. three files open (A, B and C) and edit the file A (i.e. its tab is the cirrent tab), and the file B gets modified in background, I get a prompt about reloading of B.

There are two bad points about it:
1. I'm now editing the file A. Why am I asked about B? I should be asked about B only when I switch to it.
2. After confirming the prompt, the current tab is B, i.e. I'm thrown out of the editing context.

I like how this prompt is implemented in TextPad and would like if it were implemented the same way in NP++. I even filed an entry in the idea torrent and also provided a patch (for the 2-nd point only). But nothing happened.

Am I the only one who finds the current NP++ behaviour a bit uncomfortable?

**Comment by xylographe** [comment]
Ideally, NPP would only ask about reloading the file in the active tab.

**Comment by sanastasiou** [comment]
I agree, it simple iterates through all files and focus on them. Very annoying when you have opened multiple files. What's needed is a background update, i.e. without having to actually focus on the tab, just like e.g. Visual Studio does it.

**Comment by fml2** [comment]
> Ideally, NPP would only ask about reloading the file in the active tab.

And this only when that tab gets focus (i.e. when NP++ itself gets 
focus, i.e. becomes the active application).

**Comment by xylographe** [comment]
I was wrong! I should have written:
Ideally, NPP would only ask about reloading the file(s) in the **visible** tab(s).

**Comment by Croydon** [comment]
I'm fully supporting this, since the current behaviour annoys me on a regular basis. Yes, I want to reload the background files but I don't want to switch to it.

**Comment by HBerni** [comment]
It is really annoying working with source and tracefiles concurrently in notepad
getting interrupted by the file changed dialog all the time.

Therefore I forked the repository and incooperated support to only "highlight" the (inactive) tab when automatic file change detection had detected a file change. Only when the user activates a "highlighted" tab notepad shows the known dialog to reload the file. To "highlight" a tab I let the tab header blink.

Maybe this is also a possible workaround for #745, #1481

Would be pleased to create a pull request for this.

**Comment by fml2** [comment]
> Would be pleased to create a pull request for this.

Oh, please do! This annoys me to the hell! And I wonder why donho is adding some purely cosmetic changes when there exists an issue like this one which makes NP++ barely usable a times.

**Comment by HBerni** [comment]
If you do not want to compile yourself, 
I can send u a link to binaries (based on 6.9 - without boost) for testing.

**Comment by fml2** [comment]
Yes, I'd be glad to test this!

**Comment by HBerni** [comment]
Have a look here: https://nges.at/notepad/npp_hberni_20160310_01.7z

**Comment by fml2** [comment]
It's weird, but it does not work for me. I tried following settings for "File Status Auto-Detection":

1. Only "Enabled" is checked
2. "Enabled" and "Update silently" is checked

Opened a file X, made it inactive in NP++ (i.e. made another file the current), changed X in another program, switched back to NP++, made X current file -- and nothing happens. No prompt, no file update.

**Comment by HBerni** [comment]
You have to enable the correct options
![npp_01](https://cloud.githubusercontent.com/assets/16085227/14043911/045e3838-f28a-11e5-8cef-63b9e9b0938e.png)

**Comment by fml2** [comment]
Tried it with your settings, still no effect.

**Comment by HBerni** [comment]
Sorry, that is not working for you.
Please check, if you get a prompt, when you keep the file active. Because in this case
the behavior has not been changed.

My colleges are using it on their notebooks (Win7) and we also use this version on our
development servers (Win 2008R2) as well for more than 2 weeks now successfully.

To crosscheck I downloaded my archive to my private notebook (Win10) at home,
moved the 3 original files from npp install directory away and saved files from
archive into npp directory. And it is working as intended.

Please check, that you are using the correct binaries and that these
are loaded and executed.

```
notepad++.exe  2179072 Bytes 2016-03-10 09:49 CET
NppShell.dll    260608 Bytes 2016-03-01 16:54 CET
SciLexer.dll    844288 Bytes 2016-03-01 17:47 CET
```

Bernhard

**Comment by fml2** [comment]
I double checked, and still no success. Could it be bacause I still use WIn XP SP3?

**Comment by jnm2** [comment]
+1. This is my biggest irritation with Notepad++.

The main scenario that I want to see fixed is when Notepad++ is not focused and I click a specific tab that I want to switch to, but when I click to switch to a different tab, the window gets focus and the initially focused tab (whose file changed) asks if I want to reload. Then no matter what I answer, the initial tab stays focused instead of the tab I clicked on.

I love the concept of still checking all tabs for changes but only flashing a highlight rather than switching tabs. Please add to that allowing switching tabs without interruption when the window is not focused even when the current tab has changes.

**Comment by HBerni** [comment]
Good point, I guess I could address this, but have to check first.

Basically we usually have source files active and trace/log files inactive and it was really annoying that npp switched to the trace/log files all the time, which by there nature are updated very often. Therefore it was by intention to keep the original behavior unchanged for the active tab.
I will discuss your suggestion with my working colleges first.

fml2 didn't get my version working at all on win xp, did you test my binaries?
And if, what os are u using?

**Comment by jnm2** [comment]
To be clear, I want the active tab to show me the message when the window
gets focus except for those times when the window gets focus by me clicking
on a different tab. Then that different tab should be the one to ask (if it
has changed), and the initial tab should just flash until I click it.

**Comment by jnm2** [comment]
Also, when I click the tab's X button and that happens to focus the window, I do not want to be interrupted by a message box asking if I want to reload that tab.

**Comment by HBerni** [comment]
@fml2 : Sorry, I am a little bit busy at the moment and I did not check at XP, yet.

I changed implementation to not store the highlight information in the tab (which might need a newer version of ComCtl32.dll than your xp is using), instead I store the information in the corresponding file buffer object. Additionally I removed an introduced flickering of the tab headers.

I uploaded a new binary https://nges.at/notepad/npp_hberni_20160407_01.7z

**Comment by fml2** [comment]
Hello Bernhard,

I really appreciate your efforts! Thank you!

I immediately installed a fresh copy of NP++ (6.9.1) and then overwrote two files (notepad++.exe, SciLexer.dll) with the ones from your archive (I didn't copy NppShell.dll since it is not present in the official .7z distribution of NP++).

I'm sorry to say that it still does not work.

Could you maybe provide a version that would write some data to some log file which would indicate

1. Whether the correct mode is really active (and not just the check box checked)
2. Whether the fact that the file has changed has been detected. It might be that the file change has been detected but the the GUI does nothing.

Maybe we could track down the problem this way.

Thank you again for your efforts!

**Comment by germanTHX** [comment]
@HBerni Nice one!
Finally the log files aren't driving me crazy anymore. 

Just used your files on a 7.3.5 NP++ and it works like a charm. 
Even though i would rather have just the yellow highlighting. The 'blinking' effect is a bit too much again and is just distracting after a while. Therefore you than have to open the file anyway so the blinking stops. 

But anyway, thanks for your work!

**Comment by jnm2** [comment]
Yes, this is still a big day-to-day irritation.

**Comment by HBerni** [comment]
@germanTHX I will consider removing the blinking, or make it optional via the settings dialog - but it will take some time, since I am really busy at the moment. Anyway thanks for feedback, I didn't expect that my code will still work on recent versions. Good to know.

@jnm2 I do not expect an official solution, since notepad++ includes "Log Monitoring" since 6.9.2. I didn't try that feature yet, so I am unable to say, which approach is more suitable. But I think that my approach suits me more when working with source and trace files mixed in one notepad++ window.

**Comment by jnm2** [comment]
@HBerni Surely that does not cover the same scenario, because log monitoring doesn't expect you to be modifying the log in Notepad++.

**Comment by Rajas-Git** [comment]
In an ideal world, Notepad++ should ask for reloading the file only when user switches to that tab. I am ## **very annoyed** by the behavior that when I open Notepad++ using "Edit in Notepad++" context menu, if blasted with a series for prompts to confirm if I want to reload the file and it does NOT takes me to the file that I opened.

**Comment by Nao** [comment]
Thanks HBerni for your fixed files! Was looking for a solution to this. I backed up & replaced my NPP 7.5.1 with these files and it works like a charm. It would probably be best if you updated your files to the latest NPP though, but I'm not gonna complain :)

**Comment by micktion** [comment]
It looks great.  There are like a million complaints about this functionality.  I'm just wondering why this hasn't been incorporated into a release yet?

**Comment by PFight** [comment]
@HBerni thask very much, using your version now! 
Please, can you find some time to make setting - enable/disable blinking? Just highlight with yellow is enough.

**Comment by HBerni** [comment]
I uploaded a new binary to https://nges.at/notepad/npp_hberni_20180320_01.7z

It's a fast and almost untested port of my patches to the official 7.5.6 npp.
By the way I removed the blinking, since it was more annoying than useful.

**Comment by HBerni** [comment]
@micktion I can't tell you. I would be pleased to see them in the official build as well.

**Comment by fml2** [comment]
I'm curious whether @donho is aware of this (and the similar) ticket. Some much less important changes (IMO of course) get committed (like auto typing cool wisdoms) but this issue (which directly affects productivity) does not get attention.

**Comment by Cife69** [comment]
It would be very useful to get this feature in the official version. This strange behaviour led me to make a series of mistakes during last years. Usually I have to edit several files with the same name, these files are stored in different network folders and can be modified at the same time by different users. So sometimes it happens that I modify a wrong file due to automatic file tab switch after reload. 
I would like to thank @donho for his great job.

**Comment by Cerno-b** [comment]
Glad to see that this issue is basically resolved. Is there a way to increase visibility to get it into a release? This is really annoying.

**Comment by HBerni** [comment]
I am sorry to say, that I am not aware how to increase visibility.
I would be pleased if @donho could contribute his opinion and his expertise on how we could manage to make it into an official release.

**Comment by donho** [comment]
@Amitkad 
Did you even try the recent releases?

**Comment by Amitkad** [comment]
I followed the commits after writing this comment and realized that i was way after the latest release. Not sure why because auto updates are on..
Sorry for disturbing. Works fine!
