### ISSUE TITLE
C# reserved words 'nameof' is not marked as reserved

### ISSUE THREAD

**Issue by digocesar** [notepad-plus-plus/notepad-plus-plus#10870]
I'm using Notepad++ v.8.1.9.2 (32-bit) and the reserved words `when` and `nameof` from C# is not marked as reserved (as blue, in my case).
Pull requests #9667 and #8633 implement these reserved words. But it looks like they haven't been included in the most recent releases yet.

**Comment by ArkadiuszMichalski** [comment]
@digocesar Looks like you have old `langs.xml` file. Try remove it (location is depending on your settings, details https://npp-user-manual.org/docs/config-files/).

**Comment by digocesar** [comment]
I did uninstall and install again. Then the `when` keyword started to be marked in blue.
But the `nameof` doesn't. It is showing in the autocomplete option. But is not marked in blue.
I think it's because `langs.model.xml` should have been changed too, right?
If so, I can change it and request the pull request.

**Comment by ArkadiuszMichalski** [comment]
https://github.com/notepad-plus-plus/notepad-plus-plus/issues/10870
