### ISSUE TITLE
Selection doesn't move caret

### ISSUE THREAD

**Issue by WrongBit** [notepad-plus-plus/notepad-plus-plus#10881]
When you press [Shift] and arrow right, symbol under caret should become selected and caret move right. But caret still stays on the same place! (caret is set to "box") It's confusing and wrong behaviour.

**Comment by CennoxX** [comment]
What do you mean by

> caret` is set to "box"

?

**Comment by WrongBit** [comment]
@CennoxX : "block" I meant. :) Preferences->Editing->Caret Settings->Width. There.

**Comment by alankilborn** [comment]
This is to be fixed in Notepad++ 8.4.5 with the addition of a "Block After" choice for caret size in the preferences.
Recommend CLOSURE of this item.

**Comment by ArkadiuszMichalski** [comment]
Fixed by https://github.com/notepad-plus-plus/notepad-plus-plus/commit/70660eb608eea7a9c85a4bfb08761ffd6bfbc887.
