### ISSUE TITLE
[feature request] Distinguish between "indent width" and "tab width"

### ISSUE THREAD

**Issue by jwt27** [notepad-plus-plus/notepad-plus-plus#10882]
### Description of the Issue
Currently in Notepad++, there is only a single option for both tab and indent
width.  They should be considered separate concepts.

Each language should have separate options to set the indent size (the number of
spaces inserted when you press TAB), and the width of an ASCII `TAB` character.
The "replace by spaces" option is then more accurately named "use only spaces".

GNU indentation style is a good example, and this is currently very frustrating
to use in NP++.  Pressing TAB should indent by 2 spaces, and each sequence of 8
spaces should be replaced by a single `TAB` character.  So here, "indent width"
is 2, and "tab width" is 8.

When tab and indent size are both set to the same value, and "use only spaces"
is then unchecked, pressing TAB will just insert a single `TAB` character.

**Comment by donho** [comment]
https://github.com/notepad-plus-plus/notepad-plus-plus/pull/12333#issuecomment-1430684990
