### ISSUE TITLE
[MinGW] Try reading Windows environment variables correct also for unix-like shell.

### ISSUE THREAD

**Issue by ArkadiuszMichalski** [notepad-plus-plus/notepad-plus-plus#10885]
In [makefile ](https://github.com/notepad-plus-plus/notepad-plus-plus/blob/master/PowerEditor/gcc/makefile) using `$(windir)` will not work on Windows when we directly use Bash or sh. This shell on Windows automatically convert some system environment variables to uppercase and we have to check with uppercase. This causes creation of `SensApi.dll` may fail when we run makefile through Bash or sh. Universal checking such variables for cmd or Bash/sh under Windows can be `$(or $(windir),$(WINDIR))`.

**Comment by donho** [comment]
I can build under Git Bash (MIGW64) without any modification.
Which shell do you use?

**Comment by ArkadiuszMichalski** [comment]
But did you test both build, also 32-bit? For 32-bit it makes a difference because it has to create a SensApi.dll` file and read `windir`.
