### ISSUE TITLE
dspellcheck plugin is removed at each new install..

### ISSUE THREAD

**Issue by cpasmoi** [notepad-plus-plus/notepad-plus-plus#1089]
there was a bug that have been solved many months ago with this plugin, but it's still removed at each new install :/ 

in fact the "auto removal" of the plugin have been added AFTER that the plugin have been fixed :D

thx

**Comment by justanotheranonymoususer** [comment]
I agree. That's a great plugin, but it gets disabled every time.

**Comment by donho** [comment]
DSpellCheck plugin makes Notepad++ crash in some environment, so it will be removed by installer.
Rename your DSpellCheck.dll to DSpellCheck2.dll in order to avoid removal on each installation.
