### ISSUE TITLE
Fix Microsoft's cloude Onedrive

### ISSUE THREAD

**Issue by pozoun** [notepad-plus-plus/notepad-plus-plus#109]
Microsoft moved UserFolder from HKCU\SOFTWARE\Microsoft\SkyDrive to HKCU\SOFTWARE\Microsoft\OneDrive

I'm not familiar with Git so maybe I didnt make all that needed nor I should do - for instance I cannot add my branch with my changes.
 I strongly propose to add to Parameters.cpp, line 996 this:
 if (res != ERROR_SUCCESS)
 {
 res = ::RegOpenKeyEx(HKEY_CURRENT_USER, TEXT("SOFTWARE\Microsoft\OneDrive"), 0, KEY_READ, &hOneDriveKey);
 }

**Comment by pozoun** [comment]
I propose to add to Parameters.cpp, line 996 this:
if (res != ERROR_SUCCESS)
{
	res = ::RegOpenKeyEx(HKEY_CURRENT_USER, TEXT("SOFTWARE\\Microsoft\\OneDrive"), 0, KEY_READ, &hOneDriveKey);
}

**Comment by MAPJe71** [comment]
Might be best to check in both hives i.e. SkyDrive and OneDrive for the MS Cloud.

**Comment by pozoun** [comment]
Definitely. I proposed it - after some OneDrive update the former hive (SkyDrive) remains in registry, Microsoft removed UserFolder from it and created new OneDrive key with all values that probaly were in SkyDrive including UserFolder. I would do this:
1. Test if SkyDrive\UserFolder exists and holds valid value
2. If yes then to také it
3. If doesn't then do the same with OneDrive\UserFolder
Could it be correct?

But I have another problem - I have never worked with git nor github - I don't know howto checkout file from repository and commit/checkin my proposed changes to be done code review by architect? Could someone shortly advise me pls? :)  .

**Comment by xylographe** [comment]
I think, the order would be `OneDrive\UserFolder` (new location first), then `SkyDrive\UserFolder` (fall back location).

[Create a fork of `donho/notepad-plus-plus`.
 Clone your fork.
 Create new branch.
 Change & commit.
 Push branch to your fork.
 Create pull request.](https://help.github.com/articles/fork-a-repo/)

**Comment by pozoun** [comment]
@xylographe - Thanks for all - it'sgreat - your swap is better - I do this. 
When I'm free I'll do all according to your cooking book :+1: .  
:) Cheers ....

**Comment by milipili** [comment]
See 5e240147c51b6c27f1accbcfa191d9ddc4967e68

**Comment by pozoun** [comment]
Ok. This has to be closed.
