### ISSUE TITLE
Broken RSS feed on website

### ISSUE THREAD

**Issue by pandronic** [notepad-plus-plus/notepad-plus-plus#10900]
I don't know if it's the right place to report it, but the feed (https://notepad-plus-plus.org/index.xml) is broken for some time. See attached screenshot.

![image](https://user-images.githubusercontent.com/315108/145374881-e25023bc-7017-4ada-901c-d514e7b94e3c.png)

**Comment by pandronic** [comment]
It's not such a big inconvenience for me since the updates are not that frequent, but it's clearly a bug - there's a fragment of Javascript pertaining to cookie consent in the **description** field.

**Comment by donho** [comment]
@pandronic 
There are 2 added page on each release, news and download.
For download page, it's not necessary to provide description.
Is the current RSS OK for you?
https://notepad-plus-plus.org/index.xml
