### ISSUE TITLE
comparing two files in dark mode makes differences unreadable

### ISSUE THREAD

**Issue by shocked-gamer** [notepad-plus-plus/notepad-plus-plus#10905]
### Description of the Issue
when dark mode is enabled in the app, the compare plugin still uses the default colors for the white mode. this makes reading the differences very hard to read. 

### Steps to Reproduce the Issue

1. go to settings, preferences and enable dark mode
2. open to text files and press ctrl+alt+c to start the compare 
3. see the highlighted results that are hard to read

### Expected Behavior
when enabling dark mode the plugin should auto change it's highlight colors to darker tones or permanently change the colors to darker tones no matter if the user selected white or dark mode.

### Debug Information
Notepad++ v8.1.9.3   (64-bit)
Build time : Dec  6 2021 - 19:21:37
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 10 Home (64-bit) 
OS Version : 2009
OS Build : 19044.1348
Current ANSI codepage : 1252
Plugins : ComparePlugin.dll DSpellCheck.dll mimeTools.dll NppConverter.dll NppExport.dll 

![Capture](https://user-images.githubusercontent.com/33640073/145673041-68117587-cba0-49a1-b147-231db571679d.PNG)
![Capture2](https://user-images.githubusercontent.com/33640073/145673043-184254a6-ce69-432a-9f42-35fe2ecea2a4.PNG)

**Comment by ArkadiuszMichalski** [comment]
This is Compare plugin problem, you can repot it directly to this [plugin repo](https://github.com/pnedev/compare-plugin).
