### ISSUE TITLE
User Defined Language

### ISSUE THREAD

**Issue by CNCHoward** [notepad-plus-plus/notepad-plus-plus#10902]
### Description of the Issue
we have a user defined language that we have made for out CNC programs.  In order to default to that language when opened you have to have a file extension.  Our CNC programs do not have a file extension "(value not set)" .  is there a way to accomplish this 

### Expected Behavior
when a file without a file extension is opened "chosen user defined language" would be used

### Actual Behavior
user defined language is not chosen.

**Comment by CNCHoward** [comment]
@donho?

**Comment by donho** [comment]
![image](https://user-images.githubusercontent.com/90293/146028582-e954b6c6-d6ee-464c-beaa-d46326ba5fb0.png)
