### ISSUE TITLE
Auto-complete when pressing enter

### ISSUE THREAD

**Issue by cjldadios** [notepad-plus-plus/notepad-plus-plus#10915]
I don't know if you see the image that I pasted.

When typing and a suggested word appears, eg. the word Summary, I've already typed and fully spelled out the word Summary and did not use the suggested word even though that's correct.

Having completely spelled the word Summary, what I want to do next is to make a new line by pressing enter--because I've already typed word.

What happens, instead, is that I need to press Enter twice, because the first Enter press just confirms the Suggested word even though I've already spelled it out.

What I want to happen is that the Enter key should already be a new line because the suggestion has already been spelled out.

This could be annoying for Python developers because there's no semi-colon there.

Thanks.

![image](https://user-images.githubusercontent.com/16794866/146125206-e2da37ca-7a8e-41da-ba5d-26be3bcec691.png)
![image](https://user-images.githubusercontent.com/16794866/146125285-f3942150-cae1-41a0-beb8-a29350082bbe.png)
![image](https://user-images.githubusercontent.com/16794866/146125328-04b8df8d-17d9-4f3c-bd40-01a4d572dd2c.png)

**Comment by ArkadiuszMichalski** [comment]
Duplicate fo https://github.com/notepad-plus-plus/notepad-plus-plus/issues/8389 and https://github.com/notepad-plus-plus/notepad-plus-plus/issues/4799.

**Comment by Jens-G** [comment]
> [Auto-completion currently use both ENTER and TAB to insert the select…](https://github.com/chcg/notepad-plus-plus/commit/38cdc769bcb877ac3465eeac06a7ccb332248802) …

Not confirmed. That drives me crazy for a while. now and it still does NOT work in 8.3.2. Can we please fix that for good?
