### ISSUE TITLE
TypeScript Not Detected / Displayed In Settings->Style Configurator

### ISSUE THREAD

**Issue by Dulux-Oz** [notepad-plus-plus/notepad-plus-plus#10911]
### Description of the Issue

In Notepad++ v8.1.9.3 (on Windows 10 - & presumably previous versions on Notepad++/Windows) the TypeScript language:
    1) Is not detected automatically from a .ts file extension - ie when opening a .ts file Notepad++ does not automatically set the language to TypeScript.
    2) Does not appear in the Language: list on the Settings->Style Configurator Window.

### Steps to Reproduce the Issue
    1) Double-Click on a file with a .ts extension => TypeScript language is not set.
    2) Go to Settings->Style Configurator
    3) Scroll through the Language: list => TypeScript is not in the list.

### Expected Behavior
    1) When opening a file with a .ts extension expected behaviour is for the TypeScript language to be automatically set.
    2) Expect to set TypeScript listed in the Language: list on the Settings->Style Configurator Window.

### Debug Information
Notepad++ v8.1.9.3   (64-bit)
Build time : Dec  6 2021 - 19:21:37
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : "C:\temp\myfile.ts"
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 10 Pro (64-bit) 
OS Version : 2009
OS Build : 19042.1348
Current ANSI codepage : 1252
Plugins : DSpellCheck.dll mimeTools.dll NppConverter.dll NppExport.dll

**Comment by ArkadiuszMichalski** [comment]
Try with [portable version](https://github.com/notepad-plus-plus/notepad-plus-plus/wiki/Testing#using-the-latest-release-portable-version-of-notepad) to eliminate configuration problem.

**Comment by Dulux-Oz** [comment]
My bad - sorry about that.

I ended up uninstalling NP and reinstalling - issue no-longer exists.
