### ISSUE TITLE
ALT Key Incorrectly Passed To Notepad++ When ALT+Tabbing Causing Menu To Take Focus

### ISSUE THREAD

**Issue by atom0s** [notepad-plus-plus/notepad-plus-plus#10922]
### Description of the Issue

When using ALT+Tab to switch between applications on Windows, Notepad++ is now causing the ALT key to stay 'down' when tabbing back to it. This causes key presses to then react as if you're pressing ALT+(insert key here) to do a menu action. I now have to press escape every time first before I try to start typing again otherwise I'll do some random menu action by accident.

This seems to have just started recently in the last month or so.

This is on a brand new, fully updated, install of Windows 10 Pro and latest Notepad++.

**Windows Version:** Windows 10 21H2 (Nov. 2021 update.)
**Notepad++ Version:** 8.1.9.3 (x32)

### Steps to Reproduce the Issue

1. Open Notepad++
2. Create a new empty document and type some words into it so that the cursor is focused to the text area.
3. Hold `ALT` and press `Tab` to move away from the Notepad++ application window and have it lose focus.
4. Do something in another app showing it properly got cursor focus.
5. Hold `ALT` and press `Tab` to move back to the Notepad++ application window.

At this point, Notepad++ will show the menu having focus instead of the text area, acting as if ALT was pressed again after the window regained focus, or is being held down.

### Expected Behavior

When ALT+Tabbing back to Notepad++, the text area that had focus last should regain cursor focus. This was the behavior before but is now broken for me.

### Actual Behavior

Notepad++'s menu system is given focus when ALT+Tabbing back to Notepad++ instead of the text area.

### Debug Information

Notepad++ v8.1.9.3   (32-bit)
Build time : Dec  6 2021 - 19:16:45
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 10 Enterprise (64-bit) 
OS Version : 2009
OS Build : 19044.1348
Current ANSI codepage : 1252
Plugins : mimeTools.dll NppConverter.dll NppExport.dll

**Comment by alankilborn** [comment]
Fixed recently; See here:  https://github.com/notepad-plus-plus/notepad-plus-plus/commit/ee884f87bbb66d1431f0d530d0cd25bb7cde6b35#commitcomment-62032223

**Comment by egvijayanand** [comment]
Observed this issue in Windows 11 and not only on Notepad++ but almost all applications while using Alt+Tab to switch context.

After landing in the intended destination, the Alt key is still active over there, and pressing any key after that activates the corresponding shortcut, for example pressing the F key opens the File menu as Alt+F is mapped to that.

Reported this in the Windows Feedback portal as well: https://aka.ms/AAfcbnn

**Comment by donho** [comment]
It's not Notepad++ issue but the system one.

**Comment by atom0s** [comment]
I'm not sure how this is a system issue when this was not a problem until the linked commit above happened..? If I roll back my Notepad++ version, it is fixed. No other program on my system has this problem, just Notepad++.

I am using Windows 10, not 11.

**Comment by donho** [comment]
@atom0s 
Could you try the latest version 8.2 ?
https://notepad-plus-plus.org/news/v82-released/
