### ISSUE TITLE
[FR] Support editing of files greater than 2GB.

### ISSUE THREAD

**Issue by Stan-Green** [notepad-plus-plus/notepad-plus-plus#10921]
The software currently cannot edit very large files (i.e. > 2GB). This makes the tool unusable for tasks that included large files (e.g. Data Science). Please enhance the software to handle large files.

**Comment by klausph** [comment]
Hi, 
I have found a solution: vedit (as 64bit!)
https://www.vedit.com/
attention: its exepensiv! a normal 64bit license costs about $229.
You can this software. I think, this is very certain.

and my old loveliest editor BRIEF (I has used it for 20-30years), is also able to open files. a small test with a mrk-file (ascii) 35GB. brief its a little bit slow. to go on the end of this edited file, it costs more than a half of one hour....

another idea: maybe its not a real good idea to use an editor for very very big files....
mostly I use a "search&replace"-tool. something like perl(of course 64bit)....
my machine: 32 logical processors, 16 kernels and 256GB ram.... ;-)

Good luck. Yours, Klaus

**Comment by chcg** [comment]
@Stan-Green Which version of N++ do you use? And is it the 32 or 64 bit Version.

**Comment by Stan-Green** [comment]
@chcg Notepad++ v8.1.9.3 (64bit). I have a 3.6Gb file that the app cannot open. It says: File is too big to be opened by Notepad++

**Comment by Stan-Green** [comment]
@klausph I would say $229 is way too high for a text editor. Yes, I could find a one-off workaround for some things, but I would rather have a general-purpose editor. Using an editor for large files, rather than command-line tools (e.g. Perl) is a matter of opinion.  I like Notepad++ so this is why I made the feature request.

**Comment by xomx** [comment]
1) There is hardcoded INT_MAX (2GB) file limit in the FileManager::loadFileData() method, I think it is a relic from the 32-bit only era:

```
// As a 32bit application, we cannot allocate 2 buffer of more than INT_MAX size (it takes the whole address space)
if (bufferSizeRequested > INT_MAX)
{
	NativeLangSpeaker *pNativeSpeaker = (NppParameters::getInstance()).getNativeLangSpeaker();
	pNativeSpeaker->messageBox("FileTooBigToOpen",
									NULL,
									TEXT("File is too big to be opened by Notepad++"),
										TEXT("File size problem"),
									MB_OK|MB_APPLMODAL);

	fclose(fp);
	return false;
}
```
This can be easily patched e.g. in this way:
```
#ifdef _M_IX86
// As a 32bit application, we cannot allocate 2 buffer of more than INT_MAX size (it takes the whole address space)
if (bufferSizeRequested > INT_MAX)
{
	NativeLangSpeaker *pNativeSpeaker = (NppParameters::getInstance()).getNativeLangSpeaker();
	pNativeSpeaker->messageBox("FileTooBigToOpen",
									NULL,
									TEXT("File is too big to be opened by Notepad++"),
										TEXT("File size problem"),
									MB_OK|MB_APPLMODAL);

	fclose(fp);
	return false;
}
#endif // #ifdef _M_IX86
```


2) But I do not think that Notepad++ (and the underlying Scintilla) is appropriate for the handling of such large files for these reasons:
- the N++ loads the whole file to the memory, there is no filemapping or similar technique, how to handle only relevant chunks of the file data (so for a 3GB file you will really need min 3GB of contiguous memory)
- an there is the underlying Scintilla, which needs one style byte for every data byte, so for a 3GB file it will in fact takes around 6GB+ in memory (the plus extra memory is for line positions and other data...)
- and even if you have such memory available, the N++ will then slow down to the point, where it will not be usable at all

IMO: N++ (and Scintilla) is simply designed for source code editing and not for the handling of 2GB+ files.

**Comment by xomx** [comment]
@donho 
What do you think about my patch above?

I tried such patch long time ago and if I remember correctly, I tested that with a ~5GB text-file and it opened in N++ ok, but it was slow as hell and I had to terminate N++ sometimes, because of it circled somewhere deep in the Scintilla calls. But there are other people with fast workstations, so maybe they can take advantage of that patch without problems.

I am currently only on thin clients and laptops without MSVS, so I cannot do testing or a possible PR, sorry.

**Comment by Stan-Green** [comment]
@xomx Thanks for looking into this.

I understand the limits of an in-memory file. My current PC is what I would call a low-end. I only have 32GB of memory with an i7 running 3.26GHz.  For my next build, I am targeting 256GB of memory and an i9 or Maybe Threadripper. So, memory usage is somewhat relative. Opening a 10GB file should not be an issue with my system resources. If you are working with files this large, you likely have the hardware to support it.

I do like the idea of using just one editor for all my editing regardless of whether I am working on source code or data. I also have not seen an editor I like and is free that can handle large files. I have played around with EmEditor but the price for the full version is way higher than I am willing to pay.

**Comment by chcg** [comment]
@Stan-Green Maybe you want to try out the plugin https://github.com/superolmo/BigFiles which reads big files in customizable chunks and might have an acceptable performance also in this case.

**Comment by xomx** [comment]
@Stan-Green 
If Don approves such change, I am willing to try a PR for this next week.

There should be also an additional precaution check to prevent an inexperienced user opening such big files accidentally (this can easily lead to unresponsive system, because of the OS virtual memory mechanism...). Now I have in mind two possibilities:

1) Checking the available physical memory on user PC, then use logic like:
`if ((bufferSizeRequested * 2) > (PC_MEM_DETECTED - MIN_SYSTEM_MEM_REQUIRED))`
Nowadays the x64 Windows RAM min requirement is 4GB, whereof the system itself needs approx. 2GB for reasonable work, so it can be PC_MEM_DETECTED - 2GB.

2) Let the users decide for themselves - adding a new N++ cmdline param like `-largeFiles`, so then this check will looks like:
`if ((bufferSizeRequested > INT_MAX) && ! _bLargeFiles)`
I prefer to use this second way, otherwise powerusers (for which it is intended anyway) can hit e.g. a similar problem as here:
https://sourceforge.net/p/sevenzip/discussion/45797/thread/4bc9804cf9/
https://sourceforge.net/p/sevenzip/discussion/45797/thread/ba29828ce0/#3c6c
https://sourceforge.net/p/sevenzip/discussion/45797/thread/edcb38bbab/#2b14

**Comment by Stan-Green** [comment]
@chcg Thanks for the information. The plugin looks like it is for reading only. The point of an editor is to make changes. I don't think BigFIles will support my use case.

**Comment by Stan-Green** [comment]
@xomx A command-line param would be OK. A setting in the tool would be better. This is because I frequently use the Windows Explorer "Edit with Notepad++" so there is no place to put the command line. Hacking the registry might be an option in this case.

**Comment by xomx** [comment]
@Stan-Green 
> A setting in the tool would be better
As this is relevant only for small audience and it is simultaneously dangerous to play with for inexperienced users, I do not think that it is a good idea. But ok, I can imagine this implemented e.g. as a numeric editbox in Preferences, where 0 means 'no limit'.

**Comment by donho** [comment]
@xomx 
> But I do not think that Notepad++ (and the underlying Scintilla) is appropriate for the handling of such large files for these reasons:
> ...

You did a very good summary for the limitation of Scintilla.

> Maybe you want to try out the plugin https://github.com/superolmo/BigFiles which reads big files in customizable chunks and might have an acceptable performance also in this case.

As @chcg suggested, BigFiles plugin could be a solution, though it's not convenient to use.

Otherwise, `2 minute 39 seconds` is the result of my test on a gaming laptop purchased recently, to open a 2.04 GB file with Notepad++ x64, **with Word Wrap option OFF**. 
Same file with Word Wrap option ON, the test went through over10 minutes, and I kill the process without the load being done.

> What do you think about my patch above?

We can do somethings about the x64 binary, but I am not for removing this limit completely without any condition.
02:39 is a huge amount of time to open a file, so user should be aware of such consequence - not only a warning to user that opening 2GB file will take time, but also a control file `allowHugeFileOpenning.xml` which enables to open huge file should be added by user. Also, before opening the huge file, Word Wrap option should be turned OFF.

What do you think @xomx? Do you want to do this feature?

**Comment by alankilborn** [comment]
>a warning to user that opening 2GB file will take time

So...user attempts to open a large file, and the first thing it does is popup with a warning box that user has to answer yes/no to?  I would like to see that popup's appearance (appear/not-appear) governed by a _Preference_ setting.

>but also a control file allowHugeFilesOpening.xml which enables to open huge files should be added by user.

This seems like a kludge.  Why not just _Preference_ options; suggest:
(checkbox) Allow opening of huge files (default: checked)
(checkbox) Issue popup warning when opening of huge file is attempted (default: unchecked)

Thus the default is no change to existing behavior.

>before opening the huge file, Word Wrap option should be turned OFF by Notepad++.

I like this.

**Comment by xomx** [comment]
@donho 


> a control file `allowHugeFilesOpening.xml` which enables to open huge files

I like that, it is better than my `-largeFiles` param suggested. And it also solves the @Stan-Green "Edit with Notepad++" case.


> Word Wrap option should be turned OFF

I agree.


> a warning to user that opening 2GB file will take time

I am not a friend of that. If someone is able to use the allowHugeFilesOpening.xml way, we should not annoy a poweruser by such nag.

> Do you want to do this feature?

Ok, but I can start next week. So if someone else want to do this, I have no objection.




@alankilborn 
I agree with your first note about the warning messagebox, but I do not want to add anything in the Preferences.

Could it be this way instead?
- the allowHugeFilesOpening.xml file will not be included in the N++ install packages
- we adjust a little bit the original filesize check:  `if (bufferSizeRequested > INT_MAX && ! _bAllowHugeFilesOpening)`
- we extend current existing 'FileTooBigToOpen' messagebox in that check to: TEXT("File is too big to be opened by Notepad++.\n\nTo allow such operation, one has to create first an empty allowHugeFilesOpening.xml file in the Notepad++ directory (warning: doing so could temporarily or permanently affect the Notepad++ responsiveness!)")
- if user then creates and uses the allowHugeFilesOpening.xml file, there will not be any other message at all

Remember, there are also really powerful workstations available (I have one AMD EPYC machine with huge RAM at my workplace, so I can test this next week), where such operations can be ok.

**Comment by donho** [comment]
@alankilborn 
> So...user attempts to open a large file, and the first thing it does is popup with a warning box that user has to answer yes/no to? I would like to see that popup's appearance (appear/not-appear) governed by a Preference setting.

If the file need 2 - 3 minutes to be opened, users don't mind to click on OK. This prevents users from opening wrong files by accident.

> This seems like a kludge. Why not just Preference options; suggest:
(checkbox) Allow opening of huge files (default: checked)
(checkbox) Issue popup warning when opening of huge file is attempted (default: unchecked)

The goal of this "kludge" (in your word) is keep the current behaviour completely, and not encourage people to open the huge files - Scintilla is for source code not for huge text file, but average users have no idea about it. And when they wait 3 minutes for loading a file, they will blame to Notepad++. So it's not a "feature" but a way to workaround for removing the restriction. Hence it's better an activation file added by users conscientiously than a simple option in preferences, IMO.

**Comment by donho** [comment]
@xomx 
> I am not a friend of that. If someone is able to use the allowHugeFilesOpening.xml way, we should not annoy a poweruser by such nag.

As I said above, If the file need 2-3 minutes to be opened, users don't mind to click on OK. This prevents users from opening wrong files by accident.

> Remember, there are also really powerful workstations available (I have one AMD EPYC machine with huge RAM at my workplace, so I can test this next week), where such operations can be ok.

I care about more average users who don't have super machine, and it (removing the restriction) is not a "feature" to them definitely.

> Ok, but I can start next week. So if someone else want to do this, I have no objection.

No problem. I may implement it myself - if I didn't find other priority.

**Comment by chcg** [comment]
I think we need to check if really all integer variables involved within N++ are ready to handle sizes greater than INT_MAX as lately seen with Exchange year 2022 bug.
Would be also interesting if all the plugins are prepared for that step.

**Comment by xomx** [comment]
@donho
> If the file need 2-3 minutes to be opened, users don't mind to click on OK. This prevents users from opening wrong files by accident.

Ok. I thought about this - maybe it will be better to add a common progress-dlg feature (it could have an abort possibility too) for all potentially lengthy operations to N++. From this can benefit anyone, who tries e.g. opening a 300MB file with the WordWrap accidentally switched ON or similar.

I will create a separate FR issue for that, if you like the idea.
Implementation of this feature is simple, if we do not choose something fancy. E.g. I have this in my SW for pics:
![progressdlg](https://user-images.githubusercontent.com/13075183/149128860-6771ca1a-d908-4802-b7e5-d1e5abd00325.png)

**Comment by alankilborn** [comment]
I script a lot of solutions.  Sometimes I open files via script.  But my scripts would have no way to know that a popup asking if it is OK to open a detected large file.  I guess what I'm asking is that when a change is implemented, will existing functionality be preserved if the .xml file is not present?  I would think so, but I just want to make sure...

**Comment by xomx** [comment]
@alankilborn 
Simple answer is YES.

But even now there is the 'FileTooBigToOpen' popup, when you try to open a 2GB+ file.

Summary:
- for users with files under 2GB: no popup (maybe the above progress-dlg will be visible sometimes for somewhat bigger files, if such solution is accepted, but it will not need any user interaction, so for your purpose it is ok) 
- for users with 2GB+ files without the allowHugeFilesOpening.xml: no change, they will see the same popup denying the opening
- for users with 2GB+ files with the allowHugeFilesOpening.xml: they will see either Don's warning popup or the above progress-dlg (ditto above; for your needs is better the possible progress-dlg)

**Comment by alankilborn** [comment]
>But even now there is the 'FileTooBigToOpen' popup, when you try to open a 2GB+ file.

True.  OK, I don't think that has ever been a problem with my scripts.  Of course, with what I do it is hard to find a huge text file anyway. :-)

**Comment by donho** [comment]
@xomx 
The issue is a request of removing 2GB restriction for x64.
The suggestion was from adding the pre-processor to adding a progress bar.
No, I'm not for the progress bar to make the code even more complex, whereas a simple warning message can get job done.

@alankilborn 
Sorry about that I have to reject a power user's suggestion, but there might be the way to script a push button action?

**Comment by alankilborn** [comment]
>@alankilborn
Sorry about that I have to reject a power user's suggestion, but there might be the way to script a push button action?

No problem, I just wanted to talk it thru.  It's okay for me whatever is decided to do.

**Comment by donho** [comment]
With the several tests:
https://github.com/notepad-plus-plus/notepad-plus-plus/pull/11044#issuecomment-1012698517
it's meaningless to remove 2GB limit for Notepad++

**Comment by ArkadiuszMichalski** [comment]
@donho On SciTE for big file I get this:
![image](https://user-images.githubusercontent.com/2730894/149537143-a1e9f2be-f4db-43ce-a1f8-ebfe3520a286.png)
After press yes some progress appear:
![image](https://user-images.githubusercontent.com/2730894/149537248-f1c33a08-d62e-447d-b661-1582b75d94f3.png)

And opening 2GB dummy text file takes 14s. Maybe there are some improvements in the new Scintilla. Maybe it's worth coming back to this after updating Scintilla.

**Comment by donho** [comment]
@ArkadiuszMichalski 
I've tested SciTE 5.1.6 and indeed it took only few seconds to load even 5GB file.
The poor performance in Notepad++ could be due to old Scintilla, or some imperfection of its loading routine.
The issue is reopened.
