### ISSUE TITLE
HTML Parsing : inside script element - block 

### ISSUE THREAD

**Issue by raphpell** [notepad-plus-plus/notepad-plus-plus#10925]
### Description of the Issue
Blocks not working correctly in SCRIPT html element.

### Steps to Reproduce the Issue
1. type <SCRIPT ></SCRIPT >
2. type  <SCRIPT ></SCRIPT >
3. type JS Code in the second element

### Expected Behavior
Blocks works properly (expanding, reducing js code)

### Actual Behavior
Blocks don't works properly

### Debug Information
Notepad++ v8.1.9.3   (32-bit)
Build time : Dec  6 2021 - 19:16:45
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 10 Home (64-bit) 
OS Version : 2009
OS Build : 19043.1415
Current ANSI codepage : 1252
Plugins : mimeTools.dll NppConverter.dll NppExport.dll

**Comment by ArkadiuszMichalski** [comment]
Put some real example where this problem occur.

**Comment by raphpell** [comment]
```
<html>
<head></head>
<body>

<script src=""></script><!-- Delete this line tu reduce myFunction block -->
<script>
let myFunction (){
    /* I can't reduce this block - block not detected */
    }
</script>
</html>

</body>
```

**Comment by ArkadiuszMichalski** [comment]
This is not valid JS syntax.

**Comment by raphpell** [comment]
```
<html>
<head></head>
<body>

<script src=""></script><!-- Delete this line tu reduce myFunction block -->
<script>
var myFunction (){
    /* I can't reduce this block - block not detected */
    }
</script>
</html>

</body>
```

**Comment by ArkadiuszMichalski** [comment]
Adding one or two new lines before `myFunction` (depending on the cursor position) fixes it too. You can report it directly to [Lexilla](https://github.com/ScintillaOrg/lexilla) (for `LexHTML.cxx` lexer) which is used by Notepad++.

**Comment by ArkadiuszMichalski** [comment]
![image](https://user-images.githubusercontent.com/2730894/146790375-12f78a21-2f74-4d37-b1b4-09212d4fd4b4.png)

**Comment by ArkadiuszMichalski** [comment]
https://github.com/ScintillaOrg/lexilla/issues/47

**Comment by ArkadiuszMichalski** [comment]
Fixed by https://github.com/notepad-plus-plus/notepad-plus-plus/commit/a61b03ea8887e21c6e1b7374068962f635b79b80.
