### ISSUE TITLE
search and substitute function is working bad after latest update

### ISSUE THREAD

**Issue by mtomatis** [notepad-plus-plus/notepad-plus-plus#10920]
### Description of the Issue

After updating notepad++ at 8.1.9.3 version, the search and substitution function is not working regularly anymore

### Steps to Reproduce the Issue

1. search a word or a character
2. substitute it with another
3. substitution won't be complete and the curent text won't be updated. Restart notepad++ is the only chance to make it work, but only once.

### Expected Behavior

Search and substitute characters or strings more times on the same text

### Actual Behavior

Search and replace seems to work only once and not on all cases.

### Debug Information

Notepad++ v8.1.9.3   (64-bit)
Build time : Dec  6 2021 - 19:21:37
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 10 Pro (64-bit) 
OS Version : 2009
OS Build : 22000.376
Current ANSI codepage : 1252
Plugins : ComparePlugin.dll mimeTools.dll NppConverter.dll NppExport.dll Remove Duplicate Lines.dll 

Actually my notepad++ is running on Windows 11 64bit

**Comment by alankilborn** [comment]
I think you need to provide a data file and then elaborate some scenarios where replace isn't working, on data in that file.  Be specific.

If I load up 8.1.9.3 and try a replacement in the `license.txt` file, like to change `e` to `E` it works just fine, either once or multiple times.

**Comment by mtomatis** [comment]
Ok, I found my system needed a full reboot to let notepad++ work properly after its latest update.
Case closed.
