### ISSUE TITLE
Hmm... things of i think abnormally functions. (and some wish functions)

### ISSUE THREAD

**Issue by TinyProbe** [notepad-plus-plus/notepad-plus-plus#10928]
[abnormal func]
1. If a block-shaped cursor is selected, we think that when selecting text, the cursor should be positioned to the right beyond the characters at either end of the selected text, but this is not the case.

[wish func]
1. Add cursor underline.

Thank you.

**Comment by alankilborn** [comment]
>If a block-shaped cursor is selected, we think that

Who is "we"?
I certainly don't think that.
I think that, with the cursor set to "block", the selected text is correct and obvious.

>Add cursor underline

The underline caret is used to indicate when the user is in "overwrite mode".
I don't think this behavior should be changed.

**Comment by TinyProbe** [comment]
oh, you answered to this ask.
yeah. you're right. i just suggested cuz i think would be better if change some func similarly as another text editor.
and thank you for give this editor

**Comment by donho** [comment]
You should submit your feature request to [Scintilla](https://www.scintilla.org/) instead of here.
The cursor behaviour is standard so I don't think it gonna be changed.
