### ISSUE TITLE
Notepad++ it's very slow when opening an inlined file

### ISSUE THREAD

**Issue by swordfish2011** [notepad-plus-plus/notepad-plus-plus#10932]
When you open a bigger ( 2-3 MB ) inlined file, the software almost crashes and the scrollbar it's almost impossible to move.
Open any inlined file and you will see the behaviour.

**Comment by mere-human** [comment]
What is "inlined file"? Can you attach it here?

**Comment by swordfish2011** [comment]
Sure. Here it is. Open it in notepad and you will see what I am talking about.
My environment it's Windows 10 with last version of Notepad++.
Thanks. 

[https://drive.google.com/file/d/1wPmfdIJ19hjCyVw1q_sof0pAyBBLmeWE/view?usp=sharing](url)

**Comment by alankilborn** [comment]
@swordfish2011 Nobody wants to (and not everyone can) open your google-drive linked file.  Do what @mere-human suggests and simply _attach_ your file here.

**Comment by swordfish2011** [comment]
[slow.txt](https://github.com/notepad-plus-plus/notepad-plus-plus/files/7757808/slow.txt)

My bad, there you go :)

**Comment by dail8859** [comment]
Cannot reproduce. The attached file opens fine for me.

@swordfish2011 Please provide more details such as your debug info at a minimum.

My debug info:

```
Notepad++ v8.1.9.3   (64-bit)
Build time : Dec  6 2021 - 19:21:37
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : "C:\Users\jdailey\Downloads\slow.js"
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 10 Home (64-bit) 
OS Version : 2009
OS Build : 19044.1415
Current ANSI codepage : 1252
Plugins : ComparePlugin.dll ElasticTabstops.dll LuaScript.dll mimeTools.dll NppConverter.dll NppExport.dll NppMenuSearch.dll 
```
