### ISSUE TITLE
Python Syntax Highlighting "triple" blue

### ISSUE THREAD

**Issue by RedKnite5** [notepad-plus-plus/notepad-plus-plus#10936]
### Description of the Issue

The Python syntax highlighting for keywords includes "triple" in the default keywords list and does not have "nonlocal".

The default keyword list is:
and as assert break class continue def del elif else except exec False finally for from global if import in is lambda None not or pass print raise return triple True try while with yield

### Steps to Reproduce the Issue

1. Create a file associated with Python with the .py extension.
2. Write the word "triple".

### Expected Behavior

The word to be black like any other name like "foo" would be.

### Actual Behavior

It turned blue like a keyword.

### Debug Information

Notepad++ v8.1.9.3   (64-bit)
Build time : Dec  6 2021 - 19:21:37
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 10 Pro (64-bit) 
OS Version : 2009
OS Build : 19043.1348
Current ANSI codepage : 1252
Plugins : BigFiles.dll ComparePlugin.dll DSpellCheck.dll mimeTools.dll NotepadStarterPlugin.dll NppConverter.dll NppExport.dll NppGist.dll NppQrCode64.dll NppSaveAsAdmin.dll OpenSelection.dll PoorMansTSqlFormatterNppPlugin.dll 

![NPP_BUG](https://user-images.githubusercontent.com/33992887/147150622-e9d7548f-7319-4621-9d5f-54f0cf48e4a6.PNG)

**Comment by dail8859** [comment]
You must have custom configuration changes as it does not highlight triple by default and also highlights `nonlocal` fine.

![image](https://user-images.githubusercontent.com/3694843/147183850-4e94ad4e-2883-4f08-9290-165559713094.png)


The default keywords are here for python:

https://github.com/notepad-plus-plus/notepad-plus-plus/blob/85d6108a6b799a7c5ae75f903e16133e273d9aac/PowerEditor/src/langs.model.xml#L307-L310


You might also want to take a look at this to potentially help solve your issue: https://npp-user-manual.org/docs/config-files/#configuration-files-during-upgrades

My debug info for reference.

```
Notepad++ v8.1.9.3   (64-bit)
Build time : Dec  6 2021 - 19:21:37
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 10 Home (64-bit) 
OS Version : 2009
OS Build : 19044.1415
Current ANSI codepage : 1252
Plugins : ComparePlugin.dll ElasticTabstops.dll LuaScript.dll mimeTools.dll NppConverter.dll NppExport.dll NppMenuSearch.dll 
```

**Comment by ArkadiuszMichalski** [comment]
https://docs.python.org/3/reference/lexical_analysis.html#keywords

They are all listed in `instre1`. The first three (`False`, `None`, `True`) are listed in `instrer2`. It's also worth checking if something is missing also in the [`python.xml`](https://github.com/notepad-plus-plus/notepad-plus-plus/blob/85d6108a6b799a7c5ae75f903e16133e273d9aac/PowerEditor/installer/APIs/python.xml) autocompletion file.

**Comment by dail8859** [comment]
I think it is safe to say that Notepad++ is configured correctly as far as syntax highlighting goes. @RedKnite5 If you have more details or are able to reproduce this issue with Notepad++ portable (e.g. the zip) then please let us know.
