### ISSUE TITLE
Installer shows Python twice

### ISSUE THREAD

**Issue by massic80** [notepad-plus-plus/notepad-plus-plus#10937]
### Description of the Issue
Just downloaded and installed x64 version: in "Function List Files" section of installer, Python appears twice.

### Steps to Reproduce the Issue
Run the installer and scroll to "Function List Files"

### Expected Behavior
I'm not a Python developer and I don't know whether there is a difference between the two listed items, but in case two of them are needed a better naming would be appreciated in order to tell them apart. Otherwise, there is one too many :)

### Actual Behavior
They are both called just Python

**Comment by dail8859** [comment]
Introduced in 1039c10bae0509895d90ff1269b768a3b1971996

The new one was supposed to be for Lua.

**Comment by donho** [comment]
Fixed in https://github.com/notepad-plus-plus/notepad-plus-plus/commit/30c586d94c71b41b708716750f63c908306d8aa4
