### ISSUE TITLE
Please simplify the Update-Process

### ISSUE THREAD

**Issue by Alfagun74** [notepad-plus-plus/notepad-plus-plus#10947]
### Description of the Issue
Is it really necessary to click through the entire installer again?
Please just update on-the-fly, if auto-update is enabled.

### Expected Behavior
Automatic Update, like Steam for example.

### Actual Behavior
Do you want to install this?  
Next.  
Next.  
Install.  
Close.  
README  

### Debug Information
Notepad++ v8.1.9.3   (64-bit)
Build time : Dec  6 2021 - 19:21:37
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 10 Pro (64-bit) 
OS Version : 2009
OS Build : 22000.376
Current ANSI codepage : 1252
Plugins : mimeTools.dll NppConverter.dll NppExport.dll

**Comment by donho** [comment]
I don't use Steam, but I suppose your "automatic update" is like chrome's silent update.
However, the audience is not the same, so users' need is not the same - A lot of Notepad++ users prefer to get update notification and decide to update it or not.
OTOH, such silent update needs a complex system that I'm not willing to implement.
