### ISSUE TITLE
UDL documentation images broken -- guide is useless as is

### ISSUE THREAD

**Issue by kbearle** [notepad-plus-plus/notepad-plus-plus#10940]
### Description of the Issue

This URL -- https://ivan-radic.github.io/udl-documentation/, is supposed to guide a person through the use and application of creating a UDL -- however, it relies on embedded images and those image links are broken, so they don't appear.

The written text isn't enough information to understand what is shown in the images, so as it stands, the documentation is useless.

### Steps to Reproduce the Issue

1.   Fix image links.
2.   Create more text that describes / provides context for what is to be found in the images (for those that are visually impaired).
3. 

### Expected Behavior

Be able to read and understand how to create a UDL that works much like the SQL defined language, only has the ability to implement folded sections (as the code I'm working on is involved and long, with multiple CTE -- would like to fold those up when I'm not in those sections.

### Actual Behavior

No images, so couldn't figure out how to get the folding operation done in UDL.  Also, couldn't figure out how to get the coloring of keywords to work as it does in the SQL defined language.

**Comment by AikenBM** [comment]
Seems to be working for me. I see no broken images on any of the screens. Might be an issue with a CDN or a web filter.

**Comment by kbearle** [comment]
Looks like AikenBM was right.  The links work on my personal computer, but didn't on my work computer.  Ugh!!  Sorry to bother everyone, but thanks for the response.
