### ISSUE TITLE
[MinGW] Support both MingGW multilib versions

### ISSUE THREAD

**Issue by ArkadiuszMichalski** [notepad-plus-plus/notepad-plus-plus#10941]
MinGW can come as a multilib version, which means that a given version can generate both 32-bit and 64-bit binary. In this variant one pack contains two kinds of library. We don't need have two completely separate tools and switching between them through the `PATH` variable.

MinGW multilib version is available on the locations:
[MinGW-W64 GCC-8.1.0 i686-posix-sjlj](https://sourceforge.net/projects/mingw-w64/files/Toolchains%20targetting%20Win32/Personal%20Builds/mingw-builds/8.1.0/threads-posix/sjlj/)
[MinGW-W64 GCC-8.1.0 x86_64-posix-sjlj ](https://sourceforge.net/projects/mingw-w64/files/Toolchains%20targetting%20Win64/Personal%20Builds/mingw-builds/8.1.0/threads-posix/sjlj/)
This is the same version of GCC 8.1.0 that appveyor uses, just a different exception handling (here `sjlj` for both types). We need only download one of them and we can generate 32-bit and 64-bit Notepad++. I checked both and they work fine. There are even newer versions, but I haven't checked them:
[Multilib Toolchains(Targetting Win32 and Win64)](https://sourceforge.net/projects/mingw-w64/files/Multilib%20Toolchains(Targetting%20Win32%20and%20Win64)/)

We can check if our version of gcc supports multilibs with the `-v` option, by invoking `gcc -v` (find `--enable-multilib` or `--disable-multilib` state).

Currently in the `makefile` it is possible to force generation of 32-bit Notepad ++ if we have 64-bit MinGW. But the reverse is not possible, I mean to generate 64-bit Notepad++ if we have 32-bit MingGW. This behaviour is controlled by explicitly passing the `TARGET_CPU` variable in the command line.
https://github.com/notepad-plus-plus/notepad-plus-plus/blob/30c586d94c71b41b708716750f63c908306d8aa4/PowerEditor/gcc/makefile#L85
To support oposite case we need only add one more condition that checking `x86_64` value in passing `TARGET_CPU` and set proper flags.

BTW, we can also add detection for multilib support, but that will complicate the conditions a bit (it seems unnecessary). I assume that if someone wants to use the `TARGET_CPU` variable, they know that his version of MinGW supports multilib.

**Comment by donho** [comment]
> Currently in the makefile it is possible to force generation of 32-bit Notepad ++ if we have 64-bit MinGW.

It's rather a good news - so no modification in makefile, but some modifications in Build.md I suppose?

**Comment by ArkadiuszMichalski** [comment]
@donho Generation 64-bit Notepad++ from 32-bit MingWG multilib needs to only add (before [line 90](https://github.com/notepad-plus-plus/notepad-plus-plus/blob/master/PowerEditor/gcc/makefile#L90) ):
```
else ifneq "$(and $(findstring x86_64,$(TARGET_CPU)),$(findstring command line,$(origin TARGET_CPU)))" ""
export CXX += -m64
export LD += -m64
export RC += -Fpe-x86-64
```

People who have 32-bit MinGW multilib in `Path` set by default could also quickly generate 64-bit Notepad++ without modifying `Path`. But if you don't want it, I won't add it. Well, it is worth mentioning in `Build.md` that at least for 64-bit MinGW multilib it is possible through the `TARGET_CPU` variable.

BTW; also here only one flag should be add:
https://github.com/notepad-plus-plus/notepad-plus-plus/blob/a563a8b812c843279879986e84fdc312a25f0b9d/PowerEditor/gcc/makefile#L53

I would give [`-Os`](https://gcc.gnu.org/onlinedocs/gcc/Optimize-Options.html#index-Os) because it generates a smaller `.exe`.

**Comment by donho** [comment]
It's good to provide an unique, simpler way to users (and to us) in order to provide a good experience.
Could you provide a PR for it please?

**Comment by chcg** [comment]
Regarding -O2 vs. -Os
https://gcc.gnu.org/onlinedocs/gcc-9.1.0/gcc/Optimize-Options.html#Optimize-Options
```

Optimize for size. -Os enables all -O2 optimizations except those that often increase code size:

-falign-functions  -falign-jumps 
-falign-labels  -falign-loops 
-fprefetch-loop-arrays  -freorder-blocks-algorithm=stc

It also enables -finline-functions, causes the compiler to tune for code size rather than execution speed, and performs further optimizations designed to reduce code size. 
```
, so -Os should be sufficient.
