### ISSUE TITLE
Automatic updates does not default to install folder

### ISSUE THREAD

**Issue by malcolm-davis** [notepad-plus-plus/notepad-plus-plus#10942]
### Description of the Issue
When the application notifies the user of a Notepad++ update, the update defaults to C:\Program Files\Notepad++ and not the folder that I installed the application.

### Steps to Reproduce the Issue
1.  Install Notepad++ in a folder other than C:\Program Files\Notepad++.  I have mine installed in C:\dev\tools\Notepad++\
2.  Wait for an update.
3.  During the update, C:\Program Files\Notepad++ is displayed in the install folder selection.

### Expected Behavior
During the update, I expect C:\dev\tools\Notepad++\ to be displayed.

### Debug Information
Notepad++ v8.1.9.3   (64-bit)
Build time : Dec  6 2021 - 19:21:37
Path : C:\dev\tools\Notepad++\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 10 Pro (64-bit) 
OS Version : 2009
OS Build : 19042.1415
Current ANSI codepage : 1252
Plugins : mimeTools.dll NppConverter.dll NppExport.dll NPPJSONViewer.dll

**Comment by dail8859** [comment]
Duplicate #8251

**Comment by dail8859** [comment]
Closing as duplicate.
