### ISSUE TITLE
Check sign in Language menu not shown

### ISSUE THREAD

**Issue by AleWin32** [notepad-plus-plus/notepad-plus-plus#1095]
The selected language used for the opened file in Notepad++ it is not shown in Language menu.
In previous versions, there were a check sign close to the language name showing this.
You can notice that the space needed for the check sign it is created in front of the language name.

**Comment by fml2** [comment]
The language menu is nested, so a check mark would not be visible if the menu is opened. A better place would be the status line IMO. It could also be used as a language switcher (double click on it -- and a language selection menu appears).

**Comment by AleWin32** [comment]
As i told, that check sign APPEARED in previous versions and now don't.
I have found a curious case, selecting "C++" languages show the check, but "Java" don't!

No language mark:
![c](https://cloud.githubusercontent.com/assets/7621682/10969199/0e6469a6-83c7-11e5-8631-cc00ab10a2f9.png)

Language mark:
![java](https://cloud.githubusercontent.com/assets/7621682/10969210/28cab58e-83c7-11e5-828e-e95638704254.png)

**Comment by dail8859** [comment]
Same bug for me in v6.8.3. Seems like the about the only menu it shows up on is under the `C` submenu.

**Comment by AleWin32** [comment]
This bug is very easy to reproduce, any clues? Thanks

**Comment by ClaudiaFrank** [comment]
Afaik it is needed to iterate over the menuitems.
A new function could look like

    void doCheck(HMENU mainHandle, int id)
    {
        MENUITEMINFO mii;
        mii.cbSize = sizeof(MENUITEMINFO);
        mii.fMask = MIIM_SUBMENU | MIIM_FTYPE | MIIM_ID | MIIM_STATE;

        int count = ::GetMenuItemCount(mainHandle);
        for (int i = 0; i < count; i++)
        {
            ::GetMenuItemInfo(mainHandle, i, MF_BYPOSITION, &mii);
            if (mii.fType == MFT_RADIOCHECK || mii.fType == MFT_STRING)
            {
                if (mii.hSubMenu == 0)
                {
                    if (mii.wID == (unsigned int)id)
                    {
                        ::CheckMenuRadioItem(mainHandle, 0, count, i, MF_BYPOSITION);
                    }
                    else
                    {
                        mii.fState = 0;
                        ::SetMenuItemInfo(mainHandle, i, MF_BYPOSITION, &mii);
                    }
                }
                else
                {
                    doCheck(mii.hSubMenu, id);
                }
            }
        }
    }

and checkLangsMenu would be needed to be modified to

    void Notepad_plus::checkLangsMenu(int id) const
    {
        Buffer * curBuf = _pEditView->getCurrentBuffer();
        if (id == -1)
        {
            id = (NppParameters::getInstance())->langTypeToCommandID(curBuf->getLangType());
            if (id == IDM_LANG_USER)
            {
                if (curBuf->isUserDefineLangExt())
                {
                    const TCHAR *userLangName = curBuf->getUserDefineLangName();
                    const int nbChar = 16;
                    TCHAR menuLangName[nbChar];

                    for (int i = IDM_LANG_USER + 1 ; i <= IDM_LANG_USER_LIMIT ; ++i)
                    {
                        if (::GetMenuString(_mainMenuHandle, i, menuLangName, nbChar-1, MF_BYCOMMAND))
                            if (!lstrcmp(userLangName, menuLangName))
                            {
                                //::CheckMenuRadioItem(_mainMenuHandle, IDM_LANG_C, IDM_LANG_USER_LIMIT, i, MF_BYCOMMAND);
                                HMENU _langMenuHandle = ::GetSubMenu(_mainMenuHandle, 5);
                                doCheck(_langMenuHandle, i);
                                return;
                            }
                    }
                }
            }
        }
        //::CheckMenuRadioItem(_mainMenuHandle, IDM_LANG_C, IDM_LANG_USER_LIMIT, id, MF_BYCOMMAND);
        HMENU _langMenuHandle = ::GetSubMenu(_mainMenuHandle, 5);
        doCheck(_langMenuHandle, id);
    }

results in

![langmenu](https://cloud.githubusercontent.com/assets/16170444/14001757/005f78ac-f148-11e5-945f-cdb4e97eb9b6.png)

Maybe someone picks up the code and makes a proper pull request out of it.

**Comment by dail8859** [comment]
@ClaudiaFrank If this is a code change you have made and tested, are you able to create a patch file from your *local* repository? (meaning you don't have to fork it, just commit it locally on your computer).

**Comment by ClaudiaFrank** [comment]
@dail8859 - patch created. But I understood that I need to send such patch via mail, don't I?

**Comment by dail8859** [comment]
You don't have to since it's just a text file so you can attach it here.

**Comment by dail8859** [comment]
The patch file is nice because it captures not only the code changes but also commit message and author.

**Comment by ClaudiaFrank** [comment]
@dail8859, thank you. Took some time to find out why patch has been created even dialog
stated otherwise. Here it is. Hopefully usefull.

[LangMenuPatch.txt](https://github.com/notepad-plus-plus/notepad-plus-plus/files/187084/LangMenuPatch.txt)

**Comment by christino156** [comment]
I am using Notepad++ v7.2.1 and I still have this problem. 

If I select any language that begins with c (in this case CSS), everything is ok (the language is checked) :
![works with c](https://cloud.githubusercontent.com/assets/20790332/20649068/3ef627b0-b4bf-11e6-8ec9-364b7251f6bb.JPG)


If I select ANY other language (in this case Normal Text), no language is checked:
![else doesn t work](https://cloud.githubusercontent.com/assets/20790332/20649044/cafa2352-b4be-11e6-8c06-dd370cf28c6c.JPG)

If the issue has already been resolved, I apologize for bringing it up again, but I don't understand why the newest version of Notepad++ would still have this problem.
