### ISSUE TITLE
Memory Leak when toggling to and from Dark Mode.

### ISSUE THREAD

**Issue by Ashfaaq18** [notepad-plus-plus/notepad-plus-plus#10957]
### Description of the Issue

Here's a GIF on the issue

![MemoryLeak_Issue1](https://user-images.githubusercontent.com/27722888/147487811-2701be97-5659-413e-ab4d-f5f31937c0e4.gif)

The task manager above shows the increase in memory consumption when toggling to and from dark mode.

### Steps to Reproduce the Issue

1. Open Notepad++
2. Go to settings->Preferences->Dark Mode
3. Enable and Disable dark mode multiple times and observe your notepad++ memory usage increase in task manager.

### Expected Behavior

Stable memory consumption when toggling to and from dark mode.
### Actual Behavior

Steady linear increase in memory consumption when toggling to and from dark mode .

### Debug Information

Notepad++ v8.1.9.3   (64-bit)
Build time : Dec  6 2021 - 19:21:37
Path : \npp.8.1.9.3.portable.x64\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : ON
Cloud Config : OFF
OS Name : Windows 10 Pro (64-bit) 
OS Version : 2009
OS Build : 19042.1415
Current ANSI codepage : 1252
Plugins : mimeTools.dll NppConverter.dll NppExport.dll

**Comment by donho** [comment]
Are you willing to work on it @Ashfaaq18 ?

**Comment by xomx** [comment]
I can reproduce that. Only private N++ memory is increasing (number of handles, GDI handles and USER handles remains the same).

But it seems to me that there are many memory leaks, so good luck with finding this DM toggling one.

To see these leaks yourself, just open a debugging session of the debug N++ build in the MSVS and close it immediately, with the following stuff added at the very start of N++ wWinMain:

```
#if defined(_DEBUG)
	{
		// check for memory leaks at the exit through a call to _CrtDumpMemoryLeaks
		// - note that in debug mode, objects allocated with the new operator may be destroyed *after* the end of the main function
		int tmpDbgFlag = _CrtSetDbgFlag(_CRTDBG_REPORT_FLAG);
		tmpDbgFlag |= _CRTDBG_LEAK_CHECK_DF;
		tmpDbgFlag |= _CRTDBG_ALLOC_MEM_DF;
		//_crtBreakAlloc = xxx; // specify allocation number of the leaked memory - use this line only after a memory leak has been reported! (do not change any other code and recompile)
		_CrtSetDbgFlag(tmpDbgFlag); // report detected leaks when the program exits
	}
#endif
```

In the 'Output' MSVS window you will see many of the lines like:
Detected memory leaks!
Dumping objects ->
{131956} normal block at 0x00000218980E1BE0, 32 bytes long.
 Data: <N o t e p a d P > 4E 00 6F 00 74 00 65 00 70 00 61 00 64 00 50 00 
{131955} normal block at 0x000002189AA32BA0, 16 bytes long.
 Data: <                > 00 C5 8F 98 18 02 00 00 00 00 00 00 00 00 00 00 
{131954} normal block at 0x000002189AA31FC0, 16 bytes long.
 Data: <                > D8 C4 8F 98 18 02 00 00 00 00 00 00 00 00 00 00 

Usually one can simply identify such leak by setup a _crtBreakAlloc (see the commented line above) for such allocation reported (eg here ... _crtBreakAlloc = 131956;) and recompile and run the debug session again - now the code stops on the relevant memory allocation and you can see the associated N++ code in the callstack...

**Comment by Ashfaaq18** [comment]
> Are you willing to work on it @Ashfaaq18 ?

yeah sure @donho , I'll try looking into it. Let me see if i can find a solution. 

> To see these leaks yourself, just open a debugging session of the debug N++ build in the MSVS and close it immediately, with > the following stuff added at the very start of N++ wWinMain:

And thanks for the tips @xomx.

Btw, If anyone else finds a fix for this, feel free to open a PR.

**Comment by mshingote** [comment]
Every call to `::SendMessage(hwndRoot, NPPM_INTERNAL_REFRESHDARKMODE, static_cast<WPARAM>(!forceRefresh), 0);` from file _...notepad-plus-plus\PowerEditor\src\NppDarkMode.cpp_:344 increases the memory
