### ISSUE TITLE
Unable to download latest portable build

### ISSUE THREAD

**Issue by superbonaci** [notepad-plus-plus/notepad-plus-plus#10960]
Following the guide
https://github.com/notepad-plus-plus/notepad-plus-plus/wiki/Testing#using-the-current-build-version-of-notepad

takes me to
https://ci.appveyor.com/project/donho/notepad-plus-plus

where there isn't any link to any portable .zip or .7z file to test. How can this be?

**Comment by alankilborn** [comment]
Clearly you didn't "follow the guide" like you said...

**Comment by superbonaci** [comment]
Finally did it:

- Download [npp.8.1.9.3.portable.x64.zip](https://github.com/notepad-plus-plus/notepad-plus-plus/releases/download/v8.1.9.3/npp.8.1.9.3.portable.zip) for Windows 64 bits
- Download [Notepad++.x64.Debug.exe](https://ci.appveyor.com/api/buildjobs/9nlscdev4wwtgn37/artifacts/Notepad%2B%2B.x64.Debug.exe) and put it inside the extracted zip.
