### ISSUE TITLE
feature request for a bug: auto disable line wrapping when file size is too large to prevent NPP from hanging

### ISSUE THREAD

**Issue by w-e-w** [notepad-plus-plus/notepad-plus-plus#10967]
### Description of the Issue
this is a duplicate of #8824
currency if line wrapping is enable for large files NPP will likely hang when opening / reading / searching file

### Steps to Reproduce the Issue
open a large text file (say a couple of MB in size) with line wrapping enable
scroll through the file do some search operations
if it didn't hang, then try a bigger size file.
### Expected Behavior

on small files, NPP runs smoothly

### Actual Behavior

NPP hangs, generally doesn't crash but it's not responsive for some time,
the hang Time depends on the size of the file

### Suggested Solution
**simple soluton**
like in VS code and some other code viewers IDEs,
have a check that will auto disable line wrapping if file is too large.
_and perhaps have a warning if someone tries to re-enable it._

**hard solution**
a complete rework on how is handled,
making it in independent process from NPP or something, 
so one can continue using NPP without having it blocked NPP's main function

**Comment by ArkadiuszMichalski** [comment]
Previous discussion https://github.com/notepad-plus-plus/notepad-plus-plus/issues/1910.

**Comment by donho** [comment]
44004d41d43dd803cf7aa5b4639df365e88cdee7
