### ISSUE TITLE
Rename has a length limit

### ISSUE THREAD

**Issue by Tvirus** [notepad-plus-plus/notepad-plus-plus#10961]
![image](https://user-images.githubusercontent.com/42616862/147546314-6ac4fd80-02f0-43fa-8ee5-4e907168db1f.png)

Notepad++ v8.1.9.3   (64-bit)
Build time : Dec  6 2021 - 19:21:37
Path : D:\Notepad++\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 10 Pro (64-bit) 
OS Version : 2009
OS Build : 19043.1415
Current ANSI codepage : 936
Plugins : HexEditor.dll mimeTools.dll NppConverter.dll NppExport.dll NppMarkdownPanel.dll

**Comment by alankilborn** [comment]
I think it is designed to have a limit.
If you are putting a lot of effort in (in order to use a lot of characters in this name), isn't it better to "hard-name" it into a real file in the file system anyway?

**Comment by ArkadiuszMichalski** [comment]
This was raise earlier and closed https://github.com/notepad-plus-plus/notepad-plus-plus/issues/9849.  @donho Any plan to increase this limit or this issue can be close too ([here an explanation why someone may needs a longer name](https://github.com/notepad-plus-plus/notepad-plus-plus/issues/9849#issuecomment-838682078))?

**Comment by donho** [comment]
What length limit is reasonable to you guys?

**Comment by alankilborn** [comment]
I think it is OK the way it is.  If you let it be too long, then the length could be a problem in other parts of the program.  For example, it could do some wacky things to the file tabs if it is too long.  

Plus, people should be encouraged to "hard name" their files, as the first step in a good backup strategy.  (A good backup strategy can include Notepad++'s backup features, but it also needs to include some sort of independent backup -- which can't reasonably be done with "soft named" files).
