### ISSUE TITLE
Please release v8.1.9.4

### ISSUE THREAD

**Issue by superbonaci** [notepad-plus-plus/notepad-plus-plus#10968]
Request to release v8.1.9.4 due to bug #10916

**Comment by dail8859** [comment]
Please see https://community.notepad-plus-plus.org/topic/22325/notepad-8-2-release-candidate

**Comment by alankilborn** [comment]
@superbonaci Please don't waste everyone's time by creating such an issue.  UGH!

**Comment by superbonaci** [comment]
Thanks. I'm asking this because release candidates are not available over chocolatey:
https://github.com/chocolatey-community/chocolatey-packages/issues/1769

**Comment by dail8859** [comment]
@superbonaci chocolatey releases are not supported through the official Notepad++ project, so we cannot help you at all. Please be patient.

**Comment by superbonaci** [comment]
Notepad++ v8.2 already released and available to `chocolatey`.
