### ISSUE TITLE
Stable tabs row position with multiple tab rows

### ISSUE THREAD

**Issue by PlexPro** [notepad-plus-plus/notepad-plus-plus#1096]
Please allow for tab rows not to dynamically reposition themselves.  It is not necessary for the row of the current document to be up front.

When I have enough tabs open that I have multiple rows of tabs, stability of the rows' position becomes important, both to find a document, as well as to be able to drag and drop a tab to a different position.  I often find repositioning a tab impossible.

**Comment by aaaxx** [comment]
:+1: It's completely disorienting. The fact that Microsoft uses it throughout Windows is a proof enough that it's a bad design :-p

**Comment by Ede123** [comment]
I'm currently working on tabbar, so I might have a look at the issue. However I'd prefer to have feedback on #1075 by project members before putting any work into this.

**Comment by AngryGamer** [comment]
Fixed in [9967c59](https://github.com/notepad-plus-plus/notepad-plus-plus/commit/9967c59912a05bfac57854e583d573877fdcb787)
