### ISSUE TITLE
Count action in the Find dialog counts the item from the current context and not on the whole document

### ISSUE THREAD

**Issue by egvijayanand** [notepad-plus-plus/notepad-plus-plus#10971]
### Description of the Issue

Count action in the Find dialog counts the item from the current context and not on the whole document

### Steps to Reproduce the Issue

1. Open any text document, ensure the cursor context is at the beginning of the file and bring on the Find dialog (with focus on Find tab)
2. Enter a search keyword that is available within the document and click on the Count action
3. This will return the total no. of occurrences within the document as the context is at the start
4. Now go back to the document and update the cursor context to the middle of the document
5. Repeat the process in Step 2 and now the Count returned will be from the current context till the end of the document
6. Previously this used to Count the total no. of items irrespective of the cursor context
7. If the intended behavior is this, introduce another action button titled Count All for counting all the items

### Expected Behavior

Counts all the no. of occurrences within the document for the specified keyword

### Actual Behavior

The count returned depends on the cursor context within the document

**Comment by egvijayanand** [comment]
This is observed in the Notepad++ v8.1.9.3 running on Windows 11.

**Comment by alankilborn** [comment]
Observe the status bar of the _Find_ window while you are doing a _Count_.  It will tell you the scope of the search for the count:

* With _Backward Direction_ and _Wrap around_ unticked, it will say `...matches from caret to end-of file`
* With _Backward Direction_ ticked and _Wrap around_ unticked, it will say `...matches from start-of file to caret`
* With _Wrap around_ ticked, it will say `...matches in entire file`

_Wrap around_ means "search from the caret to end, then (wrap the search around to beginning of file and) search from beginning to caret".

The expected behavior you are looking for is in bullet point 3.  Thus, tick _Wrap around_ and your problem is solved.

This issue can be closed.

**Comment by egvijayanand** [comment]
Hi @alankilborn,

Thanks for the details.

A hint can be added to the `Wrap around` option mentioned to get it at first look.

Regards,
Vijay Anand E G

**Comment by alankilborn** [comment]
> A hint can be added to the `Wrap around` option mentioned to get it at first look.

A popup tooltip type hint _would_ be nice, if its text could be short and succinct enough.
What would be your suggestion for such hint text?

BTW, please close this issue.

**Comment by egvijayanand** [comment]
Hi @alankilborn, 

Any meaningful message that would help the end-user to understand the intended behavior better.

Hope one will be added in the near future.

Thanks for your response, closing this issue as the concern raised has been answered.

Regards,
Vijay Anand E G

**Comment by alankilborn** [comment]
> Any meaningful message that would help the end-user to understand the intended behavior better.

Right, obviously, but that kind of reply doesn't help.
I was looking for your specific suggestion as to the exact text, because I can't think of any that is short enough of an explanation to make it a practical tooltip.

**Comment by egvijayanand** [comment]
Check this option to search across the document, irrespective of the caret position.

Hope this message helps.

**Comment by alankilborn** [comment]
> suggested tool-tip text: "Check this option to search across the document, irrespective of the caret position."

Right, but that's not all it does.  It affects some of the non-Count operations differently, particularly _Find Next_.  Thus it is might not be possible to capture all of the functionality in one short little text blurb.  But...I thought you might have had some great inspiration for it.
