### ISSUE TITLE
Replace in all open files crashes since version v8.1.9.3

### ISSUE THREAD

**Issue by BJTimmermann** [notepad-plus-plus/notepad-plus-plus#10974]
### Description of the Issue

Notepad++ 1.9.3 crashes when a replace in all open files is triggered.
In Version 1.9.2 this works fine.

### Steps to Reproduce the Issue

1. Open some files (8 in my case)
2. Select a part of a file to be replaced in all open files
3. Start the use case with the Replace dialog
4. Enter the text to replace and its replacement
5. Click "Replace in all open Files"

### Expected Behavior

Query, if I really want it, and texts replaced without crash.

### Actual Behavior

Notpad++ crashes.

**Comment by donho** [comment]
@BJTimmermann 
Please fill **Debug Information**. It's on the menu `? >  Debug Info...`.

**Comment by donho** [comment]
Closed due to the lack of reply.
