### ISSUE TITLE
Feature Request to wit i.e. Character Count Statistics

### ISSUE THREAD

**Issue by PaltryProgrammer** [notepad-plus-plus/notepad-plus-plus#10987]
Greetings Kind Regards Please consider providing a character count usage statistics tool providing alphabetical and ranked order. Am a bit surprised it is not provided as it seems simple to implement and an obvious tool for a text editor - Thank You - Cheerio

**Comment by donho** [comment]
You can have Character Count Statistics via menu "View > Summary...".

**Comment by PaltryProgrammer** [comment]
I am sorry I did not explain myself properly . My meaning is statistics on a per character basis to wit i.e. e.g.
'a' 27 count 13%
'b' 15 count 7%
etc. for each character including punctuation and space

**Comment by alankilborn** [comment]
It is a good task for one of the scripting plugins, e.g., PythonScript.
For instance, here is one I wrote to do a word-based histogram: https://community.notepad-plus-plus.org/post/61801
I'm sure it would seem simple to you to change it to implement a character-based histogram
