### ISSUE TITLE
Missing translation on Dialog Title "Select a folder as default directory"

### ISSUE THREAD

**Issue by conky77** [notepad-plus-plus/notepad-plus-plus#10984]
### Description of the Issue
Missing translation on Dialog Title "Select a folder as default directory"
### Steps to Reproduce the Issue

1.  Settings-->preferences-->Default directory-->button
2.  you see the missing translation on the title

### Actual Behavior
Translate the tile

### Debug Information
Notepad++ v8.2   (64-bit)
Build time : Dec 30 2021 - 03:40:42
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : -multiInst
Admin mode : ON
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 10 Home (64-bit) 
OS Version : 2009
OS Build : 19044.1415
Current ANSI codepage : 1252
Plugins : ComparePlugin.dll mimeTools.dll NppConverter.dll NppExport.dll NppXmlTreeviewPlugin.dll 

![image](https://user-images.githubusercontent.com/59116246/147880601-b4969d09-dcf0-4f76-8dc1-924c869326fb.png)

**Comment by conky77** [comment]
#8972

**Comment by donho** [comment]
@mere-human 
Could the title be translatable?

**Comment by mere-human** [comment]
> @mere-human Could the title be translatable?

Yes. I can create a PR for it.
