### ISSUE TITLE
Missing translation on Dialog Title "Select a folder to add in Folder as Workspace panel"

### ISSUE THREAD

**Issue by conky77** [notepad-plus-plus/notepad-plus-plus#10983]
### Description of the Issue
Missing translation on Dialog Title "Select a folder to add in Folder as Workspace panel"
### Steps to Reproduce the Issue

1.  file-->Open folder as workspace
2.  you see the missing translation on the title

### Actual Behavior
Translate the tile

### Debug Information
Notepad++ v8.2   (64-bit)
Build time : Dec 30 2021 - 03:40:42
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : -multiInst
Admin mode : ON
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 10 Home (64-bit) 
OS Version : 2009
OS Build : 19044.1415
Current ANSI codepage : 1252
Plugins : ComparePlugin.dll mimeTools.dll NppConverter.dll NppExport.dll NppXmlTreeviewPlugin.dll 

![image](https://user-images.githubusercontent.com/59116246/147880072-35c8b2bd-e4a3-4efe-a7ba-5080100a70fb.png)

**Comment by conky77** [comment]
#8972

**Comment by donho** [comment]
@mere-human 
Could the title be translatable?

**Comment by mere-human** [comment]
> Select a folder to add in Folder as Workspace panel

@donho 
Yes. We just need to add a string to XML and load it here.
https://github.com/notepad-plus-plus/notepad-plus-plus/blob/master/PowerEditor/src/NppCommands.cpp#L186
I can provide a PR.
