### ISSUE TITLE
[MinGW] Place the Scintilla build intermediate files separate from the source files

### ISSUE THREAD

**Issue by ArkadiuszMichalski** [notepad-plus-plus/notepad-plus-plus#10991]
Actually all Scintilla build intermediate files are placed in a permanent folder. It causes that we can't generate Notepad++ by various tools without calling `clean` first. And this means that when we go back to the previous tool, we have to do the whole generation again.

I will fix this after resolving the followings:
https://github.com/notepad-plus-plus/notepad-plus-plus/issues/10504 (fixed)
https://sourceforge.net/p/scintilla/bugs/2306/ ([fixed](https://sourceforge.net/p/scintilla/code/ci/121b4040ce34f3a57bfcfc2ce5adb881b7d2c032/))
https://github.com/ScintillaOrg/lexilla/issues/50 ([fixed](https://github.com/ScintillaOrg/lexilla/commit/815572f252932f69c67a196030cba917efa7480b))

**Comment by donho** [comment]
It's neat this enhancement. However, Scintilla's makefile should not be modified.

**Comment by ArkadiuszMichalski** [comment]
Currently Scintilla's makefile is modified in this place:
https://github.com/notepad-plus-plus/notepad-plus-plus/blob/573a3db6e9d7f032b453154d232991da19f1d7e9/scintilla/win32/makefile#L120

I will wait for the upgrade to the new Scintilla version because [Lexilla's makefile](https://github.com/ScintillaOrg/lexilla/blob/master/src/makefile) will probably be used. And this will require a correction of the Notepad ++ 's makefile. But I have some idea how to do this so we don't have to modify Lexilla's makefile as above.
