### ISSUE TITLE
Syntax highlighting of backticks for language "D"

### ISSUE THREAD

**Issue by andre2007** [notepad-plus-plus/notepad-plus-plus#1099]
In language D a string is either enclosed in quotation marks "HelloWorld!" or in back ticks \`Hello World!\`. 
The built in syntax highlighting of D in Notepad++ doesn't recognize the back ticks.

Could the string enclosed in back ticks highlighted the same ways as with quotation marks?

**Comment by andre2007** [comment]
More precise:  ...quotation marks "HelloWorld!" or in back ticks `Hello World!`

**Comment by paulroho** [comment]
The same issue comes up when editing ES6 code utilizing template strings, e.g. to use string interpolation:
https://developers.google.com/web/updates/2015/01/ES6-Template-Strings

**Comment by dail8859** [comment]
Can you give me a simple example of how back ticks are used in D?
