### ISSUE TITLE
any plans to support Linux?

### ISSUE THREAD

**Issue by 4evermaat** [notepad-plus-plus/notepad-plus-plus#11002]
any plans to support Ubuntu or other Linux flavors?

Or anyone have a trustworthy fork repo that makes Notepad++ available on linux?

**Comment by rdipardo** [comment]
sudo snap install notepad-plus-plus

 - <https://snapcraft.io/install/notepad-plus-plus/ubuntu>
 - <https://community.notepad-plus-plus.org/search?term=linux&in=titles>

**Comment by dail8859** [comment]
As suggested above, there are ways to run it on Linux, however Notepad++ is not officially supported on Linux.

**Comment by darus90** [comment]
npp on windows  less 100MB
npp on snap or wine more 1.3GB
sad.
we need a linux version, a appimage.

**Comment by 4evermaat** [comment]
> npp on snap or wine more 1.3GB

I guess on a server that would be an issue.  On local laptop, not so bad.
