### ISSUE TITLE
Ghost NUL char shows up on editor after Ctrl+R File -> ReloadFromDisk

### ISSUE THREAD

**Issue by sumariva** [notepad-plus-plus/notepad-plus-plus#11007]
### Description of the Issue

I was debugging a log file to read the results. Issuing Ctrl+R to reload contents while task producing the output.
After the end, I fixed the errors reported and then launched the task again.
Then, presses again Ctrl+R to reload contents.
The editor reloaded the file contents but the last line filled with a lot of NUL characters shows up.

The task is a simple php process that writes to stdout and got contents redirected with '>' file redirect operator on a Linux console.
### Steps to Reproduce the Issue

1. Open a File on the editor.
2. I relaunched the task from the console. I do not know if Linux bash truncates the file contents when the '>' operator exec.
3. Press Ctrl+R to reload contents.
4. Confirm the reload on confirm dialog 'This file has been modified by another program'.

### Expected Behavior

Expected that only characters from file have been displayed. It is a text file ISO-8859-1 encoded with Linux line endings '\n'.
### Actual Behavior

The editor shows the file contents plus the last line with lots of NUL(in black background).

### Debug Information

Notepad++ v8.1.9   (64-bit)
Build time : Oct 21 2021 - 23:37:53
Path : U:\Utilitarios\npp.8.1.9.portable.x64\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : ON
Cloud Config : OFF
OS Name : Windows Server 2008 R2 Standard (64-bit) 
OS Build : 7601.24546
Current ANSI codepage : 1252
Plugins : mimeTools.dll NppConverter.dll NppExport.dll

**Comment by donho** [comment]
@sumariva 
Can you reproduce it steadily? If yes, could you provide detailed instructions please?

**Comment by sumariva** [comment]
Well, I just press the Ctrl + R several times. What I have noticed is a kind of buffer/cache on the filesystem.
Because sometimes when I hit the Ctrl + R, the editor does not show the popup warning.
Much like it did not see a file change.

Now I could attach a print screen to show you the situation.
Look at the statusbar of the application. It reported a file size length of 35.798 bytes.

![nul bytes](https://user-images.githubusercontent.com/6371372/148712594-0fbb5638-21ab-4728-94fe-529383c2965d.png)

Now, take a look at filesize on the Linux console. 12763 bytes.

![file-size](https://user-images.githubusercontent.com/6371372/148712651-63c70c05-7362-40ac-87ab-bfddedeff337.png)

For some reason, it is reading beyond the end of the file. The file is been accessed through a file share on the windows server.
I do not know how the application accessed the file. Maybe need a refresh to the filesystem stat information.

Hope it clarifies the problem.

**Comment by sumariva** [comment]
I will try to download the new release this week.

**Comment by donho** [comment]
@sumariva 
Does the bug happened in the new release?

**Comment by sumariva** [comment]
The server administrator still has not upgraded the Notepad++. I will try inquiry again.

**Comment by donho** [comment]
Outdated.
If the bug reappears in the newest version, please ping me.
