### ISSUE TITLE
Find-Replace dialogs :  narrow text box is cutting translated labels display

### ISSUE THREAD

**Issue by FdaSilvaYY** [notepad-plus-plus/notepad-plus-plus#11006]
### Description of the Issue

![image](https://user-images.githubusercontent.com/15791524/148546179-6c5ff507-f6fd-41be-a940-c331a55774b2.png)

Whole french translation is `". comprend ligne nouvelle"`

This group box and labels should be enlarged a bit to avoid cutting translated texts.

I bet, this GUI issue exist for other translations than French

### Steps to Reproduce the Issue

1. select a GUI language other than English.
2. Open any Find, Find-Replace dialog box
3. 

### Debug Information
Seen in the last 8.2 version.
I see this GUI issue since a long time, may be a duplicated one ?

**Comment by FdaSilvaYY** [comment]
Want a PR to fix it ?

**Comment by alankilborn** [comment]
Screen real estate is a rare resource.  I think the way it goes is that sizes are optimized for English, and other translations have to adjust the translation text to fit.

**Comment by mere-human** [comment]
An alternative solution could be to show a tool tip when hovering over the shortened text label.

**Comment by donho** [comment]
> An alternative solution could be to show a tool tip when hovering over the shortened text label.

The tooltip are using for the hint, not for the translation - it will make confusion, not mention to the implementation is not easy.
