### ISSUE TITLE
Debug information reports wrong OS information with windows 11

### ISSUE THREAD

**Issue by conky77** [notepad-plus-plus/notepad-plus-plus#11011]
### Description of the Issue
Notepad++'s Debug Information reports wrong OS information with windows 11.
It shows the license information and not the current OS

From Control Panel:
Edition	**Windows 11 Home**
Version	21H2
Data installazione:	‎08/‎01/‎2022
Build OS	22000.376
Esperienza	Pacchetto delle esperienze delle funzionalità Windows 1000.22000.376.0

from Debug information:
Notepad++ v8.2   (64-bit)
Build time : Dec 30 2021 - 03:40:42
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : **Windows 10 Home (64-bit)** 
OS Version : 2009
OS Build : 22000.376
Current ANSI codepage : 1252
Plugins : ComparePlugin.dll mimeTools.dll NppConverter.dll NppExport.dll NppXmlTreeviewPlugin.dll 

I tried also to re-install Notepad++, but the result is the same

### Steps to Reproduce the Issue

1. update windows 10 to windows 11 
2. Notepad++, debug information 

### Debug Information
Notepad++ v8.2   (64-bit)
Build time : Dec 30 2021 - 03:40:42
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 10 Home (64-bit) 
OS Version : 2009
OS Build : 22000.376
Current ANSI codepage : 1252
Plugins : ComparePlugin.dll mimeTools.dll NppConverter.dll NppExport.dll NppXmlTreeviewPlugin.dll 

![image](https://user-images.githubusercontent.com/59116246/148638520-4bfc37e8-df7c-4a87-9f77-93ee309430b6.png)

**Comment by chcg** [comment]
See https://github.com/notepad-plus-plus/notepad-plus-plus/blob/master/PowerEditor/src/Parameters.cpp#L803, currently Win 10 is the latest version which could be detected. Unclear if major version 11 is used for WIN11. See
https://chromium.googlesource.com/chromium/src/base/+/refs/heads/main/win/windows_version.cc, but various sites stated the Win11 still used major version 10 + appropriate build number.

**Comment by donho** [comment]
Notepad++ has the similar way for the detection of Windows 11:
https://github.com/notepad-plus-plus/notepad-plus-plus/blob/master/PowerEditor/src/DarkMode/DarkMode.cpp#L250

I will see what I can do about it.
