### ISSUE TITLE
Can't map a shortcut to toggle Dark mode

### ISSUE THREAD

**Issue by csdvrx** [notepad-plus-plus/notepad-plus-plus#11010]
### Description of the Issue

Currently, there is no possibility to follow the system theme. The next best would be to toggle the Dark mode with a shortcut

However, there is no possibility either to map a key to the Dark mode checkbox

### Steps to Reproduce the Issue

1. Open Settings/Shortcut mapper
2. Try each tab: dark is not anywhere
3. You can only modify shortcuts, not create a new one

### Expected Behavior

I would expect Settings/Shortcut mapper would have an actual entry for Dark Mode

### Actual Behavior

There is no shortcut possibility for dark mode: it requires going into settings with Alt T enter Down Down Down Tab Tab space

That's a lot a keys to press

### Debug Information

It happens in v.8.1.9.3 but unless something has changed, it'll still be the case in the latest vrsion

Notepad++ v8.1.9.3   (64-bit)
Build time : Dec  6 2021 - 19:21:37
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : "C:\Users\Charlotte\Desktop\usbipd.txt"
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 10 Pro (64-bit) 
OS Version : 2009
OS Build : 22000.376
Current ANSI codepage : 1252
Plugins : mimeTools.dll NppConverter.dll NppExport.dll

**Comment by donho** [comment]
Switching ON/OFF dark mode is Preferences dialog, but not via menu command. Therefore there's no way to implement the shortcut ability on dark mode.

**Comment by csdvrx** [comment]
I would suggest adding a link between the toogle and a menu command, so that it would become possible...

For now I'm using the following AHK script after having mapped Ctrl ` to settings (the 18 ups are necessary since preferences save the current position, so this assumes a worst case (bottom) and goes back to top, where extra "ups" are ignored):

toggleDarkModeInNotepadPlusPlus() {
  ControlSend,Scintilla1,{Control down}`,{Control up},ahk_class Notepad++
  ControlSend,ListBox1,{Up}{Up}{Up}{Up}{Up}{Up}{Up}{Up}{Up}{Up}{Up}{Up}{Up}{Up}{Up}{Up}{Up}{Up},ahk_class #32770
  ControlSend,Button34,{Space},ahk_class #32770
  ControlSend,ListBox1,{Esc},ahk_class #32770
  Return
} ;toggleDarkModeInNotepadPlusPlus
