### ISSUE TITLE
with Dark mode, in Search Dialog, the tab labels are cut (windows 11)

### ISSUE THREAD

**Issue by conky77** [notepad-plus-plus/notepad-plus-plus#11012]
### Description of the Issue
with Dark mode, in Search Dialog, the tab labels are cut (i.e. "replace" and "find in files" )
OS: windows 11
resolution: 1920 X 1080, zoom 150%
changing to 1280 X 768 zoom 100%, the result is the same
with a different computer, with win 10, the labels are more visible (just a little bit cut)

### Steps to Reproduce the Issue

1.  set dark mode
2.  open search dialog
3.  see the labels "replace" and "find in files" cut

### Debug Information
Notepad++ v8.2   (64-bit)
Build time : Dec 30 2021 - 03:40:42
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 10 Home (64-bit)  --> Actually windows 11 (N++ shows wrong information)
OS Version : 2009
OS Build : 22000.376
Current ANSI codepage : 1252
Plugins : ComparePlugin.dll mimeTools.dll NppConverter.dll NppExport.dll NppXmlTreeviewPlugin.dll 

![image](https://user-images.githubusercontent.com/59116246/148638974-8dfdfd9e-f832-4939-aa3c-efb27920d72b.png)

**Comment by ageekhere** [comment]
I also have this issue, any updates on a fix for it?

**Comment by donho** [comment]
@conky77 @ageekhere 
Do you still have the issue with latest Notepad++ v8.6.5 ?

**Comment by ageekhere** [comment]
> @conky77 @ageekhere Do you still have the issue with latest Notepad++ v8.6.5 ?

Here is the current screenshot
![Screenshot 2024-04-12 092011](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/13173133/78ebc441-387d-485b-821b-3ec0a42e11e4)
![Screenshot 2024-04-12 091951](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/13173133/5b00a7f7-4d80-4e17-b9d8-b6d5f03aad94)

The tab labels are not cut for me now, however there is still a box border around in selection, count, find all in current document and replace all, but that is a different issue

**Comment by conky77** [comment]
@donho 
I still have the same problem
![image](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/59116246/e2d8feb2-1678-4a25-9ef4-f45b5a79c7ba)

The problem looked solved, but after restarting Notepad++, the problem appeared.
I don't remember the exact sequence, but I was in Ligth mode in Italian.
I switched to Dark mode (from setting, dark mode)
<img width="659" alt="image" src="https://github.com/notepad-plus-plus/notepad-plus-plus/assets/59116246/ebb5f767-624b-40b3-b44b-1c8f7b433699">

The problem was solved
I switched to the English language (entering setting...)
the problem still was solved (I Moved from find and replace)
I restarted Notepad++ and the problem appeared
Now, even when I return to light mode, to Italian, and restart Notepad++, the labels in dark mode are always cut.

To open the find dialog, I always used ctrl+f, but I used the mouse to open the setting
The labels are cut only in dark mode: in ligth mode everything is ok
![image](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/59116246/18637898-8713-4ea7-8773-c29b36c8f410)

debug info:
Notepad++ v8.6.5   (64-bit)
Build time : Mar 22 2024 - 00:07:29
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
Periodic Backup : ON
OS Name : Windows 11 Home (64-bit
OS Version : 23H2
OS Build : 22631.3447
Current ANSI codepage : 1252
Plugins : 
    ComparePlugin (2.0.2)
    CSVLint (0.4.6.6)
    DSpellCheck (1.5)
    JsonTools (7.1)
    mimeTools (3.1)
    NppConverter (4.6)
    NppExport (0.4)
    NPPJSONViewer (2.0.7)
    NppXmlTreeviewPlugin (2)
    XMLTools (3.1.1.13)

**Comment by conky77** [comment]
in addition, I just realized in debug info,  
OS Name : Windows 11 Home (64-bit

a parenthesis is missing (after "(64 bit"      )

 issue #14987

**Comment by ozone10** [comment]
@conky77 @ageekhere
could you check if there is issue with Shortcut mapper, Plugins admin and User Defined Language dialogs?

**Comment by conky77** [comment]
@ozone10 
yes, there are some problems in any dialog you mentioned

<img width="566" alt="image" src="https://github.com/notepad-plus-plus/notepad-plus-plus/assets/59116246/c83202a6-2091-4614-89f2-15d85afa1004">

<img width="509" alt="image" src="https://github.com/notepad-plus-plus/notepad-plus-plus/assets/59116246/a9d01430-f361-45ad-912e-d8862bd37c9f">

<img width="549" alt="image" src="https://github.com/notepad-plus-plus/notepad-plus-plus/assets/59116246/1f50175d-59d3-40ee-99da-8d2ae177023c">

**Comment by ozone10** [comment]
@conky77 
could you try Notepad++ build from https://github.com/notepad-plus-plus/notepad-plus-plus/actions/runs/8672750106

**Comment by conky77** [comment]
@ozone10   it seems ok now
<img width="569" alt="image" src="https://github.com/notepad-plus-plus/notepad-plus-plus/assets/59116246/4bdc5939-71cc-4dcf-81a7-b164278ebf50">

In light mode, the separation between the two tab sheets is lighter and lighter in both this build and the official version.
![image](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/59116246/b85112f2-1833-4bfc-b895-2b759409aee3)

I am trying to remember what happens with Windows 10 or if it has always been like that.

**Comment by donho** [comment]
https://github.com/notepad-plus-plus/notepad-plus-plus/commit/e0bb723700c2ed75da90284bcf0e33300e3463ff
