### ISSUE TITLE
Notepad++ version 8.2 not automatically updated yet

### ISSUE THREAD

**Issue by Fruchtzwerg94** [notepad-plus-plus/notepad-plus-plus#11015]
The latest 8.2 release is not yet available in the automatic updater.
The reason is, the [Update URL](https://notepad-plus-plus.org/update/getDownloadUrl.php) still links the _8.1.9.3_ and was not updated after the release.
Is there a reason why the version is not updated there yet?

**Comment by alankilborn** [comment]
Please don't open issues of this sort.  It just increases the general noise level.  Author of N++ will set the updater when he feels it is warranted.

**Comment by Fruchtzwerg94** [comment]
> Please don't open issues of this sort. It just increases the general noise level. Author of N++ will set the updater when he feels it is warranted.

Didn't know that. Okay. Thanks!

**Comment by vbojan** [comment]
This is an ongoing issue and keeps causing confusion among users :(

If built-in Updater keeps reporting no new version exist and yet there are new versions including a security fixes then the updater defeats the purpose. I understand that author wants to be sure new(er) version(s) goes through stability validation which takes some time, but that's what Beta and RC versions are for, so users can join a Beta channel and be early adopters of latest and greatest features and can then report on any issues they might suffer from.

But I currently have 8.8.8 and the update URL keeps returning `<NeedToBeUpdated>no</NeedToBeUpdated>` even though 8.8.9 was released containing a vulnerability fix, followed by 8.9 with security enhancements and then 8.9.1.

And this keeps happening every once in a while where for a while it shows no updates even after multiple releases have occurred in the meantime and I end up downloading new version and manually installing it on top of the existing version, so then the built-in updater kind of defeats the purpose.

The current strategy with flagging new(er) versions as stable enough to be pushed could be fine if "auto-updater" would actually do the automated updates, but all it currently does is checking if there is a newer version and is prompting user to update. It basically works the same way as if user would manually check for updates, and in both cases I believe it should report existence of the new version if there is one.
If Notepad++ ever implements automatic updates (i.e. like browsers work) then it would have sense to be more conservative and only push those versions that have confirmed to be stable enough.
