### ISSUE TITLE
Using a Black Windows High Contrast Theme causes tabs to black out, etc

### ISSUE THREAD

**Issue by cookieboyeli** [notepad-plus-plus/notepad-plus-plus#1101]
Official WIndows High Contrast Theme Black:
![image](https://cloud.githubusercontent.com/assets/5998991/10994634/9ddcea80-8445-11e5-9e20-e1476b7277ac.png)

Custom WIndows High Contrast Theme:
![image](https://cloud.githubusercontent.com/assets/5998991/10994615/845b74a0-8445-11e5-91f8-2d09bef795a2.png)

Some disabled text is also displayed strangely:
![image](https://cloud.githubusercontent.com/assets/5998991/10994703/063b32f8-8446-11e5-8020-e074de755bb4.png)

An overall issue WIth Notepad++ and WIndows High Contrast is the Windows XP theme that Notepad++ still uses. It causes the white borders and XP themed buttons everywhere. 
The button style should obey your system version.

**Comment by Ede123** [comment]
I'm currently working on tabbar, so I can have a look at the issue with tabs. However I'd prefer to have feedback on #1075 by project members before putting any work in this.

**Comment by cookieboyeli** [comment]
Oh good, they were looking a bit out of line but I didn't want to nitpick. I took some time looking closely at the new and old examples you posted. I left some feedback for you. :)

**Comment by ZoomDomain** [comment]
Ok, i wrote a high contrast notepad theme generator so you can make 1000 high contrast notepad themes with random colors randomly in a second of processing time, some of the results are awesome:
http://forum.unity3d.com/threads/wrote-a-random-notepad-theme-generator.393215/

**Comment by skabala** [comment]
I'm also using High Contrast Black as my Windows 7 theme. (It helps me with eye-strain and remote viewing.) I see the same issue reported in the original post -- cannot read filename for the active tab because text and background are both dark. I am using Notepad++ v6.9.

**Comment by ZoomDomain** [comment]
depends on theme somewhat... 6 1 6 is awesome for my needs, it used to even work with function list,which was awesome, and recently we have ghe generator which is cool. 
![2016-04-01_185629](https://cloud.githubusercontent.com/assets/2262417/14214146/abffc884-f83b-11e5-9fb6-268b53a5a147.jpg)

![2016-04-01_185529](https://cloud.githubusercontent.com/assets/2262417/14214151/b255cdd2-f83b-11e5-94f4-a7878bfd5777.jpg)

**Comment by MetaChuh** [comment]
we are closing this issue due to its age and multiple newer notepad++ versions since it was filed.

please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html).
if your issue persists, and it is still of relevance to you, please feel free to file a new issue.

thank you for your help and best regards.

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
```
[<kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd>](https://notepad-plus-plus.org/community/)

**Comment by JamesO2x** [comment]
I'm running v7.9.1 and this still persists, using Windows High Contrast theme. The text for Notepad++'s tabs seems to be hard-code as black.

The tab text color should probably be pulling its value from the registry key: **ButtonText**. Specifically:
_HKEY_CURRENT_USER\Control Panel\Colors\ButtonText_

This is the value which determines the text color for any 3D objects (like buttons, windows, tabs) in win32 applications.

**Comment by InstantAli3n** [comment]
Thanks for reopening, 5 years later and it's unchanged just as JamesO2x has described above.
