### ISSUE TITLE
Not all duplicates are removed after removing duplicated lines

### ISSUE THREAD

**Issue by FilipSzm** [notepad-plus-plus/notepad-plus-plus#11024]
### Description of the Issue

When selecting only some of the lines in file and using remove duplicate lines not all of the duplicates are removed

### Steps to Reproduce the Issue

1. Open attached file
[message.txt](https://github.com/notepad-plus-plus/notepad-plus-plus/files/7841403/message.txt)
2. Select lines from 123 to 4122
3. Click 'Edit' in toolbar
4. Click 'Line Operations' in Edit menu
5. Click ' Remove Duplicate Lines' in Line Operations submenu

### Expected Behavior

Duplicates upon the line set spanned by the current selection are removed, and contents of opened file are identical to contents of file:
[message_removed.txt](https://github.com/notepad-plus-plus/notepad-plus-plus/files/7841429/message_removed.txt)

### Actual Behavior

for attached file `rs` in line 2618 is not removed despite being a duplicate

### Debug Information

Notepad++ v8.1.9.3   (64-bit)
Build time : Dec  6 2021 - 19:21:37
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 10 Pro (64-bit) 
OS Version : 2009
OS Build : 19042.1415
Current ANSI codepage : 1250
Plugins : mimeTools.dll NppConverter.dll NppExport.dll

**Comment by alankilborn** [comment]
In message.txt, `rs` appears on line 4123.  
Change that line to be `rs - orig 4123`.
Select fully lines 123 to 4122 (as per the original STR).
Do step 5 in STR.
Do a Find-all-in-current-document on `rs`.
It will appear on line 1514 and its next appearance is on line 2618 which contains `rs - orig 4123`.
So the `rs` on line 1514 was the first occurrence in the original selected text.
There are no other occurrences of `rs` from the original selected text remaining in the file.

Thus the problem statement is invalid and there does not appear to be a bug here.

**Comment by ArkadiuszMichalski** [comment]
@FilipSzm `Remove Duplicate Lines` operation means that one occurrence of this line (the first) will stay after finishing this operation. If you want to delete everything you can use `Replace` dialog with `In selection` checkbox and proper rules.

https://npp-user-manual.org/docs/editing/
`Remove Duplicate Lines: leaves only the first instance of any full lines that have more than one copy anywhere in the active file; acts upon the line set spanned by the current selection, or the entire file if no active selection`
