### ISSUE TITLE
Function list not work properly in python file

### ISSUE THREAD

**Issue by Racy** [notepad-plus-plus/notepad-plus-plus#11027]
### Description of the Issue

Function list not work properly in python file when write a class

### Steps to Reproduce the Issue

1.  When the end of the class does not end in CRLF, it do not show anything in functions list
![image](https://user-images.githubusercontent.com/1407229/148831665-2c8693b8-053d-402c-a3a3-25a1aac97063.png)
![image](https://user-images.githubusercontent.com/1407229/148831978-5bc928b8-cf67-4062-a948-ce1a2ca7537e.png)
![image](https://user-images.githubusercontent.com/1407229/148832243-b3f0c4eb-41b0-47b1-baa7-99fe0e71f4a4.png)

2.  Only show when the last line is CRLF or global function
![image](https://user-images.githubusercontent.com/1407229/148832084-22207ce3-e672-4e3e-97db-a599934dd13b.png)
![image](https://user-images.githubusercontent.com/1407229/148832702-c392f72f-5c15-4c6b-9f77-e1c4c7e0736b.png)

### Debug Information
Notepad++ v8.1.9.3   (64-bit)
Build time : Dec  6 2021 - 19:21:37
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 10 Pro (64-bit) 
OS Version : 2009
OS Build : 19044.1415
Current ANSI codepage : 1252
Plugins : none

**Comment by ArkadiuszMichalski** [comment]
Duplicate of Duplicate of https://github.com/notepad-plus-plus/notepad-plus-plus/issues/8814, https://github.com/notepad-plus-plus/notepad-plus-plus/issues/3095, https://github.com/notepad-plus-plus/notepad-plus-plus/issues/2910..

**Comment by nkern802** [comment]
this is a problem of the python.xml
