### ISSUE TITLE
function list have a bug when fonction's name is starting by "for"

### ISSUE THREAD

**Issue by bacomino** [notepad-plus-plus/notepad-plus-plus#1103]
Hello...
I found that "function list" is not working for PHP when fonction's name staring by "for".

Exemple : this simple code is returning "or123" as function's name)

```
<?php
function for123(){
    alert 'nothing';
}
?>
```

**Comment by Blitzdoctor** [comment]
Can confirm and expand, PHP functions starting with for, while and if do not show up in the function list.

**Comment by donho** [comment]
https://github.com/notepad-plus-plus/notepad-plus-plus/commit/60b4aa6b75c60b436d1f3a539cd75956fbb98b3e
