### ISSUE TITLE
macro "Style all occurrences of token" does not support regular expressions

### ISSUE THREAD

**Issue by Buger2022** [notepad-plus-plus/notepad-plus-plus#11034]
### Description of the Issue

1. Open the windows10 display settings, change portrait, 1080x1920, change the advanced text scaling settings, when it is set to 270.the replacement box of notepad++ is not displayed completely.
![20220112032953067.jpg](https://s2.loli.net/2022/01/12/4YrCPhqQbgis9uB.jpg)

2. Notepad++ records macros, finds and uses regular expressions, then Style all occurrences of token, using 1st style, saves macros. When this macro runs, only the first content matched by the regular expression has the background color.

### Steps to Reproduce the Issue

2:
test file:`test.html`

```
<html>
<title>test1</title>
<title>test2</title>
<title>test3</title>
</html>
```
1. crlt+f, open find
2. Start recording macro
3. Select the regular expression and find: `<title>.*</title>`
4. click the search in the menu bar with the mouse, Style all occurrences of token, using 1st style
5. Save the recorded macro

### Expected Behavior

I want when this macro run, all the content matched by the regular expression will show the background color.
Mark `ctrl+m` the recorded macro, all the content matched by the regular expression has a background color. Then I hope this macro also support regular expressions.

### Actual Behavior

`shortcuts.xml`,we got it
```
        <Macro name="regular expression mark" Ctrl="no" Alt="no" Shift="no" Key="0">
            <Action type="3" message="1700" wParam="0" lParam="0" sParam="" />
            <Action type="3" message="1601" wParam="0" lParam="0" sParam="&lt;title&gt;.*?&lt;/title&gt;" />
            <Action type="3" message="1625" wParam="0" lParam="2" sParam="" />
            <Action type="3" message="1702" wParam="0" lParam="768" sParam="" />
            <Action type="3" message="1701" wParam="0" lParam="1" sParam="" />
            <Action type="2" message="0" wParam="43022" lParam="0" sParam="" />
        </Macro>
```
This macro can save the color mark, but only the first search content shows the background color, because the search uses regular expressions, if you don't use regular expressions, just search `<title>`, then all `<title>` are displayed background color.

```
        <Macro name="no regular expression mark" Ctrl="no" Alt="no" Shift="no" Key="0">
            <Action type="3" message="1700" wParam="0" lParam="0" sParam="" />
            <Action type="3" message="1601" wParam="0" lParam="0" sParam="&lt;title&gt;" />
            <Action type="3" message="1625" wParam="0" lParam="2" sParam="" />
            <Action type="3" message="1702" wParam="0" lParam="768" sParam="" />
            <Action type="3" message="1701" wParam="0" lParam="1" sParam="" />
            <Action type="2" message="0" wParam="43022" lParam="0" sParam="" />
        </Macro>
```

### Debug Information

Notepad++ v8.2   (32-bit)
Build time : Dec 30 2021 - 03:36:49
Path : D:\npp\notepad++.exe
Command Line : D:\test.html
Admin mode : ON
Local Conf mode : ON
Cloud Config : OFF
OS Name : Windows 10 Enterprise (64-bit) 
OS Version : 2009
OS Build : 19044.1288
Current ANSI codepage : 936
Plugins : AutoSave.dll ComparePlugin.dll mimeTools.dll NppConverter.dll NppExec.dll NppExport.dll NPPJSONViewer.dll

**Comment by alankilborn** [comment]
This issue is fairly incomprehensible.
For starters, on a high level, it contains two separate and totally different problem descriptions.
I'd start by separating these into 2 issues.
Perhaps move the first one into a completely new issue, because at least the second one seems to go with the title of this issue.

**Comment by alankilborn** [comment]
Next, judging the second part of the issue solely by the issue title `"macro "Style all occurrences of token" does not support regular expressions`, I'd respond with:

The "Style all..." function does not support regular expressions, by design, and that isn't likely to change.

**Comment by donho** [comment]
"Style all occurrences of token" does not support regular expression but only the selected word(s).
Use "Mark" in Find dialog - it supports not only regular expression, but works also with recording/play macro.
