### ISSUE TITLE
Taskbar icon now unrecognisable

### ISSUE THREAD

**Issue by cor-of-org** [notepad-plus-plus/notepad-plus-plus#11032]
### Description of the Issue
The taskbar icon is no longer recognisable. It's just a wee blob of some sort.

### Steps to Reproduce the Issue
1. Upgrade Notepad++

### Expected Behaviour
To be able to see and recognise Notepad++ in my taskbar.

### Actual Behaviour
I got a tiny half-icon thing.

![Notepad++ Icon](https://user-images.githubusercontent.com/12812552/148942952-e14eba51-9a9b-49f9-b3a4-1095ee1b26de.png)

**Comment by donho** [comment]
This bug is closed due to lack of info.
If you just complain "xxx feature doesn't work for me", we cannot solve your problem because of lack of info.
Please provide the Debug Info (via menu "? > Debug Info"), and your configurations, not only a screenshot.

**Comment by cor-of-org** [comment]
Wow.

Okay, here it is..

Notepad++ v8.2   (64-bit)
Build time : Dec 30 2021 - 03:40:42
Path : C:\Program Files\Text Ed\Notepad++\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 10 Pro (64-bit) 
OS Version : 2009
OS Build : 19044.1415
Current ANSI codepage : 1252
Plugins : AnalysePlugin.dll BigFiles.dll ComparePlugin.dll DSpellCheck.dll Explorer.dll HTMLTag.dll JSMinNPP.dll LanguageHelp.dll Linefilter3.dll Merge files in one.dll mimeTools.dll NavigateTo.dll NppConverter.dll NppDocShare.dll NppExec.dll NppExport.dll NppQrCode64.dll NppSaveAsAdmin.dll NppSnippets.dll NppTaskList.dll NppTextViz.dll NppToolBucket.dll NppXmlTreeviewPlugin.dll pork2sausage.dll Remove Duplicate Lines.dll RunMe.dll selectNLaunch.dll SessionMgr.dll zoomdisabler_x64.dll _CustomizeToolbar.dll
