### ISSUE TITLE
this file has been modified by another program.  would you like to reload it?

### ISSUE THREAD

**Issue by i300220** [notepad-plus-plus/notepad-plus-plus#1104]
Hi,

Sometimes, I use sed to perform a global search and replace on a batch of files already opened in notepad++

When I return in notepad++, I get a ton of similar windows like the title describes.  

Could we have something to accept all of them once for all instead of one by one (It's not uncommon that I have hundreds of files where I've changed something like "find . -name _rss\*.php -exec sed -i 's/5px -12px/5px -17px/g' {} \;"

See attachment for clarity.

Thanks in advance.
![clipboard01](https://cloud.githubusercontent.com/assets/15702355/11014781/6aa5d39c-8513-11e5-8111-dbb4ea592d11.jpg)

**Comment by i300220** [comment]
Hi,

I've been using notepad++ for years on several computers.  Never been able to print a single sheet of paper out of it.  Absolutely nothings happens.  Only workaround is to save the file to disk and Open the file in another program to print it.  Using XP, and Win 7 as computers.  I own 4 of them.  None of them would print any notepad++ document.

Thanks in advance.

**Comment by dail8859** [comment]
Have you tried using the `Update Silently` option?

**Comment by i300220** [comment]
It's impossible to access the menu.  As soon as I close that pop-up, another opens with a new file name, asking the same question over and over again until all updated files are exhausted.

That is a major annoyment.

**Comment by dail8859** [comment]
Go into Settings / Preferences / MISC. and select update silently.

**Comment by i300220** [comment]
Makes sense.  Thanks again.
