### ISSUE TITLE
Reason why it asks for sourceannotations.h

### ISSUE THREAD

**Issue by modz2014** [notepad-plus-plus/notepad-plus-plus#11045]
hi i cant figure why it fails to build with this file its not include nor is in the winsdk10 can some one tell me

**Comment by mere-human** [comment]
What is this about?
Please, use issue template




### Description of the Issue


### Steps to Reproduce the Issue

1. 
2. 
3. 

### Expected Behavior


### Actual Behavior


### Debug Information
