### ISSUE TITLE
Taskbar icon now unrecognisable

### ISSUE THREAD

**Issue by cor-of-org** [notepad-plus-plus/notepad-plus-plus#11042]
### Description of the Issue

The taskbar icon is no longer recognisable. It's just a wee blob of some sort.

### Steps to Reproduce the Issue

1. Upgrade Notepad++

### Expected Behavior

To be able to see and recognise Notepad++ in my taskbar

### Actual Behavior

I got a tiny half-icon thing.

### Debug Information
Notepad++ v8.2 (64-bit)
Build time : Dec 30 2021 - 03:40:42
Path : C:\Program Files\Text Ed\Notepad++\notepad++.exe
Command Line :
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 10 Pro (64-bit)
OS Version : 2009
OS Build : 19044.1415
Current ANSI codepage : 1252
Plugins : AnalysePlugin.dll BigFiles.dll ComparePlugin.dll DSpellCheck.dll Explorer.dll HTMLTag.dll JSMinNPP.dll LanguageHelp.dll Linefilter3.dll Merge files in one.dll mimeTools.dll NavigateTo.dll NppConverter.dll NppDocShare.dll NppExec.dll NppExport.dll NppQrCode64.dll NppSaveAsAdmin.dll NppSnippets.dll NppTaskList.dll NppTextViz.dll NppToolBucket.dll NppXmlTreeviewPlugin.dll pork2sausage.dll Remove Duplicate Lines.dll RunMe.dll selectNLaunch.dll SessionMgr.dll zoomdisabler_x64.dll _CustomizeToolbar.dll

![148942952-e14eba51-9a9b-49f9-b3a4-1095ee1b26de](https://user-images.githubusercontent.com/12812552/149377444-7aa89e26-ba88-4db9-a4a8-7e2dd6e3cad7.png)

If you need any more information please, JUST ASK.

**Comment by dfs-** [comment]
Looks like it's not a Notepad++ issue, but seems like your Icon Cache is corrupted. Can you try the solutions provided here:
https://www.tenforums.com/general-support/36894-taskbar-icons-get-corrupted.html

**Comment by cor-of-org** [comment]
I have an app for that. Then a quick toggle of the pinning and I have the document+pencil icon. Much easier to navigate to. Thanks!
