### ISSUE TITLE
Folder workspace background color suggestion.

### ISSUE THREAD

**Issue by BloodElf** [notepad-plus-plus/notepad-plus-plus#11040]
Hello developer! I want to suggest an improvment.

When I use the folder workspace the background is so white and my eyes felt hurt.

I hope you can fix it or let user to define the background of the folder workspace.

thank you!

![image](https://user-images.githubusercontent.com/5360927/149300755-ffe3863d-a7b3-4119-860a-9b1ae127ef8f.png)

**Comment by Ekopalypse** [comment]
Use the default background option instead??
![image](https://user-images.githubusercontent.com/47723516/149301999-721e61e1-458e-4cbf-b2c9-5ad3572f5f4b.png)

**Comment by BloodElf** [comment]
thank you! I got it!
