### ISSUE TITLE
TYPO: Change 'your' to 'you' in README.md

### ISSUE THREAD

**Issue by TheOnlyWayUp** [notepad-plus-plus/notepad-plus-plus#11058]
### Description of the Issue
There's a spelling mistake [over here](https://github.com/notepad-plus-plus/notepad-plus-plus/blob/master/README.md#:~:text=some%20rules%20that-,your,-should%20follow%20to) in the readme.

I also believe rewriting this sentence altogether would be more beneficial as it looks incredibly janky at the moment.

Possibly change 
`Code contribution is welcome. Here are some [rules](CONTRIBUTING.md) that your should follow to make your contribution accepted easily.` 

to -

`Contributions are welcome. Be mindful of our [Contribution Rules](CONTRIBUTING.md) to increase the likelihood of your contribution getting accepted.`

**Comment by jbarryfl** [comment]
Could you assign this to me? I'd love to fix this, it would be my first contribution and would be a great way to familiarize myself with the codebase.

**Comment by thomassmith311** [comment]
The comma in your proposed change is grammatically incorrect. Two full sentence clauses ("contributions are welcome" and "be mindful of our contribution rules to increase the likelihood of your contribution getting accepted") need to be separated by 1) a semicolon, 2) a comma + conjunction, like "and", or 3) a period (thus making two independent sentences).

Source https://www.grammarly.com/blog/comma/ (this is called a comma splice).

**Comment by TheOnlyWayUp** [comment]
> The comma in your proposed change is grammatically incorrect. Two full sentence clauses ("contributions are welcome" and "be mindful of our contribution rules to increase the likelihood of your contribution getting accepted") need to be separated by 1) a semicolon, 2) a comma + conjunction, like "and", or 3) a period (thus making two independent sentences).
> 
> Source https://www.grammarly.com/blog/comma/ (this is called a comma splice).

Thanks for pointing this out. I've edited the comment to change
`Contributions are welcome, be mindful of our [Contribution Rules](CONTRIBUTING.md) to increase the likelihood of your contribution getting accepted.`
to
`Contributions are welcome. Be mindful of our [Contribution Rules](CONTRIBUTING.md) to increase the likelihood of your contribution getting accepted.`

**Comment by alankilborn** [comment]
@TheOnlyWayUp Editing your original posting in this thread made @thomassmith311 's comment nonsensical (unless one bothers to look at the revision history).  The better way to do it would have been to leave the original alone and post corrections in your followup.

**Comment by TheOnlyWayUp** [comment]
Got it, what do I do now? if I revert it back and make a new comment, your comment will look nonsensical.

**Comment by alankilborn** [comment]
>what do I do now?

Nothing.
