### ISSUE TITLE
Dark mode Campare plugin colors

### ISSUE THREAD

**Issue by tadaspat** [notepad-plus-plus/notepad-plus-plus#11059]
Could dark mode Compare function colors be modified so the text would be more visible?
![2022-01-19 13_42_51-Photos](https://user-images.githubusercontent.com/98051207/150194202-d4a9aa91-045e-4bf5-98fa-b6d8d4915b7e.png)

**Comment by dail8859** [comment]
This is related to a plugin that is not supported by the Notepad++ project.

I think this project is the better place to have your issue addressed.

https://github.com/pnedev/compare-plugin/issues

**Comment by chcg** [comment]
@tadaspat The compare plugin has a settings page where the colours could be changed but just as global setting and not dark mode specific.
