### ISSUE TITLE
Can't change active tab background color from fuggly grey

### ISSUE THREAD

**Issue by dbareis** [notepad-plus-plus/notepad-plus-plus#11051]
### Description of the Issue
I've tried multiple preferences but none seem to affect the behaviour that clicking the background colors in the "Style configurator" doesn't do anything.  

### Steps to Reproduce the Issue
Happens all the time.

### Expected Behavior
I'd expect it to display the background color selection as happens for the foreground color and if it is disabled for some reason it should tell me why (and how to fix it) before or after clicking it and/or not be visible if it's an invalid option (for example , if changing foreground text colors).

### Actual Behavior
Clicking the background color does nothing.

### Debug Information
Notepad++ v8.1.9.3   (64-bit)
Build time : Dec  6 2021 - 19:21:37
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : "D:\DBAREIS\FamilyTree\FAG (cemetery visits)\Vic\Bunurong Memorial Park, Dandenong, (very pretty place with lake)\John William Fisher.GenealogyResearch"
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 10 Pro N (64-bit) 
OS Version : 2009
OS Build : 19044.1466
Current ANSI codepage : 1252
Plugins : mimeTools.dll NppConverter.dll NppExport.dll 

![Can't change active tab background color from fuggly grey](https://user-images.githubusercontent.com/295230/149846224-a545347d-2197-4274-ad38-b0a45c41530f.png)

**Comment by thomassmith311** [comment]
This isn't a bug or glitch, it just isn't a valid option. The grey is not the color but rather "greyed-out".

**Comment by dbareis** [comment]
So consider it a suggestion, I spent ages trying to work this out.  And why shouldn't I be able to set that anyway? Apart from the language bug this is the thing that anoys me most out of all of this apps "quirks".

**Comment by ArkadiuszMichalski** [comment]
@donho 
Looks like there is a regression introduced in 8.1.3. All foreground/background colour box that we can't change should be greyed, but now they don't.

This is how it looked like before, e.g. in 8.1.2:
![image](https://user-images.githubusercontent.com/2730894/150113108-edecba08-afc9-4082-988d-c5382008730c.png)

**Comment by donho** [comment]
@ArkadiuszMichalski 
Indeed, it's a regression.
Thank you for pinging me for this issue!
