### ISSUE TITLE
Updated to recent

### ISSUE THREAD

**Issue by derrickhawkins** [notepad-plus-plus/notepad-plus-plus#11055]
### Description of the Issue

All the time when I write notes in the app it autumatically saves it when i close the app. THis time it did not. Is that a new feature that all  explicitly save each session(s)
Notepad++ v8.1.9.3   (64-bit)
Build time : Dec  6 2021 - 19:21:37
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 10 Pro (64-bit) 
OS Version : 2009
OS Build : 22533.1001
Current ANSI codepage : 1252
Plugins : mimeTools.dll NppConverter.dll NppExport.dll

**Comment by alankilborn** [comment]
Verify this setting tick in "Settings" menu > "Preferences...":

![image](https://user-images.githubusercontent.com/77065706/183162250-94344316-f65b-448f-93aa-136f2e8d903d.png)

Recommend CLOSURE of this item.

**Comment by ArkadiuszMichalski** [comment]
If the problem still exists, let me know.
