### ISSUE TITLE
Clear Function List search filter on Escape

### ISSUE THREAD

**Issue by vinsworldcom** [notepad-plus-plus/notepad-plus-plus#11063]
### Description of the Issue
Currently, ESCAPE in the function list search clears the search and ESCAPE in the function list tree sets focus to Notepad++ Scintilla editing component.  But, ESCAPE from the function list tree should also clear the function list search to repopulate the entire function list tree structure since ESCAPE is presumably used to return focus to the Notepad++ component after not "using" the function list.  If one had found what they wanted from a search, they would use "ENTER" or double click to goto that function in the Notepad++ Scintilla component and keep the filtered view if any.

### Steps to Reproduce the Issue

1. Open a document that populates the function list
2. Use the function list search to narrow down the full list to a filtered view
3. Click in the tree view to set focus there
4. Press ESCAPE

### Expected Behavior
Focus should go to Notepad++ Scintilla editing component AND function list search filter should be cleared restoring the full function list view.

### Actual Behavior
Focus should go to Notepad++ Scintilla editing component BUT function list search filter is still applied.

### Debug Information
Notepad++ v8.2.1   (64-bit)
Build time : Jan 19 2022 - 18:43:05
Path : C:\usr\bin\npp64\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : ON
Cloud Config : OFF
OS Name : Windows 10 Enterprise (64-bit) 
OS Version : 2009
OS Build : 19042.1466
Current ANSI codepage : 1252
Plugins :

**Comment by donho** [comment]
I just tested in the master, after ESC key function list search filter IS cleared and the full function list view IS restored.
Is it not your case?

**Comment by vinsworldcom** [comment]
@donho Depends where your focus is when you press ESC.  If your focus is in the function list search box, then yes, the search is cleared and the full function list is restored unfiltered.  If however, you have a filter applied and your focus is in the tree view of the function list, pressing ESC sets the focus to the Scintilla editing component and the filtered search list stays as-is.

My thought is if you are ESC'ing, from function list to get back to editing, you don't want the filter anymore.  If you indeed filter and find the function you want, you would click it or press ENTER on it and get taken to that function in the Scintilla editing component - function list search filter still applied.

My real preference would be anytime exiting the function list - any filter is cleared and the full function list is viewed.  I like to use the filter to quickly find a function, but I always want all functions visible.  That may just be my preference though.  So this change only partially implements that - clearing filter if you ESC out of function list. Filter stays applied if you click or ENTER a function name to be taken there.

Hope this clears it up.

Cheers.

**Comment by donho** [comment]
@vinsworldcom 
I do believe there are some users need only ESC for switching to edit zone but keeping the filter and filtered entries.
But let's see the reaction of people for this way.

**Comment by vinsworldcom** [comment]
@donho thanks.  I think this PR strikes the right balance between leaving filtered entities and clearing it when there are no matches.
