### ISSUE TITLE
npp 6.8.n: Ctrl-Tab moves to the top of document

### ISSUE THREAD

**Issue by magnush0lm** [notepad-plus-plus/notepad-plus-plus#1106]
At some point in time the ctrl-tab behavior has changed.

Earlier, the position in an open document (line+char position) would be kept when switching between documents. Now the position/cursor is moved to line 1 when switching. This is incredibly irritating, especially when editing 1000+ lines documents. A lot of time is lost navigating.

Please revert to the old behavior.

**Comment by dail8859** [comment]
It is a known bug with XML Tools. Either install the new version from their website or try turning off "Set XML type automatically".
