### ISSUE TITLE
arm64 version string

### ISSUE THREAD

**Issue by chcg** [notepad-plus-plus/notepad-plus-plus#11068]
### Description of the Issue
From code inspection arm64 is missing in the platform information and therefore also the version string doesn't contain 64bit attribute.

See https://docs.microsoft.com/en-us/windows/win32/api/sysinfoapi/ns-sysinfoapi-system_info

### Steps to Reproduce the Issue
Check debug info text

### Expected Behavior
OS Name : Windows 10 Pro (64-bit)

### Actual Behavior
OS Name : Windows 10 Pro (Unknown-bit)

### Debug Information
N/A

**Comment by donho** [comment]
@chcg 
I have no ARM device for testing, but it seems `getWinVerBitStr()` return the right info (ie. 64 bits) on DebugInf box under ARM system:
https://github.com/notepad-plus-plus/notepad-plus-plus/issues/10640

**Comment by chcg** [comment]
I expected the info at the wrong place. It is used for OS Name. I corrected the description above, see debug info of #10640
