### ISSUE TITLE
User sees different amount of lines to npp (Line Operations)

### ISSUE THREAD

**Issue by ThatScar** [notepad-plus-plus/notepad-plus-plus#11065]
### Description of the Issue
The user sees a line break regardless of the EOL type (not the issue.)
Line Operations treat lines based on current file EOL type (not the issue.)
The user sees a different amount of lines to what Line Operations sees (ex.: in mixed EOL content), resulting in unexpected behaviour from Line Operations.

### Steps to Reproduce the Issue
Use mixed EOL content like this:
c[CR][LF]b[LF]a
See 3 lines.
Make sure notepad recognises this file as having EOL "Windows (CR LF)" (should be by default)
*
Use Edit -> Line Operations -> Sort Lines Lexicographically Ascending
See 3 lines that do not look sorted:
b
a
c

*If you remove the first line (reading "c"), there's no more mixed EOL content (only LF) but Sort Lines will still not sort (still set to CR LF).

### Expected Behavior
All _visible_ lines sorted

### Actual Behavior
Some _visible_ lines are left as they were without being sorted.

A lot of ways to address this - introducing more clarity can help change expectations to align with reality.

**Comment by alankilborn** [comment]
This boils down to be a complaint against line sort, so:

Duplicate; the master issue for this seems to be #7735

**Comment by ThatScar** [comment]
That is it, thank you.
I would like to mention that it's not just sorting but other Line Operations as well.
Closing as duplicate of #7735.
