### ISSUE TITLE
@sasumner, I apologize, I wasn't clear. I don't just want to change the dialog box text, I want to actually change the way it works.

### ISSUE THREAD

**Issue by 12farhanzakaria** [notepad-plus-plus/notepad-plus-plus#11079]
@sasumner, I apologize, I wasn't clear. I don't just want to change the dialog box text, I want to actually change the way it works.

The current options are:
1. Don't auto-fill the `Find` dialog box, _or_
2. Auto-fill it, even if you don't have anything selected.

I would prefer that one of the options would be:
1. If text is selected, auto-fill, otherwise, don't auto-fill.

_Originally posted by @pbarney in https://github.com/notepad-plus-plus/notepad-plus-plus/issues/3243#issuecomment-777582180_

**Comment by donho** [comment]
Create a new issue with the accurate info.
