### ISSUE TITLE
completion doesn't work

### ISSUE THREAD

**Issue by boris-999** [notepad-plus-plus/notepad-plus-plus#11073]
### Description of the Issue
completion pop-up, pops, i can cursor keys/up-down, but when i hit enter to select an item, it's just ignore, the pop-up is dismissed but i has not done any completion.

only started seeing this in v8.2.1

**Comment by alankilborn** [comment]
>only started seeing this in v8.2.1

Anybody ever read release notes when updating to a new version?
https://community.notepad-plus-plus.org/topic/22425/notepad-v8-2-1-release
Hmm, point 3 seems relevant.

**Comment by boris-999** [comment]
I don't that release note was very clear about a change of behaviour.  It says `add an option..`  nothing is very optional when default behaviour is forceable changed on you.  Point #11 is also relevant... regression.

**Comment by jbostoen** [comment]
Glad I stumbled upon this, I would also call changing this kind of default behavior a regression.

Also didn't see the release notes, I did a quick auto-update.

**Comment by alankilborn** [comment]
>I would also call changing this kind of default behavior a regression

I call it improving the software by providing a fix for a long standing "bug".

>Also didn't see the release notes, I did a quick auto-update.

That's on you.
