### ISSUE TITLE
Target directory for the installation is ignored in silent mode

### ISSUE THREAD

**Issue by J-U-B** [notepad-plus-plus/notepad-plus-plus#11072]
### Description of the Issue
The installer of version **8.2.1** ignores the provided target directory in silent mode.

### Steps to Reproduce the Issue
```
notepadpp-8.2.1-x64.exe /S /D="C:\Program Files\NPP"
```

### Expected Behavior
The program should be installed in the target directory `C:\Program Files\NPP`

### Actual Behavior
The program is always installed in the directory `C:\Program Files\Notepad++`, no matter which target directory is specified.
This behavior has only started with version 8.2.1.

**Comment by dail8859** [comment]
According to the [NSIS documentation](https://nsis.sourceforge.io/Docs/Chapter3.html):

> /D sets the default installation directory ($INSTDIR), overriding InstallDir and InstallDirRegKey. It must be the last parameter used in the command line and **must not contain any quotes**, even if the path contains spaces. Only absolute paths are supported.

Does removing the spaces solve the issue?

**Comment by dail8859** [comment]
This is also documented in the Notepad++ User Manual [here](https://npp-user-manual.org/docs/command-prompt/#installer-options)

**Comment by J-U-B** [comment]
My original script version had no quotes and it didn't work there either.
I just tried 
```
notepadpp-8.2.1-x64.exe /S /D=C:\Program Files\NPP
```
by hand with  the same result as before. The software will be installed at `c:\Program Files\Notepad++`

**Comment by J-U-B** [comment]
The problem still exists in **8.3**.
At least in *silent mode* the software will aways be installed in `c:\Program Files\Notepad++`.

```
notepadpp-8.3-x64.exe /S  /D=C:\Program Files\NPP\
```

results in install location: `c:\Program Files\Notepad++`

(Until this is fixed, I have to suspend the update of [OPSI_notepadpp](https://github.com/J-U-B/OPSI_notepadpp)/)

**Comment by natiT** [comment]
I can confirm that the Parameter is ignored from the setup.

**Comment by dail8859** [comment]
Issue has been identified by @xomx 

https://community.notepad-plus-plus.org/topic/22495/d-programdata-notepad-not-working

**Comment by xomx** [comment]
I am going to do a PR for this, when I find a time for testing.

**Comment by natiT** [comment]
Thank you for your contribution :)

**Comment by xomx** [comment]
Could you please test both installers from:
http://redwoodal.sweb.cz/NotepadPlusPlus/NppTestInstaller_issue11072.7z

**Comment by J-U-B** [comment]
@xomx Thank you.
Now both installers deliver the software to the desired location.
