### ISSUE TITLE
[Feature request] Pacdoc integration for better text export

### ISSUE THREAD

**Issue by Alekwk** [notepad-plus-plus/notepad-plus-plus#11077]
Please consider integrating Pandoc into N++, for exporting to pdf, epub, and others.

https://github.com/jgm/pandoc

**Comment by dail8859** [comment]
That seems to be a rather complex tool to be integrated by default into Notepad++. Your best option would be to look at integrating it by calling the command line tools, or potentially as a plugin. This kind of thing could be discussed on the Notepad++ Community forum page.
