### ISSUE TITLE
Base64 encoded json file syntax highlighting is unreadable

### ISSUE THREAD

**Issue by kotenok2000** [notepad-plus-plus/notepad-plus-plus#11076]
### Description of the Issue

Linked file syntax highlighting is unreadable
[bitburnerSave_BN1x1_1628187604.zip](https://github.com/notepad-plus-plus/notepad-plus-plus/files/7929873/bitburnerSave_BN1x1_1628187604.zip)

### Steps to Reproduce the Issue

1. Unzip attached  zip file
2. open bitburnerSave_BN1x1_1628187604.json

### Debug Information

Notepad++ v8.1.9.3   (64-bit)
Build time : Dec  6 2021 - 19:21:37
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : 
Admin mode : ON
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 10 Pro (64-bit) 
OS Version : 2009
OS Build : 22000.434
Current ANSI codepage : 1251
Plugins : ComparePlugin.dll DSpellCheck.dll HexEditor.dll mimeTools.dll NppConverter.dll NppExport.dll 

![Снимок экрана (117)](https://user-images.githubusercontent.com/8822292/150891420-3cc4eced-5688-438c-9146-028490e0601e.png)

**Comment by rdipardo** [comment]
### Option 1

Choose a different style theme (e.g. "DarkModeDefault"):

![b64_json_dm_deafult_theme](https://user-images.githubusercontent.com/59004801/150894267-498e4734-e56d-44d2-a6f1-6a0fa01e9ae1.png)

### Option 2

Change the default style of the JSON `ERROR` lexical class:

![b64_json_custom_default_theme](https://user-images.githubusercontent.com/59004801/150894299-46445397-444d-43bf-a695-8e7cae602e25.png)

**Comment by kotenok2000** [comment]
Can you look at my other issue?

**Comment by rdipardo** [comment]
https://github.com/notepad-plus-plus/notepad-plus-plus/issues/11075#issuecomment-1020752674
