### ISSUE TITLE
File content, not extension is used to determine if a file is a shortcut

### ISSUE THREAD

**Issue by Taemporus** [notepad-plus-plus/notepad-plus-plus#11089]
### Description of the Issue
Somewhat related topics have already been opened and closed (e.g. #9643 or #10139) which are about the behaviour with regards to `.lnk` files and if they or their target should be opened. This is NOT about that; it has been made clear repeatedly that the change is here to stay. It is at least consistent with most other Windows-based tools, so it makes sense.

However, this also happens when a Windows shortcut file has been renamed to no longer have the `.lnk` extension, which can be a problem in a number of ways — and this is in fact not even consistent with other tools either, like the basic built-in Notepad.

### Steps to Reproduce the Issue
1. Take/copy/create a shortcut file `test.lnk`.
2. Rename it to `test.txt` in e.g. the standard command prompt.
3. Open it with Notepad++ (either provide as a command line argument, drag & drop, use the open dialog, or the Open with Notepad++ context menu entry).

(Alternatively, download the attached `desktop.txt` file. WARNING: Notepad++ will attempt to open all files on the desktop, including iterating over the contents of any directories placed there.)

### Expected Behavior
The user sees a `.txt` file, Notepad++ sees one too. One would expect a _text editor_ to open the file _as text_, whatever the text content may be. If a file does not have the `.lnk` extension, Notepad++ should just open it as a regular file, same as most other Windows software do.

### Actual Behavior
Notepad++ seems to read the file, identify it as a WIndows shortcut, then proceed to open the target (or try to do so).

### Why this is a problem
The established behaviour of Windows is for the file extension to determine what the default action is. While `.lnk` files are shown as shortcuts, `.txt` files are not, and the OS doesn’t treat them as such either, regardless of their content. Whether or not a user has, say, extensions turned on in the default File Explorer, it will show the file type as a text file. Something shown as a text file is expected to be opened by a text editor regardless of if the content happens to be gibberish.

If a user has gone to the trouble of taking a shortcut, renaming it to no longer have the `.lnk` extension (which Windows deliberately makes hard to do), Notepad++ shouldn’t look over the file, say “oh, you must have accidentally renamed this shortcut to `not-a-shortcut.txt`, let me open the targeted `cmd.exe` for you instead” — or worse, try to open a directory it “points to” and everything inside it recursively, including following any shortcuts to other files or directories (whether with `.lnk` extension or not). One can even create an infinite loop that crashes the program when opening a seemingly innocuous TXT file: one with the contents of a shortcut pointing to, let’s say, a directory that contains another TXT file identical to the first… or two fake TXT shortcuts pointing to each other etc.

While it is unlikely someone would accidentally create such a text file (not least because it must include a whole lot of NUL characters) — though the attached `desktop.txt` file takes a grand total of 2 non-zero bits (and a fair number of zeros) after the obligatory LNK header for Notepad++ to try and open everything on your desktop — I can’t imagine someone would be happy to download a small TXT file `harmless.txt`, only for Notepad++ to try and go over and open their entire `C:\` drive when they double-click it.

### Debug Information
Notepad++ v8.2.1   (64-bit)
Build time : Jan 19 2022 - 18:43:05
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 10 Pro (64-bit) 
OS Version : 2009
OS Build : 19044.1466
Current ANSI codepage : 1252
Plugins : ComparePlugin.dll HexEditor.dll mimeTools.dll NppConverter.dll NppExport.dll RunMe.dll 

### Attachments
[desktop.txt](https://github.com/notepad-plus-plus/notepad-plus-plus/files/7946288/desktop.txt)

**Comment by kotenok2000** [comment]
It happens to me too.
Notepad++ v8.3.3   (64-bit)
Build time : Mar 13 2022 - 17:20:02
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : "E:\Downloads\desktop.txt"
Admin mode : ON
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 11 (64-bit) 
OS Version : 2009
OS Build : 22000.556
Current ANSI codepage : 1251
Plugins : ComparePlugin.dll DSpellCheck.dll HexEditor.dll mimeTools.dll NppConverter.dll NppExport.dll 

Fortunately npp is smart enough to ask for confirmation.
 
![Снимок экрана (158)](https://user-images.githubusercontent.com/8822292/160294278-fe014246-0813-4a94-8b4e-34e1804a9793.png)

**Comment by Taemporus** [comment]
Unless of course you only have e.g. a smaller (but presumably still significant) number of shortcuts on the desktop (or whatever place the txt-ified link pointed to), all of which point to applications, not directories. In which case, Notepad++ will quite happily follow each link and open tens of exe files, each in its own tab — all that just from the user trying to open a simple txt file.

Point is, weird things can happen in situations when the user definitely doesn't expect it, when they have no reason whatsoever to expect _anything_ strange to happen.

**Comment by rdipardo** [comment]
> If a user sees a text file because the OS sees a text file (and _not_ a shortcut), the editor should not overrule that.

Let's not forget to mention that __*no*__ software program should __*ever*__ display a binary data stream as editable text. 
And why does a full installation create a context menu option to "Edit with Notepad++" for executable files?

![open_exe_as_text](https://user-images.githubusercontent.com/59004801/160456845-0da32fa5-b7d0-401c-8be1-3a1cf26df29e.png)

**Comment by Taemporus** [comment]
@rdipardo That in itself is not that much of a problem, I think (though the explicit entry is questionable, it follows from how the entry is added to the registry, i.e. to the `*` key among the file associations, and _excluding_ it for specific file types would lead to endless debates on when exactly to do so, while it would also presumably require a dedicated shell extension DLL). The general pattern of deciding what to do with files in Windows goes like this (unless, of course, the application was directly invoked):

1. The OS looks at the extension.
2. It finds the program associated to that extension.
3. The program is called to perform its action on that file.

If a text editor is supplied a binary file, its only somewhat sensible action is try and represent it as text. Not that useful (hex editors are much more suitable for operating on binary files after all), but there is no real meaningful alternative either (within the scope of what the editor is expected to do; it definitely should not _run_ an exe file for instance), and there exist niche use cases. Other software (not text editors) may require files opened by them to have a special format, so they may refuse to open non-conforming files. But at least theoretically, any binary stream _could_ be text, and it is not up to the piece of software to decide whether this was the right application to open the file with. Once the user / OS has made the call, it should just try and open it.

As such, usually what the program should do is just open the file as text. One possible valid exception, as is the point of this issue, is when the software _does_ have something sensible to do with the file in its role as a text editor, e.g. when the file is a link to another file as determined by the OS. In Windows, this is customarily signified by the `.lnk` extension, and that is the only case when the OS itself will redirect an action. A file with the same content but a different extension does not qualify. So the editor may look at the extension and try to resolve the shortcut if it sees `.lnk`, but should not otherwise do so. (Ideally, it would, instead of just looking at the extension, make some suitable API call to the OS to see if _that_ would treat the file as a shortcut based on the extension in order to account for nonstandard configurations, but that is less important. )

**Comment by Sorontik** [comment]
@rdipardo 
> Let's not forget to mention that **_no_** software program should **_ever_** display a binary data stream as editable text. And why does a full installation create a context menu option to "Edit with Notepad++" for executable files?

I disagree.
Many binary formats (including .exe, .dll and many more) contain useful information that can be extracted when viewed as text file.
It rarely makes sense to EDIT binary files in a text editor, but there are situations, where even that can make sense, if you're in a pinch.

In fact, this is one of the main reasons, why I started to use NPP: because it allowed me to simply view the content of ANY file in a reliable manner, regardless of file type or format, and then let me worry about what to do with the content.


As a side-note:
Given the long history and wide spectrum of software programming, not to mention the unimaginable future, I don't think anyone can claim being an authority on what programs should or shouldn't "ever" do, so it might be a good idea to be very careful with absolute statements like that.

**Comment by xomx** [comment]
@donho 
I can easily fix (one src-line change) the behavior requested in this issue. So then e.g. a "file.lnk" renamed to "file.lnk.txt" will not be considered as a shortcut anymore in N++. This will also allow such a workaround - https://github.com/notepad-plus-plus/notepad-plus-plus/issues/13995#issuecomment-1675373803 .  What do you think?

**Comment by Taemporus** [comment]
@xomx That certainly is all I was asking for. This extra stuff that got mentioned afterward — being sidetracked by whether or not one should or should not (be able to) open binary files with a text editor — obfuscated the initially mentioned, very simple issue: there are files where if a user asks Notepad++ to open them, the software does something completely different from what they expect, with no way to tell beforehand without knowing the contents of the file.

A check to only try and treat a file as a shortcut if it has the .lnk extension solves that completely, since that is also exactly how the OS decides what to display as a shortcut.

**Comment by donho** [comment]
@xomx 
> So then e.g. a "file.lnk" renamed to "file.lnk.txt" will not be considered as a shortcut anymore in N++.

The thing is, if `*.txt` can change the behaviour, why not `*.ini` or `*.log`?

**Comment by xomx** [comment]
@donho 
I mean any other extension but `*.lnk`, `*.txt` was only an example.

I would use something like (C++20 ends_with is unfortunately case sensitive, so it will need a little bit different sln...):
```
if (!resolveLinkFile.ends_with(TEXT(".lnk"))
	return false;
```
at the start of the NppIO.cpp `resolveLinkFile`.

**Comment by donho** [comment]
OK, go ahead then.
Note that a text file `aTest.txt` can be rename to `aTest.txt.lnk`.
Please make sure that it can be opened as a text file and show its content.
