### ISSUE TITLE
Notepad++ seems to not fetch remote XSD declared in schema location

### ISSUE THREAD

**Issue by antoniolocandro** [notepad-plus-plus/notepad-plus-plus#11083]
Notepad++ seems to not fetch remote XSD declared in schema location

1. Open Notepad++
2.  Load the attached file
[20211104_Obstacles_Norway_Area1_CRC_800AF400.zip](https://github.com/notepad-plus-plus/notepad-plus-plus/files/7943520/20211104_Obstacles_Norway_Area1_CRC_800AF400.zip)
3.  Validate
4. following result is obtained
![image](https://user-images.githubusercontent.com/4627073/151207995-e49d9ef1-1031-4fdc-9cb3-b20c85e38c54.png)

The following options have been set
![image](https://user-images.githubusercontent.com/4627073/151208257-83843e3f-eb76-4508-9a3a-5758e38f71c6.png)

Notepad ++ version

![image](https://user-images.githubusercontent.com/4627073/151208637-1e2f34c4-7e0d-4a80-85d4-e24df4a91e86.png)

**Comment by dfs-** [comment]
XML Tools is a plugin and not Notepad++. Please post your issue in the XML Tools repository here: https://github.com/morbac/xmltools
