### ISSUE TITLE
[Regression] Remove 2GB file open restriction for x64 binary

### ISSUE THREAD

**Issue by ArkadiuszMichalski** [notepad-plus-plus/notepad-plus-plus#11080]
This change is quite large and may cause new problems. If anyone catches anything, let us know.

https://community.notepad-plus-plus.org/topic/22438/notepad-v8-2-2-release-candidate << RC for test

https://github.com/notepad-plus-plus/notepad-plus-plus/commit/961a133a6008bf2a664360691942ef95bc2710f2

@donho I have one:

- turn on `Enable session snapshot and periodic backup` in `Preferences > Backup`
- open `New` file and write something (don't save)
- close and open NPP once again

I get error:

![image](https://user-images.githubusercontent.com/2730894/151170505-b641a42c-7ff6-43c9-84a2-f06a53356967.png)

**Comment by ArkadiuszMichalski** [comment]
Maybe not regression, but definitely a performance issue: using `PageUP/PageDown` or `Ctrl+Home/Ctrl+End` is extremely slow on such large files. This is especially noticeable as we are somewhere further down in the file. Something on the Notepad++ side is wrong, because SciTE or Notepad2 have no problems on this case, regardless of the current cursor position.

**Comment by ArkadiuszMichalski** [comment]
@donho
Some advice from Notepad2 author https://github.com/notepad-plus-plus/notepad-plus-plus/issues/8802#issuecomment-687200365 how to improve handling of large files. Looks like update Scintilla to the never 5.x version might also help. 

https://github.com/zufuliu/notepad2/issues/125

Maybe some of these tips will be useful.

**Comment by donho** [comment]
@ArkadiuszMichalski 
> Edit: problem is with the Word wrap option turned on, I forgot about it. Maybe these changes will finally improve something.

The disabling Word Wrap is added in the latest commit: https://github.com/notepad-plus-plus/notepad-plus-plus/commit/edabe440008d5e324cdee890378df0696b8b0b4f

**Comment by ArkadiuszMichalski** [comment]
>The disabling Word Wrap is added in the latest commit: edabe44

It's rational, because with this option turned on, we basically can't do anything. The worst part is that even for files smaller than 2GB it is a big problem. We must remember that this option is problematic.

@donho Any thoughts why editing a large file in Notepad++ is so slow? I do the same at SciTE and the result is immediate.

**Comment by donho** [comment]
@ArkadiuszMichalski 
Smart Highlighting shouldn't have any impact here because it was considered the performance issue in the implementation - only the visible part is highlighted. It can be disabled anyway for the large file.

I just did another commit for disabling backup, auto_completion and word wrap when file size is over 200MB - so it should be better with these improvement. I'm doing another RC.  Please let me know it's better now.
