### ISSUE TITLE
add as official

### ISSUE THREAD

**Issue by huezo** [notepad-plus-plus/notepad-plus-plus#11085]
add as official

[https://snapcraft.io/notepad-plus-plus](https://snapcraft.io/notepad-plus-plus)

[https://github.com/mmtrt/notepad-plus-plus](https://github.com/mmtrt/notepad-plus-plus)

**Comment by rdipardo** [comment]
Similar to this (rejected) request:  https://github.com/notepad-plus-plus/notepad-plus-plus/issues/11002

**Comment by ArkadiuszMichalski** [comment]
These projects are independent and no one will take responsibility for them here.
