### ISSUE TITLE
The find / replace keeps defaulting to [In Selection]

### ISSUE THREAD

**Issue by StingyJack** [notepad-plus-plus/notepad-plus-plus#11084]
v8.1.9.3 and v8.2.1

STR:
Select some text to replace
Ctrl + H
replace dialog is opened

Actual: "In Selection" checkbox is checked
Expected: "In Selection" checkbox is not checked

Closing the window with the box unchecked does not save the preference, it keeps coming back as checked. I cant find a setting to make it unchecked by default.

**Comment by alankilborn** [comment]
>Select some text to replace

You probably have "too much" selected.
When you have a lot, it does what you are describing.

**Comment by StingyJack** [comment]
The selected text was `LIKE 'Dev_Aks_QC_%`

**Comment by alankilborn** [comment]
Tested in N++ 8.4.4 (current version as of this writing) and could not repro.
Recommend CLOSURE of this item.

**Comment by StingyJack** [comment]
Its definitely been fixed.
