### ISSUE TITLE
LexMarkdown vs UDL Markdown

### ISSUE THREAD

**Issue by pryrt** [notepad-plus-plus/notepad-plus-plus#11099]
In [this recent forum discussion](https://community.notepad-plus-plus.org/post/73416), a user pointed out that Scintilla has had LexMarkdown.cpp since 2010 -- and I see it's included in the Notepad++ source code as well (and has been since [NPP v7.2.2's update to Scintilla 2.20](https://github.com/notepad-plus-plus/notepad-plus-plus/commit/d4d42f8a1a29e067f63d7639f3e8e2dcbc1aab19#diff-2a858402685d93d75cc9cd7faf055d47e1cee6f93553e2d33261854d2133d8d2)).

I was surprised, because I'd always assumed the reason you started distributing Markdown as a UDL was that Scintilla had ignored that common text language; but now that I know it's in Scintilla and available to Notepad++, it makes me wonder why Notepad++ has never enabled the Markdown lexer.

Given the limitations of UDL compared to full built-in lexers, would it be possible to enable Scintilla's Markdown lexer, so that it's treated as a full Language rather than requiring use of the UDL?  If you don't want to enable it by default, is there a way for users to individually enable it without re-compiling?

**Comment by ArkadiuszMichalski** [comment]
In the past, LexMarkdown has produced worse results than UDL. They've [improved something](https://github.com/ScintillaOrg/lexilla/commits/master/lexers/LexMarkdown.cxx) about it since then, but not much. Some time ago I checked the results of both solutions, and the one from UDL was probably better.

https://github.com/notepad-plus-plus/notepad-plus-plus/pull/7792

**Comment by ArkadiuszMichalski** [comment]
For test actual LexMarkdown the most convenient way i to just download SciTE.

**Comment by pryrt** [comment]
Yeah, I experimented after making that "provides instructions" addition, and realized that the other topic was suggesting that you download the [pull-request build](https://github.com/notepad-plus-plus/notepad-plus-plus/wiki/Testing#using-a-pull-request-pr-build-version-of-notepad) from that PR... but PR builds don't get stored forever, and it's gone now.
