### ISSUE TITLE
Search result contains many repeat row

### ISSUE THREAD

**Issue by songtao542** [notepad-plus-plus/notepad-plus-plus#11090]
Search result contains many repeat row

![image](https://user-images.githubusercontent.com/5105572/151304177-b28d0ede-9241-49b5-8ea7-df00322a9d79.png)

**Comment by alankilborn** [comment]
It is not an issue, it is how it is designed to function.
One match is shown per output row.
If you want one row for multiple matches, do regular expression search for `abc.*` where the `abc` part is what you want to find.

**Comment by dail8859** [comment]
Closing since this is working as expected. If you have a smaller use-case with more details that demonstrates different behavior, please reopen.
