### ISSUE TITLE
The Link part of the Customized tone of the Dark Mode is not persistent.

### ISSUE THREAD

**Issue by vds2212** [notepad-plus-plus/notepad-plus-plus#11095]
### Description of the Issue
When you change the Link part of the Customized tone of the Dark Mode

![image](https://user-images.githubusercontent.com/160393/151420288-9b442367-169b-42d5-b331-8995559e7ac8.png)

It is not persistent.

### Steps to Reproduce the Issue

1.  Change the Link part of the Customized tone of the Dark Mode (see screen shot)
2.  Leave the application
3.  Restart the application
4.  Visit the Customized tone configuration

### Expected Behavior

The Link should be changed.

### Actual Behavior

The Link is not changed.

### Debug Information

Notepad++ v8.2.1   (32-bit)
Build time : Jan 19 2022 - 18:38:49
Path : C:\Softs\Notepad++\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : ON
Cloud Config : OFF
OS Name : Windows 10 Enterprise (64-bit) 
OS Version : 2009
OS Build : 19044.1469
Current ANSI codepage : 1252
Plugins : DSpellCheck.dll Explorer.dll FingerText.dll HexEditor.dll htmlcolor.dll IndentByFold.dll LanguageHelp.dll MenuIcons.dll mimeTools.dll NppConverter.dll NppExec.dll NppExport.dll NppOpenPath.dll NppTextFX.dll Python Indent.dll PythonScript.dll SpellChecker.dll _CustomizeToolbar.dll

**Comment by ArkadiuszMichalski** [comment]
Indeed, remembering doesn't work.
