### ISSUE TITLE
Command line file open with wildcard asterisk fails

### ISSUE THREAD

**Issue by vinsworldcom** [notepad-plus-plus/notepad-plus-plus#11098]
ORIGINALLY REPORTED HERE:  https://github.com/notepad-plus-plus/notepad-plus-plus/commit/2132505cba1895468231f582942aa9a292563b77#commitcomment-64777544

### Description of the Issue
2132505cba1895468231f582942aa9a292563b77 seems to have introduced a file-open-from-command-line regression. In previous Notepad++ up to and including the prior 2G restriction removal commit 961a133, opening from the command line with a wildcard asterisk worked:

PS VinsWorldCom ~\tmp > notepad++.exe C:\tmp\out.raw C:\tmp\out.txt out.cpp
Works fine. It's just when using the asterisk for wildcard that causes the crash in this commit, but not previous ones.

Cheers.

### Steps to Reproduce the Issue
```
PS VinsWorldCom ~\tmp > ls out.*
out.raw  out.txt  out.cpp
PS VinsWorldCom ~\tmp > notepad++.exe C:\tmp\out.*
```

With this commit, results in a silent crash - that is, the Notepad++ windows flashes on screen then closes - no error window or anything.

### Expected Behavior
```
PS VinsWorldCom ~\tmp > notepad++.exe C:\tmp\out.*
```

Should open all `out.*` files from the directory provided - as it does with previous version and new commits up to 2132505cba1895468231f582942aa9a292563b77, but not including that one.

### Debug Information
Notepad++ v8.2.1   (64-bit)
Build time : Jan 26 2022 - 17:41:07
Path : C:\Users\mvincent\Downloads\npp\notepad++.exe
Command Line : .\readme.txt .\license.txt
Admin mode : OFF
Local Conf mode : ON
Cloud Config : OFF
OS Name : Windows 10 Enterprise (64-bit) 
OS Version : 2009
OS Build : 19042.1466
Current ANSI codepage : 1252
Plugins : mimeTools.dll NppConverter.dll NppExport.dll

**Comment by donho** [comment]
@vinsworldcom 
Please confirm me if this issue has been fixed.

**Comment by vinsworldcom** [comment]
Commit db33083 did indeed fix the issue for me!

Thanks!
