### ISSUE TITLE
[GCC] Trying to open a large file in 32-bit  Notepad++ generates a crash

### ISSUE THREAD

**Issue by ArkadiuszMichalski** [notepad-plus-plus/notepad-plus-plus#11103]
On MSC compiler version when we try open too large file (but still less than 2GB) we get a Exception:
![image](https://user-images.githubusercontent.com/2730894/151639665-c2d17f22-31a3-4099-a4f9-09ca42570f60.png)
After closing this dialog we can continue working with NPP.

But on GCC compiler we get crash:
![image](https://user-images.githubusercontent.com/2730894/151639763-4d805999-376e-47d5-914a-1e85635ba965.png)

Can we somehow get a similar effect as in MSC (I mean catch the exception and continue working)?

```
Notepad++ v8.2.1   (32-bit)
Build time : Jan 29 2022 - 00:32:04
Built with : GCC 8.1.0
Path : D:\WebTools\GitHub\NPP\PowerEditor\gcc\bin.i686\notepad++.exe
Command Line : -multiInst
Admin mode : ON
Local Conf mode : ON
Cloud Config : OFF
OS Name : Windows 7 Ultimate (64-bit) 
OS Build : 7601.0
Current ANSI codepage : 1250
Plugins : none
```

**Comment by xomx** [comment]
This is coded in the `FileManager::loadFileData()` by the help of the MS specific extension to C/C++  `__try/__except`.
So maybe replacing by the C/C++ standard `try/catch` helps.

**Comment by ArkadiuszMichalski** [comment]
>@xomx
>So maybe replacing by the C/C++ standard try/catch helps.

For GCC it was done here [gcc-fixes.h](https://github.com/notepad-plus-plus/notepad-plus-plus/blob/master/PowerEditor/gcc/gcc-fixes.h) but still we have a crash.

>Just for the record - how big is the file you can successfully open in the 32-bit N++?

Same as you, close to 650MB, but this applies to all files (the sum of all files cannot exceed this value). Looks like this 2GB check limit is too big since even 1GB can't be opened. Later I will check other 32-bit Scintilla-based editors how it looks.

**Comment by xomx** [comment]
@ArkadiuszMichalski 

> For GCC it was done here [gcc-fixes.h](https://github.com/notepad-plus-plus/notepad-plus-plus/blob/master/PowerEditor/gcc/gcc-fixes.h) but still we have a crash.

Ok. But then it only means, that the `catch(...)` substitute in the [gcc-fixes.h](https://github.com/notepad-plus-plus/notepad-plus-plus/blob/master/PowerEditor/gcc/gcc-fixes.h) cannot catch the `throw` in:
```
if (_pscratchTilla->execute(SCI_GETSTATUS) != SC_STATUS_OK)
	throw;
```
If so, then maybe something like this will help:
```
int sciStatus = static_cast<int>(_pscratchTilla->execute(SCI_GETSTATUS));
if (sciStatus != SC_STATUS_OK)
	throw std::exception(((sciStatus == SC_STATUS_BADALLOC) ? "SC_STATUS_BADALLOC" : "SC_STATUS_FAILURE");
```

**Comment by ArkadiuszMichalski** [comment]
@donho 
I found that if a `throw` has a value, there is no crash also in GCC (for example `throw 0`).
https://github.com/notepad-plus-plus/notepad-plus-plus/blob/4077ec2f69030a8ce7df07b5131c04cedc64d3b3/PowerEditor/src/ScintillaComponent/Buffer.cpp#L1469
https://github.com/notepad-plus-plus/notepad-plus-plus/blob/4077ec2f69030a8ce7df07b5131c04cedc64d3b3/PowerEditor/src/ScintillaComponent/Buffer.cpp#L1537

I don't know what value should be throw in order not to change the current behavior in the MSC. 

Also, the 2GB limit for 32-bit seems too big, because even half of it cannot be handled. We can display a dialog box for files larger than 1GB (`IMAGE_FILE_MACHINE_I386/2`), instead of trying to open it and wait for the exception.

**Comment by xomx** [comment]
@ArkadiuszMichalski 


> I don't know what value should be throw in order not to change the current behavior in the MSC.

You can use my example for the MSC without problem (as I said - MS `__try/__except` catches any kind of exception):
```
int sciStatus = static_cast<int>(_pscratchTilla->execute(SCI_GETSTATUS));
if (sciStatus != SC_STATUS_OK)
	throw std::exception(((sciStatus == SC_STATUS_BADALLOC) ? "SC_STATUS_BADALLOC" : "SC_STATUS_FAILURE"));
```

> But @xomx has already mentioned that Notepad++ consume 2x more RAM for the file

This is no longer true for the files above 200MB (see the NPP_STYLING_FILESIZE_LIMIT in [Buffer.h](https://github.com/notepad-plus-plus/notepad-plus-plus/blob/master/PowerEditor/src/ScintillaComponent/Buffer.h)).
I just opened a 700MB file in the 32-bit N++ and it takes ~787MB only.

**Comment by ArkadiuszMichalski** [comment]
> I just opened a 700MB file in the 32-bit N++ and it takes ~787MB only.

For me 750MB file takes 830MB RAM (after stabilized). On fresh Notepad++ run we can open a single file with max size under 900MB (for me 890MB files takes 970MB RAM). Above this value we get an exception. Also when we try reopen such file we get an exception (only fresh run can handle such max size, next must be less than 850MB, at least in my case). 

This is still less than in SciTE, where I can open a single file smaller than 1.5GB.

**Comment by xomx** [comment]
@ArkadiuszMichalski @donho 

I have a good news for all the 32-bit N++ users - I just successfully opened a 1.4GB text file with only a little trick :-)
(SciTe is evidently using the same, I just checked the Sc446.exe binary, it is visible in its file Characteristic...)

So please do your own testing:
- open the current N++ project in MSVS
- build a x86 build (let's say the Release one)
- try to open e.g. a 1GB text file ... size exception, so you cannot open that
- go to back to the the MSVS
- go to the Notepad++ Project -> Properties -> Linker -> System -> EnableLargeAddresses and select:
  `Yes (/LARGEADDRESSAWARE)`
- rebuild a retest on the same large file ... now it opens without the exception :-)

I think you know, what is going behind (if not, Google for the x86 /3GB switch).

**Comment by ArkadiuszMichalski** [comment]
Looks like this was discussed on the past https://github.com/notepad-plus-plus/notepad-plus-plus/issues/681. Like @chcg [mentioned](https://github.com/notepad-plus-plus/notepad-plus-plus/issues/681#issuecomment-139812275), there may be disadvantages to this solution. I only checked the `-Wl, - large-address-aware` flag for GCC and now I can open a file smaller than 1.8GB, so even better than in SciTE. But should it be changed? I don't know, I don't work with such large files to catch potential problems. At least it's worth knowing why it works like that now.

**Comment by xomx** [comment]
I am using this flag in my somewhat large x86 multimedia SW bundle without problems. But there I have control over all the exe&dll used. I think that this will be the main N++ problem with the `LARGEADDRESSAWARE` (plugins). On the other hand - releasing such N++ binary could reveal all the '2GB+ files/memory incompatible' plugins.

**Comment by ArkadiuszMichalski** [comment]
> (to be clear, I am not for such exchange - somewhat larger files instead of otherwise fully functional plugins).

Such a change had already been rejected https://github.com/notepad-plus-plus/notepad-plus-plus/pull/891#issuecomment-255581867.

When I have some time, I will check all plugins after these changes (at least when starting Notepad++) through [plug_crash](https://github.com/ArkadiuszMichalski/NPP_tools#plug_crash).

**Comment by donho** [comment]
:@xomx 
>  go to the Notepad++ Project -> Properties -> Linker -> System -> EnableLargeAddresses and select: Yes (/LARGEADDRESSAWARE)

Not mention to [the warning given in StackOverFlow](https://stackoverflow.com/questions/2288728/drawbacks-of-using-largeaddressaware-for-32-bit-windows-executables), one of my responsibilities is keeping the stability of Notepad++ releases. So no, we don't change the compiling/linking flag for gaining this feature. 

@ArkadiuszMichalski 
> Such a change had already been rejected #891 (comment).

I confirm. The decision is remained with the same argument - especially v8.2.2 x64 can open 2GB+ files now.

**Comment by donho** [comment]
@ArkadiuszMichalski 
If you can capture this exception by using GCC way, I won't reject the PR which uses `#if` to deal with the problem.

**Comment by ArkadiuszMichalski** [comment]
@donho Something like that, based on [this advice](https://github.com/notepad-plus-plus/notepad-plus-plus/issues/11103#issuecomment-1024921612)?
```cpp
if (_pscratchTilla->execute(SCI_GETSTATUS) != SC_STATUS_OK)
#if defined(__GNUC__)
	throw std::runtime_error(((_pscratchTilla->execute(SCI_GETSTATUS) == SC_STATUS_BADALLOC) ? "SC_STATUS_BADALLOC" : "SC_STATUS_FAILURE"));
#else
	throw;
#endif
```

Or just throw something simple, like `throw std::runtime_error("SC_STATUS_FAILURE");` or `throw "SC_STATUS_FAILURE";` or `throw SC_STATUS_FAILURE;`?

**Comment by xomx** [comment]
@donho 
Current N++ behavior is not accurate there (`FileManager::loadFileData`), because of it reports every Scintilla problem as it could be only the `SC_STATUS_BADALLOC` in the `__except(EXCEPTION_EXECUTE_HANDLER)`. Moreover as it intercepts any exception, the problem could be something completely different.
(besides there is the 'TODO:' written for that reason).

So it should be something like:
```
	__except(EXCEPTION_EXECUTE_HANDLER) //TODO: should filter correctly for other exceptions; the old filter(GetExceptionCode(), GetExceptionInformation()) was only catching access violations
	{
		int sciStatus = static_cast<int>(_pscratchTilla->execute(SCI_GETSTATUS));
		switch (sciStatus)
		{
			case SC_STATUS_BADALLOC:
				pNativeSpeaker->messageBox("FileTooBigToOpen",
					_pNotepadPlus->_pEditView->getHSelf(),
					TEXT("File is too big to be opened by Notepad++"),
					TEXT("Exception: File size problem"),
					MB_OK | MB_APPLMODAL);
				break;
			case SC_STATUS_FAILURE:
				// ... report likewise as in the above SC_STATUS_BADALLOC, e.g.:
				pNativeSpeaker->messageBox("FileOpeningProblem",
					_pNotepadPlus->_pEditView->getHSelf(),
					TEXT("File failed to open in Notepad++."),
					TEXT("Exception: Scintilla failure"),
					MB_OK | MB_APPLMODAL);
				break;
			case SC_STATUS_OK:
			default:
				// ... report GetExceptionCode() or similar here
				break;
		}
		
		success = false;
	}
```

**Comment by donho** [comment]
@ArkadiuszMichalski 
> Something like that, based on this advice?

I would say it's good for both case (MSVS & GCC)
```
if (_pscratchTilla->execute(SCI_GETSTATUS) != SC_STATUS_OK)
{
	...
	throw std::runtime_error(((_pscratchTilla->execute(SCI_GETSTATUS) == SC_STATUS_BADALLOC) ? "SC_STATUS_BADALLOC" : "SC_STATUS_FAILURE"));
}
```

But what @xomx has provided looks more accurate.
@xomx 
My question is, 
1. how to reproduce `SC_STATUS_FAILURE` case?
2. in the case of `SC_STATUS_OK` or `default`, what's happening?

**Comment by xomx** [comment]
@donho 

> 1. how to reproduce `SC_STATUS_FAILURE` case?

Just e.g. simulate this error - invalid negative `bufferSizeRequested` (aka the int overflow, I know that it cannot happen there nowadays, as this is now a int64 variable), this throws the `SC_STATUS_FAILURE`:
```
__try
	{
		// First allocate enough memory for the whole file (this will reduce memory copy during loading)
		_pscratchTilla->execute(SCI_ALLOCATE, WPARAM(-bufferSizeRequested));
```

The point is that the Scintilla has in its `ScintillaWin::WndProc` (".\scintilla\win32\ScintillaWin.cxx") this exception handler code:
```
try {
... the ScintillaWin::WndProc body ...
} catch (std::bad_alloc &) {
	errorStatus = SC_STATUS_BADALLOC;
} catch (...) {
	errorStatus = SC_STATUS_FAILURE;
}
```
So any other thrown C++ exception, than the `std::bad_alloc`, causes SC_STATUS_FAILURE.



> 2\. in the case of `SC_STATUS_OK` or `default`, what's happening?

I had it wrong there, but it should be the part, where a SEH-exception has been thrown instead (not a Scintilla C++ error, e.g. divide by zero ... 0xC0000094).

According to the Scintilla [Doc](https://www.scintilla.org/ScintillaDoc.html#ErrorHandling), a status in between 1-999 is the error state. So there is an attempt to adjust the __try-__except part (the `int sciStatus` there has been added to not repeat several times the same SCI_GETSTATUS Scintilla call):

```
	bool success = true;
	EolType format = EolType::unknown;
	int sciStatus = SC_STATUS_OK;
	TCHAR szException[128] = { 0 };
	__try
	{
		// First allocate enough memory for the whole file (this will reduce memory copy during loading)
		_pscratchTilla->execute(SCI_ALLOCATE, WPARAM(bufferSizeRequested));
		sciStatus = static_cast<int>(_pscratchTilla->execute(SCI_GETSTATUS));
		if ((sciStatus > SC_STATUS_OK) && (sciStatus < 999))
			throw std::runtime_error("Scintilla error");


...


			sciStatus = static_cast<int>(_pscratchTilla->execute(SCI_GETSTATUS));
			if ((sciStatus > SC_STATUS_OK) && (sciStatus < 999))
				throw std::runtime_error("Scintilla error");

...

	}
	__except(EXCEPTION_EXECUTE_HANDLER)
	{
		switch (sciStatus)
		{
			case SC_STATUS_OK:
				// it is not a Scintilla problem here, so report a possible SEH-exception instead
				_stprintf_s(szException, _countof(szException), TEXT("0x%X (SEH)"), ::GetExceptionCode());
				pNativeSpeaker->messageBox("FileOpeningException",
					_pNotepadPlus->_pEditView->getHSelf(),
					TEXT("Failed to open the file."),
					TEXT("Exception code: $STR_REPLACE$"),
					MB_OK | MB_APPLMODAL,
					0,
					szException);
				break;
			case SC_STATUS_BADALLOC:
				pNativeSpeaker->messageBox("FileTooBigToOpen",
					_pNotepadPlus->_pEditView->getHSelf(),
					TEXT("File is too big to be opened by Notepad++"),
					TEXT("Exception: File size problem"),
					MB_OK | MB_APPLMODAL);
				break;
			case SC_STATUS_FAILURE:
			default:
				_stprintf_s(szException, _countof(szException), TEXT("%d (Scintilla)"), sciStatus);
				pNativeSpeaker->messageBox("FileOpeningException",
					_pNotepadPlus->_pEditView->getHSelf(),
					TEXT("Failed to open the file."),
					TEXT("Exception code: $STR_REPLACE$"),
					MB_OK | MB_APPLMODAL,
					0,
					szException);
				break;
		}

		success = false;
	}
```

**Comment by donho** [comment]
@xomx 
Thank you for your explanation.

I agree for this part:
```
	__try
	{
		// First allocate enough memory for the whole file (this will reduce memory copy during loading)
		_pscratchTilla->execute(SCI_ALLOCATE, WPARAM(bufferSizeRequested));
		sciStatus = static_cast<int>(_pscratchTilla->execute(SCI_GETSTATUS));
		if ((sciStatus > SC_STATUS_OK) && (sciStatus <= 999))
			throw std::runtime_error("Scintilla error");
```

But what's the point of this part?
```
...


			sciStatus = static_cast<int>(_pscratchTilla->execute(SCI_GETSTATUS));
			if ((sciStatus > SC_STATUS_OK) && (sciStatus <= 999))
				throw std::runtime_error("Scintilla error");

...
```

**Comment by ArkadiuszMichalski** [comment]
@donho 
>But what's the point of this part?

There are two places when the status is checked and eventually `throw` .
https://github.com/notepad-plus-plus/notepad-plus-plus/issues/11103#issuecomment-1024916395

**Comment by donho** [comment]
@ArkadiuszMichalski 
OK I see. Thank you for pointing it out.

@xomx 
Could you provide a PR please? It'll not be in release v8.2.2 but in the next one.

**Comment by xomx** [comment]
@donho 


> Could you provide a PR please?

Ok.
