### ISSUE TITLE
install Plugin DSpellCheck generates a crash

### ISSUE THREAD

**Issue by KlausiD** [notepad-plus-plus/notepad-plus-plus#11104]
### Description of the Issue
after install Plugin DSpellCheck, the npp++ do not start!

### Steps to Reproduce the Issue

1. compile actual npp++  from 29.1.2021
2. open npp and install DSpellCheck Plugin
3. after install, by reopening npp npp++ crash

**Comment by xomx** [comment]
https://github.com/notepad-plus-plus/notepad-plus-plus/pull/11047#issuecomment-1023814476

**Comment by KlausiD** [comment]
ok, the same is also with m HEX Editor after switching to HEX-view.
So the error can be solved only in the plugin.
Are the developers of the plugins informed about this?

**Comment by xomx** [comment]
> Are the developers of the plugins informed about this?

Not yet, this is still under development.
But I have already mentioned that: https://github.com/notepad-plus-plus/notepad-plus-plus/pull/11047#issuecomment-1024048200
If you check also other N++ plugins, it will be great.

**Comment by KlausiD** [comment]
ok, when i find time i will test some more plugins.
Where should I report the results?
under this issues?

**Comment by xomx** [comment]
Yes, report it here.
Or you can then rename this issue to something more generic.

**Comment by ArkadiuszMichalski** [comment]
@KlausiD You can report directly to plugin author https://github.com/Predelnik/DSpellCheck.

**Comment by xomx** [comment]
@KlausiD 
Yes, it is better to do it the way  @ArkadiuszMichalski .
But please report it (a list of checked plugins by you) here too, so we have an overview.

**Comment by vinsworldcom** [comment]
The Compare plugin seems to crash when a compare is triggered.  It loads OK, that is Notepad++ loads fine with it enabled, but when Plugin => Compare => Compare is used, Notepad++ crashes.

This is the latest N++ AppVeyor build, 64-bit:

Notepad++ v8.2.1   (64-bit)
Build time : Jan 29 2022 - 14:26:54
Path : C:\usr\bin\npp64\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : ON
Cloud Config : OFF
OS Name : Windows 10 Enterprise (64-bit) 
OS Version : 2009
OS Build : 19042.1466
Current ANSI codepage : 1252
Plugins : AutoSave.dll BetterMultiSelection.dll ChangedLines.dll CodeAlignmentNpp.dll ComparePlugin.dll CustomizeToolbar.dll Explorer.dll GitSCM.dll JSMinNPP.dll MarkdownPanel.dll NppExec.dll NppFTP.dll NppMenuSearch.dll PythonScript.dll QuickText.dll SurroundSelection.dll TagLEET.dll XMLTools.dll ZoomDisabler.dll

**Comment by ArkadiuszMichalski** [comment]
@donho You should not automatically dissabled DSpellCheck for this release with some information why?  There will be a lot of reports again as before with other plugins that completely crashed Notepad ++. This plugin is very popular.

**Comment by xomx** [comment]
@vinsworldcom 
> The Compare plugin seems to crash when a compare is triggered

It is the same problem and place in code as in the DSpellCheck case. As soon as plugin authors recompile their plugins with the updated headers, everything will be ok. Here is the crash (assert) detail:

![plugin-assert](https://user-images.githubusercontent.com/13075183/151713248-df68b816-bab2-40c9-82c4-676755569bcb.png)

**Comment by donho** [comment]
I haved tested DSpellCheck, HexEdit & Compare plugins. All of them make Notepad++ x64 binary crash.
All of them will be excluded during the installation.
Thank you for your reports!

**Comment by xomx** [comment]
@vinsworldcom 

CSVQuery - confirmed, the same place and code (`SCI_GETTEXTRANGE`) as the other reported plugins here.

**Comment by vinsworldcom** [comment]
Yes I saw that too, opened an issue

https://github.com/jokedst/CsvQuery/issues/33

Cheers

**Comment by vinsworldcom** [comment]
I recompiled Compare with the new Scintilla.h and Sci_Position.h from latest Notepad++ repo and it's working fine.  I don't know how to test DSpellCheck since it uses CMake (no VS project files) nor can I test CsvQuery since it's C# and I don't know that well enough to understand if any porting is involved in the Scintilla gateway stuff other C# plugins seem to use.

I saw that a few other older plugins crash as well but recompiling them with the same header updates fixes them:

SpeechPlugin
QuickColorPicker
TagLEET

Cheers.

**Comment by pnedev** [comment]
@donho ,

I will update Compare plugin ASAP (perhaps later in the evening). If you hold a bit the new Notepad++ release you could include Compare in the plugins list as well. Thanks.

**Comment by donho** [comment]
@pnedev 
Good news!
Sure, v8.2.2 will come with the newest plugin-list.
I suppose the new version of Compare plugin will be `v2.0.2` ?

**Comment by pnedev** [comment]
Hi @donho ,
Yes, the new Compare plugin will be version 2.0.2

**Comment by xomx** [comment]
For the DSpellCheck plugin is really enough to update the Sci_Position.h, you can check that for yourself:
https://ci.appveyor.com/project/Predelnik/dspellcheck/build/job/tkm6y5f4l5e5b6gr/artifacts
I tested my simple [PR](https://github.com/Predelnik/DSpellCheck/pull/281) x64 artifact with different textfile sizes up to 5.26GB and DSpellCheck worked ok as before.

@donho 
The HexEditor case is not that simple, it will need a lot of changes. I do not think I will be able to prepare a stable PR for it in time (before the new N++ release). Maybe someone else with more time?

**Comment by donho** [comment]
@vinsworldcom 
> I saw that a few other older plugins crash Notepad++ only when they are activated / used - not on Notepad++ startup. but recompiling them with the same header updates fixes them:
>
> SpeechPlugin
QuickColorPicker
TagLEET

I can reproduce the crash of SpeechPlugin, I don't have CTag install, so I cannot really reproduce the crash of TagLEET.
For QuickColorPicker, however, I've download the source code from https://github.com/nulled666/nppqcp/ , compile it as x64 and I cannot reproduce crash at all: Both "Open Color Palette" & "Pick Color from Screen" commands works fine.

How did you reproduce the crash for QuickColorPicker ?

**Comment by vinsworldcom** [comment]
@donho 

SpeechPlugin you said can be reproduced and just wanted to say I have a slightly modified version that cleans up the menu items and I update it with the new headers and test and it resolves the crash - so that should be a simple recompile fix.

TagLEET doesn't crash Notepad++, rather it generates an "Access Violation" popup message box.  This is fixed in my customized version, but since TagLEET is in the Plugin Admin by the original author, I only post mine as "pre-release" since it is heavily customized and not very good coding practice.  But it does show that simply fixing the headers **_should_** resolve the issue.

QuickColorPicker is a bit more complicated.  You need to:

1) Set language to XML
2) Enter the text:  "rgb(255,255,255)"  : without the double quotes
3) Double click anywhere on the "rgb" text letters
4) Notepad++ should crash

Again, I have an updated version that I added new color recognition so it would highlight colors in Notepad++ XML theme files for when I was creating a new theme.  I never use that custom version anymore, but I did update it with the new headers and test and the above problem goes away.

Cheers.

**Comment by xomx** [comment]
@donho @vinsworldcom 
The QuickColorPicker will not work without additional code changes anyway. There are other 2GB+ problems in its code. But this one I can fix quickly, at least I think so. If I succeed, I will do a PR there.

**Comment by vinsworldcom** [comment]
@xomx assume you're using https://github.com/chcg/nppqcp and not the abandoned https://github.com/nulled666/nppqcp?

**Comment by donho** [comment]
@vinsworldcom 
Thank you, I can reproduce the crash of QuickColorPicker with your instructions now.

> TagLEET doesn't crash Notepad++, rather it generates an "Access Violation" popup message box. 

Then I won't include TagLEET in exclusion list.

> assume you're using https://github.com/chcg/nppqcp 

@xomx Yes it'll be better that you do a PR in @chcg 's fork - the statement of original author is clear to us.
BTW @chcg : is there any reason that QuickColorPicker is not in PluginList? Just asking.

**Comment by pnedev** [comment]
@donho , @vinsworldcom , all,

Compare plugin v2.0.2 is ready, here is the plugin list PR: https://github.com/notepad-plus-plus/nppPluginList/pull/402

**Comment by xomx** [comment]
@vinsworldcom @donho 
Thanks for the tip-off, where to put an eventual PR.

Quick comparing of the master branches in both (original one and @chcg fork) repositories shows me, that they are the same.
But the newest released version ([2.0.11](https://github.com/chcg/nppqcp/releases/tag/2.0.11)) has not been propagated to the master branch there(?!).

Also in the sln&vcxproj file are somewhat mixed-up Win32/x64/Unicode project configurations (so e.g. the Debug x64 refused to build at all). I have to fix this first.

**Comment by xomx** [comment]
@pnedev 
Tested your v2.0.2 - it works ok now.

**Comment by donho** [comment]
@pnedev 
Thank you for your work. However, I didn't see any new commit in the master:
https://github.com/pnedev/compare-plugin/commits/master

Am I missing somethings?

**Comment by Yaron10** [comment]
@xomx,

Could you please have a look at the [HTML Tag plugin](https://sourceforge.net/p/npp-plugins/discussion/725650/thread/08c8e87447/)?
It's written in Delphi.

Thank you for your work.

***
Related: https://github.com/notepad-plus-plus/notepad-plus-plus/issues/8700.

**Comment by xomx** [comment]
@Yaron10 

> Could you please have a look at the [HTML Tag plugin](https://sourceforge.net/p/npp-plugins/discussion/725650/thread/08c8e87447/)?
> It's written in Delphi.

My last coding in Pascal is now 25 years old for sure ;-)
Your need to scroll down in the HTMLTag source code file .\HTMLTag_plugin_src\src\LibNppPlugin\NppScintillaConstants.pas and change the cpMin/Max `integer` type specifier to the `NativeInt` there:

```
type
    RSciCharacterRange = record
      cpMin: integer;
      cpMax: integer;
    end;
```
Maybe it will be enough, but I doubt do.

I am sorry, but I am not going to help you with that. I do not have a Delphi IDE to test and compile. And besides, this is just another abandoned project: https://fossil.2of4.net/npp_htmltag/wiki?name=Deprecation

**Comment by Yaron10** [comment]
@xomx,

Thank you for the detailed reply.
I don't have a Delphi IDE either.

**Comment by donho** [comment]
> Quick comparing of the master branches in both (original one and @chcg fork) repositories shows me, that they are the same.
But the newest released version (2.0.11) has not been propagated to the master branch there(?!).

@chcg 
We are a little bit confused here. Could you please lighted us for this point?

**Comment by vinsworldcom** [comment]
@donho I just had XML Tools crash Notepad++ 8.2.2 when doing Plugins => XML Tools => Pretty print.

The [code ](https://github.com/morbac/xmltools/blob/7981818467f2a154fd06538750149b811d92aea7/ToolsEditor.cpp#L25)does use `SCI_GETTEXTRANGE` .

I've opened an [issue](https://github.com/morbac/xmltools/issues/135).

There were a flurry of XML Tools updates over the past year if I remember correctly so hopefully @morbac can get this fixed quick with just the Sci_Position.h update.

Cheers.

**Comment by xomx** [comment]
@vinsworldcom 

> I just had XML Tools crash Notepad++ 8.2.2 when doing Plugins => XML Tools => Pretty print.

I can reproduce this crash.

> hopefully @morbac can get this fixed quick with just the Sci_Position.h update.

This time it will need more than the Sci_Position.h update, as this specific crash originates from the `sciWorkText` `long` overflow (".\xmltools-master\ScintillaDoc.h"):

```
struct sciWorkText
{
	char* text;
	long length;
	long selstart;
	...
```
should be changed to:
```
struct sciWorkText
{
	char* text;
	intptr_t length;
	intptr_t selstart;
	...
```
Because of this plugin is actively developed, we should preferably wait for a PR from its own developer, he knows his code best.

**Comment by xomx** [comment]
@chcg 
There is my fixed & updated NppQCP plugin: [nppqcp-2.0.12.7z](http://redwoodal.sweb.cz/NotepadPlusPlus/nppqcp-2.0.12.7z)
There are a lot of changes even in its sln&vcprojx files. So before I will start creating PRs in your forked repository, I rather wait for your instructions/permission. Or if you will take the nppqcp-2.0.12.7z and do all the necessary stuff yourself, I will be glad.

**Comment by chcg** [comment]
@xomx @donho  I just did a release for https://github.com/nulled666/nppqcp/issues/30. At that time it was not clear that the project was abandoned by the original author.
@vinsworldcom If you want to take over the development of that plugin it is fine for me.

**Comment by vinsworldcom** [comment]
@chcg I can take over hosting [SpeechPlugin](https://github.com/vinsworldcom/nppSpeechPlugin/) and [QCP](https://github.com/vinsworldcom/nppQCP/) if that helps you.

Some notes:

+ I'm not a very talented C++ developer - never formally learned it, just understand programming in general from my Perl scripting days and know how to use Google.  Taking over would be more like maintenance versus development.
+ SpeechPlugin is pretty much inline with where you are on it so it may be as simple as me updating the plugin list with my repo information / SHA256 hash and we're done.
+ QCP is a bit different.  I've merged all of @xomx latest updates to your manually into mine and I've added another developer's fork commits that were more about secure coding practices.  I've also added some stuff to recognize colors in Notepad++ theme files and most of all - changed the name from NppQCP => QuickColorPicker - a pet peeve of mine about how the plugin menu orders plugins alphabetically.  This means it's not quite a simple upgrade for users who already have NppQCP installed; mine would not show up as an upgrade; rather, a new plugn.

If we're all "cool" with that, I'm happy to take over hosting them and maintaining them - like I said, basic maintenance, accept pull requests, etc. but probably not any new advance feature development - I just don't have the chops for that.

Cheers.

**Comment by chcg** [comment]
@vinsworldcom
I already updated SpeechPlugin some hours ago and added the updated 0.4.0 to the pluginlist. I also don't add new features, just try to keep them alive and functional. Just get aware right now that you also have a repo of the speechplugin and already did the interface adaptation there. As I don't expect much work from that plugin it is ok to keep it as it is for now and maybe switch if you add some new features at some point in the future.

The old pluginManager had an alias system for such plugin renamings. That is not available with the current PluginAdmin system.

NppQCP is just available for x86 as
	
> "folder-name": "NppQCP",
> "display-name": "Quick Color Picker +",
> "version": "2.0",

So x64 and arm64 user would anyhow have no problem with a different name or the same displayname with a different repo behind.


Maybe it would be a good idea to have an organization repo (e.g. https://github.com/npp-plugins where donho has his plugins) for such no longer actively maintained repos. In this case it would be possible to transfer the plugins currently spreaded
https://docs.github.com/en/repositories/creating-and-managing-repositories/transferring-a-repository
to a common repo with multiple maintainers.

**Comment by vinsworldcom** [comment]
> Maybe it would be a good idea to have an organization repo (e.g. https://github.com/npp-plugins where donho has his plugins) for such no longer actively maintained repos

I like this idea - in our case, "lightly maintained" plugins, not dead yet 😁

Cheers.

**Comment by chcg** [comment]
@donho What do you think about transferring the ownership of these "lightly" maintained plugins to  https://github.com/npp-plugins or something similar?

**Comment by rdipardo** [comment]
@donho or @chcg
I think someone needs to manually trigger the appveyor check for my PR https://github.com/notepad-plus-plus/nppPluginList/pull/411

**Comment by donho** [comment]
@chcg 
> What do you think about transferring the ownership of these "lightly" maintained plugins to https://github.com/npp-plugins or something similar?

Sure. Feel free to transfer them to npp-plugins.
I'll do my best to maintain such plugins.

**Comment by rdipardo** [comment]
@xomx, @Yaron10
> You need to scroll down in the HTMLTag source code file .\HTMLTag_plugin_src\src\LibNppPlugin\NppScintillaConstants.pas and change the cpMin/Max `integer` type specifier to the `NativeInt` there.

Close, but the better candidate was a near duplicate called `TCharacterRange` around line 47 at `lib/SciSupport.pas`. The same unit defines a `TTextRange` that (correctly) gives the `LPSTR` type to its `lpstrText` field; the version at `LibNppPlugin\NppScintillaConstants.pas` has the higher-level `PChar`, which points to a UTF-16 string in modern Delphi(!!!). That could not have been the author's intention, since HTMLTag dates from the pre-Unicode days of N++. The last release (v1.1) [could not decode a multi-byte sequence] like `\u0048\u0065\u006c\u006c\u006f` without an access violation. The [next version] will be safe for x64 architecture and work as advertised:

![HTMLTag](https://user-images.githubusercontent.com/59004801/152662501-676fb6a0-e98b-4d7e-9ab7-4adbe36ebfef.gif)

)

> And besides, this is just another abandoned project

Until now: <https://community.notepad-plus-plus.org/topic/22503/new-version-of-html-tag/1>

[next version]: https://bitbucket.org/rdipardo/htmltag/src/default/NEWS.textile
[could not decode a multi-byte sequence]: https://community.notepad-plus-plus.org/topic/18488/htmltag-1-1-plugin-broken-since-npp-7-7

> I do not have a Delphi IDE to test and compile.

You're not missing much. When it's "working" it interrupts you just to say that Embarcadero wants their money:

![patente](https://user-images.githubusercontent.com/59004801/152662689-676eb058-0afb-4ab9-a299-e6701d0b6f36.png)

When my remaining 90 days are up, it's over to the [blue cheetah IDE].

[next version]: https://bitbucket.org/rdipardo/htmltag/src/default/NEWS.textile
[could not decode a multi-byte sequence]: https://community.notepad-plus-plus.org/topic/18488/htmltag-1-1-plugin-broken-since-npp-7-7
[blue cheetah IDE]: https://wiki.freepascal.org/Lazarus_For_Delphi_Users#The_first_thing_to_do_when_converting_a_Delphi_project_to_Lazarus

**Comment by vinsworldcom** [comment]
@rdipardo since you seem to know Delphi and have a compiler for it, how about taking a crack at the [DBGp plug-in](https://sourceforge.net/projects/npp-plugins/files/DBGP%20Plugin/)  and making it 64 bit?

You'd be considered a god!

Cheers.

**Comment by vinsworldcom** [comment]
@donho 
> I'll do my best to maintain such plugins.

I think the thought was that we would help maintain these "legacy", once-abandoned plugins

Cheers.

**Comment by Yaron10** [comment]
@rdipardo,

We seem to have had a midair-collusion. :) I've just posted in https://github.com/notepad-plus-plus/nppPluginList/pull/411.

Thanks again.

**Comment by rdipardo** [comment]
@vinsworldcom,
> how about taking a crack at the [DBGp plug-in](https://sourceforge.net/projects/npp-plugins/files/DBGP%20Plugin/) and making it 64 bit?

I always thought SourceForge was just a software vendor (am I wrong? 😉)
That said, I'm sure the DBGp source code is hidden somewhere on the site.  Any tips?

Porting to x64 might be tricky is there's inline assembly involved. A similar task went badly once before, when I tried to revive [NPPFSIPlugin](https://github.com/ppv/NPPFSIPlugin/issues/7). The 32-bit version should be safe from the recent ABI change, so it would be a longer term TODO in any case.

**Comment by vinsworldcom** [comment]
@rdipardo Source seems to be right with the latest plugin (32-bit only). Not sure how "accurate" it is as it's just a ZIP, not a repo:

https://sourceforge.net/projects/npp-plugins/files/DBGP%20Plugin/DBGP%20Plugin%20v0.13%20beta/DBGpPlugin_0_13b_src.zip/download

I did talk to the author quite some time ago and he said it would be difficult and he no longer had a Delphi dev environment setup.  If you know Delphi and can have a look, .. like I said - you'd be a hero!  That's the one plugin that kept me on 32-bit N++ for longer than I would have liked.  Ultimately I had to leave it behind - but I had some "good" times with it:

+ https://vinsworldcom.blogspot.com/2015/08/notepad-dbgp-and-python.html
+ https://vinsworldcom.blogspot.com/2015/08/debugging-perl-debugger-part-1-notepad.html
+ https://vinsworldcom.blogspot.com/2015/08/debugging-perl-debugger-part-2-variable.html
+ https://vinsworldcom.blogspot.com/2015/08/debugging-perl-debugger-part-3.html

Cheers.

**Comment by donho** [comment]
@vinsworldcom 
> I think the thought was that we would help maintain these "legacy", once-abandoned plugins

Yes, that's the ideal situation.
But in the case that no one want to do it, then I will (try it).
