### ISSUE TITLE
NPPM_RELOADFILE long filename issue

### ISSUE THREAD

**Issue by chcg** [notepad-plus-plus/notepad-plus-plus#11106]
### Description of the Issue
Usage of NPPM_RELOADFILE from pythonscript by test case https://github.com/bruderstein/PythonScript/blob/master/PythonScript/python_tests/tests/NotepadWrapperTestCase.py#L383-L397 with a 8.3 notation of the file path shows an issue that the file is not found by N++. Introduced from the very beginning with:

> Revision: 5529852d672db73d059fa22c9e9ac794a399e481
> Author: harrybharry <harrybharry@f5eea248-9336-0410-98b8-ebc06183d4e3>
> Date: 16.06.2008 13:35:05
> Message:
> Fix file case problem.
> Fix incremental search not using selected text.
> Fix Session not loaded using anything other than file->open menu.
> 
> git-svn-id: svn://svn.tuxfamily.org/svnroot/notepadplus/repository@235 f5eea248-9336-0410-98b8-ebc06183d4e3
> ----
> Modified: PowerEditor/src/Notepad_plus.cpp
> Modified: PowerEditor/src/ScitillaComponent/Buffer.cpp
> Modified: PowerEditor/src/lastRecentFileList.cpp

### Steps to Reproduce the Issue
1. Call NPPM_RELOADFILE  with a filename containing 8.3 notation, e.g. C:\\longnamedir aka C:\\longna~1  

### Expected Behavior
- File reloaded

### Actual Behavior
- File not reloaded

### Debug Information
Notepad++ v8.2.1   (64-bit)
Build time : Jan 30 2022 - 00:24:07
Path : C:\Users\christian\Source\Repos\npp.8.2.portable.x64\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : ON
Cloud Config : OFF
OS Name : Windows 10 Home (64-bit) 
OS Version : 2009
OS Build : 19044.1503
Current ANSI codepage : 1252
Plugins : HexEditor.dll Papyrus.dll PythonScript.dll

**Comment by donho** [comment]
PR #11107 causes the regression #11215.
 So this issue is reopened.
