### ISSUE TITLE
Improve search lines: 1 -> 01 if XX lines, 001 if XXX lines, 0001 if XXXX lines, etc.

### ISSUE THREAD

**Issue by Neustradamus** [notepad-plus-plus/notepad-plus-plus#11119]
Currently when we search in files, the result is like this but it is not easy to compare line because one rank shift at 10 / 100 / 1000 / etc.
Line 1 ...
Line 2 ...
Line 3 ...
Line 4 ...
Line 5 ...
Line 6 ...
Line 7 ...
Line 8 ...
Line 9 ...
Line 10 ...
...
Line 99 ...
Line 100 ...
...
Line 1000 ...
...

Improve search lines:
- Line 1 to 99 -> Line 01 to 99 if XX lines
- Line 1 to 999 -> Line 001 to 999 if XXX lines
- Line 1 to 9999 -> Line 0001 to 9999 if XXXX lines
- etc

Thanks in advance.

**Comment by alankilborn** [comment]
This is not an unreasonable request but I would prefer leading spaces rather than leading zeroes, e.g.:

    Line   6: Copyright (C)2021 Don HO <don.h@free.fr>.  This program is free SOFT
    Line   6: Copyright (C)2021 Don HO <don.h@free.fr>.  This program is free SOFT
    Line  16: Copyright (C) 2007 Free Software Foundation, Inc. <https://fsf.org/>
    Line  21: The GNU General Public License is a free, copyleft license for softw
    Line  23: The licenses for most software and other practical works are designe
    Line  25: When we speak of free software, we are referring to freedom, not pri
    Line  27: To protect your rights, we need to prevent others from denying you t
    Line  31: Developers that use the GNU GPL protect your rights with two steps: 
    Line  33: For the developers' and authors' protection, the GPL clearly explain
    Line  35: Some devices are designed to deny users access to install or run mod
    Line  37: Finally, every program is threatened constantly by software patents.
    Line 101: a) Convey the object code in, or embodied in, a physical product (in
    Line 102: b) Convey the object code in, or embodied in, a physical product (in
    Line 169: A patent license is "discriminatory" if it does not include within t
    Line 180: The Free Software Foundation may publish revised and/or new versions
    Line 182: Each version is given a distinguishing version number. If the Progra
    Line 200: If you develop a new program, and you want it to be of the greatest 
    Line 207:     This program is free software: you can redistribute it and/or mo
    Line 209:     the Free Software Foundation, either version 3 of the License, o
    Line 225:     This is free software, and you are welcome to redistribute it

**Comment by wassinkl** [comment]
Can I be assigned to this issue? Would you prefer leading zeros or leading spaces?

**Comment by gawkla** [comment]
Hi all. It should be also possibility to have no preffix in result window.

Other issue is, that search should behave like grep command: if searched sentence exists twice or more in one line this line should be presented once in results. Now each occurence provide one line in output, which easy give double line results, triple line results etc...
