### ISSUE TITLE
A minor problem when using the Logitech MX Master 3 mouse

### ISSUE THREAD

**Issue by FomchenkoMajorAuto** [notepad-plus-plus/notepad-plus-plus#11117]
A minor problem when using the Logitech MX Master 3 mouse.
Its design provides a wheel that can be used for a horizontal scrolling.
Problem: If you use it (the wheel), then the still horizontal scrollbar is moves but the text remains in place.
In other programs, this feature is working normally.

**Comment by rimrul** [comment]
Duplicate of #4720, #10490, #2096, #9452, #8794.

**Comment by dail8859** [comment]
Closing as a duplicate of #10490
