### ISSUE TITLE
Tiny Feature Request: Show number of results found

### ISSUE THREAD

**Issue by curya** [notepad-plus-plus/notepad-plus-plus#11118]
When searching for a word in Chrome, for example, you get something that looks like this:
![VIuRUC4](https://user-images.githubusercontent.com/71131343/152148385-07f2d0a8-2a1d-490b-b99a-b779413922a9.png)

And it changes numbers as you go through them:
![4zVjonJ](https://user-images.githubusercontent.com/71131343/152148636-3c52dd35-6506-4c1a-9aee-3dbd24034e05.png)

I know you already have features like "Count," "Mark," and "Find All in Current Document," but it would be very useful to see what number I'm on in the Find window as I search through the results.

**Comment by alankilborn** [comment]
That works well for Chrome, where text is constant.  In an editor, after a find users typical make changes producing more/less matches with their changes.

So N++ would have to continually (with every text change by the user) scan an entire file (potentially a huge file) to make sure that the YY in XX/YY remains correct, while that box remains showing.

I wouldn't say it is a "tiny" feature request.  It's a feature request with possibly big implications and impact to the software.

**Comment by curya** [comment]
Doesn't "Count" basically do that already...? I would just like the information displayed when I press "Find Next."

**Comment by alankilborn** [comment]
>I would just like the information displayed when I press "Find Next."

I think it is a good feature request; it could update the Find window's status bar with every Find Next press.

**Comment by silver5171** [comment]
What if the numerator becomes a '?' when a change comes through, and then when the arrow or "find next" is pressed N++ could scan the entire file, which would then change both the numerator and denominator?

Pros:
- deferred work so that N++ does not need to continually scan files
- Gives users extra information on what number they are on in the common case

Cons:
- In a naive implementation the denominator would not change, which may cause some confusion until "find next" is clicked and the file rescanned (unless we did something on a file change that would display something like '?/?')

**Comment by vinsworldcom** [comment]
I'd love to see it on the incremental find - which already shows the "matches":

![image](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/9657169/a4dae774-4a1c-429d-8628-3ccb9963b79e)

I've had a quick look and not sure how easy it is to add this.  Maybe in this:

notepad-plus-plus/PowerEditor/src/ScintillaComponent/FindReplaceDlg.cpp:
```
2813: int FindReplaceDlg::processRange(ProcessOperation op, FindReplaceInfo & findReplaceInfo, const FindersInfo * pFindersInfo, const FindOption *opt, int colourStyleID, ScintillaEditView *view2Process)
```

Need to get the current position and keep a counter of `numBeforeCurrPos` during the while loop at:

notepad-plus-plus/PowerEditor/src/ScintillaComponent/FindReplaceDlg.cpp:
```
2918: 	while (targetStart >= 0)
2919: 	{
2920: 		targetStart = pEditView->searchInTarget(pTextFind, stringSizeFind, findReplaceInfo._startRange, findReplaceInfo._endRange);
2921: 
2922: 		// If we've not found anything, just break out of the loop
2923: 		if (targetStart == -1)
2924: 			break;
2925: 
```

and return that info somehow.  Then it could be used to update (by `numBeforeCurrPos++`) with logic to "wrap around" if `nbCounted` is hit (or 0 if going backward) in:

notepad-plus-plus/PowerEditor/src/ScintillaComponent/FindReplaceDlg.cpp:
```
5478: void FindIncrementDlg::setFindStatus(FindStatus iStatus, int nbCounted)
5479: {
5480: 	generic_string statusStr2Display;
5481: 
5482: 	static const TCHAR* const strFSNotFound = TEXT("Phrase not found");
5483: 	static const TCHAR* const strFSTopReached = TEXT("Reached top of page, continued from bottom");
5484: 	static const TCHAR* const strFSEndReached = TEXT("Reached end of page, continued from top");
5485: 
         ...
```

Cheers.

**Comment by donho** [comment]
It makes users/devs dreaming, even me I have to admit.
However, let's not forget the fact that the content in a browser is read-only, whereas in an editor the content can be modified. 
That is, adding the same word of searching occurrence before and after current found word is possible in Notepad++. Such fact could make an incoherent searching result. Also, current implementation is one result per shot, whereas this requested feature have to keep the trace on the same word - that will make the current code of search (which is already complex) even more complex. 
As a result, I have to decline this feature request.
