### ISSUE TITLE
Deleting an XML tag crashes NPP 8.3 64-bit 

### ISSUE THREAD

**Issue by Yaron10** [notepad-plus-plus/notepad-plus-plus#11128]
**STR:**
Open a new document and set the language to XML or HTML.
Paste the following two lines:
```
<NotepadPlus>
</NotepadPlus>
```
Delete the last `>`.

**Result:**
NPP crashes.

***
Notepad++ v8.3   (64-bit)
Build time : Feb  3 2022 - 03:39:05
Path : C:\Users\---\Downloads\npp.8.3.portable.x64\notepad++.exe
Command Line : 
Admin mode : ON
Local Conf mode : ON
Cloud Config : OFF
OS Name : Windows 10 Pro (64-bit) 
OS Version : 2009
OS Build : 19042.985
Current ANSI codepage : 1255
Plugins : mimeTools.dll NppConverter.dll NppExport.dll

**Comment by xomx** [comment]
Reproducible only in Release build (but if you switch off the compiler and linker optimizations there, it stops crashing), Debug one does not crash.

Crash origin ... ".\PowerEditor\src\ScintillaComponent\xmlMatchedTagsHighlighter.cpp":
```
vector< pair<intptr_t, intptr_t> > XmlMatchedTagsHighlighter::getAttributesPos(intptr_t start, intptr_t end)
{
	...

	delete [] buf;
	return attributes;
}
```
It crashes at the `delete [] buf`.
But the problems are in the caller - `XmlMatchedTagsHighlighter::tagMatch(bool doHiliteAttr)`, one of them is:
- there is instantiation of `XmlMatchedTagsPos xmlTags;` and the xmlTags members are not reset to some starting value, so it can contain a random integers within at the start
- then there is `getXmlMatchedTagsPos(xmlTags)` call and when the closing xml-tag is deleted (or missing from the start - try to open a file with the same content, but with the already missing `>`), the XMLTags.tagCloseEnd member is not updated at all, so it still can contain this starting random integer after

**Comment by Yaron10** [comment]
@xomx,

Thank you for looking into it. 👍 

@vinsworldcom,

Interesting. Windows 7?

**Comment by donho** [comment]
@Yaron10 
Well spotted! Thank you!

@vinsworldcom 
I can reproduce it with no problem. What's your OS?

@xomx 
Thank you for your analysis to help fixing this bug.

**Comment by xomx** [comment]
@Yaron10 
> I cannot reproduce the crash

That is probably by your random integers are 'better' than mine or @Yaron10  ;-)

**Comment by Yaron10** [comment]
@donho,

Great.
Thank you for the quick fix. 👍 

@xomx,

Thanks again. 👍 

***

@xomx,

> That is probably by your random integers are 'better' than mine or @Yaron10 ;-)

If the crash only happened on NPP 64-bit, isn't it also possible it only occurred on Win 10? 
(And not on Win 7 @vinsworldcom might be using).

**Comment by xomx** [comment]
@Yaron10 
> If the crash only happened on NPP 64-bit, isn't it also possible it only occurred on Win 10?

Well, it depends on many many factors.

My previous note about 'better random integers' was only a programmer joke. But it is based on facts:
- in Debug builds all the instantiated variables are automatically reset to zero
- in Release builds one of the compiler&linker optimization is to leave this job on the programmer only
- so in a Release build the content of an uninitialized variable is 'random'
- this 'randomness' depends on many factors and one of them could be the OS version used

**Comment by vinsworldcom** [comment]
I'm actually on Windows 10

**Comment by Yaron10** [comment]
@xomx,

I liked the joke. And my question was serious. :)
Thanks for the explanation.

@vinsworldcom,

So it's indeed "better random integers". :)

**Comment by xomx** [comment]
@Yaron10 

Ok, so when it is serious:
- I omitted some details before, e.g. the global and static variables are also automatically reset to zero
- my tip about what will have the biggest influence on the content of an uninitialized variable is: the compiler type & version used (some compilers intentionally uses specific 'random' values, some does not care at all, this is also very dependent on the C standard used etc.)

So maybe @vinsworldcom compiler is different than mine. But this is only a guess and it can also depend on the OS version or build or some system setting.

**Comment by Yaron10** [comment]
@xomx,

Thank you for the serious explanation. 
I've learned something new and I appreciate it.

**Comment by vinsworldcom** [comment]
> So @vinsworldcom was lucky, that his previous variable/object value at that memory address was 0.

HOLD THE PHONE - I can replicate it, but only with a fresh x64 portable.  I was testing on the x64 portable Notepad++ copied into my installation - with all my customizations (but running with the `-noPlugin`) option.  SO... it appears a Preferences setting could be responsible perhaps?

Cheers.

**Comment by xomx** [comment]
@vinsworldcom 
> a Preferences setting could be responsible perhaps?

Yes, it can be that. Or something else. Whatever what changes your current N++ memory layout even a little bit. The memory space, allocated by the `XmlMatchedTagsPos xmlTags;` on the stack, could be used before for some Preferences stuff.

**Comment by Yaron10** [comment]
If _Highlight tag attributes_ is unchecked, NPP does not crash (i.e. even without the recent fix).

![תמונה](https://user-images.githubusercontent.com/10229320/152581019-950bc51a-3e9e-4311-871c-638ef3d85de8.png)

**Comment by vinsworldcom** [comment]
@Yaron10 Great find!! By default, in my freshly unzipped 8.3 x64 it is CHECKED by default.

In my normal everyday portable install, I have that UN-checked by default.  Which is probably why I didn't see the crash originally.

Cheers.

**Comment by Yaron10** [comment]
So it was "a better setting". :)
