### ISSUE TITLE
No PoorMansTSqlFormatter button in Notepad++ toolbar

### ISSUE THREAD

**Issue by eric13500** [notepad-plus-plus/notepad-plus-plus#11122]
Hi!

I'm using PoorMansTSqlFormatter great extension in Notepad++, but unlike all the others, PoorMansTSqlFormatter doesn't add any button in the toolbar, so I have to go to Extension Modules/Poor Man's T-Sql Formatter/Format T-SQL Code each time I need to use it (wich is very common)...

it would be nice if we could format the code with a single click in the toolbar.

Regards (and thanks a lot for your job!)
Eric.

**Comment by alankilborn** [comment]
Plugins aren't "owned" by Notepad++ dev team and this site.
Suggest you find that plugin's support site and request a toolbar button there.

Or probably the _CustomizeToolbar_ plugin could allow you to create your own button.

**Comment by ArkadiuszMichalski** [comment]
Write to author of this plugin or use shortcut or CustomizeToolbar plugin (as suggested above).
