### ISSUE TITLE
Hide lines feature: "unhide lines" markers sometimes disappear

### ISSUE THREAD

**Issue by vlakoff** [notepad-plus-plus/notepad-plus-plus#1112]
How to reproduce:
- Select a few lines, trigger "Hide lines".
- Select a few other lines, trigger "Hide lines" as well.
- Unhide **the topmost block** by clicking on the appropriate marker.
- The marker to restore the other block disappear. So the block is still hidden, it cannot be unhidden and there is no more visual indication there are hidden lines!

(tested on Notepad++ 6.8.6)

**Comment by tomecho** [comment]
Has anyone started work on this?

**Comment by Currie6** [comment]
This needs to be fixed! Bugging the crap out of me.

**Comment by Currie6** [comment]
Fix IT!!!!

**Comment by CookiePLMonster** [comment]
Notes taken.

I saw the "ninja" post though - it's not a nice way to bump your issue if you ask me. If you're this desperate on seeing it fixed, you could attempt to do it yourself - that's what open source is about, technically.

**Comment by MetaChuh** [comment]
hi @vlakoff
thanks, verified to be reproducible on 7.6.6.

reader's note:
a current workaround is to reload a file using <kbd>file > reload from disk</kbd>.
(reload from disk will be triggered by <kbd>ctrl</kbd>+<kbd>r</kbd> in the upcoming release)

**Comment by SinghRajenM** [comment]
@vlakoff, @MetaChuh, may I ask to you to verify the fix?

Binaries are available here ([x64](https://ci.appveyor.com/api/buildjobs/7r7hsdbs5paxt91q/artifacts/Notepad%2B%2B.x64.Unicode%20Release.exe) and [x86](https://ci.appveyor.com/api/buildjobs/ax0koo9rq3758n97/artifacts/Notepad%2B%2B.Win32.Unicode%20Release.exe)).

**Comment by vlakoff** [comment]
I tried to launch the x86 version but got several runtime issues. Still happens when also replacing the SciLexer.dll

**Comment by MetaChuh** [comment]
@vlakoff 

you have to use the 7.7 release candidates.
https://notepad-plus-plus.org/community/topic/17655/notepad-7-7-release-candidate-v5

@SinghRajenM 

verified to work for as far as i had time to test.
many thanks.

**Comment by vlakoff** [comment]
@MetaChuh Thanks for the explanation :)

@SinghRajenM I just tried the binary, on 7.7 final as it has been released since then. It seems to work. Good job!

Too bad the fix didn't land in 7.7… hope the fix will be merged soon!

**Comment by TomatoJoe** [comment]
Still not fixed.  There is a "Hide lines" (context) menu item, but no "Unhide lines" menu item!!  Which prompted a "WTF? " reaction. So I enabled the _Display bookmark_ column to sow the arrow markers.
Could unhide  the first line but clicking the arrow for the next hidden line did nothing.
