### ISSUE TITLE
Version 8.3 Regression: No UI right away & slower to open 4-6MB files

### ISSUE THREAD

**Issue by Gitoffthelawn** [notepad-plus-plus/notepad-plus-plus#11127]
### Description of the Issue
The Notepad++ UI no longer appears right away and takes longer to load files that are 4-6MB in size.

### Steps to Reproduce the Issue

1. Create a text file that is ~4.8MB in length, with ~92K lines, with lines ranging in length from 50-600 characters.  Use UTF-8 encoding, and include characters from various languages.  Use Unix/Linux line terminators (LF).
2. Create a Windows shortcut to launch Notepad++ 32-bit (portable, if possible) with the file you created in step 1 loaded into it.
3. Launch the shortcut created in step 2.

### Expected Behavior
Notepad++ to open right away with its UI visible.

### Actual Behavior
Before v8.3, such files would open right away in Notepad++ with its UI visible.  With v8.3, the Notepad++ window appears right away, but it is **completely** empty.  **No titlebar, no menubar, no content.**  After ~0.5 - 1.5sec, the titlebar, menubar, and content appear.  About 0.5sec later, the toolbar appears.

This is a regression not found prior to v8.3 (except for the toolbar appearing late).

I noticed 2 differences as compared to previous Notepad++ versions:
 1. The time from clicking on the shortcut to launch Notepad++ (with the file loaded) until it is ready to use is now longer.  I estimate it takes 10-25% longer.
 2. The Notepad++ window is **completely blank** until Notepad++ is able to show the file's content.

### Debug Information
Notepad++ v8.3   (32-bit portable)
Path : C:\notepadplusplustest\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : ON
Cloud Config : OFF
OS Name : Windows 7 (64-bit) 
Plugins : Converter.dll CustomizeToolbar.dll DSpellCheck.dll HexEditor.dll mimeTools.dll NppExec.dll NppExport.dll Remove Duplicate Lines.dll TopMost.dll

### Other Info
I thought this was perhaps a word wrap issue, but I tested with word wrap enabled and disabled.  With it enabled, things were a bit slower, but not enough to account for the above.

**Comment by alankilborn** [comment]
What is the spec on "opening time"?

**Comment by Yaron10** [comment]
@Gitoffthelawn,

Could you please upload your file?

**Comment by Gitoffthelawn** [comment]
> What is the spec on "opening time"?

@alankilborn Are you asking me or someone else?  If you're asking me, can you help me understand what information will help?  I'm not quite sure what you are asking.

@Yaron10 Without having people sign a bunch of documents, I cannot upload the files.  But I can create similar files with dummy text.  If there is interest in working on this, I'm happy to spend some time creating such files.  If there is no interest, that's fine too, but then I won't need to spend time creating such files.  Just let me know at your convenience.

**Comment by Yaron10** [comment]
@Gitoffthelawn,

I certainly see your point.
I can not guarantee the developers should work on it.
I can test it and ask them to have a look if indeed there's a regression.

**Comment by donho** [comment]
@Gitoffthelawn 
Please attach your dummy file here if the issue still happen to you with this dummy file.
Also, could you test again WITHOUT plugins? You can rename plugins folder to "plugins.OFF" then launch Notepad++ v8.3 to see if the issue persists.

**Comment by Yaron10** [comment]
@donho,

Thank you.

@Gitoffthelawn,

Don is the author of Notepad++. :)

**Comment by Gitoffthelawn** [comment]
> @Gitoffthelawn Please attach your dummy file here if the issue still happen to you with the dummy file in question. Also, could you test again WITHOUT plugins? You can rename plugins folder to "plugins.OFF" then launch Notepad++ v8.3 to see if the issue persists.

Yes and yes.  :)  I'll add both items to my list to get done.  Hopefully I will have time within a few days.

**Comment by ArkadiuszMichalski** [comment]
@Gitoffthelawn What is the state of this problem still exist in latest Notepad++? I can't reproduce it.
```
Notepad++ v8.3.3   (32-bit)
Build time : Mar 13 2022 - 17:11:10
Path : D:\_test\NPPClean\notepad++.exe
Command Line : -multiInst
Admin mode : ON
Local Conf mode : ON
Cloud Config : OFF
OS Name : Windows 7 Ultimate (64-bit) 
OS Build : 7601.0
Current ANSI codepage : 1250
Plugins : none

```

**Comment by Gitoffthelawn** [comment]
@ArkadiuszMichalski I just completed a few tests using Notepad 8.3.3 32-bit.  It seems to be greatly improved.  The big thing that now lags is the toolbar creation when plugins are installed (including the Customize Toolbar plugin... I often think it would good to have that functionality native within Notepad++).  The files themselves seem to be loading much faster now.

**Comment by Gitoffthelawn** [comment]
Okay, I finished that other project faster than expected.

I ran a bunch more tests on Notepad 8.3.3 32-bit, including the dummy file you provided.

Except for the toolbar creation lagging, opening the files was much faster.

I'm going to close this issue now, but if others experience this issue, feel free to comment and I'll reopen it.

**Comment by ArkadiuszMichalski** [comment]
@Gitoffthelawn 
>Except for the toolbar creation lagging, opening the files was much faster.

Maybe it's the plugin's fault? If the toolbar was created faster in earlier versions of Notepad ++, find out which plugin is causing this problem and write to its author.
