### ISSUE TITLE
Invalid state of panel/button "Function list"

### ISSUE THREAD

**Issue by WinterSilence** [notepad-plus-plus/notepad-plus-plus#11121]
### Description of the Issue

After restart application dock/panel not displaying, but toolbar button is active/pressed.

### Steps to Reproduce the Issue

1. Press toolbar button "Function list" to show dock/panel
2. Restart application

### Expected Behavior

Display panel or unactive toolbar button

### Actual Behavior

Toolbar button is active, panel is hidden

### Debug Information

Notepad++ v8.2   (32-bit)
Build time : Dec 30 2021 - 03:36:49
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Command Line : "C:\OpenServer\domains\webasyst\wa-system\image\waImageImagick.class.php"
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 10 Enterprise (64-bit) 
OS Version : 2009
OS Build : 19044.1503
Current ANSI codepage : 1251
Plugins : ComparePlugin.dll DoxyIt.dll JSMinNPP.dll NppAutoIndent.dll NppExec.dll NppMarkdownPanel.dll NppQCP.dll NppUISpy.dll XMLTools.dll zoomdisabler.dll

**Comment by ArkadiuszMichalski** [comment]
@WinterSilence Can you try with [last portable version](https://github.com/notepad-plus-plus/notepad-plus-plus/wiki/Testing#using-the-latest-release-portable-version-of-notepad)? I can't reproduce this.

**Comment by WinterSilence** [comment]
@ArkadiuszMichalski fixed in last release
