### ISSUE TITLE
Notepad++ crash when saving XML add back the missing > for a comment

### ISSUE THREAD

**Issue by asdf913** [notepad-plus-plus/notepad-plus-plus#11137]
### Steps to Reproduce the Issue

Sample XML

\<?xml version="1.0" encoding="UTF-8"?>
\<!DOCTYPE server>
\
\<server>

  \<mbean code="org.jboss.varia.property.SystemPropertiesService" 
	 name="jboss:type=Service,name=SystemProperties">

    <attribute name="Properties">
	
    </attribute>
     
  \</mbean>

 \</server>

1.  Remove **>** in the comment within the **attribute** (i.e  to )
3.  Application Crash
![image](https://user-images.githubusercontent.com/2301325/152732180-9a9108db-e0ea-4fca-a044-edf8f3f90c8a.png)

### Expected Behavior
Save Successfully

### Actual Behavior
Application Crash

**Comment by vinsworldcom** [comment]
See https://github.com/notepad-plus-plus/notepad-plus-plus/commit/73a4cdc1040c15cee87ff21de94dd7669cdda607, this will be fixed in the next release.
