### ISSUE TITLE
javascript language colors settings are gone

### ISSUE THREAD

**Issue by i300220** [notepad-plus-plus/notepad-plus-plus#1113]
Notepad++ 6.8.6

Since last update, the javascript language colors are all messed up, gone.

The last version I had was pushed by the automatic updates and was 6.7.?

I noticed immediately after the update, I use that every day.  There is now 

![clipboard01](https://cloud.githubusercontent.com/assets/15702355/11041866/fc9cb232-86e1-11e5-9e82-4be151648031.jpg)

that ugly white background everywhere.

**Comment by csharpninja** [comment]
Have the same problem. Another javascript syntax highlighting.

![js_syn_h](https://cloud.githubusercontent.com/assets/1819952/11090972/2e72599e-887f-11e5-8d5e-62bd90d67c44.jpg)

**Comment by Tmp341** [comment]
Have you ever tried to change the theme?

**Comment by csharpninja** [comment]
What theme? Downgrade to version 6.7.9.2 has solved the problem.

**Comment by donho** [comment]
https://notepad-plus-plus.org/community/topic/10670/notepad-6-8-4-released

**Comment by i300220** [comment]
I believe this issue was closed by error.

That issue I reported occurred in 6.8.6 which is posterior to 6.8.4

I never tested any other 6.8.x as the updater jumped to 6.7.? maximum.  Going from 6.7.? to 6.8.6 was down via a manual download.

**Comment by Tmp341** [comment]
Have you tried the solution?

**Comment by i300220** [comment]
I did, with success.
