### ISSUE TITLE
C-Style Textblocks Folding together with Comments does not work right in UDL 

### ISSUE THREAD

**Issue by eowmob** [notepad-plus-plus/notepad-plus-plus#11130]
### Description of the Issue
I tried defining a UDL definition for LPC (Lars Pensjö C). It is very much like C, with bits of Ansi and C++ and well..

It has C-Style /* */ comments and command blocks with { }.

I understand the limitations of UDL vs. builtin languages, but when I start defining comments and blocks, folding screws up.

### Steps to Reproduce the Issue
Enter the .c file from the comment (also attached) and the attached very simple udl definition and you'll see what I mean.
I also attach a screen shot. This is with version 8.3 (I won't go to Beijing either) under 64bit Windows.

### Expected Behavior
Folding should work properly, that is start at {

### Actual Behavior
Folding starts in the line *AFTER* the one with the opening { character.

### Additional Comments/Wishes
Keywords starting or containing a ' character behave odd. &Backslash;' seems to escape this behaviour, at least partially. I wonder if the keyword / pattern fields are allowing some special characters. If so, should be documented. I was not able to figure it out.

A means to extend / control the parser for the builtin languages (beyond what is available now) should be provided, however complex the syntax may be.

### Debug Information
Notepad++ v8.3   (64-bit)
Build time : Feb  3 2022 - 03:39:05
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : "D:\Userdaten\Programmierprojekte\SomeAldebaranFiles\small.c"
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 10 Pro (64-bit) 
OS Version : 2009
OS Build : 19042.1466
Current ANSI codepage : 1252
Plugins : mimeTools.dll NppConverter.dll NppExport.dll

**Comment by eowmob** [comment]
![Screenshot 2022-02-04 193958](https://user-images.githubusercontent.com/72653851/152584768-456e5859-cb68-4261-8340-29b42cec2dbe.png)

Could not upload .c and udl file test1.xml directly, hence in a zip.
[small.c.and.udl.zip](https://github.com/notepad-plus-plus/notepad-plus-plus/files/8005434/small.c.and.udl.zip)

**Comment by rdipardo** [comment]
> It has C-Style /* */ comments

Duplicate of https://github.com/notepad-plus-plus/notepad-plus-plus/issues/10988
Set the EOL mode to CRLF are the fold levels will appear correct again.

**Comment by eowmob** [comment]
Shoot, you are right! I wasn't even aware my files had a Unix-EOL.
As I know it now, I can work around it.
Sorry for the duplicate issue. I did not find the other entry.
