### ISSUE TITLE
Path Completion not working regression

### ISSUE THREAD

**Issue by donho** [notepad-plus-plus/notepad-plus-plus#11147]
### Description of the Issue
Path Completion has stopped working seems for quite moment.
It's a regression but it's not due to the removal 2GB restriction. 

### Steps to Reproduce the Issue

1. Type `C:\`
2. Choose menu command `Edit > Auto-Completion > Path Completion` or hit `Ctrl-Alt-Space`  

### Expected Behavior
Auto-completion list appears. All the sub-folder of C drive should be in the list.
  
### Actual Behavior
Nothing happens.

### Debug Information
Notepad++ v8.3   (64-bit)
Build time : Feb  5 2022 - 19:07:43
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 11 (64-bit) 
OS Version : 2009
OS Build : 22000.434
Current ANSI codepage : 1252
Plugins : mimeTools.dll NppConverter.dll NppExport.dll

**Comment by alankilborn** [comment]
I went on a version search to where this feature last worked.
I had to go back to v 6.9 !

**Comment by mpheath** [comment]
@donho 

Testing autocompletion and path completion is one of tests. I repeatly get these 3 msgboxes using the menu entry

```
---------------------------
General Exception
---------------------------
std::bad_alloc
---------------------------
OK   
---------------------------


---------------------------
Recovery initiating
---------------------------
Notepad++ will attempt to save any unsaved data. However, dataloss is very likely.
---------------------------
OK   
---------------------------


---------------------------
Recovery success
---------------------------
Notepad++ was able to successfully recover some unsaved documents, or nothing to be saved could be found.

You can find the results at :

C:\Users\Michael\AppData\Local\Temp\\N++RECOV
---------------------------
OK   
---------------------------
```

and then Notepad++ exits.

With Ctrl+Alt+Space I get

```
---------------------------
Microsoft Visual C++ Runtime Library
---------------------------

This application has requested the Runtime to terminate it in an unusual way.
Please contact the application's support team for more information.

---------------------------
OK   
---------------------------
```

Click OK and crashs Notepad++.

Strange the different behaviours of menu item to keys. Probably irrelevent if fixed. 

<hr>

Added some `printf` calls to get some information.

Output:

```
bufSize: '260'
currentPos: '41'
startPos: '-219'
```

`-219` for start position. Negative integer could be a possible reason for crashing.

So added more characters to get position to 3000 in the document and tried again. Path completion works.

``` cpp
const auto startPos = max(0, currentPos - bufSize);
```

If I change `auto` to `int`, no crash and no path autocomplete. If I replace `currentPos` and `bufSize` with real integers inside `max()`, then it works and I see autocomplete. I consider `max()` does not like `intptr_t` types as I got GCC to show `error: no matching function for call to 'max(int, long long int)'` with separate test code. https://cplusplus.com/reference/algorithm/max/ mentions `Note that invalid arguments cause undefined behavior`. So it might be undefined behaviour with types that `max()` cannot handle.

`sizeof()` displays `8` for `intptr_t` and comparing different byte sizes causes problems, so replace

``` cpp
const auto startPos = max(0, currentPos - bufSize);
```

with

``` cpp
const long long int startPos = (currentPos >= bufSize) ? (currentPos - bufSize) : 0;
```

works ok as it avoids directly comparing 4 byte int type with 8 byte int type. `long long int` is to save precision. `auto` works too though the compiler probably replaces it with `int`.

**Comment by ozone10** [comment]
@mpheath 
Notepad++ rather than using `std::max` is using `max` macro in `windows.h`.
I would use `intptr_t` since for 64 bit it's `long long` (`__int64`) and for 32 bit `int`

**Comment by mpheath** [comment]
@ozone10 

Thanks for the information.
Whether `max` or `std::max`, both seem to dislike comparing `intptr_t` with `int`.

This test works good as comparisons are only with `intptr_t`.

```cpp
#include <iostream>     // std::cout
#include <algorithm>    // std::max
#include <shlwapi.h>    // MAX_PATH

int main () {
	const intptr_t bufSize = MAX_PATH;
	const intptr_t currentPos = 41;
	const intptr_t zero = 0;
	const auto startPos = std::max(zero, currentPos - bufSize);
	std::cout << startPos << '\n';
}
```

In `AutoCompletion.cpp`, changing

```cpp
const auto startPos = max(0, currentPos - bufSize);
```

to

```cpp
const auto startPos = (currentPos > bufSize) ? (currentPos - bufSize) : 0;
```

or

```cpp
const intptr_t startPos = (currentPos > bufSize) ? (currentPos - bufSize) : 0;
```

or

```cpp
const intptr_t zero = 0;
const auto startPos = max(zero, currentPos - bufSize);
```

works for me.

If you can trust the compiler, then `auto` seems OK, though it should be `intptr_t ` if the compiler gets it right unless I am fail to understand.

I changed the ternary `>=` to `>` as doing `currentPos - bufSize` seems meaningless to return `0`. The ternary has the benefit of not needing the `zero` to be declared and assigned a value.
