### ISSUE TITLE
On -n, Np++ does not follow to the line number

### ISSUE THREAD

**Issue by Iton-Horn** [notepad-plus-plus/notepad-plus-plus#11146]
Hello, dear Notepad++ Community!

### Description of the Issue
The command line execution of the following command
C:\Dir\notepad++.exe -n856 C:\Dir\File.txt
opens the File.txt file on the first line, does not follow to the line 856.
Please check.

### Steps to Reproduce the Issue
On the portable x64 and x32 versions of Notepad++:
1. Download Notepad++ from https://notepad-plus-plus.org/downloads/v8.3/
2. Install Notepad++.exe to C:\Dir\
2. Run command line command: "C:\Dir\notepad++.exe -n856 C:\Dir\File.txt".
There is NO "space" between "-n" and "856".

### Expected Behavior
Notepad++ opens the C:\Dir\File.txt file and places the cursor in the line 856.

### Actual Behavior
Notepad++ opens the C:\Dir\File.txt file and places the cursor in the first line.

### Debug Information
Notepad++ v8.3 (32-bit)
Build time : Feb 3 2022 - 03:35:48
Path : C:\Dir\notepad++.exe
Command Line : C:\Dir\File.txt
Admin mode : OFF
Local Conf mode : ON
Cloud Config : OFF
OS Name : Windows 10 Enterprise (64-bit)
OS Version : 2009
OS Build : 19043.1466
Current ANSI codepage : 1251
Plugins : ComparePlugin.dll

###
1. Posted under
[https://community.notepad-plus-plus.org/topic/22517/on-n-np-does-not-follow-to-the-line-number](url)
2. Notepad++ v. 8.2 functions properly, does not have the above described misbehavior.

**Comment by vinsworldcom** [comment]
This is fixed already: (https://github.com/notepad-plus-plus/notepad-plus-plus/commit/deb99ae45bb13c4b028546c47358a4e02bec24b9)
