### ISSUE TITLE
Crash when copying text from Analyse Plugin window

### ISSUE THREAD

**Issue by tillrathmann** [notepad-plus-plus/notepad-plus-plus#11152]
### Description of the Issue
Notepad++ v8.3 (64-bit) crashes when copying text from the Analyse Plugin window.
Notepad++ v8.2.1 (64-bit) was still working.
The 32-bit version of Notepad++ is not affected.

### Steps to Reproduce the Issue
1. Install the Analyse Plugin (1.12.47).
2. Write "test" in the document.
3. Add "test" as search string to the Analyse Plugin and click search.
4. Mark and copy some text in the Analyse Plugin window.
5. The application crashes!

### Debug Information
Notepad++ v8.3   (64-bit)
Build time : Feb  3 2022 - 03:39:05
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 10 Enterprise (64-bit) 
OS Version : 2009
OS Build : 19042.1469
Current ANSI codepage : 1252
Plugins : AnalysePlugin.dll JSMinNPP.dll mimeTools.dll NppConverter.dll NppExport.dll NPPJSONViewer.dll XMLTools.dll 

From Visual Studio:
Unhandled exception at 0x00007FF6F6698195 in notepad++.exe: 0xC000041D: An unhandled exception was encountered during a user callback.
>	notepad++.exe!Scintilla::Editor::WndProc(unsigned int iMessage, unsigned __int64 wParam, __int64 lParam) Line 6419	C++
 	notepad++.exe!Scintilla::ScintillaBase::WndProc(unsigned int iMessage, unsigned __int64 wParam, __int64 lParam) Line 1196	C++
 	notepad++.exe!ScintillaWin::WndProc(unsigned int iMessage, unsigned __int64 wParam, __int64 lParam) Line 2066	C++
 	notepad++.exe!ScintillaWin::DirectFunction(__int64 ptr, unsigned int iMessage, unsigned __int64 wParam, __int64 lParam) Line 3539	C++
 	[External Code]	
 	notepad++.exe!Notepad_plus_Window::isDlgsMsg(tagMSG * msg) Line 380	C++
 	notepad++.exe!wWinMain(HINSTANCE__ * hInstance, HINSTANCE__ * __formal, wchar_t * pCmdLine, int __formal) Line 716	C++

		tr->lpstrText	0x0000000000000001 <Error reading characters of string.>	char *

I tracked it down to this commit:

>Revision: db3308329bd23a073b7de6f4ded2a523b282fcc3
>Author: Don Ho <don.h@free.fr>
>Date: 28.01.2022 04:17:45
>Message:
>Fix crash on opening file with wild card characters
>
>And redefining Sci_PositionCR to 64 bits on x64 build for managing 2GB+ files.
(ref: https://github.com/notepad-plus-plus/notepad-plus-plus/pull/11047#issuecomment-1021540298)
>
>Fix #11098
>----
>Modified: PowerEditor/src/ScintillaComponent/Buffer.cpp
>Modified: scintilla/include/Sci_Position.h

With the old

		typedef long Sci_PositionCR;
in Sci_Position.h instead of

		typedef intptr_t Sci_PositionCR;
the crash doesn't occur.

**Comment by alankilborn** [comment]
Sure seems like this is reported in the wrong place.
Shouldn't it be reported wherever Analyse plugin is supported?

**Comment by rdipardo** [comment]
> Shouldn't it be reported wherever Analyse plugin is supported?

<https://sourceforge.net/p/analyseplugin/bugs/86>

**Comment by rdipardo** [comment]
@tillrathmann,
> Plugins : [ . . . ] XMLTools.dll

You need at least version [3.1.1.11](https://github.com/morbac/xmltools/releases/tag/3.1.1.11) to use XMLTools without crashing 64-bit N++ 8.3 (same vulnerablity as AnalysePlugin).
[Plugins Admin](https://github.com/notepad-plus-plus/nppPluginList/blob/0a71162cf1426f1ee1ebd73530af702089d58333/src/pl.x64.json#L1238-L1239) has not updated to the safe version yet; you'll have to upgrade manually for now.

---
✅ mimeTools [(patched in v2.7)](https://github.com/npp-plugins/mimetools/releases/tag/v2.7)
✅ NppConverter [(patched in v4.4)](https://github.com/npp-plugins/converter/releases/tag/v4.4)
✅ NppExport [(patched in v0.4)](https://github.com/chcg/NPP_ExportPlugin/releases/tag/0.4.0)
✅ JSMinNPP (doesn't use the `SCI_GETTEXTRANGE` API)
✅ NPPJSONViewer (doesn't use the `SCI_GETTEXTRANGE` API)

**Comment by mattesh** [comment]
> ### Description of the Issue
> 
> Notepad++ v8.3 (64-bit) crashes when copying text from the Analyse Plugin window. Notepad++ v8.2.1 (64-bit) was still working. The 32-bit version of Notepad++ is not affected.
> ### Steps to Reproduce the Issue
> 
>     1. Install the Analyse Plugin (1.12.47).
> 
>     2. Write "test" in the document.
> 
>     3. Add "test" as search string to the Analyse Plugin and click search.
> 
>     4. Mark and copy some text in the Analyse Plugin window.
> 
>     5. The application crashes!
> 
> 
> ### Debug Information
> 
> Notepad++ v8.3 (64-bit) Build time : Feb 3 2022 - 03:39:05 Path : C:\Program Files\Notepad++\notepad++.exe Command Line : Admin mode : OFF Local Conf mode : OFF Cloud Config : OFF OS Name : Windows 10 Enterprise (64-bit) OS Version : 2009 OS Build : 19042.1469 Current ANSI codepage : 1252 Plugins : AnalysePlugin.dll JSMinNPP.dll mimeTools.dll NppConverter.dll NppExport.dll NPPJSONViewer.dll XMLTools.dll
> 
> From Visual Studio: Unhandled exception at 0x00007FF6F6698195 in notepad++.exe: 0xC000041D: An unhandled exception was encountered during a user callback.
> 
> > notepad++.exe!Scintilla::Editor::WndProc(unsigned int iMessage, unsigned __int64 wParam, __int64 lParam) Line 6419	C++
> > notepad++.exe!Scintilla::ScintillaBase::WndProc(unsigned int iMessage, unsigned __int64 wParam, __int64 lParam) Line 1196	C++
> > notepad++.exe!ScintillaWin::WndProc(unsigned int iMessage, unsigned __int64 wParam, __int64 lParam) Line 2066	C++
> > notepad++.exe!ScintillaWin::DirectFunction(__int64 ptr, unsigned int iMessage, unsigned **int64 wParam, **int64 lParam) Line 3539	C++
> > [External Code]
> > notepad++.exe!Notepad_plus_Window::isDlgsMsg(tagMSG * msg) Line 380	C++
> > notepad++.exe!wWinMain(HINSTANCE** * hInstance, HINSTANCE** * __formal, wchar_t * pCmdLine, int __formal) Line 716	C++
> 
> ```
> 	tr->lpstrText	0x0000000000000001 <Error reading characters of string.>	char *
> ```
> 
> I tracked it down to this commit:
> 
> > Revision: [db33083](https://github.com/notepad-plus-plus/notepad-plus-plus/commit/db3308329bd23a073b7de6f4ded2a523b282fcc3)
> > Author: Don Ho [don.h@free.fr](mailto:don.h@free.fr)
> > Date: 28.01.2022 04:17:45
> > Message:
> > Fix crash on opening file with wild card characters
> > And redefining Sci_PositionCR to 64 bits on x64 build for managing 2GB+ files.
> > (ref: [#11047 (comment)](https://github.com/notepad-plus-plus/notepad-plus-plus/pull/11047#issuecomment-1021540298))
> > ## Fix #11098
> > Modified: PowerEditor/src/ScintillaComponent/Buffer.cpp
> > Modified: scintilla/include/Sci_Position.h
> 
> With the old
> 
> ```
> 	typedef long Sci_PositionCR;
> ```
> 
> in Sci_Position.h instead of
> 
> ```
> 	typedef intptr_t Sci_PositionCR;
> ```
> 
> the crash doesn't occur.

Can you please check with v1.13-pre-release version?
https://sourceforge.net/p/analyseplugin/discussion/1662529/thread/fb01eb99/#b17b
thx,, Mattes

**Comment by mattesh** [comment]
Hi All,
I finished my release for 1.13-R49 fixing this issue
https://sourceforge.net/projects/analyseplugin/files/binaries/v01.13-R49/
Changes in this version compared to 1.12
Changes since 1.13
 - update to NPP 8.4.1
 - bugfix #86 regression in 64-bit version
 - #49 Drag N Drop files to the patternlist dialog loads them
 - ESC key in patternlist dialog resets edit fields to the selected pattern
 - using cursor up down in pattern list updates content in upper dialog
 - Column Order# for explicit order sorting added
 - #85 Dark Mode support preparation step 1 (new icons added)
 - Caused by update in NPP this plugin is now also GPLv3
 - the result window context menu shows the order number of a pattern if specified

If you detect any issues pls. report to 
https://sourceforge.net/p/analyseplugin/bugs/milestone/1.13/

Thanks, Mattes

**Comment by chcg** [comment]
@mattesh See https://github.com/chcg/AnalysePlugin/compare/master...appveyor_CI and https://ci.appveyor.com/project/chcg/analyseplugin/builds/43753139, maybe you want to add an arm64 build.

**Comment by chcg** [comment]
@mattesh See also https://github.com/notepad-plus-plus/nppPluginList/commit/c5015627c03596191ddc5b0190bd45d9ad39f1fd

**Comment by alankilborn** [comment]
Seems like this issue could be CLOSED.

**Comment by budhisagar** [comment]
In analyze pluging search can we do ORing to do multiple search in one instead of adding multiple world in multiple line ?
Can we group them in one line?

**Comment by alankilborn** [comment]
@budhisagar This is not the correct place to ask questions about how a plugin works; you'll have better luck asking on the plugin support site, or on the [Notepad++ Community](https://community.notepad-plus-plus.org/).

**Comment by budhisagar** [comment]
My mistake ,
Deleted .
