### ISSUE TITLE
Hitting ENTER when Autocomplete suggestion pops up does not select the autocomplete and just linebreaks

### ISSUE THREAD

**Issue by GhbSmwc** [notepad-plus-plus/notepad-plus-plus#11159]
### Description of the Issue
This is the setting I'm using:
![image](https://user-images.githubusercontent.com/13095760/153113075-aeb3b40d-12b6-4bd8-8ab1-5fc4a0dbac1f.png)
I was ending a large text file a while ago with it turned off because it is causing a huge lag storm as I type (I would assume it scans the entire file as I type for guessing 1000s of words). After I turn that back on, this bug occurs:
![NotepadPlusPlus_AutocompleteBug](https://user-images.githubusercontent.com/13095760/153113224-e580c28f-273a-4569-b353-3439770a4e07.gif)
I hit ENTER, and instead of picking that word in the suggestion and not entering a new line, it does not select that item on the list and inserts a new line

### Steps to Reproduce the Issue

1. When, especially programming JavaScript (that is what I use), type in some keywords, say ``foo bar``
2. Enter a couple of new lines, like in the gif here.
3. Then type ``b`` and it should show some of the previous words you type on the list
4. Select any of the words, and hit ENTER (not clicking)

### Expected Behavior

On the word suggestion, hitting ENTER is supposed to pick that word and insert it in the text area you are typing in.
### Actual Behavior

New line is inserted instead of just use the word selected if you hit ENTER while focused on the word suggestion.
### Debug Information

![image](https://user-images.githubusercontent.com/13095760/153113797-fa23f6dd-ad5c-46cc-af31-f5052b1c921c.png)

**Comment by dfs-** [comment]
In settings check the box „ENTER“ in the group „Insert selection.“

**Comment by GhbSmwc** [comment]
oh, didn't know it is called "insert selection". Okay then.
