### ISSUE TITLE
Make translatable these strings

### ISSUE THREAD

**Issue by kubalav** [notepad-plus-plus/notepad-plus-plus#11162]
### Description of the Issue
Following strings are missing in language file:

**View menu:**
Hide Line Number Margin
Hide Bookmark Margin
Hide Folder Margin
![view](https://user-images.githubusercontent.com/37414585/153189541-1c07959e-c881-4f59-b19c-7c632bac2fab.png)

**Language menu:**
Markdown (preinstalled)
Markdown (preinstalled dark mode)
![language](https://user-images.githubusercontent.com/37414585/153189570-b7d1edca-0644-4645-85e4-d89f2f4aacc4.png)

### Debug Information
Notepad++ v8.2.1   (32-bit)
Build time : Jan 19 2022 - 18:38:49
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : 
Admin mode : ON
Local Conf mode : ON
OS Name : Windows 10 Enterprise (64-bit) 
OS Version : 2009
OS Build : 19044.1503
Current ANSI codepage : 1250
Plugins : AutoSave.dll combine.dll ComparePlugin.dll DSpellCheck.dll HTMLTag_unicode.dll Linefilter3.dll LocationNavigate.dll Merge files in one.dll mimeTools.dll NppConverter.dll NppExport.dll NppTextFX.dll NppTextViz.dll PreviewHTML.dll SourceCookifier.dll XMLTools.dll _CustomizeToolbar.dll

**Comment by alankilborn** [comment]
Those menu items aren't provided by Notepad++ and thus aren't translatable by its translation engine.
They must be provided by one of your plugins.

Recommend issue closure.

**Comment by thomassmith311** [comment]
^^

As for the Markdown, that is defined in the UDL itself. Under Language go to User Defined Language > Open User Defined Language Folder.
![image](https://user-images.githubusercontent.com/19561856/153237862-3fd30289-d830-4bf3-9219-bc11460022b9.png)
![image](https://user-images.githubusercontent.com/19561856/153237942-89f4354e-ee08-4b6a-9086-ade1c2a91a65.png)
Open one in a code editor:
![image](https://user-images.githubusercontent.com/19561856/153238042-043e7159-f1a1-4550-a87f-49805c292489.png)
Change `<UserLang name="Markdown (preinstalled)"...` to whatever translation you want. Then the same thing with the other file.

**Comment by kubalav** [comment]
@alankilborn @thomassmith311 
Thanks, boys.
