### ISSUE TITLE
Crash when typing XML closing tag

### ISSUE THREAD

**Issue by araghon007** [notepad-plus-plus/notepad-plus-plus#11167]
### Description of the Issue
When closing a XML tag, Notepad++ crashes as I type the last letter of the tag name. Happens in v8.3. If the file is saved in an older version, and opened in v8.3, Notepad++ will crash. Can cause a crash on startup.

### Steps to Reproduce the Issue
1. Create a new file
2. Set the language to XML
3. Type in:
```
<test>
</test
```
4. The program will crash as you type in the last letter

### Expected Behavior
Notepad++ should highlight the opening tag, as in v8.2.1

### Actual Behavior
Notepad++ crashes

### Debug Information
Notepad++ v8.3   (64-bit)
Build time : Feb  3 2022 - 03:39:05
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line :
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 11 (64-bit)
OS Version : 2009
OS Build : 22000.434
Current ANSI codepage : 1252
Plugins : mimeTools.dll NppConverter.dll NppExport.dll

**Comment by rdipardo** [comment]
Duplicate of #11128, #11137 and #11157

**Comment by araghon007** [comment]
Ah thanks, I didn't think about looking at closed issues, oops
