### ISSUE TITLE
command line option "scroll to indicated line" not working

### ISSUE THREAD

**Issue by Hubert21** [notepad-plus-plus/notepad-plus-plus#11161]
### Description of the Issue

The command line option "scroll to indicated line", -nLineNumber, is not working anymore in 8.3 (it is working on 8.2.1)

### Steps to Reproduce the Issue

In a windows cmd :
"npp.8.3.portable.x64\notepad++.exe" -n205 my_file.py

### Expected Behavior

to go to the correct line

### Actual Behavior

stays on line 1

### Debug Information
Notepad++ v8.3   (64-bit)
Build time : Feb  3 2022 - 03:39:05
Path : C:\Users\norbert\Desktop\npp.8.3.portable.x64\notepad++.exe
Command Line : -n205 E:\My_programs\my_file.py
Admin mode : OFF
Local Conf mode : ON
Cloud Config : OFF
OS Name : Windows 10 Pro (64-bit) 
OS Version : 2009
OS Build : 19043.1466
Current ANSI codepage : 1252
Plugins : mimeTools.dll NppConverter.dll NppExport.dll

**Comment by dfs-** [comment]
Already fixed as of #11132
Will work again in the upcoming version of N++.
