### ISSUE TITLE
Notepad++ closes suddenly

### ISSUE THREAD

**Issue by mariojr18** [notepad-plus-plus/notepad-plus-plus#11166]
### Description of the Issue
When you open a new file, switch to XML language type and type `<a></a` notepad++ closes the application.

### Steps to Reproduce the Issue

1. Open the notepad++
2. Open new file
3. Go to the language menu and select the XML option
4. In the new file, write de code `<a></a`

### Expected Behavior
do not close the application

### Actual Behavior
close the application

### Debug Information
Notepad++ v8.3   (64-bit)
Build time : Feb  3 2022 - 03:39:05
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 10 Pro (64-bit) 
OS Version : 1909
OS Build : 18363.1556
Current ANSI codepage : 1252
Plugins : mimeTools.dll NppConverter.dll NppExport.dll

**Comment by imsirovicnurudin** [comment]
Can confirm this does not occur under the previous release **8.2.1**

**Comment by ArkadiuszMichalski** [comment]
Fixed in https://github.com/notepad-plus-plus/notepad-plus-plus/commit/73a4cdc1040c15cee87ff21de94dd7669cdda607
The fix will be in the next release.
