### ISSUE TITLE
Issues with large files

### ISSUE THREAD

**Issue by Merdider** [notepad-plus-plus/notepad-plus-plus#11165]
### Description of the Issue
A strange space at the end of a document in a large .reg file. This space doesn't count the lines in the document.

### Steps to Reproduce the Issue
1. Export a backup file of your Registry in Windows 10.
2. Open the file with Notepad Plus Plus.

### Expected Behavior
Ending on the last line.

### Actual Behavior
A large space at the end of the file.
![captura](https://user-images.githubusercontent.com/99332393/153197700-a5151dee-4d7f-4c64-8979-65055366be05.png)

### Debug Information
Notepad++ v8.3   (64-bit)
Build time : Feb  3 2022 - 03:39:05
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 10 Pro (64-bit) 
OS Version : 2009
OS Build : 19044.1503
Current ANSI codepage : 1252
Plugins : mimeTools.dll NppConverter.dll NppExport.dll

**Comment by imsirovicnurudin** [comment]
This is expected behavior if you have enabled **Enable scrolling beyond last** line in **Settings** -> **Editing**
