### ISSUE TITLE
updating issue

### ISSUE THREAD

**Issue by modz2014** [notepad-plus-plus/notepad-plus-plus#11170]
how make GUP find the latest version of notepad++ if the current version is 64bit not 32bit

**Comment by dail8859** [comment]
You'll have to provide more details because I'm not sure if there is even a problem. It would have helped to follow the template provided.

**Comment by modz2014** [comment]
Well GUP doesn't search for 64bit when updating only 32bit

**Comment by modz2014** [comment]
There isn't really a issues just when you go and update notepad ++ keeps updating to 32bit not 64bit

**Comment by donho** [comment]
If you want to be assisted, you have to ask the right question.
Please use the template to provide the complete information.
