### ISSUE TITLE
为啥  notepad++  编辑 markdown 文件,右边窗口不能实时预览

### ISSUE THREAD

**Issue by huyang19881115** [notepad-plus-plus/notepad-plus-plus#11171]
我使用的notepad++ 版本是  v8.1.9.3   64位的
安装了 markdown panal 的插件，实现 md 文件的预览，但是 实际还是左边源文件更改后，右边不会同步去更新，不知道怎么回事。

在有一个电脑上，是实时更新的，是我电脑缺少了啥东西吗？
### Steps to Reproduce the Issue

1. 
2. 
3.

**Comment by dail8859** [comment]
You will need to open an issue with the developer of the markdown panel plugin.

I think this is the correct link: https://github.com/mohzy83/NppMarkdownPanel/issues
