### ISSUE TITLE
Style All Occurrences of token Doesnot work when there is '[ ]' brackets in the text. Earlier versions it used to work 

### ISSUE THREAD

**Issue by rajesh-dhiman** [notepad-plus-plus/notepad-plus-plus#11185]
### Description of the Issue

Style All Occurrences of token Doesnot work when there is '[ ]' brackets in the text. Earlier versions it used to work 

### Steps to Reproduce the Issue

1. Have text  like  Hello how [some text] are you? 
2.  Try to style [some text]  with any color option
3.  Does not Style it..

### Expected Behavior
Earlier versions of np++ was able to do that

### Actual Behavior
nothing happens

### Debug Information
Notepad++ v8.1.9.1   (64-bit)
Build time : Nov 13 2021 - 15:28:20
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : "C:\WorkSpace\Temporary\Logs\XXXXXXXXXXXX03Feb2022_162523.log"
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 10 Enterprise (64-bit) 
OS Version : 2009
OS Build : 19042.1466
Current ANSI codepage : 1252
Plugins : mimeTools.dll NppConverter.dll NppExport.dll

**Comment by alankilborn** [comment]
Settings have been added to control how this works; probably need to adjust yours:

![image](https://user-images.githubusercontent.com/77065706/153683323-4e6465ec-3c9b-420f-945e-b353533d6e47.png)

**Comment by rajesh-dhiman** [comment]
I think "Match whole word only" was default ON in this new version checking that off, started working..

These small things are hard to find out..

Thank you..
