### ISSUE TITLE
Status of x64 plugins affected by ABI changes in N++ 8.3

### ISSUE THREAD

**Issue by rdipardo** [notepad-plus-plus/notepad-plus-plus#11198]
### Background 

Since version  [8.3], x64 builds of Notepad++ can open files >2GiB in size. To achieve this, the type of Scintilla's `Sci_PostionCR` message was [changed] to `intptr_t`, which expands to eight bytes on x86_64 architecture. 

See:
- https://github.com/notepad-plus-plus/notepad-plus-plus/issues/10921
- https://community.notepad-plus-plus.org/topic/22471/recompile-your-x64-plugins-with-new-header

### Plugin List

The following collects what has been reported[^1] about plugins distributed in x86_64 versions

| Name             | Status          | First patched version   | Suggested alternative (pre-release, or from a different source than the [Plugins Admin] distribution)   |
| :--------------- | :-------------: | :------------: | :------------------------------------------------------------------------------------------------------ |
| [AnalysePlugin]  | &#x2705;        | [1.13.49][anlyz]   |                                |
| AutoIndentDetect | &#x2705;        | [2.1]          |                                                                                                         |
| BracketsCheck    | &#x2705;        | *not affected* |                                                                                                         |
| ColumnTools      | &#x2705;        | [1.4.4.1]      |                                                                                                         |
| [Comment Wrap]   | &#x2705;        |[1.0.0.5][derek]|                                                                                                         |
| ComparePlugin    | &#x2705;        | [2.0.2]        |                                                                                                         |
| [CS-Script]      | &#x2705;        | [1.7.29][css]  |                                                                                                         |
| [CsvQuery]       | &#x2705;        | [1.2.9][csvq]    |                                                                                                     |
| DSpellCheck      | &#x2705;        | [1.4.23]       |                                                                                                         |
|[Elastic Tabstops]| &#x2705;        | [1.3.2]        | https://ci.appveyor.com/project/dail8859/elastictabstops/builds/43155677/job/8aohta1g2deuc24t/artifacts |
| FWDataViz        | &#x2705;        | [2.4.0.2]      |                                                                                                         |
| GitSCM           | &#x2705;        | [1.4.6.1]      |                                                                                                         |
| GotoLineCol      | &#x2705;        | [2.2.0.2]      |                                                                                                         |
| HTML Tag         | &#x2705;        | [1.2]          |                                                                                                         |
|[ jN]         | &#x2705;        | [2.2.185.7]          |                                                                                                         |
| JSMinNPP         | &#x2705;        | *not affected* |                                                                                                         |
| JSFunctionViewer | &#x2705;        | *not affected* |                                                                                                         |
| [LuaScript]      | &#x2705;        | [0.12][lua]    |                                                                                                         |
| MarkdownPanel    | &#x2705;        | *not affected* |                                                                                                         |
| MarkdownViewer++ | &#x2705;        | *not affected* |                                                                                                         |
| mimeTools        | &#x2705;        | [2.7]          |                                                                                                         |
| NppConverter     | &#x2705;        | [4.4]          |                                                                                                         |
| NppExport        | &#x2705;        | [0.4]          |                                                                                                         |
| [NppGist]        | &#x2705;        | [1.5.1][gist]  |                                                                                                         |
| NPPJSONViewer    | &#x2705;        | *not affected* |                                                                                                         |
| NppTaskList      | &#x2705;        | [2.4]          |                                                                                                         |
|[nvda-notepadPlusPlus]| &#x2705;    | [2022.05.1][nvda]<a id="nvda-addon"></a> |                                                                                     |
| [Papyrus Script] | &#x2705;        | [0.3.0.24]     |                                                                                                         |
| [Python Indent]  | &#x2705;        |[1.0.0.4][derek]|                                                                                                         |
| [PythonScript]   | &#x2705;        | [2.0.0]        | https://github.com/bruderstein/PythonScript/releases/tag/v3.0.12 (*Note* Win7 support [has been dropped])         |
| QuickColorPicker | &#x2705;        | [2.1.2.1]      |                                                                                                         |
| QuickText        | &#x2705;        | [0.2.4.1]      |                                                                                                         |
| SecurePad        | &#x2705;        | [2.4][secpad]  |                                                                                                         |
| [SelectToClipboard] | &#x2705; | [1.0.3][cb] |                                                                                                               |
| SpeechPlugin     | &#x2705;        | [0.4][SpPl]    |                                                                                                         |
| VisualStudioLineCopy | &#x2705;    |[1.0.0.2][derek]|                                                                                                         |
| [TagLEET]        | &#x274C;        | [???][TLpre]   | https://github.com/vinsworldcom/nppTagLEET/releases/tag/1.3.10.1                                        |
| WakaTime         | &#x2705;        | *not affected* |                                                                                                         |
| XBrackets Lite   | &#x2705;        | [1.3.1][XBL]   |                                                                                                         |
| XMLTools         | &#x2705;        | [3.1.1.12]     |                                                                                                         |

### Related Issues 

*Only those reported against N++ are listed*

*To expedite closing duplicates, maintainers are encouraged to mention this issue*

- #11203
- #11193
- #11173
- #11167
- #11157
- #11137
- #11133
- #11128
- #11104
- #11103
- #11101
- https://community.notepad-plus-plus.org/topic/22619/notepad-8-3-1-crashes-and-closes-without-warning
- https://community.notepad-plus-plus.org/topic/22575/notepad-crashing
- https://community.notepad-plus-plus.org/topic/22560/notepad-crashes-after-i-use-the-delete-button-on-keyboard-in-a-text-file
- https://community.notepad-plus-plus.org/topic/22543/notepad-crashes-while-coding-in-html
- https://community.notepad-plus-plus.org/topic/22521/comment-wrap-plugin-crashes-in-notepad-8-3

[^1]: Current as of 2022-11-08 1:52 PM EST

---
**Notes** 

- the [Win32::Mechanize::NotepadPlusPlus] Perl module has been patched in version [0.009](https://github.com/pryrt/Win32-Mechanize-NotepadPlusPlus/releases/tag/v0.009)
- QuickColorPicker is the [new name][2.1.2.1] of the ([abandoned]) NppQCP plugin

[AnalysePlugin]: https://github.com/notepad-plus-plus/notepad-plus-plus/issues/11152
[anlyz]: https://sourceforge.net/projects/analyseplugin/files/binaries/v01.13-R49/
[Comment Wrap]: https://community.notepad-plus-plus.org/topic/22521/comment-wrap-plugin-crashes-in-notepad-8-3
[CsvQuery]: https://github.com/jokedst/CsvQuery/issues/33
[css]: https://github.com/oleg-shilo/cs-script.npp/releases/tag/v1.7.29.0
[csvq]: https://github.com/jokedst/CsvQuery/releases/tag/v1.2.9
[CS-Script]: https://github.com/notepad-plus-plus/notepad-plus-plus/issues/11232
[Elastic Tabstops]: https://github.com/dail8859/ElasticTabstops/issues/28
[LuaScript]: https://github.com/dail8859/LuaScript/issues/92
[NppGist]: https://github.com/KvanTTT/NppGist/issues/20
[nvda-notepadPlusPlus]: https://github.com/nvaccess/nvda/pull/13364#issuecomment-1045524646
[nvda]: https://github.com/derekriemer/nvda-notepadPlusPlus/releases/tag/2022.05.1
[Papyrus Script]: https://github.com/blu3mania/npp-papyrus/issues/20
[Python Indent]: https://community.notepad-plus-plus.org/topic/22800/can-no-longer-paste-onto-a-screen
[PythonScript]: https://github.com/bruderstein/PythonScript/issues/218
[Win32::Mechanize::NotepadPlusPlus]: https://github.com/pryrt/Win32-Mechanize-NotepadPlusPlus
[PerlScriptBug]: https://github.com/pryrt/Win32-Mechanize-NotepadPlusPlus/issues/84
[SelectToClipboard]: https://github.com/KubaDee/SelectToClipboard/issues/1
[Tagleet]:https://github.com/gstavi/npp/tree/master/tagleet
[TLpre]:https://sourceforge.net/projects/tagleet/files/
[jN]: https://github.com/sieukrem/jn-npp-plugin/issues/110

[2.1]: https://github.com/Chocobo1/nppAutoDetectIndent/releases/tag/2.1
[1.4.4.1]: https://github.com/vinsworldcom/nppColumnTools/releases/tag/1.4.4.1
[2.0.2]: https://github.com/pnedev/compare-plugin/releases/tag/v2.0.2
[1.4.23]: https://github.com/Predelnik/DSpellCheck/releases/tag/v1.4.23
[1.3.2]: https://github.com/dail8859/ElasticTabstops/commit/dea282cf2902b3070623a66601a3b721f42f914b
[2.4.0.2]: https://github.com/shriprem/FWDataViz/releases/tag/v2.4.0.2
[1.4.6.1]: https://github.com/vinsworldcom/nppGitSCM/releases/tag/1.4.6.1
[2.2.0.2]: https://github.com/shriprem/Goto-Line-Col-NPP-Plugin/releases/tag/v2.2.0.2
[1.2]: https://community.notepad-plus-plus.org/topic/22503/new-version-of-html-tag
[lua]: https://github.com/dail8859/LuaScript/releases/tag/v0.12
[2.7]: https://github.com/npp-plugins/mimetools/releases/tag/v2.7
[4.4]: https://github.com/npp-plugins/converter/releases/tag/v4.4
[0.4]: https://github.com/chcg/NPP_ExportPlugin/releases/tag/0.4.0
[SpPl]: https://github.com/chcg/SpeechPlugin/releases/tag/v0.4.0
[1.3.9.7]: https://github.com/vinsworldcom/nppTagLEET/releases/tag/1.3.9.7
[0.3.0.24]: https://github.com/blu3mania/npp-papyrus/releases/tag/v0.3.0
[derek]: https://github.com/notepad-plus-plus/nppPluginList/pull/436
[2.0.0]: https://github.com/bruderstein/PythonScript/releases/tag/v2.0.0
[has been dropped]: https://github.com/bruderstein/PythonScript/issues/203#issuecomment-851680090
[2.1.2.1]: https://github.com/vinsworldcom/nppQCP/releases/tag/2.1.2.1
[0.2.4.1]: https://github.com/vinsworldcom/nppQuickText/releases/tag/0.2.4.1
[gist]: https://github.com/KvanTTT/NppGist/releases/tag/1.5.1
[secpad]: https://github.com/DominicTobias/SecurePad/releases/tag/v2.4
[cb]: https://github.com/KubaDee/SelectToClipboard/releases/tag/v1.0.3
[2.4]: https://github.com/Megabyteceer/npp-task-list/releases/tag/v2.4.0
[XBL]: https://github.com/d0vgan/npp-XBracketsLite/releases/tag/v131
[3.1.1.12]: https://github.com/morbac/xmltools/releases/tag/3.1.1.12
[2.2.185.7]: https://github.com/sieukrem/jn-npp-plugin/releases/tag/2.2.185.7

[8.3]: https://github.com/notepad-plus-plus/notepad-plus-plus/releases/tag/v8.3
[changed]: https://github.com/notepad-plus-plus/notepad-plus-plus/commit/db3308329bd23a073b7de6f4ded2a523b282fcc3#diff-8968b5cad4cc8f62c9204894eea9941dac353af428a26be64f52055e99992040
[abandoned]: https://github.com/nulled666/nppqcp#this-project-was-discontined
[Plugins Admin]: https://github.com/notepad-plus-plus/nppPluginList/blob/0bd66df69aad5fd06cfde0273483a84cd66492b2/src/pl.x64.json

**Comment by xomx** [comment]
What I miss in N++ is a definition of some NPP_PLUGIN_INTERFACE_VERSION. It should be obligatory for all the N++ plugins (ABI compatibility check). Or am I overlooking something?

Unfortunately even the above NPP_PLUGIN_INTERFACE_VERSION does not solve current external apps Scintilla/N++ incompatibility (e.g. NVDA). Scintilla itself should abandon its archaic `typedef long Sci_PositionCR;` for the Windows 64-bit platform.

**Comment by vinsworldcom** [comment]
@rdipardo I would not list TagLEET 1.3.9.7 as fixed.  The original author @gstavi of the official [TagLEET](https://sourceforge.net/projects/tagleet/) still has the links in the plugin list and my version is a just a copy I work on making improvements that I wanted that diverged from what @gstavi was supporting at the time.  I only create "pre-releases" and they are not in the official plugin list.

Further, my 1.3.9.7 version just compiles with the new headers to stop the access violation crash.  I do not correct all the Scintilla positions returning `Sci_Position` instead of `int` so while it works in >N++ 8.3, it will most likely still crash on >2Gb files.

Cheers.

**Comment by rdipardo** [comment]
@xomx, 
> What I miss in N++ is a definition of some NPP_PLUGIN_INTERFACE_VERSION. It should be obligatory for all the N++ plugins (ABI compatibility check). Or am I overlooking something?

Something like it was suggested after the `SCNotification` structure was enlarged in N++ 7.7

- https://github.com/notepad-plus-plus/notepad-plus-plus/issues/5741

The (proposed) ABI check was only intended for CI workflows: https://github.com/notepad-plus-plus/nppPluginList/issues/250#issuecomment-751371466
All previously implemented attempts at catching problem plugins at runtime have been limited to intercepting the library loader, a recent example being [HexEdit](https://github.com/notepad-plus-plus/notepad-plus-plus/pull/10972/files).

@ArkadiuszMichalski has developed an automated plugin crash detector: <https://github.com/ArkadiuszMichalski/NPP_tools>
Likewise, it only catches exceptions during DLL load. Testing Scintilla interop would require a kind of Selenium framework for text editors.

> IMO: They (Scintilla) know that this is a problem, see my comment about SciTe [here].

As you pointed out, SciTE uses only `Sci_Position`, which has been `typedef`ed as `ptrdiff_t` since [version 4.0.0]. 
N++ currently links against [4.4.6], so the platform-independent `Sci_Position` was always available for large file support (as the author of XBrackets Lite has just [recently demonstrated]). Granted, a  `Sci_Position` would have still left many plugins broken (something SciTE doesn't have to worry about), but using the given interface type would have eliminated the need to patch Scintilla 5.x (which [retains] the legacy `Sci_PositionCR`), whenever the long-awaited [platform jump](#10504) is finished.

[here]: https://github.com/notepad-plus-plus/notepad-plus-plus/pull/11047#issuecomment-1016190937

[version 4.0.0]: https://sourceforge.net/p/scintilla/code/ci/a313995bcaea98b2702439ce1781fb79ccc5a492/tree/include/Sci_Position.h?diff=3b4435f30201c9ca9442ea9642a5012d480835c3

[4.4.6]: https://github.com/notepad-plus-plus/notepad-plus-plus/commit/d7819cf601051510b7fa1640ca17fedad297e1f8
[recently demonstrated]: https://github.com/d0vgan/npp-XBracketsLite/commit/ff82c2922c80689c58c2bb4235ad12e11ab6e2e9#diff-a7e76cb7ee674360de35d7ad8319044cda5667552930a97f83921df508b68d59R82

[retains]: https://sourceforge.net/p/scintilla/code/ci/default/tree/include/Sci_Position.h#l21

**Comment by vinsworldcom** [comment]
> XMLTools

The most updated version is [3.1.1.12](https://github.com/morbac/xmltools/releases/tag/3.1.1.12).

**Comment by vinsworldcom** [comment]
@rdipardo You may also add:

[CsvQuery](https://github.com/jokedst/CsvQuery) by @jokedst with the open issue at:  https://github.com/jokedst/CsvQuery/issues/33

In an email correspondence, he said he was still supporting the plugin and would provide a fix, though no ETA.

Cheers.

**Comment by rdipardo** [comment]
### Update
- new stable [PythonScript release](https://github.com/bruderstein/PythonScript/releases/tag/v2.0.0)

**Comment by rdipardo** [comment]
@xomx ,
> What I miss in N++ is a definition of some NPP_PLUGIN_INTERFACE_VERSION. It should be obligatory for all the N++ plugins (ABI compatibility check). Or am I overlooking something?
> 
<https://github.com/notepad-plus-plus/nppPluginList/issues/416>

7.7 was the first opportunity, then along comes 8.3 . . . maybe the 3rd time will be the charm?

**Comment by xomx** [comment]
If an `INTERFACE_VERSION` exists, we can e.g.:
```
// For Sci_CharacterRange  which is defined as long to be compatible with Win32 CHARRANGE
#if INTERFACE_VERSION > 1
typedef intptr_t Sci_PositionCR;
#else
typedef long Sci_PositionCR;
#endif
```

Unfortunately a dynamic flexible API/ABI is not easy to [implement](http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2020/p2123r0.html). So using the above `INTERFACE_VERSION` (together with the above mentioned `nppPluginList` proposal of `npp-version`) is probably the easiest way, how to automatically ensure the ABI compatibility of N++ plugins in the future.

**Comment by vinsworldcom** [comment]
@rdipardo AnalysePlugin is on the way to being fixed:  [[v01.13-pre1](https://sourceforge.net/projects/analyseplugin/files/binaries/v01.13-pre1/)](https://sourceforge.net/projects/analyseplugin/files/binaries/v01.13-pre1/)

**Comment by rdipardo** [comment]
### Update

 [Plugins Admin 1.4.9] will feature new stable versions of Comment Wrap, Python Indent and VisualStudioLineCopy.

[Plugins Admin 1.4.9]: https://github.com/notepad-plus-plus/nppPluginList/pull/436

**Comment by rdipardo** [comment]
### Update
- a stable release of [ElasticTabstops](https://github.com/dail8859/ElasticTabstops/pull/30) is forthcoming

**Comment by vinsworldcom** [comment]
@rdipardo I have an [alternative for CsvQuery](https://github.com/vinsworldcom/CsvQuery/releases/tag/v1.2.9)

**Comment by rdipardo** [comment]
> @rdipardo I have an [alternative for CsvQuery](https://github.com/vinsworldcom/CsvQuery/releases/tag/v1.2.9)

Noted.

**Comment by rdipardo** [comment]
P.S. 
In case anyone wants to adopt another orphaned plugin, I [posted a patched build of SelectToClipboard][0], but @KubaDee still hasn't reacted.

[0]: https://github.com/KubaDee/SelectToClipboard/issues/1#issuecomment-1092083743

**Comment by jokedst** [comment]
I've released a [new version](https://github.com/jokedst/CsvQuery/releases/tag/v1.2.9) of CsvQuery. A [pull request](https://github.com/notepad-plus-plus/nppPluginList/pull/442) for the plugin list has been created. So no need to switch to the alternative :P

**Comment by donho** [comment]
@jokedst @vinsworldcom 
List updated.

**Comment by vinsworldcom** [comment]
@donho, thanks - but the list above in the first comment of this issue for CsvQuery should also be updated to reflect:

First patched version: 1.2.9
Suggested alternative (pre-release, or from a different source than the Plugins Admin distribution):  `[blank]`

**Comment by rdipardo** [comment]
> I have removed my forked repo so the link currently in "Suggested alternative ..." no longer works

@vinsworldcom, you can restore it anytime within the next 30 days at https://github.com/settings/deleted_repositories

**Comment by vinsworldcom** [comment]
@rdipardo thanks, but I'm hoping there isn't a need to, since @jokedst has updated the official version!

Cheers.

**Comment by KubaDee** [comment]
> P.S. In case anyone wants to adopt another orphaned plugin, I [posted a patched build of SelectToClipboard](https://github.com/KubaDee/SelectToClipboard/issues/1#issuecomment-1092083743), but @KubaDee still hasn't reacted.

Thanks for pointing me. Just fixed it now. PR into plugin-list will follow soon.

**Comment by rdipardo** [comment]
The next major breaking change has been announced: [Add SCI_GETTEXTRANGEFULL for 64-bit positions](https://groups.google.com/g/scintilla-interest/c/mPLwYdC0-FE)

**Comment by rdipardo** [comment]
Updated with [newest jN release](https://github.com/sieukrem/jn-npp-plugin/releases/tag/2.2.185.7).

**Comment by rdipardo** [comment]
BTW, informational issues like this one should be [pinned to the top of the issue tracker](https://docs.github.com/en/issues/tracking-your-work-with-issues/pinning-an-issue-to-your-repository). 
It will remain visible even after it's closed.

**Comment by rdipardo** [comment]
Closing because:

1. The last remaining hold-out is the [orignal TagLEET plugin][4], which [seems abandoned][0].
   The [patched fork][1] should be good enough for most users. Any problems with it can be reported to the plugin maintainer(s).

2. Scintilla has begun providing [64-bit positions on the Windows platform][3].
   All current and future plugin develpment should be utilizing the new suite of `*FULL` APIs. Unmaintianed plugins will eventually be left behind; but that will be a separate issue entirely.

[0]: https://github.com/gstavi/npp/tree/master/tagleet
[1]: https://github.com/vinsworldcom/nppTagLEET/releases
[3]: https://groups.google.com/g/scintilla-interest/c/mPLwYdC0-FE
[4]: https://sourceforge.net/projects/tagleet/files/
