### ISSUE TITLE
Feature suggestion: Copy find results of only highlighted text

### ISSUE THREAD

**Issue by GhbSmwc** [notepad-plus-plus/notepad-plus-plus#11201]
### Description of the Issue

When searching for text, and ``find all in current document``, the output displays the results line-by-line, and I would like the contextmenu on that find result to have a new option that copies only the text portion that matches and not the entire thing.

For example:
I search `foo((?= bar)|$)` when the text area is this:
```
foo bar
```
and the result is this (github is not letting me use highlight using the mark tag, so I had to italicize it):

_foo_ bar

And when copying it, it copes the whole line instead of just the foo.

So I would like it to have the option to only copy matched text instead of the entire lines that have a match.

**Comment by alankilborn** [comment]
Use the _Mark_ tab to redmark your search hits (tick _Wrap around_), then use the _Copy Marked Text_ button.

**Comment by GhbSmwc** [comment]
Thanks.

**Comment by niczoom** [comment]
So many features. This is brilliant, thanks for sharing.
