### ISSUE TITLE
Crash on closing html tags

### ISSUE THREAD

**Issue by meypi** [notepad-plus-plus/notepad-plus-plus#11203]
### Description of the Issue

Notepad++ 64 bit 8.3 crashes when manually (no auto complete) typing html tags.
### Steps to Reproduce the Issue

1. Open new document
2. Change language to PHP
3. type: &lt;head&gt;&lt;/head&gt;

### Expected Behavior

Nothing

### Actual Behavior

Notepad++ 64 bit 8.3 crashed

### Debug Information

Notepad++ v8.3   (64-bit)
Build time : Feb  3 2022 - 03:39:05
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 11 (64-bit) 
OS Version : 2009
OS Build : 22000.493
Current ANSI codepage : 1252
Plugins : ComparePlugin.dll mimeTools.dll NppConverter.dll NppExport.dll

**Comment by vinsworldcom** [comment]
Known bug. Will be fixed in the next release

**Comment by NicusorN5** [comment]
Also works on HTML language.

**Comment by ArkadiuszMichalski** [comment]
Fixed.
