### ISSUE TITLE
More granular theme control

### ISSUE THREAD

**Issue by UncleFred** [notepad-plus-plus/notepad-plus-plus#11207]
NotePad++ dark theme is great. Is it possible to control the indicated visual elements?

![2022-02-14_0-57-55](https://user-images.githubusercontent.com/5650331/153809691-1fd21c11-3cbd-4031-897f-239c5cda1d58.jpg)

**Comment by ozone10** [comment]
IRC that yellow text is controlled by link color. And for other not possible.
