### ISSUE TITLE
Regression: wrong behavior on double-clicking a line in Search Results

### ISSUE THREAD

**Issue by Yaron10** [notepad-plus-plus/notepad-plus-plus#11215]
**STR:**
Open a new file.
Paste the following two lines:
```
Test
Test
```
Search for `Test`.
Double-click a line in the _Search Results_ window.

**Result:**
![תמונה](https://user-images.githubusercontent.com/10229320/154168513-faeb2156-0fad-4c0e-9594-194d8b4c1714.png)

**Caused by https://github.com/notepad-plus-plus/notepad-plus-plus/commit/c0be50494ceba80bd1c380f64c9c02391f926526.**

***
Notepad++ v8.3.1   (64-bit)
Build time : Feb 13 2022 - 15:41:12
Path : C:\---\npp.8.3.1.portable.x64\notepad++.exe
Command Line : 
Admin mode : ON
Local Conf mode : ON
Cloud Config : OFF
OS Name : Windows 10 Pro (64-bit) 
OS Version : 2009
OS Build : 19042.985
Current ANSI codepage : 1255
Plugins : mimeTools.dll NppConverter.dll NppExport.dll

**Comment by donho** [comment]
@Yaron10 
Thank you very much for pointing out the culprit commit.
That saves me a lot of time!

**Comment by Yaron10** [comment]
@donho,

I'm glad I've found the relevant commit.
Thank you for the quick fix. I appreciate your time and work. 👍

**Comment by chcg** [comment]
@Yaron10 Thanks for finding this.
@donho Thanks for fixing it.

**Comment by Yaron10** [comment]
@chcg,

> Maybe it should be noted that this is not happening for saved files.

:+1:
