### ISSUE TITLE
[2GB+] cmdline params structs & session.xml adaptation

### ISSUE THREAD

**Issue by xomx** [notepad-plus-plus/notepad-plus-plus#11213]
This problem has been identified while fixing #11131 .

### Description of the Issue
Some members (`_line2go`, `_column2go` and `_pos2go`) from the `CmdLineParams` & `CmdLineParamsDTO` structs (".\PowerEditor\src\Parameters.h") need `int` to `intptr_t` change to support 2GB+ files. Saving & loading of the 'session.xml' needs a 2GB+ adaptation too.

### Steps to Reproduce the Issue
1. Open 64-bit N++ (v8.3+).
2. Load a 2GB+ file (I will use a file with exactly 2 GB = 2147483648 B as an example here).
3. Make sure you have the 'Remember current session for next launch' checked in Settings -> Preferences... -> Backup.
4. Scroll down & move cursor to the very end of this file (check that the 'Pos:' in the bottom status bar shows at least 2147483649).
5. Close the opened N++.
6. Go to a folder, where you have your 'session.xml' file stored (for portable N++ it will be the same folder, where is the main N++ executable 'notepad++.exe') and open that file.
7. You will see the result of an `int` integer overflow - incorrect negative values `endPos="-2147483648" startPos="-2147483648"`

### Expected Behavior
You see correct positive values `endPos="2147483648" startPos="2147483648"

### Actual Behavior
After the saved N++ session is restored, the cursor is not at the end of the 2GB file, where it was left before.

@donho 
I can do a PR for this if you agree with this proposal.

**Comment by donho** [comment]
@xomx 
> I can do a PR for this if you agree with this proposal.

OK. Please keep the PR as short as possible.

**Comment by xomx** [comment]
@donho 

I bumped to weird source code local/server mismatch things, while working on this PR. The culprit can be different source code encodings(?). E.g. this is my screenshot, when I use the web-access editing of the "PowerEditor/src/ScintillaComponent/ScintillaEditView.h" (it then creates my fork of the N++):
![ISO-8859-1_ScintilaEditView_h](https://user-images.githubusercontent.com/13075183/154710721-972845de-f7c7-4e19-9d17-597f068f035c.png)

When I delete old & paste my new patched content there, it shows me in the 'Preview changes' additional code changes I did not do at all, e.g.:
![ISO-8859-1_ScintilaEditView_h_-_invalid_content](https://user-images.githubusercontent.com/13075183/154711067-822f0bca-a297-448e-9800-3a7d4c2d4ff4.png)
- the right content at the above image seems to be the bottom green line (aka "my changes") and not the red original one (at least when I downloaded the notepad-plus-plus-master to my local PC and checked - at this line is the content of the green line)

The same stuff is valid for the "PowerEditor/src/ScintillaComponent/ScintillaEditView.cpp".

**Comment by donho** [comment]
Here's my local updated with https://github.com/notepad-plus-plus/notepad-plus-plus:

![image](https://user-images.githubusercontent.com/90293/154720668-445e95b5-681a-4d22-895c-519324b3ff46.png)

Under what OS are you working?

**Comment by xomx** [comment]
> Here's my local updated with https://github.com/notepad-plus-plus/notepad-plus-plus:

Ok, you have the same content, as I have on my local disk. But the web-interface incorrectly thinks, that it was changed to that content in my patch!



> Under what OS are you working?

Win 8.1 Enterprise (CZ).
I am leaving now, so I will try that from my home Win10 Pro EN.

**Comment by xomx** [comment]
@donho 

Another PC & OS (Win10Pro EN), another webbrowser (latest Edge, previously used was the latest Firefox), the same problem with server version of `ScintillaEditView.h` & `ScintillaEditView.cpp`:
![npp_source_encoding_problem](https://user-images.githubusercontent.com/13075183/154810622-26c8252a-ffd0-48e5-9f65-91d6431df658.png)

Any other file I tried shows correctly this:
![npp_source_encoding_ok](https://user-images.githubusercontent.com/13075183/154810653-22424989-01a4-47b1-b908-ffa9d99bf8f1.png)

**Comment by donho** [comment]
@xomx 
Could you provide the screenshots (and the URLs) of the modified line in your browser please?

**Comment by xomx** [comment]
https://github.com/notepad-plus-plus/notepad-plus-plus/edit/master/PowerEditor/src/ScintillaComponent/ScintillaEditView.h

![npp_source_encoding_patch_problem](https://user-images.githubusercontent.com/13075183/154814124-761ccdcb-8f25-4f7c-bc67-7a503fd977d9.png)

The change visible at line 411 is intended, the one at line 935 not.

**Comment by donho** [comment]
So the first change `void scroll(intptr_t column, intptr_t line){` is intentional, isn't it?
After do your change, the git of github show the 2nd change (on which you've done nothing):
`execute(SCI_SETWORDCHARS, 0, reinterpret_cast<LPARAM>("abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789?!.’+-*&|=_~"));`

Do my description of your situation correct?

**Comment by xomx** [comment]
> Is my description of your situation correct?

Yes.

**Comment by donho** [comment]
Hmm... that remind me a similar issue when I worked on PHP (very long time ago):
The bug was in Opera browser, during the test of the interface of our web application, the filed of text zone modifies some special characters and then save them into the DB with the wrong data. I guess it's kind of the same situation.

Can't you work with git locally?

**Comment by xomx** [comment]
This is the only difference shown, when working locally:

![npp_source_encoding_patch_local_ok](https://user-images.githubusercontent.com/13075183/154817910-e399e9de-7c77-46ba-afdf-718f6b8f1dbc.png)

**Comment by xomx** [comment]
@donho 

I have found another case of such web-interface source file editing problem:
https://github.com/notepad-plus-plus/notepad-plus-plus/edit/master/PowerEditor/src/Notepad_plus.cpp

This time it is showing a 'red-dot' at the file begin. When I hover my mouse above the red-dot, it reveals the `\ufeff` BOM (UTF-16 (BE)?!):
![NPP_webaccess_error_Notepad_plus cpp](https://user-images.githubusercontent.com/13075183/154948467-9b845761-f46a-4ada-bddd-de03473e5988.png)

**Comment by donho** [comment]
@xomx 
This file is set to UTF due to [Space Invader](https://github.com/notepad-plus-plus/notepad-plus-plus/blob/master/PowerEditor/src/Notepad_plus.cpp#L7263). BOM was added par VSStudio.
