### ISSUE TITLE
config.xml missing DarkMode url custom color

### ISSUE THREAD

**Issue by ARYX01** [notepad-plus-plus/notepad-plus-plus#11211]
### Description of the Issue
in the setting the yellow url color if changed doesn't save itself in the config file
![image](https://user-images.githubusercontent.com/13236949/153876124-7ed3f2ff-668a-4fbb-83c3-87762dfc8872.png)

### Expected Behavior
keep custom color at restart

### Actual Behavior
reset to default

**Comment by ARYX01** [comment]
`<GUIConfig name="DarkMode" enable="yes" colorTone="32" customColorTop="2105376" customColorMenuHotTrack="4210752" customColorActive="4210752" customColorMain="12940323" customColorError="176" customColorText="14737632" customColorDarkText="12632256" customColorDisabledText="12632256" customColorEdge="6579300" />`
There it should be another value for the custom color url?

**Comment by dfs-** [comment]
Should be fixed in the next version, since it should be the same issue as #11095

**Comment by ArkadiuszMichalski** [comment]
Fixed.
