### ISSUE TITLE
Switching between large files is too slow

### ISSUE THREAD

**Issue by mshingote** [notepad-plus-plus/notepad-plus-plus#11218]
### Description of the Issue
I have opened couple of large files. Whenever I try to switch between then using tab view its too slow and notepad++ hangs.

### Steps to Reproduce the Issue
1.  Open 10 large files ~200mb each
2.  They are shown in tabs. Try to switch between them using mouse click.
3.  It takes time and slows notepad++ down.

### Expected Behavior
Switching between files should be fast.

### Actual Behavior
Switching between files is slow.

### Debug Information
Notepad++ v8.2.1   (64-bit)
Build time : Jan 19 2022 - 18:43:05
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 10 Pro for Workstations (64-bit) 
OS Version : 2009
OS Build : 19043.1526
Current ANSI codepage : 1252
Plugins : JSMinNPP.dll mimeTools.dll NppConverter.dll NppExport.dll NPPJSONViewer.dll NppXmlTreeviewPlugin.dll XMLTools.dll

**Comment by alankilborn** [comment]
Notepad++ 8.3 and up contains better support for larger files.
Suggest you try that and report back?

**Comment by mshingote** [comment]
I'll check with latest **Notepad++ 8.3.1 (Boycott Beijing 2022)**
and then report back.

Thanks!

**Comment by mshingote** [comment]
Closing this ticket as I'm happy with the updated Notepad++

Notepad++ v8.3 new features and bug-fixes:

> 1. Remove 2GB file open restriction for x64 binary.
> 2. Improve large files (200MB) loading speed and editing/browsing performance.
> 3. Fix Find in Files crash issue.
