### ISSUE TITLE
No politics Please!

### ISSUE THREAD

**Issue by shimanshe** [notepad-plus-plus/notepad-plus-plus#11228]
notepad-plus-plus is not a software that owned by anyone. it's a software that a lot of people contributing to, As it says "Based on the powerful editing component [Scintilla](https://www.scintilla.org/)". Anyway jedit is a mature programmer's text editor with hundreds (counting the time developing plugins) of person-years of development behind it, http://www.jedit.org/. I use it as replacement.
![image](https://user-images.githubusercontent.com/7099296/154481348-f4640af1-027c-4765-a90c-8658c6f01966.png)

**Comment by dail8859** [comment]
All opinion related topics are welcome to be discussed in this area of the community forum: https://community.notepad-plus-plus.org/category/8/boycott-notepad

**Comment by Korb** [comment]
This is a duplicate of #6288 (disrespect for other members of the FOSS community by posting political propaganda spam in text editor resources).
