### ISSUE TITLE
Copying range of lines from search bar.

### ISSUE THREAD

**Issue by jdecrypted** [notepad-plus-plus/notepad-plus-plus#11224]
### Description of the Issue

Sometimes, when we search for a pattern, we need to check things between the range.
The search results window just provides the search results, if I need to select the in between data, I need to manually select the lines and then check.
Instead, we have options to deal with it:
1) provide some option which can copy to clip board [from-to] number of line.
2) If we select from search bar , option will be provided to just copy the result,  or the range.

### Steps to Reproduce the Issue

1. 
2. 
3.

**Comment by alankilborn** [comment]
>Sometimes, when we search for a pattern, we need to check things between the range.

Select the text you want to search, then tick this box before doing a _Find All in Current Document_ search:

![image](https://user-images.githubusercontent.com/77065706/154479966-1a4b7d11-0e9e-4870-b6b8-3c723ee76d79.png)

>provide some option which can copy to clip board [from-to] number of line.
>If we select from search bar , option will be provided to just copy the result, or the range.

In the _Search results_ window, there are right-click context menu options for copying.

**Comment by alankilborn** [comment]
Recommend CLOSURE of this item.
