### ISSUE TITLE
Wrong cursor position after open files

### ISSUE THREAD

**Issue by Alpengreis** [notepad-plus-plus/notepad-plus-plus#11220]
### Description of the Issue
After open a text file with at least one char in it, with explorer or something "external" else,
the cursor will be in line 1 position 2 instead of line 1 position 1, like this:

![cursor-problem](https://user-images.githubusercontent.com/11355601/154314249-4a10b29c-6cd4-42b2-841d-87e659ebfce9.PNG)

This does NOT happen when I open it in the editor itself (with file open dialogue or file
history).

### Steps to Reproduce the Issue

1. Prepare a text file with at least 1 char in it.
2. Open the prepared text file with Windows Explorer, NOT within the editor itself.

### Expected Behavior
Cursor should be in line 1 position 1.

### Actual Behavior
Cursor is in line 1 position 2.

### Debug Information
Notepad++ v8.3   (64-bit)
Build time : Feb  3 2022 - 03:39:05
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : "C:\Users\ag-usr\Downloads\test1.txt"
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 10 Pro (64-bit) 
OS Version : 2009
OS Build : 19044.1566
Current ANSI codepage : 1252
Plugins : DSpellCheck.dll mimeTools.dll NppConverter.dll NppExec.dll NppExport.dll PythonScript.dll

**Comment by thomassmith311** [comment]
Cannot reproduce - video of attempt:

https://user-images.githubusercontent.com/19561856/154326583-96220902-c972-41d5-be25-0219196aa425.mp4

Debug info:

Notepad++ v8.3.1   (64-bit)
Build time : Feb 13 2022 - 15:41:12
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 11 (64-bit) 
OS Version : 2009
OS Build : 22000.493
Current ANSI codepage : 1252
Plugins : mimeTools.dll NppConverter.dll NppExport.dll

**Comment by xomx** [comment]
> Also I updated to 8.3.1, but that probably isn't the reason

Yes, it is the [reason](https://github.com/notepad-plus-plus/notepad-plus-plus/blob/master/PowerEditor/bin/change.log#L4).

**Comment by Alpengreis** [comment]
Thank you very much for reponses!

Then I will update now to v8.3.1.

If it's good then here too, I will close the issue.

**Comment by Alpengreis** [comment]
It's good with 8.3.1 here too. Sorry for the trouble!
