### ISSUE TITLE
[Feature request] - Allow line numbering to start from 0

### ISSUE THREAD

**Issue by recoil1992** [notepad-plus-plus/notepad-plus-plus#11226]
As hobby programmer I am using Notepad++ on daily basis and I would like to thank you for such a great tool.
When I am doing various debugging, including log reviews etc. I often need to go through the content/output of the vectors/arrays where the numbering starts at 0. It is sometimes confusing to see line number different than the actual vector/array row number.
It would be helpful to have a possibility to set line numbering starting at 0.
This could be configurable by right clicking the Line numbering and setting the value from which the line numbering begin.

Thanks for considering this.

**Comment by alankilborn** [comment]
I believe this plugin can do it, although I haven't used it:

![image](https://user-images.githubusercontent.com/77065706/154480990-13c35eff-6b50-4a67-bd1a-e3c5495485db.png)

**Comment by recoil1992** [comment]
Good catch, plugin works! Many thanks for hint. :-)
