### ISSUE TITLE
& and && are not visible in various languages

### ISSUE THREAD

**Issue by jotapdiez** [notepad-plus-plus/notepad-plus-plus#1123]
I just figured out that && and & is not visible when using language javascript. That happens with other languages too.

For Example, create a new document, put this lines
```javascript
var var1= (that.state.active == null && i==0  ? true : that.state.active== view._id);
var var3= var1 & var2;
```
and select language ->Javascript.

Other languages :
Double ampersand is visible on ASP, BATCH, CMake, Diff, HTML, Inno, JSON, and (probably) more.
Is NOT visible in C, C#, C++, Java, Javascript, Shell, and maybe others.

Additional information:
- I renamed the plugin folder
- Windows 7 64b
- Notepad++ v6.8.6 (Build Time: Oct 29 2015 - 01:13:57)
- Screenshot:
![Screenshot](https://drive.google.com/file/d/0Bz8VTzJV6y1FbXhRTGhBNWdKS2c/view?usp=sharing)

**Comment by donho** [comment]
Source code pro font is the reason of the bug. Please see:
https://notepad-plus-plus.org/community/topic/271/notepad-6-8-1-released

**Comment by jotapdiez** [comment]
Sorry but I still don't know how to solve this issue.
Your link says "In v6.8.1 Notepad++ include Source Code Pro’s ttf (font files) instead of otf. That solves this hanging issue" and I have 6.8.6.

Should I revert to 6.8.1? Should I update my video drivers?

Thanks
