### ISSUE TITLE
Crash on closing xml tags

### ISSUE THREAD

**Issue by AlexZanini70** [notepad-plus-plus/notepad-plus-plus#11236]
Notepad++ 64 bit 8.3.1 crashes when manually typing xml tags.

Steps to Reproduce the Issue
Open an XML or a new document
Change language to XML if needed
type any tag, for instance: <Setup>
Expected Behavior
Nothing

Actual Behavior
Notepad++ 64 bit 8.3.1 crashed after closing the tag with >

Notepad++ v8.3.1   (64-bit)
Build time : Feb 13 2022 - 15:41:12
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 10 Pro (64-bit) 
OS Version : 2009
OS Build : 19044.1526
Current ANSI codepage : 1252
Plugins : mimeTools.dll NppConverter.dll NppExport.dll NppXmlTreeviewPlugin.dll qkNppReverseLines.dll XMLTools.dll

**Comment by donho** [comment]
@AlexZanini70 
This crash bug has been fixed in v8.3.1 normally.
Could you remove 2 plugins `NppXmlTreeviewPlugin.dll` & `XMLTools.dll` then try it again?

**Comment by donho** [comment]
OK I can reproduce it with XMLTools 3.1.1.10.
After upgrade XMLTools to 3.1.1.12 with the Plugin Admin, the crash gone.
I will see what I can do about it.
