### ISSUE TITLE
New Auto-Complete icons causes sort issues for edge use cases

### ISSUE THREAD

**Issue by vinsworldcom** [notepad-plus-plus/notepad-plus-plus#11233]
### Description of the Issue
For users not using the Notepad++ autoComplete files as intended, but rather putting large strings of non-typical word characters to use autocomplete as a form of code snippet provider, the addition of the "fx" icon has causes some sorting issues.

This is because the default separator we use `?` is higher in the ASCII table than some other non-typical word characters so it is sorted latter.  For example, see the [community discussion](https://community.notepad-plus-plus.org/topic/22587/autocomplete-items-order-issue).

In that example autocomplete is providing a list like:

```
print_r(get_class_methods(get_class($var)));die();
print_r
```

when the desire is the lone `print_r` comes first.  This is because internally, the `?1000` tag is appended for the "fx" image icon as per using the default Scintilla [SCI_AUTOCSETTYPESEPARATOR](https://www.scintilla.org/ScintillaDoc.html#SCI_AUTOCSETTYPESEPARATOR) which is the `?`.  So the list internal to Notepad++ is really:

```
print_r?1000
print_r(get_class_methods(get_class($var)));die();?1000
```

and after column by column sorting, the `(` (ASCII 40 (\x28)) from the second item compared to the `?` (ASCII 63 (\x3F)) of the first item, ..  they are switched in the sort since 40 < 63, i.e., parenthesis comes **_before_** question mark even though the question mark isn't displayed in the Autocomplete output window.  So the output of the autocomplete window appears "incorrectly" sorted.

### Steps to Reproduce the Issue

1. Using the autoComplete/python.xml file as an example, add a line directly under the current `print` KeyWord so it looks like the following:

```XML
		<KeyWord name="print" />
		<KeyWord name="print(somestuff)" />
```
 
2. Set Notepad++ language to Python
3. Ensure Settings => Preferences => Auto-Completion is enabled (default values):

![image](https://user-images.githubusercontent.com/9657169/154560185-4ec8903d-95a8-416c-a142-f3ee34cc845e.png)

4. Type `pr` and observe:

![image](https://user-images.githubusercontent.com/9657169/154560519-dde20058-41b6-4833-8743-4f5f41d0fccc.png)

`print(somestuff)` is sorted ***before*** `print` and as described above this is expected, but not desirable.

### Expected Behavior
Sort

```
print
print(somestuff)
```

### Fix

This is easily fixed as pointed out by @pryrt in the Community link above.  Just use a lower ASCII character as the `SCI_AUTOCSETTYPESEPARATOR` instead of the default `?` and I think "Record Separator" (ASCII 30 (\x1E)) is a good choice by name and by sort order - lower than all visible ASCII characters one could think to put in the autocomplete XML files.

I have tested and will submit a pull request.  But **_PLEASE_** do your own testing as well!

### Debug Information
Notepad++ v8.3.1   (32-bit)
Build time : Feb 13 2022 - 15:35:09
Path : C:\Downloads\32\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : ON
Cloud Config : OFF
OS Name : Windows 10 Enterprise (64-bit) 
OS Version : 2009
OS Build : 19042.1526
Current ANSI codepage : 1252
Plugins :

**Comment by pryrt** [comment]
As noted in that conversation, the bug also shows on autoComplete files that aren't quite as abusive: Perfectly valid autocomplete word characters (0-9) are sorted incorrectly because of the use of ? as the image separator character.

For example, in the sequence of keywords:
```
print_r
print_r0
print_rand
```
The shorter `print_r` should always come before anything longer that starts with the same sequence.  And that list is sorted correctly, lexicographically, as I show it there.

But because asc(`0`)=48=0x30 is less than asc(`?`)=63=0x3F, the auto-complete will list `print_r0` _before_ `print_r`.  This is a bug in the current implementation.

![image](https://user-images.githubusercontent.com/17455758/154567988-a2f1535c-1817-424f-9d4b-bcd66dc7b7cd.png)

```
<?xml version="1.0" encoding="UTF-8" ?>
<!--
@author	 Geoffray Warnants - http://www.geoffray.be
@version	1.35.20100625
-->
<NotepadPlus>
	<AutoComplete>
		<KeyWord name="print_r" func="yes">
			<Overload retVal="mixed">
				<Param name="mixed expression"/>
				<Param name="[bool return=false]"/>
			</Overload>
		</KeyWord>
		<KeyWord name="print_r0" func="yes">
			<Overload retVal="mixed">
				<Param name="argument"/>
			</Overload>
		</KeyWord>
		<KeyWord name="print_rand" func="yes"/>
	</AutoComplete>
</NotepadPlus>
```
