### ISSUE TITLE
UDL comment configuration input fields are broken

### ISSUE THREAD

**Issue by MaDill** [notepad-plus-plus/notepad-plus-plus#11239]
### Description of the Issue
When opening the UDL dialog, select an existing UDL with something setup in the comment block, the input fields are empty. When type something in there, close notepad++ and reopen it again it is again empty. But when there is an existing UDL with configured comments they are used for syntax highlighting.

### Steps to Reproduce the Issue
1. Open an existing UDL xml file, for example markdown._preinstalled.udl.xml and check <Keywords name="Comments"> if there is something configured
2. Open the UDL dialog and 
3. select the before checked language
4. switch to the "Comment & Number" tab
5. check "Comment line style" and "Comment style" blocks => they are empty
6. type in all the Fields something
7. close the dialog
8. close notepad++
9. open everything again and the fields are again empty

The xml is changed when something is written into the input fields, but not with the values what was typed in.
Example from markdown._preinstalled.udl.xml
Before: <Keywords name="Comments">00# 01 02((EOL)) 03&lt;!-- 04--&gt;</Keywords>
Open NP++, open the dialog and type something in the comment input fields. Close NP++
After: <Keywords name="Comments">0 1 2 3 4</Keywords>

### Expected Behavior
Display configured comment configuration and allow to config a new configuration for comments.

### Actual Behavior
See "Steps to Reproduce the Issue"

### Debug Information
Notepad++ v8.3.1   (64-bit)
Build time : Feb 13 2022 - 15:41:12
Path : C:\_PortablePrograms\Notepad++\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : ON
Cloud Config : OFF
OS Name : Windows 10 Pro (64-bit) 
OS Version : 2009
OS Build : 19044.1466
Current ANSI codepage : 1252
Plugins : DSpellCheck.dll HexEditor.dll mimeTools.dll NppConverter.dll NppExec.dll NppExport.dll PythonScript.dll XMLTools.dll 

![udl](https://user-images.githubusercontent.com/7298934/154682482-a004afd5-f3bb-4f5b-a00a-18d7a7affaea.png)

**Comment by donho** [comment]
@pryrt 
The following url:
https://github.com/notepad-plus-plus/npp-usermanual/releases/download/2.9/nppUserManual.zip
shows "Not found".

Should you provide the nppUserManual.zip for the indicated url or we should modify the url?

**Comment by pryrt** [comment]
@donho , I think you made this comment to the wrong issue.  I fixed the usermanual problem, but it has nothing to do with this reported bug in the UDL. (I un-assigned myself from this issue)

**Comment by donho** [comment]
@pryrt 
Oups! Sorry about that.
Thank you for fixing it anyway.

**Comment by pryrt** [comment]
On this actual issue, \@who-what in the Forum had the same problem.  See my results when I replicated what \@who-what described in [my post there](https://community.notepad-plus-plus.org/post/74464) -- basically, take a working comment setup from v8.3 UDL, and put that UDL in v8.3.1 -- when it loads, it clears out the Comment Line definition, and comments are not correctly highlighted.

**Comment by donho** [comment]
@MaDill 
Could you confirm it's fixed by: https://ci.appveyor.com/api/buildjobs/y4puc9l8mc8m65wq/artifacts/Notepad%2B%2B.x64.Release.exe
please ?

**Comment by volkankaban** [comment]
Maybe I'm posting in the wrong place for this opinion, but why can't we customize the fold/unfold feature globally for all languages in Notepad++? My main purpose in using Notepad++ is to explore all types of files, read or update their information, and use it for taking notes and keeping all of my tips and notes in one file. I have notes related to various languages such as JavaScript, PHP, HTML, MySQL, Bash, SSH, and so on. I mainly use the JavaScript language view, but I can't customize it or use plain text, so it looks useless.

For example, I would like to be able to start a section with;

[]####  

 notes, tips, bla bla bla js, php, html, c, 

####[] 

for all languages, rather than having to customize each language individually.
