### ISSUE TITLE
Document cannot be saved if the file was set to another char set before 

### ISSUE THREAD

**Issue by donho** [notepad-plus-plus/notepad-plus-plus#11238]
Starting with 8.3 and 8.3.1 when I try to create a new file with different character set the software does not allow me to save directly. I need to click Save As in order save file.

ref: https://community.notepad-plus-plus.org/topic/22577/notepad-v8-3-1-release/8?_=1645184495902

### Steps to Reproduce the Issue

1.    Open new tab on Notpad++
2.   Without writing anything click Encoding menu and Character Sets
3.    Choose any chracter set
4.    Write or copy paste some text

### Expected Behavior
File can be saved.

### Actual Behavior
Save button is grey and Save option under File menu is greyed out.

### Debug Information
Notepad++ v8.3.1   (64-bit)
Build time : Feb 13 2022 - 15:41:12
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 11 (64-bit) 
OS Version : 2009
OS Build : 22000.493
Current ANSI codepage : 1252
Plugins : DSpellCheck.dll mimeTools.dll NppConverter.dll NppExport.dll

**Comment by donho** [comment]
Introduced in https://github.com/notepad-plus-plus/notepad-plus-plus/commit/961a133a6008bf2a664360691942ef95bc2710f2.
Switching to another tab and back, “Save” is enabled.

Ref: https://community.notepad-plus-plus.org/topic/22577/notepad-v8-3-1-release/9?_=1645184495904

**Comment by xomx** [comment]
I know what is happening there (let's say I have opened a fresh N++, pressed Ctrl+N to have 2nd empty tab, chose in the Encoding menu a character set:
- `Notepad_plus::command(int id)` is called (in my case I chose the IDM_FORMAT_WIN_1250), there is this relevant code:

```
	if (!buf->isDirty())
	{
		buf->setEncoding(encoding);
		buf->setUnicodeMode(uniCookie);
		fileReload();
	}
	break;
```
- so when the N++ buffer (new tab) is empty, the fileReload() is called, it ends up in `FileManager::reloadBuffer(BufferID id)`, relevant code:

```
	buf->_canNotify = false;	//disable notify during file load, we don't want dirty status to be triggered

	//Get file size
	FILE* fp = generic_fopen(buf->getFullPathName(), TEXT("rb"));
	if (!fp)
		return false;
```  
- the problem is, that the `_canNotify` is disabled (set to `false`) 1st, but then the `generic_fopen` fails here, so the notification is not re-enabled back (until someone does not switch the tabs...)

**Comment by Yaron10** [comment]
@xomx,

That was quick. Thank you. 👍 
(I haven't tested it).

**Comment by donho** [comment]
> the problem is, that the _canNotify is disabled (set to false) 1st, but then the generic_fopen fails here, so the notification is not re-enabled back (until someone does not switch the tabs...)

Exactly.
This regression is due to insertion of file size detection, and I was not aware of the important position of `_canNotify`.
Uncle Ben was right: 
"With great refactoring comes great regressions."
:(

**Comment by Yaron10** [comment]
@donho,

> "With great refactoring comes great regressions."

Thank you for the great solution. 👍
