### ISSUE TITLE
Enable backwards search with reg exp

### ISSUE THREAD

**Issue by juuso-valimaa** [notepad-plus-plus/notepad-plus-plus#11230]
I know, I'm not the first one to post this. And it's probably a niche audience that needs this. But if ever you have too much free time on your hands, please:

### Fix backwards search with regular expressions
Backwards search with regular expressions doesn't work, or isn't on by default, or something else. Anyway, from the point of view of the end-user it just doesn't work.

### Steps to Reproduce the Issue
Open search. Tick Regular Expression. Search backwards. Well, I mean, you can't.

### Expected Behavior
To search backwards one step.

### Actual Behavior
The option is grayed out.

If backwards searching is too difficult for some overly technical reason, could it be possible to just cache previous search positions in a stack or whatever and loop through them? I don't know, just an idea.

**Comment by dail8859** [comment]
There are some technical limitations and possible incorrect results when searching backwards using regular expressions. If you do in fact need this, [you can enable the functionality manually](https://npp-user-manual.org/docs/preferences/#preferences-for-advanced-users).
