### ISSUE TITLE
The "Append extension" checkbox is ignored in the "Save As" dialogue in Notepad++ 8.2.1

### ISSUE THREAD

**Issue by pansamolot** [notepad-plus-plus/notepad-plus-plus#11247]
## Description of the Issue

The "Append extension" checkbox in the "Save As" dialogue in 8.2.1 is not working. Even though it is checked (and "Save as type" field is set to "Normal text file"), when user types filename without any extension, file is saved under that filename only and the extension is not added.

## Steps to Reproduce the Issue

1. Open a new file in Notepad++ and type some text
2. Hit <kbd>Ctrl</kbd>+<kbd>S</kbd>
3. Change the "File name" in the "Save As" dialogue to "test"
4. Click "Save" button

## Expected Behavior

The "Append extension" checkbox is respected, extension is added and file is saved as "test.txt".

## Actual Behavior

The "Append extension" checkbox is ignored, extension is not added and file is saved as "test".

## Screenshot

![npp](https://user-images.githubusercontent.com/60975060/154841136-fa1e2d26-ef06-40fc-849b-4f496303444e.gif)

## Debug Information

Notepad++ v8.2.1   (64-bit)
Build time : Jan 19 2022 - 18:43:05
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : 
Admin mode : ON
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 10 Pro (64-bit) 
OS Version : 2009
OS Build : 19042.1526
Current ANSI codepage : 1250
Plugins : DSpellCheck.dll mimeTools.dll NppConverter.dll NppExport.dll _CustomizeToolbar.dll

**Comment by alankilborn** [comment]
Cannot reproduce, either in Adminstrator mode or not.

Notepad++ v8.2.1   (64-bit)
Build time : Jan 19 2022 - 18:43:05
Path : C:\...\Releases\npp.8.2.1\npp.8.2.1.portable.x64\notepad++.exe
Command Line : -titleAdd="8.2.1 64-bit" -multiInst "C:\...\Releases\npp.8.2.1\npp.8.2.1.portable.x64\license.txt"
Admin mode : OFF
Local Conf mode : ON
Cloud Config : OFF
OS Name : Windows 10 Enterprise (64-bit) 
OS Version : 2009
OS Build : 19042.1466
Current ANSI codepage : 1252
Plugins : mimeTools.dll NppConverter.dll NppExport.dll PythonScript.dll

**Comment by Yaron10** [comment]
https://github.com/notepad-plus-plus/notepad-plus-plus/issues/10436

**Comment by pansamolot** [comment]
@Yaron10 #10436 says about **empty** _Default Directory_. However, the above bug was reported / I can reproduce it with _Default Directory_ **set to** _Follow current document_:

![image](https://user-images.githubusercontent.com/60975060/154843629-4cc9c772-954e-4b4d-8fec-c2e592b2ec44.png)

@alankilborn Truly regret, but as you can see from the attached gif, the bug is reproducible.

**Comment by alankilborn** [comment]
>Truly regret, but as you can see from the attached gif, the bug is reproducible.

Understood.
I just wanted to share my experience in trying to reproduce it, and that shows that it doesn't repro for everyone, making the problem harder to fix.

**Comment by Yaron10** [comment]
@pansamolot,

The case in https://github.com/notepad-plus-plus/notepad-plus-plus/issues/10436 is saving to an empty folder which does not contain any files. It doesn't have anything to do with the _Default Directory_ settings.

Watching your video, you're saving to an empty folder.
The issue should be fixed in the latest v8.3.1. Could you try it?

**Comment by alankilborn** [comment]
>Watching your video, you're saving to an empty folder.

With the filter set at `*.txt` I don't know that we can judge for certain that @pansamolot is saving to an empty folder.  Perhaps the judgment that can be passed is that the folder contains no .txt files...

But "trash" might be an odd place to create a demo of this problem, anyway...

**Comment by Yaron10** [comment]
@alankilborn,

> Perhaps the judgment that can be passed is that the folder contains no .txt files...

Correct. As usual. :)

It should be:
Watching your video and knowing the empty folder issue, I assume you're saving to an empty folder.

**Comment by pansamolot** [comment]
@Yaron10 @alankilborn is right. The folder is not empty. It contains (contained at the moment of recording example video) several files with no extension -- result of previous testing of this issue. Thus, if 8.3.1 deals with saving to an empty folder then the results will be the same, as the folder in question isn't empty.

@alankilborn To be honest, I don't see nothing weird about my "Trash" folder! :> C:\Trash -- the fastest accessible folder when many programs leads me to as weird locations as "Downloads" etc. A folder like any other on my disk. I don't think that picking up this folder could influence the issues, the recording or this report in any way.

**Comment by Yaron10** [comment]
@pansamolot,

@alankilborn is usually right. He's also a bit sarcastic. :)

Could you please try it with [v8.1.3](https://community.notepad-plus-plus.org/topic/22577/notepad-v8-3-1-release)?

**Comment by Yaron10** [comment]
> The folder is not empty. It contains (contained at the moment of recording example video) several files with no extension -- result of previous testing of this issue.

I can reproduce it in v8.2.1. **Fixed in v8.3.1**.
Thanks to @mere-human.

**Comment by alankilborn** [comment]
> I don't see nothing weird about my "Trash" folder! 

Well, as long as it is "yours" and is just an ordinary folder, and is not a special folder created by some add-on you might be using, it should be OK.

**Comment by pansamolot** [comment]
@Yaron10 So, if this is confirmed fixed in 8.3.1 then you / we can safely close current bug report only linking to an issue / PR that fixed this problem in 8.3.1, right?

I'll double check this resolution on 8.3.1 a bit later, as I am currently overloaded with some other duties. Thanks.

**Comment by Yaron10** [comment]
@pansamolot,

I'm not authorized to close your issue.
Please do it yourself _after testing it with v8.3.1_.

Thank you.

**Comment by pansamolot** [comment]
@Yaron10 Sure, I'll do this after testing.

Can you provide me with a link to PR or issue number that corresponds to the solution (in 8.3.1) for the problem reported here? So I can link both issues toghether?

**Comment by Yaron10** [comment]
@pansamolot,

👍 

https://github.com/notepad-plus-plus/notepad-plus-plus/issues/10436.
https://github.com/notepad-plus-plus/notepad-plus-plus/pull/11050.
https://github.com/notepad-plus-plus/notepad-plus-plus/commit/b5a5baf13bb3f0b041f49698afb74af2b7059f6a.

I think that mentioning those links should suffice.

**Comment by pansamolot** [comment]
Confirmed resolved in [8.3.1](https://community.notepad-plus-plus.org/topic/22577/notepad-v8-3-1-release) as per #10436.
