### ISSUE TITLE
When colon is press semi colon comes

### ISSUE THREAD

**Issue by BarthdryZ** [notepad-plus-plus/notepad-plus-plus#11245]
While writing code suddenly colon stopped working and always semi colon appeared even after i shift click it multiple times. i also tried to copy paste the colon but again it changes to semi colon. I also tested my keyboard in other applications my colon is working: ;
So i restarted the application but still the bug is not fixed. Please fix this small glitches happening suddenly while doing things.

**Comment by dail8859** [comment]
Have you tried a different font?

Also, please post your debug information as requested by the template.

**Comment by BarthdryZ** [comment]
I don't know. But it wis a temporary bug i just did it after an hour it got fixed this is kinda weird. Even now i have seen sometime the blinking cursor is glitching out.

**Comment by dail8859** [comment]
I'll go ahead and close this since the original issue is not there any more.

If you are having some other issue feel free to open a new issue with details and your debug information.
