### ISSUE TITLE
v8.3.1 not compatible with windows 11

### ISSUE THREAD

**Issue by mshingote** [notepad-plus-plus/notepad-plus-plus#11243]
### Description of the Issue
I recently updated Notepad to v8.3.1 it seems it crashes on launch.

Windows OS info

Edition	Windows 11 Home Single Language
Version	21H2
Installed on	‎Saturday ‎07 ‎August ‎2021
OS build	22000.527
Experience	Windows Feature Experience Pack 1000.22000.527.0

### Steps to Reproduce the Issue
1. Update to notepad++ to v8.3.1 on windows 11
2. Launch notepad
3. It crashes

### Expected Behavior
Notepad++ should launch without crash

### Actual Behavior
Notepad++ crashes on launch.

### Debug Information
Unable to fetch info for now.

**Comment by mshingote** [comment]
I'll debug issue and revert here soon.

**Comment by mshingote** [comment]
so far there is problem with 
_"C:\Program Files\Notepad++\plugins\NppTaskList\NppTaskList.dll"_

**Comment by mshingote** [comment]
There was problem with plugin in my system.

```
pi->_pFuncIsUnicode = (PFUNCISUNICODE)GetProcAddress(pi->_hLib, "isUnicode");
if (!pi->_pFuncIsUnicode || !pi->_pFuncIsUnicode())
	throw generic_string(TEXT("This ANSI plugin is not compatible with your Unicode Notepad++."));
```

**Comment by chcg** [comment]
@mshingote See new release for interface change with N++ 8.3.x 
https://github.com/Megabyteceer/npp-task-list/releases/tag/v2.4.0

**Comment by donho** [comment]
It's worth to exclude task list v2.3.
Once the plugin is updated in Plugin List, I will change this script.

**Comment by chcg** [comment]
@donho I added v2.4 with https://github.com/notepad-plus-plus/nppPluginList/commit/a6596d99c9ee13f807832b51125eb2198e0d2ed9 right now.
