### ISSUE TITLE
Notepad++ 8.3.x won't start anymore

### ISSUE THREAD

**Issue by reinerblock** [notepad-plus-plus/notepad-plus-plus#11241]
### Description of the Issue
As a view versions ago, Notepad 8.3.x won’t start anymore.

Therefore, I started it with *“-noplugins -nosession”* and got the following message.

![grafik](https://user-images.githubusercontent.com/5745579/154749647-ad887af1-33b0-4616-bf60-a144e013d00b.png)

When I renamed said internal DLL NP++ started, loaded the session but showed no toolbar (and I think no menu) and closed after max. a second.

Now I am back to 8.2.1 because there are no problems.
### Steps to Reproduce the Issue
1. Install version 8.3.0 or 8.3.1
2. Start NP++ with “-noplugins -nosession”
3. NP++ won't start, just the message above appears.

### Expected Behavior
NP++ starts normal

### Actual Behavior
see above

### Debug Information
Can't get any debug information because NP++ won't start

**Comment by alankilborn** [comment]
The correct command line argument is `-noPlugin`, not `-noplugins`.

Since this isn't going to end with a problem in Notepad++, suggest you continue working it on the Community forum and close this issue.

Or a moderator can close it here.

**Comment by reinerblock** [comment]
I got it from BleepingComputer - [How to fix crashes when you start Notepad++](https://www.bleepingcomputer.com/tutorials/how-to-fix-crashes-when-you-start-notepad-plus-plus/)

Yeah, I found out that there are plugings inside the program folder and in my user folder. And I can't really uninstall those that are in the program folder.

**Comment by alankilborn** [comment]
`-noplugin` (yours) is NOT equivalent to `-noPlugin` (mine).

**Comment by pryrt** [comment]
> I got it from BleepingComputer

![image](https://user-images.githubusercontent.com/17455758/154757405-9b6a5f76-1fdd-40c1-9173-1c9830da1b08.png)

Even BleepingComputer , which is not a canonical information resource for Notepad++, had it `-noPlugin` , with a capital `P`.  You mis-copied it from that site.

**Comment by reinerblock** [comment]
I do know that BleepingComputer is absolutely not the _ULTIMATE_ authority, but if you are in a kind of frenzy, you take the first advice you find. ;)

**Comment by donho** [comment]
`notepad++.exe -noPlugin -nosession` works for me.

**Comment by mshingote** [comment]
There was problem with plugin in my system too.

```
pi->_pFuncIsUnicode = (PFUNCISUNICODE)GetProcAddress(pi->_hLib, "isUnicode");
if (!pi->_pFuncIsUnicode || !pi->_pFuncIsUnicode())
	throw generic_string(TEXT("This ANSI plugin is not compatible with your Unicode Notepad++."));
```

**Comment by reinerblock** [comment]
I uninstalled NP++ completely, moved everything that was left of the config folders to a backup drive and installed it anew.

Now everything is working great again. :)
