### ISSUE TITLE
Wrong behavior when using Enter key from keyboard to select an item from auto select

### ISSUE THREAD

**Issue by ummarbhutta** [notepad-plus-plus/notepad-plus-plus#11256]
### Steps to Reproduce the Issue

1. Create a text file with contents `This is a beautiful City.` and save it.
2. On next line write `I live in this Ci`, as soon as you will write `Ci` you will see a dropdown showing text `City` and selected.
3. Press Enter to select.
4. Text `City` will not be selected and cursor moves to next line.

### Expected Behavior

It should select the focused item from dropdown and place it at current cursor location.

### Actual Behavior

As in step # 4 above

### Debug Information

This issue came after latest upgrade to `8.2.1`, before that it was working as expected.

**Comment by alankilborn** [comment]
![image](https://user-images.githubusercontent.com/77065706/154975060-b65109a7-e3e4-4e6a-a41f-b4d09fd5461e.png)

**Comment by ummarbhutta** [comment]
Thanks @alankilborn , my bad I was not aware of this feature. Looks like it is recently added. It worked.
