### ISSUE TITLE
Gray vertical line appearing suddenly

### ISSUE THREAD

**Issue by SkytAsul** [notepad-plus-plus/notepad-plus-plus#11250]
### Description of the Issue
After enabling the DirectWrite option and restarting NPP, a vertical line appeared on all file editors:
![image](https://user-images.githubusercontent.com/28827134/154863590-a58cf5a7-cee4-462a-b5f9-4b91919fe21f.png)
Is this a bug, or have I enabled another option without knowing?
I have the DarkModeDefault enabled.

### Debug Information
Notepad++ v8.1.9.3   (32-bit)
Build time : Dec  6 2021 - 19:16:45
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 10 Home (64-bit) 
OS Version : 2009
OS Build : 19044.1526
Current ANSI codepage : 65001
Plugins : ComparePlugin.dll mimeTools.dll NppConverter.dll NppExport.dll

**Comment by thomassmith311** [comment]
Think DirectWrite is a red herring. Go to Preferences > Margins/Border/Edge > Vertical Edge Settings and remove whatever number is in the textbox. That should get rid of the line if you don't like it.

**Comment by SkytAsul** [comment]
My savior. Thank you very much. Maybe my cat walked on the keyboard. Have a nice day!
