### ISSUE TITLE
Feature request: more NPPM_MESSAGES.

### ISSUE THREAD

**Issue by Leonard-The-Wise** [notepad-plus-plus/notepad-plus-plus#11253]
Extracted from this post [here](https://community.notepad-plus-plus.org/post/74432)

As I am writting a custom Lexer plugin that have custom indentation (It's on Git, but project still private, sorry), I currently have no way to read the Auto-Indent settings from Notepad and it causes conflicts with my plugin. Something like `NPPM_GETCURRENTAUTOINDENTSTATUS` would be nice to have, so I won't execute my indentation code with that flag turned on.

If possible, if I was able to disable the built-in auto-indentation temporarily from a command would be nice either (although not mandatory). Then I would check the current status, auto-set it to disable, and when language changed (or program exitted) I would restore the user previous state.

Also, I can’t read whether the user is currently recording/playing a macro properly. This also causes conflict with the plugin functionality. I already studied the code and found a `WM_GETCURRENTMACROSTATUS` but it is not enough, since it doesn’t tell me if a macro is running.

Thanks.

**Comment by Ekopalypse** [comment]
I second this, in general it would be beneficial for plugin developers if a notification is available informing about configuration changes. Something like NPPN_CONFIGURATION_CHANGED with wparam an ID that points to the setting and lparam 0 or 1 for Boolean on/off and -1 when it is necessary to call another NPPM_ message to see the current status.
