### ISSUE TITLE
Autocompletion list doesn't react to enter

### ISSUE THREAD

**Issue by luthor112** [notepad-plus-plus/notepad-plus-plus#11269]
### Description of the Issue
When the autocompletion list appears, pressing enter doesn't insert the selected one, but instead starts a new line.
This started happening right after upgrading from Windows 10 to Windows 11.

### Steps to Reproduce the Issue
1. Install npp, enable Auto-Completion
2. Upgrade from Windows 10 to Windows 11
3. Try using Auto-Completion

### Expected Behavior
When I press enter, the highlighted text should be inserted.

### Actual Behavior
Npp starts a new line.

### Debug Information
Notepad++ v8.2.1   (64-bit)
Build time : Jan 19 2022 - 18:43:05
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 11 (64-bit) 
OS Version : 2009
OS Build : 22000.527
Current ANSI codepage : 1252
Plugins : mimeTools.dll NppConverter.dll nppcrypt.dll NppDocShare.dll NppExport.dll NppFTP.dll NPPJSONViewer.dll SecurePad.dll TopMost.dll

**Comment by xomx** [comment]
#11178 
https://github.com/notepad-plus-plus/notepad-plus-plus/blob/master/PowerEditor/bin/change.log#L6
etc.

**Comment by luthor112** [comment]
I can see it's already out. There's another problem then, now with the Update functionality.
This issue can be closed.

**Comment by luthor112** [comment]
Additional info for others:
If not on default options, reaction to the Enter key can be enabled in Settings -> Preferences -> Auto-Completion -> Insert Selection
