### ISSUE TITLE
Make NOTEPAD++ as default opener for .TXT files

### ISSUE THREAD

**Issue by tazotodua** [notepad-plus-plus/notepad-plus-plus#1127]
PLEASE, include automatically checked option during installation, to check the file extensions , to make the NOTEPAD++ as default opener.

**Comment by polymetric1** [comment]
You can do this in preferences. http://lmgtfy.com/?q=notepad%2B%2B+default+for+txt+files

**Comment by MetaChuh** [comment]
* close notepad++ if it is open
* right click on any .txt file and choose `open with > choose other app` and select notepad++ from this list.
* select `always use this app to open .txt files`and hit ok.
* close notepad++ again and retry opening your .txt file by double clicking on it.

if you are not able to select notepad++.exe form the choose other app list above:

* close notepad++ if it is open
* right click on your notepad++ icon and choose "run as administrator"
(make sure you see `[Administrator]` at the top bar of your notepad++ window (see screenshot)
* go to `settings > preferences > file association` and make sure your needed extensions, like .txt are visible at the registered extensions panel (last panel on the right) as seen on this screenshot:

![Imgur](https://i.imgur.com/m0St1R0.png)

* hit close and exit notepad++
* now reopen notepad++ normally, and go to `settings > preferences > file association` again, and make sure your needed extensions are also visible for the standard user account.
* then exit notepad++ again
* right click on any .txt file and choose `open with > choose other app` and select notepad++ from this list.
* select `always use this app to open .txt files`and hit ok.
* close notepad++ again and retry opening your .txt file by double clicking on it.

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
```
[<kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd>](https://notepad-plus-plus.org/community/)
