### ISSUE TITLE
Crash when XML-Tools installed and in an xml file enter ">"

### ISSUE THREAD

**Issue by MichaelEnke** [notepad-plus-plus/notepad-plus-plus#11285]
When XML-Tools is installed: When edit an xml file and pressing the ">" key, notepad++ crashes.
When XML-Tools is not installed, no crash.
I know that this could be an issue in the XML-Tools plugin, but this issue happens since my NPP was updated but no XML-Tools updated.

### Debug Information
Notepad++ v8.3   (64-bit)
Build time : Feb  3 2022 - 03:39:05
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 10 Pro (64-bit) 
OS Version : 2009
OS Build : 19042.1526
Current ANSI codepage : 65001
Plugins : JSMinNPP.dll mimeTools.dll NppConverter.dll NppExport.dll NPPJSONViewer.dll XMLTools.dll

**Comment by alankilborn** [comment]
Try 8.3.1

**Comment by MichaelEnke** [comment]
Not solved with 8.3.1.
Notepad++ v8.3.1   (64-bit)
Build time : Feb 13 2022 - 15:41:12
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 10 Pro (64-bit) 
OS Version : 2009
OS Build : 19042.1526
Current ANSI codepage : 65001
Plugins : JSMinNPP.dll mimeTools.dll NppConverter.dll NppExport.dll NPPJSONViewer.dll XMLTools.dll

**Comment by alankilborn** [comment]
Oops.  I read your initial comment wrong.  Sorry.
You probably want to pursue this through a newer version of XMLTools, if one exists.
Sometimes Notepad++ core changes and plugins need to follow.

**Comment by vinsworldcom** [comment]
@MichaelEnke if you're on Notepad++ >= 8.3, you will need XML Tools >= 3.1.1.12.  That should be available in Plugin Admin to upgrade; otherwise you can manually install from https://github.com/morbac/xmltools

I have Notepad++ 8.3.2 RC1 and XML Tools 3.1.1.12 and cannot replicate your crash.

Cheers.

**Comment by MichaelEnke** [comment]
I deinstalled XML-Tools as I tested without it, then installed again - that should have installed the latest version, at least I thought. Version offered from NPP plugin management is 3.1.1.10. I checked Github and latest version is 3.1.1.12 - that fixes the issue. Thanks!
