### ISSUE TITLE
DSpellCheck plugin underlined words also print with underlines

### ISSUE THREAD

**Issue by Intrepid-MR** [notepad-plus-plus/notepad-plus-plus#11281]
### Steps to Reproduce the Issue

1.  Click on Plugins, DSpellCheck
2.  Select "Spellcheck document automatically"
3.  Type a misspelled word which will be underline in red
4.  Print the document and the underlining also prints

### Expected Behavior

Don't print underlines for "misspelled" words

### Actual Behavior

Documents print with words underlined

**Comment by chcg** [comment]
The issue could be added here https://github.com/Predelnik/DSpellCheck/issues.
