### ISSUE TITLE
Debug info dialog lists the installed plug-ins but not the plug-in versions

### ISSUE THREAD

**Issue by BdR76** [notepad-plus-plus/notepad-plus-plus#11284]
### Debug info dialog lists plug-ins but not versions

In the menu `? -> Debug info -> Copy debug info to clipboard` on the last line it lists the plug-ins that are installed. However, it only lists the dll names and not the version for each plug-in.

This would be handy to determine if an old plugin is causing problems.

### Steps to Reproduce the Issue
See menu `? -> Debug info -> Copy debug info to clipboard`

### Actual Behavior
The current debug info text is like this for example:

```
Notepad++ v8.2.1   (64-bit)
Build time : Jan 19 2022 - 18:43:05
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : "C:\Users\ReuverB\************DataDictionary.csv"
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows Server 2019 Standard (64-bit) 
OS Version : 1809
OS Build : 17763.2452
Current ANSI codepage : 1252
Plugins : ComparePlugin.dll CSVLint.dll CsvQuery.dll NppConverter.dll NppExport.dll
```

### Expected Behavior
It would be nice if it showed something like this:
```
..
Plugins : ComparePlugin.dll (v2.0.1) CSVLint.dll (v0.4.4) CsvQuery.dll (v1.2.8) NppConverter.dll (v4.3) NppExport.dll (v0.3)
```

**Comment by alankilborn** [comment]
As far as I can see from the user manual, there is no current command definition for N++ to get a plugin's version.

**Comment by BdR76** [comment]
Ok I don't know about that, but the plug-in versions are visible in Notepad++ under `Plugins -> Plugins admin -> tab Installed`, so I assume they're available somewhere within Notepad(?).

**Comment by alankilborn** [comment]
>but the plug-in versions are visible in Notepad++ under Plugins -> Plugins admin -> tab Installed, so I assume they're available somewhere within Notepad

OK, good point.

**Comment by rdipardo** [comment]
N++ can easily look up plugin versions at runtime with the [`GetFileVersionInfo`] Win32 API function.
But this assumes every plugin was linked with a resource file containing version info (what you see in the "Properties" dialog under the "Details" tab when you right-click a DLL).

It seems the Plugins Admin library goes the easier way of [hard-coding the whole list as JSON text]. 


[`GetFileVersionInfo`]: https://docs.microsoft.com/en-us/windows/win32/api/winver/nf-winver-getfileversioninfoa
[hard-coding the whole list as JSON text]: https://github.com/notepad-plus-plus/nppPluginList/blob/master/src/nppPluginList.rc#L31

**Comment by alankilborn** [comment]
>N++ can easily look up plugin versions at runtime with the [GetFileVersionInfo](https://docs.microsoft.com/en-us/windows/win32/api/winver/nf-winver-getfileversioninfoa) Win32 API function.
But this assumes every plugin was linked with a resource file containing version info (what you see in the "Properties" dialog under the "Details" tab when you right-click a DLL).

Yep, big assumption, though.

**Comment by BdR76** [comment]
> It seems the Plugins Admin library goes the easier way of [hard-coding the whole list as JSON text](https://github.com/notepad-plus-plus/nppPluginList/blob/master/src/nppPluginList.rc#L31).

Yes, the "Available" tab shows the hardcoded JSON list versions, but the "Installed" tab shows the actual versions of the installed DLLs. Notepad++ compares these versions and displays any older versions in the "Updates" tab.

Also, the debug info dialog is typically used for trouble shooting, so you do need the actual installed versions to verify that it's not any outdated plug-ins that are causing problems.

**Comment by vinsworldcom** [comment]
> but the "Installed" tab shows the actual versions of the installed DLLs. Notepad++ compares these versions and displays any older versions in the "Updates" tab.

@BdR76 @alankilborn @rdipardo , indeed:

https://github.com/notepad-plus-plus/notepad-plus-plus/blob/8132f4f3b01ae34196200984924fe79f6854c827/PowerEditor/src/WinControls/PluginsAdmin/pluginsAdmin.cpp#L68

I think it's a great idea!

Cheers.

**Comment by rdipardo** [comment]
> https://github.com/notepad-plus-plus/notepad-plus-plus/blob/8132f4f3b01ae34196200984924fe79f6854c827/PowerEditor/src/WinControls/PluginsAdmin/pluginsAdmin.cpp#L68
> 

Yes, but look how it's implemented:

https://github.com/notepad-plus-plus/notepad-plus-plus/blob/8132f4f3b01ae34196200984924fe79f6854c827/PowerEditor/src/WinControls/PluginsAdmin/pluginsAdmin.cpp#L78-L85

Like I said, [`::GetFileVersionInfo`] returns useful data only if the DLL was compiled with a resource file. No resources means the `buffer` and `cbFileInfo` pointers end up NULL,  and the version comparsion is skipped.
 
 [`::GetFileVersionInfo`]: https://docs.microsoft.com/en-us/windows/win32/api/winver/nf-winver-getfileversioninfoa
[`VerQueryValue`]: https://docs.microsoft.com/en-us/windows/win32/api/winver/nf-winver-verqueryvaluea

**Comment by vinsworldcom** [comment]
But isn't that better than nothing?  Most Plugins have a version compiled in, and for the ones that don't we just don't get a version:

![image](https://user-images.githubusercontent.com/9657169/155803887-b087af22-9053-4fdf-8598-04eb9d70243b.png)

**Comment by alankilborn** [comment]
Does it have value to flag plugins whose installed versions are behind the latest available, in the _Debug Info_?

Something like `TagLEET-1.3.10.2✓` for an up-to-date version installed and `TagLEET-1.3.10.1🠧` for something behind the latest known version?

**Comment by vinsworldcom** [comment]
Yes, to some extent. The update tab will show plugins that have a newer version than what is installed. I'm assuming that is pulling from the npppluginlist.dll though.

**Comment by alankilborn** [comment]
>The update tab will show plugins that have a newer version than what is installed

Yes but the point of this issue is to convey the data for tech support purposes in the Debug Info.

**Comment by vinsworldcom** [comment]
@alankilborn sorry I misread your response. You're asking, does it add value to include a mark in the proposed plug-in version in debug info?

Yes that would be nice but I would be happy with just the version numbers.

Cheers.

**Comment by BdR76** [comment]
> Something like `TagLEET-1.3.10.2✓` for an up-to-date version installed

Thanks for the suggestion, but I think it's better to just display the version instead of only a checkmark for "latest version", because the version label is unambiguous.

I mean, what if you get a debug info just days after a plugin was updated? Did the user have the latest plugin version or the previous version? You would have to infer it from the Notepad++ version which is a hassle imho.

**Comment by rdipardo** [comment]
> Thanks for the suggestion, but I think it's better to just display the version instead of only a checkmark for "latest version", because the version label is unambiguous.

Would something like this be acceptable?

![npp_dbg_info_enhanced](https://user-images.githubusercontent.com/59004801/166885742-affec090-06b4-4eba-aec9-b4b282d576f9.png)

**Comment by BdR76** [comment]
> Would something like this be acceptable?

That looks perfect actually. Is that a mock-up screenshot or already working code?

**Comment by rdipardo** [comment]
>  Is that a mock-up screenshot or already working code?

Compiled from a fork. I was still hoping to create a more column-based layout, but found that `printf` alignment specifiers don't work as expected because the "MS System" font is not monospaced, and there's no configuring a Win32 message box as you could, say, a [Task Dialog](https://docs.microsoft.com/en-us/windows/win32/controls/task-dialogs-overview).

**Comment by BdR76** [comment]
The main thing is that it shows the correct version labels. Any extra formatting beyond what you have now (which already looks great) would be over-engineering it imho. I think you should submit it in a pull request, this is a nice update.
