### ISSUE TITLE
Autoselection on hitting enter key is not working in current notepad released version i.e product version: 8.21

### ISSUE THREAD

**Issue by RitikaGhosh15** [notepad-plus-plus/notepad-plus-plus#11291]
### Description of the Issue

Autoselection of any word is not working when hitting enter from keyboard

### Steps to Reproduce the Issue

1. Open Notepad++
2. write any word on first line
3. repeat the same word in second line and after autoselection option visible hit enter from keyboard

### Expected Behavior
- The selected item should automatically be written on 2nd line

### Actual Behavior
- After hitting enter, the selected option is not visible in the expected line.

### Debug Information
Notepad++ v8.2.1   (32-bit)
Build time : Jan 19 2022 - 18:38:49
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 10 Enterprise (64-bit) 
OS Version : 2009
OS Build : 19042.1348
Current ANSI codepage : 1252
Plugins : JSMinNPP.dll mimeTools.dll NppConverter.dll NppExport.dll NPPJSONViewer.dll XMLTools.dll 

<img width="237" alt="image" src="https://user-images.githubusercontent.com/82997275/155710939-a8022ebd-c46e-43fd-8d69-fa225fd63405.png">

**Comment by alankilborn** [comment]
![image](https://user-images.githubusercontent.com/77065706/155711925-6e26bbef-d4ee-4e8c-9cbb-2553bd113d02.png)

**Comment by RitikaGhosh15** [comment]
@alankilborn Thank you. now its working
