### ISSUE TITLE
Does nppLogNulContentCorruptionIssue.xml need to be included in the distribution archive files?

### ISSUE THREAD

**Issue by Gitoffthelawn** [notepad-plus-plus/notepad-plus-plus#11304]
### Description of the Issue
Does `nppLogNulContentCorruptionIssue.xml` need to be included in the distribution archive files?

### Details, Details, Details
It's a little odd to see it included, but if needs to be included, no problem.  An an experiment, I tried deleting it, and didn't notice a difference.  But now my desk light won't turn off.  ;)

### Debug Information
The file is present, at least, in the 32-bit `.7z` portable archive file for v8.3.2.

**Comment by dfs-** [comment]
This files triggers a setting that will generate additional information when a NUL Content corruption is detected. You can remove it safely in your local installation.

**Comment by Gitoffthelawn** [comment]
@dfs- Thank you Daniel.  Is that file intentionally included in the distribution files?  If so, I'll close this issue.

**Comment by dartraiden** [comment]
> Is that file intentionally included in the distribution files?

See https://notepad-plus-plus.org/news/v8193-released/

**Comment by Gitoffthelawn** [comment]
@dartraiden Thanks so much Daniel.  I make a point to read all release notes for all software I use or recommend, but somehow that one slipped by me.  Thanks for the link.  I was going through the code figuring out the exact purpose of that file, and the release notes add much clarity.

Closing this issue now.  Thanks again for your help.
