### ISSUE TITLE
NP++ 8.3.1+Extension type not appended when saving with Return (win 7)

### ISSUE THREAD

**Issue by EatDesk** [notepad-plus-plus/notepad-plus-plus#11305]
### Description of the Issue

As reported previously in this issue: https://github.com/notepad-plus-plus/notepad-plus-plus/issues/9657

The bug where the extension type is not appended when saving with the Return key is back on win 7 in NP++ 8.3.1 or higher.

NP++ 8.2.1 does not have this issue so I'm guessing it is as a result of the following commit: https://github.com/notepad-plus-plus/notepad-plus-plus/commit/b5a5baf13bb3f0b041f49698afb74af2b7059f6a

@mere-human should be familiar with this having fixed the previous issues.

### Steps to Reproduce the Issue

ALT -> F -> A -> for the "Save As..." menu, type filename and hit Return.

The CTRL+ALT+S shortcut followed by hitting Return will also replicate the issue.

### Expected Behavior
Output: lol.txt

### Actual Behavior
Output: lol

### Debug Information

Notepad++ v8.3.2   (64-bit)
Build time : Feb 27 2022 - 03:35:46
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : 
Admin mode : ON
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 7 Ultimate (64-bit) 
OS Build : 7601.0
Current ANSI codepage : 1252
Plugins : ComparePlugin.dll mimeTools.dll NppConverter.dll NppExport.dll

**Comment by mere-human** [comment]
Hi @EatDesk 
Thank you for the report. I can't take a look at it currently. 
I'm in Ukraine now. Russian forces are still attacking the country.

**Comment by EatDesk** [comment]
Very sorry to hear that @mere-human ! Take care of yourself.

**Comment by Yaron10** [comment]
@mere-human,

I hope you stay safe and strong in these harsh days. 
I wish you, your family and friends the very best.

**Comment by Yaron10** [comment]
@EatDesk,

Have you tried it with Win 10? Is it unique to Win 7?

**Comment by xomx** [comment]
@mere-human 
Take care of yourself! Hope this war will end up soon.

**Comment by mere-human** [comment]
> @EatDesk,
> 
> Have you tried it with Win 10? Is it unique to Win 7?

It would be nice if somebody else can confirm it on Windows 7.
Also, does it work if your press Alt+S while the file dialog is open? Also, try making the Save button focused with tab and then press Space.

---

Thank you guys for your support!

**Comment by Yaron10** [comment]
@mere-human,

I can't reproduce it on Windows 10.
I'll try the various cases on Windows 7 tomorrow.

I hope you're in a safe place.
Best wishes.

**Comment by Yaron10** [comment]
@mere-human,

I've tested the various cases on Windows 7 **32-bit**. I can not reproduce it.

@EatDesk,

Could you please list again your **exact steps**?
Can you also try it with a fresh portable Notepad++?

@xomx,

Could you please test it too?

**Comment by xomx** [comment]
@Yaron10 
I can try tomorrow.

**Comment by Yaron10** [comment]
@xomx,

> Hope this war will end up soon.

Just remembered the catchphrase by the great Czech writer Jaroslav Hašek: "After the war at six o'clock". :)

**Comment by Yaron10** [comment]
https://github.com/notepad-plus-plus/notepad-plus-plus/issues/9657#issuecomment-799508446

> You're right it doesn't occur with a fresh portable version. However that allowed me to find the setting that was causing this, it was the default save file directory apparently: Settings > Preferences > Default Directory: C:\Users\EatDesk\Desktop

I missed that. I can reproduce it on Win 7.

> Also, does it work if your press Alt+S while the file dialog is open? Also, try making the Save button focused with tab and then press Space.

The problem only exists on pressing "Enter".

**Comment by donho** [comment]
@mere-human 
Take care & good luck!
