### ISSUE TITLE
Considering adding support statements for Ukraine and condemning Russia's aggressive war

### ISSUE THREAD

**Issue by lietu** [notepad-plus-plus/notepad-plus-plus#11302]
### Description of the Issue
Russia is currently fighting a ruthless war of aggression against Ukraine, while Russians inside their own borders are denied much of the information on the justifications for it, the actions being committed, or the losses their forces are facing.

Russians however still need to use everyday tools such as editors like everyone else, and this could be a way to reach some of them and cause further internal pressure to force the war to an end.

### Steps to Reproduce the Issue
1. Download Notepad++
2. Install Nodepad++
3. Launch Nodepad++
4. Use Notepad++

### Expected Behavior
A message to condemn Russian government actions, or sharing the truth of their actions is shown - at least to users within Russia if geolocation is desired & possible.

### Actual Behavior
No message seen targeting Russian users condemning their government's actions

### Final thoughts
The developer community can choose to participate in a peaceful protest, and raising the message of injustices in the world. Your "Stand with Hong Kong Edition" has clearly ruffled some feathers already, and this could ruffle some more of the right kind of feathers.

To be fully effective a Russian translation of the messages is likely preferred.

**Comment by rdipardo** [comment]
<https://notepad-plus-plus.org/news/v832-declare-variables-not-war/>

**Comment by rdipardo** [comment]
> https://notepad-plus-plus.org/news/v832-declare-variables-not-war/

# :warning: :warning: :warning:

At paragraph 3 of the release notes, it reads:

> You can also sign a [petition](https://www.openpetition.eu/petition/online/people-around-the-world-ask-nato-to-close-the-airspace-over-ukraine) [. . .]

A community member has reported that the petition website may be linked to a phishing scam: <https://community.notepad-plus-plus.org/topic/22646/notepad-v8-3-2-release-declare-variables-not-war/18>

Visit the [donations page](https://notepad-plus-plus.org/donate-to-ukraine/) for alternative ways to support the cause.

# :warning: :warning: :warning:

**Comment by jmp0x7c00** [comment]
Ukraine deserves it...

**Comment by LoganDark** [comment]
What the fuck is this issue? Why are you opening issues when you _don't_ see political protests in your software? This is stupid.

**Comment by SkpC9** [comment]
> What the fuck is this issue? Why are you opening issues when you _don't_ see political protests in your software? This is stupid.

Yeah, this is stupid, but the developers don't think so. There are already many versions which include those political things.
