### ISSUE TITLE
double-clicking on a "find all in current document" result, for an unsaved doc, prompts to save it

### ISSUE THREAD

**Issue by bughit** [notepad-plus-plus/notepad-plus-plus#11300]
### Steps to Reproduce the Issue
1. start np++
2. enter some text into the empty new doc
3. "find all in current document" the entered text
4. double click on the first and only find result 

### Expected Behavior
no prompt to save the doc

### Actual Behavior
prompt to save the doc

### Debug Information
Notepad++ v8.3.1   (64-bit)
Build time : Feb 13 2022 - 15:41:12
Path : C:\tmp\npp.8.3.1.portable.minimalist.x64\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : ON
Cloud Config : OFF
OS Name : Windows 10 Enterprise (64-bit) 
OS Version : 2009
OS Build : 19044.1526
Current ANSI codepage : 1252
Plugins : none

**Comment by alankilborn** [comment]
Tested in N++ 8.4.4 (current version as of this writing) and could not repro.
Recommend CLOSURE of this item.
