### ISSUE TITLE
Labels in Find dialog moved unintentionally in v8.2.1+

### ISSUE THREAD

**Issue by dfs-** [notepad-plus-plus/notepad-plus-plus#11318]
### Description of the Issue
After Notepad++ 8.2 the labels in the Find dialog are a offset making it overflow in some non-Englisch translations.

Here's how it looked in 8.2:
![2022-03-02 09_20_10-Notepad++8 2](https://user-images.githubusercontent.com/6563013/156323245-1aa3f0c7-3b56-475f-82a3-49194fe31527.png)

And here's how it looks right now:
![2022-03-02 09_20_10-Notepad++8 2 1_and_above](https://user-images.githubusercontent.com/6563013/156323288-a02369a9-8cf9-4f39-9345-05d2b95b07f1.png)

Please note the "Find what", "Replace with", "Filters" texts.

### Steps to Reproduce the Issue
1. Open the Find dialog using CTRL+F

### Expected Behavior
Positioning as in Notepad++ 8.2

### Actual Behavior
Positioning is a bit offset.

### Debug Information
Notepad++ v8.3.2   (64-bit)
Build time : Feb 27 2022 - 03:35:46
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 10 Pro (64-bit) 
OS Version : 2009
OS Build : 19044.1526
Current ANSI codepage : 1252
Plugins : ComparePlugin.dll JSMinNPP.dll mimeTools.dll NppConverter.dll NppExport.dll PythonScript.dll XMLTools.dll

**Comment by dfs-** [comment]
See PR #11320 for proposed fixed layout.

**Comment by cezariuszmarek** [comment]
BTW note https://www.sussex.ac.uk/informatics/punctuation/colonandsemi/colon

> the colon is **never** preceded by a white space

**Comment by alankilborn** [comment]
>the colon is never preceded by a white space

Well maybe in writing...but un user interface text with proportional fonts, I think it helps.

**Comment by cezariuszmarek** [comment]
> I think it helps.

I respectfully disagree. I find it distracting when programmers think they know better and don't follow the general writing rules.

**Comment by alankilborn** [comment]
>I find it distracting when programmers think they know better and don't follow the general writing rules.

But user interfaces aren't formal writing.
In a proportional font such as that used in the labels of the _Find_ window, the colon jammed up against the text, really makes it harder to read, IMO.  If it was a fixed-pitch font, it wouldn't matter.
Also, one could take the stance that the colon should be implied, and not even used.

**Comment by nanangp** [comment]
I'm in the "don't bother with colons" camp. But I also strongly feel that **consistency** should trump correctness. If one were to use colons, at least use them consistently; which currently is not (yet) the case for N++. 

The inconsistencies are present in many popup windows, Preferences being one that carries all 3 variants (with space, without space, and even no colon at all).

**Comment by alankilborn** [comment]
>consistency should trump correctness

I like to say it as "consistency is king". :-)

I think the colons are unnecessary, so it would be best to do a global remove of them.  If they are not there, there's no debate about them having a space before them or not.

**Comment by pryrt** [comment]
For those who don't like the space before the colon, edit `localization\english_customizable.xml` to remove the colons, then switch to **Settings > Preferences > Localization = `English (customizable)`**, _et voila_, no spacey colons for you.  That makes everyone happy. Don makes Notepad++ so overwhelmingly customizable to make as many people happy as possible.  🎉
