### ISSUE TITLE
Macro doesn't record 4 button commands

### ISSUE THREAD

**Issue by bashbeik** [notepad-plus-plus/notepad-plus-plus#1131]
I cannot record a macro to pretty print ( ctrl+shift+alt+b)

**Comment by sampalmer** [comment]
I just tested this out, and it seems that Notepad++ 7.2 doesn't support recording macros to support some (or maybe all) keyboard shortcuts. I tested the following keyboard shortcuts:

* Ctrl + O
* Ctrl + Shift + Alt + B
* Alt + M

Personally, I'm fine with this; I haven't yet run into a situation where I've needed to automate this sort of thing. Maybe you're looking for a higher-level macro tool that operates on an OS-level?

**Comment by MetaChuh** [comment]
please use macros only for built in features, not for plugins like xmltools.

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)
