### ISSUE TITLE
Register QuietUninstallString in Registry to be fully compatible with Winget

### ISSUE THREAD

**Issue by fulopm** [notepad-plus-plus/notepad-plus-plus#11310]
Hello,

as you can see in [this](https://github.com/microsoft/winget-pkgs/issues/49601) issue I created in winget-pkgs, Notepad++ silent uninstall would work in winget if it would implement writing the QuitUninstallString registry value. With that, winget would know what arguments to use for a silent uninstall.

Is it possible to implement this? We're automating Notepad++ silent installation on corporate machines with winget, and the absence of this feature forces us to bypass winget and use a custom uninstall command.

Thank you!

**Comment by xomx** [comment]
@fulopm 
I will look at it.

**Comment by chcg** [comment]
see https://nsis.sourceforge.io/Add_uninstall_information_to_Add/Remove_Programs

**Comment by KaranKad** [comment]
@xomx I tested it on my system and it works fine.

**Comment by fulopm** [comment]
@xomx
I created a custom Winget manifest with this installer, and the silent uninstall worked as intended. 
Thank you for the quick fix!

**Comment by xomx** [comment]
Ok, I will create a PR for this.
