### ISSUE TITLE
Fx icon shown for keywords that are not functions

### ISSUE THREAD

**Issue by EuropeanDeveloper** [notepad-plus-plus/notepad-plus-plus#11311]
### Description of the Issue

After the implementation of #11087, "fx" icon is shown for all keywords from auto-completion file. The icon should be shown only for keywords with attribute `func="yes"`.

### Steps to Reproduce the Issue

1. Open empty file.
2. Set language to `C`.
3. Type `ab`.

![screenshot](https://user-images.githubusercontent.com/52759436/156064729-72f9738d-483d-4845-9d22-432eb920a1a5.png)

### Expected Behavior

"fx" icon is shown only for functions (`abort`, `abs`, `access`, `acos`), not for keywords (`absread`, `abswrite`, `acosl`, `allocmem`, `arc`).

### Actual Behavior

"fx" icon is shown for all keywords (including ones that are not functions) from auto-completion file.

### Debug Information

Notepad++ v8.3.2   (64-bit)
Build time : Feb 27 2022 - 03:35:46
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 10 Enterprise (64-bit) 
OS Version : 2009
OS Build : 19042.1526
Current ANSI codepage : 1250
Plugins : DSpellCheck.dll mimeTools.dll NppConverter.dll NppExport.dll XMLTools.dll

**Comment by xomx** [comment]
@EuropeanDeveloper 
https://community.notepad-plus-plus.org/topic/22587/autocomplete-items-order-issue/28
https://community.notepad-plus-plus.org/topic/22587/autocomplete-items-order-issue/32

@vinsworldcom
Maybe it is not a well-chosen symbol for that.

**Comment by vinsworldcom** [comment]
@EuropeanDeveloper @xomx , we can change the "icon", a simple XPM "file" [embedded into the AutoCompletion.cpp source](https://github.com/notepad-plus-plus/notepad-plus-plus/blob/30b6b18d1ebcaec11afc6ccb95c091ac1edb6ced/PowerEditor/src/ScintillaComponent/AutoCompletion.cpp#L24).

There currently is no code in AutoCompletion.cpp to check for `func=yes` so there was no way for me (at the time) to add differentiated icons.  My goal was to distinguish between "autoComplete/*.xml" files and words from the current Notepad++ document.  It was easier to add icons to the "autoComplete/*.xml" items than to current document words (explanation in the [original issue](https://github.com/notepad-plus-plus/notepad-plus-plus/issues/11087)).

I'm afraid I don't have the requisite C++ skills to add the check for `func=yes` parameter in the XML parsing.  My guess is it would go [somewhere here](https://github.com/notepad-plus-plus/notepad-plus-plus/blob/30b6b18d1ebcaec11afc6ccb95c091ac1edb6ced/PowerEditor/src/ScintillaComponent/AutoCompletion.cpp#L969) and if `func=yes` then add the "fx" image and if not then add a different image.  The goal being that *any* words from the "autoComplete/*.xml" files get an icon to distinguish them from discovered current document words.  We could create a simple "block" image  like the VS Code image referenced at the [bottom of my comment](https://community.notepad-plus-plus.org/topic/22587/autocomplete-items-order-issue/28).

Cheers.

**Comment by vinsworldcom** [comment]
Here's an XPM for this image:

![image](https://user-images.githubusercontent.com/9657169/156087238-8c8f79d0-823c-4b57-9421-50f85321cad2.png)


```
const char* xpmbox[] = {
    /* columns rows colors chars-per-pixel */
    "16 16 70 1 ",
    "  c None",
    ". c #712472",
    "X c #752775",
    "o c #7A2B7B",
    "O c #7C2D7D",
    "+ c #7C2E7C",
    "@ c #7E2E7E",
    "# c #7E307F",
    "$ c #7F3080",
    "% c #8D358E",
    "& c #953896",
    "* c #9C3C9D",
    "= c #9F3C9F",
    "- c #8E468F",
    "; c #904E91",
    ": c #965297",
    "> c #A74FA8",
    ", c #A650A7",
    "< c #A850A9",
    "1 c #A950AA",
    "2 c #A952AA",
    "3 c #BB6FBC",
    "4 c #BC70BD",
    "5 c #CB67CC",
    "6 c #D16AD2",
    "7 c #D26BD3",
    "8 c #D16DD2",
    "9 c #D36ED4",
    "0 c #D56FD5",
    "q c #8A99AE",
    "w c #98A4AE",
    "e c #9CA7AE",
    "r c #ACB5AD",
    "t c #ACB4AE",
    "y c #B5BBAD",
    "u c #C1C4AC",
    "i c #CCCEAC",
    "p c #D5D5AC",
    "a c #E5E2AB",
    "s c #E9E5AB",
    "d c #F7F0AB",
    "f c #CF88CF",
    "g c #DD98DE",
    "h c #E698E7",
    "j c #E990EA",
    "k c #EB91EC",
    "l c #EE9DEF",
    "z c #FA98FB",
    "x c #FA99FB",
    "c c #FA9BFB",
    "v c #FA9FFB",
    "b c #E3ACE3",
    "n c #E2AFE2",
    "m c #EEA5EF",
    "M c #EEBEEE",
    "N c #FAABFB",
    "B c #FAAEFB",
    "V c #E4CAE4",
    "C c #E6CCE6",
    "Z c #E8D1E8",
    "A c #EBD1EB",
    "S c #ECD2EC",
    "D c #EDD8ED",
    "F c #F0D4F0",
    "G c #F0D5F0",
    "H c #F2DBF2",
    "J c #F0E3F0",
    "K c #F2E0F3",
    "L c #F3E3F3",
    "P c #F4E6F4",
    /* pixels */
    "                ",
    "                ",
    "         HfJ    ",
    "        HfbfL   ",
    "       FfMBkfJ  ",
    "  dptq fnNzzjfP ",
    "       ,3mxxzh; ",
    "dsputw ,83mvl:@ ",
    "       <604g-*@ ",
    " daiyw C179$=%O ",
    "        Z15@&OG ",
    "         D1@XZ  ",
    "          S.C   ",
    "                ",
    "                ",
    "                "
};
```

**Comment by EuropeanDeveloper** [comment]
I understand what was the idea behind "fx" icon. I still think there should be different symbols for functions (`func=yes`) and actual keywords. Sometimes it is a quite confusing to know which word is a keyword and which one is a name of a function.

**Comment by vinsworldcom** [comment]
@EuropeanDeveloper how's this:

![image](https://user-images.githubusercontent.com/9657169/156183181-80d06d1a-b0e5-4d14-8d1f-941aec00ea5e.png)


**NOTE:** This creates a ***whole new problem*** of updating the autoComplete/*.xml files.  Take your example of C - my file looks like this:

```XML
[...]
		<KeyWord name="atan" func="yes">
			<Overload retVal="double" >
				<Param name="double x" />
			</Overload>
		</KeyWord>
		<KeyWord name="atan2" func="yes">
			<Overload retVal="double" >
				<Param name="double y" />
				<Param name="double x" />
			</Overload>
		</KeyWord>
		<KeyWord name="atan2l" />
		<KeyWord name="atanl" />
[...]
```

see how `atan` and `atan2` are functions but `atan21` and `atanl` are not by definition in the XML file.  So, autocomplete will happily display that now:

![image](https://user-images.githubusercontent.com/9657169/156183784-df38c404-0cac-4565-b5f1-d665fa727285.png)

see `atan21` and `atanl` marked "correctly" by the code because indeed they are not ***configured*** to be functions, but incorrect logically as they are functions.

Cheers.

**Comment by EuropeanDeveloper** [comment]
I like the proposed solution 🙂. The behavior is expected and correct to my mind. If someone wants to list functions in auto-completion file they should mark them as functions using `func=yes`! Notepad++ can't guess which ones are functions and which ones are not. This is up to the author of auto-completion file.

**Comment by donho** [comment]
Problem:
In some (even many) language function entirs, there's no `func` attribute at all - see javascript.xml:
https://github.com/notepad-plus-plus/notepad-plus-plus/blob/master/PowerEditor/installer/APIs/javascript.xml

**Comment by vinsworldcom** [comment]
@donho  for those languages that don't have `func="yes"`, they'll just show the new "box" icon.  As people contribute and update the autoComplete/*.xml files with `func="yes"` as appropriate, their icons will change.  Reference the following example using Javascript as the language as you pointed out does not have any "functions" defined in the "autoComplete/javascript.xml" file:

![image](https://user-images.githubusercontent.com/9657169/156465363-470638f3-f403-4c34-83b5-b51c38301772.png)

I think that looks OK.  And then any complaints about "functions not showing with "fx"" can easily be fixed with pull requests to update the autoComplete files rather than changing the N++ AutoCompletion.cpp code.

That's my argument for the counterpoint.  Understand this is your project and you have the final say.

Cheers.

**Comment by EuropeanDeveloper** [comment]
@vinsworldcom: I agree with you.

@donho: What about other languages like Batch/CofeeScript/HTML/TypeScript? Their auto-completion files contain mostly keywords. Or some auto-completion files contain preprocessor definitions (e.g. #define). I don't think it makes sense to see "fx" icon for non-functions. The proposed solution by @vinsworldcom will not negatively affect the current implementation I think. If you don't like it, at least change the icon from "fx" to something else. The current icon is really confusing. "fx" implies function, not keywords...

**Comment by vinsworldcom** [comment]
@EuropeanDeveloper there is a bit of a workaround that can be triggered after Autocomplete is used once and if you have PythonScript installed.  The first time Notepad++ autocomplete is triggered and goes through to show the list, it registers the "fx" image and sets a flag to that it never registers it again.  You can override the registration by registering a new image with the same image ID as the "fx" icon, but it will only work **_after_** the "fx" image is registered by triggering autocomplete for the first time in a Notepad++ session.  Basically, after that first autocomplete, just run the following PythonScript (assuming you have that plugin installed):

```Python
from Npp import editor

xpmbox = """/* XPM */
"16 16 70 1 ",
"  c None",
". c #712472",
"X c #752775",
"o c #7A2B7B",
"O c #7C2D7D",
"+ c #7C2E7C",
"@ c #7E2E7E",
"# c #7E307F",
"$ c #7F3080",
"% c #8D358E",
"& c #953896",
"* c #9C3C9D",
"= c #9F3C9F",
"- c #8E468F",
"; c #904E91",
": c #965297",
"> c #A74FA8",
", c #A650A7",
"< c #A850A9",
"1 c #A950AA",
"2 c #A952AA",
"3 c #BB6FBC",
"4 c #BC70BD",
"5 c #CB67CC",
"6 c #D16AD2",
"7 c #D26BD3",
"8 c #D16DD2",
"9 c #D36ED4",
"0 c #D56FD5",
"q c #8A99AE",
"w c #98A4AE",
"e c #9CA7AE",
"r c #ACB5AD",
"t c #ACB4AE",
"y c #B5BBAD",
"u c #C1C4AC",
"i c #CCCEAC",
"p c #D5D5AC",
"a c #E5E2AB",
"s c #E9E5AB",
"d c #F7F0AB",
"f c #CF88CF",
"g c #DD98DE",
"h c #E698E7",
"j c #E990EA",
"k c #EB91EC",
"l c #EE9DEF",
"z c #FA98FB",
"x c #FA99FB",
"c c #FA9BFB",
"v c #FA9FFB",
"b c #E3ACE3",
"n c #E2AFE2",
"m c #EEA5EF",
"M c #EEBEEE",
"N c #FAABFB",
"B c #FAAEFB",
"V c #E4CAE4",
"C c #E6CCE6",
"Z c #E8D1E8",
"A c #EBD1EB",
"S c #ECD2EC",
"D c #EDD8ED",
"F c #F0D4F0",
"G c #F0D5F0",
"H c #F2DBF2",
"J c #F0E3F0",
"K c #F2E0F3",
"L c #F3E3F3",
"P c #F4E6F4",
"                ",
"                ",
"         HfJ    ",
"        HfbfL   ",
"       FfMBkfJ  ",
"  dptq fnNzzjfP ",
"       ,3mxxzh; ",
"dsputw ,83mvl:@ ",
"       <604g-*@ ",
" daiyw C179$=%O ",
"        Z15@&OG ",
"         D1@XZ  ",
"          S.C   ",
"                ",
"                ",
"                "
"""

editor.registerImage(1000, xpmbox)

```

Cheers.

**Comment by donho** [comment]
If the keyword is not function (fx), then it"s normal keyword (kw).
If you make a `kw` with the same style & color of `fx`, why not?

**Comment by EuropeanDeveloper** [comment]
@donho: Can't we use the box icon for keywords as @vinsworldcom proposed?

**Comment by donho** [comment]
@vinsworldcom @EuropeanDeveloper 

The icon fx was added for the purpose of distinguishing the languages keyword entries from the word entries. So it's enough IMO that 1 icon for both kinds of keywords. But if we want to add one more icon for telling "normal keyword" from "function keyword", I prefer to have the same colour & style, for the following reasons:
1. It might be easier for updating Scintilla - The dark mode of auto-completion box in Scintilla may just inverse the xpm image's colour, that would be more harmony in black & white, then it might be not necessary to change the icons.
2. It's more coherent to me that the keywords from the same source remain the same colour & style.
3. Auto-completion xml files in lot of languages provided by Notepad++ have no distinguish between  "normal keyword" and "function keyword", so I prefer to using an icon as neuter as possible. 

After all, you can suggest the other symbols to stand for "normal keyword" with the constraint. It will be accepted if it's meaningful and readable.

**Comment by vinsworldcom** [comment]
@donho understood.

@EuropeanDeveloper 

dropping the "w" from "kw" and just using a script "k" seems to work a little better.  Visually, it's hardly differentiated due to point 2 above:

![image](https://user-images.githubusercontent.com/9657169/157120979-d5c1f12d-257c-47ae-87ca-2d2033295bc9.png)


Cheers

**Comment by donho** [comment]
@vinsworldcom 
> can we look forward to a Scintilla 5+ upgrade soon? :-) 

Yes, once v8.3.x is stable enough. I think next release v8.3.3 will be stable, so I will work on the Scintilla 5+ updating.

> dropping the "w" from "kw" and just using a script "k" seems to work a little better. Visually, it's hardly differentiated due to point 2 above:

This `k` looks like `f`...
"kw" and "k" are 2 of possibilities. Could we find the other possibilities?

**Comment by EuropeanDeveloper** [comment]
@vinsworldcom @donho

I agree that "k" icon looks like "f", it is quite hard to distinguish them.

If we want to use the same icon for "normal" keywords and functions, I think the best approach is to use box icon. What do you think about this?

**Comment by vinsworldcom** [comment]
> I agree that "k" icon looks like "f", it is quite hard to distinguish them.

@donho @EuropeanDeveloper , maybe I was being to literal on 2 and 3 with "style" using a letter.  How about an icon - like the box, but not purple colored.  How about a black key for "keyword":

![image](https://user-images.githubusercontent.com/9657169/157536221-772c029d-2370-4109-b698-0e002db4a4db.png)

Same "style/color" base black with transparent (color = None) background and yet much more easily distinguished.

PNG:
![key](https://user-images.githubusercontent.com/9657169/157536370-8bb73063-97d3-4ec7-9702-f95c3b8ff7f5.png)


XPM:
```
const char* xpmkw[] = {
    /* columns rows colors chars-per-pixel */
    "16 16 24 1 ",
    "5 c None",
    "  c #000000",
    ". c #030303",
    "X c #101010",
    "o c #181818",
    "O c #202020",
    "+ c #282828",
    "@ c #222222",
    "# c #252525",
    "$ c #484848",
    "% c #585858",
    "& c #606060",
    "* c #474747",
    "= c #505050",
    "- c #565656",
    "; c #9F9F9F",
    ": c #A7A7A7",
    "> c #AFAFAF",
    ", c #757575",
    "< c #818181",
    "1 c #D7D7D7",
    "2 c #DFDFDF",
    "3 c #EFEFEF",
    "4 c #979797",
    /* pixels */
    "5555555555555555",
    "5555555555555555",
    "5555555555555555",
    "5555555555555555",
    "5:+ @>5555555555",
    ";     -,,,,,,,55",
    "o+O           =5",
    ".42            <",
    ".-*     X.=.%O#5",
    "&     #=3<5<5235",
    "3$   $4555555555",
    "551,255555555555",
    "5555555555555555",
    "5555555555555555",
    "5555555555555555",
    "5555555555555555"
};
```

Cheers.

**Comment by donho** [comment]
![image](https://user-images.githubusercontent.com/90293/157588453-e5276d80-f790-45bf-bbb2-5f950e9a97d5.png)

How about a cube like it?

**Comment by vinsworldcom** [comment]
@donho @EuropeanDeveloper how about:

![image](https://user-images.githubusercontent.com/9657169/157656411-60770fad-bdfc-42b7-8afa-80badc28b453.png)

I like it.

PNG:
![box](https://user-images.githubusercontent.com/9657169/157656459-78239496-ec93-4e65-9a89-bd604fcbad12.png)


XPM:
```
const char* xpmkw[] = {
    /* columns rows colors chars-per-pixel */
    "16 16 36 1 ",
    "u c None",
    "  c #000000",
    ". c #030303",
    "X c #101010",
    "o c #181818",
    "O c #202020",
    "+ c #282828",
    "@ c #191919",
    "# c #222222",
    "$ c #252525",
    "% c #484848",
    "& c #505050",
    "* c #606060",
    "= c #444444",
    "- c #474747",
    "; c #505050",
    ": c #535353",
    "> c #565656",
    ", c #979797",
    "< c #9A9A9A",
    "1 c #9F9F9F",
    "2 c #A7A7A7",
    "3 c #AFAFAF",
    "4 c #B7B7B7",
    "5 c #757575",
    "6 c #767676",
    "7 c #787878",
    "8 c #797979",
    "9 c #818181",
    "0 c #D0D0D0",
    "q c #828282",
    "w c #D7D7D7",
    "e c #DFDFDF",
    "r c #E7E7E7",
    "t c #EFEFEF",
    "y c #979797",
    /* pixels */
    "uuuuuuuuuuuuuuuu",
    "uuuuuuuuruuuuuuu",
    "uuuy4;$  *euuuuu",
    "u4@ $-4t6;X*euuu",
    "u1oX>uuu4u5+ 1uu",
    "u1*w%O2:%XO*&;uu",
    "u1*uu4 =,ruu1;uu",
    "u1*uuu uquuu1;uu",
    "u1*uuu u9uuu1;uu",
    "u1*uuu u4uuu1;uu",
    "u1*uww e8qyu1;uu",
    "u3o<uu uuu991;uu",
    "uu7#%w uu4-#.1uu",
    "uuuu,o $.%:7uuuu",
    "uuuuut,7uuuuuuuu",
    "uuuuuuuuuuuuuuuu"
};
```

Cheers.

**Comment by donho** [comment]
@vinsworldcom 
Sorry for the request of modification again.
With the small icon as it, maybe it's better to remove the transparent effect, like this:
![image](https://user-images.githubusercontent.com/90293/157687904-32fdd534-f3b4-438b-aa0b-05063bbf8bad.png)

And also please post one more screenshot under another language without distinguishing normal / function keywords (like Java), so we have a vision more general, not only in c/c++

**Comment by donho** [comment]
@vinsworldcom 
It looks nicer :) thank you.
What do you think @EuropeanDeveloper  ?

**Comment by EuropeanDeveloper** [comment]
I love it! Good job @vinsworldcom 👍.

**Comment by vinsworldcom** [comment]
@donho should I open a new pull request, or just push to the existing "rejected" pull request and you can re-accept it if you still want to go this way?

Happy to do either.

Cheers.

**Comment by donho** [comment]
OK for pushing to the existing "rejected" pull request
