### ISSUE TITLE
Autocomplete options cannot be selected with the enter key

### ISSUE THREAD

**Issue by andressocialsnack** [notepad-plus-plus/notepad-plus-plus#11328]
### Description of the Issue

Autocomplete options cannot be selected with the enter key
### Steps to Reproduce the Issue

1. type part of a word and wait for the autocomplete options window to appear
2. navigate to the correct option with arrow keys
3. press enter

### Expected Behavior

The chosen option should replace the word we are typing.
### Actual Behavior

But instead, said word is incomplete and the cursor appears on the next line.
### Debug Information

Notepad++ v8.2.1   (64-bit)
Build time : Jan 19 2022 - 18:43:05
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : "C:\wamp64\www\audifarm\desarrollo\config\config.php"
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 10 Home Single Language (64-bit) 
OS Version : 2009
OS Build : 19043.1526
Current ANSI codepage : 1252
Plugins : mimeTools.dll NppConverter.dll NppExport.dll

**Comment by vinsworldcom** [comment]
@andressocialsnack please take the time to search for the "issue" before you post as:

1) there is no issue
2) this has been asked and answered many time
3) this was actually a "bug fix"

Please open your menu Settings => Preferences... => Auto-Completion and tick the box for "ENTER"

![image](https://user-images.githubusercontent.com/9657169/156465010-a5153144-aa55-476f-8512-e7fd656c0a22.png)

Cheers.

**Comment by andressocialsnack** [comment]
Thanks for answering. You're right.
