### ISSUE TITLE
Find in Projects is not available in the Search menu

### ISSUE THREAD

**Issue by alankilborn** [notepad-plus-plus/notepad-plus-plus#11324]
### Description of the Issue
_Find in Projects_ is not available in the _Search_ menu; it should be.  It should also appear in the _Shortcut Mapper_ but without a default keycombo assigned.

### Steps to Reproduce the Issue

1. Drop _Search_ menu
2. Look for _Find in Projects_

### Expected Behavior
For it to be there.

### Actual Behavior
Not there.

### Debug Information
Notepad++ v8.2.1   (64-bit)
Build time : Jan 19 2022 - 18:43:05
Path : C:\...\Releases\npp.8.2.1\npp.8.2.1.portable.x64\notepad++.exe
Command Line : -titleAdd="8.2.1 64-bit" -multiInst "C:\...\Releases\npp.8.2.1\npp.8.2.1.portable.x64\license.txt"
Admin mode : OFF
Local Conf mode : ON
Cloud Config : OFF
OS Name : Windows 10 Enterprise (64-bit) 
OS Version : 2009
OS Build : 19042.1466
Current ANSI codepage : 1252
Plugins : mimeTools.dll NppConverter.dll NppExport.dll PythonScript.dll

**Comment by donho** [comment]
Different from the other find subjects- "Find in Projects" needs the  at least 1 project panel opened to search in the project(s).
So it can only triggered via context menu of project panel.

**Comment by alankilborn** [comment]
>So it can only triggered via context menu of project panel.

I have literally never used it that way.
I have open the _Find_ window on a different tab and then I click into the _Find in Projects_ tab.
This 2-step is annoying.
If it were a first-class menu item I could assign my own keycombo to it and move there directly.
