### ISSUE TITLE
notepad-plus-plus is not a free software

### ISSUE THREAD

**Issue by gsw945** [notepad-plus-plus/notepad-plus-plus#11329]
### Steps to Reproduce the Issue

1. visit https://notepad-plus-plus.org/news/ in web browser

**Comment by gsw945** [comment]
Why boycotting Beijing 2022?
---
**Beijing 2022** is prefect 👍 , and [Bing Dwen Dwen](https://en.wikipedia.org/wiki/Bing_Dwen_Dwen_and_Shuey_Rhon_Rhon) is lovely 👀 .

**Comment by thomassmith311** [comment]
Using Notepad++ no more means supporting Don's political positions than being a U.S. citizen means supporting the political positions of whatever random party happens to be in power. Don already stated his reasons for boycotting Beijing 2022. Just as you can choose to leave your country if you don't like the present politics, you can choose to not use Notepad++.

**Comment by gsw945** [comment]
I have refused to use notepad++ for several years.
Subjectively speaking, the United States slandered China, North Korea, Russia and other countries, and notepad++ followed suit against China, then notepad++ is an accomplice of fascism.

**Comment by Yharimium** [comment]
The first step to turn Taiwan into "Ukraine" has been extremely successful. Today, Taiwan's open-source software announced a break with Chinese Mainland, and tomorrow it will be industrial and agricultural products. People on both sides of a strait fall into a cycle of discrimination against each other. Taking the conflict between Russia and Ukraine as a reference, one day, Taiwan leaders such as Tsai will become the trigger for war, and Chinese Mainland and Taiwan Island will shoot missiles at each other like Russia and Ukraine. Some people are willing to be clowns and fantasize that the real invaders can save the world they think is in deep water, some innocent civilians are blown to pieces, while a "certain country" will be great again. People have never learned anything from history, even the history at hand.
