### ISSUE TITLE
Default Directory does not work

### ISSUE THREAD

**Issue by K2AAE** [notepad-plus-plus/notepad-plus-plus#11326]
Set the Default Directory to 'last used directory' then exit, when you open NP++ again then click File/Open it looks in C:\Program Files\Notepad++

I expect it to look in the last directory I was working in NOT the install directory.

**Comment by dfs-** [comment]
From what you describe I don’t see a directory you were working in, so the default (= installation folder) is used.

Are there some additional steps you perform. I would suspect after changing the settings you need to open at least one file.

**Comment by Yaron10** [comment]
_Last used directory_ is only remembered for the current session.
Exiting and restating NPP, the installation folder is displayed in the Open/Save dialog.

I think @K2AAE is correct and that folder should be saved to _config.xml_.

**Comment by alankilborn** [comment]
I experimented with this on 8.2.1 and I see the behavior described above.
Then I changed it back to _Follow current document_ (the only sensical choice IMO).

However, on fresh restart of N++, I wanted to make a new PythonScript and when I went to Plugins > PythonScript > New Script and it wanted to create my new file in yesterday's "last directory".  :-(

I guess not a N++ problem per se, I just found it unusual enough to say something about it.

**Comment by Yaron10** [comment]
@alankilborn,

> I experimented with this on 8.2.1 and I see the behavior described above.

I suppose you mean "Last used directory is only remembered for the current session.".

> However, on fresh restart of N++, I wanted to make a new PythonScript and when I went to Plugins > PythonScript > New Script and it wanted to create my new file in yesterday's "last directory". :-(

I can't reproduce that.
NPP 8.3.2.
PythonScript 2.0.

**Comment by alankilborn** [comment]
>I suppose you mean "Last used directory is only remembered for the current session.".

Well... in my case _something_ remembered it from yesterday.  :-)
And it was totally frustrating to have to navigate all the way to my scripts folder in order to create a new script. :-)

>NPP 8.3.2.

I am not brave enough to go there yet.  To 8.3.* I mean.

>PythonScript 2.0.

So far I can't go there either, as my 1.5.4 sophisticated setup isn't quite working under 2.0. :-(

**Comment by Yaron10** [comment]
> Well... in my case something remembered it from yesterday. :-)

It's certainly not in config.xml.
Interesting.

> And it was totally frustrating to have to navigate all the way to my scripts folder in order to create a new script.

But in NPP Open/Save it was NOT remembered after restart, correct?

> I am not brave enough to go there yet. To 8.3.* I mean.

If you don't take the plunge, who would? :)

**Comment by Yaron10** [comment]
@alankilborn,

Completely off-topic.
https://github.com/notepad-plus-plus/notepad-plus-plus/blob/c19033c91711bc5c35bc63b804c5d31756ee58a4/PowerEditor/src/NppCommands.cpp#L1347

Can you think of a reason it's `MAX_PATH` instead of `FINDREPLACE_MAXLENGTH`?

**Comment by alankilborn** [comment]
>But in NPP Open/Save it was NOT remembered after restart, correct?

Right.  My situation is off-topic and not worth pursuing; I just wanted to mention it.

>Can you think of a reason it's MAX_PATH instead of FINDREPLACE_MAXLENGTH?

Nope.  Seems like you could create some STR a bug and open an issue.

**Comment by Yaron10** [comment]
@alankilborn,

Thank you. :+1:

**Comment by K2AAE** [comment]
I gave up on Last and Follow, set directory to a folder in Home, shut NPP down and on restart File Save opened in that Home directory instead of the install location. Note:  %HOMEPATH% would be the place to open at if nothing is set, the install directory should be write proof by normal users.

**Comment by Yaron10** [comment]
@molsonkiko,

I've never used "Last Used Directory" in real-life.
But there are quite a few opened issues about it.

https://github.com/notepad-plus-plus/notepad-plus-plus/issues/4961.
https://github.com/notepad-plus-plus/notepad-plus-plus/issues/10901.
https://github.com/notepad-plus-plus/notepad-plus-plus/issues/4119.

What do you think?

**Comment by Yaron10** [comment]
@molsonkiko,

👍 
That would be great!

I really believe that a developer like yourself would be an asset to any project. :)
Thank you for your work.

If I can't try your PR tonight, I'll do it tomorrow.
