### ISSUE TITLE
Please sort listing of languages in Style Configurator in alphabetic order

### ISSUE THREAD

**Issue by labeldevops** [notepad-plus-plus/notepad-plus-plus#11337]
While I am at it: another thing that you could change probably with one line: 

please sort listing of languages in Style Configurator in alphabetic order.

 I do not get why you do not changed that already - did you ever use it? Did you ever scroll the language list with full extra attention because it is not sorted in alphabetic order and you were looking for one language that you can not find on the list for the third time?

ULTRA annoying! Please sort it, THANKS!

**Comment by Yaron10** [comment]
@labeldevops,

You can sort the languages in stylers.xml, and that should be the order in _Style Configurator_.

**Comment by vinsworldcom** [comment]
You can just type the letters of the language and it should bring you there.

**Comment by CennoxX** [comment]
This is already sorted in the default themes and should also be sorted in other themes 👍
To sort this, take every Theme in https://github.com/notepad-plus-plus/notepad-plus-plus/tree/master/PowerEditor/installer/themes and sort the LexerType-Nodes by desc-property.
