### ISSUE TITLE
notepad++ 8.3.2 crashes on Windows 7

### ISSUE THREAD

**Issue by gh-user-2022** [notepad-plus-plus/notepad-plus-plus#11349]
### Description of the Issue
notepad++ 8.3.2 crashes on Windows 7 (Version 6.1.7601)
notepad++ 8.2.1 works on Windows 7 (Version 6.1.7601)

### Expected Behavior
To not crash.

### Actual Behavior
Crashes on startup.

**Comment by donho** [comment]
@gh-user-2022 
Could you provide the list of plugins  you use please?

**Comment by thomassmith311** [comment]
@gh-user-2022 

FYI that is done by going to ? > Debug Info and hitting Copy debug info into keyboard.

![image](https://user-images.githubusercontent.com/19561856/157097954-cdc5f1ab-5194-4c6e-bd5a-7ce98b8b6ba9.png)
![image](https://user-images.githubusercontent.com/19561856/157098101-a079aef1-e475-4d2b-955a-7dc6a0490757.png)

**Comment by gh-user-2022** [comment]
The issue no longer reproduced on `notepad++ 8.3.2` after I cleaned up the installation directory before re-installing.
So this is not related to OS version.
