### ISSUE TITLE
Auto Complete by Enter

### ISSUE THREAD

**Issue by amirhosseindesigner** [notepad-plus-plus/notepad-plus-plus#11347]
there is a problem that is where we write something and i use "Enter" key to select suggestion auto complete it will go on next line!

**Comment by dfs-** [comment]
Check the settings. There is an option to re-enable Enter for completion.

**Comment by alankilborn** [comment]
![image](https://user-images.githubusercontent.com/77065706/156938432-c16f62cb-8e98-413e-8385-64e5613e625f.png)

**Comment by amirhosseindesigner** [comment]
Thanks
