### ISSUE TITLE
In Column Mode paste Text overwrites all except the first Line

### ISSUE THREAD

**Issue by LeChatNoir666** [notepad-plus-plus/notepad-plus-plus#11346]
### Description of the Issue

I have a numbered List and want to paste Lines of Text behind this List in Column Mode.
But this works only on the first Line and on all other Lines my numbered List gets overwritten by the pasted Text,

### Steps to Reproduce the Issue

1.  Make a List like:
01 - 
02 -
03 - 
2. Copy some text you want to add after the -  
3. Switch to Column Mode 
4. Paste the copied Text
5. Check, that only the first Line show like you want it but the rest will get overwritten

### Expected Behavior

Keeping the numbered List and add the Text I paste to the List
### Actual Behavior

Only the first Line keeps the 01 - and all other is overwritten by the pasted Text.

### Debug Information
Notepad++ v8.3.2   (64-bit)
Build time : Feb 27 2022 - 03:35:46
Path : P:\!!PORTABLE!!\PortableApps.com\PortableApps\Notepad++Portable\App\Notepad++64\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : ON
Cloud Config : P:\!!PORTABLE!!\PortableApps.com\PortableApps\Notepad++Portable\Data\Config
OS Name : Windows 10 Pro (64-bit) 
OS Version : 2009
OS Build : 19042.985
Current ANSI codepage : 1252
Plugins : BookmarksDook.dll CodeAlignmentNpp.dll ColumnTools.dll Comment Wrap.dll DSpellCheck.dll Explorer.dll HTMLTag.dll JSFunctionViewer.dll JsMapParser.NppPlugin.dll JSMinNPP.dll LanguageHelp.dll Linefilter3.dll LuaScript.dll mimeTools.dll NotepadStarterPlugin.dll npp.connections.dll NppConverter.dll NppDocShare.dll NppExec.dll NppExport.dll NppFavorites.dll NppFTP.dll NPPJSONViewer.dll NppPluginOpenHost.dll PlanetCNCNpp64.dll

**Comment by thomassmith311** [comment]
Hi, Could you clarify what is meant by column mode?

**Comment by alankilborn** [comment]
@LeChatNoir666 is doing this:

Create this text:

	01 - 
	02 - 
	03 - 

leaving a space after each `-`

Create this text somewhere else:

	cat
	dog
	boy

Select, like this, in non-column block mode:

![image](https://user-images.githubusercontent.com/77065706/157332596-2df76112-755e-4be4-9a96-667fdfaaf05f.png)

Press Ctrl+c.

Move caret here:

![image](https://user-images.githubusercontent.com/77065706/157332708-889362cd-5053-47d1-9dcb-94ec085eb51a.png)

Press Ctrl+v.  Observe:

![image](https://user-images.githubusercontent.com/77065706/157332788-2c00bc88-ce78-4153-a989-49cebb6b42fe.png)

OP expects:

	01 - cat
	02 - dog
	03 - boy

**Comment by alankilborn** [comment]
To get the desired outcome, the correct sequence of actions, after my step 2 above:

3. Select, like this in column block mode (using Shift+Alt+arrows):

![image](https://user-images.githubusercontent.com/77065706/157333354-1e9f1d9e-d938-4f4b-94f8-bec4eb70286e.png)

4. As my step 4 above

5. As my step 5 above

6. As my step 6 above, observe:

![image](https://user-images.githubusercontent.com/77065706/157333657-f2910ca5-66a7-4b29-a3e1-b399357a066d.png)

**Comment by alankilborn** [comment]
It matters that the _copy_ is of a column block, not being in column-block mode when the paste is done.

**Comment by alankilborn** [comment]
Recommend CLOSURE of this item.
