### ISSUE TITLE
WEBSITE: downloads pages for ancient v6.x versions point to v7.x folders

### ISSUE THREAD

**Issue by pryrt** [notepad-plus-plus/notepad-plus-plus#11344]
@donho,

Some of the download links on the https://notepad-plus-plus.org/downloads/XXXXX pages are wrong.

If you go to any of the 6.x downloads pages there, they each have a link into the 7.x folder:
* https://notepad-plus-plus.org/downloads/v6.2.3/ : main DOWNLOAD image URL points to https://notepad-plus-plus.org/repository/7.x/6.2.3/npp.6.2.3.Installer.exe
* https://notepad-plus-plus.org/downloads/v6.6.4/ : main DOWNLOAD image URL points to https://notepad-plus-plus.org/repository/7.x/6.6.4/npp.6.6.4.Installer.exe
* https://notepad-plus-plus.org/downloads/v6.6.6/ : main DOWNLOAD image URL points to https://notepad-plus-plus.org/repository/7.x/6.6.6/npp.6.6.6.Installer.exe
* https://notepad-plus-plus.org/downloads/v6.7.4/ : main DOWNLOAD image URL points to https://notepad-plus-plus.org/repository/7.x/6.7.4/npp.6.7.4.Installer.exe
* https://notepad-plus-plus.org/downloads/v6.8.7/ : main DOWNLOAD image URL points to https://notepad-plus-plus.org/repository/7.x/6.8.7/npp.6.8.7.Installer.exe
* https://notepad-plus-plus.org/downloads/v6.9/ : main DOWNLOAD image URL points to https://notepad-plus-plus.org/repository/7.x/6.9/npp.6.9.Installer.exe

Each of those URLs points to the 7.x folder, when it should point to the 6.x folder.

We get someone new complaining about those links every few months in the forum.  If the links could be fixed, that would be great.

Example screenshot and View Source from [v6.9 downloads page](https://notepad-plus-plus.org/downloads/v6.9/):

![image](https://user-images.githubusercontent.com/17455758/156900032-1d7a84c4-6d2d-44e6-bcca-4a8894c1f012.png)

```
<p>Release Date: 2016-02-22</p>

<h3 id="download-32-bit-x86">Download 32-bit x86</h3>

<p><a href="/repository/7.x/6.9/npp.6.9.Installer.exe"><img src="/downloads/images/folder_download_4.png"></a></p>
                        ^^^
                        WRONG

```
The same thing needs to be fixed on all the pages in the bullet list above.

**Comment by donho** [comment]
@pryrt 
Fixed.
Please let me know if there are other issues found in Notepad++ website.
