### ISSUE TITLE
Show word count on status bar

### ISSUE THREAD

**Issue by abdekker** [notepad-plus-plus/notepad-plus-plus#1136]
Using v6.3 here. Currently the status bar has a panel that says "length : 31003   lines : 507" (in my example). The number of bytes is interesting but in some circumstances not of interest, whereas the number of words might be. My suggestion is to be able to toggle between "file size" and "word count" in the status bar. The status bar would then appear as:
- "length : 31003   lines : 507" [if File size (default) is selected]
- "words: 4943  lines: 507" [if Word count is selected]

I realise there is the menu option View > Summary... gives some of this information, but that's a bit buried away and requires several clicks.

Great job on notepad++, love it!

**Comment by denis-bogdanas** [comment]
I subscribe to this request.

**Comment by joergneulist** [comment]
You can also access the Summary by double clicking on the status bar. Still, I would also love to see the word count without interacting!

**Comment by abdekker** [comment]
@joergneulist: Thanks! That is new to me. The original feature request is still valid, but this is useful (hidden) feature.

**Comment by mrspaceman** [comment]
This would be a great feature for me.

**Comment by jamesford42** [comment]
+1

**Comment by vbasarkar** [comment]
+1

**Comment by stoptheinsanity** [comment]
I use the double click method, but for me, if I could just glance at the status bars and clearly see the word count it wouldn't break the flow of writing.

**Comment by laocoi** [comment]
Vote for this feature

**Comment by Aenadon** [comment]
Absolutely! Please do this!

**Comment by bitseeker** [comment]
+1 from me. Would be very progressive in workflow.

**Comment by igavronski** [comment]
+1 -- or even better, a customizable status bar would be great.

**Comment by sasumner** [comment]
Possibly relevant:  https://notepad-plus-plus.org/community/topic/14889/footer-sel-to-include-word-count

**Comment by a4jp-com** [comment]
Can I request the number of words selected get counted and displayed automatically in the bottom info bar? Everything else I wanted has been fixed and this program is wonderful. This would be very useful for students submitting homework that need to be certain lengths. As well as university students and SEO (Search Engine Optimization) workers like me that need to also find text throughout multiple files.

Like this: selected count/total count

**Comment by sasumner** [comment]
Maybe I'm off base here but perhaps an idea on why this hasn't been implemented is that it could be "expensive" to calculate the number of words in a really large document.  The standard things currently shown on the status bar are all direct Scintilla calls to data items that are already maintained.

**Comment by a4jp-com** [comment]
Word and Open Office can easily do this. It can't be that taxing on a modern day PC to do a word count. The total count is already built in and counting selected words in text when being selected isn't millions of words. It's just the words selected.

**Comment by a4jp-com** [comment]
Where is the code for the summary word count and the toolbar currently?

**Comment by sasumner** [comment]
@a4jp-com It is not advisable to compare Word or Open Office to Notepad++; apples and oranges.  As a raw assignment (won't use the word "task" here), it's not "taxing on a modern day PC"--however it would have to be "architected" in.  THAT part may or may not be "easy".  It is certainly easy to say "just (count) the words".

**Comment by sasumner** [comment]
@a4jp-com 
>Where is the code for the summary word count and the toolbar currently?
If you are a programmer it might occur to you to search the project for a string such as:
`Characters (without`

**Comment by manjukefernando** [comment]
It would be great if the word count can be shown on the status bar

**Comment by ulrich-schroeders** [comment]
+1

**Comment by mdingemanse** [comment]
+1

Love Notepad++ and use it everyday, but it always bugs me to not have this simple feature

**Comment by a4jp-com** [comment]
It can't be too difficult to implement something like this. Anyone know a programmer that can help?

**Comment by sasumner** [comment]
So maybe the discussion of this issue is getting a little too bogged down in my early comment about it being slow.  It is all a matter of scale.  If you edit mainly small files, having something constantly counting all the words and presenting that on the status bar is no big deal.  However, some people use Notepad++ to edit huge files (the largest it can handle), and in those cases having something constantly doing an action like this could be prohibitive.  So these users would start crying "Why did N++ get so slow?!".  I'm just saying this is a potential concern, not that it surely would happen.  It all gets back to architecture and design concerns, rather than just saying "this surely must be easy to implement!".  It is much better to be an on-demand feature that you summon up when needed, rather than always happening.  So we already have it in View->Summary; it just needs to be implemented for a selection when a selection is active when invoked.

**Comment by suk79sin** [comment]
+1

**Comment by donho** [comment]
Double click on the "length/lines" zone of status bar will launch Summary.
There'll be no word count on status bar.

**Comment by heresjolly** [comment]
I copy and pasted the entire Bee Movie script 105 times. It took approximately 3 seconds for the summary box to open on the resulting document as shown here: ![image](https://user-images.githubusercontent.com/69891330/90602950-820fbe00-e1c8-11ea-88fa-fdc934cdf494.png)

This is a very long time yes, however the summary opened instantaneously when the document was only a single instance of the script as shown here: ![image](https://user-images.githubusercontent.com/69891330/90603126-cb600d80-e1c8-11ea-8b41-89a84e03a523.png)

My take away is that the potential CPU lag from tracking word counts on large documents in real time is a potential concern, however I have some recommendations.

1. The word count doesn't haven't to be up to the millisecond. The consensus request that I've inferred seems to simply pertain to work flow and creative flow. If the same word counter used in summary were set to automatically kick in/refresh when the user stops interacting with the text, it would still serve the requested function.

2. A maximum count for real time could also be implemented. The entire Lord of the Rings trilogy only contains 576,459 words and Stephen King's Under the Dome (a notoriously long read) only contains 299,280. Most people aren't going to require more than 200,000-300,000 even if they're writing exorbitantly long novels. Once the counter reaches a certain length, or if it's taking over a designated time to analyze, the function self disables, or switches to a longer sliding delay before refreshing. A color system can be utilized to designate when the count is up to date, for example: green =  up to date, but then switches to red (out of date) once the user interacts with the text.

**Comment by abdekker** [comment]
+1 Nicely described feature, heresjolly

**Comment by sasumner** [comment]
>There'll be no word count on status bar.

**Comment by KasunL** [comment]
Yes, it'll be nice if I could switch between Length / Word count on status bar. +1

**Comment by sasumner** [comment]
>There'll be no word count on status bar.

**Comment by a4jp-com** [comment]
Can you add the word count as an option in the right click menu (the summary)? I would like to be able to select text and then right click bringing up and option to show details.

**Comment by sasumner** [comment]
@a4jp-com said:

>Can you add the word count as an option in the right click menu (+ summary)? I would like to be able to select text and then right click...

I attempted to add a change to the code for your need, but it was rejected.  Thus I would suggest creating a macro for it, following these steps:

1. Select some text to count the words in
2. Open the _Replace_ window by pressing Ctrl+h
3. Set up the _Replace_ window as follows:
![image](https://user-images.githubusercontent.com/30118311/92325520-a5849680-f019-11ea-9a8c-3531723775be.png)
4. Start macro recording via button on toolbar
5. Press the _Replace All_ button
6. End macro recording via button on toolbar (then suggest testing the macro to make sure it is working!)
7. Save and name the created macro (suggestion: `Word count in selection` )
8. Add your macro to the N++ right-click context menu (this Community [POSTING](https://community.notepad-plus-plus.org/post/57383) may be helpful), but maybe a simpler way is just adding this line to `contextMenu.xml`:
```
<Item MenuEntryName="Macro" MenuItemName="Word count in selection"/>
```

When you run your macro, you will see the results here (example for 5 counted words in some selected text):
![image](https://user-images.githubusercontent.com/30118311/92325683-84707580-f01a-11ea-93bd-4ed4f7958f98.png)

Some limitations with this approach:

* Requires that you have the _Replace_ window open when you wish to get a count of words in a selection
* Modifies your document (because it is doing a replacement operation)

If these limitations bother you, you can substitute the following, for the similarly numbered steps above:

2a. Open the _Find_ window by pressing Ctrl+f
3a. Set up the _Find_ window as follows:
![image](https://user-images.githubusercontent.com/30118311/92325819-7f5ff600-f01b-11ea-8ce3-cf811d82facb.png)
5a. Press the _Find All in Current Document_ button

When you run the "a" version of the macro, you will see the results here:

![image](https://user-images.githubusercontent.com/30118311/92325853-d1a11700-f01b-11ea-93b8-0dfcfb4b0593.png)

**Comment by a4jp-com** [comment]
I can't see why they would block the update unless the code was buggy. That gets around the complaints of slow counts if people have large blocks of text. Opening the file is gonna take  a long time anyway if there are millions of characters, right? I'm okay even if the useful toolbar count can't be implemented as the coding engine of this program is super slow. I just never thought a text editor would be so slow. If the code is super slow, can it be ported to a better coding system then?

Thank you so much for your try @sasumner 
Can you post the code here so we can work on it? This program is great but terrible when it comes to anything that needs a set number of words or characters. Like SEO work. Especially without a quick way of checking the numbers of words in a block of text quickly. Also checking files when they have to have paragraphs of a certain length. We just want a one or two click option if possible. @sasumner do you think your code could be made into a plugin?

**Comment by sasumner** [comment]
@a4jp-com 

I don't understand your first paragraph.  Notepad++ is know for its "speed"; recently I saw a post where someone switched from VSCode to Notepad++ because VSCode was very slow.  If N++ is slow for you, perhaps open an issue where you describe your circumstances.

>Can you post the code here so we can work on it?

What code do you mean? The macro definition from `shortcuts.xml`?

>do you think your code could be made into a plugin?

For this you mean the C++ code I did in the (rejected) PR?

**Comment by sasumner** [comment]
Adding reject label to perhaps discourage people from re-requesting this feature.

**Comment by igavronski** [comment]
So... I need this feature as well and switched to vim.
Good luck with N++, @sasumner

**Comment by a4jp-com** [comment]
@igavronski what is Vim? I'm happy to switch apps if a proper word count isn't being added to Notepad Plus Plus.

I was told Notepad Plus Plus is slow and that is why they didn't want to add the count to the toolbar as an option or feature. I can't see why having it as an option that can be turned on or a plugin would be bad though. 

@sasumner not the macro but the C++ code you made. I'm sure a it will help lots of people if it is available and working. 
I'm happy to try another apps if something out there already does this though. I like Notepad Plus Plus but like Blender prefer stuff that can be made user friendly with components that make work quicker.

**Comment by sasumner** [comment]
IMO something like this not being a native feature is an insane reason to switch away from Notepad++, when there are so many ways to "make it happen".

@a4jp-com said:

>I was told Notepad Plus Plus is slow

Do you believe everything you hear, or do you make judgments for yourself?

> not the macro but the C++ code you made
The C++ code I did is in PR #8791.

I'll work up yet another way to do this, using the Pythonscript plugin....

**Comment by sasumner** [comment]
I said:

>I'll work up yet another way to do this, using the Pythonscript plugin....

Oh wait, I already did that, over 2 years ago; see [THIS](https://github.com/notepad-plus-plus/notepad-plus-plus/issues/1136#issuecomment-361618742) from earlier in this thread.

**Comment by mdingemanse** [comment]
That Pythonscript plugin looks wonderful and just what I was looking for @sasumner. Thanks for your patient support here as people struggle to understand why this couldn't be a feature (conditional on filesize perhaps). Should the Pythonscript code still work? I've added it as a script in N++ 7.9 but it doesn't seem to show up on status bar when selecting text. (A first copy-paste gave me a Unicode error in the Python console, but after fixing the apostrophes it seems to run, yet displays nothing.)

**Comment by sasumner** [comment]
@mdingemanse 

The way that script was posted was poor, but it should still work once format and indentation problems are solved.
Here's a more properly formatted version of it that I tested:

```
# -*- coding: utf-8 -*-

from Npp import editor, notepad, SCINTILLANOTIFICATION
import re

def WCISAISB__callback_sci_UPDATEUI(args):
    if args['updated'] & UPDATE.SELECTION:
        text = editor.getSelText()
        notepad.setStatusBar(STATUSBARSECTION.DOCTYPE, 'Word count in selection: {}'.format(len(re.findall(r'\w+', text))) if len(text) > 0 else ' ')

editor.callback(WCISAISB__callback_sci_UPDATEUI, [SCINTILLANOTIFICATION.UPDATEUI])
```

**Comment by a4jp-com** [comment]
@sasumner thanks for making that.

**Comment by molsonkiko** [comment]
Thought I'd introduce a new take on this, one that gives both the wordcount in the selection and the wordcount in the entire document. As an added bonus, it only recomputes the count when a new buffer is activated or the user actually modifies the file, which should improve performance.

![image](https://user-images.githubusercontent.com/46202915/234086826-388b4a1b-d528-4698-83a7-d9ba755c6d82.png)

```
from Npp import editor, notepad, STATUSBARSECTION
from Npp import SCINTILLANOTIFICATION as SCN
from Npp import NOTIFICATION as NPPN

wordcount = 0
selected_wordcount = 0

def on_match(m):
    global wordcount
    wordcount += 1
    
def on_selection_match(m):
    global selected_wordcount
    selected_wordcount += 1

def get_wordcount(args):
    global wordcount
    if args.get('modificationType') or args.get('bufferID'):
        # doc was modified or new doc was opened; refresh count
        wordcount = 0
        editor.research('\w+', on_match)
    # add wordcount to status bar along with other info
    doclen = editor.getLength()
    doc_bar_desc = 'length: %i  lines: %i  words: %i' % (
        doclen,
        editor.getLineCount(),
        wordcount
    )
    notepad.setStatusBar(STATUSBARSECTION.DOCSIZE, doc_bar_desc)
    sel_start, sel_end = editor.getUserCharSelection()
    curloc = editor.getCurrentPos()
    curline = editor.lineFromPosition(curloc)
    curcol = editor.getColumn(curloc)
    sel_size = sel_end - sel_start
    if 0 < sel_size < doclen:
        # get wordcount in selection, add to status bar
        global selected_wordcount
        selected_wordcount = 0
        editor.research('\w+', on_selection_match, 0, sel_start, sel_end)
        start_line, end_line = editor.getUserLineSelection()
        selection_desc = 'Ln : %i  Col : %i  Sel : %i  Lines : %i  Words : %i' % (
            curline,
            curcol,
            sel_size,
            end_line - start_line + 1,
            selected_wordcount
        )
        notepad.setStatusBar(STATUSBARSECTION.CURPOS, selection_desc)

try:
    MODULE_ALREADY_INITIALIZED
except:
    MODULE_ALREADY_INITIALIZED = True
    try:
        CALLBACK_ALREADY_ADDED
    except:
        get_wordcount({"modificationType": 1})
        editor.callback(get_wordcount, [SCN.UPDATEUI, SCN.MODIFIED])
        notepad.callback(get_wordcount, [NPPN.BUFFERACTIVATED])
        CALLBACK_ALREADY_ADDED = True
```

**Comment by antanij** [comment]
Strong +1 for this much-needed feature!!

**Comment by alankilborn** [comment]
@antanji

It isn't going to become a feature in the standard product (or it would have been done some time ago).  Go with one of the scripting options above and have your desired functionality TODAY.

**Comment by a4jp-com** [comment]
> Strong +1 for this much-needed feature!! Selecting part of the text and being able to see word count for just the selected text would be a dream come true!

Yeah. It would be nice if it was built in and had an option so it could be turned off for people that don't wanna count characters. I think the version I have now is working from the code I added so I think I just forgot about it but it's a super useful feature.

**Comment by a4jp-com** [comment]
@xomx Do you want it to count special characters? Maybe a double click could open a window giving an option for the type of characters we want to count.

**Comment by alankilborn** [comment]
> Do you want it to count special characters? Maybe a double click could open a window giving an option for the type of characters we want to count.

Given that word-count on the status bar is not likely to be implemented...
This comment might serve better as a feature request for the _View_ menu's _Summary_ command.

**Comment by RamouzK** [comment]
We need word count on the status bar and also word count when selecting text (out of total word count). The info at the bottom is semi-helpful and confusing. We need different wording there and we need to be able to customise what is shown so that we can add word count and characters.

**Comment by xomx** [comment]
> [@xomx](https://github.com/xomx) Do you want it to count special characters?

> also word count when selecting text

Now it's possible via Ctrl+Alt+I (menu > Search > Incremental Search):

<img width="1014" height="159" alt="Image" src="https://github.com/user-attachments/assets/0fc5b35b-4320-4976-aba9-fd86f2a4f570" />

---

> We need word count on the status bar

Current status of this feature is REJECTED (for performance reasons).
