### ISSUE TITLE
Perl langs.model.xml does not include warnings keyword

### ISSUE THREAD

**Issue by vinsworldcom** [notepad-plus-plus/notepad-plus-plus#11369]
### Description of the Issue
The 'langs.model.xml' does not include for Perl the keyword `warnings` as in:

```Perl
use warnings;
```

It does however include `strict` which is used generally in the same case and in conjunction with `warnings` to start most Perl scripts.

```Perl
#! /usr/bin/perl

use strict;
use warnings;
```

This leads to incorrect lexing:

![image](https://user-images.githubusercontent.com/9657169/157865669-27a42785-bb43-4599-be78-70e63bd2d1ea.png)

When it should be:

![image](https://user-images.githubusercontent.com/9657169/157865789-755b9dee-bb9f-488f-8d3d-447a5a3d3fe4.png)

@pryrt :  as a fellow Perl user, would you agree?

### Debug Information

Notepad++ v8.3.3   (64-bit)
Build time : Mar 11 2022 - 03:16:47
Path : C:\usr\bin\npp64\notepad++.exe
Command Line : -noPlugin
Admin mode : OFF
Local Conf mode : ON
Cloud Config : OFF
OS Name : Windows 10 Enterprise (64-bit) 
OS Version : 2009
OS Build : 19042.1526
Current ANSI codepage : 1252
Plugins : none

**Comment by pryrt** [comment]
I always found it weird that the keyword list included the `strict` but not `warnings` as well. I was just never sure whether the right choice was to include all the core [pragma modules](https://perldoc.perl.org/modules#Pragmatic-Modules), or to include none of them.  I think it's probably best to include them all if we include any.

**Comment by vinsworldcom** [comment]
> I think it's probably best to include them all if we include any.

This shows how little I know!  I only `strict` and `warnings` and on rare occasions, `diagnostics` - what else do you recommend?

Cheers.

**Comment by pryrt** [comment]
> what else do you recommend?

I actually just did another commit to the PR that includes all of the core pragmas.

**Comment by vinsworldcom** [comment]
@pryrt while we're at it, should we update 'autoCompletion\perl.xml'?  It is missing the keyword 'warnings` (but has `strict`) and so presumably all the other core pragmas may be missing and could be added.

See my [comment in the PR](https://github.com/notepad-plus-plus/notepad-plus-plus/pull/11370#issuecomment-1065182696) though, names with '::' don't seem to highlight and probably won't work as a full keyword in the 'autoCompletion\perl.xml' file either.  May just stick with the single word core pragmas?

Cheers.

**Comment by pryrt** [comment]
I wonder if adding quotes around the `::` names would work.  But if not, then just remove them.

And yes, any of those pragmas that are missing from `autoCompletion\perl.xml` should also be added.

**Comment by vinsworldcom** [comment]
> I wonder if adding quotes around the `::` names would work. But if not, then just remove them.

Quick try didn't seem to work for me.

> And yes, any of those pragmas that are missing from autoCompletion\perl.xml should also be added.

Perhaps separate PR for this?

Cheers.

**Comment by pryrt** [comment]
I was just about to say that quotes didn't help for me, either.

As for separate PR, that's up to you.  Since it's adding the same keywords to both langs.model.xml and the autoCompletion file, I think it makes sense to group them in the same PR; but that might be just me.

**Comment by pryrt** [comment]
Regarding,
> [If] so, we can still add the single words autodie and skip instead of autodie::skip together?

Since skip only has special meaning after `autodie::`, I would be reluctant to color it elsewhere.  But then again, the lexer would improperly color `use MyModule::warnings` as well, so there are always going to be instances where the lexer would get this wrong.

**Comment by vinsworldcom** [comment]
OK - so to be clear, I'll remove the pragmas with `::` from the current PR and then add the same new keywords that are left that have been added to 'langs.model.xml' to the 'autoCompletion\perl.xml' as keywords there.

Cheers.

**Comment by vinsworldcom** [comment]
> I was just about to say that quotes didn't help for me, either.

The TCL langs.model.xml does have `::` keywords and they do highlight correctly:

![image](https://user-images.githubusercontent.com/9657169/157894756-01dc2c9c-4553-4bc7-8d40-fb458935efe5.png)

so most likely a difference in Scintilla lexer that we won't be able to fix here.  No worries though.

**Comment by vinsworldcom** [comment]
> OK - so to be clear, I'll remove the pragmas with `::` from the current PR and then add the same new keywords that are left that have been added to 'langs.model.xml' to the 'autoCompletion\perl.xml' as keywords there.
> 
> Cheers.

Done!

**Comment by double-standard-you** [comment]
American Shares Truth About Joshua Wong & Hong Kong Democracy
https://www.youtube.com/watch?v=8nXz66Btfl0

American Shares Truth on Xinjiang and Tibet Controversies in China
https://www.youtube.com/watch?v=CldtoYwPtMk

Why is Ukraine the West’s Fault? Featuring John Mearsheimer
https://www.youtube.com/watch?v=JrMiSQAGOS4

Bat coronavirus found in U.S.-funded bio-lab in Ukraine: Russian Defense Ministry
https://www.youtube.com/watch?v=BCydUeHAhzQ

Ukrainians were denied US visas as White House promise help to refugees
https://www.youtube.com/watch?v=BGZhzNFmyhc

Reports of racist treatment against Africans trying to flee Ukraine
https://www.youtube.com/watch?v=JItYOW_uT8s

Fleeing African and Indian students face racism at Ukraine border
https://www.youtube.com/watch?v=ODMOzwI__zs

Canadian RCMP use horses to trample protestors
https://www.youtube.com/watch?v=Usn3CR0E1v0

A bald-faced lie from the Western media corp: Critical “Uyghur Genocide” Questions: A CBC Interview Follow-up
https://www.youtube.com/watch?v=O7IbsPFM2Xg

**Comment by double-standard-you** [comment]
> ### Description of the Issue
> The 'langs.model.xml' does not include for Perl the keyword `warnings` as in:
> 
> ```perl
> use warnings;
> ```
> 
> It does however include `strict` which is used generally in the same case and in conjunction with `warnings` to start most Perl scripts.
> 
> ```perl
> #! /usr/bin/perl
> 
> use strict;
> use warnings;
> ```
> 
> This leads to incorrect lexing:
> 
> ![image](https://user-images.githubusercontent.com/9657169/157865669-27a42785-bb43-4599-be78-70e63bd2d1ea.png)
> 
> When it should be:
> 
> ![image](https://user-images.githubusercontent.com/9657169/157865789-755b9dee-bb9f-488f-8d3d-447a5a3d3fe4.png)
> 
> @pryrt : as a fellow Perl user, would you agree?
> 
> ### Debug Information
> Notepad++ v8.3.3 (64-bit) Build time : Mar 11 2022 - 03:16:47 Path : C:\usr\bin\npp64\notepad++.exe Command Line : -noPlugin Admin mode : OFF Local Conf mode : ON Cloud Config : OFF OS Name : Windows 10 Enterprise (64-bit) OS Version : 2009 OS Build : 19042.1526 Current ANSI codepage : 1252 Plugins : none

American Shares Truth About Joshua Wong & Hong Kong Democracy
https://www.youtube.com/watch?v=8nXz66Btfl0

American Shares Truth on Xinjiang and Tibet Controversies in China
https://www.youtube.com/watch?v=CldtoYwPtMk

Why is Ukraine the West’s Fault? Featuring John Mearsheimer
https://www.youtube.com/watch?v=JrMiSQAGOS4

Bat coronavirus found in U.S.-funded bio-lab in Ukraine: Russian Defense Ministry
https://www.youtube.com/watch?v=BCydUeHAhzQ

Ukrainians were denied US visas as White House promise help to refugees
https://www.youtube.com/watch?v=BGZhzNFmyhc

Reports of racist treatment against Africans trying to flee Ukraine
https://www.youtube.com/watch?v=JItYOW_uT8s

Fleeing African and Indian students face racism at Ukraine border
https://www.youtube.com/watch?v=ODMOzwI__zs

Canadian RCMP use horses to trample protestors
https://www.youtube.com/watch?v=Usn3CR0E1v0

A bald-faced lie from the Western media corp: Critical “Uyghur Genocide” Questions: A CBC Interview Follow-up
https://www.youtube.com/watch?v=O7IbsPFM2Xg
