### ISSUE TITLE
Application does not start (severe bug)

### ISSUE THREAD

**Issue by Elmue** [notepad-plus-plus/notepad-plus-plus#11365]
I just downloaded Notepad++ 8.3.2 and installed it on my 64 bit Windows 10 build 18363.

It does not start at all.
Even when I double click the notepad++.exe nothing happens.
I tried all.
Run as administrator.
Nothing helps.
Then I installed the latest 32 bit version.
Does not work at all.
No error message.
Just the app does not start.
It does not appear in taskmanager. So it exits immediately.

I'am using Notepad++ since decades and I have never seen this!

Then I installed Notepad 8.2.1 and it works correctly.
Also Notepad 8.3.1 works correctly.

Then I installed Notepad 8.3.2 again and now it works, too!
What ???

May be something went wrong when uninstalling my previous version ?
Before I used 5.9.8 (32 bit)

Then I continued to investigate.
I installed the old version 5.9.8 (32 bit) again and then 8.3.2 (64 bit) over it.
And in deed again the new version did not start !!

There is definitely a very bad bug.

Over the already installed 8.3.2 I installed 8.3.2 again.
I did not fix the problem.

Then I installed 8.3.1 over 8.3.2 and it works
So there is definitely something broken in the **last versio**n.

I tried it 3 times.
It is always the same: 8.3.2 cannot be installed over 5.9.8

**Comment by dfs-** [comment]
Could you try renaming the directory %APPDATA%\Notepad++ to „Notepad++bak“ after updating to 8.3.2. 

There might be some incompatibility due to your very old previous installation.

**Comment by Elmue** [comment]
The old directory did not exist anymore after updating.
The installer asked me if I want to uninstall the old version first and I clicked "Yes".

And as I wrote: This happens ONLY with the last version.
So anything has definitely been broken.

**Comment by xomx** [comment]
If replacing the main N++ executable installed with the patched binary ([32-bit](https://ci.appveyor.com/api/buildjobs/dqu8a1dx9hc3t84f/artifacts/Notepad%2B%2B.Win32.Release.exe), [64-bit](https://ci.appveyor.com/api/buildjobs/i57mhshhr8dphwed/artifacts/Notepad%2B%2B.x64.Release.exe)) helps, it is #11325 .

**Comment by donho** [comment]
> The installer asked me if I want to uninstall the old version first and I clicked "Yes".

Installer ask never that.

@Elmue, could you try the binaries @xomx provided please (https://github.com/notepad-plus-plus/notepad-plus-plus/issues/11365#issuecomment-1064495474) please ?

**Comment by xomx** [comment]
@donho 

> Installer ask never that.

He also tested 64-bit over 32-bit, so maybe it is this:
![npp-32to64](https://user-images.githubusercontent.com/13075183/157826519-d0e3f9ee-a13e-4d13-b1d4-287c05a9f759.png)
https://github.com/notepad-plus-plus/notepad-plus-plus/blob/master/PowerEditor/installer/nppSetup.nsi#L194
But even this will keep the custom config files (so a possible old session.xml file too) anyway.

The session.xml problem is the only one possibility I know about in between the v8.3.1 (which is reported here as ok) and the v8.3.2. Also it is true, that when you 1st installed the v8.3.1 & tried to run it, it fixes the old session.xml file format by updating its missing items at N++ exit, so then the v8.3.2 will work ok. This behavior will be fixed in v8.3.3 by https://github.com/notepad-plus-plus/notepad-plus-plus/pull/11327.

**Comment by donho** [comment]
@xomx 
> He also tested 64-bit over 32-bit, so maybe it is this:

Ah, true. I forget about this one.

> The session.xml problem is the only one possibility I know about in between the v8.3.1 (which is reported here as ok) and the v8.3.2.

Yes, But there's another possibility - incompatibility of plugins.
In 8.3.3 both issue are treated so this release should be stable now.

**Comment by double-standard-you** [comment]
> > The installer asked me if I want to uninstall the old version first and I clicked "Yes".
> 
> Installer ask never that.
> 
> @Elmue, could you try the binaries @xomx provided please ([#11365 (comment)](https://github.com/notepad-plus-plus/notepad-plus-plus/issues/11365#issuecomment-1064495474)) please ?

American Shares Truth About Joshua Wong & Hong Kong Democracy
https://www.youtube.com/watch?v=8nXz66Btfl0

American Shares Truth on Xinjiang and Tibet Controversies in China
https://www.youtube.com/watch?v=CldtoYwPtMk

Why is Ukraine the West’s Fault? Featuring John Mearsheimer
https://www.youtube.com/watch?v=JrMiSQAGOS4

Bat coronavirus found in U.S.-funded bio-lab in Ukraine: Russian Defense Ministry
https://www.youtube.com/watch?v=BCydUeHAhzQ

Ukrainians were denied US visas as White House promise help to refugees
https://www.youtube.com/watch?v=BGZhzNFmyhc

Reports of racist treatment against Africans trying to flee Ukraine
https://www.youtube.com/watch?v=JItYOW_uT8s

Fleeing African and Indian students face racism at Ukraine border
https://www.youtube.com/watch?v=ODMOzwI__zs

Canadian RCMP use horses to trample protestors
https://www.youtube.com/watch?v=Usn3CR0E1v0

A bald-faced lie from the Western media corp: Critical “Uyghur Genocide” Questions: A CBC Interview Follow-up
https://www.youtube.com/watch?v=O7IbsPFM2Xg

**Comment by double-standard-you** [comment]
> @xomx
> 
> > He also tested 64-bit over 32-bit, so maybe it is this:
> 
> Ah, true. I forget about this one.
> 
> > The session.xml problem is the only one possibility I know about in between the v8.3.1 (which is reported here as ok) and the v8.3.2.
> 
> Yes, But there's another possibility - incompatibility of plugins. In 8.3.3 both issue are treated so this release should be stable now.

American Shares Truth About Joshua Wong & Hong Kong Democracy
https://www.youtube.com/watch?v=8nXz66Btfl0

American Shares Truth on Xinjiang and Tibet Controversies in China
https://www.youtube.com/watch?v=CldtoYwPtMk

Why is Ukraine the West’s Fault? Featuring John Mearsheimer
https://www.youtube.com/watch?v=JrMiSQAGOS4

Bat coronavirus found in U.S.-funded bio-lab in Ukraine: Russian Defense Ministry
https://www.youtube.com/watch?v=BCydUeHAhzQ

Ukrainians were denied US visas as White House promise help to refugees
https://www.youtube.com/watch?v=BGZhzNFmyhc

Reports of racist treatment against Africans trying to flee Ukraine
https://www.youtube.com/watch?v=JItYOW_uT8s

Fleeing African and Indian students face racism at Ukraine border
https://www.youtube.com/watch?v=ODMOzwI__zs

Canadian RCMP use horses to trample protestors
https://www.youtube.com/watch?v=Usn3CR0E1v0

A bald-faced lie from the Western media corp: Critical “Uyghur Genocide” Questions: A CBC Interview Follow-up
https://www.youtube.com/watch?v=O7IbsPFM2Xg

**Comment by double-standard-you** [comment]
> @xomx
> 
> > He also tested 64-bit over 32-bit, so maybe it is this:
> 
> Ah, true. I forget about this one.
> 
> > The session.xml problem is the only one possibility I know about in between the v8.3.1 (which is reported here as ok) and the v8.3.2.
> 
> Yes, But there's another possibility - incompatibility of plugins. In 8.3.3 both issue are treated so this release should be stable now.

American Shares Truth About Joshua Wong & Hong Kong Democracy
https://www.youtube.com/watch?v=8nXz66Btfl0

American Shares Truth on Xinjiang and Tibet Controversies in China
https://www.youtube.com/watch?v=CldtoYwPtMk

Why is Ukraine the West’s Fault? Featuring John Mearsheimer
https://www.youtube.com/watch?v=JrMiSQAGOS4

Bat coronavirus found in U.S.-funded bio-lab in Ukraine: Russian Defense Ministry
https://www.youtube.com/watch?v=BCydUeHAhzQ

Ukrainians were denied US visas as White House promise help to refugees
https://www.youtube.com/watch?v=BGZhzNFmyhc

Reports of racist treatment against Africans trying to flee Ukraine
https://www.youtube.com/watch?v=JItYOW_uT8s

Fleeing African and Indian students face racism at Ukraine border
https://www.youtube.com/watch?v=ODMOzwI__zs

Canadian RCMP use horses to trample protestors
https://www.youtube.com/watch?v=Usn3CR0E1v0

A bald-faced lie from the Western media corp: Critical “Uyghur Genocide” Questions: A CBC Interview Follow-up
https://www.youtube.com/watch?v=O7IbsPFM2Xg

**Comment by Elmue** [comment]
You are right.
It is the file Session.xml
I can reproduce it 100%
When I delete the old Session.xml it starts.

I would like to attach the file here. But it seems file uploads are not allowed here.
This is really a shame !

I uploaded the bad file to my homepage:
[https://netcult.ch/elmue/session.xml](https://netcult.ch/elmue/session.xml)

**Comment by Elmue** [comment]
> If replacing the v8.3.2 main N++ executable installed with the patched binary ([32-bit](https://ci.appveyor.com/api/buildjobs/dqu8a1dx9hc3t84f/artifacts/Notepad%2B%2B.Win32.Release.exe), [64-bit](https://ci.appveyor.com/api/buildjobs/i57mhshhr8dphwed/artifacts/Notepad%2B%2B.x64.Release.exe)) helps, it is https://github.com/notepad-plus-plus/notepad-plus-plus/issues/11325 .

Yes it is fixed !
Thank you.

**Comment by xomx** [comment]
@Elmue 

> why does the program not start and finish immediately without showing anything?

Well, when there is a serious programmer's mistake (sorry for that), there is also a serious consequence :-)

**Comment by Yaron10** [comment]
@xomx,

> If replacing the v8.3.2 main N++ executable installed with the patched binary ([32-bit](https://ci.appveyor.com/api/buildjobs/dqu8a1dx9hc3t84f/artifacts/Notepad%2B%2B.Win32.Release.exe), [64-bit](https://ci.appveyor.com/api/buildjobs/i57mhshhr8dphwed/artifacts/Notepad%2B%2B.x64.Release.exe)) helps, it is https://github.com/notepad-plus-plus/notepad-plus-plus/issues/11325 .

That was good. 👍

**Comment by Elmue** [comment]
> Well, when there is a serious programmer's mistake (sorry for that), there is also a serious consequence :-)

So you confirm what I already supposed ?
This was a complete crash ?

How about implementing structured exception handling?

For each thread that you create on your own:

```
DWORD WINAPI Thread(void* p_Arg)
{
   __try
   {
      return ThreadLoop();
   }
   __catch
   {
      Show error
      Exit program
   }
}

```
and for the GUI thread:

```
LRESULT CALLBACK WindowProc(HWND hWnd, UINT uMsg, WPARAM wParam, LPARAM lParam)
{
   __try
   {
      return ProcessGuiMessages(hWnd, uMsg, wParam, lParam);
   }
   __catch
   {
      Show error
      Exit program
   }
}

and this will never happen again.
```

**Comment by xomx** [comment]
@Elmue

> How about implementing structured exception handling?

https://github.com/notepad-plus-plus/notepad-plus-plus/blob/master/PowerEditor/src/winmain.cpp#L704

But unfortunately it does not help you in this case.

Probably for security reasons, in VC8+ (Visual Studio 2005 and above) it is not possible to catch all unhandled exceptions (by default, you can overcome that, if you really want to). I will not go into details, examples are: 
- abort() stuff (SIGABRT)
- other POSIX signals like SIGINT, SIGTERM, SIGFPE, SIGILL, SIGSEGV
- C++ purecalls
- C runtime invalid params handler

The last one mentioned above (the error happens in the `_wtoi64` called from N++) is the reason, why the installed N++ SEH-handler has not been triggered here. The code-flow ends up here instead:

".\Windows Kits\...\Source\...\ucrt\misc\invalid_parameter.cpp":
```
        if (IsProcessorFeaturePresent(PF_FASTFAIL_AVAILABLE))
        {
            __fastfail(FAST_FAIL_INVALID_ARG);
        }
```
Further info:
https://docs.microsoft.com/en-us/cpp/intrinsics/fastfail
https://docs.microsoft.com/en-us/cpp/c-runtime-library/reference/set-invalid-parameter-handler-set-thread-local-invalid-parameter-handler

**Comment by Elmue** [comment]
OK.
But before executing fastfail() you could show a messagebox.

**Comment by xomx** [comment]
@Elmue 

> But before executing fastfail() you could show a messagebox.

No, that is impossible (without using e.g. the mentioned `_set_invalid_parameter_handler` CRT func). From the moment the N++ called incorrectly the `_wtoi64(NULL)`, the N++ does not get back control over the performed code.

This `__fastfail` ending has another unpleasant consequence - a N++ zombie process (you can check that via a Task Manager).

**Comment by donho** [comment]
Fixed in https://github.com/notepad-plus-plus/notepad-plus-plus/commit/a419b41ed5f35e76ad9207a127affdf0844a5333

**Comment by Elmue** [comment]
> This __fastfail ending has another unpleasant consequence - 

So dont use it. Use TerminateProcess() instead.

> No, that is impossible (without using e.g. the mentioned _set_invalid_parameter_handler

So why dont you implement this hander ?
I tested this and it works:

```
_set_new_handler   (NewCrashHandler);     // C code
AfxSetNewHandler (NewCrashHandler);     // C++ code
_set_invalid_parameter_handler(InvalidParamHandler); // _wtoi(NULL)

```
with these functions:

```
static int NewCrashHandler(size_t s32_RequestedSize)
{
    MessageBox(NULL, L"Invalid Parameter. The program will close due to a crash", L"Fatal Error", MB_ICONSTOP);
    TerminateProcess(GetCurrentProcess(), 0);
    return 0; 
}

static void InvalidParameterHandler(const wchar_t* u16_Expression, // NULL in a Release Build
                                    const wchar_t* u16_Function,    // NULL in a Release Build
                                    const wchar_t* u16_File,    // NULL in a Release Build
                                    UINT           u32_Line,   // NULL in a Release Build
                                    uintptr_t p_Reserved)
{
    MessageBox(NULL, L"Operator 'new' failure. The program will close due to a crash", L"Fatal Error", MB_ICONSTOP);
    TerminateProcess(GetCurrentProcess(), 0);
}


```

**Comment by donho** [comment]
@Elmue 
> I tested this and it works:

Thank you. I will consider it.

**Comment by xomx** [comment]
@donho 

I am using such custom crash handlers myself, but I thought that here in N++ will not be an interest (you know - too much code-lines for a small gain in a specific scenario...). Anyway, if you decide that it is worth implementing that, please take into account also the other stuff I mentioned here, at least the following 'simple' ones:
- C++ [purecalls](https://devblogs.microsoft.com/oldnewthing/20040428-00/?p=39613) (via the `_set_purecall_handler`)
- SIGABRT (all the `abort()` stuff, via the `_CrtSetReportMode` & `_set_abort_behavior` & `signal` )
- SIGTERM (termination request handler, via the `signal`)
- maybe SIGINT (interrupt (Ctrl+C) handler, via the `signal`)

But I do not know if such handlers can coexist with the N++ GCC support, it would have to be tested.

Other POSIX signals (SIGFPE, SIGILL, SIGSEGV) are little bit more difficult to handle.
And other C++ exception handlers like `set_terminate` or `set_unexpected` work on per-thread basis, so this is also not as simple as the previous ones.
You can even catch the swallowed COM exceptions via the `IGlobalOptions` `COMGLB_EXCEPTION_DONOT_HANDLE` or swallowed user/kernel mode callbacks exceptions.

**Comment by Elmue** [comment]
> C++ purecalls (via the _set_purecall_handler)
It is as easy to implement as the other 2 which I gave as example.

> SIGABRT
Does Notepad++ ever call abort() ?
If so it would have to be changed to call a better handler.

> SIGINT (interrupt (Ctrl+C) handler)
CTRL+C is only an abort signal in console applications. In Notepad++ it copies a text to the clipboard.
Does Notepad++ ever call raise() or kill() ?
If so they would have to be changed to call a better handler.

> SIGTERM 
I have never seen this. It seems to be used on Linux only?

> the __fastfail stuff is also used by the stack security cookies technology to prevent the hacker stack-overflow attacks.
Well, I doubt that a hacker will attack Notepad++.
I cannot see a problem with TerminatProcess().
It has been made for this purpose and I have never seen that it did not terminate the process.

Even if there remain special cases which are not caught by these handlers, it will catch a lot of possible crashes already.

I think all this is so easy to implement that it is faster to just write these few lines than to start a discussion and find reasons why not to do so.

It is simply a bad programming habit to shut down a process without informing the user.
Full Stop.
