### ISSUE TITLE
Can not change most fonts in Style Configurator

### ISSUE THREAD

**Issue by Skydef** [notepad-plus-plus/notepad-plus-plus#11366]
### Description of the Issue
I'm using Notepad++ v8.2.1 on Windows 10. The version I had installed before was v7.9.5. It's no longer possible to change fonts for specific languages in the Style Configurator. The only fonts I can change are 'Global Styles->Global override' and 'Global Styles->Default Style'. For all other languages and styles the font drop-box is disabled. In v7.9.5 I was able to set all the fonts. I verified this on two machines. In the places where I've set a custom font the drop-box is still enabled and I can choose a different one.

### Steps to Reproduce the Issue

1. get np++ v8.2.1 or above (maybe also some versions before this, did not test all)
2. go to 'Settings->Style Configurator'
3. try to set language specific font (e.g. C++->PREPROCESSOR->Font Style->Font name); the Global Style font drop-boxes are also disabled except for the first two (Global override & Default Style)

### Expected Behavior
Select font via the Font name drop-box

### Actual Behavior
Font name drop-box disabled (was not disabled previously in v7.9.5)

### Debug Information
Notepad++ v8.2.1   (64-bit)
Build time : Jan 19 2022 - 18:43:05
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 10 Pro (64-bit) 
OS Version : 2009
OS Build : 19043.1526
Current ANSI codepage : 1252
Plugins : mimeTools.dll NppConverter.dll NppExport.dll 

![np++ bug report](https://user-images.githubusercontent.com/7687513/157745471-3ba48f3b-87ef-4952-87a3-b66d3da38062.png)

**Comment by donho** [comment]
Fixed in https://github.com/notepad-plus-plus/notepad-plus-plus/commit/2d7b2093a198d814d8a69b2f44942637cf11e1c9
