### ISSUE TITLE
Settings for additional borders

### ISSUE THREAD

**Issue by depascalis** [notepad-plus-plus/notepad-plus-plus#11376]
### Description of the Issue
Borders are inconsistent and have too much contrast in dark mode for my taste.

### Suggestions
In short, add  color settings for various borders and fix inconsistent border widths. Maybe even add settings for custom border widths.

1. Dialog - Add settings for border color and width (some prefer high contrast borders, others prefer no borders at all)
2. List box and Text box
a. These borders are either `1.5 px`  wide or the control needs to shrink/grow `1 px` or the controls are misaligned `0.5 px`. 
b. Add setting for border color
3. Group box
a. Add setting for border color
b. Left align the title label (looks better when borders are invisible)
4. Buttons - Add setting for border color and width

Point 2 and 3 have the highest priority imo.

_Before_
![npp_borders_bef](https://user-images.githubusercontent.com/33980634/157950257-88e3f1f0-3722-48e2-b9a9-fc609d3f93e4.png)

_After_
![npp_borders_aft](https://user-images.githubusercontent.com/33980634/157950283-f0e4daef-0863-46fb-a282-bd7f83bbfa8e.png)

Suggestions above refer to controls in all dialogs, not only the Preferences dialog.

**Comment by ozone10** [comment]
Notepad++ is using common control, which is "defined" by Windows OS.

So not possible, unless everything is owner/custom drawn, which would require a lot of code rewriting.
