### ISSUE TITLE
U mom will die with Ukrainian, traitor! 你妈和乌克兰人都要死，汉奸！

### ISSUE THREAD

**Issue by NMSLUMD** [notepad-plus-plus/notepad-plus-plus#11371]
Ukrainian are nazi and you are a traitor, what a pair! 
乌克兰是纳粹而你是汉奸，真是一对！

**Comment by double-standard-you** [comment]
> 

American Shares Truth About Joshua Wong & Hong Kong Democracy
https://www.youtube.com/watch?v=8nXz66Btfl0

American Shares Truth on Xinjiang and Tibet Controversies in China
https://www.youtube.com/watch?v=CldtoYwPtMk

Why is Ukraine the West’s Fault? Featuring John Mearsheimer
https://www.youtube.com/watch?v=JrMiSQAGOS4

Bat coronavirus found in U.S.-funded bio-lab in Ukraine: Russian Defense Ministry
https://www.youtube.com/watch?v=BCydUeHAhzQ

Ukrainians were denied US visas as White House promise help to refugees
https://www.youtube.com/watch?v=BGZhzNFmyhc

Reports of racist treatment against Africans trying to flee Ukraine
https://www.youtube.com/watch?v=JItYOW_uT8s

Fleeing African and Indian students face racism at Ukraine border
https://www.youtube.com/watch?v=ODMOzwI__zs

Canadian RCMP use horses to trample protestors
https://www.youtube.com/watch?v=Usn3CR0E1v0

A bald-faced lie from the Western media corp: Critical “Uyghur Genocide” Questions: A CBC Interview Follow-up
https://www.youtube.com/watch?v=O7IbsPFM2Xg

**Comment by neilbowman666** [comment]
Nice job

**Comment by neilbowman666** [comment]
We strongly condemn author's bitchy ideology which is raping everybody around the world.

**Comment by neilbowman666** [comment]
brave guy
