### ISSUE TITLE
Program crash during save erases file!

### ISSUE THREAD

**Issue by drupamatic** [notepad-plus-plus/notepad-plus-plus#1137]
Ran in to a pretty serious bug the other day. I clicked the save button for one of my files, NotePad++ stopped responding. When I reopened, the entire file was empty: 0 bytes. Lost 1000 lines of code (Luckily, I backup)

Seems that when Notepad++ saves, it first clears out the file, then rewrites it. This can be a serious problem if the program happens to crash during that time

**Comment by donho** [comment]
@drupamatic which version do you use? Could you also provide your plugin list?

**Comment by donho** [comment]
Without further info, I have to close this issue.
Please reopen it when you can provide more info about it.
