### ISSUE TITLE
Freezing when internet lost to network drive file

### ISSUE THREAD

**Issue by mike352** [notepad-plus-plus/notepad-plus-plus#11388]
### Description of the Issue
When I have a network drive file open and the connection is lost, Notepad++ freezes before showing a dialogue box. This was the case in the past and was annoying. In the past, though, once the dialogue box was dealt with, there was no more freezing. At the moment, there's freezing each time there's a change in focus to Notepad++. 

### Steps to Reproduce the Issue

1. Open a network drive file
2. Lose internet connection to the network drive
3. Change focus to the file

### Expected Behavior
I don't think Notepad++ should be freezing. Can it not check for connection to the drive independently of being able to edit the file? And I think it shouldn't be doing it each time there's a change in focus. 

### Actual Behavior
There's a freezing each time there's a change in focus to a file in a network drive where access has been severed. 

### Debug Information
Notepad++ v8.2.1   (64-bit)
Build time : Jan 19 2022 - 18:43:05
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 11 (64-bit) 
OS Version : 2009
OS Build : 22000.556
Current ANSI codepage : 1252
Plugins : mimeTools.dll NppConverter.dll NppExport.dll

**Comment by sukhoi191** [comment]
Until there is a fix, a quick workaround is to delete %APPDATA%/Notepad++/session.xml. However, this will also delete all the information regarding any other files that were open in other tabs. To prevent that, you might edit session.xml instead of deleting it and remove only problematic "File" elements, with paths leading to disconnected network drive.

**Comment by donho** [comment]
@mike352 @sukhoi191 
Please try the latest state of fixed binary here (x64):
https://github.com/notepad-plus-plus/notepad-plus-plus/actions/runs/11118197845/artifacts/1998785683

The hanging issue should be improved considerably.
