### ISSUE TITLE
Word wrap was checked but text not wrapped (rare)

### ISSUE THREAD

**Issue by jay** [notepad-plus-plus/notepad-plus-plus#1138]
Rarely it will happen that word wrap is checked but the text is not wrapped. For example, I open a new text file in Notepad++ and paste in the text expecting it to be wrapped but every once in a while it is not. 'View > Word wrap' is already checked. If I select it again it remains checked and the text is then wrapped. I'm using Windows 7 x64 Enterprise and Notepad++ 6.8.6 (2015-10-29) with font Consolas. I've noticed this in earlier versions as well. I don't have a way to reproduce but if I find one I'll let you know.

**Comment by leewz** [comment]
Do you happen to use Compare much? That turns off wordwrap without toggling the button.

**Comment by jay** [comment]
> Do you happen to use Compare much? That turns off wordwrap without toggling the button.

Yeah I probably did that, thanks for the info. Should I report somewhere else?

**Comment by xylographe** [comment]
@jay 
Try the latest [Compare plugin development version](https://github.com/pnedev/compare-plugin) (DLLs available [here](https://www.dropbox.com/sh/f42cxkqppuapa1j/AADvlcmqoK_myRmoOpeL1yGMa?dl=0)).
[Create an issue](https://github.com/pnedev/compare-plugin/issues) if the problem persists.

**Comment by leewz** [comment]
@xylographe Why not have DLLs in "Releases"?

**Comment by jay** [comment]
> Try the latest Compare plugin development version (DLLs available here).

A few months ago I updated to the latest compare DLL at that time (https://ci.appveyor.com/project/jsleroy/compare-plugin/history > Debug Unicode; Platform Win32 > ARTIFACTS) and since then I haven't had the problem. I waited a while to update this to be sure. Thanks @xylographe
