### ISSUE TITLE
Scroll position lost after switching Tabs

### ISSUE THREAD

**Issue by mendya** [notepad-plus-plus/notepad-plus-plus#1139]
When you switch tabs, the focus goes to the top of the page and the cursor moves to position 1 of the document.
It would be nice to have that each tab should remember where it was last so that when you switch to a tab you don't have to search where you were last typing or viewing.

**Comment by dail8859** [comment]
It is a known bug with XML Tools. Either install the new version from their website or try turning off "Set XML type automatically".

**Comment by mendya** [comment]
Thank you , you were right, I installed the latest version and the problem
went away.

On Fri, Nov 13, 2015 at 10:00 AM, dail8859 <notifications@github.com> wrote:

> It is a known bug with XML Tools. Either install the new version from
> their website or try turning off "Set XML type automatically".
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/notepad-plus-plus/notepad-plus-plus/issues/1139#issuecomment-156454432>
> .
>



-- 
Mendy Aaron
Lead Technologist
Croton Group
201-939-5100 x1031
mendya@crotongroup.com

www.crotongroup.com
www.facebook.com/crotonwatch
www.twitter.com/crotonwatch
