### ISSUE TITLE
Autocomplete crash npp

### ISSUE THREAD

**Issue by sebastian-czarnecki** [notepad-plus-plus/notepad-plus-plus#11396]
### Description of the Issue

During writing html code with autocomplete for <body> </body> NPP crash / shutdown

### Steps to Reproduce the Issue
1. enter '\<body\>' and return
2. enter '\<\/body\>' and return
3. 

when You enter '</bod' - program crash

### Expected Behavior
Autocomplete procedure

### Actual Behavior
NPP crash

### Debug Information

Notepad++ v8.3   (64-bit)
Build time : Feb  3 2022 - 03:39:05
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 10 Pro (64-bit) 
OS Version : 2009
OS Build : 19044.1586
Current ANSI codepage : 1250
Plugins : mimeTools.dll NppConverter.dll NppExport.dll 

Additionally I notice in previous version in autocomplete that enter key put new line instead of accept autocomplete proposition accept

**Comment by donho** [comment]
Fixed.
Please try v8.3.3.

**Comment by sebastian-czarnecki** [comment]
No update available in app, but ok manual update works. But accepting autocomplete option don't work still: when accept option new line enter instead of option accept

**Comment by 3beeepb** [comment]
+1

**Comment by 3beeepb** [comment]
> No update available in app, but ok manual update works. But accepting autocomplete option don't work still: when accept option new line enter instead of option accept

https://github.com/notepad-plus-plus/notepad-plus-plus/issues/11328
