### ISSUE TITLE
Feature Request = Call for Plugin

### ISSUE THREAD

**Issue by tiomanisland** [notepad-plus-plus/notepad-plus-plus#11400]
### Description of the Issue

Since there is no AUTO-SORT tabs (on the fly!) I would like to ask someone to write a plugin and name the price here. I need that and I am willing to pay for it.

### Steps to Reproduce the Issue

1. 
2. 
3.

**Comment by alankilborn** [comment]
Really an inappropriate place to request this.  Try https://community.notepad-plus-plus.org/

Also, you leave out the key component: What the sorting criterion?  And I'm sure more questions follow from that...

**Comment by tiomanisland** [comment]
Sort tabs A-Z in real time. For example you have tabs:

config.php  load.php  switch_icon.php 

Now you open another file "load2.php" - i want tabs to look like this:

config.php  load.php  load2.php  switch_icon.php 

(auto sorting). If could be plugin to allow checkbox "Autosort" or "Default - no sorting"

**Comment by dail8859** [comment]
As suggested, the community forum would be the best place to discuss new plugin development.
