### ISSUE TITLE
not buildable for arm64 in MVS2017

### ISSUE THREAD

**Issue by JohannesDecker95** [notepad-plus-plus/notepad-plus-plus#11404]
### Description of the Issue
I tried to build the repo for arm64 in MVS2017 (Microsoft Visual Studio 2017) and get always the same errors:

The platform for project "SciLexer.vcxproj" is invalid.        _**and**_
The platform for project "notepadPlus.vcxproj" is invalid.

### Steps to Reproduce the Issue

1. Download the repo
2. Open the **notepad-plus-plus-master\PowerEditor\visual.net\notepadPlus.sln** file in MVS2017
3. Set build configuration to ARM64 (Debug or Release is not relevant)
4. Run the build process

### Expected Behavior
Notepad++ will be build without errors

### Debug Information
MVS2017  error code MSB8007

**Comment by ArkadiuszMichalski** [comment]
@donho After https://github.com/notepad-plus-plus/notepad-plus-plus/issues/9922 MVS2017 is still on board? If not then [BUILD.md](https://github.com/notepad-plus-plus/notepad-plus-plus/blob/master/BUILD.md) should be correct.

**Comment by donho** [comment]
@ArkadiuszMichalski 
The latest release (v8.3.3) was built with MVS2017 with the prod PC - so I'm ensuring you it does work with MVS2017.
