### ISSUE TITLE
N++ doesn't detect JSON Lexer Type in Theme

### ISSUE THREAD

**Issue by lsequeiraa** [notepad-plus-plus/notepad-plus-plus#11406]
### Description of the Issue
JSON files aren't being styled in certain themes, even though the theme .xml contains a lexer type for JSON files.
This is not a general behavior since it seems that in some themes it works, like in DansLeRuSH-Dark.

### Steps to Reproduce the Issue
1. Open StyleConfigurator
2. Select Ruby Blue (for example)
3. Notice that JSON doesn't appear on the Language's list.
4. Make sure that "Ruby Blue.xml" contains a Lexer Type for JSON.

### Expected Behavior
To see JSON in the Language's tab and have JSON files be styled.

### Actual Behavior
JSON doesn't appear in the Language's tab and as such, JSON files aren't being styled.

### Debug Information
Notepad++ v8.2.1   (64-bit)
Build time : Jan 19 2022 - 18:43:05
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 10 Education (64-bit) 
OS Version : 2009
OS Build : 19043.1586
Current ANSI codepage : 1252
Plugins : ComparePlugin.dll mimeTools.dll NppConverter.dll NppExport.dll 

![image](https://user-images.githubusercontent.com/17601958/158998318-6a151144-3f45-441a-ae77-9c6b9ffc5afb.png)

**Comment by ArkadiuszMichalski** [comment]
I can't reproduce this. Make sure you have actual theme files.
![image](https://user-images.githubusercontent.com/2730894/200698057-1e4b8a7a-ba9d-4774-9f93-0a3da0de4cf1.png)
