### ISSUE TITLE
Certain keyboard functions do not work in File dialog boxes

### ISSUE THREAD

**Issue by teamsiems** [notepad-plus-plus/notepad-plus-plus#11429]
### Description of the Issue

In each File dialog (Save, Open, even Print) in the 'File name' input box I cannot use Ctrl+V to paste a text string. I also cannot use the Delete key in the 'File name' box.

The Spacebar, Backspace, Home and End keys work. Mouse functions (Select, Cut, Copy, Paste, etc) work.

### Steps to Reproduce the Issue

1. With NPP started, click File menu, click Open...
2. In the 'File name:' input box, type a filename, put cursor at the beginning of the filename, press Delete key (Doesn't work)
3. Select the filename either with mouse or keyboard, press Ctrl+X to cut the filename into memory (Doesn't work)
4. With a string of text in your Copy-Paste memory press Ctrl+V in the 'File name:' box (Doesn't work)

### Expected Behavior

I expect to use keyboard keys and functions on every dialog box.

### Actual Behavior

Certain key combinations do not work.

### Debug Information

Notepad++ v8.3.3   (64-bit)
Build time : Mar 13 2022 - 17:20:02
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : ON
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 10 Enterprise (64-bit) 
OS Version : 2009
OS Build : 19044.1586
Current ANSI codepage : 1252
Plugins : ComparePlugin.dll mimeTools.dll NppConverter.dll NppExport.dll XMLTools.dll _CustomizeToolbar.dll

**Comment by alankilborn** [comment]
Can't reproduce with same version.
Perhaps remove plugins and see if that changes anything?

**Comment by ArkadiuszMichalski** [comment]
You can also try with [last portable version](https://github.com/notepad-plus-plus/notepad-plus-plus/wiki/Testing#using-the-latest-release-portable-version-of-notepad) to eliminate other problems (plugins or config).

**Comment by teamsiems** [comment]
Some update seems to have fixed it; not a new version. I had to install Compare and XML Tools again. Maybe going from Windows 10 -> 11 ?

Notepad++ v8.3.3   (64-bit)
Build time : Mar 13 2022 - 17:20:02
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 11 (64-bit) 
OS Version : 2009
OS Build : 22000.593
Current ANSI codepage : 1252
Plugins : ComparePlugin.dll mimeTools.dll NppConverter.dll NppExport.dll XMLTools.dll _CustomizeToolbar.dll
