### ISSUE TITLE
Doc is wrongly marked as Saved

### ISSUE THREAD

**Issue by Yaron10** [notepad-plus-plus/notepad-plus-plus#11436]
**STR:**
Open a new document (UTF-8).
Paste some text.
Convert to ANSI.
Select All.
Delete.
Undo.

**Result:**
Doc is marked as Saved.

***

Notepad++ v8.3.3 (64-bit)
Build time : Mar 13 2022 - 17:20:02
Path : C:---\npp.8.3.3.portable.x64\notepad++.exe
Command Line :
Admin mode : ON
Local Conf mode : ON
Cloud Config : OFF
OS Name : Windows 10 Pro (64-bit)
OS Version : 2009
OS Build : 19042.985
Current ANSI codepage : 1255
Plugins : BetterMultiSelection.dll DSpellCheck.dll mimeTools.dll NppConverter.dll NppExport.dll

**Comment by donho** [comment]
It's a legacy bug. I can even reproduce it in v6.6.6.

**Comment by Yaron10** [comment]
Better late than never. :)

Thank you for looking into it.

**Comment by Yaron10** [comment]
6.6.6?! :)

**Comment by donho** [comment]
@Yaron10 
[Notepad++ v6.6.6 the 13th Friday Edition](https://notepad-plus-plus.org/news/v666-friday-13th-edition/) ;)

**Comment by Yaron10** [comment]
@donho,

I can imagine the responses to that version. :)

Think of the following (forum) announcement on the coming **April 1st**.

**Notepad++ has been purchased by Microsoft**

- The next Notepad++ versions will no longer be free. 
- I am retiring to the the Caribbean Islands.

**Comment by donho** [comment]
More creditable version will be:
Notepad++ has been purchased by Microsoft, and it will always be open source and distributed with no charge.
In fact, the project Notepad++ will be merged with MS Visual Code with the new brand **MVC++**.

**Comment by Yaron10** [comment]
Amen to that. 
Actually I prefer N++.
