### ISSUE TITLE
UDL multi-part keyword in prefix mode freezes Notepad++

### ISSUE THREAD

**Issue by SnipUndercover** [notepad-plus-plus/notepad-plus-plus#11434]
### Description of the Issue
Typing out a multi-part keyword (*enclosed in either single or double quotes*) that consists of more than 1 word which has been defined in a group that has prefix mode enabled will freeze Notepad++ and cause it to not respond.

### Steps to Reproduce the Issue
1. Create a new file.
1. Set the language to **User-Defined**. (*Language > User-Defined*)
1. Open the UDL menu. (*Language > User Defined Language > Define your language...*)
1. Ensure the **User language** field is set to **User Defined Language**.
1. Navigate to the **Keywords Lists** tab.
1. Enter anything that is enclosed in either double or single quotes that includes at least one space in any group.
Examples:
`"Hello, world!"`
`'Example multi-part keyword'`
1. Ensure that that group has **Prefix mode** set.
1. Type out the keyword in the file, followed by a space or a line break.

### Expected Behavior
The expected style would be applied to the keyword.

### Actual Behavior
Notepad++ freezes.

### Debug Information
Notepad++ v8.1.9.3   (64-bit)
Build time : Dec  6 2021 - 19:21:37
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 10 Home (64-bit) 
OS Version : 2009
OS Build : 19044.1586
Current ANSI codepage : 1250
Plugins : mimeTools.dll NppConverter.dll NppExport.dll

### Screenshots
![Setting the language to User Defined Language](https://user-images.githubusercontent.com/49392266/160021459-d9b5bd4a-fcac-47bb-84d6-d05494fe2b2d.png)
![Entering the UDL menu](https://user-images.githubusercontent.com/49392266/160021498-173d606f-ea1c-4043-82b8-6d4d1a76e709.png)
![Creating a multi-part keyword](https://user-images.githubusercontent.com/49392266/160021525-617c6ffb-ac53-4cc2-8777-a889661786e6.png)
![Triggering the freeze](https://user-images.githubusercontent.com/49392266/160021541-bd9f924a-c08b-4d7f-a93d-a80124c4d8ef.png)

**Comment by rdipardo** [comment]
Your UDL is causing an infinite loop, here:

https://github.com/notepad-plus-plus/notepad-plus-plus/blob/32580e6a800130b3abfa8dd2ecbf6284a3bda97a/scintilla/lexers/LexUser.cxx#L1063-L1074

Note the comment saying "sc.GetRelative returns '  ' beyond EOF".

WRONG! `StyleContext::GetRelative` returns `'\0'` (`null`) when the end of the document is reached:

https://github.com/notepad-plus-plus/notepad-plus-plus/blob/32580e6a800130b3abfa8dd2ecbf6284a3bda97a/scintilla/lexlib/StyleContext.h#L157-L159

However, neither `::isWhiteSpace` nor `::isWhiteSpace2` considers `\0` to be "whitespace":

https://github.com/notepad-plus-plus/notepad-plus-plus/blob/32580e6a800130b3abfa8dd2ecbf6284a3bda97a/scintilla/lexers/LexUser.cxx#L215-L234

So this `while` condition is __*always*__ true:

https://github.com/notepad-plus-plus/notepad-plus-plus/blob/32580e6a800130b3abfa8dd2ecbf6284a3bda97a/scintilla/lexers/LexUser.cxx#L1066

**Comment by rdipardo** [comment]
### Quick Fix

```diff
diff --git a/scintilla/lexers/LexUser.cxx b/scintilla/lexers/LexUser.cxx
index bb1a0d47..462294c8 100644
--- a/scintilla/lexers/LexUser.cxx
+++ b/scintilla/lexers/LexUser.cxx
@@ -214,7 +214,7 @@ static nestedMapType nestedMap;
 
 static inline bool isWhiteSpace(const int ch)
 {
-    return (ch > 0 && ch < 0x21);
+    return (ch >= 0 && ch < 0x21);
 }
 
 static inline bool isWhiteSpace2(unsigned char ch, int & nlCount, unsigned char excludeNewLine=0, unsigned char chNext=0)

```

**Comment by SnipUndercover** [comment]
@rdipardo
`'\0'` is usually considered not to be a whitespace character, however the fix introduced in `::isInListBackward` seems to work by itself.
Thank you for the help!
