### ISSUE TITLE
Wrong application version in file details

### ISSUE THREAD

**Issue by stipegrbic** [notepad-plus-plus/notepad-plus-plus#11431]
### Description of the Issue
There's a wrong "Product version" number in application .exe file. It differs from the "File version" and the official version number that's shown on the web.

### Steps to Reproduce the Issue

1. Install Notepad++
2. Find the installed application .exe file
3. Open file properties, details tab

### Expected Behavior
Product version number should be the same as shown on the web when downloading the installer, and the same as shown in Control Panel list of installed programs. In this case it should be "8.3.3"

### Actual Behavior
Product version number is different. In this case it's "8.33"

![image](https://user-images.githubusercontent.com/4949711/159744816-fc8c60bc-2865-4460-b220-33118dbea5e8.png)

**Comment by ArkadiuszMichalski** [comment]
This way of presenting the version has always been:
https://github.com/notepad-plus-plus/notepad-plus-plus/blob/a29cfa8d25a72f9e337ba1b6ed87e3fc723f99a2/PowerEditor/src/resource.h#L26

**Comment by stipegrbic** [comment]
Ok, so the correct version number is 8.3.3. Can you tell me why Product version says 8.33 then? Is this wrong, can it be corrected?

**Comment by stipegrbic** [comment]
We are using the FileVersionInfo class to determine th

**Comment by stipegrbic** [comment]
@rdipardo Thank you for detailed explanation. Now I see why you have this version number in different format. I know there are different ways to get the version number, but we're trying to do it the same way for other applications, and other applications have the Product version in the same format as the correct version number is. This is basically breaking our version detection.
