### ISSUE TITLE
Add an option to prevent the arrow keys from moving cursor to previous/next line

### ISSUE THREAD

**Issue by m6502** [notepad-plus-plus/notepad-plus-plus#11444]
### Description of the Issue
Caret moves to the previous or next line when moving left or right and reaching the start or the end of the lines. There's no easy way to change the behavior unless resorting to hacky methods.

### Steps to Reproduce the Issue

Load or type some lines of text. Press left until reaching the start of a line, or right until reaching the end of a line. If there's any line before or after the current one the caret will wrap to the end of the previous line or the start of the next one. Open the settings menu and go to Preferences -> Editing. No option there.

### Expected Behavior

Having a checkbox for this.

### Actual Behavior

There's no checkbox for this.

###

Opening this issue as a prerequisite for an incoming pull request.

**Comment by TazzyT** [comment]
Look for "word wrap" in the icon bar.  That is the line wrap.
You can also find it under View > Word wrap.

**Comment by m6502** [comment]
Hi, these are two different things. "Word wrap" is related to how the text is displayed and makes long lines fully visible with a smaller window by splitting them into "virtual" unnumbered lines. "Line wrap" is related to edition itself and determines where the caret goes when moving within the text and reaching the start or the end of a line and try to continue moving in that direction.

**Comment by dfs-** [comment]
Just as a general question: why don't you use the HOME/POS1 and END key? Is the use-case different from what those keys do?

**Comment by alankilborn** [comment]
@m6502 Can you cite other text editors that support the behavior you'd like to see in Notepad++?

**Comment by m6502** [comment]
Microsoft Visual Studio. Metrowerks CodeWarrior. Vim. And many more.

**Comment by m6502** [comment]
Also, Notepad++ already supports it, with the modifications I already did to my local copy of the code.

**Comment by dfs-** [comment]
> Also, Notepad++ already supports it, with the modifications I did to my local copy of the code.

Excellent, might you want to create a pull request for the change/additional setting?

**Comment by alankilborn** [comment]
Hmm, my Microsoft Visual Studio doesn't seem to support it...

IMO this isn't needed.
Notepad++ author philosophy is "too many options == no option".

**Comment by m6502** [comment]
> > Also, Notepad++ already supports it, with the modifications I did to my local copy of the code.
> 
> Excellent, might you want to create a pull request for the change/additional setting?

Sure, that's the reason why I both opened this issue and #11443, which I also have working locally. But as this is the first time I contribute to this project I'm cautious. I want to be sure I don't break translations or resources, as I said in the other issue: https://github.com/notepad-plus-plus/notepad-plus-plus/issues/11443#issuecomment-1080105419

**Comment by m6502** [comment]
> Hmm, my Microsoft Visual Studio doesn't seem to support it...
> 
> IMO this isn't needed. Notepad++ author philosophy is "too many options == no option".

This has been supported in Microsoft Visual Studio since the 90s.

**Comment by alankilborn** [comment]
>This has been supported in Microsoft Visual Studio since the 90s.

Maybe point out how to configure it to do it?
Plus, if it is a setting that one has to turn on in VS, perhaps such a Notepad++ feature could use the same text in its UI for the feature.

**Comment by alankilborn** [comment]
>But as this is the first time I contribute to this project I'm cautious

I would say submit the PR for the code you have.
If N++ author likes it in general, you can push further commits to get it exactly right.
If it isn't liked, don't waste any more time/thought on it.

**Comment by m6502** [comment]
> > This has been supported in Microsoft Visual Studio since the 90s.
> 
> Maybe point out how to configure it to do it? Plus, if it is a setting that one has to turn on in VS, perhaps such a Notepad++ feature could use the same text in its UI for the feature.

To be honest I don't even remember ever having had to change anything to make it work that way. It's just the way it's ever worked for me, but I'll search for the specific option and post an update here.

**Comment by m6502** [comment]
To be honest I find these two features, the caret wrapping to the end or start of another line, and virtual space, to be two separate things and I don't know why Microsoft decided to group them. I have added two separate checkboxes, one for each feature, but if there's a good reason for them to be together and just disable the position warp if virtual space is enabled I can change it and submit only one pull request for both.

**Comment by alankilborn** [comment]
>although I don't see why these two should be really related one to another

Well, one thought on that would be if you're holding down the right arrow, moving infinitely into virtual space, there is no opportunity to ever get to the next line via this "wrapping".  But, yea, really seem like unrelated features...

So would you advocate a similar tying together of these features if both are implemented in Notepad++?  Probably not.

**Comment by alankilborn** [comment]
Oh, I see you already answered that with:

>I have added two separate checkboxes, one for each feature

**Comment by m6502** [comment]
> Well, one thought on that would be if you're holding down the right arrow, moving infinitely into virtual space, there is no opportunity to ever get to the next line via this "wrapping". 

Maybe that's the reasoning behind it. Disabling the wrap completely when virtual space is enabled would ensure the behaviour works the same for both directions of horizontal movement: either it does wrap, or it doesn't.

For the sake of completeness, I launched CodeWarrior and verified it does exactly the same: Virtual space and line wrapping go hand to hand there too.

Seen that way I think it would make sense for me to rework this option into the virtual space mode and doing only one pull request.

**Comment by m6502** [comment]
The pull request for this and #11443 is there now: https://github.com/notepad-plus-plus/notepad-plus-plus/pull/11452
