### ISSUE TITLE
End line character changes after pressing Enter key

### ISSUE THREAD

**Issue by mrrezaie** [notepad-plus-plus/notepad-plus-plus#11453]
### Description of the Issue
The end line character changes to something other than the defined format.

### Steps to Reproduce the Issue
1.  Change the format of ending line to **Windows (CR LF)**
2.  Edit the text and press Enter key

### Expected Behavior
When I select the **Windows (CR LF)** format, I would expect the ending line character remains **CR LF** after editing the file (pressing Enter). 

### Actual Behavior
The end line character of the new line changes to **CR**. 
I should re-change the format to fix it.

My file:
![Screenshot 2022-03-30 161105](https://user-images.githubusercontent.com/38867713/160828455-e170343b-3fee-4436-9feb-81a818bd6375.png)

After pressing Enter key:
![Screenshot 2022-03-30 161159](https://user-images.githubusercontent.com/38867713/160828496-9f05ce47-5cff-4790-975c-a0b7c52bba4f.png)

Windows 10
Npp v.8.3.3

**Comment by alankilborn** [comment]
@mrrezaie 

Please provide your complete _Debug Info..._ (see the `?` menu)

Step 1 may be flawed as it doesn't say what the line-ending format was before changing it.

I cannot repro this issue on:

Notepad++ v8.3.3   (64-bit)
Build time : Mar 13 2022 - 17:20:02
Path : C:\...\Releases\npp.8.3.3\npp.8.3.3.portable.x64\notepad++.exe
Command Line : -multiInst
Admin mode : OFF
Local Conf mode : ON
Cloud Config : OFF
OS Name : Windows 10 Enterprise (64-bit)
OS Version : 2009
OS Build : 19042.1526
Current ANSI codepage : 1252
Plugins : mimeTools.dll NppConverter.dll NppExport.dll

**Comment by mrrezaie** [comment]
Notepad++ v8.3.3   (32-bit)
Build time : Mar 13 2022 - 17:11:10
Path : F:\Notepad++\notepad++.exe
Command Line : "C:\Users\mrr\Desktop\One click.cmd"
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 10 Home (64-bit) 
OS Version : 2009
OS Build : 19044.1620
Current ANSI codepage : 1252
Plugins : ComparePlugin.dll mimeTools.dll NppConverter.dll NppExec.dll NppExport.dll Python Indent.dll 

Even I change the format initially, this happens.

**Comment by mrrezaie** [comment]
Please find the attached video:

https://user-images.githubusercontent.com/38867713/160834228-7d8f4d67-55d9-497d-a4d2-44a6251b64a6.mp4

**Comment by alankilborn** [comment]
Does not reproduce from me, per the description and the video, on:

Notepad++ v8.3.3   (32-bit)
Build time : Mar 13 2022 - 17:11:10
Path : C:\...\Releases\npp.8.3.3\npp.8.3.3.portable\notepad++.exe
Command Line : -multiInst
Admin mode : OFF
Local Conf mode : ON
Cloud Config : OFF
OS Name : Windows 10 Enterprise (64-bit) 
OS Version : 2009
OS Build : 19042.1526
Current ANSI codepage : 1252
Plugins : mimeTools.dll NppConverter.dll NppExport.dll

**Comment by alankilborn** [comment]
@mrrezaie Perhaps try without the extra plugins?

**Comment by Yaron10** [comment]
@mrrezaie,

The "Redo" button is enabled In your video.
Can you reproduce the issue on opening a file and *doing only what's shown in the video*?

**Comment by mrrezaie** [comment]
Thanks for your reply. I tested several files and still this happens. Please find the attached video.

https://user-images.githubusercontent.com/38867713/160924571-3ed40572-2a1c-4718-8374-12c37de1db73.mp4

**Comment by Yaron10** [comment]
@mrrezaie,

Thank you for testing it again and uploading the video.

Like @alankilborn, I'm baffled.
Would you mind trying [a fresh portable version](https://notepad-plus-plus.org/downloads/v8.3.3/)?

**Comment by mrrezaie** [comment]
I just tested the portable version and it works well. Any idea why the installer has such behavior in my system?

**Comment by Yaron10** [comment]
I don't know. I've never used the installer.

Did the problem start after upgrading to a specific version?
Could you install v.8.0?

I'd also try deleting "config.xml" (in your AppData folder) and restart NPP.
@alankilborn could probably think of some other useful steps.

**Comment by alankilborn** [comment]
>@alankilborn could probably think of some other useful steps.

I'm fresh out of ideas. :(

**Comment by mrrezaie** [comment]
Portable version works well. If the problem is not reproducible, feel free to close this issue. 

Thanks for your time and endeavors.
All the Best,
Mohammadreza

**Comment by Yaron10** [comment]
I find this issue interesting and even intriguing.
It would be appreciated If you could investigate the problem a bit more.

If you don't have the time or energy, you can close the issue yourself.

Thank you and all the best.

**Comment by mrrezaie** [comment]
I just installed the latest version via installer and removed the following folder afterwards:
.\AppData\Roaming\Notepad++

This fixed the issue.

Apologies for taking your time. Have a great time.
