### ISSUE TITLE
NP++ and g-sync low fps / hz / monitor refresh rate

### ISSUE THREAD

**Issue by Xetaxheb** [notepad-plus-plus/notepad-plus-plus#11457]
### Description of the Issue

Having g-sync enabled and NP++ as active window reports 60? fps cap and nvidia responds appropriately. Turning "monitor technology" to 'fixed refresh' in nvidia control panel alleviates problem but is undesirable for obvious reasons.

Basically if I have NP++ as active window, regardless of what my hardware is capable of, the refresh rate of the monitor it is considered "on" by windows will drop to 60hz.... sort of? In actuality it has a bit of a spasm around 70hz. Seems to be related to g-sync (set to "g-sync compatible", 'vertial sync' setting in nvidia control panel makes no difference).
If the np++ window isn't "active", that is literally anything else is "active" even if np++ is completely visible still (such as clicking taskbar or desktop) then the refresh rate goes back to normal.
If the np++ window is considered "on another monitor" even if 49% of it is still visible on the main monitor, the refresh rate goes back to normal.

### Steps to Reproduce the Issue

1. Have a gsync capable monitor (and optionally a refresh rate display)
2. See difference between notepad++ active or inactive
(even looking at cursor movement "smoothness" there's a drastic difference)

### Expected Behavior

Notepad++ not to report refresh rate limitations

### Actual Behavior

Notepad++ drops monitor to 60hz~ making cursor appear choppy

### Additional notes
**I don't consider this an nvidia issue nor third-party "workarounds" worth talking about. 
This is a notepad++ issue from some part of the draw code and should be treated as such.**
Please don't reply if your only responses are to mention things outside of notepad++.

**Comment by rimrul** [comment]
> ### Additional notes
> **I don't consider this an nvidia issue [...] 
> This is a notepad++ issue from some part of the draw code and should be treated as such.**

What leads you to that conclusion? I don't think notepad++ even has a concept of FPS, so I consider this to likely be an issue between Nvidia and the Win32-Api.

**Comment by adriel-tech** [comment]
I have the same problem using a 165hz FreeSync monitor and a Nvidia card. @ItsOnlyBinary suggestion to turn of 'DirectWrite' stopped the flickering for me also.
