### ISSUE TITLE
FR: Disable automatic updates as installer option

### ISSUE THREAD

**Issue by alexgit2k** [notepad-plus-plus/notepad-plus-plus#11475]
### Description of the Feature Request
When installing Notepad++ the check for automatic updates is enabled, also when Notepad++ is deployed with the silent-switch (see [notepad-plus-plus/npp-usermanual/blob/master/content/docs/command-prompt.md#installer-options](https://github.com/notepad-plus-plus/npp-usermanual/blob/master/content/docs/command-prompt.md#installer-options)). So users see a message if an update is available, but are not able to update if they have not sufficient permissions.

Therefore I suggest an additional installer option to disable automatic updates at installation time, e.g.
* `/NUPD` : disables automatic updates

### Steps to Reproduce
1. Install notepad with silent-switch: `npp.Installer.exe /S`
2. Check Settings -> Preferences -> Misc, "Enable Notepad++ auto-updater"

**Comment by softyoda** [comment]
I would add my opinion on this issue instead of adding a new feature request.
I think the auto update should be disabled or as many other apps, quiet and auto install on restart of the app as the current behavior of multiple popup isn't desirable in my opinion.

**Comment by CennoxX** [comment]
This already exists and was recently documented at https://npp-user-manual.org/docs/command-prompt/#installer-options:
`npp.Installer.exe /noUpdater`
To enable auto-updater again, you'll have to install npp again though.
Can this issue be closed?

**Comment by alexgit2k** [comment]
Perfect, thank you very much! 😃 

I am closing it.
