### ISSUE TITLE
Dead code in StyleContext.cxx raising MSVC compiler warning

### ISSUE THREAD

**Issue by rdipardo** [notepad-plus-plus/notepad-plus-plus#11477]
### Description of the Issue
In older versions of Scintilla, [`StyleContext::GetCurrent`][1] made an internal call to a static `::getRange` function:

https://github.com/notepad-plus-plus/notepad-plus-plus/blob/a29cfa8d25a72f9e337ba1b6ed87e3fc723f99a2/scintilla/lexlib/StyleContext.cxx#L67-L69

Scintila 5.1.1 [removed it][2] in favour of [the `LexAccessor::GetRange` method][3].

It seems Notepad++ [patched it back in][4] during the recent Scintilla upgrade, even though `::getRange` is no longer used internally and is no longer reachable by any code outside `lexilla/lexlib/StyleContext.cxx` because of its static linkage.

Unless I'm missing something, neither Scintilla nor Notepad++ needs `::getRange` at all[^1]. Removing it will eliminate [a distracting compiler warning][5].

### Steps to Reproduce the Issue

    cd PowerEditor\visual.net
    msbuild /v:m /t:Lexilla /p:PlatformToolset=v141;Platform=x64;WindowsTargetPlatformVersion=%WindowsSDKVersion:~0,-1%

### Expected Behavior

No compiler warnings.

### Actual Behavior

     lexilla\lexlib\stylecontext.cxx(57, 13): warning C4505: 'getRange': unreferenced local function has been removed

### Debug Information

[^1]: A few older lexers implement their own "getRange" functions, all of them hidden by static linkage, e.g., [LexCOBOL], [LexOpal], [LexTACL], [LexTAL]

[1]: https://github.com/notepad-plus-plus/notepad-plus-plus/blob/04e17b7375545e395802fdec5eddcf4b1db801ab/lexilla/lexlib/StyleContext.cxx#L70-L72
[2]: https://github.com/ScintillaOrg/lexilla/commit/2b36c2ed3491838acb580d4ba52bd20eac2e4aea#diff-c4d70acf12a47fb8f463830f3f9546fe741b79278468239e541234a016a86278
[3]: https://github.com/ScintillaOrg/lexilla/blob/2b36c2ed3491838acb580d4ba52bd20eac2e4aea/lexlib/LexAccessor.cxx#L31
[4]: https://github.com/notepad-plus-plus/notepad-plus-plus/blob/04e17b7375545e395802fdec5eddcf4b1db801ab/lexilla/lexlib/StyleContext.cxx#L57-L68
[5]: https://github.com/notepad-plus-plus/notepad-plus-plus/issues/11401#issuecomment-1087831163

[LexCOBOL]: https://github.com/notepad-plus-plus/notepad-plus-plus/blob/04e17b7375545e395802fdec5eddcf4b1db801ab/lexilla/lexers/LexCOBOL.cxx#L68
[LexOpal]: https://github.com/notepad-plus-plus/notepad-plus-plus/blob/04e17b7375545e395802fdec5eddcf4b1db801ab/lexilla/lexers/LexOpal.cxx#L30
[LexTACL]: https://github.com/notepad-plus-plus/notepad-plus-plus/blob/04e17b7375545e395802fdec5eddcf4b1db801ab/lexilla/lexers/LexTACL.cxx#L85
[LexTAL]: https://github.com/notepad-plus-plus/notepad-plus-plus/blob/04e17b7375545e395802fdec5eddcf4b1db801ab/lexilla/lexers/LexTAL.cxx#L49

**Comment by ozone10** [comment]
Seems to be fixed with https://github.com/notepad-plus-plus/notepad-plus-plus/commit/100d45f7cf02812eebf8dbfb8af5a261e95750c5

**Comment by rdipardo** [comment]
> Seems to be fixed with [100d45f](https://github.com/notepad-plus-plus/notepad-plus-plus/commit/100d45f7cf02812eebf8dbfb8af5a261e95750c5)

Confirmed: https://github.com/notepad-plus-plus/notepad-plus-plus/commit/100d45f7cf02812eebf8dbfb8af5a261e95750c5#diff-da44f0e1e38ab1bc371aae9ebe4b604b19bfaed344ad858ecace106192b67d7cL57

Good :eyes:!
