### ISSUE TITLE
NOTEPAD ++ REPLACE DOES NOT WORK :(

### ISSUE THREAD

**Issue by Linscove** [notepad-plus-plus/notepad-plus-plus#11474]
### Description of the Issue

Notepad ++ replace does not work at all - it worked last time we used it.  then we updated - now it won't work.  we tried installing the older version - still will not work - I'm not a techie - very frustrated  :(

### Steps to Reproduce the Issue

1. 
2. 
3. 

### Expected Behavior
  Replace should work 

### Debug Information

Notepad++ v8.3.1   (64-bit)
Build time : Feb 13 2022 - 15:41:12
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 10 Enterprise (64-bit) 
OS Version : 2009
OS Build : 19043.1586
Current ANSI codepage : 1252
Plugins : mimeTools.dll NppConverter.dll NppExport.dll

**Comment by alankilborn** [comment]
>I'm not a techie

We can tell, you can't even write a bug report that can help someone solve your problem.
Sorry. :-(

**Comment by Linscove** [comment]
When I do a search to replace something like spelling error in names - like it shows Mcdonald and should be McDonald - or when trying to replace Wa with WA- it says there aren’t any and zero replacements.  The replace is not working at all.

**Comment by alankilborn** [comment]
Works for me:

![image](https://user-images.githubusercontent.com/77065706/161620229-a1855ea3-4d5c-4125-b2a9-54844572677a.png)

Maybe you can show exactly what you are doing?

**Comment by Linscove** [comment]
This is what I get.  

It does not find any of them.   


Linda

**Comment by alankilborn** [comment]
Well, again if you can't show more about exactly what you are doing, no one can help you.

**Comment by dail8859** [comment]
Please provide screenshots and steps to reproduce the issue.
