### ISSUE TITLE
Find dialog backward direction doesn't work

### ISSUE THREAD

**Issue by ft525** [notepad-plus-plus/notepad-plus-plus#11502]
### Description of the Issue
Open the find dialog `<Ctrl + F>`, press `<Shift>`, and click "Find Next" should find the previous one.
It doesn't work now.

### Debug Information
Notepad++ v8.3.3   (64-bit)

**Comment by alankilborn** [comment]
Impossible to solve or even comment on with the level of detail provided.

**Comment by jasonklas** [comment]
I can't reproduce this on Notepad++ v8.3.3 (64-bit).  It works for both left and right shift buttons for me.

**Comment by dfs-** [comment]
Do you perhaps have the search mode set to Regular Expressions? If so, searching backwards is disabled which can be seen by enabling two button mode.

**Comment by ft525** [comment]
> Do you perhaps have the search mode set to Regular Expressions? If so, searching backwards is disabled which can be seen by enabling two button mode.

Yes, I was. I tried the other modes, they do work,
This issue can be closed.
