### ISSUE TITLE
Framed Current Line option

### ISSUE THREAD

**Issue by shriprem** [notepad-plus-plus/notepad-plus-plus#11501]
### Change Request
It would be nice to have the **Framed Current Line** option in Notepad++ similar to the ones in Visual Studio or VS Code.

Currently it is achievable with either the [FWDataViz](https://github.com/shriprem/FWDataViz) plugin OR by running the following command with the [PythonScript]( https://github.com/bruderstein/PythonScript) plugin: `editor.setCaretLineFrame`.

The result would be something like:
[  _The clip below has line wrapping enabled on purpose. It is capturing the related settings line in NPP's config.xml._  ]

![image](https://user-images.githubusercontent.com/45252729/162333290-22e53d4d-f423-4f91-950b-3712a71395db.png)

---

### Preference dialog

In the Notepad++ Preferences dialog, this setting can be handled either with a checkbox or a horizontal slider control ranging between values 0 to 10. If we implement it with a checkbox, an ideal value to use with the `SCI_SETCARETLINEFRAME` call would be: 2

Mock screenshot with the new checkbox control in Preferences:

![image](https://user-images.githubusercontent.com/45252729/162334062-62c6cd89-a9c2-4245-8e9c-7545cbd4a6d6.png)

---

### Implementation

The current-line-framing feature is achievable via the Scintilla API function [SCI_SETCARETLINEFRAME](https://www.scintilla.org/ScintillaDoc.html#SCI_SETCARETLINEFRAME).

The _executing_ code for this new setting would be the last two lines below added inside Notepad_plus.cpp:
[ _The first two lines below are pre-existing, and are only indicated here for the location context._ ] 
```C++
...
	_mainEditView.execute(SCI_SETCARETLINEVISIBLE, svp._currentLineHilitingShow);
	_subEditView.execute(SCI_SETCARETLINEVISIBLE, svp._currentLineHilitingShow);

	_mainEditView.execute(SCI_SETCARETLINEFRAME, svp._currentLineFrameWidth);
	_subEditView.execute(SCI_SETCARETLINEFRAME, svp._currentLineFrameWidth);
...
```

Of course, there will be other minor additions to: Parameters.h, Parameters.cpp, preference.rc, preferenceDlg.cpp, config4zipPackage.xml. Plus, additions to unitTest scripts for functionList and xml.  Lastly, this will also impact various translation files.

**Comment by alankilborn** [comment]
>implement it with a checkbox, an ideal value to use with the SCI_SETCARETLINEFRAME call would be: 2

I find 2 to be too "heavy".  For me, 1 is ideal.

**Comment by vinsworldcom** [comment]
> > implement it with a checkbox, an ideal value to use with the SCI_SETCARETLINEFRAME call would be: 2
> 
> I find 2 to be too "heavy". For me, 1 is ideal.

Funny, I've been using PythonScript to set it to 3 for me.  I just looked 1 is barely noticeable for me.  Of course that probably has to do with my dark background and not much brighter / contrasted cursor line highlight / frame.  I'll bet a brighter color would be harsher at my current setting 3.

Maybe instead of a checkbox, it's a combo box or URL thingie like Auto-Complete:
![image](https://user-images.githubusercontent.com/9657169/162519191-4ff3e9e4-f76b-458c-b892-ea929cb78404.png)

This way the user can specify the frame size, with 0 frame size being disabled - current standard.

Cheers.

**Comment by shriprem** [comment]
Although I had earlier mentioned the alternative to use a slider control to specify the frame width, I was feeling a bit lazy to prepare a mockup for it. So, this should be the preferred implementation:

![image](https://user-images.githubusercontent.com/45252729/162534091-287d57bc-2027-4d33-a926-466bd13a14db.png)

#### P.S:
1. For the PythonScript command, I had omitted the integer width value in the command. So, it should be, for example: `editor.setCaretLineFrame(2)`.
2. A third alternative to achieve this currently is the excellent [NPPExec](https://github.com/d0vgan/nppexec) plugin. With NppExec, a sample command is: `sci_sendmsg 2705 3`, where the number 2705 is the message ID for `SCI_SETCARETLINEFRAME`, and '3' is the desired frame width.

**Comment by alankilborn** [comment]
I think the slider is better than "whatever that is" in the Auto-completion window.
It might be nice if one end of the slider had `-` and the other end `+` like the _Blink rate_ has `F` and `S`.
Is a number really needed to be shown?  To the user, the number doesn't mean as much as it does to the programmers.
Maybe if the slider is all the way to the "-" end, some static text saying "no frame" appears.
I don't think the tooltip is necessary, but I guess it is OK (but again it exposes a numeric value not useful to end-user).
It isn't clear to me that this is a current line frame.  It either needs to explicitly state that, or be grouped somehow with _Enable current line highlighting_.

Just ideas...

**Comment by alankilborn** [comment]
More: Are _Enable current line highlighting_ and the "Frame" mutually exclusive?  When I turn the frame on, the background color I had for current line disappears and the frame takes on that background color setting.  If so, UI design need to account for this.

**Comment by shriprem** [comment]
The numeric value appears on multiple sliders in the _Margins/Border/Edge_ section of the Preferences dialog. In fact, I clipped the image of one of those sliders and used it in the mockup.

If the _Enable current line highlighting_ is unchecked, the framing is automatically turned off by Scintilla. However for the users clarity, the _Frame Width_ slider should be disabled when the _Enable current line_ gets unchecked.

**Comment by alankilborn** [comment]
I suppose the numeric value is OK if it really means frame is N pixels wide.  I wasn't clear if this is truly the case from Scintilla docs.

**Comment by Yaron10** [comment]
How about a `Frame Only` CheckBox enabling/disabling the slider (**1** to 10)?
Wouldn't that be much clearer to the user?

**Comment by shriprem** [comment]
@Yaron10 , thanks for the RTL tips. It will help whoever will be eventually implementing this change.

For the slider, I think we should just display 'No Framing' when the slider is at zero, and display the numeric value  for slider positions 1 to 10 in the common static text control. An extra check box may actually confuse users since the slider's enabled state will then be dependent on two (i.e., _Enable current line highlighting_ & the proposed _Frame Only_) checkboxes.

**Comment by alankilborn** [comment]
> It will help whoever will be eventually implementing this change.

Why not YOU? 
:-)

**Comment by Yaron10** [comment]
@shriprem,

> An extra check box may actually confuse users since the slider's enabled state will then be dependent on two (i.e., Enable current line highlighting & the proposed Frame Only) checkboxes.

It's not that important. But...

_Slider only_.
- Default value must be 0.
- The user wants to test the new Frame - they have to slide.
- The user wants to toggle Frame *after selecting their desired value* - they have to slide.

_Slider + `Frame Only`_.
- Default can be 2.
- The user wants to test the new Frame - they only need to check.
- The user wants to toggle Frame *after selecting their desired value* - they only need to check/uncheck.

But there's indeed an advantage in _Slider only_: less controls and parameters to read/right.

Either way, `Frame Only` is important as `Frame` might imply "Highlight the entire line and add a frame".

***

> Why not YOU?
:-)

I second that. But no pressure at all. :)

**Comment by shriprem** [comment]
@Yaron10 ,
> Either way, Frame Only is important as Frame might imply "Highlight the entire line and add a frame".

Your points are quite persuasive. Unless anyone else can make a better case for _Slider Only_, I think we should go with _Frame Only + Slider_ combo.

---

@alankilborn 
> I suppose the numeric value is OK if it really means frame is N pixels wide. I wasn't clear if this is truly the case from Scintilla docs.

Indeed, the values correspond to the pixel width of the frame. While verifying this, I found that `SCI_SETCARETLINEVISIBLE` function maxes out at 6 pixels. Specifying a value higher than 6 still yields a 6-pixels-wide frame. So, the new NPP Preferences slider needs to have a max value of 6 as well.

**Comment by alankilborn** [comment]
>less controls and parameters to read/right

+1 if less controls makes it clearer/easier for users
-1 if less controls makes it easier for programmers but less clear for users
:-)

**Comment by Yaron10** [comment]
@alankilborn,

You're absolutely right.

> less controls and parameters to read/right

And, my goodness, this is certainly NOT "right". :)
Edited.
