### ISSUE TITLE
shebang/xml heuristic not applied if default language is set

### ISSUE THREAD

**Issue by pryrt** [notepad-plus-plus/notepad-plus-plus#11504]
### Background

While participating in https://community.notepad-plus-plus.org/topic/22819/select-language-by-name-and-not-by-extension , two issues came up that are related, but that I'll document as separate issues or requests.  (I think the fixes will be in different sections of code, though maybe they can actually be fixed simultaneously)

When a file with no extension is opened in Notepad++, then the program will run some first line heuristics, and files that start with unix-style shebang lines (like `#!/bin/bash` or `#!/usr/bin/env perl`) will switch to the language indicated by the shebang (Unix shell script or Perl source file in those two examples); or if it starts with `<?xml version="1.0" encoding="UTF-8"?>`, it will be interpreted as XML.

### Problem

This heuristic works as expected when the default language (Settings > Preferences > New File > Default Language) is set to None (Normal Text). However, if the default language is set to anything else, then the heuristic is not applied and the default language is always selected.  The expected behavior would be that the same heuristic is applied to files with no extension, whether the default language is set to None or to something else.

### Reproduce

1. Create the file
```
<?xml version="1.0" encoding="UTF-8"?>
<blah></endblah>
```
2. Save as `test`
3. Close the file
4. **Settings > Preferences > New File > Default Language > Ada** (or other language)
5. Open the file and look at the selected **Language**-menu (or the Language in the Status Bar)
   * **ACTUAL BEHAVIOR**: it opens as **Ada** file (follows the Default Language setting)
   * **EXPECTED BEHAVIOR**: it opens as an XML file, just like the it would if Default Language were **None (Normal Text)**

### Other

user \@franco-otaola determined the order of priority in https://community.notepad-plus-plus.org/post/75877:
1. extension of the file
2. default language
3. first line e.g. #!/bin/bash

In both of our expectations, this is not the desired behavior.  We would expect that if the heuristic (shebang or <?xml?>) applies to a default language of None (Normal Text) that it would also apply the same heuristic -- so in the ordered list, the priorities of #2 and #3 would swap, so it would go in order of extension, shebang/xml, then default.

(Obviously, I would expect that a file created with **File > New** would keep the default file type, even if the first line typed were a shebang or xml declaration.  And that if the user manually set **Language**, it should keep that.  It's just when reading a new file that has no extension that I would expect the order of priority in the decision process to change compared to what it is now.)

### Debug Info
```
Notepad++ v8.3.3   (64-bit)
Build time : Mar 13 2022 - 17:20:02
Path : C:\usr\local\apps\npp\npp.8.3.3.portable.x64\notepad++.exe
Command Line : -multiInst
Admin mode : OFF
Local Conf mode : ON
Cloud Config : OFF
OS Name : Windows 10 Enterprise (64-bit) 
OS Version : 2009
OS Build : 19042.1586
Current ANSI codepage : 1252
Plugins : mimeTools.dll NppConverter.dll NppExport.dll 
```

**Comment by pryrt** [comment]
For either of these issues, if you choose to not change the current behavior, I will just update the User Manual to document it.

**Comment by rdipardo** [comment]
I debugged this and in fact the language is always inferred by the leading bytes; but it's overwritten afterwards if the new buffer specifies a preferred language (i.e., anything other than plain text):

https://github.com/notepad-plus-plus/notepad-plus-plus/blob/7fa6fb083b0ab454be4a1565b8747732cdea9cc4/PowerEditor/src/ScintillaComponent/Buffer.cpp#L744-L746

It would be trivial to change the condition at line 745 so priority goes to the inferred language over the user preference.
Currently the opposite is true, and should probably stay that way. A deliberately set preference ought to be respected before an autodetection algorithm.

Now, as one user [has already pointed out][1], "plain text" is not actually a selectable choice of default "language": all paths lead to some kind of lexer. Changing _that_ behaviour would be welcome in cases where lexing a massive stream of markup degrades performance: #11319


[0]: https://github.com/notepad-plus-plus/notepad-plus-plus/commit/9ebb4b39f5b6341c246a3f25221b716d20b5d1df
[1]: https://community.notepad-plus-plus.org/topic/22658/how-to-prevent-auto-syntax-highlighting-for-files-with-xml-tag-in-first-line

**Comment by rdipardo** [comment]
> A deliberately set preference ought to be respected before an autodetection algorithm.

My mistake. Of course we're talking about an _existing_ source file, one with a prominent and distinctive byte pattern indicating what it contains. 

The [current logic][0] makes a flawed comparison between the loaded file and an instance of a *new file*. Assuming that `buf->getLangType() == L_TEXT` means the same thing as "no file extension" is plain wrong; every new `Buffer` object gets its `_lang` attribute automatically set by the preferred language &#x2014; for new files!

> It would be trivial to change the condition at line 745

And so it is:

```diff
diff --git a/PowerEditor/src/ScintillaComponent/Buffer.cpp b/PowerEditor/src/ScintillaComponent/Buffer.cpp
index d1437230..7a1df5b8 100644
--- a/PowerEditor/src/ScintillaComponent/Buffer.cpp
+++ b/PowerEditor/src/ScintillaComponent/Buffer.cpp
@@ -742,7 +742,7 @@ BufferID FileManager::loadFile(const TCHAR* filename, Document doc, int encoding
 		buf->setEncoding(-1);
 
 		// if no file extension, and the language has been detected,  we use the detected value
-		if (!newBuf->_isLargeFile && ((buf->getLangType() == L_TEXT) && (loadedFileFormat._language != L_TEXT)))
+		if (!newBuf->_isLargeFile && (!buf->isUntitled() && (loadedFileFormat._language != L_TEXT)))
 			buf->setLangType(loadedFileFormat._language);
 
 		setLoadedBufferEncodingAndEol(buf, UnicodeConvertor, loadedFileFormat._encoding, loadedFileFormat._eolFormat);

```

[0]: https://github.com/notepad-plus-plus/notepad-plus-plus/blob/7fa6fb083b0ab454be4a1565b8747732cdea9cc4/PowerEditor/src/ScintillaComponent/Buffer.cpp#L744-L746

**Comment by rdipardo** [comment]
I got this one wrong, but better late than never: https://github.com/notepad-plus-plus/notepad-plus-plus/pull/12236#issue-1384835936

**Comment by donho** [comment]
https://github.com/notepad-plus-plus/notepad-plus-plus/commit/af0bc2e113f4398ecf3104052a6fb23ffd9e3aef
