### ISSUE TITLE
Refinement of 'Replace' dialog

### ISSUE THREAD

**Issue by maettu-this** [notepad-plus-plus/notepad-plus-plus#11500]
Follow-up to https://github.com/notepad-plus-plus/notepad-plus-plus/issues/11494.

### Description of the Issue

- Why is `Backward direction` greyed out when using `Regular expression`? `Wrap around` is active.
- `. matches newline` seems a very particular behavior when being used to regular expression.

### Steps to Reproduce the Issue
`Search > Replace... > Regular expression`

### Expected Behavior
`Backward direction` is available also with `Regular expression`.
Explanation on `. matches newline`.

### Actual Behavior
`Backward direction` greyed out when using `Regular expression`.
`. matches newline` seems a very particular behavior.

### Debug Information

Notepad++ v8.2.1   (64-bit)
Build time : Jan 19 2022 - 18:43:05
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 10 Home (64-bit) 
OS Version : 2009
OS Build : 19044.1620
Current ANSI codepage : 1252
Plugins : CSScriptNpp.dll HexEditor.dll mimeTools.dll NppConverter.dll NppExport.dll

**Comment by alankilborn** [comment]
_Backward direction_ can be enabled; see user manual.
Recommend CLOSURE of this item.

**Comment by ArkadiuszMichalski** [comment]
https://npp-user-manual.org/docs/preferences/#preferences-for-advanced-users
