### ISSUE TITLE
In Save dialog, File name is highlighted but it is not where focus is

### ISSUE THREAD

**Issue by dabrams** [notepad-plus-plus/notepad-plus-plus#11517]
### Description of the Issue

On Windows, when you go to save a file as  a new type, the file save dialog opens with the filename highlighted in white text with a blue background indicating is it the active field.  If you use the dropdown to select a new file type, the file name is still highlighted but if you start to type a new filename it changes the file type (based on the letter you type) not the name.

When you change the file type, either the focus should be removed from the file name or the file name should retain the focus after the type dropdown is closed.

### Steps to Reproduce the Issue

1. Select File/Save as... with a file that already has a name - the filename textbox has the focus
2. Change the file type - notice the file name text entry is still highlighted 
3. Start typing as though you were entering a new file name.  The type changes

### Expected Behavior

I expect test entry to change the highlighted field (i.e., the file name).  (Most other program I tried remove the focus from the filename text entry box when the extension/type dropdown opens.)

### Actual Behavior

The file type (extension) changes.

### Debug Information

Notepad++ v8.3.3   (64-bit)
Build time : Mar 13 2022 - 17:20:02
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 10 Pro (64-bit) 
OS Version : 2009
OS Build : 19044.1586
Current ANSI codepage : 1252
Plugins : mimeTools.dll NppConverter.dll NppExport.dll

**Comment by Yaron10** [comment]
@dabrams,

@mere-human is aware of the issue.
He lives in Ukraine. Let's hope for peace there.

**Comment by donho** [comment]
@dabrams 
Sorry but I don't really get the correct behaviour you expected.
Could you elaborate it?

**Comment by Yaron10** [comment]
> Steps to Reproduce the Issue
>
>    Select File/Save as... with a file that already has a name - the filename textbox has the focus
    Change the file type - notice the file name text entry is still highlighted
    Start typing as though you were entering a new file name. The type changes

> Expected Behavior

> I expect test entry to change the highlighted field (i.e., the file name). (Most other program I tried remove the focus from the filename text entry box when the extension/type dropdown opens.)

**STR:**
Select File/Save as... with a file that already has a name - the filename textbox has the focus
Change the file type **using the mouse** - notice the file name text entry is still highlighted
Start typing as though you were entering a new file name. The type changes

**Expected:**
The file name selection should be removed as the "File Type" field has the focus.
***
**A similar case:**
Open the Save dialog with "Append extension" unchecked.
Check "Append extension" **using the mouse**.

**Result:**
The file name is selected.
This is confusing as the "Append extension" box has the focus.

**Expected:**
The file name selection should be removed.

**Comment by dabrams** [comment]
A dialog field should not be highlighted if it does not have the focus.

 

The correct behavior in Windows when you click on a dialog field is the blue highlight on the current active field should be removed and the new field should receive the focus AND the highlight to show it is the destination of keystroke input.  In this case, the extension (file type) field is receiving keystrokes because it has the focus, but the file name field is still highlighted. This indicates to me that any text I type will change the root filename. However, it does not, it changes the file type which still has the focus.

 

Here is what Notepad++ does:

 

https://www.dropbox.com/s/5mz2c5cn81xsvg5/What%20Notepad%2B%2B%20does.mp4?dl=0

 

Here is what other Windows applications do:

 

https://www.dropbox.com/s/im9zh6r0t0oo044/Windows%20standard%20behavior.mp4?dl=0

 

David
