### ISSUE TITLE
Feature request: Functions list default sorted

### ISSUE THREAD

**Issue by jcrmatos** [notepad-plus-plus/notepad-plus-plus#1151]
Hello,

Please consider changing the default of the Functions list to be sorted.
Now the default is unsorted (lists functions as they exist in the source from top to bottom), which doesn't help when searching for a specific function (which I think if the main purpose of the Functions list).

Thanks,

JM

**Comment by MAPJe71** [comment]
Duplicate or least related to: #98

**Comment by sasumner** [comment]
Closing this one as the newer #8787 covers it
