### ISSUE TITLE
Fatal crash of notepad plus plus on windows 11

### ISSUE THREAD

**Issue by AlexandrKozlovskiy** [notepad-plus-plus/notepad-plus-plus#11528]
When i try to open some file with npp on windows 11 i have fatal crash. In empty session all ok. If i open some file via npp i have crash too.

**Comment by AlexandrKozlovskiy** [comment]
Notepad++ v8.3.3   (64-bit)
Build time : Mar 13 2022 - 17:20:02
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : 
Admin mode : ON
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 11 (64-bit) 
OS Version : 2009
OS Build : 22000.438
Current ANSI codepage : 1251
Plugins : mimeTools.dll NppConverter.dll NppExport.dll

**Comment by donho** [comment]
Could you download and unzip the zip package here:
https://github.com/notepad-plus-plus/notepad-plus-plus/releases/download/v8.3.3/npp.8.3.3.portable.x64.zip
And try it again?

**Comment by ts-50** [comment]
What happens when you create a new file?
