### ISSUE TITLE
Saving a document using the colon symbol in the same led to the loss of the document

### ISSUE THREAD

**Issue by ErnestLB** [notepad-plus-plus/notepad-plus-plus#11521]
When you save a "new document", using a colon symbol (it does not happen if using comma or semicolon, not sure about other symbols) an empty file is created with the partial indicated name (until the semicolon), and the editor display a partial name (after the semicolon). When you close the document in the editor, you loss all the content. Due to the document was not saved on disk, only created an empty file with a partial name.

### Steps to Reproduce the Issue
1. New document
2. Write anything
3. Press the save button
4. The "save as" dialog appears
5. Choose for example the name "AB: CD"
6. Press the save button

### Expected Behavior
A file with the choose name to be created

### Actual Behavior
An empty file with a partial name is created.
All the content is lost when close the document in the editor.

### Debug Information

![step1](https://user-images.githubusercontent.com/66790256/162694657-c3803fe4-3e9b-4107-8796-71859264127a.jpg)
![step2](https://user-images.githubusercontent.com/66790256/162694668-e4b21d23-b9ce-4219-9822-895a03dfdb31.jpg)
![step3](https://user-images.githubusercontent.com/66790256/162694684-2e6bd91e-8329-4b77-a810-31131aa5bf59.jpg)

**Comment by polluks** [comment]
Your filename is invalid: "In Win32 namespace: any UTF-16 code unit (case-insensitive) except `/\:*"?<>|` as well as NUL"
https://en.wikipedia.org/wiki/NTFS

**Comment by rdipardo** [comment]
If your Notepad++ version is at least 6.8.7, activate the "new style" save file dialog, as explained here: <https://stackoverflow.com/a/52163373>

<img width="630" alt="npp_687_file_prefs" src="https://user-images.githubusercontent.com/59004801/162722220-2282d2b0-6f50-456c-8c5b-cb28845bc430.png">

Your screen capture shows the "old" file dialog (before [Vista]), which may not be doing proper file name validation.

[Vista]: https://github.com/notepad-plus-plus/notepad-plus-plus/pull/9378#issuecomment-757141575

**Comment by alankilborn** [comment]
Tested in N++ 8.4.4 (current version as of this writing) and could not repro any "loss of document".
Recommend CLOSURE of this item.

![image](https://user-images.githubusercontent.com/77065706/183642393-68bcecec-b1ff-45d8-ba71-f4cd66b0f1c6.png)
