### ISSUE TITLE
[v6.8.6] duplicate language in menu

### ISSUE THREAD

**Issue by AyrA** [notepad-plus-plus/notepad-plus-plus#1152]
Today I tried to change some styles of the javascript language, because it bugs me to hell, that `null` and `undefined` are not colored as keywords. I did this once in the past and it worked fine for me. During an update of Notepad++ lately, the styles were reset. Since the decoloration of the two terms annoyed me again, I decided to add the keywords again to the list. This does not works. In the style configurator, Javascript is listed twice:

![New definition at thwe bottom of the list](http://i.imgur.com/gvrd3Lf.png)

![Old definition in its alphabetical location](http://i.imgur.com/J2nuyMe.png)

The problem I have now is, that changes to the new definition (first image) are saved in the old one (second image), but when displaying a file, then the new one is used for styling. In the language drop down menu, Javascript is listed only once.

Is there a way I can easily reset all styles to default? I have made only a few changes, so resetting is fine for me.

**Comment by AyrA** [comment]
Update:

I have tried to solve this issue by deleting my **stylers.xml** in the appdata folder. This did not helped. However, now the old one of the two Javascript definitions has been renamed to "Javascript (embedded)". Defining my own keywords still does not helps.

**Comment by AyrA** [comment]
Thank you very much

**Comment by GreatLeaderTechnus** [comment]
I have this same issue....
