### ISSUE TITLE
`VERSION_VALUE` should always have at least 3 digits

### ISSUE THREAD

**Issue by rdipardo** [notepad-plus-plus/notepad-plus-plus#11535]
### Description of the Issue

N++'s [`VERSION_VALUE` resource string][0] sometimes has 3 digits, e.g. "8.33". 
But with every "minor version" bump, it's reduced to only 2 digits, e.g. "8.4".
After N++ 8.3.3 comes 8.4, then, perhaps, 8.4.1, then 8.5, etc.

If a plugin is concerned about compatibility, it has to know that 4 comes *after* 33, and 5 comes *after* 41. 
This is a headache for developers targeting N++'s plugin API [^1] [^2] [^3].

#### Method 1

1. Install Notepad++ 8.4 (64-bit)
2. Install HTML Tag (1.2.2)
3. Start Notepad++
4. Notice that HTMLTag thinks Notepad++ is incompatible:

![htmltag_v122_x64](https://user-images.githubusercontent.com/59004801/165362920-2b442b26-d49c-421d-b845-11294d68867d.png)

5. Read [this explanation](https://community.notepad-plus-plus.org/topic/22503/new-version-of-html-tag/8) of what went wrong

#### Method 2

1. Clone the Notepad++ source tree
2. Edit `PowerEditor/src/resource.h` by adding a `0` to the end of the `VERSION_VALUE` string: `#define VERSION_VALUE "8.40"`
3. Repeat steps 2-3 of *Method 1*
4. No more issue!

#### Method 3

1. Write a plugin that calls into the [`NPPM_GETNPPVERSION` API][1]
2. Build 4 different Notepad++ binaries with 4 different strings assigned to `VERSION_VALUE`
3. Run the plugin in each version and note the results:

| HIWORD | LOWORD | N++ version |
| :---:  | :---:  |  ---------: |
| 8      | 33     | 8.3.3       |
| 8      | **4**  | 8.4         |
| 8      | 41     | 8.4.1       |
| 8      | **5**  | 8.5         |

### Expected Behavior

Every version string has at least 3 digits, e.g.,

N++ 8.4 -> `#define VERSION_VALUE "8.40"`
N++ 8.5 -> `#define VERSION_VALUE "8.50"`

What does the plugin see now?

| HIWORD | LOWORD | N++ version |
| :---:  | :---:  |  ---------: |
| 8      | 33     | 8.3.3       |
| 8      | **40** | 8.4         |
| 8      | 41     | 8.4.1       |
| 8      | **50** | 8.5         |

33 . . . 40 . . . 41 . . . 50 . . . 

Every new version has a low word greater than the last one! Easy!

### Actual Behavior

33 . . . 4 . . . 41 . . . 5 . . . 

### Debug Information

Notepad++ v8.4   (64-bit)
Build time : Apr 20 2022 - 03:31:06
Path : C:\bin\npp_8.4\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : ON
Cloud Config : OFF
OS Name : Windows 11 (64-bit) 
OS Version : 2009
OS Build : 22000.651
Current ANSI codepage : 1252
Plugins : HTMLTag.dll mimeTools.dll NppConverter.dll NppExport.dll 

[^1]: https://github.com/notepad-plus-plus/notepad-plus-plus/issues/11431
[^2]: https://github.com/nvaccess/nvda/pull/13382#issuecomment-1049294658
[^3]: https://github.com/oleg-shilo/cs-script.npp/issues/64#issuecomment-1108448994

[0]: https://github.com/notepad-plus-plus/notepad-plus-plus/blob/master/PowerEditor/src/resource.h#L24-L25
[1]: https://github.com/notepad-plus-plus/npp-usermanual/blob/master/content/docs/plugin-communication.md#nppm_getnppversion
[2]: https://github.com/notepad-plus-plus/notepad-plus-plus/blob/f6ade2c9157e7c6a56c95dfd04c436df512ca028/PowerEditor/src/resource.h#L26-L27

**Comment by alankilborn** [comment]
Probably this is very naïve, but if LOWORD is <= 9, can't it just be considered as multiplied by 10?  E.g., 4 becomes 40, etc.  As this in no way affects me directly, and thus I may not have a complete understanding of the issue...I await the flames. :-)

**Comment by rdipardo** [comment]
> I may not have a complete understanding of the issue

Basically, we have  a "descriptive" version *string* doing double duty as a version *number*:

https://github.com/notepad-plus-plus/notepad-plus-plus/blob/32580e6a800130b3abfa8dd2ecbf6284a3bda97a/PowerEditor/src/NppBigSwitch.cpp#L1262-L1283

If it was always a string, the current "system" would work fine given ASCII character order:

~~~sh-session
$ tree --sort=name
.
├── 8.33
├── 8.4
├── 8.41
├── 8.5
└── 8.51
~~~

Granted, a plugin can always convert the high and low values returned by NPPM_GETNPPVERSION to strings and (reliably) sort them &#x2014; as strings! It's just more effort and CPU cycles for something that should be quite simple.

**Comment by rdipardo** [comment]
Here we go again . . . 
https://github.com/notepad-plus-plus/notepad-plus-plus/blob/f6ade2c9157e7c6a56c95dfd04c436df512ca028/PowerEditor/src/resource.h#L26-L27

**Comment by Leonard-The-Wise** [comment]
As a quick fix for your plugin, you can use my method for picking Notepad++ version. I get it straight from the executable, so it never misses.

This sample here tells you how to do that.
https://iq.direct/blog/336-code-sample-retrieve-c-application-version-from-vs-version-resource.html

So I've created my own class for that:
https://github.com/Leonard-The-Wise/NWScript-Npp/blob/master/src/Utils/VersionInfoEx.h
https://github.com/Leonard-The-Wise/NWScript-Npp/blob/master/src/Utils/VersionInfoEx.cpp

Only problem to portability of that code is: I'm using PCRE2 as regex engine for VersionInfoEx.cpp (right [here](https://github.com/Leonard-The-Wise/NWScript-Npp/blob/133154a9fb79450efed5757f42b6ed4b70a0014b/src/Utils/VersionInfoEx.cpp#L26)) because all of my project is based on PCRE2, but it should be very easy to port to any other regex engine, including std::regex.

Then, once you get the class running it is as simple as this:

``` C++
    // Pick current Notepad++ version 
    VersionInfoEx currentNotepad = VersionInfoEx(_pluginPaths["NotepadInstallExecutablePath"]);

    if (currentNotepad > "8.3.1")
    {
           ... do stuff
    }
```

Code sample [here](https://github.com/Leonard-The-Wise/NWScript-Npp/blob/133154a9fb79450efed5757f42b6ed4b70a0014b/src/PluginMain.cpp#L350).
Hope it helps.

Bye.

**Comment by pnedev** [comment]
Hi @donho ,

Thank you for the quick reaction. 👍 
This seems OK for me but it will work if we make the assumption that all Notepad++ versions will always have minor version numbers composed of just one digit. For example versions like 8.10.5 or 8.5.12 (you got it) will not be valid as those would lead to LOWORD 105 and 512 respectively and those will conflict with 8.1.0.5 and 8.5.1.2.

**Comment by pnedev** [comment]
OK, great news, Don! 👍 
The retro-compatibility approach seems right as well.

Can you tell me when are you planning to release 8.4.1 ?

**Comment by donho** [comment]
@pnedev I just implemented `#define NPPM_GETNPPVERSION_NEW (NPPMSG + 109)`

Could you check ;
http://download.notepad-plus-plus.org/repository/8.x/8.4.2.RC/

Please confirm me if it works - if it is, please update your plugin with this new change - I will update PluginList in newest v8.4.1 which will be out in 2 days.

**Comment by rdipardo** [comment]
@donho, @pnedev,
> BTW for the retro-compatibility, it'll be the new API `NPPM_GETNPPVERSION_NEW`, and the old one will be renamed to `NPPM_GETNPPVERSION_DEPRECATED` (its value will remain the same).
>

### 👎🏼 
That means every single plugin using the `NPPM_GETNPPVERSION` message needs to update its API !!!
The safer new version values should be available *right now*, by calling into `NPPM_GETNPPVERSION`, not into a new API that will take months to integrate into all the plugins (and plugin templates[1]) already out there !!! 
#### The old system *never* worked as it was supposed to. It needs *fixing*, not *replacement* !!!!

---
[1] See:
- https://github.com/npp-plugins/plugintemplate
- https://github.com/kbilsted/NotepadPlusPlusPluginPack.Net
- https://sourceforge.net/projects/npp-plugins/files/DelphiPluginTemplate
- https://bitbucket.org/rdipardo/delphiplugintemplate

**Comment by donho** [comment]
@rdipardo 
The thing is, we don't know how the plugins manage the LOWORD - it could compare v8.4 with v8.4.1 in the following way:
8.4 < 8.41

So IMO, it'll be safer ti introduce a new API.

**Comment by donho** [comment]
After some thinking, I'm not sure if this issue is a real issue.

@rdipardo  & @pnedev 
Could you show me (with link of your source code) how you compare Notepad++ minor part version?

**Comment by donho** [comment]
After some thinking, I'm not sure if this issue is a real issue.

@rdipardo  & @pnedev 
Could you show me (with link of your source code) how you compare Notepad++ minor part version?

**Comment by rdipardo** [comment]
@donho,
> The thing is, we don't know how the plugins manage the LOWORD - it could compare v8.4 with v8.4.1 in the following way: 8.4 < 8.41
> 

     High     Low    Compatible?
    -----   -----   ------------
        8       0          False
        8       1          False
        8      11          False
        8      12          False
        8      13          False
        8      14          False
        8      15          False
        8      16          False
        8      17          False
        8      18          False
        8      19          False
        8     191          False
        8     192          False
        8     193          False
        8       2          False
        8      21          False
        8       3           True
        8      31           True
        8      32           True
        8      33           True
        8       4           True

> So IMO, it'll be safer ti introduce a new API.

410 > 4
411 > 410
. . .

Anything gonna break ?

**Comment by donho** [comment]
@rdipardo 
I'm wondering if it's really simple & intuitive to "fix" NPPM_GETNPPVERSION or  add a new API for having always 3 digits in LOWORD.

Here's the scenario that I've got if we use the " always 3 digits" system:
My plugin MIME Tools of version 3.0 will work with Notepad++ v8.3.3, but not with v8.4. So I want to release a new version 3.1 to make sure it works only with Notepad++ v8.4 and after.
What I want to compare with LOWORD of NPPM_GETNPPVERSION's result must be **400** - which is not intuitive at all.

The good way might document (with comment) more detail for user to know how to compare with LOWORD of NPPM_GETNPPVERSION's result - declaring a double to form integer part and fractional part for comparing with 8.4

So there's no bug on NPPM_GETNPPVERSION API (for me), but at least we can always add a new argument "ADD_ZERO_PADDING" into NPPM_GETNPPVERSION to get the format you expect. What do you think?

**Comment by Leonard-The-Wise** [comment]
Pardon the intromission, but wouldn't the easiest fix for this would be a new API that returns a 64bit `long long` variable?
This way you have 16 bits for each version part and can assign anything up to 65535 to any version part. This is the way Microsoft does it - but they actually codify the 64bits variable into a struct like:

```
struct Version {
DWORD Major;
DWORD Minor;
}.
```

OR

If you want to keep the int format, at least change to unsigned int and use one byte for each part. Since int has 32bit, it can go up to 255.255.255.255 version. And comparisons would be as easy as comparing if A > B.

Just my 2 cents on this.

**Comment by donho** [comment]
@Leonard-The-Wise 
Yes why not? Then it needs absolutely a new API.

**Comment by pnedev** [comment]
> @pnedev I just implemented `#define NPPM_GETNPPVERSION_NEW (NPPMSG + 109)`
> 
> Could you check ; http://download.notepad-plus-plus.org/repository/8.x/8.4.2.RC/
> 
> Please confirm me if it works - if it is, please update your plugin with this new change - I will update PluginList in newest v8.4.1 which will be out in 2 days.

Don, I'll check it as soon as I can, thanks.

**Comment by pnedev** [comment]
> @rdipardo The thing is, we don't know how the plugins manage the LOWORD - it's possible to compare v8.4 with v8.4.1 in the following way: 8.4 < 8.41
> 
> So IMO, it'll be safer ti introduce a new API.

In my code if I want to check if Notepad++ version is above certain number I do the reverse of getting the HIWORD and LOWORD:
lets say the threshold version is 8.3.3. I create my DWORD threshold value like (8 << 16) | 33 and check if NPPM_GETNPPVERSION returnts value that is below the threshold:
`( (8 << 16) | 33) < NPPM_GETNPPVERSION `

**Comment by donho** [comment]
@pnedev 
> Don, I'll check it as soon as I can, thanks.

Please check here:
https://github.com/notepad-plus-plus/notepad-plus-plus/pull/11648

Use with or without option ADD_ZERO_PADDING when you call NPPM_GETNPPVERSION.

**Comment by rdipardo** [comment]
> Use with or without option ADD_ZERO_PADDING to get the format you want when you call NPPM_GETNPPVERSION.

See https://github.com/notepad-plus-plus/notepad-plus-plus/pull/11648/files#r867413977
As long as it doesn't require any interface changes, I can live with it.

My own plugins have [something much simpler][0] than @pnedev's algorithm:

1. HIWORD > 8 OK
2. HIWORD = 8 ? then:
   - reject versions 8.1.9.1, 8.1.9.2, 8.1.9.3, i.e., LOWORD &#x2208; { 191, 192, 193 }
   - *accept* versions > 8.2.1, i.e., LOWORD > 21 *or* versions 8.3 - 8.9, i.e,  LOWORD &#x2208; { 3, 4, 5, 6, 7, 8, 9 }

[0]: https://bitbucket.org/rdipardo/delphiplugintemplate/src/e753191a505927901ee85415a53f3b1d40d8ffee/Source/Units/Common/NppPlugin.pas#lines-291

**Comment by pnedev** [comment]
> @pnedev
> 
> > Don, I'll check it as soon as I can, thanks.
> 
> Please check here: #11648
> 
> Use with or without option ADD_ZERO_PADDING to get the format you want when you call NPPM_GETNPPVERSION.

I tested one of my plugins with 8.4.1 RC - the ADD_ZERO_PADDING works perfectly, thanks!
