### ISSUE TITLE
Dark Mode for plugins

### ISSUE THREAD

**Issue by Leonard-The-Wise** [notepad-plus-plus/notepad-plus-plus#11546]
Hi,

Recently, I've added Dark Mode support for my Notepad++ Plugin - NWScript Tools (will be released in a couple days from now). Screenshot here:

![image](https://user-images.githubusercontent.com/99574879/163735029-6b0cf75e-921e-4ff9-b4d4-611526895b32.png)

The only problem: currently I have no way of detecting whether Notepad++ is using Dark Mode or not. I've implemented a "Crude" detector, based on fetching the window's pixels colors and setting dark mode according to the pixels luminosities when scintilla window finishes painting... sounds reasonable, but this method is glitchy, because not every time I can fetch the right pixels, specially when the user is actively resizing windowzes (if they do it abruptly the function will fail), also on minimize/maximize events and also on high DPI settings - specially if multimonitors are involved with different DPI for each.

Sample of the glitch:

![image](https://user-images.githubusercontent.com/99574879/163735089-adee61b0-216e-413f-8df5-45a7be46a7d4.png)

So, a definitive solution is to modify Notepad++ to support a couple of new messages. One to allow plugins to query for Dark Mode status, other is a notification of when Notepad++ changes Dark Mode settings.

I already implemented the changes. This issue is to be associated with my pull request. :)

PS: I also took the freedom to fix a glitch with `NppDarkMode.cpp` that would cause any Checkbox styled with `BS_PUSHLIKE` to be drawn incorrectly. The bug is because any checkbox will be `subclassed`, and the `BS_PUSHLIKE` checkboxes don't need a `subclass`, just need a `SetWindowTheme` to work. Currently I don't know of any control in Notepad++ with this issue, but if you decide to add in the future it will be already issue-free with this pull request. Also, Tab controls subclasses work for TCS_BOTTOM style (tested on my plugin, see pictures above), so I removed the restriction from the function.

Thanks.

**Comment by Leonard-The-Wise** [comment]
Oh, I realized that this request wouldn't be complete without any means to query for the Dark Mode tone also. Added to pull request.

**Comment by shriprem** [comment]
>Oh, I realized that this request wouldn't be complete without any means to query for the Dark Mode tone also.

That might work for the standard tones. But what about for the "Customized tone" (for which the colors could be any random value)? So, a more complete query should accept a pointer to a `Colors` struct and fill in the ten colors defined for the currently selected tone, be it a standard tone or a "Customized tone".

I am referring to this struct in `NppDarkmode.h`:
```C++
   struct Colors
   {
      COLORREF background = 0;
      COLORREF softerBackground = 0;
      COLORREF hotBackground = 0;
      COLORREF pureBackground = 0;
      COLORREF errorBackground = 0;
      COLORREF text = 0;
      COLORREF darkerText = 0;
      COLORREF disabledText = 0;
      COLORREF linkText = 0;
      COLORREF edge = 0;
   };
```

**Comment by Leonard-The-Wise** [comment]
Hmm, good hint. I didn't notice the customized tones before. Updated the pull request to get colors in a more color-scheme agnostic way.

**Comment by CennoxX** [comment]
I've had the same problem, my (bad) work around was using `NPPM_GETEDITORDEFAULTBACKGROUNDCOLOR`, but dark background is not the same as using dark mode, so this wasn't sufficiant.

**Comment by donho** [comment]
@Leonard-The-Wise 
> PS: I also took the freedom to fix a glitch with NppDarkMode.cpp that would cause any Checkbox styled with BS_PUSHLIKE to be drawn incorrectly. The bug is because any checkbox will be subclassed, and the BS_PUSHLIKE checkboxes don't need a subclass, just need a SetWindowTheme to work. Currently I don't know of any control in Notepad++ with this issue, but if you decide to add in the future it will be already issue-free with this pull request.

Not sure that I understand you:
So can the bug reproducible? If yes, could you provide the instructions to reproduce it?

**Comment by Leonard-The-Wise** [comment]
@donho 

Sure.

1) Create any Checkbox control with the BS_PUSHLIKE style (so it will appear as a push button instead of a checkbox). 
2) Call `NppDarkMode::autoSubclassAndThemeChildControls(_hWindow)`

Example:

``` C++
...
HWND newCheckbox = CreateWindow(WC_BUTTON, TEXT("Testing"), WS_CHILD | WS_VISIBLE | WS_TABSTOP | BS_AUTOCHECKBOX | BS_PUSHLIKE, rc.left, rc.top, rc.right - rc.left, rc.bottom - rc.top, _hSelf, 0, _hInst, 0);

NppDarkMode::autoSubclassAndThemeChildControls(_hSelf);
...
```

Here are samples of my plugin with and without the patch:

1) Normal behavior (with patch):

![image](https://user-images.githubusercontent.com/99574879/164788444-10c16955-439b-4320-8c39-60c0b0b9527e.png)

2) What is currently going on (without patch):

![image](https://user-images.githubusercontent.com/99574879/164786697-90b652e8-5d8e-4b6b-b83d-abd993283b88.png)


PS: Notice that my buttons are using bitmaps instead of text, so only the checkbox appears where the button should be.
