### ISSUE TITLE
Hi, Love your Notepad, but something is missing in it for me...

### ISSUE THREAD

**Issue by MrTatiTunes** [notepad-plus-plus/notepad-plus-plus#11542]
### Description of the Issue

I am missing possibility of edition of CSV files, as table text, edit columns and again save it as CSV. Excel destroys any text starting with 0, or maybe I do not know how to use it. ;) CSV database for contacts have phones starting with 0, and it is pointless to edit them in Excel, but can be close to Notepad and extend its ability to really original context.

### Steps to Reproduce the Issue

1. no thi ng to rep ro duce
2. 
3. 

### Expected Behavior

look at it ;)

**Comment by alankilborn** [comment]
Recommend CLOSURE due to confusing nature of the request and Notepad++ design goals which make it not go too far into the realm of a dedicated CSV editor.

**Comment by ArkadiuszMichalski** [comment]
Specific requirements are the space for plugins:
https://github.com/jokedst/CsvQuery
https://github.com/BdR76/CSVLint
