### ISSUE TITLE
Bug on save large XML files

### ISSUE THREAD

**Issue by marciordonez** [notepad-plus-plus/notepad-plus-plus#11552]
### Description of the Issue
Bug on save large XML files. Notepad++ freezes

### Steps to Reproduce the Issue

1. Open a XML file with more than 5000 lines
2. Alter any line
3. Freeze after save. Needed to force close.

### Expected Behavior

Only Save

### Actual Behavior

Notepad++ freezes

### Debug Information

Notepad++ v8.3.3   (64-bit)
Build time : Mar 13 2022 - 17:20:02
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : 
Admin mode : ON
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 10 Enterprise (64-bit) 
OS Version : 1903
OS Build : 18362.356
Current ANSI codepage : 1252
Plugins : ComparePlugin.dll mimeTools.dll NppConverter.dll NppExport.dll NPPJSONViewer.dll XMLTools.dll 

The problem is XML Tools plugin (v3.1.1.12). After removing it worked.

**Comment by tarkett2018** [comment]
You must upgrade the XML Tools plugin to 3.1.1.13. See https://github.com/morbac/xmltools/issues/152

**Comment by ArkadiuszMichalski** [comment]
If the mentioned new version does not fix the problem, let us know.
