### ISSUE TITLE
Version 8.3.X bug with NVDA 2021.3.4 on Windows 10

### ISSUE THREAD

**Issue by shadow2560** [notepad-plus-plus/notepad-plus-plus#11565]
### Description of the Issue
Notepad++ force close when a file is loaded (tested with a 3 KO file minimum, not tested with less, open an empty file doesn't seems to cause this bug).

### Steps to Reproduce the Issue
1. Install Notepad++ and NVDA.
2. Open a file in Notepad++.

### Expected Behavior
File should open and I can edit or modify what I want.

### Actual Behavior
Notepad++ launch, stay open for a short time (I can't do anything in the editor) and then it close automaticaly.

### Debug Information
Notepad++ v8.3.3   (64-bit)
Build time : Mar 13 2022 - 17:20:02
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 10 Enterprise (64-bit) 
OS Version : 1909
OS Build : 18363.2212
Current ANSI codepage : 1252
Plugins : mimeTools.dll NppConverter.dll NppExport.dll 

With Notepad++ version 8.2.1 this bug is not present, it start from 8.3.1 at least.

**Comment by shadow2560** [comment]
Thanks for the infos and sory for the duplicate issue.

**Comment by rdipardo** [comment]
Using NVDA version 2022.1 may resolve this issue, as reported [here](https://github.com/notepad-plus-plus/notepad-plus-plus/issues/11629#issuecomment-1135434814).
