### ISSUE TITLE
Exclude filter must prune early

### ISSUE THREAD

**Issue by mvorisek** [notepad-plus-plus/notepad-plus-plus#11571]
Filters set to `*.php !.git` in the `Find in Files` window must exclude also directories matching such exclude mask and prune early.

Currently, the `*.php !.git` example does not prune early and whole `.git` folder is scanned.

When an excluded directory is large, it takes notepad++ minutes to return the search results which makes it almost unusable for daily use, thus I would appretiate a priority fix for this issue.

Fixing this issue will also some workaround for:
- https://github.com/notepad-plus-plus/notepad-plus-plus/issues/9445
- https://github.com/notepad-plus-plus/notepad-plus-plus/issues/11150
- https://github.com/notepad-plus-plus/notepad-plus-plus/issues/10929
- https://github.com/notepad-plus-plus/notepad-plus-plus/issues/9456

as binary/hidden files are often in a few directories writing the exclusing masks using the `!` syntax is quite usable solution for the most usecases /wo any extra GUI change needed.

**Comment by dfs-** [comment]
`!.git\` should be the way to go. 

https://npp-user-manual.org/docs/searching/

This manual explains how filtering using find in files works and that exclude directories always habe to start with `!` and end with `\`.

**Comment by mvorisek** [comment]
I tested `* !.git\` and git folder is still seached:

![image](https://user-images.githubusercontent.com/2228672/164942756-5c20399a-aa7b-4a8d-8933-f5191a6db7bc.png)

**Comment by maddes-b** [comment]
According to the [docs](https://npp-user-manual.org/docs/searching/#find-in-files-tab) with N++ 8.2 or laterfolders can be specified .
Folders have to be prefixed with backslash `\`, if this filter should be applied on all levels then add `+` before the backslash.
To exclude all .git folder specify: `!+\.git`

**Comment by mvorisek** [comment]
I have no N++ 8.2+ in reach now, but I am closing this issue, as I expected to be resolved as documented. If not, I or someone else can reopen.
