### ISSUE TITLE
Analyse Plugin missing

### ISSUE THREAD

**Issue by sterlingberger** [notepad-plus-plus/notepad-plus-plus#11578]
### Description of the Issue
Hi, my dev team uses the analyse plugin of notepad++ a lot. Lately I had an issue with version [Notepad++ 8.3.3 (Make Apps, not war)](https://notepad-plus-plus.org/downloads/v8.3.3/), wher the plugin does not show in plugin menu. The dll is present in the plugin folder. The plugin cannot be reinstalled from the "install plugin" menu (it's not listed).

### Steps to Reproduce the Issue
Download an older version of npp and install the plugin -> use it. Update to newest version -> plugin is gone and can't be installed again.

I'm not sure which version was the first that had the issue, but I rolled back to an older one and the plugin works fine again. I noticed the issue on multiple machines now, so I decided to report.

Anyway: npp is one of the most helpful tools out there, great job.

**Comment by chcg** [comment]
See https://sourceforge.net/p/analyseplugin/bugs/86/ an updated version of the plugin needs to be provided by the plugin author. Otherwise with N++ versions newer than 8.3.3 the plugin is disabled to avoid the crashes.
