### ISSUE TITLE
wrong emoji entered from windows 8 visual keyboard

### ISSUE THREAD

**Issue by hubaishan** [notepad-plus-plus/notepad-plus-plus#1157]
When entering emoji character from windows 8 visual keyboard (lies beside the clock), Wrong character is typed in (plain text/UTF8) document

**Comment by donho** [comment]
I believe this issue has been fixed since long time ago.
Update your Notepad++ to the latest version (v7.6.6).
If the issue persists, please create a new issue for it.
Thank you.
