### ISSUE TITLE
JavaScript "null" cannot be highlighted

### ISSUE THREAD

**Issue by ygoe** [notepad-plus-plus/notepad-plus-plus#11584]
### Description of the Issue
The JavaScript keyword `null` cannot be syntax-highlighted, even after manually adding it in the langs.xml file. It remains black.

### Steps to Reproduce the Issue
1. Create a new document
2. Switch content language to JavaScript
3. Type "null"

### Expected Behavior
blue colour

### Actual Behavior
black colour

### Debug Information
Notepad++ v8.3.3   (32-bit)
Build time : Mar 13 2022 - 17:11:10
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 10 Enterprise (64-bit) 
OS Version : 2009
OS Build : 19044.1586
Current ANSI codepage : 1252
Plugins : CustomizeToolbar.dll JSMinNPP.dll mimeTools.dll NppConverter.dll NppExport.dll NppSaveAsAdmin.dll XMLTools.dll

**Comment by ArkadiuszMichalski** [comment]
Works fine. Try with [portable version](https://github.com/notepad-plus-plus/notepad-plus-plus/wiki/Testing#using-the-latest-release-portable-version-of-notepad) to eliminate configuration problem.

![image](https://user-images.githubusercontent.com/2730894/166438321-9ed8e5f3-d06c-4d27-bd0b-90bd28b45f91.png)

**Comment by ygoe** [comment]
Thanks. Comparing the portable langs.xml with mine revealed a pretty mess so I deleted all JavaScript/JSON parts from mine and copied those of the portable file in. Now it works.
