### ISSUE TITLE
Column Copy/Paste no longer functioning as expected

### ISSUE THREAD

**Issue by pantsmann** [notepad-plus-plus/notepad-plus-plus#11586]
### Description of the Issue
Been a Notepad++ user for years. I used to be able to copy a column of data (in column mode) and paste it as a column in another location. It seems I can no longer do that. I'm not sure what version this first started happening with. I can still paste a single line string to multiple lines with Column Mode paste, but not multi-line column values. 

I've seen a number of submissions describing the behavior I'm seeing except the user didn't copy in Column Mode. This is not what is happening here. For me Notepad++ is behaving as if I copied the data in normal mode (without the end of the lines) instead of copying in Column Mode

### Steps to Reproduce the Issue
1. start with a document like this
![image](https://user-images.githubusercontent.com/11760776/165366166-5c5380c3-8e30-454d-bfe1-5d920cb09a8b.png)

2. Highlight in Column Mode the letter prefixes
![image](https://user-images.githubusercontent.com/11760776/165366391-f6294a49-883b-4128-a738-1d02395c6a1d.png)

3. Hit Ctrl-C

4. Highlight  in Column Mode before the number suffix
![image](https://user-images.githubusercontent.com/11760776/165368026-ddd853f6-51aa-4e7b-9be0-87c766131271.png)

5. Hit Ctrl-V

### Expected Behavior
![image](https://user-images.githubusercontent.com/11760776/165366839-32d4a8ad-bdd4-4dff-80d5-2ecfcbb67e64.png)

### Actual Behavior
![image](https://user-images.githubusercontent.com/11760776/165366984-1b2c2a15-b8ef-42ad-99fb-4939c4c946ee.png)

### Debug Information
Notepad++ v8.3.3   (32-bit)
Build time : Mar 13 2022 - 17:11:10
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 10 Enterprise (64-bit) 
OS Version : 2009
OS Build : 19044.1586
Current ANSI codepage : 1252
Plugins : mimeTools.dll NppConverter.dll NppExport.dll

**Comment by alankilborn** [comment]
Solution:  Replace step 4 with "Put a single, non-column mode caret before the final `1` in line 1".

**Comment by pantsmann** [comment]
Sorry, no. That produces this:
![image](https://user-images.githubusercontent.com/11760776/165372081-59e52e2f-a5b2-45b6-ba7e-ff7780e272dd.png)

I expect this:
![image](https://user-images.githubusercontent.com/11760776/165372173-c66a2e4c-779a-469a-96e9-e65659df74f9.png)

**Comment by alankilborn** [comment]
For me, your STR but with my step 4 replacement takes this text:

```
a1..1
b2..2
c3..3
```

to this text:

```
a1..a1
b2..b2
c3..c3
```

**Comment by pantsmann** [comment]
What version are you running?

**Comment by alankilborn** [comment]
Notepad++ v8.3.3   (32-bit)
Build time : Mar 13 2022 - 17:11:10
Path : C:\.....\npp.8.3.3.portable\notepad++.exe
Command Line : -multiInst
Admin mode : OFF
Local Conf mode : ON
Cloud Config : OFF
OS Name : Windows 10 Enterprise (64-bit) 
OS Version : 2009
OS Build : 19042.1586
Current ANSI codepage : 1252
Plugins : mimeTools.dll NppConverter.dll NppExport.dll

**Comment by alankilborn** [comment]
Recommend CLOSURE of this item due to lack of further information from OP after being unable to repro.
