### ISSUE TITLE
compare, clear results, open new file, paste > crash

### ISSUE THREAD

**Issue by 5mi11er** [notepad-plus-plus/notepad-plus-plus#1158]
I've had this happen twice to me now within the past 2 days.  I have many files open, I compare two files, clear the compare, several times, with changes being made as a normal work process; I then later, have some new file to work on from email, select and copy that, come back to notepad++, clear the previous comparison results, open a new file, paste, and it crashes on me.

I've tried to replicate this behavior after this last time it crashed, but i've not been able to do so. I have not created the dump file yet, but the last thing it says is something about a pure virtual call.

**Comment by dail8859** [comment]
Sounds like it's caused by the plug in. You should probably report it to the plug-in authors.

**Comment by donho** [comment]
It's a plugin issue. Please report directly to author.

**Comment by informatorius** [comment]
Try with latest ComparePlugin from
https://bitbucket.org/uph0/compare/downloads
ComparePlugin.v1.5.6.6.bin.zip
