### ISSUE TITLE
8.4 Highlighting issues

### ISSUE THREAD

**Issue by thareh** [notepad-plus-plus/notepad-plus-plus#11585]
### Description of the Issue
8.4 seems to bring issues with highlighting, PHP-files with HTML in them will not highlight the HTML as before. Also when downloading and editing PHP-files using the NppFTP-plugin the PHP will not highlight at all until switching tab or opening the Style configurator and clicking on PHP.

### Steps to Reproduce the Issue
Open a PHP file with HTML in it.

### Expected Behavior
Highlighted keywords.

### Actual Behavior
Highlighting missing.

### Debug Information
Notepad++ v8.4   (64-bit)
Build time : Apr 20 2022 - 03:31:06
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : C:\Users\Carl\OneDrive\Apps\Notepad++
OS Name : Windows 11 (64-bit) 
OS Version : 2009
OS Build : 22000.652
Current ANSI codepage : 1252
Plugins : NppFTP.dll

**Comment by donho** [comment]
@thareh 
Could you provide  a PHP file with HTML in it please?

**Comment by a254476321** [comment]
> @thareh Could you provide a PHP file with HTML in it please?

Reloading any file will trigger this problem.

**Comment by boris-999** [comment]
similiar to my bug report;  mine has a tine reproducable example.  https://github.com/notepad-plus-plus/notepad-plus-plus/issues/11602

**Comment by DarkNami** [comment]
![8 3 3](https://user-images.githubusercontent.com/5100919/165697114-d4b3e0aa-da3d-4ab2-b012-8acb5cc1a58f.png)
![8 4 0](https://user-images.githubusercontent.com/5100919/165697144-e5d603e7-0121-4bdc-b33c-6c61e70b8eba.png)

PHP file lost all HTML syntax highlighting in 8.4.0.

**Comment by rdipardo** [comment]
Try using a development version from here: https://ci.appveyor.com/project/donho/notepad-plus-plus/builds/43354039/job/22wf6xmfhw7ku2pf/artifacts

**Comment by thareh** [comment]
The development version fixes the PHP HTML issues, thanks!

The NppFTP issue persists though, but perhaps that's an issue for the dev of NppFTP? The way NppFTP opens a file does not seem to apply any highlighting at all.

**Comment by rdipardo** [comment]
N++ 8.4 uses a brand new version of the [Scintilla editing component][0], which controls text highlighting and other features.
Plugins like NppFTP have probably not caught up yet.
The best place to make a report is https://github.com/ashkulz/NppFTP/issues

[0]: https://github.com/notepad-plus-plus/notepad-plus-plus/commit/a61b03ea8887e21c6e1b7374068962f635b79b80

**Comment by a254476321** [comment]
@rdipardo You can try open README.md, after that it will be lose text highlighting throw reloading

**Comment by rdipardo** [comment]
Thank you, @a254476321, I can reproduce it, and without NppFTP installed.

Like @thareh [originally said][0], switching tabs away and back again brings the highlighting back.
I also tried an XML file. The colours never disappeared, but the fold levels did! They reappeared only after shifting focus away and back again.

[0]: https://github.com/notepad-plus-plus/notepad-plus-plus/issues/11585#issue-1216271248

**Comment by rdipardo** [comment]
@donho, on the face of it, I'd say one of the 2 edit views is falling out of sync.

Here's a minimal example with JSON. Note how the style of `null` changes to `SCE_JSON_ERROR` after reload, as if some bytes of the document were lost in one of the edit views (probably the "hidden" one, since all the bytes are still showing in the window):

![npp-840-buffer-truncated-on-reload](https://user-images.githubusercontent.com/59004801/165744488-3f1262c8-6d4f-40fb-aa06-06feb7ea5490.gif)

**Comment by rdipardo** [comment]
@donho,
> Could you elaborate it please?

You can recreate the faulty highlight colours in any Notepad++ version (e.g. 7.8.5) by simply deleting text:

~~~json
{
  "a": nul
~~~

![x json-repro](https://user-images.githubusercontent.com/59004801/165817697-7a4c70a2-412d-4f6d-a507-f54f2f330665.png)

So, I think one edit view "sees" the reloaded buffer like this &#x2014; with bytes missing.
The edit window still *displays* the complete document, so at least one edit view is being updated properly on reload.
The other edit view doesn't "see" the full document you manually refocus the tab.

**Comment by Yaron10** [comment]
@rdipardo,

```
{
  "a": nul
```

This is JSON ERROR highlighting, isn't it?

**Comment by Yaron10** [comment]
I see the problem in 8.4. But what's wrong in 7.8.5?

**Comment by rdipardo** [comment]
> But what's wrong in 7.8.5?

Nothing at all. I just wanted to illustrate how a chopped-off JSON document is lexed.

**Comment by donho** [comment]
@rdipardo 
Yes, it could be lexer - I can also reproduce this issue on Markdown (UDL). OTOH, I didn't reproduce it on the other programming language so far.
Could you create an issue please? I will work on that.

**Comment by Yaron10** [comment]
> So, I think one edit view "sees" the reloaded buffer like this — with bytes missing.

But the problem isn't unique to JSON. It happens with many other files as well (e.g. CPP, RC).
How can you reproduce it in CPP by deleting a character?

**Comment by rdipardo** [comment]
@Yaron10,
> How can you reproduce it in CPP by deleting a character?

Not every lexer defines an error style to signal a truncated document, so the problem will manifest differently depending on file type. The C++ lexer will just render all text as `SCE_C_DEFAULT`, retaining some hints of style for numbers and operators.
Fold levels disappear because the folding routines depend on style: no detected style, no folds:

![npp_8 4_styled](https://user-images.githubusercontent.com/59004801/165837905-f2770fa4-4d4c-47f5-9901-0e231eb50d6f.png)

![npp_8 4_post-reload](https://user-images.githubusercontent.com/59004801/165837920-ecbc8337-6c3d-463a-9f0f-fc699d497eb4.png)

**Comment by Yaron10** [comment]
Thank you Robert. 👍

**Comment by donho** [comment]
@rdipardo 
Thank you.

**Comment by Bilbo47** [comment]
That development version from April 28 (6,211,584 bytes) did not fix the problem of "syntax highlighting disappears when the file is auto-reloaded". Auto-reload happens because the file was updated behind Npp's back. Switching to another tab and back does yes restore the highlighting.

**Comment by Bilbo47** [comment]
@donho said in [Notepad\+\+ 8\.4\.1 Release Candidate](/post/76654):
> Fix “Reload from disk” loosing syntax highlighting regression.

Confirmed this is now working as expected in the 64-bit version.
