### ISSUE TITLE
8.4 changes the background color of selected text if not in focus

### ISSUE THREAD

**Issue by hopalongrock** [notepad-plus-plus/notepad-plus-plus#11595]
See the forum 
post https://community.notepad-plus-plus.org/post/76419

![P1](https://user-images.githubusercontent.com/6840865/165522293-010d80dc-15bc-4ba9-803c-c8936081b2bf.jpg)

![P2](https://user-images.githubusercontent.com/6840865/165522300-da27fe0a-0581-44a1-af59-627dce8899ca.jpg)

It seems that a new color setting needed for the case, when the selected text isn't in focus.
The automatic quite dark grey colored text hardly readable.

**Comment by vinsworldcom** [comment]
To elaborate, Scintilla 5+ now uses `SC_ELEMENT_SELECTION_INACTIVE_BACK` to provide highlighting on selected text when the window loses focus.  The default may not match well with light / dark color schemes and / or foreground text color.

I use Obsidian theme and use PythonScript to set the color to RGB(96, 96, 96).

Pseudo-code:
```
SendMessage(scintilla.hwnd, SCI_SETELEMENTCOLOUR, SC_ELEMENT_SELECTION_INACTIVE_BACK, rgb2int(96, 96, 96))
```

Cheers.
