### ISSUE TITLE
Closing NP++ 6.8.6 saves file without asking

### ISSUE THREAD

**Issue by hergetr** [notepad-plus-plus/notepad-plus-plus#1160]
If I close Notepad++ v6.8.6 (most current version), it saves my changes to file without asking.
This is critical, because files become accidentally corrupted from time to time.

In settings, I found no option to change this behavior.

I installed NP++ using local settings (i.e. for install on usb stick).

yours,
Rainer Herget

**Comment by donho** [comment]
It's a "feature" that I have never implemented.
Check if you got any plugin which do it for you!

**Comment by hergetr** [comment]
Hello Don,

thank you for your reply.

As I discovered in-between, np++ does not save the modified files, but seems to kepp the modified file in its own memory:

1.     If I click the close button or press Alt-F4, NP++ closes without asking whether to save my changes.

2.     Next time I open the same file with NP++, my changes are still here.

3.     Only if I open that file with another editor, I can see, that my changes are not saved to disk.

Plug-Ins: Only the ones delivered with your setup. I have not installed any other ones.

If you still tell me that there is no such feature, I will try to find and remove any file and registry locations of np++ and reinstall.

Yours,
Rainer Herget

Phone: +49 621 60-54837 Fax: +49 621 60-21949 E-Mail: rainer.herget@basf.com
Postal Address: BASF SE, GT/SI - Q920, 67056 Ludwigshafen, Germany

150 years
BASF - We create chemistry

BASF SE, Registered Office: 67056 Ludwigshafen, Germany
Registration Court: Amtsgericht Ludwigshafen, Registration No.: HRB 6000
Chairman of the Supervisory Board: Juergen Hambrecht
Board of Executive Directors:
Kurt Bock, Chairman; Martin Brudermueller, Vice Chairman; Hans-Ulrich Engel,
Sanjeev Gandhi, Michael Heinz, Harald Schwager, Wayne T. Smith, Margret Suckale

Von: Don HO [mailto:notifications@github.com]
Gesendet: Donnerstag, 19. November 2015 23:59
An: notepad-plus-plus/notepad-plus-plus <notepad-plus-plus@noreply.github.com>
Cc: Rainer Herget <rainer.herget@basf.com>
Betreff: Re: [notepad-plus-plus] Closing NP++ 6.8.6 saves file without asking (#1160)


It's a "feature" that I have never implemented.
Check if you got any plugin which do it for you!
