### ISSUE TITLE
bug reprt

### ISSUE THREAD

**Issue by aminadav1** [notepad-plus-plus/notepad-plus-plus#11609]
I wanted to report a bug related to the name recognition mechanism 
of the functions shown in the list. It turns out that when a note appears 
in the same line of the function definition it does not allow the function 
to be recognized, and it will not appear in the list. 
for example:
void func () // This note prevents the function name from being identified.

Notepad++ v8.3.3   (64-bit)
Build time : Mar 13 2022 - 17:20:02
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 10 Home (64-bit) 
OS Version : 2009
OS Build : 19043.1526
Current ANSI codepage : 1255
Plugins : mimeTools.dll NppConverter.dll NppExport.dll

**Comment by dfs-** [comment]
Which programming language or lexer are we talking about. Where do you miss the function (function list, auto-completion, etc)?

**Comment by ArkadiuszMichalski** [comment]
Close due to lack of response.
