### ISSUE TITLE
8.4 PHP style is broken.

### ISSUE THREAD

**Issue by boris-999** [notepad-plus-plus/notepad-plus-plus#11602]
issue:
when viewing a .php file the colours for non-php-space change on an apostrophe. 

if teh text was within the php-space it would make sense to consider it the start of a PHP string, but it's occuring outside the <? ?> php-space.  it's occuring in the regular text space.

i don't recall having this issue in npp 8.3.x

### reproduce this issue
1.  ```<?php ?><html><body> isn't this awesome ..```
2.  observe how the `'` in the word  isn't  is being interpreted as a PHP string start token.
 

### Expected Behavior
it to know the difference between being inside and outside PHP <? ?> tags, when making style changes.

### Debug Information
Notepad++ v8.4   (64-bit)
Build time : Apr 20 2022 - 03:31:06
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 10 Home (64-bit) 
OS Version : 2009
OS Build : 19044.1645
Current ANSI codepage : 1252
Plugins : JSMinNPP.dll mimeTools.dll NppConverter.dll NppExport.dll NPPJSONViewer.dll NppSnippets.dll NppXmlTreeviewPlugin.dll XMLTools.dll

**Comment by DarkNami** [comment]
![8 3 3#11585](https://user-images.githubusercontent.com/5100919/165703693-06e95667-1e6d-49c9-8396-d0e30531369c.png)
![8 4 0#11585](https://user-images.githubusercontent.com/5100919/165703726-b25c08b6-63f2-42dd-91b3-a84b2202a3e9.png)

**Comment by rdipardo** [comment]
Try using a development version from here: https://ci.appveyor.com/project/donho/notepad-plus-plus/builds/43354039/job/22wf6xmfhw7ku2pf/artifacts

**Comment by DarkNami** [comment]
![8 4 0#PR-FIX](https://user-images.githubusercontent.com/5100919/165707983-bf3dc702-e5b3-4139-9edb-0a319c5d50ac.png)

**Comment by boris-999** [comment]
i manually applied the patch,  that 1 line:  setLexerFromLangID(L_HTML);     fixed it right up!  good work everyone :)
