### ISSUE TITLE
V8.4 random crashes

### ISSUE THREAD

**Issue by TheArPee** [notepad-plus-plus/notepad-plus-plus#11611]
### Description of the Issue
Seemingly at random but especially if trying to drag the active application window from screen to screen the fails to gain focus and app crashes

### Steps to Reproduce the Issue

1. Have a few saved files open (3 or 4)
2. Have 5 or 6 unsaved files open 
3. Click on another app window and do something
4. Click on Notepad++ Window
5. Try to move the app window between two screens or even edit the active file

### Expected Behavior

App windows drags to new location or is able to be edited

### Actual Behavior

App crashed - 4 times in the last 8 hours

### Debug Information
Notepad++ v8.4   (64-bit)
Build time : Apr 20 2022 - 03:31:06
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 10 Pro (64-bit) 
OS Version : 2009
OS Build : 19044.1645
Current ANSI codepage : 1252
Plugins : ComparePlugin.dll CSScriptNpp.dll ExtSettings.dll HTMLTag.dll JSMinNPP.dll LanguageHelp.dll Linefilter3.dll mimeTools.dll NavigateTo.dll NppConverter.dll NppEditorConfig.dll NppExport.dll NPPJSONViewer.dll NppMarkdownPanel.dll NppRegExTractorPlugin.dll NppTextViz.dll NppXmlTreeviewPlugin.dll PreviewHTML.dll PythonScript.dll Remove Duplicate Lines.dll XMLTools.dll

**Comment by donho** [comment]
@TheArPee 
Could you try without plugins?

**Comment by TheArPee** [comment]
@donho - yes I will. Problem is on my work laptop and does not happen on my Home PC so I am trying to find out the difference between the installs

**Comment by TheArPee** [comment]
@donho Ok tests complete:
Opened Notepad++ WITH plugins (normal start) machine had NOT been rebooted.
Switched to other running apps (Outlook & Visual Studio) then clicked on Notepad++ page & tried to select different file tab from the one that was highlighted - Crash.

Opened Notepad++ with -noPlugin argument & carried out exact same steps as above - NO CRASH

closed Notepad++ and then reopened from normal shortcut with all plugins enabled.
Repeated steps from first test - NO CRASH

Closed & Repeated last test 5 times - NO CRASH

I hope that helps (maybe plugin was cached in a bad state?)

I will report if there is another episode of this issue

**Comment by rdipardo** [comment]
> . . . (maybe plugin was cached in a bad state?)
> 

That's very likely, if you left a docked panel open when shutting down Notepad++, e.g., the document tree viewer that NPPJSONViewer provides. Every panel's location and geometry is cached, along with name of the plugin module, in `%APPDATA%\Notepad++\config.xml`:

~~~xml
        <GUIConfig name="DockingManager" leftWidth="200" rightWidth="200" topHeight="200" bottomHeight="200">
            <PluginDlg pluginName="NPPJSONViewer.dll" id="0" curr="0" prev="-1" isVisible="yes" />
            <PluginDlg pluginName="dbgpPlugin.dll" id="0" curr="3" prev="-1" isVisible="no" />
            <ActiveTabs cont="0" activeTab="0" />
            <ActiveTabs cont="1" activeTab="-1" />
            <ActiveTabs cont="2" activeTab="-1" />
            <ActiveTabs cont="3" activeTab="-1" />
        </GUIConfig>
~~~

If the application misreads the cached data, or you dropped a stale `config.xml` into another version's data diectory, the editor will try to access an invalid memory address and crash.

**Comment by TheArPee** [comment]
Re opening:
@donho - Still getting crashes when trying to open files - even when running with -noPlugins

**Comment by donho** [comment]
@TheArPee 
Could you find your `config.xml` and attach it here please?
As @rdipardo has explained, it could be due to some incoherent settings among the different versions.

**Comment by TheArPee** [comment]
[config.xml.txt](https://github.com/notepad-plus-plus/notepad-plus-plus/files/8638077/config.xml.txt)

**Comment by TheArPee** [comment]
@donho - file attached above (Had to change file name to add .txt but otherwise unchanged)

**Comment by donho** [comment]
@TheArPee Thank you.
Strange, it doesn't crash my Notepad++ v8.4 x64.
Did you copy it from `%APPDATA%\Notepad++\`?
If yes, please close Notepad++, rename `config.xml` and launch it again to see if it crashes.

**Comment by TheArPee** [comment]
@donho Yes I did copy from %APPDATA\Notepad++\
renamed config.xml and started app:
All themes etc removed. 
App crashes after about 20 seconds. :-(
No new config.xml created.

**Comment by donho** [comment]
@TheArPee 
Do you have NVDA screen reader installed on your PC?

**Comment by TheArPee** [comment]
No I don't

**Comment by TheArPee** [comment]
@donho As this is only affecting the updated install on my work laptop (and I have tried the 64bit portable version with no issues on the same machine), is it time to try and do a full uninstall and a clean install? Or would you like me to persevere so that we can try to find out what the issue is?

**Comment by donho** [comment]
@TheArPee 
Could you, if it's possible, provide me 2 zipped files of your whole `%APPDATA%\Notepad++\` and your `%ProgramFiles%\Notepad++\` ?
I'll try to reproduce the crash on my machine.

**Comment by TheArPee** [comment]
It will not let me copy the ProgramFiles zip - maybe too large?

**Comment by TheArPee** [comment]
[ProgFiles_Notepad++.zip](https://github.com/notepad-plus-plus/notepad-plus-plus/files/8654175/ProgFiles_Notepad%2B%2B.zip)

**Comment by TheArPee** [comment]
OK I tried everything but the plugins folder and it worked

**Comment by TheArPee** [comment]
[plugins_part1.zip](https://github.com/notepad-plus-plus/notepad-plus-plus/files/8654215/plugins_part1.zip)

**Comment by TheArPee** [comment]
[plugins_part2.zip](https://github.com/notepad-plus-plus/notepad-plus-plus/files/8654217/plugins_part2.zip)

**Comment by TheArPee** [comment]
Finally! Obviously the plugins are in a folder called plugins!
Hope that helps

**Comment by donho** [comment]
@TheArPee 
I've replaced all the files in `%APPDATA%\Notepad++\` by yours, rename `config.xml.bad` to `config.xml` and copied all your non-binaries files from your `%PROGRAMFILES%\Notepad++\` to mine. I didn't copy the plugins since the crash still happens when you launch your Notepad++ without loading plugins. With such configuration I launch notepad++ v8.4 x64, I try to do as you did, during 2-3 hours (without changing the screen since my laptop cannot plug external monitor), I cannot reproduce the crash.

Obviously your crash is an isolated case, related to a special configuration. 
I suggest you uninstall your Notepad++ and remove manually all the files in `%APPDATA%\Notepad++\` and `%PROGRAMFILES%\Notepad++\` after installation.

**Comment by TheArPee** [comment]
I have done a complete uninstall - removed all remaining files / folders in %APPDATA% and %PROGRAMFILES% and rebooted. Clean install from newly downloaded installer.
Reinstalled my most used plugins.

No issues so far.

Shame we were not able to identify the issue - but at least everything is working properly now.

Thank you @donho for your time and effort.

**Comment by donho** [comment]
@TheArPee 
Thank you for providing all the files.
Please close this issue if there's no more crash after some test.

**Comment by TheArPee** [comment]
Still working with no crashes after 4 hours so closing this issue
