### ISSUE TITLE
Weird search result when searching multiple files

### ISSUE THREAD

**Issue by nico-apps** [notepad-plus-plus/notepad-plus-plus#11618]
### Description of the Issue
Recently, I wanted to use the feature of Notepad++ to search through multiple files to see where I used my function. This listed off all the occurences correctly (appearences in .c source files) except for one, this one being in the executable file `a.out`. As it turns out, the function name can be found in that file as well, but the search window showed the incorrect output as you can see here:
![grafik](https://user-images.githubusercontent.com/35093969/166114900-2559d575-c6cc-45c3-9ad3-007a5b418b03.png)

### Steps to Reproduce the Issue

1. Create a code file of any compilable language with a custom function.
2. Compile the code using a Linux compiler (GCC in my case).
3. Search for the function using the "Find in Files" option.

### Expected Behavior

The occurence in `a.out` should be listed correctly, saying something like `Line 156: interpreter_resetFlags`

### Actual Behavior

The occurence in `a.out` is listed incorrectly, saying something like `Line 156:  L`

### Debug Information
Notepad++ v8.3.3   (32-bit)
Build time : Mar 13 2022 - 17:11:10
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 10 Home (64-bit) 
OS Version : 2009
OS Build : 19044.1645
Current ANSI codepage : 1252
Plugins : mimeTools.dll NppConverter.dll NppExport.dll 

a.out file that I tested it with, converted to .txt because of the Github upload rules: [a.txt](https://github.com/notepad-plus-plus/notepad-plus-plus/files/8597462/a.txt)

**Comment by alankilborn** [comment]
Notepad++ is a text file editor.
a.out is not a text file.
Thus, I wouldn't worry about what it is showing you in this case.

**Comment by alankilborn** [comment]
Recommend CLOSURE of this item.
