### ISSUE TITLE
Notepad++ 8.4 Immediately Crashes When Using NVDA

### ISSUE THREAD

**Issue by Access4All96** [notepad-plus-plus/notepad-plus-plus#11629]
### Description of the Issue
When using Notepad++ 8.4 with NVDA screen reading software, Notepad++ immediately crashes when you start typing. This does not happen with previous versions of Notepad++. The problem began on version 8.3.3.

### Steps to Reproduce the Issue
1. Start NVDA screen reading software, which can be downloaded freely from nvaccess.org/download.
2. Start the most current version of Notepad++.
3. Type anything you'd like. The app will immediately close.

### Expected Behavior
Notepad++ should simply cooperate with the screen reading program I use by allowing me to type and read what I've written.

### Actual Behavior
The program closes unexpectedly.

### Debug Information
Notepad++ v8.4   (64-bit)
Build time : Apr 20 2022 - 03:31:06
Path : C:\Users\bestbiu\Downloads\npp.8.4.portable.x64\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : ON
Cloud Config : OFF
OS Name : Windows 10 Home (64-bit) 
OS Version : 2009
OS Build : 19044.1645
Current ANSI codepage : 1252
Plugins : mimeTools.dll NppConverter.dll NppExport.dll

**Comment by rdipardo** [comment]
Known issue:

- #11565
- #11424
- https://github.com/notepad-plus-plus/notepad-plus-plus/issues/11133#issuecomment-1036204216

32-bit Notepad++ should be unaffected

**Comment by PatrykMis** [comment]
Can be closed - no problem on latest (as time of writing) stable NVDA version 2022.1.

**Comment by PepperTheVixen** [comment]
Can confirm Notepad++ 8.4.4 64-bit is working with NVDA 2022.2 on Windows 10 version 21h2. Had to run COM Registration Fix Tool in NVDA and disabled the Notepad++ NVDA addon in NVDA. The addon still works in the 32-bit version of Notepad++. Big sad. Hope that NVDA addon gets updated at some point
