### ISSUE TITLE
Folding is broken

### ISSUE THREAD

**Issue by sanastasiou** [notepad-plus-plus/notepad-plus-plus#1162]
OS WIndows 10 64bit, NPP 6.8.6

To reproduce this issue, just do the following:

Open a relatively big file:

e.g NotepadPP\PowerEditor\src\Parameters.cpp from the source

Try to fold in line 349: static const ScintillaKeyDefinition scintKeyDefs[] =

Observe the bug, the whole file get's folded instead of only the array initialization list..

The same problem can be found in other languages as well.

**Comment by dail8859** [comment]
First of all, this issue is with Scintilla/Scite, meaning it should probably be reported to them instead of Notepad++.

Secondly, to reproduce this issue, it looks like it is getting confused on line 461 of that file. If you add a space immediately after the `//` then the folding works correctly.

**Comment by sanastasiou** [comment]
It's getting confused in random places and files, that was just an example. OK, I'll report this to Scite as well. Note: this effectively breaks folding in any and all languages give a big enough file.. Editing/manipulating the file seems to partially fix this.. but that shouldn't be the case.

**Comment by sanastasiou** [comment]
LOL there are about a million bugs regarding folding already reported there. I wonder why I should bother posting the next one...

**Comment by sanastasiou** [comment]
Posted :  https://sourceforge.net/p/scintilla/bugs/1780/ let's see when this is fixed there, and when the new scintilla get's integrated here :)

**Comment by sanastasiou** [comment]
@dail8859 reply I got from scintilla bug:

http://sourceforge.net/p/scintilla/bugs/1780/

The file contains an explicit fold marker //{ which affects the fold structure. Either remove this or turn off explicit fold markers.

Any idea what to do here?

**Comment by sanastasiou** [comment]
@dail8859  It appears you were correct to identify the problem area, but I do not find any "turn off explicit fold markers" option. It this in scintilla? Does NPP use it? Can one set this off for some lexer/extension ?

Thanks
