### ISSUE TITLE
Add 'View with Notepad++ (read only)' to context menu

### ISSUE THREAD

**Issue by kpopv** [notepad-plus-plus/notepad-plus-plus#11635]
### Description of the Feature Request
I often find myself opening files I should only read and not edit. Therefore, It would be nice to have a context menu item that says "View with Notepad++ (read-only)" which automatically opens the file in read-only mode, using the -ro flag. I've tried to hack the menu item myself through the registry, but I was unsuccessful.

### Steps as workaround
1. Open the context menu of a file
2. Choose "Edit with Notepad++"
3. Edit > Set read only

### Desired Behavior
I would like an item in the context menu with "View with Notepad++ (read only)" that does the above step 3 automatically.

**Comment by kpopv** [comment]
I understand this might be rather specific, so I'm open to any workaround that does not require altering Notepad++.

**Comment by alankilborn** [comment]
> I've tried to hack the menu item myself through the registry, but I was unsuccessful.

I have a setup that supports this, and it works just fine.
Surely the burden isn't on the Notepad++ developers to help you set something like this up.
Perhaps it is something to inquire about on the Community support site: https://community.notepad-plus-plus.org/

**Comment by ts-50** [comment]
Could probably be done in NppShell https://github.com/notepad-plus-plus/notepad-plus-plus/tree/master/PowerEditor/src/tools/NppShell https://github.com/notepad-plus-plus/notepad-plus-plus/blob/master/PowerEditor/src/tools/NppShell/src/NppShell.cpp

**Comment by alankilborn** [comment]
Recommend CLOSURE of this item.

**Comment by ArkadiuszMichalski** [comment]
@donho If you don't plan to expand NppShell with new entries then please close this issue. Everyone can do it on their own way by modifying the system registry.

**Comment by donho** [comment]
> If you don't plan to expand NppShell with new entries then please close this issue. Everyone can do it on their own way by modifying the system registry.

Yes, indeed, it's a very specific (and rarely needed) request. It'll not implemented, for the sake to not pollute the context menu.
