### ISSUE TITLE
Printing selected text does not work as expected in 8.4

### ISSUE THREAD

**Issue by loxia01** [notepad-plus-plus/notepad-plus-plus#11638]
### Description of the Issue
After updating to v8.4 (checked 8.3 for presence of issue) printing selected text also outputs the selection highlight marking (default pink color). That is not expected behavior I suppose. Have tested with two different printers.

### Steps to Reproduce the Issue
1. Select some text lines.
2. Choose Print... in menu.
3. Print selected text (make sure "Selection" is chosen under Page Range).

### Expected Behavior
Expected behavior is printing of the selected text lines WITHOUT the selection highlight marking.

### Actual Behavior
The selected text is printed WITH the pink selection highlight marking.

### Debug Information
Notepad++ v8.4   (64-bit)
Build time : Apr 20 2022 - 03:31:06
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 10 Pro (64-bit) 
OS Version : 2009
OS Build : 19043.1645
Current ANSI codepage : 1252
Plugins : mimeTools.dll NppConverter.dll NppExport.dll NPPJSONViewer.dll

**Comment by naveenudhayasankar** [comment]
Can I pick up this issue?

**Comment by donho** [comment]
@naveenudhayasankar Assigned to you too.
I won't work this fix so far, so go ahead to provide your PR.

**Comment by naveenudhayasankar** [comment]
Hi @donho, 

Can you let me know where to look, I debugged Printer.cpp, Notepad_plus.cpp and Parameters.cpp between the versions 8.3 and 8.4, the variable values look similar to me, can you provide some insight where to look?

**Comment by ts-50** [comment]
Did 8.3 have the issue?

**Comment by loxia01** [comment]
> Did 8.3 have the issue?

No, I have double checked 8.3 for the issue.

**Comment by loxia01** [comment]
> Did 8.3 have the issue?

No, I have double checked 8.3 (8.3.3) for the issue.

**Comment by naveenudhayasankar** [comment]
8.3 did not have this issue.
