### ISSUE TITLE
Code Question

### ISSUE THREAD

**Issue by resteves-99** [notepad-plus-plus/notepad-plus-plus#11646]
I am struggling to explore the code and I was hoping to get some help.

Specifically I am looking for the function that is called when a user saves a file

**Comment by alankilborn** [comment]
That's not an issue.
Questions like that belong on the Community support forum: https://community.notepad-plus-plus.org/

**Comment by rdipardo** [comment]
@resteves-99,
the easiest way is to install [Git](https://gitforwindows.org) and open the "Git Bash" application. At the prompt, enter:

    git clone https://github.com/notepad-plus-plus/notepad-plus-plus.git
    cd notepad-plus-plus
    git grep -ni "Save file" -- *.cpp

---
#### Pro tip

If you have [VS Code][0] and the `git` executable is on your [system's PATH][1], you can jump to any matching line number by hovering the mouse and pressing <kbd>Ctrl + Click</kbd>.

![Screenshot_2022-05-06_21-31-18](https://user-images.githubusercontent.com/59004801/167232699-a29a110b-85cd-4b91-bbd8-ade6a61555d3.png)


[0]: https://code.visualstudio.com
[1]: https://techpp.com/2021/08/26/set-path-variable-in-windows-guide/

**Comment by alankilborn** [comment]
@rdipardo 

Surely you jest:
* Recommending a "git grep" instead of Notepad++'s _Find in Files_.
* An implicit recommendation for VS Code (a competing text editor), on a Notepad++ site

But still, not appropriate to even attempt to answer the original question here.
OP was directed to the correct resource.

**Comment by rdipardo** [comment]
> * An implicit recommendation for VS Code (a competing text editor), on a Notepad++ site
> 

The existence of alternative text editors was never a secret, and the original title was "__*Code*__" Question" after all:

~~~sh-session
$ scoop which code
C:\Users\Rob\AppData\Local\Programs\Microsoft VS Code\bin\code.cmd
~~~
😄 

> But still, not appropriate to even attempt to answer the original question here.

Until GitHub allows the total deletion of unwanted issues &#x2014; or this project gets serious about [enforcing the issue template][0], with a bot  performing routine cleanup &#x2014; just humouring the question where it was asked is still better than encouraging yet more pointless chatter on the forum &#x2014; where, at least, threads __*can*__ be completely scrubbed.

[0]: https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository#configuring-the-template-chooser

**Comment by resteves-99** [comment]
thanks for the advice on community forums and the solution
