### ISSUE TITLE
last 2 releases doesnt appear in  the release tab

### ISSUE THREAD

**Issue by PierreCsn** [notepad-plus-plus/notepad-plus-plus#11651]
Hello 
The latest release here is 8.3.2, we are using a bot to package every new releases , should we switch to the latest tag instead of release or do you plan to publish them as releases soon.
Best regards

**Comment by theofficialgman** [comment]
yes please mark these latest tags as releases. normal users will miss them and we use them at pi-apps to check for the latest release automatically

**Comment by dail8859** [comment]
There's a discussion on #11654 that seems to point to a GitHub issue. Closing this in favor of #11654. Further questions/comments can be made there.
