### ISSUE TITLE
bad line warp while typing Chinese

### ISSUE THREAD

**Issue by monororo** [notepad-plus-plus/notepad-plus-plus#1165]
Here is something about "I have a dream" by Martin Luther King, Jr.  I tried different types of line warp and it was bad about Chinese.
The line 10 is a copy of line 8, just has a extra blank after second comma. I think it should be helpful resolving this problem.
![default](https://cloud.githubusercontent.com/assets/15166609/11293510/b564a53e-8f95-11e5-960c-fbeb15412287.png)
![aligned](https://cloud.githubusercontent.com/assets/15166609/11293511/b566a708-8f95-11e5-971b-7c4adb94abb5.png)
![indent](https://cloud.githubusercontent.com/assets/15166609/11293509/b5644fbc-8f95-11e5-85ea-ece578ecbf5e.png)

**Comment by donho** [comment]
It's rather a Scintilla issue.
