### ISSUE TITLE
Strange context menu

### ISSUE THREAD

**Issue by maxqwerty** [notepad-plus-plus/notepad-plus-plus#1166]
Open two or more documents. Open long doc (scrollbar should be shown). Try to right click while scrolling (middle mouse button). If not to release RMB, then a strange context menu will be shown.
The same effect if hold RMB and scroll. It is not seems like a feature.

**Comment by 18763C27** [comment]
isn't that the document switcher?

it's activated by scrolling up or down while holding down RMB, or by pressing tab while holding down ctrl

you can disable it under preferences > misc. if you don't want to use it

**Comment by maxqwerty** [comment]
Yes, it is. I do not know about that feature. It looks very strange compared with common style.
