### ISSUE TITLE
[Feature request]: Json5 highlighting

### ISSUE THREAD

**Issue by LostTime76** [notepad-plus-plus/notepad-plus-plus#11676]
I realize this might be a long shot.. but I am a long time user of N++. I don't think this is currently implemented and apologies if there is another issue open... but would it be possible to add Json5 highlighting via the json5 file extension? It seems like there may be a way to hack the highlighting a little by using JavaScript highlighting instead as that seems to be close; however, if I choose JavaScript highlighting, it's not very good..

I really really x1000 do not want to move to another editor for this support. I tried atom and it seemed like it had support, but I want to continue to use N++. 

This is what I currently get using JavaScript highlighting.
![image](https://user-images.githubusercontent.com/62843610/168480660-504c1288-ac9a-421d-83b8-46553105daa5.png)

This standard json highlighting is much more palatable. 
![image](https://user-images.githubusercontent.com/62843610/168480691-233f1572-8f00-4048-ad26-11a8ded3051f.png)

I may  be a long time user of N++ as a software engineer, but I have never gone past the basic UI or twiddled any settings. If there is another way to achieve better highlighting, I am all for it.

**Comment by rdipardo** [comment]
@donho, just make a new `L_JSON5` enum value and use the builtin JSON lexer's option to allow comments [^1].

N++ currently uses *none* of the JSON lexer's available options; `ScintillaEditView::setJsonLexer` has not been updated since the days when the C++ lexer did the styling for every C-style curly brace language:

https://github.com/notepad-plus-plus/notepad-plus-plus/blob/74395977bbf5dbd9bb9bfc3645b78584ce7b03f1/PowerEditor/src/ScintillaComponent/ScintillaEditView.cpp#L711-L715

[^1]: https://github.com/notepad-plus-plus/notepad-plus-plus/blob/74395977bbf5dbd9bb9bfc3645b78584ce7b03f1/lexilla/lexers/LexJSON.cxx#L125-L127

**Comment by LostTime76** [comment]
Json5 has several more changes than just adding comments. As shown above, the first screenshot is valid Json5. For example, property values can be single quoted, double quoted, or not quoted. Additionally, there are changes to allow different number formats for number values.

I don't know enough about javascript to know if Json5 is close to it or not. However, the unquoted property values are highly desirable to use and having them properly highlighted with a different color would be useful. I think the unquoted property value is valid javascript, but the javascript highlighter doesn't seem to highlight it regardless. 

Json5 spec: https://spec.json5.org/#prod-JSON5Identifier

**Comment by rdipardo** [comment]
The lexer module is maintained by another project: https://github.com/ScintillaOrg/lexilla
New language features have to be implemented by them before N+ can benefit.

**Comment by donho** [comment]
Adding L_JSON5 enum and applying all `*.json5` to L_JSON5 for enabling comment in JSON could be a solution.

**Comment by ArkadiuszMichalski** [comment]
Next ask: https://community.notepad-plus-plus.org/topic/23600/jsonc-support.

**Comment by arose26** [comment]
This is still an issue as of 8.6.5. While NPP recognizes a json5 file, the style does not map correctly. In fact, it is not even possible to make a custom style for json5's features.
![image](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/145766958/40ef6abd-04f8-4b8f-b521-3fb5024c6667)
