### ISSUE TITLE
[DarkMode] Blurry static text in preference "tab size"

### ISSUE THREAD

**Issue by ozone10** [notepad-plus-plus/notepad-plus-plus#11695]
Issue for Notepad++ v8.4.1

![image](https://user-images.githubusercontent.com/55940305/169117467-8ce1333b-2374-4e71-84b1-04c3f61a187b.png)

Feel free to do PR, I am currently busy.
If no one will fix it, I will do it later when I have free time.

**Comment by ts-50** [comment]
That's odd, I'm not getting that. I'm not even seeing a Default Value checkbox.
![image](https://user-images.githubusercontent.com/19561856/169307798-60e7c4ac-4fff-41da-b6d6-53d73ab7d08f.png)

Notepad++ v8.4.1   (64-bit)
Build time : May  8 2022 - 19:51:18
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 11 (64-bit) 
OS Version : 2009
OS Build : 22000.675
Current ANSI codepage : 1252
Plugins : mimeTools.dll NppConverter.dll NppExport.dll

**Comment by alankilborn** [comment]
>I'm not even seeing a Default Value checkbox.

Try selecting something other than `[Default]` in the listbox and it will appear.
