### ISSUE TITLE
Select All... Delete

### ISSUE THREAD

**Issue by KevinFernandes** [notepad-plus-plus/notepad-plus-plus#1169]
If the Notepad++ window is not maximized and I right-click and select “Select All” from the menu then hit the Delete key, the Notepad++ window resizes to a minimal window with only the app icon, the minimize and maximize buttons and the close button visible.

It does this every time, even if there is nothing in the document or its a new document.

If the Notepad++ window is maximized and on a different monitor other than the primary, then the window jumps to the primary monitor but stays maximized.

In all cases, when I press the Delete key, the window shows “Not responding” even if the document was new/empty at the time (so what is it doing??).

I am using the latest 6.8.6, but I noticed this at least two or three versions before that.

**Comment by donho** [comment]
I believe this issue has been fixed since long time ago.
Update your Notepad++ to the latest version (v7.6.6).
If the issue persists, please create a new issue for it.
Thank you.
