### ISSUE TITLE
Multiple new docs have the same title

### ISSUE THREAD

**Issue by Yaron10** [notepad-plus-plus/notepad-plus-plus#11704]
**STR:**
Open two new docs.
Move "New 2" to the other view.
Move "New 2" back to the other view.
Open a new doc.
Open another new doc.

**Result:**
Two docs titled "New 2".

![תמונה](https://user-images.githubusercontent.com/10229320/169531156-c70e61db-4c2c-4ab1-b4ca-3110aa6b0888.png)

Repeating those steps with more tabs, you can get:

![תמונה](https://user-images.githubusercontent.com/10229320/169531325-474f9ca2-0a4c-4ad0-acbc-837a59f486a0.png)

***

Notepad++ v8.4.1   (64-bit)
Build time : May 20 2022 - 00:41:35
Path : C---Notepad++ Original.exe
Command Line : $COMMAND_LINE_PLACEHOLDER$
Admin mode : ON
Local Conf mode : ON
Cloud Config : OFF
OS Name : Windows 10 Pro (64-bit) 
OS Version : 2009
OS Build : 19042.985
Current ANSI codepage : 1255
Plugins : 
    ComparePlus (1)
    HTMLTag (1.2.3)
    MenuIcons (1.2.5)
    PythonScript (2)
    _CustomizeToolbar (4.2)

**Comment by ArkadiuszMichalski** [comment]
@Yaron10 

I can't reproduce this with actual NPP 8.4.9. If we have only 2 untitled documents, move second to other view and move back to main view then first doc is replaced by this second, and finally we have only 1 doc. Such behavior always been here or has it changed at some point?

**Comment by Yaron10** [comment]
@ArkadiuszMichalski,

> If we have only 2 untitled documents, move second to other view and move back to main view then first doc is replaced by this second, and finally we have only 1 doc.

And then:
Open a new doc.
Open another new doc.

Thank you for testing it.

**Comment by ArkadiuszMichalski** [comment]
Ah right.
