### ISSUE TITLE
"Alternate icons" setting is ignored

### ISSUE THREAD

**Issue by Yaron10** [notepad-plus-plus/notepad-plus-plus#11703]
Using https://ci.appveyor.com/project/donho/notepad-plus-plus/builds/43603874.

**STR:**
Uncheck "Preferences -> General -> Alternate icons".
Restart NPP.

**Result:**
The alternative icons are used.

Caused by https://github.com/notepad-plus-plus/notepad-plus-plus/commit/67297397d45df93bc6b7f628b210052f7a25315e.

**Comment by ozone10** [comment]
Sorry my mistake
https://github.com/notepad-plus-plus/notepad-plus-plus/blob/3750cf8fa34470e3196fd041254960d88534cd80/PowerEditor/src/Notepad_plus.cpp#L238
should be 
`unsigned char indexDocTabIcon = (((tabBarStatus & TAB_ALTICONS) == TAB_ALTICONS) ? 1 : NppDarkMode::isEnabled() ? 2 : 0);`
