### ISSUE TITLE
How to sort files in Folder as Workspace?

### ISSUE THREAD

**Issue by msgoussi** [notepad-plus-plus/notepad-plus-plus#11716]
i am wondering if notepad++ can allow the user to sort the files shown in the Folder as Workspace!
Thanks

**Comment by saturdaywalkers** [comment]
Opening a 'webDAV' folder, the files are in a random order, not alphabetical order. "Last modified" order would be a nice-to-have as well

**Comment by donho** [comment]
Currently it's sorted, at least in the latest version I've tested.

**Comment by aavmurphy** [comment]
@donho Still broken for me
notepad++ v8.6.5
using webdav with (ubuntu) apache 2.4.59

**Comment by donho** [comment]
@aavmurphy 
Could you open an issue with detailed information please?
I will check it and see what I can do about it.

**Comment by aavmurphy** [comment]
@donho That's this issue :)
Set up an Apache httpd server with WebDAV module.
- Make sure you have options like 'auto indexes' and '.htaccess' files turned OFF
Connect to the webserver's filesystem from Windows (windows file explorer | network icon | right hand click | map network drive | 'connect to a website'.
- This opens the 'network connection wizard'
In Notepad++, do 'open folder as workspace' on the webserver filesystem
1) Files aren't sorted
2) There is no way to refresh the view (i.e. create a new file, it isn't visible)

I'm guessing its differences between the "webdav" api, and the "windows file directory" api, e.g. Windows probably returns a sorted list, but webdav doesn't.

**Comment by AngelsDragon** [comment]
Dear Notepad++ Development Team,

I am currently using the latest version of Notepad++ (v8.7.5, 32-bit) and have observed that while child elements within the workspace are automatically sorted, the workspace names themselves are not. I would like to request the addition of an option to sort the workspace names automatically.

Specifically, I suggest implementing the following in the Workspace settings:

1. **Enable AutoSort Workspace:** A checkbox that, when enabled, automatically sorts the workspace names.
2. **Disable Manual Movement:** When AutoSort is enabled, disable the option to manually move workspaces up or down.

Thank you for considering this feature request. I appreciate your efforts in continuously improving Notepad++.

Best regards,
X
