### ISSUE TITLE
Nested block of comments in SQL code isn't highlighted correctly

### ISSUE THREAD

**Issue by piomiq** [notepad-plus-plus/notepad-plus-plus#11718]
### Description of the Issue
Code of SQL commented by block commands which is nested (example below) is not highlighted correctly. Please notice that in Microsoft SQ Server Management Studio below works as expected.

/* aaaaaaaaaa
   /*  bbbbbbbbbbbbbbb  */
aaaaaaaaaa */

### Steps to Reproduce the Issue

1.  Put below into editor
/* aaaaaaaaaa
   /*  bbbbbbbbbbbbbbb  */
aaaaaaaaaa */

2. Change highlighting with SQL
3. 

### Expected Behavior
all lines coming from example should be like as commented

### Actual Behavior
last line is incorrectly highlighted - like would be not commented

**Comment by rdipardo** [comment]
This would be an issue for the project that maintains [the SQL lexer][0]: https://github.com/ScintillaOrg/lexilla/issues

The target dialect is Oracle SQL, and I couldn't find an example of nested comments here: https://docs.oracle.com/cd/B14117_01/server.101/b10759/sql_elements006.htm#sthref522

[0]: https://github.com/ScintillaOrg/lexilla/blob/c456b6bd008f137fcf0dc946481e89db9eea876e/lexers/LexSQL.cxx#L502-L507

**Comment by piomiq** [comment]
BTW. The same issue happens for C++, Java and the most likely in all other languages where is allowed block comment.
Anyway I will report this issue to ScintillaOrg.

About target dialect.
I think any example is not necessary in this case. The simplest way would be just test it in Oracle SQL Plus editor or any Oracle developer application like Toad for Oracle.

**Comment by rdipardo** [comment]
Fixed for Transact-SQL in ScintillaOrg/lexilla@ab003b93

"Ordinary" SQL was never an issue because the Notepad++ lexer is based on Oracle PL/SQL, which doesn't allow nested block comments: <https://docs.oracle.com/cd/B19306_01/appdev.102/b14261/fundamentals.htm#sthref364>
