### ISSUE TITLE
[Request] Allow Scintilla's option to enable/disable comments highlighting for JSON files

### ISSUE THREAD

**Issue by tilleul** [notepad-plus-plus/notepad-plus-plus#11713]
### Description of the Issue

Although comments are not officially supported in JSON files, many subsets of JSON allow comments.
According to https://github.com/notepad-plus-plus/userDefinedLanguages/issues/58
and https://community.notepad-plus-plus.org/topic/19486/help-with-json-and-scintilla-lexer/2?lang=fr
Scintilla highlighting engine has a ``options.allowComments`` variable in the JSON lexer that would allow the highlight of comments. This option is not accessible from NPP. Also notice that the "Style configurator" has styles for "LINECOMMENT" and "BLOCKCOMMENT" for JSON files but these styles are not applied (because "allowComments" is set to false as default).

Could the "allowComments" option be added to Settings/Preferences/Languages screen in the same way that "Treat backslash as escape character for SQL" is an option on this screen ?

### Steps to Reproduce the Issue

Create a new file, set Language to JSON and type
```
{
    "myProperty": "any value" // this comment is treated as an error (red)
}
```

### Expected Behavior

```
{
    "myProperty": "any value" // this comment should be treated as a comment if "allowComments" option is set
}
```

### Actual Behavior

Line comments and block comments are treated as errors.

### Debug Information
not applicable (request feature)

**Comment by RemixPL1994** [comment]
Please allow red colors to be turned off or red to another more subtle and mellow color.

Red is very eye-catching when the .json configuration is opened:

![obraz](https://user-images.githubusercontent.com/52541621/172232200-342369e1-804d-40f5-9d2d-8213207ed2c3.png)

**Comment by alankilborn** [comment]
@RemixPL1994 

>Red is very eye-catching when the .json configuration is opened

Probably to alert you to the fact that this could be an error.

>...or red to another more subtle and mellow color

Feel free to change the color as you like, here:

![image](https://user-images.githubusercontent.com/77065706/172232861-29d31094-a18b-4936-8057-520fc25eb408.png)
