### ISSUE TITLE
[Request] [UI] Plus-button to the right of tabs => new tab

### ISSUE THREAD

**Issue by elofu17** [notepad-plus-plus/notepad-plus-plus#11724]
Feature request:

Apart from pressing Ctrl-N or clicking the [New] button to the left, please add a [+] button to the right of the tabs, to easily create a New tab.
(just like you do to start a new tab in web browsers)

Also see discussion in https://community.notepad-plus-plus.org/topic/23032/plus-to-the-right-of-tabs-new-tab where, among other things, an undocumented workaround was suggested to me:
Simply doubleclick in the whitespace where the Plus-button would be, and a New tab will appear.

**Comment by alankilborn** [comment]
>please add a [+] button to the right of the tabs

Example from Edge browser, for hopefully maximum clarity of what is being requested:

![image](https://user-images.githubusercontent.com/77065706/170354190-645291af-64a6-4093-8e29-7f070db4d15f.png)

**Comment by ozone10** [comment]
[+] button/tab right next to tabs can cause issue, when there are several tabs and overflow is created, as button than could be hidden.

Also what about multi-line tabs, should it be next to last tab on last line, or on first line?
What about other view, should [+] button be created for each views?

Using [+] button with fixed position seems better.

What do you think about this, we already have close button here.
![image](https://user-images.githubusercontent.com/55940305/170492515-186d9f13-3cee-4542-b538-f18150cacfeb.png)

**Comment by elofu17** [comment]
To me, that location is unintuitive.
In any program I expect to find the New button up to the left (where it already is), and if the program has a tab-bar, then I expect to always see a + to the right of the last tab.

**Comment by ozone10** [comment]
I know web browsers and some terminals have plus button next to last tab, but no text editor.
I have tried many text editor and IDE with GUI with tabs and IIRC only two have plus button right, not next to last tab, but in fixed position. So I don't expect plus button next to last tab in text editor.

Also how should we solve this
![image](https://user-images.githubusercontent.com/55940305/170774615-2e7e4e7b-233a-4769-8b17-d5e995dd5b30.png)
last tab is hidden.

Implementing this isn't easy, and for such minor ui feature I don't think it will done soon.

**Comment by alankilborn** [comment]
Desired feature added in Notepad++ 8.4.3.
Please CLOSE this issue.
