### ISSUE TITLE
Notepad++ is not run when Windows 10 restores its previous session (in moment of user login)

### ISSUE THREAD

**Issue by piomiq** [notepad-plus-plus/notepad-plus-plus#11721]
### Description of the Issue
I'm not sure is Notepad++ is not run in moment when Windows 10 restore its previous session, because I use portable version or this is not some how supported in Notepad++

### Steps to Reproduce the Issue
1. Turn on restore session in Windows 10
2. Run Notepad++
3. Log off or restart Windows
4. Login again

### Expected Behavior
Notepad++ should be run when Windows 10 restores its session (in moment of user login)

### Actual Behavior
Notepad++ isn't run when Windows 10 restores its session (in moment of user login)

**Comment by xomx** [comment]
@piomiq 
I am just finished a fix, which is needed before anyone could try a PR for this. If everything will be ok (let's say after that fix will be incorporated and released in a future N++ release, so N++ users will be able to test it and confirm its correctness), I will try to add this functionality (like some browsers, e.g. the Google Chrome, have) in a subsequent PR.
