### ISSUE TITLE
Notepad++ crashes when moving the "Find In Files progress" window while the search finishes 

### ISSUE THREAD

**Issue by Ede123** [notepad-plus-plus/notepad-plus-plus#1172]
When the search finishes while one is moving around the "Find In Files progress" window with the mouse Notepad++ crashes (or rather becomes unresponsive and has to be killed).

I'm consistently seeing this behavior in Notepad++ 6.8.6 on Windows 7 x64.

Pinging @pnedev since he has done most of the work on the progress bar if I remember correctly.

**Comment by donho** [comment]
@Ede123 Can you reproduce all the time? I can not reproduce hanging at all.

**Comment by Ede123** [comment]
Yes it's always reproducible for me with the following steps:
- Open a file
- Open the Find in Files dialog
- Execute a search "In all sub-folders"
- While the search is running grab the progress bar dialog with the mouse (and hold it!)
- When the search finishes instead of showing results Notepad++ becomes unresponsive

It is important to hold the dialog during the time the search operation finishes. If one lets go of the dialog before the search operation finishes the problem does not occur,

**Comment by linquize** [comment]
Similar problem: In old win xp,  if you drag the title bar of explorer copy progress dialog,  the operation is suspended until you release.

**Comment by dail8859** [comment]
> It is important to hold the dialog during the time the search operation finishes.

Yep doing this part specifically causes it to crash every time for me.
