### ISSUE TITLE
There won't be the standard icon large set as internal option, since I don't have the large set.

### ISSUE THREAD

**Issue by drakkar20d** [notepad-plus-plus/notepad-plus-plus#11735]
instructions
1. Put the file "toolbarIcons.xml" (Note 1) in the same folder of "config.xml" file (Note 2).

sorry Don but there is no config.xml file it doesn't exist

**Comment by ozone10** [comment]
https://github.com/notepad-plus-plus/notepad-plus-plus/commit/d85b9a7464b681a3e9363b12666e90c4859edbef#commitcomment-74782292


>  2. If you find the file "doLocalConf.xml" in the Notepad++ installed directory, you will find the "config.xml" in Notepad++ installed directory. Otherwise it should be in >"%APPDATA%\Notepad++" directory.

**Comment by drakkar20d** [comment]
ok found it in   Users\Myname\AppData\Roaming\Notepad++   followed the instructions , still doesn't work , does it matter if I'm running windows 7 ?

**Comment by ArkadiuszMichalski** [comment]
@drakkar20d I would suggest practicing on the portable version first.
