### ISSUE TITLE
Tabella

### ISSUE THREAD

**Issue by Soldo07** [notepad-plus-plus/notepad-plus-plus#11736]
1. <table border =1 width=100% height=100%>
2.  
3. <tr height=20% bgcolor=red>
4.  <td></td>
5.  <td></td>
6. <tr/>
7. 
8. <tr>
9.   <td></td>
10.  <td></td>
11. <tr/>
12. 
13. <tr>
14.   <td></td>
15.  <td></td>
16. <tr/>
17. 
18. <table/>

**Comment by rdipardo** [comment]
Brava tabella; però esistono miglior luoghi per giocare con Markdown: https://markdownlivepreview.com
