### ISSUE TITLE
JSON syntax highlighting error when escaping a quote right after a link

### ISSUE THREAD

**Issue by uWynell** [notepad-plus-plus/notepad-plus-plus#11746]
### Description of the Issue
JSON syntax highlighting error when escaping a quote right after a link

But the syntax highlighting for it isn't:
![image](https://user-images.githubusercontent.com/65278392/171052692-aa8b4b36-fea8-4dd4-9522-90fa220305fd.png)
However if I add a space, for example, before the backslash, the highlighting is completely correct again:
![image](https://user-images.githubusercontent.com/65278392/171052750-c570999c-7c91-4acb-b683-f0a62c03d2d8.png)

### Debug Information

Notepad++ v8.4.1   (64-bit)
Build time : May  8 2022 - 19:51:18
Path : D:\Users\Wynell\AppData\Local\Temp\Rar$EXa7020.16065\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : ON
Cloud Config : OFF
OS Name : Windows 10 Pro (64-bit) 
OS Version : 2009
OS Build : 19044.1706
Current ANSI codepage : 1251
Plugins : none

**Comment by rdipardo** [comment]
Exact duplicate of #11467 and ScintillaOrg/lexilla#72

**Comment by uWynell** [comment]
:\
