### ISSUE TITLE
Regular Expression - [A-Z] pattern does not work

### ISSUE THREAD

**Issue by robbi73** [notepad-plus-plus/notepad-plus-plus#11745]
### Description of the Issue

Regular Expression - [A-Z] pattern does not work
It does not distinguish between uppercase and lowercase.

### Steps to Reproduce the Issue

1. CTRL+F to open search panel
2. Check the regular expression checkbox
3. Write [A-Z] in "search" text filed
4. Push the "Find Next" button.

### Expected Behavior

I'd like the searching tool highlight only uppercase letters

### Actual Behavior

Every letter both lowercase and uppercase is highlighted

### Debug Information

Notepad++ v8.3.3   (64-bit)
Build time : Mar 13 2022 - 17:20:02
Path : D:\Program Files\Notepad++\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 10 Enterprise (64-bit) 
OS Version : 2009
OS Build : 19044.1706
Current ANSI codepage : 1252
Plugins : ComparePlugin.dll jN.dll JsMapParser.NppPlugin.dll JSMinNPP.dll mimeTools.dll NppConverter.dll NppExport.dll NPPJSONViewer.dll RegexTrainer.dll XMLTools.dll

**Comment by alankilborn** [comment]
Two options:

* tick the _Match case_ box
* start the regular expression with `(?-i)`

**Comment by robbi73** [comment]
It seemed to me that in the past it also worked without these workaraounds.
Anyway, thanks for the tips

**Comment by alankilborn** [comment]
It has always worked this way; these are not workarounds.
Please close the issue.
