### ISSUE TITLE
Selected text changes color/styling/lexing when editor window loses focus

### ISSUE THREAD

**Issue by alankilborn** [notepad-plus-plus/notepad-plus-plus#11743]
### Description of the Issue
When selected foreground coloring is enabled by creating the enableSelectFgColor.xml file in the same folder as config.xml lives, selected foreground coloring works when text is selected, but doesn't display correctly when editor window loses input focus.

### Steps to Reproduce the Issue
1.  Create a zero-length file named enableSelectFgColor.xml file in the same folder as config.xml lives
2.  Run Notepad++
3. Load an .xml file, e.g. langs.xml
4. Select some text; observe the coloring of the selected text:
![image](https://user-images.githubusercontent.com/77065706/170885853-790287bc-f227-4430-bdea-45d4ec789840.png)
5. Invoke _Find_ window via Ctrl+f.
6. Observe the same selected text as before in the editor window now appears styled/colored/lexed like this:
![image](https://user-images.githubusercontent.com/77065706/170885900-0a7b820e-d5b2-4a96-a2f0-99d26e710d6c.png)

### Expected Behavior
Coloring of selected text remains as shown in step 4.

### Actual Behavior
Coloring of selected text changes to that shown in step 6.

### Debug Information
Notepad++ v8.4.1   (64-bit)
Build time : May  8 2022 - 19:51:18
Path : C:\...\npp.8.4.1.portable.x64\notepad++.exe
Command Line : -titleAdd="8.4.1 64-bit" -multiInst "C:\...\1\npp.8.4.1.portable.x64\license.txt"
Admin mode : OFF
Local Conf mode : ON
Cloud Config : OFF
OS Name : Windows 10 Enterprise (64-bit) 
OS Version : 2009
OS Build : 19042.1645
Current ANSI codepage : 1252
Plugins : mimeTools.dll NppConverter.dll NppExport.dll PythonScript.dll 

### Misc

See:

* https://community.notepad-plus-plus.org/post/77104 
* https://community.notepad-plus-plus.org/topic/23038/selected-text-goes-funky-when-n-loses-focus

**Comment by rdipardo** [comment]
As a guess, it could be that 9cc01de9 forgot about this particular use case. 
Maybe the default value of `forceApplyHilite` should be `true` instead?

https://github.com/notepad-plus-plus/notepad-plus-plus/blob/b5479bb9b0ab70ce909bb0da46894bb1b011c383/PowerEditor/src/Notepad_plus.h#L453

**Comment by Yaron10** [comment]
https://www.scintilla.org/ScintillaDoc.html#SC_ELEMENT_SELECTION_INACTIVE_TEXT
(I haven't tested it).

**Comment by rdipardo** [comment]
> https://www.scintilla.org/ScintillaDoc.html#SC_ELEMENT_SELECTION_INACTIVE_TEXT

That leaves me even more confused.
The foreground style option has existed since N++ 8.0: cd1a468b1c0b6668daac4f9ff01f8a806699cb91
N++ inherited the `SC_ELEMENT_SELECTION_INACTIVE_TEXT` message only after [upgrading to Scintilla 5.2.1][0].

How did this feature work in previous releases? Or was it always broken as the OP described?

[0]: https://github.com/notepad-plus-plus/notepad-plus-plus/blob/a61b03ea8887e21c6e1b7374068962f635b79b80/scintilla/include/Scintilla.h#L287

**Comment by Yaron10** [comment]
@rdipardo,

> How did this feature work in previous releases?

`SC_ELEMENT_SELECTION_INACTIVE_TEXT` did not exist in older versions, nor the difference between selection-focused and selection-unfocused.

See https://github.com/notepad-plus-plus/notepad-plus-plus/commit/3b0d5242acd23b4a727560ea98139cc5f4a8b88a.

I suppose that adding `SC_ELEMENT_SELECTION_INACTIVE_TEXT` after
https://github.com/notepad-plus-plus/notepad-plus-plus/blob/3b0d5242acd23b4a727560ea98139cc5f4a8b88a/PowerEditor/src/ScintillaComponent/ScintillaEditView.cpp#L2599
should fix the current issue.

**Comment by alankilborn** [comment]
>was it always broken as the OP described?

It was not broken until recently.
I just moved from 8.2.1 to 8.4.1 and it was working fine in 8.2.1.

**Comment by rdipardo** [comment]
> It was not broken until recently.

Since 3b0d5242, in fact:

https://github.com/notepad-plus-plus/notepad-plus-plus/blob/b5479bb9b0ab70ce909bb0da46894bb1b011c383/PowerEditor/src/ScintillaComponent/ScintillaEditView.cpp#L2617

This bug is the price of fixing [another breaking change in Scintilla 5 upgrade](https://github.com/notepad-plus-plus/notepad-plus-plus/issues/11595#issuecomment-1111293326):

> Scintilla 5+ now uses `SC_ELEMENT_SELECTION_INACTIVE_BACK` to provide highlighting on selected text when the window loses focus. The default may not match well with light / dark color schemes and / or foreground text color.

**Comment by rdipardo** [comment]
@Yaron10,
> https://www.scintilla.org/ScintillaDoc.html#SC_ELEMENT_SELECTION_INACTIVE_TEXT

You were right #1744

![selectColorFore-inactive-buffer](https://user-images.githubusercontent.com/59004801/170909676-a072e892-3e23-474b-a089-3d303fcc5698.png)
