### ISSUE TITLE
UI: Find Dialog text alignment

### ISSUE THREAD

**Issue by Octal450** [notepad-plus-plus/notepad-plus-plus#11747]
### Description of the Issue

The text to the left of the boxes is misaligned and too close to the input boxes, in an older release these were placed correctly. The "Directory :" below is closer to correct.

![image](https://user-images.githubusercontent.com/25598604/171076364-8fea0385-f036-4b4f-b07e-94523a2ddd41.png)

Sometimes, it causes the following visual bug also:
![image](https://user-images.githubusercontent.com/25598604/171081593-8c03366c-5782-46fd-8f17-08034168ba88.png)

### Steps to Reproduce the Issue

1. Open NP++
2. Press CTRL+F

### Expected Behavior

The text should be placed farther from the input box

### Actual Behavior

The text has been moved too close to the input boxes

### Debug Information

Notepad++ v8.3.3   (64-bit)
Build time : Mar 13 2022 - 17:20:02
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 10 Pro (64-bit) 
OS Version : 2009
OS Build : 19044.1706
Current ANSI codepage : 1252
Plugins : mimeTools.dll NppConverter.dll NppExport.dll NppToolBucket.dll TopMost.dll 

Also, I wonder if there should be a space between "Find what" and the : anyways, should it not be "Find what:" ?

**Comment by dfs-** [comment]
I fixed that, update your NPP.

**Comment by dail8859** [comment]
As suggested by @dfs- please update Notepad++. If the issue still occurs post a screenshot and this can be reopened.

**Comment by Octal450** [comment]
You're right, my mistake. I apologize for the confusion. The updater kept saying "no update available", I had to manually update. 

Kind Regards,
Josh
