### ISSUE TITLE
Plugin Admin not visible

### ISSUE THREAD

**Issue by ganego** [notepad-plus-plus/notepad-plus-plus#11742]
### Description of the Issue
I have no menu entry Plugins -> Plugin Admin.

### Steps to Reproduce the Issue
1. Removed `C:\Users\xxx\AppData\Roaming\Notepad++`
2. Removed `C:\Program Files (x86)\Notepad++`
3. Installed `npp.8.4.2.Installer.exe` (with Plugins & Plugin Admin enabled)

I have this file: `"C:\Program Files (x86)\Notepad++\plugins\Config\nppPluginList.dll"`.  
I read some posts on the forum about this issue, but nothing that helped.

### Debug Information
```
Notepad++ v8.4.2   (32-bit)
Build time : May 28 2022 - 04:29:32
Path : C:\Program Files (x86)\notepad++\notepad++.exe
Command Line : $COMMAND_LINE_PLACEHOLDER$
Admin mode : ON
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 7 Ultimate (64-bit) 
OS Build : 7601.0
Current ANSI codepage : 1252
Plugins : 
    mimeTools (2.8)
    NppConverter (4.4)
    NppExport (0.4)
```

Thank you

**Comment by rdipardo** [comment]
Same issue with the portable version.

    Notepad++ v8.4.2   (32-bit)
    Build time : May 28 2022 - 04:29:32
    Path : C:\bin\npp_8.4.2_x86\notepad++.exe
    Command Line : $COMMAND_LINE_PLACEHOLDER$
    Admin mode : OFF
    Local Conf mode : ON
    Cloud Config : OFF
    OS Name : Windows 11 (64-bit) 
    OS Version : 21H2
    OS Build : 22000.708
    Current ANSI codepage : 65001
    Plugins : 
        HTMLTag_unicode (1.3)
        mimeTools (2.8)
        NppConverter (4.4)
        NppExport (0.4)
