### ISSUE TITLE
New file in a new Instance

### ISSUE THREAD

**Issue by eymre** [notepad-plus-plus/notepad-plus-plus#1176]
When notepad++ is open with some files, is there an easy way to start a new notepad++ window (new Instance) with a blank document? Multi-Instance setting is set to Default (mono-instance).

Currently the easiest I found is a 5-step process:
1. Make sure there are at least two saved documents open in npp
2. Tear-off (drag the document tab) one of the documents into a new instance
3. Ctrl+N in the new instance to create a blank document
4. Type something in the blank document
5. Move the saved document from new instance back into the old instance

Thanks,

**Comment by donho** [comment]
Make a shortcut icon with "-multiInst" on the desktop will do it.
