### ISSUE TITLE
In Style Configurator / Global Styles / Global override and Default Style, the Font Style / Font size setting is reset to default 10 value, after each new release applied

### ISSUE THREAD

**Issue by script24546** [notepad-plus-plus/notepad-plus-plus#11777]
**Description of the Issue**
From a while (since a few updates), on each new release applied, in Settings / Style Configurator / Global Styles / Global override and Default Style, the Font Style / Font size setting we’ve made, is automatically overwritten with the default 10 value. So we have to manually revert back to our own settings which is again overwritten with 10 on next release

**Steps to Reproduce the Issue**
1. Go to Settings
2. next, to Style Configurator
3. in Global Styles language
4. in each Style, at first "Global override" Style, then with "Default Style" Style
5. watch the Font size value in the Font Style section, which revert back to default 10, if already set to a different value previously

**Expected Behavior**
Previously custom setting shouldn't have been revert back to Default 10 Font size after applying the last Notepad++ update

**Actual Behavior**
The Font Size is updated and revert back to 10 value, as for an initial installation

**Debug Information**
Notepad++ v8.4.2   (64-bit)
Build time : May 29 2022 - 16:47:30
Path : C:\Tools\Notepad++\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 10 Pro (64-bit) 
OS Version : 21H2
OS Build : 19044.1741
Current ANSI codepage : 1252
Plugins : 
    AutoEolFormat (1.0.2)
    ComparePlugin (2.0.2)
    CsvQuery (1.2.8)
    DSpellCheck (1.4.23)
    JSFunctionViewer (1.1)
    JSMinNPP (1.1905.1)
    mimeTools (2.8)
    NppConverter (4.4)
    NppExport (0.4)
    NPPJSONViewer (1.34)
    NppXmlTreeviewPlugin (0.1)
    SQLinFormNpp64 (5.3.35)
    urlPlugin (1.1)
    XMLTools (3.1.1.12)
    zoomdisabler_x64 (1.2)

![image](https://user-images.githubusercontent.com/107255490/173072903-dc75f0bd-b671-45f7-9e38-624ca250037f.png)

![image](https://user-images.githubusercontent.com/107255490/173072800-a18ec421-36a5-405e-95e1-7bda813d08b4.png)

**Comment by donho** [comment]
Hmm... I cannot reproduce it - after re-installing Notepad++, my font size setting remains 16.
