### ISSUE TITLE
NotePad++ "Latest Version" Download Link

### ISSUE THREAD

**Issue by TonyValenti** [notepad-plus-plus/notepad-plus-plus#11771]
Hi @donho -
I make an app that a number of IT consultants use.  One of the features we have is an "Install NotePad++" button.  If it isn't installed, it downloads the installer and launches it.

Is there a link that we can use that will always download the latest version's installer?

**Comment by javiergutierrezchamorro** [comment]
Great idea. Maybe the solution would be creating a LATEST link here http://download.notepad-plus-plus.org/repository/

**Comment by ts-50** [comment]
I like this idea a lot.

**Comment by rddim** [comment]
Try https://notepad-plus-plus.org/update/getDownloadUrl.php

**Comment by TonyValenti** [comment]
@rddim This is great!  Are there any params I can put that will cause an automatic redirect to the download Url?
Looking to do something like this:

https://notepad-plus-plus.org/update/getDownloadUrl.php?redirect=true

**Comment by rddim** [comment]
@TonyValenti 
I'm sorry I can't answer your question. I'm not familiar with this, but I'm sure will find the answers in https://github.com/notepad-plus-plus/wingup. Also `GUP.exe` should be available in your `\Notepad++\updater` directory. The link in my previous comment is from `gup.xml`
