### ISSUE TITLE
[MSVC] Optimization flags and VS 2022 (v143)

### ISSUE THREAD

**Issue by ozone10** [notepad-plus-plus/notepad-plus-plus#11778]
@donho 
some question about optimization flags and VS 2022 (v143):
Why is whole program optimization enabled here (example for x64 here, same applies to x86 and arm64 )
https://github.com/notepad-plus-plus/notepad-plus-plus/blob/f517c6c05367543729e29cd5e70fcc3b9f92f929/PowerEditor/visual.net/notepadPlus.vcxproj#L47
but disabled here? Deleting this line will enable whole program optimization.
https://github.com/notepad-plus-plus/notepad-plus-plus/blob/f517c6c05367543729e29cd5e70fcc3b9f92f929/PowerEditor/visual.net/notepadPlus.vcxproj#L306

It's better to use /O2 instead of /Ox, replacing line below with `<Optimization>MaxSpeed</Optimization>` will apply it.
https://github.com/notepad-plus-plus/notepad-plus-plus/blob/f517c6c05367543729e29cd5e70fcc3b9f92f929/PowerEditor/visual.net/notepadPlus.vcxproj#L302

IIRC some MS developers consider flag /Ox evil.

Also what do you think about updating to VS 2022 (v143)?
VS 2022 is 64-bit, which allow to use more memory, which might have performance improvements for some tasks for developers.

**Comment by donho** [comment]
@ozone10 
No idea about the disabled optimization. I set this value always via GUI:

![image](https://user-images.githubusercontent.com/90293/173107191-8869e9e6-4a79-47a6-b5b0-ab44c717b235.png)

> It's better to use /O2 instead of /Ox, replacing line below with <Optimization>MaxSpeed</Optimization> will apply it.
IIRC some MS developers consider flag /Ox evil.

You might be right. With some searches on Google, I found this:
https://stackoverflow.com/questions/2722302/can-compiler-optimization-introduce-bugs

I can modify it from /Ox to /O2 via GUI of VS. Or you prefer to modify directly the XML file? 

> Also what do you think about updating to VS 2022 (v143)?
VS 2022 is 64-bit, which allow to use more memory, which might have performance improvements for some tasks for developers.

I have VS 2022 installed in dev machine, but in PROD machine I still prefer use VS2019 for the sake of compatibility issue.

**Comment by ozone10** [comment]
@donho 
Both lexilla and scintilla have whole program optimization enabled, so I would also enable it for notepad++.
For whole program optimization I would delete it from XML directly, for /O2 it can be done via GUI, it will have same effect.

About v143, I think there shouldn't be any compatibility issue. It was released last year in November, so what about updating it after summer.

**Comment by donho** [comment]
@ozone10 
OK, I will apply your suggestion about the program optimization.
Regarding the change of toolkit version, I prefer to wait a little while.
Thank you for your suggestion.
