### ISSUE TITLE
Hide Line Number Margin toolbar icon not actually hiding the margin for me

### ISSUE THREAD

**Issue by BillH99999** [notepad-plus-plus/notepad-plus-plus#11779]
### Description of the Issue

I am having a problem with the Hide Line Number Margin icon in the toolbar.  I'm not sure if I am misunderstanding what that icon is supposed to do or if there is a bug.  I searched in the online manual, but couldn't find a description of the icons purpose.

### Steps to Reproduce the Issue

1. In the Preferences, have the option turned on to display line numbers.
2. Open a document and verify that line numbers are displayed in a margin at the left.
3. Click on the Hide LIne Numbers Margin icon in the toolbar.

### Expected Behavior

I expected the line number margin to be hidden.  

### Actual Behavior

The line number margin is not hidden.  It is still showing.  In comparison, the Hide Bookmark Margin works fine and does hide that margin.

### Debug Information

Notepad++ v8.4.2   (64-bit)
Build time : May 29 2022 - 16:47:30
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : $COMMAND_LINE_PLACEHOLDER$
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 10 Pro (64-bit) 
OS Version : 21H2
OS Build : 19044.1706
Current ANSI codepage : 1252
Plugins : 
    DSpellCheck (1.4.23)
    mimeTools (2.8)
    NppConverter (4.4)
    NppExport (0.4)
    _CustomizeToolbar (4.2)

The only way I can hide the line number margin is to go into Settings and de-select Display for the line number.

**Comment by alankilborn** [comment]
>I am having a problem with the Hide Line Number Margin icon in the toolbar

I hate to break the news to you, but Notepad++ has no such toolbar button.
If you're using some sort of Notepad++ extension (e.g. a plugin) to do this, then perhaps you should look for support wherever that extension is supported.  
Or maybe ask on the [Community](https://community.notepad-plus-plus.org/).

**Comment by BillH99999** [comment]
I am using the plugin Customize Toolbar, but I didn't realize it isn't part of Notepad++.  As it is listed in the Plugins Admin, I thought that it was part of Notepad++.   Is there an easy way to toggle the Line Numbers header on and off without having to go into the preferences?

Thanks,
Bill

**Comment by alankilborn** [comment]
>Is there an easy way to toggle the Line Numbers header on and off without having to go into the preferences?

I don't know if you'd consider it "easy" or not, but you could use the PythonScript plugin and a bit of code.

First, set this Preference (one time only) as follows, to turn off Notepad++ controlling the line number margin:
![image](https://user-images.githubusercontent.com/77065706/173187086-3d9228b5-32f9-4b68-a43b-bd7ffd5e6a9d.png)

Then, with the PS plugin, a console command such as `editor.setMarginWidthN(0,40)` will show the line numbers and `editor.setMarginWidthN(0,0)` will hide it.

A script could be made to toggle the functionality (and that script could be tied to a keycombo for easy running):

`editor.setMarginWidthN(0, 40 if editor.getMarginWidthN(0) == 0 else 0)`

Notes:
* the line number margin is margin number 0 (first argument to the functions)
* the default width of the line number margin is 40
* further info on using the PS plugin may be obtained [HERE](https://community.notepad-plus-plus.org/topic/23039/faq-desk-how-to-install-and-run-a-script-in-pythonscript/1).

**Comment by BillH99999** [comment]
Thanks for the reply.  I guess the answer to my question is no.  :-)

This is out of my comfort level.  It would be really nice if there were a toolbar icon or a key combination that would toggle the line number margin on and off.  This would be a nice enhancement to the program.  I use the line number margin sometimes when I edit a document, but I don't want the line numbers to appear when I print.

Thanks,
Bill

**Comment by alankilborn** [comment]
>This is out of my comfort level.

Freedom of choice.  It seems ridiculous that you could have the functionality you want today and yet you turn it down for such a reason, in favor of waiting an indeterminate amount of time for developers to _maybe_ think your request is reasonable for the core software, and then _maybe_ find the time to implement it.  Cheers.

**Comment by ArkadiuszMichalski** [comment]
Due to changes in Notepad++ this icon from CustomizeToolbar will not work:
https://github.com/notepad-plus-plus/notepad-plus-plus/issues/9631

**Comment by alankilborn** [comment]
Complaint seems to be against a plugin rather than Notepad++ itself.
Thus recommend CLOSURE of this item.
