### ISSUE TITLE
The portable version of the configuration file save path is incorrect

### ISSUE THREAD

**Issue by fxqy** [notepad-plus-plus/notepad-plus-plus#11783]
### Description of the Issue
 In the portable version8.4.2, windows10.19044.1741 , the configuration file is saved to ```User/*/AppData/Remoting/notepad++```, including the profile of the plugin

This problem does not exist in older versions of Windows!

**Comment by alankilborn** [comment]
Where's all the stuff you were supposed to fill in for the issue template?

**Comment by fxqy** [comment]
### Description of the Issue
In the portable version8.4.2, windows10.19044.1741 , the configuration file is saved to ```C:\Users\Dong\AppData\Roaming\notepad++```, including the profile of the plugin

This problem does not exist in older versions of Windows!

### Steps to Reproduce the Issue
1. run portable notepad++ in window 19044.1741
2. check 'C:\Users\*\AppData\Roaming'

### Expected Behavior
want the portable version of the configuration file to be saved in the ‘notepad++’ directory

### Actual Behavior
 the configuration file is saved to ```C:\Users\Dong\AppData\Roaming\notepad++```

### Debug Information
```
Notepad++ v8.4.2   (64-bit)
Build time : May 29 2022 - 16:47:30
Path : C:\notepad++\notepad++.exe
Command Line : $COMMAND_LINE_PLACEHOLDER$
Admin mode : ON
Local Conf mode : ON
Cloud Config : OFF
OS Name : Windows 10 Enterprise G (64-bit) 
OS Version : 21H2
OS Build : 19044.1741
Current ANSI codepage : 936
Plugins : 
    JSMinNPP (1.2205)
    mimeTools (2.8)
    NppConverter (4.4)
    NppExport (0.4)
    NppJavaPlugin (0.4)
    QuickText (0.2.4.1)

```

![image](https://user-images.githubusercontent.com/42601163/173227462-5c4e04ff-fab3-4dae-96a6-68957636c6ac.png)

![image](https://user-images.githubusercontent.com/42601163/173227482-4220d82d-7bf9-404e-9706-5860cc517f51.png)

**Comment by donho** [comment]
I cannot reproduce the bug at all.
Can anyone else reproduce it?

**Comment by fxqy** [comment]
I went back to version 7.8.2 and everything worked fine.

**Comment by ts-50** [comment]
> I cannot reproduce the bug at all. Can anyone else reproduce it?

If I am understanding the issue correctly, then yes I can reproduce with 8.4.2.
![image](https://user-images.githubusercontent.com/19561856/173594802-b78e612b-2b6b-4d21-a16f-ae397253e3f8.png)

Debug info:

Notepad++ v8.4.2   (64-bit)
Build time : May 29 2022 - 16:47:30
Path : C:\Users\thoma\Desktop\npp.8.4.2.portable.x64\notepad++.exe
Command Line : $COMMAND_LINE_PLACEHOLDER$
Admin mode : OFF
Local Conf mode : ON
Cloud Config : OFF
OS Name : Windows 11 (64-bit) 
OS Version : 21H2
OS Build : 22000.675
Current ANSI codepage : 1252
Plugins : 
    mimeTools (2.8)
    NppConverter (4.4)
    NppExport (0.4)

**Comment by ArkadiuszMichalski** [comment]
I also can't reproduce this.

**Comment by fxqy** [comment]
After testing, the 8.4.3 version no longer has the problem（win10.19044.1741）
