### ISSUE TITLE
Notepad++ auto updated to 8.4.2

### ISSUE THREAD

**Issue by Mac404** [notepad-plus-plus/notepad-plus-plus#11785]
Hi Everyone

I updated NP++ to v8.4.2 a few days ago. Upon launch it complains about incompatibility of csvlint.dll and prompting to remove it, it wouldn't delete it for me, so I manually deleted it. However, before the above noted problem and even after deleting it, after the exit, I get an exception msg 0xc0000005 unexpected parameters, screenshot included.  Not sure what's causing the error. Do I need to roll back?

Thanks

![np++ error](https://user-images.githubusercontent.com/70410606/173255529-02d8765e-e974-4227-9e54-b7cb84c7c567.png)
![np++ error1](https://user-images.githubusercontent.com/70410606/173255546-391c805b-e161-4461-bb40-fbc328365309.png)

**Comment by rdipardo** [comment]
> ![np++ error1](https://user-images.githubusercontent.com/70410606/173255546-391c805b-e161-4461-bb40-fbc328365309.png)

The technical explanation is [here](https://community.notepad-plus-plus.org/topic/22866/make-external-lexer-plugin-work-with-v8-4) and [here](https://community.notepad-plus-plus.org/topic/22787/remove-the-external-lexer-support-due-to-scintilla-5). This is not a bug in Notepad++. Just replace `CSVLint.dll` with the [latest version](https://github.com/BdR76/CSVLint/releases/tag/0.4.5.2) and it should be fine.

**Comment by donho** [comment]
https://github.com/BdR76/CSVLint/issues/24#issuecomment-1153373190

**Comment by donho** [comment]
Use the newest version will fix the crash.
However, I have just added the compatibility info of CVS Lint :
https://github.com/notepad-plus-plus/nppPluginList/commit/7cddde97112d5d2d7f0758167d255e1d4ef020cc
So it won't happen in next version of Notepad++.

**Comment by Mac404** [comment]
Thank you gentlemen for your quick replies. That worked and I don't get the error anymore. Thanks :)
