### ISSUE TITLE
[Feature Request] Make Search/Replace Dialog Collapsible

### ISSUE THREAD

**Issue by peterthoeny** [notepad-plus-plus/notepad-plus-plus#11780]
### Description of the Enhancement Request

Enhancement request for usability: Make the search & replace dialog collapsible, and show only the minimum content needed when collapsed. The dialog can already be made semi-transparent, which helps a bit. However, the collapsed dialog will use very little space, and offers the functionality 90% of the time.

### Expected Behavior

1. The default is expanded, showing a collapse icon on the lower right:

![notepadpp-search-1](https://user-images.githubusercontent.com/46544951/173128697-e495462e-3572-4493-a4f7-4c80d5950101.png)

Same for Replace and other tabs:

![notepadpp-replace-1](https://user-images.githubusercontent.com/46544951/173128755-4c80e2be-f064-49a5-bf54-d0ce8060d596.png)

2. Once you click on the collapse icon you get the collapsed view that shows the expand icon in the lower right:

![notepadpp-search-2](https://user-images.githubusercontent.com/46544951/173128867-32d7c85c-f0ce-40c4-956d-faf211bf6ff2.png)

![notepadpp-replace-2](https://user-images.githubusercontent.com/46544951/173128883-9d41e203-04be-4f1e-8397-349c42b7a1a9.png)

3. Remember the state between application runs.

Thank you for Notepad++, it's a great editor! Thank you for the consideration for this suggestion.

**Comment by dfs-** [comment]
For search there already is the "incremental search" (CTRL+ALT+I). Is this something that fits your needs maybe expanded to include a replace method as well?

**Comment by alankilborn** [comment]
@peterthoeny This is not a bad idea, but a problem with it is that the options are very important and are not available in your suggested smaller window. 

It would be nice if the button to shrink the window (I like it as the symbol you show) produced something small like Visual Studio uses. but yet has all the options at hand:

![image](https://user-images.githubusercontent.com/77065706/173576698-be4ff6b4-42e1-481a-aefa-587aa9219e74.png)

The little up arrow to the left of Find in the VS window merely changes a replace-view into a find-view, but in Notepad++, there could be the addition of a symbol like you show that would restore the existing Notepad++ window:

![image](https://user-images.githubusercontent.com/77065706/173577254-e55c85ce-f735-4b46-9afd-a9781a356f8c.png)

Of course it isn't a perfect model, just some thoughts.

**Comment by peterthoeny** [comment]
@dfs-: I don't find the Incremental Search intuitive, and the options are too limiting. For example, I prefer to always have regex on.

@alankilborn: IRT "but a problem with it is that the options are very important and are not available in your suggested smaller window." My whole point is to be able hide rarely used options. For example, I always search with regex on, so once my preferred search is set, I don't need the clutter. I can change my mind and temporarily expand the dialog.

Yes, the options on the dialog could be squeezed a bit, but I think the two rows in the collapsed view are sufficient for most use cases. For search (not replace), I frequently use the count button, hence better to keep the two rows for search.

**Comment by alankilborn** [comment]
@peterthoeny Ok, but to "sell" the feature you maybe have to go a bit beyond how an individual user (you) would work with it.

**Comment by peterthoeny** [comment]
@alankilborn: not sure I understand what you are asking for. More examples?

**Comment by peterthoeny** [comment]
@donho: What is your take on this feature request?

**Comment by alankilborn** [comment]
>not sure I understand what you are asking for. More examples?

Nope.  I'm not asking for anything.  You are. :-)

**Comment by peterthoeny** [comment]
@donho: 
> self-assigned this [20 hours ago](https://github.com/notepad-plus-plus/notepad-plus-plus/issues/11780#event-6808800435)

Cool! Thank you for this fantastic editor!
