### ISSUE TITLE
Use color fonts by default

### ISSUE THREAD

**Issue by sohang3112** [notepad-plus-plus/notepad-plus-plus#11794]
# Feature Request
I suggest that support for [Color Fonts](https://docs.microsoft.com/en-us/windows/win32/directwrite/color-fonts) be added to Notepad++. This would allow Unicode characters (eg. emojis) to show in colour.

**Note:** The above link discusses how to use color fonts in Windows - however I am sure that similar methods for doing this exist in Linux and Mac also.

**Comment by sohang3112** [comment]
This would especially be useful for working with Markdown / HTML files that have Emojis in them.

**Comment by sohang3112** [comment]
@donho Is there any update on this issue?? If no one else is working on this issue, I would like to work on this issue - please confirm that you would be interested in a PR for this issue.

**Comment by DejayRezme** [comment]
@sohang3112 I was just wondering about this too. 
If you enable "DirectWrite" under preferences->MISC you get emoji's in color! (mentioned in bug 14578)

**Comment by sohang3112** [comment]
> If you enable "DirectWrite" under preferences->MISC you get emoji's in color!

Thanks @DejayRezme - that worked!
