### ISSUE TITLE
[FEATURE REQUEST] Allow to run multiple notepad++ instances

### ISSUE THREAD

**Issue by darkworks** [notepad-plus-plus/notepad-plus-plus#11793]
Currently we cant run multiple notepad++ instances , we one instance is running and if another one is run it will give error that one instance is already running. 

So i request add some sort of config file to notepad++ which is used to create different process to avoid conflict and we can run two independent instances. like i have one notepad++ installation on my laptop and one on my portable SSD where i have notepad++ installation and its two different workspaces so when i attach my ssd to laptop and open that notepad ++ instance am unable to run it because notepad++ is already running already on my laptop.  its hard to close notepad++ as there is tons of things are open in it.

thanks

**Comment by dfs-** [comment]
Just modify the settings:
![image](https://user-images.githubusercontent.com/6563013/173520029-a85b8419-8872-45b9-931b-e8e7343c0169.png)

**Comment by darkworks** [comment]
tested but not working :(

tried to run portable version of notepad++ from my portable drive so that it not conflict with my notepad++ running on my windows but no success

![image](https://user-images.githubusercontent.com/12841788/174135973-0e6e8d2f-e9dc-4f38-a3ab-a1f4f87073c7.png)

**Comment by dfs-** [comment]
Why do you use PortableApps stuff when Notepad++ comes with built-in portable mode. Nobody knows what the launcher might break.

**Comment by alankilborn** [comment]
PortableApps running of Notepad++ is not supported.  Please close this issue.

**Comment by darkworks** [comment]
> Why do you use PortableApps stuff when Notepad++ comes with built-in portable mode. Nobody knows what the launcher might break.

am not aware of it , i search in preference but i not found any settings , can u tell from where i can activate its portable mode so that it save everything on my portable SSD instead of my system appdata folder.
thanks

**Comment by alankilborn** [comment]
> i search in preference but i not found any settings , can u tell from where i can activate its portable mode so that it save everything on my portable SSD instead of my system appdata folder

See [HERE](https://npp-user-manual.org/docs/config-files/#:~:text=the%20configuration%20files%20go%20in%20the%20same%20directory%20as%20the%20notepad%2B%2B.exe%20executable.%20(An%20installation%20is%20treated%20as%20%E2%80%9Cportable%E2%80%9D%20if%20the%20zero%2Dbyte%20doLocalConf.xml%20file%20is%20present%20alongside%20the%20notepad%2B%2B.exe%20executable).

**Comment by alankilborn** [comment]
>i tried it but when i run notepadd++ from my SSD it just open another note pad instance which is of my system. i would like to operate two different independent instance of notepad++ in mono mode. so that the one running from SSD save everything on SSD and not conflict with my notepad++ instance running on my system in which i have already 50+ notes opened.

It sounds like you want a totally separate second copy of Notepad++ on your system to achieve something like this.  Your existing version could be an "installed" version, the second version would then be a "portable" version.  Portable versions are present on the Notepad++ download page (again, forget "Portable apps" junk).

**Comment by darkworks** [comment]
ok thanks i will give try to this portable version on official page.

**Comment by darkworks** [comment]
> > i tried it but when i run notepadd++ from my SSD it just open another note pad instance which is of my system. i would like to operate two different independent instance of notepad++ in mono mode. so that the one running from SSD save everything on SSD and not conflict with my notepad++ instance running on my system in which i have already 50+ notes opened.
> 
> It sounds like you want a totally separate second copy of Notepad++ on your system to achieve something like this. Your existing version could be an "installed" version, the second version would then be a "portable" version. Portable versions are present on the Notepad++ download page (again, forget "Portable apps" junk).

i have downloaded : npp.8.4.2.portable.x64.7z  and extracted it to my SSD , however when i run notepad++.exe then it just open to my existing system installed version. :(

**Comment by alankilborn** [comment]
You have to add `-multiInst` on the command line.

**Comment by darkworks** [comment]
> You have to add `-multiInst` on the command line.

great now it worked :) 
thanks

**Comment by alankilborn** [comment]
@darkworks If you are satisfied you should close this issue.
