### ISSUE TITLE
[Feature Request] Add Jump Points to GO TO window

### ISSUE THREAD

**Issue by darkworks** [notepad-plus-plus/notepad-plus-plus#11792]
I mostly code in notepad++ so i keep jumping back and forth in page and using **CTRL + G**  **Go To** line feature a lot and when i work let say on header and want to go  to middle of my code then i mostly forget where i was working and then have to scroll.

So i request that please add Notes / Jump Points option to GO TO window where user can add about 5 notes in to go to window which would allow him to jump to location quickly without remembering line numbers

something like this

![image](https://user-images.githubusercontent.com/12841788/173505175-b6e035ff-aea6-478a-a178-f0450feae0e7.png)

Also it will be good that these jump points line numbers updated too according with new + lines or - lines
like if i added 10 new lines before line # 100 then jump points should got update.

1: line #100                 coding header       JUMP
2: line #500                 coding body          JUMP 
3: line #750                 coding footer        JUMP

becomes

1: line #100  + 10                coding header       JUMP
2: line #500  + 10                coding body          JUMP 
3: line #750  + 10                coding footer        JUMP

or if i remove 10 lines before at line # 300 then 

1: line #100                       coding header       JUMP
2: line #500  - 10              coding body          JUMP 
3: line #750  - 10              coding footer        JUMP

i think this will be unique feature to notepad++ have not seen even in visual studio code

thanks

**Comment by alankilborn** [comment]
@darkworks 

I've proposed a different means of implementing your request, using a feature that Notepad++ already possesses (bookmarks), and created a mock-up of it in the form of a runnable demo, [HERE](https://community.notepad-plus-plus.org/topic/23128/all-bookmarks-list-view).

**Comment by darkworks** [comment]
> @darkworks
> 
> I've proposed a different means of implementing your request, using a feature that Notepad++ already possesses (bookmarks), and created a mock-up of it in the form of a runnable demo, [HERE](https://community.notepad-plus-plus.org/topic/23128/all-bookmarks-list-view).

well these bookmarks are saved collectively of all notes. i think its not good approach to save them collectively. because in situation like me where you have 70+ notes open in notepad++ and if am currently working in note # 3 and this bookmark file will open with a lot of other bookmarks and you have to switch between bookmark tab and your note tab back and forth. this approach is good for normal users but not for developers. if jump points for single note is maintain within its CTRL + G modal then will be good and when note is close it should be destroyed with it.

**Comment by alankilborn** [comment]
I'm not a Notepad++ developer, just a long-time user.  From that perspective I would say it is extremely unlikely that a feature such as what you describe would ever be implemented.  Perhaps you should consider developing a plugin that can do exactly what you want.

**Comment by darkworks** [comment]
ok thanks , i will look into notepad++ source code and plugins dev to see how to start then will try to make one

**Comment by alankilborn** [comment]
Functionality seems to be handled already by using a plugin.
Recommend CLOSURE of this item.

**Comment by ArkadiuszMichalski** [comment]
This is a specific case that should be implemented with plugins.
