### ISSUE TITLE
Adjust Window and ▼ menu width

### ISSUE THREAD

**Issue by Yaron10** [notepad-plus-plus/notepad-plus-plus#11810]
**STR:**
Open a large-file-name file.
Open the Window menu or ▼.

![תמונה](https://user-images.githubusercontent.com/10229320/174319222-39d4055f-6406-4351-85c2-71f1e6d75bf4.png)

Close that file.
Open the Window menu or ▼.

**Result:**
![תמונה](https://user-images.githubusercontent.com/10229320/174319409-497906ca-f601-4656-bbc6-576d9ae05457.png)

**Expected:**
The menu width should be adjusted.

_Relevant to Recent Files as well._ 

***

Notepad++ v8.4.2   (64-bit)
Build time : Jun 14 2022 - 21:11:12
Path : C:\---\Notepad++ Original.exe
Command Line : 
Admin mode : ON
Local Conf mode : ON
Cloud Config : OFF
OS Name : Windows 10 Pro (64-bit) 
OS Version : 20H2
OS Build : 19042.985
Current ANSI codepage : 1255
Plugins : 
    ComparePlus (1)
    HTMLTag (1.3.2)
    MenuIcons (1.2.5)
    PythonScript (2)
    _CustomizeToolbar (4.2)

**Comment by ozone10** [comment]
@Yaron10 
This seems to be Windows issue, sometimes it will use previous width, sometimes it will update to new width. I am not sure if there is some API for updating width size.

**Comment by Yaron10** [comment]
@ozone10,

Thank you for looking into it.
If a pro like yourself thinks it's a Windows issue, I certainly respect it.
