### ISSUE TITLE
Portable version has no Plugin Admin in Plugins menu

### ISSUE THREAD

**Issue by Mosney** [notepad-plus-plus/notepad-plus-plus#11828]
### Description of the Issue

Has no "Plugin Admin" in Menu-Plugins

Install via [scoop](https://github.com/ScoopInstaller/Scoop), reported this issue to them and they think this is Npp's issue. See https://github.com/ScoopInstaller/Extras/issues/8748

### Debug Information
Notepad++ v8.4.2   (64-bit)
Build time : May 29 2022 - 16:47:30
Path : D:\scoop\apps\notepadplusplus\current\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : ON
Cloud Config : OFF
OS Name : Windows 11 (64-bit) 
OS Version : 21H2
OS Build : 22000.739
Current ANSI codepage : 936
Plugins : 
    mimeTools (2.5)
    NPPJSONViewer (1.34)

**Comment by alankilborn** [comment]
>Install via scoop

Don't know what this means, exactly, but no one is going to problem-solve anything related to that for you.  Using other installers is not supported by Notepad++.
