### ISSUE TITLE
Powershell missing several styles

### ISSUE THREAD

**Issue by dail8859** [notepad-plus-plus/notepad-plus-plus#1183]
Obligatory ticket for incoming pull request...

The Powershell lexer is missing styles for [multi-line comments](http://ss64.com/ps/syntax-comments.html), [comment based keywords](https://technet.microsoft.com/en-us/library/dd819489.aspx), and [here-strings](https://technet.microsoft.com/en-us/library/ee692792.aspx).

![before](https://cloud.githubusercontent.com/assets/3694843/11387735/b577081e-92fb-11e5-8e75-2c8e422ffb56.png)

**Comment by xylographe** [comment]
Ty! Much better with #1184.
