### ISSUE TITLE
[ESC] search/delete

### ISSUE THREAD

**Issue by jimlynnjulian** [notepad-plus-plus/notepad-plus-plus#11837]
I run a python program that occasionally outputs warnings from a python app in a Windows WSL shell.
The warnings can be redirected to a text file, along with the program output.

Upon opening such a file in n++, I discovered escape characters in the text. These are the ones "[ESC]" in white letters on a black background. The text can be copied and pasted and the characters remain intact. However, they cannot be found in a search, or deleted.

I suggest including common characters, such as [ESC], [BEL], in search and delete. Or filtering them out / replacing them with standard text, possibly, as options.

Thanks for the program.

**Comment by alankilborn** [comment]
They should be able to be found with a search; how exactly are you searching for them?

Filtering these characters out is a user level task, not something for the program to do

**Comment by jimlynnjulian** [comment]
I copied and pasted the character into the 'Find' text box.
What appeared was a 'square.'
When I hit the search button, nothing was returned.
As for the second part, responsibility is what you make it. Take as much, or as little as you wish.

**Comment by alankilborn** [comment]
>I copied and pasted the character into the 'Find' text box.
What appeared was a 'square.'

Can you provide a small file with some of this output?

**Comment by jimlynnjulian** [comment]
Thank you for your response. The error mentioned was mine. I rarely use regex and left that setting on. The character was findable and deletable, once that setting was cleared.
Thank you for your time.

**Comment by alankilborn** [comment]
You may want to leave your files intact and process them with something like [THIS](https://github.com/Ekopalypse/NppPythonScripts/tree/master/npp) -- the error lister -- in order to see them in color and with the "ESC" stuff not showing.

**Comment by alankilborn** [comment]
>The error mentioned was mine.

Recommend CLOSURE of this item on that basis.
