### ISSUE TITLE
Enhancement: Toggle to maintain window placement for Ctrl+F / Ctrl+H

### ISSUE THREAD

**Issue by andrewc2** [notepad-plus-plus/notepad-plus-plus#11838]
### Description of the Issue
Toggle to maintain window placement for Ctrl+F / Ctrl+H when the window is already open. Currently this keyboard shortcut will reset the window location to center of screen if the window was already open but moved to the side.

### Steps to Reproduce the Issue

1. Open Find/Replace window (Ctrl+F / Ctrl+H)
2. Move said window
3. Select code window
4. Activate Ctrl+F again window will snap to center

### Expected Behavior
Expect the window to remain where I last placed it out of the way for the code I'm working with before needing to search for another item that will need updating in the same file.

### Actual Behavior
Window snaps back to the center each time the keyboard shortcut is activated.

### Debug Information

Notepad++ v8.4.2   (64-bit)
Build time : May 29 2022 - 16:47:30
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 10 Pro (64-bit) 
OS Version : 21H2
OS Build : 19044.1766
Current ANSI codepage : 1252
Plugins : 
    DSpellCheck (1.4.24)
    mimeTools (2.8)
    NppConverter (4.4)
    NppExport (0.4)

Similar to #905

**Comment by alankilborn** [comment]
This issue has its origins [HERE](https://github.com/notepad-plus-plus/notepad-plus-plus/issues/905#issuecomment-1165860229).

OP is asking for a "preference" setting to be created, enabling or disabling the "second press re-centering".

I don't think the STR here are accurate.
After step 3, the input focus is back in an editing tab ("code view" as OP calls it).
Proper behavior at this point when Ctrl+f is pressed is to switch input focus back to the Find window, not to re-center it; re-center would only happen if the Find window has input focus when Ctrl+f is pressed.  This IS current behavior of the referenced N++ version.

**Comment by andrewc2** [comment]
> I don't think the STR here are accurate.

This is exactly how it functions for me, after returning to the editor, with the Ctrl+F window already open but not in focus hitting Ctrl+F at this point recenters the window for me.

**Comment by alankilborn** [comment]
>after returning to the editor, with the Ctrl+F window already open but not in focus hitting Ctrl+F at this point recenters the window

Interesting.  Does anyone else see this behavior?  @Yaron10 ?

**Comment by Yaron10** [comment]
@alankilborn,

> Does anyone else see this behavior?

No. I get "your behavior".
It is Interesting.

**Comment by andrewc2** [comment]
Aha! I knew it didn't used to do that on my work computer, thus why I posed the question in #905 to know the intended operation. This doesn't happen on my home computer either, it functions as @alankilborn describes it should where the first press out of focus doesn't recenter.

**Comment by alankilborn** [comment]
>now is exhibiting normal expected behavior.

Ok, so that part is solved (I guess).  Let's see if the aberrant behavior returns...

If that behavior doesn't return, do you still think a "preference" setting is needed?  (If not, and the bad behavior doesn't return, probably you ( @andrewc2  ) can close this issue).

**Comment by andrewc2** [comment]
I agree the "preference" isn't needed, by default it's hard to trigger the re-center assuming normal operation. If this recurs I'll open a bug issue. Thank you for the assistance.
