### ISSUE TITLE
Multi-line search changes search-mode and find-what

### ISSUE THREAD

**Issue by alankilborn** [notepad-plus-plus/notepad-plus-plus#11847]
### Description of the Issue

Running a (normal mode) search where the _Find what_ data contains line-ending(s) unexpectedly changes the _Search mode_ to _Extended_ and inserts textual `\r` and/or `\n` into user's data.

### Steps to Reproduce the Issue

1. Select some data that includes a line-ending (i.e., make a selection that touches two or more lines), example:
![image](https://user-images.githubusercontent.com/77065706/175944534-5eb315a3-5b59-4099-a8d0-13c94e465cbc.png)

source data:
```
456
abc
123
def
```
2. Press Ctrl+f to see:
![image](https://user-images.githubusercontent.com/77065706/175945048-0c5c2521-2b76-46f4-9041-4ec907e6abdb.png)

3. Observe in the _Find_ window that _Search mode_ is _Normal_ (if not, set it to _Normal_).
4. Observe that _Find what_ does not show `\r` or `\n`.
5. Run a _Find All in Current Document_ search.

### Expected Behavior
I expect my _Search mode_ and my _Find what_ data to remain unchanged after such a search.

### Actual Behavior

Observe that _Search mode_ has been set to _Extended_ by Notepad++ and that _Find what_ data has been changed to contain `\r` and/or `\n`:
![image](https://user-images.githubusercontent.com/77065706/175945434-721bd5ce-670a-4123-bda0-dda70dd187e7.png)

I don't really like this behavior as it changes settings and data on me.

### More Steps

Repeat all steps except pressing the _Find All in Current Document_ button (step 5).  

New step 5: Tick the _Wrap around_ checkbox.  
New step 6: Press the _Find Next_ button.
New step 7: Observe that _Search mode_ is NOT automatically changed, and _Find what_ data does not get altered to insert `\r` or `\n`.  

At the very least, this behavior seems INCONSISTENT with the _Find All in Current Document_ behavior -- but the _Find Next_ behavior seems more correct.

### Debug Information
Notepad++ v8.4.2   (64-bit)
Build time : May 29 2022 - 16:47:30
Path : C:\\....\\npp.8.4.2.portable.x64\notepad++.exe
Command Line : $COMMAND_LINE_PLACEHOLDER$
Admin mode : OFF
Local Conf mode : ON
Cloud Config : OFF
OS Name : Windows 10 Enterprise (64-bit) 
OS Version : 20H2
OS Build : 19042.1708
Current ANSI codepage : 1252
Plugins : 
    mimeTools (2.8)
    NppConverter (4.4)
    NppExport (0.4)
    PythonScript (2)

### Other

* This issue originated from a request by @donho here: https://github.com/notepad-plus-plus/notepad-plus-plus/pull/11808#issuecomment-1166347899 to create a new issue out of that offshoot discussion.

* If current behavior is to remain, it surely should be documented in the user manual?

**Comment by alankilborn** [comment]
@Yaron10 had a comment here: https://github.com/notepad-plus-plus/notepad-plus-plus/pull/11808#issuecomment-1166330226 that I'll try to address now...

![image](https://user-images.githubusercontent.com/77065706/175947129-a2096bfb-42a0-4b93-a8e6-61bf74fb9a0c.png)

>If you select the first line including its EOL, open the Find dialog and search - the result would correctly be 1

I might argue that it would be 2, but that would depend on line 2 having an ending on it. :-)

>If you then manually select the Normal RadioButton, the result would be 0.

Well yes, I guess so, currently...but that's the whole argument of this issue; at that point N++ has _changed_ by search data on me.  If it had left it alone, a second search would result in non-zero hits.

>How would you implement that?

I wouldn't.  I'd just leave everything alone. :-)

But.. I feel like I'm misunderstanding your comments here.

**Comment by Yaron10** [comment]
@alankilborn,

> I might argue that it would be 2, but that would depend on line 2 having an ending on it.

I emphasized the the 2 in "If your file contains the following **2** lines." so that it would be understood that second line did not have an EOL (otherwise, the file would contain **3** lines).
I should have mentioned it explicitly.

> New step 6: Press the Find Next button.
New step 7: Observe that Search mode is NOT automatically changed, and Find what data does not get altered to insert \r or \n.
...
At the very least, this behavior seems INCONSISTENT with the Find All in Current Document behavior

👍
That's a very good point.

I did not have the `Find Next` behavior in mind when I replied in that PR.

> but the Find Next behavior seems more correct.

Is it?

There's a difference between searching for `Test`, `TestEOL` (i.e. selecting `Test` + EOL) and `Test\r\n` (i.e. literal `Test\r\n`).
When the user sees `Test` in `Find what`, how should they know if it includes the EOL or not? 
Don't you think there should be some indication?

If you agree, NPP should actually add the `\r\n` on activating the Find dialog and _before executing the search_.
And on `Find Next` there's even a better reason to add the `\r\n`: the user does not see it in the Search Results' header.

Those are some thoughts after a busy day. :)
Can you think of a better way to handle the various `Test` cases?

**Comment by alankilborn** [comment]
Responding to the many Yaron10 comments... :-)

So a lot of Yaron10's comments, and a lot of my original comments were based on N++ not doing something obvious in the _Find what_ box (or _Replace with_ for that matter) for these many years when end-of-line is included in the data.  I've just accepted that behavior, because change is difficult. :-)

But, mainly responding now to Yaron10's comment of:

>When the user sees Test in Find what, how should they know if it includes the EOL or not?
Don't you think there should be some indication?

If "we" are considering non-trivial changes to this functionality, perhaps there should be some sort of "multi-line data is present in this box" indicator, and then pressing that indicator opens a multi-line edit box.  Something like what is shown [HERE](https://community.notepad-plus-plus.org/assets/uploads/files/1655474527613-resize.png) perhaps?.  That image comes from [THIS](https://community.notepad-plus-plus.org/post/77628) posting on the Community.

>NPP should actually add the \r\n on activating the Find dialog and before executing the search.

I really don't like \r\n, as 4 characters of text, in a _Normal_ mode search, if that's what is being proposed.

**Comment by alankilborn** [comment]
Apparently EditPlus (which I do not have) also has some multiline Find/Replace editing areas; I found that out from [THIS](https://community.notepad-plus-plus.org/post/24068) Community post where there are some screenshots.  I'm not sure on this UI what invokes the multiline boxes at the bottom to be used instead of the single line edit controls at the top (which appear disabled -- while the multiline boxes are open??).

**Comment by alankilborn** [comment]
I found a 5-year-old similar complaint as this issue,  [HERE](https://community.notepad-plus-plus.org/post/25529) by @sasumner and @guy038.  Neither one of them ever made a real issue out of it; I wonder why.  The Community posting reads like they didn't feel strongly about it. :-(

**Comment by Yaron10** [comment]
@alankilborn,

We seem to agree that some indication is needed _before executing the search_.
I've also thought about a multi-line edit box. I'm wondering how complex it should be.

If you have the following 2 lines:
```
Test
Test\r\n
```
If you search for `Test\r\n` in normal-mode, line 2 is the match.
If you search in extended-mode, line 1 is the match.

So, wouldn't it be *wrong* not to auto select the extended-mode (in case you select multi-lines in the editor and Ctrl+F)?
It IS an extended-mode. Again, you'd get completely different results with normal-mode.

I do think the search-mode should be restored when the search-term changes and does not include any EOLs.

It's not that simple.

We can discuss it for days. :)
Let's wait for Don to join us.

**Comment by Yaron10** [comment]
Continuing from this point depends on multi-line edit box being even considered. :)

My Notepad adds some characters.
![תמונה](https://user-images.githubusercontent.com/10229320/176275043-69a7b222-295c-491e-a80b-c808cc9d0713.png)

**Comment by donho** [comment]
> At the very least, this behavior seems INCONSISTENT with the Find All in Current Document behavior

I agree.

It seems that it was done for fixing a crash problem in find in files 13 years ago: 
https://github.com/notepad-plus-plus/notepad-plus-plus/commit/e94b452d2aabcecd6ec0d119b08a27cbbb854b82

I may try to remove the line `combo2ExtendedMode(IDFINDWHAT);` to see if the crash still happen.
But it doesn't mean that the current behaviour will be changed (even there's no crash). 
It's a inconsistent behaviour, but it's a very minor one and users don't even care.
As a result, it doesn't worth to take risk of regression for a very little gain.

**Comment by alankilborn** [comment]
OK, thank you Don for the consideration, at least.

Peeve:  Why does it say "closed this as completed X days ago"?  This leads one to believe that something was done (and not just thought about) for this issue.  Is that the only thing it CAN say when something is closed?  Or are there other choices and perhaps a better one could have been selected?
