### ISSUE TITLE
8.4.2 Crashes when double clicking a word in order to select it

### ISSUE THREAD

**Issue by jeejeestudio** [notepad-plus-plus/notepad-plus-plus#11844]
### Description of the Issue
8.4.2 Crashes when double clicking a word i order to select it

### Steps to Reproduce the Issue

1.  open a random php file
2. double click any word
3. crash

### Expected Behavior
the word hilited, to be able to copy/paste it

### Actual Behavior
crashed

### Debug Information
Notepad++ v8.4.2   (64-bit)
Build time : May 29 2022 - 16:47:30
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : $COMMAND_LINE_PLACEHOLDER$
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 10 Pro (64-bit) 
OS Version : 21H2
OS Build : 19044.1766
Current ANSI codepage : 1252
Plugins : 
    ComparePlugin (2.0.2)
    jN (2.2.185.5)
    JSMinNPP (1.1905.1)
    mimeTools (2.8)
    NppConverter (4.4)
    NppExport (0.4)
    NPPJSONViewer (1.34)
    PreviewHTML (1.3.2)
    XBrackets (1.3)

**Comment by alankilborn** [comment]
See [HERE](https://community.notepad-plus-plus.org/topic/23146/faq-desk-notepad-crashes-freezes-unresponsive-after-update/1).

**Comment by donho** [comment]
@jeejeestudio 
It seems to me the plugin issue.
Could you remove them one by one to find the culprit one?
Thank you.

**Comment by jeejeestudio** [comment]
Thanks @alankilborn and @donho.
Without plugins indeed no issue.
It seems that I did not see a few plugins needed updating(some seem to be updating when a new notepad++ version is installed)
After updating jN Notepad++ plugin to 2.2.185.6, the issue seems solved.

**Comment by donho** [comment]
@jeejeestudio 
Could you still please help us to identify the culprit plugin?
It is important for the future stability of Notepad++ (to exclude the incompatible versions of plugin).

**Comment by rdipardo** [comment]
It is undoubtedly jN. Another user could reproduce this crash when jN was the only 3rd-party plugin installed: https://community.notepad-plus-plus.org/topic/23100/notepad-8-4-2-64-bit-suddenly-closes-for-no-reason

A patched version has been released: https://github.com/sieukrem/jn-npp-plugin/releases/tag/2.2.185.7

**Comment by ArkadiuszMichalski** [comment]
@rdipardo You can udpate [your list](https://github.com/notepad-plus-plus/notepad-plus-plus/issues/11198) for this plugin.

**Comment by jeejeestudio** [comment]
@donho of course,I can always help. 
as @rdipardo mentioned I also believe it was the jN. As without any plugins it ran ok. Then only updated jN and the others active before updating the others, the issue was gone.

**Comment by donho** [comment]
@jeejeestudio 
> Then only updated jN to 2.2.185.6 and the others active before updating the others, the issue was gone.

Do you mean only updated jN to **2.2.185.7** ?

**Comment by jeejeestudio** [comment]
@donho No I really meant only updating jN to 2.2.185.6, because I updated it yesterday and that one was available within the update possibility in Notepad++. I double checked the version.
After that it was OK.
Just today I updated manually to 2.2.185.7 by copying the files. As this one was not available via the plugin update utility.

**Comment by donho** [comment]
@jeejeestudio 
Thank you for your confirmation!

**Comment by jeejeestudio** [comment]
@donho Your Welcome!
