### ISSUE TITLE
Bookmarks Dook does not write text.

### ISSUE THREAD

**Issue by DogancanYr** [notepad-plus-plus/notepad-plus-plus#11843]
Description of the Issue:

Bookmarks Dock does not write text.

Steps to Reproduce the Issue:

Shown in the video

https://user-images.githubusercontent.com/90002969/175789600-05794086-89d4-4144-a5e3-8bc078f6a98f.mp4

 Expected Behavior:

Save the text

Actual Behavior:

I couldn't save the text

Debug Information:

Notepad++ v8.4.2   (64-bit)
Build time : May 29 2022 - 16:47:30
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : $COMMAND_LINE_PLACEHOLDER$
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 10 Home (64-bit) 
OS Version : 21H2
OS Build : 19044.1806
Current ANSI codepage : 1254
Plugins : 
    AutoCodepage (1.2.4)
    AutoSave (1.6.1)
    BetterMultiSelection (1.5)
    BigFiles (0.1.3)
    BookmarksDook (2.3.3)
    BracketsCheck (1.2.2)
    CodeAlignmentNpp (14.1.107)
    ComparePlugin (2.0.2)
    CustomLineNumbers (1.1.7)
    DSpellCheck (1.4.24)
    ExtSettings (1.2.1)
    HexEditor (0.9.12)
    JsMapParser.NppPlugin (4.2)
    JSMinNPP (1.2205)
    LanguageHelp (1.7.5)
    LocationNavigate (0.4.8.1)
    MarkdownViewerPlusPlus (0.8.2)
    MenuIcons (1.2.5)
    Merge files in one (1.2)
    mimeTools (2.8)
    NavigateTo (1.12.7)
    NewFileBrowser (0.1.5)
    NppConverter (4.4)
    NppEditorConfig (0.4)
    NppExport (0.4)
    NppGTags (4.5)
    NppJavaPlugin (0.4)
    NPPJSONViewer (1.40)
    NppMarkdownPanel (0.6.1)
    NppMenuSearch (0.9.6)
    nppplugin_solutionhub (3.0.1)
    nppplugin_solutionhub_ui (3.0.1)
    nppplugin_solutiontools (3.0.1)
    NppRegExTractorPlugin (2.1)
    NppSaveAsAdmin (1.0.211)
    NppTextViz (0.4.2)
    NppToolBucket (1.10.6622.41516)
    OpenSelection (1.1.3)
    QuickText (0.2.4.1)
    Remove Duplicate Lines (1.3)
    RestApiToText (1.3.1)
    RunMe (1.4.1)
    selectNLaunch (2.1)
    SelectQuotedText (1)
    zoomdisabler_x64 (1.2)
    _CustomizeToolbar (5.3)

**Comment by alankilborn** [comment]
This site does not support BookmarksDook plugin, which seems to be what your complaint is about?
Please find the site that supports it, and write there.
Please close this issue.

**Comment by donho** [comment]
@DogancanYr 
It seem BookmarksDook plugin doesn't let user modifier the text in Notepad++.
But it's not Notepad++ issue anyway. Please find BookmarksDook forum or issue tracker to report it.
