### ISSUE TITLE
i found that notepad++ doesn't pop up to the forefront

### ISSUE THREAD

**Issue by j717273419** [notepad-plus-plus/notepad-plus-plus#11841]
I also use notepad++ everyday, and I found a bug. i right click txt and open it with notepad++, or double click txt. i found that notepad++ doesn't pop up to the forefront. I need to click notepad++ again to get it to work. My environment is win11

**Comment by j717273419** [comment]
you can do this to reappear this bug.

envrionment: win 11 + noteapd ++ latest version

1. open notepad++, then click minimal button
2.open explorer, double a txt file or right click a txt file then choose edit in notepad++.

step 2 will not take notepad++ in the top of the window.

**Comment by alankilborn** [comment]
@j717273419 Fill in the issue template to be taken seriously.

**Comment by j717273419** [comment]
> @j717273419 Fill in the issue template to be taken seriously.

ok, I found this issue was fixed in v8.4.2
