### ISSUE TITLE
Themes: Default setting of EOL is hard to distinguish from background or normal text

### ISSUE THREAD

**Issue by MarkusBodensee** [notepad-plus-plus/notepad-plus-plus#11840]
### Description of the Issue
Use new feature to modify EOL appearance and apply custom color. Try it with different themes in default settings. The EOL marks are either hard to distinguish from background or hard to distinguish from normal text.

### Steps to Reproduce the Issue
1. Go to Settings --> Preferences --> Editing --> EOL (CRLF)
2. Choice of Default or Plain Text is not important, look at both
3. Check the Custom Color checkbox
4. Type some text with spaces, tabs and line ends
```
UPPER CASE TEXT
  		  
	CRLFCRLF

```

### Expected Behavior
A good look and feel with default settings.

### Actual Behavior
The EOL marks are either hard to distinguish from background or hard to distinguish from normal text with default settings. See Screenshot.

### Debug Information
I used the portable v8.4.2, copied artifact from master branch of Jun 18 2022 - 16:26:48, and copied the themes from master branch

Notepad++ v8.4.2   (64-bit)
Build time : Jun 18 2022 - 16:26:48
Path : C:\npp.8.4.2.portable.x64\Notepad++.x64.Release.exe
Command Line :
Admin mode : OFF
Local Conf mode : ON
Cloud Config : OFF
OS Name : Windows 7 Professional (64-bit) 
OS Build : 7601.24546
Current ANSI codepage : 1252
Plugins : 
    mimeTools (2.8)
    NppConverter (4.4)
    NppExport (0.4)

![grafik](https://user-images.githubusercontent.com/82021174/175767068-bd7dd9f9-6fea-4af4-ac22-d7645c2b2fac.png)

**Comment by MarkusBodensee** [comment]
Here is an approach which uses same color for EOL like for whitespaces. What do others think on this approach?

![grafik](https://user-images.githubusercontent.com/82021174/175767142-5195a590-007c-406d-a305-b4a2e8c9817e.png)

**Comment by MarkusBodensee** [comment]
The themes in the screenshots are, alphabetically:
- Bespin, Black board, Choco
- DansLeRuSH-Dark, DarkModeDefault, Deep Black
- Hello Kitty, HotFudgeSundae, khaki
- Mono Industrial, Monokai, MossyLawn
- Navajo, Obsidian, Plastic Code Wrap
- Ruby Blue, Solarized, Solarized-light
- Twilight, Vibrant Ink, vim Dark Blue
- Zenburn, Default (stylers.xml)

**Comment by alankilborn** [comment]
> same color for EOL like for whitespaces. What do others think on this approach?

I think this is the obvious and best choice for this!

**Comment by donho** [comment]
The default custom CRLF colour is discreet - that's the whole point of custom CRLF.

**Comment by MarkusBodensee** [comment]
@donho
Thank you for the explanation. Yes, indeed, grey colour is more discreet, that's a valid point to which I did not pay much attention before.

I almost feared that the request would be rejected. Nevertheless, I wanted to try it and bring it up again, at least in the hope some other users contribute with their opinions.

**Comment by MarkusBodensee** [comment]
@donho
Please allow me to bring my arguments once more, after that I think I let the topic rest, maybe for others to join. Or am I the only one with these points (apart from Alan)? (Which also would be fine, because then nobody else complains.)

- That whitespace-symbols are currently not discreet in some themes is intentional. I think, this is also what a normal user assumes for EOL by choosing the theme. Otherwise the user would select a different theme with more discreet symbols. In other IDEs all symbols (whitespace and eol) appear always in the same colour per default (at least the ones I know), so I think this is definitely valid assumption what a user expects by activating the show all symbols option.

- With the same colour for whitespace and EOL, it is visually more clear that everything in that colour are symbols. Especially it is visually more clear that the CRLF at the end of the line are symbols and not letters.

- That 808080-grey is more discreet for EOL in all themes is not true. For example in the popular Obsidian theme, DansLeRuSH-Dark, DarkModeDefault, Zenburn or in vim Dark Blue, 808080-grey is more conspicuous than the whitespace colour. (And especially look at Hello Kitty, in which I did the change the other way round.) In Solarized theme, normal text is grey, no distinction possible to EOL-symbols. So I think there is no "one colour fits all"-solution. That's why themes look different at all.

By the way, the PR was also made as room for more discussion on the colours while having a code base with hex-values. (HotFudgeSundae and MossyLawn seems not good with my values. And in vim Dark Blue, now I think the more discreet values would be better...)

Thank you for your attention.

**Comment by donho** [comment]
@MarkusBodensee 
I saw your point and we have talked already about it.
I'll explain once and for the last time: this feature has added for making the EOL less visible.
Except EOL colour is set perfectly matched with the theme, the default custom colour will be remained. 
You (and other users) can always set to the color you (they) want in any theme - that's the purpose of customization.

**Comment by MarkusBodensee** [comment]
@donho
I see that my arguments weren't strong enough to convince you. That's ok, and as stated above I will not bother you further with this topic.

Anyway, a big thank you for making this feature of EOL colouring available! It will affect my daily use of Notepad++ and I will enjoy it with the customisation. I was excited while seeing your PR for it incoming and really appreciate your work.
