### ISSUE TITLE
Settings->Preferences->Misc->Clickable Link Settings, Enable work always

### ISSUE THREAD

**Issue by mishin** [notepad-plus-plus/notepad-plus-plus#1185]
if you check or not it works always

**Comment by dail8859** [comment]
Seems to work fine for me. Try following [these](https://github.com/notepad-plus-plus/notepad-plus-plus/blob/master/CONTRIBUTING.md#reporting-issues) steps.

**Comment by mishin** [comment]
thanks. may be others plugin make this effects, well close

**Comment by donho** [comment]
@mishin May we know which plugin makes this issue?
