### ISSUE TITLE
Problem with Katakana in macro

### ISSUE THREAD

**Issue by qx87** [notepad-plus-plus/notepad-plus-plus#11851]
Macro in `shortcuts.xml` to type ¯\_(ツ)_/¯ sequence:

        <Macro name="Insert &#x00AF;\_(&#x30C4;)_/&#x00AF;" Ctrl="yes" Alt="no" Shift="no" Key="0">
            <Action type="1" message="2001" wParam="2" lParam="0" sParam="&#x00AF;" />
            <Action type="1" message="2170" wParam="0" lParam="0" sParam="\" />
            <Action type="1" message="2170" wParam="0" lParam="0" sParam="_" />
            <Action type="1" message="2170" wParam="0" lParam="0" sParam="(" />
            <Action type="1" message="2001" wParam="2" lParam="0" sParam="&#x30C4;" />
            <Action type="1" message="2170" wParam="0" lParam="0" sParam=")" />
            <Action type="1" message="2170" wParam="0" lParam="0" sParam="_" />
            <Action type="1" message="2170" wParam="0" lParam="0" sParam="/" />
            <Action type="1" message="2001" wParam="2" lParam="0" sParam="&#x00AF;" />
        </Macro>

Every character except "the one" ツ works fine. Unicode number of the char is U+30C4, UTF-8 code: E3 83 84. But NPP types only two bytes: E3 83.

**Comment by rdipardo** [comment]
Like you said, the Kana character is 3 bytes long, so the `wParam` attribute should be that number:

~~~xml
<Action type="1" message="2001" wParam="3" lParam="0" sParam="&#x30C4;" />
~~~

**Comment by qx87** [comment]
Thanks a lot, it works!
