### ISSUE TITLE
Bug report: URL in single quotes retains trailing single quote when following link

### ISSUE THREAD

**Issue by jonnyt1978** [notepad-plus-plus/notepad-plus-plus#11854]
### Description of the Issue
When clicking on a URL link in a script file in Notepad++ which is enclosed in single quotes (the ' character, to the right of the semi-colon key on a UK/US keyboard), the URL in the browser window that is opened has the URL with the trailing ' character still appended.

For example, in a PowerShell script, you might have the following variable defined:

$Web_Home_URL = 'https://ftp.mozilla.org/pub/firefox/releases/'

The URL is recognised by NP++ and highlighted as such (underlined). Double-clicking the URL opens it in the default browser, but the URL comes up as:

https://ftp.mozilla.org/pub/firefox/releases/'

which gives a 404 error. Removing the trailing single quote loads the page ok.

This does not occur for double quotes, e.g. 

$Web_Home_URL = "https://ftp.mozilla.org/pub/firefox/releases/"

but in scripting languages such as PowerShell, single and double quotes are handled differently

### Steps to Reproduce the Issue
1. Create a new blank document in NP++
2. Add a valid URL, enclosed in single quotes
3. Double-click on this URL to open it in your default browser

### Expected Behavior
The URL should open in your default browser

### Actual Behavior
The browser throws a 404 error, due to the trailing single quote character

### Debug Information
Notepad++ v8.4.2   (64-bit)
Build time : May 29 2022 - 16:47:30
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : $COMMAND_LINE_PLACEHOLDER$
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 10 Pro (64-bit) 
OS Version : 21H2
OS Build : 19044.1766
Current ANSI codepage : 1252
Plugins : 
    mimeTools (2.8)
    NppConverter (4.4)
    NppExport (0.4)

**Comment by ArkadiuszMichalski** [comment]
Anyone can reproduce this?

**Comment by xomx** [comment]
@ArkadiuszMichalski 
A duplicate issue, already fixed by the #15058 in v8.6.6.

**Comment by donho** [comment]
https://github.com/notepad-plus-plus/notepad-plus-plus/commit/c584a77e0e3d5588d1c900a3e78b96d959737129
