### ISSUE TITLE
political stand ? what f dev!

### ISSUE THREAD

**Issue by GongLe** [notepad-plus-plus/notepad-plus-plus#11853]
他妈的个sb项目，不好好写代码搞政治，这哥们有强盗基因 ！

**Comment by GongLe** [comment]
![QQ图片20220629150940](https://user-images.githubusercontent.com/1720495/176374100-66e6b0bd-60ba-4c31-9302-9f7ce5922399.jpg)

**Comment by Korb** [comment]
This is a duplicate of #6288 (disrespect for other members of the FOSS community by posting political propaganda spam in text editor resources).
