### ISSUE TITLE
[Feature Request] Save a Copy As and then OPEN THE COPY

### ISSUE THREAD

**Issue by alankilborn** [notepad-plus-plus/notepad-plus-plus#11861]
Often I need to copy a file that I have open in Notepad++ and then edit that file immediately, while keeping the original file open as well (for reference or independent change).

This becomes an operation of multiple steps because neither _Save As..._ or _Save a Copy As..._ will conclude with both the original and the copy open in Notepad++ tabs.

So I would like to see a way to achieve this in one step, e.g. a new command called _Save a Copy As and Open The Copy..._.

### Debug Information

Above comments based on behavior current to Notepad++ 8.4.2

### Workarounds

Currently I work-around the (minor) pain of the missing feature by:

* Using _Save As_ and then _File Open_ and then find my original file and reopen it
* Using _Save a Copy As_ and then _File Open_ and then find my new file and open it
* Getting an Exporer window in the parent folder of the original file, use drag-n-drop copy of the file, rename the file, and then drag-n-drop the renamed file into Notepad++

**Comment by pryrt** [comment]
"Save a Copy As and Open The Copy" is a very descriptive name, but way too unwieldy, IMO

I think using "Clone" as the verb would've been the most natural, but "Clone" already means something different in Notepad++, so shouldn't be used here. 

I think a name like "Replicate" or "Replicate To and Edit" or "Replicate To and Open" or "Duplicate To and Edit" or "Duplicate To and Open" would work for entries in the File menu -- though the short "Replicate" is probably _too_ terse for a new user of the feature. 

If you don't like those, "Save Copy As and Open" would be a way to condense the unwieldy name to something slightly more usable without changing the basic word choice.

**Comment by alankilborn** [comment]
So as @pryrt freshened this request by commenting on it, another point comes to mind:

If I use the existing _Save a Copy As_ command, and save my copy is some "far off" path, when control returns to Notepad++ I have no way to easily open that file for editing, aside from _File_ > _Open_ and slogging through potentially a lot of directories until I get to where I've put the copy.  This is painful when I just specified all of this path info to the SaveAs box.

**Comment by notdodgeball** [comment]
I also struggle with this. Instead of a fifth save option, it would be possible to add a 'Open after save' checkbox to the file dialog, this way we could use it with both "Save as" and "Save a copy as" 

CustomFileDialog.cpp can already add a custom checkbox it seems.

**Comment by alankilborn** [comment]
> add a 'Open after save' checkbox to the file dialog, this way we could use it with both "Save as" and "Save a copy as"

This is a reasonable idea, though I'm unclear as to why it would be needed upon executing a _Save As_.  Certainly I see the utility of it with _Save a Copy As_.

**Comment by alankilborn** [comment]
@pryrt and/or @notdodgeball :

If the copy is opened, should it also become the active file, or should the original file remain the active one?

**Comment by pryrt** [comment]
In any other command that I can think of that opens a file, or creates a new file, or clones a file into a new view or new instance, it always activates the one that is opened as a result of the action. 

Based on that consistency of experience so far, I would guess that a generic user would expect that the new copy would be the one to be active for this action as well.

But, even if I guessed wrong, keeping the interface consistent seems to be a good rule of thumb, in the absence of pre-existing feedback from other users.

**Comment by donho** [comment]
https://github.com/notepad-plus-plus/notepad-plus-plus/pull/14742#issuecomment-1962395930
