### ISSUE TITLE
Toggling DARK MODE on and off replaces icon menu bar icons

### ISSUE THREAD

**Issue by samolzenstrs** [notepad-plus-plus/notepad-plus-plus#11867]
### Description of the Issue
Toggling DARK MODE on and off replaces icon menu bar icons with small black and white versions.

### Steps to Reproduce the Issue
Toggle DARK MODE on and off.

### Expected Behavior
Turning DARK MODE on and off should not change anything.

### Actual Behavior
The menu bar icons changed.

### Debug Information

Notepad++ v8.4.2   (64-bit)
Build time : May 29 2022 - 16:47:30
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : $COMMAND_LINE_PLACEHOLDER$
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 10 Pro (64-bit) 
OS Version : 21H2
OS Build : 19044.1766
Current ANSI codepage : 1252
Plugins : 
    mimeTools (2.8)
    NppConverter (4.4)
    NppExport (0.4)

**Comment by alankilborn** [comment]
I think the idea is that the majority of dark mode users would prefer a dark toolbar, so the toolbar icons are changed with a switch to dark mode.  If this is not desired, switch the toolbar icons to another choice at _Settings_ > _Preferences_ > _General_ > _Toolbar_.

**Comment by alankilborn** [comment]
BTW, the dark-mode side effects to the toolbar icons are discussed in the [MANUAL](https://npp-user-manual.org/docs/preferences/#dark-mode) for Notepad++

**Comment by ArkadiuszMichalski** [comment]
Was asked and rejected https://github.com/notepad-plus-plus/notepad-plus-plus/issues/10212.
