### ISSUE TITLE
Please help us to test Notepad++ v8.4.3 Release Candidate

### ISSUE THREAD

**Issue by donho** [notepad-plus-plus/notepad-plus-plus#11868]
https://community.notepad-plus-plus.org/topic/23185/notepad-v8-4-3-release-candidate

**Comment by ArkadiuszMichalski** [comment]
I assume this can be closed now.

**Comment by ArkadiuszMichalski** [comment]
Was pinnet (not by me) so if @donho thinks that it is no longer necessary, let him remove it himself.
