### ISSUE TITLE
Notepad++ Unavailable on Android Ecosystem

### ISSUE THREAD

**Issue by zaheernathani** [notepad-plus-plus/notepad-plus-plus#11875]
### Description of the Issue
Notepad++ Unavailable on Android Ecosystem

### Steps to Reproduce the Issue

1.  Go to Google Playstore or F-Droid
2.  Search Notepad ++

### Expected Behavior
Notepad++ should be available on Andoid Mobile Ecosystem as well

### Actual Behavior
Notepad++ Unavailable on Android Ecosystem

### Debug Information
NA - New request

**Comment by alankilborn** [comment]
Close.

**Comment by dail8859** [comment]
https://github.com/notepad-plus-plus/notepad-plus-plus/wiki/FAQ#support-for-systems-other-than-the-ms-windows-family
