### ISSUE TITLE
How can I open a file and list by date in Linux notepad++?

### ISSUE THREAD

**Issue by yhm2046** [notepad-plus-plus/notepad-plus-plus#11879]
windows version is very pretty when I using it , but after I install notepad++ in ubuntu, I can't open  a file list by date.
I hope linux version can show like this :
[Imgur](https://i.imgur.com/R3HnxLG.jpg)

**Comment by alankilborn** [comment]
Linux is not directly supported by Notepad++; see [HERE](https://github.com/notepad-plus-plus/notepad-plus-plus/wiki/FAQ#support-for-systems-other-than-the-ms-windows-family).  Thus, Linux issues are not treated.

**Comment by xomx** [comment]
@yhm2046 
That is because of this file-opening dialog you see does not belong to the N++ but to the underlying OS itself. N++ just invokes this system dialog. So the problem is probably that the [WINE](https://www.winehq.org/)-layer shows different system resource than on a real Windows.

**Comment by alankilborn** [comment]
Recommend CLOSURE of this item.
