### ISSUE TITLE
Find All in current document freezes NPP++ for more than 2 minutes

### ISSUE THREAD

**Issue by Hexaae** [notepad-plus-plus/notepad-plus-plus#11878]
Find All is deadly slow

### Description of the Issue
_Find All in current document_ for large files takes too much (minutes, not seconds!)

### Steps to Reproduce the Issue
1. open for example this huge file [workshop.zip](https://github.com/notepad-plus-plus/notepad-plus-plus/files/9053080/workshop.zip)
2. 'Find All in current document' for ":" (443218 matches)
3. repeat the same search at point 2 multiple times

### Expected Behavior
Find and mark all occurrences in a few secs

### Actual Behavior
Can take more than 2:33 minutes on i7-8750h, 32GB RAM. Can also freeze forever sometimes randomly on repeat.
Same thing on other programs like 'CudaText' is almost instant, on 'NotepadNext' takes 2 secs, on 'Geany' takes less than 8 secs...

**Comment by alankilborn** [comment]
No _Debug Info_ supplied...really can't be analyzed.

**Comment by ArkadiuszMichalski** [comment]
No I mean current, read instruction.

**Comment by Hexaae** [comment]
```
Notepad++ v8.4.2   (64-bit)
Build time : Jul  6 2022 - 10:57:08
Path : C:\Users\Virtu\Desktop\Notepad++.x64.Debug.exe
Command Line : 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 10 Pro (64-bit) 
OS Version : 21H1
OS Build : 19043.1741
Current ANSI codepage : 1252
Plugins : none
```

Ok, sorry. Just tested https://ci.appveyor.com/project/donho/notepad-plus-plus
[Environment: compiler=MSC, platform=x64; Configuration: Debug]

and prolonged freeze is still reproducible...

**Comment by Hexaae** [comment]
Yep, not a bug but isn't top notch in speed compared to others (try also [NotepadNext](https://github.com/dail8859/NotepadNext) maybe you can share what seems to be a faster code?)

**Comment by ArkadiuszMichalski** [comment]
Maybe @dail8859 could write some suggestions how to improve this search.

**Comment by dail8859** [comment]
@ArkadiuszMichalski 

Search results are displayed differently in Notepad Next. Not sure if the performance issue is related to the actual searching, or populating the results since it uses another Scintilla instance with a custom lexer.

**Comment by informatorius** [comment]
Even when the current performance bottleneck gets fixed, would it make sense to do the searching multithreaded for big files?

**Comment by yyuyitian** [comment]
meet the same promble, we always use npp to analysis android logs, sometime when open 10+ files ,and find all in all opened files,sometimes the page will get stuck, at this time, i have to exit the npp process and reopen it. it really means alot to improve the perfomance of find all in all opened files.

**Comment by yyuyitian** [comment]
for me, npp 8.4.4 took 33s, my computer configuration is i3-10100 ;RAM: 16GB; 64bit; windows10
