### ISSUE TITLE
Ctrl + C does not work

### ISSUE THREAD

**Issue by griffin-warrior** [notepad-plus-plus/notepad-plus-plus#11877]
### Description of the Issue

`Ctrl + C` does not work when there is a `Ctrl + C + C` hotkey defined in other applications.
`Ctrl + C + C` means hold Ctrl and double press C.

### Steps to Reproduce the Issue

1. Download [GoldenDict](https://sourceforge.net/projects/goldendict/files/early%20access%20builds/).
2. Open GoldenDict and confirm that shortcuts in Preference > Hotkeys is set to `Ctrl + C + C`.
3. Leave GoldenDict launched and open notepad++ you will find `Ctrl + C` won't copy what you selected. 
4. Close GoldenDict or remove the hotkey `Ctrl + C + C`, then `Ctrl + C` will work properly again in notepad++.

### Expected Behavior

`Ctrl + C` should not be affected by `Ctrl + C + C` like other Windows applications.
 
### Actual Behavior

If `Ctrl + C + C` exists, `Ctrl + C` will not work in notepad++.

### Debug Information

Notepad++ v8.3.3   (64-bit)
Build time : Mar 13 2022 - 17:20:02
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : 
Admin mode : ON
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 10 Pro for Workstations (64-bit) 
OS Version : 2009
OS Build : 19043.1526
Current ANSI codepage : 936
Plugins : mimeTools.dll NppConverter.dll NppExport.dll 

This bug has been introduced since several previous versions ago. I haven't found it is caused by `Ctrl + C + C` until today.

**Comment by alankilborn** [comment]
>Ctrl + C + C means hold Ctrl and double press C.

To me this sounds like simply Ctrl+c pressed twice...

GoldenDict says it has "Support for global hotkeys".  Probably this is preventing Notepad++ from seeing the Ctrl+c.  (Hence, not a problem with Notepad++, and not something that could be "fixed").

Strong suggestion:  Remap your global hotkey in GoldenDict to something else.

**Comment by griffin-warrior** [comment]
As long as I found out the reason, it's very easy to get a workaround.
I know I can remap the hotkey with something else in GoldenDict. 
Yet, if it's not a problem with notepad++, why `Ctrl + C + C` does not affect other applications?
`Ctrl + C + C`  does not change the default behavior of normal copy operation.
I just point it out and for me it a problem which I hope could be fixed. 
But It up to developers to decide whether it is worthy to deal with it as a problem.🤷‍♂️

**Comment by alankilborn** [comment]
Recommend CLOSURE of this item.

**Comment by ArkadiuszMichalski** [comment]
@griffin-warrior 
>This bug has been introduced since several previous versions ago. I haven't found it is caused by Ctrl + C + C until today.

You could determine which version the shortcut worked correct (use the portable version).

**Comment by griffin-warrior** [comment]
Finally, I figured out that this is not notepad++'s fault. 
GoldenDict also affects other applications if the shortcut is set in the `Ctrl + A + B` form.
