### ISSUE TITLE
Please fix product version of installer.

### ISSUE THREAD

**Issue by ThomasKlengel** [notepad-plus-plus/notepad-plus-plus#11886]
### Description of the Issue
When you look at the Windows x64bit installers of at least 8.4 (didnt check the others), The file version is e.g. "8.4.2" but the product version is "8.42".

### Steps to Reproduce the Issue
Under Windows, right click an installer, go to details, have a look at file version and product version.

### Expected Behavior
Expected product version to be the same as the version that is to be installed.
(file version may be different, since the installer does not need to be the same version as the product that is installed by the installer)

### Actual Behavior
The version of the installed product is e.g. "8.4.2" but the product version of the installer is "8.42"

### Debug Information
Under Windows, right click an installer, go to details, have a look at file version and product version.

[stackoverflow](https://stackoverflow.com/questions/60113511/set-product-version-and-file-version-to-different-numbers-in-c-sharp)

> You can set the value displayed in the "Product Version" info using the AssemblyInformationalVersion attribute. Set this in your Assembly.cs file like this:
> 
> [assembly: AssemblyInformationalVersion("1.2.3.4")]
> From the [Microsoft documentation](https://docs.microsoft.com/en-us/dotnet/standard/assembly/set-attributes):
> 
> Note: If the AssemblyInformationalVersionAttribute attribute is not applied to an assembly, the version number specified by the 
> AssemblyVersionAttribute attribute is used by the Application.ProductVersion, Application.UserAppDataPath, and Application.UserAppDataRegistry properties.

**Comment by ArkadiuszMichalski** [comment]
Same as https://github.com/notepad-plus-plus/notepad-plus-plus/issues/11431.

**Comment by donho** [comment]
Notepad++ has its own version management.
It may not be the "conventional" one, but as far as it work, I don't see why it's a bug.
