### ISSUE TITLE
stop cultural discrimination

### ISSUE THREAD

**Issue by pasu** [notepad-plus-plus/notepad-plus-plus#11887]
In the middle of the red rectangle 1, the words "儒家文化" mean **confucius culture**, and around it, the word “屁” means ass. He was insulting confucius culture obviously.

Cultural discrimination in a product is an irrational behavior, it‘s weird why you did this. And don't confuse the difference between cultural discrimination and political views.

![image](https://user-images.githubusercontent.com/2180609/177986999-2dc13cbd-a708-434e-a88d-0c847d4a12c5.png)

https://notepad-plus-plus.org/news/v843-unhappy-users-edition/

By the way, is it allowed to express your personal political view via a GPL licensed product?

**Comment by Carighan** [comment]
Please explain? Isn't this just showing 3 new features?

**Comment by rimrul** [comment]
> Please explain? Isn't this just showing 3 new features?

According to google translate, the 12 outer characters of the chosen sample text all mean `ass` and the inner 4 something about `Confucius` and `culture`.

Might be related to #8820, #11805, #11763, #11853 and similar issues.

**Comment by pasu** [comment]
> Please explain? Isn't this just showing 3 new features?



> > Please explain? Isn't this just showing 3 new features?
> 
> According to google translate, the 12 outer characters of the chosen sample text all mean `ass` and the inner 4 something about `Confucius` and `culture`.
> 
> Might be related to #8820, #11805, #11763, #11853 and similar issues.

Culture is quite different with political view. Just image replacing **confucius culture** with other words such as ...

**Comment by alankilborn** [comment]
>Just imagine replacing `confucius culture` with other words such as ...

Isn't this akin to convicting someone in a court-of-law for what they _thought_ rather than their actions?
