### ISSUE TITLE
Deleting a file via the Notpad++ menu leads to a crash

### ISSUE THREAD

**Issue by rainman74** [notepad-plus-plus/notepad-plus-plus#11882]
### Description of the Issue
When trying to delete a loaded file using the Notpad++ menu, Notepad crashes.

### Steps to Reproduce the Issue
1. Recyle bin is disabled on your drive in Windows
2. Open a file
3. Select File -> Move to recyle bin
4. Click yes in request dialog "Delete file - The file xyz will bei moved to your recycle bin and dies document will be closed."
5. Notepad crashes

### Expected Behavior

File will be deleted and Notepad doesn't crash 👍 

### Actual Behavior

File won't be deleted but Notepad crashes 👎 

### Debug Information

Notepad++ v8.4.2   (32-bit)
Build time : May 29 2022 - 16:45:17
Path : D:\Apps\Notepad++\notepad++.exe
Command Line : $COMMAND_LINE_PLACEHOLDER$
Admin mode : ON
Local Conf mode : ON
Cloud Config : OFF
OS Name : Windows 10 Enterprise (64-bit) 
OS Version : 21H2
OS Build : 19044.1806
Current ANSI codepage : 1252
Plugins : 
    ComparePlugin (2.0.2)
    HexEditor (0.9.12)
    JSMinNPP (1.2205)
    mimeTools (2.8)
    nppAutoDetectIndent (2.3)
    NppConverter (4.4)
    NppExport (0.4)
    NppTextFX (0.2.6)
    XMLTools (3.1.1.13)

![2022-07-07_225350](https://user-images.githubusercontent.com/16306963/177870014-be37a007-f435-4ed2-ad2e-725c4392dc4c.png)

![2022-07-07_225136](https://user-images.githubusercontent.com/16306963/177870038-0140829b-e637-49b1-aa89-836198c2d910.png)

**Comment by xomx** [comment]
Cannot reproduce.
After the 1st "Delete file" dlg I have got the following 2nd dlg (instead of your exception):
![npp-delete-2nd](https://user-images.githubusercontent.com/13075183/178097191-3d589ad5-1611-4a38-8a37-a36229edbf23.png)
And then the file is gone as expected.
Tried N++ 8.4.2, 8.4.3, 8.3.3, both 32 & 64-bit, Win10Pro & Win8.1Ent.

**Comment by rainman74** [comment]
> Cannot reproduce. After the 1st "Delete file" dlg I have got the following 2nd dlg (instead of your exception): ![npp-delete-2nd](https://user-images.githubusercontent.com/13075183/178097191-3d589ad5-1611-4a38-8a37-a36229edbf23.png) And then the file is gone as expected. Tried N++ 8.4.2, 8.4.3, 8.3.3, both 32 & 64-bit, Win10Pro & Win8.1Ent.

Notepad++ v8.4.0/8.4.1/8.4.2/8.4.3 (32-bit) crashes as described, but 64-bit versions work fine and can delete!

I also tried with a new installation, standard configuratiuon and no plugins! Same effect :-(

**Comment by rainman74** [comment]
> Cannot reproduce. After the 1st "Delete file" dlg I have got the following 2nd dlg (instead of your exception): ![npp-delete-2nd](https://user-images.githubusercontent.com/13075183/178097191-3d589ad5-1611-4a38-8a37-a36229edbf23.png) And then the file is gone as expected. Tried N++ 8.4.2, 8.4.3, 8.3.3, both 32 & 64-bit, Win10Pro & Win8.1Ent.

I uninstalled Visual Studio 2022 (Community Edition) and now Notepad++ (x86) no longer crashes when deleting a file and deleting works. Strange!
