### ISSUE TITLE
"EOL custom color" does not appear to be working in v8.4.3

### ISSUE THREAD

**Issue by Gitoffthelawn** [notepad-plus-plus/notepad-plus-plus#11890]
### Description of the Issue
`EOL custom color` is a new feature in v8.4.3.  But it doesn't seem to work. :(

### Steps to Reproduce the Issue
1. Install v8.4.3
2. Ensure your style includes a custom colour for `EOL custom color`
3. Turn on the display of EOL markers
4. Notice no custom colour for EOL markers

### Expected Behavior
EOL markers to match the custom colour defined in the current style

### Actual Behavior
No custom colour for EOL markers

### Relevant Debug Information
Notepad++ v8.4.3   (32-bit)
Command Line : 
Admin mode : OFF
Local Conf mode : ON
Cloud Config : OFF
Plugins : 
    CustomizeToolbar (5.3)
    DSpellCheck (1.4.24)
    HexEditor (0.9.12)
    JSONViewer (1.40)
    NppQrCode32 (0.0.0.1)
    nppRegEx ()
    Remove Duplicate Lines (1.3)
    TopMost (1.4)

**Comment by ArkadiuszMichalski** [comment]
https://community.notepad-plus-plus.org/topic/23212/notepad-v8-4-3-unhappy-users-edition/2?_=1657299743200

> [CennoxX](https://community.notepad-plus-plus.org/user/cennoxx) [about 8 hours ago](https://community.notepad-plus-plus.org/post/78222)
[@donho](https://community.notepad-plus-plus.org/uid/3) I think it is unintuitive, that you have to go to the Editing section of the Preferences dialog and set a checkbox there, before making EOL (CRLF) display customizable. Before reading this description I saw the entry “EOL custom color” in the Style Configurator, changed it and wondered, why it didn’t had any effect.

**Comment by Gitoffthelawn** [comment]
@ArkadiuszMichalski Thank you.  That did it.  So it's a UX issue and not a programming bug.  Maybe Tom was right! 🤣 🤣 🤣

**Comment by ArkadiuszMichalski** [comment]
@donho
Maybe `Style configurator > EOL custom color` should have some point/info to `Preferences >  Editing > EOL`, same as `Preferences >  Editing > EOL` has point to `Style configurator > EOL custom color`

**Comment by CennoxX** [comment]
Why is this checkbox necessary at all? Yes, that would be the previous behavior, but I think at least the default behavior should be to follow the chosen style. Or is it this way due to technical reasons?

**Comment by ArkadiuszMichalski** [comment]
> @CennoxX  Why is this checkbox necessary at all?
Because you can set default presentation or plain text (both can additionally have their own color),

**Comment by Gitoffthelawn** [comment]
@donho Thank you for implementing this feature (being able to colour the EOL markers).  I wasn't sure exactly how helpful it would be, but in practice it is already very helpful.  Thanks!
