### ISSUE TITLE
Semitransparent boxes remain drawn in panels after mouse cursor is moved away from list items

### ISSUE THREAD

**Issue by misuser** [notepad-plus-plus/notepad-plus-plus#11898]
### Description of the Issue

If a dark theme is set in dark mode then semitransparent boxes are drawn when mouse cursor is placed over list items in Project panels, "Folder as workspace" panel and "Function list" panel and these semitransparent boxes won't disappear when mouse cursor is moved away.
### Steps to Reproduce the Issue

1. Switch to dark mode,
2. Set some dark theme,
3. Open Project panel or "Folder as workspace" or "Function list" panel and place mouse cursor over list items (without clicking).

semitransparent boxes are drawn when mouse cursor is placed over list items and don't disappear if cursor is moved away.
### Expected Behavior

When mouse cursor is moved away from list items in panels semitransparent boxes should disappear.
### Actual Behavior

semitransparent boxes remain drawn around each list item that was hovered by mouse.
### Debug Information

Notepad++ v8.4.3   (32-bit)
Build time : Jul  7 2022 - 10:53:37
Path : C:\Portable\NotepadPlusPlus\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : ON
Cloud Config : OFF
OS Name : Windows 8.1 Pro (32-bit) 
OS Build : 9600.20371
Current ANSI codepage : 1252
Plugins : 
    ComparePlus (1)
    mimeTools (2.8)
    NppConverter (4.4)
    NppExport (0.4)

![Untitled](https://user-images.githubusercontent.com/109034009/178155696-be2aed21-ea25-4b24-9908-1819e53f9432.png)

**Comment by donho** [comment]
@misuser 
Could you confirm that this issue has been solved by https://github.com/notepad-plus-plus/notepad-plus-plus/pull/11913 ?

**Comment by misuser** [comment]
> @misuser Could you confirm that this issue has been solved by #11913 ?

No, issue not solved in version 8.4.4

Notepad++ v8.4.4   (32-bit)
Build time : Jul 15 2022 - 17:56:38
Path : C:\Portable\NotepadPlusPlus\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : ON
Cloud Config : OFF
OS Name : Windows 8.1 Pro (32-bit) 
OS Build : 9600.20371
Current ANSI codepage : 1252
Plugins : 
    mimeTools (2.8)
    NppConverter (4.4)
    NppExport (0.4)

**Comment by donho** [comment]
@misuser 
Sorry I wasn't clear.
v8.4.4 doesn't include the fix.
You have download and copy the binary in which this bug is fixed:
https://ci.appveyor.com/api/buildjobs/6uu3kd43gql6o1n4/artifacts/Notepad%2B%2B.Win32.Release.exe

**Comment by misuser** [comment]
> @misuser Sorry I wasn't clear. v8.4.4 doesn't include the fix. You have download and copy the binary in which this bug is fixed: https://ci.appveyor.com/api/buildjobs/6uu3kd43gql6o1n4/artifacts/Notepad%2B%2B.Win32.Release.exe

I can't use installer. I can only test standalone app. Sorry for that.

**Comment by ArkadiuszMichalski** [comment]
@misuser It's not an installer, just download and put to portable folder and run [(detail)](https://github.com/notepad-plus-plus/notepad-plus-plus/wiki/Testing).

**Comment by misuser** [comment]
> @misuser It's not an installer, just download and put to portable folder and run [(detail)](https://github.com/notepad-plus-plus/notepad-plus-plus/wiki/Testing).

In the release that you provided if dark theme is set in dark mode no surrounding boxes (framing rectangles) appear at all when mouse cursor is placed over a list item in a panel and cursor does not change its shape from default to pointer any more, there is nothing to indicate that item is hovered with mouse any more. When item is clicked only then framing rectangle appears around it. Light themes are still not affected by the issue even in dark mode.

**Comment by ozone10** [comment]
> In the release that you provided if dark theme is set in dark mode no surrounding boxes (framing rectangles) appear at all when mouse cursor is placed over a list item in a panel, text color is not changed and cursor does not change its shape from default to pointer any more, there is nothing to indicate that item is hovered with mouse any more. When mouse button is pressed background of item's text becomes blue which only lasts until mouse button is released. When item is clicked only then framing rectangle appears around it and disappears when another item is clicked.

@misuser 
can you try this binary https://ci.appveyor.com/api/buildjobs/9il74g4054i5hicr/artifacts/Notepad%2B%2B.Win32.Release.exe
I have re-enabled hot tracking, but I am not sure if it works correctly on Windows 8.1.
 
> Light themes ("Hello Kitty" , "Navajo", "Solarized Light") are still not affected by the issue even in dark mode, although when these light themes are set in dark mode and list item in a panel is hovered with mouse, framing rectangle's background is too dark and triangle shaped icons are indistinguishable from the background. When an item is clicked triangle shaped icon changes its color and becomes distinguishable only if the cursor is placed directly over the icon.

Windows 8.1 does not have "dark mode explorer" so it is not possible to change color for arrow icons, but you can change framing rectangle colors.
![image](https://user-images.githubusercontent.com/55940305/179421693-4047a1df-1704-4fd0-8f2c-9fc0243bbc44.png)

**Comment by misuser** [comment]
> can you try this binary https://ci.appveyor.com/api/buildjobs/i7meammnwxqomb69/artifacts/Notepad%2B%2B.Win32.Release.exe

My observations regarding this release:

If a dark theme is set in dark mode:
When list item in panel is hovered with mouse cursor changes its shape to pointer, item's text color is changed to white, text gets underlined, text background changes to gray with no borders. 
When list item in panel is clicked, dark framing rectangle with thin borders appears, spanning panel's width.

If a light theme is set in dark mode:
When list item in panel is hovered with mouse mouse cursor changes its shape to pointer,  item's text color is changed to some light color, text's background also changes to some light color, in case of "Solarized Light" light colored text is almost indistinguishable from the background, text is not underlined and text's background has thin borders unlike dark themes. 
When list item in panel is clicked, dark framing rectangle with thin borders appears, spanning panel's width.

**Comment by ozone10** [comment]
> If a dark theme is set in dark mode: When list item in panel is hovered with mouse cursor changes its shape to pointer, item's text color is changed to white, text gets underlined, text background changes to gray with no borders. When list item in panel is clicked, dark framing rectangle with thin borders appears, spanning panel's width.

Ok dark theme in dark mode is working.

> If a light theme is set in dark mode: When list item in panel is hovered with mouse cursor changes its shape to pointer, item's text color is changed to some light color, text's background also changes to some light color, text is not underlined and text's background has thin borders unlike dark themes. In case of "Solarized Light" light colored text is almost indistinguishable from the background. When list item in panel is clicked, dark framing rectangle with thin borders appears, spanning panel's width.

Can you provide screenshot?

**Comment by ozone10** [comment]
@misuser 
try https://ci.appveyor.com/api/buildjobs/61xl2usr2o7r0mge/artifacts/Notepad%2B%2B.Win32.Release.exe

**Comment by misuser** [comment]
> @misuser
> try https://ci.appveyor.com/api/buildjobs/61xl2usr2o7r0mge/artifacts/Notepad%2B%2B.Win32.Release.exe

Screenshots from this release

Dark theme (Bespin) in dark mode:

![Bespin](https://user-images.githubusercontent.com/109034009/179703764-79f027fe-3173-42a7-ac40-e5b5fc59d122.png)

Light theme (Solarized-light) in dark mode:

![Solarized-light](https://user-images.githubusercontent.com/109034009/179703979-f79d3c45-a9c0-4954-bd4e-f45334d26bed.png)

Now in case of light themes when item in panel is hovered with mouse two rectangles appear: transparent one (which is barely visible)  framing item itself including text and icon on the left and dark one spanning panel's width.
I have a question: is it possible to limit the width of dark rectangle to the item's width including only text and icon on the left so it won't span full panel's width at least when item is just hovered with mouse?

**Comment by ozone10** [comment]
@donho 
Ok I think that reported bug is fixed.

@misuser
> Now in case of light themes when item in panel is hovered with mouse two rectangles appear: semitransparent one (which is barely visible) framing item itself including text and icon on the left and dark one spanning panel's width. I have a question: is it possible to limit the width of dark rectangle to the item's width including only text and icon on the left so it won't span full panel's width at least when item is just hovered with mouse?

It is possible, but I don't want to make code more complex, I also need to take into account that plugin's author might use custom draw, which might cause visual issues if there is issue in code.

You can make separate request issue for it if you want.
