### ISSUE TITLE
Multi-line comments ignored if they begin with single-line comment

### ISSUE THREAD

**Issue by InterLinked1** [notepad-plus-plus/notepad-plus-plus#11897]
### Description of the Issue

For defining multi-line comment syntax in a User Defined Language, the syntax does not seem to get parsed at all if the multi-line comment syntax is a superset of the single-line comment syntax.

### Steps to Reproduce the Issue

1. Use `;` as the single-line comment syntax.
2. Use `;-` as the multi-line comment begin and `-;` as the mutli-line comment end syntax.

(This is the syntax used in the Asterisk config language).

### Expected Behavior
Both single and multi line comments are treated as comments.

### Actual Behavior
Single line comments are displayed as desired; multi-line comments are ignored.

HOWEVER, if you add a `-` before the `;-`, then it gets picked up, so it seems that Notepad++ is ignoring syntax that starts with a `;` because the `;` is used to begin a single-line comment. Thus, it ignores the `-` after the `;` and the multi-line comment never gets picked up. This is a bug.

### Debug Information

Notepad++ v8.3.3   (64-bit)
Build time : Mar 13 2022 - 17:20:02
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 7 Enterprise (64-bit) 
OS Build : 7601.24546
Current ANSI codepage : 1252
Plugins : Explorer.dll mimeTools.dll NppConverter.dll NppExport.dll NppFavorites.dll 

as well as:

Notepad++ v7.7.1   (32-bit)
Build time : Jun 16 2019 - 21:14:50
Path : Y:\Notepad++\App\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : ON
OS : Windows 10 (64-bit)
Plugins : IndentByFold.dll mimeTools.dll NppConverter.dll NppExport.dll NppFavorites.dll

**Comment by dustinvoelker** [comment]
Hello, I am a computer science student and I am looking to work on this issue to contribute to an open source project as part of my software engineering class. Would I be able to work on this with my partner? Thank you.

**Comment by SMCraft21** [comment]
Hi, I am a computer science student and am planning on working with @dustinvoelker on this issue to contribute to an open source project as part of an assignment for a software engineering class. Would it be possible for us to work on this issue if accepted? Thank you.

**Comment by InterLinked1** [comment]
I don't have any affiliation with the project, but generally with open source projects like this one, anyone is welcome to work on an issue and submit a pull request (PR). Whether the PR is accepted or not is up to the maintainer. Either way, thanks for the interest!
