### ISSUE TITLE
Feature request: Allow typing in address bar

### ISSUE THREAD

**Issue by holdenlee** [notepad-plus-plus/notepad-plus-plus#1189]
The address bar is a dropdown which doesn't allow typing. 

(In other applications, I regularly use the address bar to navigate to shortcuts by typing %SHORTCUT_NAME%.)

**Comment by linquize** [comment]
Where is the address bar?

**Comment by holdenlee** [comment]
The address bar is the bar which lists the current directory in the "open file" popup window.
