### ISSUE TITLE
能否支持中西文字体分开设置？

### ISSUE THREAD

**Issue by renyouguo** [notepad-plus-plus/notepad-plus-plus#119]
就像word那样。
文本编辑器目前只发现everedit实现了。

**Comment by MAPJe71** [comment]
Could someone translate this?

**Comment by ariccio** [comment]
> 就像word那样。
 文本编辑器目前只发现everedit实现了。



Google translate phonetic:

> Jiù xiàng word nàyàng. Wénběn biānjí qì mùqián zhǐ fāxiàn everedit shíxiànle.


Google translate final:

> Like that word.  Text Editor is currently found only everedit achieved.

**Comment by ariccio** [comment]
Title of post:

> 能否支持中西文字体分开设置？


Google translate phonetic:

> Néng fǒu zhīchí zhōngxī wén zìtǐ fēnkāi shèzhì?

Google translate final: 

> Western text font can support provided separately?

**Comment by ariccio** [comment]
Ahh that seems to make sense. I think I'll ask a friend who speaks fluent Chinese to confirm.

**Comment by MAPJe71** [comment]
Thanks!
Tried Google Translate, didn't work but that's probably me.

Tried again ... (yes, it was me)
Issue title: `Western text font can support provided separately?`
Issue text: `Like that word. Text Editor is currently found only everedit achieved.`

Issue still doesn't make sense.

**Comment by ariccio** [comment]
Human translation (via my friend): 

> Can (this) install and separate western characters from Chinese?

**Comment by donho** [comment]
@renyouguo 
中西文字体分开设置？像word？
很抱歉，我還是不明白你的意思。
可否詳加說明i？謝謝。

**Comment by ariccio** [comment]
You speak chinese?

**Comment by MAPJe71** [comment]
i.e.
> Western text font set separately ? Like word?
> Sorry, I still do not understand what you mean.
> Can you elaborate ? THX.
> (If any pictures better)

@ariccio You're kidding right?

**Comment by ariccio** [comment]
> @ariccio You're kidding right?

No, actually. I'm (apparently just) stupid. 

Google translate, duh!

**Comment by renyouguo** [comment]
@donho 
![everedit](https://cloud.githubusercontent.com/assets/2649544/7826578/6b5e0f34-044e-11e5-83f1-4d3cf2474e89.png)

说明参见：
文档 - EverEdit | 领先的专业文本编辑器
http://cn.everedit.net/doc.html
字体
2：激活中日韩专用字体。勾选该项的话，将会激活一个新的字体设定tab（CJK），在该tab可以配置中日韩字符专用的字体。当遇到中日韩字符时，EverEdit会使用该字体进行渲染。

**Comment by ariccio** [comment]
> 说明参见：
> 文档 - EverEdit | 领先的专业文本编辑器
> http://cn.everedit.net/doc.html
> 字体
> 2：激活中日韩专用字体。勾选该项的话，将会激活一个新的字体设定tab（CJK），在该tab可以配置中日韩字符专用的字体。当遇到中日韩字符时，EverEdit会使用该字体进行渲染。

Google translate phonetic:

> Shuōmíng cānjiàn:
> Wéndàng - EverEdit | lǐngxiān de zhuānyè wénběn biānjí qì
> http://Cn.Everedit.Net/doc.Html
> zìtǐ
> 2: Jīhuó zhōng rì hán zhuānyòng zìtǐ. Gōu xuǎn gāi xiàng dehuà, jiāng huì jīhuó yīgè xīn de zìtǐ shè dìng tab(CJK), zài gāi tab kěyǐ pèizhì zhōng rì hán zìfú zhuānyòng de zìtǐ. Dāng yù dào zhōng rì hán zìfú shí,EverEdit huì shǐyòng gāi zìtǐ jìnxíng xuànrǎn.


Google translate final:

> Description See also:
> Documentation - EverEdit | leading professional text editor
> http://cn.everedit.net/doc.html
> Font
> 2: Activate CJK specific fonts. Check the box, it will activate a new font settings tab (CJK), the tab can be configured CJK character-specific font. When faced with CJK characters, EverEdit will use the font rendering.


English version of documentation link: http://www.everedit.net/doc.html

**Comment by ariccio** [comment]
I think the checkbox in the screenshot (labeled in chinese) is mentioned in the docs as:

> If you want to use CJK font, check the [CJK characters use second font] checkbox.

Which I think means that this user is asking for a feature that allows [CJK characters](https://en.wikipedia.org/wiki/CJK_characters) to be rendered in a separate font, *inline with other text*.

I think this is Scintilla's responsibility? 

Related:

[FAQ: How to enable Cantonese characters and Unicode Chinese Extensions in Windows](http://www.pinyinjoe.com/faq/windows-cantonese-chinese-characters-cjk-extension.htm)

**Comment by donho** [comment]
@renyouguo It's hard to implement this feature in Notepad++. I will keep it in mind but it won't be the priority.

**Comment by prclx323800** [comment]
现在网上可以下载到一个混合字体，中文由微软雅黑组成，西文由 Consolas 组成。如果你喜欢这两个字体混搭的话就不需要 NPP 加新功能了。

I'll translate myself so that some of you don't need to go to Google.
I mean, a font of mixture can be found on the Internet, which uses Microsoft Yahei (the default font of Windows 7+ for China) for Chinese words, and Consolas for western words (letters, numbers and symbols). If renyouguo likes these two, there is no need for Notepad++ to add a new feature.
(Sorry for my grammar mistakes probably)

**Comment by donho** [comment]
@prclx323800  That's a great tip! Thx!
