### ISSUE TITLE
do twice "Find in Files", then the Search results window is abnormal

### ISSUE THREAD

**Issue by Tvirus** [notepad-plus-plus/notepad-plus-plus#11907]
### Steps to Reproduce the Issue

1. do Find in Files (Refer to the attached picture)
2. do again
3.  the Search results window is abnormal, turned black and white (Refer to the attached picture)

![err](https://user-images.githubusercontent.com/42616862/178470225-f6a4c603-1a5a-493d-88f3-af7205f3e06e.PNG)

Notepad++ v8.4.3   (64-bit)
Build time : Jul  7 2022 - 10:55:58
Path : D:\Notepad++\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 10 Pro (64-bit) 
OS Version : 21H2
OS Build : 19044.1766
Current ANSI codepage : 936
Plugins : 
    mimeTools (2.8)
    NppConverter (4.4)
    NppExport (0.4)

**Comment by donho** [comment]
Fixed in https://github.com/notepad-plus-plus/notepad-plus-plus/commit/e6fe568bbf83b38449306d75bb2f8ea1aa766b54
The fix will be in the next release which is coming.
