### ISSUE TITLE
Command line parameter -n stopped working with 8.4.2

### ISSUE THREAD

**Issue by leitwolf7** [notepad-plus-plus/notepad-plus-plus#11901]
### Description of the Issue

When -n123 is specified on the command line, Notepad++ opens the file but does not jump to the given line number 123.
This worked before.

### Steps to Reproduce the Issue

1. On the command line, invoke like this: "notepad++.exe -n%line% %path%" where %line% is a valid line number and %path% a valid file.

### Expected Behavior

Notepad++ opens the file and jumps to the specified line number.

### Actual Behavior

Notepad++ opens the file and the cursor is line 1, column 1.

### Debug Information

Notepad++ v8.4.2   (32-bit)
Build time : May 29 2022 - 16:45:17
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Command Line : $COMMAND_LINE_PLACEHOLDER$
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 10 Enterprise (64-bit) 
OS Version : 21H2
OS Build : 19044.1766
Current ANSI codepage : 1252
Plugins : 
    mimeTools (2.8)
    NppConverter (4.4)
    NppExport (0.4)

**Comment by alankilborn** [comment]
`-n` works fine for me on the same version.
It is a pity that "Command Line" in the _Debug Info_ isn't working correctly; we can't see exactly what the program thinks it is getting on the command line. :-(
