### ISSUE TITLE
Why the Incremental Search didn't support RegEx?

### ISSUE THREAD

**Issue by znsoooo** [notepad-plus-plus/notepad-plus-plus#11902]
Sometimes I want to type a regular expression into the search box and get a match right away, so I can quickly confirm that the expression I've written is correct.

And I found the incremental search function, but it doesn't support regular expressions.

Another thing, does the mark panel can be able to support hightlight the captured groups for a complex regular expression into different color?

e.g. `(\w+)\.(\w+)`.

**Comment by alankilborn** [comment]
You should create TWO separate issues for these items, to serve as feature requests.

**Comment by alankilborn** [comment]
Also, regarding the regex part, see:

* https://community.notepad-plus-plus.org/topic/12722/survey-incremental-search-usefulness
* https://community.notepad-plus-plus.org/topic/19309/vim-like-search

**Comment by znsoooo** [comment]
Thanks for these references. This is a disappointing ending. I will fork and build it myself if I need.

**Comment by donho** [comment]
Incremental search is for a quick search so its interface provides minimum parameters.
If you want a more sophisticated search, you can use Find/Replace dialog instead. It will allow user to collapse the dialog in the future (the dialog takes less space).
