### ISSUE TITLE
[Bug] The crash of the plugin should not cause Npp to crash

### ISSUE THREAD

**Issue by znsoooo** [notepad-plus-plus/notepad-plus-plus#11903]
When I use the plugin `MarkdownPanel` and `MarkdownViewer++` and `RunMe`, the plugin function often crashes, **and the Npp exit too**. I was opening a complex makrdown file, and I was tested on **Npp v8.4.2 32 bit** and **Npp v7.6.3 32 bit**.

Maybe it behaves differently on different computers, so maybe I can't give a reproducible example.

Of course, plugin crashes are a matter of plugins, but is it possible to make virtual isolation between Npp and plugin, so it can **prevent Npp from crashing and exiting along with it**?

**Comment by alankilborn** [comment]
No, not possible.  Please close this issue.

**Comment by donho** [comment]
@znsoooo 
Please use the template and provide the complete info.
