### ISSUE TITLE
TextFx missing after installing v8.4.3

### ISSUE THREAD

**Issue by DavidHaslam** [notepad-plus-plus/notepad-plus-plus#11900]
The TextFx plugin has gone missing after I installed v8.4.3

It was still working while I was using v8.4.2

It’s not even listed anymore in available plugins.

**Comment by ArkadiuszMichalski** [comment]
Maybe completely dead.
https://github.com/notepad-plus-plus/nppPluginList/issues/472

**Comment by alankilborn** [comment]
@DavidHaslam 

Some other info on the state of TextFX here:  https://community.notepad-plus-plus.org/topic/23166/faq-desk-how-do-i-replicate-the-features-of-textfx

**Comment by ArkadiuszMichalski** [comment]
@DavidHaslam You can try change `NPP\plugins\Config\nppPluginList.dll` name, for example to `_nppPluginList.dll`, but you lost `Plugin admin` functionality.

**Comment by rainman74** [comment]
Use this new compiled version:
https://github.com/rainman74/NPPTextFX2/releases

**Comment by DavidHaslam** [comment]
> Use this new compiled version:
> https://github.com/rainman74/NPPTextFX2/releases

@rainman74  - many thanks! That works with both v8.4.3 & v8.4.4 of Notepad++ (x86).
