### ISSUE TITLE
Notepad++ release 8.4.3: broken highlight in search

### ISSUE THREAD

**Issue by MrMyth** [notepad-plus-plus/notepad-plus-plus#11920]
Good evening. As a result of the search, the backlight is broken.
1) We are looking for any word. The search results will be correct.
2) We are looking for something again. In the search results, all text will be black, even the names of the files where the word was found. If you click on the file name, it will not open.

**Comment by rdipardo** [comment]
Already reported in #11910 and #11883

A patched version of Notepad++ can be downloaded here: https://ci.appveyor.com/project/donho/notepad-plus-plus/builds/44124788/job/99g24uejgy2yp7hj/artifacts

**Comment by ArkadiuszMichalski** [comment]
@MrMyth You can try portable and `.exe` from above link to confirm that it was fixed ([instruction](https://github.com/notepad-plus-plus/notepad-plus-plus/wiki/Testing#using-the-latest-release-portable-version-of-notepad)).

**Comment by MrMyth** [comment]
Fix. Thx.
