### ISSUE TITLE
TextFX removes last character when running character case conversion

### ISSUE THREAD

**Issue by TamBuzz** [notepad-plus-plus/notepad-plus-plus#11925]
### Description of the Issue

When converting text character case to a different case (uppercase, lowercase, proper case, sentence case, etc) using TextFX, the last character (or space) in the selection is getting deleted. It used to work properly and has recently started having this issue.

### Steps to Reproduce the Issue

1. Install TextFX into Notepad++
2. Type some characters or words
3. Select some or all of those characters or words (also try including an ending space)
4. Note how many characters are included in your selection
5. Click on TextFX in the menu bar
6. Select TextFX Characters
7. Select any of the "case" commands in the bottom section to run one of those commands
8. Notice that the last character in the resulting text has been deleted, while the rest of the characters got converted appropriately.

### Expected Behavior

Expected behavior is to have the same number of characters before running the TextFx character case conversion command as after running the command.

### Actual Behavior

The last character in the selection was deleted by running the TextFx character case conversion command.

### Debug Information

Notepad++ v8.4.2   (32-bit)
Build time : May 29 2022 - 16:45:17
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Command Line : $COMMAND_LINE_PLACEHOLDER$
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 10 Home (64-bit) 
OS Version : 21H2
OS Build : 19044.1826
Current ANSI codepage : 1252
Plugins : 
    DSpellCheck (1.4.15)
    mimeTools (2.8)
    NppConverter (4.4)
    NppExport (0.4)
    NppTextFX (0.2.6)

**Comment by rdipardo** [comment]
Known issue: https://sourceforge.net/p/npp-plugins/bugs/354 

See ["How do I Replicate the Features of TextFX?"](https://community.notepad-plus-plus.org/topic/23166/faq-desk-how-do-i-replicate-the-features-of-textfx), or have a look at [NPPTextFX2](https://github.com/rainman74/NPPTextFX2/releases).

**Comment by ArkadiuszMichalski** [comment]
This should be report to plugins author.

**Comment by TamBuzz** [comment]
> See ["How do I Replicate the Features of TextFX?"](https://community.notepad-plus-plus.org/topic/23166/faq-desk-how-do-i-replicate-the-features-of-textfx), or have a look at [NPPTextFX2](https://github.com/rainman74/NPPTextFX2/releases).

Thank you for the helpful links! Funny, I had no idea these functions had been integrated into Notepad++! I really should read update notes every time.
