### ISSUE TITLE
[Question] How is the autotyping feauture developed in "Je suis  Charlie Edition"?

### ISSUE THREAD

**Issue by GeorgeGkas-zz** [notepad-plus-plus/notepad-plus-plus#1193]
A question that most of us asked on the web.
In the special release version 6.7.4 "Je suis Charlie" the first thing that someone point is the welcome message. A very well design auto typing message. 
I wanted to ask the actual developers how they have get it. I mean with the time. How the set the `wait()` function in their code to print the letters of the sentences so smoothly?
Can you please point it in the project file or answer?

**Comment by TdPiza** [comment]
I liked it too! I wish I had that exe file so I could read it again.

**Comment by vlakoff** [comment]
Have a look at:
* [6.7.4 release](https://github.com/notepad-plus-plus/notepad-plus-plus/commit/00f664188f844d0c58f8c73a9c7b7e89ae72b41e)
* [`Notepad_plus::showQuoteFromIndex`](https://github.com/notepad-plus-plus/notepad-plus-plus/blob/d8f6ac67ea31a33feaeca37f00d01835ce9904d7/PowerEditor/src/Notepad_plus.cpp#L5980)
* and especially [`Notepad_plus::threadTextPlayer`](https://github.com/notepad-plus-plus/notepad-plus-plus/blob/d8f6ac67ea31a33feaeca37f00d01835ce9904d7/PowerEditor/src/Notepad_plus.cpp#L5699)
