### ISSUE TITLE
Open Notepad++ after windows restart

### ISSUE THREAD

**Issue by HarelM** [notepad-plus-plus/notepad-plus-plus#11934]
First and foremost, this is a great piece of software! I love it! Thanks you for all the hard work on this!

### Description of the Issue
If Notepad++ was open before a windows restart (for windows updates for example) it will not be reopened after the restart had completed.

### Steps to Reproduce the Issue
1. Open notepad++
2. Restart windows
3. --> Notepad++ is not lunched after the system finishes to boot up.

### Expected Behavior
This is more of a feature request, but it would be nice if notepad++ could be opened after restart

### Actual Behavior
I need to manually open it.

### Debug Information
Not a bug...

### More info
I think the following article might help, but I haven't been writing in C++ for a long time so I'm not sure:
https://docs.microsoft.com/en-us/windows/win32/recovery/registering-for-application-restart

Also worth noting:
I use windows and other applications such as outlook, edge, chrome, teams etc... have been adopting this behavior lately, and I think it's a great user experience.
I'm also using a mac (which sadly can't run notepad++ >>sob<<) and has this experience for longer time now.

**Comment by CennoxX** [comment]
Duplicate of #9722.

**Comment by HarelM** [comment]
My bad, thanks for the info!
