### ISSUE TITLE
Clear search results leaves "(X hit(s))" whereas there is no more search result

### ISSUE THREAD

**Issue by gluttony38** [notepad-plus-plus/notepad-plus-plus#11931]
### Introduction
This is a very minor issue but still, I report it.

### Description of the Issue
After a search in files, when clearing all, a "(X hit(s))" is still displayed whereas there is no more search result

### Steps to Reproduce the Issue
1. Start a search in files with Ctrl+Shift+F, pressing "Find all", for instance:
![image](https://user-images.githubusercontent.com/16116396/179742503-0d7259fa-f4fc-4530-9a0f-2f9d43737bc8.png)
2. Search results are displayed, with number of hit(s):
![image](https://user-images.githubusercontent.com/16116396/179742736-c0ca696a-e7a1-4dfa-a333-e913b2fce15d.png)
3. Press right click then "Clear all" in search result view, search results are cleared but there is still the number of hit(s) displayed:
![image](https://user-images.githubusercontent.com/16116396/179742994-1aba86ae-ca48-4e30-b7b7-47ec75885c54.png)

### Expected Behavior
When clearing all, number of hit(s) should be set to 0 or hidden (just display "Search results").

### Actual Behavior
Number of hit(s) are displayed whereas there is no more result.

**Comment by Yaron10** [comment]
https://github.com/notepad-plus-plus/notepad-plus-plus/issues/8626.

**Comment by ArkadiuszMichalski** [comment]
Duplicate.
