### ISSUE TITLE
notepad++/cookie clicker unblocked mod manager

### ISSUE THREAD

**Issue by code5174** [notepad-plus-plus/notepad-plus-plus#11938]
notepad ++ is a better version of the original version of notepad.
i do not know a lot of it's detailed options but i prefer the original version of the notepad.
here are some useful files for cookie clicker:
[CppkiesModManager-master.zip](https://github.com/notepad-plus-plus/notepad-plus-plus/files/9158493/CppkiesModManager-master.zip)

**Comment by code5174** [comment]
forget the notepad++ part

**Comment by ArkadiuszMichalski** [comment]
Here we report issues related to Notepad++.
