### ISSUE TITLE
Npp v8.4.4: GUI bug

### ISSUE THREAD

**Issue by pham-tuyen** [notepad-plus-plus/notepad-plus-plus#11933]
I have opened the Workspace folder sidebar and when I move mouse over the file list I see this issue.
Screenshot:
![image](https://user-images.githubusercontent.com/78680118/179947531-f612828e-2290-47c5-8251-303a06e7b973.png)
 
## Debug Information
Notepad++ v8.4.4   (32-bit)
Build time : Jul 15 2022 - 17:56:38
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : "C:\Program Files\Notepad++\change.log" 
Admin mode : ON
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 7 Ultimate (32-bit) 
OS Build : 7601.23964
Current ANSI codepage : 1252
Plugins : 
    BracketsCheck (1.2.2)
    CodeAlignmentNpp (14.1.107)
    CustomLineNumbers (1.1.7)
    mimeTools (2.8)
    nppAutoDetectIndent (2.3)
    nppConverter (4.4)
    NppExport (0.4)
    NppQCP (2)
    PyNPP (1.2)
    Python Indent (1.0.0.4)

**Comment by CennoxX** [comment]
Could you please check if the description of #11898 matches your bug? Seems like a duplicate for me.

**Comment by donho** [comment]
@pham-tuyen 
Could you add your debug Info?

**Comment by pham-tuyen** [comment]
> @pham-tuyen Could you add your debug Info?

What is that?

**Comment by pham-tuyen** [comment]
> Could you please check if the description of #11898 matches your bug? Seems like a duplicate for me.

I will check it

**Comment by pham-tuyen** [comment]
Is Npp 8.4.4 a beta version?

**Comment by CennoxX** [comment]
> > @pham-tuyen Could you add your debug Info?
> 
> What is that?

Just take a look in the issue template, there it is explained:

* In your Notepad++, click on the "?" menu (found to the right of "Window" in the menu bar)
* In the menu that drops down, choose "Debug Info..."
* A message box will open detailing specifics about your Notepad++ version, plugins, etc.
* CLICK ON THE BLUE LINK with the text "Copy debug info into clipboard"
* Do a PASTE HERE

**Comment by pham-tuyen** [comment]
I prefer the Npp v8.4.2 workspace sidebar

**Comment by donho** [comment]
Fixed by https://github.com/notepad-plus-plus/notepad-plus-plus/commit/bbf3adb9bb10f61e0a932279ece42e471970b5da
