### ISSUE TITLE
Option for hiding the ＋ and ▼ buttons that were added to the menu bar

### ISSUE THREAD

**Issue by peter-fb** [notepad-plus-plus/notepad-plus-plus#11945]
Can you please add an option for hiding the two new shortcuts (＋ and ▼ buttons) that were added to the menu bar?

The shortcuts add clutter and if there's a way to remove them again I would be very grateful.

**Comment by donho** [comment]
Hiding ＋ and ▼ will also hide X.
Is it what you want?

**Comment by peter-fb** [comment]
Yes, that would be fine.

**Comment by alankilborn** [comment]
The way I see it, the "clutter", if there was any, has now been moved from where it was, to the _Preferences_ area.  Bummer.  I really liked it when the attitude was "too many options == no option".

**Comment by Giulidan** [comment]
I never liked that 'x' button either. Thank you for the OP for suggesting this and thank you @donho for the work!
