### ISSUE TITLE
Set the default language

### ISSUE THREAD

**Issue by wqcblog** [notepad-plus-plus/notepad-plus-plus#11947]
I want to set the default appearance language in notepad++, I understand the way of graphical setting, but which file is the language configuration saved in, please help me solve this problem, thank you

**Comment by alankilborn** [comment]
Please post your question here: https://community.notepad-plus-plus.org/

**Comment by ArkadiuszMichalski** [comment]
Here we open/discuss about issues. As suggested above please use forum.
