### ISSUE TITLE
Cursor behavs strange since a long time...

### ISSUE THREAD

**Issue by madmetz** [notepad-plus-plus/notepad-plus-plus#11944]
### Description of the Issue
A long time ago and many versions before 8.4.4 the text cursor has changed its behavior.
Before, it was correct wich means - if you mark a single character the character changes its background color and the cursor moves one position forward. Starting from version (I don't know) the cursor doesn't move anymore and is in some cases even invisible.
(I think this depends on the highlite/background color settings.) This is sometimes confusing. Especially if several lines are selected
or in case of copy and paste.
Can you please go back to the original state?

### Steps to Reproduce the Issue

1.  Mark a character or an entire  line 
2.  Watch the cursor
3. 

### Expected Behavior
Cursor should move one step ahead or to the beginning of the next line if an entire line is selected.

### Actual Behavior
The cursor remains at its current position.

**Comment by alankilborn** [comment]
Perhaps some screenshots or a video of your situation helps here, as I see no such problem when I use 8.4.4 or prior versions.

**Comment by madmetz** [comment]
I made 4 jpegs in order to verify notepad++ with arduino-ide editor.
In (much) earlier versions notepad++ behave like arduino-ide or microsoft notepad.

![arduino-ide_entire_line_marked](https://user-images.githubusercontent.com/42972320/180860991-01bc814c-d3ee-45ef-88b6-8b7edb2d57bc.jpg)
![arduino-ide_some_chars_marked](https://user-images.githubusercontent.com/42972320/180860994-61400dd6-f0e3-4118-9a54-6ffd76f46a42.jpg)
![notepad++_entire_line_marked](https://user-images.githubusercontent.com/42972320/180860997-94e2684b-6c5c-4b16-9db1-e6280ebde845.jpg)
![notepad++_some_chars_marked](https://user-images.githubusercontent.com/42972320/180861000-28d51789-6da0-454c-b4f2-a5ff2c1770f6.jpg)

**Comment by alankilborn** [comment]
Without the screenshots I for one would have never surmised what the actual complaint was.  So thank you for the screenshots.

I believe what you are seeing is an effect from having a "Block" caret selected:

![image](https://user-images.githubusercontent.com/77065706/180865224-0f2b91dd-f4a4-48ae-a7a8-a821f444edf5.png)

I seem to recall some really old discussion about how this should work (for the "Block" caret), and I think the result of that was the behavior you are seeing.  This is not just true for Notepad++ but also for the editing component project that Notepad++ embeds (called Scintilla).  I think what was decided is that what you are seeing is the correct way for it to function.

I'd suggest changing the caret setting; perhaps set the width to 3.

**Comment by alankilborn** [comment]
Maybe this discussion is the old one I am remembering?:  https://github.com/notepad-plus-plus/notepad-plus-plus/issues/5833

**Comment by alankilborn** [comment]
OK, so I did some more research.  Scintilla added an option for the SCI_SETCARETSTYLE command called CARETSTYLE_BLOCK_AFTER.  Subsequent to that, Notepad++ did not elect to implement a change that would allow that choice to be used by its users.

**Comment by alankilborn** [comment]
A suggestion for Notepad++ developers might be to add a new entry to this dropdown:

![image](https://user-images.githubusercontent.com/77065706/180870143-02ffc215-394f-4ee3-9207-233902e510f1.png)

The entry could be called "Block After" so that the choices in the dropdown would be:

* 0
* 1
* 2
* 3
* Block
* Block After

Currently the code for the "Block" selection is:

https://github.com/notepad-plus-plus/notepad-plus-plus/blob/7a64fd5161f5cd09254260229bd9fbbb64e49b55/PowerEditor/src/NppBigSwitch.cpp#L1641

If the "Block After" choice was made, the code for that would look like this:

    _mainEditView.execute(SCI_SETCARETSTYLE, CARETSTYLE_BLOCK | CARETSTYLE_BLOCK_AFTER);

**Comment by madmetz** [comment]
> If the "Block After" choice was made, the code for that would look like this:
> 
> ```
> _mainEditView.execute(SCI_SETCARETSTYLE, CARETSTYLE_BLOCK | CARETSTYLE_BLOCK_AFTER);
> ```

Many thanks for your effort. If it works, it will make me a bit happier.

**Comment by alankilborn** [comment]
>Many thanks for your effort

Well, I didn't do anything that will affect the code.
A developer will have to come along and read this and agree it is a good change to make.
And then actually make it.

**Comment by alankilborn** [comment]
Nice job, @donho !

**Comment by madmetz** [comment]
@alankilborn - I fully agree...
@donho - I'll keep waiting...
Thanks to both of you.
