### ISSUE TITLE
Toolbar missing from new instance

### ISSUE THREAD

**Issue by lazylionca** [notepad-plus-plus/notepad-plus-plus#11948]
### Description of the Issue
Whenever I open a new instance, the toolbar and status bar are missing.
(menu bar and tab bar are fine)
If I open a new tab, or resize the window, they appear.
If go to settings/preferences and make a change, they appear.
Show status bar is checked.
Hide is unchecked.

### Steps to Reproduce the Issue
1.  Select "Always in multi-instance mode"
2.  Open a new instance
3. 

### Expected Behavior
Expect to see the status bar and tool bar.

### Actual Behavior
menu bar and status bar are not visible

### Debug Information
Notepad++ v8.4.4   (64-bit)
Build time : Jul 15 2022 - 17:54:42
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : "C:\OneDrive\OneDrive - vincentcommunications.ca\-- Checklists\Commissioning.txt"
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 10 Pro (64-bit) 
OS Version : 21H2
OS Build : 19044.1826
Current ANSI codepage : 1252
Plugins : 
    ComparePlugin (2.0.2)
    mimeTools (2.8)
    NppConverter (4.4)
    NppExport (0.4)
    NPPJSONViewer (1.40)

**Comment by ArkadiuszMichalski** [comment]
@lazylionca Try with portable to eliminate configuration problem.

**Comment by lazylionca** [comment]
Hi all

This seems to have been caused by a 3rd party program: Actual Windows Manager.

Thanks anyway.

**Comment by bmazak** [comment]
I did the removal of the _ before CutomizeToolBar in the folder called Plugins and they came back. Then I went into the Plugins/CustomizeToolBar and installed it again and it worked.  Something about new version and must remove the _CustommizeToolBar entry.  Must be a bug.  Never had this problem before last update 7.7.1.  Do plugins get updated automatically?
