### ISSUE TITLE
Function Completion: keystroke to cycle through choices

### ISSUE THREAD

**Issue by pryrt** [notepad-plus-plus/notepad-plus-plus#11950]
### Description of the Issue

Function Completion allows multiple “overload” variants in the definitions. I know when it pops down, you can click on the up and down arrows to cycle through those variants:
![image](https://user-images.githubusercontent.com/17455758/181627519-8fbb3aa3-8616-40e9-9835-bdd854fc7b43.png)

However, there doesn't appear to be a keyboard shortcut for that action.

In other programs, like Visual Studio, when doing Function parameter Completion, you can use the up and down arrows to navigate between the overloaded function definition popups: 
![image](https://user-images.githubusercontent.com/17455758/181627545-a0315289-1cee-4811-a04f-c6e620116f81.png)

In Notepad++, when doing normal "word" autocomplete, you can use the up and down arrows to select between the various options: 
![image](https://user-images.githubusercontent.com/17455758/181627603-e0ccb9d8-1ee8-4e33-bc27-a21f64130b70.png)

But in the Notepad++ Function Completion, it doesn't have that.

This was brought up in a post about IDE features in Notepad++ and other editors [in a Perl forum](https://perlmonks.org/?node_id=11145809).  This was a confusing discrepancy for the person trying Notepad++'s implementation for the first time.  Being able to navigate through the Function Completion choices by keyboard would make another selling point for Notepad++ in such discussions when talking with people in forums not related to Notepad++. ;-)

### Steps to Reproduce the Issue

1. Language > Perl (or any other language that has Function Completion definitions
2. type `split(`, or use Ctrl+Shift+Spacebar after navigating to the right of the paren in `split(...)`
3. You can navigate the overload options by clicking on the arrow buttons, but you cannot navigate through those options using the keyboard

### Expected Behavior

Allow a keyboard input there: it doesn't really matter whether it's Up and Down arrows, or some shift+ or alt+ the arrows, or something similar.  (For comparison: VS uses the standard up/down arrows.)

### Actual Behavior

You cannot navigate those choices with the keyboard.

### Debug Information

```
Notepad++ v8.4.4   (64-bit)
Build time : Jul 15 2022 - 17:54:42
Path : c:\usr\local\apps\npp\npp.8.4.4.portable.x64\notepad++.exe
Command Line : -multiInst
Admin mode : OFF
Local Conf mode : ON
Cloud Config : OFF
OS Name : Windows 10 Enterprise (64-bit) 
OS Version : 20H2
OS Build : 19042.1586
Current ANSI codepage : 1252
Plugins : 
    mimeTools (2.8)
    NppConverter (4.4)
    NppExport (0.4)
```

**Comment by vinsworldcom** [comment]
Community discussion:  https://community.notepad-plus-plus.org/topic/23315/function-completion-cycle-through-choices
