### ISSUE TITLE
how to install notepad++ on ubuntu?

### ISSUE THREAD

**Issue by ardeal** [notepad-plus-plus/notepad-plus-plus#11965]
Hi,

how could I install notepad++ on ubuntu?

**Comment by xomx** [comment]
https://www.google.com/search?q=how+could+I+install+notepad%2B%2B+on+ubuntu%3F

**Comment by alankilborn** [comment]
Further questions should be posted here:  https://community.notepad-plus-plus.org/

**Comment by ArkadiuszMichalski** [comment]
Please use forum for such questions.
