### ISSUE TITLE
Enhancement - Allow F13 to F24 keys for shortcuts, and have ability to set shortcut by tapping key combination (rather than selecting from a dropdown)

### ISSUE THREAD

**Issue by Lewis8379** [notepad-plus-plus/notepad-plus-plus#11975]
### Description of the Issue

Although I understand that the majority of people do not use the F13 to F24 keys, as they are not on physical keyboards, these keys can still be accessed by other means, such as using macro buttons like the Stream Deck. 

The shortcut mapper only shows F1 to F12 in the dropdown, however, the shortcuts.xml file under \AppData\Roaming\Notepad++ shows the key as the number from https://docs.microsoft.com/en-us/dotnet/api/system.windows.forms.keys?view=windowsdesktop-6.0

If I open the shortcuts file and replace the "key" with its matching number from the above website, like "124" for the F13 key, save the file, and reload Notepad++, the F13 does work as expected, but the shortcut mapper shows the shortcut as "Unlisted".

On another note, it's a shame that there's also no ability to click inside the box, use the shortcut key, and the dialog box fills up with the key combination I had just physically pressed. Having to go through and find the key in a dropdown feels archaic

### Steps to Reproduce the Issue

1. Open the shortcut mapper
2. Try to set up a new shortcut for an F13 to F24 key
3. See it only lists F1 to F12

![1](https://user-images.githubusercontent.com/89745850/182486393-3784ccaa-4d80-4536-ad97-c2e80fd010ee.png)
![2](https://user-images.githubusercontent.com/89745850/182486457-b15aa3a0-738f-470d-8b21-7f799a61e3c0.png)
![3](https://user-images.githubusercontent.com/89745850/182486511-dcdf9ecd-25d1-4b7a-ac68-9560cea8449e.png)

**Comment by CeelB-2055440** [comment]
Yes, please! Add the keys F13 - F24. These keys are reserved keys that you can map to your additional mouse buttons. (Like I have done.)  So, you could press one of these buttons, these would then activate a macro.
