### ISSUE TITLE
Crash when a document is moved by drag and drop from another instance

### ISSUE THREAD

**Issue by m-wim** [notepad-plus-plus/notepad-plus-plus#11976]
### Description of the Issue
Notepad++.exe crashes when a document is moved by drag and drop from another instance

### Steps to Reproduce the Issue
1.  Open more than two documents
2.  Move two of the documents into a new instance by context menu of document tab, so there are two additional instances running now
3.  Consolidate these two instances by dragging and dropping one document to the instance of the other

### Expected Behavior
One instance closes, the other instance shows two documents

### Actual Behavior
One instance closes, the other instance crashes:
Unhandled exception at 0x00007FF75ECA29A0 in notepad++.exe: An invalid parameter was passed to a function that considers invalid parameters fatal.

### Debug Information
Notepad++ v8.4.4   (64-bit)
Build time : Jul 15 2022 - 17:54:42
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : "C:\Projects\Funktionstest.GEN\remote_test_20220803-0813_AROMEERL0128GB\syslog-AROMEERL0128GB-20220803-081902.log"
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 10 Enterprise (64-bit) 
OS Version : 20H2
OS Build : 19042.1826
Current ANSI codepage : 1252
Plugins : 
    BetterMultiSelection (1.4)
    BookmarksDook (2.3.3)
    ComparePlugin (2.0.2)
    Explorer (1.9.4)
    HexEditor (0.9.12)
    Linefilter3 (1)
    mimeTools (2.8)
    NppConverter (4.4)
    NppEventExec (0.9)
    NppExec (0.6.2)
    NppExport (0.4)
    NppTextViz (0.4.2)
    NppXmlTreeviewPlugin (2)

**Comment by xomx** [comment]
@m-wim 

Could you please replace your "notepad++.exe" file with [the patched one](https://ci.appveyor.com/api/buildjobs/lvpexo037p2k4dvs/artifacts/Notepad%2B%2B.x64.Release.exe) and test again?
