### ISSUE TITLE
Only autofill search text in find and replace dialog if text is **_highlighted_** when opened

### ISSUE THREAD

**Issue by vertigo220** [notepad-plus-plus/notepad-plus-plus#11988]
### Description of the Issue

As the title says. I personally find it very useful to have the "Find what" box auto-filled with _selected_ text, but it's also very counter-productive when it auto-fills with the word the cursor is on, when that word isn't selected. I have to place the cursor on a blank line every time I open the search box if I don't want this to happen.

This has been brought up at least a couple times before, but this specific issue has been seemingly ignored/overlooked. In #2373, it's stated that it works this way, but that is not my experience, up to and including the latest version, so maybe something has changed since then. In #3243, the option "Searching > Don't fill find field in Find dialog with selected word" was added, but as mentioned by a couple users after the change, it only provides an all-or-nothing option. Those users, like myself, want the feature but only want it to work when a word is actually highlighted, which is how it's supposed to work, _not_ when nothing is highlighted.

### Steps to Reproduce the Issue

1. Open Find dialog and enter some text in the "Find what" box
2. Close the dialog
3. Place the cursor on a word but _don't_ highlight it
4. Open Find dialog and see that the word where the cursor is placed was auto-filled, replacing the text you previously had there

### Expected Behavior

With no selection, no autofill should occur

### Actual Behavior

With no selection, autofill does occur

### Debug Information

Notepad++ v8.4.4   (64-bit)
Build time : Jul 15 2022 - 17:54:42
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : "C:\Program Files\Notepad++\change.log" 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 10 Pro N (64-bit) 
OS Version : 21H2
OS Build : 19044.1826
Current ANSI codepage : 1252
Plugins : 
    mimeTools (2.8)
    NavigateTo (1.12.4.1)
    NppConverter (4.4)
    NppExport (0.4)
    NppMenuSearch (0.9.3)
    NppSaveAsAdmin (1.0.211)
    NppSnippets (1.6)
    RegexTrainer (1)
    RunMe (1.4)
    SurroundSelection (1.4.1)
    _CustomizeToolbar (4.2)

**Comment by tools400** [comment]
Great to have that new option.
