### ISSUE TITLE
Hide "Find in Files progress..." dialog box

### ISSUE THREAD

**Issue by evildog1** [notepad-plus-plus/notepad-plus-plus#1198]
Hi

Can you make it hide behind the other window when i focus other windows? it's annoying when it just sit on the front of the screen while i'm multitasking.

![billede 2015 15 11 57](https://cloud.githubusercontent.com/assets/8687585/11457548/07be3f44-96ac-11e5-886b-c02cb9e957be.png)

**Comment by donho** [comment]
Yes, indeed.
@pnedev any solution for that?

**Comment by vlakoff** [comment]
Same as #293.
