### ISSUE TITLE
[Feature Request] Syntax Highlight CDATA Content in XML Files

### ISSUE THREAD

**Issue by Yaron10** [notepad-plus-plus/notepad-plus-plus#1199]
Hello,

I would like to apply my JavaScript style-settings to the CDATA sections in XML files.
In Style Configurator -> XML you can set CDATA style, but the entire content is displayed in the same font and color.

Thank you.

**Comment by MetaChuh** [comment]
@Yaron10 

sorry, we can't do much if it isn't a feature available at scintilla.

many thanks and best regards.
