### ISSUE TITLE
regex search matchs differs from actual matches when using long search strings

### ISSUE THREAD

**Issue by 4evermaat** [notepad-plus-plus/notepad-plus-plus#12000]
### Description of the Issue

I'm trying to do a negative lookahead with a lot of search terms.  It is important to exclude all the correct terms to properly filter out the document.

The search result count appears to be correct.  But the actual returned results seem to return incorrect matches along with the correct matches.  

### Steps to Reproduce the Issue

1. Open the eventCalendar with 105163 rows
2. regex search `count` with following string
`(,[A-Z]{3}),(0)(?i)(?!day|Day|holiday|fest|dussehra|lady|deepavali|deewali|zumbi|palmares|immaculate|conception|orthodox|pentecost|christ|new year|lunar|epiphany|maha shivratri|fatherland|carnival|march 1st|movement|samil|holi|saint|isra miraj|hari raya nyepi|ram navami|mahavir jayanti|cinco de mayo|buddha|purnima|easter|early may|cuti bersama|eid al fitr|hari raya puasa|idul|fitr|juha|rama|ramzan|sacrifice|feast|revolution|corpus|christi|midsummer|sacred heart|hari raya haji|eid al adha|sacrifice|feast|assumption|muharram|muharam|uprising|anniversary|victory|liberation|federal fast|maulidur rasul|juneteen|foundation|bush|honor).*?$`
Also do a `Mark` to mark the items.  The count should be the same.
make sure  `wrap around` and `regular expressions` are checked
3.  In Find tab, do a search for `Find All in Current Document`
4.  Copy the results of the Find All into a new document.  Count the rows.  Is it `4543`?  (`4541` + 2 header rows) or more than that?
5. repeat the same regex search again with the new document.   Do you get 4541?  or much higher number?

### Expected Behavior

return 4541 results .  And the actual matches are also 4541
### Actual Behavior

the count appears to be 4541 (sometimes it might be different also, but usually it is 4541).  But the actual matches is a lot more.  15000.  So matches that shouldn't be there are also being included.

### Debug Information

```
Notepad++ v8.4.4   (32-bit)
Build time : Jul 15 2022 - 17:56:38
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Command Line : "C:\Users\4EverMaAT\Documents\TextCrawler_log.txt"
Admin mode : ON
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 10 Enterprise LTSC 2019 (64-bit) 
OS Version : 1809
OS Build : 17763.2565
Current ANSI codepage : 1252
Plugins : 
    mimeTools (2.8)
    NppConverter (4.4)
    NppExport (0.4)
    XMLTools (3.1.1.10)
    _CustomizeToolbar (4.2)

```

Here is all the tools needed, with screenshot proof
I do think the 4541 results are correct.

* The event csv with `105163` rows of data
* screenshot notepad++ showing `4541` matches
![regex-notepad++_search-result-window_4541](https://user-images.githubusercontent.com/830306/183380664-9299ebd9-8509-49ac-93ae-dc46beaadf82.png)
<br />
* results export from notepad++ document search (15000+ rows, false matches)
* results export copied from regex101.com (PCRE2) 4541 matches
* screenshot from emeditor showing 4541 matches.   Match Selection copied to new file confirms 4541 rows.
![regex-emeditor_search-result-4541](https://user-images.githubusercontent.com/830306/183380711-3b0a28a4-fcf7-4ded-b71e-8f0a21e013fa.png)
<br /><br />
* regex search string (see above) <br /><br />
**[Zip file of evidence to reproduce bug]
**[Zip file of evidence to reproduce bug](https://github.com/notepad-plus-plus/notepad-plus-plus/files/9280433/_eventCalendar_105163-rows.zip)**

**Comment by alankilborn** [comment]
The `_event_calendar_notepad++ results_19947-vs-4541.csv` file contains MULTIPLE search runs; that's why it has 19947 lines.

Possibly this _Search results_ right-click context menu helps you?:
![image](https://user-images.githubusercontent.com/77065706/183430108-37377b47-3478-451d-a4c0-402ca7be228c.png)
It will clear out old search results when a search is run.

**Comment by 4evermaat** [comment]
Just did it again and it looks like it increased again.  So perhaps there is some memory leak or some cache is not being cleared out properly before returning the actual matches?

https://user-images.githubusercontent.com/830306/183433135-0b3606a1-7cae-45b4-97dd-fb828e5254ec.mp4

Either way, there is something wrong there.   Let me know if you need some additional debug logging to be done.

**Comment by alankilborn** [comment]
At 1:25 in the video, it appears you have selected text for copying.  Unfortunately, you have selected the data from several old searches as well.  In the file where you paste the search results, do a regular expression search for `^Search` to see how much data from old searches you now have.

**Comment by alankilborn** [comment]
Why did I get a "laugh" here?:

![image](https://user-images.githubusercontent.com/77065706/183436925-60fdeb16-fd56-4ce3-ae97-62f16c0c5431.png)

**Comment by 4evermaat** [comment]
> The `_event_calendar_notepad++ results_19947-vs-4541.csv` file contains MULTIPLE search runs; that's why it has 19947 lines.
> 
> Possibly this _Search results_ right-click context menu helps you?: ![image](https://user-images.githubusercontent.com/77065706/183430108-37377b47-3478-451d-a4c0-402ca7be228c.png) It will clear out old search results when a search is run.

I just saw this just now.  it was unchecked 🙄   But then I checked it and re-ran the search.  **And it still appended to the older searches.**  Looks like older searches are at bottom and newest search is at the top.

While I can appreciate the desire to accumulate searches at times, shouldn't that be in a separate tab (accumulated searches)?  And shouldn't that be in the search options from the main search window....before clicking the search button?
<img width="431" alt="Snag_5755fb9d" src="https://user-images.githubusercontent.com/830306/183439523-9d49b9ef-cefc-455f-95cf-98e0083e3dc0.png">


Not sure why that would be the default action append searches vs show fresh searches each time.  Why would you have that option after the fact, unless they were stored separately and could be easily re-separated with that option?

Good to know though that I am not crazy.  Wasted nearly a day on it though.

**Comment by alankilborn** [comment]
>Looks like older searches are at bottom and newest search is at the top.

Yes, older searches will auto-fold when a new search is run.  And newer results are inserted at the top, as observed.

>I can appreciate the desire to accumulate searches at times, shouldn't that be in a separate tab

Well, this is in the realm of UI subjectiveness (meaning "everyone has their own best idea of how the UI should work").  N++ developers chose folded results as the "accumulation" area.

>And shouldn't that be in the search options from the main search window....before clicking the search button?

N++ developers considered this, but decided it "fit" better in the results context menu (they don't like excessive clutter in the main search UI).

>Not sure why that would be the default action append searches vs show fresh searches each time

N++ for a long time didn't have a way to automatically clear older searches; when the "purge..." option was added, users were used to it NOT autoclearing...so retaining/accumulating old searches was retained as default behavior.

>Why would you have that option after the fact

There really is no "after the fact" with the current wording.  Now if the wording were something like "Show only the most-recent search result", then I would expect toggling it would change what is displayed.  With the "Purge..." wording, the implication is you have to run another search to see the result.  Using the word "purge" has some more N++ history, as the _Mark_ tab of the _Find_ window has long had similar functionality.

-----------------------------------------------------

BTW, I think some better results would have been obtained had you been more careful about what you copied from the _Search results_ window.  Specifically, NOT selecting prior search data before copying.  For future reference:

* `Copy (Ctrl+c)` - this will copy EXACTLY what is selected, including search metadata
* `Copy Selected Line(s)` - this copies on a "tree basis" (example: make even a one-character selection on a `Search "..."` line and invoke this and it will copy the whole tree for only that search, without any search metadata)

More info in the user manual, [HERE](https://npp-user-manual.org/docs/searching/#search-results-window:~:text=if%20the%20user%20makes%20a%20selection%20of%20text%20in%20the%20Search%20results%20window) about this.

-----------------------------------------------------

More from the user manual, [HERE](https://npp-user-manual.org/docs/searching/#search-results-window:~:text=menu%20item%20entitled-,Purge%20for%20every%20search,-is%20present%20in) is some info about purging old results.  Hmm, it is rather a circular reference:  "Purge for every search...running a search will purge old results."  @pryrt Could that be elaborated on a bit more to remove the circle?

-----------------------------------------------------

>then I checked it and re-ran the search. And it still appended to the older searches

>And you must also "clear all" to start over. Just checking purge for every search was not enough.

These are NOT my experiences, with 8.4.4.
Unless you want to explore this aspect further, please CLOSE this issue.

**Comment by 4evermaat** [comment]
> BTW, I think some better results would have been obtained had you been more careful about what you copied from the Search results window. Specifically, NOT selecting prior search data before copying. For future reference:

Hmmm.   at that time when I was copying lines and getting more data than I should, I would only notice that when I pasted into the blank tab.....where I would clearly see more lines.

I was just ctrl + A and ctrl + c  based on the assumption that it was a fresh search results only.  When you explained that the results accumulate and that there is an independent context menu with `purge for every search` check option, **that was the first I knew of it.**

I will give you the tech win in that I did not refer to the manual.  Perhaps I should have.  I stand on my observation that this current default way to append old searches and not show the option in the search dialog box is **not intuitive** way to do it.   You must look at this from a casual user's point of view, particularly someone using a feature like `match all` only a few times a year maybe .  Not a power user who uses the feature in question every 3rd day.  But we can agree to disagree there as [after the fact] you can always argue it is developer's choice anyway.

I am still somewhat of a novice with regex `coding` persay, so I was still thinking the whole extra lines fiasco was due to the regex string.   It was not until I tried search string in different regex program (Regex101.com, TextCrawler, EmEditor) I figured out it was something specific to notepad++.  And hence this bug report to show that I'm getting a lot more lines than I should.

Interestingly enough, in EmEditor I was able to `select all` for the search (and there are separate options to mark all automatically).  Then I could copy just manually the regex match to new tab.   The `Extract` button will take whole row of all matches over to the a tab automatically, with the regex matched part pre-marked.   
<img width="369" alt="Snag_57dd5c1c" src="https://user-images.githubusercontent.com/830306/183470118-5c7b55e4-a4f3-4192-bb61-4e091f6ad9e6.png">

Didn't touch the manual.  No confusion copying anything.  But as you eluded to earlier, different developers do things differently, so I'll leave it at that. 

> These are NOT my experiences, with 8.4.4.
> Unless you want to explore this aspect further, please CLOSE this issue.

Hmmm  It is a bug if the program is not clearing after the `purge for every search`  is finally checked, and then a new search is performed. and that new search still contains stale search results appended.

It is possible that I missed something.   So I might try again in a day or two (unchecking and re-checking the `purge for every search`  Or perhaps another user has some similar issue and will chime in.

**Comment by alankilborn** [comment]
>So I might try again in a day or two (unchecking and re-checking the purge for every search

If it is "might" and "a day or two", please close this issue; you can always open a new one in the future, if needed.

**Comment by 4evermaat** [comment]
fair enough
