### ISSUE TITLE
"Block Uncomment" not working for Python code

### ISSUE THREAD

**Issue by mountaindust** [notepad-plus-plus/notepad-plus-plus#1200]
Windows 10, Notepad++ version 6.8.7.

Issue is reproduced by the following steps:
1. Create a new document, call it something like "temp.py".
2. Type some dummy code, e.g.:
    here = 1
    for ii in range(3):
        here += 1
3. Highlight all or part of this code. Right-click, and choose "Block Comment". (code is now commented)
4. Highlight the commented code and try to use either the context-menu "Block Uncomment" or the equivalent command from the Edit>Comment/Uncomment menu. Nothing happens.

**Comment by AlexEshoo** [comment]
I have this at version 6.9.1 also.

**Comment by abzalov** [comment]
For VBScript it is not worked too (Block Uncomment).

**Comment by sjsy** [comment]
I have the same problem at version 6.9.2.
As a  workaround you can use [column mode editing](https://notepad-plus-plus.org/features/column-mode-editing.html) to delete all # characters.
