### ISSUE TITLE
Warning message for big files not translated

### ISSUE THREAD

**Issue by DevonFrosch** [notepad-plus-plus/notepad-plus-plus#12005]
### Description of the Issue
The warning message appearing when opening a large file (> 2GB) is not translated. The message after clicking No stating that the file could not be found ist translated though.

### Steps to Reproduce the Issue
1. Set language to German
2. Try opening a file bigger than 2 GB
3. Message appears (with german OS, might be the reason Yes and No are translated):

```
---------------------------
Opening huge file warning
---------------------------
Opening a huge file of 2GB+ could take several minutes.
Do you want to open it?
---------------------------
Ja   Nein   
---------------------------
```

### Expected Behavior
Fully translated message header and text.

### Actual Behavior
English header and text, localised buttons Yes and No.

### Debug Information
(stripped some local paths with `<path>`)
```
Notepad++ v8.4.4   (64-bit)
Build time : Jul 15 2022 - 17:54:42
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : "<big file>"
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : <Setting file path>
OS Name : Windows 10 Pro N (64-bit) 
OS Version : 21H2
OS Build : 19044.1826
Current ANSI codepage : 1252
Plugins : 
    ComparePlugin (2.0.2)
    JSMinNPP (1.2202)
    mimeTools (2.8)
    NppConverter (4.4)
    NppExport (0.4)
```

By the way, thanks for the amazing program Notepad++ is (and for the great german translation as well).
If I missed anything feel free to give me a shout.

**Comment by alankilborn** [comment]
This text in the application is all set to handle translation; see [HERE](https://github.com/notepad-plus-plus/notepad-plus-plus/blob/2e66fe000765d7923f731ef8f1e524a27ddc0912/PowerEditor/installer/nativeLang/english.xml#L1292).

And, in fact, german translation is already complete, see [HERE](https://github.com/notepad-plus-plus/notepad-plus-plus/blob/2e66fe000765d7923f731ef8f1e524a27ddc0912/PowerEditor/installer/nativeLang/german.xml#L1299).

Probably you just need to update what Notepad++ is actively using, by reselecting German in the _Localization_ dropdown on _Settings_ (menu) > _Preferences_ > _General_.

If that works, recommend CLOSURE of this item.  If it doesn't recommend tagging this item with the "translation" label.

**Comment by DevonFrosch** [comment]
You're right, reselecting the german locale worked, message box is now translated. Learned something new today :-)

Thanks for the help!

**Comment by alankilborn** [comment]
>Learned something new today

Can you stand to learn more? :-)

MORE INFO:

The way it works is when you select a localization from the dropdown, the language file for the selection is copied to a `nativeLang.xml` file, and then that is used.  But that file is only current to the time of the copy.  So if you later update your Notepad++ and that has new translations in it, only germal.xml gets updated, not nativeLang.xml.

I'm not certain as to WHY it was designed that way.
