### ISSUE TITLE
Plugin rendered wrong since v8.4.3

### ISSUE THREAD

**Issue by ffes** [notepad-plus-plus/notepad-plus-plus#12007]
### Description of the Issue

Since the update in v8.4.3 the feature `Add dark mode support for plugins` was added, But that doesn't work for my NppSnippets plugin in light mode.

### Steps to Reproduce the Issue

1. Install the NppSnippets plugin
2. Make sure you are in light mode
3. Select the "ANSI characters" library from the list (because that has a long list of snippets)
4. Scroll through the list and notice that the list is not rendered as expected.
5. Also notice that the combobox (with the list of libraries) isn't rendered correctly as well.

### Expected Behavior
The rendering should work, just like before v8.4.3.

### Remarks

See https://github.com/ffes/nppsnippets/issues/45 for more details and screenshots.

Note that I could not find any docs that plugin devs need to do anything to support this feature.

**Comment by rdipardo** [comment]
It's been [independently reported][0] that:

> Since Notepad++ 8.4.4 enhanced Dark Mode [*sic*], the plugins’ docked dialogs seem to stop receiving the WM_CTLCOLOREDIT message.

Also, the size of the `NppDarkMode::Colors` structure was enlarged in d65967de (release version 8.4.2). Unannounced ABI changes like that can [affect plugins that don't account for them][1].


[0]: https://community.notepad-plus-plus.org/topic/23018/question-about-the-dark-mode-s-dark-scrollbars-and-toolbars/6
[1]: https://community.notepad-plus-plus.org/topic/23080/impact-analysis-of-generic-darkmode-rendering-of-plugin-dock-panels-from-pr-11711/7

**Comment by ozone10** [comment]
I am currently away, so I cannot investigate it properly.
I can guess that plugin may use `WM_CTLCOLORLISTBOX` message which interfere with Notepad++ generic dark mode implementation.

@ffes 
currently for workaround you can update Notepad++ header files and use flag
https://github.com/notepad-plus-plus/notepad-plus-plus/blob/2e66fe000765d7923f731ef8f1e524a27ddc0912/PowerEditor/src/WinControls/DockingWnd/Docking.h#L39
to disable generic dark mode for plugin.

Or temporarily don't use `WM_CTLCOLORLISTBOX` message until there is workaround/fix for `WM_CTLCOLOR*` messages for Notepad++. There might be other code which might interfere with generic dark mode.

So IMHO I think using `DWS_USEOWNDARKMODE` flag might be easiest solution.

@rdipardo 
Notepad++ currently process almost all `WM_CTLCOLOR*` messages for docking interface. To use plugin own implementation `DWS_USEOWNDARKMODE` flag is needed but this will also disable generic dark mode.

Or subclass main plugin window after it has been subclassed by Notepad++.

**Comment by ffes** [comment]
I have tried both solutions you mentioned, but both doesn't seem to help. Since the problem occurs in the light mode, disabling the dark mode (which is what both suggestions are about) seems unlikely to be the solution.

**Comment by ozone10** [comment]
@ffes 
> I have tried both solutions you mentioned, but both doesn't seem to help. Since the problem occurs in the light mode, disabling the dark mode (which is what both suggestions are about) seems unlikely to be the solution.

generic dark mode also affect light mode as it use subclassing, disabling it will stop subclassing dock interface.

also https://github.com/ffes/nppsnippets/pull/48

**Comment by mattesh** [comment]
I would guess the mentioned change violates WINAPI 
https://learn.microsoft.com/en-us/windows/win32/controls/wm-ctlcolorlistbox
_If an application processes this message, it must return a handle to a brush. The system uses the brush to paint the background of the list box._
`		case WM_CTLCOLORLISTBOX:
		{
			if (NppDarkMode::isEnabled())
			{
				return NppDarkMode::onCtlColorListbox(wParam, lParam);
			}
			break;
		}
`
Found in many places in 8.4.8 version.
