### ISSUE TITLE
Suggestion: Search in All Documents -> show how times there is corresponding results in same line

### ISSUE THREAD

**Issue by Tequiller** [notepad-plus-plus/notepad-plus-plus#12010]
To start, it has been a great step forward by putting in the Search result box only one time a line 👍 

But a little step more forward may be done by telling how many results there are by line.

- For example (sorry for french words, don't exactly know how it's in english version), today we have:

`Rechercher "b" (21 résultats dans 1 documents depuis 1 documents recherchés)`
`  nouveau 1 (21 résultats)`
`	Ligne 1: ababababababababababa`
`	Ligne 2: ababababa`
`	Ligne 3: aba`
`	Ligne 4: ababababababa`

- The update could be:

`Rechercher "b" (21 résultats dans 1 documents depuis 1 documents recherchés)`
`  nouveau 1 (21 résultats)`
`	Ligne 1 (10 résultats): ababababababababababa`
`	Ligne 2 ( 4 résultats): ababababa`
`	Ligne 3 ( 1 résultat ): aba`
`	Ligne 4 ( 6 résultats): ababababababa`

Thanks :)

**Comment by alankilborn** [comment]
I think the repeated use of the word `results` on each line is a terrible waste of screen space.
Maybe with this waste one of my matches is pushed off the screen on the righthand side.

Truly repeating `Line` constantly is awful as well, when something very short like `L` would suffice, but `Line` is not a new feature.

I really think that something like `Line 2 (4)` would suffice.

**Comment by Patriccollu** [comment]
@alankilborn 
> Truly, repeating Line constantly is awful as well, when something very short like L would suffice, but using Line is a long-established way that N++ does it.

In December 2020, the string `Line` was made translatable by https://github.com/notepad-plus-plus/notepad-plus-plus/commit/e3455a0f7e2e8aa2c97d1f7a6d2ddfde2d83f95e:

https://github.com/notepad-plus-plus/notepad-plus-plus/blob/f2c4ecd7e1bfd5d7d5c14c854438c02f2ba0909a/PowerEditor/installer/nativeLang/english.xml#L1552

So if you really want, you can reduce its size to `L`. But you will have to redo your change after every new release installed.

**Comment by alankilborn** [comment]
>So if you really want, you can reduce its size to L. 

Oh, I already did it, long ago...

>But you will have to redo your change after every new release installed.

Not true; why do you think so?

**Comment by alankilborn** [comment]
Oh.  Sorry, but I don't keep such details in mind, so I didn't think about it.  I don't used the installer version (I use the portable).  I like to control what gets updated.

I maintain my own english_customizable.xml, and I look at what changes (additions) have been made when a new english.xml is published; then I add those to my english_customizable.xml file.

**Comment by donho** [comment]
With PR #14520, this feature request is not applicable.
