### ISSUE TITLE
Remember projects and its subfolders' expanding/collapse states

### ISSUE THREAD

**Issue by byzod** [notepad-plus-plus/notepad-plus-plus#12012]
### Description of the Issue

All sub entries of a project in project panel is always collapsed when open npp

It's extreme tedious to click 20+ times to bring the expanding states back with every cold start of npp, when you have a lot of files in project panel

Please make it possible to remember expand/collapse state of a project

### Steps to Reproduce the Issue

1. Create a project with multiple files/folders
2. Click some of them to expand sub entries
3. Close npp and open it again

### Expected Behavior
4. All entries remain the expand state as before you close npp
![2](https://user-images.githubusercontent.com/848607/184483182-196beffd-1824-4827-8a78-e593bf9afb44.png)

### Actual Behavior
4. All entries are collapsed
![1](https://user-images.githubusercontent.com/848607/184483226-1662d01b-8bf8-45dc-90c1-b4a518198511.png)

### Debug Information
Notepad++ v8.4.4   (64-bit)
Build time : Jul 15 2022 - 17:54:42
Path : C:\App\Something\Notepad++\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : ON
Cloud Config : OFF
OS Name : Windows 10 Home China (64-bit) 
OS Version : 21H2
OS Build : 19044.1889
Current ANSI codepage : 936
Plugins : 
    ComparePlugin (2.0.2)
    CSharpRegexTools4Npp (1.1.2)
    EmmetNPP (1.0.2)
    HexEditor (0.9.12)
    JSMinNPP (1.2006)
    mimeTools (2.8)
    NppConverter (4.4)
    NppExport (0.4)
    NppTextViz (0.4.2)
    PythonScript (2)

**Comment by ArkadiuszMichalski** [comment]
Duplicate fo https://github.com/notepad-plus-plus/notepad-plus-plus/issues/8323.
