### ISSUE TITLE
Unable to access file on a drive map to a samba drive

### ISSUE THREAD

**Issue by guillcote** [notepad-plus-plus/notepad-plus-plus#12029]
### Description of the Issue

When I try to open a file on the drive H: (which is map to samba share), I got an error message 

H:\filename cannot be open, : Folder H:\ doesn't exist.

If I use file open, I don't see H: in the list of drive.  I see each H: in all other application and I can open files on this drive with all other application.

### Steps to Reproduce the Issue

1.  Open a file with notepad++

### Expected Behavior

The file open.

### Actual Behavior

I got an error message 

H:\filename cannot be open, : Folder H:\ doesn't exist.

### Debug Information

Notepad++ v8.4.4   (64-bit)
Build time : Jul 15 2022 - 17:54:42
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : "C:\program files bis\inpath\t20.bat"
Admin mode : ON
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 11 (64-bit) 
OS Version : 21H2
OS Build : 22000.856
Current ANSI codepage : 1252
Plugins : 
    mimeTools (2.8)
    NppConverter (4.4)
    NppExport (0.4)

I can open the same file with the network path : \\toledo\gcote\filename, but not H:\filename.  H: is map to \\toledo\gcote

**Comment by guillcote** [comment]
![capture_%m23Y_113023](https://user-images.githubusercontent.com/47930145/186201064-53dd3fee-efbe-46e7-b322-8f28bb633743.png)

**Comment by guillcote** [comment]
![capture_%m23Y_113800](https://user-images.githubusercontent.com/47930145/186201264-9e733122-145f-4a05-99da-59f9faf96773.png)

**Comment by guillcote** [comment]
![capture_%m23Y_113908](https://user-images.githubusercontent.com/47930145/186201473-f1ce6a10-20d2-4b0c-bdd3-02bb8b7b6db3.png) This is the file open of Notepad, you can see the H: that should be in Notepad++ and is not.

**Comment by rdipardo** [comment]
This was resolved in #3847 by letting `notepad++.exe` through the firewall: https://github.com/notepad-plus-plus/notepad-plus-plus/issues/3847#issuecomment-419162654

_FYI, I can't reproduce_

![npp-mapped-net-drive](https://user-images.githubusercontent.com/59004801/186256449-81063b5e-7d30-4d7b-acc8-be76e687e0e8.png)

    Notepad++ v8.4.4   (64-bit)
    Build time : Jul 15 2022 - 17:54:42
    Path : ~\npp_8.4.4\notepad++.exe
    Command Line : 
    Admin mode : OFF
    Local Conf mode : ON
    Cloud Config : OFF
    OS Name : Windows 11 (64-bit) 
    OS Version : 22H2
    OS Build : 22621.382
    Current ANSI codepage : 1252
    Plugins : 
        mimeTools (2.8)
        NppConverter (4.4)
        NppExport (0.4)

Samba version:

    4.13.13-Debian

UNC path :

    \\bunsen\smb

Mapped with:

    net use K: \\bunsen\smb

**Comment by guillcote** [comment]
Thanks for the info rdipardo.

I had installed with choco, I uninstalled with choco and installed again by downloading directly from notepad++ website and running as administrator.  The issue is now gone.

Seem like this is an issue with the choco package, not with Notepad++ itself.  Closing the issue.

**Comment by guillcote** [comment]
This is the comment that I base myself on to say it is a choco package issue : 

https://github.com/notepad-plus-plus/notepad-plus-plus/issues/3847#issuecomment-364809636
