### ISSUE TITLE
Change nomenclature globally: Collapse/Uncollapse --> Fold/Unfold

### ISSUE THREAD

**Issue by alankilborn** [notepad-plus-plus/notepad-plus-plus#12035]
### Description of the Issue

The English UI of Notepad++ uses the wording "Collapse" for the folding of text lines, and "Uncollapse" for the unfolding.  But, this usage is inconsistent, as some places it is actually referred to as "fold".  

Why not move to using "Fold" and "Unfold" everywhere in the UI?

This makes sense for the English UI, hopefully it makes the same sort of sense for other localizations?  And that there is concise equivalents for "fold" and "unfold" in other localizations?

For those that don't know, "folded" text lines are lines 21-22 in this Python code example:

![image](https://user-images.githubusercontent.com/77065706/186448998-a2310197-6d6d-4a71-82fa-8eb1348f9503.png)

Comments based upon nomenclature used in Notepad++ 8.4.4.

Note: This issue has its origins in the comments in this other issue: https://github.com/notepad-plus-plus/notepad-plus-plus/issues/11995

**Comment by alankilborn** [comment]
Current usages:

![image](https://user-images.githubusercontent.com/77065706/186453221-4303e6e7-a594-4d7f-8476-6dbbe687fca7.png)

Suggest the simpler "Fold Margin Style" for this one:
![image](https://user-images.githubusercontent.com/77065706/186453468-78f34af6-f395-47f9-9a97-d26dfcb3edfa.png)

![image](https://user-images.githubusercontent.com/77065706/186453840-b5b279a8-759f-40a1-bcc9-21ffdf37f734.png)

![image](https://user-images.githubusercontent.com/77065706/186454346-29a8b331-0962-4e18-ba94-8ac5b076a205.png)

![image](https://user-images.githubusercontent.com/77065706/186455345-c64b7ba8-b0a1-4715-966e-97a789146f4f.png)

![image](https://user-images.githubusercontent.com/77065706/186455612-3011f3e9-f561-4a1c-8ddc-1b9c96bccbd2.png)

**Comment by Yaron10** [comment]
👍

**Comment by donho** [comment]
@alankilborn 
Could you check PR #12094 please?
Note that there's no change for Folder As Workspace for the following reasons:
1. "Fold all folders" sounds wired to me.
2. It's not the code folding, it's not necessary to unify to the same term.

**Comment by Yaron10** [comment]
@donho,

> "Fold all folders" sounds wired to me.

"Fold/Unfold All"?

"Folder Margin Style" to "Folding Margin Style"?

**Comment by alankilborn** [comment]
@donho said:

> Could you check PR #12094 please?

It looks good except, as @Yaron10 points out, _Folder Margin Style_ was missed.
From an English speaker's standpoint, this is actually the MOST annoying one that is correct.
I suggest my original "Fold Margin Style" (preferred) or Yaron10's "Folding Margin Style" (acceptable).
Thinking deeper about it, "Fold Margin Symbol" might be even better. :-)
