### ISSUE TITLE
Feature request: Hotkey combination for reloading files

### ISSUE THREAD

**Issue by kaniggl** [notepad-plus-plus/notepad-plus-plus#1204]
Hello,

would it be possible to get also a hotkey or hotkey combination for the function: Reload from disc?
I have automatic reloading disabled because i am viewing logfiles very often which change their content frequently in background. But sometimes it would be nice to press a hotkey instead of clicking in the gui if i need to reload them.

best regards

**Comment by dail8859** [comment]
Using the shortcut mapper you can define one yourself. Takes like 5 seconds. :)

**Comment by kaniggl** [comment]
Great! Sorry i did not see this menu entry before. Thank you!
