### ISSUE TITLE
Missing Symbols / non-alt-coded. 

### ISSUE THREAD

**Issue by rkreilly** [notepad-plus-plus/notepad-plus-plus#12043]
So I've been in school for aerospace engineering, and I've been using N++ for many of my notes. But, I've been running into some issues with some of the symbols. 

Greek letters have been somewhat difficult, as several of them (gamma, rho, lambda, omega, psi, zeta, etc) don't have alt-codes, and requires a copy-paste every time. (Also others like nabla/del, partial derivative, not equals.)

Other symbols don't even work - I just get a question mark box. I don't remember all of the ones that do this, but the angle symbol is the recent one, used in polar form: ∠ . Several other detailed math symbols as well. 

So, is there any way to add missing characters like '∠' to N++? 
Also, is there any way to insert a symbol using hex or decimal, instead of alt-codes? That would solve most/all of the greek letters at least.

**Comment by rdipardo** [comment]
There's [a plugin][0] that may help, if you don't mind typing out the code points yourself.

![eng-syms](https://user-images.githubusercontent.com/59004801/186830771-6d9497c0-f39d-4530-8f19-d0c12dba6b8c.gif)

Note that `U+2220: Angle` (and probably others) will not render properly unless you check the option box at `Settings > Preferences > MISC. > "Use DirectWrite . . . "`. With that enabled, operators like `U+2260 Not Equal To` will even appear auto-magically in a ligatured font like [Cascadia Code][1]. (The GIF above shows the non-ligatured Cascadia Mono.)


[0]: https://community.notepad-plus-plus.org/topic/22503/new-version-of-html-tag
[1]: https://github.com/microsoft/cascadia-code/releases

**Comment by alankilborn** [comment]
>So, is there any way to add missing characters like '∠' to N++?

This was a problem nicely solved by the _Character panel_ in Notepad++, in the days when there were only 256 possible characters, of which a bit more than half were not directly typeable via a single key on the keyboard.

Those days are long gone, as we're now in the Unicode era, and there really isn't a great way to have thousands (millions?) of different characters easily imputable at your whim.

One option for you is to just keep an extra file/tab in Notepad++ with your frequently used characters; then it just becomes a fairly quick copy/paste to embed them in another file/tab.  I know you think copy/paste is laborious, but more laborious would be remembering that the angle code point is 2220, omega is ..., gamma is ..., you get the idea...

**Comment by alankilborn** [comment]
>Other symbols don't even work - I just get a question mark box. I don't remember all of the ones that do this, but the angle symbol is the recent one, used in polar form: ∠ . Several other detailed math symbols as well.

This is often solved by turning on the DirectWrite setting:

![image](https://user-images.githubusercontent.com/77065706/186913594-ef626e70-e527-445f-b5fe-45698b341544.png)

or doing that in combination with choosing a different font.

**Comment by alankilborn** [comment]
@rkreilly You can also consider using a script with Notepad++ like the one I show below.  I call the script `InsertUnicodeCharsFromSet.py`.  You would run the script (can be bound to a keycombo) when your caret is positioned where you want to insert a special character.  You'll get a prompt like this, which should then be self-explanatory what to do:

![image](https://user-images.githubusercontent.com/77065706/186967666-2515709d-57bb-4e25-aeb2-e4f6c40c8493.png)

Here's the listing for the script:

```
# -*- coding: utf-8 -*-
from __future__ import print_function

# references:
#  https://github.com/notepad-plus-plus/notepad-plus-plus/issues/12043

from Npp import *
import inspect
import os

#-------------------------------------------------------------------------------

class IUCFS(object):

    def __init__(self):
        self.this_script_name = inspect.getframeinfo(inspect.currentframe()).filename.split(os.sep)[-1].rsplit('.', 1)[0]
        char_dict = {
            'gamma' :  u'\U00000393',
            'rho' :    u'\U000003A1',
            'lambda' : u'\U0000039B',
            'omega' :  u'\U000003A9',
            'psi' :    u'\U000003A8',
            'zeta' :   u'\U00000396',
        }
        prompt_str = ' '.join([' {}={}'.format(i+1, val) for i, val in (enumerate(char_dict.keys()))])
        while True:
            user_input = self.prompt('Enter the number (and only the number) to insert desired character', prompt_str)
            if user_input == None: return  # user cancel
            try:
                user_input = int(user_input)
            except ValueError:
                continue
            if 1 <= user_input <= len(char_dict): break
        k = char_dict.keys()[user_input - 1]
        editor.addText(char_dict[k])

    def prompt(self, prompt_text, default_text=''):
        if '\n' not in prompt_text: prompt_text = '\r\n' + prompt_text
        prompt_text += ':'
        return notepad.prompt(prompt_text, self.this_script_name, default_text)

#-------------------------------------------------------------------------------

if __name__ == '__main__': IUCFS()
```

It should also be reasonably self-explanatory on how you'd modify the script to add more characters of your choosing.

>I've been in school for aerospace engineering

BTW...good for you! 👍 😀

**Comment by rkreilly** [comment]
Well thanks guys, the DirectWrite fixed the main issue with them not displaying at all. I did install the htmltag, and it look like it'll help with the symbols that don't have an alt-code, so I'll have to start writing those U-codes down as I need them. It is extra steps though, wish I could just modify my own alt-code list to add in everything it's missing!

But yup, I've a general notes tab that has the long list of all the symbols, and their related alt-codes (now to include U-code for some). So I'd copy-paste or check it for alts, but I did get several of them memorized from using so much: °, ², ³, √, and a couple of the greek letters :p 

Alan, thanks a bunch! That actually looks like a pretty efficient/quick way to do this, at least for the oft-used characters. I'll definitely  try it out when I get some time to get it figured out!

**Comment by alankilborn** [comment]
@rkreilly Given all that's been said, is there really anything that a code-change to Notepad++ could help with on this? If you don't think so, you (as the initiator) should close this issue, as leaving an issue open indicates that code change work could "fix" it.  If you DO think so, it is probably time to be very specific on what said code changes would be.

**Comment by rkreilly** [comment]
Maybe adding a symbol list (similar to word's but smoother), but no, I just didn;t see the "close issue" button earlier.

**Comment by alankilborn** [comment]
>Maybe adding a symbol list

Well, the problem there is, today Notepad++ adds a symbols list (presumably these math symbols you want), tomorrow someone will want an emoji's list, the next day... and suddenly it becomes adding the entire unicode library of potentially tens/hundreds of thousands of things.  It really isn't practical.

**Comment by rkreilly** [comment]
True, but many of the actual symbols are practical in many different applications. And a lot of them aren't just symbols, but text characters from different languages (mostly Greek). Same as having a Cyrillic or Japanese character set, just added on top of the English one. 

Emoji pictures are practical in... no applications whatsoever :p 

And I suppose Windows always has the charmap you can run if you really need to type something. Or the general websearch/copy/paste.

**Comment by rkj90266** [comment]
@rkreilly you might find this response to my similar query more convenient - you just define some easy-to-remember text codes to be replaced with the characters you want. For example, \alpha inserts greek letter alpha, \angle inserts the angle symbol, etc. You might be aware that th TeX typesetting program defined a lot of characters that way and that the MS Office equation editor now supports them as well (they call it "MathType" I believe). 
https://github.com/notepad-plus-plus/notepad-plus-plus/issues/13856

**Comment by rkreilly** [comment]
Yup, that certainly looks to be an easier way to do this, having a quick type auto-correct is faster than opening a dialog box for sure.
