### ISSUE TITLE
[bug] "Find in Files": Long Filters Get Truncated

### ISSUE THREAD

**Issue by maddes-b** [notepad-plus-plus/notepad-plus-plus#12041]
### Description of the Issue
"Find in Files": When using a long filter, then the list gets truncated and not all patterns are included/excluded.

### Steps to Reproduce the Issue

1.  Use "Find in Files" with following filter `* !+\.svn !+\.git !*.exe !*.com !*.zip !*.gz !*.7z !*.cab !*.deb !*.pkg !*.bmp !*.jpg !*.jpeg !*.png !*.gif !*.ico !*.crt !*.pub !*.pem !*.key !*.csr !*.pdf !*.docx !*.doc !*.odt !*.xlsx !*.xls !*.ods !*.mdb !*.epub !*.drawio !*.swf !*.jar !*.wmv !*.wav !*.mp4 !*.mp3 !*.iso !*.cso !*.vpk !*.cmbackup !*.bin !+\dvb !+\cache2` (324 chars)
2. Execute the search

### Expected Behavior
The filter is untouched and complete

### Actual Behavior
It is cut down to 255chars: `* !+\.svn !+\.git !*.exe !*.com !*.zip !*.gz !*.7z !*.cab !*.deb !*.pkg !*.bmp !*.jpg !*.jpeg !*.png !*.gif !*.ico !*.crt !*.pub !*.pem !*.key !*.csr !*.pdf !*.docx !*.doc !*.odt !*.xlsx !*.xls !*.ods !*.mdb !*.epub !*.drawio !*.swf !*.jar !*.wmv !*.wav !`
Please increase to 1024 (1k).

### Debug Information
Notepad++ v8.4.4   (32-bit)
Build time : Jul 15 2022 - 17:56:38
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Command Line : "D:\Users\private\Documents\Coding\regex.txt"
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 10 Enterprise (64-bit) 
OS Version : 21H2
OS Build : 19044.1889
Current ANSI codepage : 1252
Plugins : 
    ComparePlugin (2.0.2)
    CSVLint (0.4.5.2)
    ElasticTabstops (1.3.1)
    HexEditor (0.9.12)
    JSMinNPP (1.2205)
    mimeTools (2.8)
    NppConverter (4.4)
    NppExport (0.4)
    RegexTrainer (1)
    XMLTools (3.1.1.13)

**Comment by doug1234** [comment]
I don't see any reason for the limit in the code.  I will give fixing this one a shot unless the change is not wanted.

**Comment by maddes-b** [comment]
Thanks for considering.

Maybe defining a constant, so that the text box of the dialog always has the same length as the related variable, just my two cents.

**Comment by donho** [comment]
@maddes-b 
> Actual Behavior
It is cut down to 255chars

Could you provide the detail about how did you observe the filter is cut down to 255 characters?

**Comment by maddes-b** [comment]
@donho
I needed to search through a folder with multiple types of files in multiple subfolders, but I got hits for file types that I excluded. 
To test I did the following:
* created my filter in a text file
* copied the filter from text file into the search window
* checked that filter was complete in the window field and it was
* executed the search and got hits for filtered out file types
* reopened the search window again and the filter was cut down to 255 chars

Details of the filter are described in the initial post.

**Comment by doug1234** [comment]
@donho I was definitely able to see the filter getting cut off in the debugger.  Actually its pretty clear from just looking at the code that there is a limit to the buffer size.
