### ISSUE TITLE
Missing tooltip localization for invalid RegEx in Find dialog

### ISSUE THREAD

**Issue by rddim** [notepad-plus-plus/notepad-plus-plus#12047]
### Description of the Issue

As of version 8.0, there is a tooltip in the status bar of the `Find` dialog that says some smart things when the user enters an invalid regular expression. Unfortunately these messages cannot be translated.

### Steps to Reproduce the Issue

1. Open the `Find` dialog
2. On `Find what:` type `+`, `*`, `?`, `[` or `\` to get different messages
3. Select `Regular expression` radio button
4. Click `Find next` button
5. Hover the little tooltip icon on the status bar after the `Find: Invalid regular expression` message

### Debug Information

Notepad++ v8.4.4   (64-bit)
Build time : Jul 15 2022 - 17:54:42
Path : G:\npp.8.4.4.portable.minimalist.x64\notepad++.exe
Command Line : 
Admin mode : ON
Local Conf mode : ON
Cloud Config : OFF
OS Name : Windows 7 Professional (64-bit) 
OS Build : 7601.0
Current ANSI codepage : 1251
Plugins : none

![npp_regex_err_msg](https://user-images.githubusercontent.com/8998791/187045869-05ceb47a-3a1d-4a90-bde5-03317b79c8c3.png)

**Comment by alankilborn** [comment]
@rddim These texts come from Boost's regex engine; I don't know if they are localizable.  Thus Notepad++ can't do much about it.

**Comment by ArkadiuszMichalski** [comment]
This was discussed earlier https://github.com/notepad-plus-plus/notepad-plus-plus/pull/9566. Showing the original messages in the tooltip directly from the Boost is intentional.

**Comment by alankilborn** [comment]
@ArkadiuszMichalski Probably should just close?
