### ISSUE TITLE
Inform users which plugins have been blocked

### ISSUE THREAD

**Issue by ArkadiuszMichalski** [notepad-plus-plus/notepad-plus-plus#12069]
After updating Notepad++ some plugins may become incompatible with the new version and automatically blocked. It comes from: 
https://github.com/notepad-plus-plus/notepad-plus-plus/commit/a06b4047
https://github.com/notepad-plus-plus/nppPluginList/commit/2137a2c0cd908ca0c615712dd1d6165645cbde29

The problem is that the user does not receive any information about such situation. Blocked plugins are still in the plugins folder and after updating Notepad++ it may not be clear why they are not working (not loading at all). There have been several report related to blocked NppTextFX.

Possible solutions:
- display such information in Plugins Admin, for example by adding a tab "Blocked" beside of tab "Installed". Or show such plugin also in "Installed" tab but blocked (greayed) with some explanation why it was blocked: this can be added in the description box or add third column with additional information (beside of Version). 
This solution will be convenient for standard users because they will instinctively analyze their plugins in the Plugin Admin window.

- display such information also in Debug Info, for example: 
```
Plugins : 
    mimeTools (2.8) (Blocked: incompatibilie)
    NppConverter (4.4)
    NppExport (0.4)
``` 
This solution will be convenient for people that analyzing reported issues.  Directly from the issue we see why some plugin doesn't work.

Other reports:
https://github.com/notepad-plus-plus/notepad-plus-plus/issues/11900
https://github.com/notepad-plus-plus/notepad-plus-plus/issues/12057
https://github.com/notepad-plus-plus/notepad-plus-plus/issues/11932

**Comment by CennoxX** [comment]
It would be better to see this information before updating Notepad++.

**Comment by alankilborn** [comment]
> It would be better to see this information before updating Notepad++.

That is a BIG ask.
