### ISSUE TITLE
File name extension not being added after saving

### ISSUE THREAD

**Issue by eddyh95** [notepad-plus-plus/notepad-plus-plus#12063]
### Description of the Issue
I'm working on some txt files which include a 3-letter language indicator before the extension. 
For example, "test.eng.txt" as in this is the english text file of "test". Before I re-installed Windows 10 this week, I used to be able to type "test.eng" in the File Name save as dialogue, and it automatically adds ".txt" making it a text file, but after re-installing my OS and installing the latest version of Notepad++ v8.4.4, it does not add ".txt" after saving, making it a ".eng" file.

After searching the notepad++ forums, I saw [this article](https://community.notepad-plus-plus.org/topic/19215/faq-desk-automatic-file-extensions) which indicates in which versions these changes were introduced into Notepad++. Apparently I was using **v7.9.1** when it automatically added the ".txt" to the file name. I could stick to that version, but I realized that version 8 introduced Dark Mode, which I'm kind of a sucker for haha.

**This is in v7.9.1:**

https://user-images.githubusercontent.com/38137496/187573894-2296eb77-3f63-45ed-8766-75fc182416c9.mp4

**This is in v8.4.4:**

https://user-images.githubusercontent.com/38137496/187574785-349fc932-a841-4693-8ce8-47fdff2da347.mp4

Apparently in v7.9.1, there was a toggle in Preferences -> MISC. -> "Set Save Dialog file extension filter to .* instead of .txt for Normal Text", when unchecked, it would automatically add ".txt" anyway, and when checked, it doesn't do that, like in v8.4.4. I don't see that option in v8.4.4 to uncheck it.

<img width="636" alt="Capture" src="https://user-images.githubusercontent.com/38137496/187575278-bceed764-2329-46fb-8125-f1dad0c34e78.PNG">
<img width="631" alt="Capture2" src="https://user-images.githubusercontent.com/38137496/187576396-8c625158-3522-4c81-bc60-01e65860df5c.PNG">

### Steps to Reproduce the Issue

1. Save As in Notepad++
2. Add file name with dot and any letters after it, for example "test.eng", with "Save As Type"  set to "Normal Text File (*.txt)"
3. Save

### Expected Behavior
Notepad++ v7.9.1 adding the extension by itself, disregarding the ".eng" as an extension, resulting in file "test.eng.txt"

### Actual Behavior
Notepad++ v8.4.4 not adding .txt which was selected as "Save As Type", resulting in a file "test.eng"

### Debug Information
Notepad++ v8.4.4   (64-bit)
Build time : Jul 15 2022 - 17:54:42
Path : C:\Users\HP\Downloads\Compressed\npp.8.4.4.portable.x64\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : ON
Cloud Config : OFF
OS Name : Windows 10 Pro (64-bit) 
OS Version : 22H2
OS Build : 19045.1889
Current ANSI codepage : 1252
Plugins : 
    mimeTools (2.8)
    NppConverter (4.4)
    NppExport (0.4)

Thank you for your time.

**Comment by alankilborn** [comment]
Anything after the first `.` begins the "extension" part of the filename.
Thus when it sees `.eng` it won't automatically add `.txt`.

This changed (from earlier N++ versions) because so many other users requested changes to this feature.
A wholesale rethinking of how it should work was done.

I don't see the behavior you saw in an earlier version making a return.

**Comment by eddyh95** [comment]
Oh okay, thanks for clarifying. I did notice the "Append extension" button added in later versions, but still in this case it doesn't change anything. I do paste the name when I wanna save every time, and adding ".txt" every time could work. Anyway I'll stick to v7.9.1 with no dark mode.

**Comment by eddyh95** [comment]
> Probably something could be scripted to add `.txt` regardless of previous `.` in the filename; if that is of interest to you, please post again.

Yes, I'd definitely be interested. Unfortunately, I don't have much experience in scripting. Would you be able to help me out?

**Comment by alankilborn** [comment]
Below find a PythonScript called `AddDotTxtToFilename.py`.
To use it, you'd first just save your file as you like, e.g. with filename `test.eng`.
Running the script will change the name on it to `test.eng.txt`.
Obviously, you need to tie running of this script to a single keycombo using _Shortcut Mapper_, otherwise it is just simpler to add the `.txt` manually at original _Save As_ time.

Here's good information on getting scripting going:  https://community.notepad-plus-plus.org/topic/23039/faq-desk-how-to-install-and-run-a-script-in-pythonscript/1

Here's the text of the script:

```
# -*- coding: utf-8 -*-
from __future__ import print_function

# references:
#  https://github.com/notepad-plus-plus/notepad-plus-plus/issues/12063

from Npp import *
import inspect
import os

#-------------------------------------------------------------------------------

class ADTTF(object):

    def __init__(self):
        self.debug = True if 1 else False
        self.this_script_name = inspect.getframeinfo(inspect.currentframe()).filename.split(os.sep)[-1].rsplit('.', 1)[0]
        self.this_script_path_without_ext = inspect.getframeinfo(inspect.currentframe()).filename.rsplit('.', 1)[0]
        current_filename = notepad.getCurrentFilename()
        if not os.path.isfile(current_filename):
            self.mb("Can't append .txt until file is saved onto disk!")
            return
        if current_filename.lower().endswith('.txt'):
            self.mb('Current file already ends with .txt')
            return
        filename_plus_dot_txt = current_filename + '.txt'
        if os.path.isfile(filename_plus_dot_txt):
            self.mb("Can't rename current file to have .txt appended because a file like that already exists!")
            return
        if editor.getModify():
            notepad.save()
        notepad.saveAs(filename_plus_dot_txt)
        if notepad.getCurrentFilename() != filename_plus_dot_txt:
            self.mb('Some problem occurred saving file as "{}"'.format(filename_plus_dot_txt))
            return
        os.remove(current_filename)

    def mb(self, msg, flags=0, title=''):  # a message-box function
        return notepad.messageBox(msg, title if title else self.this_script_name, flags)

#-------------------------------------------------------------------------------

if __name__ == '__main__': ADTTF()
```

**Comment by eddyh95** [comment]
I'll take a look at this. Thanks a lot for the time you took to write this. I appreciate it.
