### ISSUE TITLE
 Search in files....

### ISSUE THREAD

**Issue by jakubeQ1337** [notepad-plus-plus/notepad-plus-plus#12062]
### Description of the Issue
Option "Find in files", also searches for text in image (.png), texture (.txd) and similar files

### Steps to Reproduce the Issue
1. Search --> Find in files
2.  Directory (we must have text files and graphic files, e.g. a package of game files)
3. Find All

### Expected Behavior

Results only in text files

### Actual Behavior
Search results are from all files in the folder

### Debug Information
Notepad++ v8.4.4   (64-bit)
Build time : Jul 15 2022 - 17:54:42
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : "C:\Users\ceco\AppData\Local\Temp\Rar$DIa7364.16463\c.lua"
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 10 Home (64-bit) 
OS Version : 21H2
OS Build : 19044.1889
Current ANSI codepage : 1250
Plugins : 
    mimeTools (2.8)
    NppConverter (4.4)
    NppExport (0.4)

![search](https://user-images.githubusercontent.com/93059493/187570473-efec1eb4-c6f0-4261-913c-eaff25dbcae7.png)
![result](https://user-images.githubusercontent.com/93059493/187570475-3280ae34-dd6f-44dd-8c33-f1168da30ef5.png)

**Comment by alankilborn** [comment]
Use the _Filters_ box to avoid searching in files of your choosing, using the `!` operator there.  See user manual for details.

**Comment by xomx** [comment]
Mouse can be used to invoke tooltip...
![npp-filters-tooltip](https://user-images.githubusercontent.com/13075183/187697262-61814a26-42f0-4910-983e-1f3432eedcae.png)
