### ISSUE TITLE
Highlight intraline differences in diff (or patch) files

### ISSUE THREAD

**Issue by johnferg** [notepad-plus-plus/notepad-plus-plus#1206]
For my code review workflow, Notepad++ is the most convenient tool for viewing git patch files. However, it only highlights new and deleted lines. If it could also highlight the differences within a line, that would make code reviewing significantly more efficient!

NB. There are many file *comparison* tools which have this feature, but that's *not* what I'm looking for. I'm looking for a patch file *viewer* with this feature. The Trac project, for example includes a patch file viewer with this feature (although that's no use to me as it requires attaching each patch file one at a time, which is a massive time killer and thus defeats the point).

**Comment by johnferg** [comment]
Could someone please advise on whether this feature would be better implemented in the core product or as a plugin? Given that highlighting of patch files is currently supported by the core product, I would imagine that it makes more sense to be an additional preference in the core product, but I'd like to confirm this with a Notepad++ veteran before going ahead with it.

**Comment by dail8859** [comment]
The lexer that is used for [diff files](https://github.com/notepad-plus-plus/notepad-plus-plus/blob/master/scintilla/lexers/LexOthers.cxx#L506-L559) comes from the Scintilla project. In general code from Scintilla is just used as-is. So if you needed to make changes to that file then that should be submitted to Scintilla.

However using a plugin would probably be the easiest option for you. You might want to look into using [indicators](http://www.scintilla.org/ScintillaDoc.html#Indicators) to mark parts of the text. This allows the normal Scintilla lexer to highlight the diff file (as it is already doing), and the indicators just lay over top of the styling.

**Comment by johnferg** [comment]
OK, many thanks for the pointer. It sounds like a plugin is the way to go.

**Comment by dail8859** [comment]
No problem. If you have any further questions related to plugin development feel free to post on the [forum](https://notepad-plus-plus.org/community/).
