### ISSUE TITLE
TAB headings too small

### ISSUE THREAD

**Issue by dg3nec** [notepad-plus-plus/notepad-plus-plus#12074]
Version: v84.4.4 (64bit)
I need a larger font because of glasses. I set this in Win10. However, I find that this does not affect the TAB caption in Notepad++. Please allow the TAB caption to change with the system font sizes.

**Comment by alankilborn** [comment]
Do you have the _Reduce_ setting turned on?:

![image](https://user-images.githubusercontent.com/77065706/187920089-aa91d55d-728e-46dc-b0d4-0f2c86bfa0ea.png)

If so, maybe turn it off to obtain:

![image](https://user-images.githubusercontent.com/77065706/187920319-6aed0001-8e0a-49de-9712-af60caf3a03e.png)

**Comment by dg3nec** [comment]
Hello 

yes, you are right. The reduced was on in my settings. Thank's. I can
now better read the tab. That is the solution :-) and case can be
closed. 

Greetinngs 

Am 2022-09-01 15:03, schrieb alankilborn:

> Do you have the _Reduce_ setting turned on?: 
> 
> [1] 
> 
> If so, maybe turn it off to obtain: 
> 
> [2] 
> 
> --
> Reply to this email directly, view it on GitHub [3], or unsubscribe [4].
> You are receiving this because you authored the thread.Message ID: ***@***.***>
 

Links:
------
[1]
https://user-images.githubusercontent.com/77065706/187920089-aa91d55d-728e-46dc-b0d4-0f2c86bfa0ea.png
[2]
https://user-images.githubusercontent.com/77065706/187920319-6aed0001-8e0a-49de-9712-af60caf3a03e.png
[3]
https://github.com/notepad-plus-plus/notepad-plus-plus/issues/12074#issuecomment-1234250595
[4]

**Comment by dg3nec** [comment]
Yes. So your solution was correct.Grüßli, Michael
-------- Ursprüngliche Nachricht --------Von: alankilborn ***@***.***> Datum: 01.09.22  15:07  (GMT+01:00) An: notepad-plus-plus/notepad-plus-plus ***@***.***> Cc: Michael Stahl ***@***.***>, Author ***@***.***> Betreff: Re: [notepad-plus-plus/notepad-plus-plus] TAB headings too small (Issue #12074) 
Do you have the Reduce setting turned on?:

If so, maybe turn it off to obtain:

**Comment by dg3nec** [comment]
I have changed as you pointed. During change the size switch was to see. Thats great. Now its readable.Grüßli, Michael
-------- Ursprüngliche Nachricht --------Von: alankilborn ***@***.***> Datum: 01.09.22  15:07  (GMT+01:00) An: notepad-plus-plus/notepad-plus-plus ***@***.***> Cc: Michael Stahl ***@***.***>, Author ***@***.***> Betreff: Re: [notepad-plus-plus/notepad-plus-plus] TAB headings too small (Issue #12074) 
Do you have the Reduce setting turned on?:

If so, maybe turn it off to obtain:

**Comment by alankilborn** [comment]
@dg3nec If satisfied, please close your issue.
