### ISSUE TITLE
notepadPlus.vs2005.vcproj

### ISSUE THREAD

**Issue by ariccio** [notepad-plus-plus/notepad-plus-plus#121]
Why do we still have `notepadPlus.vs2005.vcproj`?

**Comment by NN---** [comment]
With the removing of vs2005.vcproj please close this issue.

**Comment by ariccio** [comment]
Eh? It's still there?

**Comment by ariccio** [comment]
Oh. Ok. When it's removed, I'll close.

**Comment by ariccio** [comment]
Ummm..... let me know when it is?

**Comment by ariccio** [comment]
Are there any plans to remove it?

**Comment by milipili** [comment]
In the 7.x.

**Comment by ariccio** [comment]
Removed as of 125aee20f7cc169ec314be408b928765f7be4ccf.
