### ISSUE TITLE
Incomplete styler.xml tag can crash Npp

### ISSUE THREAD

**Issue by Ekopalypse** [notepad-plus-plus/notepad-plus-plus#12101]
Incomplete, maybe corrupted, styler (theme) xml can cause Npp to crash.

### Steps to Reproduce the Issue
1. Edit stylers.xml or any theme.xml and add the following line  `<LexerType name="aaa" desc="aaa" ext="" />`
2. Start Npp
3. Chose Settings->Style Configurator
4. Select aaa from the Language combobox

### Expected Behavior
no crash

### Actual Behavior
crash

### Debug Information

I assume this happens with older releases as well but tested with

Notepad++ v8.4.5   (32-bit)
Build time : Sep  3 2022 - 03:56:37
Path : D:\temp\delete\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : ON
Cloud Config : OFF
OS Name : Windows 10 Enterprise (64-bit) 
OS Version : 21H2
OS Build : 19044.1889
Current ANSI codepage : 1252
Plugins : 
    mimeTools (2.8)
    NppConverter (4.4)
    NppExport (0.4)

**Comment by alankilborn** [comment]
I believe @rdipardo pointed out recently that there are a lot of situations where missing or incomplete xml configuration files can cause a crash...

**Comment by rdipardo** [comment]
https://github.com/notepad-plus-plus/notepad-plus-plus/blob/6d36d9d398497a6914c64a5804f0400b8bcd6fbd/PowerEditor/src/Parameters.h#L436-L439

`_styleVect` will be empty when the `LexerType` element defines no children.

Quick fix:

~~~cpp
Style& getStyler(size_t index) {
  Style defaultStyle = {};
  // assert(index < _styleVect.size());
  return (index < _styleVect.size()) ? _styleVect[index] : defaultStyle;
};
~~~
