### ISSUE TITLE
Allow filling in selected word in search and replace dialog via option

### ISSUE THREAD

**Issue by CrHasher** [notepad-plus-plus/notepad-plus-plus#12122]
Sometimes when you search and replace all you want is turn some variable name from lowercase to camelCase, and it would be very nice to have an option here:
![image](https://user-images.githubusercontent.com/834518/189073609-dee760f6-4756-4789-8a69-125777b2b22a.png)
"Fill in replace with field in Replace dialog with selected word"

Hope it gets implemented it would help me a lot.

**Comment by alankilborn** [comment]
>Fill in replace with field in Replace dialog with selected word

That won't get you to camelCase much quicker than:

* place caret on desired word
* invoke _Replace_ via Ctrl+h
* press Ctrl+c
* press Tab
* press Ctrl+v
* make changes to lowercase word to turn it into camelCase word

It works because when Replace is invoked, the word at the caret is put into the _Find what_ box and that box gets input focus and the entire content there is selected.  Ctrl+c copies the selection and Tab moves focus to the _Replace with_ box and selects everything there.  A Ctrl+v paste gets your data duplicated there.

It sounds like a lot when described, but it is really not.

Just a suggestion that is available to you NOW.

------------------------------------------------------------------

Otherwise, IMO your suggestion is not a bad one, although perhaps a better way of doing it might be via an additional button on the _Replace_ window itself, e.g. this button could be moved down:

![image](https://user-images.githubusercontent.com/77065706/189115331-76cae4c9-51d8-4a05-bd2e-2ca7f60a070e.png)

and a second button inserted above it that looks like this (sorry, ASCII art, but it gets the point across?):

```
+-----------------------+
|                       |
|                       |
|           |           |
|           |           |
|           |           |
|           |           |
|           |           |
|        \  |  /        |
|         \ | /         |
|          \|/          |
|           '           |
|                       |
|                       |
+-----------------------+
```

With that button available, when you have data in the _Find what_ box that you want duplicated into the _Replace with_ box, you simply press this new button.

**Comment by CrHasher** [comment]
Button still requires an extra step, instead why not a check box? If selected text gets duplicated when the dialog opens and field gets cleared or left empty when unselected, this way I can leave that checkbox checked and would be applied every time I open the replace dialog or leave the checkbox unchecked for current behavior. Obviously, this would only work if options in the dialog are persisted between sessions which I bet they are.

**Comment by alankilborn** [comment]
@CrHasher 

Either way is viable.  Your method has a speed advantage, my suggestion makes users more aware that the capability exists; users can see a new button (some users are barely aware that _Preferences_ exist).

I'm not certain how common this need is among all users, however, and that is the factor that drives changes to Notepad++.

If your method is adopted, I'd suggest placing it here (_Searching_ prefs have changed in 8.4.5, current version as of this writing):

![image](https://user-images.githubusercontent.com/77065706/189349761-3af6b809-d432-4037-bb6a-aa89905efb98.png)

The obvious implication is that if the Find field is not configured to be auto-filled, the Replace field can't be.

>but it is still very frustrating to do it for 30 vars as an example.

My condolences that you are stuck doing a poor task.  It seems like your skills could be put to better purpose. :-(

**Comment by alankilborn** [comment]
If "Fill Replace Field Same as Find Field" is ticked, wouldn't it make more sense when _Replace_ is invoked, to have input focus on the _Replace with_ box when the window is opened (or is made active) by N++ ?

**Comment by CrHasher** [comment]
I'm fine with any option really if it automagically fills the Replace Field.

**Comment by xomx** [comment]
Hmm, sometimes it could be useful for my purposes.
When I find spare time I try a PR for this.

**Comment by xomx** [comment]
@CrHasher 

You can download & test the PR here:
[32-bit](https://ci.appveyor.com/project/donho/notepad-plus-plus/builds/44810982/job/j5y9h2v8n1yyb0xr/artifacts)
[64-bit](https://ci.appveyor.com/project/donho/notepad-plus-plus/builds/44810982/job/akri66e37chr514g/artifacts)

**Comment by alankilborn** [comment]
The idea behind this feature is to get identical contents into both the _Find what_ and _Replace with_ fields.  Some may think this is ridiculous because using that would result in effectively no replacement.  But the power in this is that you likely need only to tweak the _Replace with_ field slightly to achieve what you need, resulting in less overall effort than copy -> change-control -> paste

**Comment by donho** [comment]
Has such feature been requested before?

**Comment by Mateos81** [comment]
I'd appreciate that feature too

**Comment by alankilborn** [comment]
@CrHasher 

So your request was denied.  Actually it was "suspended" but, pretty much, that is the same as a denial.  I can't be sure, but I think maybe it was talked to death.

If you're willing to use the PythonScript plugin, I have a solution for you to get your desired functionality.

You would replace, in _ShortcutMapper_, the mapping for Ctrl+h, and then tie the running of the following script code to Ctrl+h.  Details on obtaining and setting up PythonScript are found [HERE](https://community.notepad-plus-plus.org/topic/23039/faq-desk-how-to-install-and-run-a-script-in-pythonscript/1).

Here's the script listing for `ReplaceWithAutoFill.py`:

```
# -*- coding: utf-8 -*-
from __future__ import print_function

# references:
#  https://github.com/notepad-plus-plus/notepad-plus-plus/issues/12122
#  https://github.com/notepad-plus-plus/notepad-plus-plus/pull/12195

from Npp import *
import inspect
import os
import sys
from ctypes import (WinDLL, create_unicode_buffer)
from ctypes.wintypes import (HWND, UINT, WPARAM, LPARAM)
LRESULT = LPARAM

python2 = True if sys.version_info.major == 2 else False
user32 = WinDLL('user32')
WM_NEXTDLGCTL = 0x28
SendMessage = user32.SendMessageW
SendMessage.restype = LRESULT
SendMessage.argtypes = [ HWND, UINT, WPARAM, LPARAM ]
IDFINDWHAT = 1601
IDREPLACEWITH = 1602

#-------------------------------------------------------------------------------

class RWAF(object):

    def __init__(self):
        self.debug = True if 0 else False
        notepad.menuCommand(MENUCOMMAND.SEARCH_REPLACE)
        replace_window_hwnd = user32.FindWindowW(None, u'Replace')
        self.print('replace_window_hwnd:', replace_window_hwnd)
        findwhat_edit_hwnd = user32.GetDlgItem(replace_window_hwnd, IDFINDWHAT)
        self.print('findwhat_edit_hwnd:', findwhat_edit_hwnd)
        replwith_edit_hwnd = user32.GetDlgItem(replace_window_hwnd, IDREPLACEWITH)
        self.print('replwith_edit_hwnd:', replwith_edit_hwnd)
        self.set_control_text(replwith_edit_hwnd, self.get_control_text(findwhat_edit_hwnd))
        self.set_dialog_control_focus(replwith_edit_hwnd, replace_window_hwnd)

    def get_control_text(self, hwnd):
        length = user32.GetWindowTextLengthW(hwnd)
        ubuff = create_unicode_buffer(length + 1)
        user32.GetWindowTextW(hwnd, ubuff, length + 1)
        return ubuff.value.encode('utf-8') if python2 else ubuff.value

    def set_control_text(self, hwnd, string):
        if python2 and isinstance(string, str): string = unicode(string, 'utf-8')
        return user32.SetWindowTextW(hwnd, string)

    def set_dialog_control_focus(self, hwnd, dialog_hwnd):
        # see https://devblogs.microsoft.com/oldnewthing/20040804-00/?p=38243
        return True if SendMessage(dialog_hwnd, WM_NEXTDLGCTL, WPARAM(hwnd), LPARAM(True)) == 0 else False

    def print(self, *args):
        if self.debug:
            #console.show()
            print('RWAF:', *args)

#-------------------------------------------------------------------------------

if __name__ == '__main__': RWAF()
```

**Comment by donho** [comment]
> But the power in this is that you likely need only to tweak the Replace with field slightly to achieve what you need, resulting in less overall effort than copy -> change-control -> paste

It could happen - and it has happened to me, not often though.
When user does (or not) need this feature, he/she will leave Find replace dialog and check (or uncheck) the option, then redo Ctrl+H to back to find replace dialog - it's make this feature pointless and useless.
