### ISSUE TITLE
Can't see highlighted selection in Dark Mode

### ISSUE THREAD

**Issue by garberfc** [notepad-plus-plus/notepad-plus-plus#12127]
I love using Dark Mode, but I have a problem. When searching for things, I can't always find / see the highlighted text. 

Is it possible to change the "highlight color"?

**Comment by alankilborn** [comment]
Yours is really a "question", not an "issue".  
Questions properly go [HERE](https://community.notepad-plus-plus.org/) in the future.

-----------------------------------------

The match text is "highlighted" by the search engine using "selection" styling.  That is, it is the same as if you use the mouse to select some text or use shift+arrowkeys to select some text.

So, I think your "problem" is bigger than you think it is. :-)

You can adjust the background of selected text by going to _Settings_ menu > _Style Configurator_ and changing the setup here to improve the contrast to your liking:

![image](https://user-images.githubusercontent.com/77065706/189129883-5e44775d-73c5-40d0-a6dc-951725c869a8.png)

**Comment by garberfc** [comment]
Thanks! You solved my problem
