### ISSUE TITLE
Please prevent misleading adware on your download page

### ISSUE THREAD

**Issue by jgentes** [notepad-plus-plus/notepad-plus-plus#12134]
I understand the need for ad revenue, but contributing to the spread of misleading adware through pages like this shouldn't happen by great software like yours:
![image](https://user-images.githubusercontent.com/1149470/189243347-dbe7af90-e7d3-4cf9-8a35-1e0c8fabbcd2.png)

Could you please do something to prevent this, so people don't accidentally download something other than Notepad++ while thinking they are downloading your software?

**Comment by donho** [comment]
@jgentes 
Please send me the link.
I'll block the url from the domain.

**Comment by donho** [comment]
Just downloaded Tor, identify and block several domains (including Opera browser's official site). All the big green buttons (Download, Start, Next...) ads which could mislead users are blocked manually in the Ads settings. It should be OK for the moment.
However, such advertising will come back. Feel free to let me know (comment in this issue or send me an email with the malicious URL) If you see such ads on Notepad++ download page.
I'll keep an eye on it anyway. Sorry for the inconvenience.

**Comment by jgentes** [comment]
Hmm, it's still there - the links take you to `https://applaunchpro.com/ext/rdel?cid=W81edl9R6X2Xx58&gclid=EAIaIQobChMI06DDgI6I-gIVdM3nAx1zXQQoEAEYASAAEgIe__D_BwE&matchtype=&baexist=&placement=&dclid=CL_ZkIOOiPoCFZKYpwodQiwJ6Q`

Which then prompts the user to download `NotepadPCSetup_39484320.msi` which is not the file listed in your GPG Signature, and no doubt installs the "App Launch Pro" adware.

I'm referring to the giant 1. Click "Start" 2. Download for Free buttons on your download page:
![image](https://user-images.githubusercontent.com/1149470/189396551-3fbd5fa4-7c6a-428b-b210-8a8dd4d2b620.png)

**Comment by donho** [comment]
@jgentes 
Thank you for your link.
I just blocked `https://applaunchpro.com/` and it won't be displayed in 5-10 minutes.
Please let me know if you find any other malicious links

**Comment by alankilborn** [comment]
@donho Still a problem for me (well not exactly a problem because I know what to click on and what to not click on, but still a problem for users):

![image](https://user-images.githubusercontent.com/77065706/190180811-4351ea47-3cbf-46f5-aea0-9a1b93d2678c.png)

**Comment by donho** [comment]
@alankilborn 
As I said, I have not the same Ads as displayed on your country.
So the best way to do is providing me the address of link so I can block their domain names.

**Comment by alankilborn** [comment]
@donho 

https://www.googleadservices.com/pagead/aclk
https://googleads.g.doubleclick.net/pagead/ads

**Comment by donho** [comment]
@alankilborn 
Thank you. But they are not the ads' destination address. You have to wait for a little bit.
BTW, I have blocked some domains. Could you check if it's better now?

**Comment by donho** [comment]
The current issue has been treated in the latest download pages (v8.8.1): 
https://community.notepad-plus-plus.org/topic/26920/fighting-malicious-ads-on-download-pages
