### ISSUE TITLE
Autocomplete contains mispelled words leading to code not working properly

### ISSUE THREAD

**Issue by DermotMW** [notepad-plus-plus/notepad-plus-plus#12130]
### Description of the Issue
I use Notepad++ for many different languages. The autocomplete feature is very good BUT I have had issues where code does not work as expected and it turns out to be a typo from AUTOCOMPLETE.
A good example is when writing CSS if I start typing "grid-template-columns" the first option that appears is actually "grid-template-coliums" and if I don't spot that the grid does not style correctly.

### Steps to Reproduce the Issue
I have no idea how to do this except from the description above.

### Expected Behavior
As above.

### Actual Behavior
As above.

### Debug Information
Notepad++ v8.4.4   (32-bit)
Build time : Jul 15 2022 - 17:56:38
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 10 Home (64-bit) 
OS Version : 21H1
OS Build : 19043.1889
Current ANSI codepage : 1252
Plugins : 
    ComparePlugin (2)
    DSpellCheck (1.4.6)
    mimeTools (2.8)
    NppConverter (4.4)
    NppExec (0.6.2)
    NppExport (0.4)

![image](https://user-images.githubusercontent.com/90055672/189150569-ea888033-f077-49bb-9852-83e203b0e89e.png)
You can see this here - I do not know of any way to get rid of this entry.

I have searched all files but this typo is not in any of them; it is obvious that at some stage I made that typing mistake and Notepad++ saved it but how can I correct autocomplete?

Feel free to email dermot@dermotnolan.ie

**Comment by alankilborn** [comment]
Interestingly, I can't reproduce this.
If I introduce `template-coliumns` by having putting it in my document, it appears in autocomplete choices.
After deleting it from the document, however, it no longer appears as an autocomplete choice.

**Comment by DermotMW** [comment]
For whatever reason I can't get rid of it - note that having searched the CSS file for the text it cannot find it yet it still appears in the autocomplete:

![image](https://user-images.githubusercontent.com/90055672/189164014-3fd82936-058e-4f79-91bd-f98928a145e1.png)

**Comment by DermotMW** [comment]
Hi,

Thie issue was that I had made TWO mistakes - grid-template-coliums AND grid-template-cooliumns; however, having deleted the first the second was still there.

Once I searched again and deleted it, the issue no longer arose.
