### ISSUE TITLE
[Feature request] Option to preserve tabs and white spaces in indents at new lines

### ISSUE THREAD

**Issue by Enjymon** [notepad-plus-plus/notepad-plus-plus#12131]
### Description of the Issue.

[This is more a feature request, but I cannot find where to add the corresponding label in the editing page...]

At a new line, NPP maintains the indent of the previous line by converting as much of the indent into tab characters and completing the indent with white space characters. It would be useful to have the option to maintain the partition of tabs and spaces in the indent of a new line.

Example:
\<TAB\>\<TAB\>\<SPACE\>\<SPACE\>This is an indented line
\<TAB\>\<TAB\>\<SPACE\>\<SPACE\>[] <- cursor position after [ENTER]

My personal use case is that I use NPP as a text editor to write down notes in monospace fonts (useful to align texts such as genetic sequences for instance or to make tables in a plain text documents). It is often that I want to structure my document for better readability as such:

`Title`
`<TAB>Items: - List #1: Long word...<TAB> Other word`
`<TAB>.......- item #2: Short.......<TAB> Whatever`
`<TAB>.......- Item #3: Longest word<TAB> End`
In this example, `.`'s after a `<TAB>` character are there to indicate a track of white space characters.

This way, I use tab characters to shift and align text like for a list or like in a table, and I use white space characters to make the spacing between tabs the same when the actual content might have different lengths.

There are probably other use cases, but that is just my example.

So for example, in the example text above, if one wants to add a 4th item: going at the end of the line of the 3rd item and taping <ENTER> would produce a new line with the following indent:
`<TAB>.......`
(where again `.`'s indicate white space characters)

I know one can ask NPP to convert tabs to spaces, but I fin it difficult/inconvenient to write completely without using tabs. And it seems to me that it would not be very difficult to implement this option.

**Comment by alankilborn** [comment]
>This is more a feature request, but I cannot find where to add the corresponding label in the editing page...

I don't believe there is a way for submitters to do this; what I do is title my issue `[Feature Request] Blah blah blah`

**Comment by alankilborn** [comment]
As this is a core editing feature, it is more of a Scintilla request than a Notepad++ request.  I took a look through the Scintilla configurability of indenting, and I didn't see anything related to this, meaning something simple like an "enable" for such behavior.  That's not to say absolutely that it doesn't exist; it could and I merely missed it, but I have my doubts about that.

**Comment by alankilborn** [comment]
So with scripting, one can intercept the Enter press at end of line and then do special actions.  In this case, we can:

* obtain the exact whitespace from the line (that is now) directly above
* insert the same whitespace at the start of the current line
* leave the typing caret at the end of the inserted whitespace

As I had a script that did something similar previously, I call the following script `AutoIndentReplacement2.py`:

```
# -*- coding: utf-8 -*-
from __future__ import print_function

# references:
#  https://github.com/notepad-plus-plus/notepad-plus-plus/issues/12121 "Option to preserve tabs and white spaces in indents at new lines"

# note that to use this script the setting for "Auto-indent" should be unticked (see Preferences -> Auto-Completion -> Auto-indent)

from Npp import *
import re

#-------------------------------------------------------------------------------

class AIR2(object):

    def __init__(self):
        self.debug = True if 0 else False
        editor.callback(self.charadded_callback, [SCINTILLANOTIFICATION.CHARADDED])

    def charadded_callback(self, args):
        self.print('CHARADDED:', args)
        if args['ch'] == ord('\n'):
            line_above_contents = editor.getLine(editor.lineFromPosition(editor.getCurrentPos()) - 1).rstrip('\r\n')
            m = re.match(r'\s+', line_above_contents)
            if m:
                start_of_line_whitespace = m.group(0)
                curr_pos = editor.getCurrentPos()
                editor.beginUndoAction()
                editor.insertText(curr_pos, start_of_line_whitespace)
                editor.setEmptySelection(curr_pos + len(start_of_line_whitespace))
                editor.chooseCaretX()
                editor.endUndoAction()

    def print(self, *args):
        if self.debug:
            #console.show()
            print('AIR2:', *args)

#-------------------------------------------------------------------------------

# to run via another file, e.g., startup.py, put these lines (uncommented and unindented) in that file:
#  import AutoIndentReplacement2
#  air2 = AutoIndentReplacement2.AIR2()

if __name__ == '__main__':
    try:
        air2
    except NameError:
        air2 = AIR2()
```

Nice instructions for installing the needed components and setting up the script may be found [HERE](https://community.notepad-plus-plus.org/topic/23039/faq-desk-how-to-install-and-run-a-script-in-pythonscript/1).

**Comment by Enjymon** [comment]
@alankilborn 
This seems like a very good solution/work-around! I will try to apply it in the coming days.
Thank you so much for such a fast response!

**Comment by alankilborn** [comment]
@Enjymon You can reopen this if you'd like to someday see the feature in Notepad++ itself.

**Comment by VL4DST3R** [comment]
Came here looking for the same issue as OP, this should really be considered for addition in NP++ by default. If no other way is possible, i guess at least by implementing the above script as-is; within the programs options menu.
