### ISSUE TITLE
ColourPopup's ChooseColor dialog does not handle dark mode

### ISSUE THREAD

**Issue by blu3mania** [notepad-plus-plus/notepad-plus-plus#12148]
In dark mode, bringing up a ChooseColor dialog from any color picker/popup's "More Colours ..." button still displays it in normal mode:
![image](https://user-images.githubusercontent.com/59448289/189553464-60fe115f-c8b8-4d27-b30a-bb66c27003e4.png)

This can be fixed by hooking up lpfnHook in CHOOSECOLOR structure before calling ChooseColor. See https://docs.microsoft.com/en-us/windows/win32/api/commdlg/nc-commdlg-lpcchookproc for details. E.g.:
```
In ColourPopup.cpp:

          // Handle dark mode for ChooseColor dialog
          //cc.Flags = CC_FULLOPEN | CC_RGBINIT;
          cc.lpfnHook = chooseColorDialogProc;
          cc.Flags = CC_FULLOPEN | CC_RGBINIT | CC_ENABLEHOOK;
```

The new chooseColorDialogProc is similar to how other dialogs handle dark mode. The only thing that needs to be paid attention to is that the return type is UINT_PTR instead of INT_PTR:
```
In header:

  static UINT_PTR CALLBACK chooseColorDialogProc(HWND hwnd, UINT message, WPARAM wParam, LPARAM lParam);

In code:

UINT_PTR CALLBACK ColourPopup::chooseColorDialogProc(HWND hwnd, UINT message, WPARAM wParam, LPARAM lParam) 
{
  switch (message) {
    case WM_INITDIALOG: {
      // Handle dark mode
      NppDarkMode::setDarkTitleBar(hwnd);
      NppDarkMode::autoSubclassAndThemeChildControls(hwnd);
      break;
    }

    case WM_CTLCOLOREDIT: {
      if (NppDarkMode::isEnabled()) {
        return NppDarkMode::onCtlColorSofter(reinterpret_cast<HDC>(wParam));
      }
      break;
    }

    case WM_CTLCOLORLISTBOX:
    case WM_CTLCOLORDLG:
    case WM_CTLCOLORSTATIC: {
      if (NppDarkMode::isEnabled()) {
        return NppDarkMode::onCtlColorDarker(reinterpret_cast<HDC>(wParam));
      }
      break;
    }

    case WM_PRINTCLIENT: {
      if (NppDarkMode::isEnabled()) {
        // Do not proceed in dark mode
        return TRUE;
      }
      break;
    }

    case WM_ERASEBKGND: {
      if (NppDarkMode::isEnabled()) {
        RECT clientRect {};
        ::GetClientRect(hwnd, &clientRect);
        ::FillRect(reinterpret_cast<HDC>(wParam), &clientRect, NppDarkMode::getDarkerBackgroundBrush());
        return TRUE;
      }
      break;
    }
  }

  return FALSE;
}
```

The result:
![image](https://user-images.githubusercontent.com/59448289/189553693-b772eb43-d207-46e9-8bc0-99dc597c099e.png)

**Comment by ArkadiuszMichalski** [comment]
@ozone10 It's on your list:
https://github.com/notepad-plus-plus/notepad-plus-plus/issues/10171

**Comment by ozone10** [comment]
@blu3mania 
cool. Can you do PR. Check https://github.com/notepad-plus-plus/notepad-plus-plus/blob/master/CONTRIBUTING.md for coding style and if possible move code (header) to NppDarkMode.cpp  (NppDarkMode.h).

**Comment by blu3mania** [comment]
@ozone10 Sorry but I don't have a local NPP build environment so if I make the changes I would not be able to verify if it builds and runs without issues. The solution was only verified in my plugin (see https://github.com/blu3mania/npp-papyrus/commit/3d9ab37e926f110a58f41b947d1579ebf222b7ef#diff-598801e888495476a824c8ded03bb27c5079911ff9f5679c85545dc3c9a9c612).

As for checking NppDarkMode::isExperimentalSupported() before calling NppDarkMode::setDarkTitleBar(hwnd), I checked other dialogs like FindReplaceDlg, UserDefineDialog, StaticDialog, and they are all calling setDarkTitleBar without checking. I think it works because setDarkTitleBar () essentially calls AllowDarkModeForWindow and RefreshTitleBarThemeColor in DarkMode.cpp. The former checks for g_darkModeSupported, and the latter checks for _IsDarkModeAllowedForWindow && _ShouldAppsUseDarkMode which are required before g_darkModeSupported is set to true.

Anyway, I made the required code changes and attached here (please remove ".txt " extension). You can test them locally and see if it works fine.

[ColourPopup.h.txt](https://github.com/notepad-plus-plus/notepad-plus-plus/files/9548629/ColourPopup.h.txt)
[ColourPopup.cpp.txt](https://github.com/notepad-plus-plus/notepad-plus-plus/files/9548628/ColourPopup.cpp.txt)

**Comment by blu3mania** [comment]
Well, I spend a bit effort to have NPP checked out and VS Code tasks properly set up, and was able to build it with my changes. I will clone the repo and create a PR.
