### ISSUE TITLE
Revamp tab context menu

### ISSUE THREAD

**Issue by donho** [notepad-plus-plus/notepad-plus-plus#12147]
The context menu of Tab is currently too long & too cluttered:

![image](https://user-images.githubusercontent.com/90293/189549934-e8b465bf-11c3-4659-abb9-bac9cfb26a20.png)

It would be better to reorganize it in another way:

```
----------------------
Close                  
Close More           🢒
Save
Save As...
Open into            🢒
Rename
Reload
Move to Recycle Bin
Print
----------------------
Read Only
Clear Read Only Flag
Copy to Clipboard    🢒
Move Document        🢒
Apply Color to Tab   🢒
----------------------
```

**Close More** contains :
 * Close ALL BUT This
 * Close ALL to the Left
 * Close ALL to the Right
 * Close ALL Unchanged
  
**Open** contains:
* Open Containing Folder in Explorer
* Open Containing Folder in Cmd
* Open Containing Folder as Workspace
* Open in Default Viewer

**Copy to Clipboard** contains:
* Copy Full File Path
* Copy Filename
* Copy Current Dir.

**Move Document** contains:
* Move to Other View
* Clone to Other View
* Move to New Instance
* Open in New Instance

**Apply Color to Tab** contains:
* Apply Color 1
* Apply Color 2
* Apply Color 3
* Apply Color 4
* Apply Color 5
* Remove Color

**Comment by chip33** [comment]
I appreciate the tidying up of the tab context menu but I really miss the quick access to “Close all but this” and “Close all to the right”. Both these commands are very commonly used maybe even more than close itself and now I have to navigate to Close multiple tabs , then move across and then down to select my choice.
Before it was an almost subconscious action and now I have to concentrate to do it correctly.

This action of closing tabs I do not need is one of the things I actually interact with most in the top menu of notepad++ so this difference in layout makes usage a lot less efficient compared to a quick swipe down and select.

There has been lots of nice space saved and clutter removed with the new changes to the tab context menu so restoring just the often used commands to the initial context menu for fast and easy access would be a improvement in usability overall.

Thanks for considering this.

**Comment by alankilborn** [comment]
>“Close all but this” and “Close all to the right”. Both these commands are very commonly used maybe even more than close itself 

I would say this is NOT true among the entire sample space of Notepad++ users.

Regardless, I believe a feature to allow total user customization of the tab-context menu is underway, or at least will be begun soon.  See #12170

**Comment by chip33** [comment]
> > “Close all but this” and “Close all to the right”. Both these commands are very commonly used maybe even more than close itself
> 
> I would say this is NOT true among the entire sample space of Notepad++ users.
> 
> Regardless, I believe a feature to allow total user customization of the tab-context menu is underway, or at least will be begun soon. See #12170

Thanks for the reply, customising the tab context menu would be a great solution. I already have a customised main context menu which saves me a lot of movement to the top menu.

I appreciate the use case is different but for example certain browsers which have a lot of data to go on add just "Close", "Close other tabs” and “Close tabs to the right" to the main tab menu.

**Comment by jmvdkolk98** [comment]
This feature should have been postponed until https://github.com/notepad-plus-plus/notepad-plus-plus/issues/12170. All of the options that I use in the options menu are now in sub-menus, causing me to have to open a sub-menu before I can select the option I need. This is not an improvement at all. If there had been keyboard shortcuts, I would have used those, and would not have noticed. But there are no keyboard shortcuts either.

**Comment by alankilborn** [comment]
>But there are no keyboard shortcuts either

So map some for a workaround until 12170 is finished.

**Comment by madscijr** [comment]
> I appreciate the tidying up of the tab context menu but I really miss the quick access ... and now I have to concentrate to do it correctly.

> All of the options that I use in the options menu are now in sub-menus, causing me to have to open a sub-menu before I can select the option I need. 
> 
> So map some (in _Shortcut Mapper_) for a workaround until 12170 is finished.

I had the same problem as the other posters, where I have to do 2 clicks to access functions that used to take 1 click (in this case the "copy to clipboard" functions). 

I tried the workaround of recording a macro and mapping to a keyboard shortcut worked for me:
e.g.
ALT+F = Copy Full File Path
ALT+G = Copy Filename
ALT+P = Copy Current Dir Path

Also, the macro is smart enough that it copies the paths/names for the current tab (and not just the tab I recorded the macro with). 

Thanks for your help.

**Comment by ghahn-IV** [comment]
I also appreciated the expanded nature with all the clutter as it was quicker. I often use 'move to other view' and 'open in file explorer'. I will agree it was a long menu, but I learned where everything was.

Another software that I use handles this by giving me a preference to have it either way. 

I would like to see a check box for this (as I searched for it) in the Preferences under MISC -> Expanded Context Menus. Then everyone can have what they want.

**Comment by alankilborn** [comment]
>I would like to see a check box for this (as I searched for it) in the Preferences under MISC -> Expanded Context Menus. 

You're not going to get this.

>Then everyone can have what they want.

Everyone _can_ have what they want, in 8.4.8 and later.
You just have to customize it yourself.
See the user manual.

**Comment by jmvdkolk98** [comment]
> Everyone _can_ have what they want, in 8.4.8 and later. You just have to customize it yourself. See the user manual.

Thank you very much for providing this option in 8.4.8, and for providing such an amazing template example. I had my most popular commands back in no time once I learned of the change. As you say, everyone can now get that they want!
