### ISSUE TITLE
"Print" toolbar icon shouldn't print immediately

### ISSUE THREAD

**Issue by vlakoff** [notepad-plus-plus/notepad-plus-plus#1215]
Just clicked this icon accidentally and my printer went on fire.

Straightforward to improve, by changing the icon action from "Print Now" to "Print...".
I assume most people would be OK with this change.

Should also save some paper, statistically.

**Comment by cmeriaux** [comment]
+1
A long time ago, I printed accidentally my bash history. More than 40 pages printed for nothing.... 
I happened because I used accidentally the shortcut... 
Bye

**Comment by brandpeter** [comment]
Try the Customize Toolbar plugin; it will allow you to take the icon off the toolbar.

**Comment by vlakoff** [comment]
Thanks for the tip, however I'd like to install as few plugins as possible.

**Comment by dail8859** [comment]
:+1:
