### ISSUE TITLE
Add new feature: Change History Margin

### ISSUE THREAD

**Issue by donho** [notepad-plus-plus/notepad-plus-plus#12164]
It'll be great that there's a margin for change history which marks saved/unsaved modification and undo states, so user can follow the changes of editing document.

Ref: https://github.com/notepad-plus-plus/notepad-plus-plus/pull/12045#issuecomment-1229195785

**Comment by vinsworldcom** [comment]
Just testing out the PR as it's AppVeyor building :

![image](https://user-images.githubusercontent.com/9657169/189944729-807be6eb-6f51-4f0f-87c7-491730184cd0.png)

I had not considered putting the change markers in the existing symbol margin; rather, I put in a new one.  But this doesn't look that bad with the bookmarks in the same margin.

I see currently, the change history is 3 = enabled + markers.  Using inline text indicators would require adding 4 so change history would be 7.  I personally prefer the way it is - inline text indicators is too much for me to process.  But in terms of making this feature user configurable, any thought to the mock up in:

https://github.com/notepad-plus-plus/notepad-plus-plus/issues/12046#issuecomment-1235842820

![image](https://user-images.githubusercontent.com/9657169/188225869-22bd7269-2862-496f-b84d-4ad422e5a978.png)

but with @alankilborn suggestions of naming (or something else like):

- With symbols in margin
- With in-text colouring

**Comment by ImSpecial** [comment]
I tired looking for a way to turn off this"change history" and it looks like my settings menu is missing the options???
 
https://i.imgur.com/ZoOxNSJ.png

Notepad++ v8.4.6   (64-bit)
Build time : Sep 25 2022 - 19:51:39
Path : C:\Programs\Notepad++\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : ON
Cloud Config : OFF
OS Name : Windows 10 Pro (64-bit) 
OS Version : 21H2
OS Build : 19044.2006
Current ANSI codepage : 1252
Plugins : 
    BetterMultiSelection (1.5)
    ComparePlugin (2.0.2)
    DSpellCheck (1.4.24)
    mimeTools (2.8)
    nppConverter (4.4)
    NppExport (0.4)

**Comment by shortthirdman** [comment]
Hey, I have updated to the latest version (`8.4.6`) in Windows but still don't see those settings as shown by @vinsworldcom @donho

**Comment by alankilborn** [comment]
@shortthirdman Some of @vinsworldcom 's showings are experimental additions that aren't in the released version of the feature.

**Comment by shortthirdman** [comment]
When will it be released? Wanted badly to turn off that feature.

**Comment by alankilborn** [comment]
> Wanted badly to turn off that feature.

That's dumb, but your choice.
See [HERE](https://community.notepad-plus-plus.org/topic/23565/how-can-i-turn-off-change-history/).

**Comment by shortthirdman** [comment]
> @shortthirdman Some of @vinsworldcom 's showings are experimental additions that aren't in the released version of the feature.

Ok I got the settings to turn it off. It's available under `Margins/Border/Edge` in `Settings -> Preferences`

**Comment by kgovindan4** [comment]
Hi Team,

I updated my notepad ++ and i lost my data which i keep in that file, Is there any way retrieves that page,

backup also missing in notepad++ folder  

Regards,
G Karthick

**Comment by shortthirdman** [comment]
@kgovindan4 Then its not possible now if you didn't save the file. From next time onwards, do a quick save of the file you are working on in a temporary location.

**Comment by kgovindan4** [comment]
@shortthirdman Thanks for the update
