### ISSUE TITLE
Translation for "Apply Tab Colour" is not working

### ISSUE THREAD

**Issue by yasmise** [notepad-plus-plus/notepad-plus-plus#12163]
### Description of the Issue
Some translations for "Apply Tab Colour" are not working. More specific, following lines are affected:
```
<Item id="44110" name="Remove Tab Colour"/>
<Item id="44111" name="Apply Tab Colour 1"/>
<Item id="44112" name="Apply Tab Colour 2"/>
<Item id="44113" name="Apply Tab Colour 3"/>
<Item id="44114" name="Apply Tab Colour 4"/>
<Item id="44115" name="Apply Tab Colour 5"/>
```

### Steps to Reproduce the Issue
1. Download AppVeyor's build. I used [this one (link)](https://ci.appveyor.com/project/donho/notepad-plus-plus/builds/44756411/job/8e37voc3jpev7d8y/artifacts).
2. Move it to `C:\Program Files\Notepad++`.
3. Open `english.xml` from git repository and change line 665 to something like `<Item id="44110" name="Remove Tab Colour - test"/>`.
4. Save and copy it to `C:\Program Files\Notepad++\localization`
5. Launch `Notepad++.x64.Release.exe` and change language setting to English.

### Expected Behavior
The most bottom item of `View` -> `Tab` should be `Remove Tab Colour - test`.

### Actual Behavior
It says `Remove Color`.
Same thing happens for `Apply Tab Colour 1` to `Apply Tab Colour 5`.
![image](https://user-images.githubusercontent.com/22886576/189896830-83342717-3708-4bea-9a1e-1b8f2afacee0.png)

### Debug Information
Notepad++ v8.4.5   (64-bit)
Build time : Sep 13 2022 - 00:53:58
Path : C:\Program Files\Notepad++\Notepad++.x64.Release.exe
Command Line : 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 11 (64-bit) 
OS Version : 21H2
OS Build : 22000.918
Current ANSI codepage : 932
Plugins : 
    mimeTools (2.5)
    NppConverter (4.2.1)
    NppExport (0.2.9)

**Comment by rddim** [comment]
Confirm

![npp-tab-colors](https://user-images.githubusercontent.com/8998791/190004359-ec0dfdc6-3ecb-4aa0-9764-2604ec2a3145.png)

### Debug Information
Notepad++ v8.4.5   (64-bit)
Build time : Sep 13 2022 - 16:28:42
Path : D:\Install\Office Programs\Notepad++\Notepad++.x64.Release.exe
Command Line : 
Admin mode : ON
Local Conf mode : ON
Cloud Config : D:\Install\Office Programs\Notepad++\_settings
OS Name : Windows 7 Professional (64-bit) 
OS Build : 7601.0
Current ANSI codepage : 1251
Plugins : 
    AutoSave (1.6.1)
    ComparePlus (1)
    TakeNotes (1.2.3)
    VisualStudioLineCopy (1.0.0.2)

**Comment by ArkadiuszMichalski** [comment]
You change wrong entries (for shortcuts), for tab context try:
```
                    <Item CMID="24" name="Apply Color 1"/>
                    <Item CMID="25" name="Apply Color 2"/>
                    <Item CMID="26" name="Apply Color 3"/>
                    <Item CMID="27" name="Apply Color 4"/>
                    <Item CMID="28" name="Apply Color 5"/>
```

**Comment by yasmise** [comment]
@ArkadiuszMichalski Thanks for your reply. I can confirm that translations for tab context menu and shortcuts are working well.
But then, I think translation for `main menu's View` -> `Tab` is missing.

**Comment by ArkadiuszMichalski** [comment]
@donho The next time you modify `english.xml` it's worth adding these missing entries for `main menu's View -> Tab`.

**Comment by donho** [comment]
OUPS!
