### ISSUE TITLE
Add customization for tab context menu

### ISSUE THREAD

**Issue by ArkadiuszMichalski** [notepad-plus-plus/notepad-plus-plus#12170]
Would be nice if we can modify tab context menu in the same way that the main context menu (via an `.xml` file, even using the same `contextMenu.xml` file) or other way.

After merge https://github.com/notepad-plus-plus/notepad-plus-plus/pull/12150 it's possible that not everyone will be happy to move some items to an additional sub-menu. First unhappy report https://github.com/notepad-plus-plus/notepad-plus-plus/pull/12098#issuecomment-1245605230.

Temporary solution:
Now most (if not all) commands from the tab context menu are generally available, so they can be placed in the main context menu (and this menu we can modify as we want via `contextMenu.xml` file).

**Comment by madscijr** [comment]
> 

I would use this feature.

**Comment by latin-programmer** [comment]
Thank you @ArkadiuszMichalski for implementing this. I'm a NotePad++ user and software developer and for me having "Close All BUT This" in a subtab prompted me to downgrade until your fix is out. I use it very often and it saves time to have it accessible directly. I'll upgrade again once your commit is made part of the next release.

**Comment by ArkadiuszMichalski** [comment]
@latin-programmer 
Thanks should go to @donho and people who tested his PR https://github.com/notepad-plus-plus/notepad-plus-plus/pull/12576. I didn't do anything here.

**Comment by alankilborn** [comment]
>having "Close All BUT This" in a subtab prompted me to downgrade 

This is not smart.
If you use it "very often" the smart thing to have done (in order to make it even faster than a right-click top-level choice) would have been to assign it a keycombo.

>until your fix is out

I wouldn't call it a fix.  I'd call it a option.

**Comment by AgostinoSturaro** [comment]
Is this documented somewhere? The `tabContextMenu_example.xml` file, which is in `%APPDADA%\Notepad++` (I couldn't find it at first), says
```
Please check "How to Customize the Context Menu" on:
https://npp-user-manual.org/docs/config-files/#the-context-menu-contextmenu-xml
```
But that's about a different menu, not the one that comes up when right-clicking on a tab.

**Comment by alankilborn** [comment]
@AgostinoSturaro 

>Is this documented somewhere?

It will be in the user manual.  As 8.4.8 supporting this was recently released, the user manual release lags a bit behind.

>But that's about a different menu, not the one that comes up when right-clicking on a tab

The format of the xml file is the same, so the editor right-click context menu instructions can be followed for editing the right-click tab context menu -- the only thing different is the file that is being edited.

**Comment by cmeriaux** [comment]
@AgostinoSturaro @alankilborn  is user manual web site updated now ? it doesn't seems so. Is it an in progress task ?
Cheers

**Comment by alankilborn** [comment]
>is user manual web site updated now ? it doesn't seems so. Is it an in progress task ?

@pryrt (Peter Jones) is your best user-manual contact, as he is the active maintainer.

But, no, as of this moment, user manual changes for v8.4.8, are not released yet.  They usually lag the software release by a little bit of time.  I see constant activity for the user manual sources, so it is "in-progress".

**Comment by pryrt** [comment]
@cmeriaux , the updated user manual has now been released
