### ISSUE TITLE
Small spelling mistake

### ISSUE THREAD

**Issue by martinwalke** [notepad-plus-plus/notepad-plus-plus#1218]
Hi,

I'm using v6.6.9 (I know there are later versions) and have spotted a small spelling mistake which does nothing to detract from this great program and may still exist in the later versions! 

When trying to a file, I was present with the attached message asking "Do I wan to save..." with a missing T.

![npp_error](https://cloud.githubusercontent.com/assets/5419182/11563372/837f4598-99cb-11e5-9859-137023a07e3f.jpg)

**Comment by xylographe** [comment]
Fixed [here](https://github.com/notepad-plus-plus/notepad-plus-plus/blob/master/PowerEditor/src/NppIO.cpp#L769) and [here](https://github.com/notepad-plus-plus/notepad-plus-plus/blob/master/PowerEditor/src/NppIO.cpp#L822) in commit 1d92d189b30c49ed65372635cc2561ad76077894 (12 Nov 2014).
