### ISSUE TITLE
Copycat logo designed on another project relating to editing component of a framework.

### ISSUE THREAD

**Issue by maietta** [notepad-plus-plus/notepad-plus-plus#12187]
![image](https://user-images.githubusercontent.com/11745020/190841071-c52e9e6c-d064-4cae-8c38-bef10bbcdb52.png)

Found in docs for editing component of the PyQt project. Too similar of a logo to Notepad++ project, especially considering the nature of the software it's depicted for.

https://qscintilla.com/#intro

I tried to reach out to the maintainer/creator of Notepad++ (Don Ho?) but email was reject due to "inactivity".

So here I file an issue instead.

**Comment by alankilborn** [comment]
I'm not sure of your reasoning behind creating this "issue".
What would you expect Notepad++ developers to do with this information?

**Comment by mariusft** [comment]
Chameleon vs Frog fight :)

**Comment by maietta** [comment]
It's informational. I'm just wanting the owner of the project to know that this exists, in case it's a legal issue. You can ignore this issue thread.

**Comment by rdipardo** [comment]
> Too similar of a logo to Notepad++ project

If you think that's bad, have you seen the branding of the (totally unaffiliated) [Android app]?

![](https://community.notepad-plus-plus.org/assets/uploads/files/1659407779307-org.sutragroups.notepadplus.png)

This kind of stuff is so common that the developer has already [stopped caring][0] about it.

[0]: https://community.notepad-plus-plus.org/topic/18462/notepad-for-android/14
[Android app]: https://apkpure.com/notepad-editor/org.sutragroups.notepadplus

**Comment by maietta** [comment]
@rdipardo, thanks for chiming on this. I did not see that application or logo. I could easily see why people would be confused into thinking that this application was affiliated with the creator and this project.

This line from the description of the Android app concerns me: "Notepad++ Editor app is a great application that is also installable on PC. The SutraGroups has developed it and, the popularity of Notepad++ Editor software is increasing awesomely. "

There appears to be no effort to make it clear to the visitors that the Android app in question is in no way affiliated with the real Notepad++ project. This in itself is a violation of the developer terms and conditions for publishing of apps.

The current play store policy concerning misrepresentation is as follows:

Misrepresentation
We do not allow apps or developer accounts that:

- impersonate any person or organization, or that misrepresent or conceal their ownership or primary purpose. 
- that engage in coordinated activity to mislead users. This includes, but isn’t limited to, apps or developer accounts that misrepresent or conceal their country of origin and that direct content at users in another country.
- coordinate with other apps, sites, developers, or other accounts to conceal or misrepresent developer or app identity or other material details, where app content relates to politics, social issues or matters of public concern.

Interestingly, though, I couldn't find the app on the official play store.

**Comment by maietta** [comment]
I'm closing this issue for now. I didn't realize there was a community forum, but I will not be joining it to post about this issue.
