### ISSUE TITLE
Document list items under vertical scrollbar when resizing

### ISSUE THREAD

**Issue by ozone10** [notepad-plus-plus/notepad-plus-plus#12191]
### Steps to Reproduce the Issue

1. Have Document List with many items so vertical scrollbar appears
2. Resize Document List or Notepad++ window

### Expected Behavior

Document List will take into account vertical scrollbar when resizing, therefore items won't be under scrollbar

### Actual Behavior

Document List will ignore vertical scrollbar and resize items under it.

### Debug Information

Notepad++ v8.4.5

**Comment by Yaron10** [comment]
@ozone10,

![תמונה](https://user-images.githubusercontent.com/10229320/190916500-b256cc7a-6c2f-4d61-8c00-2eb4896c44fa.png)

After resizing NPP window:

![תמונה](https://user-images.githubusercontent.com/10229320/190916558-c1f0ea02-26b3-409b-bc13-e978847914de.png)

Could you please elaborate? 

Thank you.

**Comment by ozone10** [comment]
@Yaron10 
resize only horizontally so vertical scrollbar remains

**Comment by Yaron10** [comment]
@ozone10,

Could you please attach a screenshot of the problem?

**Comment by ozone10** [comment]
@Yaron10 
currently
![resize](https://user-images.githubusercontent.com/55940305/190917878-9eb87faf-9ef6-489c-93e4-caffb4adf7ec.gif)
PR
![resize2](https://user-images.githubusercontent.com/55940305/190917882-d7a95b9d-b9d3-4540-b1dd-54e1e70c55e2.gif)

notice horizontal scrollbar

resizing with splitter make it easier to notice difference
![image](https://user-images.githubusercontent.com/55940305/190918027-5d4d79ef-5607-46e9-91f7-92464e862f47.png)

**Comment by Yaron10** [comment]
@ozone10,

Thank you. 

I must take a break now. I'll try it later.

**Comment by Yaron10** [comment]
@ozone10,

Very nice!
Thank you for the explanation and the PR. 👍
