### ISSUE TITLE
Session file contains zero files but backup folder contains numerous files

### ISSUE THREAD

**Issue by softwarecraft** [notepad-plus-plus/notepad-plus-plus#12194]
### Description of the Issue
session.xml file is well formed but contains zero file nodes whereas the backup folder contains numerous files.

Session snapshot and periodic backup settings are all enabled:
* Remember current session for next launch
* Enable session snapshot and periodic backup 

Path is local to my laptop, C:\Users\ _myusername_ \AppData\Roaming\Notepad++\backup\ .

This occurs rarely and at random, there are no obvious steps to reproduce it. It occurs after a period of inactivity, eg overnight.

On this occasion it coincided with a pending auto-update.

### Steps to Reproduce the Issue
These are not steps to reproduce, but simply a detailed sequence of what happened on this and prior rare occasions that this happened:
1. Leave Notepad++ open, lock computer, leave overnight
2. Unlock computer, find Notepad++ is no longer open
3. Launch Notepad++
4. Observe no files from prior session are auto opened
5. Observe that auto-update dialog is open in the background (not sure if this happened the other rare occasions of this issue, possibly)
6. Observe that backup folder contains numerous files

### Expected Behavior
Notepad++ should have re-opened files from prior session

### Actual Behavior

Notepad++ launched with no files open, except new empty "file 1"
Notepad++ auto-update dialog was open in background

### Debug Information
Notepad++ v8.4.5   (32-bit)
Build time : Sep  3 2022 - 03:56:37
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Command Line : "C:\Users\johnm\AppData\Roaming\Notepad++\session.xml"
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 10 Home (64-bit) 
OS Version : 22H2
OS Build : 19045.1949
Current ANSI codepage : 1252
Plugins : 
    mimeTools (2.8)
    NppConverter (4.4)
    NppExport (0.4)

I was able to recover my session my manually editing the session.xml file to re-add the missing file nodes for each of the files in the backup folder. I started with a template by creating one new empty file and waiting until it was added to the session.xml file, then duplicating this XML node and changing the filename and backupFilePath attributes accordingly. 

It would be nice to add a feature to Notepad++ to auto rescue a set of backup files by auto rebuilding the session.xml file from that folder's contents.

**Comment by xomx** [comment]
Probably the same as #9850 .

As for the session.xml recovering - there are user scripts to automate that (e.g. [here](https://github.com/notepad-plus-plus/notepad-plus-plus/issues/9850#issuecomment-1249404695), [here](https://community.notepad-plus-plus.org/post/79695)) or [here](https://community.notepad-plus-plus.org/post/79802).

Could you also try [this](https://github.com/notepad-plus-plus/notepad-plus-plus/issues/9850#issuecomment-1261157605)?

**Comment by donho** [comment]
Fix by https://github.com/notepad-plus-plus/notepad-plus-plus/commit/6000f3bb21a42a4d28d068617e0dc642ef739b26
