### ISSUE TITLE
Can't save any file after updating to 8.4.5

### ISSUE THREAD

**Issue by raidenlal** [notepad-plus-plus/notepad-plus-plus#12193]
### Description of the Issue
After giving up of not wanting to update to new version I updated to 8.4.5. After that I can't save any file.

### Steps to Reproduce the Issue
1. Locate file in C:\Folder\file.txt
2. Right click -> from context menu click Edit with Notepad++
3. Change something
4. CTRL+S results in an error message pop-up: [Save failed] Failed to save file. \n It seems there's not enough space on disk to save file.

### Expected Behavior
File to be saved.

### Actual Behavior
Error message, no contents saved. I need to open it with regular Notepad and save it there.

### Debug Information
Notepad++ v8.4.5   (32-bit)
Build time : Sep  3 2022 - 03:56:37
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Command Line : "C:\Folder\file.txt"
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 10 Enterprise (64-bit) 
OS Version : 21H2
OS Build : 19044.2006
Current ANSI codepage : 1252
Plugins : 
    mimeTools (2.8)
    NppConverter (4.4)
    NppExport (0.4)

Any ideas how to fix this?

**Comment by chguw** [comment]
Maybe it was blocked by Microsoft Defender. 
Try to go to (I am using Chinese system and my translation may be different from official ones):
Microsoft Defender - Virus and Threat Protection - "Virus and Threat Protection" Settings (Manage Settings)- Folder Access Protection (Manage Controlled Folder Access) - Allow a certain application through "Folder Restricted Access" 
and add notepda++ as an exception

**Comment by raidenlal** [comment]
My bad. This was due to recently enabled "ransomware protection". Sorry.
