### ISSUE TITLE
Installer won't persist on "dont use %appdata%" selection

### ISSUE THREAD

**Issue by SullyPanda76cl** [notepad-plus-plus/notepad-plus-plus#12202]
### Description of the Issue
The installer, has a setting called "don't use %Appdata%" which is intended, among other uses, for portable instalation.s

An update installation will not honor this previous selection: users who select this option, will need to select it each time. Other wise sill result in a lose of settings.

### Steps to Reproduce the Issue

1.  Install n++, selecting "don't use %appdata%" settings
2.  install an update to n++
3.  "don't use %appdata%" will not be eselected

### Expected Behavior
Expected to honor  "don't use %appdata%" preference

### Actual Behavior
"don't use %appdata%" option is always uncxhecked, on any instalation

### Debug Information
This bug is 10yr old.... God, my procastination took a while to report it!

**Comment by SullyPanda76cl** [comment]
![image](https://user-images.githubusercontent.com/44233071/192400340-e14ba837-96cd-46ba-a9a6-27113c96b244.png)

**Comment by alankilborn** [comment]
>would not it be better if you just directly download a portable N++ instead?

A problem comes in trying to upgrade a portable version; settings can easily be lost by inexperienced users.

**Comment by xomx** [comment]
So here are patched installers for testing (these are not signed):
[32-bit](http://redwoodal.sweb.cz/NotepadPlusPlus/installer_-_remember_do_not_use_APPDATA/npp.8.4.6.Installer.exe)
[64-bit](http://redwoodal.sweb.cz/NotepadPlusPlus/installer_-_remember_do_not_use_APPDATA/npp.8.4.6.Installer.x64.exe)
[64-bit (ARM)](http://redwoodal.sweb.cz/NotepadPlusPlus/installer_-_remember_do_not_use_APPDATA/npp.8.4.6.Installer.arm64.exe)

The change in installer source code logic is not big, but I need to be sure that it also works on other user's PC than mine, before I  create a PR.
