### ISSUE TITLE
Delphi/Object Pascal - folding issue

### ISSUE THREAD

**Issue by azriels** [notepad-plus-plus/notepad-plus-plus#12205]
### Description of the Issue
If I use compiler directives, i.e. {$REGION} {$ENDREGION}, then this directive can be folded, but everything inside is no longer can be folded (except for blocks of comment lines). All the procedures, functions, begin-end, if-then-else, loops - become one block of text without any folding available.

### Expected Behavior
I should be able to fold begin-end, if-then-else, loops, etc. regardless whether they are inside of  {$REGION} {$ENDREGION} or not.

### Actual Behavior
see description of the issue

Screenshot to demo the issue:
![image](https://user-images.githubusercontent.com/28586474/191456745-c9cc189d-8b20-464b-ae01-7e5d258af711.png)

**Comment by vinsworldcom** [comment]
> However, having in mind all this, if you want to enable folding of code blocks
> inside preprocessor blocks, you can disable folding of preprocessor blocks by
> changing "fold.preprocessor" property, in which case everything inside them
> would be folded.

@azriels you can change the `fold.preprocessor` property if you have [NppExec](https://github.com/d0vgan/nppexec) or [PythonScript](https://github.com/bruderstein/PythonScript).:

![image](https://user-images.githubusercontent.com/9657169/191562562-0266ce24-61c6-4f0f-b8df-5aeb0bd17655.png)

[PythonScript](https://github.com/bruderstein/PythonScript):

```
editor.setProperty("fold.preprocessor", 0)
```

[NppExec](https://github.com/d0vgan/nppexec):

```
SCI_SENDMSG SCI_SETPROPERTY "fold.preprocessor" "0"
```

 **Note:**  When using NppExec, the change is not instantaneous - you will need to click back in the Scintilla editing component (i.e., the file edit area) to see it take affect

Cheers.

**Comment by ArkadiuszMichalski** [comment]
More and more need manualy adjustment:

**Comment by azriels** [comment]
Thank you, my issue almost solved.

First of all, I find it very strange that such behavior is by design, but anyway, this is another issue.

I installed PythonScript plugin, wrote and run script

if notepad.getCurrentLang() == LANGTYPE.PASCAL:
    editor.setProperty("fold.preprocessor", 0)

and it works, but I am not sure (forgive my ignorance) where to put the callback you are talking about.

Thanks again for your help.

**Comment by vinsworldcom** [comment]
In your 'startup.py', the script that runs when you start PythonScript:

![image](https://user-images.githubusercontent.com/9657169/191733536-95ba4d38-7943-41ff-a020-93e4a6b85ea7.png)

add the following:

```
from Npp import editor, notepad, NOTIFICATION
def _on_buffer_activated(args):
    if notepad.getCurrentLang() == LANGTYPE.PASCAL:
        editor.setProperty("fold.preprocessor", 0)
notepad.callback(_on_buffer_activated, [NOTIFICATION.BUFFERACTIVATED, NOTIFICATION.LANGCHANGED])

print(f"  File \"{os.path.realpath(__file__)}\", line 1 : PythonScript initialized")
```

The last `print` line isn't really needed, but it will be helpful in quickly navigating to the 'startup.py' by clicking the link it generates in the PythonScript console window.

Cheers.

**Comment by alankilborn** [comment]
@azriels @vinsworldcom 

I don't know that vins's previous post tells all one would need to know about startup.py.
There is some supplementary info [HERE](https://community.notepad-plus-plus.org/topic/23039/faq-desk-how-to-install-and-run-a-script-in-pythonscript/1) if needed (look for `startup` in that).

**Comment by azriels** [comment]
Thank you both of you. 
With the additional info and a little struggle - it works now. Learned a few things about the NotePad++.
