### ISSUE TITLE
[6.8.7] N++ detect PHP Strings as link?

### ISSUE THREAD

**Issue by Commifreak** [notepad-plus-plus/notepad-plus-plus#1221]
With "clickable links" enabled:

![1](https://cloud.githubusercontent.com/assets/87267/11587085/566adff2-9a77-11e5-813d-cf9f20b82778.png)

with disabled clickable links:

![2](https://cloud.githubusercontent.com/assets/87267/11587090/5e6218b0-9a77-11e5-82fd-84ebf77eef42.png)

Why is N++ detecting these 'normal' strings as link?

This seems to be since the few last versions. This issue was not happening all the time. Some changes in link detection?

**Comment by donho** [comment]
This regression should be fixed but not in the release yet.
Could you try this binary and confirm if it is fixed?
[npp.zip](https://github.com/notepad-plus-plus/notepad-plus-plus/files/52055/npp.zip)

**Comment by cyber01** [comment]
In order not to produce several topics, I write here:
After upgrading to 6.8.7 when you open a .php file automatically turns syntax Json, but not PHP. Prior to version 6.8.6 all worked well, after updating to 6.8.6 and then to 6.8.7 - does not work properly

**Comment by cyber01** [comment]
P.S. with binary from link above - work properly

**Comment by donho** [comment]
@cyber01 Thank you for your confirmation.
The fix will be in v6.8.8

**Comment by dail8859** [comment]
Just FYI, related [community post](https://notepad-plus-plus.org/community/topic/10911/styles-messed-up).

**Comment by Commifreak** [comment]
Wow! that was fast! :) - had still no chance to test it, will test it monday. But it seems to work, so: Thanks you! ;)
