### ISSUE TITLE
Flickering screen when last visible line reaches 1000 (in double view)

### ISSUE THREAD

**Issue by niente0** [notepad-plus-plus/notepad-plus-plus#12214]
### Description of the Issue
Sometimes when enabling the "double view" and resizing it, the first view starts flickering, while the second is unusable.
**Please watch attached video**
https://user-images.githubusercontent.com/168951/191752653-b7409550-0663-421d-8784-581d0cec2fdd.mp4

### Steps to Reproduce the Issue

1. open a second window for the same file
2. resize views
3. I think it has to do with line numbers (it switches from 999 to 1000 -> this resizes lines of code -> loop)

### Debug Information
Notepad++ v8.4.4   (64-bit)
Build time : Jul 15 2022 - 17:54:42
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : "C:\inetpub\wwwroot\\-------\www\functions.asp"
Admin mode : ON
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 10 Pro (64-bit) 
OS Version : 21H2
OS Build : 19044.2006
Current ANSI codepage : 1252
Plugins : 
    AutoEolFormat (1.0.2)
    ComparePlugin (2.0.2)
    mimeTools (2.8)
    NppConverter (4.4)
    NppExport (0.4)

**Comment by Yaron10** [comment]
@niente0,

Can you reproduce it if you set "Preferences -> Margins -> Line Number" to "Constant width"?
![תמונה](https://user-images.githubusercontent.com/10229320/191771544-de67edde-34ea-44e1-bbdc-2edda044adbc.png)

BTW, a new and much improved version of ComparePlugin is available.
https://community.notepad-plus-plus.org/topic/23434/new-plugin-compareplus-v1-0-0

**Comment by niente0** [comment]
> 

Thank you very much, your solution worked perfectly! (I think this setting should be set as default)
