### ISSUE TITLE
change the UI font to "Segoe UI" or "Microsoft YaHei UI" ?

### ISSUE THREAD

**Issue by kokutoukiritsugu** [notepad-plus-plus/notepad-plus-plus#12228]
in tchinese or other Asia Region.
the default "MS Shell Dlg" font bad to display on 4k 200% dpi scale.
or make UI font modifiable?

![Snipaste_2022-09-24_19-45-24](https://user-images.githubusercontent.com/5471433/192096287-d55951d2-e282-412c-b855-c05f08946857.png)

**Comment by kokutoukiritsugu** [comment]
#12414

**Comment by donho** [comment]
AFAIK, the font in question is not provided as default font of OS.
