### ISSUE TITLE
8.4.5 color highlighting: XML language definition overrides specializations of XML

### ISSUE THREAD

**Issue by zoidbergthepopularone** [notepad-plus-plus/notepad-plus-plus#12226]
### Description of the Issue

In Notepad v8.4.5, file formats that are based on XML get detected as plain XML instead of their more specialized version. For example, I have a sample file in XHTML format [test.htm.zip](https://github.com/notepad-plus-plus/notepad-plus-plus/files/9638112/test.htm.zip):

```
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<title>Test</title>
</head>

<body>
<p>This is a test.</p>
</body>
</html>
```

This should identify as (X)HTML and should get highlighted as such - and it does, in versions up to 8.4.4. In 8.4.5, though, the file is identified as plain XML and highlighted using the standard XML highlighter. The same happens in other XML-based files, e.g. MSBuild project files, provided that they use the XML header:
```
<?xml version="1.0"?>
```
I suspect it was caused by https://github.com/notepad-plus-plus/notepad-plus-plus/issues/11504 - the description seems to explain what I am seeing.

In my opinion, the new behavior is not correct - a special highlighter should always take precedence over the generic one.

### Steps to Reproduce the Issue
1. Download Notepad++ v8.4.5, portable version and unpack it to any directory.
2. Unpack my sample file above to the same directory.
3. Run `notepad++.exe test.htm`.

### Expected Behavior
The file should get highlighter using the HTML highlighter. The easiest way to check it is, go to the Language menu - `H`->`HTML` should be selected.

### Actual Behavior
The file gets highlighted using the XML highlighter. In the Language menu, `XML` is selected.

**Comment by ArkadiuszMichalski** [comment]
This detector could be made better:
https://github.com/notepad-plus-plus/notepad-plus-plus/blob/6263ce5dece595543bbfaa4207391075ae3a212a/PowerEditor/src/ScintillaComponent/Buffer.cpp#L1372

**Comment by rdipardo** [comment]
> It would be easier if the fact of having an extension also was remembered as a bool for `Buffer` so we can write: `if (!newBuf->_isExt && !newBuf->_isLargeFile && loadedFileFormat._language != L_TEXT)`
>

Or simply make the call to `::detectLanguageFromTextBegining` depend on `filename`, so we skip it for existing files with an extension:

~~~diff
diff --git a/PowerEditor/src/ScintillaComponent/Buffer.cpp b/PowerEditor/src/ScintillaComponent/Buffer.cpp
index 0604b275..3aad5f4a 100644
--- a/PowerEditor/src/ScintillaComponent/Buffer.cpp
+++ b/PowerEditor/src/ScintillaComponent/Buffer.cpp
@@ -1507,9 +1507,9 @@ bool FileManager::loadFileData(Document doc, int64_t fileSize, const TCHAR * fil
 						fileFormat._encoding = detectCodepage(data, lenFile);
                 }
 
-				if (fileFormat._language == L_TEXT)
+				if (wcsrchr(filename, '.') == NULL)
 				{
-					// check the language du fichier
+					// AUCUNE EXTENSION -- check the language du fichier
 					fileFormat._language = detectLanguageFromTextBegining((unsigned char *)data, lenFile);
 				}
 
~~~


Currently `fileFormat._language == L_TEXT` is a known condition &#x2014; it's always true since every file is constructed with the same value:

https://github.com/notepad-plus-plus/notepad-plus-plus/blob/0ce3bc08df1a7de8eff1ec1d70ee3b713224407c/PowerEditor/src/ScintillaComponent/Buffer.h#L109-L111

**Comment by ArkadiuszMichalski** [comment]
@rdipardo I wonder if detecting this only for files without an extension make sense for the following? Who works with such files without an extension?

https://github.com/notepad-plus-plus/notepad-plus-plus/blob/6263ce5dece595543bbfaa4207391075ae3a212a/PowerEditor/src/ScintillaComponent/Buffer.cpp#L1370-L1378

Perhaps it 's enough to provide some additional conditions for extreme cases. Here the detected XML should not be used for HTML (for all its extensions). Maybe there will be more later.

**Comment by rdipardo** [comment]
> Who works with such files without an extension?

Exactly right. The file extension should prevail in 9/10 cases. Auto-detection should only ever be used for scripting languages that support shebang lines. A pattern like `<?xml` is way too inclusive to be useful. But that's another issue.

**Comment by ArkadiuszMichalski** [comment]
But detecting XML prolog (even for file with extension - although not recognized extension ) was added long time ago https://github.com/notepad-plus-plus/notepad-plus-plus/issues/285. If it stops working now, there may be many reports. On the other hand, there should be some kind of `ON/OFF` option for such detection (it's not always useful). 

https://github.com/notepad-plus-plus/notepad-plus-plus/commit/9b91480ecfc5eb392d562ddab1d530bd439d386e#commitcomment-33326608
>Just wondering if anyone has considered making this auto-detection feature optional via Preferences or prefer file extension over detected format by default? There are times where I'd rather have an xml file identified as something else (windows script file with .wsf file extension for example). I can add the .wsf extension to VB or Javascript, but it is overridden by this feature and always switches to xml.

**Comment by rdipardo** [comment]
> But detecting XML prolog (even for file with extension - although not recognized extension) was added long time ago #285. If it stops working now, there may be many reports. 

In fact, there's an even more important (accidental) feature of the current implementation that users will probably miss. Most IDE's store project configuration files in XML format, using a great variety of extensions.

Perhaps `langs.model.xml` could be extended to map the most common project file extensions to `L_XML`, with a catch-all condition just to be safe, e.g.:

~~~cpp
    if (!_tcsrchr(filename, '.')
        || _tcsstr(filename, L".project")   // any *.project file
        || _tcsstr(filename, L"proj"))      // any *proj* file (e.g. *.vcxproj)
    {
       // check the language du fichier
       fileFormat._language = detectLanguageFromTextBegining((unsigned char *)data, lenFile);
    }
~~~

XML Prolog would be harder to work around, unless there's a common extension that can be added to `langs.model.xml`.
