### ISSUE TITLE
Please add support for go language

### ISSUE THREAD

**Issue by weedjy** [notepad-plus-plus/notepad-plus-plus#1222]
Please add support for go language (syntax highlighting for .go files)

**Comment by linquize** [comment]
Golang is quite common nowadays.

**Comment by blinksmith** [comment]
this udl using default color that always come with npp [User Defined Language Files for Go ](https://gist.github.com/blinksmith/99e5234ea601af8ba8bfab35c8fbebef)

**Comment by Cyberdr8gon** [comment]
Was working on this yesterday. This is implemented in the latest version of Scintilla. Will be added as soon as the scintilla library is updated to what is already upstream.

**Comment by MAPJe71** [comment]
Updating the Scintilla library does not automatically result in the languages supported by that library are supported also by Notepad++.

**Comment by Cyberdr8gon** [comment]
You are correct, however I have all of the other data finished to merge when it is updated.

**Comment by MetaChuh** [comment]
please use a go udl

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)
