### ISSUE TITLE
Notepad keeps crashing

### ISSUE THREAD

**Issue by TheodoreCaesar** [notepad-plus-plus/notepad-plus-plus#1223]
So when I updated the latest version, every file I tried to open on it keep crashing the app. Does anyone know why?

**Comment by dail8859** [comment]
Try following [these steps](https://github.com/notepad-plus-plus/notepad-plus-plus/blob/master/CONTRIBUTING.md#reporting-issues).

**Comment by donho** [comment]
@TheodoreCaesar Any feedback after the assistance of @dail8859 ?

**Comment by TheodoreCaesar** [comment]
Yeah I have ◦NppFTP and something called Hunspell. I assume I just delete it, right?

**Comment by donho** [comment]
@TheodoreCaesar please just move the both plugins into another directory, to make sure that Notepad++ doesn't crash anymore. Then move them back one by one.
Please let us know which one is culprit.

**Comment by TheodoreCaesar** [comment]
Oh I've been visiting the AppData files. Sorry I'll come back to you shortly.

**Comment by TheodoreCaesar** [comment]
Notepad doesn't even seem to work even with no plugins enabled.

**Comment by TheodoreCaesar** [comment]
Even with all files removed from Notepad++, and backed up elsewhere, still doesn't make the app work.

**Comment by donho** [comment]
@TheodoreCaesar What is your Notepad++ version?

**Comment by thakyZ** [comment]
I get this issue too and my Notepad++ version is 6.8.7

**Comment by thakyZ** [comment]
So here is all the information you need:
- When double clicking or File>Open a file of any type freezes Notepad++ and then eventually crashes.
- My OS is Windows 10 build 1151
- My Notepad++ version is 6.8.7
- List of installed plugins (even though it doesn't matter)
    - ComparePlugin.dll
    - DSpellCheck2.dll
    - mimeTools.dll
    - NppColumnSort.dll
    - NppConverter.dll
    - NppCrypt.dll
    - NppExport.dll
    - nppplugin_solutionhub.dll
    - nppplugin_solutionhub_ui.dll
    - nppplugin_svn.dll
    - NppSaveAsAdmin.dll
    - ReloadButton.dll
- And again, still happens without any plugins being in the Notepad++ folder (any of them even the configs).

**Comment by TheodoreCaesar** [comment]
thakyZ basically. It all happened when I downloaded the latest version.

**Comment by donho** [comment]
@TheodoreCaesar @thakyZ Thank you for your info.
Could you download zip package:
https://notepad-plus-plus.org/repository/6.x/6.8.7/npp.6.8.7.bin.minimalist.7z
Unzip it in a new created folder, then launch Notepad++. (make sure you quit Notepad++ before).

**Comment by TheodoreCaesar** [comment]
Didn't work for me, sadly. Can't say for anyone else. Thanks for trying, though.

**Comment by thakyZ** [comment]
No but I did find out something, it may have to do with the configs for notepad++ because I tried downgrading and it still crashed so I deleted the configs and it worked. I will post back for what config crashed in particular.

**Comment by thakyZ** [comment]
Wait it worked. So it has to do with the configs but now since I did the minimal package I can't test it. @TheodoreCaesar you should try deleting your configs.

**Comment by TheodoreCaesar** [comment]
I tried that, and it still crashed for me.

**Comment by TheodoreCaesar** [comment]
Which files did you exactly remove? I only removed the config.model file, which was the only one there.

**Comment by TheodoreCaesar** [comment]
It appears that I can only edit the files if I right click on it and click on 'Edit with Notepad++', but unavailable whenever I double left-click.

**Comment by thakyZ** [comment]
no in appdata/roaming/notepad++ or where ever you have (if you have) cloud storage for notepad++

**Comment by TheodoreCaesar** [comment]
Still didn't work for me.

**Comment by TheodoreCaesar** [comment]
According to my computer, there's a runtime error.

**Comment by mohamedahmedabdelfattah** [comment]
same problem since updating to the latest version but deleting DSpellCheck plugin seems to fix it

**Comment by donho** [comment]
@TheodoreCaesar  
What is your OS?

Could you download v6.8.8 here:
https://notepad-plus-plus.org/repository/6.x/6.8.8/npp.6.8.8.bin.minimalist.7z

**Comment by mohamedahmedabdelfattah** [comment]
i`m now on win 10 x64 and v6.8.8, reinstalled the plugin and everything seems ok

**Comment by TheodoreCaesar** [comment]
Windows 10 x64, reinstalled the plugin and it didn't work for me. Maybe my computer is just shit, or... no I'm going with that.

**Comment by mohamedahmedabdelfattah** [comment]
have a try with the portable version: https://notepad-plus-plus.org/repository/6.x/6.8.8/npp.6.8.8.bin.zip

**Comment by donho** [comment]
@TheodoreCaesar So Notepad++ works without plugin, right?

**Comment by donho** [comment]
@TheodoreCaesar it's a plugin issue.
please let us know which plugin causes the crash.
