### ISSUE TITLE
Corrupted files?

### ISSUE THREAD

**Issue by RicardoTadeu** [notepad-plus-plus/notepad-plus-plus#12249]
### Description of the Issue

Hello all,

I've been trying to use Notepad++ to replace texts (actually just one word) in Microsoft Office Word .doc files. When I search the words I want to replace, Notepad++ can find them, but when I click to replace the texts, Notepad++ says they were replaced, the files open , but a dialog box appears saying that the file may be corrupted. Then I can't do anything else, the content of the file doesn't appear anymore.

I hope someone can help me with this issue.

Thanks
Ricardo

### Steps to Reproduce the Issue

1. 
2. 
3.

**Comment by ArkadiuszMichalski** [comment]
Notepad++ is used to edit plain text (TXT) files, not every possible format (like .doc, .xls, .pdf). If you want to edit a specific format, use a program that provides it. Alternatively, you can use the HexEditor plugin and try to change this word directly from Notepad ++, although I don't know if that will work.

You should post such questions on the forum: https://community.notepad-plus-plus.org/.
