### ISSUE TITLE
How to build or get NppShell?

### ISSUE THREAD

**Issue by SuperH-0630** [notepad-plus-plus/notepad-plus-plus#12240]
### Description of the Issue
How to build or get NotepadShell?

### Steps to Reproduce the Issue

1. Download source code.
2. Build in vs2022.
3. Can not get NppShell in bin.

### Expected Behavior
Get NppShell in bin.

### Actual Behavior
Not get NppShell in bin.

**Comment by alankilborn** [comment]
Questions should be asked [HERE](https://community.notepad-plus-plus.org/).
