### ISSUE TITLE
XML auto-detection overrides file extension language selection

### ISSUE THREAD

**Issue by firmwareminion** [notepad-plus-plus/notepad-plus-plus#12253]
### Description of the Issue
I have a consolidated logs file that contain a portion of XML at the beginning, and a large amount of ASCI logs (~80MB) following the XML structure. I use a user defined language to highlight particular data within the log, and I've associated certain extensions so notepad++ will correctly select my user defined language instead of attempting to parse the entire log as XML.  
After the recent update to v8.4.5, my logs no longer are detected using the *.logs extension and defaults to XML as the language.

### Steps to Reproduce the Issue

1.  Create A User Defined Language, using 'logs' as the File extension type for the language, or ADD 'logs' as a user extension for the "dos style" language in the Style Configurator.
2.  Create a file, called 'test.logs', 
3. Add `<?xml version="1.0" encoding="UTF-8"?>` in the first line of the file.
4.  Save 'test.logs' and close the file.
5.  Open the file 'test.logs'. Open the language tab and observe the selected language.

### Expected Behavior
On step 4, it is expected 'test.logs' to be auto-detected as the User defined language.

### Actual Behavior
The file will be opened as the detected XML language.

### Debug Information
Notepad++ v8.4.5   (64-bit)
Build time : Sep  3 2022 - 04:05:32
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : 
Admin mode : ON
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 10 Enterprise (64-bit) 
OS Version : 21H2
OS Build : 19044.1889
Current ANSI codepage : 1252
Plugins : 
    mimeTools (2.8)
    NppConverter (4.4)
    NppExec (0.6)
    NppExport (0.4)

**Comment by firmwareminion** [comment]
Probably duplicate of #12226

**Comment by ArkadiuszMichalski** [comment]
@firmwareminion You can check if this PR https://github.com/notepad-plus-plus/notepad-plus-plus/pull/12236 (build https://ci.appveyor.com/project/donho/notepad-plus-plus/builds/44873889) fix your problem. 

How test PR:
https://github.com/notepad-plus-plus/notepad-plus-plus/wiki/Testing#using-a-pull-request-pr-build-version-of-notepad

**Comment by rdipardo** [comment]
> After the recent update to v8.4.5

@firmwareminion, can you please confirm that an older Notepad++ version did not have this issue? 

It is undocumented behaviour, but in fact the auto-detection function is __*always*__ triggered, for every file opened by Notepad++, and this predates v8.4.5 (see [the table in this comment] for a detailed explanation). This behaviour used to be suppressed by a conditional check, so the auto-detected file type was usually ignored. The check was altered in v8.4.5 to address [a rare edge case][0]. Unfortunately, that gave too much freedom to the undocumented behaviour just described.

[the table in this comment]: https://github.com/notepad-plus-plus/notepad-plus-plus/pull/12236#issuecomment-1258825840

[0]: https://github.com/notepad-plus-plus/notepad-plus-plus/issues/11504

**Comment by firmwareminion** [comment]
@rdipardo, I've reverted to v8.4.4 I no longer experience the issue. On a file open of my files using the .logs extension, the User-defined language is always selected as the language instead of XML.


Debug Info in case:
Notepad++ v8.4.4   (64-bit)
Build time : Jul 15 2022 - 17:54:42
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : "C:\Program Files\Notepad++\change.log" 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 10 Enterprise (64-bit) 
OS Version : 21H2
OS Build : 19044.1889
Current ANSI codepage : 1252
Plugins : 
    mimeTools (2.8)
    NppConverter (4.4)
    NppExec (0.6)
    NppExport (0.4)

**Comment by rdipardo** [comment]
@firmwareminion,
> On a file open of my files using the .logs extension, the User-defined language is always selected as the language instead of XML.

That sounds right.
Thank you.

**Comment by ArkadiuszMichalski** [comment]
@firmwareminion I can't reproduce this also in 8.4.4 (use `logs` ext inside UDL file), I always get XML detected. Are you sure that `mimeTools` does not mix here?
