### ISSUE TITLE
ProgramFiles env var incorrectly set

### ISSUE THREAD

**Issue by aledonati** [notepad-plus-plus/notepad-plus-plus#12255]
### Description of the Issue
On the shell opened by "Open Containing folder in cmd", ProgramFiles and other environment variables are incorrectly set

### Steps to Reproduce the Issue
1. Right click on a file's tab and select "Open Containing folder in cmd"
2. On the resulting cmd window, type SET
3. Some environment variables are incorrectly set

### Expected Behavior
On my PC, Windows 10 64-bit, where C: is the system drive, if I open a cmd window I get this:

CommonProgramFiles=C:\Program Files\Common Files
PROCESSOR_ARCHITECTURE=AMD64
ProgramFiles=C:\Program Files

### Actual Behavior
On the shell opened by Notepad++ I get this:

CommonProgramFiles=C:\Program Files (x86)\Common Files
PROCESSOR_ARCHITECTURE=x86
PROCESSOR_ARCHITEW6432=AMD64
ProgramFiles=C:\Program Files (x86)

### Debug Information
Notepad++ v8.4.5   (32-bit)
Build time : Sep  3 2022 - 03:56:37
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 10 Enterprise (64-bit) 
OS Version : 21H2
OS Build : 19044.2006
Current ANSI codepage : 1252
Plugins : 
    GotoLineCol (1.1)
    HexEditor (0.9.10)
    JSMinNPP (1.2006)
    MarkdownViewerPlusPlus (0.8.2)
    mimeTools (2.8)
    NppConverter (4.4)
    NppExport (0.4)
    NPPJSONViewer (1.34)
    XMLTools (3.1.1.6)

**Comment by rimrul** [comment]
This looks like it is working as Microsoft  intended. Because your `Notepad++` is x86 `Notepad++` on AMD64 Windows, it'll find and launch `C:\Windows\SysWOW64\cmd.exe` when launching `cmd.exe` where all those values are the default.

**Comment by aledonati** [comment]
IMHO the fact Notepad++ is the x86 version is incidental. I would expect "Open Containing folder in cmd", without other specification like "x86 shell" or "x64 shell", to open a shell with whatever settings are the default for my OS, which is 64-bit.

**Comment by ArkadiuszMichalski** [comment]
I use Notepad++ x86 and it launch `C:\Windows\System32\cmd.exe`.  Maybe you have a changed system `PATH` variable?

**Comment by aledonati** [comment]
I think I see the reason for this. ShellExecute is used to start cmd, that will cause cmd to inherit the environment from the calling process, which is Notepad++ x86. There would be a way using CreateProcess not to share the environment, but I totally understand this is overkill. 
I have solved by installing the 64 bit version. Thanks anyways, closing
