### ISSUE TITLE
Reloading a file will mark all lines as changed in change history bar

### ISSUE THREAD

**Issue by crystalcrag** [notepad-plus-plus/notepad-plus-plus#12261]
Title pretty much explain all there is to it.

Stock notepad++ 8.4.6 32bits (if that matter...). No plugins, besides standard ones.

**Comment by rdipardo** [comment]
Scintilla's maintainer is aware, and [posted this to the official mailing list][0]:

> An issue that has appeared with change markers is that SciTE's Revert command leads to the whole document getting a green change mark as revert just reloads each byte of the file. Since its useful to undo to before the revert, this point can't just be set as the start of change history to appear clear.
>
> It may be possible to add a 'revert' state to the change history that could appear clear but its not obvious what the semantics of this state would be.
>
> <https://groups.google.com/g/scintilla-interest/c/9zNAgBG4Pd0/m/C46OGiz_CwAJ>

There's nothing that Notepad++ can do but wait for a future Scintilla release.

[0]: https://groups.google.com/g/scintilla-interest/c/9zNAgBG4Pd0/m/C46OGiz_CwAJ

**Comment by alankilborn** [comment]
A possible workaround: instead of doing a Ctrl+r to _Reload from disk_, do a Ctrl+w (_Close_) followed by a Ctrl+Shift+t (_Restore Recent Closed File_).

And note that this doesn't help the situation where a file is externally modified and Notepad++ prompts to reload it, and you answer Yes to that.  You'd have to follow that up with the workaround above.

**Comment by alankilborn** [comment]
Additional discussion, including more about workarounds, is [HERE](https://community.notepad-plus-plus.org/topic/23544).

**Comment by alankilborn** [comment]
>This feature also affects other plugins negatively

Stating your case in the best way possible would include details on "negatively".
