### ISSUE TITLE
folder can not be delete due is used by another process

### ISSUE THREAD

**Issue by Santjo** [notepad-plus-plus/notepad-plus-plus#12263]
### Description of the Issue
After modifying a xml file and then closing it, the related folder is still locked (it cant't be removed)

### Steps to Reproduce the Issue
1.  open xml file c:\x\y\z\abc.xml
2.  modify abc.xml and save it
3.  close file c:\x\y\z\abc.xml only, but not np++
4. try to delete folder c:\x\y  => windows error:  “The action cannot be completed because the file is open in another program” 
5. exit np++
6.  try to delete folder c:\x\y  => deletion is successfull

The problem occurs ony for xml files.

**Comment by alankilborn** [comment]
Could not reproduce using:

Notepad++ v8.4.6   (64-bit)
Build time : Sep 25 2022 - 19:51:39
Path : C:\\...\npp.8.4.6.portable.x64\notepad++.exe
Command Line : -titleAdd="8.4.6 64-bit" -multiInst
Admin mode : OFF
Local Conf mode : ON
Cloud Config : OFF
OS Name : Windows 10 Enterprise (64-bit) 
OS Version : 21H2
OS Build : 19044.1889
Current ANSI codepage : 1252
Plugins : 
    mimeTools (2.8)
    NppConverter (4.4)
    NppExport (0.4)

**Comment by Santjo** [comment]
The error occurs only with XMLTools plugin!

Notepad++ v8.4.5 (32-bit)
Build time: Sep 3 2022  - 03:56:37
OS Version : 21H2
OS Build: OS Build : 19044.2006
Plugins :
=====
Compare (2.0.1)
JSON Viewer  (1.40)
MarkedownViewer ++ (0.8.2)
MimeTools (2.8)
NppConverter (4.4)
NppExport (0.4)
**XML Tools (3.1.1.10)**
