### ISSUE TITLE
replace algorithm very stupid, this edit replace 100000 line use one day, I use my algorithm only one second.

### ISSUE THREAD

**Issue by epowsal** [notepad-plus-plus/notepad-plus-plus#12266]
replace algorithm very stupid, this editor replace 100000 line use one day, I use my algorithm only one second.

I guess it use too many string concat algorithm.

![2022-10-01_052907](https://user-images.githubusercontent.com/89308109/193358966-8656de4a-22e6-4a05-8816-17e7d0f6341e.png)

**Comment by alankilborn** [comment]
Not much of an issue here; recommend CLOSURE.

**Comment by ArkadiuszMichalski** [comment]
Please open the ticket according to the issue template.
