### ISSUE TITLE
Portuguese mistranslation: "Alternate icones"

### ISSUE THREAD

**Issue by conky77** [notepad-plus-plus/notepad-plus-plus#12269]
### Description of the Issue

Portuguese mistranslation
Settings-->Preferences-->general-->"Alternate icones" is mistranslated "Alternar icones"; the correct translation is "**Ícones alternativos**"

### Debug Information
Notepad++ v8.4.6   (64-bit)
Build time : Sep 25 2022 - 19:51:39
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : "C:\Program Files\Notepad++\change.log" 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 11 (64-bit) 
OS Version : 22H2
OS Build : 22621.521
Current ANSI codepage : 1252
Plugins : 
    ComparePlugin (2.0.2)
    DSpellCheck (1.4.24)
    mimeTools (2.8)
    NppConverter (4.4)
    NppExport (0.4)
    NPPJSONViewer (1.40)
    NppXmlTreeviewPlugin (2)
    XMLTools (3.1.1.13)

![immagine](https://user-images.githubusercontent.com/59116246/193360757-7e28f39b-cfdd-4b4d-8c81-1830b719fea4.png)

**Comment by conky77** [comment]
@hugok79, the label "Alternate Icones" was mistranslated in Italian.xml, and  Portuguese.xml (and Spanish) seems to have the same problem. I wrote you as the official Portuguese translator. Thanks

**Comment by hugok79** [comment]
@conky77 Thanks in advance. I will fix that :)

**Comment by hugok79** [comment]
Fixed
