### ISSUE TITLE
Venetian mistranslation: "Alternate icones"

### ISSUE THREAD

**Issue by conky77** [notepad-plus-plus/notepad-plus-plus#12270]
### Description of the Issue

Venetian mistranslation
Settings-->Preferences-->general-->"Alternate icones" is mistranslated "Alterna icone"; the correct translation is "**Icone alternative**"

### Debug Information
Notepad++ v8.4.6   (64-bit)
Build time : Sep 25 2022 - 19:51:39
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : "C:\Program Files\Notepad++\change.log" 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 11 (64-bit) 
OS Version : 22H2
OS Build : 22621.521
Current ANSI codepage : 1252
Plugins : 
    ComparePlugin (2.0.2)
    DSpellCheck (1.4.24)
    mimeTools (2.8)
    NppConverter (4.4)
    NppExport (0.4)
    NPPJSONViewer (1.40)
    NppXmlTreeviewPlugin (2)
    XMLTools (3.1.1.13)

![immagine](https://user-images.githubusercontent.com/59116246/193363592-4d17cd55-5c90-41b3-8baf-d68d39403b59.png)

**Comment by ArkadiuszMichalski** [comment]
@conky77 

Could you fix this when next time update localization files?

**Comment by conky77** [comment]
@ArkadiuszMichalski  yes, I'm going to fix it when I update it

**Comment by conky77** [comment]
closed with #15491
