### ISSUE TITLE
"Go To" dialog does not update their values when current document is changed

### ISSUE THREAD

**Issue by ErnestLB** [notepad-plus-plus/notepad-plus-plus#12284]
### Description of the Issue
The "Go To" dialog does not update the values of "You are here:" and "You can't go further than:" when current document is changed by clicking in a tab of the other opened document.

### Steps to Reproduce the Issue
1. Open 2 documents in Notepad++ (in the current opened document it should appear 2 tabs)
2. Press Ctrl+G to open the "Go To" dialog, the values that appear in that dialog correspond to the first document (that is OK)
3. Press the second tab, to activate the second document; in the background the content is updated, but the values of the dialog still display the values of the first document.

### Expected Behavior
When you change the current document the values of "You are here:" and "You can't go further than:" must be updated with the values of the current document.

### Actual Behavior
When you change the current document the values of "You are here:" and "You can't go further than:" are displaying the values of the document that opened the dialog

NOTE: the values are properly updated when the dialog is clicked

**Comment by Anklebitter** [comment]
Ok, I've managed to reproduce your error, however, I found that if I click the "Go To" dialog after changing tabs that the content then updates. Can you confirm the same on your end?

**Comment by ErnestLB** [comment]
Yes, same behavior.
When the dialog is "printed" again (by cliking anywhere in the dialog or moving the dialog), the values are recalculated.
But losing or recovering the focus, does not recalculates the values of the dialog with the active document.

**Comment by Anklebitter** [comment]
Just to clarify, is the "Go To" dialogue supposed to update regardless of whether it is in focus or not each time you change tabs?

**Comment by alankilborn** [comment]
>is the "Go To" dialogue supposed to update regardless of whether it is in focus or not each time you change tabs?

That falls into the area of undefined behavior.
Since it is a modeless dialog, it certainly would be nice if it did that.

**Comment by Anklebitter** [comment]
Wouldn't that be part of scintilla then? Since the window selection is responsible for making the "Go To" dialog inactive, and I believe that is handled by scintilla. Also if the "Go To" dialog is inactive it's unable to update/display the new information, essentially it's frozen.

**Comment by alankilborn** [comment]
No, nothing to do with Scintilla.
And, an inactive dialog window can certainly be updated at any time.

**Comment by alankilborn** [comment]
@Anklebitter 

Possibly you could make the [updateLinesNumbers](https://github.com/notepad-plus-plus/notepad-plus-plus/blob/f57c69aac6c1f62fc9240647bcfce11757fa8790/PowerEditor/src/ScintillaComponent/GoToLineDlg.h#L58) function public, and then call that near the bottom of [notifyBufferActivated](https://github.com/notepad-plus-plus/notepad-plus-plus/blob/f57c69aac6c1f62fc9240647bcfce11757fa8790/PowerEditor/src/Notepad_plus.cpp#L6124).

**Comment by Anklebitter** [comment]
Thanks for the info. If I add the same to the bottom of updateStatusBar() it will also update each time a different line is clicked.

**Comment by Anklebitter** [comment]
I'll go ahead and submit a pull request. Thank You!
