### ISSUE TITLE
Older versions of Notepad++ is not able to update automaticlly to v8.4.6

### ISSUE THREAD

**Issue by LeonC510** [notepad-plus-plus/notepad-plus-plus#12288]
### Description of the Issue

Versions of Notepad++ older than the newest version at the time this issue is opened (v8.4.6) are not able to update to the newest version by clicking on the `Update Notepad++` button in the `?` menu located in the menu bar.

### Steps to Reproduce the Issue

1. Open Notepad++ v8.4.5.
2. Click `?` menu in the menu bar.
3. Click `Update Notepad++` in the dropdown menu.

### Expected Behavior

A pop-up window opens, asking for confirmation to update to the newest version (v8.4.6 at the time this issue is opened).

### Actual Behavior

A pop-up window opens, saying `No update is available`, as screenshot below:

![image](https://user-images.githubusercontent.com/112387366/194035196-56743087-0cd0-4b5f-b842-74f3474d2e96.png)

### Debug Information

Notepad++ v8.4.5   (64-bit)
Build time : Sep  3 2022 - 04:05:32
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 10 Home China (64-bit) 
OS Version : 21H2
OS Build : 19044.2006
Current ANSI codepage : 936
Plugins : 
    mimeTools (2.8)
    NppConverter (4.4)
    NppExport (0.4)

**Comment by alankilborn** [comment]
I think the explanation is right there in your screenshot:

![image](https://user-images.githubusercontent.com/77065706/194053322-949d24f5-13d1-43a8-8693-ee79b34bb2af.png)

Perhaps click the `more info` link.

**Comment by ArkadiuszMichalski** [comment]
Auto-update has some delay before will start:
https://npp-user-manual.org/docs/upgrading/#no-new-version-found-safety-delay

**Comment by LeonC510** [comment]
I understand now. Truly sorry for my carelessness!
