### ISSUE TITLE
Strange behavior of the sort feature, with a zero-length column mode selection

### ISSUE THREAD

**Issue by guy038** [notepad-plus-plus/notepad-plus-plus#12299]
### Description of the Issue

In some cases, a **rectangular** selection, **followed** with an **ascending sort**, does **not** sort lines of that **selection** correctly !

### Steps to Reproduce the Issue

- - In a **new** tab, insert the *INPUT* text, below :

~~~diff
    one
    two
    three
    four
    five
    six
    seven
    eight
    nine
    ten
~~~

- Move the caret between the four **leading space** chars and the word **`three`**

- Hit **simustaneously** the **`Alt`** and **`Shift`** keys and, at the **same** time, hit **five** times on the **`Down arrow`** key

=> The indication **`Sel: 6x0`** should appear in the **Status** bar

- Now, hit, for instance, the **`=`** sign

=> A **`=`** sign is inserted in front of the lines **`three`** to **`eight`**

- Select the **`Edit > Line Operations > Sort lines Lexicographically Ascending`**

### Expected Behavior

The **alphabetic** sort should work !

### Actual Behavior

Nothing happens :-((

---

- Now, hit the  **`Left arrow`** key, **once**, to cancel the **rectangular** selection

- Hit **simustaneously** the **`Alt`** and **`Shift`** keys and, at the **same** time, hit **five** times on the **`Down arrow`** key

=> Again, a **rectangular** selection ( **`Sel: 6x0`** ), after the **`=`** sign, is created

- Select, again, the **`Edit > Line Operations > Sort lines Lexicographically Ascending`**

=> This time, the **expected** behavior occurs and we get this *OUTPUT* text :

~~~diff
    one
    two
    =eight
    =five
    =four
    =seven
    =six
    =three
    nine
    ten
~~~

As you can see, the lines of the **selection**, with an **`=`** sign, have been **correctly** sorted, in an **ascending** order !

### Debug Information

~~~diff
Notepad++ v8.4.6   (64-bit)
Build time : Sep 25 2022 - 19:51:39
Path : E:\846_x64\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : ON
Cloud Config : OFF
OS Name : Windows 10 Pro (64-bit) 
OS Version : 21H2
OS Build : 19044.2075
Current ANSI codepage : 1252
Plugins : 
    mimeTools (2.8)
    NppConverter (4.4)
    NppExport (0.4)
    PythonScript (2)
    ComparePlus (1)
    BetterMultiSelection (1.5)
~~~

**IMPORTANT** note :

- Although, the **`BetterMultiSelection`** plugin is present in my **local** configuration, I **disabled** the plugin for the tests above ! And, anyway, the results are similar when the **`BetterMultiSelection`** plugin is **enabled**

---

Refer for **similar** tests in the post :

https://community.notepad-plus-plus.org/post/80310

And some **replies** to my **initial** post, below :

https://community.notepad-plus-plus.org/post/80313

https://community.notepad-plus-plus.org/post/80325

As well as a **possible** solution in :

https://community.notepad-plus-plus.org/post/80336

Best Regards,

guy038

**Comment by alankilborn** [comment]
>As well as a possible solution in : https://community.notepad-plus-plus.org/post/80336

Since `SCI_SELECTIONISRECTANGLE` really can't be relied upon (logically) to always report if a column selection is active -- it clearly fails the case where the user has modified data and ends up with a zero-width rectangle -- probably all uses of SCI_SELECTIONISRECTANGLE in the source code base should be examined for a problem similar to this issue's.

**Comment by ArkadiuszMichalski** [comment]
@alankilborn 

I didn't check everywhere but look only at the status bar. Currently when we make an empty rect selection the status bar show it correct.
![image](https://user-images.githubusercontent.com/2730894/205294484-0c61b5a7-849e-410c-9e1c-ad02a4f65eca.png)
![image](https://user-images.githubusercontent.com/2730894/205293588-785dd348-0ae2-4167-a1ca-ae4f33913d0f.png)

But when we add something status bar presents it as multiselection:
![image](https://user-images.githubusercontent.com/2730894/205293761-e95d325d-0403-4af0-99b9-c03e7d58491f.png)
![image](https://user-images.githubusercontent.com/2730894/205293801-ffb149f5-0235-4667-a1b5-e9372e78fd20.png)

In fact, we're in `SC_SEL_THIN` mode. It fits more to rect or multiselect mode? 

This can be corrected by changing this line as well:
https://github.com/notepad-plus-plus/notepad-plus-plus/blob/aa8ae48b9946d0a26b1e51564246bb1dc981a827/PowerEditor/src/Notepad_plus.cpp#L3878

So after add something we will see on status bar something simillar as on first pic:
![image](https://user-images.githubusercontent.com/2730894/205294920-6698fbb9-3f4e-47ec-92de-fcac4eebf2f0.png)

**Comment by alankilborn** [comment]
@ArkadiuszMichalski 

The idea of "thin" mode is very new to me, I've always thought of a zero-width column selection as "rectangle mode".  I don't see the need for a separate "thin" mode, but Scintilla did so we are stuck processing it.  So my advice (take it or leave it) is that both cases above should show `Sel : 3x0 = 0`.

**Comment by ArkadiuszMichalski** [comment]
I think similar.

In fact, I don't know why empty rec mode is reported as rec (`SCI_SELECTIONISRECTANGLE` is true) not thin. But if we type something it change to thin (`SCI_SELECTIONISRECTANGLE` is false). After all both cases are still empty.

**Comment by alankilborn** [comment]
But what it means is that all areas of the code that the coder previously thought that any possible situation in which some selection made with Alt+Shift+arrows would be indicated as `SCI_SELECTIONISRECTANGLE` = true, now need to be reevaluated.

**Comment by Yaron10** [comment]
>  I don't see the need for a separate "thin" mode

The explanation might be as follows:

Both `SCI_SELECTIONISRECTANGLE` and `SC_SEL_THIN` are column-selection.
In `SCI_SELECTIONISRECTANGLE`, you're in OVR mode.
In `SC_SEL_THIN`, the mode can be either OVR or INS.

The difference may be useful in some cases.

> In fact, I don't know why empty rec mode is reported as rec (SCI_SELECTIONISRECTANGLE is true) not thin. But if we type something it change to thin (SCI_SELECTIONISRECTANGLE is false).

Probably a bug. :)

**Comment by alankilborn** [comment]
>OVR / INS

Interesting observation!

--------------------------------------------------------

>> I don't know why empty rec mode is reported as rec (SCI_SELECTIONISRECTANGLE is true) not thin. But if we type something it change to thin (SCI_SELECTIONISRECTANGLE is false).

>Probably a bug. :)

The Scintilla docs seem to make it clear that it is "by design"; I don't see much use for it, but maybe there is something useful about it with overwrite vs. insert modes...

**Comment by Yaron10** [comment]
> The Scintilla docs seem to make it clear that it is "by design";

All I see is:
"SC_SEL_THIN is the mode after a rectangular selection has been typed into and ensures that no characters are selected."

But if the initial column-selection was "thin/empty", why should `SCI_SELECTIONISRECTANGLE` be true?

**Comment by alankilborn** [comment]
>But if the initial column-selection was "thin/empty", why should SCI_SELECTIONISRECTANGLE be true?

I suppose the answer is "because it is designed that way". :-)
I really feel this is totally intentional, and not a bug.
But it would be great to hear what Neil has to say if you want to open a bug report on the Scintilla site.

The initial column-selection can't be "thin".  It _can_ be "empty", and then it is a zero-width rectangle.
But apparently "thin" is not the same as "empty".

For my purposes, I have a new function for my scripts, to wit:

```
def rectangular_selection_is_active():
    return editor.getSelectionMode() == SELECTIONMODE.RECTANGLE or editor.getSelectionMode() == SELECTIONMODE.THIN
```

**Comment by Yaron10** [comment]
> I really feel this is totally intentional, and not a bug.

I trust your feeling.

> But it would be great to hear what Neil has to say if you want to open a bug report on the Scintilla site.

Reading your reply, I realize I might not be aware of all the possible nuances.
But it would be great to hear what Neil has to say if **you** want to open a bug report on the Scintilla site. :)

**Comment by alankilborn** [comment]
> if you want to open a bug report on the Scintilla site

I respectfully decline, and not only because I don't think it is a bug. :-)
