### ISSUE TITLE
Theme bug in portable version

### ISSUE THREAD

**Issue by qx87** [notepad-plus-plus/notepad-plus-plus#12296]
I already posted the issue #1344 but it was closed for no good reason.

There was said:
> if your issue still persists, and it is still of relevance to you, please feel free to file a new issue as detailed and reproducible as possible.

Yes, the issue still persists, and yes, it is still of relevance to me, nothing changed.

And people did write about it: #2579, #1589,  #9409.

**Comment by clonsberry** [comment]
For others who are searching: I wrote [workaround instructions](https://github.com/notepad-plus-plus/notepad-plus-plus/issues/9409#issuecomment-1298496463) in 9409.
