### ISSUE TITLE
Three feature requests

### ISSUE THREAD

**Issue by sikotat** [notepad-plus-plus/notepad-plus-plus#12304]
Hello,

I want te suggest three feature requests.

1. Put the plus sign to the right of x. Currently, the plus sign is in the top right corner, which for me and someone else is far away and it gets annoying to come to the top right corner to open a new tab. I have named the screenshot "plus sign".
![plus sign](https://user-images.githubusercontent.com/115248917/194706623-a85f6f68-37fb-4a95-ac91-b490c8697246.png)

2. Add an option "Show the tab bar at the bottom". Some users like the tab bar at the bottom, than on top.

3.  Add panes, each of which supports tabbed browsing. I have named screenshots from "window pane 1" to "window pane 12". This is available in windows file explorer alternative called Q-Dir Explorer. If this is possible to make for Notepad++, it can be a real-time saver.
![window pane 1](https://user-images.githubusercontent.com/115248917/194707543-c58b280d-f14d-42a9-a66d-b80f3d8e6ede.png)
![window pane 2](https://user-images.githubusercontent.com/115248917/194707550-7b842fd7-c9b8-4049-9939-da3532150bda.png)
![window pane 3](https://user-images.githubusercontent.com/115248917/194707553-cbcf4eea-b74a-4aff-9acb-2d22c8e9d7d2.png)
![window pane 4](https://user-images.githubusercontent.com/115248917/194707558-7e462004-3be0-4875-aeb1-d38673725fd5.png)
![window pane 5](https://user-images.githubusercontent.com/115248917/194707564-20285559-e61c-4392-bbea-0fa6e94780f4.png)
![window pane 6](https://user-images.githubusercontent.com/115248917/194707567-f1c1ed4d-7f22-41f9-85e3-afb8d8529e25.png)
![window pane 7](https://user-images.githubusercontent.com/115248917/194707571-0ef78ad0-89de-423f-bb61-3b2662ef39b9.png)
![window pane 8](https://user-images.githubusercontent.com/115248917/194707574-ebf2dea1-c265-4d1b-b55b-526daa9e1554.png)
![window pane 9](https://user-images.githubusercontent.com/115248917/194707579-d87bf356-846a-46f1-b9d1-b8aec927773c.png)
![window pane 10](https://user-images.githubusercontent.com/115248917/194707586-17cdc1c3-14e6-4426-b4fd-5761c04bc688.png)
![window pane 11](https://user-images.githubusercontent.com/115248917/194707589-b6e7f46e-a8db-49a7-ac86-8bb737c50fcf.png)
![window pane 12](https://user-images.githubusercontent.com/115248917/194707591-5df119bc-c392-4166-9f8b-82e2656ae906.png)

**Comment by alankilborn** [comment]
Please make one "issue" per feature request.
As it is, your issue cannot be acted upon.
Moderator: Please reject and close this issue.
