### ISSUE TITLE
Spell checker has been removed?!

### ISSUE THREAD

**Issue by ddfssdfkofdsfighdfuigf** [notepad-plus-plus/notepad-plus-plus#1230]
The best thing ever introduced in any program was Notepad++'s built-in and wonderful spellchecker. No more fiddling with inane third-party crap. It was just there. I used it constantly, all day.

Then one day, recently, it was just gone. I haven't been able to find a single person or announcement or anything to explain what happened or why. Why is it removed?! It was the best damn feature ever introduced. I want it back if you really did remove it on purpose. And if not... then what's wrong?!

**Comment by dail8859** [comment]
Yes at one point it was removed (I believe v6.8) because it was causing issues for some users. With the latest version (v6.8.7), if you have it installed it will ask you if you want to keep it. So just reinstall it and you should be good from now on.

**Comment by ddfssdfkofdsfighdfuigf** [comment]
I just tried installing the latest version, but it didn't ask me anything like that. Sigh...

**Comment by dail8859** [comment]
Did you have the plug in installed?

**Comment by ddfssdfkofdsfighdfuigf** [comment]
What plug in?

**Comment by dail8859** [comment]
The DSpellCheck plug in I assumed the original question was about...

**Comment by ddfssdfkofdsfighdfuigf** [comment]
No... I'm talking about the built-in one, as clearly mentioned.

**Comment by dail8859** [comment]
> I'm talking about the built-in one

There is no spell checking "built-in", it has always been provided by a plugin.

**Comment by ddfssdfkofdsfighdfuigf** [comment]
That is simply not correct...

**Comment by dail8859** [comment]
It normally came with Notepad++ but was still a plugin.

To clear things up, just use the Plugin Manager and install the DSpellCheck plugin.

**Comment by ddfssdfkofdsfighdfuigf** [comment]
Thanks.

**Comment by Croydon** [comment]
@ddfssdfkofdsfighdfuigf Please close this issue.
