### ISSUE TITLE
Add edit notepad++ to Windows 11 context menu.

### ISSUE THREAD

**Issue by TruSoggy** [notepad-plus-plus/notepad-plus-plus#12303]
I have noticed, that this program was able to add stuff to the context menu on windows 11

maybe you can get some inspiration

https://github.com/ikas-mc/ContextMenuForWindows11

**Comment by n-buna404** [comment]
duplicate of https://github.com/notepad-plus-plus/notepad-plus-plus/issues/10320
workaround on win11 22H2 u can use shift+right click to open classic context menu

**Comment by Kristijan1001** [comment]
How is holding shift a solution, why are the devs so stubborn about it like bruh

**Comment by lilalien** [comment]
I'd like to see this added as well please.
