### ISSUE TITLE
Search is not working when text have a backslash (path)

### ISSUE THREAD

**Issue by arielbud** [notepad-plus-plus/notepad-plus-plus#12317]
### Description of the Issue

Search is not working when text have a backslash (path) , for example D:\TEST
### Steps to Reproduce the Issue

1.  Open the Notepad++ and enter several lines that have a path in it, for example 
D:\TEST
D:\TEST\test1
D:\TEST\test2

2.  Mark D:\TEST and open the search with Ctrl+F (or any other option)
3.  Search for D:\TEST with any option, nothing can be found (checking or unchecking Match Case does not change the outcome).

### Expected Behavior

I expect all 3 lines to appear in the search.

### Actual Behavior

Search fails to find any.

### Debug Information

Notepad++ v8.4.6   (64-bit)
Build time : Sep 25 2022 - 19:51:39
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : "C:\Program Files\Notepad++\change.log" 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 11 (64-bit) 
OS Version : 21H2
OS Build : 22000.978
Current ANSI codepage : 1255
Plugins : 
    ComparePlugin (2.0.2)
    mimeTools (2.8)
    NppConverter (4.4)
    NppExport (0.4)

![Notepad++SearchIssus](https://user-images.githubusercontent.com/115526963/195011120-85749ebd-fa6b-4253-8614-6b5c400da5b8.png)

**Comment by datatraveller1** [comment]
If you have "Regular expression" checked, the search has to be:
Find what: D:\\TEST

**Comment by arielbud** [comment]
OK, so I need the Extended , please solve this one

**Comment by alankilborn** [comment]
>please solve this one

Nothing to solve.  PBKAC.  Consult the searching section of the user manual, [HERE](https://npp-user-manual.org/docs/searching/) for more information.

Recommend CLOSURE of this item.

**Comment by dail8859** [comment]
Working as expected.
