### ISSUE TITLE
crash in Goto Matching brace

### ISSUE THREAD

**Issue by chund** [notepad-plus-plus/notepad-plus-plus#12318]
### Description of the Issue
N++ crashes when pressing Ctrl + B in an .RTF file having many  { } braces.

### Steps to Reproduce the Issue

1. Open RTF File
2. Press Ctrl + B

### Expected Behavior
not crash, Jump to last }

### Actual Behavior
crashed

### Debug Information

Notepad++ v8.4.6   (64-bit)
Build time : Sep 25 2022 - 19:51:39
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 11 (64-bit) 
OS Version : 21H2
OS Build : 22000.978
Current ANSI codepage : 1252
Plugins : 
    mimeTools (2.8)
    NppConverter (4.4)
    NppEditorConfig (0.4)
    NppExport (0.4)
    NppTextFX (0.2.4)
    XMLTools (3.1.1.13)

I can provide crash dump file if needed.

**Comment by xomx** [comment]
Cannot reproduce, it works ok for me (x64 v8.4.6, Win10).

Try to run N++ without the NppTextFX plugin and repeat the test.

If it does not help, append here please your specific RTF file (if you can or any such file where you can reproduce the crash) and the crashdump (zipped).

**Comment by chund** [comment]
Thanks for the hint! It works without NppTextFX.

**Comment by xomx** [comment]
I did not try that myself but there is a recent attempt to make it compatible with the N++ again:

https://github.com/rainman74/NPPTextFX2/releases

**Comment by alankilborn** [comment]
>recent attempt to make it compatible with the N++ again

@chund Possibly report this match-brace issue on the NPPTextFX2 site.
