### ISSUE TITLE
Number of lines is one too much in the status bar if the last line ends with CRLF

### ISSUE THREAD

**Issue by datatraveller1** [notepad-plus-plus/notepad-plus-plus#12316]
### Description of the Issue
On MS Windows, usually every line ends with CRLF including the last line.
If the last line ends with CRLF, the Notepad++ lines count in the status bar "lines: ..." always shows one line too much.

### Steps to Reproduce the Issue
If I open e.g. the file "c:\Program Files\Notepad++\change.log" of Notepad++ v8.4.6, the last line 30 is:
`* WinGup (for Notepad++) v5.2.4`**CRLF**

### Expected Behavior
Status bar: `lines: 30`

### Actual Behavior
Status bar: `lines: 31`

**Comment by alankilborn** [comment]
>usually every line ends with CRLF including the last line.

_Usually_ is the key word here.  It isn't a requirement.  If you want to require it, you should probably use the `editorConfig` plugin and specify you want that in its setup.

>Number of lines is one too much in the status bar if the last line ends with CRLF

You have an arguable point, but Notepad++ has decided to make the highest line number shown in the line-number margin match the `lines:` count on the status bar.  It is probably a "consistency" thing.

**Comment by datatraveller1** [comment]
Ok, I understand your point. The consistency is a good and valid point, but personally I have understood `lines:` on the status bar as lines count (number of lines) like the `wc -l` command. Actually, the number of lines should correspond to the newline (LF) counts.

I have been confused by this for many years, but it seems most people prefer the current implementation, so no problem. Thank you very much for your answer. And, of course: Best editor ever, many thanks to the developer team!

**Comment by datatraveller1** [comment]
One thought comes to my mind: To make everyone happy, options are great. So an option "Show lines: as LF count" would be nice. Imho I still think the lines count implementation of Notepad++ is simply wrong.

**Comment by alankilborn** [comment]
>an option "Show lines: as LF count" would be nice

IMO, I don't think there will ever be a setting controlling this.

>I still think the lines count implementation of Notepad++ is simply wrong.

Just to explore further:

So if there is any character present on line 31 but still no CRLF at the end, is that 30 lines to you (because there is 30 CRLF) or is it 31 lines (because there is some amount of data beyond the CRLF on line 30)?

**Comment by datatraveller1** [comment]
Thank you for coming back to this issue.
IF there is any character present on line 31 but still no LF at the end, the lines count should be 31.
Only if there is no character present the lines count should be 30. So you are right, the LF count isn't a proper solution either.
The correct solution is: `count LF characters in a file plus last line if without LF`

**Comment by alankilborn** [comment]
I did a little more research and confirmed what I suspected:  Notepad++ isn't determining the line count; Scintilla (Notepad++'s editing component) is.  This can be seen [HERE](https://github.com/notepad-plus-plus/notepad-plus-plus/blob/9bec8f54603a5fa8422c2ad5873123dcd7d10763/PowerEditor/src/Notepad_plus.cpp#L3793) with the call to the [SCI_GETLINECOUNT](https://www.scintilla.org/ScintillaDoc.html#SCI_GETLINECOUNT) function.

While Notepad++ itself _could_ override Scintilla's decision about the number of lines, something like that isn't typically done -- Notepad++ lets Scintilla be concerned with document interpretation.

So, yea, now more than ever I don't see this behavior ever changing...

**Comment by datatraveller1** [comment]
ok, thank you.
