### ISSUE TITLE
Auto-Completion for Normal Text doesn't work immediately

### ISSUE THREAD

**Issue by pryrt** [notepad-plus-plus/notepad-plus-plus#12325]
### Description of the Issue

When I have `autoCompletion\normal.xml` defined with `function` and `word`, Notepad++ doesn't auto-complete those in Normal Text files (*.txt or *.log) right away.  However, if I change the language to something else (like `XML` and then back to `None (Normal Text)`), then the auto-completions for Normal Text start working, and any new files opened or created after that

### Steps to Reproduce the Issue

0. Fresh unzip of portable v8.4.6 and run
1. `Settings > Preferences > Auto-Completion`: confirm
   - `> From _N_th character` = `1`
   - `Enable auto-completion on each input` = `Function and word completion`
2. Create new file:
    ```
    <?xml version="1.0" encoding="UTF-8" ?>
    <NotepadPlus>
        <AutoComplete language="Normal">
            <Environment ignoreCase="no" />
            <KeyWord name="function" func="yes" />
            <KeyWord name="word" />
        </AutoComplete>
    </NotepadPlus>
    ```
3. SaveAs `<portableDirectory>\autoCompletion\normal.xml`
4. **File > New**
5. Type `f` or `w` and it doesn't suggest anything
6. **Language > XML** then **Language > None (Normal Text)**
7. type `f` and it suggests `function`, or type `w` and it suggests `word`
   - at first I thought the difference between step 5 and step 7 was because normal.xml was new, and the toggle caused it to reload the normal.xml
8. from now on, any **File > New** followed by typing _will_ suggest the words/functions from `normal.xml`
9. **File > Close All**
10. Exit Notepad++ and restart
11. type `f` or `w` and it doesn't suggest anything
    - here, it proves that even if normal.xml already exists, Notepad++ doesn't immediately start autocompleting on normal text files
12. **Language > XML** then **Language > None (Normal Text)**
13. type `f` and it suggests `function`, or type `w` and it suggests `word`
    - but triggering a different language will allow Notepad++ to autocomplete on plain text files
14. from now on, any **File > New** followed by typing _will_ suggest the words/functions from `normal.xml`
15. **File > Close All**
16. Exit Notepad++ and restart
17. **Language > Perl** (so `new 1` now shows up as Perl): don't need to type anything
18. **File > New** (so now you are editing `new 2` which is still a normal text file)
19. type `f` and it suggests `function`, or type `w` and it suggests `word`
    - thus, it appears that even triggering a different language through another file will trigger autocompletion on plain text
20. **File > Close All**
21. Exit Notepad++ and restart
22. **File > Open** `change.log` or `LICENSE.txt`
23. Go to the end of and start typing `f` or `w`, and it doesn't suggest anything
    - just loading a normal text file isn't sufficient to trigger autocompletion
24. **Language > XML** then **Language > None (Normal Text)**
25. type `f` and it suggests `function`, or type `w` and it suggests `word`
26. from now on, any **File > New** followed by typing _will_ suggest the words/functions from `normal.xml`

### Expected Behavior

At step 5 or step 11 or step 23, it should suggest `function` or `word` as appropriate.  It shouldn't matter whether it's the first file loaded in Notepad++ or not, or whether you have changed the language or not: the autocompletions in normal.txt should always apply to normal text files.

### Actual Behavior

At step 5 or step 11 or step 23, it suggests nothing, and I have to do a workaround of changing the language away from None (Normal Text) and back, or at least loading or creating a file that uses a different language, in order to get Notepad++ to do autocompletion on normal .txt files.

### Debug Information

```
Notepad++ v8.4.6   (64-bit)
Build time : Sep 25 2022 - 19:51:39
Path : C:\usr\local\apps\npp\npp.8.4.6.portable.x64\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : ON
Cloud Config : OFF
OS Name : Windows 10 Enterprise (64-bit) 
OS Version : 20H2
OS Build : 19042.2006
Current ANSI codepage : 1252
Plugins : 
    mimeTools (2.8)
    NppConverter (4.4)
    NppExport (0.4)
```

**Comment by donho** [comment]
@pryrt 
IIRC, no API for normal text it's by design - and it makes sense for me.
 Are there some request for API of normal text?

**Comment by pryrt** [comment]
> IIRC, no API for normal text it's by design

There is actually about 99% of the functionality already in Notepad++, as my steps-to-reproduce showed, as long as you use `autoCompletion\normal.xml` as the name of the API/autocompletion file.  The problem is that it just doesn't take effect until you change from Normal Text to something else and then back to Normal Text, or if you start with a file in some other language with autocompletion (like Perl) and then do a `Ctrl+N`/**New File** to create a new Normal Text file.

> Are there some request for API of normal text?

People _are_ actually using it: if they type a lot of text files that aren't coding (ie, truly "plain text"), people populate the `autoCompletion\normal.xml` with their "jargon" words instead of function names, so they can use auto-completion to help them write longer words, even if they haven't yet typed it in the active document (so it's not in the active documents "words already typed" list).  (Imagine someone writing about life sciences, with words like `deoxyribonucleic` acid or `pneumonoultramicroscopicsilicovolcanoconiosis` -- even the first time they type it in a given document, they'd want to be able to auto-complete it).  So there's definitely a use case for it, and people _are_ using it, even with that limitation.

So, it mostly works as implemented, except when run with an empty session or starting with a session that only has Normal Text files open, it won't start auto-completing right away.

**Comment by donho** [comment]
@pryrt 
Thank you for your detailed explanation. I see your point.
I'll see what I can do to fix it.
