### ISSUE TITLE
FunctionList bugs in parsing code

### ISSUE THREAD

**Issue by brandpeter** [notepad-plus-plus/notepad-plus-plus#1232]
FunctionList only recognizes the closeSymbole of a classRange if it is followed by a cr/lf. If none is present, (ie. the file ends with the closeSymbole character), the entire class is not displayed.

Also, in a mixed parse, any function that is not in a classRange is still parsed and displayed even though it is enclosed in commentExpr.

In a classRange, the function's mainExpr starts parsing from the START of text returned by the classRange's mainExpr which is the text specifying the class. Thus the function's mainExpr has to make sure it skips forward past that string, either by starting on the next line or looking for some other text, otherwise the first function displayed will be the class itself.

**Comment by brandpeter** [comment]
Version used above is 6.8.7
Example of first problem ([eof] is the end of file marker):

    class xyz {
       statement;
    }[eof]

doesn't show class xyz, but

    class xyz {
        statement;
    }
    [eof]

does show.

**Comment by brandpeter** [comment]
Example of second problem is

    /* class xyz {
           statement
        } */

Still shows class xyz in the list even though `commentExpr="((/\*.*?\*)/|(//.*?$))"` is specified.

**Comment by brandpeter** [comment]
In JavaScript code, (or any other language where '//' is a comment marker?), if any literal in the code of a class contains a double slash, FunctionList ceases to output anything for that class. For example the double slash in the literal for the xpath property below:

    var class1 = {};
    class1.prototype = {
        prop1 : 1
        func1 : function(){
            var ret = {'xpath' : '//doc/xyz'};
        }
    };

**Comment by WinterSilence** [comment]
please fix it, php to have this problem

**Comment by MetaChuh** [comment]
please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins if you update from version 7.5.9 or below.
if your issue still persists, and it is still of relevance to you, please feel free to file a new issue as easy to understand and reproducible as possible.

thank you for your support and best regards.

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
(no extra account is needed, just use your github account to sign in)
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)

**Comment by WinterSilence** [comment]
@MetaChuh You behave inadequately and dont try fix this bug.
bug: file ended after `}`, function list - empty.
~~~
<?php
class Test {
  public function foo() {
  }
}
~~~
new line after `}`, function list - not empty.
~~~
<?php
class Test {
  public function foo() {
  }
}

~~~
