### ISSUE TITLE
Installers do not check for compatibility when run

### ISSUE THREAD

**Issue by kotenok2000** [notepad-plus-plus/notepad-plus-plus#12320]
### Description of the Issue

When i ran npp.8.4.6.Installer.arm64.exe it just installed it, despite the fact that my system uses amd64 cpu.
### Steps to Reproduce the Issue

1. Check that your system uses amd/intel cpu.
2. Install https://github.com/notepad-plus-plus/notepad-plus-plus/releases/download/v8.4.6/npp.8.4.6.Installer.arm64.exe
3. notepad++ is installed, but doesn't work

### Expected Behavior

Instaler refuses to install notepad++ on unsupported architecture.
### Actual Behavior

Installer installs arm64 notepad++ on amd64 hardware.

**Comment by alankilborn** [comment]
An off-topic but somewhat related suggestion: 

Installer should suggest a x64 install if running on 64-bit machine, and user is trying to install 32-bit version. An allowable thing, to be sure, but I’d think it makes sense to push the unknowing in the right direction.

**Comment by xomx** [comment]
OK, I will try a PR for this.
Maybe it could be in a similar style as it is now in the case of an unsupported OS.

**Comment by alankilborn** [comment]
>Installer should suggest a x64 install if running on 64-bit machine, and user is trying to install 32-bit version. An allowable thing, to be sure, but I’d think it makes sense to push the unknowing in the right direction.

@CennoxX downvoted this.  How about if it is modified to "For a very-first, i.e., non-upgrade, install..."?  That was my original intention, it just went unstated.

**Comment by xomx** [comment]
@alankilborn 

I understand your intention but I am not for it.

Even if I like it, there is still the fact that doing so would probably annoy not only the N++ power-users, but also all the conservative ones, as they simply do not like any change in behavior they are accustomed to (e.g. look at the fix for the autocomplete ... Enter -> Tab -> has to become Enter or Tab at the end).

I also saw here requests heading in the complete opposite direction (like "make the installer/updater less noisy or completely silent").

But I saw here too that Don sometimes gives preference to BFU-users over the power-users, so maybe create a new FR-issue and ask him about this proposal.

**Comment by alankilborn** [comment]
@xomx 

I'd move it to a separate issue if I cared enough. :-)
Having NEVER EVER installed Notepad++ is the reason for my personal lack of caring.  :-)

I just thought it made sense for the new user that perhaps grabs the 32-bit installer by mistake or out of a lack of knowledge, to nudge them toward the 64-bit if they have a 64-bit machine.

But I got a thumbs down and an "I'm not for it" so I'm certainly not advocating further for something I personally have no stake in.

Cheers.

**Comment by xomx** [comment]
@alankilborn 

> Having NEVER EVER installed Notepad++ is the reason for my personal lack of caring. :-)

Understood :-)
Even if I use the installer sometimes (especially at work), my own PC is full of differently set-up portable Notepads++, every for a different purpose, no installed one.

**Comment by xomx** [comment]
[Here](http://redwoodal.sweb.cz/NotepadPlusPlus/installer_-_ARM64_CPU_check/npp.8.4.6.Installer.arm64.exe) is the patched arm64 installer for testing.

How it looks in action:
![ARM64_CPU_installer_check](https://user-images.githubusercontent.com/13075183/195459238-e735e1f6-f250-4a82-952b-a63ffb17db77.png)

Is that OK? (the text is adapted to the existing "N++ unsupported OS" style messages.
