### ISSUE TITLE
Feature Request: Allow setting Change History colors

### ISSUE THREAD

**Issue by jmhg92** [notepad-plus-plus/notepad-plus-plus#12321]
### Description of the Issue

This isn't a bug report but rather a feature request if possible.

The new "Change History" feature should have an option to change the colors of the changes made and not just have green and red. This would be of great help for those of us who are colorblind and have difficulty telling both colors apart from each other.

### Steps to Reproduce the Issue

1. Open a file
2. Make changes to display the first color
3. Save the file to display the second color

### Debug Information

Notepad++ v8.4.6   (64-bit)
Build time : Sep 25 2022 - 19:51:39
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : C:\_BACKUPS\_NPP
OS Name : Windows 10 Pro (64-bit) 
OS Version : 21H2
OS Build : 19044.2075
Current ANSI codepage : 1252
Plugins : 
    ComparePlugin (2.0.2)
    DSpellCheck (1.4.24)
    JSMinNPP (1.2205)
    mimeTools (2.8)
    NppConverter (4.4)
    NppExport (0.4)
    NppSaveAsAdmin (1.0.211)
    XMLTools (3.1.1.13)
    zoomdisabler_x64 (1.2)

**Comment by JimKnecht** [comment]
I would like this feature as well.

I'm not colorblind I just use a dark theme someone made (VS2015-Dark) that clashes with such a bright orange color which makes it kind of distracting to me.

![image](https://user-images.githubusercontent.com/3501940/195737924-cb24e939-e8aa-430f-ae5e-a29a49aca6ab.png)

**Comment by arbabf** [comment]
> I would like this feature as well.
> 
> I'm not colorblind I just use a dark theme someone made (VS2015-Dark) that clashes with such a bright orange color which makes it kind of distracting to me.

You echoed my sentiment word-for-word.

**Comment by kger** [comment]
I'll chime in here that I, too, would like to see this option.  The green background clashes with my syntax colors and makes the changed text basically unreadable.

**Comment by alankilborn** [comment]
>The green background clashes with my syntax colors and makes the changed text basically unreadable.

How does it affect changed text (making it unreadable)? -- _Change History_ in its current form is only putting something in the margin, not affecting text appearance

**Comment by JimKnecht** [comment]
> > The green background clashes with my syntax colors and makes the changed text basically unreadable.
> 
> How does it affect changed text (making it unreadable)? -- _Change History_ in its current form is only putting something in the margin, not affecting text appearance

I think what kger is getting at is that when using a dark mode the color of the border is so bright it makes the eyes focus there making it difficult to focus on the actual text that changed which is what we were all saying above.

The feature is nice but it is just too bright which is why we would like configurable colors.

**Comment by Nagidrop** [comment]
Gotta bump this one up. There hasn't been any signs of implementation after such a long time. Could it possibly be forgotten amid thousands of issues?

**Comment by mpheath** [comment]
Implementation to modify the Change History colours.  It will handle the colouring of both markers and indicators of Change History, Themes default to existing Change History colours though can be updated in the Style Configurator.

![style](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/58158242/5bdc1a0c-a8ad-4428-88e9-ad117de080de)
