### ISSUE TITLE
Someone violated your copyright license

### ISSUE THREAD

**Issue by yuxin212** [notepad-plus-plus/notepad-plus-plus#12324]
Hello,

Just want to let you know that someone in China copied your code and changed the license (which is not allowed), and published in GitHub. 
Link to it: https://github.com/NotepadFree/NotepadFree
I really don't like this kind of things. 
I hope you can contact GitHub to delete that repo. 
Thanks.

**Comment by dail8859** [comment]
How exactly is the license violated? It looks to be released under the same license that this repository is released under.

**Comment by dail8859** [comment]
Looking a little more than just the root license file I guess there seems to be a lack of attribution which could potentially be an issue. And for the record: I am not a lawyer.

**Comment by yuxin212** [comment]
The header of the license is modified. It appears they directly copied your code and just changed all 'Notepad++' to 'Notepadfree'. 
You can find a history of change from here: https://github.com/NotepadFree/NotepadFree/commit/e7a014388ab16ef07d412d0b0c1aa073ccb605dc
I am also not a lawyer. I don't know how GitHub handles such issues. 
Thanks.

**Comment by yuxin212** [comment]
As I understand, even change in the header of the license is not allowed.

**Comment by dail8859** [comment]
From my understanding that section that was changed isn't _technically_ part of the official GPLv3 license.

However, do believe removing copy right notices from the code is a potential issue...but I'll let @donho decide.

**Comment by yuxin212** [comment]
Thanks.

**Comment by donho** [comment]
I'm not lawyer either - that makes 3 of us :)
Joke aside, I think it's OK - as soon as the GPL v3 and all the contributor's name are kept.

For the fork of changing the product name - why not? From my viewpoint, I have no problem with it: at least Chinese users can use Notepad++ (or NotepadFree, or whateverits name) without any censorship from the Chinese government, and that might be a good thing.

**Comment by prahladyeri** [comment]
I'm not a lawyer either and that makes 4 of us :)

I'm not sure if this (technically) violates the GPL license or not but it sure doesn't appear to violate the larger spirit of GPL or the Free Software Foundation (FSF). The distributed copies are still free with source code and don't take away any rights from their users. Correct me if I'm wrong?

**Comment by dail8859** [comment]
@prahladyeri I agree the GPL allows (and encourages) other users to distribute their own version of free software.

The only part I am not sure of is if you create a fork of an open-source project if you can claim that you own the entire source code or not. Don Ho holds the original copyright.

Section 5a of the GPLv3 states ```The work must carry prominent notices stating that you modified it, and giving a relevant date.``` I haven't looked at NotepadFree very deeply, but they may be adequalty applying to this requirement. The thing I initially saw was the removal of the copyright noticed within the source code from the commit linked above which may or may not be allowed since I am not a lawyer.

**Comment by WillemJiang** [comment]
It's wrong to remove the copyright declaration.  I just created [an issue](https://github.com/NotepadFree/NotepadFree/issues/11) for it. 

You could not change the copyright statement unless you significantly changed the source code.

Here is a free course about License and copyright in Open Source development tells about it.
https://trainingportal.linuxfoundation.org/courses/licensing-basics-for-developers-lfc191

**Comment by donho** [comment]
在 Twitter 上有關 Notepad++ 被複刻 (forked) 而[我的反應](https://github.com/notepad-plus-plus/notepad-plus-plus/issues/12324#issuecomment-1276085720)似乎沒被大部分的人理解，在此用漢語解釋我的想法與立場：

Notepad++ 是在 GPL 保護下的自由軟體 (Free Software)，GPL 保證任何人有複刻 (fork) 以 GPL 為授權的軟體的自由，前提是 1. 被複刻 (forked) 的軟體必須保持原作者或貢獻者名（他們的著作權受 GPL 保護）2. 修改的軟體必須附帶修改過的原始碼 3. 被複刻軟體必須以 GPL 為授權。在這三個主要前提被尊重的情況下，複刻 Notepad++ 是合理與合法的。

因為我行使我的言論自由而遭致 Notepad++ 在中國無法被下載。
而開發 Notepad++ 的初衷是提供分享免費的文字與原始碼編輯軟體給任何電腦從事人員 (Software, IT ppl, etc...)，當然也抱括中國電腦從事人員。我的重點是，即便我不願意讓這些中國極端的民族主義者使用 Notepad++，並非所有的中國人都是如此。被複刻的 Notepad++，不論其動機如何，它可以通過中國政府的審查機制而提供中國電腦從事人員使用 Notepad++ 的可能，無論它的名稱為何。而「讓任何人使用」是GPL 自由軟體的真髓，也是我開發 Notepad++ 的初衷 。

我相信上述的解釋相當明確了，我也不會再為類似的事件講述我的看法。要做的事情太多，而時間總是不夠 ； 上 PornHub 網站卯管自慰的時間都不夠了，我不想也不願浪費時間在這些盲目的愛國主義者身上。

**Comment by ethzerox** [comment]
局气👍

**Comment by chen3feng** [comment]
赞一个

**Comment by HongJheLi** [comment]
> 

當然也「包括」中國電腦

**Comment by ariakeumi** [comment]
> 在 Twitter 上多人討論有關 Notepad++ 被複刻 (forked)，而[我的反應](https://github.com/notepad-plus-plus/notepad-plus-plus/issues/12324#issuecomment-1276085720)似乎沒被大部分的人理解，在此用漢語解釋我的想法與立場：
> 
> Notepad++ 是在 GPL 保護下的自由軟體 (Free Software)，GPL 保證任何人有複刻 (fork) 以 GPL 為授權的軟體的自由，前提是 1. 被複刻 (forked) 的軟體必須保持原作者或貢獻者名（他們的著作權受 GPL 保護）2. 修改的軟體必須附帶修改過的原始碼 3. 被複刻軟體必須以 GPL 為授權。在這三個主要前提被尊重的情況下，複刻 Notepad++ 是合理與合法的。
> 
> 因為我行使我的言論自由而遭致 Notepad++ 在中國無法被下載。 而開發 Notepad++ 的初衷是提供分享免費的文字與原始碼編輯軟體給任何電腦從事人員 (Software, IT ppl, etc...)，當然也抱括中國電腦從事人員。我的重點是，即便我不願意讓這些中國極端的民族主義者使用 Notepad++，並非所有的中國人都是如此。被複刻的 Notepad++，不論其動機如何，它可以通過中國政府的審查機制而提供中國電腦從事人員使用 Notepad++ 的可能，無論它的名稱為何。而「讓任何人使用」是 GPL 自由軟體的真髓，也是我開發 Notepad++ 的初衷 。
> 
> 我相信上述的解釋相當明確了，我也不會再為類似的事件講述我的看法。要做的事情太多，而時間總是有限 ； 上 PornHub 網站卯管自慰的時間都不夠了，我不想也不願浪費時間在這些盲目的愛國主義者身上。

《格局》

**Comment by yu-steven** [comment]
老哥稳，我狭隘了

**Comment by yu-steven** [comment]
老哥稳👍

**Comment by a-lang** [comment]
成熟兼具自信的回文👍❤️🇹🇼

**Comment by KevinZonda** [comment]
i believe they used the same license (GPLv3)

**Comment by 1live** [comment]
之前俺是小粉红的时候觉得俺用一下也没什么的，毕竟是白嫖您的劳动成果，现在更是一定要继续支持啦

**Comment by earthengine** [comment]
@donho 
問題在於他們違反了（至少）這一條

> 1. 被複刻 (forked) 的軟體必須保持原作者或貢獻者名（他們的著作權受 GPL 保護）

（因爲您的名字成爲了禁止詞）

如果這樣可以的話，大概GPL就名存實亡了。

**Comment by ShikiSuen** [comment]
> The header of the license is modified. It appears they directly copied your code and just changed all 'Notepad++' to 'Notepadfree'. You can find a history of change from here: [NotepadFree/NotepadFree@e7a0143](https://github.com/NotepadFree/NotepadFree/commit/e7a014388ab16ef07d412d0b0c1aa073ccb605dc) I am also not a lawyer. I don't know how GitHub handles such issues. Thanks.

This has no solution. The name "Notepad++" is almost like a censored word. Even if GPLv3 has legal power, it is useless in front of other more powerful laws in China.

此局无解。「Notepad++」几乎就快成了敏感词。哪怕 GPLv3 有法律效力，在中国也是有法律优先级的（多部不同种类的法律，有优先权之分）。

**Comment by ShikiSuen** [comment]
Although I have no comment to Notepad++ here at this moment, I do have some comments regarding the word "free" among the author's replies above: It appears like "free world is consisting of only NATO countries and therir semi-colonies like Japan and South Korea" to me.

**Comment by OSCARJ0211** [comment]
> Although I have no comment to Notepad++ here at this moment, I do have some comments regarding the word "free" among the author's replies above: It appears like "the free world is consisting of only NATO countries and their semi-colonies like Japan and South Korea, plus those countries / regions used as war proxies benefitiable to the United States" to me.
> 
> ![image](https://user-images.githubusercontent.com/3164826/198342076-4cecc3b2-945f-49d7-93ef-b8c6a5e3ffc0.png)

请不要岔开话题，没人在乎你颅内的世界政治。

**Comment by Razodiac** [comment]
> Although I have no comment to Notepad++ here at this moment, I do have some comments regarding the word "free" among the author's replies above: It appears like "the free world is consisting of only NATO countries and their semi-colonies like Japan and South Korea, plus those countries / regions used as war proxies benefitiable to the United States" to me.
> 
> ![image](https://user-images.githubusercontent.com/3164826/198342076-4cecc3b2-945f-49d7-93ef-b8c6a5e3ffc0.png)

I'm grateful that you included New Zealand.

**Comment by ShikiSuen** [comment]
@goldflower 你是被 BrLi 灌了腦屎才來的？誰跟你說我還在日本的？
作者的言論與產品本身是兩碼事情。

**Comment by ShikiSuen** [comment]
@Razodiac 'cause New Zealand is among those countries who respects Her / His Majesty as their only one emperor.
