### ISSUE TITLE
NppFTP, timeout set to 0, has to be reset every time I invoke NPP

### ISSUE THREAD

**Issue by gailmwalker** [notepad-plus-plus/notepad-plus-plus#1233]
Since the last time I updated the NppFTP plugin, several weeks ago, I have had trouble connecting to a remote system with it. A co-worker discovered that it's because the timeout in Profile Settings is 0. If we reset it to a larger value, it all works but this revised timeout setting never gets saved so we have to do it every day.

NppFTP version: 0.26.3 Unicode
Notepad++ version: 6.8.6 (though this was happening with an older version with current NppFTP plugin too, I hadn't updated Notepad++ in a few years)

I didn't see this reported already. I am running on Windows 7 using NppFTP to a Linux system.

I'm not sure if its NppFTP that needs a fix or if you should fix the main system so that when the timeout in profile settings is reset, it gets saved. Maybe both.

**Comment by vlakoff** [comment]
If I configure a timeout, it gets properly saved when Notepad++ exits.

Then I open Notepad++ again, the timeout is 0, and this 0 gets saved when exiting again.

So the problem should be somewhere about config *reading*.

**Comment by vlakoff** [comment]
Also, isn't timeout 0 supposed to mean "no timeout"?

**Comment by dail8859** [comment]
Closing since this is 3rd party plugin related.
