### ISSUE TITLE
Search & replace \n\r in a single file and "all open files"

### ISSUE THREAD

**Issue by WernerWarweg** [notepad-plus-plus/notepad-plus-plus#12340]
### Description of the Issue

1. I tried to change a file with CRLF at the end of line to only LF. That runs!
But when two lines are there like
askldjhalfksdjhfkadsjh **text** aflsdjfhalsdjhflajsdhfl.LRLF
LRLF
it doesn´t run
2. When I opend more than one file, and in all of them I tried to change CRLF to LF there is no changeing in  all files,

### Steps to Reproduce the Issue
1. Enter a demo test with normal CRLF 
CRLF 
2. strg-h and enter the \r\n \r\n and run
3. the error willl appear.
4. open two or more files with content like number 1.
5. the same like 2
6. Button "in all open files"
7. the error willl appear.

### Expected Behavior
I expected, that all CRLF ate chneged into LF and if "in all files"-button is clicked, in all files there is a changing.

### Actual Behavior
see above

### Debug Information
Notepad++ v8.4.6   (64-bit)
Build time : Sep 25 2022 - 19:51:39
Path : D:\Program Files\Notepad++\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 11 (64-bit) 
OS Version : 21H2
OS Build : 22000.1098
Current ANSI codepage : 1252
Plugins : 
    DSpellCheck (1.4.23)
    Linefilter3 (1)
    mimeTools (2.8)
    NppConverter (4.4)
    NppExport (0.4)
    PreviewHTML (1.3.2)

**Comment by dfs-** [comment]
Guess you need to remove your space between `\r\n \r\nˋ. However I must admit, that I barely understand anything from what is written.

can you add real-life examples of whats the starting document and whats the desired result?

**Comment by WernerWarweg** [comment]
1. I tried both: with and without blanc. 
![grafik](https://user-images.githubusercontent.com/6221476/196037033-f8f0c044-0792-45fb-be9c-6ab896dd86fd.png)
(red arrow: shows the blanc)
2. when starting this with strg-h and press "in all files" nothing happens in other then the actuell file.
![grafik](https://user-images.githubusercontent.com/6221476/196037343-f028a657-e49a-4314-9519-9c9803914898.png)

**Comment by datatraveller1** [comment]
Perhaps you accidentally pressed "Replace all" instead of "Replace all in all open documents"?

**Comment by alankilborn** [comment]
>However I must admit, that I barely understand anything from what is written.

I agree with this.

@WernerWarweg Can you take your problem over to the Community site?  See [HERE](https://community.notepad-plus-plus.org/).  You'll get some definitely help there as that is the main support site.

**Comment by WernerWarweg** [comment]
Now the problem is solved!
**The editor shows a blanc** , but search and replace **doesn´t need one**. With \r\n [blanc] \r\n is no search & replace to realise, 
Now I take two steps: 
**First** search \r\n replace with \n and 
**second** \n\n replace with \n
Thank you for thecomments.

**Comment by alankilborn** [comment]
A key closing point is that there was nothing wrong with the search and replace functionality of Notepad++ stemming from this issue.

**Comment by alankilborn** [comment]
>Please look at the grafic some days ago (red arrow). My problem was the blanc at the end of the line. If the search field has that content the exchange doesn´t fit.

That's because there is no blank character there; it is just a visual effect -- convince yourself of that by putting your caret on the `s` character in `optimistisch.` and start pressing and releasing the right arrow key several times slowly, noting where the caret moves to after each release.  After the `.` one more right arrow press+release and your caret will be at the start of the following line.  Thus, there is NO SPACE where your red arrow points, so you should not include it in a search expression.

@datatraveller1 said this well when he said:

>There cannot be a blank after a CRLF on the same line.

Also, if you are converting line endings you should not do it with search-and-replace; there's a built-in method:

![image](https://user-images.githubusercontent.com/77065706/196802888-cb7ce7de-ee7f-470a-aac7-14ee2589dfe2.png)

**Comment by WernerWarweg** [comment]
Thank you!!!
Thats very fine, because this Wordpress installation runs on Linux. 
This help is an addition while I like Notepad++!!!
Have a nice day.
Warm regards,
Werner
