### ISSUE TITLE
Language detection for php/html

### ISSUE THREAD

**Issue by Stan-librarian** [notepad-plus-plus/notepad-plus-plus#12378]
### Description of the Issue

Language detection of php files containig both php and html codes is html, not php.
So when I use the comment function (CTRL Q) it inserts html comment code and not php comment code.
Doesn't language detection use file extension any more ?

### Expected Behavior

Each choice has its own logic, I don't know how N++ could do better when a single file uses more than one language.

### Actual Behavior

After updating to 8.4.6 x86 version, the detected language of my php files containig both php and html codes is html, not php. Prior to the update, it was php.
So when I use the comment function (CTRL Q) it inserts html comment code and not php comment code.

### Debug Information

Notepad++ v8.4.6   (32-bit)
Build time : Sep 25 2022 - 19:55:26
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Command Line : "D:\Users\sjun\Documents\webapps\php-sip2\retours.php"
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 10 Enterprise (64-bit) 
OS Version : 21H2
OS Build : 19044.2006
Current ANSI codepage : 1252
Plugins : 
    ComparePlugin (2.0.2)
    CsvQuery (1.2.9)
    mimeTools (2.8)
    NppConverter (4.4)
    NppExport (0.4)
    NPPJSONViewer (1.40)
    NppMarkdownPanel (0.6.2)
    NppToolBucket (1.10.6622.41336)
    PythonScript (2)

**Comment by ArkadiuszMichalski** [comment]
@Stan-librarian Put some file/code to reproduce your issue.

**Comment by rdipardo** [comment]
@Stan-librarian,
> After updating to 8.4.6 x86 version, the detected language of my php files containig both php and html codes is html, not php.

Do these files have a document type declaration at the top, like this?

~~~html
<!DOCTYPE html>
~~~~

If so, it's the same problem as #12226 and #12253, which was fixed in af0bc2e11.
