### ISSUE TITLE
Mouse cursor keeps changing to “I-beam pointer”

### ISSUE THREAD

**Issue by przemo20** [notepad-plus-plus/notepad-plus-plus#12385]
### Steps to Reproduce the Issue

1. Install ComparePlus plugin
2. Create 3 new documents and type something different in Document #&#x2060;2 and #&#x2060;3 (#&#x2060;1 can stay empty)
3. Compare Document #&#x2060;2 and #&#x2060;3 with ComparePlus plugin (click on the third document → from the top menu bar select “Plugins” → ComparePlus → Compare)
4. Click on the Document #&#x2060;1
5. Click on the blank area in the 2nd view (Document #&#x2060;3)
6. Cursor should start now acting weird

### Expected Behavior

Mouse cursor should not keep changing to “I-beam pointer”.

### Actual Behavior

Mouse cursor keeps changing to “I-beam pointer”, when you hover over something, like top menu bar items.

### Debug Information

Notepad++ v8.4.6   (64-bit)
Build time : Sep 25 2022 - 19:51:39
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 10 Pro (64-bit) 
OS Version : 22H2
OS Build : 19045.2130
Current ANSI codepage : 1252
Plugins : 
    ComparePlus (1)
    mimeTools (2.8)
    NppConverter (4.4)
    NppExport (0.4)

Video: https://www.youtube.com/watch?v=tXayNJirels
I'm not entirely sure if this is a problem with Notepad++ or if I should report it on the [ComparePlus github page](https://github.com/pnedev/comparePlus).

**Comment by alankilborn** [comment]
Can you list some Steps to Reproduce that don't include use of the ComparePlus plugin?  If not, I'd say you should find where ComparePlus is supported and log an issue there.

**Comment by Yaron10** [comment]
@przemo20,

This is a ComparePlus issue. It should be fixed in the [latest development version](https://ci.appveyor.com/project/pnedev/compareplus/builds/45114280/job/1kf2xe82ciy6pu7i/artifacts).
Could you please try it?

**Comment by przemo20** [comment]
@Yaron10 Just tried it and it seems to work – I can no longer reproduce the issue.

Thanks for investigating it.

**Comment by Yaron10** [comment]
@przemo20,

Thank you for confirming.

@pnedev,

Thank you for fixing it.
I haven't tested it, but https://github.com/pnedev/comparePlus/commit/6db7921fff99ac2dce89529fdf749971690beca1 probably fixes this issue as well.
