### ISSUE TITLE
My settings for Notepad-Plus-Plus aren't saved

### ISSUE THREAD

**Issue by zetdo** [notepad-plus-plus/notepad-plus-plus#12382]
### Steps to Reproduce the Issue

1. Go to Settings -> Style Configurator  
2. Check Bold in 'Font Style' and check 'Enable global font', 'Enable global font size', and 'Enable global bold font style' 
3. Save & Close 
4. Exit Notepad

### Expected Behavior

Font style is bold 
### Actual Behavior

All checked box is unchecked when I open a new Notepad 
###

**Comment by alankilborn** [comment]
Please follow the template and provide _Debug Info_

**Comment by zetdo** [comment]
Sorry, I don't know what you need. [This is my record video](https://file.io/dyBEhSATDawU).

**Comment by alankilborn** [comment]
Read and follow the template where it says Debug Information:

```
<!--- In your Notepad++, click on the "?" menu (found to the right of "Window" in the menu bar) -->
<!--- In the menu that drops down, choose "Debug Info..." -->
<!--- A message box will open detailing specifics about your Notepad++ version, plugins, etc. -->
<!--- CLICK ON THE BLUE LINK with the text "Copy debug info into clipboard" -->
<!--- Do a PASTE HERE -->
```

**Comment by zetdo** [comment]
Notepad++ v8.4.6   (64-bit)
Build time : Sep 25 2022 - 19:51:39
Path : D:\Software\Notepad++\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : ON
Cloud Config : OFF
OS Name : Windows 11 (64-bit) 
OS Version : 22H2
OS Build : 22621.674
Current ANSI codepage : 65001
Plugins : 
    mimeTools (2.8)
    NppConverter (4.4)
    NppExport (0.4)

**Comment by pryrt** [comment]
When I follow that same procedure, it works for me.  Global Override toggles are stored in `config.xml`.  You are in Local Config Mode, so that config file is stored as `D:\Software\Notepad++\config.xml`.  You will need to check to make sure that your normal user has write-permission to that file: if not, it cannot save changes to those settings.

**Comment by ArkadiuszMichalski** [comment]
As suggested above, check your access permissions for your path `D:\Software\Notepad++`.
