### ISSUE TITLE
Syntax highlight does not work for triple-quote f-strings in python script files

### ISSUE THREAD

**Issue by CC-Hsu** [notepad-plus-plus/notepad-plus-plus#12392]
### Description of the Issue
Hi, team,

Recently I find that syntax highlight does not work on python triple-quote form f-strings in the latest Notepad++ 8.4.6.

Syntax highlight on normal triple-quote strings works and I can find the corresponding options for them.
![image](https://user-images.githubusercontent.com/8018872/197546719-f4195d77-9385-4c5f-bcab-e1f27c16f78b.png)

It would be great if notepad++ can include f-string triple-quote syntax highlight. 

Best Regards.

### Simple test case

``` python
#!/bin/python3

xx="notepad++"

# syntax highlight works in notepad++
str1 = '''
TRIPLE hello, {}
'''.format(xx)

# syntax highlight works in notepad++
str2 = """
TRIPLEDOUBLE hello, {}
""".format(xx)

# syntax highlight does not work in notepad++
str3 = f'''
f-TRIPLE hello no highlight, {xx}
'''

# syntax highlight does not work in notepad++
str3 = f"""
f-TRIPLEDOUBLE hello no highlight, {xx}
"""
```
![image](https://user-images.githubusercontent.com/8018872/197548725-524b57f7-9c21-4aa8-9c65-ebd4cccb2488.png)

**Comment by alankilborn** [comment]
It works for me:

![image](https://user-images.githubusercontent.com/77065706/197549608-d9e66b08-0ffb-4617-8f29-0292ca56c4fa.png)

Probably your stylers.xml just needs updating.

**Comment by CC-Hsu** [comment]
Hi, alankilborn,

Thanks a lot for your hint. 😊

It seems that my `C:\Users\username\AppData\Roaming\Notepad++\stylers.xml` does not match the current `C:\Program Files\Notepad++\stylers.model.xml`.

![image](https://user-images.githubusercontent.com/8018872/197561712-7dc06297-4ed0-4c15-8eb4-da24638b3484.png)

Is it OK to simply overwrite my `stylers.xml` with the current `stylers.model.xml`?

Is there anything should I overwrite together?
(I have some custom preference settings. 😅)

Best Regards.

**Comment by CC-Hsu** [comment]
Hi, alankilborn, 

Thanks a lot for your suggestion.

I'll try to merge these two files later.

Best Regards.
