### ISSUE TITLE
Tab settings are not persistent ( at least for external lexers ).

### ISSUE THREAD

**Issue by sanastasiou** [notepad-plus-plus/notepad-plus-plus#1239]
Hi,

I have a plugin which among other stuff has a lexer. Everything works just fine, except one thing..

Changing the tab settings is not persistent. It works only for the current session. It doesn't matter if the settings are stored locally or in the cloud, they reset to default after every restart of the editor.

**Comment by sanastasiou** [comment]
Will try to debug this my own and see wth is going on - will provide updates.

**Comment by sanastasiou** [comment]
It's pretty obvious from the source that DSL tab settings aren't saved. 

@dail8859 Can you please tell me how to enable plugins when using the source? Then I can fix this issue easily.

**Comment by dail8859** [comment]
I've just copied the built exe over the installed version.  Not really a nice or easy way, but haven't had a situation where I've had to do it a lot. So I just did what worked.

**Comment by sanastasiou** [comment]
OK, I will try it like this.

**Comment by sanastasiou** [comment]
Fix merged with another plugin related pull request. https://github.com/notepad-plus-plus/notepad-plus-plus/pull/863

Already tested this with most actual master. Works like a charm :)

**Comment by sanastasiou** [comment]
I hope this get's committed.

**Comment by sanastasiou** [comment]
@dail8859 

As requested:

https://github.com/notepad-plus-plus/notepad-plus-plus/pull/1242

**Comment by sanastasiou** [comment]
Closing this since relevant PR never got merged and I stopped using the editor all together.
