### ISSUE TITLE
Notepad 8.4.6 bookmark problem

### ISSUE THREAD

**Issue by jacdyl** [notepad-plus-plus/notepad-plus-plus#12391]
### Description of the Issue
Notepad version 8.4.6 64 bit

### Steps to Reproduce the Issue

1.  checkbox Bookmark line
2.  Mark All
3. Search>Bookmark>remove unmarked lines

### Expected Behavior

Non bookmarked lines should be deleted

### Actual Behavior

Lines are still visible

### Debug Information

Notepad++ v8.4.6   (64-bit)
Build time : Sep 25 2022 - 19:51:39
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : "C:\Users\*USER*\Desktop\sometext.txt"
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 10 Pro (64-bit) 
OS Version : 21H1
OS Build : 19043.2130
Current ANSI codepage : 1250
Plugins : 
    mimeTools (2.8)
    NppConverter (4.4)
    NppExport (0.4)

**Comment by alankilborn** [comment]
Cannot reproduce:

Start with:

![image](https://user-images.githubusercontent.com/77065706/197524983-277cebdf-eb3c-408b-9a2c-7d0358b727ad.png)

Run:

![image](https://user-images.githubusercontent.com/77065706/197525080-0be84e01-ac29-4661-b277-3b0f593475e4.png)

Produces:

![image](https://user-images.githubusercontent.com/77065706/197525155-517fcfaf-147d-4538-8b32-63fb7fa8e73b.png)

Running:

Notepad++ v8.4.6   (64-bit)
Build time : Sep 25 2022 - 19:51:39
Path : C:\\...\npp.8.4.6.portable.x64\notepad++.exe
Command Line : -titleAdd="8.4.6 64-bit" -multiInst
Admin mode : OFF
Local Conf mode : ON
Cloud Config : OFF
OS Name : Windows 10 Enterprise (64-bit) 
OS Version : 21H2
OS Build : 19044.2006
Current ANSI codepage : 1252
Plugins : 
    MenuIcons (2)
    mimeTools (2.8)
    NppConverter (4.4)
    NppExport (0.4)
    PythonScript (2)

**Comment by ArkadiuszMichalski** [comment]
It works fine for me too. 
@jacdyl Describe in more detail how to reproduce your problem.

**Comment by jacdyl** [comment]
There is a problem with files above 70 MB. When I bookmark some lines and
choose (from search) option: remove unmarked lines then nothing happens.

pt., 28 paź 2022, 11:55 użytkownik ArkadiuszMichalski <
***@***.***> napisał:

**Comment by jacdyl** [comment]
This option works well with small files.  But with large files this problem
arises, but not always either.


pt., 28 paź 2022, 20:20 użytkownik Jacek D ***@***.***> napisał:

**Comment by jacdyl** [comment]
I will try to record a video and will send you when it happens to me again.

pt., 28 paź 2022, 20:29 użytkownik Jacek D ***@***.***> napisał:

**Comment by ArkadiuszMichalski** [comment]
Would be better to put the zipped file where this problem can be reproduced.

**Comment by jacdyl** [comment]
I am sending a sample file.
As you can see on pic1, I've marked address, city and postcode.
When I used remove the unmarked lines pic2, nothing happened.
You see the result on pic3. My computer is dell vostro, 8 GB RAM, 1 TB SSD


[test_file.zip](https://github.com/notepad-plus-plus/notepad-plus-plus/files/9895526/test_file.zip)
![pic1](https://user-images.githubusercontent.com/116565167/198872224-37c815c6-823c-4c56-9de2-195413951b35.png)
![pic2](https://user-images.githubusercontent.com/116565167/198872225-e2cd81d2-248b-42e9-b283-15c11a771184.png)
![pic3](https://user-images.githubusercontent.com/116565167/198872226-66770d87-1003-4f82-b66a-52c60b7db183.png)

**Comment by ArkadiuszMichalski** [comment]
In fact, something is wrong with large files. STR:
1. Open some big files or download and unpack this one [html_whatwg.zip](https://github.com/notepad-plus-plus/notepad-plus-plus/files/9895719/html_whatwg.zip).
2. Open Notepad++ and open above file.
3. Add some bookmarks at the begining.
4. Invoke `Search>Bookmark>Remove Unmarked Lines`.

Unmarked lines still exists. Additionally our file has change state, undo (ctrl+z) and `Search>Bookmark>Remove Bookmarked Lines` commands not work.

I also checked if it was not the fault of `History change` future and bingo. After turning it off, everything works fine. Another problem with this option. @donho Maybe turning it on by default was too hasty.

**Comment by satori80** [comment]
The file doesn't have to be 70 MB big; I'm having similar issues with a ~ 30 MB file where I'm trying to remove the bookmarked lines. It will remove some small % & won't do any more until I save, close, reopen & do it again. I have to keep doing this repeatedly until it all gets done.

This has actually been going on for a while now, but I didn't realize that the larger processed file size meant that not everything was being removed it until 2 days ago.

**Comment by ArkadiuszMichalski** [comment]
@donho 

Check my STR https://github.com/notepad-plus-plus/notepad-plus-plus/issues/12391#issuecomment-1296241498, looks like `History change` and `Remove Bookmarked Lines` disturb each other. Also this one https://github.com/notepad-plus-plus/notepad-plus-plus/issues/12381#issuecomment-1294941706 is caused because of `History change`.

It would be worth eliminating them before the next release.

**Comment by donho** [comment]
Thank you @ArkadiuszMichalski for pinging me.
I will check this issue.

**Comment by donho** [comment]
Fix by https://github.com/notepad-plus-plus/notepad-plus-plus/commit/69998ab7dec86c2fcf4f8381ce10f5a7d09574de

**Comment by jacdyl** [comment]
Hi,

In the new version of notepad++ v8.5.8
, there is still a problem, which Arkadiusz has already written about
earlier, regarding "display change history". If this function is active,
the function with search>bookmark>remove non-bookmarked lines does not
work. I am working on a 220 Mb file.

wt., 7 lis 2023 o 21:23 Don HO ***@***.***> napisał(a):
