### ISSUE TITLE
Static analysis in Notepad++

### ISSUE THREAD

**Issue by ariccio** [notepad-plus-plus/notepad-plus-plus#124]
In rejecting my Pull Request ([`Added a static analysis compatible config to the project`](https://github.com/donho/notepad-plus-plus/pull/13)), you said:

> I prefer to use an external analyzer than modify project's settings.

Can you elaborate? What kind of static analysis will you accept? `/analyze` comes with Visual Studio, and the modification in the Pull Request had a separate build config to prevent interference with normal development.

`/analyze` not only finds a multitude of bugs in Notepad++, but it has tremendous potential to improve Notepad++'s overall code quality, so there's very good reason to use it.

**Comment by ariccio** [comment]
Possibly interested parties:

@NN---

**Comment by rcdailey** [comment]
Obvious question, but have you tried [cppcheck](http://cppcheck.sourceforge.net/)?

**Comment by ariccio** [comment]
Kinda.....not on Notepad++, but I found that it had a very high noise-to-actual-bugs ratio.

Maybe I'll give it another try, but `/analyze` is lightyears better :)

**Comment by NN---** [comment]
There is also PVS Studio which analyzed Notepad++ a long time ago.
http://www.viva64.com/en/b/0131/#ID0EOAAG
But it costs a lot of money , maybe they have some special license for open source projects.

The point of static analyzer is not running it once for the old code but rather running it always for the better new code.
http://www.viva64.com/en/d/0218/

**Comment by pnedev** [comment]
+1 for static analysis

**Comment by ariccio** [comment]
> But it costs a lot of money , maybe they have some special license for open source projects.

They also offer `cppcat` which has most of the features of `PVS-Studio`, and is significantly cheaper. I've seriously considered buying it.....but I can't even get @donho to listen to the built in Visual Studio code analysis, so I haven't.

**Comment by ariccio** [comment]
> The point of static analyzer is not running it once for the old code but rather running it always for the better new code.

Personally, I'm a fan of turning it on by default for all builds. Yeah, compile times suffer, but code quality improves tremendously. You can even set up the analyzer to cause a build failure for annoying mistakes (e.g. bad arguments to a format string), which is pretty damned useful.

**Comment by ariccio** [comment]
....and since the article mention it, I want to take the opportunity to berate `CharUpper` & `CharLower` for being *extremely shitty* APIs.

No really, they're really poorly designed.

**Comment by ariccio** [comment]
Xref: https://github.com/donho/notepad-plus-plus/commit/2216c19dd06c9daeda6656b6f07a1d4ffc55cb0a

**Comment by ariccio** [comment]
@Croydon

**Comment by ariccio** [comment]
Xref: #123

**Comment by ariccio** [comment]
Xref: #125
