### ISSUE TITLE
NPPM_RELOADFILE doesn't return doReload() result

### ISSUE THREAD

**Issue by chcg** [notepad-plus-plus/notepad-plus-plus#12418]
### Description of the Issue
NPPM_RELOADFILE doesn't return changing BOOL as expectable by interface definition:

https://github.com/notepad-plus-plus/notepad-plus-plus/blob/4d5069280900ee249d358bc2b311bdb4b03f30a9/PowerEditor/src/MISC/PluginsManager/Notepad_plus_msgs.h#L136

https://github.com/notepad-plus-plus/notepad-plus-plus/blob/50a50cce3c0773e602e6cec344249349eacd6835/PowerEditor/src/NppBigSwitch.cpp#L520-L523

### Steps to Reproduce the Issue
1. Call NPPM_RELOADFILE  e.g. from pythonscript by `notepad.reloadFile(filename, False)`
2. Check result which is always FALSE

### Expected Behavior
result depends on return value of doReload() like e.g. NPPM_RELOADBUFFERID

### Actual Behavior
result is always FALSE

### Debug Information
Notepad++ v8.4.6   (64-bit)
Build time : Oct 12 2022 - 20:50:30
Path : C:\npp.8.4.6.portable.x64\notepad++.exe
Command Line : ""
Admin mode : OFF
Local Conf mode : ON
Cloud Config : OFF
OS Name : Windows 10 Home (64-bit) 
OS Version : 22H2
OS Build : 19045.2193
Current ANSI codepage : 1252
Plugins : 
    PythonScript (3.0.14)

**Comment by Ekopalypse** [comment]
Looks like this issue can be closed, implemented with [060396c](https://github.com/notepad-plus-plus/notepad-plus-plus/commit/060396c6988e278dbc10208099010947e72be6dc)

**Comment by chcg** [comment]
N++ 8.6.5 .
