### ISSUE TITLE
HTML coloring and autocompletion: "minlength" is missing

### ISSUE THREAD

**Issue by cinoyter** [notepad-plus-plus/notepad-plus-plus#12416]
### Description of the Issue
Hello! When writing an HTML file, the keyword "minlength" (see [https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/text#minlength](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/text#minlength) ) is missing from the text completion and colour scheme.

### Steps to Reproduce the Issue
1. Open a new buffer. Set the language to HTML.
2. Type the following line: `<input type="text" name="username" id="username" required minlength="2" maxlength="10">`

### Expected Behavior
Both "minlength" and "maxlength" should be highlighted as keywords (attribute names).

### Actual Behavior
Only "maxlength" is recognized as a keyword.
![image](https://user-images.githubusercontent.com/882511/198701471-492cebcf-c440-434b-83d0-8e8073d7a60d.png)

### Debug Information
Notepad++ v8.4.6   (32-bit)
Build time : Sep 25 2022 - 19:55:26
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Command Line : 
Admin mode : ON
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 10 Enterprise (64-bit) 
OS Version : 21H1
OS Build : 19043.2130
Current ANSI codepage : 1252
Plugins : 
    mimeTools (2.8)
    NppConverter (4.4)
    NppExport (0.4)

**Comment by alankilborn** [comment]
Confirmed.
