### ISSUE TITLE
Notepad++ always remove your javascript/scss/json/etc syntax highlighters

### ISSUE THREAD

**Issue by manuel-di-iorio** [notepad-plus-plus/notepad-plus-plus#1241]
if I set javascript as syntax highlighter for  .js and other extensions, Notepad will remove the association when you reopen Notepad++ or close/open the single file 

For some reasons, the html/xml association will stay but the others not.
Seems like the settings are saved only for the current session, but reloading the file will not take the syntax chosen..

Edit: the problem seems to come only when I open the file from the file explorer, instead if I open Notepad from a link in the start menu (set with admin rights) there is no issue. I'm on windows and I don't find an option to open the file (not Notepad, the .js file) with admin rights.

Is the problem related to the fact that the Notepad++ app is not in the main drive ?

**Comment by sanastasiou** [comment]
Do you have cloud settings?

**Comment by manuel-di-iorio** [comment]
No, however I reinstalled notepad in the main folder of the drive (E:) and now there are no problems. 
There is even another strange issue, if the app is not in the main folder, when associating notepad+ as "default program" to open the file, the system will not remember the association.. maybe a permissions problem. Meanwhile, I close this.
