### ISSUE TITLE
Add ability to separate "Dark Mode" from styling

### ISSUE THREAD

**Issue by vertigo220** [notepad-plus-plus/notepad-plus-plus#12427]
I have N++ set up the way I want it for the content area, using the Blackboard theme/style which is, to me, a good combination of dark with good syntax coloring, not to mention it has color templates configured for most languages. But the window itself (the menu and tool bars, tabs, status bar, etc) are still light-colored and therefore end up often being one of the brighter things on the screen. But if I switch to dark mode to fix this, not only do I have a difficult time getting those parts to look right, but it messes with the content area and completely ruins the look of that.

I'd like the ability to separately adjust the color of just the window elements, i.e. the areas surrounding the content area, independent of that area and the right pane (document map, etc). A setting to adjust only that while leaving everything else alone would be preferable to the current setup.

**Comment by ArkadiuszMichalski** [comment]
@vertigo220
So what's the problem after turning on Dark Mode once again switch to the Blackboard theme? Additionally you can customize the appearance of some elements of Notepad ++ itself in Dark Mode.

![image](https://user-images.githubusercontent.com/2730894/199058848-d4787db7-b1e3-464b-a6ae-39b5641dcf5a.png)

**Comment by vertigo220** [comment]
Ok, so that does work, and I can't believe I didn't try it, but I guess I just thought since enabling dark theme overrode that, which is configured separately, that it had priority over the style settings, which would mean messing with them wouldn't have an effect, so I didn't even try. After all, since that is controlled specifically by the style settings, it doesn't make sense to have it controlled elsewhere as well. I think it would make sense to at least have a setting in the dark theme section to not override the current style settings. Or, perhaps even better, have it ask when enabling it, since a setting could be missed and the style could be messed up by enabling dark mode without checking that setting first, a particular problem since disabling dark mode doesn't revert back to how things were (a whole other issue, though one that's apparently been decided it's somehow _not_ an issue).

I also thought at first when I did try changing it back to Blackboard that it wasn't the same as it was before. This was partially due to it appearing more blue vs the black it seemed to be before, and made me question if Blackboard was in fact the style I was using previously (another issue caused by the current setup, which is what if the user doesn't know/remember the style they were using) but it turns out that's just because of the contrast against the light vs dark of the rest of the app. Of course, if it hadn't messed with the style in the first place, I likely wouldn't have thought that and had to take screenshots of both and compare back and forth to make sure. So again, it would be better, IMO, to allow the user to limit the dark theme to N++'s border elements only and not make changes to the content areas.

**Comment by alankilborn** [comment]
>thought since enabling dark theme overrode that, which is configured separately, that it had priority over the style settings

This was my thinking as well.

While dark mode looks great (although I don't use it, except to experiment), its user interface controls seem a bit lacking.  I agree that having it as something controlled OUTSIDE of _Style Configurator_ makes little sense.  And the lack of inheriting from the operating system setting for it seems an omission.

**Comment by ArkadiuszMichalski** [comment]
This confusion comes from the fact that toggling `Enable dark mode` option does:
- when ON always change theme to Dark Mode Default
- when OFF always change theme to Default (stylers.xml)

So you have to remember that if you switch `Enable dark mode`  and you want to use a different theme then you have to select it again. This behawior is reasonable for less advanced users as the rest of the included themes don't have a dark mode variant, and they might then think that this option doesn't work well (appearance is inconsistent).

I would suggest add some info that toggling `Enable dark mode` always change theme as above.  And for more advanced also add option to not switch theme when toggling this option, because having to reselect theme is annoying.

@vertigo220 Dark mode is a fairly young option (although a long awaited one) and some inconsistencies may appear). 

@ozone10 This behawior for changing `Inactive tabs` through `Style Configurator` when `Dark mode` is on is intentional? I mean that changing background color does nothing, and foreground color is opposite (white is black and black is white). Same if for `Active tab text`. This is a bit confusing.

**Comment by vertigo220** [comment]
In addition to your suggestions, another possibility would be to simply remember the active theme when enabling it and ask the user when they disable it if they'd like to revert back to the previous theme. Though I'm having a hard time understanding why it would be confusing or undesirable to not do so.

I realize it's new, and so am not surprised to find issues with it. And certainly, even with those issues, it's a welcome change. But, of course, it's always best to point out those issues so they can be resolved and the feature improved.

Speaking of which, dark mode would also benefit from providing better descriptions of what the items under the "Customized" option do. I spent a while going through the annoying process of adjusting some of them to try and figure out what they do, since the names aren't very descriptive and there are no tooltips, only to find not all of them even seem to have any effect, possibly for the same reason, whatever that may be, that trying to change the tab colors didn't work correctly.

I'm not sure which options affect it; in fact, I don't think any of the ones that can be adjusted in the dark mode settings window do. I just know that when I enabled it, that area changed, and so I had to do as you suggested and go back into styles to change it back to Blackboard to put that area back how it was. It's probably just the various settings in the dark mode style. And that's part of the confusion: there are several customizable components of dark mode in its settings window, yet none of them appear to affect that, so when it's suddenly changed, this is unexpected because it doesn't look like dark mode would have an effect on that area, due to the available options there, and it's confusing because there's no readily apparent way to readjust it. Nothing matches up to expectations and it's all designed in a fragmented, conflicting way.

**Comment by ozone10** [comment]
@ArkadiuszMichalski 
I did not write code for tab background, but IIRC dark mode ignores tab background color (not only inactive tabs) setting from style configurator and invert color for text. 

I would like to rewrite logic behind this as it cause issue with text visibility with some combination of colors, there is open issue for it.
I would also like to add setting to not change theme/style, toolbar icons and tab icons when toggling dark mode.

Unfortunately I don't have time until next year, I am really busy IRL.

**Comment by CennoxX** [comment]
The issue in the first post is solved. For other mentioned problems inside this thread, separate issues should be created, but some should also be solved with #12466, probably coming with the next release. So this issue should be closed.

**Comment by donho** [comment]
https://github.com/notepad-plus-plus/notepad-plus-plus/commit/e2a1234384cbbe0665baee77b1abfee985c1c5d8
