### ISSUE TITLE
Searching dropdown controls need vertical scrollbars in dropdown area

### ISSUE THREAD

**Issue by alankilborn** [notepad-plus-plus/notepad-plus-plus#12459]
### Description of the Issue
Many times I "drop down" the _Find what_ combobox control, looking for a previous search that I know I did, and what I'm looking for doesn't seem to be there.  Shrug, move on, retype that search term...

But, recently I got frustrated because I _knew_  my search term _should_ have been there, so I dug in and got to the bottom of this problem.

### Steps to Reproduce the Issue

1. It is easiest to create the problem by using a fresh extract of a portable N++, so that the following steps will work exactly.
2.  Open the _Find_ window with Ctrl+f.
3.  Put `a` in _Find what_; press Enter to do a _Find Next_. Put `b` in _Find what_; press Enter to do a _Find Next_. Put `c` in _Find what_; press Enter to do a _Find Next_. Continue to put sequential letters of the alphabet and pressing Enter after, up to and including `z`. Put `1` in _Find what_; press Enter to do a _Find Next_. Put `2` in _Find what_; press Enter to do a _Find Next_. Continue with sequential digits and conclude with `0` (zero), remembering to press Enter after each one.
4. The goal of the previous step is to have `a` in the oldest history (bottom entry in the dropdown when it is actually dropped) and `0` (zero) as the newest history (topmost entry in the dropdown when it is actually dropped).
5. Put `k` in _Find what_ (don't press Enter) and use the combobox's arrow to "drop it down"; observe:

![image](https://user-images.githubusercontent.com/77065706/199739406-b9000d3c-2af7-4a33-9055-a0b5adfe6ebd.png)

6. Point to the dropped area with the mouse, say where the yellow dot is shown.  Use the mouse wheel to hopefully scroll.
7. Use the keyboard up arrow repeatedly to move above the `4` entry a the top of the dropped box area.  View that `5`, `6`, `7` etc. become visible after repeated up arrow presses (proving that more data than originally shown is there):

![image](https://user-images.githubusercontent.com/77065706/199739767-468a3e73-e602-48dd-a059-bbab12bd0994.png)

### Expected Behavior

(At the time of the first screenshot above) I expect to see ALL possible choices in the initial dropping of the combobox, or I expect to see a scrollbar so that I can see there are more values that are simply out of my current view.  Also, rotating the mouse wheel should scroll the box to show more entries.

### Actual Behavior

(At the time of the first screenshot above) What I actually saw is misleading because it makes me think that I'm looking at all possible choices, when there are actually some I'm not being shown (the ones above the top displayed one).  Scrolling the mouse wheel does nothing to bring unshown entries into view.

### Debug Information
Notepad++ v8.4.6   (32-bit)
Build time : Sep 25 2022 - 19:55:26
Path : C:\\...\npp.8.4.6.portable\notepad++.exe
Command Line : -multiInst
Admin mode : OFF
Local Conf mode : ON
Cloud Config : OFF
OS Name : Windows 10 Enterprise (64-bit) 
OS Version : 21H2
OS Build : 19044.2006
Current ANSI codepage : 1252
Plugins : 
    mimeTools (2.8)
    NppConverter (4.4)
    NppExport (0.4)

**Comment by alankilborn** [comment]
I believe adding `| WS_VSCROLL` to this line solves the problem for the _Find what_ combobox:

https://github.com/notepad-plus-plus/notepad-plus-plus/blob/f3f615d52252439b56dd62446a29e2ea5af456ca/PowerEditor/src/ScintillaComponent/FindReplaceDlg.rc#L27

**Comment by alankilborn** [comment]
Indeed, adding in `WS_VSCROLL makes it obvious that there are more entries than shown (scrollbar wouldn't appear otherwise), and I can clearly see the unshown entries are _above_ the top of what is shown (see all the space above the thumb that I've highlighted in bright green):

![image](https://user-images.githubusercontent.com/77065706/199755846-0ea53fa7-ac91-4164-9ddd-58c496d9b8e4.png)

**Comment by Yaron10** [comment]
@alankilborn,

👍 
Thank you.

**Comment by alankilborn** [comment]
>Thank you.

I know, right...
The feature you maybe never realized you needed.
You realized something was a bit "off" but could never figure out what it was...
(I'm describing my own experience with this)

**Comment by Yaron10** [comment]
I think I've never had the required number of entries to notice the issue. :)
Nice catch!

Thanks again.

**Comment by alankilborn** [comment]
@ArkadiuszMichalski Do you have interest in this issue?  Enough for you to do the PR for it?  I'm not currently set up to do PRs of my own.  But I think this is (a) very valuable and (b) very easy to implement.

**Comment by ArkadiuszMichalski** [comment]
@alankilborn OK, I'll create the appropriate PR.

**Comment by ArkadiuszMichalski** [comment]
@alankilborn `WS_VSCROLL` should not be add for all `COMBOBOX` (4 elements) ?

**Comment by alankilborn** [comment]
It is most important for _Find what_ combobox, secondarily for _Replace with_.  But really, why not add to all comboboxes in the _Find_ family of windows?
