### ISSUE TITLE
Update galician.xml to 8.4.6

### ISSUE THREAD

**Issue by conky77** [notepad-plus-plus/notepad-plus-plus#12463]
### Description of the Issue

Update galician.xml to 8.4.6

File originally uploaded in #12440 from @P0rsche-911
(See also #10742 and #12336 )

[galician.zip](https://github.com/notepad-plus-plus/notepad-plus-plus/files/9932909/galician.zip)

**Comment by conky77** [comment]
@donho Galician.XML hasn't been updated for years, and @P0rsche-911 would like to update it. 
He created issue #10742 one year ago, but he hasn't been able to update the file yet.
He is not very confident with PR (Pull Request) and speaks Spanish).
The original galician.xml contains different styles (For example, every paragraph uses another character for indentation).
In order to facilitate the updating, is it possible to format the original file with the same style indentation (or tab or 4 spaces)?
Does he also have to keep the original author's header?

**Comment by P0rsche-911** [comment]
[galician.xml](https://github.com/notepad-plus-plus/notepad-plus-plus/blob/master/PowerEditor/installer/nativeLang/galician.xml) last translation on November 22, 2011

The reference file has been english.xml, version 8.4.6. They are identical except for the translations.

![Notepad++ galego](https://user-images.githubusercontent.com/93552629/199959385-7537952c-31c2-4b25-bed5-0c666dc063ad.PNG)
![Notepad++ inglés](https://user-images.githubusercontent.com/93552629/199959392-75f892cc-e598-4a31-b4f2-2c8654378aa6.PNG)

**Comment by donho** [comment]
@conky77 
Thank you for your explanation.

@P0rsche-911 
Will you maintain the `galician.xml` in the future?

**Comment by conky77** [comment]
@P0rsche-911 
if you activate the button "mostrar todos los caracteres" you can see the differences: the original file use sometimes TAB, sometimes 4 spaces. You used almost always TAB. It would be better to have only one style in the entire file.
![immagine](https://user-images.githubusercontent.com/59116246/200050597-acc05519-2ba6-4622-81f1-7aebeb225b2f.png)

**Comment by P0rsche-911** [comment]
> @conky77 Thank you for your explanation.
> 
> @P0rsche-911 Will you maintain the `galician.xml` in the future?

It is possible. But keep in mind that I am inexperienced in these matters. I can make mistakes because I don't know about programming/computing.
Thank you very much for your offer.

Es posible que sí. Pero tenga en cuenta que soy inexperto en estos temas. Puedo cometer errores por no saber de programación/informática.
Muchas gracias por su ofrecimiento.

**Comment by P0rsche-911** [comment]
> @P0rsche-911 if you activate the button "mostrar todos los caracteres" you can see the differences: the original file use sometimes TAB, sometimes 4 spaces. You used almost always TAB. It would be better to have only one style in the entire file, but to do that, Don-Ho has to accept. ![immagine](https://user-images.githubusercontent.com/59116246/200050597-acc05519-2ba6-4622-81f1-7aebeb225b2f.png)

This information is very important to me. I was unaware of this detail. I check everything again to make it identical to the english.xml file.

Esta información es muy importante para mí. Desconocía este detalle. Vuelvo a revisar todo para que sea idéntico al archivo english.xml.

**Comment by conky77** [comment]
> It is possible. But keep in mind that I am inexperienced in these matters. I can make mistakes because I don't know about programming/computing. Thank you very much for your offer.
@P0rsche-911 
In my opinion, the answer you gave to Don-Ho, in English, it is not very clear. It sounds "maybe" or "no sé". It's not clear if you accept or not.

**Comment by conky77** [comment]
If you decide to use 4 spaces, you could activate this option:

![immagine](https://user-images.githubusercontent.com/59116246/200107592-aca55bfc-88ee-442a-ae9e-a559cd248ca1.png)

To convert tab-->4 spaces


![immagine](https://user-images.githubusercontent.com/59116246/200107819-762bba56-e530-435f-9087-50c75ec8da20.png)

**Comment by P0rsche-911** [comment]
@conky77 Thank you very much for all your help.
I think I have left the file identical to the english.xml file.
I have used the "TAB to space" option, as recommended.
It is impossible for me to upload the galician file in .xml format. I have to upload it in .zip format.

Muchas gracias por toda su ayuda.
Creo haber dejado el archivo idéntico al fichero english.xml
He usado la opción "TAB a espacio", tal y como me recomienda.
Me es imposible subir el fichero galician en formato .xml. Lo tengo que subir en formato .zip.
[galician.zip](https://github.com/notepad-plus-plus/notepad-plus-plus/files/9944397/galician.zip)

If someone can pass the spanish translation to the coloborators, because I don't know how to contact them.

Si alguien le puede pasar la traducción al español a los coloboradores, ya que no sé cómo contactar con ellos.
[spanish.zip](https://github.com/notepad-plus-plus/notepad-plus-plus/files/9944399/spanish.zip)

Thanks to all and excuse my inexperience.

**Comment by P0rsche-911** [comment]
> > It is possible. But keep in mind that I am inexperienced in these matters. I can make mistakes because I don't know about programming/computing. Thank you very much for your offer.
> 
> @P0rsche-911 In my opinion, the answer you gave to Don-Ho, in English, it is not very clear. It sounds "maybe" or "no sé". It's not clear if you accept or not.

I would be happy to do so.
If I have doubts, it is because my inexperience will cause me to make mistakes, something I do not want to do. Also, keep in mind that I need to use deepl.com to communicate in the forum and my knowledge of programming languages is very limited, almost null.
If you trust me, go ahead. I ask not to be scolded too much.
Thanks for trusting me.

Lo haría encantado.
Si tengo dudas es porque mi inexperiencia me hará cometer errores, algo que no deseo. Además, tengan en cuenta que necesito usar deepl.com para comunicarme en el foro y mis conocimientos de lenguajes de programación son muy limitados, casi nulos.
Si confían en mí, adelante. Pido que no me regañen mucho.
Gracias por confiar en mí.

**Comment by conky77** [comment]
> @conky77 Thank you very much for all your help. I think I have left the file identical to the english.xml file. I have used the "TAB to space" option, as recommended. It is impossible for me to upload the galician file in .xml format. I have to upload it in .zip format.
> 
> Muchas gracias por toda su ayuda. Creo haber dejado el archivo idéntico al fichero english.xml He usado la opción "TAB a espacio", tal y como me recomienda. Me es imposible subir el fichero galician en formato .xml. Lo tengo que subir en formato .zip. [galician.zip](https://github.com/notepad-plus-plus/notepad-plus-plus/files/9944397/galician.zip)
> 
> If someone can pass the spanish translation to the coloborators, because I don't know how to contact them.
> 
> Si alguien le puede pasar la traducción al español a los coloboradores, ya que no sé cómo contactar con ellos. [spanish.zip](https://github.com/notepad-plus-plus/notepad-plus-plus/files/9944399/spanish.zip)
> 
> Thanks to all and excuse my inexperience.

This issue is for Galician. Please create a new "issue" only for Spanish.xml . 
Before to do that, consider that the version 8.4.7 is coming (see #12404 and [the preview here](https://community.notepad-plus-plus.org/topic/23696/notepad-v8-4-7-release-candidate) )
Once you have done this, add to [your post in the community](https://community.notepad-plus-plus.org/topic/22072/translation-spanish-lng-latest-version/4) the reference to the new Spanish "issue". Please continue the Spanish topic in the Community.

**Comment by P0rsche-911** [comment]
galician.xml updated to version 8.4.7. I used the english.xml file from [the repository](http://download.notepad-plus-plus.org/repository/8.x/8.4.7.RC/) as a reference.
[galician.zip](https://github.com/notepad-plus-plus/notepad-plus-plus/files/9946614/galician.zip)

**Comment by conky77** [comment]
@P0rsche-911 let me know if you can create the file with the first step Don Ho asked for. 
I suppose that Don Ho will use software like XmlTreeNav (comparing the current galician.xml and the new galician.xml) to check the row you will have deleted and which you will have added. It is more difficult to check if the old entries have a different format.
Once you have done, you can upload the file here, and if you want, I can check if the file is ok. After that, I can help you to make the first Pull request.

**Comment by P0rsche-911** [comment]
I'm sorry, but I don't quite understand what I have to do.
The galician.xml file is identical to the english.xml file of version 8.4.7 portable. Spaces, TAB, without removing or putting lines, exactly the same. I don't understand what you are asking me. Or at least attach an image of what I have to correct.
The current galician.xml file is more than 10 years old, should I use it as a reference?

Sorry for my inexperience

Lo siento, pero no termino de entender lo que tengo que hacer.
El archivo galician.xml es idéntico al archivo english.xml de la versión 8.4.7 portable. Espacios, TAB, sin quitar ni poner líneas, exactamente igual. No entiendo lo que me piden. O por lo menos adjunten una imagen de lo que debo corregir.
El archivo galician.xml actual es de hace más de 10 años. ¿Debo usarlo como referencia?

Perdonen mi inexperiencia

**Comment by donho** [comment]
@P0rsche-911 
I think you should take time to learn how to do the PR by checking other localization translation PR.
Submitting a localization PR is not about only translation, but know how to work and a lot of tests.

**Comment by conky77** [comment]
@P0rsche-911
Let's move the discussion to the community. Next week-end I will prepare the file as Don Ho asked and I and others people will give you the training he suggested you.

@donho 
For the first Pull request, could we also modify the previous translation or do you prefer a different PR for that?

Do you prefer that?
1. adding new item, deletion item, reordering
2. formatting
3. modifing items

**Comment by donho** [comment]
@conky77 
As a integrator, I always need to know what's been added, removed and modified.
In [contribution rules](https://github.com/notepad-plus-plus/notepad-plus-plus/blob/master/CONTRIBUTING.md#guidelines-for-pull-requests) it has been said, I say it again here: `PR of reformatting (changing of ws/TAB, line endings or coding style) of source code won't be accepted... In short: The easier the code review is, the better the chance your pull request will get accepted.`

I do understand that translator needs to do the formatting, so once the first step above has been done, translator can do the formatting and reordering thing - this should be done once for all.

I hope I make it clear.

**Comment by P0rsche-911** [comment]
Sorry to disturb.
What is the reference file used to compare with the translation?

Latest version of english.xml or galician.xml?

**Comment by P0rsche-911** [comment]
@conky77  Thank you very much for all your help. I need to first learn how to do this double numbering thing to show the changes:

Muchas gracias por toda tu ayuda. Necesito aprender primero a saber cómo se hace esto de la doble numeración para mostrar los cambios:
![Notepad++ alemán](https://user-images.githubusercontent.com/93552629/201219350-cb2ba420-e8f7-4a05-899c-c9c3f97cfe26.PNG)

**Comment by conky77** [comment]
@P0rsche-911 please write your question [here in the community](https://community.notepad-plus-plus.org/topic/22072/translation-spanish-lng-latest-version/7)
