### ISSUE TITLE
Remove Empty Lines is almost unusable so slow

### ISSUE THREAD

**Issue by Nuklon** [notepad-plus-plus/notepad-plus-plus#12462]
### Description of the Issue
If you have a large document with several thousand (most empty, some not) lines: Use Edit > Line Operations > Remove Empty Lines, the program freezes for a long time as it takes forever to complete. A workaround is to first remove duplicate lines (which is very fast) and then remove the remaining empty line(s) manually.

### Steps to Reproduce the Issue

1. Have a large document 2000+ lines, with say 80% empty lines (mostly \r\n, some with a space).
2. Edit > Line Operations > Remove Empty Lines.
3. This takes a long, long time.

### Expected Behavior
Should be quick.

### Actual Behavior
Is slow.

### Debug Information
Notepad++ v8.3   (64-bit)
Build time : Feb  3 2022 - 03:39:05
Path : D:\Notepad++\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : ON
Cloud Config : OFF
OS Name : Windows 10 Pro (64-bit) 
OS Version : 2009
OS Build : 19044.2130
Current ANSI codepage : 1252
Plugins : JSMinNPP.dll mimeTools.dll NppConverter.dll NppExport.dll

**Comment by ArkadiuszMichalski** [comment]
Please add some file for test where such problem could be reproduce.

**Comment by Nuklon** [comment]
Here:
[bug.txt](https://github.com/notepad-plus-plus/notepad-plus-plus/files/9995281/bug.txt)

**Comment by ArkadiuszMichalski** [comment]
@Nuklon Could you check build from this [PR](https://github.com/notepad-plus-plus/notepad-plus-plus/pull/12512) if it's faster?

**Comment by Nuklon** [comment]
I downloaded the exe from Environment: compiler=MSC, platform=x64; Configuration: Release and wow, what a difference! It's now almost instantaneously. Great work 🎉
