### ISSUE TITLE
Commands don't change color in Powershell (In Notepad++)

### ISSUE THREAD

**Issue by GabrielFrigo4** [notepad-plus-plus/notepad-plus-plus#12465]
When I write batch code, always the first word has a different color representing a command, even if it's not in a command list, I think that's pretty cool. But this doesn't happen when I create a PowerShell script, and if the command starts with a number, the number is in a different color than the rest of the command in PWSH. Is there any way I can fix this on my PC locally or does it have to be updated in Notepad++?

Batch:
![image](https://user-images.githubusercontent.com/66432268/200091857-80868ef3-e2f4-4b22-b878-efa3cbeb5507.png)
Powershell:
![image](https://user-images.githubusercontent.com/66432268/200091886-fb624a4c-59de-4f14-b01d-0699ac803b0d.png)

**Comment by ArkadiuszMichalski** [comment]
Batch and Powershell use separate lexer. Batch has something like `COMMAND` (which can match any name), but for Powershell there is no such thing (there are separate styles only for specifically defined keywords). You can play with this through `Setting > Style Configurator...`.

You can manually add some commands if they are missing and you want colors for them.

**Comment by GabrielFrigo4** [comment]
> Batch and Powershell use separate lexer. Batch has something like (which can match any name), but for Powershell there is no such thing (there are separate styles only for specifically defined keywords). You can play with this through .`COMMAND``Setting > Style Configurator...`
> 
> You can manually add some commands if they are missing and you want colors for them.

Works with all the names I put, except the 7z (probably because it starts with number):
![image](https://user-images.githubusercontent.com/66432268/201713673-f1528565-2b86-49d5-bff2-103ab8a790dc.png)

**Comment by ArkadiuszMichalski** [comment]
>Works with all the names I put, except the 7z (probably because it starts with number):

Yes, if you want this notation to also be compared with the defined words, you should report it in the [Lexilla project](https://github.com/ScintillaOrg/lexilla) for `LexPowerShell.cxx` lexer.

**Comment by GabrielFrigo4** [comment]
mkdir is a default powershell alias and it is not in the notepad++ powershell alias list

**Comment by GabrielFrigo4** [comment]
> > Works with all the names I put, except the 7z (probably because it starts with number):
> 
> Yes, if you want this notation to also be compared with the defined words, you should report it in the [Lexilla project](https://github.com/ScintillaOrg/lexilla) for `LexPowerShell.cxx` lexer.

I added 'lib' and 'link' as alias, I think when it has a dot or a bar before or after it was not for the alias to continue being griffind
![image](https://user-images.githubusercontent.com/66432268/201749711-0cc49354-966f-4e60-8a1d-7f45b6f1aa3d.png)
