### ISSUE TITLE
Printing gives colored background on paper

### ISSUE THREAD

**Issue by mbeltoft** [notepad-plus-plus/notepad-plus-plus#12478]
### Description of the Issue

When I print from Notepad++ I get orange background for lines marked with orange in left margin in editor.
I'm not familiar with that feature, but appears to mark changed lines since last save.
When I save the file the margin marking turns green and prints green on paper.
This is not controlled by Settings / Print / Colour Options. Both "No background color" and "WYSIWYG" prints this color.

### Steps to Reproduce the Issue

1. Paste some text (marked orange in margin)
2. Print page
3. Orange background on paper for all lines of text

### Expected Behavior

Normal print of text with no background color.

### Actual Behavior

Printed text has colored background that follows the marking in the left border in the editor.

### Debug Information

Notepad++ v8.4.6   (64-bit)
Build time : Sep 25 2022 - 19:51:39
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 10 Pro (64-bit) 
OS Version : 21H2
OS Build : 19044.2130
Current ANSI codepage : 1252
Plugins : 
    mimeTools (2.8)
    NppConverter (4.4)
    NppExport (0.4)

**Comment by ArkadiuszMichalski** [comment]
This was fixed in 8.4.7.

**Comment by mbeltoft** [comment]
Oh - the auto updater had not given me that version yet.
But yes a manual update removed the problem.
Thanks!
