### ISSUE TITLE
Sort Lines Lexicographically broken

### ISSUE THREAD

**Issue by Phergus** [notepad-plus-plus/notepad-plus-plus#12475]
### Description of the Issue

Using Line Operations -> Sort Lines Lexicographically not working.  Appears to be not like JSON fields.

### Steps to Reproduce the Issue
1. Load attached theme.text file.
2. Select the content and then select Line Operations -> Sort Line Lex. Ascending
3. Does not sort the content.

[theme.txt](https://github.com/notepad-plus-plus/notepad-plus-plus/files/9963098/theme.txt)

### Expected Behavior
This used to work

### Actual Behavior
Sometimes when it is just a few lines it will change the order but not correctly and sometimes insert a blank line.

### Debug Information
Notepad++ v8.4.6   (64-bit)
Build time : Sep 25 2022 - 19:51:39
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : "D:\mydocs\Gaming\configJavaOptions.txt"
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 10 Home (64-bit) 
OS Version : 22H2
OS Build : 19045.2130
Current ANSI codepage : 1252
Plugins : 
    ComparePlugin (2.0.2)
    JsonTools (3.2)
    mimeTools (2.8)
    NppConverter (4.4)
    NppExport (0.4)
    NPPJSONViewer (1.41)
    NppToolBucket (1.10.6622.41516)

**Comment by alankilborn** [comment]
You have mixed line-ending types in your file:

![image](https://user-images.githubusercontent.com/77065706/200665614-89fba48c-a3c6-4e31-8140-c0a9f06fe038.png)

Reference #7735

Close as duplicate (leaving 7735 as the master issue)?

**Comment by Phergus** [comment]
So it does.  Closing as duplicate.

**Comment by sunk818** [comment]
I experience this issue as well. If files off GitHub is Unix lined ending (LF only), I can not get it to sort  Lexicographically ascending. If I copy & paste into a new document that is Windows (CR LF), then it will sort correctly. This used to work for me as well. It seems to only happen upon when I first open Notepad++. After I create a new document, get that to sort correctly, then other documents sort even if it Unix (LF).
