### ISSUE TITLE
New instance is not restored after re-opening notepad++

### ISSUE THREAD

**Issue by idopycl** [notepad-plus-plus/notepad-plus-plus#12470]
### Description of the Issue

When dragging a tab with a file to another location, a new instance is opened.
When quitting notepad++ and later on running it again, the opened file at the original new instance is not in the opened tabs, and no new instance with the opened file is executed.

### Steps to Reproduce the Issue

1. Drag an existed saved file to a different location.
2. Wait for a new instance with that file was created.
3. Quit notepad++.
4. Run notepad++ again.

### Expected Behavior

Either a single instance with the opened file should be loaded, or a new instance with the opened file.

### Actual Behavior
The file was not restored on opening, and it is "lost" to notepad++.

### Debug Information

    Notepad++ v8.4.6   (64-bit)
    Build time : Sep 25 2022 - 19:51:39
    Path : C:\Program Files\Notepad++\notepad++.exe
    Command Line : "C:\Users\USER_PC\Desktop\xxxxx\xxxxxxxxxyyyy.txt"
    Admin mode : OFF
    Local Conf mode : OFF
    Cloud Config : OFF
    OS Name : Windows 10 Pro (64-bit) 
    OS Version : 22H2
    OS Build : 19045.2193
    Current ANSI codepage : 1255
    Plugins : 
        AutoCodepage (1.2.4)
        AutoEolFormat (1.0.2)
        BracketsCheck (1.2.2)
        CodeAlignmentNpp (14.1.107)
        ColumnTools (1.4.4.1)
        ComparePlus (1)
        CSVLint (0.4.5.4)
        CsvQuery (1.2.9)
        DSpellCheck (1.4.24)
        GotoLineCol (2.4.2)
        HexEditor (0.9.12)
        HTMLTag (1.3.5)
        JsonTools (3.2)
        mimeTools (2.8)
        nppAutoDetectIndent (2.3)
        NppConverter (4.4)
        NppEditorConfig (0.4)
        NppExport (0.4)
        NPPJSONViewer (1.41)
        nppRandomStringGenerator (1.4)
        NppSnippets (1.7)
        NppXmlTreeviewPlugin (2)
        Python Indent (1.0.0.4)
        PythonScript (2)
        RandomValuesNppPlugin (0.2.1)
        urlPlugin (1.2)
        XMLTools (3.1.1.13)

**Comment by alankilborn** [comment]
>Drag an existed saved file to a different location.

Hold Ctrl while doing this (the file will remain in the original instance so that when Notepad++ is restarted, it will still be there).

>...and no new instance with the opened file is executed.

It is not in the design that multiple-instance status is remembered over runs of Notepad++.

**Comment by idopycl** [comment]
Thank you

**Comment by alankilborn** [comment]
@idopycl 

Please close this issue.
