### ISSUE TITLE
Linebreak (LF and/or CR) are highlighted as error in JSON

### ISSUE THREAD

**Issue by Klimmbimmel** [notepad-plus-plus/notepad-plus-plus#12476]
### LF and/or CR are highlighted as error in JSON
As [RFC 4627](https://www.rfc-editor.org/rfc/rfc4627#section-2) shows, LF and CR are allowed at any position in a JSON.

### Steps to Reproduce the Issue
Put the following 2 lines in a .json file. let's call this Version A:
`{'id': 1,
'name': 'Mr. Meeseeks'}` 

For comparison use the following version B:
`{ 'id'   : 1,	 	  'name ': 'Mr. Meeseeks'	 	}`

### Expected Behavior
Version A should not be highlighted as error as is version B.

### Actual Behavior
Version A is highlighted as error (which is yellow on red for me), while version B isn't (which is correct).

### Debug Information
Notepad++ v8.4.6   (64-bit)
Build time : Sep 25 2022 - 19:51:39
Command Line : 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 10 something (64-bit) 
OS Version : 21something
OS Build : 19044.something
Current ANSI codepage : 1252
Plugins : none

**Comment by rdipardo** [comment]
Code highlighting is provided by a third-party module.
Problems with it should be sent to https://github.com/ScintillaOrg/lexilla/issues

**Comment by ArkadiuszMichalski** [comment]
>Well... seems like using double quotation marks fixes this... and seems like apostrophe aka. single quote is not valid JSON... but then also Version B should be highlighted as error.

And also Version B is highlighted as error. Valid JSON requires `""` for strings.
![image](https://user-images.githubusercontent.com/2730894/200690956-f1f35f11-5fef-42c3-a66a-66799aba97e3.png)
