### ISSUE TITLE
Make Word wrap default

### ISSUE THREAD

**Issue by jgentes** [notepad-plus-plus/notepad-plus-plus#12479]
I think for many users the first time they interact with Notepad++ they are copying/pasting something, only to discover that it's unreadable because it extends beyond the length of the screen. I would question:

1. What value does extending content beyond the screen provide to the 80% of users? (I acknowledge here that there's probably a 20% of cases where this might make sense)
2. Why not default to wrap, which is what I think 95% of users would expect?

**Comment by alankilborn** [comment]
Defaults for long-existing features aren't going to be changed.
Please close this issue.

**Comment by jgentes** [comment]
Ah, the `that's the way it's always been, therefore` argument.

**Comment by alankilborn** [comment]
>Ah, the that's the way it's always been, therefore argument.

Well, it actually IS an important thing, when you have the number of users Notepad++ has, and those users really get riled up if such a default is changed.

I could have cited other reasons for not having word-wrap enabled by default, but I'm sure they wouldn't convince you, and, well, the one I cited is probably the overwhelming one anyway.

**Comment by aelfwyne** [comment]
So annoying, such a basic feature and not even a discussion of allowing users to change the default. Lack of a default wordwrap on TXT files even, extremely annoying.
