### ISSUE TITLE
long hyperlinks truncated

### ISSUE THREAD

**Issue by kurtseebauer** [notepad-plus-plus/notepad-plus-plus#1248]
Hi,

I have a text-file with some very long hyperlinks. I can follow those links with a double click in notepad++, but they are cut off at a limit of 519 characters. Since there is no official size limit for links or parameters, notepad++ should support links of any length. 

Tested with Version 6.8.8.

**Comment by sanastasiou** [comment]
Could you post here such a hyperlink for testing purposes? :) thanks.

**Comment by kurtseebauer** [comment]
of course, try this one: 
http://localhost:8080/SaveEntscheidungen?uid=1&gameid=1&formname=L1P1&periode=3&BrilleP3=400%2C00&Radiospot=1&Mobile=1&Zeitungsanzeige=1&Glaeserpaar=1.500&Kunststoffgranulat=1.500&feAusgaben=30.000&Anteilguid_FEEigenschaft_Technik_P3=50%2C0&Anteilguid_FEEigenschaft_Design_P3=50%2C0&kauf_anlage_BGA_BGA_P3=0&kauf_anlage_TAM_3D-Druckmaschine_P3=0&kauf_anlage_TAM_3D-Druckmaschine_nG_P3=1&Produktionsmenge_BrilleP3=1.500&einstellungenProduktion=2%2C0&entlassungenProduktion=0%2C0&einstellungenVertrieb=2%2C0&entlassungenVertrieb=0%2C0&einstellungenVerwaltung=2%2C0&entlassungenVerwaltung=0%2C0&kredit_name_kurzfristiger_Kredit=0%2C00&kredit_name_langfristiger_Kredit=0%2C00&finanzanlage_name_finanzanlage_kurzfristig_p3=0%2C00&verkauf_anlagevermoegenAV_TAM_3D-Druckmaschine_U1_date-24lfd_nr0=nutzen&verkauf_anlagevermoegenAV_TAM_3D-Druckmaschine_U1_date6lfd_nr0=nutzen&verkauf_anlagevermoegenAV_TAM_3D-Druckmaschine_U1_date6lfd_nr1=verkaufen&verkauf_anlagevermoegenAV_BGA_BGA_U1_date-24lfd_nr0=nutzen&verkauf_anlagevermoegenAV_BGA_BGA_U1_date-24lfd_nr1=nutzen&verkauf_anlagevermoegenAV_BGA_BGA_U1_date-24lfd_nr2=nutzen&verkauf_anlagevermoegenAV_BGA_BGA_U1_date-24lfd_nr3=nutzen&verkauf_anlagevermoegenAV_BGA_BGA_U1_date-24lfd_nr4=nutzen&verkauf_anlagevermoegenAV_BGA_BGA_U1_date-24lfd_nr5=nutzen&verkauf_anlagevermoegenAV_BGA_BGA_U1_date-24lfd_nr6=nutzen&verkauf_anlagevermoegenAV_BGA_BGA_U1_date-24lfd_nr7=nutzen&verkauf_anlagevermoegenAV_BGA_BGA_U1_date-24lfd_nr8=nutzen&verkauf_anlagevermoegenAV_BGA_BGA_U1_date-24lfd_nr9=nutzen&verkauf_anlagevermoegenAV_BGA_BGA_U1_date6lfd_nr0=nutzen&verkauf_anlagevermoegenAV_BGA_BGA_U1_date6lfd_nr1=nutzen&verkauf_anlagevermoegenAV_BGA_BGA_U1_date12lfd_nr0=nutzen&verkauf_anlagevermoegenAV_BGA_BGA_U1_date12lfd_nr1=nutzen&verkauf_anlagevermoegenAV_BGA_BGA_U1_date12lfd_nr2=nutzen&verkauf_anlagevermoegenAV_LIZENZ_Softwarelizenz_U1_date-30lfd_nr0=nutzen

you will find that only the first 519 characters arrive at localhost.

**Comment by kurtseebauer** [comment]
Thanks, GoodNike, for the fix. Great response time! I will retest with the next binary release.

**Comment by sanastasiou** [comment]
It has to be merged first but I see no reason why it wouldn't  ..

**Comment by GoodNike** [comment]
Thanks glad to hear it ;)

**Comment by kurtseebauer** [comment]
will this fix be merged into the next version? I see it is still "open".
