### ISSUE TITLE
Custom toolbar custom buttons getting messed up randomly

### ISSUE THREAD

**Issue by ScienceDiscoverer** [notepad-plus-plus/notepad-plus-plus#12486]
I made a bunch of custom buttons with custom icons using the Custom Toolbar plugin. I positioned them as I see fit in the toolbar. However, after relaunching Notepad++ the toolbar randomly breaks sometimes. With all the icons (even standard ones) getting randomly interchanged and buttons changing positions. After relaunching Notepad++ from 5 to 10 times it sometimes fixes itself. But restarting it once again breaks everything.

Is this only me or somebody else have this problem? Can this be fixed?

**Comment by alankilborn** [comment]
Plugins are not "associated" with Notepad++.  Anyone can make a plugin.  As such, Notepad++ core is not responsible for tech support on all possible plugins.  Suggest you find the place where your plugin is supported, and pursue questions/problems on that site.

Please close this issue.

**Comment by ArkadiuszMichalski** [comment]
@ScienceDiscoverer Put debug info. Recently I saw someone had such a problem. But that was due to the addition of new built-in buttons by Notepad ++ in a next update. The loss of ordering after a regular restart looks strange. But that should have been reported to the plugin author anyway, not here.

**Comment by alankilborn** [comment]
@ScienceDiscoverer 

>Is this only me or somebody else have this problem? Can this be fixed?

I have this problem as well, since getting a new Win11 PC recently.
It hasn't bothered me enough to report it to the plugin author.
But if you want to report it, I will "second" your issue.  :-)
