### ISSUE TITLE
Simplified search feature

### ISSUE THREAD

**Issue by zypperlake** [notepad-plus-plus/notepad-plus-plus#12483]
![image](https://user-images.githubusercontent.com/77734001/200740216-e6049dd7-acbd-46c4-b4cf-6adcd2470d4a.png)

**How it works:**
_When a word is typed in the search bar, the editor marks the search results._

**Comment by alankilborn** [comment]
This feature already exists; see

![image](https://user-images.githubusercontent.com/77065706/200823979-5a63dc8c-6cab-4e38-8a98-97d720b900ae.png)

Please close this issue.

**Comment by zypperlake** [comment]
Hi @alankilborn. Yes, there really is such a function, thanks for the tip.
