### ISSUE TITLE
Slow start when OutputDebugString() does not return in a timely fashion

### ISSUE THREAD

**Issue by Jens-G** [notepad-plus-plus/notepad-plus-plus#12490]
### Description of the Issue
The RELEASE build (as it comes friom the downloads section) starts with > 1 minute delay when calls to OutputDebugString() for some reason do not return in a timely fashion.

### Steps to Reproduce the Issue
I can't give exact steps but I am pretty certain about it. At startup NPP prints the following three lines into ODS() and if the system is in that particular state where ODS() runs into a timeout, then we have 3x the delay.

> E687332916D6B681FE28C5EF423CEE259D3953B9
> E687332916D6B681FE28C5EF423CEE259D3953B9
> E687332916D6B681FE28C5EF423CEE259D3953B9

### Expected Behavior
Fast startup would be a good start (pun intended)

### Actual Behavior
You double-click a file and nothing happens. You click again and still nothing happens. After three tries you check taskman to find that there are three NPP processes running (well, sort of) in the background without any visible window. After waiting long enough (approx one minute, even a maybe little more) it finally appears. 

### Debug Information
Notepad++ v8.4.6   (32-bit)
Build time : Sep 25 2022 - 19:55:26
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 10 Enterprise (64-bit) 
OS Version : 22H2
OS Build : 19045.2251
Current ANSI codepage : 1252
Plugins : 
    DSpellCheck (1.4.6)
    mimeTools (2.8)
    NppConverter (4.4)
    NppExport (0.4)
    RandomValuesNppPlugin (0.2.1)

### Additional info
I am aware that this might primarily be an environmental and/or Windows issue. However, may I suggest that you check whether these debug strings are really needed in a RELEASE build? Removing them might already solve that issue.

**Comment by xomx** [comment]
@Jens-G 

1st - I do not think that a ODS() call itself slows substantially down the N++, especially in case when no one is listening to its output. Ok, when a listener is running (e.g. the Visual Studio debugger), it can slow down things a bit (such debugger then has to hook the ODS() output etc...). But surely this is not the case for few (3) individual ODS() calls.

2nd - I think that the real slow down is not the OSD() output itself but [the verification](https://github.com/notepad-plus-plus/notepad-plus-plus/blob/67256a107b620e9cc84b0cbade56129dda4ba8a9/PowerEditor/src/MISC/Common/verifySignedfile.cpp#L112) of the signed N++ binaries behind. So I agree with your
> I am aware that this might primarily be an environmental and/or Windows issue.

It is probably a specific problem with the N++ certificate verification process on your computer. If you are capable of building the N++ from its source code and debugging it in MSVS, you can set up a breakpoint on the above mentioned N++ method and watch where the real slowdown occurs.

**Comment by Jens-G** [comment]
>  I do not think that a ODS() call itself slows substantially down the N++

That's the difference. I know it, you only assume. It also affects other applications BTW.

**Comment by alankilborn** [comment]
@Jens-G That's rather a harsh posting in response to someone that is only trying to help point you in the right direction.  Of course things are _assumed_ in such a response, because it is a problem that (I _assume_ based on lack of similar reports) is only happening to you.  Good luck in solving your problem.  Cheers.

**Comment by xomx** [comment]
> It also affects other applications BTW.

And that was the missing part for my assumptions ;-)

Anyway, to your question about possible removing ODS() in RELEASE builds - I am for it as I am for any N++ startup speedup. 


@donho 
Is that debug output really needed in the release builds?
And if it is, maybe an asynchronous variant of the OutputDebugString could speed up the N++ startup a bit (that way we do not block the main N++ UI thread by the ODS()...).

I have not experienced any such problem described here myself but theoretically the ODS() calls can be seriously affected by other SW running, e.g. when some app blocks the Windows debug monitoring mutex (mechanism is visible here in the [ReactOS source code equivalent](https://github.com/reactos/reactos/blob/11a71418d50f48ff0e10d2dbbe243afaf34c4368/dll/win32/kernel32/client/debugger.c#L693))

**Comment by donho** [comment]
**OutputDebugString** for me is activated only in debug mode.
In [official MS doc](https://learn.microsoft.com/en-us/windows/win32/api/debugapi/nf-debugapi-outputdebugstringa) says:
`If the application has no debugger and the system debugger is not active, OutputDebugString does nothing.`

> 2nd - I think that the real slow down is not the OSD() output itself but [the verification](https://github.com/notepad-plus-plus/notepad-plus-plus/blob/67256a107b620e9cc84b0cbade56129dda4ba8a9/PowerEditor/src/MISC/Common/verifySignedfile.cpp#L112) of the signed N++ binaries behind. So I agree with your...

The certificate verification is time consuming for sure. Even **OutputDebugString** is active in release, it's rather the part of certificate verification which takes time.

> Is that debug output really needed in the release builds?

No. Indeed it's not necessary. I will see what I can do about it.

**Comment by Jens-G** [comment]
Thanks @donho!
