### ISSUE TITLE
Update galician.xml v. 8.4.7

### ISSUE THREAD

**Issue by conky77** [notepad-plus-plus/notepad-plus-plus#12503]
### Description of the Issue

Update galician.xml without any reformatting
[galician.zip](https://github.com/notepad-plus-plus/notepad-plus-plus/files/9997476/galician.zip)

this issue includes the re-elaboration of the file uploaded initially by @P0rsche-911 in #12463 
I didn't apply any re-formation.
I changed something from the @P0rsche-911 file
Please check the differences:
[differencies_from_P0rche911.zip](https://github.com/notepad-plus-plus/notepad-plus-plus/files/9997509/differencies_from_P0rche911.zip)

Please also check item 6128
`<Item id="6128" name="Alternar iconas"/>`
the correct translation in Spanish is
`<Item id="6128" name="Iconos alternativos"/>`
there was a mistranslation in many Latin languages.

Please upload your final Galician file when you have checked it.
(please write here only something related to the file, write [in the community](https://community.notepad-plus-plus.org/topic/22072/translation-spanish-lng-latest-version/19) if you need help and you don't know how to do anything)

**Comment by conky77** [comment]
I also attach the differences between the current galician.xml and the new one

[diff_between_current_and_new.zip](https://github.com/notepad-plus-plus/notepad-plus-plus/files/9997580/diff_between_current_and_new.zip)

**Comment by P0rsche-911** [comment]
@conky77
Revised
[galician.zip](https://github.com/notepad-plus-plus/notepad-plus-plus/files/10026248/galician.zip)

It is possible that it contains some errors. It is very long.

Thank you all very much for the opportunity you give me.

**Comment by P0rsche-911** [comment]
@conky77 I have found some errors which I have corrected.

Edited lines:

532 and 533, insert spaces as in the english.xml file

1006 bad translation

1295 delete a space

1350 unintentional mistake

New review
[galician.zip](https://github.com/notepad-plus-plus/notepad-plus-plus/files/10045516/galician.zip)

To avoid confusion I will hide the previous message with the wrong translation.

**Comment by conky77** [comment]
@P0rsche-911
Please check the item "IncrementalFind-FSFound" and all strings with`" $INT_REPLACE$:` there is an initial space in the strings, and in the English, there isn't. Maybe it is better to remove them. If any string is truncated in Galician, we have the same problem in all languages. In case it is better to insert an issue (bug)
![immagine](https://user-images.githubusercontent.com/59116246/202839811-74eda666-21c3-4b93-9250-9346c477c425.png)

**Comment by conky77** [comment]
@P0rsche-911
It seems you applied a new formation for old strings (comparing the current Galician and your new one)
![immagine](https://user-images.githubusercontent.com/59116246/202840818-760a03e6-170b-4f86-927d-01cbcedfd236.png)

You converted TAB in spaces, and you added spaces before and after "=" 
the correct file should be very similar to this example (I kept TAB in old items and I didn't add spaces before and after "=".

![immagine](https://user-images.githubusercontent.com/59116246/202842110-09da24b0-aedb-4a3e-8f9b-87998dd6a3dc.png)

In the first step, we have to modify just the translation (from the current galician.xml to the new galician.xml)
We can format the old entries in step two.

**Comment by P0rsche-911** [comment]
> @P0rsche-911 Please check the item "IncrementalFind-FSFound" and all strings with`" $INT_REPLACE$:` there is an initial space in the strings, and in the English, there isn't. Maybe it is better to remove them. If any string is truncated in Galician, we have the same problem in all languages. In case it is better to insert an issue (bug) ![immagine](https://user-images.githubusercontent.com/59116246/202839811-74eda666-21c3-4b93-9250-9346c477c425.png)

Fixed

**Comment by P0rsche-911** [comment]
> @P0rsche-911 It seems you applied a new format for old strings (comparing the current Galician and your new one) ![immagine](https://user-images.githubusercontent.com/59116246/202840818-760a03e6-170b-4f86-927d-01cbcedfd236.png)
> 
> You converted TAB in spaces, and you added spaces before and after "=" the correct file should be very similar to this example (I kept TAB in old items and I didn't add spaces before and after "=" ).
> 
> ![immagine](https://user-images.githubusercontent.com/59116246/202842110-09da24b0-aedb-4a3e-8f9b-87998dd6a3dc.png)
> 
> In the first step, we have to modify just the translation (from the current galician.xml to the new galician.xml) We can format the old entries in step two.
> 
> (I don't know if there are any problems with automatic translation, but when we say "format a string" we mean changing spaces, TAB, the structure of xml file)

I think what needs to be done is going to take a long time.
I understand that I have to modify the galician.xml from 2011 with the current one instead of using directly the english.xml from version 8.4.7.

It is going to be complicated to compare because there are translations that are not going to match.

**Comment by P0rsche-911** [comment]
Will this work?
In any case, a picture may help me better understand what needs to be modified.

[galician test.zip](https://github.com/notepad-plus-plus/notepad-plus-plus/files/10047184/galician.test.zip)

**Comment by conky77** [comment]
[P0rsche-911](https://github.com/P0rsche-911)

![image](https://user-images.githubusercontent.com/59116246/202856663-c8dc581a-3016-4e10-ab37-3af4a22418bc.png)


I think you should do the following in all files (even the new items you added). When the first Pull Request has been approved, we can change it again)

substitute
` name="`  --> `  name = "`      (there is a space at the beginning)
`<Item id="` --> `<Item id = "`

![image](https://user-images.githubusercontent.com/59116246/202856376-4e0921d6-1504-4aa8-afe6-80aa60e6ace0.png)

![image](https://user-images.githubusercontent.com/59116246/202856408-48c702e9-754f-47d4-9b80-71597ba12203.png)

**Comment by conky77** [comment]
and..

` title="`  -->  ` title = "`
`<Item CMID="`  -->  `<Item CMID = "`

**Comment by conky77** [comment]
@P0rsche-911 
there is also an error
`ProjectPanel*Changed*SaveError`  --> `ProjectPanelSaveError`

**Comment by P0rsche-911** [comment]
> @P0rsche-911 there is also an error `ProjectPanel*Changed*SaveError` --> `ProjectPanelSaveError`

[is fixed in galician test.xml](https://github.com/notepad-plus-plus/notepad-plus-plus/issues/12503#issuecomment-1320896533)

**Comment by P0rsche-911** [comment]
@conky77 Revised again.

[galician test 1.zip](https://github.com/notepad-plus-plus/notepad-plus-plus/files/10048114/galician.test.1.zip)

**Comment by conky77** [comment]
@P0rsche-911 
your last file has again the problem
`<ProjectPanel*Changed*SaveError`

**Comment by P0rsche-911** [comment]
@conky77  It is a mystery. I put a screenshot of having corrected it. And I had already done it.
![Notepad++ galego 2](https://user-images.githubusercontent.com/93552629/202895397-53f9598c-60a2-4ed5-b7a2-93a363de2ba7.PNG)

**Comment by conky77** [comment]
@P0rsche-911 
the original version had spaces before and after the symbol `=`
`<Item id=" --> <Item id = "`
`<Item CMID="`  --> `<Item CMID = "`
see the images below

![image](https://user-images.githubusercontent.com/59116246/202905348-ef033026-0c7a-4fe0-baff-ef041e30929b.png)

<img width="947" alt="image" src="https://user-images.githubusercontent.com/59116246/202905653-ec2fb3d3-fff7-45d1-9e30-bfea9dd2c400.png">

**Comment by P0rsche-911** [comment]
> @P0rsche-911 the original version had spaces before and after the symbol `=` `<Item id=" --> <Item id = "` `<Item CMID="` --> `<Item CMID = "` see the images below
> 
> ![image](https://user-images.githubusercontent.com/59116246/202905348-ef033026-0c7a-4fe0-baff-ef041e30929b.png)
> 
I have only modified the elements that appear in the old version. The ones that are not changed do not exist and that is why I left them as they are.

I think it was much easier to change them all than having to go through them one by one to space out just the old ones.
I understood that I should edit only the old elements and not all of them.  Is it necessary to change them all?

Solo he modificado los elementos que aparecen en la versión antigua. Los que no están cambiados no existen y por eso los dejé como están.

Creo que era mucho más fácil cambiarlos todos que tener que revisar uno por uno para espaciar solo los antiguos.
Entendí que debía editar solo los elementos antiguos y no todos. ¿Es necesario cambiarlos todos?

> <img alt="image" width="947" src="https://user-images.githubusercontent.com/59116246/202905653-ec2fb3d3-fff7-45d1-9e30-bfea9dd2c400.png">
Mover a otra... -> Move to other... Mover a outra
Clonar en otra... -> Clone to other... Mover noutra (contraction of "en outra")

**Comment by conky77** [comment]
@P0rsche-911 
You must modify old entries (for example 41001, 41002,41003, 41004,41005,41006, 41007, 41008, 41009, 41010, 41011, 41012, 41013, 41014, 1001, cmid="0", cmid="1", cmid="2", cmid="3", etc). (You can modify the new entries only if you want; I suggested modifying all entries because it was easier).
I wanted just to show you spaces before and after the symbol   `=`   (I left the color of winmerge)

**Comment by P0rsche-911** [comment]
@conky77 You are right. I didn't realize that. I'll get right on it. Sorry.

**Comment by conky77** [comment]
@P0rsche-911 
please don't consider my following list a complete list.
before updating the file, please check if there are other cases

![immagine](https://user-images.githubusercontent.com/59116246/203404414-a0ef6adf-c132-4639-a769-aae35fc0001d.png)


![immagine](https://user-images.githubusercontent.com/59116246/203404868-d8fbadf6-d3e3-4721-95a1-475071df6471.png)



![immagine](https://user-images.githubusercontent.com/59116246/203403061-06c03f4d-f6cd-4995-b650-bb8d30bcae72.png)


![immagine](https://user-images.githubusercontent.com/59116246/203403325-6c71b3eb-4aaa-4d2f-9c5d-094d160d58e0.png)

**Comment by P0rsche-911** [comment]
`<Item menuid="tools" name = "&amp;Ferramentas"/>` Does not exist in the previous version.

`<Item submenuid="view-collapseLevel" name = "Niveis para contraer pestana actual"/>
<Item submenuid="view-uncollapseLevel" name = "Niveis para expandir pestana actual"/>` Those lines are just below this one:
`<Item submenuid = "view-tab" name = "Pestanas"/>`

`<Item id="1903" name="The Program to Run"/> <Item id = "1903" name = "Programa a executar"/>
<Item id="2" name="Cancel"/><Item id = "2" name = "Cancelar"/>`

I am still looking for...

**Comment by P0rsche-911** [comment]
@conky77 I think this is the good one

[galician test 4.zip](https://github.com/notepad-plus-plus/notepad-plus-plus/files/10087385/galician.test.4.zip)

**Comment by conky77** [comment]
@P0rsche-911 
It looks good!
You are ready to create your first "Pull request"
I teach you how to make it in the web browser.

- Login in github
- click on [galician.xml](https://github.com/notepad-plus-plus/notepad-plus-plus/blob/master/PowerEditor/installer/nativeLang/galician.xml)
- Click on "edit"
- copy the text from your file
- paste it in GitHub
- save it
- push on "create pull request"
title: `update galician.xml`
description: `fix #12503`
If you need more help in creating a new pull request, please write in the community (new topic), so people more expert than me can teach you how to do it (and maybe there are Spanish speaker)

**Comment by P0rsche-911** [comment]
@conky77
Thank you very much.
Once the pull request is created and accepted, is it possible to modify it later to put it as the english.xml version?
That is, the code, spaces, line breaks, etc. should be identical. That the reference file is english.xml and not galician.xml from 2011.

Muchísimas gracias.
Una vez creado el pull request y sea aceptado, es posible modificarlo después para ponerlo como la versión english.xml?
Es decir, que el código, espacios, saltos de línea, etc. sea idéntico. Que el archivo de referencia sea english.xml y no galician.xml del 2011.

**Comment by conky77** [comment]
@P0rsche-911 
Once the first Pull Request is accepted (close and committed), we can create a new Pull Request with only format stuff (the second Pull request). Once the second Pull Request is accepted, we can make a Pull Request to version 8.4.8 (the third Pull Request). Don Ho usually verifies the Pull Request only before closing the version. To earn time, when we are sure the Pull request is OK, I can ask Don HO to commit the Pull Request as soon as possible so we can create the subsequent Pull Request. We have only to pay attention to not writing too often him ;-) 
Let me know when you have created the Pull Request

**Comment by P0rsche-911** [comment]
@conky77
https://github.com/notepad-plus-plus/notepad-plus-plus/pull/12572

**Comment by ArkadiuszMichalski** [comment]
Fixed by https://github.com/notepad-plus-plus/notepad-plus-plus/commit/9752c9e1031fb227a4d90f9315ad3e002f1b4ec2.
