### ISSUE TITLE
Hyperlink color still as blue without follow the style changed 

### ISSUE THREAD

**Issue by KristyJone** [notepad-plus-plus/notepad-plus-plus#12505]
### Steps to Reproduce the Issue

1. Change the URL hovered color to lime (whatever), its work.
2. Restart Notepad again, its back to navy.
3.

**Comment by ArkadiuszMichalski** [comment]
I can't reproduce this. After changing the color did you press the `Save & Close` button? 

This report is not complete, `Debug Information` is missing. I close until it's completed.

**Comment by KristyJone** [comment]
May be not a bug.
Just want to know how to let URL link viewable in dark mode.
I make a demo as video file on Youtube
https://youtu.be/6VmXMpK7Lh8

 
 
 
Notepad++ v8.4.7   (64-bit)
Build time : Nov  1 2022 - 23:31:11
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 10 Enterprise (64-bit) 
OS Version : 22H2
OS Build : 19045.2251
Current ANSI codepage : 950
Plugins : 
    AutoSave (1.6.1)
    BetterMultiSelection (1.4)
    CodeAlignmentNpp (14.1.107)
    CsvQuery (1.2.8)
    DSpellCheck (1.4.23)
    ERPHelper (1.1.2)
    Explorer (1.9.5)
    FWDataViz (2.4.0.2)
    HexEditor (0.9.12)
    mimeTools (2.9)
    NppConverter (4.5)
    nppcrypt (1.0.1.6)
    NppDocShare (0.1)
    NppExport (0.4)
    NppFavorites (1.0.0.1)
    NppFTP (0.29.8)
    NPPJSONViewer (1.40)
    NppQrCode64 (0.0.0.1)
    NppSaveAsAdmin (1.0.211)
    NppXmlTreeviewPlugin (2)
    Remove Duplicate Lines (1.3)
    RestApiToText (1.3.1)
    SpeechPlugin (0.4)
    urlPlugin (1.2)
    XMLTools (3.1.1.13)
    _CustomizeToolbar (5.3)

**Comment by ArkadiuszMichalski** [comment]
Try without plugins (`-noPlugin` command line) or test this on last portable.

**Comment by KristyJone** [comment]
32 bits Portable is work without problem whatever have or haven't plugin.

 

Thanks Arkadiusz

 


Sent: Monday, November 14, 2022 at 9:38 PM
