### ISSUE TITLE
All Style tokens colors in Notepad++ are black. How do I bring the default colors back?

### ISSUE THREAD

**Issue by scapeh1ps** [notepad-plus-plus/notepad-plus-plus#12504]
I am using the DansLeRuSH-Dark theme

Debug Information:-
Notepad++ v8.4.6   (64-bit)
Build time : Sep 25 2022 - 19:51:39
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 11 (64-bit) 
OS Version : 22H2
OS Build : 22621.819
Current ANSI codepage : 65001
Plugins : 
    BracketsCheck (1.2.2)
    CodeAlignmentNpp (14.1.107)
    CodeStats (1.0.1)
    ComparePlus (1)
    CsvQuery (1.2.9)
    HexEditor (0.9.12)
    Merge files in one (1.2)
    mimeTools (2.8)
    MusicPlayer_1.0.11x64 (1.0.0.3)
    NavigateTo (1.12.7)
    NppConverter (4.4)
    NppExport (0.4)
    NppSaveAsAdmin (1.0.211)
    NppSnippets (1.7)
    NppToolBucket (1.10.6622.41516)
    pork2sausage (2.2)
    PreviewHTML (1.3.2)
    Python Indent (1.0.0.4)
    PythonScript (2)
    RandomValuesNppPlugin (0.2.1)
    SecurePad (2.4)
    SQLinFormNpp64 (5.3.35)
    urlPlugin (1.2)
    WakaTime (4.2.3)
    XMLTools (3.1.1.13)

![Screenshot 2022-11-13 213907](https://user-images.githubusercontent.com/50423845/201531942-f8bc4e41-344a-42ef-8dfe-5edfd3e1c1a8.png)

**Comment by ArkadiuszMichalski** [comment]
You can change this through `Setting > Style Configurator...` for `DansLeRuSH-Dark` theme (entry `Mark Style1` to `Mark Style5`). 
But in fact this theme has it set wrong (basically it uses the default `bgColor`), so marking something is not visible, this should be corrected.

**Comment by scapeh1ps** [comment]
I fixed it thanks!

**Comment by ArkadiuszMichalski** [comment]
It's worth correcting this also in the inbuilt theme file but I don't know what colors will be appropriate.
