### ISSUE TITLE
[Feature Request] Add function list parser for NppExec plugin's scripting language

### ISSUE THREAD

**Issue by dinkumoil** [notepad-plus-plus/notepad-plus-plus#12517]
### Description of the Issue
Since an [UDL lexer for _NppExec_ plugin's scripting language is available](https://github.com/notepad-plus-plus/userDefinedLanguages/blob/master/UDLs/NppExec_themeDefault_byAndreasHeim.xml), it would be nice to have a function list parser for this language as well.

### Steps to Reproduce the Issue
1. [Install the UDL lexer](https://npp-user-manual.org/docs/user-defined-language-system/#import-a-udl) for _NppExec_ plugin's scripting language from the link above.
2. Load the [sample file for this language](https://github.com/notepad-plus-plus/userDefinedLanguages/blob/master/UDL-samples/NppExec_byAndreasHeim.exec) with _Notepad++_. 
3. Watch function list panel.

### Expected Behavior
Function list panel should display a list of functions contained in the code of the loaded _NppExec_ script.

### Actual Behavior
Function list panel stays empty.

### Applies to
All versions of _Notepad++_.

**Comment by donho** [comment]
Such file can use BATCH parser.

**Comment by dinkumoil** [comment]
> Such file can use BATCH parser.

Batchscript and _NppExec_ script are very different. Batchscript function list parser doesn't fit the structure of _NppExec_'s _npes_saved.txt_ file (the container file for all _NppExec_ scripts). Thus, the resulting function list tree gives no satisfying result, it's nearly useless.

Anyhow, I will let it go like this.

**Comment by donho** [comment]
@dinkumoil 
> Batchscript and NppExec script are very different.

Could you provide me the link of NppExec script manual? If it's the case, I will reconsider the PR.

**Comment by dinkumoil** [comment]
Link to _NppExec_ repo: https://github.com/d0vgan/nppexec
Link to manual files: https://github.com/d0vgan/nppexec/tree/master/NppExec/doc/NppExec

BTW: This is how Notepad++ displays my _npes_saved.txt_ file (_NppExec_'s script container) when my UDL lexer and my function list parser for _NppExec_ script is active. Please note that you can see in function list panel a list of all scripts contained in the plugin's script container file:

![grafik](https://user-images.githubusercontent.com/24699812/203823523-63aa09c7-1b0d-4490-b7f8-4b64a563130e.png)

This is how it looks when I activate Batchscript lexer (what has to be done to get Batchscript function list parser as well). Please note the flat list of all jump labels in function list panel, which is nearly useless because a user wants to navigate at first to a specific script and only then to a jump label of this script:

![grafik](https://user-images.githubusercontent.com/24699812/203824887-9b203a8d-1000-4839-8a2e-4984b60a01d9.png)

**Comment by donho** [comment]
@dinkumoil 
> Batchscript and NppExec script are very different. 

Sorry I wasn't clear: I need NppExec **Script** manual to compare both script, in order to know the difference.

**Comment by dinkumoil** [comment]
You can find the docu of _NppExec_ script commands in file `NppExec_HelpAll.txt` which you can find under the second link I already posted in a previous comment. Direct link: https://github.com/d0vgan/nppexec/blob/master/NppExec/doc/NppExec/NppExec_HelpAll.txt

But it seems like you still have not understood that the problem is not about being Batchscript similar to _NppExec_ script or not. The problem is that a Batchscript function list parser produces useless results when parsing _NppExec_ script code. Please see the screenshots above and please also read my comments thoroughly.

**Comment by donho** [comment]
@dinkumoil 
Trust me, I can see the difference of result and I do know the parsers do the different job.
From my side, I have to prove your parser is specific for NppExec Script but not for your own personal use.
So if you can point me out your container/class implementation is linked with NppExec Script (in any document of NppExec), that will help me to accept your PR.

**Comment by alankilborn** [comment]
I like the idea of a NppExec function-list parser for N++, but doesn't it get a bit awkward if the parser is part of N++ core, but the plugin-functionality itself is not?

I mean, NppExec is a plugin only for N++, so it is different than C/C++/Python etc.

**Comment by dinkumoil** [comment]
@donho 

> So if you can point me out your container/class implementation is linked with NppExec Script (in any document of NppExec), that will help me to accept your PR.

The container file _npes_saved.txt_ is **not** my implementation in any way. As I [already wrote](https://github.com/notepad-plus-plus/notepad-plus-plus/issues/12517#issuecomment-1326640793)

> using the script container file _npes_saved.txt_ is nothing special what only I do. This file is the intended way of storing _NppExec_ scripts. The plugin relies on this file. Only scripts contained in this file can be added to the Macro menu and assigned to a keyboard shortcut.

This is documented [here](https://github.com/d0vgan/nppexec/blob/faa384bddd8152fb9b7bcf9359db306638423711/NppExec/doc/NppExec/NppExec_TechInfo.txt#L727).

@alankilborn @donho 

Yes, _NppExec_ is only a plugin for Notepad++ but it is a (supposedly widely used) plugin that exists since 2007:

![grafik](https://user-images.githubusercontent.com/24699812/204004006-c6bbed55-2167-437d-8b73-28c141b36f2c.png)

This is a screenshot of the [plugin's repo on _SourceForge_](https://sourceforge.net/projects/npp-plugins/files/NppExec/) and shows the "last modified" time of the v0.1 directory of this plugin.

And even that it can only be used with Notepad++ and its only use case is controlling and manipulating Notepad++ I think it deserves to have its function list parser included with future Notepad++ releases.

An alternative to include _NppExec_ function list parser into Notepad++ releases would be to provide a repo for user defined function list parsers like the official repo fur UDL lexers. Currently there is nothing like that AFAIK.

**Comment by donho** [comment]
@alankilborn @dinkumoil 
Every script deserve its place without considering its popularity. If we take the popularity as a criteria, NppExec is one of most popular plugins for Notepad++, and this parser could help people who use NppExec. That's the reason I consider it.

@dinkumoil 
> using the script container file npes_saved.txt is nothing special what only I do. This file is the intended way of storing NppExec scripts. The plugin relies on this file. Only scripts contained in this file can be added to the Macro menu and assigned to a keyboard shortcut.

This argument is not enough to me.
I would like know the specifications of NppExec Script thay you rely on for doing the nodes and leafs for your parser.

**Comment by dinkumoil** [comment]
> This argument is not enough to me.
I would like know the specifications of NppExec Script thay you rely on for doing the nodes and leafs for your parser.

That's the reason why I already wrote "please also read my comments thoroughly". The links you are requesting are part of my last comment.

**Comment by dinkumoil** [comment]
@donho 

If you want a documentation for the file format of _npes_saved.txt_ - I think this doesn't exist.

**Comment by donho** [comment]
OK, there are no even description "2 colons" but only [this bloc](https://github.com/d0vgan/nppexec/blob/faa384bddd8152fb9b7bcf9359db306638423711/NppExec/doc/NppExec/NppExec_TechInfo.txt#L303)

That's what I need to validate the parser.
Thank you for you explanation @dinkumoil , and sorry for wasting your time.

**Comment by dinkumoil** [comment]
@donho Thank you for accepting my PR!
