### ISSUE TITLE
Move current line down Operation sucks !

### ISSUE THREAD

**Issue by Alex21c** [notepad-plus-plus/notepad-plus-plus#1251]
# Bug Info
When moving current line downwards  (using keyboard) more than once it get stuck and start just swapping the current line with the previous line.
Very annoying. Everything was fine until previous version of N++. 

## Txt File On which i'm using to test the bug 
[testFile.npp](http://bit.ly/1MdLHfs)

## Bug Clip
[bugClip](https://youtu.be/TlxWaNgRK8U)

## Here is My N++ Debug Info:
* Notepad++ v6.8.8
* Build time : Dec 10 2015 - 01:11:37
* Admin mode : OFF
* Local Conf mode : ON
* OS : Windows 8.1

**Comment by dail8859** [comment]
The file has mixed line endings, which is causing it to get confused. Use `Edit > EOL Conversion` and choose a format to unify the line endings.

**Comment by Alex21c** [comment]
I have EOL Conversion already set to Windows Format.

**Comment by dail8859** [comment]
Set it to Unix and then back to Windows.

**Comment by Alex21c** [comment]
Nope, Actually its messing with two symbols
First one is [
Second one is .

**Comment by Alex21c** [comment]
I have attached the [testFile](http://bit.ly/1MdLHfs) test it and let me know if it works for you?

**Comment by dail8859** [comment]
That is exactly what I tried. I open the file, try to move the lines, it gets stuck. Which is exactly what you are seeing.

Converted the line endings to Unix, then converted it to Windows. Now I can move lines fine.

If you want to see the line endings you can you can select `View > Show Symbol > Show End of Line` and you can see some end with CRLF and some just end with LF.

**Comment by Alex21c** [comment]
Lol, My fault....

**Comment by Alex21c** [comment]
Actually i used the Regular Expression Replacements where i just \n but not \r. thats why all this happens. Because windows supports \r\n = Carriage Return and line feed !

**Comment by dail8859** [comment]
Glad it's working now :)

**Comment by Alex21c** [comment]
:)

**Comment by Alex21c** [comment]
Issue Fixed !
