### ISSUE TITLE
Some features (like autocomplete) stay with dark theme after switching from dark theme to light theme

### ISSUE THREAD

**Issue by AlexandraMN** [notepad-plus-plus/notepad-plus-plus#12514]
### Description of the Issue
Some features stay with dark theme after switching from dark theme to light theme

### Steps to Reproduce the Issue
1. Dark theme enabled
2. Added some changes
![image](https://user-images.githubusercontent.com/37780342/201635811-aa5bead1-3eb7-4a08-9083-a19bb165fcb1.png)
3. Changed to light theme
![image](https://user-images.githubusercontent.com/37780342/201636242-442d5de7-9a8b-4f4a-9876-8ed6ada1204a.png)
Also a problem with auto complete
![image](https://user-images.githubusercontent.com/37780342/201636493-f14aa284-a6b3-4974-ae00-84a49f9700f1.png)

After restart, the views will switch to light mode.

### Expected Behavior
All features are changed to light theme without restarting the application

### Debug Information
Notepad++ v8.4.7   (64-bit)
Build time : Nov  1 2022 - 23:31:11
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 10 Enterprise (64-bit) 
OS Version : 21H2
OS Build : 19044.2130
Current ANSI codepage : 1252

**Comment by CennoxX** [comment]
According to Donho this is due to the absence of style “Change History margin” in your stylers.xml https://community.notepad-plus-plus.org/post/80150

**Comment by ozone10** [comment]
Does not depend on dark mode, but theme.
Started from version 8.4.1., only affect default theme ("styler.xml"), changing to some different theme works correctly.

**Comment by ArkadiuszMichalski** [comment]
Confirmed, started from 8.4.1:
https://github.com/notepad-plus-plus/notepad-plus-plus/wiki/Changes#841
