### ISSUE TITLE
Notepad++ corrupts/cuts off large files

### ISSUE THREAD

**Issue by timsu100** [notepad-plus-plus/notepad-plus-plus#12526]
### Description of the Issue
When editing a large file and saving it, it does get corrupted and cut off

### Steps to Reproduce the Issue
Requires `bash` and `python3` but this simple example file can easily be generated by other means

#### Generate example file (does need 10 GB Space)
1. Create python script `run.py`
```python
for i in range(1000):
    print("a" * 10**7)
```
2. run script and redirect output to file `python run.py > demofile.txt`

#### Verify file size
```
$ wc -c demofile.txt
10000002000 demofile.txt
```
We can see file size is around 10 GB.

#### Edit file in Notepad++
1. Open file in npp, do a simple edit (for example add a space to the begin of the first line). This can be a bit slow and sluggish.
2. Save file

#### Verify file size again
```
$ wc -c demofile.txt
1410067409 demofile.txt
```
We can see file size is around 1.4 GB.

### Expected Behavior
The file size should increase by one byte.

### Actual Behavior
The **file loses most of its contents**, now it has **only 141 lines instead of 1000**.

### Debug Information
Notepad++ v8.4.6   (64-bit)
Build time : Sep 25 2022 - 19:51:39
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : "C:\Users\<username>\Documents\data\demofile.txt"
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 10 Enterprise (64-bit) 
OS Version : 21H2
OS Build : 19044.2130
Current ANSI codepage : 1252
Plugins : 
    ComparePlugin (2.0.2)
    DSpellCheck (1.4.24)
    MarkdownViewerPlusPlus (0.8.2)
    mimeTools (2.8)
    NppConverter (4.4)
    NppExport (0.4)
    TextFX (0.2.4)
    XMLTools (3.1.1.13)

**Comment by xomx** [comment]
I can reproduce that.

**Comment by xomx** [comment]
I found the problem in the N++ code, there are invalid 64-bit -> 32-bit castings of filesize integers.
I will try to fix that but no ETA.

**Comment by xomx** [comment]
@pnedev 

Hello, many thanks for the help, I don't have time for that right now.

> changes to the `FileInterface::write` method so now it directly accepts and handles size_t as size to write

Yes, that's it. It should be enough to solve both this issue and the mentioned community report.

> WcharMbcsConvertor::encode

I didn't even checked this so far.

> If you like you could use my changes as a starting point

Definitely, thanks. 
It might be better if you create and handle the whole PR yourself, but I assume you don't have a time for it(?)

> Unfortunately I haven't tested my changes, I'm sorry about that.
Understood. Thanks anyway.

**Comment by xomx** [comment]
Hello @pnedev , I wish you nice holidays.

I have some time for this now, so I can handle the testing & PR if you still cannot?

I have already reviewed the potentially problematic `WcharMbcsConvertor::encode` and I think it is OK as it is now, as there seems to be zero chance that the converted data size reaches problematic 2GB `int` limit. The func in question is used here: [1](https://github.com/notepad-plus-plus/notepad-plus-plus/blob/3ee8660c2323989acfda7ef0e6a5c067c9eb5f05/PowerEditor/src/ScintillaComponent/Buffer.cpp#L1055), [2](https://github.com/notepad-plus-plus/notepad-plus-plus/blob/3ee8660c2323989acfda7ef0e6a5c067c9eb5f05/PowerEditor/src/ScintillaComponent/Buffer.cpp#L1195), [3](https://github.com/notepad-plus-plus/notepad-plus-plus/blob/3ee8660c2323989acfda7ef0e6a5c067c9eb5f05/PowerEditor/src/ScintillaComponent/Buffer.cpp#L1597) and in these places the data are processed in chunks that cannot exceed the [blockSize](https://github.com/notepad-plus-plus/notepad-plus-plus/blob/3ee8660c2323989acfda7ef0e6a5c067c9eb5f05/PowerEditor/src/ScintillaComponent/Buffer.cpp#L35).

**Comment by pnedev** [comment]
Hi @xomx ,

I haven't worked on this yet, sorry about that.
If you can look into it please do, thank you! Tell me if I can assist you with something.

Happy holidays to you too!
BR

**Comment by alankilborn** [comment]
@xomx

>the data are processed in chunks that cannot exceed the blockSize

Your comment about blockSize reminded me of #8966 .  Related in any way?

**Comment by xomx** [comment]
@alankilborn 
I do not think so. That issue is about handling an incorrectly split UTF8 character encoding at the buffer boundaries.
For this issue is relevant only that the data handled by `WcharMbcsConvertor::encode` does not need the `int` -> `size_t` patch because of it cannot exceed the 2GB `int` limit.

**Comment by alankilborn** [comment]
@xomx OK, but it sounds like you have expertise in the general area of this; maybe have a try at 8966 too? :-)

**Comment by xomx** [comment]
@alankilborn 
I am by no means an expert in Unicode. Actually, if possible, I avoid it. Nowadays, Unicode is something monstrous, but it is probably also prepared for a possible future complement to the alphabet of aliens. ;-)

IMO - currently the Windows OS UTF-16 (and all the associated MultiByteToWideChar/WideCharToMultiByte conversions) is the worst choice of all, both the UTF-8 (1B ASCII compatibility, universality) and the UTF-32 (fixed-length encoding, simplicity, speed) are better.

**Comment by xomx** [comment]
@pnedev 
Your patch does not need any change, good work!
I checked saving for files up to ~9GB (also for usual smaller ones under 4GB, of course), files with different encodings etc.

**Comment by pnedev** [comment]
@xomx ,
Excellent, thank you very much for looking into this :+1:
