### ISSUE TITLE
Saved/unsaved line changes print color background

### ISSUE THREAD

**Issue by josephgg216** [notepad-plus-plus/notepad-plus-plus#12529]
### Description of the Issue
With 'Display Change History' (DCH) enabled, lines with a saved/unsaved (green/orange) edge indicator will print with indicator color as the background across entire line, with no option to turn off or otherwise modulate in Print settings. Will print background despite Print preference setting of 'black on white', for example.

### Steps to Reproduce the Issue
1. Select 'Display Change History' checkbox in Settings -> Preferences -> Margins/Borders/Edge (requires restart to enable).
2. 'Print Line Numbers' setting in Print Preferences has no effect on DCH print behavior. 
3. Edit some or all lines in a file, such that the DCH editor displays a color, and either save or don't save.
4. Print the file.

### Expected Behavior
Expected 'Display Change History' edge indicator to stay in the edge of hardcopy (as it appears on screen display), or not print.

### Actual Behavior
The color of the indicator became the background color for the entire row, extending from left margin to right. Only by closing and reopening the file (removing the edge indicator) can this be avoided.

### Debug Information
Notepad++ v8.4.6   (64-bit)
Build time : Sep 25 2022 - 19:51:39
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 10 Enterprise (64-bit) 
OS Version : 20H2
OS Build : 19042.1706
Current ANSI codepage : 1252
Plugins : 
    mimeTools (2.8)
    NppConverter (4.4)
    NppExport (0.4)

**Comment by alankilborn** [comment]
Please search for existing/closed issues that are the same as yours before opening a new one.
Fixed in 8.4.7; workaround for 8.4.6 is [HERE](https://community.notepad-plus-plus.org/topic/23616/faq-desk-new-change-history-feature#:~:text=was%20last%20updated.-,PRINTING,-Issue%20%2312281%3A%20Due).

**Comment by alankilborn** [comment]
Please CLOSE this issue.
