### ISSUE TITLE
SQL syntax coloration bug

### ISSUE THREAD

**Issue by hahahafr** [notepad-plus-plus/notepad-plus-plus#1253]
Hello,

In this file : https://raw.githubusercontent.com/glpi-project/glpi/0.84.6/install/mysql/glpi-0.84.6-empty.sql
the SQL coloration of notepad++ fails at line 1715.

Cordially.

**Comment by jonandr** [comment]
There's a setting for this, Settings -> Preferences -> Misc -> Treat backslash as escape character for SQL.

**Comment by hahahafr** [comment]
I disabled it, enabled it, and it still has no effect.

**Comment by sanastasiou** [comment]
Did you reload the file after changing the setting?

**Comment by hahahafr** [comment]
Yes.

**Comment by DarkNexusNR** [comment]
Tested with v6.8.8 and v6.8.2 and the setting is no longer working correctly for me.

**Comment by unobtainable** [comment]
Thanks jonandr & sanastasiou - that sorted the issue for me.

Running v6.8.3 here

**Comment by DarkNexusNR** [comment]
I just had another look at this. It doesn't escape correctly when opening a file or switching languages. It does start to escape correctly after switching tabs.

**Comment by incredibleweirdo** [comment]
I've installed versions 6.8.8, 6.9.2, and 7, and all seem to still have this bug where changing the setting does nothing. Even setting the setting utilizing the NppExec plugin (following steps here: http://docs.notepad-plus-plus.org/index.php/Built-in_Languages) does not seem to make a difference. Syntax highlighting is still incorrect when a backslash is present before a double quote.

**Comment by dcamarena** [comment]
> There's a setting for this, Settings -> Preferences -> Misc -> Treat backslash as escape character for SQL.

Hi, seems that this setting is no longer available in 7.8.2. The backslash is recognized as escape character, which is wrong: 

> In ANSI SQL, the backslash character (\\) is the escape character.
... 
> However, ANSI standards specify that using the backslash character (\\) to escape single (' ') or double (" ") quotation marks is invalid.

Refer to https://www.ibm.com/support/knowledgecenter/SSGU8G_11.70.0/com.ibm.esqlc.doc/ids_esqlc_0015.htm

Example: 
SQL Server Management Studio: 
![SQL Server Management Studio](https://user-images.githubusercontent.com/4989593/70882741-fd352a80-1fd0-11ea-9531-3d3100824f5a.PNG)
Notepad++ 7.8.2:
![notepad 7 8 2](https://user-images.githubusercontent.com/4989593/70882778-16d67200-1fd1-11ea-8460-535d94374cea.PNG)

**Comment by xylographe** [comment]
> … this setting is no longer available in 7.8.2.

**Settings > Preferences > Language**

**Comment by dcamarena** [comment]
@xylographe: Thanks. I didn't find it. Shame on me. 
But the issue that \\ is escape character in SQL (except for " and ') is still valid. Right? Should I open a new issue for that or would that be handled in this?

**Comment by xylographe** [comment]
This looks very similar to issue #1852. I think, this cannot be solved in NPP. It seems to be a [Scintilla lexer issue](https://sourceforge.net/p/scintilla/bugs/). Most likely, it has already been reported there.

**Comment by incredibleweirdo** [comment]
> This looks very similar to issue #1852. I think, this cannot be solved in NPP. It seems to be a [Scintilla lexer issue](https://sourceforge.net/p/scintilla/bugs/). Most likely, it has already been reported there.

It looks like it was fixed in Scintilla - https://sourceforge.net/p/scintilla/bugs/2098/

**Comment by xylographe** [comment]
IIRC NPP 7.8.2 comes with Scintilla 4.2.0. Hence, the reported problem should be resolved, but apparently it is not⁈

**Comment by incredibleweirdo** [comment]
Actually, I'll confirm now that it is fixed and working for me. Unchecking **Settings > Preferences > Language >** `Treat backslash as escape character for SQL` and restarting NPP, I no longer see issues when there's a backslash before a single nor double quote. Using the example SQL in issue #1852, I'm not longer seeing syntax highlighting issues. 

![image](https://user-images.githubusercontent.com/1223976/71382539-3f400c80-258d-11ea-8242-acc05680eb85.png)

**Comment by dcamarena** [comment]
Hi all, from my point of view ist still open. 

> But the issue that \ is escape character in SQL (except for " and ') is still valid.

So, If setting "use backslash as escape character" is on, NPP should display it as escape character EXCEPT before" and '. 
If the setting is off, it shouldn't show it as escape character at all. 
If you would like to, you could add a setting next to the escape character setting for SQL which gets active when using escape characters in SQL with name `except for " and ' ` or use `ANSI ISO SQL`

> In ANSI SQL, the backslash character (\\) is the escape character.
...
**However, ANSI standards specify that using the backslash character (\\) to escape single (' ') or double (" ") quotation marks is invalid.**

> Excerpt from https://www.ibm.com/support/knowledgecenter/SSGU8G_11.70.0/com.ibm.esqlc.doc/ids_esqlc_0015.htm

Happy Christmas, Daniel

**Comment by xylographe** [comment]
IMO the highlighting cannot be wrong, because backslash before single or double quote is **invalid**. You cannot expect some specific outcome from erroneous input, can you?

**Comment by incredibleweirdo** [comment]
> IMO the highlighting cannot be wrong, because backslash before single or double quote is **invalid**. You cannot expect some specific outcome from erroneous input, can you?

Backslash before single or double quote is not invalid, no. Backslash _as escape character_ before single or double quote is invalid.

**Comment by dcamarena** [comment]
I agree to @incredibleweirdo 
So, I think it is still open and my proposal still valid: 

> So, If setting "use backslash as escape character" is on, NPP should display it as escape character EXCEPT before" and '.
> If the setting is off, it shouldn't show it as escape character at all.
> If you would like to, you could add a setting next to the escape character setting for SQL which gets active when using escape characters in SQL with name except for " and ' or use ANSI ISO SQL

Better ideas welcome:)

**Comment by xylographe** [comment]
If "use backslash as escape character" is on, I believe, you must write **`'\\'`** and **`"\\"`**, because **`'\'`** and **`"\"`** are invalid.

**Comment by incredibleweirdo** [comment]
> If "use backslash as escape character" is on, I believe, you must write **`'\\'`** and **`"\\"`**, because **`'\'`** and **`"\"`** are invalid.

I think you're misunderstanding. `\'` and `\"` are not invalid in SQL. The backslashes are _invalid as escape characters before the quotes_. The character string is valid. If "use backslash as escape character" is on, **the backslash should be treated as a backslash and the single/double quotes as single/double quotes that are unescaped, because backslash is invalid as escape character before quotes in SQL**. If "use backslash as escape character" is Off, then it should not be treated as an escape character anywhere in SQL.
