### ISSUE TITLE
Set inactive tab colours by default

### ISSUE THREAD

**Issue by xxxmicrobexxx** [notepad-plus-plus/notepad-plus-plus#12537]
For people with visual impairment issues, it is really hard to read the text on inactive tabs when it is Dark grey on light grey.

![image](https://user-images.githubusercontent.com/1052491/202705955-acb6d273-0038-4076-b4fb-f089a257bbce.png)

It would be supportive if there was a way to adjust the generic tab colours.  I would make the text black and the background colour be in contrast to the text, anything but grey.

I know it is possible to assign colours to tabs, but this needs to be done to individual tabs, unless I am missing something.

In my perfect world I would be able to set the colour of all inactive tabs by default.

**Comment by alankilborn** [comment]
Seems achievable to me (in v8.4.7); here `new 1` is the inactive tab:

![image](https://user-images.githubusercontent.com/77065706/202707714-fe0ec0b3-68d6-4806-a58a-cecc04725fbd.png)

**Comment by xxxmicrobexxx** [comment]
I had a feeling it might be, but we are so spoiled for choice with options
I missed it.

Thanks.  This can be closed.Message ID:
***@***.***>

>

**Comment by alankilborn** [comment]
>This can be closed.

As the one who opened it, you are the best one to CLOSE it.
(I can't, I'm not a team member, just a helper-outer)

**Comment by xxxmicrobexxx** [comment]
I notice that the background colour of the Active Tab can't be edited.  Is this by design?

**Comment by alankilborn** [comment]
By the way,

>For people with visual impairment issues,

I'd think the tab icons would be a problem as well, distinguishing a saved (blue icon) from a locked (grey icon) file from a changed (red icon):

![image](https://user-images.githubusercontent.com/77065706/202720091-6bbefa11-fcb2-49e1-87c0-0fd984640fd5.png)



For this case, try the "Alternate Icons" feature:

![image](https://user-images.githubusercontent.com/77065706/202719895-8c5f0492-c946-411a-abbb-ac2bd37d6c73.png)
