### ISSUE TITLE
N++ v8.4.7 inconsistencies at exit during OS restart/shutdown

### ISSUE THREAD

**Issue by xomx** [notepad-plus-plus/notepad-plus-plus#12541]
Two problems in the same area reported:
1. Single dirty file is directly saved during the OS restart without asking the user 1st (Community [report1](https://community.notepad-plus-plus.org/post/81726))
2. N++, with its backup engine ON, does not behave identically during the usual N++ exit initiated by the user and during the one initiated by the OS restart (Community [report2](https://community.notepad-plus-plus.org/post/81616)} 

STRs:

1)
- open only 1 existing file in N++
- add some text in the opened file without saving it, do not close N++
- restart Windows, “This program preventing restart...” dialog appears, click on the "Cancel" option there - the opened unsaved file is saved now (error - the N++ SaveAll dialog should be opened instead as in the case of 2 or more dirty files)
- this problem has to be fixed for sure, N++ should behave the same as for the 2 or more dirty files...

2)
- “Remember current session for next launch” and “Enable session snapshot and periodic backup” are enabled in the N++ 'Preferences'
- open some files, edit at least one of them
- now if the running N++ was closed by user manually ... no save dialog for the changed file(s), N++ just silently closes and on its next start all the files are opened again from the N++ backup
- but if the Windows OS restart tried to close that running N++ ...  we get the “This program preventing restart...” dialog and when the user clicks on its "Cancel" option,  N++ offers its  SaveAll dialog for all the unsaved files ("Restart anyway" option is ok from this point of view)
- this is intentional new safer behavior at the OS restart time, but it can be changed back to the previous state, when only the N++ backup engine silently handles the unsaved user's data

Possible solutions:

1)
- either we create a new separate N++ message (e.g. IDM_FILE_SAVEALL_AT_SHUTDOWN) and use it [here](https://github.com/notepad-plus-plus/notepad-plus-plus/blob/6803b69c0b92057d2ac5700b7a312a6cf2f82b39/PowerEditor/src/NppBigSwitch.cpp#L2131), then show in its handler new YESNO dialog “Windows restart/shutdown is closing the Notepad++ running. Do you want to save unsaved file(s)?” etc.
- or we adjust the v8.4.3+ [speed exception](https://github.com/notepad-plus-plus/notepad-plus-plus/issues/10995) for the only one dirty file in the [Notepad_plus::fileSaveAll()](https://github.com/notepad-plus-plus/notepad-plus-plus/blob/6803b69c0b92057d2ac5700b7a312a6cf2f82b39/PowerEditor/src/NppIO.cpp#L1669) at the OS restart time to:  `if ((nbDirty == 1) && curBuf->isDirty() && !(NppParameters::getInstance()).isEndSessionStarted())`

2)
If the consistency-view wins, we can use an additional check for the N++ active backup [here](https://github.com/notepad-plus-plus/notepad-plus-plus/blob/6803b69c0b92057d2ac5700b7a312a6cf2f82b39/PowerEditor/src/NppBigSwitch.cpp#L2114) like:

```
// we have unsaved filebuffer(s), give the user a chance to respond (non-critical shutdown and N++ backup-OFF only)
if (!isForcedShuttingDown && isFirstQueryEndSession && !nppParam.getNppGUI().isSnapshotMode())
```

**Comment by donho** [comment]
The save guard (Suspending OS shutting down) is a good idea. The question we should asking ourselves is, what's the proper action when user click on Cancel.

The problem we want to solve is loosing session (and probably loosing the content of unsaved files). This problem happens only while Windows forcing restarting or power loosing. Such problem won't happen when Notepad++ quit normally.

So force users to save all unsaved files could be the solution, but it might not be the best one, IMO.

When user clicks cancel, OS shutting down is suspend - it's the best chance that Notepad++ could quit gracefully. So why don't we suggest users to quit Notepad++ directly? 

Just my 2 cents.

**Comment by xomx** [comment]
> When user clicks cancel, OS shutting down is suspend - it's the best chance that Notepad++ could quit gracefully. So why don't we suggest users to quit Notepad++ directly?

Ok,I like that idea. So what about this - after the user clicked on the "Cancel" at the OS restart screen, there will be a messagebox like: 

a) with the N++ backup ON behind
"Notepad++ has some unsaved file(s) or tab(s). Would you like to save such unsaved data manually before closing the Notepad++?\n\n (otherwise the currently active Notepad++ backup setting will handle that)"

b) with the N++ backup OFF
"Notepad++ has some unsaved file(s) or tab(s). Would you like to save such unsaved data before closing the Notepad++?"

Or you mean something completely different?

**Comment by donho** [comment]
They are 2 good options but what I suggest is even more simple:
When user clicks on **Cancel**, the message "Windows is forcing shutting down, Notepad++ will exit now." with only **OK** button. Notepad++ will be close gracefully after **OK** being clicked whichever backup mode is - if backup mode is ON, then nothing to do and everything will be saved correctly; Otherwise user will be ask for saving files one by one, just as usual.

**Comment by xomx** [comment]
Ok, I see now.
I will need some time to think about it and to test such scenario proposed in a real debugging. (I have a suspicion that for the users, with N++ backup setting ON, it will have no real benefit. Maybe quite the opposite.)

**Comment by donho** [comment]
> (I have a suspicion that for the users, with N++ backup setting ON, it will have no real benefit. Maybe quite the opposite.)

How come "no real benefit"? Could you elaborate it please?

**Comment by xomx** [comment]
I haven't had a time to look more at it yet, but I try to explain what I think for now:

N++ had two serious data-saving problems in the past:
- NUL-bytes issues, but these have been fixed some time ago (nowadays similar reports are always rather something else than such N++ problem)
- and loosing of the session file content during a forced critical OS restart/shutdown, but this has been fixed in v8.4.7+ for good

So in the past anything that could help to bypass such problems should had a high priority. But hopefully, it is not the today's state.

I also has to say here that for me personally my data has higher price than my computers or disks. I usually do not let my programs or OSes to close without properly saving my data first. However, I could not overlook that for many others often easiness or speed has a higher priority than a potential higher safety. And who am I to tell the others what they want.

So I have changed my opinion here and now I agree with [the one](https://community.notepad-plus-plus.org/post/81750), that if the user set the N++ backup engine ON and is relying solely on it for the data saving, we should not bother such user about the unsaved data fact during the OS restart/shutdown. Such user has already decided and simply does not care. If we do not bother such user during the usual manual N++ exit , why should we at the OS restart time? Otherwise for such users there will be two "annoying useless" clicks - on the "Cancel" restart screen option and then on your OK button. They probably rather like the "Restart anyway" way here but without it to appear at all and the necessity to click on it.

All of the above is valid of course only in case that the N++ backup-engine works equally good at the normal N++ exit and when restarting the OS with the N++ still running. And that is something I will have to double-check to be sure.

And for the users, with the N++ backup engine OFF, I would like to maintain the current state with offering the  "Restart Anyway" & "Cancel" and then in the "Cancel" selection case, the SaveAll dlg (it really needs only a little adjustment to fix the only-one-dirty-file inconsistency you have found...).

**Comment by donho** [comment]
The intention of (your) implementation is: when Windows forcing restart and user clicking on Cancel, all the unsaved files should be saved, right?

**Comment by xomx** [comment]
Yes. I would like to prevent a possible data-loss for the users, who do not expect the OS restart or forgot about their unsaved data.

**Comment by xomx** [comment]
> all the unsaved files should be saved, right?

More precise - I would like to give the users a chance to decide, after they select the "Cancel" restart-option, which data should be saved (or not).

**Comment by donho** [comment]
> More precise - I would like to give the users a chance to decide, after they select the "Cancel" restart-option, which data should be saved (or not).

OK, so we are on the same page.
In this case, after **Cancel**, a dialog asking user to exit Notepad++ or not - which is legit since Notepad++ will be closed anyway. 
If **No** is chosen, then user is on his/her own. Otherwise we exit Windows gracefully:
1. Backup mode is ON - Notepad++ exits with data saved.
2. Backup mode is OFF - User will save files one by one manually. 

In all above cases, users have the control, data is saved and no complicate implementation/logic.
What do you think?

**Comment by donho** [comment]
> So what about: "Your current Windows session is about to be terminated. Do you want to exit the Notepad++ now?"

Sounds good to me.

> So when the user chose YES before (please exit the N++), then the N++ shows its standard dlg in such situation (unsaved data), right? I.e.:

Not necessarily. It depends user's options if my recall is good.

> But for all the users, with the N++ backup mode ON, I recommend not initiate the showing of the blue OS restart screen at all (N++ will not return FALSE from its WM_QUERYENDSESSION handler). I mean no "Restart anyway" & "Cancel" possibility. Just let the N++ backup engine to handle that situation itself as in the usual N++ exit case initiated manually by the user.

That's a very good suggestion - but then the logic is more complex. I'm always for the simple solution.
Let's keep this idea in mind and see the reaction of users. We could implement it afterward if needed.

**Comment by xomx** [comment]
> Not necessarily. It depends user's options if my recall is good.

So far I've got only this 2nd one for the only one dirty tab/file:
![save_dlg_-_only_one_dirty](https://user-images.githubusercontent.com/13075183/203391364-bcef32ec-8c9c-4d53-a4a8-8109281c6d57.png)
Otherwise I do not know how to get a different behavior at exit with the N++ backup mode OFF.

> That's a very good suggestion - but then the logic is more complex. I'm always for the simple solution.
> Let's keep this idea in mind and see the reaction of users. We could implement it afterward if needed.

I like KISS. But a user has already reacted - [the Nino-kun reaction](https://community.notepad-plus-plus.org/post/81750) correctly points to this current N++ inconsistent behavior. So if we believe that the N++ backup engine does not have an unknown flaw during the OS restart, then the N++ should behave in the same way in both the manual exit and in the OS forced one.

**Comment by xomx** [comment]
@donho 
I have started to implement your version.

I had to modify the previously proposed text `"Your current Windows session is about to be terminated. Do you want to exit the Notepad++ now?"` a bit, otherwise sometimes (especially when the active N++ tab was not an one with the unsaved data) it was then a little bit confusing, why N++ just did not directly exit and is rather asking for the explicit exit permission. So now, after a user select the "Cancel" restart option, the messagebox  looks like:
![WinSessionExitCancelled-NppBackupOFF-dlg2](https://user-images.githubusercontent.com/13075183/203797679-82a7ed45-ad7c-41c4-8bab-bbda1a0eea77.png)

N++ backup mode is ON, answer:
- YES ... N++ simply quits (N++ backup engine silently handles all the stuff needed)
- NO ... N++ stays running, user is on his/her own

N++ backup mode is OFF, answer:
- YES ... N++ behaves identically as in the case of the usual N++ IDM_FILE_EXIT or WM_CLOSE messages (save dlgs appears etc., it depends on the current user N++ settings)
- NO ... N++ stays running, user is on his/her own

Is that OK?

**Comment by donho** [comment]
@xomx 
That it's perfect! Thank you!

**Comment by xomx** [comment]
@arrmo 
No worry, it is a legitimate interjection here.  To your question - no, in the current state of the proposal, it is not an option.

I owe you an apology myself because I was the one who introduced this not so useful hold up in v8.4.7 for the users with N++ backup mode ON. That is probably the reason I spent for me too much time & words above with backing up the idea to not bother such users. Although I usually have the N++ backup mode OFF, as I use different backup ways.

For you, I can think of about e.g. these options now:
- get accustomed to one more click on the "Restart anyway" option (with N++ backup mode ON behind your data should be backed up as in the case of a usual manual N++ exit)
- patch & build your own version of the N++, simply change [this line](https://github.com/notepad-plus-plus/notepad-plus-plus/blob/6803b69c0b92057d2ac5700b7a312a6cf2f82b39/PowerEditor/src/NppBigSwitch.cpp#L2115) to `if (!isForcedShuttingDown && isFirstQueryEndSession && !nppParam.getNppGUI().isSnapshotMode())` then you will not see the blue OS restart screen with its options at all
- persuade the decision-maker  @donho to accept the above change
- submit a feature request issue about some new relevant setting in the N++ Preferences

Maybe the latest option could be useful even for the users with the N++ backup mode OFF. I can imagine e.g. a situation in which it was more important to not interrupt an non-critical OS restart at all, etc ...

**Comment by arrmo** [comment]
Thanks for the detailed response, appreciate it! And now worries, breaking a few eggs making a cake 😆 

I'm not so worried about the backup before shutdown ... but blocking shutdown is a bit more painful. Any way to avoid that, without turning Backoff OFF?

Thanks again.

**Comment by donho** [comment]
https://github.com/notepad-plus-plus/notepad-plus-plus/commit/bd4c323d75bbe9a565e9bc31bb522133d78421a6

**Comment by xomx** [comment]
@donho 



> > But for all the users, with the N++ backup mode ON, I recommend not initiate the showing of the blue OS restart screen at all (N++ will not return FALSE from its WM_QUERYENDSESSION handler). I mean no "Restart anyway" & "Cancel" possibility. Just let the N++ backup engine to handle that situation itself as in the usual N++ exit case initiated manually by the user.
> 
> That's a very good suggestion - but then the logic is more complex. I'm always for the simple solution. Let's keep this idea in mind and see the reaction of users. We could implement it afterward if needed.

As I expected, there is another user [reaction](https://community.notepad-plus-plus.org/post/82132) similar to the previous [Nino-kun](https://community.notepad-plus-plus.org/post/81750) one.
Let's leave aside the commanding offensive type of that reaction for now, what about some new relevant N++ Preferences setting? E.g. in MISC. some "Allow unsaved data checking at the Windows restart/shutdown" or similar?

And I have in my mind another possible extension in this area - making the N++ a possible ["restartable app"](https://community.notepad-plus-plus.org/topic/20972/are-there-any-plans-to-make-notepad-a-restartable-windows-10-application) in the future, like how e.g. the Google Chrome is now. Then the running N++ session could be automatically reopened after a Windows restart. For that I would need to add some new Preferences setting for sure. What do you think - to MISC. or elsewhere?

**Comment by donho** [comment]
@xomx 
> E.g. in MISC. some "Allow unsaved data checking at the Windows restart/shutdown" or similar?

So the ideal behaviour for you is: 
- Backup mode ON: just quit Notepad++ then restart Windows, **without** blocking dialog.
- Backup mode OFF: with blocking dialog. If user cancel, a dialog ask users to quit Notepad++ - the current behaviour for all situation.  

Do you confirm it?

If yes, please prepare a PR - if the logic and code not complicated, it'll be accepted. But no more settings for such stuff please.

> And I have in my mind another possible extension in this area - making the N++ a possible ["restartable app"](https://community.notepad-plus-plus.org/topic/20972/are-there-any-plans-to-make-notepad-a-restartable-windows-10-application) in the future, like how e.g. the Google Chrome is now. Then the running N++ session could be automatically reopened after a Windows restart. For that I would need to add some new Preferences setting for sure. What do you think - to MISC. or elsewhere?

Why not? But one thing at a time :)

**Comment by xomx** [comment]
@donho 

> Do you confirm it?

Yes.
The backup-mode-ON users then will not see N++ initiating showing of that blue Windows restart screen at all (as before). Even if there will be another app blocking the OS restart and showing that blue screen, the N++ will not be visible there.

> please prepare a PR - if the logic and code not complicated, it'll be accepted. 

OK, probably during this weekend.

> But no more settings for such stuff please.

Understood. So no option in the GUI. Just change in code.

> Why not? But one thing at a time :)

Great. Some arrival for my TODO :-)

**Comment by arrmo** [comment]
This sounds great - thanks!

And restartable ... very cool idea. Appreciated!
