### ISSUE TITLE
Style tokens appear colorless in context menu, and do not apply any style to a selected text

### ISSUE THREAD

**Issue by arnonshp** [notepad-plus-plus/notepad-plus-plus#12564]
### Description of the Issue
Style tokens appear colorless in context menu, and do not apply any style to a selected text.

### Steps to Reproduce the Issue
1. Select text
2. Right-click
3. Choose "Style Token"

### Expected Behavior
![image](https://user-images.githubusercontent.com/8546722/203766774-4d3595b4-6fdb-4079-98c5-6c4d32206073.png)

### Actual Behavior

![image](https://user-images.githubusercontent.com/8546722/203766422-de7d1474-0350-41a7-b887-dbbe9f85cc87.png)

### Debug Information
Notepad++ v8.4.7   (32-bit)
Build time : Nov  1 2022 - 23:29:20
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 10 Enterprise (64-bit) 
OS Version : 21H2
OS Build : 19044.2251
Current ANSI codepage : 1252
Plugins : 
    mimeTools (2.9)
    NppConverter (4.5)
    NppExport (0.4)
    NppXmlTreeviewPlugin (2)

**Comment by ArkadiuszMichalski** [comment]
@arnonshp What theme are you using? Dark Mode is on? Can you check with the portable version if this problem exists?

**Comment by arnonshp** [comment]
Dark mode was off. Theme was set to "Default (stylers.xml)".Changing to any other them resolved the issue. Thanks for your prompt response!
