### ISSUE TITLE
Sass compiler

### ISSUE THREAD

**Issue by Nodir-any** [notepad-plus-plus/notepad-plus-plus#12562]
### Description of the Issue
Sass compiler is needed for Web Devs, however it is not currently possible in Notepad++ to install extansion for it. 
Please consider adding such extension for Sass

**Comment by CennoxX** [comment]
You can install sass and add a user defined command to compile to your shortcuts.xml . https://npp-user-manual.org/docs/config-files/#keyboard-shortcuts-shortcuts-xml

**Comment by alankilborn** [comment]
>Sass compiler is needed for Web Devs, however it is not currently possible in Notepad++ to install extansion for it.
Please consider adding such extension for Sass

Not really something that would ever be done; best approach is @CennoxX 's advice.
Please CLOSE this issue.
