### ISSUE TITLE
Tab menu: "Reload from Disk" is wrongly enabled in new documents

### ISSUE THREAD

**Issue by Yaron10** [notepad-plus-plus/notepad-plus-plus#12579]
**STR:**
Open a new document.
Right-click on its tab to display the context-menu.

**Result:**
"Reload from Disk" is wrongly enabled.
(Correctly disabled in the File menu).

***
Notepad++ v8.4.7.

**Comment by Yaron10** [comment]
@alankilborn,

If you use the new `tabContextMenu.xml`, you get "Reload from Disk". :)

**Comment by alankilborn** [comment]
>If you use the new tabContextMenu.xml, you get "Reload from Disk"

Ah, OK, but this complaint is against 8.4.7.
But, I understand...

**Comment by Yaron10** [comment]
@donho,

👍 
Thank you.
