### ISSUE TITLE
Virus detected

### ISSUE THREAD

**Issue by DerBasler** [notepad-plus-plus/notepad-plus-plus#12577]
**Issue:**
1 Virus scanner report a Trojan in the latest exe

**How To Reproduce:**
Download and reupload the latest exe to virustotal.com or visit
https://www.virustotal.com/gui/file/515d2c71ece7c4c7432794b9e1bb6fcf60fdaa2e499744c09af113c65d6dbb68

**Expected Behavior:**
No virus flaged

**Additional context:**
This might be a false positive but this only seams to appear after the [(Stand up for Ukraine)] editiion https://www.virustotal.com/gui/file/662450bbbe1d642bddd5501f65de830341ac4c7846b4fe9ad8512c9e2888d129?nocache=1  so this was strange.

**Comment by CennoxX** [comment]
> Download and reupload the latest exe to virustotal.com or visit
> https://www.virustotal.com/gui/file/515d2c71ece7c4c7432794b9e1bb6fcf60fdaa2e499744c09af113c65d6dbb68

On this site I see a "No security vendors and no sandboxes flagged this file as malicious". Could you add a screenshot of the part, where the trojan is reported?

**Comment by DerBasler** [comment]
Sure
![image](https://user-images.githubusercontent.com/45329909/204556715-0cece11a-fdf7-46b6-92ba-3c63711cc73b.png)

**Comment by donho** [comment]
It's false positive due to NSIS.
Please report it to your virus vendor.
