### ISSUE TITLE
Find/Replace dialog doesn't find occurrencies on searching text with a leading or ending space(s)

### ISSUE THREAD

**Issue by maufirma** [notepad-plus-plus/notepad-plus-plus#12578]
### Description of the Issue
Search/Replace doesn't find occurencies when searching text with a leading space character in "Find What" field. 

### Steps to Reproduce the Issue
1. Create a new black file
2. Write some text with some spaces character (i.e. "abc cde fgh") in it
3. HIt Ctrl+H to open the Replace dialog window
4. Type a space followed by a sequence of characters included in text (i.e. " cde")

### Expected Behavior
NP++ finds the string in "Find what:" field and enlights it, if present

### Actual Behavior
NP++ doesn't find occurrencies of the searched string; note that if you search a text without a leading space, all works as usual
Same bug with ending spaces on text to be find.

### Debug Information
Notepad++ v8.4.7   (64-bit)
Build time : Nov  1 2022 - 23:31:11
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 10 Enterprise (64-bit) 
OS Version : 21H2
OS Build : 19044.2132
Current ANSI codepage : 1252
Plugins : 
    mimeTools (2.9)
    NppConverter (4.5)
    NppExport (0.4)

The bug appeared from 8.4.6 version of Notepad++
![image](https://user-images.githubusercontent.com/89565245/204240454-2806a4f4-65b2-4775-a8c5-ebe47d29906a.png)

**Comment by ArkadiuszMichalski** [comment]
@maufirma Uncheck `Match whole word only` because space is not considered as part of the word

**Comment by alankilborn** [comment]
@maufirma Become familiar with how searching works, especially the control in question; read [HERE](https://npp-user-manual.org/docs/searching/#:~:text=%E2%98%90-,Match%20whole%20word%20only,-%3A%20if%20checked%2C%20searches).
