### ISSUE TITLE
Compare can cause tab text to flicker rapidly.

### ISSUE THREAD

**Issue by urnati** [notepad-plus-plus/notepad-plus-plus#12582]
### Description of the Issue
When comparing two files one or both tabs will flicker making the text unreadable.
I use Lua for World of Warcraft scripting.

### Steps to Reproduce the Issue
1. Typically two code files; same name; in two different folders; 1k lines or more(?)
2. 'Fold' one of them to level 1
3. Then scroll to see differences
4. The flicker is usually near the end of the file compare; fairly consistent that it happens.
### Description of the Issue
When comparing two files one or both will flicker making the text unreadable.
I use Lua for World of Warcraft scripting.

### Steps to Reproduce the Issue
1. Typically two code files; same name; in two different folders; 1k lines or more(?)
2. 'Fold' one of them to level 1
3. Then scroll to see differences
### Expected Behavior
No flicker.
Although I realize the visual of comparing two files while one is folded is not always useful...

### Actual Behavior
One or both tabs begin flickering.
Typically the tab with the 'folded' file.
You can cancel the compare or close the flickering tab(s) so NotePad++ is still useable.

### Debug Information
Notepad++ v8.4.7   (32-bit)
Build time : Nov  1 2022 - 23:29:20
Path : C:\Software\Notepad++\notepad++.exe
Command Line : "C:\Users\Dave\Documents\Projects\TitanPanel\TitanPanelRetail\Titan\TitanUtils.lua"
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 10 Home (64-bit) 
OS Version : 21H2
OS Build : 19044.2251
Current ANSI codepage : 1252
Plugins : 
    ComparePlugin (2.0.1)
    mimeTools (2.9)
    NppConverter (4.5)
    NppExport (0.4)

Attached are two files as an example. On my system they are .lua files and are same name in two different folders (SCM and game folders).
If it helps I have a Gigabyte GeForce RTX 3060 video card.

[TitanRepairNew.txt](https://github.com/notepad-plus-plus/notepad-plus-plus/files/10113452/TitanRepairNew.txt)
[TitanRepair.txt](https://github.com/notepad-plus-plus/notepad-plus-plus/files/10113458/TitanRepair.txt)

**Comment by Yaron10** [comment]
@urnati,

Please try ComparePlus.

https://community.notepad-plus-plus.org/topic/23434/new-plugin-compareplus-v1-0-0.
https://github.com/pnedev/comparePlus/releases.

**Comment by urnati** [comment]
Thank you for the quick reply!
At first attempt ComparePlus appears to resolve the problem.

It is not your issue but ComparePlus seems a bit clunky. And the color choices awful for my old eyes! Guess I'll be playing in the settings...

Seeing the new functionality, I'll close this. I'll open another ticket if it is not working as expected.
Thanks again.

**Comment by Yaron10** [comment]
@urnati,

My pleasure.
And the flowers to @pnedev. :)

> It is not your issue but ComparePlus seems a bit clunky. And the color choices awful for my old eyes! Guess I'll be playing in the settings...

I'm sure it should be fine.
If you still have a problem, please open an issue in https://github.com/pnedev/comparePlus and attach some screenshots.

**Comment by pnedev** [comment]
Thank you for resolving this query Yaron :+1: 

@urnati ,

As Yaron suggested, please use [ComparePlus](https://github.com/pnedev/comparePlus) repository to report issues with file comparisons in Notepad++.

BR
