### ISSUE TITLE
v8.4.7 regression: Default Language not working for the first empty file with empty Notepad++ session

### ISSUE THREAD

**Issue by pryrt** [notepad-plus-plus/notepad-plus-plus#12586]
I am reporting this issue on behalf of [this forum post](https://community.notepad-plus-plus.org/topic/23826/new-document-default-langauge-not-working-for-new-np-instance), since the user who reported it there probably doesn't have a github account.  I will quote their description below, and then add in my confirmation

### Description of the Issue

> Hi,

> I’ve noticed that when I start a new instance of Notepad++ the “New 1” document isn’t set as HTML (my New document | Default language setting).

> Works fine if I create a new document via File | New.

> Seems like it’s started happening since v8.4.7 - just wondering if this is happening for others too?

> thanks, Craig.

> My Debug Info:

> Notepad++ v8.4.7 (64-bit)
> Build time : Nov 1 2022 - 23:31:11
> Path : C:\Program Files\Notepad++\notepad++.exe
> Command Line :
> Admin mode : OFF
> Local Conf mode : OFF
> Cloud Config : OFF
> OS Name : Windows 10 Enterprise (64-bit)
> OS Version : 21H2
> OS Build : 19044.2251
> Current ANSI codepage : 1252
> Plugins :
> BetterMultiSelection (1.5)
> DSpellCheck (1.4.24)
> HexEditor (0.9.12)
> HTMLTag (1.3.5)
> mimeTools (2.9)
> NppExport (0.4)
> PythonScript (2)
> QuickColorPicker (2.1.2.1)
> XBrackets (1.3.1)

---
[end of Craig's text]

### Steps to Reproduce the Issue

I used these steps to confirm Craig's results.

0. Start with fresh 8.4.7 portable, so no other settings or plugins get in the way
1. **Settings > Preferences > New Document > Default Language** = `HTML`
2. Close all open files (to make sure the session is empty)
3. Exit Notepad++
4. Run notepad++ again: the default `new 1` is "Plain Text", not "HTML"
5. Use **File > New** or equivalent, and `new 2` is correctly "HTML"
6. Close `new 1` and leave `new 2` open
7. Use **File > New** or equivalent, and the newly-created `new 1` is is also correctly "HTML".
8. Close `new 1`.
9. Exit Notepad++
10. Run Notepad++ again: the default `new 1` is "Plain Text", not "HTML"

### Expected Behavior

When Notepad++ is opened with no files in the current session, I expect it to follow the **Settings > Preferences > New Document > Default Language** for `new 1`.  

In v8.4.6, the `new 1` for a new run was correctly HTML (ie, followed the expected behavior).
```
Notepad++ v8.4.6   (64-bit)
Build time : Sep 25 2022 - 19:51:39
Path : C:\usr\local\apps\npp\npp.8.4.6.portable.x64\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : ON
Cloud Config : OFF
OS Name : Windows 10 Enterprise (64-bit) 
OS Version : 20H2
OS Build : 19042.2251
Current ANSI codepage : 1252
Plugins : 
    mimeTools (2.8)
    NppConverter (4.4)
    NppExport (0.4)
```

### Actual Behavior

When Notepad++ is opened with no files in the current session, `new 1` was "Normal text file" despite **Settings > Preferences > New Document > Default Language** being set to `HTML`.  I confirmed this regression in my portable v8.4.7.
```
Notepad++ v8.4.7   (64-bit)
Build time : Nov  1 2022 - 23:31:11
Path : C:\usr\local\apps\npp\npp.8.4.7.portable.x64\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : ON
Cloud Config : OFF
OS Name : Windows 10 Enterprise (64-bit) 
OS Version : 20H2
OS Build : 19042.2251
Current ANSI codepage : 1252
Plugins : 
    mimeTools (2.9)
    NppConverter (4.5)
    NppExport (0.4)
```

Since this worked as expected in v8.4.6 and now doesn't in v8.4.7, I assume this regression came about because of #11504 (but that is just an assumption)

--
_update_: I removed my use of "instance" (though I kept it in the quote from Craig): the problem is **not** specific to multi-instance mode.  As the steps I described show, it happens even when you just have one instance of Notepad++ running at a time, with the unedited (default setting) of single-instance-mode.

**Comment by rdipardo** [comment]
Since a265997, the value of `NewDocDefaultSettings::_lang` is only ever checked when `File > New` executes [^1].

~~~sh-session
$ git grep -n "ndds._lang" -- PowerEditor/src/ScintillaComponent/Buffer.cpp

PowerEditor/src/ScintillaComponent/Buffer.cpp:1303:     newBuf->_lang = ndds._lang;
~~~

The user-preferred default used to be assigned [in the constructor][0], which runs without user intervention.

> this worked as expected in v8.4.6 and now doesn't in v8.4.7,

I would aim for restoring the behaviour of 8.4.__*4*__; versions 8.4.5 - 8.4.6 were even more regressive in terms of file type detection:

- #12226
- #12253
- #12378

[^1]: https://github.com/notepad-plus-plus/notepad-plus-plus/blob/aa8ae48b9946d0a26b1e51564246bb1dc981a827/PowerEditor/src/ScintillaComponent/Buffer.cpp#L1290-L1303

[0]: https://github.com/notepad-plus-plus/notepad-plus-plus/blob/a610387fb40411f992f1fea38c9e7eaa7cf5c8cc/PowerEditor/src/ScintillaComponent/Buffer.cpp#L82

**Comment by pryrt** [comment]
> I would aim for restoring the behaviour of 8.4.4

Just to be clear, I am hoping that whatever change gets implemented as a result of this issue just affects the first `new 1` on a new run -- I don't want all the hard work to get all the other file detection working right to be undone.  (Personally, given a choice between going back to v8.4.4 behavior and getting this fixed, I'd rather have everything else working and this ignored, but I somehow doubt Craig would agree with me.)
