### ISSUE TITLE
Texted selected and copied with "column mode" not pasting correctly in 8.4.7

### ISSUE THREAD

**Issue by bkirkland13** [notepad-plus-plus/notepad-plus-plus#12594]
### Description of the Issue
Prior to version 8.4.7, when selecting text using ALT+SHIFT, you could copy and paste and Notepad++ would paste as a column. After updating to 8.4.7, this no longer works.

### Steps to Reproduce the Issue
Given the following text:
```
abc 12
def 34
ghi 56
jkl 78
```

1. Move cursor immediately before "56"
2. Hold ALT+Shift
3. Select 56, as well as 78 on the next line
4. Release ALT+SHIFT
5. Cut selection to clipboard
6. Move cursor to immediately after 12
7. Paste clipboard

### Expected Behavior
```
abc 1256
def 3478
ghi 
jkl 
```

### Actual Behavior
```
abc 1256
78

def 34
hij 
klm 
```

### Debug Information
Notepad++ v8.4.7   (32-bit)
Build time : Nov  1 2022 - 23:29:20
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Command Line : "C:\Program Files (x86)\Notepad++\change.log" 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 10 Enterprise (64-bit) 
OS Version : 21H2
OS Build : 19044.2251
Current ANSI codepage : 1252
Plugins : 
    ComparePlugin (2.0.1)
    mimeTools (2.9)
    NppConverter (4.5)
    NppExport (0.4)
    Tidy2 (0.2)
    XMLTools (3.1.1.13)

**Comment by alankilborn** [comment]
If I try it, in Notepad++ v8.4.7 (32-bit), I get exactly your expected behavior.

**Comment by bkirkland13** [comment]
Well that's embarrassing... You are correct.

I assumed it was related to the update as it worked yesterday, but not today immediately after updating to 8.4.7. It appears that my issue was due to having an N-Able TakeControl session open to another machine with clipboard sharing enabled. After disconnecting that session, it works properly again.

**Comment by alankilborn** [comment]
No problem.  In the future, you could possibly eliminate the drudge work of creating an issue, if you experience what you think is a problem:  Check out the user support site at https://community.notepad-plus-plus.org/.
