### ISSUE TITLE
CMake support

### ISSUE THREAD

**Issue by rcdailey** [notepad-plus-plus/notepad-plus-plus#126]
@donho I'm implementing some CMake scripts. However, if possible, I want to take the opportunity to modularize the project a little bit. Right now everything has been monolithically placed in a single project. I'd like to decompose it into a few distinct pieces if possible.

After a bit of analysis, I found the following decomposition a rough step in the "feel good" direction:

* sqlite
* TinyXML (Downloaded latest version; not sure what the "A" version of tinyxml was for)
* MISC
* ScintillaComponent
* WinControls
* Notepad++

Everything except for the last item would be compiled in its own CMake project as a static library. However, there are a ton of dependency issues here so I want to ask your opinion on this.

It isn't clear which direction dependencies flow. It seems rather spaghetti at the moment. Any feedback? Thanks.

**Comment by MAPJe71** [comment]
You might want to consider to include the following as separate projects:
 - ChangeIcon
 - IExplorerShell
 - NppShell
 - xmlApiSorter
 - xmlUpdater

They each compile into a separate PE i.e. Exe, Dll, Dll, Exe and Exe resp.

**Comment by rcdailey** [comment]
Thanks for the idea. At the moment I'm just trying to sort out the mess of the main app. The other apps seem simpler.

**Comment by donho** [comment]
@rcdailey What do you mean "decompose" exactly? Make them in lib or dll?

**Comment by rcdailey** [comment]
@donho You have a very large code base. Everything is clumped together and built as a single executable. However, you obviously have common code (WinControls is a good example) which should be separated out.

At the moment I am trying to build a few key pieces as static libraries. This is a means to allowing code to be compiled in isolation. This will expose circular dependencies and other dependency problems. It also encourages proper modularization of code and code location.

When everything is just one big blob of source files, you won't see these problems.

**Comment by ariccio** [comment]
Another good idea would be to split components into their own repositories and use git subtrees to combine them. This would allow plugin developers to easily update shared headers, as part of version control. I discussed this as part of #103.

**Comment by ariccio** [comment]
....but reorganization is neither a "bug-fix", nor a "feature request", and the official policy is:


> Only bug-fix and feature request will be accepted. 

So this won't be accepted.

**Comment by donho** [comment]
@rcdailey 
Decomposing Notepad++ and building the key pieces as static libaries sounds a good idea for me.
However this task will take time and there's no strong relation with CMakefile. 

For me, CMakefile can be done with the current structure of project, and if you want you can create another issue for it and create another branch in your repository for building the static lib, with the suitable CMakeFile.

**Comment by milipili** [comment]
@rcdailey I intend to provide a cmake lists (as an alternative build tool for now). To avoid useless work on both sides, do you have started something ?
