### ISSUE TITLE
"Blank Operations" should work on a selection of lines of text

### ISSUE THREAD

**Issue by alankilborn** [notepad-plus-plus/notepad-plus-plus#12602]
### Description of the Issue
Some users think that if they make a selection of lines, then choose _Edit_ > _Blank operations_ > _Trim Leading Space_, for example, that only the lines that are selected should be affected by the operation, not all lines in the currently active document.  Reference [THIS](https://community.notepad-plus-plus.org/topic/23847) Community thread.

### Steps to Reproduce the Issue

1. Create a new tab and paste the following data:
```
4
     Inf 795
     Sup 793
       Izq 1923
        Der 1923
5
         Inf 799
         Sup 800
          Izq 1920
           Der 1920

  6.    
           Inf 800
            Sup 800
              Inz 2010
               Der 2007

7.        
               Inf 797
                Sup  800
                 Izq 2090
                  Der 2093
```
2. Selected lines 1-10:
![image](https://user-images.githubusercontent.com/77065706/205515525-d1805586-c0d9-4d3b-900d-f0bd058cd72d.png)

3. Execute _Edit_ > _Blank operations_ > _Trim Leading Space_

### Expected Behavior
![image](https://user-images.githubusercontent.com/77065706/205515469-c185d247-4ca9-4de9-96ec-4aa4777e7715.png)

### Actual Behavior
![image](https://user-images.githubusercontent.com/77065706/205515499-35988142-a0fa-4f37-a21f-64c4871759bb.png)

### Debug Information
Notepad++ v8.4.7   (64-bit)
Build time : Nov  1 2022 - 23:31:11
Path : C:\\...\npp.8.4.7.portable.x64\notepad++.exe
Command Line : -titleAdd="8.4.7 64-bit" -multiInst
Admin mode : OFF
Local Conf mode : ON
Cloud Config : OFF
OS Name : Windows 10 Enterprise (64-bit) 
OS Version : 21H2
OS Build : 19044.2130
Current ANSI codepage : 1252
Plugins : 
    mimeTools (2.9)
    NppConverter (4.5)
    NppExport (0.4)
    PythonScript (3.0.14)

**Comment by donho** [comment]
https://github.com/notepad-plus-plus/notepad-plus-plus/commit/a0c41cc5a5b42c1255d47cc7d29a7da0b02bc44d
