### ISSUE TITLE
No selectable color for EOL symbols (+request: nicer EOL symbols, paragraph symbol)

### ISSUE THREAD

**Issue by fade0ff** [notepad-plus-plus/notepad-plus-plus#1260]
In the current form, the EOL symbols ("Show end of line") are hardly usable because they are much too distracting due to their size, background filling and color (same as the text).
As first step, I would suggest to add the ability to change their color, so they can be displayed in e.g. a shade of gray to make them less distracting.
However, I'd also suggest to rework them to a "nicer" look and/or an option to just display a "paragraph" symbol as this is done in the Eclipse editor (or UltraEdit) instead of separate CR/LF symbols. While it can make sense to display CR/LF explicitly, most of the times only the general paragraph information is needed.

**Comment by aaaxx** [comment]
Since you're more interested in generic paragraph symbol than the actual characters it sounds like you're actually worried about trailing whitespaces. If that's the case, you can check out the option to “Show White Space and TAB” only (no EOL), in Shortcut Mapper.

Having said that, you're right about EOL symbols needing a less ugly design and a separate option in Style Configurator.

**Comment by fade0ff** [comment]
I already enabled the white spaces and tab display of course. Yet being able to see paragraphs goes a bit beyond detecting trailing spaces - even though this also helps a bit.
E.g. it's much better to see if a line was wrapped or if there is a manual line feed. Yes, you can also see this from the line numbers if they're displayed. Still a proper paragraph display is one of my main issues with Notepad++.

**Comment by dail8859** [comment]
Just as an FYI, this is not something Scintilla supports, which means Notepad++ can't do it. Quote from the [Scintilla documentation](http://www.scintilla.org/ScintillaDoc.html#Styling):

> **STYLE_CONTROLCHAR** This style sets the font used when drawing control characters. Only the font, size, bold, italics, and character set attributes are used and not the colour attributes.

I agree it would be nice to be able to set the color, but it would have to be something Scintilla implements.

**Comment by sanastasiou** [comment]
@fade0ff so - what @dail8859  said. Open up a feature request at Scintilla. If they implement it.. then you may get what you want in the futrue.

Feature request : http://sourceforge.net/p/scintilla/feature-requests/

**Comment by fade0ff** [comment]
OK, I created a ticket #1129 there. Let's hope I didn't completely disgrace myself as obviously I don't know heck where NPP starts and where Scintilla ends.

**Comment by xylographe** [comment]
Scintilla ticket `#1129`: https://sourceforge.net/p/scintilla/feature-requests/1129/

**Comment by wernerschka** [comment]
I support this feature request very much, and I accord with @fade0ff ideas 100%. I already posted my comment in scintilla's sourforge ticket. Let's see what scintilla's developers think...

But if they'are refusing to implement this feature: Would it be technically possible to code an alternative solution directly within Notepad++ source code, to get this or some similar option to change the style of non printable characters?

**Comment by dail8859** [comment]
> if they'are refusing to implement this feature

AFAIK they never said it was a bad idea, just that someone has to take the time to do it implement/test it.

> Would it be technically possible to code an alternative

No. The only way is to modify Scintilla since it handles the low level drawing functions.

**Comment by dogancelik** [comment]
Also [discussed in 2010, 2011, 2012](https://sourceforge.net/p/notepad-plus/discussion/331754/thread/2eeb88f4/) and mentioned in [this SuperUser question in 2015](https://superuser.com/questions/945856/styling-of-notepad-end-of-line-eol-symbols-cr-and-lf).

I really want to make EOL characters same color as TAB colors (orange), possibly smaller than visible characters.

Current:
![Current](https://user-images.githubusercontent.com/486818/48441733-5531aa00-e79d-11e8-98cf-d7d86bf1c254.png)

Request:
![Request](https://user-images.githubusercontent.com/486818/48441737-57940400-e79d-11e8-8571-9f0163a3eb9a.png)

**Comment by MetaChuh** [comment]
can't be fixed in notepad++, please report your issue to the scintilla project.
-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)

**Comment by jparrot99** [comment]
This is now marked as "completed" in Scintilla:
    [https://sourceforge.net/p/scintilla/feature-requests/1129/](https://sourceforge.net/p/scintilla/feature-requests/1129/)
Does that mean we can now use this in Notepad++ somehow?

**Comment by sasumner** [comment]
I got an email from github with user "jparrot99" saying the following, but it is not here so I'm adding it:

>This is now marked as "completed" in Scintilla:
>https://sourceforge.net/p/scintilla/feature-requests/1129/
>Does that mean we can now use this in Notepad++ somehow?

**Comment by sasumner** [comment]
Ach, never mind, looks like a user-headspace error. :-)

Nothing new on that Scintilla request since 2015!

**Comment by fade0ff** [comment]
It's really a shame that there is no progress whatsoever. Every time I need to display line breaks/carriage returns, it's like a punch in the stomach. Again and again for >5 years. This is one of the main reasons (apart from large files and some multi-line RegEx issues) for me to return to UltraEdit now and then. I really don't get how anybody involved in Scintilla or NPP could be OK with this.

**Comment by sasumner** [comment]
> I really don't get how anybody involved in ... NPP could be OK with this.

As stated earlier, it is 100% controlled by Scintilla.
Thus, someone "involved in N++" has no choice about being "OK" or being "not OK" with it.

**Comment by dogancelik** [comment]
@fade0ff please comment in [this issue](https://sourceforge.net/p/notepad-plus/discussion/331754/thread/2eeb88f4/) so the Scintilla developers can prioritize it.

**Comment by DietmarSchwertberger** [comment]
The Scintilla developers won't prioritize this...
If nobody else volunteers, it won't happen.

**Comment by sasumner** [comment]
>If nobody else volunteers, it won't happen.

There's a volunteer ... his name is @DietmarSchwertberger !
:-)

**Comment by DietmarSchwertberger** [comment]
Rather not. I have other projects. If someone organizes a bounty, I would pay some Euros / Dollars, though.

**Comment by fade0ff** [comment]
Looks like after all these years, the color/style feature was finally added in Scintilla:
https://sourceforge.net/p/scintilla/feature-requests/1129/#46ef
--> SCI_SETREPRESENTATIONAPPEARANCE and SCI_SETREPRESENTATIONCOLOUR were added...
Can we hope for the update in Notepad++ now?

**Comment by sasumner** [comment]
>Can we hope for the update in Notepad++ now?

Probably, as long as one realizes that "now" would mean after these things:

* a release of Scintilla with that feature in it
* a Scintilla change-of-version within Notepad++ (a somewhat rare event)
* someone doing a PR to use the new Scintilla commands

**Comment by i3v** [comment]
Just in case: [here](https://github.com/notepad-plus-plus/notepad-plus-plus/pull/11773#issuecomment-1152273735)'s how to set the color now.
