### ISSUE TITLE
Don't populate Find-what if enough text selected to auto-select In-selection

### ISSUE THREAD

**Issue by alankilborn** [notepad-plus-plus/notepad-plus-plus#12603]
### Description of the Issue
If a stream selection of 1024 or more characters is selected when _Find_ is invoked, the _In selection_ checkbox will be checked automatically.  In this case, the _Find what_ box should NOT be populated with the text of the selection, but it is.

This issue was first raised on the Community site [HERE](https://community.notepad-plus-plus.org/topic/23845).

### Steps to Reproduce the Issue

1. Create a N++ tab with more than 1024 characters using this data
```
aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb
cccccccccccccccccccccccccccccccccccccccccccccccc
dddddddddddddddddddddddddddddddddddddddddddddddd
eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee
ffffffffffffffffffffffffffffffffffffffffffffffff
gggggggggggggggggggggggggggggggggggggggggggggggg
hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh
iiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiii
jjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjj
kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk
llllllllllllllllllllllllllllllllllllllllllllllll
mmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmm
nnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnn
oooooooooooooooooooooooooooooooooooooooooooooooo
pppppppppppppppppppppppppppppppppppppppppppppppp
qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq
rrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr
ssssssssssssssssssssssssssssssssssssssssssssssss
tttttttttttttttttttttttttttttttttttttttttttttttt
uuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuu
vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww
xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy
zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz
```
2. Select all text with Ctrl+a
3. Invoke _Find_ with Ctrl+f

### Expected Behavior
Find window appears with _In selection_ checked but the _Find what_ box NOT being populated with the selected text.

### Actual Behavior
Find window appears with _In selection_ checked and the _Find what_ box is pre-populated with the selected text.

### Debug Information
Notepad++ v8.4.7   (64-bit)
Build time : Nov  1 2022 - 23:31:11
Path : C:\\...\npp.8.4.7.portable.x64\notepad++.exe
Command Line : -titleAdd="8.4.7 64-bit" -multiInst
Admin mode : OFF
Local Conf mode : ON
Cloud Config : OFF
OS Name : Windows 10 Enterprise (64-bit) 
OS Version : 21H2
OS Build : 19044.2130
Current ANSI codepage : 1252
Plugins : 
    mimeTools (2.9)
    NppConverter (4.5)
    NppExport (0.4)
    PythonScript (3.0.14)

**Comment by Yaron10** [comment]
@alankilborn,

> But… it does seem a bit inconsistent and “at odds” that when enough text is selected to cause In selection to be auto-checked, that the selected data is also copied into the Find what box.

You in the forum.
👍 

For my personal use I made the following changes:
1. No difference between 1 char and 1024.
2. If there's a selection, _enable_ the `InSelection` CheckBox, but _do not auto-check it_.

I had other reasons for that change (switching between tabs and more).
