### ISSUE TITLE
On Windows shutdown

### ISSUE THREAD

**Issue by mrp100461** [notepad-plus-plus/notepad-plus-plus#12612]
When closing windows if np++ is open it asks to close tab it was in, this never use to happen

1. Edit NP tab 
2. Shutdown windows
3.  Stop you from shutting down windows unless say continue

Windows shuts down without any errors

Notepad++ v8.4.7   (64-bit)
Build time : Nov  1 2022 - 23:31:11
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 10 Pro (64-bit) 
OS Version : 21H2
OS Build : 19044.2251
Current ANSI codepage : 1252
Plugins : 
    mimeTools (2.9)
    NppConverter (4.5)
    NppExport (0.4)
    XMLTools (3.1.1.12)

**Comment by AntonioCS** [comment]
Yes, I am getting exactly this.
This dialog pops up:
![image](https://user-images.githubusercontent.com/1086401/206562496-1271cca6-b2e9-47ff-97d6-d2457d9f5639.png)

I used to just shutdown windows with notepad++ open without any issues, but now every time I forget to close notepad++ and start the shutdown process, I have to cancel and manually close notepad++ and then shutdown.

**Comment by xomx** [comment]
Already [fixed](https://github.com/notepad-plus-plus/notepad-plus-plus/commit/6c9f4cdff37e8b15207c3044efd54a425529ec4c), will be in the next N++ version.
