### ISSUE TITLE
SQL Syntax Highlighter Issue with CASE statement

### ISSUE THREAD

**Issue by pamanes** [notepad-plus-plus/notepad-plus-plus#12610]
### Description of the Issue
SQL file syntax highlighter fails when a case is involved in a specific way

### Steps to Reproduce the Issue

1. Create new File
2. Paste the following SQL code:
      `UPDATE U SET
	      Title = xt.Title
      OUTPUT 
			      case when (inserted.nt_account is not null and charindex('\', inserted.nt_account) > 0) then
				      substring(inserted.nt_account, 1, charindex('\', inserted.nt_account) - 1)
			      else
				      null
			      end domain
      INTO dbo.TABLE
      FROM
	      dbo.TABLE2 xt`
4. Save as SQL file type

### Expected Behavior
Code after chardindex should not be gray as it's not comments

### Actual Behavior
You will notice the code after charindex is GRAY as if they were comments but they are not

![image](https://user-images.githubusercontent.com/1147472/205949987-1f4a9460-61ab-4f1c-912d-1a73c9139856.png)

**Comment by rdipardo** [comment]
P.S. 
In the meantime, there's a (rather dated) UDL for MS SQL Server 2008 that might be more suitable: https://github.com/notepad-plus-plus/userDefinedLanguages/blob/master/UDLs/T-SQL-MSServer2008r2_bySergeyIvanov.xml

**Comment by rdipardo** [comment]
P.P.S.
I forgot to mention there's a simple, immediate solution to the reported issue:

1. <kbd>Settings</kbd>
2. <kbd>Language</kbd>
3. Uncheck the "Treat backslash as escape character or SQL" option

![ignore_bkslash_esc](https://user-images.githubusercontent.com/59004801/206081059-98c14514-57f6-4478-866b-2d7fffbd108b.png)

The extra stuff above is still relevant, but probably more useful as an independent issue.

@pamanes, feel free to close this ticket if the workaround does the trick.

**Comment by ArkadiuszMichalski** [comment]
Switch option as suggested above.

**Comment by pamanes** [comment]
thanks! that workaround works really well
