### ISSUE TITLE
autosave issue

### ISSUE THREAD

**Issue by PraetorAngel** [notepad-plus-plus/notepad-plus-plus#12622]
I updated notepad++ about a week ago, and when i quit out of it it popped up a new dialog that said something like " prompt to save when closing? y/n/never show" and now instead of just closing normally and saving the session, it prompts me to save every time with a save as dialog.

how can I turn the save on exit dialog back off?

**Comment by alankilborn** [comment]
See [HERE](https://community.notepad-plus-plus.org/topic/23864/save-on-exit-preventing-computer-reboot).

**Comment by donho** [comment]
https://github.com/notepad-plus-plus/notepad-plus-plus/commit/6c9f4cdff37e8b15207c3044efd54a425529ec4c
