### ISSUE TITLE
Moving tab very slow if Document List Panel is open with many tabs

### ISSUE THREAD

**Issue by SlugFiller** [notepad-plus-plus/notepad-plus-plus#12632]
### Description of the Issue
When the Document List Panel is open, and many tabs are open, dragging a tab, or moving it using shift+mouse wheel, causes the Document List to completely reload, by removing all the items, then re-adding them. If there are many tabs, the process takes a couple of seconds (!!), and is repeated on every single movement of the tab, even if still holding the button down in a mouse drag.

### Steps to Reproduce the Issue
1. Open NotePad++
2. View->Document List
3. Hold Ctrl+N for a couple of seconds
4. Hover the mouse over the tab bar
5. Hold shift, and roll the mouse wheel down.

### Expected Behavior
The tab just moves, and I can continue moving it or working with the document

### Actual Behavior
The Document List's scroll bar goes crazy for a while as all the opened tabs first disappear, then reappear in the new order. About 5-6 seconds of work time are lost, and that's for a single movement. If wanting to move, say, the first tab to the end, a few minutes would be required.

### Debug Information

Notepad++ v8.4.6   (32-bit)
Build time : Sep 25 2022 - 19:55:26
Path : C:\Apps\NotepadPP\notepad++.exe
Command Line : "C:\Docs\Programs\mollyim-android\libsignal\service\src\main\java\org\whispersystems\signalservice\internal\websocket\WebSocketConnection.java"
Admin mode : OFF
Local Conf mode : ON
Cloud Config : OFF
OS Name : Windows 10 Enterprise (64-bit) 
OS Version : 22H2
OS Build : 19045.2251
Current ANSI codepage : 1252
Plugins : 
    ComparePlugin (2.0.2)
    DSpellCheck (1.4.24)
    HTMLTag_unicode (1.2.3)
    LocationNavigate (0.4.8.1)
    mimeTools (2.8)
    MultiClipboard (2.1)
    NppConverter (4.4)
    NppExport (0.4)
    NPPJSONViewer (1.40)
    NppSaveAsAdmin (1.0.211)
    NppToolBucket (1.10.6622.41336)
    Remove Duplicate Lines (1.3)
    ScrollPastEOFUni (1)
    SessionMgr (1.4.4)

**Comment by korpx** [comment]
Seen the same issue here for awhile

Notepad++ v8.4.6   (64-bit)
Build time : Sep 25 2022 - 19:51:39
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : (not relevant)
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 10 Enterprise (64-bit) 
OS Version : 22H2
OS Build : 19045.2251
Current ANSI codepage : 1252
Plugins : 
    mimeTools (2.8)
    NavigateTo (1.12.7)
    NppConverter (4.4)
    NppExport (0.4)

**Comment by TomArrow** [comment]
Same here, really obnoxious, makes moving tabs almost impossible. Version 8.4.7 (64 bit)

Win 10 Pro latest updaate

**Comment by ONaumov** [comment]
Same issue for version v8.5.6
