### ISSUE TITLE
I can't find a configuration file for tones to use as a reference.

### ISSUE THREAD

**Issue by Dhyfer1** [notepad-plus-plus/notepad-plus-plus#12643]
### Description of the Issue
I am using the latest portable version and every time a new version is released I have to re-configure the integrated tone and/or custom tones.

### Steps to Reproduce the Issue

1. Open Settings>Preferences>Dark mode
2. Select one of the 7 built-in tones or create a custom tone.
3. I have to re-select my favorite tone here or re-select colors for a custom tone.

![2022-12-14_18-40-08](https://user-images.githubusercontent.com/50301201/207742333-eec2f6fe-f382-4fcc-9315-18aeb95e7c81.png)

### Expected Behavior
I would like Notepad++ to save custom tones in a configuration file for use in a next version, so I don't have to start from scratch every time I create a custom tone. If this configuration file exists, what is it called and where is it located? and... Is there any way to customize the built-in tones?

### Actual Behavior
What I have already mentioned in "Steps to Reproduce the Issue"

**Comment by ozone10** [comment]
in `config.xml`

**Comment by Dhyfer1** [comment]
@ozone10 Thanks, I found the file you indicate but I'm a little confused. After activating dark mode the following line appears in the file:

```xml
<GUIConfig name="DarkMode" enable="yes" colorTone="0" customColorTop="2105376" customColorMenuHotTrack="4210752" customColorActive="4210752" customColorMain="2105376" customColorError="176" customColorText="14737632" customColorDarkText="12632256" customColorDisabledText="8421504" customColorLinkText="65535" customColorEdge="6579300" customColorHotEdge="10197915" customColorDisabledEdge="4737096" />
```
But these numerical values don't change every time I choose one of the 7 built-in tones, except for the one indicated by `colorTone`, is this normal? and if these numerical values indicate color codes, in what format are they? because they are not RGB or Hex values, I have no idea.

These numerical values only change when I create a custom tone.

**Comment by ozone10** [comment]
@Dhyfer1 
next time ask in https://community.notepad-plus-plus.org/

`colorTone` corresponds to tone you set via GUI (Black, Red, ...). `customColor*` are used only for custom tone.
Format is `256*256*r + 256*g + b`.

You can close this issue.

**Comment by Dhyfer1** [comment]
Ok, thanks for the link. Then I will move my question to the Notepad++ community. Thanks for your attention, I now close this issue. 👍
