### ISSUE TITLE
Notepad asks to save all when shutting down

### ISSUE THREAD

**Issue by SuezDavidOrd** [notepad-plus-plus/notepad-plus-plus#12640]
### Description of the Issue
When you have an unsaved tab (or several) when you have notepad + + open and shutdown the computer it now prevents shutdown and you have to cancel shutdown and then say no to save all and then close notepad + + before shutting down.
This is new behaviour as it hasn't done it previously.

### Steps to Reproduce the Issue

1. open notepad + + with an unsaved tab
2. shutdown windows
3. 

### Expected Behavior

it should just shutdown and preserve the content of the tabs

### Actual Behavior

shutdown is prevented and you have to cancel shutdown

**Comment by donho** [comment]
https://github.com/notepad-plus-plus/notepad-plus-plus/commit/6c9f4cdff37e8b15207c3044efd54a425529ec4c
