### ISSUE TITLE
R Language Default Foreground Colour Only Applies to Tabs and Punctuation

### ISSUE THREAD

**Issue by mekkim** [notepad-plus-plus/notepad-plus-plus#1264]
Steps to reproduce:
- Open an R script file in NPP
- Verify that R is selected as the language
- Open Settings -> Styles Configurator
- Select R under the Language column. Ensure that "DEFAULT" is selected in Style column
- Change the foreground colour

Expected behaviour:
All foreground colours not explicitly defined in other styles in the R styles list switch to the new default foreground colour

Observed behaviour:
You'll see that the foreground colour only applies to tabs and some other punctuation.  Most of the content remains the previous foreground colour setting.  Setting ALL the other foreground colours for all the R styles listed still does not set it correctly.

My guess is that there is a missing style that isn't captured by "DEFAULT" but also doesn't show up in the R "styles" list.

**Comment by dail8859** [comment]
You would seem to be correct. It appears the `SCE_R_IDENTIFIER` is not defined. You can work around this for now. 
* Open your `stylers.xml` file **not using Notepad++**
* Find the section that starts with `<LexerType name="r" desc="R" ext="">`
* In that section add:
```xml
<WordsStyle name="IDENTIFIER" styleID="9" fgColor="000000" bgColor="FFFFFF" fontName="" fontStyle="0" fontSize="" />
```
When you open the configurator again you will now have an IDENTIFIER style.

**Comment by mekkim** [comment]
Thanks for the quick response.  I followed your steps, and the IDENTIFIER value now shows up in styles.  combining DEFAULT & IDENTIFIER works better, but I still can't find a way to set the WHOLE background colour for R.  Am I missing something?

**Comment by dail8859** [comment]
As far as I know you'll have to do that to each style. You might be able to use the Global Override but that does it for *everything* not just R. Never tried it myself though.

**Comment by mekkim** [comment]
Global Override works, but kills the R syntax highlighting.  Changing all the background styles listed in R (including the newly added identifier) still doesn't seem to cover the whole background.  Could there be another style missing?

**Comment by dail8859** [comment]
I guess technically there is 1 other style but not sure what that covers. You can try adding

```xml
<WordsStyle name="INFIX EOL" styleID="11" fgColor="000000" bgColor="FFFFFF" fontName="" fontStyle="0" fontSize="" />
```

And see if that helps.

**Comment by mekkim** [comment]
INFIX EOL doesn't seem to do anything that I can see.  I'm ok with using global background override.  It's not a big deal to not be able to set a separately defined background for R so long as I can keep the syntax highlighting, which works fine now with IDENTIFIER added.

Thanks again!
