### ISSUE TITLE
Crashes and random chars when inserting new lines to the beginning of the file

### ISSUE THREAD

**Issue by Podbrushkin** [notepad-plus-plus/notepad-plus-plus#12654]
### Description of the Issue

Notepad++ crashes or corrupts text when you insert new lines to the beginning of the file, if language is PowerShell and file begins with word 'function'
### Steps to Reproduce the Issue

1. Open npp
2. File-> New
3. Language -> PowerShell
4. In first line type 'function'
5. Move cursor back to the beginning of the line
6. Press Enter multiple times.

### Expected Behavior
New lines inserted

### Actual Behavior
'function' word is scattered
invisible cr lf are shown (even though 'Show all characters' is off)
sometimes npp also exits

### Debug Information
Notepad++ v8.4.7   (64-bit)
Build time : Nov  1 2022 - 23:31:11
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 10 Pro (64-bit) 
OS Version : 21H2
OS Build : 19044.2364
Current ANSI codepage : 1251
Plugins : 
    mimeTools (2.9)
    NppConverter (4.5)
    NppExport (0.4)
    NPPJSONViewer (1.41)
    QuickText (0.2.4.1)

**Comment by Podbrushkin** [comment]
I've deleted QuickText plugin and issue is gone.

**Comment by alankilborn** [comment]
Can you close this issue?

**Comment by Podbrushkin** [comment]
It was a bug of QuickText (0.2.4.1) plugin.
