### ISSUE TITLE
Need notepad ++ for mac OS

### ISSUE THREAD

**Issue by VaraPrasad36** [notepad-plus-plus/notepad-plus-plus#12659]
### Please provide the notepad++ for mac OS

@notepad

**Comment by alankilborn** [comment]
See [HERE](https://github.com/notepad-plus-plus/notepad-plus-plus/wiki/FAQ#support-for-systems-other-than-the-ms-windows-family:~:text=%2C%20%238613-,Support%20for%20systems%20other%20than%20the%20MS%20Windows%20family,-Notepad%20%2B%2B%20is%20created).

Please close this issue.
