### ISSUE TITLE
PC shutdown behaviour changed

### ISSUE THREAD

**Issue by Wyrade** [notepad-plus-plus/notepad-plus-plus#12661]
### Description of the Issue
On PC shutdown if I have unsaved files it prevents shutdown.

### Steps to Reproduce the Issue
1. Open a new tab in np++, write something (or might trigger on unsaved changed existing files too, not sure)
2. Try to shut down PC without saving or closing the program

### Expected Behavior
Since a few updates ago np++ just closed, and if I press the X in the upper right corner it still does that. It's only when I try to shutdown my windows 11 PC that this issue occurs.
The changes were and are saved in the np++ temporary location anyway, so this forced saving dialog is just an annoyance.

### Actual Behavior
Shutdown is prevented until i cancel shutdown and either save or cancel saving and close the program.

### Additional Info
The only relevant setting I found is Settings -> Preferences -> MISC. -> "Enable Save All confirm dialog", but it is not a solution.
If it is enabled, it asks on shutdown whether to save and prevents shutdown. If it's disabled, it starts to asks for save locations, and prevents shutdown.
I'm using many unsaved temporary files as random temporary notes, and would appreciate if the shutdown behaviour would be just closing the app like I do with the upper right X, and not this different popup asking to save all. Or at least have the option for this, so I don't have to pay attention to close np++ manually before i press shutdown on my PC.
Thanks in advance!

### Debug Information

Notepad++ v8.4.7   (64-bit)
Build time : Nov  1 2022 - 23:31:11
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 11 (64-bit) 
OS Version : 21H2
OS Build : 22000.1335
Current ANSI codepage : 1250
Plugins : 
    mimeTools (2.9)
    NppConverter (4.5)
    NppExport (0.4)

**Comment by alankilborn** [comment]
See [HERE](https://community.notepad-plus-plus.org/topic/23864/save-on-exit-preventing-computer-reboot) for more information on this topic.
To [QUOTE](https://github.com/notepad-plus-plus/notepad-plus-plus/issues/12612#issuecomment-1344261666) the developers, "Already fixed, will be in 8.4.8."
Please close this issue.
