### ISSUE TITLE
Bug fixes in english.xml file

### ISSUE THREAD

**Issue by P0rsche-911** [notepad-plus-plus/notepad-plus-plus#12665]
Bug fixes in english.xml file

When updating spanish.xml and galician.xml, Notepad++ does not accept translations because there are separations instead of spaces in the new text added to the latest version.

I have also removed unneeded spaces and edited line 1607 (You can re-enable it via menu View &quot;Word Wrap&quot;.)

I hope I am not breaking any rules. I just want to help to improve the program.

Corrección de errores en el archivo english.xml

Al actualizar spanish.xml y galician.xml, Notepad++ no acepta las traducciones debido a que hay separaciones en lugar de espacios en el nuevo texto añadido a la última versión.

Además he eliminado espacios no necesarios y editado la línea 1607 (You can re-enable it via menu View &quot;Word Wrap&quot;.)

Espero no incumplir norma alguna. Solo pretendo ayudar a mejorar el programa.

[english 8.4.8.zip](https://github.com/notepad-plus-plus/notepad-plus-plus/files/10252923/english.8.4.8.zip)

**Comment by donho** [comment]
@P0rsche-911 
> Bug fixes in english.xml file

What's the bug exactly in english.xml ?

> When updating spanish.xml and galician.xml, Notepad++ does not accept translations because there are separations instead of spaces in the new text added to the latest version.

Could you provide more detail please?

**Comment by P0rsche-911** [comment]
Hi, sorry for taking so long to reply.

The update file to [version 8.4.8](https://github.com/notepad-plus-plus/notepad-plus-plus/issues/12649) has no spaces, there are separations between words and the program does not recognise the translations.
I have also deleted some spaces in some lines.
You can compare it with [version 8.4.6](https://github.com/notepad-plus-plus/notepad-plus-plus/blob/master/PowerEditor/installer/nativeLang/english.xml) to see the changes.

Hola, perdón por tardar en responder.

El archivo de actualización a la versión 8.4.8 no tiene espacios, tiene separaciones entre palabras y el programa no reconoce las traducciones.
Además he borrado algún espacio en alguna línea.
Se puede comparar con la versión 8.4.6 para ver los cambios.

**Comment by donho** [comment]
The english.xml is fine for every translator, so I don't think there's somethings to be fixed.
