### ISSUE TITLE
[Bug] Saving both via the File menu and Ctrl+S bring up the save as dialog.

### ISSUE THREAD

**Issue by LAPIII** [notepad-plus-plus/notepad-plus-plus#12677]
### Description of the Issue
Saving both via the File menu and Ctrl+S bring up the save as dialog.
EDIT: Saving works correctly now.

### Debug Information
Notepad++ v8.4.7   (64-bit)
Build time : Nov  1 2022 - 23:31:11
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 11 (64-bit) 
OS Version : 22H2
OS Build : 22621.963
Current ANSI codepage : 1252
Plugins : 
    mimeTools (2.9)
    NppConverter (4.5)
    NppExport (0.4)

**Comment by alankilborn** [comment]
>EDIT: Saving works correctly now.

??

If so, please close this issue.
