### ISSUE TITLE
Documentation says column mode selection sorts are stable sorts, but they are not

### ISSUE THREAD

**Issue by Coises** [notepad-plus-plus/notepad-plus-plus#12678]
The documentation at https://npp-user-manual.org/docs/editing/ says "If a Column Mode selection is active, the sort will re-order all the lines included in the selection, but the sort key (the text that decides the sort order) will be limited to what is inside the column selection. If the keys are identical on two lines, then the order of those two lines will not change (even if text outside of the selected key columns is different)."

It is not true that the order of lines with equal sort keys is preserved.

The reason for this is clear: PowerEditor/src/MISC/Common/Sorters.h uses std::sort for all sorts. The documented behavior requires std::stable_sort.

Ideally column sorts should be changed to use std::stable_sort, since this behavior would be very useful to effect multi-level sorts (sorting on one column first, then on another, etc.).

**Comment by alankilborn** [comment]
Hmm, I thought this was dealt with before, but I guess not.
Easy enough to confirm that this is a bug (of omission) -- or at least a bug against how the manual is written.
(I think it is a bug no matter how the manual is written.)

Tested and confirmed on 8.4.8 RC2.

**Comment by donho** [comment]
@Coises 
Normally bug issue needs to fill template.
Could you fill up at least : 
### Steps to Reproduce the Issue

1. 
2. 
3. 

### Expected Behavior


### Actual Behavior

**Comment by Coises** [comment]
### Steps to Reproduce the Issue

1. Create a new text file with 100 lines, like this:

100  100
101  100
102  100
103  100
104  100
105  100
106  100
107  100
108  100
109  100
110  101
111  101
112  101
113  101
114  101
115  101
116  101
117  101
118  101
119  101
120  102
121  102
122  102
123  102
124  102
125  102
126  102
127  102
128  102
129  102
130  103
131  103
132  103
133  103
134  103
135  103
136  103
137  103
138  103
139  103
140  104
141  104
142  104
143  104
144  104
145  104
146  104
147  104
148  104
149  104
150  105
151  105
152  105
153  105
154  105
155  105
156  105
157  105
158  105
159  105
160  106
161  106
162  106
163  106
164  106
165  106
166  106
167  106
168  106
169  106
170  107
171  107
172  107
173  107
174  107
175  107
176  107
177  107
178  107
179  107
180  108
181  108
182  108
183  108
184  108
185  108
186  108
187  108
188  108
189  108
190  109
191  109
192  109
193  109
194  109
195  109
196  109
197  109
198  109
199  109

2. Select the second column of numbers, then use Edit > Line Operations > Sort Lines Lexicographically Descending

### Expected Behavior

Should look like this:

190  109
191  109
192  109
193  109
194  109
195  109
196  109
197  109
198  109
199  109
180  108
181  108
182  108
183  108
184  108
185  108
186  108
187  108
188  108
189  108
170  107
171  107
172  107
173  107
174  107
175  107
176  107
177  107
178  107
179  107
160  106
161  106
162  106
163  106
164  106
165  106
166  106
167  106
168  106
169  106
150  105
151  105
152  105
153  105
154  105
155  105
156  105
157  105
158  105
159  105
140  104
141  104
142  104
143  104
144  104
145  104
146  104
147  104
148  104
149  104
130  103
131  103
132  103
133  103
134  103
135  103
136  103
137  103
138  103
139  103
120  102
121  102
122  102
123  102
124  102
125  102
126  102
127  102
128  102
129  102
110  101
111  101
112  101
113  101
114  101
115  101
116  101
117  101
118  101
119  101
100  100
101  100
102  100
103  100
104  100
105  100
106  100
107  100
108  100
109  100

### Actual Behavior

Looks like this:

190  109
191  109
198  109
197  109
196  109
195  109
194  109
193  109
192  109
199  109
180  108
181  108
182  108
183  108
184  108
185  108
186  108
188  108
189  108
187  108
170  107
179  107
178  107
177  107
176  107
175  107
174  107
173  107
172  107
171  107
160  106
161  106
163  106
164  106
165  106
166  106
167  106
168  106
162  106
169  106
150  105
151  105
152  105
153  105
154  105
155  105
156  105
157  105
158  105
159  105
140  104
149  104
148  104
147  104
146  104
145  104
144  104
143  104
142  104
141  104
138  103
139  103
137  103
136  103
135  103
134  103
130  103
131  103
132  103
133  103
125  102
123  102
122  102
121  102
120  102
124  102
129  102
128  102
127  102
126  102
112  101
119  101
118  101
117  101
116  101
115  101
114  101
113  101
111  101
110  101
101  100
102  100
103  100
104  100
105  100
100  100
109  100
108  100
107  100
106  100

Note that with a small number of lines, the error does not appear. The above produced the error using Notepad++ v 8.4.7 (32-bit). The results won't necessarily be the same each time the test is run, as std::sort is not guaranteed to be deterministic as to the order of elements with equal sort keys.
