### ISSUE TITLE
[Feature Request] Add a separator between two views in the Document List

### ISSUE THREAD

**Issue by Phroneris** [notepad-plus-plus/notepad-plus-plus#12689]
### Description of the Issue

I have 43 documents opening in Notepad++ now.
33 on the main (left) view and 10 on the sub (right).

Within the **Document List** a.k.a. Doc Switcher, I would like a **separator** (or something like that) between the main and sub file groups for visual organization.

<img width="250" height="450" title="click for full size" src="https://user-images.githubusercontent.com/9891867/209113145-d51716c2-e847-47fc-951f-a3b322e23c06.png">

### Steps to Reproduce the Issue

Because this isn't an issue, here is just an example situation.

1. Turn on [View] → [Document List]
2. Open many files on the main and sub view
3. Go to each file around the middle of the order on each view
4. In the Document List, try to go to the last file of the main view

... But sometimes the list order goes sub → main.
If that happens, try to find the last of sub instead.

### Expected Behavior

The separator indicates the boundary of two views so that you can easily find the desired file.

### Actual Behavior

You can't easily find the desired file unless you remember its name or your random clicks hit on it.

### Debug Information

- Notepad++ v8.4.7 (64-bit)
- Windows 10 (64-bit)

**Comment by TBugReporter** [comment]
On a semi-related note (which I'm sure some here will see as me being too picky - which is why I'm tacking this on to this FR instead of creating yet another new one), it would also be nice if the Window menu would list the windows in **both** panes instead of just the one that's currently active.

**Comment by alankilborn** [comment]
> On a semi-related note (which I'm sure some here will see as me being too picky - which is why I'm tacking this on to this FR instead of creating yet another new one), it would also be nice if the Window menu would list the windows in **both** panes instead of just the one that's currently active.

It's certainly NOT "too picky".
It is something I suggested when the "total documents: xx" was added to the title bar of the popup window when one chooses _Window_ > _Windows..._.  Or at least I think I suggested it -- I know I commented that if you have N documents open in the primary view and M docs open in the secondary view, then you have M+N total documents...
But it is off-topic to this current issue and deserves its own; I encourage you to create one (after searching to see if there is already one existing).

**Comment by TBugReporter** [comment]
Found:  [Show open documents from both views in Window menu and ▼ #11764](https://github.com/notepad-plus-plus/notepad-plus-plus/issues/11764).

Apparently, @Yaron10 worked on this [with the + ▼ ✕ stuff](https://github.com/notepad-plus-plus/notepad-plus-plus/pull/11757#issuecomment-1145896988), but it never made it in.  Whether it fell by the wayside, or wasn't ready for prime time, I can't tell.
