### ISSUE TITLE
Find in Files remembers wrong directory after closing and re-opening

### ISSUE THREAD

**Issue by ketchup201** [notepad-plus-plus/notepad-plus-plus#12692]
**Description:**
When using Find in Files, it appears that the directory field selection is off-by-one after performing a search, closing the dialog, and then re-opening it.

**Steps to Reproduce:**
1. Open the Find in Files dialog.
2. Take note of the Directory text in the dialog.
3. Enter some text into 'find what', and choose a directory different than the one already displayed.
4. Click on 'Find All'.
5. Close the dialog.
6. Re-open the Find in Files dialog.

**Expected Behavior:**
I expect that the Directory text entered most recently into the dialog will in the Directory text field by default when the dialog is subsequently opened.

**Actual Behavior:**
The Directory text in the dialog is not what you entered from step 3. It's actually the one from step 2. Also note that when expanding the Directory dropdown, the selected item is the second one in the list instead of the first, which happens to be the text entered in step 3.

**Debug Information:**
Notepad++ v7.9.1   (64-bit)
Build time : Nov  2 2020 - 01:07:46
Path : C:\Program Files\NotepadPlusPlus\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS Name : Windows 10 Enterprise (64-bit) 
OS Version : 2009
OS Build : 19044.2364
Current ANSI codepage : 1252
Plugins : JsMinNPP.dll mimeTools.dll NppConverter.dll NppExport.dll XMLTools.dll

**Comment by alankilborn** [comment]
Note:  When checked, this control (pictured) has a great deal of influence over what appears in the _Directory_ box when _Find in Files_ is invoked from keycombo or menu when the editor window has input focus.

![image](https://user-images.githubusercontent.com/77065706/209246624-4a815f40-5d61-4b92-8126-ca3728756618.png)

And although similarly named is a control here (next picture), this area also has influence over what appears in the _Find in Files_ _Directory_ box:

![image](https://user-images.githubusercontent.com/77065706/209246812-7dddbcc0-f83f-4161-9bb5-8fe43dd115b0.png)

So I think probably the best course of action is to add your settings for these areas into your issue description / steps to reproduce.

**Comment by ketchup201** [comment]
Thanks to @alankilborn  I was able to resolve my own issue. I had "Follow current doc." checked in the "Find in Files" dialog, which was causing my issue. With that checkbox unchecked, The dialog is now remembering my last used directory. Thanks Alan!!!
