### ISSUE TITLE
Fake Notepad++ website?!?

### ISSUE THREAD

**Issue by HttXx** [notepad-plus-plus/notepad-plus-plus#12690]
Hello i was downloading notepad++ and just google notepad++ in the google and clicked the first link it was this: https://notwgoq.shop/

downloaded and noticed that in fact was a fake website, because it did'nt install the notepad++..

this website is yours or not?

**Comment by alankilborn** [comment]
Not.

**Comment by HttXx** [comment]
> Not.

srry, its not yours or its not fake?

**Comment by dail8859** [comment]
@HttXx It is fake.
