### ISSUE TITLE
bookmark file or fav files

### ISSUE THREAD

**Issue by deemetrius** [notepad-plus-plus/notepad-plus-plus#12700]
This feature request is needed for quick access to list of some files. Maybe as main menu item.

Possible Sub menu items:
- Fav current file
- Edit fav list
- _List_ ...

Also please add to the context menu of document list this command.

**Comment by alankilborn** [comment]
Please redo your issue following the issue template.
Otherwise, close this issue.

**Comment by deemetrius** [comment]
> Please redo your issue following the issue template. Otherwise, close this issue.

Does that template fit my request?

**Comment by alankilborn** [comment]
Yes, in that you could detail some expected behavior in that section of the template.
And I do mean "provide detail".
As it is, your request reads like: "want fav".
You need to put some effort in.

The Explorer plugin has some fav support.
You could start there, describe what you like about that, what you don't like, etc.
And maybe it could be turned into a native Notepad++ feature.
But maybe you don't want to put that kind of effort in.

**Comment by deemetrius** [comment]
> Yes, in that you could detail some expected behavior in that section of the template. And I do mean "provide detail". As it is, your request reads like: "want fav". You need to put some effort in.
> 
> The Explorer plugin has some fav support. You could start there, describe what you like about that, what you don't like, etc. And maybe it could be turned into a native Notepad++ feature. But maybe you don't want to put that kind of effort in.

I don't know how to open file explorer. Can you please explain it to me?

**Comment by deemetrius** [comment]
> Yes, in that you could detail some expected behavior in that section of the template. And I do mean "provide detail". As it is, your request reads like: "want fav". You need to put some effort in.

I think I provide enough information.

> The Explorer plugin has some fav support. You could start there, describe what you like about that, what you don't like, etc. And maybe it could be turned into a native Notepad++ feature.

Yes I found it recently. Didn't know about that plugin.

> But maybe you don't want to put that kind of effort in.

It seems so.

**Comment by alankilborn** [comment]
Please close.

**Comment by deemetrius** [comment]
> Please close.

I not going to do it by self.

**Comment by donho** [comment]
Please fill the template for your request.
