### ISSUE TITLE
TYPO: Tab context menu modification instructions are incorrect

### ISSUE THREAD

**Issue by Gitoffthelawn** [notepad-plus-plus/notepad-plus-plus#12708]
### Description of the Issue
The tab context menu modification instructions are incorrect.

### Recommendation
See https://github.com/notepad-plus-plus/notepad-plus-plus/pull/12706 for recommended fix.

### Debug Information
Notepad++ v8.4.8

**Comment by ImSpecial** [comment]
Wouldn't wording it like this sound better/be more correct?

**Old:**
"you can customize your context menu popped up when right-clicking on the tab zone."

**NEW:**
"you can customize your context menu **pop-up** when right-clicking on the tab zone."
