### ISSUE TITLE
.js file no longer has the usual theme

### ISSUE THREAD

**Issue by nodeffect** [notepad-plus-plus/notepad-plus-plus#1271]
When opening .js file, usually the colors/template are the same as the <script> tag. However it is not the case anymore on this new version 6.8.8. 

You can try putting <script> </script> tag on a PHP file and you get the supposed colors/template/style or whatever you call it. Even when opening a .js file, it give the same styles on the previous version.

Thanks.

**Comment by vlakoff** [comment]
This is a feature. Since version 6.8.4, Notepad++ manages separately .js files and embedded JavaScript, so you can apply different styling to them.
