### ISSUE TITLE
Update spanish.xml to v8.4.8

### ISSUE THREAD

**Issue by P0rsche-911** [notepad-plus-plus/notepad-plus-plus#12725]
Some texts are cropped because the translation does not fit in the different windows of the programme.
Version adapted to english.xml v8.4.8

Algunos textos están recortados porque la traducción no cabe en las distintas ventanas del programa.
Versión adaptada a english.xml v8.4.8

[spanish.zip](https://github.com/notepad-plus-plus/notepad-plus-plus/files/10316762/spanish.zip)

**Comment by schnurlos** [comment]
Probably this new commit could fix that: https://github.com/notepad-plus-plus/notepad-plus-plus/commit/3d1aa408dd75cb1a9619cc9c4e10544bf8e44108 (I had the same problem with german.xml) ...
So check again with the next release.

**Comment by Fnombela** [comment]
The following lines of the Spanish.xml file do not appear translated into notepad ++ 8.4.8, is this a problem of mine or does it happen to everyone?            

<TabBar>
                <Item CMDID="41003" name="Cerrar"/>
                <Item CMDID="0" name="Cerrar múltiples pestañas"/>
                <Item CMDID="41005" name="Cerrar todo MENOS esto"/>
                <Item CMDID="41009" name="Cerrar todo a la izquierda"/>
                <Item CMDID="41018" name="Cerrar todo a la derecha"/>
                <Item CMDID="41024" name="Cerrar todo sin cambios"/>
                <Item CMDID="41006" name="Guardar"/>
                <Item CMDID="41008" name="Guardar como..."/>
                <Item CMDID="1" name="Abrir en"/>
                <Item CMDID="41019" name="Abrir carpeta contenedora en el explorador"/>
                <Item CMDID="41020" name="Abrir carpeta contenedora en CMD"/>
                <Item CMDID="41025" name="Abrir carpeta contenedora como espacio de trabajo"/>
                <Item CMDID="41023" name="Abrir en el visor predeterminado"/>
                <Item CMDID="41017" name="Renombrar..."/>
                <Item CMDID="41016" name="Mover a la Papelera de reciclaje"/>
                <Item CMDID="41014" name="Recargar"/>
                <Item CMDID="41010" name="Imprimir..."/>
                <Item CMDID="42028" name="Solo lectura"/>
                <Item CMDID="42033" name="Quitar marca de solo lectura"/>
                <Item CMDID="2" name="Copiar al portapapeles"/>
                <Item CMDID="42029" name="Copiar ruta completa del archivo"/>
                <Item CMDID="42030" name="Copiar nombre del archivo"/>
                <Item CMDID="42031" name="Copiar ruta actual"/>
                <Item CMDID="3" name="Mover documento"/>
                <Item CMDID="10001" name="Mover a otra vista"/>
                <Item CMDID="10002" name="Clonar en otra vista"/>
                <Item CMDID="10003" name="Mover a una nueva instancia"/>
                <Item CMDID="10004" name="Abrir en una nueva instancia"/>
                <Item CMDID="4" name="Aplicar color a pestana"/>
                <Item CMDID="44111" name="Aplicar color 1"/>
                <Item CMDID="44112" name="Aplicar color 2"/>
                <Item CMDID="44113" name="Aplicar color 3"/>
                <Item CMDID="44114" name="Aplicar color 4"/>
                <Item CMDID="44115" name="Aplicar color 5"/>
                <Item CMDID="44110" name="Quitar color"/>
            </TabBar>

**Comment by P0rsche-911** [comment]
Sorry for the mistake. Out of place

Perdón por el error. Fuera de lugar
