### ISSUE TITLE
New version doesn't have Document List Panel

### ISSUE THREAD

**Issue by attaporn** [notepad-plus-plus/notepad-plus-plus#12729]
### Description of the Issue
In the new version under  Settings menu > Preferences > General section NOT found Document list Panel.

**Comment by alankilborn** [comment]
![image](https://user-images.githubusercontent.com/77065706/209976137-9ed34ab5-f5ea-4084-82d3-f2cad82f5106.png)

![image](https://user-images.githubusercontent.com/77065706/209976196-a3744aca-df07-4767-9d19-26d2c904b91b.png)

Please close this issue.
