### ISSUE TITLE
PowerShell syntax highlighting for multiline string does not stop highlighting

### ISSUE THREAD

**Issue by BlueToast** [notepad-plus-plus/notepad-plus-plus#12724]
### Description of the Issue
Notepad++ does not stop highlighting everything in light gray text after a multi-line string syntax
`@"`
`multi-line`
`string text`
`here`
`"@`

### Steps to Reproduce the Issue
1. Create empty file.ps1
2. Paste the following into file.ps1:
`$otherVar = (Get-Content 'C:\Windows\Temp\test.log').FileName;`
`$myVar = @"`
`This is a`
`multiline string`
`value`
`"@;`
`If ($otherVar -eq 0) {`
`Write-Output ('This is a message for ' + (whoami));`
`};`

3. Observe syntax highlighting beginning at @" does not stop after "@ and continues to end of file

### Expected Behavior
Normal PowerShell syntax highlighting should continue after the "@

### Actual Behavior
Syntax highlighting that begins at @" continues to apply through to end of file even after the closing "@

### Debug Information
Notepad++ v8.4.7   (64-bit)
Build time : Nov  1 2022 - 23:31:11
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : "U:\Temp\whoami.ps1"
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : C:\Users\Developer1\OneDrive\Documents\NppBackups\Cloud
OS Name : Windows 10 Enterprise (64-bit) 
OS Version : 20H2
OS Build : 19042.2364
Current ANSI codepage : 1252
Plugins : 
    mimeTools (2.9)
    NppConverter (4.5)
    NppExport (0.4)

(**Note as of 29 Dec 2022** - the screenshots below depict errorneous usage of `@"texthere"@` presented as a single line when it should be multi-lined. With correction, a new red underline further revealed VSCode and PowerShell ISE have similar syntax highlighting issues when tabs and white space exist before `"@` despite any code validity, and syntax highlighting corrects in all three programs when all preceding whitespace is removed in the line of `"@`)

![image](https://user-images.githubusercontent.com/516539/209873929-4ef38ee2-ebd1-4d29-87c5-9904ee0cd20d.png)
![image](https://user-images.githubusercontent.com/516539/209873998-b4184040-b699-4900-8b2d-86f498deb5c3.png)
![image](https://user-images.githubusercontent.com/516539/209874005-dcaf0e91-0fda-43e7-9712-2d9119c350d9.png)

**Comment by ArkadiuszMichalski** [comment]
@BlueToast
You could report this problem to https://github.com/ScintillaOrg/lexilla project for `LexPowerShell.cxx` lexer.

**Comment by mpheath** [comment]
https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_quoting_rules?view=powershell-7.3#here-strings

Please read to understand the syntax.

`@";` obviously a typo as should be `"@;`.

The images are trying to tell you something. Look at the red underline of `Write-Output`. The `W` after `@"` should not be there.

``` powershell
$a = @"hello"@;
$a
```
```
At C:\test\test1.ps1:1 char:8
+ $a = @"hello"@;
+        ~
No characters are allowed after a here-string header but before the end of the line.
    + CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : UnexpectedCharactersAfterHereStringHeader
```

Error.  Notice colour of `@`.

``` powershell
$a = "hello";
$a
```

```
hello
```

OK

``` powershell
$a = @"
hello
"@;
$a
```

```
hello
```

OK. Notice colour of `@`.

**Comment by ArkadiuszMichalski** [comment]
Right, looks like a typo.

@BlueToast your example should not be like that?
```powershell
$otherVar = (Get-Content 'C:\Windows\Temp\test.log').FileName;
$myVar = @"
This is a
multiline string
value
"@;
If ($otherVar -eq 0) {
Write-Output ('This is a message for ' + (whoami));
};
```

**Comment by BlueToast** [comment]
Sorry about the typo, yes the @"; should be "@;

Also thanks for the correction regarding the illustrated examples: @"Write-Output 'test'"@; should be multi-lined as indicated by others.

However, even with corrections to my mistakes, Notepad++ is still not ceasing its gray highlight at "@

**Comment by ArkadiuszMichalski** [comment]
>I then checked across all three programs to see the before and after, as illustrated below, and learned that a syntax highlighting issues occurs in all three.

Without white space before `#@` all three programs works correct. After `#@` syntax highlighting still works.
