### ISSUE TITLE
Update galician.xml to v8.4.8

### ISSUE THREAD

**Issue by P0rsche-911** [notepad-plus-plus/notepad-plus-plus#12726]
Some texts are cropped because the translation does not fit in the different windows of the programme.
Version adapted to english.xml v8.4.8

Algunos textos están recortados porque la traducción no cabe en las distintas ventanas del programa.
Versión adaptada a english.xml v8.4.8

[galician.zip](https://github.com/notepad-plus-plus/notepad-plus-plus/files/10316778/galician.zip)

**Comment by schnurlos** [comment]
Probably this new commit could fix that: https://github.com/notepad-plus-plus/notepad-plus-plus/commit/3d1aa408dd75cb1a9619cc9c4e10544bf8e44108 (I had the same problem with german.xml) ...
So check again with the next release.

**Comment by P0rsche-911** [comment]
Sorry for the mistake. Out of place

Perdón por el error. Fuera de lugar
