### ISSUE TITLE
Add support selection to TAB and Space conversion commands

### ISSUE THREAD

**Issue by ArkadiuszMichalski** [notepad-plus-plus/notepad-plus-plus#12720]
Would be nice to have selection support for these three commands: `TAB to Space`, `Space to TAB (All)` and `Space to TAB (Leading)`. Same as we have for trim operations https://github.com/notepad-plus-plus/notepad-plus-plus/pull/12655 and maybe two others https://github.com/notepad-plus-plus/notepad-plus-plus/pull/12711.

![image](https://user-images.githubusercontent.com/2730894/209812019-f3b588a3-50af-4f5b-bddb-394123f0b8e6.png)

@donho Here also is question how treat selection:
- exactly as it is
- or expand to full lines

If expand then for all three or only for some, like `Space to TAB (Leading)`?

Maybe in this submenu `Blank Operations` all commands should be treat in entire lines context, so partially selected line should be expand to full lines. It would be more consistent. Is there any command here for which a partially selected line would be better (more expected)?

**Comment by ArkadiuszMichalski** [comment]
@donho 

Any advice on this? Only here the selection support is still missing. I would correct these commands too.

**Comment by Yaron10** [comment]
@ArkadiuszMichalski,

In `Tab to Space` and `Space to Tab (All)` even column-selection can be useful in real-life. :)

In the following case the user might want to replace the selected spaces only.
![תמונה](https://user-images.githubusercontent.com/10229320/210111894-76623b20-9ddf-4650-b3fc-20efd7ff4b4f.png)

**Comment by donho** [comment]
@ArkadiuszMichalski 
> Any advice on this? Only here the selection support is still missing. I would correct these commands too.

I would say that let's keep it as it is if there's no feature request.

**Comment by alankilborn** [comment]
>In the following case the user might want to replace the selected spaces only.

No user I've ever met would want to do that.  :-)

**Comment by donho** [comment]
I set suspended so far so if there's need we will unsuspended, ans see if we will do it.

**Comment by ArkadiuszMichalski** [comment]
@donho
I want this, especially `Space to TAB (Leading)`. Even Notepad++ codebase often has a tab/space mix ([where tabs are preferred ](https://github.com/notepad-plus-plus/notepad-plus-plus/blob/master/CONTRIBUTING.md#use-tabs-instead-of-white-spaces-we-usually-set-our-editors-to-4-white-spaces-for-1-tab-but-the-choice-is-up-to-you)). Thanks to the selection support it easier to clean up a certain piece of code that we are working on.

I think that expand partially selection to full lines (same as `Trim`) makes the most sense here. I remind that the number of spaces per one tab depends on the settings, so operating on partial spaces in a line seems less useful.

**Comment by Yaron10** [comment]
@alankilborn,

> No user I've ever met would want to do that.

I don't understand it.

If you have a 1000-lines file containing somewhere the following text:
![תמונה](https://user-images.githubusercontent.com/10229320/210118330-5179c2cc-064d-43b9-b3cb-b2bcf7c7eb39.png)


You might want want to replace the column-selected spaces only. Not in the entire file nor in those 4 lines.
Unlike Trim where we must either ignore column-selection or expand it to the entire lines.

**Comment by alankilborn** [comment]
>>No user I've ever met would want to do that.

>I don't understand it.

Well, you went and changed the example...

**Comment by Yaron10** [comment]
@alankilborn,

It was an "in-principle" example. :)

Happy New Year!
To you and all.

**Comment by donho** [comment]
@ArkadiuszMichalski 
Have you a list of commands you want to enhanced with the selection?

**Comment by donho** [comment]
> Happy New Year! To you and all.

Thank you @Yaron10 
I don't celebrate new year, since there's no one for me.
But I wish you happy holiday :)

**Comment by Yaron10** [comment]
@donho,

Thank you!
I wish you many happy years. Whenever they start and end. :)

**Comment by ArkadiuszMichalski** [comment]
@donho 
>Have you a list of commands you want to enhanced with the selection?

No, I'm focusing on `Lines Operations` and `Blank Operations` at the moment because selection for them seems to be the most useful.

These three commands: `TAB to Space`, `Space to TAB (All)` and `Space to TAB (Leading)` are covered by one function `wsTabConvert` so selection support just needs to be added in one place.

**Comment by annwitbrock** [comment]
It works fine on a new file, respecting the chosen setting. It does not work in an existing file. I have just tested this carefully.
I will report it on the changelog page.
![Notepadplusplus spacetab 2023-05-03 200052](https://user-images.githubusercontent.com/150476/236017357-89ad1bfe-b079-4297-b0be-f6ddbc6426ee.jpg)
