### ISSUE TITLE
Npp current master crash in debug mode

### ISSUE THREAD

**Issue by sanastasiou** [notepad-plus-plus/notepad-plus-plus#1273]
The crash occurs, when trying to access "Delimiter" option from the Preferences menu.

Win10 OS with latest updates.

Current master compiled under 2013 VS Ultimate Version Win32/Unicode configuration.

The crash is 100% reproducible.

![untitled](https://cloud.githubusercontent.com/assets/2955627/11913587/0b523a1c-a669-11e5-9ff8-67bb16918621.png)

**Comment by sanastasiou** [comment]
Thanks for the fix m8 :). Hope it get's merged.

**Comment by donho** [comment]
https://github.com/notepad-plus-plus/notepad-plus-plus/commit/19476bbbaed6a0421d2f234839d8dbe40e663b37
