### ISSUE TITLE
Hang with 100% CPU after changing tab settings

### ISSUE THREAD

**Issue by benrg** [notepad-plus-plus/notepad-plus-plus#1274]
To reproduce:
1. Extract npp.6.8.8.bin.7z into an empty directory.
2. Run notepad++.exe.
3. In the Language menu, set the language of the "new 1" document to JavaScript.
4. In the document, type a tab.
5. In Settings → Preferences → Tab Settings → javascript.js, uncheck "Use default value" and change the tab size to 8.
6. Close Notepad++ (Alt+F4).
7. Run it again.

Result: hang with one CPU core at 100%, with the window partially painted. If you kill and restart it, it hangs again. After deleting tabSettings="8" from langs.xml, it works again. This is always reproducible on my machine.

**Comment by ClaudiaFrank** [comment]
@donho 
Problem is within
`void ScintillaEditView::setTabSettings(Lang *lang)
{
    if (lang && lang->_tabSize != -1 && lang->_tabSize != 0)
    {
		//if (lang->_langID == L_JAVASCRIPT)
		//{
		//	//Lang *ljs = _pParameter->getLangFromID(L_JS);
		//	//execute(SCI_SETTABWIDTH, ljs->_tabSize);
		//	//execute(SCI_SETUSETABS, !ljs->_isTabReplacedBySpace);
		//	
		//	execute(SCI_SETTABWIDTH, lang->_tabSize); // ljs->_tabSize);
		//	execute(SCI_SETUSETABS, !lang->_isTabReplacedBySpace); //!ljs->_isTabReplacedBySpace);
		//	return;
		//}
        execute(SCI_SETTABWIDTH, lang->_tabSize);
        execute(SCI_SETUSETABS, !lang->_isTabReplacedBySpace);
    }
    else
    {
        const NppGUI & nppgui = _pParameter->getNppGUI();
        execute(SCI_SETTABWIDTH, nppgui._tabSize);
		execute(SCI_SETUSETABS, !nppgui._tabReplacedBySpace);
    }
}`

when commented, like provided, tabsettings can be used. No freeze anymore.

Actually, I don't know why there is a need to distinguish which javascript should be used
as there is only one available in language menu.
Did the test, setting tabs = 8, for java, javascript, json and jsp all of them worked.

**Comment by Nerketur** [comment]
I can confirm this is still an issue in latest notepad++.  It may be minor, but its something that took me forever to fix, and i started using different text editors because of it being such a huge issue.  I finally looked it up and found this was why.  If only I had known sooner :(

**Comment by ClaudiaFrank** [comment]
Suggest to close as it seems to be fixed using latest version 7.5.2
