### ISSUE TITLE
Let GCC behaves similar to MSC for implicit conversions that may alter a value

### ISSUE THREAD

**Issue by ArkadiuszMichalski** [notepad-plus-plus/notepad-plus-plus#12740]
Now MSC for implicit conversions that may alter a value throws an error (aborts compilation) for both: Release and Debug.
https://ci.appveyor.com/project/donho/notepad-plus-plus/builds/45808112

Unfortunately, GCC does not respect this (doesn't even warn about it). It looks like at least [`-Wconversion`](https://gcc.gnu.org/onlinedocs/gcc/Warning-Options.html#index-Wconversion) should be add to:
https://github.com/notepad-plus-plus/notepad-plus-plus/blob/307fd2fcd2d4dd7a626092e6e1dc1a0467b596f5/PowerEditor/gcc/makefile#L40
so would be easier to catch such problem before we push on GitHub. It's a waste of time when MSC won't compile with these warnings anyway.

By using [`-Werror=`](https://gcc.gnu.org/onlinedocs/gcc/Warning-Options.html#index-Werror_003d) we can even turn such warning into an error so GCC will break compilation too.

**Comment by donho** [comment]
@ArkadiuszMichalski 
If I understand well, you'ree using only GCC as your compiler?

**Comment by ArkadiuszMichalski** [comment]
@donho 
Yes, and sometimes it happens to me that GCC doesn't give me any warning when MSC throws an error. I send a PR, block the queue and waste time unnecessarily. So from now on, I'll be adding these warnings flags to GCC, where in MSC we get errors.

I won't treat these warnings as errors in GCC because we can't get identical behavior in both compilers, and I don't want that GCC will block MSC compilation. Warnings in this case are enough and if they are sometimes more restrictive, they will not affect the compilation of MSC.
