### ISSUE TITLE
[Security]  Fake website?

### ISSUE THREAD

**Issue by NeodymiumFerBore** [notepad-plus-plus/notepad-plus-plus#12748]
Suspicious link promoted by Google when searching for "download notepad++". Looking like a scam. More info and screenshots below.

### Description of the Issue

On a freshly installed Windows 10 and Chrome browser, by looking for "download notepad++" on Google Search (without quotes), the first link is an ad, pointing to a website `www.noetepad.com`, with a certificate for `*.noetepad.com`.

It looks highly suspicious for the following reasons:

- Claims that the latest version of Notepad++ is 8.4.7. Latest is 8.4.8 as I am writing this (and the `notepad-plus-plus.org` website is up to date).
- All links point to the same page (download page).
- GPG links point to 403 error pages
- All links make you download the same zip file. See details in "Debug Information" section

VirusTotal did not find anything in the zip file though (uploaded it zipped).

For some reason, I don't have this ad with Firefox (still searching on Google Search), nor on Chrome in private mode, nor on my main computer. The ad appears inconsistently.

### Steps to Reproduce the Issue

Go to `https[:]//www[.]noetepad[.]com` with Google Chrome or Mozilla Firefox.

On my main computer, looking for "download notepad++" does not return this ad, private navigation or not. I don't know why.
On a fresh install of Windows 10, with an up to date Chrome and latest Windows 10 (`10.0.19045 N/A Build 19045`), the ad appears, with a random description, only if not in private mode. Chrome not signed in/synced. See screenshots below.

![image](https://user-images.githubusercontent.com/32781483/210254687-79f57583-41f7-450f-894f-24afcc393aae.png)

![image](https://user-images.githubusercontent.com/32781483/210254762-21f71bc4-2226-42bf-aa95-6908e246f879.png)

### Expected Behavior

No weird website when looking to download notepad++

### Actual Behavior

Weird website promoted by Google (inconsistently) when looking to download notepad++

### Debug Information

EDIT: opened the zip file. Here is some information. Let me know if you need more.

![image](https://user-images.githubusercontent.com/32781483/210259323-7b69eeae-90da-4f6f-b53a-c0cad4be52cd.png)

Also, the file is 750 MB. It exceeds the maximum file size allowed by VirusTotal. What a coincidence.

**Comment by NeodymiumFerBore** [comment]
Update: I don't see the ad on any computer, any browser now. Sorry for the inconsistency. The website I'm talking about is still up though.

**Comment by donho** [comment]
Just tried. It still happens to me:

![image](https://user-images.githubusercontent.com/90293/210258829-9ee5f6ee-5a61-4175-8cb5-91ba420bdafb.png)

**Comment by NeodymiumFerBore** [comment]
Update: edited my issue, added information about the zip content in "Debug Information" section.

**Comment by NeodymiumFerBore** [comment]
Extracted PE32 from the suspect .exe (750MB -> 328KB) (`dd if=fake-notepad.exe of=suspect.exe size=1 count=332832`). It was padded with random words in capital letters. Having reduced the total size of the file, it appears as corrupted on VirusTotal. I didn't take the time to fix PE headers (so long I haven't done such thing, I can't even remember how it works).

If you want to take a look (behavioral analysis is not over yet and it's getting late over here):

[VirusTotal: e70453595755a4b907fd7b8df33ce6180e5637921cccc451f63146b37975e303](https://www.virustotal.com/gui/file/e70453595755a4b907fd7b8df33ce6180e5637921cccc451f63146b37975e303)

On my side:

```sh
# sha256sum
3d53384a8fe46b98abdb9aecc08f7f71f6f79787c630ed8b94e8b2ff2273fba7  Nottepaad_lastNeWx32x64.zip
f94b23aecc74c117143d4ad6dccb1cf5975d3609b02ecb3169c122e1fc86b658  Noteppad_SettupX32iX64.exe
e70453595755a4b907fd7b8df33ce6180e5637921cccc451f63146b37975e303  suspect.exe

# du -sh
67M   Nottepaad_lastNeWx32x64.zip
758M  Noteppad_SettupX32iX64.exe
328K  suspect.exe
```

I don't know if it can help...

**Comment by donho** [comment]
@NeodymiumFerBore 
Thank you for taking time for the investigation.
It's rather Google's problem/issue to let such fake site to take over their search result. And it's not the first time.
The binaries from the fake site is certainly malware - I will see what I can do for this issue.

**Comment by donho** [comment]
Could anyone here reproduce Notepad++ fake problem on Google by searching **Download Notepad++**?

**Comment by NeodymiumFerBore** [comment]
Hello. No more weird add on my side, from any browser, but tests from other people may be required to validate it's gone.

However, something is sure: `www.noetepad.com` has ben taken down (not resolved anymore).

**Comment by kkm000** [comment]
Guys, when you see this kind of dangerous misleading ad or a search result, **do report it immediately!** Google takes these reports seriously. Instructions are for a desktop resolution; smaller screens may have same buttons laid out differently.
 1. If it's marked with an "Ad" icon: click on the kebab. The _Report Ad_ button is at the top left of the _My Ad Center_ popup. One report of such a grotty hacking activity is one of the most egregious violation of the AdSense TOS, leading to the loss of an AdSense account for life.
 2. If it's a regular, non-ad search result: click on the kebab. In the _About this result_ popup, press the button _Remove this result_ near its bottom. Next menu asks for the reason; select _Illegal information._ This takes you to the “Create report” page. Workflow is a bit more complex, but still worth 5 minutes of your time for the benefit of the rest of us.

Of course, info should be reasonably suspected illegal. Posting software that a regular person would reasonably believe was a decoy intended to break into a computer system certainly qualifies, and, in the US, my country, is regarded by 18 USC § 1030 (b), intent to illegally access a computer, equally serious as an actual break-in, covered in (a), and recommends the same punishment, outlined in (c), which includes up to 10 years imprisonment, which solidly puts it into the federal felony territory. Not a stuff to pass by and pretend to not notice lightheartedly. Please be a good citizen and report either of the above, an ad or not! Actual prosecution is unlikely (the actor is most likely not even in the US), but Google will remove it expeditiously.

No forensics, like that which has been excellently done by @NeodymiumFerBore, is necessary or even needed. Only a screenshot is strictly required for a take-down. Pasting the result of right-click/_Copy URL_ won't hurt, too, as it contains an encrypted provenance token; the only caveat is, it also includes your exact search phrase under the `q=` param in clear text, so you'll see it, they will too, thus adding the URL is your privacy call. `q=download+npp` is not what **I** would consider a privacy exposure, but I felt obliged to remind about it, however innocuous it in fact may be.

**Comment by Andre601** [comment]
This isn't really related to the issues topic, but I don't think opening another issue for it is actually good either, so I post it here as it is imo close enough to the topic...

Anyways, I would like to ask if Notepad++ has any form of social media they are using.
The reason why I ask is, that there seems to be a twitter account called `notepad_plus` which seems to look like being from you guys... Tho given the bio an tweets, it seems to be more an impersonator and/or troll trying to poke fun at you where possible with (sometimes negative) tweets?

Either way, I would like to have some clarification on this matter as your website doesn't share/link any social medias and while the account could be fake, is it not that clear and people could misunderstand it as real which in the end harms your reputation (This actually happened with one person who actually shared a tweet and thinks it's really from you... Is it?)

Appreciate a quick reply to this.

**Comment by rdipardo** [comment]
@Andre601,
> there seems to be a twitter account called `notepad_plus`

That's the Twitter handle associated with [the GitHub organization](https://github.com/notepad-plus-plus), so probably genuine.

<img alt="org" src="https://user-images.githubusercontent.com/59004801/217705879-e1d55a3c-808b-48a8-b203-b4c2b462a7fc.png">

**Comment by AnandFifteen** [comment]
This issue is not reproducible any more, testing on 13/July/2023.

Observations:
- search string used with google "download notepad++"
  among the results there was no link pointing to, noetepad.com. Posting screenshot of search result below: 

![image](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/85217748/28b677ef-d3f7-4f48-98f1-1c5f486829d6)


- when search string used with google was this - "noetepad.com"
   among the results there was no website by this name, noetepad.com.

**Comment by AnandFifteen** [comment]
Yes you are correct. This is my first open source project. Hence asking this question, After testing and finding that the defect is not reproducible any more, don't we close such issues. So that others do not spend time when they such issues and the issues count can also come down. Please correct me if I am missing something.
