### ISSUE TITLE
Notepad++ does not actually save the full session when i manually do it

### ISSUE THREAD

**Issue by Question2** [notepad-plus-plus/notepad-plus-plus#12742]
I am attempting to save my Notepad++ session to transfer it to my new computer, and am using the file->save session command. However, it never saves the entire session to the file...so when i load the session, it only restores a small portion of all the tabs and data i had. I have tried to do this multiple times, and each time the session file generated via the "save session" command does not contain a FULL copy of my session data.

It should clearly be containing a full copy of the session data but is not doing that...

### Debug Information
Notepad++ v8.4.8   (64-bit)
Build time : Dec 24 2022 - 19:40:27
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : "C:\Users\quest\Documents\test session"
Admin mode : ON
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 10 Home (64-bit) 
OS Version : 22H2
OS Build : 19045.2364
Current ANSI codepage : 932
Plugins : 
    mimeTools (2.9)
    NppConverter (4.5)
    NppExport (0.4)
    NPPJSONViewer (1.40)
    NppToolBucket (1.10.6622.41516)

**Comment by Question2** [comment]
Hmm i wonder if this is due to the differing user account names. On the laptop where i am saving the session, the session contains a lot of files opened to C:\Users\quest\Documents while the account on this PC is called c:\users\USER instead...

**Comment by alankilborn** [comment]
I think you solved your own problem.
Please close this issue.

**Comment by Question2** [comment]
Please add an error message when attempting to load a session which has missing file paths.
