### ISSUE TITLE
Files created from the command line don't get correct language settings

### ISSUE THREAD

**Issue by benrg** [notepad-plus-plus/notepad-plus-plus#1275]
To reproduce:

1. Extract npp.6.8.8.bin.7z into an empty directory.
2. Run notepad++.exe with "foo.cpp" (or any nonexistent file with a recognized language extension) as a command-line argument.
3. When asked if you want to create it, say yes.
4. Type some C++ (or appropriate language) code.

Result: The code is not syntax highlighted.

This worked in 6.6.8 (i.e., the new file was treated as C++) and stopped working in 6.6.9, so I suspect it is related to the feature "Apply new file default settings on created new file (opened via command line)."

**Comment by dail8859** [comment]
Related to #2016. Closed by f3abc30c7af6e5b67e7670df98a9fd82e026d946
