### ISSUE TITLE
Under certain circumstances function list parsers produce duplicate or unwanted entries in function list panel

### ISSUE THREAD

**Issue by dinkumoil** [notepad-plus-plus/notepad-plus-plus#12759]
### Description of the Issue
The C++ code that processes function list parser files and fills the tree in function list panel produces under certain circumstances unwanted  or duplicate entries in that tree.

It seems that this C++ code creates a data model of a source code file by inspecting it with the help of the content of a function list parser's file. The process of creating that data model and/or filling the tree in function list panel (based on that data model) seems to be faulty and leads under certain circumstances to wrong results.

In the following I give 3 examples of wrong results I found so far.

### Prerequisites
1. Download a fresh portable copy of _Notepad++_ from official web site.
2. Save the following _Pascal_ source code as  `FnListTest1.pas`:

```Pascal
unit FnListTest1;


interface

uses
  System.SysUtils, System.Types, System.Classes;


// function FreeFunc1(const Param: integer): integer;



implementation

{
function FreeFunc1(const Param: integer): integer;
begin
  Result := 0;
end;
}

end.
```

3. Save the following _Pascal_ source code as `FnListTest2.pas`:

```Pascal
unit FnListTest2;


interface

uses
  System.SysUtils, System.Types, System.Classes;


function  FreeFunc1(const Param: integer): integer;
procedure FreeProc1(AParam: integer);



implementation

function FreeFunc1(const Param: integer): integer;
begin
  Result := 0;
end;


procedure FreeProc1(AParam: integer);
begin
end;


end.
```

---

### Steps to Reproduce (Issue 1)
1. Navigate to directory `<Npp-folder>\functionList` and load file `pascal.xml` into downloaded _Notepad++_.
2. Download the following file [>> pascal.txt <<](https://github.com/notepad-plus-plus/notepad-plus-plus/files/10355466/pascal.txt), copy&paste its content into `pascal.xml` and save it. **Please note:** This is the _Pascal/Delphi_ function list parser of the next version of _Notepad++_. You can test the regex contained in `parser` XML node's attribute `commentExpr` with normal _Search & Replace_ dialog of _Notepad++_ on the `FnListTest1.pas` file from the _**Prerequisites**_ section to verify that it matches _Pascal_ block comments.
3. Restart _Notepad++_ and load the `FnListTest1.pas` file from the _**Prerequisites**_ section.
4. Watch the tree in function list panel, it will contain **one** node.

### Expected Behavior (Issue 1)
In step 4, the tree in function list panel should contain **no** nodes as the only existing function is part of a block comment.

### Actual Behavior (Issue 1)
In step 4, the tree in function list panel contains one node `FreeFunc1` though it is commented out. This is unwanted behaviour. It happens though function `FreeFunc1` is part of a block comment.

---

### Steps to Reproduce (Issue 2)
1. Navigate to directory `<Npp-folder>\functionList` and load file `pascal.xml` into _Notepad++_.
2. Download the following file [>> pascal.txt <<](https://github.com/notepad-plus-plus/notepad-plus-plus/files/10352197/pascal.txt), copy&paste its content into `pascal.xml` and save it. **Please note:** This is a function list parser that contains a mixed parser. However, the class parser part is stripped down to nearly empty regular expressions that do absolutely nothing. The function parser part is reduced to the absolute necessary minimum. In order to prevent matching procedure/function declarations in the interface section of _Pascal_ files, in XML node `parser` the `commentExpr` attribute contains the regex `(?is:^\h*INTERFACE\h*$.*?^\h*IMPLEMENTATION\h*$)`. This declares everything between the keywords `interface` and `implementation` as a comment, thus this section should not be parsed.
3. Restart _Notepad++_ and load the `FnListTest2.pas` file from the _**Prerequisites**_ section.
4. Watch the tree in function list panel, it will contain **four** nodes.
5. Navigate to directory `<Npp-folder>\functionList`, load file `pascal.xml` into _Notepad++_ and delete the whole `classRange` XML node.
6. Save file `pascal.xml`, restart _Notepad++_ and load the `FnListTest2.pas` file from the _**Prerequisites**_ section.
7. Watch the tree in function list panel, now it will contain only **two** nodes.

### Expected Behavior (Issue 2)
In step 4, the tree in function list panel should contain two nodes, `FreeFunc1` and `FreeProc1`, the same like in step 7.

### Actual Behavior (Issue 2)
In step 4, the tree in function list panel contains four nodes, two times `FreeFunc1` and two times `FreeProc1`. Clicking on these tree items shows that two of them refer to the declarations of the procedures/functions in the `interface` section of the _Pascal_ file. This is unwanted behaviour. Solely because the parser file contains a dummy class parser the tree in function list panel is filled with wrong data.

---

### Steps to Reproduce (Issue 3)
1. Navigate to directory `<Npp-folder>\functionList` and load file `pascal.xml` into _Notepad++_.
2. Download the following file [>> pascal.txt <<](https://github.com/notepad-plus-plus/notepad-plus-plus/files/10352426/pascal.txt), copy&paste its content into `pascal.xml` and save it. **Please note:** This is a function list parser that contains only a function parser that is reduced to the absolute necessary minimum. In order to prevent matching procedure/function declarations in the interface section of _Pascal_ files, in XML node `function` the `mainExpr` attribute contains the regex `(?!(?s:.*?^\h*IMPLEMENTATION\h*$))`. This negative lookahead filters out patterns of procedures/functions that are followed by the `implementation` keyword at a line's beginning somewhere after them.
3. Restart _Notepad++_ and load the `FnListTest2.pas`  file from the _**Prerequisites**_ section.
4. Watch the tree in function list panel, it will contain **two** nodes.
5. Set the caret to one of lines 12, 13 or 14 in the loaded _Pascal_ file (the empty lines between the declarations of the procedures/functions and the `implementation` keyword) and add some type of comment. It can be a line comment (`// xxx`) or a block comment (`{ xxx }` or `(* xxx *)`).
6. In function list panel, click the `Update` toolbar button in order to make the function list to apply your edits from step 5.
7. Watch the tree in function list panel, now it will contain **four** nodes.

### Expected Behavior (Issue 3)
In step 7, the tree in function list panel should contain two nodes, `FreeFunc1` and `FreeProc1`, the same like in step 4.

### Actual Behavior (Issue 3)
In step 7, the tree in function list panel contains four nodes, two times `FreeFunc1` and two times `FreeProc1`. Clicking on these tree items shows that two of them refer to the declarations of the procedures/functions in the `interface` section of the _Pascal_ file. This is unwanted behaviour. Solely because of adding a comment in step 5. the tree in function list panel is filled with wrong data.

---

### Applies To
_Notepad++_ v8.4.8, 32 bit and 64 bit version

**Comment by mpheath** [comment]
My observation of a `FnListTest1.pas` operation.

<details>

<summary>Observation</summary>

`getCommentZones()` gets the pairs for the comments. Pairs are the positions of start and end from the searches.

```
172, 257
```
This pair matches the comment block.

`classParse()` gets nothing as no classes exist. `commentZones` is passed to `funcParse()` which can call `isInZones()` to validate if inside or outside of `commentZone` pairs.

`getInvertZones()` gets the inverted pairs

```
0, 267
```

which is the whole document. Note that `classParse()` got nothing so `scannedZones` is empty, so the first condition within `getInvertZones()` returned `0, 267`. 

Next, `commentZones` is NOT passed to `funcParse()` so all functions are found and are considered valid anywhere in the document.

Quote mentioned at the [forum](https://community.notepad-plus-plus.org/post/82869)

> When I remove the class parser part of my mixed parser (i.e. the whole classRange XML node) I’m able to define everything between the interface and implementation keywords as a comment.

My reply: Comment the `classRange` XML node calls `FunctionUnitParser::parse` else calls `FunctionMixParser::parse`. The later does much more work due to searching for classes using `scannedZones` and `nonScannedZones` pairs.

To avoid function detection in comment zones, try passing `commentZones` to

https://github.com/notepad-plus-plus/notepad-plus-plus/blob/b3934afd9210f7f580355c7eb54f263d425ebd43/PowerEditor/src/WinControls/FunctionList/functionParser.cpp#L738

which gives better results though causes more work. Not sure about another possible fix.

`FnListTest2.pas` also is improved. 

Does not affect current unit tests as no commented functions exist in the test files.

</details>

<details>

<summary>Debug Information</summary>

Done with some `std::cout` lines to mostly check function calls, zone pairs...

Default:

```
## FunctionMixParser::parse
## FunctionParser::getCommentZones
CommentZone: 172, 257
## FunctionZoneParser::classParse
## FunctionParser::getInvertZones
InvertZone1: 0, 267
nonScannedZone: 0, 267
## FunctionParser::funcParse
funcParse: 175, 225
## FunctionParser::parseSubLevel
## FunctionParser::parseSubLevel
parseSubLevel: 184, 193
```

unitTest:

```json
{"leaves":["FreeFunc1"],"root":"unitTest"}
```

<hr>

Modified to pass `commentZones`:

```
## FunctionMixParser::parse
## FunctionParser::getCommentZones
CommentZone: 172, 257
## FunctionZoneParser::classParse
## FunctionParser::getInvertZones
InvertZone1: 0, 267
nonScannedZone: 0, 267
## FunctionParser::funcParse
funcParse: 175, 225
## FunctionParser::parseSubLevel
## FunctionParser::parseSubLevel
parseSubLevel: 184, 193
## FunctionParser::isInZones
isInZone: 184 >= 172 && 184 < 257
isInZone: true
```

unitTest:

```json
{"root":"unitTest"}
```

<hr>

</details>
