### ISSUE TITLE
Notepad++ doesn't have the Solidity Language

### ISSUE THREAD

**Issue by dhoward8816** [notepad-plus-plus/notepad-plus-plus#12755]
### Description of the Issue
The Language Menu in Notepad++ does not have the Solidity language and there is no UDL for it.

### Steps to Reproduce the Issue

1. Not Applicable
2. 
3. 

### Expected Behavior
Solidity language available

### Actual Behavior
Nothing

**Comment by postmeback** [comment]
May i know, why this issue was closed ?

Still today, I don't see support for solidity.
![No-Solidity-Support](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/14862687/622365b1-895e-475d-ab2f-4a700efba120)
