### ISSUE TITLE
Request: Simple "Close All" context menu item

### ISSUE THREAD

**Issue by ericrrichards** [notepad-plus-plus/notepad-plus-plus#12756]
### Description of the Issue

One of the things that I use Notepad++ for most frequently is digging through log files.  I'll usually have 5-10 files open related to a particular issue, and when I'm done with them, I want to zero the editor out and go to the next batch of logs I need to look at.

The "Close Multiple Tabs" submenu is more complicated than I'd like, when I want to close everything 95% of the time.  Maybe I'm ignorant and there's a keystroke command or a way I can customize things that I need to learn instead.

### Expected Behavior

![image](https://user-images.githubusercontent.com/2787661/210572049-dfbba2d6-73f1-4d2f-a21c-d4f868986ae8.png)

### Actual Behavior

![image](https://user-images.githubusercontent.com/2787661/210570417-237d2ba3-aac5-45fd-b572-cb7c5da33263.png)

**Comment by alankilborn** [comment]
By default _Close All_ is mapped to Ctrl+Shift+w.  If you don't like that combo, you can set it to something you like.

If you really want it in the tab right-click context menu, in 8.4.8 and later you can add it in there.

Please close this issue.

**Comment by ericrrichards** [comment]
Thank you very much for the info, will do that
