### ISSUE TITLE
Issue when switching form dark mode back to light mode

### ISSUE THREAD

**Issue by triniumbarryassadi** [notepad-plus-plus/notepad-plus-plus#12764]
### Description of the Issue

I have the latest version (Notepad++ v8.4.8) installed and now have dark mode.
### Steps to Reproduce the Issue

1. Start in light mode with a file open.
2. Switch to dark mode.
3. Switch back to light mode.
4. A black vertical bar now appears on the left of the text; to the right of the row counter ruler.

### Expected Behavior

That bar should not be there.
<img width="716" alt="notepad-plus-plus-issue-when-going-from-dark-mode-to-light-mode" src="https://user-images.githubusercontent.com/89485990/210879869-fc2d372b-dff8-488f-83a4-23edcab76252.png">

**Comment by donho** [comment]
@triniumbarryassadi 
Please provide **Debug Information**

**Comment by triniumbarryassadi** [comment]
Notepad++ v8.4.8   (64-bit)
Build time : Dec 24 2022 - 19:40:27
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 10 Pro (64-bit) 
OS Version : 21H2
OS Build : 19044.2364
Current ANSI codepage : 1252
Plugins : 
    mimeTools (2.9)
    NppConverter (4.5)
    NppExport (0.4)
    XMLTools (3.1.1.13)

**Comment by mikavaliviita** [comment]
> 4\. A black vertical bar now appears on the left of the text; to the right of the row counter ruler.

I can also confirm this behaviour with 8.4.8
