### ISSUE TITLE
Typo in style configurator

### ISSUE THREAD

**Issue by vlakoff** [notepad-plus-plus/notepad-plus-plus#1277]
In [stylers.model.xml](https://github.com/notepad-plus-plus/notepad-plus-plus/blob/7b2b640357070ab97b879d5947f7f9be5132da24/PowerEditor/src/stylers.model.xml#L393), "embbeded" should instead be "embedded".
On a related note, the proper capitalization is "JavaScript" ;-) (lines 393, 406, and other themes)

(also occurrences of "embbeded" [here](https://github.com/notepad-plus-plus/notepad-plus-plus/blob/4fee79907b9b680173844012f0a06274ad883397/PowerEditor/src/langs.model.xml#L113) and [there](https://github.com/notepad-plus-plus/notepad-plus-plus/blob/715a64a32a462f7264fc989a66c480c15bba346d/PowerEditor/src/ScitillaComponent/ScintillaEditView.cpp#L974))

**Comment by donho** [comment]
https://github.com/notepad-plus-plus/notepad-plus-plus/commit/e584c474296ae6403ed71b3ede263347d42eea04
