### ISSUE TITLE
Failing to delete bookmarked lines in large TXT files

### ISSUE THREAD

**Issue by afg-thierry-duval** [notepad-plus-plus/notepad-plus-plus#12788]
Hi Team

i am having a large file with 7 203 278 lines
i use the mark to mark all line I want to remove --> about 3022033 lines containing a word
marks works fine and it marked 

![2023-01-11 09 39 20](https://user-images.githubusercontent.com/68956675/211758484-a564b984-bafe-4977-a870-82310134eefc.png)

then i used remove bookmarked lines and notepad failed removing the lines ?????
notepad++ processed the command but stopped after a certain time
![image](https://user-images.githubusercontent.com/68956675/211759946-6927e132-01dd-4650-8838-860aa45f5e6b.png)

we can see that it deleted some lines but stopped in the middle of its process and removed the bookmark??

does anyone have a clue?

the file containing some confidential data i cannot share :(

_Originally posted by @afg-thierry-duval in https://github.com/notepad-plus-plus/notepad-plus-plus/issues/8279#issuecomment-1378416330_

**Comment by alankilborn** [comment]
Duplicate of #8279.
Please close this issue.

**Comment by afg-thierry-duval** [comment]
hi alankilborn

but #8279 is closed ? then I will see no answer ?

**Comment by alankilborn** [comment]
Your comments on the closed 8279 will be seen, and developers will reopen.

**Comment by afg-thierry-duval** [comment]
thank you ;)
