### ISSUE TITLE
[Feature request/ Enhancement]: Add Exclusion list for 'Find in Files' function

### ISSUE THREAD

**Issue by caccorsi** [notepad-plus-plus/notepad-plus-plus#12789]
Hello, 
In addition to all the wonderful uses of Notepad++, the Find in Files function is an invaluable resource when working with large code bases. Especially when there's a lot of reflection and IDE searches do not find what I'm looking for. 

One enhancement that would make it even more powerful is having the ability to exclude folders / patterns. When I search one of our large code bases (without limiting the file extension) it takes 5-7 seconds which is perfectly reasonable. However if there's a node_modules folder present, which there often is, it can take upwards of a minute because of the incalculable number of files under that folder. I would suspect others have experienced this as well. The UI implementation doesn't need to be sophisticated, just accept a delimited list of paths.. in a perfect world it would also accept some rudimentary expressions, for example */bin  (all bin folders)

Then when the searches are performed, the paths matching the exclusions would be skipped, yielding a faster search. 

Below is how I'm envisioning it but I think you get the idea.. Thanks!!
![npp_design_suggestion](https://user-images.githubusercontent.com/18270533/211822648-def56d87-4e1a-42f4-8036-489a8325eae3.jpg)

**Comment by alankilborn** [comment]
Already supported, RTFM:
https://npp-user-manual.org/docs/searching/#:~:text=exclude%20particular%20folders

Please close this issue.
