### ISSUE TITLE
[REQ] Can we pin/lock tabs?

### ISSUE THREAD

**Issue by worldor** [notepad-plus-plus/notepad-plus-plus#12806]
Hello

[REQ] Can we pin/lock tabs?
I read online such request from 2015 but still cannot see any implementation.

Thanks!

**Comment by alankilborn** [comment]
Duplicate of #5786 
Please close this issue.

**Comment by donho** [comment]
https://github.com/notepad-plus-plus/notepad-plus-plus/commit/ce58b424bdeec3616943f9ea8cd257f66700c3c0
