### ISSUE TITLE
When N lines are selected pressing "down arrow" key causes the cursor sometimes to move to line 2 instead of to line N+1

### ISSUE THREAD

**Issue by github-wow** [notepad-plus-plus/notepad-plus-plus#12805]
### Description of the Issue
when N lines are selected (tested for more than 1 screen of lines) pressing "down" arrow key causes the cursor sometimes to move to line 2 instead of line n+1

### Steps to Reproduce the Issue
1. select N lines (more than 1 screen)
2. press "Down Arrow" key

### Expected Behavior
the cursor moves to line N+1

### Actual Behavior
sometimes the cursor moves to line 2 but sometimes to line N+1

### Debug Information
Notepad++ v8.4.6   (64-bit)
Build time : Sep 25 2022 - 19:51:39
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : "path/to/my/file"
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 10 Home (64-bit) 
OS Version : 22H2
OS Build : 19045.2486
Current ANSI codepage : 1252
Plugins : 
    ...list of plugins...

**Comment by alankilborn** [comment]
Not a valid issue; fill in the template.
Provide a specific example as well.
If you're not going to do that, please CLOSE this issue.
