### ISSUE TITLE
"Style all occurences of token" not working

### ISSUE THREAD

**Issue by intrinsor** [notepad-plus-plus/notepad-plus-plus#12803]
### Description of the Issue
when I select a text that appeats multiple times in the document, and then right click -> "Style all occurences of token"
normally it highlights all of these occurences, but actually nothing is highlighted.
It worked with some previous versions.

### Steps to Reproduce the Issue
I select a text that appears multiple times in the document, and then right click -> "Style all occurences of token"

### Expected Behavior
normally it highlights all of these occurences

### Actual Behavior
nothing is highlighted.

### Debug Information
Notepad++ v8.4.8   (64-bit)
Build time : Dec 24 2022 - 19:40:27
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : "C:\Program Files\Notepad++\change.log" 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 10 Pro (64-bit) 
OS Version : 22H2
OS Build : 19045.2486
Current ANSI codepage : 1252
Plugins : 
    mimeTools (2.9)
    NppConverter (4.5)
    NppExport (0.4)

It worked with some previous versions.
At least with 6.7.7. it is working !!

**Comment by alankilborn** [comment]
Your settings in _Preferences_ for _Highlighting_ are set contrary to what you think should be happening.
Check and adjust those, and/or read the user manual.
Without an exact example from you, I can't tell you exactly what is set up wrong. 
Please close this issue.

**Comment by intrinsor** [comment]
okay, indeed "Match whole word only" was enabled in settings.
Thats why it wasn't as expected.

Thx

closed.
