### ISSUE TITLE
[AppVeyor build script] Commits may be classified erroneously as "XML changes only"

### ISSUE THREAD

**Issue by dinkumoil** [notepad-plus-plus/notepad-plus-plus#12810]
### Description of the Issue
Commits that change files in certain directories of the project's directory structure are automatically classified as "XML changes only" which causes _AppVeyor_ to run only the build job for _Win32 Debug_. This is presumably caused by [>> this filter in _appveyor.yml_ <<](https://github.com/notepad-plus-plus/notepad-plus-plus/blob/7fad2a62d43eeaf6023046277e77fb260c9c54a3/appveyor.yml#L41) which is applied at [>> this line <<](https://github.com/notepad-plus-plus/notepad-plus-plus/blob/7fad2a62d43eeaf6023046277e77fb260c9c54a3/appveyor.yml#L44). Thus, changed files whose paths contain (case insensitive) the strings `PowerEditor/Test/`, `/filesForTesting/` or `/functionList/` are matched and prevent _AppVeyor_ from building the project with all build tasks because "XML validation mode" is turned on.

### Steps to Reproduce the Issue
1. Open list of changed files of commit 7fad2a62d43eeaf6023046277e77fb260c9c54a3. You will notice that file `PowerEditor/src/WinControls/FunctionList/functionParser.cpp` is changed by this commit.
2. Go to [_AppVeyor_ build details](https://ci.appveyor.com/project/donho/notepad-plus-plus/builds/45956872) of this commit and check all build jobs for artifacts.

### Expected Behavior
All build jobs should provide artifacts as commit 7fad2a62d43eeaf6023046277e77fb260c9c54a3 changes a _*cpp_ file, thus the project should be compiled with all build jobs.

### Actual Behavior
Only the build job for _Win32 Debug_ provides an artifact.

**Comment by vinsworldcom** [comment]
@dinkumoil thank you!  I saw this too and wasn't sure why or where to report it - on the commit itself?  Here seems obvious :-)

Cheers.
