### ISSUE TITLE
Error after replacing Notepad.exe via debugger v8.4.8

### ISSUE THREAD

**Issue by rainman74** [notepad-plus-plus/notepad-plus-plus#12824]
### Description of the Issue
If you replace Notepad.exe with debugger registry key, every time you open a file you get the error message:
Cannot open file " ".

![image](https://user-images.githubusercontent.com/16306963/213677693-0169c500-1ccf-4193-a26d-1847de2ffad8.png)

### Steps to Reproduce the Issue

1. install notepad++
2. set registry keys
3. open a file via Windows Explorer per double click

### Expected Behavior
No error message, as it was with version 8.4.7.

### Actual Behavior
Error message: Cannot open file " "

### Debug Information

![image](https://user-images.githubusercontent.com/16306963/213678987-9117f702-3848-43cf-8975-c8750a584a78.png)

![image](https://user-images.githubusercontent.com/16306963/213679214-02b7b55b-111a-4759-90de-6cdcde49266e.png)

**Comment by alankilborn** [comment]
>It works again when I remove the brackets, but is that intentional?

(For English speakers, `brackets` here means `double quote pair`.)

OK, but if you remove them, isn't that going to break things if the pathname in `%1` contains space(s)?

So, I'd say No, it wasn't intentional.

**Comment by rainman74** [comment]
> double quote pair

No, the missing double quote pairs do not break anything, even if the filename contains spaces, but you have to remove these double quotes from the entries of reg-files, cmd-files, etc., because this is the Microsoft standard, which leads to the problem in the latest Notepad v8.4.8.

Example:
![image](https://user-images.githubusercontent.com/16306963/213786642-d7dbd383-61fd-4547-a021-7d70aa6396c9.png)

**Comment by rdipardo** [comment]
> If you replace Notepad.exe with debugger registry key, every time you open a file you get the error message: Cannot open file " ".

Duplicate of #12775, which was [fixed a week ago](https://github.com/notepad-plus-plus/notepad-plus-plus/commit/6c3659fe7300992ae7a3cd32410377bd88ac263a).

**Comment by rainman74** [comment]
> > If you replace Notepad.exe with debugger registry key, every time you open a file you get the error message: Cannot open file " ".
> 
> Duplicate of #12775, which was [fixed a week ago](https://github.com/notepad-plus-plus/notepad-plus-plus/commit/6c3659fe7300992ae7a3cd32410377bd88ac263a).

Thanks for the info. I compiled the latest master and it fixed the problem!
