### ISSUE TITLE
The plugin BracketsCheck does not work

### ISSUE THREAD

**Issue by Pawwwle** [notepad-plus-plus/notepad-plus-plus#12825]
The plugin BracketsCheck does not work. I tested version 1.2.2 and 1.2.3.
Shouldn't plugin then be removed from the repository and blocked installable?

**Comment by ArkadiuszMichalski** [comment]
@Pawwwle You should report this to author of this plugin:
https://github.com/niccord/BracketsCheck

**Comment by chcg** [comment]
@Pawwwle Against which version of N++ do you test? 32 or 64 bit?

**Comment by Pawwwle** [comment]
I am using N++ latest 64 bits version. The addon falsely alerts in php about unclosed parentheses.

**Comment by Pawwwle** [comment]
My notification under verification: [https://github.com/niccord/BracketsCheck/issues/15](url)
