### ISSUE TITLE
v8.4.8 hanging while opening some Pascal files

### ISSUE THREAD

**Issue by donho** [notepad-plus-plus/notepad-plus-plus#12822]
Notepad++ v8.4.8 hanging while opening some Pascal files.

### Description of the Issue
Notepad++ v8.4.8 hanging (with Function list panel opened) while opening [these 2 Pascal files](https://github.com/notepad-plus-plus/notepad-plus-plus/files/10460178/2_files_hanging_npp.zip).

### Steps to Reproduce the Issue
1. Launch Notepad++ v8.4.8
2. Open the Function list panel
3. Open the 2 provided files in zip

### Expected Behavior
2 files can be opened in Notepad++.

### Actual Behavior
Notepad++ is hanging.

### Debug Information
```
Notepad++ v8.4.8   (64-bit)
Build time : Dec 24 2022 - 19:40:27
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 11 (64-bit) 
OS Version : 21H2
OS Build : 22000.1455
Current ANSI codepage : 1252
Plugins : 
    mimeTools (2.9)
    NppConverter (4.5)
    NppExport (0.4)

```

~~The hanging of opening 2 Pascal files is due to the PR #12489, obviously the hanging issue is fixed in #12811, so the issue will be fixed in the next release (v8.4.9) of Notepad++~~

The hanging of opening 2 Pascal files is due to function list parser (C++ code) problem. See [the analysis](https://github.com/notepad-plus-plus/notepad-plus-plus/issues/12822#issuecomment-1397862706)

**Comment by dinkumoil** [comment]
The file `main.pas` which is contained in the provided ZIP file contains code that does not represent a valid _Pascal_ unit file. Testing function list parsers with invalid test files that are not compilable should be avoided.

**Comment by donho** [comment]
@dinkumoil 
> The file `main.pas` which is contained in the provided ZIP file contains code that does not represent a valid _Pascal_ unit file.

Could you provide more detail of this argument please?

**Comment by rdipardo** [comment]
> The file `main.pas` which is contained in the provided ZIP file contains code that does not represent a valid _Pascal_ unit file. 

Indeed, the other one (`Bass.pas`) has problems of its own.
There's an unfinished nested block comment starting at line 791:

    Free Pascal Compiler version 3.2.2 [2022/09/24] for i386
    Copyright (c) 1993-2021 by Florian Klaempfl and others
    Target OS: Win32 for i386
    Compiling Bass.pas
    Bass.pas(791,1) Warning: Comment level 2 found
    Bass.pas(801,1) Warning: Comment level 2 found
    Bass.pas(869) Fatal: Unexpected end of file
    Fatal: Compilation aborted

**Comment by rdipardo** [comment]
@donho,
> Could you provide more detail of this argument please?

"Garbage in, garbage out."

Why not just fetch [a real Pascal source file](https://gitlab.com/freepascal.org/lazarus/lazarus/-/raw/main/components/activex/activexcontainer.pas) from [a public repository](https://gitlab.com/freepascal.org/lazarus/lazarus) instead?

**Comment by donho** [comment]
@dinkumoil @rdipardo 
Well, the problem is Notepad++ hanging due to the old pascal.xml parsing these 2 files.
Though the hanging has been fixed in the current version pascal.xml (in master), in order to prevent future version of pascal.xml from making Notepad++ crashing again, these 2 invalid Pascal could help as sentinel.  Or do you've got a better idea?

**Comment by mpheath** [comment]
The 2 files `main.pas` and `Bass.pas` are decompiled from an InnoSetup installer. These sources are probably from a cracker/repacker setup as `Bass.dll` is used to control audio and `IsDone.dll` has functions to assist with validation. The decompiler has done a poor job as can be seen with all the `?` characters and the url redirects to some investment promotion.

I am getting some recurring pairs

```
funcZone: 18446744073709551614, 3131
fi._pos: -1
fi._pos2: -1
begin,end: 3131, 169813
```
as these 4 lines repeat. The 1st number is `targetStart` which is `size_t`. Probably an overflow with bad type?

The while loop never ends:

https://github.com/notepad-plus-plus/notepad-plus-plus/blob/61408653518a1aa851299ef0af594a37db66e30f/PowerEditor/src/WinControls/FunctionList/functionParser.cpp#L395

as `targetStart` constantly passes the condition.

funcZone output is from
``` c++
std::cout << "funcZone: " << targetStart << ", " << targetEnd << std::endl;
```
which inserted after
https://github.com/notepad-plus-plus/notepad-plus-plus/blob/61408653518a1aa851299ef0af594a37db66e30f/PowerEditor/src/WinControls/FunctionList/functionParser.cpp#L403-L405

Pos 3131 in `main.pas` is
``` pascal
function IS7zipExtract(Arg0: ?; Arg1: ?; Arg2: ?; Arg3: ?; Arg4: ?; Arg5: ?): ? stdcall;
	external 'IS7zipExtract@ISDone.dll stdcall DelayLoad';
                             ^
```
roughly where I inserted the `^` and `169813` is EOF. Pos `3131` is a weird IMO.

These files display a bug in the function list parser which causes an endless loop.

**Comment by donho** [comment]
@mpheath 
> as these 4 lines repeat. The 1st number is targetStart which is size_t. Probably an overflow with bad type?
>
> The while loop never ends:

You are right about it. 
After fix the type of `targetStart` & `targetEnd` from `size_t` to `intptr_t`, opening the 2 files in question with old version of pascal.xml (#12489).

Thank you for your tip and help - it's indeed the problem in the C++ code (my negligence) but not in old version of pascal.xml. Even the Regular Expression is badly done, application should not crash.

Thank you @dinkumoil @rdipardo for your suggestions.

**Comment by dinkumoil** [comment]
Sorry for my late response, I was off-keyboard soon in the evening yesterday. Thank you @rdipardo and @mpheath for helping out to clarify the situation.
