### ISSUE TITLE
Add new command and default keycombo for Begin/End Select in column mode

### ISSUE THREAD

**Issue by alankilborn** [notepad-plus-plus/notepad-plus-plus#12833]
### Description of the Issue

-----------------------------------------

PREAMBLE NOTE: If #12832 is adopted, this would be a nice addition as well.  If 12832 is NOT adopted, this probably doesn't make sense to implement on its own.

-----------------------------------------

Currently Notepad++ ships with one sample macro, _Trim Trailing Space and Save_.  I'd like to suggest a second one be created and shipped with Notepad++ releases.

I'd call this macro "Begin/End Select in Column Mode" and I would suggest a default key assignment of Alt+Shift+b.  The Alt+Shift part reminds the user of the column-mode nature of running the macro -- because the user is used to using Alt+Shift+arrows to make a keyboard column selection.

Here is the suggested macro content:

```
<Macro name="Begin/End Select in Column Mode" Ctrl="no" Alt="yes" Shift="yes" Key="66">
    <Action type="0" message="2429" wParam="0" lParam="0" sParam="" />
    <Action type="0" message="2428" wParam="0" lParam="0" sParam="" />
    <Action type="2" message="0" wParam="42020" lParam="0" sParam="" />
</Macro>
```

----------------------------------------

Here's how the suggested entry would appear on the _Macro_ menu:

![image](https://user-images.githubusercontent.com/77065706/213866753-7dcea1f2-c4eb-492c-a9a2-e699b6cd58e1.png)

----------------------------------------

Here's a usage example, for clarity:

1. Open Notepad++'s `license.txt` file.
2. Move the caret to line 1, column 5.
3. Invoke the (suggested) Shift+Alt+b keycombo (to begin-select).
4. Move the caret to the last line of the file, column 20.
5. Invoke the (suggested) Shift+Alt+b keycombo a second time (to end-select).
6. Observe the (longish) column block selection is made:

![image](https://user-images.githubusercontent.com/77065706/213866056-59bebeb0-1676-4c81-b9ae-2d74bc0af504.png)

------------------------------------------

NOTE: This issue has its basis in discussions in this Community thread: https://community.notepad-plus-plus.org/topic/20616

-----------------------------------------

### Debug Information
Feature request based on current content of Notepad++ 8.4.8.

**Comment by pryrt** [comment]
> If 12832 is NOT adopted, this probably doesn't make sense to implement on its own.

Personally, I'm more likely to use this one (which is why I have that macro).  I think it would be good to have this one in the default macros for a fresh install.

**Comment by donho** [comment]
That's a good feature.
My only concern is the shortcut - for users who have already Alt-Shift-B defined, there will be the conflict.

**Comment by alankilborn** [comment]
> That's a good feature.
> My only concern is the shortcut - for users who have already Alt-Shift-B defined, there will be the conflict.

It's true, but I think for the "greater good of the software" going forward...that it should be done.
Thank you for liking my suggestion.

**Comment by donho** [comment]
@alankilborn 
> PREAMBLE NOTE: If #12832 is adopted, this would be a nice addition as well. If 12832 is NOT adopted, this probably doesn't make sense to implement on its own.

I don't think this PR depends on #12832. As I mentioned, my concern is added new shortcuts will have conflicts with users' defined - and users who use Begin/End Select command have added their own defined shortcut certainly. So #12832 won't be accepted.
However, it's interesting the macro of Begin/End Select in column mode.

**Comment by alankilborn** [comment]
>users who use Begin/End Select command have added their own defined shortcut certainly. So 12832 won't be accepted.

It certainly would be nice to just say "the standard shortcut for Begin/End Select is ____".
Users wouldn't be overly annoyed that Notepad++ took over one of their custom assignments with the goal of standardization going forward; they'd just reassign it back to what they like and move on.  Or even better, say, "this is what Notepad++ says it should be...well, OK then".

**Comment by alankilborn** [comment]
Assigning new default keycombos is not without recent precedent.
It wasn't too long ago that _Mark_ was assigned to Ctrl+m, I see.

**Comment by donho** [comment]
> It wasn't too long ago that _Mark_ was assigned to Ctrl+m, I see.

Is there any complain for it?

**Comment by alankilborn** [comment]
>Is there any complain for it?

I don't recall a single complaint.
@pryrt , do you remember any complaint?

**Comment by pryrt** [comment]
Not that I recall.  And a quick search doesn't reveal any.

**Comment by donho** [comment]
OK.
Could you guys create a PR for both #12832 & #12833 ?

**Comment by alankilborn** [comment]
I had a late thought:

It is "cool" that the column version could be a macro, and we can move forward with that, but should it be considered to instead be a "real command", e.g., on the _Edit_ menu there would be the existing _Begin/End Select_ and then right below it "Begin/End Select in Column Mode" ??

**Comment by alankilborn** [comment]
So it could appear on the _Edit_ menu as:

```
...
----------------------
Column Mode HOW-TO...
Column Editor...                       Alt+C
Begin/End Select in Column Mode        Alt+Shift+B
----------------------
...
```

**Comment by pryrt** [comment]
Based on the way Don described it, I interpret that as either 1 or 2 below:
![image](https://user-images.githubusercontent.com/17455758/214086025-3e870fed-4af3-416e-a276-7f4df21c637e.png)

Based on the way Alan originally described this, I was imagining it as 3:
![image](https://user-images.githubusercontent.com/17455758/214086112-e0434310-e556-47b4-bb5b-b30a0834a339.png)

Personally, I would prefer it as 3, because it falls more naturally for me with Select All and Begin/End Select.

**Comment by donho** [comment]
@pryrt @alankilborn 
Thank you for your thought. 
Let's take Solution 3 which is also the original proposal of @alankilborn. 

And Column Mode Tip dialog message will be change from:
```
Please use "ALT+Mouse Selection" or "Alt+Shift+Arrow key" to switch to column mode.
```
to
```
There are 3 ways to switch to column mode:
1. Keyboard + Mouse: "ALT+Mouse Selection"
2. Keyboard: "Alt+Shift+Arrow key"
3. Command + caret position (via Mouse or Keyboard):  1st caret position + "Begin/End Select Column Mode (Alt+Shit+B)" + 2nd caret position + "Begin/End Select Column Mode (Alt+Shit+B)"
```

Any suggestion for a better Column Mode Tip dialog message ?

**Comment by alankilborn** [comment]
>Any suggestion for a better Column Mode Tip dialog message ?

I don't think we should say "shit" to the user in your number 3.
Number 2 would be a better place to say that (total joke, hopefully you understand that one).
(we want to say `Shift`, not `Shit`)

OK, I can tweak the message.
I'll see what I can do about submitting something to make these changes.
But as I am not set up for submitting PRs, it will take me a bit of time.
I see that translation files are currently being submitted for an 8.4.9 release.
Certainly don't hold up 8.4.9 waiting for me with this really minor feature.

**Comment by donho** [comment]
> I don't think we should say "shit" to the user in your number 3.
> Number 2 would be a better place to say that (total joke, hopefully you understand that one).
> (we want to say `Shift`, not `Shit`)

:D 
The 2nd one is convenient too, it depends on users' habit/

> I see that translation files are currently being submitted for an 8.4.9 release.
Certainly don't hold up 8.4.9 waiting for me with this really minor feature.

v8.4.9 is already on its way, so this feature will be in the next next version (v8.5) for sure.

> I'll see what I can do about submitting something to make these changes.
> But as I am not set up for submitting PRs, it will take me a bit of time.

I can do it if there are too many tasks for you.
Just let me know.

**Comment by alankilborn** [comment]
>I can do it if there are too many tasks for you.

I'll try it...should be fairly simple.
We have some time before 8.5.

**Comment by alankilborn** [comment]
@donho, Probably easiest to combine #12832 and #12833 into a single PR -- acceptable?

**Comment by donho** [comment]
> @donho, Probably easiest to combine #12832 and #12833 into a single PR -- acceptable?

Sure - it makes sense to me.

**Comment by alankilborn** [comment]
@donho, After some review of "reality" :-) I wanted to change the spec on this, and of course want your approval before proceeding with it.

I think we are best served by this slight change to the proposed menu from Peter's "3" above:

```
* Begin/End Select            Ctrl+Shift+B
* End Select in Column Mode   Alt+Shift+B
```

"Begin" of the selection doesn't need to know the user-desired type (stream or column).

So the suggestion is that user uses `Begin/End Select` to start a selection, always.  When user wants to end a stream selection, they again use `Begin/End Select` (no change from existing behavior).  When user wants to end selection and have a column block appear, they use `End Select in Column Mode`.

There would be no change to the existing menu checkmark behavior for `Begin/End Select`.

There would be no menu checkmark at all for `End Select in Column Mode` as it is not needed.

However, `End Select in Column Mode` would be disabled/greyed if no "begin" is in effect.
Thus, these situations would always be true:
* if `Begin/End Select` has no menu checkmark, then `End Select in Column Mode` is disabled/greyed
* if `Begin/End Select` has the menu checkmarked, then `End Select in Column Mode` is enabled

What do you think?

**Comment by donho** [comment]
@alankilborn 
Your new proposal is logic and understandable from the devs' view (or from the view of ppl who do know well about Scintilla component). 
However a newbie of Notepad++ would be confused by `"Begin/End Select" + "End Select in Column Mode"` & `"Begin/End Select" + "Begin/End Select" command"` combinations for 2 modes of selection.
Furthermore, using shortcuts `"Ctrl+Shift+B" + "Alt+Shift+B"` needs more effort to not invert the combination and to memorize. I would say it makes more sense `"Alt+Shift+B" + "Alt+Shift+B"` if user wants to do a column selection.
If users find out it's possible to do `"Ctrl+Shift+B" + "Alt+Shift+B"`, it's good to them - they will have more option for column selection.

For the sake of simplicity and less confusion, I prefer the separation of the 2 sets of commands for the 2 modes of selection.

**Comment by alankilborn** [comment]
@donho

OK, I will proceed based upon that feedback.

However, 

>If users find out it's possible to do "Ctrl+Shift+B" + "Alt+Shift+B", it's good to them - they will have more option for column selection.

I don't think this works.

If a user has activated `Ctrl+Shift+B` to create a begin-of-stream-select-position, and then sometime later presses `Alt+Shift+B`, wouldn't that cancel the begin-of-stream and create a begin-of-column-select-position?  I'm trying to think of novice user expectation here, but maybe I'm failing because I am not a novice user.

**Comment by pryrt** [comment]
I think greying out the opposite mode until the selection is **End**ed is probably the most user-intuitive way of handling it.  That way, it's abundantly clear to the user that they have to **End** in the same mode they **Began**.

**Comment by alankilborn** [comment]
>3. Command + caret position (via Mouse or Keyboard):  1st caret position + "Begin/End Select Column Mode (Alt+Shift+B)" + 2nd caret position + "Begin/End Select Column Mode (Alt+Shift+B)"

The keycombos should NOT be embedded into this text (the "Column mode tip text") because these are just default/suggested keycombos, and can be changed by the user.

I will remove them from the text, and adjust the (entire) tip text a bit as well (to make it even better).

**Comment by donho** [comment]
@alankilborn 
> The keycombos should NOT be embedded into this text (the "Column mode tip text") because these are just default/suggested keycombos, and can be changed by the user.

Hmm... you're right about it. Let's remove the shortcuts from the tip then.
