### ISSUE TITLE
Assign default shortcut keycombo of Ctrl+Shift+b to Begin/End Select command

### ISSUE THREAD

**Issue by alankilborn** [notepad-plus-plus/notepad-plus-plus#12832]
### Description of the Issue
The very useful command _Edit_ (menu) > _Begin/End Select_ has no default key binding.
Suggest defaulting the currently unused Ctrl+Shift+b to this command.  (NOTE: Ctrl+b might be better for this function, but it is already used in the default keymapping supplied with N++).

Usage of this command comes up frequently on the support site, for users seeking to select a lot of text without long scrolling with a keyboard or mouse selection.  It would be nice to tell users to use a keycombo to start/end their selection, instead of saying "go into the _Edit_ menu and choose _Begin/End Select_, then move your caret, then go back into the _Edit_ menu and choose _Begin/End Select_ again".

### Debug Information
Feature request based on default key assignments in Notepad++ 8.4.8

**Comment by pryrt** [comment]
Every few months, we do get people wanting to do things where it would be easiest to tell them a keyboard sequence, but instead we had to give the detailed menu commands for each step.  Having Notepad++ ship with a keyboard shortcut for that action would be helpful in helping users.

- https://community.notepad-plus-plus.org/post/83495 (https://community.notepad-plus-plus.org/topic/20616/remove-columns-from-a-file)
- https://community.notepad-plus-plus.org/post/70040 (https://community.notepad-plus-plus.org/topic/21883/need-numbers-going-up-on-every-blank-line-followed-by-a-previous-line-break-for-subtitles)
- https://community.notepad-plus-plus.org/post/71915 (https://community.notepad-plus-plus.org/topic/22201/installing-outdated-plugin)
- https://community.notepad-plus-plus.org/post/76689 (https://community.notepad-plus-plus.org/topic/22965/copy-entire-code-group)
- https://community.notepad-plus-plus.org/post/80082 (https://community.notepad-plus-plus.org/topic/23529/selecting-text-while-doing-a-search-in-a-macro)
- https://community.notepad-plus-plus.org/post/83315 (https://community.notepad-plus-plus.org/topic/24011/quick-way-to-mark-columns-using-the-keyboard)
