### ISSUE TITLE
German translation file contains wrong translation

### ISSUE THREAD

**Issue by dinkumoil** [notepad-plus-plus/notepad-plus-plus#12839]
### Description of the Issue
The current translation file for german contains a wrong and misleading translation for an option in preferences dialog.

![grafik](https://user-images.githubusercontent.com/24699812/213994757-fa572103-fa2b-484c-9f7d-26081b0e584d.png)

In `english.xml` the [item with translation id 6431](https://github.com/notepad-plus-plus/notepad-plus-plus/blob/0d22c4d867cfffb5da6a0567421fef2049f865ea/PowerEditor/installer/nativeLang/english.xml#L1002) reads

> Open all files of folder instead of launching Folder as Workspace on folder dropping

In `german.xml` the [same item]( https://github.com/notepad-plus-plus/notepad-plus-plus/blob/0d22c4d867cfffb5da6a0567421fef2049f865ea/PowerEditor/installer/nativeLang/german.xml#L1009) reads

> Alle Dateien im jeweiligen Verzeichnis öffnen anstelle des Start-Verzeichnisses

whose meaning in english is

> Open all files in the respective directory instead of the start directory

A correct translation (that fits in the available space of the preferences dialog) could be

> Verzeichnis-Drag&Drop öffnet alle enthaltenen Dateien statt „Verzeichnis als Arbeitsbereich“ zu starten

Thus, the following line should replace the current line in `german.xml`:

```xml
<Item id="6431" name="Verzeichnis-Drag&amp;&amp;Drop öffnet alle enthaltenen Dateien statt &quot;Verzeichnis als Arbeitsbereich&quot; zu starten"/>
```
@schnurlos I sent you an email but you ignored it.

### Applies to
German translation of upcoming version of Notepad++ after v8.4.8

**Comment by schnurlos** [comment]
Sorry & thanks, but I was busy with real life!
