### ISSUE TITLE
applying style token resize Notepad++ window

### ISSUE THREAD

**Issue by thomasleveil** [notepad-plus-plus/notepad-plus-plus#1283]
Since I updated Notepad++ to v6.8.8, every time I:
- select some text
- right click
- style tokens
- apply style #

The Notepad++ window gets resized in height and width to the bare minimum and it is moved to the top left corner of my screen.

![2015-12-23_09h10_14](https://cloud.githubusercontent.com/assets/42300/11973081/7d84b7f6-a955-11e5-947d-e9a25133ab51.png)
![2015-12-23_09h11_53](https://cloud.githubusercontent.com/assets/42300/11973082/807e87de-a955-11e5-8dbb-e1fa108accdd.png)

```
Notepad++ v6.8.8
Build time : Dec 10 2015 - 01:11:37
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : ON
Local Conf mode : OFF
OS : Windows 7
Plugins : ComparePlugin.dll JSLintNpp.dll mimeTools.dll NamedBookmarks.dll NppConverter.dll NppExport.dll NppFTP.dll NPPJSONViewer.dll NppJumpList.dll NppSaveAsAdmin.dll NppTextFX.dll PluginManager.dll Python Indent.dll PythonScript.dll regrexplace.dll SpellChecker.dll XMLTools.dll ZenCoding-Python.dll 
```

**Comment by cmeriaux** [comment]
Hello,
I don't have your problem on my Job PC and my home PC. One of your plugin may be provoke this problem
Here is my config : 

```
Notepad++ v6.8.8
Build time : Dec 10 2015 - 01:11:37
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : ON
Local Conf mode : OFF
OS : Windows 7
Plugins : CodeAlignmentNpp.dll FileFinder.dll LightExplorer.dll linefilter2.dll mimeTools.dll NppConverter.dll NppExec.dll NppExport.dll NppFTP.dll NppGTags.dll NPPJSONViewer.dll NppMenuSearch.dll OpenSelection.dll PluginManager.dll SherloXplorer.dll 
```

**Comment by thomasleveil** [comment]
I tried @ home and could not reproduce. However on my work computer, the problem still exists event after deleting everything within the `plugins` folder.

Also I uninstalled Notepad++, downloaded the installer again and went on with a clean install and I still have that bug.

Let me know what can I do to provide additional information.
