### ISSUE TITLE
Undo "Single Line Uncomment"

### ISSUE THREAD

**Issue by Yaron10** [notepad-plus-plus/notepad-plus-plus#12830]
**STR:**
Paste the following code into a new document and set the language to CSS.
```
:root
{
	/* --toolbarbutton-inner-padding: 6px !important; */
	/* --arrowpanel-border-radius: 0px !important; */
	/* --panel-border-radius: 0px !important; */
}

.tab-context-line { height: 30px !important;  flex: 1 !important; }
```
Select lines 3, 4 and 5.
"Single Line Uncomment".
Undo.

**Result:**
Only Line 5 is undone and re-commented.

**Expected:**
A single Undo should re-comment the three lines.

***
Notepad++ v8.4.8   (64-bit)
Build time : Jan 20 2023 - 14:41:09
Path : C:\---notepad++.exe
Command Line : 
Admin mode : ON
Local Conf mode : ON
Cloud Config : OFF
OS Name : Windows 10 Pro (64-bit) 
OS Version : 20H2
OS Build : 19042.985
Current ANSI codepage : 1255
Plugins : 
    ComparePlus (1.1)
    HTMLTag (1.3.6)
    MenuIcons (2.0.2)
    PythonScript (2)
    _CustomizeToolbar (4.2)

**Comment by Yaron10** [comment]
@donho,

👍 
Thank you for that too.

**This commit creates another issue:**
Paste the code above.
Select lines 3, 4 and 5.
"Single Line Uncomment".
*Delete line 5.*
Undo.

**Result:**
The 3 lines are wrongly commented.

**Comment by Yaron10** [comment]
There are Undo Begin/End points within the loop.

**Comment by donho** [comment]
@Yaron10 
Thank you for your help!
It should be fixed now.
Please let me know if you found the other issues.

**Comment by Yaron10** [comment]
@donho,

Great. 👍 
Thank you. I appreciate your work.
