### ISSUE TITLE
"Show All Characters" button does not highlight NBSP or SHY

### ISSUE THREAD

**Issue by jmcwilliams403** [notepad-plus-plus/notepad-plus-plus#12836]
### Description of the Issue
screenshot of three spaces followed by three nonbreaking spaces followed by three spaces:
![image](https://user-images.githubusercontent.com/37010132/213934927-ab6e8e56-9db3-4333-87f3-171e481ed441.png)
screenshot of three spaces followed by three soft hyphens followed by three spaces:
![image](https://user-images.githubusercontent.com/37010132/213935464-d5aa19cf-045b-4cb6-9132-c504b4282356.png)

### Steps to Reproduce the Issue

1.  Click the "Show All Characters" button (stylized as "¶")
2. if your keyboard layout has these characters, type them, otherwise copy/paste " " & "­" or use alt codes
3. ????
4. Profit

### Expected Behavior
a black box with the acronym SHY and/or NBSP etched out of it

### Actual Behavior
no special treatment as opposed to "Show All Characters" being off.

### Debug Information
Notepad++ v8.4.8   (32-bit)
Build time : Dec 24 2022 - 19:30:12
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 10 Home (64-bit) 
OS Version : 22H2
OS Build : 19045.2486
Current ANSI codepage : 1252
Plugins : 
    mimeTools (2.9)
    NppConverter (4.5)
    NppExport (0.4)
    NppMarkdownPanel (0.6.2)

**Comment by alankilborn** [comment]
Duplicate.
Master issue is probably #8284; if you have more to add, please add it there.
Please close this issue.
