### ISSUE TITLE
Plugins Admin missing after Silent Installation, but is present with a manual installation

### ISSUE THREAD

**Issue by mikejunk43** [notepad-plus-plus/notepad-plus-plus#12841]
### Description of the Issue
Installing silently using the /S switch is not installing the Plugins Admin. However, installing manually does install the Plugins Admin.

Can this be corrected?

Also, please advise if there is a different method for silently installing Notepad++.

![image](https://user-images.githubusercontent.com/88735729/214087746-7e3aa323-b56b-4a99-b3f7-d4c2e8bd101f.png)

![image](https://user-images.githubusercontent.com/88735729/214087798-81243bb0-b626-4616-9fbd-9adfdbf978ee.png)

### Steps to Reproduce the Issue
1.  Install Notepad++ from CMD or PS using the /S switch

### Expected Behavior
When Notepad++ is installed silently using the /S switch, the Plugins Admin should be available in Notepad++.

### Actual Behavior
After the silent installation, the Plugins Admin is missing.

### Debug Information
Notepad++ v8.4.8   (64-bit)
Build time : Dec 24 2022 - 19:40:27
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 10 Enterprise (64-bit) 
OS Version : 20H2
OS Build : 19042.2486
Current ANSI codepage : 1252
Plugins : 
    mimeTools (2.9)
    NppConverter (4.5)
    NppExport (0.4)

**Comment by donho** [comment]
@mikejunk43 


    The Plugins Admin was installed with previous versions, so this should not be a feature request.

“previous versions” is vague.
Could you precise in which version Plugins Admin is installed with /S ?

**Comment by mikejunk43** [comment]
> @mikejunk43
> 
> ```
> The Plugins Admin was installed with previous versions, so this should not be a feature request.
> ```
> 
> “previous versions” is vague. Could you precise in which version Plugins Admin is installed with /S ?

I believe it was available with version 8.4.7.  However, shouldn't this be available with all versions of Notepad++?  If not, do you have documentation advising how the installation can be silent and also include the Plugins Admin?

**Comment by donho** [comment]
@mikejunk43 
I have tested with v8.4.9 - silent installation (with `/S`) does install Plugin Admin.
Could you test it?

**Comment by mikejunk43** [comment]
> @mikejunk43 I have tested with v8.4.9 - silent installation (with `/S`) does install Plugin Admin.
> 
> Could you test it? https://community.notepad-plus-plus.org/topic/24055/notepad-v8-4-9-release-candidate

Still the same issue using the installer "npp.8.4.9.Installer.x64.exe" /S

![image](https://user-images.githubusercontent.com/88735729/214603917-b353b52c-eee7-44d0-b224-495a46eedda2.png)

![image](https://user-images.githubusercontent.com/88735729/214604246-3170b3b4-4e7e-439e-ade9-c930eca0d8c1.png)

**Comment by donho** [comment]
@mikejunk43 
I have uninstalled and reinstalled my Notepad++, but I cannot reproduce it. Did you do the same way?
Could anyone reproduce this bug?

**Comment by mikejunk43** [comment]
> @mikejunk43 I have uninstalled and reinstalled my Notepad++, but I cannot reproduce it. Did you do the same way? Could anyone reproduce this bug?

Have you tried installing on a new system that hasn't had Notepad++ installed previously?  I do know that an upgrade retains the Plugins Admin but is missing with a fresh install.

**Comment by mikejunk43** [comment]
Hello, 

Any update on this issue?

**Comment by donho** [comment]
@mikejunk43
After your installation, do you have `C:\Program Files\Notepad++\plugins\Config\nppPluginList.dll` installed?

**Comment by BigJoe1979** [comment]
I have the same issue (no Plugin Admin), but may be a different cause.  

My enterprise installed v8.5 using the /S switch but also deletes the GUP.exe and GUP.xml files to prevent autoupdates.  I do have the nppPluginList.dll present.

Is having GUP integral to the Plugin Admin working?

**Comment by donho** [comment]
@BigJoe1979
> Is having GUP integral to the Plugin Admin working?

Yes. Plugin Admin needs GUP.exe for downloading/installing plugins.  Without GUP.exe Plugin Admin cannot work hence it is hidden.

**Comment by donho** [comment]
I believe this issue is due to lack of GUP.exe so it's not a bug of installer.
