### ISSUE TITLE
Hidden Lines command not working correctly; simple case

### ISSUE THREAD

**Issue by alankilborn** [notepad-plus-plus/notepad-plus-plus#12844]
### Description of the Issue
The _View_ menu's _Hide Lines_ feature is not correctly hiding lines, in all cases.

### Steps to Reproduce the Issue

1. Open Notepad++'s `license.txt` file into a file tab
2. Click+drag down the line number margin, starting on line 2 and stopping when the caret is in the first column of line 5:
![image](https://user-images.githubusercontent.com/77065706/214373988-c9b1b1bf-fdc6-4846-94b1-856d709bf440.png)
3. Execute _View_menu's _Hide Lines_ command (or press Alt+h) to obtain the correct hiding of lines 2-5, inclusive:
![image](https://user-images.githubusercontent.com/77065706/214374298-af41c3bf-13a3-4492-9b0d-08c4978f0999.png)
4. Click+drag down the line number margin, starting on line 7 and stopping when the caret is in the first column of line 11:
![image](https://user-images.githubusercontent.com/77065706/214374515-1784015c-f343-4003-bba6-0dc28c4707dd.png)
5. Execute _View_menu's _Hide Lines_ command (or press Alt+h).

### Actual Behavior
Line 6 did not remain visible:
![image](https://user-images.githubusercontent.com/77065706/214374821-19df67ba-90a5-4671-8ec6-6b35c5a6aba7.png)

### Expected Behavior
I expected lines 1, 6, and 12+ to remain visible.

### Debug Information
Notepad++ v8.4.8   (64-bit)
Build time : Dec 24 2022 - 19:40:27
Path : W:\npp.misc\_NoBackup\Releases\npp.8.4.8\npp.8.4.8.portable.x64\notepad++.exe
Command Line : -titleAdd="8.4.8 64-bit" -multiInst
Admin mode : OFF
Local Conf mode : ON
Cloud Config : OFF
OS Name : Windows 10 Enterprise (64-bit) 
OS Version : 21H2
OS Build : 19044.2364
Current ANSI codepage : 1252
Plugins : 
    mimeTools (2.9)
    NppConverter (4.5)
    NppEditorConfig (0.4)
    NppExport (0.4)
    PythonScript (3.0.14)

**Comment by cynthplusplus** [comment]
It seems like putting the carat on the first line, hitting alt+h, then doing the same on the second line will give you this merged result, regardless of whether there is a line in between.

<img width="315" alt="hide lines merge bug" src="https://user-images.githubusercontent.com/17750551/235297762-cbd6c3c5-003c-4b55-8756-f65426f912f8.png">

<img width="204" alt="hide lines merge bug 2" src="https://user-images.githubusercontent.com/17750551/235297777-1824e6e8-3630-4dc7-b6c5-ab76c42a4195.png">

And when I tried to reproduce this issue, I accidentally hit ctrl-z and this is what happened (removed the text inside the hidden lines but didn't remove the green line):

<img width="400" alt="image" src="https://user-images.githubusercontent.com/17750551/235297842-890bc2b6-ec43-422a-8650-63e948e57fef.png">

Probably an unrelated issue.

**Comment by victorel-petrovich** [comment]
I could reproduce the described steps in the issues.

Notepad++ v8.5.4   (32-bit)
Build time : Jun 17 2023 - 20:40:14
Path : C:\Users\Vic\AppData\npp.8.5.4.portable\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : ON
Cloud Config : OFF
OS Name : Windows 7 Ultimate (32-bit)
OS Build : 7601.24546
Current ANSI codepage : 1252
Plugins : 
    mimeTools (2.9)
    NppConverter (4.5)
    NppExec (0.8.4)
    NppExport (0.4)
    PythonScript (2)
