### ISSUE TITLE
Windows-1251 Locale problem

### ISSUE THREAD

**Issue by stivfil** [notepad-plus-plus/notepad-plus-plus#12847]
### Description of the Issue

When I work with CP1251 locale text file after some amount  of  capital letters the editor during opening file detects 
the locale as Macintosh - the text distorts. If I manually select  the cp1251 locale the text becomes good. 
### Steps to Reproduce the Issue

1.  Take the cyrilic text file in CP1251 locale ~ 10 kB . 
2.  Print  the capital letters ААААААА....АААА  during 3 strings ( maybe more)  in any place of the file. Save it.
3. Open the file.

### Expected Behavior
   
 Мужчина                        Женщина 
Год рождения =    1959       Год рождения =    1960 
Месяц рождения =  1         Месяц рождения =   9 
День рождения =    31         День рождения =    15  
АААААААААААААА ...

### Actual Behavior
 
  ћужчина                        ∆енщина 
√од рождени¤ =    2000       √од рождени¤ =    2023 
ћес¤ц рождени¤ =  1         ћес¤ц рождени¤ =   1 
ƒень рождени¤ =    1         ƒень рождени¤ =    24  
јјјјјјјјјјјјјјјјјјјјјј ...
### Debug Information

Notepad++ v8.4.8   (32-bit)
Build time : Dec 24 2022 - 19:30:12
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Command Line : "D:\Work\Exeshnik\test_24.01.2023.txt"
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 10 Home (64-bit) 
OS Version : 22H2
OS Build : 19045.2486
Current ANSI codepage : 1251
Plugins : 
    mimeTools (2.9)
    NppConverter (4.5)
    NppExport (0.4)

[ExampleFIles.zip](https://github.com/notepad-plus-plus/notepad-plus-plus/files/10497176/ExampleFIles.zip)

**Comment by rddim** [comment]
Confirm

Solution: Try to disable `Autodetect character encoding` in `Settings` > `Preferences...` > `MISC.`

This is very reported issue with this option enabled...

**Comment by stivfil** [comment]
2 rddim
Thank you very much for quick answer. It helps.
