### ISSUE TITLE
'Open containing folder in Explorer'

### ISSUE THREAD

**Issue by Songpyeon** [notepad-plus-plus/notepad-plus-plus#12853]
Before it was possible to right click on file tab and pick this option.
Now it takes an extra step to click it and it's pretty annoying, can you bring this option back as it was?

**Comment by alankilborn** [comment]
You can customize the menu yourself.
See here: https://community.notepad-plus-plus.org/topic/23593
And here: https://community.notepad-plus-plus.org/topic/23956
And also see the user manual.

Please close this issue.
