### ISSUE TITLE
Website is down

### ISSUE THREAD

**Issue by crogonint** [notepad-plus-plus/notepad-plus-plus#12859]
Notepad-plus-plus.org Server Status Check
Notepad++Website Name:
notepad-plus-plus.org
URL Checked:
no response
Response Time:
~38 mins
Down For:
DOWN
Notepad-plus-plus.org is DOWN
It is not just you. The server is not responding...

**Comment by schnurlos** [comment]
confirmed here

**Comment by Bluepoison1337** [comment]
same

**Comment by nikesh-maharjan** [comment]
Same issue

**Comment by lings-aa** [comment]
It blocks access to some IP areas, and currently testing IPs in the UK can access

**Comment by donho** [comment]
@schnurlos 
Is website still down for you?

**Comment by ideapad2009** [comment]
它妈死了，回家奔丧去了，大家不要慌

**Comment by bittin** [comment]
The website is up now

**Comment by donho** [comment]
Thank you @bittin for your info.
This issue can be closed now.
