### ISSUE TITLE
Stop adding political elements to an open source software.

### ISSUE THREAD

**Issue by Yharimium** [notepad-plus-plus/notepad-plus-plus#12854]
My friend, adding political elements to open source software is an unwise act in violation of open source software specifications. I feel so sorry for your momentary impulse.

Admittedly, contemporary young people have an increasingly urgent need for freedom, including freedom of speech. Anyone feels uncomfortable when strictly constrained. Our emotions need to be vented, which is reasonable. However, we should also choose the right place to vent our emotions, right? Open source software is not a good place. After all, notepad++is not your own software. It is an open source software developed by a team, and it is also a world-renowned excellent software. It is more or less unreasonable to vent one's emotions on such a perfect software and impose one's own political views on others.

Although your move to add political elements to open source software was originally intended to resist some unfair factors you think, it really hurt everyone in Chinese Mainland who uses notepad++.

People on both sides of the Straits have seen the "ugliness" of each other's politics, but this does not mean that all people have the same "ugliness" as the politics of their regions. The people of Taiwan are very good, and the people of Chinese Mainland are also very good. They should be kind and work together through difficult times, instead of resisting each other because of some actions of the upper class.

It is understandable that the emotions of contemporary young people are easily intensified. Some young people in Hong Kong fought against the police because of their dissatisfaction with the authorities, and the Hong Kong police responded. In this internal conflict, no one was the winner. In some media reports, public opinion support for Hong Kong is one-sided. They fabricated some unnecessary things to stir up contradictions between Chinese Mainland, Hong Kong and Taiwan, and reduce China's core influence on the world. This will not benefit any participant except the instigator. Emotional young people tend to be the biggest accomplices.

The boycott content in Notepad ++ will regrettably encourage this activity to weaken the political and economic vitality of Chinese Mainland, Hong Kong and Taiwan.

The first step to turn Taiwan into "Ukraine" has been extremely successful. Today, Taiwan's open-source software announced a break with Chinese Mainland, and tomorrow it will be industrial and agricultural products. People on both sides of a strait fall into a cycle of discrimination against each other. Taking the conflict between Russia and Ukraine as a reference, one day, Taiwan leaders such as Tsai will become the trigger for war, and Chinese Mainland and Taiwan Island will shoot missiles at each other like Russia and Ukraine. Some people are willing to be clowns and fantasize that the real invaders can save the world they think is in deep water, some innocent civilians are blown to pieces, while a "certain country" will be great again. People have never learned anything from history, even the history at hand.

I use my right of "freedom of speech" to submit this issue to the open source project notepad++. If you see this issue, please carefully consider what I said. Don't be a narrow-minded person, open your vision and pattern, and think about how to bring real benefits to the people on both sides of the Strait.

With best wishes.

**Comment by futz12** [comment]
Me Too

**Comment by FuKun0113** [comment]
俺也一样

**Comment by ZengXiaoPi** [comment]
fuck you ,notepad++

**Comment by 5Erb6rBGCQn** [comment]
我认为添加任何形式的政治诉求 / 观点是作者的自由，你可以不用该软件，或者创建属于你自己 Fork，这才是开源软件该有的要素。（FORK IS WELCOME）
开源并不代表不能在软件中添加任何的政治观点，这两者没有任何逻辑关系。

I think it is author freedom, you can do not use it, FORK IS WELCOME.
Open source software doesn't mean he cannot add any personal emotion or political views into his software.

**Comment by futz12** [comment]
Welcome to use https://github.com/NotepadFree/NotepadFree?
But I think is not clean still.

**Comment by Random7239** [comment]
由于某种未知原因，我暂时无法打开 Notepad++ 的官网，看不到更新日志，姑且随便说几句。
虽然 @donho 生活在法国，但是依照国际范围内比较有影响力的判例（[Bernstein v. United States](https://en.wikipedia.org/wiki/Bernstein_v._United_States)），软件源代码属于言论的范畴，受到宪法言论自由条款的保护。
原则上，我赞成 @5Erb6rBGCQn 的观点：在开放源代码的基础上，GNU 自由软件可以被任意复刻、修改，“合之则留，不合则去”应当是适用于自由软件的准则。作者没有强迫任何人使用这个软件，即使你一定要用， 你也可以自己动手修改。Notepad++ 不是一款面向无代码能力的用户的软件。
尽管我不反对在开源软件中表达政见，同时我对作者的政治立场整体上不持反对态度，但是作为一名（自诩的）自由主义者，我依然要对作者的决定表示**极度的遗憾**：
在某种意义上，**“容忍”与“非强制”是当代自由主义的道义与力量之源**。当你敌视的政治实体在使用骇人听闻的技术和武力手段打压异己、控制思想，对于政治自由和思想自由的拥护者而言，效仿敌人的举措绝非明智之举——当然，如果你并不推崇自由的价值，而只是无比厌恶中共的话，当我什么都没说。
虽然作者在 Twitter 上所描述的修改（暂且不知如何实现）远没有达到中共维稳体系严苛程度的万分之一，但这终归伤及了 Notepad++ 作为开源软件的[道义基础](https://github.com/notepad-plus-plus/notepad-plus-plus/issues/12324#issuecomment-1286360079)：“我们”可以心平气和地在言论自由的场域内亮明自己的政治观点，“他们”不行；“我们”可以容纳在我们看来近乎反人类的“错误”观点（Notepad-- 作者语），“他们”不行。
当我们如中共支持者一般行事的时候，我们是没有资格指责他们的。拖垮苏联的是苏共自己的昏庸、颟顸和暴行，不是麦卡锡主义。
我希望那条 Tweet 只是一个玩笑。
P.s. 致中共支持者：你们阐述的很多“事实”，在旁观者看来，恐怕只能算作一种“信念”。

For some reason, I can't open the official website of Notepad++ and read the release note. So let me just say a few words.
Although the author lives in France, software source code falls under the umbrella of speech and is protected by free speech clause, according to Bernstein v. United States, a internationally influential jurisprudence.
I agree with @5Erb6rBGCQn : on the basis of open-source, GNU software can be freely forked and modified. The author doesn't force anyone to use Notepad++. Even if you have a reason to use it, you can make your own modifications. Notepad++ is not a software designed for those who can't code.
In general, I have no objection to either the expressing political opinions in open-source software or the author's political stance, but as a self-proclaimed liberal, I still have to express my extreme regret for the author's decision:
In a sense, tolerance and non-coercion are the source of the morality and strength of contemporary liberalism. When your enemies are suppressing dissent and implementing thought control through appalling ways, it's not a wise move to act like those you oppose. Of course, if you don't cherish the value of freedom and just hate CCP, forget what I said.
The modification described in the Tweet is far less harsh than what CCP is doing now, but it still undermines the moral basis of Notepad++: "we" can express our political opinions calmly within the scope of freedom of speech, and "they" can't; "we" can tolerate those "wrong opinions" (said by the author of Notepad--, a modified Notepad++ maintained by CCP supporters) that are almost anti-human to us, and "they" can't.
When we behave like CCP supporters, we are in no position to accuse them. It's CPSU's stupidity and brutality which brought down the Soviet Union, not McCarthyism.
I hope that Tweet was just a joke.
P.s. To CCP supporters: I am afraid that many of the "facts" you state can only be regarded as some kind of "belief" in the eyes of bystanders.

**Comment by Yharimium** [comment]
> I think it is author freedom, you can do not use it, FORK IS WELCOME. Open source software doesn't mean he cannot add any personal emotion or political views into his software.

On the one hand, I support your statement. In principle it's completely correct. And it is quite good that the author can WELCOME FORK.

On the other hand, it seems to be inconsistent with the consensus of the entire open source community. Just like Node.js and OpenJS -- in order to maintain the harmonious atmosphere of the open source community, they finally withdrew the political declaration on the homepage of their website.

People can choose to publish your comments on the appropriate social platform, but please don't get involved in open source projects. Open source projects like Node.js are not backed by a single person. They have contributors from all over the world and many users of the project. Some inappropriate political comments will always hurt some people.

Hasn't Notepad++ been the same? So please end this farce as soon as possible. There is no politics here. Developers all over the world should be a family.

**Comment by clqs803** [comment]
作者智障，和它说不通的  以后软件作者生孩子得多检查检查有没有PY

**Comment by ebpaa** [comment]
@5Erb6rBGCQn @Random7239 
Microsoft，Github与npm的所有者，在faker.js的作者出于“政见”而在软件放置逻辑炸弹这一事件中，做出的处理（他们接管了该作者的账号，禁止原作者访问）显然与你们的愿景相悖。
当然，你们是不会在意这种事情的，因为所有人都知道打中文的“自由支持者”十有八九支持的是“American”而非“Freedom”。

**Comment by yinlinghunjiang** [comment]
Turn that down, bro, spamming can't hurt anyone

**Comment by ebpaa** [comment]
> Turn that down, bro, spamming can't hurt anyone

作者发表你赞成的自己的观点叫言论自由，而我们发表你不赞成的观点叫做“spamming”。

**Comment by clqs803** [comment]
> 

双标狗就是这样子的啦

**Comment by clqs803** [comment]
> > Turn that down, bro, spamming can't hurt anyone
> 
> 作者发表你赞成的自己的观点叫言论自由，而我们发表你不赞成的观点叫做“spamming”。

双标狗就是这样子的啦

**Comment by Addmsfw** [comment]
乐
