### ISSUE TITLE
UDL repository

### ISSUE THREAD

**Issue by KOLANICH** [notepad-plus-plus/notepad-plus-plus#1286]
It is not good to write UDLs into wiki and install them manually.
Could you create a new repo for UDL and add the code into NPP Plugin Manager to manage UDL's

**Comment by dail8859** [comment]
That's actually a pretty good idea. However it would be best to report this to the PluginManager author.

**Comment by Croydon** [comment]
FYI there is an organisation called Notepad++ plugins: https://github.com/npp-plugins

**Comment by KOLANICH** [comment]
@MetaChuh closing issues without a notice is just impolite.

**Comment by MetaChuh** [comment]
@KOLANICH 

my apologies, i thought everything was clear for experienced users.

> Could you create a new repo for UDL and add the code into NPP Plugin Manager to manage UDL's

NPP Plugin Manager is an external plugin which is currently not maintained and not compatible with newer versions of notepad++.

while it theoretically would be possible to implement repo deployment of udls in plugin manager, you would have to file such request at https://github.com/bruderstein/nppPluginManager

many thanks and best regards

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
(no extra account is needed, just use your github account to sign in)
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)

**Comment by KOLANICH** [comment]
>NPP Plugin Manager is an external plugin which is currently not maintained and not compatible with newer versions of notepad++.

NPP has an own plugin manager now. I guess the issue is still valid, if applied to own one.

**Comment by donho** [comment]
> NPP has an own plugin manager now. I guess the issue is still valid, if applied to own one.

Plugins Admin installs only the plugins into the specific folder. Whereas UDLs are installed into another specific folder. So I don't see how we can put UDLs repo into Plugins Admin's one.

**Comment by KOLANICH** [comment]
>So I don't see how we can put UDLs repo into Plugins Admin's one

Its machinery can be parameterized and reused to install UDLs. What is needed to be redesigned:
1 create a tree instead of a list. root -> category name -> module name
2 create an interface for retrieving info about plugins available and 2 classes: one retrieves info about plugins from the dll and another one retreives the info from remote repo.
3 create an interface representing an installer. Has members for a target folder and 4 virtual functions: one validates a package, another one installs it, another one uninstalls it and yet another one checks if installed. 2 classes, one installs plugins, another one installs UDLs.
4 create a class for a plugin category, having members for category name and an installer.

**Comment by donho** [comment]
@KOLANICH 

Plugins Admin is on the stabilizing stage, so I won't modify its behaviour/design.
OTOH, UDL is rather for specific use, it's rarely for the public. So I don't see the advantage to maintain a repository for that.
