### ISSUE TITLE
emmet is not working properly

### ISSUE THREAD

**Issue by henrix343** [notepad-plus-plus/notepad-plus-plus#1287]
http://docs.emmet.io/cheat-sheet/

ul>li.item$*5 should give me 5 li classes in an ul:

<ul>
    <li class="item1"></li>
    <li class="item2"></li>
    <li class="item3"></li>
    <li class="item4"></li>
    <li class="item5"></li>
</ul>

but instead it give me:

display: block;
-webkit-user-select: none;
-moz-user-select: none;
-ms-user-select: none;
user-select: none;
list-style: ;

why it's not working? And how to fix it? win7/64bit, Notepad++ 6.8.8 with latest emmet and python script, also tried with PythonScript_1.0.8.0 - to no avail.

**Comment by dail8859** [comment]
Please report this to the author of the plug in.

**Comment by henrix343** [comment]
moved to - https://github.com/emmetio/npp/issues/13
