### ISSUE TITLE
Errors save

### ISSUE THREAD

**Issue by ghost** [notepad-plus-plus/notepad-plus-plus#1292]
Problem signature:
  Problem Event Name:   BEX
  Application Name: notepad++.exe
  Application Version:  6.8.8.0
  Application Timestamp:    5668c37c
  Fault Module Name:    notepad++.exe
  Fault Module Version: 6.8.8.0
  Fault Module Timestamp:   5668c37c
  Exception Offset: 000de911
  Exception Code:   c0000417
  Exception Data:   00000000
  OS Version:   6.1.7601.2.1.0.256.1
  Locale ID:    1045
  Additional Information 1: 83aa
  Additional Information 2: 83aaec1861dfdbb25c35f1cab3fe317d
  Additional Information 3: f478
  Additional Information 4: f478469fac958d4e588b688c1e4c6c1c

**Comment by dail8859** [comment]
Just providing that information is not enough. How did you cause it to occur? Is it reproducable? Try following [these](https://github.com/notepad-plus-plus/notepad-plus-plus/blob/master/CONTRIBUTING.md#reporting-issues) steps.

**Comment by donho** [comment]
absence of op reply
