### ISSUE TITLE
傻逼作者开发傻逼软件捏🤗🤗🤗Silly software developed by silly authors🤗🤗🤗🤗🤗🤗

### ISSUE THREAD

**Issue by fight-for-cn** [notepad-plus-plus/notepad-plus-plus#12948]
傻逼作者开发的傻逼软件捏
Silly software developed by silly authors
Глупое программное обеспечение, разработанное глупыми авторами
愚かな作者によって開発された愚かなソフトウェア
Des logiciels stupides développés par des auteurs stupides
바보 같은 작성자가 개발한 바보 같은 소프트웨어
Dumme Software, entwickelt von dummen Autoren

**Comment by Jordon10086** [comment]
No discrimination against persons or groups: The license must not discriminate against any person or group of persons

**Comment by Grey-Wind** [comment]
I think it's inappropriate, but the author is really offensive

**Comment by ZZhangC** [comment]
Yes

**Comment by ZengXiaoPi** [comment]
不是很友好啊，但是好骂

**Comment by LeBronZhangbo** [comment]
Since it is open source, I think we can remove its reactionary code.

**Comment by Addmsfw** [comment]
Only things zhina people knows is the xi says,let's take a second of silence for their brains.

**Comment by ki0ding** [comment]
We can create a fork that leverages community power to overturn the original.

**Comment by fight-for-cn** [comment]
> Only things zhina people knows is the xi says,let's take a second of silence for their brains.

攻击力不够，太垃了

**Comment by fight-for-cn** [comment]
> Only things zhina people knows is the xi says,let's take a second of silence for their brains.

白皮的攻击力就只有这么一点点吗🤣🤣🤣

**Comment by fight-for-cn** [comment]
> Only things zhina people knows is the xi says,let's take a second of silence for their brains.

原来不是白皮，又是一个二鬼子🤣👉🤡

**Comment by Addmsfw** [comment]
> > Only things zhina people knows is the xi says,let's take a second of silence for their brains.
> 
> 白皮的攻击力就只有这么一点点吗🤣🤣🤣

正确的，中肯的，建议gitee的

**Comment by Addmsfw** [comment]
开心用有审核的平台自己去用

**Comment by fight-for-cn** [comment]
> > > Only things zhina people knows is the xi says,let's take a second of silence for their brains.
> > 
> > 
> > 白皮的攻击力就只有这么一点点吗🤣🤣🤣
> 
> 正确的，中肯的，建议gitee的

为什么要去gitee?github也没封我啊🤣

**Comment by fight-for-cn** [comment]
> 开心用有审核的平台自己去用

我什么时候用gitee了？🤣🤣🤣

**Comment by Addmsfw** [comment]
什么事都要插手可不是github的风格

**Comment by Addmsfw** [comment]
你要喜欢永远有一个强大的力量

**Comment by fight-for-cn** [comment]
> 什么事都要插手可不是github的风格

确实，但是这个作者插手了🤣

**Comment by Addmsfw** [comment]
能为所有人贯彻同一个观点

**Comment by Addmsfw** [comment]
那悉听尊便

**Comment by fight-for-cn** [comment]
> 你要喜欢永远有一个强大的力量

你语文过小学水平了吗？说话说一半🤣

**Comment by Addmsfw** [comment]
不要一边言论自由

**Comment by Addmsfw** [comment]
一边党同伐异

**Comment by Addmsfw** [comment]
当年光头估计就愁没有这样的民众

**Comment by fight-for-cn** [comment]
触碰了我的底线，我自然是要“伐”的

**Comment by Addmsfw** [comment]
全一起信flg去了

**Comment by fight-for-cn** [comment]
你要是想念光头，大可以去赴死

**Comment by Addmsfw** [comment]
学几门语言去吧

**Comment by Addmsfw** [comment]
别天天把大字报乱贴

**Comment by Addmsfw** [comment]
现在只能证明你是个破烂

**Comment by fight-for-cn** [comment]
现在就只是为了把这个软件搞烂呢

**Comment by fight-for-cn** [comment]
没有其他的目的😋

**Comment by fight-for-cn** [comment]
破烂就破烂吧，把这个软件搞烂了，被骂也不亏😋😋

**Comment by Addmsfw** [comment]
支持捏

**Comment by Addmsfw** [comment]
反正没有开发者真的会用NP工作

**Comment by fight-for-cn** [comment]
确实

**Comment by Addmsfw** [comment]
平滑滚动都不支持

**Comment by Grey-Wind** [comment]
> Only things zhina people knows is the xi says,let's take a second of silence for their brains.

Did all the foreigner just know Xi? 
Or you can't find other ways to attack Chinese.
You look like a mad dog to me.
