### ISSUE TITLE
JSON viewer defaults to first view

### ISSUE THREAD

**Issue by PhilHargHF** [notepad-plus-plus/notepad-plus-plus#12954]
### Description of the Issue

If you have a json file open and move it to another view and then try to format the json the formatter tries to format the active tab in view 1 rather than the currently active tab in view 2

### Steps to Reproduce the Issue

1. open two files, one should contain json text
2. move the json file to another view
3. click on the moved document to ensure it's active
4. From the menu chose: Plugins -> JSON Viewer -> Format JSON

### Expected Behavior

I expected the compressed line of JSON to be formatted

### Actual Behavior

All the text in the file in view 1 is selected and formatted rather than the selected tab in view 2

### Debug Information

Notepad++ v8.4.8   (64-bit)
Build time : Dec 24 2022 - 19:40:27
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : "D:\JETS\Logs\Trace\BookingXML\2023-01-23\427755\Book01\VILLA_547845_BOOK_03a_NPX_VillaDetails_Res.json"
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 11 (64-bit) 
OS Version : 22H2
OS Build : 22621.1105
Current ANSI codepage : 1252
Plugins : 
    JsonTools (4.4)
    mimeTools (2.9)
    NppConverter (4.5)
    NppExport (0.4)
    NPPJSONViewer (2.0.4)
    XMLTools (3.1.1.13)

**Comment by chcg** [comment]
@PhilHargHF From your description this is an issue of the plugin. Please create the ticket at the ticket queue of the plugin: https://github.com/kapilratnani/JSON-Viewer/issues
