### ISSUE TITLE
Problem on utf8 chars

### ISSUE THREAD

**Issue by chalda-pnuzig** [notepad-plus-plus/notepad-plus-plus#1295]
With some fonts the utf8 rapresentation of chars is a crossed rectangle, 
but if you insert in the same line an another utf8 char the rectangle change with the correct render.

![bug-notepad](https://cloud.githubusercontent.com/assets/16133710/12020432/c70b515c-ad7c-11e5-92b3-5d579d038c40.png)

How to reproduce:
- set font to "Source code pro"
- write a hearth ♥ 
- write a snowman on the same line ☃

**Comment by kirhgoph** [comment]
![image](https://cloud.githubusercontent.com/assets/6734564/12025005/35aaf0f2-adbb-11e5-8cae-9c8986800c12.png)
<li>Set font to "Source code pro" (here is a link to it: http://www.fontsquirrel.com/fonts/source-code-pro )
<li>wrote set of symbols (see screenshot attached)
<li> everything works as expected.
Notepad++ ver. 6.8.8

**Comment by chalda-pnuzig** [comment]
Ok, 
the problem was an old version of that font :)
Thanks :)
