### ISSUE TITLE
We need a clean community

### ISSUE THREAD

**Issue by poplangfan** [notepad-plus-plus/notepad-plus-plus#12952]
It is a pity that you have violated the spirit of open source, which is the foundation and core of open source software. Many users use your software not because you are excellent and irreplaceable, but because they don't understand your words, deeds and behavior. In fact, there are a large number of other open source software on the market that can be replaced, and you will personally destroy your work.

**Comment by lings-aa** [comment]
How dare you!
I don't think it's a joke. Any poisoning for political reasons will trample on the spirit of the open source community. Thecommunity needs to come forward to clarify and make promises to users of the software. Any adult should know thatinappropriate jokes aren't supposed to be made, even on April Fools' Day, and they can happen.

**Comment by Addmsfw** [comment]
靠捂嘴来解决纠纷，只是在学习中共的行径。
