### ISSUE TITLE
Generate MD5 from file causes Non-Responsive behaviour

### ISSUE THREAD

**Issue by PaulKonen** [notepad-plus-plus/notepad-plus-plus#12953]
### Steps to Reproduce the Issue

1. Tools > MD5 > Generate from files > Choose files to generate MD5...
2. File selector dialog pops up and cursor just spins
3. 

### Expected Behavior

Expected the dialog to present files to select

### Actual Behavior
The dialog box pops up and the cursor just spins

### Debug Information

Notepad++ v8.4.8   (64-bit)
Build time : Dec 24 2022 - 19:40:27
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 11 (64-bit) 
OS Version : 22H2
OS Build : 22621.1105
Current ANSI codepage : 1252
Plugins : 
    HexEditor (0.9.12)
    mimeTools (2.9)
    NppConverter (4.5)
    NppExport (0.4)

**Comment by alankilborn** [comment]
The feature works fine end-to-end for me in:

Notepad++ v8.4.8 (64-bit)
Build time : Dec 24 2022 - 19:40:27

Perhaps for you it has something to do with the folder that it is intending to show?

**Comment by PaulKonen** [comment]
Thanks.  All it shows is the base box.
Tried is again and it was fine this time.

Ok to close issue.

**Comment by alankilborn** [comment]
>Ok to close issue.

As the petitioner, you should be the one to close.
