### ISSUE TITLE
I just want to ask, if there is an armed conflict between China and Taiwan, is that still a joke?

### ISSUE THREAD

**Issue by lings-aa** [notepad-plus-plus/notepad-plus-plus#12955]
I just want to ask, if there is an armed conflict between China and Taiwan, is that still a joke?

**Comment by Ricky-fight** [comment]
You signed up this issue just to ask this quetion which is unrelated to this repo?

**Comment by lings-aa** [comment]
> 

If you think the security of software has nothing to do with me being threatened by the author, then yes.

**Comment by lings-aa** [comment]
> 你注册这个问题只是为了问这个与这个 repo 无关的问题？

If you think the security of software has nothing to do with me being threatened by the author, then yes.

**Comment by Ricky-fight** [comment]
That's useless. Npp is not irreplaceable. And this software is not made by himself. Mad cannot hurt anyone, neither let him go out of the project.

**Comment by asivwolf** [comment]
can Open source software  kid users?

**Comment by lings-aa** [comment]
> That's useless. Npp is not irreplaceable. And this software is not made by himself. Mad cannot hurt anyone, neither let him go out of the project.

It's fine that the account is his personal account, but unfortunately, I don't understand his interest in using the official account to send such remarks.

**Comment by lings-aa** [comment]
> can Open source software kid users?

Vue-cli, node-ipc are poisoned
