### ISSUE TITLE
Show all characters does not quite

### ISSUE THREAD

**Issue by tomvines** [notepad-plus-plus/notepad-plus-plus#12950]
### Description of the Issue
Zero length spaces are not displayed

### Steps to Reproduce the Issue

1. Create an html page with the following `<html><head></head><body>Hi the&ZeroWidthSpace;re</body></html>` 
2. View the page
3. Copy the text into Notepad ++
4. Enable view all characters 
5. Note that the zero length space is not displayed however can be detected as you use the cursor keys to move the caret over "there"

### Expected Behavior
A character of some sort to indicate that there is a space present in there

### Actual Behavior
No character is displayed

Other than that your program rocks!

**Comment by alankilborn** [comment]
Duplicate.
Master issue for this is #8284.
You can add any relevant new comments in that issue.
Please close this issue.
