### ISSUE TITLE
![image](https://user-images.githubusercontent.com/123729649/215249925-06f03af2-51c9-4103-87e6-d064222ee0b1.png)

### ISSUE THREAD

**Issue by Clancy6** [notepad-plus-plus/notepad-plus-plus#12966]
![image](https://user-images.githubusercontent.com/123729649/215249925-06f03af2-51c9-4103-87e6-d064222ee0b1.png)

主人都已经认错了，却总是有狗在这边护主，一群小丑🤣👉🤡

_Originally posted by @fight-for-cn in https://github.com/notepad-plus-plus/notepad-plus-plus/issues/12961#issuecomment-1407305376_
          
No Discrimination Against Persons or Groups !

**Comment by fight-for-cn** [comment]
兄弟，是友军φ(*￣0￣)
