### ISSUE TITLE
一个个张口闭口“虽远必诛”，这么好战呢？

### ISSUE THREAD

**Issue by Clancy6** [notepad-plus-plus/notepad-plus-plus#12962]
No Discrimination Against Persons or Groups !

**Comment by sider2vf** [comment]
![image](https://user-images.githubusercontent.com/116246824/215250009-417993d9-1a38-47f7-a3ac-c1eaa7b1dd10.png)

**Comment by OrochiZ** [comment]
傻狗还开新帖.
