### ISSUE TITLE
“人权”“自由”

### ISSUE THREAD

**Issue by Clancy6** [notepad-plus-plus/notepad-plus-plus#12974]
唐山打人，刀战房和枪战房有区别？

_Originally posted by @sider2vf in https://github.com/notepad-plus-plus/notepad-plus-plus/issues/12971#issuecomment-1407310369_
            
No Discrimination Against Persons or Groups !

**Comment by OrochiZ** [comment]
党你妈了个逼,呕吐

**Comment by tmdakm** [comment]
我的评价是：您要是不喜欢辱华为什么还要在辱华垃圾堆里到处发布抽象言论捏 小粉红火速去学习党史了解党的文化 然后去把总加速师习近平独裁国贼给刺了捏

党在全力清除黑恶势力 那么为什么网上有那么多黑恶势力捏 党跟不上时代的进不了？笑嘻了
