### ISSUE TITLE
NP++ v6.8.6 not reading pipe delimited text file produced by SSIS 2008 R2

### ISSUE THREAD

**Issue by gcodellc** [notepad-plus-plus/notepad-plus-plus#1297]
The address; 
|250 Mercer St. 
C616| within my text file created by SSIS 2008R2 (flat file manager) is showing in Notepad++ v6.8.6 as two separate lines instead of one line. It seems like NP++ is disregarding the pipe as a column delimiter over the possibility that there is a new line inadvertently being put in to the file. It does seem like a SSIS bug and I would have kept this view point if I had not opened this same file in Microsoft Notepad and found that this record was read as intended. (see attached file).
[wr_account_pipe.txt](https://github.com/notepad-plus-plus/notepad-plus-plus/files/74046/wr_account_pipe.txt)

**Comment by dail8859** [comment]
> NP++ is disregarding the pipe as a column delimiter

Notepad++ doesn't try to separate things into columns, it just displays the file as-is, character by character. In your case there are line feed characters in some of the fields. The reason Microsoft Notepad *seems* to display it correctly is that it is not made to handle Unix line endings (i.e. line feeds) so it ignores them.
