### ISSUE TITLE
Please delete the China-related issues to make the issue area clean

### ISSUE THREAD

**Issue by sider2vf** [notepad-plus-plus/notepad-plus-plus#12970]
### List of issues that may be China-related （精彩节目大赏，定期更新）:
_Maybe some issues have been deleted by GitHub_

#12969 
#12968 
#12967 
#12966 
#12965 
#12964 
#12963 
#12962 
#12961 
#12960 
#12959 
#12957 
#12948 
#12947 
#12862 
#12971 
#12972 
#12973 
#12974 
#12975 

### TO 战螂/小粉红：别看你今天闹得欢，小心啊今后拉清单；攻击一个将软件免费给你们用并开源代码给你们的人，你们也好意思？996人矿的命，操中南海的心，自我审查做的很不错😘。每一个人都有发表自己政治观点的权利，只有某些人才会认为不符合所谓的“政治正确”就是对他的一种侮辱，内心狭隘可笑

![image](https://user-images.githubusercontent.com/116246824/215249136-b59a4944-1fda-4cb1-a2a3-97e42f794b53.png)

**Comment by Clancy6** [comment]
我非常厌恶GitHub里面出现的反华辱华言论，况且在https://github.com/notepad-plus-plus/notepad-plus-plus/issues/12961 里面已重申，请不要把个人的带有歧视色彩的言论带到GitHub上

**Comment by sider2vf** [comment]
辱华只是你们自己全身敏感点，如果喜欢内循环、喜欢可怕的民族主义、喜欢思想控制和言论审查，你可以回到 Gitee 上捏

**Comment by fight-for-cn** [comment]
无所谓，拉黑了再创账号就可以了😋反正都是小号😋

**Comment by Clancy6** [comment]
你怎么看我不在乎，但是请不要发出来好吗？空口无凭！

**Comment by OrochiZ** [comment]
> 我非常厌恶GitHub里面出现的反华辱华言论，况且在#12961 里面已重申，请不要把个人的带有歧视色彩的言论带到GitHub上

那你只能离开这个世界了,早死

**Comment by fight-for-cn** [comment]
> > 我非常厌恶GitHub里面出现的反华辱华言论，况且在#12961 里面已重申，请不要把个人的带有歧视色彩的言论带到GitHub上
> 
> 那你只能离开这个世界了,早死

好怕怕哦

**Comment by sider2vf** [comment]
> 你怎么看我不在乎，但是请不要发出来好吗？空口无凭！

我凭什么要惯着你？我不是你父母，喜欢禁评和皇帝就会内循环

**Comment by OrochiZ** [comment]
我已经举报他了

**Comment by sider2vf** [comment]
另外问一下各位，你们干这个发评论的工作赚钱多不多，我听说一条五毛呢，还可以减刑，是真的吗？

**Comment by Clancy6** [comment]
> 另外问一下各位，你们干这个发评论的工作赚钱多不多，我听说一条五毛呢，还可以减刑，是真的吗？

刚才火葬场给你爹我打电话说你妈尸骨烧粘锅了你他妈还跟你爹我在这逼逼赖赖？

**Comment by Clancy6** [comment]
> 我已经举报他了

举报举报，你咋不举报我在你婊子妈的烂逼里自由的翱翔完成高难度动作first blood double kill triple kill Quadra kill penta kill成为本场日你血妈最佳MVP

**Comment by Clancy6** [comment]
> > 我非常厌恶GitHub里面出现的反华辱华言论，况且在#12961 里面已重申，请不要把个人的带有歧视色彩的言论带到GitHub上
> 
> 那你只能离开这个世界了,早死

小废物你好，野爹我一道毁灭光线把你婊子妈乳房连同你家祖宗八代的祖坟射上天空变为绚烂烟火洒下万点光芒，还他妈UFO呢真他妈喜庆

**Comment by Clancy6** [comment]
> > > 我非常厌恶GitHub里面出现的反华辱华言论，况且在#12961 里面已重申，请不要把个人的带有歧视色彩的言论带到GitHub上
> > 
> > 
> > 那你只能离开这个世界了,早死
> 
> 好怕怕哦

哇，你这人真神奇，跟个傻逼似的。你妈头七都过了都不知道去看看。跟你说哦 ，你祖宗坟前那个草啊，被老王割去喂牛了，这牛吃了啊，当场爆炸。把你家祖坟给炸没了，村里头人人都叫好哇。

**Comment by Clancy6** [comment]
> 无所谓，拉黑了再创账号就可以了😋反正都是小号😋

你妈的黑曜石逼无坚不摧，无数嫖客的健壮鸡巴都无法捅爆你妈处女膜只好我亲自出马

**Comment by Clancy6** [comment]
> 辱华只是你们自己全身敏感点，如果喜欢内循环、喜欢可怕的民族主义、喜欢思想控制和言论审查，你可以回到 Gitee 上捏

GitHub是你家开的？你想骂就骂？我看全世界都欠你爸你妈一个避孕套

**Comment by sider2vf** [comment]
通过扣字取得的精神胜利不还是更丢人，中国粉红脑回路清奇哦

**Comment by Clancy6** [comment]
> ### List of issues that may be China-related （精彩节目大赏，定期更新）:
> #12969 #12968 #12967 #12966 #12965 #12964 #12963 #12962 #12961 #12960 #12959 #12957 #12948 #12947 #12862 #12971 #12972 #12973 #12974
> 
> ### TO 战螂/小粉红：别看你今天闹得欢，小心啊今后拉清单；攻击一个将软件免费给你们用并开源代码给你们的人，你们也好意思？996人矿的命，操中南海的心，自我审查做的很不错

一看这傻逼无脑脑残巨人痴就让人窝火 你婊子妈被爸爸一拳打到火星再打回来顿时你婊子妈血泪横流哭爹喊娘求爸爸饶他一命可惜你野爹我还是把你这傻狗儿子鸡巴狠狠撕下揉成一团强行塞进你婊子妈下体

**Comment by sider2vf** [comment]
好像有个今早骂的特别欢的被删号了欸，开香槟

**Comment by OrochiZ** [comment]
那个Clancy6死了

**Comment by MinGGeMG-sourcecode** [comment]
![无标题](https://user-images.githubusercontent.com/49353343/215259105-21226ec9-e136-458d-8a09-97858e4d8131.png)

**Comment by sider2vf** [comment]
又有人被ban了，好耶

**Comment by SmallKi-d** [comment]
关于 自由 开源 软件 也受到了政治侵害
别开我，我就B站刷到视频来蹭热闹的

**Comment by Cyrillya** [comment]
感觉不如 #12854
