### ISSUE TITLE
ffmpeg console output in notepad++  search results

### ISSUE THREAD

**Issue by jimlynnjulian** [notepad-plus-plus/notepad-plus-plus#12978]
### Description of the Issue
I was running mkvinfo from the mkvtoolnix suite to gather tag data for some matroska files. The output for each file was placed in a separate file, e.g. _1.txt, 2.txt, and so on. I opened these files to examine the results. During the examination, I ran a global search of all opened documents, the the word 'Name'. The results for the mkvinfo output for one matroska file included ffmpeg console output.

### Steps to Reproduce the Issue
Add one mkv file of questionable metadata integrity
Add mkvinfo
Run ""mkvinfo "file.mkv" > _file.txt"".
Open in notepad++ with several similar files and run a search on all opened documents.
Examine results.

What follows is an excerpt of the search results that include the error:

<code>
  H:\4K UHD\_Hidden.txt (29 hits)
	Line  49: |  + Name: Commentary with Director and writer Theodore Melfi & star Taraji P. Henson
	Line  60: |  + Name: English (SRT)
	Line  68: |  + Name: English SDH (SRT)
	Line  76: |  + Name: English SDH (SUP)
	Line  85: |  + Name: Spanish (SUP)
	Line  94: |  + Name: Spanish (SUP)
	Line 103: |  + Name: French (SUP)
	Line 112: |  + Name: Danish (SUP)
	Line 121: |  + Name: Dutch (SUP)
	Line 130: |  + Name: Finnish (SUP)
	Line 139: |  + Name: German (SUP)
	Line 148: |  + Name: Italian (SUP)
	Line 157: |  + Name: Japanese (SUP)
	Line 166: |  + Name: Norwegian (SUP)
	Line 175: |  + Name: Swedish (SUP)
	Line 184: |  + Name: Chinese (SUP)
	Line 193: |  + Name: Chinese (SUP)
	Line 201: |  + Name: English Commentary (SUP)
	Line 210: |  + Name: Spanish Commentary (SUP)
	Line 219: |  + Name: Spanish Commentary (SUP)
	Line 228: |  + Name: French Commentary (SUP)
	Line 237: |  + Name: Danish Commentary (SUP)
	Line 246: |  + Name: Dutch Commentary (SUP)
	Line 255: |  + Name: Finnish Commentary (SUP)
	Line 264: |  + Name: German Commentary (SUP)
	Line 273: |  + Name: Italian Commentary (SUP)
	Line 282: |  + Name: Japanese Commentary (SUP)
	Line 291: |  + Name: Norwegian Commentary (SUP)
	Line 300: |  + Name: Swedish Commentary (SUP)
  H:\4K UHD\_Jurassic.txt (4 hits)
	Line  40: |  + Name: DTS-X 7.1
	Line  52: |  + Name: Stripped SRT (not positioned)
	Line  60: |  + Name: SDH SRT (not positioned)
	Line  68: |  + Name: SDH
  H:\4K UHD\_Matrix.txt (9 hits)
	Line  39: |  + Name: Atmos 7.1
	Line  50: |  + Name: AC-3 5.1
	Line  61: |  + Name: Philosopher Commentary by Dr. Cornel West and Ken Wilber
	Line  72: |  + Name: Critics Commentary by Todd McCarthy John Powers and David Thomson
	Line  83: |  + Name: Cast and Crew Commentary by Carrie-Anne Moss, Zach Staenberg and John Gaeta
	Line  94: |  + Name: Composer Commentary by Don Davis
	Line 105: |  + Name: Stripped SRT
	Line 113: |  + Name: SDH SRT
	Line 121: |  + Name: SDH
  H:\4K UHD\_Matrix2.txt (1 hit)
	Line  28: |  + Name: @NAHOM
  new 2 (89 hits)
	Line   8: Search "Name" (86 hits in 12 files of 19 searched)
	Line  10: 	Line 46: -map "1:0" "-metadata:s:s:0" "language=heb" "-metadata:s:s:0" "handler_name=Hebrew" "-metadata:s:s:0" "title=Hebrew"
	Line  11: 	Line 47: -map "2:0" "-metadata:s:s:1" "language=eng" "-metadata:s:s:1" "handler_name=English" "-metadata:s:s:1" "title=English"
	Line  13: 	Line 28:       handler_name    : Ambarella EXT
	Line  15: 	Line  5: # for i in $(find . -name *.mkv); do echo $i -i "$i" -codec copy "${i%}.mp4"; done
	Line  16: 	Line  6: # find . -name "*.mp4" -exec bash -c 'for f; do echo $i -i "$f" -codec copy "${f%.*}.mkv"; done' -- {} +
	Line  17: 	Line  8: # find . -name "*.mkv" -exec bash -c 'for f; do ffmpeg $i -i "$f" -codec copy "${f%.*}.mp4"; rm "${f%.*}.mp4" ; done' -- {} +
	Line  18: 	Line 13: # find . -name "*.mkv" -exec bash -c 'for f; do ffmpeg $i -i "$f" -map 0 -c copy "${f%.*}.mp4"; rm "${f%.*}.mkv" ; done' -- {} +
	Line  19: 	Line 21: find . -name "*.mp4" -exec bash -c 'for f; do ffmpeg $i -i "$f" -c copy "${f%.*}.mkv" ; rm "${f%.*}.mp4" ; done' -- {} +
	Line  20: 	Line 33: # Add srt subtitle into mkv video with FFMPEG- put all of your mkv and srt files with same names in a folder and run bash command. All of the converted files will be in the added folder inside the current folder.
	Line  22: 	Line  40: find . -type f -name "*.mp4" -exec bash -c 'FILE="$1"; ffmpeg -i "${FILE}" -vf scale=1280:-1 -acodec copy -y "${FILE%.mp4}.shrink.mp4";' _ '{}' \;
	Line  23: 	Line  56:      $f.fullname
	Line  24: 	Line  57:      & C:\Utils\FFmpeg\bin\ffmpeg.exe -y -i "$($f.Fullname)"  -b:a 128k "$($f.Directory)\$($f.baseName).mp3"
	Line  25: 	Line  78: - {/}    basename  [1/4]                                                                      
	Line  26: 	Line  81: - {/.}   basename without file extension
	Line  27: 	Line 100: find . -type f -name '*.mp4' -exec sh -c '
	Line  28: 	Line 101:     name="${1%.*}"
	Line  29: 	Line 102:     echo "$name"
	Line  30: 	Line 103:     ffmpeg -i "$1" -r 0.0033 -vf scale=-1:1024 -vcodec png "${name}.png"
	Line  31: 	Line 107: In your original code name=`echo "$i" | cut -d'.' -f1` is rather low quality fragment. It cuts at the first dot, this seems wrong. It's not the only problem but I won't elaborate. If you want to remove an extension, the right way is name="${i%.*}".
	Line  32: 	Line 118: for i in $(find . -name *.mkv); do ffmpeg -i "$i" -codec copy "${i%}.mp4"; done
	Line  33: 	Line 130: Two errors there. You forgot quotes around the pattern to -name, and that loop doesn't handle filenames properly. Use either -exec or -print0
	Line  34: 	Line 133: find . -name "*.mkv" -exec bash -c 'for f; do ffmpeg -i "$f" -codec copy "${f%.*}.mp4"; done' -- {} +
	Line  35: 	Line 137: find . -name "*.mkv" -print0 | while IFS= read -rd '' f; do
	Line  36: 	Line 152: for video in $(find . -name *.mp4); do ffmpeg -i "$video" -acodec aac -ac 2 "${video%.*}".mkv; rm "$video"; done
	Line  38: 	Line 53: |   +	Name: MAJOR_BRAND
	Line  39: 	Line 56: |   +	Name: MINOR_VERSION
	Line  40: 	Line 59: |   +	Name: COMPATIBLE_BRANDS
	Line  41: 	Line 62: |   +	Name: ENCODER
	Line  42: 	Line 68: |   +	Name: HANDLER_NAME
	Line  43: 	Line 74: |   +	Name: DURATION
	Line  44: 	Line 80: |   +	Name: DURATION
	Line  46: 	Line  51: |  + Name: Stripped SRT
	Line  47: 	Line  59: |  + Name: SDH SRT
	Line  48: 	Line  67: |  + Name: SDH
	Line  50: 	Line 54: |  + Name: Commentary with director Ridley Scott
	Line  51: 	Line 67: |  + Name: Commentary with writer/executive producer Hampton Fancher; writer David Peoples; producer Michael Deeley; and production executive Katherine Haber
	Line  52: 	Line 80: |  + Name: Commentary with visual futurist Syd Mead; visual effects supervisors Douglas Trumbull, David Dryer, and Richard Yuricich; art director David Snyder; and production designer Lawrence G. Paull
	Line  54: 	Line  29: |  + Name: Grease (1978) 2160p Multi
	Line  55: 	Line  41: |  + Name: English audio track
	Line  57: 	Line  49: |  + Name: Commentary with Director and writer Theodore Melfi & star Taraji P. Henson
	Line  58: 	Line  60: |  + Name: English (SRT)
	Line  59: 	Line  68: |  + Name: English SDH (SRT)
	Line  60: 	Line  76: |  + Name: English SDH (SUP)
	Line  61: 	Line  85: |  + Name: Spanish (SUP)
	Line  62: 	Line  94: |  + Name: Spanish (SUP)
	Line  63: 	Line 103: |  + Name: French (SUP)
	Line  64: 	Line 112: |  + Name: Danish (SUP)
	Line  65: 	Line 121: |  + Name: Dutch (SUP)
	Line  66: 	Line 130: |  + Name: Finnish (SUP)
	Line  67: 	Line 139: |  + Name: German (SUP)
	Line  68: 	Line 148: |  + Name: Italian (SUP)
	Line  69: 	Line 157: |  + Name: Japanese (SUP)
	Line  70: 	Line 166: |  + Name: Norwegian (SUP)
	Line  71: 	Line 175: |  + Name: Swedish (SUP)
	Line  72: 	Line 184: |  + Name: Chinese (SUP)
	Line  73: 	Line 193: |  + Name: Chinese (SUP)
	Line  74: 	Line 201: |  + Name: English Commentary (SUP)
	Line  75: 	Line 210: |  + Name: Spanish Commentary (SUP)
	Line  76: 	Line 219: |  + Name: Spanish Commentary (SUP)
	Line  77: 	Line 228: |  + Name: French Commentary (SUP)
	Line  78: 	Line 237: |  + Name: Danish Commentary (SUP)
	Line  79: 	Line 246: |  + Name: Dutch Commentary (SUP)
	Line  80: 	Line 255: |  + Name: Finnish Commentary (SUP)
	Line  81: 	Line 264: |  + Name: German Commentary (SUP)
	Line  82: 	Line 273: |  + Name: Italian Commentary (SUP)
	Line  83: 	Line 282: |  + Name: Japanese Commentary (SUP)
	Line  84: 	Line 291: |  + Name: Norwegian Commentary (SUP)
	Line  85: 	Line 300: |  + Name: Swedish Commentary (SUP)
	Line  87: 	Line  40: |  + Name: DTS-X 7.1
	Line  88: 	Line  52: |  + Name: Stripped SRT (not positioned)
	Line  89: 	Line  60: |  + Name: SDH SRT (not positioned)
	Line  90: 	Line  68: |  + Name: SDH
	Line  92: 	Line  39: |  + Name: Atmos 7.1
	Line  93: 	Line  50: |  + Name: AC-3 5.1
	Line  94: 	Line  61: |  + Name: Philosopher Commentary by Dr. Cornel West and Ken Wilber
	Line  95: 	Line  72: |  + Name: Critics Commentary by Todd McCarthy John Powers and David Thomson
	Line  96: 	Line  83: |  + Name: Cast and Crew Commentary by Carrie-Anne Moss, Zach Staenberg and John Gaeta
	Line  97: 	Line  94: |  + Name: Composer Commentary by Don Davis
	Line  98: 	Line 105: |  + Name: Stripped SRT
	Line  99: 	Line 113: |  + Name: SDH SRT
	Line 100: 	Line 121: |  + Name: SDH
	Line 102: 	Line  28: |  + Name: @NAHOM
	Line 107: Search "name" (0 hits in 0 files of 1 searched)
	Line 108: Search "Name" (0 hits in 0 files of 1 searched)
</code>

The errors do not occur in the mkvinfo.exe output
Extra spaces and tabs were added by me for clarification.
Hope this helps.

**Comment by alankilborn** [comment]
Ummm, I think you're going to have to be more specific about what the Notepad++ error is...
I mean, well, to me it looks like you've copied some search results to a tab and then when you do a _Find All in All Open Documents_ you get `Line xx.....Line yy...` type hits, but that's a reasonable thing.
Really, if you suspect a problem with Notepad++ processing, you're supposed to work it down a bit into a smallish example, not dump a big bunch of output and say "here ya go!"

**Comment by jimlynnjulian** [comment]
I'm closing this as not reproducable.
Copy the text to notepad++, or similar, and search for "ffmpeg."  Examine the following twenty, or so, lines. Or just keep searching for "ffmpeg."
The line sequence is not continuous.
I have tried to reproduce the error but cnnot, hence the closure.

**Comment by jimlynnjulian** [comment]
Not  reproducable.
