### ISSUE TITLE
辱华只是你们自己全身敏感点，如果喜欢内循环、喜欢可怕的民族主义、喜欢思想控制和言论审查，你可以回到 Gitee 上捏

### ISSUE THREAD

**Issue by fight-for-cn** [notepad-plus-plus/notepad-plus-plus#12971]
辱华只是你们自己全身敏感点，如果喜欢内循环、喜欢可怕的民族主义、喜欢思想控制和言论审查，你可以回到 Gitee 上捏

_Originally posted by @sider2vf in https://github.com/notepad-plus-plus/notepad-plus-plus/issues/12970#issuecomment-1407309224_
            

🐸🐸是这样的

**Comment by Clancy6** [comment]
暗网、洋葱路由、泛滥的枪支武器、频发的暴力事件、儿童色情和病毒实验室，这就是你所谓的“完全自由”“保障人权”“无监管”“无审查”？

**Comment by sider2vf** [comment]
唐山打人，刀战房和枪战房有区别？

**Comment by OrochiZ** [comment]
> 唐山打人，刀战房和枪战房有区别？

你有必要和狗辩论吗?

**Comment by OrochiZ** [comment]
> 暗网、洋葱路由、泛滥的枪支武器、频发的暴力事件、儿童色情和病毒实验室，这就是你所谓的“完全自由”“保障人权”“无监管”“无审查”？

人家不用翻墙气死你

**Comment by Karmylr** [comment]
中共和notepad++都不是好东西

**Comment by OrochiZ** [comment]
> 中共和notepad++都不是好东西

成年人还说好坏?
我只知道n++对我有利就行了

**Comment by ro0ki4** [comment]
> 

🤣抛开前面一句，后面那句没十年脑瘫说不出来

**Comment by ro0ki4** [comment]
> > 唐山打人，刀战房和枪战房有区别？
> 
> 你有必要和狗辩论吗?



> 唐山打人，刀战房和枪战房有区别？

抛开前面一句，后面那句话没十年脑瘫说不出来🤣

**Comment by sprybee** [comment]
有政治倾向无所谓，给源码下毒真是日尼玛。

**Comment by sider2vf** [comment]
你好，作者并没有给源码下毒

**Comment by sprybee** [comment]
> 你好，作者并没有给源码下毒

对不起，国内辣鸡营销号，忘记求证了。

**Comment by 0ingchun** [comment]
--捏

**Comment by Marce1ek** [comment]
有些人是真奇怪 可能自己都不在用这款软件 看个视频就能高潮了😅
