### ISSUE TITLE
Open source software should be apolitical

### ISSUE THREAD

**Issue by z2z63** [notepad-plus-plus/notepad-plus-plus#12976]
Your point of view is destructive and hurts the interests of everyone in mainland China but I don't want to argue with you about the right or wrong .  What I only knows is that **open source software should be apolitical. Forcing users to agree with your political views has already deviated from the original intention of the open source spirit**

**Comment by fengshuo2004** [comment]
> Your point of view is destructive and hurts the interests of everyone in mainland China but I don't want to argue with you about the right or wrong . What I only knows is that **open source software should be apolitical. Forcing users to agree with your political views has already deviated from the original intention of the open source spirit**

Agreed. In addition, it's okay if people don't care about Chinese politics and are reluctant side with anyone; However if you are reading this, please remember, _**if the author could target the group of China mainland users like this, there's no guarantee that he won't do the same to you**_. I'd suggest everyone, Chinese or not, to _**remove NotePad++ from their PC and use other alternatives**_.
