### ISSUE TITLE
作者你妈死得好惨啊，什么伞兵作者，生仔冇屎窿

### ISSUE THREAD

**Issue by dkjnsdvsodvnosdvm** [notepad-plus-plus/notepad-plus-plus#12975]
不同意反华条款就私自篡改用户文件？恶心人啊

**Comment by OrochiZ** [comment]
不同意为什么还要用?真贱

**Comment by dkjnsdvsodvnosdvm** [comment]
OSI 对开源的定义有：No Discrimination Against Persons or Groups
：开放源代码软件不得因性别、团体、国家、族群等设置限制，但若是因为法律规定的情形则为例外（如：美国政府限制高加密软件的出口）。
打着开源的口号，来掺杂政治。不同意就篡改文件？开个屁源，干脆别开源

**Comment by OrochiZ** [comment]
> OSI

OSI有什么资格规定开源,笑死

**Comment by dkjnsdvsodvnosdvm** [comment]
抛开“乳滑”不谈，你作为一个开发者，你难道不知道“加入随机字符串”会给源代码文件造成什么样的影响吗？你有为用户的数据安全考虑吗？
这叫开源？
还有，别一

**Comment by dkjnsdvsodvnosdvm** [comment]
哦对了，虽然粉红恶心，但是你们罕见和粉红都是凉拖答辩而已🤣

**Comment by OrochiZ** [comment]
> 抛开“乳滑”不谈，你作为一个开发者，你难道不知道“加入随机字符串”会给源代码文件造成什么样的影响吗？你有为用户的数据安全考虑吗？ 这叫开源？

你不同意协议,自然就不用了,怎么还会有影响呢?

**Comment by OrochiZ** [comment]
> 哦对了，虽然粉红恶心，但是你们罕见和粉红都是凉拖答辩而已🤣

这轮不到以为OSI可以定义开源的智力残疾者说

**Comment by dkjnsdvsodvnosdvm** [comment]
哇，这就是开源😱强行把用户拉到你们的政治上，不同意就私自篡改用户文件。这就是蛙蛙人的自豪么？🤣

**Comment by OrochiZ** [comment]
> 哇，这就是开源😱强行把用户拉到你们的政治上，不同意就私自篡改用户文件。这就是蛙蛙人的自豪么？🤣

笑死,有谁强行让你同意协议了?真是会造谣污蔑.

**Comment by tonyqus** [comment]
哪里改用户文件了？有实锤证据吗？或者你把commit id贴出来呗，npp作者口嗨而已，别被国内帖子带风向，嫌韭菜做的不够？作者都说了这是个玩笑，所以你开不起玩笑吗？

有空多写写代码，别让洋人老说大陆人只会骂人，写不出好软件。

**Comment by dkjnsdvsodvnosdvm** [comment]
那你就别开源啊，非要同意你所谓反华条款，不同意就篡改？🤣

**Comment by mczph** [comment]
use this https://github.com/cxasm/notepad--

**Comment by dkjnsdvsodvnosdvm** [comment]
也不是不行，我也只是讨厌这种“必须同意反华条款，不同意就篡改文件”的行为而已，我才不管他什么zz立场😑。

**Comment by tonyqus** [comment]
notepad-- 我是不敢用的，打嘴炮谁不会，等这事件过去了，这个所谓的作者还愿不愿意维护是个大问号，要知道这是完全公益的项目，没有收益的，爱国热情够不够用？这是个需要由时间来验证的问题。

我看他已经两个月没维护新功能了，除了更新readme。希望他会继续推出有别于npp的新功能。
![image](https://user-images.githubusercontent.com/772561/215304343-08363c59-72f4-4c24-93d5-6776c814c318.png)

**Comment by OrochiZ** [comment]
> 换其他的也不是不行，我也只是讨厌“必须同意反华条款，不同意就篡改文件”这种传播恶心思想的行为而已。我才不管他什么zz立场expressionless

你要知道,不反华才是恶心思想

**Comment by OrochiZ** [comment]
> 那你就别开源啊，非要同意你所谓反华条款，不同意就篡改？rofl

好笑了,用任何软件都需要同意条款,不同意就别用

**Comment by dkjnsdvsodvnosdvm** [comment]
> > 换其他的也不是不行，我也只是讨厌“必须同意反华条款，不同意就篡改文件”这种传播恶心思想的行为而已。我才不管他什么zz立场expressionless
> 
> 你要知道,在这个地球上 不反华 才是恶心思想 请你停止传播这种恶心思想

原来乳滑是对的，那我攻击你全家似，骂你生仔冇屎窿,也是对的捏🤣
恶心人还不能让人吐槽？😱那没人逼你回复我啊

**Comment by dkjnsdvsodvnosdvm** [comment]
打着”free speech“，又阻止别人发表言论，别双标好么。要不你还是锁定话题，一了百了，反正我们也聊不来。

**Comment by dkjnsdvsodvnosdvm** [comment]
打着”言论自由“，又阻止别人发表言论，别双标好么。要不你还是锁定话题，一了百了，反正我们也聊不来。

**Comment by dkjnsdvsodvnosdvm** [comment]
打着”言论自由“，又阻止别人发表言论，别双标好么。要不你还是锁定话题，一了百了，反正我们也聊不来。

**Comment by dkjnsdvsodvnosdvm** [comment]
> notepad-- 我是不敢用的，打嘴炮谁不会，等这事件过去了，这个所谓的作者还愿不愿意维护是个大问号，要知道这是完全公益的项目，没有收益的，爱国热情够不够用？这是个需要由时间来验证的问题。
> 
> 我看他已经两个月没维护新功能了，除了更新readme。希望他会继续推出有别于npp的新功能。 ![image](https://user-images.githubusercontent.com/772561/215304343-08363c59-72f4-4c24-93d5-6776c814c318.png)
> 
> 这事情不是没有先例，看看这个黄掉的[Ournotepad项目](https://github.com/Mapoet/OurNotepad)你就知道所谓的爱国热情有多少分量，之前这哥们还在知乎各种骂，说notepad谁不会写，结果什么都没有发生，就是蹭热度。
> 
> 我不想通过骂人来挑起进一步的战争，我想表达的是 既然是程序员就用程序员的方式来决斗——show me the code

人家在基本在gitee更新，又不是不更新😑
![2345截图20230129201341](https://user-images.githubusercontent.com/102846666/215325439-3ce849f7-6fc3-4be5-82a4-e5c0b8aa421d.png)

**Comment by OrochiZ** [comment]
> 打着”言论自由“，又阻止别人发表言论，别双标好么。要不你还是锁定对话，一了百了，反正我们也聊不来。

言论自由是在属于你自己的地方有自由,不是在别人的地方,毫无常识还乱叫

**Comment by tonyqus** [comment]
> 打着”言论自由“，又阻止别人发表言论，别双标好么。要不你还是锁定对话，一了百了，反正我们也聊不来。

在Github言论是很自由的呀，不信你把这个issue的话在gitee打一遍，分分钟404，牛逼啊。所以我从来不用Gitee。

但言论自由的前提下，你别给中国人丢脸啊，我一直在劝你不要乱骂人，你完全不听，那我也没办法。如果言论不自由，你可能都没办法在这里骂到现在，不是吗？因为没有国内的审查机制。

**Comment by tonyqus** [comment]
另外我昨天就有点感觉，总感觉npp作者这次是故意的，嫌事不够大，他玩的激将法，然后我找到了实锤 #12324 。

npp作者之所以激怒你们的目的就是要你们fork并且在国内传播npp，改名都无所谓，因为那始终是npp。
