### ISSUE TITLE
请滚出互联网，别来污染开源环境please get off the internet and don't pollute the open source environment

### ISSUE THREAD

**Issue by HelloDB** [notepad-plus-plus/notepad-plus-plus#12988]
### Steps to Reproduce the Issue

1. 
2. 
3.

**Comment by OrochiZ** [comment]
开源环境属于作者,不属于你这种机器人

**Comment by brushhousejn** [comment]
**草™的notepad++，犯我中华者虽远必诛！！！**

**Comment by OrochiZ** [comment]
> **草™的notepad++，犯我中华者虽远必诛！！！**

诛你妈逼

**Comment by brushhousejn** [comment]
> 



> > **草™的notepad++，犯我中华者虽远必诛！！！**
> 
> 诛你妈逼

# 脑子不要可以捐给有需要的人，但是请不要把中国的脸丢到国外。
![cn](https://brushhousejn.github.io/img/cnflag.png)

**Comment by OrochiZ** [comment]
> > 
> 
> > > **草™的notepad++，犯我中华者虽远必诛！！！**
> > 
> > 
> > 诛你妈逼
> 
> # 脑子不要可以捐给有需要的人，但是请不要把中国的脸丢到国外。
> ![cn](https://camo.githubusercontent.com/37eed666ee3fc23a38f99113081c22d49b1a47e3ca859cd75642d1dfd7366e37/68747470733a2f2f6272757368686f7573656a6e2e6769746875622e696f2f696d672f636e666c61672e706e67)

不就是你这种垃圾在丢脸吗

**Comment by brushhousejn** [comment]
> > > 
> > 
> > 
> > > > **草™的notepad++，犯我中华者虽远必诛！！！**
> > > 
> > > 
> > > 诛你妈逼
> > 
> > 
> > # 脑子不要可以捐给有需要的人，但是请不要把中国的脸丢到国外。
> > ![cn](https://camo.githubusercontent.com/37eed666ee3fc23a38f99113081c22d49b1a47e3ca859cd75642d1dfd7366e37/68747470733a2f2f6272757368686f7573656a6e2e6769746875622e696f2f696d672f636e666c61672e706e67)
> 
> 不就是你这种垃圾在丢脸吗

funny mud pee
