### ISSUE TITLE
滚出互联网，f*** off from the Internet！

### ISSUE THREAD

**Issue by brushhousejn** [notepad-plus-plus/notepad-plus-plus#12989]
Notepad++ say it the user HAVE to agree to anti China, or it will put virus into our computer.  This violates the spirit of open source！
（Notepad++强迫使用者反华，违反了开源精神！）

1. Uninstall notepad++.
2. Report it.

![国旗护体-doge](https://image.fcweb.ml/i/2023/01/28/s5zilb.png)

### Debug Information

[https://www.bilibili.com/video/BV1dY411D7zW/](https://www.bilibili.com/video/BV1dY411D7zW/)

**Comment by ErrorNoInternet** [comment]
> or it will put virus into our computer.

When did anyone ever say that?

**Comment by brushhousejn** [comment]
> > or it will put virus into our computer.
> 
> When did anyone ever say that?

Notepad++ said it On Twitter.

**Comment by ErrorNoInternet** [comment]
> > > or it will put virus into our computer.
> > 
> > 
> > When did anyone ever say that?
> 
> Notepad++ said it On Twitter.

![image](https://user-images.githubusercontent.com/61157623/215412653-7723266e-7e5f-47f7-9c9e-f2b87e5e9b23.png)
![image](https://user-images.githubusercontent.com/61157623/215412456-ada566b9-0c53-4b21-a06d-60e08e03edd2.png)

哇塞好大的病毒！！！11！😳🤯😱

**Comment by ripsnortntear** [comment]
![Screenshot 2023-01-30 035734](https://user-images.githubusercontent.com/96964368/215431819-040fe798-8b56-472e-8b56-ac6d8b4b727b.jpg)

**Comment by Poempoat** [comment]
小粉红又狗急跳墙了

**Comment by brushhousejn** [comment]
> 

我跟你讲，语文不好可以学，脑子不要可以捐给有需要的人

**Comment by brushhousejn** [comment]
> 小粉红又狗急跳墙了

我跟你讲，语文不好可以学，脑子不要可以捐给有需要的人

**Comment by OrochiZ** [comment]
1.作者没有义务遵守任何精神
2.开源精神不是你说了算

**Comment by Hatsune-George** [comment]
> 小粉红又狗急跳墙了

你是中国人还是外国人，如果是外国人，我就不喷了，毕竟没意义

**Comment by OrochiZ** [comment]
> > 小粉红又狗急跳墙了
> 
> 你是中国人还是外国人，如果是外国人，我就不喷了，毕竟没意义

是中国人的祖宗

**Comment by Hatsune-George** [comment]
> 1.作者没有义务遵守任何精神 2.开源精神不是你说了算

So ,you are not a chinese people , right ?

**Comment by Hatsune-George** [comment]
> > > 小粉红又狗急跳墙了
> > 
> > 
> > 你是中国人还是外国人，如果是外国人，我就不喷了，毕竟没意义
> 
> 是中国人的祖宗

You are Chiang Kai-shek's grandson，right ?

**Comment by OrochiZ** [comment]
> > 1.作者没有义务遵守任何精神 2.开源精神不是你说了算
> 
> So ,you are not a chinese people , right ?

没有必要告诉你这种狗吧.

**Comment by brushhousejn** [comment]
> 

炎帝黄帝还活着？？？你没事吧，还中国祖宗

> > > 小粉红又狗急跳墙了
> > 
> > 
> > 你是中国人还是外国人，如果是外国人，我就不喷了，毕竟没意义
> 
> 是中国人的祖宗

**Comment by brushhousejn** [comment]
> 1.作者没有义务遵守任何精神,也就不存在违反 2.作者和开源精神也没有任何矛盾 3.你是傻逼乱叫唤

丢脸丢国外

**Comment by Hatsune-George** [comment]
> > > 1.作者没有义务遵守任何精神 2.开源精神不是你说了算
> > 
> > 
> > So ,you are not a chinese people , right ?
> 
> 没有必要告诉你这种狗吧.

**我不知道我是什么，但你一定是莓果的走狗，哈哈哈**
为什么我们的祖国里会出现你这样的人捏，你去外国吧，既然不支持我们中国的政策

**Comment by brushhousejn** [comment]
> > > 1.作者没有义务遵守任何精神 2.开源精神不是你说了算
> > 
> > 
> > So ,you are not a chinese people , right ?
> 
> 没有必要告诉你这种狗吧.

？滚滚滚

**Comment by brushhousejn** [comment]
> > > > 1.作者没有义务遵守任何精神 2.开源精神不是你说了算
> > > 
> > > 
> > > So ,you are not a chinese people , right ?
> > 
> > 
> > 没有必要告诉你这种狗吧.
> 
> **我不知道我是什么，但你一定是莓果的走狗，哈哈哈** 为什么我们的祖国里会出现你这样的人捏，你去外国吧，既然不支持我们中国的政策

其实我觉得美国都不要它做狗，太™臭了

**Comment by Hatsune-George** [comment]
> > 1.作者没有义务遵守任何精神,也就不存在违反 2.作者和开源精神也没有任何矛盾 3.你是傻逼乱叫唤
> 
> 丢脸丢国外

这人还不如xxs，郑智从小到大考0蛋

**Comment by brushhousejn** [comment]
> ![Screenshot 2023-01-30 035734](https://user-images.githubusercontent.com/96964368/215431819-040fe798-8b56-472e-8b56-ac6d8b4b727b.jpg)

这不是笑话，这是圆场，还圆得比我还差！（It's not a joke, fun tmd pee!）

**Comment by OrochiZ** [comment]
> > > > 1.作者没有义务遵守任何精神 2.开源精神不是你说了算
> > > 
> > > 
> > > So ,you are not a chinese people , right ?
> > 
> > 
> > 没有必要告诉你这种狗吧.
> 
> **我不知道我是什么，但你一定是莓果的走狗，哈哈哈** 为什么我们的祖国里会出现你这样的人捏，你去外国吧，既然不支持我们中国的政策

为什么不是你的狗屁政策滚出中国呢

**Comment by chhongzh** [comment]
> 1.作者没有义务遵守任何精神,也就不存在违反 2.作者和开源精神也没有任何矛盾 3.你是傻逼乱叫唤

开源协议确实管不到，
但是你的**民族精神**去哪了?

The open source agreement is really beyond our control,
But where is your national spirit?
