### ISSUE TITLE
[DUPLICATE] Font is broken for Obsidian (maybe any non-default) theme

### ISSUE THREAD

**Issue by eugeneko** [notepad-plus-plus/notepad-plus-plus#1299]
Duplicate of #364

STR:
1) Switch theme from Default to Obsidian
2) Restart Notepad++

Note that text font is not Courier New anymore.
Reproduced on two unrelated PCs.
This is broken for a long time.

**Comment by alfrrr** [comment]
I figured out the field _fontName_ at line 739 of Obsidian.xml is empty and it's sufficient to change `fontName=""` to `fontName="Courier New"` to fix the issue.

This is the original line of Obsidian.xml that I changed:

`<WidgetStyle name="Default Style" styleID="32" fgColor="E0E2E4" bgColor="293134" fontName="" fontStyle="0" fontSize="" />`

**Comment by mjohnsonengr** [comment]
@alfrrr 
Awesome thanks!

Was line 738 for me, but details...
