### ISSUE TITLE
i Support NotePad++.

### ISSUE THREAD

**Issue by MomijiHanako** [notepad-plus-plus/notepad-plus-plus#12993]
I respect the author's political stance, because I also use notepad++, and I came here to give the author stars.

**Comment by Hatsune-George** [comment]
emmm...Where are you from ?

**Comment by MomijiHanako** [comment]
> emmm...Where are you from ?

japan thx.

**Comment by Hatsune-George** [comment]
> 

I have no comment on your opinion because you are not a Chinese, but I think it is shameful to destroy the territorial integrity of our motherland. & thx

**Comment by MomijiHanako** [comment]
これらの嫌なコメントがあれば、この問題はクローズします。
还有，我是住在日本的中国人。
支持作者的政治立场。

**Comment by Hatsune-George** [comment]
### **What I don't understand is why you think that. Why do you want our territory split ? I'm confused**

**Comment by MomijiHanako** [comment]
All I can say is your heart. It's too fragile, and it belongs to the kind that breaks when touched.

**Comment by Hatsune-George** [comment]
> All I can say is your heart. It's too fragile, and it belongs to the kind that breaks when touched.

### 嘿嘿，呃，也许吧，只是我不知道你们为什么没有理由地去那样想
Well, maybe, but I don't know why you have no reason to think that way

**Comment by MomijiHanako** [comment]
> > All I can say is your heart. It's too fragile, and it belongs to the kind that breaks when touched.
> 
> ### 嘿嘿，呃，也许吧，只是我不知道你们为什么没有理由地去那样想
> Well, maybe, but I don't know why you have no reason to think that way

我只是说那些人，天天无聊在这里霸屏，但是这可没有影响到作者。

I'm just talking about those people who are bored here and dominate the screen every day, but this does not affect the author.

**Comment by Hatsune-George** [comment]
> > > All I can say is your heart. It's too fragile, and it belongs to the kind that breaks when touched.
> > 
> > 
> > 嘿嘿，呃，也许吧，只是我不知道你们为什么没有理由地去那样想
> > Well, maybe, but I don't know why you have no reason to think that way
> 
> 我只是说那些人，天天无聊在这里霸屏，但是这可没有影响到作者。
> 
> I'm just talking about those people who are bored here and dominate the screen every day, but this does not affect the author.

### 呃，我想声明的是：
**第一，我无法预言未来会发生什么，但是我知道中国有个成语叫“厚积薄发”。
第二，我认为，我们中的大部分人只不过是过一过嘴瘾罢了，没想将这位作者怎么样。
第三，我认为，这位作者恶意向他人源代码中植入随机字符串的行径，严重违反了国际开源准则和公约
第四，我认为，github不是键政的地方，既然作者这么喜欢建政，那我们也只好奉陪一下，毕竟我们是中国人**
