### ISSUE TITLE
中华人民共和国是工人阶级领导的，以工农联盟为基础的社会主义国家！

### ISSUE THREAD

**Issue by JiaGuZhuangZhi** [notepad-plus-plus/notepad-plus-plus#13001]
某些人不是工人、农民或无产者却在道德的制高点上批判共产主义，批判中华人民共和国，这是荒谬的、可笑的、无耻的！我对此表示强烈谴责！

**Comment by OrochiZ** [comment]
举报中共狗

**Comment by XiaoMeng22333** [comment]
> 举报中共狗

我没有说中国共产党，我说的是共产主义！！！！

**Comment by OrochiZ** [comment]
> > 举报中共狗
> 
> 我没有说中国共产党，我说的是共产主义！！！！

中共狗自己说了什么都不记得了,真可笑

**Comment by XiaoMeng22333** [comment]
> > > 举报中共狗
> > 
> > 
> > 我没有说中国共产党，我说的是共产主义！！！！
> 
> 中共狗自己说了什么都不记得了,真可笑

我指的是这个issues，而且我说话没有侮辱性语言，而您总是恶语相向

**Comment by Hatsune-George** [comment]
### **中华人民共和国万岁，中国共产党万岁！英特纳雄耐尔就一定要实现**
