### ISSUE TITLE
”数典忘祖，认贼作父“的bug怎么修

### ISSUE THREAD

**Issue by laxusvip** [notepad-plus-plus/notepad-plus-plus#13008]
数典忘祖，认贼作父

**Comment by poijsda** [comment]
翻个墙，就是为了来骂作者。

**Comment by Faq** [comment]
你的责骂改变不了任何事

**Comment by yangshunhuai** [comment]
GitHub 不容忍基于个人或群体的特征（包括年龄、体型、能力、民族、性别认同和表达、经验水平、国籍、个人外表、种族、宗教、性身份或性取向）攻击或宣扬对个人或群体的仇恨言论。

不可接受的行为包括：

* 使用性暗示语言或意象，或者不恰当的身体接触、性关注或挑逗
* **挑衅、侮辱或贬损性评论，人身或政治攻击，或总是打断谈话或其他活动**
* 蓄意恐吓、尾随、跟踪或骚扰性摄影或录音
* **任何形式的骚扰，即使是以开玩笑或嘲弄的方式进行**
* 在职业场合中会被认为不适当的其他行为

直接举报吧，前面还扬言要加什么恶意代码，恶心死了
