### ISSUE TITLE
Last docs/files lost after upgrade to Notepad++

### ISSUE THREAD

**Issue by sjs1959** [notepad-plus-plus/notepad-plus-plus#13002]
### Steps to Reproduce the Issue

1. Our IT department automatically Updated our version of Notepad++ to v8.4.8 - [Dec 24 '22  19:40:27]
2. After this the previously opened files that I had been looking at are no longer loaded.
3. I have searched the Registry for any clues of the previously attached/opened files with no luck.

### Expected Behavior

When I opened Notepad++, I expected to see the previously opened files.

### Actual Behavior

The screen opened as expected but no files are there to be seen.

### Debug Information

Notepad++ v8.4.8   (64-bit)
Build time : Dec 24 2022 - 19:40:27
Path : C:\ProgramData\App-V\8F5FD81E-FE14-4989-8D4D-6F6A0B487387\5F797667-9E47-4E31-91D2-E538171B5AB9\Root\VFS\ProgramFilesX64\Notepad++\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 10 Enterprise (64-bit) 
OS Version : 22H2
OS Build : 19045.2486
Current ANSI codepage : 1252
Plugins : 
    ComparePlugin (2.0.2)
    CsvQuery (1.2.9)
    mimeTools (2.9)
    NppConverter (4.5)
    NppExport (0.4)

**Comment by donho** [comment]
Related issue:
https://community.notepad-plus-plus.org/topic/23938/notepad-v8-4-8-release/24?_=1675031317491

**Comment by donho** [comment]
@sjs1959 
Thank you for your report. And sorry for your lost session data.
Could you provide the content of file `%APPDATA%\Notepad++\session.xml` please?

**Comment by sjs1959** [comment]
Hi Don,

I have found why the files were lost and as you have suggested the Session.xml holds the key. I found the old Session.xml file with all the files within it, however our IT department have blocked me from copying the old file into the new area. I will need to get them to do that for me. Hopefully, this will resolve my problem.

This will continue to happen unless there is a work around. Maybe the Workspace Container? I don't know anything about this though.


________________________________

**Comment by donho** [comment]
@sjs1959 
> I have found why the files were lost and as you have suggested the Session.xml holds the key. I found the old Session.xml file with all the files within it, however our IT department have blocked me from copying the old file into the new area. I will need to get them to do that for me. Hopefully, this will resolve my problem.

Happy to learn that you will be able to get all your data back. Just try to understand better the situation: Has your old `%APPDATA%\Notepad++\session.xml` been moved into another folder during the update of Notepad++?

**Comment by sjs1959** [comment]
Hi Don,

The new software was installed in %APPDATA%\Notepad++ along with the new 'empty' sessions.xml file.

The old version software was left on the disk with the OLD %APPDATA% reference and the BIG session.xml file still exists.

I found all the files in the backup folder.
Saved them to OneDrive.
Loaded new software. Went to Settings/Preference/Default Directory. Pointed to OneDrive Folder and recovered all the 'lost' files.

So we got there in the end.

Thanks for your interested with this.

KR
Scott

________________________________

**Comment by donho** [comment]
@sjs1959 
Thank you for your information.
Nice to learn that everything is in order for you now!
