### ISSUE TITLE
Php 8.1 keywords `readonly`, `enum` and `never` have no syntax highlighting

### ISSUE THREAD

**Issue by Compaszer** [notepad-plus-plus/notepad-plus-plus#13012]
### Description of the Issue
Php 8.1 keywords `readonly`, `enum` and `never` have no syntax highlighting.

### Steps to Reproduce the Issue
Type in `readonly`, `enum` or `never` in a .php file.

### Expected Behavior
Expected `readonly`, `enum` and `never` to be syntax highlighted as keywords like `class` or `private`.

### Actual Behavior
`readonly`, `enum` and `never` have actually no syntax highlighting

**Comment by ArkadiuszMichalski** [comment]
Refs:
https://www.php.net/manual/en/language.oop5.properties.php#language.oop5.properties.readonly-properties

https://www.php.net/manual/en/language.types.enumerations.php
https://www.php.net/manual/en/language.enumerations.basics.php

https://www.php.net/manual/en/language.types.never.php

Some examples:
https://php.watch/versions/8.1/readonly
https://php.watch/versions/8.1/never-return-type
https://php.watch/versions/8.1/enums
