### ISSUE TITLE
您怎么还活着？

### ISSUE THREAD

**Issue by QianMoo0121** [notepad-plus-plus/notepad-plus-plus#13019]
你知道你为什么会被网爆吗，你知道为什么你的软件会被这么多人抛弃吗？他们都用上国产Notepad3了，你在丢尽台湾人的脸，你不觉得你的心智是不成熟的，像一个孩子一样叫唤反华，祖国辛辛苦苦培养你你就这么报答祖国吗?在官网明示反华，互联网不是你的撒野之地，没有人会惯着你这种心理。

**Comment by alter2718** [comment]
支持，我鄙视的是作者这个小人，但是，如果你坚持统一，放弃政治，那我愿意接受，毕竟，这是个开源软件

**Comment by tonyqus** [comment]
> 作者真的是太搞笑了，自己作为被资本剥削的打工人，还在为资本主义摇旗呐喊

哎，韭菜何必为难韭菜，你来这里，不就是为中国特色社会主义摇旗呐喊，都一样。

**Comment by Meritamen** [comment]
支那猪能不能滚回墙内

**Comment by andrewintw** [comment]
@QianMoo0121 @alter2718 @hywlzn 笑死了，一群自嗨的傻 B，你們崩潰的樣子，看了有夠療癒。

**Comment by tonyqus** [comment]
好想去台湾旅游，共军不允许，妈的！
