### ISSUE TITLE
Tab order of controls in Mark dialog

### ISSUE THREAD

**Issue by white-gthb** [notepad-plus-plus/notepad-plus-plus#13021]
### Description of the Issue
Pressing the Tab key repeatedly moves focus to unexpected controls in the Mark dialog.

### Steps to Reproduce the Issue

1.  Open the Mark dialog: menu `Search/Mark.. (Ctrl+M)`
2.  Hit the Tab key repeatedly.

### Expected Behavior
A tab order consistent with the tab order on the other pages of the dialog (Find, Repace, etc,).

### Actual Behavior
Tab order is all over the place.

### Debug Information
Notepad++ v8.4.9   (64-bit)
Build time : Jan 27 2023 - 03:11:16
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 11 (64-bit) 
OS Version : 22H2
OS Build : 22621.1194
Current ANSI codepage : 1252
Plugins : 
    DSpellCheck (1.4.24)
    HexEditor (0.9.12)
    mimeTools (2.9)
    NppConverter (4.5)
    NppExport (0.4)

**Comment by alankilborn** [comment]
I have a hard time knowing what is really expected for good UX in this case.

But let's consider how the _Replace_ tab's tab-ordering works; here is its ordering for repeated presses of Tab:

* Find what
* Replace with
* "swap"
* In selection
* Backward direction
* Match whole word only
* Match case
* Wrap around
* Search mode
* Find previous
* Find next
* "2 find button mode"
* Replace
* Replace All
* Replace All in All Opened Documents
* Close
* Transparency
* "reduce size"
* Replace tab (after which the cycle will repeat from the top with "Find what")

Mostly it seems like a "top-to-bottom-on-left-side-then-top-to-bottom-on-right-side" scheme.

With that in mind, I don't think "tab order is all over the place" for Mark tab.  Yes, there is a problem here, but it really is just a few things that are out of sequence and maybe cause it to appear "all over...".

If we take how Replace tab works, and consider that as gospel, then repeated Tab presses in the Mark tab should proceed in this order:

* Find what
* In selection
* Bookmark line
* Purge for each search
* Backward direction
* Match whole word only
* Match case
* Wrap around
* Search mode
* Mark All
* Clear All Marks
* Copy Marked Text
* Close
* Transparency
* "reduce size"
* Mark tab (after which the cycle will repeat from the top with "Find what")

A perhaps "wonky" choice is where I placed "In selection" in the ordering.  I placed it based on the Replace tab's behavior, but, I don't know if that's best for Mark tab...

------------------------------------------------

A suggestion that is unrelated to the problem, is to use the Alt+key choices to move directly to and "activate" the control you wish to.  For example, Alt+m would move the focus to "Bookmark line" and toggle its state.  A problem with this is that some of the controls (notably the "action" buttons along the right of the window don't feature underlined characters in their text, indicating they have this feature. :-(  But, Enter will always "press" the Mark All button, which is the most commonly used one.

**Comment by alankilborn** [comment]
@ozone10 Will this one also be addressed with your other one(s) that deal with tab ordering?

**Comment by white-gthb** [comment]
Seems to be fixed in v8.5.2.
Closing this issue.
