### ISSUE TITLE
Syntax highlighting in JSON files

### ISSUE THREAD

**Issue by vlakoff** [notepad-plus-plus/notepad-plus-plus#1303]
Just noticed my JSON files don't have syntax highlighted anymore.
I can get it back by switching to "Language > JavaScript".
Might be related to the recent "embedded JavaScript" styler changes.

Tell me if you need more info :)

**Comment by vlakoff** [comment]
Ah, and I'm using ZenBurn theme. Looks like it's a theme issue.

**Comment by vlakoff** [comment]
It's in fact due to the implementation of [JSON highlighting](https://github.com/notepad-plus-plus/notepad-plus-plus/commit/46e810aa53a75c9dcf4edb23dbdf7b96e68349c5), which has been separated from JavaScript highlighting.

Themes would need updating, but another solution could be to fallback to JavaScript if the theme doesn't have JSON rules, like it has been done for [embedded JavaScript](https://github.com/notepad-plus-plus/notepad-plus-plus/commit/963d7fc885e022c5e1937151cb35df2cf39a14aa#diff-7fec46067447d7e861ce9c86d169fd4c).

**Comment by vlakoff** [comment]
Writing a JSON ruleset for Zenburn theme, I encountered the following issues about JSON highlighting:
* can't figure out what the `CHARACTER` rule applies to
* can't style these valid JSON values: `true`, `false`, `null`

**Comment by dail8859** [comment]
The `CHARACTER` rule is applied to strings wrapped in single quotes. The values are not able to be highlighted currently. To highlight JSON, the C++ lexer is reused, so in theory with a few changes to the code and xml file, you could specify a list of values to highlight (e.g. `true`, `false`, `null`)

**Comment by vlakoff** [comment]
Thanks :)

How about my above suggestion, fallbacking to the JavaScript rules if the theme doesn't have rules for JSON?

> Themes would need updating, but another solution could be to fallback to JavaScript if the theme doesn't have JSON rules, like it has been done for [embedded JavaScript](https://github.com/notepad-plus-plus/notepad-plus-plus/commit/963d7fc885e022c5e1937151cb35df2cf39a14aa#diff-7fec46067447d7e861ce9c86d169fd4c).
