### ISSUE TITLE
https://notepad-plus-plus.org/ is inaccessible in China

### ISSUE THREAD

**Issue by cheny0y0** [notepad-plus-plus/notepad-plus-plus#13038]
Maybe it is caused by GFW or DNS pollution. Please fix.

**Comment by QiBowen2008** [comment]
Because the author of this application has said and done something that made China government unhappy and against Chinese laws so this website cannot be accessed in China now like google.

**Comment by cheny0y0** [comment]
> Because the author of this application has said and done something that made China government unhappy and against Chinese laws so this website cannot be accessed in China now like google.

Qí shí wǒ shì gù yì nòng zhè ge issue de

**Comment by tonyqus** [comment]
@cheny0y0 Why don't you contact Chinese network administration department by yourself? I don't think it's npp's fault. The government should allow different voices as it said in Chinese Constitution. 

`第三十五条  中华人民共和国公民有言论、出版、集会、结社、游行、示威的自由。`

This is the issue you should fix instead of telling npp to fix it. It doesn't make sense.

**Comment by tonyqus** [comment]
So a open source software can impact the national security of China. Do you think it makes sense? Or the government doesn't have confidence on its own at all.

**Comment by I-AM-A-NOOB** [comment]
> So a open source software can impact the national security of China. Do you think it makes sense? Or the government doesn't have confidence on its own at all.

不。错误不是开源软件导致的，而是一些开源软件背后反华势力。中国政府对此做出限制是为了防止中国人因反华势力的不良影响造成社会动荡，进而保障中华人民共和国与中国人民根本利益。
这也并不是中国政府对自己没有信心，而是中华人民共和国极少部分傻瓜（尤其集中于台湾）会相信你们的错误言论，进而危害中国人民的利益。

No. The mistake is not caused by open source software, but by the anti-Chinese forces behind some open source software. The Chinese government restricts this in order to prevent social unrest among Chinese people caused by the bad influence of anti-Chinese forces, and thus to protect the fundamental interests of the People's Republic of China and the Chinese people.
It is not that the Chinese government has no confidence in itself, but that a very small number of fools in the People's Republic of China (especially concentrated in Taiwan) will believe your false statements and thus endanger the interests of the Chinese people.

Most Chinese people's view of donho:https://www.zhihu.com/question/271281045

**Comment by tonyqus** [comment]
> 而是中华人民共和国极少部分傻瓜（尤其集中于台湾）会相信你们的错误言论
你这句就不利于团结和统一了，一边说台湾省是祖国的一部分，一边却在骂人家是傻瓜。你让人家怎么愿意归顺朝廷呢？

那为啥中国大陆要设置国家防火墙（GFW）来屏蔽这些所谓的反华网站，台湾和全世界大部分国家没有国家防火墙呢？这些国家的人民可以自由的了解各种咨询，无论是对国家还是不利的。按照正常逻辑，他们（帝国主义和资本主义）应该害怕才对，他们才应该屏蔽中国的爱国网站。事实却相反，你说这是为什么呢？

> 保障中华人民共和国与中国人民根本利益

到底你指的根本利益是什么呢？能具体说一下吗？

我觉得你这句话改成保障党的利益更合适，因为党不想让普通民众看到或听到不同的声音，这样不利于它的统治。其实npp所提倡的stand with hongkong，好像也谈不上反华吧，hongkong本来就是中国的一部分，当年香港人民也没说要分裂国家呀，他们并没有主张香港独立，而是捍卫香港的言论自由（香港一直是中国民主自由的灯塔，比如以前每年的7.1大游行）。

既然你能上Github，我理解你应该可以翻墙，那些废青、勾结境外反动势力的人你应该去了解下他们的背景，我不认为大部分人会因为金钱利益去出卖自己的国家或者出卖自己的出生地。你可以顺便去了解下香港人民为什么占中，当时多少人占中？出于什么目的？墙外有不同的声音，你可以google搜索（不要用百度，因为那就不是一个完整的搜索引擎），那些所谓的反华势力为什么这么一致的造谣呢？要知道，一个人说谎是容易的，一堆人一起说谎，还说得这么一致是很难的。

我觉得有的时候，你不应该去光听 所谓的好人的说法，也应该去了解下 坏人的想法和动机，你觉得我说的有道理吗？

**可能你还没有成年，所以独立思考的能力还有待提高，但这是每个正常人应该具有的能力，包括你以后从事科研工作，独立思考是非常重要的，不要因为主流思想而左右你的思考范围和科学创意，很多科学发现都是跳出主流框架之后产生。** 这也是为什么大部分近代重大科学发现是在西方自由思想大框架下实现的，而我们中国在基础科学研究领域远远落后，甚至大量的论文抄袭成风（大学教授自己也抄），学术不端。这些与禁锢思想的大环境是有很大的关系的。

我相信你应该听得出，我其实不反华，我爱这个国家。作为中国人，我们的方向其实是一致的，希望国家好、国家富强，清末时期进步思想一度被认为是反动势力（甚至反华），被清政府打压，你有没有发现和现在有点像呢？

**Comment by chinese-wzq** [comment]
> 

建议看一下这个视频：(Bilibili)[https://www.bilibili.com/video/BV1Ua411o7jh/]
叠甲：上述视频主要是讲GFW的利，但是不可否认它也存在弊。当前情况下，其利大于其弊，等到它没有存在价值的时候，自然就消失了。

**Comment by tonyqus** [comment]
我从来没觉得GFW有什么利，不需要看。。。就是一个浪费钱的维稳+洗脑工具

**Comment by chinese-wzq** [comment]
> 我从来没觉得GFW有什么利，不需要看。。。就是一个浪费钱的维稳+洗脑工具

不需要看？......（无语住了）
1.维稳难道是浪费钱吗......
2.说得好听点叫政治宣传，说得难听点叫洗脑，其实就是维护国家稳定。没了GFW外国势力想要搞乱中国轻而易举（视频里也说了），打起仗来到时候你我连活着都是问题了。说到底，带有洗脑性质（如果你认为政治宣传=洗脑的话），但利大于弊。
3.请你看视频，谢谢

**Comment by tonyqus** [comment]
你知道张教授在复旦的口碑都多差吗？这人很多说法你不能细品，细品你就会发现基本都是强词夺理。

> 1.维稳难道是浪费钱吗......

首先说维稳这事，你说大家都是成年人，为什么要维稳呢？为什么要有个强来禁止你看所谓不该看的东西呢？这明明是人民的政权，维稳是动词，那对象是谁？是人民吗？这好像说不通啊，一个人民的政权要来维稳自己？还说是特权阶层维稳韭菜（或者说羊群）？

你如果说的是后者，那从这个角度来说，确实墙不浪费钱，但为什么近几年维稳经费越来越多，但是网上维稳效果一年不如一年呢？真的是如同张教授所说的，美国的互联网意识形态武器特别厉害，无孔不入吗？还是说韭菜也在觉醒？

回过来说 墙的效果，按理说，有了墙就能让“人民安居乐业”，不受“墙外境外势力”和诈骗集团的感染，但为什么还是电信诈骗频发呢？搞得现在就算真警察打电话过来，我都不相信他是真警察，你说这社会到底怎么了？

> 说到底，带有洗脑性质（如果你认为政治宣传=洗脑的话），但利大于弊。

你既然知道这玩意是洗脑，你还认为利大于弊，我真的觉得你的思路不正常。顺民对于管理来说确实方便，但是对于科学发展、创意产业、学术提升都是弊大于利，因为大家的棱角都被磨掉了，甚至都不会表达自己的不同观点，那对于社会的发展自然是弊大于利。反观北美的高等教育，鼓励学生挑战权威、不提倡尊师重道（在学术问题上不要给面子）。

你看这么多年了，中国的社会人文科学有什么进步吗？更不要说理工类的学术腐败了，其实我觉得跟GFW的存在都是有潜移默化的关系的，因为洗脑的关系，抹杀了社会的创造力，这是中国社会目前面临最严重的问题，说句不好听的就是摧毁生产力。

香港其实在推行国安法之后，就基本摧毁了原本的言论自由，你知道现在的香港有多萧条吗？

**Comment by tonyqus** [comment]
再来说Stand with Hongkong，其实我一直觉得这个口号非常中立，只是很多人把他误读为 香港独立。那你说他为什么不直接说 香港独立 呢？你看美国加州年年都说要独立，他们就从来不用这么温和的标语，人家是直接说 calexit（加州独立）。

一样的道理，有欧洲的兄弟建议我支持乌克兰的话，应该说Stand with Ukraine，而不是Slava Ukraini，因为Slava Ukraini更像是纳粹口号，所以他们建议用Stand with Ukraine，所以我说Stand with XXX 是很中立的表述。

其实，香港问题不能单单归结为境外势力，否则不可能前几年100多万人出来游行，要知道香港人口才700多万。如果你从小生活在言论自由的国家，从小被灌输人权、言论自由思想，你就能理解为什么香港人要站起来返送中，虽然我不是香港人，但我能理解他们。然而，我能理解，不等于我支持香港独立啊，再说怎么独立？哪有这么容易？要说独立，先让加州做个表率，独立出来给大家看看呗。

**Comment by chinese-wzq** [comment]
1.虽然他是复旦之耻，但是我个人认为这个视频讲得还是有点道理的，所以我才会想让你看看......如果你认为他说得不对你也可以在视频评论区里捋一下思路说出来。


2.你应该是理解错我的意思了，我说的维稳是维护国家稳定，跟维护中国共产党不是一个意思。最少国家稳定、没有战争这个GFW存在的直接效果是和你的生活质量有关系吧？


3.`不受“墙外境外势力”和诈骗集团的感染`？有可能嘛，总不可能GFW哪一天把境外号码、境外到境内的流量全屏蔽了吧，所以说这根本不是墙要达到的目的，也根本不可能达到，只能通过做舆论宣传，减少诈骗分子、增加防骗意识。


4.大哥，我说的是如果你认为政治宣传等于洗脑的话，不代表我认为政治宣传等于洗脑啊。政治宣传和洗脑是不同的概念。政治宣传可以是合法的和合理的，只要它是透明的、诚实的和不涉及强制手段的。而洗脑则是非法的和不道德的，因为它侵犯了个人的思想自由和人权。难道国家强制你上党课了吗？


`政治宣传抹杀了社会的创造力`这句话太绝对了。政治宣传也可以激发人们的热情和动力，推动社会变革和进步。宣传某种政治理念或价值观也可以激励人们去思考、探索和创新。如在中国的抗日战争和解放战争时期，共产党通过宣传和鼓动，激发了人们的爱国热情和抗日斗争的动力，推动了中国人民的团结和抗战胜利。再比如，在新中国成立后，共产党通过宣传和鼓动，推动了社会主义建设和现代化进程，取得了一系列重大的成就。


5.`GFW对于科学发展、创意产业、学术提升都是弊大于利，因为大家的棱角都被磨掉了，甚至都不会表达自己的不同观点`、`中国的社会人文科学有什么进步吗？更不要说理工类的学术腐败了` 硬要说是GFW的锅有点牵强了，涉及太多方面了。还有，我和你看到的好像不太一样，我看到了：`长春光机所研制成功极紫外光刻机重要部件一一EUV光源工程化样机`、`三年疫情期间中国成为唯一连续三年正增长国家，成为全球7大经济体中增幅最高的一个`。

中国仍然存在很多问题，需要我们共同探讨、思考解决之道，创造更美好的未来。


6.`Stand with Hongkong`为什么很多人把他误读为香港独立？很重要的原因是香港的历史。炎黄子孙是一家，没有人希望香港再独立一遍了，这也是为什么我们这么希望台湾统一。所以你也应该知道为什么大部分中国人对于`Stand with Hongkong`这句话的理解和你的不一样了。在你这它可能是中立的、温和的，但是对于大部分其他人来说就是另一个意思了，所以还是少用吧。
不可否认，中国的言论自由得到了更多限制，但这不等于中国没有言论自由。这是有历史原因的。相信随着时间的推移，中国的言论自由会得到越来越好的保障。

关于解决这些问题，你怎么看？应该怎么做？如果合理的话，你可以试试找附近的人大代表聊一聊，写成提案;或者去(人民群众留言入口)[https://liuyan.www.gov.cn/hudong/atwls/rmqz.htm]留言。


7.打了这么多字，我也真的很累，但是也蛮有收获的。我之后可能不会回复这么快，因为我还有自己的事要去做，但我想到的话就会回复你的。
还有不知道你擅不擅长C++或Python？我看你的个人资料你应该是个资深程序员，想有问题能够问你，我不擅长C++，Python也就中等水平吧。

**Comment by tonyqus** [comment]
> 你可以试试找附近的人大代表聊一聊，写成提案

你在逗我玩吗？你还能找到人大代表聊聊？请demo一下。你好像对国内的官场运作机制不太了解，是不是刚留学回来？出国更爱国？

> 如在中国的抗日战争和解放战争时期，共产党通过宣传和鼓动，激发了人们的爱国热情和抗日斗争的动力，推动了中国人民的团结和抗战胜利。再比如，在新中国成立后，共产党通过宣传和鼓动，推动了社会主义建设和现代化进程，取得了一系列重大的成就。

你这段实在太正面了，感觉像官方宣传稿。建议去了解下真实的抗日战争历史，以及国军和共军实际伤亡人数对比，从数字能看出到底谁在真抗日，特别是一些大的战役。比如著名的淞沪抗战和四行仓库战役。建议理性爱国，了解真实历史。

**Comment by chinese-wzq** [comment]
> 

1.如果可能的话。不能一棒子打死所有的官，对吧？也许你在的地区受限于各种条件就不适合。
2.我看到的又和你看到的不太一样了：[知乎：国共两党，谁在积极抗日，谁在祸国殃民](https://zhuanlan.zhihu.com/p/389577797)

**Comment by tonyqus** [comment]
我刚发现你是初中生，可能我语气有点重。我之所以跟你聊这么多，是因为我在你这年龄的时候一样“爱国爱党”，我甚至是第一批入团的，可能需要个过程吧，慢慢来，既然能出墙，你会知道一个真实的中国。少看知乎和国内媒体，你可以在油管上找找国民党抗日的资料，国内能说的都是对执政有利的东西，但不一定是真实的历史。

一样的道理，我们现在的聊天不可能出现在国内任何媒体（包括知乎），因为肯定会被删帖，甚至封号。所以你在国内的网站根本看不到真正的历史。

**Comment by chinese-wzq** [comment]
> 

在敌方就能看到更客观的历史了？虽说不是不可能，但夹带私货也还是有的。这个notepad++不就夹带私货吗，墙外看到的不全是对的，应该有自我判断力。
油管上的视频真的让我很无语......给中国人深度定制政治内容，用意太明显了。所以这就是我不刷油管的原因。

很想问个问题：你看到的中国，真的是真实的中国吗？

**Comment by tonyqus** [comment]
那我想问你：你墙内看到的中国，真的是真实的中国吗？

当然我知道很难说服你，我说了这需要时间，毕竟按你的年龄，你也被洗了10几年脑子了，我自己也是花了好多年才被洗回来（因为论年龄我被洗脑的时间比你长多了），你可以质疑我，怀疑真实性。但我希望今天的聊天能够在你的心里埋下种子，我说的也不一定都对，正如你说的，油管上也有很多假的信息，包括假的历史描述。

另外你比其他初中生更有优势，毕竟你懂得用梯子，墙外有很多好的编程学习资源，还是免费的。

**Comment by tonyqus** [comment]
我确实不能证明 你被洗脑了，但是你也说了 GFW的一个目的就是用来洗脑的（你所谓的政治宣传），所以我感觉你隐约是接受这种说法的。

淞沪抗战是个不错的研究课题，你可以具体研究下墙内外的表述和相关资料。很多时候，真相是需要靠拼凑的，哪一方都不一定说的对，说的全面。

维基解密是个相对中立的百科网站，类似于国内的百度百科，维基解密是所有百科的鼻祖。
https://zh.wikipedia.org/wiki/%E6%B7%9E%E6%B2%AA%E4%BC%9A%E6%88%98

建议不要受战狼外交策略的影响，不要把墙外所有的东西都假设为敌对势力，其实我们并没有这么多敌人和境外势力。撇开政客不说，全球人民还是有很多善意的，很多时候我们所说的恶意和诋毁，只是因为他们在说事实，而不是因为他们跟我们对立。

**Comment by chinese-wzq** [comment]
> 

1.淞沪抗战？有意思，记住了。
2.我知道维基百科（比百度百科强很多），但不知道维基解密（查了之后发现是多人泄密网站），你给的网站是维基百科的。
3.`建议不要受战狼外交策略的影响，不要把墙外所有的东西都假设为敌对势力，其实我们并没有这么多敌人和境外势力。撇开政客不说，全球人民还是有很多善意的` 我同意，外国还是有很多国际友人的，应该分清人民和敌人。
4.`很多时候，真相是需要靠拼凑的，哪一方都不一定说的对，说的全面。` 我同意你的看法，看事实真相不能只看一方，不然就不用翻墙了。
5.`很多时候我们所说的恶意和诋毁，只是因为他们在说事实，而不是因为他们跟我们对立。` 我也同意，忠言逆耳利于行，但有时也是真的恶意诋毁。
6.在你看来GFW存在的主要作用是洗脑，我想这是你认为它没有什么利的原因。但我认为它的`当下`的主要作用是维护国家稳定，而且政治方面能起的效果也越来越弱，因为现在大家的目光越来越开阔（得益于B站、抖音这类短视频平台的兴起），越来越有国际视野，我相信墙有一天会完成使命，光荣退休。

**Comment by systemoutprintlnhelloworld** [comment]
果然是不同立场都无法说服对方...

**Comment by tonyqus** [comment]
@systemoutprintlnhelloworld 你的大学让我想起了知乎上某个技术大佬，现在医学生都这么牛逼的吗？

![image](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/772561/374ef5ca-4335-4fef-b70c-9336ba6ae458)

**Comment by systemoutprintlnhelloworld** [comment]
> @systemoutprintlnhelloworld 你的大学让我想起了知乎上某个技术大佬，现在医学生都这么牛逼的吗？
> 
> ![image](https://private-user-images.githubusercontent.com/772561/296624307-374ef5ca-4335-4fef-b70c-9336ba6ae458.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUzMDA5NTAsIm5iZiI6MTcwNTMwMDY1MCwicGF0aCI6Ii83NzI1NjEvMjk2NjI0MzA3LTM3NGVmNWNhLTQzMzUtNGZlZi1iNzBjLTkzMzZiYTZhZTQ1OC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDExNVQwNjM3MzBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yNmE0MTEyMmFmZTUxOTM4ODMyNmFkYjI0M2UyMGJlOTllMjdhNDMxNzRjNDA3ZmYxZjQ3ZWY1NjI1NTEzMDQ4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Y9mQHaWj0lqMjDahyu4QD6GwomPhQkFlZWc5Frzfss4)

医科大也不都是医学生,我CV方向搞医学人工智能的
