### ISSUE TITLE
I want to use a web version for an Application I am Developing

### ISSUE THREAD

**Issue by Trigve-Hagen** [notepad-plus-plus/notepad-plus-plus#1305]
Do you have a embed-able version I can use for this App?
Go here and Login in, then go to the Editor link. I need an editor that can work like pixler.com here. Thanks. You can contact me Trigve Hagen at 818-916-0513.
http://www.wereigo.school/web/app_dev.php
http://www.wereigo.school/web/app_dev.php/editor

**Comment by dail8859** [comment]
I would highly recommend *not* using Notepad++. It is purely created as a desktop application. I'd say you are better off using something else. A quick Google search found numerous embeddable editors.

**Comment by linquize** [comment]
Good performance as it is written in C++

**Comment by Trigve-Hagen** [comment]
True, Thanks


Hello,

My name is Trigve Hagan Web Master for Muybridge Media. We are your One
Stop marketing resource for a small or medium size business.  We are a team
of visionary artist with years of experience., specializing in Web
Development, Graphic Design, Photography, Video Production, Social Media
Marketing and Branding.

We believe by coming to one source you will have one clear message across
all your digital and print platforms.  We are interested in creating
marketing materials for you and your brand. Please visit our website at
www.MuybridgeMedia.net <http://www.muybridgemedia.net> to review some of
our recent clients.

If you have any questions please contact us at our office 424-239-9063 or
via email at Contact@MuybridgeMedia.net

We look forward to working with you in future,

[image: photo Emailheadshot.jpg]
<http://s81.photobucket.com/user/sketch2da/media/EmailLogo.jpg.html>
