### ISSUE TITLE
When updating a localization file, which field requires [xml] prefix?

### ISSUE THREAD

**Issue by Patriccollu** [notepad-plus-plus/notepad-plus-plus#13052]
Hello,

I saw that there was a great work on reducing _AppVeyor_ build time and a lot of tests to suppress unnecessary jobs, and I have a question regarding `[xml]` prefix.

In last December, as other translators, I have been told to add `[xml]` [on the beginning of commit title](https://github.com/notepad-plus-plus/notepad-plus-plus/pull/12561#issuecomment-1336163858). But I noticed that the recent PRs also contain `[xml]` on their title.

Please can you clarify whether `[xml]` is required:
- only on Commit description (and subsequent commit for same file)
- only on Pull Request title
- on both fields

Best regards,
Patriccollu.

**Comment by rdipardo** [comment]
It goes in the commit message.

When you create the PR, GitHub copies the commit message into the title field. Most contributors just accept the automatically generated title; that's why it appears in both the PR title and the commit message.

**Comment by Patriccollu** [comment]
Thanks a lot for this clarification. I'm closing this issue.
