### ISSUE TITLE
Notepad++ crashing on W11

### ISSUE THREAD

**Issue by HansTroost** [notepad-plus-plus/notepad-plus-plus#13068]
### Steps to Reproduce the Issue

1. start editing a file with Notepad++
2. just continue for 1 or 2 minutes
3. 

### Expected Behavior

Nothing special, expected just normal editing behaviour
### Actual Behavior

it crashed, without any notice and returned to windows without saving anything.
### Debug Information

Notepad++ v8.4.9   (64-bit)
Build time : Jan 27 2023 - 03:11:16
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 11 (64-bit) 
OS Version : 22H2
OS Build : 22621.1194
Current ANSI codepage : 1252
Plugins : 
    ComparePlugin (2.0.2)
    Explorer (1.9.5)
    MarkdownViewerPlusPlus (0.8.2)
    mimeTools (2.9)
    NppConverter (4.5)
    NppExport (0.4)
    NppHorizontalRuler (0.1.6)

Tried it with older NPP-versions earlier, just upgraded this morning to NPP 8.4.9 but problem persists
Checked windows event-viewer and found this and same messages for older versions as well.
Probably this is an OS-related problem, given de file causing the error. How to solve this?
**Event viewer output:**
Log Name:      Application
Source:        Application Error
Date:          6-2-2023 12:39:56
Event ID:      1000
Task Category: Application Crashing Events
Level:         Error
Keywords:      
User:          HANS-W11\Hans
Computer:      Hans-W11
Description:
Faulting application name: notepad++.exe, version: 8.4.9.0, time stamp: 0x63d33303
Faulting module name: ntdll.dll, version: 10.0.22621.900, time stamp: 0xa97a9ed6
Exception code: 0xc0000374
Fault offset: 0x000000000010c249
Faulting process id: 0x0x4334
Faulting application start time: 0x0x1D93A1EF2560066
Faulting application path: C:\Program Files\Notepad++\notepad++.exe
Faulting module path: **C:\Windows\SYSTEM32\ntdll.dll**
Report Id: 15237773-058e-42df-a8e4-e5e152205892
Faulting package full name: 
Faulting package-relative application ID: 
Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Application Error" Guid="{a0e9b465-b939-57d7-b27d-95d8e925ff57}" />
    <EventID>1000</EventID>
    <Version>0</Version>
    <Level>2</Level>
    <Task>100</Task>
    <Opcode>0</Opcode>
    <Keywords>0x8000000000000000</Keywords>
    <TimeCreated SystemTime="2023-02-06T11:39:56.5128422Z" />
    <EventRecordID>22376</EventRecordID>
    <Correlation />
    <Execution ProcessID="12368" ThreadID="2276" />
    <Channel>Application</Channel>
    <Computer>Hans-W11</Computer>
    <Security UserID="S-1-5-21-124815091-2906503004-3958602653-1001" />
  </System>
  <EventData>
    <Data Name="AppName">notepad++.exe</Data>
    <Data Name="AppVersion">8.4.9.0</Data>
    <Data Name="AppTimeStamp">63d33303</Data>
    <Data Name="ModuleName">ntdll.dll</Data>
    <Data Name="ModuleVersion">10.0.22621.900</Data>
    <Data Name="ModuleTimeStamp">a97a9ed6</Data>
    <Data Name="ExceptionCode">c0000374</Data>
    <Data Name="FaultingOffset">000000000010c249</Data>
    <Data Name="ProcessId">0x4334</Data>
    <Data Name="ProcessCreationTime">0x1d93a1ef2560066</Data>
    <Data Name="AppPath">C:\Program Files\Notepad++\notepad++.exe</Data>
    <Data Name="ModulePath">C:\Windows\SYSTEM32\ntdll.dll</Data>
    <Data Name="IntegratorReportId">15237773-058e-42df-a8e4-e5e152205892</Data>
    <Data Name="PackageFullName">
    </Data>
    <Data Name="PackageRelativeAppId">
    </Data>
  </EventData>
</Event>

**Comment by alankilborn** [comment]
The first thing you should try is removing all plugins except the ones that ship with Notepad++.  Those are:

* mimeTools
* NppConverter
* NppExport

**Comment by rdipardo** [comment]
@HansTroost,
> NppHorizontalRuler (0.1.6)

NppHorizontalRuler has been [incompatible with Notepad++][0] since the 8.4 release.

There is an official patched version of the plugin available for download at https://github.com/roryap/NppHorizontalRuler-x64-en-US/issues/3#issuecomment-1219806900

[0]: https://github.com/roryap/NppHorizontalRuler-x64-en-US/issues/3

**Comment by HansTroost** [comment]
Thanks to both Alan Kilborn and Robert Di Pardo,

 

*	Following Alan’s advice, this time I completely removed Notepad++ without leftovers, using Revo Uninstaller and reinstalled NPP 8.4.9.
Result: a stable working NPP now with less plugins
*	I already downloaded again NppHorizontalRuler but thanks to Robert I now decide to not install it but going to use ColumnTools plugin.

 

I hope that NppHorizontalRuler was the cause of the problem, so it will be gone “forever”.

 

Does – as far as you both know -  Compare Plus cause problems as well? That’s the one I frequently use nowadays.

 

Thanks for your fast and adequate replies!!

 

Kind regards, Hans Troost

**Comment by HansTroost** [comment]
To let you both now: seems that NppHorizontalRuler indeed caused the problem. After removing it, Notepad++ is as stable as it should be.
And btw, I'm very happy with the ColumnTools plugin as a replacement as Robert suggested.

Thanks again you both,

Best regards, Hans Troost
