### ISSUE TITLE
Plugin dialogs are too small when rendered by Vista subsystem (8.4.9 regression)

### ISSUE THREAD

**Issue by rdipardo** [notepad-plus-plus/notepad-plus-plus#13078]
### Description of the Issue

As @ozone10 pointed out [in #13054], 8.4.9 was compiled with the Minimum Required Subsystem set to 6.00 (Windows Vista graphics API), an increase from 5.01/5.02 (XP graphics API). The Vista subsystem can sometimes render GDI dialogs with truncated dimensions that require runtime adjustments (i.e., recompilation) to correct. There is already [one reported case][in #13053] involving N++'s File Doc Switcher, but plugins are affected also.

For example, HTML Tag loads a simple GDI form ([wrapped in Object Pascal](https://github.com/graemeg/fpGUI/blob/571c84ad5cacb100292581ae656bde5c1138b479/src/corelib/gdi/fpg_gdi.pas#L692)). Since 8.4.9, the bottom is cut off, just like @ozone10 reported in #13053 _à propos_ the File Doc Switcher.

<img width="850" alt="htmltagv136-about-dlg-npp-848-v-849" src="https://user-images.githubusercontent.com/59004801/217648087-20c82692-2e5c-4f06-b633-d38627ae86a9.png">

For now this can be worked around by running 8.4.9 in "Compatibility Mode":
- right-click 'notepad++.exe'
- click `Properties > Compatibility > "Run this program in compatibility mode for:"`
- "Windows 7" or older seems to work (your own results may vary)

### Steps to Reproduce the Issue

1. Install N++ 8.4.9
2. Install HTML Tag (*must be >= v1.3.5*)
3. <kbd>Plugins</kbd> > <kbd>HTML Tag</kbd> > <kbd>About</kbd>
4. Only &#x00bd; of the **OK** button is shown
5. Now: 
5.1 Install N++ >= 8.4.8, or;
5.2 Run 8.4.9 in "Compatibility Mode" as per the workaround above
7. Repeat *2.* and *3.*
8. No issue.

### Expected Behavior

Simple GDI dialogs are fully visible when rendered.

### Actual Behavior

Since 8.4.9, simple GDI dialogs are cut off, e.g., the File Doc Switcher, HTML Tag's About dialog, and likely many, many more undiscovered cases

### Debug Information

    Notepad++ v8.4.9   (64-bit)
    Build time : Jan 27 2023 - 03:11:16
    Path : C:\Users\Rob\workspace\bin\npp.8.4.9\notepad++.exe
    Command Line : 
    Admin mode : OFF
    Local Conf mode : ON
    Cloud Config : OFF
    OS Name : Windows 10 Pro (64-bit) 
    OS Version : 21H2
    OS Build : 19044.2486
    Current ANSI codepage : 1252
    Plugins : 
        HTMLTag (1.3.6)
        mimeTools (2.9)
        NppConverter (4.5)
        NppExport (0.4)
        NppFSIPlugin (0.2.1)

<del>### Suggestion</del>

<del>Looks like the Minimum Required Subsystem was changed purely by accident. Perhaps it can just be reverted to the value it had in 8.4.8? I predict the current build configuration will cause a flood of bug reports about truncated windows, and likely months of case-by-case regression patching similar to #13054.</del>

Never mind; the [official word on the new subsystem] is that it stays.

[official word on the new subsystem]: https://github.com/notepad-plus-plus/notepad-plus-plus/pull/13362#issuecomment-1472943894

[in #13054]:
https://github.com/notepad-plus-plus/notepad-plus-plus/pull/13054#issuecomment-1419562836
[in #13053]: https://github.com/notepad-plus-plus/notepad-plus-plus/issues/13053

**Comment by ozone10** [comment]
IMHO `SM_CXFRAME` (`SM_CXSIZEFRAME`) and their "Y" counterparts should be used with `SM_CXPADDEDBORDER` for same values as with XP subsystem.

For ARM64 users the minimal is set to "6.02" so it will still be broken for them.

**Comment by rdipardo** [comment]
> IMHO `SM_CXFRAME` (`SM_CXSIZEFRAME`) and their "Y" counterparts should be used with `SM_CXPADDEDBORDER` for same values as with XP subsystem.

Agreed that the 3rd-party lib is probably at fault.

The better-maintained LCL toolkit [always pads the dimensions] without any visual glitches that I've noticed. (The LCL is too "heavy" for HTML Tag, but [other projects] are using it.)

Closing this now since the immediate issue has been patched: rdipardo/nppHTMLTag@c4d621b

[always pads the dimensions]: https://gitlab.com/freepascal.org/lazarus/lazarus/-/blob/main/lcl/interfaces/win32/win32winapi.inc#L3506-L3525
[other projects]: https://github.com/rdipardo/nppFSIPlugin#readme
