### ISSUE TITLE
Feature request: hotkey to move cursor between cloned document frames

### ISSUE THREAD

**Issue by rujiel** [notepad-plus-plus/notepad-plus-plus#13076]
After using the "clone to other view" hotkey to create a split panel, I would like for there to be a hotkey to navigate to that other panel without having to click anything

The "move to other view" is close to this, but I would like an option where just the cursor is moved rather than the entire document.

In Jetbrains IntelliJ,, this hotkey option is called "Goto next splitter"
 
### Debug Information
Notepad++ v8.4.8   (64-bit)
Build time : Dec 24 2022 - 19:40:27
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : /home/leliel/Desktop/a0a0a0a0a0.txt
Admin mode : ON
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Microsoft Windows 10 (64-bit) 
OS Build : 17134.0
Current ANSI codepage : 1252
WINE : 6.0.3
Plugins : 
    mimeTools (2.9)
    NppConverter (4.5)
    NppExport (0.4)
    NppJsonViewer (1.32)
    NppTextFX (0.2.4)
    XMLTools (3.1.1.12)

**Comment by alankilborn** [comment]
FWIW, a workaround can be achieved using the PythonScript plugin and a short script:

```py
    if not notepad.isSingleView():
        editor2.grabFocus() if notepad.getCurrentView() == 0 else editor1.grabFocus()
```

As scripts can be run by binding them to a keycombo of your choice, this workaround achieves the goal.

For more on scripting, see [HERE](https://community.notepad-plus-plus.org/topic/23039/faq-desk-how-to-install-and-run-a-script-in-pythonscript).

**Comment by Yaron10** [comment]
`View -> Focus on Another View`?

**Comment by alankilborn** [comment]
>View -> Focus on Another View?

Ah, yes, good call.
Default keycombo: F8
@rujiel, please use F8 for your need.

This issue may be CLOSED.

(The PythonScript is still good info for changing the active view programmatically)

**Comment by rujiel** [comment]
Bingo! Thank you both!
