### ISSUE TITLE
Missing translation for the “Move to Other View” and “Clone to Other View” menu items

### ISSUE THREAD

**Issue by przemo20** [notepad-plus-plus/notepad-plus-plus#13088]
### Description of the Issue

Missing translation for the “Move to Other View” and “Clone to Other View” menu items.

### Steps to Reproduce the Issue

1. Open Notepad++
2. Create a new file (open up a new tab)
3. Drag and drop the newly opened tab onto the text area and the menu with untranslated items should show up

https://user-images.githubusercontent.com/22180480/218073956-ee465ce7-f7d9-4611-acb5-34f840527cfd.mp4

### Expected Behavior

Make these items translatable (I believe they aren't yet).

### Actual Behavior

The “Move to Other View” and “Clone to Other View” menu items are missing translation.

### Debug Information

```
Notepad++ v8.4.9   (64-bit)
Build time : Jan 27 2023 - 03:11:16
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 10 Pro (64-bit) 
OS Version : 22H2
OS Build : 19045.2486
Current ANSI codepage : 1250
Plugins : 
    ComparePlus (1.1)
    mimeTools (2.9)
    NppConverter (4.5)
    NppExport (0.4)

```

**Comment by donho** [comment]
@alankilborn 
Done. Thank you!

**Comment by ArkadiuszMichalski** [comment]
This looks like some regression (translate for these two items stop working from version 8.4.8). I check some earlier version like 8.4.7 (and others) and in them these two items were translated.

**Comment by alankilborn** [comment]
@donho 

Is it OK to change the obvious typo/misspelling along with a PR that fixes this issue?:

`changeLangTabDrapContextMenu` should be `changeLangTabDropContextMenu`

**Comment by donho** [comment]
@alankilborn 
> Is it OK to change the obvious typo/misspelling along with a PR that fixes this issue?:

Sure, no problem. Go ahead.
