### ISSUE TITLE
Workspace file SaveAs should default to same folder as existing workspace file location

### ISSUE THREAD

**Issue by alankilborn** [notepad-plus-plus/notepad-plus-plus#13086]
### Description of the Issue
See StR.

### Steps to Reproduce (StR) the Issue

Note for what follows:  **_The use of the "dot workspace" extension on a workspace filename is my own convention._**

1. On a Project Panel, create and save a .workspace file (e.g. `foo.workspace`) to a desired location on disk.
2. Create a new editor window tab and save it to disk, in a folder that is NOT the same as the folder used for the .workspace file in step 1.
3. Right-click the workspace and choose _Save As..._ (or _Save a Copy As..._) from the ensuing menu:
![image](https://user-images.githubusercontent.com/77065706/217947821-1ab7a0b4-b234-4b8f-a001-98c57fac14d5.png)

### Expected Behavior

I expect the standard Windows SaveAs dialog to open up with the directory of the existing workspace as the default, and the existing .workspace file to be seen in the files area of that dialog.

### Actual Behavior

The standard Windows SaveAs dialog opens up to the directory of the active file tab of the editor window.

### Debug Information
Notepad++ v8.4.9 (64-bit)
Build time : Jan 27 2023 - 03:11:16
Path : W:\npp.misc_NoBackup\Releases\npp.8.4.9\npp.8.4.9.portable.x64\notepad++.exe
Command Line : -titleAdd="8.4.9 64-bit"
Admin mode : OFF
Local Conf mode : ON
Cloud Config : OFF
OS Name : Windows 10 Enterprise (64-bit)
OS Version : 21H2
OS Build : 19044.2486
Current ANSI codepage : 1252
Plugins :
mimeTools (2.9)
NppConverter (4.5)
NppExport (0.4)
PythonScript (2)

**Comment by richlysakowski** [comment]
This is a bug, or at least an oversight of the correct expected behavior.

**Comment by donho** [comment]
@alankilborn 

> Actual Behavior
The standard Windows SaveAs dialog opens up to the directory of the active file tab of the editor window.

It's logical to initialize save dialog path to saved project folder and it's easy to fix it (please check #13936).
However, the new behaviour that you want might to break the feature that people use the last used directory.
So I'm not sure it should be done.

**Comment by alankilborn** [comment]
@donho 

>please check # 13936

Checked; works.  Thank you for your effort.

>might to break the feature that people use the last used directory.

If "last used directory" (LUD) is an absolute, it is OK.  ("absolute" meaning if you save something...anything... then wherever that was becomes your LUD)

Otherwise... then file tabs need their own LUD, workspace files need their own LUD, etc.  (too complicated to bother with).

**Comment by Yaron10** [comment]
@donho & @alankilborn,

> I expect the standard Windows SaveAs dialog to open up with the directory of the existing workspace as the default

That indeed makes sense. - The current Workspace should override the current doc in the editing view.
But, IMO, that is only true if "Follow current doc" is selected in "Preferences -> Default Directory".

Closed as I was typing. :)

**Comment by TheSimArchitect** [comment]
I agree that when you have an open file and you choose "Save As..." it should save on the same folder of the original file, not try to find the last used folder or anything else. You can add an option for Notepad++ to NOT have this behavior (or to HAVE this behavior, which is the most intuitive and functional as people frequently want to make editions to text files while saving with a different name on the same folder as the original to prevent losing previous versions).

When you deal with a large number of files spread across multiple folders the current behavior is extremely counter productive, besides being counter intuitive.

Hopefully you feel like fixing this or implementing is an option.
