### ISSUE TITLE
Recent file list broken?

### ISSUE THREAD

**Issue by astext** [notepad-plus-plus/notepad-plus-plus#13087]
Although installed in the default location on a Dell G3 at C:\Program Files\Notepad++

the most recent files list is (almost) never populated by the actual files that I last used. And if it does work, it's never the proper list of files that I last used, just a random pick from them with no apparent rhyme or reason. I have to manually gather my crop of files again every session. 

This wasn't always true but it's been many updates later that this has been broken on my platform, so I thought I'd report it.

On Windows 11 Home ver 2H2 and it's Notepad++ 8.4.9 (and at least >4-5 versions back).

I'll happily donate to get this looked at, and you can draw your own conclusions as to whether it's a user issue or nay.

kind regards,
Anthony

**Comment by alankilborn** [comment]
There's a popular misconception that files that are currently open in N++ tabs also belong in the recent file history -- is this your situation?

It should be fairly simple if it is malfunctioning as you say to write up some "steps to reproduce" that illustrate the problem, that others could then try to reproduce.

For me, it is working as I expect.

**Comment by astext** [comment]
No, I expect recent files to be populated by the files I had open in the previous session, by that I mean, after a shut down, none of my recently opened files get populated here at any time unless as previously noted, a very random one and certainly not the group of files I regularly use, consistently, each time I launch N++.

**Comment by alankilborn** [comment]
>I have to manually gather my crop of files again every session.

Do you have this setting as shown:

![image](https://user-images.githubusercontent.com/77065706/218236929-4d887472-3b3e-41c6-8d87-070d0fbd4500.png)

**Comment by astext** [comment]
Yes, that's my setting too. 
 
If n++ is working correctly, then this is something else, to do with my  anti-virus  app - a privacy setting that perhaps needs n++ to be whitelisted. I'm looking into that now.,

**Comment by alankilborn** [comment]
@astext I'm guessing your problem got solved; was it the anti-virus thing?
