### ISSUE TITLE
QoL: Support for user defined fold regions without needing to add a user defined language

### ISSUE THREAD

**Issue by Demopans** [notepad-plus-plus/notepad-plus-plus#13094]
Similar to how \<div> blocks would operate in HTML, but extended generally to languages that allow for comments such as C++.

Example behavior:
Before folding:
![a](https://user-images.githubusercontent.com/22843987/218229567-44714805-8f03-4d92-9639-3f683526dbb6.PNG)
After:
![b](https://user-images.githubusercontent.com/22843987/218229617-0d0310f9-4e3c-4146-877d-baeb51a9479f.PNG)

**Comment by rdipardo** [comment]
This was requested once before on [the user community forum][0].

As the replies try to explain, you can't easily change the behaviour of a [compiled C++ library][1], which is what Notepad++ uses for code highlighting.

Apps that read from "syntax" files (Vim, Sublime Text, VS Code, etc.) can be configured by simply editing some JSON or other config file. N++ has always been more of a "hacker's editor". If you want extend its capabilities, better learn C++.

[0]: https://community.notepad-plus-plus.org/topic/23088/region-support-for-languages
[1]:https://github.com/ScintillaOrg/lexilla
