### ISSUE TITLE
Closes after opening large file

### ISSUE THREAD

**Issue by msdev77** [notepad-plus-plus/notepad-plus-plus#13092]
### Description of the Issue
Npp closes automatically after approximately 3 to 9 seconds after opening a text file or immediately after clicking anywhere in the text fie.

### Steps to Reproduce the Issue
1. Open a file either by right clicking on it and selecting Open with Npp or drag the file into an open Npp window.
2. Wait for a few seconds or click anywhere in the file window.
3. Watch it close.

### Expected Behavior
Continues to stay open and allow edits.

### Actual Behavior
Closes after a few seconds or when clicked by mouse.

### Debug Information
Notepad++ v8.4.8   (64-bit)
Build time : Dec 24 2022 - 19:40:27
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : 
Admin mode : ON
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 10 Enterprise (64-bit) 
OS Version : 22H2
OS Build : 19045.2486
Current ANSI codepage : 1252
Plugins : 
    ComparePlugin (2.0.2)
    ComparePlus (1.1)
    CSScriptNpp (2.0.2)
    mimeTools (2.9)
    NppConverter (4.5)
    NppExport (0.4)

This behavior didn't start until after the last update and installing the following plugins: 
Compare v2.0.2, Compare Plus v1.1.0 and CS-Script v2.0.2.0.

Steps to correct the bug.
Open Npp.
Select 'Open Plugins Folder...' from the Plugins top menu.
Close Npp.
Delete the CS-Script sub-folder in the Plugins folder.
Reopen Npp and verify that the CS-Script Plugin is no longer on the Plugins menu.
Open several files one at a time.
Npp operates as normal.

**Comment by alankilborn** [comment]
>Steps to correct the bug.
Delete the CS-Script sub-folder in the Plugins folder.
Npp operates as normal.

You've solved it!
Please CLOSE this issue.

**Comment by rdipardo** [comment]
@msdev77,

> Admin mode : ON

Versions of CSScriptNpp before 2.0.3 are [known to make unsafe API calls](https://github.com/oleg-shilo/cs-script.npp/blob/8da9d888fce9420fd031993a2514e58005a59d6c/src/CSScriptIntellisense/Interop/NppExtensions.cs#L425-L430) when admin mode is active. Try upgrading to [the latest version](https://github.com/oleg-shilo/cs-script.npp/releases/tag/v2.0.3.0).

**Comment by msdev77** [comment]
I will upgrade to the latest version.  Thank you.

**Comment by Yaron10** [comment]
@msdev77,

Just curious: why are you using both ComparePlus and ComparePlugin? - ComparePlus is meant to *replace* ComparePlugin.
