### ISSUE TITLE
Double-clicking "Copy debug info into clipboard" puts "Copy debug info into clipboard" into clipboard

### ISSUE THREAD

**Issue by aybe** [notepad-plus-plus/notepad-plus-plus#13106]
### Steps to Reproduce the Issue

1. Double-click "Copy debug info into clipboard" 
2. Check your clipboard, it contains "Copy debug info into clipboard"  

### Expected Behavior

There should be the debug info in the clipboard.

### Debug Information

Notepad++ v8.4.8   (64-bit)
Build time : Dec 24 2022 - 19:40:27
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 10 Enterprise (64-bit) 
OS Version : 22H2
OS Build : 19045.2486
Current ANSI codepage : 1252
Plugins : 
    ComparePlugin (2.0.2)
    JSMinNPP (1.2202)
    mimeTools (2.9)
    NppConverter (4.5)
    NppExport (0.4)
    XMLTools (3.1.1.13)

**Comment by alankilborn** [comment]
A single click on the link suffices to copy debug info to clipboard.
Please CLOSE this issue.
