### ISSUE TITLE
ANSI file converted to UTF-8 is missing special characters

### ISSUE THREAD

**Issue by danifgxcom** [notepad-plus-plus/notepad-plus-plus#13116]
As far as I understood, an ANSI file can be converted to  UTF-8 with NO BOM without missing any special character.

I have a file in ANSI, with special accents (in Spanish).

![image](https://user-images.githubusercontent.com/16970877/218566362-75a9684f-15aa-47dd-84bf-2551915b04aa.png)

I used the menu Encoding --> Convert to UTF-8, but this is what I see:

![image](https://user-images.githubusercontent.com/16970877/218566494-2aec7068-bced-4b50-b03e-fac9a90819d4.png)

I no longer have the accented vowels (e.g. AUTOVÍA).

I also tried with the Settings --> Preferences --> New Document --> UTF-8 Apply to opened ANSI files. But that does not change anything.

![image](https://user-images.githubusercontent.com/16970877/218566750-0ee71a77-97ed-4027-a9f4-240c8e900110.png)

I have done this with other files and it worked perfectly. But with this one it is not possible.
For this one I used Microsoft Office - Excel, and it worked. But I cannot reproduce this with Notepad++.
![image](https://user-images.githubusercontent.com/16970877/218566937-e2af9271-648c-4846-8457-cb1471c81e49.png)

Does it make sense?

Thank you very much in advance.

Kindest regards, 
   Dani.

**Comment by alankilborn** [comment]
Please add Debug Info.
Is it possible to upload the problem file here?

**Comment by danifgxcom** [comment]
Hi Alan:
[VialesVigentesDistritosBarrios_20221003.csv](https://github.com/notepad-plus-plus/notepad-plus-plus/files/10726261/VialesVigentesDistritosBarrios_20221003.csv)

Yes, I can upload the file as it is:

Debug info:

**Comment by alankilborn** [comment]
When I try the file, it converts to UTF-8 and keeps the accented characters, both visually and at the byte-level.  This is just a data point; I'm sure it is happening the way you say it is for you, @danifgxcom .

My debug info:

Notepad++ v8.4.9   (64-bit)
Build time : Jan 27 2023 - 03:11:16
Path : W:\npp.misc\_NoBackup\Releases\npp.8.4.9\npp.8.4.9.portable.x64\notepad++.exe
Command Line : -titleAdd="8.4.9 64-bit" -multiInst
Admin mode : OFF
Local Conf mode : ON
Cloud Config : OFF
OS Name : Windows 10 Enterprise (64-bit) 
OS Version : 21H2
OS Build : 19044.2486
Current ANSI codepage : 1252
Plugins : 
    mimeTools (2.9)
    NppConverter (4.5)
    NppExport (0.4)
    PythonScript (2)

**Comment by danifgxcom** [comment]
Uhmmm, that's interesting...
For me it does convert to UTF-8 and removes the accented vowels in Spanish.
I have done this before with Notepad++ and it worked, but I recall that I also used Office for that.

But now I do not have access to an installable version of Excel and the online 365 version works differently.

As you can see from the screenshots, when I convert to UTF-8 it does miss the special characters... 
I will install a different version of Notepad++ and check what is going on.

Thanks a lot, Alan.
Your support is much appreciated.

**Comment by alankilborn** [comment]
>I will install a different version of Notepad++ and check what is going on.

I encourage you to try a portable version.
That way you can experiment without a potential bunch of reinstalls.

**Comment by danifgxcom** [comment]
Hi Alan,

I found it.

Actually you gave me the clue to identify what is going on.

From your debug info, your ANSI Code Page (ACP) is 1252 (standard Windows).
I had 65001.
The reason why I had that number is because the other day I was changing the language settings in my computer with Windows 11, and I touched the following settings:

![image](https://user-images.githubusercontent.com/16970877/218579236-4848b6d6-0e9e-42d1-9c96-1757ef3f9b33.png)


Administrative Language Settings: 

![image](https://user-images.githubusercontent.com/16970877/218579313-a3dcf9ed-fafe-4d73-9bf3-43c20a1d90df.png)

Change System Locale:
![image](https://user-images.githubusercontent.com/16970877/218579387-9208f8ae-ebf5-4903-80da-1df5bc67581b.png)


I used this "Beta: Use Unicode UTF-8 for worldwide language support" thinking that it would use UTF-8 in general.
That changed the ACP to 65001 and it makes Notepad++ to be unable to properly convert to UTF-8.

I reverted the settings, tried again and now it works:

![image](https://user-images.githubusercontent.com/16970877/218579684-e7a56c62-fffb-4e93-adea-689a9706a15e.png)


I believe that this is an interesting thing, but you may think that it is better to remove the thread.
It is entirely up to you but I am really thankful since now I do understand what is going on and the file works.

A big thank you.

Kindest regards,
   Dani.

**Comment by alankilborn** [comment]
Glad that it is solved.
Issue threads don't get deleted; it may be of interest to someone in the future.
But you can CLOSE it.

**Comment by danifgxcom** [comment]
> > I will install a different version of Notepad++ and check what is going on.
> 
> I encourage you to try a portable version. That way you can experiment without a potential bunch of reinstalls.

BTW I tried the portable version, it did not work... The issue is with that "beta setting" that changes the ACP to 65001.
But it is a good advice indeed to test different version without installing them. I copy that! ;)

**Comment by danifgxcom** [comment]
The ANSI Code Page gets changed to 65001 with the new beta setting in Windows 11 for UTF-8 worldwide format.
Unchecking that and reverting to the standard ACP 1252 makes Notepad++ convert ANSI to UTF-8 as expected.

I close this as this is no longer an issue.
