### ISSUE TITLE
MISC. Show only filename in title bar

### ISSUE THREAD

**Issue by AnaTrav1s** [notepad-plus-plus/notepad-plus-plus#13124]
### Show only filename in title bar
upon enabling the option, the app name and [admin] still remains

![image](https://user-images.githubusercontent.com/100277491/218794026-992d5047-11b0-4190-9f62-10b07d7ddab5.png)
![image](https://user-images.githubusercontent.com/100277491/218794070-cb888d30-4669-4d38-85b0-a6d44b846f07.png)

**Comment by alankilborn** [comment]
It is meant to be a choice between "full pathname" and "only filename".

Thus, the difference between:

`c:\users\foo\downloads\myfile.txt - Notepad++ 8.4.9 [Administrator]`

and 

`myfile.txt - Notepad++ 8.4.9 [Administrator]`

It was never meant to control whether or not anything after the `-` appears.
