### ISSUE TITLE
libcurl vulnerabilities in v8.4.9

### ISSUE THREAD

**Issue by K2Manning** [notepad-plus-plus/notepad-plus-plus#13139]
mkruntest identified libcurl version 7.79.1-DEV in the latest version of NP++ (v8.4.9)

per curls website (https://curl.se/) v7,88.0 is the latest available and should mitigate the vulnerabilities identified here (https://curl.se/docs/vuln-7.79.1.html)

Is it possible for development to upgrade and test libcurl to the latest verion within NP++ to mitigate all open vulnerabilities?

Thank you 
Please have a great day

**Comment by chcg** [comment]
N++ itself doesn't use libcurl, but the update tool wingup, so likely the better place is https://github.com/notepad-plus-plus/wingup/issues

**Comment by pryrt** [comment]
since this issue was left open pending the wingup issue, I thought someone should provide a cross-link to notepad-plus-plus/wingup#36 , which is the corresponding issue over there.

**Comment by pryrt** [comment]
The updated wingup was included in the [Notepad++ v8.6 release](https://community.notepad-plus-plus.org/topic/25165/notepad-v8-6-release-20th-year-anniversary), including libcurl 8.4, which solves the security vulnerability mentioned here.
