### ISSUE TITLE
File -> Save Session should prompt with current session file name

### ISSUE THREAD

**Issue by alankilborn** [notepad-plus-plus/notepad-plus-plus#13141]
### Description of the Issue
See StR.

### Steps to Reproduce (StR) the Issue

1. On _File_ menu, select _Save Session..._
2. Supply a file/pathname for the session file and continue on with the save process
3. On _File_ menu, select _Save Session..._ again, and observe the SaveAs dialog that appears

### Expected Behavior

I expected to be prompted in the _File name_ area with the same filename (and path) that I specified in step 2.

Note that I only expect this behavior if I've previously saved or loaded a session, otherwise existing behavior (see `Actual Behavior`, below) is appropriate.

Note that if Notepad++ has been started with the `-openSession` command-line argument, I'd expect to see the file/pathname of that file in the _File name_ box in this situation, as well.

### Actual Behavior
_File name_ box is empty:
![image](https://user-images.githubusercontent.com/77065706/219178024-581e08b9-fa40-4320-b7d3-066b6e3334a3.png)

### Debug Information
Notepad++ v8.4.9   (64-bit)
Build time : Jan 27 2023 - 03:11:16
Path : W:\npp.misc\_NoBackup\Releases\npp.8.4.9\npp.8.4.9.portable.x64\notepad++.exe
Command Line : -titleAdd="8.4.9 64-bit" -multiInst
Admin mode : OFF
Local Conf mode : ON
Cloud Config : OFF
OS Name : Windows 10 Enterprise (64-bit) 
OS Version : 21H2
OS Build : 19044.2486
Current ANSI codepage : 1252
Plugins : 
    mimeTools (2.9)
    NppConverter (4.5)
    NppExport (0.4)
    PythonScript (3.0.14)

**Comment by donho** [comment]
"Save session..." command is not designed as Save opened file - that user can simply save, save as, or save a copy...
So in order to keep its simple logic, let's keep its unitary action for not maintaining a complex logic (especially with "Load session...").

**Comment by alankilborn** [comment]
@donho 

I think in my original request here, I was looking for a way to save changes to a previously opened session WITHOUT adding another _File_ menu entry, e.g., _Save Session_ (no `...`).  As an alternative to the rejected idea above, would you consider adding that menu entry?

Thus, perhaps there would be:

_Load Session..._
_Save Session_                            <--- new entry
_Save Session As..._                     <--- slightly renamed entry

Oh, wait, you said:

>"Save session..." command is not designed as Save opened file - that user can simply save, save as, or save a copy...

Hmm, without quick and easy way to save session currently in...session handling remains clunky to use.
And thus I can't use them, without writing yet another workaround script; so many of these...
:-(

**Comment by donho** [comment]
Among "no session", "default unnamed session", "saved session" and "loaded session", there's no trivial logic to do what you demanded without drawing users' confusion. That's the reason of rejection.

**Comment by alankilborn** [comment]
>what you demanded

Oh no, no demands...only suggestions that I feel strongly about. :-)

Hmm, I would think that if the default-unnamed session is in effect, a proposed _Save Session_ (no `...`) would be greyed/disabled.  If a named session is in effect (via `-opensession` command line param or prior _Load Session..._), then _Save Session_ would save that (in preparation for the next _Load Session...`).

But, OK, I can only suggest. :-)
