### ISSUE TITLE
Wildcard character

### ISSUE THREAD

**Issue by Robi8O** [notepad-plus-plus/notepad-plus-plus#13147]
Good morning,
Congratulations on your program.

I have a doubt, how do you search with the joker

Example

"brand": as
"brand":aw
"brand": po
"brand": c

and I have to replace

"brand":00

can anything be done?

Thank you

**Comment by alankilborn** [comment]
Questions belong here:  https://community.notepad-plus-plus.org/

The site you are currently on is for creating "issues" which are reported problems with the software.
Please don't ask general usage questions here.
You may also want to consult the user manual, go to the `?` menu in Notepad++ and choose _Notepad++ Online User Manual_ before asking questions, anywhere.

**Comment by alankilborn** [comment]
Please CLOSE this issue.
