### ISSUE TITLE
Notepad++ Will not open files with space in name when clicking with mouse

### ISSUE THREAD

**Issue by Yanta0205** [notepad-plus-plus/notepad-plus-plus#13153]
### Description of the Issue
After upgrading to v8.4.9 when I click to open a file with spaces in the name I get an error that the file does not exist do I want to create it? I have associated some file types with Notepad++ such as .txt, .disc and .nfo

### Steps to Reproduce the Issue
1. I was on 8.4.8. Install 8.4.9 over the top
2. set association with registry settings;
`REG ADD "HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Explorer\FileExts\.txt\OpenWithList" /v b /d notepad++.exe /t REG_SZ /f`
`REG ADD "HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Explorer\FileExts\.nfo\OpenWithList" /v b /d notepad++.exe /t REG_SZ /f`
`REG ADD "HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Explorer\FileExts\.disc\OpenWithList" /v b /d notepad++.exe /t REG_SZ /f`

Note: I also add an entry for Notepad, and set the MRUList to ba so Notepadd++ is first choice.

### Expected Behavior
The file would opened with Notepad++

### Actual Behavior
An error dialog is displayed for each part of the file name. For example, if file name is one two three.txt I will get three errors then notepad++ will open witrh an empty document

### Debug Information
Notepad++ v8.4.9   (64-bit)
Build time : Jan 27 2023 - 03:11:16
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : "K:\PostInstall\PostInstall.cmd"
Admin mode : ON
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 10 Enterprise LTSC 2021 (64-bit) 
OS Version : 21H2
OS Build : 19044.2486
Current ANSI codepage : 1252
Plugins : 
    mimeTools (2.9)
    NppConverter (4.5)
    NppExport (0.4)

I can open the file by right clicking on the filename and selecting "Edit with Notepad++"

![npp_error](https://user-images.githubusercontent.com/81943074/219516223-e1f9c8ee-acd1-45d7-b301-baf65d3e747b.png)

**Comment by alankilborn** [comment]
Known issue; see https://github.com/notepad-plus-plus/notepad-plus-plus/pull/13027
Will be fixed with the release of 8.5.
Please CLOSE this issue.

**Comment by Yanta0205** [comment]
No problems. Thank you.
