### ISSUE TITLE
Suspected code error calling doOpen() 

### ISSUE THREAD

**Issue by alankilborn** [notepad-plus-plus/notepad-plus-plus#13150]
Not really sure how to log an issue against what I see as an error in the code, if I can't (or don't know how to) make it translate into a user-level bug.

Here's the problem I see, in this function call to `doOpen`:

https://github.com/notepad-plus-plus/notepad-plus-plus/blob/9627494043d3ace4d4b5ab04b85fbdd0bd5a87a5/PowerEditor/src/NppIO.cpp#L1994

Here's the function definition:

https://github.com/notepad-plus-plus/notepad-plus-plus/blob/9627494043d3ace4d4b5ab04b85fbdd0bd5a87a5/PowerEditor/src/NppIO.cpp#L169

Here's the function declaration, so one can see the default argument values:

https://github.com/notepad-plus-plus/notepad-plus-plus/blob/9627494043d3ace4d4b5ab04b85fbdd0bd5a87a5/PowerEditor/src/Notepad_plus.h#L164

As is fairly obvious, something related to "readonly" is being passed as something related to "recursing".

I don't know what to do with this, because I don't know what recursion has to do with opening a file from the file-open dialog.  I can understand the idea of "readonly" when opening a file, but I don't see a way for the user to indicate that they want to open a file as readonly from the file-open dialog.

**Comment by rdipardo** [comment]
> Not really sure how to log an issue against what I see as an error in the code, if I can't (or don't know how to) make it translate into a user-level bug.


1. Locate all the calls to `doOpen` with multiple arguments:

~~~sh-session
$ git grep -nEo "[^:]doOpen\(.*,\s?\w+(\W\w+)?" -- *.cpp

PowerEditor/src/Notepad_plus.cpp:6438: doOpen(pFn, recursive, readOnly
PowerEditor/src/NppIO.cpp:1992: doOpen(fns.at(i).c_str(), fDlg.isReadOnly
PowerEditor/src/NppIO.cpp:2111: doOpen(pFn, false, false, session._mainViewFiles[i]._encoding, session._mainViewFiles[i]._backupFilePath.c_str(), session._mainViewFiles
PowerEditor/src/NppIO.cpp:2113: doOpen(pFn, false, false, session._mainViewFiles
PowerEditor/src/NppIO.cpp:2117: doOpen(pFn, false, false, session._mainViewFiles[i]._encoding, session._mainViewFiles[i]._backupFilePath.c_str(), session._mainViewFiles
PowerEditor/src/NppIO.cpp:2222: doOpen(pFn, false, false, session._subViewFiles[k]._encoding, session._subViewFiles[k]._backupFilePath.c_str(), session._subViewFiles
PowerEditor/src/NppIO.cpp:2224: doOpen(pFn, false, false, session._subViewFiles
PowerEditor/src/NppIO.cpp:2234: doOpen(pFn, false, false, session._subViewFiles[k]._encoding, session._subViewFiles[k]._backupFilePath.c_str(), session._subViewFiles


~~~

2. Ignore any call site where the `isReadOnly` parameter is a constant value (e.g. `false`)

3. Set breakpoints on the remaining lines and attach `notepad++.exe` to a debugger

**Comment by alankilborn** [comment]
@rdipardo 

I feel chided.  :-)
I feel like you said "Do some basic debugging."
That's fine to chide me.  I have a thick skin.
And you're right.

I have looked deeper since posting yesterday...I just have to decide where I want to go with this...

**Comment by alankilborn** [comment]
So I have completed my deeper look at this.
There are no paths through the chain of code in question where the value of `isRecursive` is going to matter.
Also, `isReadOnly` _could_ matter, but it doesn't as something "later on" will mark the loaded file tab as non-modifiable anyway, if the file being opened is ro in the file system.
I still don't have a STR that will demonstrate a bug that the user will see from this.
But, this is still "wrong" so I will create a fix for it.
If the author declines the fix because he can't demonstrate a user-level anomaly in the original code, so be it.
