### ISSUE TITLE
Are there plans to support macOS ?

### ISSUE THREAD

**Issue by hoochanlon** [notepad-plus-plus/notepad-plus-plus#13154]
On macOS, I couldn't find a lightweight text editor that worked well.

**Comment by hoochanlon** [comment]
Current solution:Used mas install app in Apple Store Mac. So-so.

```
brew install mas &&  mas lucky coteditor
```

**Comment by Ramalama2** [comment]
there is coteditor, sublime text...
but none of those can even reach notepad++, i would love notepad++ on mac, since there is anyway arm support :-(

But this means also more work to support another platform.
How was it? More Productive, More Money, More Donation, More? :-)
