### ISSUE TITLE
Left bitwise shift operator (<<) shouldn't be treated the same as HERE Q in bash .sh

### ISSUE THREAD

**Issue by GregTonoski** [notepad-plus-plus/notepad-plus-plus#13151]
Steps to reproduce:
1) Type: 
```
echo $(( x << n ))
anything
anything
n
```
2) save a file as .sh

Actual result
All text after "<< n" until the next "n" is highlighted as if it was HERE Q and n was a delimiter.

Notepad++ v8.4.8 64-bit

**Comment by rdipardo** [comment]
Code highlighting is provided by a 3rd-party library: https://github.com/ScintillaOrg/lexilla/issues

**Comment by GregTonoski** [comment]
The fix is ready to be merged ("included in release 5.2.5").

**Comment by rdipardo** [comment]
@notepad-plus-plus, this was fixed in Lexilla 5.2.5 and can be closed: ScintillaOrg/lexilla@682f573d28eb9863a98f78476626bc3901952b6a

**Comment by chcg** [comment]
Fix is available since N++ release  v8.5.4
