### ISSUE TITLE
SQL Language Option - Apostrophe ' in Square Brackets [] not escaped

### ISSUE THREAD

**Issue by KeithHenselNOV** [notepad-plus-plus/notepad-plus-plus#13160]
### Description of the Issue
Apostrophes are not escaped in square brackets, resulting in the syntax highlighting for .sql files breaking.

### Steps to Reproduce the Issue
The below code adds a column with an apostrophe in the name.
--alter table Default_Test_Table add [bad_column'] [nvarchar](50) NULL
update Default_Test_Table set [bad_column'] = 'asdf'
update Default_Test_Table set [bad_column''] = 'asdf'

### Expected Behavior
In other editors like SSMS (tested with SQL Server Management Studio 19), this code will have the proper syntax highlighting, and the second line will execute correctly.

### Actual Behavior
Notepad++ doesn't escape the ', resulting in syntax highlighting breaking after that point in the file (in the above example, the third line will display incorrectly).

### Debug Information
Notepad++ v8.4.9   (64-bit)
Build time : Jan 27 2023 - 03:11:16
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : "C:\[REDACTED].sql"
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 10 Enterprise (64-bit) 
OS Version : 21H2
OS Build : 19044.2604
Current ANSI codepage : 1252
Plugins : 
    mimeTools (2.9)
    NppConverter (4.5)
    NppExport (0.4)

First screenshot is Notepad++ (third line not displaying correctly)
![NPP_01](https://user-images.githubusercontent.com/124633337/219817156-7173f94c-9802-4538-b3f4-357f00fdd309.png)

Second is SSMS (displaying correctly)
![NPP_02](https://user-images.githubusercontent.com/124633337/219817159-1f002771-e064-46e3-ab26-c29b103fa664.png)

**Comment by rdipardo** [comment]
> tested with SQL Server Management Studio 19

Notepad++ does not have built-in support for Transact-SQL: https://github.com/notepad-plus-plus/notepad-plus-plus/issues/12610#issuecomment-1340297100

In the meantime there's [a UDL](https://github.com/notepad-plus-plus/userDefinedLanguages/blob/master/UDLs/T-SQL-MSServer2008r2_bySergeyIvanov.xml) (for MS SQL Server 2008) that may be more suitable.

**Comment by ArkadiuszMichalski** [comment]
SciTE for `SQL` display this correctly, but not for MS SQL.

**Comment by rdipardo** [comment]
@ArkadiuszMichalski,

> SciTE for `SQL` display this correctly, but not for MS SQL.

Here is what SciTE does with the OP's query when the MS SQL lexer is enabled (*1):

![scite-mssql](https://user-images.githubusercontent.com/59004801/219922716-be5a45a0-2afd-4b4d-80cd-8ecb1286be59.png)

Now watch as I select "ordinary" SQL from the lexer menu:

![scite-sql](https://user-images.githubusercontent.com/59004801/219922724-f3c99690-beb6-4782-aa05-cfc8ae5c1061.gif)


---
(*1) Extract this archive, start SciTE, and open the `*.tsql` file: [issue-13160.zip](https://github.com/notepad-plus-plus/notepad-plus-plus/files/10775980/issue-13160.zip)
The custom `SciTE.properties` will override any existing file mapping as long as it's in the same directory as the SQL script.

**Comment by ArkadiuszMichalski** [comment]
Right, looks like I test something in past and don't delete additional file `mssql.properties`.

Maybe Notepad++ should support MS SQL and MySQL language because we have such lexers.

**Comment by KeithHenselNOV** [comment]
I would like to clarify, should the behaviour between Oracle SQL and MSSQL be different in this case?
