### ISSUE TITLE
window Command line Arguments is untranslatable

### ISSUE THREAD

**Issue by conky77** [notepad-plus-plus/notepad-plus-plus#13166]
### Description of the Issue

Window "Command line Arguments" is untranslatable
 
### Steps to Reproduce the Issue

1. click on "?", "Command line Arguments"
2. All strings are untranslated

### Expected Behavior

It should be possible to translate:
- title
- parameter description: every parameter should have a different entry in english.xml (string with only explanation, without parameter name)
- buttons

### Actual Behavior

All strings are untranslated

### Debug Information

Notepad++ v8.4.9   (64-bit)
Build time : Jan 27 2023 - 03:11:16
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : 
Admin mode : ON
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 11 (64-bit) 
OS Version : 22H2
OS Build : 22621.1265
Current ANSI codepage : 1252
Plugins : 
    ComparePlugin (2.0.2)
    CSVLint (0.4.6.2)
    DSpellCheck (1.4.24)
    JsonTools (4.8.1)
    mimeTools (2.9)
    NppConverter (4.5)
    NppExport (0.4)
    NPPJSONViewer (2.0.4)
    NppXmlTreeviewPlugin (2)
    XMLTools (3.1.1.13)

![immagine](https://user-images.githubusercontent.com/59116246/219875934-0fbf03d0-c522-48d1-a75d-a7bef748b008.png)

**Comment by conky77** [comment]
#8972

**Comment by ArkadiuszMichalski** [comment]
@conky77 

You can test if [PR 13269](https://github.com/notepad-plus-plus/notepad-plus-plus/pull/13269) works as expected.

**Comment by conky77** [comment]
@ArkadiuszMichalski Since I can't compile the project and test, I can just check the english.xml. From the point of view of a translator should be ok: you can translate all strings and it is not possible to miss or confuse strings.

**Comment by ArkadiuszMichalski** [comment]
@conky77 
You don't need compile yourself, just use build from AppVeyor:
https://ci.appveyor.com/project/donho/notepad-plus-plus/builds/46369591

Instruction:
https://github.com/notepad-plus-plus/notepad-plus-plus/wiki/Testing#using-a-pull-request-pr-build-version-of-notepad

**Comment by conky77** [comment]
> @conky77 You don't need compile yourself, just use build from AppVeyor: https://ci.appveyor.com/project/donho/notepad-plus-plus/builds/46369591
> 
> Instruction: https://github.com/notepad-plus-plus/notepad-plus-plus/wiki/Testing#using-a-pull-request-pr-build-version-of-notepad

I tried translating some strings and making a variation to all items, and it looks good. Thanks
![image](https://user-images.githubusercontent.com/59116246/222649137-599cfe8b-a2ff-4c5f-b78e-f8380245fdd1.png)

**Comment by conky77** [comment]
@ArkadiuszMichalski
"ok" is still untranslatable

**Comment by ArkadiuszMichalski** [comment]
Actually we don't translate "OK" button in any message box.

**Comment by donho** [comment]
It's good to make translatable the most of controls. But for some are difficult to translate as this one I would say no, for the following reasons:
1. code maintenance: making it translatable makes code maintenance more difficult. The PR #13269 make code more complicated and hard to maintain (for adding or deleting parameter items)
2. missing information: this dialog could be translated in one big string (different from the way of PR #13269). In this case while the translation is not sync with modified content of this dialog, users will loose some information.

For above reasons, I prefer to keep this dialog untranslated.

**Comment by ArkadiuszMichalski** [comment]
Because of the 2 point I had to do such combinations. Well, but it will be easiest to keep everything in the original English.
