### ISSUE TITLE
style configuration

### ISSUE THREAD

**Issue by alrutaimi** [notepad-plus-plus/notepad-plus-plus#1316]
Hi there it's really frustration, I had asked to sort out my issue but I didn't get relevant answer. I'm trying to change from plain text which is standard to a color coding text. I reinstall twice and I tried to change things from "sitting, style configuration, language, but I just gave up. could you please help. many thanks

**Comment by dail8859** [comment]
Not sure what you mean. You should be able to select an option under the Language menu and it will highlight your code.

**Comment by dail8859** [comment]
![menu](https://cloud.githubusercontent.com/assets/3694843/12079396/a0d6646c-b205-11e5-9675-c8aea05af6a4.png)

**Comment by alrutaimi** [comment]
![imag0064](https://cloud.githubusercontent.com/assets/16420310/12079453/81021ca4-b231-11e5-8c69-e6f00f6b62ad.jpg)
I'm using windows 10, I reinstalled notepad++ twice, I installed custom-theme. I fiddled with style con but nothing changed.

**Comment by dail8859** [comment]
In your style configurator make sure you don't have the global override enabled.

**Comment by dail8859** [comment]
You can also delete your `stylers.xml` file most likely located in your APPDATA directory (no idea where Win10 stores that). This will reset *all* style settings.

**Comment by alrutaimi** [comment]
![imag0065](https://cloud.githubusercontent.com/assets/16420310/12079539/aa7775fe-b234-11e5-92bb-5ecdf6e7e784.jpg)

Many thanks

**Comment by alrutaimi** [comment]
how to set global override disabled.
thanks

**Comment by alrutaimi** [comment]
I really appreciated at last sorted. thanks for your assistant.

**Comment by dail8859** [comment]
If everything is working fine now you can close this issue.
