### ISSUE TITLE
Notepad++ v.8.4.9 Find & Replace with simple regular expressions doesn't work in file of 49 MB

### ISSUE THREAD

**Issue by KiaraValloti** [notepad-plus-plus/notepad-plus-plus#13164]
### Description of the Issue

Find & Replace with simple regular expressions doesn't work in file of 49 MB
### Steps to Reproduce the Issue

1. Click Search/Replace... 
2. Click Tab Find in Files
3. Find what (\d*);(\d*):(\d*):(\d*)
4. Replace with \1;\2:\3
5. Directory choose the directory where you unzipped the attached .csv file
6. Search Mode Regular expression
7. Click Replace in Files
8. You obtain 0 occurrences were replaced, you should obtain 948 occurrences
9. The same holds for tab Replace clicking Replace All
10. Open the file, cut off the first half of the text file, now its size is about 23 MB, repeat the experience on the last part, you obtain 948 occurrences
### Expected Behavior
You should obtain 948 occurrences of  replacement

### Actual Behavior
You should obtain 0 occurrences of  replacement

### Debug Information

Notepad++ v8.4.9   (64-bit)
Build time : Jan 27 2023 - 03:11:16
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : "D:\all.ibdd\data\CME.GBP\CME.GBP_1.csv"
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 10 Home (64-bit) 
OS Version : 1803
OS Build : 17134.1130
Current ANSI codepage : 1252
Plugins : none

[CME.GBP_1.zip](https://github.com/notepad-plus-plus/notepad-plus-plus/files/10773812/CME.GBP_1.zip)

**Comment by wallrik** [comment]
I tried replicating this, and there is indeed some type of error or timeout when I try your pattern.

However, if I change the regex to anchor at the start of each line, like so `^(\d*);(\d*):(\d*):(\d*)`, the replacement succeeds with 948 replacements. 👍

**Comment by alankilborn** [comment]
>You obtain 0 occurrences were replaced

Do you happen to get this thing showing up when it occurs?:

![image](https://user-images.githubusercontent.com/77065706/219977552-6c54ebce-bb2f-4ccc-a794-0cac26440447.png)

**Comment by KiaraValloti** [comment]
> > You obtain 0 occurrences were replaced
> 
> Do you happen to get this thing showing up when it occurs?:
> 
> ![image](https://user-images.githubusercontent.com/77065706/219977552-6c54ebce-bb2f-4ccc-a794-0cac26440447.png)
No,I don't. You can see what I obtain.
![Untitled](https://user-images.githubusercontent.com/125733001/220369243-b4f1bc2c-cc34-4356-bf1b-6f1536e77852.png)

**Comment by jofon** [comment]
The Replace buttons don't show the error, but if you try with a Find you'll see the tooltip that alankilborn mentioned. The specific error in your case is from boost's regex: "The complexity of matching the regular expression exceeded predefined bounds. Try refactoring the regular expression to make each choice made by the state machine unambiguous. This exception is thrown to prevent "eternal" matches that take an indefinite period time to locate."
It's failing on the Find step, and doesn't get to the Replace part. The easiest solution is a "better" regex as wallrik mentioned.

**Comment by Denidil** [comment]
> complexity

I'm experiencing this bug now on purely search expressions that used to work fine.  fairly simple ones like

(LOG BEGIN|New join|AddNode|EvictNode|\[IM\] got event)

these regexes used to work fine and i used them all the time.  if i turn on Match Case they work again, though that is mildly annoying as I need to go through them and check the the cases are always right now
