### ISSUE TITLE
[Feature Request] - Option to hide prompt when closing an unsaved file

### ISSUE THREAD

**Issue by vbergaaa** [notepad-plus-plus/notepad-plus-plus#13178]
### Description of the Issue
Needing to close multiple tabs that you don't want to save changes to is tedious due to the multiple prompts that appear when trying to close these tabs

### Use Case
I often use notepad++ as a scrapbook to write down notes I need to store for a limited time. The duration could range from 10s to a week.
When needing to create a note, I open Notepad++ and create a new tab to store the information. The note is named 'New n' for the duration of it's life, and because I know it's a temp file, I don't want to save it, I just rely on Notepad++ to store it for it's duration.
I might create 10-20 tabs like this during a day. This quickly builds up, and at so at the end of the day (or week), I often go through each file and decide if it's ready to be deleted or not.
If its something I want to keep for another day, I go to the next tab, if not, I hit the x to delete it, then have to navigate to the prompt to hit 'no' because it's unsaved.
This is the tedious part and the part I wish I didn't have to do. I'm more than aware I'm deleting an unsaved file and that I'll be losing those changes, having a prompt appear in the middle of the window every time is unnecessary to me. 

### Proposed Feature
Add some type of optional way that a user can delete the file without being prompted about losing the unsaved changes
A few possible ideas (with my prefered one at the top):
- Hold Shift while clicking close to close without prompt (and have a tooltip when the prompt appears saying 'hold shift while clicking to force delete without this prompt' (Discord does this and it's very effective).
- A checkbox (or two) on the prompt that says ("do not show this prompt again" and/or "do not show this prompt again for new files")
- A user preference you can navigate to that allows the prompt to not appear for new files.

Thank you for your consideration

**Comment by alankilborn** [comment]
>Hold Shift while clicking close to close without prompt

Seems like a good idea.

**Comment by doug1234** [comment]
I was able to add the shift+click feature @alankilborn but do you think it is a useful addition without some keyboard way of doing it?  Also, how would you document the feature's existence?

**Comment by alankilborn** [comment]
@doug1234 

>but do you think it is a useful addition without some keyboard way of doing it

I'm not a good judge of this.  :-)
The procedure is to submit a PR for the feature and let the Notepad++ author decide.

>how would you document the feature's existence?

In the Notepad++ user manual, but no point in talking about that unless a change is going to be accepted.

Good luck.

**Comment by doug1234** [comment]
Thank you!  I will get a PR together and see.

**Comment by alankilborn** [comment]
>I will get a PR together and see.

Be sure to follow the instructions in CONTRIBUTING.md.

**Comment by donho** [comment]
I personally don't like this idea - it's above all data security to me.
Let's see if there are the similar request coming.

**Comment by avishayp** [comment]
Elaborating more on why this feature is required.
I normally have dozens++ open tabs in npp (for reason as mentioned above by OP). If I now click close by mistake - there's no fallback except from:

1. Clicking `cancel` X number of open files OR
2. Killing npp from taskmngr

This is a serious usability issue affecting all npp users on windows who open hundreds of unsaved files... a population of min 2 people.

**Comment by alankilborn** [comment]
@avishayp You are describing a different scenario than the one presented by this issue.  You should create a new issue.

**Comment by donho** [comment]
I don't see it as a good behaviour. This feature won't be implemented.

**Comment by donho** [comment]
Instead, please use the feature of #13776
