### ISSUE TITLE
N++ 849 not staying open

### ISSUE THREAD

**Issue by Illegit** [notepad-plus-plus/notepad-plus-plus#13174]
### Description of the Issue
when running N++ 849 it doesn't stay open

### Steps to Reproduce the Issue
Just open it
1. 
2. 
3. 

### Expected Behavior
stay open

### Actual Behavior
it closes after a while (10-60 sec about)

### Debug Information
I install 489, 488, 484, all of them experienced the same situation (I use w11)

**Comment by alankilborn** [comment]
Supply _Debug Information_ by following instructions, or please CLOSE this issue.
