### ISSUE TITLE
Document map overlay stuck to first monitor

### ISSUE THREAD

**Issue by Thomas14** [notepad-plus-plus/notepad-plus-plus#1317]
Hello,

Moving Notepad++ to another monitor using the <kbd>Windows</kbd> + <kbd>Shift</kbd> + <kbd>►</kbd> shortcut causes the document map overlay to stay behind on the first monitor.

Here's a screenshot showing the issue:

![npp_document_map_stuck](https://cloud.githubusercontent.com/assets/6246893/12080796/4ad10862-b267-11e5-88e0-c84ac473c476.png)

The overlay will stay there until I minimize, and then maximize the window.

Notepad++ 6.8.8

**Comment by dail8859** [comment]
Reported #1247

**Comment by wolf99** [comment]
@dail8859 this appears to actually be a slightly different issue than #1247, That issue involves desktops. This issue involves monitors that are displaying the one desktop that is split over two screens.

**Comment by wolf99** [comment]
Additionally I have noticed that if I put focus on the document map and then use the key combo (WinKey + Shift + LArrow/RArrow) to have an application switch screens (not desktops) then **only** the overlay switches, leaving the application itself behind.

**Comment by dail8859** [comment]
The underlying bug is still probably the same though.

**Comment by kjalsk** [comment]
This is still happening for me, but I found some stuff that might shed some light on the underlying issue.
When you click on the document map the main Notepad++ goes out of focus. If I displace the document map I am able to edit the text of the code through the smaller text viewer under the document map, albeit not properly. If I write a character anywhere in the code, the next will always be written on the first position of the document.
Also the document map still works as intended when displaced.
The document map seems to be treated like a seperate window.
Finally if I switch files the document map returns to its proper position.
