### ISSUE TITLE
Change "Replace by" wording in Tab Settings

### ISSUE THREAD

**Issue by alankilborn** [notepad-plus-plus/notepad-plus-plus#13186]
### Description of the Issue
It is possible for a user to misinterpret the meaning of the _Replace by space_ control on _Settings_ (menu) > _Preferences..._ > _Language_ > _Tab Settings_.

The use of "replace by" could be interpreted to mean that, when the box is transitioned from unchecked to checked by the user, a replace (in the sense of _Search_ (menu) > _Replace..._ > _Replace All_) will be executed for the current document.

Ref.: #13182

Suggestions for change:

* _Replace by space_ --> "Tab press inserts space(s)"
* _Replace by space_ --> "Tab key inserts space(s)"

### Debug Information
Above comment made on behavior current to N++ v. 8.4.9.

### Screenshot
![image](https://user-images.githubusercontent.com/77065706/220342715-fc5b41e3-668d-455c-bdaa-a5b9b58bd217.png)

**Comment by ArkadiuszMichalski** [comment]
But `Tab size` can also be changed from `4` to another value, and it doesn't mean conversion in the whole document. For me the current form is clear. Well, but if there is space and the new description will be more precise, it may be worth changing.

**Comment by alankilborn** [comment]
@ArkadiuszMichalski

Why did you tag this with a "translation" label?
It isn't a translation issue.
If it is accepted and implemented then the code and `english.xml` will be changed.
Only AFTER that point does it becomes a translation issue.
Or do I misunderstand the usage of the "translation" label?

>For me the current form is clear.
Apparently it is not clear for all users.  Sure it is impossible to satisfy everyone, but sometimes it is best to reflect and think: "Could this be improved and is it worth it to do so?"  In this case, my opinion is yes.

**Comment by pryrt** [comment]
I would vote for "Tab key inserts space(s)".  

(And I am not offended by the "translation" label, because changing this will _affect_ translation: looking at the other issues that have that tag, it seems to be both submissions for translation, and changes that will create a need for translations to be updated; since this is changing the English phrasing, it creates a need for the translators to assess whether there is the same translation need in other languages, or whether their existing phrasing already leaves no ambiguity.)

**Comment by alankilborn** [comment]
>And I am not offended by the "translation" label

Well, "offended" would not describe my reaction either. :-)
But my conception of the "translation" label is that it cues translators that something needs translating (maybe I'm wrong?).  As nothing has been changed (yet) on this, why cue them?
It perhaps also makes devs gloss over an issue with such a label ("...purely a translation issue...").

**Comment by ArkadiuszMichalski** [comment]
>But my conception of the "translation" label is that it cues translators that something needs translating (maybe I'm wrong?). 

Not so strictly, also if we are discussing the choice of a better name. Here we basically do not modify the mechanism of the action, only its name, so marking it with this label makes sense. In addition, it is easier to search for such issues marked with a common label. After some time such issues are pushed down by newer ones and then they are harder to find. Thanks to this label with one click we get a list of open problems and we can choose which one is worth (or we can) fix.

**Comment by LexaGV** [comment]
+1000000 for "Tab key inserts space(s)" - THIS is real action which happen underneath! Only pressing key makes spaces, existing 0x09 stay at place.

**Comment by sXNA** [comment]
maybe fix can be included in this https://github.com/notepad-plus-plus/notepad-plus-plus/pull/13177

**Comment by alankilborn** [comment]
>maybe fix can be included in this

It _could_, but it is also fine for it to be two separate things, especially as that is the track it is currently on.

**Comment by donho** [comment]
I don't want to change it for 2 reasons:
1. I want to make it as short as possible so all the translation could fit in it.
2. Under "Tab settings" with option **Replace by space** means "Replace Tab by space" and that is obvious to me.

If current label makes other users confusing, and complains keep coming, I'll consider changing it. But for the moment, I prefer to keep the current one.
