### ISSUE TITLE
Disable monitoring mode deactivates read-only

### ISSUE THREAD

**Issue by rotemit** [notepad-plus-plus/notepad-plus-plus#13181]
### Description: 

I want to open a file as read only, and keep it as read only as long as it's open no matter what. It's a log file and I don't want the user to be able to delete important parts accidentally.
While the file is open, I want to toggle monitoring mode, because I need it to be on at times and off at other times (the file is being written to continuously).
The problem arises when I disable monitoring: this deactivates the read only feature.

### Steps to Reproduce the Issue

1. Open a file in Notepad++ via command line with "-ro" and "-monitor" flags
2. When the file is open, turn off monitoring using the eye icon
3. Edit and save the file

**Other ways to reproduce**;
Instead of step 1 above, do one of the following:
- Open the file from command line with "-ro" flag and when the file is open turn on monitoring.
- Open the file from command line with "-monitor" flag and when the file is open make it read-only, from either "edit menu" or "tab context menu".
- Open the file manually from Notepad++, turn on monitoring and read-only manually, then turn off monitoring.

### Expected Behavior
Editing the file shouldn't be allowed. Especially in the scenario where it was opened from command line using "-ro" flag.

### Actual Behavior
We can write, delete, and save the file. In essence, read-only was disabled once monitoring was disabled.

### Debug Information
Notepad++ v8.4.9   (64-bit)
Build time : Jan 27 2023 - 03:11:16
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : 
Admin mode : ON
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 10 Enterprise (64-bit) 
OS Version : 1909
OS Build : 18363.2274
Current ANSI codepage : 1252
Plugins : 
    mimeTools (2.9)
    NppConverter (4.5)
    NppExport (0.4)

**Comment by donho** [comment]
The issue cannot be reproduced in v8.7 - I do believe it's been solved in previous versions since long time ago.
BTW, using only `-monitor` is enough. `-RO` is not necessary.

**Comment by BubuC** [comment]
@donho This bug in one form or other is still there... I submitted a suggested fix for it in #15605

To reproduce: Launch without switches, open a log file, set as readonly from Edit menu. If later we enable monitoring, then disable monitoring, file is no longer in readonly, which is unexpected behaviour to us.
