### ISSUE TITLE
Find in Files progress window bugged

### ISSUE THREAD

**Issue by dfs-** [notepad-plus-plus/notepad-plus-plus#13185]
### Description of the Issue
The find in files progress window is bugged after update to 8.4.9. The progress bar reaches out of the form and the cancel button also is offset and too large for the form, despite not necessarily resized between versions 8.4.8 <> 8.4.9.

![image](https://user-images.githubusercontent.com/6563013/220281092-279740a4-0fe5-4afb-99d5-d0d59d5e5fa3.png)

### Steps to Reproduce the Issue
1. using Windows 10 perform a find in files search
2. observe the progress bar and cancel button being cut off by the forms borders

### Expected Behavior
Progress bar and cancel button should be aligned correctly, as it was in 8.4.8.

### Actual Behavior
Progress bar and cancel button are cut off by the forms dimensions.

### Debug Information
```
Notepad++ v8.4.9   (64-bit)
Build time : Jan 27 2023 - 03:11:16
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 10 Pro (64-bit) 
OS Version : 22H2
OS Build : 19045.2546
Current ANSI codepage : 1252
Plugins : 
    ComparePlus (1.1)
    JSMinNPP (1.2205)
    mimeTools (2.9)
    NppConverter (4.5)
    NppExport (0.4)
    PythonScript (2)
    XMLTools (3.1.1.13)
```

**Comment by rdipardo** [comment]
> the progress bar and cancel button being cut off by the forms borders

Probably for the [same reason] as in #13053 and #13078.

[same reason]: https://github.com/notepad-plus-plus/notepad-plus-plus/pull/13054#issuecomment-1419562836

**Comment by dfs-** [comment]
Seems fitting.
