### ISSUE TITLE
Notepad++ v8.4.9 regression: Folder display mess in non-western languges under Macro/Run menu 

### ISSUE THREAD

**Issue by rddim** [notepad-plus-plus/notepad-plus-plus#13221]
### Description of the Issue

The issue come from https://github.com/notepad-plus-plus/notepad-plus-plus/commit/6e7901ecb311670e03fbe23adebd2417ea483d08. After creating a subfolder in Cyrillic everything seems normal. But when a macro/command change (rename, delete or record new one) is made via the GUI, the created submenu does not appear readable the next time Notepad++ is started. After opening `shortcuts.xml` it is seen that the subfolder name is not readable either.
### Steps to Reproduce the Issue

1. Make sure you have the latest v8.4.9
2. Open the `shortcuts.xml`
3. Follow the instructions in the file and add `макрос` for the submenu (i.e. `FolderName="макрос"`) to the existing `Trim Trailing Space and Save` macro
4. Save and close the file
5. Open `notepad++.exe` and rename the macro `Trim Trailing Space and Save` to something else.
6. Close and open Notepad++ again
7. Check the macro subfolder name

### Expected Behavior

I have expected to have a readable macros subfolder after changing something.
![npp_shortcuts_readable](https://user-images.githubusercontent.com/8998791/208510774-289d45cf-2401-468b-b58a-0c0fe66e43ac.png)
### Actual Behavior

After changes the subfolder name in `shortcuts.xml` is stored as `&#x043C;&#x0430;&#x043A;&#x0440;&#x043E;&#x0441;` or `&lt;0:@&gt;A` instead of `макрос`
![npp_unread_macro](https://user-images.githubusercontent.com/8998791/221255794-cdc6a741-b096-48b6-b1b0-d51355f672b3.png)

### Debug Information

```
Notepad++ v8.4.9   (64-bit)
Build time : Jan 27 2023 - 03:11:16
Path : D:\Install\Office Programs\Notepad++\notepad++.exe
Command Line : 
Admin mode : ON
Local Conf mode : ON
Cloud Config : D:\Install\Office Programs\Notepad++\_settings
OS Name : Windows 7 Professional (64-bit) 
OS Build : 7601.0
Current ANSI codepage : 1251
Plugins : 
    AutoSave (1.6.1)
    ComparePlus (1.1)
    TakeNotes (1.2.4)
    VisualStudioLineCopy (1.0.0.2)
```

@donho pointed here

**Comment by ArkadiuszMichalski** [comment]
@donho 
You convert `FolderName` when read XML file but don't do this when save this file:
https://github.com/notepad-plus-plus/notepad-plus-plus/blob/20f381e506af79917d0843a2b87e4f1ef6562bc8/PowerEditor/src/Parameters.cpp#L3582

Btw, you allow native language in `FolderName` attribuite but not in `name` attribute? It's a bit inconsistent. In both it should be allowed or forbidden.

I was looking to change `_pXmlShortcutDoc` from `TiXmlDocument` to `TiXmlDocumentA` (similarly as we do with other files):
https://github.com/notepad-plus-plus/notepad-plus-plus/blob/caff51c78817dedbe0e5b74a55b93adfef78eccc/PowerEditor/src/Parameters.h#L1806-L1808
but that would require quite a loft other correct (datatypes in multiple places, etc.) so converting the values of just these two attributes seems the simplest.

**Comment by donho** [comment]
@ArkadiuszMichalski 
> You[ convert `FolderName`](https://github.com/notepad-plus-plus/notepad-plus-plus/blob/20f381e506af79917d0843a2b87e4f1ef6562bc8/PowerEditor/src/Parameters.cpp#L2742) when read XML file but don't do this when save this file:

Yes, that's why I assigned to myself to fix it. 
   
> Btw, you allow native language in FolderName attribuite but not in name attribute? It's a bit inconsistent. In both it should be allowed or forbidden.

For all the added context menu items from menu commands, the translation has been done if one of nativeLang.xml is enabled.
It's a hack for people who want to have his/her language completely. 

> I was looking to change _pXmlShortcutDoc from TiXmlDocument to TiXmlDocumentA (similarly as we do with other files):
...
but that would require quite a loft other correct (datatypes in multiple places, etc.) so converting the values of just these two attributes seems the simplest.

I have also checked this point long time ago. For not having any regression, let's keep it as it is.

**Comment by ArkadiuszMichalski** [comment]
@donho
>Btw, you allow native language in FolderName attribuite but not in name attribute? It's a bit inconsistent. In both it should be allowed or forbidden.
>>For all the added context menu items from menu commands, the translation has been done if one of nativeLang.xml is enabled.
It's a hack for people who want to have his/her language completely.

If a submenu can be in a native language, why not a name?

![image](https://user-images.githubusercontent.com/2730894/223293204-ca42e7ee-0d94-4b93-844b-d7f3a5d62214.png)

But the same is for Run.
![image](https://user-images.githubusercontent.com/2730894/223293565-8d4a43d1-5070-4ee9-b257-b066fa990414.png)

Well, these names from `Macro` and `Run` also appear in the `Shortcut mapper` dialog and there may also be problems with the correct display.

**Comment by donho** [comment]
@ArkadiuszMichalski
> If a submenu can be in a native language, why not a name?

Makes sense. I will see what I can do about it.

**Comment by donho** [comment]
https://github.com/notepad-plus-plus/notepad-plus-plus/commit/96b56f61f90d8b3f27d8fab804676a8ddcbd4a22
