### ISSUE TITLE
Dangerous use of sscanf?

### ISSUE THREAD

**Issue by mjunix** [notepad-plus-plus/notepad-plus-plus#13237]
https://github.com/notepad-plus-plus/notepad-plus-plus/blob/b1e136118958e34888a125a301a68de5e32ff7a3/lexilla/lexers/LexTCMD.cxx#L242

Isn't it dangerous to use "%[" without a field width specifier?

**Comment by alankilborn** [comment]
Lexilla isn't Notepad++ owned code, so this question/issue doesn't belong here.
You'll find Lexilla on scintilla.org.

Please CLOSE this issue.

**Comment by chcg** [comment]
@mjunix Please report this issue at https://github.com/ScintillaOrg/lexilla/issues.
