### ISSUE TITLE
Switch between tabs (key shortcut)

### ISSUE THREAD

**Issue by Jedrzej94** [notepad-plus-plus/notepad-plus-plus#1324]
Hey,

How about switching between tabs key shortcut, just like in the browser.

CTRL + number = tab to be shown.

**Comment by ClaudiaFrank** [comment]
Is already there, be aware that number is on numpad.
If you want to modify it use shortcut mapper.

**Comment by gabera** [comment]
My sugestion is to add the abillity to change between tabs with ctrl+Page Up/Down shortcut as we can do in web browsers.

**Comment by ClaudiaFrank** [comment]
Is already there, maybe you have an outdated version or a plugin has occupied the shortcut?

**Comment by gabera** [comment]
I got it! My Notepad++ was out of date cause my network is blocked.
Thank you Claudia!
