### ISSUE TITLE
Regex Macro crash when replacing selection with "\1"

### ISSUE THREAD

**Issue by OshidaBCF** [notepad-plus-plus/notepad-plus-plus#13246]
### Description of the Issue
I have a macro that is supposed to add "\n\n" before every line that start by a letter 
But when i tried to add it to my macro that already reformate my file, using the macro crash N++

Testing the regex with the normal find/replaced worked

This is the regex i used : 
Search : (\n[a-zA-Z])
Replace : \n\n\1

### Steps to Reproduce the Issue

1. use the macro in the "crash" file on exemple.txt
2. N++ crash

### Expected Behavior
It shouldn't crash to do what's explained in exemple.txt

### Actual Behavior
N++ Crash

### Debug Information
Notepad++ v8.4.8   (64-bit)
Build time : Dec 24 2022 - 19:40:27
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 10 Home (64-bit) 
OS Version : 22H2
OS Build : 19045.2604
Current ANSI codepage : 1252
Plugins : 
    ComparePlugin (2.0.2)
    mimeTools (2.9)
    NppConverter (4.5)
    NppExport (0.4)
    NppFavorites (1.0.0.1)

[Crash.txt](https://github.com/notepad-plus-plus/notepad-plus-plus/files/10833454/Crash.txt)
[NoCrash.txt](https://github.com/notepad-plus-plus/notepad-plus-plus/files/10833455/NoCrash.txt)
[Exemple.txt](https://github.com/notepad-plus-plus/notepad-plus-plus/files/10833456/Exemple.txt)

**Comment by alankilborn** [comment]
First, your `Exemple.txt` file is in Windows end-of-line format.  This means that line-endings are CRLF.  When you use `\n` in regular expression replacement, you will "corrupt" the line-endings in your data file.  You should use `\r\n`, not `\n'.

**Comment by alankilborn** [comment]
You can see the corruption that occurs if you turn on visible line endings with _View_ (menu) > _Show Symbol_ > _Show End of Line_:

![image](https://user-images.githubusercontent.com/77065706/221408409-2fd78915-69a7-4ab1-84a3-1043bc1f790e.png)

**Comment by alankilborn** [comment]
However, the line-ending corruption isn't related to the crash.  The crash is caused by your poor hand-editing of your macro.  

Note that on line 34 and 35 of Crash.txt you a repeat of the `message="1700"` line.  Thus, the steps that now begin on line 41 now have no leading "1700" line and cause the crash.  You should move line 35 to be before line 41 so that everything is balanced and in proper sequence.

Please CLOSE this issue.

**Comment by OshidaBCF** [comment]
I seeee, so instead of replacing by "\n\n\1" i should replace by "\r\n\r\n\1" ?

**Comment by OshidaBCF** [comment]
Ahhhh, so i placed the lines a bit too low.

**Comment by alankilborn** [comment]
>so instead of replacing by "\n\n\1" i should replace by "\r\n\r\n\1" ?

More importantly, you should replace `\n` by `\r\n` EVERYWHERE in your macro!
If you are used to other programming where `\n` is automatically done correctly automatically for you, you have to get used to this being a difference in Notepad++ regex, where you have to be explicit.

**Comment by alankilborn** [comment]
>so i placed the lines a bit too low.

In reality, your insertion point for the new part of the macro was one line off.  :-)

**Comment by alankilborn** [comment]
You may find this section of the user manual to be of interest:  https://npp-user-manual.org/docs/searching/#searching-actions-when-recorded-as-macros

**Comment by OshidaBCF** [comment]
I see for \r\n.

Moving the replacement up by one line fixed it, now it's perfect
