### ISSUE TITLE
Error C7692

### ISSUE THREAD

**Issue by Avtroman** [notepad-plus-plus/notepad-plus-plus#13251]
Error C7692

notepad-plus-plus-master\PowerEditor\src\WinControls\FunctionList\functionListPanel.cpp(297,9): error C7692: "bool nlohmann::json_abi_v3_11_2::basic_json<std::map,std::vector,std::string,bool,int64_t,uint64_t,double,std::allocator,nlohmann::json_abi_v3_11_2::adl_serializer,std::vector<uint8_t,std::allocator<uint8_t>>>::operator ==(const nlohmann::json_abi_v3_11_2::basic_json<std::map,std::vector,std::string,bool,int64_t,uint64_t,double,std::allocator,nlohmann::json_abi_v3_11_2::adl_serializer,std::vector<uint8_t,std::allocator<uint8_t>>> &) noexcept const": перезаписанная функция-кандидат была исключена из разрешения перегрузки, поскольку соответствующий оператор!= объявлен в той же области
3>

**Comment by alankilborn** [comment]
Please CLOSE this issue.

**Comment by Avtroman** [comment]
> Please CLOSE this issue.

Why?
And how to build?

**Comment by alankilborn** [comment]
>And how to build?

See https://github.com/notepad-plus-plus/notepad-plus-plus/blob/master/BUILD.md
