### ISSUE TITLE
[Feature Request] - Ability to customize color Tones in Light Mode 

### ISSUE THREAD

**Issue by RemoteRV** [notepad-plus-plus/notepad-plus-plus#13255]
Ability to customize color Tones in Light Mode similar to Dark Mode
This allow to customize color Tones for "extreme distraction free / best readability" also in Light Mode

Please can you enable option **Preferences > Dark Mode > Light mode > "Customized"**

Currently we can customize color Tones in Dark Mode via:  **Preferences > Dark Mode > Dark mode > "Customized"**

Could we have an option to quickly customize also the Light Mode color Tones

![image](https://user-images.githubusercontent.com/126469198/221602963-4c1d7e76-0645-4eb3-857c-3bd70673eef5.png)

- I know I can modify many things via Style Configurator but the **Dark mode > "Customized"** window is the only way in NP++ to modify the edges of windows and panels via color picker "Top"
- The color pickers in **Dark mode > "Customized"** allow me to change the look of NP++ in more radical ways than what Style Configurator can do... unfortunately only in Dark Mode and not in Light Mode

### Why we need this / Problematic Behavior
Iam trying to achieve a "maximum distraction free" "super flat" Light Mode look that is similar to extreme minimalism of Windows 10 Notepad
- because I can't customize the Light Mode directly, I have to switch to Dark Mode and work backwards to achieve "flat" Light Mode
- unfortunately, with this reverse approach I am stuck with DARK Windows UI colors (buttons, scrollbars, menus, window title bar) that I cannot make light in Dark Mode (my "reverse Light Mode hack" hits the wall here)

![image](https://user-images.githubusercontent.com/126469198/221602274-41f84fa8-4d74-41ca-88a1-b6b980a2d223.png)

### Expected Behavior
The solution would be to have proper Light Mode customization - I could stay in Light Mode. Windows UI colors (buttons, scrollbars, menus, window title bar) that are dark in Dark Mode, would stay light in Light Mode and I could customize only what I want modified in the Light Mode. No need to hack the customized Dark Mode to achieve customized Light Mode (which doesn't work as demonstrated in case study above)

### Expected Solution
I took the liberty to "simulate" in Photoshop how NP++ could look in "maximum distraction free" "super flat" Light Mode emulating Windows 10 Notepad (its just a mockup from Photoshop) - I also removed the icons from tabs (which is currently not possible)

You can see in Windows 10 Notepad and now in this NP++ mockup how the text-editor interface completely disappears (minus the menu and search dialog box) the only thing standing out is the edited text itself - ultimate distraction free editing

![image](https://user-images.githubusercontent.com/126469198/221609139-a1590e87-da19-4e24-826a-183b06db6705.png)

And this would be the ULTIMATE minimalist version that I would hope to be able to achieve with the customizable Tones in Light Mode

![image](https://user-images.githubusercontent.com/126469198/221621787-cd5f6300-a720-4346-aae2-3e762037be3f.png)

**Comment by donho** [comment]
Let's light mode be light mode.
Only the dark mode can be customized.

**Comment by RemoteRV** [comment]
Doesn't make any sense to me...

Its not about Light or Dark mode... its simply about theme color
customization of a program regardless if you want to call something Dark or
Light or Rainbow mode...
