### ISSUE TITLE
Find in Projects should be a command (so that it can be assigned a shortcut)

### ISSUE THREAD

**Issue by alankilborn** [notepad-plus-plus/notepad-plus-plus#13256]
### Steps to Reproduce (StR) the Issue
1. Look in _Search_ menu for a _Find in Projects..._ command (that when invoked would open the main _Find_ window  and activate the _Find in Projects_ tab), so that it will be available in the _Shortcut Mapper_ and I can assign my own custom keycombo to it.

### Expected Behavior
That I would locate _Find in Projects_ on the _Search_ menu, perhaps in either the indicated red (preferred) or blue (secondary) positions?:

![image](https://user-images.githubusercontent.com/77065706/221604655-8ba61a8b-0067-4b89-b577-fc272946a539.png)

### Actual Behavior
_Find in Projects_ command not found.

### Debug Information
Comments based on behavior current to Notepad++ 8.4.9.

**Comment by donho** [comment]
> Look in Search menu for a Find in Projects... command (that when invoked would open the main Find window and activate the Find in Projects tab), so that it will be available in the Shortcut Mapper and I can assign my own custom keycombo to it.

The reason that **Find in project** is not in the command menu is because without project context this action is meaningless.
This command is available on the context menu of project panel which makes sense, but not alone in the menu.
Hence the rejection.

**Comment by alankilborn** [comment]
https://community.notepad-plus-plus.org/topic/25096
