### ISSUE TITLE
Notepad.exe replacement issue with filenames containing spaces

### ISSUE THREAD

**Issue by q2956** [notepad-plus-plus/notepad-plus-plus#13267]
### Description of the Issue
Notepad++ in combination with the registry key for notepad.exe replacement does pass though file names with spaces correctly.
This behavior occurs since 8.4.9. In previous Versions like 8.4.8 it did work perfectly with filenames containing spaces. 

### Steps to Reproduce the Issue

1. install notepad ++ 8.4.9
2. set registry key with
reg add "HKLM\Software\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\notepad.exe" /v "Debugger" /t REG_SZ /d "\"%ProgramFiles%\Notepad++\notepad++.exe\" -notepadStyleCmdline -z" /f
4. double klick a txt file like "c:\test file.txt" with a space in the file name.
5. notepad++ will tell "File c:\test does not exist. Create it?" 

### Expected Behavior
Notepad should open the file containing spaces in the file name it self. 

### Actual Behavior
Notepad does not open the file "c:\test file.txt". Notepad does ask, if it should create a new file named "C:\test", then a second dialoge opens and asks if it should create a file called "c:\file.txt". 

### Debug Information
Notepad++ v8.4.9   (64-bit)
Build time : Jan 27 2023 - 03:11:16
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : -notepadStyleCmdline -z "C:\WINDOWS\system32\NOTEPAD.EXE" C:\test file.txt
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 10 Pro (64-bit) 
OS Version : 22H2
OS Build : 19045.2604
Current ANSI codepage : 1252
Plugins : 
    ComparePlugin (2.0.2)
    mimeTools (2.9)
    NppConverter (4.5)
    NppExport (0.4)

![image](https://user-images.githubusercontent.com/13078418/221982807-d50b10c1-ac73-4783-bf24-595ad52f7e72.png)
![image](https://user-images.githubusercontent.com/13078418/221982840-bed3a2f8-4d92-4005-8171-163f096cf6f4.png)

**Comment by alankilborn** [comment]
You wasted your time in typing that up.
If you'd have searched existing issues you'd have found it has already been fixed; see #13032
You can test the change currently, in 8.5 RC; see [HERE](https://community.notepad-plus-plus.org/topic/24184/notepad-v8-5-release-candidate) for more info on that.

**Comment by q2956** [comment]
Thanks, i could not find it...
