### ISSUE TITLE
States for Mark's Bookmark-Line and Purge not rememberd over N++ restart

### ISSUE THREAD

**Issue by alankilborn** [notepad-plus-plus/notepad-plus-plus#13277]
### Description of the Issue
The _Mark_ window's _Bookmark line_ and _Purge for each search_ 's checked state is not remembered over a Notepad++ restart cycle.

### Steps to Reproduce the Issue

1. Invoke _Mark_ via Ctrl+m.
2. Checkmark _Bookmark line_.
3. Checkmark _Purge for each search_.
4. Do some _Mark All_ operations to verify bookmarking and pre-search purging of redmarking is working (it is).
5. Restart Notepad++.
6. Invoke _Mark_ via Ctrl+m.

### Expected Behavior
I expected the checked state of _Bookmark line_ and _Purge for each search_ to be retained, because that is how I last used these options, and typically how I want to use them every time I do a _Mark_ operation.

### Actual Behavior
_Bookmark line_ and _Purge for each search_ are unchecked after a Notepad++ restart.

### Debug Information
Notepad++ v8.4.9   (64-bit)
Build time : Jan 27 2023 - 03:11:16
Path : W:\npp.misc\_NoBackup\Releases\npp.8.4.9\npp.8.4.9.portable.x64\notepad++.exe
Command Line : -titleAdd="8.4.9 64-bit" -multiInst
Admin mode : OFF
Local Conf mode : ON
Cloud Config : OFF
OS Name : Windows 10 Enterprise (64-bit) 
OS Version : 21H2
OS Build : 19044.2486
Current ANSI codepage : 1252
Plugins : 
    Explorer (1.9.3)
    mimeTools (2.9)
    NppConverter (4.5)
    NppExport (0.4)
    PythonScript (3.0.14)

**Comment by alankilborn** [comment]
@donho Would it be OK to implement a fix for this one?  If so, please assign me (and also reply so I get a notification email).

**Comment by donho** [comment]
@alankilborn 
Yes sure. It's rather a bug to me.
