### ISSUE TITLE
Virus warning

### ISSUE THREAD

**Issue by gackt2** [notepad-plus-plus/notepad-plus-plus#13281]
Virus Total flags for a virus on version:

npp.8.4.9.Installer.x64.exe

6b170127061feb082ffd1b14309ef6d4a783df3c0fd51999e1786067731a49f3
npp.8.4.9.Installer.x64.exe

The portable zip is clean.

[https://www.virustotal.com/gui/file/6b170127061feb082ffd1b14309ef6d4a783df3c0fd51999e1786067731a49f3](url)
![Annotation 2023-03-03 194749](https://user-images.githubusercontent.com/45133573/222874407-34ef359a-ab6a-426c-8c70-8bca72c4c588.jpg)

**Comment by dfs-** [comment]
Not saying this is no issue, but Zillya is one of those snake oils, that always flags anything as being potentially harmful. 

It also flags other AC software…

**Comment by donho** [comment]
It's the false positive comes over and over again:
https://nsis.sourceforge.io/NSIS_False_Positives
