### ISSUE TITLE
Tooltips are not updated after changing translation

### ISSUE THREAD

**Issue by ArkadiuszMichalski** [notepad-plus-plus/notepad-plus-plus#13286]
### Description of the Issue
When we change translation all tooltips from `Preferences` and `Find/Replace` dialogs are not update. It's a bit annoying, especially when we doing a translation because we have to restart Notepad++ (and we don't always remember to do that and wonder why our translation doesn't work).

### Steps to Reproduce the Issue

1. Open Notepad++.
2. Open `Preferences` dialog and check tooltips (move mouse over `[?]` in `Editing/Delimiter/Performance`).
3. Check tooltips also in `Find/Replace` dialog.
4. Change translation to other and once again check above tooltips.

### Expected Behavior
Tooltips text should be update when we switch translation.

### Actual Behavior
Tooltips text is  not update when we switch translation.

Tooltips from other places are done differently and their text is updated when we switch translation.

### Debug Information
```
Notepad++ v8.4.9   (64-bit)
Build time : Mar  3 2023 - 18:39:25
Built with : GCC 12.2.0
```

**Comment by alankilborn** [comment]
@donho said "not a bug to me" -- see [HERE](https://community.notepad-plus-plus.org/post/84525).

**Comment by donho** [comment]
I personally don't fix that - but if you do and the solution is quite simple, it will be accepted.

**Comment by donho** [comment]
Please see:
https://github.com/notepad-plus-plus/notepad-plus-plus/pull/13288#issuecomment-1454937340
