### ISSUE TITLE
Shortcut Go to matching brace (CtrlB) = Notepad crash

### ISSUE THREAD

**Issue by rescalda** [notepad-plus-plus/notepad-plus-plus#13284]
### Description of the Issue
Positioning the cursor on a brace and pressing Ctrl + B causes Notepad++ to crash

### Steps to Reproduce the Issue
Enter a very simple C style code:
main() {
    printf("Hello world");
}
Position cursor on one any bracket, Menu -> Search -> Go to matching brace: this works fine.
But Ctrl + B causes Notepad++ to freeze and, after a while, crash.
Tried to map "Go to matching brace" to some other shortcust, same problem.

### Expected Behavior
Go to matching brace!

### Actual Behavior
Freeze -> crash.

### Debug Information
Notepad++ v8.4.9   (64-bit)
Build time : Jan 27 2023 - 03:11:16
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : "C:\Source\Arduino\Experimenting\TeodoCtl\TeodoCtl.ino"
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 10 Pro (64-bit) 
OS Version : 21H2
OS Build : 19044.2604
Current ANSI codepage : 1252
Plugins : 
    BigFiles (0.1.3)
    BracketsCheck (1.2.2)
    ComparePlugin (2.0.2)
    HexEditor (0.9.12)
    HTMLTag (1.2.1)
    mimeTools (2.9)
    NppConverter (4.5)
    NppExport (0.4)
    NPPJSONViewer (1.40)
    NppTextFX (0.2.4)
    NppTextViz (0.4.1)
    NppXmlTreeviewPlugin (2)
    PreviewHTML (1.3.2)
    XMLTools (3.1.1.12)

**Comment by alankilborn** [comment]
Works fine in a fresh 8.4.9.
Are you sure Ctrl+b isn't running some plugin function?
This is likely a plugin issue; remove plugins, repeat test, add plugins back in one by one until problem repeats.

**Comment by rescalda** [comment]
Thanks a lot alankilborn, you found the reason! 
I made it the opposite way: I removed my plugins one-by-one up to  **Npp TextFx.dll** and it was the cause.
When I re-installed what I had removed, I didn't find it and I don't really know when an why I installed it and it doesn't exist.
So, now I am perfectly ok.
