### ISSUE TITLE
Toggling line comments does not work for JavaScript

### ISSUE THREAD

**Issue by freggeldoe** [notepad-plus-plus/notepad-plus-plus#1328]
* ctrl+q, ctrl+k does not work for JavaScript, MenuItems do not work either
* works for (some?) other languages - only tested java

**Comment by ClaudiaFrank** [comment]
windows 7 x64 npp 6.8.8 seems to be ok
tested with java script, python, perl, php and vbs. Could it be that a plugin has taken over the shortcuts?

**Comment by freggeldoe** [comment]
No extra plugins were installed but i could solve the problem by deleting the "AppData/Roaming/Notepad++"-Folder and copying over my old config.xml. Might have been some residual settings there..

**Comment by KolyaKorruptis** [comment]
Same problem here. It was caused by changes in langs.xml
