### ISSUE TITLE
Thousand separator

### ISSUE THREAD

**Issue by AlBundyLoves69** [notepad-plus-plus/notepad-plus-plus#1329]
Hi, can you add the thousand separator to the displayed numbers? See the attached screen shot. How big is the file?

![notepad](https://cloud.githubusercontent.com/assets/9625486/12147608/195f0ac4-b49a-11e5-8223-143f74ce1f6e.png)

**Comment by dail8859** [comment]
:+1:

That is actually a really good idea. I think this should also apply to the information in the status bar.

**Comment by AlBundyLoves69** [comment]
Perfect! According to the new C++14 standard you could use ' as the separator - according to my example it would then appear like this:
Characters (without blanks): 230'222'680
