### ISSUE TITLE
Characters U+25A6, U+22A2, U+29BE, U+2245 should render by default

### ISSUE THREAD

**Issue by VariableEconometrics** [notepad-plus-plus/notepad-plus-plus#13292]
### Description of the Issue
When opening Notepad++ and loading in a file, the characters render as blank squares, when they should not. 

### Steps to Reproduce the Issue

1. load in these characters into Notepad++ after opening in default configuration:
 ▦⦾⊢≅

### Expected Behavior
These should render as the glyphs associated with these symbols: a grid, concentric circles, the "proves" symbol, and and equal sign with a tilde on top.

### Actual Behavior
Just four blank squares seen.

### Debug Information
Notepad++ v8.4.9   (64-bit)
Build time : Jan 27 2023 - 03:11:16
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : "C:\Program Files\Notepad++\change.log" 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 11 (64-bit) 
OS Version : 22H2
OS Build : 22621.1265
Current ANSI codepage : 1252
Plugins :

**Comment by ArkadiuszMichalski** [comment]
@VariableEconometrics 
Try switch this option:
` Settings > Preferences... > MISC. >  Use DirectWrite (May improve rendering special characters, need to restart Notepad++)`

https://github.com/notepad-plus-plus/notepad-plus-plus/wiki/FAQ#incorrect-character-rendering

**Comment by VariableEconometrics** [comment]
Thanks. This does in fact resolve the issue. From my point of view, I would prefer if editors just worked "out of the box" without additional configuration, but presumably there are good reasons here for this design choice.
