### ISSUE TITLE
Bug report: Two "Edit with Notepad++" context menu entries in Windows 11

### ISSUE THREAD

**Issue by k-kolev1985** [notepad-plus-plus/notepad-plus-plus#13296]
### Description of the Issue
After updating to Notepad++ v8.5 under Windows 11, now there are two "Edit with Notepad++" context menu entries for files in the used file managers (e.g. Windows Explorer/File Manager, SpeedCommander).
If I uninstall Notepad++ v8.5, both two context menu entries are removed.
The two context menus appear at the same time only in the classic context menu (the one that appears if invoked from the keyboard).

### Steps to Reproduce the Issue
1. Install Notepad++ 8.5 with the option to add a context menu "Edit with Notepad++".
2. Open a file manager (e.g. Windows Explorer/File Manager, SpeedCommander) and select a text file to open with Notepad++.
3. Invoke the file manager's context menu for the selected file, by pressing either the "Applications" key or Shift+F10.
4. Observe the number of "Edit with Notepad++" context menu entries.

### Expected Behavior
There should be only one context menu entry - the one with the underlined (accelerator) "N" - that is the one for the classic context menu.

### Actual Behavior
Two context menu entries appear - the one with the underlined (accelerator) "N", and the one with no accelerator, probably used for the modern context menu.

### Debug Information
Notepad++ v8.5   (64-bit)
Build time : Mar  6 2023 - 02:18:13
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 11 Pro (64-bit)
OS Version : 22H2
OS Build : 22621.1265
Current ANSI codepage : 1251
Plugins : 
    DSpellCheck (1.4.24)
    mimeTools (2.9)
    NppConverter (4.5)
    NppExport (0.4)
    NppSaveAsAdmin (1.0.211)

![NPPExplorerContextMenu](https://user-images.githubusercontent.com/4395934/223065673-98faca32-6d18-4181-a34a-e7eb3b5481db.png)

**Comment by rddim** [comment]
@k-kolev1985 

Sorry for the offtopic

Regarding the localization of `Edit with Notepad++`, how do you prefer it to be: `Редактиране с Notepad++` as it is now or `Отваряне с Notepad++` (`Open with Notepad++`) as it is offered in the `Open with...` context menu of Windows?


Отностно превода на `Edit with Notepad++` как предпочитате да бъде: `Редактиране с Notepad++`, както е сега или `Отваряне с Notepad++` (`Open with Notepad++`), както се предлага в контекстното меню `Open with...` на Windows?

**Comment by k-kolev1985** [comment]
@rddim I prefer „Редактиране с Notepad++“, because this clearly states that the file will be opened for editing and not only for viewing (read-only).

**Comment by GurliGebis** [comment]
This is due to it overwriting the "Pin to quick access" (which is not the way to add things to the new Win11 context menu).

So the bug is really that it replaces it instead of adding it's own like it should do.

**Comment by GurliGebis** [comment]
Please see https://github.com/notepad-plus-plus/notepad-plus-plus/pull/13170#issuecomment-1437229089 for how this should be done instead of this hacky way.

**Comment by donho** [comment]
It's intentional to install both (new & classic) context menu so user chooses his/her way to access to it.

**Comment by k-kolev1985** [comment]
Yes, I can understand, but how can we choose which of the two menu entries to leave and remove/disable the other?

**Comment by danieledp** [comment]
Hi guys,

I had this problem (two contextual entries, one grayed out) on Win 11 with new contextual menu disable in the reg.

Just found a quick solution. Try these steps:
1. Download the 8.4.9 installer (https://github.com/notepad-plus-plus/notepad-plus-plus/releases/tag/v8.4.9)
2. Unzip it somewhere (7-zip will do the job)
3. Find the _NppShell_06.dll_ file and put it in **C:\Program Files\Notepad++\contextMenu\** (or wherever Npp is installed)
4. Open a terminal and deregister the file just copied (run **regsvr32 /u "C:\Program Files\Notepad++\contextMenu\NppShell_06.dll"**)

Hope it helps someone.

Cheers,
Daniele

**Comment by GurliGebis** [comment]
@danieledp okay, that is interresting.
What this does is remove the classic menu handler (it shares that id's with the old one).

@donho would it make sense to have some logging features (I already have a branch with some logging, that can be enabled with an environment variable) ?

**Comment by donho** [comment]
@GurliGebis 
What do you mean by "logging features" ?

**Comment by GurliGebis** [comment]
@donho It allows the user to enable logging for the context menu code (by setting an environment variable) - that way it is easier to ask people to help debug it, if they are having issues. 🙂

**Comment by donho** [comment]
@GurliGebis 

> I already have a branch with some logging, that can be enabled with an environment variable) ?

OK then.
Please use long name like NPPSHELL_ALLOW_LOG_FOR_XXX so there won't be collision for any system environment variable.

**Comment by GurliGebis** [comment]
@donho I have created a PR with logging here: notepad-plus-plus/nppShell#41

**Comment by p1r473** [comment]
Im still having this issue with WIndows Explorer on Windows. Reinstall did not fix.

**Comment by GurliGebis** [comment]
@p1r473 once the next version is released, we can work on figuring out what is wrong, since it has logging implemented.

**Comment by donho** [comment]
@GurliGebis @p1r473 
Notepad++ v8.5.5 which contain NppShell.dll with logging is available here:
https://notepad-plus-plus.org/downloads/v8.5.5/

**Comment by GurliGebis** [comment]
@p1r473 are you up for testing with the latest version with logging enabled?

**Comment by p1r473** [comment]
@GurliGebis sure - sorry for the late response. Im still having the same issue.
I went to the 8.5.5 download page and dont see one with logging. which binary do you want me to test with now?
Im on latest 8.5.7 
![image](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/9235633/770af8e9-c48e-4f81-9ac6-6e6531dda981)

**Comment by GurliGebis** [comment]
> @GurliGebis sure - sorry for the late response. Im still having the same issue. Im on latest 8.5.7 using Win 11. how do i enable logging? I cant find any logging version on the 8.5.5 [page](https://notepad-plus-plus.org/downloads/v8.5.5/) ![image](https://user-images.githubusercontent.com/9235633/274808414-770af8e9-c48e-4f81-9ac6-6e6531dda981.png)

First, you create an new environment variable called `NPPSHELL_LOGGING_ENABLED` and set it to `true`
Then you kill explorer.exe using task manager, so it restarts (or restart the computer)
After that, you reproduce the issue.
Finally, inside your Roaming AppData folder, you should find a NppShell folder, with the logfile

**Comment by p1r473** [comment]
@GurliGebis can I do it on 8.5.7?
To reproduce the issue, do I just right click a file?

**Comment by p1r473** [comment]
@GurliGebis 
[NppShell.log](https://github.com/notepad-plus-plus/notepad-plus-plus/files/12894666/NppShell.log)

**Comment by GurliGebis** [comment]
@p1r473 can you try installing the version from here: http://download.notepad-plus-plus.org/repository/MISC/nppShell_more_log/
After installing, restart explorer, delete the logfile, and try triggering the issue again. (Deleting to ensure the old log messages are removed).

**Comment by p1r473** [comment]
@GurliGebis Same issue, let me know if this helps. I deleted the logfile after uninstall but before reinstall, as I thought it might be more helpful
![image](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/9235633/050a886f-0925-40c4-98c9-6f4f9e71527e)
[NppShell.log](https://github.com/notepad-plus-plus/notepad-plus-plus/files/13046790/NppShell.log)

**Comment by GurliGebis** [comment]
@p1r473 
Looking at the log, it looks to be working like it should.
The classic menu is asking the shell to be hidden, so only the modern one is to be shown.

However, there is a lot of objects being created and destroyed, which I cannot reproduce on my machine.

Do you have some kind of UI changes installed (like something to remove the new right click menu) or something else, because the way it is acting is strange?

**Comment by p1r473** [comment]
@GurliGebis yes, for sure, I turned off that awful new right click menu 
https://www.elevenforum.com/t/disable-show-more-options-context-menu-in-windows-11.1589/

**Comment by GurliGebis** [comment]
In that case, I expect that to be the cause of it, since things are acting strangely.
Sorry, but applying strange hacks to explorer has weird side effects - it's not really something we can workaround, since the code is working as intended, from what the log files show (Except for creating way way too many objects).

**Comment by NarrativeBias** [comment]
@p1r473 
Had same problem
![explorer_9UEw5CAJua](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/47028771/e4e3e9d3-e640-439e-ab41-eb45958bf6f9)
went and deleted via regex
\HKEY_CLASSES_ROOT\*\shell\ANotepad++64
along with all the keys inside, no duplicate now
![explorer_9l2etnRNlL](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/47028771/76c1e941-d5c5-4436-a247-2ad964264641)

Just keep in mind that if you reinstall/update notepad++ you should keep off "Context Menu Entry" 
with this option off you get 1 instance of notepad++ in context menu if you modified win11 right-click innovation
and with it on you'll get same duplicate problem again

**Comment by GurliGebis** [comment]
@NarrativeBias if you completely uninstall notepad++, and then do a clean install with the context menu enabled, does it still happen?

**Comment by NarrativeBias** [comment]
> @NarrativeBias if you completely uninstall notepad++, and then do a clean install with the context menu enabled, does it still happen?

uninstall removes both instances of notepad++ from context menu
clean install with "Context Menu Entry" on brings both instances back into context menu
clean install with "Context Menu Entry" off brings none of the instances back into context menu

after uninstall for things to be correct i have to first install with "Context Menu Entry" on and then mess with regedit to remove the duplicate

**Comment by GurliGebis** [comment]
That sounds really weird - can you try with the version mentioned here: https://github.com/notepad-plus-plus/notepad-plus-plus/issues/13296#issuecomment-1768568906 and get the log file to me like described further above?

**Comment by NarrativeBias** [comment]
[NppShell.log](https://github.com/notepad-plus-plus/notepad-plus-plus/files/13299205/NppShell.log)
Here is clean installation log where problem persists.

**Comment by GurliGebis** [comment]
Sorry for the long wait.
I have looked at it, and the strange thing is that is looks identical to what I see on other systems.
I'll keep thinking about it, there might be a better solution to the problem.
