### ISSUE TITLE
TypeScript Support

### ISSUE THREAD

**Issue by joewashear007** [notepad-plus-plus/notepad-plus-plus#133]
_Sorry, I hope this is the right spot for this. I am not sure if it should have been here or on source forge._

Would it be possible to add TypeScript Language support? At least code highlighting and folding would be amazing. 

Thanks,
Joe

**Comment by MAPJe71** [comment]
As TypeScript is a super set of JavaScript wouldn't associating TypeScript files with the JavaScript lexer address your issue?

**Comment by milipili** [comment]
maybe a temporary solution: https://github.com/sorskoot/npp-typescript-vs

**Comment by joewashear007** [comment]
Thanks for the temp solution, I will try that for now.

Typescript does compile down to JavaScript, but they are different
syntactically. Typescript has many different key words, classes and
modules, and of courses variables have types. Most of the code logic is the
same, but the two ate really structured differently.

Would you consider adding it to the language list? Do you have an idea of
what modifications would be required to nnp-typescript-vs to merge it?

Thanks
Joe

**Comment by donho** [comment]
Another temporary solution here:
https://github.com/hansrwindhoff/nppPluginTypescript

**Comment by ArtemAvramenko** [comment]
> At least code highlighting and folding

Light theme - https://gist.github.com/ArtemAvramenko/3ebf93096bb4bd59b5c4
Dark theme - https://gist.github.com/ArtemAvramenko/e11394cc3669e775c882

**Comment by HarelM** [comment]
Would be wonderful to get this, also associate the highlighting with `.ts` files.

**Comment by MetaChuh** [comment]
closed due to:
* inactivity (2y)
* can be done by using one of the existing TypeScript udl variants

**Comment by snow8gaia** [comment]
note - current status is not fixed. no valid reason. future status - not fixed.

one more reason to  ->
1. not use notepad++ 
2. use a text editor that is aware of  Typescript (and other programming languages).

**Comment by sasumner** [comment]
Requires Typescript be supported by Scintilla project, see https://sourceforge.net/p/scintilla/feature-requests/958/

**Comment by snow8gaia** [comment]
reasons for-
 👎 - It's not the only way. I might be wrong.
removing 👎  - for some reason they are in control of notepad++?
👎 - sourceforge link.

---

I don't open sourceforge.com links. I messed up and did but then I instantly closed it, so still curious about the contents of the scintilla feature request 958.

---
## thanks anyways.
