### ISSUE TITLE
Improve Find/Replace logic window (GUI)

### ISSUE THREAD

**Issue by gaamaaresosa** [notepad-plus-plus/notepad-plus-plus#13304]
I am really sorry not to fill the template properly.
The point is that the NotePad ++ is a real ultimate tool for programers like us.

But while comparing the Sublime Editor and other VSCode the help gui is not user friendly.
First this no inline find/search.
A new window opening and annoying.
That too it opens on the 2nd or 1st display but NotePad ++ in other display.
After typing few letters of a word no auto search starts like other editors.

Please improve.
Thanks again for your wonderful NotePad ++

**Comment by alankilborn** [comment]
>First this no inline find/search.

>After typing few letters of a word no auto search starts like other editors

Try _Incremental Search_, default keycombo: Ctrl+Alt+i

-------------------------

>A new window opening and annoying.
That too it opens on the 2nd or 1st display but NotePad ++ in other display.

_Find_ window stays where you put it.  Do Ctrl+f twice in a row to recenter it on N++ window.

**Comment by gaamaaresosa** [comment]
> Try _Incremental Search_, default keycombo: Ctrl+Alt+i

Wow !
I didn't know this for many years. Why hidden ?
Ctrl+F should show this option first like other editors.
Annoying separate search window also dosen't have any link to Incremental Search.

Please increase the font size on Incremental Search.
As we are 60+ very difficult to see the Font size 8 to 9

Please compare: Top is NotePad++ and bottom is Sublime
![image](https://user-images.githubusercontent.com/21296884/223416846-b4a37594-2841-4a75-b31e-a3dd399a18b4.png)

>Do Ctrl+f twice in a row to recenter

Good !
Why everything always not stright forward in NP++ ?
Why can't a single Ctrl+f make it center by default or follow the mouse curzor point ?

**Comment by alankilborn** [comment]
>Why hidden ?

It's not hidden; it's on the _Search_ menu.

>Ctrl+F should show this option first like other editors.

_Incremental Search_ is a different kind of search, thus a different menu entry and keycombo.

>Annoying separate search window also dosen't have any link to Incremental Search.

Why does it need one?

>Why can't a single Ctrl+f make it center by default or follow the mouse curzor point ?

Well, for me, I always want the Find window to be at the same place, and that place is not right over the middle of the window where the text I'm editing is.

>Why everything always not stright forward in NP++ ?

Is everything always "straight forward" in any software program?

**Comment by gaamaaresosa** [comment]
No doubt NP++ is a plum cake with very good taste.
I expect little cream on top.
I use it mostly for my regular work for many years.
But same time Sublime also I use because of little glitches in NP++
(Mainly find option), but today I learned a good this Ctrl+Alt+i 
(Soon I may forget such keycombo :-)
(Why should one remember Ctrl+Alt+i instead of Ctrl+f ?)

Current big Find window blocking the editor and annoying...
But appart from that everything is ultimate and a very big Thanks to you.

Please use VSCode, Sublime and just concentrate Find option in the middle of busy work. It will be seamless....
Thats what I expect in NP++, which is not there now.

**Comment by alankilborn** [comment]
>Why should one remember Ctrl+Alt+i instead of Ctrl+f ?

If you like _Incremental Search_ that much, simply use _Shortcut Mapper_ to change out Ctrl+Alt+i for Ctrl+f.

>Current big Find window blocking the editor and annoying...

It's true, but on a multi-monitor setup it is better as _Find_ can be moved to another monitor and N++ main window can be maximized on first monitor.

You can reduce its size, click here:

![image](https://user-images.githubusercontent.com/77065706/223429949-d2c1910e-3229-4726-8ba0-2e85b20a445d.png)

>Please use VSCode, Sublime and just concentrate Find option in the middle of busy work. It will be seamless....

It is probably "seamless" for you because you are used to it.
I use VSCode for certain things and I really don't like the find interface (which probably has its behavior roots in how Visual Studio's text editor "find" works).

**Comment by gaamaaresosa** [comment]
> use _Shortcut Mapper_ to change out Ctrl+Alt+i for Ctrl+f.

Simply superb !
Solved my problem, Thank you so much !!!
I have swapped Ctrl+F <> Ctrl+Alt+i

> You can reduce its size, click here:

This also excellent !
Now I could make the Help window smaller.

I will use the modified options for few days and update.
Thanks again !

**Comment by gaamaaresosa** [comment]
> If you like _Incremental Search_ that much, simply use _Shortcut Mapper_ to change out Ctrl+Alt+i for Ctrl+f.

After swaping the Incremental Search, its better.
But why F3 doesn't take me to the next available seach word on the editor ?
F3 and all very common for Find/Search Next right ?

**Comment by alankilborn** [comment]
First, F3 is only a suggestion; users can remap F3 to something else.  F3 has never made sense to me for _Find Next_ functionality; I use Ctrl+n (makes more sense, for "next").  The point is, you get to choose.

However, F3 (default) already has a function; it does _Find Next_ based on what is in the _Find_ window, not the _Incremental Search_ window.  

For _Incremental Search_, if you have input focus IN the _Incremental Search_ window, just press Enter to do a find-next on its data.  Or Shift+Enter to find-previous.

If your input focus is in the editing window, press the keycombo for _Incremental Search_ (your Ctrl+f remapping) and then press Enter one or more times to find next matches of its data.

**Comment by gaamaaresosa** [comment]
> For _Incremental Search_, if you have input focus IN the _Incremental Search_ window, just press Enter to do a find-next on its data. Or Shift+Enter to find-previous.

Ok, thanks again.
But one thing is sure, we have to do lot of workarround while working in NP++
This is unusual.

**Comment by alankilborn** [comment]
>But one thing is sure, we have to do lot of workarround while working in NP++

Haha.

Not really sure how you'd expect F3 to possibly have two meanings...

**Comment by gaamaaresosa** [comment]
> Not really sure how you'd expect F3 to possibly have two meanings..

Simply I expect inline find process for simple and quick find/search, unlike separate (annoying) window.
The big separate find window cab be called for "Search and Replace" etc.
Working 15 to 20 hours a day on coding makes feel about this glitches in NP++.
No such regrats in Sublime/VSCode editors.

That's ok, that's your own logic on your own software.

![image](https://user-images.githubusercontent.com/21296884/224520119-bbad91b1-7881-4bd3-83bb-54ffff34c23c.png)

**Comment by alankilborn** [comment]
Well, you keep talking about Sublime and VSCode, so suggest you stop frustrating yourself and go permanently with one of those.  We're sorry that Notepad++ does not meet your need; it does for many, however.

**Comment by gaamaaresosa** [comment]
@alankilborn
I am extremely sorry if I disturbed you.
I could have simply switched to any one of the those other editors any time.
There are lot of plus points in NP++ which others don't
That's why I am interested continuing NP++

Simpy forget this now.
In future if you recollect what I meant. That time you will do the best.

Honestly my heartful thanks to your wonderful NP++
I will use it for ever.
