### ISSUE TITLE
Error with SQL highlighting

### ISSUE THREAD

**Issue by CGarces** [notepad-plus-plus/notepad-plus-plus#1330]
Hi!

There is some error with the SQL highlighting and the '\' char under some scenarios.

How reproduce the error (v 6.8.8).

1.-Save the attached file and rename ir to test.sql
2.-Load it on a new notepad++ (the file is loaded correctly as SQL)
3.-Open a new file (Ctrl+N)
4.-Come back to the previous file (Ctrl+Tab)
5.-Now the SQL highlighting is incorrect after the '\' char 

[test.txt](https://github.com/notepad-plus-plus/notepad-plus-plus/files/80336/test.txt)

**Comment by Froggitt** [comment]
Hi

I have a work round for you if it helps.

If you go Preferences => MISC. and untick the "Treat Backslash as escape character for SQL" you will find the issue no longer occurs (at least in the uploaded file).

John
