### ISSUE TITLE
Column Editor OK button should be disabled if Text-to-Insert is empty

### ISSUE THREAD

**Issue by alankilborn** [notepad-plus-plus/notepad-plus-plus#13315]
### Description of the Issue
See StR.

### Steps to Reproduce (StR) the Issue
1. Invoke _Column Editor_
2. Click the _Text to Insert_ radio button
3. Delete all text out of the edit box below the _Text to Insert_ radio button

### Expected Behavior
I expected the OK button to turn be disabled/grey when the last character is removed from the edit box.

### Actual Behavior
OK button remains enabled:
![image](https://user-images.githubusercontent.com/77065706/223849452-42b6df56-a9a0-4d79-95fc-f82cd74b59e7.png)

### Debug Information
Notepad++ v8.5   (64-bit)
Build time : Mar  6 2023 - 02:18:13
Path : W:\npp.misc\_NoBackup\Releases\npp.8.5\npp.8.5.portable.x64\notepad++.exe
Command Line : -titleAdd="8.5 64-bit" -multiInst
Admin mode : OFF
Local Conf mode : ON
Cloud Config : OFF
OS Name : Windows 10 Enterprise (64-bit)
OS Version : 21H2
OS Build : 19044.2486
Current ANSI codepage : 1252
Plugins : 
    mimeTools (2.9)
    NppConverter (4.5)
    NppExport (0.4)
    PythonScript (2)

**Comment by Yaron10** [comment]
If the column-selection is not zero-width, it should be legit (like replacing `X` with an empty string).

If you're not in column-selection, pressing OK should not modify the file.
But it does: Undo is active, and you get Changed History markers. 
Do you understand why?

**Comment by alankilborn** [comment]
>If the column-selection is not zero-width, it should be legit (like replacing X with an empty string).

Nah, too obscure.  Just press Delete key, don't even invoke _Column Editor_ at all.

>If you're not in column-selection, pressing OK should not modify the file.
Do you understand why?

Nope.
