### ISSUE TITLE
Latest Notepad++ replaces "Pin to Quick access" in the Windows 11 menu

### ISSUE THREAD

**Issue by GurliGebis** [notepad-plus-plus/notepad-plus-plus#13320]
### Description of the Issue
The latest version of Notepad++ replaces the "Pin to Quick access" in the Windows 11 right click menu.
This is due to it being added in the wrong way.

Instead of just overwriting something else, it should be added like described here:
https://github.com/notepad-plus-plus/notepad-plus-plus/pull/13170#issuecomment-1437229089

The correct way to do it is to use Sparse Manifests: https://blogs.windows.com/blog/2021/07/19/extending-the-context-menu-and-share-dialog-in-windows-11/

Also, please don't close this bug as "expected behavior", since you are not supposed to just overwrite the built-in menu options to add your own.

### Steps to Reproduce the Issue
1.  Install the latest Notepad++ version
2.  Watch as it takes over the "Pin to Quick access" menu option

### Expected Behavior
It shouldn't overwrite the default Windows behavior, but should instead add it's own menu option to the list.

### Actual Behavior
It takes the easy (and wrong) way out, and just replaces the existing menu item, instead of doing it the right way.

**Comment by wallrik** [comment]
Please consider rolling back release 8.5 until this is fixed. 😣 Also, people have left [comments](https://github.com/notepad-plus-plus/notepad-plus-plus/commit/a0031159cd15e2798996f53c05d98b10ec69ead0#commitcomment-103252580) on the commit and other places as well.

Rolling back the release would stop more people from getting messed up installs, and save a lot of headache.

**Comment by riverar** [comment]
@donho Would consider rolling back a0031159cd15e2798996f53c05d98b10ec69ead0

**Comment by ErikHumphrey** [comment]
Doesn't seem necessary to do it the way it's currently implemented. At minimum, it should be an option; I wouldn't expect this behaviour just by installing Notepad++, especially as uninstalling it doesn't revert the change.

**Comment by donho** [comment]
Stop sharing the following link with me - it says it "should do" but not says "how to"
https://blogs.windows.com/blog/2021/07/19/extending-the-context-menu-and-share-dialog-in-windows-11/

If you have the concrete solution, please let me know.

For people who don't want the context menu, just uncheck **Context Menu Entry** during the installation:

![image](https://user-images.githubusercontent.com/90293/224195477-fecf2d3e-4660-48a0-9b99-690475b23aea.png)

**Comment by donho** [comment]
If you have the concrete solution, please let me know, or you can do your contribution by opening a PR.

**Comment by riverar** [comment]
@donho Sounds fair, thanks!

**Comment by GurliGebis** [comment]
I think this is what is needed: It explains how to create the needed Sparse Manifest with an example: https://blogs.windows.com/windowsdeveloper/2019/10/29/identity-registration-and-activation-of-non-packaged-win32-apps

From what I can see, registrering it should not require too many changes.

**Comment by sylveon** [comment]
There's a full example here: https://github.com/microsoft/AppModelSamples/tree/master/Samples/SparsePackages/PhotoStoreContextMenu

**Comment by GurliGebis** [comment]
Also, there is a clean C++ example for VS Code here: https://github.com/microsoft/vscode/pull/139640 - the one above requires C# it seems

**Comment by sylveon** [comment]
The context menu project in the sample I linked is all C++, but yeah that's also another good example.

**Comment by valinet** [comment]
@donho Why do you think it is okay to hijack the user’s preferences without notifying, at least? There is no mention of this app *replacing* some other entry in the context menu. Even if there was, it’s still a poor choice to do it like this when there’s documentation and examples available, you just have to look up. This is downright malware behavior - antivirus vendors better flag this release as such. This is unacceptable, the fact that you dare to ship such a mess brings a lot of question marks above the credibility and trust for this project going forward. There are already plenty comments advising not to push forward with this, yet you did it anyway.

I will uninstall this product for the time being, this is unacceptable.

**Comment by ToothyDev** [comment]
For everyone whose registry has already been messed with, deleting the `HKLM\SOFTWARE\Classes\*\shell\\pintohome` will make N++'s changes undone. This key doesn't exist in Windows by default and is created by N++, and thus safe to delete

**Comment by GurliGebis** [comment]
I have started working on implementing this, though nothing is even close to ready yet (the DLL compiles, but that is all - I haven't had time to finish it yet, and we also need to manifest and package files)

**Comment by LtCmdrKeene** [comment]
I really expected better from a project like this, than to hijack system entries in unsupported hacky methods.

**Comment by riverar** [comment]
@LtCmdrKeene Well to be fair, Microsoft didn't exactly document this convulted process properly, outside from a few random blog posts and some complex samples. Seems like the author had pure intentions here. Maybe at the MVP Summit or your PGIs you can discuss how terrible this process is.

**Comment by valinet** [comment]
@riverar Still, this is not a proper way of going about it. Period. As I said, this is malware behavior. Things indeed may be poorly documented or not documented at all sometimes. Trust me, I know how frustrating it feels. But just because someone does something bad, that doesn’t make it okay to do something else equally bad or even worse.

**Comment by donho** [comment]
@riverar 
It's an open source project so you are welcome to do your contribution, instead of whining.

**Comment by riverar** [comment]
@donho Wrong person? I'm on your side here lol

**Comment by donho** [comment]
@valinet 
 It's an open source project so you are welcome to do your contribution, instead of whining.

**Comment by GurliGebis** [comment]
Okay, I'm not normally the one doing this, but can we please get back on track with fixing the issue (see my PR above), instead of throwing things at each other and acting like children?
All this "he said, she said" isn't helping anyone.

**Comment by valinet** [comment]
> @valinet It's an open source project so you are welcome to do your contribution, instead of whining. Or you can use [v8.4.3 Unhappy Users' Edition](https://notepad-plus-plus.org/news/v843-unhappy-users-edition/) and get a refund.

Inexplicably, you failed to understand what I wrote. For example, being open source doesn't make malware less "malwarey". The behavior in the latest update is by all definitions malware. Also, I was not questioning or "whining" about the lack of such feature - I use Windows 11 and live just fine without said feature. So yeah, please pay more attention and actually read what people write before throwing non-sense around. Since you mention it, free software means anything but non-transparency, disregard of feedback and user preferences and malware-like behavior, which, as I said, is exactly what this here is all about. My 2 cents regarding your remark.

**Comment by donho** [comment]
@GurliGebis 
Thank you for your coding effort - very appreciated.
The non-ARM64 version (64 bits) has been tested - it works like charm.
I'm preparing the package to include your implementation into v8.5.1 release. The RC should be out this night or tomorrow.
Thank you again for your contribution!

**Comment by GurliGebis** [comment]
@donho you're welcome 🙂
Quick question, how do we cleanup for the people that has installed 8.5.0?
Their registry will have those keys, replacing the pin to quick access.
One way might be added a check on startup, and then use that to cleanup.

**Comment by donho** [comment]
@GurliGebis 
> Quick question, how do we cleanup for the people that has installed 8.5.0?

Via installer, this entry will be checked under Windows 11 - if it exists and, and contain the "Notepad++", then it'll be removed (even it's done by user manually). And the new "Edit with Notepad++" (your implementation) will be installed. 
See https://github.com/notepad-plus-plus/notepad-plus-plus/commit/5645ca150bf9b24813d5da7ee3a061e1306837d9

**Comment by GurliGebis** [comment]
@donho great 🙂
The auto-update that is built-in, does that run the installer or just replace the files?

**Comment by donho** [comment]
@GurliGebis 
> The auto-update that is built-in, does that run the installer or just replace the files?

The auto-updater (WinGUp) is not built-in feature, but a stand-alone exe which is delivered with the installers and packages.
It downloads installer when it's triggered, and then run installer - so the hijacked entry "Pin to Quick access" will be removed and the new modern shell "Edit with Notepad++" will be in place during the update.

The v8.5.1 RC is available here:
https://community.notepad-plus-plus.org/topic/24262/notepad-v8-5-1-release-candidate

The official release will be out in one week if no critical issue found.
You're welcome to give us a feedback :)

**Comment by GurliGebis** [comment]
@donho I just tested the RC, and it is working fine 🙂

**Comment by donho** [comment]
@GurliGebis 
That's a good news! Thank you for testing RC.
I'll let more time for more people testing it - it will be released in 6 days (hopefully!).

**Comment by GurliGebis** [comment]
@donho I haven't tested the cleanup though, now that I think of it

**Comment by donho** [comment]
@GurliGebis 
The cleanup works - at least according my tests when I integrated your implementation.
Please let me know if you detected it's not working some cases.

**Comment by GurliGebis** [comment]
@donho I have found a bug when upgrading from an earlier version to 8.5.1 - here is how to reproduce:

1. Install an earlier version with the context menu - NppShell_06.dll will be installed and registered.
2. Install the 8.5.1 version, which will register the new context menu.
3. Restart explorer, just to be sure.
4. Right click a file and select "Show more options" - you will see this:

![screenshot](https://user-images.githubusercontent.com/13592619/226166314-661073bf-3a31-46ab-80bd-24667cbcdf89.png)

This is due to NppShell_06.dll still being registered - you might want to update the install script to detect if it is already in the target directory (which means an upgrade), and then unregister and delete it.
Doing a clean install with just 8.5.1 works fine, since NppShell_06.dll is not installed and registered.

**Comment by GurliGebis** [comment]
@donho The uninstaller also has two problems:

- It doesn't unregister the sparse package, so the dll and msix isn't being deleted.
- It tries to unregister NppShell_06.dll, but it isn't there on a clean 8.5.1 install (so it might do a test for it before trying to unregister it)

**Comment by sylveon** [comment]
My recommendation is to drop NppShell_06 entirely in favor of the new NppModernShell, since they are effectively duplicates of each other.
- On Windows 11, register it using the sparse package.
- On lower, register it traditionally in the registry.

**Comment by GurliGebis** [comment]
@donho I have a PR for this, that is untested though, since I cannot create the installer: #13373

**Comment by sylveon** [comment]
I was thinking more like, also using NppModernShell downlevel

**Comment by GurliGebis** [comment]
@sylveon I'm pretty sure you cannot use sparse packages on anything other than Windows 11, so it won't work there.

**Comment by riverar** [comment]
Sparse packages are supported starting with Windows 10, version 2004.

**Comment by sylveon** [comment]
I believe the registration in the registry would be the same method as IContextMenu (the interface NppShell uses)

**Comment by GurliGebis** [comment]
@riverar Okay 🙂
@sylveon Would you be able to create a PR that sets that up?

**Comment by sylveon** [comment]
Unfortunately I am too busy to do so myself, but I imagine a lot of the infra for the previous DLL can be reused

**Comment by GurliGebis** [comment]
@sylveon if you can point me at some documentation on it, I might be able to take some time to look at it. (I haven't been able to find any, that's why I'm asking)

**Comment by sylveon** [comment]
From a quick look, it's pretty much exactly what NppShell does. It's all documented [here](https://learn.microsoft.com/en-us/windows/win32/shell/reg-shell-exts).

A full example would then end up being (replacing placeholders of course)
```
HKEY_CLASSES_ROOT
   CLSID
      {00000000-1111-2222-3333-444444444444}
         InProcServer32
            (Default) = C:\MyDir\MyCommand.dll
            ThreadingModel = Apartment
   *
      Shellex
         ContextMenuHandler (this is the same for both IContextMenu and IExplorerCommand)
            ANotepad++64 (this is what NppShell uses)
               (Default) = {00000000-1111-2222-3333-444444444444}
```

So my suggestion would be to:
- Migrate the IExplorerCommand implementation to the NppShell project.
- Update the IExplorerCommand implementation code to honor existing settings registry keys (you can probably look at how the IContextMenu implementation does it).
- Remove the old IContextMenu implementation but re-use its CLSID for the new IExplorerCommand implementation.
- Migrate RegisterSparsePackage and UnregisterSparsePackage as well and export it from the DLL.
- Remove NppModernShell project.
- In the installer, when registering NppShell, detect Windows 11 and if so call RegisterSparsePackage instead of DllRegisterServer (and the other way around for uninstallation)

This seems a lot cleaner (no duplication of functionality, can't end up with two "Edit with Notepad++" entries, installer can treat this as a normal update of NppShell, etc.)

Also, to avoid needing to restart Explorer after registration, one needs to call `SHChangeNotify` with `SHCNE_ASSOCCHANGED`. This can probably be done within RegisterSparsePackage, UnregisterSparsePackage, DllRegisterServer and DllUnregisterServer.

**Comment by GurliGebis** [comment]
@sylveon thanks, and I agree 🙂
@donho you want me to give it a go?

**Comment by donho** [comment]
@GurliGebis 
Yes, it'll be great to have only one dll to maintain.

**Comment by GurliGebis** [comment]
@donho okay, I'll take a look at it - would it be okay if I migrate it into the new project instead?
That way, it would be less moving around, since everything is in there, except for the registry registration.

I also have an idea for changing the Register/Unregister functions to new names, and have them do this:

- Detect which windows version we are on.
- If Windows 11, unregister using the old code on register and register the new way.
- If lower than Windows 11, register in the registry instead.
- Uninstall unregisters both.

That way, installation just has to call the register function, and it handles it correctly, depending on which Windows version you are installing on.

Would that be okay?

**Comment by GurliGebis** [comment]
By that I mean moving the new project into the NppShell folder and renaming stuff

**Comment by donho** [comment]
@GurliGebis 
> That way, installation just has to call the register function, and it handles it correctly, depending on which Windows version you are installing on.

>Would that be okay?

Yes, sounds good to me.

> By that I mean moving the new project into the NppShell folder and renaming stuff

I would say it deserved to be a independent project in [Notepad++ organization](https://github.com/notepad-plus-plus).
What do you think?

**Comment by ozone10** [comment]
@GurliGebis 
IMHO it should be independent project.
Modifying "NppModernShell" source code has no effect on notepad++.exe binary, appveyor is not building it and it blocks appveyor.

And we can use [git submodules](https://git-scm.com/book/en/v2/Git-Tools-Submodules) to include it here.

btw
It can also help other to learn how to implement Windows 11 context menu since it can be easier to find, instead of buried deep inside Notepad++ main repository.

**Comment by GurliGebis** [comment]
@ozone10 you got a compelling argument 🙂
I'll refactor it in this repo, and we can then look at moving it into another repo and add it back as a submodule.
@donho would that be okay with you?

**Comment by donho** [comment]
@GurliGebis 
> I'll refactor it in this repo, and we can then look at moving it into another repo and add it back as a submodule.
@donho would that be okay with you?

It sounds good to me - please mark it as work in progress as you did so it won't trigger the CI's compiling.

**Comment by GurliGebis** [comment]
@donho I will do.
@sylveon If I try and register the handler in the old menu with a IExplorerCommand, the object gets created just fine, but it is not added to the "classic" right click menu.
Any ideas on why that might be? (There seems to be absolutely 0 documentation on how to use IExplorerCommand for anything but APPX/MSIX packages.)

**Comment by donho** [comment]
@GurliGebis 
> Any ideas on why that might be? (There seems to be absolutely 0 documentation on how to use IExplorerCommand for anything but APPX/MSIX packages.)

Absolutely no idea.
I cloned long time ago the project which was the menu entry shell for SciTE: 
https://burgaud.com/scite-context-menu

With the permission of Andre Burgaud (the author), I've modified the  project slightly for meeting Notepad++'s need. You might find some document in the website or you may write to the author.

**Comment by sylveon** [comment]
There is documentation from the Windows 7 days mentioning IExplorerCommand for menus: https://learn.microsoft.com/en-us/windows/win32/shell/how-to-create-cascading-menus-with-the-iexplorercommand-interface

It says:
> In Windows 7 and later, you can provide the same verb implementation using the [IExplorerCommand](https://learn.microsoft.com/en-us/windows/desktop/api/shobjidl_core/nn-shobjidl_core-iexplorercommand) interface as you can with the [IContextMenu](https://learn.microsoft.com/en-us/windows/win32/api/shobjidl_core/nn-shobjidl_core-icontextmenu) interface.

So I suspect something somewhere else is broken.

There's an old sample also from that era here, if that helps: https://github.com/microsoft/Windows-classic-samples/blob/main/Samples/Win7Samples/winui/shell/appshellintegration/ExplorerCommandVerb/ExplorerCommandVerb.cpp

**Comment by GurliGebis** [comment]
I think I have figured it out - I'll take a look at it later.
If my theory is correct, then it is facepalming time 😃

**Comment by mike000000000001** [comment]
My God, this program is a horror. Can't be uninstalled completely, leaves context menu doubled up. Uninstalling for good.

**Comment by GurliGebis** [comment]
@mike000000000001 well, that is what we are working on fixing, but sure, you are welcome to uninstall if that is what is right for you.
@donho and @sylveon Okay, I got a small demo project working, so now I know what changes are needed - yay 🙂

**Comment by alankilborn** [comment]
@mike000000000001 said:

>Uninstalling for good.

Don't forget to apply for your refund by filling out the refund [FORM](https://notepad-plus-plus.org/news/v843-unhappy-users-edition/) on your way out...

**Comment by donho** [comment]
@GurliGebis 
Sorry, I don't follow you - what's **WRL** ?

**Comment by GurliGebis** [comment]
@donho Windows Runtime Library - develop ment has shifted to WIL (Windows Interface Library), but both are fine to use.
WRL is the "old" way of writing COM object, but it seems it is needed here (the sample for sparse packages is also using it, so it is what Microsoft themselves uses)

**Comment by GurliGebis** [comment]
@donho they are pretty small - the size difference on my machine on the x64 DLL is only 5kb larger than the old NppShell dll.

I have create a PR now with the changes, if you can take a look at it (and maybe create an installer for me to test with)? 🙂
#13389

@sylveon thank you for helping with this one, your notes above helped a lot with finding the right place to look.

**Comment by donho** [comment]
The thread becomes huge so let's talk in #13389 then.

**Comment by GurliGebis** [comment]
@donho I agree, can you lock this issue?
