### ISSUE TITLE
NPP 8.4.9 -> 8.5: dark mode, broken explorer control repaint after theme change

### ISSUE THREAD

**Issue by klaus101** [notepad-plus-plus/notepad-plus-plus#13343]
### Description of the Issue
Since NPP 8.5 (it did not occur with NPP 8.4.9), dark mode, when switching to another theme or changing style settings,
the treeview and scrollbar parts of the explorer container windows appear white.

Don't know if it's rather a explorer plugin or an NPP issue, So i think it's better to open a topic here too.
See also https://github.com/oviradoi/npp-explorer-plugin/issues/39
with full description and an attached video too.

Recently the author of the plugin removed some own painting and relies on NPP's repaint of the control container. But at theme or style settings change apparently a notification of the changes are missing or applied too late on the container so that parts of the control are painted using a white default theme.

### Steps to Reproduce the Issue

Steps to reproduce are easy:
- NPP 8.5; Settings > Preferences > Dark Mode > Dark mode on
- Settings > Style Configurator -> choose (example:) "DarkModeDefault"
Restart NPP
- Settings > Style Configurator -> choose (example:) "Deep Black"

==> Parts of the Explorer plugin window are not correctly dark-themed refreshed and appear to be white until next restart.

### Expected Behavior

Control's background adapts immediately when a theme or style setting is changed. The appearance should be according to the theme (as before with 8.4.9).

### Actual Behavior

Treeview and scrollbars appear white themed. When the "Save" button is pressed, the treeview background adapts, but the scrollbar colors are still wrong.

### Debug Information
Notepad++ v8.5   (64-bit)
Build time : Mar  6 2023 - 02:18:13
Path : D:\KHApps\Editors\NPP\NPP\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : ON
Cloud Config : OFF
OS Name : Windows 10 Home (64-bit)
OS Version : 22H2
OS Build : 19045.2673
Current ANSI codepage : 1252
Plugins : 
    Explorer (1.9.8)
    mimeTools (2.9)
    NppConverter (4.5)
    NppExport (0.4)
    NPPJSONViewer (2.0.4)

![Missing_refresh-](https://user-images.githubusercontent.com/31130146/224740355-f374fd13-7511-444c-ac88-9c3655a12e84.jpg)

**Comment by ozone10** [comment]
@klaus101 
could you try alternative https://github.com/funap/npp-explorer-plugin,
if there is no issue with alternative, than it should be plugin issue.

**Comment by klaus101** [comment]
Hello ozone10, thanks a lot for attention!
Yes, this fork alternative doesn't show up the issue described.
But, hm. I don't know if you can draw a conclusion from that it is an issue of the plugin. This issue did not exist until  PP 8.4.9. Why now with 8.5? And, who at the end is reponsible for to paint eg. an invalidated treeview background resp. to refresh it?  I don't assume the plugin told: paint it white ..

**Comment by ozone10** [comment]
@klaus101 
I've just tried it with portable npp v8.4.9 and it's also showed this glitch.
Also even if it was not opened it affected other docking windows, even internal ones.
Also for some reason it also caused visual glitch in other apps not related to Notepad++, even explorer, this is bad.

**Comment by ozone10** [comment]
@klaus101 
having both panels from plugin open, will fix it.
Issue must be caused by some uninitialized variable.

**Comment by klaus101** [comment]
@ozone10, thank you!  Thar sounds very interesting, but i don't quite understand ... what is this second, additional panel from plugin optionally to be opened?

**Comment by ozone10** [comment]
@klaus101 
Explorer panel and Favorites panel

**Comment by klaus101** [comment]
@ozone10 thank you again! Yes, that this is meant had been my first assumtion, but when i tried this,
i had either favorites open or explorer, but not both in parallel.   __But__: retried this morning and, ah, yes i see, it's a separate dialogue;. I had not been aware of that yet - sorry for that ignorance!

-> Yes, when both are opened, the issue does not occur. Interesting! I'll pass the info to the developer.
Thank you!

**Comment by klaus101** [comment]
There had been a comment from the author of the plugin, saying:
"After some more testing, I was able to reproduce the problem. Indeed, it seems it's a problem in Notepad++'s code.
There are several other tree panels built into Notepad++ that have the same issue. They are the Project Panel, and Folder as Workspace.
If you try to open them using File -> Open Folder as Workspace and View -> Project Panels-> Project Panel 1, you will see that all of them have the same problem.
I think you can report this to Notepad++'s team. When they solve this issue it should also be solved for Explorer."

I could reproduce that finding:
having **not** the explorer opened, but when having opened a folder as workspace, i see the issue too. - See image:
![foldler_as_workspace](https://user-images.githubusercontent.com/31130146/224957786-a61d9ba5-dc68-48ec-ac91-50ba9f834248.jpg)

**Comment by klaus101** [comment]
Did a bit more testing.
If i - for test - deinstall the explorer plugin, then the issue as showing up at "Folder as workspace" does NOT occur.
So it might be the plugin, already when being installed/loaded, but not been started?

**Comment by ozone10** [comment]
> Did a bit more testing. If i - for test - deinstall the explorer plugin, then the issue as showing up at "Folder as workspace" does NOT occur. So it might be the plugin, already when being installed/loaded, but not been started?

Yes 
what I said in https://github.com/notepad-plus-plus/notepad-plus-plus/issues/13343#issuecomment-1466826904 about internal panels

**Comment by klaus101** [comment]
@ozone10 
Exactly - fully right!

Meanwhile there are news from the author of the plugin, saying:
> indeed, it seems that the Explorer plugin was causing this problem. Notepad++ did not like it when Explorer invalidated the tree controls after the style changed.
> This issue should be fixed in the latest release, v1.9.9

Tested the update of the plugin and for me it does solve the issue.
So i'd close this topic, after a short period of time for the case of possible comments.

**Comment by klaus101** [comment]
Problem solved by plugiin version 1.9.9; so closing ...
