### ISSUE TITLE
Error while opening files whose name starts/ends with `=` (v8.5, 32b)

### ISSUE THREAD

**Issue by GGa-JJa** [notepad-plus-plus/notepad-plus-plus#13344]
### Description of the Issue
Error while opening files whose name starts/ends with `=`

### Steps to Reproduce the Issue
1. Create a file whose name starts and ends with `=`, e.g. `=NOTE=`
2. Open the file with this command: `"C:\Program Files\npp\notepad++.exe" "P:\ath\of\file\=NOTE="` (or similar, with the correct paths of course)
3. The program opens the file, but it also displays a "cannot open file" error box (see picture).

### Expected Behavior
(just open the file)

### Actual Behavior
(also an error messagebox)

### Debug Information
It's Notepad++ v8.5, 32 bit.
Doing the same as described above was not a problem with older versions, e.g. 6.7.9.2
![immagine](https://user-images.githubusercontent.com/127774868/224767447-bf6624b2-acba-4ee4-9b57-a4830fca8e9b.png)

**Comment by molsonkiko** [comment]
Tried on v8.5 64bit and 32bit, both using terminal and opening with the file explorer. I couldn't replicate it.

**Comment by GGa-JJa** [comment]
Oh... how strange.
What OS did you use?
(I tried on Windows 10)

**Comment by molsonkiko** [comment]
I also am on Windows 10.

**Comment by rddim** [comment]
Confirm

Open `=note=` **with** error message
Open `note=` **with** error message
Open `=note` **without** error message

### Debug Info Win 11
```
Notepad++ v8.5   (64-bit)
Build time : Mar  6 2023 - 02:18:13
Path : D:\Notepad++\notepad++.exe
Command Line : "D:\Notepad++\note="
Admin mode : OFF
Local Conf mode : ON
Cloud Config : D:\Notepad++\_settings
OS Name : Windows 11 Pro (64-bit)
OS Version : 21H2
OS Build : 22000.1696
Current ANSI codepage : 1251
Plugins : 
    AutoSave (2)
    ComparePlus (1.1)
    VisualStudioLineCopy (1.0.0.2)
```

Later today I will test with Win 7

**Comment by xomx** [comment]
@molsonkiko 

> I couldn't replicate it.

Did you try the OP's STR without or with param quotes (as in STR)?

This works ok for me (invoked from my N++ directory):
`notepad++.exe C:\TEMP\=NOTE=`

This does not (the error message about nonexisting `" "` file appears):
`notepad++.exe "C:\TEMP\=NOTE="`

Possible fix:
I do not have a time for debugging & PR, sorry, but I try shooting in the dark - just try to replace [this line](https://github.com/notepad-plus-plus/notepad-plus-plus/blob/ce4d374a4782185f2e0dbaa2e6527ba7f8b9ad39/PowerEditor/src/winmain.cpp#L547) with the following code (taken from my previously rejected PR}:

```
			if ((i + 1) < nbFilesToOpen)
				quotFileName += TEXT("\" "); // use 'space'-char delimiter
			else
				quotFileName += TEXT("\""); // last item
```

**Comment by GGa-JJa** [comment]
> Confirm
> 
> Open `=note=` **with** error message
> Open `note=` **with** error message
> Open `=note` **without** error message

Yes, I made some more "testing" and it's the same: the `=` at the end of the name is the problem.
The same error applies for files like "note.txt=", but not for "note=.txt".

A question for [molsonkiko](https://github.com/molsonkiko) that couldn't replicate: of course, you are not hiding the file extension (like some geniuses at microsoft think should be the default), right?

**Comment by GGa-JJa** [comment]
> This works ok for me (invoked from my N++ directory): `notepad++.exe C:\TEMP\=NOTE=`
> This does not (the error message about nonexisting `" "` file appears): `notepad++.exe "C:\TEMP\=NOTE="`

Very interesting, I didn't try this! (B.t.w. thany you _all_ for trying!).
My files are opened with quotes for two reasons:
1) There may be spaces, as usual, and
2) The command is written in the registry, and as a non-administrator I cannot edit it (I could just replace the NP++ program, but the registry is off-limits).
Any ideas for a workaround? (Except renaming the .exe and replacing with another program that modies the arguments and then calls the renamed .exe...)
Or should I think that a new version will soon correct the issue?

(It may seeem very silly, but I have notes and explanations for nearly all my works in files named with that pattern... funny, eh?)

**Comment by molsonkiko** [comment]
I have been doing this without an extension.

Trying it again with and without quotes, I found the following:

name      | quotes? | result
----------|-----------|------
=note  | yes | good
note=   | yes | bad
=note=  |yes | bad
=note |no | good
note=|no | good
=note|no | good

This is consistent with what you all have observed.

**Comment by molsonkiko** [comment]
Just for fun, I also tried filenames ending in `_`, `~`, `^`, `v`, `-`, `)`, and `(`. None of those ending characters caused weird behavior whether in or out of quotes (if possible; `v` can't be outside of quotes)

**Comment by Yaron10** [comment]
> Doing the same as described above was not a problem with older versions, e.g. 6.7.9.2

This regression was introduced in a relatively recent version.

**Comment by jofon** [comment]
@Yaron10 
Before the error dialog was introduced by #12613, in v8.4.8, the problem would be silently ignored.

**Comment by Yaron10** [comment]
@jofon,

Thank you for pointing that out.

> The last "stable" version is 8.4.7

I've just noticed that sentence by @rddim.

**Comment by GGa-JJa** [comment]
Happy to notice that someone took care of "my" problem ^_^
(Thank you!)

So, any hope of a fix in a "stable" new version?

**Comment by Yaron10** [comment]
A rare case. Just for the record.

Change a new tab name to to `Test ` (Test + Space).
Open the Find dialog and "Find All in Current Document".
Double-click an entry in the Search Results window.

Result:
An error message: "Cannot open file Test ".

**Comment by alankilborn** [comment]
>Change a new tab name to to Test (Test + Space).

IMO, a soft-named tab should not be allowed to have space(s) before the first (non-space) character, nor after the last (non-space) character.  [ It feels unclean just typing that.  :-) ]

It just isn't necessary.  This should have been thought of when renaming of soft-named (i.e., `new #`) tabs was implemented.  A user-supplied name should have been "trimmed" of whitespace on the left side and the right side.

**Comment by Yaron10** [comment]
@alankilborn,

I agree. Do you think it's worth the extra code?

It occurred to me to test it after seeing @donho's nice PR (https://github.com/notepad-plus-plus/notepad-plus-plus/pull/13960).
The Search Results' "title" is apparently "New ", and I was wondering what should happen if there was a tab named "New ".

**Comment by alankilborn** [comment]
>Do you think it's worth the extra code?

I do; it shouldn't be much code.

>The Search Results' "title" is apparently "New "

Maybe it should be given a better title, even if there is no purpose (user wouldn't see it) other than to avoid potential "N++ programmer" confusion at some future point.

**Comment by Yaron10** [comment]
> I do; it shouldn't be much code.

OK.

> Maybe it should be given a better title, even if there is no purpose (user wouldn't see it) other than to avoid potential "N++ programmer" confusion at some future point.

I see your point.
And again I'm wondering if it's worth the extra code. :)
I suppose @donho should see this.

**Comment by donho** [comment]
Do you think it's worth the extra code?

    I do; it shouldn't be much code.

@alankilborn 
If you're interested in doing it, then go ahead please. Otherwise I'm gonna fix it.

**Comment by alankilborn** [comment]
>If you're interested in doing it

@donho  I would, but I'm currently not set up to do so; I've been trying for a while to find time to get my new PC fully set up, but I'm not there yet.

>Otherwise I'm gonna fix it.

Please go ahead.  Thank you.

**Comment by Yaron10** [comment]
@donho,

> Otherwise I'm gonna fix it.

Thank you.

@alankilborn,

Congratulations!
