### ISSUE TITLE
Feature Request: Select multiple tabs by holding down the shift key

### ISSUE THREAD

**Issue by Elmar010** [notepad-plus-plus/notepad-plus-plus#13357]
**Description of the requested Feature**
Select multiple tabs by holding down the SHIFT key and close them all at the same time with the close tab keyboard shortcut (Shortcut mapper --> Main menu --> 13 Close). This feature is possible in Microsoft Edge and I would like it in Notepad++ as well.

**Steps to Reproduce the requested Feature**
1. Select multiple tabs by holding down the SHIFT key
2. Close all selected tabs with the close tab feature (my case: Ctrl+W)

**Expected Behavior**
All selected tabs are closed in the normal close tab way.

**Actual Behavior**
N/A

**Comment by alankilborn** [comment]
Possibly similar idea for this that the author of N++ seemed to like:  https://github.com/notepad-plus-plus/notepad-plus-plus/pull/13291#issuecomment-1503366788

**Comment by donho** [comment]
There's no (or very difficult) way to implement this feature.
You can use Document List for such purpose.

**Comment by cmvalma** [comment]
Chrome, and almost any other Chromium-based browsers do this (you select multiple tabs by pressing the Shift key). How can it be so difficult in Edge?
