### ISSUE TITLE
Notepad autocloses/crashes while searching

### ISSUE THREAD

**Issue by Silassentinel** [notepad-plus-plus/notepad-plus-plus#13351]
### Description of the Issue
Whilst working with any kind of file in notepad++ and searching, the application closes without any message.

After encountering this a few times I checked  Event-Viewer.

There I found an entry stating the following: 

Level : Error
Source: .NET Runtime
Application: notepad++.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: exception code c0000005, exception address 00007FF7D8733220
Stack:

And this: 
Faulting application name: notepad++.exe, version: 8.4.8.0, time stamp: 0x63a747f8
Faulting module name: notepad++.exe, version: 8.4.8.0, time stamp: 0x63a747f8
Exception code: 0xc0000005
Fault offset: 0x0000000000203220
Faulting process id: 0x0x1690
Faulting application start time: 0x0x1D95739421248AE
Faulting application path: C:\Program Files\Notepad++\notepad++.exe
Faulting module path: C:\Program Files\Notepad++\notepad++.exe
Report Id: 36e7a023-5452-458f-88c1-70ad7daf10d8
Faulting package full name: 
Faulting package-relative application ID: 

### Steps to Reproduce the Issue
1. Open a file
2. Press ctrl + f to open search
3.  Enter a word to find
4. Click next a few times

### Expected Behavior
Notepad++ does not autocloses.

### Actual Behavior
Notepad++ autocloses.

### Debug Information
Notepad++ v8.4.8   (64-bit)
Build time : Dec 24 2022 - 19:40:27
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 11 (64-bit) 
OS Version : 22H2
OS Build : 22621.1265
Current ANSI codepage : 1252
Plugins : 
    CSScriptNpp (2.0.2)
    CSVLint (0.4.5.4)
    CsvQuery (1.2.9)
    GitSCM (1.4.7.1)
    JSMinNPP (1.2205)
    JsonTools (3)
    mimeTools (2.9)
    NppConverter (4.5)
    NppExport (0.4)
    NPPJSONViewer (1.40)
    Python Indent (1.0.0.4)
    PythonScript (2)
    XMLTools (3.1.1.13)

### aditional info:

I found that this : 0xc0000005 
Refers to a nullpointer exception/ writing to a wrong address
see link : https://learn.microsoft.com/en-us/shows/inside/c0000005

**Comment by molsonkiko** [comment]
Probably CsvQuery, CsvLint, or JsonTools, since those are made using .NET.
Older versions of JsonTools (to my shame) have some crash bugs (though none that happened so frequently on my computer), and it's probably worth upgrading to a newer version if you find that's the problem.
