### ISSUE TITLE
Microsoft SQL sorted under `T` instead of `M` in styler language menu

### ISSUE THREAD

**Issue by rdipardo** [notepad-plus-plus/notepad-plus-plus#13367]
### Description of the Issue

Since 2474cbea, the Style Configurator sorts languages alphabetically by *description* &#x2014; *not* identifier; e.g. "Fortran (fixed form)", *not* [fortan77].

A user looking for Microsoft SQL has to scroll down to "TeX" because the current description starts with `T`:

https://github.com/notepad-plus-plus/notepad-plus-plus/blob/5645ca150bf9b24813d5da7ee3a061e1306837d9/PowerEditor/src/stylers.model.xml#L730

<img width="230" alt="stylers-menu-v8 5 1" src="https://user-images.githubusercontent.com/59004801/226089436-2389d55b-fde3-4f82-956f-8b44afa69a34.png">

### Steps to Reproduce the Issue
1. Download/install [a release candidate build] of 8.5.1
2. <kbd>Settings</kbd> > <kbd>Style Configurator...</kbd>
3. Scroll the language listbox down to "Makefile" . . . . "Matlab" . . . "MMIXAL" . . .
4. No "Microsoft SQL" so keep looking . . .
5. "Tektronix extended HEX" . . . "TeX" . . .
6. Finally find "T-SQL (MS SQL Server)"

### Expected Behavior

Scroll to "Makefile" . . . . "Matlab" . . . find "Microsoft SQL"

### Actual Behavior

> 5. "Tektronix extended HEX" . . . "TeX" . . .
> 6. Finally find "T-SQL (MS SQL Server)"

### Debug Information

    Notepad++ v8.5.1   (32-bit)
    Build time : Mar 17 2023 - 02:32:57
    Path : C:\Users\Public\Downloads\npp.8.5.1.rc\notepad++.exe
    Command Line :
    Admin mode : OFF
    Local Conf mode : ON
    Cloud Config : OFF
    OS Name : Windows 10 Enterprise (64-bit)
    OS Version : 21H2
    OS Build : 19044.2728
    Current ANSI codepage : 1252
    Plugins :
        mimeTools (2.9)
        NppConverter (4.5)
        NppExport (0.4)

[fortan77]: https://github.com/notepad-plus-plus/notepad-plus-plus/blob/5645ca150bf9b24813d5da7ee3a061e1306837d9/PowerEditor/src/stylers.model.xml#L463
[a release candidate build]: http://download.notepad-plus-plus.org/repository/8.x/8.5.1.RC/

**Comment by rimrul** [comment]
T-SQL or Transact-SQL is the proper name, though. Microsoft uses that name, too.

https://learn.microsoft.com/en-us/sql/t-sql/language-reference?view=sql-server-ver16

**Comment by Yaron10** [comment]
It's under M in the Language menu, and I was also looking it up under M in the Style Configurator.
If `Transact-SQL` is the proper name, it should be moved to T in the Language menu.

**Comment by donho** [comment]
[Transact-SQL (T-SQL) is Microsoft's and Sybase's proprietary extension to the SQL](https://en.wikipedia.org/wiki/Transact-SQL).
So I think that we can remove the word "Microsoft" completely. 
What do you guys think?

**Comment by Yaron10** [comment]
@donho,

Personally I prefer the shorter term.
Whatever you prefer would be good if the Language menu and the Style Configurator were "synced".

**Comment by rdipardo** [comment]
> Personally I prefer the shorter term. Whatever you prefer would be good if the Language menu and the Style Configurator were "synced".

:+1:

However the Style Configurator listbox is only ~12 characters wide and can't be scrolled horizontally, 

That's why I suggested "Microsoft SQL". It's brief enough to be completely legible and sorts with 'M' like the <kbd>Language</kbd> toolbar menu already does.

<img width="480" alt="stylers-menu-patched-v8 5 1" src="https://user-images.githubusercontent.com/59004801/226141552-7588cb29-371b-4670-991c-67a414433917.png">

**Comment by Yaron10** [comment]
> However the Style Configurator listbox is only ~12 characters

That could be changed. :)

> That's why I suggested "Microsoft SQL".

👍 
Whatever you and the others prefer.
