### ISSUE TITLE
Two minor issues with Close Button

### ISSUE THREAD

**Issue by Yaron10** [notepad-plus-plus/notepad-plus-plus#1336]
1) If "Reduce" is unchecked, the Close button is not centered.

![np-6 8](https://cloud.githubusercontent.com/assets/10229320/12189350/730dd3c6-b5c5-11e5-9913-0693fc05c0b6.PNG)

2) A regression in recent versions: in RTL locals, the button is cut off (width is only 10px).

The following screenshot is v6.7 (width is 11px). 
![np-6 7](https://cloud.githubusercontent.com/assets/10229320/12189326/4eda3d96-b5c5-11e5-8fee-33e61ccb0684.PNG)

**Comment by kraint** [comment]
Appears to be redundant with #1705.

**Comment by Yaron10** [comment]
@kraint,

Thanks.
