### ISSUE TITLE
Notepad++ consistently not indicating updates and says there is no update when there is one. [Possibly due to NORTON]

### ISSUE THREAD

**Issue by coder1000** [notepad-plus-plus/notepad-plus-plus#13366]
### Description of the Issue

1. Disconnect:  Notepad++ will claim no update is available when there has been one available for weeks, possibly months, possibly longer. This behavior has emerged in the last year or so.
2. Regression:   Notepad++ will not indicate there is an update like it used to. This behavior has emerged in the last year or so.
3. Suspicion:  I have Norton installed, which "checks your software versions for you". This new feature has emerged in the last year or so.

### Steps to Reproduce the Issue

1. Wait until an update is available.
2. Notice that no popup dialog box appears saying there is a new version available.
3. Attempt an update
4. Maybe see how many weeks or months go by where Notepad++ will not indicate an update
5. You may need to have software installed like in this case NORTON which has an obligatory feature that "checks your software versions for you".

### Expected Behavior

Notepad++ is supposed to say that it has an update available in a dialog box, or
in the case of using the update menu that it will update (because it sees that an update has been triggered.

### Actual Behavior

Notepad++ will not alert about updates anymore and claims an update is not available or that the update process has not been triggered.

It's certainly triggering me, I can tell you that.

### Debug Information

Notepad++ v8.5   (64-bit)
Build time : Mar  6 2023 - 02:18:13
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : "C:\Program Files\Notepad++\change.log" 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 11 Pro (64-bit)
OS Version : 22H2
OS Build : 22621.1413
Current ANSI codepage : 1252
Plugins : 
    DSpellCheck (1.4.24)
    mimeTools (2.9)
    NppConverter (4.5)
    NppExport (0.4)

Suggested Resolution:

One of:
1. Fix the problem that has nothing to do with Norton or other software; or
2. Alternatively, include a warning statement in the update window when no updates are available that other software such as Norton might possibly or can deliberately attempt to override Notepad++'s update logistics.  Possibly include an image of offending software as a caricature in a manner that would be inappropriate to describe in this issue description.

**Comment by alankilborn** [comment]
>I have Norton installed, which "checks your software versions for you".

Ugh.  For this to work, wouldn't there have to be some standard way for all applications to indicate they have an update available?  There probably is... but I'm sure that Notepad++ isn't conforming.  But I wouldn't call that a bug in N++, I'd call it a lack of interest by N++ developers to participate in that.

---------------------------------------

The timeline is vague.  Well OK, you say it has been "weeks/months".  But note this fact:  Not every released version of Notepad++ is judged "good" enough to trigger a mass update alert.  This is a common complaint: Users haven't seen an update notice in a while, they go to the website and see newer releases and then complain they weren't notified.  If a release isn't good enough for a mass notify, perhaps be glad you didn't get one.

-------------------------------

Just my 2c.

**Comment by coder1000** [comment]
> > I have Norton installed, which "checks your software versions for you".
> Ugh. For this to work, wouldn't there have to be some standard way for all applications to indicate they have an update available? There probably is... but I'm sure that Notepad++ isn't conforming. But I wouldn't call that a bug in N++, I'd call it a 

Ah, yeah so what Norton is apparently doing is going after popular programs like Notepad++ and figuring out how they update. So, literally Norton has in its little update list an entry that says "Notepad++" ... along with the installed version and the current version numbers.  So they've gotten at least that far.  But apparently they may have gotten a lot farther:  to disengage the update facilities inside Notepad++.


> note this fact: Not every released version of Notepad++ is judged "good" enough to trigger a mass update alert.
...
>  If a release isn't good enough for a mass notify, perhaps be glad you didn't get one.

I think the really insidious thing that seems to be going on with Norton is if the user goes to Notepad++'s "?"  menu and actually selects "Update Notepad++" to straight up request an update, the update dialog attempts to run but will ALWAYS come back with that there's no update available.   I can understand this happening a couple times or at first, but this is consistent and it is not going away.

Notepad++ needs some way to recognize that it's being interfered with if indeed that is the case.

There's another really big problem here that may not be immediately obvious:
If this is happening to me, how many other users are and will be sitting with old versions of Notepad++ on their machines and they don't pay attention to the Norton thing, it's just installed and they don't even run it but it wrecks Notepad++ anyway?

So there might be a rather large number of Notepad++ users who have no idea they're way out of date. For a really long time, right? And that number could grow and cause problems for Notepad++ because it keeps the software stagnated across a population of users and all their machines.

That scenario is all kinds of bad.

**Comment by matteotomasoni** [comment]
I think I have the same problem but I don't have anything Norton on my PC.
In the image you can see the update window of Notepad++ v8.5.1 that says "No update is available" while in the background on the official webpage we can clearly see that 8.5.2 has been available since at least 6 days.
![image](https://user-images.githubusercontent.com/26254320/231393472-623dbde3-570d-40eb-bdf1-bf279b3c7fac.png)

I tried running the updater manually, and it says the latest version is 8.4.8
I think the error is on the Notepad++ server, because the "getDowbloadUrl.php" page says:
