### ISSUE TITLE
Make feature "swap/copy" in "replace dialog" more discoverable

### ISSUE THREAD

**Issue by conky77** [notepad-plus-plus/notepad-plus-plus#13368]
### Description of the Issue

Only by right-clicking on replace dialog, you discover some commands 

from 8.5.1 release note (release candidate)
“Add ability to copy “Find what” to “Replace with” and vice versa in Find Replace dialog. (Fix #12122  )”

![immagine](https://user-images.githubusercontent.com/59116246/226095574-b16aaa66-9247-4465-9044-a89dc7bcfb03.png)

See also the topic [in the community announcement 	Notepad++ v8.5.1 Release Candidate](https://community.notepad-plus-plus.org/topic/24262/notepad-v8-5-1-release-candidate/13)

### Steps to Reproduce the Issue

1.  open find replace dialog, replace section  
2.  right click on the icon close to "find what"
3.  some functionalities appear (you have to know that by right-clicking somewhere, something happens)

### Expected Behavior

To make this feature more discoverable 
(even if you wrote that on the manual, you would look for a manual only whether you think you need to understand something better)
A possible solution could be to modify the current button
![immagine](https://user-images.githubusercontent.com/59116246/226097040-4bf745cf-2af6-48f0-adc4-7fa56e8f402a.png)
in order to get something like that
![immagine](https://user-images.githubusercontent.com/59116246/226097630-a3ac7a65-e804-42eb-b152-d28739704335.png)

Another solution could be to add 3 different buttons

### Actual Behavior

feature hardly discoverable

### Debug Information

Notepad++ v8.5.1   (64-bit)
Build time : Mar 17 2023 - 02:35:00
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 11 Home (64-bit)
OS Version : 22H2
OS Build : 22621.1413
Current ANSI codepage : 1252
Plugins : 
    ComparePlugin (2.0.2)
    CSVLint (0.4.6.2)
    DSpellCheck (1.5)
    JsonTools (4.11.1)
    mimeTools (2.9)
    NppConverter (4.5)
    NppExport (0.4)
    NPPJSONViewer (2.0.4)
    NppXmlTreeviewPlugin (2)
    XMLTools (3.1.1.13)

**Comment by alankilborn** [comment]
Dude, weren't you just told to "read the release notes"?
There's something to be said for "learning about the software you intend to use".
Now that you know about this feature, are you ever going to forget about it?

Please don't start picking apart the Notepad++ UI for UX issues -- it will be never-ending and this issues list will grow exponentially.

**Comment by ozone10** [comment]
@donho 
can I do this?

**Comment by donho** [comment]
@ozone10 
Sure. But the present GUI on the image is not what I want.
I would put the flash button blow the swap button so we don't change the coordination of other controls.
Are you always interested in doing it?

**Comment by ozone10** [comment]
@donho 
what do you mean flash button? Button which open context menu?

I did some quick coding with split button.

![image](https://user-images.githubusercontent.com/55940305/226119241-4fb917a3-e632-4ba2-8cf0-7336787c3103.png)
![image](https://user-images.githubusercontent.com/55940305/226119269-54769395-2a38-4fa4-a7e7-31b56fe49dea.png)
![image](https://user-images.githubusercontent.com/55940305/226119312-d8b97649-78de-4653-9c88-fd0bcede2fd6.png)

**Comment by donho** [comment]
@ozone10 
> what do you mean flash button? Button which open context menu?

Sorry I meant "Arrow down" button ( Arrow In French is flêche - I was mistaking).

What I prefer is as the following GUI:

![image](https://user-images.githubusercontent.com/90293/226120894-d31f2f45-8be8-4ac5-9ca9-1ff68811f6b0.png)

**Comment by ozone10** [comment]
@donho 
I see, but this separate button might confuse users, they might think that it move "Find what" text to "Replace with"

btw 
there seems to be visual glitch with checkbox focus rectangles
I also want to fix https://github.com/notepad-plus-plus/notepad-plus-plus/issues/13021

So I might need to change some controls coordination.

**Comment by donho** [comment]
@ozone10 
For fixing https://github.com/notepad-plus-plus/notepad-plus-plus/issues/13021 it needs to change some controls' order in RC but not their coordination in dialog.

> I see, but this separate button might confuse users, they might think that it move "Find what" text to "Replace with"

From the images you provided, they are 2 buttons side by side right? So it's the same with 2 up & down buttons - and we can make them very close. I don't think it's confusing. In the worst case, users will click both of them they will find out what the buttons use for.
My goal is to keep the both combobox find what & replace with as large as possible, for the sake of usability.

**Comment by ozone10** [comment]
@donho 
it is only one button. It has style [BS_SPLITBUTTON](https://learn.microsoft.com/en-us/windows/win32/controls/button-styles#constants)

I did not change comboboxes size, I only moved right controls little right. 

Note for coordinates is for checkbox buttons.

**Comment by rddim** [comment]
I prefer @ozone10's solution, but if possible make the button a bit smaller

**Comment by donho** [comment]
@ozone10 
> it is only one button. It has style [BS_SPLITBUTTON](https://learn.microsoft.com/en-us/windows/win32/controls/button-styles#constants)

Sounds interesting.
OK, please do the PR. I will see the effect.
