### ISSUE TITLE
Find & replace in files badly crash after some files

### ISSUE THREAD

**Issue by squeeze69** [notepad-plus-plus/notepad-plus-plus#13369]
### Description of the Issue
Find & replace in files silently crash after some files, nothing is saved (status & so on)

### Steps to Reproduce the Issue
1.open np++ 
2. select find&replace in files, more than a 100 files in several subdirs (i.e.: php files), plain text search, case insensitive. 
3. start and see the crash

### Expected Behavior
...word replaced in every file

### Actual Behavior
crash after some files

### Debug Information
Notepad++ v8.5   (32-bit)
Build time : Mar  6 2023 - 02:15:26
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 10 Enterprise (64-bit)
OS Version : 21H2
OS Build : 19044.2604
Current ANSI codepage : 1252
Plugins : 
    AutoSave (2)
    GOnpp (1.2)
    HTMLTag_unicode (1.3.6)
    JsonTools (4.10)
    mimeTools (2.9)
    NppConverter (4.5)
    NppExport (0.4)
    NPPJSONViewer (2.0.4)

**Comment by rdipardo** [comment]
See https://github.com/notepad-plus-plus/notepad-plus-plus/issues/13351#issuecomment-1470694032

Upgrading to [the latest version of JsonTools](https://github.com/molsonkiko/JsonToolsNppPlugin/releases) is most likely all you need

**Comment by squeeze69** [comment]
Thanks. It worked flawlessly.
