### ISSUE TITLE
Voice dictation in Notepad++?

### ISSUE THREAD

**Issue by worldor** [notepad-plus-plus/notepad-plus-plus#13361]
Voice dictation in Notepad++?

Thanks!

**Comment by alankilborn** [comment]
Please ask questions [HERE](https://community.notepad-plus-plus.org/).

**Comment by worldor** [comment]
thanks but I dont want to expose my email to anyone?

**Comment by alankilborn** [comment]
>thanks but I dont want to expose my email to anyone?

???

You have a github id; log in with that?

**Comment by worldor** [comment]
unfortunately it says that I will have to share my email with the owner
