### ISSUE TITLE
[Feature request] "Find in Files progress" dialog show number of hits and num of files searched

### ISSUE THREAD

**Issue by Explorer09** [notepad-plus-plus/notepad-plus-plus#13364]
### Description of the Issue
The current "Find in Files progress" dialog only shows the filename, a progress bar, and a Cancel button. When the user just needs to get the first few matches of the keyword in a large directory tree, the user has to wait for the whole operation to finish even though it's technically possible to stop the Find progress in the middle and let the user continue their work quickly.

This is a UI suggestion:
1. Rename the "Cancel" button in the "Find in Files progress" dialog to "Stop", since the latter describes the action more accurately.
2. During the progress, show the number of hits, number of files containing the hits, and number of files searched so far, roughly in this format: `%u hits in %u files of %u searched` (this is the same format as used in the "Search results" panel)

![notepadpp-find-in-files-progress-suggestion](https://user-images.githubusercontent.com/2487263/225832797-cd17a30d-3483-4696-b9db-aedc197e3f84.png)

Related to #11459, except that my suggestion has a more practical use case.

### Steps to Reproduce the Issue
1. "Search" -> "Find in Files"
2. Choose a large directory, e.g. "C:\", for the "Directory" field, and a keyword ("Find what") that probably appears only once or twice.
3. Click "Find All"
4. Wait.

### Debug Information
```
Notepad++ v8.5   (64-bit)
Build time : Mar  6 2023 - 02:18:13
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 10 Pro (64-bit)
OS Version : 1909
OS Build : 18363.418
Current ANSI codepage : 950
Plugins : 
    mimeTools (2.9)
    NppConverter (4.5)
    NppExport (0.4)
```

**Comment by klaus101** [comment]
Good request in my eyes.

Except, imo, that the total number of files (.... of 20478) should not be a part of it. Please don't.
Probably that does imply a noticeable slowdown!
Afaik there is no simple call to the OS: "tell me the total number of files within drive C: oder folder x".

Does mean: you need to loop along all objects for to get the total count.
Afterwards there's a second loop for to do the search itself.
Instead of that, i'd recommend to use a kind of cycling bar that does not need to know the total number at the beginning.

**Comment by alankilborn** [comment]
@klaus101 

Notepad++ currently builds the list of files that it is going to search, before the search actually starts, so it knows the "of xxx searched" number already:

https://github.com/notepad-plus-plus/notepad-plus-plus/blob/5645ca150bf9b24813d5da7ee3a061e1306837d9/PowerEditor/src/Notepad_plus.cpp#L1997-L2004

**Comment by klaus101** [comment]
@alankilborn 
Alan, thank you!
If the count is already known, then it's ok so far about the request.

But can you tell how long it might take to retrieve this number for a highly populated folder, having, let's say, 60000 files?

If it's done via a background thread meanwhile, then this is a different story.

If, as you say,  it's done besides on the fly when building the file list, i don't quite understand:
I'd expected that eg- by using a filter mask (eg.*.cpp)  the number of files requested from the file system might have been shrinked a lot. already. 
Would that mean that the total count does refer to the humber that results after having a filter applied for the search?
Lert's say there are only 3 files for a certain extension are in there, total count would say "of 3", not "of 60000". Then i could understand iit, sorry then  if i should have misinterpreted.

**Comment by alankilborn** [comment]
>But can you tell how long it might take to retrieve this number for a highly populated folder, having, let's say, 60000 files?

It doesn't matter.  It isn't about the "number", it is about the list of filenames that will be searched.  So I'm confused about this question...

>If it's done via a background thread meanwhile

AFAIK, Notepad++ never uses more than one thread.  I think Scintilla (the underlying editing component) can, but not Notepad++ itself.  Scintilla is NOT involved in the setup of a find-in-files search, only the direct "find the string" part.

>Let's say there are only 3 files for a certain extension are in there, total count would say "of 3", not "of 60000"

Yes, that is how it works.

**Comment by alankilborn** [comment]
Maybe a better suggestion for an "in progress" search would be:

`12 hits in 34 files of 50 searched so far, 3456 remaining...`

**Comment by klaus101** [comment]
> Yes, that is how it works.

OK, so no unneccesary I/Os so far, that's reassuring. Really many thanks for having clarified!

> of 50 searched .. 3456 remaining

That let's me feel a bit confused .. If the total sum is 3456 (remaining) plus 50, why then "of 50" (instead "of 3506") ?
Intuitively i would assume the first number should be bigger than the second -> eg.  "of 3506 searched .. 3456 remaining"

**Comment by alankilborn** [comment]
>That let's me feel a bit confused .. 

It can be as complicated as you want (to the limits of tolerance of the N++ developers):

`12 hits in 34 files of 50 searched so far out of 3506 total with 3456 remaining`

In reality probably these numbers would change so fast that it really wouldn't matter anyway.
The longer the information is, the less chance your eyes/brain can take it all in before it changes, too.

This feature might only be valuable so those seeking ONE hit can cancel the search when they see non-zero in the very first part.

**Comment by klaus101** [comment]
@alankilborn 
Oh, personally i have absoklutely no need to see many numbers --.
The major concern had been not to loose additional time simply for to determine a maxcount. I understood there won't, so all is fine :-) 👍

**Comment by Explorer09** [comment]
Just to answer your questions

> Afaik there is no simple call to the OS: "tell me the total number of files within drive C: oder folder x".
> 
> Does mean: you need to loop along all objects for to get the total count. Afterwards there's a second loop for to do the search itself. Instead of that, i'd recommend to use a kind of cycling bar that does not need to know the total number at the beginning.

The UI I suggested isn't about the total number of files, but the number of files _that have been opened and searched_. The latter information should be available already. It's just about showing it, so that the user can tell, e.g. that Notepad++ isn't stuck reading a large file.

The "number of files remaining" count may not be technically known from the start, so I'm not suggesting showing that. (If it's not known, then the dialog can show an indeterminate progress bar, but that's outside the scope of this feature request.)

**Comment by klaus101** [comment]
Yes, my assumption had been wrong ... but i'm happy about that. Thank you both for clarification!!

**Comment by Explorer09** [comment]
@alankilborn 

> This feature might only be valuable so those seeking ONE hit can cancel the search when they see non-zero in the very first part.

Yes. That's the primary use case for the feature, and it happened to me a lot of time when I was just looking for the definition of a particular C/C++ structure or API, and I did not need to know where the API were used and how many uses at the moment.
Instead of a checkbox to tell Notepad++ to stop after the first hit, it's _way less disruptive_ to the users if we just let Notepad++ report the number of hits (in a text label) as the search progress goes. If the users think they can wait, then wait. Otherwise the user can press the Stop button when they think they have enough hits already.

**Comment by klaus101** [comment]
I'd  have thoughts somehow near by. I'd written a kind of wiingrep for myself (long ago) and did it so:
- at the first hit of a search string within a file, it (the thread) stops searching within this file and enters it's name into a listbox, whilst continuing searching in the next file(s)
- if i click onto the listbox item, it opens the file in the viewer and highlights this first occurance.
- With F3 here i could step to a next occurance, if any..

But that's only because (purely personal habit!) i'm not interested in the # of occurances, but want to reach the occurances within their contexts in the viewer easily.
Yes, personal usage habits are different ... (surely a nightmare for developers) ...

**Comment by alankilborn** [comment]
@Explorer09 and/or @klaus101 
If you want to try out a prototype of this change (only shows inprogress hits number), you can get a test exe from #13404

**Comment by klaus101** [comment]
@alankilborn 
Sorry for my lack of info Alan how to get the executable from there, but as seen from the screeenshot it appears to me the prototype is on a good way. Just showing at least the number of hits so far is an improvement anyway!

**Comment by alankilborn** [comment]
@klaus101 You can find instructions for getting an exe for testing [HERE](https://github.com/notepad-plus-plus/notepad-plus-plus/wiki/Testing#using-a-pull-request-pr-build-version-of-notepad) if you  want to try it out.  Thanks.

**Comment by klaus101** [comment]
@alankilborn 
Oh .. probably not the next days where i'm somehow short in time. Would need a bit for to get familiar with this build environment.
Actually i'd fully rely on what the screenshot let us see, i feel optimistic here.

**Comment by alankilborn** [comment]
>Would need a bit for to get familiar with this build environment.

FYI: You don't have to "build" anything.

**Comment by klaus101** [comment]
@alankilborn 
I have it already on my to-try list for the next free time ... :-)
Thank you Alan for all those infos, all the best!
