### ISSUE TITLE
Npp 8.5.0 does not show EOL_annotation anymore

### ISSUE THREAD

**Issue by Ekopalypse** [notepad-plus-plus/notepad-plus-plus#13360]
### Description of the Issue
Npp version 8.5.0 (the right one in the image) no longer shows end-of-line annotations.
Npp version 8.4.9 (the left one in the image) works as expected.

The missing part is `Undefined name ANNOTATIONVISIBLE`

### Debug Information
Notepad++ v8.5   (64-bit)
Build time : Mar  6 2023 - 02:18:13
Path : D:\Tests\npp\850\x64\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 10 Pro (64-bit)
OS Version : 21H2
OS Build : 19044.2364
Current ANSI codepage : 1252
Plugins : 
    EnhanceAnyLexer (1.1.3)
    mimeTools (2.9)
    NppConverter (4.5)
    NppExport (0.4)
    NppLspClient (0.0.13)

![image](https://user-images.githubusercontent.com/47723516/225757438-d7ab6220-b3f9-4c54-88e7-9ed43c557c1d.png)

**Comment by vinsworldcom** [comment]
Seems to work for me with NppExec:

![image](https://user-images.githubusercontent.com/9657169/225763758-d14d16e3-1851-4273-8afb-f530cfad9d0a.png)

Though I thought the 0x102 would make the pointing left, rounded right border you have, but it doesn't.  Could be my misuse of styles?

Cheers.

**Comment by Ekopalypse** [comment]
Hi Vince, thanks for double checking and letting me know.
I can confirm that using NppExec works. For me even with the right layout.
![image](https://user-images.githubusercontent.com/47723516/225828763-92954fae-c0a3-498a-928e-f74907760e5a.png)

Requires further investigation. Closed for the time being.
