### ISSUE TITLE
Can you change that 8==D around, cause now it's a dick

### ISSUE THREAD

**Issue by Antosser** [notepad-plus-plus/notepad-plus-plus#13384]
https://github.com/notepad-plus-plus/notepad-plus-plus/blob/9c15bdc236d5f62f4f418f26bee189638a380f86/PowerEditor/src/Parameters.cpp#L8256

**Comment by donho** [comment]
How come **now** it's a dick?
It was, it is and it will be always a dick. :)

**Comment by Antosser** [comment]
> How come **now** it's a dick?
> It was, it is and it will be always a dick. :)

*Right now

**Comment by Antosser** [comment]
It is also considered very bad practice to name variables single letters / abbreviations. I saw a lot of that in the code. I understand the rvalue being on the left hs tho; that gives an error if you use one = instead of two

**Comment by alankilborn** [comment]
I think it is all about...well...exactly how it is.

**Comment by Antosser** [comment]
Nah Nah... I see the commit message 
![image](https://user-images.githubusercontent.com/71790328/227795837-2719060d-da7e-4e52-9bea-96c2fee8e009.png)
