### ISSUE TITLE
Select and Find Next: Create the Find Dialog Invisibly

### ISSUE THREAD

**Issue by Yaron10** [notepad-plus-plus/notepad-plus-plus#13381]
**STR:**
Open NPP.
Do not open the Find dialog.
Select and Find Next.

**Result:**
The Find dialog is displayed for a split second and then hidden.
This causes a "flickering effect".

**Expected:**
Avoid the flickering and create the Find dialog invisibly.

***

Notepad++ 8.5.1.

**Comment by alankilborn** [comment]
#9536 ?

**Comment by Yaron10** [comment]
@alankilborn,

👍 
Does the "Walking Encyclopedia" remember ALL issues? :)
Let's keep this one open as I've just referenced it in https://github.com/notepad-plus-plus/notepad-plus-plus/pull/13372#issuecomment-1476139576.

**Comment by alankilborn** [comment]
>Does the "Walking Encyclopedia" remember ALL issues?

No, but I remembered this from our fairly recent discussion of the flicker when doing the recent "volatile" changes.

**Comment by alankilborn** [comment]
I can't currently find it, but I know it came up along with "volatile"...
Regardless, this StR shows it:

Open NPP.
Do not open the Find dialog.
Find (Volatile) Next.

**Comment by alankilborn** [comment]
>You probably mean that if your "volatile" proposal had been implemented, we would have had the flicker there as well.
Currently, Find (Volatile) Next does not create the Find dialog.

Ah yes, you are correct; ignore my earlier babble in my previous posting.

**Comment by Yaron10** [comment]
I suppose you've implemented your proposal for your personal use. :)
This happened to me [here](https://github.com/notepad-plus-plus/notepad-plus-plus/pull/13159#issuecomment-1435419788). I didn't even remember I changed that.

**Comment by Yaron10** [comment]
Related:
https://github.com/notepad-plus-plus/notepad-plus-plus/issues/13396.
