### ISSUE TITLE
Digitally-signing releases on Windows

### ISSUE THREAD

**Issue by smiley** [notepad-plus-plus/notepad-plus-plus#1339]
Digitally-signing programs helps with security (user knows it's your official release, updater can verify) and generally makes the program look better to users & security software alike.

[Certum](https://www.certum.eu/certum/cert,offer_en_open_source_cs.xml) offers a free Authenticode certificate for open-source developers. They only require identity verification, and the resulting certificate only holds your name & email address (and that email address could be a generic one for the project, e.g.: `notepadplusplus@example.com`).

What do you think?

*(Sadly, I couldn't phrase this in a way that doesn't sound like an ad. I'm not affiliated in any way with Certum or any CA; this is just an innocent suggestion)*

**Comment by dail8859** [comment]
Related #49

**Comment by tushevorg** [comment]
certum is not free any more, however, we are close to another solution in #49

**Comment by donho** [comment]
https://github.com/notepad-plus-plus/notepad-plus-plus/issues/49
