### ISSUE TITLE
NPP Site download section has incorrect URLs for the downloads (8.5.1.1, instead of 8.5.1)

### ISSUE THREAD

**Issue by vdbhb59** [notepad-plus-plus/notepad-plus-plus#13401]
When trying to download from the NPP site's download section, the github file URL pointing to is incorrect. It has 8.5.1.1, instead of 8.5.1.

Example URL from download section of NPP site: https://github.com/notepad-plus-plus/notepad-plus-plus/releases/download/v8.5.1.1/npp.8.5.1.1.Installer.x64.exe

Actual URL from github release site: https://github.com/notepad-plus-plus/notepad-plus-plus/releases/download/v8.5.1/npp.8.5.1.Installer.x64.exe

I could not locate any code to do a PR for the official website correction, hence raised as an issue here.

Snapshot below:

![image](https://user-images.githubusercontent.com/60728004/227492504-8ebec5f5-af22-453f-83de-b0a8c17e8e3d.png)

**Comment by donho** [comment]
Fixed now. Thank you for your heads up.
