### ISSUE TITLE
Search fails on some Python text

### ISSUE THREAD

**Issue by motohead99** [notepad-plus-plus/notepad-plus-plus#13403]
### Description of the Issue
Search fails on some Python text.

### Steps to Reproduce the Issue
1.  Create a text file that contains this text and save it as test.py:
`print("There are " + str(result) + " intances of error: " + e.decode("utf-8") + ", failing if more than " + str(failCount) + " are found.")`
2. Put the cursor at the end of the text and try searching for "more" (without quotes). It is not found.
3. Put the cursor inside the "failing" text and search for "more" (without quotes). It is found.
4. Try searching for "print" (without quotes). It is not found (regardless of where the cursor is).
5. Most of the text cannot be found, above are some examples.

### Expected Behavior
I would expect any text that is searched for to be found, regardless of where the mouse cursor is. I had a large Python file and I was searching for "more" and it couldn't be found. I knew that it was in the file though because the output of the Python script had it. I manually scrolled through the file and found the line with the word "more" in it.

### Actual Behavior
Searching this Python text fails. Some text will work though depending on where the mouse cursor is located.
Note that I originally had an older version of Notepad++ and thought that maybe it was fixed in a newer version. I downloaded the latest version and the issue is still there.

### Debug Information
Notepad++ v8.5.1   (32-bit)
Build time : Mar 21 2023 - 19:13:46
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Command Line : "C:\code\test\.project"
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 10 Enterprise (64-bit)
OS Version : 22H2
OS Build : 19045.2728
Current ANSI codepage : 1252
Plugins : 
    DSpellCheck (1.4.6)
    mimeTools (2.9)
    NppConverter (4.5)
    NppExport (0.4)
    NppTextFX (0.2.6)

**Comment by alankilborn** [comment]
Please take some time to learn how searching in the program works.

Solve your specific situation by doing this:
![image](https://user-images.githubusercontent.com/77065706/227519271-94f048cc-1107-4dca-8242-fdc4f754dae9.png)

Further [REFERENCE](https://npp-user-manual.org/docs/searching/#:~:text=%E2%98%90-,Wrap%20Around,-%3A%20if%20checked%2C%20when).

Please CLOSE this issue.

**Comment by motohead99** [comment]
Good catch! I've used Notepad++ for well over 10 years and have never had that unchecked. My bad (don't know how it got unchecked). This is definitely an ID10T error and I'll close this bug. Sorry for the noise.
