### ISSUE TITLE
v8.5.1 needs AppXSVC running even if modern shell menu is not installed

### ISSUE THREAD

**Issue by bokeron2020** [notepad-plus-plus/notepad-plus-plus#13418]
Hi!

I'm using a modified Windows 10 x64 version where I've been using every new version of Notepad++ x64 for the last 2 years without a single problem.

Last update v8.5.1 is showing a window with this error everytime I try to start the program:

**The service cannot be started, either because it is disabled or because it has no enabled devices associated with it.**

I guess something that my custom W10 doesn't like something the new version does or needs. Maybe something it's been removed from my Windows install.

Could someone please help me with this?
What is this new version needing that the previous one didn't? What service or .DLL or...?

Thanks for any help you can provide.

EDIT:

After some tests I've found the problem: **AppXSVC needs to be running** no matter what.

This behaviour... I don't understand it. Why?
I am not installing the new "modern shell - Edit with notepad++", and AppXSVC should only be needed for installing its .msix package... but if I'm not using it, why is the software needing it?

I do find this an undesired behaviour so I'm reporting my findings so it can be considered an alternative implementation where AppXSVC is only needed if installing the shell menu.

**Comment by rdipardo** [comment]
Just a shot in the dark here, but did your locked-down system cripple the installation of "MS Store Apps", i.e. *.msix packages? 

The new context menu is now distributed as a *.msix package (stripped to the essentials, yes, but the installation mechanism should be the same as any other App from the Store). See https://github.com/notepad-plus-plus/notepad-plus-plus/tree/master/PowerEditor/src/tools/NppModernShell#readme

**Comment by bokeron2020** [comment]
Good aim, I think.

Nope. Micosoft Store isn't present, Clicking an *.msix causes Windows to ask me what to use to open it. Same with *.appinstaller or *.msixbundle.

But... I've never installed the "Context menu entry" and I'm not installing it now either.
I've tried installing on a clean VM running my modified W10 and the problem exist wether I install it or not.

I don't know if not installing it should prevent triggering this problem in my system or it isn't necessarily so.

**Comment by bokeron2020** [comment]
I have edited the original message.

Am I misunderstanding why AppXSVC is needed?
