### ISSUE TITLE
ColumnEditor hex number insertion always uses even number of digits

### ISSUE THREAD

**Issue by alankilborn** [notepad-plus-plus/notepad-plus-plus#13413]
### Description of the Issue
The _Column Editor_ number insertion feature always inserts its hex numbers with an _even_ number of field-width characters, when it should insert such numbers using the minimum number of characters needed to suit the value(s) of the numbers inserted.

This bug was mentioned here, by @Yaron10 : https://github.com/notepad-plus-plus/notepad-plus-plus/pull/13336#issuecomment-1483234273

### Steps to Reproduce (StR) the Issue
1. Set up the following _Column Editor_ operation and execute it on the data indicated in `new 1` tab:
![image](https://user-images.githubusercontent.com/77065706/227714773-7344c6a2-1cf8-4152-8107-3aff7cec4b69.png)

### Actual Behavior
Resulting numbers inserted are done so with a field-width of 4, even though the hex numbers generated only need a field-width of 3:

![image](https://user-images.githubusercontent.com/77065706/227714918-7dc3df0a-66c2-4081-b20f-7e9a7c7b86af.png)

### Expected Behavior
![image](https://user-images.githubusercontent.com/77065706/227714987-a2e620db-43c0-4987-aa55-f83ca40ad1cc.png)

### Comments

Bug caused by the following code:

https://github.com/notepad-plus-plus/notepad-plus-plus/blob/c59c07b4fae16c83f545e0da8772950d03ac4988/PowerEditor/src/ScintillaComponent/ScintillaEditView.cpp#L178-L179

The reason for the above code is probably lost to history...

### Debug Information

Evaluate bug after this commit:
https://github.com/notepad-plus-plus/notepad-plus-plus/commit/7f54a4b959c51323db635f76a4c037cb8f432c0e
but note that the bug is present _before_ the commit, in N++ 8.5.1 (when using _Leading Zeros_ checkbox either checked or unchecked).

**Comment by donho** [comment]
Let's see if there are more request of the same issue.

**Comment by alankilborn** [comment]
>Let's see if there are more request of the same issue.

No one but @Yaron10 will ever notice this bug, so no sense in having this in the suspended state; I will close this issue and the PR.

Sorry, @Yaron10, I tried! :-)
Kind of makes you want to stop finding bugs, eh? :-)

**Comment by rimrul** [comment]
> The reason for the above code is probably lost to history

I'll issue a guess: It was supposed to always produce pairs of hex digits (full bytes). That behaviour only really makes sense with leading zeroes, though.

**Comment by alankilborn** [comment]
>It was supposed to always produce pairs of hex digits (full bytes). That behaviour only really makes sense with leading zeroes, though.

Maybe when `Hex` is selected there should be a "Full Bytes" checkbox. :-)

How about binary?  Doesn't it deserve some full-bytes love as well?

(These are just silly ramblings)
