### ISSUE TITLE
"Find in Search Results": Default "Whole Word" & Case to false

### ISSUE THREAD

**Issue by Yaron10** [notepad-plus-plus/notepad-plus-plus#13415]
**STR:**
Open the Find dialog and execute a command displaying the Search Results window.
Open the "Find in Search Results" dialog.

**Result:**
The "Whole Word" & Case options are checked.

**Expected:**
Those options should be unchecked by default (just like the Find dialog)

***

Notepad++ 8.5.1

**Comment by alankilborn** [comment]
>unchecked by default (just like the Find dialog)

This is only the default for _Find_ dialog on a new install.
After that, the current setting specified by user is remembered by N++.

Should same be true for "Find in Search Results"?  That is, last setting remembered?

**Comment by Yaron10** [comment]
> Should same be true for "Find in Search Results"? That is, last setting remembered?

I don't know.
That dialog is not used (as) frequently, and each new setting adds some overhead to NPP startup time.
What do you think?

**Comment by alankilborn** [comment]
It could be reasonable to just, when the "Find in Search Results" dialog is opened, copy whatever is currently set in the main _Find_ dialog for these options?

**Comment by Yaron10** [comment]
And if you change the options in the "Find in Search Results" dialog and reopen it?
Would it be worth while for the first time only?

**Comment by alankilborn** [comment]
I'd say:

* first time - copy current settings from regular _Find_
* other times - whatever it had last time

**Comment by Yaron10** [comment]
It's a nice idea.
Personally, I tend to prefer just defaulting to false on startup (the dialog's `init()`).
As you understand. :)

**Comment by alankilborn** [comment]
>first time - copy current settings from regular Find

I think maybe users have their favorite (most used) setting already in _Find_ (the main one), so that copying to the secondary one does make sense...

I don't know if we've really decided anything (like a direction) here...

**Comment by Yaron10** [comment]
> so that copying to the secondary one does make sense...

Yes, it does. :)

If you're considering submitting a PR, it's up to you.
Anyway, thank you for looking into it. 👍

**Comment by alankilborn** [comment]
I do like the idea of unchecked, too, though.
(side note: I have a script for myself that when press Ctrl+f, it opens _Find_ and _unchecks_ both "match case" and "whole word").

**Comment by Yaron10** [comment]
> I do like the idea of unchecked, too, though.

Me too. :)

Your idea does make sense.
But if you link it to the Find options, one can argue it should work both ways. That is: changing the options in "Find in Search Results" should modify them in the Find dialog.
(I know it's "primary" and "secondary", and yet...).

Also, the Incremental Find Bar's Case is defaulted to false regardless of the Find settings.

> I have a script for myself that when press Ctrl+f, it opens Find and unchecks both "match case" and "whole word"

Interesting!

**Comment by alankilborn** [comment]
(continuing side note)

>I have a script for myself that when press Ctrl+f, it opens Find and unchecks both "match case" and "whole word"

>Interesting!

For more detail about the script, see the **Nov 24, 2022, 8:35 PM** posting in this Community thread: https://community.notepad-plus-plus.org/topic/23793

An interesting idea posed in that thread is to be able to set a "default" for the search mode.  Thus, every time the _Find_ window is invoked (from a closed state) the search mode would be reset to _Normal_ (or whatever) automatically.

An older text editor I used supported this idea.  In its preferences was a page where the Find dialog is replicated, for the sole purpose of setting the control values the way you'd want then to be preset/reset when the real Find is invoked.  It was a nice way of providing the capability.

**Comment by alankilborn** [comment]
@donho What do you think about this issue?  

![image](https://user-images.githubusercontent.com/77065706/227769576-9db23d21-1ff2-47a4-9ab7-5977641be6fc.png)

![image](https://user-images.githubusercontent.com/77065706/227769595-4aff3788-d7c9-4201-8a90-c278c3cc8b0c.png)


Two opinions so far on which way to go, when this _Find in search results_ dialog is invoked:

* ALWAYS uncheck "match case" and "whole word"

* Copy current settings of these controls from main _Find_ window the first time the dialog appears; if reinvoked, would use current settings from previous instance of itself

**Comment by donho** [comment]
OK, I think it's fair to make both unchecked by default.
Then remember the settings during the session, but not though the sessions.

**Comment by alankilborn** [comment]
@donho 

Assign me to this issue?

**Comment by Yaron10** [comment]
@alankilborn,

> For more detail about the script, see...

Thank you for the reference.
