### ISSUE TITLE
Bug report: Notepad++ 8.5.1 crashes when invoked from the context menu

### ISSUE THREAD

**Issue by k-kolev1985** [notepad-plus-plus/notepad-plus-plus#13425]
Bug report: Notepad++ 8.5.1 crashes when invoked from the context menu

### Description of the Issue
With the latest Notepad++ release (v8.5.1), if Notepad++ is invoked from the context menu, it appears for a second or two and then closes itself (crashes).
The selected for opening file opens (is loaded) when Notepad++ appears for a moment.
If Notepad++ is already opened when the invoking from the context menu occurs, the crash does not happen.

### Steps to Reproduce the Issue
1. Install Notepad++ and during the setup select to install the context menu integration.
2. Open a file manager like Windows File Explorer.
3. Select a text file and invoke its context menu.
4. Activate the command "Edit with Notepad++" from the menu.

### Expected Behavior
Notepad++ opens and the selected file is loaded.

### Actual Behavior
Notepad++ opens for a moment with the selected file loaded, but then crashes (closes itself).

### Debug Information
Notepad++ v8.5.1   (64-bit)
Build time : Mar 21 2023 - 19:16:10
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 11 Pro (64-bit)
OS Version : 22H2
OS Build : 22621.1413
Current ANSI codepage : 1251
Plugins : 
    DSpellCheck (1.5)
    mimeTools (2.9)
    NppConverter (4.5)
    NppExport (0.4)
    NppSaveAsAdmin (1.0.211)

**Comment by donho** [comment]
@GurliGebis 
Can I assign this issue to you?

**Comment by donho** [comment]
@k-kolev1985 
Could you test the new context menu entry to see if it fixed your issue:
http://download.notepad-plus-plus.org/repository/MISC/nppShell.TEST09/npp.8.5.1.Installer.x64.exe

**Comment by GurliGebis** [comment]
@donho sure 🙂

**Comment by k-kolev1985** [comment]
@donho Yes, the context menu functionality in this build seems to work as expected.

**Comment by GurliGebis** [comment]
@donho one more reason not to go back to 8.5.1 🙂

**Comment by GurliGebis** [comment]
@donho this one can be closed
