### ISSUE TITLE
French translation text is cropped in search window

### ISSUE THREAD

**Issue by mooms06** [notepad-plus-plus/notepad-plus-plus#13426]
### Steps to Reproduce the Issue

1. Open a text file
2. Hit Ctrl+F
3.  The following text is cropped: "Dans la séléctio" (see image)

![image](https://user-images.githubusercontent.com/25405517/227780071-1e37140e-302a-4d95-a094-6efc9f9fa951.png)

### Debug Information
Notepad++ v8.5.1   (64-bit)
Build time : Mar 21 2023 - 19:16:10
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : "C:\Users\xxx\Desktop\test.CSV"
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 10 Education (64-bit)
OS Version : 22H2
OS Build : 19045.2728
Current ANSI codepage : 1252
Plugins : 
    mimeTools (2.9)
    NppConverter (4.5)
    NppExport (0.4)

**Comment by SaiyajinK** [comment]
pareil pour moi.
same for me.

**Comment by conky77** [comment]
#15027
