### ISSUE TITLE
Is there a way to add a context menu to the Windows 11 system in the portable version

### ISSUE THREAD

**Issue by FanXiangTM** [notepad-plus-plus/notepad-plus-plus#13439]
Is there a way to add a context menu to the Windows 11 system in the portable version

**Comment by chip33** [comment]
If you mean the new modern context menu in windows 11 you could give this a try.

**Comment by chip33** [comment]
You could give this a try.
https://github.com/MikeCoder96/notepad-plus-plus-context-menu

**Comment by GurliGebis** [comment]
I would wait for the next version.
If you want to add the context menu, run the following command as admin inside the contextmenu folder (next release, not the 8.5.1 release):
`regsvr32.exe NppShell.dll`

**Comment by donho** [comment]
The "portable" version means no interaction with OS - no stored information in registry for example. 
So if you need Explorer context menu "Edit with Notepad++", you have to it manually. Otherwise you can always use installer which gets job done for you.

**Comment by FanXiangTM** [comment]
> regsvr32.exe NppShell

Is it done in version 8.5.2

**Comment by GurliGebis** [comment]
No, you need to do it manually, the command is `regsvr32.exe NppShell.dll`
Run it as admin inside the contextMenu folder
