### ISSUE TITLE
Blanck icon in taskbar Windows 11

### ISSUE THREAD

**Issue by manoletto** [notepad-plus-plus/notepad-plus-plus#13438]
### Description of the Issue
With version 8.5.1, the program icon in the taskbar is blanck.

### Steps to Reproduce the Issue
Open Notepad++

### Expected Behavior
The beautiful icon in the taskbar

### Debug Information

Notepad++ v8.5.1   (64-bit)
Build time : Mar 21 2023 - 19:16:10
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : "K:\private\efournier\Econocom\CD31\cd31.txt"
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 11 Pro (64-bit)
OS Version : 22H2
OS Build : 22621.1413
Current ANSI codepage : 65001
Plugins : 
    ComparePlugin (2.0.2)
    HexEditor (0.9.12)
    JSMinNPP (1.2205)
    mimeTools (2.9)
    NppConverter (4.5)
    NppExport (0.4)
    NPPJSONViewer (1.40)
    XMLTools (3.1.1.13)

![image](https://user-images.githubusercontent.com/6593655/228460127-b576c1c1-23bb-489f-bb6b-628a6c40597b.png)

**Comment by RaZer0k** [comment]
Same here... only open with

**Comment by GurliGebis** [comment]
@manoletto, @RaZer0k and @Nuklon it has been fixed and will be included in the RC version that will be released soon.
@donho should we close this issue, since it has been fixed?

**Comment by donho** [comment]
https://github.com/notepad-plus-plus/nppShell/commit/e4f9037de5ec438db4b5ffca5d6dfada4cc4e912

**Comment by manoletto** [comment]
Great, thank you ;-)
