### ISSUE TITLE
Find in Files seriously disrutping other programs

### ISSUE THREAD

**Issue by blackears** [notepad-plus-plus/notepad-plus-plus#13445]
### Description of the Issue
I'm not sure when this tarted  but I've noticed if I use Find in Files in the last month it causes many other programs that I run to start behaving badly.  Firefox grids to a halt and my IDE becomes unresponsive for minutes.  I have to start killing programs to get things working again.  I used to be able to Find in Files without this kind of trouble and used it as a substitute for grep.  But now even just trying to scan a small directory tree with text files will bring down my web browser and IDE.

### Steps to Reproduce the Issue

1. Have several 3rd party programs open on your file system (Firefox, Visual Studio Code, others in the background)
2. Select Find in Files from main menu
3. Specify the root of a repository you're working on
4. Search files with a text extension, eg, *.py

### Expected Behavior

Search should not interfere with operation of either Notepad++ or third party programs.

### Actual Behavior
Notepad will become unresponsive as the scan is conducted.  Firefox will freeze and so will Visual Studio Code and other IDEs I use.  Windows will not respond to user input for tens of seconds at a time.  You have to start killing processes to get control back of your system.

Does Notepad++ spawn a new thread to conduct this search?  If not, I think it should since that will stop the user interface from becoming unresponsive.  Also, the search should not starve out other applications running on your OS.

### Debug Information
Notepad++ v8.4.8   (64-bit)
Build time : Dec 24 2022 - 19:40:27
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 10 Pro (64-bit) 
OS Version : 22H2
OS Build : 19045.2728
Current ANSI codepage : 1252
Plugins : 
    HexEditor (0.9.12)
    mimeTools (2.9)
    NppConverter (4.5)
    NppExport (0.4)

**Comment by molsonkiko** [comment]
Are you searching `In all sub-folders` in some directory with a ton of deep-nested subfolders, like the directory of your Python executable? If anything would cause `Find in files` to behave like that, my guess would be that.
In any case, I tried doing just that (searching for `fo` in all files (`*.*`) in my Python folder, and even when the search was going my other applications remained responsive.

**Comment by blackears** [comment]
No it was a fairly shallow directory and I was using a filter for text only files.  But I think it may be more that I have an old computer that can become unstable when it's been running for a few days.  I've tried doing the same thing with it after a fresh boot and don't run into problems.  So this issue might have more to do with me using the filesystem than anything specific to Notepad++.  I probably shouldn't have filed this bug.

**Comment by alankilborn** [comment]
>I probably shouldn't have filed this bug.

So...close it?
