### ISSUE TITLE
Meta issue tracker for context menu and installer changes

### ISSUE THREAD

**Issue by GurliGebis** [notepad-plus-plus/notepad-plus-plus#13447]
### Description of the Issue
Meta issue for tracking bugs and pull requests related to the new context menu implementation.

### Fixed and can be closed with next release
* ~~#13425~~
* ~~#13399~~
* ~~#13410~~
* ~~#13411~~
* ~~#13439~~
* ~~#13440~~
* ~~#13446~~
* ~~#13448~~
* ~~#13476~~
* ~~notepad-plus-plus/nppShell#2~~

**Comment by GurliGebis** [comment]
@donho This should make it easy to keep an overview over which issues we have to update with the next release.

**Comment by Yaron10** [comment]
https://github.com/notepad-plus-plus/notepad-plus-plus/issues/13457.
