### ISSUE TITLE
NPP RTL: Display Find in Files Progress window in RTL layout

### ISSUE THREAD

**Issue by Yaron10** [notepad-plus-plus/notepad-plus-plus#13458]
**STR:**
Set NPP interface to RTL.
Run Find in Files.

**Result:**
The Progress window is displayed in LTR layout.

https://github.com/notepad-plus-plus/notepad-plus-plus/blob/508b3fabd657d32488eb9105d0cdc90055f55d2b/PowerEditor/src/ScintillaComponent/FindReplaceDlg.cpp#L5635

Should be replaced with
```
WS_EX_APPWINDOW | WS_EX_TOOLWINDOW | WS_EX_OVERLAPPEDWINDOW | (pNativeSpeaker->isRTL() ? WS_EX_LAYOUTRTL : 0),
```
***
Notepad++ 8.5.1.

**Comment by alankilborn** [comment]
>With the strings localized to RTL

Yes, of course; I was just asking if the general picture was correct.  And you've said it is, so thanks.
