### ISSUE TITLE
What is this? Appeared recently

### ISSUE THREAD

**Issue by vitalii2011** [notepad-plus-plus/notepad-plus-plus#13454]
### Description of the Issue
Symbols that do not affect anything (?): 
![Image 001](https://user-images.githubusercontent.com/41552153/229094739-feb62874-2a7e-446d-9503-bc17a12dfe85.png)

### Steps to Reproduce the Issue
Line 90, after "Prix": 
[modDesc.zip](https://github.com/notepad-plus-plus/notepad-plus-plus/files/11120813/modDesc.zip)

### Expected Behavior
Without symbols, or what / where to configure so that they are not displayed.

### Debug Information
Notepad++ v8.5.1   (64-bit)
Build time : Mar 21 2023 - 19:16:10
Path : D:\Portable\PortableApps\Notepad++Portable\App\Notepad++64\notepad++.exe
Command Line : "C:\Users\Mavra\Desktop\modDesc.xml"
Admin mode : OFF
Local Conf mode : ON
Cloud Config : D:\Portable\PortableApps\Notepad++Portable\Data\Config
OS Name : Windows 10 Pro (64-bit)
OS Version : 22H2
OS Build : 19045.2728
Current ANSI codepage : 1251
Plugins : 
    mimeTools (2.9)
    NppConverter (4.5)
    NppExport (0.4)

**Comment by alankilborn** [comment]
![image](https://user-images.githubusercontent.com/77065706/229100647-7b23c2a2-0376-4aaf-8dc7-07a647204d91.png)

**Comment by vitalii2011** [comment]
Thank you. Everything worked out.
