### ISSUE TITLE
Why not limit line length to a constant?

### ISSUE THREAD

**Issue by mudongliang** [notepad-plus-plus/notepad-plus-plus#1346]
I encounter a problem in using notepad++, I can't find the setting for the line length. Can you tell me? The information which is obtained from the search engine is useless.
Besides, I think maybe many people dislike the feature of line length now. Why not limit line length to constant value, such as 80 or the screen.

**Comment by sanastasiou** [comment]
Line length can already be the screen if you use the "Line Wrap" feature.

**Comment by mudongliang** [comment]
Why not open it as default?

**Comment by linquize** [comment]
You should not assume the format of a text file.  So line limit is not enabled by default

**Comment by mudongliang** [comment]
I know. Thanks
