### ISSUE TITLE
[Win 11, NP++ 8.5.1] Explorer contextmenuitem "Edit with Notepad++" is visible only for admin user/installing user

### ISSUE THREAD

**Issue by WolfgangHG** [notepad-plus-plus/notepad-plus-plus#13476]
On my Win11 machine, the explorer contextmenu "Edit with Notepad++" is no longer available.

I found in the changelog this:
_Use new modern shell "Edit with Notepad++" of Windows 11 instead of hijacking "Pin to Quick access"._

But it does not work for me: the menu item is neither on the root menu available nor in the "Show more options" menu:
![win11_npp851](https://user-images.githubusercontent.com/138049/229891048-e34c78a7-2335-431f-8aac-0bafc6dc1e41.png)

Here is a screenshot from a Win10 machine with Notepad++ 8.4.8 to show what I mean:
![win10_npp848](https://user-images.githubusercontent.com/138049/229891138-9573fd0f-8376-408a-b6fa-bd61b8891a54.png)

I have to admit: the Np++ update was installed automatically by our Endpoint protection. But I want to avoid uninstalling/reinstalling it if not necessary.
Is there any additional information that I could provide?

Similar question here, but about Windows 10: [https://community.notepad-plus-plus.org/topic/18140/how-to-get-windows-explorer-right-click-menu-open-edit-with-notepad](https://community.notepad-plus-plus.org/topic/18140/how-to-get-windows-explorer-right-click-menu-open-edit-with-notepad)

**Comment by WolfgangHG** [comment]
OK, now I see what has happened: my user is not allowed to install software. When I logon with an admin user, the context menu item is there:
![win11_npp8 5 1_admin](https://user-images.githubusercontent.com/138049/229900938-b657cc8e-8c80-43e6-b65d-bb8332c63708.png)

Is it maybe only available for the user that installed Notepad++?

**Comment by donho** [comment]
@WolfgangHG 
So if the installation of context menu is for all users of the machine, will it solve the problem?

**Comment by WolfgangHG** [comment]
Yes, for me this would help.

**Comment by GurliGebis** [comment]
@donho some installeres ask if the program should be installed for all users or only the current user.
Should we do the same? This would decide which HKEY the registry entries are created.
If not, then I have an idea we could try (changing the HKEY from HKEY_LOCAL_MACHINE to the virtual key HKEY_CLASSES_ROOT)

**Comment by GurliGebis** [comment]
Hmm, HKEY_CLASSES_ROOT is only there for compatibility reasons, so not sure about that.
Also it might break multi user systems, where user A installs it, but then user B doesn't have the menues, since the are installed locally for user A.

**Comment by WolfgangHG** [comment]
The installer always shows an UAC prompt (where I have to enter the admin user), so an installation per user is not really possible I think?

**Comment by GurliGebis** [comment]
I agree, and really, that is how it should be.
So keeping it in HKEY_LOCAL_MACHINE makes sense, since it is available to all users then.

**Comment by GurliGebis** [comment]
@WolfgangHG and @donho The issue is because the package is only registered for the user that does the installation.
I'm looking into how to install it for all users (that should be possible from what I can read).

**Comment by GurliGebis** [comment]
Okay, so you can provision an MSIX package for all users.... as long as it isn't a sparse package.
I'll spend some time thinking about the solution - it should be doable.

**Comment by donho** [comment]
@GurliGebis 
> some installeres ask if the program should be installed for all users or only the current user.
> Should we do the same?

Maybe... I'm not sure about that.
But let's do it for all users firstly. We will see if there are such requests coming,

**Comment by GurliGebis** [comment]
@donho this is pretty simple - please see notepad-plus-plus/nppShell#24
And yes, I agree that is it complicated - but as long as Notepad++ is being distributed using another installer than MSIX (so it has to be sparse), some things are not as easy as I would like them to be.

**Comment by GurliGebis** [comment]
This is way simpler than the other things we have done so far, and pretty clean actually 🙂

**Comment by donho** [comment]
@WolfgangHG 
Maybe I don't understand totally your problem.
Is it about Notepad++ deployment to several PC, or a installation by launching Notepad++ installer on 1 PC for sharing Notepad++ usage with several users on the same PC?

**Comment by WolfgangHG** [comment]
@donho I am no admin user on my company machine. So when installing Notepad++, I have to enter the credentials of an admin user (which is of course not my own user) in the UAC prompt. And now, the admin account sees the contextmenu when I login with it, but my own user don't see it.

**Comment by GurliGebis** [comment]
@donho User A installs Notepad++ on the PC, user B the logs in - she has no context menues, since the sparse package isn't installed system wide, but user wide.
The PR I have above makes sure it is installed when the right click menu is opened, if the user doesn't have it installed.

**Comment by ZanzaZanzara** [comment]
Problem still exists in 5.8.2 on Windows 11 64Bit. After installation the Edit with Notepad++ is still gone in modern and classic right click menu. Going back to 5.8 and it works again.

**Comment by GurliGebis** [comment]
@ZanzaZanzara are you using a system with multiple users or just one user? (Like, is the user that installed Notepad++ also the user having the problem)

**Comment by ZanzaZanzara** [comment]
> @ZanzaZanzara are you using a system with multiple users or just one user? (Like, is the user that installed Notepad++ also the user having the problem)

yes its multiple users. i am installing silent with local system account.

**Comment by GurliGebis** [comment]
@WolfgangHG the issue isn't that it is only visible for admin users - it is only visible for the user that installed Notepad++ (even with two admin users, only the one who installed it has them).
@ZanzaZanzara okay, that explains it.

The solution is in:
* notepad-plus-plus/nppShell/pull/24

**Comment by WolfgangHG** [comment]
@GurliGebis yes, I got this already. I just changed the subject to something that describes my symptoms better ;-). The previous subject was too general.
If you need testing of prerelease fixes, come back to me.

**Comment by GurliGebis** [comment]
Once donho has built a test installer with that PR, we should be able to have you test i.

**Comment by donho** [comment]
@WolfgangHG & @ZanzaZanzara 
Could you test the following installers of your choice to see if your problem is solved?
http://download.notepad-plus-plus.org/repository/MISC/nppShell.TEST15/

**Comment by GurliGebis** [comment]
@donho please see the issue I have created in here.
The installer is unable to replace the dll if explorer has a lock on it.
The solution is in there, to move it out of the way.

https://github.com/notepad-plus-plus/notepad-plus-plus/issues/13496

**Comment by GurliGebis** [comment]
This is due to explorer loading the dll into it's address space for the classic menu.
So the Cleanup Dll function moved it out of the way, so the installer can place the new one.
The old stays in memory, so the menu keeps working.

**Comment by donho** [comment]
@GurliGebis 
> This is due to explorer loading the dll into it's address space for the classic menu.
> So the Cleanup Dll function moved it out of the way, so the installer can place the new one.
> The old stays in memory, so the menu keeps working.

Where is the report from users?

**Comment by GurliGebis** [comment]
@donho it is from me, since I just tested it myself 😃 (think of me as the user in this case - I do use NPP daily after all 😉)
You can test it yourself, install 8.5.2 and make sure the dll is loaded into explorer.exe
Then upgrade to the test build above - notice that the dll isn't being replaced like it should, since it is locked 🙂

**Comment by WolfgangHG** [comment]
Do you need testing feedback from us users? At least I should not be affected by the "locked" issue, as the DLL should not be in use on my setup ;-).

**Comment by GurliGebis** [comment]
@WolfgangHG as long as you are sure the right dll is there, feedback would be great.
If you check the timestamp on the file signaturer, you can see if it is from today

**Comment by WolfgangHG** [comment]
I can confirm that it works now (and the menu item is present on the new Win11 menu and on the old menu - which is fine for me). But I had to logoff/login after installation to make the menu appear though I killed explorer.exe after having started the installer. I think I read something in the changelog that you made changes so that this is not necessary any longer?

Here is a screenshot of the Notepad++ dir before installation:
![before](https://user-images.githubusercontent.com/138049/230792376-ed467898-be2c-4ec5-a79a-fc345c1c744e.png)

And that is the "contextmen" subdir after installation (which was not present in the previous version 8.5.1 - but I think you made changes about this):
![after](https://user-images.githubusercontent.com/138049/230792382-ad059677-4a03-4081-8ff8-195f6a7abc05.png)
Why don't you increment the dll version number ;-)?

**Comment by GurliGebis** [comment]
We are adding versioning to the dll 🙂
Do you mean giving it a new name each time? If so, that is a bit more troublesome, since it is referenced inside the msix, so that would have to be updated as well for each release.
Since the old dll is loaded into explorer.exe, it would explain why you had to logoff, if it was already loaded into memory of the current user. (that is why the Win11 version is smarter, since it uses dllhost.exe, which starts and stops on demand, so no locking there)

**Comment by WolfgangHG** [comment]
About versioning: nope, I mean the versions that are displayed e.g. in my explorer screenshots: "NppShell.dll" has "1.0.0.0" (and "NppModernShell.dll" has no version at all), but I would have expected a version that reflects the 8.5.2 build. I am a C# dev, so I know how to version .NET assemblies, but I don't have much C++ knowledge. So the version attribute is just a suggestion by someone who doesn't understand what you are doing ;-).

I assume that the 8.5.2 prelease has changed "NppModernShell.dll" to "contextMenu\NppShell.dll", and the old DLL will be deleted on next reboot?

**Comment by GurliGebis** [comment]
@WolfgangHG Yes, versioning has been added to the repo, the version won't be following the NPP version, since there can be a release of NPP without any changes done to NppShell.
And yes, the file has changed name and moved into the subfolder, so the old one should be scheduled to be remove at next reboot.

**Comment by WolfgangHG** [comment]
I can confirm that the old "NppModernShell.dll" was deleted, so all is fine now!

But there is one strange problem with WinZip - either a new issue or to be ignored: I use WinZip 21 (a bit older), which somehow pulls parts of the old style explorer context menu to is own context menu:
I click the "Edit with Notepad++" item in the WinZip contextmenu and a Windows prompt "choose an app to open this file type" appears (which did not happen before). And after this, there are two "Edit with Notepad++" items in the context menu:
![winzip](https://user-images.githubusercontent.com/138049/230874376-715c36a2-255b-4d98-b37d-4183321ac267.png)
This duplication happens always.

Is this something that you want to dig deeper? If yes I can create a new issue.

Note that the "Edit with Notepad++" in previous versions did not work at all (https://community.notepad-plus-plus.org/topic/19660/context-menu-item-edit-with-notepad-does-not-work-in-winzip-for-subdirectories), so the current behavior is actually an improvement ;-).

**Comment by GurliGebis** [comment]
@WolfgangHG does it happen if you go into the normal explorer and then shift rightclick on a file?
If not, then I don't think we should look into it, since we really cannot handle all other programs that load the context menu into them (Since they can be doing all kinds of things).

**Comment by WolfgangHG** [comment]
Nope, Windows Explorer is fine. It is just WinZip.

**Comment by GurliGebis** [comment]
@WolfgangHG actually, I think I have a better solution, that is way less "flaky", since it doesn't use the counter I have been using
Could I get you to test with a test dll and see if both explorer and winzip works like they should on your machine?

**Comment by WolfgangHG** [comment]
Sure!

**Comment by GurliGebis** [comment]
@WolfgangHG thanks - the file is here: https://www.dropbox.com/s/dxuxfpd9oxpeu8p/ReworkedLogic.zip?dl=0
Do the following (make sure it is a test machine, since it involves installing my test cert as a trusted root certificate):

1. Download the zip file and unzip it
2. Double click the certificate and install it as a Trusted Root Certificate Authority, both for the Current User and Local Machine.
3. Go into the contextMenu folder, and run the following command: `regsvr32 /u NppShell.dll`
4. Restart explorer to unload the DLL from memory.
5. Copy the DLL file from the zip file into the contextMenu folder, overwriting the existing file.
6. Register the DLL file by running the following command in the folder: `regsvr32 NppShell.dll`
7. Verify the right click menu (both modern and classic) works like they should (test the classic with both SHIFT+rightclick and normal rightclick + show more).
8. Test in Winzip, does it work normally there as well?

**Comment by WolfgangHG** [comment]
Works perfect now (even without installing the certificate) - only one item is visible in WinZip, and all explorer items work also as expected.

I think that Win11 and WinZip 21 have a problem in combination, as "Edit with Notepad++" causes the same behavior as the "Share with Skype" menu item => above them is an item "Open with", and all three items show the "Open with" dialog. So "Edit with Notepad++" and "Share with Skype" actually don't work ;-). But this seems to be not your business.

**Comment by GurliGebis** [comment]
@WolfgangHG thank you.
Can I get you to create another issue for the WinZIP issue and link it here and tag me in it.
I will create a pull request with the fix later today

**Comment by WolfgangHG** [comment]
Done.

**Comment by GurliGebis** [comment]
Thanks, I have created a PR with the fix from the test DLL above.

**Comment by hieuck** [comment]
Notepad++ 8.5.2
Plugin Explorer 1.9.9
![image](https://user-images.githubusercontent.com/30469654/235066698-8eb85e30-b255-463b-a859-29d04ce76ced.png)

**Comment by GurliGebis** [comment]
@hieuck can you try with this one: http://download.notepad-plus-plus.org/repository/MISC/nppShell.TEST20/
@donho would it be possible to release a 8.5.3 soon(ish) with the things from the latest NppShell repo?

**Comment by WolfgangHG** [comment]
@hieuck Just for curiousity: what happens when you click the "Edit with Notepad++" items for a filetype which is not already associated with Notepad++? Will it open in Notepad++ (as expected), or will the Windows 11 prompt "choose an app to open this file type" appear? The latter happens with WinZip for me, and with your help we could validate whether this is a WinZip issue or a Notepad++ issue.

**Comment by hieuck** [comment]
> @hieuck Just for curiousity: what happens when you click the "Edit with Notepad++" items for a filetype which is not already associated with Notepad++? Will it open in Notepad++ (as expected), or will the Windows 11 prompt "choose an app to open this file type" appear? The latter happens with WinZip for me, and with your help we could validate whether this is a WinZip issue or a Notepad++ issue.

cả 2 dòng đều mở Notepad++ đúng tệp cần mở lên

both lines open Notepad++ the right file to open

> @hieuck can you try with this one: http://download.notepad-plus-plus.org/repository/MISC/nppShell.TEST20/ @donho would it be possible to release a 8.5.3 soon(ish) with the things from the latest NppShell repo?

tôi đã cập nhật và không thấy 2 dòng 
i updated and didn't see 2 lines
![image](https://user-images.githubusercontent.com/30469654/235292043-b6a73042-dc0b-43c8-849d-f28a439d9ab5.png)

**Comment by hieuck** [comment]
tôi chạy máy ảo Windows mới nhất thì NPP 8.5.2 không gặp sự cố 2 dòng 
i run latest windows VM then NPP 8.5.2 no problem 2 lines
![image](https://user-images.githubusercontent.com/30469654/235838705-dcb559e4-8d1e-4132-89ff-a639f96ea017.png)

**Comment by GurliGebis** [comment]
To everyone seeing this issue, can you retry with 8.5.3 and see if the problems persists.
