### ISSUE TITLE
mIRC Scripting Language (mSL) highlight

### ISSUE THREAD

**Issue by westor7** [notepad-plus-plus/notepad-plus-plus#1347]
Hello,

I've created an full highlight documented color parser for Notepad++ , it supports the latest mIRC scripting language functions on it, it is 100% tested and is ready to implent in Notepad++, mIRC Scripting Language is more than 20 years old and there are a lot of users that requesting this language to highlight into the Notepad++ all the time in the support room, its time to get this request after many years in real and do not ignore it.

mSL XML Code: http://pastebin.com/CfdKyQsk
- Thanks!

**Comment by MetaChuh** [comment]
udl's can be distributed on any author's web pages and imported by any user.
there is no need to distribute it to everyone.

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)
