### ISSUE TITLE
Notepad++ logo not visible in Windows11

### ISSUE THREAD

**Issue by vidhyadhara** [notepad-plus-plus/notepad-plus-plus#13477]
NP++ logo is not visible in the taskbar
### Description of the Issue

NP++ logo is visible on desktop but when its being used, the logo is not visible on taskbar
### Steps to Reproduce the Issue

1. Install NP++ v8.5.1 on windows11
2. Launch NP++
3. Taskbar doesnt have the logo visible though NP++ is running

### Expected Behavior

Expectec to have the logo visible
### Debug Information

<img width="960" alt="image" src="https://user-images.githubusercontent.com/41357197/229965862-77fd4950-98bd-4025-a64f-c9378c547060.png">

**Comment by TheLonerD** [comment]
#13438

**Comment by ArkadiuszMichalski** [comment]
@vidhyadhara How about version [8.5.2](https://notepad-plus-plus.org/downloads/v8.5.2/)?

**Comment by vidhyadhara** [comment]
It was released just yesterday !! I updated NP++ to 8.5.2 and the issue is resolved now. @ArkadiuszMichalski
