### ISSUE TITLE
shortcuts.xml gets mixed line-endings on macro record and save

### ISSUE THREAD

**Issue by alankilborn** [notepad-plus-plus/notepad-plus-plus#13488]
### Description of the Issue
See StR.

### Steps to Reproduce (StR) the Issue
1. Extract a fresh portable version of 8.5.2.
2. Open its `shortcuts.xml` with it.
3. Do regex search for `(?<!\r)\n` and observe 0 hits.
4. Record and save any macro.
5. Restart.
6. Do regex search for `(?<!\r)\n` in `shortcuts.xml`.

### Expected Behavior
No hits.

### Actual Behavior
3 hits in the file.
Turn on visible line-endings.
Observe LF line-endings on lines 3 through 5 while the rest of the file has CRLF endings:
![image](https://user-images.githubusercontent.com/77065706/230600719-a5ebf654-b55d-47a0-87bf-c99ce0a91069.png)
![image](https://user-images.githubusercontent.com/77065706/230600815-55006617-c1fc-4d0d-83e3-19cbcaf0c266.png)

### Debug Information
Notepad++ v8.5.2   (64-bit)
Build time : Apr  4 2023 - 19:55:32
Path : W:\npp.misc\_NoBackup\Releases\npp.8.5.2\test\notepad++.exe
Command Line : -multiInst
Admin mode : OFF
Local Conf mode : ON
Cloud Config : OFF
OS Name : Windows 10 Enterprise (64-bit)
OS Version : 21H2
OS Build : 19044.2728
Current ANSI codepage : 1252
Plugins : 
    mimeTools (2.9)
    NppConverter (4.5)
    NppExport (0.4)

**Comment by alankilborn** [comment]
I'm sure that _any_ type of action that forces N++ to have to write out `shortcuts.xml` also causes this issue, not just saving a recorded macro.

**Comment by donho** [comment]
@alankilborn 
I believe this issue is not only for macro modification, but also for run menu modification.

**Comment by alankilborn** [comment]
>but also for run menu modification.

Agreed.  I tried a test with that, and same problem resulted.
