### ISSUE TITLE
Dark Mode Printing Issue

### ISSUE THREAD

**Issue by skypilot65** [notepad-plus-plus/notepad-plus-plus#13489]
### Description of the Issue
When printing in Dark Mode the output is almost unreadable. Switching to Light mode corrects the problem. Also in Dark mode the line count per page is 63 versus Light mode is 67. The files being edited are standard C/C++ code. I am printing to an HP Color LaserJet printer (in color).

### Steps to Reproduce the Issue
1. Set Dark Mode on using default settings
2. Print a C/C++ source code file

### Expected Behavior
Dark mode printing should be identical to the Light mode

### Actual Behavior
The printed contents of the C/C++ files are color faded and in some cases barely readable.

### Debug Information
Notepad++ v8.5.2   (64-bit)
Build time : Apr  4 2023 - 19:55:32
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : "C:\Program Files\Notepad++\change.log" 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 10 Pro (64-bit)
OS Version : 21H2
OS Build : 19044.2728
Current ANSI codepage : 1252
Plugins : 
    mimeTools (2.9)
    NppConverter (4.5)
    NppExport (0.4)

**Comment by CennoxX** [comment]
Preferences > Print > Color Options > Black on white should be set.
I think this should be the default setting.
