### ISSUE TITLE
Contextmenu in WinZip contains duplicate "Edit with Notepad++"

### ISSUE THREAD

**Issue by WolfgangHG** [notepad-plus-plus/notepad-plus-plus#13499]
This is a followup of #13476: I use WinZip 21 (a bit older), which somehow pulls parts of the old style explorer context menu to is own context menu. With the following steps, the "Edit with Notepad++" item is duplicated:
I click the single "Edit with Notepad++" item in the WinZip contextmenu and a Windows prompt "choose an app to open this file type" appears (which did not happen before). And after this, there are two "Edit with Notepad++" items in the context menu:
![winzip](https://user-images.githubusercontent.com/138049/230929625-b5c0abab-4aac-4c27-9e38-de3bedf88d7f.png)

**Comment by WolfgangHG** [comment]
I already verified that the [fix](https://github.com/notepad-plus-plus/notepad-plus-plus/issues/13476#issuecomment-1501739545) by @GurliGebis resolves the duplicate items.

The WinZip "Edit with Notepad++" item does not work actually - it behaves the same as the "Open With" item and shows the Win11 "Open with" dialog. But as the "Share with Skype" shows the same behavior, this is either a Win11 or a WinZip problem.

**Comment by GurliGebis** [comment]
@donho this PR changes the logic from a counter to a state flag instead, which is more stable, since it doesn't depend on "magic numbers", but instead just the state of whether the modern has been shown first (since it always loads first).
