### ISSUE TITLE
Silent un/installer

### ISSUE THREAD

**Issue by 720720** [notepad-plus-plus/notepad-plus-plus#13497]
The silent un/installer does not check if Notepad++ is running.
The un/installer reports success even if the executable is not updated.
This behaviour can lead to problems when updating Notepad++ via winget for example.

**Comment by brain246** [comment]
Just stumbled across the same issue (updated Notepad++ with WinGetUI while it was opened):
<img width="911" alt="image" src="https://user-images.githubusercontent.com/85419575/230924712-a94ba29d-66be-4534-b6fd-802fa7e38792.png">

<img width="309" alt="image" src="https://user-images.githubusercontent.com/85419575/230924747-e7ae16cf-4a5b-40b1-a735-ef25f3449347.png">

**Comment by Guardempire** [comment]
Its the same with an Win32 APP-Package or if you start it per cmd... It all works well and easy, as long as Notepad is closed. Is it in use and you use the silent installer, it tells you everthing is right AND changes the REG-Key for the version to the new one. But the program itself remains the old version!

**Comment by CennoxX** [comment]
This is fixed by #14251

**Comment by donho** [comment]
https://github.com/notepad-plus-plus/notepad-plus-plus/commit/83f1195bc1f8d84080a4a243019f155a2f45f430
