### ISSUE TITLE
Add text align

### ISSUE THREAD

**Issue by KareemMAX** [notepad-plus-plus/notepad-plus-plus#1350]
When I have installed notepad++ in Arabic translation it is started with right text align so it makes problems when I try to code something so I had to change my display language to English
Maybe text align feature or text direction feature will be awesome because I can write in English when I am in Arabic display or write in Arabic when I am in the English display without problems

And thanks for that great job :smiley:

**Comment by ClaudiaFrank** [comment]
Isn't this already available
VIEW->Text Direction RTL and VIEW->Text Direction LTR?

**Comment by KareemMAX** [comment]
Ya sorry, I didn't see that.
I will close the issue now.
Thanks for the replay.
