### ISSUE TITLE
javascript regexp missing highlight

### ISSUE THREAD

**Issue by madebycambiamentico** [notepad-plus-plus/notepad-plus-plus#1351]
**np++6.8.8**: i'm using **default style**, but in any js code the **regexp** are highlighted (<script></script> in HTML/PHP or even in any *file.js*).
```javascript
"123_somestring".match(/(\d+)_[a-z]+/ig); //this should be easy to detect
"image/png".match(/image.*/ig); //maybe this can be trivial... seems a comment end
```
`/(\d+)_[a-z]+/ig` should be highlighted.
at least it was sometime ago... something like fuchsia color.

is this thing only my issue or can be reproduced by elsebody?

**Comment by dail8859** [comment]
This is what I see. When setting the language to HTML:
![html](https://cloud.githubusercontent.com/assets/3694843/12236207/6a73519a-b846-11e5-87ad-2abb99c6e5c1.png)

When setting the language to JavaScript:
![js](https://cloud.githubusercontent.com/assets/3694843/12236224/7b62ffdc-b846-11e5-87f4-38cdf0567a7b.png)

In the second example the regex is bold (although barely noticeable). For the JavaScript language you can change this through the Style Configurator for now. I do agree that the regex should be styled like the first example though.

**Comment by dail8859** [comment]
Also, if this is not what it looks like for you, try deleting your `styles.xml` file most likely in your `%APPDATA%` directory.

**Comment by dail8859** [comment]
@donho Checking into this I see alot of discrepancies between the `javascript` and `javascript.js` lexer. Is it assumed that these two lexers try to style things similarly (obviously the embedded javascript has a different background color, etc)? For example I see there is a `type2` keywords list defined for the `javascript.js` lexer but never used in any style.

**Comment by madebycambiamentico** [comment]
is it still open this issue? by the way it was in fact a *"problem"* in `stylers.xml` (default is black bold). for my sanity sake, i changed the `javascript.js` REGEXP into the old fucsia style:

`<WordsStyle name="REGEX" styleID="14" fgColor="8000FF" bgColor="FFFFFF" fontName="" fontStyle="1" fontSize="" />`

thank you for the hint @dail8859 !
