### ISSUE TITLE
Notepad++ 8.5.1.0 and some previous versions crash at startup on Windows 2008R2

### ISSUE THREAD

**Issue by R-Voorhorst** [notepad-plus-plus/notepad-plus-plus#13510]
### Description of the Issue
Application crash when starting up on Windows 2008R2

### Steps to Reproduce the Issue

1. Start the program
2. 
3. 

### Expected Behavior
obvious: start up

### Actual Behavior
Notepad stopped working

### Debug Information

<Problem signature:
  Problem Event Name:	APPCRASH
  Application Name:	notepad++.exe
  Application Version:	8.5.1.0
  Application Timestamp:	6419f4ef
  Fault Module Name:	StackHash_918d
  Fault Module Version:	6.1.7601.24545
  Fault Module Timestamp:	5e0eb67f
  Exception Code:	c0000374
  Exception Offset:	00000000000bf262
  OS Version:	6.1.7601.2.1.0.274.10
  Locale ID:	1033
  Additional Information 1:	918d
  Additional Information 2:	918dc92ccecaf71de6135c5197d11492
  Additional Information 3:	f614
  Additional Information 4:	f6148fe3a150ffe0183d2d447a90c20b

Read our privacy statement online:
  http://go.microsoft.com/fwlink/?linkid=104288&clcid=0x0409

If the online privacy statement is not available, please read our privacy statement offline:
  C:\Windows\system32\en-US\erofflps.txt
>

**Comment by dail8859** [comment]
According to https://github.com/notepad-plus-plus/notepad-plus-plus/blob/master/SUPPORTED_SYSTEM.md

Only v8.4.6 and earlier are able to run on Windows Server 2008

**Comment by R-Voorhorst** [comment]
Yes, but it is on Windows 2008**R2** which is not 2008 and a version later; it is compatible with Windows 7 and on that platform the npp++ version is supported

**Comment by R-Voorhorst** [comment]
L.S.

 

The bug is on 2008R2 which is a version later and different from Windows 2008; 2008R2 is Win7 compatible and should run.

 

Best regards,

 

R. Voorhorst
