### ISSUE TITLE
Tab Size Should Be A Language Specific Setting

### ISSUE THREAD

**Issue by jolleekin** [notepad-plus-plus/notepad-plus-plus#1353]
Different languages use different tab sizes, so it would be better if Notepad++ can allow users to define the tab size at the language level.

**Comment by dail8859** [comment]
Settings > Preferences... > Tab Settings

**Comment by jolleekin** [comment]
Oh sorry. I must be using an old version.

**Comment by dail8859** [comment]
The newest version is [v6.8.8](https://notepad-plus-plus.org/download/v6.8.8.html). :)

**Comment by herrleonhardt** [comment]
doesn't work with userdefined Languages 👎

**Comment by CookiePLMonster** [comment]
Can you form it into a proper issue report? When posted this way it's very unlikely somebody will a) notice it b) take their time to verify it.

**Comment by herrleonhardt** [comment]
Sorry...
Ok, unfortunately it seems to be impossible to use tabSettings within a  UserDefinedLanguage

Is there a way to combine these two features?
