### ISSUE TITLE
New feature: tab groups

### ISSUE THREAD

**Issue by b4ckirc** [notepad-plus-plus/notepad-plus-plus#13559]
### Description of the Issue
I think can be useful a new feature: Creating tabs groups with the possibility of enlarging and collapsing groups of tabs.
Thanks!

### Expected Behavior
- Creating groups of tabs with name and color
- Adding tabs to group
- Removing tabs from group
- Enlarging and collapsing a group of tabs
- Delete a group (tabs automatically removed from group)

### Actual Behavior
Feature not available

**Comment by alankilborn** [comment]
This feature request already exists; https://github.com/notepad-plus-plus/notepad-plus-plus/issues/9517. Please search existing issues before creating identical new ones. If you have something new to say, just add to what already exists.

**Comment by b4ckirc** [comment]
> This feature request already exists; #9517. Please search existing issues before creating identical new ones. If you have something new to say, just add to what already exists.

ok, I'm sorry. I searched without success. I close the issue...

**Comment by alankilborn** [comment]
In case you were searching wrongly, here's what I did:

![image](https://user-images.githubusercontent.com/77065706/233646066-0b4f1631-e6e9-43fd-b062-2e2db929a32f.png)

**Comment by freezer2022** [comment]
Just in case noone knows - another old closed duplicate: 
- https://github.com/notepad-plus-plus/notepad-plus-plus/issues/5154
