### ISSUE TITLE
Highlight not visible in Elixir and GO

### ISSUE THREAD

**Issue by alex1543** [notepad-plus-plus/notepad-plus-plus#13550]
Dear Developer,

I have been using your editor Notepad++ for a long time. He helps me in developing programs in many languages. Thank you very much for your work. Is it possible to add syntax support for Elixir (https://elixir-lang.org/) and Go (Golang)? It is very inconvenient to watch white text without color highlighting. Version Notepad++ v7.9.5.

Sincerely,
Alexei

**Comment by ArkadiuszMichalski** [comment]
For GO we have separate issue https://github.com/notepad-plus-plus/notepad-plus-plus/issues/8090

**Comment by alex1543** [comment]
Thank you very much for your work. Notepad++ is the best editor for all languages.

Sincerely,
Alexei
