### ISSUE TITLE
Inappropriate language in installer 

### ISSUE THREAD

**Issue by cnapier** [notepad-plus-plus/notepad-plus-plus#13552]
### Description of the Issue

Inappropriate language and sentiments in the installer file.

### Steps to Reproduce the Issue

1. During the install process, random quotes are displayed at the bottom of the screen 
2. Some of these are inappropriate for certain audiences, especially in a school setting

### Expected Behavior

Not to see swearing and sexual references in the installer

### Actual Behavior

we did see them :)

### Debug Information

I appreciate this is not a bug as such. We use the software in School for students learning HTML and CSS, because the software is great. I just hadn't noticed the issue in the installer until now , and having the F-bomb on screen in front of a class of 12 year olds is .... sub-optimal!

I realise we dont pay for this software and I could probably make the changes in the NSIS file myself but I suspect then the auto-updater will still pull the official installer and then expose those quotes again.

This is not a demand by any means, but if it was possible to have the offending quotes removed from the installer it would perhaps make it more accessible for schools. I am not particularly au-fait with Github and pull requests etc but I am happy to go through the file and remove the lines and submit a "clean" version 

Warm regards
Colin

**Comment by alankilborn** [comment]
This comes up occasionally and is always rejected by the author of Notepad++.
I don't see any reason why it would be different this time, so recommend you close this issue.

**Comment by cnapier** [comment]
I think I have a work around. It is just the Branding text in line 333 PowerEditor/installer/nppSetup.nsi that is the issue. The quotes in the cpp files dont appear, not sure what they do or how to expose them.

I will just remove the updater folder from the installed machines and that will prevent students from seeing the installer or being prompted for updates, and I will just package up the updates via group policy when I get time.
