### ISSUE TITLE
Regression: Key-Combos in Shortcuts Mapper not displayed correctly 

### ISSUE THREAD

**Issue by Yaron10** [notepad-plus-plus/notepad-plus-plus#13554]
**STR:**
Settings -> Shortcuts Mapper.
Switch to the `Scintilla commands` tab.
Double-click on an item containing a Key-Combo.

**Result:**
![תמונה](https://user-images.githubusercontent.com/10229320/233430551-79d4672c-3765-4a3f-afe2-a7240371aba3.png)

https://github.com/notepad-plus-plus/notepad-plus-plus/blob/15decdb3d93a165ce362743ba32164391373687a/PowerEditor/src/WinControls/shortcut/shortcut.cpp#L1062

_There are some more `toString()` in that file._

***
Current master: https://github.com/notepad-plus-plus/notepad-plus-plus/commit/15decdb3d93a165ce362743ba32164391373687a

Notepad++ v8.5.2   (32-bit)
Build time : Apr 20 2023 - 08:54:38
Path : ---\Notepad++.Win32.Release.exe
Command Line : 
Admin mode : ON
Local Conf mode : ON
Cloud Config : OFF
OS Name : Windows 7 Enterprise (32-bit)
OS Build : 7601.23964
Current ANSI codepage : 1255
Plugins : 
    ComparePlus (1.1)
    HTMLTag (1.3.6)
    MenuIcons (2.0.2)
    PythonScript (1.5.4)
    _CustomizeToolbar (4.2)

**Comment by Yaron10** [comment]
Reproducible on Windows 10 as well.

**Comment by rdipardo** [comment]
> *There are some more `toString()` in that file.*

Looks like fff5f9b simply missed a few spots:

~~~diff
diff --git a/PowerEditor/src/WinControls/shortcut/shortcut.cpp b/PowerEditor/src/WinControls/shortcut/shortcut.cpp
index 635aa386..11abff9a 100644
--- a/PowerEditor/src/WinControls/shortcut/shortcut.cpp
+++ b/PowerEditor/src/WinControls/shortcut/shortcut.cpp
@@ -1036,7 +1036,7 @@ void ScintillaKeyMap::showCurrentSettings()
 
 void ScintillaKeyMap::updateListItem(int index)
 {
-	::SendDlgItemMessage(_hSelf, IDC_LIST_KEYS, LB_INSERTSTRING, index, reinterpret_cast<LPARAM>(toString(index).c_str()));
+	::SendDlgItemMessage(_hSelf, IDC_LIST_KEYS, LB_INSERTSTRING, index, reinterpret_cast<LPARAM>(string2wstring(toString(index), CP_UTF8).c_str()));
 	::SendDlgItemMessage(_hSelf, IDC_LIST_KEYS, LB_DELETESTRING, index+1, 0);
 }
 
@@ -1059,7 +1059,7 @@ intptr_t CALLBACK ScintillaKeyMap::run_dlgProc(UINT Message, WPARAM wParam, LPAR
 
 			for (size_t i = 0; i < _size; ++i)
 			{
-				::SendDlgItemMessage(_hSelf, IDC_LIST_KEYS, LB_ADDSTRING, 0, reinterpret_cast<LPARAM>(toString(i).c_str()));
+				::SendDlgItemMessage(_hSelf, IDC_LIST_KEYS, LB_ADDSTRING, 0, reinterpret_cast<LPARAM>(string2wstring(toString(i), CP_UTF8).c_str()));
 			}
 			::SendDlgItemMessage(_hSelf, IDC_LIST_KEYS, LB_SETCURSEL, 0, 0);
 
@@ -1161,7 +1161,7 @@ intptr_t CALLBACK ScintillaKeyMap::run_dlgProc(UINT Message, WPARAM wParam, LPAR
 					{
 						if (res == static_cast<int32_t>(oldsize))
 						{
-							::SendDlgItemMessage(_hSelf, IDC_LIST_KEYS, LB_INSERTSTRING, static_cast<WPARAM>(-1), reinterpret_cast<LPARAM>(toString(res).c_str()));
+							::SendDlgItemMessage(_hSelf, IDC_LIST_KEYS, LB_INSERTSTRING, static_cast<WPARAM>(-1), reinterpret_cast<LPARAM>(string2wstring(toString(res), CP_UTF8).c_str()));
 						}
 						else
 						{	//update current generic_string, can happen if it was disabled

~~~

**Comment by Yaron10** [comment]
@rdipardo,

:+1: 
Yes, modifying those occurrences fix the issue.

Thank you.

**Comment by Yaron10** [comment]
Thank you @donho. 👍
