### ISSUE TITLE
Request: Make it work for MACs?

### ISSUE THREAD

**Issue by peterthorpe5** [notepad-plus-plus/notepad-plus-plus#13560]
Hi Notepad++ people,

This is the King of Editors! I miss using it a lot. Would you please make it work for MACs?

regards,

Pete

**Comment by alankilborn** [comment]
See https://github.com/notepad-plus-plus/notepad-plus-plus/wiki/FAQ#support-for-systems-other-than-the-ms-windows-family

And please close this issue.
