### ISSUE TITLE
[Regression] Run Macro Multiple Times: "number of times" is ignored 

### ISSUE THREAD

**Issue by Yaron10** [notepad-plus-plus/notepad-plus-plus#13561]
**STR:**
Save a simple macro (e.g. press Enter once).
Run Macro Multiple Times: insert `4`.

**Result:**
The macro is run once.

***
Current master: https://github.com/notepad-plus-plus/notepad-plus-plus/commit/0457a112c76ddc883a99074cf459a970741cf5b6.

**Comment by ozone10** [comment]
@Yaron10 
sorry my mistake, will fix it soon.
