### ISSUE TITLE
Regression: macro is not saved properly

### ISSUE THREAD

**Issue by Yaron10** [notepad-plus-plus/notepad-plus-plus#13565]
**STR:**
Open a file containing the word `cpp`.
Start recording a macro.
Open the Find dialog.
Search for `cpp` in the current document.
Stop recording the macro.
Save the macro.
Run the saved macro.

**Result:**
A search for `c` is executed.

***
Current master: https://github.com/notepad-plus-plus/notepad-plus-plus/commit/0457a112c76ddc883a99074cf459a970741cf5b6.

**Comment by donho** [comment]
@Yaron10 
Is it a regression due to https://github.com/notepad-plus-plus/notepad-plus-plus/commit/fff5f9b24c1e7a6f33633b665c06e8785f6a3455 ?

**Comment by Yaron10** [comment]
@donho,

The macros I've tested (_Find in Current Document_, _Find in Files_) work properly with the binary before https://github.com/notepad-plus-plus/notepad-plus-plus/commit/fff5f9b24c1e7a6f33633b665c06e8785f6a3455.

And @doug1234's PR fixes _Find in Current Document_.

**Comment by rdipardo** [comment]
@donho,
> Is it a regression due to [fff5f9b](https://github.com/notepad-plus-plus/notepad-plus-plus/commit/fff5f9b24c1e7a6f33633b665c06e8785f6a3455) ?

*Sans doute.*

`_options._str2Search` is a *wide string*. If you don't convert it *before* it goes to TinyXml, you're effectively doing this: `(char*)_options._str2Search`; e.g.

~~~cpp
#include <iostream>
#include <windows.h>
int main (void)
{
    TCHAR *wstr = TEXT("cpp");
    printf("%s", wstr);
}
~~~

Prints: `c`

**Comment by donho** [comment]
> And @doug1234's PR fixes _Find in Current Document_.

Not completely - the PR doesn't work with non-western Unicode characters.
