### ISSUE TITLE
notepad++ doesn´t show "&&" in my C-source file

### ISSUE THREAD

**Issue by rse-stein** [notepad-plus-plus/notepad-plus-plus#1357]
Notepad++ 6.8.6, Windows 7 Ultimate x64

In my c-Source there are statements like:
  if ( 		(pMOS_L_Get() == _MOS_L_OFF )			// 
	&&	(pMOS_H_Get() == _MOS_H_OFF )
  ) {
or
if ( 		  ( (V1_T1 >= _VS2) && (V1_T1 < _VCC_MIN ) )   

In notepad++ i can not see the "&&", instead i see nothing (maybee spaces)

I´m using also SourceCookifier.

**Comment by rse-stein** [comment]
![editor01](https://cloud.githubusercontent.com/assets/16668463/12267161/0e8119e2-b947-11e5-9ea2-afd8e6e3f484.jpg)
![np01](https://cloud.githubusercontent.com/assets/16668463/12267162/0e86d53a-b947-11e5-92cf-a1af11000fa3.jpg)

see attached screenshots, first from an other editor, second from np++

**Comment by dail8859** [comment]
Most likely you are using the Source Code Pro font. There have been issues with it not showing ampersands. #1123, #679, #552, #547

**Comment by rse-stein** [comment]
Hello,
i installed the new Source Code Pro fonts (C:\Windows\Fonts).
After that nothing was seen in npp, even no normal Text. So i removed npp and installed notepad++ 6.8.8.
Now it works.
Thanks

Raimund
