### ISSUE TITLE
Allow plugins to apply darkmode colors to dialogs using method call or API call?

### ISSUE THREAD

**Issue by BdR76** [notepad-plus-plus/notepad-plus-plus#13574]
### Description of the Issue
Is it possible to somehow call the [autoSubclassAndThemeChildControls](https://github.com/notepad-plus-plus/notepad-plus-plus/blob/master/PowerEditor/src/NppDarkMode.cpp#L1940) function from within a plug-in? afaik there isn't a API call for this. That way the plugins can use the default Notepad++ function to apply darkmode colors uniformly to all dialogs.

Currently most plugins display any dialogs in normal/lightmode colors even when Notepad++ is set to darkmode. I know there is `DWS_USEOWNDARKMODE` but for simple Settings/About forms when there are no special controls or anything, it would imho be better to just let Notepad++ change these to darkmode.

### Steps to Reproduce the Issue
1) Set Notepad++ to darkmode `Settings > Preferences > Dark Mode`
2) See "About" dialog in (almost?) all plugins, the CSV Query parse settings, CSV Lint setting dialogs etc.

![csvquery_example_dialog](https://user-images.githubusercontent.com/7793956/233845357-8ebfe4bf-8173-4cb9-9402-ffd8575e936d.png)

### Expected Behavior
Be able to call the function [autoSubclassAndThemeChildControls](https://github.com/notepad-plus-plus/notepad-plus-plus/blob/master/PowerEditor/src/NppDarkMode.cpp#L1940) to stylize any extra dialogs (settings, parameters, about etc) with the default darkmode colors, see mockup below.

![notepad_plugin_darkmode](https://user-images.githubusercontent.com/7793956/233845379-a6732b3a-51d2-4e0f-a0b2-281f07140761.png)

### Actual Behavior
When Notepad++ is set to darkmode, some plugin dialogs will display using the normal/lightmode colors.

### Debug Information
Tagging @ozone10 for his knowledge about darkmode

**Comment by rdipardo** [comment]
To [quote the author of #11711](https://github.com/notepad-plus-plus/notepad-plus-plus/pull/11711#issuecomment-1146860165):

> there might be visual glitches if plugin is written in C#, as it use WinForms for GUI, it also does not affect plugins which use their own custom control [...]

Even assuming N++ could predict every possible GUI component a plugin may have, the implementation would be in C++. You still need some kind of bridge on the .NET side to make it usable.

It might be more productive asking [the .NET plugin project](https://github.com/kbilsted/NotepadPlusPlusPluginPack.Net) to include the subclassing capability in the template.

**Comment by ozone10** [comment]
@BdR76 
there is no easy way to get handle to these dialogs. So dark mode should be handled by plugin author.

I could try to provide call to 
https://github.com/notepad-plus-plus/notepad-plus-plus/blob/c76f178534bba518f263c8120b732801e13c4916/PowerEditor/src/NppDarkMode.cpp#L2542

but it won't be soon.

**Comment by BdR76** [comment]
PRoviding a call to `autoSubclassAndThemePluginDockWindow` sounds great. Although I don't exactly know what the `SetWindowSubclass` part does.

**Comment by ozone10** [comment]
@BdR76 
unfortunately subclassing for C# plugins won't work.

**Comment by rdipardo** [comment]
@BdR76, this quick patch will get you started (it's copied from [my forum post](https://community.notepad-plus-plus.org/post/85943)): [WIP-Integrate-Npps-dark-mode-API.diff.txt](https://github.com/notepad-plus-plus/notepad-plus-plus/files/11328336/WIP-Integrate-Npps-dark-mode-API.diff.txt)
