### ISSUE TITLE
Generic darkmode for plug-in windows is not applied to all controls (groupbox, panels, labels etc)

### ISSUE THREAD

**Issue by BdR76** [notepad-plus-plus/notepad-plus-plus#13572]
### Description of the Issue
The generic darkmode for plug-in dock panels was added, see [PR 11711](https://github.com/notepad-plus-plus/notepad-plus-plus/pull/11711) but it doesn't apply darkmode colors to all wincontrols, for example groupbox, panel and labels. See screenshot below, the darkmode colors are not appied to the textbox within the panel.

![notepad_darkmode_window](https://user-images.githubusercontent.com/7793956/233844283-c60a325b-3714-4a8b-ac77-f98823750011.png)

### Steps to Reproduce the Issue
See some plug-ins with a docking panel, for example CSV Lint, NppMarkdownPanel, CSV Query (only the buttons), Json Tools (Tree viewer)

### Expected Behavior
The main docking window should use darkmode color for all controls/labels/textboxes etc.

### Actual Behavior
The panel shows some widgets/controls in light mode colors

### Debug Information

I think it has to do with function [autoSubclassAndThemeChildControls](https://github.com/notepad-plus-plus/notepad-plus-plus/blob/master/PowerEditor/src/NppDarkMode.cpp#L1940) which doesn't call `EnumChildWindows` recursively for container-type controls.

If I understand correctly, the container controls like Panels, GroupBoxes, SplitContainer etc are called [REBARCLASSNAME](https://learn.microsoft.com/en-us/windows/win32/controls/common-control-window-classes) controls

Tagging @ozone10 in this issue, because of the required knowledge of darkmode support, (was suggested in [thread](https://community.notepad-plus-plus.org/topic/24403/darkmode-doesn-t-stylize-all-plugin-controls-on-docked-window-groupbox-panel-labels-etc))

**Comment by ozone10** [comment]
@BdR76 
Are those C# plugins?
IIRC C# are using some containers/controls with its classname which are not same as standard win32 classname.
They may behave same but subclassing may/may not work.

For edit, listbox, static text controls those are affected by `WM_CTLCOLOR*` messages processed by their parents.
So the edit control in container won't be affected since its parent - container does not handle these messages.

Notepad++ only process `WM_CTLCOLOR*` messages for main window.

I won't be able soon to investigate this, my pc recently broke.

**Comment by ozone10** [comment]
@BdR76 
I did some quick testing, unfortunately there is no easy way to make generic dark mode work with C# plugins.

**Comment by alankilborn** [comment]
@ozone10 

How about C++ plugins that derive from the official N++ plugin template?

Reference [HERE](https://community.notepad-plus-plus.org/post/85915) where I said:

>I tried a quick test using the N++ plugin demo, found [HERE](https://github.com/npp-plugins/plugindemo).

>I created a groupbox and an edit control on the docking dialog. I ran it and both were “dark” in dark mode. Then in the code, I changed the parent of the edit control to be the groupbox. Rerunning that, the edit control ended up not being “dark”.

**Comment by ozone10** [comment]
@alankilborn 
that makes sense, since edit, listbox, static text controls are handled by parent by processing `WM_CTLCOLOR*` messages,
and only docking container/main dialog is subclassed with these messages.

**Comment by ozone10** [comment]
@alankilborn 
I am working on fix for https://github.com/notepad-plus-plus/notepad-plus-plus/issues/13574.
This should help.

**Comment by donho** [comment]
https://github.com/notepad-plus-plus/notepad-plus-plus/commit/e7f321f21a2feae3669b286ae2b64e6e033f231f
