### ISSUE TITLE
URL parsing issue with '#' and '?'

### ISSUE THREAD

**Issue by desk7** [notepad-plus-plus/notepad-plus-plus#13583]
### Description of the Issue
there is a problem with the parsing of the URL.

If there is a '#' within the URL, and in the following there is a '?', the part of the URL following '?' is not recognized.

### Steps to Reproduce the Issue

1. type an URL such as `https://example.com/#/app/0?context`
2. the part of the URL after `?` is not recognized as URL.

### Expected Behavior

All the `https://example.com/#/app/0?context` should be recognized as URL.

### Actual Behavior

Only `https://example.com/#/app/0` is parsed as URL.

### Debug Information

Notepad++ v8.5.2   (64-bit)
Build time : Apr  4 2023 - 19:55:32
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 10 Home (64-bit)
OS Version : 22H2
OS Build : 19045.2846
Current ANSI codepage : 1252
Plugins : 
    DSpellCheck (1.4.24)
    mimeTools (2.9)
    NppConverter (4.5)
    NppExec (0.8.2)
    NppExport (0.4)

### Screenshot
<img width="370" alt="test" src="https://user-images.githubusercontent.com/46022640/234059412-8492c5d0-5d09-4dec-a7e5-d2a2fbc2dfd6.png">

**Comment by sredna** [comment]
It does look like a bug. RFC3986 says
 >  The characters slash ("/") and question mark ("?") are allowed to represent data within the fragment identifier

**Comment by sistosilvio** [comment]
I see the issue everyday. It happens with links to a popular web based Agile Application. Using N++ version 8.5.8 
Screenshot
![image](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/24465451/9697ef1c-8385-491d-8dff-b83262a34f2a)

**Comment by page200** [comment]
This also happens with URLs of the Gmail web app. So it can affect many people.

The URL with a draft email starts for example with `https://mail.google.com/mail/u/0/#inbox?compose=`

**Comment by mikefitz** [comment]
This is also a problem if there are two question marks e.g.
https://myCompany.service-now.com/nav_to.do?uri=incident?sys_id=8833905836858bb35d4
The link ends at the end of uri=incident
So the problem is: if a ? follows a # or another ? the URL stops at the # or second ?

**Comment by WAZAAAAA0** [comment]
query strings in local URLs have a vaguely similar bug

for example this shows fully underlined:
`file:///C:/123/index.htm?key=value`
but when you click it, anything starting from the question mark gets ignored and you will instead navigate this:
`file:///C:/123/index.htm`

**Comment by ArkadiuszMichalski** [comment]
Similar to https://github.com/notepad-plus-plus/notepad-plus-plus/issues/9212.
