### ISSUE TITLE
Change vcxproj to not treat warnings as errors

### ISSUE THREAD

**Issue by molsonkiko** [notepad-plus-plus/notepad-plus-plus#13586]
### Description of the Issue

When I try to compile Notepad++ using Visual Studio 2022, it fails due to 89 warnings that are treated as errors. All of these errors seem to be in `atomic.h` and `xlocale.h` in the MSVC toolset, [at least one of which seem to have developed this problem in Visual Studio 2019](https://stackoverflow.com/questions/67732065/why-does-vs2019-pro-have-compile-errors-with-xutility-xmemory-and-atomic-when).

I would suggest changing [PowerEditor/visual.net/notepadPlus.vcxproj](https://github.com/notepad-plus-plus/notepad-plus-plus/blob/master/PowerEditor/visual.net/notepadPlus.vcxproj) to not treat compiler warnings as errors by default.

### Steps to Reproduce the Issue

1. Try to compile the project using Visual Studio 2022 on Windows in Debug mode using an untouched fork of master.
2. After waiting a very long time (about as long as it would take for the project to compile if nothing was wrong) compilation will fail.
### Expected Behavior

The program should compile when there are no errors in the code in this repository.
### Actual Behavior

The code fails to compile as described above.
### Debug Information
Using a fork of master originating in commit `2c6c556a3a657e0c33598372f9872ef632cb55d5`.
<details><summary>Visual Studio info</summary>
Microsoft Visual Studio Community 2022
Version 17.4.3
VisualStudio.17.Release/17.4.3+33205.214
Microsoft .NET Framework
Version 4.8.04084

Installed Version: Community

Visual C++ 2022   00482-90000-00000-AA271
Microsoft Visual C++ 2022

ASP.NET and Web Tools   17.4.326.54890
ASP.NET and Web Tools

Azure App Service Tools v3.0.0   17.4.326.54890
Azure App Service Tools v3.0.0

C# Tools   4.4.0-6.22580.4+d7a61210a88b584ca0827585ec6e871c6b1c5a14
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Linux Core Dump Debugging   1.0.9.33020
Enables debugging of Linux core dumps.

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

NuGet Package Manager   6.4.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit https://docs.nuget.org/

TypeScript Tools   17.0.10921.2001
TypeScript Tools for Microsoft Visual Studio

Viasfora   4.4.212
Add color to your Visual Studio editor!

Visual Basic Tools   4.4.0-6.22580.4+d7a61210a88b584ca0827585ec6e871c6b1c5a14
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual C++ for Linux Development   1.0.9.33020
Visual C++ for Linux Development

Visual F# Tools   17.4.0-beta.22512.4+525d5109e389341bb90b144c24e2ad1ceec91e7b
Microsoft Visual F# Tools

Visual Studio IntelliCode   2.2
AI-assisted development for Visual Studio.
</details>

**Comment by alankilborn** [comment]
Current master (as of a few moments ago) builds fine for me.

**Comment by molsonkiko** [comment]
Eh, that's weird. For now, it's only an inconvenience for me, so I'll just close this.

**Comment by ozone10** [comment]
@molsonkiko 
you need at least Microsoft Visual Studio 2022 Version **17.5**

**Comment by molsonkiko** [comment]
Thanks for the help, @ozone10 !
