### ISSUE TITLE
[DarkMode] Groupbox key accelerators inconsintency

### ISSUE THREAD

**Issue by ozone10** [notepad-plus-plus/notepad-plus-plus#13597]
### Description of the Issue

Groupbox key accelerators in dark mode are not in sync with rest of controls.
![image](https://user-images.githubusercontent.com/55940305/234657228-edb4bdd5-6ad9-4938-b7bd-56677723b8bd.png)
![image](https://user-images.githubusercontent.com/55940305/234657292-ce52c867-689d-47a1-9c03-cb1dbadbb186.png)
![image](https://user-images.githubusercontent.com/55940305/234657554-446ae041-7648-4037-9409-978b787ee6a4.png)
![image](https://user-images.githubusercontent.com/55940305/234657489-564018f7-4547-480c-9aa2-315543f55880.png)

### Steps to Reproduce the Issue

1. Enable dark mode
2. Open Run or Run a Macro Multiple times with mouse
3. Press alt to enable key accelerators

### Expected Behavior

Consistent key accelerators state.
### Actual Behavior

Inconsistent key accelerators state.

### Debug Information

Notepad++ v8.5.2 https://github.com/notepad-plus-plus/notepad-plus-plus/commit/80b34f0adf3c5249f9d9c1dc52c41e9ef2c84926

**Comment by donho** [comment]
@ozone10 
I cannot reproduce the 2nd screenshot for each dialog under my Windows 11.
Could you provide more detail of STR please?

**Comment by ozone10** [comment]
@donho 
Windows 11 automatically redraws, so you won't be able to reproduce it, but earlier Windows versions are affected.

**Comment by donho** [comment]
@ozone10 
In which OS can we reproduce this glitch then?

**Comment by ozone10** [comment]
@donho 
I can test only Windows 10, but it should be every Windows versions except Windows 11.
