### ISSUE TITLE
Silent installer doesn't install Win11 context menu

### ISSUE THREAD

**Issue by Schlumpf** [notepad-plus-plus/notepad-plus-plus#13592]
### Description of the Issue
When the program is installed in  silent mode, the Win11 context menu is not installed.

### Steps to Reproduce the Issue
1. Install in silent mode

### Expected Behavior
Win11 context menu available

### Actual Behavior
Win11 context menu not available

### Debug Information
Notepad++ v8.5.2   (32-bit)
Build time : Apr  4 2023 - 19:48:53
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Command Line : "K:\mol\Textdatei.txt"
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 11 Enterprise (64-bit)
OS Version : 21H2
OS Build : 22000.1696
Current ANSI codepage : 1252
Plugins : 
    mimeTools (2.9)
    NppConverter (4.5)
    NppExport (0.4)

**Comment by sredna** [comment]
Does it happen if you delete HKLM\Software\Microsoft\Windows\CurrentVersion\Uninstall\Notepad++ in the registry before running it silently?

**Comment by Schlumpf** [comment]
Still the same.

We have investigated the problem further and found that it is due to the Windows user. The context menu is displayed only under the user who has installed the program. The problem is that in our case the program is installed under an admin account and is then not available for the actual user. The old context menu is available for all users.

**Comment by donho** [comment]
This issue is solved in v8.5.3 usually.
