### ISSUE TITLE
right mouse completely disabled on intensive search in editor

### ISSUE THREAD

**Issue by ophian** [notepad-plus-plus/notepad-plus-plus#136]
First let me say thanks. I love this editor!

I often work with a huge amount of opened files. Because of this and other repository needs, I have to use the search recursively on directories. At some time of working the results give me a complete shut up of the right mouse click to use copy/paste and others in the opened files. I really bought a new mouse because of this, while I couldn't believe it to be an issue of npp. But this still happens with several versions until current. Mouse is doing well everywhere else. Starting npp up this is OK again. 
Is there a restriction on RAM or something, preventing npp right mouse environment pop up?
I wonder why I have never read about others having this issue. It might be based to Scintilla though.

**Comment by andreas-jonsson** [comment]
@donho Which version of Visual Studio is used to compile the release version? I'm able to reproduce this issue with 6.7.8.2 from the website, but when compiling the same tag on my own computer (VS 2013 Update 4), it disappears.

**Comment by ariccio** [comment]
> Which version of Visual Studio is used to compile the release version?

Might be related to [a comment on a change he made](https://github.com/donho/notepad-plus-plus/commit/0628508ef0dbdda9955134920b9331adb7bf02ca#commitcomment-11342725).

 12.0.21005.1 is VS2013 RTM

**Comment by ophian** [comment]
> I'm able to reproduce this issue with 6.7.8.2 from the website, but when compiling the same tag on my own computer (VS 2013 Update 4), it disappears.

Good to hear this, thanks. So we may expect a solution with next release...? :)

**Comment by andreas-jonsson** [comment]
Possibly, the project owner (Don) needs to get involved.

**Comment by donho** [comment]
@andreas-jonsson My version of VS2013 is 12.0.21005.1
OK, I see the problem - I will update my VS for the next release.

**Comment by donho** [comment]
@andreas-jonsson  After updating to 12.0.31101.00 update 4 (under my 32 bits Windows 8.1), I can still reproduce this problem.
OTOH, I cannot reproduce it with the binary compiled under my 64 bits Windows 8.1 by VS2013 12.0.21005.1.
I believe that the problem is due to the difference of binary generated by VS2013 under 32 and 64 bits.

**Comment by ophian** [comment]
Still not solved with 6.7.9

**Comment by Tarun80** [comment]
Would love to see a 64-bit version for those really large/long text documents.

**Comment by milipili** [comment]
A 64-bit version is planned for 7.x

**Comment by robotboy655** [comment]
Please look into this issue. Every single time I use "Find in Files" feature the right clicking no longer works. A restart fixes it.

**Comment by donho** [comment]
Fixed.
