### ISSUE TITLE
GUI glitch in "Preferences -> Print"

### ISSUE THREAD

**Issue by Yaron10** [notepad-plus-plus/notepad-plus-plus#13601]
**STR:**
_Preferences -> Print_.
Add some variables to the _Left part._

**Result:**
![תמונה](https://user-images.githubusercontent.com/10229320/235325176-b6329673-a421-4bc9-a65a-66c01a8c57dc.png)

***
Notepad++ v8.5.2.

**Comment by ozone10** [comment]
I've mentioned it here https://github.com/notepad-plus-plus/notepad-plus-plus/issues/10169
I will see what I can do.

**Comment by Yaron10** [comment]
@ozone10,

👍 
Thank you for looking into it, and best of luck.
