### ISSUE TITLE
[Feature Request] In Find In Files form allow the user to filter files modified within a specified period of time (x minutes or hours or days)

### ISSUE THREAD

**Issue by fededim** [notepad-plus-plus/notepad-plus-plus#13611]
A want to suggest a feature that would be very useful in Find in Files form.

The feature would allow the user to **filter files in the supplied directory modified within a period of time (x minutes or hours or days)**.

This would be very useful if you use Notepad++ to analyse the most recent application logs.

**Comment by alankilborn** [comment]
It's a fine idea, but the user interface design get complicated quickly when you think about how to support all of the different possible time ranges a user might want.

**Comment by fededim** [comment]
Hmmm IMHO it isn't too complicated you just need to add:

1.  An int/float textbox for specifying a value, if the value is not null and valid the filter is applied to the files inside the specified folder with a potential filter pattern. 
2. A dropdownlist (sorry in the picture I wrongly inserted combobox, you can only select a value from list, not type also something) for specifying the time unit containing 3 choices: min(s), hour(s), day(s), the dropdownlist preselects a default value (min(s) ?) .

Here follows the picture of where you could insert these 2 graphic controls:

![image](https://user-images.githubusercontent.com/8364158/236043876-32fb5056-fcb9-4958-8df0-0a10fa249162.png)

**Comment by alankilborn** [comment]
Users want lots of things, once you give them the core capability.

* Files older than _____
* Files modify between _____ and _____
* etc.

Sure, for your "simple" need of "most recent application logs"...  but supporting only that would open the door to more complex needs, and thereby I stand by my original statement of "gets complicated quickly".

**Comment by fededim** [comment]
Well the feature I proposed as reported in the title wants **to filter files modified within a specified period of time due to the use case of analysing the most recent application logs**. If you want to evaluate also other use cases fine, maybe we can leave this feature request open and look at newer comments in the following months.

**Comment by alankilborn** [comment]
Sorry, you don't always get exactly what you want.  Also worth noting is often you don't get anything. :-)

Issues/requests here often are turn into _generalized_ new features, so the implementation has to cover a breadth of needs.

If a very specific thing is implemented, then others start wailing that they can't make it do exactly what _they_ want.

**Comment by fededim** [comment]
IMHO what I suggested has a usefulness meaning, but I'll let the community decide...as far as the fact I do not get anything I do not complain, everyone makes its own decisions, should I need this feature inevitably I would branch the code and implement it by myself, it's just a matter of time :-)

**Comment by alankilborn** [comment]
If you implement something, please do submit it.

**Comment by alankilborn** [comment]
Here's a sample UI for how this could be made:

![image](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/77065706/96dd3416-d9dc-4335-8498-cba1a5f87d27)

![image](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/77065706/e317672d-3843-463f-9884-5fda5be5ab90)

The "date picker" would be the typical one:

![image](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/77065706/bce048d9-ce5a-4bd1-a23b-a886c2e28289)

And the orange dropdown control could lead to some/all of the following choices:

![image](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/77065706/1ebe8dfb-ce39-4ac0-823f-06e249b4db7c)

The ideas and screenshots here come from a program called XYplorer, see https://www.xyplorer.com/

But, honestly, I have no idea what the text `Enter 0 for "this".`  means on its UI.  :-(

**Comment by alankilborn** [comment]
@donho 

If you have interest in this issue, and want to assign me, I'll implement something similar to the sample UI I've proposed.

If there's no interest, then I suppose rejecting this issue is the best thing to do.

**Comment by donho** [comment]
Making an already complex UI more complex for a feature not really asked frequently won't be accepted indeed.
I'll close it now and see if there are similar FR coming.

**Comment by alankilborn** [comment]
>Making an already complex UI more complex...

Just a final post to say that an idea for the UI would be to put controls for time-based criterion on a separate tab, with an "enable" on the _Find in Files_ tab.  Not perfect I know, but just a thought.
