### ISSUE TITLE
My problem is the same as issue #13586.

### ISSUE THREAD

**Issue by wednesday2024** [notepad-plus-plus/notepad-plus-plus#13626]
I get these same 89 errors as well. I used to be able to compile NotePad++ without an issue. Now for the past 4 months I have been stuck with these 89 errors. I have the latest Visual Studio 2022 Community 17.5.5 installed with all of the needed components to compile NotePad++. I can compile Lexilla and Scintilla just fine but when it comes to NotePad++, it just fails. I've reinstalled Windows several times thinking maybe Windows is corrupted or something but obviously that didn't fix it. Has anyone found a fix for this yet? Thanks.

Here is the original issue link from someone else: https://github.com/notepad-plus-plus/notepad-plus-plus/issues/13586

**Comment by Ekopalypse** [comment]
Make sure that the installed SDK matches the configured one. Maybe you just need to retarget your solution/projects?

**Comment by rdipardo** [comment]
> Make sure that the installed SDK matches the configured one. Maybe you just need to retarget your solution/projects?

Some illustrations might be helpful here.

The active SDK version is the `%WindowsSDKVersion%` env var set by Visual Studio (by default the highest version installed):

~~~sh-session
**********************************************************************
** Visual Studio 2022 Developer Command Prompt v17.5.5
** Copyright (c) 2022 Microsoft Corporation
**********************************************************************

> echo %WindowsSDKVersion%
10.0.19041.0\
~~~

You can have multiple SDK versions installed: each one goes into a unique subfolder:

<img width="640" alt="path-to-installed-sdks" src="https://user-images.githubusercontent.com/59004801/236703900-93c2990c-942e-4a86-95eb-92e12d626f7f.png">

Install new SDKs with `Visual Stdio Installer` > `Modify` > `Individual components`: 

<img width="640" alt="installing-updated-sdks" src="https://user-images.githubusercontent.com/59004801/236703905-17acac01-98a6-48ef-a05c-8708edd86e78.png">

**Comment by ozone10** [comment]
@R5-3600 
could you run these 2 powershell commands 
```powershell
get-childitem -Path 'C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC'

get-content 'C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Auxiliary\Build\Microsoft.VCToolsVersion.v143.default.props'
```

**Comment by ozone10** [comment]
@R5-3600 
first command shows installed VC tools. You have latest installed,
but from second command, you're not using it. It should be 14.35.32215.

Check if you need different VC tools versions, if not use only the latest 
![image](https://user-images.githubusercontent.com/55940305/236813628-51b41d0d-bc52-4b3c-8404-d10277b7baef.png)

**Comment by ozone10** [comment]
@R5-3600
👍
You can now close this issue.
