### ISSUE TITLE
Search no longer working if search term includes underscore

### ISSUE THREAD

**Issue by TonyRietwyk** [notepad-plus-plus/notepad-plus-plus#1363]
I've just ungraded from 6.8.3 to 6.8.8.  When I search for text containing an underscore in normal mode, it doesn't match, and the error text says Can't find the text "..." - but the text shown does not include the underscore.  This makes the editor useless for programs with variables with underscores! See the attached image. 
![notepad_plusplus_search_bug](https://cloud.githubusercontent.com/assets/5600947/12313958/8f82424e-bac0-11e5-8965-90a0de6fc649.png)

**Comment by TonyRietwyk** [comment]
Weird.  I reloaded the file and now search works no problems.

**Comment by dail8859** [comment]
If this is working as expected, please close this issue. Thanks.

**Comment by TonyRietwyk** [comment]
It has continued to work OK so I'll close it.  I think an internal issue should be raised to explain why the underscore was stripped from the search text.
