### ISSUE TITLE
Empty Folder as Workspace 

### ISSUE THREAD

**Issue by PaltryProgrammer** [notepad-plus-plus/notepad-plus-plus#13639]
greetings kind regards please see attached PNG demonstrate Folder as Workspace is displayed empty . kindly advise thank you . version is most recent i.e. to wit 8.5.2 as can be seen . PS i am always surprised application About pages do not provide [copy version to clipboard] button .
![image](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/48535920/d8ac55f1-66b7-4b5d-a163-88ee396e79b2)
![image](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/48535920/23a8eb83-0d1a-446f-a2f0-107ca96f451e)

**Comment by rdipardo** [comment]
> PS i am always surprised application About pages do not provide [copy version to clipboard] button .

https://github.com/notepad-plus-plus/notepad-plus-plus/blob/3c15ff5783de1d2d9e0f73be8209b557d7aa6fe2/ISSUE_TEMPLATE.md?plain=1#L19-L23

**Comment by alankilborn** [comment]
>PS i am always surprised application About pages do not provide [copy version to clipboard] button .

If you'd actually read the instructions for submitting an issue, you'd find a very-copyable version on the _Debug Info_ menu item.

**Comment by PaltryProgrammer** [comment]
i could not locate the aforementioned "instructions for submitting an issue" . perhaps you would be kind enough to direct me to it . actually your kind post confuses me . the post seems to state the "instructions for submitting an issue" will provide instruction re/ the Debug Info menu item . that does not seem logical .  i am always surprised how often it is difficult to comprehend the logic of a kind posters' kind advice . if you kindly elaborate i would be most appreciative as i am eager to comprehend the logic you present .

**Comment by alankilborn** [comment]
>i could not locate the aforementioned "instructions for submitting an issue" 

When you click the button to create a new issue, a template comes up, which you either ignored or deleted out before creating your original posting here.  This template had instructions, including how to submit proper Debug Info.

**Comment by donho** [comment]
missing debug info and detail description of issue.

**Comment by PaltryProgrammer** [comment]
below please find aforementioned "debug info"
re/ said "detail description of issue." may i say a picture is worth one thousand words .
- kind regards

Notepad++ v8.5.4   (64-bit)
Build time : Jun 17 2023 - 20:42:45
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : "C:\Program Files\Notepad++\change.log" 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 10 Pro (64-bit)
OS Version : 22H2
OS Build : 19045.3086
Current ANSI codepage : 1252
Plugins : 
    DSpellCheck (1.4.24)
    mimeTools (2.9)
    NppConverter (4.5)
    NppExport (0.4)

**Comment by alankilborn** [comment]
>re/ said "detail description of issue." may i say a picture is worth one thousand words 

Nope (if you mean your original screenshot).

Again, you have failed to follow the instructions for submitting an issue.

The instructions require you to specify action steps on how to reproduce your problem.
You screenshot indicates nothing -- an empty FAW display is totally possible in a normal operation sequence.  HOW you got to the empty display point MAY be relevant, but you need to show convincing evidence of that.

Or, you can continue being obtuse.

**Comment by PaltryProgrammer** [comment]
hopefully the attached few more one-thousand words are not obtuse 
![Empty Workspace Folder](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/48535920/000b2ea6-91ac-49d2-8637-8da35bcf4573)
