### ISSUE TITLE
For Linux Version

### ISSUE THREAD

**Issue by CGTDev53** [notepad-plus-plus/notepad-plus-plus#1364]
Notepad-plus-plus is not available for Linux OS.

**Comment by Croydon** [comment]
Please use the search.
Duplicate of #108 and #332. Related to #662

**Comment by linquize** [comment]
You have to use wine if you need to use notepad++ on Linux.

**Comment by GitMensch** [comment]
Please close as duplicate (making it easier to find the "real" one).
