### ISSUE TITLE
Error uninstalling v8.5.2 on Win11 21H2 under system context

### ISSUE THREAD

**Issue by itnewsteam** [notepad-plus-plus/notepad-plus-plus#13649]
![Screenshot_1](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/34739867/668849f4-1ae3-4d4d-8ecc-41389ac56452)

### Description of the Issue
During removing of the application in silent mode under the system context.

### Steps to Reproduce the Issue

1. Open cmd under the system context.
2. Run c:\Program Files (x86)\Notepad++\uninstall.exe /S.

Could you please take a look at this issue?

Thank you in advance.

**Comment by itnewsteam** [comment]
Due to the software  during uninstallation (uninstall.exe) creates subprocess Un_A.exe, some next command in the code (clean up) were performed earlier than they should be executed. It happens because the main uninstall.exe is stopped once when Un_A.exe is started. As a result it is required to create additional logic for waiting till Un_A.exe will be closed and only then continue further actions. To be honest it is not convenient.

![Screenshot_2](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/34739867/fe7dab05-0448-4aa0-af11-d1012d3611b3)

**Comment by itnewsteam** [comment]
Is it possible to change a little bit a logic and force "uninstall.exe" to wait till Un_A.exe will be finished and only then close the main  process (uninstall.exe)?

**Comment by donho** [comment]
Fixed in v5.8.3
https://notepad-plus-plus.org/downloads/v8.5.3/
