### ISSUE TITLE
Fold All/Unfold All (ALT+0/ ALT+SHIFT+0) not working enymore in new version

### ISSUE THREAD

**Issue by CoverUp** [notepad-plus-plus/notepad-plus-plus#13650]
### Description of the Issue
Fold All/Unfold All (ALT+0/ ALT+SHIFT+0) not working anymore in new version

### Steps to Reproduce the Issue
1.  Open Notepad++
2.  Paste sample code in a new document and save it as sample.php:
```
<?php
//sample code
function hello(){
//this should be folded
echo "Hello";
//but dont anymore in new version
}
echo "world";
?>
```

4.  Press ALT+0 to fold everything

### Expected Behavior
All line of code should be folded, even to <?php tag, and all the functions inside too

### Actual Behavior
Not folded at all/ not working, nothing happens

This issue only happen with the shortcut alt+0 and alt+shift+0, If you choose the option from the menu it works as expected
View>Fold All
the issue is only with the shortcut keys

### Debug Information
Notepad++ v8.5.2   (64-bit)
Build time : Apr  4 2023 - 19:55:32
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : "C:\Program Files\Notepad++\change.log" 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 7 Ultimate (64-bit)
OS Build : 7601.24544
Current ANSI codepage : 1252
Plugins : 
    ComparePlugin (2.0.2)
    mimeTools (2.9)
    NppConverter (4.5)
    NppExport (0.4)

**Comment by victorel-petrovich** [comment]
Can't reproduce on either portable (copied below) or installer, latest version, 8.5.4
Notepad++ v8.5.4   (32-bit)
Build time : Jun 17 2023 - 20:40:14
Path : C:\Users\Vic\Downloads\editors\npp.8.5.4.portable\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : ON
Cloud Config : OFF
OS Name : Windows 7 Ultimate (32-bit)
OS Build : 7601.24546
Current ANSI codepage : 1252
Plugins : 
    mimeTools (2.9)
    NppConverter (4.5)
    NppExec (0.8.4)
    NppExport (0.4)
    PythonScript (2)

**Comment by CoverUp** [comment]
I confirm that the issue is no longer present in the lastest build

Notepad++ v8.5.4   (64-bit)
Build time : Jun 17 2023 - 20:42:45
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : "C:\Program Files\Notepad++\change.log" 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 7 Ultimate (64-bit)
OS Build : 7601.24544
Current ANSI codepage : 1252
Plugins : 
    ComparePlugin (2.0.2)
    mimeTools (2.9)
    NppConverter (4.5)
    NppExport (0.4)

Notepad++ v8.5.4 bug-fixes and new features:

 1. Fix macro recording regression on Unicode character.
 2. Fix regression of defective detection for file read-only attribute removal via Explorer.
 3. Fix opening multi-files on multi-instance mode regression.
 4. Update: Scintilla 5.3.5 Lexilla 5.2.5
 5. Fix Notepad++ hanging issue running macro to EOF.
 6. Fix EOL symbol color/appearence being reset issue while changing encoding.
 7. Enable code folding in Assembly source files.
 8. Fix document language not remembered through sessions issue.
 9. Add SHA-1 hash features.
10. Add "open new blank document in addition on startup" ability.
11. Fix lexer plugin is sorted unconventionally in language menu issue.
12. Add message NPPM_DARKMODESUBCLASSANDTHEME to allow plugin to use generic dark mode.
13. Add the ability to close multiple files without saving in Document list.
14. Several GUI Enhancements.
15. Fix tabContextMenu_example.xml not being deleted while uninstallation.
16. Fix error message on uninstallation.
