### ISSUE TITLE
[v8.5.3] `Apply to C0, C1 Unicode EOL` is cut off in some localizations

### ISSUE THREAD

**Issue by rddim** [notepad-plus-plus/notepad-plus-plus#13657]
### Description of the Issue

With https://github.com/notepad-plus-plus/notepad-plus-plus/commit/0cad36d636aaa517f8fd50bdc171f6fa01181a38 some languages need more room for their localization of the `<Item id="6258" name="Apply to C0, C1 &amp; Unicode EOL"/>` string.
### Steps to Reproduce the Issue

1. Go to `Settings` > `Preferences...` > `General` and change the localization to Bulgarian (Български), Brazilian Portuguese (Português brasileiro), Corsican (Corsu), Dutch (Nederlands), Galician (Galego), Italian (Italiano) or Portuguese (Português)
2. Go to `Editing` in the same window
3. See the localization for `Apply to C0, C1 Unicode EOL` is cut off

### Expected Behavior

I have expected to have more room for completely visible localization
### Actual Behavior

The localization of `Apply to C0, C1 Unicode EOL` is cut off
### Debug Information

```
Notepad++ v8.5.3   (64-bit)
Build time : May 15 2023 - 06:09:36
Path : G:\_System\Users\Home\Downloads\npp.8.5.3.portable.x64\notepad++.exe
Command Line : 
Admin mode : ON
Local Conf mode : ON
Cloud Config : OFF
OS Name : Windows 7 Professional (64-bit)
OS Build : 7601.0
Current ANSI codepage : 1251
Plugins : 
    mimeTools (2.9)
    NppConverter (4.5)
    NppExport (0.4)
```

### Other info
Reported [here](https://github.com/notepad-plus-plus/notepad-plus-plus/commit/0cad36d636aaa517f8fd50bdc171f6fa01181a38#r108675058) and [here](https://community.notepad-plus-plus.org/topic/24448/notepad-v8-5-3-release-candidate/4?_=1684177548787) (point 3)

![](https://user-images.githubusercontent.com/8998791/231561436-cc02cb21-7c94-40eb-b38a-8ecc0dac1538.png)

**Comment by Yaron10** [comment]
@rddim,

@ozone10 has addressed this in https://github.com/notepad-plus-plus/notepad-plus-plus/pull/13632.
Could you test it please?

**Comment by rddim** [comment]
Thank you @Yaron10, I've missed this PR. It fix this issue.

**Comment by Yaron10** [comment]
@rddim,

I'm glad it fixes the issue.
The thanks and flowers to @ozone10.
