### ISSUE TITLE
Editor crashes when updating a changed file

### ISSUE THREAD

**Issue by old-fool** [notepad-plus-plus/notepad-plus-plus#1368]
Notepad++ v6.8.9 crashes on Windows 10 when it attempts to update a file that is open in the editor and has been externally rewritten by another program. Installed plugins are:
Compare 1.5.6.1
Converter 3.0
MIME Tools 1.9
NppExec 0.5.3
NppExport 0.2.8
NppFTP 0.26.3
Plugin Manager 1.3.5
Spell-Checker 1.3.3

**Comment by ClaudiaFrank** [comment]
Tried to replicate reported behaviour but didn't crash. So I assume there must be a explicit way how this
happens.
My steps
1) Create a test.txt in C:\users\admin\documents with MS Editor.
2) put some content in and save it
3) start npp and open test.txt
4) modify file in MS Editor and save it
5) click on npp -> received popup saying file has been updated... -> click yes
6) content updated in npp
7) changed content in npp and save it
-> no crash
My config
Notepad++ v6.8.9
Build time : Jan 12 2016 - 00:00:51
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : ON
Local Conf mode : OFF
OS : Windows 10
Plugins : ComparePlugin.dll mimeTools.dll NppConverter.dll NppExec.dll NppExport.dll NppFTP.dll PluginManager.dll PythonScript.dll SpellChecker.dll

**Comment by donho** [comment]
@old-fool Can you reproduce the crash steadily?

**Comment by old-fool** [comment]
I have a Perl program which I run external to the editor.  This program rewrites 2 text files which I have open in the editor.

The previous version of Notepad++ would pop up a window asking if I wanted to reload the files which it did without error.

If I run the Perl program from the editor via NppExec then it works perfectly.

However if I run the same Perl program from a DOS prompt then the following window pops up.

I can reproduce this each time.

**Comment by donho** [comment]
@old-fool Thank you for your help - I can reproduce the crash as well now.
Due to this critical regression, Notepad++ 6.8.9 release has been removed from the website:
https://notepad-plus-plus.org/news/v6.8.9-has-been-removed.html
