### ISSUE TITLE
[Feature Request] Add ".yaml" to the YAML extension list

### ISSUE THREAD

**Issue by Mertsch** [notepad-plus-plus/notepad-plus-plus#13695]
### Description of the Issue
Currently it's only ".yml"

---
![2023-05-24 10-44-05](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/9402861/22d3478e-3f4d-4190-b54e-96bbd2f83c51)
---

Official FAQ states
```
    Is there an official extension for YAML files?

    Please use ".yaml" when possible.
```
https://yaml.org/faq.html

**Comment by vinsworldcom** [comment]
Works for me with fresh portable 64-bit of 8.5.3:

Notepad++ v8.5.3   (64-bit)
Build time : May 15 2023 - 06:09:36
Path : C:\Users\mvincent\Downloads\npp\notepad++.exe
Command Line : -multiInst
Admin mode : OFF
Local Conf mode : ON
Cloud Config : OFF
OS Name : Windows 10 Enterprise (64-bit)
OS Version : 21H2
OS Build : 19044.2965
Current ANSI codepage : 1252
Plugins : 
    mimeTools (2.9)
    NppConverter (4.5)
    NppExport (0.4)


![image](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/9657169/6eff647d-e858-42f7-b740-62d5f24aacdc)


Cheers.

**Comment by schnurlos** [comment]
That seems to be part of the lexer package

**Comment by ArkadiuszMichalski** [comment]
It's added:
https://github.com/notepad-plus-plus/notepad-plus-plus/blob/master/PowerEditor/src/langs.model.xml#L420

Probably you have old `langs.xml` file.

**Comment by Mertsch** [comment]
@ArkadiuszMichalski You are right ... I deleted `\AppData\Roaming\Notepad++\langs.xml` and the newly created version contains the yaml extension. Thanks!
