### ISSUE TITLE
Illegal replacement to double-byte space in macro

### ISSUE THREAD

**Issue by project-flower** [notepad-plus-plus/notepad-plus-plus#13698]
### Description of the Issue

The replacement is not correct when run a macro that replaces with double-byte spaces.

### Steps to Reproduce the Issue

1. Click "Macro" in Menubar > "Start Recording".
2. Press Ctrl+H to Open Replace Window.
3. Set some text in "Find what".
4. Set double-byte space in "Replace with".
5. Click "Replace All".
6. Click "Macro" > "Stop Recording".
7. Click "Macro" > "Save Current Recorded Macro" and save the macro.
8. Run the macro.

### Expected Behavior

Text must be replaced with full-width spaces.

### Actual Behavior

The text is replaced with the text "`&#x3000;`".

### Debug Information

Notepad++ v8.5.3   (64-bit)
Build time : May 15 2023 - 06:09:36
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 10 Pro (64-bit)
OS Version : 22H2
OS Build : 19045.2965
Current ANSI codepage : 932
Plugins : 
    mimeTools (2.9)
    NppConverter (4.5)
    NppExport (0.4)

### Misc.
It was working fine in version 8.5.2.

**Comment by alankilborn** [comment]
I would assume that by "double-byte space" you mean [U+3000](https://www.fileformat.info/info/unicode/char/3000/index.htm).

You should read [HERE](https://community.notepad-plus-plus.org/topic/24464/faq-desk-v8-5-3-macros-and-run-menu-commands) and [HERE](https://community.notepad-plus-plus.org/topic/24477/help-having-trouble-with-macros-in-v8-5-3-or-later).

**Comment by project-flower** [comment]
@alankilborn 
Thanks, indeed macros created with Ver.8.5.3 seem to work fine.
I didn't expect such a big change in an update of this small number.
