### ISSUE TITLE
Irritating alert appearing on close of program.

### ISSUE THREAD

**Issue by plane007** [notepad-plus-plus/notepad-plus-plus#13694]
### Description of the Issue
The change log was picked up every time the program was opened until I removed the  file. The image below is a view I see every time I close the program now, whether or not I have used a session. 

### Steps to Reproduce the Issue
Just close the program.

### Expected Behavior
No appearance of this alert. 

### Actual Behavior
The alert just appears, however I close the program.

### Debug Information
Notepad++ v8.5.3   (64-bit)
Build time : May 15 2023 - 06:09:36
Path : E:\Program Files\Notepad++\notepad++.exe
Command Line : "C:\Users\Admin\AppData\Local\Temp\BvSshSftp-AT08X42C\5XWRAW5V\1BGX93WY\ossn.lib.initialize.php"
Admin mode : OFF
Local Conf mode : ON
Cloud Config : OFF
OS Name : Windows 10 Pro (64-bit)
OS Version : 22H2
OS Build : 19045.2965
Current ANSI codepage : 1252
Plugins : 
    mimeTools (2.9)
    NppConverter (4.5)
    NppExport (0.4)

![2023-05-24_08-51-35](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/321005/b520c534-5fe0-4b13-ab12-a43a7854650c)

**Comment by donho** [comment]
@plane007 
Could you replace your notepad++.exe with the binary of #13741, relaunch it and reproduce the alert message. 
After closing Notepad++, provide your **session.xml.fail2Load** here please?

**Comment by donho** [comment]
@plane007 
Please let me know when you're available for testing.
