### ISSUE TITLE
Misaligned search results in Find All when over 1 million lines.

### ISSUE THREAD

**Issue by Jvella94** [notepad-plus-plus/notepad-plus-plus#13692]
### Description of the Issue

When doing a find in current document with a document over a million lines, the line numbers are not padded equally. This results in having an alt+drag select become misaligned if you're trying to copy from sepcific columns in each search result.

### Steps to Reproduce the Issue

1. Create a file with just over a million lines
2. Each base 10 amount (10,100,1000 etc) have a specific word to be found in those lines.
3. Search for that word in  Find and do Find All in Current Document
4. In the search results, there will be the lines with a value of 1 million or more padded differently to the others.

### Expected Behavior

All lines padded to account for highest found line number.

### Actual Behavior

Only up to 1 million is handled correctly with padding.

### Debug Information

Notepad++ v8.4.7   (32-bit)
Build time : Nov  1 2022 - 23:29:20
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Command Line : "C:\Users\user\Desktop\bigLog.log"
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows Server 2016 Datacenter (64-bit) 
OS Version : 1607
OS Build : 14393.5501
Current ANSI codepage : 1252
Plugins : 
    mimeTools (2.9)
    NppConverter (4.5)
    NppExport (0.4)

![image](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/20588370/96718ece-c5ba-4113-aa89-e2bafaf1e125)

**Comment by alankilborn** [comment]
Already fixed; see v8.5.3.
Please close.

**Comment by alankilborn** [comment]
For those that want to try it, search the attached file in regex mode for `0999997|1000003`

**Comment by alankilborn** [comment]
[million_line_file.zip](https://github.com/notepad-plus-plus/notepad-plus-plus/files/11564232/million_line_file.zip)
