### ISSUE TITLE
The update dialog should be blocking

### ISSUE THREAD

**Issue by milipili** [notepad-plus-plus/notepad-plus-plus#137]
When asking if n++ is up-to-date, a dialog is created "No update is available". However, the form is not blocking and it is possible to try it several times, or to do something else, and to launch several wingup.
![npp-multiple-update-dialog](https://cloud.githubusercontent.com/assets/5516919/7894077/2119936c-0665-11e5-8c4e-ab975ab9cfa7.png)

**Comment by MetaChuh** [comment]
assigned, but closed due to:
* inactivity (4y)
* inactivity since assignment (2y)
* minor relevance for the majority of users
* workaround: don't press on `update notepad++` more than once 😉

please reopen if wanted

greetings
