### ISSUE TITLE
Add copy link to right click

### ISSUE THREAD

**Issue by mendya** [notepad-plus-plus/notepad-plus-plus#1370]
It would be nice to have a "copy link" when you right click on a link.
There is already a finger pointer and the link becomes highlighted and if you double click the link opens up.
But I'd like to be able to copy the whole link with one click.

**Comment by MetaChuh** [comment]
this will depend on the scintilla component.
unfortunately scintilla is an external project, so you will have to file your issue at the [<kbd>scintilla feature-requests tracker</kbd>](https://sourceforge.net/p/scintilla/feature-requests/).
we apologise for that.

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
(no extra account is needed, just use your github account to sign in)
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)
