### ISSUE TITLE
[GUI] Style configurator dlg font

### ISSUE THREAD

**Issue by ozone10** [notepad-plus-plus/notepad-plus-plus#13705]
### Description of the Issue

Some style configurator controls are using `DEFAULT_GUI_FONT` which is not recommended and may cause issue in hiDPI.
### Expected Behavior

Not using `DEFAULT_GUI_FONT` font.
### Actual Behavior

Using `DEFAULT_GUI_FONT` font.
### Debug Information

Notepad++ v8.5.3

**Comment by donho** [comment]
@ozone10 
If DEFAULT_GUI_FONT is not recommended and may cause issue in hiDPI, why don't we remove it from:
https://github.com/notepad-plus-plus/notepad-plus-plus/blob/master/PowerEditor/src/Parameters.cpp#L1866
and from:
https://github.com/notepad-plus-plus/notepad-plus-plus/blob/master/PowerEditor/src/Parameters.cpp#L1874
?

**Comment by ozone10** [comment]
@donho 
https://github.com/notepad-plus-plus/notepad-plus-plus/blob/master/PowerEditor/src/Parameters.cpp#L1874
is fallback in case `SystemParametersInfo` fails, but should never happen.

I've added commit in PR to remove former.
