### ISSUE TITLE
Feature request: Insert symbol dialog

### ISSUE THREAD

**Issue by sharkbyte16** [notepad-plus-plus/notepad-plus-plus#13708]
The Character Panel provides easy access to the 256 ASCII characters. However, to input any other character or symbol (non-Latin, math etc.) one has to open the Windows Character Map and copy/paste the symbol. It would be great to integrate an Insert Symbol dialog to directly insert symbol similar to the dialog in Microsoft Office.

**Comment by alankilborn** [comment]
IMO, not a lot of value in expending effort to do this.

Helper:
Create a _Run_ menu entry, and use character map from there, e.g.:
![image](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/77065706/e5d20bff-4379-416d-910c-4f506786db0c)

**Comment by donho** [comment]
For me, what @alankilborn suggested is the solution.
