### ISSUE TITLE
macro EOL characters inserted don't match those in the macro source (v8.5.3)

### ISSUE THREAD

**Issue by pryrt** [notepad-plus-plus/notepad-plus-plus#13717]
### Description of the Issue

When a macro is recorded that inserts a CR and LF, the CR is encoded in the `shortcuts.xml` as a CR, but the LF is encoded in the `shortcuts.xml` as a CRLF.  The means that the converse is true, as well: if you manually edit a macro in `shortcuts.xml` and try to use a [SCI_REPLACESEL](https://scintilla.org/ScintillaDoc.html#SCI_REPLACESEL) to insert CRLF by hitting ENTER in the sParam attribute value (to get the `CR` and `LF` characters), when the macro is played back, it will only insert the `LF` character.

[original discussion](https://community.notepad-plus-plus.org/topic/24477/help-having-trouble-with-macros-in-v8-5-3-or-later/18) => [v8.5.3 announcement follow-on](https://community.notepad-plus-plus.org/post/86565) => my original example:

> For example, a user is hand editing their macro, and they know from Scintilla.iface that 2170 is "ReplaceSel" which maps to [SCI_REPLACESEL](https://scintilla.org/ScintillaDoc.html#SCI_REPLACESEL), and they know from the Scintilla documentation that [SCI_REPLACESEL](https://scintilla.org/ScintillaDoc.html#SCI_REPLACESEL) allows any string, not just a string containing a single character.  So then while hand-editing, they put in "A new line.`[CR][LF]`A second line.`[CR][LF]`" and save their macro file, and restart.  
> ![image](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/17455758/a7f4d7cc-a2b5-41c8-8ec5-b3829c0a65bb)
>They now run this macro, and the macro inserts a single `[LF]`, _not_ the `[CR][LF]` that they intended.
> ![image](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/17455758/bd179644-8d3a-4b9a-b8ae-ea0efbb53aea)

This was described in the announcement thread as a regression caused by the updates to the Run and Macro internals, but Don requested that this get a separate issue, since it may not be immediately fixable.

### Steps to Reproduce the Issue

1. Hand edit `shortcuts.xml` as shown below (all newlines are `[CR][LF]`)
   ```xml
   <Macro name="Two Line Macro" Ctrl="no" Alt="no" Shift="no" Key="0">
      <Action type="1" message="2170" wParam="0" lParam="0" sParam=A new line.
   A second line.
   " />
   </Macro>
   ```
2. save/exit/restart
3. run **Macros > Two Line Macro**
4. **View > Show Symbols > Show All Characters**
5. It only inserts `[LF]`, not `[CR][LF]` as was intended by the macro source code: 
   ![image](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/17455758/bd179644-8d3a-4b9a-b8ae-ea0efbb53aea)

### Expected Behavior

It should insert `[CR][LF]` when it runs across `[CR][LF]` in 

### Actual Behavior

It only inserts `[LF]`, not `[CR][LF]`

### Debug Information

Notepad++ v8.5.3   (64-bit)
Build time : May 15 2023 - 06:09:36
Path : C:\usr\local\apps\npp\npp.8.5.3.portable.x64\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : ON
Cloud Config : OFF
OS Name : Windows 10 Enterprise (64-bit)
OS Version : 22H2
OS Build : 19045.2965
Current ANSI codepage : 1252
Plugins : 
    mimeTools (2.9)
    NppConverter (4.5)
    NppExport (0.4)

**Comment by Tragen** [comment]
How do you insert a CRLF in XML?
To insert a CR into XML, you need to use its character entity &#13; . This is because compliant XML parsers must, before parsing, translate CRLF and any CR not followed by a LF to a single LF. This behavior is defined in the End-of-Line handling section of the XML 1.0 specification.
So everything you read from an XML will return only LF until you manually encode CR LF with &#13  / &#xD and &#10

**Comment by pryrt** [comment]
> So before saving you could encode CR and LF and this should solve the problem.

That's the way it worked before Notepad++ v8.5.3.  In v8.5.3, Notepad++ got rid of the ability to use entities in that configuration file (`shortcuts.xml` -- and you can look through the history of that change to see the reasons; I won't rehash them here).  But in the current implementation, if Notepad++ sees `&#13;&#10;` (or other equivalent entity-based sequences) in any of the text attributes, it will treat them as literal characters (ampersand, hash, one, three, semicolon, ampersand, hash, one, zero, semicolon).  If it hadn't been for the removal of entity-parsing from v8.5.3, I would have never had to submit this bug report.

**Comment by pryrt** [comment]
The changes were because of #12670, #13221, and #13488 ... but the discussion of the no-entity was in #13589

**Comment by Tragen** [comment]
I still try to understand it but it looks like because N++ uses and old and outdated XML parser which has bugs.

**Comment by molsonkiko** [comment]
One thing that might make sense would be for there to be some optional boolean attribute for macros (default false, maybe named `xmlEscaped`?) that determines whether XML-escapes are treated as literal strings or XML escapes.
For example,
```
<Action type="1" message="2170" wParam="0" lParam="0" sParam="&#8349;" xmlEscaped="1"/>
```
would be interpreted as the same as
```
<Action type="1" message="2170" wParam="0" lParam="0" sParam="草"/>
```
By default, the xmlEscaped attribute would only be set to true for strings containing absolutely illegal characters (e.g., `<`, `>`) and questionably legal characters (e.g., `\r`, `\n`).

In addition to making macros containing newlines more intelligible, this would help when sharing macros containing non-printing characters. For example, in my [recent PR](https://github.com/notepad-plus-plus/notepad-plus-plus/pull/13780), I created a macro that others could run to test my PR, rather than having to follow a series of steps manually. However, because the macro included nonprinting characters, I couldn't share the macro via GitHub. My proposal above would alleviate that issue.

**Comment by git4source** [comment]
I am not using any special characters, the macro has added the following (all characters after the last =):
=====================================================================================================================&#x000D;&#x000A;

**Comment by pryrt** [comment]
> I am not using any special characters, the macro has added the following : `&#x000D;&#x000A;`

That is the newline sequence (CRLF) in the _old style_ macros, which means you presumably hit ENTER as part of the recorded macro.  To make those work in the v8.5.3-and-newer, you need to use `&#x0D;&#x0A;` instead.  See [this FAQ](https://community.notepad-plus-plus.org/topic/24464/faq-v8-5-3-and-newer-macros-and-run-menu-commands) from the [Notepad++ Community Forum](https://community.notepad-plus-plus.org/).

**Comment by pryrt** [comment]
But since this "ping" on the issue reminded me, I had previously said,

> But in the current implementation, if Notepad++ sees `&#13;&#10;` (or other equivalent entity-based sequences) in any of the text attributes, it will treat them as literal characters (ampersand, hash, one, three, semicolon, ampersand, hash, one, zero, semicolon). If it hadn't been for the removal of entity-parsing from v8.5.3, I would have never had to submit this bug report.

As was later corrected in the FAQ, the `&#x0D;&#x0A;` sequence _will_ work in v8.5.3-and-newer, because it's using the two-digit hex notation for the entities (three-or-more-digit hex entities, or any-digit decimal entities will not).

But since there _is_ a way to encode the newline sequence, and since XML isn't supposed to have unencoded newlines in attribute values anyway, I am closing this issue.
