### ISSUE TITLE
Notepad++ Icon missing from Taskbar when opening from shell with "edit with notepad++"

### ISSUE THREAD

**Issue by dani0104** [notepad-plus-plus/notepad-plus-plus#13718]
I mean the title says it all, icon is perfectly fine when opening normally, but when opening with shell extension it is missing from taskbar

### Steps to Reproduce the Issue

1.  Select Any File right clicking it
2.  click "Edit with Notepad++"
3. observe the taskbar and see that the notepad++ icon is missing, 

when opening any other way the icon is there.

### Debug Information
Notepad++ v8.5.1   (64-bit)
Build time : Mar 21 2023 - 19:16:10
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 11 Pro (64-bit)
OS Version : 22H2
OS Build : 22621.1778
Current ANSI codepage : 1252
Plugins : 
    mimeTools (2.9)
    NppConverter (4.5)
    NppExport (0.4)

When opening normally: https://snipboard.io/sTJuDz.jpg
When opening with shell extension (context menu) it is missing: https://snipboard.io/wNGzBE.jpg

**Comment by donho** [comment]
@dani0104 
This issue has been fixed in v8.5.3
