### ISSUE TITLE
[Feature Request] Adding the last directory name to each tab

### ISSUE THREAD

**Issue by Saul510** [notepad-plus-plus/notepad-plus-plus#13715]
I've been an avid Notepad++ user for over 10 years now and what's always been confusing and bugging me since day one is that the tabs only contain the filename.

This results to confusion if you have multiple files open that have the same filename (see photo):
![tabs](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/82345560/4de13b4b-8dfd-4876-8dc4-8deffc66f855)

Would it be possible to have a setting added that, once enabled, would show the last directory path along with the filename as this would solve the majority of the issues as you can not have multiple files with the same name in the same directory.
So for example if the path were to be _**/home/user/public_html/index.php**_ the tab name would then be _**public_html/index.php**_

This would be immensely helpful and would probably save me in total a few hours per month as I won't have to jump between the filenames to find the file that I'm looking for.

In exchange for my time saved and for the effort of adding this, I would be more than happy to donate $200 to have this added (perhaps it can be seen as some sort of a bounty?) and all I need is the PayPal address of the developer (or developers if this would be split between multiple developers).

**Comment by molsonkiko** [comment]
FWIW, the plugin [NavigateTo](https://github.com/young-developer/nppNavigateTo) makes it pretty easy to tell what the directories are for two files with the same name.
I agree with you that this would be a useful feature, and I'll see about putting together a PR.
![image](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/46202915/2bab1165-3b47-416a-aaa1-a478643d5849)

**Comment by Saul510** [comment]
@molsonkiko thanks for the reply and I've actually already installed this before and the problem with this is that it uses too much space and you have to give it 20% of the width of the screen which is very valuable in order to see the ending of the path.  You could of course move all the files as close to root as possible to help with this, but still it'll take up a lot of space.

You would be an absolute savior if you put in a pull request and this gets added.
Please write your paypal address or crypto address and I'll send you the payment as promised when this is added.

**Comment by molsonkiko** [comment]
Agree that having NavigateTo as a docking form is very suboptimal. The good
news is that you can make it a free-floating form and alleviate the issues
you described by dragging it away from the Notepad++ window with your
mouse. If you do this, Notepad++ remembers this display decision on future
sessions.

I am interested in submitting a PR, but IDK if I will be able to make a
fully satisfactory solution in any case.

**Comment by Saul510** [comment]
@molsonkiko I wasn't aware of that and that does indeed make it a lot more useful as you could place it on another screen, but still you need to sacrifice screen space for something that you normally shouldn't need to do with this small change in the tab names.  
  
I am rooting for you and I truly hope you accomplish this - again please return with your payment addresses if you do succeed with this as I'm keeping my word on the reward.

**Comment by alankilborn** [comment]
I was unaware that such a feature can be enabled in VSCode.  This will show how to do that, for those that have VSCode and would like to preview how it might work someday in N++:  https://stackoverflow.com/questions/39598007/showing-path-in-file-tabs-in-visual-studio-code

**Comment by Saul510** [comment]
@alankilborn Yes, I've been using this for a while now, but I genuinely miss N++ despite the tremendous amount of extensions that VSC has.

**Comment by molsonkiko** [comment]
Just an update on what I've done so far. It's not ready for the prime time, because of some things that I need to fix/add/consider:
1. Doesn't yet have a configurable setting for the user
2. Doesn't correctly rename the tab bar when a buffer is renamed (open/close seems fine)
3. Has the potential to be incredibly slow when closing a file that has the same name as many other files (because removal of the `(n + 1)th` file triggers pairwise comparison of the remaining `n` files, for a total of `n*(n - 1)/2 =~ n^2/2` comparisons

![image](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/46202915/a8365bfc-2a9b-4e03-bbe3-ccaf22f0cf02)

**Comment by Saul510** [comment]
@molsonkiko wow, that's nice and just seeing directory names in the tabs is refreshing, even though it's not working correctly yet.
As for the disambiguation, I think this is overkill and could perhaps be confusing too at times and the best way is to just do it like the option in VSCode which is that it just shows the parent directory or the full path if you choose the long option [(VSC)](https://github.com/microsoft/vscode/issues/12965#issuecomment-328494134)

I think that that would be the best solution and in most cases the parent directory differs when the filename is identical.

Keep up the great work also!

**Comment by donho** [comment]
https://github.com/notepad-plus-plus/notepad-plus-plus/pull/13854#issuecomment-1619171120
