### ISSUE TITLE
Changing EOL with very long UTF-8 files

### ISSUE THREAD

**Issue by BBW1** [notepad-plus-plus/notepad-plus-plus#1371]
Hi,

I create very long UTF-8 encoded text files with Python (anywhere from hundreds of thousands to millions of rows) and when I open the files in Notepad ++, it assigns the WIN EOL. When I change the EOL to Unix, Notepad ++ compromises some of the UTF-8 characters, inserting black-filled squares with white in the beginning and middle of my words sporadically throughout the file. This has happened to me with Russian (Cyrillic), Croatian (Latin with special characters) and Slovene (Latin with special characters). 

The same error has happened to me sometimes when editing the file in Notepad++ and searching and replacing throughout the file. The time/actions that cause the characters to be inserted in that scenario seem more random.

Because of this, I consider Notepad++ unreliable for editing UTF-8 encoded files. But I would love to be able to use it as I love the functionalities in other situations. 

Please let me know if you have any questions. Thanks in advance.

**Comment by ClaudiaFrank** [comment]
This surprises me, normally utf-8 is the default encoding npp uses.
I tried to replicate your issue by creating a utf-8 file on my linux machine. Checked by using file -bi.
a) if loaded by npp eol doesn't get replaced automatically
b) if I changed to windows eol everything was still ok.

So I assume, either one, of possibly installed, plugin or the big number of lines is causing this.
Is there a way for you to make some test to see when this happens e.g. a file loaded with 10 lines
100, 1000 and so on?

**Comment by sanastasiou** [comment]
@BBW1 the buffers get's corrupted. I have seen this behavior as well. Seems sporadic.. If u have such a file and can reproduce this you should upload it somewhere so the dev's can have a better look at it.

**Comment by dail8859** [comment]
@BBW1 If you have backups enabled try turning that off to see if it helps.

**Comment by BBW1** [comment]
I am using a Windows environment. I too found the behavior sporadic @sanastasiou, I have been experiencing it for months, but yesterday I was able to reproduce it consistently for the first time and so I thought I would enter this ticket. 

Here's a specific example of what happened: In today's exercise/test, I copied and pasted the content into a WIN-EOL file, saved it, then tried to change the EOL to Unix style. No error messages but when I scroll through the text I found the NUL character pictured below (I am including a before and an after screenshot) 
![image](https://cloud.githubusercontent.com/assets/16708641/12355115/8077dd88-bb68-11e5-9ac6-9d6dbc72ca0b.png)

![image](https://cloud.githubusercontent.com/assets/16708641/12354981/a7fd5a1e-bb67-11e5-87e7-95daded5fb97.png)

When I change back to WIN format for the EOL, the NUL remains. If I try to undo, the NUL remains.

@dail8859, I have not changed the default behavior which seems to be auto backups every 7 seconds. I turned it off and tried my exercise and didn't get the NUL. I changed it back to the default, closed the file without saving and then when I opened it again and tried the EOL conversion, I got this error message:

![image](https://cloud.githubusercontent.com/assets/16708641/12355164/eb156d68-bb68-11e5-8f83-a1fa8bb74041.png)

I think this part must have something to do with the size of the file, as I must be unwittingly issuing commands before it's done processing the last command.

@ClaudiaFrank I never experienced it with smaller files, only when they got to be several hundred thousand lines and only when non-English characters were in the text (i.e. Cyrillic and Latin characters with diacritics: č, š, and similar).

I will continue testing and will update if I can document anything else new/relevant.

**Comment by sanastasiou** [comment]
Please zip the file and upload it somewhere where it can be used for testing!

**Comment by dail8859** [comment]
My experience with editing large files and having the backups enabled has never turned out well for me.

**Comment by krilbe** [comment]
I can confirm that files get corrupted by EOL conversion if backups are enabled. This is not the only operations that has problems with backups.

I'd suggest that the backups feature be **removed** until it has been rewritten in a more reliable way.
