### ISSUE TITLE
Update prompt opens on a different monitor

### ISSUE THREAD

**Issue by PhilipEve** [notepad-plus-plus/notepad-plus-plus#13720]
When Notepad++ opens, if there is an update available, it opens a dialog to prompt the user to update. This dialog is modal to the main notepad++ window but it may open on a different monitor. If the user does not look at the monitor that has the update prompt window on it, then they will be puzzled as to why Notepad++ appears to have hung.

Modern Windows doesn't signal the "you are trying to interact with this window, but there is another window modal to it" situation very well, particularly when sounds are disabled, so this can be fairly confusing.

The update prompt should ideally open over the centre of the Notepad++ main window

**Comment by donho** [comment]
https://github.com/notepad-plus-plus/notepad-plus-plus/blob/master/CONTRIBUTING.md#reporting-issues
