### ISSUE TITLE
[Feature requests] Change on delete buttons in Shortcut Mapper window

### ISSUE THREAD

**Issue by Buggfix42** [notepad-plus-plus/notepad-plus-plus#13723]
### Feature request 1
On Settings > Shortcut Mapper > Scintilla commands you have to manually set a shortcut to none in the shortcut modification window.
The clear button is not clickable, but would make resetting shortcuts easier.

~~### Feature request 2
On *Settings > Shortcut Mapper > Macros* and *Settings > Shortcut Mapper > Run commands* you must press the DEL key to delete that entry, the actual delete button only resets the shortcut.
Why aren't there two buttons: "Delete entry" and "Delete shortcut"? Some users that assume that the DEL key does the same as the delete button will not know how to delete an entry.~~

### Debug information
v8.5.3

**Comment by CennoxX** [comment]
There are two context menu entries for both actions.

**Comment by alankilborn** [comment]
Unknown what version you mean because you didn't follow the template and specify.

FR1:

"Delete" in _Shortcut Mapper_ means to remove a line item; consequently it is only available for _Macros_ and _Run commands_.  "Clear" means to remove the shortcut assignment.

It is true that "Clear" is not available for Scintilla commands.

FR2:

For me in 8.5.3, Del key doesn't do anything.

**Comment by alankilborn** [comment]
> There are two context menu entries for both actions.

Yes but those entries are the same as the buttons that appear along the bottom of the _Shortcut Mapper_ window, so they don't add functionality.

**Comment by alankilborn** [comment]
Some time ago I created some _Shortcut Mapper_ issues that may be related/relevant:  #12034 #12036 #12039 #12040

**Comment by Buggfix42** [comment]
> There are two context menu entries for both actions.

Oh, my bad. But now i figured out what's wrong. It's a translation mistake in the german version of Notepad++.
In the german version there are two buttons: "delete" and "delete all" and the "delete all" button deletes the entry, not all shortcuts.

**Comment by donho** [comment]
> In the german version there are two buttons: "delete" and "delete all" and the "delete all" button deletes the entry, not all shortcuts.

So it's rather an issue of German translation?
If it is, please create a new issue with "German translation" in the title, so the translator will fix it in the next release.
