### ISSUE TITLE
I lost my theme

### ISSUE THREAD

**Issue by andreasdc** [notepad-plus-plus/notepad-plus-plus#13726]
I don't have my selected theme

**Comment by alankilborn** [comment]
With that level of (lack of) detail, no one here will be able to help you.
Try posting [HERE](https://community.notepad-plus-plus.org/) but be prepared to provide more detail on your problem.

**Comment by andreasdc** [comment]
I turned on notepad++ and I had default white theme.

**Comment by andreasdc** [comment]
Just like I lost my opened files last time.

**Comment by andreasdc** [comment]
Where is my theme?

**Comment by donho** [comment]
https://github.com/notepad-plus-plus/notepad-plus-plus/blob/master/CONTRIBUTING.md#reporting-issues

**Comment by andreasdc** [comment]
what?
