### ISSUE TITLE
[Feature request] Make menu bar elements hideable

### ISSUE THREAD

**Issue by Buggfix42** [notepad-plus-plus/notepad-plus-plus#13724]
Notepad++ is an editor, so why are there build-in functions like checksum generation and program running directly in the menu bar?
I personally prefer things to be clean and unused things to go out of view. It would be nice if there is an option to hide menu bar elements.

**Comment by alankilborn** [comment]
Fill out issue template.

Show screenshots of what you're talking about.

In other words, put some effort into your issue to be taken seriously.

**Comment by Buggfix42** [comment]
It's not an issue, it's a feature request as said in the title. And i think the title explains it. I want to hide/remove the *Tools* and *Run* entries in the menu bar to personalize Notepad++. Just as there is a contextMenu.xml file it would be great if there were a menuBar.xml where I can modify the menu bar.

**Comment by alankilborn** [comment]
>why are there build-in functions like checksum generation and program running directly in the menu bar?

This statement was confusing; I don't think I'm the only one confused by it.

>I want to hide/remove the Tools and Run entries in the menu bar to personalize Notepad++

I doubt developers would be interested in providing this functionality.  But you never know...  Good luck.

**Comment by donho** [comment]
> Notepad++ is an editor, so why are there build-in functions like checksum generation and program running directly in the menu bar? I personally prefer things to be clean and unused things to go out of view. It would be nice if there is an option to hide menu bar elements.

For items of some sub-menu, it's necessary and implemented. But globally hiding items is not easy to implemented, and it's better to not hide items because once it's hidden, the features are forgotten by users. OTOH, for the features you don't use, you can just ignore them.
For the above reasons, this feature won't be implemented.
