### ISSUE TITLE
character doesnt show/ or changes within highlighted brackets

### ISSUE THREAD

**Issue by charlieb000** [notepad-plus-plus/notepad-plus-plus#1372]
trivial bug if it changes within brackets.

put 슴 into the document (UCS2 BE encoded) and you should see a square.
put 合 before it and the above character will show.
put the first mentioned character within brackets after the above character and it will become a square if the brackets highlight.

V 6.8.5

**Comment by ClaudiaFrank** [comment]
if I put a 슴 I see a 슴 
tested on 6.8.9

**Comment by donho** [comment]
@charlieb000  The square problem of Chinese/Korean/Japanese is rather your system font issue, not a bug in Notepad++. Use Style Configurator to set font manually.
