### ISSUE TITLE
Minor style bug

### ISSUE THREAD

**Issue by Brig9902** [notepad-plus-plus/notepad-plus-plus#13728]
### Description of the Issue

I have EOL marks set to be visible, but I have assigned them a gray color rather than the obtrusive black. However, if I change the open file’s encoding - say from UTF-8 to ANSI - the color of the EOL marks becomes black. If I close the file and open it again, they go back to gray. A minor issue, but it’s new to the latest version.

### Steps to Reproduce the Issue

1. See above
2. 
3. 

### Expected Behavior

See above

### Actual Behavior

See above

### Debug Information

NA

**Comment by donho** [comment]
https://github.com/notepad-plus-plus/notepad-plus-plus/blob/master/CONTRIBUTING.md#reporting-issues

**Comment by ozone10** [comment]
@Brig9902 
next time properly fill issue template.
