### ISSUE TITLE
Double-clicking on a left or right border of a maximized Notepad++ window creates a new tab.

### ISSUE THREAD

**Issue by 68kPoker** [notepad-plus-plus/notepad-plus-plus#13733]
### Description of the Issue
The issue occurs when user double-clicks left or right border of the maximized window of the Notepad++. The new tab is created.

### Steps to Reproduce the Issue
1. Maximize Notepad++ window
2. Double-click on left or right border of the window
3. Notice the new tab is created

### Expected Behavior
There should be no reaction to double-clicking the window border.

### Actual Behavior
The new tab is created, like the user clicked on the tabs bar.

### Debug Information
Notepad++ v8.5.3   (64-bit)
Build time : May 15 2023 - 06:09:36
Path : C:\Users\rober\Desktop\Programy\Notepad++\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 11 Pro (64-bit)
OS Version : 22H2
OS Build : 22621.1702
Current ANSI codepage : 1250
Plugins : 
    mimeTools (2.9)
    NppConverter (4.5)
    NppExport (0.4)

**Comment by alankilborn** [comment]
Presumably this happens because it is effectively the same as double-clicking in the area to the right of existing tabs in the tab bar, i.e., in this area:

![image](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/77065706/7242b54b-ef89-436e-8700-98e6b86ec7d0)

and the design intent for that **IS** to create a new tab.

If you increase the _Border Width_, then this whole area:

![image](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/77065706/30c1f844-0ab6-4e73-8d05-cf3d17fbf1c7)

can be thought of as a "double-click to create new tab" area.

To me existing behavior is OK...one more quick way to create a new tab.  It's a feature, not a bug.

Why are you double-clicking the border anyway? (If, you state, you are expecting nothing to happen by so doing)

**Comment by 68kPoker** [comment]
> Why are you double-clicking the border anyway? (If, you state, you are expecting nothing to happen by so doing)

I double-click very often on the right side vertical scroller. And this produces the new tab, this behavior is unexpected.

**Comment by alankilborn** [comment]
When I try double-clicking on the right side vertical scrollbar, exactly nothing happens for me.  Plus, the discussion wasn't about that, it was about the border.

Are you saying that when you intend to double-click on the right side vertical scrollbar, for whatever purpose, you either see a new tab created, or you _miss_ the scrollbar and hit the border with the double-click, and then see a new tab created?

**Comment by 68kPoker** [comment]
> Are you saying that when you intend to double-click on the right side vertical scrollbar, for whatever purpose, you either see a new tab created, or you _miss_ the scrollbar and hit the border with the double-click, and then see a new tab created?

Yes, i miss the scrollbar and click on the right border when clicking.

**Comment by alankilborn** [comment]
So, again...why would you double-click on the scrollbar?

**Comment by 68kPoker** [comment]
I click on the scrollbar very frequently, thus sometimes the clicks have short interval, which produces double-clicks. When I move the mouse right to the scrollbar, it almost always positions on the right edge of the maximized Notepad++ window.
Please, correct this behavior of creating tab in this situation.
I noticed that it's connected to clicking of the left/right window borders just few days ago. I was always thinking it's related to scrollbar.

**Comment by alankilborn** [comment]
Suggest you set this setting to avoid the problem:

![image](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/77065706/d289504b-7e95-48da-b5b2-a27428008a49)

**Comment by 68kPoker** [comment]
Thank you, this eliminates the problem. 👍 

I close the issue, however consider making the Tab creation only by double-clicking the Tab-Bar only. I think it's reasonable.
