### ISSUE TITLE
consider showing non-printing characters even when "show all characters" is not on

### ISSUE THREAD

**Issue by molsonkiko** [notepad-plus-plus/notepad-plus-plus#13734]
### Description of the Issue

While I *really like* the new setting where I can see the Unicode codepoint of non-printing characters instead of their abbreviation, I'm not crazy about needing to turn on the `Show all characters` setting to see them. I preferred being able to clearly see where all the weird characters were at a glance without also needing to see the CR and LF.

It would be nice to be able to see those characters all the time (possibly with a configurable setting) the way it used to be.
### Steps to Reproduce the Issue

1. Create a new document
2. Hit `Ctrl-E` (assuming you have default keybindings, this will create the `ENQ` character, `\x05`)
3. It will be invisible until you hit the `Show All Characters` button in 8.5.3, but in earlier NPP versions those characters were always visible.

### Expected Behavior

As stated above, always make non-printing characters visible.
### Actual Behavior

See above
### Debug Information

```
Notepad++ v8.5.3   (64-bit)
Build time : May 15 2023 - 06:09:36
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 10 Home (64-bit)
OS Version : 22H2
OS Build : 19045.2965
Current ANSI codepage : 1252
Plugins : 
    ComparePlus (1.1)
    CSVLint (0.4.6.4)
    CsvQuery (0.1)
    Demo (0.7)
    DSpellCheck (1.5)
    EnhanceAnyLexer (1.1.3)
    HexEditor (0.9.12)
    HugeFiles (0.4.1)
    JsonTools (5.0.0.5)
    mimeTools (2.9)
    NavigateTo (2.4.3)
    NppConverter (4.5)
    NppExport (0.4)
    PythonScript (3.0.16)
    QuickText (0.2.5.1)
    XMLTools (3.1.1.13)
```

The below screenshot shows what happened when I hit Ctrl+E 7 times in Notepad++ 8.5.3 with `Show all characters` off.
![image](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/46202915/530c0853-4467-44ad-b6ae-9e2492af7995)

**Comment by pryrt** [comment]
Option already exists:
**All**
![image](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/17455758/8d129f24-76fb-4833-9f9c-40b6d01b8619)

**None**
![image](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/17455758/8f7a1f8e-e191-45b8-a220-5eb3c7ba74ad)

**Show Control Characters & Unicode EOL**
![image](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/17455758/7604969f-4bc7-40b7-8d54-58ebcde8537f)

So, if you want to only show the control characters, but nothing else, just have the **Show Control Characters & Unicode EOL** marked.

**Comment by molsonkiko** [comment]
Thanks, @pryrt ! That is a very helpful explanation.

I'm still slightly disappointed that I need to use two different menu commands (both un-macroable, so a macro can't combine them) to toggle control characters and other non-printing characters; this distinction may be rather pedantic and hard to grasp for some people who aren't familiar with the intricacies of Unicode. That said, I was able to resolve my problem by creating a simple PythonScript:

```
from Npp import *

notepad.menuCommand(44130) # toggle all non-printing characters
notepad.menuCommand(44131) # toggle all control characters (e.g., BEL, ENQ)
```

**Comment by datatraveller1** [comment]
I think the "Show Symbol" options are what we need, but after setting these options, clicking sometime the "Show All Characters" button and then clicking again this button so "Show All Characters" is unchecked, I would prefer to see the old "Show Symbol" settings again instead of all "Show Symbol settings" being unchecked so they always need to be checked manually again.

**Comment by andreqts** [comment]
Personally, I usually prefer to see everything (including newlines) or nothing. But for people who want to see everything but the newline, another option would be the creation of an explicit "**Show All Except End of Line**". So clicking on it would diable the "Show All Characters" options, and vice-versa.

**Comment by LucioMenci** [comment]
I'm agree with @datatraveller1, but I can add something. When you set Show all characters, npp should remember which selections were set previously to retrieve them at its unset. Futhermore, when the specific character style is not selected, I would like that a standard non printing character (like □ or something else) is used, or a simple space, but no disappairing at all. I selected two characters and see 10 characters selected on status bar... After all, when they are unselected, also white spaces, tabs and carriage returns has their used space occuped....

**Comment by molsonkiko** [comment]
So I just realized that you can create macros that couldn't have been recorded by just editing `shortcuts.xml`, so I made a macro that does the same thing as my earlier PythonScript script.

```
<Macro name="toggle_nonprinting_and_control_chars" Ctrl="no" Alt="no" Shift="no" Key="0">
    <Action type="2" message="0" wParam="44130" lParam="0" sParam="" /> <!-- toggle all non-printing characters -->
    <Action type="2" message="0" wParam="44131" lParam="0" sParam="" /> <!-- toggle all control characters (e.g., BEL, ENQ) -->
</Macro>
```

**Comment by molsonkiko** [comment]
> I think the "Show Symbol" options are what we need, but after setting these options, clicking sometime the "Show All Characters" button and then clicking again this button so "Show All Characters" is unchecked, I would prefer to see the old "Show Symbol" settings again instead of all "Show Symbol settings" being unchecked so they always need to be checked manually again. Unchecking "Show All Characters" should only uncheck "View - Symbol - Show End of Line" so the other "Show Symbol" options can persist.

I've [submitted a PR](https://github.com/notepad-plus-plus/notepad-plus-plus/pull/13780) to implement this suggestion.

**Comment by donho** [comment]
https://github.com/notepad-plus-plus/notepad-plus-plus/pull/13780#issuecomment-1603426007
