### ISSUE TITLE
No automatic backup

### ISSUE THREAD

**Issue by mchnp006** [notepad-plus-plus/notepad-plus-plus#13739]
Today when I started Notpad++ there was asked from the software if I would like to install the new update.

I clicked on "yes".

After the update was done, Notepad++ opened and the to-do-list which was shown was an old one.

So I looked on for an backup to-do-list on my computer.

The latest i saved was from the date 9.3.23.

All changes I did from 9.3.23 till yesterday (there are many) are lost.

I ask why after an update from notepad++ the actual to-do-list is not shown and I also ask why there are no automatic backups are done.

**Comment by donho** [comment]
https://github.com/notepad-plus-plus/notepad-plus-plus/blob/master/CONTRIBUTING.md#reporting-issues

**Comment by alankilborn** [comment]
> where is your help???????????

![image](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/77065706/7a539d54-9bb7-4249-b9d6-8f24f530c24b)
