### ISSUE TITLE
XML files being opened with JSON5 language highlighting when opening from Explorer

### ISSUE THREAD

**Issue by maathieu** [notepad-plus-plus/notepad-plus-plus#13746]
### Description of the Issue

When opening an XML file (file extension in .xml), associated to Notepad++ as default editor, via double clicking on it in Explorer, the file's text is all highlighted in orange. Going into the Language menu, the language is set to letter "J" > JSON5.

Opening the file via File > Open interprets it correctly as XML.

### Steps to Reproduce the Issue

1. open an Explorer window containing an XML file (file with .xml extension, associated with Notepad++)
2. double-click on XML file to open it with Notepad++

### Expected Behavior

I expect normal XML syntax highlighting.

### Actual Behavior

The text is all highlighted in orange, and in the language menu, the language is set to letter "J" > JSON5.

### Debug Information

Notepad++ v8.5.3   (64-bit)
Build time : May 15 2023 - 06:09:36
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : "C:\Users\\*********\Documents\test bug notepad++\test ok.xml"
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 10 Enterprise (64-bit)
OS Version : 21H2
OS Build : 19044.2965
Current ANSI codepage : 1252
Plugins : 
    HexEditor (0.9.12)
    mimeTools (2.9)
    NppConverter (4.5)
    NppExport (0.4)

![image](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/382045/c36998ac-b25f-4d2e-aa58-d0be32e710c0)

![image](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/382045/c5a6f64b-2660-459c-81c0-4c79be281244)

**Comment by maathieu** [comment]
EDIT: this could have been caused by a mix between an older standalone installed version and a version installed in c:\Program Files . I have removed the standalone version and now the files seem to open with correct type.

**Comment by jinsu-park-zemt** [comment]
> EDIT: this could have been caused by a mix between an older standalone version and a version installed in c:\Program Files . I have removed the standalone version and now the files seem to open with correct type.

I had the same symptoms and this answer was helpful!!
