### ISSUE TITLE
missing translation

### ISSUE THREAD

**Issue by hugok79** [notepad-plus-plus/notepad-plus-plus#13747]
Missing translation **Close** button. As shown in the image below. (Portuguese)
![Captura de ecrã 2023-06-06 115910](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/16929048/965d6027-6334-4611-8e1d-48ef2750ba18)

**Comment by rddim** [comment]
This is a part of https://github.com/notepad-plus-plus/wingup and the issue is already reported here https://github.com/notepad-plus-plus/wingup/issues/33
