### ISSUE TITLE
Hiding Languages from sub-menu Languages makes language type for the hidden languages not remembered though the sessions

### ISSUE THREAD

**Issue by donho** [notepad-plus-plus/notepad-plus-plus#13743]
### Description of the Issue
Hiding Languages from sub-menu **Languages** makes language type (syntax highlighting & folding) for the hidden languages not remembered though the sessions.

### Steps to Reproduce the Issue
1. Open Preferences dialog, go to "Languages" section.
2. In "Language Menu" part, choose C++ & XML from "Available items" list, put them into "Disabled items" by clicking `->` button.
3. Open some CPP and XML files, and make sure the syntax highlighting & syntax folding working for this files.
4. Close Notepad++ and relaunch it.

### Expected Behavior
The C++ & XML files reopened with both syntax highlighting & syntax folding of its language (C++ or XML) applied. 

### Actual Behavior
The C++ & XML files reopened with no any language applied.

### Debug Information
Notepad++ v8.5.3   (64-bit)
Build time : May 15 2023 - 06:09:36
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 11 Home (64-bit)
OS Version : 22H2
OS Build : 22621.1778
Current ANSI codepage : 1252
Plugins : 
    mimeTools (2.9)
    NppConverter (4.5)
    NppExport (0.4)

**Comment by Yaron10** [comment]
@donho,

Nice catch. :+1:

Thank you.
