### ISSUE TITLE
Special characters in macros are recorded incorrectly

### ISSUE THREAD

**Issue by BernieStn** [notepad-plus-plus/notepad-plus-plus#13757]
### Description of the Issue
Special characters in macros are recorded incorrectly. Recording german ä, ö, ü, and ß resulted in unexpected result when executing the macro.

### Steps to Reproduce the Issue
1. Start Notepad++
2. Record a new macro
3. Enter the following: ä ö ü ß
4. Stop recording the macro
5. Save the macro and assign a name to the macro
6. Execute the macro.

### Expected Behavior
The following should be displayed: ä ö ü ß

### Actual Behavior
See screenshot below.

### Debug Information
Notepad++ v8.5.3   (64-bit)
Build time : May 15 2023 - 06:09:36
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 10 Pro (64-bit)
OS Version : 21H2
OS Build : 19044.2965
Current ANSI codepage : 1252
Plugins : none

![image](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/41064284/333514e5-1519-4810-8648-952c7f0d3b1a)

**Comment by Yaron10** [comment]
@donho, @pryrt & all,

This and the EOL issues.
Would it better to revert https://github.com/notepad-plus-plus/notepad-plus-plus/commit/fff5f9b24c1e7a6f33633b665c06e8785f6a3455 with all its advantages?

**Comment by rdipardo** [comment]
@Yaron10
> Would it better to revert [fff5f9b](https://github.com/notepad-plus-plus/notepad-plus-plus/commit/fff5f9b24c1e7a6f33633b665c06e8785f6a3455) with all its advantages?

My position on that is the same [as before](https://github.com/notepad-plus-plus/notepad-plus-plus/issues/13589#issuecomment-1521156259). The technical debt that TinyXML has become needs to be seriously considered before it starts holding Notepad++ back in even more critical things, like security.

UTF-8 is the present and foreseeable future of data interchange formats. The choice between UTF-8 and TinyXML should be easy to make.

As for this particular issue, `0xC3` is the high-order byte of all four umlauts, so, to take a guess, either :

- the macro was saved by an older N++ version (i.e, as the byte sequence `&#x00c3&#x00a4; &#x00c3&#x00b6; &#x00c3&#x00bc; &#x00c3&#x009f;`), and only the top byte of each character was read by 8.5.3 when it loaded `shortcuts.xml`;

- "neu 1" is encoded in some singe-byte (big-endian ?) code page, so, even if the macro contents were UTF-8, only the first, highest byte was written to the file.

---

@BernieStn, hast du [die FAQ] gelesen?

[die FAQ]: https://community.notepad-plus-plus.org/topic/24464/faq-desk-v8-5-3-macros-and-run-menu-commands

**Comment by Yaron10** [comment]
@rdipardo,

> As for this particular issue, 0xC3 is the high-order byte of all four umlauts, so, to take a guess, either :

I'm not sure.

I've tested `שלום` with the latest version & UTF-8.
If you record **pasting** `שלום`, you get the expected result on playing the macro.
If, however, you record **typing the letters**, you get: 

![תמונה](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/10229320/d1fdf21a-d218-477f-b59f-60432e0ccad1)

Thank you.

**Comment by BernieStn** [comment]
@rdipardo Thanks for your response. Here's an answer for your guess:

- "the macro was saved by an older N++ version". No, I installed a new version of Notepad++, deleted all existing macros (because a MessageBox popped up and informed me that macros might be incompatible, so I thought it would be a good idea to start from scratch) and recorded the new macros.
- "neu 1" is encoded in some singe-byte (big-endian ?) code page": No, it is encoded UTF-8.

If you need further information, please let me know. I will provide any needed information.

**Comment by Yaron10** [comment]
@donho,

Great! 👍
One little `*`. :)

Thank you for the quick fix.

**Comment by donho** [comment]
@Yaron10 
Thank you for your heads up!

**Comment by BernieStn** [comment]
Absolutely great, thanks a lot for this quick fix. Just one character fixes the bug :-)
