### ISSUE TITLE
Shift F3 is broken when [Regular Expression] is selected

### ISSUE THREAD

**Issue by jwongsci** [notepad-plus-plus/notepad-plus-plus#13750]
Reverse Search hotkey (Shift F3) is not functioning when [Regular Expression] option is selected in Find window.
Steps to recreate:
- Open Find window (Ctrl F)
- Under Search Mode group, select [Regular Expression]
- Close Find window
- Select a word to search
- Press F3 to search forward
- Press Shift F3 to search backward ---> BROKEN.

Thank you.

**Comment by donho** [comment]
![image](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/90293/98dbb8d5-95f0-4dd1-ba1d-9b0fbaa2fc80)

**Comment by jwongsci** [comment]
I am using the latest version of notepad++ v8.5.3 (64-bit).
Did you try Shift-F3 hotkey with [Regular expression] checked?

**Comment by jwongsci** [comment]
![image](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/135733882/23a26355-886f-4847-ac32-14d061a07dfb)


My plugins

**Comment by alankilborn** [comment]
>Did you try Shift-F3 hotkey with [Regular expression] checked?

This keycombo should do nothing in the described circumstance.

The user manual has more information on backward searching in regular expression search mode.

It IS working as designed in 8.5.3, meaning that normally you can't do it.
