### ISSUE TITLE
Minor text navigation inconsistency while text is selected

### ISSUE THREAD

**Issue by shodanx2** [notepad-plus-plus/notepad-plus-plus#13754]
Here is the situation, you have selected text but you want to more your cursor back to the starting position

![image](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/10621885/4a5e409f-8887-4ad6-897a-020253deccff)

If you press left arrow, the text is unselected and your cursor returns to the start of the selection.

![image](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/10621885/d71c8f76-f967-4601-ab15-a6ff8ae67579)

However, if you press CTRL+Left arrow 

![image](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/10621885/eb8a5913-d7af-43e5-ba74-c8249ca7201e)

Since CTRL+arrows is how you cross larger distances through text, in this specific situation, it behaves opposite of expectation.

I believe in this specific situation (deselecting text), the cursor should have the same behaviour for arrow key movement than for CTRL+arrow key movement. 

The current behaviour for arrow key movement while text is selected is to : 1 unselect text 2 move cursor to start of selection if left arrow key is pressed and move cursor to end of selection if right arrow key is pressed. If the cursor was already at the location, then the text is unselected and the cursor does not move. 

If the behaviour of cursor movement while text is selected really should be different, then I would propose that the cursor move one delimiter stop past the end of the selection text in the direction of the arrow keypress.

**Comment by donho** [comment]
It's a standard behaviour.

**Comment by shodanx2** [comment]
What standard is that ? 
Intuitively, CTRL+arrow keys increases traversal speed.
But in this situation, CTRL+arrow keys has a lower traversal speed.
If it's a standard, it is inconsistent and something the users have to adapt to without realizing it.
