### ISSUE TITLE
PHP array_key_first() and array_key_last() not highlighted blue

### ISSUE THREAD

**Issue by PawanjitAhluwalia** [notepad-plus-plus/notepad-plus-plus#13752]
### Description of the Issue

PHP **array_key_first** and **array_key_last** not highlighted blue.
### Steps to Reproduce the Issue

Just type in the functions in the editor.

### Expected Behavior

Should be highlighted blue. Have checked - both exist in langs.model.xml.
### Actual Behavior

Both functions remain as normal text.
### Debug Information

Notepad++ v8.5.3   (64-bit)
Build time : May 15 2023 - 06:09:36
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 11 Pro (64-bit)
OS Version : 22H2
OS Build : 22621.1702
Current ANSI codepage : 1252
Plugins : 
    AutoSave (1.6.1)
    mimeTools (2.9)
    NppConverter (4.5)
    NppExport (0.4)
    NppFTP (0.29.10)
    XMLTools (3.1.1.13)
    _CustomizeToolbar (5.3)

**Comment by chcg** [comment]
The PHP lexer is just the embedded one of https://github.com/ScintillaOrg/lexilla/blob/master/lexers/LexHTML.cxx#L42. Therefore

`<?php`

is needed at the top of the php file to get the highlighting.

**Comment by PawanjitAhluwalia** [comment]
Thank you for your feedback. However, given the fact I have only reported two keywords, I assumed it was clear that <?php is already being used. All the other functions I am using are highlighting blue as normal. Sorry if I didn't make this sufficiently clear.

**Comment by ArkadiuszMichalski** [comment]
They were added a long time ago https://github.com/notepad-plus-plus/notepad-plus-plus/commit/e7bf582ffddbcfa6c9907bdfc963864bbdce7372. Looks like you have old `langs.xml` file. Update your file or try with portable version (where this file is always up to date).
![image](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/2730894/c492ae94-4d50-44c9-8cc6-06d942ae7473)

**Comment by PawanjitAhluwalia** [comment]
As I mentioned above I do see them both in the langs.model.xml file. Is this the correct file?

How do I use the 'portable version'? Where do I get it from and how do I install it?

**Comment by ArkadiuszMichalski** [comment]
Try read this [Outdated configuration files](https://github.com/notepad-plus-plus/notepad-plus-plus/wiki/FAQ#outdated-configuration-files).

**Comment by PawanjitAhluwalia** [comment]
I tested using the portable version as you suggested and it worked fine. So I uninstalled my current version of Notepad++ and reinstalled a brand new version. Now both keywords are being highlighted. Thank you for your help in resolving this!
