### ISSUE TITLE
Regression in v8: Style token does not work for some strings

### ISSUE THREAD

**Issue by SBieger** [notepad-plus-plus/notepad-plus-plus#13771]
### Description of the Issue
Since version 8.0 the "Style token" feature does not work as expected for some texts.

### Steps to Reproduce the Issue
1. Enter the following example text: "Test .\2023-06-11 Test Test .\2023-06-11 Test"
2. Now mark the first occurence of "\2023-06-11", right-click on it and select a "Style token"

### Expected Behavior
Up to version 7.9.5 this does highlight both appearances of "\2023-06-11" with the selected style token color.

### Actual Behavior
Nothing is highlighted. Interestingly if the selected portion is ".\2023-06-11" (so that it includes the leading dot), the style token works. Seems like it is a problem when the first character is backslash.

### Debug Information
Notepad++ v8   (32-bit)
Build time : Jun  6 2021 - 18:41:52
Path : C:\Users\Name\Documents\npp.8.0.portable.minimalist\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : ON
Cloud Config : OFF
OS Name : Windows 10 Enterprise (64-bit) 
OS Version : 2009
OS Build : 19042.631
Current ANSI codepage : 1252
Plugins : none

**Comment by alankilborn** [comment]
I can reproduce this on 8.5.3.

>Interestingly if the selected portion is ".\2023-06-11" (so that it includes the leading dot), the style token works

For me the start-with-leading-dot case worked, but strangely.
Normally if one styles all occurrences, the "source" one will be styled and be seen when the selection is removed from it by the user moving the caret after the style command has completed.
But NOT in this case; it styles all of the others but not the one that is the "source".

**Comment by alankilborn** [comment]
See if this setting is ticked; if it is ticked, untick it and try your issue again:

![image](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/77065706/a9675a9f-8ed8-4799-a8b2-eb9b1ac20926)

**Comment by SBieger** [comment]
Thanks for the hint. Yes, this option was indeed ticked. After I disabled the option, the behaviour is like it used to be on the older versions of Notepad++.
So, no regression. Actual problem was in front of the keyboard ;-)

**Comment by alankilborn** [comment]
>Actual problem was in front of the keyboard

Well, don't beat yourself up about it.  I actually debugged it by single-stepping the code, to find root cause.  So it wasn't an obvious thing...

**Comment by alankilborn** [comment]
This: https://github.com/notepad-plus-plus/notepad-plus-plus/issues/13771#issuecomment-1591268276

ended up being a non-issue; or rather a different manifestation again caused by having _Match whole word only_ ticked.
