### ISSUE TITLE
NUL in txt document

### ISSUE THREAD

**Issue by SDRTGT45** [notepad-plus-plus/notepad-plus-plus#13770]
I ran into a problem when a large file with the work of three whole years turned into one big NULL text, when trying to restore it, everything happens, the file is restored, but its contents turn into hieroglyphs, and an attempt to change the encoding does not lead to anything, please tell me what to do?
![2023-06-11_17-48-37](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/98409327/12c4430b-d24b-4d78-aee4-c00423fe8cfe)
![2023-06-11_17-48-22](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/98409327/3605c172-68da-4156-a6c7-1d1a01740bd3)

**Comment by donho** [comment]
@SDRTGT45 
Could you provide your debug info via menu `?`->`Debug Info...` please?

**Comment by SDRTGT45** [comment]
Notepad++ v7.8.5   (64-bit)
Build time : Mar  4 2020 - 11:08:34
Path : D:\Program Files\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS Name : Windows 10 Pro (64-bit) 
OS Version : 2009
OS Build : 19042.2364
Plugins : mimeTools.dll NppConverter.dll NppExport.dll 


In the evening I made some changes to the text, and in the morning when I opened it I found the full contents of NULL (image 2), I downloaded the file through the recovery program "Recovery Wizard", but when I opened this file I found that all my text turned into hieroglyphs (image 1)

**Comment by P0rsche-911** [comment]
Image 1: Macintosh

Image 2: Windows

Different coding?

**Comment by SDRTGT45** [comment]
I don't know, I just noticed, but the restored file and Windows doesn't work, I've already poked back at the Mac, I've visited all the options, and put it on Windows too

**Comment by SDRTGT45** [comment]
Maybe it will help, but I will attach 2 versions of the broken file, the original ZERO and its version with the broken encoding
[chipsam_1.txt](https://github.com/notepad-plus-plus/notepad-plus-plus/files/11715721/chipsam_1.txt)
[chipsam_1.txt](https://github.com/notepad-plus-plus/notepad-plus-plus/files/11715722/chipsam_1.txt)

**Comment by xomx** [comment]
@SDRTGT45 

> Notepad++ v7.8.5 (64-bit) Build time : Mar 4 2020 - 11:08:34

This is a pretty old version of the N++. Meanwhile, many versions have been released that specifically tried to eliminate such problems (IMO - it was not so much a mistake in the N++, as the prevention of errors arising from the Windows caching mechanism at specific circumstances like unexpected power outages, Windows Update forced reboots etc). For the future I recommend upgrading to any N++ v8.4.9+ (if so, do not forget to update all your x64 plugins as from the v8.3+ there is support for large 2GB+ files which brings some incompatibility for many plugins...).

> In the evening I made some changes to the text, and in the morning when I opened it I found the full contents of NULL

Was there an unattended restart in the meantime? 

> Maybe it will help, but I will attach 2 versions of the broken file, the original NUL and its version with the broken encoding
> [chipsam_1.txt](https://github.com/notepad-plus-plus/notepad-plus-plus/files/11715721/chipsam_1.txt)
> [chipsam_1.txt](https://github.com/notepad-plus-plus/notepad-plus-plus/files/11715722/chipsam_1.txt)

It seems to me that the restored one is just random garbage from the disc, sorry.

**Comment by SDRTGT45** [comment]
Hmm, okay, I found backups for 2021, nothing terrible happened, of course now the files are garbage, but nothing can be done. I decided to update Notepad++ to the latest version, I think the issue is settled
