### ISSUE TITLE
Notepad++ 6.8.9 crashing in custom languages.

### ISSUE THREAD

**Issue by westor7** [notepad-plus-plus/notepad-plus-plus#1377]
Hello,

6.8.9 crashing when i open a file (like test.mp3) and inside the .mp3 it has an custom language style that this style does not exist into the XML language custom addition.

if the XML file has for example this XML setting: http://pastebin.com/6As71d7Q
the problem that i detect is if it has an other extention in the XML setting and you try to load an other
file extention then in any file modification the Notepad++ crashing.

and trying to load an .mp3 file that inside this file it has code instead of song and if you modify it from an other program source then Notepad++ crashing and not asking for reload.

Notepad++ v6.8.9
Build time : Jan 12 2016 - 00:00:51
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10
Plugins : mimeTools.dll NppConverter.dll NppExport.dll NPPJSONViewer.dll PluginManager.dll

**Comment by donho** [comment]
https://notepad-plus-plus.org/news/v6.8.9-has-been-removed.html
