### ISSUE TITLE
Selected multiple files are being opened as new instance for each file while on Multi-Instance mode

### ISSUE THREAD

**Issue by eltheaseir** [notepad-plus-plus/notepad-plus-plus#13778]
### Description of the Issue
Recently (not sure if Windows update but currently on Windows 11 Version 22H2 OS Build 22621.1702) when opening multiple files, each file will be opened on a new instance of N++. So if I open 3 files, there will be 3 instances of N++

When using multi-instance mode
### Steps to Reproduce the Issue
1. Enable "Always in multi-instance mode"
2. Select multiple files (logs or text files) by highlighting, right click and "Edit with Notepad++"

### Expected Behavior
By right, all selected files should be opened in a single instance of Notepad++ and if you select another group of files, it should be opened on another instance and all files should be on it.

### Actual Behavior
Each files are being opened in a new (separate) instance

### Debug Information
Notepad++ v8.5.3   (64-bit)
Build time : May 15 2023 - 06:09:36
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : "C:\SFDC\Premise\0003314981\2023.06.13\ESJconsole _V1.log"
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 11 Enterprise (64-bit)
OS Version : 22H2
OS Build : 22621.1702
Current ANSI codepage : 1252
Plugins : 
    mimeTools (2.9)
    NppConverter (4.5)
    NppExport (0.4)

**Comment by donho** [comment]
"Always multi-instance" means what it does mean.
So the result is expected.

**Comment by donho** [comment]
Just checked the behaviour of v8.4.8 - its behaviour is as you described for the old version.
So this is a regression but not a feature. My apologies.

**Comment by eltheaseir** [comment]
Thanks @donho I switched back to much more older version which is 7.6. Will the fix for this be included in the next release?

**Comment by donho** [comment]
@eltheaseir 
An issue of NppShell has been created here: https://github.com/notepad-plus-plus/nppShell/issues/36

@GurliGebis 
Could you check this issue please?

**Comment by GurliGebis** [comment]
Sure, I'll take a look at it - might be a few days before I get around to it though.

**Comment by Yaron10** [comment]
NPP portable version.
Manually associate some files with NPP.
Set _Always in multi-instance mode_.
Select some associate files in _File Explorer_.
Right-click and _Open_.

Result on my Windows 10 machine:
The files are opened in separate instances.

**Comment by pnedic** [comment]
Seems after windows update (last night) I've got irritating N++ behavior: if I select multiple files in win explorer and select "Edit with Notepad++" then depending of selected "Multi instance settings" I get two (unacceptable) behaviors
First behavior is with selected "Default (mono instance)" OR "Open session in new instance (and save...." it always opens files in the same (already opened) N++ window (instance)
Second behavior is with selected "Always in multi-instance mode" it opens each file in new window.

Till yesterday, each selected group of files it was opening in new instance. This option now I cannot get. And this is really irritating to me.

Any help ?

**Comment by Yaron10** [comment]
> Result on my Windows 10 machine:
The files are opened in separate instances.

I meant that this might be the expected behavior as @donho initially assumed.
Anyway, it seems that some users would prefer a different result.

**Comment by GurliGebis** [comment]
@donho the PR looks line 🙂

**Comment by eltheaseir** [comment]
> NPP portable version. Manually associate some files with NPP. Set _Always in multi-instance mode_. Select some associated files in _File Explorer_. Right-click and _Open_.
> 
> Result on my Windows 10 machine: The files are opened in separate instances.



> Seems after windows update (last night) I've got irritating N++ behavior: if I select multiple files in win explorer and select "Edit with Notepad++" then depending of selected "Multi instance settings" I get two (unacceptable) behaviors First behavior is with selected "Default (mono instance)" OR "Open session in new instance (and save...." it always opens files in the same (already opened) N++ window (instance) Second behavior is with selected "Always in multi-instance mode" it opens each file in new window.
> 
> Till yesterday, each selected group of files it was opening in new instance. This option now I cannot get. And this is really irritating to me.
> 
> Any help ?

Guys @Yaron10 @pnedic if you read back, you will see that @donho said they will try to fix this behavior and you can refer to this link https://github.com/notepad-plus-plus/nppShell/issues/36 for the progress. Thanks!



> @eltheaseir An issue of NppShell has been created here: [notepad-plus-plus/nppShell#36](https://github.com/notepad-plus-plus/nppShell/issues/36)
> 
> @GurliGebis Could you check this issue please?

**Comment by pnedic** [comment]
Hello, yes I've read debug info. Now, waiting for new NPP version to download.

**Comment by pnedic** [comment]
New version of NPP 8.5.4 did NOTHING related to this problem. They told they did it !?
Please check it again
