### ISSUE TITLE
Can't connect to an Azure account with FTPS

### ISSUE THREAD

**Issue by jk-85** [notepad-plus-plus/notepad-plus-plus#13785]
An Azure FTPS account is unable to connect to an FTPS Azure endpoint. I tried out many things but mostly I get "Unable to connect". If I use FileZilla it works like a charme. Maybe it's because the username Azure want's to connect has a $ in it? (blabla/$blabla), or the long password I can't change via Azure? Password has a length of 60 characters.

I use Notepad++ 8.5.3

**Comment by donho** [comment]
I guess you are reporting for FTP plugin for Notepad++.
It's rather a plugin issue than Notepad++'s one.
Please report it to plugin project.

**Comment by jk-85** [comment]
OK, will do so.
