### ISSUE TITLE
new “open new blank document in addition on startup” option

### ISSUE THREAD

**Issue by circcc** [notepad-plus-plus/notepad-plus-plus#13796]
“open new blank document in addition on startup” option is needed only when remembering sessions for improve privacy, so it is better to go into the sub option of "Remember current session for next launch" option I think. If I turn on “open new blank document in addition on startup” option without using the remember session option, I get two tabs, new 1 and new 2. What is the use of these? 
![mock](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/72944033/f231483f-d513-4462-adb6-f29724377398)

**Comment by donho** [comment]
The GUI won't change. OTOH, if **"Remember current session for next launch"** is OFF, no blank doc  will be added on startup even **"Always open a new document in addition at startup"** is ON.
