### ISSUE TITLE
Feature Request: Add shortcut "Open containing folder in PowerShell"

### ISSUE THREAD

**Issue by AnuragUnnikannan** [notepad-plus-plus/notepad-plus-plus#13794]
### Feature Request

Similar to the shortcut "Open containing folder in Command Prompt", it would be nice to have another shortcut for opening the containing folder in PowerShell.

**Comment by alankilborn** [comment]
Just add it to the _Run_ menu.
Do _Run_ > _Run..._ and then put this in for _The Program To Run_:

`%SystemRoot%\system32\WindowsPowerShell\v1.0\powershell.exe -noexit -command "cd '$(CURRENT_DIRECTORY)'"`

Save it and give it a name and a shortcut.

**Comment by AnuragUnnikannan** [comment]
Thanks! That worked.

Closing the issue.
