### ISSUE TITLE
Support for Proxy PAC

### ISSUE THREAD

**Issue by sbpodila** [notepad-plus-plus/notepad-plus-plus#1380]
For setting updater proxy , current supported with IP and port. It will be good if there an option to choose Internet Explorer settings or support for proxy pac file.

Thanks,
Sasi

**Comment by zerbey** [comment]
Bumping this.  A proxy PAC file is just JavaScript code so we should only need to duplicate the existing JavaScript to account for Proxy.

**Comment by donho** [comment]
It means Notepad++ should has a JavaScript engin to execute PAC file or to get the value from PAC file.
