### ISSUE TITLE
German umlauts aren't displayed anymore in Run menu

### ISSUE THREAD

**Issue by dodmi** [notepad-plus-plus/notepad-plus-plus#13803]
### Description of the Issue

The titles of the entries containing German umlauts are broken in the run menu

### Steps to Reproduce the Issue

1. Open NPP 8.5.4
2. Open "Ausführen"

### Expected Behavior

I'd expect to see correct German umlauts, where they are contained

### Actual Behavior

![image](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/4572946/417d0f52-e95d-4a9e-bae0-67b7fea416d0)

**Comment by rdipardo** [comment]
> ![image](https://user-images.githubusercontent.com/4572946/246909985-417d0f52-e95d-4a9e-bae0-67b7fea416d0.png)

Hast du [die FAQ] gelesen?

[die FAQ]: https://community.notepad-plus-plus.org/topic/24464/faq-desk-v8-5-3-macros-and-run-menu-commands

**Comment by dodmi** [comment]
No, I didn't. I read the changelogs. After reading this FAQ, I guess this hides behind "Add the UTF8 character ability for Run & Macro menu."

The entries from the screenshot are default entries coming with the default installation of Notepad++. Why don't you handle such a thing with the update routine (or maybe better on the first run of NPP) itself. At the moment, NPP is undeployable in larger environments. 

What's the proposed way to update multiple machines with more than one user profile?
Tell each user: Hey, it's broken and if you'd like to fix it, go to a hidden directory and replace fancy characters?

You broke it, please fix it.

**Comment by donho** [comment]
@dodmi 
> You broke it, please fix it.

RTFM
