### ISSUE TITLE
SHA-256 entry is displayed twice in tools menu

### ISSUE THREAD

**Issue by dodmi** [notepad-plus-plus/notepad-plus-plus#13802]
### Description of the Issue
After introducing SHA-1 features in NPP 8.5.4 (seen in changelog), I've two entries for SHA-256 but no entry for SHA-1

### Steps to Reproduce the Issue

1.  Open NPP 8.5.4 (German)
2. Open "Werkzeuge"

### Expected Behavior

I'd expect to see entries for MD5, SHA-1 and SHA-256

### Actual Behavior

![image](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/4572946/ac8d0b6c-f8eb-4f17-a3ca-ed22b6863ced)

**Comment by rddim** [comment]
It is fixed in https://github.com/notepad-plus-plus/notepad-plus-plus/commit/5b5238610e6ca57ee779d04aa19db9e8df568241 but the translations of `Generate...`, `Generate from files...` and `Generate from selection into clipboard` are not added.

**Comment by donho** [comment]
@rddim 
They are added  in https://github.com/notepad-plus-plus/notepad-plus-plus/commit/4ffd897ccf8d30d8dd945c42907e61381c590d08
