### ISSUE TITLE
Clipboard History panel shows unexpected hieroglyph-like symbols

### ISSUE THREAD

**Issue by d0vgan** [notepad-plus-plus/notepad-plus-plus#13817]
### Description of the Issue
When Notepad++ is active and its Clipboard History panel is shown, after copying and pasting in both Notepad++ and other applications (such as other text editors, file managers, browsers) during some noticeable time (let's say, 2 hours) one may notice unexpected hieroglyph-like symbols (that were not part of any copy-pasted text).
This behavior is reproduced with and without plugins.
Please look at the screenshot (I did not alter the screenshot - it shows exactly how the Clipboard History panel looks like).
![Npp_ClipboardHistory](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/2848457/229db7d6-9e76-45b3-b497-ab4a047c45d5)

### Steps to Reproduce the Issue
1. Start Notepad++
2. Show the Clipboard History panel and keep it visible
3. Copy and paste different text inside and outside Notepad++ during a few hours (if you are a developer, it actually means just to keep Notepad++ open with its Clipboard History panel visible during a few working hours).
4. Observe how the lines in the  Clipboard History panel look like
5. I noticed that when I copy-paste from and to [FAR Manager](https://farmanager.com/download.php?l=en), especially when copying multi-line text (in [FAR Manager](https://farmanager.com/download.php?l=en) it is e.g. Ctrl+Insert and Ctrl+Alt+Insert when there are selected files in the file panels), the chances to get corrupted text in the Clipboard History are higher.

### Expected Behavior
All the copy-pasted strings shoud look as is, without any unexpected symbols.

### Actual Behavior
Unexpected hieroglyph-like symbols appear (see the screenshot). Also, some other strings look truncated (some trailing characters are missed).
I believe it may be caused by out-of-buffer reading, when e.g. some data in the Clipboard is expected to be a null-terminated string while it is actually not (I mean, it does not contain the trailing \0); or, maybe, some code in Notepad++ uses structures where the trailing \0 is expected but not provided.

### Debug Information
Notepad++ v8.5.4   (32-bit)
Build time : Jun 17 2023 - 20:40:14
Path : C:\Progs\Notepadpp\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : ON
Cloud Config : OFF
OS Name : Windows 10 Enterprise (64-bit)
OS Version : 22H2
OS Build : 19045.3086
Current ANSI codepage : 1251
Plugins :

**Comment by alankilborn** [comment]
If you double-click to paste one of these entries, what gets pasted into your N++ document. the correct text, or the hieroglyph-like symbols?

**Comment by d0vgan** [comment]
Well, I've debugged it and here is the outcome.
The method `ClipboardHistoryPanel::getClipboadData()` is responsible for capturing clipboard data.
When a text is copied to the Clipboard within Notepad++ itself, the following code block is executed:
```
else if (lpWchar != nullptr)
{
	int nbBytes = (lstrlenW(lpWchar) + 1) * sizeof(wchar_t);
	for (int i = 0 ; i < nbBytes ; ++i)
	{
		clipboardData.push_back(static_cast<unsigned char>(lpchar[i]));
	}
}
```
This code works perfectly: it reads the proper number of wide characters plus the trailing '\0'.
When a text is copied to the Clipboard in FAR Manager, the following code block is executed:
```
if (IsClipboardFormatAvailable(cf_nppTextLen))
{
	HGLOBAL hglbLen = GetClipboardData(cf_nppTextLen); 
	if (hglbLen != NULL) 
	{ 
		unsigned long *lpLen = (unsigned long *)GlobalLock(hglbLen); 
		if (lpLen != NULL) 
		{
			for (size_t i = 0 ; i < (*lpLen) ; ++i)
			{
				clipboardData.push_back(static_cast<unsigned char>(lpchar[i]));
			}
			GlobalUnlock(hglbLen); 
		}
	}
}
```
This code block contains 2 general errors:
1. The value of `*lpLen` is a lengths in wide characters, so it must be multiplied by `sizeof(wchar_t)` to get the number of bytes.
2. The value of `*lpLen` does not include the trailing '\0' character, so it must be explicitly added as well.

Finally, in all honestly, I don't understand the whole idea with `RegisterClipboardFormat(CF_NPPTEXTLEN)`. As I can see, it reveals (causes?) the errors mentioned above. But what is the purpose and what is the benefit of doing it?

**Comment by d0vgan** [comment]
Here is the corresponding Clipboard helper function in NppExec's code. It works:
```
tstr GetClipboardText(HWND hWndOwner )
{
    tstr sText;

    if ( ::OpenClipboard(hWndOwner) )
    {
      #ifdef UNICODE
        const UINT uClipboardFormat = CF_UNICODETEXT;
      #else
        const UINT uClipboardFormat = CF_TEXT;
      #endif
        HANDLE hClipboardTextData = ::GetClipboardData(uClipboardFormat);
        if ( hClipboardTextData )
        {
            LPTSTR pszText = (LPTSTR) ::GlobalLock(hClipboardTextData);
            if ( pszText )
            {
                sText = pszText;
                ::GlobalUnlock(pszText);
            }
        }
        ::CloseClipboard();
    }

    return sText;
}
```

**Comment by Yaron10** [comment]
Also:

https://github.com/notepad-plus-plus/notepad-plus-plus/blob/1943ce87b59a5147932dbfaa0f9885332ab6b5a5/PowerEditor/src/WinControls/ClipboardHistory/clipboardHistoryPanel.cpp#L65

Shouldn't it be `lpWchar`?

@donho,

Could you please have a look?

Thank you.

**Comment by Yaron10** [comment]
I get gibberish on copying certain characters(e.g. Tab, EOL) in NPP.

Copying
![תמונה](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/10229320/dde27837-d71b-4488-8d04-d9b174d3c748)

I get:
![תמונה](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/10229320/b66e028f-f609-41ff-8b7d-1f0ba26460df)

**Comment by Yaron10** [comment]
@d0vgan,

> Finally, in all honestly, I don't understand the whole idea with `RegisterClipboardFormat(CF_NPPTEXTLEN)`.

The purpose might be `IDM_EDIT_COPY_BINARY`.
https://github.com/notepad-plus-plus/notepad-plus-plus/blob/1943ce87b59a5147932dbfaa0f9885332ab6b5a5/PowerEditor/src/NppCommands.cpp#L432
***
> I get gibberish on copying certain characters(e.g. Tab, EOL) in NPP.

Can you reproduce that?

**Comment by donho** [comment]
@d0vgan @Yaron10 
I have run Notepad++ (current master, debug version) more than 8 hours now. 
But cannot reproduce the bug (all the copied text displayed correctly and paste  the exact text). 
My windows localization is in English, so I'm wondering this bug can be reproduced only on non-English Windows.
What's the language of your Windows?

**Comment by d0vgan** [comment]
Originally I noticed it on a machine in cloud with English locale and Windows 11. Then I reproduced it on a local PC and local laptop, both with Windows 10 and cp1251 as non-Unicode character set.
Did you try to reproduce it with [FAR Manager](https://www.farmanager.com/download.php?l=en)? To me, it happens almost immediately, after a couple of attempts:
1. Run FAR Manager (Far.exe)
2. In FAR Manager's panel, select 2 or 3 items in the active file panel (by pressing Insert - the selected items will have yellow color)
3. In FAR Manager's panel, copy the selected items to the clipboard (by pressing Ctrl+Insert or Ctrl+Alt+Insert).
That's it. You should be able to hit a breakpoint in Notepad++ under the `if (IsClipboardFormatAvailable(cf_nppTextLen))` code block.

**Comment by Yaron10** [comment]
@donho,

Thank you for looking into it.

> But cannot reproduce the bug (all the copied text displayed correctly and paste the exact text).

I suppose you're referring to my Tab & EOL issue as well.

My Windows language is Hebrew.

https://github.com/notepad-plus-plus/notepad-plus-plus/blob/1943ce87b59a5147932dbfaa0f9885332ab6b5a5/PowerEditor/src/WinControls/ClipboardHistory/clipboardHistoryPanel.rc#L27C50-L27C69

If I remove `LBS_OWNERDRAWFIXED` (which, BTW, solves https://github.com/notepad-plus-plus/notepad-plus-plus/issues/13827) and add `LBS_USETABSTOPS`, the Tab issue is fixed.

So copying
![תמונה](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/10229320/943d5e30-1a51-461f-bf84-3c259538620d)

I get
![תמונה](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/10229320/87d062ea-44f1-4e97-9a29-119e5cdc7de9)

**Comment by donho** [comment]
@d0vgan 
I can reproduce this issue by using Far.exe - the corrupted text concerns only the copied data via far.exe. The other data via other applications (Firefox, Git MingW64 shell and other win appz) remains correct.

The code:
```cpp
	/*1*/		UINT cf_nppTextLen = RegisterClipboardFormat(CF_NPPTEXTLEN);
	/*2*/		if (IsClipboardFormatAvailable(cf_nppTextLen)) 
			{
	/*3*/			HGLOBAL hglbLen = GetClipboardData(cf_nppTextLen);
				if (hglbLen != NULL) 
				{ 
					unsigned long *lpLen = (unsigned long *)GlobalLock(hglbLen); 
					if (lpLen != NULL) 
					{
						for (size_t i = 0 ; i < (*lpLen) ; ++i)
						{
							clipboardData.push_back(static_cast<unsigned char>(lpchar[i]));
						}
						GlobalUnlock(hglbLen); 
					}
				}
			}
	/*4*/		else if (lpWchar != nullptr)
			{
				int nbBytes = (lstrlenW(lpWchar) + 1) * sizeof(wchar_t);
				for (int i = 0 ; i < nbBytes ; ++i)
				{
					clipboardData.push_back(static_cast<unsigned char>(lpchar[i]));
				}
			}
```
Code explanation:
1. **RegisterClipboardFormat** registers **CF_NPPTEXTLEN** format for the 1st time and get the registered ID, if the format has been registered, then the same ID will be returned.  for **CF_NPPTEXTLEN** format, as @Yaron10 said, it's Notepad++ internal format for the binary.
2. Test to see if the binary data is in the clipboard, if yes, than do the point 3.
3. Get binary length in the Clipboard, loop it to copy the binary data byte by byte.
4. In case that it's not binary data, copy it as normal wchar.

So normally, the copied data in clipboard via other applications should stop at 2 then jump to 4, since there's no way to do [the same as Notepad++](https://github.com/notepad-plus-plus/notepad-plus-plus/blob/master/PowerEditor/src/NppCommands.cpp#L431C4-L433C37) in these applications.

After my quick test, it seems to me far.exe is the only application which causes this issue. Could you contact their devs to see how do they handle the copied data from far.exe to the Clipboard?

**Comment by d0vgan** [comment]
It looks like there are inconsistencies in both FAR Manager and Notepad++ itself.

Here is how the bug can be reproduced by means of Notepad++ itself:
[here](https://github.com/notepad-plus-plus/notepad-plus-plus/blob/master/PowerEditor/src/NppCommands.cpp#L476) CF_NPPTEXTLEN interpreted as length in symbols without trailing zero. but [here](https://github.com/notepad-plus-plus/notepad-plus-plus/blob/master/PowerEditor/src/WinControls/ClipboardHistory/clipboardHistoryPanel.cpp#L52) as length in bytes including trailing zero. if you do Edit->Paste Special->Copy Binary Content you get the same trash bytes without FAR Manager.

**Comment by Yaron10** [comment]
@donho,

> I cannot reproduce both issues on my PC either.
...
> Unfortunately, LBS_OWNERDRAWFIXED cannot be removed...

👍 
Thank you for the explanation.

I've opened a separate issue.
https://github.com/notepad-plus-plus/notepad-plus-plus/issues/13832.

**Comment by donho** [comment]
@d0vgan 
> [here](https://github.com/notepad-plus-plus/notepad-plus-plus/blob/master/PowerEditor/src/NppCommands.cpp#L476) CF_NPPTEXTLEN interpreted as length in symbols without trailing zero. but [here](https://github.com/notepad-plus-plus/notepad-plus-plus/blob/master/PowerEditor/src/WinControls/ClipboardHistory/clipboardHistoryPanel.cpp#L52) as length in bytes including trailing zero.

Sorry I don't follow you:
Both codes are almost the same except the usage of length.
Could you elaborate it?

**Comment by rdipardo** [comment]
@d0vgan,
> Edit->Paste Special->Copy Binary Content

That implies the FAR Manager copies ANSI text to the clipboard: an array of `char`s is the same thing as a *byte* array &mdash; i.e. *binary* data.

@donho,
> Both codes are the same for getting length. 

Yes, but `lpchar` should be *segmented* differently depending on the *encoding* of the text it points to. 

If it points to *binary data* (i.e. ANSI text, array of `char`), then counting each byte 1 by 1 is OK. 

But if it points to *Unicode* text (array of `wchar_t`), then you should count by `sizeof(wchar_t)` (i.e. 2 bytes at a time; *hint: remember [this?]*)


[this?]: https://github.com/notepad-plus-plus/notepad-plus-plus/issues/13556#:~:text=wchar_t%20%C3%97%2064-,After%20fff5f9b,-Unicode%20%E2%86%92%20ANSI%20%E2%86%92%20Unicode

**Comment by donho** [comment]
@d0vgan @rdipardo 
I see the problem, it's not problem of length, but the problem of pointer.
I'll do a PR for that. Thank you for the help.
