### ISSUE TITLE
One click open file on the sidebar

### ISSUE THREAD

**Issue by webdev20** [notepad-plus-plus/notepad-plus-plus#1382]
Hey,

I want to suggest a one click open file on the left sidebar of notepad++, just like what sublime and brackets have. It currently require double click to open file on document tree view.

It will make notepad++ perfect if that feature can be added.

Thank you,
Ari

**Comment by sr12123** [comment]
can you just elaborate more what do you want ???

**Comment by webdev20** [comment]
Hello, this is what I mean
https://youtu.be/tRPzkPoKIys

Thank you,
Ari

**Comment by sr12123** [comment]
okay understood
Thanks

**Comment by carlosporter** [comment]
Was I this ever implemented on notapad++ ?

**Comment by sasumner** [comment]
Personally, I think that double-click is better.  Single-click is too prone to an error click activating it.

**Comment by webdev20** [comment]
Visual studio code is a good example of this sort of feature implementation. It does single click to open the file on editor and double click to persist it.

**Comment by carlosporter** [comment]
Thanks for the reply, I agree... Double click is better when you're programming, but in my case I create about 100 to 150 plain text files per day and I have to be going back and forth between notes, so speed is a key factor. it's more important than security specially when all you need is a quick glance at the contents of a file, on that regard Visual Studio or Atom do the job just fine.

**Comment by sasumner** [comment]
I've never considered the difference in the amount of effort between a single click and a double click.  Thinking about it now, I think it is negligible.  Still vote for leaving this alone.

**Comment by webdev20** [comment]
Thanks everyone..

On 4/13/19, MetaChuh <notifications@github.com> wrote:
> Closed #1382.
>
> --
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/notepad-plus-plus/notepad-plus-plus/issues/1382#event-2273872603


-- 
Best Regards,

Ari Susanto
skype: avajo71
Mobile: 087824204171

**Comment by darkoverlordofdata** [comment]
It's a good reason not to use notepad++. I know I uninstalled it.

**Comment by scabilos** [comment]
I have the same need since yesterday.
I want to use np++ to manage many notes on Windows.
Applications like Obsidian and friends generate extra files and folders, and use markdown, which is not suitable where simplicity and a clean folder structure is key.
Coming fom the Linux world, I know the difference in speed and comfort between one click and two clicks.

**Comment by jonsnow231** [comment]
Notepad++ could replace many knowledge bases like Obsidian and Zim for me if it had a few simple features like one click files that automatically saved and closed when you clicked another.

**Comment by manfromarce** [comment]
It would be nice if this was reconsidered (as an option, not a default behavior)
