### ISSUE TITLE
An open source software with serious political tendencies

### ISSUE THREAD

**Issue by xinzeyi** [notepad-plus-plus/notepad-plus-plus#13825]
An open source software with serious political tendencies, individuals have a position, but should not be substituted into the political color.

**Comment by xinzeyi** [comment]
<img width="696" alt="Snipaste_2023-06-23_18-35-10" src="https://github.com/notepad-plus-plus/notepad-plus-plus/assets/70065876/2fe03afb-926e-40f5-a38f-9f241df0de35">

**Comment by Korb** [comment]
This is a duplicate of #6288 (disrespect for other members of the FOSS community by posting political propaganda spam in text editor resources).
