### ISSUE TITLE
Feature proposal: File status detection only when reopening files

### ISSUE THREAD

**Issue by b9a1** [notepad-plus-plus/notepad-plus-plus#13824]
When opening a file (e.g. from File Explorer) that has already been opened in Notepad++, it is useful to know if the file has been modified by another program, even if File Status Auto‐Detection is not enabled. Otherwise, one might forget that the file has been opened and be confused by seeing an outdated copy of the file.

Therefore, I’m proposing a new option for the File Status Auto‐Detection settings:

- Enable
- Enable for all opened files
- **Enable when reopening files**
- Disable

Compared to ‘Disable’, this option ensures that opening a file always means reading its content, and never merely switching to an existing tab. I think this behavior is more desirable for most use cases. The feature may be assigned to myself if accepted.

**Comment by donho** [comment]
The current 3 states are enough for covering all situation. This added state (option) will make users confused.
