### ISSUE TITLE
Problem with the character º (U+00BA)

### ISSUE THREAD

**Issue by gabrielbarros** [notepad-plus-plus/notepad-plus-plus#1383]
I create a new file (UTF-8 w/o BOM) with the following content:
Nº

I save it and close the file. Then when I reopen it, it shows:
Nยบ

But if I save it as ANSI or UTF-8 with BOM, it will open correctly. Anyway, when I open the file with Windows notepad, it'll open correctly whether it's ANSI or UTF-8.

[utf8.txt](https://github.com/notepad-plus-plus/notepad-plus-plus/files/95176/utf8.txt) (md5: 19C4A38B9C5866A8AD3A1954E813EEE6)
[ansi.txt](https://github.com/notepad-plus-plus/notepad-plus-plus/files/95177/ansi.txt) (md5: 4CEC92E0E408D56CCE53479C8DC8EB87)
[utf-bom.txt](https://github.com/notepad-plus-plus/notepad-plus-plus/files/95184/utf-bom.txt) (md5: 1E83AA366B7D0D71F46BC87ABA3F81AC)

![utf8](https://cloud.githubusercontent.com/assets/3298817/12406668/4eefd4de-be36-11e5-9fb9-9034ce906320.png)
![ansi](https://cloud.githubusercontent.com/assets/3298817/12406671/526913dc-be36-11e5-9ceb-7237774c36de.png)

**Comment by gabrielsbarros** [comment]
Opening the files with a hex editor:
ansi.txt:
4e ba

utf8.txt
4e c2 ba

-----------------------------------------------

Debug info:
Notepad++ v6.8.8
Build time : Dec 10 2015 - 01:11:37
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 7
Plugins : mimeTools.dll NppConverter.dll NppExport.dll NppFTP.dll PluginManager.dll

**Comment by guy038** [comment]
Hello **gabrielsbarros**,

Sorry for this very, very **late** reply !

In the **Settings - Preferences... - MISC** panel, uncheck the **Autodetect character encoding** option : It should be OK !

I already noticed, several times, that some **combination** of characters at the **very beginning** of a file, with that option **set**, may cause N++ to choose a **wrong** encoding ( **TIS-620**, in your case )

Unfortunately, I've **never** been able to figure out the **logic** and/or the **characters** which break down the **default** encoding of a file :-(

Best regards,

guy038

**Comment by inwaj** [comment]
It's not me. What do you think. I never subscribed in any thread. Sorry.
On Mar 28, 2016 6:47 PM, "THEVENOT Guy" <notifications@github.com> wrote:
>
> Hello gabrielsbarros,
>
> Sorry for this very, very late reply !
>
> In the Settings - Preferences... - MISC panel, uncheck the Autodetect
character encoding option : It should be OK !
>
> I already noticed, several times, that some combination of characters at
the very beginning of a file, with that option set, may cause N++ to choose
a wrong encoding ( TIS-620, in your case )
>
> Unfortunately, I've never been able to figure out the logic and/or the
characters which break down the default encoding of a file :-(
