### ISSUE TITLE
Vertical edges (column markers) disappear after after restart of np++

### ISSUE THREAD

**Issue by TipaRiordan** [notepad-plus-plus/notepad-plus-plus#13837]
### Description of the Issue

For some nasty old software I need the vertical edges (column markers) feature. After editing the respective settings field, they appear in my code window and stay there ... until I close np++. After starting it again, the vertical edges (column markers) are gone. To get them back, I have to at least open the settings dialog and enter a blank character at the end ... that brings them back.

### Expected Behavior

Once I've activated the column markers, the should be there until I deactivate 'em.
(I could live with the need to clkick a menu button to toggle the markers on/off)

### Actual Behavior
The column markers stay only for the current session, they're gone when I start up np++ next time.

### Debug Information

Notepad++ v8.5.3   (64-bit)
Build time : May 15 2023 - 06:09:36
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 10 Pro (64-bit)
OS Version : 22H2
OS Build : 19045.3031
Current ANSI codepage : 1252
Plugins : 
    BetterMultiSelection (1.3)
    BigFiles (0.1.1.1)
    CsvQuery (1.2.7)
    Explorer (1.8.7)
    ExtSettings (1.2.1)
    LanguageHelp (1.7.3)
    Linefilter3 (1)
    mimeTools (2.9)
    NppConverter (4.5)
    nppcrypt (1.0.1.6)
    NppEditorConfig (0.4)
    NppExport (0.4)
    NppFavorites (1.0.0.1)
    NppRegExTractorPlugin (2.1)
    NppToolBucket (1.10.6622.41516)
    NppUISpy (1.0.4)
    NppXmlTreeviewPlugin (2)
    Remove Duplicate Lines (1.2)
    RunMe (1.4)
    _CustomizeToolbar (4.2)

**Comment by alankilborn** [comment]
It's remembered just fine for me.  Suggestions: provide more detail on exact setup of vertical edge(s), try without plugins.

**Comment by donho** [comment]
I cannot reproduce it either.

**Comment by saustin99** [comment]
I've has the same problem for months now. I do the same thing to fix it. I wish they'd fix this.

**Comment by TipaRiordan** [comment]
Yippie ... finally another user suffering the same bug ...

Anybody around to reopen the issue ?
