### ISSUE TITLE
Notepad++ should stop supporting mass-murdering agendas

### ISSUE THREAD

**Issue by donotsdubba** [notepad-plus-plus/notepad-plus-plus#13843]
### Description of the Issue
Notepad++ main page should not push propaganda and agendas that demonstrably facilitate mass murder.

### Steps to Reproduce the Issue
1. Open https://notepad-plus-plus.org/
2. Search for string:
"By optimizing as many routines as possible without losing user friendliness, Notepad++ is trying to reduce the world carbon dioxide emissions. When using less CPU power, the PC can throttle down and reduce power consumption, resulting in a greener environment."

### Expected Behavior
Main page should not promote murder-enabling greenwashing.

### Actual Behavior
Current main page pushes factually-false agenda and braindead, extremely irresponsible, pseudo-scientific propaganda.

As of today, the main page for NotePad++ defends greenwashing propaganda which is being used to push the notion that, and I quote the actual institutions pushing it (UN, for instance), "human rights are a secondary right". It's disgusting to see the NotePad++ project appropriators (mislabelled as "author") engaging, promoting and pushing agendas that have nothing but genocide in mind.

While real climate issues exist, they scientifically have near-nothing (less than 1%) to do with "carbon footprint", see the renowned meteorologist Dane Wigington's [material and on-the-field coverage of the real cause for over a decade](https://www.geoengineeringwatch.org/), which is military-led climate engineering AKA geoengineering worldwide (US, China, Russia, Israel etc. all alike, and in bed together behind-the-scenes, demonstrably), and [the consequences](https://www.youtube.com/watch?v=GJpYLDSXTaA). If you look around, you will see a lot of declassified US army documents and patents demonstrating this, spanning across numerous decades. These are public, official documents.

Let's also not try to conveniently ignore [Spain's 2015 lead dioxide parliamentary revelation as seen on the EU parliament's website](https://www.europarl.europa.eu/doceo/document/E-8-2015-007937_EN.html), not to mention the [2020 official publication by the Spanish government directly regarding further such actions as per a UN program](https://www.boe.es/boe/dias/2020/04/17/pdfs/BOE-A-2020-4492.pdf) [last link being in Spanish, naturally, translate it if needed].

So when is the release of the **Notepad++** version "**9.0.0 - We were wrong about everything and humbly apologize**" coming? Cease from being a brainless, irresponsible, ignorance-spreading, murder-pushing, denialist TV parrot.

Also, let's see if you will even keep this issue and ALL (not just some) of the comments non-minimized or at all available, you self-proclaimed "free speech" advocators. According to your earlier comments [from 2022](https://github.com/notepad-plus-plus/notepad-plus-plus/issues/11153), YOU guys aren't hypocrites whatsoever. Right? Well, just behold your own actions revealing your true selves _now_ (rather, _again_).

**Comment by donotsdubba** [comment]
To further add to the issue, if you drop support for older OSes, as you have not too long ago for Windows XP, you hypocritically generate further "carbon footprint" due to promoting more of the older, incompatible hardware to go to the landfill despite being 100% serviceable. So even within the propagandized lunacy, there is dramatic inconsistency. Newer OSes, within this same thought process, should be outright discouraged, also because of the further resources they take. Not to mention the ever-increasing amount of 1st party keyloggers and other malware.

All such demonstrable, factual fallacy aside, OS compatibility is NOT to be trivialized in general: there are many genuine reasons to keep them well-served with our software, especially in the Libre Software domain.

**Comment by rimrul** [comment]
> Current main page pushes factually-false agenda and braindead, extremely irresponsible, pseudo-scientific propaganda.

Accusing others of being pseudo-scientific, while peddling highly unscientific chemtrail nonsense, that's my kind of troll account.

> I quote the actual institutions pushing it (UN, for instance), "human rights are a secondary right".

The only source for this quote I can find on google is this very issue. So it seems to be made up.

> While real climate issues exist, they scientifically have near-nothing (less than 1%) to do with "carbon footprint",

There is wide agreement among scientists that emissions of greenhouse gasses including CO2 are a huge cause of climate change. 


> see the renowned meteorologist Dane Wigington

Renowned meterologist is a big euphemism in this context. 

> Let's also not try to conveniently ignore [Spain's 2015 lead dioxide parliamentary revelation as seen on the EU parliament's website](https://www.europarl.europa.eu/doceo/document/E-8-2015-007937_EN.html), 

To quote the [answer to that ridiculous question](https://www.europarl.europa.eu/doceo/document/E-8-2015-007937-ASW_EN.html):

> The Commission has investigated the matter with the Spanish authorities and found no evidence of the allegations of a military geoengineering scheme for changing climate in Spain. 

> not to mention the [2020 official publication by the Spanish government directly regarding further such actions as per a UN program](https://www.boe.es/boe/dias/2020/04/17/pdfs/BOE-A-2020-4492.pdf) [last link being in Spanish, naturally, translate it if needed].

That document seems to be about COVID-19 measures and entirely unrelated.

**Comment by PPPDUD** [comment]
For those reading this thread later on:
# The facts
Notepad++'s commitment here is misguided at the very least. I don't think that the authors intended to support murderous causes though (it's a _text editor_ after all).

Geoengineering and military intervention are irrelevant factors here. A text editor has nothing to do with those things.

Let's just think about the primary idea a bit here. Most people don't actively run a text editor for more than 2 days, and rarely spend more than an hour actually doing stuff there (these numbers were just made up by me, but I think that they're pretty accurate in this scenario).

My entire computer runs at about ~120 watts, including the CPU (which has bad power optimization), and my massive NVIDIA GPU that nearly fills its whole case. For context, a beefy microwave oven running at full power can draw about 1000 watts.

A powerful computer draws less than my microwave, when both are doing their best work. Let that sink in for a moment. Ever wonder why you never saw a commercial for the latest smart microwaves?

Idling VSCode (a much more demanding, bloated editor) on my Ubuntu 25 machine uses about the same amount of power as if the program was closed.

I don't think that slightly improving an algorithm in a text editor is going to somehow improve carbon dioxide emissions any more than banning nonstop microwave usage.

I make no comments or arguments about geoengineering or military intervention here. Everybody's entitled to their own opinion.
