### ISSUE TITLE
[Windows] FileVersion output is different than visible in GUI context menu.

### ISSUE THREAD

**Issue by GrossiBP** [notepad-plus-plus/notepad-plus-plus#13842]
### Description of the Issue
On Windows when I look on the File Version it is differently presented than in the command line. In GUI it shows with dots between subversions while in Powershell without dots. Official version is marked as v8.5.4 and this could be continued when using commands.

### Steps to Reproduce the Issue
1. Open Powershell.
2. (Get-ChildItem -Path "$path_to_notepad\notepad++.exe").VersionInfo
3. (Get-ChildItem -Path "$path_to_notepad\notepad++.exe").VersionInfo.FileVersion or .ProductVersion
4. Right-click on notepad++.exe and go to Details. Compare the results.

### Expected Behavior
FileVersion should be like in GUI? 8.5.4

### Actual Behavior
FileVersion is 8.54

### Debug Information
Notepad++ v8.5.4   (64-bit)
Build time : Jun 17 2023 - 20:42:45
Path : E:\Tools\Notepad++\notepad++.exe
Command Line : 
Admin mode : ON
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows Server 2019 Standard (64-bit)
OS Version : 1809
OS Build : 17763.4499
Current ANSI codepage : 1252
Plugins : 
    mimeTools (2.9)
    NppConverter (4.5)
![8 54](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/3890611/3d1ea2c7-3b06-428c-bed9-0ad15e289583)

    NppExport (0.4)

**Comment by rdipardo** [comment]
It comes from here:

https://github.com/notepad-plus-plus/notepad-plus-plus/blob/1943ce87b59a5147932dbfaa0f9885332ab6b5a5/PowerEditor/src/Notepad_plus.rc#L45-L52

The "FileVersion" and "ProductVersion" fields are assigned the same value, `VERSION_VALUE`:

https://github.com/notepad-plus-plus/notepad-plus-plus/blob/1943ce87b59a5147932dbfaa0f9885332ab6b5a5/PowerEditor/src/resource.h#L24-L27

What File Explorer is showing as the "File version" is the 4 digits assigned to `VERSION_DIGITALVALUE`, above.

---

Duplicate of #11431

**Comment by GrossiBP** [comment]
I read all and still I hold to the previous ticket complain that it's quite confusing and creates unncesary effort to manipulate what is given on the official page and is actually inside hardcoded for version maintenance.

**Comment by mpheath** [comment]
> ### Expected Behavior
> 
> FileVersion should be like in GUI? 8.5.4

The file version in the Gui is `8.5.4.0` as what my eyes see. Powershell's `.FileVersion` does seem confusing as it is duplicating `.ProductVersion` for some reason.

Seems like Powershell might have a better method to get the version. Try `.FileVersionRaw`

```ps1
$path_to_notepad = 'C:\Programs Files\Notepad++'
$ver = (Get-ChildItem -Path "$path_to_notepad\notepad++.exe").VersionInfo.FileVersionRaw
"$ver"
$ver
```
Output
```
8.5.4.0

Major  Minor  Build  Revision
-----  -----  -----  --------
8      5      4      0
```
which shows the version as string and a table of all 4 segments of the version.

Compared to AutoIt

```au3
$ver = FileGetVersion('C:\Program Files\Notepad++\notepad++.exe')
ConsoleWrite($ver & @CRLF)
```
Output
```
8.5.4.0
```
which shows the version as string.

Notepad++ versioning seems ok to me.

**Comment by GrossiBP** [comment]
I think this is the very last and best option to take it out of the box at present state. Thanks for this "Raw" option. For some reason I missed that...
