### ISSUE TITLE
Style not saving properly when updating

### ISSUE THREAD

**Issue by optus23** [notepad-plus-plus/notepad-plus-plus#13851]
### Description of the Issue
Style not saving properly when updating

### Steps to Reproduce the Issue
1. Update Notepad++
2. Open Notepad++

### Expected Behavior

Not adding the style again every update.

### Actual Behavior
Style not saving properly when updating

### Debug Information
Notepad++ v8.5.4   (32-bit)
Build time : Jun 17 2023 - 20:40:14
Path : F:\DATA\PROGRAMS\Notepad++\notepad++.exe
Command Line : "F:\DATA\PROGRAMS\Notepad++\change.log" 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 10 Enterprise (64-bit)
OS Version : 22H2
OS Build : 19045.3086
Current ANSI codepage : 1252
Plugins : 
    mimeTools (2.9)
    NppConverter (4.5)
    NppExport (0.4)

**Comment by alankilborn** [comment]
I think you'll have to provide more detail to get anyone to understand the problem you're seeing.

**Comment by donho** [comment]
We need more information about your reporting. Do you mind add more description

**Comment by optus23** [comment]
Hey, sorry for the late reply.
Yes, I would love to give you more feedback.

This is how I use to have the style of Note++
[image: image.png]

When I update the software, it turns on this:
[image: image.png]

So I have to go to the Configuration and set the Neon theme again.
[image: image.png]

In my opinion, it is just a minor bug. But I hope it helps to create a
better software.
