### ISSUE TITLE
When Shutting Down Pop Up Window: "Error of saving session file"

### ISSUE THREAD

**Issue by joe2ishere** [notepad-plus-plus/notepad-plus-plus#13859]
### Description of the Issue

When closing the program,  Notepad++ has a problem saving the session file.  Thereby causing old session data presented when the program is restarted.

### Steps to Reproduce the Issue

1. Using v 8.5.4.
2. Simply close Notepad++ 
2.1  Get the pop-up message.
3. Restart Notepad++.
  3.1  An old session is presented.

### Expected Behavior

Notepad++ session closes successfully.  And when restarting Notepad++ the previous session is restored.

### Actual Behavior

Pop-up Window = Error of saving session file.   "The old session file will be restored".
 
When restarting the application an old session is started.
### Debug Information

Notepad++ v8.5.4   (64-bit)
Build time : Jun 17 2023 - 20:42:45
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : C:\Users\joe\Notepadd++ Session
OS Name : Windows 10 Pro (64-bit)
OS Version : 20H2
OS Build : 19042.1466
Current ANSI codepage : 1252
Plugins : 
    ComparePlugin (2.0.2)
    mimeTools (2.9)
    NppConverter (4.5)
    NppExport (0.4)

**Comment by joe2ishere** [comment]
I pasted the fail2load file in previous comment but don't see any text.

**Comment by donho** [comment]
@joe2ishere 
Thank you!
I just edited your post to make xml displayed.
I'll analyze it and give you a feedback later.

**Comment by joe2ishere** [comment]
Looking at the XML file, the filename attribute indicates the files that are restored when I restart NotePad++.    

These are not the files that I was editing in the latest session but from some session in the past.

**Comment by donho** [comment]
@joe2ishere 
Could you check if your **session.xml** in `%APPDATA%\Notepad++\` is Read-Only ?

![image](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/90293/03dad2f8-abf7-415b-a790-1148d3b34318)

**Comment by donho** [comment]
> So I ended up deleting all NotePad++ xml files inside a APPDATA folder that looked like a session file.

In this case, could you check if **session.xml.fail2Load** in `%APPDATA%\Notepad++\` is Read-Only please?

**Comment by joe2ishere** [comment]
It is not marked as Read-Only.

**Comment by TMS330** [comment]
I'm having the same issue, the Notepad++ folder is marked as readonly but the session.xml file is not. I've made several attempts to remove the readonly attribute from the notepad++ folder but it keeps changing back. I can't find session.xml.fail2Load anywhere under appdata just the session.xml under appdata/notepad++. What am I doing wrong.

**Comment by donho** [comment]
@TMS330 
> I'm having the same issue, the Notepad++ folder is marked as readonly but the session.xml file is not.

In my PC all the folders under %APPDATA% are read only, and I cannot remove it either, so it should not due to it.

> I can't find session.xml.fail2Load anywhere under appdata just the session.xml under appdata/notepad++. 

What's your version of Notepad++ ?

Could you zip your session.xml and send it to me (don.h@free.fr) please?

**Comment by TMS330** [comment]
My version is v8.5.4. Just updated today but this issue has been a problem for the past several versions. I'm using Windows10 home edition.
[session.zip](https://github.com/notepad-plus-plus/notepad-plus-plus/files/12022073/session.zip)

**Comment by donho** [comment]
@TMS330 
Thank you.
Could you provide also your Debug Info via menu `?->Debug Info...` ?

**Comment by TMS330** [comment]
I'm not familiar with that.

**Comment by TMS330** [comment]
I got it:
Notepad++ v8.5.4   (32-bit)
Build time : Jun 17 2023 - 20:40:14
Path : D:\Program Files (x86)\Notepad++\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : ON
Cloud Config : OFF
OS Name : Windows 10 Home (64-bit)
OS Version : 22H2
OS Build : 19045.3086
Current ANSI codepage : 1252
Plugins : 
    mimeTools (2.9)
    NppConverter (4.5)
    NppExport (0.4)

**Comment by TMS330** [comment]
Notepad++ v8.5.4 (32-bit)
Build time : Jun 17 2023 - 20:40:14
Path : D:\Program Files (x86)\Notepad++\notepad++.exe
Command Line :
Admin mode : OFF
Local Conf mode : ON
Cloud Config : OFF
OS Name : Windows 10 Home (64-bit)
OS Version : 22H2
OS Build : 19045.3086
Current ANSI codepage : 1252
Plugins :
mimeTools (2.9)
NppConverter (4.5)
NppExport (0.4)

    On Tuesday, July 11, 2023 at 08:07:03 PM EDT, Don HO ***@***.***> wrote:  
 
 


@TMS330
Thank you.
Could you provide also your Debug Info via menu ?->Debug Info... ?

**Comment by donho** [comment]
@TMS330 
Thank you.
I suppose that you don't have `session.xml.inCaseOfCorruption.bak` in you %APPDATA%\Notepad++\ directory?

**Comment by TMS330** [comment]
No, that file is not there. I Did manage to clear the 2 file that kept comming up as tabs by running as Administrator. When I exited there was no popup and when I restarted the tabs were cleared. However when I restart normally upon exit the popup comes back.
    On Wednesday, July 12, 2023 at 06:49:44 AM EDT, Don HO ***@***.***> wrote:  
 
 


@TMS330
Thank you.
I suppose that you don't have session.xml.inCaseOfCorruption.bak in you %APPDATA%\Notepad++\ directory?

**Comment by donho** [comment]
@TMS330 
I just saw this line from your Debug Info: 
`Local Conf mode : ON`

Did you add `doLocalConf.xml` into the path `D:\Program Files (x86)\Notepad++` ?

**Comment by TMS330** [comment]
Didn't know I was supposed to. Where'd you find that and what should the file contain. or is it a file that I should find somewhere?
    On Wednesday, July 12, 2023 at 07:17:14 PM EDT, Don HO ***@***.***> wrote:  
 
 


@TMS330
I just saw this line from your Debug Info:
Local Conf mode : ON

Did you add doLocalConf.xml into the path D:\Program Files (x86)\Notepad++ ?

**Comment by donho** [comment]
No, you are not suppose to do it. Could you remove **D:\Program Files (x86)\Notepad++\doLocalConf.xml** then try to close Notepad++ without Admin privilege please?

**Comment by TMS330** [comment]
Got the same popup about sessions
    On Thursday, July 13, 2023 at 04:29:18 AM EDT, Don HO ***@***.***> wrote:  
 
 


No, you are not suppose to do it. Could you remove D:\Program Files (x86)\Notepad++\doLocalConf.xml then try to close Notepad++ without Admin privilege please?

**Comment by donho** [comment]
@TMS330 
Could you copy the following binary and replace your notepad++.exe:
https://ci.appveyor.com/api/buildjobs/0jcgrebnr5w25m4c/artifacts/Notepad%2B%2B.x64.Release.exe

Launch Notepad++ and open some files then close Notepad++ - could you provide the screenshot of error message please?

**Comment by donho** [comment]
Related: #13894

**Comment by TMS330** [comment]
Got some error messages trying to open the new exe, something about the 64 bit version being incompatible with a couple of dlls and do I wish to remove the dlls to prevent these errors next time I try opening this exe. I responded no to each after which notepad++ opened with the two files that had been stuck before I ran it as administrator that cleared them. But upon closing notepad++ there was no error popup to get a screen snap. I attached the 3 error popups that appeared upon opening notepad++.
I appreciate all the time you're putting into this and wish I wasn't doing this in between a dozen other things so I'd have more time to pay attention to what is actually going on. So a heartfelt thanks to you. -t
    On Friday, July 14, 2023 at 06:37:21 AM EDT, Don HO ***@***.***> wrote:  
 
 


@TMS330
Could you copy the following binary and replace your notepad++.exe:
https://ci.appveyor.com/api/buildjobs/0jcgrebnr5w25m4c/artifacts/Notepad%2B%2B.x64.Release.exe

Launch Notepad++ and open some files then close Notepad++ - could you provide the screenshot of error message please?
