### ISSUE TITLE
Auto-completion prompt word completion 

### ISSUE THREAD

**Issue by z000dgfb** [notepad-plus-plus/notepad-plus-plus#13866]
### Description of the Issue
Using Notepad++ v8.5.4
When using the editor to type some documents, earlier it was possible to use ENTER to complete the word which is already existing earlier in the text, but now, the ENTER does not select the word, but enters to a new line. 

### Steps to Reproduce the Issue
1. Type a sentence like Hello world and go the next line
2. Start typing He, the autoprompt for word completion pops up, press ENTER 
3. Instead of completing the Hello, it moves to the next line, making editing difficult. 

### Expected Behavior
Hello word completes and cursor is post the word for continued editing

### Actual Behavior
He stops and editor cursor moves to the next line

### Debug Information
Notepad++ v8.5.4   (64-bit)
Build time : Jun 17 2023 - 20:42:45
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : "C:\Program Files\Notepad++\change.log" 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 10 Enterprise (64-bit)
OS Version : 21H2
OS Build : 19044.3086
Current ANSI codepage : 1252
Plugins : 
    mimeTools (2.9)
    NppConverter (4.5)
    NppExport (0.4)

**Comment by mpheath** [comment]
I can reproduce the behavior if the the *Insert Selection* option for the *ENTER* checkbox is unchecked in the Preferences dialog.

![npp_autoc_enter](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/58158242/52bcb6fb-2be1-4c50-8019-f50c2b3fdab4)

See the checkbox that the mouse curser is pointing to. Can you check your setting?

**Comment by z000dgfb** [comment]
Thanks Micheal, I have now enabled and got the functionality working. :)
