### ISSUE TITLE
Dark Mode and Style settings lost if opening a txt file rather than launching the Notepad++ directly from exe or shortcut

### ISSUE THREAD

**Issue by Ash88mph** [notepad-plus-plus/notepad-plus-plus#13879]
**DESCRIPTION OF THE ISSUE**
After I updated Notepad++ 3 versions ago (atm I am on the last available version, v.8.5.4) if I open a txt file directly, rather than launching Notepad++ first (trough the exe or a shortcut), the dark mode and style will not work anymore.
In the Preferences the ‘Dark Mode’ menu is not visible and in the Style Configurator the ‘default’ style is used rather than the dark mode that I usually use (Deep Blak).
It feels like that when opening a txt directly (rather than opening Notepad++ first) the settings are reverted back to default OR as if the Dark Mode is not available in the settings (and so both preferences and style are reverted back to the default Light theme).

**STEPS TO REPRODUCE THE ISSUE**
1. Launch Notepad++ from the exe or a shortcut.
2. Open the 'Preferences' window (Settings > Preferences) and in the 'Dark Mode' menu select the 'Dark Mode' option.
3. Click the 'Close' button at the bottom of the Preference window.
4. Open the 'Style Configurator' (Settings > Style Configurator) select a theme different than the 'default'  one: for example select the Deep Black theme.
5. Click the 'Save & Close' button at the bottom of the Style Configurator window.
6. Close Notepad++.
7. Open  Close Notepad++ and verify that both the Dark Mode and the dark theme are working: you can also open the Preference and Style Configurator windows to check that the options we previously set are still working.
8. Close Notepad++.
9. On your PC open any folder (for example in Documents) and create a txt file; name it whatever you like.
10.  Right click the txt and select 'Properties' from the right click menu.
11. In the 'General' tab set to 'Open with' Notepad++.
12. Click the 'OK'  button at the bottom of the Properties window.
13. Now double click the txt file to open it
14. When Notepad++ opens, notice that both the UI as well as the display style of the document are reverted back to the Light mode
15. Open the 'Preferences' window (Settings > Preferences) and notice that the 'Dark Mode' menu in the list on the left is not present.
16. Click the 'Close' button at the bottom of the Preference window.
17. Open the 'Style Configurator' (Settings > Style Configurator) and notice that the theme has been reset to the 'default' one.
18. Click the 'Cancel' button at the bottom of the Style Configurator window to close it.

**EXPECTED BEHAVIOR**
I would expect that when opening a txt (double clicking on it) Notepad++ would have the Dark Mode and Dark style that I previously set.

**ACTUAL BEHAVIOR**
When opening a txt (double clicking on it) Notepad++ revert back to the default Light Mode and default theme (that is light/white as well) rather than using the Dark Mode and Dark style that I previously set.

**DEBUG INFORMATION**
Notepad++ v7.8.1   (64-bit)
Build time : Oct 27 2019 - 22:57:19
Path : D:\Program Files\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS Name : Windows 10 Education N (64-bit) 
OS Version : 2009
OS Build : 19045.3086
Plugins : mimeTools.dll NppConverter.dll NppExport.dll 

**ADDITIONAL NOTES**
I have been using Notepad++ as my txt application for more than 10 years.
As soon as it was available I used the Daark Mode. Even before Dark Mode was available for the interface I almost always used a Dark style, because it hurt my eyes to read on a white background.

I am currently using Windows 10:
Edition:	Windows 10 Education N
Version:	22H2
OS build:	19045.3086
Experience:	Windows Feature Experience Pack 1000.19041.1000.0
![Windows Version](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/18327671/b3286bca-229a-44de-9049-53cc8cb71fcb)

**SCREENSHOTS**

**DARK MODE AND STYLE AS I SET IT UP**
!['Dark Mode' Menu in Dark Mode](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/18327671/ffcc4849-3ab7-4e5e-aaea-8aa1a4c29ad5)

!['Style Configurator' In Dark Mode](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/18327671/5fa338b9-c2d7-40cc-a7f7-fa6e95cd7950)

**WHEN OPENING NOTEPAD++ FROM A TXT**
![Opening a  txt File Instead of Launching Notepad++ Directly](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/18327671/08360f80-74c3-4c7a-8cf8-1bf73c561550)

![Missing 'Dark Mode' Menu in the Preferences](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/18327671/b9a91b61-4e1a-4e66-9ab2-89842380e1b8)

!['Style Configurator' Reset to Default When Opening a  txt Directly](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/18327671/fa33f83d-2f92-4f50-9be6-0ef04bf7b0ce)

**WHEN OPENING NOTEPAD++ FROM A EXE OR SHORTCUT**
!['Dark Mode' Menu in the Preferences is Present Launching Notepad++ Directly](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/18327671/a9b22153-362f-471b-9f2c-d01824737835)

!['General' Menu has More Options When Launching Notepad++ Directly](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/18327671/91ba7a4c-1123-4cdc-adf9-8397376e91b4)

**'OPEN WITH' SETTINGS IN THE TXT PROPERTIES**
![Open txt with Notepad++](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/18327671/77b5257f-5b81-4360-a7b9-de8c3176980e)

**Comment by alankilborn** [comment]
The symptoms here lead one to guess that you have TWO versions of Notepad++ on your machine, one is version 8.5.4 and the other is version 7.8.1.

**Comment by Ash88mph** [comment]
I am pretty sure I only have one version of Notepad++ installed.
A couple of days ago I also uninstalled Notepaad++ and reinstalled from scratch (but I kept the settings) just to see if that was fixing the problem.

Check the images below.

![Notepad++ Version (1)](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/18327671/840e40cd-23d6-4aa8-9dca-717bdf84f6c2)

![Notepad++ Version (2)](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/18327671/905668e2-f9f7-4719-87c5-a65a2873fb77)

![Notepad++ Version (3)](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/18327671/8adb5d0b-bfd8-449f-b537-16f70d932ae5)

------------------------------

An ADDITIONAL NOTE regarding the issue, that might be helpful.
After reporting the but earlier today I looked at the Notepad++ Preferences and I found a workaround !

1. Launch Notepad++ as admin.
2. Open the 'Preferences' window (Settings > Preferences) and in the 'File Association' add .txt and .ini to the 'Registered Extensions'.
3. Click the 'Close' button at the bottom of the Preference window.

With these new settings, if I close Notepad++ and I doubleclick any .txt or .ini file to open Notepad++ the dark mode and style are properly used/displayed.

![File Association](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/18327671/c3872067-9735-4e66-8b12-660a0d8f4ae4)

**Comment by alankilborn** [comment]
>It might be that is picking that version up from the preferences file?

No.  When you "associate" in Windows, the 7.8.1 version is getting picked.

**Comment by Ash88mph** [comment]
Damn, you are right! 
It was the file association in txt properties that was pointing at the old version.

Now with the new association it opens the correct version 8.5.4.
![Notepad++ Version 8 5 4](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/18327671/99d8ba86-c07b-4233-98d5-8bd3cbee145d)

Thank you so much for the help [alankilborn](https://github.com/alankilborn) !

**Comment by alankilborn** [comment]
Please close this issue.
(You also might want to seek out and manually remove the 7.8.1 version on your system!)

**Comment by Ash88mph** [comment]
Yeah I finally found where the other installation was ! 
All done, issue closed !
