### ISSUE TITLE
Brace matching style dos not appear to work on files over 5 million

### ISSUE THREAD

**Issue by stitlown** [notepad-plus-plus/notepad-plus-plus#13876]
### Description of the Issue
Brace matching style does not appear to work on very large files - in this case a file of 10 million lines

### Steps to Reproduce the Issue
1. Uninstalled and re-installed latest NPP.
2. With a smaller file and the big file open at the same time, Brace matching is working in the smaller file (14,000 lines) but not in the big file.
3. re-opened NPP with plugins folder renamed - same behaviour / issue
4. Using the "sledgehammer" approach of deleting lines / saving / restarting, I've found that the issue resolves at under 5,000,000 lines but is present above 7,500,000 lines

### Expected Behavior
The usual "matching braces" where the dotted "Matched Brace" line in the "show indent guide" view turns red to illustrate the span of the matching brace set.

### Actual Behavior
No red indent guide lines for any set of matching braces, small span or large span.

In addition, the  "Style Configurator" appears to default to "Global override" and the "save and close" box in that dialogue greys out.

### Debug Information
Notepad++ v8.5.4   (64-bit)
Build time : Jun 17 2023 - 20:42:45
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : "T:\Daz Library\A-Daz Scenes\PrisonXIVM\PrisonXIVM.duf"
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 10 Pro (64-bit)
OS Version : 21H2
OS Build : 19044.3086
Current ANSI codepage : 1252
Plugins : 
    mimeTools (2.9)
    NppConverter (4.5)
    NppExport (0.4)

**Comment by alankilborn** [comment]
What is your setup here?:

![image](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/77065706/a6a275bd-60ad-40bf-bd1d-27917f2b43fc)

**Comment by stitlown** [comment]
Thanks - all my error / inexperience.  Ticking the "Allow brace match" box fixes the issue.  Cheers.
