### ISSUE TITLE
"Clear Change History": cloned document markers are not cleared

### ISSUE THREAD

**Issue by Yaron10** [notepad-plus-plus/notepad-plus-plus#13877]
**STR:**
Clone a dirty document to the other view.
"Clear Change History".

**Result:**
The History markers in the other view are visible until you activate it.

**Ref:** https://github.com/notepad-plus-plus/notepad-plus-plus/pull/13861#issuecomment-1627375067.

***

Master: https://github.com/notepad-plus-plus/notepad-plus-plus/commit/ebdc910dcd7bf0577b8d54f6c6cb0fd2e1f6f703.

**Comment by Yaron10** [comment]
@donho,

👍 
Very nice!

Allow me two _minor_ questions:
1. `clearChangesHistory()` is called on Reload as well, and in that case both `checkUndoState();` & `_pNonEditView->redraw();` are not needed.
Wouldn't it be better to move both lines to `case IDM_SEARCH_CLEAR_CHANGE_HISTORY:`?
```cpp
		case IDM_SEARCH_CLEAR_CHANGE_HISTORY:
			clearChangeHistory();
			checkUndoState();
			_pNonEditView->redraw();
			break;
```

2. Is there a reason not to use `execute()`?
```cpp
void Notepad_plus::clearChangesHistory()
{
	intptr_t currentPos = _pEditView->execute(SCI_GETCURRENTPOS);
	int chFlags = (int)_pEditView->execute(SCI_GETCHANGEHISTORY);
	_pEditView->execute(SCI_EMPTYUNDOBUFFER);
	_pEditView->execute(SCI_SETCHANGEHISTORY, SC_CHANGE_HISTORY_DISABLED);
	_pEditView->execute(SCI_SETCHANGEHISTORY, chFlags);
	_pEditView->execute(SCI_GOTOPOS, currentPos);
}
```

Thank you for your work.

**Comment by donho** [comment]
@Yaron10 
For answering your question:
1. It could be. But I don't see so far the advantage to do so. Contrarily if we use `clearChangeHistory()` again in another place, we have to also add these 2 calls.
OTOH, `clearChangeHistory()` is a method of `Notepad_plus`, but not of ScitillaEditView, so I feel it's legit to put the 2 calls rather in `clearChangeHistory()`. 
2. You're absolutely right! It's better to use `execute` than `SendMessage`

**Comment by Yaron10** [comment]
@donho,

Thank you for the explanation.

> But I don't see so far the advantage to do so.

Those calls are redundant on Reload. 

> Contrarily if we use clearChangeHistory() again in another place, we have to also add these 2 calls.

That's a good point.

Anyway, it was a minor question.
