### ISSUE TITLE
Could u pls add Dart/kotlin format doc suport to npp?

### ISSUE THREAD

**Issue by petercao** [notepad-plus-plus/notepad-plus-plus#13880]
### Steps to Reproduce the Issue

1. 
2. 
3. 

### Debug Information

Could u pls add Dart/kotlin format doc suport to npp?
*.kt,

**Comment by rdipardo** [comment]
Duplicate of &mdash; at least &mdash; #13700, #13179, #12638, #3708, #3266 and ScintillaOrg/lexilla#58
