### ISSUE TITLE
Context menu "edit with Notepad++" has lost mnemonic (shortcut key)

### ISSUE THREAD

**Issue by ghueller** [notepad-plus-plus/notepad-plus-plus#13896]
### opening remark
I'm writing specifically for the German translation but I did not add German to the title because maybe it is a generic problem... feel free to update

### Description of the Issue
The Windows context menu "edit with Notepad++" is, in German: "Mit Notepad++ bearbeiten"
for years, the "N" was a mnemonic i.e. shortcut letter so that letter was underlined and pressing "N" would invoke this menu item (without having to use the mouse or cursor keys).
Since a few weeks, this mnemonic is lost.
(In my case, it is now occupied by some dropbox stuff so whenever I press the shortcuts I always pressed, I delete a file and move it to dropbox)

Please bring the mnemonic back!

AFAIK, in Windows it is usually configured with "&" in front of the letter and the rest (display, keyboard handling) is done by windows it self
so the menu item should probably be:
"Mit &Notepad++ bearbeiten"

NB I see there has been an initiative to translate this menu item into many languages:
https://github.com/notepad-plus-plus/notepad-plus-plus/issues/13201
It seems to me that the mnemonic was lost during that initiative

**Comment by GurliGebis** [comment]
I just tested it, and adding an ampersand in front of Notepad does not work in the new context menu, so I'm not sure this is the correct solution.
From what I can see, there is no way to do it in the new menu (I just checked several other programs I have installed with the menu, and none of them has an accessor key).

**Comment by donho** [comment]
I would say it's the limitation of OS.
While Windows 11 doesn't open this possibility, we can do nothing about it.

**Comment by GurliGebis** [comment]
@donho we can do it in the resource file, so the classic menu handler has the feature.
Then, if Microsoft starts to support it, it should "just work" in the new menu.

**Comment by donho** [comment]
@GurliGebis 
We can always do such way but there's no warranty that MS will implement it in this way.
Let's wait until this job is done by MS so we won't waste our time for it.
