### ISSUE TITLE
Save session error pops up and closes NPP before file is saved

### ISSUE THREAD

**Issue by loojo547** [notepad-plus-plus/notepad-plus-plus#13894]
### Description of the Issue
NPP opens and a file is loaded/ opened. When the file is modified an error pops up and the program closes without saving any changes to the file.

### Steps to Reproduce the Issue
1. Open NPP 
2. Load file
3. Make changes to file
4. Error pops up and within seconds the whole program closes, the changes in the file is not saved 

### Expected Behavior
Being able to change the file without the error and abrupt closure of the program.

### Actual Behavior
Pop-up Window = Error of saving session file. "The old session file will be restored". Program window closes abruptly.

### Debug Information
Notepad++ v8.5.4   (64-bit)
Build time : Jun 17 2023 - 20:42:45
Path : D:\bin\Notepad++\notepad++.exe
Command Line : "D:\projects\LIMA\Test\PAW\paw.bat" 
Admin mode : OFF
Local Conf mode : ON
Cloud Config : OFF
OS Name : Windows Server 2019 Standard (64-bit)
OS Version : 1809
OS Build : 17763.4499
Current ANSI codepage : 1252
Plugins : 
    mimeTools (2.9)
    NppConverter (4.5)
    NppExport (0.4)

![image](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/139502557/0aee5a43-e58f-481b-a4c1-d81eb70bdbaa)

**Comment by donho** [comment]
@loojo547 
Could you copy the following binary and replace your notepad++.exe:
https://ci.appveyor.com/api/buildjobs/0jcgrebnr5w25m4c/artifacts/Notepad%2B%2B.x64.Release.exe

Launch Notepad++ and open some files then close Notepad++ - could you provide the screenshot of error message please?

**Comment by loojo547** [comment]
@donho 
Thank you for getting back to me so quickly. This is a screenshot of the error message

![image](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/139502557/54dc613d-2c44-4f4f-b702-4ac8226b07ff)

**Comment by donho** [comment]
@loojo547 
I need more information:
1. Is it the only message box you've got?
2. Is `D:\bin\Notepad++\` directory read-only?
3. Does the file `D:\bin\Notepad++\doLocalConfig.xml` exist?

**Comment by loojo547** [comment]
@donho 

1. Yes this is the only message box I get when I modify the file in NPP
2. Is D:\bin\Notepad++\ directory read-only? --> yes it is, have changed it to Not read-only --> now the session is restored correctly when I open NPP with the binary you provided, but not when I use the existing .exe file (where I still get an error "
![image](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/139502557/b57d1d57-5f1d-4af9-acaf-ae9be62de20c)
")
3. Does the file D:\bin\Notepad++\doLocalConfig.xml exist? --> yes it does

Thank you for All your help

**Comment by donho** [comment]
> Is D:\bin\Notepad++\ directory read-only? --> yes it is, have changed it to Not read-only -->

Great.

> now the session is restored correctly when I open NPP with the binary you provided, but not when I use the existing .exe file (where I still get an error "
image
")

It seems you launch the old binary - the new binary show the different message.
Could you check it please?


Anyway, could you zip `session.xml.fail2Load` and upload it here please?

**Comment by loojo547** [comment]
sorry about that, tried opening and changing a file again
when launching with new binary I get these two error pop ups
![image](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/139502557/dbb67144-ed32-44d6-8e86-51eebf77cc8f)

![image](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/139502557/560a48ad-a827-4d95-9b3c-1842a92abf9e)

Unfortunately, there is no  session.xml.fail2Load  file only these
![image](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/139502557/4c0b21d8-dc58-42f5-8144-fd03b1ab1966)

**Comment by loojo547** [comment]
Hi @donho 
Thank you for your help thus far. The `session.xml` is not read-only, the directory `D:\bin\` is read-only and therefore if the `D:\bin\Notepad++\` directory is not read-only this change will be reset.
