### ISSUE TITLE
Changing text encoding does not work after version 8.4.7

### ISSUE THREAD

**Issue by newnews** [notepad-plus-plus/notepad-plus-plus#13905]
### Description of the Issue

Changing text encoding does not work after version 8.4.7
### Steps to Reproduce the Issue

1.  open a text file, it always shows OEM-US regardless of actual encoding
2.  go to encoding, select UTF-8 or other encoding type
3.  Nothing has been changed

### Expected Behavior

Should change to selected encoding
### Actual Behavior

no change at all
### Debug Information

Notepad++ v8.4.7   (32-bit)
Build time : Nov  1 2022 - 23:29:20
Path : D:\Tools\Notepad++847\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : ON
Cloud Config : OFF
OS Name : Windows 10 Enterprise (64-bit) 
OS Version : 22H2
OS Build : 19045.3208
Current ANSI codepage : 1252
Plugins : 
    mimeTools (2.9)
    NppConverter (4.5)
    NppExport (0.4)

**Comment by rdipardo** [comment]
> 1. open a text file, it always shows OEM-US [...]

Are you talking about *.nfo files? #9153
