### ISSUE TITLE
regression on the Style token feature (it do not highlight all occurrences of the text selected)

### ISSUE THREAD

**Issue by Omaroovitch** [notepad-plus-plus/notepad-plus-plus#13910]
### Description of the Issue
When selecting a text then right click on it, after apply a "Style token" after choosing a style, the color or the style is not applied on all occurrences of the text selected. However in an old version of Notepad (like v7.6.3) this feature is working fine.

### Steps to Reproduce the Issue
1. select a text in the opened file
2. right click on it
3. move through the menu appeared to the section "Style token"
4. choose a style

### Expected Behavior
All occurrences of the text selected is highlighted with the color or the style selected.

### Actual Behavior
not all occurrences of the text selected is highlighted with the color or the style selected.

### Debug Information
Notepad++ v8.5.4   (64-bit)
Build time : Jun 17 2023 - 20:42:45
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 10 Enterprise (64-bit)
OS Version : 22H2
OS Build : 19045.3208
Current ANSI codepage : 1252
Plugins : 
    CodeAlignmentNpp (14.1.107)
    ComparePlugin (2.0.2)
    IndentByFold (0.7.3)
    JSMinNPP (1.2205)
    mimeTools (2.9)
    nppAutoDetectIndent (2.3)
    NppConverter (4.5)
    nppcrypt (1.0.1.6)
    NppExport (0.4)
    NppFTP (0.29.12)
    NPPJSONViewer (2.0.5)
    nppplugin_svn (3.0.1)
    NppQrCode64 (0.0.0.1)
    NppTextViz (0.4.2)
    NppXmlTreeviewPlugin (2)
    XMLTools (3.1.1.13)

### Screen shot
Below a comparison of the behavior or result of this feature between two different versions of Notepad++:
Version: 8.5.4
![image](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/140070210/31456fcd-12ee-4db2-8d4b-c22842bee86f)

Version: 7.6.3
![image](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/140070210/2a8da617-70ec-4236-9303-9db1d8b6e797)

Thank you for your valuable efforts !

**Comment by alankilborn** [comment]
Adjust your settings to your liking, here:

![image](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/77065706/0caad832-fa3e-4746-987e-97c703ac45b5)

Please CLOSE this issue.

**Comment by Omaroovitch** [comment]
Thank you dear, 
It's okay now when uncheck the below option:

![image](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/140070210/d168385f-6e48-4c12-82e3-203894490225)
