### ISSUE TITLE
"Last Used Directory" may not be saved to config.xml

### ISSUE THREAD

**Issue by Yaron10** [notepad-plus-plus/notepad-plus-plus#13914]
**STR:**
Use the binary of https://github.com/notepad-plus-plus/notepad-plus-plus/commit/ff2179aeca7b708f5c3d0dd8aa1faeec10b84005 (IMPORTANT: rename it notepad++.exe).
Preferences -> Default Directory: select "Last Used Directory".
Open a file in "foo".
Exit NPP.
Delete config.xml.
Select "Last Used Directory".
File -> Open ("foo" is the folder).
Exit NPP.

**Result:**
The `lastUsedDirPath` field in config.xml is empty.

**Ref:**
https://github.com/notepad-plus-plus/notepad-plus-plus/pull/13887#issuecomment-1645258885.

@donho,

Could you please try it?

***

Notepad++ v8.5.4   (64-bit)
Build time : Jul 21 2023 - 09:35:05
Path : ---\npp.8.5.4.portable.x64\notepad++.exe
Command Line : 
Admin mode : ON
Local Conf mode : ON
Cloud Config : OFF
OS Name : Windows 10 Pro (64-bit)
OS Version : 20H2
OS Build : 19042.985
Current ANSI codepage : 1255
Plugins : 
    mimeTools (2.9)
    NppConverter (4.5)
    NppExport (0.4)

**Comment by Yaron10** [comment]
@alankilborn,

May I ask to try reproducing it on your machine?

Thank you!

**Comment by donho** [comment]
@Yaron10 
By using the same config as yours:
```
Admin mode : ON
Local Conf mode : ON
```
I cannot still reproduce this bug.

OTOH, when I check the code, the last used dir cannot be empty while the dialog is shown and the use last dir is ON.
I'm out of idea how & why it is happening in your PC - there must be a very special config on your PC or manipulation from you.

**Comment by alankilborn** [comment]
>May I ask to try reproducing it on your machine?

Following @Yaron10 's exact steps **I CAN reproduce his result**.
I'm not sure what it means, however :-)

Notepad++ v8.5.4   (64-bit)
Build time : Jul 21 2023 - 09:35:05
Path : C:\NotepadPlusPlus\Misc\_NoBackup\Releases\npp.8.5.4\New Folder\Notepad++.exe
Command Line : 
Admin mode : ON
Local Conf mode : ON
Cloud Config : OFF
OS Name : Windows 11 Pro (64-bit)
OS Version : 22H2
OS Build : 22621.1992
Current ANSI codepage : 1252
Plugins : 
    mimeTools (2.9)
    NppConverter (4.5)
    NppExport (0.4)

**Comment by Yaron10** [comment]
@donho,

Thank you for looking into it. 👍 

I'd like to make sure we're on the same page.

Preferences -> Default Directory: select "Last Used Directory".
**Open a file in "foo".**
Exit NPP.
Delete config.xml.
Select "Last Used Directory".
**File -> Open ("foo" is the folder). Just open the dialog. Do NOT open a file in "foo".** 
Exit NPP.

After deleting config.xml, relaunching NPP and opening the Open dialog - is "foo" the displayed folder?

***

@alankilborn,

Thank you for testing and confirming. 👍 

> I'm not sure what it means, however :-)

`lastUsedDirPath` should contain the last used folder if we don't want to rely on Windows handling it.
See https://github.com/notepad-plus-plus/notepad-plus-plus/pull/13887#issuecomment-1643672108 & Don's reply.

**Comment by donho** [comment]
@Yaron10 
>  Just open the dialog. Do NOT open a file in "foo".

OK, I see.
Now I can reproduce it. Thank you.

Could you validate https://github.com/notepad-plus-plus/notepad-plus-plus/pull/13918 please?

**Comment by Yaron10** [comment]
@donho,

Very nice! 👍 
Thank you for your time and work.

Two points:
1. Assigning a randomly browsed folder in the Open dialog (i.e. no file was actually opened in that folder) to "Last Used Directory" is unlike Windows native behavior. - You can test it in (e.g.) MS-Paint.
But I'm not sure NPP should follow Windows native behavior.

2. After deleting config.xml, relaunching NPP, selecting "Last Used Folder" and opening the Open dialog - the displayed folder might NOT be the one before deleting config.xml. it's either the one saved by Windows, or NPP installation folder. 
Perhaps not ideal but certainly legit.

Summery:
Great work.

**Comment by donho** [comment]
@Yaron10 
Thank you for your checking and remark!
