### ISSUE TITLE
Wish for a bit easier way to select file in Recent Files list, by keyboard

### ISSUE THREAD

**Issue by victorel-petrovich** [notepad-plus-plus/notepad-plus-plus#13920]
Currently, to open a recent file after the combo "alt+F", you need to *move* your yes to the left (long pathsnames), remember a number and then press that. 

I think it would be easier to have a key that to press after "alt-F" that would jump selection to the first file in the list, or to a header of the list, allowing you to use up-down arrow keys to select the desired file.
I've seen it so in other editors, like Geany, and I found it more convenient. 

Possible solutions: 

1. make pressing key 1 just select first file in list, without actually opening it before your press Enter 
2. ~make a Header for that recent file list (say Recent Files), one of whose letters can be used after "alt-F" to jump there. This could either make jump again directly to 1st file, like a) above, or: That could allow the list to be hidden in submenu -- probably a good thing in itself for *info hiding* when you're NOT looking for recent files . That submenu would automatically open when the header's access key (letter) is pressed, and you could again use key arrows up-down to select your file.~

EDIT: after the reply I got, I realize I missed that there is option to put the recent files in submenu, via in Preferences -> Recent Files History . But still, issue is still that accessing them is *not optimal*, because: 
Can't find how to change the short-cut letters associated with subentries in menu->File (ex, to make only "Recent Files" be mapped to "R" or "F").

**Comment by alankilborn** [comment]
You should probably checkmark this box in _Settings_ (menu) > _Preferences..._ and reevaluate your issue description:

![image](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/77065706/c5584160-8921-4d91-a6f1-a6acb2b38bfc)

But, wait...  after doing this there are TWO entries in the _File_ menu that have Alt+r as a shortcut:  _Rename_ and _Recent Files_.  😒

If you want to go to the trouble of removing the underline from _Rename_, then I think maybe you achieve a lot of your goal, for example, Alt+f (then keep Alt held) and press r gets you to this point:

![image](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/77065706/1e1d9f2e-1d77-46de-ac53-6802f8e70b89)

**Comment by victorel-petrovich** [comment]
Ah, thanks, I didn't notice that option in Settings to enable that submenu. Enabled it now. 

> But, wait... after doing this there are TWO entries in the File menu that have Alt+r as a shortcut: Rename and Recent Files. 😒

This would be less of a problem if, upon pressing "R" a second time, that submenu for recent files would open without waiting for "enter" or "right-arrow".

> If you want to go to the trouble of removing the underline from Rename, then I think maybe you achieve a lot of your goal, for example, Alt+f (then keep Alt held) and press r gets you to this point:

I'm interested, how? 
Because I just spent a long time trying to follow https://github.com/notepad-plus-plus/notepad-plus-plus/issues/5128#issuecomment-446190141   and it didn't work, my edits were ignored. Even though I tried editing in both "english.xml" and "english_customizable.xml", both in portable and installed version; for latter, both in %AppData% and in installation directory.

**Comment by victorel-petrovich** [comment]
Okay, through trial and error found that the first steps should be: 
1. menu -> Settings -> Preferences -> General -> Localization: change to "english (customizable)" (or any other language than "english").  But for that, when you install (if you install) N++ need to make sure you select that language to be available! 
2. Then you need to open nativeLang.xml from where user data is stored (%AppData%\Notepad++ if install) 
3. now, finally, do those edits to menu items names...

**Comment by alankilborn** [comment]
>found that the ... steps should be

The correct steps are:

* Edit `English (customizable)` to include the change you wish to make (and save it) -- no problem with doing this while Notepad++ is running, BTW
* Settings -> Preferences -> General -> Localization: change to `English (customizable)`

Leave `nativeLang.xml` alone as Notepad++ manages that (when you change _Localization_)

**Comment by victorel-petrovich** [comment]
@alankilborn  That doesn't work, after using the Installer. 
I tried your steps and also read in details the documentation, both https://npp-user-manual.org/docs/preferences/ ad https://npp-user-manual.org/docs/binary-translation/, 

Here's the catch: if I only have "english_customizable.xml" and "english.xml"  in folder "localization" (created by me) in "%AppData%\Notepad++", then there is no `English (customizable)` option in Settings -> Preferences -> General -> Localization. 

On the other hand, if I have have "english_customizable.xml" in folder "localization" in (default) install directory, in addition to in my %AppData%\Notepad++ one, then yes, that option is present there, BUT: my edits in the local "english_customizable.xml" are not taken in consideration. I have to edit the version in "installdir\localization" folder for it to have effect. 

So it behaves as if it first looks for the localization folder only in install directory.

So, it contradicts https://npp-user-manual.org/docs/binary-translation/ .

**Comment by victorel-petrovich** [comment]
those steps in doc don't work, I explain here https://community.notepad-plus-plus.org/topic/13762/disable-menu-activation-for-a-shortcut/11?_=1690241227100 , because more viewers here I guess.
