### ISSUE TITLE
Closing Notepad++ on a VM Image crashes with unknown error

### ISSUE THREAD

**Issue by GryphonJax** [notepad-plus-plus/notepad-plus-plus#1392]
When working on a VM Player 12 image and I close Notepad++, the application exits with an unknown error message, and I must manually kill the remaining process in Task Manager. This does not happen when I am using my workstation, only for the VM. In both cases, I am running on Windows 7.

Notepad++ 6.8.8.0, 12/9/2015 7:12 PM

**Comment by donho** [comment]
@GryphonJax  could you provide debug info via menu "?->Debug Info" ?
