### ISSUE TITLE
Suggestion: in "Recent Files" submenu, move individual files to the top, and the other 3 options - either out or to the bottom

### ISSUE THREAD

**Issue by victorel-petrovich** [notepad-plus-plus/notepad-plus-plus#13925]
That is, I mean after you check in Preferences -> Recent Files History -> Display -> "In Submenu"

This way, it will be consistent with how the menu->File looks when the option above is un-checked. 

Why: you will faster get to select the required recent file. 

Alternatively: move the other 3 options from the submenu to the menu->File, under the subentry "Recent Files" and above "exit".

**Comment by alankilborn** [comment]
Comments apply to current release version of Notepad++, specifically, 8.5.4.

**Comment by Yaron10** [comment]
> This way, it will be consistent with how the menu->File looks when the option above is un-checked.

👍

**Comment by alankilborn** [comment]
Or, leave these 3 in the _File_ menu:

* Restore Recent Closed File
* Open All Recent Files
* Empty Recent Files List

And have only (numbered) recent files listed in the submenu.

**Comment by victorel-petrovich** [comment]
I think the 2nd alternative is better, as it will make possible to navigate the files with arrows from both up and down direction, not having to skip over those 3 options, thus faster.

This seems like something easy; even though I'm not a C++ programmer, I think I could figure it out... But I've no idea where's the the menu structure coded. I browsed https://github.com/notepad-plus-plus/notepad-plus-plus/tree/master and ... no clue. 

If someone would guide a little, I'd try.

**Comment by alankilborn** [comment]
@victorel-petrovich It sure seems like this would be a good place to start looking in the code: https://github.com/notepad-plus-plus/notepad-plus-plus/blob/master/PowerEditor/src/lastRecentFileList.cpp

**Comment by victorel-petrovich** [comment]
It turns out it's a lot more complicated than I thought.
(functions and overall program logic are not explained/documented; very few explanatory comments, and I don't know this messy C++ lang)
 
So, I'll pass.

**Comment by victorel-petrovich** [comment]
The other alternative, of just moving to the bottom the 3 options (Restore Recent Closed File, Open All Recent Files, Empty Recent Files List) should be easier to do. 
But I still have a few questions I can't anwer.

I've set up a forked repository and pushed there a version of lastRecentFileList.cpp with my comments of what I understand and the questions. See https://github.com/victorel-petrovich/notepad-plus-plus/commit/57a88958fde7061af81ad3979b4933a099c8ed7f 
I guess "we" can discuss there under commit, can add comments. 
@alankilborn  , maybe you could have a look ?

**Comment by victorel-petrovich** [comment]
I just thought that the other alternative, of just moving to the bottom the 3 options (Restore Recent Closed File, Open All Recent Files, Empty Recent Files List) should be easier to do. 

But I still have a few questions I can't anwer.

See https://github.com/victorel-petrovich/notepad-plus-plus_lastRecentFileList.cpp/issues

I guess "we" (whoever is interested ) can discuss there , took keep this thread about the feature-proposal itself. 
But let me know if you think it's ok/better here. 

@alankilborn   @Yaron10  , maybe you could have a look ?

**Comment by Yaron10** [comment]
@victorel-petrovich,

Thank you for your work.

If you submit a PR or build a binary on AppVeyor, I'd be glad to test and discuss it.

Good luck.

**Comment by victorel-petrovich** [comment]
@ozone10 , as you have some experience with menus in Npp, could you answer some questions I'm stuck at? They are here: 
https://github.com/victorel-petrovich/notepad-plus-plus_lastRecentFileList.cpp/issues
First the closed issue there, where I think a particular line of code is unnecessary, but it would be good if someone else confirms.
Then the open issue.

**Comment by victorel-petrovich** [comment]
I've finally figured out what confused me all these days. The code is very misleading for someone who has no experience with menus. Also my mistake to believe I could understand it just by reading the code. 
Changes are in progres :)

**Comment by alankilborn** [comment]
>for someone who has no experience with menus...

>...The code is very misleading

Yes, the appropriate thing to do in such a case is to blame the code.  Oh boy.

**Comment by victorel-petrovich** [comment]
@alankilborn  , because the code uses a sort of hack, rather than what would be straitforward to use based on the documentation of the particular functions in case (which I had read from the beginning!). 

So, for example, to insert in submenu at position 0, for example, the code doens't specify position `0`, but some `_posBase`, where `_posBase` is some random number (22). 
But it works, because, apparently (I haven't found this documented), if you insert at a position greater than where last item resides ,then automatically it results in inserting immediatedly after that last item.

**Comment by alankilborn** [comment]
>the code uses a sort of hack

Maybe a hack, maybe not.  I'd lean towards not, with the likelihood that you just don't understand it.
But, if you think it is a needless hack, and you are changing the code, it is your job to remove the hack.

**Comment by victorel-petrovich** [comment]
@alankilborn  
> > is some random number (22)
> 
> I doubt this is a "random" choice...

common, that was simply to mean that the particular number is not relevant for the point I'm illustrating (of course it's not totally random ). But it could have been 10000 and still what I wrote above stands.

**Comment by victorel-petrovich** [comment]
That was done to save the need for a if -else or conditional operator (ternary) to specify position 0 in case of submenu... But at the cost of clarity for readers of the code. Wish there was at least a little comment saying, hey, the items will still result at the top of submenu.
 I wasted so much time trying to understand.
> Yes, the appropriate thing to do in such a case is to blame the code. Oh boy. 

I blame myself too, as I wrote above. 

Life lesson, moving on.

**Comment by Yaron10** [comment]
https://github.com/notepad-plus-plus/notepad-plus-plus/blob/f6e1b2cab6b42530869f600121443350f0292ad6/PowerEditor/src/menuCmdID.h#L81

It's "kind of random" in sub-view-mode.

@victorel-petrovich,

Have you tried https://github.com/victorel-petrovich/notepad-plus-plus_lastRecentFileList.cpp/issues/5#issuecomment-1673650489?

**Comment by victorel-petrovich** [comment]
@alankilborn 
> But, if you think it is a needless hack, and you are changing the code, it is your job to remove the hack.

oh, I will !

@Yaron10 
> Have you tried https://github.com/victorel-petrovich/notepad-plus-plus_lastRecentFileList.cpp/issues/5#issuecomment-1673650489? 

Have a little patience, I needed to vent a bit first... :D

**Comment by victorel-petrovich** [comment]
OK, one alternative (just reverse files w/ the 3 commands in submenu) is done!
Artifact here https://ci.appveyor.com/project/victorel-petrovich/notepad-plus-plus-lastrecentfilelist-cpp/build/artifacts
(let me know if you can't access or you can't run 32 bit; my guess is that 64bitWin should run it) 

Code here https://github.com/victorel-petrovich/notepad-plus-plus_lastRecentFileList.cpp/blob/fddf328bc3e9ba09ec5e6dd582f3050687e472ab/PowerEditor/src/lastRecentFileList.cpp
(main changes in updateMenu() )

**Comment by donho** [comment]
I'm not for changing a correct behaviour (personally, I prefer such behaviour) by taking the regression furthermore.
Such behaviour won't be implemented in Notepad++.

**Comment by victorel-petrovich** [comment]
@donho  , we're talking about 2 possible alternatives here; one just mentioned, and the other: 
* with only actual recent files in submenu, and those 3 commands currently in submenu (Restore Recent Closed File, Open All Recent Files, Empty Recent Files List ) -- to stay in main menu?

The point is to make it faster to access the recent files, by keyboard up/down arrows. 

I'll prepare the artifact for the other one too and you can compare.

**Comment by victorel-petrovich** [comment]
@donho  
> by taking the regression furthermore. 

what regression?

**Comment by donho** [comment]
> what regression?

Sorry for the typo:  `by taking the risk of regression`

**Comment by donho** [comment]
> we're talking about 2 possible alternatives here; one just mentioned, and the other:
> 

The current one is correct to me. Both suggestions are not pertinent to me.

> I'll prepare the artifact for the other one too and you can compare.

You can always do your PR. I just want you know that such PR, if the modification is complex, and the gain is minim, won't be accepted in general.

**Comment by victorel-petrovich** [comment]
No problem. I knew from start rejection was likely. 
I'm doing all this for the sake of fun and experience.

**Comment by victorel-petrovich** [comment]
For completion, here's the second alternative too:
https://ci.appveyor.com/project/victorel-petrovich/notepad-plus-plus-lastrecentfilelist-cpp/builds/47780745

https://github.com/victorel-petrovich/notepad-plus-plus_lastRecentFileList.cpp/blob/d274fefe31d3fd1f61b74ce4a30adaedffcaddbe/PowerEditor/src/lastRecentFileList.cpp

**Comment by victorel-petrovich** [comment]
@donho , one last question on this: which mode do you personally use, for recent files history: in main menu or in submenu?

**Comment by donho** [comment]
in main menu

**Comment by alankilborn** [comment]
>one last question on this: which mode do you personally use, for recent files history: in main menu or in submenu?

Is knowing this helpful?
Don is just one user of so many...

**Comment by donho** [comment]
> Is knowing this helpful?
> Don is just one user of so many...

I know about your feeling. But my position is keeping this software moving on, as stable as possible.

Quite a lot modifications has been done in the past, and they caused the regressions. 
For some it's mandatory (big improvement, features or bug fixes), for little the modifications are useless.
Such cosmetic improvement if it needs a lot of factoring, won't be accepted, for preventing the later case.

Hope you understand.

**Comment by victorel-petrovich** [comment]
@donho 
> in main menu

So, you see, the suggestions here won't affect your own use of N++ at all; ... yet you are against them, 
when not only me likes one or other of them.
*For fear of possible regression?*
With all due respect, that does not make any sense. 
1. The PR would be reviewed - not only by you, by the way.
2. It's a small change.
3. The changes I was going to make would actually make the code there clearer, and more according to documented use of some API like InsertMenu, and easier to maintain later. 

Overall, your position means it's a small but net loss for everyone.

**Comment by victorel-petrovich** [comment]
And from what I've read in closed Issues, it would be a first time something like this happens. 

IMHO, it would be better if you allow/trust a few other experienced maintainers to help you review and accept good changes.

**Comment by donho** [comment]
> So, you see, the suggestions here won't affect your own use of N++ at all; ... yet you are against them,

Not only. I judge it by users' needs, that is, users' requests.

> Overall, your position means it's a small but net loss for everyone.

If you can find the same requests from the past, I might reconsider it.
