### ISSUE TITLE
Cannot change/edit language based on xml files in localization folder in: %AppData%\Notepad++

### ISSUE THREAD

**Issue by victorel-petrovich** [notepad-plus-plus/notepad-plus-plus#13932]
### Description of the Issue
I was trying to follow https://npp-user-manual.org/docs/binary-translation/ , but step 4 there, 
> To see the changes take effect, save the file, then go to [Settings > Preferences > General > Localization](https://npp-user-manual.org/docs/preferences/#general) and select <yourlanguagename> from the pulldown menu: this will copy localization\<yourlanguagename>.xml to nativeLang.xml and will immediately update the Notepad++ application to use the text from your saved XML file.

fails: the new languages don't show up in that menu. They only show up if I download them to the localization folder inside the installation directory. 

And so, any edits done to the local language .xml files are completely ignored. 
Or is this the intended behavior and the doc needs change? 

### Steps to Reproduce the Issue
1. Have installer version
2. Put in user's %AppData%\Notepad++ a language .xml file (from https://github.com/notepad-plus-plus/notepad-plus-plus/tree/master/PowerEditor/installer/nativeLang ), that is not already present when you look in: Settings -> Preferences -> General -> Localization. 
3. Restart N++ and check that Settings -> Preferences -> General -> Localization for presence of the new language. 
4. (optional) Delete localization folder in Installation directory
5. check as in 3. 

### Expected Behavior
To see the locally added languages in that Pref. setting, and be able to edit language xml files from user %AppData% and see the changes reflected

### Actual Behavior
For 3., the new languages absent in that Pref. setting
For 5., no languages show up at all there at all

### Debug Information
Notepad++ v8.5.4   (32-bit)
Build time : Jun 17 2023 - 20:40:14
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 7 Ultimate (32-bit)
OS Build : 7601.24546
Current ANSI codepage : 1252
Plugins : 
    mimeTools (2.9)
    NppConverter (4.5)
    NppExec (0.8.4)
    NppExport (0.4)

**Comment by victorel-petrovich** [comment]
Somewhat (?) related issue: https://github.com/notepad-plus-plus/notepad-plus-plus/issues/9306

**Comment by donho** [comment]
Notepad++ User Manual has been updated:
https://github.com/notepad-plus-plus/npp-usermanual/commit/0a2ecce1f926cfde6611921896465d8ff2722b93
