### ISSUE TITLE
feature request: MRU navigation with "back" and "forward" buttons

### ISSUE THREAD

**Issue by meiskam** [notepad-plus-plus/notepad-plus-plus#13937]
### Background
i have mouse buttons 4 and 5 set to send "back" and "forward" commands, which in browsers navigate the the last page you were on.  I also have a keyboard with those same meta keys ([scancodes](https://www.win.tue.nl/~aeb/linux/kbd/scancodes-6.html#msinternet)).  using either of these keys navigates one tab to the left or right, irrespective of the Document Switcher or MRU settings.

### Request
change (or add a setting for) back/forward, to navigate through the MRU stack, the same way as you can in a web browser, and other IDEs. note, navigating this way doesn't add a new entry into MRU as ctrl-tab-release does, so hitting the back button twice goes to the 2nd most recent, not back to where you started.

### Expected Behavior
switch to the most recent tab

### Actual Behavior
switch tabs left/right

### Example that act as the Expected Behavior by default
vscode

**Comment by meiskam** [comment]
possible duplicates #1733 #4587 #8604

**Comment by donho** [comment]
Use concerning plugins.
