### ISSUE TITLE
[X] button on top-right corner ------ annoying

### ISSUE THREAD

**Issue by RadioOperator** [notepad-plus-plus/notepad-plus-plus#13939]
![Capture](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/27762920/7ae7d240-4039-4d1b-999a-6cf01ee51b9f)

Thanks.

**Comment by Yaron10** [comment]
@RadioOperator,

![תמונה](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/10229320/7bd3a6a7-0abd-4f09-b162-55671f9a0370)

**Comment by RadioOperator** [comment]
HI, @Yaron10 , thank you very much. I did not know that.

Now all OK for me, thanks again.
