### ISSUE TITLE
(Suggestion) Make it easier for users of the Portable version to create the Windows context-menu (at right-click) "Edit with Notepad++" ?

### ISSUE THREAD

**Issue by victorel-petrovich** [notepad-plus-plus/notepad-plus-plus#13935]
Currently, users of Portable version, if they want to have that Windows context menu, have to either download the Installer just for that, then extract it using 7z or like that, and copy `NppShell.dll` into their Portable install folder, 
or - edit the registry themselves.

So, for convenience, perhaps you could ship that file in the Portable version?  

EDIT: there are a few better suggestions down in the thread, so I changed the title to a more general one.

**Comment by victorel-petrovich** [comment]
My general intention  was to make it easier for Portable users to get the Windows context-menu feature. 
But one (main?) specific of Portable version is that you don't need admin rights to install & use it (including for new plugins, in my experience). 

So perhaps a better feature request would be to ship not that NppShell.dll, which requires admin rights to be run, but a different customized .dll , or just .reg file, that will be possible to run by non-admin users?

**Comment by sredna** [comment]
If you install N++ in a folder that is not inside Program Files then it gives you the option of storing all the settings in the same folder as N++. This is a per-user install which is not the same as a portable install. 

A portable install is not supposed to register itself in the system and leave no trace when you remove the USB stick where the portable app is located.

**Comment by victorel-petrovich** [comment]
> If you install N++ in a folder that is not inside Program Files then [...]  It gives you all the features but you don't have to be admin.

In my experience: it asks for admin password right from the start of installation (before you get to choose where). 
Also, even if you install not in standard Program Files ( I tried in C:\Users\MYUSER\somefolder) , you will still need admin pass later when install plugins (at least in case of NppExec). And for uninstalling. 

> A portable install is not supposed to register itself in the system and leave no trace when you remove the USB stick where the portable app is located.

True. My suggestion does not contradict that.

**Comment by sredna** [comment]
> It asks for admin password right from the start of installation

You can [bypass that UAC](https://devblogs.microsoft.com/oldnewthing/20161117-00/?p=94735) and install as non-admin.



> My suggestion does not contradict that.

But what good is the shell dll if it's not registered? Perhaps you are asking about a new feature where portable mode registers it when N++ is started and removes it when closed? This would have to use a different CLSID and take care when there are multiple instances.

**Comment by victorel-petrovich** [comment]
> You can [bypass that UAC](https://devblogs.microsoft.com/oldnewthing/20161117-00/?p=94735) and install as non-admin. 

That's new to me, thanks for the tip! 

However, when I use it (and choose to install not in Program Files, so that no further issues), Notepad no longer can install that right-click shell extension (I understand why, regsvr32 needs admin rights). 
Then what is the advantage of "installing" vs using portable version ? Just trying to understand.

> But what good is the shell dll if it's not registered? Perhaps you are asking about a new feature where portable mode registers it when N++ is started and removes it when closed? This would have to use a different CLSID and take care when there are multiple instances.

I'm not that advanced of a programmer and I thought that maybe it's possible to have a .dll that non-admin user can run manually and which would add a right-click menu for a single user. 
And to remove the effects, maybe just delete that .dll , or delete N++. But if that not possible, then user could delete key (or 2) in registry manually. 
If not .dll, then a .reg file. 
Even better: 2 reg files: `InstallRightClickEntry.reg` and `UninstallRightClickEntry.reg`, to be run manually, once each.

Whatever makes life a bit easier :)

**Comment by sredna** [comment]
Manual batch files would work, just write to HKCU\Software\Classes\... with reg.exe

**Comment by donho** [comment]
https://npp-user-manual.org/docs/shell-extension/

**Comment by victorel-petrovich** [comment]
@donho  , why are you referencing that, if users of Portable version often don't have admin priviledges?
