### ISSUE TITLE
Files with long path/filenames not loaded

### ISSUE THREAD

**Issue by kris22-120** [notepad-plus-plus/notepad-plus-plus#13953]
### Description of the Issue
Files with a length of the filename including path with more than 256 characters cannot be loaded by notepad++ 8.5.4 (32bit), Win10

### Steps to Reproduce the Issue
File to load:
G:\kris\Downloads\Amerika\trainsimcommunity\freight\40 ft container patch for GTrax and ABStudios well cars by NHG™Jeskoisking 2022-01\40ft Container Patch\Assets\G-TraX\ArticulatedStacks\Railvehicles\Freight\ArticulatedStack\Railcars_BNSF02\ArticStack_A PC.xml"

1.)  open in command:
cd G:\kris\Downloads\Amerika\trainsimcommunity\freight\40 ft container patch for GTrax and ABStudios well cars by NHG™Jeskoisking 2022-01\40ft Container Patch\Assets\G-TraX\ArticulatedStacks\Railvehicles\Freight\ArticulatedStack\Railcars_BNSF02\
"c:\Program Files (x86)\Notepad++\notepad++.exe" "ArticStack_A PC.xml"
-> fails (only an empty notepad++ shows up)

2.) open from within the program, like the started session from 1.) -> fails

Opening the file with the standard windows editor works.
Hope that this is not a limitation of the 32bit version.

Thanks
Kris

**Comment by alankilborn** [comment]
This is just the latest duplicate of all of these (and possibly more):

https://github.com/notepad-plus-plus/notepad-plus-plus/issues/4078
https://github.com/notepad-plus-plus/notepad-plus-plus/issues/4483
https://github.com/notepad-plus-plus/notepad-plus-plus/issues/5061
https://github.com/notepad-plus-plus/notepad-plus-plus/issues/8501
https://github.com/notepad-plus-plus/notepad-plus-plus/issues/9181
https://github.com/notepad-plus-plus/notepad-plus-plus/issues/10493
https://github.com/notepad-plus-plus/notepad-plus-plus/issues/12777

**Comment by kris22-120** [comment]
I have to apologize, I'm new to GitHub and haven't mastered searching yet. 
Thank you, since the problem is known I think it will be solved one day.
