### ISSUE TITLE
Find does not actually find text

### ISSUE THREAD

**Issue by astrohart** [notepad-plus-plus/notepad-plus-plus#13952]
![image](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/8261875/50c72308-310e-486c-9a37-6d2943a5f103)
**Figure 1.** Notepad++ can't find the text `Advisor` in the text where there are clearly occurrences of the search text.

### Description of the Issue
Notepad++'s **Edit**, **Find**, and **Edit**, **Replace** commands do not work.  The **Find What** text is not found even when multiple occurrences are present in the text to be searched.  The dialog box reports: `Find: Can't find the text "Foo"` (say, for example).

As a user, given that I've inserted text content that does indeed contain several occurrences of the word `Foo`, say, and I search for `Foo`, this is not the result I expect.  I expect to get several hits on all the `Foo`s in the text.

### Steps to Reproduce the Issue
1. Open a document or paste content into an editor tab containing text, say, `Foo`. 
2. Click the **Edit** menu, and then click **Find**.
3. In the **Find What** box, type `Foo` (or whatever text you're trying to search for).
4. Uncheck the **Backward Direction** check box.
5. Uncheck the **Match Whole Word Only** check box.
6. Click to place a check mark in the **Match Case** check box.
7. Uncheck the **Wrap Around** check box.
8. In the **Search Mode** group box, select either **Normal** or **Extended**.
9. Click **Find Next**.
10. The dialog box reports `Find: Can't find the text "Foo"`.  

### Expected Behavior
Several occurrences of the word `Foo` are found and highlighted, and clicking **Find Next** jumps the cursor to the next occurrence of `Foo`.

### Actual Behavior
The dialog box reports `Find: Can't find the text "Foo"`, when clearly, this is incorrect behavior.  As a user, if I use the **FInd** dialog box to search for `Foo` in text that obviously contains several occurrences of `Foo`, I expect to see those occurrences found and highlighted.

**Comment by mpheath** [comment]
@astrohart The caret is at line `13`, which is EOF (End Of File). The caret position is where the **Find Next** starts the search.

 * "*Uncheck the Backward Direction check box*" means **Find Next** must search forward.
 * "*Uncheck the Wrap Around check box*" means **Find Next** stops searching at EOF.

If **Find Next** starts at Line `13` and ends at Line `13` in which the caret is already positioned at EOF, then do not expect to find anything.

**Comment by alankilborn** [comment]
@astrohart 

Additional to what @mpheath said, familiarizing yourself with searching by reading that section of the user manual would be a good thing.  See [HERE](https://npp-user-manual.org/docs/searching/).

This issue can be closed.

**Comment by astrohart** [comment]
My bad.  Stupid mistake...LOL!  I didn't notice that the insertion point was at the end of the file, and that the **Wrap Around** checkbox was not checked.  Whoops :-)

**Comment by astrohart** [comment]
> @astrohart
> 
> Additional to what @mpheath said, familiarizing yourself with searching by reading that section of the user manual would be a good thing. See [HERE](https://npp-user-manual.org/docs/searching/).
> 
> This issue can be closed.

I think I know how to use software...but even the best of us have brain farts sometimes.

**Comment by alankilborn** [comment]
>I think I know how to use software...but even the best of us have brain farts sometimes.

Hmm, you were fairly definitive with your step 7...

But, OK...

**Comment by astrohart** [comment]
*facepalm* yes, a genius move on my part :-p  We all have our 'stupid moments.'
