### ISSUE TITLE
Incorrect color coding

### ISSUE THREAD

**Issue by AlexMineware** [notepad-plus-plus/notepad-plus-plus#13963]
### Description of the Issue
For some reason the 'color coding' goes wrong from the middle of line 61 of the attached SQL file.  Note that I use the Dark Mode as "Follows Windows' and is 'Black' 

### Steps to Reproduce the Issue

1.  Open the attached SQL file with Dark Mode as described above 
2. Check from Line 61 col 52 - things go wrong 
3. 

### Expected Behavior

The closing bracket on line 61 col 52 should be again in yellow (in my case) and not as part of a SQL string anymore as the SQL string ends on col 51.
### Actual Behavior

The SQL string is not ended (color wise) correctly and the rest of the file is now in 'inverse color coding'

### Debug Information

Notepad++ v8.5.4   (64-bit)
Build time : Jun 17 2023 - 20:42:45
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 11 Pro for Workstations (64-bit)
OS Version : 21H2
OS Build : 22000.2176
Current ANSI codepage : 1252
Plugins : 
    ComparePlugin (2.0.2)
    DSpellCheck (1.4.23)
    mimeTools (2.9)
    NppConverter (4.5)
    NppExport (0.4)
    NPPJSONViewer (2.0.4)
    PoorMansTSqlFormatterNppPlugin (1.6.13.31508)
    XMLTools (3.1.1.12)

![image](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/31504750/ecf51ccb-7605-4ac5-9409-733df5defaad)
[test.zip](https://github.com/notepad-plus-plus/notepad-plus-plus/files/12257547/test.zip)

**Comment by rdipardo** [comment]
1. Settings > Preferences > Language
2. *Clear* the "Treat backslash as escape character for SQL" checkbox

![lexer sql escape backslash](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/59004801/70213c3e-6bfb-4099-a33b-4140b403d9be)

**Comment by AlexMineware** [comment]
Hi,

 

Great stuff – thank you !

 




Regards

 

ALEX CAUDRON

 

Snr Developer

 

Mobile: 072 597 6440

 

 <https://www.mineware.co.za/> www.mineware.co.za

 

 

Using data to solve problems
