### ISSUE TITLE
Context Menu duplicated discussion

### ISSUE THREAD

**Issue by modz2014** [notepad-plus-plus/notepad-plus-plus#13962]
hi not really an issue just a discussion of the context menu showing up in the new one and also showing up in the old one

**Comment by victorel-petrovich** [comment]
Hi,
If it's just a discussin, I think this place is more appropriate: https://community.notepad-plus-plus.org/category/2/general-discussion

**Comment by modz2014** [comment]
hey sorry to annoy you guys but I have found a bug in notepad++ shell extension for some reason if I install other msix packages notepad++ context menu duplicates the new lay which is windows 11 new context menu and under the show more options but if I uninstall any msix package there wont be context menu showing up under show more options only the top layer
