### ISSUE TITLE
[feature req.] Make the "Hide Lines" symbols toggable and persistent

### ISSUE THREAD

**Issue by victorel-petrovich** [notepad-plus-plus/notepad-plus-plus#13983]
![image](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/11040279/e2b8faff-6119-439b-beb5-3924fb57d4fb)
### Description of the Issue
The  Hide Lines feature (shortcut `Alt+H`, located in: Menu > View > Hide Lines ) 
would be a very useful feature, but, unfortunately, is far from so, because you can't toggle the symbols/markers to show/hide the lines, and also Notepad++ doesn't remember their hiding-state when you restart N++, as it does for folded lines. 

Wanted by others too:
https://community.notepad-plus-plus.org/topic/16203/remember-hidden-lines-after-unhiding
https://community.notepad-plus-plus.org/topic/17293/keep-hidden-lines-hidden

### Steps to Reproduce the Issue
1. Select some lines and hide them
2. Click on other lines, then click on the triangle symbols to unhide the lines
3. Do 1. again
4. Restart N++

### Expected Behavior
After step 2, to still see the markers, so that could hide/unhide the lines again if needed. 
Also, *preferably*, to see a vertical line in the margin, indicating which lines belong to the hiding-group.

After 4, to see the lines in same hidden/unhidden state.

### Actual Behavior
After 2, the symbols disappear.
After 4, the lines are not hidden and the symbols are gone. 

### Debug Information
Notepad++ v8.5.4   (32-bit)
Build time : Jun 17 2023 - 20:40:14
Path : C:\Users\Vic\AppData\npp.8.5.4.portable\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : ON
Cloud Config : OFF
OS Name : Windows 7 Ultimate (32-bit)
OS Build : 7601.24546
Current ANSI codepage : 1252
Plugins : 
    mimeTools (2.9)
    NppConverter (4.5)
    NppExec (0.8.4)
    NppExport (0.4)
    PythonScript (2)

**Comment by victorel-petrovich** [comment]
I do realize that this would imply a new way to remove the symbols entirely. Possible options:
- a 3rd little symol, looking like `x`, in between the 2 present symbols (triangles);
- have just a single triangle, which will change orientation at toggling, and the `x` below it for closing

**Comment by alankilborn** [comment]
>you can't toggle the symbols/markers to show/hide the lines, and also Notepad++ doesn't remember their hiding-state when you restart N++, as it does for folded lines.

Items that are different (even if related through the common bond of being about the same high-level feature) should be broken down into separate issues (2 in this case).

**Comment by victorel-petrovich** [comment]
@alankilborn , I had that thought too, but wasn't sure. OK, I'll delete and close this and create 2 issues.
