### ISSUE TITLE
File synchronisation failes when npp restarts with admin privilages

### ISSUE THREAD

**Issue by saitejalakkimsetty** [notepad-plus-plus/notepad-plus-plus#1398]
Heres the case:
1. Open `C:\Windows\System32\drivers\etc\hosts` from context menu [opens npp non-admin].
2. Make some changes, blue icon on the tab of open file turns to red, pressing `Ctrl+S` to save.
3. npp asks to launch in admin mode, press `yes`
4. npp relaunches and icon turns to blue, but the file is not saved [Can be verified by closing the file tab and opening again].

**Comment by YueLinHo** [comment]
Cause: npp always opens `C:\Windows\SysWOW64\drivers\etc\hosts`.

**Comment by YueLinHo** [comment]
Suppose this issue is a duplicate one, see #1168.

**Comment by saitejalakkimsetty** [comment]
Fixed.
