### ISSUE TITLE
[feature request] Double click on the tab to rename the file

### ISSUE THREAD

**Issue by wuxr131** [notepad-plus-plus/notepad-plus-plus#13984]
**Description of the Issue**
Double-clicking tabs does not have binding capabilities, and you want to be able to set and bind different capabilities, such as renaming the current file

**Expected Behavior**
Double-click the tab binding function

**Comment by alankilborn** [comment]
>Just curious, why do you need this

Agree.  This is a frivolous "need".  AND, it's susceptible to accidental mouse stutter invoking it.  
Overall:  Blech!

**Comment by victorel-petrovich** [comment]
@wuxr131 , forgot to mention: check out right-click on a tab as well, if you're into mouse clicks.
