### ISSUE TITLE
TYPO CONTRIBUTING.md

### ISSUE THREAD

**Issue by moonlit-melody** [notepad-plus-plus/notepad-plus-plus#13989]
Hello,

In this issue, I have identified two minor typos that need correction.
__Updated: reference links to master__
1. `fuctions` -> `functions` [CONTRIBUTING.md L424](https://github.com/notepad-plus-plus/notepad-plus-plus/blob/master/CONTRIBUTING.md?plain=1#L424)
2. `initializatize` -> `initialize` [CONTRIBUTING.md L295](https://github.com/notepad-plus-plus/notepad-plus-plus/blob/master/CONTRIBUTING.md?plain=1#L295)

Thank you for your time and consideration in addressing these errors.
Best regards,
Melody

**Comment by victorel-petrovich** [comment]
... but they are funny :)

**Comment by victorel-petrovich** [comment]
#1 doesn't exist in current version (you were looking in a past commit, apparently). 
https://github.com/notepad-plus-plus/notepad-plus-plus/edit/master/CONTRIBUTING.md

**Comment by moonlit-melody** [comment]
> Thanks for your time as well.
> 
> #1 doesn't exist in current version (you were looking in a past commit, apparently). https://github.com/notepad-plus-plus/notepad-plus-plus/edit/master/CONTRIBUTING.md

I have updated the reference links to the master.
Could you please check it again?

Best regards,
Melody
