### ISSUE TITLE
Make the hidden lines *persistent* at Npp restart  

### ISSUE THREAD

**Issue by victorel-petrovich** [notepad-plus-plus/notepad-plus-plus#13986]
![image](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/11040279/e2b8faff-6119-439b-beb5-3924fb57d4fb)
#### Description of the Issue
The  Hide Lines feature (shortcut `Alt+H`, located in: Menu > View > Hide Lines ) 
would be a much more useful feature if Notepad++ remembered their hiding-state when you restart N++, as it does for folded lines. 

Wanted by others too:
https://community.notepad-plus-plus.org/topic/16203/remember-hidden-lines-after-unhiding
https://community.notepad-plus-plus.org/topic/17293/keep-hidden-lines-hidden

### Steps to Reproduce the Issue
1. Select some lines and hide them
2. Restart N++

### Expected Behavior
To see the lines in same hidde state.

### Actual Behavior
The lines are not hidden and the symbols/markers/handles are gone. 

### Debug Information
Notepad++ v8.5.4   (32-bit)
Build time : Jun 17 2023 - 20:40:14
Path : C:\Users\Vic\AppData\npp.8.5.4.portable\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : ON
Cloud Config : OFF
OS Name : Windows 7 Ultimate (32-bit)
OS Build : 7601.24546
Current ANSI codepage : 1252
Plugins : 
    mimeTools (2.9)
    NppConverter (4.5)
    NppExec (0.8.4)
    NppExport (0.4)
    PythonScript (2)

**Comment by donho** [comment]
Duplicate #12051

**Comment by victorel-petrovich** [comment]
Oh, somehow I missed that duplicate, even though I searched.

**Comment by alankilborn** [comment]
Don Ho noted the duplicate and closed this one, but did not assign himself to take a deeper look (i.e., give more consideration) to the issue that remains open.  :-(

**Comment by donho** [comment]
@alankilborn 
> Don Ho noted the duplicate and closed this one, but did not assign himself to take a deeper look (i.e., give more consideration) to the issue that remains open.

That's because it's not a bug but an intentional behaviour.
#12051 is rather a feature request than a bug report.
And sincerely, I'm not sure it's a worthy feature for being implemented.

**Comment by alankilborn** [comment]
>I'm not sure it's a worthy feature for being implemented.

OK.

**Comment by raaomoka** [comment]
> And sincerely, I'm not sure it's a worthy feature for being implemented.

Why not create a poll inviting users to vote on it on X or here on GitHub? 😄 Like I mentioned in #12051, it'll significantly help in scanning through thousands of lines of code. As of this post, the AutoHotkey script I keep building on for my workflow has 14,453 lines of code, almost double what I mentioned 8 months ago, and it's only growing with more and more clients coming our way. Mostly growing with write-once-use-forver code that provide means to rapidly enter client-specific details in OneNote/Excel/Word/etc. in my case.

By proper coding practice, I already group my code in paragraps and with header notes. Being able to hide the write-once-use-forever groups of code will immensely aid in navigating through my lines of code as it continues to grow.
