### ISSUE TITLE
Plugin Manager Auto Update check

### ISSUE THREAD

**Issue by djdiscodave** [notepad-plus-plus/notepad-plus-plus#1399]
Is it possible to move Update check for the Plugin Manager to the main program preferences dialog.  It may even be better if the option was merged with Notepad++ option to check for updates, so one preference controls both checks.  Having set the option to No during installation, the Plugin Manager need subsequent configuration.

**Comment by dail8859** [comment]
As of Notepad++ v7.5 the Plugin Manager is no long being shipped with Notepad++. See https://notepad-plus-plus.org/news/notepad-7.5-released.html

All Plugin Manager related issues should be reported to https://github.com/bruderstein/nppPluginManager/issues
