### ISSUE TITLE
Activate file(s) loaded from a Session file

### ISSUE THREAD

**Issue by Yaron10** [notepad-plus-plus/notepad-plus-plus#14006]
**STR:**
Open file _A_.
File -> Save Session: save it as _testSes_.
Close file _A_, and open file _B_.
Open _testSes_.

**Result:**
File _A_ is opened, but file _B_ is still active.

**Expected:**
File _A_ should be active.

***

Notepad++ 8.5.5.

**Comment by victorel-petrovich** [comment]
Reproduced on v. 8.5.6, Win 32 bit.

**Comment by donho** [comment]
@Yaron10 
> File A should be active.

It's questionable.
Why do you think B shouldn't be active after opening a session?

**Comment by alankilborn** [comment]
Since B is still in the open tab space, I think it should remain active.

I didn't test it, but if the only thing in the current session is a "new 1" tab, when the session file (testSes) is opened, should "new 1" remain active?  Or, is "new 1" judged too temporary to even remain open at this point?  (My idea here is that user wants to close all open tabs before opening testSes, but, since you must have at least one tab open at all times...)

**Comment by Yaron10** [comment]
> My idea here is that user wants to close all open tabs before opening testSes

Doesn't that strengthen the position that the session file(s) should be activated?

BTW, "file(s)" here and in the thread's title: in case the session file contains files in both views

**Comment by alankilborn** [comment]
>Doesn't that strengthen the position that the session file(s) should be activated?

Yes, for my specific example of the user not wanting to retain any existing tabs.
But in the case of adding to a bunch of existing tabs, then I don't know for sure, but I don't think I'd want to see the session file's active document activated.

**Comment by victorel-petrovich** [comment]
> But in the case of adding to a bunch of existing tabs, then I don't know for sure, but I don't think I'd want to see the session file's active document activated. 

why would you Load another session if you don't want to switch to it's document ? (the active one, that is). 
Normally, if you still have stuff to do in doc B, you finish it before loading another session.

**Comment by alankilborn** [comment]
>why would you Load another session if you don't want to switch to it's document ? (the active one, that is).
Normally, if you still have stuff to do in doc B, you finish it before loading another session.

Loading a session file doesn't close existing tabs.  I have a "sometimes" need to combine tab groups and this behavior provides a nice way to do it, with a follow-on save of the session.

**Comment by victorel-petrovich** [comment]
So it's "normally" vs "sometimes".

**Comment by Yaron10** [comment]
Thank you all.

I'm still trying to understand why there should be a difference between opening a file directly or via a Session file.

**Comment by alankilborn** [comment]
>Normally, if you still have stuff to do in doc B, you finish it before loading another session.

I wouldn't go too far with this.  The designer deemed that loading a session file combines existing tabs with tabs from that session file.  If your "normally" was the designer's normal, it wouldn't have been done that way.

>...sometimes...

The designer's design just happens to work out well for me. :-)

**Comment by victorel-petrovich** [comment]
> The designer deemed that loading a session file combines existing tabs with tabs from that session file. 

That is fine by me too. Nobody said that loading a session file should close other tabs. But that doesn't mean the existing tabs are of more importance than the newly loaded ones. Just like when you open un-sessioned files, if you open file B, it doesn't mean existing tab A is more important and thus should retain focus.

**Comment by alankilborn** [comment]
When "combining" sessions in such a manner, it probably isn't super-important which tab is activated after.  My expectation was different than @Yaron10 's, but that's OK and if his expectation is strong enough to create an issue on it, I'll agree that he is right about it. :-)

**Comment by donho** [comment]
@Yaron10 
The index of position `activeIndex` is used for activate the tab after loading a session, that explains the bug while you load session with other files open:  
```
<NotepadPlus>
    <Session activeView="0">
        <mainView activeIndex="1">
			<File firstVisibleLine="0" xOffset="0" ... />
			<File firstVisibleLine="0" xOffset="0" ... />
		</mainView>
        <subView activeIndex="0" />
    </Session>
</NotepadPlus>
```
I have no solution for the moment (without changing the session file structure), but I will see what I can do about it.

**Comment by Yaron10** [comment]
@donho,

Thank you for looking into it. I appreciate that. 👍 

A preliminary and vague direction you've probably considered: activate `activeIndex` + (`nbItem()` before loading the Session files).
If there's only one clean untitled doc, `nbItem` should be decreased.

Another case to consider (the bug is more severe):
**STR:**
Open file A.
File -> Save Session: save it as testSes.
Close file A, and open file B.
_Reopen file A directly._ 
Open testSes.

**Result:**
File B is activated.

*** 

Thank you all again for the discussion.
