### ISSUE TITLE
Please stop applying that "reject" label. It's enough to close the issue.

### ISSUE THREAD

**Issue by victorel-petrovich** [notepad-plus-plus/notepad-plus-plus#14004]
It's unnecessarily unpleasant, if that's not obvious.

Isn't the `Close as not planned` option of closing enough for the purpose?

**Comment by alankilborn** [comment]
LOL

**Comment by victorel-petrovich** [comment]
I'm not surprised

**Comment by victorel-petrovich** [comment]
Could go in the Humor section in the community forum.
