### ISSUE TITLE
Keyboard shortcuts for Zoom In/Out/Restore - laptops don't have Num keypad

### ISSUE THREAD

**Issue by tingtron** [notepad-plus-plus/notepad-plus-plus#14008]
### Description of the Issue
Existing keyboard shortcuts for Zoom In/Out/Restore require Num keypad, which is missing on laptops.

Also the Shortcut Mapper does not have Zoom, so it cannot be even redefined.

### Steps to Reproduce the Issue

1. Need to Zoom In/Out/Restore with keyboard
2. The existing keyboard shortcuts require Num keypad Laptop
3. Laptops don't have Num keypad
4. Shortcut Mapper does not have Zoom entries

### Expected Behavior
Two options, or even both:
A. Use additional combinations for Zoom In/Out/Restore, like in the browser: Ctrl++/Ctrl+-/Ctrl-0
B. In Shortcut Mapper, provide entries for Zoom In/Out/Restore

### Actual Behavior
Cannot Zoom In/Out/Restore with keyboard on a laptop.
Cannot modify shortcuts for Zoom In/Out/Restore.

### Debug Information
Notepad++ v8.5.4   (64-bit)
Build time : Jun 17 2023 - 20:42:45
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 11 Pro (64-bit)
OS Version : 22H2
OS Build : 22621.1992
Current ANSI codepage : 1252
Plugins : 
    mimeTools (2.9)
    NppConverter (4.5)
    NppExport (0.4)
    XMLTools (3.1.1.13)

**Comment by victorel-petrovich** [comment]
Have you looked in the tab: "Scintilla Commands" of the Shorcut Mapper?

**Comment by tingtron** [comment]
Yes indeed, "Scintilla Commands" of the Shorcut Mapper is where Zoom In/Out/Restore are located. -- Thank you!

Even though `Ctrl+0` is already taken, there are other available options, such as `Ctrl+~`.

**Comment by tingtron** [comment]
So it wasn't an issue.

**Comment by victorel-petrovich** [comment]
> Yes indeed, "Scintilla Commands" of the Shorcut Mapper is where Zoom In/Out/Restore are located. -- Thank you!
> 
> Even though `Ctrl+0` is already taken, there are other available options, such as `Ctrl+~`.

You're welcome.

I prefer the reset of zoom keys to be near the +/-; so I chose ctrl+alt+Backspace. Another option could be ctrl+alt+0. Etc.

**Comment by ygoe** [comment]
It is an issue. There is no Plus key in that dialog selection. Instead of <kbd>Ctrl</kbd>+<kbd>Num+</kbd> I'd like to use the browser's shortcuts <kbd>Ctrl</kbd>+<kbd>+</kbd> but that's not possible, surprisingly. The Minus (dash) key is there but Plus is not. And a few others are that don't even exist. Is this tied to the en-US keyboard layout? I have the de-DE layout. That dialog doesn't work anywhere else in the world than in the USA maybe.

**Comment by tingtron** [comment]
@ygoe - It's not Ctrl+`+`, it's Ctrl+`=`.
So the Zoom shortcuts can be set up like
![image](https://github.com/user-attachments/assets/d82f2991-7f81-4267-b5db-af03442e28f3)

**Comment by ygoe** [comment]
@tingtron What does that mean? "It's not Ctrl++, it's Ctrl+=." It's this for me:

![grafik](https://github.com/user-attachments/assets/e68d4d9c-7d5a-487c-ba3a-2925aef83141)

And I would like to have it Ctrl++. The "=" key doesn't exist, that character would be produced with Shift+0. Welcome to keyboard layouts.

**Comment by alankilborn** [comment]
> It's not Ctrl+`+`, it's Ctrl+`=`.

> What does that mean? 

On en-US keyboards, `+` is the shifted `=`.  So, when @tingtron assigns zoom-in to Ctrl+=, visually it looks like the `+` key is involved, which makes sense for zoom-in.

**Comment by tingtron** [comment]
> I have the de-DE layout. That dialog doesn't work anywhere else in the world than in the USA maybe.

Maybe because Germans are good at hardware. And not so much in software... Where are the German contributors to Scintilla or Notepad++ to implement such enhancements?
