### ISSUE TITLE
Feature Request: Default Language for new Tabs

### ISSUE THREAD

**Issue by ibrahimGit123** [notepad-plus-plus/notepad-plus-plus#14013]
### Description of the Issue
Feature Request: If I set the Language on a tab in Notepad++ and then click to open a new tab beside it, the new tab should default to the same Language as the first tab I was on.

This is a very common scenario I run across and would be very helpful.

**Comment by victorel-petrovich** [comment]
My understanding is that you want the language in the new tab to be set to the lang in the last active tab you were in (not necessarily besides the new tab). 

But, won't your wish conflict with the preference you have set in: menu > Preferences > New Document > Default Language ? 

Also,

**Comment by ibrahimGit123** [comment]
You are correct here re: "My understanding is that you want the language in the new tab to be set to the lang in the last active tab you were in (not necessarily besides the new tab)."

O , you are right, they would contradict. The feature would have to only apply in cases where there is no default language set. 

I will try using the default language option and that may just be what I was looking for instead of this request!

**Comment by victorel-petrovich** [comment]
Also, I don't know your particular use case, but:
 if you get in the habbit of saving the new file from the beginning (something good anyway), and give it the desired extension, then the lang will be set already.
