### ISSUE TITLE
[Feature requests] 4. Essential for beginners and everyone. Please consider

### ISSUE THREAD

**Issue by sng843ndf86nd8** [notepad-plus-plus/notepad-plus-plus#1401]
#1, Ability to delete Auto-Inserted (Auto-Completion Preferences menu) half of dual symbol (parenthesis, brackets, curly braces, quotas…) by pressing Backspace. It means to remove whole double symbol by deleting it’s first half wrote manually in origin.

#2, Ability to delete Tabbed whitespaces (by pressing Backspace), transformed to regular spaces due to Tab Settings in Preferences; in sense of one Backspace = one deleted tabbed whitespace. It means not x-times pressed Backspace to delete one tabbed whitespace.

#3, Ability to reset key bindings to default from GUI. For beginners who never used such poweful notepad and are trying to find their own efficient work habits.

#4, Ability to exclude numbers from Auto-Completion.
And ability to exclude specific strings from Auto-Completion per file or default for anything opened !

Many thanks Devs <3

**Comment by sng843ndf86nd8** [comment]
kind bump

**Comment by dail8859** [comment]
Moving discussion to #2090
