### ISSUE TITLE
Bash syntax highlighting: dollar at end of string (regex)

### ISSUE THREAD

**Issue by remgeek** [notepad-plus-plus/notepad-plus-plus#14016]
### Description of the Issue
A dollar at the end of a regex string puzzles bash syntax highlighting since v8.5.4.

### Steps to Reproduce the Issue
The below picture illustrates the issue:
![image](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/52370774/59994385-0356-4540-a749-d37efb937afb)

### Expected Behavior
Can be restored by escaping the dollar sign, but I would like to avoid having to do this in my entire code base.
![image](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/52370774/9961dc17-98d6-415f-8e38-6957b8aea3d3)

### Debug Information
Notepad++ v8.5.4   (64-bit)
Build time : Jun 17 2023 - 20:42:45
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 10 Enterprise (64-bit)
OS Version : 21H2
OS Build : 19044.3208
Current ANSI codepage : 1252
Plugins : 
    mimeTools (2.9)
    NppConverter (4.5)
    NppExport (0.4)

**Comment by rdipardo** [comment]
This [has been fixed](https://github.com/notepad-plus-plus/notepad-plus-plus/pull/13940#issuecomment-1654745947) since version 8.5.5

> #### Debug Information
> . . .
> Notepad++ v8.5.4 (64-bit)

Time for an update?
