### ISSUE TITLE
[feature] Default or Remembered location when `Load/Save Session...`

### ISSUE THREAD

**Issue by victorel-petrovich** [notepad-plus-plus/notepad-plus-plus#14022]
Using Npp's `Load/Save Session...` in menu>File would be easier if you didn't have to browse Every Time to the location of your saved session file. 

Any of these options would solve this, IMO:
1. Remember last used directory (specifically at a Load Session or Save Session, not at open/save any general file)
2. Ability to specify the prefered directory (in Preferences or in an xml file...) where you could store all your session files , and open that
3. Open a directory predetermined, fixed by Npp, where all user session files are meant to be stored (named `Sessions`, for ex.); probably in the user configuration directory (be it inside %AppData% or just inside Portable folder)

Similar feature has been asked before:
https://community.notepad-plus-plus.org/topic/12005/session-file-handling-needs-improvement
https://community.notepad-plus-plus.org/topic/13648/feature-request
https://github.com/notepad-plus-plus/notepad-plus-plus/issues/5878

**Comment by victorel-petrovich** [comment]
I don't think this is a duplicate of https://github.com/notepad-plus-plus/notepad-plus-plus/issues/5878 , because on the one hand, I only ask about Location , not also remembering & filling in the previous session file name (though that is nice), and on the other hand, my request is more general: not only at Saving but also at Loading a session, and offers few more options that would solve this.

**Comment by alankilborn** [comment]
A "duplicate" issue is one that puts forth a general common idea/spirit as another.  Certainly if to dubbed a duplicate then two issues have to _exactly_ match, then there wouldn't be many.  Differences can be accounted for in the comments on an issue that gets dubbed (somehow) the _master_ issue for the general idea.

**Comment by victorel-petrovich** [comment]
@alankilborn , I think a good "litmus test" for telling duplicates is: 
will implementing / fixing Issue A also fix Issue B? And viceversa. 

So here, you can see that fixing current issue will not fix issue https://github.com/notepad-plus-plus/notepad-plus-plus/issues/5878 (but only partially so).

**Comment by Yaron10** [comment]
@victorel-petrovich,

> where you could store all your session files
...
where all user session files are meant to be stored

I have Session files in various different folders.
(For example: different Firefox profiles).

I'm wondering if most users store their Session files in one specific folder.
One might request a unique Open/Save folder for Visual Basic scripts. :)

What do you think?

**Comment by alankilborn** [comment]
>I'm wondering if most users store their Session files in one specific folder.

Well, I for one do this, but I can understand doing it other ways.

**Comment by Yaron10** [comment]
> Well, I for one do this

So - it's you, @victorel-petrovich and probably many others.
Well. :)

**Comment by donho** [comment]
https://github.com/notepad-plus-plus/notepad-plus-plus/issues/5878#issuecomment-1684528143

**Comment by victorel-petrovich** [comment]
@Yaron10 ,
> One might request a unique Open/Save folder for Visual Basic scripts. :)

I'm not sure we'are on the same page:
By "session files" in this posted Issue , to be stored in a default or last-used location, I meant the special `.xml` meta-files that store info about which other files / scripts are in a particular "session" (and other details about them). 

> I'm wondering if most users store their Session files in one specific folder.

So, talking about those special "session" xml files, I don't see for now why they can't be stored all in a single location. 
As opposed to the files grouped/referred to by a particular "session" file.

**Comment by victorel-petrovich** [comment]
@donho , I thought you'd label it as `duplicate`

**Comment by victorel-petrovich** [comment]
@donho , you could update CONTRIBUTING.md to say clearly that you're not welcoming new feature requests, for now.
So people won't waste their time, 
and energy,  resulting in a greener environment , as you say you care about on https://notepad-plus-plus.org/ .

**Comment by alankilborn** [comment]
>you could update CONTRIBUTING.md to say clearly that you're not welcoming new feature requests, for now.
So people won't waste their time,

`CONTRIBUTING.md` has to do with contributing code, not contributing ideas e.g. feature requests.

New feature requests are always welcome, they (of course) may not be acted upon, due to lack of developer time, or a decision that a request isn't right for the product (authors always have the judgement call on this).

**Comment by victorel-petrovich** [comment]
> CONTRIBUTING.md has to do with contributing code, not contributing ideas e.g. feature requests.

your're wrong about that; it stipulates for example how to format an issue, bug reports etc

> New feature requests are always welcome 

no they are not, from what can be seen. 

You're just pathetically defending Don here, as if he was attacked, hoping to be liked by him

**Comment by victorel-petrovich** [comment]
a kind of bootlicking

**Comment by donho** [comment]
@victorel-petrovich 

People have done a lot of contribution in the project, some are rejected, and some are accepted. I am sorry to not be able to accept your suggestions/feature requests, I ensure you that it's not the case for the others, if the contribution provide is pertinent (please see: https://github.com/notepad-plus-plus/notepad-plus-plus/commits/master).

> a kind of bootlicking

Do you realize that you're insulting people here? Such behaviour is not allowed in this project.
We provide the arguments to make decision, not the insulting words.

You'll be banned if it happens again.

**Comment by victorel-petrovich** [comment]
>  I am sorry to not be able to accept your suggestions/feature requests, 

No need to appologize, it's not about just my requests. Daily people submit suggestions, hoping that they will be implemented. But it's all a waste, 99.9999999% of them will not get done. It's just what it is, mostly a 1 man project. 
And I still think it's a good idea to be straight about that in the contributing page. 

> Do you realize that you're insulting people here? Such behaviour is not allowed in this project. 

@alankilborn , I apologize for that, I was just going to delete that comment, because I may have been wrong and it was probably too harsh even if I was right about you overly-defending Don.

**Comment by alankilborn** [comment]
> I apologize for that, I was just going to delete that comment, because I may have been wrong and maybe it was too harsh even if I was right about you overly-defending Don.

Really, no problem...
You maybe should read more old issue comments.  A LOT of the time, Don and I don't see things the same way, so I'm hardly a "Don defender".  But it doesn't bother me, and Don wouldn't care if it did.  :-)
Let's carry on...

**Comment by victorel-petrovich** [comment]
@alankilborn , thanks for the perspective & wrap-up. Hope we'll carry on on more interesting/productive things. 

@donho , I don't hate you (or maybe just a little ;) )... but I also don't care if you ban me. 
I have an idea or 2 how to get the potential contributors to work on Issues you'd like... Maybe another time.

**Comment by Yaron10** [comment]
@victorel-petrovich,

I've enjoyed corresponding with you.
But I'm grateful to my old friends here, and your personal attacks were quite inappropriate.
I'm glad you've apologized.
