### ISSUE TITLE
Error of Saving Session XML File

### ISSUE THREAD

**Issue by tktewell** [notepad-plus-plus/notepad-plus-plus#14024]
### Description of the Issue

after I open Notepad++ v8.5.6 and open a new tap and coping an SQL query from SQL Server then pasting the code in the tab I get a popup pox with the following message **Error of Saving session XML File**.

### Steps to Reproduce the Issue

1. Open Notepad++
2. Copy SQL for SQL Serer Management Studio
3. Select File>New
4. Paste Code copied from SQL Serer Management Studio

### Expected Behavior

I expected noting to happen so I could select the language and then save the file
### Actual Behavior

Got the error message **Error of Saving session XML File**. C:\USers\myID\Roaming\Notepad++\Session.xml
### Debug Information

Notepad++ v8.5.6   (32-bit)
Build time : Aug 15 2023 - 15:27:06
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 10 Enterprise (64-bit)
OS Version : 22H2
OS Build : 19045.3324
Current ANSI codepage : 1252
Plugins : 
    mimeTools (2.9)
    NppConverter (4.5)
    NppExport (0.4)

**Comment by donho** [comment]
@tktewell 
Could you check if `C:\USers\myID\Roaming\Notepad++\Session.xml` is read only?
