### ISSUE TITLE
gedcomLexer bug

### ISSUE THREAD

**Issue by jmatifat** [notepad-plus-plus/notepad-plus-plus#1402]
The lexer is not consistent : 
- in INDI section, the BIRTH clause can be hidden or not (see jpg2)
- in FAM section, the MARR clause can be hidden or not (see jpg1)
A very nice plugin idea (if you play with gedcom files)

Thanks
![gedcomlexer-dll_bug_2016_1](https://cloud.githubusercontent.com/assets/16854280/12531363/84ce6abe-c1c6-11e5-83b2-e0beed528d5f.jpg)
![gedcomlexer-dll_bug_2016_2](https://cloud.githubusercontent.com/assets/16854280/12531364/84d2e5b2-c1c6-11e5-8971-43e9083c8708.jpg)

**Comment by dail8859** [comment]
Please report this to the author of the GEDCOM lexer.

**Comment by dail8859** [comment]
Closing since this is an issue with an external lexer.
