### ISSUE TITLE
Line numbers do not print 8.5.6 

### ISSUE THREAD

**Issue by parios59** [notepad-plus-plus/notepad-plus-plus#14032]
### Debug Information

Notepad++ v8.5.6   (64-bit)
Build time : Aug 15 2023 - 15:29:28
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 11 Pro (64-bit)
OS Version : 22H2
OS Build : 22621.2134
Current ANSI codepage : 1252
Plugins : 
    CustomLineNumbers (1.1.7)
    mimeTools (2.9)
    NppConverter (4.5)
    NppExport (0.4)
![2023-08-19_18-49-13](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/8902122/ff93c621-677b-4c7d-9fcf-a8bd490d4408)

**Comment by alankilborn** [comment]
Try eliminating the CustomLineNumbers plugin and see if printing line numbers is successful.

**Comment by parios59** [comment]
AlanKilBorn,  Thank you for the tip.  Removing the plugin allowed the line #s to print.

Please close / mark ticket as resolved.
