### ISSUE TITLE
[Bug] Uncomment in html files (Ctrl-shift-k), uncomments more than it should!

### ISSUE THREAD

**Issue by rickski-au** [notepad-plus-plus/notepad-plus-plus#14047]
Create this html file, follow steps to reproduce problem.
Bug started with version 8.5?

<html>

</html>

**Comment by rickski-au** [comment]
[notepad plus plus BUG uncomment error.html.txt](https://github.com/notepad-plus-plus/notepad-plus-plus/files/12436451/notepad.plus.plus.BUG.uncomment.error.html.txt)

**Comment by Yaron10** [comment]
@rickski-au,

https://github.com/notepad-plus-plus/notepad-plus-plus/issues/12829.

**Comment by MarkusBodensee** [comment]
Is it fixed with 7bbe4d1ff88fba41dec8750843f31bb542cd0d5e ?

**Comment by Yaron10** [comment]
@MarkusBodensee,

It should be fixed with https://github.com/notepad-plus-plus/notepad-plus-plus/commit/7bbe4d1ff88fba41dec8750843f31bb542cd0d5e.

**Comment by ArkadiuszMichalski** [comment]
This was fixed.
