### ISSUE TITLE
Add an option to suppress large file warning

### ISSUE THREAD

**Issue by DerivativeOfLog7** [notepad-plus-plus/notepad-plus-plus#14054]
### Description of the Issue
Notepad++ will completely hang and await user confirmation when trying to open a file bigger than 2GB, this includes while it's automatically searching for a string in a group of files; this could be an issue especially if it's left doing the search unattended
There also may be users that simply don't feel the need to be warned when opening big files
#14053 proposes to add an option to suppress the warning

**Comment by donho** [comment]
@DerivativeOfLog7 
You should follow the template for providing all the information.
