### ISSUE TITLE
Add an option to suppress large file warning

### ISSUE THREAD

**Issue by DerivativeOfLog7** [notepad-plus-plus/notepad-plus-plus#14055]
### Description of the Issue
Notepad++ will completely hang and await user confirmation when trying to open a file bigger than 2GB.

This includes while it's automatically searching for a string in a group of files  
If an user were to start a search in a folder without realizing there are big files, a single one of those files could waste time leaving Notepad++ doing nothing AND still leaving the rest of the files to be searched (especially if the big file were in the beginning of the file list); especially when leaving the computer unattended (but even while using the PC with Notepad++ in the background, as the warning can go unnoticed as it only plays a Windows message sound that could easily be dismissed)

There also may be users that simply don't feel the need to be warned when opening big files (especially on faster machines that don't take "several minutes" to open them, my RAM-starved laptop takes less than 10s for 2GB)

#14053 proposes to add an option to suppress the warning

### Steps to Reproduce the Issue
1. Open a big file
#### Alternatively
1. Open the Search in files window
2. Start a search in a folder containing a big file
3. When Notepad++ tries to open a big file to search it's content, the warning will pop up and halt the search until acted upon

### Expected Behavior
Provide an option to suppress the warning when opening a big file.
Users that don't deem the warning necessary can disable it, and users who want to search in a folder that may contain big files won't have to worry about it halting 

### Actual Behavior
There's no option to suppress the warning
In case of the Search in files function, here's an example of the issue described above:
![image](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/100133857/5f57bc35-08c1-43b9-bb9b-d1ab8db24e88)

Completely halted, not searching in the rest of the files; if I didn't know about having ≥2GB files in a folder with a lot of files I could leave the PC unattended for nothing because of the warning

### Debug Information
Notepad++ v8.5.6   (64-bit)
Build time : Aug 15 2023 - 15:29:28
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 11 Pro (64-bit)
OS Version : 22H2
OS Build : 22621.2215
Current ANSI codepage : 1252
Plugins : 
    ComparePlugin (2.0.2)
    mimeTools (2.9)
    NppConverter (4.5)
    NppExport (0.4)

**Comment by donho** [comment]
@DerivativeOfLog7 
**Steps to Reproduce the Issue**
&
**Expected Behavior**
&
**Actual Behavior**

are important to fill for providing the information to reproduce the bug or inconvenience.

**Comment by DerivativeOfLog7** [comment]
This isn't a bug report, it's a feature request; I tried to fill them but there's not much to say

**Comment by DerivativeOfLog7** [comment]
> @DerivativeOfLog7 **Steps to Reproduce the Issue** & **Expected Behavior** & **Actual Behavior**
> 
> are important to fill for providing the information to reproduce the bug or inconvenience.

This isn't a bug report, it's a feature request; I tried to fill them but there's not much to say

**Comment by donho** [comment]
> this could be an issue especially if it's left doing the search unattended

Regarding this part, you can provide the instructions, or I'm missing something?

**Comment by DerivativeOfLog7** [comment]
> > this could be an issue especially if it's left doing the search unattended
> 
> Regarding this part, you can provide the instructions, or I'm missing something?

Find a folder with a big file (>2gb), start a Search in Files with notepad++ and wait; once it's time to search in the big file npp will popup the warning and halt the search until it's acted upon.

If this happens when the computer is unattended, the rest of  the time is wasted; imagine starting a search in 1000 files only to later find out that it's been stuck near the beginning because of one big file (even if it's not left unattended - iirc even while I was using the computer with npp searching in the background and the warning popped up, there was no real noticeable warning, apart from a windows sound that could easily be dismissed or the user may not be realized what caused it)

Additionally, for people with fast enough computers, the warning could be completely superfluous - on my laptop a 2GB file takes less than 10 seconda to open

**Comment by donho** [comment]
> If this happens when the computer is unattended, the rest of the time is wasted; imagine starting a search in 1000 files only to later find out that it's been stuck near the beginning because of one big file (even if it's not left unattended - iirc even while I was using the computer with npp searching in the background and the warning popped up, there was no real noticeable warning, apart from a windows sound that could easily be dismissed or the user may not be realize what caused it) (this inconvenience alone was enough for me to fork the repo to create a version without the warning, and then opening the pull request)

This is what I'm talking about.
With above information, you can fill:

**Steps to Reproduce the Issue**
1. Open Find in File dialog.
2. Search into a directory in which some huge files exit.
3. ... (to be filled)
4. ... (to be filled)
5. ... (to be filled)

**Expected Behavior**
Just leave 1 hour, the computer working alone, the search goes on.
1 hour later, the search is over, the search result is shown.

**Actual Behavior**
... (to be filled)

Please finish to full fill the template.

**Comment by DerivativeOfLog7** [comment]
> > If this happens when the computer is unattended, the rest of the time is wasted; imagine starting a search in 1000 files only to later find out that it's been stuck near the beginning because of one big file (even if it's not left unattended - iirc even while I was using the computer with npp searching in the background and the warning popped up, there was no real noticeable warning, apart from a windows sound that could easily be dismissed or the user may not be realize what caused it) (this inconvenience alone was enough for me to fork the repo to create a version without the warning, and then opening the pull request)
> 
> This is what I'm talking about. With above information, you can fill:
> 
> **Steps to Reproduce the Issue**
> 
> 1. Open Find in File dialog.
> 2. Search into a directory in which some huge files exit.
> 3. ... (to be filled)
> 4. ... (to be filled)
> 5. ... (to be filled)
> 
> **Expected Behavior** Just leave 1 hour, the computer working alone, the search goes on. 1 hour later, the search is over, the search result is shown.
> 
> **Actual Behavior** ... (to be filled)
> 
> Please finish to full fill the template.

done...
