### ISSUE TITLE
Spacing error after 🏴 character, but only under one condition so far

### ISSUE THREAD

**Issue by SMcCandlish** [notepad-plus-plus/notepad-plus-plus#14056]
### Description of the Issue
Space characters eaten after the 🏴 character in a copy-pasted string.

### Steps to Reproduce the Issue

1. Go to this Facebook page https://www.facebook.com/groups/871997216601215/ and copy the name of the group, "Scotland’s Descendants 🏴󠁧󠁢󠁳󠁣󠁴󠁿"
2. Paste the group name into Notepad++
2. Put one or more space characters after it, then some other text.
3. Notice that the spaces get eaten.

### Expected Behavior
Same as with any other text entry,  you should get "Scotland’s Descendants 🏴󠁧󠁢󠁳󠁣󠁴󠁿  - foo bar baz", with some spaces between the flag and the "-".

### Actual Behavior
You get "Scotland’s Descendants 🏴󠁧󠁢󠁳󠁣󠁴󠁿- foo bar baz", with no spaces between the flag and the "-".

### Debug Information
Notepad++ v8.5.4   (32-bit)
Build time : Jun 17 2023 - 20:40:14
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Command Line : "C:\Users\mech\Documents\Development\McC_server\heraldry.wp.html"
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 10 Enterprise (64-bit)
OS Version : 22H2
OS Build : 19045.3324
Current ANSI codepage : 1252
Plugins : 
    ComparePlugin (2.0.1)
    mimeTools (2.9)
    NppConverter (4.5)
    NppExport (0.4)

If you manually use the 🏴 character, this doesn't seem to happen. Just in a copy-paste (and only from that one source so far, since I haven't been looking for other material with that character to copy-paste from).  UPDATE: Nope, it's happening again when I copy-paste  the first flag from here: https://flagpedia.net/scotland/emoji  This suggests that it's specifcally the emoji code U+1F3F4, assuming they are listing them in the same order.

PS: Depending on your system's Emoji-rendering capabilities, the char may just show up as a black flag instead of Scotland's flag (I think that's what it's supposed to be; I'm one of the black flag receivers because of my Win10 build).

**Comment by alankilborn** [comment]
Maybe try [THIS](https://npp-user-manual.org/docs/preferences/#:~:text=enables%20DirectWrite%20drawing).

**Comment by SMcCandlish** [comment]
Yep, turning on DirectWrite did actually work.

**Comment by alankilborn** [comment]
Okay then, please close this issue.
