### ISSUE TITLE
shell parser extends a comment to next line if line ends with backslash

### ISSUE THREAD

**Issue by whobertoos** [notepad-plus-plus/notepad-plus-plus#14062]
### Description of the Issue

Shell parser. Comment line finishing with backslash causes the following line to be shown as comment. 

### Steps to Reproduce the Issue

1. Open attached IncorrectBackslashHandlingExample.sh.txt file. 
2. Make sure the shell parser is chosen. Language->S->Shell
3. 
4. 

### Expected Behavior

Line 10, 11, 12, 13, and 14 should not be displayed as comment. 

### Actual Behavior

Line 10, 11, 12, 13, and 14 is displayed as comment. 

### Debug Information

Notepad++ v8.5.6   (64-bit)
Build time : Aug 15 2023 - 15:29:28
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : "C:\priv\notepad++issue\IncorrectBackslashHandlingExample.sh.txt"
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 10 Pro (64-bit)
OS Version : 22H2
OS Build : 19045.3208
Current ANSI codepage : 1252
Plugins : 
    mimeTools (2.9)
    NppConverter (4.5)
    NppExport (0.4)

![IncorrectBackslashHandlingExample](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/143410158/7f12b93d-ce80-4ea2-b50c-853d375cd0a1)

[IncorrectBackslashHandlingExample.sh.txt](https://github.com/notepad-plus-plus/notepad-plus-plus/files/12454590/IncorrectBackslashHandlingExample.sh.txt)

**Comment by rdipardo** [comment]
This is [a known issue](https://github.com/ScintillaOrg/lexilla/issues/195) which [has already been fixed](https://github.com/ScintillaOrg/lexilla/commit/8a688e3b2fbbe707a7fc8913bc3eca7388d454d3). It will probably be several weeks before the patched lexer trickles down to Notepad++'s code base.
