### ISSUE TITLE
Website https://notepad-plus-plus.org/ gone?

### ISSUE THREAD

**Issue by happenpappen** [notepad-plus-plus/notepad-plus-plus#14068]
Just realized, that the Website is gone and don't know where else to report this...

**Comment by dail8859** [comment]
@donho

**Comment by donho** [comment]
The website is restored.

**Comment by wjabrac** [comment]
hi @donho I don't even use github enough to know how to open a new thread, or where it would be appropriate. Hopefully, you see this. The website is down and I've tried VPNs from a few countries and flushed DNS so I don't think it's me.  It's been going on for at least 6 or 7 hours.

**Comment by donho** [comment]
@wjabrac Thank you for your heads up. 
It should be OK now, I can access it with no problem.
Please let me know if the problem persists.
