### ISSUE TITLE
[Feature Request] Search window hotkey - toggle (open/close) instead of just open

### ISSUE THREAD

**Issue by TheArkive** [notepad-plus-plus/notepad-plus-plus#14078]
Currently on N++ v8.5.4 64-bit

### Description of the Issue
When assigning a hotkey to open the Search Window, it does just that.  But for my uses, a toggle would be more useful.  Is that change worthy of consideration?

### Steps to Reproduce the Issue
1. Assign hotkey to Search Results Window.
2. Press hotkey multiple times.
3. It always stays open, and won't close with hotkey press (like a toggle would).

This is of course not a big deal.  It would be a minor (but appreciated) change.

**Comment by alankilborn** [comment]
>Assign hotkey to Search Results Window.

It has one by default (F7) -- but of course you can change that.

>Press hotkey multiple times.

If you press the hotkey (F7) _once_ then press Esc, it closes.

**Comment by TheArkive** [comment]
That is helpful, but sometimes I'll shift the focus away from the search window, to investigate deeper into the search, and then ESC won't close the search window unless I click on it again to regain focus.

Not a big deal either way.  I can make do with ESC.  Thanks for the reply 👍

**Comment by alankilborn** [comment]
>sometimes I'll shift the focus away from the search window...

If _Search result_ doesn't have focus, the F7 gives it focus, then Esc closes it.  As an all-keyboard solution it is much faster than mousing to give it focus.

**Comment by TheArkive** [comment]
Yes, I can adjust to that.  Thanks.

Sorry if it seemed like I was making a big deal out of something small.

Thanks for your time.
