### ISSUE TITLE
NPP using a lot o CPU

### ISSUE THREAD

**Issue by LeandroMagno73** [notepad-plus-plus/notepad-plus-plus#14075]
### Description of the Issue

Notepad++ process is using more than 5% of computing power, even when left in background.
I´ve been uninstalling, reinstaling, installing a lower version, and it allways do the same.
Windows 11, 64bits version.

### Steps to Reproduce the Issue

1. Install Notepad++
2. Run it.

### Expected Behavior

Just be quiet or suspended.

### Actual Behavior

Uses a lot of CPU.

### Debug Information

Notepad++ v8.5.6   (64-bit)
Build time : Aug 15 2023 - 15:29:28
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 11 Home Single Language (64-bit)
OS Version : 22H2
OS Build : 22621.2215
Current ANSI codepage : 1252
Plugins : 
    HexEditor (0.9.12)
    mimeTools (2.9)
    NppConverter (4.5)
    NppExport (0.4)

**Comment by xomx** [comment]
My guess: #11556 (Brazilian banks TOPAZ OFD/Warsaw rootkit installed).

**Comment by LeandroMagno73** [comment]
Just stop using.

--
  Leandro


Em qua., 30 de ago. de 2023 às 17:52, xomx ***@***.***>
escreveu:

**Comment by donho** [comment]
Check #11556
