### ISSUE TITLE
[FEATURE REQUEST] Disable spell checker while printing

### ISSUE THREAD

**Issue by WalterHof** [notepad-plus-plus/notepad-plus-plus#14084]
### Description of the Issue
Spell checker marks unknown words with an red underline. Printing a document with enabled spell checker,
prints these unknown words with an red underline. This is in most cases not useful and not wanted.

### Expected Behavior

Allow printing without the red underline. I. e. automatically disable the spell checker.
Please add an option to disable spell check (DSpellChek) while printing and re enable spell check after printing.

**Comment by alankilborn** [comment]
The spell checker is not part of Notepad++.
It is a plugin.
You'd have to find the support site for the spell checker and make the request there.
Please close this issue.

**Comment by WalterHof** [comment]
I found the developer and created the issue: https://github.com/Predelnik/DSpellCheck/issues/328
