### ISSUE TITLE
Same crash as 6.8.9 using 6.8.8

### ISSUE THREAD

**Issue by art-losangeles** [notepad-plus-plus/notepad-plus-plus#1409]
As I read the description of the problem with 6.8.9, I had the exact same issue with 6.8.8. Had document open in N++, did something else, came back to N++ and it reported the document had changed outside of N++, clicked "YES" and got a crash. Document was vbscript. Document gone with no backup made (no sure why that would be as backup was enabled). The last version I downloaded and installed was 6.8.8 and never tried to upgrade from that.

On Windows XP.

**Comment by donho** [comment]
Could you reproduce the steadily?

**Comment by art-losangeles** [comment]
I just tried and I cannot seem to reproduce it. I tried several different combinations of opening and closing.

Now that I think about, I believe my crash occurred when I switched the focus back to N++ after having done other things for a few hours. I think it was merely bringing N++ to the front that caused the crash. When I reopened N++ I got the message about "document changed outside do you want to reopen" and selected "Yes." I must admit I wasn't paying a lot of attention to the specifics of the crash at that point as the crash replaced the document I spend a couple of days working on with a blank document and I lost a lot of my work. I was kind in a bit of a panic on THAT rather than the crash. I found the backup using an undelete program (don't know why it was deleted as I did find other unsaved backups in the backup directory) but it seemed to contain an embedded PNG file?!?

I've attached the undeleted backup - the end is the end of my vbscript document but the beginning seems to be a png. I don't expect any action - just thought you might find the file interesting. I don't know how the code of a PNG could get into a text file - and it seems to be a Firefox cache file of some sort.
[test-002_record-IDs.zip](https://github.com/notepad-plus-plus/notepad-plus-plus/files/104653/test-002_record-IDs.zip)
