### ISSUE TITLE
WANTED FEATURE: Tab Separation Support

### ISSUE THREAD

**Issue by Sahil-Verma-Vectra** [notepad-plus-plus/notepad-plus-plus#14105]
### Description of the Feature

When multiple text files are opened in Notepad++, there is no option to separate two tab so we can work on it side by side. Instead of switching tabs again and again, I would like to drag one tab and place it on another screen.

**Comment by Sahil-Verma-Vectra** [comment]
Oh. This is great. I was not aware of this feature. Is there any option to completely detach it and set it to another screen. Basically what I envisioned was that we can open multiple Notepad++ instances.

**Comment by alankilborn** [comment]
>Basically what I envisioned was that we can open multiple Notepad++ instances.

See where I said "Choose Move to New Instance".

Also see user manual:  https://npp-user-manual.org/docs/preferences/#multi-instance-and-date

If satisfied, please CLOSE this issue.

**Comment by Sahil-Verma-Vectra** [comment]
I'm yet to go over the documentation. Didn't notice that earlier. Thanks for pointing it out to me. I'll close this issue.
