### ISSUE TITLE
Windows 11 Print Dialog Error

### ISSUE THREAD

**Issue by krutzy62** [notepad-plus-plus/notepad-plus-plus#14109]
### Description of the Issue
Printing in Windows 11 gives print error 0x80040003.  If run Notepad++ as admin, prints as expected.   Quick print works

### Steps to Reproduce the Issue
1.  With a file open select  print to open print dialog
2.  
3. 

### Expected Behavior
See print dialog 

### Actual Behavior
Error:  Your printer experienced an unexpected configuration problem.  0x80040003
Run as admin prints fine
Quick print works fie

### Debug Information

Notepad++ v8.5.6   (64-bit)
Build time : Aug 15 2023 - 15:29:28
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 11 Pro (64-bit)
OS Version : 22H2
OS Build : 22621.2215
Current ANSI codepage : 1252
Plugins : 
    ComparePlugin (2.0.2)
    mimeTools (2.9)
    NppConverter (4.5)
    NppExport (0.4)

I saw others having problem and saw someone suggest posting it here.   When I looked I didn't see it posted so I am doing it, hopefully not duplicating a issue reported.
All other PC applications print as they should - only Notepad++ has this error on my system.

**Comment by xomx** [comment]
Cannot reproduce (Win11 Enterprise 22H2):
![npp-win11-printdlg-ok](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/13075183/a35cb6c6-de18-4de0-82b7-f7d7f1f6e3de)

Relevant [Community thread](https://community.notepad-plus-plus.org/topic/23719/print-error-0x80040003), maybe a HP printer driver problem(?)

**Comment by krutzy62** [comment]
Yes I saw that work around before the latest update.  Since an update just came out I had hoped it had been resolved and was just making sure it was known here.  
Thank you though for the reply.

**Comment by Frnkcox6** [comment]
I have loved NOTEPAD++ for many years, and have the most current version  - npp.8.5.7.Installer.x64.exe - installed on my WIN11 PC.  However, I suddenly cannot print to my HP printer, as I get the message: "Your printer has experienced an unexpected configuration problem 0x80040003".  I have, of course, cleared my printer spooler, cold booted the printer & PC, checked drivers, run the troubleshooter & HP Doctor, etc. etc.  All works well - only Notepad++ is the problem.  Others report they have reinstalled drivers, reinstalled Windows, and chanted curses - all to no avail. 

I see an older Community discussion at   https://community.notepad-plus-plus.org/topic/23719/print-error-0x80040003  that others experience this same bug.  For some reason, I cannot log in there w/o joining Facebook (ugh - intolerable!).  I did join GITHUB but I'm clueless as a programmer.   An interim fix, open Notepad++ as an Administrator on the file (just giving it Admin privileges won't work), and you can print that file OK - but this means kludging around one file at a time.  

The "final" posted answer suggested someone who (a) can program in C++ and (b) can replicate the issue to solve the problem should go on GITHUB and fix it.   I am NOT a programmer.   Can someone suggest a 'permanent' fix so Notepad++ users can easily print TXT files w/o this error?

**Comment by xomx** [comment]
Can you check if [this solution](https://h30434.www3.hp.com/t5/Printers-Archive-Read-Only/Can-only-print-with-Admin-privileges/m-p/5635480/highlight/true#M3318448) helps?

There are other [similar reports](https://h30434.www3.hp.com/t5/Printer-Setup-Software-Drivers/administrator-required-to-print/td-p/5844301) at the HP site, so maybe it could help. If not, you can also try asking at that HP support site what to try next.

**Comment by krutzy62** [comment]
I looked at my file permissions for my \User\krutz\AppData\Local\Temp folder an I have full control of it already (see attached).
Great idea, probably on the right track, but not this one.  
![npp](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/43507966/21d4c3ef-4805-420a-a49b-88cabc87d08d)

**Comment by xomx** [comment]
Well, my guess is that this issue has nothing to do with N++. There are [similar reports](https://h30434.www3.hp.com/t5/Printer-Setup-Software-Drivers/resolve-error-code-0x80040003/m-p/7167647/highlight/true#M163386), where user cannot print from one specific app.

Maybe you could at least test that your current user profile does not have any negative effect on it - create a new user account and try to print from there...

**Comment by krutzy62** [comment]
To be frank, it is the only application that I have an issue with.  I have a lot of non-mainstream programs (amateur radio related) that is opensource and this is the only one I have issues with.  Now how they "call" the printer might be different.
I have attached the print dialog and I wonder if this could be the cause?  In order to do that, does that require admin permissions.  I turn it off but it comes back if I try to print again.  Just a shot.
In all fairness this is an older printer.  Getting it work with Win 11 took some digging.  So it could be just that.  I just could be my setup and since npp is the only app I am getting the error I can live with it and it could be a system issue vs. an application error.
Thank you for your help!
![npp dialog](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/43507966/ddd417cc-9a3e-4b6c-a782-d64909849873)

**Comment by xomx** [comment]
Hmm, old printer == old driver and MS forced in the Win11 22H2 new UWP/Store-apps print dialogue even to all the classic WIN32 apps - so maybe [this](https://www.winhelponline.com/blog/restore-legacy-print-dialog-windows-11/?expand_article=1) will help you.

**Comment by krutzy62** [comment]
Bingo!  That fixed it and Windows Notepad too.  Thank you!!!

I appreciate it very much!

**Comment by Frnkcox6** [comment]
Hmm the "let the app change my printing preferences' didn't work for me. 
So I POSTED THIS ON THE HP FORUM:

Printing from NOTEPAD++ to my HP Officejet Pro 8620 -> "unexpected configuration problem 0x8004000"
---
I see many similar users report "Your printer has experienced an unexpected configuration problem 0x80040003",  This only happens to me when I print from NOTEPAD++ to my HP OFFICEJET PRO 8620.  I can print easily using MS Office, Foxit PDF printer, Notepad plain, and similar apps.  

Sometimes HP rep recommends a total deletion of the print spooler + drivers and then reinstallation from scratch. To quote one user who did this and more : "....ok,,,,6 hours and this is not working. ...." UGH. So I have:
- Updated ALL Microsoft Windows11 software and all drivers. Checked multiple times.
- Run HP Doctor and HP SMART printer settings and Win11 Troubleshoot Printer.... NO luck.
- Given myself FULL control of Notepad++ Go to Notepad++ > Properties > Security > Allow Full Control
- Created a new user on Windows and tried to print Notepad++ No success
- I have NOT moved my %USERPROFILE%\AppData\Local\Temp from default as another person did.
- I have rolled back Notepad++ to earlier version (no improvement, I'm back to npp.8.5.7.Installer.x64.exe)
- i have posted the problem on GITHUB Notepad++ forum, and have been told please post it on HP FORUM. 
SO
Does anyone know the secret incantation that will make this specter go away.?

**Comment by rdipardo** [comment]
> Does anyone know the secret incantation that will make this specter go away.? 

Did you replace the new-fangled print dialog "app" with the "legacy" dialog as explained in the help article that @xomx [shared above](https://github.com/notepad-plus-plus/notepad-plus-plus/issues/14109#issuecomment-1730172732)?, i.e. [Restore the Legacy Print Dialog in Windows 11 22H2](https://www.winhelponline.com/blog/restore-legacy-print-dialog-windows-11/?expand_article=1)

**Comment by Frnkcox6** [comment]
THIS FIXED THE PROBLEM!
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
read this article
Restore the Old Print Dialog in Windows 11 22H2
https://www.winhelponline.com/blog/restore-legacy-print-dialog-windows-11/?expand_article=1

1. Open Command Prompt (run as administrator)
2. Copy/paste this line to activate the OLD old print dialog in Windows 11 before Win11 version 22H2 messed it up: 
	reg add "HKCU\Software\Microsoft\Print\UnifiedPrintDialog" /v "PreferLegacyPrintDialog" /d 1 /t REG_DWORD /f
3. If the command was executed correctly, you should see the message “The operation completed successfully.”
4. My NOTEPAD++ now Prints to my HP OfficeJet Pro 8620 printer.  	
 
Thank you!

**Comment by dtrout** [comment]
I know this is an old thread, but I have recently discovered new information on this problem that I'd like to add in case anyone else is trying to solve this issue.

I recently setup a new Windows 11 Pro machine (latest 24H2 patch level), installed the latest Notepad ++ (8.7.8 64-bit), and installed my HP 9135e OfficeJet Pro printer.

I immediately hit the problem documented here by the original poster.  To get around it, I did the Registry mod as identified in this thread and that got me back to the older Windows 10 print dialog as indicated and everything was working fine when printing from Notepad ++.

A while later I discovered that my HP 9135e printer installation included BOTH a "Type 3" driver and a "Type 4" driver as follows:
```
HP OfficeJet Pro 9130 Series PCL3 (V3)
HP OfficeJet Pro 9130 Series PCL-3 (V4)
```

A little research revealed that Type 4 drivers in Windows use XPS (XML Paper Specification Document format), an apparently enhanced version of the Type 3 drivers which use GDI/EMF format.  **It turns out that if you select the V4 driver for your HP printer, Notepad++ will work just fine with new printing dialog in Windows 11.**  You will still see the "This app doesn't support print preview" message in the dialog preview window, but that's completely normal for apps like Notepad ++.  Previews would typically be generated by apps like MS Office etc.

You can select the driver to be used with the printer in this Printer Properties dialog window:

![Image](https://github.com/user-attachments/assets/4d94b423-88cb-49ae-bcaf-5ee648e422bc)

Now, when you print from Notepad ++ you'll see the new Windows 11 print dialog:

![Image](https://github.com/user-attachments/assets/d43b18e1-cf73-44ab-8908-27f8fd7f3a46)

I have no idea if all recent HP printers include both driver versions, but it's easy to check if you have a V4 driver available and worth doing if you are having the problem documented in this thread.
