### ISSUE TITLE
Notepad++ won't print.  Reports unexpected configuration problem 0x80040003

### ISSUE THREAD

**Issue by Frnkcox6** [notepad-plus-plus/notepad-plus-plus#14124]
I have loved NOTEPAD++ for many years, and have the most current version  - npp.8.5.7.Installer.x64.exe - installed on my WIN11 PC.  However, I suddenly cannot print to my HP printer, as I get the message: "Your printer has experienced an unexpected configuration problem 0x80040003".  I have, of course, cleared my printer spooler, cold booted the printer & PC, checked drivers, run the troubleshooter & HP Doctor, etc. etc.  All works well - only Notepad++ is the problem.  Others report they have reinstalled drivers, reinstalled Windows, and chanted curses - all to no avail. 

I see an older Community discussion at   https://community.notepad-plus-plus.org/topic/23719/print-error-0x80040003  that others experience this same bug.  For some reason, I cannot log in there w/o joining Facebook (ugh - intolerable!).  I did join GITHUB but I'm clueless as a programmer.   An interim fix, open Notepad++ as an Administrator on the file (just giving it Admin privileges won't work), and you can print that file OK - but this means kludging around one file at a time.  

The "final" posted answer suggested someone who (a) can program in C++ and (b) can replicate the issue to solve the problem should go on GITHUB and fix it.   I am NOT a programmer.   Can someone suggest a 'permanent' fix so Notepad++ users can easily print TXT files w/o this error?

**Comment by xomx** [comment]
Duplicate of #14109.
Please close this issue and use the previous one instead.

(Note: Maybe it really looks like a "HP-problem" like a said before.)

**Comment by Frnkcox6** [comment]
This posting is CLOSED.... MOVED TO  Windows 11 Print Dialog Error #14109  at 
https://github.com/notepad-plus-plus/notepad-plus-plus/issues/14109
thanks
Frnkcox6
