### ISSUE TITLE
Sort preferences

### ISSUE THREAD

**Issue by JoeBrunsTR** [notepad-plus-plus/notepad-plus-plus#14120]
### Description of the Issue
Cosmetic

### Steps to Reproduce the Issue
Click on Settings > Preferences

### Expected Behavior
Sort the list (left pane)

### Actual Behavior
Scrambled list

**Comment by JoeBrunsTR** [comment]
What release will this be made available?

**Comment by alankilborn** [comment]
>What release will this be made available?

It won't be.  I believe @donho meant to give this a "rejection".
