### ISSUE TITLE
(feature request) Numbered ordering list

### ISSUE THREAD

**Issue by ZhuanM** [notepad-plus-plus/notepad-plus-plus#14144]
### Description of the feature request
I'd love an ordered number list functionality, similarily to found in Microsoft Word for example.
I use Notepad++ to manually enter lists (since I love Notepad++ and its speed and dislike Microsoft Word for many reasons) and daily I run into situations like this:
1. Test 1
2. Test 2
3. Test 3
and so on up until let's say "50. Test 50"

And I want to add a line/item between "2." and "3.". I'd have to manually change the numbers of each line/item afterward, which could be very tiresome and annoying. Having this functionality that will also automatically change the numbering could be an insane boost in productivity for people like us, as we won't have to waste time manually changing numbers several times a day, which adds up over time.

**Comment by alankilborn** [comment]
You could use the *Column Editor* to fairly painlessly renumber...  Default keycombo to invoke is Alt+c

**Comment by ZhuanM** [comment]
I see, didn't know about that. However, it seems to be missing quite an essential functionality - automatic renumbering. If I create a list:
1 ) Test 1
2 ) Test 2
3 ) Test 3

And then decide to add a line/item between "2" and "3", as I said in my original post, then using the _Column Editor_ will just add numbers in front of the original numbers. So the only solution would be manually deleting all numbers and then using the _Column Editor_ to add them back in an ordered way, which seems to be about just as inconvenient as the original manual method. Also, it seems that we cannot add other characters, such as `)` or `.` with a space afterward, in front of the numbers. We can only add a leading _zero_ or _space_ before the number.

**Comment by alankilborn** [comment]
Notepad++ is a text editor, not a word processor, so you're not going to get any "automatic renumbering".

Regarding manually renumbering of some previously numbered list, I'd put my caret on the first numbered item and then Shift+Alt+downarrow multiple times to get a thin caret across all lines that are numbered.  Then a few delete presses removes old numbering on all lines, then _Column Editor_ can insert new numbers.

I do such a series of actions often; once you do it a few times, it's fairly easy.  

Regarding adding a `)` or a `.`, I also do this often.  Once you have the thin caret spanning multiple lines, just typing a `.` (for example) will insert it at the thin caret position on all lines.

The _Better Multiselection_ plugin can also be a help here (as the "thin caret" is really a multi-selection).
