### ISSUE TITLE
Function Find missing sentences 

### ISSUE THREAD

**Issue by podtor** [notepad-plus-plus/notepad-plus-plus#14153]
### Description of the Issue

Function Find missing sentences 

### Steps to Reproduce the Issue

1.  Create new file
2.  put into file one line "10-06-2023"
3.  Ctrl+F and try to find "10-06-2023"

### Expected Behavior

Find "10-06-2023" sentence

### Actual Behavior

Function Find don't find "10-06-2023" sentence

### Debug Information

but function Find all in Opened Documents can find "10-06-2023" sentence

**Comment by alankilborn** [comment]
Works fine for me in 8.5.7.
When it happens for you, show screenshot of your _Find_ window, like this:

![image](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/77065706/c6affebe-1818-40ae-ba08-925457577c07)

**Comment by podtor** [comment]
I confirm that in 8.5.7 is correct.
