### ISSUE TITLE
Error #14109

### ISSUE THREAD

**Issue by Frnkcox6** [notepad-plus-plus/notepad-plus-plus#14169]
### Steps to Reproduce the Issue

1. 
2. 
3.

**Comment by alankilborn** [comment]
?

**Comment by rdipardo** [comment]
I think he means [this](https://learn.microsoft.com/en-us/windows/win32/debug/system-error-codes--12000-15999-#:~:text=ERROR_GENERIC_COMMAND_FAILED):

    ERROR_GENERIC_COMMAND_FAILED

    14109 (0x371D)

**Comment by alankilborn** [comment]
Well, even if he does, I'm not sure how anyone would do something with that information...
Hint:  Fill out the issue template.

**Comment by Frnkcox6** [comment]
My Typo Error when I was trying to do a search!  Sorry about that. 
I'm closing this oops and think the discussion can be found here: 
https://github.com/notepad-plus-plus/notepad-plus-plus/issues/14109
