### ISSUE TITLE
NPP 8.5.7 session will not remember the position within a document anymore

### ISSUE THREAD

**Issue by Bro-Account** [notepad-plus-plus/notepad-plus-plus#14164]
### Description of the Issue
When closing NPP and starting it again, NPP used to remember the position within a file when restoring the session. Starting with NPP 8.5.7, NPP will re-open the files, but the position will be at the beginning for all tabs.

### Steps to Reproduce the Issue

1. Open a long file
2. Clone the file to the other view (keep it open in the left pane)
3.  Scroll down within the file on the right pane
4.  Close NPP and reopen it.

### Expected Behavior
NPP should reopen at the previous position within the file(s).

### Actual Behavior
NPP displays all files opened in both panes at Line 1 in the right pane.

### Debug Information
Notepad++ v8.5.7   (64-bit)
Build time : Sep  6 2023 - 23:13:49
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 11 Pro (64-bit)
OS Version : 22H2
OS Build : 22621.2283
Current ANSI codepage : 1252
Plugins : 
    mimeTools (2.9)
    NppConverter (4.5)
    NppExec (0.8.2)
    NppExport (0.4)
    SQLinFormNpp64 (6.23.3.24)

**Comment by Yaron10** [comment]
@Bro-Account,

I can not reproduce it.
Could you try it with a fresh portable Notepad++?

**Comment by Bro-Account** [comment]
> @Bro-Account,
> 
> I can not reproduce it. Could you try it with a fresh portable Notepad++?

Sorry, I found what I was missing in the initial description and I didn't notice it so far.
Clone the document to the other pane. The issue will only occur in the right pane.

**Comment by Yaron10** [comment]
@Bro-Account,

I can reproduce that.

https://github.com/notepad-plus-plus/notepad-plus-plus/commit/f4297f1a837c93e09962715c40ba932567d46aa2 fixed another issue and caused this regression.

@donho & @molsonkiko,

Could you please have a look?

**Comment by GwenDragon** [comment]
I can confirm this issue for 8.5.8 (64bit) Windows 11 22H2

**Comment by donho** [comment]
Thank you @Yaron10 for the ping and for the tip.
The commit which causes the regression has been reverted.

**Comment by Bro-Account** [comment]
Unfortunately, this is still not working for me in 8.6.1. I also tried to close the Document in the right pane and to re-clone it there, but after restarting NPP 8.6.1, it will still show me the start of the text file.

**Comment by Yaron10** [comment]
@Bro-Account,

You're right, your issue & https://github.com/notepad-plus-plus/notepad-plus-plus/issues/14461 are not properly fixed.
https://github.com/notepad-plus-plus/notepad-plus-plus/issues/10266 & https://github.com/notepad-plus-plus/notepad-plus-plus/issues/10365 are not fixed either.

***

https://github.com/notepad-plus-plus/notepad-plus-plus/pull/14451#issuecomment-1844115449

> https://github.com/notepad-plus-plus/notepad-plus-plus/commit/a51e62c16dc45160afe6c7deb19096e98ad18372.
Does not fix anything.

***

https://github.com/notepad-plus-plus/notepad-plus-plus/pull/14431#issuecomment-1872281691

> https://github.com/notepad-plus-plus/notepad-plus-plus/commit/a51e62c16dc45160afe6c7deb19096e98ad18372
Try it with new untitled cloned document, and with 2 sets of cloned files.

**Comment by donho** [comment]
I have tested again, and observed that only one case works with https://github.com/notepad-plus-plus/notepad-plus-plus/commit/a51e62c16dc45160afe6c7deb19096e98ad18372 : only 1 file opened in the 1st view and its clone opened in the 2nd view.

If there are any other file opened in the 1st or the 2nd view, it doesn't work. So https://github.com/notepad-plus-plus/notepad-plus-plus/commit/a51e62c16dc45160afe6c7deb19096e98ad18372 doesn't fix completely the issue. The issue will be reopened.
