### ISSUE TITLE
Unselected lines may become hidden

### ISSUE THREAD

**Issue by Adrian104** [notepad-plus-plus/notepad-plus-plus#14166]
### Description of the Issue
Suppose that the content of the document alternates between visible individual lines and hidden blocks of text. In this situation, when the user tries to hide a single line, only that should become hidden. Instead, program hides all the lines that alternate between already hidden blocks of text.

### Steps to Reproduce the Issue
**Step 1.** Copy and paste the following text in a new document:
```
Line 1
 Line 2    (hide)
  Line 3
   Line 4  (hide)
    Line 5
   Line 6  (hide)
  Line 7
 Line 8    (hide)
Line 9
```

**Step 2.** Hide labeled lines. It should look like this:  
![A](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/63365428/a1c1373a-b771-48fc-ac75-bc46ccd74f9d)
**Step 3.** Select **only** the line number 5 and hide it.

### Expected Behavior
Line 1, 3, 7 and 9 should remain visible:  
![B](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/63365428/8c944224-ea6d-4d73-9e77-5c09f7226417)

### Actual Behavior
Only line 1 and 9 are visible:  
![C](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/63365428/22f70b92-cac8-4a55-9140-5dc50be0fc5c)

### Debug Information
```
Notepad++ v8.5.7   (64-bit)
Build time : Sep  6 2023 - 23:13:49
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 10 Home (64-bit)
OS Version : 22H2
OS Build : 19045.3448
Current ANSI codepage : 1252
Plugins : none
```

**Comment by alankilborn** [comment]
This joins a long list of issues about problems with hiding lines in Notepad++.
