### ISSUE TITLE
add shortcut window/windows

### ISSUE THREAD

**Issue by bbitere** [notepad-plus-plus/notepad-plus-plus#14179]
please add shortcut window/windows

**Comment by alankilborn** [comment]
Fairly fast method:

* Press and hold `Alt`
* Press and release `w`
* Press and release `w`
* Release `Alt`

**Comment by P0rsche-911** [comment]
These keyboard shortcuts only work well in English. Other languages may have different letters.
In Spanish it is with "P" for Pestañas.

**Comment by alankilborn** [comment]
>please add shortcut window/windows

_Window_ > _Windows..._ is not allowed to be tied to a custom shortcut mapping in 8.5.7.

**Comment by bbitere** [comment]
it 's working. please, put this info somewhere to be visible in application. thanks
