### ISSUE TITLE
Horizontal scroll bars never shrink

### ISSUE THREAD

**Issue by seppo498573908457** [notepad-plus-plus/notepad-plus-plus#14176]
### Description of the Issue

When editing the longest row and making it shorter, horizontal scroll bar is not updated to reflect new document "width".
Do not change the vertical scroll bar, it's perfect.

### Steps to Reproduce the Issue

1. Make a long row, that goes past your viewport and enables the horizontal scroll bar. I made the window smaller to emphasize the problem.
![npp1](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/39709137/9caff8b0-4071-491f-a383-c1cffbadde75)
3. Cut the row in half with a line feed.
![npp2](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/39709137/7e5dc7d5-6e14-49b9-99e0-4c601f6ec6d8)
5. Scroll to right. The horizontal scroll bar goes past end of row. If I were to reduce the line lengths even shorter, the scroll bar would go relatively even further away.
![npp3](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/39709137/9a804b3d-daf5-4c13-a2ef-d7d66aa56457)

### Expected Behavior

The length of the horizontal scroll bar should be updated to reflect the new, shorter than before, longest row.

### Actual Behavior

Horizontal scroll bar never shrinks, except when restarting the whole app.

### Debug Information

Notepad++ v8.5.7   (64-bit)
Build time : Sep  6 2023 - 23:13:49
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 10 Enterprise (64-bit)
OS Version : 22H2
OS Build : 19045.3324
Current ANSI codepage : 1252
Plugins : 
    ComparePlugin (2.0.2)
    mimeTools (2.9)
    NppConverter (4.5)
    NppExport (0.4)
    NPPJSONViewer (2.0.5)
    NppMarkdownPanel (0.7.3)
    pork2sausage (2.3)
    Python Indent (1.0.0.4)
    PythonScript (2)
    SQLinFormNpp64 (6.23.3.24)
    XMLTools (3.1.1.13)

**Comment by alankilborn** [comment]
Rejected before, see https://github.com/notepad-plus-plus/notepad-plus-plus/issues/9494

Please search for existing issues before creating new ones on the same topic.

Please close this issue.
