### ISSUE TITLE
Recover search string after accessing search history

### ISSUE THREAD

**Issue by Cerno-b** [notepad-plus-plus/notepad-plus-plus#14174]
### Description of the Issue

I think it would be store the contents of the search line edit, in case someone accidentally presses the down key while writing a search term.

Tested in 8.5.2

### Current Behavior

1. Enter search text
2. Press down key (search text is replaced by history entry)
3. Press up (nothing changes, original search text is lost)

This can be pretty annoying if you try to write a complex regex term only to accidentally hit arrow up instead of arrow left so you have to start over.

### Expected Behavior

1. Enter search text (draft is stored somewhere)
2. Press arrow down
4. Press arrow up (draft is restored, only if going up from the first history element)

**Comment by alankilborn** [comment]
From someone who has fat-fingered the down key when I meant to hit left/right, this issue seems reasonable.

**Comment by donho** [comment]
Do we have any similar request? If not, I prefer to not implement it.

**Comment by alankilborn** [comment]
I have seen it at least once before, either here or more likely on the Community support site.
If you need me to, I will try to find it. If there's no interest, I won't bother.

**Comment by Yaron10** [comment]
There are two parts here:
1. "only to accidentally hit arrow up instead of arrow left" & "fat-fingered the down key".
\- My first thought was: you can accidentally hit the DEL key and lose your complex regex (and yes, it's not quite the same).
2. An option to save the search-term without executing a search.
\- This might be a bit unconventional, but can be useful.

As you understand.

**Comment by alankilborn** [comment]
>accidentally hit the DEL key and lose your complex regex

But this would require the text in the _Find what_ box to be entirely selected first, and this would be rather a rare event for the user to find himself in.

**Comment by alankilborn** [comment]
The OP has put forth a simple solution to a real problem.  I like it; I like its simplicity.  I like its unobtrusiveness to the user (no additional options/settings/controls).  Having an "undo" for changes on _Find what_ would also suffice, but this would necessitate a lot of code/change, AFAIK.

**Comment by Yaron10** [comment]
> you can accidentally hit the DEL key and lose your complex regex (and yes, it's not quite the same).

You can also Undo. :)
Yes, it's not quite the same.

**Comment by Yaron10** [comment]
Another _minor_ point:

Currently (master) the user can easily know if a search has been executed for the term in "Find what".
It might be slightly confusing with the proposed PR.

**Comment by alankilborn** [comment]
>can easily know if a search has been executed for

One would think that a user that has a fat-finger moment will remember it when he is saved by this feature, and will be sure to mentally note that one of the entries in the history is "unexecuted".  And he'll be really glad to do so.

**Comment by Yaron10** [comment]
@alankilborn,

I 👍 your PR, and I'm not retracting it. :)
I was just sharing some thoughts here.

**Comment by Cerno-b** [comment]
> Do we have any similar request? If not, I prefer to not implement it.

Would you share some info on your reluctance with it? Do you think the issue is not relevant or do you think the proposed solution has some flaws? I consider the issue to be an annoyance, but maybe my proposal could be improved.

**Comment by Cerno-b** [comment]
@donho I created a PR that does what I initially wanted and takes into account your comments.

**Comment by Cerno-b** [comment]
@donho After your revert, I created a new PR that addressed the bug found by @alankilborn.
