### ISSUE TITLE
Crash on using RegEx

### ISSUE THREAD

**Issue by ulu** [notepad-plus-plus/notepad-plus-plus#1417]
I tried to erase (Ctrl + H) all lines (Button "replace all") from a log file using following RegEx: (^(.(?!.img)(?!md5sum))*$)

The pattern matches all lines which do not contain ".img" or "md5sum". NPP crashes immediately. Erasing a single line works for me.

[nppDump.zip](https://github.com/notepad-plus-plus/notepad-plus-plus/files/106925/nppDump.zip)

**Comment by donho** [comment]
@ulu  could you provide debug info via menu "?->Debug Info" ?

**Comment by ulu** [comment]
Sorry for delay. I cannot reproduce this anymore because I have no clue what the file was nor if I updated npp. My current version v6.8.7 does not show this behavior with a 32 MByte file. Sorry.
