### ISSUE TITLE
Highlighting of current word disappears when file is (automatically) reloaded

### ISSUE THREAD

**Issue by michel53** [notepad-plus-plus/notepad-plus-plus#14186]
### Description of the Issue

Highlighting disappears when the file is (automatically) reloaded.

### Steps to Reproduce the Issue

1. I have a logfile that is automatically updated by an external application
2. In the file, I highlight a token (all occurences of this token are highlighted)
3. After some time, the file is updated from external application

### Expected Behavior

All occurences of the token should stay highlighted after a file reload/update, eventually adding new occurrences.
This was the case in a former version of notepad++ (8.5.1)

### Actual Behavior

The highlighting is removed

### Debug Information

Notepad++ v8.5.7   (32-bit)
Build time : Sep  6 2023 - 23:07:35
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Command Line : c:\Projekte\DSP\CCS_Workspace\CCS_Workspace_newest\.metadata\.plugins\org.eclipse.debug.core\.launches\Industrie_NG_REC_IGBT_280049_XDS200.launch
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 10 Enterprise (64-bit)
OS Version : 21H1
OS Build : 19043.1348
Current ANSI codepage : 1252
Plugins : 
    mimeTools (2.9)
    NppConverter (4.5)
    NppExport (0.4)

**Comment by alankilborn** [comment]
I think you mean "styling"...?

![image](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/77065706/ff027d80-4cdc-4939-892d-d41a0fa0596f)

**Comment by alankilborn** [comment]
>All occurences of the token should stay highlighted after a file reload/update, eventually adding new occurrences.
This was the case in a former version of notepad++ (8.5.1)

No, it did NOT work this way in 8.5.1.  Any type of "reload" causes all styling to be reset.  This has always been "by design" and I don't think Notepad++ will entertain a change to retain the styling after reload.

>eventually adding new occurrences

This also has never been a design criterion for the way styling works in Notepad++.

**Comment by michel53** [comment]
Sorry, maybe I was not exact enough.
I mean the colour marking when I double click on an expression/word in the file, not the styling that has to be selected via context menu as you showed.

![grafik](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/18734724/13624f4f-2331-48f9-b010-3472282c0489)

**Comment by alankilborn** [comment]
Ok, we've established that you are talking about the _Smart Highlighting_ feature.

But still, a reloading of a document resets pretty much everything, so if you want a word smart-highlighted after reload, you're going to have to double-click it again.

**Comment by michel53** [comment]
Okay, even if it was different in 8.5.1 (there reloading kept the smart highlighted words)?
Was this changed intentionally?

**Comment by alankilborn** [comment]
> even if it was different in 8.5.1 (there reloading kept the smart highlighted words)?

I cannot reproduce that in 8.5.1.  
There a reload cancels the smart-highlighting, just like the current version 8.5.7.

**Comment by michel53** [comment]
Okay, so I just have to live with it.

**Comment by alankilborn** [comment]
Maybe someone else can repro your behavior in 8.5.1?
But, I don't know, if it happens then it becomes an inconsistency (where some things are reset on a reload, but not ALL things).
So, consistency is better, so I'd say no change will come from this.
