### ISSUE TITLE
TYPO Small Typos Found in Quote Easter Eggs

### ISSUE THREAD

**Issue by RHornberger20** [notepad-plus-plus/notepad-plus-plus#14182]
I found a few small typos in some quote Easter Eggs:

![image](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/71733231/f51c3b42-c119-4e5c-8d72-180451492044)
![image](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/71733231/e8e38d8b-f40f-48cc-aeb8-3d7be93f50aa)

I think an "an" should be added: "Should an array index start at 0 or 1? My compromised solution is 0.5."

![image](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/71733231/d0b4e478-7e92-4603-80d1-872b64b17fd9)
![image](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/71733231/4c428773-9773-43d9-9f31-659838c26851)

"The smartphone is the best invention of the 21st century for avoiding eye contact with people you know while crossing the street."

![image](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/71733231/b9838106-953a-4800-bf1c-acf9c6786cc7)
![image](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/71733231/a828c31b-3cb0-416a-8f65-d3b7c3c35ba8)

The "I" should be capitalized (you should also stay away from graveyards): 
"I love necrophilia, but I can't stand the awkward silences."

**Comment by RHornberger20** [comment]
I just found where these are in the source code. I can update these if needed.

**Comment by alankilborn** [comment]
@RHornberger20 
Per the contributing guidelines, typos are not to be fixed by user submission.

@donho In the spirit of that other recent change, perhaps the quote about "necrophilia" should simply be deleted.  If not, I'm sure future complaints will come.

**Comment by RHornberger20** [comment]
@alankilborn Yep, I originally commented that I could fix them in the source code, and deleted my message after I looked at the guidelines more closely. I agree on that quote too, there are a few other quotes that are a bit risque (Anonymous #62 especially).

**Comment by donho** [comment]
> In the spirit of that other recent change, perhaps the quote about "necrophilia" should simply be deleted. If not, I'm sure future complaints will come.

It's different from the slogan of installer (which is not hidden).
Eastern egg is another situation - the same quotes of Linus is still in the Eastern eggs, and it won't be deleted. 
So no, "necrophilia" is a phenomenon which exists in our society, I don't see why we should avoid to talk about it.
Except regarding the racist/sexist/fascist content, all complains about eastern eggs will be rejected/ignored.
The unhappy users can always uninstall Notepad++ and [get refund](https://notepad-plus-plus.org/news/v843-unhappy-users-edition/).

**Comment by alankilborn** [comment]
Ha, okay, if just seemed like if a recent change of philosophy removed questionable quotes in one place, that it might be time for a complete purge.

**Comment by xomx** [comment]
> In the spirit of that other recent change, perhaps the quote about "necrophilia" should simply be deleted. If not, I'm sure future complaints will come.

@donho 
For a moment you hesitated and showed a weakness when you accepted that arguments of moralization about what is appropriate and what is not. Now you will pay for that :-)

Resistance is futile - your "naughty" character will be assimilated (by correctness) ;-)

**Comment by donho** [comment]
> For a moment you hesitated and showed a weakness when you accepted that arguments of moralization about what is appropriate and what is not. Now you will pay for that :-)
> 


LOL

But still, I feel that I have to explain the decision for issue  #14052. 
The old slogan has been asked by users over and over again, for the reason that these individuals are appalled - I personally don't care and am not embarrassing, hence the rejection of request with such argument.

However the issue #14052 has provided solid arguments (IMO) instead of "I'm appalled". It is like many feature requests, if the arguments are valid, it's hard to be rejected.

> Resistance is futile - your "naughty" character will be assimilated (by correctness) ;-)

"Only idiots refuse to change their minds."
:)

**Comment by xomx** [comment]
@donho 
I only meant my above sentences as a joke. But now my psychic debugging powers saw the length of your answer...

IMO - I think you did the right thing. Life is too short to bother with naggings like "Your installer triggered a PTSD!" or "A nurse could theoretically have a tantrum...!"

More to the point - I have already seen a valid [counter-argument](https://github.com/notepad-plus-plus/notepad-plus-plus/commit/00481aadd5563c3cf8ab27edfdbbd7ab596003e3#r125687484) for the new installer motto.

So here is my humble attempt how to fix that:
"Being free is the best thing in life and Notepad++ is."

It is then only up to the users whether they prefer to feel there the emphasis on "freedom" or on "to be the best" or both.

<tl;dr>
My POV on that Linus Torvald's quote is schizophrenic. I like the essence of that quote, but not its placement in the N++ installer. I even remember myself considering a similar take-down request a long time ago too! What saved me from that fateful shame was probably my love of freedom (of speech here) :-)
</tl;dr>

**Comment by donho** [comment]
@xomx 

The new slogan come from the famous quote: "The best things in life are free.", then I applied the same logic stupidly to make dumb quote for trolling (it was long time ago). I've never thought Notepad++ "the best" - there are so many code/text editors available, and Notepad++ is like every one of them, which has its advantage/inconvenience. 

You just reminded me that the irony/trolling/humor I tried to make could be taken seriously by people, just like the old slogan. I'll consider to change another one in which the meaning is less obscure.

"Being free is the best thing in life and Notepad++ is."

I like it. I may consider it if I cannot find another suitable one :)

**Comment by xomx** [comment]
@donho 

When trolling is behind it all only, I  would expect more from you than just the current slogan, e.g.:

"Sex is not like software where being free is not necessarily better but Notepad++ is."

This will left the moralists scratching their heads for a while ;-)

**Comment by Zichqec** [comment]
@donho how about "The best things in life are free, just like Notepad++"
It flows a little better imo, and it implies Notepad++ is the best without stating it outright
or something like "The best things in life are free, including software"
or even, "The best software in life is free"
The current one seems a bit clunky to me. My last two suggestions I think hold a little more true to the original sentiment (or at least how i interpreted it), not necessarily stating that Notepad++ is the best, but saying that software is better when it's free.
I think "The best software in life is free" has the nicest ring to it of these three

**Comment by BdR76** [comment]
@donho Might I suggest adding a quote [to the easter eggs](https://github.com/notepad-plus-plus/notepad-plus-plus/blob/e5ee4c3638a4b7d96504de6beba088016f1922f3/PowerEditor/src/Notepad_plus.cpp#L7578) from Zachary Polansky aka Jack Lance, a programmer and puzzle designer who died recently -> https://beautifulthorns.wixsite.com/puzzlesforprogress/post/the-puzzling-xlnc-of-jack-lance-1997-2023

He had a lot of brilliant linguistic quotes, or for example maybe his "Fibonacci rabbits" or 5 house puzzle.
