### ISSUE TITLE
Perl keywords need updating

### ISSUE THREAD

**Issue by pryrt** [notepad-plus-plus/notepad-plus-plus#14190]
### Description of the Issue

The last major update of Perl keywords (`autoCompletion\perl.xml` and `langs.model.xml` keyword list) was for Perl v5.30.
Perl is now at v5.38, and there are a number of new keywords (both built-in functions and pragmas) that need to be added.

Also, the default list of extensions should include `t`, as that is the Perl-standard naming convention for a Perl-unit-test file. (I confirmed that `langs.model.xml` doesn't have any other language whose extensions include `t`, so it won't conflict with anything.)

I will be submitting a PR momentarily to address this.

**Comment by donho** [comment]
https://github.com/notepad-plus-plus/notepad-plus-plus/commit/caf6303896cd01c813d3954b9d8c0a0bed622c8d
