### ISSUE TITLE
Right click and selecting "Edit with Notepad++" causes Explorer.exe to crash when using Windows 11 Safe Mode

### ISSUE THREAD

**Issue by mkupper** [notepad-plus-plus/notepad-plus-plus#14194]
### Description of the Issue
Please see [this Notepad++ forum thread](https://community.notepad-plus-plus.org/topic/24974/notepad-installation-and-explorer-exe-crash-only-in-safe-mode) for screen shots for how the issue was reported and reproduced. While the OP mentioned Notepad__ v8.5.7 it is not confirmed if this also happens with older versions of Notepad++.

### Steps to Reproduce the Issue

1.  Boot Windows 11 in Safe Mode
2. From Windows Explorer do right click and then "Edit with Notepad++" on a .txt file
3. Explorer will crash and restart.

### Expected Behavior
Open Notepad++ for the selected file.

### Debug Information
People reporting and reproducing the issue are shy and have not posted debug info other than "N++ v8.5.7 x64."

**Comment by xomx** [comment]
> People reporting and reproducing the issue are shy and have not posted debug info other than "N++ v8.5.7 x64."

I am definitely not "shy" :-)

But ok, more relevant details: NppShell.dll v1.2

And please close this issue and recreate where it really belongs:
https://github.com/notepad-plus-plus/nppShell/issues

**Comment by mkupper** [comment]
> > People reporting and reproducing the issue are shy and have not posted debug info other than "N++ v8.5.7 x64."
> 
> I am definitely not "shy" :-)
> 
> But ok, more relevant details: NppShell.dll v1.2
> 
> And please close this issue and recreate where it really belongs: https://github.com/notepad-plus-plus/nppShell/issues

Done and reposted to https://github.com/notepad-plus-plus/nppShell/issues/45

**Comment by mkupper** [comment]
Moving issue to https://github.com/notepad-plus-plus/nppShell/issues/45
