### ISSUE TITLE
Search Count inaccurate when a selection is active (and not counting in-selection)

### ISSUE THREAD

**Issue by alankilborn** [notepad-plus-plus/notepad-plus-plus#14200]
### Steps to Reproduce the Issue

Common setup; have only this text in a Notepad++ tab:

```
bbbbb bbbb bbbbbb
ccccc cccc cccccc
```

Steps To Reproduce (case 1):

* Put caret in the middle word (the one with 4 `b`)
* Ctrl+f to invoke _Find_; note `bbbb` gets put in the _Find what_ edit/combobox
* Type a single `b` so that it appears in _Find what_
* Uncheckmark all boxes in _Find_, select a _Search mode_ of _Normal_ (especially note that _In selection_ and _Wrap around_ are NOT to be checkmarked)
* Click on the N++ main window title bar (to activate the editor window so you can see the blinking caret); note that the caret is at the end of the second word
* Click on the _Count_ button in the _Find_ window and then observe the status bar of the _Find_ window
* **Expected**: `Count: 6 matches from caret to end-of-file`
* **Actual**: `Count: 10 matches from caret to end-of-file`

Steps To Reproduce (case 2):

* Select the middle word such that the blinking caret is before the first `b` in the word `bbbb`
* Ctrl+f to invoke _Find_; note `bbbb` gets put in the _Find what_ edit/combobox
* Type a single `b` so that it appears in _Find what_
* Uncheckmark all boxes in _Find_, select a _Search mode_ of _Normal_ (especially note that _In selection_ and _Wrap around_ are NOT to be checkmarked)
* Checkmark the _Backward direction_ checkbox
* Click on the N++ main window title bar (to activate the editor window so you can see the blinking caret); confirm that the caret is at the start of the second word
* Click on the _Count_ button in the _Find_ window and then observe the status bar of the _Find_ window
* **Expected**: `Count: 5 matches from start-of-file to caret`
* **Actual**: `Count: 9 matches from start-of-file to caret`

Steps To Reproduce (case 3):

* Make a column-block selection covering `bbbb` and `cccc` with the visible caret to the right/left of these words
* Try various counting operations of single `b` or single `c` characters in forward and/or backward directions
* Note various inaccurate counts...
* **Expected**: Accurate counts based off of the main-selection caret position
* **Actual**: Inaccurate counts

### Debug Information
Notepad++ v8.5.7   (64-bit)
Build time : Sep  6 2023 - 23:13:49
Path : C:\NotepadPlusPlus\Misc\_NoBackup\Releases\npp.8.5.7\virgin\notepad++.exe
Command Line : -multiInst
Admin mode : OFF
Local Conf mode : ON
Cloud Config : OFF
OS Name : Windows 11 Pro (64-bit)
OS Version : 22H2
OS Build : 22621.2283
Current ANSI codepage : 1252
Plugins : 
    mimeTools (2.9)
    NppConverter (4.5)
    NppExport (0.4)

**Comment by alankilborn** [comment]
With some further consideration, perhaps the behavior is "by design", but I was surprised by it as I was using the _Count_ feature on some real data.

**Comment by Yaron10** [comment]
@alankilborn,

👍 

I'm pretty sure the first two cases have been discussed before. I don't remember if it was with you or @sasumner. :)
The last case is an interesting and nice catch.

**Comment by alankilborn** [comment]
I don't remember specifically talking about _Count_, but what you are remembering is something I've forgotten or perhaps you indeed discussed with @sasumner or someone else.

**Comment by alankilborn** [comment]
If _Count_ is going to produce results in the form of "...to caret", then there is only one (main) caret at a single position, so the resulting count should be accurate in relation to that caret position, regardless of an active selection.

**Comment by Yaron10** [comment]
If I understand you correctly, you're re-validating the issue.

**Comment by Yaron10** [comment]
@alankilborn,

The following point might also be recycled. :)

One may argue and expect that "Find All in Current Document" and Count should display the same results.
But the first is not affected by the check-state of "Wrap around" whereas the latter IS.

I'm wondering if this is what you meant in
> If Count is going to produce results in the form of "...from caret"...

**Comment by alankilborn** [comment]
>I'm wondering if this is what you meant in
If Count is going to produce results in the form of "...from caret"...

A reluctant "yes" although I think bringing FACD into the discussion doesn't do anything for the clarity of the issue.
Isn't the issue clear enough with the STR?

**Comment by Yaron10** [comment]
@alankilborn,

Your wording in

> If Count is going to produce results in the form of "...from caret"

made me wonder if YOU were thinking it might be better not to count "from caret" but rather in entire-doc. :)
I suppose I was wrong.

"from caret" is obviously useful.
But if we agree that FACD & Count should display the same results (&& it's too complex to implement "from caret" in FACD),
we have another issue which requires some thinking.

**Comment by alankilborn** [comment]
@Yaron10 

I wasn't proposing changes in how counting is supposed to work.  Entire-doc counting is already possible, just checkmark _Wrap around_ (as you know, I'm sure).

I don't think FACD needs caret-based behavior -- here "all" means "all".  But if Don thinks it does...I wouldn't disagree and I might even work on it.  :-)

As a user, if I wanted to obtain _Search results_ from e.g. caret to end-of-file, I'd simply mentally note the line the caret is currently on, then run the FACD, then ignore result output from start-of-file to the mentally-noted caret line.

**Comment by Yaron10** [comment]
@alankilborn,

Thank you for the explanation.

But you agree that FACD & Count displaying different results can be considered weird/unexpected, don't you?
It should indeed be discussed in a separate thread.

> and I might even work on it. :-)

👍 :)!

**Comment by alankilborn** [comment]
>But you agree that FACD & Count displaying different results can be considered weird/unexpected, don't you?

Personally, I don't agree.  Thus, I'm not going to create a new issue/thread about it.

But if someone else were to create the issue, and Don wants it, I'd implement it.

**Comment by Yaron10** [comment]
I might create the issue when I have the time and mood to discuss it.

> But if someone else were to create the issue, and Don wants it, I'd implement it.

👍 
Thank you. I appreciate it.

**Comment by alankilborn** [comment]
For closure reason see closure comment in #14213

**Comment by alankilborn** [comment]
I created my own Counting implementation via script, which fixes the bugs I've noted here, and additionally provides even more capability that Notepad++'s native _Count_ feature, specifically multiple selection and column-block counting capability, and the ability to count _outside_ of selected text region(s).  This can be seen in its UI:

![image](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/77065706/15374033-fefa-4dcd-b319-a2142ae6e528)

For further detail, see https://community.notepad-plus-plus.org/topic/25022

**Comment by Yaron10** [comment]
@alankilborn,

Thank you for sharing.
Unfortunately I'm still using Python Script v2. The dialog is impressive. :)
