### ISSUE TITLE
"Clear read-only flag" right-mouse menu doesn't work

### ISSUE THREAD

**Issue by briancovingtonhsv** [notepad-plus-plus/notepad-plus-plus#14211]
### Description of the Issue
If you open a read-only file from disk, the Clear read-only flag does not make the file writeable unless you open a new tab or change to another already open tab.

### Steps to Reproduce the Issue
1.  Make a text file read-only on disk 
2.  Open that file (by itself or with others) in Notepad++ v8.5.7
3.  Right mouse on the read-only files' tab and select the Clear read-only flag menu item
4.  Notice the file is still read-only and not editable
5.  Open a new tab (or swap tabs to an already open tab) and come back to the original tab, now the file is editable
6. NOTE: Before switching tabs, you can note in Windows Explorer that the read-only attribute is gone from the file.

### Expected Behavior
File should be editable without tab switching to make it so.

### Actual Behavior
File is not editable until switching to another tab or opening a new one

### Debug Information
Notepad++ v8.5.7   (64-bit)
Build time : Sep  6 2023 - 23:13:49
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : "W:\S3DBuild\Builder\MapSpecial.ps1"
Admin mode : ON
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 10 Enterprise (64-bit)
OS Version : 21H2
OS Build : 19044.3448
Current ANSI codepage : 1252
Plugins : 
    mimeTools (2.9)
    NppConverter (4.5)
    NppExport (0.4)
    XMLTools (3.1.1.13)

This is a regression from v8.5.6, where this works properly.

**Comment by alankilborn** [comment]
Please search for existing issues before creating new ones.

**Comment by briancovingtonhsv** [comment]
I searched open issues for "Clear", "read-only", and "Clear read-only flag" and nothing in those returned results was this issue.  If this is a duplicate, I am sorry, but I feel I did my due diligence.

**Comment by alankilborn** [comment]
#14138 
#14165
