### ISSUE TITLE
Suggestion: Add document pinning

### ISSUE THREAD

**Issue by TsukiZero** [notepad-plus-plus/notepad-plus-plus#14216]
Just like how browser allows you to pin tabs, add "Pin Document" as a feature. Alongside that, I propose the following:
- Add an option to show the pinned document's name or not.
- Add a dedicated color or icon to the pinned document.
- Pinned documents always stays even if the original document source has been deleted or changed.
- If in Administrator Mode, pinned documents will be greyed out (disabled and unloaded), but can still be unpinned or closed. This is in case they are causing some problem and needs to be closed by other means.

Perhaps I should convey "why": there's a a couple of documents I want to always be there on Notepad++ when I open it, but to NOT keep any other open when I close Notepad++. While closing them individually while keeping the ones I want open, or having it not remember open documents are good ideas, they add extra steps to something that could be solved by other means.

**Comment by CennoxX** [comment]
A workaround for this would be to create a shortcut with the files you want to open every time.

**Comment by donho** [comment]
https://github.com/notepad-plus-plus/notepad-plus-plus/commit/ce58b424bdeec3616943f9ea8cd257f66700c3c0
