### ISSUE TITLE
Extra Underline When Pasting a URL between two ' characters

### ISSUE THREAD

**Issue by eschultz-csod** [notepad-plus-plus/notepad-plus-plus#14212]
### Description of the Issue
When you put a URL inside of two single quotes, the right most tickmark gets underlined which makes it appear as if its part of the URL. This behavior is different when you enclose a URL inside of two double quotes -- the right most double quote does not get underlined which seems normal to me.

### Steps to Reproduce the Issue

1.  Start with a signle quote '
2. Type the rest of the url, followed by a second single quote like this: 'http://example.com'
3. Auto formating takes over and underlines the url and the last single quote.

### Expected Behavior
I dont expect the last single quote to be underlined as its not part of the URL. When you enclose a URL in double quotes, the application behaves correctly and doesnt underline the double quote.

### Actual Behavior
The right most ' character gets underlined which is misleading. See the attached screenshot.

### Debug Information
Notepad++ v8.5.6   (64-bit)
Build time : Aug 15 2023 - 15:29:28
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : "C:\Users\MY_USER\MY_FOLDER\Desktop\scripts\MY_PROJECT\MY_FILEt.xt" 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 10 Enterprise (64-bit)
OS Version : 22H2
OS Build : 19045.3324
Current ANSI codepage : 1252
Plugins : 
    JsonTools (5.4)
    mimeTools (2.9)
    NppConverter (4.5)
    NppExport (0.4)
    XMLTools (3.1.1.13)

![image](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/146704606/7636e0d1-c7f7-4c2a-8305-4e47fc896d26)

**Comment by bcurran3** [comment]
Additionally, double clicking the URL will result in going to that URL with the addition of the single quote.

EXAMPLE:
Double clicking 'http://example.com' will open up http://example.com' instead of http://example.com.
