### ISSUE TITLE
Small graphical bug modified tab

### ISSUE THREAD

**Issue by HelloWorldFR** [notepad-plus-plus/notepad-plus-plus#14214]
Hello,

When we are modifying a new tab, the symbol "*" appear on the left side of the name.

![01.png](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/119363820/68aa1944-65bf-479e-93d6-52f7cf956bb2)

But when we move the tab, the symbol dont follow the tab.
![02.png](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/119363820/e03bf499-89e8-4d5e-a24d-9b0e086a1ecd)

Best regard

**Comment by alankilborn** [comment]
Your issue is not valid.
Please fill out the issue template, at the very least supply the _Debug Information_ part.

**Comment by HelloWorldFR** [comment]
They are not template on android app, but i will edit the 1st post.

**Comment by alankilborn** [comment]
>android app

There is no Notepad++ for android.  You're really in the wrong place.

**Comment by HelloWorldFR** [comment]
I mean i use github on android to post the message. github version for android have no template, only on computer version.

**Comment by alankilborn** [comment]
Ah, well, not sure why the template wouldn't exist for however one accesses github...

OK, well, somehow figure out how to get your debug information into your post.
