### ISSUE TITLE
Search History

### ISSUE THREAD

**Issue by mididoc** [notepad-plus-plus/notepad-plus-plus#14219]
Hello,
can someone please tell me where the settings for 'search history' can be done in Settings?

Thanks mike

**Comment by alankilborn** [comment]
@mididoc 

Questions about the software belong here:  https://community.notepad-plus-plus.org/
If you ask there, you'd better say a bit more (because I don't understand the question).

Please close this issue.

**Comment by mididoc** [comment]
Hi @alankilborn 
I ment where are these settings done in 'settings' dialog:

`<FindHistory nbMaxFindHistoryPath="0" **nbMaxFindHistoryFilter="0" nbMaxFindHistoryFind="0" nbMaxFindHistoryReplace="0"** matchWord="no" matchCase="no" wrap="yes" directionDown="yes" fifRecuisive="yes" fifInHiddenFolder="no" fifProjectPanel1="no" fifProjectPanel2="no" fifProjectPanel3="no" fifFilterFollowsDoc="no" fifFolderFollowsDoc="no" searchMode="0" transparencyMode="0" transparency="150" dotMatchesNewline="no" isSearch2ButtonsMode="no" regexBackward4PowerUser="no" bookmarkLine="no" purge="no" />
`
Thanks in advance.
Cheers mike
