### ISSUE TITLE
Suggestion: Window Groups

### ISSUE THREAD

**Issue by Warren52** [notepad-plus-plus/notepad-plus-plus#14227]
### Suggestion: Window Groups
Presently there is a **Window** entry in the Main Menu. It lists all the files NotePad++ presently has opened and makes it easy to find and jump to one (which I really like). Now I would like to propose an embellishment. 

With NotePad++ ver 8.5.7 on Windows 10, when you press the Window entry, a dialog box with two sub entries and a following listing of windows appears.  Now if a **Group** entry was added, it would open a second dialog box, like _Sort By_ presently does, allowing you to select _Group 1_ through _Group x_ (how many would be your call). Group 1 would always be the default while selecting another group would cause NotePad++ to close all the current windows and bring up a different set of windows. In code I would image this would be like having different lists of file name references with only one list being selected and active and showing its windows at a time. 

Then if we were also able to include a **NAME** with each group, I can bring up a _Python Project_ group, a _C++ Project_ group, a _rst doc_ group, or what ever group of windows that would be active for that name.  And if using a Name becomes too difficult, then being able to bring up Group 1, Group 2, Group 3, etc. would still be useful. 

Just a thought.

**Comment by alankilborn** [comment]
Sort of sounds like things Notepad++ already supports:  Sessions and/or projects.

**Comment by Warren52** [comment]
Well, thank you for informing me about sessions. That DOES seem to fit the bill. I suppose the only thing I would like to see for them is a Settings entry where a Default Sessions Directory could be set and used that is different from the Open / Save directory.

**Comment by alankilborn** [comment]
>Should all that be a different issue?

For best handling, yes, and TWO issues would be best, as you make two points.
