### ISSUE TITLE
"Session file is corrupted" message may not be displayed

### ISSUE THREAD

**Issue by Yaron10** [notepad-plus-plus/notepad-plus-plus#14228]
**STR:**
Manually save a session via _File -> Save Session_.
Open that session file in another editor and delete the first `<NotepadPlus>` line (-> file is corrupted).
_Preferences -> Multi-Instance_: select one of the non-default options.

![תמונה](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/10229320/717fa5e2-17f4-4007-911b-d371d1fc6795)

Restart NPP.
Open some file.
Open the corrupted session file.

**Result:**
The "Session file is corrupted" message is not displayed.

https://github.com/notepad-plus-plus/notepad-plus-plus/blob/64e95cc61c69eaceb889584ced414f88f19b25f7/PowerEditor/src/NppIO.cpp#L2478

***

Notepad++ v8.5.7.

**Comment by xomx** [comment]
@donho 
I have fixed this issue before starting to test your PR #14202, but now I see that you have assigned to this - should I continue to the PR or you will handle that?

**Comment by Yaron10** [comment]
@xomx & @donho,

Thank you for looking into it.

It's related to https://github.com/notepad-plus-plus/notepad-plus-plus/pull/14202.

The warnings for corrupted/missing files can be unified. Both in `Notepad_plus::fileLoadSession()` and `Notepad_plus::loadCommandlineParams()`.

```
if (!nppParams.loadSession(session2Load, sessionFileName.c_str()) || !loadSession(session2Load))
{
	_nativeLangSpeaker.messageBox("UserSessionFilesFailure",
		_pPublicInterface->getHSelf(),
		TEXT("Notepad++ can not open some file(s) included in the following Session file:\n\n\"$STR_REPLACE$\"."),
		TEXT("Open Files Failure"),
		MB_OK | MB_ICONWARNING,
		0,
		sessionFileName.c_str());
}
```

If you agree with the basic idea, the text itself should perhaps be changed to reflect "corrupted" more explicitly.

**Comment by xomx** [comment]
@Yaron10 

> If you agree with the basic idea

No.
I do not like to mix here a corrupted session-file (a xml parsing failure) issue and a possible missing file from a valid session xml-file.

My fix is simple - I moved [the error message](https://github.com/notepad-plus-plus/notepad-plus-plus/blob/85d5f972a8f4507f5e462541cd8b372f059b1fa7/PowerEditor/src/NppIO.cpp#L2476) to the `NppParameters::loadSession` [here](https://github.com/notepad-plus-plus/notepad-plus-plus/blob/85d5f972a8f4507f5e462541cd8b372f059b1fa7/PowerEditor/src/Parameters.cpp#L2273), where it works also for the 'Multi-Instance' N++ configs.

**Comment by Yaron10** [comment]
@xomx,

> My fix is simple - I moved...

👍

> I do not like to mix here a corrupted session-file (a xml parsing failure) issue and a possible missing file from a valid session xml-file.

If @donho decides to add a message for missing files, I don't understand why the two warnings can't be unified.
Why use two different `_nativeLangSpeaker.messageBox()`?

**Comment by donho** [comment]
> I have fixed this issue before starting to test your PR #14202, but now I see that you have assigned to this - should I continue to the PR or you will handle that?

@xomx Go ahead please. 
For me it's rather a message which belongs to XML loading than anywhere-else.

**Comment by Yaron10** [comment]
Another question:
Is it more important to check the validity of manually-created session files than that of session.xml?
Is the prompt more important?
And other XML files used by NPP?

**Comment by Yaron10** [comment]
@xomx,

https://github.com/notepad-plus-plus/notepad-plus-plus/blob/8b50f876c92c3a74c5f3bc059f7daa61d6d4b742/PowerEditor/src/NppBigSwitch.cpp#L1302
https://github.com/notepad-plus-plus/notepad-plus-plus/blob/8b50f876c92c3a74c5f3bc059f7daa61d6d4b742/PowerEditor/src/NppBigSwitch.cpp#L1316

Should the message be displayed there?

**Comment by xomx** [comment]
@Yaron10 
Good point.

1. `NPPM_GETNBSESSIONFILES` ... here I am for the error message because of returning zero only is not enough (as returning 0 here also means no session file at all in a valid session xml-file and we unfortunately have no other way to say "error" here)
2. `NPPM_GETSESSIONFILES` ... here the error message is not necessary because we can return `FALSE` as an error

But before any possible modification of this PR, I will wait for the Don's opinion.

**Comment by Yaron10** [comment]
@xomx,

> NPPM_GETNBSESSIONFILES ... here I am for the error message

When `NPPM_GETNBSESSIONFILES` is used in a plugin, the session is not loaded.
What's the point of prompting on getting the number of files?

**Comment by xomx** [comment]
https://npp-user-manual.org/docs/plugin-communication/#2037-nppm-getnbsessionfiles

- a plugin is just checking number of the session files in a saved session xml-file (by the help of N++ main app)
- such session xml-file can also have zero session file-items in it
- how else will the plugin distinguish a valid (but empty) session xml-file from an invalid one?

**Comment by Yaron10** [comment]
@xomx,

> how else will the plugin distinguish a valid (but empty) session xml-file from an invalid one?

I'm not sure I understand that.
1. The plugin can not distinguish between a valid (but empty) session xml-file and an invalid one (and I'm not sure that distinction is important).
2. How would the prompt solve that?
3. Would a plugin author want to prompt the user on merely getting the number of files?

**Comment by donho** [comment]
@Yaron10 
> Should the message be displayed there?

Good point. They shouldn't, and plugins should get a error return value.

@xomx 
> 1. `NPPM_GETNBSESSIONFILES` ... here I am for the error message because of returning zero only is not enough (as returning 0 here also means no session file at all in a valid session xml-file and we unfortunately have no other way to say "error" here)

In this case, -1 should be return when the loaded XML is invalid.

> https://npp-user-manual.org/docs/plugin-communication/#2037-nppm-getnbsessionfiles
>how else will the plugin distinguish a valid (but empty) session xml-file from an invalid one?

It's a bug in this API.
I would say the current implementation should do the following:

Return value:
    Returns -1 if sessionFileName is  an empty string/NULL, or XML session file is corrupted/invalid, else the number of files.
    
What do you guys think?

(FYI @pryrt)

**Comment by xomx** [comment]
@donho 

> > Should the message be displayed there?
> 
> Good point. They shouldn't, and plugins should get a error return value.

Agree.
I can modify my PR to not show that error-message in case of a plugin call.

> Return value:
> Returns -1 if sessionFileName is an empty string/NULL, or XML session file is corrupted/invalid, else the number of files.

I am for it.
Just a note - this will broke (again) the public API contract between the N++ and its plugins.
This is why I once wanted somewhere in the past versioning of the plugin's interface to be implemented.
With such a NPP_PLUGIN_INTERFACE_VERSION defined, N++ can solve any:
- binary API incompatibilities (gracefully prevents N++ crashing by refusing to load an older incompatible plugin + an info-msg for the user...)
- binary compatible changes in the already published API by accommodating the N++ code according to the plugin interface version reported

**Comment by Yaron10** [comment]
@donho,

> Returns -1

1. Is it important for plugins to distinguish between corrupted and valid-empty files? - In both cases the bottom line is "0 files".
2. As @xomx wrote: "this will broke (again) the public API contract between the N++ and its plugins".
Plugins which use `if (---NPPM_GETNBSESSIONFILES---)` (as opposed to if `(---NPPM_GETNBSESSIONFILES--- > 0)`), would get `true` on `-1`.

**Comment by donho** [comment]
> 2\. "this will broke (again) the public API contract between the N++ and its plugins".
>         Plugins which use `if (---NPPM_GETNBSESSIONFILES---)` (as opposed to `if (---NPPM_GETNBSESSIONFILES--- > 0)`), would get `true` on `-1`.

@xomx @Yaron10 

Or we can implement the specs as following description:

**NPPM_GETNBSESSIONFILES**

Retrieves the number of files to load in the session sessionFileName. sessionFileName should be a full path name of an xml file.

**Parameters:**

wParam [in]
    BOOL* isValidXML, if this value is null, then this parameter will be ignored. Otherwise TRUE or FALSE.

lParam [in]
    const TCHAR * sessionFileName

**Return value:**
Returns 0 if sessionFileName is an empty string/NULL, or XML session file is corrupted/invalid, else the number of files.

It makes sense  because when session file is corrupted/invalid, there'll be no session to be loaded so the number of files is zero.
For the old plugins there will be no impact but they can choose to be evolved.

What do you guys think?

**Comment by xomx** [comment]
Nice idea, this time I have no objections :-)

> wParam [in]

You mean wParam [`out`], is it?

**Comment by donho** [comment]
@xomx 
> You mean wParam [out], is it?

You're right. It's corrected.

**Comment by Yaron10** [comment]
@donho,

If you think it can be useful, it's a nice idea. 👍
