### ISSUE TITLE
Line Operations sometimes do nothing

### ISSUE THREAD

**Issue by endolith** [notepad-plus-plus/notepad-plus-plus#14220]
### Description of the Issue

Sometimes the Line Operations work, but other times they inexplicably don't.  I can't figure out what is different in each case.

### Steps to Reproduce the Issue

1. Select All
2. Edit -> Line Operations -> Sort Lines Lexigraphically Ascending

### Expected Behavior

Lines should be sorted

### Actual Behavior

Nothing

### Debug Information

Notepad++ v8.5.7   (32-bit)
Build time : Sep  6 2023 - 23:07:35
Path : C:\Program Files (x86)\Notepad++\notepad++.exe

Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 10 Enterprise (64-bit)
OS Version : 22H2
OS Build : 19045.3516
Current ANSI codepage : 1252
Plugins : 
    DSpellCheck (1.4.24)
    mimeTools (2.9)
    NppConverter (4.5)
    NppExport (0.4)
    NppTextFX (0.2.6)

**Comment by alankilborn** [comment]
You'd need to show some specific data where it isn't working.

**Comment by endolith** [comment]
```
.sync\ID
.sync\IgnoreList
C:\Users\endolith\Music\
C:\Users\endolith\Music\
C:\Users\endolith\Music\
C:\Users\endolith\Music\
.sync
C:\Users\endolith\Music\
```

gets "sorted" into 

```
.sync\ID
.sync\IgnoreList
C:\Users\endolith\Music\
C:\Users\endolith\Music\
C:\Users\endolith\Music\
C:\Users\endolith\Music\

C:\Users\endolith\Music\
.sync
```

for instance.

"remove duplicate lines" then converts it to 

```
.sync\ID
.sync\IgnoreList
C:\Users\endolith\Music\
C:\Users\endolith\Music\

C:\Users\endolith\Music\
.sync
```

if I then take 

```
.sync\ID
.sync\IgnoreList
C:\Users\endolith\Music\
C:\Users\endolith\Music\
C:\Users\endolith\Music\
.sync
```

and remove duplicate lines, it gets converted to

```
.sync\ID
.sync\IgnoreList
C:\Users\endolith\Music\
C:\Users\endolith\Music\
.sync
```

**Comment by alankilborn** [comment]
I can't even duplicate your first result (above `for instance` in your post).

Maybe you have mixed line endings before you sort?
Try _View_ > _Show Symbol_ > _Show End of Line_

Sorting only works when all line-endings are of the same type.

**Comment by endolith** [comment]
![image](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/58611/40a50b54-f9bf-456a-a822-12954b0f5be7)

Why wouldn't it work when line endings are different?

**Comment by alankilborn** [comment]
>Why wouldn't it work when line endings are different?

#7735

I think the unspoken judgement thus far is that if you have differing line-endings you have a corrupted input, so it doesn't matter if sort is correct.  That's just my guess, though, so don't hold Notepad++ developers to that opinion.

**Comment by endolith** [comment]
I can see it affecting duplicate line removal because they're arguably not duplicates in that case, but it still shouldn't affect sorting…

**Comment by alankilborn** [comment]
>but it still shouldn't affect sorting…

Hence, #7735
