### ISSUE TITLE
Replace All not working

### ISSUE THREAD

**Issue by arz1gwa** [notepad-plus-plus/notepad-plus-plus#14226]
### Description of the Issue

Replace All only updates the first occurrence and reports only one instance found.
Temp fix is to use Replace All in All Open Documents.

### Steps to Reproduce the Issue

1.  Select any text that occurs more than once
2.  CTRL + h
3.  Type new text
4.  Click on Replace All

### Expected Behavior

All instances of text to be replaced

### Actual Behavior

Only the first instance was replaced

### Debug Information

Notepad++ v8.5.7   (64-bit)
Build time : Sep  6 2023 - 23:13:49
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : "D:\Finance\blog\dynamic-drop-down-lists.html" 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : E:\articles
OS Name : Windows 10 Pro (64-bit)
OS Version : 22H2
OS Build : 19045.3516
Current ANSI codepage : 1252
Plugins : 
    mimeTools (2.9)
    NppConverter (4.5)
    NppExport (0.4)

**Comment by alankilborn** [comment]
Cannot replicate.

Provide some same text data that shows your problem and also a screenshot of the _Replace_ window just before you are going to press the _Replace All_ button.
