### ISSUE TITLE
Wrong "Error saving session XML file"

### ISSUE THREAD

**Issue by Yaron10** [notepad-plus-plus/notepad-plus-plus#14235]
**STR:**
File -> Save Session.
Click Cancel in the Save dialog.

**Result:**

![תמונה](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/10229320/8c7d110d-e2b4-4ef8-9dc7-a122fbe9710f)

https://github.com/notepad-plus-plus/notepad-plus-plus/blob/8b50f876c92c3a74c5f3bc059f7daa61d6d4b742/PowerEditor/src/Parameters.cpp#L3615
https://github.com/notepad-plus-plus/notepad-plus-plus/commit/7e353903b82a8035ead20759db8ec32a4ff88d94.

***

Notepad++ v8.5.7.

**Comment by P0rsche-911** [comment]
It shows that if there are unsaved files.
It would be better if it would warn you that you have to save all pending files before saving the session instead of displaying the error.

**Comment by Yaron10** [comment]
@P0rsche-911,

Could you please provide the steps to reproduce your issue?

**Comment by madzi-hove** [comment]
I am also receiving this error ever since upgrading to v8.5.7. I use an administrator account so it is strange to be denied access to this file.

**Comment by madzi-hove** [comment]
I am also getting this error since upgrading to v8.5.7

**Comment by P0rsche-911** [comment]
Sorry, I checked again and it shows the warning either with everything saved or if there is work to be saved.
It is possible that it was naming the session instead of cancelling.
