### ISSUE TITLE
Add Support for Ctrl+1/2/...9/0

### ISSUE THREAD

**Issue by mjmatthiesen** [notepad-plus-plus/notepad-plus-plus#14240]
### Description of the Issue
Very common keybaord shortcut in tabbed applications, e.g. vscode, firefox, etc, to quickly jump to first/second/last tab.
cltrl+1 -> first tab
ctrl+9 -> ninth tab
ctrl+0 -> last tab

Whether 0 or 9 should be jump to last seems to be debated, firefox uses 9, vscode uses 0.

### Steps to Reproduce the Issue

1. Open multiple documents
2. press ctrl+1 to go to first document
3. nothing happens

### Expected Behavior
Jump to first doc/tab.

### Actual Behavior
Nothing happens.

### Debug Information
Notepad++ v8.5.7   (64-bit)
Build time : Sep  6 2023 - 23:13:49
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : "C:\Users\mmatthiesen\Documents\AL Dev\DynamicShipDevCustomer\Coburn\Fix LP headers\app.json"
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 10 Enterprise (64-bit)
OS Version : 22H2
OS Build : 19045.3570
Current ANSI codepage : 1252
Plugins : 
    ComparePlugin (2.0.2)
    mimeTools (2.9)
    NppConverter (4.5)
    NppExport (0.4)
    NPPJSONViewer (1.40)
    XMLTools (3.1.1.12)

**Comment by alankilborn** [comment]
![image](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/77065706/fbec1566-f15c-4cbf-a00f-a98278010c53)

**Comment by mjmatthiesen** [comment]
Thanks! Cleared out the silly shortcuts and made them non-numpad.

**Comment by Yaron10** [comment]
@mjmatthiesen & @alankilborn,

> Would be nice if last tab was added, but there you go.

👍 
If there isn't an existing issue for that, could you please open one?
