### ISSUE TITLE
Allow For More Than Two Views In One Instance

### ISSUE THREAD

**Issue by SteveWonderbelt** [notepad-plus-plus/notepad-plus-plus#14242]
### Description of the Issue
Currently, a user can split the window view by right-clicking a tab and going to "Move Document". However, to open a third window, the user must start an entirely new instance and open the file there. I feel that it would be a significant QOL enhancement to allow users to split a file more than once without opening a new instance. 

### Steps to Reproduce the Issue
1. Open a file in Notepad++
2. Right-click the file's tab and go to "Move Document" 
3. Select "Move to Other View"
4. Right-click the new view's tab and repeat. 
5. The second view closes

### Expected Behavior
A third view opens. 

### Actual Behavior
The second view closes.

### Debug Information
Notepad++ v8.5.3   (64-bit)
Build time : May 15 2023 - 06:09:36
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : "C:\Users\stevenchilds\.ssh\id_rsa.pub"
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 11 Pro (64-bit)
OS Version : 22H2
OS Build : 22621.2283
Current ANSI codepage : 1252
Plugins : 
    CodeAlignmentNpp (14.1.107)
    Explorer (1.9.9)
    mimeTools (2.9)
    NppConverter (4.5)
    NppExport (0.4)

**Comment by sere3925sere** [comment]
I want this feature too, except I want it to work the visual studio way. In it, you can have tabs SomeDocument.txt:1 SomeDocument.txt:2 SomeDocument.txt:3 SomeDocument.txt:4, as many as you want.

**Comment by donho** [comment]
Unfortunately, this feature needs a lot of coding effort, so the implementation is unlikely to be done.
