### ISSUE TITLE
Error with the SQL syntax highlighting. 

### ISSUE THREAD

**Issue by hoylegj** [notepad-plus-plus/notepad-plus-plus#14241]
Error with the SQL syntax highlighting. 

If you you four single quotes in a row it causes the syntax highlighter to lose its colouring. Please see the screenshot as this shows it much better than I can explain. 

Many thanks Geoff. 
P.S. fabulas editor thanks very much

<img width="618" alt="sql_quoting_causing_syntax_colouring_issue" src="https://github.com/notepad-plus-plus/notepad-plus-plus/assets/24733177/0607ef38-0761-4200-81f8-fd03a13a4ebf">

Second similar issue.. this one is stranger though, it's just one quote 
![image](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/24733177/94c36045-9b17-4868-ac28-0e7025e16065)

**Comment by rdipardo** [comment]
1. Settings > Preferences > Language
2. _Clear_ the "Treat backslash as escape character for SQL" checkbox

![lexer sql escape backslash](https://user-images.githubusercontent.com/59004801/258336108-70213c3e-6bfb-4099-a33b-4140b403d9be.png)

**Comment by hoylegj** [comment]
Fabulas, that worked. 

Thanks very much, I've had that problem for years :-)  

Regards Geoff.

**Comment by hoylegj** [comment]
Closed 

Regards Geoff.
