### ISSUE TITLE
Customized toolbar only shows on main instance

### ISSUE THREAD

**Issue by FaceCrap** [notepad-plus-plus/notepad-plus-plus#14248]
### Description of the Issue

Any next instance of Notepad++ shows a completely different toolbar than the customized one I have on the main instance.
### Steps to Reproduce the Issue

1. Customize the toolbar of the first instance.
2. Open another instance
3. Observe a totally different toolbar

### Expected Behavior

That each next instance shows the toolbar in the way I customized it.
### Actual Behavior

I get a totally different toolbar that doesn't even look like the default one.
### Debug Information

Notepad++ v8.5.7   (64-bit)
Build time : Sep  6 2023 - 23:13:49
Path : E:\PortableApps\Notepad++Portable\App\Notepad++64\notepad++.exe
Admin mode : OFF
Local Conf mode : ON
Cloud Config : E:\PortableApps\Notepad++Portable\Data\Config
OS Name : Windows 10 Pro (64-bit)
OS Version : 22H2
OS Build : 19045.3570
Current ANSI codepage : 1252
Plugins : 
    AutoEolFormat (1.0.4)
    BracketsCheck (1.2.2)
    CodeAlignmentNpp (14.1.107)
    ColumnTools (1.4.5.1)
    ComparePlus (1.1)
    DSpellCheck (1.5)
    GotoLineCol (2.4.2)
    JSMinNPP (1.2307.1)
    mimeTools (2.9)
    nppAutoDetectIndent (2.3)
    NppConverter (4.5)
    NppExport (0.4)
    NPPJSONViewer (2.0.6)
    Python Indent (1.0.0.5)
    PythonScript (2)
    urlPlugin (1.2)
    _CustomizeToolbar (5.3)

Customized version
![image](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/95778718/23379cee-b613-44ae-8227-7e71fe60465b)

Version on other instances (which is always the same)
![image](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/95778718/a9c4601f-e8c1-4d09-b924-ce2cc21ea54f)

**Comment by alankilborn** [comment]
Seems like it would be reasonable to take this up on the support site for "_CustomizeToolbar".  Unless, that is, if you disable that plugin, and the standard Notepad++ toolbar appears different on multiple instances.

**Comment by FaceCrap** [comment]
> Seems like it would be reasonable to take this up on the support site for "_CustomizeToolbar". Unless, that is, if you disable that plugin, and the standard Notepad++ toolbar appears different on multiple instances.

You are right. I totally didn't think of that.
