### ISSUE TITLE
[minor] Incorrect new file numbering

### ISSUE THREAD

**Issue by arfmach** [notepad-plus-plus/notepad-plus-plus#1425]
When opening NP++ with an existing file, next new file created will be named “new 2” instead of “new 1”. When opening it without any file, first new file is correctly named “new 1”, but next is “new 3” instead of “new 2”.

**Comment by rushikesh90** [comment]
Hi,

I am getting the correct behavior when using notepad v6.0 for new file. 
![note](https://cloud.githubusercontent.com/assets/6714143/12871147/d645ecd4-cd90-11e5-952d-408720de66b7.png)

**Comment by vlakoff** [comment]
Can't reproduce either. Using Notepad++ 6.8.8.
