### ISSUE TITLE
syntax color bug

### ISSUE THREAD

**Issue by Neonberg** [notepad-plus-plus/notepad-plus-plus#14262]
### Description of the Issue
Syntax colors doesn't show on second open in .cs files

### Steps to Reproduce the Issue
1. Open any .cs file
2. Close notepad++ (dont close .cs tab)
3. Open .cs file again

### Expected Behavior
Always show syntax colors no matter how many times I open .cs files

### Actual Behavior
No syntax colors.
![image](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/116980697/bfaf6020-af67-4889-8dec-501714dfd5b5)

**Comment by alankilborn** [comment]
Not sure why you ignored the request for Debug Information in the issue template...

Anyway, when I attempt the STR in N++ 8.5.8, it works fine for me (syntax colors for .cs file are shown).

**Comment by xomx** [comment]
Cannot reproduce (v858 x64, I have many C# files open in N++, no problem when the N++ is restarted & the files are reopened as in STR).

**Comment by Neonberg** [comment]
Strangely I can't replicate bug while i saw it for a while. Theres probably other steps to replicate bug sorry. I'll try replicating (bug doesnt work after i updated notepad++)
