### ISSUE TITLE
[Feature Request] Hotkey for "Copy Selected Line(s)"

### ISSUE THREAD

**Issue by GOLEM777** [notepad-plus-plus/notepad-plus-plus#14269]
Add the ability to use a hotkey Ctrl+Shift+X  in find space.

for comand NPPM_INTERNAL_SCINTILLAFINDERCOPY

`generic_string copyLines = pNativeSpeaker->getLocalizedStrFromID("finder-copy", TEXT("Copy Selected Line(s)"));`

not VERBATIM.

```
		case NPPM_INTERNAL_SCINTILLAFINDERCOPY :
				{
					copy();
					return TRUE;
				}

```

**Comment by donho** [comment]
This feature has been done.

**Comment by alankilborn** [comment]
>This feature has been done.

No, it hasn't (there must have been some misunderstanding)

---

The suggestion is to add a keycombination here (in the green box):

![image](https://github.com/user-attachments/assets/12b1f07f-660e-4b22-921d-f91cf10b22bf)

---

>Add the ability to use a hotkey Ctrl+Shift+X

I would suggest Ctrl+Shift+c.
The use of `x` would imply a "cut" action, not a copy action.

Note that the _Search results_ window would need to have input focus for this proposed keycombo to work.

**Comment by GOLEM777** [comment]
Problem of implementation in a specific team.
Set of several commands FindReplaceDlg.cpp
` void Finder::copy()`
