### ISSUE TITLE
Automatic newline at the end of file

### ISSUE THREAD

**Issue by dogancelik** [notepad-plus-plus/notepad-plus-plus#1426]
I noticed that NPP doesn't have this feature for adding the final newline at the end of file.

> A text file, under unix, consists of a series of lines, each of which ends with a newline character (\n). A file that is not empty and does not end with a newline is therefore not a text file.

Final newline in files is important for Unix and Git. [ref](http://unix.stackexchange.com/a/18789)

Git diff warns you if you don't follow this rule.

Every text editor supports it (Emacs, Vim, Sublime Text, TextMate, Atom). [ref](https://robots.thoughtbot.com/no-newline-at-end-of-file)

> The C language standard says A source file that is not empty shall end in a new-line character, which shall not be immediately preceded by a backslash character.

GCC warns you if you don't follow this rule. [ref](http://stackoverflow.com/a/729725/2522142)

A checkbox under _Editing_ or _New Document_ is sufficient for this feature.

**Comment by vgturtle127** [comment]
@dogancelik @donho :+1:

**Comment by MetaChuh** [comment]
notepad++ has to be able to generate a file, without adding any appending characters automatically.
a switchable setting would only shift the user's focus from having to be aware of an eol before eof, to having to be aware which eol settings are currently active, to know if a eol will be added automatically, eventually adding a second lf by accident.

it is a user choice to manually add a (cr)lf to the last line or not, making it able to create a zero length files, like you would do with touch test.txt, or a single string text line without line breaks.
as you're also very aware of any missing noeol, you will spot it immediately at the last line number,
and most current linux releases should not have issues with noeol files, if you forget an lf.

i do however think that such function could be a nice, external plugin or script.
a possible idea for an NoEOLChecker plugin or script would be, to colour the eol mode Unix (LF) section at the status bar in red, as long as no eol is found at the last line, green if it is found, and no colour if this plugin or script is disabled for that file type.

many thanks and best regards

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
(no extra account is needed, just use your github account to sign in)
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)

**Comment by mohd-akram** [comment]
This can be achieved using the EditorConfig plugin. Create a `.editorconfig` file in your home directory or wherever is the root directory for your code with the following contents:

```ini
root = true

[*]
insert_final_newline = true
```

**Comment by still-dreaming-1** [comment]
> This can be achieved using the EditorConfig plugin. Create a `.editorconfig` file in your home directory or wherever is the root directory for your code with the following contents:
> 
> ```ini
> root = true
> 
> [*]
> insert_final_newline = true
> ```

Will it only insert the final newline if one does not already exist? What if there are multiple newlines at the end, will it remove the extra ones? If I install this plugin and start using it, will I have to redefine some of the same settings I already configured in Notepad++ just in case EditorConfig has conflicting defaults?

**Comment by alankilborn** [comment]
Will it only insert the final newline if one does not already exist? What if there are multiple newlines at the end, will it remove the extra ones? If I install this plugin and start using it, will I have to redefine some of the same settings I already configured in Notepad++ just in case EditorConfig has conflicting defaults?

Yes (that's the idea behind it), no, and no (editorconfig only uses what you tell it to).
