### ISSUE TITLE
tag quot VS apostrophe to cite "In Selection" (setting, Searching)

### ISSUE THREAD

**Issue by conky77** [notepad-plus-plus/notepad-plus-plus#14265]
### Description of the Issue

Setting, Searching "In Selection" is cited with an apostrophe in 2 points instead of using the tag `&quot;`

### Steps to Reproduce the Issue

1. open the window setting, section "Searching" 

### Expected Behavior
when there is a citation, the TAG `&quot;` should be used instead using the apostrophe symbol ( ' )

![immagine](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/59116246/29fb88e6-db1b-401a-8f1f-56b055123369)

### Actual Behavior
"In Selection" is cited with an apostrophe in 2 points (in the checkbox description and the explanation)

![immagine](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/59116246/9f1711df-65fc-466e-9786-60280b82dadc)

`&quot;` is used in many points:
![immagine](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/59116246/ebdca6b6-d817-490f-b85b-e808bb78dace)

### Debug Information
Notepad++ v8.5.8   (64-bit)
Build time : Oct 15 2023 - 21:43:56
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : -multiInst
Admin mode : ON
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 11 Home (64-bit)
OS Version : 22H2
OS Build : 22621.2428
Current ANSI codepage : 1252
Plugins : 
    ComparePlugin (2.0.2)
    CSVLint (0.4.6.5)
    DSpellCheck (1.5)
    JsonTools (5.6)
    mimeTools (2.9)
    NppConverter (4.5)
    NppExport (0.4)
    NPPJSONViewer (2.0.6)
    NppXmlTreeviewPlugin (2)
    XMLTools (3.1.1.13)

**Comment by alankilborn** [comment]
>when there is a citation, the TAG `&quot;` should be used instead using the apostrophe symbol ( ' )

Presume that you meant `&apos;` ?

**Comment by alankilborn** [comment]
There are many uses of `'` in english.xml currently, and zero uses of `&apos;`.  I suppose to be strictly correct `&apos;` should be used for all of them, but I can't see making such a change.

**Comment by conky77** [comment]
@alankilborn 
At the moment, in Notepad++ messages, when there is a citation, it is delimited by Quotation Marks ( `"` ) and not Apostrophe ( `'` ).
The only citations that uses Apostrophe ( `'` ) are
`Number of selected characters in edit zone to automatically check the 'In selection' checkbox when the Find dialog is activated.`

`Minimum Size for Auto-Checking 'In selection' The maximum value is 1024. Set the value to 0 to disable auto-checking.` 

examples of citations with  Quotation Mark ( `"` ) are many (with the word citation I mean when a command or a label is mentioned):
`Search Engine (for command "Search on Internet")` 
`Choose "Always yes" if you don't want to see this dialog again.`
etcetera

I would see, in Notepad,++ always the same style.

Technical speaking, if you want to represent the symbol Quotation Mark ( `"` ) in an XML file, it is mandatory to use `&quot;`

![immagine](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/59116246/4e961947-dd9f-4a9b-87d7-14756a169cf0)

**Comment by alankilborn** [comment]
I see what you mean, now.

`DoSaveAll` also uses `'`.

It is not a big deal to me, but I can change it to be consistent.

**Comment by conky77** [comment]
> `DoSaveAll` also uses `'`.
in `DoSaveAll` I found `'` only in the comments, but not in the text with function of citing a label
![immagine](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/59116246/2a76f594-3343-448e-b1fe-d061e20745f0)


> It is not a big deal to me, but I can change it to be consistent.
thanks
