### ISSUE TITLE
assignment missing

### ISSUE THREAD

**Issue by maddin200** [notepad-plus-plus/notepad-plus-plus#14276]
/scintilla/src/Document.cxx line 2203

Code:

} else {
	char bytes[UTF8MaxBytes]{ static_cast<char>(leadByte) }; // <-- no assignment ( = missing)

**Comment by alankilborn** [comment]
In some quick searching I couldn't find an authoritative example that was easy to understand (when passing along to someone else), but there's an example [HERE](https://www.informit.com/articles/article.aspx?p=1852519) in the `Introducing C++11 Brace-Initialization` section.

Bottom line: No missing `=` here.

**Comment by xomx** [comment]
If I am not mistaken that is the C++11 direct initialization.

And besides - since this is Scintilla code (and not a N++ one), it should not be reported here (if at all).

**Comment by xomx** [comment]
@alankilborn 
We posted both at the same time :-)

>  I couldn't find an authoritative example

https://en.cppreference.com/w/cpp/language/list_initialization

(And the subtlety of the initialization differences between C and C++ is my personal nightmare because I use both langs and often forget to flip the switch in my head...)

**Comment by maddin200** [comment]
ok - false positive

**Comment by alankilborn** [comment]
@xomx said:

https://en.cppreference.com/w/cpp/language/list_initialization

Right.  I tried there first.  And it certainly IS authoritative.
But it didn't contain a practical example of the type I thought the OP would see is like the opening comment of this issue.
