### ISSUE TITLE
Notepad++ Discord Server

### ISSUE THREAD

**Issue by feruenzerujkun** [notepad-plus-plus/notepad-plus-plus#14270]
Is there a Discord server dedicated to the Notepad++ application.
It tired searching it through reddit (https://www.reddit.com/r/notepadplusplus/), but suddenly there's no Discord server invite link to their own there.

Tried.
1. Reddit (like I said there)
2. Discord server = the Discovery function, e.g "Notepad or Notepad++" as that search.
3. Search Engines (first DuckDuckGo, now Google) = none.

+ Can you or anyone ask me where an official or unofficial Np++ Discord server (unless there is one there) online is so I can join via invite links there please? :-)

e.g link (leave most of it blank due to randomization-ness) :
https : // discord . gg / AnyKindOfLinkCodingForNpPlusPlusDiscordServer

**Comment by feruenzerujkun** [comment]
@donho 

![npPlusPlus_Discord](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/40934370/32a09ea3-5d00-4101-a60f-8cf0f08559b4)

**Comment by alankilborn** [comment]
IMO:
Discord = no need

**Comment by donho** [comment]
What is Discord?
:)

No, seriously. I have no life already.
With Discord, I will "have no life" * 2. 
Thank you for asking, but no.

**Comment by alankilborn** [comment]
Discord seems like something Notepad++ use to have ... if memory serves it was called the "gitter" (???) and there were some abuses with it (?) and @donho shut it down several years ago.

**Comment by feruenzerujkun** [comment]
> Discord seems like something Notepad++ use to have ... if memory serves it was called the "gitter" (???) and there were some abuses with it (?) and @donho shut it down several years ago.

Hmm... I see.
I noticed, I just don't wanna use Github for communication since I prefer Discord as my alternative to both that and reddit.
Plus I'm about to be (sadly) shutting down or abandon (abandon = same thing) [my account](https://www.reddit.com/user/feruenzerujkun/submitted/) on [reddit ](https://www.reddit.com/user/feruenzerujkun/comments/)created in [2018](https://www.reddit.com/user/feruenzerujkun/) (several years ago) due to desperation, disappointment and due to ([any of](https://www.reddit.com/r/notepadplusplus/comments/175v01d/joined_the_npp_subreddit_23_days_ago_because_im_a/) [my posts there having](https://www.reddit.com/r/qemu_kvm/comments/16si6r4/can_somebody_lend_me_or_anybody_who_played/)) lack of new messages and new comments to it/them there rather. ;-(

**Comment by feruenzerujkun** [comment]
> > Discord seems like something Notepad++ use to have ... if memory serves it was called the "gitter" (???) and there were some abuses with it (?) and @donho shut it down several years ago.
> 
> Hmm... I see. I noticed, I just don't wanna use Github for communication since I prefer [Discord](https://discord.com/login) as my alternative to both that and reddit. Plus I'm about to be (sadly) shutting down or abandon (abandon = same thing) [my account](https://www.reddit.com/user/feruenzerujkun/submitted/) on [reddit ](https://www.reddit.com/user/feruenzerujkun/comments/)created in [2018](https://www.reddit.com/user/feruenzerujkun/) (several years ago) due to desperation, disappointment and due to ([any of](https://www.reddit.com/r/notepadplusplus/comments/175v01d/joined_the_npp_subreddit_23_days_ago_because_im_a/) [my posts there having](https://www.reddit.com/r/qemu_kvm/comments/16si6r4/can_somebody_lend_me_or_anybody_who_played/)) lack of new messages and new comments to it/them there rather. ;-(

@donho @alankilborn 
sidenote:
Please note that I only the "confused" emoji instead of the thumb down emoji as the only use of sad-face to frown face emoji because there's no frown to sad face emoji for the reactions function available here on github sadly.
