### ISSUE TITLE
Placeholders are not marked as read-only if "Session Snapshot" is disabled 

### ISSUE THREAD

**Issue by Yaron10** [notepad-plus-plus/notepad-plus-plus#14271]
**STR:**
Use the binary from https://github.com/notepad-plus-plus/notepad-plus-plus/commit/e5ee4c3638a4b7d96504de6beba088016f1922f3.
Enable "Remember current session" & "Remember inaccessible files".
_Disable "Session Snapshot"._
Open file A.
Close NPP.
Delete file A.
Open NPP.
Choose "Yes" to create the placeholder.

**Result:**
File A is not marked as read-only.

NOTE: activating another program and returning to NPP - it IS marked as read-only.

**Comment by xomx** [comment]
Cannot reproduce, I have got the correct RO immediately.

> Enable "Remember current session" & "Remember inaccessible files".
> _Disable "Session Snapshot"._

I tried with this setting, right?

![npp_backup_setting_#14271](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/13075183/79ac16a0-b4fe-4ead-af3b-8b0a0844d6da)

**Comment by Yaron10** [comment]
@xomx,

Thank you for testing.

I should have added another step:

![תמונה](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/10229320/41e3e7f2-2898-4f7b-9d4d-f677418db576)
