### ISSUE TITLE
Feature Request: Using settings in config.xml in InstallationDirectory as default when creating user-specific config.xml

### ISSUE THREAD

**Issue by larskarag** [notepad-plus-plus/notepad-plus-plus#14277]
### Description of the Issue
Is it possible to use the settings from config.xml in the InstallationDirectory as default when creating the config.xml in %appdata%?

We are trying to disable auto-update - this is possible by setting the "noUpdate" value in config.xml for the user to "yes".
Problem is: We are installing Notepad++ when no userprofile exists, so we can not set the value in the user-specific config.xml in %appdata%.

It would be helpful if the user-specific config.xml would use the settings from the config.xml-file in the installation directory on initial creation.
As described here, it probably does, but not for every setting: https://npp-user-manual.org/docs/config-files/

### Steps to Reproduce the Issue
1. Install Notepad++
2. Set "noUpdate"-Value in "%InstallDir%\Notepad++\config.xml" to "yes"
3. Open Notepad++
4. Close Notepad++ -> "%appdata%\Notepad++\config.xml" is created

### Expected Behavior
 "noUpdate"-Value in "%appdata%\Notepad++\config.xml" is set to **"yes"**

### Actual Behavior
"noUpdate"-Value in "%appdata%\Notepad++\config.xml" is set to **"no"**

### Debug Information
Notepad++ v8.5.7   (64-bit)
Build time : Sep  6 2023 - 23:13:49
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 11 Enterprise (64-bit)
OS Version : 21H2
OS Build : 22000.2538
Current ANSI codepage : 1252
Plugins : 
    ComparePlugin (2.0.2)
    DSpellCheck (1.5)
    mimeTools (2.9)
    NppConverter (4.5)
    NppExport (0.4)
    NPPJSONViewer (2.0.6)
    XMLTools (3.1.1.13)

**Comment by xomx** [comment]
> We are trying to disable auto-update

For that you could use the Notepad++ installer [/noUpdater](https://npp-user-manual.org/docs/command-prompt/#installer-options) option (this possibility has been around for quite some time, but unfortunately it was only recently documented - https://github.com/notepad-plus-plus/notepad-plus-plus/issues/8514#issuecomment-1772921861), e.g. use at the installation time:

`npp.8.5.8.Installer.x64.exe /noUpdater /S /D=your-npp-install-path`

The above will silently install the N++ into "your-npp-install-path" dir but without the N++ updating components (GUP & PluginsAdmin). This then effectively disables/hides the N++ "Enable Notepad++ auto-updater" option for ANY USER later:

![npp_noGUP_noAutoUpdateCheckBox](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/13075183/7070151b-96ee-420f-ad5c-e418753404a2)
 
If you would like to try the above Preferences state, just close a running N++, rename your "...\\Notepad++\\updater\\" dir to "...\\Notepad++\\updater.bak\\" and restart N++.
