### ISSUE TITLE
Request Batch After Label style configuration

### ISSUE THREAD

**Issue by mpheath** [notepad-plus-plus/notepad-plus-plus#14283]
### Description of the Issue

Notepad++ v8.5.4 containing Lexilla v5.2.5 added a new style to the Batch lexer known as `AFTER LABEL`.
Notepad++ has no option to configure this new style as it has not been added to the theme xml files ( Ref: #14244 ).

Example syntax:

```bat
:label after_label
```

### Steps to Reproduce the Issue

1. Open `Settings -> Style Configurator`
2. Select `Batch` language.
3. `AFTER LABEL` style name is not listed.

### Expected Behavior

To be able to configure the style of `AFTER LABEL`.

### Actual Behavior

`AFTER LABEL` not available to configure the style.

### Debug Information

```
Notepad++ v8.5.8   (64-bit)
Build time : Oct 15 2023 - 21:43:56
```

### Suggestion

Base `AFTER LABEL` on `LABEL` bgColor and `COMMENT` fgColor styling.

<details>

<summary>Click to view image</summary>

In the order as listed in the `Style Configurator` combobox.

![npp_after_label2](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/58158242/6cd9dba2-3786-49d2-96ca-c1fb2f870f3a)

</details>

**Comment by donho** [comment]
@mpheath 
I'm not aware of the existence of "after label" in batch.
Could you provide me a link about "after label" feature in batch file?

**Comment by rdipardo** [comment]
@donho

> Could you provide me a link about "after label" feature in batch file?

ScintillaOrg/lexilla@bcfad41

It *début*ed in N++ 8.5.4, to the confusion of at least one user, who was accustomed to abusing multi-word labels as if they were comments: https://community.notepad-plus-plus.org/post/87322

**Comment by donho** [comment]
@rdipardo 
Thank you for the reference!
