### ISSUE TITLE
[Feature Request] Shortcut Key Enhancement

### ISSUE THREAD

**Issue by nrv-96** [notepad-plus-plus/notepad-plus-plus#14296]
### Description of the Feature

Please consider adding the following shortcut, as it would be more impactful and useful:

**Shift + Delete**:  without selected text, it will delete the whole line.
**Ctrl + C**:  without selected text, it will copy the whole line
**Ctrl + X**: without selected text, it will cut the whole line

p.s. : This shortcut works well in VSCode.

**Comment by alankilborn** [comment]
For <kbd>Shift</kbd>+<kbd>Delete</kbd>, just do some remapping in _Shortcut Mapper_ such that that keycombo is tied to the _SCI_LINEDELETE_ command.

For <kbd>Ctrl</kbd>+<kbd>c</kbd> and <kbd>Ctrl</kbd>+<kbd>x</kbd>, the _Visual Studio Line Copy_ plugin should work.

**Comment by nrv-96** [comment]
Thanks @alankilborn, It works. 

@donho Can we make the **Visual Studio Line Copy plugin** a core functionality? It will make a developer's life easier :)

**Comment by Yaron10** [comment]
@nrv-96,

You can remap in the Shortcut Mapper `SCI_LINECOPY` & `SCI_LINECUT` as well.

**Comment by alankilborn** [comment]
>You can remap in the Shortcut Mapper SCI_LINECOPY & SCI_LINECUT as well.

That's not (all that) useful.  User wants one keycombo to have dual functionality depending upon selected text or not.  Reading again, my advice about Shift+Delete violates that (so it is bad advice and should be ignored).

**Comment by donho** [comment]
> Shift + Delete: without selected text, it will delete the whole line.

@alankilborn @Yaron10 
Without selection, Shift-DEL, Ctrl-C and Ctrl-X do nothing currently in Notepad++.
If the following behaviours
```
Shift + Delete: without selected text, it will delete the whole line.
Ctrl + C: without selected text, it will copy the whole line
Ctrl + X: without selected text, it will cut the whole line
```
are in the most popular code/text editors, why does not Notepad++ align with?

**Comment by alankilborn** [comment]
I have no argument against Notepad++ aligning with the described behavior.

**Comment by Yaron10** [comment]
> ...are in the most popular code/text editors, why does not Notepad++ align with?

👍 
IMO _Copy/Delete/Cut Current Line_ should be also added to the menu.

**Comment by MAPJe71** [comment]
FYI: I'm currently using the LuaScript plugin with the following lines in the `startup.lua` to mimic the behavior:
```
-- Mimic Visual Studio's "Ctrl+C" that copies the entire line if nothing is selected
npp.AddShortcut("Copy Allow Line", "Ctrl+C", function()
    editor:CopyAllowLine()
end)

-- Mimic Visual Studio's "Ctrl+X" that cuts the line if nothing is selected
npp.AddShortcut("Cut Allow Line", "Ctrl+X", function()
    if editor.SelectionEmpty then
        editor:CopyAllowLine()
        editor:LineDelete()
    else
        editor:Cut()
    end
end)
```

**Comment by Yaron10** [comment]
```
Shift + Delete: without selected text, it will delete the whole line.
Ctrl + C: without selected text, it will copy the whole line
Ctrl + X: without selected text, it will cut the whole line
```

Thinking about it a bit more:
"Copy" & "Cut" would have to be always enabled. Personally I don't like it.

I'm currently using:

![תמונה](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/10229320/5b88531f-6adb-471c-a67c-4bc8b942a07a)

**Comment by donho** [comment]
Could you guys check #14298 please?
It's just an idea for the moment. 
An option "Visual Studio Line Shortcuts" will be added in preferences dialog afterward, if everyone think it's OK.

**Comment by alankilborn** [comment]
@Yaron10 said:

> Thinking about it a bit more:
> "Copy" & "Cut" would have to be always enabled. Personally I don't like it.

At least that would solve part of https://github.com/notepad-plus-plus/notepad-plus-plus/issues/11437 :-)

**Comment by alankilborn** [comment]
>It's just an idea for the moment.

Looking at the code, it seems a bit of a backdoor way to do it, hardcoding keycombos.

What if I want to take advantage of the behavior for Ctrl+c and Ctrl+x but NOT Shift+Delete?

It seems to me the better way to do it is three new commands that are individually shortcut-mappable.

>An option "Visual Studio Line Shortcuts" will be added in preferences dialog afterward

With the 3 new commands approach, no preference setting is needed.

**Comment by alankilborn** [comment]
>We have already SCI_LINECOPY, SCI_LINECUT & SCI_LINEDELETE to which we can remap the shorcuts, havn't we?

I'm not sure how mention of these is relevant.

---

>The goal is to reuse Ctrl-C, Ctrl-X and Shift-DEL, an option to enable or disable this feature

As you like.

---

I'd suggest considering a name change.  `Visual Studio Line Shortcuts` is not ideal IMO because it mentions "Visual Studio" and other editors support the actions, and overall the caption isn't very descriptive.  I know you'll ask for suggestions, so here's mine: "Line Copy/Cut/Delete when no text selected".

**Comment by alankilborn** [comment]
Question to others reading this thread:  Are there other users like me that remap Ctrl+c to something other than _Copy_ and use Ctrl+INS for copying?

**Comment by Yaron10** [comment]
@alankilborn,

> At least that would solve part of https://github.com/notepad-plus-plus/notepad-plus-plus/issues/11437 :-)

Do you have a chip installed somewhere? :)
The fix to that issue should be quite simple.

> Looking at the code, it seems a bit of a backdoor way to do it, hardcoding keycombos.
...
It seems to me the better way to do it is three new commands that are individually shortcut-mappable.

👍 

1. This would provide a way to execute those actions via the mouse as well.
IIRC, in Visual Studio "Copy" & "Cut" are indeed always enabled.
2. Those new commands would Copy, Delete & Cut the entire line even if it's partially selected.
3. In the following case
![תמונה](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/10229320/b2586fde-f14f-43a4-a67d-10741285d662)

\- `SCI_LINEDELETE` deletes the current line only. 
\- `SCI_LINECUT` cuts the three lines.

**Comment by Yaron10** [comment]
https://sourceforge.net/p/scintilla/bugs/2409/

**Comment by alankilborn** [comment]
@Yaron10 

Regarding scintilla...bugs...2409, also see:

* https://sourceforge.net/p/scintilla/feature-requests/1489/
* https://community.notepad-plus-plus.org/topic/23096/improve-sci_linedelete-shortcut
* https://github.com/notepad-plus-plus/notepad-plus-plus/issues/13921

**Comment by Yaron10** [comment]
@alankilborn,

Thank you.

**Comment by donho** [comment]
@alankilborn 


>>>It seems to me the better way to do it is three new commands that are individually shortcut-mappable.

>>We have already SCI_LINECOPY, SCI_LINECUT & SCI_LINEDELETE to which we can remap the shorcuts, havn't we?

> I'm not sure how mention of these is relevant.

I did understand that you prefer to add 3 new commands in the menu "Copy Line" "Cut Line" & "Delete Line". But I might mistake.

> I'd suggest considering a name change. Visual Studio Line Shortcuts is not ideal IMO because it mentions "Visual Studio" and other editors support the actions, and overall the caption isn't very descriptive.

No option finally. I hate to add options on options on options... and I don't see why an option is necessary here: it's rather a hidden feature here (it needs to be documented though). For people who are used to these shortcuts for single line, they can use  them directly; for people who are not, they ignore them.

I finally like these 3 shortcuts and I find no selection for doing single line operations makes sense.

> Thinking about it a bit more:
"Copy" & "Cut" would have to be always enabled. Personally I don't like it.

Furthermore, the implementation of PR #14298 won't impact "Copy" & "Cut".

**Comment by alankilborn** [comment]
@Yaron10, I don't understand it -- do you?

**Comment by Yaron10** [comment]
@alankilborn,

I don't understand why those functionalities should not be available in the menu.
Is "Duplicate Current Line" more important?

And also...

_With the default shortcuts:_
1. All of the new shortcuts appear in the menu. When there's no "real" selection, they are _disabled_.
I wouldn't expect disabled shortcuts to do anything. 
2. Shift+Delete is assigned to both Delete and Cut. This is weird IMO.

_Custom shortcuts:_
If the user has removed Ctrl+X from Cut and assigned it to Close, the new hard-coded Ctrl+X would still close the current tab. 
I've just realized that's what you meant in https://github.com/notepad-plus-plus/notepad-plus-plus/issues/14296#issuecomment-1788959210.

**Comment by alankilborn** [comment]
It's still definitely odd to me, but I suppose it isn't "fatal".
There's no way for me to put this "smart" copy on some other keycombo (e.g. Ctrl+Ins) if I want to.

But... I'll keep using my script anyway, which allows me full control to achieve what I want.
P.S. One thing my script does is quickly flash 3 times the selected text, so I know that the copy actually happened.  Sometimes it can seem like you hit a keycombo when you really slightly missed it.  With copy, there's no feedback that a copy actually happened -- I've created some.  With the script and nothing selected, it selects and flashes the entire line 3 times, thus not only do I know the copy happened, I'm reminded that what was copied was the entire line.

**Comment by CennoxX** [comment]
The way the v8.6 Release Candidate 2 of Notepad++ works when using ctrl+c without selection and then ctrl+v differs from Visual Studio Code. In VS Code the whole line will be added in the line above, in Notepad++ the line will be added on the cursor position. I'm probably biased because I've used VS Code's copy function before, but I think VS Code's behaviour is more useful.

**Comment by Coises** [comment]
@CennoxX:
> In VS Code the whole line will be added in the line above

Having Notepad++ paste differently if the clipboard content came from a copy without a selection vs a copy with a selection would create a hidden state. Granted, we already have one of those for when the copy is from a rectangular selection; I still wouldn’t relish another. Hidden states are confusing to both programmers and users.

**Comment by donho** [comment]
@CennoxX 
> The way the v8.6 Release Candidate 2 of Notepad++ works when using ctrl+c without selection and then ctrl+v differs from Visual Studio Code. In VS Code the whole line will be added in the line above, in Notepad++ the line will be added on the cursor position. I'm probably biased because I've used VS Code's copy function before, but I think VS Code's behaviour is more useful.

This behaviour worth to talk about.
Could you create an issue and PING me?

**Comment by circcc** [comment]
v8.6, 2 Problem

1.When text is not selected, the Cut/Copy menu and toolbar icons are disabled and cannot be used.
The Cut/Copy menu and toolbar icons should always be active.
Ultraedit 'Enable copy/cut of current line with no selection active' option work like this.

2.Shift + Delete: without selected text, it shoud 'Cut'(not 'Delete') the whole line. 
This is the standard and UltraEdit works like this too.

**Comment by progers-de** [comment]
Is there any way to turn off this new "copy line by default" feature?  (It's messing up some AutoHotkey shortcuts I've set up.)

**Comment by hujhax** [comment]
Is there any way to turn off this new "copy line by default" feature? (It's messing up some AutoHotkey shortcuts I've set up.)

**Comment by progers-de** [comment]
@donho Thanks! Is there documentation on how to pull/build a version of Notepad++ that includes this PR (on Windows)?

**Comment by nrv-96** [comment]
@progers-de you can find exe on the [PR](https://github.com/notepad-plus-plus/notepad-plus-plus/pull/14476/checks#:~:text=fb7c01e-,Artifacts,-10) Page.

**Comment by hujhax** [comment]
@donho AFAICT, that fix doesn't seem to address my request.  Here's what I tried:

1. I pulled "Notepad++.MSVC.x64.Release" and set up the "noColumnToMultiSelect.xml" file in "%APPDATA%\Notepad++
2. I ran notepad and created a test file with just the text "test"
3. I typed ctrl-C with no selection
4. I typed ctrl-V

I expected nothing to happen — i.e., that it would disable the "copy line if no selection" behavior.
Instead, Notepad++ pasted 'test' at the selection point.

**Comment by Coises** [comment]
Just a thought... 

Would it make sense to make it possible to assign more than one command to the same shortcut key _if_ one of the commands only works when there is a non-empty selection, and the other works when there is an empty selection? So, for example, if one assigned both “copy selection” and “copy line” to Ctrl+c, “copy selection” would be effective when there is a selection, and “copy line” would be effective when there isn’t. If you want nothing to happen when there is no selection, you don’t assign “copy line.” If you want them on two separate keys, you assign them to two separate keys (then “copy line” works whether there is a selection or not). If you want Shift+Delete to “cut selection” when there is a selection and “delete line” when there isn’t, you assign those two; if you want it to “cut selection” and “cut line,” you assign those; if you want it to do nothing when nothing is selected, you just assign “cut selection.”

The paste thing seems more complicated to me, but the same principle could apply: paste for a normal paste, and “paste as line above” such that if both are assigned to the same key, “paste as line above” takes effect only if the clipboard contains a full line cut or copy.

This doesn’t solve the menu problem, but is anyone really much concerned about how the menu options operate?

**Comment by alankilborn** [comment]
> Could you try PR #14476 please? Your issue should be fixed in this PR.

Maybe I'm confused, but I see no relation between this issue and PR 14476...

---

>but is anyone really much concerned about how the menu options operate?

I'd say the answer to this is a resounding yes.
Keycombos are supposed to do the exact thing that their menu items do.
(It's OK to have keycombos that do things that don't have menu items, but when they do...)

---

https://github.com/notepad-plus-plus/notepad-plus-plus/issues/14296#issuecomment-1788812490 ... no one listened.  :-(

**Comment by SN-CH** [comment]
@hujhax Did you manage to find the solution? If yes, I would very much appreciate, if you could share it. This change created problems for me for exactly the same reason it did for you.

@donho I believe this new feature to be quite useful for many people. Still there is a minority which prefers not to use it (these people are not necessarily retrogrades and not all users of your program are programmers). It would be great to have possibility to disable it (somewhere in config files, possibly, if it requires efforts to implement it in GUI). After all, it is MS way to enforce every new feature upon users (my colleagues and myself have no choice, but to use a lot of their software at work and that is why every one of us hates the word «update»).

**Comment by hujhax** [comment]
> @hujhax Did you manage to find the solution? If yes, I would very much appreciate, if you could share it. This change created problems for me for exactly the same reason it did for you.

@SN-CH Nope, no solution yet :(

**Comment by donho** [comment]
@hujhax
>> Is there any way to turn off this new "copy line if no selection" feature? (It's messing up some AutoHotkey shortcuts I've set up.) Alternately, is there an alternate "copy" key combination that won't activate the new feature?

> Could you try PR https://github.com/notepad-plus-plus/notepad-plus-plus/pull/14476 please? Your issue should be fixed in this PR.

Oups! Sorry for the wrong info. 

@hujhax @SN-CH 
Could you provide the scenario that the copying and cutting line (Ctrl-C & Ctrl-X, while there's no selection) is bothering or breaks your workflow?

**Comment by hujhax** [comment]
@donho 
> Could you provide the scenario that the copying and cutting line (Ctrl-C & Ctrl-X, while there's no selection) is bothering or breaks your workflow?

Sure thing!

I've got a set of AutoHotkey scripts for editing text that need to determine, for any windows application, whether there is a current text selection.  It does this by (1) emptying the clipboard, (2) sending a ctrl-C to the current app, and (3) determining if the clipboard is still empty.  Previously in Notepad++, and currently in every other app I use, if the clipboard is empty in step 3 I can conclude that the selection was empty.  But if ctrl-C selects the current line on no selection, I'm hosed.

(Specifically, I've got a bunch of tools that will either (1) put a set of tags around the selected text, or [if no selection] (2) will insert the tags at the selection point and leave the caret between the two.)

**Comment by Coises** [comment]
Keycombos are supposed to do the exact thing that their menu items do. (It's OK to have keycombos that do things that don't have menu items, but when they do...)
> 
> [#14296 (comment)](https://github.com/notepad-plus-plus/notepad-plus-plus/issues/14296#issuecomment-1788812490) ... no one listened. :-(

Then your suggestion in the referenced comment — create a unique command for each *reasonable* combination of actions — seems like the coherent solution. The problem I foresee with this is that there will be too many commands on the Edit menu and/or the commands on the menu won’t correspond to the commands the user actually uses. Would it make sense to show on the menu only the variant of a command which is assigned to a shortcut key (under the assumption that the ones the user uses are assigned), and if either multiple variants are assigned (like Ctrl+Insert to “copy selection” and Ctrl+C to “copy selection or line”) or none are assigned, the most flexible one (e.g., “copy selection or line”) is shown on the menu?

Perhaps the same concept of separate commands could apply to SCI_CHARRIGHT vs “Character right or convert rectangular selection to multiple selection” and similar actions, rather than the “empty file in a hidden directory” solution?

Though I have to say that while these solutions are flexible for advanced users, for *most* users simple check boxes to enable or disable “Cursor movement cancels rectangular selection,” “Cut/Copy whole lines when no selection” and (as a suboption only when “Cut/Copy whole lines when no selection” is enabled) “Paste whole line cut/copy above current line” would be more discoverable and easier to use.

**Comment by SN-CH** [comment]
@donho The use case of @hujhax is very similar to mine. I use the same logic described in his post implemented in AHK code for putting tags around the selected piece of text (or inserting pair of tags if there is no selection), but also for surrounding text/quick entering $$ (LaTeX), `` (markdown), quotes «» that are in wide use in my native language an so on.

**Comment by alankilborn** [comment]
>for most users simple check boxes to enable or disable...

I agree, but additional Preference settings have become unpopular.

**Comment by Coises** [comment]
> I've got a set of AutoHotkey scripts for editing text that need to determine, for any windows application, whether there is a current text selection. It does this by (1) emptying the clipboard, (2) sending a ctrl-C to the current app, and (3) determining if the clipboard is still empty. Previously in Notepad++, and currently in every other app I use, if the clipboard is empty in step 3 I can conclude that the selection was empty. But if ctrl-C selects the current line on no selection, I'm hosed.

Could your AutoHotkey script send [SCI_GETSELECTIONEMPTY ](https://www.scintilla.org/ScintillaDoc.html#SCI_GETSELECTIONEMPTY) directly to the Scintilla control (e.g., like [this post](https://www.autohotkey.com/board/topic/36100-scintilla-and-sendmessage/), but simpler, since you only need a simple numeric return value and don’t have to deal with a string buffer)?

**Comment by donho** [comment]
@hujhax @SN-CH 
Could you check the PR https://github.com/notepad-plus-plus/notepad-plus-plus/pull/14513, and tell me if it solves your issue?

**Comment by SN-CH** [comment]
@hujhax Do you mind sharing how you tested it? The description says disableLineCopyCutDelete.xml should be added to the Notepad++'s profile directory, but where exactly do I get this file? I checked the pull request page and found only zipped versions of Notepad++.exe.

**Comment by SN-CH** [comment]
@hujhax Okay, I got it. The file can be empty...

@donho It works for me as well. Thank you very much for your understanding.

**Comment by SN-CH** [comment]
@Coises Thank you for this idea. Finally, it seems to have been solved in more straightforward way, but it is good to know about this possibility of AHK calling the Scintilla control directly. One day that may come in handy.

**Comment by donho** [comment]
@hujhax @SN-CH 
Thank you for testing!

**Comment by vlakoff** [comment]
Note these standard keyboard shortcuts ([refs](https://askubuntu.com/questions/26655/how-do-you-know-when-to-use-shiftinsert-vs-ctrl-v-vs-right-click-paste-to-paste/356032#356032)) also exist:
* <kbd>Shift</kbd>+<kbd>Del</kbd>: Cut
* <kbd>Ctrl</kbd>+<kbd>Insert</kbd>: Copy
* <kbd>Shift</kbd>+<kbd>Insert:</kbd>: Paste

Generally in Windows applications, and in Notepad++ with text selection, these work.

In Notepad++ without text selection, I would suggest the following:
* Change <kbd>Shift</kbd>+<kbd>Del</kbd> action from "delete" to "cut" (the whole line).
* Implement <kbd>Ctrl</kbd>+<kbd>Insert</kbd> (which would copy the whole line).

As so, we would have the same, standard shortcuts with and without text selection.

**Comment by idkani** [comment]
> ### Description of the Feature
> Please consider adding the following shortcut, as it would be more impactful and useful:
> 
> **Shift + Delete**: without selected text, it will delete the whole line. **Ctrl + C**: without selected text, it will copy the whole line **Ctrl + X**: without selected text, it will cut the whole line
> 
> p.s. : This shortcut works well in VSCode.

Well, this is indeed **impactful**, but not useful for everybody. For me, this should be an option that you can enable if you want, but don't change the default behavior for this kind of "Feature" or use **new** shortcuts for **new** features.

There is already a shortcut `Ctrl`+`L` to cut the whole line, there is no need to change the functionality of `Ctrl`+`X`.

Today I had to update Notepad++ to version 8.6.1, usually this is not a problem. But then I noticed, that the "old" shortcuts for cut/copy/paste, i.e. `Shift`+`Delete`, `Ctrl`+`Insert`, `Shift`+`Insert ` are not working anymore, which is really bad for me. I then searched for a solution and found this forum discussion. I'm a left-hander and that means I hold the mouse with the left hand, for instance to select some text and with the right hand I can easily access these "old" shortcuts to cut, copy and paste. The shortcuts `Ctrl`+`X`, `Ctrl`+`C` and `Ctrl`+`V` are not easily accessible with the right hand and therefore I have always to change my left hand between the mouse and these shortcuts, which is really annoying.

Unfortunately I can't install the older version of Notepad++ to get it work again for me, it will be updated automatically by the corporate IT ASAP. :-(

I would really appreciate that this "Feature" is an option that can be enabled when desired, but left disabled as default. When updating Notepad++ it always shows the change log and there you could explain in a _What's new_ section the new options and how to enable them, that would be great :-)

**Comment by Coises** [comment]
@idkani

[The workaround for 8.6.1 is described here.](https://github.com/notepad-plus-plus/notepad-plus-plus/pull/14513)

[Current plans appear to be to revert these changes in the next release.](https://github.com/notepad-plus-plus/notepad-plus-plus/pull/14569)

**Comment by idkani** [comment]
@Coises
Thank you very much! 👍 
The workaround "_By adding disableLineCopyCutDelete.xml in "%APPDATA%\Notepad++" directory_" works perfectly for me. 

Sorry, I didn't see the link to the workaround before, it was already mentioned by https://github.com/notepad-plus-plus/notepad-plus-plus/issues/14296#issuecomment-1867177166 😳

**Comment by victorel-petrovich** [comment]
> **Shift + Delete**: without selected text, it will delete the whole line.

And with selection? 
Del already deletes the exact selection. 
What do you think of "shift + del" to delete all lines touched by that selection?
