### ISSUE TITLE
TinyXML2 upgrade (Uninitialized read in tinyxmlparser)

### ISSUE THREAD

**Issue by turbanoff** [notepad-plus-plus/notepad-plus-plus#143]
I found it with Dr.Memory

    Error #1: UNINITIALIZED READ: reading 0x00918040-0x00918044 4 byte(s)
    # 0 TiXmlParsingData::Stamp               [c:\projects\npp\powereditor\src\tinyxml\tinyxmlparser.cpp:75]
    # 1 TiXmlDeclaration::Parse               [c:\projects\npp\powereditor\src\tinyxml\tinyxmlparser.cpp:1088]
    # 2 TiXmlDocument::Parse                  [c:\projects\npp\powereditor\src\tinyxml\tinyxmlparser.cpp:464]
    # 3 TiXmlDocument::LoadFile               [c:\projects\npp\powereditor\src\tinyxml\tinyxml.cpp:743]
    # 4 TiXmlDocument::LoadFile               [c:\projects\npp\powereditor\src\tinyxml\tinyxml.cpp:678]
    # 5 NppParameters::load                   [c:\projects\npp\powereditor\src\parameters.cpp:1307]
    # 6 WinMain                               [c:\projects\npp\powereditor\src\winmain.cpp:295]
    Note: @0:00:07.679 in thread 5164
    Note: instruction: cmp    0x0c(%ecx) $0x00000001

**Comment by milipili** [comment]
Yes. Tinyxml needs to be upgraded.

**Comment by NN---** [comment]
[TinyXML2](https://github.com/leethomason/tinyxml2) should be considered then.

**Comment by NN---** [comment]
Just to notice there is a NuGet package for TinyXML2: https://www.nuget.org/packages/tinyxml2/

**Comment by milipili** [comment]
The upgrade of Tinyxml2 will be considered later
