### ISSUE TITLE
Style Configurator not saving between sessions

### ISSUE THREAD

**Issue by e4494s** [notepad-plus-plus/notepad-plus-plus#14303]
### Description of the Issue
The Style Configurator does not properly save changes that are made to it after Notepad++ is closed and reopened. Specifically, changed user-defined type words for various languages are not saved when the program is closed.

### Steps to Reproduce the Issue
1. Go to Style Configurator
2. Go to Java-->TYPE WORD
3. Edit the "User-defined keywords" section
4. Notice the changes in the text editor
5. Reload Notepad++ and the changes will be gone in Style Configurator

### Expected Behavior
I expected it to save after reloading the program, making it very difficult to change the style since I would have to change it every single time I open Notepad++.

### Actual Behavior
The "User-defined keywords" box reset to the last state before I changed it.

### Debug Information
Notepad++ v8.5.8   (64-bit)
Build time : Oct 15 2023 - 21:43:56
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 11 Home (64-bit)
OS Version : 22H2
OS Build : 22621.2428
Current ANSI codepage : 1252
Plugins : 
    mimeTools (2.9)
    NppConverter (4.5)
    NppExport (0.4)

**Comment by alankilborn** [comment]
Do you ever run multiple instances of Notepad++?
