### ISSUE TITLE
[Enhancement] Better distinction between main-selection and other-selections 

### ISSUE THREAD

**Issue by Yaron10** [notepad-plus-plus/notepad-plus-plus#14302]
**STR:**
Create multiple selections.

**Result:**
The distinction between the main-selection and the other-selections is not clear.

![תמונה](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/10229320/73d01370-54f5-4897-84d6-5ebc676f4d1f)

**Suggestion:**
1. Add a unique style for the other-selections caret color.
2. Add a unique style for the other-selections background color.

Personally I prefer the first option.

**Ref:**
https://github.com/notepad-plus-plus/notepad-plus-plus/pull/14295#issuecomment-1791745374.

***

Notepad++ v.8.5.8.

**Comment by alankilborn** [comment]
for `2. Add a unique style for the other-selections background color.` a simple PythonScript can demo it:

```
# -*- coding: utf-8 -*-
from Npp import *
red = 222; green = 222; blue = 222; alpha = 255
SC_ELEMENT_SELECTION_ADDITIONAL_BACK = 13
editor.setElementColour(SC_ELEMENT_SELECTION_ADDITIONAL_BACK, (red, green, blue, alpha))
```

This sets additional sections to a lighter grey than the main selection, to yield:

![image](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/77065706/2ee28b8d-2290-45fc-979d-41a1b59d4a60)

This effect is maybe more striking for a column block selection, with current line background color set to white, making it really clear that line 13 holds the main selection and the lines above are the other-selections:

![image](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/77065706/c04b7900-b590-4c1b-9f5e-1a57f2e08115)

**Comment by Yaron10** [comment]
@alankilborn,

That's very nice!
I can't test `SC_ELEMENT_SELECTION_ADDITIONAL_BACK` with PythonScript v2.

`SELECTION_ADDITIONAL_BACK` inactive?

**Comment by alankilborn** [comment]
>I can't test SC_ELEMENT_SELECTION_ADDITIONAL_BACK with PythonScript v2.

I think for PS2 you'd use `editor.setSelectionAdditionalBack()`?  I'm not 100% sure but I think Scintilla has deprecated [SCI_SETADDITIONALSELBACK](https://scintilla.org/ScintillaDoc.html#SCI_SETADDITIONALSELBACK) and other similar -- because I see a strikethrough font on it in current Scintilla docs.  The newer way to set element colors is via the [SCI_SETELEMENTCOLOUR](https://scintilla.org/ScintillaDoc.html#SCI_SETELEMENTCOLOUR) api, where _what_ you want to set is passed as the first argument (instead of having a bunch of separate functions, one for each possible thing you could set the color on.

Perhaps PS3 has adopted the element-colour api but this hasn't been backported into PS2.  I'm not delving too hard into PS2 any longer (I've "moved on").

**Comment by alankilborn** [comment]
>SELECTION_ADDITIONAL_BACK inactive?

SC_ELEMENT_SELECTION_INACTIVE_BACK (note the "inactive") is for when you have multiple selections active and the Notepad++ editing window loses input focus.

**Comment by Yaron10** [comment]
> For me, I'd just like to have my blue colors remain as is when the editing window loses focus, but this doesn't appear possible. All selections turn the same background color when focus is lost.

https://github.com/notepad-plus-plus/notepad-plus-plus/blob/69998ab7dec86c2fcf4f8381ce10f5a7d09574de/PowerEditor/src/ScintillaComponent/ScintillaEditView.cpp#L2838

That line overrides your style.
That's what I meant in `SELECTION_ADDITIONAL_BACK` inactive.

**Comment by alankilborn** [comment]
>That line overrides your style.

Not exactly overrides...but if I don't set that attribute, I will get what that line says.
My PS setting of the colors takes place _after_ that line executes on startup.
(Of course, if I go into _Style Configurator_ and make a change to anything, that line _will_ execute, making my PS settings go away (until next N++ restart); it's OK, I typically don't change any styles now that I'm set in my ways).

**Comment by Yaron10** [comment]
If `SC_ELEMENT_SELECTION_ADDITIONAL_BACK` is implemented in NPP itself, we'd still need `SC_ELEMENT_SELECTION_ADDITIONAL_INACTIVE_BACK` for a full control.

Unfortunately I can't find it.
A FR on Scintilla? :)

**Comment by alankilborn** [comment]
Scintilla doesn't currently seem to give that level of control.
I'd think N++ could live without it?

---

> A FR on Scintilla?

If you'd like to...go for it.  :-)

**Comment by Yaron10** [comment]
> If you'd like to...go for it.

Perhaps I'll do that.

Thank you for testing and sharing. 👍

**Comment by alankilborn** [comment]
Regarding:

> 1 Add a unique style for the other-selections caret color.

When I tried this:

```
# -*- coding: utf-8 -*-
from Npp import *
red = 0; green = 255; blue = 0; alpha = 255
SC_ELEMENT_CARET_ADDITIONAL = 41
editor.setElementColour(SC_ELEMENT_SELECTION_ADDITIONAL_BACK, (red, green, blue, alpha))
```

What I got was no change in the additional carets coloring.  :-(
Instead of going green they remained some shade of grey.

**Comment by Yaron10** [comment]
You're using `setElementColour(SC_ELEMENT_SELECTION_ADDITIONAL_BACK`. :)

**Comment by alankilborn** [comment]
Doh!

**Comment by donho** [comment]
@Yaron10 
> Suggestion:

 >  1. Add a unique style for the other-selections caret color.
 >  2. Add a unique style for the other-selections background color.

>Personally I prefer the first option.

Just check v8.5.8 official release, the feature is already there:

![image](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/90293/1d32acc5-b4d6-4c56-a5cd-904751955aa9)

Or am I missing somethings?

**Comment by donho** [comment]
@Yaron10 
> Or am I missing somethings?

NM, it's a FR for OTHER selectionS.
However, we can distinguish if we set Caret colour....
I'll see what can I do about it.

**Comment by eldepor** [comment]
where is `multi-select background & caret colours customizable`? I cant find that option

**Comment by alankilborn** [comment]
@eldepor 

Maybe see [HERE](https://community.notepad-plus-plus.org/post/91094).

**Comment by eldepor** [comment]
> @eldepor
> 
> Maybe see [HERE](https://community.notepad-plus-plus.org/post/91094).

Ok thanks now I can see it, but only in dark mode style
