### ISSUE TITLE
Search in Note++ not working

### ISSUE THREAD

**Issue by jr7138** [notepad-plus-plus/notepad-plus-plus#14304]
The search feature is not working, please see the attached screenshot.

My steps:
1. control f
2. enter the search string
3. returns no hits

It should find 'org'

![search2](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/51214020/20bd3c03-684c-4656-9132-48b700ecabc6)

Notepad++ v8.5.8   (64-bit)
Build time : Oct 15 2023 - 21:43:56
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : "C:\Program Files\Notepad++\change.log" 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 10 Enterprise (64-bit)
OS Version : 22H2
OS Build : 19045.3570
Current ANSI codepage : 1252
Plugins : 
    JSMinNPP (1.2205)
    mimeTools (2.9)
    NppConverter (4.5)
    NppExport (0.4)
    XMLTools (3.1.1.13)

**Comment by alankilborn** [comment]
Provide the source file as an attachment here.

**Comment by Yaron10** [comment]
@jr7138,

Please check "Wrap around".

***

So many similar issues & confusions.

> If the search is executed in selection, we get "in 1 selection" in the Search Results window.
How about always adding the range & conditions to the Search Results?
>
> For example:
"in selection; Case: ON; Whole word: OFF".
"from caret/selection down; Case: OFF; Whole word: ON".

https://github.com/notepad-plus-plus/notepad-plus-plus/pull/14213#issuecomment-1752036434

Implementing that in the Find dialog status bar should solve that confusion.

**Comment by alankilborn** [comment]
>wrap around

Doh! Didn't consider that one.  Thought about whole-word, backward-regex...

---

>How about always adding the range & conditions to the ... Find dialog status bar should solve that confusion

Make me an issue, I will code it if we can get it approved.

**Comment by Yaron10** [comment]
@alankilborn,

https://github.com/notepad-plus-plus/notepad-plus-plus/issues/14305.

> I will code it if we can get it approved.

👍 
Great! Thank you.
