### ISSUE TITLE
Right-click local menu of tab header is shown in English in Hungarian users' interface

### ISSUE THREAD

**Issue by DadManBlues** [notepad-plus-plus/notepad-plus-plus#14319]
### Description of the Issue

The language of np++ is set to Hungarian but when I click on any tab, the local menu appears in English. Pls. take a look at the screenshot attached.

![npp-hiba](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/148427828/282b5eed-322e-4b23-b9d5-cecebb95378f)

### Steps to Reproduce the Issue

Set np++ to (probably, not checked) any other language than English, then right-click on any tab header (the 'ear' where the filename is shown).

### Expected Behavior

The language in all menus should match the one the user had previously selected.

### Actual Behavior

The language of the tab header local menu is English. The language of the local menu of the edit area matches the selected (in my case Hungarian).

### Debug Information

Notepad++ v8.5.8   (64-bit)
Build time : Oct 15 2023 - 21:43:56
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : "C:\Program Files\Notepad++\change.log" 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 11 Pro N for Workstations (64-bit)
OS Version : 22H2
OS Build : 22621.2506
Current ANSI codepage : 1250
Plugins : 
    JsonTools (4.0.0.1)
    mimeTools (2.9)
    NppConverter (4.5)
    NppExport (0.4)
    NppFTP (0.29.12)
    NPPJSONViewer (2.0.3)

**Comment by alankilborn** [comment]
It's because there has been no translator supplying Hungarian translations for a period of time.  As new features are added to Notepad++, they are added in English, and translators see the new features and supply translations.

This one might not be so difficult to get the translations done because all/most of it was items that were just shifted from another place.

**Comment by DadManBlues** [comment]
Thanks, I saw that there are so many duplicate elements in the menus so I thought it was an error. I'll check where can I translate those strings.
