### ISSUE TITLE
I can't drag-and-drop using Notepad++ v6.8.8

### ISSUE THREAD

**Issue by marceloluzsantos** [notepad-plus-plus/notepad-plus-plus#1431]
Hi!

Seens that I can’t drad-and-drop anymore using Notepad++ v6.8.8.

The drop was made on the right side of the last open tab. I tried a file from a simple path (C:\HaxLogs.txt) and other from a more complex one. None opened the file.

Here goes the debug info:

Notepad++ v6.8.8
Build time : Dec 10 2015 - 01:11:37
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : ON
Local Conf mode : OFF
OS : Windows 10
Plugins : mimeTools.dll NppConverter.dll NppExport.dll NppFTP.dll PluginManager.dll 

Thank you,

Marcelo.

**Comment by ClaudiaFrank** [comment]
@devs
Assumtion is that npp and and explorers aren't on same elevation level.
Answer has been given in npp forum.

**Comment by marceloluzsantos** [comment]
After reading some topics on [Forum](http://sourceforge.net/p/notepad-plus/discussion/331753/thread/28aefaa4/?page=1), I've set the compatibility mode of notepad++.exe to **Windows 7** and the drag-and-drop feature started to work again. Thanks!
