### ISSUE TITLE
AppVeyor XML checks hang indefinitely since 02e4202

### ISSUE THREAD

**Issue by rdipardo** [notepad-plus-plus/notepad-plus-plus#14315]
### Description of the Issue

02e4202 removed *all* build configurations but x64-Release, which applies a `skip_commits` filter for commits that only touch XML. AppVeyor puts them in queue for building, then does nothing. The amber "pending" icon will be displayed indefinitely until someone manually cancels the build.

### Steps to Reproduce the Issue
1. Browse the [currently open translation updates](https://github.com/notepad-plus-plus/notepad-plus-plus/pulls?q=is%3Apr+is%3Aopen+sort%3Aupdated-desc+xml+in%3Atitle).
2. See the amber circle beside the most recent ones, e.g.,
   - #14275
   - #14260
   - #14290
3. Click any of the amber circles and see the AppVeyor job is still "pending"

### Expected Behavior
CI builds triggered by translation updates run to completion.

### Actual Behavior
AppVeyor hangs indefinitely on translation updates.

### Debug Information
*n/a*

**Comment by donho** [comment]
notepad-plus-plus project is removed from appveyor - the same issue will be solved in the future builds, but unfortunately not for the past ones.
