### ISSUE TITLE
Run menu | Send via Outlook - replace by Send via Email

### ISSUE THREAD

**Issue by DavidHaslam** [notepad-plus-plus/notepad-plus-plus#1432]
Please update this menu option.

Rather than being tied only to the Outlook engine, this option should use the default Email client on the user's PC.

**Send via Email**

It might be useful also to add a further option.
**Compress and Send via Email**,

with **User Preferences** for choosing the default compression utility and method

**Comment by DavidHaslam** [comment]
I'm not a user of Outlook.  My email client is Mozilla Thunderbird.

**Comment by vgturtle127** [comment]
@donho @DavidHaslam I think this is a beneficial change. I am also a user of Mozilla Thunderbird.

:+1:

**Comment by sanastasiou** [comment]
Agree - could even use a standard compression library as default.

**Comment by MetaChuh** [comment]
`Send via Outlook` has been removed from the run menu, in current versions of notepad++, for security reasons.
renaming of `Send via Outlook`, or adding the mailing run menu entry, from older versions of notepad++, is possible, by editing `shortcuts.xml`.

please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins.
if your issue still persists, and it is still of relevance to you, please feel free to file a new issue as detailed and reproducible as possible.

thank you for your help and best regards.

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
(no extra account is needed, just use your github account to sign in)
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)
