### ISSUE TITLE
"In selection" resets each time you make a new selection

### ISSUE THREAD

**Issue by marcohennig** [notepad-plus-plus/notepad-plus-plus#14325]
### Description of the Issue

"In selection" resets each time you make a new selection.

### Steps to Reproduce the Issue

1. open a document 
2. select some text
3. open replace dialog
4. enable "In selection"
5. go back to to the document
6. select some other text
7. go back to the replace dialog

### Expected Behavior
"In selection" still enabeld

### Actual Behavior
"In selection" not enabeld anymore

### Debug Information
Notepad++ v8.5.8   (32-bit)
Build time : Oct 15 2023 - 21:12:23
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Command Line : "D:\xplm\GIT\Extern\extern.Revit2024\project.nuspec" 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 10 Enterprise (64-bit)
OS Version : 22H2
OS Build : 19045.3448
Current ANSI codepage : 1252
Plugins : 
    ComparePlugin (2)
    mimeTools (2.9)
    NppConverter (4.5)
    NppExport (0.4)
    NppTextFX (0.2.6)
    XMLTools (2.4.11)
    _CustomizeToolbar (5.3)

**Comment by alankilborn** [comment]
Proper terminology:
"enable" -> "checkmark"
"enabled" -> "checkmarked"

---

@donho I will look into this.

**Comment by Yaron10** [comment]
@marcohennig,

![תמונה](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/10229320/31cea75f-64ae-44bd-b819-81fd79d8fb46)

Set the value to `0`.

***

@alankilborn,

Should there be a difference between this case and https://github.com/notepad-plus-plus/notepad-plus-plus/pull/14175#issuecomment-1735278341?
