### ISSUE TITLE
Feature request - Will NotepadPP work natively on Debian through Wine? I used notepadqq but it hasnt been updated in years.

### ISSUE THREAD

**Issue by natewrench** [notepad-plus-plus/notepad-plus-plus#14326]
### Debug Information
Notepad++ v8.5.8   (64-bit)
Build time : Oct 15 2023 - 21:43:56
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 11 Home (64-bit)
OS Version : 22H2
OS Build : 22621.2506
Current ANSI codepage : 1252
Plugins : 
    mimeTools (2.9)
    NppConverter (4.5)
    NppExport (0.4)

https://notepadqq.com/s/ for reference

if notepadpp can work through wine or if there is an updated fork for debian.

Love notepadpp because of its option to reopen file as admin feature! and autosaves documents if i forget to save them.. keeps them open

**Comment by xomx** [comment]
https://github.com/notepad-plus-plus/notepad-plus-plus/wiki/FAQ#support-for-systems-other-than-the-ms-windows-family

I recommend closing of this issue.

Related: #5162

For fun - one of the notepadqq users apparently asks for the exact opposite (he wants a Windows version of that notepadqq ...}:
https://notepadqq.com/wp/download/#comment-47738
