### ISSUE TITLE
Full screen view not working properly

### ISSUE THREAD

**Issue by jani8787** [notepad-plus-plus/notepad-plus-plus#14337]
I attached a video. Notepad ++ in a full-screen view, but on the top of its view I can control other programs I can close other programs, and it is very annoying.

https://drive.google.com/file/d/1aLgJE4hy6a3jbNQfWALWHyOJt5UXaEqU/view?usp=sharing

**Comment by CennoxX** [comment]
1) Please add your Debug Information as stated in the issue template.
2) Whats that pin symbol at the top?

**Comment by alankilborn** [comment]
@jani8787 Can you just attach the video directly here?

**Comment by jani8787** [comment]
Hi,

The pin is display fusion program, but I try to exit from that and the same
result.
I can not attach the video here, because no option for video, only pics.
But you can see everything on the video from my GDrive. Additional info
that I have an extra monitor with HDMI and on the main screen it is good,
the mentioned problem exist only on the extended monitor. Please check it.


Üdvözlettel,
Csizmadia János


alankilborn ***@***.***> ezt írta (időpont: 2023. nov. 9.,
Cs, 15:48):

**Comment by alankilborn** [comment]
>I can not attach the video here, because no option for video, only pics

The upload link here says "Paste, drop, or click to add files".  All types of files can be added, nothing specific here about pictures or videos.

>But you can see everything on the video from my GDrive

Well, I for one don't click links that I don't know, and don't use GDrive at all, so...
Maybe others don't mind clicking on your link.
Good luck with your problem.

**Comment by jani8787** [comment]
Uploading 2023-11-08 14-14-44 bug shared.mp4…

**Comment by jani8787** [comment]
https://github.com/notepad-plus-plus/notepad-plus-plus/assets/48155682/7663d196-29c9-4a3f-b494-20f5e5eaf5a5

**Comment by xomx** [comment]
@jani8787 
As you were told, always paste here at least your Notepad++ menu > ? > Debug Info...

I cannot reproduce your issue (Win10, portable x64 N++ v8.5.8) but the others can:  [Through the title bar](https://community.notepad-plus-plus.org/topic/20077/through-the-title-bar) or in #8660 .

Do you have a multi-monitor setup?
If so maybe this workaround could help you: https://github.com/notepad-plus-plus/notepad-plus-plus/issues/8660#issuecomment-775185904

**Comment by jani8787** [comment]
Yes I have 2 monitor. And this behaviour exist on second one. If I try that workarround the second monitor will be good BUT the first will have the same mentioned bug :( (originally the first working well!)

**Comment by jani8787** [comment]
Notepad++ v8.5.8   (64-bit)
Build time : Oct 15 2023 - 21:43:56
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 11 Enterprise (64-bit)
OS Version : 22H2
OS Build : 22621.2428
Current ANSI codepage : 1252
Plugins : 
    ComparePlugin (2.0.2)
    Linefilter3 (1)
    mimeTools (2.9)
    NppConverter (4.5)
    NppExport (0.4)
    XMLTools (3.1.1.12)

**Comment by chcg** [comment]
See https://github.com/notepad-plus-plus/notepad-plus-plus/pull/9381 on problems with  "Per-monitor" and "Per-monitor V2"

**Comment by xomx** [comment]
@chcg 

Thanks. Yes, this is exactly what I meant before.

IMO - these previous attempts failed because one cannot simply declare an app as Per-monitor aware without proper WM_DPICHANGED handler. Returning TRUE there only is a nonsense. N++ will need to manually resize and reposition its GUI stuff according to the received WM_DPICHANGED lParam.

**Comment by Tyrben** [comment]
This doesn't solve the "mouse standing at the top-right edge, it clicks under the Notepad window"

**Comment by Hawkling** [comment]
"mouse standing at the top-right edge, it clicks under the Notepad window"

This is still a very annoying issue, keeps closing the wrong apps.

**Comment by pryrt** [comment]
> This is still a very annoying issue, keeps closing the wrong apps.

As mentioned above, #8660 already tracks that issue.  This 14337 is closed because there doesn't need to be multiple open issues tracking it.  Actually, the more-recent #15639 is also still open, despite being a duplicate of #8660.  Commenting on one of the open versions might be more productive than on a closed issue.
