### ISSUE TITLE
Where is "free palestine edition"?

### ISSUE THREAD

**Issue by ymiftnfntyt** [notepad-plus-plus/notepad-plus-plus#14331]
### Description of the Issue
The authors seize to support "**free speech**, **human right** and **peace**" anymore, quite a strange behavior depending on what they have actively expressed before right?

### Steps to Reproduce the Issue
1. Open https://notepad-plus-plus.org/downloads/v8.5.8/

### Expected Behavior
At least some "comments" regarding to the multiple genocides occuring on both side of this god damm war.

### Actual Behavior
Literally nothing. A strange yet deafening vacancy.

**Comment by Yaron10** [comment]
**Free the World of Hamas-ISIS**.
Issue solved.

**Comment by p4pper** [comment]
> **Free the World of Hamas-ISIS**. Issue solved.

You are a fucking retard if you think Hamas is the issue

**Comment by cskyaluna** [comment]
> ### Description of the Issue
> 
> The authors seize to support "**free speech**, **human right** and **peace**" anymore, quite a strange behavior depending on what they have actively expressed before right?
> ### Steps to Reproduce the Issue
> 
>     1. Open https://notepad-plus-plus.org/downloads/v8.5.8/
> 
> 
> ### Expected Behavior
> 
> At least some "comments" regarding to the multiple genocides occuring on both side of this god damm war.
> ### Actual Behavior
> 
> Literally nothing. A strange yet deafening vacancy.

 I see just one genocide on one side that's currently ongoing.

**Comment by clinasama** [comment]
free palestine
