### ISSUE TITLE
Treat .ino files as C++

### ISSUE THREAD

**Issue by ccoenen** [notepad-plus-plus/notepad-plus-plus#1433]
Arduino code is actually just C++ code, so it could just use the built-in c++ capabilities of Notepad++.

**Comment by googlebleh** [comment]
You can do this yourself by going to **Settings > Style Configurator > C++** and adding "ino" to the "User ext." field in the bottom left:

![inoino](https://cloud.githubusercontent.com/assets/7331683/12956303/5aa977d2-cff5-11e5-8168-eca060b2aa4c.png)

**Comment by ccoenen** [comment]
Yes, but i think it's a sensible default to have.

**Comment by milipili** [comment]
from [Arduino FAQ](https://www.arduino.cc/en/Main/FAQ):
> In fact, you already are; the Arduino language is merely a set of C/C++ functions that can be called from your code. Your sketch undergoes minor changes (e.g. automatic generation of function prototypes) and then is passed directly to a C/C++ compiler (avr-g++).

Since this extension does not seem to be used for something else, we can add it.
