### ISSUE TITLE
the search function does not find text

### ISSUE THREAD

**Issue by jvbutter01** [notepad-plus-plus/notepad-plus-plus#14335]
### Description of the Issue
when using CTRL F to find text in the document it will not find it. Clearly in the img attached, you can see the test is there. 
This is NOT 100% of the time. sometimes in this same document ( other docs also) it will find the text selected. 

![search Notepadd++](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/150162327/c6c20018-6a7b-4b6a-80fd-93cbb12a9a84)

### Steps to Reproduce the Issue

1. nothing
2. 
3. 

### Expected Behavior
should find the text

### Actual Behavior
error, cannot find the text "6119"

### Debug Information

Notepad++ v8.4.2   (64-bit)
Build time : May 29 2022 - 16:47:30
Path : C:\Program Files\WindowsApps\HaukeGtze.NotepadEditor_1.8420.1.0_x64__6bk20wvc8rfx2\notepad++.exe
Command Line : $COMMAND_LINE_PLACEHOLDER$
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 11 (64-bit) 
OS Version : 22H2
OS Build : 22621.2428
Current ANSI codepage : 1252
Plugins : 
    mimeTools (2.8)
    NppConverter (4.4)
    NppExport (0.4)

**Comment by rddim** [comment]
Yes, because `Wrap around` is not checked and your current line (28) is under the searched (24).

**Comment by jvbutter01** [comment]
wrap around ? what does that do. seems pretty stupid, we are looking for 4 digits.

**Comment by jvbutter01** [comment]
Nope you are incorrect. I just did a search again, and it shows up... 
![notepad search 2](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/150162327/7d42422c-a227-4ab5-b79a-d79b5de38f21)

**Comment by jvbutter01** [comment]
if you do click as you say WORD WARP, the search does find every time. without, its hit and miss.

why so inconsistent?

![notepad search 3](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/150162327/8398fee9-850f-4a6e-a342-1044bb992ad7)

**Comment by alankilborn** [comment]
>I would disagree with you both

Really...please don't do that.

> I just did a search again, and it shows

Your caret (do you know what that is?) this time was above the 6119.

https://npp-user-manual.org/docs/searching/#:~:text=%E2%98%90-,Wrap%20Around,-%3A%20If%20checked%2C%20when

**Comment by jvbutter01** [comment]
[alankilborn](https://github.com/alankilborn),  are you saying the search starts and goes up only ? so when i am on line 24 and the searched item is on 28 it will never find it? Unlike word / excel it searches whole document.

**Comment by jvbutter01** [comment]
no thats not it either. I clicked line 19 and it would go down to line 24

**Comment by jvbutter01** [comment]
so another bug is when you do find it, see the GREEN text. and then select find again, it will give an error. 
![notepad search 4](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/150162327/589121fa-3ad3-4dfd-b0df-b327ff25eec9)

**Comment by jvbutter01** [comment]
> > I would disagree with you both
> 
> Really...please don't do that.
> 
> > I just did a search again, and it shows
> 
> Your caret (do you know what that is?) this time was above the 6119.
> 
> https://npp-user-manual.org/docs/searching/#:~:text=%E2%98%90-,Wrap%20Around,-%3A%20If%20checked%2C%20when

yes i see what the link is pointing to. Yes having that finds it each time. 
Next question, how to make that default ON
Some of us older generation foget things. Having default CHECK is better

**Comment by alankilborn** [comment]
> I will still argue the consistency in search w/o this enabled

There is no inconsistency.

Please close this issue.
