### ISSUE TITLE
Strange naming

### ISSUE THREAD

**Issue by JaggedNel** [notepad-plus-plus/notepad-plus-plus#14345]
### Description of the Issue
I'm just surprised that the latest version wasn't about Israel's brutal invasion of the Palestinian Enclave. In just a month, Israel has already killed almost twice as many civilians as have been killed on both sides in Ukraine over the past few years. What logic is the author guided by? Or not logic, but hypocrisy? First he calls for a war against sports, then he turns over and already wants to help fight the Russians... And now he doesn't notice anything? Or does the author really not want anyone to be killed, except for those who can be killed, as the government told him? Very interesting, waiting for an answer

![image](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/33070237/1c1cce77-aa3e-4857-a563-1b77f7b8852f)

**Comment by Yaron10** [comment]
One bright morning Israel brutally attacked the innocent and peaceful "Palestinian Enclave".
The shameless distortion of recent history and twisted morality are quite expected from the people whose leadership and masses strongly supported Hitler in World War II.

**Free the World of Hamas-ISIS!**

**Comment by JaggedNel** [comment]
> One bright morning Israel brutally attacked the innocent and peaceful "Palestinian Enclave". The shameless distortion of recent history and twisted morality are quite expected from the people whose leadership and masses strongly supported Hitler in World War II.
> 
> **Free the World of Hamas-ISIS!**

Your message is the most stupid thing i read for this week. Clowning literally in every single word XD
