### ISSUE TITLE
Python f-strings are not recognised as text strings

### ISSUE THREAD

**Issue by IanSav** [notepad-plus-plus/notepad-plus-plus#14353]
### Description of the Issue
Python 3.10 and higher now offer f-strings.  These are quoted text strings that allow inline specification of python variables and code.  This code like:
`print("Variable fred has a value of '%s'." % fred)`
can now be written as:
`print(f"Variable fred has a value of '{fred'}'.")`
In the first version Notepad++ shows the quoted string in the text highlight while the second is missing the text highlight.

### Steps to Reproduce the Issue
Any use of f-strings within the editor in Python mode will show the issue.

### Expected Behavior
If Notepad++ is correctly detecting the new syntax then the string checking and highlighting should work as expected.

It would be helpful if the text within the braces "{}" of f-strings is shown as code and not text.

### Actual Behavior
At the moment text highlighting is not happening.

### Debug Information

Notepad++ v8.5.8   (64-bit)
Build time : Oct 15 2023 - 21:43:56
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : "Filename.py" 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 10 Pro (64-bit)
OS Version : 22H2
OS Build : 19045.3636
Current ANSI codepage : 1252
Plugins : 
    DSpellCheck (1.4.24)
    HexEditor (0.9.12)
    HTMLTag (1.3.5)
    mimeTools (2.9)
    NppConverter (4.5)
    NppExport (0.4)
    Remove Duplicate Lines (1.3)
    SpeechPlugin (0.4)
    XMLTools (3.1.1.13)
    zoomdisabler_x64 (1.2)

![Notepad++Highlighting](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/6904736/06634d8f-d01c-49f2-a35c-ed43e5dcfd39)

**Comment by alankilborn** [comment]
In Notepad++ 8.5.8:

![image](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/77065706/ce872b66-6f80-47d1-8dc1-dc61d7c03dca)

You just need to update your langs.xml file.
Get new one from downloading 8.5.8 portable and extracting that file.
Either copy over your outdated langs.xml file, or, if you've ever modified settings for languages and want to keep those mods, diff the 8.5.8 file with yours and merge relevant updates into your version of the file.

**Comment by IanSav** [comment]
There is no langs.xml in the 8.5.8 portable package.

I did note that a number of my XML files were out of date so I updated them all manually.  (They were never changed by me.)  Still not joy.

If files are untouched by the user from a previous release they should be updated during the upgrade process.  ;)

**Comment by rdipardo** [comment]
> There is no langs.xml in the 8.5.8 portable package.

It will be generated from `langs.model.xml` the first time you run the portable Notepad++, or any time you delete the generated `langs.xml` after that. `langs.model.xml` is updated with every release.

> If files are untouched by the user from a previous release they should be updated during the upgrade process. ;)

The configurable files under `%AppData%\Notepad++` should be re-generated from the newest model once you delete them, same as explained above. Leaving them "untouched" is what prevents the automatic refreshing.

**Comment by IanSav** [comment]
Thank you all.  The old files in the AppData directory were the issue.  All good now.

**Comment by IanSav** [comment]
Thank you all.  The old files in the AppData directory were the issue.  All good now.

**Comment by IanSav** [comment]
Thank you all.  The old files in the AppData directory were the issue.  All good now.
