### ISSUE TITLE
Orange/ green line not working on 8.5.8

### ISSUE THREAD

**Issue by Danieltz19** [notepad-plus-plus/notepad-plus-plus#14369]
![1000087540](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/151428195/4efc7d5e-7bd6-4fef-b48d-54b5a048cd6e)
When i checked the option " display change history" after reset the app, it's not showing the Orange/green line for history

**Comment by alankilborn** [comment]
Fill out the issue template or the author will close your issue.

**Comment by donho** [comment]
@alankilborn 
you're right about it.
