### ISSUE TITLE
Unicode superscript characters are shown as placeholders but only in some positions

### ISSUE THREAD

**Issue by native-api-work** [notepad-plus-plus/notepad-plus-plus#14363]
### Description of the Issue
Unicode superscript characters are sometimes shown as placeholder characters

### Steps to Reproduce the Issue
1. Open the attached [bug.txt](https://github.com/notepad-plus-plus/notepad-plus-plus/files/13391842/bug.txt)
2. See that some characters are shown as square placeholders: [screenshot](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/110392407/315ace02-2f23-4f27-9378-6db597ae12ce)

3. Paste superscript "-4" from the 2nd line to the 1st => it shows correctly
4. Delete superscript "-"on the 1st line => the remaining superscript 4 is replaced with a square placeholder.
5. Delete superscript "-" on the 2nd line => the remaining superscript 4 is not replaced with a placeholder

### Debug Information
Notepad++ v8.5.8   (64-bit)
Build time : Oct 15 2023 - 21:43:56
Path : C:\Users\2\Totalcmd\Plugins\exe\Notepad++\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : ON
Cloud Config : OFF
OS Name : Windows 10 Pro (64-bit)
OS Version : 22H2
OS Build : 19045.3208
Current ANSI codepage : 1251
Plugins : 
    HexEditor (0.9.12)
    JsonTools (5.4)
    mimeTools (2.9)
    NppConverter (4.5)
    NppExport (0.4)
    NppXmlTreeviewPlugin (2)
    XMLTools (3.1.1.13)

**Comment by alankilborn** [comment]
Try:

![image](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/77065706/4a8819eb-ca51-4fb5-b37d-18fa9fd58382)

**Comment by native-api-work** [comment]
@alankilborn Thanks, `Settings->MISC.->Use DirectWrite` solves the problem!

**Comment by alankilborn** [comment]
@donho I feel like I've answered this same bug report a hundred times; is it time yet for _DirectWrite_ to be defaulted to ON?

**Comment by pryrt** [comment]
> is it time yet for DirectWrite to be defaulted to ON?

I think it should be.  Changing the default wouldn't affect people who already have it installed and set to their desired preference, and, given the comments we've seen here and in the Forum, turning it on helps way more often than turning it off does.

**Comment by donho** [comment]
Enabling Direct Write Technology by default will be in the next release.
https://github.com/notepad-plus-plus/notepad-plus-plus/commit/975d29b30bfd624b6392541b133c2bd32f3212b0
