### ISSUE TITLE
Incorrect Localization Offsets

### ISSUE THREAD

**Issue by wbic16** [notepad-plus-plus/notepad-plus-plus#14378]
### Description of the Issue
While working on a fork of Notepad++, I ran across the comments in `BOOL Notepad_plus::notify(SCNotification *notification)` near line 532. In my fork, I plan to update `itemUnitArray` - so I went over to localization.cpp to review the mappings. Much to my surprise, they are no longer lined up.

### Steps to Reproduce the Issue
The offsets in tabCmSubMenuEntryPos from localization.cpp should point to valid rows in itemUnitArray. Currently, they do not. I don't use localization, so I'm not entirely sure how this manifests in the UI...

The old indexes map 5 commands - of which only close multiple tabs appears to work properly.
0. "Close Multiple Tabs" - offset 1 - seems OK
1. "Open into" - offset 4
2. "Copy to Clipboard" - offset 13
3. "Move Document" - offset 14
4. "Apply Color to Tab" - offset 15

### Expected Behavior
I expected these offsets to actually match the observed indexes.

### Actual Behavior
The given indexes would map as follows:
1. Open into -> Close All Unchanged
2. Copy to Clipboard -> Move to Recycle Bin
3. Move Document -> Reload
4. Apply Color to Tab -> Print

### Debug Information
Notepad++ v8.5.8   (64-bit)
Build time : Nov 19 2023 - 18:23:39
Path : C:\Source\notepad-plus-plus\PowerEditor\visual.net\x64\Debug\Notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 11 Home (64-bit)
OS Version : 22H2
OS Build : 22621.2715
Current ANSI codepage : 1252
Plugins : none

Notepad_plus.cpp tells you to keep location.cpp matched up...
![image](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/88622/54f2ddd6-83e8-41d2-8e06-465aeeff7328)

But localization.cpp doesn't currently match!
![image](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/88622/83b9ffa7-67f7-44fd-b70c-9d04451ec5bd)

**Comment by wbic16** [comment]
If anyone uses location, could you confirm steps to reproduce this bug? I think mapping "Copy to Clipboard" as "Move to Recycle Bin" would be a bad idea? ;)

**Comment by donho** [comment]
![image](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/90293/7099f4d3-9764-4d98-966e-0c1cb76e9e06)
