### ISSUE TITLE
Cant use functions that use the windows browser dialog in Windows Server Core 2019 using 8.5.8 or 8.5.7 (worked on 7.7.1)

### ISSUE THREAD

**Issue by AbdullaQeblawi** [notepad-plus-plus/notepad-plus-plus#14389]
### Description of the Issue
Opening or Saving new files in the UI does nothing (file browser dialog is expected to open). 
Environment: Windows Server Core 2019 
Version: 8.5.8 or 8.5.7 both x64 and x86 bit versions
Last Version that worked (didnt test all the versions since): 7.7.1

### Steps to Reproduce the Issue
1. Install 8.5.8 or 8.5.7 both x64 or x86 bit versions  
2. Open Notpad++
3. Click File > Open or Try to save a newly edited file

### Expected Behavior
File Browser Windows Dialog should show

### Actual Behavior
Nothing happens. No errors. 

### Work Around
Specify the filepath in commandline. Saving existing files works as it does not need to open the file browser dialog. 

### Debug Information
Notepad++ v8.5.7   (64-bit)
Build time : Sep  6 2023 - 23:13:49
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : 
Admin mode : ON
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows Server 2019 Datacenter (64-bit)
OS Version : 1809
OS Build : 17763.4974
Current ANSI codepage : 1252
Plugins : 
    mimeTools (2.9)
    NppConverter (4.5)
    NppExport (0.4)

**Comment by xomx** [comment]
Known issue, see the #9621 .
There is also a report that it works ok on server core >= 2022, but not on the 2019.

The needed MS comdlg32.dll is probably missing on your system (maybe you can add it manually somehow as a workaround).

**Comment by AbdullaQeblawi** [comment]
Thanks!
