### ISSUE TITLE
Occurrence Highlighting

### ISSUE THREAD

**Issue by kbrewer08** [notepad-plus-plus/notepad-plus-plus#1438]
Sorry, this isn't actually an issue, but I think this may be the best place to ask this. I am using scintilla in my own project and I'm trying to get occurrence highlighting to work right, but I'm having trouble in figuring out exactly how to use scintilla's styling to do so.

In Notepad++, when you double click on something, it automatically highlights all occurrences of that item. You can also choose to mark all highlighted items permanently in a particular color. I am assuming, maybe erroneously, that this is using scintilla's styling feature. As in, set up a style, and then do startstyling() and setstyling(). I can find all the occurrences just fine, it's just the actual styling that I can't seem to get right. I figured it'd be as straight-forward as start and set, but clearly not since all kinds of wacky things are happening to me. 

I looked through the Notepad++ source for a while but couldn't really clearly follow how this feature worked. Can someone familiar with this functionality post all the relevant snippets that make this work?

**Comment by dail8859** [comment]
What you want are [indicators](http://www.scintilla.org/ScintillaDoc.html#Indicators). They are used to display additional information over the top of styling. There aren't any "clean" snippets of code from Notepad++, but in general just define your indicator, and when a whole word is "selected", find all the occurrences of it and mark it with that indicator. Referencing the Scintilla link should be sufficient.

**Comment by dail8859** [comment]
Also, it's not easy to follow but [this](https://github.com/notepad-plus-plus/notepad-plus-plus/blob/71edfb2dba3fd94b9b8b642e3d7dd7c00eeed307/PowerEditor/src/ScitillaComponent/SmartHighlighter.cpp#L40) is some of the code that does it within Notepad++

**Comment by kbrewer08** [comment]
Perfect! That's exactly what I needed! I've been asking around about this for days. I tried wxWidgets (they have a class that 1-to-1 maps scintilla), CodeBlocks (the IDE I'm using, it's based on wxWidgets and therefore uses scintilla for its editor), and I even asked on Stackoverflow. No one seemed to know and no one thought to point me away from styles and toward indicators.

I really appreciate the fast and perfect response, thanks!

**Comment by dail8859** [comment]
You'll have to close it or wait for an admin to see this. Should be a button down below to close it. Also there is a Notepad++ forum where you can post in the Plugin Development thread and possibly get some Scintilla help.
