### ISSUE TITLE
Hide Recent Files History

### ISSUE THREAD

**Issue by ptzie** [notepad-plus-plus/notepad-plus-plus#14380]
### Description of the Issue

For security reasons, is there a way to hide or, better, to not record recent files history?
### Steps to Reproduce the Issue

1.  Settings > Preferences > Recent File History
2.  Set Max at 0
3.  Check "Don't check..."

### Expected Behavior

No History
### Actual Behavior

History is still there
### Debug Information

No need

**Comment by xomx** [comment]
Cannot reproduce, for me (tested with portable x64 N++ v8.5.8, Win10) it is working ok:

![npp_RecentFilesHistory](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/13075183/3e34f6a1-27d5-4c35-9ee2-60badb68219d)


> ### Debug Information
> 
> No need

Apparently that is not true (as almost always, at least append here the N++ menu > ? > Debug Info...).

**Comment by ptzie** [comment]
You are right. However, if you work on several docs, save them, and quit NotePad++ without explicitly closing them, they are opened on the next Notepad run.

IMHO, this is a security risk. On subsequent runs, Notepad should provode en option to avoid opening recent files.

**Comment by xomx** [comment]
So it is not an issue with the Recent Files History at all.

Go to the Preferences > Backup and uncheck there the 'Remember current session for next launch'.

**Comment by ptzie** [comment]
Thank you !!!
Though it was hard for me to imagine where and what this setting was, that did it.
