### ISSUE TITLE
Line Copy doesn't work as expected

### ISSUE THREAD

**Issue by CennoxX** [notepad-plus-plus/notepad-plus-plus#14399]
@donho (per https://github.com/notepad-plus-plus/notepad-plus-plus/issues/14296#issuecomment-1823722799)

With Notepad 8.6 "Visual Studio Line Shortcut options" (#14298) were added, but the implemented behavior differs from the Visual Studio behavior. In Visual Studio the whole line will be added in the line above, in Notepad++ the line will be added on the cursor position. I'm probably biased because I've used Visual Studios copy function before, but I think Visual Studios behavior is more useful.

### Steps to Reproduce the Issue
1. Set cursor in the middle of a line, without making a selection
2. Press <kbd>ctrl</kbd>+<kbd>c</kbd>
3. Optionally change the line position with <kbd>↑</kbd> or <kbd>↓</kbd>
4. Press <kbd>ctrl</kbd>+<kbd>v</kbd>

### Expected Behavior
The complete line is inserted as a line, as it is done in Visual Studio
![notepad++_Hhlwy40nSO](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/6975881/f71eccfe-4073-4723-ae8b-4686c74b2e90)

### Actual Behavior
The line is inserted at cursor position, making line breaks
![notepad++_s2voDBXErJ](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/6975881/72b5b576-4052-44b7-ac14-9431b8d85e9c)

### Debug Information
Notepad++ v8.6   (64-bit)
Build time : Nov 22 2023 - 02:58:14
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 10 Pro (64-bit)
OS Version : 22H2
OS Build : 19045.3693
Current ANSI codepage : 65001
Plugins :

**Comment by donho** [comment]
@CennoxX 
> Expected Behavior
The complete line is inserted as a line, as it is done in Visual Studio

Yes, after trying, I confirm this behaviour in Visual Studio.
However, I don't think it's a "correct" behaviour and it could confuse our users - the pasted place should be where there's carret logically. 
I would like follow the "good" behaviour of any unknown editor, but not the illogical behaviour of famous editor. 

Therefore this "feature" won't be implemented.
