### ISSUE TITLE
Korean user report

### ISSUE THREAD

**Issue by magsabal** [notepad-plus-plus/notepad-plus-plus#14400]
Thank you very much for making such great software.

I am a Korean user.

1. After editing a document, pressing the Han/English key on the keyboard to save 
   it in Korean mode does not work.
   If you press the Han/English keys to switch to English mode, it works normally.
2. If you press the HAN/English keys to open a file in Korean mode, the document
   does not open.
   Pressing the Han/English keys to switch to English mode works normally.
3. The versions where the above phenomenon occurs are 8.5.5, 8.5.6, 8.5.7,
   ,8.5.8., and 8.6.0

Best reguard

comradar@naver.com

**Comment by JamesKosin25** [comment]
Seems to work for me using Korean Microsoft IME...
What do you mean by Korean mode?

**Comment by circcc** [comment]
> Seems to work for me using Korean Microsoft IME... in Windows 10. What do you mean by Korean mode?

![unnamed](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/72944033/4538a4b7-d3a5-40b3-ae9b-fddcc14db889)
keyboard Korean(한)/English(영) key

**Comment by unicorn-system8** [comment]
I am experiencing the same issue. On Windows 11, when I create a new document and press "Save," nothing happens after I specify a file name and click the "Save" button in the window that appears.

Closing and reopening Notepad++ sometimes resolves the issue, but after some time, the same problem reoccurs.

When this issue happens, I also cannot open files. There were no such issues in Windows 10.

**Comment by xomx** [comment]
@magsabal 
> 3\. The versions where the above phenomenon occurs are 8.5.5, 8.5.6, 8.5.7,
>         ,8.5.8., and 8.6.0

If the problem starts with the v8.5.5 I suspect this commit: https://github.com/notepad-plus-plus/notepad-plus-plus/commit/6330a688b1460ed0da38a60943696f96b63c14d4

@unicorn-system8 
>  There were no such issues in Windows 10.

Are you sure that this issue is about Windows version (and not about the Notepad++ v8.5.5+)?

**Comment by unicorn-system8** [comment]
@xomx 
I was mistaken. I am using version 8.5.4 on Windows 10. 
I installed version 8.5.4 on Windows 11 and the "save" issue is not occurring anymore. 
It seems it's not a problem with the Windows version.

**Comment by xomx** [comment]
@80ROkWOC4j 
It seems that your #13788 caused this issue.

**Comment by donho** [comment]
@magsabal  @circcc @unicorn-system8 
Could you try PR #14593 to see if your issue is fixed?
