### ISSUE TITLE
Syntax colour highlighting of HTML with JSON context in JavaScript section

### ISSUE THREAD

**Issue by ajtruckle** [notepad-plus-plus/notepad-plus-plus#14413]
### Description of the Issue
You can use `\` to split long lines of text over multiple lines in the editor for clarity. But the syntax highlighting goes not respect this.

### Steps to Reproduce the Issue
Create a HTML file and insert a JavaScript section in the `<body> … </body>` element. Eg:

```js
<script>
   var language = {
       cs: {
           title: "S-89 Assignment Slips",
           phrase: "​The S-89 assignment slip templates are not automatically included with the application. \
                   Please email a copy of your S-89 PDF document using the \
                   <a href = \"https://www.notepad-plus-plus.com/contact-form/\" target=\"_blank\">Contact Form</a> on the website."
       }
  };
</script>
```

### Expected Behavior
Best to see the next screenshot. The second line after `\` should continue as a "string" colour. And ideally the `\` itself should be a different colour to make it stand out.

### Actual Behavior
I can show you:

![image](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/7985331/c7e892b9-9e23-47d5-b723-7bd94947f0a3)

### Debug Information
Notepad++ v8.5.8   (64-bit)
Build time : Oct 15 2023 - 21:43:56
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 11 Home (64-bit)
OS Version : 22H2
OS Build : 22621.2715
Current ANSI codepage : 1252
Plugins : 
    mimeTools (2.9)
    NppConverter (4.5)
    NppExport (0.4)

**Comment by mpheath** [comment]
Thanks for the code and image to detail the issue. I can reproduce in Notepad++ and in SciTE which both use the Lexilla component.

The code between double quotes and single quotes are alittle different in the html lexer. Seems the two quote types can be interchanged in Javascript, so for now could try single quotes

```js
<script>
   var language = {
       cs: {
           title: 'S-89 Assignment Slips',
           phrase: '​The S-89 assignment slip templates are not automatically included with the application. \
                   Please email a copy of your S-89 PDF document using the \
                   <a href = "https://www.notepad-plus-plus.com/contact-form/" target="_blank">Contact Form</a> on the website.'
       }
  };
</script>
```
 which appears to style correct and escaping the double quotes might not be neccessary.

Any fixes to the html lexer will require an issue to be posted at [Lexilla]. If you can do this :+1: .

[Lexilla]: https://github.com/ScintillaOrg/lexilla

**Comment by ajtruckle** [comment]
@mpheath 

Thanks for the suggestion. I can see that that would work, although I have 50+ languages in the file and some of them will need `'` handled as it is part of the text. So if I can get a solution with it as-is it would be ideal. Particularly if they also show the `\` character in a different colour.

I created a ticket as you can see, linking back to this one.

**Comment by mpheath** [comment]
@ajtruckle Lexilla 5.3.0 has been [merged](https://github.com/notepad-plus-plus/notepad-plus-plus/commit/dcc7e600c7faffdf9640ad69e57bdb64bdbc309d) into the Notepad++ master branch. The fix to this issue will be in the next release of Notepad++. You may close this issue as complete at your discretion. Thankyou for your patience to resolve this issue.
