### ISSUE TITLE
Several tab's problem

### ISSUE THREAD

**Issue by jporter-sdl** [notepad-plus-plus/notepad-plus-plus#1441]
Hi guys!

Case:
Open 25 files (more tab's than it can display).
Close several tab's by pressing the X icon on the tab's itself until you have one left.

Now you have several, say 15 files open but it will only display 1 tab. It should just always display the maximum it can.

**Comment by donho** [comment]
I believe this issue has been fixed since long time ago.
Update your Notepad++ to the latest version (v7.6.6).
If the issue persists, please create a new issue for it.
Thank you.
