### ISSUE TITLE
Tab icon glitch when pasting

### ISSUE THREAD

**Issue by alankilborn** [notepad-plus-plus/notepad-plus-plus#14410]
### Description of the Issue
When experimenting with Notepad++ 8.6's new multi-select feature, in certain circumstances when pasting, I noticed a visual glitch of the tab's icon.  Looking closer it briefly changes to a "lock" icon before quickly changing back to a "pencil" icon.

### Steps to Reproduce the Issue

1. Checkmark _Alternate icons_ in the _Editing_ preferences.
2. Create some text in a new tab:
```
bbbbbbbbbb
bbbbbbbbbb
bbbbbbbbbb
bbbbbbbbbb
bbbbbbbbbb
bbbbbbbbbb
ccccccccc
ddddddddd
eeeeeeeee
```
3. Make a column block selection:
![image](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/77065706/1d216818-0d47-46fe-81ad-974cf41d291a)
4. Press Ctrl+c to copy that selection.
5. Create some "multi-carets":
![image](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/77065706/2e6b0a96-4380-4d3b-b02b-60b599d232e1)
6. Press Ctrl+v to paste, while (IMPORTANT!) watching the file tab icon closely.

### Expected Behavior
No visual glitch of tab icon at paste.

### Actual Behavior
Visual glitch of tab icon at paste.
I see the "lock" briefly before it switches back to the "pencil".

### Debug Information
Notepad++ v8.6   (64-bit)
Build time : Nov 23 2023 - 16:58:44
Path : C:\NotepadPlusPlus\Misc\_NoBackup\Releases\npp.8.6\npp.8.6.portable.x64\notepad++.exe
Command Line : -multiInst
Admin mode : OFF
Local Conf mode : ON
Cloud Config : OFF
OS Name : Windows 11 Pro (64-bit)
OS Version : 22H2
OS Build : 22621.2428
Current ANSI codepage : 1252
Plugins : 
    mimeTools (2.9)
    NppConverter (4.5)
    NppExport (0.4)

**Comment by alankilborn** [comment]
I think I tracked the glitch to this line in the code:

```
// Hack for preventing the char "SYN" (0x16) from being adding into edit zone 
buf->setUserReadOnly(true);
```

https://github.com/notepad-plus-plus/notepad-plus-plus/blob/2768cf5422e6a443e7ed043ddd21a961e5c9859d/PowerEditor/src/ScintillaComponent/ScintillaEditView.cpp#L687C8-L687C8

If I comment-out this line and run, then do the STR (Steps To Reproduce) above, I don't see the glitching I described.

And...**_I don't see a "SYN" character added into the edit zone_**; using this setup:

![image](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/77065706/d08daf77-ce08-4794-9177-ff3e6a4ef1cd)

**Comment by alankilborn** [comment]
@donho Are you sure you were getting a "SYN" character put into the edit zone, before adding the hack?  If you remove the hack, can you give some STR (steps to reproduce) so that I could see it as well?

**Comment by pryrt** [comment]
I forgot step1, but I was able to replicate with my screen-capture software running.  The read-only mode lasts about 130ms.
![](https://i.imgur.com/8AAq0WT.gif)

**Comment by donho** [comment]
@alankilborn @pryrt 
This is intentional hack, due to between `Ctrl-V` keyDown & keyUp there is SYN char added.
The solution (hack) is make document read-only to prevent SYN from being added, then while keyUp, remove read-only from document.

I have no better solution so far. Please create a PR if you've got one.

>  If you remove the hack, can you give some STR (steps to reproduce) so that I could see it as well?

Just turn on "Show All Characters".

**Comment by alankilborn** [comment]
>Just turn on "Show All Characters".

But...from my screenshot earlier I have _Show Control Characters..._ on already, and SYN is a control character.  I wonder why I do not see it?

**Comment by donho** [comment]
@alankilborn 
If  you comment set read-only as following:
```cpp
// Hack for preventing the char "SYN" (0x16) from being adding into edit zone 
//buf->setUserReadOnly(true);
```
Then do as following:
https://github.com/notepad-plus-plus/notepad-plus-plus/pull/14338#issuecomment-1802645330

What did you see?

**Comment by alankilborn** [comment]
>What do you see?

After the paste, I see the following (incorrect) result, but no `SYN` character:

![image](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/77065706/c4ae1ac7-e884-4652-9002-5c7d35507388)

---

To show that I have visible control characters turned on, I move to lower in the file and type some Ctrl+e (an unmapped shortcut) characters:

![image](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/77065706/dc584a15-1806-49eb-9de9-2603d7cb1ab1)

**Comment by donho** [comment]
@alankilborn 

Now you modify the code to the following:
```cpp
								if (pasteToMultiSelection())
								{
									// Hack for preventing the char "SYN" (0x16) from being adding into edit zone 
									//buf->setUserReadOnly(true);

									//_isMultiPasteActive = true; // It will be set false with WM_KEYUP message
									return TRUE;
								}
```
and do the same manipulation, you will see SYN char appear.

**Comment by alankilborn** [comment]
Ok, got it, thank you:

![image](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/77065706/3e0559fc-8299-492d-ac30-28645b8e9993)

I'll see if I have some ideas about it...
