### ISSUE TITLE
Unable to change the highlight color in Python code

### ISSUE THREAD

**Issue by user1823** [notepad-plus-plus/notepad-plus-plus#14414]
### Description of the Issue

In the following code, I want to give a different color to the words `int`, `input`, `range`, `print`. I have tried to adjust the settings in the Style Configurator but the color of no style option seems to affect the color of these words.

```py
rows = int(input("Enter number of rows: "))

k = 0
count=0
count1=0

for i in range(1, rows+1):
    for space in range(1, (rows-i)+1):
        print("  ", end="")
        count+=1
    
    while k!=((2*i)-1):
        if count<=rows-1:
            print(i+k, end=" ")
            count+=1
        else:
            count1+=1
            print(i+k-(2*count1), end=" ")
        k += 1
    
    count1 = count = k = 0
    print()
```

### Actual Behavior
<img width="334" alt="image" src="https://github.com/notepad-plus-plus/notepad-plus-plus/assets/92206575/e8e23f9c-883f-4626-9e3a-85e456349783">

### Debug Information
```
Notepad++ v8.5.8   (64-bit)
Build time : Oct 15 2023 - 21:43:56
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 11 Home Single Language (64-bit)
OS Version : 22H2
OS Build : 22621.2715
Current ANSI codepage : 1252
Plugins : 
    mimeTools (2.9)
    NppConverter (4.5)
    NppExport (0.4)
```

My theme: [Fluent.txt](https://github.com/notepad-plus-plus/notepad-plus-plus/files/13470577/Fluent.txt) (Modified from https://github.com/ikoshura/Fluent-Npp)

**Comment by mpheath** [comment]
@user1823  Compare with stylers.model.xml. Fluent.txt has `14` Python styles while stylers.model.xml has `19`. Also styleID uses `12` twice for Python which seems a typo maybe. You want the lines containing `name="BUILTINS"` for styling print...

> these words is missing from the Style Configurator.

As they are missing from your file. The Style Configurator inherits them from the file.

**Comment by user1823** [comment]
> Fluent.txt has 14 Python styles while stylers.model.xml has 19.

Thanks; issue solved 😊
