### ISSUE TITLE
Not bug! Please consider to use website link mapped to latest stable version of installation file

### ISSUE THREAD

**Issue by cquresphere** [notepad-plus-plus/notepad-plus-plus#14428]
### Description of the Issue
Current links to download installation file are very difficult to automate and needs to be manually inputted or web-scrapped from Git Hub.
[https://github.com/notepad-plus-plus/notepad-plus-plus/releases/download/**v8.6/npp.8.6.Installer.x64.exe**](https://github.com/notepad-plus-plus/notepad-plus-plus/releases/download/v8.6/npp.8.6.Installer.x64.exe)

similar to the main website:
[https://notepad-plus-plus.org/downloads/**v8.6**/](https://notepad-plus-plus.org/downloads/v8.6)

### Steps to Reproduce the Issue
Use the latest link from 

### Expected Behavior
If links were composed like this it would be great :)
https://notepad-plus-plus.org/downloads/latest/x64/npp.latest.Installer.x64.exe

or 
[https://github.com/notepad-plus-plus/notepad-plus-plus/releases/download/**latest/npp.latest.Installer.x64.exe**](https://github.com/notepad-plus-plus/notepad-plus-plus/releases/download/latest/npp.latest.Installer.x64.exe)
mapped to e.g.:
[https://github.com/notepad-plus-plus/notepad-plus-plus/releases/download/**v8.6/npp.8.6.Installer.x64.exe**](https://github.com/notepad-plus-plus/notepad-plus-plus/releases/download/v8.6/npp.8.6.Installer.x64.exe)

https://notepad-plus-plus.org/downloads/latest/x86/npp.latest.Installer.x86.exe
mapped to e.g.:
https://github.com/notepad-plus-plus/notepad-plus-plus/releases/download/v8.6/npp.8.6.Installer.x64.exe

etc. 

### Final words

Please consider this idea I would be greateful for that.

Anyway. I would like to thank you (all the Notepad++'s team) for the great product I hope you have a lot of satisfaction and profit from this project. I hope you will continue to improve it.

**Comment by PGomersall** [comment]
The location of the latest installers is always the same and very easy to automate. Here is an example that includes a version check, download and installation in PowerShell which needs to be run as admin:
$assetPattern = "*.Installer.x64.exe"
$releasesUri = "https://api.github.com/repos/notepad-plus-plus/notepad-plus-plus/releases/latest"
$asset = (Invoke-RestMethod -Uri $releasesUri -Method Get -ErrorAction stop).assets | Where-Object name -like $assetPattern
$downloadUri = $asset.browser_download_url
$WebVersion = ((Invoke-RestMethod -uri $releasesUri -Method Get -ErrorAction stop | Select-Object -first 1).tag_name).substring(1)
$Installed = (Get-ItemProperty HKLM:\Software\Microsoft\Windows\CurrentVersion\Uninstall\* | Select DisplayName, DisplayVersion | Where { $_.DisplayName -eq "Notepad++ (64-bit x64)" }).DisplayVersion
If ([System.Version]$WebVersion -gt [System.Version]$Installed) {
	If (!(Test-Path C:\Temp)) {
		New-Item -Path "C:\Temp" -ItemType Directory
	}
	$installerPath = "C:\Temp\$($asset.name)"
	Invoke-RestMethod -Uri $downloadUri -OutFile $installerPath
pause	
Start-Process -FilePath $installerPath -ArgumentList "/S" -Wait -NoNewWindow
	Remove-Item $installerPath -Force
}

**Comment by cquresphere** [comment]
Thank you <3
