### ISSUE TITLE
v 8.6 column delete also deleted an unexpected end-of-lines

### ISSUE THREAD

**Issue by mkupper** [notepad-plus-plus/notepad-plus-plus#14426]
### Description of the Issue
This is a v8.6 regression.

I had some text with varying line lengths and wanted to add a second column to the right at column 37.  On lines 6 and 7 below I manually added the tabs. I saw that lines 1 to 5 were shorter and so rather than manually adding tabs needing to pay attention I selected the area and then did a search/replace to replace `$` with 9 tabs `\t\t\t\t\t\t\t\t\t`.

My normal practice at this point is I moved the typing cursor to the end of line 7 and while holding Shift+Alt I did up-arrow to line 1 and then held down the right arrow key until things stopped jumping around meaning I was past the end of the longest line. I then pressed Del but was surprised that line 7 was appended on line 6 and line 8 was appended to line 7.

With Notepad v8.5.8 this worked as I expected and it deleted the excess tabs without also deleting any end of line marks.  To make the end of line visible in this post I appended a tilde `~` to each line. They were not part of the test and so should be removed if you want to copy the test data below into Notepad to reproduce the issue.

The 9_9_9_... text was already there as the second column of text for line 8. I was about to add the second column of text for lines 1-7 which lead me to add the tabs and then try to trim the excess so that all lines ended at column 37 meaning I could type stuff and then up-arrow as I worked my way up the table.

### Original data
```txt
1_1_1_									~
2_2_2									~
3_3_3_3_3									~
4_4_4_4_4_4_4_4_4_4_4_									~
5_5_5_5_5_									~
6_6_6_6_6_6_6_6_6_6_6_6_6_6_6_		~
7_7_7_7_7_7_7_7_7_7_7_7_7_7_7		~
8_8_8_8_8_8							9_9_9_9_9_9_9_9_9_~
```

### Results after the `Del` using Notepad++ v8.6
```txt
1_1_1_								~
2_2_2								~
3_3_3_3_3							~
4_4_4_4_4_4_4_4_4_4_4_				~
5_5_5_5_5_							~
6_6_6_6_6_6_6_6_6_6_6_6_6_6_6_		7_7_7_7_7_7_7_7_7_7_7_7_7_7_7		8_8_8_8_8_8							9_9_9_9_9_9_9_9_9_~
```

### Results after the `Del` using Notepad++ v8.5.8 - this is the result I expected.
```txt
1_1_1_								~
2_2_2								~
3_3_3_3_3							~
4_4_4_4_4_4_4_4_4_4_4_				~
5_5_5_5_5_							~
6_6_6_6_6_6_6_6_6_6_6_6_6_6_6_		~
7_7_7_7_7_7_7_7_7_7_7_7_7_7_7		~
8_8_8_8_8_8							9_9_9_9_9_9_9_9_9_~
```

**Comment by Coises** [comment]
To aid in reproduction, what was your tab size? I'm getting similar, but not identical, results (I'm losing the line break after line 7, but not the one after line 6).

Various versions of the same change in behavior exist; in general, pre-8.6 the delete key with a rectangular selection or a thin selection never deletes line endings, and the Enter key replaces the main selection only (bottom row if you selected top to bottom, top row if you selected bottom to top) and leaves the others unaffected.

In 8.6, the distinction between rectangular selections and multiple stream selections is blurred. In my opinion, the changes to the behavior of rectangular selections are unwelcome, and while there may be logic to it, from the standpoint of someone who uses rectangular selections often and multiple stream selections rarely, the new behaviors appear erratic.

**Comment by mkupper** [comment]
My tab size is x4 by it turns out my earlier example turns out to be hard to reproduce exactly and so let's do this:
1. Download v8.6 portable from https://github.com/notepad-plus-plus/notepad-plus-plus/releases/download/v8.6/npp.8.6.portable.x64.zip (this was found via https://notepad-plus-plus.org/downloads/v8.6/ )
2. Expand npp.8.6.portable.x64.zip into an empty folder.  I used c:\npp\test
3. Run `c:\npp\test\Notepad++.exe -multiInst c:\npp\test.txt`
4. I selected `Yes` to the pop up about Create new file / "c:\npp\test.txt" doesn't exist. Create it?
5. My test data is below which you should be able to load, including the trailing tabs, using that double box thing in the upper-right corner:
```txt
1_1_1_								
2_2_2								
3_3_3_3_3								
4_4_4_4_4_4_4_4_4_4_4_								
5_5_5_5_5_								
6_6_6_6_6_6_6_6_6_6_6_6_6_6_6_		
7_7_7_7_7_7_7_7_7_7_7_7_7_7_7		
8_8_8_8_8_8							9_9_9_9_9_9_9_9_9_
```
6. After copy pasting the test data into test.txt the cursor is at the end of the `9_9_9_9_9_9_9_9_9_`
7. `Ctrl-left-arrow` to get to the beginning of the `9_9_9_9_9_9_9_9_9_` and then up-arrow once to position the cursor at line 7, col 37, pos 168.
8. While holding `Shift+Alt` down up-arrow six times to line one and then while continuing to hold `Shift+Alt` down I held the right arrow down until I was past the end of the longest line. For reproduction let's make the right edge of the selection box we are creating at or past the right edge of the `9_9_9_9_9_9_9_9_9_` that's on line 8. The status line is not changing while I did this but getting a square looking box or something wider gets the same results at the following step.
9. Release the `Shift+Alt` keys and do one `Del` or `Delete`.
10. I ended up with:
```txt
1_1_1_								2_2_2								3_3_3_3_3							
4_4_4_4_4_4_4_4_4_4_4_				
5_5_5_5_5_							
6_6_6_6_6_6_6_6_6_6_6_6_6_6_6_		7_7_7_7_7_7_7_7_7_7_7_7_7_7_7		8_8_8_8_8_8							9_9_9_9_9_9_9_9_9_
```
There are also now many cursors.  I added `|` symbols below to show where they are. Copy/paste that into Notepad++ to better see the alignment with 4x tabs.
```txt
1_1_1_								|2_2_2								|3_3_3_3_3							|
4_4_4_4_4_4_4_4_4_4_4_				|
5_5_5_5_5_							|
6_6_6_6_6_6_6_6_6_6_6_6_6_6_6_		|7_7_7_7_7_7_7_7_7_7_7_7_7_7_7		|8_8_8_8_8_8							9_9_9_9_9_9_9_9_9_
```

While the results are quite pretty what I expected nor desired is below. I added `|` to show the cursors though again you'll need to copy paste that into Notepad++ with 4x tab stops to better see the alignment.
```txt
1_1_1_								|
2_2_2								|
3_3_3_3_3							|
4_4_4_4_4_4_4_4_4_4_4_				|
5_5_5_5_5_							|
6_6_6_6_6_6_6_6_6_6_6_6_6_6_6_		|
7_7_7_7_7_7_7_7_7_7_7_7_7_7_7		|
8_8_8_8_8_8							9_9_9_9_9_9_9_9_9_
```

**Comment by Coises** [comment]
@mkupper I get the same results as you, following your procedure starting from step 5 in my already-installed copy of 8.6. I get the results you expected in an installed copy of 8.5.8.

I also get the _expected_ results, even in 8.6, if I select **Edit** | **Delete** from the menu instead of using the Delete key in step 9.

**Comment by mkupper** [comment]
@Coises That prompted me to try a mouse right click and selecting Delete at step 9.  That also gets the expected/desired result.

The downside of fixing that is that it seems we would be doing more of the code and work in Notepad++ rather than relying on Scintilla.  I'm assuming the `Del` key is passed through to Scintilla and that both **Edit | Delete** and **Right click | Delete** are handled by Notepad++.  The good news is that the code already exists in Notepad++ and is confirmed to work as at least some people expect and desire.

**Comment by benrg** [comment]
Here's a much simpler reproduction of what I imagine is the same bug: extract `npp.8.6.portable.x64.7z` in a new directory, run it, type

```
abcd
ab
abcd
```

, make a rectangle selection containing the two `d`s, and press Delete. The expected result and 8.5.8 result is three lines: `abc`, `ab`, `abc`. The 8.6 result is two lines: `abc`, `ababc`.

The same thing happens if you select the `c` column, but it oddly doesn't happen if you select the `bc` columns.

As a workaround, pressing Backspace instead of Delete works correctly.

Please do fix this, as I do this kind of noncontiguous column deletion pretty frequently.

**Comment by mkupper** [comment]
I confirmed that the problem still exists in v8.6.1 which was released today.  I tested using the example @benrg posted.

**Comment by donho** [comment]
@benrg @mkupper 
Could you guys check #14536 please?
