### ISSUE TITLE
Notepad++ Access is denied session.xml for autosaving.

### ISSUE THREAD

**Issue by Sambouza** [notepad-plus-plus/notepad-plus-plus#14421]
### Description of the Issue

When notepad++ tries to autosave, it gives me a popup saying that it did not have sufficient permissions to write data to session.xml and note I did not install any plugin which autosaves text. Also, I intentionally turned on the checkbox bool which says "Don
t use %AppData% to make notepad++ more portable.

One solution I found is that to check "Run program as administrator" from compatibility from properties when right clicking on notepad++. However, this is irritating since each time notepad++ runs, it asks me for permissions. Is there a way to grant notepad++ permissions to read/write data from the notepad++ installation directory without administrator permissions or is that just not possible?

### Steps to Reproduce the Issue

1. When installing notepad++ from the installer, check "Don't use %AppData% to true

### Debug Information

Notepad++ v8.5.8   (64-bit)
Build time : Oct 15 2023 - 21:43:56
Path : D:\Program Files\Notepad++\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : ON
Cloud Config : OFF
OS Name : Windows 11 Pro (64-bit)
OS Version : 22H2
OS Build : 22621.2134
Current ANSI codepage : 1252
Plugins : 
    mimeTools (2.9)
    NppConverter (4.5)
    NppExport (0.4)

**Comment by xomx** [comment]
> Path : D:\Program Files\Notepad++\notepad++.exe

> Local Conf mode : ON

This is a bad combination - you have installed Notepad++ to a protected location ("...\\Program Files\\...") but at the same time you have declared the N++ as the portable one ("Local Conf mode : ON"). As a result N++ tries to save its session.xml file alongside the "notepad++.exe" file, so it needs the admin-rights to do so...

Solution: either use a truly portable version somewhere else, where you will not need the admin-rights for saving or delete the "D:\\Program Files\\Notepad++\\doLocalConf.xml" configuration file.

**Comment by donho** [comment]
@xomx 
Normally if destination of installation is %PROGRAMFILES% or %PROGRAMFILES(x86)%, `"Don't use %APPDATA%"` option will be disabled.
 
![image](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/90293/8dc65f81-60da-45b9-a334-dc8351cd66c0)

Obviously `D:\Program Files\` is not detected by NSIS installer as %PROGRAMFILES% so user can set this option, whereas the admin privilege is needed to modify this directory (which is done by the IT team I suppose).

I've check in NSIS script of Notepad++ installer, and I don't think we can do somethings to prevent this inconvenience.

@Sambouza I suggest you reinstall Notepad++ by unchecking `"Don't use %APPDATA%"` option to make your Notepad++ works nomally.

**Comment by ItsBrank** [comment]
Had this issue now, didn't realize if you selected don't use appdata in the installer you are REQUIRED to run notepad++ as admin every time you launch, or else it flat out doesn't work. Wish it would mention that in the installer...
