### ISSUE TITLE
I would like to use Bing not Google

### ISSUE THREAD

**Issue by r-a-n-y** [notepad-plus-plus/notepad-plus-plus#1442]
I personally use **Bing** so could you **please** add an **option to change search engines** since when I right click I would get in the context menu **Google Search**. So please may you **remove that feature** or just **add option to change search engines**. Thanks!

**Comment by ynar-ynah** [comment]
I honestly want that because I got banned from Google after hacking my mate's account.

**Comment by vlakoff** [comment]
You can add the following in `%AppData%\Notepad++\shortcuts.xml`:

    <Command name="Bing Search" Ctrl="no" Alt="no" Shift="no" Key="0">https://www.bing.com/search?q=$(CURRENT_WORD)</Command>

Then in `%AppData%\Notepad++\shortcuts.xml`:

    <Item MenuEntryName="Run" MenuItemName="Bing Search"/>

**Comment by r-a-n-y** [comment]
Thank you mate.

**Comment by r-a-n-y** [comment]
Thanks vlakoff!
