### ISSUE TITLE
Hide end of line characters

### ISSUE THREAD

**Issue by PavelBlend** [notepad-plus-plus/notepad-plus-plus#14433]
### Description of the Issue
I would like to be able to turn on the display of spaces and tabs, but turn off line end characters (CR LF).

If you enable this button, all non-printable characters will be displayed:

![02](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/7983249/1155d5a4-d566-44a4-8540-9452123232fb)

I need the ability to disable spaces and CR LF individually.

End of line characters are confusing and annoying:

![01](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/7983249/5e23042d-6b05-4bfe-b722-5529f771ff35)

My code has mixed spaces and tabs. And they are difficult to see visually, since CR LF interfere and make the text “dirty”.

**Comment by alankilborn** [comment]
Solution:

Stop using the button on the toolbar, and get finer control over what you want to display, here:

![image](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/77065706/4b24c292-b23c-4ea2-93fb-23f5b2d55c50)
