### ISSUE TITLE
what programs can edit these files?

### ISSUE THREAD

**Issue by ioc2e3** [notepad-plus-plus/notepad-plus-plus#14436]
Can NotePad++ edit these files ?

If not, what programs can edit these files ?

.aff
.bdic
.db
.dic
.qm
.jar
.json
.pak

.

**Comment by alankilborn** [comment]
Questions belong here: https://community.notepad-plus-plus.org/
Please close this issue.

**Comment by ioc2e3** [comment]
but ...

https://community.notepad-plus-plus.org/

Can't seem to log in ?

**Comment by pryrt** [comment]
> Can't seem to log in

go to https://community.notepad-plus-plus.org/login , then click on the Facebook, Google, or GitHub icon, and use one of those services to authenticate you for logging in.

See the [Community FAQ on logging in](https://community.notepad-plus-plus.org/topic/19196/faq-logging-in-to-this-forum)
