### ISSUE TITLE
Coloration (Language) lost when tab is dragged outside the window

### ISSUE THREAD

**Issue by nodj** [notepad-plus-plus/notepad-plus-plus#1443]
I have defined a custom coloration langage.
It is automatically used when I open files with a specific extension (.todo), this is great.
But when i drag the tab outside the window, notepad creates an other window for this tab, but then the coloration is lost.
I have to go in the Language menu, and select again my user-defined coloration.

**Comment by donho** [comment]
It's not bug.

**Comment by nodj** [comment]
Is it the expected behavior ?
