### ISSUE TITLE
Compare Plugin issue with notepad++

### ISSUE THREAD

**Issue by globappcots** [notepad-plus-plus/notepad-plus-plus#14435]
Compare plugin issue for notepad++ application.

We are trying to use the compare Plugin for notepad++ application but the plug is not working, kindly help us on this issue.

### Expected Behavior
after placing the compare plugin .dll file in the install directory (plugin should be visible in the application plug-ins tab)

### Actual Behavior
but the plug-in is not available in the plug-ins tab.

**Comment by alankilborn** [comment]
Please pursue support here: https://community.notepad-plus-plus.org/

And close this issue.
