### ISSUE TITLE
[NEW FEATURE] Add level of subfolders to "Find In Files" option

### ISSUE THREAD

**Issue by livius2** [notepad-plus-plus/notepad-plus-plus#14434]
Hi

In Find In Files there is a checkbox to "include subfolders", but sometimes there is a need to look only at some level of deep.
Please add such option, e.g.:
![image](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/14888294/c67659bb-52f7-4440-b324-5e38928cacb9)

**Comment by alankilborn** [comment]
It's a good idea.
The default value would be `0` which means "infinite levels down".

**Comment by saivaka** [comment]
Could this be assigned to me?

**Comment by alankilborn** [comment]
While **_I_** think it is a fine idea, you should wait for the author of Notepad++ 's endorsement that it would be accepted if you went to the effort.

**Comment by donho** [comment]
Though the "searching # levels" idea could be useful for few circumstances, such feature needs more finer tune which is not allowed to displayed in a small interface surface.
Therefore this feature won't be implemented.
