### ISSUE TITLE
[Feature Request] - Enable suggestions from all open files in NPP.

### ISSUE THREAD

**Issue by nrv-96** [notepad-plus-plus/notepad-plus-plus#14445]
**Description of the Feature**
Currently, I receive suggestions only from the working file. It would be much better if suggestions could be retrieved from all open files in NPP to enhance the range of available suggestions.

**Expected Behavior:**
You can watch the video below. In the video, you'll notice that when I write 'Configure,' it doesn't retrieve suggestions from any other opened files. However, I'm suggesting that if we could get results from all opened files, it would be much more helpful.

Additionally, if possible, it would be beneficial to add an enable/disable option in the settings. This way, users who do not find this feature helpful can choose to disable it.

https://github.com/notepad-plus-plus/notepad-plus-plus/assets/62826272/6fd5a77a-dfd7-40a6-880b-4c62d34b546e

**Comment by donho** [comment]
This feature, technically is not possible to be implemented. Even it is possible, there will be a performance issue, without mentioning that it'll be confusing for users.
