### ISSUE TITLE
My run menu got wiped!

### ISSUE THREAD

**Issue by JonnieLebert** [notepad-plus-plus/notepad-plus-plus#1444]
I sat down to do some work and a pop-up asked if I'd like to update my notepad++. I agreed for the heck of it and when it finished the run button menu was cleaned. All there's left is the 'Run... F5' option. No browser options or any thing else. How do I recover those options?

**Comment by JonnieLebert** [comment]
P.S. I also got my notepad++ back to the previous version, not that it helps.

**Comment by vlakoff** [comment]
In `%AppData%\Notepad++` directory, what's the content of `shortcut.xml`? Anything else missing?

**Comment by JonnieLebert** [comment]
In the Shortcuts.xml:
<NotepadPlus>
    <InternalCommands />
    <Macros />
    <UserDefinedCommands />
    <PluginCommands />
    <ScintillaKeys />
</NotepadPlus>

**Comment by vlakoff** [comment]
And `<macros>` and `<UserDefinedCommands>` sections are empty? That's strange. But unless there is a way to reproduce the issue, I doubt this could be fixed.

Meanwhile, you could repair by copying back the [original file](https://github.com/notepad-plus-plus/notepad-plus-plus/blob/master/PowerEditor/src/shortcuts.xml) to `%AppData%\Notepad++`.

Another possibility, maybe `%ProgramFiles(x86)%\Notepad++\shortcuts.xml` was altered? This one isn't supposed to be modified.

**Comment by JonnieLebert** [comment]
That code helped out big time! Maybe I should make backups of those .xml
files in case this happens again.

**Comment by donho** [comment]
Please ask your question in 
https://notepad-plus-plus.org/community/
