### ISSUE TITLE
Enhancement Request : Convert Contents of Search Window (or Specific set of results with Search Window) to new text document

### ISSUE THREAD

**Issue by markddrake** [notepad-plus-plus/notepad-plus-plus#14441]
### Description of the Issue

Current in order to search or perform other operations such as compare, it is necessary to select, copy and paste into a new document. It would be nice if there was an option on the right mouse menu to do this in one-click. If possible allow "Open as txt document" for the entire search window, or the results of a particular search.

### Steps to Reproduce the Issue

1. 
2. 
3.

**Comment by donho** [comment]
Ctrl-A & Ctrl-C are your best friends.

**Comment by alankilborn** [comment]
@markddrake 

You can script this functionality if you want to use the PythonScript plugin.

You'd need two scripts, the first one is found [HERE](https://community.notepad-plus-plus.org/post/90935).

Here's the second one, I call it `SearchResultsTextToNewTab.py`:

```py
# -*- coding: utf-8 -*-
from __future__ import print_function

from Npp import *
import SearchResultPanelGetText

t = SearchResultPanelGetText.SRPGT().get_text()
if len(t) > 0:
    notepad.new()
    editor.setText(t)
```

It gets _all_ the text from _Search results_, but you could change the Python code to make it do something lesser.
