### ISSUE TITLE
WordStar Key Mapping Not Working

### ISSUE THREAD

**Issue by Warren52** [notepad-plus-plus/notepad-plus-plus#14449]
I have my Scintilla shortcuts setup to mimic WordStar key presses.
As of the last auto update (ver 8.6), I have found an issue.

First, to SCI_LINEDOWN, I have DOWN or CTRL-X, which has been working fine. 
But with Ver 8.6, DOWN still works as expected but CTRL-X now:
- Deletes the line the cursor was on (regardless of where in the line the cursor was)
- Moves the cursor to the start of the line that moved up to replace the deleted line
- Moves the cursor down one more line

I modify SCI_LINEDOWN Shortcut by removing DOWN and leaving just CTRL-X and had the same results.
I modify SCI_LINEDOWN Shortcut by changing CTRL-X to CTRL-9 and it moves down a line like DOWN would.
I modify SCI_LINEDOWN Shortcut by putting in DOWN and CTRL-9 and it moves down a line with either 
keypress like DOWN would. HOWEVER!! When CTRL-X is pressed:
- Deletes the line the cursor was on (regardless of where in the line the cursor was)
- Moves the cursor to the start of the line that moved up to replace the deleted line
- Moves the cursor down one more line
- Places CAN with White letters on a Black background at the start of the line

Second, I am quite certain that as of ver 8.5.7, I was running 64-bit Notepad
as the install file I used has x64 in its title. But when I went to menu item
"?" (Question mark) then "Debug", I have the following which indicates the 8.6
update gave me a 32-bit program. Aside from the above issue, all else seems to
be working fine, but I just don't understand. I am leaving this with this issue
with the idea they may be related. 

Notepad++ v8.6   (32-bit)
Build time : Nov 23 2023 - 16:56:22
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 10 Enterprise (64-bit)
OS Version : 22H2
OS Build : 19045.3693
Current ANSI codepage : 1252
Plugins : 
    DSpellCheck (1.5)
    mimeTools (2.9)
    NppConverter (4.5)
    NppExport (0.4)

**Comment by alankilborn** [comment]
An unfortunate decision was made to hardcode some functionality to Ctrl+x starting in version 8.6.
Thus, if you try to use Ctrl+x for anything other than "cut", you'll probably get less than desired results.
I believe some post-8.6 development has attempted to resolve this problem.

**Comment by Warren52** [comment]
I would rather Ctrl-X be free for shortcut usage but if it NEEDS to be hardcoded as some usage, then shouldn't the combination be also removed from the various shortcut selections to prevent inadvertent usage? Or a warning pop-up saying it is a reserved combination. Just a thought.

**Comment by alankilborn** [comment]
You seem to be agreeing with my "unfortunate decision" point.

**Comment by donho** [comment]
@Warren52 
The bug has been fixed in the master (https://github.com/notepad-plus-plus/notepad-plus-plus/commit/0978b2e29f21e7797f488e9e6d2e85763b25a406), the fix will be in the next release.
You can use the binary of current master in the meanwhile.
