### ISSUE TITLE
Column mode (or multi-caret?), I find it strange behaviour

### ISSUE THREAD

**Issue by Eqatrpfvvzzih** [notepad-plus-plus/notepad-plus-plus#14453]
### Description of the Issue
I select rectangular text area via Shift+Alt+Down, delete it, then press Down key, then Del key, then
I find it strange (and somewhat new. did it behave a couple of months ago? or changed?) that not only the
current line is deleted (which was the intent) but also the first character of many lines are deleted too.

### Steps to Reproduce the Issue

1.  New document (Ctrl+n)
2. Write 123456789 and Enter.
3. Duplicate that line 9 times.
4. Ctrl+Home, (Shift+Right)*4, (Shift+Alt+Down)*9, so select vertically the first 4 columns
5. Del, so delete the seletion
6. (Down)*7, so press 7 times the Down key
7. Del, so press the Del

### Expected Behavior

The "566789" lines remain. (I only wanted to delete an empty line (if present), after the "56789"-lines.)

56789
56789
56789
56789
56789
56789
56789
56789
56789
56789

### Actual Behavior

The last 3 lines of "56789"s changed to "6789". (Besides possibly deleting the actual empty line, if present.)

56789
56789
56789
56789
56789
56789
56789
6789
6789
6789

So it got stuck in some "multi-caret" (or column? or vertical?) mode?
What key ends that mode?
(And, it would be very nice too see where are my carets. If multi. And to see the actual "mode".)

### Debug Information

Notepad++ v8.6   (64-bit)
Build time : Nov 23 2023 - 16:58:44
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : "C:\Users\xxx\Documents\xxx.txt"
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 11 Home (64-bit)
OS Version : 23H2
OS Build : 22631.2715
Current ANSI codepage : 1252
Plugins : 
    mimeTools (2.9)
    NppConverter (4.5)
    NppExport (0.4)

**Comment by alankilborn** [comment]
>What key ends that mode?

<kbd>Esc</kbd>
