### ISSUE TITLE
not work in windows 11 26010

### ISSUE THREAD

**Issue by joesdu** [notepad-plus-plus/notepad-plus-plus#14459]
My OS version number is Windows11 26010, opening notepad++ will prompt no response, and I can't use Task Manager to end the process, this problem is found in the latest version of the system.I am using the latest notepad++ v8.6

**Comment by xomx** [comment]
>  Windows11 26010

[Announcing Windows 11 Insider Preview Build 26010 (Canary Channel)
](https://blogs.windows.com/windows-insider/2023/12/07/announcing-windows-11-insider-preview-build-26010-canary-channel/)

That's why MS uses the term "Canary" here, yours is evidently dead ;-)
