### ISSUE TITLE
BUG: Freezes by saving large XML files

### ISSUE THREAD

**Issue by BNociar** [notepad-plus-plus/notepad-plus-plus#14469]
### Description of the Issue
Freezes when saving larger XML files. See attached files.

### Steps to Reproduce the Issue
1. Load XML file
2. Change something
3. Save file

### Attached
* XML file in ZIP file
* Installed plugins
* Version

[Example.zip](https://github.com/notepad-plus-plus/notepad-plus-plus/files/13633108/Example.zip)
![Version](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/153496795/9910c5e4-d92c-4eb6-bc71-23184a3ca2d6)
![Plugins](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/153496795/81458e10-f5d3-4705-9137-854511926c23)

**Comment by xomx** [comment]
Cannot reproduce with your Example.xml.

Notepad++ v8.6   (64-bit)
Admin mode : OFF
Local Conf mode : ON
OS Name : Windows 10 Enterprise LTSC 2021 (64-bit)
OS Version : 21H2
OS Build : 19044.3693
Plugins : 
    HTMLTag (1.4.1)
    mimeTools (2.9)
    NppConverter (4.5)
    NppExport (0.4)
    XMLTools (3.1.1.13)

You can use for reporting the N++ menu > ? > Debug Info...
Try to update or temporarily disable your plugins.

**Comment by BNociar** [comment]
Notepad++ v8.6   (64-bit)
Build time : Nov 23 2023 - 16:58:44
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 10 Pro (64-bit)
OS Version : 22H2
OS Build : 19045.3693
Current ANSI codepage : 1252
Plugins : 
    HexEditor (0.9.12)
    HTMLTag (1.3.6)
    mimeTools (2.9)
    NppConverter (4.5)
    NppExport (0.4)
    XMLTools (3.1.1.12)

**Comment by BNociar** [comment]
Update plugins:
Plugins : 
    HTMLTag (1.4.1)
    XMLTools (3.1.1.13)

**Comment by BNociar** [comment]
@xomx THANKS !

**Comment by donho** [comment]
It seems due to XML tools plugin.
