### ISSUE TITLE
File position not remembered after program restart

### ISSUE THREAD

**Issue by rekmus** [notepad-plus-plus/notepad-plus-plus#14461]
### Description of the Issue

Windows 11. One instance, multi-view (two panes). There are a couple of files open in the left pane and a couple of files in the right pane. Some of them are the same. Generally they are couple of thousands lines long. The file I mostly work on is in the right pane. Every time I open the program I'm at the beginning of the file, regardless where I left when closing. The file on the left pane is positioned as left before closing.

### Expected Behavior

For years, before the last upgrade, Notepad++ remembered all the files' positions. I assume this is correct behaviour.

### Actual Behavior

Some of the files' positions are forgotten during program restart and scrolled to the top.

### Debug Information
Versions affected: 8.5.8 and 8.6, not sure about the earlier.
Preferences -> Backup -> Remember current session for next launch is ON

**Comment by donho** [comment]
It's indeed fixed by https://github.com/notepad-plus-plus/notepad-plus-plus/commit/a51e62c16dc45160afe6c7deb19096e98ad18372

**Comment by donho** [comment]
Hmm... only one case works with https://github.com/notepad-plus-plus/notepad-plus-plus/commit/a51e62c16dc45160afe6c7deb19096e98ad18372 : only 1 file opened in the 1st view and its clone opened in the 2nd view.

If there are any other file opened in the 1st or the 2nd view, it doesn't work. So https://github.com/notepad-plus-plus/notepad-plus-plus/commit/a51e62c16dc45160afe6c7deb19096e98ad18372 doesn't fix completely the issue. The issue will be reopened.
