### ISSUE TITLE
SQL Language stops color coding mid file with specific (valid sql) string is present

### ISSUE THREAD

**Issue by lofator** [notepad-plus-plus/notepad-plus-plus#14463]
### Description of the Issue
SQL Language stops color coding mid file when a following string combination is present: '\'

### Steps to Reproduce the Issue
1.  Load SQL file with '\' string
2. Set Language to SQL
3.  Observe highlighting to stop after '\'.

### Expected Behavior
Color code entire file
### Actual Behavior
Color coding stopped

### Debug Information
Notepad++ v8.5.7   (32-bit)
Build time : Sep  6 2023 - 23:07:35
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Command Line : "C:\Users\jrehacek\Documents\11_CLSMigration\ViewsExport.sql"
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 7 Professional (64-bit)
OS Build : 7601.0
Current ANSI codepage : 1252
Plugins : 
    DSpellCheck (1.4.6)
    mimeTools (2.9)
    NppConverter (4.5)
    NppExport (0.4)

![image](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/55462162/c420fa7e-a530-4b41-b0ce-734bff2dfc4d)

**Comment by rdipardo** [comment]
1. `Settings > Preferences > Language`
2. _Clear_ the "Treat backslash as escape character for SQL" checkbox

![lexer sql escape backslash](https://user-images.githubusercontent.com/59004801/258336108-70213c3e-6bfb-4099-a33b-4140b403d9be.png)

**Comment by acontestabile** [comment]
Would it be appropriate to deselect that option for SQL language by default?

**Comment by mpheath** [comment]
@acontestabile In the SQL lexer is off by default, though Notepad++ sets on by default. Might make sense with off by default as to the number of [closed issues](https://github.com/notepad-plus-plus/notepad-plus-plus/issues?q=is%3Aissue+backslash+escape) like yours about the same checkbox. It really depends on the SQL engine being used to weather backslash escapes are needed. MS TSQL lexer also styles your SELECT statement ok so also can be considered if suitable.
