### ISSUE TITLE
Notepad++ Open on windows 11 start up

### ISSUE THREAD

**Issue by tj15241** [notepad-plus-plus/notepad-plus-plus#14462]
### Description of the Issue
Notepad++ Open on windows start up
### Steps to Reproduce the Issue

1. 
2. 
3. 

### Actual Behavior
2 files are opened on starting computer
1: File Name detect_version.bat
   @echo off
    call Read_DUCE_fw_version_usi4.bat CS18Version.log -nos %1
    exit /b %errorlevel%

2. File Name: mydel.bat
     mrd . /s /q
### Debug Information

Notepad++ v8.5.8   (64-bit)
Build time : Oct 15 2023 - 21:43:56
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : "C:\Windows\TempInst\USBCDKFW3704_1_DETECT\mydel.bat"
Admin mode : ON
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 11 Pro (64-bit)
OS Version : 23H2
OS Build : 22631.2792
Current ANSI codepage : 1252
Plugins : 
    mimeTools (2.9)
    NppConverter (4.5)
    NppExport (0.4)

**Comment by xomx** [comment]
Either you have some specific startup setting active (check your Windows Settings > Apps > Startup) or the Windows Restart-Apps setting is in action.

From the v8.5.8+ Notepad++ supports the Windows OS Restart Manager (check Windows Settings > Accounts > Sign-in options > Restart Apps). If you want to have this setting globally ON but for the N++ OFF, put an empty config file  "noRestartAutomatically.xml" either to the N++ app-folder or to the "%APPDATA%\\Notepad++\\" one to disable this auto-restarting feature (or always close manually N++ before you logoff, restart or shutdown the Windows OS).

**Comment by tj15241** [comment]
I checked both places and don't have either one

**Comment by xomx** [comment]
> Command Line : "C:\Windows\TempInst\USBCDKFW3704_1_DETECT\mydel.bat"

This means that something has invoked the N++ as:
   notepad++.exe "C:\Windows\TempInst\USBCDKFW3704_1_DETECT\mydel.bat"

Google tells me that the USBCDKFW3704_1_DETECT has something to do with a Lenovo ThinInstaller...
