### ISSUE TITLE
HTML Tag error

### ISSUE THREAD

**Issue by StarSkiandHike** [notepad-plus-plus/notepad-plus-plus#14479]
### Description of the Issue
Update to 8.6 caused HTML Tag plugin to report that "The installed version of HTML Tag requires Notepad++ 8.3 or greater.  Plugin commands have been disabled."  If the HTMLTag folder is renamed, the error no longer appears.  The result was the same after direct update and when Notepad++ was completely uninstalled and reinstalled.

### Steps to Reproduce the Issue

1.  Simply starting Notepad++ 8.6.  The error message appears immediately on launch before Notepad++ starts.
2. 
3. 

### Expected Behavior

No pop-up error message

### Actual Behavior

Pop-up error message before the Notepad++ workspace appeared

### Debug Information

Notepad++ v8.6   (64-bit)
Build time : Nov 23 2023 - 16:58:44
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 11 Pro (64-bit)
OS Version : 23H2
OS Build : 22631.2861
Current ANSI codepage : 1252
Plugins : 
    ComparePlugin (2.0.2)
    HTMLTag (1.2.1)
    JsMapParser.NppPlugin (4.2)
    Merge files in one (1.2)
    mimeTools (2.9)
    NppConverter (4.5)
    NppExport (0.4)
    NPPJSONViewer (1.40)
    PlanetCNCNpp64 (3001.21.1123.1)
    PreviewHTML (1.3.2)
    PythonScript (2)
    XMLTools (3.1.1.12)

**Comment by alankilborn** [comment]
Plugin issues for plugins that do not ship with Notepad++ are not filed here, as plugins are independent entities.
Please close this issue and find the plugin site to report a plugin problem.

**Comment by StarSkiandHike** [comment]
My apologies. Since HTML Tag installed with Notepad++ 8.6, I assumed that it fell within the guidelines.  I will look for the plugin site.

**Comment by alankilborn** [comment]
> Since HTML Tag installed with Notepad++

??

To be clear, the only plugins that install WITH Notepad++, as of version 8.6, are:

* MIME Tools
* NppExport
* Converter

**Comment by StarSkiandHike** [comment]
Sorry (again).  Uninstall left the C:\Program Files\Notepad++\plugins folder intact, including long unused plugins.  Perhaps an uninstall option to remove the entire Notepad++ folder might be helpful.
________________________________

**Comment by rdipardo** [comment]
@StarSkiandHike
> ### Debug Information
> . . .
> HTMLTag (1.2.1)

Known issue: <https://community.notepad-plus-plus.org/post/90823>

Re-install Notepad++, select *Plugins* from the main menu, then *Plugins Admin*. Select HTML Tag (1.4.1) from the *Install* tab:

<img width="564" alt="npp-8 6 -pl-admin-install-tab" src="https://github.com/notepad-plus-plus/notepad-plus-plus/assets/59004801/a8f9c496-99ca-4d84-9cd8-d71ec4a3590c">
