### ISSUE TITLE
Detecting PowerToys Keyboard Manager key remaps

### ISSUE THREAD

**Issue by ndc** [notepad-plus-plus/notepad-plus-plus#14470]
PowerToys Keyboard Manager is a tool to remap keys in a keyboard. I use this tool to remap my laptop keys because I use 'home' and 'end' keys much more frequently than 'insert' and 'delete'. Notepad++ used to be able to detect the key remapping but the latest version doesn't. The 'insert' and 'delete' buttons become 'insert' and 'delete', ignoring the remap.

### Steps to Reproduce the Issue
1. Install PowerToys.
2. Using Keyboard Manager remap 'insert' to 'home', 'delete' to 'end'.
3. Press 'insert' and 'delete'

### Expected Behavior
The cursor goes to the beginning of the line then to the end of the line.

### Actual Behavior
Edit mode changes to overwrite and then deletes the character under the cursor.

### Debug Information
Notepad++ v8.6   (64-bit)
Build time : Nov 23 2023 - 16:58:44
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : "C:\mysolutions\mysolution.sln" 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 11 Enterprise (64-bit)
OS Version : 22H2
OS Build : 22621.2715
Current ANSI codepage : 1252
Plugins : 
    mimeTools (2.9)
    NppConverter (4.5)
    NppExport (0.4)

**Comment by alankilborn** [comment]
Probably an effect from the implementation from https://github.com/notepad-plus-plus/notepad-plus-plus/issues/14296

**Comment by donho** [comment]
@ndc 
Could you reproduce it in v8.5.8 ?

**Comment by ndc** [comment]
@donho not reproducible in 8.5.8. My remaps still work in 8.5.8.

**Comment by ndc** [comment]
BTW congrats on the 20th anniversary of notepad++! 👍

**Comment by donho** [comment]
@ndc 
Do you use Shift-DEL? Is the Shift-DEL doesn't work for your assigned action?

**Comment by ndc** [comment]
@donho actually both used to work, the behavior is just like pressing END and SHIFT-END (the key that I assign to DEL).
For example pressing DEL will go to the end of the line, while pressing SHIFT-DEL will select the characters between the current cursor location to the end of the line.

**Comment by donho** [comment]
"disableHardCodedShiftDelete.xml" (renamed to "disableLineCopyCutDelete.xml") won't be used anymore.
This issue is reopened.
