### ISSUE TITLE
Line count is not displayed properly for larger files

### ISSUE THREAD

**Issue by garydgregory** [notepad-plus-plus/notepad-plus-plus#1447]
See http://ibin.co/2VssG5OabhA4

**Comment by vlakoff** [comment]
To clarify: the issue is in the status bar, where the number of lines doesn't fit.

Looks like it's due to the DPI scaling.

**Comment by sky5walk** [comment]
How many times must I resubmit this BUG report?! It is still broken as of v6.9.2.
![bug_notepad v692_statusbar](https://cloud.githubusercontent.com/assets/13093122/17600925/b2ae874c-5fd3-11e6-92da-5c2e52337b3b.PNG)
[BUG_Notepad++v692_statusbar.txt](https://github.com/notepad-plus-plus/notepad-plus-plus/files/413972/BUG_Notepad.v692_statusbar.txt)
