### ISSUE TITLE
Alternate row colors in the background

### ISSUE THREAD

**Issue by Shade-Of-Fear** [notepad-plus-plus/notepad-plus-plus#1448]
Hello,
This is a feature request.
Would it be possible to implement alternating row colors in the background? I think this will be useful for system administrators who are using notepad++ to examine any kind of log files.

I'm attaching an example of this functionality in excel:
![shade-alternate-rows-result](https://cloud.githubusercontent.com/assets/17080472/12841948/44a1f4ce-cbf8-11e5-8c14-9ca65661b5e0.png)

**Comment by alicanyildiz** [comment]
That would be good and I want to attach a footnote if this going to be applied, it should be like in the CSS **:nth-child(N) ** pseudo class form not just even or odd, this would be more useful.

**Comment by marcortw** [comment]
+1

**Comment by john295fsu** [comment]
+1, please

**Comment by robinhugy** [comment]
+1 :$

**Comment by 3NQfgBiMnL** [comment]
+1

**Comment by nassausky** [comment]
+1, that would be epic 🥇

**Comment by Mitsjol** [comment]
+1

**Comment by Roy-N** [comment]
+1 pls and thanks

**Comment by TorinoSM** [comment]
+1

**Comment by sasumner** [comment]
Use the LuaScript plugin and the sample script that colors alternating lines differently:  https://dail8859.github.io/LuaScript/examples/stylecsv.lua.html

**Comment by MetaChuh** [comment]
please install the luascript plugin and the script provided above.

implementing same feature directly at the notepad++ core would require modifications to the scintilla component, which is an external project.

if you have any questions on how to install luascript and/or the alternating line script, please feel free to visit us at the notepad++ community (link at the bottom) to get support on all things that are not directly related to the notepad++ code parts.

thank you for your support and best regards.

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
(no extra account is needed, just use your github account to sign in)
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)
