### ISSUE TITLE
Syntax highlighting for user extension stopped working in style configurator 8.6

### ISSUE THREAD

**Issue by PRXPHET** [notepad-plus-plus/notepad-plus-plus#14499]
I am setting ".script" user extension in style configurator so when I open any ".script" file my syntax highlighting automatically setting to "lua" type. In 8.6 it stopped working.

### Steps to Reproduce the Issue

1. Open style configurator.
2. Set user extension for any language (i.e. .script for lua)
3. Open any file with this user extension.

### Expected Behavior
Syntax highlighting will automatically set to lua.

### Actual Behavior
Syntax highlighting not changing, it's just a common text.

**Comment by Graff46** [comment]
Faced with the same error

**Comment by xomx** [comment]
Fixed by https://github.com/notepad-plus-plus/notepad-plus-plus/commit/e08c5471678220ee6694caa145abccf35321a2e0 .

You can try e.g. the x64 commit artifact: https://github.com/notepad-plus-plus/notepad-plus-plus/actions/runs/7074248254/artifacts/1088589910
