### ISSUE TITLE
Virus Detection

### ISSUE THREAD

**Issue by crogonint** [notepad-plus-plus/notepad-plus-plus#14496]
### Steps to Reproduce the Issue

1.  Install Bitdefender Antivirus Free
2. Fresh install of Notepad++ current
3. Install plug-ins.

### Expected Behavior
No virus reported

### Actual Behavior
Bitdefender Antivirus reports:

The file C:\Program Files\Notepad++\plugins\JSMinNPP\JSMinNPP.dll is infected with Gen:Variant.Tedy.504791 and was moved to quarantine. It is recommended that you run a System Scan to make sure your system is clean.

### Debug Information
Notepad++ v8.6   (64-bit)
Build time : Nov 23 2023 - 16:58:44
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 11 Pro (64-bit)
OS Version : 22H2
OS Build : 22621.2861
Current ANSI codepage : 1252
Plugins : 
    CodeAlignmentNpp (14.1.107)
    Comment Wrap (1.0.0.7)
    ComparePlugin (2.0.2)
    ComparePlus (1.1)
    DSpellCheck (1.5)
    HexEditor (0.9.12)
    HTMLTag (1.4.1)
    IndentByFold (0.7.3)
    JsMapParser.NppPlugin (4.2)
    LanguageHelp (1.7.5)
    Linter (0.1)
    MenuIcons (2.0.5)
    mimeTools (2.9)
    NavigateTo (2.6.4)
    Npp-Highlighter (1.0.0.1)
    NppConverter (4.5)
    NppExport (0.4)
    NppFTP (0.29.12)
    NppSnippets (1.7.1)
    NppXmlTreeviewPlugin (2)
    PreviewHTML (1.3.2)
    Python Indent (1.0.0.5)
    PythonScript (2)
    TakeNotes (1.2.6)
    XMLTools (3.1.1.13)

**Comment by alankilborn** [comment]
Hmm, well `JSMinNPP.dll` has no relationship to Notepad++ from a development perspective, so I think you're reporting this in the wrong place.

**Comment by crogonint** [comment]
They've moved where the plug-ins are stored (online) at least 4 times. I have no idea who's in charge of them.. but I bet the devs here do. :)

**Comment by rdipardo** [comment]
> They've moved where the plug-ins are stored (online) at least 4 times. I have no idea who's in charge of them...

No need to bother. Someone's already done it: https://github.com/sunjw/jstoolnpp/issues/147

**Comment by alankilborn** [comment]
>They've moved where the plug-ins are stored (online) at least 4 times. I have no idea who's in charge of them.. but I bet the devs here do.

Why would you think the devs here care?
Plugins are NOT sanctioned by Notepad++ itself.

**Comment by donho** [comment]
> Why would you think the devs here care?
Plugins are NOT sanctioned by Notepad++ itself.

If it's not false positive, then we have do somethings in Notepad++.
