### ISSUE TITLE
Feature request; Add change control to text documents.

### ISSUE THREAD

**Issue by kylemanel** [notepad-plus-plus/notepad-plus-plus#14491]
### Description of the Issue
Having utilized GIT myself, I have often felt it would be valuable to have this capacity within a simple text file editor, enabling one to utilize a file history with time stamps and modification notes
~ The issue with many similar systems is that they utilize a complex file/folder structure, NOT a singular file to provide change control; I'm thinking a repo per file, such that each file can be distinct, and modified isolated from a repository, as well as moved and utilized quickly/easily.

### Steps to produce this

1. Open/create a text file
2. Utilize an app gui to provide a clickable interface, enabling one to provide file modifications, as well as associated notes, such that the user could easily identify time for changes in documents, as well as track modifications to said file.
3. This would be very similar to GIT, though it would be provided for the purposes of a text file;
I am a Systems Administrator, for instance, and I am constantly creating configuration files, with accompanying notes, HOWEVER these need to be then stored and reviewed with GIT, which becomes frustrating, as they are merely text documents, and don't require that form of additional complexity, as I only need to provide a way to review notes for all changes, as well as the changes themselves.
~ A text file seems like an easy place to produce this, as it is small, and relatively uncomplex, such that adding this form of meta data within the file would be non-complex.

~ In terms of notepad++, I see this as a feature request because it would require significant additional logic, but it could provide exceptional value to your platform, enabling notepad++ to be THE file editor for the purposes of configuration management.

### Expected Behavior
I want to be able to make and then review alterations to text documents, such that I can have the completed file, as well as a history of all changes that occurred within it, along with accompanying times.

This is likely to require a new file-format, so potentially .git, or .chng, etc. could be used.

**Comment by alankilborn** [comment]
IMO it sounds like a great idea for a plugin; not so great as a native N++ feature.

**Comment by alankilborn** [comment]
Also, there's already the Verbose Backup feature which archives a copy of the file upon every save.  Probably some scripting could be written that could call a compare plugin/utility to "walk back" through these files sequentially, showing the differences between saves.

Every-save might be overkill, though.  Maybe there's some sort of "checkpoint" command that the user invokes, to save the file with a special stamp, and the compare only walks back through the checkpointed (stamped) versions.

**Comment by donho** [comment]
Agree with @alankilborn: the requested ability should be rather in a plugin than in the text/code editor.
