### ISSUE TITLE
Unsupported Unicode Character: Vertical Ellipse (U+22EE)

### ISSUE THREAD

**Issue by coldReactive** [notepad-plus-plus/notepad-plus-plus#14495]
### Description of the Issue

The Unicode Character for Vertical Ellipse (U+22EE) is unsupported. The ellipse is allowed to be in monospaced formatted text fields such as the code blocks in Discord and even in Microsoft's own Notepad Program (see image below.)

![image](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/1313673/48ef4c88-1083-4df5-938c-60e0233ab493)

### Steps to Reproduce the Issue

1. Attempt to paste in the Vertical Ellipse Unicode Character. ( ⋮ )

### Expected Behavior

The Unicode Character is supported.

### Actual Behavior

The Vertical Ellipse Unicode Character ( ⋮ ) is Unsupported and shows as a Unicode Code Box.

![image](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/1313673/0aa8d549-d40f-4f17-a93f-2ea9003c0e1a)

### Debug Information
Notepad++ v8.5.7   (64-bit)
Build time : Sep  6 2023 - 23:13:49
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : "D:\Documents\Test.txt"
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 11 Home (64-bit)
OS Version : 23H2
OS Build : 22631.2861
Current ANSI codepage : 1252
Plugins : 
    mimeTools (2.9)
    NppConverter (4.5)
    NppExport (0.4)
    NPPJSONViewer (1.40)

**Comment by alankilborn** [comment]
Probably solved by:

![image](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/77065706/86bc6d30-e089-4ed5-95d1-87cf2e523db4)

**Comment by coldReactive** [comment]
Closing this. Should be left on GitHub just in case someone else tries to search for it.
