### ISSUE TITLE
[Feature Request] v8.6 "Multi-Select" barely explained

### ISSUE THREAD

**Issue by zipacna** [notepad-plus-plus/notepad-plus-plus#14493]
### Description of the Issue
With Notepad++ v8.6 the IMO missing feature of (multi)selecting occurences of text across disconnected chunks within a file (think the magical 8.6 animation) has been added, but with [much confusion](https://community.notepad-plus-plus.org/topic/25207/npp-8-6-multi-edit-preference-not-shown/9) about the older Multi-Edit being a completely different point-and-click adventure.

### Steps to Reproduce the Issue
Install Notepad++ v8.6; read change.log; think VS Code CTRL+D or IntelliJ Alt+J now works with Notepad++ under some Shortcut.
1. Well yes, but actually no.
2. Suprised Pikachu Face
3. several hours later

### Expected Behavior
Proper Feature USAGE Explanation (alongside the much reported animation). Directly mapped shortcut for Multi-Select.

### Actual Behavior
GLHF

### Suggestion
Maybe map CTRL+E to the analog of VS Code or IntelliJ (as partially discussed in the thread of the quote). As IMO Copying with CTRL+C, Duplicating Lines with CTRL+D and Selecting Occurences with CTRL+E is part of the very basis of text editing, alongside cut/paste CTRL+X/CTRL+V and undo/redo CTRL+Z/CTRL+Y (from my German Perspective may need to consider other non-english languages regarding the shortcuts). CTRL+E for Multi-Select may even make search/replace CTRL+F/CTRL+H obsolete.

### Context
Spend a solid hour trying to find how to reproduce the animation (that is shared everywhere but without the info on how to use it). And another hour putting this issue together. Only the old "Ctrl+Mouse Click" and not the new unmapped 
![image](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/4885295/b574b322-ec7c-49a6-a498-04322f66339f)

In the German Translation the Prefix "Multi-Select Next" is hidden and without the hint of "check entry 104" wouldn't even have guessed this is THE Feature Notepad++ was missing from the beginning. (will stay with english for now)

German Translation
![image](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/4885295/cbacbf3a-728b-4286-bb15-e9821de12746)

# THE ORIGINAL OF THE QUOTE NEEDS TO BE THE NEW LANDING SITE FOR THE v8.6!

The [quote](https://github.com/notepad-plus-plus/notepad-plus-plus/issues/8203#issuecomment-1852894767) that needs to be in every news article and docs about Notepad++ v8.6; Considering its complexity, this may need some higher Priority (to be more accessable).

> To reproduce the demonstration you first have to set a shortcut to the new function:
> 
> * In Notepad++ v8.6 go to menu "_Settings / Shortcut mapping ..._"
> * Go to tab "_Main menu_"
> * Find the command "_Multi-select Next: Match Case Only_" (line 104)
> * Double click to the empty field in column "_Shortcut_"
> * Choose **Ctrl + D** as shortcut
> * When the shortcut becomes red and it says "conflict found", go to that entry (e.g. SCI_LINEDUPLICATE in "Scintilla Commands") and set the other shortcut to "none" in order to disable it.
> * There are also other useful commands for multi editing. They were not used in the animation, but for completeness I recommend the following list of shortcut mappings, so that you get used to shortcuts that are partially the same in common projects (e.g. Visual Studio Code):
>   
>   * `Multi-select Next: Match Case Only`: **Ctrl + D**
>   * `Multi-select Next: Match Case and Whole Word`: **Ctrl + Shift + D**
>   * `Undo the Latest Added Multi-Select`: **Ctrl + U**
>   * `Skip Current & Go to Next Multi-select`: **Ctrl + E**
>   * `Multi-select All: Match Case Only`: **Ctrl + L**
>   * `Multi-select All: Match Whole Word Only`: **Ctrl + Shift + L**
> 
> In the animation the only new shortcut that was used is **Ctrl + D**. All other commands where standard shortcuts from any other Windows editor.
> 
> To start with the example, copy this line into Notepad++: `var1, var2, object1, object2, object3, flag1, flag2`
> 
> Now these are the first steps I did in the animation:
> 
> * Add another comma at the end
> * Select the first comma
> * Press **Ctrl + D** seven times. This is the magic command that does the whole trick. Try it and you will love it!
> * Now you can do everything you normally do with a sinlge selection and a single cursor: **Backspace**, **Backspace**, **Enter**, ... Even Copy and Paste is working in the expected way.
> * Also very useful standard shortcuts for multi editing are **Ctrl + Left**, **Ctrl + Right**, **End** and **Home** etc. to navigate the cursors inside lines with variable names of different length.
> * **Ctrl + D** was also used in the animation for the selection of lines with "obj."  and for the renaming of "object" to "data".
> 
> Here is again the animation: ![](https://raw.githubusercontent.com/bitagoras/PyPadPlusPlus/master/demo/multiedit.gif) [ ![multiedit.gif](https://raw.githubusercontent.com/bitagoras/PyPadPlusPlus/master/demo/multiedit.gif) ](https://raw.githubusercontent.com/bitagoras/PyPadPlusPlus/master/demo/multiedit.gif) [ ](https://raw.githubusercontent.com/bitagoras/PyPadPlusPlus/master/demo/multiedit.gif)

Obligatory Relevant XKCD: https://xkcd.com/1172/

Bonus GitHub Visual Bug: 
![image](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/4885295/f5532806-1166-4167-a303-23a6819a3dfd)

**Comment by donho** [comment]
https://github.com/notepad-plus-plus/notepad-plus-plus/issues/14509
