### ISSUE TITLE
Imported types in Ada cause Fuction List to fail to list functions that use them

### ISSUE THREAD

**Issue by ronww** [notepad-plus-plus/notepad-plus-plus#14498]
### Description of the Issue
When editing an Ada source file, the "Function List" panel only shows the names of subroutines that are declared with "procedure"

### Steps to Reproduce the Issue
1. Load an Ada source file that has both procedures and functions (see screen shot in Jan 18th comment, below)
2. Under View, enable the Function List
3. Observe that only subroutines declared with "procedure" are shown

### Expected Behavior
subroutines declared with either "function" or "procedure" should be shown

### Actual Behavior
only subroutines declared with "procedure" are shown

### Debug Information
Notepad++ v8.5.3   (64-bit)
Build time : May 15 2023 - 06:09:36
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line :
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 10 Enterprise (64-bit)
OS Version : 21H2
OS Build : 19044.3693
Current ANSI codepage : 1252
Plugins :
    mimeTools (2.9)
    NppConverter (4.5)
    NppExport (0.4)

See Jan 18th comment, below

**Comment by rdipardo** [comment]
I don't know what version of the [ADA standard](https://www.adaic.org/ada-resources/standards/) you are writing for, but a literal range is typically not allowed in a paramter list. Try something like this instead:


    subtype Color is Integer range 0 .. 255;
    
    procedure Set_Saturation ( Value : Color ) is
    begin
    -- ...
    end Set_Saturation;
    
    function Get_Saturation return Color is
    begin
    -- ...
    end Get_Saturation;

<img  alt="gh-14498" src="https://github.com/notepad-plus-plus/notepad-plus-plus/assets/59004801/265f2057-eb4a-453e-a003-bad36b427970">

**Comment by ronww** [comment]
I was translating my employer's internally defined types to provide examples.

What I can say is that only subroutines declared with "procedure" where shown in the Function List. Those declared with "function" were not.

**Comment by ronww** [comment]
I have prepared a sanitized sample showing where functions were excluded.
Appears that functions using type definitions imported from another module fail to appear in the function list, although procedures using imported type definitions are listed.
See attached screen shot.
![NP++FuncList](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/62124/ae058205-1a67-4138-8488-a72fb356c288)

**Comment by ronww** [comment]
Also, the following function was not listed:

`function Int32toInt8TwosComplement (value : Vt.Int32) return Vt.Int8 is`
`begin`
`    -- body`
`end Int32toInt8TwosComplement; `
