### ISSUE TITLE
Escape key does not always exit multiline mode

### ISSUE THREAD

**Issue by theppnex** [notepad-plus-plus/notepad-plus-plus#14492]
### Description of the Issue
Recent changes to multi-line edit mode (Alt-Shift) are a bit frustrating for those who use this feature frequently.  With the recent changes one must hit escape to exit multi-line edit mode, however depending on the edit performed in multiline it does not seem to work and one must fiddle with the cursor position and hit the escape key more than once to switch back out of multiline mode.
In general: Would love to have a settings / preference option to revert multiline mode back to the legacy behavior as I find the new design a bit frustrating myself.

### Steps to Reproduce the Issue
1. Set the curser at the beginning of a line
2. enter multiline mode (shift-alt)
3. use the up/down arrow keys to expand influence area to 3-4 lines
4. Make no changes but decide you need to do something else first so hit escape to exit multiline mode

### Expected Behavior
Program switches out of multiline mode

### Actual Behavior
Multiline mode is still active

### Debug Information
Notepad++ v8.6   (64-bit)
Build time : Nov 23 2023 - 16:58:44
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : 6ECA50~1
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 10 Enterprise (64-bit)
OS Version : 22H2
OS Build : 19045.3208
Current ANSI codepage : 1252
Plugins : 
    HexEditor (0.9.12)
    mimeTools (2.9)
    NppConverter (4.5)
    NppExport (0.4)
    PlanetCNCNpp64 (3001.21.1123.1)
    RegexTrainer (1)

**Comment by rdipardo** [comment]
Already reported as #14464, and supposedly fixed in aef0438.

> 2. enter multiline mode (shift-alt)

To be precise, <kbd>SHIFT</kbd>+<kbd>ALT</kbd> creates a *rectangular* selection, as known as "column mode". What's new in v8.6 is the permanent availability of multiple *stream* selections.

**Comment by donho** [comment]
https://github.com/notepad-plus-plus/notepad-plus-plus/commit/aef04381800c920264dc475483f5013572dfea5a
