### ISSUE TITLE
Selection duplicate Shortcut not working

### ISSUE THREAD

**Issue by hinki-x** [notepad-plus-plus/notepad-plus-plus#14502]
### Description of the Issue

The selection duplicate Shortcut "CTRL+D" does nothing and is also not changeable.

### Steps to Reproduce the Issue

1. select some Text
2. Press "CTRL+D"
3. See that nothing happens

### Expected Behavior

When using "CTRL+D" i would expect (since V.8.6) a selection duplicate.

### Actual Behavior

Since fixed [#5298](https://github.com/notepad-plus-plus/notepad-plus-plus/issues/5298) The Shortcut "CTRL+D" doesn't work in the expected way. Also the Shortcut is not changeable in the shortcut mapper.

Since the latest changes the German translation is not correct anymore. "Zeile bzw. Markierung duplizieren" would be correct for <V8.6 (means "Line or selection duplicate"). The English version only says "Duplicate Current Line" (GER: "Zeilde duplizieren"). 
Since the separation between SCI_SELECTIONDUPLICATE and SCI_LINEDUPLICATE the German naming isn't correct anymore.
 

### Debug Information

Notepad++ v8.6   (64-bit)
Build time : Nov 23 2023 - 16:58:44
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 10 Enterprise (64-bit)
OS Version : 20H2
OS Build : 19042.2965
Current ANSI codepage : 1252
Plugins : 
    ComparePlugin (2.0.2)
    mimeTools (2.9)
    NppConverter (4.5)
    NppExport (0.4)

**Comment by alankilborn** [comment]
>The selection duplicate Shortcut "CTRL+D" does nothing

Cannot replicate.  On my system making a selection and pressing Ctrl+d duplicates the selected text.

---

>and is also not changeable.

Cannot replicate; changeable on my system:

![image](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/77065706/bcef9a6a-7169-4c14-aaf9-6614d5b96b40)

**Comment by hinki-x** [comment]
Sorry, i assumed pressing "OK" includes an "Apply". Therefore changing the Shortcut is possible.
Removing only per select "None" and apply, would expect the Remove Button would do this.

Did some further investigations as the Problem was on several different machines and found out that the problem is Webex.
They now use CTRL+D as a global HotKey. When disabling the "global", than everything works fine so far.

**Comment by alankilborn** [comment]
>i assumed pressing "OK" includes an "Apply". Therefore changing the Shortcut is possible.
Removing only per select "None" and apply, would expect the Remove Button would do this.

I have put in other issues on the strangeness in this regard.

---

It seems as though you can now close this issue.
