### ISSUE TITLE
v.8.6 64bit: "Replace All in All Opened Documents" does double replacement on document and its clone

### ISSUE THREAD

**Issue by HolterPhylo** [notepad-plus-plus/notepad-plus-plus#14505]
### Description of the Issue
"Replace All in All Opened Documents" does double replacement on document and its clone when a 2nd document is involved.

### Steps to Reproduce the Issue
1.  create 2 documents: doc_1.lua and doc_3.lua
2.  open doc_1.lua and doc_3.lua in npp
3.  select doc_1.lua and 'Clone to other view'
4.  write in doc_1.lua some code/text: 
> function test_1()
	print("test_1")
end
function test()
	print("test")
end
5. write in doc_3.lua:
> function test()
	print("test")
end
6. still in doc_3.lua, do a 'Replace' 
==> 'Find what:' "test(" 
==> 'Replace with:' "LH.test("
Click 'Replace All in All Opened Documents' and answer 'OK' to the question 'Are you sure...'
7. Now, doc_3.lua is
> function LH.test()
	print("test")
end
8. Looking at doc_1.lua test() function name, notice that it is now 'LH.LH.test()' in both the original and the clone
> function LH.LH.test()
	print("test")
end

### Expected Behavior
doc_1.lua test() function name should only be 'LH.test()' in both the original and the clone

### Actual Behavior
doc_1.lua test() function name is wrongly named 'LH.LH.test()' in both the original and the clone

### Debug Information
Notepad++ v8.6   (64-bit)
Build time : Nov 23 2023 - 16:58:44
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : "G:\NPP test\doc_1.txt" 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 10 Pro (64-bit)
OS Version : 22H2
OS Build : 19045.3803
Current ANSI codepage : 1252
Plugins : 
    BracketsCheck (1.2.2)
    Comment Wrap (1.0.0.5)
    ComparePlus (1.1)
    EnhanceAnyLexer (1.1.3)
    HTMLTag (1.3.7)
    LocationNavigate (0.4.8.1)
    LuaScript (0.12)
    MarkdownViewerPlusPlus (0.8.2)
    Merge files in one (1.2)
    mimeTools (2.9)
    NavigateTo (2.4.1)
    NppConverter (4.5)
    NppExport (0.4)
    NPPJSONViewer (2.0.5)
    NppTextViz (0.4.2)
    NppToolBucket (1.10.6622.41516)
    NppXmlTreeviewPlugin (2)
    PreviewHTML (1.3.2)
    Python Indent (1.0.0.4)
    PythonScript (2)
    RegexTrainer (1)
    SessionMgr (1.4.4)
    XBrackets (1.3.1)
    zoomdisabler_x64 (1.2)
    _CustomizeToolbar (5.3)

Before replacement:
![image](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/3037251/f92f4c27-afcd-45d4-a291-e2db814582bc)

After replacement:
![image](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/3037251/5bbe9c4a-52ea-43f3-a0e9-beb78b910103)

Showing doc_1.lua original and clone:
![image](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/3037251/12bc2f11-81f6-4dce-a29d-f3d821047d67)

**Comment by alankilborn** [comment]
I can replicate this bug.

**Comment by alankilborn** [comment]
@donho Sorry, I didn't see you self-assigned to this before I worked on it...

**Comment by donho** [comment]
@alankilborn 
No problem :)
