### ISSUE TITLE
Some keyboard accelerators in Incremental Search don't work

### ISSUE THREAD

**Issue by alankilborn** [notepad-plus-plus/notepad-plus-plus#14503]
### Steps to Reproduce the Issue

1. Create some text `tttttt` in a new Notepad++ tab
2. Invoke _Incremental Search_ with Ctrl+Alt+i
3. Enter `t` in the `Find` edit box; observe that one of the `t` in the edit zone is selected
4. Press _Find Next_ keyboard shortcut (F3) (or _Find Previous_ keyboard shortcut (Shift+F3))

### Expected Behavior
The next (or previous) occurrence of `t` should be selected.

### Actual Behavior
F3 (or Shift+F3) does nothing.

### Analysis
The _Incremental Search_ accelerator table is created here:
https://github.com/notepad-plus-plus/notepad-plus-plus/blob/4e6bbbc17ffbf765d095b63414d534066fe4c877/PowerEditor/src/WinControls/shortcut/shortcut.cpp#L625
and is soon after and wrongly deleted here:
https://github.com/notepad-plus-plus/notepad-plus-plus/blob/4e6bbbc17ffbf765d095b63414d534066fe4c877/PowerEditor/src/WinControls/shortcut/shortcut.cpp#L628-L629

### Debug Information
Notepad++ v8.6   (64-bit)
Build time : Nov 23 2023 - 16:58:44
Path : C:\NotepadPlusPlus\Misc\_NoBackup\Releases\npp.8.6\npp.8.6.portable.x64\notepad++.exe
Command Line : -titleAdd="8.6 64-bit" -multiInst
Admin mode : OFF
Local Conf mode : ON
Cloud Config : OFF
OS Name : Windows 11 Pro (64-bit)
OS Version : 22H2
OS Build : 22621.2715
Current ANSI codepage : 1252
Plugins : 
    mimeTools (2.9)
    NppConverter (4.5)
    NppExport (0.4)
    PythonScript (3.0.16)

**Comment by donho** [comment]
**Find Next keyboard shortcut (F3)** and **Find Previous keyboard shortcut (Shift+F3)** do work only on `Find what` field of Find/Replace dialog, but not on `Find` field of Incremental Search Bar. See:
https://github.com/notepad-plus-plus/notepad-plus-plus/blob/master/PowerEditor/src/NppCommands.cpp#L1354
