### ISSUE TITLE
[Proposal] Prompt before opening file exceeding a given size

### ISSUE THREAD

**Issue by vlakoff** [notepad-plus-plus/notepad-plus-plus#1450]
If by mistake I'm opening e.g. a movie file with Notepad++, the application hangs (without surprise), and I have to kill it.

I might be helpful to add a setting "☑ Prompt before opening file exceeding [100] MB", the size being of course configurable.

**Comment by rushikesh90** [comment]
Hi I am getting following notif when trying to open the file.
![image](https://cloud.githubusercontent.com/assets/6714143/12896512/6808bef2-cec8-11e5-8b5b-d592ae6c269a.png)

**Comment by vlakoff** [comment]
This message is shown by [FileManager::loadFileData](https://github.com/notepad-plus-plus/notepad-plus-plus/blob/fb189fa247324cb84b1b4de1ea174be29cd98680/PowerEditor/src/ScitillaComponent/Buffer.cpp#L1332), there are 2 occurrences of it in the code.

It appears when:
* File size exceeds the 32-bit limit
* Some exception occurred

I'm getting this message too, though the file is less than 2 GB. So I deduce I'm hitting an exception.

If the computer is idle, the message doesn't appear instantaneously, but quite fast. But if the computer is under load, it can hangs for much time.

**Comment by rushikesh90** [comment]
I found this note .  //TODO: should filter correctly for other exceptions; the old filter(GetExceptionCode(), GetExceptionInformation()) was only catching access violations

Currently for all the errors the same message is shown ,i.e File is too big to be opened by Notepad++

**Comment by dail8859** [comment]
Keep in mind that just because the file is <2GB, Scintilla also has to allocate a lot of other memory for styling, folding, lexing, etc. But I do agree that more specific error messages would be appropriate in case it isn't actually hitting a memory limit.

**Comment by rushikesh90** [comment]
Also as you say just because address space limit is 2GB , it shouldn't be max file limit. So I think we can also avoid bufferSizeRequested > INT_MAX while opening the file. Instead we can define MAX_FILE_SIZE and that too only at one place in the code.

**Comment by dail8859** [comment]
Unfortunately that probably isn't a good solution since some file types (like XML, HTML) use a lot more memory by Scintilla than say a plain text file.

**Comment by Gabr-F** [comment]
Best of all would be that the documents be loaded asynchronously, of course, and that you be able to stop their loading at any time

**Comment by ziegel** [comment]
At the very least a helpful error message would be appreciated. Saying a file is too big, when it's about memory allocation, is not helpful at all. I wonder if flushing big files to disk when not having focus should be a selectable option Settings > Preferences. Something like "Flush big files onto disk unless it has focus."

**Comment by donho** [comment]
"exceeding size" is an ambiguous term for different environments. Some PC have less memory and some have more so their capacities are different.
This is a good idea, but unpracticable (as communism) IMO.
