### ISSUE TITLE
The caret colour of multiselected lines is dark grey

### ISSUE THREAD

**Issue by PJBoy** [notepad-plus-plus/notepad-plus-plus#14515]
### Description of the issue
When selecting multiple lines with alt+down or ctrl+click, the carets other than the most recently placed one are all dark grey, which is almost invisible on dark backgrounds (and visible, but still miscoloured on light backgrounds)

### Steps to reproduce the issue / actual behavior
One can sketch out some simple text columns and activate multi-line selection with alt+down, e.g.
![image](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/9425558/aeb0d81b-cedd-472b-8382-ae969d9fe124)

### Expected behavior
This wasn't the behaviour before, this was introduced in a recent update. It used to be that all carets used the same colour (defined by the style configuration)

### Debug information
Notepad++ v8.6   (32-bit)
Build time : Nov 23 2023 - 16:56:22
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Command Line : 
Admin mode : ON
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 10 Home (64-bit)
OS Version : 21H2
OS Build : 19044.3086
Current ANSI codepage : 1252
Plugins : 
    AnalysePlugin (1.13.49)
    BetterMultiSelection (1.5)
    ComparePlugin (2.0.2)
    DSpellCheck (1.5)
    mimeTools (2.9)
    NppConverter (4.5)
    NppDocShare (0.1)
    NppExport (0.4)
    NppFTP (0.29.9)
    NppGraphViz (1.0.0.4)
    NppSmartSense (0.3)
    NppTextFX (1.4.1)
    PreviewHTML (1.3.2)
    SmRamLookup (4.1)
    Tidy2 (0.2)

My apologies if this is a Scintilla issue and I should redirect my concern over there, I haven't quite figured out who's responsible for what yet.

Thanks

**Comment by alankilborn** [comment]
Perhaps relevant: https://community.notepad-plus-plus.org/topic/25226

**Comment by PJBoy** [comment]
Thanks for the link :)

Curiously, my `.\themes\Deep Black.xml` does have `<WidgetStyle name="Multi-edit carets color" styleID="0" fgColor="FFFFFF" />`, but of course it has no effect and does not appear in my Style Configurator
![image](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/9425558/971d3fc1-6ef9-458a-8dce-8128688c4538)

**Comment by PJBoy** [comment]
Ah, mystery solved. My actual theme is `%APPDATA%\Notepad++\themes\Deep Black.xml`, which appears to not have been updated in a very long time. Thanks again for the link, you're the best
