### ISSUE TITLE
Textfiles 'lost' on an external hard drive when USB knocked out

### ISSUE THREAD

**Issue by soi521** [notepad-plus-plus/notepad-plus-plus#1451]
This is half a bug report, half a feature request.

I use Notepad++ extensively and have several textfiles open all the time that I edit over long periods of time (see attached), for example fragments of code that I'm still 'working on' but sometimes I haven't touched for months. It's useful for me just to keep them all open in Notepad++ so that I can use the search-through-all-open-files feature in case I need a bit of code from here or there.

I've recently changed job and now instead of having my files all on D Drive I have to use an external hard drive (I'm in a research institute which requires this for security reasons) so essentially a lot of those textfiles have now been moved to EHD. This has brought up a problem: the EHD is attached through a standard USB port but every once in a while the thing gets knocked out sometimes without my even noticing.

Whenever the USB attachment gets knocked out, next time I open Notepad++ it tells me that half my textfiles are no longer there and would I like to keep this nonexistent file in the editor? Notepad++ diligently asks me to confirm every single file and either closes them or turns them red and I can't get out of it without confirming every one even if I reattach the EHD. If I keep all of them in the editor then the texfiles on the EHD all turn red (indicating changes to be saved). If I then find and reattach the EHD then Notepad says these have been modified by another program and offers me to reload them and this can turn them all back to blue so fine, but if I had actually modified any of those files before knocking out the USB cable then those changes are all lost and one time I lost a lot of code changes that way.

Apologies for all the detail, but I get the impression this is something that you guys haven't imagined could be happening. Could I please suggest that something be done about this? It's clever that Notepad can tell when a file has become nonexistent, but if the source was on a removable drive then perhaps it wasn't actually deleted but the connection to that resource has been lost. If it's reconnected and the date stamp of the file is earlier than the datestamp of the last modification then Notepad shouldn't ask to reload the file, I think, but offer more options?

Thanks very much for looking at this!

Toby Marthews

![lots of open files](https://cloud.githubusercontent.com/assets/8268559/12853383/b22e1c56-cc2b-11e5-809e-6826a844b13a.png)
![prompt when usb kicked out](https://cloud.githubusercontent.com/assets/8268559/12853829/2477c9cc-cc2e-11e5-87dc-ed4f4237f5e5.png)

**Comment by fade2gray** [comment]
Just curious; do you mean the connecting USB cable gets physically "knocked out" or the system stops recognising the EHD for whatever reason?

**Comment by soi521** [comment]
Thanks for the response. I mean it gets physically knocked out: I have a lot of cables going into and out of more than one machine on my desk and USBs do get knocked out on occasion. It's not faulty: it's just that sometimes I move my laptop a bit closer to me of adjust the screen and this can work the attachment loose over the day. Then I get a string of "Keep this file in the editor" errors as I described and have to try to remember what changes I've made where over the last 5-6 hours (30 or the textfiles I keep always open are on external storage and I'm unwilling to move them to C: drive because they are all sorted into project folders and because my C drive is only 238 Gb I can't fit the whole project folder tree on C).
   Would it be possible to make it so that instead of assuming the file has been deleted and asking "Keep this file in editor" Notepad++ just marked that file as 'Connection temporarily lost' - e.g. by putting red stripes on the tab for that file, but remembering the datestamp of the last file save (which it knows). If the connection is restored then Notepad++ could check the datestamp and, if the same, simply remove the red stripes and continue as before without prompting the user.
   I'm not sure whether this would be a feature that would mean much to many users, but for this user it would be a huge help!

Best,
Toby Marthews

**Comment by fade2gray** [comment]
Hi Toby,
 I'm not a dev so can't comment on your 'Connection temporarily lost' lost solution, but if it's not possible to use a longer and better fitting USB cable, how about using the portable (non installed) version of Notepad++, extracted to and run directly from your EHD. At least that way, if the EHD did get accidentally disconnected, Notepad++ might pick up where it left off without protest when reconnected (just a thought - never tried it).

**Comment by MetaChuh** [comment]
please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins if you update from version 7.5.9 or below.
if your issue still persists, and it is still of relevance to you, please feel free to file a new issue as easy to understand and reproducible as possible.

thank you for your support and best regards.

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
(no extra account is needed, just use your github account to sign in)
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)
