### ISSUE TITLE
Plugin fails to run despite providing an API key

### ISSUE THREAD

**Issue by Uziel9999** [notepad-plus-plus/notepad-plus-plus#14519]
### Description of the Issue
Despite setting the secret key in NppOpenAI.ini, running the plugin errs with:
```
  [Json.exception.parse_error.101] parse error at line 2, column 25: syntax
  error while parsing value - invalid string: missing closing quote, last
  read: • •chatcmpl-8ZQ91i'
```
  ![image](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/4681445/3c3c278c-26cf-4094-aed3-5218cf44b4da)

### Debug Information
```
Notepad++ v8.5.4   (64-bit)
Build time : Jun 17 2023 - 20:42:45
Path : D:\Program Files\Notepad++\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : ON
Cloud Config : OFF
OS Name : Windows 11 Pro N (64-bit)
OS Version : 23H2
OS Build : 22631.2861
Current ANSI codepage : 1252
Plugins : 
    BigFiles (0.1.3)
    CodeAlignmentNpp (14.1.107)
    ComparePlugin (2.0.2)
    JsonTools (5)
    mimeTools (2.9)
    NotepadStarterPlugin (2.3.3)
    NppConverter (4.5)
    NppExport (0.4)
    NppFavorites (1.0.0.1)
    NPPFSIPlugin (0.2.1.1)
    NPPJSONViewer (2.0.5)
    NppOpenAI (0.1.5)
    NppTextFX (1.4.1)
    RegexTrainer (1)
    RestApiToText (1.4.0.1)
    SQLinFormNpp64 (6.23.3.24)
```

I tried uninstalling, restarting NPP, then re-installing the plugin with the same results.

**Comment by alankilborn** [comment]
Suggest you seek support on the plugin support site, as plugin development has nothing to do with Notepad++ development .

**Comment by rdipardo** [comment]
@Uziel9999 

> ### Debug Information
>```
>     ...
>     NppOpenAI (0.1.5)
>     ...
> ```

Try a more recent version (i.e., >= 0.2.1): https://github.com/Krazal/nppopenai/issues/9
