### ISSUE TITLE
The font surrogate fallback fails in version 8.6.

### ISSUE THREAD

**Issue by Yukisama** [notepad-plus-plus/notepad-plus-plus#14510]
The font surrogate fallback fails in version 8.6.

### Description of the Issue
OS: Windows 10 22H2 19045.3803
version: Notepad++ 8.6.0 x64 portable

When upgrade the Npp 8.5.8 to 8.6, the font surrogate fallback fails.
and downgrade the Npp 8.6 to 8.5.8, the font surrogate fallback success.

### Steps to Reproduce the Issue
1. Download the fontpackge ( https://drive.google.com/file/d/1m0-WYAXbEz3lxJrti25ZvWv6LkHjMp2X/view?usp=sharing )
2. Install all font ( *.ttf files )
3. Dbclick the "SurrogateFallback.reg" to setup surrogate fallback on Win10.
4. open the test file "漢字簡易測試.txt" (included in fontpackge)
5. If successful, all characters will be displayed.

p.s. the fontpackage is created by WFG (https://fgwang.blogspot.com/2023/10/unicode-151.html)

### Expected Behavior
all characters will be displayed.

### Actual Behavior
squares replace most characters.

### Debug Information
Notepad++ v8.6   (64-bit)
Build time : Nov 23 2023 - 16:58:44
Path : C:\Portable\Notepad++ 8\notepad++.exe
Command Line : "C:\Portable\Notepad++ 8\readme.txt"
Admin mode : OFF
Local Conf mode : ON
Cloud Config : OFF
OS Name : Windows 10 Pro (64-bit)
OS Version : 22H2
OS Build : 19045.3803
Current ANSI codepage : 950
Plugins : 
    GotoLineCol (2.3)
    mimeTools (2.9)
    NppConverter (4.5)
    NppExport (0.4)
    NppTextFX (0.2.4)
    XMLTools (3.1.1.13)

![npp860](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/5416163/206cbf3b-8aba-4350-a18e-83dd4201e6bc)

**Comment by rdipardo** [comment]
v8.6 comes with [Direct Write][0] text rendering enabled by default. You can disable it by going to `Settings` > `Preferences...` > `MISC.`

<img alt="no-d2d" src="https://github.com/notepad-plus-plus/notepad-plus-plus/assets/59004801/8ca85e0c-4c7d-4bf7-af2b-97950fb04a05">


[0]: https://learn.microsoft.com/zh-cn/windows/win32/directwrite/direct-write-portal
