### ISSUE TITLE
Problem with Alt+Shift+ArrowKeys (Column Mode Select issue)

### ISSUE THREAD

**Issue by networkproblemsolver** [notepad-plus-plus/notepad-plus-plus#14517]
After doing Alt+Shift+ArrowKeys and selecting a column, I press the Del key to delete the selection, but the "cursor" stays tall, the size of my previous selection, and anything typed "acts crazy"... I was able to get out of "column select mode" by using CTRL-END.

Notepad++ v8.6   (64-bit)
Build time : Nov 23 2023 - 16:58:44
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 10 Pro (64-bit)
OS Version : 22H2
OS Build : 19045.3803
Current ANSI codepage : 1252
Plugins : 
    mimeTools (2.9)
    NppConverter (4.5)
    NppExport (0.4)

**Comment by alankilborn** [comment]
Perhaps this upcoming change will solve your issue:
https://github.com/notepad-plus-plus/notepad-plus-plus/pull/14476
