### ISSUE TITLE
The selected text colour of multiselected lines is light grey

### ISSUE THREAD

**Issue by PJBoy** [notepad-plus-plus/notepad-plus-plus#14516]
### Description of the issue
When selecting multiple lines with alt+down or ctrl+click, followed by shift+left/right to highlight text, the highlighted background other than the current line are all light grey, which makes almost invisible text when using light font colour

### Steps to reproduce the issue / actual behavior
One can sketch out some simple text columns and select text on multiple lines, e.g.
![image](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/9425558/1615d2c5-8d41-446f-a2bc-0ed3c3d5d95b)

### Expected behavior
This wasn't the behaviour before, this was introduced in a recent update. It used to be that all highlight colours were the same (defined by the style configuration, orange in the above image)

### Debug information
Notepad++ v8.6   (32-bit)
Build time : Nov 23 2023 - 16:56:22
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Command Line : 
Admin mode : ON
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 10 Home (64-bit)
OS Version : 21H2
OS Build : 19044.3086
Current ANSI codepage : 1252
Plugins : 
    AnalysePlugin (1.13.49)
    BetterMultiSelection (1.5)
    ComparePlugin (2.0.2)
    DSpellCheck (1.5)
    mimeTools (2.9)
    NppConverter (4.5)
    NppDocShare (0.1)
    NppExport (0.4)
    NppFTP (0.29.9)
    NppGraphViz (1.0.0.4)
    NppSmartSense (0.3)
    NppTextFX (1.4.1)
    PreviewHTML (1.3.2)
    SmRamLookup (4.1)
    Tidy2 (0.2)

Thanks

**Comment by alankilborn** [comment]
Somewhat related: #14515

**Comment by PJBoy** [comment]
Resolved via the resolution of #14515, my style file in %APPDATA% needed updating
