### ISSUE TITLE
Different Font Variant/Weight Style Fallbacks To Default Sans-Serif Font

### ISSUE THREAD

**Issue by oxou** [notepad-plus-plus/notepad-plus-plus#14526]
### Description of the Issue
See screenshot at the bottom of the post.  

### Steps to Reproduce the Issue
1. Download [Roboto Mono](https://fonts.google.com/specimen/Roboto+Mono) and install the TrueType variants.
2. Configure fonts as shown in the screenshot at the bottom.

### Expected Behavior
**Roboto Mono Medium** font variant applied.

### Actual Behavior
Font variant of **Roboto Mono** should get changed to **Medium** but instead a fallback font is used.

### Debug Information
```
Notepad++ v8.6   (64-bit)
Build time : Nov 23 2023 - 16:58:44
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : "C:\Users\user\AppData\Local\Microsoft\Windows Terminal\settings.json"
Admin mode : ON
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 10 Enterprise (64-bit)
OS Version : 22H2
OS Build : 19045.2364
Current ANSI codepage : 1252
Plugins : 
    mimeTools (2.9)
    NppConverter (4.5)
    NppExport (0.4)

```

![image](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/102489121/c761a4ff-41a2-49e5-b8c8-2c34edc39791)

**Comment by Mikka-TheOne** [comment]
I do confirm this behaviour for **Notepad++ v8.6.2** (64-bit) and a [different monospaced font](https://github.com/JetBrains/JetBrainsMono).

### Debug Information
```
Notepad++ v8.6.2   (64-bit)
Build time : Jan 14 2024 - 02:16:00
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 8.1 Pro (64-bit)
OS Build : 9600.0
Current ANSI codepage : 1252
Plugins :
    mimeTools (3)
    NppConverter (4.5)
    NppExport (0.4)
    NppPluginOpenHost (1.1)
    NppSaveAsAdmin (1.0.211)
    NppTextFX (1.4.1)
    Remove Duplicate Lines (1.3)
```

**Comment by tormento** [comment]
Same problem with [Iosevka ](https://github.com/be5invis/Iosevka)family.

I am used to Iosevka Curly Slab and it turns to some sans serif font instead.

**Comment by xomx** [comment]
Try to switch off (uncheck) the N++ Settings > Preferences... > MISC. >  Use DirectWrite.

This is somewhat difficult issue concerning also the underlying Scintilla editor component, e.g. see the https://github.com/notepad-plus-plus/notepad-plus-plus/issues/9951

**Comment by oxou** [comment]
@xomx That solves the problem, but introduces a second.  Now emojis are not rendered correctly.

**Comment by xomx** [comment]
@oxou 
>  Now emojis are not rendered correctly.

Yes, this is expected.

It is a pity that the [patch](https://sourceforge.net/p/scintilla/bugs/2356/) mentioned in the issue #9951 cannot be accepted to Scintilla. With it, the DirectWrite mode in N++ would not need any N++ source code change. Otherwise, you need to modify the  existing N++ GDI font handling code to match the weight/stretch/style model of the DirectWrite font families.

**Comment by tormento** [comment]
Have a peek at notepad3 solution. It works just fine and it is scintilla based too

**Comment by oxou** [comment]
@xomx Thanks for the heads-up.  I'm closing this issue as solved.  Regarding the Emoji problem it doesn't bother me, and someone else should open an issue regarding that topic.
