### ISSUE TITLE
Can I do this with multi-edit?

### ISSUE THREAD

**Issue by curya** [notepad-plus-plus/notepad-plus-plus#14522]
Let's say I have these two documents:
![image](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/43591297/d1dc8538-6452-43a3-9eb6-ec3cefcb7aec)
![image](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/43591297/fe2e8de6-4f44-4b7b-ba03-b5c0632754e2)

Can I use multi-edit to somehow paste them together to get this result?
![image](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/43591297/f24d2232-9f95-4a9e-97e5-2b8ec074d6e8)

**Comment by alankilborn** [comment]
Questions belong here:  https://community.notepad-plus-plus.org/

**Comment by curya** [comment]
@alankilborn I was going to post there but I thought this might work better as a feature request. Apologies if I did this incorrectly though.

**Comment by alankilborn** [comment]
Bad plan, any way you look at it.
Please close.
