### ISSUE TITLE
Open File: wrong determination of the caret position

### ISSUE THREAD

**Issue by slwmr** [notepad-plus-plus/notepad-plus-plus#14543]
### Description and Steps to Reproduce the Issue

I have a line of text:
(tab)(tab)(tab)tst.txt
three tab characters and the file name (the file is in the same directory as the file I'm editing).

I want to open the file with the context menu and the option 'Open File'.
I can't open the file if I place the caret on the file name, but I can do that if I place the caret between the first and the second tab.

### Analysis

I think the problem is in NppBigSwitch.cpp
...
case NPPM_GETFILENAMEATCURSOR:
...
col = _pEditView->getCurrentColumnNumber();
This method uses SCI_GETCOLUMN to determine the caret position in the string.
We have tabs as single characters in the string, but SCI_GETCOLUMN takes into account how many 'spaces' every tab (on the left side of the caret) takes.

SCI_GETCOLUMN(position pos) → position
This message returns the column number of a position pos within the document taking the width of tabs into account. This returns the column number of the last tab on the line before pos, plus the number of characters between the last tab and pos. 

Guessing where to click could be fun for short lines, but for long ones with many tab characters... ;)

### Debug Information
Notepad++ v8.6   (32-bit)
Build time : Nov 23 2023 - 16:56:22
Path : C:\b\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : ON
Cloud Config : OFF
OS Name : Windows 10 Home (64-bit)

**Comment by alankilborn** [comment]
I can replicate this in v8.6.

@donho Assign me to fix it?

**Comment by alankilborn** [comment]
Not only is there the bug as described above, but this code is not Unicode-ready. :-(

**Comment by alankilborn** [comment]
@slwmr 

I'm still going to fix this bug, but if you want a more well-rounded "open file" function and you can use a scripting plugin, you might want to check out a script I've written, [HERE]( https://community.notepad-plus-plus.org/topic/17169/how-to-right-mouse-click-file-open-from-current-directory).

**Comment by slwmr** [comment]
Thank you for the suggestion. Indeed, I can use this on my home computer. Otherwise I'm limited to what someone considers safe (the NPP program and a very limited selection of plugins). So I would be grateful if you could fix the bug for some future release.
