### ISSUE TITLE
Symbol mess code

### ISSUE THREAD

**Issue by sonichy** [notepad-plus-plus/notepad-plus-plus#14545]
### Description of the Issue

▶ display as ▢

### Steps to Reproduce the Issue

1. 
2. 
3. 

### Expected Behavior

▶ display as ▶

### Actual Behavior

▶ display as ▢

**Comment by alankilborn** [comment]
Did you try:

![image](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/77065706/9ec36816-50c2-48a2-bda4-e952a30dce93)

**Comment by sonichy** [comment]
After use DirectWrite ▶ can display now, but the height has become smaller .
