### ISSUE TITLE
Changes outside silently overwrites by Search and Replace dialog

### ISSUE THREAD

**Issue by andry81** [notepad-plus-plus/notepad-plus-plus#14540]
I am not sure is that already fixed in the last version or not. But I can not check this at the moment.

### Description of the Issue

If open N files in N tabs and changed some of them outside, then the Notepad++ reports about incoming changes only when the Tab is selected. If not selected and then start to replace in all tabs and then press CTRL+SHIFT+S, then incoming changes would be lost without any notice.

### Steps to Reproduce the Issue

1. Open N files
2. Select any random tab
3. Then change a file associated with not selected tab
4. Replace a text in all tabs
5. Press CTRL+SHIFT+S
6. An external change is overwritten and so is lost

### Expected Behavior

Report of unsaved external changes in a tab before overwrite them by the Replace dialog or any other incoming internal change.

### Debug Information

Notepad++ v7.9.2   (32-bit)
Build time : Dec 31 2020 - 03:58:36
Path : C:\Programs\Utility\notepad-plus-plus.org\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS Name : Windows 8 Single Language (64-bit) 
OS Build : 9200.0
Current ANSI codepage : 1251
Plugins : mimeTools.dll NppConverter.dll NppExport.dll PythonScript.dll

**Comment by alankilborn** [comment]
To cure this problem, make sure the indicated setting is set:

![image](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/77065706/7521ebf8-19ae-439a-845e-7204884a314b)

This issue may be closed.

**Comment by alankilborn** [comment]
>Notepad++ v7.9.2 (32-bit)
>I am not sure is that already fixed in the last version or not.

Please do not report a "problem" against software that is very old, without checking the current version first.

>But I can not check this at the moment.

???
Then wait until you _can_ check it.

**Comment by andry81** [comment]
8.6.1 - same behavior.

> To cure this problem, make sure the indicated setting is set:

Why this is not set as by default?

**Comment by andry81** [comment]
> To cure this problem, make sure the indicated setting is set:

There is another issue. It does not remember the selection if Notepad were run with `-nosession -multiInst` options.

**Comment by alankilborn** [comment]
>Why this is not set as by default?

Defaults are chosen as deemed best for most users.

>It does not remember the selection if Notepad were run with -nosession -multiInst options.

* Close all instances of Notepad++.  
* Start Notepad++ with no command line options.  
* Set _Preference_ settings the way you desire.  
* Exit Notepad++.  

At this point all instances started should use the new settings.

**Comment by alankilborn** [comment]
Possibly you could use the `-settingsDir` command line argument, but I don't know too much about that one.  You'd have to experiment.

**Comment by andry81** [comment]
Thx for advice. I've found the setting:

```xml
<GUIConfig name="Auto-detection">yesOld</GUIConfig>
```

Seems it's an old setting. Don't know why. But then I have to copy entire directory to just only for a bit of change in the settings. It's too much.
