### ISSUE TITLE
The Notepad++ GUI does not save user ext for XML added via the style configurator

### ISSUE THREAD

**Issue by Talthos** [notepad-plus-plus/notepad-plus-plus#14555]
### Description of the Issue
User extensions for XML are not saved when added via the Notepad++ GUI in the style configurator. Both the default theme and custom themes are affected.

### Steps to Reproduce the Issue
1. Start Notepad++
2. Open Style Configurator.
3. Scroll the Language list down to XML
4. Add any value to the "User ext" box, then click "Save & Close"
5. Re-open the Style Configurator, de-select then re-select XML in the Language list.

### Expected Behavior
The Style Configurator retains any added User ext once "Save & Close" has been clicked.

### Actual Behavior
The Style Configurator does not retain any added User ext once "Save & Close" has been clicked.

### Debug Information
Notepad++ v8.6   (64-bit)
Build time : Nov 23 2023 - 16:58:44
Path : J:\Notepad++\notepad++.exe
Command Line : "C:\Users\jerem\AppData\Roaming\Notepad++\stylers.xml"
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 10 Pro (64-bit)
OS Version : 22H2
OS Build : 19045.3803
Current ANSI codepage : 1252
Plugins : 
    ComparePlus (1.1)
    mimeTools (2.9)
    NppConverter (4.5)
    NppExport (0.4)

### Other Info
Adding User extensions by directly opening and modifying the "stylers.xml" seems to work; user extensions added this way are retained properly.

**Comment by alankilborn** [comment]
See point 3 in the 8.6.1 change.log [HERE](https://community.notepad-plus-plus.org/topic/25315/notepad-v8-6-1-release).

Suggest you retest your issue in 8.6.1.

**Comment by Talthos** [comment]
> See point 3 in the 8.6.1 change.log [HERE](https://community.notepad-plus-plus.org/topic/25315/notepad-v8-6-1-release).
> 
> Suggest you retest your issue in 8.6.1.

Just updated to the version you linked. And huzzah! It works!

Thanks!

**Comment by donho** [comment]
Fixed in v8.6.1
