### ISSUE TITLE
Paste/Cut with SHIFT+INS/DEL broken in v8.6.1

### ISSUE THREAD

**Issue by fda77** [notepad-plus-plus/notepad-plus-plus#14551]
Since updating to version 8.6.1 pasting text is no longer possible by SHIFT + INS keys.

It worked before and with other methods like CTRL+V or CONTEXTMENU + INSERT

I tested older version v8.6(.0) , this works

### Debug Information

```
Notepad++ v8.6.1   (64-bit)
Build time : Jan  4 2024 - 05:01:52
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : "C:\some.txt"
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 10 Pro (64-bit)
OS Version : 22H2
OS Build : 19045.3803
Current ANSI codepage : 1252
Plugins : 
    ComparePlugin (2.0.2)
    mimeTools (3)
    NppConverter (4.5)
    NppExport (0.4)
```

**Comment by salavessa** [comment]
Same happens for "cut" command via "SHIFT + DEL". It works in version 8.6 but not in 8.6.1.

**Comment by fda77** [comment]
@salavessa Windows?

**Comment by donho** [comment]
https://github.com/notepad-plus-plus/notepad-plus-plus/issues/14557
