### ISSUE TITLE
Search ignore diacritics

### ISSUE THREAD

**Issue by andradadad** [notepad-plus-plus/notepad-plus-plus#14552]
### Description of the Issue

Searches don't show diacritics except if written.

### Steps to Reproduce the Issue

1.  search without/with diacritics
2.  results don't specify unless if objective

### Expected Behavior

Tickable 'ignore diacritics' option.

Would also be nice to have removed the button "replace on all opened documents" which looks extremely dangerous, unless if you had chosen yourself to have such button.

**Comment by donho** [comment]
Please follow the template to provide detail info and the sample to reproduce the issue.

**Comment by andradadad** [comment]
Ridiculous abuse for closing an issue.

**Comment by alankilborn** [comment]
>Ridiculous abuse for closing an issue.

There are a lot of open issues, so improper ones get closed quickly.
Simply add the requested info and your issue will likely be reopened.
