### ISSUE TITLE
[Crash] TeX-Command length over 100

### ISSUE THREAD

**Issue by Guest12345678** [notepad-plus-plus/notepad-plus-plus#1455]
Hello everybody.
Since I didn't like the current folding mechanism of Tex Documents, I wanted to look if I could understand the source code for why it performs so strange on my System. 
I got nothing, but I found a small little bug: in "scintilla/lexers/LexTeX.cxx::Line312", there is a while(... && length<100). 
For fun I tested what happens if I make such a Long command (\commandaaaaa......), and I was not surprised that Npp crashed as I reached column 101.
I don't have the time nor knowledge to catch that error, but since such a Thing only happens on purpose, it should be that important anyway. Just letting everyone know.

**Comment by dail8859** [comment]
These lexers are from the Scintilla project. Notepad++ just uses them as-is and does not modify them. You'll have to report it to Scintilla...assuming this bug hasn't already been fixed in their latest version.

**Comment by dail8859** [comment]
Closing since this is a Scintilla issue.
