### ISSUE TITLE
undo no longer steps back to states before last save

### ISSUE THREAD

**Issue by CaverBruce** [notepad-plus-plus/notepad-plus-plus#14556]
### Description of the Issue
Previously undo used to step back to and prior to document states prior to the last save.
Now (v8.6) undo stops at the currently saved state of the file and will not step back further.

### Steps to Reproduce the Issue
1.  open a document
2.  make some changes
3.  save the document
4.  make 1 more change
5.  Ctrl+Z = undoes the change = good
6.  Ctrl+Z = nothing happens = bad

### Expected Behavior
Step 6 should have undone the changes made in step 2 above, just like NotePad++ used to do

### Actual Behavior
Step 6 did nothing

### Debug Information
Notepad++ v8.6   (32-bit)
Build time : Nov 23 2023 - 16:56:22
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Command Line : "D:\CaveSurvey\th_RiwakaCaveSystemData\th_RiuwakaCaveSystem\NgaruaArea\HawkesKairuruCaves\ptopoHawkes\1-HawkesTEXT.txt"
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 10 Home (64-bit)
OS Version : 22H2
OS Build : 19045.3803
Current ANSI codepage : 1252
Plugins : 
    ComparePlugin (2)
    DSpellCheck (1.4.6)
    mimeTools (2.9)
    NppConverter (4.5)
    NppExport (0.4)

**Comment by alankilborn** [comment]
Unable to reproduce.  Trying step 6 results in Expected Behavior.

DSpellCheck plugin sometimes causes odd things to occur.  Suggest removing it and retesting.

**Comment by CaverBruce** [comment]
OK, perhaps I raised this prematurely, or perhaps it is intermittent.
I had noticed the behaviour for some time, however on rebooting the machine the issue has been resolved.
Will reopen if if comes back.
