### ISSUE TITLE
Find Dialogue- Writing text and hitting Enter searches up no matter what

### ISSUE THREAD

**Issue by dvjrickkraft** [notepad-plus-plus/notepad-plus-plus#14563]
### Description of the Issue
Typing text in the Find dialogue and hitting Enter searches up, not down.
This searches up no matter if the Find Up or Find Next boxes are selected (or last used).
(Even after clicking on Find Next and therefore selecting the box, Enter still searches up.)
Also, with the check-mark beside Find Next deselected so there's only Find Next, typing text and hitting Enter searches up.

### Steps to Reproduce the Issue
1. Have a document with a minimum of two identical text such as "tech". 
2. Ensure the cursor is above the first text occurrence, in this example, "tech".
3. Ctrl+F, to bring up the Find Dialogue. 
4. Type "tech" into search bar. Hit Enter. Search starts from the bottom.

### Expected Behavior
Expected result when hitting Enter is to Find Next.
(unless the Find Up box is selected from being last used.)

### Actual Behavior
Search started from the bottom.

### Debug Information
Notepad++ v8.5.4   (64-bit)
Build time : Jun 17 2023 - 20:42:45
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : "C:\Temp\Main settings UNICODE.txt"
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 11 Pro (64-bit)
OS Version : 22H2
OS Build : 22622.290
Current ANSI codepage : 1252
Plugins : 
    mimeTools (2.9)
    NppConverter (4.5)
    NppExport (0.4)

This is my first time to submit and I've searched carefully through other 'Find' submissions, didn't see this reported yet. 
I've read the guidelines, and tried to follow everything that should be done. Please let me know if I need to fix or add anything. Thank you! 🙂

**Comment by alankilborn** [comment]
Your description seems consistent with having this checkbox checkmarked:

![image](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/77065706/32f42b6b-93c4-4f4e-a132-6081c8b038b3)

IS it checkmarked?

**Comment by dvjrickkraft** [comment]
Uhhh... yes. Yes it was. That was it??? Dang. Been using NPP++ for 4-5 years and must've clicked it sometime in the past, and it's been driving me nuts for over a half year at least.  Thank you kindly for enlightening me.  My apologies.

**Comment by dvjrickkraft** [comment]
Uhhh... yes. Yes it was. That was it??? Dang. Been using NPP++ for 4-5 years and must've clicked it sometime in the past, and it's been driving me nuts for over a half year at least.  Thank you kindly for enlightening me.  My apologies.

**Comment by alankilborn** [comment]
> driving me nuts for over a half year at least

Wow, sorry to hear, that's a LONG time.
I'm not sure how Notepad++ could've made this easier for you to figure out quickly and on your own.  :-(
Take a critical look at the UI settings when something is not found when you think it should be, or other things you feel are "odd" occur when searching.

BTW, _Backward direction_ is a bit antiquated -- a suggestion for you might be to NEVER checkmark it (and that way Enter will always search downward and Shift+Enter will always look upward).

**Comment by dvjrickkraft** [comment]
Thanks yeah, as a tech guy this is very embarrassing heh. I remember i was fooling around with searching up and must've clicked it then, closed the Find Dialogue... then used it a week later and forgotten what I had done.  It happens.

As part of my career I have documented and helped Dev teams to streamline and make GUIs better... and it's the very first item, I should have seen it. So, I have zero suggestions here. And thank you for even considering that!  
Love the friendly help here at NPP++. 💘    -Rick, Techspin (on YT)
