### ISSUE TITLE
Can’t use Ctrl+V to paste text into the text fields of forms for certain plugins

### ISSUE THREAD

**Issue by donho** [notepad-plus-plus/notepad-plus-plus#14568]
Ref:
1. https://community.notepad-plus-plus.org/topic/25315/notepad-v8-6-1-release/2?_=1704770077793
2. https://github.com/notepad-plus-plus/notepad-plus-plus/issues/14557#issuecomment-1879914173

### Description of the Issue
Can’t use Ctrl+V to paste text into the text fields of forms for certain plugins in v8.6.1

### Steps to Reproduce the Issue

1. Install [JsonTools 6.1.1 ](https://github.com/molsonkiko/JsonToolsNppPlugin) in Notepad++ v8.6.1
2. Start Notepad++ and  launch JsonTools GUI
4. Try to paste a text by using Ctrl-V

### Expected Behavior
Can paste text by using Ctrl-V

### Actual Behavior
Cannot paste text by using Ctrl-V

### Debug Information
```
Notepad++ v8.6.1   (64-bit)
Build time : Jan  4 2024 - 05:01:52
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : -multiInst
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 11 Home (64-bit)
OS Version : 23H2
OS Build : 22631.2861
Current ANSI codepage : 1252
Plugins : 
    BetterMultiSelection (1.5)
    mimeTools (3)
    NppConverter (4.5)
    NppExport (0.4)
    PythonScript (2)
    VisualStudioLineCopy (1.0.0.2)
```

**Comment by Coises** [comment]
I mentioned this in the #14557 discussion, but one possible way to fix this would be to put code like this:

	for (HWND msgAncestor = msg->hwnd; msgAncestor && msgAncestor != _hSelf; msgAncestor = ::GetParent(msgAncestor))
	{
		if (WC_DIALOG == MAKEINTATOM(GetClassLong(msgAncestor, GCW_ATOM))) return ::IsDialogMessage(msgAncestor, msg);
	}

into [Notepad_plus_Window::isDlgsMsg](https://github.com/notepad-plus-plus/notepad-plus-plus/blob/eb0922c2233bff484f91e7f1cf26446e6a9bc2a5/PowerEditor/src/Notepad_plus_Window.cpp#L422).

If you like this approach, for efficiency it might make sense to test msg->hwnd against _hSelf and the two main Scintilla windows at the top of the routine.

With this approach there is also the question of whether to retain NPPM_MODELESSDIALOG and the scan of _notepad_plus_plus_core._hModelessDlgs (in case some plugins create non-modal windows that are not dialogs and use this message to avoid having application accelerators recognized), and the possibility that some plugin (or Notepad++ itself) might *intend* that application accelerators be recognized in some dialog.

However, it would quickly and cleanly dispose of the common complaint. Determining whether there are troublesome side effects would take some testing.
