### ISSUE TITLE
Improve / clarify description for setting 'Backup in every [ X ] seconds'

### ISSUE THREAD

**Issue by dcog989** [notepad-plus-plus/notepad-plus-plus#14560]
### Description of the Issue
The setting in 'Preferences ... Backup ... Backup in every [ X ] seconds' does not mention that it is conditional and only triggers "if file has changed". A user could therefore misinterpret this to to mean a backup is running every X seconds regardless.

### Solution
Change the text for this setting to:

`Backup every [ X ] seconds if files have changed`

**Comment by alankilborn** [comment]
I suggest that this suggestion be rejected, as unnecessary.
Only persons unfamiliar with computers would think that a program would continually make backups of data that hasn't changed.

**Comment by dcog989** [comment]
@alankilborn

If the description says *"this backup will run every 5 seconds"* then a lot of people will think that the backup is going to *run every 5 seconds*. So, reasonable people are going to think that maybe the description could be improved when that assumption is not true. This is about making software that is designed to **help** the **majority** of people. 

I appreciate that you desperately want to appear superior to everyone else, but you are achieving the opposite.

**Comment by xomx** [comment]
I am not saying that this is necessary but if it helps some users - why not.

What about `Backup edits every [xxx] seconds` ?

**Comment by donho** [comment]
> I suggest that this suggestion be rejected, as unnecessary. Only persons unfamiliar with computers would think that a program would continually make backups of data that hasn't changed.

It seems evident for Notepad++ veterans. However the common users (no background of computer knowledge, my grand mom for example) cannot get the subtlety of the complex backup feature. As Notepad++ should be accessible for the software engineers, IT people, as well the common users, I think it's fair to reword a few of labels to make some feature more clear.

**Comment by donho** [comment]
How about: **"Trigger backup after modification in every XX seconds"** ?
