### ISSUE TITLE
Ctrl/Shift insert not working

### ISSUE THREAD

**Issue by jandohrmann** [notepad-plus-plus/notepad-plus-plus#14571]
Ctrl/Shift insert is not working anymore on Windows 11 with the newest version of NotePad++ (8.6.1)

Believe it is due to the Scintilla update. Can not find Ctrl/Shift insert as macro for copy/paste.

Went back to version 8.6 and everything works again.

Best Regards
Jan Dohrmann

**Comment by atom888888** [comment]
I just looked and 8.6.2 version has fixed this issue.  Thank you for fixing it.

**Comment by passee** [comment]
Im on v8.7.1 and CTRL+Shift+V isnt working for me..
@atom888888 could you check if it still works for you?

**Comment by alankilborn** [comment]
@passee said:

>CTRL+Shift+V isnt working for me

And, what are you expecting it to do?
What command do you have it assigned to?

**Comment by passee** [comment]
@alankilborn 
i have not assigned it todo anything in npp.
default windows behaviour would be "past as plain text", which doesnt work

**Comment by alankilborn** [comment]
>default windows behaviour would be "paste as plain text"

Notepad++ is a text editor; plain text is the only type of pasting you're likely to get.
If you do Ctrl+v (no Shift), what do you obtain?

**Comment by passee** [comment]
Well first off when pasting as plain text some weird characters or symbols often wont get pasted and secondary if there isnt any macro on it, why should it **not** work?
