### ISSUE TITLE
how to set notpad++ as default for files that start with a period/dot

### ISSUE THREAD

**Issue by slyfox1186** [notepad-plus-plus/notepad-plus-plus#14572]
How do you edit the config files or edit Windows registry to make notepad++ open a file like this ".bashrc" as the default editor?

**Comment by rddim** [comment]
`Setting` > `Preferences...` > `File Association` > `customize`, type `bashrc` in the field and click `->` to add it to the `Registered extensions:`

**Comment by molsonkiko** [comment]
I tend to do this from Windows File Explorer, just right-click a file, click `Properties`, click `Change` near the top where it says `type of file: BASHRC file (.bashrc)`, and select `Notepad++` from the list.

rddim's solution is probably faster, but mine is perhaps more general
