### ISSUE TITLE
REQUEST: Implement python CMD & PowerShell shortcut to save the script, type in python and current script name, and wait for commands.  Autosave the file first too

### ISSUE THREAD

**Issue by MichaelWoodc** [notepad-plus-plus/notepad-plus-plus#14589]
### Description of the Issue
There is no easy to use run button..  You have to save the file, open command prompt, type python, drag the file over, etc.  

We must write python programs that run through cmd and use sys.argv in order to get user input.  I was able to do the following with PowerShell, which would be convenient for everyone else if it were standard, and I want to try and make a cmd prompt version, but I am not having any luck!

`powershell -NoProfile -ExecutionPolicy Bypass -Command "& { $input = Read-Host 'Enter values' ; python '$(FULL_CURRENT_PATH)' $($input -split ' ') ; Read-Host 'Press Enter to exit' }"`

This will open PowerShell, type in everything needed to be ready for your input, you put in your input and press enter, it runs and the window stays open to see your results.  

Also, in order for it to run as it is without saving the file, I have to use the autosave plugin configured to run every time notepad++ loses focus.  

Here's what I'm hoping could be implemented:

![notepad++auto](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/51295010/947e4156-a70a-4008-845a-c61a12c6723b)

**Comment by MichaelWoodc** [comment]
ok I just found the cmd prompt equivalent:
cmd /K set /p additional_args=Enter additional command line arguments for Python: && call python "$(FULL_CURRENT_PATH)" %additional_args%

**Comment by rdipardo** [comment]
Have you heard of [NppExec](https://github.com/d0vgan/nppexec)?

<img width="600" alt="py-run-nppexec" src="https://github.com/notepad-plus-plus/notepad-plus-plus/assets/59004801/1fc1e01f-3e28-4720-8d9a-2205c82d9899">

*See esp. [Running Python & wxPython](https://d0vgan.github.io/nppexec/NppExec_Manual/4.6.4.html)*

**Comment by MichaelWoodc** [comment]
> Have you heard of [NppExec](https://github.com/d0vgan/nppexec)?
> _See esp. [Running Python & wxPython](https://d0vgan.github.io/nppexec/NppExec_Manual/4.6.4.html)_

Never heard of it, thanks for the tip!  I'm trying to figure out now how I can execute the python program, leave the terminanl open, and press a hotkey to run it again without having to close it and reopen it.  

Now if I've ran the python program it stays open.  If I run it again it says that the termial is already open and I need to close it

**Comment by CDL512** [comment]
Hello Chris,
![Screenshot (24)](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/158224844/1c26887c-4b14-4a3d-8389-bf19ae636b03)
 this is what I have now.
