### ISSUE TITLE
NPP crashes upon selecting from Menu file/open

### ISSUE THREAD

**Issue by cmartin64bb** [notepad-plus-plus/notepad-plus-plus#14582]
### Description of the Issue
Running on Ubuntu 20.04 with Notepad++ v8.6.1. Never was an issue until now - after sudo apt update/upgrade

### Steps to Reproduce the Issue

1. Start app (fine)
2. Click on Top Menu "File" (fine)
3. Click on "Open) - crashes
![image](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/153114642/89686b97-9fec-441f-accf-cac3ce970548)

### Expected Behavior
no crash

### Debug Information
Notepad++ v8.6.1   (64-bit)
Build time : Jan  4 2024 - 05:01:52
Path : Z:\home\joe90\snap\notepad-plus-plus\388\notepad-plus-plus\notepad-plus-plus.exe
Command Line : 
Admin mode : ON
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Microsoft Windows 7 (64-bit)
OS Build : 7601.0
Current ANSI codepage : 1252
WINE : 7.22
Plugins : 
    mimeTools (3)
    NppConverter (4.5)
    NppExport (0.4)

**Comment by cmartin64bb** [comment]
above steps solved it

**Comment by h3d-longnsp** [comment]
I have similar problem and the above step did solve it (I'm so lost). I'm using Ubuntu 24.04 and notepad++ version 8.6.9.0. New version 8.7 came out a few days ago and NPP just crashed when I try to open it. So reinstall it did fix the bug, just remember to backup your unsaved at this location `/home/<your-user>/snap/notepad-plus-plus/common/.wine/drive_c/users/<your-user>/AppData/Roaming/Notepad++`
