### ISSUE TITLE
Blue screen when selecting text with mouse drag on AMD 7840HS (eGPU 780M)

### ISSUE THREAD

**Issue by hippogamesunity** [notepad-plus-plus/notepad-plus-plus#14581]
### Description of the Issue
Blue screen when selecting text with mouse drag on AMD 7840HS (eGPU 780M). Stable blue screens. The same in 8.5 and 8.6.1.

### Steps to Reproduce the Issue
1. Open any text file
2. Select text with mouse drag

### Expected Behavior
Text selected

### Actual Behavior
Blue screen

### Debug Information
I've purchased a mini PC with AMD 7840HS (eGPU 780M) and found that it hangs all the time I use np++. No issues when working with texts in Word, Visual Studio, Notepad, Chrome. The latest AMD drivers installed (23.12.1). Windows 10 with all updates installed. 32 GB DDR5 5600.

**Comment by xomx** [comment]
Cannot reproduce (on a laptop with the same CPU/GPU & RAM but + 2nd Nvidia Optimus graphics card, Win11).

Update your report with the info from the Notepad++ menu > ? > Debug Info...

Try to switch on/off the DirectWrite checkbox in the Settings > Preferences > MISC.

Are you are able to select the same text via keyboard?  (if so maybe the mouse/touchpad driver could be the culprit)

**Comment by hippogamesunity** [comment]
Please close the issue, it looks it's hardware problems. I've found a thread with the same symptoms from other users. I have to refund this pc as broken.
