### ISSUE TITLE
Abnormal display

### ISSUE THREAD

**Issue by k9fvm** [notepad-plus-plus/notepad-plus-plus#14580]
Win11 3840X2160 Global-Zoom 150% (Windows Default Recommended)
<img width="170" alt="1" src="https://github.com/notepad-plus-plus/notepad-plus-plus/assets/90003417/107b4b1b-4279-4303-845e-2ccacac1703a">

**Comment by k9fvm** [comment]
> Do you have a multi-monitor setup?

No, Just one 4K monitor.

**Comment by xomx** [comment]
Cannot reproduce (x64 N++ v8.6.1, Win11Pro 22H2, monitor 3200x2000, scaled up to 200%).

Could you append your N++ menu > ? > Debug Info... ?

**Comment by k9fvm** [comment]
Try again with npp.**portable**.x64 and monitor **3840X2160**.
**Restart** npp everytime, and **No window-maximized**.
I believe you can reproduce it.
(The most important thing is that **3840X2160** monitor.)

**Comment by xomx** [comment]
I cannot test 3840x2160 as my mon is 16:10 and yours 16:9, but at least I tried 3840x2400 by the help of the virtual super resolution - no problem either. I do not have a suitable 16:9 one, sorry.
