### ISSUE TITLE
Dynamically Share Notepad++ Configuration Between Multiple Instances '-multiInst'

### ISSUE THREAD

**Issue by addonszz** [notepad-plus-plus/notepad-plus-plus#1459]
##### Dynamically Share Notepad++ Configuration Between Multiple Instances '-multiInst'

Environment: 
1. On an environment where the user has multiple (a lot) notepad++ instances open and some of them open and close more/later than others. 
2. Then when the user change a setting on one instance, it is not shared between the others opened instances. 

This cause the new setting lost when and older instance is closed after the new instance where the new configuration was set.
1. This happens because the setting is saved to the disk after the current sessions is closed.
2. To partially solve the setting lost, should be checked before override the current disk setting, if it was changed by another instance.

This is partially solve because could no support the user change different settings across different notepad++ instances, as they are not synchronized.
1. To completely solve this, synchronize default configuration across all existent notepad++ instances.
2. This must be used to the default notepad++ settings because could be others notepad++ instances using settings other than the default settings file as notepad++ portable.

**Comment by donho** [comment]
It's not a trivial issue, I won't work on this issue.
