### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by adec86** [notepad-plus-plus/notepad-plus-plus#14608]
### Steps to Reproduce the Issue

1. When I type "{" symbol after "p", it jumped to right.
2. filename styles.css
3. code below

### Expected Behavior

body {background-color: powderblue;}
h1   {color: blue;}
	p {

**Comment by adec86** [comment]
You can try write in this code after "p" this "{" symbol and see how it jump as indentation. Why it go to right?

**Comment by alankilborn** [comment]
> You can try write in this code after "p" this "{" symbol and see how it jump as indentation. Why it go to right?

Nope, not near enough of the required info to keep discussing this...

**Comment by xomx** [comment]
I can reproduce the behavior described.

1) DL & unzip the 
[test-#14608.zip](https://github.com/notepad-plus-plus/notepad-plus-plus/files/13979556/test-.14608.zip)

2) Open styles.css & styles2.css in N++.

3) Try to type that "p{" or "p {" at the end of these files, the problem will only appear in the styles.css file.

**Comment by adec86** [comment]
[Screen Recording - Made with FlexClip.webm](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/50264542/196839ce-3dc4-4998-98ff-1537199f378e)

I record my screen show how it do.

**Comment by adec86** [comment]
Another PC there is same problem after typing {, but in simple notepad have not this problem, it only in N++.

**Comment by adec86** [comment]
Hello

in the new version notepad++ 8.6.4 the same problem after writing { the
string jump right.

If you not trust me you can create in you PC empty file with .css extension
and check it


Thanks


Best Regards
Sergey Nazaryan

чт, 18 янв. 2024 г. в 21:09, xomx ***@***.***>:
