### ISSUE TITLE
Notepad++ 8.6.2 portable version updater not working, please help!

### ISSUE THREAD

**Issue by bryanray** [notepad-plus-plus/notepad-plus-plus#14609]
Hi,

![image](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/1768531/f5b54eab-44fa-41cd-b95a-a7e1f42e6af5)
menu -> update notepad++
error returned
![image](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/1768531/58ab9a74-ad42-4790-89b6-088209452ec7)
menu -> set updater proxy - this is default
![image](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/1768531/4c56aed5-3b8f-4854-bb16-29b6c27c77a8)

Notepad++ 8.6.2 portable
Running as administrator
using proxy and no proxy result the same

every time I update I download new version from npp website, and create new folder for new portable version,
but today I find out there is a function call updater, when I try it, it always return error message as in attached image,
please help out fellow coding magician!

thanks

**Comment by xomx** [comment]
notepad-plus-plus.org was down today, retry now...

**Comment by bryanray** [comment]
sorry, still saying the same error message, I just tried twice, with and without the SSR proxy.

also I did not setup the "proxy settings" in npp, i always leave it as is.

> notepad-plus-plus.org was down today, retry now...

**Comment by xomx** [comment]
Just tried with a fresh v8.6.2 portable, no proxy - works ok for me:

![npp-v862-portable-update-ok](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/13075183/153447c1-6f00-433e-aad9-7f10bb9a4dd0)

Maybe a firewall issue or similar.

**Comment by bryanray** [comment]
Hi, not local firewall software issue i tried add both inbound and outbound rules...
 
maybe some country bound firewall, must use proxy to visit...

i cannot direct access to the official website, had to use proxy to gain access......
https://notepad-plus-plus.org/

**Comment by xomx** [comment]
@bryanray 
Ok, so I recommend closing of this issue.
