### ISSUE TITLE
Tablename in tab shown in very large font when using hig dpi

### ISSUE THREAD

**Issue by Bascy** [notepad-plus-plus/notepad-plus-plus#1461]
When using monitors with high dpi settings, the table names shown in the tabs are using very large fonts

![image](https://cloud.githubusercontent.com/assets/633644/12972719/d03700d4-d0a7-11e5-9feb-387daca9a1da.png)

**Comment by wseguin** [comment]
I'm getting the exact opposite on 4k monitors when connecting to RDP sessions. The font gets tiny (unscaled).

![image](https://cloud.githubusercontent.com/assets/10696533/13398477/750d5eaa-decc-11e5-9e11-073b2d653c51.png)

**Comment by JerryBian** [comment]
Any plan to support high DPI?

**Comment by alenl** [comment]
I see the same problem as in the screenshot from Bascy - tab names are too large. The High-DPI support was supposedly added two years ago: https://notepad-plus-plus.org/news/notepad-6.5.4-release.html However, it seems like something is wrong there.
Could that be because I have multiple monitors with different font scales (some are 4k, some are not)? I've seen similar UI errors with some apps where the "per-monitor DPI-aware" setting was not consistent between the actual application behavior, and the app manifest.

**Comment by MetaChuh** [comment]
please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins if you update from version 7.5.9 or below.
if your issue still persists, and it is still of relevance to you, please feel free to file a new issue as easy to understand and reproducible as possible.

thank you for your support and best regards.

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
(no extra account is needed, just use your github account to sign in)
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)
