### ISSUE TITLE
Notepad++ freezes several times a day

### ISSUE THREAD

**Issue by tage5447** [notepad-plus-plus/notepad-plus-plus#14612]
### Description of the Issue
After last install and update freezes Notepad++ several times a day. It happens randomly when I type in code.  Nothing happens until, for example, I click get another tab or a panel. Then it closes and I can start it again. When I look at the file, everything has been saved and recreated exactly where I was. It may even happen that the last part of what I entered, but which I did not see at the time of locking, is included.
The computer is newly reinstalled after a system disk crash.

### Steps to Reproduce the Issue
It happens randomly.
No possibility to consciously re-examine the situation when it happens.
1. 
2. 
3. 

### Expected Behavior
So far, the programme has worked perfectly. And I hope that it will continue to do so in the future - without lockdown.

### Debug Information
Notepad++ v8.6   (64-bit)
Build time : Nov 23 2023 - 16:58:44
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 10 Home (64-bit)
OS Version : 22H2
OS Build : 19045.3930
Current ANSI codepage : 1252
Plugins : 
    BracketsCheck (1.2.2)
    CodeAlignmentNpp (14.1.107)
    CommentToggler (1)
    ComparePlus (1.1)
    DSpellCheck (1.5)
    FoldingLineHider (1)
    HTMLTag (1.4.1)
    ImgTag (2.0.1)
    JsMapParser.NppPlugin (4.2)
    mimeTools (2.9)
    NavigateTo (2.6.4)
    Npp-Highlighter (1.0.0.1)
    nppAutoDetectIndent (2.3)
    NppConverter (4.5)
    nppcrypt (1.0.1.6)
    NppEventExec (0.9)
    NppExec (0.8.4)
    NppExport (0.4)
    NppFavorites (1.0.0.1)
    NppFTP (0.29.12)
    NppJumpList (1.2.2)
    NppQrCode64 (0.0.0.2)
    NppRegExTractorPlugin (2.1)
    NppSnippets (1.7.1)
    NppTaskList (2.5)
    NppTextViz (0.4.2)
    NppXmlTreeviewPlugin (2)
    PreviewHTML (1.3.2)
    RegexTrainer (1.2)
    SQLinFormNpp64 (6.23.3.24)
    XBrackets (1.3.1)
    XMLTools (3.1.1.13)
    _CustomizeToolbar (5.3)

**Comment by xomx** [comment]
https://community.notepad-plus-plus.org/topic/23146/faq-notepad-crashes-freezes-unresponsive-after-update

**Comment by donho** [comment]
I bet it's an issue of one of your plugins.
Remove all of them then try.
If it happens again, please open a new issue.
