### ISSUE TITLE
community forum failing secure connection

### ISSUE THREAD

**Issue by molsonkiko** [notepad-plus-plus/notepad-plus-plus#14610]
### Description of the Issue

Trying to reach [the community forum](https://community.notepad-plus-plus.org/) on Firefox or Edge gives an `SSL_ERROR_UNRECOGNIZED_NAME_ALERT` error, and it cannot be accessed. I believe this started yesterday or the day before.

I'm using Firefox 121.01, Edge 120.0.2210.133, Windows 10 Home 64bit build 19045.3930.

### Steps to Reproduce the Issue

1. Search the forum on Firefox or Edge as described above

**Comment by xomx** [comment]
Seems to be fixed now.

**Comment by molsonkiko** [comment]
> Seems to be fixed now.
Agreed. I'll close this since it's fixed on my end.
