### ISSUE TITLE
Change the default JSON styles so that errors on selected line are easier to see

### ISSUE THREAD

**Issue by molsonkiko** [notepad-plus-plus/notepad-plus-plus#14618]
### Description of the Issue

I have long *hated* the default styling of JSON in Notepad++, because when the active line has an error, it looks like this:

![image](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/46202915/6ee75f9e-3262-4fe8-b3c3-25d9ce01440f)

As you can see, lines other than the active line are fine, but the active line is practically unreadable, because whoever was designing the styles __ignored the fact that the active line background overrides the backgrounds for a lexer style.__

Since the default JSON lexer treats comments and single-quoted stirngs and NaN and Infinity as an error, this problem applies to all of those things in any file with the `.json` extension instead of `.json5`

I have changed the default styling so that errors look like this instead:

![image](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/46202915/82c9c850-8966-4dd5-be99-a1e9587330a9)

The exact details don't matter, but I chose this color combination because:
1. errors on any line (including the active line) are immediately obvious
2. light red should provide reasonable contrast with dark blue even for people who are red-green colorblind
3. the bold-underline-italic combination ensures visual contrast with every other style.

Please please please don't close this issue because this is a bad setting and thus arguably not a true bug. I refuse to believe that there is anyone who really thinks it is *good* for errors to make the active line unreadable, and this is the way things look by default, not some esoteric styler like Hello Kitty. I believe that many people will look at these unreadable errors and simply give up and switch to something like VSCode for working with JSON rather than trying to change the settings.

I believe that simply changing this setting fixes most of my problems with JSON in Notepad++.

### Steps to Reproduce the Issue

1. Change the styling to the default stylers.xml, and turn off dark mode if it was on
2. Go to  `Settings->Style Configurator`, choose `JSON` from the language list and `ERROR` from the style list, and verify that the `Colour Style->Background` is red and `Colour Style->Foreground` is yellow, which I believe are the defaults.
3. Enter `[1, 2, 3, true, false]` in a file and save it as JSON, or just choose `JSON` from the language menu.
4. Go back to the `true` and observe how all the line from the `t` onward becomes nearly unreadable.
5. Try changing the foreground color to the default blue and the background color to light red (really light, use the `More Colours` option to dial it down, to ensure good contrast), then turn on underlining, italics, and bold.
6. Observe how it is now possible to read the entire line, and it is still obvious where the error started.

### Expected Behavior

Errors don't make the active line invisible

### Actual Behavior

errors make the active line invisible

### Debug Information
```
Notepad++ v8.5.8   (64-bit)
Build time : Oct 15 2023 - 21:43:56
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : "C:\Users\mjols\Documents\mjork_website\mjork_website\failed_tests.txt" 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 10 Home (64-bit)
OS Version : 22H2
OS Build : 19045.3930
Current ANSI codepage : 1252
Plugins : 
    ColumnsPlusPlus (1.0.2)
    ComparePlus (1.1)
    CSharpPluginPack (0.0.1.4)
    CSVLint (0.4.6.5)
    EnhanceAnyLexer (1.1.3)
    HTMLTag (1.4.1)
    HugeFiles (0.4.1)
    JsonTools (6.1.1.10)
    mimeTools (2.9)
    NavigateTo (2.7)
    NppConverter (4.5)
    NppExport (0.4)
    NppLspClient (0.0.13)
    PythonScript (3.0.16)
    QuickText (0.2.5.1)
    XMLTools (3.1.1.13)
```

**Comment by rdipardo** [comment]
Duplicate of #8715, fixed in https://github.com/notepad-plus-plus/notepad-plus-plus/commit/bac903208c30ae5b73671ba05f4f0c5a1ef23b12

I guess your `stylers.xml` needs to be regenerated from a recent copy of `stylers.model.xml`. A freshly installed 8.6.2 release looks like this:

<img width="580" alt="npp-8 6 2-json-error-caret-line" src="https://github.com/notepad-plus-plus/notepad-plus-plus/assets/59004801/d448f6e7-20ec-47dd-8768-cd87204de3c5">

**Comment by molsonkiko** [comment]
Great! That is definitely a significant improvement over the previous coloring, and I am satisfied enough that I'll just close this now.

I *still* think that there's something to be said for changing the lexer a bit more to increase the loudness of the current line. __Maybe adding underlines or italics for the foreground?__
