### ISSUE TITLE
Blurry text with "Use Direct Write" enabled

### ISSUE THREAD

**Issue by u07** [notepad-plus-plus/notepad-plus-plus#14622]
### Description of the Issue
I've just updated. But hey, what da hell is this? The text is changing as I look at it, it is getting blurry, more blurry every second.

![image](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/20968145/e1a0feed-944e-4d3c-b44c-a5fad862d8b2)

### Debug Information
Notepad++ v8.6.2   (64-bit)
Build time : Jan 14 2024 - 02:16:00
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 7 Ultimate (64-bit)
OS Build : 7601.23964
Current ANSI codepage : 1251
Plugins : 
    mimeTools (3)
    NppConverter (4.5)
    NppExport (0.4)

**Comment by u07** [comment]
![image](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/20968145/a21571a2-b636-41b4-a5aa-415d802c1ac1)

**Comment by u07** [comment]
It's been fine a moment ago with the x86 version. But then I installed x64 to speed up a little. And voila, this.

**Comment by alankilborn** [comment]
_DirectWrite_ enabled is a new default with recent versions.
Don't like the effect?  Disable it.

>Still an issue, though?

No.

**Comment by u07** [comment]
Yeah, I definitely don't like the effect. And if not that topic, I would never know what to disable. 

>No.
Yeah, you're right. When a feature sometimes doesn't work as intended it should be called **a bug**. Issue sounds to vague.

**Comment by rdipardo** [comment]
> _DirectWrite_ enabled is a new default with recent versions. Don't like the effect? Disable it.
> 
> > Still an issue, though?
> 
> No.

It's actually a Scintilla bug: <https://sourceforge.net/p/scintilla/bugs/2344>

For [example](https://sourceforge.net/p/scintilla/bugs/2344/#9328):

![Bug-2344-DpiUnaware125.png](https://www.scintilla.org/DpiUnaware125.png)

**Comment by u07** [comment]
Scintilla-related, definitely. But not same bug (and how is it "closed"?). 

Cause my DPI is normal and my "blur" is actually dynamic, it changes with time.

**Comment by u07** [comment]
Like this:
![ice_video_20240121-023024__](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/20968145/5c0a1bfa-5e79-45b0-946e-c1cd94a3e31e)

**Comment by nyamatongwe** [comment]
> @rdipardo For [example](https://sourceforge.net/p/scintilla/bugs/2344/#9328):

That image isn't from a Scintilla release or even code from the repository. It was produced by running a proposed patch and led to  the rejection of that patch due to the poor quality image scaling.

**Comment by u07** [comment]
Okay, Neil Hodgson [says](https://sourceforge.net/p/scintilla/bugs/2344/?page=3#143d/42d2), it's unrelated to that DPI bug:

> The video appears to be drawing again over a previous draw without clearing and could be due to video driver capabilities. Try the alternative SC_TECHNOLOGY_DIRECTWRITERETAIN or SC_TECHNOLOGY_DIRECTWRITEDC options when calling SCI_SETTECHNOLOGY.

**Comment by u07** [comment]
I'd love to help solving this bug, but I don't feel able to compile NPP from scratch to test alternative options... At least, without additional help) Though I could patch the binary if you know the function and the param value that Neil is talking about.

**Comment by donho** [comment]
@u07 
Is it reproducible in v8.6.8?

**Comment by u07** [comment]
Seems to be fixed in v8.6.8. How did you do that?
