### ISSUE TITLE
TYPO: 'inaccessinble' in Buffer.cpp

### ISSUE THREAD

**Issue by Nagidrop** [notepad-plus-plus/notepad-plus-plus#14621]
### Description of the Issue

Typo on dialog title at lines 1376 and 1387 in [Buffer.cpp](https://github.com/notepad-plus-plus/notepad-plus-plus/blob/master/PowerEditor/src/ScintillaComponent/Buffer.cpp)

### Expected Behavior

Dialog title is 'File inaccessible'

### Actual Behavior

Dialog title is 'File inaccessinble'

### Debug Information

![Typo_inaccessinble](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/58417614/dc4757b3-1d7a-45a3-82f2-18acb3a05d28)

**Comment by donho** [comment]
https://github.com/notepad-plus-plus/notepad-plus-plus/commit/bb278b26fc9a772242e702d2fac40c18c6cc21b9
