### ISSUE TITLE
"In Selection" becomes unchecked on clicking "Replace All" 

### ISSUE THREAD

**Issue by Gilgamech** [notepad-plus-plus/notepad-plus-plus#14624]
### Description of the Issue
The behavior of the `In Selection` checkbox is highly inconsistent. Usually it is in the wrong mode, so I'm used to clicking the checkbox after opening the Replace window. I understand that there is other logic that attempts to determine the correct mode, and am willing to work around that.

And until recently, the checkbox would remain the same as long as the dialog box is open. Now, after highlighting and replacing text in a section with the checkbox checked, highlighting another section (and without closing or modifying the Replace dialog) causes the `In Selection` checkbox to become unchecked. But the UI doesn't update until it gains focus again, which occurs when I click the `Replace All` button. 

### Steps to Reproduce the Issue
1. Have a document with text in it. Highlight a multi-line section
2. Press `Ctrl+R` to open the Replace window and check the `In Selection` checkbox.
3. Highlight a section of text., and press `Replace All`. 
4. Highlight another section of text and press `Replace All`. 

### Expected Behavior
The replaceable text only within the selection would be replaced.

### Actual Behavior
The replaceable text throughout the document was replaced.

### Debug Information
Notepad++ v8.6.2   (64-bit)
Build time : Jan 14 2024 - 02:16:00
Path : C:\Program Files\n++\notepad++.exe
Command Line : "C:\repos\website\www\calc.md"
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 11 Home (64-bit)
OS Version : 22H2
OS Build : 22621.3007
Current ANSI codepage : 1252
Plugins : 
    AutoSave (1.6.1)
    ComparePlugin (2.0.2)
    mimeTools (3)
    NppConverter (4.5)
    NppExport (0.4)

I don't mind that the checkbox is usually in the wrong state. What I mind is that it changes state while the Replace window is open, and that its behavior continues to change. It seems as though Notepad++ is determined to always replace across the wrong set, necessitating a `Ctrl+Z`, re-check selection, re-check settings, and `Replace All` again. Which is an inefficient workflow.

**Comment by alankilborn** [comment]
Note: Step 2 should say `Ctrl+h`, not `Ctrl+r`.

---

I think setting this avoids the above problem:

![image](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/77065706/3b1bef77-70dd-45d6-a5e6-395a3a590843)

although, doing that may cause other problems with some different workflows (haven't thought about that too much).

**Comment by Gilgamech** [comment]
Yes, Step 2 should say `Ctrl+H`. 

In the above image, mine has 1024. I'm not sure of the impact of changing this setting. 

I suppose, as a feature request, a checkbox for "Disable auto-checking 'In-Selection'". Ultimately I want the checkbox to only change when I click it.

**Comment by alankilborn** [comment]
>Ultimately I want the checkbox to only change when I click it

For pure manual control:
![image](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/77065706/91d034df-18d1-486a-898b-12a44505566c)

Also described in user manual: https://npp-user-manual.org/docs/preferences/#searching

**Comment by Gilgamech** [comment]
Thanks for posting that. It didn't pop up when I clicked it on mine.

**Comment by alankilborn** [comment]
> It didn't pop up when I clicked it on mine.

You just hover to get the popup balloon; you don't click the button with the `?` on it.

**Comment by Gilgamech** [comment]
That's a very unusual design decision that doesn't fit with the rest of the application. Why have a one-off note that's contained within a hover element that resembles a button? Why not either just display this normally, or have the hover element be a button?  It feels like extra effort went into making this information hard to access. 

Feature request: Replace the hover element with box always displaying this text. It's too useful of a note to be hidden behind an unusual and awkward element.

**Comment by alankilborn** [comment]
>... doesn't fit with the rest of the application

There are several other buttons-with-hover like that throughout the application.
There's some limitation with having hover text appear, say, when you point to the edit box itself, so the `?` button is a UI compromise.

---

>Feature request: Replace the hover element with box always displaying this text. It's too useful of a note to be hidden behind an unusual and awkward element.

I'm fairly confident your changed feature request (which should have been a new and different issue) will be rejected.

**Comment by Gilgamech** [comment]
> There are several other buttons-with-hover like that throughout the application.

They're [Tooltips](https://learn.microsoft.com/en-us/windows/apps/design/controls/tooltips). Why isn't this also? 

> I'm fairly confident your changed feature request (which should have been a new and different issue) will be rejected.

While your advice is appreciated, your pessimism isn't.

**Comment by alankilborn** [comment]
>While your advice is appreciated, your pessimism isn't.

realism? :-)

---

>They're Tooltips. Why isn't this also?

If you think it is reasonably easy to do, go ahead and give it a shot as Notepad++ accepts user-contributed code changes.

**Comment by lukemim** [comment]
I'm still experiencing this problem in version 8.4.6 when "minimum size for auto-checking" is not 0: when I make a first replacement in selection and then select another text the checkbox appears to be still checked, but when I click replace all it gets unchecked and the replacement occurs even outside of the selection. Setting minimum size for auto-checking to 0 only works around this bug, but the bug is still there.

**Comment by alankilborn** [comment]
>I'm still experiencing this problem in version 8.4.6

I presume you mean 8.6.4

**Comment by alankilborn** [comment]
>when "minimum size for auto-checking" is not 0

So, what is the value you have set for this?

**Comment by lukemim** [comment]
the value that was there before I set it to 0 was 1024. The steps are the same as in the original description, it's the same bug

**Comment by Gilgamech** [comment]
> > when "minimum size for auto-checking" is not 0
> 
> So, what is the value you have set for this? Please give more detailed steps-to-reproduce the entire scenario you are seeing.

Could you stop harassing other users for making simple bug reports? You act like this is your castle but it's not. I'd report your comments as bullying if the option were available.

**Comment by alankilborn** [comment]
@Gilgamech said:

> Could you stop harassing other users for making simple bug reports?

Harassing??  I see it as attempting to solicit further information in order to replicate/understand the another user's scenario for a bug report.  @lukemim 's situation must be different from yours because you wanted "full manual control" and I provided instructions for how to obtain that.

>You act like this is your castle, but it's not.

Wrong on the first part of that, correct on the second.
@donho wears the crown around here.

>I'd report your comments as bullying if the option were available.

I just did it myself (by addressing donho).  He can decide if I'm a "bully" or not.
What I'm simply trying to do is fully understand user concerns about a feature I was involved in, and coded for.

Since you (Gilgamech) stopped adding to the original conversation, and went off on some tangent about hover tooltips, I presumed that the solution I gave you was satisfactory.

**Comment by Gilgamech** [comment]
> What I'm simply trying to do is fully understand user concerns about a feature I was involved in, and coded for.

You do this with the grace of a person swatting flies with a hammer

And thank you for ceding the point through your ad hominem attack. Beyond making me feel unwelcome in this open source project, and giving bad advice, you're making me want to change IDEs and stop recommending this software product. Is this intentional?

**Comment by alankilborn** [comment]
@lukemim Do you have anything more to say on this topic?

**Comment by lukemim** [comment]
thanks for creating #14897

I suppose a part of the problem is that the checkbox gets automatically checked or unchecked based on the selection size by default without any obvious indication - I had no idea such functionality is enabled by default. 

Besides that a good UX solution might be to have separate buttons for "replace all" and "replace in selection"
