### ISSUE TITLE
Wrong indexing of new tabs

### ISSUE THREAD

**Issue by fdarius2014** [notepad-plus-plus/notepad-plus-plus#1462]
When you open the program for the first time, the tabs start at new 0 and increase. If you close new 1, it starts from new 1 but If you close new 0 it will start from new 1 still.

**Comment by donho** [comment]
I do recall that I have treated such issue.
Update your Notepad++ to the latest version (v7.6.6).
If the issue persists, it's not even a cosmetic glitch, and I won't fix it.
