### ISSUE TITLE
In v8.6.2 (32-bit), when no text selection is made, Ctrl-C copies and Ctrl-X deletes the whole current line

### ISSUE THREAD

**Issue by vsl7** [notepad-plus-plus/notepad-plus-plus#14638]
Is there a workaround for this?

**Comment by CennoxX** [comment]
It's a feature, not a bug. Without selection the whole line is copied / cut.
To disable, see here: https://github.com/notepad-plus-plus/notepad-plus-plus/pull/14513

**Comment by vsl7** [comment]
@CennoxX Adding disableLineCopyCutDelete.xml in %APPDATA%\Notepad++ doesn’t solve this issue.

**Comment by CennoxX** [comment]
You're right, 8.6.2 removed this option. The changelog states, the empty file takes no effect, it worked for me.
@donho Is it still possible to disable Line Copy / Cut?

**Comment by donho** [comment]
"disableLineCopyCutDelete.xml" is canceled in v8.6.2
I'll see what I can do for this issue.

**Comment by pedroeloy21** [comment]
Hi, to help the users could this new feature be enabled/disabled in the GUI? 

PS: In my case I'm getting some "strange" pastes, because sometimes I miss the selection before doing Ctrl-C, and then when I try a paste on a new text selection e get a full line out of nowhere. Annoying.
