### ISSUE TITLE
[Enhancement/Feature] Add option to pin search/replace entries or stor/load favourite

### ISSUE THREAD

**Issue by GitMensch** [notepad-plus-plus/notepad-plus-plus#1463]
I'm using search/replace a lot. Depending on the actual file contents the actual search differs much, therefore the search history is not really helping.
What would help would be the suggested feature - often used entries could be pinned (=always stay in history) or be saved/load via favourites.

Thank you for this already marvellous editor!
Simon

**Comment by donho** [comment]
It's not an easy implemented feature, so it won't be implemented.

**Comment by GitMensch** [comment]
Thank you for coming back to this.

> It's not an easy implemented feature, so it won't be implemented.

Hm, in this case I think I should have split the FR. Pinning seems easy, but only if the used controls allow for this (or could easily be switched to a control allowing it, or if the control could be extended to a two-column drop-down with a "button" in the second column to pin/unpin.
From your note both seem to be not something that could be easily done.

@donho Are you sure that implementing load/save for the history

![draft of new buttons](https://user-images.githubusercontent.com/6699539/56080204-19f3df80-5dfe-11e9-848c-e33836116f9d.png)

would be hard to implement, too?
