### ISSUE TITLE
Selecting a backup directory and then saving the text file isn't saving to the backup directory

### ISSUE THREAD

**Issue by gut5** [notepad-plus-plus/notepad-plus-plus#14633]
### Description of the Issue
I have made a backup directory (bak) and selected it in Settings and I get the error in the screenshot when I try to save a test file.

### Steps to Reproduce the Issue
1. Create new text file called test 
2.  Press ctrl+s to save it
3.  Error

### Expected Behavior
Expected to get the test.txt.bak in the bak folder

### Actual Behavior
Error

### Debug Information
Notepad++ v8.6.2   (64-bit)
Build time : Jan 14 2024 - 02:16:00
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : "C:\Users\Guts\Documents\text-files\test.txt" 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 10 Education (64-bit)
OS Version : 22H2
OS Build : 19045.3930
Current ANSI codepage : 1252
Plugins : 
    mimeTools (3)
    NppConverter (4.5)
    NppExport (0.4)

![Screenshot 2024-01-24 184446](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/44514/bfab9402-6b73-4768-900e-7980191a703a)

**Comment by xomx** [comment]
Looks like you have set this in the Settings:

![npp-bak-problem](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/13075183/a3d3d5a3-3762-46a0-b982-cb233821632c)

If so, then the N++ tries to backup to the protected storage place "C:\\Program Files\\Notepad++\\bak\\", which is impossible without admin-rights ...

> Path : C:\Program Files\Notepad++\notepad++.exe

> Admin mode : OFF

**Comment by gut5** [comment]
Yes, that's correct. I thought it would use the folder as a variable in future documents so that it would always save under that folder in the hierarchy. Is there a way to do that?
I don't really want everything to be backed up to the same backup folder but I guess it could work for my purpose.

**Comment by xomx** [comment]
Sorry, there is the N++ [$(CURRENT_DIRECTORY)](https://npp-user-manual.org/docs/config-files/#userdefinedcommands) but unfortunately it cannot be used in the N++ Preferences like `$(CURRENT_DIRECTORY)\bak\`. There already is a similar request for using of these N++ specific variables in the settings - #9388 .

But you can use there Windows environment variables if you like, e.g. this is possible to use in the Custom Backup Directory:

`%TEMP%\bak\`

then in your %USERPROFILE%\AppData\Local\Temp\ folder will be created and used the bak-subfolder.

You can also add & use new Windows environment user/system variables and use them likewise.

![win-sysprop-envvars](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/13075183/ab1e5c57-aeff-4453-9748-f947aea22813)
