### ISSUE TITLE
Cut and paste in macro doesn't work properly

### ISSUE THREAD

**Issue by lrto** [notepad-plus-plus/notepad-plus-plus#14634]
### Description of the Issue
Since version 8.6.1, macros using cut and paste fail.

I was using versions 8.6.1 and 8.6.2, but I had to downgrade to 8.6, since macros were needed to a specific job and they were almost unusable.

### Steps to Reproduce the Issue

1. Start recording a Macro;
2. Cut (Ctrl+X) an entire line of text or just some part of a word;
3. Paste (Ctrl+V) it at a blank line at the end of the document;
4. Stop recording;
5. Put the caret at the beginning of another line of text and select Playback (Ctrl+Shift+P), in order to repeat the work.
6. You will see the content will NOT be pasted at the end of the document.

### Expected Behavior
The macro should work as expected. I've been using Notepad++ for many years, and have never seen this cut/paste macro issue.

### Actual Behavior
Cut and paste in macro doesn't work properly, as described above.

### Debug Information

I saw this issue extensively in Notepad++ v8.6.2 (64-bit). Is this really a bug? Is there any workaround?
(Meanwhile, I'll stick with v8.6)
Thanks!

**Comment by molsonkiko** [comment]
> 6\. You will see the content will NOT be pasted at the of the document.

- was it not pasted at all?
- if it was pasted, where?

**Comment by lrto** [comment]
> > 6. You will see the content will NOT be pasted at the of the document.
> 
>     * was it not pasted at all?
> 
>     * if it was pasted, where?

The content is not pasted. It doesn't work.

**Comment by molsonkiko** [comment]
@lrto 
Huh, yeah, I can replicate this.

The weird thing is that this bug doesn't apply to all cut/paste macros; it only seems to act weird when you cut and paste at the end of the document.

Try making a macro where you do the following:
1. select the three characters before the caret
2. Cut (Ctrl+X)
3. select the entire document
4. push the back arrow to move to the start of the document
5. Paste (Ctrl+V)

You should find that this macro works fine in 8.6.1 or 8.6.2 too.

But if I do the same macro, but hit the forward arrow after selecting the whole document to move to the end of the document (thus pasting at the end), the macro works in 8.5.8 but not in 8.6.1 or 8.6.2.

**Comment by lrto** [comment]
> @lrto Huh, yeah, I can replicate this.
> 
> ~The weird thing is that this bug doesn't apply to all cut/paste macros; it only seems to act weird when you cut and paste at the end of the document.~
> 
> Never mind, it's just a function of which version the macro was recorded in. That is, the same sequence of actions will generate a different macro depending on whether it was recorded in 8.5.8 or 8.6.2.
> 
> I would assume this issue is a result of [this commit](https://github.com/notepad-plus-plus/notepad-plus-plus/commit/3c4f0f9cb2f5ff858bb7f85f81fbb8f6cbd221f5), which was later rolled back by [this commit (I think)](https://github.com/notepad-plus-plus/notepad-plus-plus/pull/14569/files).
> 
> To expand: Let's look at a macro that cuts the two characters before the caret and moves them to the start of the document, one version from 8.5.8 and one from 8.6.2. The commands being executed are in the XML comments after each step of the macro.
> 
> **From 8.5.8:**
> 
> ```
> <Macro name="cut 2 chars before caret, move to start 8.5.8" Ctrl="no" Alt="no" Shift="no" Key="0">
>     <Action type="0" message="2305" wParam="0" lParam="0" sParam="" /> 
>     <Action type="0" message="2305" wParam="0" lParam="0" sParam="" /> 
>     <Action type="0" message="2177" wParam="0" lParam="0" sParam="" /> 
>     <Action type="0" message="2013" wParam="0" lParam="0" sParam="" /> 
>     <Action type="0" message="2304" wParam="0" lParam="0" sParam="" /> 
>     <Action type="0" message="2179" wParam="0" lParam="0" sParam="" /> 
> </Macro>
> ```
> 
> **From 8.6.2:**
> 
> ```
> <Macro name="cut 2 chars before caret, move to start 8.6.2" Ctrl="no" Alt="no" Shift="no" Key="0">
>     <Action type="0" message="2305" wParam="0" lParam="0" sParam="" /> 
>     <Action type="0" message="2305" wParam="0" lParam="0" sParam="" /> 
>     <Action type="0" message="2177" wParam="0" lParam="0" sParam="" /> 
>     <Action type="2" message="0" wParam="42001" lParam="0" sParam="" /> 
>     <Action type="0" message="2013" wParam="0" lParam="0" sParam="" /> 
>     <Action type="0" message="2304" wParam="0" lParam="0" sParam="" /> 
>     <Action type="0" message="2179" wParam="0" lParam="0" sParam="" /> 
> </Macro>
> ```
> 
> **It seems that in 8.6.2 (and presumably 8.6.1 as well), Ctrl+X is causing `MENUCOMMAND.EDIT_CUT` to be recorded in the macro _in addition to `SCINTILLAMESSAGE.SCI_CUT`_, which is all that is required to do the job.**
> 
> By the way, you can find the recorded macros in `%Appdata/Roaming/Notepad++/shortcuts.xml`, and you can [read about how to understand them here](https://npp-user-manual.org/docs/config-files/#macros)

Thanks for the response!

Yes, I always keep the shortcuts.xml file in Windows when manually updating (7z) Notepad++ , in order to preserve my macros.

That's interesting. It's weird that in the newer version a _different_ macro is being recorded...so the newer version clearly has a bug regarding this.

For now, I'm fine using the older version 8.6 in Windows, until a fix is made or a workaround is found.

(In another computer, where I'm using Linux + wine, unfortunately snap updated Notepad++ for this faulty v8.6.2, for my dispair. I'll check a way to downgrade it there, or perhaps I'll need to create macros with jEdit or vim for a while.)

**Comment by molsonkiko** [comment]
Before I submit a PR that I think will fix this, just letting people know that I think the fix is as simple as [commenting out this line](https://github.com/notepad-plus-plus/notepad-plus-plus/blob/c0eaf544a61d3f3a53ab5923af643c11a583749a/PowerEditor/src/NppCommands.cpp#L4196) and thus making `IDM_EDIT_CUT` un-macroable by default.

If anybody doesn't come up with some compelling reason *not* to do this in the next hour or so, I'm just going to submit my PR. suspect that a 2-character change to one file is a reasonably small code footprint :wink:
