### ISSUE TITLE
'Cut, Paste' pastes into also cut location

### ISSUE THREAD

**Issue by Fern99** [notepad-plus-plus/notepad-plus-plus#14645]
### Description of the Issue
'Cut, Paste' pastes into also cut location

### Steps to Reproduce the Issue

1.  Cut a text  on line X
2.  Paste into line Y

### Expected Behavior
Text has been pasted **ONLY** into line Y.

### Actual Behavior
Text has been pasted into line Y **AND** line X.

Note: noColumnToMultiSelect.xml in %APPDATA%\Notepad++\ does not seem to help.

8.6.2

https://github.com/notepad-plus-plus/notepad-plus-plus/assets/40309155/d535bc6a-c474-4b6c-a179-d80367b27401

**Comment by alankilborn** [comment]
Presume you are doing the cut with Ctrl+x and the paste with Ctrl+v ?

If so, are you releasing Ctrl after the cut and before clicking on line 27 to place the caret for the paste point?
If not, you need to release it.
Because otherwise you are placing a _second_ caret there (in addition to the one on line 32).  With a second caret, you do indeed correctly get two pastes.

**Comment by Fern99** [comment]
> Presume you are doing the cut with Ctrl+x and the paste with Ctrl+v ?
> 
> If so, are you releasing Ctrl after the cut and before clicking on line 27 to place the caret for the paste point? If not, you need to release it. Because otherwise you are placing a _second_ caret there (in addition to the one on line 32). With a second caret, you do indeed correctly get two pastes.



Cut and Paste actions are programmed into mouse buttons.
Whether cut and paste or ctrl+x and ctrl+v is programmed into the buttons, double paste happens.


If I press "esc" before pasting double paste does not happen.

If this issue does not happen with other users using cut and paste with mouse buttons, then it is only my problem.
If this issue is happening with other users who uses cut and paste programmed into mouse buttons, then it is happening with multiple users **_(think of a percentage of users using cut and paste from mouse buttons)_**.

An issue did not exist before 8.6 and still existing on 8.6.2

**Comment by alankilborn** [comment]
>(think of a percentage of users using cut and paste from mouse buttons)

I would imagine that's a very small percentage...

---

>Cut and Paste actions are programmed into mouse buttons.

How exactly?
With third-party (e.g. Logitech) software?
Which mouse?
Which buttons are these actions programmed to?

**Comment by Fern99** [comment]
If you think that is a small percentage, fine. (I do not know the percentage myself, but I would think that hoe much percentage of users are affected by removing the multiediting option)

Yes, with a third party software such as Logitech.
A trackball MX Ergo (also tried it on G603 mouse)
Slide middle button to left and right cut and copy, middle button click as paste.

This problem is because multiline is automatically enabled and noColumnToMultiSelect.xml in %APPDATA%\Notepad++\ does not seem to be helping (still cannot figure out why, unless something changed in 8.6.2 that stopped that file from working).

This means if a user cuts a text on line 50 and pastes it onto line 500, where line 50 **_IS NOT VISIBLE_**, user cannot even see it is double pasted. (Imagine the problems this can cause)

There is not a color change or flash something option that multilines are selected or multi carets are selected or an option to disable multiline completely.

This comes to the issue of how much percentage of users are affected by this.

If enabling multiline as a default option is so much important, maybe, there can be an option to disable multiline editing or noColumnToMultiSelect.xml may made to work at all times (TRUSTABLY), or any other better suggestion.

**Comment by alankilborn** [comment]
>Slide middle button to left and right cut and copy, middle button click as paste.

I'm wondering how the mouse software implements these.

**Comment by Fern99** [comment]
Mouse software probably implements these probably wrongly(key up - key down problem), but this is in all Logitech mouse software (and probably others too).

So, now, any shortcut assigned to any keyboard or mouse key (Yes, it happens when any shortcut with 'Ctrl' is implemented in keyboard keys too.) 'Ctrl' gets stuck till it is pressed again (or mouse is clicked somewhere else)

This is in any shortcut. Not just 'Ctrl+X', 'Ctrl+C','Ctrl+V'; it also happens with 'Ctrl+S', 'Ctrl+Alt+S' and 'Ctrl+Shift+S'.
(Therefore, using the 'Shift' shortcuts for cut and paste does not help either)

Creating any other shortcuts without 'Ctrl' from shortcut mapper does not help either because shortcuts assigned through shortcut mapper does not work with 'Find and Replace' window. 
(Therefore, we are limited to assigned shortcuts in Notepad++)

Shortly, 'Ctrl' key is used in so many shortcuts, most of the time, without an alternative without 'Ctrl'.

So, now, instead of a perfectly functioning option with a tick option (multiline), software is not usable because it is butchered and that option (even reversed, as 'disable multiline') is not available; neither through a tick option, nor through a file.

I am sure Notepad++ Settings has enough place for a tick option.

The problem does not happen only in cut, copy, paste.
It happens in all Save functions, and also every time something is copied, zoom changes.
So, any 'Ctrl' related shortcut is affected.

As an extra information, I started to use Shift shortcuts for cut and paste, but I am still having problems with copy and save functions every time.
If there was an option to disable multiline in the software, none of these problems would occur.
(They were not happening before 'multiline' was automatically enabled.)

Has the developer has thought about these problems after so many users has complained?
Does there really need to be so much insistence about a tick option? (Even as an unofficial option)

**Comment by alankilborn** [comment]
I present a couple of ways to disable multi-editing, which could solve the problem of this issue:

* https://github.com/notepad-plus-plus/notepad-plus-plus/issues/14611#issuecomment-1937720522
* https://github.com/notepad-plus-plus/notepad-plus-plus/issues/14611#issuecomment-1937725416

**Comment by Fern99** [comment]
> I present a couple of ways to disable multi-editing, which could solve the problem of this issue:
> 
> * [[Feature Request] Configurable multi-edit keys #14611 (comment)](https://github.com/notepad-plus-plus/notepad-plus-plus/issues/14611#issuecomment-1937720522)
> * [[Feature Request] Configurable multi-edit keys #14611 (comment)](https://github.com/notepad-plus-plus/notepad-plus-plus/issues/14611#issuecomment-1937725416)

Thank you very much for these.
