### ISSUE TITLE
Multi Edit resists escape after typing

### ISSUE THREAD

**Issue by krilbe** [notepad-plus-plus/notepad-plus-plus#14649]
### Description of the Issue

If you enable multi edit using Alt + Shift + arrow keys, and type something on multiple rows, I expect to be able to end multi edit mode by hitting Esc. But that doesn't work unless i move using arrow keys before I hit Esc. That makes the multi edit mode annoyingly "sticky". Please ensure that Esc ALWAYS ends multi edit mode and/or provide some other hotkey for that.

### Steps to Reproduce the Issue
1.  New document, add some blank lines.
2. Use Alt+Shift+Down or Up to start multi edit mode.
3. Type some text.
4. Hit Esc to end multi edit mode.
5. Notice that multi edit mode remains.
6. Hit arrow left to move the multi edit focus one character position to the left.
7. Hit Esc to end multi edit mode and notice that it is now ended.

https://github.com/notepad-plus-plus/notepad-plus-plus/assets/4610988/c9032a06-b8b3-470f-98cc-5128d98a470a

### Expected Behavior

I expect to be able to always reliable end multi edit mode with a single keystroke or shortcut key no matter what I did with multi edit mode before that keystroke. 

### Actual Behavior
Multi edit remains after hitting Esc, unless I use unshifted arrow keys before hitting Esc,

### Debug Information
Notepad++ v8.6.2   (64-bit)
Build time : Jan 14 2024 - 02:16:00
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 11 Pro (64-bit)
OS Version : 23H2
OS Build : 22631.3085
Current ANSI codepage : 1252
Plugins : 
    mimeTools (3)
    NppConverter (4.5)
    NppExport (0.4)

**Comment by project-flower** [comment]
[Editing | Notepad++ User Manual](https://npp-user-manual.org/docs/editing/)

> As soon as you make a caret movement that doesn’t intentionally keep you in column mode, your selection mode returns to the stream selection mode.

I hope this description will be updated as well.

**Comment by krilbe** [comment]
Nice with the options in the latest release, so multi edit can be disabled, but I do like the new abilitites of multi edit.

Fixing this bug would make it a lot more streamlined in my everyday use, since this bug forces me to do extra nonsense key strokes just to get out of multi edit mode.

**Comment by xomx** [comment]
You can try my patch with this x64 Release binary:
https://github.com/notepad-plus-plus/notepad-plus-plus/actions/runs/8598896815/artifacts/1393847482
