### ISSUE TITLE
Block select retained until mouse click

### ISSUE THREAD

**Issue by ksmith1787** [notepad-plus-plus/notepad-plus-plus#14641]
### Description of the Issue

The block select feature tails the cursor when moving it after modifications to text.

### Steps to Reproduce the Issue

1.  Perform a block select (Shift-Alt then move cursor with keys or mouse)
2.  Make edits as needed (add or remove text)
3. Move the cursor using the keys and not the mouse
4. The block select cursor moves with the keys even across lines, and subsequent typing causes text to be enter on lines not intended.
5. Only clicking with the mouse fixes this.

### Expected Behavior

After a block operation, any cursor movement clears the block select target multi-cursor

### Debug Information

Notepad++ v8.6   (32-bit)
Build time : Nov 23 2023 - 16:56:22
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 10 Enterprise (64-bit)
OS Version : 22H2
OS Build : 19045.3930
Current ANSI codepage : 1252
Plugins : 
    ComparePlugin (2.0.2)
    HTMLTag_unicode (1.3.5)
    JsonTools (4.0.0.1)
    mimeTools (2.9)
    NppConverter (4.5)
    NppExport (0.4)
    NppJavaPlugin (0.4)
    NppXmlTreeviewPlugin (2)
    XMLTools (3.1.1.13)

**Comment by anatoly77g** [comment]
It seems like block-select works like multi-select. If you do multi-select (Ctrl+left_mouse_click) and use arrow keys, multi-selection remains in effect, and this is very useful behavior.
I am not sure block-select behaving like multi-select is very useful, but in my experience, it's not very annoying either: just do a mouse click anywhere or press Esc to disable it.

**Comment by donho** [comment]
You can disable it in v8.6.3 via Preferences.
