### ISSUE TITLE
text

### ISSUE THREAD

**Issue by xivi1839** [notepad-plus-plus/notepad-plus-plus#14655]
When the subtitle text is opened, it displays garbled characters. Can this be solved?
See the picture.

download file：
https://drive.google.com/file/d/18oaUXd1jRdJpdAQ8AC57GkM5_nU_XJZR/view?usp=drive_link

![_20240201071742](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/24610024/6e1c0e8f-1286-4e6b-aab9-9620fc35e25f)

**Comment by alankilborn** [comment]
Fill out the issue template in its entirety, or you risk closure of your issue without action.
