### ISSUE TITLE
Stop view jumps when mouse selecting a long line

### ISSUE THREAD

**Issue by KleinMuci** [notepad-plus-plus/notepad-plus-plus#14658]
### Description of the Issue

Every time you try to select a long line with the mouse you need to be very careful to not accidentally send your cursor above or below it. If that happens and the adjacent line is shorter than the line you're selecting, the view jumps on it and the selection stops.

### Steps to Reproduce the Issue

1. Add a long line of text that requires you to scroll horizontally to fully view it. Make it extra long.
2. Add two other shorter lines above and below it that don't require you to scroll horizontally to fully view them.
3. Try to fully select the long line with the mouse and "accidentally" move your cursor above or below it.

### Expected Behavior

Not sure what would be the right behavior to have but a crude idea is to allow the selection to happen without the view jump. Or maybe delay it to allow time for the user to correct its mistake. 

### Actual Behavior

The screen shifts to the adjacent line getting selected.

### Debug Information

Notepad++ v8.6   (64-bit)
Build time : Nov 23 2023 - 16:58:44
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 10 Pro (64-bit)
OS Version : 1909
OS Build : 18363.1556
Current ANSI codepage : 1252
Plugins : 
    mimeTools (2.9)
    NppConverter (4.5)
    NppExport (0.4)

**Comment by alankilborn** [comment]
There really is no "cure" for this; suggestions are:

* select via keyboard instead of mouse
* _Enable virtual space_ in the settings (which prevents the "jump" but its other effects aren't always desired)

**Comment by KleinMuci** [comment]
@alankilborn, I enabled virtual space and at first glance looks like it is everything I wanted. What are the undesired effects?

**Comment by alankilborn** [comment]
>What are the undesired effects?

Well, your caret can now be _anywhere_, so if it is way off to the right of existing characters on a (shorter) line, and you start typing, you get an instant fill-with-space, from the end of the short line to the current caret location.

Some people don't like this; most want to confine their caret to where the existing text is.

If you are satisfied with the solution proposed, please close this issue.

**Comment by KleinMuci** [comment]
@alankilborn, ah! I see. Before I close this, is there any way to not have that behavior? Basically not allowing writing if there is only virtual space around the caret? As it can be understood from my question, I'm only looking for a way to make selection easier so wouldn't be interested in writing capabilities. I guess I can settle for this if not but thought I'd ask before anyway.

**Comment by alankilborn** [comment]
> not allowing writing if there is only virtual space around the caret?

Not in Notepad++ itself.
However, if you can use a scripting plugin, e.g. PythonScript, something could be scripted to prevent the "typing" case.

**Comment by KleinMuci** [comment]
I see. Hopefully in the future we can have a better overall native experience on this matter. Thank you for your fast replies! I'm closing this issue here.
