### ISSUE TITLE
spacing slightly off in Windows 11 (?)

### ISSUE THREAD

**Issue by nr1995** [notepad-plus-plus/notepad-plus-plus#14656]
Hi, noob here.
I noticed something funny when I connected a Windows 11 PC
into the same monitor my Windows 10 PC used to be connected to.

The first thing I noticed was that in some of my files,
I'd lined everything up neatly with tabs,
but when viewed in Windows 11,
about 2% of those lines which were all lined up neatly,
were now not lined up neatly, despite the number of tab characters not having changed.
In about 2% of cases, I'd have to add an extra tab for thingsto be lined up again.
This suggests a very slight change in width from before.

And yes, before anyone says, I've gone through Style Configurator,
and absolutely everything is set indentically to the way it was on the Windows 10 PC.
(I'm using the font Verdana Pro, bold, size 7, but regular Verdana is the same.)

I then had an idea to enable visible whitespace characters,
and just hold down on the space button, entering dozens of space characters,
just to see if there was any misalignment in Windows 11,
and sure enough, this is what I saw:
![image](https://i.imgur.com/XbMijom.png)

On the Windows 10 PC, the spaces are uniformly spaced,
and not bunched in groups of 5 or 6 as you can see here.

What do you guys think of this?

**Comment by nr1995** [comment]
@mpheath 
I don't think you read my issue properly.

**Comment by xomx** [comment]
@nr1995 
Did you use the same N++ version both on the Win10 and Win11?
Currently there has been a N++ default setting change, which could influence this, try to experiment with the Settings > Preferences > MISC. > Use DirectWrite.

Anyway, such spacing and kerning issues could be influenced e.g. by different graphics card drivers too.

**Comment by nr1995** [comment]
> @nr1995 Did you use the same N++ version both on the Win10 and Win11? Currently there has been a N++ default setting change, which could influence this, try to experiment with the Settings > Preferences > MISC. > Use DirectWrite.
> 
> Anyway, such spacing and kerning issues could be influenced e.g. by different graphics card drivers too.

Yes!  It's a DirectWrite issue!  Man you're good at this!
I'm so tired of posting issues online and getting responses like the one above,
i.e. like they're written by an AI from 2005.
When I push out a bunch of visible space characters now, they're all uniform and evenly spaced.
This suggests to me that DirectWrite still needs some work.
What do you think?
And thanks!

**Comment by xomx** [comment]
> This suggests to me that DirectWrite still needs some work.
> What do you think?

This is maybe suitable for a bug report to the underlying editor component Scintilla:
https://sourceforge.net/p/scintilla/bugs/

You can ask them what do they think about it (you can put there a link to this N++ issue as well).
Or maybe there is already something similar there, IDK.

**Comment by nr1995** [comment]
> > This suggests to me that DirectWrite still needs some work.
> > What do you think?
> 
> This is maybe suitable for a bug report to the underlying editor component Scintilla: https://sourceforge.net/p/scintilla/bugs/
> 
> You can ask them what do they think about it (you can put there a link to this N++ issue as well). Or maybe there is already something similar there, IDK.

Would you mind terribly to just post the bug report for me?
I don't seem to speak the same language as the experts around here,
and if I don't sound like I know what I'm talking about, 
it's far less likely they'll take the issue seriously.
If you don't have the time or can't be bothered I totally get it.

**Comment by xomx** [comment]
https://sourceforge.net/p/scintilla/bugs/2429/

**Comment by nr1995** [comment]
> https://sourceforge.net/p/scintilla/bugs/2429/

Yeah v8.6.2 ! (64-bit)
Windows 11 (23H2)
Verdana Pro (Bold, size 7) (that screenshot is default zoom, i.e. really small, but blown up)
1440p resolution

**Comment by xomx** [comment]
@nr1995 
So this is more of a DirectWrite feature than a bug, I am copying the Scintilla's author answer here:
`DirectWrite uses fractional positioning and a space in 7pt bold Verdana Pro is around 3.19 pixels wide. Thus there are 3 pixels for most space dots and an extra pixel after 5 or 6 spaces once the fractions have accumulated to a whole pixel.`

I recommend closing of this issue.

**Comment by nr1995** [comment]
> @nr1995 So this is more of a DirectWrite feature than a bug, I am copying the Scintilla's author answer here: `DirectWrite uses fractional positioning and a space in 7pt bold Verdana Pro is around 3.19 pixels wide. Thus there are 3 pixels for most space dots and an extra pixel after 5 or 6 spaces once the fractions have accumulated to a whole pixel.`
> 
> I recommend closing of this issue.

Yeah I read it.
That's a bit unfortunate, because I like the text really small to see as much as possible at once.
I write a lot in Chinese, especially for my work,
and with DirectWrite, Chinese looks just... wow... completely night and day better.
And not just in its rendering but in its alignment too.
A Chinese native would consider the top text unreadable in that picture.
However, I do think it messes just **_slightly_** with the kerning of the roman alphabet,
which for all the Chinese writing I do, is still 95% of what I'm looking at any given day.
Just enough for me to not want to turn DirectWrite on.
![image](https://i.imgur.com/XsYy2yA.png)
Awkwardly caught between past and future again.  How annoying :)
Anyway thanks again for your help.
