### ISSUE TITLE
Notepad++ hangs when changing open file while printer preferences dialog open

### ISSUE THREAD

**Issue by Zweater** [notepad-plus-plus/notepad-plus-plus#1466]
**Detailed explanation:**
Notepad++ hangs when printing a file (Press CTRL+P), opening the printer preferences dialog, then changing a file which is open. You then get a dialog "This file was modified by another program, would you like to reload it?". You can say Yes, but the print dialog then no longer works. Because this dialog is opened in modal mode, you can no longer access the Notepad++ interface, so for the operator it "hangs".

**Operating System version**
Windows 7 Enterprise, Service Pack 1

**Notepad++ version**
Build time Jan 10 2015, 17:20:21

**List of installed plugins (if it is related to a plugin)**
N/A

**Comment by Zweater** [comment]
I tried reproducing the issue at another workstation, there it doesn't reproduce.
Tried with Notepad++ build time Dec 10 2015 - 01:11:37 (v6.8.8) on Windows 8.1 Pro.

**Comment by donho** [comment]
I believe this issue has been fixed since long time ago.
Update your Notepad++ to the latest version (v7.6.6).
If the issue persists, please create a new issue for it.
Thank you.
