### ISSUE TITLE
Notepad++ Update popup window does not indicate the name of the software being updated

### ISSUE THREAD

**Issue by Evil-E242** [notepad-plus-plus/notepad-plus-plus#14668]
### Description of the Issue
The Notepad++ Update popup window (for updating to v8.6.2) has no indication whatsoever what software application is about to be updated, this is very confusing.

### Steps to Reproduce the Issue
1.  open Notepad++
2.  check out the small "Update" popup window

### Expected Behavior
Please include the application name in the popup window title, perhaps also include the default app icon.
Maybe also include the application name in the popup window body text.

### Actual Behavior
A small popup window appears informing that an update is about to be installed without any indication whatsoever what it is about to update.

**Comment by alankilborn** [comment]
![image](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/77065706/27024aff-51ae-43c0-81b3-8548f8a0d298)

It really isn't all that unclear to a user, as it pops up right after Notepad++ is launched.  But, really, it _could_ and _should_ also say "Notepad++" on it somewhere...

I'd suggest that an appropriate title bar change would be to use: `Update available for Notepad++`

**Comment by donho** [comment]
I'll see what I can do about it.
