### ISSUE TITLE
Performing line operations on large files leads to data loss

### ISSUE THREAD

**Issue by ericmc2** [notepad-plus-plus/notepad-plus-plus#14672]
### Description of the Issue

I was trying to sort and remove duplicate lines from a CSV file with ~1.8 million lines (70 MB of data).  Unfortunately, both commands lead to significant data loss. I only get around 50-70k lines of output. For comparison: Doing sort and uniq in a shell leaves me with ~1.7 million lines.

Possibly related to #7714.

### Steps to Reproduce the Issue

1. Open a large file with millions of lines
2. Run "Sort Lines Lexicographically" or "Remove Duplicate Lines"
3. Check the resulting number of lines

### Expected Behavior

Perform the line operations as expected or display an error message if the file is too large to be handled correctly.

### Actual Behavior

Data is lost unless the user carefully checks the result before saving.

### Debug Information

Notepad++ v8.6.2   (64-bit)
Build time : Jan 14 2024 - 02:16:00
Path : D:\Programs\Notepad++\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : ON
Cloud Config : OFF
OS Name : Windows 10 Pro (64-bit)
OS Version : 22H2
OS Build : 19045.3930
Current ANSI codepage : 1252
Plugins : 
    ComparePlugin (2.0.2)
    HexEditor (0.9.12)
    mimeTools (3)
    NppConverter (4.5)
    NppExport (0.4)
    NPPJSONViewer (2.0.6)
    XBrackets (1.3.1)

**Comment by alankilborn** [comment]
@ericmc2 

Can you provide a sample file illustrating the problem?

**Comment by ericmc2** [comment]
I tried generating a big file to illustrate the problem, but I fail to reproduce it. So, it seems to be related to the content in multiple files I work with (unfortunately, I can't post them). I'll have to do some more experimenting to find out what exactly causes the problem.

Sorry about that. I'll close this issue for now as it doesn't seem to be caused by the size alone.
