### ISSUE TITLE
Notepad++ cannot save a file

### ISSUE THREAD

**Issue by wimgielis** [notepad-plus-plus/notepad-plus-plus#1467]
Hello,

I have a file called D:\Wim\Consultancy\Geldtemplate\do do.log
It only contains the word "test". I open it in Notepad++, change the file contents, save and the date in Windows Explorer does not change. The menu icon indicates that the file is saved.
The file date (last modified) remains at Febr. 7, 2016, 12.02 PM (noon + 2 minutes). Now we are Februari 16 so this does not make sense at all.
A txt file can be saved and modified without problem.
Is this a bug ?

**Comment by donho** [comment]
Update your Notepad++ to the latest version (v7.6.6).
If the issue persists, please create a new issue for it.
Thank you.
