### ISSUE TITLE
NotePad++ Macro Cut-Paste Bug

### ISSUE THREAD

**Issue by JediSQL** [notepad-plus-plus/notepad-plus-plus#14695]
### Description of the Issue
I have found what I believe to be a bug during playing back a macro that uses cut and paste.

Sample text:
1111
2222
3333
4444
5555
6666
7777
8888

### Steps to Reproduce the Issue
Copy and paste the Sample text into a new text file.
Put cursor at the beginning of Line 3.
Start macro recording.
Tap Shft-Down three times to select lines 3, 4 and 5; leaving the cursor at the beginning of line 6.
Tap Ctrl-X to cut three lines of selected text.
Tap Ctrl-Home to put the cursor at the beginning of the file.
Tap Ctrl-V to paste the cut text at the beginning of the file (lines 3, 4 and 5 have been moved to the top of the file).
Stop macro recording.
Copy and paste the Sample text into another new text file.
Put cursor at the beginning of Line 3.
Playback the macro.

### Expected Behavior
I would expect lines 3, 4, and 5 to be moved to the top of the file while all other lines remain as they were.

### Actual Behavior
Lines 3, 4, and 5 disappear, and line 6 gets moved to the top of the file.

It seems that when "cut" occurs during macro playback, it happens twice:
1: on the selected text,
2: on the line where the cursor is after the first cut, discarding the text from the first cut.

### Debug Information
Notepad++ v8.6.2   (32-bit)
Build time : Jan 14 2024 - 02:18:41
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : G:\My Drive\Notepad++
OS Name : Windows 10 Enterprise (64-bit)
OS Version : 22H2
OS Build : 19045.3930
Current ANSI codepage : 1252
Plugins : 
    JsonTools (5.6)
    mimeTools (3)
    NppConverter (4.5)
    NppExport (0.4)
    NppFavorites (1.0.0.1)
    SpellChecker (1.3.3)
    XMLTools (3.1.1.13)

**Comment by lrto** [comment]
The macro feature is unfortunately buggy in versions 8.6.1 and 8.6.2, and we have already mentioned it here:

[https://github.com/notepad-plus-plus/notepad-plus-plus/issues/14634](url)
[https://github.com/notepad-plus-plus/notepad-plus-plus/pull/14613](url)

There's a pull request and a fix will probably be done for the next release.

I suggest you to downgrade to 8.6 for now (that's what I did), or wait for the next version.

**Comment by donho** [comment]
https://github.com/notepad-plus-plus/notepad-plus-plus/commit/91074da46d2d0110b151e8d31aeb4b872ebaf77c
