### ISSUE TITLE
Ctrl+LeftClick shortcut : select word

### ISSUE THREAD

**Issue by jamesford42** [notepad-plus-plus/notepad-plus-plus#1469]
In visual studio a very very frequently used shortcut is control+leftclick to select the clicked 'word'. This is the same behavior as double clicking at that location. 

As a programmer you do a lot of 'select this term, replace with new term by typing over it'. It's not that double clicking doesn't work, its just much more awkward operation to do than holding down control. 

Seems to me this could be the default behavior when 'multi line editing' is turned off. 

...and then when my brain reflexively tries to do control+leftclick word selection when i switch between visual studio and notepad++... it would actually work!  This 'accident' happens at least once every day of my life...

**Comment by 2chg** [comment]
This feature request seems to be (kinda) implemented by now. If I ctrl+click a word, the whole word ist being selected. Unfortunately this happens also if multi-editing is activated (which I like to use often!), what renders the mutli-editing feature unusable for me most of the time.

I'd like to suggest to activate the ctrl-click-word-selection feature only when mutli-editing is disabled, as proposed by @jamesford42

**Comment by donho** [comment]
Use Ctrl+← Left to move caret to the beginning of the word. Then press Ctrl+Shift+Right →. The word will be highlighted.

**Comment by AndersBillLinden** [comment]
I find it very useful to be able to ctrl-left click to select a word and find that I will not do that in notepad++.

**Comment by AndersBillLinden** [comment]
I also find it useful to select a word just by ctrl+left click on it. It will make editing a lot faster compared to double clicking. Another feature that I appreciate in other editors is to ctrl+left click+drag to select a number of whole words.

**Comment by sasumner** [comment]
>select a word just by ctrl+left click on it. It will make editing a lot faster compared to double clicking

Please explain how ctrl+lclick could possibly be faster than double-click.

>Why is this issue closed?

Author declined the suggestion.

**Comment by AndersBillLinden** [comment]
It is faster to copy text because ctrl and left click will be a simultanous operation. It does not seem to be a lot faster if you did not try it, but it really is.
