### ISSUE TITLE
DPI scaling for QVGA displays

### ISSUE THREAD

**Issue by terado** [notepad-plus-plus/notepad-plus-plus#147]
I've just received a Lenova Yoga 3 with QVGA display - after loading Notepad++ the toolbar shows very small. My understanding is that if applications have not used DPI scaling then it will not scale properly for higher resolutions. Now these displays are becoming popular it would be worth checking.

**Comment by tushevorg** [comment]
+1 request

**Comment by h-h-h-h** [comment]
Notepad++ seems to scale, but the icons don't go along with that. See issue https://github.com/notepad-plus-plus/notepad-plus-plus/issues/568.

**Comment by ThePadawan** [comment]
+1
