### ISSUE TITLE
Lost my last session (all my temporary files are not reopened)

### ISSUE THREAD

**Issue by ner00** [notepad-plus-plus/notepad-plus-plus#14707]
### Description of the Issue
Losing last session when reopen Notepad++ 

### Steps to Reproduce the Issue
Notepad++ lost the session when it is opened.

### Expected Behavior
The opened files in the last session are reopened.

### Actual Behavior
Only the empty document "new 1" is opened.

### Debug Information
```
Notepad++ v8.6.4   (64-bit)
Build time : Feb 20 2024 - 00:12:59
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 10 Pro (64-bit)
OS Version : 22H2
OS Build : 19045.4170
Current ANSI codepage : 1252
Plugins : 
    ComparePlus (1.1)
    mimeTools (3.1)
    NppConverter (4.6)
    NppExport (0.4)
```

**Comment by alankilborn** [comment]
I guess you should have saved your files.

**Comment by ner00** [comment]
@alankilborn Yeah, for sure. Get fucked.

**Comment by ner00** [comment]
@donho I understand that this wasn't the best way to go about this issue, and if you prefer I can open a new one or "merge" into an open issue covering this issue, but this keeps happening about 2 or 3 times a month.

Initially I thought this was maybe due to some old cache of Npp backups, but since then I cleaned the cache folder and, as before, everything looked good for around a couple weeks, yet today I open Npp and again it unloaded all opened/unsaved files (don't recall if any saved files were loaded, might have been). The backups are still available in `AppData/Roaming`.

OS is Win10, what additional details would be useful? Should I uninstall Npp completely and try from scratch?

I don't seem to run into this issue at work, and it's also up to date and same OS, so maybe there is something else?

**Comment by donho** [comment]
@ner00 
Sorry for your lost data. 

Could you please describe what was happening for these 3 times of data losing:
1. Is it due to Windows Update forcing OS restart when Notepad++ was opened?
2. Is it due to the power outrages when Notepad++ was opened? 
3. Or you just shutdown your PC normally without existing Notepad++?

As well, how was your data losing situation:
1. When you start Notepad++, all your files opened last time in Notepad++ are not reopened automatically in Notepad++? (so you lost your last session)
2. When you start Notepad++, all your files opened last time in Notepad++ are reopened automatically in Notepad++, but one or more files are empty or filled with NUL characters, instead of the content you typed?

Finally, could you provide your Debug Info here (via menu `?->Debug Info...`)?

**Comment by ner00** [comment]
@donho Thanks for the reply.
Fortunately no data was ever lost since Npp was doing the background backup normally (`%AppData%\Notepad++\backup`).

On your first question: I can't give a straight answer because I don't recall how Npp was closed before I noticed the issue, but so far I have not found a pattern. My computer never crashed nor lost power, but it is probable that Npp was often forcibly closed by a scheduled or intentional kernel power event (shutdown or restart); although, if that was the root cause I imagine I would experience this issue more frequently.

On your second question, the first case is what I experienced, suddenly Npp lost the session (didn't reopen last opened files or backups) and just had a `new 1` empty file (although the data was ok in the backups folder for the files that hadn't been saved).

At this time, I have uninstalled Npp with the aid of Revo Uninstaller to try to clean any old setting or registry key as best as possible, I then restarted and reinstalled the latest version (basically the same as it was, but a clean slate). It has only been 3 days since, but so far it hasn't happened again.

As for the debug info:
```
Notepad++ v8.6.4   (64-bit)
Build time : Feb 20 2024 - 00:12:59
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 10 Pro (64-bit)
OS Version : 22H2
OS Build : 19045.4170
Current ANSI codepage : 1252
Plugins : 
    ComparePlus (1.1)
    mimeTools (3.1)
    NppConverter (4.6)
    NppExport (0.4)
```

If it happens again, I'll be sure to chime in again. And in the meantime, should I keep an eye on `session.xml` for possible deletion by some accidental or third-party software? If that's the file responsible, maybe I should try and monitor it somehow?

Thanks.

**Comment by donho** [comment]
@ner00 
Thank you for all the information you have provided.
One last demanded stuff: Could you provide the screenshot of your Preference dialog Backup section please?

**Comment by ner00** [comment]
@donho Not a problem.
PS: bear in mind that I uninstalled/reinstalled Npp 4 days ago, the only settings that should fall outside the defaults are the theme (Obsidian) and plugin ComparePlus v1.1, but that's been like that on every system I use, including the home computer and only that one gave me this issue a few times before.
Thanks!

![image](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/2269603/d4437bed-7e3c-4d20-ba03-2fb058864a27)

**Comment by ner00** [comment]
It happened again. 
`session.xml` vanished and it's not that it was empty, it was gone from the folder altogether, it only reappeared (blank) after I closed Npp - Npp was actually open at the time that I noticed the missing files.

Event Viewer doesn't show anything of note, with the exception of a Dell service named `DSAService` which also employs a file named `session.xml`, located in `C:\ProgramData\Intel\DSA\Data`. As far as I know, that Dell service has existed since forever in my computer, part of Dell's Support Assist service. I don't know if that service could recently be deleting the session file in `%AppData%` for some unknown reason.

I have been using a tool to backup my Npp `session.xml` daily since this problems started, so I restored that file from the backup and everything was normal (last modification was 3 days ago). I'm still puzzled as to what is happening with Npp session file being wiped for no apparent reason. For the time being I need to rely on a third-party backup of that file because I can't understand how it gets "deleted".

**Comment by donho** [comment]
@ner00 
Could you provide the Debug Info of you v8.6.5 please?

**Comment by ner00** [comment]
@donho
Sure, although the last issue was still on v8.6.4. 
I updated to v8.6.5 around Sunday and haven't experienced the issue again (yet).

```
Notepad++ v8.6.5   (64-bit)
Build time : Mar 29 2024 - 17:04:43
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
Periodic Backup : ON
OS Name : Windows 10 Pro (64-bit
OS Version : 22H2
OS Build : 19045.4170
Current ANSI codepage : 1252
Plugins : 
    ComparePlus (1.1)
    mimeTools (3.1)
    NppConverter (4.6)
    NppExport (0.4)
```

**Comment by ner00** [comment]
Some good news, at last!

Notepad++ v8.6.5 solves my problem, but not because the previous versions were its cause... but rather due to the implementation of `session.xml.inCaseOfCorruption.bak` to recover from a corrupt or missing session.

Using Windows SACL to audit/monitor `session.xml` interactions finally paid off, and the offender is a third-party app. Below is the Windows Event that logged the deletion of `session.xml` last night (`Event Time: 2024-04-12T21:05:21.8234573Z [UTC+01:00]`):
```
An attempt was made to access an object.

Subject:
	Security ID:		SYSTEM
	Account Name:		DESKTOP-S4VK9SM$
	Account Domain:		WORKGROUP
	Logon ID:		0x3E7

Object:
	Object Server:		Security
	Object Type:		File
	Object Name:		C:\Users\ner0\AppData\Roaming\Notepad++\session.xml
	Handle ID:		0xc10
	Resource Attributes:	S:AI

Process Information:
	Process ID:		0x4660
	Process Name:		C:\Program Files\Dell\SupportAssistAgent\SRE\SRE.exe

Access Request Information:
	Accesses:		DELETE

	Access Mask:		0x10000
```

Dell's SupportAssist has been in my system forever, but it was updated January 17th 2024, which is just a couple weeks or so before I started having this issue of losing Npp's session.

I looked a bit deeper into this. 
I started by opening SupportAssist's interface and checked the history, there I found the following actions:

![image](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/2269603/62c654f2-7f97-4052-a580-57a94a655521)

In my attempt to find more concrete details, I ended up finding logs in `C:\ProgramData\Dell\SupportAssist\SRE\ExtendedLogs`, there were two log files from last night, their naming scheme is in the form of a GUID prefix, followed by two suffixes and date/time: 

- `_ScanDiskCleanerResult_2024_04_12_22_05.txt`
- `_FixedDiskCleanerResult_2024_04_12_22_05.txt`

Both of these log files contain this specific line (verbatim):
```c:\users\****\appdata\roaming\notepad++\session.xml, 25,36 kb, 1, noteplusplus, application```

I have no clue why or how SupportAssist started "cleaning" files that it clearly doesn't understand their purpose, sloppy management at Dell being my best guess. I don't even care for their cleaning routine, I just have it for the system drivers and BIOS updates.

I am not entirely sure how to disable the cleanup job, for now I went to SupportAssist's `Settings > Scans and optimizations` where there are scheduled scans for various things, one of which is `Test system performance` which includes a on/off toggle for `Automatically boost performance, optimize network settings, and remove viruses and malware` - I disabled this hoping that it stops doing weird crap like deleting Npp's session. Contacting Dell to try to solve this seems futile, there are forum threads in their community about the aggressive cleanup job in they have gone unanswered for years.

This is it, I seem to have my issue resolved one way or another. Sorry for the long post.

Thanks for the support!

**Comment by xomx** [comment]
@ner00 
Good job!

This reminds me of #14661 , just another example of a short-sighted approach. I am guessing that someone at Dell just needed to delete their "session.xml" file as part of some maintenance task and used a method to do so that probably also deletes such external app files...

Anyway, it is also good to know that the N++ "session.xml.inCaseOfCorruption.bak" safety works as it should, thanks for the report.

**Comment by donho** [comment]
> Anyway, it is also good to know that the N++ "session.xml.inCaseOfCorruption.bak" safety works as it should, thanks for the report.

I didn't see @ner00 has mentioned this part.
@ner00 Can you confirm your session has been restored to n-1 while you restart Notepad++ ?

**Comment by xomx** [comment]
@donho 

> Notepad++ v8.6.5 solves my problem, but not because the previous versions were its cause... but rather due to the implementation of `session.xml.inCaseOfCorruption.bak` to recover from a corrupt or missing session.

**Comment by donho** [comment]
@xomx 
It was a good code review from you - I didn't even think of this part after doing the PR. Congrats!

BTW, for the next users who have lost session issue, it may be good to get the info of their hardware - at least to know if DELL SupportAssist is installed.

Thank you @ner00 for all these infos!

**Comment by ner00** [comment]
@donho @xomx Thanks again for following up.

As quoted above, I can confirm that a few hours before I noticed the root of my issue, n-1 or `session.xml.inCaseOfCorruption.bak` had already kicked in without me even noticing that the original session had been deleted by SupportAssist, I only noticed it because I opened Event Viewer and checked my filtered logs.

So it appears that the session recovery functionality is extremely solid, so much so that had I not "fixed" it on my end, it would have solved the problem seamlessly for about 99.99% of the cases.

**Comment by xomx** [comment]
@donho @ner00 
There is probably another victim of this Dell SW: https://github.com/notepad-plus-plus/notepad-plus-plus/issues/14781#issuecomment-2054220157

**Comment by xomx** [comment]
Quick fix of this issue could be renaming the N++ "session.xml" e.g. to "npp-session.xml".

But I am afraid that the "session.xml" has been with us for too long, so changing it might cause some regression/inconvenience for people or external SW expecting the old name.

**Comment by ner00** [comment]
I actually had thought about suggesting a rename to the session file, but refrained because where does it end? This is just a horrible implementation by Dell. 

In any case, you (devs) are the ones to be able to gauge the pros and cons, the only pro at this moment is catering to unfortunate Dell users that have SupportAssist v4 installed.

**Comment by donho** [comment]
> but refrained because where does it end? This is just a horrible implementation by Dell.

I couldn't agree more. 
Renaming file is just a workaround, making Dell fix their lamentable bug is the solution.
I'll try to ping Dell via Twitter very soon. Hope they will be reactive.

**Comment by xomx** [comment]
And another affected user: https://github.com/notepad-plus-plus/notepad-plus-plus/issues/14976#issuecomment-2055603118

**Comment by ner00** [comment]
Probably a waste of time, but I posted about this on [Dell Community forum](https://www.dell.com/community/en/conversations/supportassist-for-pcs/supportassist-v4-cleanup-deletes-sensitive-data/661d48d8fcb3f754c1d59938)

**Comment by xomx** [comment]
On a funnier note, it seems that I can see through a millstone and my mountain was not just a molehill ;-)

> IDK if it is just me, but I seem to be seeing an increase in the user reports of losing the session file list these days, e.g.:
https://github.com/notepad-plus-plus/notepad-plus-plus/issues/14870#issuecomment-2024017117

**Comment by donho** [comment]
@ner00 
> Probably a waste of time, but I posted about this on [Dell Community forum](https://www.dell.com/community/en/conversations/supportassist-for-pcs/supportassist-v4-cleanup-deletes-sensitive-data/661d48d8fcb3f754c1d59938)

Hope not. I have tweeted here:
https://twitter.com/Notepad_plus/status/1779936290709930025

Let's wait & see.

**Comment by xomx** [comment]
Another user case, this time a direct verification by executing the Boost performance task in DELL SupportAssist for Home PCs in 4.0.2 version:
https://github.com/notepad-plus-plus/notepad-plus-plus/issues/15010#issuecomment-2061019860

**Comment by donho** [comment]
@ner00 
Do you have any news from DELL for this issue?

**Comment by ner00** [comment]
@donho
I have not, but at first glance SupportAssist v4.0.3 (latest) doesn't seem to be deleting Npp session file anymore, although I haven't kept a close eye on it. The last time it was deleted by SupportAssist was 2 weeks ago, not sure what version of SA was running then, but it would delete the session every week as per its schedule. I just ran a manual "optimization" task and it didn't delete Npp session either. It may be fixed, but I'll have to keep an eye on it for a few more weeks to be sure.

**Comment by donho** [comment]
@ner00 
Thank you for your observation and your information.
Please ping me if it happens again.

**Comment by ner00** [comment]
Another week went by, and no issue. As a precaution, I'll wait another week to see what happens but it's almost safe to say that since SupportAssist v4.0.3 or above this has been addressed silently. Before that, as per it's schedule and pattern, it was expected to delete Npp `session.xml` file every Friday as part of its scheduled cleaning/optimization job, which was what was happening since the February upgrade to SupportAssist from v3 to v4. This behavior last happened on May 10th 2024, but since then (17, 24, 31) it has not touched Npp `session.xml`.

I'm inclined to advise people to either update to SupportAssist v4.0.3 (although it should update automatically), or to just stick with v3 if their system doesn't support v4, or any other reason that refrains them from updating; just make sure to not use SupportAssist v4.0.0 - v4.0.2

**Comment by donho** [comment]
@ner00 
It's a very good news. Dell team SHOULD at least THANK YOU for helping to identify their bug, so they can fix it.
And from my side, THANK YOU for identifying the culprit!
