### ISSUE TITLE
Toolbar icons of many plugins are far too small with UHD display

### ISSUE THREAD

**Issue by bege10** [notepad-plus-plus/notepad-plus-plus#14709]
### Description of the Issue
I have a Thinkpad T570 with UHD display. As soon as the text scaling goes above 125% the toolbar looks like this:

![Screenshot_347_notepad++](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/1184237/22bc422c-4ceb-4540-a2d3-dde89f5ee294)

### Steps to Reproduce the Issue

1.  Switch display resolution between FHD and UHD forth and back 
2.  With scaling until 125% everything is OK
3. Above these icons are too small.

### Debug Information
 ```
Notepad++ v8.6.2   (64-bit)
Build time : Jan 14 2024 - 02:16:00
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 10 Pro (64-bit)
OS Version : 22H2
OS Build : 19045.3996
Current ANSI codepage : 1252
Plugins : 
    AutoCodepage (1.2.6)
    BetterMultiSelection (1.5)
    BracketsCheck (1.2.2)
    CodeAlignmentNpp (14.1.107)
    ColumnTools (1.4.5.1)
    CommentToggler (1)
    ComparePlus (1.1)
    CSVLint (0.4.6.5)
    DSpellCheck (1.5)
    Explorer (1.9.9)
    HTMLTag (1.4.1)
    ImgTag (2.0.1)
    LanguageHelp (1.7.5)
    Linefilter3 (1)
    MenuIcons (2.0.5)
    mimeTools (3)
    NavigateTo (2.6.4)
    nppAutoDetectIndent (2.3)
    NppConverter (4.5)
    NppExport (0.4)
    NppFavorites (1.0.0.1)
    NppFTP (0.30.1)
    NPPJSONViewer (2.0.6)
    NppMenuSearch (0.9.6)
    NppTextViz (0.4.2)
    NppToolBucket (1.10.6622.41516)
    NppXmlTreeviewPlugin (2)
    RegexTrainer (1.2)
    RunMe (1.6.1)
    SelectQuotedText (1.1)
    SessionMgr (1.4.4)
    SurroundSelection (1.4.1)
    XBrackets (1.3.1)
    XMLTools (3.1.1.13)
    _CustomizeToolbar (5.3)

```

The icons of ComparePlus and JSON Viewer have correct size, the other plugins are not usable from the toolbar.

**Comment by rdipardo** [comment]
There is no general solution for this.
Each individual plugin developer would have to scale their own icons the way comparePlus does.

See https://github.com/pnedev/comparePlus/blob/2b652f5c/src/Compare.cpp#L4210-L4218

**Comment by bege10** [comment]
Setting compatibility option for high DPI to "System advanced" solved the issue.
