### ISSUE TITLE
Ctrl drag does not copy

### ISSUE THREAD

**Issue by GetWild** [notepad-plus-plus/notepad-plus-plus#14702]
### Steps to Reproduce the Issue

1. Select text
2. Hold ctrl down
3. Drake selected text to copy

### Expected Behavior

Expected text to be copied and pulled with the mouse

### Actual Behavior

Selected text is no longer selected and new selection is started

### Debug Information

Notepad++ v8.6.2   (64-bit)
Build time : Jan 14 2024 - 02:16:00
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 11 Pro (64-bit)
OS Version : 22H2
OS Build : 22621.3007
Current ANSI codepage : 1252
Plugins : 
    ComparePlugin (2.0.2)
    mimeTools (3)
    NppConverter (4.5)
    NppExport (0.4)

**Comment by alankilborn** [comment]
It's now done this way:

* Select text
* Left-click selected text and start dragging to destination
* Add in Control hold
* Release left mouse button
* Release Control

**Comment by GetWild** [comment]
That's a shame, must have be some reason to change it, thanks for the quick response.

**Comment by alankilborn** [comment]
The change was to better support "multi-edit" -- making / manipulating more than one selection at a time.

**Comment by GetWild** [comment]
Ok, thanks for the info, will just have to get used to it.
