### ISSUE TITLE
Missing shebang support in JavaScript

### ISSUE THREAD

**Issue by ghost** [notepad-plus-plus/notepad-plus-plus#14706]
### Description of the Issue
Currently the official JavaScript [specification](https://www.w3schools.io/javascript/shebang-examples/) supports shebang. A script can be executed both in the browser and in the terminal (like node.js for example). In the browser, the shebang will be interpreted as a comment and will be ignored.

### Expected Behavior
The text of any line in the shebang should be displayed highlighted in green, as is the case in other languages such as Python.

### Example code
HTML file
```
<!DOCTYPE html>
<html>
<head>
<script type="text/javascript" src="test.js"></script>
</head>
<body></body>
</html>
```
JS file
```
#!/usr/bin/env node

console.log("Shebang Supported in Javascript");
```

### Debug Information
Notepad++ v8.6.2   (64-bit)
Build time : Jan 14 2024 - 02:16:00
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 10 Pro (64-bit)
OS Version : 22H2
OS Build : 19045.3996
Current ANSI codepage : 1252
Plugins : 
    mimeTools (3)
    NppConverter (4.5)
    NppExport (0.4)

**Comment by molsonkiko** [comment]
Open an issue in [Lexilla](https://github.com/ScintillaOrg/lexilla), the lexer library for Notepad++.

You could also use [EnhanceAnyLexer](https://github.com/Ekopalypse/EnhanceAnyLexer) to colorize the regex `(?-s)^#!.*`, which matches the shebang.

**Comment by ArkadiuszMichalski** [comment]
Will be fixed in next Lexilla https://github.com/ScintillaOrg/lexilla/issues/253.
