### ISSUE TITLE
Freezes after attempting to close from task bar.

### ISSUE THREAD

**Issue by ciaagent** [notepad-plus-plus/notepad-plus-plus#14718]
### Description of the Issue

Unable to close, save, or click anything in app, and must kill from Task Manager. If notepad++ is minimized, with 2 or more docs edited, and you try to close it using right click close on task bar icon.

### Steps to Reproduce the Issue

1. Uncheck "Remember current session for next launch" in Backup
2. Have 2 or more unsaved docs.
3. Minimize app
4. Right click on task bar icon and click close.
5. Nothing shows and app is unusable if you maximize

### Expected Behavior

Show the "Save" dialog.

### Actual Behavior

The application acts like a dialog has been displayed and locks up everything. At this point you're unable to save or even just close it and must kill task.

### Debug Information

Windows 10 device:
Notepad++ v8.5.7   (64-bit)
Build time : Sep  6 2023 - 23:13:49
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 10 Pro for Workstations (64-bit)
OS Version : 22H2
OS Build : 19045.3930
Current ANSI codepage : 1252
Plugins : 
    ComparePlugin (2.0.2)
    JSMinNPP (1.2205)
    mimeTools (2.9)
    NppConverter (4.5)
    NppExport (0.4)
    NPPJSONViewer (1.40)
    XMLTools (3.1.1.13)

Windows 11 device:
Notepad++ v8.5.4   (64-bit)
Build time : Jun 17 2023 - 20:42:45
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 11 Pro (64-bit)
OS Version : 22H2
OS Build : 22621.3007
Current ANSI codepage : 1252
Plugins : 
    ComparePlugin (2.0.2)
    mimeTools (2.9)
    NppConverter (4.5)
    NppExport (0.4)
    NPPJSONViewer (2.0.5)

**Comment by xomx** [comment]
I can reproduce this issue.

You probably have this N++ setting unchecked:
![npp-hidden-dlg_at_exit_-_reason](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/13075183/aaf56354-b2f1-47a1-8fec-b7266e3fa256)

Then at the described N++ exit from the taskbar, you have this invisible N++ dialog blocking its exit (I used the [SystemInformer](https://systeminformer.sourceforge.io/) capabilities to find that hidden dlg-window and maximize it for the debugging purposes):
![npp-hidden-dlg_at_exit](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/13075183/184fb484-d447-4bf2-a959-dd34ded8c043)

This is a N++ bug and I will try to fix that.

**Comment by ciaagent** [comment]
> I can reproduce this issue.
> 
> You probably have this N++ setting unchecked: ![npp-hidden-dlg_at_exit_-_reason](https://private-user-images.githubusercontent.com/13075183/304352871-aaf56354-b2f1-47a1-8fec-b7266e3fa256.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc4MzgxMTAsIm5iZiI6MTcwNzgzNzgxMCwicGF0aCI6Ii8xMzA3NTE4My8zMDQzNTI4NzEtYWFmNTYzNTQtYjJmMS00N2ExLThmZWMtYjcyNjZlM2ZhMjU2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjEzVDE1MjMzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM1ZDNiZWM3YmRkM2JjNmNkMGY4OTY3MTQ4YWFhZjYzYjIzNmYzNGQ3NGVmYTNkMGZhODUzYWEyOWVlNzA2MWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.xsY9Jnrg2HgW7OZjWJnuYakTeg2fSUvleiLyS2j-Yew)
> 
> Then at the described N++ exit from the taskbar, you have this invisible N++ dialog blocking its exit (I used the [SystemInformer](https://systeminformer.sourceforge.io/) capabilities to find that hidden dlg-window and maximize it for the debugging purposes): ![npp-hidden-dlg_at_exit](https://private-user-images.githubusercontent.com/13075183/304353443-184fb484-d447-4bf2-a959-dd34ded8c043.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc4MzgxMTAsIm5iZiI6MTcwNzgzNzgxMCwicGF0aCI6Ii8xMzA3NTE4My8zMDQzNTM0NDMtMTg0ZmI0ODQtZDQ0Ny00YmYyLWE5NTktZGQzNGRlZDhjMDQzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjEzVDE1MjMzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYwODA0ZDU5MGRjYWIxZWI3NmNlNjNiZjUyNTBhM2JjMDhjNDg5MDlhYjU3N2MwMDk5ZjcxNzljZjgwZGQzY2MmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.j2r592PEO2WlJO9YsGwm8ZMJW5Iuj7_acRTZN1p5jB4)
> 
> This is a N++ bug and I will try to fix that.

You are correct. I can confirm that I uncheck "Remember current session for next launch".

**Comment by donho** [comment]
@xomx 
I see always the popup saving dialog with Notepad++ appearing. How do you reproduce the hidden Notepad++ and its saving dialog?

**Comment by xomx** [comment]
@donho 
Ok, I found the real source of the problem - it is the way how the N++ creates its own custom modal dialogs (the ones invoked by the DialogBoxParam WINAPI, not by the simple MessageBox one).

The STR says

> 1. Have 2 or more unsaved docs.

Because for one only the MessageBox WINAPI will be used, but for 2+ the doSaveOrNotBox dlg created by the DialogBoxParam:
https://github.com/notepad-plus-plus/notepad-plus-plus/blob/250dfe0f8b2fabbb09242696c08e1c3b451c1fbe/PowerEditor/src/Notepad_plus.cpp#L2461-L2480

When the doSaveOrNotBox dlg is being initialized, it is also centered relative to the owner (main N++ wnd), but when that owner is minimized (systray seems to be ok), the ClientToScreen WINAPI returns [-32000, -32000](https://devblogs.microsoft.com/oldnewthing/20041028-00/?p=37453) as the center x,y:
https://github.com/notepad-plus-plus/notepad-plus-plus/blob/250dfe0f8b2fabbb09242696c08e1c3b451c1fbe/PowerEditor/src/WinControls/StaticDialog/StaticDialog.cpp#L78-L91

So, we should rather fix this common StaticDialog::goToCenter N++ code than the one specific manifestation of the problem in this issue.

**Comment by xomx** [comment]
I found another problem from this category, STR e.g. (there are probably other such dialogs to invoke):
- launch empty N++, make the "new 1" tab dirty by typing something
- set Backup settings ON like:
  ![npp-backup-setting](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/13075183/9e84c27d-ec00-41f1-a050-331867def0c1)
- have the minimizing to systray ON (Settings > Preferences... > MISC. > Minimize to system tray)
- close N++
- relaunch N++
- goto the N++ .\\backup\\ dir & delete there the "new 1" backup ("new 1@YYYY-MM-DD_HHMMSS" file)
- minimize N++
- right-click on the N++ tray-icon & chose "Close Tray Icon" from the popup
- click on Cancel here:
  ![npp-backup-missing-dlg](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/13075183/f7aaff04-240f-4549-ba1f-efb97ce982b5)
- now you will have the N++ process running but without any GUI visible (no systray icon either)

**Comment by donho** [comment]
> That's the STR I was using to reproduce the issue (v8.6.3 x64). However, I cannot reproduce at all :(

Sorry, @xomx  I can reproduce it now with you STR:
***minimize N++ (do not use the systray setting in Preferences > MISC. > Minimize to system tray)***

**Comment by xomx** [comment]
Moved the https://github.com/notepad-plus-plus/notepad-plus-plus/issues/14718#issuecomment-1950725489 systray problem to separate issue: #14777
