### ISSUE TITLE
Delphi project file (.dpr) syntax not autodetected

### ISSUE THREAD

**Issue by ManOfFlash** [notepad-plus-plus/notepad-plus-plus#1471]
Opened .dpr file looks without syntax highlight
EDIT: Just download & install v6.9 - issue still present

**Comment by milipili** [comment]
note: Delphi > Pascal

**Comment by donho** [comment]
Add the file ext you need via Configurator.

**Comment by zedxxx** [comment]
@donho Please add `dpr` to the default extension list. I can see that `lpr` is already present (Lazarus project file), but Delphi is missing.

**Comment by zedxxx** [comment]
PR #17985

**Comment by zedxxx** [comment]
I also create PR #17986 to add `.dproj` extension for xml default ext
