### ISSUE TITLE
https://npp-user-manual.org/docs/editing/

### ISSUE THREAD

**Issue by k22725** [notepad-plus-plus/notepad-plus-plus#14738]
chrome control+f search【depress】can find【depressed】
maybe 【pressed】 is true

**Comment by alankilborn** [comment]
@k22725 

I, for one, don't know what your point is, exactly.
Maybe put some time and effort into what you want to say, so others understand?

**Comment by donho** [comment]
https://github.com/notepad-plus-plus/npp-usermanual
