### ISSUE TITLE
[BEHAVIOR] "Split Lines" keeps trailing spaces

### ISSUE THREAD

**Issue by aaaxx** [notepad-plus-plus/notepad-plus-plus#1473]
"Split Lines" option (Ctrl + I) counts a trailing space as part of a word, which unnecessarily pushes some words into the next line and also leaves every line but the last one with a trailing space.

<pre>
Lorem ipsum dolor sit amet, consectetur_      |
adipiscing elit. Proin hendrerit vel sapien_  |
vel pulvinar. Aenean lectus ipsum, dictum_    | “non” would have fit here
non consectetur eget, sollicitudin sit amet_  |
elit. Donec aliquet dui quis sodales_         | “posuere.” would have fit here
posuere. Lorem ipsum dolor sit amet,_         |
consectetur adipiscing elit. Pellentesque_    |
scelerisque lacinia justo vitae mattis._      | “Proin” would have fit here
Proin laoreet erat in gravida venenatis._     | “Sed” would have fit here
Sed vel felis et nisi aliquet molestie non_   | “et” would have fit here
et lacus.                                     | (only line w/o trailing space)
</pre>

**Comment by donho** [comment]
It's Scintilla issue so it won't be fixed in Notepad++.
