### ISSUE TITLE
Plugin NppEventExec causes NPP crash and leaves remnants after uninstall

### ISSUE THREAD

**Issue by discoverSlow** [notepad-plus-plus/notepad-plus-plus#14731]
A great plugin, in principle.

I changed some rule's regular expression.
When executing the rule NPP crashed ("NPP no longer working", I had to kill the process eventually).
Afterwards each  NPP restart produces this popup window:

    NppEventExec: Error
    Failed to read the rules list. The plugin will not function until
    the issues are resolved.

It is not possible to resolve anything. A click on  Plugins -> NppEventExec 
shows all menu entries greyed out.

**It does not help to uninstall and re-install the plugin. After re-installation (w/o any other action)  the error-popup window shows again and the menu items remain greyed out, making the plugin unusable for any future purpose.**

### Steps to Reproduce the Issue
Unfortunately I do not know the exact regular expression which caused the plugin to break Notepad++ ("NPP no longer working".) I cannot make any further experiments. As described above the plugin cannot be used any more.

### Expected Behavior
I would expect that uninstalling the plugin and re-installing it would lead to a state as if the plugin had never been installed before.
In general I would expect that uninstalling a plugin leaves no remnants at all. Re-Installation afterwards should work exactly as the very first installation.

### Actual Behavior
As described above: after un-install and re-install  (w/o any other action)  the error-popup window shows again and the menu items remain greyed out, **making the plugin unusable for any future purpose**. 

### Debug Information
Notepad++ v8.6.2   (32-bit)
Build time : Jan 14 2024 - 02:18:41
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 10 Enterprise (64-bit)
OS Version : 22H2
OS Build : 19045.4046
Current ANSI codepage : 1252
Plugins : 
    ComparePlugin (2.0.2)
    DSpellCheck (1.4.6)
    mimeTools (3)
    NppConverter (4.5)
    NppExec (0.8.4)
    NppExport (0.4)

**Comment by alankilborn** [comment]
NppExec issue, not a Notepad++ issue (so shouldn't be logged here).
