### ISSUE TITLE
New blank files cannot be saved

### ISSUE THREAD

**Issue by nkarytia** [notepad-plus-plus/notepad-plus-plus#14741]
### Description of the Issue

New blank file cannot be saved.

### Steps to Reproduce the Issue

1. Create a new file (ctrl+N)
2. Try saving it with (ctrl+S)
3. Nothing happens

### Expected Behavior

The file save dialogue should open, to provide a filename and save the file.

### Actual Behavior

Nothing. ctrl+S does nothing and the Save option of the file menu is grayed as if it is an opened file with no changes.

### Debug Information

Notepad++ v8.6.2   (64-bit)
Build time : Jan 14 2024 - 02:16:00
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : "C:\Program Files\Notepad++\change.log" 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 10 Enterprise (64-bit)
OS Version : 22H2
OS Build : 19045.3930
Current ANSI codepage : 1252
Plugins : 
    ColumnTools (1.4.5.1)
    CSVLint (0.4.6.5)
    FileFinder (0.3)
    HexEditor (0.9.12)
    mimeTools (3)
    NppConverter (4.5)
    NppExport (0.4)
    XMLTools (3.1.1.13)

**Comment by alankilborn** [comment]
This has come up before and the Notepad++ author disagrees that it is a problem.  You can search closed issues for it and with some luck you might find it.

---

* Workaround 1:  type a character and then backspace it -- now Ctrl+s will be enabled and will work

* Workaround 2:  do _File_ > _Save As_

**Comment by nkarytia** [comment]
> This has come up before and the Notepad++ author disagrees that it is a problem, and has declined to make any code change to implement your desired behavior. You can search closed issues for it and with some luck you might find it (the author rejecting such a change).
> 
>     * Workaround 1:  type a character and then backspace it -- now Ctrl+s will be enabled and will work
> 
>     * Workaround 2:  do _File_ > _Save As_

I know of these workarounds, but Notepad ++ should work like this like any other editing software does. It makes lots of sense to have lots software doing similar things and expecting the same behaviour (e.g. Word, Excel, Visual Studio Code and many more).
I like notepad ++ and I have to open several new files that I would like to save them named before starting pasting content in them. This blocks it though.

There are quite a few annoyances with notepad++ and that's one of them. For example, when pasting long chunks of texts, the last line of the paste is out of screen (!!!), dark and light modes aren't really modes but themes (!!!) and switching to dark changes also your code colouring preferences, your chosen font and messes up your views. 
If this is not worth considering, please close it. Thanks anyway.

**Comment by alankilborn** [comment]
>but Notepad ++ should work like any other editing software does

I can't help you with this, as I stated, Notepad++ author has declined to implement it.

---

>There are quite a few annoyances with notepad++ and that's one of them. For example, ...

Feel free to create additional issues, one per topic.

**Comment by nkarytia** [comment]
O.k. Closed since it won't be fixed.

Thank you!

**Comment by mingshey** [comment]
Non-blank new files won't get saved either.
I have reverted to version 8.2.1 for now and in _Settings_ -> _Preferences..._ -> MISC , turned off the check-box "Enable Notepad++ auto-updater"

**Comment by alankilborn** [comment]
> Non-blank new files won't get saved either.

This is NOT true.
If you think it is true, provide exact steps to reproduce.
