### ISSUE TITLE
Batch File Colour Coding Gone Wrong

### ISSUE THREAD

**Issue by Thor110** [notepad-plus-plus/notepad-plus-plus#14747]
### Description of the Issue
After a certain amount of characters the colour coding for a batch script goes wrong.

### Steps to Reproduce the Issue
1.  Create a batch file and place the following line enclosed in brackets within it.
2. (del "%files%\Textures\M01Tex.utx" "%files%\Textures\M05ATex.utx" "%files%\Textures\M05BTex.utx" "%files%\Textures\M05CTex.utx" "%files%\Textures\M05dTex.utx" "%files%\Textures\M08Tex.utx" "%files%\Textures\M10Atex.utx" "%files%\Textures\M10Btex.utx" "%files%\Textures\M12Tex_test.utx" "%files%\Textures\M15Tex22.utx" "%files%\Textures\M15Tex_tomerge.utx" "%files%\Textures\m16.utx" "%files%\Textures\M16ATex.utx" "%files%\Textures\M16BTex.utx" "%files%\Textures\StargateEffectsTex.utx" "%files%\Textures\M10_train_anim.ukx" "%files%\Textures\SGAllianceUIX.uix" "%files%\Textures\UE2Runtime.ini" "%files%\Textures\XBoxLiveFont.xpr" "%files%\Textures\m17tex.utx" "%files%\Textures\x_delete_m17tex.utx" "%files%\Textures\xx_old_m17tex.utx" "%files%\Textures\M07_fresco_tex.utx" "%files%\Textures\M10_train_tex.utx" "%files%\Textures\StargateGameFontsTex.utx" "%files%\Textures\Tutorial_Tex.utx" "%files%\Animations\sg1_anim_comp.ukx" "%files%\Animations\sg1_anim2.ukx" "%files%\Animations\Goauld_Turret_anim.ukx" "%files%\Animations\Goa_Vehicles.ukx" "%files%\Animations\Haaken_anim.ukx" "%files%\Animations\Haaken_leader_anim.ukx" "%files%\Animations\Haaken_Shield_anim.ukx" "%files%\Animations\Haaken_warrior_anim.ukx" "%files%\Animations\jaffa_anim.ukx" "%files%\Animations\M07_fresco_anim.ukx" "%files%\Animations\M21_Crystal_anim.ukx" "%files%\Animations\sg1_anim.ukx" "%files%\Animations\sg1_turret_M60_Humvee.ukx" "%files%\Animations\SG1_weapons_1st.ukx" "%files%\Animations\SG1_Wep_Anim2.ukx.tmp" "%files%\Animations\super_soldier_anim.ukx" "%files%\Animations\tokra_anim.ukx" "%files%\Animations\veh_jeep.ukx" "%files%\StaticMeshes\M16Prefabs.upx" "%files%\StaticMeshes\UW.ini")
3. scroll sideways to ""%files%\Animations\Goa_Vehicles.ukx"" and you will see that the colour coding falls out of line after the letters "Anim".

**Comment by xomx** [comment]
The problem occurs exactly at the 1024 char-position (you can add or subtract one character around that pos and it will still be at that 1024 one). So I suspected some exceeding of a buffer capacity and here it is:
https://github.com/notepad-plus-plus/notepad-plus-plus/blob/5110069841744e9bb927ac219871e06ab9447764/lexilla/lexers/LexBatch.cxx#L120

So your report belongs here (you should check there for a similar issue 1st):
https://github.com/ScintillaOrg/lexilla/issues

**Comment by Thor110** [comment]
> The problem occurs exactly at the 1024 char-position (you can add or subtract one character around that pos and it will still be at that 1024 one). So I suspected some exceeding of a buffer capacity and here it is:
> 
> https://github.com/notepad-plus-plus/notepad-plus-plus/blob/5110069841744e9bb927ac219871e06ab9447764/lexilla/lexers/LexBatch.cxx#L120
> 
> So your report belongs here (you should check there for a similar issue 1st): https://github.com/ScintillaOrg/lexilla/issues

Thanks for your quick response, I have checked for a similar issue there and will post an issue about it there.

Realistically I suspect it's not an issue for most people and is rarely ever noticed but so long as it's noted somewhere.
