### ISSUE TITLE
Feature proposal: filter shortcut mapper by each word in the filter text box separately

### ISSUE THREAD

**Issue by molsonkiko** [notepad-plus-plus/notepad-plus-plus#14743]
Before I begin, I should note that this is not a request for someone else to implement a feature. I have already implemented this feature in my own fork, and can submit a PR if core devs are interested.

### Description of the Issue

Currently the shortcut mapper filters using the entire contents of the `Filter` search box (I will hereafter call this `filterStr`). If any field for a shortcut contains `filterStr` in its entirety, the shortcut is displayed.

This behavior is fine, but there are many times when a more flexible system would be useful. A simple, user-friendly way to do this is to split `filterStr` into a list of whitespace-separated words (I will hereafter call this `filterWords`), and then require *every word in `filterWords` to be matched by at least one field.*

For example, let's look at a screenshot from 8.5.8.

![image](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/46202915/21e9c5c5-d303-48a0-b21d-3153d5d91630)

I have used the `jsont` search term to find all the shortcuts associated with the `JsonTools` plugin. But JsonTools has a lot of shortcuts, and maybe I want to see all the JsonTools shortcuts that relate to `regex`. With the current implementation, this can only be done manually.

Here's a screenshot showing how to do exactly that with my proposed implementation.

![image](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/46202915/2e2fe26e-015f-4986-9084-f1ded03d2447)

Hopefully the advantages of the new behavior are obvious.

### Disadvantages of the proposed behavior, and my counterarguments

1. __It's different from the existing behavior, and would cause initial confusion.__
    - __Anything matched by the existing behavior will still be matched by the new behavior.__ For example, suppose the user wants to find a shortcut called `csv to json`, so they input `csv to json`. The new behavior will match `csv to json`, but it will also match any shortcut containing the word `csv` associated with the `JsonTools` plugin.
2. __Literal space characters in the search term are no longer matched.__
    - I think this is a pretty niche case.
3. __It might make performance worse.__
    - I tested it. There's no obvious difference.
4. __It makes the code more complex.__
    - my current implementation causes a roughly 20-line diff, including about 20 changed lines in `ShortcutMapper.cs` and 2 changed lines in `ShortcutMapper.h`. About half of the new lines are explanatory comments.
    - in addition, the changed functions are only called in `ShortcutMapper.cs`, __which is a modal dialog__, meaning that ripple effects to the broader codebase are essentially impossible.
    - __However, the code footprint gets a lot larger if a new setting is desired to allow toggling between the old behavior and the new behavior__ (say, maybe a checkbox next to the `Filter` textbox). For this reason, I would prefer to avoid adding a new configurable setting, especially one that is saved to a config file.

**Comment by kiwichick888** [comment]
I really like this idea. However, I have a thought about disadvantage number 1. "Anything matched by the existing behavior will still be matched by the new behavior." This would mean that filtering with a whitespace, when the whitespace is part of the full filter term (eg: csv to json), will give more results than desired. If that is going to also match any shortcut containing the word csv, would it in some situations, return too many results? If not, no need to read any further. But if this is something to be considered, I'm wondering would it be possible/desirable/sensible to have some other way to filter each word separately using a method other than a space? Maybe each word to be filtered could be enclosed in single quotation marks. Or a multiple-word filter term like csv to json could be enclosed in single quotation marks.

**Comment by molsonkiko** [comment]
@kiwichick888 
> If that is going to also match any shortcut containing the word csv

I think you misunderstand my proposal. If the filter is `csv to json`, a shortcut is not matched under my proposal unless it contains __`csv` and `to` and `json`.__

> Or a multiple-word filter term like csv to json could be enclosed in single quotation marks.

That is a good idea! If I wanted to allow literal whitespace characters in my search term, that might be how I would implement it.

However, my feeling is that the first version of the feature should be as simple as possible, and then if enough users complain about the simple implementation, it can be incrementally expanded.

**Comment by kiwichick888** [comment]
> @kiwichick888
> 
> > If that is going to also match any shortcut containing the word csv
> 
> I think you misunderstand my proposal. If the filter is `csv to json`, a shortcut is not matched under my proposal unless it contains **`csv` and `to` and `json`.**
> 
> > Or a multiple-word filter term like csv to json could be enclosed in single quotation marks.
> 
> That is a good idea! If I wanted to allow literal whitespace characters in my search term, that might be how I would implement it.
> 
> However, my feeling is that the first version of the feature should be as simple as possible, and then if enough users complain about the simple implementation, it can be incrementally expanded.

Thanks for the speedy feedback. Yes, I think I did misunderstand what you meant, sorry about that. I absolutely agree that the first version should be as simple as possible, and go from there. I think this would be a fantastic new feature.

**Comment by alankilborn** [comment]
> and can submit a PR if core devs are interested

Can you submit it to allow interested parties to try it out?
Or show us where in your fork to get it to try it out?

**Comment by alankilborn** [comment]
A comment without trying it out first:

Often I'm looking for a certain thing, but I don't want to have to think about which "tab" it might be on in _Shortcut Mapper_, in order to be able to find it.  It may be "much too big of a change" but it would be nice to filter/search more globally.  Perhaps this is food for a different, new issue.

---

Afterthought:

But I suppose this works well enough:

* put search term in Filter box
* click through all of the tabs (_Main menu_, _Macros_, _Run commands_, _Plugin commands_, _Scintilla commands_) and note that the filter still filters with each tab change
