### ISSUE TITLE
Restore Recent Closed File translation not picked up

### ISSUE THREAD

**Issue by batagy** [notepad-plus-plus/notepad-plus-plus#1476]
Hi!

Translation related issue.
Below item's translation is not pickup by the program properly:

Item id=“41021” name=“Restore Recent Closed File”

Around 2015-05-10 , this was fixed, so that translation was picked up properly in Notepad++, but later in version 6.8.1 it went bad again. So the translation is not pickup up again since 6.8.1 version.

The issue I've mentioned already in PR #542  towards the end of discussion, but finally it was ignored.

Please note! If in Settings, if you change the language to English, then back to the Language, then the translation is refreshed and picked up! But as soon as you open Notepad++ next time, this item is forgotten again.

Thanks a lot
György

**Comment by Tmp341** [comment]
I've stated that in #1016, and i thought it was my mistake. But it looks like the problem is occuring other than English. Just like you said : 

> if you change the language to English, then back to the Language, then the translation is refreshed and picked up! But as soon as you open Notepad++ next time, this item is forgotten again.

**Comment by batagy** [comment]
Hi!
Why is that so hard to correct such a minor issue?! 
Should we wait years somebody to correct this damn issue?
Thanks a lot

**Comment by batagy** [comment]
@Rikk 
@milipili 
Hi guys! Could you please check this annoying bug?
Why Don ignores this for months?
Who can correct this?

(PS: this issue was already mentioned in #542 .)

**Comment by Rikk** [comment]
Why me? I don't help Npp anymore, the entire project is handled and slowed by only one sir: donho.
There are hundreds of proposed fixes that are simply ignored. I, at least, don't like to help this kind of projects.

**Comment by batagy** [comment]
Hi!
This issue is still present in version 7.3.

**Comment by schnurlos** [comment]
And still in 7.6.1 ...

**Comment by chcg** [comment]
Still repoducible with:

Notepad++ v7.6.6   (64-bit)
Build time : Apr  3 2019 - 23:52:32
Path : C:\Users\christian\Source\Repos\npp.7.6.6.bin.x64\notepad++.exe
Admin mode : OFF
Local Conf mode : ON
OS : Windows 10 (64-bit)
Plugins : DSpellCheck.dll mimeTools.dll NppConverter.dll PluginManager.dll XMLTools.dll

**Comment by MetaChuh** [comment]
way to reproduce summary:
* change to any language (except english)
(`file > restore recent closed file` is correctly shown translated)
* close notepad++
* reopen notepad++

now `restore recent closed file` is now not translated anymore (41021)

<img width="717" alt="Bildschirmfoto 2019-04-14 um 08 54 59" src="https://user-images.githubusercontent.com/45773305/56089471-a3a1bc80-5e93-11e9-95fe-b41ac1f33105.png">

**Comment by chcg** [comment]
Related code:
https://github.com/notepad-plus-plus/notepad-plus-plus/blob/52a4e21af5c7197926cf32a45f4b96f015ccc2d3/PowerEditor/src/lastRecentFileList.cpp#L105

which gets overwritten by the specialname of:
https://github.com/notepad-plus-plus/notepad-plus-plus/blob/52a4e21af5c7197926cf32a45f4b96f015ccc2d3/PowerEditor/src/Parameters.cpp#L103
