### ISSUE TITLE
notepad++ repository not available

### ISSUE THREAD

**Issue by ThierryDFR** [notepad-plus-plus/notepad-plus-plus#14761]
### Description of the Issue
(1/3) Trouvé Notepad++ [Notepad++.Notepad++] Version 8.6.3
La licence d’utilisation de cette application vous est octroyée par son propriétaire.
Microsoft n’est pas responsable des paquets tiers et n’accorde pas de licences à ceux-ci.
Téléchargement en cours https://github.com/notepad-plus-plus/notepad-plus-plus/releases/download/v8.6.3/npp.8.6.3.Installer.x64.exe
Une erreur inattendue s'est produite lors de l'exécution de la commande :
Download request status is not success.
0x80190194 : Non trouv (404).

URL : https://github.com/notepad-plus-plus/notepad-plus-plus is available
URL : https://github.com/notepad-plus-plus/notepad-plus-plus/releases not available

### Steps to Reproduce the Issue

winget upgrade --all --include-unknown --accept-source-agreements --accept-package-agreements --disable-interactivity --silent.

**Comment by ThierryDFR** [comment]
new URL : https://github.com/notepad-plus-plus/notepad-plus-plus/releases/download/v8.6.4/npp.8.6.4.Installer.x64.exe

**Comment by ThierryDFR** [comment]
NEw URL : https://notepad-plus-plus.org/downloads/v8.6.4

**Comment by donho** [comment]
The binaries of v8.6.3 are removed due to the regression. 
Download v8.6.4 instead.
