### ISSUE TITLE
[Feature request] Support Zig?

### ISSUE THREAD

**Issue by jcs090218** [notepad-plus-plus/notepad-plus-plus#14772]
It would be great if [Zig](https://github.com/ziglang/zig) highlighting is supported by default.

**Comment by sdasda7777** [comment]
I don't know anything about Zig syntax, but you can define your custom language and its highlighting using `Language` > `User Defined Language` > `Define your language`. If you have a version that works for you, you can post it here, perhaps make a pull request.

**Comment by molsonkiko** [comment]
Agree that the UDL system is your best option here. I'd also recommend the [EnhanceAnyLexer plugin](https://github.com/Ekopalypse/EnhanceAnyLexer), which can give you a lot of syntax coloring options that the UDL system can't provide.

**Comment by chcg** [comment]
The FR needs to go here first https://github.com/ScintillaOrg/lexilla/issues as this is the base for the lexers used by N++. Already published UDLs are available at https://github.com/notepad-plus-plus/userDefinedLanguages.

**Comment by ArkadiuszMichalski** [comment]
Lexer will probably be available in the next version of Lexilla:
https://github.com/ScintillaOrg/lexilla/pull/267

**Comment by chcg** [comment]
Lexilla support for N++ is available with https://github.com/notepad-plus-plus/notepad-plus-plus/pull/15717 . It is now possible to add the remaining parts necessary within N++, see e.g. #15000 + #15128
