### ISSUE TITLE
Incorrect language detection and highlighting again?

### ISSUE THREAD

**Issue by cyber01** [notepad-plus-plus/notepad-plus-plus#1477]
Welcome to the last version seems to have fixed the problem, but in the latest version at the moment there is a problem 6.8.8.
When you open a .php file incorrectly identifies the language and, consequently, syntax highlighting, she posed as a "JSON" because of what has to constantly switch manually syntax. When it correct? Unable to work

**Comment by rushikesh90** [comment]
Can you provide screenshot? Also provide "?"->Debug Info.

**Comment by cyber01** [comment]
http://puu.sh/n8emt/d2e47b3772.png  (in the bottom - JSON, file openned from filezilla edit), 
Notepad++ v6.8.8
Build time : Dec 10 2015 - 01:11:37
Path : d:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : ON
Local Conf mode : OFF
OS : Windows 7
Plugins : CodeAlignmentNpp.dll ComparePlugin.dll HTMLTag_unicode.dll mimeTools.dll NppCalc.dll NppCCompletionPlugin.dll NppConverter.dll NppCrypt.dll NppDocIt.dll NppExec.dll NppExport.dll NppFTP.dll NppGTags.dll NppJumpList.dll NPPTextFX.dll PluginManager.dll regrexplace.dll SelectNLaunch.dll SpeechPlugin.dll

**Comment by rushikesh90** [comment]
I cannot find any issue in detecting the file. Maybe it is parser issue in your case. Can you try with more than one files ?

**Comment by cyber01** [comment]
You did not find the problem? I opened the PHP file, but he was determined as JSON with the appropriate syntax highlighting and there is no problem? I have tried a lot of PHP files and all there is the problem definition syntax.
Perhaps the problem is that the file is opened for editing through Filezilla, but then again, before (in versions prior to 6.8.6) all worked fine.

**Comment by rushikesh90** [comment]
![image](https://cloud.githubusercontent.com/assets/6714143/13117236/0a7bffac-d5c5-11e5-9496-5d7fab53d85b.png)

As you can see , the issue is not coming now. Will look in the code though.

**Comment by cyber01** [comment]
If open local files (HDD) - yes, all is well, but if the file is sent by an application (such as FileZilla (FTP client)) - incorrect syntax is chosen

**Comment by cyber01** [comment]
Hmm i opened json file, but syntax incorrect (plain text).
The problem only occurs if you open a file via FTP (FileZilla) by clicking on the "View / Edit"

**Comment by GitMensch** [comment]
I have the problem "everything opens as JSON" problem, too and it occurs when opening a file via file association to NPP (Windows 10). If I close the file and reopen it from History the syntax highlighting is correct.

**Comment by donho** [comment]
Cannot reproduce it in the latest release.

**Comment by GitMensch** [comment]
I also cannot reproduce it any more, so closing seems to be fine.
