### ISSUE TITLE
Regression - selected text can't be copied by ctrl-drag

### ISSUE THREAD

**Issue by pnkFloyd** [notepad-plus-plus/notepad-plus-plus#14774]
### Description of the Issue

Can't copy selected text by Ctrl-drag

### Steps to Reproduce the Issue

1. Select any text.
2. Press and hold Ctrl and try to drag selected text. 

### Expected Behavior

In previous versions up to 8.6 it would copy selected text into dragged position.

### Actual Behavior

It does nothing on all the next versions - 8.6.1, 8.6.2, 8.6.4

**Comment by alankilborn** [comment]
In 8.6.4, either:

* start dragging BEFORE adding in Ctrl

OR

* disable multi-editing via this:
![image](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/77065706/cf162507-8aac-4a3f-86ee-bb9e7eed6f13)

**Comment by pnkFloyd** [comment]
Thank you! It works.

**Comment by alankilborn** [comment]
> Thank you! It works.

Then please close this issue -- thanks.
