### ISSUE TITLE
context menu duplicated

### ISSUE THREAD

**Issue by modz2014** [notepad-plus-plus/notepad-plus-plus#14783]
Seems like the context menu is duplicated again

**Comment by santropedro** [comment]
If you don't add all the important required information you know it's needed to file a bug it's not worth to try to pay attention to you, you are essentially spamming. How to distinguish this post from voluntary spam? Don't do this.

**Comment by modz2014** [comment]
hey i should have explained a bit better sorry mate anyway i have notice the last 4 updates the context menu is being duplicated it shows on the first context menu fine and it also shows under show more options i can not remember which version it wasn't showing under there i will have reinstall notepad++ again and go from there

**Comment by CennoxX** [comment]
Could you add a screenshot?

**Comment by modz2014** [comment]
![NotePad++ContextMenu](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/25472227/be6ccb82-40fc-4f01-83f6-b79351a192bf)

**Comment by modz2014** [comment]
it was not showing up on in the right photo in a older version i have to figure out what versio n when i have time

**Comment by CennoxX** [comment]
It's normal behaviour for context menu entries to show under both context menus. Take a look, for example the Microsoft Notepad is also shown on both context menus.

**Comment by modz4567** [comment]
I notice as well it different version of notepad++

**Comment by modz2014** [comment]
> It's normal behaviour for context menu entries to show under both context menus. Take a look, for example the Microsoft Notepad is also shown on both context menus.

wasnt showing in previous versions

**Comment by modz2014** [comment]
Alright, I've identified a bug. If two MSIX packages utilize a shared counter in their source code, it leads to a duplication of the context menu. This issue arises because both applications are attempting to manage the same context menu items, potentially causing conflicts in their display

**Comment by donho** [comment]
@GurliGebis
Are you aware of it?

> Alright, I've identified a bug. If two MSIX packages utilize a shared counter in their source code, it leads to a duplication of the context menu. This issue arises because both applications are attempting to manage the same context menu items, potentially causing conflicts in their display

**Comment by GurliGebis** [comment]
@modz2014 which two MSIX packages are you using that does this? (Notepad++ and which one else?)
