### ISSUE TITLE
Since 8.6.1 自從8.6.1之後

### ISSUE THREAD

**Issue by BoringMan314** [notepad-plus-plus/notepad-plus-plus#14788]
Since 8.6.1, it is no longer possible to move selected text by dragging with the left mouse button or to copy the text using Ctrl + left mouse button.

自從8.6.1之後，無法把選起來的文字使用滑鼠左鍵移動位置，或使用Ctrl+滑鼠左鍵複製該文字

**Comment by alankilborn** [comment]
Move to 8.6.4 and disable Multi-editing on the Editing 2 preference setting page.

**Comment by BoringMan314** [comment]
thanks
