### ISSUE TITLE
Allow a hotkey to move the cursor to the first/last visible line

### ISSUE THREAD

**Issue by dg9ngf** [notepad-plus-plus/notepad-plus-plus#1478]
Like Ctrl+PageUp and Ctrl+PageDown in Visual Studio, I'd like to move the text cursor to the first or last visible line in the editor without scrolling. I can't find a Scintilla command to assign a hotkey for this. Have I missed it?

**Comment by dail8859** [comment]
Under the Scintilla commands I believe you want `SCI_STUTTEREDPAGEUP` and `SCI_STUTTEREDPAGEDOWN`

**Comment by dg9ngf** [comment]
Correct, thanks.
