### ISSUE TITLE
Vertical edge displayed at wrong position (shift of 1 unit)

### ISSUE THREAD

**Issue by coucout** [notepad-plus-plus/notepad-plus-plus#14793]
### Description of the Issue
Vertical edge is displayed at wrong position in the editor

### Steps to Reproduce the Issue
Define a position in the preferences->margin section->Vertical edge settings

### Expected Behavior
Vertical ruler displayed at the specified columun number

### Actual Behavior
the ruler is displayed at n+1 column position instead of n

### Debug Information
Notepad++ v8.5.4   (64-bit)
Build time : Jun 17 2023 - 20:42:45
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : "....." (my file name)
Admin mode : ON
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 11 Pro (64-bit)
OS Version : 22H2
OS Build : 22621.1992
Current ANSI codepage : 1252
Plugins : 
    ComparePlugin (2.0.2)
    HexEditor (0.9.12)
    JSMinNPP (1.2205)
    JsonTools (4.0.0.1)
    Linefilter3 (1)
    mimeTools (2.9)
    NppConverter (4.5)
    NppExport (0.4)
    NPPJSONViewer (2.0.3)
    XMLTools (3.1.1.13)

![image](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/3479885/9c1d41ae-fe62-47dd-860d-cf19be990fd3)

**Comment by alankilborn** [comment]
I disagree that there is any problem here.

If you press Shift+Home from where your caret is shown, how many characters do you get in the selection?
Answer: 59
So the vertical edge is showing you 59 characters to the left of the caret (as expected).

The status bar's `Col:` number is for the column to the _right_ of the caret, or equivalently, the column that a typed character will be entered into.
