### ISSUE TITLE
DarkModeDefault.xml become very eavy.

### ISSUE THREAD

**Issue by SigmaFlame** [notepad-plus-plus/notepad-plus-plus#14809]
### Description of the Issue
Hello,
When Notepad++ is used for a very long time, it become slow to open a file. It could take some seconds.
This issue seems to be caused by the file DarkModeDefault.xml that become very eavy. (64 Mo in my case)

### Steps to Reproduce the Issue
Using the program for a very long time, multiple weeks or years, updating it when asked, and so on.

### Expected Behavior
It stays fast.

### Actual Behavior
It becomes slow after a while, some weeks or years after, depending of the usage.

### Debug Information
According to my tests, it appears that the file « %appdata%/Notepad++/themes/DarkModeDefault.xml » become very eavy.
Deleting this file makes the program fast again, the dark mode is still on and this file is not automatically recreated.
Deleting all « %appdata%/Notepad++ » recreate a new light DarkModeDefault.xml file.

My old DarkModeDefault.xml have a size of 64.1 Mo with 67 292 488 lines. The default one is only 183 Ko.
This file is very too eavy to be opened with any program that I have on my computer.
I guess at some time, something went wrong somewhere and this file will increase its size each time I open a file.

On my Notepadd++ settings I have disabled "memory session" so if I close the program with files open, they are closed the next time I open Notepad++, and I added some word in the PHP colorization section.

**Comment by mpheath** [comment]
It appears an accented character triggered this corruption to occur.

![accent](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/58158242/7088943e-4630-4ce0-b0ab-4998d6210fb3)

The top line is fresh from v8.5.4 portable zip.
The bottom line is from v8.5.4 in use which shows some corruption and probably gets larger over time.

The latest version does not have the accented character in the comment header.

https://github.com/notepad-plus-plus/notepad-plus-plus/blob/12548b6abb607de94163e9171908de4a1b7a718c/PowerEditor/installer/themes/DarkModeDefault.xml#L2-L6

**Comment by ArkadiuszMichalski** [comment]
Please use actuall Notepad++ and it's thems.
