### ISSUE TITLE
[HiDPI] Dark mode scrollbar positions in edit/listbox controls in hiDPI wrong 

### ISSUE THREAD

**Issue by ozone10** [notepad-plus-plus/notepad-plus-plus#14817]
Dark mode scrollbar positions in edit/listbox controls in hiDPI are in very rare case wrong.

### Steps to Reproduce the Issue

1. Have multi-monitor setup with different dpi scaling
2. Have dark mode enabled 
3. Open window with edit/listbox control which has scrollbar

note: It's is very hard to reproduce. 

### Expected Behavior

![image](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/55940305/97ceabfd-9bb4-471a-a9de-c0a1d0a98d2e)

### Actual Behavior

![dpi](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/55940305/a420dbaa-a348-4fb3-b26f-1e1de15c36ac)

### Debug Information

Notepad++ v8.6.4   (64-bit)
Build time : Feb 20 2024 - 00:12:59
Path : D:\Test\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : ON
Cloud Config : OFF
OS Name : Windows 11 Pro (64-bit)
OS Version : 23H2
OS Build : 22631.3155
Current ANSI codepage : 1252
Plugins : 
    mimeTools (3.1)
    NppConverter (4.6)
    NppExport (0.4)

**Comment by donho** [comment]
@ozone10 
Could you precise your configuration for reproducing this issue please?

I cannot reproduce it with the following configuration:
3840 x 2160 laptop screen resolution
1920 x 1080 2nd screen (TV)

**Comment by ozone10** [comment]
@donho 
Unfortunately it's very rare, for the last 6 month it only happened twice for me.
So I am not sure how to reproduce it consistently. 
But I have scale 125 % and 100 %.

**Comment by donho** [comment]
999b4d18877c3baa6e4a1b33bf8301e0b884a76f & 10305ebded73375c47d4068236b21d0d4265cee8

**Comment by ozone10** [comment]
closed by https://github.com/notepad-plus-plus/notepad-plus-plus/commit/29fcd1ac9117a09bd5a988ffdb7fd0e4e0b2fe6b
