### ISSUE TITLE
Allow disabling automatic changed file detection per-file

### ISSUE THREAD

**Issue by MNGoldenEagle** [notepad-plus-plus/notepad-plus-plus#1481]
Currently if you want to stop NPP from detecting that a file has been changed on the filesystem, you have to apply the global solution: go to Preferences, select MISC., and disable File Status Auto-Detection.  This isn't always desirable; sometimes you may want to only prevent one file from being auto-updated, while still checking other files.

This feature request proposes adding an option in either the File menu or the right-click menu for the file tab (or both) that toggles file status auto-detection on a per-file basis.

**Comment by donho** [comment]
This feature is quite complex to implement, so it won't be done.
However in the latest version, this feature is enhanced, so just give it a try.
