### ISSUE TITLE
Kedit - Zone editing

### ISSUE THREAD

**Issue by JackGFuller** [notepad-plus-plus/notepad-plus-plus#14828]
### Steps to Reproduce the Issue

1. 
2. 
3. 

### Debug Information

Kedit is another text editor. It has a capability to specify a column zone in which editing will be accomplished, only within that zone.

So, for example, if Zone is set to columns 6 thru 12, any editing will occur ONLY in those columns.

1] Does Notepad++ have that feature?
2] If not, could it be implemented?

Kedit.com

Thank you!

**Comment by donho** [comment]
https://community.notepad-plus-plus.org/category/4/help-wanted

**Comment by JackGFuller** [comment]
DonHo -- I don't understand your rejection of my request.

I looked at the link you included in your note, and was unable to find anything about specifying columns within which editing would occur. 

Could you elaborate on saying that this issue was rejected or completed?

Thanks! - Jack Fuller

**Comment by JackGFuller** [comment]
I will do that. I don't often use GitHub, and even less for Notepad++, as it is most excellent - except for this ability to restrict editing to a range of columns. And indeed, that capability may already be there - I just haven't been able to figure out how access and use it.

NP++ is an excellent app, and I use it frequently for reading and editing text files. So I was not familiar with the process about requesting what might be a possible feature. Thanks for clarifying!
________________________________

**Comment by donho** [comment]
@JackGFuller 
Thank you for your comprehension!

**Comment by alankilborn** [comment]
>The question is neither a feature request nor a bug report, so it doesn’t belong in the issue trackers here.

>2] If not, could it be implemented?

This part sure seems like a feature request.

**Comment by donho** [comment]
@alankilborn 
> This part sure seems like a feature request.

True. But the idea is that users should go to the community for ensuring the non-existing of feature.
OTOH, community people could provide the script for solving users' need.
