### ISSUE TITLE
Binary files are not displayed properly after tab change

### ISSUE THREAD

**Issue by u07** [notepad-plus-plus/notepad-plus-plus#14832]
### Description of the Issue

Hi. After updating NPP I found out that I can't edit binary files anymore. They open normally, but then if I switch to another file (another tab) and go back, NPP freezes and then shows the binary file stripped from all non-printable symbols. 

In the newest version same happens when I open binary via Explorer context menu -> Open in NPP. The only way to view it correctly is to drag it into NPP window.

### Steps to Reproduce the Issue

1. open file
2. open another tab 
3. go back to the file

### Actual Behavior
![image](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/20968145/6b2fcecc-1483-4901-9ba6-244240ae606c)
![image](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/20968145/1b0c2481-d6d3-4cb1-ad11-e3345faad07f)
![image](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/20968145/6c4d4183-2c2a-4cb2-9557-f6f8d0eed012)

### Debug Information

Notepad++ v8.6.4   (64-bit)
Build time : Feb 20 2024 - 00:12:59
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : 
Admin mode : ON
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 7 Professional (64-bit)
OS Build : 7601.0
Current ANSI codepage : 1251
Plugins : none

**Comment by u07** [comment]
I used to work with it like this, it's been fine for ages. It pretty much is)

Actually, I think, I found the problem. What is this param  ccShow="No"?  Where is it in the config window? It seems not available via GUI. Although, in my setup (after update) it is NO. And in a fresh new install it is YES. And when it's YES, the problem is gone

**Comment by u07** [comment]
![image](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/20968145/09ad6d88-adbb-4bc5-ac42-3f90373190f2)

**Comment by alankilborn** [comment]
>ccShow

Probably relating to one of these:

![image](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/77065706/06973c3e-860e-46a0-931c-c50041fad644)

---

>It pretty much is hex- or whatever- super-duper multi editor

If you don't have NUL in your data, it is "pretty much ok".
But... you do have NUL in there, so, a lot of Notepad++ editing actions will not work correctly.  You're playing with fire.  Good luck to not get burned.

**Comment by u07** [comment]
Ah, I see.. it's linked with this button now.  It's behaviour is inconsistent, it has 3 states instead of 2. By default CCs are enabled, button is Off. Then you click it and it's On - CCs are still enabled. Then you declick it and CCs are gone. 

 I can't remember, was it the default behaviour in previous versions? This button used to (?) disable spaces and tabs only, not CCs.

![image](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/20968145/f604d225-96d0-41be-ae96-41f417f9dd54)


![image](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/20968145/43c273c1-83a2-4c71-98bd-c166f2fa77d1)


![image](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/20968145/ce1102c6-c67e-4db8-a1b3-0ecdb31bcec4)

**Comment by u07** [comment]
Similar issue: https://github.com/notepad-plus-plus/notepad-plus-plus/issues/13988

**Comment by alankilborn** [comment]
As you point out, 13988 is a similar issue.  I'd forgotten about that one.

Regarding the ¶ toolbar button, it is intended to be an "all on" or "all off" control. 
If the button is in the depressed/on state (visually), you can be sure it is showing the maximum that can be shown.
However, if it is in the non-depressed/off state, it might not be the minimum (all off), but it definitely isn't the maximum (all on).
If you exclusively use the toolbar button for control, however, you *can* be sure that it is all-on or all-off.
(it isn't the most obvious behavior)

**Comment by alankilborn** [comment]
> Regarding the ¶ toolbar button

More information regarding this button was added to the user manual: https://github.com/notepad-plus-plus/npp-usermanual/pull/646/commits

**Comment by u07** [comment]
I got your idea. But still believe it's a wrong approach. That's why:

First, in other editors same button is normally used for displaying invisible characters only. Like, tabs, spaces and paragraphs. The icon itself represents the paragraph symbol. Look at MS Word: disarmed btn & visible CCs:

![image](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/20968145/bb452394-e76b-409a-b7a0-5624aa940490)

Second, the behaviour of this button was different in previous versions of NPP. It used to work as you expected it to work based on your experience with any other editor. See: 

![output](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/20968145/cf38a495-112d-429d-9336-ef0496fae396)

Third, showing TABs ans spaces is a more essential and popular function than hiding CCs. 

I believe that the behaviour of the button was changed unintentionally. Someone added a new functionality allowing user to hide control characters. And he placed it into the submenu that was controlled by that button. So the button got new function. As there's a bug related to that change, it may prove me right, the programmer just did it without noticing this hidden impact.

**Comment by alankilborn** [comment]
> * Second, the behaviour of this button was different in previous versions of NPP. It used to work as you expected it to work based on your experience with any other editor. See:

I see what is happening for you in your animated screen capture in your "Second" bullet point.
Unfortunately, when I attempt to reproduce that behavior, I can't.
For me, when the toolbar button is shown in the depressed state, I see all of the inverse video characters.
When it is in the not-depressed state, I see none of the inverse video characters.
For me, I am obtaining "correct" behavior, so, sorry, I can't be of more help on that aspect -- maybe someone else?

**Comment by u07** [comment]
Btw, here is the commit: https://github.com/notepad-plus-plus/notepad-plus-plus/commit/0cad36d636aaa517f8fd50bdc171f6fa01181a38

By https://github.com/ozone10

**Comment by alankilborn** [comment]
For users that desire some alternative functionality to how the toolbar button works, you can create some macro(s) and bind them to keycombo(s) for quick access.

For example, here are two possible macros (that could be added into `shortcuts.xml`):

        <Macro name="View ShowSymbol: show eol and control chars" Ctrl="no" Alt="no" Shift="no" Key="0">
            <Action type="2" message="0" wParam="44019" lParam="0" sParam="toggle ShowAllChars (cannot know which state it is in after this)" />
            <Action type="2" message="0" wParam="44025" lParam="0" sParam="toggle ShowSpaceAndTab; this will definitely uncheckmark ShowAllChars" />
            <Action type="2" message="0" wParam="44019" lParam="0" sParam="checkmark ShowAllChars (and all others will become checkmarked too)" />
            <Action type="2" message="0" wParam="44019" lParam="0" sParam="uncheckmark ShowAllChars (and all others will become uncheckmarked too)" />
            <Action type="2" message="0" wParam="44026" lParam="0" sParam="checkmark ShowEndOfLine" />
            <Action type="2" message="0" wParam="44131" lParam="0" sParam="checkmark ShowControlChars" />
        </Macro>
        <Macro name="View ShowSymbol: show everything except eol" Ctrl="no" Alt="no" Shift="no" Key="0">
            <Action type="2" message="0" wParam="44019" lParam="0" sParam="toggle ShowAllChars (cannot know which state it is in after this)" />
            <Action type="2" message="0" wParam="44025" lParam="0" sParam="toggle ShowSpaceAndTab; this will definitely uncheckmark ShowAllChars" />
            <Action type="2" message="0" wParam="44019" lParam="0" sParam="checkmark ShowAllChars (and all others will become checkmarked too)" />
            <Action type="2" message="0" wParam="44026" lParam="0" sParam="uncheckmark ShowEndOfLine" />
        </Macro>

Some notes on the macros:

* As `sParam` is unused for these commands, I've used it to embed some comments about the steps in the macros.

* The first 3 actions in the macros are the same; after these 3 actions it is guaranteed that all of the _View_ > _Show Symbol_ choices are checkmarked.  Macro logic can then continue from there to set or clear the various choices.

* I haven't bound any keycombos to these macros; that would be up to the user to decide on keycombos and then set that up.

Here are the command ids for the possible commands:

* _Show Space and Tab_ : 44025
* _Show End of Line_ : 44026
* _Show Non-Printing Characters_ : 44130
* _Show Control Characters & Unicode EOL_ : 44131
