### ISSUE TITLE
Notepad++ and NAS.

### ISSUE THREAD

**Issue by Spuner** [notepad-plus-plus/notepad-plus-plus#14836]
Why does it bring the NAS out of sleep mode when I run Notepad++.exe? This happens with both the installed version and the portable version. Notepad++ feels like it's sending a request over the network.

Notepad++ Version: 8.6.4
OS: Windows 10 Pro 22H2 x64 (Build: 19045.4046)

**Comment by xomx** [comment]
If it is really the N++ which causes that:
 - you could check the content of your N++ session.xml file (for the installed version in the %APPDATA%\\Notepad++\\ folder, otherwise in the main notepad++.exe folder), look there for any record of a file\path residing on your NAS (existing or not)
 - check also your N++ plugins possible NAS-file activities (you can append here also your N++ menu > ? > Debug Info... , there is the installed plugins list)

**Comment by Spuner** [comment]
> If it is really the N++ which causes that:
> 
> * you could check the content of your N++ session.xml file (for the installed version in the %APPDATA%\Notepad++\ folder, otherwise in the main notepad++.exe folder), look there for any record of a file\path residing on your NAS (existing or not)
> * check also your N++ plugins possible NAS-file activities (you can append here also your N++ menu > ? > Debug Info... , there is the installed plugins list)

- Here are the entire contents of the "session.xml" file.

```
<NotepadPlus>
<Session activeView="0">
<mainView activeIndex="0"/>
<subView activeIndex="0"/>
</Session>
</NotepadPlus>
```

- As for plugins... Two plugins are installed - DSpellCheck and ZoomDisabler. There are no more plugins.

**Comment by xomx** [comment]
How exactly you are launching the N++?
Do you use some command line parameters?

(This is why the users here should follow the issue template and should at least put here their N++ menu > ? > Debug Info...,  where is the important info for a help at one place...:
```
Notepad++ v8.6.4   (64-bit)
Build time : Feb 20 2024 - 00:12:59
Path : C:\Notepad++\Notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : ON
Cloud Config : OFF
OS Name : Windows 11 Pro (64-bit)
OS Version : 22H2
OS Build : 22621.3155
Current ANSI codepage : 1250
Plugins : ...
``` 
)

**Comment by Spuner** [comment]
```
Notepad++ v8.6.4   (64-bit)
Build time : Feb 20 2024 - 00:12:59
Path : D:\Various\Notepad++ (Mini-Portable)\Notepad++\notepad++.exe
Command Line : 
Admin mode : ON
Local Conf mode : ON
Cloud Config : OFF
OS Name : Windows 10 Pro (64-bit)
OS Version : 22H2
OS Build : 19045.4046
Current ANSI codepage : 1251
Plugins : 
    DSpellCheck (1.5)
    zoomdisabler_x64 (1.2)
```

**Comment by xomx** [comment]
How are you accessing the NAS from Windows - a mapped network drive/directory to a drive letter, SMB, webdav or some other way?

**Comment by Spuner** [comment]
SMB.

**Comment by xomx** [comment]
I tried, but cannot reproduce anything like that.

1. ensure that no N++ instance is running
2. dl & run the [Process Monitor](https://learn.microsoft.com/en-us/sysinternals/downloads/procmon)
3. add your filter(s) there and start capturing the N++ events:
   ![npp-PM-NAS](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/13075183/f8b711a9-016d-4ab1-b8a8-a8c3f1dc1316)
4. launch the N++
5. close the N++
6. switch back to procmon and stop capturing
7. look for any N++ IO pointing to your NAS

**Comment by Spuner** [comment]
I don't understand what's going on. Right now running Notepad++ does not bring the NAS out of sleep mode. When I first noticed this, I started to investigate this issue: I waited until the NAS went to sleep and started Notepad++ again, and the NAS woke up again, and so on several times. So I thought that Notepad++ wakes up the NAS. Then I disabled "Recent Files History", and after that everything started working fine. But I don't know if that was the reason or if it was just a coincidence.....

**Comment by xomx** [comment]
> Then I disabled "Recent Files History", and after that everything started working fine.

Seems you have nailed that - the default N++ behavior is to check its stored recent files list at startup to possibly erase the non-existing entries from it (that PathFileExists WINAPI call at line 592 is doing your NAS waking up here by issuing an IO request...):
https://github.com/notepad-plus-plus/notepad-plus-plus/blob/9d09ee818a2effcb54e4e7452dbd2c377bed835b/PowerEditor/src/Notepad_plus.cpp#L582-L596

**Comment by Spuner** [comment]
[xomx](https://github.com/xomx), maybe the reason was really in “Recent Files History”, but then I can’t explain one thing... I tried to play back the situation...

The sequence of my actions.

1. I Enabled "Recent Files History"
2. Logged into the NAS via SMB (Explorer)
3. Opened any *.txt file
4. Logged out of the NAS (closed Explorer)
5. I waited until he fell a sleep
6. And started Notepad++ again

And after all these actions, the NAS did not wake up. So I don’t know what to think anymore :-/

**Comment by xomx** [comment]
It is ok, just try to add one more step in between your steps 3. and 4. - Close that opened *.txt file.

This is another standard N++ behavior - the recent files list will not be populated until you close that opened file. And when you open that file again in N++, that RFL entry will be removed again.

**Comment by Spuner** [comment]
[xomx](https://github.com/xomx), sorry, I forgot to indicate this point. I close the *.txt file before exiting the NAS. I really hope this problem doesn't happen again )
