### ISSUE TITLE
The function "PathFileExists" causes confusion in the judgment of directories and files.

### ISSUE THREAD

**Issue by softmgr** [notepad-plus-plus/notepad-plus-plus#14839]
The program extensively uses the function "PathFileExists" to determine directories and files.
In the source code, the judgments about directories and files are confusing.
For example, if the directory "plugins" or "backup" is a file, it will also be judged as successful, but there may be problems with the subsequent execution of the program.

**Comment by alankilborn** [comment]
This is not a properly formed issue.  Please follow the issue template or you risk closure without further comment.

**Comment by xomx** [comment]
@alankilborn 
I think I know what the OP is trying to say. I also ran into this when I recently experimented with replacing this function in the N++ code with my own non-blocking cancellable variant (to solve the issues here with suddenly inaccessible network resources...). 

For example, N++ code here uses this function to determine if a file exists:
https://github.com/notepad-plus-plus/notepad-plus-plus/blob/83f0232d910444c6683a5dc104732b7c73c53b87/PowerEditor/src/MISC/Common/Common.cpp#L53-L61

But if the `file2read` here corresponds to an existing directory (and not to a file), the PathFileExists WINAPI also returns TRUE, which IMO is not what the author of this code-part intended to achieve.

**Comment by softmgr** [comment]
> This is not a properly formed issue. Please follow the issue template or you risk closure without further comment.

Sorry, I'm using the GITHUB mobile app to submit issue, but there are no issue templates in the app interface.

**Comment by softmgr** [comment]
> @alankilborn I think I know what the OP is trying to say. I also ran into this when I recently experimented with replacing this function in the N++ code with my own non-blocking cancellable variant (to solve the issues here with suddenly inaccessible network resources...).
> 
> For example, N++ code here uses this function to determine if a file exists:
> 
> https://github.com/notepad-plus-plus/notepad-plus-plus/blob/83f0232d910444c6683a5dc104732b7c73c53b87/PowerEditor/src/MISC/Common/Common.cpp#L53-L61
> 
> But if the `file2read` here corresponds to an existing directory (and not to a file), the PathFileExists WINAPI also returns TRUE, which IMO is not what the author of this code-part intended to achieve.

Add this function to Common.h and Common.cpp, I have tested.
`bool fileExists(const TCHAR* filename);`

`bool fileExists(const TCHAR* filename) {`
`	WIN32_FILE_ATTRIBUTE_DATA fileData;`
`	// Append special suffix \\?\ to allow path lengths up to 32767`
`	std::wstring path = L"\\\\?\\" + std::wstring(filename);`
`	if (!GetFileAttributesEx(path.c_str(), GET_FILEEX_INFO_LEVELS::GetFileExInfoStandard, &fileData))`
`		return false;`
`	//constexpr unsigned int FILE_ATTRIBUTE_DIRECTORY = 16;`
`	if ((fileData.dwFileAttributes & FILE_ATTRIBUTE_DIRECTORY) == 0)`
`		return true;`
`	return false;`
`}`

**Comment by alankilborn** [comment]
@xomx said:

> But if the `file2read` here corresponds to an existing directory (and not to a file), the PathFileExists WINAPI also returns TRUE, which IMO is not what the author of this code-part intended to achieve.

---

`::PathFileExists` calls in N++ code are _mostly_ attempting to get existence info about files, but _sometimes less often_ it is used for info about directories.  How about a new replacement function that would allow either... but with the "easiest" calling method, it would mean file-only? Example:

```
bool pathExists(const TCHAR* pathname, bool canBeFile = true, bool canBeDir = false)
{
	bool isExisting = false;
	if (!canBeFile && !canBeDir)
	{
		generic_string testPath(TEXT("\\\\?\\"));  // prepend special \\?\ prefix to allow path lengths up to 32767
		testPath += pathname;
		WIN32_FILE_ATTRIBUTE_DATA fileAttributeData;
		if (GetFileAttributesEx(testPath.c_str(), GET_FILEEX_INFO_LEVELS::GetFileExInfoStandard, &fileAttributeData))
		{
			if (canBeFile && canBeDir)
			{
				isExisting = true;
			}
			else
			{
				bool isFileNotDir = (fileAttributeData.dwFileAttributes & FILE_ATTRIBUTE_DIRECTORY) == 0;
				isExisting = isFileNotDir ? canBeFile : canBeDir;
			}
		}
	}
	return isExisting;
}
```

**Comment by xomx** [comment]
@alankilborn 

This issue relates to a misunderstanding of the ambiguity of the PathFileExist WINAPI. So I rather add & use simpler wrappers of your pathExists(...) proposed - fileExists(const TCHAR* fileName) & dirExists(const TCHAR* dirName). These will be calling your new universal pathExists(...). That way it will be clearer in the code what one is trying to achieve.

For both the file and dir existence, the current PathFileExist may remain in use.

**Comment by alankilborn** [comment]
> This issue relates to a misunderstanding of the ambiguity of the PathFileExist WINAPI.

I understand this.  It is because the _writers_ of that function have a strong feeling that a directory is just another type of file, whereas sometimes the _users_ (N++ programmers) have taken it to mean "file not dir".

---

>For both the file and dir existence, the current PathFileExist may remain in use.

Doesn't this idea just keep the old "problem" going?

---

Maybe my new suggestion is:

* `fileExists()`
* `dirExists()`
* `pathExists()` -- this one would be used to test "either", i.e. ANY type of existence

Would there then be a way to prevent calling of PathFileExists (again to keep the old "problem" from creeping back in)?
Example: programmer tries to call it, something intercepts that at compile time and suggests to use `fileExists`, `dirExists`, `pathExists` instead

Just some "make things better" ideas...

**Comment by rdipardo** [comment]
> EDIT: Maybe there isn't enough need for a function to check pure existence (i.e., that pathname is _either_ a file or a directory); in which case maybe a signature like this is better?: bool pathExists(const TCHAR* pathname, bool mustBeDir=false).

Not to be overly critical of pseudo-code, but in fact *anything* would be better than this:

> ```
>   if (!canBeFile && !canBeDir)
>   {
>        // . . .
>   }
> ```

Digital circuits are logic devices, and [De Morgan's][0] fundamental laws of logic tell us that `!A && !B` and `!( A || B )` mean the same thing (i.e., the last two columns identical):

| `canBeFile` (A) | `canBeDir` (B) | `!A` | `!B`   | `A ｜｜ B` | `!(A ｜｜ B)` | `!A && !B` |
|  :----:         |  :----:        | :---: | :---: | :----:    | :---:       | :---:  |
|    1            |      1         |  0   |  0     |    1       |   **0**         |  **0**        |
|    1            |      0         |  0   |  1     |    1       |   **0**         |  **0**        |
|    0            |      1         |  1   |  0     |    1       |   **0**         |  **0**        |
|    0            |      0         |  1   |  1     |    0       |   **1**         |  **1**        |

So the condition would be met *only* when it's neither a file, nor a directory.

[0]: https://wikipedia.org/wiki/De_Morgan%27s_laws

**Comment by alankilborn** [comment]
> Not to be overly critical of pseudo-code

It's fine to be critical, especially when something is wrong. :-)
I don't know that we needed to go down the DeMorgan's law road, though. :-)

Clearly (?), I was either (a) out of my mind ;-), or (b) wanting `if (canBeFile || canBeDir)` ... with the end goal of not running any further logic if both were false (just returning false in such a case).

**Comment by donho** [comment]
I do understand the concern. However, please provide the instructions to reproduce the bug.
Without it, it's not an issue to me.

**Comment by donho** [comment]
I would use the following function to replace PathFileExists:

```cpp
bool doesFileExists(wchar_t* filePath)
{
    DWORD dwAttrib = ::GetFileAttributesW(filePath);
    return (dwAttrib != INVALID_FILE_ATTRIBUTES && !(dwAttrib & FILE_ATTRIBUTE_DIRECTORY));
}
```

What do you guys think?

**Comment by donho** [comment]
@alankilborn 
> Are there places currently where PathFileExists is used to determine if a directory exists?

There could be, though I don't remember. If there are, the `doesDirectoryExist` will be defined and used.

> Is there a way to generate a build-time error if in the future some contributor attempts to call PathFileExists? If so, this error should direct the coder to use doesFileExists.

I don't think there's any "cheap" way to have  build-time error for using PathFileExists API. Even there is, it shouldn't be - there could still be the various reasons for using it. The simple code review can prevent it.

**Comment by xomx** [comment]
@donho 
It will work and it is enough (for now).

The using of that special prefix `\\?\` to allow checking for the long-paths is not necessary in N++ now, as it is currently limited to the MAX_PATH anyway. 

I have in progress some sort of a non-blocking cancellable IO variant of the PathFileExists to solve the N++  networking timeout issues (see e.g. the #8055 ), but it has not been tested yet, so I am for your `doesFileExist` for now.

**Comment by alankilborn** [comment]
>Is there a way to generate a build-time error if in the future some contributor attempts to call PathFileExists? If so, this error should direct the coder to use doesFileExists.

>I don't think there's any "cheap" way to have build-time error for using PathFileExists API. Even there is, it shouldn't be - there could still be the various reasons for using it. The simple code review can prevent it.

Yes, but there human memory is relied upon...a dubious prospect.  :-P

**Comment by nyamatongwe** [comment]
> Is there a way to generate a build-time error if in the future some contributor attempts to call PathFileExists?
~~~c++
#pragma deprecated(PathFileExists)
~~~
