### ISSUE TITLE
autocomplete preferences reset

### ISSUE THREAD

**Issue by Compaszer** [notepad-plus-plus/notepad-plus-plus#14831]
### Description of the Issue
The autocomplete preferences reset themselfs after I restart Npp. I'm not sure if all settings do so, but the "Auto-Insert {" and "Auto-Insert ' " settings definitely do.

### Expected Behavior
They stay as I set them.

### Actual Behavior
They do not persist.

### Debug Information
Notepad++ v8.6.4   (64-bit)
Build time : Feb 20 2024 - 00:12:59
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : <Redacted>
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 10 Home (64-bit)
OS Version : 22H2
OS Build : 19045.4046
Current ANSI codepage : 1252
Plugins : 
    JSMinNPP (1.2312)
    LuaScript (0.12)
    MarkdownViewerPlusPlus (0.8.2)
    mimeTools (3.1)
    NppConverter (4.6)
    NppExport (0.4)
    NPPJSONViewer (2.0.6)
    NppMarkdownPanel (0.7.3)
    XMLTools (3.1.1.13)

**Comment by Jeankree** [comment]
I have the same with personal Auto-Insert characters "<" and ">" (I tried with other characters, but it has the same behaviour).
In the meantime, I put the file config.xml READ-ONLY.
But... When I open again np++, tag doesn't insert automatically. I have to go to the Settings / Preference / Auto-Completion window (personal tags are still there) and close it, then it works.

**Comment by alankilborn** [comment]
With 8.6.5, I could not replicate the problem with `{` or `'`, but I definitely can with a matched-pair of `<` and `>`:

![image](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/77065706/f894c97a-40ed-4024-b726-d09ac31856ec)

Notepad++ v8.6.5   (64-bit)
Build time : Mar 29 2024 - 17:04:43
Path : C:\NotepadPlusPlus\Misc\_NoBackup\Releases\npp.8.6.5\npp.8.6.5.portable.x64\notepad++.exe
Command Line : -titleAdd="8.6.5 64-bit" -multiInst
Admin mode : OFF
Local Conf mode : ON
Cloud Config : OFF
Periodic Backup : ON
OS Name : Windows 11 Pro (64-bit
OS Version : 23H2
OS Build : 22631.3296
Current ANSI codepage : 1252
Plugins : 
    mimeTools (3.1)
    NppConverter (4.6)
    NppExport (0.4)

**Comment by alankilborn** [comment]
BTW, how come the `{ }` and `' '` hardcoded matched-pairs are showing both the open and close symbols, but `(` and `"` and `[` only show the opening characters of their respective pairs??

**Comment by Jeankree** [comment]
I updated this morning to 8.6.5 because of this problem, it still doesn't work for me.
This is my setting:
![immagine](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/126502015/87d7fec7-5d34-4135-8799-49b7fac487a4)

Notepad++ v8.6.5   (64-bit)
Build time : Mar 29 2024 - 17:04:43
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : "C:\Users\jc\Documents\Affaires\Desenzano Musica\MATERIALE\_Materiale per classe 2023-24\Coro\Va pensieroV3---PIANOFORTE ACCOMP   IN CORSO   .log"
Admin mode : ON
Local Conf mode : OFF
Cloud Config : OFF
Periodic Backup : OFF
OS Name : Windows 7 Home Premium (64-bit
OS Build : 7601.0
Current ANSI codepage : 1252
Plugins : 
    HexEditor (0.9.12)
    HTMLTag (1.3.7)
    mimeTools (3.1)
    NppConverter (4.6)
    NppEventExec (0.9)
    NppExec (0.8.4)
    NppExport (0.4)
    NppXmlTreeviewPlugin (2)
    XMLTools (3.1.1.13)

**Comment by Jeankree** [comment]
> BTW, how come the `{ }` and `' '` hardcoded matched-pairs are showing both the open and close symbols, but `(` and `"` and `[` only show the opening characters of their respective pairs??

As you can see in my last screenshot above, in latest English version (v8.6.5 64-bit for windows) all pairs are showing both opening and closing symbol. Only single quote `'` is not… Maybe you are using some other version (older, or 32-bits, or another system…)? Or maybe do you use np++ in another language than English? (translation problem?)

**Comment by mpheath** [comment]
@alankilborn @Jeankree The display probably has something to do with the checked/unchecked status.

https://github.com/notepad-plus-plus/notepad-plus-plus/blob/e0bb723700c2ed75da90284bcf0e33300e3463ff/PowerEditor/src/WinControls/Preference/preferenceDlg.cpp#L4750

---

Looking at the OP issue:

There are 2 source code names that handle the user pairs.

 * `_matchedPairsInit`

   1. Stores the user pairs read from the xml file.
   2. User pairs are inserted into the Preferences dialog edit ctrls.

 * `_matchedPairs`

   1. **Init**ially empty.
   2. Stores user pairs from Preferences dialog edit ctrls.
   3. User pairs are saved to the xml file.

User pairs Auto-Insert will not operate until the Preferences dialog is opened as that is when the pairs are stored into `_matchedPairs`. If the Preferences dialog is not opened in an instance of Notepad++, then the user pairs will not be saved to the xml file.

Related: b0ad8ca #3171 #8063 #12547
