### ISSUE TITLE
How to download test build?

### ISSUE THREAD

**Issue by kubalav** [notepad-plus-plus/notepad-plus-plus#14849]
It seems that the [Wiki page](https://github.com/notepad-plus-plus/notepad-plus-plus/wiki/Testing) needs to be updated. Can you advice me how to download the test builds?

**Comment by rddim** [comment]
1. `Sign in` - required
2. Go to `Actions`
3. Select the workflow that you want
4. Scroll to the bottom - `Artifacts`

You can open the `Actions` without signed in, but you can not download

**Comment by kubalav** [comment]
Thank you, man.
