### ISSUE TITLE
Release Key Expires 2024-03-11

### ISSUE THREAD

**Issue by DavidHaslam** [notepad-plus-plus/notepad-plus-plus#14840]
The release key described in the ReadMe states that it expires on 2024-03-11 which is in 3 days time.

In case there’s no automatic notification from the key authority, this is a prompt to take action.

**Comment by donho** [comment]
Thank you for your heads up.
The certificate has been extended 3 more years.

**Comment by donho** [comment]
https://github.com/notepad-plus-plus/notepad-plus-plus/commit/2ac5e3a7ed23b5b8e39d84601e052eff917819ac

**Comment by DavidHaslam** [comment]
@donho

Please remember to update the project readme.md to show the new expiry date.

**Comment by donho** [comment]
Thank you.
Done: https://github.com/notepad-plus-plus/notepad-plus-plus/commit/9d848b6a4758c4ea63b364c0c3a1941f0ac77b31
