### ISSUE TITLE
borad vs board typo in source code

### ISSUE THREAD

**Issue by alankilborn** [notepad-plus-plus/notepad-plus-plus#14847]
https://github.com/notepad-plus-plus/notepad-plus-plus/blob/9d92b0a86939e391a8fc709c97de0929532b986f/PowerEditor/src/MISC/Common/Common.cpp#L953

`buf2Clipborad` should be `buf2Clipboard`

@donho : You fix, me fix, or ?

**Comment by gitgrub** [comment]
sharp eyes :)

**Comment by donho** [comment]
@alankilborn 
Thank you for the heads up.
I'll do it.
