### ISSUE TITLE
Small code optimization

### ISSUE THREAD

**Issue by chcg** [notepad-plus-plus/notepad-plus-plus#14843]
### Description of the Issue
- Scope of var wmc is bigger than needed in FileManager::saveBuffer()
- grabSize is not initialized
- remove unused var in TreeView::searchLeafRecusivelyAndBuildTree()
- missing nullpointer check in ScintillaEditView::init()

### Steps to Reproduce the Issue
N/A

### Expected Behavior
N/A

### Actual Behavior
N/A

### Debug Information
N/A

**Comment by MarkusBodensee** [comment]
PR is merged, but auto closing this issue didn't work. Can be closed manually.

**Comment by donho** [comment]
https://github.com/notepad-plus-plus/notepad-plus-plus/commit/9d09ee818a2effcb54e4e7452dbd2c377bed835b
