### ISSUE TITLE
notepad++ crash after massive tab operation

### ISSUE THREAD

**Issue by FAMOSTester** [notepad-plus-plus/notepad-plus-plus#14852]
### Description of the Issue
After working a lot in a text document (no difference what coding) with a lot (200-300, uncounted) of tab operations 
notepad++ hang up and shows a white text field with some words/fragments of words.
After closing the whole window the text is still there...
This behaviour is reproducable!

### Steps to Reproduce the Issue
1. Use a text with more than 500 rows (i don't know if this is important) 
2. Modify some rows with using the tab to move the words
3. After doing this more than 100 times notepad will "crash" and this "white" screen occours

![notepad++_01](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/24524310/4b42429a-8061-41ae-8e4b-a4efebfa16ec)

![notepad++_02](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/24524310/4c6f20da-3180-4938-886e-faf61ac75ee8)

### Debug Information
Notepad++ v8.6.4   (64-bit)
Build time : Feb 20 2024 - 00:12:59
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 10 Enterprise (64-bit)
OS Version : 22H2
OS Build : 19045.4046
Current ANSI codepage : 1252
Plugins : 
    ComparePlugin (2.0.2)
    ComparePlus (1.1)
    DSpellCheck (1.5)
    HexEditor (0.9.12)
    HTMLTag (1.4.3)
    JsonTools (6.1.1)
    Linefilter3 (1)
    MarkdownViewerPlusPlus (0.8.2)
    mimeTools (3.1)
    Npp-Highlighter (1.0.0.1)
    NppConverter (4.6)
    NppExport (0.4)
    NPPJSONViewer (2.0.7)
    NppMarkdownPanel (0.7.3)
    NppTextFX (1.4.1)
    PlantUmlViewer (1.6.0.10)
    Python Indent (1.0.0.5)
    PythonScript (2)
    RegexTrainer (1.2)
    Remove Duplicate Lines (1.3)
    XMLTools (3.1.1.13)

**Comment by alankilborn** [comment]
>This behaviour is reprducable!

First, you need to remove all of that long list of plugins, and then see if the behavior is reproducible.

**Comment by FAMOSTester** [comment]
i will try

**Comment by rdipardo** [comment]
> It looks like one of the now uninstalled plugins caused the problem. Unfortunately, I don't have the time to test each of them again now.

Just from looking at the complete plugin collection:

> ComparePlugin (2.0.2)
> ComparePlus (1.1)

These are, functionally and historically, [the same plugin][0]. ComparePlugin was deprecated and renamed as ComparePlus in [September 2022][1].

> NppTextFX (1.4.1)

Using both NppTextFX and a version of ComparePlus [before 1.2][2] is [known][3] to crash the editor, as they both modify the status bar, and when NppTextFX goes first it will corrupt a memory block that ComparePlus 1.1 and older versions attempt to access.

> Npp-Highlighter (1.0.0.1)

See:

- https://github.com/michaelxzhang/Npp-Highlighter/issues/26

- https://github.com/notepad-plus-plus/notepad-plus-plus/issues/14564


[0]: https://github.com/pnedev/comparePlus/blob/0b6f9425e1cb19ea8c103c8410c62f113a09f7fc/README.md?plain=1#L46
[1]: https://github.com/notepad-plus-plus/nppPluginList/pull/493/files#diff-f87810c274c1b91e9e18358cb1203fa76a325899a8a188773ee1abcb4083d428
[2]: https://github.com/pnedev/comparePlus/issues/370#issuecomment-1763880760
[3]: https://github.com/rainman74/NPPTextFX2/issues/19

**Comment by FAMOSTester** [comment]
@rdipardo: Many thanks for this explanation! 
I will try it out. Actually the Compare Plugin is the most important for me. 
Greets Wolfgang

**Comment by FAMOSTester** [comment]
In this case i close the issue.

**Comment by donho** [comment]
@FAMOSTester 
Could you confirm that removing Npp-Highlighter has fixed your problem?
