### ISSUE TITLE
Refactor FindFirstFile/FindNextFile code blocks to avoid lengthy repetition of the same code

### ISSUE THREAD

**Issue by alankilborn** [notepad-plus-plus/notepad-plus-plus#14853]
In several places in the N++ code, there is this type of logic, expressed here in somewhat-pseudocode:

```
h = ::FindFirstFile()
if (h != INVALID_HANDLE_VALUE)
    code block "A"
while (::FindNextFile())
    code block "A"
::FindClose()
```

This would be okay if `code block "A"` was a line or even 2.
But when this code block is 10+ non-trivial lines, it becomes somewhat of a "how do I read this code" hassle and a future-maintenance nightmare (as the exact same potential changes would need to be made in 2 places); and it doesn't need to be either of these things.

The logic should be restructured as:

```
if (::FindFirstFile() != INVALID_HANDLE_VALUE)
{
    do
    {
        code block "A"
    } while (::FindNextFile());
    ::FindClose();
}
```
---

Here are some areas of the code in question; links are to the FindFirstFile call:

* https://github.com/notepad-plus-plus/notepad-plus-plus/blob/aa0be9973ba6cf1c4206952de75655436accbcfa/PowerEditor/src/Notepad_plus.cpp#L1828
* https://github.com/notepad-plus-plus/notepad-plus-plus/blob/aa0be9973ba6cf1c4206952de75655436accbcfa/PowerEditor/src/WinControls/FileBrowser/fileBrowser.cpp#L887

Even this area of the code, where only 3 lines are duplicated, could benefit from the above restructuring suggestion:
* https://github.com/notepad-plus-plus/notepad-plus-plus/blob/aa0be9973ba6cf1c4206952de75655436accbcfa/PowerEditor/src/MISC/Common/Common.cpp#L1344

---

Finally, here's a section of code that does it "correctly", for reference, and need not be refactored:
* https://github.com/notepad-plus-plus/notepad-plus-plus/blob/9251955d106c1dd482cc53e43e50267be8027111/PowerEditor/src/ScintillaComponent/AutoCompletion.cpp#L637

---

Comments are based on the state of the code after the 8.6.4 release but before any releases beyond that.

**Comment by alankilborn** [comment]
@donho What do you think of such a refactoring? Would you accept it?

( Note: I discovered this as I was experimenting with a possible solution for #14617 )

**Comment by donho** [comment]
@alankilborn 
OK for the refactoring. 
BTW, please fix the type #14847 in the same PR.
Thank you!

**Comment by donho** [comment]
@alankilborn 
Could you please also include a typo-fix which is notified here in the new PR:
https://github.com/notepad-plus-plus/notepad-plus-plus/commit/060396c6988e278dbc10208099010947e72be6dc#r139323315

Thank you very much!

**Comment by alankilborn** [comment]
For the affected code in Common.cpp, there's an additional (minor) bug with the current code.
The code currently only runs to find `*.xml` files for UDL.
BUT...because of the bug, if a _directory_ happens to be named with a `.xml` extension (rare for directories to have extensions, I know...), then the _directory_ would be added to what is supposed to be a vector of only _file_ paths...
