### ISSUE TITLE
As of v8.6.3 a search/replace that results in a link no longer gets auto-underlined

### ISSUE THREAD

**Issue by mkupper** [notepad-plus-plus/notepad-plus-plus#14864]
### Description of the Issue

I was using v8.6.4 and had
```
xyzzy
```
I did a search/replace:
**Search: `^xyzzy`
Replace: `https://notepad-plus-plus.org/`**

`https://notepad-plus-plus.org/` appeared but it was not underlined and was not clickable. If you then scroll the page or make any changes then `https://notepad-plus-plus.org/` gets underlined and is clickable.

With Notepad++ v8.6.2 and earlier the link was underlined immediately after the search/replace. A change related to v8.6.3 RC1 on out broke this.

The exact search/replace does not matter as long as it's one that creates a file:// or https?:// style string of text that is normally underlined and clickable.

The https://community.notepad-plus-plus.org/topic/25577/link-underlines-no-longer-auto-applied-on-search-replace forum thread has thoughts about what caused this change in behavior.

**Comment by molsonkiko** [comment]
This issue appears to be fixed by [this commit](https://github.com/molsonkiko/notepad-plus-plus/commit/60c58faca66229a12e6ca2615fc33ca3bf28862a). Give it a try!
