### ISSUE TITLE
Search-results output has unconventional subfolder ordering

### ISSUE THREAD

**Issue by alankilborn** [notepad-plus-plus/notepad-plus-plus#14885]
### Description of the Issue
When doing a _Find in Files_ on a folder tree, it is conventional to show results closest to the top/root of the tree _first_ in the output; Notepad++ currently displays the tree inverted, i.e., closest-to-top _last_.

### Steps to Reproduce (STR) the Issue

1. Extract the attached `dir0.zip` to a temporary folder on your disk (I chose to do it to `C:\JUNK\` such that after the extraction I had `C:\JUNK\dir0\...`) [dir0.zip](https://github.com/notepad-plus-plus/notepad-plus-plus/files/14666453/dir0.zip)
2. Invoke _Find in Files_ via Shift+Ctrl+f and set up the following search (changing the _Directory_ as to your specific temporary folder extraction of the zip file)
![image](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/77065706/1a3100a1-18ac-4ac1-a347-31cb2e9a1e6b)
3. Press _Find All_
4. Right-click in the _Search results_ window and choose _Fold All_
5. Click the `+` in the box to the left of `Search "t"`...

### Actual Behavior
Bottom-up output:

![image](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/77065706/5831f1d5-da8c-4250-9e36-b8570645e3f7)

### Expected Behavior
Top-down output:
```txt
C:\JUNK\dir0\t.txt
C:\JUNK\dir0\dir1\t.txt
C:\JUNK\dir0\dir1\dir2\t.txt
C:\JUNK\dir0\dir1\dir2\dir3\t.txt
C:\JUNK\dir0\dir1\dir2\dir3\dir4\t.txt
C:\JUNK\dir0\dir1\dir2\dir3\dir4\dir5\t.txt
C:\JUNK\dir0\dir1\dir2\dir3\dir4\dir5\dir6\t.txt
```

---

### **EDIT** to add:

It appears that the output might be sorted (ascending) by the full file pathname.

Repeat the STR with after extracting this alternate zip: 
[dir0_a.zip](https://github.com/notepad-plus-plus/notepad-plus-plus/files/14694236/dir0_a.zip)

to obtain:

![image](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/77065706/070c1cc7-4cfd-4bec-bd3f-ed4637ba8a36)

And still, the following would be a much more expected output (where the files closest to the top of the directory tree are presented first):

```txt
C:\JUNK\dir0\a.txt
C:\JUNK\dir0\t.txt
C:\JUNK\dir0\dir1\a.txt
C:\JUNK\dir0\dir1\t.txt
C:\JUNK\dir0\dir1\dir2\a.txt
C:\JUNK\dir0\dir1\dir2\t.txt
C:\JUNK\dir0\dir1\dir2\dir3\a.txt
C:\JUNK\dir0\dir1\dir2\dir3\t.txt
C:\JUNK\dir0\dir1\dir2\dir3\dir4\a.txt
C:\JUNK\dir0\dir1\dir2\dir3\dir4\t.txt
C:\JUNK\dir0\dir1\dir2\dir3\dir4\dir5\a.txt
C:\JUNK\dir0\dir1\dir2\dir3\dir4\dir5\t.txt
C:\JUNK\dir0\dir1\dir2\dir3\dir4\dir5\dir6\a.txt
C:\JUNK\dir0\dir1\dir2\dir3\dir4\dir5\dir6\t.txt
```

---

### Debug Information
Notepad++ v8.6.4   (64-bit)
Build time : Feb 20 2024 - 00:12:59
Path : C:\NotepadPlusPlus\Misc\_NoBackup\Releases\npp.8.6.4\npp.8.6.4.portable.x64\notepad++.exe
Command Line : -multiInst
Admin mode : OFF
Local Conf mode : ON
Cloud Config : OFF
OS Name : Windows 11 Pro (64-bit)
OS Version : 23H2
OS Build : 22631.3155
Current ANSI codepage : 1252
Plugins : 
    mimeTools (3.1)
    NppConverter (4.6)
    NppExport (0.4)

**Comment by pryrt** [comment]
With the first example, I was thinking it had just been a depth-first search, which makes sense algorithmically, though isn't what everyone is expecting.  But with that second, it's obviously not depth-first, and does appear to be purely alphabetical. 

I think displaying them alphabetical-by-file in a given layer, followed by alphabetical by subdirectory from that level would make the most sense to a user.  And that's what Alan's "expected results" indicate, so I guess I'm saying "I agree, that would be best" ;-)

**Comment by alankilborn** [comment]
I think it is merely an effect from the recursion used, without further treatment.
This often happens with "simple" recursion algorithms.
As soon as a directory is detected, it is diven into, and this keeps happening as files and dirs are processed at that lower level.

For example, following the `dir0\a.txt` file, directory after directory (and their files) are encountered and processed, leaving `dir0\t.txt` as the last thing processed (all the recursive/directory processing has been completed).

A better algorithm would be to build a list of all of the directories, in depth-order, first.  Then start searching those directories for files.  I don't think any sorting needs to occur, as the natural order (as returned by FindFirstFile/FindNextFile seems sufficient).  I believe that following this scheme would produce my expected output.

**Comment by alexprabhat99** [comment]
@alankilborn Could you please check out my PR #14899 which attempts to order search results output as is expected in this issue. This is my first attempt at contributing to any open source project. Your feedback would certainly help me improve. Thanks in advance!

**Comment by donho** [comment]
The existing Find in Files algorithm, while not flawless, effectively performs its task iteratively and recursively, ensuring that no files remain unsearched. However, altering this non-buggy algorithm could potentially introduce regressions.

While I consider this feature desirable, the associated risk of regression is not acceptable. Therefore, I stand by my rejection, and I hope my reasoning is clear.

**Comment by alankilborn** [comment]
@donho

---

> While I consider this feature desirable

That's good, we have agreement.

---

>the associated risk of regression is not acceptable

Can't we just prove that a feature's implementation doesn't create a regression, and then it can be accepted?
Note that I haven't looked at or tested the implementation in #14899, I'm just speaking generally here.

**Comment by donho** [comment]
@alankilborn 
> Can't we just prove that a feature's implementation doesn't create a regression, and then it can be accepted?
Note that I haven't looked at or tested the implementation in https://github.com/notepad-plus-plus/notepad-plus-plus/pull/14899, I'm just speaking generally here.

That’s a good question, and the criteria are indeed not obvious. In general, a completely new feature is more likely to be accepted (provided it’s a good feature, and, of course, judged by me). Alternatively, a behavior change involving a small amount of code is preferable because it has less impact on the current behavior of the application.

Regarding this feature request, even if the impact could be significant, if there were a large number of people who needed such behavior, it would likely be accepted. However, in this case, I prefer that either I or the devs I trust handle the change.

This list could give you a general idea for which kind of feature request will be accepted:
https://github.com/notepad-plus-plus/notepad-plus-plus/pulls?q=is%3Apr+is%3Aclosed

**Comment by alankilborn** [comment]
>if there were a large number of people who needed such behavior

This one isn't a "need", it is more of a "this new way would be nicer".  But that seems equally as valid.

---

>I prefer that either I or the devs I trust handle the change.

How about a "dev you sort-of-trust".  Me.  :-)
I created this issue, and I was going to code it as well.

But I'd dislike casting aside the coding that's been attempted so far, without even looking at it...that doesn't seem fair to someone that's put their effort in.  I'll take a look at the code that's been done...

**Comment by donho** [comment]
> How about a "dev you sort-of-trust". Me. :-)
I created this issue, and I was going to code it as well.

It seems to me that this pre-condition is not fullfilled:

**Comment by alankilborn** [comment]
> if there were a large number of people who needed such behavior

Probably a decent number of people have observed a mess such as this:

![image](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/77065706/210393e9-1f1e-4da7-84d0-64b71bde061b)

Then thought: "WTF kind of ridiculous output ordering is this?" ...shrugged... and thought: "Well, at least it _did_ the search." ...and moved on...

You've always been big on "let's see if a large number of users want this ... or complain about that..."
IMO that's a cop out for a feature you don't really want, even though things like this are said: "while I consider this feature desirable..."

You should be listening to the smaller group of users that care about making things better, e.g. comment contributors on this thread.  Then the larger user group benefits, without having to put the effort into complaining (which they won't do, because they're interested only in getting their text-editing job done, not making a better thing).

**Comment by alankilborn** [comment]
Poll taken about how users feel:  https://community.notepad-plus-plus.org/topic/25634
