### ISSUE TITLE
Impossible to change the default tab size

### ISSUE THREAD

**Issue by tbrcrl** [notepad-plus-plus/notepad-plus-plus#1490]
Hello, in the following the description of the issue.

OS Win 8.1 64 bit
Notepad ++ 6.8.8
Screen resolution 1920 x 1080

Way to reproduce
Go to Settings / Preferences / Tab settings
Choose [Default]
Click on the number of Tab size
A window will open
Change the number for example from 4 to 2
At this point in time click on the Close button (no other buttons are available)
The window with the changed number will blink and an error sound is emitted (the window is not resizeable)
(screenshot attached)
The same will happen if I try to change the tab size for a specific language

Any suggestion?

Thanks
![cattura di schermata 1703](https://cloud.githubusercontent.com/assets/16580030/13112117/d3af17b0-d589-11e5-8aed-de7339870214.png)

**Comment by dail8859** [comment]
After typing the number, press `Enter`.

**Comment by tbrcrl** [comment]
Thanks so much, everything is OK now.
