### ISSUE TITLE
Inconsistencies in listing functions in Function list

### ISSUE THREAD

**Issue by ronww** [notepad-plus-plus/notepad-plus-plus#14908]
### Description of the Issue
In this example:
This function appears in the function list:
    function AproxU8 (n : Vt.U8; x : Vt.U8) return Boolean is
        eq : Boolean := False;
    begin
        -- code
        return eq;
    end AproxU8;

 But this function does not:
    function Read_I32 (Register : Vt.Address_Range) return Vt.Int_32 is
        Data : Vt.Int_32;
    begin
        -- code
        return Data;
    end Read_ I32;

### Steps to Reproduce the Issue
1. Enter above example as an Ada source file
2. Enable Function List
3. Observe one function is listed but the other is not

### Expected Behavior
Both functions be listed in Function List

### Actual Behavior
one function is listed but the other is not

### Debug Information
Notepad++ v8.6.4   (64-bit)
Build time : Feb 20 2024 - 00:12:59
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line :
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 10 Enterprise (64-bit)
OS Version : 22H2
OS Build : 19045.4170
Current ANSI codepage : 1252
Plugins :
    DSpellCheck (1.5)
    mimeTools (3.1)
    NppConverter (4.6)
    NppExport (0.4)

**Comment by chcg** [comment]
The relevant file is https://github.com/notepad-plus-plus/notepad-plus-plus/blob/master/PowerEditor/installer/functionList/ada.xml . Seems function is not covered by the randomly selected from the internet unittest input file https://github.com/notepad-plus-plus/notepad-plus-plus/blob/master/PowerEditor/Test/FunctionList/ada/unittest .

**Comment by ronww** [comment]
Perhaps this is also the reason for: https://github.com/notepad-plus-plus/notepad-plus-plus/issues/14687

**Comment by notdodgeball** [comment]
Add the literal dot as a valid identifier at line 50 in your ada.xml file:
[A-Za-z_\.]\w*

The later function will now be listed.

The ada function parser clearly needs some work, not sure why the keywords are case sensitive, and it does not work with parameters across multiple lines.

**Comment by notdodgeball** [comment]
Actually the newline thing is a problem across the board apparently, related to #14754

**Comment by ronww** [comment]
I tested this change and it appears to work for my current project.

**Comment by ronww** [comment]
Functions/procedure specifications and definitions with comments in the parameter list fail to show in the Function List

Example:
procedure Test_Get_Register(
Reg : Address_Range; -- Register to test
Page : Page_Range; -- Page of target register
ID : String; -- Test case identification
) is
begin
-- code
end Test_Get_Register;

If the comments in the parameter list are removed, then the procedure is shown.

**Comment by MAPJe71** [comment]
see https://community.notepad-plus-plus.org/topic/19480/faq-function-list-basics
