### ISSUE TITLE
Search Mode Extended does not work in some cases

### ISSUE THREAD

**Issue by superbonaci** [notepad-plus-plus/notepad-plus-plus#14909]
### Description of the Issue
New file and paste:

```
//Downloads//bin/://Users//Downloads//bin/
```
Try to replace `:` with a newline `\n`. Does not work:

![2024-03-27](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/8339596/23667331-df52-4808-9671-3b0ac8342b78)

### Debug Information

Notepad++ v8.6.4   (64-bit)
Build time : Feb 20 2024 - 00:12:59
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 11 Pro (64-bit)
OS Version : 21H2
OS Build : 22000.2538
Current ANSI codepage : 1252
Plugins : 
    mimeTools (3.1)
    NppConverter (4.6)
    NppExport (0.4)
    NPPJSONViewer (2.0.6)

**Comment by superbonaci** [comment]
It works if `Wrap around` is selected, for some reason...

**Comment by alankilborn** [comment]
In the status bar in your screenshot it shows you "...from caret to end-of-file".  Thus, you can infer that your caret, when the _Replace All_ was invoked, was closer to the end of your file than any `:` and so there was nothing to replace.

By checkmarking _Wrap around_, the replacement operation considers the entire file; indeed after pressing _Replace All_ with _Wrap around_ checkmarked, the status bar will say "...occurrences were replaced in entire file".

User manual [REF](https://npp-user-manual.org/docs/searching/#:~:text=If%20checked%2C%20when%20the%20search%20reaches%20the%20end%20of%20the%20document%2C%20it%20will%20wrap%20around%20to%20the%20beginning%20and%20continue%20searching.).

Please close this issue.

**Comment by alankilborn** [comment]
Also, is the file you are working on a "Windows" file?  (Check the Notepad++ main window status bar for `Windows (CR LF)`).  If so, then by replacing with `\n` you are likely corrupting your file.  The degree of corruption depends upon what you intend to do with your file after creating it.  With a Windows file, you should replace with `\r\n` instead.

**Comment by superbonaci** [comment]
The file is new created by notepad++ just to paste some text (from echo "$PATH") and view it nicer each path in a line, so that doesn't matter.

The reason it didn't work is because after pasting the cursor is after the pasted text hence didn't replace from the beginning.

Working as expected so closing.
