### ISSUE TITLE
Google search with 2+ lines gives 400 error

### ISSUE THREAD

**Issue by weirdal3333** [notepad-plus-plus/notepad-plus-plus#1491]
Whenever I search for something with more than 2 lines using the google search in the program it gives me a 400 error.

**Example:**
Search:

```
notepad++
is awesome!
```

The address it uses is:
`http://www.google.com/search?q=notepad++is%20awesome!`
For some reason it will **NOT WORK**.
A good potential workaround is changing the protocol to https.
`https://www.google.com/search?q=notepad++is%20awesome!`

**Comment by dail8859** [comment]
What version of Notepad++ do you have? It works for me. It looks like it is [already using https](https://github.com/notepad-plus-plus/notepad-plus-plus/blob/35adb1910ba98897ad3a935fa7d712a986289bd3/PowerEditor/src/shortcuts.xml#L15) by default.

**Comment by weirdal3333** [comment]
Now that i'm back at my own computer... It works?
Both versions of Notepad++ are the same.
There must have been something with the proxy server at my school that that messed with the program.
I will try this again tomorrow and report back with my findings.

**Comment by dail8859** [comment]
I would guess proxy or browser. If I enter that URL into my browser using http I get redirected to https.

**Comment by lockandstrike** [comment]
Is this issue resolved or does it still need to be fixed?

**Comment by dail8859** [comment]
It would seem it is not actually an issue that needs fixed and could be closed.

**Comment by SinghRajenM** [comment]
@MetaChuh as @dail8859 mentioned it should be closed.
