### ISSUE TITLE
Not showing Emojis with multiple codepoints correctly even with DirectWrite enabled

### ISSUE THREAD

**Issue by myonlylonely** [notepad-plus-plus/notepad-plus-plus#14918]
### Description of the Issue
DirectWrite is enabled.
It shows normal Emojis correctly. But Emojis with multiple codepoints combination don't show correctly.

For example, 👩‍👩‍👧‍👧 is not showing correctly.

Notepad++:
![image](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/8188177/13ab3093-3e45-402a-9ae6-91899c4cef82)

Windows notepad:
![image](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/8188177/d5d4f7df-e4f9-43c9-9dc6-0a55167dcc6e)

**Comment by byzod** [comment]
There're so many feature about emoji not working, too lazy to create an issue so just post here:

All `Edit > Line Operation > Sort line xxx` are not working with emoji

**Comment by molsonkiko** [comment]
@byzod 
> There're so many feature about emoji not working, too lazy to create an issue so just post here

If you're "too lazy" to create an issue, I expect the developers will be "too lazy" to fix the issue for you.

Don't expect busy developers to prioritize helping you if you don't put some effort into explaining what you want, and making a case for why it's worth their time. Yes, this means creating an issue. Alternatively, you could go to the [community forum](https://community.notepad-plus-plus.org/) and ask for guidance there.

@myonlylonely 

__This is correct behavior__, not a problem with Notepad++! The reason you're seeing the `ZWJ` control characters is that you have the [Show All Characters](https://npp-user-manual.org/docs/views/#show-symbol) menu item checked. I'll show you what I mean:

With `Show All Characters` __checked:__

![image](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/46202915/5d445087-5e6d-43f7-8bc0-759c87673b15)

With `Show All Characters` __unchecked:__

![image](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/46202915/33e018b1-d793-4d5f-ad1e-e7ab042c30ad)

**Comment by byzod** [comment]
> @byzod
> 
> Don't expect busy developers to prioritize helping you if you don't put some effort into explaining what you want

I think you're suppose that I'm not busy and has 24 hours per day to test 1000 edge cases of emoji bugs for npp, yes?

**Comment by myonlylonely** [comment]
@molsonkiko OK, I'll close this issue.
