### ISSUE TITLE
Find dialog box hidden behind start menu/taskbar

### ISSUE THREAD

**Issue by wyattsl1972** [notepad-plus-plus/notepad-plus-plus#14913]
### Description of the Issue
Minor issue:   If you move the START MENU BAR/TASKBAR (where you launch programs on windows) from the bottom of the screen to the LEFT-HAND SIDE of the screen, when you open FIND (CTRL-F), the dialog box is hidden behind the start menu/task bar.
I have to then "move" the dialog box right so I can see it.
It would be nice if the dialog box considered the "available" screen geometry instead of actual screen geometry.

### Steps to Reproduce the Issue

1.   Move the start menu/task bar to the LEFT-hand side of the screen
2.   Open notepad++
3.   Press CTRL-F
4.   the dialog box will be hidden behind the taskbar

### Expected Behavior
have the dialog box open more to the right so it can be seen.

### Actual Behavior
its hidden.

### Debug Information
n/a

**Comment by wyattsl1972** [comment]
I do understand what you are saying, however, I often load NPP using
"RUNAS" so that it runs under a different user context.  When that happens,
it does not remember.  Because of that, I see the "overlay" problem all of
the time.

-stephen

**Comment by alankilborn** [comment]
Possible workaround:  If you press Ctrl+f twice in succession, it should center the _Find_ window on the Notepad++ main window (I'm thinking that this would move it from being covered by the left-side task bar).

**Comment by wyattsl1972** [comment]
Thanks for the tip!   That works perfectly.

-stephen

**Comment by whindsaks** [comment]
> the "available" screen geometry

The desktop area not covered by the taskbar and other app bars is called the work area, GetMonitorInfo knows this rectangle.
