### ISSUE TITLE
Update GPG key on notepad-plus-plus.org

### ISSUE THREAD

**Issue by cschneegans** [notepad-plus-plus/notepad-plus-plus#14920]
### Description of the Issue

The [GPG Notepad++ Public key](https://notepad-plus-plus.org/gpg/nppGpgPub.asc) link on **notepad-plus-plus.org** refers to an [older version](https://github.com/notepad-plus-plus/notepad-plus-plus/blob/c0760e49c67ae43a361f93e34a43dbdc0ba49a76/nppGpgPub.asc) of the GPG key (which has since been expired), not [the current one](https://github.com/notepad-plus-plus/notepad-plus-plus/blob/2ac5e3a7ed23b5b8e39d84601e052eff917819ac/nppGpgPub.asc).

**Comment by donho** [comment]
Updated.
Thank you for your heads up.
