### ISSUE TITLE
 Ctrl+Shift+... not registered in npp shortcutmanager but type sys chars

### ISSUE THREAD

**Issue by kuzduk** [notepad-plus-plus/notepad-plus-plus#14934]
### Description of the Issue
I press:
Ctrl+Shift+Q
Ctrl+Shift+W
Ctrl+Shift+E
Ctrl+Shift+R
...
This shortcuts not registered in npp shortcutmanager and OnKeyDown must do nothing but… I enable “Show all characters” and see a lot of hide and not unnecessary: system chars typed in text file quietly!!! I want for sys chars not typed so via Ctrl+Shift+… How i can disable this unnecessary?

### Steps to Reproduce the Issue

1. Ctrl+Shift+Q. not registered in npp shortcutmanager but type sys chars
2. press this shortcut
3. erorrly type sys chars

### Expected Behavior
Ctrl+Shift+Q. not registered in npp shortcutmanager  => NOTHING

### Actual Behavior
erorrly type sys chars DC1, ETB...

### Debug Information
Notepad++ v8.5.8 - 8.6.5   (64-bit)
Build time : Oct 15 2023 - 21:43:56
Path : E:\! SOFT\Total Commander\!KU\Notepad++\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : ON
Cloud Config : OFF
OS Name : Windows 10 Pro (64-bit)
OS Version : 22H2
OS Build : 19045.2311
Current ANSI codepage : 1251
Plugins : 
    DSpellCheck (1.5)
    mimeTools (3.1)
    NppConverter (4.6)
    NppExport (0.4)
    PythonScript (2)
    _CustomizeToolbar (5.3)

![10b4573a83b49c4ca97c6899b63c6667](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/45499457/5a5028f3-5f5b-4386-9881-5da9e0a6cfd8)

**Comment by alankilborn** [comment]
![image](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/77065706/2d4dd5f1-5be2-4295-8ff5-df78043005e5)

**Comment by kuzduk** [comment]
oh yes! it work! thanks. new option in preferences of npp 8.6.5 i think it must be off by default

**Comment by alankilborn** [comment]
You can close this issue.

**Comment by kuzduk** [comment]
how can i off this issue in npp 8.5.8? - i use npp 8.5.8it not 8.6-above, because 8.6-above incorrectly work with PauseBreak

**Comment by alankilborn** [comment]
You'd have to use a script in 8.5.8 to get the behavior; see https://community.notepad-plus-plus.org/topic/25179

**Comment by kuzduk** [comment]
> You'd have to use a script in 8.5.8 to get the behavior; see https://community.notepad-plus-plus.org/topic/25179
it is work! Thank u very much!!! 
i dont understand why Don Ho do not off by default this  Special characters with unmapped "shortcut"...

**Comment by alankilborn** [comment]
> i dont understand why Don Ho do not off by default this Special characters with unmapped "shortcut"...

See https://community.notepad-plus-plus.org/post/94030
