### ISSUE TITLE
Some maths characters don't show up

### ISSUE THREAD

**Issue by lanstonchu** [notepad-plus-plus/notepad-plus-plus#14932]
![image](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/38820312/321a5663-7b0c-4206-bb76-1602dcf08488)

### Description of the Issue
below maths characters do not show up in Notepad++ (v8.6), while they would show up in a normal Windows notepad:-

≷⊆∈∉⊄⊇∋∌⊅⟂∓⋅⊕⊗⊢⊨⋮⋯⋱∄∃∅

### Steps to Reproduce the Issue
1. Save the above maths chacters into a .txt file
2. Open the .txt file in Notepad++

### Expected Behavior
The maths characters should show up in Notepad++, just like they did in the normal Windows notepad

### Actual Behavior
You will see empty blocks in Notepad++ instead of the maths characters

### Debug Information
Notepad++ v8.6   (64-bit)
Build time : Nov 23 2023 - 16:58:44
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 11 Home (64-bit)
OS Version : 23H2
OS Build : 22631.3296
Current ANSI codepage : 1252
Plugins : 
    mimeTools (2.9)
    NppConverter (4.5)
    NppExport (0.4)

**Comment by alankilborn** [comment]
Try turning _Direct Write_ on:

![image](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/77065706/a486b408-2919-4bb5-9988-bae9d645696d)

and restart Notepad++ after changing that setting.

**Comment by lanstonchu** [comment]
It works for me, thanks.
