### ISSUE TITLE
search for file in workspace (project panel 1)

### ISSUE THREAD

**Issue by mischlrebl** [notepad-plus-plus/notepad-plus-plus#14937]
Using a workspace structure with several nested folders and files.

Is there a way to search for a file name and therefore, to see where the appropriate file is located?

workaround atm: search in the workspace.xml

thanks in advance

**Comment by alankilborn** [comment]
Questions properly go here: https://community.notepad-plus-plus.org/
But I believe the answer is no.

**Comment by mischlrebl** [comment]
thank you
