### ISSUE TITLE
Confusing dialog

### ISSUE THREAD

**Issue by slorion** [notepad-plus-plus/notepad-plus-plus#1493]
That dialog shown during my last upgrade is very confusing:
- What happens if I click "Yes" ?
- What is meant by "keep it forever" ?
- How can I simply uninstall the plugin ?
- What is the stability issue exactly ?
- etc.

![npp](https://cloud.githubusercontent.com/assets/1606672/13118494/65b5004c-d572-11e5-9c87-d1cda1d7bc8e.png)

**Comment by donho** [comment]
Outdated.
