### ISSUE TITLE
Reduce CI build time

### ISSUE THREAD

**Issue by ArkadiuszMichalski** [notepad-plus-plus/notepad-plus-plus#14942]
Hello again after a long break, I can finally do some programming.

The first thing I noticed was that we migrated from AppVeyor to Github Actions. Build time has been significantly reduced without any optimization, but it can still be improved a bit. I see no reason to run all jobs (generating tons of artifacts) when someone is only modifying `.xml` or `.txt` files. As a learning experience (Github Actions is new to me), I decided to restore the previous optimization from [appveyor.yml](https://github.com/notepad-plus-plus/notepad-plus-plus/blob/master/appveyor.yml) file. Even if it wouldn't be accepted, at least I will learn something new.

From what I've established, this can be done in two ways:
- Run all jobs in parallel and filter conditions directly in them. This wastes resources unnecessarily (because some of it may be stopped anyway) and requires more code (unless we create a separate file containing the code for all jobs).
- Add one additional job that will filter conditions and, depending on the results, launch further jobs.

I chose the second approach because it seems the simplest at this point. Job with filtration takes a short time (like 30 seconds), so even if it runs all the other jobs, the runtime will increase slightly compared to the current state. In the case of simple changes, it will be much shorter compared to the current state (30s vs 6-7min).

In short, some practical examples of how it works:
- change  `.md|txt|log|ini` file like `README.md`
No additional actions are triggered.
- change  `.xml` file which need test but doesn't need compilation like `english.xml`
Only XML validation is done (without compilation).
- change  `.xml` file which need compilation and test like `functionList\cpp.xml`
Only one `Win32/Debug` job will be run.
- change  `.xml` and `.cpp` and `.md` files
All jobs will be run because one of them needs full compilation (here `.cpp` file)

Filtering works by default without adding the `[xml]` flag in the commit title (for the master and PR, but this can be changed). This behavior was accepted in the previous solution. People in PR can still add `[xml]` flag to indicate that they are only making simple changes that do not require compilation, but this has no impact on the all process (this is just a tip for reviewers).

There are also additional flags in the commit title like `[force all]`, `[force one]`, `[force none]` and `[force xml]`, but they are mainly useful when we working on the file `CI_build.yml`.

**Comment by donho** [comment]
@ArkadiuszMichalski 
Welcome to be back! :)
