### ISSUE TITLE
saved macros getting overwritten

### ISSUE THREAD

**Issue by khdetwei** [notepad-plus-plus/notepad-plus-plus#1495]
C:\Users\AppData\Roaming\Notepad++\shortcuts.xml
only gets updated when a file in which I saved macro(s) is closed. NOT when the file is saved. 

Even more insidious, shortcuts.xml gets overwritten whenever ANY notepad++ instance is closed regardless of whether a new macro was created in it. The offshoot of this is, if I have any other notepad++ files opened in another window while creating a macro (then closing the file to "save" it), when one of the other files is closed it overwrites the macros I just saved in shortcuts.xml

The only workable system seems to be to have ONE file that is used ONLY to create macros, and close all other files while I open the designated "macro creation file", create new macros, then close that file before opening anything else. 

I typically have many files opened that I am working on. It not worth the hassle to jump through these hoops closing and opening files just to save a macro. Is there a better workflow?

**Comment by donho** [comment]
I believe this issue has been fixed since long time ago.
Update your Notepad++ to the latest version (v7.6.6).
If the issue persists, please create a new issue for it.
Thank you.
