### ISSUE TITLE
Style Tokens marks not work always with `"` or other not character symbols

### ISSUE THREAD

**Issue by Yankes** [notepad-plus-plus/notepad-plus-plus#14960]
In recent v8.6.5 I notice inconsistent behavior, when I select manually `"id"` in text like:
```
"id":5123008,
"id":5123008,
"id":5123008,
```
and then apply on one of them `Style Token` then there is no reaction from program.
When I select only `id` (without `"`) then its work fine.
When I try select second `"` in line its fails, but when I select `":` it correctly mark all similar text in file.
Overall one observation I have is when you double click on some text and its select some range then I can always use  `Style Token`.

**Comment by alankilborn** [comment]
Make sure this setting is uncheckmarked:

![image](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/77065706/1dd5c794-3ae1-49c3-9f37-056e9e254548)

**Comment by Yankes** [comment]
thanks for this, its indeed change behavior to expected.
