### ISSUE TITLE
CSS bug

### ISSUE THREAD

**Issue by adec86** [notepad-plus-plus/notepad-plus-plus#14962]
### Description of the Issue

When I write (p {) it is jump to right.

### Steps to Reproduce the Issue

1.  please create in your clear PC any .css file, for example style.css
2.  write this code
body {background-color: powderblue;}
h1 {color: blue;}

and then p {

3. you see in new version of notepad-plus-plus. why? 

Thanks.

**Comment by xomx** [comment]
respawn of #14608

**Comment by alexprabhat99** [comment]
@xomx Could you please check out my PR: #14968 which should fix this issue. Your feedback would certainly help me improve. Thanks in advance!
