### ISSUE TITLE
App freeze when opening a file

### ISSUE THREAD

**Issue by sommmen** [notepad-plus-plus/notepad-plus-plus#14965]
Hello,

Opening the following file completely crashes notepad++, 
The app freezes completely.

![image](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/8641495/f746dbbe-0fa7-4e13-b2db-1fb836bfc8eb)

This file is battlefield profile file, i was going through my documents and tried to randomly open it.
I now no longer am able to open notepad++.
I've attached said file with the .txt extension so that github allows it. On disc the file does not have an extension.

[PROFSAVE.txt](https://github.com/notepad-plus-plus/notepad-plus-plus/files/14930100/PROFSAVE.txt)

**Comment by sommmen** [comment]
Renaming the file on disk, the starting npp allowed me to recover.

**Comment by xomx** [comment]
This is a binary [FBCHUNKS](https://www.tapatalk.com/groups/daitools/fbchunks-files-profileoptions-and-save-games-t68.html) file, N++ is not an appropriate editor for that.

Besides, I can open (x64 N++ v8.6.5) that file without a problem:
![npp-FBCHUNKS](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/13075183/a63c0074-090c-4d4d-a8a4-5f84ecc697d8)

**Comment by JamesParrott** [comment]
I can open this in v8.5.3 on Windows, ANSI encoding, Mac CR line endings).

Why on earth does the file end in approximately 1,526,950 null bytes?  Reserving disk space?

**Comment by sommmen** [comment]
> This is a binary [FBCHUNKS](https://www.tapatalk.com/groups/daitools/fbchunks-files-profileoptions-and-save-games-t68.html) file, N++ is not an appropriate editor for that.
> 
> Besides, I can open (x64 N++ v8.6.5) that file without a problem: ![npp-FBCHUNKS](https://private-user-images.githubusercontent.com/13075183/321207909-a63c0074-090c-4d4d-a8a4-5f84ecc697d8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI3NTk5NzcsIm5iZiI6MTcxMjc1OTY3NywicGF0aCI6Ii8xMzA3NTE4My8zMjEyMDc5MDktYTYzYzAwNzQtMDkwYy00ZDRkLWE4YTQtNWY4NGVjYzY5N2Q4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDEwVDE0MzQzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMxNmViMTk3YzA5ODE0NGRjZTExNmVmZmFkMDY5ZTZjZmE0ZWRlOTIyMDQ1ZTUwOGQyMTc5NzM2N2Y5M2Y0ZTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.nZMvVctrS6ReSsLaVYHSKHTa1QfxtJioVuDa57igUxA)

I randomly opened it, i don't expect N++ to correctly read it, but it froze and kept freezing on startup. I'll  try to backup shelved files and retry opening. I also updated from 8.6.2 to the latest.

**Comment by sommmen** [comment]
![image](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/8641495/0587b361-0298-4011-9095-03158264e5e5)

This time i could open the file, but then i clicked another tab and it froze again.

``` 
Notepad++ v8.6.5   (64-bit)
Build time : Mar 29 2024 - 17:04:43
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
Periodic Backup : ON
OS Name : Windows 11 Education N (64-bit
OS Version : 23H2
OS Build : 22631.3296
Current ANSI codepage : 1252
Plugins : 
    mimeTools (3.1)
    NppConverter (4.6)
    NppExport (0.4)
``` 

Anyways - i just noticed the 2.3k issues, this has 0 priority for me - I think i'll close this, i think dev time can better be spent elsewhere :).
