### ISSUE TITLE
hyperlink [bug]

### ISSUE THREAD

**Issue by xyz349925756** [notepad-plus-plus/notepad-plus-plus#14978]
### Description of the Issue
The hyperlink bug in Notepad++ version 8.6.5 causes URLs to contain the ' symbol when you double-click with the left mouse button after entering 'https://www.google.com/' in a text file. This results in the URL becoming 'https://www.google.com'/'.

### Steps to Reproduce the Issue

1. open notepadd++  input  'https://www.google.com' 
2. Double-click the URL with the left mouse button.

![QQ截图20240411203655](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/22998118/de990a4c-434b-45ca-8559-33f2a394eef4)

**Comment by SubActif** [comment]
Same problème with the ` character !
![notepad++_t5ABw2syPu](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/17392472/e4bee265-6273-4eca-8586-91db80ea298d)

### DEBUG INFOS
````
Notepad++ v8.6.5   (64-bit)
Build time : Mar 29 2024 - 17:04:43
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : D:\Dropbox\Applications\Notepad++
Periodic Backup : OFF
OS Name : Windows 10 Home (64-bit
OS Version : 22H2
OS Build : 19045.4291
Current ANSI codepage : 1252
Plugins : 
    CodeAlignmentNpp (14.1.107)
    DSpellCheck (1.5)
    mimeTools (3.1)
    NppConverter (4.6)
    NppSaveAsAdmin (1.0.211)
    NppSnippets (1.7.1)
    Remove Duplicate Lines (1.3)
    _CustomizeToolbar (5.3)
````
