### ISSUE TITLE
Why you don't stand with people of gaze? 

### ISSUE THREAD

**Issue by royluo1984** [notepad-plus-plus/notepad-plus-plus#14977]
since you stood with hongkong, stood with Ukraine
is that means you are happy with the world right now?
or you are just a hypocrite?

**Comment by gitgrub** [comment]
unfriendly post

**Comment by We1eVen** [comment]
这傻卵蛙蛙作者双标也不是一天两天了，传统艺能了属于是，可以说它永远 stand with 它美爹

**Comment by LanYebo** [comment]
傻卵湾湾作者，洗好屁股等解放军来解放台湾
