### ISSUE TITLE
All tabs have been closed after update to v8.6.5

### ISSUE THREAD

**Issue by KraskoVladimir** [notepad-plus-plus/notepad-plus-plus#14976]
Debug info:
Notepad++ v8.6.5   (64-bit)
Build time : Mar 29 2024 - 17:04:43
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
Periodic Backup : ON
OS Name : Windows 11 Enterprise (64-bit
OS Version : 23H2
OS Build : 22631.3447
Current ANSI codepage : 1252
Plugins : 
    mimeTools (3.1)
    NppConverter (4.6)
    NppExport (0.4)

After applying this version, all my previous tabs (saved and not saved) were closed! Only the last tab remains opened, but it changed its name to "New 1". Why? Is there any way to bring all the other tabs back?

**Comment by xomx** [comment]
Cannot reproduce, I tried:
- uninstalled the current N++
- logoff/logon (this is to possibly release the previous NppShell extension loaded in the Windows Explorer shell process
- installed older v8.6.4 x64
- opened in N++ few unsaved tabs with something and some existing files
- closed the v8.6.4
- installed v8.6.5 over the previous version (I tried both the automatic WinGup way from within the N++ and also the update via a manually downloaded installer)
- opened the v8.6.5 ... ok, all the previously opened N++ tabs were there

Could you describe your upgrade in more details? Anything unusual during that process?

**Comment by xomx** [comment]
Do you by any chance have also the Dell SupportAssist SW installed on your computer?

(check if you have the `C:\Program Files\Dell\SupportAssistAgent\SRE\SRE.exe` on your disk, we have a proof that this external program, in its latest version updated January 17th 2024, is deleting the Notepad++ `session.xml` file)

**Comment by KraskoVladimir** [comment]
> Do you by any chance have also the Dell SupportAssist SW installed on your computer?
> 
> (check if you have the `C:\Program Files\Dell\SupportAssistAgent\SRE\SRE.exe` on your disk, we have a proof that this external program, in its latest version updated January 17th 2024, is deleting the Notepad++ `session.xml` file)

Hi @xomx, thank you for your reply. Yes, I have that file. I had these checked:
https://community.notepad-plus-plus.org/topic/15742/faq-autosaving-unnamed-new-1-files
so I was able to restore my New... files from the backup, thankfully.
