### ISSUE TITLE
Clarification of NPPM_CREATESCINTILLAHANDLE

### ISSUE THREAD

**Issue by dail8859** [notepad-plus-plus/notepad-plus-plus#1500]
I would like some clarification from @donho of the `NPPM_CREATESCINTILLAHANDLE` message. My assumption (whether wrong or right) was that it was a simple way for Notepad to call `CreateWindowEx()` and return the handle to a Scintilla control for a plugin.

After some problems I ran into with a plugin, I discovered that internally this message causes Notepad++ to create a `ScintillaEditView` instance. It gets [preconfigured](https://github.com/notepad-plus-plus/notepad-plus-plus/blob/master/PowerEditor/src/ScitillaComponent/ScintillaEditView.cpp#L170) with a lot of settings specific to Notepad++. The `FileManager` also [allocates](https://github.com/notepad-plus-plus/notepad-plus-plus/blob/master/PowerEditor/src/ScitillaComponent/Buffer.cpp#L1212) a `Buffer`, which gets [preconfigured](https://github.com/notepad-plus-plus/notepad-plus-plus/blob/master/PowerEditor/src/ScitillaComponent/Buffer.cpp#L84) with whatever the default settings happen to be.

All this seems like a lot of excess memory and processing. Only the HWND is returned so it's not like the plugin can use it for anything much more than `SendMessage()` etc. Is this the expected/desired behavior?

Thanks

**Comment by sanastasiou** [comment]
Very nice question. I am also confused about this and especially the "destroy" handle counterpart. Notepad++ has two views, two handles. Can some other plugin destroy one of those? If that were to happen, It could cause massive problems to other plugins..

**Comment by dail8859** [comment]
> Can some other plugin destroy one of those?

[No](https://github.com/notepad-plus-plus/notepad-plus-plus/blob/35adb1910ba98897ad3a935fa7d712a986289bd3/PowerEditor/src/ScitillaComponent/ScintillaCtrls.cpp#L61). It has to be in a specific vector in order for it to be destroyed.

> It could cause massive problems to other plugins

Even if it *were* possible, it wouldn't be any more of a concern than say a null pointer exception. Both would be pure programmer error.

**Comment by MetaChuh** [comment]
@dail8859 
what's the status on that ?

**Comment by dail8859** [comment]
Still an outstanding question...and at this point probably never will get an answer.

**Comment by donho** [comment]
Sorry I didn't see this question.
I don't think I can answer it now since I'm too tired (almost 3AM now).
I'll try to aswer your question tomorrow.

**Comment by donho** [comment]
@dail8859 Very sorry for this very late reply.

`NPPM_CREATESCINTILLAHANDLE` is indeed for plugins to create a ScintillaEditView the plugins can control it by using Win32 `SendMessage routine.
It is the expected/desired behavior.

> All this seems like a lot of excess memory and processing. 

Have you better suggestion for it ?

**Comment by Ekopalypse** [comment]
@donho, there seem to be an issue with NPPM_CREATESCINTILLAHANDLE and NPPM_DESTROYSCINTILLAHANDLE like discussed at #4487.
Is it expected, that once a plugin creates a ScintillaEditView it should stay alive until npp gets closed?
If so, maybe worth mentioning it at the plugin dev section as well?
