### ISSUE TITLE
Copy Link Under Caret Shortcut Key Needed

### ISSUE THREAD

**Issue by alienfxfiend** [notepad-plus-plus/notepad-plus-plus#15014]
I tried Generative AI to create a Python script that does this but it doesn't work in large files and is broken most of the time. Could you please add a hotkey customizable for this (Copying Link Under Caret) 😊 —It would be very useful & faster than pressing the Right-Click Context Menu keyboard key for it. If someone knows a foolproof way to script it using Python I would love to try out your code !! P.S: I would like it assigned to the key: Ctrl+P

**Comment by rddim** [comment]
It's a workaround but this macro should work. It's not a Python.
```
        <Macro name="Copy link" Ctrl="no" Alt="no" Shift="no" Key="0">
            <Action type="2" message="0" wParam="42082" lParam="0" sParam="" />
        </Macro>
```

**Comment by alienfxfiend** [comment]
> It's a workaround but this macro should work. It's not a Python.
> 
> ```
>         <Macro name="Copy link" Ctrl="no" Alt="no" Shift="no" Key="0">
>             <Action type="2" message="0" wParam="42082" lParam="0" sParam="" />
>         </Macro>
> ```

Thank you ! 😊 That works brilliantly !
