### ISSUE TITLE
Empty content of current file  when Notepad crashes!

### ISSUE THREAD

**Issue by mockassin** [notepad-plus-plus/notepad-plus-plus#1501]
I have noticed with several versions of Notepad including the last one (6.8.8) that if Notepad crashes, the content of the current file (the tab) you are editing is saved totally empty, so any content is lost! If you don't have any backup, then you could lose your work. I have got multiples files opened at the same time (multiple tabs) split on two screens. Only the one that I was editing lose its contents (fortunately).
PS: I don't know why my Notepad++ crashes... btw. I will transfer next time the report.

**Comment by moikonomou** [comment]
I can confirm the same behavior on version 6.9.1. I cannot reproduce it but I had two instances opened   and only one of them crashed. The backup file  on %APPDATA%\Roaming\Notepad++\backup\  was in the most recent version, so I think the crash and the autosave happened  almost "concurrently"

**Comment by donho** [comment]
I believe this issue has been fixed since long time ago.
Update your Notepad++ to the latest version (v7.6.6).
If the issue persists, please create a new issue for it.
Thank you.
