### ISSUE TITLE
[BUG] Find In File Progress Pane show wrong "Hits:" label in Italian

### ISSUE THREAD

**Issue by dellacse-bh** [notepad-plus-plus/notepad-plus-plus#15027]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description of the Issue

Using the Italian translation, if you launch a "Find In Files" search, an "Hits:" counter appears in the window. The Italiano label for "Hits:" is shown wrong: you should see "orrispondenze" instead of "Corrispondenze". The language file is properly translated. I suppose the issue comes from the lenght of the word "Corrispondenze".

### Steps To Reproduce

1.  Set the language to Italian
2. Launch a Find In File Search  (Cerca nei File)
3.  You will see the progress counter with the label "orrispondenze <nr>", instead of "Corrispondenze <nr>"

### Current Behavior

The label is wrong

### Expected Behavior

I expect the right label

### Debug Information

```shell
Notepad++ v8.6.5
Italian Language pack
```

### Anything else?

![Immagine 2024-04-22 095624](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/89377814/9bc7265c-3600-4e9d-84eb-4cdea475a9e6)

**Comment by rdipardo** [comment]
*Che __orr__&#x200D;ibile difetto!*

**Comment by dellacse-bh** [comment]
> _Che **orr**‍ibile difetto!_
Beh, anche se piccolo, è pur sempre un difetto. E non dipende dalle traduzioni, ho controllato.

**Comment by conky77** [comment]
thanks @dellacse-bh
I could solve trying to make the translation shorter, but I checked other translations of Latin origin like French, Corsu, Spanish, and Galician and all of them could have some problems making the translation shorter.
So it is better to fix it.

**Comment by conky77** [comment]
@alankilborn 
if it not possible to give more space to the label, both solutions are ok for me. With more space the translation does not need to be modified
