### ISSUE TITLE
[Feature request] When you paste a text, select that text

### ISSUE THREAD

**Issue by shodanx2** [notepad-plus-plus/notepad-plus-plus#15038]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description of the Issue

Currently, if you paste text, whatever selection you had, becomes unselected

There is never selected text after a paste

### Describe the solution you'd like.

I propose after pasting, that the pasted text be selected

In my case I have plugin SurroundSelection 
When will surround characters around my selection

For instance if I have a selection and I press "
This plugin will surround the selection with "myselection"

However in the present case, there is never a selection after pasting so it requires an extra action to re-select

Often I will doubleclick a variable to select it, then paste, then have to re-select it to surround it

So it would be nice that the selection appear "maintained" in that situation

Here is an example

https://github.com/notepad-plus-plus/notepad-plus-plus/assets/10621885/7013ec57-bbb0-481b-818c-1cc9aecb3004

### Debug Information

```shell
Notepad++ v8.6.1   (64-bit)
Build time : Jan  4 2024 - 05:01:52
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 10 Pro (64-bit)
OS Version : 22H2
OS Build : 19045.4291
Current ANSI codepage : 1252
Plugins : 
    ActiveX (1.1.8.7)
    AnalysePlugin (1.13.49)
    AutoSave (2)
    BigFiles (0.1.3)
    BracketsCheck (1.2.2)
    ComparePlus (1.1)
    DSpellCheck (1.5)
    HexEditor (0.9.12)
    LocationNavigate (0.4.8.1)
    MarkdownViewerPlusPlus (0.8.2)
    mimeTools (3)
    NavigateTo (2.6.4)
    Npp-Highlighter (1.0.0.1)
    NppConverter (4.5)
    NppExport (0.4)
    NPPJSONViewer (2.0.6)
    nppRandomStringGenerator (1.8)
    NppSaveAsAdmin (1.0.211)
    NppTaskList (2.5)
    NppToolBucket (1.10.6622.41516)
    NppXmlTreeviewPlugin (2)
    SecurePad (2.4)
    SurroundSelection (1.4.1)
    TakeNotes (1.2.6)
    urlPlugin (1.2)
    XMLTools (3.1.1.13)
    _CustomizeToolbar (5.3)
```

### Anything else?

I anticipate one problem with this however.

The situation where you paste the same text multiple time

timetimetimetimetimetimetimetime

Like this. If my suggestion is implemented AS IS, it would continually overwrite the same bit of text.

Since normally pasting while having a selection will overwrite said select.

So I propose a tweak to this special case.

If you paste with selection, but the LAST ACTION was also a paste, don't overwrite instead paste as if it weren't selected.

I'm not sure if then the selection should be, only the last paste, or if the previous selection should be extended with each paste.

My first reaction would be the selection should be extended when a "second" (and immediate subsequent) paste occurs

**Comment by CennoxX** [comment]
This would be a very unique (and therefore for many users unanticipated) behaviour for a text editor. I don't know any other editors working like this.

**Comment by shodanx2** [comment]
I see yes, it's probably since I use SurroundSelection that I need this. 

Often I will double click a variable, paste a new one in and then try to apply expansion/quotes to the selection, but I lost my selection by pasting. 

It only happens when I double click to select though, maybe that could be the limiting factor. Only keep selection if the selection was made with a double-click word select.

**Comment by alankilborn** [comment]
> Only keep selection if the selection was made with a double-click word select.

There's no relationship between how a selection is made, and then a subsequent paste.  And I doubt that the developers would entertain adding in such an artificial relationship.

**Comment by shodanx2** [comment]
Well, I think it would be something like 

When text is doubleclicked, somewhere a function to "select word under cursor" is called

This function find the "edges" of the word and knows what the "word" delimiter characters are.

That function could set a variable "selectiondoubleclicked=true"

Somewhere else, there is a function called for unselecting text. That function should clear variable selectiondoubleclicked.

Lastly, in the paste function, check if selectiondoubleclicked=true then select pasted text instead of clearing current selection.

**Comment by CennoxX** [comment]
What you think has nothing to do with the actual implementation. Maybe this functionality could be something for an individual [PythonScript](https://github.com/chcg/PythonScript) or [LuaScript](https://github.com/dail8859/LuaScript). But it would not make sense for everyone as implementation in the Notepad++.

**Comment by donho** [comment]
> A user would paste the text, write further and directly overwrite the pasted text. 

Agree. It's even a dangerous feature which could be transformed to a critical bug.

**Comment by alankilborn** [comment]
>Is there an existing issue for this?
 I have searched the existing issues

There **_IS_**.
See https://github.com/notepad-plus-plus/notepad-plus-plus/issues/4901.
The linked issue has a script [HERE](https://github.com/notepad-plus-plus/notepad-plus-plus/issues/4901#issuecomment-1719293316) that solves the problem, i.e., it leaves the pasted text selected after the paste.
