### ISSUE TITLE
[BUG] Can't CTRL+V paste in function list filter, however rightclick paste works

### ISSUE THREAD

**Issue by shodanx2** [notepad-plus-plus/notepad-plus-plus#15057]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description of the Issue

 Can't CTRL+V paste in function list filter, however rightclick paste works

### Steps To Reproduce

Open batch file with functions

Open function list (View -> Function List)

copy the name of a function present in the file

focus function list filter

![image](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/10621885/c88f9625-0e76-42ef-a09c-7cf46ab24db6)

Try pasting with CTRL+V

No text appears

Rightclick paste

Text appears

### Current Behavior

CTRL+V does not paste in function list filter, 
Rightclick context menu paste does work

### Expected Behavior

CTRL+V should  paste in function list filter, 

### Debug Information

```shell
Notepad++ v8.6.1   (64-bit)
Build time : Jan  4 2024 - 05:01:52
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : -notepadStyleCmdline -z "C:\Windows\System32\NOTEPAD.EXE" D:\shodan\Documents\BatchfileFrameWork-main\lib\function\ListFunctions.bat
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 10 Pro (64-bit)
OS Version : 22H2
OS Build : 19045.4291
Current ANSI codepage : 1252
Plugins : 
    ActiveX (1.1.8.7)
    AnalysePlugin (1.13.49)
    AutoSave (2)
    BigFiles (0.1.3)
    BracketsCheck (1.2.2)
    ComparePlus (1.1)
    DSpellCheck (1.5)
    HexEditor (0.9.12)
    LocationNavigate (0.4.8.1)
    MarkdownViewerPlusPlus (0.8.2)
    mimeTools (3)
    NavigateTo (2.6.4)
    Npp-Highlighter (1.0.0.1)
    NppConverter (4.5)
    NppExport (0.4)
    NPPJSONViewer (2.0.6)
    nppRandomStringGenerator (1.8)
    NppSaveAsAdmin (1.0.211)
    NppTaskList (2.5)
    NppToolBucket (1.10.6622.41516)
    NppXmlTreeviewPlugin (2)
    SecurePad (2.4)
    SurroundSelection (1.4.1)
    TakeNotes (1.2.6)
    urlPlugin (1.2)
    XMLTools (3.1.1.13)
    _CustomizeToolbar (5.3)
```

**Comment by alankilborn** [comment]
It works for me in v8.6.5 -- suggest you try that version and report back results.

**Comment by shodanx2** [comment]
Thank you that was it. 
On 8.6.5 the problem is gone
However, I notice the filter string has a max lenght of 13 characters and will automatically trunkate anything pasted into it. 
Strange but oh well !
