### ISSUE TITLE
Suggestions to "with BOM" and "without BOM"

### ISSUE THREAD

**Issue by scootergrisen** [notepad-plus-plus/notepad-plus-plus#1505]
UTF-8 encoded file can be with or without BOM and that is nice to know.
But it seems this is not always showed to the user.
Sometimes it just say "UTF-8" and the user does not know if the file is saved with or without BOM.

So maybe it would be a good idea to use:
"UTF-8 without BOM"
"UTF-8 with BOM"

And not just:
"UTF-8"

**Comment by donho** [comment]
The current way in Notepad++ latest version answers better to this issue IMO.
