### ISSUE TITLE
Add Support for Unicode Characters.

### ISSUE THREAD

**Issue by santosh-gurav** [notepad-plus-plus/notepad-plus-plus#15067]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description of the Issue

I cannot use these Unicode characters in my text ❝ ❞

When these characters are copied in the Editor, it gets converted into Rectangle characters ▯ ▯

There are many such characters.

If there is any workaround or option available in the existing versions, kindly let us know.
![NPP Msg](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/92359716/9b0f148c-52df-4bef-81ba-3900ffcce95d)

### Describe the solution you'd like.

I am so much grateful for the features that Notepad ++ comes with and they keeps on adding and improving.

I would like to have the support to Unicode characters included in the upcoming versions of the Notepad ++.

Thank You So Much

### Debug Information

```shell
.
```

### Anything else?

.

**Comment by ozone10** [comment]
use 
![image](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/55940305/3bfd400b-ebfb-4feb-b244-9deb5eef839b)
and close issue

**Comment by santosh-gurav** [comment]
Thank You very much. It solved the issue.
