### ISSUE TITLE
[Feature request] Spanish Documentation Files

### ISSUE THREAD

**Issue by coates4** [notepad-plus-plus/notepad-plus-plus#15060]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description of the Issue

I want to include for example README and CONTRIBUTING files for Spanish speaking contributors who may not be able to read the English files inhibiting contribution. 

### Describe the solution you'd like.

I would like there to be Spanish versions of the documentation files. 

### Debug Information

```shell
None
```

**Comment by donho** [comment]
There won't be other official translations for these files.
