### ISSUE TITLE
[BUG] Multi-editing not showing multiple cursors in dark mode

### ISSUE THREAD

**Issue by Your-Pal-Al** [notepad-plus-plus/notepad-plus-plus#15075]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description of the Issue

Multi-editing only showing one cursor 

Not sure if this was in a recent update, or if it's just an issue on my end, however I'm not seeing multiple cursors like I used to when using multi-editing. It still works (multi-editing, that is), but it is now impossible to know what lines have been selected without the extra cursors

### Steps To Reproduce

1.  open a file in notepad++
2.  CTRL + mouse left-click in various areas on multiple lines
3.  behold only one cursor

### Current Behavior

only one viewable cursor when multi-editing

### Expected Behavior

multiple cursors when multi-editing

### Debug Information

```shell
Notepad++ v8.6.5   (64-bit)
Build time : Mar 29 2024 - 17:04:43
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
Periodic Backup : ON
OS Name : Windows 11 Enterprise (64-bit
OS Version : 22H2
OS Build : 22621.3447
Current ANSI codepage : 1252
Plugins : 
    BracketsCheck (1.2.2)
    CodeAlignmentNpp (14.1.107)
    ComparePlus (1.1)
    mimeTools (3.1)
    NppConverter (4.6)
    NppExport (0.4)
    NppFavorites (1.0.0.1)
    NppQrCode64 (0.0.0.1)
    PlanetCNCNpp64 (3001.21.1123.1)
    RandomValuesNppPlugin (0.2.1)
    RegexTrainer (1)
```

### Anything else?

I recently updated notepad++ within the past week, but I'm not sure exactly when the bug started. I infrequently use multi-editing, but it's such an awesome feature. Thankfully it still works, but it would be a little easier to use if I could see all the cursors I've 'clicked' (? hope that makes sense)

**Comment by CennoxX** [comment]
Which theme (Settings > Style Configurator > Select theme: ...) are you using?

**Comment by Your-Pal-Al** [comment]
I'm using 'DarkModeDefault'

I noticed that if I switch to 'Default', I can see all of the cursors when multi-editing, but not on dark mode. Which is weird because I'm almost positive I've seen multiple cursors on dark-mode but I could be mistaken

Thank you giving me a work-around, albeit to the detriment of my poor eyeballs!

**Comment by CennoxX** [comment]
@Your-Pal-Al To safeguard thy sight, I suggest the following intervention: Could you compare C:\Program Files\Notepad++\themes\DarkModeDefault.xml, %appdata%\Notepad++\themes\DarkModeDefault.xml and https://github.com/notepad-plus-plus/notepad-plus-plus/blob/master/PowerEditor/installer/themes/DarkModeDefault.xml? Maybe the "Multi-selected text color"/"Multi-edit carets color" is not set in one of your themes.

**Comment by Your-Pal-Al** [comment]
@CennoxX My %appdata% version was missing the caret's line;

     `<WidgetStyle name="Multi-edit carets color" styleID="0" fgColor="808040" />`

and I think my text color line was `bgColor="000000"` as opposed to;

     `<WidgetStyle name="Multi-selected text color" styleID="0" bgColor="C0C0C0" />`)

 I added the line and changed the other and now I can see all my cursors. Thanks for your help!
