### ISSUE TITLE
[Feature requests] 5.  Please consider

### ISSUE THREAD

**Issue by sng843ndf86nd8** [notepad-plus-plus/notepad-plus-plus#1507]
Hi everybody !
First, I want say, I check NP++ webpage every day in awaiting of new program update. I strongly hope, my 1 month old useful requests may appear:
#1, Ability to delete Auto-Inserted (Auto-Completion Preferences menu) half of dual symbol (parenthesis, brackets, curly braces, quotas…) by pressing Backspace. It means to remove whole double symbol by deleting it’s first half wrote manually in origin.

#2, Ability to delete Tabbed whitespaces (by pressing Backspace), transformed to regular spaces due to Tab Settings in Preferences; in sense of one Backspace = one deleted tabbed whitespace. It means not x-times pressed Backspace to delete one tabbed whitespace.

#3, Ability to reset key bindings to default from GUI. For beginners who never used such poweful notepad and are trying to find their own efficient work habits.

#4, Ability to exclude numbers from Auto-Completion.
And ability to exclude specific strings from Auto-Completion per file or default for anything opened !
#5, Ability to enlarge Find and replace window (ctrl + h) for more comfortable multi lines operating. This window has in right down corner an enlarge mark, but it does not work (windows 7 ultimate 32 bit).
Also would be handy to be able enter Tab whitespaces into those text fields (“Find what:”, “Replace with:”). Because now, when you press Tab, it will move you to other clickable object in window.
And maybe bug: When occurs Tab whitespace from very beginning of the line pasted into text fields, it is longer than same Tab whispace in middle of that text field. Try select two lines in code, where both start tabbed and paste it into window's text fields. Second tab will be shorter.

Many thanks for understanding devs !
I wish you best

**Comment by sng843ndf86nd8** [comment]
Hey
Excited about new version, but sadly none of suggested things appeared.
Please please cmon

**Comment by dail8859** [comment]
Please do not repost issues that you have already posted. #1401
