### ISSUE TITLE
[BUG] Lua: cannot add additional styles

### ISSUE THREAD

**Issue by Thaoky** [notepad-plus-plus/notepad-plus-plus#15081]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description of the Issue

Only 4 keyword lists are passed to the Lua lexer, preventing users from adding more lists for syntax highlighting.

### Steps To Reproduce

1.  In Langs.xml, add a line `<Keywords name="type3">Lang3</Keywords>` in the lua section
2.  In Stylers.xml, add a line `<WordsStyle name="FUNC4" styleID="16" fgColor="FF8000" bgColor="3F3F3F" fontName="" fontStyle="1" fontSize="" keywordClass="type3">Test4</WordsStyle>`
3.  Restart N++
4. Type the word, it is not highlighted

### Current Behavior

After modifying the configuration files, the new sections are visible in the Styler Configuration, colors can be changed, keywords can be added, but the highlighting does not work.

### Expected Behavior

The highlighting should work.

### Debug Information

```shell
Notepad++ v8.6.5   (64-bit)
Build time : Mar 29 2024 - 17:04:43
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
Periodic Backup : ON
OS Name : Windows 11 Pro (64-bit
OS Version : 23H2
OS Build : 22631.3447
Current ANSI codepage : 1252
Plugins : 
    ComparePlugin (2.0.2)
    Explorer (1.9.5)
    HexEditor (0.9.12)
    mimeTools (3.1)
    NppConverter (4.6)
    NppExport (0.4)
```

### Anything else?

Link to the forum topic : https://community.notepad-plus-plus.org/topic/25746/lua-cannot-add-additional-styles

**Comment by mpheath** [comment]
Related:
 * #7615 also requests more lua keyword list styles.
