### ISSUE TITLE
UI redraw stability

### ISSUE THREAD

**Issue by ksundnes** [notepad-plus-plus/notepad-plus-plus#1508]
When re-sizing the UI window and and any panel you have on the right, the UI is redrawing all the time and so it blinks like crazy (tabs, status line, panel content etc).

Maybe there is a way to stabilize that - to feel more solid and professional. Maybe avoding the blanking out before redrawing or something.

Look at Android Studio, there is no redraw blinking but still updates UI elements in stable way.

Nothing major but contributes to the overall feel.

**Comment by donho** [comment]
I believe this issue has been fixed since long time ago.
Update your Notepad++ to the latest version (v7.6.6).
If the issue persists, please create a new issue for it.
Thank you.
