### ISSUE TITLE
[Feature request] Add support to associate  files extensions with language by default

### ISSUE THREAD

**Issue by henrypp** [notepad-plus-plus/notepad-plus-plus#15108]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description of the Issue

By default .toml file (it's over 9000, really) opens as simple text file, this is wrong, needs register .toml file by developers/solution below.

.toml looks good when i select INI language:
![sshot-003](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/3902025/20a976be-3a5c-411c-9284-5898556d8b18)

### Describe the solution you'd like.

Create new settings listview item (or what do you have?) to manage configured extensions.

### Debug Information

```shell
Notepad++ v8.6.5   (64-bit)
Build time : Mar 29 2024 - 17:04:43
Path : D:\soft\Notepad++\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : ON
Cloud Config : OFF
Periodic Backup : OFF
OS Name : Windows 11 Professional (64-bit
OS Version : 24H2
OS Build : 26120.461
Current ANSI codepage : 1251
Plugins : 
    mimeTools (3.1)
    NppConverter (4.6)
    NppExport (0.4)
    NppMarkdownPanel (0.7.3)
```

### Anything else?

Where is devs? I also created another issue with fix current assoc. implementation #14703, not any info from them! It is not good.

**Comment by ozone10** [comment]
You could add extensions here Menu -> Settings -> Style Configurator...
![image](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/55940305/7a1afbdc-5631-4f90-9446-2e8ae229e360)

> Where is devs? I also created another issue with fix current assoc. implementation #14703, not any info from them! It is not good.

Unfortunately there are over 2.3k issues and only one main developer, others are volunteers who usually focus only on part they are interested.

**Comment by henrypp** [comment]
@ozone10 thx, that helped
