### ISSUE TITLE
[BUG] Raku file extension not recognized automatically + Syntax highlighting in default theme (light mode) not working

### ISSUE THREAD

**Issue by hankache** [notepad-plus-plus/notepad-plus-plus#15116]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description of the Issue

Raku support was added in 8.6.6 nonetheless syntax highlighting doesn't work in the default theme light mode, in addition raku files are not automatically detected.

### Steps To Reproduce

1.  Open any Raku file
2.  
3.  

### Current Behavior

1 - Language not automatically detected
2- In default theme (light mode) no syntax highlighting

### Expected Behavior

1 - Automatic detection of language
2 - Syntax highlighting working in default light theme 

### Debug Information

```shell
Notepad++ v8.6.6   (64-bit)
Build time : May  6 2024 - 21:59:00
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
Periodic Backup : ON
OS Name : Windows 10 Pro (64-bit)
OS Version : 22H2
OS Build : 19045.4291
Current ANSI codepage : 1252
Plugins : 
    mimeTools (3.1)
    NppConverter (4.6)
    NppExport (0.4)
```

**Comment by chcg** [comment]
The problem is not happening with the portable version. So most likely that is an issue that the installer is not overwriting your local style files.

**Comment by hankache** [comment]
Indeed. I uninstalled Notepad++ and deleted C:\Program Files\Notepad++ then reinstalled again. It works normally.

Shall we close this issue? or is it still valid?
