### ISSUE TITLE
Open links with a keyboard shortcut

### ISSUE THREAD

**Issue by dogancelik** [notepad-plus-plus/notepad-plus-plus#1511]
According to [this page](https://superuser.com/questions/447978/open-links-in-notepad-with-keyboard) and my experience, there is currently no way to open links with a keyboard shortcut. You can only open links with mouse double click.

This keyboard shortcut is essential for power users who mainly use Notepad++ solely with their keyboards.

**Comment by dogancelik** [comment]
Please add labels: `feature, ideas`

**Comment by donho** [comment]
It needs a lot of coding effort, so this feature won't be done.
