### ISSUE TITLE
[BUG] Typo in config.xml GUIConfig setting: "MaitainIndent"

### ISSUE THREAD

**Issue by chaoctopod** [notepad-plus-plus/notepad-plus-plus#15111]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description of the Issue

The config.xml file that is generated when launching notepad++.exe contains a setting that appears to be a typo: "MaitainIndent"

### Steps To Reproduce

1.  Download notepad++ x64 portable
2.  Launch notepad++.exe
3.  Exit notepad++.exe
4. View config.xml setting `<GUIConfig name="MaitainIndent">yes</GUIConfig>`

### Current Behavior

config.xml contains:
`<GUIConfig name="MaitainIndent">yes</GUIConfig>`

### Expected Behavior

config.xml would contain:
`<GUIConfig name="MaintainIndent">yes</GUIConfig>`

### Debug Information

```shell
Notepad++ v8.6.5   (64-bit)
Build time : Mar 29 2024 - 17:04:43
Path : C:\tmp\npp.8.6.5.portable.x64\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : ON
Cloud Config : OFF
Periodic Backup : OFF
OS Name : Windows 11 Pro (64-bit
OS Version : 23H2
OS Build : 22631.3527
Current ANSI codepage : 1252
Plugins : 
    mimeTools (3.1)
    NppConverter (4.6)
    NppExport (0.4)
```

### Anything else?

Similar thing reported a long time ago: https://github.com/notepad-plus-plus/notepad-plus-plus/issues/1026

There was not a GUI preference I could find that referenced this setting, and only appeared in config.xml. If you delete `<GUIConfig name="MaitainIndent">yes</GUIConfig>` and relaunch, the setting is re-added.

**Comment by donho** [comment]
https://github.com/notepad-plus-plus/notepad-plus-plus/commit/ee3aecb161c24f58eb1a01ed9df0abd1e1acb08e
