### ISSUE TITLE
[BUG] The caret position is unnatural when repeating column mode.

### ISSUE THREAD

**Issue by project-flower** [notepad-plus-plus/notepad-plus-plus#15126]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description of the Issue

[Multi Edit resists escape after typing · Issue #14649 · notepad-plus-plus/notepad-plus-plus · GitHub](https://github.com/notepad-plus-plus/notepad-plus-plus/issues/14649)
This issue has been resolved in v8.6.6, but
I would like to report that the behavior when starting column mode again after canceling column mode was different from v8.6.5 and earlier.

### Steps To Reproduce

1. Press Alt+Shift+Down two or more times to place the caret in three or more rows.
2. Press Esc to exit column mode.
3. Press Alt+Shift+Up, then the caret will be placed up to the first line selected in 1.

### Current Behavior

Column mode attempts to restore the last manipulated position.

### Expected Behavior

Column mode must operate anew, regardless of the previously set range.

### Debug Information

```shell
Notepad++ v8.6.6   (64-bit)
Build time : May  6 2024 - 21:59:00
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : "C:\Program Files\Notepad++\change.log" 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
Periodic Backup : OFF
OS Name : Windows 10 Pro (64-bit)
OS Version : 22H2
OS Build : 19045.4291
Current ANSI codepage : 932
Plugins : 
    mimeTools (3.1)
    NppConverter (4.6)
    NppExport (0.4)
```

**Comment by alankilborn** [comment]
I can confirm this bug (simply follow _Steps To Reproduce_; ignore _Description_) in 8.6.6.

**Comment by donho** [comment]
@project-flower @alankilborn 
Could you check PR #15129 to make sure if it's fixed?

**Comment by alankilborn** [comment]
It seems fixed to me!
