### ISSUE TITLE
Divide "Move to Other View" into two commands

### ISSUE THREAD

**Issue by Yaron10** [notepad-plus-plus/notepad-plus-plus#1513]
The command "Move to Other View" executes two related yet different actions:
1) Toggle One View/Two Views (simplest case: two files are open).
2) Move current file from one view to the other (simplest case: two files are open in the top (or left) view, and one file is open in the bottom view; - move current file from top to bottom).

I find three problems in the current behavior:
1) It's confusing. Those two actions are indeed related but they are certainly different.
2) When switching from "One View" to "Two Views", the current file gets the **bottom** view in some cases and the **top** view in others.
This is not random but still annoying. 
3) If several files are open in both views (e.g. ten files at top and ten others at bottom), there isn't an easy way to switch to One View mode.

I suggest to divide the "Move to Other View" command into two commands:
1) Toggle One View/Two Views.
When switching from One View to Two Views, the current file _always_ gets the top view and the tab next to it (needs some elaboration) gets the bottom view.
2) "Move to Other View": if we're in Two Views mode, move current to the other view.
(If only two files are open, switch the files' views). 

---

Related: #1514 and #1515.

**Comment by donho** [comment]
I don't see the point to divide this command in 2.
