### ISSUE TITLE
[BUG] "Save as admin" 1.0.211 shows as not compatible with NPP 8.6.7

### ISSUE THREAD

**Issue by pebl-hank** [notepad-plus-plus/notepad-plus-plus#15137]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description of the Issue

Save as admin's version 1.0.211 is not compatible to this version of Notepad++ (v8.6.7).
As a result the plugin cannot be loaded.

### Steps To Reproduce

1.  Install NPP 8.6.7
2.  Load "Save as admin" 1.0.211
3.  NPP shows the error in the Plugins Admin

### Current Behavior

Can not use "Save as admin" anymore.

### Expected Behavior

Saving a file that is blocked by UAC directly without having to restart NPP as an admin.

### Debug Information

```shell
Notepad++ v8.6.7   (64-bit)
Build time : May 12 2024 - 20:04:00
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : "C:\Program Files\Notepad++\change.log" 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
Periodic Backup : OFF
OS Name : Windows Server 2022 Standard (64-bit)
OS Version : 21H2
OS Build : 20348.1850
Current ANSI codepage : 1252
Plugins : 
    mimeTools (3.1)
    NppConverter (4.6)
    NppExport (0.4)
```

### Anything else?

![screenshot_177](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/4146413/700a5ba7-0550-4620-a23a-d1e6f1019c85)

**Comment by xomx** [comment]
https://github.com/notepad-plus-plus/notepad-plus-plus/issues/14990#issuecomment-2053828749

https://github.com/notepad-plus-plus/nppPluginList/commit/7a889ea7f1ea59deaa8fcae5185d759098a83fbc

**Comment by isillo** [comment]
Can somebody please update this plugin so it can be loaded again? Thanks.

**Comment by donho** [comment]
@isillo 
You don't need the plugin to do the feature provided already by Notepad++.

**Comment by pebl-hank** [comment]
That is not true. When opening such a file in NPP, it asks if it should oben in Admin-Mode when you try to save it. When opening in Admin Mode, the edited data is lost. You need to manually copy and paste it to the admin-NPP.

**Comment by isillo** [comment]
> @isillo You don't need the plugin to do the feature provided already by Notepad++.

Cant find this feature in Notepad++. Of course I know walkaround by starting notepad++ as administrator but thats not the case. The incompatible plugin allowed much more flexibility which I cant find in native Notepad++ app. Please point me to where I can set Notepad++ to autmatically relaunch and eleveate itself to save file as admin.

**Comment by ponjadito23** [comment]
Hi, I have used this plugin because my main user in Windows is a standard user and I have a separate user that has administrator privileges. This means that when I restart Notepad++ as administrator to save a protected file, a completely different profile gets loaded with no opened files. With this plugin I could simply escalate my privileges temporarily to save my file, keeping my session.

**Comment by curtisthefox** [comment]
I agree that this plugin does have a valid use case.

**Comment by cgri** [comment]
I would also appreciate if the plugin could be used with notepad++ again!

**Comment by Brondahl** [comment]
For clarity, the functionality of the "Save as Admin" plugin is now fully supported by Notepad++, out of the box, as of #16933, linked above.
