### ISSUE TITLE
[Feature request] Macro - Run until end - Progress update

### ISSUE THREAD

**Issue by Kochise** [notepad-plus-plus/notepad-plus-plus#15130]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description of the Issue

Running a lengthy regex macro through a 50 MB CSV file until its end.

Progress is unknown since the window gets unresponsive for hours long.

### Describe the solution you'd like.

Would be nice to display a progress in % somewhere (cursor line / total lines).

And update it every 10 or 30 seconds, perhaps with expected end time.

### Debug Information

```shell
Notepad++ 8.6.6 32 bits
(can't post more, window is unresponsive)
```

### Anything else?

The regex is buggy on some text patterns. Could it be upgraded ?

**Comment by alankilborn** [comment]
>The regex is buggy on some text patterns. 

No one can do anything with such a statement.  Provide specific examples.

**Comment by donho** [comment]
Instead of "there's a bug", please provide the detail information so we can help.

**Comment by Kochise** [comment]
Updated with debug info and "anything else" : I'll open a separate bug report instead.

Please reconsider the feature request.
