### ISSUE TITLE
[BUG] NP++ shows up as a WIndows Store App.

### ISSUE THREAD

**Issue by streetwolf** [notepad-plus-plus/notepad-plus-plus#15134]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description of the Issue

The last few updates to NP++ shows up as a Windows Store App even though I downloaded the updates from your website. Among the various uninstaller programs I looked at some show it as a regular app while others like HiBit Uninstaller shows it as a Windows Store App.

Here is what it looks like in my Registry:

[NP++.txt](https://github.com/notepad-plus-plus/notepad-plus-plus/files/15296616/NP%2B%2B.txt)

From HiBit Uninstaller app:

HiBit Windows Store Apps Manager Report:

Apps Name                                          Install Date                       Size         Version                 Publisher

Notepad++                                          5/13/2024 (Today)           61.1 KB      1.0.0.0                 Notepad++

### Steps To Reproduce

1.  Update NP++ to latest version.
2.  
3.  

### Current Behavior

Appears as a Windows Store App

### Expected Behavior

SHould appear as a regular installed app as it appeared a few updates ago.

### Debug Information

```shell
Notepad++ v8.6.7 (64-bit)
Build time : May 12 2024 - 20:04:00
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : "D:\OneDrive\Desktop\Report.txt"
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
Periodic Backup : OFF
OS Name : Windows 11 Pro (64-bit)
OS Version : 23H2
OS Build : 22631.3527
Current ANSI codepage : 1252
Plugins : 
 HexEditor (0.9.12)
 mimeTools (3.1)
 NppConverter (4.6)
 NppExport (0.4)
```

**Comment by alankilborn** [comment]
>Appears as a Windows Store App

Don't know what you're looking at, but it isn't THIS Notepad++.
This issue may be closed.
