### ISSUE TITLE
Open files appear in the Recently Closed list

### ISSUE THREAD

**Issue by Yaron10** [notepad-plus-plus/notepad-plus-plus#1514]
STR:
Open two files.
Move to Other View.

Result:
The open files appear in the Recently Closed list.

---

When calling doClose in the docGotoAnotherEditView function, do not add the files to the Recently Closed list.

---

Related: #1513 and #1515.

**Comment by Yaron10** [comment]
Hello @dail8859,

May I ask your opinion about the proposed fix in https://github.com/pnedev/compare-plugin/issues/19?

Thank you.

Best regards.

**Comment by dail8859** [comment]
Just looking at it looks like it seems ok. Kind of difficult to properly review it without it being in a PR.

**Comment by Yaron10** [comment]
Hello dail,

Thank you for looking at it. I appreciate it.

Best regards.

**Comment by donho** [comment]
Fixed
