### ISSUE TITLE
[BUG] Inserting numbers with Column Editor causes crash

### ISSUE THREAD

**Issue by cddiffz** [notepad-plus-plus/notepad-plus-plus#15144]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description of the Issue

Attempting to insert certain non-decimal number sequences using the Column Editor crashes the program.

### Steps To Reproduce

1.  Select at least 28 lines in Column Mode or multi-select at least 28 positions
2.  Open Column Editor, select "Number to Insert", set "Increase by" to 9999999, "Repeat" to 1, and "Format" to "Hex"
3.  Press "OK"

### Current Behavior

Program crashes

### Expected Behavior

Numbers are inserted at selected positions

### Debug Information

```shell
Notepad++ v8.6.7   (64-bit)
Build time : May 12 2024 - 20:04:00
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line :
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
Periodic Backup : ON
OS Name : Windows 10 Pro (64-bit)
OS Version : 1809
OS Build : 17763.1579
Current ANSI codepage : 1252
Plugins :
    mimeTools (3.1)
    NppConverter (4.6)
    NppExport (0.4)
```

### Anything else?

I have localized the problem and will create a PR as soon as possible.

**Comment by alankilborn** [comment]
I can reproduce this crash bug.  For me N++ simply disappears (closes); no crash box or other type of notification.
