### ISSUE TITLE
Change All KeySequences /  new KeySequence Function "delete entire line"

### ISSUE THREAD

**Issue by Miger88** [notepad-plus-plus/notepad-plus-plus#15149]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description of the Issue

Hello,
I wish that all keyboard shortcuts could be customized. Currently, the keyboard shortcut "CTRL+D" cannot be customized.

From Eclipse, I know the keyboard shortcut "CTRL+D" for deleting entire lines. Is it possible to offer a function for deleting entire lines in Notepad++ where the keyboard shortcut can be freely selected?

### Describe the solution you'd like.

1. A new keyboard shortcut function for deleteing entire lines with customizable key shortcut combination
2. customization of keyboard short for "CTRL+D"

### Debug Information

```shell
Notepad++ v8.6.5   (64-bit)
Build time : Mar 29 2024 - 17:04:43
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
Periodic Backup : ON
OS Name : Windows 10 Pro (64-bit
OS Version : 22H2
OS Build : 19045.4412
Current ANSI codepage : 1252
Plugins : 
    ComparePlugin (2.0.2)
    mimeTools (3.1)
    NppConverter (4.6)
    NppExport (0.4)
    PoorMansTSqlFormatterNppPlugin (1.6.13.31508)
```

**Comment by alankilborn** [comment]
First, why do you think Ctrl+d cannot be customized (i.e., assigned to whatever command you like)?

**Comment by Miger88** [comment]
Cause I cannot find this Shoetcut in the Settings Gui.

**Comment by alankilborn** [comment]
Second, there already is a command for deleting a line without selecting it first, it is called SCI_LINEDELETE.

**Comment by Miger88** [comment]
Can you tell me the german function name?

**Comment by alankilborn** [comment]
> Cause I cannot find this Shortcut in the Settings Gui.

You can't find Ctrl+d ?
You aren't looking hard enough then:
![image](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/77065706/fda3efc8-8fbb-4044-b929-755fbe266ecb)

**Comment by alankilborn** [comment]
> Can you tell me the german function name?

For the line delete?
In the _Shortcut Mapper_ there is no translation; it's still SCI_LINEDELETE

**Comment by Miger88** [comment]
Perfect, that is what I searched for and didn't find in first tab named Main Menu
