### ISSUE TITLE
Restore previous tabs order when switching from Two Views to One View  

### ISSUE THREAD

**Issue by Yaron10** [notepad-plus-plus/notepad-plus-plus#1515]
STR:
Open several files.
Move to Other View (switch from One View mode to Two Views mode).
Move to Other View (switch from Two Views mode to One View mode).

Result:
In many cases the previous tabs order is not restored.

---

Related: #1513 and #1514.

**Comment by donho** [comment]
It needs more complex system to manage the tab order (therefore more coding effort).
It won't be implemented.
