### ISSUE TITLE
[BUG] Extra space inserted when inserting hexadecimal numbers with Column Editor

### ISSUE THREAD

**Issue by cddiffz** [notepad-plus-plus/notepad-plus-plus#15168]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description of the Issue

Sometimes, when inserting hexadecimal numbers with Column Editor, an extra space is inserted.

### Steps To Reproduce

1.  Type "ab" and place the cursor between the letters
2.  Open Column Editor, select "Number to Insert", set "Initial number" to 0, "Leading" to "None", and "Format" to "Hex"
3.  Press "OK"

### Current Behavior

You get "a0 b".

### Expected Behavior

You get "a0b".

### Debug Information

```shell
Notepad++ v8.6.7   (64-bit)
Build time : May 12 2024 - 20:04:00
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line :
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
Periodic Backup : ON
OS Name : Windows 10 Pro (64-bit)
OS Version : 1809
OS Build : 17763.1579
Current ANSI codepage : 1252
Plugins :
    mimeTools (3.1)
    NppConverter (4.6)
    NppExport (0.4)
```

**Comment by alankilborn** [comment]
OK, but how about providing a USEFUL use case.
No one is going to use _Column Editor_ to insert a single number.

**Comment by cddiffz** [comment]
Are you serious? This is a **minimal** example.

**Comment by donho** [comment]
Hmm... I can reproduce with several lines:

![image](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/90293/f9db57ea-3d7e-4c46-9287-7188ff2d502a)

**Comment by donho** [comment]
@cddiffz 
I can assign this issue to you if you want to provide a PR.
Otherwise, I'll fix it.

**Comment by cddiffz** [comment]
Please assign it to me.

**Comment by donho** [comment]
Hmm... after playing around, here's the result:

![image](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/90293/8c940239-816c-4814-888e-6710dee724c8)

The first column with "leading zero" and the 2nd column with "None".

So what I have said is not wrong:
https://github.com/notepad-plus-plus/notepad-plus-plus/pull/15152#discussion_r1606045567

However, I believe that if Hex is chosen, "leading zero" should be forced chosen. What do you guys think?

**Comment by cddiffz** [comment]
I would let the user decide and treat all number systems equally.

**Comment by donho** [comment]
@cddiffz 
> I would let the user decide and treat all number systems equally.

In this case, what's the correct result of the 2nd column (with **"None"**) for you?

**Comment by cddiffz** [comment]
aFE b
aFF b
a100b
a101b
…

**Comment by donho** [comment]
```
aFE b
aFF b
a100b
…
a110b
```
OK
