### ISSUE TITLE
[BUG] Clicking on the Theme Toggle Button Creates an Unnecessary Border

### ISSUE THREAD

**Issue by subhadipbhowmik** [notepad-plus-plus/notepad-plus-plus#15161]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description of the Issue

When clicking on the Theme Toggle Button, an unnecessary border appears around the button. This behavior is not consistent with the intended design and may cause visual disruption.

<img width="445" alt="note-pad-plus-plus" src="https://github.com/notepad-plus-plus/notepad-plus-plus/assets/57017965/650627a3-d4d7-4e2b-8815-b5c547c5ab30">

### Steps To Reproduce

1.  [Got NotePad++](https://notepad-plus-plus.org/)
2.  Locate the Theme Toggle Button.
3.  Click on the Theme Toggle Button.
4. Observe the appearance of an unnecessary border around the button.

### Current Behavior

After clicking the Theme Toggle Button, a border appears around the button that should not be there.

<img width="445" alt="note-pad-plus-plus" src="https://github.com/notepad-plus-plus/notepad-plus-plus/assets/57017965/c56faed5-c245-43cc-b6a4-6f5aea1e032b">

### Expected Behavior

The Theme Toggle Button should switch themes without any additional border appearing around it.

### Debug Information

```shell
Notepad++ v8.6.7   (64-bit)
Build time : May 12 2024 - 20:04:00
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line :
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
Periodic Backup : ON
OS Name : Windows 10 Pro (64-bit)
OS Version : 1809
OS Build : 17763.1579
Current ANSI codepage : 1252
Plugins :
    mimeTools (3.1)
    NppConverter (4.6)
    NppExport (0.4)
```

**Comment by alankilborn** [comment]
Step 2 says "Locate the Theme Toggle Button" -- where do you find this in Notepad++, exactly?

**Comment by subhadipbhowmik** [comment]
> Step 2 says "Locate the Theme Toggle Button" -- where do you find this in Notepad++, exactly?

Visit the website's homepage.

**Comment by alankilborn** [comment]
This site here is about issues with the Notepad++ software, not with the website that host's the program's information.
Please close this issue.
