### ISSUE TITLE
More language features

### ISSUE THREAD

**Issue by declanmarks** [notepad-plus-plus/notepad-plus-plus#1517]
I would love there to be more language features for PHP. By this I mean I would like to be able to create themes and be more specific in what I can change. At the moment, for PHP you can only change: string, string variable, simplestring, word, number, variable, comment, commentline and operator. I would like to be able to change more than this.

Many IDE's allow you to customise every aspect of the theme.

Examples of things I would like to change include instance methods and variables,  constants, classes, static methods and variables and function parameters etc.

I just feel that it is very limited at the moment.

**Comment by dail8859** [comment]
The lexers that highlight code comes from the [Scintilla](http://www.scintilla.org/) software. Notepad++ just uses this software as-is. Any new features for highlighting PHP would have to be made to that project.
