### ISSUE TITLE
[BUG] Cannot highlight text and drag to copy anymore.

### ISSUE THREAD

**Issue by sam308223** [notepad-plus-plus/notepad-plus-plus#15185]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description of the Issue

Prior to a few updates ago in Notepad ++, you had the ability to highlight text and then, while holding down Ctrl key, drag a copy of the the text to one or more places within the document. It would nice tho see this feature **restored** again. I have been using Notepad ++ for over 10 years. It's a great program. Thanks.

### Steps To Reproduce

1.  highlight text
2.  hold down Ctrl key
3.  drag a copy of the the text to one or more places within the document. 

### Current Behavior

Cannot drag a copy of the the text to one or more places within the document. anymore

### Expected Behavior

Have the ability to highlight text and then, while holding down Ctrl key, drag a copy of the the text to one or more places within the document.

### Debug Information

```shell
Notepad++ v8.6.7   (32-bit)
Build time : May 12 2024 - 20:02:31
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
Periodic Backup : OFF
OS Name : Windows 7 Professional (64-bit)
OS Build : 7601.0
Current ANSI codepage : 1252
Plugins : 
    AutoCodepage (1.2.4)
    ccc (1.4.1)
    DSpellCheck (1.4.13)
    ImgTag (2.0.1)
    mimeTools (3.1)
    MultiClipboard (2.1)
    NppConverter (4.6)
    NppExport (0.4)
    NppTextFX (0.2.6)
    PreviewHTML (1.3.2)
    SpellChecker (1.3.3)
    Tidy2 (0.2)
```

**Comment by ozone10** [comment]
duplicate of #14916

change order of steps to 1. 3. 2. to make it work

**Comment by sam308223** [comment]
I tried it. How do you get it to drag and copy like it did before in previous versions?

**Comment by sam308223** [comment]
Solution in issue by @ozone10. change order of steps to 1. 3. 2. to make it work.
