### ISSUE TITLE
[BUG] <title>TextFX Characters 

### ISSUE THREAD

**Issue by sam308223** [notepad-plus-plus/notepad-plus-plus#15188]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description of the Issue

When using TextFX Characters  to change the selected highlighted text string to either Proper, UPPER, or lower case, the last Character in  the selected text is removed (truncated).

### Steps To Reproduce

1.  Select text
2.  Using the TextFX Characters feature, highlight some text ,then select either change to Proper, UPPER, or lower case,

### Current Behavior

When using TextFX Characters  to change the selected highlighted text string to either Proper, UPPER, or lower case, the last Character in  the selected text is removed (truncated).

### Expected Behavior

Not to remove the last last Character in the selected text string.

### Debug Information

```shell
Notepad++ v8.6.7   (32-bit)
Build time : May 12 2024 - 20:02:31
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
Periodic Backup : OFF
OS Name : Windows 7 Professional (64-bit)
OS Build : 7601.0
Current ANSI codepage : 1252
Plugins : 
    AutoCodepage (1.2.4)
    ccc (1.4.1)
    DSpellCheck (1.4.13)
    ImgTag (2.0.1)
    mimeTools (3.1)
    MultiClipboard (2.1)
    NppConverter (4.6)
    NppExport (0.4)
    NppTextFX (0.2.6)
    PreviewHTML (1.3.2)
    SpellChecker (1.3.3)
    Tidy2 (0.2)
```

**Comment by alankilborn** [comment]
Plugins (except the few that are shipped with Notepad++) are not developed by the Notepad++ team, so you're reporting this in the wrong place.

**Comment by rdipardo** [comment]
@sam308223

>     NppTextFX (0.2.6)

That plugin has been superseded by TextFX&#x200D;__*2*__&#x200D;: <https://github.com/rainman74/NPPTextFX2/releases>. Please install it and close this issue.

> the last Character in the selected text is removed 

See <https://sourceforge.net/p/npp-plugins/bugs/354>.

**Comment by sam308223** [comment]
The lugin has been updated. Thank you.
