### ISSUE TITLE
Trying to open a Qt translation file kills NP++

### ISSUE THREAD

**Issue by rb07** [notepad-plus-plus/notepad-plus-plus#1518]
Problem description:

I have a Qt project with all the translation files (.ts) in a subdirectory named translations.

When I try to open one of those files, the file chooser panel opens, I navigate, select, and expand the "translations" directory, the list of files appears... and NotePad++ dies.   Tried several times, it always dies, and it is fast, no time to select a file, it only shows the list and dies.

**Comment by linquize** [comment]
How large is the file?
What are special things in the file?

**Comment by rb07** [comment]
@linquize :

The size is not relevant.  Read again what I wrote, there is nothing saying that a file was actually being opened.

Special?  Again read what I wrote.  If you don't know what a .ts file for Qt is, then in short it's a text file, in xml format, in this case UTF-8 encoded.

**Comment by rb07** [comment]
Never mind, its a Windows issue (file explorer also dies after opening the directory, it seems that Windows is trying to interpret the .ts files as something, perhaps video, and it fails in the worst possible way: killing the app).

Sorry for the noise.
