### ISSUE TITLE
[Feature request] <title>About search help.

### ISSUE THREAD

**Issue by scotenchen** [notepad-plus-plus/notepad-plus-plus#15197]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description of the Issue

The extension and regex options in the NPP's search mode options are not annotated for usage, which makes it difficult for users to use their features.

### Describe the solution you'd like.

Please annotate their usage after the extension and regex options in the NPP search mode options, just like Notepad2 does.For example, \t is enter; \n is newline;……。When annotating on this, it is best to include a Chinese annotation as well.
Thanks!

### Debug Information

```shell
tks!
```

**Comment by alankilborn** [comment]
The user manual has adequate documentation on the regular expression features of Notepad++.

**Comment by molsonkiko** [comment]
As alankilborn said, the user manual has extensive documentation on [Extended Searching](https://npp-user-manual.org/docs/searching/#extended-search-mode) and [regular expressions](https://npp-user-manual.org/docs/searching/#regular-expressions).

If you felt that *that documentation* was insufficient, the best place to complain would be at the [user manual's GitHub repo](https://github.com/notepad-plus-plus/npp-usermanual).

**Comment by scotenchen** [comment]
Therefore, what does the two mean is that when I use the search function of npp, I need to go to the user manual website to check the usage of each escape parameter and keep it in my head, so that I can use the search function of npp correctly?So what if I forget the usage of the escape parameters?Do you want to access the user manual website again?Is it convenient for users to do so?This is very inconsistent with the usage habits of Oriental people, and not every NPP user is a programming master, and its user manual website is quite complicated!I think Notepad2's approach is excellent! Think about this again, Please! thanks！

**Comment by alankilborn** [comment]
There are so many nuances to it (regex), it is pointless to bother trying to annotate it within the program.
Just keep the correct section of the manual in a tab in your web browser if remembering regex is a problem for you.

**Comment by alankilborn** [comment]
@pryrt Maybe you have opinion/advice here?

**Comment by pryrt** [comment]
In general, practice makes perfect -- the more you use a particular regular expression token, the better you will remember how to use it; when I started with regex in `vi` and `perl` in the 90s, I had to look up nearly every symbol every time; but over years of using it, I rarely have to look up most regex symbols anymore. But however you learn is the best way for learning for you.  

If going to an external website repeatedly to learn is inconvenient for you, then download the zipfile version of the User Manual so you have a local copy on your computer -- that is, after all, the reason that the User Manual includes a download link.  There is no practical difference between it being available "in the app" vs "alongside the app" if you have the offline... and you can even add a Run-menu link to open the unzipped User Manual from the Run menu.

**Comment by scotenchen** [comment]
hi, all!  I am very shocked that you programming masters would have such a low-level misunderstanding. I have already explained twice to ask you to refer to the approach of Notepad 2, so that you will find that things turned out to be so simple. There's nothing I can do, I can only take screenshots for you to see.
Additionally, you did not provide a function button to delete the search records of NPP, which makes it quite troublesome to delete the search records of NPP, not so direct. Why don't you go see how Notepad 2 works? This is regrettable!
![1](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/146079045/094f44e6-ec6f-4f9d-aefb-2845b4df6e30)

**Comment by alankilborn** [comment]
> I am very shocked that you programming masters would have such a low-level misunderstanding.

No one replying on this issue claimed to be a "programming master".

> such a low-level misunderstanding

I don't think anyone misunderstood -- at least I didn't; I knew what you were requesting from the very start.

>screenshot of Notepad2

IMO, that's hardly useful as it is too basic to be useful.

---

>you did not provide a function button to delete the search records of NPP, which makes it quite troublesome to delete the search records of NPP, not so direct.

This seems to be a different complaint?

Anyway, to delete items from the search history, drop down the combo/edit box for _Find what_ and then press the Delete key when the item you want to delete is highlighted.
