### ISSUE TITLE
[BUG] “Batch coding” color codes in 'Command' and 'Keywords' sections are not working.

### ISSUE THREAD

**Issue by OgnitorenKs** [notepad-plus-plus/notepad-plus-plus#15198]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description of the Issue

Batch coding; “Command” color scheme is not applied to headers. So when I say 'Call :Ornek', the 'Ornek' section does not get the color code. Also, the additions made to the “user-defined keywords” section in the “Keywords” section are not color coded. Version 6.4 does not have this bug. Please fix it in current versions.

Translated with Deepl.com

### Steps To Reproduce

1.  Settings
2.  Style Configurator
3.  Batch

### Current Behavior

The color codes in the 'Command' and 'Keywords' sections are not working.

### Expected Behavior

I want the color codes in the 'Command' and 'Keywords' sections to work. 

### Debug Information

```shell
Notepad++ v8.6.7   (64-bit)
Build time : May 12 2024 - 20:04:00
Path : C:\Notepad++\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : ON
Cloud Config : OFF
Periodic Backup : ON
OS Name : Windows 11 Home (64-bit)
OS Version : 23H2
OS Build : 22631.3593
Current ANSI codepage : 1254
Plugins : 
    mimeTools (3.1)
    NppConverter (4.6)
    NppExport (0.4)
```

**Comment by mpheath** [comment]
> Batch coding; “Command” color scheme is not applied to headers. So when I say 'Call :Ornek', the 'Ornek' section does not get the color code.

`:Ornek` after `Call` is a *label*, not a *command*. It was styled incorrectly in previous versions and due to fixing styling bugs was fixed. A *label* not at the start of a line has no style so is set as default style.

> Also, the additions made to the “user-defined keywords” section in the “Keywords” section are not color coded.

Appears to be working.

![nppKeywordColours](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/58158242/5b6a0916-0d55-43a0-8c3e-c1638170fd6a)

`user_defined_keyword` is styled as `KEYWORDS` in the image.

Copied from stylers.xml:

```xml
<WordsStyle name="KEYWORDS" styleID="2" fgColor="0000FF" bgColor="FFFFFF" fontName="" fontStyle="1" fontSize="" keywordClass="instre1">user_defined_keyword</WordsStyle>
```
*User-defined keywords* is theme based. Change of theme may have *User-defined keywords* as being empty so `user_defined_keyword` may not style as `KEYWORDS` with another theme.

It appears to be working as intended.

**Comment by OgnitorenKs** [comment]
Thank you for the detailed information. Since I got used to the old versions, this version seemed bad to me. Looks like I will continue to use version 6.4. Have a good day.

Translated with Deepl.com

**Comment by mpheath** [comment]
@OgnitorenKs If you choose to use current version 8.6.7 or later, then may I suggest [EnhanceAnyLexer](https://github.com/Ekopalypse/EnhanceAnyLexer) that can be installed in *Plugins Admin*.

1. Install *EnhanceAnyLexer* plugin
2. Open a batch file as active tab
3. Select in main menu *Plugins -> EnhanceAnyLexer -> Enhance current language*
4. Under `[batch]` section, add this line:
   ```ini
   0xFF8000 = (?<=call)\h*:\w+
   ```

That will color the label following `call`. That is the default stylers theme color of `#0080FF` though changed to BGR color format.

If want to also color the label following `goto`, add this line:

```ini
0xFF8000 = (?<=goto)(?:\h+|\h*:)\w+
```

The regular expression patterns should be good with ASCII characters.

Result of using both patterns:

![nppKeywordColours2](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/58158242/378ec737-c061-45bf-97eb-6bb91715be96)

**Comment by OgnitorenKs** [comment]
I installed version 8.6.7. I added the plugin as you said and applied the setting you specified. It worked for me for the most part. However, there is only one problem, when I call the tag 'Call :Test.Test', it does not color after the '.' sign. I edited the '.' sign as '_' to solve it.

![notepad++_x0U83xUkiF](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/93199689/641dcbe9-ce45-4173-8c78-aa3c72537dff)

Also, additions to the “user-defined keywords” section in the “Keywords” section do not receive color codes.

![notepad++_h252UGJsWW](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/93199689/ce0ff2d0-1618-438d-9d75-5b3802ddbfec)

![notepad++_LsDeCms9dc](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/93199689/69eff776-fdb9-491f-b8b3-212834796fb8)

Thank you for taking care of the problem. That's very kind of you.

Translated with Deepl.com

**Comment by OgnitorenKs** [comment]
The plugin you mentioned did more than enough for me. Thank you very much for your support.
