### ISSUE TITLE
How to disable / remove the annoying code line display jumping sideways to the right by one space when the code is longer than 1000 characters.

### ISSUE THREAD

**Issue by RemixPL1994** [notepad-plus-plus/notepad-plus-plus#15193]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description of the Issue

Hello.

How to disable / remove the annoying code line display jumping sideways to the right by one space when the code is longer than 1000 characters. 

### Steps To Reproduce

It is enough to have several lines of code / commands with the same number of characters that end in the same place and you can see that at the 1000th line everything shifts to the right by one additional space.

### Current Behavior

Instead of having the code in the same place all the time, after 1000 lines it diverges to the right by an additional space.

### Expected Behavior

The code before line 1000 and after 1000 and after 10000 etc. should still be shown the same.

It should not move in the program. It bothers me a lot at the moment.

### Debug Information

```shell
https://imgur.com/epzAle0

https://i.imgur.com/epzAle0.gif
```

### Anything else?

https://imgur.com/epzAle0

https://i.imgur.com/epzAle0.gif

![PROBLEM 1000 LINES](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/52541621/ced8d683-5d89-4a88-b3af-d7714015794f)

**Comment by alankilborn** [comment]
> I have searched the existing issues

Perhaps you didn't search all that well:

* #5670 
* #9161 

Choosing _Constant width_ should solve the problem:

![image](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/77065706/936133e0-da37-426a-b8b2-b291ecaed6f4)

**Comment by alankilborn** [comment]
>when the code is longer than 1000 characters

Also, try to be accurate in your reporting.  "characters" here is clearly not correct.

**Comment by rdipardo** [comment]
*F.Y.I.* There's a feature proposal on Scintilla's [mailing list](https://groups.google.com/g/scintilla-interest) that could mitigate this issue in the future:

> Applications may have a line number margin that widens or narrows depending on the number of digits needed to display all line numbers. A SC_UPDATE_LINE_COUNT flag for SCN_UPDATEUI can improve performance for this feature.
>
> <https://groups.google.com/g/scintilla-interest/c/O4R6zOtmO_M>
