### ISSUE TITLE
[BUG] Rendering performance tanks when viewing a relatively simple text file

### ISSUE THREAD

**Issue by leduyquang753** [notepad-plus-plus/notepad-plus-plus#15191]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description of the Issue

When opening the attached text file, Notepad++ struggles a lot more to render frames.

[11.1-3d.txt](https://github.com/notepad-plus-plus/notepad-plus-plus/files/15443821/11.1-3d.txt)

### Steps To Reproduce

1. Open the text file.
2. Scroll and observe the rendering performance (frame rate, CPU usage).

### Current Behavior

The window can only update at a rate of less than 10 frames per second on my machine, the application can also be seen to consume much of the available CPU time.

### Expected Behavior

Fast rendering and smooth updates.

### Debug Information

```shell
Notepad++ v8.6.7   (64-bit)
Build time : May 12 2024 - 20:04:00
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : "C:\Program Files\Notepad++\change.log" 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
Periodic Backup : ON
OS Name : Windows 11 Pro (64-bit)
OS Version : 23H2
OS Build : 22631.3593
Current ANSI codepage : 65001
Plugins : 
    ComparePlugin (2.0.2)
    MarkdownViewerPlusPlus (0.8.2)
    mimeTools (3.1)
    NppConverter (4.6)
    NppExport (0.4)
    NPPJSONViewer (1.40)
    XMLTools (3.1.1.13)
```

**Comment by molsonkiko** [comment]
I can't replicate this on any of my Notepad++ installations (versions 8.4.9 through a version slightly after 8.6.7), regardless of what plugins I have installed. Maybe try uninstalling some of your plugins and see if that helps?

**Comment by leduyquang753** [comment]
> I can't replicate this on any of my Notepad++ installations (versions 8.4.9 through a version slightly after 8.6.7), regardless of what plugins I have installed. Maybe try uninstalling some of your plugins and see if that helps?

I just removed all plugins and the issue still persists.

**Comment by leduyquang753** [comment]
It seems like the issue is related to fonts. I normally use a custom-built version of [Iosevka](https://github.com/be5invis/iosevka) and as I changed the font to Consolas it is smooth again.

**Comment by leduyquang753** [comment]
As I checked in other editors they also have a performance problem, so turns out this is possibly something about Windows itself and not Notepad++.
