### ISSUE TITLE
make backup path changeable

### ISSUE THREAD

**Issue by msjasinski** [notepad-plus-plus/notepad-plus-plus#1520]
I faced this problem after system crash and reinstall. I simply forgot to copy preedited documents (which I use a lot) from C:\Users\USERNAME\AppData\Roaming\Notepad++\backup to my other drive before format C:, because I was pressed for time and I (wisely) keep most if not all my data on drive D:, so I didn't expect them to be lost (this being a relatively new feature).

This could have been prevented if backup path were changeable.

For more scenarios & arguments for this change see discussion: https://notepad-plus-plus.org/community/topic/51/can-t-change-backup-path-under-settings-preferences-backup-session-snapshot-and-periodic-backup

**Comment by vgturtle127** [comment]
:+1:

**Comment by MetaChuh** [comment]
please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins if you update from version 7.5.9 or below.
if your issue still persists, and it is still of relevance to you, please feel free to file a new issue as easy to understand and reproducible as possible.

thank you for your support and best regards.

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
(no extra account is needed, just use your github account to sign in)
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)
