### ISSUE TITLE
[BUG] Begin/End Select Problem

### ISSUE THREAD

**Issue by RitzSpecial** [notepad-plus-plus/notepad-plus-plus#15221]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description of the Issue

After using Begin/End Select to start a selection and another Begin/End Select to end the selection, and deleting the selection, pressing cursor keys to move causes a continued selection.

### Steps To Reproduce

1.  Ctrl-Shift-B
2.  Select some text
3.  Ctrl-Shift-B
4. Press Delete to delete it
5. Press a cursor key and see a selection get expanded instead of just moving the cursor.

### Current Behavior

Trying to move the cursor with the cursor keys after using Begin/End Select is selecting text along the cursor's path.

### Expected Behavior

I expect that once the selection is ended that any cursor movements would simply be cursor movements.

### Debug Information

```shell
Notepad++ v8.6.7   (64-bit)
Build time : May 12 2024 - 20:04:00
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : "C:\Users\j.ritter\AppData\Roaming\Notepad++\shortcuts.xml" 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
Periodic Backup : ON
OS Name : Windows 10 Enterprise (64-bit)
OS Version : 22H2
OS Build : 19045.4412
Current ANSI codepage : 1252
Plugins : 
    HexEditor (0.9.12)
    mimeTools (3.1)
    NppConverter (4.6)
    NppExport (0.4)
    NppFTP (0.29.12)
```

### Anything else?

I have v7.3.3 on another machine and it acts as expected with a Begin/End Select sequence and normal cursor movements afterward.

**Comment by molsonkiko** [comment]
I did some bisection search, and it appears that this issue originated in [version 8.5](https://notepad-plus-plus.org/downloads/v8.5/), meaning that the last version where the issue was *not present* was [version 8.4.9](https://notepad-plus-plus.org/downloads/v8.4.9/).

Version 8.5 also happens to be the first version where Ctrl+Shift+B was a keyboard shortcut for this command, so probably this is some weirdness associated with that change.

**Comment by alankilborn** [comment]
> Version 8.5 also happens to be the first version where Ctrl+Shift+B was a keyboard shortcut for this command

As that was a change _I_ made, I'll look into it.  :-)

@donho Assign me, please.

**Comment by alankilborn** [comment]
It appears to be a difficulty with this line, added in https://github.com/notepad-plus-plus/notepad-plus-plus/pull/13034:

https://github.com/notepad-plus-plus/notepad-plus-plus/blob/6cd6aa38432c6c33a8bc762ccc5b59a198a6438b/PowerEditor/src/ScintillaComponent/ScintillaEditView.cpp#L2796

I suggest to eliminate that line and replace it with:

		if (isColumnMode)
		{
			execute(SCI_SETSELECTIONMODE, static_cast<WPARAM>(SC_SEL_RECTANGLE));
		}

**Comment by alankilborn** [comment]
It still feels like the original code should work, but clearly Scintilla doesn't like it.
Maybe @nyamatongwe has some suggestion on how this should be written so that moving the caret with an arrow key after deleting/cutting selected text doesn't create a selection.

**Comment by nyamatongwe** [comment]
https://www.scintilla.org/ScintillaDoc.html#SCI_CHANGESELECTIONMODE

**Comment by alankilborn** [comment]
SCI_CHANGESELECTIONMODE is a newer API I was unfamiliar with.  But OK...

It still looks/feels a bit odd, but here's the code I'm thinking of proposing:

```
void ScintillaEditView::beginOrEndSelect(bool isColumnMode)
{
	auto currPos = execute(SCI_GETCURRENTPOS);
	
	if (_beginSelectPosition == -1)
	{
		_beginSelectPosition = currPos;
	}
	else
	{
		execute(SCI_CHANGESELECTIONMODE, static_cast<WPARAM>(isColumnMode ? SC_SEL_RECTANGLE : SC_SEL_STREAM));
		execute(isColumnMode ? SCI_SETANCHOR : SCI_SETSEL, 
			static_cast<WPARAM>(_beginSelectPosition), 
			static_cast<LPARAM>(currPos));
		_beginSelectPosition = -1;
	}
}
```
