### ISSUE TITLE
Unify VS project files

### ISSUE THREAD

**Issue by linquize** [notepad-plus-plus/notepad-plus-plus#1523]
It is possible maintain only one VS project file for both VS2013 and VS2015.

**Comment by NN---** [comment]
I wish the project moved to VS2015.
It is stable enough to develop.

**Comment by NN---** [comment]
Any progress ?

**Comment by NN---** [comment]
@donho Is there anything preventing from doing this ?
That way it is easy to extend it to VS15 as well.
Thanks.

**Comment by donho** [comment]
@NN--- 
For the sake of stability, I prefer to have them separately.

**Comment by NN---** [comment]
@donho I really don't see how it can affect stability , but I do see how it annoying to merge changes and make PR each time project changes.
