### ISSUE TITLE
[BUG] Find Previous (Shift + F3) doesn't work in the last update 8.6.7

### ISSUE THREAD

**Issue by StelianNicolae** [notepad-plus-plus/notepad-plus-plus#15239]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description of the Issue

Find Previous (Shift + F3) doesn't work in the last update 8.6.7

### Steps To Reproduce

1. Search a word (with F3), it finds it properly. 
2. Try do go to the previous find, and it doesn't do anything.
3. Find Previous (Shift + F3) doesn't work in the last update 8.6.7. 
    - It doesn't work also from Search menu

* In find Menu, backward option is disabled

### Current Behavior

Notepad++ doesn't do anything when pressing Shift + F3 or Find Previous from menu.

### Expected Behavior

Shift + F3 or Find Previous should work (similar to F3)

### Debug Information

```shell
Notepad++ v8.6.7   (64-bit)
Build time : May 12 2024 - 20:04:00
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : "C:\Program Files\Notepad++\change.log" 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
Periodic Backup : ON
OS Name : Windows 10 Enterprise (64-bit)
OS Version : 22H2
OS Build : 19045.4412
Current ANSI codepage : 1252
Plugins : 
    mimeTools (3.1)
    NppConverter (4.6)
    NppExport (0.4)
```

**Comment by alankilborn** [comment]
Is your _Search mode_ set to _Regular expression_?
Backward searching does not work in this mode.

If that's not the case, you need to provide more specifics about what exactly you are doing, what is the string you are searching for, etc.

**Comment by alankilborn** [comment]
Just a note about visual cues you _do_ get that backward search isn't enabled...these controls are not enabled when _Search mode_ is _Regular expression_:

![image](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/77065706/bc0f95c5-e3cd-426f-91b2-14043b9c227d)
