### ISSUE TITLE
Broken x64 build since v6.8.9-3-g07ce6c2

### ISSUE THREAD

**Issue by linquize** [notepad-plus-plus/notepad-plus-plus#1524]
Broken x64 build since v6.8.9-3-g07ce6c2

**Comment by NN---** [comment]
See  #1525

**Comment by cmeriaux** [comment]
@linquize ,
when you compile x64, you have to compile scintilla in x64. Am I right ? 
How do you compile scintilla in x64 ?

**Comment by linquize** [comment]
You need to patch `scintilla.mak` first
(https://github.com/linquize/notepad-plus-plus/commit/461784b8ae2432bbdc56ad484f9a57f022e8d7e1)

Open VS2015 x64 Command Prompt
```
cd scintilla\win32
nmake -f scintilla.mak
```

**Comment by cmeriaux** [comment]
@linquize  Thanks
