### ISSUE TITLE
[BUG] Status bar flickers when updated

### ISSUE THREAD

**Issue by yirkha** [notepad-plus-plus/notepad-plus-plus#15260]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description of the Issue

Hi everyone.

Sometimes I use Notepad++ to write a lot of text in a kind of distraction-free mode (F11 full-screen, dark mode, etc.) and I have noticed during this that the status bar flickers quite often.

Because this ruins the nice experience a bit, I want to propose fixing this by implementing double buffering.

### Steps To Reproduce

1.  Open Notepad++
2.  Start writing some long text, or even just hold down a random character key

### Current Behavior

The status bar (`length : 51    lines : 1 | Ln : 1    Col : 52    Pos : 52 | ...` ) is redrawn after each keystroke.
This is done in two steps, as typical for Win32 controls - first erase the background and then write the new text over it.
Sometimes these two steps happen separately and become visible to the user as flickering of the text.

### Expected Behavior

Updates of the status bar are flicker-free. User experience is smooth, fluent and without distractions.

### Debug Information

Tested also on the latest commit of "master" from today.
Happens for both normal mode (standard control) and dark mode (custom drawn).

### Anything else?

~Proposed fix in a fork: https://github.com/yirkha/notepad-plus-plus/commit/8ecc6697214c1c2d03099b3f5763dddbf4dff5c1~ Edit: obsolete

Thank you for your consideration

**Comment by xomx** [comment]
@donho 
I tried that fork and it seems to work ok, the described flickering is gone (I tested by the mentioned key-holding).
IDK if there are some other places which could benefit from such double buffering(?).

**Comment by yirkha** [comment]
Thank you for trying it out and verifying the changes!

> are there some other places which could benefit from such double buffering?
Good question. I was wondering the same, if to put DoubleBuffer.h rather to some common directory for reuse. But I did not think of anything similarly updated/repainted often, except the Scintilla editor itself which works fine, of course. So I decided to not complicate things and leave it under StatusBar/.

Now I tried again and duh, the tab bar. Hold Ctrl+N or Ctrl+T and you'll see. Even much more in multi-line mode.
So I'd propose doing the same change analogically also in TabBarPlus to rectify that too: https://github.com/yirkha/notepad-plus-plus/commit/d66f2bb11d92ca63b04a94786e4d9c71d0fcacc0

**Comment by ozone10** [comment]
@yirkha 
can you do PR? 

@xomx 
> IDK if there are some other places which could benefit from such double buffering(?).

Maybe splitters and containers.

**Comment by donho** [comment]
@yirkha 
Sounds interesting...
Could you do a PR for that?

**Comment by yirkha** [comment]
Sure, I'll submit a PR. I just wanted to discuss first per the contributing guidelines.

@ozone10 Good idea with splitters/panels. Turns out resizing those causes some ugly blinking too. So I'll see about that as well

**Comment by ozone10** [comment]
@yirkha 
Could you do a PR for status bar and tab bar firstly? So the PR is not too complex and if there are some requested changes, you won't have to rewrite much.

**Comment by yirkha** [comment]
Okay, you go ^
