### ISSUE TITLE
[BUG] minor: Consolas UTF-8 \xE2\xA4\xA3 glyph rendering

### ISSUE THREAD

**Issue by leok7v** [notepad-plus-plus/notepad-plus-plus#15262]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description of the Issue

Rendering text file with UTF-8 sequence "\xE2\xA4\xA3"
North West Arrow with Hook
https://www.compart.com/en/unicode/U+2923
and possibly others failed to show correct glyph for UTF-8 codepoint while Notepad.exe with the same Consolas font can.

Screenshot and files attached.

![image](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/1149445/43b63d97-eb5c-4341-b973-55ac9bf5fffe)

[sample8_crash_log.txt](https://github.com/user-attachments/files/15754120/sample8_crash_log.txt)

Notepad v8.6.5

### Steps To Reproduce

1.  Open attached document in both Notepad++.exe and Notepad.exe 
2. Make sure Encoding is set to UTF-8
2. Observe difference in rendering.

### Current Behavior

See screenshot

### Expected Behavior

Correct glyph rendering (see screenshot)

### Debug Information

```shell
Notepad++ v8.6.5   (32-bit)
Build time : Mar 29 2024 - 17:02:48
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Command Line : "C:\Users\leok7v\sample8_crash_log.txt" -multiInst -nosession -x94 -y915 -lnormal -n14 -c93
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
Periodic Backup : OFF
OS Name : Windows 10 Enterprise (64-bit
OS Version : 22H2
OS Build : 19045.4412
Current ANSI codepage : 1252
Plugins : 
    DSpellCheck (1.3.5)
    mimeTools (3.1)
    NppConverter (4.6)
    NppExport (0.4)
```

### Anything else?

![image](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/1149445/f56f66f1-5a74-4e22-8236-36d671055bd3)
[sample8_crash_log.txt](https://github.com/user-attachments/files/15754133/sample8_crash_log.txt)

**Comment by xomx** [comment]
![npp-DirectWrite](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/13075183/91f9e205-93cd-48b2-bb5d-618ac5c1f78c)

**Comment by leok7v** [comment]
Yes, it did help. Though I actually render the same sequence myself using GDI DrawTextW() (converting UTF-8 to UTF-16) and it does work.
Nevertheless pure cosmetics for now. Feel free to reject and close.
Thank you very much for the prompt response and maintaining and developing very very useful tool.

![image](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/1149445/fb7963d3-7c69-4925-8401-db7200f13fd8)
