### ISSUE TITLE
Find/Replace modal opacity is transparent in dark mode

### ISSUE THREAD

**Issue by bekahbeets2003** [notepad-plus-plus/notepad-plus-plus#15266]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description of the Issue

When pressing Ctrl+F/Ctrl+H on Windows 10, the modal is mostly transparent

![image](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/717608/28e4739a-83c4-4418-9c10-dfcfda0a24a7)

### Steps To Reproduce

1.  Open Npp
2.  Change to dark mode
3.  Press Ctrl+F, Ctrl+H
4. Make coffee
5. Put on desired music
6. Fix bug or cry, whichever ya need. Possibly simultaneous

### Current Behavior

Currently, I am experience imposter syndrome, existential dread, with some dramatic angst

### Expected Behavior

To cause the dev to cry out to the heavens bc another bug

### Debug Information

```shell
Notepad++ v8.6.6   (64-bit)
Build time : May  6 2024 - 21:59:00
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : "C:\Program Files\Notepad++\change.log" 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
Periodic Backup : ON
OS Name : Windows 10 Pro (64-bit)
OS Version : 22H2
OS Build : 19045.4412
Current ANSI codepage : 1252
Plugins : 
    MarkdownViewerPlusPlus (0.8.2)
    mimeTools (3.1)
    NppConverter (4.6)
    NppExport (0.4)
    NPPJSONViewer (1.40)
    NppMarkdownPanel (0.7)
```

**Comment by ozone10** [comment]
Did you notice that there is Transparency checkbox down right?

**Comment by bekahbeets2003** [comment]
I did not... I must have accidentally hit that at some point
