### ISSUE TITLE
[BUG] Renaming files

### ISSUE THREAD

**Issue by EliasB1110** [notepad-plus-plus/notepad-plus-plus#15274]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description of the Issue

You can't rename a unsaved file, when you only want to change the large and lower case. 

### Steps To Reproduce

1.  Name a file without saving (TestFile)
2.  Rename this file without saving, use the same name but i dont want to be the F capital (Testfile)
3.  There is the error 

### Current Behavior

It tells that the name is already used in another tab

"Rename failed - The specified name is already in use on another tab."

### Expected Behavior

Renaming the file

### Debug Information

```shell
Notepad++ v7.9.5   (32-bit)
Build time : Mar 21 2021 - 02:09:07
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS Name : Windows Server 2012 R2 Datacenter (64-bit) 
OS Build : 9600.0
Current ANSI codepage : 1252
Plugins : ComparePlugin.dll mimeTools.dll NppConverter.dll NppExport.dll
```

### Anything else?

Tested on several machines and with a fresh installation

**Comment by alankilborn** [comment]
Confirmed in:

Notepad++ v8.6.8   (64-bit)
Build time : Jun  4 2024 - 00:30:00
Path : C:\NotepadPlusPlus\Misc\_NoBackup\Releases\npp.8.6.8\npp.8.6.8.portable.x64\notepad++.exe
Command Line : -titleAdd="8.6.8 64-bit" -multiInst
Admin mode : OFF
Local Conf mode : ON
Cloud Config : OFF
Periodic Backup : ON
OS Name : Windows 11 Pro (64-bit)
OS Version : 23H2
OS Build : 22631.3737
Current ANSI codepage : 1252
Plugins : 
    mimeTools (3.1)
    NppConverter (4.6)
    NppExport (0.4)
    PythonScript (3.0.18)

**Comment by alankilborn** [comment]
(Obvious) Workaround when you have `mytab` and you want `MyTab` (for example):

* rename `mytab` to an unrelated name not in use on any tab (e.g. `temp`)
* rename `temp` to `MyTab`

**Comment by xomx** [comment]
Similar issue: #12396

> You can't rename a unsaved file, when you only want to change the large and lower case.

There already was a PR ( #14971 ) fixing that but it has to be reverted as it caused a regression.

**Comment by donho** [comment]
We can't change any file name UPPER/lower case in Notepad++, unsaved or saved file.
The reason is provided here:
https://github.com/notepad-plus-plus/notepad-plus-plus/issues/14724#issuecomment-2094562208
