### ISSUE TITLE
Show smart highlight occurrence lines in vertical scroll bar

### ISSUE THREAD

**Issue by tisimst** [notepad-plus-plus/notepad-plus-plus#1527]
**Feature Request**
This isn't critical, but I think it would be a useful feature. In some web-browsers (like Google Chrome), when you are in search/find mode, a light colored line will appear within the vertical scroll bar itself to show the relative location of each occurrence on the page. In addition to the regular "Smart Highlight" feature (which is sooooo helpful), I think this additional functionality can only make it that much better.

**Comment by adigourdi** [comment]
This would be useful, hope we'd have it in the near future, **+1**

**Comment by MetaChuh** [comment]
please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins if you update from version 7.5.9 or below.
if your issue still persists, and it is still of relevance to you, please feel free to file a new issue as easy to understand and reproducible as possible.

thank you for your support and best regards.

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
(no extra account is needed, just use your github account to sign in)
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)

**Comment by tisimst** [comment]
So, did this feature get added?

**Comment by sasumner** [comment]
@tisimst Nope.

**Comment by tisimst** [comment]
On Thu, Apr 18, 2019 at 6:14 AM sasumner <notifications@github.com> wrote:

> @tisimst <https://github.com/tisimst> Nope.
>
That’s totally fine. I hope my question didn’t come across as a complaint.
I will gladly continue to use the app anyway.

I understand it may take a lot of effort to implement this wishlist item,
but why mark the issue closed if it’s not? At least a statement about why
it won’t be implemented anytime soon would be sufficient to close it.

**Comment by sasumner** [comment]
> I hope my question didn’t come across as a complaint.

Not at all.  To me it was an "Enhancement suggestion".

>but why mark the issue closed if it’s not?

I think it is just a by-product of mass issue closure currently going on.
