### ISSUE TITLE
[BUG] Another instance of Notepad++ is already running. Please close other instances of Notepad++ before launching Notepad++ Portable.

### ISSUE THREAD

**Issue by J0n1k4** [notepad-plus-plus/notepad-plus-plus#15284]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description of the Issue

I have Notepad++ Portable. I do not have any other versions installed.
Some files are opened in N++.
I try to open another TXT file by clicking on it. I get the 
"Another instance of Notepad++ is already running. Please close other instances of Notepad++ before launching Notepad++ Portable."
warning.

### Steps To Reproduce

1.  I have Notepad++ Portable. I do not have any other versions installed.
Some files are opened in N++.

2.  I try to open another TXT file by clicking on it. I get the 
"Another instance of Notepad++ is already running. Please close other instances of Notepad++ before launching Notepad++ Portable." warning.
3.  I close the warning, the TXT file is not opened.
4. I close the N++, and then click on a file, it is then opened.

### Current Behavior

I can't open TXT file in already running N++ portable by clicking on a file.
I have to close it and then click on a new file to be able to open it

### Expected Behavior

I don't want to open this TXT in another instance - I want to open it in current one, in new tab.

### Debug Information

```shell
Notepad++ v8.4.4   (64-bit)
Build time : Jul 15 2022 - 17:54:42
Path : C:\_APPS\Notepad++Portable\App\Notepad++64\notepad++.exe
Command Line : "C:\Users\SRJ1999\Downloads\SSGET Info.txt"
Admin mode : OFF
Local Conf mode : ON
Cloud Config : C:\_APPS\Notepad++Portable\Data\Config
OS Name : Windows 10 Enterprise (64-bit) 
OS Version : 22H2
OS Build : 19045.4355
Current ANSI codepage : 1252
Plugins : 
    ComparePlugin (2.0.2)
    mimeTools (2.8)
    NppConverter (4.4)
    NppExport (0.4)
```

### Anything else?

![image](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/26709833/0ac129c6-46ed-46c9-ba67-a5dcc5941afd)

**Comment by alankilborn** [comment]
"PortableApps" is not supported and questions/problems won't be addressed here.
Please close this issue.

**Comment by ozone10** [comment]
@J0n1k4 
better to ask on their forum, IIRC if you're using portable apps never add file association to app directly, add association to launcher. Still adding file association for portable apps is wrong.

**Comment by xomx** [comment]
https://portableapps.com/forums/support/development
