### ISSUE TITLE
[Feature request] Hide Close button on inactive tabs

### ISSUE THREAD

**Issue by WildByDesign** [notepad-plus-plus/notepad-plus-plus#15298]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description of the Issue

This is just a concept at the moment. The inactive tabs might look cleaner and less busy by hiding the close button.

### Describe the solution you'd like.

Hide the close button on inactive tabs. Only show the close button on inactive tabs when the mouse hovers over.

This will require the close button BMP images to be converted to ICO to benefit from transparency and better scaling.

### Debug Information

```shell
Notepad++ v8.6.8   (64-bit)
Build time : Jun 15 2024 - 08:53:28
Path : D:\Tools\Notepad++\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : ON
Cloud Config : OFF
Periodic Backup : ON
OS Name : Windows 11 Pro (64-bit)
OS Version : 24H2
OS Build : 26100.863
Current ANSI codepage : 1252
Plugins : 
    mimeTools (2.9)
    NppConverter (4.5)
    NppExport (0.4)
    RainLexer (2.21)
```

### Anything else?

![animation](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/26308319/53966498-5683-42df-a635-a0df1580cb5e)

**Comment by alankilborn** [comment]
The proposal is not a good one.
It would turn a one-step close action into a two-step action -- first have to activate the tab, then press the `x`.

**Comment by CennoxX** [comment]
It would be better, if the x shows direct, when hovering above the tab, not the place, where I suspect the close button to come. And I think it has to be possible to deactivate this behaviour.

**Comment by myTempTemp** [comment]
侯今吾是一条狗 我家里有一条狗，我给它起名叫侯今吾，来吃点屎吧！

**Comment by WildByDesign** [comment]
> when hovering above the tab, not the place, where I suspect the close button to come

This is a very good point, I agree.

**Comment by donho** [comment]
@WildByDesign 
I will see if it's easy to be implemented. But I promise nothing.

**Comment by donho** [comment]
@WildByDesign 
Different from file state images (saved, dirty, RO & monitoring) on the document tab, close buttons are in BMP format.

After some googling, the bitmap support the transparency:
https://stackoverflow.com/questions/14195289/can-a-bmp-image-format-handle-transparency

So if you manage to create a transparent bmp and use it to replace **closeTabButton_inact.bmp**, then this FR is feasible.
Could you try it and let me know the result please?

**Comment by WildByDesign** [comment]
@donho 
> Could you try it and let me know the result please?

I just tried this morning with all formats of BMP transparency (`A1:R5:G5:B5 (16 bpp)`, `A4:R4:G4:B4 (16 bpp)` and `A8:R8:G8:B8 (32 bpp)`) and they all failed to show the transparency. The two 16 bpp formats caused all of the close button icons to fail to function. The 32 bpp with alpha didn't cause the failure in functionality but did not show the transparency.

Also of note, Notepad++ has always had that built-in functionality with BMP icons to grab 1 pixel from a corner and automatically turn all pixels of that matching color into a layer of transparency. That works for all other BMP icons in Notepad++ but has never worked for the close button BMPs for some reason.

I have an idea based on what @CennoxX said above. This should come first before the icons but is related. We need to know which inactive tab the mouse is hovering over so that it can trigger a slightly brighter color. And as a future step, it could also potentially trigger an icon change.

Example inactive tab mouse hovering (from Firefox):

![Animation](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/26308319/b8ccd970-d7a8-4123-87db-d2372724e43a)

Is this possible?

**Comment by WildByDesign** [comment]
@alankilborn @CennoxX  Can I please get your opinion on this?

I brought back the close buttons on the inactive tabs but made them dimmed to about 10%. I also added a little animation to the close button when actually closing a tab. These are very subtle changes but I really like them so far.

![Animation](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/26308319/c8950585-4405-4bcb-a808-50d3b74caca6)

You may have to click to start the animated gif.

**Comment by CennoxX** [comment]
For me, this solution looks less busy than the status quo and seems to be a better than completely hiding the close button.

**Comment by ozone10** [comment]
Notepad++ use `LoadBitmap` which I think does not support transparency, I will see what I can do.

**Comment by donho** [comment]
@WildByDesign 

Thanks to @ozone10 's [PR](https://github.com/notepad-plus-plus/notepad-plus-plus/commit/8760dd2c07cda889dd257eeddba00a537080fbc9) (merged into the master), we can have this feature with codeless or less coding effort. 

Could you try from your side to a transparent ico and use it to replace closeTabButton_inact.ico?
If it does work for you, then I will see how to make it as an option.

**Comment by WildByDesign** [comment]
@donho 
> Could you try from your side to a transparent ico and use it to replace closeTabButton_inact.ico?

Yes, transparency is working perfectly and the icons that I am working on right now for close buttons are showing up sharp and nice at scaling 100, 125 and 150 so far.

I just have to nail down the exact measurements between those scaling scenarios for perfect consistency. They should be done tonight or tomorrow morning at the latest.

**Comment by donho** [comment]
@WildByDesign 
Take your time :)

When you're ready, please commit under the name "closeTabButton_inact_hidden.ico" and also add the transparent icon in standard icon folder.

**Comment by donho** [comment]
https://github.com/notepad-plus-plus/notepad-plus-plus/commit/8e1f6414724111bdffb24b886ff43d481bc879e0

**Comment by donho** [comment]
Reopen it because the commit above doesn't address the issue.

**Comment by WildByDesign** [comment]
This is really exciting and totally made my day! This opens up more possibilities for the design.

I can’t test this until later tonight but I will compile in a few hours and provide some feedback at that time.

**Comment by silkfire** [comment]
@WildByDesign @donho Is there any way to restore the old behavior? I prefer to always see the close button, even on inactive tabs.
