### ISSUE TITLE
[BUG] Crash with inserted text

### ISSUE THREAD

**Issue by abydos2002** [notepad-plus-plus/notepad-plus-plus#15292]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description of the Issue

I frequently copy articles from reddit to Notepadd++ into a new empty file. When going to the first or second line und trying to insert a newline the app freezes and shuts down. On restart the file (most times) appears as automatically saved 'new1.txt', sometimes as emty file.
This does not happen if saved beforehand, and happens apparently without any recognizeable cause, in about every 10th - 15th try

Not  a severe bug, but annoying from time to time :-)

### Steps To Reproduce

1.  open an article on reddit (browser), it seem longer texts with a couple of newlines produces the error more often
2. copy the contents
3. paste it into a new file
4. move to beginning (ctrl+pos1)
5. go to the beginning of the second line with text
6. hit 'Enter'
7.  move up with arrow keys to first emty line
8. hit 'Enter'
9. error occurs randomly

### Current Behavior

app freezes and shuts down

### Expected Behavior

app should not crash

### Debug Information

```shell
Notepad++ v8.6.8   (32-bit)
Build time : Jun  4 2024 - 00:29:00
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Command Line : 
Admin mode : ON
Local Conf mode : OFF
Cloud Config : OFF
Periodic Backup : ON
OS Name : Windows 10 Enterprise (64-bit)
OS Version : 22H2
OS Build : 19045.4529
Current ANSI codepage : 1252
Plugins : 
    DSpellCheck (1.4.17)
    mimeTools (3.1)
    NppAutoIndent (1.2)
    NppConverter (4.6)
    NppExport (0.4)
    Tidy2 (0.2)
    XMLTools (3.1.1.1)
```

### Anything else?

Thank you for this really excellent editor

**Comment by xomx** [comment]
Do you mean to copy something from [here](https://www.reddit.com/r/Articles/)?

Better be more specific and append here directly a zipped file with an example content being copied into N++ and causing your issue.

**Comment by myTempTemp** [comment]
侯今吾是一条狗 我家里有一条狗，我给它起名叫侯今吾，来吃点屎吧！

**Comment by xomx** [comment]
It could also be caused by one of your outdated plugins, you should upgrade them (menu > Plugins > Plugins Admin... > Updates tab).

If that does not help, you can test the problem without any plugin and if that solves your issue, you can put back your plugins one by one to determine the culprit. See the "Possible Culprit: Plugin" part of this FAQ"
https://community.notepad-plus-plus.org/topic/23146/faq-notepad-crashes-freezes-unresponsive-after-update

**Comment by donho** [comment]
@abydos2002 
I do believe it's a plugin issue.
Please follow @xomx 's suggestion and report the culprit plugin.
