### ISSUE TITLE
[REGRESSION] Find Replace size is not remembered through the sessions

### ISSUE THREAD

**Issue by donho** [notepad-plus-plus/notepad-plus-plus#15294]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description of the Issue

Find Replace size is not remembered in the next session, though its position is.

### Steps To Reproduce

1.  Open Find Replace dialog, drag it to a place, and enlarge it.
2.  Close Notepad++ and relaunch it.
3.  Open Find Replace dialog.

### Current Behavior

It's at the position where it was dropped, but with its size minimum.

### Expected Behavior

Both position and size should be remembered.

### Debug Information

```shell
Notepad++ v8.6.8   (64-bit)
Build time : Jun  4 2024 - 00:30:00
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
Periodic Backup : ON
OS Name : Windows 11 Home (64-bit)
OS Version : 23H2
OS Build : 22631.3672
Current ANSI codepage : 1252
Plugins : 
    mimeTools (3.1)
    NppConverter (4.6)
    NppExport (0.4)
```

### Anything else?

It's a regression of v8.6.8 - it works fine in v8.6.7

**Comment by ozone10** [comment]
@donho 
https://github.com/notepad-plus-plus/notepad-plus-plus/pull/15158#discussion_r1606008602

**Comment by donho** [comment]
@ozone10 
My bad!

**Comment by donho** [comment]
@ozone10 
Do you want to work on it?

**Comment by ozone10** [comment]
@donho 
sorry I will be away until end of June.
But removing "_" from "rc" in (to use saved size instead of minimal)
https://github.com/notepad-plus-plus/notepad-plus-plus/blob/fa2fce2b41a36340c8f7a86b2c061a8895059161/PowerEditor/src/ScintillaComponent/FindReplaceDlg.cpp#L350
should work for current dpi manifest.

**Comment by donho** [comment]
Thank you @ozone10 for the remote quick patch!

**Comment by psantofe** [comment]
Found the same problem: Find in Files window doesn't memorize its modified dimensions and start always with default ones.
