### ISSUE TITLE
Language menu doesn't show seletced lexer if in compact mode

### ISSUE THREAD

**Issue by ClaudiaFrank** [notepad-plus-plus/notepad-plus-plus#1529]
When in compact mode only lexers in c group, like C, C# C++... get the marker to show that this lexer is used, all other lexers, UDL included, don't get the ball icon in front of the lexer name.
npp 6.8.7/6.9 windows 7 x64

**Comment by dail8859** [comment]
Duplicate of #1095

**Comment by ClaudiaFrank** [comment]
Yep, agreed - I was searching if it has been already reported but didn't find it.
I'm going to close it.
