### ISSUE TITLE
[BUG] Wrong rename dialog box can appear

### ISSUE THREAD

**Issue by alankilborn** [notepad-plus-plus/notepad-plus-plus#15307]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description of the Issue

See Steps below

### Steps To Reproduce

1.  Press Ctrl+n to create a new tab
2.  Rename the tab to `nul`
3.  Start the rename process for the tab again

### Current Behavior

The Windows standard dialog for renaming (really it's the SaveAs dialog with a different title) appears, instead of the unsaved tab renaming dialog.

### Expected Behavior

The unsaved tab renaming dialog should appear; specifically, this one:

![image](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/77065706/79194b85-1f2c-4134-a607-55d19ed8a027)

### Debug Information

```shell
Notepad++ v8.6.8   (64-bit)
Build time : Jun  4 2024 - 00:30:00
Path : C:\NotepadPlusPlus\Misc\_NoBackup\Releases\npp.8.6.8\npp.8.6.8.portable.x64\notepad++.exe
Command Line : -titleAdd="8.6.8 64-bit" -multiInst
Admin mode : OFF
Local Conf mode : ON
Cloud Config : OFF
Periodic Backup : ON
OS Name : Windows 11 Pro (64-bit)
OS Version : 23H2
OS Build : 22631.3737
Current ANSI codepage : 1252
Plugins : 
    mimeTools (3.1)
    NppConverter (4.6)
    NppExport (0.4)
    PythonScript (3.0.18)
```

**Comment by xomx** [comment]
This is another reason for the valid filename checking requested in the #15211 . The essence of this issue is that for the Windows shell funcs used in N++ (here the PathFindFileName) is the "nul" (or "NUL") a valid WIN32 pseudoname and it consequently confuses the N++ to think that its tab/filebuffer is a valid file...

I will try a PR for this later (I will also include this [fix](https://github.com/notepad-plus-plus/notepad-plus-plus/pull/15211#issuecomment-2156733853)).

**Comment by alankilborn** [comment]
@xomx said:

>I will try a PR for this later

Did you ever do this?

**Comment by xomx** [comment]
No, but it fixed "itself". This is the best way, I like it ;-)

(it is a positive byproduct of the [using the GetFileAttributes instead of PathFileExists](https://github.com/notepad-plus-plus/notepad-plus-plus/commit/0858dfa4afc4353653e9cf3fc47f8b23f18f48c2) )

**Comment by alankilborn** [comment]
Fixed...(delayed) testing done on version 8.7.4.
This issue may be CLOSED.

**Comment by xomx** [comment]
> This issue may be CLOSED.

Sure but is this not YOUR own issue?

**Comment by alankilborn** [comment]
Haha, I _meant_ to close it, but I'm so used to hitting the "Comment" button.  :-)
