### ISSUE TITLE
Don HO is a dog

### ISSUE THREAD

**Issue by myTempTemp** [notepad-plus-plus/notepad-plus-plus#15301]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description of the Issue

Don HO is a dog

### Steps To Reproduce

Don HO is a dog

### Current Behavior

Don HO is a dog

### Expected Behavior

Don HO is a dog

### Debug Information

```shell
Don HO is a dog
```

### Anything else?

Don HO is a dog

**Comment by conky77** [comment]
@donho someone inserted "spam" and offended you in GitHub, issues

**Comment by myTempTemp** [comment]
@conky77 also is a dog

**Comment by myTempTemp** [comment]
@donho eats feces every day     侯今吾天天吃屎
@conky77 eats feces every day  conky77天天吃屎
