### ISSUE TITLE
Feature Request: folder as workspace: ignore files using wildcards manually

### ISSUE THREAD

**Issue by gdh1995** [notepad-plus-plus/notepad-plus-plus#1530]
I've noticed that Notepad++ has ignored `.git` folder, but this is far less than actual needs.

For example, `*.pyc` should be hidden, and in my workspace `.idea` and `.venv` are also not needed.

I want to be able to:
- On a file/folder's context menu, click a menu item to hide it manually
- Edit a multi-line setting file to decide what files should be hidden
  (just like `.gitignore` but it should use another filename)

**Comment by pquiring** [comment]
I want something like this.  Maybe not a file, but just somewhere in NotePad++'s config you specify extensions of files you don't want listed (*.o *.a *.dll etc).  I just want source files listed.

**Comment by charleshb** [comment]
I do agree! I do **not** want Notepad++ to display DLLs in the listing for Folder As Workspace. If the list of extensions is configurable, that should be great! 
I tried to use the option under Settings -> Preferences -> MISC. -> "Workspace file ext.:". I put this "txt,config,log,xml,js" in that field, but it doesn't seem to have any effect.
Any ideas?

**Comment by CircuitSerialKiller** [comment]
I'd like to see a file filter option too!

**Comment by matthewparkes** [comment]
+1 I would like to hide *.pyc files.

**Comment by iccor56** [comment]
i would really appreciate if you could filter out files too. a list of binary files you don't want to see/open would clean up the workspace alot
