### ISSUE TITLE
Find in Files Progress Bar Window Position

### ISSUE THREAD

**Issue by kawinga** [notepad-plus-plus/notepad-plus-plus#1531]
If Notepad++ is opend on the NOT PRIMARY Screen on a Dual-Monitor-System (Windows 7 64bit), the "Find in Files"-Progress-Bar is not shown where its supposed to be shown.

Supposed is the same position as if Notepad++ is opend on the primary Screen.

Actually it appears somewhere at the border on the primary Screen.

This bug is seen on multiple systems, i am pretty sure its general, independent of any plugins.

If you need any more information, please respond, i will provide as fast as possible.

![findinfiles_primary](https://cloud.githubusercontent.com/assets/5804986/13244756/0c1c7a38-da09-11e5-8871-c0df06eb09b1.png)
![findinfiles_secondary](https://cloud.githubusercontent.com/assets/5804986/13244755/0c1aa7ee-da09-11e5-91f4-510cb07e4073.png)

**Comment by pnedev** [comment]
Hi @kawinga ,

What is your Notepad++ version?

BR,
Pavel

**Comment by kawinga** [comment]
Hi Pavel,

it's the actual version, 6.9.
![nppv](https://cloud.githubusercontent.com/assets/5804986/13319748/3849a38a-dbc4-11e5-9e94-f5ce85baf8fa.png)

KR, Robert

**Comment by pnedev** [comment]
Hi again Robert,

I don't have multi-monitor setup so unfortunately I cannot test my fix.
Could you do that for me?

Here is a
[notepad++.zip](https://github.com/notepad-plus-plus/notepad-plus-plus/files/147490/notepad.zip)
containing the Notepad++ v6.9 executable with the fix.
Just overwrite your notepad++.exe wth this one in your Notepad++ install path (be sure to save a copy of your original exe so you can recover it later if there is a need).

Could you test it with Notepad++ window positioned on the first monitor and then on the next to see if things are OK in both cases?

Then write back, thanks.

BR,
Pavel

**Comment by kawinga** [comment]
Hallo Pavel,

the Progress-Bar is now allways in the center of its owner (the find in files-dialog).

It works as expected :+1: 

Thank you!

Kind regards,

Robert

**Comment by pnedev** [comment]
Hi Robert,

I submitted the patch officially - [#1549](https://github.com/notepad-plus-plus/notepad-plus-plus/pull/1549),
Thanks for reporting and testing.

BR,
Pavel
