### ISSUE TITLE
NOTEPAD++ v8.6.8 Crashed and throwing exception when launching on Windows Core Server 2022

### ISSUE THREAD

**Issue by Pmalhotra2024** [notepad-plus-plus/notepad-plus-plus#15313]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description of the Issue

NOTEPAD++ v8.6.8 crashing and throwing exception on Windows Core Server 2022

Getting error: 
 Exception on WM_CREATE iconList::addicon : Loadicon() function return null

### Steps To Reproduce

1.  Install latest Notepad++ version 8.6.8 x64 on Windows Core 2022 server.
2.  Try to launch Notepad++ application. It crashed.
3.  Dialog box pops up with exception: iconList::addicon : Loadicon() function return null

### Current Behavior

On launching Notepad++ v8.6.8 on Windows Core 2022, it is crashing.
Throwing exception- 
iconList::addicon : Loadicon() function return null

### Expected Behavior

Notepad++ should be launched.

### Debug Information

```shell
Not able to launch Notepad++ after upgrading to v8.6.8 on Windows CORE 2022 Servers.
```

### Anything else?

![Notepad++ErrorOnCORE](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/173039485/0ec7ba2b-ebc8-451b-9a86-e5d569950f32)

**Comment by rkwk** [comment]
Same on Windows 7.

**Comment by xomx** [comment]
https://github.com/notepad-plus-plus/notepad-plus-plus/blob/57a89b257a769ea93405b5b34bcb2660e61db857/PowerEditor/src/WinControls/ImageListSet/ImageListSet.cpp#L49-L52

@ozone10 
Looks like we should offer also some alternative way. (problem is probably the COMMCTRL lib [LoadIconWithScaleDown](https://learn.microsoft.com/en-us/windows/win32/api/commctrl/nf-commctrl-loadiconwithscaledown), it should be supported from the WinVista+ / WinSever2008+ but apparently there could be a problem with it)

**Comment by donho** [comment]
***Minimum supported server | Windows Server 2008 [desktop apps only]***
If server 2008 is supported by `LoadIconWithScaleDown`, I wonder how & why server 2022 is not.
But here is Windows **Core** Server 2022, so it could be the different between "Windows Server" and "Windows Server Core".

Anyone here who has Window Server experience are welcome to provide his/her opinion.

**Comment by donho** [comment]
> Same on Windows 7.

OTOH, [LoadIconWithScaleDown](https://learn.microsoft.com/en-us/windows/win32/api/commctrl/nf-commctrl-loadiconwithscaledown) SOULD work on Windows 7. It might be an isolated case IMO.

**Comment by Pmalhotra2024** [comment]
Windows Server 2022 Core is a windows server without Desktop Experience feature.
It only provides PowerShell Terminal to run and launch apps from command line.
Notepad++ version 8.6.7 is working fine with Core machines. Only new update is crashing.

**Comment by donho** [comment]
@Pmalhotra2024 
Thank you for the information.
Does only Windows 2022 Server come with "Sever Core" version?  

@ozone10 
I guess we need to distinguish Windows Server 2022 Core (and other previous versions) from the other Windows, for `DPIManagerV2::loadIcon()`.

**Comment by xomx** [comment]
@donho 
> let me know if v8.6.8 works under your Win7

![npp-Win7-v868portable-x64](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/13075183/41b4f655-e4ba-4bd4-ba49-e4489244c569)

@rkwk 
You could try to update/reinstall your installation of the MS Common Controls (COMCTL32) library on your Win7.

**Comment by Pmalhotra2024** [comment]
> @Pmalhotra2024 Thank you for the information. Does only Windows 2022 Server come with "Sever Core" version?
> 
> @ozone10 I guess we need to distinguish Windows Server 2022 Core (and other previous versions) from the other Windows, for `DPIManagerV2::loadIcon()`.



> @Pmalhotra2024 Thank you for the information. Does only Windows 2022 Server come with "Sever Core" version?
> 
> @ozone10 I guess we need to distinguish Windows Server 2022 Core (and other previous versions) from the other Windows, for `DPIManagerV2::loadIcon()`.



> @Pmalhotra2024 Thank you for the information. Does only Windows 2022 Server come with "Sever Core" version?
> 
> @ozone10 I guess we need to distinguish Windows Server 2022 Core (and other previous versions) from the other Windows, for `DPIManagerV2::loadIcon()`.

Windows Core editions are available since Windows Server 2016 was launched
Windows_Server-2016-English-Core
Windows_Server-2019-English-Core
Windows_Server-2022-English-Core

**Comment by donho** [comment]
@Pmalhotra2024 
Could you check the PR #15314 and confirm me if crash has been fixed?

**Comment by Pmalhotra2024** [comment]
Unfortunately it is still crashing with same error.

![image](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/173039485/3705888f-39a7-4745-8c06-3a9b44041f6c)

**Comment by donho** [comment]
@Pmalhotra2024
Please try the PR  #15315

**Comment by donho** [comment]
@Pmalhotra2024 
In case that https://github.com/notepad-plus-plus/notepad-plus-plus/pull/15315 doesn't work to you, could you try https://github.com/notepad-plus-plus/notepad-plus-plus/pull/15316 ?
It contains debug info for letting us understand why the crash happen.

**Comment by ozone10** [comment]
@xomx @donho 
thanks to #15465
one possible cause of not loading ico with png is missing/not loaded/corrupted `IconCodecService.dll` 
in `C:\Windows\SysWOW64` and in `C:\Windows\System32`

![image](https://github.com/user-attachments/assets/7f5d4f61-bf14-4f90-a88b-519442eaba79)

**Comment by xomx** [comment]
@ozone10 
I'd like try to play with this in my testing WinCoreServer VM when I find a time.
Maybe that service is there but not set to run automatically.

**Comment by donho** [comment]
@rs262 
Can you reproduce it if you restart your Windows 10 ?

**Comment by rs262** [comment]
yes, even after a restart I get the 
![image](https://github.com/user-attachments/assets/70d3090b-cf9f-41c0-9c68-0775022a212f)
error.

**Comment by donho** [comment]
@rs262 
In which directory you find your "IconCodecService.dll"? And what's your debug Info of your Notepad++?

**Comment by donho** [comment]
@ozone10 @xomx 
> thanks to https://github.com/notepad-plus-plus/notepad-plus-plus/issues/15465
one possible cause of not loading ico with png is missing/not loaded/corrupted IconCodecService.dll
in C:\Windows\SysWOW64 and in C:\Windows\System32

I confirm.
I Copied "IconCodecService.dll" from my Windows 11 to C:\Windows\System32\ of my Windows Server Core 2022, then I restarted the windows server. 
Relaunch Notepad++ v8.6.9 and no more IconList::addIcon() warning dialog.

However, I don't understand "not loaded" part. For me it's Notepad++ load this dll while the concerning function is called.
Am I missing somethings?

**Comment by ozone10** [comment]
@donho 
there might be some misconfiguration e.g. in registry which will block loading it.

Checking if icons are not blank when using large or extra large icons in explorer could tell us if there is issue with `IconCodecService.dll`
![image](https://github.com/user-attachments/assets/11b6d6f4-de1c-4c96-9e25-4764810d4e3f)

**Comment by atrenton** [comment]
Adding the IconCodecService.dll from Windows 11 to WinPE C:\Windows\System32\ folder built with December 2024 ADK resolved this issue for me.
