### ISSUE TITLE
Download pop-under obscures what to do next, causes misclicks

### ISSUE THREAD

**Issue by davehodls** [notepad-plus-plus/notepad-plus-plus#15311]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description of the Issue

When I open Notepad++ and get the update prompt, the Download box that shows up will complete but not close before the Update Yes/No box appears (which appears underneath for no discernable reason, looking like it's inaccessible like most Windows pop-unders):

![image](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/34919864/293fafda-0cbe-4802-b4d9-db3500329689)

I have to click the underlying box (that just shows Yes or No) to continue, or click Cancel on the Download box (which seems like it'll cancel the update).

![image](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/34919864/82ae3da4-2e7e-489e-be44-f2f040f22b1c)

This kind of behavior is counter-intuitive to how Windows works, and Windows is known for sometimes showing inaccessible pop-unders, so Notepad++'s behavior here just adds to messy UX.

While I've goofed this up once or twice in the past, I've seen other people do the same thing, and prevent the update inadvertantly.

The solution seems to be to close the Download box when it's done.

### Describe the solution you'd like.

Close the Download box when it's complete, before the update Yes/No box appears.

### Debug Information

```shell
I don't know what to put here, I'm just typing to get the Submit button to show. The issue has existed on every version of Notepad++ I've had for years, I'm just now deciding to try to correct the behavior.
```

**Comment by xomx** [comment]
Already fixed, will be in the next N++ release (probably v8.6.9):
https://github.com/notepad-plus-plus/wingup/commit/237176fe349882048075a65e0ca8ab6372dcf230
