### ISSUE TITLE
[Feature request] Auto-hide or Show-on-hover close buttons on each tab (Visual/UI feature)

### ISSUE THREAD

**Issue by scapehips** [notepad-plus-plus/notepad-plus-plus#15328]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description of the Issue

This is a UI/visual feature request. Currently, the close buttons for all tabs are displayed when the option "Show close button on each tab" is ticked. This makes the UI appear cluttered.

![Screenshot 2024-06-20 124900](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/50423845/c1f1c2b4-8eaa-4791-a846-013531bd166d)

### Describe the solution you'd like.

Instead, the close buttons on tabs should only appear when the mouse hovers over them and disappear when the mouse moves away, i.e., implement a "Auto-hide close button on each tab" or "Show close button on each tab on hover" option.

### Debug Information

```shell
Notepad++ v8.6.8   (64-bit)
Build time : Jun  4 2024 - 00:30:00
Path : C:\Portables\Notepad++\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : ON
Cloud Config : OFF
Periodic Backup : ON
OS Name : Windows 11 Home Single Language (64-bit)
OS Version : 23H2
OS Build : 22631.3737
Current ANSI codepage : 1252
Plugins : 
    mimeTools (3.1)
    NppConverter (4.6)
    NppExport (0.4)
```

**Comment by xomx** [comment]
Duplicate of #15298 .
It is only 10 lines below this request (please do not skip the "I've searched existing issues" folks).

**Comment by scapehips** [comment]
oops yeah i missed it
