### ISSUE TITLE
[BUG] Notepad++ can't display most characters at the Unicode block "Number Forms"

### ISSUE THREAD

**Issue by artsyhugh** [notepad-plus-plus/notepad-plus-plus#15338]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description of the Issue

Notepad++ can't display most characters at the Unicode block "Number Forms." They all show up as a fallback glyph (a rectangle for example), despite the fact that most characters (that I've known of, including CJK characters) display correctly. This is the case for the main text working area, but also for the Find All in Current Document/All Opened Documents results. These characters do display correctly in input fields (such as those of the Find dialog).

### Steps To Reproduce

1.  Paste characters at the block [Number Forms](https://en.wikipedia.org/wiki/Number_Forms#Block) into Notepad++.
![image](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/36994943/c05d0cb0-39f3-4631-90ef-47ee1d8ac1c5)
![image](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/36994943/08be4448-d66d-4c27-8114-a45c8f7967f6)

### Current Behavior

Characters at the block "Number Forms" display as a fallback glyph (a rectangle, for example).

### Expected Behavior

They should display correctly like all other characters.

### Debug Information

```shell
Notepad++ v8.6.8   (64-bit)
Build time : Jun  4 2024 - 00:30:00
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
Periodic Backup : ON
OS Name : Windows 11 Home Single Language (64-bit)
OS Version : 23H2
OS Build : 22631.3737
Current ANSI codepage : 65001
Plugins : 
    ComparePlugin (2.0.2)
    mimeTools (3.1)
    NppConverter (4.6)
    NppExport (0.4)
    NppTextFX (1.4.1)
```

**Comment by xomx** [comment]
![npp-DirectWrite](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/13075183/bbd99a7f-ea42-4a4e-9c46-cb454eb5d3de)
