### ISSUE TITLE
[Editor.cxx:1866]: (error) Array 's[1]' accessed at index 1, which is out of bounds.

### ISSUE THREAD

**Issue by usta** [notepad-plus-plus/notepad-plus-plus#1533]
in notepad-plus-plus-master\scintilla\src\Editor.cxx

	if (treatAsDBCS) {
		NotifyChar((static_cast<unsigned char>(s[0]) << 8) |
		        static_cast<unsigned char>(s[1]));
on the other hand cppcheck gives that s[1] is outofbounds. Is this a falsepossitive ?
[Editor.cxx:1866]: (error) Array 's[1]' accessed at index 1, which is out of bounds.

**Comment by dail8859** [comment]
> Is this a falsepossitive ?

I'd assume if you are running cppcheck then you have enough knowledge to determine if that could be a false positive or not. :smile: 

Also, Editor.cxx is part of [Scintilla](https://sourceforge.net/projects/scintilla/). They seem to be using CppCheck themselves so I'd guess either they know about it or you can report it to them.

**Comment by usta** [comment]
:) cppcheck is a static analyser so it couldn't guess  the size of dynamic allocated arrays.
Thats the why i asked if this is a false possitive or not :)
So i will open a ticket in Scintilla . Thanks

**Comment by usta** [comment]
Reported to upstream : https://sourceforge.net/p/scintilla/bugs/1812/
I'm closing issue in here
