### ISSUE TITLE
Styling of line feeds

### ISSUE THREAD

**Issue by WarrantyVoid** [notepad-plus-plus/notepad-plus-plus#1535]
In global styles, Notepad++ allows setting of different styles for white space symbols as "tab" and "space". I always find it irritating, that the "line feed" / "carriage return" symbols instead use the same style as regular text. Have them either use white space style or introduce a new one. I wonder why nobody has posted it yet, the effort should be minimal..

**Comment by dail8859** [comment]
It has been reported and discussed :) #1260

**Comment by WarrantyVoid** [comment]
Ah, thanks dail8859, seems like I have been looking for the wrong keywords. But this means, as summary of the discussion, one could say:
"It's a Scintilla issue and they won't bother to fix it.." which is not satisfying at all..

**Comment by WarrantyVoid** [comment]
Closed as duplicate.
