### ISSUE TITLE
[BUG] Convert to ANSI | UTF-8

### ISSUE THREAD

**Issue by mtlrdvr** [notepad-plus-plus/notepad-plus-plus#15356]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description of the Issue

The functions "Convert to" of "Encoding" menu fail

### Steps To Reproduce

1.  File | New (default encoding is UTF-8)
2.  Write something
3.  Encoding | Convert to ANSI
4. All content has been deleted
5. ... or ...
6. File | New (default encoding is UTF-8)
7. Encoding | ANSI
8. Write something
9. Encoding | Convert to UTF-*
10. All content has been deleted
11. ... or ...
12. File | Open a UTF-* encoded file
13. Failed same way when converting to ANSI encoding
14. ... or ...
15. File | Open a ANSI encoded file
16. Failed in the same way when converting to UTF-* encoding

In all cases "undo" isn't available.

### Current Behavior

This happens in version 8.6.8.
Perhaps it should be tried after putting the computer in "sleep" mode, or after rebooting the computer.
I use this feature all the time, so I had to go back to the previous version.

### Expected Behavior

It should work smoothly as in version 8.6.7.

### Debug Information

```shell
Notepad++ v8.6.8   (64-bit)
Build time : Jun  4 2024 - 00:30:00
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
Periodic Backup : ON
OS Name : Windows 7 Professional (64-bit)
OS Build : 7601.24511
Current ANSI codepage : 1252
Plugins : 
    ComparePlugin (2.0.2)
    HexEditor (0.9.12)
    JsonTools (4.10)
    mimeTools (3.1)
    NppConverter (4.6)
    nppcrypt (1.0.1.6)
    NppExport (0.4)
    NPPJSONViewer (2.0.4)

-/-

Notepad++ v8.6.8   (64-bit)
Build time : Jun  4 2024 - 00:30:00
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
Periodic Backup : ON
OS Name : Windows 10 Home (64-bit)
OS Version : 22H2
OS Build : 19045.4529
Current ANSI codepage : 1252
Plugins : 
    ComparePlus (1.1)
    mimeTools (3.1)
    NppConverter (4.6)
    nppcrypt (1.0.1.6)
    NppExport (0.4)
```

**Comment by SupportRainbow** [comment]
@xomx Hey Xomx,

Sorry I haven't replied about this until just now, I see you fixed the issue which is great but, I'm not the best with Notepad ++ and just submitted this for my DP team but, how exactly do I go about applying this fix to the problem machines running into this issue, any help would be greatly appreciated and great job and founding out the issue, that's some magic!

**Comment by melopeter** [comment]
I eagerly await version 8.6.9
Thanks,

**Comment by chcg** [comment]
Fixed with https://github.com/notepad-plus-plus/notepad-plus-plus/releases/tag/v8.6.9
