### ISSUE TITLE
Please move Notepad++ to a non-GPL license.  Richard Stallman is extremely repulsive.

### ISSUE THREAD

**Issue by GeneGeneGitHub** [notepad-plus-plus/notepad-plus-plus#15358]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description of the Issue

Here are a few quotes from his own website:
-----------------------------------------------------------------------------------
[believes eg child porn videos shouldn't be removed from the Internet]

"When making pornography involves real abuse of real children, those who
distribute it under a business relationship with the abusers arguably
participate in the abuse. They could be prosecuted for doing so.
However, that does not excuse censorship. No matter how disgusting
published works might be, censorship is more disgusting."
https://stallman.org/archives/2011-jan-apr.html

-----------------------------------------------------------------------------------
[doubts children are harmed by pedophilic abuse]

"necrophilia, bestiality, possession of child pornography, and even
incest and pedophilia... should be legal as long as no one is coerced.
They are illegal only because of prejudice and narrowmindedness."
https://stallman.org/archives/2003-may-aug.html

-----------------------------------------------------------------------------------
[believes high schools should employ sex teachers to fsck kids all day long]

Every secondary school should aim for all of its graduates to be fully
capable in sexuality; none should be excluded from participation in sex
due to lack of proper experience. Therefore, the school should have
several sex teachers, adults with whom students can learn to be
comfortable with sex and confident in pleasing their lovers. They would
also learn good habits for avoidance of disease and pregnancy.

https://stallman.org/archives/2014-sep-dec.html#14_November_2014_%28Teacher_prosecuted_for_sex_with_student%29

### Describe the solution you'd like.

any license you like, as long as it's not GPL.

I like public domain or BSD.

### Debug Information

```shell
na
```

**Comment by donho** [comment]
I have no problem with necrophilia. However,

**Comment by GeneGeneGitHub** [comment]
That's a bullshit answer.  Stallman is a disgusting skeptic of the harm of pedophilia (as long as "no one is coerced").  How can a child or a corpse or an animal consent to sex?

Please release future versions of  Notepad++ under a public domain, BSD or MIT license, so everyone can use it with a clear conscience.  Thanks.
