### ISSUE TITLE
[Feature request] Confirm before closing multiple tabs on exit

### ISSUE THREAD

**Issue by student13371** [notepad-plus-plus/notepad-plus-plus#15362]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description of the Issue

I work with multiple Tabs opened in Notepad++. 

Sometimes when I want to close just 1 tab, I accidentally click the X button in the very top right corner.
This immediately closes Notepad++ and all opened tabs without any warning or prompt.

I suggest an option to 'Confirm before closing multiple tabs on exiting / closing Notepad++'.

This feature has been suggested back in 2008:
https://sourceforge.net/p/notepad-plus/discussion/331754/thread/5f0370ba

### Describe the solution you'd like.

This feature doesn't have to be active by default, but it could be activated in Notepad++ Preferences > MISC section.

This is how the prompt could look like:

![confirm before closing multiple tabs](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/12573989/d1bc3b7f-642f-453e-954f-3d0fc4777457)

### Debug Information

```shell
Notepad++ v8.6.7   (64-bit)
Build time : May 12 2024 - 20:04:00
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
Periodic Backup : OFF
OS Name : Windows 11 Enterprise (64-bit)
OS Version : 23H2
OS Build : 22631.3737
Current ANSI codepage : 1252
Plugins : 
    mimeTools (3.1)
    NppConverter (4.6)
    NppExport (0.4)
```

**Comment by alankilborn** [comment]
Paste a screenshot of your setup from this screen:

![image](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/77065706/45f29f1b-7ccc-4104-a1cf-799878805bc7)

**Comment by biggestdickus** [comment]
YES, YES, YES ! example: I have three file open (.html, css, .js) I save all then refresh my browser to see the changes. I don't like the changes but I mistakely click the notepad++ close button and go WTF, WTF, WTF.  I don't use 'Remember currect session..' as it clutters up my workspace.  student13371 idea is perfect..... So whomeven is in change of the next version , Implement it please.
Conclussion: option: Confirm before closing multiple tabs on exit EVEN IF ALL HAVE BEEN SAVED.
