### ISSUE TITLE
[BUG] Building Release Win32 from source causes crash on startup (probably Visual Studio version dependent)

### ISSUE THREAD

**Issue by molsonkiko** [notepad-plus-plus/notepad-plus-plus#15372]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description of the Issue

When I build Notepad++ from source (based on [this commit](https://github.com/notepad-plus-plus/notepad-plus-plus/commit/d0f57426640b1ecab9c9c5acac0855c1bb009176), two commits before the current master at the time of writing), my `Debug Win32` and `Release x64` and `Debug x64` builds work fine, even with plugins.

However, when I try to build `Release Win32`, I get a message like the following:
```
Unhandled exception at 0x76960B82 (KernelBase.dll) in notepad++.exe: 0xC000041D: An unhandled exception was encountered during a user callback.
```

If I try to run the executable outside of the Visual Studio debugger, the program exits silently. Sometimes, it seems to try to execute commands like opening the `Print` or `Open File` dialog, or open up a web browser.

I thought perhaps this was happening because of some problematic files in the `bin` folder that this binary is output to, but *even if I delete the entire `bin` folder* and let it be regenerated by the build process, this error persists. It's also not related to the `doLocalConf.xml` file, because the crash happens even if I delete that file. It doesn't matter whether I have plugins enabled.

---

My current best theory is that this is all happening because I'm using a newer version of Visual Studio than the version `17.5` recommended in [the build guide](/https://github.com/notepad-plus-plus/notepad-plus-plus/blob/master/BUILD.md). If that's the case, I expect I will just give up on trying to build `Release Win32`, because I don't really feel like downgrading Visual Studio.

Below is the info about my Visual Studio installation (from `Help->About Microsoft Visual Studio->Copy Info` on the main menu).
```
Microsoft Visual Studio Community 2022
Version 17.9.7
VisualStudio.17.Release/17.9.7+34902.65
Microsoft .NET Framework
Version 4.8.09037

Installed Version: Community

Visual C++ 2022   00482-90000-00000-AA271
Microsoft Visual C++ 2022

ASP.NET and Web Tools   17.9.199.22661
ASP.NET and Web Tools

Azure App Service Tools v3.0.0   17.9.199.22661
Azure App Service Tools v3.0.0

Azure Functions and Web Jobs Tools   17.9.199.22661
Azure Functions and Web Jobs Tools

C# Tools   4.9.0-3.24121.1+a98c90d56455379836dd5c845b35fa932b00cfa3
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

Linux Core Dump Debugging   1.0.9.34714
Enables debugging of Linux core dumps.

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

NuGet Package Manager   6.9.2
NuGet Package Manager in Visual Studio. For more information about NuGet, visit https://docs.nuget.org/

Razor (ASP.NET Core)   17.9.2.2412004+684740676513b3b208d5bd5b7f8786dab8d287b7
Provides languages services for ASP.NET Core Razor.

SQL Server Data Tools   17.9.56.1
Microsoft SQL Server Data Tools

TypeScript Tools   17.0.30103.2001
TypeScript Tools for Microsoft Visual Studio

Viasfora   4.4.212
Add color to your Visual Studio editor!

Visual Basic Tools   4.9.0-3.24121.1+a98c90d56455379836dd5c845b35fa932b00cfa3
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual C++ for Linux Development   1.0.9.34714
Visual C++ for Linux Development

Visual F# Tools   17.9.0-beta.23614.3+a521e1cd420beb56c15faf6836184fadd2b7937a
Microsoft Visual F# Tools

Visual Studio IntelliCode   2.2
AI-assisted development for Visual Studio.
```

### Steps To Reproduce

See above

### Current Behavior

See above

### Expected Behavior

Not crashing on startup

### Debug Information

```shell
Can't show you debug info because it crashes on startup
```

**Comment by molsonkiko** [comment]
At this point it's pretty obvious that this bug is caused by using too new of a version of Visual Studio. I haven't closed this issue yet because what happened here is much worse than just failing to compile. If the code had simply refused to compile, I might not have bothered posting this issue, because it doesn't result in a malformed executable that behaves unpredictably.

**Comment by ozone10** [comment]
@molsonkiko 
I am using newer version 17.10.3 without issue. Github actions is also using newer version.

**Comment by molsonkiko** [comment]
I stopped having this issue a while ago. Just remembering to close the issue now.
