### ISSUE TITLE
Close all window size varies depending on the file status...

### ISSUE THREAD

**Issue by harerama** [notepad-plus-plus/notepad-plus-plus#1537]
I often have a lot of files open at once - and when I select to close multiple files (close all, close all but this...), the close dialog depends on the file status (new file never saved, modified file, ...) and the buttons are not at the same position for each file.
This is very annoying, since when doing the action fast, I often click on the wrong button...
It also makes closing several unsaved files difficult, since I would expect to always click on the same button to close files - but the close button itself moves ... 
I think the best solution would decide on the dialog size based on the largest one, and position buttons in a consistent manner across all dialogs for that "mass closing" session.

This is really the only annoyance about this amazing piece of software you have built - thanks for everything.

**Comment by MetaChuh** [comment]
please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins if you update from version 7.5.9 or below.
if your issue still persists, and it is still of relevance to you, please feel free to file a new issue as easy to understand and reproducible as possible.

thank you for your support and best regards.

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
(no extra account is needed, just use your github account to sign in)
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)

**Comment by sasumner** [comment]
Hint: Don't use the mouse and you won't have to search for a button that has changed location.  Use the keyboard, Y or N.
