### ISSUE TITLE
Find always defaults to focused word

### ISSUE THREAD

**Issue by msmigiel** [notepad-plus-plus/notepad-plus-plus#1538]
When I press CTRL+F to find text in a text file, the word to find is defaulted to the focused word in the text file (whether or not it is highlighted, just where the cursor is). While this can be useful in some instances, personally I would like the option to have it default to the last used search. My use case is that I often am trying to find the same string in a text file and if I stop searching and move my cursor, the word I am looking for is lost. Other text editors (EditPlus, even Windows Notepad) work like this. Please consider implementing this as an option.

**Comment by MetaChuh** [comment]
please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins if you update from version 7.5.9 or below.
if your issue still persists, and it is still of relevance to you, please feel free to file a new issue as easy to understand and reproducible as possible.

thank you for your support and best regards.

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
(no extra account is needed, just use your github account to sign in)
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)

**Comment by sasumner** [comment]
Perhaps some (unwelcome?) advice:

Don't press ctrl+f.  Simply use Find Next or Find Previous.

OR

Don't press ctrl+f.  Leave the find window open after a search.  Then use the mouse to switch to it.  Your last search term will not change.

OR

Press ctrl+f but first have your caret somewhere that isn't touching a "word", e.g. in some whitespace or on an empty line.  The previously used search term won't be changed.

**Comment by donho** [comment]
Done in commit `Make filling find field of Find dialog with selected word(s) optional`:
https://github.com/notepad-plus-plus/notepad-plus-plus/commit/7a1096de5b3618bc3e6611e6c25caac952d41ae2

It will come with v7.8.3
