### ISSUE TITLE
Use Optimize Flag in regex

### ISSUE THREAD

**Issue by miywm** [notepad-plus-plus/notepad-plus-plus#15391]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description of the Issue

I don't see the flag `regex_constants::optimise` in the source code, and I think that normally the regex in npp is slowly (for large files).
So I think it should be added.

### Describe the solution you'd like.

Add this flag, and I hope the speed will increase.

### Debug Information

```shell
Notepad++ v8.6.8   (64-bit)
Build time : Jun  4 2024 - 00:30:00
Path : E:\Notepad++\notepad++.exe
Command Line : "E:\Notepad++\change.log" 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
Periodic Backup : ON
OS Name : Windows 11 Pro (64-bit)
OS Version : 23H2
OS Build : 22631.3737
Current ANSI codepage : 936
Plugins : 
    mimeTools (3.1)
    NppConverter (4.6)
    NppExport (0.4)
```

### Anything else?

[I read this](https://github.com/notepad-plus-plus/notepad-plus-plus/blob/master/boostregex/BoostRegExSearch.cxx) (source code)

**Comment by mpheath** [comment]
I doubt zero will have any affect with an increase in speed:

https://github.com/notepad-plus-plus/notepad-plus-plus/blob/5501485c0bce1f5f8e3402374d96e5b830ef413e/boostregex/boost/regex/v5/regbase.hpp#L78

Another zero for a deprecated flag:

https://github.com/notepad-plus-plus/notepad-plus-plus/blob/5501485c0bce1f5f8e3402374d96e5b830ef413e/boostregex/boost/regex/v5/regbase.hpp#L73

These flags with a value of zero seem to exist to be compatible:

https://github.com/notepad-plus-plus/notepad-plus-plus/blob/5501485c0bce1f5f8e3402374d96e5b830ef413e/boostregex/boost/regex/v5/regbase.hpp#L111
