### ISSUE TITLE
[Feature request] <Mac OS Support>

### ISSUE THREAD

**Issue by GvHarish9894** [notepad-plus-plus/notepad-plus-plus#15399]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description of the Issue

Need Mac os supported application

### Describe the solution you'd like.

Provide app that support macos

### Debug Information

```shell
This is feature so no debug information
```

**Comment by alankilborn** [comment]
Please see [HERE](https://github.com/notepad-plus-plus/notepad-plus-plus/wiki/FAQ#support-for-systems-other-than-the-ms-windows-family).
And the close this issue.

**Comment by GvHarish9894** [comment]
Okay
