### ISSUE TITLE
Windows 7 32-bit Notepad++ 8.6.8 Exception On WM_CREATE

### ISSUE THREAD

**Issue by Gerundive** [notepad-plus-plus/notepad-plus-plus#15406]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description of the Issue

Windows 7 32-bit Notepad++ 8.6.8 Exception On WM_CREATE
![npp 8 6 8_Bug](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/174816122/d7202b13-655a-4f40-b788-a9b6fbf6d21b)

### Steps To Reproduce

1.  
2.  
3.  
On running the newest version of NotePad++ (8.6.8) The message Exception On WM_Create occurs
Windows 7 32-bit

### Current Behavior

Crash

### Expected Behavior

The product to work as well as it does on versions 8.6.7 and earlier

### Debug Information

```shell
Cannot do this as version crashes before the menu appears
This is all I can obtain from 8.6.6:
Notepad++ v8.6.6   (32-bit)
Build time : May  6 2024 - 21:55:48
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : 
Admin mode : ON
Local Conf mode : OFF
Cloud Config : OFF
Periodic Backup : OFF
OS Name : Windows 7 Professional (32-bit)
OS Build : 7601.24535
Current ANSI codepage : 1252
Plugins : 
    mimeTools (3.1)
    NppConverter (4.6)
    NppExport (0.4)
    NppTextFX (0.2.6)
    XMLTools (3.1.1.5)
```

### Anything else?

![npp 8 6 8_Bug](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/174816122/1af756e0-9fa7-4112-8ba3-fca5c3a1cac8)

**Comment by xomx** [comment]
This has been already reported https://github.com/notepad-plus-plus/notepad-plus-plus/issues/15313#issuecomment-2173538278 but I could not reproduce https://github.com/notepad-plus-plus/notepad-plus-plus/issues/15313#issuecomment-2173752730.

But it should be also fixed by the https://github.com/notepad-plus-plus/notepad-plus-plus/commit/46c5a0c226b3fd42ec2ae883cad3d5b3704933f7 .

**Comment by donho** [comment]
@Gerundive 
Could you try v8.6.9 RC here:
https://community.notepad-plus-plus.org/topic/25918/notepad-v8-6-9-release-candidate
and confirm that the issue has been fixed?
