### ISSUE TITLE
[BUG] Vertical scrollbar not docked to right side. Doubleclicking near the right margin opens new document instead of scrolling.

### ISSUE THREAD

**Issue by daddynino** [notepad-plus-plus/notepad-plus-plus#15402]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description of the Issue

Vertical scrollbar doesn't appear to be docked to the right side of the window, there's padding of 3-4 pixels between the scrollbar and the edge of the window. Moving the mouse to the far right, and doubleclicking should move the scrollbar up/down a page, but instead it opens a new document tab. This means that to use the scrollbar, I have to visually confirm that the mouse cursor is precisely within the confines of the scrollbar before clicking.

### Steps To Reproduce

1.  Open or create a document that is more than a page long, thus needing scrollbars
2.  Move mouse to right edge of the window
3.  Double-click to get a new document tab

### Current Behavior

New document tab opens when attempting to double-click on the vertical scrollbar near the right border. This occurs both when the app is windowed mode and maximized to full screen. Also happens if there's no scrollbar, if that's relevant.

### Expected Behavior

Document should scroll up or down a page based on where in the scrollbar I double-clicked

### Debug Information

```shell
Notepad++ v8.6.8   (32-bit)
Build time : Jun  4 2024 - 00:29:00
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Command Line : "Z:\Repos\CodeSnippets\StartUp.vb" 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
Periodic Backup : OFF
OS Name : Windows 10 Enterprise (64-bit)
OS Version : 22H2
OS Build : 19045.4598
Current ANSI codepage : 1252
Plugins : 
    mimeTools (3.1)
    NppConverter (4.6)
    NppExport (0.4)
```

**Comment by alankilborn** [comment]
Try adjusting these settings:

![image](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/77065706/449fae1a-78a2-4e4f-8101-30aacb561b43)

**Comment by daddynino** [comment]
That resolved the issue. Thank you.
