### ISSUE TITLE
folder as workspace : file - open folder as workspace

### ISSUE THREAD

**Issue by bcag2** [notepad-plus-plus/notepad-plus-plus#1542]
It is not intuitive to go to view menu to find "folder as workspace" even if it is an added windows. I first try to find in file menu to open ! It is not opposed. If you add a open folder as workspace in file menu, it can activate view menu-folder as workspace option.

Regards

bcag2

**Comment by bcag2** [comment]
Thank you!

**Comment by donho** [comment]
Done in v6.9.2
