### ISSUE TITLE
[BUG] Closing tabs does not move focus in expected order

### ISSUE THREAD

**Issue by jaybeedk** [notepad-plus-plus/notepad-plus-plus#15428]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description of the Issue

If you open / create many files and then start closing them again with hotkey (e.g. CTRL+W), then you expect "tab focus" to move in a certain and predictive way:
- opening / creating a file will always move tab focus to the new file
- closing a file will always move tab focus to the previous file

Indeed, if you open multiple files one file at a time and then start closing them, focus follows LIFO order.
However, if you already have files open and then open several more files in one go (e.g. select several files and drag them all into Notepad++ in one go), then closing files will no longer follow LIFO order.

LIFO is simple to understand, especially in the trivial case, it may not be the best choice IRL.
Perhaps you could consider the behavior that browsers seem to have agreed upon, "close and move focus to the right if possible, otherwise to the left" (this will even be LIFO in the trivial case)

### Steps To Reproduce

1. Open 3 new tabs (3x CTRL+N) and observe how focus moves to the new appended tab as expected
2. Close 3 tabs (3x CTRL+W) and observe how each time focus moves to the file on the left as expected
3. Open 3 new tabs again and then drag 3 additional text files into Notepad++ in one go (NOT one file at a time)
4. Observe how all tabs are in expected order (3 new tabs followed by the 3 files) and the last opened file tab has focus
5. Close the last tab (CTRL+W) and observe how the last file tab is closed successfully
6. BUG: focus goes to the last "new" tab where the expectation is the second-to-last opened text file
7. Use the mouse to select one of the remaining 2 files and close the tab (CTRL+W)
8. BUG: the focus again goes to the last "new" tab instead of the last text file
9. OBSERVATION: you see expected behavior if you drag the extra text files into Notepad++ one at a time instead of all 3 in a "bundle"
10. OBSERVATION: it does not matter if you use File / Open (CTRL+O) or drag-and-drop - one file at a time works as expected, multiple files in one go does not

### Current Behavior

Opening multiple files (one file at a time) then closing them with hotkey will move the tab focus as expected.
Having any number of files open beforehand, then opening multiple files in one go will NOT follow expected behavor when closing files

### Expected Behavior

The tab behavior that browsers have made ubiquitous, "close and move tab focus to the right if possible, otherwise to the left"

### Debug Information

```shell
Notepad++ v8.6.8   (64-bit)
Build time : Jun  4 2024 - 00:30:00
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
Periodic Backup : ON
OS Name : Windows 10 Pro (64-bit)
OS Version : 22H2
OS Build : 19045.4651
Current ANSI codepage : 1252
Plugins : 
    JsonTools (4.4)
    mimeTools (3.1)
    NppConverter (4.6)
    NppExport (0.4)
    XMLTools (3.1.1.13)
```

**Comment by alankilborn** [comment]
Note that when this setting is checkmarked, which tab is activated upon closure of another tab is influenced:

![image](https://github.com/user-attachments/assets/f4e8a50e-f6b2-4c08-bbaf-3a1b3f751910)

**Comment by jaybeedk** [comment]
Amazing! I must have enabled it, wishing for the behavior I described.
Instead it works as described when this setting is off, thanks!!
