### ISSUE TITLE
[BUG] Expired SSL Certificate for npp-user-manual.org

### ISSUE THREAD

**Issue by CennoxX** [notepad-plus-plus/notepad-plus-plus#15437]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description of the Issue

When attempting to access [https://npp-user-manual.org](https://npp-user-manual.org), I encountered a security warning indicating that the site's SSL certificate has expired. This issue prevents users from accessing the user manual.

### Steps To Reproduce

1. Open browser.
2. Navigate to [https://npp-user-manual.org](https://npp-user-manual.org).

### Current Behavior

 I encountered a security warning

### Expected Behavior

 I see the website

### Debug Information

```shell
Windows 10
Firefox 128.0 (64-Bit)
```

**Comment by pryrt** [comment]
@donho,

I see the same thing:

![image](https://github.com/user-attachments/assets/b1e2312d-385b-4a27-936c-c4f026810c09)

![image](https://github.com/user-attachments/assets/eda47b19-590d-4924-96d1-38211829a8db)

I know with my personal website, which uses Let'sEncrypt free SSL certs, they expire every three months, and my webhost automatically renews them for me.  I don't know how you've got it set up in the background, but I have gotten the impression that you have a lot of manual configuration that you have to do for such things ... so my guess is you have a script or a prompt that's _supposed_ to renew it every 3 months for you, but it just didn't run this time, for whatever reason.

**Comment by donho** [comment]
@pryrt 
The certificate for npp-user-manual.org is an option of my host (web server service provider). So it shouldn't be down as the current situation. I will check with them ASAP for getting this fixed.

**Comment by donho** [comment]
FYI, the domain `npp-user-manual.org` has been to point to a new IP address. The propagation needs 48 hours so I have to wait a little bit.

**Comment by donho** [comment]
SSL certificate is working.
