### ISSUE TITLE
[BUG] Multi-caret mode remains after block- or column-copy

### ISSUE THREAD

**Issue by Bilbo47** [notepad-plus-plus/notepad-plus-plus#15433]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description of the Issue

Maybe related to https://github.com/notepad-plus-plus/notepad-plus-plus/issues/15242 https://github.com/notepad-plus-plus/notepad-plus-plus/issues/15241.

### Steps To Reproduce

1. Place the caret for select+Copy on line 3 col 5 
![2024-07-14 Multi-caret 1](https://github.com/user-attachments/assets/7aa9236d-e1f2-4e1b-93a2-9a5b6ee212bf)
2. Press Alt+Shift+DownArrow and Alt+Shift+RightArrow to select a rectangular block 
![2024-07-14 Multi-caret 2](https://github.com/user-attachments/assets/145435e3-6ae8-4a97-80e9-194632c54ecb)
3. Abort the Paste operation and exit block-edit mode: Press DownArrow to place the caret for editing on line 6 col 10
![2024-07-14 Multi-caret 3](https://github.com/user-attachments/assets/180db4b9-f2f8-445c-bc17-f16b70d4d76a)

### Current Behavior

Problem: NPP is still in multi-caret mode. Newly entered characters are inserted at all caret locations. [Home] or [End] do not exit multi-caret; [PageUp] or [PageDn] do yes return to normal entry.

### Expected Behavior

This is new in 8.6.1. Release notes did not alert users to new behavior. Need info how to disable multi-caret, or otherwise preserve previous behavior. SciTe 5.5.0 32bit properly exits block-edit mode upon DownArrow.

### Debug Information

```shell
Notepad++ v8.6.9   (32-bit)
Build time : Jul 12 2024 - 05:08:26
Path : d:\Path\Notepad++\notepad++.exe
Command Line : "d:\path\Notepad++ 8.6.9 Changes.TXT"
Admin mode : ON
Local Conf mode : OFF
Cloud Config : OFF
Periodic Backup : ON
OS Name : Windows 8.1 Pro N (64-bit)
OS Build : 9600.0
Current ANSI codepage : 1252
Plugins : none
```

**Comment by 0hip** [comment]
> 3. Abort the Paste operation and exit block-edit mode:

You mean "Press [ESC] to Abort the Paste operation and exit block-edit mode",  right?

**Comment by Bilbo47** [comment]
> Press [ESC] to ~~Abort the Paste operation and~~ exit block-edit mode
Okay this does yes work, thanks. But where else would this new behavior (DownArrow no longer exits block-edit) have been published? And how come NPP is different from SciTe this way?

**Comment by 0hip** [comment]
> > Press [ESC] to ~Abort the Paste operation and~ exit block-edit mode
> > Okay this does yes work, thanks. But where else would this new behavior (DownArrow no longer exits block-edit) have been published? And how come NPP is different from SciTe this way?

![image](https://github.com/user-attachments/assets/ad4b51b9-c6b2-4985-9cd4-cb5d9f8fc506)

**Comment by Bilbo47** [comment]
Settings => Preferences => Editing 2 => Un-check "Enable Column Selection to Multi-Editing"
Terrific, thank you! Now able to actually try using a current version :)

**Comment by Bilbo47** [comment]
Settings => Preferences => Editing 2 => Un-check "Enable Column Selection to Multi-Editing"
Terrific, thank you! Now able to actually try using a current version :)
