### ISSUE TITLE
Ugly Syntax Highlighting for javascript Template Strings

### ISSUE THREAD

**Issue by egoroof** [notepad-plus-plus/notepad-plus-plus#1543]
notepad 6.9 on windows 10 x64

Here is how it looks (file extension is `.js`):

![2016-02-24 20 11 55](https://cloud.githubusercontent.com/assets/2605831/13285169/2ff7e786-db34-11e5-8d8b-0540be44f34a.png)
![2016-02-24 20 12 04](https://cloud.githubusercontent.com/assets/2605831/13285170/315d64d4-db34-11e5-9df9-2e9c1a2a3001.png)

You can see that when the string is selected it's ugly highlighted and it's hard to understand what's inside. I use default settings and didn't install any other plugins.

**Comment by Slayer95** [comment]
This is actually a bad usability problem :/
