### ISSUE TITLE
folder as workspace : search in workspace files

### ISSUE THREAD

**Issue by bcag2** [notepad-plus-plus/notepad-plus-plus#1544]
I use a lot search in all open files. That require all project files was open. With folder as workspace, I hope to just open working files because all other are easy to open if needed... but seach in all open file will not search in all my project !

**Comment by donho** [comment]
"Find in files" command has been added in the context menu, and it will be in the next release:
https://github.com/notepad-plus-plus/notepad-plus-plus/commit/338b98dee85cb165e558c4b5af5311bfd19e3f1e

**Comment by bcag2** [comment]
Great! thanks

**Comment by bcag2** [comment]
I just tested it. With filter, it is very convenient... I should change my using of notepad++ to work more efficiency, thank a lot.
