### ISSUE TITLE
[BUG] huge visible tab size on the right panel

### ISSUE THREAD

**Issue by vrz** [notepad-plus-plus/notepad-plus-plus#15453]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description of the Issue

With one open .js file in two panels, when you move the cursor from the left panel to the right, the visible size of the tabulation symbols increases. this appeared on NPP versions 8.6.8 and 8.6.9

![npp err](https://github.com/user-attachments/assets/79dcefba-fb4f-4458-b952-1858fba46be6)

### Steps To Reproduce

1.  open .js file, tabulation symbols
2.  right click on its tab
3.  select menu 'Move document'
4. select menu iteme 'Clone to Other View'
5. after open file in right panel move move cursor from the left panel to the right
6. the visible size of the tabulation symbols increases

### Current Behavior

With one open .js file in two panels, when you move the cursor from the left panel to the right, the visible size of the tabulation symbols increases

### Expected Behavior

size of the tabulation symbols should be the same

### Debug Information

```shell
Notepad++ v8.6.9   (64-bit)
Build time : Jul 12 2024 - 05:09:25
Path : D:\WinApp\_dev\Notepad++.64\notepad++.exe
Command Line : "D:\Projects\.devices\.RP2040\weather monitor\weatherMonitor.js"
Admin mode : OFF
Local Conf mode : ON
Cloud Config : OFF
Periodic Backup : OFF
OS Name : Windows 10 Pro (64-bit)
OS Version : 21H2
OS Build : 19044.1526
Current ANSI codepage : 1251
Plugins : 
    ComparePlugin (2.0.2)
    ComparePlus (1.2)
    CSVLint (0.4.6.7)
    DSpellCheck (1.5)
    GitSCM (1.4.9.1)
    HexEditor (0.9.12)
    jN (2.2.185.10)
    JSMinNPP (1.2312)
    MarkdownViewerPlusPlus (0.8.2)
    mimeTools (3.1)
    NppConverter (4.6)
    nppcrypt (1.0.1.6)
    NppExec (0.8.8)
    NppExport (0.4)
    NppMarkdownPanel (0.7.3)
    PreviewHTML (1.3.2)
    PythonScript (2)
    RegexTrainer (1.2)
    SourceCookifier (0.10)
    _CustomizeToolbar (5.3)
```

**Comment by xomx** [comment]
Cannot reproduce.

Most likely a problem with a plugin (or combinations thereof). To confirm, try the same with N++ launched via "notepad++.exe -noPlugin". If that helps, follow this guide, the "Try without a specific plugin" part:
https://community.notepad-plus-plus.org/topic/23146/faq-notepad-crashes-freezes-unresponsive-after-update

**Comment by vrz** [comment]
Thanks for the tip.
Problem was with my script in plugin 'jN'.
