### ISSUE TITLE
[BUG]  "Style All Occurrences of Token"  fails on some text

### ISSUE THREAD

**Issue by abs0** [notepad-plus-plus/notepad-plus-plus#15454]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description of the Issue

Depending on the text selection "Style All Occurrences of Token" will fail on some selections which work with "Style One Token"

If the selection is created by double clicking on an element and dragging left/right (so it always starts and ends on a Notepad++ token boundary) - the styling works

### Steps To Reproduce

1.  Create a new file with the two lines below
2.  Select the text "startTimeInSeconds"
3.  Choose "Search" -> "Style All Occurrences of Token"  -> Colour - see nothing happens
4.  Choose "Search" -> "Style One Token"  -> Colour - see the style set
objects={"activityFiles":[{"startTimeInSeconds":1721256190,"activityId":34123671489,"activityType":"RUNNING"}]}
objects={"activityFiles":[{"startTimeInSeconds":1721256190,"activityId":34123671489,"activityType":"RUNNING"}]}

### Current Behavior

"Style All Occurrences of Token" will fail on some selections which work with "Style One Token"

### Expected Behavior

"Style All Occurrences of Token" styles all matching selections which work with "Style One Token"

### Debug Information

```shell
Notepad++ v8.6.9   (64-bit)
Build time : Jul 12 2024 - 05:09:25
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : 
Admin mode : ON
Local Conf mode : OFF
Cloud Config : OFF
Periodic Backup : ON
OS Name : Windows 11 Pro (64-bit)
OS Version : 23H2
OS Build : 22631.3737
Current ANSI codepage : 1252
Plugins : 
    mimeTools (3.1)
    NppConverter (4.6)
    NppExport (0.4)
```

**Comment by alankilborn** [comment]
You probably have _Match whole word only_ checkmarked in your _Preferences_:

![image](https://github.com/user-attachments/assets/7953e99d-36fe-47e8-a515-ac238189ca0d)

Uncheckmark it and the behavior should meet your expectation.

**Comment by abs0** [comment]
> You probably have _Match whole word only_ checkmarked in your _Preferences_:
> 
> Uncheckmark it and the behavior should meet your expectation.

Thanks, that absolutely gets the desired behaviour!

Could I ask as to the reason behind the default behaviour? It was quite surprising to be able to select a block of text and have "Style one token" action on it, but  "Style All Occurrences of Token" do nothing. If the current selection does not match whole word tokens would "Style All Occurrences of Token" always do nothing?

**Comment by alankilborn** [comment]
I'm not privy to all of Notepad++ author's decisions, but for your example, if it is only a single selection that you are styling, then something like "whole word only" doesn't really come into play -- what gets styled is the entirety of your selection.

So, another example:  If you select `the` in the word `another`, and you tell the program to style that single occurrence, it does exactly that.  But if you were to style all occurrences, the program wants to know, do you want only `the` as a standalone word, or do you want it in `another`, `there`, `other`, etc.

**Comment by abs0** [comment]
OK, I think I understand. So if I have selected something which is not a valid whole word token (such as "startTimeInSeconds" - note quotes included), then with the default settings "Style All Occurrences of Token" will always fail, as I do not have a valid whole world token selected?

In that case could I suggest some visual feedback that an invalid selection has been made (possibly with a reference to the preferences setting), rather than a silent failure to do anything?

Thanks

**Comment by alankilborn** [comment]
> suggest some visual feedback that an invalid selection has been made

This opens the door to the same thing for the _Find what_ field in the _Find_ family of windows, when _Match whole word only_ is selected.

Also, note that quote (`"`) is rather simple to detect as a non-word character.  I'm not certain that all Unicode characters that _should_ be considered "word" characters actually are detected that way.  Translation: It may be difficult to implement.

**Comment by abs0** [comment]
> > suggest some visual feedback that an invalid selection has been made
> 
> This opens the door to the same thing for the _Find what_ field in the _Find_ family of windows, when _Match whole word only_ is selected.
> 
> Also, note that quote (`"`) is rather simple to detect as a non-word character. I'm not certain that all Unicode characters that _should_ be considered "word" characters actually are detected that way. Translation: It may be difficult to implement.

It may actually be easy to detect, but possibly not in an easy place to handle - if calling "Style All Occurrences of Token" with a non empty selection ends up styling nothing (not even the currently selected area of text), then we have probably hit this case :)

**Comment by alankilborn** [comment]
Well, I meant, if you're going to trap it out in _one_ place, then you should probably trap out the condition in analogous places.

**Comment by alankilborn** [comment]
Note also that it is not strictly dependent upon the quotes.
Consider `a"startTimeInSeconds"b` which _would_ be matched with _Match whole words only_ checkmarked.
In the example at the top of this thread it is only because of what _surrounds_ `"startTimeInSeconds"` that causes it not to be styled, specifically: `{"startTimeInSeconds":` (the opening brace and the colon).

**Comment by donho** [comment]
https://github.com/notepad-plus-plus/notepad-plus-plus/issues/15454#issuecomment-2245127744

**Comment by alankilborn** [comment]
@abs0 
Your idea for an error message when your situation occurs was rejected by the author of Notepad++.
The situation will continue to do nothing with no error indication.
