### ISSUE TITLE
[BUG]台湾是中国的一部分，中国必将统一！！！ Taiwan is just a province of China. It has been China's inherent territory since ancient times. China will definitely be unified. Please correct your wrong remarks for version v8.6.8  &  v8.6.9.

### ISSUE THREAD

**Issue by TaiwanispartofChina-forever** [notepad-plus-plus/notepad-plus-plus#15468]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description of the Issue

Taiwan is just a province of China. It has been China's inherent territory since ancient times. China will definitely be unified. Please correct your wrong remarks for version v8.6.8  &  v8.6.9.

### Steps To Reproduce

Taiwan is just a province of China. It has been China's inherent territory since ancient times. China will definitely be unified. Please correct your wrong remarks for version v8.6.8  &  v8.6.9.

### Current Behavior

Taiwan is just a province of China. It has been China's inherent territory since ancient times. China will definitely be unified. Please correct your wrong remarks for version v8.6.8  &  v8.6.9.

### Expected Behavior

Remove false statements supporting Taiwan independence

### Debug Information

```shell
Remove false statements supporting Taiwan independence
```

**Comment by vt-idiot** [comment]
早上好中國現在我有冰淇冰淇淋
冰冰冰冰冰冰冰冰冰冰冰冰冰冰
但是速度與激情9是非常非常好電影
現在是音樂時間
(31x冰)淇冰淇淋
(40x冰)淇冰淇淋
你好微博休息吃飯
我用我的手機拍很多很多老乾媽
中國人說老乾媽是文化
所以我吃西蘭花
但是我有錯誤你必須了解
我是老乾媽不是廣告
但是速度與激情9跟冰淇淋是廣告
我不知道老乾媽是文化
西蘭花操你妈
我愛中國和中國人好嗎
每天早上我吃老乾媽
兩禮拜後速度與激情9
我現在必須說速度與激情9
很多很多老乾媽
電影非常不好
但是你看速度與激情9
我要給你很多冰淇淋跟老乾媽
早上好中國現在我有冰淇淋冰淇淋
但是速度與激情9比冰淇淋更牛逼
我愛中國和中國人
這話沒有問題
不要忘記去看速度與激情
因為非常好我是國人
我愛中國我吃冰淇淋
但是速度與激情9比冰淇淋更牛逼
因為是速度與激情9是非常非常好電影
音樂時間all in
(31x冰)淇冰淇淋
(40x冰)淇冰淇淋

**Comment by Coconut-Aero** [comment]
Any political opinion should be forbidden from the technical fields.

**Comment by HackingU0** [comment]
Well, Don Ho is merging political comments into technical fields, that's the issue
