### ISSUE TITLE
[BUG] IconList:AddIcon LoadIcon error when starting the app

### ISSUE THREAD

**Issue by solo16** [notepad-plus-plus/notepad-plus-plus#15465]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description of the Issue

Everytime I open the app it will throw up an error msg prompt IconList:addIcon: LoadIcon() function return null error

I could use the app with yes but the tab now is missing the "X" icon

### Steps To Reproduce

1.  open the app
2.  
3.  

### Current Behavior

Everytime I open the app it will throw up an error msg prompt IconList:addIcon: LoadIcon() function return null error

I could use the app with yes but the tab now is missing the "X" icon

### Expected Behavior

Expected to open the app without error msg and the "x" icon show appear on each tab
![loadicon null error](https://github.com/user-attachments/assets/32a807a4-8d2f-42d1-b858-e51cbf095b82)
![missing icon](https://github.com/user-attachments/assets/4d807534-c9c5-40df-9965-ac62654ceca7)

### Debug Information

```shell
Notepad++ v8.6.9   (64-bit)
Build time : Jul 12 2024 - 05:09:25
Path : F:\Program Files\Notepad++\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
Periodic Backup : ON
OS Name : Windows 10 Pro (64-bit)
OS Version : 22H2
OS Build : 19045.2006
Current ANSI codepage : 1252
Plugins : 
    mimeTools (3.1)
    NppConverter (4.6)
    NppExport (0.4)
```

**Comment by sXNA** [comment]
something broken on your OS, working fine for me on 3 computers with Windows 10 build 19045.4651

**Comment by solo16** [comment]
Thank you I've found out the issue for that which is IconCodecService.dll not being loaded during logon and I re-enabled it and now it works fine without the error.

**Comment by donho** [comment]
@solo16 
>  IconCodecService.dll not being loaded during logon and I re-enabled it and now it works fine without the error.

Could you tell me how you did know it's due to IconCodecService.dll not being loaded ?

**Comment by solo16** [comment]
Hi,

Because I looked up with the Autoruns from sysinternal tool and for
some reason it was disabled (unchecked) so I just enable it and it worked.

Thank you!

**Comment by donho** [comment]
@solo16 
Thank you for your explanation!

**Comment by Enjymon** [comment]
@solo16 

Hello,
I just encounter the same problem. How did you go about re-enabling IconCodecService.dll?

**Comment by solo16** [comment]
Hi,
I use a little app call Autorun from Microsoft

Cheers!
