### ISSUE TITLE
[Feature request] Select All Occurrences

### ISSUE THREAD

**Issue by BurningClutchez** [notepad-plus-plus/notepad-plus-plus#15484]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description of the Issue

I put an example below.
When trying to edit files of 600+ lines, if asked to delete all lines containing 'class="four"' could take a lot of time

```html
<div class="whatever">
<button class="four">Button One</button>
<button id="one">No issue</button>
<button class="four">Button Two</button>
<button id="three">No issue</button>
<button class="four">Button Three</button>
<p id="two">No issue</p>
<button class="four">Button five</button>
<p>orem ipsum dolor sit amet, consectetur adipiscin</p>
<button class="four">Button Six</button>
</div>
```

The example is specific, but I believe there would be a lot of benefits.

### Describe the solution you'd like.

With an all occurrence select, example issue be done in seconds.
If not as a build in feature, a plugin would work.

### Debug Information

```shell
Notepad++ v8.6.9   (64-bit)
Build time : Jul 12 2024 - 05:09:25
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : "C:\Program Files\Notepad++\change.log" 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
Periodic Backup : ON
OS Name : Windows 11 Home (64-bit)
OS Version : 23H2
OS Build : 22631.3880
Current ANSI codepage : 1252
Plugins : 
    mimeTools (3.1)
    NppConverter (4.6)
    NppExport (0.4)
```

**Comment by alankilborn** [comment]
"Select All Occurrences" can be done with multi-editing.
See the user manual [HERE](https://npp-user-manual.org/docs/editing/#multi-editing).

**Comment by BurningClutchez** [comment]
In the documentation you sent me 

Using multi- cursor accomplishes what I was looking for. Thank you

"Run Edit > Multi-Select Next > Match Case Only command 6 times. Note: You can always run this command via the menu, but it’ll be much easier to use the shortcut (I assigned Ctrl-E to it). You can assign any available shortcut to Multi-Select Next > Match Case Only command via Shortcut Mapper."
