### ISSUE TITLE
Remove notepadPlus.vs2005.vcproj

### ISSUE THREAD

**Issue by NN---** [notepad-plus-plus/notepad-plus-plus#155]
It is not maintained and the code uses C++11 features anyway.

**Comment by ariccio** [comment]
Xref: #121

**Comment by donho** [comment]
@NN--- Yes, I'm thinking about it. Will be done in few hours.

**Comment by NN---** [comment]
I don't see you have removed it :)

**Comment by milipili** [comment]
Nothing urgent :)
