### ISSUE TITLE
[Feature request] Please synchronize the browsers in the "Run" tab and the "View Current File in..." in the "View" tab

### ISSUE THREAD

**Issue by vochant** [notepad-plus-plus/notepad-plus-plus#15500]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description of the Issue

~As is known to all, Internet Explorer ended its support on June, 15, 2022. In the latest Windows system, attempting to open Internet Explorer will automatically redirect to Microsoft Edge. So keeping "Launch in IE" in "Run" tab is an outdated design. Please remove it and add "Launch in Edge", at least in Windows 10 version 1803 or newer.~

Is "Edit/View Current File in..." and "Run/Launch in ..." the same function? However, the browsers they support is not the same, which looks strange.

### Describe the solution you'd like.

 - ~Remove "Launch in IE"~
 - ~Add "Launch in Edge"~
 - Display the same browsers on the two tabs

### Debug Information

```shell
Notepad++ v8.6.9   (64-bit)
Build time : Jul 12 2024 - 05:09:25
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
Periodic Backup : ON
OS Name : Windows 11 Pro (64-bit)
OS Version : 23H2
OS Build : 22631.3880
Current ANSI codepage : 936
Plugins : 
    AutoSave (2)
    MarkdownViewerPlusPlus (0.8.2)
    mimeTools (3.1)
    NppConverter (4.6)
    NppExport (0.4)
```

**Comment by alankilborn** [comment]
![image](https://github.com/user-attachments/assets/62da6a68-8723-4189-a3a7-bc5b4799fa31)

Please close this issue.

**Comment by vochant** [comment]
> ![image](https://private-user-images.githubusercontent.com/77065706/353543689-62da6a68-8723-4189-a3a7-bc5b4799fa31.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIzOTIyOTMsIm5iZiI6MTcyMjM5MTk5MywicGF0aCI6Ii83NzA2NTcwNi8zNTM1NDM2ODktNjJkYTZhNjgtODcyMy00MTg5LWEzYTctYmM1YjQ3OTlmYTMxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzMxVDAyMTMxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIzMmNlOTBmN2Q0Yzc1ZDViNTI4NjE4ODE5ZGMwM2QzZDE1MmU1OTFmZGEwYTNlMjlmMmMzZGQ2ZmYyODVhYWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.bHlvAq8-TszOrnbobGdAps5jBqn7BHtNZK0i1LNU9nU)
> 
> Please close this issue.
![image](https://github.com/user-attachments/assets/c935bc88-0bcd-4422-bfd1-27047b225296)
I said 'Run' tab, are these two the same function? Or is it just a redundant design? The update has not been synchronized here yet.

**Comment by alankilborn** [comment]
>I said 'Run' tab

These were long ago removed from the `Run` menu of a fresh install (and put on the `View` menu).  The reason they still appear on your `Run` menu is that that menu is configurable and Notepad++ won't remove items from it (because it doesn't know if you've customized items or not).
