### ISSUE TITLE
[BUG] Close Notepad++ to continue dialog box comes up behind download progress box during update.

### ISSUE THREAD

**Issue by weogarth** [notepad-plus-plus/notepad-plus-plus#15507]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description of the Issue

During upgrade, have "Close npp to proceed with update" box on top/in front of the download progress box.

### Steps To Reproduce

1.  Have pre-8.6.9 version
2.  Initiate update
3.  Profit?

### Current Behavior

"Close npp to proceed with update" comes up behind the download bar, and is largely hidden by it.

### Expected Behavior

"Close npp to proceed with update" should be on top of the download bar so it can be clearly seen and interacted with.

### Debug Information

```shell
Notepad++ v8.6.9   (64-bit)
Build time : Jul 12 2024 - 05:09:25
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : "C:\Program Files\Notepad++\change.log" 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
Periodic Backup : ON
OS Name : Windows 10 Home (64-bit)
OS Version : 22H2
OS Build : 19045.4651
Current ANSI codepage : 1252
Plugins : 
    mimeTools (3.1)
    NppConverter (4.6)
    NppExport (0.4)
```

### Anything else?

Love the product! Been using off and on for years (I'm not a coder)

Unrelated, thank you SO VERY MUCH for having a dark mode not only in the product but blatantly obvious on your website as well.

Cheers!

**Comment by xomx** [comment]
@weogarth 
Are you talking about this:
https://github.com/notepad-plus-plus/wingup/commit/069edc21e28db01b13f88ac451aa71aea4889dfe#commitcomment-143134592
https://github.com/notepad-plus-plus/wingup/commit/069edc21e28db01b13f88ac451aa71aea4889dfe#commitcomment-143137138

If so, it should be already fixed.

Or, if it is something else, please include your relevant screenshots here.

**Comment by weogarth** [comment]
Yes. This is what was experienced.  Thank you.
