### ISSUE TITLE
[Feature request] Dont ask to save new files only containing new lines(\n)

### ISSUE THREAD

**Issue by tadghh** [notepad-plus-plus/notepad-plus-plus#15504]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description of the Issue

When trying to close a 'new' file that only contains new lines I am prompted to save.

### Describe the solution you'd like.

When a file is being closed and its only content is '\n' skip the save dialog.

### Debug Information

```shell
Notepad++ v8.6.9   (64-bit)
Build time : Jul 12 2024 - 05:09:25
Path : C:\Users\tadghh\scoop\apps\notepadplusplus\current\notepad++.exe
Command Line : "\\192.168.1.105\raid16\blog-db\comp552.txt"
Admin mode : ON
Local Conf mode : ON
Cloud Config : OFF
Periodic Backup : ON
OS Name : Windows 10 IoT Enterprise LTSC 2021 (64-bit)
OS Version : 21H2
OS Build : 19044.4529
Current ANSI codepage : 1252
Plugins : 
    Linter (0.1)
    mimeTools (3.1)
    NppConverter (4.6)
    NppExport (0.4)
    XMLTools (3.1.1.13)
    _CustomizeToolbar (5.3)
```

### Anything else?

![image](https://github.com/user-attachments/assets/f6854ee5-c22f-4560-ac70-2978695017ca)

Its just new lines I dont need to save it

**Comment by alankilborn** [comment]
IMO this is not a reasonable request

**Comment by tadghh** [comment]
> IMO this is not a reasonable request

How so? Why is the behaviour for an empty file different from this?

**Comment by molsonkiko** [comment]
@tadghh 

It takes less than a second to hit Ctrl+A then Backspace to select and delete the contents of a `new 1` scratch buffer. Why do you find it so onerous to need to hit Ctrl+A and then Backspace?

**Comment by alankilborn** [comment]
@tadghh said:

> Why is the behaviour for an empty file different from this?

Because the file (as described by you earlier) is not empty?
Programmers want to create all kinds of different files for all kinds of purposes all the time.
In that light, it's dumb to put something in place that prevents this, even thought that's not _your_ use case.

For me, on a semi-related note, it's dumb for Notepad++ to not allow you to save an untitled file right after you create it with Ctrl+n.  I _need_ zero-length files sometimes, and Notepad++ forces me to type a character and then backspace it off before I can save the new file.  Grrrr.

**Comment by tadghh** [comment]
> 
> 
> @tadghh said:
> 
> > Why is the behaviour for an empty file different from this?
> 
> Because the file (as described by you earlier) is not empty?
> Programmers want to create all kinds of different files for all kinds of purposes all the time.
> In that light, it's dumb to put something in place that prevents this, even thought that's not _your_ use case.
> 
> For me, on a semi-related note, it's dumb for Notepad++ to not allow you to save an untitled file right after you create it with Ctrl+n.  I _need_ zero-length files sometimes, and Notepad++ forces me to type a character and then backspace it off before I can save the new file.  Grrrr.

Ah I guess so
