### ISSUE TITLE
[Feature request] Send message to plugins when native language preference is changed.

### ISSUE THREAD

**Issue by molsonkiko** [notepad-plus-plus/notepad-plus-plus#15513]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description of the Issue

[See this community forum post for a description of the issue](https://community.notepad-plus-plus.org/post/96012).

In brief, it is currently *possible* for plugins to learn whether the user has changed their localization preference, but it is cumbersome and unintuitive to do so. There have been many requests (in various places) over the years to make plugins translatable, and adding an `NPPN_*` notification would definitely help plugin maintainers add translation to their plugins.

### Describe the solution you'd like.

It seems to me that relatively little code would be required to send an `NPPN_*` notification to all the plugins after Notepad++ has finished changing all of its own UI elements. I would probably recommend continuing to use the old `NPPM_INTERNAL_RELOADNATIVELANG` notification internally, and just create a new notification, maybe called `NPPN_RELOADNATIVELANG`, to notify plugins.

Based on my own experience [implementing a response to `NPPN_INTERNAL_RELOADNATIVELANG`](https://github.com/molsonkiko/NppCSharpPluginPack/commit/82edb829a39426d1a2cba8d7fb6284fc07267c5c) in my own plugin, I believe that this notification should probably also have the following payload:
```
// Assume that const char * nativeLangName is the filename associated with the nativeLang.xml file (minus the .xml extension)
//     for example, if the current language is English, nativeLangName = "english", if the current language is Italian, nativeLangName = "italian", and so on
//  Also assume that HMENU pluginMenuHandle is the HMENU to the Plugins submenu of the Notepad++ main menu.
//      We want to send this to plugin too, so that they can always find the submenu associated with their plugin, and then re-translate all their menu items.
//     You might be thinking "Wait, can't the plugins menu be found by using GetSubMenu(hNotepadPlusMainMenu, MENUINDEX_PLUGINS)?"
//     No! This is not possible, because some plugins like Columns++ can add their plugin's submenu to the Notepad++ main menu, and that means that the Plugins submenu is no longer at index MENUINDEX_PLUGINS of the main menu.
SCNotification scnN{};
scnN.nmhdr.code = NPPN_RELOADNATIVELANG
scnN.text = nativeLangName;
scnN.length = strlen(nativeLangName);
scnN.lParam = pluginMenuHandle;
```

By telling the plugin what the user's new native language preference is, and where the Plugins submenu of the Notepad++ main menu is located, you supply every plugin with enough information to re-translate their plugin into the current UI language of Notepad++, and you eliminate the need for every plugin to re-read the `nativeLang.xml` file every time the notification is fired.

### Debug Information

```shell
Notepad++ v8.6.9   (64-bit)
Build time : Jul 12 2024 - 05:09:25
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : "C:\Users\mjols\AppData\Roaming\Notepad++\nativeLang.xml"
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
Periodic Backup : ON
OS Name : Windows 10 Home (64-bit)
OS Version : 22H2
OS Build : 19045.4651
Current ANSI codepage : 1252
Plugins : 
    ColumnsPlusPlus (1.1.1)
    ComparePlus (1.1)
    CSharpPluginPack (0.0.3.11)
    CSVLint (0.4.6.6)
    EnhanceAnyLexer (1.1.3)
    HTMLTag (1.4.3.1)
    HugeFiles (0.4.1)
    JsonTools (8.0.0.17)
    mimeTools (3.1)
    NavigateTo (2.7)
    NppConverter (4.6)
    NppExport (0.4)
    NppLspClient (0.0.21)
    PythonScript (3.0.16)
    XMLTools (3.1.1.13)
```

**Comment by rdipardo** [comment]
👍🏼 I've been waiting for this: rdipardo/nppHTMLTag#5

**Comment by conky77** [comment]
#8972

**Comment by rdipardo** [comment]
@molsonkiko 

> ```
> SCNotification scnN{};
> scnN.nmhdr.code = NPPN_RELOADNATIVELANG
> scnN.text = nativeLangName;
> scnN.length = strlen(nativeLangName);
> scnN.lParam = pluginMenuHandle;
> ```

But will this be emitted during program startup, when the menus get initialized?

If the plugin needs to know what the current language is, what about a companion API like `NPPM_GETUSERNATIVELANG(0, [out] char* nativeLangName)`? That way plugins don't have to parse `nativeLang.xml` to discover a basic attribute of the GUI state. Even better if the language identifiers were enumerated (e.g. `enum NativeLang { NL_ENG, NL_FR, ..., NL_MAX };`).

**Comment by molsonkiko** [comment]
@rdipardo 
> Even better if the language identifiers were enumerated (e.g. enum NativeLang { NL_ENG, NL_FR, ..., NL_MAX };).

I'm in favor of enums for pretty much every situation like this, *except* this one. Whenever someone is doing translation, they are naturally going to be mapping strings (language names) to objects that contain translation data. For example, in JsonTools, I have `langName.json5` files, and I just set `langName` to the same language name that Notepad++ uses. If we used an enumeration instead, I would have to go into the Notepad++ source code, find the enumeration, find where the enumeration is mapped to language names, and then copy that mapping into my source code. The only benefit this confers is that it indicates what language translations exist for Notepad++, which can easily be done by looking [in this folder](https://github.com/notepad-plus-plus/notepad-plus-plus/tree/master/PowerEditor/installer/nativeLang).

> But will this be emitted during program startup, when the menus get initialized?

I think this is the best solution. As you say, if we fire this message at startup, it won't be necessary for plugins to *ever* parse `nativeLang.xml`. And since the notification is emitted at startup and whenever the UI language changes, we don't need to create a new `NPPM_GETUSERNATIVELANG`.

As I noted in my original post, it is *not* sufficient for Notepad++ to tell plugins what the user language is; they also need to know the handle to the plugins submenu (it's *not* always going to be at position 10, trust me), so that they can use `GetSubMenu` and `GetMenuItemInfo` to page through the plugins until they find their plugin's submenu. That's why I like a notification; the struct has space to confer both pieces of information.

**Comment by molsonkiko** [comment]
I've implemented this notification [in this branch of my fork](https://github.com/molsonkiko/notepad-plus-plus/tree/FEAT-notify_plugins_native_lang). Instructions for how to test it are in [the commit message for this commit](https://github.com/molsonkiko/notepad-plus-plus/commit/67624f1f7b8fa254cd871f20d1c1d4c6c08bc75d).

**Comment by rdipardo** [comment]
@molsonkiko

I'm vaguely familiar with the .NET solution; roughly, create a ghost application deriving from `System.Windows.Forms.NativeWindow`, enqueue this in N++'s event loop so it gets hit with menu updates, register the ghost application's event handler with the plugin so it, too, stays in the loop, etc.

On the C++ side however there doesn't seen to be any straightforward way to get a handle to any specific plugin menu. The mostly opaque [`Notepad_plus::reloadLang` function](https://github.com/notepad-plus-plus/notepad-plus-plus/blob/9e4290094dfd008bd1de1b3cf4b23c204cb0bba6/PowerEditor/src/Notepad_plus.cpp#L7112) simply iterates through every translatable menu that's currently visible and redraws 'em all in one go.

So, would the notification collect the handles of *all* the affected dialogs and return 'em, and in what field? Pointers change size depending on CPU architecture, and then even the *number* of menu handles will change whenever more components become translatable, which often happens in point releases...

There's a pretty strong precedent for N++ notifications only filling the `NMDR` fields (and for good reason: Microsoft maintains the library where that structure is defined), and since the `NPPM_INTERNAL_RELOADNATIVELANG` call site isn't already using a `WPARAM` or `LAPARAM`, a starting point for a quick and dirty implementation might look something like this:

```diff
diff --git a/PowerEditor/src/MISC/PluginsManager/Notepad_plus_msgs.h b/PowerEditor/src/MISC/PluginsManager/Notepad_plus_msgs.h
index d94f6427..b66ad926 100644
--- a/PowerEditor/src/MISC/PluginsManager/Notepad_plus_msgs.h
+++ b/PowerEditor/src/MISC/PluginsManager/Notepad_plus_msgs.h
@@ -1196,3 +1196,8 @@ enum Platform { PF_UNKNOWN, PF_X86, PF_X64, PF_IA64, PF_ARM64 };
 	//scnNotification->nmhdr.code = NPPN_GLOBALMODIFIED;
 	//scnNotification->nmhdr.hwndFrom = BufferID;
 	//scnNotification->nmhdr.idFrom = 0; // preserved for the future use, must be zero
+
+	#define NPPN_NATIVELANGCHANGED (NPPN_FIRST + 31)  // To notify plugins that the user has changed their native language preference
+	//scnNotification->nmhdr.code = NPPN_NATIVELANGCHANGED;
+	//scnNotification->nmhdr.hwndFrom = hwndNpp;
+	//scnNotification->nmhdr.idFrom = nativeLangName; // `nullptr` (0) for English, otherwise a pointer to the new language name
diff --git a/PowerEditor/src/NppBigSwitch.cpp b/PowerEditor/src/NppBigSwitch.cpp
index 37ad0447..cf92e2ac 100644
--- a/PowerEditor/src/NppBigSwitch.cpp
+++ b/PowerEditor/src/NppBigSwitch.cpp
@@ -912,7 +912,15 @@ LRESULT Notepad_plus::process(HWND hwnd, UINT message, WPARAM wParam, LPARAM lPa
 
 		case NPPM_INTERNAL_RELOADNATIVELANG:
 		{
-			reloadLang();
+			if (!reloadLang())
+				return FALSE;
+
+			SCNotification scnN{};
+			scnN.nmhdr.code = NPPN_NATIVELANGCHANGED;
+			scnN.nmhdr.hwndFrom = hwnd;
+			scnN.nmhdr.idFrom = static_cast<uptr_t>(wParam); // `nullptr` (0) for English, otherwise a pointer to the new language name
+			_pluginsManager.notify(&scnN);
+
 			return TRUE;
 		}
 
diff --git a/PowerEditor/src/WinControls/Preference/preferenceDlg.cpp b/PowerEditor/src/WinControls/Preference/preferenceDlg.cpp
index 28fc980f..49948007 100644
--- a/PowerEditor/src/WinControls/Preference/preferenceDlg.cpp
+++ b/PowerEditor/src/WinControls/Preference/preferenceDlg.cpp
@@ -820,7 +820,7 @@ intptr_t CALLBACK GeneralSubDlg::run_dlgProc(UINT message, WPARAM wParam, LPARAM
 										// Change the language 
 										if (localizationSwitcher.switchToLang(langName))
 										{
-											::SendMessage(::GetParent(_hParent), NPPM_INTERNAL_RELOADNATIVELANG, 0, 0);
+											::SendMessage(::GetParent(_hParent), NPPM_INTERNAL_RELOADNATIVELANG, reinterpret_cast<WPARAM>(langName), 0);
 											::InvalidateRect(_hParent, NULL, TRUE);
 										}
 									}
```

**Comment by molsonkiko** [comment]
@rdipardo 

> On the C++ side however there doesn't seen to be any straightforward way to get a handle to any specific plugin menu. The mostly opaque [Notepad_plus::reloadLang function](https://github.com/notepad-plus-plus/notepad-plus-plus/blob/9e4290094dfd008bd1de1b3cf4b23c204cb0bba6/PowerEditor/src/Notepad_plus.cpp#L7112) simply iterates through every translatable menu that's currently visible and redraws 'em all in one go.

Yes, and in my experience it is at least as irritating to do this in C#. That is why I wanted my new notification to give every plugin the `HMENU` of the `Plugins` submenu, which it does by [determining the name of the `Plugins` submenu, and then iterating through the Main menu until it finds a submenu with that name](https://github.com/molsonkiko/notepad-plus-plus/blob/67624f1f7b8fa254cd871f20d1c1d4c6c08bc75d/PowerEditor/src/Notepad_plus.cpp#L7254). If we didn't send this to the plugins, they would have to parse `config.xml` to find out what the name of the `Plugins` menu is, so that they could find it.

> There's a pretty strong precedent for N++ notifications only filling the `NMDR` fields

That is a good point, [which is why my current implementation only uses those fields](https://github.com/molsonkiko/notepad-plus-plus/blob/67624f1f7b8fa254cd871f20d1c1d4c6c08bc75d/PowerEditor/src/MISC/PluginsManager/Notepad_plus_msgs.h#L1200).

**Comment by rdipardo** [comment]
> I don't see a particular advantage to having `nullptr` be the default.

My neither, but I observed that `NPPM_INTERNAL_RELOADNATIVELANG` was always sent twice, and the first time always followed the zero-parameter path ca. line 820 in `PowerEditor/src/WinControls/Preference/preferenceDlg.cpp`. Just another example of how N++'s localization code wasn't designed with external processes in mind :(

**Comment by molsonkiko** [comment]
@rdipardo 

> Me neither, but I observed that `NPPM_INTERNAL_RELOADNATIVELANG` was always sent twice, and the first time always followed the zero-parameter path:

In my implementation, I made it so `NPPM_INTERNAL_RELOADNATIVELANG` uses its `WPARAM` as a `BOOL` to indicate whether a notification should be sent to plugins. When the first message in each pair is sent out, the `WPARAM` is `FALSE`.

**Comment by rdipardo** [comment]
@molsonkiko 

> I made it so `NPPM_INTERNAL_RELOADNATIVELANG` uses its `WPARAM` as a `BOOL` to indicate whether a notification should be sent to plugins.

Yeah that's much more logical. However the `LPARAM` will still be `0` when the destination language is English (and `WPARAM` is 0). At other times, `LPARAM` will point to `L"English"`. That should probably be documented somewhere, assuming N++'s internal logic remains the same.

**Comment by donho** [comment]
The better specs (IMO) should be:
```cpp
	#define NPPN_NATIVELANGCHANGED (NPPN_FIRST + 31)  // To notify plugins that the current native language is just changed to another one.
                                                      // Use NPPM_GETNATIVELANGFILENAME to get current native language file name.
                                                      // Use NPPM_GETMENUHANDLE(NPPPLUGINMENU, 0) to get submenu "Plugins" handle (HMENU)
	//scnNotification->nmhdr.code = NPPN_NATIVELANGCHANGED;
	//scnNotification->nmhdr.hwndFrom = hwndNpp
	//scnNotification->nmhdr.idFrom = 0; // preserved for the future use, must be zero
```
For the sake of performance:
Not all plugins need treat this notification, so the notification should be brief to have less impact of performance.
