### ISSUE TITLE
[BUG] style configurator, global styles are not translated

### ISSUE THREAD

**Issue by conky77** [notepad-plus-plus/notepad-plus-plus#15514]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description of the Issue

style configurator, all items"global styles" are not translatable

![immagine](https://github.com/user-attachments/assets/8783b537-c3e8-457b-913a-bf5f290b0cb2)

### Steps To Reproduce

1.  enter style configurator
2.  enter global styles
3.  

### Current Behavior

items not translatable

### Expected Behavior

give more space and make translatable
- global styles
- global override
- default style
- indent guideline style
- etc

### Debug Information

```shell
Notepad++ v8.6.9   (64-bit)
Build time : Jul 12 2024 - 05:09:25
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : -multiInst
Admin mode : ON
Local Conf mode : OFF
Cloud Config : OFF
Periodic Backup : ON
OS Name : Windows 11 Home (64-bit)
OS Version : 23H2
OS Build : 22631.3958
Current ANSI codepage : 1252
Plugins : 
    ComparePlus (1.2)
    DSpellCheck (1.5)
    ERPHelper (1.1.2)
    HexEditor (0.9.12)
    JsonTools (8.0.0.3)
    mimeTools (3.1)
    MultiReplace (3.0.3.15)
    NppConverter (4.6)
    NppExport (0.4)
    NPPJSONViewer (2.0.7)
    NppMenuSearch (0.9.6)
    NppPluginOpenHost (1.1)
    PoorMansTSqlFormatterNppPlugin (1.6.13.31508)
    SQLinFormNpp64 (6.24.4.1)
    XMLTools (3.1.1.13)
```

**Comment by conky77** [comment]
#8972

**Comment by donho** [comment]
They (strings) are the IDs for using in the code, so they are not for the translation.
