### ISSUE TITLE
Change To Debug Flags & Code/Text Lines

### ISSUE THREAD

**Issue by JohnWHagen** [notepad-plus-plus/notepad-plus-plus#15519]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description of the Issue

I'd like to suggest a change where the breakpoints and line numbers are displayed. Personally I find it annoying that when I click in the wrong spot (next to a line number) in Notepad++ that the breakpoint "marker" is displayed,instead of selecting the whoe line. In Visual Studio 2022, they implemented a different design that I believe is superior. See attached snip of a screen. By making this change, I believe it would enhance the user experience of Notepad++.

By the way, this IS the greatest lie/text/programming source code editor out there! Thanks for a great product!!

John
![Screenshot 2024-08-07 105227](https://github.com/user-attachments/assets/18593dfe-4dc5-4a30-bb4e-2bd165a9f491)

### Describe the solution you'd like.

Implement the same style/design as MSVC 2022 code editor.

### Debug Information

```shell
Nothing to debug. Just cosmetics.
```

### Anything else?

![Screenshot 2024-08-07 105227](https://github.com/user-attachments/assets/6157b27f-b426-4a15-87dd-7add3fc1f0a5)

**Comment by alankilborn** [comment]
So...you want to change Notepad++ behavior and make possibly many thousands of users confused because when they click where they are used to clicking, now Notepad++ does something different from what they have been used to for a really long time?

Actually, in Visual Studio's code editor, I'm guessing that you are clicking to the _right_ of the line number?  If so, just train yourself to click _on_ the line number (which I think in the VS code editor this is actually the same thing, the line number is just left-justified in a really wide line-number margin).  If you click _on_ the line number, both in VS code editor and in Notepad++, the entire line of text is selected.  Also, in either editor, triple-clicking anywhere within the actual line of text will achieve line selection.

**Comment by JohnWHagen** [comment]
ref:  So...you want to change Notepad++ behavior and make
        possibly many thousands of users confused because when they
        click where they are used to clicking, now Notepad++ does
        something different from what they have been used to for a
        really long time?
      
    Wow, so much for making any suggestions. Inertia is
      hard to overcome... No more suggestions from me. Sorry.
    John
    
    
    
    On 8/7/2024 1:58 PM, alankilborn wrote:
    
    
      
      So...you want to change Notepad++ behavior and make
        possibly many thousands of users confused because when they
        click where they are used to clicking, now Notepad++ does
        something different from what they have been used to for a
        really long time?
      Actually, in Visual Studio's code editor, I'm
        guessing that you are clicking to the right of the
        line number? If so, just train yourself to click on
        the line number (which I think in the VS code editor this is
        actually the same thing, the line number is just left-justified
        in a really wide line-number margin). If you click on
        the line number, both in VS code editor and in Notepad++, the
        entire line of text is selected. Also, in either editor,
        triple-clicking anywhere within the actual line of text will
        achieve line selection.
      —
        Reply to this email directly, view it on GitHub, or unsubscribe.
        You are receiving this because you authored the thread.Message
          ID: ***@***.***>
      [
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/notepad-plus-plus/notepad-plus-plus/issues/15519#issuecomment-2274145926",
"url": "https://github.com/notepad-plus-plus/notepad-plus-plus/issues/15519#issuecomment-2274145926",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by alankilborn** [comment]
>Wow, so much for making any suggestions. Inertia is hard to overcome... No more suggestions from me. Sorry.

Suggestions need to be well thought out, and impact to other users assessed.
Hopefully you read far enough into my earlier response to see that if you simply alter your behavior slightly, in both the VS code editor and Notepad++, you'll find enough "common ground" such that you wouldn't have made the suggestion in the first place.

**Comment by JohnWHagen** [comment]
No problem, done here. 
    
    One final suggestion, Delete the GitHub account. 
    
    You know, nothing changes without suggestions. After all, Notepad++
    has come a long way sine inception. Why, because changes were made
    to improve its usefulness, correct? Were all suggestions good? No,
    of course not. I don't have a problem with the suggestion being
    thrown out. As a software guy, I totally understand.
    
    It's the attitude that's my issue. I could go on but there is no
    purpose.
    
    Delete the account so I don't get any more crappy responses.
    
    Bye and continue doing well with Notepad++!!
    
    John
    
    
    On 8/7/2024 2:37 PM, alankilborn wrote:
    
    
      
      
        Wow, so much for making any suggestions. Inertia
          is hard to overcome... No more suggestions from me. Sorry.
      
      Suggestions need to be well thought out, and impact
        to other users assessed.
        Hopefully you read far enough into my earlier response to see
        that if you simply alter your behavior slightly, in both the VS
        code editor and Notepad++, you'll find enough "common ground"
        such that you wouldn't have made the suggestion in the first
        place.
      —
        Reply to this email directly, view it on GitHub, or unsubscribe.
        You are receiving this because you authored the thread.Message
          ID: ***@***.***>
      [
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/notepad-plus-plus/notepad-plus-plus/issues/15519#issuecomment-2274212672",
"url": "https://github.com/notepad-plus-plus/notepad-plus-plus/issues/15519#issuecomment-2274212672",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by alankilborn** [comment]
I don't really understand.  You seem to be upset that I (just another Notepad++ user, BTW, with no real power to influence Notepad++ coding direction) commented on your suggestion, perhaps pointing out some weaknesses with the idea, along with trying to be helpful and point out how you can already achieve the common functionality you desire.  I'm really sorry if I've offended you somehow / some way; this surely was not my intent.

**Comment by ArkadiuszMichalski** [comment]
@JohnWHagen In Notepad++ it's not breakpoints but bookmarks. If you don't use it you can turn it off:

![image](https://github.com/user-attachments/assets/756c397b-50b0-42be-bda6-dca7a5dfd43a)

**Comment by alankilborn** [comment]
Another potential problem for the OP and others regarding the OP's problem:

There is not a great distinction in the background color of the line number margin and the bookmark margin.  They both have a light grey background, and they are different greys -- but it is subtle.  Thus, it may appear that there is only one margin there, and that clicking to the right of the line number is the same as clicking _on_ the line number.  Not so.

**Comment by ArkadiuszMichalski** [comment]
@alankilbor Also in default style `Bookmark margin` and `Change History margin` use same color which can be confusing. Fortunately, this can be changed, so if someone is constantly making mistakes, they can make it more clear.

`Change History margin` is also clickable and allows us to select a line, but `Line number margin` it's bigger and I think it's easier to just click on it.

![image](https://github.com/user-attachments/assets/8582d596-a555-48a6-aefc-86829219247b)

**Comment by alankilborn** [comment]
>so if someone is constantly making mistakes, they can make it more clear.

I definitely agree, but the typical user doesn't want to have to bother with this; they just want the default to have good contrast (if they think about it at all).

Note that in my discussion of background color, I've only considered non-dark mode -- I haven't looked at dark mode in this regard.
