### ISSUE TITLE
[BUG] <More Colours...>should be translated

### ISSUE THREAD

**Issue by zy0016** [notepad-plus-plus/notepad-plus-plus#15518]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description of the Issue

Settings->Style Configurator ->Foreground color: "More Colours..." text should be translated for Chinese.
![image](https://github.com/user-attachments/assets/94304582-c482-4076-ada6-73574c8eee93)

### Steps To Reproduce

1.  Settings
2.  Style Configurator
3.  Foreground color

### Current Behavior

dialog display "More Colours..."

### Expected Behavior

dialog display "更多颜色"

### Debug Information

```shell
Notepad++ v8.6.9   (64-bit)
Build time : Jul 12 2024 - 05:09:25
Path : D:\Program Files\Notepad++\notepad++.exe
Command Line : 
Admin mode : ON
Local Conf mode : OFF
Cloud Config : OFF
Periodic Backup : ON
OS Name : Windows 10 Enterprise (64-bit)
OS Version : 22H2
OS Build : 19045.4529
Current ANSI codepage : 936
Plugins : 
    ComparePlugin (2.0.2)
    ComparePlus (1.1)
    GitSCM (1.4.9.1)
    HexEditor (0.9.12)
    JsonTools (7.1)
    MarkdownViewerPlusPlus (0.8.2)
    mimeTools (3.1)
    NppConverter (4.6)
    NppExport (0.4)
    NPPJSONViewer (2.0.7)
    NppMarkdownPanel (0.7.3)
```

**Comment by donho** [comment]
It's a system dialog, so it's not possible to translate.
