### ISSUE TITLE
[BUG] xml keystroke comment

### ISSUE THREAD

**Issue by whutton-CLGX** [notepad-plus-plus/notepad-plus-plus#15524]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description of the Issue

If you enter in the keyboard command for commenting a xml line you get a error dialog.  If you select the command from the menu system then the line is commented correctly..

This is using the XML plugin / XML Tools

### Steps To Reproduce

1.  Highlight a line in a xml file
2.  Enter in   <crlt> <alt> <shift> C
3.  A error dialog is displayed "Error while trying to parse JSON.

### Current Behavior

![image](https://github.com/user-attachments/assets/98f4c172-4d62-418b-984e-5584d92f56cc)

### Expected Behavior

Commented line

![image](https://github.com/user-attachments/assets/fa80b900-7a1a-4e70-9d02-ea8f349d597a)

### Debug Information

```shell
Notepad++ v8.6.9   (64-bit)
Build time : Jul 12 2024 - 05:09:25
Path : C:\program1\Notepad++\notepad++.exe
"
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
Periodic Backup : ON
OS Name : Windows 10 Enterprise (64-bit)
OS Version : 22H2
OS Build : 19045.4529
Current ANSI codepage : 1252
Plugins : 
    GitSCM (1.4.7.1)
    HexEditor (0.9.12)
    JsonTools (4.4)
    MarkdownViewerPlusPlus (0.8.2)
    mimeTools (3.1)
    npp.connections (1.1)
    NppConverter (4.6)
    NppEditorConfig (0.4)
    NppExport (0.4)
    NppFTP (0.29.9)
    NPPJSONViewer (1.40)
    NppOpenAI (0.1.5)
    XMLTools (3.1.1.13)
```

**Comment by alankilborn** [comment]
Plugins are not developed by the Notepad++ dev team.
This site here is for core Notepad++ issues.
Please find the plugin site and report your problem there.
