### ISSUE TITLE
[BUG] Double Clicking text in Find/Replace Menu is inconsistent with main editor

### ISSUE THREAD

**Issue by Paxtez** [notepad-plus-plus/notepad-plus-plus#15525]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description of the Issue

If you double click text to quick select it, it doesn't match if you clicked on the same text in the body

### Steps To Reproduce

1.  CTRL + N for new document
2.  Enter the following text:  ``$this (test) "shows" 'the' double-clicking {issue} [described].``
3.  Double click on each word and notice that only the text is highlighted.
4. CTRL + F to open the Find menu
5. Enter the same text in the find box: ``$this (test) "shows" 'the' double-clicking {issue} [described].``
6. Double click on each word and observe that the selection includes the the special characters around it.

### Current Behavior

Currently double clicking a word in the find box appears to select everything between two spaces/hyphens (and also selects a trailing space/hyphen).

### Expected Behavior

Double clicking a word should be consistent with the logic used in the main program.

### Debug Information

```shell
Notepad++ v8.6.9   (64-bit)
Build time : Jul 12 2024 - 05:09:25
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : "C:\Program Files\Notepad++\change.log" 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
Periodic Backup : ON
OS Name : Windows 11 Pro (64-bit)
OS Version : 22H2
OS Build : 22621.2134
Current ANSI codepage : 1252
Plugins : 
    DSpellCheck (1.5)
    mimeTools (3.1)
    NppConverter (4.6)
    NppExport (0.4)
    zoomdisabler_x64 (1.2)
```

**Comment by alankilborn** [comment]
The editor window is a special editing container.
The _Find what_ box is a standard control provided by Windows.
Thus, they have (and always will have) different behaviors.
This issue can be closed.
