### ISSUE TITLE
Text cursor thickness

### ISSUE THREAD

**Issue by borsotti** [notepad-plus-plus/notepad-plus-plus#15526]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description of the Issue

The text cursor, the one that looks like a large, thin, "I" (NOT the caret), that is displayed when the mouse pointer hovers
the text, is so thin as to be very hard to see. There is no Windows setting that could make it bigger. Notepad++ allows
to configure the thickness of the caret, but not that of the text cursor. Would it be possible to make it thicker?

### Describe the solution you'd like.

Have it thicker

### Debug Information

```shell
Notepad++ v8.6.9   (64-bit)
Build time : Jul 12 2024 - 05:09:25
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
Periodic Backup : ON
OS Name : Windows 10 Pro (64-bit)
OS Version : 22H2
OS Build : 19045.4651
Current ANSI codepage : 1252
Plugins : 
    DSpellCheck (1.5)
    LocationNavigate (0.4.8.1)
    mimeTools (3.1)
    NppConverter (4.6)
    NppExport (0.4)
    _CustomizeToolbar (5.3)
```

**Comment by alankilborn** [comment]
>There is no Windows setting

Wrong.  It's a Windows setting.

In Win 11 (I'm sure Win 10 is similar):
![image](https://github.com/user-attachments/assets/e000cc48-00cf-48a0-97e6-1ddb31009938)

**Comment by whindsaks** [comment]
> is so thin as to be very hard to see

Is it also too thin in other applications? 

I believe this sizing feature was added to Windows 10 April 2019 Update and there is no similar option in older versions.
