### ISSUE TITLE
Replace All works only from cursor down

### ISSUE THREAD

**Issue by sedlacl** [notepad-plus-plus/notepad-plus-plus#15527]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description of the Issue

As far as I remember ReplaceAll replaced all items in current file. Now is behaviour it replaces only from cursors to eof.

### Steps To Reproduce

1.  Make file with 3 same lines with text "aaa"
2.  Go to second line
3.  Call ReplaceAll with "a"->"d"

### Current Behavior

It replaces only from cursor to end of file. There is no way how to replace all occurences in file with single button.

### Expected Behavior

I expect to Replace All found instances in whole file.

It could be also option [x] whole file (I understand some expect different behaviour) or another button "Replace all in whole file"

### Debug Information

```shell
Notepad++ v8.6.9   (64-bit)
Build time : Jul 12 2024 - 05:09:25
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
Periodic Backup : OFF
OS Name : Windows 11 Enterprise (64-bit)
OS Version : 23H2
OS Build : 22631.3880
Current ANSI codepage : 65001
Plugins : 
    ComparePlus (1.2)
    JSMinNPP (1.2312)
    mimeTools (3.1)
    NppConverter (4.6)
    NppExport (0.4)
    XMLTools (3.1.1.13)
```

**Comment by alankilborn** [comment]
Place a checkmark in _Wrap around_.
This issue may be closed.
