### ISSUE TITLE
[BUG] {regression} Style All Occurrences of Token is working only with whole words

### ISSUE THREAD

**Issue by arfmach** [notepad-plus-plus/notepad-plus-plus#15539]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description of the Issue

If we select some text and choose "Search / Style All Occurrences of Token" (with any of the 5 styles), NPP will only style the tokens if the selected text is a whole word; if we select some part of a word, then nothing occurs (not even the selected text becomes styled). Oddly enough, if we do the same with the option "Search / Style One Token", the selected text becomes styled regardless of being a whole word or not.

### Steps To Reproduce

1. Have any text opened in NPP
2. Select some text that is only a part of a word (e.g. "quest" in "Request")
3. Choose menu "Search / Style All Occurrences of Token / any style" (or use keyboard shortcut)

### Current Behavior

None of the tokens become styled, not even the selected one.

### Expected Behavior

All occurrences of the selected text should become styled according to the chosen option.

### Debug Information

```shell
Notepad++ v8.6.9   (64-bit)
Build time : Jul 12 2024 - 05:09:25
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : "C:\Program Files\Notepad++\change.log" 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : C:\Users\<username>\OneDrive - <company>\Notepad++
Periodic Backup : ON
OS Name : Windows 11 Pro (64-bit)
OS Version : 23H2
OS Build : 22631.3958
Current ANSI codepage : 1252
Plugins : 
    BigFiles (0.1.3)
    BracketsCheck (1.2.2)
    CodeAlignmentNpp (14.1.107)
    ColumnTools (1.4.4.1)
    ComparePlugin (2.0.2)
    JsMapParser.NppPlugin (4.2)
    JSMinNPP (1.2205)
    JsonTools (3)
    MarkdownViewerPlusPlus (0.8.2)
    mimeTools (3.1)
    NppConverter (4.6)
    nppcrypt (1.0.1.6)
    NppExport (0.4)
    NppMarkdownPanel (0.6.2)
    NppToolBucket (1.10.6622.41516)
    PoorMansTSqlFormatterNppPlugin (1.6.13.31508)
    XMLTools (3.1.1.13)
```

**Comment by alankilborn** [comment]
Uncheckmark this Settings > Preferences entry:

![image](https://github.com/user-attachments/assets/66b9a46b-446d-4038-bb4d-2df39ff5ccea)

I recently suggested a code change so that an error message would pop up in the situation you describe ("not even the selected text becomes styled"), but the author of Notepad++ ( @donho ) declined to accept it.

**Comment by donho** [comment]
> I recently suggested a code change so that an error message would pop up in the situation you describe ("not even the selected text becomes styled"), but the author of Notepad++ ( @donho ) declined to accept it.

@alankilborn 
We can find several cases that the behaviour can be change in Preferences. If an application should REMIND some users with a bothering dialog to do the right thing, it will be unbearable to use it. 

BTW I just googled *"How to Style All Occurrences of Token to Match part of word Notepad++"*, and here the result:
https://www.google.com/search?q=How+to+Style+All+Occurrences+of+Token+to+Match+part+of+word+Notepad%2B%2B&client=firefox-b-d&sca_esv=09c6452bc1fe88ee&sca_upv=1&sxsrf=ADLYWIIBnIwYADsbdgch7OOuLkIDES8orA%3A1723562656591&ei=oHq7ZrPkI6yckdUPloe60QU&ved=0ahUKEwiztJOfo_KHAxUsTqQEHZaDLloQ4dUDCA8&uact=5&oq=How+to+Style+All+Occurrences+of+Token+to+Match+part+of+word+Notepad%2B%2B&gs_lp=Egxnd3Mtd2l6LXNlcnAiRUhvdyB0byBTdHlsZSBBbGwgT2NjdXJyZW5jZXMgb2YgVG9rZW4gdG8gTWF0Y2ggcGFydCBvZiB3b3JkIE5vdGVwYWQrK0gAUABYAHAAeACQAQCYAQCgAQCqAQC4AQPIAQD4AQGYAgCgAgCYAwCSBwCgBwA&sclient=gws-wiz-serp

So the repeated "bug" report does not show it's a real impact, user can find the answer easily.
If such confusion happens over and over again, we can consider to disable "Match whole word only" by default for "Style All Occurrences of Token" settings. But let's forget about the troublesome dialog which will cause more problem.

**Comment by alankilborn** [comment]
> If an application should REMIND some users with a bothering dialog to do the right thing, it will be unbearable to use it.

...OR, the user appreciates that the application is saying something to him and reminding him what he's doing wrong, as opposed to just doing nothing and making the user want to put in a bug report.  

> I just googled ...user can find the answer easily.

It's easy to google, but user is annoyed that he has to google in the first place.
