### ISSUE TITLE
Replace function doesnt allow bigger sample than 2048 bytes

### ISSUE THREAD

**Issue by sirapacz** [notepad-plus-plus/notepad-plus-plus#1555]
I use it for removing php injections of malware code. When code to cut is less than 2048 you can use this function byt bigger one is truncated.
I can add such big block only by selecting block of text and then use Replace function (it pastes automaticly). If i will try to copy-paste it cuts ataround 44b

**Comment by MetaChuh** [comment]
please update your notepad++ to the latest 64 bit version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins if you update from version 7.5.9 or below.
if your issue still persists, and it is still of relevance, please feel free to file a new issue as easy to understand and reproducible as possible.

thank you for your help and best regards.
