### ISSUE TITLE
[BUG] Full Window Is Too Short By 1 Pixel

### ISSUE THREAD

**Issue by whitsettbe** [notepad-plus-plus/notepad-plus-plus#15557]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description of the Issue

NPP maximized window does not capture all mouse actions in the top 1px of the screen.

### Steps To Reproduce

1.  Open Notepad++ in external monitor
2.  Maximize window
3.  Hover/click mouse along the top pixel row of the window

### Current Behavior

Click action is not caught by Notepad++, usually affecting the window behind it instead. Several strips of the top of the window are caught effectively, but these are few and far between. Trying to exit Notepad++ from the top pixel row often closes the application behind it instead.

### Expected Behavior

Notepad++ should catch all clicks made atop the external monitor when maximized.

### Debug Information

```shell
Notepad++ v8.6.9   (64-bit)
Build time : Jul 12 2024 - 05:09:25
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
Periodic Backup : ON
OS Name : Windows 11 Home (64-bit)
OS Version : 23H2
OS Build : 22631.4037
Current ANSI codepage : 1252
Plugins : 
    mimeTools (3.1)
    NppConverter (4.6)
    NppExport (0.4)
```

### Anything else?

My primary display runs on an AMD Radeon Graphics Processor (0x1681), with the afflicted display running through an NVIDIA GeForce RTX 3070 Laptop GPU.
Connecting the monitor to my other laptop, which runs both displays on a single Intel(R) UHD Graphics card, does not have the same issue. (Same OS and NPP versions)

Seems similar to microsoft/terminal#7422.

**Comment by xomx** [comment]
Known multi-monitor issue.
Reason - Notepad++ is not yet a per-monitor DPI aware (V2) app yet. A long term PR fix is in progress.

Duplicate of many issues, search e.g. for the "Maximized", "Maximised", "Full screen" or similar.

Here user reported a successful workaround:
https://github.com/notepad-plus-plus/notepad-plus-plus/issues/14337#issuecomment-1835791674

**Comment by whitsettbe** [comment]
Thank you. The "system" DPI override from that link prevented the issue. Icons are now slightly blurred on my primary monitor, but I can tolerate that until a fix is released.
