### ISSUE TITLE
Search Dialog transparency

### ISSUE THREAD

**Issue by otalado** [notepad-plus-plus/notepad-plus-plus#15551]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description of the Issue

I'm generally happy with Notepad++, but I'm having trouble adjusting to the transparent search dialog that appears when I click on text. While I see the reasoning behind it, it just doesn't work for me. 

### Describe the solution you'd like.

I'd like to kindly ask if it would be possible to give users the option to enable or disable transparency.

### Debug Information

```shell
Notepad++ v8.6.7   (64-bit)
Build time : May 12 2024 - 20:04:00
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : 
Admin mode : ON
Local Conf mode : OFF
Cloud Config : OFF
Periodic Backup : ON
OS Name : Windows 11 Pro (64-bit)
OS Version : 23H2
OS Build : 22631.4037
Current ANSI codepage : 1252
Plugins : 
    mimeTools (3.1)
    NppConverter (4.6)
    NppExport (0.4)
```

**Comment by alankilborn** [comment]
>give users the option to enable or disable transparency

Hmmmmmmmmmmmmmmm:

![image](https://github.com/user-attachments/assets/8dc4eab9-2947-4651-8d8b-44acd856638a)

Please close this issue.

**Comment by otalado** [comment]
I am ashamed! It was in front of me, yet I played blind. No wonder I found nothing while searching. Please excuse me, I did not want to insult anybody. It was just a case of being blind an stupid --- :(
