### ISSUE TITLE
WDL language definition file

### ISSUE THREAD

**Issue by fangdongming** [notepad-plus-plus/notepad-plus-plus#15550]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description of the Issue

Hi,
There is no WDL language definition file, Could you added the WDL.xml ?
WDL, Workflow Description Language;

Thank you.

### Describe the solution you'd like.

Add the WDL.xml in  userDefinedLanguages/UDLs.

### Debug Information

```shell
No.
```

**Comment by alankilborn** [comment]
>Add the WDL.xml in userDefinedLanguages/UDLs.

If developers were to add this, it wouldn't be "userDefined".

---

I presume this is a good place to find out what WDL is:  https://github.com/openwdl/wdl/blob/wdl-1.1/SPEC.md
