### ISSUE TITLE
[BUG] Pig Latin Mistranslation

### ISSUE THREAD

**Issue by quinntropolis** [notepad-plus-plus/notepad-plus-plus#15567]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description of the Issue

The "Status Bar" `Hide` checkbox option in the `Settings -> Preferences -> General` menu is not translated in Pig Latin

This is from v8.6.9, and I was sure to check that I had the latest pig latin localization installed

### Steps To Reproduce

1.  Open Notepad++, make sure to have the `Pig Latin` localization installed 
2. On the menu bar, select the Settings drop down, then go to Preferences
3.  In General, change Localization to `Pig Latin`

### Current Behavior

The Status Bar `Hide` checkbox option in the `Settings -> Preferences -> General` menu is not translated in Pig Latin

![Screenshot 2024-08-22 192620](https://github.com/user-attachments/assets/b0d71be2-36bc-4c6b-9bf3-666f7fbbd084)

### Expected Behavior

Should be translated as `Idehay`, the same as in the Toolbar section just below

### Debug Information

```shell
Notepad++ v8.6.9   (32-bit)
Build time : Jul 12 2024 - 05:08:26
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Command Line : "C:\Program Files (x86)\Notepad++\change.log" 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
Periodic Backup : ON
OS Name : Windows 11 Home (64-bit)
OS Version : 23H2
OS Build : 22631.4037
Current ANSI codepage : 1252
Plugins : 
    mimeTools (3.1)
    NppConverter (4.6)
    NppExport (0.4)
```

**Comment by schnurlos** [comment]
piglatin.xml is from last year, so nobody is doing new translations there ...
Probably you can continue?
https://github.com/notepad-plus-plus/notepad-plus-plus/blob/master/PowerEditor/installer/nativeLang/piglatin.xml
