### ISSUE TITLE
[Feature request]Link Pop-Up Window <title>

### ISSUE THREAD

**Issue by PaltryProgrammer** [notepad-plus-plus/notepad-plus-plus#15570]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description of the Issue

To traverse a link it is necessary to recall the required key + mouse click combination. I utilize many editors each w/ their own combination w/ the result it is necessary to experiment id est "is it mouse click is it double mouse click is it Ctrl+mouse click is it Ctrl + double mouse click is it Alt+mouse click is it Alt+double mouse click is it Ctrl+Alt+mouse click is it Ctrl+Alt+double mouse click etc. etc. etc. ad nauseum not to mention the Shift key. Doing so is of course annoying. This is the "Issue".

### Describe the solution you'd like.

May I please request feature as per BowPad per demonstration in attached video. Such is very convenient as it precludes the necessity of attempting to recall the required key + mouse click combination to traverse the link.
Thank You Kindly
![Link Pop-Up Window](https://github.com/user-attachments/assets/fe20e552-708b-43a4-9aef-8564608411c8)

### Debug Information

```shell
Notepad++ v8.6.9   (64-bit)
Build time : Jul 12 2024 - 05:09:25
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
Periodic Backup : ON
OS Name : Windows 10 Pro (64-bit)
OS Version : 22H2
OS Build : 19045.4780
Current ANSI codepage : 1252
Plugins : 
    DSpellCheck (1.4.24)
    mimeTools (3.1)
    NppConverter (4.6)
    NppExport (0.4)
```

**Comment by alankilborn** [comment]
You didn't search existing issues too well.
#12209

**Comment by PaltryProgrammer** [comment]
May i please inquire your search term(s) as my search via "link pop-up box " did not reveal duplicate.

**Comment by pryrt** [comment]
I disagree:
![image](https://github.com/user-attachments/assets/9f61fbdc-3c93-4950-ba0d-9e4756053306)
[search yourself, with those exact words](https://github.com/notepad-plus-plus/notepad-plus-plus/issues?q=is%3Aissue+is%3Aopen+link+pop-up+box)

**Comment by ozone10** [comment]
btw #12209 is duplicate of #10650
