### ISSUE TITLE
xiaobiesun

### ISSUE THREAD

**Issue by baijingetangzichen** [notepad-plus-plus/notepad-plus-plus#15585]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description of the Issue

![image](https://github.com/user-attachments/assets/8521ecec-6da7-4462-9be1-f77bc08e30c2)

### Steps To Reproduce

1.  dwadaw
2.  dwadawdawd
3.  awdawdawdawdaw
awdawdawd

### Current Behavior

awdawdawdawdawdaw

### Expected Behavior

dwadawdawdawd

### Debug Information

```shell
dwadawdawdawdawdaw
```

### Anything else?

dawdawdawdawdawdawdawd

**Comment by baijingetangzichen** [comment]
kankanba

**Comment by woaicandy** [comment]
+1
