### ISSUE TITLE
[Feature request] Toolbar icons design improvement

### ISSUE THREAD

**Issue by wildtang** [notepad-plus-plus/notepad-plus-plus#15586]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description of the Issue

Some Fluent UI icons need to be improved for consistency, I think.
See the image below please:

<img width="1082" alt="2024-08-28_101946" src="https://github.com/user-attachments/assets/d4d1a019-a90d-41ad-b07e-567e2fda89e2">

### Describe the solution you'd like.

Some Fluent UI icons need to be improved for consistency.

### Debug Information

```shell
Nope.
```

**Comment by wildtang** [comment]
The version of Notepad++ is 8.6.8

**Comment by CennoxX** [comment]
I also had this thought multiple times. Especially the record macro icon makes for a restless appearance.
@WildByDesign If you find the time, could you make suggestions for alternatives?

**Comment by WildByDesign** [comment]
The Save Macro button, in particular, has bothered me for a while. I actually did a mock up a couple of months ago but got into some other work and didn't end up posting it.

![npp-savemacro](https://github.com/user-attachments/assets/b952879b-7cd0-4987-9f4b-2b25f45d42f3)

Although I understand that this still has some filled components to it. I might be able to do the disk part of it with the lines design, but it's quite small and might not look well. But I can have a look at it.

The New Document and Record icons should be pretty easy.

**Comment by wildtang** [comment]
@CennoxX @WildByDesign What nice two men you are🚀

**Comment by wildtang** [comment]
Good job, Thanks!
