### ISSUE TITLE
[Feature request] Remove the inactive Border right to the vertical ScrollBar

### ISSUE THREAD

**Issue by vws-java** [notepad-plus-plus/notepad-plus-plus#15592]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description of the Issue

This is about scrolling by dragging the vertical scrollbar with the mouse. Scrolling this way would be more comfortable if there wasn't a border to the right of the scrollbar. Currently, you have to be careful not to move the mouse to the very edge of the screen.
![scriollbar](https://github.com/user-attachments/assets/d96da3e6-59c2-43f4-840a-ef3abdcb1dd2)

### Describe the solution you'd like.

"Tear down the border" ;-)
See also how scrollbars are implemented by modern browsers, e.g.

**Comment by xomx** [comment]
@vws-java 

try in N++:

![npp-noedge](https://github.com/user-attachments/assets/96b13d59-ed17-42f1-982b-8a089b183914)

**Comment by vws-java** [comment]
Nice, hanks for the tip!
