### ISSUE TITLE
Feature Request: Extended Syntax Highlighting Recognition

### ISSUE THREAD

**Issue by neurodeamon** [notepad-plus-plus/notepad-plus-plus#1559]
Hi,

sadly matching the syntax highlighting solely based on file extensions is pretty limited when it comes to different programs/services using the same extension: i.e.  ".conf" is such a candidate (used by Apache, Asterisk, Icinga, etc).

It would be nice to have an option to activate for some extensions to match the file content for language specific keywords (and pick the best match) if there are multiple candidates for syntax highlighting.

Kind regards

neuro

**Comment by MetaChuh** [comment]
this is currently not possible.
