### ISSUE TITLE
[Feature request] hybrid font: English and Chinese

### ISSUE THREAD

**Issue by maxchendt** [notepad-plus-plus/notepad-plus-plus#15593]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description of the Issue

text with English and Chinese, the default screen font is changed from 8.5.x to 8.6.x

![858](https://github.com/user-attachments/assets/768a9f3f-8ae0-4e4a-a78d-28626242b783)

![869](https://github.com/user-attachments/assets/5a995a1d-0829-4338-918a-702c9d07d8e9)

### Describe the solution you'd like.

In 8.6.x, to behave like 8.5.x, change the font by:  settings > style configurator > global styles > default style, and  set the font to SongTi (宋体), however, the English text is now in SongTi, and looks not as good as that in default settings.

### Debug Information

```shell
nothing
```

### Anything else?

How to let 8.6.x show the hybrid text (En+Cn) the style as in 8.5.x?

**Comment by rdipardo** [comment]
Have you tried __*dis*__&#x200C;abling [Direct Write] technology at `Settings > Preferences > MISC.`?

[Direct Write]: https://learn.microsoft.com/zh-cn/windows/win32/directwrite/direct-write-portal

<img width="800" alt="npp-8 6 9-d2d-disabled" src="https://github.com/user-attachments/assets/08e10c5c-44ae-44b4-80b3-22cd0c7f9841">

**Comment by maxchendt** [comment]
great!  It restores to old fashion without this "Direct Write technology"

Without a setting of hybrid fonts, I would like to keep the "Direct Write technology" disable.
