### ISSUE TITLE
[BUG] <title>Notepad++ closes while typing

### ISSUE THREAD

**Issue by catlover-forever** [notepad-plus-plus/notepad-plus-plus#15596]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description of the Issue

Typical scenario: I open a document previously created using Notepad++ to make a few changes. After locating the position to change or add I start typing. But after a few keystrokes Notepad++ just terminates without any trace. I reopen the document, the change I managed to make is there but when I start to type it terminates again. This is repeated various times, but somehow it suddenly accepts what I'm typing and all is back to normal. This has been going on for a long time and after every update I hope this issue has been solved, but no, it's still there today. I'm running v8.6.8 under Windows 10. I guess there is some sort of log that shows what happens but as an ordinary user I don't know how to get this solved. Help requested. Thanks.

### Steps To Reproduce

1.  Open the existing document
2.  Start typing
3.  Crash

### Current Behavior

Please see the issue description

### Expected Behavior

That Notepad++ doesn't close without trace

### Debug Information

```shell
Notepad++ v8.6.8   (64-bit)
Build time : Jun  4 2024 - 00:30:00
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : "C:\Users\staff\Documents\Registrum\Website\kanelbullar\index.html" 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
Periodic Backup : ON
OS Name : Windows 10 Home (64-bit)
OS Version : 22H2
OS Build : 19045.4780
Current ANSI codepage : 1252
Plugins : 
    ColumnTools (1.4.4.1)
    ComparePlugin (2.0.2)
    mimeTools (3.1)
    NppConverter (4.6)
    NppExport (0.4)
    NppHorizontalRuler (0.1.6)
    SelectQuotedText (1)
    XMLTools (3.1.1.13)
    _CustomizeToolbar (5.3)
```

**Comment by rdipardo** [comment]
>  NppHorizontalRuler (0.1.6)

Uninstall that: <https://github.com/notepad-plus-plus/notepad-plus-plus/issues/13068#issuecomment-1419540283>

**Comment by catlover-forever** [comment]
Thanks. I select NppHorizontalRuler.dll in the plugin administrator and click Delete (Borrar on my Spanish version), I'm asked if Notepad++ is allowed to make changes to the system, which I allow. The app restarts but the plugin is still there :-( What do I need to do more?

**Comment by rdipardo** [comment]
Try running the application as an Adminstrator:

<img width="442" alt="Screenshot 2024-09-01 145214" src="https://github.com/user-attachments/assets/f2393423-ca05-4079-8faa-32e345586f8f"><br>

If that doesn't work, open File Explorer and delete this folder: `C:\Program Files\Notepad++\plugins\NppHorizontalRuler\`

I suggest also removing or upgrading the SelectQuotedText plugin: https://github.com/ffes/selectquotedtext/releases/tag/v1.1.0

**Comment by catlover-forever** [comment]
Done. Thanks!
