### ISSUE TITLE
[BUG] <title>Those who split the country must be punished no matter how far away they are

### ISSUE THREAD

**Issue by topworldcoder** [notepad-plus-plus/notepad-plus-plus#15600]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description of the Issue

Those who split the country must be punished no matter how far away they are

### Steps To Reproduce

1.  Those who split the country must be punished no matter how far away they are
2.  Those who split the country must be punished no matter how far away they are
3.  Those who split the country must be punished no matter how far away they are

### Current Behavior

Those who split the country must be punished no matter how far away they are

### Expected Behavior

Those who split the country must be punished no matter how far away they are

### Debug Information

```shell
Those who split the country must be punished no matter how far away they are
```

### Anything else?

Those who split the country must be punished no matter how far away they are

**Comment by 239573049** [comment]
Those who split the country must be punished no matter how far away they are
