### ISSUE TITLE
find in Files

### ISSUE THREAD

**Issue by Rsilver-shepardes** [notepad-plus-plus/notepad-plus-plus#1561]
It seems that the find in files is no longer working in ver. 6.9.
I have tested on 2 machines both Windows 10 Pro.
Simply running the setup for ver 6.8.8 over 6.9 did not fix the issue.
I had to uninstall ver 6.9, then install 6.8.8 and find in files works again.

Thank you for this AWESOME editor.

Respectfully,
Richard Silver
rsilver@shepardes.com

**Comment by dail8859** [comment]
Define "no long working". Does this mean you just are not finding any results? Or it doesn't even try to search at all? 

I can at least verify it works for me under Win7. Make sure you have the appropriate settings for the filters, search mode, etc.

**Comment by Rsilver-shepardes** [comment]
Thank you for your quick response.
Sorry for not enough info.

So before it would search each file, in my directory it takes about 1 minute because of all of the files.
Ver 6.9 does not search any of the files nor displays the window to show no files found.

It is like it quits just after the click of the find all button.

Please check on windows 7  because it could be a windows 10 issue.

Thank you again,
Richard Silver

**Comment by dail8859** [comment]
I'm sure you have already but I'd recommend making sure you are using the exact same settings in the dialog (e.g. "In all sub-folders", etc). Since I only have Win7 someone else may need to see if this is specific to Win10. 

Does this happen for all directories? Only certain ones?

**Comment by Rsilver-shepardes** [comment]
So tested searching files on local drive and it worked on my domain windows 10 computer.
I tried to search a mapped drive again and it did not work.
I removed the filter and it still did not work.

Hope this helps!

Richard Silver

**Comment by Faq** [comment]
@Rsilver-shepardes  is this issue still valid with newest version? if not then please close it.

**Comment by donho** [comment]
I believe this issue has been fixed since long time ago.
Update your Notepad++ to the latest version (v7.6.6).
If the issue persists, please create a new issue for it.
Thank you.
