### ISSUE TITLE
End key vs. Shift+End moves the cursor to different places in a wrapped line

### ISSUE THREAD

**Issue by joshburnett** [notepad-plus-plus/notepad-plus-plus#1562]
When the cursor is on a paragraph of text long enough to wrap around, pressing the End key and Shift+End may move the cursor to different places. If the cursor is on the first line (before the first wrapping point), pressing the End key will move the cursor to the end of the line, to the point where the text gets wrapped.  However, pressing Shift+End will move the cursor to the very end of the paragraph, past any wraps, highlighting along the way.

For example, I start with the following block of text, all in a single paragraph, and the cursor partway through the second line:
![1 - cursor starting point](https://cloud.githubusercontent.com/assets/12973799/13432201/a63c1006-df9a-11e5-9b15-59998f361d19.png)

If I press the End key, the cursor moves to the end of the line, after the word 'Raw'.  If I press Shift+End, the rest of the paragraph is selected:
![2 - after shift-end key](https://cloud.githubusercontent.com/assets/12973799/13432392/58d1d426-df9b-11e5-8b11-9cfc69be08c8.png)

Similar behavior is observed with the Home key vs. Shift+Home.

**Comment by dail8859** [comment]
What version of Notepad++ are you using? It should be fixed in the newest version (v6.9)

**Comment by joshburnett** [comment]
Ah, excellent! I was using 6.8.6.  Updated to 6.9 and it now works properly.  It's been bugging me for many many versions now, didn't think about it getting fixed just before I finally got around to submitting the bug report.

Thanks!
