### ISSUE TITLE
[BUG] In Npp 8.7 RC, if there is no nativeLang.xml, receiving NPPM_GETNATIVELANGFILENAME from a plugin causes crash

### ISSUE THREAD

**Issue by molsonkiko** [notepad-plus-plus/notepad-plus-plus#15627]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description of the Issue

As described in the title. [First described here](https://community.notepad-plus-plus.org/topic/26105/notepad-v8-7-release-candidate/6).

I discovered this accidentally when I installed the latest version of [NppCSharpPluginPack](https://github.com/molsonkiko/NppCSharpPluginPack) in a fresh install of the [Notepad++ 8.7 RC](http://download.notepad-plus-plus.org/repository/8.x/8.7.RC/), and found that Notepad++ was crashing on startup when that plugin was enabled. Running the plugin in the Visual Studio debugger determined that __the crash happened while Notepad++ was processing the `NPPM_GETNATIVELANGFILENAME` message__ that my plugin sent in response to the `NPPN_READY` notification.

When I run the same version of the plugin on Notepad++ 8.6.9, or a slightly earlier version of the plugin that doesn't sent the message on Notepad++ 8.7, I have no problem.

Presumably the best fix to this issue is to have `NPPM_GETNATIVELANGFILENAME` return `NULL` if there is no `nativeLang.xml` file, or else return `english` since that's the default language.

### Steps To Reproduce

1. Download the NppCSharpPluginPack ([64-bit files](https://github.com/molsonkiko/NppCSharpPluginPack/blob/main/NppCSharpPluginPack/Release_x64.zip), and the [32-bit files](https://github.com/molsonkiko/NppCSharpPluginPack/blob/main/NppCSharpPluginPack/Release_x86.zip))
2.  Unzip the zipped folder into a folder named `CSharpPluginPack` and put it into the `plugins` folder of the latest master
3.  Try to run `notepad++.exe`
4. Watch it crash

### Current Behavior

See above

### Expected Behavior

See above

__NOTE:__ the Debug Information below obviously does not show CSharpPluginPack 0.0.3.14, because that plugin caused the crash.

### Debug Information

```shell
Notepad++ v8.7   (64-bit)
Build time : Sep 11 2024 - 19:03:37
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
Periodic Backup : ON
OS Name : Windows 10 Home (64-bit)
OS Version : 22H2
OS Build : 19045.4894
Current ANSI codepage : 1252
Plugins : 
    JsonTools (8.1.0.6)
    mimeTools (3.1)
    NppConverter (4.6)
    NppExport (0.4)
```

**Comment by rdipardo** [comment]
#### Quick fix

```diff
--- a/PowerEditor/src/localization.h
+++ b/PowerEditor/src/localization.h
@@ -102,3 +102,3 @@ private:
 	bool _isEditZoneRTL = false; // for Scitilla
-	const char *_fileName = nullptr;
+	const char *_fileName = "";
 	std::map<std::string, std::wstring> _shortcutMenuEntryNameMap;
```

**Comment by xomx** [comment]
@rdipardo 
> Quick fix

On the 2nd sight this fix is not ok as the `_fileName` NULL is taken into account elsewhere (maybe there are other such constructs in the N++ code):
https://github.com/notepad-plus-plus/notepad-plus-plus/blob/45cd29f8ea700b602550e5329bac8ab90b341313/PowerEditor/src/Notepad_plus.cpp#L144-L148

**Comment by molsonkiko** [comment]
I've fixed it in my fork. The problem was pretty simple: in [the response to the message in NppBigSwitch](https://github.com/notepad-plus-plus/notepad-plus-plus/blob/45cd29f8ea700b602550e5329bac8ab90b341313/PowerEditor/src/NppBigSwitch.cpp#L3764) the code tries to make a `string` from a `const char *` without doing a `NULL` check first.

I'll submit a PR; I don't see any reason for anyone else to work on it, since the fix is so simple.

**Comment by donho** [comment]
@molsonkiko 
Sorry I did my fix without checking your PR.
