### ISSUE TITLE
Code Folding for between bracket (D Language)  [ ... ]

### ISSUE THREAD

**Issue by apz28** [notepad-plus-plus/notepad-plus-plus#15647]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description of the Issue

D language has array defined between '[' & ']' and it can be long or break into multiple lines. Without code folder for this can cause scrolling

### Describe the solution you'd like.

Same folder as '{' & '}' pair

### Debug Information

```shell
Any workaround?
```

**Comment by rdipardo** [comment]
@apz28 this issue should have been opened in the Lexilla project: <https://github.com/ScintillaOrg/lexilla/issues>
