### ISSUE TITLE
[BUG] NPPexport - copy RTF to clipboard

### ISSUE THREAD

**Issue by laurentc2** [notepad-plus-plus/notepad-plus-plus#15644]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description of the Issue

Last year, it was OK to select the text an NPPexport the RTF to clipboard to copy the colored text to MSword or LibreOfficeWriter, but now I have to save the RTF to get the colored text : the copy to clipboard does not work anymore 👎 
Can youfix it ? Thank you,
Laurent

### Steps To Reproduce

1.  
2.  
3.  

### Current Behavior

The NPPexport copy RTF to clipboard does not copy the colors

### Expected Behavior

The NPPexport copy RTF to clipboard should copy the colors of the text

### Debug Information

```shell
none
```

**Comment by xomx** [comment]
Cannot reproduce, works ok for me with latest v8.7:

![npp-RTFexport-ok](https://github.com/user-attachments/assets/87f4bb7c-0186-4c24-a453-f8b9c7bdba01)

![npp-RTFexport-ok-WordPad](https://github.com/user-attachments/assets/a699228e-640d-4117-a8a3-51a4634ef012)

> but now I have to

Next time please fill out the issue template, at least your N++ menu > ? > Debug Info..., as no one can help you with your specific problem if one does not now at least the basics of your N++ setup...

**Comment by xomx** [comment]
https://community.notepad-plus-plus.org/post/97175
