### ISSUE TITLE
[Feature request] Documentation enhancement to describe the process of aborting/exiting column mode via the Esc key

### ISSUE THREAD

**Issue by turonosaurus** [notepad-plus-plus/notepad-plus-plus#15663]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description of the Issue

I decided to investigate my inability to control / figure out how, in Notepad++, to control where the cursor lands when you're using Column mode and you hit your Esc key to exit/abort column mode.  It seemed to me like usually it would fall **_after_** the selection but **_sometimes_** at the beginning, but I couldn't control it or predict **_where_** it was going to land.  After searching online and in the Notepad++ documentation on this and finding nothing, I was about to submit a Bug report and, as I was thinking about the steps to reproduce it hit me!  Where the cursor lands is dependent upon the direction you are going **_when you first make_** your selection at the point **_when you activate_** column mode.
- If I hold Alt+C and hit my **_up_** arrow key to select in the upwards direction, later when I hit Esc the cursor lands **_at the beginning_** of the selection.
- In contrast if I hold Alt+C and hit my **_down_** arrow key to select in the upwards direction, later when I hit Esc the cursor lands **_at the end_** of the selection.

With this realization I can see that it is working as designed - however - it would be nice if Notepad++'s documentation had explicitly spelled this out for me - and for the community of users.  I would think that [this "Selection modes & Column Editor" article](https://npp-user-manual.org/docs/editing/) should get updated appropriately to convey this information.

### Describe the solution you'd like.

I am not requesting any code updates to Notepad++ itself; I'm only suggesting that a bit of content ought to be added to [this "Selection modes & Column Editor" article](https://npp-user-manual.org/docs/editing/) that more explicitly describes how you can use your Esc key to exit/abort column mode, and how where the cursor lands afterwards is dependent upon the direction in which you were going when you first activated column mode.

### Debug Information

```shell
Notepad++ v8.6.9   (64-bit)
Build time : Jul 12 2024 - 05:09:25
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : "\\[aServerName]\[aSubPath]\config.json"
Admin mode : ON
Local Conf mode : OFF
Cloud Config : OFF
Periodic Backup : ON
OS Name : Windows 11 Enterprise (64-bit)
OS Version : 23H2
OS Build : 22631.4169
Current ANSI codepage : 1252
Plugins : 
    mimeTools (3.1)
    NppConverter (4.6)
    NppExport (0.4)
```

**Comment by alankilborn** [comment]
Close this issue; open one here: https://github.com/notepad-plus-plus/npp-usermanual/issues

**Comment by turonosaurus** [comment]
OK @alankilborn, I have opened [new issue 703 under the Notepad++ User Manual](https://github.com/notepad-plus-plus/npp-usermanual/issues/703), and I will close this one.  Thanks!

**Comment by turonosaurus** [comment]
Closing
