### ISSUE TITLE
[BUG] Regression in 8.7 : Find dialog status bar messaging

### ISSUE THREAD

**Issue by alankilborn** [notepad-plus-plus/notepad-plus-plus#15662]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description of the Issue

See below.

### Steps To Reproduce

* Consider (otherwise empty) document containing `abc abc`.
* Place the caret on the first `abc`.
* Invoke Ctrl+f checkmark the box for _Wrap around_ and uncheckmark _Backward direction_.
* Press _Find Next_ until the status bar indicates "Find: Found the last occurrence from the top. The end of the document has been reached."

### Current Behavior

The problem with this is that what is selected is now the _first_ occurrence from the top, not the _last_ occurrence from the top (as the status messaging says).

This is purely a problem with the messaging, not the searching logic.

Here's the regressive text, from `english.xml` :

```
<find-status-top-reached value="Find: Found the last occurrence from the bottom. The beginning of the document has been reached."/>
<find-status-end-reached value="Find: Found the last occurrence from the top. The end of the document has been reached."/>
<find-status-replace-top-reached value="Replace: Replaced the last occurrence from the bottom. The begin of document has been reached"/>
<find-status-replace-end-reached value="Replace: Replaced the last occurrence from the top. The end of document has been reached"/>
```

### Expected Behavior

I'd expect better status messages.

Generally, in 8.7, the texts "Find: Found the 1st occurrence" and "Replace: Replaced the 1st occurrence" have been replaced with "Find: Found the last occurrence" and "Replace: Replaced the last occurrence", respectively.  And this is bad...

Even if this regression was not introduced, couldn't these texts be made better?  

Instead of (the non-regressive 8.6.9 text):

```
<find-status-end-reached value="Find: Found the 1st occurrence from the top. The end of the document has been reached."/>
<find-status-top-reached value="Find: Found the 1st occurrence from the bottom. The beginning of the document has been reached."/>
<find-status-replace-end-reached value="Replace: Replaced the 1st occurrence from the top. The end of document has been reached"/>
<find-status-replace-top-reached value="Replace: Replaced the 1st occurrence from the bottom. The begin of document has been reached"/>
```

I'd suggest:

```
<find-status-end-reached value="Find: Found the first occurrence in the document (the bottom was reached and &quot;Wrap around&quot; to top occurred)"/>
<find-status-top-reached value="Find: Found the last occurrence in the document (the top was reached and &quot;Wrap around&quot; to bottom occurred)"/>
<find-status-replace-end-reached value="Replace: Replaced the last occurrence in the document (then &quot;Wrap around&quot; to top occurred)"/>
<find-status-replace-top-reached value="Replace: Replaced the first occurrence in the document (then &quot;Wrap around&quot; to bottom occurred)"/>
```

The suggested new text also informs the user what _Wrap around_ means (many novice users are confused on this point).

### Debug Information

```shell
Notepad++ v8.7   (64-bit)
Build time : Sep 17 2024 - 17:06:31
Path : C:\NotepadPlusPlus\Misc\_NoBackup\Releases\npp.8.7\npp.8.7.portable.x64\notepad++.exe
Command Line : -titleAdd="8.7 64-bit" -multiInst "C:\NotepadPlusPlus\Temp\20240928-055958_.txt" -n12
Admin mode : OFF
Local Conf mode : ON
Cloud Config : OFF
Periodic Backup : ON
OS Name : Windows 11 Pro (64-bit)
OS Version : 23H2
OS Build : 22631.4169
Current ANSI codepage : 1252
Plugins : 
    mimeTools (3.1)
    NppConverter (4.6)
    NppExport (0.4)
```

**Comment by alankilborn** [comment]
Some evidence that users don't really understand what "wrap around" means (and thus could benefit from the term appear in a status bar message -- to get them thinking about it):  https://github.com/notepad-plus-plus/notepad-plus-plus/issues/15668

**Comment by alankilborn** [comment]
A sample of what one of the suggested messages would look like:

![image](https://github.com/user-attachments/assets/0c82f27e-ae6d-464a-bda9-dd4e77de7ce2)

**Comment by donho** [comment]
@alankilborn 
Your suggested texts are too long, which makes them unacceptable.
However, it's not the point.
The point is, why are the current messages the problem?

**Comment by alankilborn** [comment]
>too long

Well, for clarity I think they're perfect.
But, I'll allow that when translated to other localizations, they could possibly be even longer.

**Comment by donho** [comment]
@alankilborn 
> But, I'll allow that when translated to other localizations, they could possibly be even longer.

Yes, that's the reason.
