### ISSUE TITLE
[BUG] Replace All is replacing only after the cursor position

### ISSUE THREAD

**Issue by otuzemen** [notepad-plus-plus/notepad-plus-plus#15668]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description of the Issue

When user wants to replace all in the opened document, replace all occurs only after the cursor position. If the cursor is in the end, no replace occurs.

### Steps To Reproduce

1.  Put the cursor in the middle of the file, somewhere
2.  Choose a string to replace which occurs before and after the cursor position
3.  Make a replace all, the text chosen into anything

### Current Behavior

Replace all occurs only after the cursor

### Expected Behavior

All occurrences of the searched string in the file must be replaced. 

### Debug Information

```shell
Notepad++ v8.7   (64-bit)
Build time : Sep 17 2024 - 17:06:31
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : "C:\Program Files\Notepad++\change.log" 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
Periodic Backup : ON
OS Name : Windows 11 Pro (64-bit)
OS Version : 23H2
OS Build : 22631.4249
Current ANSI codepage : 1252
Plugins : 
    ComparePlugin (2.0.2)
    CSVLint (0.4.6.2)
    CsvQuery (1.2.9)
    Explorer (1.9.9)
    HexEditor (0.9.12)
    JSFunctionViewer (1.1)
    JsonTools (4.11.1)
    mimeTools (3.1)
    NppConverter (4.6)
    NppExport (0.4)
    NppJavaPlugin (0.4)
    NPPJSONViewer (2.0.4)
    NppSnippets (1.7.1)
    PoorMansTSqlFormatterNppPlugin (1.6.13.31508)
    RegexTrainer (1)
    RestApiToText (1.4.0.1)
    SessionMgr (1.4.4)
    XMLTools (3.1.1.13)
```

**Comment by alankilborn** [comment]
Checkmark _Wrap around_ before pressing _Replace All_.
Please close this issue.
