### ISSUE TITLE
BUG: Folder as Workspace: Opens file on opening/closing folder

### ISSUE THREAD

**Issue by freeofbugs** [notepad-plus-plus/notepad-plus-plus#1567]
Hello.

If you have some folders and files in your workspace and selected one of those files then a bug occurs through the following action:

Open/expand a folder by clicking on the plus sign (+), then close it by clicking on the minus sign. This causes Notepad++ to open the currently selected file, which is - i think - not intended. Obviously Notepad++ recognizes a double-click as you can see in the second try.

![anim](https://cloud.githubusercontent.com/assets/17577970/13442033/ab756ec2-dffa-11e5-960a-88fe7bc90c53.gif)

**Comment by MetaChuh** [comment]
please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins if you update from version 7.5.9 or below.
if your issue still persists, and it is still of relevance to you, please feel free to file a new issue as easy to understand and reproducible as possible.

thank you for your support and best regards.

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
(no extra account is needed, just use your github account to sign in)
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)
