### ISSUE TITLE
[Feature request]  <Search result of multiple files should show which files not having searched string>

### ISSUE THREAD

**Issue by palaniappankvignesh** [notepad-plus-plus/notepad-plus-plus#15680]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description of the Issue

In the "Find in Files" option,
1. The user will search for a particular string is there in multiple files in a specific folder
2. The search result should also show which files do not have that string if we give it checkbox 

### Describe the solution you'd like.

In the "Find in Files" window, it can have a checkbox as "Inverse", when user clicked that it should show files that do not having that string

### Debug Information

```shell
Notepad++ v8.6.8   (64-bit)
Build time : Jun  4 2024 - 00:30:00
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
Periodic Backup : ON
OS Name : Windows 10 Enterprise (64-bit)
OS Version : 22H2
OS Build : 19045.4894
Current ANSI codepage : 1252
Plugins : 
    mimeTools (3.1)
    NppConverter (4.6)
    NppExport (0.4)
```

**Comment by alankilborn** [comment]
> The search result should also show which files do not have that string if we give it checkbox

It is perhaps not a bad idea...

---

For now, it can be done using regular expression search, for example to find files that do NOT contain `abc`:

Find what: `(?s-i)\A(?:(?!abc).)+\z`
Search mode: Regular expression

**Comment by alankilborn** [comment]
Also, see https://community.notepad-plus-plus.org/topic/19134

**Comment by palaniappankvignesh** [comment]
Yes I agree, but I just wanted to get the filename, it's giving normal search output like below.
![image](https://github.com/user-attachments/assets/b5b0c016-e946-4c3a-afbe-82098589c169)

**Comment by palaniappankvignesh** [comment]
OK, but the search result is not accurate. It gives output for the string searched, which is not present in any file.
![image](https://github.com/user-attachments/assets/377e6eac-5318-416f-b649-89deeaaae721)

**Comment by alankilborn** [comment]
@palaniappankvignesh 

> but the search result is not accurate

The result IS accurate, as to what was asked for ("show which files that do not have the searched string").
That result is in the line you have scribbled out using blue.
You can ignore the `Line 1` output line data as irrelevant.

**Comment by palaniappankvignesh** [comment]
ok, thanks..
