### ISSUE TITLE
[Feature request] <title> Enable Column Selection By Holding The Right Mouse Button Down.

### ISSUE THREAD

**Issue by tinker123456** [notepad-plus-plus/notepad-plus-plus#15686]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description of the Issue

Enable Column Selection By Holding The Right Mouse Button Down.

### Describe the solution you'd like.

Enable Column Selection By Holding The Right Mouse Button Down And Dragging.

The current way to do this is awkward.

### Debug Information

```shell
None.
```

**Comment by alankilborn** [comment]
>The current way to do this is awkward.

No more awkward than:

>Holding The Right Mouse Button Down And Dragging.

---

Please close this issue.

**Comment by donho** [comment]
> No more awkward than:

Agree.
