### ISSUE TITLE
Use pointer instead of cursor when hovering over file names in FaW

### ISSUE THREAD

**Issue by Ghasan** [notepad-plus-plus/notepad-plus-plus#1569]
Just as the question indicates. The first reason, it does not behave as what a cursor would - selecting file name text does not work. Second reason, this is what it supposed to be IMHO.

Side not, there is some annoying flickering when hovering over file names.

P.S. Thanks for the wonderful FaW. I could not think how beneficial it would be before trying it out :)

**Comment by donho** [comment]
What does it mean by FaW?
Friday After Work?
First Auto Works?
Football Association of Wales?
