### ISSUE TITLE
[Feature request] Don't clear the clipboard when no selection

### ISSUE THREAD

**Issue by Pachat** [notepad-plus-plus/notepad-plus-plus#15695]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description of the Issue

Right after Ctrl+C saves the selection, the next action is most often to press Ctrl+V somewhere else.
Because of the proximity of C and V on the keyboard, it often happens that one presses Ctrl+C instead of Ctrl+V
In most editors, the clipboard is not emptied. But Notepad++ does. Is there a reason for this?

### Describe the solution you'd like.

Keep clipboard contents on Ctrl+C without selection.

### Debug Information

```shell
None
```

**Comment by xomx** [comment]
![npp-uncheck-copycut-line-wo-selection](https://github.com/user-attachments/assets/3a490bc4-72e1-48f1-b6bf-d1104e4fb263)

**Comment by alankilborn** [comment]
>Don't clear the clipboard when no selection

For the record, the clipboard wasn't cleared.
Your caret was on a line that happened to be empty.
So when you fat-fingered Ctrl+c, meaning to hit Ctrl+v, a line-ending was copied to the clipboard.

Probably, when _Enable Copy/Cut Line without selection_ is enabled, the empty line situation should be detected, and the clipboard not changed.
