### ISSUE TITLE
[BUG]  {regression} "Replace All" keyboard shortcut regression

### ISSUE THREAD

**Issue by Jeankree** [notepad-plus-plus/notepad-plus-plus#15704]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description of the Issue

Since v8.6.9, and only in Italian, pressing Alt+T on Replace tab to "Replace All" in the current document will work only once.
Why?
Because short-key "T" is double and used for the button "Sostituisci tutti" (="Replace all") AND for the first main field "Trova" (="Find what").
Please do shortcut unique on each tab…
Until v8.6.8 it worked fine because this field  ("Find what") had no shortcut in Italian. I can understand that it could need one, but it shouldn't be the same as another object on the same "workspace" (i.e. Tab). Please remove o change the new added shortcut (field) or modify the old one (button).
HINTS: Alt-A or Alt-V could be a good choice for the Italian "Find what"-field; Alt-C could be a good choice for the Italian "Replace All"-button.

### Steps To Reproduce

1.  Have a text file with multiple character sequences (let's say it has more and more long strings of "a"). Example: aaaa bb a bbbaaaaaaajjjjajjaaaiuiuiuaaaa aaaaaaaaaaaa.
2.  Ctrl+H [you are now in the first field]
3.  Type: aa
4. Press `<Tab>` [you are now in the second field]
5. Type: a
6. Alt+T [button is activated and all aaa's strings will be halved]
7. Alt+T again [nothing happens because now the first field is "catching" the shortcut]

### Current Behavior

Alt-T on Replace tab works only once, you have then to press `<Tab>` for having Alt-T working again… once only.

### Expected Behavior

Alt-T should "Replace All", another consecutive Alt-T should "Replace All" again. etc…

### Debug Information

```shell
Notepad++ v8.7   (64-bit)
Build time : Sep 17 2024 - 17:06:31
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : "C:\[…]\TEST\test file.tx"
Admin mode : ON
Local Conf mode : OFF
Cloud Config : OFF
Periodic Backup : OFF
OS Name : Windows 7 Home Premium (64-bit)
OS Build : 7601.0
Current ANSI codepage : 1252
+ INTERFACE LANGUAGE: ITALIAN
```

**Comment by rdipardo** [comment]
Colpa di @conky77: 5f5f1e7e0a4654f3afe76c158077fa1fee9594d4

https://github.com/notepad-plus-plus/notepad-plus-plus/blob/5f5f1e7e0a4654f3afe76c158077fa1fee9594d4/PowerEditor/installer/nativeLang/italian.xml#L476

---

@Jeankree

> 3. Digit: aa
> ...
> 5. Digit: a

Tutto chiaro, però in inglese si dice "type" al imperativo.

**Comment by Jeankree** [comment]
> Colpa di @conky77: [5f5f1e7](https://github.com/notepad-plus-plus/notepad-plus-plus/commit/5f5f1e7e0a4654f3afe76c158077fa1fee9594d4)
> 
> https://github.com/notepad-plus-plus/notepad-plus-plus/blob/5f5f1e7e0a4654f3afe76c158077fa1fee9594d4/PowerEditor/installer/nativeLang/italian.xml#L476
> 
> @Jeankree
> 
> > 3. Digit: aa
> >    ...
> > 4. Digit: a
> 
> Tutto chiaro, però in inglese si dice "type" all'imperativo.
@rdipardo
Grazie, ho corretto...

**Comment by Jeankree** [comment]
Thank you guys! While waiting for the next official update, I locally modified my language files as indicated in update #15699 and it works now fine!
