### ISSUE TITLE
Plugin Manager does not show any installable plugins. 

### ISSUE THREAD

**Issue by aodpi** [notepad-plus-plus/notepad-plus-plus#1570]
I've installed the latest version of Notepad++ and after I open up the plugin manager to browse, there are no plugins to install. There is only the list of installed plugins. :cry:

**Comment by ClaudiaFrank** [comment]
Is this still the case?
Plugin Manager needs to download the file, so it could happen when there is a network issue
or sourceforge (as hoster) has a problem that you encounter such issue.

**Comment by aodpi** [comment]
Now it works fine. I did not have any network issues though.

**Comment by ClaudiaFrank** [comment]
As said, it might be that sourceforge as a hoster had problem ( this isn't unusual, it happens from time to time). To be honest, I don't think that there is a general issue, I would expect much more reports
if this would be the case. Do you think it's ok if you close the issue?

**Comment by aodpi** [comment]
Yes, sure.
