### ISSUE TITLE
[BUG] The default .toml syntax highlighter does nothing

### ISSUE THREAD

**Issue by walkersw** [notepad-plus-plus/notepad-plus-plus#15714]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description of the Issue

notepad++ has a built-in .toml syntax highlighter, but it does nothing.  Yes, I know there are a couple 3rd party toml.xml files I can download.  But I can only put those in as a user-defined language.  Every time I open notepad++, I have to manually select my user-defined .toml language.  I guess because there is a built-in .toml, it always defaults to that first.

### Steps To Reproduce

1.  Just open any .toml file and you will see it does nothing.
2.  
3.  

### Current Behavior

default .toml syntax highlighting does nothing.

### Expected Behavior

It should highlight stuff in a .toml file.

### Debug Information

```shell
Notepad++ v8.7   (64-bit)
Build time : Sep 17 2024 - 17:06:31
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
Periodic Backup : ON
OS Name : Windows 10 Pro for Workstations (64-bit)
OS Version : 22H2
OS Build : 19045.5011
Current ANSI codepage : 1252
Plugins : 
    mimeTools (3.1)
    NppConverter (4.6)
    NppExport (0.4)
```

**Comment by pryrt** [comment]
It works for me:
![image](https://github.com/user-attachments/assets/d9b97113-574d-4d17-8543-96ee45601ed8)

I am assuming you updated from an older revision of Notepad++ (that came before v8.7 when TOML was added).  If so, your `stylers.xml` will _not_ be overwritten to include the style definitions necessary to make TOML properly syntax highlight.    You will want to read the User Manual section on [Keeping Stylers and Themes up-to-date](https://npp-user-manual.org/docs/themes/#keeping-stylersthemes-up-to-date) for the details.  

It can be tedious to update all possible languages, but if all you care about updating is TOML, and don't care about other built-in languages that might need updating, then you can exit all copies Notepad++ and open just one (to make sure there are no unsaved GUI changes), open `%AppData%\Notepad++\stylers.xml` and `c:\program files\notepad++\stylers.model.xml`, copy the `<LexerType name="toml" desc="TOML" ext="">...</LexerType>` from `stylers.model.xml` and paste it in `stylers.xml`.  Save `stylers.xml` and exit Notepad++; now the next time you run Notepad++, TOML files should be properly syntax highlighted.
