### ISSUE TITLE
[BUG] Customized Find status msg colors are not remembered trough the sessions

### ISSUE THREAD

**Issue by alankilborn** [notepad-plus-plus/notepad-plus-plus#15724]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description of the Issue

Using Style Configurator to modify Find Status Message colors does work. However, the modified colors cannot be remembered through the sessions. 

Ref:
https://community.notepad-plus-plus.org/topic/26063/how-to-change-the-color-of-the-text-in-the-search-window-when-calculating-replacing

### Steps To Reproduce

1. Using Style Configurator to modify Find Status Message colors.
2. Observe Find dialog messages' colors have changed.
3. Quit Notepad++ then relauch it.
4. Open Find dialog and do some search to see Messages' colors.

### Current Behavior

The old colors are restored.

### Expected Behavior

The new colors persist.

### Debug Information

```shell
Notepad++ v8.7   (64-bit)
Build time : Sep 17 2024 - 17:06:31
Path : C:\NotepadPlusPlus\Misc\_NoBackup\Releases\npp.8.7\npp.8.7.portable.x64\notepad++.exe
Command Line : -titleAdd="8.7 64-bit" -multiInst
Admin mode : OFF
Local Conf mode : ON
Cloud Config : OFF
Periodic Backup : ON
OS Name : Windows 11 Pro (64-bit)
OS Version : 23H2
OS Build : 22631.4317
Current ANSI codepage : 1252
Plugins : 
    mimeTools (3.1)
    NppConverter (4.6)
    NppExport (0.4)
    PythonScript (2)
```

**Comment by donho** [comment]
@alankilborn 
Sorry for modifying the issue you created. Just trying to make it more accurate, because it'll be referenced in the change log.
