### ISSUE TITLE
[BUG] CTRL-G offends me.

### ISSUE THREAD

**Issue by cor-of-org** [notepad-plus-plus/notepad-plus-plus#15727]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description of the Issue

I hit Ctrl+G, to search for a line number. I have two options:

a) Go.

b) I'm going nowhere.

I realise that option b) may have seemed funny to you; as a developer; at some point, but I find it deeply offensive every time I need search by line number, which I usually avoid because of your offensive "humour".

Please remove this "humour" and do a proper, descriptive title, instead.

### Steps To Reproduce

1.  
2.  
3.  
Ctrl+G (Goto line number)

### Current Behavior

|Some teenage joke that is not funny.

### Expected Behavior

A proper, descriptive, non-offensive title like, "cancel".

You know, like every other cancel button on the planet.

### Debug Information

```shell
N/A
```

### Anything else?

I hit Ctrl+G, to search for a line number. I have two options:

a) Go.

b) I'm going nowhere.

I realise that option b) may have seemed funny to you; as a developer; at some point, but I find it deeply offensive every time I need search by line number, which I usually avoid because of your offensive "humour".

Please remove this "humour" and do a proper, descriptive title, instead.

**Comment by alankilborn** [comment]
>offends

Offends?!  Perhaps someone needs to "lighten up".

---

Workaround:

* Edit `english.xml` in the `localization` folder of Notepad++
* Find the text `I'm going nowhere` in the file
* Replace with text you like better, e.g. `Cancel`
* Save
* Go to _Settings_ > _Preferences..._ > _General_ and for the _Localization_ dropdown, drop it down and reselect `English`
