### ISSUE TITLE
[BUG] <title>Error when search / searching with "In the selection" option selected

### ISSUE THREAD

**Issue by renezito** [notepad-plus-plus/notepad-plus-plus#15737]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description of the Issue

When I'm searching with the option "In the selection" notepad++ search in all the document.  I don't know when it started with the problem, but I remember that before when I searched for some text with the "In selection" option enabled, that filter was respected.

### Steps To Reproduce

1.  type 2 phrases separated by lines.
2. In one phrase enter a word that not exists in the other phrase.
3. Select the prase that don't have the word you will search.
4.  Ctr+F and type the word to seach 
5.  Check "In the selection" and search
6. The app found the word BUT not in the selected text.

### Current Behavior

It search in all text, no only in the selected text.

### Expected Behavior

It must search only inthe selected text.

### Debug Information

```shell
Notepad++ v8.7   (64-bit)
Build time : Sep 17 2024 - 17:06:31
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : "C:\Program Files\Notepad++\change.log" 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
Periodic Backup : ON
OS Name : Windows 10 Pro (64-bit)
OS Version : 22H2
OS Build : 19045.5011
Current ANSI codepage : 1252
Plugins : 
    ComparePlugin (2.0.2)
    mimeTools (3.1)
    NppConverter (4.6)
    NppExport (0.4)
```

### Anything else?

https://drive.google.com/file/d/1tdX0ukmIs4QxW-ELvBNDmEiqX1EnaWcY/view?usp=drive_link

**Comment by alankilborn** [comment]
>5. Check "In the selection" and search

What "search" do you mean? Please be clear...
If you mean a _Find Next_ search then note the following:

![image](https://github.com/user-attachments/assets/d2e9c2c0-84fe-4437-8023-f40e642cf49a)

See the group-box pointed at by the red arrows?
This group-box contains only _In selection_, _Count_ and _Find All in Current Document_.
This means that _In selection_ only applies to the _Count_ and _Find All in Current Document_ commands (not _Find Next_).

**Comment by renezito** [comment]
Wow, yes u r right.  I didn't note that in was in a group-box and the "Find next" button doesn't interact with the "In selection" check box.  Thanks very much for ur answer and help =)

**Comment by alankilborn** [comment]
Please close.

**Comment by renezito** [comment]
There was no error, my mistake.
