### ISSUE TITLE
Upgrade in background

### ISSUE THREAD

**Issue by Brimstedt** [notepad-plus-plus/notepad-plus-plus#1573]
It would be nice if the upgrade process was more automated, right now it intertupts workflow (the upgrade dialog appears when you open some file to edit..)

It would be nicer if there was an option that checks for new versions in the background, downloads automatically and installs it into a subdir of the notepad++ main installation directory.

After that, show a dialog (or pehaps something less intrusive?) to restart with the new version.
The dialog could have options "restart now", "dont restart", "restart when losing focus"

br

**Comment by donho** [comment]
For some divers reasons, people (including me) don't want have silent background update for a text/code editor (not like for browser). OTOH, the updates are not triggered so often, so I think it's bearable and reasonable to keep its current behaviour.

**Comment by Teslafly** [comment]
an option that is disabled by default would be nice.

**Comment by Oylex** [comment]
Indeed, even as disabled by default.
Or maybe an option to prompt only for minor version and not every patch version.
Or an option to replace the update pop up on start by some icon in the toolbar like an upgrade arrow that you can click whenever you feel like updating, it would just be less intrusive
