### ISSUE TITLE
[Feature request] Add an option to store only desired tabs for next launch

### ISSUE THREAD

**Issue by walraymmo** [notepad-plus-plus/notepad-plus-plus#15732]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Description of the Issue

This is more of a life quality improvement feature that I would like to suggest more than actually request.

There is an issue I have been facing for a lot of time. I do want my tabs to be stored for next launch but I use Notepad++ to do a lot of things, so in the end I end up with lots and lots of "temporary" tabs that I have to close.

### Describe the solution you'd like.

It would be nice to be able to "_pin_" tabs to be stored and an option that says something like "_Restore only pinned tabs_" under "Remember current session for next launch" in preferences so that when you launch Notepad++ next time only those "_pinned_" tabs would be restored.

### Debug Information

```shell
Notepad++ v8.6.8   (64-bit)
Build time : Jun  4 2024 - 00:30:00
Path : D:\Miscelaneo\Editores\Notepad++\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : ON
Cloud Config : OFF
Periodic Backup : OFF
OS Name : Windows 10 Home (64-bit)
OS Version : 22H2
OS Build : 19045.5011
Current ANSI codepage : 1252
Plugins : 
    ComparePlus (1.1)
    mimeTools (3.1)
    NppConverter (4.6)
    NppExport (0.4)
```

**Comment by alankilborn** [comment]
Close this and add the specifics of this request to https://github.com/notepad-plus-plus/notepad-plus-plus/issues/5786

**Comment by donho** [comment]
Use https://github.com/notepad-plus-plus/notepad-plus-plus/commit/ce58b424bdeec3616943f9ea8cd257f66700c3c0
(This feature can be extended)
