### ISSUE TITLE
[BUG] Plugin admin action to install/update/remove are always disabled

### ISSUE THREAD

**Issue by castortech** [notepad-plus-plus/notepad-plus-plus#15735]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description of the Issue

In the plugin admin, whatever tab that I'm on, the action buttons in the top right (install, update or remove) are always disabled.

I even tried launching NPP as administrator and got the same behavior.

![image](https://github.com/user-attachments/assets/5b9480bf-5ff6-4b88-8532-83233dec0015)

### Steps To Reproduce

1.  Open Plugin admin
2.  Select any plugin
3.  Notice that action button is never active

### Current Behavior

Buttons are disabled

### Expected Behavior

Being able to use action button

### Debug Information

```shell
Notepad++ v8.7   (64-bit)
Build time : Sep 17 2024 - 17:06:31
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : 
Admin mode : ON
Local Conf mode : OFF
Cloud Config : OFF
Periodic Backup : ON
OS Name : Windows 10 Home (64-bit)
OS Version : 22H2
OS Build : 19045.5011
Current ANSI codepage : 1252
Plugins : 
    ComparePlugin (2.0.2)
    HexEditor (0.9.12)
    JSMinNPP (1.2205)
    MarkdownViewerPlusPlus (0.8.2)
    mimeTools (3.1)
    NppConverter (4.6)
    NppExport (0.4)
    NPPJSONViewer (1.40)
    urlPlugin (1.2)
    XMLTools (3.1.1.13)
```

**Comment by alankilborn** [comment]
Put a check in the checkbox for a specific plugin?
