### ISSUE TITLE
Taiwan is Chinese, no doubt about it!

### ISSUE THREAD

**Issue by jiangkun2015** [notepad-plus-plus/notepad-plus-plus#15747]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description of the Issue

Notepadd++ is a great product to use, if the author is not sick.

### Describe the solution you'd like.

Taiwan is Chinese, no doubt about it!

### Debug Information

```shell
Notepad++ v8.7   (64-bit)
Build time : Sep 17 2024 - 17:06:31
Path : D:\Program Files\Notepad++\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
Periodic Backup : ON
Current ANSI codepage : 936
```

**Comment by softmgr** [comment]
Did you eat melamine and ruin your brain?

**Comment by xiyaowong** [comment]
# 想不到台独猖狂到这种地步，一群数典忘祖的东西，台湾岛是中国领土，日遗绿蛆要建国请另寻他处。
![image](https://github.com/user-attachments/assets/042ddd36-382d-47a9-b84f-fd72aae2165e)

**Comment by softmgr** [comment]
It seems that bypassing the Great Firewall does not enhance intelligence or cognition.

**Comment by xomx** [comment]
@softmgr 
It's not about intelligence here, they just feel insecure so they're using such screams to make themselves sure they are right...

Anyway, I do not see a problem with the issue statement `Taiwan is Chinese, no doubt about it!` - they are right, 
Taiwan IS Republic of China (R.O.C). They're just unlucky to have that pesky province called P.R.C.

**Comment by LanYebo** [comment]
> It seems that bypassing the Great Firewall does not enhance intelligence or cognition.

长城防火墙和智商还有认知有什么关系？他只是用来保护大部分中国人不要被你这样的国外蠢货蠢到，少部分人出来也是抱着看奇葩的心态看你们的懂吗，身为蛮夷你就要有蛮夷的觉悟，姿态不要太高
