### ISSUE TITLE
[BUG] Narrow non-breaking space is badly displayed

### ISSUE THREAD

**Issue by NicolasDelaporte** [notepad-plus-plus/notepad-plus-plus#15748]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description of the Issue

The narrow non-breaking space is displayed as a square box instead of a space.

### Steps To Reproduce

Enter a narrow breaking space in the editor view of Notepad++ (shift+space on a BÉPO keyboard, or copy paste it from here: “ ”).

### Current Behavior

The narrow non-breaking space is displayed as a square box.
![{136B6868-F100-4897-8F22-707B5E130BFC}](https://github.com/user-attachments/assets/8ef73ca7-b2f0-4855-85c1-4b934259503b)

When displaying all characters is enabled, it is displayed as NNBSP.
![{720A7A42-E22A-4ECE-8098-DBBEBE339239}](https://github.com/user-attachments/assets/828d899a-a7f5-4088-bfa6-4f02b39436e4)

### Expected Behavior

The narrow non-breaking space should be displayed as a narrow space.
When displaying all characters is enabled, it would be better to use a single character representation

### Debug Information

```shell
Notepad++ v8.6.8   (64-bit)
Build time : Jun  4 2024 - 00:30:00
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
Periodic Backup : OFF
OS Name : Windows 11 Enterprise (64-bit)
OS Version : 23H2
OS Build : 22631.4317
Current ANSI codepage : 1252
Plugins : 
    AutoSave (2)
    ComparePlugin (2.0.2)
    DSpellCheck (1.5)
    Explorer (1.9.9)
    HexEditor (0.9.12)
    mimeTools (3.1)
    NppConverter (4.6)
    NppExport (0.4)
    XMLTools (3.1.1.13)
```

### Anything else?

See wikipedia article [Non-breaking space/Width variation](https://en.wikipedia.org/wiki/Non-breaking_space#Width_variation) for more details about narrow non-breaking space.

**Comment by alankilborn** [comment]
It seems to work reasonably well for me (in 8.7); line 27 in this example has the NNBSP, between the two `a` characters:

![image](https://github.com/user-attachments/assets/294cca3e-a30a-42d2-9dd5-55d71e828715)

Line 28 has a plain old U+20 space between the two `a` characters, for comparison.

What's your N++ pref. setting for "DirectWrite"?

**Comment by NicolasDelaporte** [comment]
“Use DirectWrite” was not enabled.
I have enabled it, the NNBSP is now displayed properly, thanks.

**Comment by alankilborn** [comment]
Please close.
