### ISSUE TITLE
[BUG] Wrong link in release note of 8.7.1

### ISSUE THREAD

**Issue by Korb** [notepad-plus-plus/notepad-plus-plus#15758]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description of the Issue

https://github.com/notepad-plus-plus/notepad-plus-plus/releases/tag/v8.7.1
wrong link in the release note to
https://notepad-plus-plus.org/news/v871-released/
instead of
???

### Steps To Reproduce

1.  Go to https://github.com/notepad-plus-plus/notepad-plus-plus/releases/tag/v8.7.1
2.  Click https://notepad-plus-plus.org/news/v871-released/ link.

### Current Behavior

> Oops, looks like the page is lost.
> This is not a fault, just an accident that was not intentional.

### Expected Behavior

List of Notepad++ 8.7.1 features and fixed bugs.

### Debug Information

```shell
------- Forwarded Message -------
From: Don HO
Date: On Monday, November 4th, 2024 at 16:51
Subject: [notepad-plus-plus/notepad-plus-plus] Release v8.7.1 - Notepad++ release 8.7.1

> Notepad++ release 8.7.1
> Repository: notepad-plus-plus/notepad-plus-plus · Tag: v8.7.1 · Commit: ba3b457 · Released by: donho
>
> Release note:
> https://notepad-plus-plus.org/news/v871-released/
>
> SHA256 Digest
> 6ba9b88ade18a9b6a40cb984b783acbccd864a3290c68d1c8fe6bac918a3bdf2  npp.8.7.1.Installer.arm64.exe
> ...
```

**Comment by vlakoff** [comment]
There is no issue, the link is working now.

That's simply because the official website is updated a bit later than the release on GitHub.
