### ISSUE TITLE
Settings in Windows Registry

### ISSUE THREAD

**Issue by JayBeeDe** [notepad-plus-plus/notepad-plus-plus#1576]
Hi,

It seems that Notepad++ settings are stored in the user profile in XML files. Is it possible to store some important system settings - such as Updates and *_Plugins *_management/download - in the Windows Registry (HKLM), so that I can create (and share to the community) the ADMX templates files in order to control theses important settings via GPO? These will be a crucial feature for IT Administrator. And Notepad++ could be deployed over hundred of Windows Machines in corporate environment!

**Comment by donho** [comment]
Even though very few settings of Notepad++ are stored in Windows Registry, Notepad++ settings policy is avoid Registry to make Notepad++ as portable as possible.

**Comment by edsonjt81** [comment]
temos o arquivo ADMX pra importar no M.Intune?
