### ISSUE TITLE
[Feature request] Shortcut to jump to the position where the last edit was done

### ISSUE THREAD

**Issue by paphko** [notepad-plus-plus/notepad-plus-plus#15768]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description of the Issue

In Eclipse, there is an [awesome keybord shortcut](https://www.vogella.com/tutorials/EclipseShortcuts/article.html#navigation-and-text-selection): **Ctrl + Q**

It jumps back to the editor tab and location in it _where the last edit was done_.

It's really useful and boosts productivity, e.g. when writing something, then looking up something in the same or any other open tabs, then pressing that shortcut, and you can immediately continue writing. 😃 

### Describe the solution you'd like.

Add a new keyboard shortcut (maybe also **Ctrl + Q**), e.g. titled: _"Go to the position where the last edit was done"_

### Debug Information

```shell
Notepad++ v8.7   (64-bit)
Build time : Sep 17 2024 - 17:06:31
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : "D:\readme.txt"
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
Periodic Backup : ON
OS Name : Windows 11 Pro (64-bit)
OS Version : 22H2
OS Build : 22621.4169
Current ANSI codepage : 1252
Plugins : 
    ComparePlugin (2.0.2)
    JsonTools (8)
    mimeTools (3.1)
    NppConverter (4.6)
    NppExport (0.4)
    XMLTools (3.1.1.13)
```

**Comment by xomx** [comment]
> It jumps back to the editor tab and location in it _where the last edit was done_.

For the active N++ tab you can create & use such shortcut via menu > Settings > Shortcut Mapper... > Main menu tab > "Go to Previous Change" Search-menu command:

![npp-goto-prev-change-shortcut](https://github.com/user-attachments/assets/9ba6af82-c0f5-431b-ae85-57d53c0ac058)

However, this will not help you in a multi-tab situation where you would like to find the very last edit in one from the currently inactive tabs (if this is what you expect to have).
