### ISSUE TITLE
Website https://notepad-plus-plus.org - The connection has timed out

### ISSUE THREAD

**Issue by mtumanov** [notepad-plus-plus/notepad-plus-plus#15770]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description of the Issue

Good day.

The website is in timeout state and don't know where else to report this.
An error occurred during a connection to https://notepad-plus-plus.org
Thanks.

### Steps To Reproduce

1.  Try to open https://notepad-plus-plus.org in any browser.
2.  
3.

### Current Behavior

--- Firefox
The connection has timed out

An error occurred during a connection to notepad-plus-plus.org. 

---- Google Chrome
This site can’t be reached
notepad-plus-plus.org took too long to respond.
ERR_CONNECTION_TIMED_OUT

### Expected Behavior

The site should open.

### Debug Information

```shell
ERR_CONNECTION_TIMED_OUT
```

**Comment by jovibor** [comment]
Try any proxy.
The site is most likely blocked on the provider side.

**Comment by mtumanov** [comment]
At now moment the site https://notepad-plus-plus.org opens via TOR browser. 
Yesterday it did not open.

Thanks, I will try to use proxy servers to access the site and for updates.

**Comment by mtumanov** [comment]
At now moment the site https://notepad-plus-plus.org/ opens via TOR browser.
Yesterday it did not open.

Thanks, I will try to use proxy servers to access the site and for updates.

**Comment by censorliber** [comment]
[Chttps://community.notepad-plus-plus.org/topic/26359/the-notepad-website-is-blocked-in-russia](https://community.notepad-plus-plus.org/topic/26359/the-notepad-website-is-blocked-in-russia)

**Comment by andry81** [comment]
> The site is most likely blocked on the provider side.

it is blocked outside too

**Comment by mtumanov** [comment]
> it is blocked outside too
At now moment the site https://notepad-plus-plus.org/ is not blocked for me in TOR browser via Netherlands in TOR circuit.
I can open this site.
