### ISSUE TITLE
[Feature request] <title> Press the CTRL key and drag the selected text to do copy operation is so inconvenient

### ISSUE THREAD

**Issue by timeshotmail** [notepad-plus-plus/notepad-plus-plus#15778]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description of the Issue

In the earlier Notepad++ version, I would like to copy the text,  I can keep the CTL key pressed, and then drag the selected text to do multi-copies. 
But now the newer version can't do it.

### Describe the solution you'd like.

I would like that do the multi-copies by mouse draging selected text during the CTL keys keep be pressing. 
Implement this feature like as in the earlier version.

### Debug Information

```shell
Notepad++ v8.7.1   (64-bit)
Build time : Oct 31 2024 - 00:48:56
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : "C:\Program Files\Notepad++\change.log" 
Admin mode : ON
Local Conf mode : OFF
Cloud Config : OFF
Periodic Backup : OFF
OS Name : Windows 11 Pro (64-bit)
OS Version : 23H2
OS Build : 22631.4317
Current ANSI codepage : 936
Plugins : 
    HexEditor (0.9.12)
    mimeTools (3.1)
    NppConverter (4.6)
    NppExport (0.4)
    NppFTP (0.29.10)
```

**Comment by xomx** [comment]
https://github.com/notepad-plus-plus/notepad-plus-plus/issues/14774#issuecomment-1959385497

**Comment by alankilborn** [comment]
This issue may now be closed.

**Comment by timeshotmail** [comment]
@xomx 
Thanks so much for your info.
I think I can close this topic.

**Comment by timeshotmail** [comment]
@xomx 
Thanks so much for your info.
I think I can close this topic.
