### ISSUE TITLE
[Feature request] Added possibility to go to system tray when closing and minimising the program

### ISSUE THREAD

**Issue by NEKolev** [notepad-plus-plus/notepad-plus-plus#15771]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description of the Issue

The new ability to have the program go to the system tray when closing is great, but it would be very useful if the ability to both minimize and close the program to go to the system tray was also added. Currently it has to look at both places in the ribbon (when minimizing) or in the system tray (when closed) and it's confusing.

### Describe the solution you'd like.

Add a fourth option that combines minimize and close.

**'minimize and close to'** system tray
![image](https://github.com/user-attachments/assets/f81c8450-6c7b-4196-ac93-825473a55ab8)

### Debug Information

```shell
Notepad++ v8.7.1   (64-bit)
Build time : Oct 31 2024 - 00:48:56
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line :
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
Periodic Backup : ON
OS Name : Windows 11 Enterprise (64-bit)
OS Version : 23H2
OS Build : 22631.4391
Current ANSI codepage : 1251
Plugins : 
    ComparePlus (1.2)
    CSVLint (0.4.6.7)
    HTMLTag (1.4.4)
    mimeTools (3.1)
    NppConverter (4.6)
    NppExport (0.4)
    NPPJSONViewer (2.0.7)
    XMLTools (3.1.1.13)
```

**Comment by ccazho1** [comment]
I'm interested in working on this!
