### ISSUE TITLE
document list tooltip bug

### ISSUE THREAD

**Issue by bkisdi** [notepad-plus-plus/notepad-plus-plus#1577]
When the file name in the document list box is too long, the full name is shown in a tooltip.
When I Save As... a document with a new name, the document list box is updated, but the tooltip is not!

![image](https://cloud.githubusercontent.com/assets/4957749/13503042/bdb17260-e16d-11e5-91ff-e4b90fe0f745.png)

(The current name is set_doc_group_rights, the previous name was set_user_group, the mouse pointer is over the gray line.)

Version 6.7.8.2

**Comment by donho** [comment]
cannot reproduce in v7.6.6.

**Comment by bkisdi** [comment]
Yes, it is fixed now. Thanks.
