### ISSUE TITLE
[BUG] Issue with language selection

### ISSUE THREAD

**Issue by tbayart** [notepad-plus-plus/notepad-plus-plus#15789]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description of the Issue

Since I updated NPP to 8.7 the language selection choose TOML when I open .Net Framework application config file
![Annotation 2024-11-12 115255](https://github.com/user-attachments/assets/da4bb45f-bd5f-452d-a959-7a10b6135fda)

### Steps To Reproduce

1.  create a new file and paste the following content inside
```
<?xml version="1.0" encoding="utf-8"?>
<configuration>
</configuration>
```
2.  save the file with .config extension (i.e: test.config)
3.  close the file
4.  open the file by double clicking it
5.  the file open badly highlighted

note : does not happen when you open the file using the NPP menu File->Open

### Current Behavior

The language automatically selected is wrong language TOML

### Expected Behavior

The language should be XML or at least NONE

### Debug Information

```shell
Notepad++ v8.7   (64-bit)
Build time : Sep 17 2024 - 17:06:31
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : "C:\temp\test.config"
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
Periodic Backup : OFF
OS Name : Windows 10 Pro N (64-bit)
OS Version : 22H2
OS Build : 19045.5011
Current ANSI codepage : 1252
Plugins : 
    mimeTools (3.1)
    NppConverter (4.6)
    NppExport (0.4)
```

**Comment by pankajk280** [comment]
Hi @tbayart, I have investigated your query and don't see any issues at the moment. Could you please update your Notepad++ version to the latest one and check if the issue persists?
