### ISSUE TITLE
[BUG] Dark Mode: Active Tab Text / Inactive Tabs styles not working

### ISSUE THREAD

**Issue by pryrt** [notepad-plus-plus/notepad-plus-plus#15797]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description of the Issue

In light mode, the **Global Styles > Active tab text** foreground and **Inactive tabs** foreground and background properly color the active tab text and inactive tabs foreground and background.  However, if I change to Dark Mode and set those same styles, the tab colors don't change.

### Steps To Reproduce

1.  Unzip new portable v8.7.1
2.  Open a total of 4 tabs, two in primary view, two in secondary view (so all types of tabs are visible)
3.  **Settings > Style Configurator > Global Styles**
    - **Active tab text** foreground to peach
    - **Inactive tabs** foreground to yellow
    - **Inactive tabs** background to burgandy 
    - See that tab colors change when in Light Mode
    - **Cancel**
4. **Settings > Preferences > Dark Mode** set to **Dark Mode**
5.  **Settings > Style Configurator > Global Styles**
    - **Active tab text** foreground to peach
    - **Inactive tabs** foreground to yellow
    - **Inactive tabs** background to burgandy 
    - See that tab colors do not change when in Dark Mode

### Current Behavior

In Dark Mode, setting those styles doesn't change the tab colors.  In Light Mode it does.

**Light**:
![image](https://github.com/user-attachments/assets/bb4c91f7-76af-4ab3-b7ef-ae139faeabcf)

**Dark**:
![image](https://github.com/user-attachments/assets/bbdc0189-3ffe-4690-984e-b995b6e76148)

### Expected Behavior

It should change the colors both in Light Mode and in Dark Mode

### Debug Information

```shell
Notepad++ v8.7.1   (64-bit)
Build time : Oct 31 2024 - 00:48:56
Path : C:\usr\local\apps\npp\npp.8.7.1.portable.x64\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : ON
Cloud Config : OFF
Periodic Backup : ON
OS Name : Windows 10 Enterprise (64-bit)
OS Version : 22H2
OS Build : 19045.5011
Current ANSI codepage : 1252
Plugins : 
    mimeTools (3.1)
    NppConverter (4.6)
    NppExport (0.4)
```

### Anything else?

(one other confirmation -- no screenshot: when in Light Mode, but using Theme=DarkModeDefault, it does work as expected.  So it's actually being in Dark Mode that makes those two styles not do anything.)

**Comment by ozone10** [comment]
@pryrt 
not an issue. There are two hidden settings in config.xml `<GUIConfig name="DarkMode" ... darkTabUseTheme="no" lightTabUseTheme="yes" ... />`

In light mode there is no issue as those themes were written when there was no dark mode.
But in dark mode this could lead to some visual inconsistency (dark text on dark background) for some users, which is why n++ dark mode in default setting does not use these colors.

**Comment by pryrt** [comment]
@ozone10 : I apparently didn't notice that [change in v8.4.8](https://github.com/notepad-plus-plus/notepad-plus-plus/wiki/Changes#848), so didn't know to research and document it.  I'm going to work on documenting those power-user settings, and will ping you when I have a PR ready for the User Manual, just to make sure I describe them correctly.
