### ISSUE TITLE
Can't modify auto-completion from n-th character's value

### ISSUE THREAD

**Issue by SamratAlamgir** [notepad-plus-plus/notepad-plus-plus#158]
The default value for auto-completion from n-th character is 1 and it shows the valid value is 1 to 9.
But it doesn't take any valid value and remains empty when trying to modify it.

![bug auto completion](https://cloud.githubusercontent.com/assets/12727437/7955182/f8455340-09f7-11e5-9003-0b7ad5e55bf0.PNG)

**Comment by smuuf** [comment]
I have the same issue on Windows 8.1 with DPI scaling being set higher than the default 100%.

**Comment by ariccio** [comment]
For reference, the culprit dialog is a `ValueDlg`, and is created in `preferenceDlg.cpp`, at line 2577:

https://github.com/notepad-plus-plus/notepad-plus-plus/blob/246c8bd1684f89d1e3c87a77148bc51e6555f83c/PowerEditor/src/WinControls/Preference/preferenceDlg.cpp#L2577

**Comment by ariccio** [comment]
...and the value that the user typed is returned in `lesDlgs.cpp`, at line 107: https://github.com/notepad-plus-plus/notepad-plus-plus/blob/246c8bd1684f89d1e3c87a77148bc51e6555f83c/PowerEditor/src/lesDlgs.cpp#L107

**Comment by schoerlock** [comment]
I have the same issue. Changing the value by editing the auto-completion tag in the config.xml file works, however. (NPP needs to be closed when saving the file, otherwise it will overwrite it on exit.)

**Comment by MetaChuh** [comment]
closed due to: not reproducible with 7.6.6 on windows 10 (150%)
