### ISSUE TITLE
[BUG] "Copy Selected Line(s)" in Search-results sometimes has unexpected behavior

### ISSUE THREAD

**Issue by alankilborn** [notepad-plus-plus/notepad-plus-plus#15803]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description of the Issue

(Some would see this as a Feature Request; I see it as a Bug because unexpected behavior is obtained)

---

Sometimes I am sloppy with selecting text when using _Copy Selected Lines_, example:

![image](https://github.com/user-attachments/assets/3e585889-78a0-4946-8857-46ba92634a2b)

My intent here is to put exactly this into the clipboard:

```txt
01 : The quick brown fox jumped over the lazy dogs.
01a : The quick brown dog jumped over the lazy foxes.
```

But after I execute _Copy Selected Line(s)_ I obtain (in the clipboard):

```txt
01 : The quick brown fox jumped over the lazy dogs.
01a : The quick brown dog jumped over the lazy foxes.
02 : The quick brown fox jumped over the lazy dogs.
02a : The quick brown dog jumped over the lazy foxes.
```

### Steps To Reproduce

1.  See Description above
2.  
3.  

### Current Behavior

Less than obvious copying behavior.

### Expected Behavior

Better behavior would be to only copy the "Line" data from lines touched by the stream selection the user has made.

### Debug Information

```shell
Notepad++ v8.7   (64-bit)
Build time : Sep 17 2024 - 17:06:31
Path : C:\NotepadPlusPlus\Misc\_NoBackup\Releases\npp.8.7\npp.8.7.portable.x64\notepad++.exe
Command Line : -titleAdd="8.7 64-bit" -multiInst
Admin mode : OFF
Local Conf mode : ON
Cloud Config : OFF
Periodic Backup : ON
OS Name : Windows 11 Pro (64-bit)
OS Version : 23H2
OS Build : 22631.4317
Current ANSI codepage : 1252
Plugins : 
    mimeTools (3.1)
    NppConverter (4.6)
    NppExport (0.4)
    PythonScript (3.0.16)
```

### Anything else?

As a convenience functionality, if there is no selected text at time of right-click, and...
* ... the line right-clicked is a Pathname line, copy the data for all Line text hierarchically below that Pathname (until either the following Pathname -- or Search line -- is encountered)
* ... the line right-clicked is a Search line, copy the data for all Line text hierarchically below that Search line, for all Pathnames (until the following Search line is encountered)

**Comment by alankilborn** [comment]
Also, I believe the user manual description for existing `Copy Selected Line(s)` is poor/difficult, due to the way the feature currently works.
@pryrt , would making the proposed change described above result in more understandable documentation and clearer/simpler functionality for the user?

**Comment by pryrt** [comment]
> would making the proposed change described above result in more understandable documentation and clearer/simpler functionality for the user?

It would definitely be more intuitive for the user, and I would hope that the documentation would be able to make the updated behavior more clear than it currently explains the existing behavior..

**Comment by donho** [comment]
@alankilborn 
> Better behavior would be to only copy the "Line" data from lines touched by the stream selection the user has made.

"Better behavior" for the case you provided . However, there could be a lot more ways of selection - what are their "Better behavior" for you?

**Comment by alankilborn** [comment]
>there could be a lot more ways of selection - what are their "Better behavior" for you?

There really _aren't_ a lot more ways of selection in this case:

* multiple selections aren't allowed in _Search results_
* column block selection IS allowed, but it wouldn't change the "desired" behavior I've described:

![image](https://github.com/user-attachments/assets/6c05a3fc-84b3-44e5-bf8c-de3fad22048e)

would copy:

```txt
01a : The quick brown dog jumped over the lazy foxes.
02 : The quick brown fox jumped over the lazy dogs.
02a : The quick brown dog jumped over the lazy foxes.
```

I suppose I just have to go ahead with a PR and see/hope it gets accepted.

**Comment by donho** [comment]
@alankilborn 
> I suppose I just have to go ahead with a PR and see/hope it gets accepted.

No, please don't.

> You've describe the "Better behavior" for the case you provided. However, there could be a lot more ways of selection - what are their "Better behavior" for you?

What we need is a definition of behaviour with different selection, hence the question above.

"Walking on water and developing software from a specification are easy if both are frozen."

**Comment by alankilborn** [comment]
>No, please don't.

Oops, didn't see this until too late!  :-)
No big deal; minimal effort...

---

>What we need is a definition of behaviour with different selection

In my view, I've already defined that above.
If that's not acceptable, and Jesus doesn't step in to tell me what to do, I guess we have to live with the wacky behavior originally described in https://github.com/notepad-plus-plus/notepad-plus-plus/issues/15803#issue-2661857462

**Comment by donho** [comment]
@alankilborn 
What I was trying to say is, before coding anything, let's check the current behaviour on the whole "Copy Selected Lines" feature with the different selections.
I'll see what I can do about it.

**Comment by donho** [comment]
@alankilborn 
Not talking about column selection, the following selection with the command in question:

![image](https://github.com/user-attachments/assets/cfb975cc-a246-4a25-8dfc-57eb85b56b52)


is
```
3.1 A blue bird & a yellow snail
3.2 A blue bird & a yellow snail
3.3 A blue bird & a yellow snail
```

So if the behaviour of this issue is wrong, then the above behaviour is not correct neither.

**Comment by alankilborn** [comment]
> selection on single "path" line: `3 (3 hit`

>So if the behaviour of this issue is wrong, then the above behaviour is not correct neither.

In my PR code, I allowed that, because it doesn't bother me for it to work that way.

But we can change the PR code:

`if (_scintView.execute(SCI_GETSELECTIONEMPTY) || fromLine == toLine)`

to the simpler:

`if (_scintView.execute(SCI_GETSELECTIONEMPTY))`

**Comment by donho** [comment]
> But we can change the PR code:

My goal is to see every selection possibility and define the behaviour of each selection possibility from the users' aspect.
Once it's done, then we can do the coding part.

**Comment by alankilborn** [comment]
> My goal is to see every selection possibility and define the behaviour of each selection possibility from the users' aspect.

There is only single stream selection and column-block selection possible currently in _Search results_ text.
Are you implying that this is to be changed, presumably to add multiple stream selection capability?

**Comment by donho** [comment]
> Are you implying that this is to be changed, presumably to add multiple stream selection capability?

Not at all.

Please consider the following case:

**1**
![image](https://github.com/user-attachments/assets/cfb975cc-a246-4a25-8dfc-57eb85b56b52)
```
3.1 A blue bird & a yellow snail
3.2 A blue bird & a yellow snail
3.3 A blue bird & a yellow snail
```

**2**
![image](https://github.com/user-attachments/assets/883fde7d-4707-4e98-b8d3-63c84d8a055c)
```
2.1 A yellow bird & a blue snail
2.2 A yellow bird & a blue snail
2.3 A yellow bird & a blue snail
3.1 A blue bird & a yellow snail
3.2 A blue bird & a yellow snail
3.3 A blue bird & a yellow snail
```


**3**
![image](https://github.com/user-attachments/assets/8f9d65f7-3cb7-4153-bc56-106da900a9e7)
```
2.3 A yellow bird & a blue snail
3.1 A blue bird & a yellow snail
```

**4**
![image](https://github.com/user-attachments/assets/961d43a1-e9d9-482c-82b7-9ee0a2d46391)
```
2.1 A yellow bird & a blue snail
2.2 A yellow bird & a blue snail
2.3 A yellow bird & a blue snail
```

What I am trying to say is, some the copied results are confusing and not coherent in its current state. Instead of focusing on a single case for doing the fix, I prefer to have an overview on the feature, and define the coherent behaviour once for all.

**Comment by alankilborn** [comment]
>What I am trying to say is, some the copied results are confusing and not coherent in its current state.

Agree, that's why this issue was opened.

---

My comments on previous posting:

Case 1 - functions as desired
Case 2 - copies too much (I would desire only lines containing 2.1, 2.2, 2.3 be in the copied text)
Case 3 - functions as desired
Case 4 - functions as desired
Case 5 - functions as desired
Case 6 - copies too much (I would exclude line containing 3.3 from the resultant copy)
Case 7 - functions as desired

---

>Column selection will be ignored as the current state.

It could be, but it doesn't have to be.  It could simply act the same a stream selection touching the same lines would.

**Comment by alankilborn** [comment]
As this is discussed more and more... I'm wondering if this command wouldn't be better renamed as "Copy Content" or "Copy Line Content".  

When doing a normal copy, for example, the _Edit_ menu > _Copy_, the name isn't "Copy Selected", because something selected is implied.  So for purposes of this issue, isn't dropping "Selected" a good idea?

This would have the added benefit of avoiding the awkward `(s)` in _Copy Selected Line(s)_.

What is the thought about this?

**Comment by donho** [comment]
@alankilborn 
I've added 2 more cases **8** & **9**
Please update your comment:
https://github.com/notepad-plus-plus/notepad-plus-plus/issues/15803#issuecomment-2515580625

Please let me know if you find any case which is not covered.

**Comment by donho** [comment]
@alankilborn 
> It could be, but it doesn't have to be. It could simply act the same a stream selection touching the same lines would.

No, let's keep it simpler - I'm thinking of disabling column edit in search results if possible.

> As this is discussed more and more... I'm wondering if this command wouldn't be better renamed as "Copy Content" or "Copy Line Content".

For me the current command labels "Copy Selected Line(s)" & "Copy Selected Pathname(s)" are clear & concise. Rename both commands are not necessary IMO.

**Comment by alankilborn** [comment]
Case 8 - copies too much (I would desire only lines containing 3.1 and 3.2 be in the copied text)
Case 9 - copies too much (I would desire only lines containing 2.1 and 2.2 be in the copied text)

I don't see a functional different between case 8 and 9.

**Comment by alankilborn** [comment]
The algorithm I seem to prefer is:

* if selection/caret intersects any `Line` line(s), copy only the intersected `Line` line(s)
* elif selection/caret is on a single line, and that line is a  "path" line, copy all of the child `Line` line(s) under that path line
* elif selection/caret is on a single line, and that line is a  "Search" line, copy all of the child `Line` lines(s) under that search tree (which could contain many "path" subtrees, all with `Line` line(s) that would be copied)

**Comment by donho** [comment]
@alankilborn 
> The algorithm I seem to prefer is...

Yes, agree. Now I would say you can reopen your PR and implement the behaviour you have defined.

**Comment by alankilborn** [comment]
@donho said:

>you can reopen your PR and implement the behaviour you have defined

OK, PR reopened.
No new code to push as the previous code agrees with us as to the desired behavior.  :-)
