### ISSUE TITLE
Possible solution to handle the doLocalConf.xml on Windows x64

### ISSUE THREAD

**Issue by xcabur1** [notepad-plus-plus/notepad-plus-plus#1582]
I used the config.xml and dolocalconf.xml in %programfiles% on windows XP to define settings for all users on the same computer. I deploy this two files to all computers on our Company. On the basis of missing write access to %programfiles% for non-administrators,  all users received the same config and could not change it. it was a great solution. After upgrading on Windows 8 x64 and install Notepad++ in program files (x86) (default), it doesn't work anymore.
As described [here  ](https://notepad-plus-plus.org/download/v5.8.3.html) "12.Due to UAC issue, doLocalConf.xml is ignored under vista and windows 7, if Notepad++ is installed in "Program files" directory." On 64-bit operatingsystem "program files" means "program files (x86)". Notepad++ ignores the local config due to lack of write access to "Program files (x86)" Directory. If we install notepad++ into a other directory like "programm files" - the x64 one - the local conf works. But a 32-Bit application in the 64-Bit application directory is not proper. I don't understand this behaviour, because a non-Administrator has no Access to both directories (program files (x86) and program files). I think there are two user friendly and more professional solutions for this issue:

Solutions 1 - i think the easy one.
- Don't ignore the dolocalconf.xml in program files (x86) 
- Notepad++ can still read the config.xml
- If a non-Administrator changes settings through the GUI and a write-access-error to config.xml occurs, ignore the error or show a error message. No changes happens and the user still use the configuration defined by Administrator. A administrator can manually run notepad++.exe as elevated Administrator and changes the settings.
- that's it

Solutions 2 -  the advanced solution
- Don't ignore the dolocalconf.xml in program files (x86) 
- Notepad++ can still read the config.xml
- If a non-Administrator changes the settings through the GUI and a write-access-error to config.xml occurs, notepad++ should request elevated Administrator privileges at runtime (runas) just for the write-process. If the user is a Administrator he can confirm the UAC and Notepad++ can write the config. If he is a non-administrator and a write-access-error occurs, Notepad++ can ignore the error or show a error message.
- that's it

I hope you understand my description and i can help to make Notepad++ even more useful than it already is :-)

**Comment by MetaChuh** [comment]
please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins.
if your issue still persists, and it is still of relevance to you, please feel free to file a new issue as easy to understand and reproducible as possible.

thank you for your support and best regards.

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
(no extra account is needed, just use your github account to sign in)
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)
