### ISSUE TITLE
[BUG] My settings are reset to zero

### ISSUE THREAD

**Issue by K14Mua** [notepad-plus-plus/notepad-plus-plus#15832]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description of the Issue

Today, the portable version of notepad++ is stuck. After restarting the program, a window about the availability of a new version was displayed with an offer to update. I refused. At the same time, the style was reset in the program, the hyphenation of too long lines disappeared and all my syntaxes disappeared

### Steps To Reproduce

1.  I don't know
2.  I don't know
3.  I don't know

### Current Behavior

I feel bitterness and annoyance that months of hard work have been wasted

### Expected Behavior

I expect that the program will not reset my settings by itself

### Debug Information

```shell
Notepad++ v8.5.8   (64-bit)
Build time : Oct 15 2023 - 21:43:56
Path : C:\Dropbox\Portable Soft\Notepad++ (Portable)\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : ON
Cloud Config : C:\Dropbox\Portable Soft\Notepad++ (Portable)\Cloud
OS Name : Windows 11 Pro (64-bit)
OS Version : 23H2
OS Build : 22631.4460
Current ANSI codepage : 1251
Plugins : 
    ComparePlugin (2.0.2)
    mimeTools (2.9)
    NppConverter (4.5)
    NppExport (0.4)
```

### Anything else?

What the hell is going on with the program? Why does it reset the settings by itself?

**Comment by K14Mua** [comment]
How do I get all my settings back?

**Comment by K14Mua** [comment]
How can I at least get the syntaxes back???

**Comment by xomx** [comment]
> After restarting the program, a window about the availability of a new version was displayed with an offer to update.

I know that this happens when someone with portable Notepad++ severely damages or deletes its `config.xml` file. In that case N++ tries to use some "factory defaults" but I think it uses defaults for the installed N++ packages, which have the `Preferences > MISC. > Enable Notepad++ auto-updater` checked unlike the portable ones. That and the existence of a newer N++ version probably led to the update offer.

> ### Expected Behavior
> 
> I expect that the program will not reset my settings by itself

Because of I wrote above, I think that one or more of your N++ config files were damaged or lost or inaccessible at the time you launched the N++ app. So it tried to recover from that state and recreated its config file(s) to a factory default state.

> How do I get all my settings back?

I see that you use some portable apps setup run from your Dropbox, is it?
Is not there an inherent Dropbox way to get back to some previous versions of the files stored there?

**Comment by K14Mua** [comment]
Do you think I postponed my work for 3 days and waited for your answer? I reinstalled the app a long time ago and started from scratch.  Do you store absolutely everything in one file? And application settings and custom syntaxes? I lost everything because of some incomprehensible failure of your application. I opened a document with several million characters in one line and this caused me to lose all my settings? There was nothing useful in backups either, why do they even need them in this case?

And even though I installed a new notepad with the latest version, I still lose my settings every time I restart the program. userDefineLanguage is reset after restarting the program. Why is this happening?

**Comment by xomx** [comment]
> I lost everything because of some incomprehensible failure of your application.

Ehm, it is not my application.

> I opened a document with several million characters in one line

There you probably have it. The underlying component Scintilla is not suitable to work with such extreme long lines, it does not handle well the layout of such lines, it consumes huge amount of memory for it. And if such a line exceeds the 2GB `int` limit, it even crashes.

> Do you think I postponed my work for 3 days and waited for your answer?

I do not think anything at all. Or actually yes, I think I should not have responded to this post, sorry.
Unsubscribing.

**Comment by donho** [comment]
@K14Mua 
Sorry for not responding you on time. Please get your refund here:
https://notepad-plus-plus.org/news/v843-unhappy-users-edition/

**Comment by K14Mua** [comment]
> https://notepad-plus-plus.org/news/v843-unhappy-users-edition/

So where's your help?
