### ISSUE TITLE
Style token color only applies to first 2047 characters

### ISSUE THREAD

**Issue by Lachvogel** [notepad-plus-plus/notepad-plus-plus#1583]
Problem: When I selected more than ca. 60 lines of code and use a style token to highlight it, it would only highlight the first 60 lines, and the rest will remain selected but not highlighted.

OS: Win 7 64bit
Np++ v: 6.9
No plugins... 

![step1](https://cloud.githubusercontent.com/assets/17644298/13528650/ba5db876-e217-11e5-8fbd-13bafe43fbba.png)
![step2](https://cloud.githubusercontent.com/assets/17644298/13528653/bd96a3fe-e217-11e5-871c-72d367f34074.png)

**Comment by MetaChuh** [comment]
please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins.
if your issue still persists, and it is still of relevance to you, please feel free to file a new issue as easy to understand and reproducible as possible.

thank you for your support and best regards.

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
(no extra account is needed, just use your github account to sign in)
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)
