### ISSUE TITLE
style token chars part word

### ISSUE THREAD

**Issue by erazmus356** [notepad-plus-plus/notepad-plus-plus#15834]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description of the Issue

Select part of the word and do "style token" will mach only whole words in lower case. 

### Steps To Reproduce

1.  select a few letters in a word
2.  right click
3.  style token
4.  select style

### Current Behavior

some words are not selected because are not whole word or not in small case
![image](https://github.com/user-attachments/assets/162c0436-85a5-42ee-87a5-50ce51da6c84)

### Expected Behavior

case should not matter 
should not matter if it is whole word or not

### Debug Information

```shell
Notepad++ v8.7.1   (32-bit)
Build time : Oct 31 2024 - 00:41:42
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Command Line : "D:\Data\-server\2892\log\anoName.log"
Admin mode : ON
Local Conf mode : OFF
Cloud Config : OFF
Periodic Backup : ON
OS Name : Windows Server 2012 R2 Datacenter (64-bit)
OS Build : 9600.0
Current ANSI codepage : 1252
Plugins : 
    mimeTools (3.1)
    NppConverter (4.6)
    NppExport (0.4)
```

**Comment by alankilborn** [comment]
There are options for controlling this behavior in the _Preferences_ on the _Highlighting_ subpage.
Please close this issue.

**Comment by erazmus356** [comment]
options works fine
