### ISSUE TITLE
Recognize .frm .bas .cls as Visal Basic language

### ISSUE THREAD

**Issue by Tragen** [notepad-plus-plus/notepad-plus-plus#1585]
When I open a .frm, .bas or .cls file I have to switch the language to VB manually.

**Comment by ClaudiaFrank** [comment]
You could do it by using Settings->StyleConfigurator->Language->VB/VBS
and add the extensions to User ext.:

**Comment by vgturtle127** [comment]
@ClaudiaFrank Yeah, but it should still be added since those files are usually exclusive to Visual Basic.

**Comment by ClaudiaFrank** [comment]
@vgturtle127, I can't tell you for .bas, I should have googled it but it isn't true for
.frm (used by mysql) and .cls (used by latex)

**Comment by vgturtle127** [comment]
@ClaudiaFrank I was actually just talking about .bas from experience. :laughing:

**Comment by milipili** [comment]
`.frm` can also be Delphi Extensions

**Comment by milipili** [comment]
Agree for `.bas`, but not the other ones.
