### ISSUE TITLE
[Feature request] <title>Que aparezca una opción en la ventana de Notepad++ para añadir al menú contextual "Editar con Notepad++" en Windows 10 y 11

### ISSUE THREAD

**Issue by Edwin-10** [notepad-plus-plus/notepad-plus-plus#15857]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description of the Issue

Cuando quiero con anticlic "Editar con Notepad++" no hay la opción en la ventana de Notepad++ si apareciera una opción para activar o desactivarlo para que aparezca o desaparezca como otros programas, porque soy de las personas que lo utilizó como sustituto del bloc de notas clásico de Windows 10, ya que tiene corrector ortográfico y color de sintaxis y más.

### Describe the solution you'd like.

Que aparezca una opción en la ventana de Notepad++ para añadir al menú contextual "Editar con Notepad++" en Windows 10 y 11

### Debug Information

```shell
Notepad++ v8.7.1   (64-bit)
Build time : Oct 31 2024 - 00:48:56
Path : D:\PortableApps\PortableApps\Notepad++Portable\App\Notepad++64\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : ON
Cloud Config : D:\PortableApps\PortableApps\Notepad++Portable\Data\Config
Periodic Backup : ON
OS Name : Windows 10 Pro (64-bit)
OS Version : 22H2
OS Build : 19045.5131
Current ANSI codepage : 1252
Plugins : 
    DSpellCheck (1.5)
    mimeTools (3.1)
    NppConverter (4.6)
    NppExport (0.4)
```

**Comment by alankilborn** [comment]
>Add an option to the Notepad++ window to add "Edit with Notepad++" to the context menu in Windows 10 and 11

There are already other ways to add an `Edit with Notepad++` menu to Windows Explorer.
See [HERE](https://npp-user-manual.org/docs/shell-extension/).
