### ISSUE TITLE
VB code folding missing keywords

### ISSUE THREAD

**Issue by Tragen** [notepad-plus-plus/notepad-plus-plus#1586]
In VB language there are some cases missing for code folding like
If
End If

or

Sub / Public Sub / Private Sub
End Sub

or

Function / Public Function / Private Function
End Function

**Comment by ClaudiaFrank** [comment]
VB folding is based on indention you could even write

these lines
    gets
folded as well

And folding is done by scintilla component so if you want this to be changed you need to address
this at scintilla group
