### ISSUE TITLE
[BUG] Docked panels in v8.6.9+ can be invisible in multi-instance mode

### ISSUE THREAD

**Issue by xomx** [notepad-plus-plus/notepad-plus-plus#15873]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description of the Issue

When one uses any Notepad++ v8.6.9+ in multi-instance mode and left the 1st instance launched minimized, then any other N++ instance will have its docked panels invisible.

### Steps To Reproduce

https://community.notepad-plus-plus.org/post/98013

### Current Behavior

Cannot see the opened panels.

### Expected Behavior

Panels can be used at the described setup.

### Debug Information

```shell
Any Notepad++ v8.6.9+
```

**Comment by Slayer95** [comment]
Thanks!
