### ISSUE TITLE
Bug] Unsaved documents lost on next launch if portable npp change its path 

### ISSUE THREAD

**Issue by Tragen** [notepad-plus-plus/notepad-plus-plus#1587]
Currently the default backup path for the session is the
N+ folder\backup
This is a fixed path in the settings. But when I keep N++ portable on y USB stick, this doesn't work.
It would be great to have a variable or an option to make the path relative to the current N++ executable

**Comment by ClaudiaFrank** [comment]
Temporary [workaround](https://github.com/notepad-plus-plus/notepad-plus-plus/issues/1344) should
work here as well
