### ISSUE TITLE
[BUG] session.xml backup paths are stored as absolute paths but the backups themselves are stored relative to npp's folder which breaks session.xml if npp's folder were renamed or moved

### ISSUE THREAD

**Issue by rust2** [notepad-plus-plus/notepad-plus-plus#15886]
### Is there an existing issue for this?

- [x] I have searched the existing issues
Related: https://github.com/notepad-plus-plus/notepad-plus-plus/issues/5098

### Description of the Issue

So, session.xml backup paths are stored as absolute paths but the backups themselves are stored relative to npp's folder which breaks session.xml if npp being launched after its folder was renamed or moved. This just happens to me between windows reinstallations as I use it in portable mode.
It can also break absolutely easy if npp is used from flash drive and windows just assign another letter to the drive

### Steps To Reproduce

1. unpack portable npp
2. start npp
3. make new file
4. edit it
5. close npp
6. check session.xml that it have absolute path to new file's backup
7. rename or move npp's folder
8. start npp
9. you lost your unsaved edited new file

### Current Behavior

as described in steps 7~9

### Expected Behavior

as backups stored relative to npp's executable folder, session.xml should also have paths that are relative to npp's executable.

Current: `backupFilePath="D:\Users\Rustam\Desktop\0Notepad++\backup\new 5@2024-11-30_165530"`
Expected: `backupFilePath="backup\new 5@2024-11-30_165530"`

### Debug Information

```shell
Notepad++ v8.7.1   (64-bit)
Build time : Oct 31 2024 - 00:48:56
Path : D:\Users\kww\Desktop\0Notepad++\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : ON
Cloud Config : OFF
Periodic Backup : ON
OS Name : Windows 10 Enterprise LTSC 2021 (64-bit)
OS Version : 21H2
OS Build : 19044.1288
Current ANSI codepage : 1251
Plugins : 
    ComparePlugin (2.0.2)
    EmmetNPP (1.0.2)
    HexEditor (0.9.12)
    mimeTools (3.1)
    NppConverter (4.6)
    NppExport (0.4)
    NPPJSONViewer (1.40)
    PythonScript (2)
```

**Comment by Trubisky** [comment]
I'm working on writing a patch that additionally attempts to load backups from the backups folder in the current working directory, if the backup file isn't found on load. Should fix this problem, will keep posted.
