### ISSUE TITLE
[Feature request] Removing the <codecvt> header file can reduce size of notepad++.exe by approximately 0.15 MB

### ISSUE THREAD

**Issue by softmgr** [notepad-plus-plus/notepad-plus-plus#15898]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description of the Issue

Currently, the functions utilizing the `<codecvt>` header file are primarily found in two places:
	1.	In Common.cpp, the functions: s2ws(), ws2s(), and writeLog().
	2.	In FileInterface.cpp, the functions: Win32_IO_File::Win32_IO_File() and Win32_IO_File::close().

We can achieve this by rewriting s2ws() and ws2s(), and modifying the related code in the other functions to call these updated versions.

Here is the improved implementation of the s2ws() function, which works correctly when compiled with both VS2022 and GCC:
```
std::wstring s2ws(const std::string& str)
{
    if (str.empty()) return std::wstring();

    int size_needed = MultiByteToWideChar(CP_UTF8, 0, str.c_str(), -1, nullptr, 0);
    if (size_needed <= 0) {
        return std::wstring();
    }

    std::wstring wstr(size_needed, 0);
    MultiByteToWideChar(CP_UTF8, 0, str.c_str(), -1, &wstr[0], size_needed);
    wstr.pop_back();
    return wstr;
}
```

And here is the improved implementation of the ws2s() function, which also works correctly with both VS2022 and GCC:
```
std::string ws2s(const std::wstring& wstr)
{
    if (wstr.empty()) return std::string();

    int size_needed = WideCharToMultiByte(CP_UTF8, 0, wstr.c_str(), -1, nullptr, 0, nullptr, nullptr);
    if (size_needed <= 0) {
        return std::string();
    }

    std::string str(size_needed, 0);
    WideCharToMultiByte(CP_UTF8, 0, wstr.c_str(), -1, &str[0], size_needed, nullptr, nullptr);
    str.pop_back();
    return str;
}
```

### Describe the solution you'd like.

none.

### Debug Information

```shell
Notepad++ v8.7.3   (64-bit)
Build time : Nov 30 2024 - 16:48:13
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
Periodic Backup : ON
OS Name : Windows 10 Pro (64-bit)
OS Version : 22H2
OS Build : 19045.5131
Current ANSI codepage : 1252
Plugins : 
    mimeTools (3.1)
```

**Comment by pawelzwronek** [comment]
@softmgr as `std::codecvt_utf8` is marked as [deprecated](https://en.cppreference.com/w/cpp/locale/codecvt_utf8) + .exe size reduction by removing is good, but why not to use already implemented converter: `WcharMbcsConvertor::char2wchar` and `WcharMbcsConvertor::wchar2char` 🤔
```cpp
WcharMbcsConvertor& wmc = WcharMbcsConvertor::getInstance();
return (wchar_t*)wmc.char2wchar(wstr.c_str(), SC_CP_UTF8);
```

**Comment by softmgr** [comment]
> @softmgr as `std::codecvt_utf8` is marked as [deprecated](https://en.cppreference.com/w/cpp/locale/codecvt_utf8) + .exe size reduction by removing is good, but why not to use already implemented converter: `WcharMbcsConvertor::char2wchar` and `WcharMbcsConvertor::wchar2char` 🤔
> 
> ```cpp
> 
> WcharMbcsConvertor& wmc = WcharMbcsConvertor::getInstance();
> 
> return (wchar_t*)wmc.char2wchar(wstr.c_str(), SC_CP_UTF8);
> 
> ```

Yes, using `WcharMbcsConvertor` to implement this makes the code more concise.

Tests show that using either `WcharMbcsConvertor` or my custom implementation is significantly more performant than using `<codecvt>`. During debugging, running 10,000 iterations of the conversion resulted in the following times:
•	`<codecvt>`: approximately 1350 milliseconds
•	`WcharMbcsConvertor` or `MultiByteToWideChar`: approximately 50 milliseconds

Using WcharMbcsConvertor for implementation does not affect the final size of the compiled notepad++.exe.

**Comment by chcg** [comment]
Also in PowerEditor/src/ScintillaComponent/Buffer.cpp codecvt is used.

string2wstring and wstring2string (based on MultiByteToWideChar and WideCharToMultiByte)  seems to be already a replacement for s2ws and ws2w.

The only issue might be the limitation to int aka 32bit in 64bit environments.

**Comment by softmgr** [comment]
> Also in PowerEditor/src/ScintillaComponent/Buffer.cpp codecvt is used.
> 
> string2wstring and wstring2string (based on MultiByteToWideChar and WideCharToMultiByte) seems to be already a replacement for s2ws and ws2w.
> 
> The only issue might be the limitation to int aka 32bit in 64bit environments.
> 
> @pawelzwronek @softmgr What do you think about #15913

Tested and working very well.

**Comment by pawelzwronek** [comment]
@chcg Also tested and can't see any issues.

Only a minor suggestion, nothing important:
Because `wstring2string` is used with `CP_UTF8` most of the time I would consider to add a wrapper: `wstring2utf8` or `wide2utf8` in short and  `wstring2ansi` or `wide2ansi` in short for `CP_ACP` encoding.

So e.g. `wstring2string(skd.name, CP_UTF8)` would be `wstring2utf8(skd.name)` or `wide2utf8(skd.name)`.

**Comment by donho** [comment]
> Because wstring2string is used with CP_UTF8 most of the time I would consider to add a wrapper: wstring2utf8 or wide2utf8 in short and wstring2ansi or wide2ansi in short for CP_ACP encoding.

wstring2utf8, wide2utf8, wstring2ansi and wide2ansi make more confusion IMO.
So personally I prefer to keep wstring2string with encoding argument.
