### ISSUE TITLE
Theme setting is not portable

### ISSUE THREAD

**Issue by Tragen** [notepad-plus-plus/notepad-plus-plus#1589]
When I select a theme, it gets saved as

```
    <GUIConfig name="stylerTheme" path="X:\Software\Editors\N++ v6.8.8\themes\MyObsidian.xml" />
```

This is not portable. Best would be to save the path relative to the executable.

**Comment by ClaudiaFrank** [comment]
Temporary [workaround](https://github.com/notepad-plus-plus/notepad-plus-plus/issues/1344)

**Comment by vgturtle127** [comment]
@Tragen I think changing everything to be relative to the executable sounds like a good idea for portability, at least on Windows. Reducing the dependence on the registry and external directories will make development and testing easier as well.

**Comment by clonsberry** [comment]
For others who are searching: I wrote [workaround instructions](https://github.com/notepad-plus-plus/notepad-plus-plus/issues/9409#issuecomment-1298496463) in 9409.
