### ISSUE TITLE
[BUG] Comment commands don't work with multiple selections

### ISSUE THREAD

**Issue by notdodgeball** [notepad-plus-plus/notepad-plus-plus#15901]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description of the Issue

The comment commands:
- Toggle Single Line Comment
- Single Line [Un]Comment
- Block [Un]Comment

### Steps To Reproduce

1.  Enable Multi-Editing in Preferences
2.  **With Ctrl+click**, create multiple selections or multiple cursors spanning multiple lines
3.  Use one of the aforementioned commands

### Current Behavior

Only the last line selected is affected

### Expected Behavior

All lines are affected

### Debug Information

```shell
Notepad++ portable v8.7.1 (64-bit)

Plugins : 
    ComparePlus (1.1)
    LocationNavigate (0.4.8.1)
    mimeTools (3.1)
    NppConverter (4.6)
    NppExport (0.4)
    NppMarkdownPanel (0.7.3)
    PythonScript (3.0.19)
    XMLTools (3.1.1.13)
```

### Anything else?

When using Alt+Shift+Up/Down or with a rectangular selection or selecting dragging using the mouse, this bug is not reproduced.
When using Ctrl+click or Multi-select All/Next this bug is reproduced.

**Comment by softmgr** [comment]
So far, most of the editing features in Notepad++ do not support multiple selections.
