### ISSUE TITLE
N++ crash with NPPAutoIndent

### ISSUE THREAD

**Issue by Tragen** [notepad-plus-plus/notepad-plus-plus#1590]
Edit this file
https://raw.githubusercontent.com/jaeksoft/opensearchserver-php-client/master/examples/oss_examples.php
and set NPPAutoIndent to smart.
Go to the second line and press enter and N++ crashes

**Comment by ClaudiaFrank** [comment]
Sounds like author of NppAutoIndent needs to take care of this
