### ISSUE TITLE
[BUG] <title>Some political shit in opensource

### ISSUE THREAD

**Issue by 1vanK** [notepad-plus-plus/notepad-plus-plus#15909]
https://www.youtube.com/watch?v=GyOsOOKUsME

**Comment by Aynyuh** [comment]
I'm done with this. It's time to switch to another editor before the maintainer finally goes radical and potentially embeds a logic bomb targeting users with different views.

**Comment by dartraiden** [comment]
Duplicate of https://github.com/notepad-plus-plus/notepad-plus-plus/issues/6288 https://github.com/notepad-plus-plus/notepad-plus-plus/issues/7426 https://github.com/notepad-plus-plus/notepad-plus-plus/issues/8659

**Comment by 1vanK** [comment]
Как ты разозлился от одного пальца, но что-то прямо такое мощное выдать не способен, смешишь только

**Comment by dartraiden** [comment]
Дык ржи, пока бесплатно, минута смеха заменяет стакан сметаны, а она нынче дорожает.

**Comment by 1vanK** [comment]
Ну давай, напрягись, пока что слабенько
