### ISSUE TITLE
[BUG] <?php at beginning of a php file gets munged when doing a reformat (ctrl-alt-m)

### ISSUE THREAD

**Issue by rootsfinder** [notepad-plus-plus/notepad-plus-plus#15920]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description of the Issue

I'm editing a file with the language set to php.  When I do a reformat (using ctrl-alt-m), it munges up the <?php
 on the first line and the file reverts to a javascript language type.

### Steps To Reproduce

1.  create a php file with <?php ont the first line
2.  verify php set as language type
3.  press ctrl-alt-m

### Current Behavior

first line is changed to: <  ? php

### Expected Behavior

first line does not change

### Debug Information

```shell
Notepad++ v8.7.1   (64-bit)
Build time : Oct 31 2024 - 00:48:56
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
Periodic Backup : ON
OS Name : Windows 10 Pro (64-bit)
OS Version : 22H2
OS Build : 19045.5198
Current ANSI codepage : 1252
Plugins : 
    JSMinNPP (1.2205)
    JsonTools (4.4)
    mimeTools (3.1)
    NppConverter (4.6)
    NppExport (0.4)
    NPPJSONViewer (2.0.4)
```

**Comment by rdipardo** [comment]
This appears to be an issue with the JSMinNPP plugin's reformatting command (mapped to <kbd>CTRL+ALT+M</kbd> by default).

Please close this bug report and resubmit it here: <https://github.com/sunjw/jstoolnpp/issues>
