### ISSUE TITLE
[BUG] notepad++ becomes unusuable after deleting files in split view

### ISSUE THREAD

**Issue by BernieStn** [notepad-plus-plus/notepad-plus-plus#15922]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description of the Issue

I opened two text files in notepad++ and splitted the view vertically. One file is displayed on the left side, the other one on the right side. After deleting both files, notepad++ becomes unusable.

### Steps To Reproduce

Open two text files in notepad++ and view them side by side:
![1](https://github.com/user-attachments/assets/8b8d6ecf-47fa-4b9b-ac42-a50d6d8e3945)

On the file system, delete both files. Result:
![2](https://github.com/user-attachments/assets/88e72f6e-59b8-46c1-8664-07fc0492d8c4)

Click "No" to not keep the file b.txt. Result:
![3](https://github.com/user-attachments/assets/4c9167b9-c17b-435b-b2bb-ee00677f81f2)

Click "No" to not keep the file a.txt. 
As shown in the following screenshot, the entire editing area is grey. I cannot edit in notepad++ anymore
![4](https://github.com/user-attachments/assets/999dec90-bd31-4440-b222-a9ef8a447ba4)

Click on "new file" several times.
Result: All tabs are named "neu 1" and none of the files can be edited, because the entire editing area is grey here as well:
![5](https://github.com/user-attachments/assets/87bb7b01-032c-496a-8a04-ee48b495c006)

### Current Behavior

See "Steps To Reproduce"

### Expected Behavior

notepad++ should be usable even if files are deleted which were viewed in split-mode

### Debug Information

```shell
Notepad++ v8.7.4   (64-bit)
Build time : Dec  4 2024 - 23:50:05
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
Periodic Backup : OFF
Placeholders : OFF
DirectWrite : ON
Multi-instance Mode : monoInst
File Status Auto-Detection : cdEnabledNew (for current file/tab only)
Dark Mode : OFF
OS Name : Windows 10 Pro (64-bit)
OS Version : 22H2
OS Build : 19045.5131
Current ANSI codepage : 1252
Plugins : none
```

**Comment by alankilborn** [comment]
Wow.  Nice find.  I can reproduce this.

**Comment by xomx** [comment]
@donho 
I see what is wrong here, I can fix this if needed(?)

**Comment by donho** [comment]
@xomx 
Yes, go ahead please.
