### ISSUE TITLE
[BUG] Default font overrides first word

### ISSUE THREAD

**Issue by MAZ06** [notepad-plus-plus/notepad-plus-plus#15937]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description of the Issue

The global font will be used on the first word in a tab that uses a different font. For me, I noticed it when typing some python code.

### Steps To Reproduce

1.  Set python to use a font different from the global font ("enable global font" turned off)
2.  Set language to python and start typing.
3.  The first word will be in the global font until you press space or go to the next line. Then the first word will stay as the global font and the rest of the document will be in the different font.

### Current Behavior

The first word is displaying in the global font.

### Expected Behavior

All words should use the non-global font.

**Comment by MAZ06** [comment]
Also happens to the word directly after a period: ".word"

**Comment by alankilborn** [comment]
Provide *Debug Info* or your issue will be rejected/closed.

**Comment by MAZ06** [comment]
Sorry! I think I accidentally deleted it when I edited my post! Here you go:

Notepad++ v8.7.4   (64-bit)
Build time : Dec  4 2024 - 23:50:05
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
Periodic Backup : ON
Placeholders : OFF
DirectWrite : ON
Multi-instance Mode : monoInst
File Status Auto-Detection : cdEnabledNew (for current file/tab only)
Dark Mode : ON
OS Name : Windows 10 Pro (64-bit)
OS Version : 22H2
OS Build : 19045.5131
Current ANSI codepage : 1252
Plugins : 
    ComparePlugin (2.0.2)
    DSpellCheck (1.5)
    HugeFiles (0.4.1)
    mimeTools (3.1)
    NavigateTo (2.6.4)
    NppConverter (4.6)
    NppExport (0.4)

**Comment by alankilborn** [comment]
>Set python to use a font different from the global font ("enable global font" turned off)

What does this mean?
I see no UI element captioned with "enable global font".
The steps-to-reproduce are supposed to be detailed enough that someone not looking over your shoulder while you do it (which is everyone) can understand your actions, and attempt to reproduce what you're seeing.

**Comment by MAZ06** [comment]
It just means that forcing global font is turned off in Style Configurator. Apparently it had a name change recently. It's now called "Force font choice for all styles."

This should not have interfered in reproduction unless you had this setting turned on already.

**Comment by alankilborn** [comment]
I guess it has to be _dragged_ out of you...

>The global font will be used on the first word in a tab that uses a different font. For me, I noticed it when typing some python code.

First, show screenshot of "some python code" that exhibits the problem.

**Comment by MAZ06** [comment]
Why such aggression? This is a bug report. No need to be rude.

Just type literally anything. The first word will be in the global default font. And anything typed after that will be in the font you selected for python. Same issue for any word typed directly after a period.

**Comment by pryrt** [comment]
![image](https://github.com/user-attachments/assets/7ac7fede-0caa-462f-85d6-7b2832b1661d)

In my experiment, I can tell it's being treated as an ATTRIBUTE.  The color I showed is from a fresh unzip of Notepad++, except I added the underline to make it doubly obvious that it really was the ATTRIBUTE style, since other styles (like the DECORATOR) also use that orange color by default.  I am surprised the lexer considers the first word an ATTRIBUTE in such a situation, because my Python almost always has a comment-style first line, so I would never see that.

If your current theme or stylers.xml is out-of-date, then it might not have a entry for Python's ATTRIBUTE style, and it must fall back to using the default style, because it has no information to use for that style.  Thus, it would look to you like it's in the "global style", when in reality, it's just in the ATTRIBUTE style with no ATTRIBUTE style settings defined.  

If when you scroll down from there, you are missing the ATTRIBUTE, DECORATOR, or the USER KEYWORDS \# entries, then your stylers.xml or theme is definitely out of date.

![image](https://github.com/user-attachments/assets/383fa25b-6641-42e8-afb8-86fa9f2f3f12)

As the [User Manual explains](https://npp-user-manual.org/docs/themes/#keeping-stylersthemes-up-to-date), themes or stylers.xml aren't updated when you update Notepad++ (because the dev doesn't want to overwrite your customizations), so it's up to you to manually update the portions of your active theme or stylers.xml that are important to you.  If you have no customizations in your stylers.xml, then you can just exit Notepad++, delete `%AppData%\Notepad++\stylers.xml`, and restart Notepad++, and Notepad++ will use a fresh copy (from `<installdir>\stylers.model.xml`, which _is_ up-to-date) -- which will then style that ATTRIBUTE in orange, as my screenshot showed (though without the underline to go with it)

And when someone with a fresh Notepad++ v8.7.4, or who has kept their stylers.xml up-to-date, tried your implied experiment, they would have seen orange, not "the global font" like you asserted; thus, they might ask that you provide a more data -- like a screenshot and example code, which specifically shows the problem you are having, so that they can try the exact same thing that you tried, and show you that theirs behaves differently than you describe , which greatly helps in debugging that kind of problem.

**Comment by MAZ06** [comment]
@pryrt Thank you for the write-up. It looks like you're right. *Your* screenshot actually shows a lot more python styles than I have!
![image](https://github.com/user-attachments/assets/f3f1239b-39e1-4c8c-9160-4ca4888b2793)

I guess my stylers.xml *is* out of date. Why is it not updated automatically?

**Comment by rdipardo** [comment]
@MAZ06

> I guess my stylers.xml is out of date.

Since b3ff400cc8ddfbd1b5da54d6519a43bad6195f2a, the Python attribute style is configurable only for "Default (stylers.xml)", "DarkModeDefault" and "Zenburn". Is your theme one of those?

@pryrt

> I am surprised the lexer considers the first word an ATTRIBUTE in such a situation

Known issue: #15590

**Comment by MAZ06** [comment]
@rdipardo I am using "Default (stylers.xml)".

**Comment by alankilborn** [comment]
> I guess my stylers.xml _is_ out of date. Why is it not updated automatically?

Because sometimes users customize things to their own taste (e.g., you did this when you "Set python to use a font different from the global font") and the Notepad++ installer doesn't update the data just for this reason; to avoid blowing away any customizations you might have made.

The above refers to a blanket overwriting of the data.  Could Notepad++ installer code look for your customizations and retain them, while writing updated data around them? Yes, sure...but Notepad++ developers have limited time and have not chosen to spend that time on such a feature, in order to bring users what they consider to be more important features.

**Comment by alankilborn** [comment]
@rdipardo 

After reading 15590 (where the petitioner amazingly supplied both Python code and a screenshot), I can't tell if this is a bug in the lexer (in which case it is not Notepad++ 's bug) or Notepad++'s misconfiguration of the lexer, or something else entirely.  What's your opinion?

**Comment by pryrt** [comment]
> I can't tell if this is a bug in the lexer (in which case it is not Notepad++ 's bug)

Whether it's a bug or not, I'm not sure... but it's definitely in Lexilla.  (I had to edit the python.properties to uncomment the `lexer.python.identifier.attributes=1` line, and added 
```
# attributes/methods
style.python.20=fore:#FF8000,underline
```

![image](https://github.com/user-attachments/assets/0953b1fd-258c-4d09-8dcf-c2c43bb8ed2f)

![image](https://github.com/user-attachments/assets/5167515e-1ead-4eb4-8da1-2223148477f7)

![image](https://github.com/user-attachments/assets/da006257-265b-4044-b1b0-35abde8217da)

**Comment by MAZ06** [comment]
> What does this mean? I see no UI element captioned with "enable global font". The steps-to-reproduce are supposed to be detailed enough that someone not looking over your shoulder while you do it (which is everyone) can understand your actions, and attempt to reproduce what you're seeing.

You could easily have just said to be more detailed. Or you could have asked for more clarification on the actual steps and not just finding a setting. But you had to go further to what amounts to provoking/harassment.

We can look at your behavior another way. I'm sure you, like many others, have family members who request computer help from time to time. Is this the way you treat them? I can't possibly imagine treating my family, or anyone else for that matter, in this way.

Imagine my mother needs help with something. I could easily ask her for more information. "Can you be more detailed in what's happening? I don't understand when you said x, y, and z."

But what if I treated her the way you treat people? "What are you talking about? I see absolutely nothing like you describe! You're acting like I can see what you're doing! Literally no one can possibly understand what you're saying!"

Whether she presented me with accurate steps or not is not the point. Treating someone that way is disgusting, unwarranted behavior.

Furthermore on this point, the only thing you mentioned having issues with was the "enable global font" option which as I said was recently changed. I don't know how anyone is supposed to keep up with slight name changes. As a contributor to this project, I highly doubt you were actually confused about what I said here.

But that's the only issue you brought up. In my next response, I clarified it as you requested. You mentioned absolutely nothing about the other steps (which should be extremely easy to follow), so I didn't mention them either. Why would I? As I said in my post: 
> This should not have interfered in reproduction unless you had this setting turned on already.

In your next post, you say:
> I guess it has to be _dragged_ out of you...

What has to be dragged out of me? I literally clarified the issue you mentioned. What else could I possibly do?

Let's try it with my family example again:
"Hey mom, I didn't understand issue 1. Can you clarify what you meant?"
"Sure," she replies. "It means ____, ____, etc."
"Well I guess it needs to be *dragged* out of you! How dare you not mention issue 2, 3, and 4!? Provide information about those things right now!"

Do you see how stupid that sounds? I can only logically conclude you're doing this on purpose. You made no mention at all about anything else. If you had mentioned any other issues *and then* I didn't clarify, then *dragging* would have made sense. But you *didn't* mention anything else. You just pretended you did so you could blame me for something.

But let's go through my original steps:

> 1. Set python to use a font different from the global font ("enable global font" turned off)

With the exception of the "enable global font" issue that I clarified when you asked, what else could I say or do here?

> 2. Set language to python and start typing.

This can't be be clearer. Do you, as a contributor, not know how to set the language to python?

> The first word will be in the global font until you press space or go to the next line. Then the first word will stay as the global font and the rest of the document will be in the different font.

Again, what else could be said? Were you unable to type words? Did you not try typing literally anything at all just to test it? It seems that @pryrt was able to understand this just fine.

You then tell me:
> First, show screenshot of "some python code" that exhibits the problem.

And I replied:
> Just type literally anything. The first word will be in the global default font. And anything typed after that will be in the font you selected for python. Same issue for any word typed directly after a period.

Did you not even try typing? It took you more time to respond on GitHub than it would have taken you to just type a few words into Notepad++.

In fact, before you even first responded, I had said:
> Also happens to a word directly after a period: ".word"

Did you not even try this either? Do you need a screenshot of my typing this?

>The steps-to-reproduce are supposed to be detailed enough that someone not looking over your shoulder while you do it (which is everyone) can understand your actions, and attempt to reproduce what you're seeing.

This is therefore an outright lie. I am in no way acting as if someone would have to look over my shoulder to understand how to reproduce the bug. My steps are incredibly simple and easy to follow. A screenshot should not even be necessary. Yet you keep insisting that it is.

@pryrt then responded with:
>And when someone with a fresh Notepad++ v8.7.4, or who has kept their stylers.xml up-to-date, tried your implied experiment, they would have seen orange, not "the global font" like you asserted; thus, they might ask that you provide a more data -- like a screenshot and example code, which specifically shows the problem you are having, so that they can try the exact same thing that you tried, and show you that theirs behaves differently than you describe , which greatly helps in debugging that kind of problem.

Yes. That's correct. Someone might ask me to provide more data like a screenshot or example code in such a situation. But that's not what happened! @alankilborn only mentioned the "enable global font" issue which, again, I clarified. They made no mention of anything else. They then pretended (lied) as if they mentioned more.

And as I have shown above, my instructions were incredibly simple to understand. And, as I also showed above, I *did* include a simple example of ".word". Again, do I need to screenshot that?

@pryrt's screenshots in that specific post add absolutely no extra information that wasn't included in my original descriptions. But as we see later, @alankilborn lies yet again insisting that they do.

>So, obviously I made a quick guess at what "literally anything" might be, and tried it. And I didn't see what @MAZ06 was (poorly) describing. But WTF was I supposed to do at that point, go into a bunch of detail typing about what I'm seeing, while knowing virtually nothing about what the reporter has done or is exactly seeing? Absolutely not: At that point, I'd be the one doing doing the bug reporting, not the petitioner.

 Another attack. Same old lie. Again, as I said above, I literally gave an example of what to type: ".word"

> After reading 15590 (where the petitioner amazingly supplied both Python code and a screenshot), I can't tell if this is a bug in the lexer (in which case it is not Notepad++ 's bug) or Notepad++'s misconfiguration of the lexer, or something else entirely. What's your opinion?

Mocking your victim again by claiming that another user did such a an amazing job that it gives you the right to knock down someone who did a poor job. A job that you lied about as is I have clearly shown in this post.

Even if I was incorrect about literally anything, it still doesn't give you the right to mistreat people like this. If someone makes a typo, do you attack them? "I couldn't understand what you were (poorly) trying to spell! Look at this other person who amazingly *didn't* make a typo!" Is this how you treat people? Typical provoking behavior.

So let's review:
1. I provide an extremely simple description of what to do. Even including a specific thing to type: ".word"
2. @alankilborn asks about "enable global font" and nothing else. Already unwarrantedly aggressive and rude about it.
3. I provide the clarification about "enable global font" and address their rude behavior.
4. @alankilborn responds acting as if they requested more than that when clearly they didn't, giving themselves their own false ammunition to use against me and claiming that (unrequested) information had to be *dragged* out of me.
5. @pryrt is able to follow my directions in spite of @alankilborn's claim that it's so difficult without a screenshot.
6. @alankilborn hits back against my claims of his aggressiveness and rudeness, doubling down on their lies in order to provoke and victim blame even more.

The worst part about this is that you're acting this way over a bug report of all things. I've looked at your other posts here and it seems that your behavior is consistent. Any slight inconvenience and you attack people. Is this how you treat people in real life too?

Do you think I'm stupid and I won't notice simple, obvious harassment? You apparently enjoy knocking people down and then playing the victim when your actual victim talks back.

I will be reporting your disgusting behavior to Github Support and I'd suggest everyone else here do the same. We need to keep Github a safe community away from users like @alankilborn.

**Comment by chcg** [comment]
Fix is available with https://github.com/notepad-plus-plus/notepad-plus-plus/releases/tag/v8.7.9
