### ISSUE TITLE
C Comment Highlight

### ISSUE THREAD

**Issue by esadkatmer** [notepad-plus-plus/notepad-plus-plus#1593]
When you write
> #define MAXLINE 1000 /* maximum input line size */
this comment doesn't highlighting. It stays white

**Comment by dail8859** [comment]
What version of N++ and theme are you using?

**Comment by esadkatmer** [comment]
version: 6.9 theme: Obsidian and the other themes

**Comment by esadkatmer** [comment]
In default style no issue but in other styles there are

**Comment by dail8859** [comment]
@esadkatmer Was this meant to be closed?
