### ISSUE TITLE
Opening this .nfo file causes a crash

### ISSUE THREAD

**Issue by vgturtle127** [notepad-plus-plus/notepad-plus-plus#1594]
If you open this .nfo file either from the "Edit with Notepad++" context menu, or by double-clicking the file to open it in the default editor (which is Notepad++ for me), Notepad++ crashes.

The weird thing is that if you open it from the "File > open" menu, it works fine.

I am running Notepad++ 6.9 on 64-bit Windows 10 Pro.

Here is the debug info:

Notepad++ v6.9
Build time : Feb 21 2016 - 21:27:55
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10
Plugins : DoxyIt.dll DSpellCheck.dll HexEditor.dll JSLintNpp.dll JSMinNPP.dll mimeTools.dll NppConverter.dll NppExport.dll NppFTP.dll NppSnippets.dll NppTaskList.dll NppTextFX.dll PluginManager.dll Tidy2.dll 

I also have included the file I was referring to (rename it to .nfo):

[codex.txt](https://github.com/notepad-plus-plus/notepad-plus-plus/files/160648/codex.txt)

This also crashed when I tried to open a similar file from the same group, except it was from the Guns Gore and Cannoli release.

EDIT: I just tried more .nfo files and most of them crash, so this must be some sort of bug or regression.

**Comment by ClaudiaFrank** [comment]
Tried it on windows7 x64 npp 6.9 without a problem. Did you try to load the file it with no plugins installed?

**Comment by vgturtle127** [comment]
@ClaudiaFrank Yeah, and it runs fine without them. The problem is, if I remove all of my plugins and just keep the default plugins, it still does it. As a matter of fact, if I have any plugins at all it doesn't load the .nfo file and crashes... :fearful: 

Do you know what is happening to make this crash like this? I opened an issue because I assumed it was a problem with Notepad++, since it seemingly has some sort of an issue with any plugin instead of just one. :disappointed:

**Comment by Tmp341** [comment]
I opened it on win7 x86 without a problem too. I only have Compare, Nppcrypt and Plugin Manager. But gonna try with yours.

**Comment by vgturtle127** [comment]
@Tmp341 Yeah, I tried it again and it seems the hex editor is causing the problem.

@donho Is it still labeled as a good plugin? Is the author still around? I feel like it may need to be labled as an unstable plugin again. More so then DSpellCheck, since this causes catastrophic errors and crashes.

**Comment by Tmp341** [comment]
@vgturtle127 Have you tried other nfos? Is it just this one or is hex editor not compatible with nfos?

**Comment by vgturtle127** [comment]
@Tmp341 I don't think the hex editor likes .nfo files, because you can literally just change the extension and it will crash. Files that have ASCII art in them (regardless of extension) also crash most of the time.

**Comment by wyrex** [comment]
Notepad++ v6.9.1
Build time : Mar 28 2016 - 19:48:40
Path : E:\Notepad++\notepad++.exe
Admin mode : ON
Local Conf mode : OFF
OS : Windows 7
Plugins : ComparePlugin.dll HexEditor.dll JSMinNPP.dll mimeTools.dll NppCCompletionPlugin.dll NppConverter.dll NppExec.dll NppExport.dll NppFTP.dll NppTextFX.dll PluginManager.dll Python Indent.dll ScrollPastEOFUni.dll Tidy2.dll 

After update to 6.9.1 HexEditor gives two errors every time when starting Notepad++ (it does start), "Failed to create file". it tries to read session.xml which doesn't exist. Other than that plugin manager fails all operations if HexEditor is loaded - it tries to restart editor but files are still in use by notepad++ process and it can't delete them (windows error popup). Everything else works.

Your nfo opens and works fine in normal and hex views using https://github.com/mackwai/NPPHexEditor (didn't try with original plugin). Ascii art takes 3 bytes per character, text only 1.

**Comment by vgturtle127** [comment]
@wyrex Thanks for the link, I will check that out.

I have pretty much switched to using a hex editor by itself, since using text editor plugins and stuff is super buggy and often performance suffers.

I wish there was a decent hex editor for Windows, or even for Linux. None of them are very good. :disappointed:

**Comment by donho** [comment]
@vgturtle127 Hex Editor plugin has been known unstable since long time ago. 
PluginManager plugin is not developped by me. I'll see how can we change the status of plugins.
