### ISSUE TITLE
[BUG] "Close all BUT pinned" not accessible in custom context menu

### ISSUE THREAD

**Issue by SimonSteinberger** [notepad-plus-plus/notepad-plus-plus#15958]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Description of the Issue

When making use of "tabContextMenu.xml", the new function "Close all BUT pinned" tabs is not available. When using the custom context menu, there seems to be no way to include this command.

### Steps To Reproduce

1.  Enable tabContextMenu.xml
2.  Try to include "Close all BUT pinned"

### Current Behavior

New feature not yet available in custom tabContextMenu.xml

### Expected Behavior

Ideally, the new feature should already have an entry that can be edited further in the file "tabContextMenu_example.xml".

### Debug Information

```shell
--
```

**Comment by alankilborn** [comment]
`tabContextMenu_example.xml` is just that... an example.
It may or may not stay in sync with the default tab right-click context menu going forward.

Anyway, have you tried just adding the following into a `tabContextMenu.xml` (that was created from copying `tabContextMenu_example.xml`)?:

`<Item FolderName="Close Multiple Tabs" MenuEntryName="File" MenuItemName="Close All but Pinned Documents"/>`

or, if you like this better:

`<Item FolderName="Close Multiple Tabs" MenuEntryName="File" MenuItemName="Close All but Pinned Documents" ItemNameAs="Close All BUT Pinned"/>`

**Comment by SimonSteinberger** [comment]
Yes, that works 👍 Thank you!

Since the menu item is called "Close All BUT Pinned" when not using the custom menu, I tried this string. "Close All but Pinned Documents" works nicely. I couldn't find a doc/help to look this up.
