### ISSUE TITLE
Top Online Notepad Tools to Revolutionize Your Writing in 2024

### ISSUE THREAD

**Issue by smartonlinenotepad** [notepad-plus-plus/notepad-plus-plus#15956]
### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by alankilborn** [comment]
@donho Ban...

**Comment by xomx** [comment]
@alankilborn 
Reported to GitHub.
Hopefully they will remove these spam-only GH accounts and possibly block the IP addresses from which these new accounts are created.
