### ISSUE TITLE
Incorrect URL opened when double clicking link

### ISSUE THREAD

**Issue by ClaudiaFrank** [notepad-plus-plus/notepad-plus-plus#1595]
URL with exclamation marks can't be opened in browser correctly.
E.g http://lederniergaulois.nouvelles-ecritures.francetv.fr/#!/episode1
opens the page http://lederniergaulois.nouvelles-ecritures.francetv.fr

Reason: NppNotification.cpp sets the wordchars without exclamation mark

```
    case SCN_HOTSPOTDOUBLECLICK:
    {
        notifyView->execute(SCI_SETWORDCHARS, 0, (LPARAM)"abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789_-+.,:?&@=/%#()");
```

but if I understand [RFC3986](http://www.ietf.org/rfc/rfc3986.txt) correctly than this char is allowed

(page 12)
sub-delims  = "!" / "$" / "&" / "'" / "(" / ")"  / "*" / "+" / "," / ";" / "="

**Comment by yoyoma2** [comment]
The same problem occurs with a URL containing a semicolon.

E.g. http://www.farmtek.com/farm/supplies/prod1;ft_greenhouses-ft_professional_greenhouses;pg104853.html

opens the page http://www.farmtek.com/farm/supplies/prod1

**Comment by richlux** [comment]
There's a good article on how to identify links in text here:

http://www.regexguru.com/2008/11/detecting-urls-in-a-block-of-text/
