### ISSUE TITLE
[BUG] Edited tab loses text after tab change

### ISSUE THREAD

**Issue by Qoolize** [notepad-plus-plus/notepad-plus-plus#15964]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description of the Issue

Hello!

If I edit a text in one tab and switch to another tab and back again, the original text is restored. I don't know if there is a setting for this. At least I haven't found one.

### Steps To Reproduce

1. Edit something in Tab A
2. Switch to Tab B
3. Switch back to Tab A
4. The edit is gone

### Current Behavior

That the... editing disappears?

### Expected Behavior

That the... editing not disappears?

### Debug Information

```shell
Notepad++ v8.7.4   (64-bit)
Build time : Dec  4 2024 - 23:50:05
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
Periodic Backup : ON
Placeholders : OFF
DirectWrite : OFF
Multi-instance Mode : monoInst
File Status Auto-Detection : cdEnabledNew (for current file/tab only) + cdAutoUpdate
Dark Mode : OFF
OS Name : Windows 10 Pro (64-bit)
OS Version : 22H2
OS Build : 19045.5247
Current ANSI codepage : 1252
Plugins : 
    JsonTools (8.2)
    mimeTools (3.1)
    NppConverter (4.6)
    NppExport (0.4)
    NPPJSONViewer (2.1)
```

**Comment by xomx** [comment]
> ```shell
> File Status Auto-Detection : cdEnabledNew (for current file/tab only) + cdAutoUpdate
> ```

From your Debug Info is visible that you have enabled silent automatic doc/tab updates in the N++ Preferences:

![npp-MISC-Update-silently](https://github.com/user-attachments/assets/369de895-1d5d-41a0-ad01-7cd84feaa471)

Could it be possible that some other process running is updating the content of your doc/tab file behind your back?

**Comment by Qoolize** [comment]
Hello!

No, this is enabled on purpose. The file itself is not modified from outside, only inside N++.
However, the error is gone, no idea what solved the problem. I only noticed later that the error only occurred with batch files.

**Comment by xomx** [comment]
For now I don't have an answer for this behaviour but I noticed another such report: https://community.notepad-plus-plus.org/post/98608

> the error is gone, no idea what solved the problem

This could be a hint for us that the problem is probably triggered by some outside-world circumstances (AV?).

> noticed later that the error only occurred with batch files.

Hmm, so it can be the AV, as it likes to control any executable files...
