### ISSUE TITLE
Crash after open with from menu.

### ISSUE THREAD

**Issue by Cabro** [notepad-plus-plus/notepad-plus-plus#1597]
Opening a .cue file using "open with notepad++" from windows explorer menu while having a text (.txt) file already open gives a crash. To be noted that the files are in different folders.
Problem signature:
  Problem Event Name:   BEX
  Application Name: NOTEPAD.EXE
  Application Version:  6.5.3.0
  Application Timestamp:    52c2c5bf
  Fault Module Name:    NOTEPAD.EXE
  Fault Module Version: 6.5.3.0
  Fault Module Timestamp:   52c2c5bf
  Exception Offset: 000ccb84
  Exception Code:   c000000d
  Exception Data:   00000000
  OS Version:   6.1.7601.2.1.0.256.1
  Locale ID:    1033
  Additional Information 1: b403
  Additional Information 2: b4033d7b553dee335a1da6fa889dedd4
  Additional Information 3: c72f
  Additional Information 4: c72fe99b1fb89eb26576cee7cec93a4d

Windows 7 64 bits

**Comment by dail8859** [comment]
> Application Version: 6.5.3.0

First of all I'd recommend updating Notepad++.

**Comment by donho** [comment]
I believe this issue has been fixed since long time ago.
Update your Notepad++ to the latest version (v7.6.6).
If the issue persists, please create a new issue for it.
Thank you.
