### ISSUE TITLE
[Feature request] Make some strings localizable

### ISSUE THREAD

**Issue by AndreiMiloiu** [notepad-plus-plus/notepad-plus-plus#15989]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description of the Issue

As I checked and rechecked the Romanian translation I discovered some strings are unlocalizable. It would be nice if I could translate them, too.

![Unlocalizable strings 8 7 5](https://github.com/user-attachments/assets/0294724b-ff7a-48be-91c4-2d3add68a395)

![Unlocalizable strings 8 7 5 2](https://github.com/user-attachments/assets/ea943d86-809b-4b32-8202-f60a8dd7bc51)

### Describe the solution you'd like.

Make them translatable

### Debug Information

```shell
The problem persisists in every language.
```

I found another untranslatable string. Command Line Arguments... is translatable in the menu but not in the dialog box.

The menu

![Unlocalizable strings 8 7 5 3 1](https://github.com/user-attachments/assets/07eb53f4-9a90-4e55-b4f7-968c9e3aa83d)

The dialog box

![Unlocalizable strings 8 7 5 3 2](https://github.com/user-attachments/assets/8663bd84-c662-442d-97f6-4341622d599d)

The dialog box is completely untranslatable.

**Comment by alankilborn** [comment]
"Trim Trailing and Save" is merely a sample macro.

**Comment by AndreiMiloiu** [comment]
I understand. If macros won't be translated, what about the others?

**Comment by chcg** [comment]
Similar for markdown (preinstalled) which is a UDL from https://github.com/Edditoria/markdown-plus-plus/blob/master/udl/markdown._preinstalled.udl.xml and the name https://github.com/Edditoria/markdown-plus-plus/blob/master/udl/markdown._preinstalled.udl.xml#L17 can't be translated. If you like you could modify it locally for your usage.

**Comment by AndreiMiloiu** [comment]
> Similar for markdown (preinstalled) which is a UDL from https://github.com/Edditoria/markdown-plus-plus/blob/master/udl/markdown._preinstalled.udl.xml and the name https://github.com/Edditoria/markdown-plus-plus/blob/master/udl/markdown._preinstalled.udl.xml#L17 can't be translated. If you like you could modify it locally for your usage.

I understand. Thank you!
