### ISSUE TITLE
Notepad++'s `Process.h` header conflicts with the system `Process.h` header

### ISSUE THREAD

**Issue by ariccio** [notepad-plus-plus/notepad-plus-plus#160]
Notepad++'s [`Process.h` header](https://github.com/notepad-plus-plus/notepad-plus-plus/blob/master/PowerEditor/src/MISC/Process/Process.h) conflicts with the [system's `Process.h` header](https://en.wikipedia.org/wiki/Process.h)!

Notepad++'s `Process.h` header should be renamed. I'm suggesting `NppProcess.h`.

We need to change only two `#include` statements:

- [In `Notepad_plus.h`](https://github.com/notepad-plus-plus/notepad-plus-plus/blob/master/PowerEditor/src/Notepad_plus.h#L108)
- [In `winmain.cpp`](https://github.com/notepad-plus-plus/notepad-plus-plus/blob/master/PowerEditor/src/winmain.cpp#L29)

**Comment by NN---** [comment]
You can use <process.h> to include the system's header.

**Comment by ariccio** [comment]
> You can use to include the system's header.

Use ***what*** exactly? I think you're missing a word there.

**Comment by NN---** [comment]
< process.h >

**Comment by ariccio** [comment]
It causes problems with third party libraries (SQLite). I'm pretty sure that SQLite *was* using that syntax, but because Notepad++ explicitly forces the inclusion of several project folders, [Visual Studio uses Notepad++'s header first](https://msdn.microsoft.com/en-us/library/36k2cdd4.aspx). I'm not sure why this only showed up for me when I was messing around - my guess is that Notepad++'s copy of SQLite is ~~hacked~~ modified - but it's a legitimate concern nonetheless.

**Comment by milipili** [comment]
Do you have any build issue ?

**Comment by ariccio** [comment]
Nope, not right now. However, I'm guessing that some else *will*.

**Comment by milipili** [comment]
I agree on that: it's ambiguous nonetheless. But maybe we could simply use better includes, with something like `#include MISC/Process/Process.h` for example

**Comment by ariccio** [comment]
> But maybe we could simply use better includes, with something like #include "MISC/Process/Process.h" for example

That would work too!
