### ISSUE TITLE
Mapped Drive not accessible in v6.9

### ISSUE THREAD

**Issue by DemersM** [notepad-plus-plus/notepad-plus-plus#1604]
I am on Window 8 and I have upgraded to v6.9 lately. 

Since then, I can't have access to mapped drives in the open file window, and rigth-click / Edit on files located on mapped drives are not opening too.

I know there was issues like this in v6.8.8. (see https://notepad-plus-plus.org/community/topic/10791/notepad-v6-8-6-fails-to-open-files-from-shared-network-drives) 

 Is there a solution to this problem?

**Comment by ClaudiaFrank** [comment]
Sounds like you are running npp elevated (as administrator). Try the same using standard user.
Check debug info (? menu) if admin mode on is set.

**Comment by DemersM** [comment]
Yes are right!

Running in admin mode off resolve the problem

Thank you!
