### ISSUE TITLE
Cursor Disappears

### ISSUE THREAD

**Issue by ghid1** [notepad-plus-plus/notepad-plus-plus#1605]
Cursor occasionally becomes invisible. Restart the app to get it back.

**Comment by ClaudiaFrank** [comment]
Is there any additional information you could provided to get this reproduced?
Like it happens always with xml documents or when doing this and that.
Which npp version do you use? Can you provide the debug info? Can be found under ? menu.

**Comment by SinghRajenM** [comment]
@donho as user has not provided enough info, this ticket can be closed.
