### ISSUE TITLE
Sorting issue in Folder as Workspace

### ISSUE THREAD

**Issue by ChrisAsi** [notepad-plus-plus/notepad-plus-plus#1613]
It seems files that have been currently modified are sorted last in its directory.

![sortingissue](https://cloud.githubusercontent.com/assets/12306539/13656006/48b31a5e-e618-11e5-83b4-9f29f5a0834c.png)

**Comment by Esfera5** [comment]
+1

**Comment by pdsheehan** [comment]
I was looking for this too... and found an earlier issue already raised: https://github.com/notepad-plus-plus/notepad-plus-plus/issues/1541

**Comment by donho** [comment]
I believe this issue has been fixed since long time ago.
Update your Notepad++ to the latest version (v7.6.6).
If the issue persists, please create a new issue for it.
Thank you.
