### ISSUE TITLE
Error message should be renamed

### ISSUE THREAD

**Issue by asashour** [notepad-plus-plus/notepad-plus-plus#1614]
In the attached image, the error message says "Choose Cancel to keep it this installation", and there is no 'Cancel' button.

Also, I guess "to keep it this installation" is not grammatically correct.

![notepad-x](https://cloud.githubusercontent.com/assets/2410127/13664407/57169a28-e6a7-11e5-8747-54173ae8b58d.PNG)

**Comment by SinghRajenM** [comment]
@asashour from the above screenshot "Cancel" button can be seen (3rd last button).
and concern regarding the grammer has alrady been corrected, please check latest version and close the ticket. Thank you.

**Comment by SinghRajenM** [comment]
@dail8859 This ticket also can be closed.
