### ISSUE TITLE
[request] release a pure 64bit binary for windows

### ISSUE THREAD

**Issue by sl1pkn07** [notepad-plus-plus/notepad-plus-plus#162]
Hi

any plans for releasing a pure 64 bit binary for windows?

greeting

**Comment by NN---** [comment]
I am working on it, see: #64 
In order to have x64 build the Scintilla must be updated , it is the essential part.

If you wish you can help me :)

**Comment by donho** [comment]
@NN--- After updating, will you have to modify scintilla source code? If yes, are there a lot of code to be modified?

**Comment by NN---** [comment]
@donho 
Scintilla is x64 ready, so no 64-bit changes.
It can use C++11 regex , if you see it is sufficient , then we don't need boost and the compiler has everything for x64 too.

I don't think there are big changes except that, hope so :)
I am going to do merge requests to make less change specifically for Notepad++ (For instance  https://sourceforge.net/u/nn-n/scintilla/ci/npp_styles/ )

Unfortunately I don't see any answers for any merge request there, so I guess you have to fork the repository on sorceforge and put here the working copy manually or using git-hg (cause it is in mercurial) .
That way it will be easy to update and to maintain changes, just to rebase over the original version.

**Comment by donho** [comment]
@NN--- I'm gonna download Scintilla source of Release 3.5.6 from:
http://www.scintilla.org/ScintillaDownload.html
Adapted and integrated into Notepad++ for next release.

So you can continue your 64 bits task.
For C++11 regex, I'm not against it if it is compatible PCRE, then it will be in future versions.

**Comment by NN---** [comment]
I have read about std::regex and it is not PCRE.
It means that you do need boost::regex .
Although I prefer as less as possible changes to scintilla.
For instance boost regex macher can be done in a separate lib and linked
with scintilla compiled with special define to not implement its own regex.
The additional defines can be in a different file and so on.

In short I think time for solution file.
With projects n++ , scintilla and scintilla additions.

What about moving to VS2015 as it is free and has xp support like 2013
while many C++ bugs are fixed.
It has more good warnings .

Another question for unittests, what do you think?
My opinion that the easiest framework is CxxTest, it requires little work
and easier to use than other frameworks.

**Comment by milipili** [comment]
A 64bits version is on its wayway

**Comment by ray-pixar** [comment]
Where is 64bit binary?
