### ISSUE TITLE
Language: [G]AWK

### ISSUE THREAD

**Issue by SStarker** [notepad-plus-plus/notepad-plus-plus#1620]
Great program! This is my first time on Notepad++. I would be really neat if you could create a [G]AWK language.

**Comment by it3xl** [comment]
This works for me pretty well. I just added the BEGINFILE as one more keyword.
source of all [User_Defined_Language_Files](http://docs.notepad-plus-plus.org/index.php/User_Defined_Language_Files)
[userDefineLang_awk.xml](http://notepad-plus.sourceforge.net/commun/userDefinedLang/userDefineLang_awk.xml)

**Comment by svnpenn** [comment]
https://github.com/Microsoft/vscode/issues/42265

**Comment by svnpenn** [comment]
https://github.com/simonsteele/pn/issues/152

**Comment by svnpenn** [comment]
https://github.com/XhmikosR/notepad2-mod/issues/208

**Comment by svnpenn** [comment]
https://github.com/mirror/scite/issues/1

**Comment by cup** [comment]
@MetaChuh why was this closed

the issue has not been fixed.

**Comment by cup** [comment]
@MetaChuh why was this closed

the issue has not been fixed.

@donho is that a bot?

**Comment by cup** [comment]
https://github.com/notepad-plus-plus/notepad-plus-plus/issues/5530
