### ISSUE TITLE
Allow save immediately when generate new document

### ISSUE THREAD

**Issue by leegom** [notepad-plus-plus/notepad-plus-plus#1622]
When I run *Notepad++* and press <kbd>Ctrl</kbd> + <kbd>N</kbd>, I want to save the new immediately like linux command `touch`.
How can I do it?
Thanks.

**Comment by veepee78** [comment]
ctrl-alt-s?

**Comment by leegom** [comment]
@veepee78 Thanks. My issue was solved with your help.
