### ISSUE TITLE
Update in background

### ISSUE THREAD

**Issue by veepee78** [notepad-plus-plus/notepad-plus-plus#1623]
There are quite a lot updates to the notepad++, would it be possible to add option to automatically update on background, so user would not need to go through wizard every time? As I have multiple computers and almost alla are running np++, it feels like I'm updating the app all the time.

Thank you for the app!

**Comment by dail8859** [comment]
Duplicate of #1573

**Comment by veepee78** [comment]
Yep, duplicate, closed
