### ISSUE TITLE
Open containing folder commands are broken

### ISSUE THREAD

**Issue by jnm2** [notepad-plus-plus/notepad-plus-plus#1628]
The tab right click > Open containing folder in Explorer/cmd options do not work. It seems the path is not being escaped correctly or something along those lines.

(Windows 10 Professional x64, Notepad++ v6.9)

**Comment by jnm2** [comment]
More information, v6.9.1:

Open in cmd words fine. Open in Explorer is broken if there is a comma in the path or filename. An easy repro would be to test `C:\a, b\c.txt` and `C:\a, b.txt`.

**Comment by dail8859** [comment]
Thank you for this additional information!

**Comment by jnm2** [comment]
I just figured out how to repro the original problem for `Open containing folder in cmd`.
Open a file with a `&` in the path.
