### ISSUE TITLE
Unsaved document is lost after undo

### ISSUE THREAD

**Issue by draagyn** [notepad-plus-plus/notepad-plus-plus#163]
When session snapshot/backup is on:

1. Create a new unsaved document and type some text into it
2. Close Notepad++
3. Open Notepad++ (the unsaved document should open up again)
4. Type some more stuff into the unsaved document
5. Hit undo
6. Close Notepad++
7. Open Notepad++

Expected: The unsaved document is still there
Observed: The unsaved document is gone :cry:

**Comment by donho** [comment]
Fixed. (Tested in latest version)
