### ISSUE TITLE
Wierd legacy view of file system and file

### ISSUE THREAD

**Issue by kbuchs** [notepad-plus-plus/notepad-plus-plus#1634]
You probably won't believe this one.

Running on WinServer2008, I edited a file using NP++ back in January. The file has repeatedly changed and I just updated it on the day of this writing. The file shows up in Windows Explorer with today's date. I can open it via the context menu and picking Word Pad and I get the correct contents. However, if I pick NP++ from the context menu, it opens up an old version of the file, which does NOT exist on the filesystem. Further, if I use the Open dialog in NP++, it displays the directory with the file having a January date and opens to the same old content. 

I figured you wouldn't believe this, so I shot a video in Jing. 

[2016-03-15_1715.zip](https://github.com/notepad-plus-plus/notepad-plus-plus/files/174943/2016-03-15_1715.zip)

**Comment by Snorqq** [comment]
I belive you and i like this feature)) NP++ caching unsaved documents.
