### ISSUE TITLE
save button

### ISSUE THREAD

**Issue by SHIVAPRASAD96** [notepad-plus-plus/notepad-plus-plus#1639]
Once the file is saved the save button gets locked, make it more comfortable for user, is the user wants to click it again to save let him do that and print a message that already saved. Actually not issue but yea could be changed.

**Comment by Snorqq** [comment]
Sorry, but as for me current functionality more preferable. I want to know is document saved or not. Locked "save button" show me immediately - document on disk and in editor are the same or not.

**Comment by SinghRajenM** [comment]
@donho and @dail8859, I think no action needed this ticket. So it can be closed.
