### ISSUE TITLE
Realize Shift+Insert and Shift+Delete shortkeys.

### ISSUE THREAD

**Issue by Snorqq** [notepad-plus-plus/notepad-plus-plus#1640]
At least on Windows. This command for me really useful.
If no selection Shift+Insert cut whole string and Shift+Delete paste it. All other editors have this feature.

**Comment by danieltallentire** [comment]
This works for me on Windows 10,, Notepad++ 7.5.1

**Comment by Snorqq** [comment]
Thanks Ctrl+Insert)
But I mean behavior as in IDE (VS for example). When some text selected than Shift+Delete cut it. But when no text selected than cuts all line. It is really convenient.

**Comment by MAPJe71** [comment]
Install the `Visual Studio Line Copy` plugin or see [Community forum topic 14920](https://notepad-plus-plus.org/community/topic/14920/copy-entire-line-without-selecting-it) on how to use either the `LuaScript` or the `PythonScript` plugin to mimic the functionality.

**Comment by Snorqq** [comment]
ok. Thanks
