### ISSUE TITLE
Find window doesn't explain extended mode characters

### ISSUE THREAD

**Issue by ghost** [notepad-plus-plus/notepad-plus-plus#1641]
In the find window, the extended characters like \t, \0, \x..., and regular expression options are not clearly explained. I know they are online but it seems easier to me if they were explained somewhere there. I was thinking of having a help button or explain them when they are moused over or right/middle clicked. I was hoping that it would help users new to NPP quickly, rather than them having to go on the internet and find it until they remember each expression.

**Comment by MetaChuh** [comment]
as there are many guides about extended characters around, they have become self explanatory for most users.

there is no need to add such guide into notepad++ itself.

many thanks and best regards.
