### ISSUE TITLE
Notepad++ slow network files

### ISSUE THREAD

**Issue by Kanthi25** [notepad-plus-plus/notepad-plus-plus#1644]
Notepad++ (v6.9) is very slow in opening network files, switching between tabs, etc.
Please provide the fix asap. Thanks.

**Comment by maksqwe** [comment]
https://github.com/notepad-plus-plus/notepad-plus-plus/commit/86ab42031f3e1688edaab8390d3a82a181abdab0
Possible fix. It should improve the situation.

**Comment by milipili** [comment]
@Kanthi25 : still the issue ?

**Comment by MetaChuh** [comment]
please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins if you update from version 7.5.9 or below.
if your issue still persists, and it is still of relevance, please feel free to file a new issue as easy to understand and reproducible as possible.

thank you for your help and best regards.
