### ISSUE TITLE
Notepad++ Crashing Often

### ISSUE THREAD

**Issue by satdsk** [notepad-plus-plus/notepad-plus-plus#1648]
Hi 
Last one year im using Notepadd++ for my php development,
Whenever i'm using its have a crash Long time usage means a day.

In my office Most of all using same editor. but it happens everyone.

OS : Windows vista
## Issue Info:

**Problem signature:
  Problem Event Name:   BEX
  Application Name: notepad++.exe
  Application Version:  6.9.0.0
  Application Timestamp:    56ca1e0b
  Fault Module Name:    notepad++.exe
  Fault Module Version: 6.9.0.0
  Fault Module Timestamp:   56ca1e0b
  Exception Offset: 000e65f1
  Exception Code:   c0000417
  Exception Data:   00000000
  OS Version:   6.0.6001.2.1.0.256.6
  Locale ID:    1033
  Additional Information 1: 37ba
  Additional Information 2: a5b750d239ada1fed018830f4fb34628
  Additional Information 3: ae98
  Additional Information 4: d7f745dc9c85b2f86de4bcd40ddbce25

Read our privacy statement:
  http://go.microsoft.com/fwlink/?linkid=50163&clcid=0x0409**

**Comment by ClaudiaFrank** [comment]
Does this also happen when starting npp with -noPlugins switch?

**Comment by satdsk** [comment]
I dont install any plugins its just the pre-installed plugins only.
Do i have to uninstall the plugin or not?

**Comment by cmeriaux** [comment]
Try to do a fresh install, remove all your config files (in the install folder and in the rooming folder)

**Comment by donho** [comment]
@satdsk Please provide us the debug infos via menu `? -> Debug Info`

**Comment by satdsk** [comment]
My Debug info

Notepad++ v6.9.1
Build time : Mar 28 2016 - 19:48:40
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows Vista
Plugins : mimeTools.dll NppConverter.dll NppExport.dll PluginManager.dll

**Comment by satdsk** [comment]
Again same problem now upgraded.

## Issue info: 
Problem signature:
  Problem Event Name:	BEX
  Application Name:	notepad++.exe
  Application Version:	7.3.3.0
  Application Timestamp:	58bf6ebc
  Fault Module Name:	notepad++.exe
  Fault Module Version:	7.3.3.0
  Fault Module Timestamp:	58bf6ebc
  Exception Offset:	000f8eee
  Exception Code:	c0000417
  Exception Data:	00000000
  OS Version:	6.1.7601.2.1.0.256.48
  Locale ID:	1033
  Additional Information 1:	83aa
  Additional Information 2:	83aaec1861dfdbb25c35f1cab3fe317d
  Additional Information 3:	541e
  Additional Information 4:	541e599586291d2f24d4946a2d551482

Read our privacy statement online:
  http://go.microsoft.com/fwlink/?linkid=104288&clcid=0x0409

If the online privacy statement is not available, please read our privacy statement offline:
  C:\Windows\system32\en-US\erofflps.txt


## Debug info:

Notepad++ v7.3.3   (32-bit)
Build time : Mar  8 2017 - 03:37:37
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 7 (64-bit)
Plugins : NppFTP.dll PluginManager.dll 


**Can anyone plese fond out why it is happening frequently?**

**Comment by MetaChuh** [comment]
closed due to:
being flagged and confirmed as not reproducible.
concerning outdated versions 6.9 to 7.3.3.
happening on windows vista.
