### ISSUE TITLE
Notepad++ started crashing this week

### ISSUE THREAD

**Issue by daniel-barrows** [notepad-plus-plus/notepad-plus-plus#1660]
I am a regular user of Notepad++. Within the last week, it started crashing regularly (like every 5 minutes). Oddly, it raises an always-on-top error dialog saying it needs to quit, but I can still interact with the application, save my work, type a little more, and close normally. As soon as I click OK on the dialog, Notepad++ actually exits.
I don't use any unusual plugins, I don't think I have updated recently (although maybe it auto-updates... I might have updated python indent plugin...)

### Environment info:
Windows XP
Notepad++ 6.5.3

**Comment by campbeb** [comment]
Is there a reason you don't want to run the latest version, 6.9?
https://notepad-plus-plus.org/news/notepad-6.9-released.html

**Comment by ClaudiaFrank** [comment]
Please start notepad++ with the -noPlugin switch (plugins don't get uninstalled, they just been ignored)
and see if the problem still exists.
What about updating to the current version?

**Comment by dail8859** [comment]
Way too old of version to try to track down bugs in.
