### ISSUE TITLE
Many distracting compile warnings with GCC

### ISSUE THREAD

**Issue by marcows** [notepad-plus-plus/notepad-plus-plus#1662]
There is a huge load of warnings, up to 200 identical warning lines per C++ file. They cause very enlarged output and distract from real problems.

**Comment by marcows** [comment]
Any reason for closing this issue?

**Comment by MetaChuh** [comment]
sorry.

closing as part of closed https://github.com/notepad-plus-plus/notepad-plus-plus/pull/1663

thank you for your help and best regards.

**Comment by marcows** [comment]
#1663 had not been merged, but I'm ok with it...
There are other open PRs like #4776 related to this issue, but no issues had been created for these.
