### ISSUE TITLE
[Enhancement] Visual space after last line

### ISSUE THREAD

**Issue by einsteinsci** [notepad-plus-plus/notepad-plus-plus#1665]
One thing that I've always found missing from Notepad++ is the ability to scroll down a little bit after the last line, so that the last line of the file stays in the middle of the screen, by adding visual space after the last line of a document. Visual Studio and IntelliJ IDEA do this with a little over one screen height's worth of visual space.

I don't know if any other developers find the extra visual space useful; this could just be a pet peeve of mine.

**Comment by xylographe** [comment]
Provided by the [**ScrollPastEOF**](https://sourceforge.net/projects/npp-plugins/files/ScrollPastEOF/) plugin.

**Comment by einsteinsci** [comment]
Oh thanks. Didn't know that existed.
