### ISSUE TITLE
JQuery function list

### ISSUE THREAD

**Issue by Snuwerd** [notepad-plus-plus/notepad-plus-plus#1667]
I would like the function list to support functions for jQuery (that are inside document.ready or inside a jQuery plugin).

**Comment by ClaudiaFrank** [comment]
functionlist.xml is configurable and [here](https://notepad-plus-plus.org/features/function-list.html) is described what needs to be done.

**Comment by shimscharf** [comment]
Check this one out:

https://github.com/notepad-plus-plus/notepad-plus-plus/issues/2012
