### ISSUE TITLE
'Open folder as workspace' breaks 'open files recursively'

### ISSUE THREAD

**Issue by SilkAndSlug** [notepad-plus-plus/notepad-plus-plus#1668]
I have many source files arranged in a deep hierarchy of directories. Before v6.9, I could drag any directory onto NPP and it would open *all* files in the directory. Now, instead, NPP opens a *list* of all files in the directory, i.e. duplicates file-manager functionality while making it massively harder to open multiple files. Please revert, or add a way of recursively opening files e.g. via right-clicking in the workspace panel.

Notepad++ v6.9 on Windows 7, opening files on a shared drive.

**Comment by SilkAndSlug** [comment]
Found a workaround: open the folder in Windows Explorer; search for e.g. "php"  -- this shows *all* files with that file extension; drag-and-drop those files into NPP and it'll open them (and not the workspace panel).

**Comment by TonyBogdanov** [comment]
+1

I can't stress enough how important this feature was for me, please bring it back or most of us will be forced to either revert to an old version or change our text editor of choice.

For me (as a programmer) there are 3 main and only reasons for using Notepad++:

- **Ability to open all files in a hierarchy of directories**
- Ability to search / replace throughout those open files
- Ability to open 300+ files without my computer dying

Remove this feature and you are basically removing all of the main reasons I'm using Notepad++, thus I'll probably just start doing the 10+ extra steps to achieve this in my default IDE.

**Comment by SilkAndSlug** [comment]
If we're listing "things only Notepad++ does", I'll add

* move lines up/down (Ctrl+Shift+arrow); and
* code-folding from the keyboard (Alt+num)

Notepad++ does things differently to other IDEs, and it suits some of us very well. Anything that makes it more like those other IDEs removes its USP, and annoys the users that prefer the "NP++" way of doing things. I'd argue that the NP++-only users are NP++'s key userbase.

**Comment by toddfun** [comment]
I had to fall back to version 6.8.8 as I NEED to be able to drag a folder to Notepad++ and have it open all files recursively. This opens 10 to 50 files for me to review quickly. I don't want to have to open 50 files in ever deeper recursive subfolders. This new "folder as workspace" feature is horrible. Please add a disable options!

**Comment by Ninetheme** [comment]
+100

**Comment by Ninetheme** [comment]
**+100******

**Comment by theleemon** [comment]
Please, bring the old behavior back!

**Comment by vuolter** [comment]
At least make it as optional.

**Comment by Cryosaur** [comment]
This hasn't been fixed yet??

You should stop playing me-too, move this project/workspace nonsense out of the app, and deliver it as a plugin for those who want it.  Like many (most?) other users, I use Notepad++ as a *gasp* more powerful Notepad, and this Folder as Workspace "feature" breaks the app for us.  If I wanted a project-oriented text editor I would use VS Code / Atom / etc., not Notepad++.  /sigh  Please focus on your app's strengths; if you're interested, I'd be happy to share my opinion of what they are.

**Comment by dail8859** [comment]
Closed by 6bbfc7a09584d382fa4f24f3c26ce790ff97323b

**Comment by ShaunDreclin** [comment]
(For people here from google) There is now a config option for this.
Preferences > Default Directory > Open all files of folder instead of launching Folder as Workspace on folder dropping

**Comment by smallscript** [comment]
It would be ideal if we could write something like:
`notepad++ -lfaws *dir-path*`.
