### ISSUE TITLE
HELP the Plug Mananger is not working anymore. "Installation Error:"

### ISSUE THREAD

**Issue by Djamana** [notepad-plus-plus/notepad-plus-plus#1669]
It's NPP 6.9 (on some old WinXP system). It says downloading, some bars, and then a msgbox pops up: **"Installation Error: Installation of NppExec failed"**

Well fired up Process Monitor and there's on suspicious entry:
notepad++.exe QueryOpen C:\Doku....\Anwendungsdaten\Notepad++\plugins\config\PluginManagerGpup.xml NAME NOT FOUND
^- see it's 'PluginManager**Gpup**.xml' theres somewhere a typo in the sources '...G>p<up' maybe that's the reason / the bug.

Deleting 'c:\...Anwendungsdaten\Notepad++' setting so they get reinitialized did help.

**Comment by ClaudiaFrank** [comment]
No, PluginManagerGpup.xml is used for temporary actions, this doesn't indicate being a problem.
The error itself doesn't point to a npp issue - it is just an informal message for you.
E.g. sometimes sourceforge does have an issue when trying to connect to the plugin repository
and you will get the installation error. So, it could be, that even another attempt would have installed
the nppexec but, of course, it could be also that the PluginManagerPlugins.xml was corrupt.

**Comment by dail8859** [comment]
Closing since this seems to be related to the Plugin Manager.
