### ISSUE TITLE
Converting character set to Norwegian character set 

### ISSUE THREAD

**Issue by ravb9z7m** [notepad-plus-plus/notepad-plus-plus#1670]
How could I convert this following SMS messag with Norwegian characters forÆØÅ and in small letters æøå ?:

BEGIN:VMSG
VERSION:1.1
X-IRMC-STATUS:UNREAD
X-IRMC-BOX:INBOX
BEGIN:VCARD
VERSION:2.1
N;ENCODING=QUOTED-PRINTABLE;CHARSET=UTF-8:;;;;
FN;CHARSET=UTF-8;ENCODING=QUOTED-PRINTABLE:
TEL;CELL:+4740817439
END:VCARD

BEGIN:VENV
BEGIN:VBODY
Date:22.03.2016 14:59:25
TEXT;CHARSET=UTF-8;ENCODING=QUOTED-PRINTABLE:I dag har de fleste bilene forhjulstrekk. Motoren ligger over drivhjulene,=
noe som normalt gir godt veigrep selv om veien er glatt. N=C3=A5r du last=
er bagasjerommet fullt av tung bagasje og legger i vei mot p=C3=A5skefjell=
et, forandrer imidlertid ting seg.
END:VBODY
END:VENV
END:VMSG

The "=C3=A5"in the text is "å". 

The other signs shows up like this:

```
æ → %C3%A6
ø → %C3%B8
å → %C3%A5
Æ → %C3%86
Ø → %C3%98
Å → %C3%85
```

The SMS message is taken from an *.vmg message file in my Java cell phone.

Thanks in advance

**Comment by ClaudiaFrank** [comment]
I assume you have a better chance to get this answered by the npp community forum.
https://notepad-plus-plus.org/community
If you agree, may I ask you to close this issue?
