### ISSUE TITLE
VB/VBS comment sign should be ' instead of REM

### ISSUE THREAD

**Issue by pnauta** [notepad-plus-plus/notepad-plus-plus#1674]
Please change line 195 in langs.xml to:

`<Language name="vb" ext="vb vbs" commentLine="'" commentStart="" commentEnd="">`

**Comment by dail8859** [comment]
Pull request #1661 fixes this issue and should be merged in soon.

**Comment by pnauta** [comment]
OK, because this has been an issue for quite long, or I am the last person to code in VBS.
