### ISSUE TITLE
"File has been modified" dialog should have an option to "do this for all files"

### ISSUE THREAD

**Issue by jeremyhaubold** [notepad-plus-plus/notepad-plus-plus#1679]
I frequently use Notepad++ with many files (dozens or hundreds) at once, and sometimes, many of those files change at the same time. It's annoying to have to click "Yes, reopen the file" a hundred times - so much so that I usually opt to kill the process and relaunch it. Having an option to reload all modified files one time would be fantastic.

**Comment by dail8859** [comment]
Duplicate of  #1484

**Comment by jeremyhaubold** [comment]
Thanks.
