### ISSUE TITLE
[Feature Request] Doc Switcher Rearrangement

### ISSUE THREAD

**Issue by ghost** [notepad-plus-plus/notepad-plus-plus#1684]
The Doc Switcher gets a little annoying when you have to close and re-open documents for them to appear the way you want them to be arranged. The ability to rearrange the documents in it would be nice.

**Comment by cajuncool** [comment]
I support this feature request.

You can sort the files in the list alphabetically in ascending or descending order, but you can never get back to the original order (as loaded or manually rearranged)!
So there should be another feature: Go back to the original/manual order.
Thank you!

**Comment by nebosite** [comment]
Please please do this.   The switcher is already a great feature and this would put it over the top.

**Comment by Andronomos** [comment]
Yes, this feature would greatly improve upon Notepad++. I already can't see myself using anything else and the lack of this feature is really my only complaint.

**Comment by pidgeon777** [comment]
Also interested.
