### ISSUE TITLE
Feature: "Clear"/ "Reset" on Shortcut Mapper items

### ISSUE THREAD

**Issue by leewz** [notepad-plus-plus/notepad-plus-plus#1686]
When right-clicking a shortcut item in the Shortcut Mapper, the only options are "Modify" and "Delete". There should also be "Clear", to remove a shortcut, and "Reset", to reset it to the default.

A non-default shortcut should be visually distinguishable from a default shortcut, though this could be a toggled setting.

**Comment by dail8859** [comment]
Closed by 7ab6458978c3f27de7078310cbd7db8a22e867f9
