### ISSUE TITLE
Associate file extension with workspace files

### ISSUE THREAD

**Issue by dail8859** [notepad-plus-plus/notepad-plus-plus#169]
You can already define a session file extension by using Settings > Preferences > MISC > Session file ext. 

Would it make sense to do the same thing for workspace files by allowing a file extension to be specified?

**Comment by donho** [comment]
Could you provide more info about its behaviour, such as: if user double-clicks on a workspace file, what will it happen?

**Comment by dail8859** [comment]
Pull request #209 can be used for reference. It behaves in the same way session files do. If a workspace file extension is defined, and the user double-clicks (or opens by any other means) a file with the workspace extension, the workspace is opened up in the first project panel. (and subsequently the file is *not* opened as a regular file for editing).
