### ISSUE TITLE
'&' does not appear in text if language is c, c++ or c# (NPP V 6.8.5)

### ISSUE THREAD

**Issue by AnalogHome** [notepad-plus-plus/notepad-plus-plus#1692]
Post this next line in Notepad++,

bit_out = (*address & 0x1);

Then set language to "C" or "C++" or "C#".

Ampersand ('&') will not show up.

Windows 7 pro x64, Notepad++ V6.8.5

**Comment by dail8859** [comment]
This is a known problem. Make sure you are not using the Source Code Pro font at all in any of your style settings.
