### ISSUE TITLE
You can support change theme

### ISSUE THREAD

**Issue by xiaoxing598** [notepad-plus-plus/notepad-plus-plus#1693]
It is strongly recommended to support black style theme, similar to the same sublime black theme. Now the interface is ugly

**Comment by WSiaB** [comment]
This is an existing feature. Go to 'Settings > Style Configurator' and select "Twilight" under 'Select theme'. There are currently 21 built in themes.
![screenshot 2016-04-03 12 59 35](https://cloud.githubusercontent.com/assets/1976258/14234623/266733f8-f99c-11e5-8f77-f189366aed9c.png)

**Comment by xiaoxing598** [comment]
Thank you, I found the local configuration.
