### ISSUE TITLE
Update README.md with info howto build scintilla from within Visual Studio

### ISSUE THREAD

**Issue by chcg** [notepad-plus-plus/notepad-plus-plus#1699]
For me it is easier to build also scintilla within the same VS solution as N++, instead of using the command line. Also debugging is easier this way.

Therefore just

https://github.com/notepad-plus-plus/notepad-plus-plus/blob/master/scintilla/win32/SciLexer.vcxproj

need to be added to the VS solution.

Config used to build is the one with boost. Boost version retrieved via nuget is boost.1.58.

All configs are available x86|x64 and debug|release also for scintilla.

**Comment by slitazcn** [comment]
look like visual studio 2013 2015 have c++11 regex support ,so is it possible use it instead boost?at least use on the vs2015 project? this issue i think create a vs projecct file for scintilla much more better

**Comment by chcg** [comment]
See #162, about the drawback of C++11 std::regex. Perl syntax is available with boost, but not with c++11, just ecma script notation (see http://www.regular-expressions.info/stdregex.html)

It is possible to use c++11 regex, if boost is replaced with std in

https://github.com/notepad-plus-plus/notepad-plus-plus/blob/master/scintilla/boostregex/BoostRegExSearch.cxx

and some smaller adaptions.

, see also https://msdn.microsoft.com/en-us/library/bb982727.aspx and
https://stackoverflow.com/questions/5047971/how-do-i-check-for-c11-support
