### ISSUE TITLE
Support indication of programming language in files without extension

### ISSUE THREAD

**Issue by c33s** [notepad-plus-plus/notepad-plus-plus#17]
a native support of auto selecting the right language based on 

- vim comments
- filenames (without extensions)

would be a really great feature.

files like "Vagrantfile" sould be auto highlighted with the ruby language and so on.

https://stackoverflow.com/questions/1984072/indicate-programming-language-in-a-file-without-extension
https://superuser.com/questions/668713/automatically-use-specific-language-in-notepad-for-files-with-no-extension
http://sourceforge.net/projects/npppythonplugsq/files/Modeline%20Parser/

**Comment by dail8859** [comment]
Hi. I'm actually working on a plugin that will do this. The language can be detected based on either file name, file extension, regular expression matches, or possibly other rules. If you have any more examples of files that Notepad++ does not currently detect I'd be glad to use those to test while I'm developing it. I plan on making the rules user-configurable too.

**Comment by c33s** [comment]
@dail8859 as i wrote in the issue, it is about the native support of this feature, without any other plugins and tools. can you add this functionality to the main code and create a PR? would be awesome.

**Comment by dail8859** [comment]
Its not a minor change so it would be a tough time getting the PR accepted. What I can do is finish the plugin and see what people think of it. If it seems like something useful and get a general consensus that it would be useful natively, then it would be pretty easy to integrate it in the main code. I'd hate to put alot of time into a PR just to get rejected.

**Comment by milipili** [comment]
That would be nice to have support for vim modelines, even partial (at least syntax hight., tabs, ...).
 * Simple description of vim modeline: http://www.lornajane.net/posts/2011/using-modelines-in-vim.

**Comment by mat-m** [comment]
@milipili: that would be great, but should be in another request :)

**Comment by milipili** [comment]
Of course :)

**Comment by donho** [comment]
it's done for xml, php, html and bash : https://github.com/notepad-plus-plus/notepad-plus-plus/commit/9b91480ecfc5eb392d562ddab1d530bd439d386e

**Comment by c33s** [comment]
please reopen.

the main issue still exists, the user should be able to add syntax highlighting based upon a filename which have no extension  (like Vagrantfile -> ruby), just xml, php and bash does not solve the general problem.

**Comment by mat-m** [comment]
@c33s : you mean like considering the filename as an extension and being allowed to say 'Vagrantfile' in the ruby extensions list ?

**Comment by c33s** [comment]
@mat-m yes something like that. or as i wrote above, support vim comments.

**Comment by ljader** [comment]
I'm experiencing the same frustration as @c33s every time I open "Vagrantfile" and I need to set syntax to Ruby.

Supporting vim commands can lead to non trivial amount of work, so please consider for now a simpler implementation: 
- if file does not have extension, then treat whole filename as an extension and search for syntax in user settings.

I think the code should go here:
https://github.com/notepad-plus-plus/notepad-plus-plus/blob/master/PowerEditor/src/ScitillaComponent/Buffer.cpp#L206

**Comment by linquize** [comment]
e.g. Makefile

**Comment by c33s** [comment]
@ljader 's solution would greatly improve the usability. just treating the filename as extension if the file has no extension would be great.

@donho please reopen this issue, the request for supporting vim comments is still here.
