### ISSUE TITLE
Line numbers & bookmarks are not removed when closing a file

### ISSUE THREAD

**Issue by wilkowy** [notepad-plus-plus/notepad-plus-plus#1703]
To make sure it is not related to config & plugins:
1. backup&delete all *.xml user configs (this also ensures that "word wrap" is off, otherwise it works ok)
2. backup&delete all *.dll plugins
1. open a text file with more line numbers than screen has (it works ok on first page)
2. press page down, optionally mark some bookmarks
3. close a file with ctrl+w (closing with "x" on menu bar or tab bar works ok)

Effect:
Window is cleared of file contents, but line numbers and bookmarks stays intact.

Fix:
Switch application (alt+tab) and return or click inside document window.

N++ 6.9.1 on XP SP3 32b

**Comment by wilkowy** [comment]
I've just experienced another similar issue which might be connected with this one, however I'm unable to reproduce it in steps except the situation where it happens.
Anyway:
- there are open several tabs (11), one of them with bigger file (>15 MB, in total whole process takes ~60 MB in RAM), there are many bookmarks marked in one of the files (almost 400), some are text files, other use syntax hilighting (xml/perl/custom), project workspace is used (not the new "Folder as Workspace", it's "Project Panel")
- upon opening new file blank file is opened, but line numbers stays from previous tab as well as bookmarks and all reverts to normal when clicking a workspace or switching application

However this issue does not happen on clean setup, so it might be related with some options/opened files (large number of bookmarks?), however it behaves the same as described above.

(same N++ version)

**Comment by donho** [comment]
I believe this issue has been fixed since long time ago.
Update your Notepad++ to the latest version (v7.6.6).
If the issue persists, please create a new issue for it.
Thank you.
