### ISSUE TITLE
Disabling "x" on tab does not shrink its size for the first time

### ISSUE THREAD

**Issue by wilkowy** [notepad-plus-plus/notepad-plus-plus#1704]
1. (clean setup without plugins)
2. Start N++.
3. Open preferences and uncheck "Show close button on each tab".

Effect:
The "X" is removed, but tab size is not reduced (it does not matter how many tabs are open). It does shrink however on further checking/unchecking this option, until next N++ restart (but only if we exited with enabled option).

N++ 6.9.1 on XP SP3 32b

**Comment by kraint** [comment]
Reproduced this with N++ 6.9.1 and 6.9.2 on Win8.1 64b.

**Comment by donho** [comment]
I believe this issue has been fixed since long time ago.
Update your Notepad++ to the latest version (v7.6.6).
If the issue persists, please create a new issue for it.
Thank you.

**Comment by wilkowy** [comment]
@donho Yes it has been partially fixed, however disabling "Show close button on each tab" does not cause tab reordering event - enabling "x" can cause tab list to occupy more tab lines, but disabling it does not reduce it to previous state. Only closing any tab causes reordering.
