### ISSUE TITLE
Problem with big (not reduced) tab size

### ISSUE THREAD

**Issue by wilkowy** [notepad-plus-plus/notepad-plus-plus#1705]
1. (clean setup without plugins)
2. Start N++.
3. Open preferences and disable "Reduce" - now the tab is like active tab line plus icon+text under: http://oi66.tinypic.com/iptilx.jpg
4. Click any number of times "Show close button on each tab" (here twice) and tab icon is shifted 1px up&left, tab is also smaller: http://oi66.tinypic.com/111njn9.jpg
5. Restart N++ and the tab is even smaller, wider and icon is larger: http://oi66.tinypic.com/b8kakh.jpg

This might be somewhat related with #1704

N++ 6.9.1 on XP SP3 32b

**Comment by kraint** [comment]
Reproduced this with N++ 6.9.1 and 6.9.2 on Win8.1 64b. 

Tab height is being changed(reduced) by several pixels when the tab close button is disabled after the Reduce option is disabled. Tab length is also reduced by 1 pixel.
Re-enabling the close button option does not fix this.

**Comment by wilkowy** [comment]
Just to leave a note - in N++ 7.6.6 it is still not fixed.
