### ISSUE TITLE
Broken searching in regex mode - floating/vanishing bookmarks

### ISSUE THREAD

**Issue by wilkowy** [notepad-plus-plus/notepad-plus-plus#1706]
1. (clean setup without plugins)
2. Open a quite big text file (source file is better) with many lines and repeated words on few "pages". (language does not matter)
3. Bookmark some lines.
4. Open Find dialog, switch to "Regular expression" (extended mode is ok) and now this is tricky as I haven't figured out the pattern:
- some searches cause our bookmarks (from currently visible range) to stick with the screen and follow our search on different pages
- some searches cause bookmarks to disappear or other bookmarks reappear in wrong line

Bookmarks are restored when document is scrolled.

N++ 6.9.1 on XP SP3 32b

**Comment by donho** [comment]
Update your Notepad++ to the latest version (v7.6.6).
If the issue persists, please create a new issue for it.
Thank you.
