### ISSUE TITLE
Focus doesn't move to within tab when creating new tab

### ISSUE THREAD

**Issue by Eldaw** [notepad-plus-plus/notepad-plus-plus#171]
Normally, if you double-click an empty area on the tab bar to create a new tab, then focus moves to inside that new tab, ready for typing or pasting text into that new tab.

However, if the focus is currently inside the Find Result pane and you double-click an empty area of the tab bar to create a new tab, focus does not move to the text area inside the newly created tab.

This means, for example, that if you've copied some text from the Find Result pane, and want to paste that into a new file, you have to double-click the tab bar and then click again to move the focus into that new tab.

**Comment by Eldaw** [comment]
Any chance someone could fix this, pretty please! :)

**Comment by mvrbaski** [comment]
Would love to have this, too!
