### ISSUE TITLE
Documentation comment autocomplete + asterisk autoinserting

### ISSUE THREAD

**Issue by Craftist** [notepad-plus-plus/notepad-plus-plus#1716]
As you know, documentation comment is a comment looks like that:

``` csharp
/**
 * Documentation example
 * @author AuthorName
 * @version 1.0
 **/
```

So I want that Notepad++ will autocomplete asterisks (like Eclipse) and will autocomplete @these @tags.

**Comment by MetaChuh** [comment]
i'm sorry, but we have not been able to understand this request for a long time.

if your issue still persists, and it is still of relevance to you, please feel free to file a new issue as detailed and reproducible as possible.

```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
(no extra account is needed, just use your github account to sign in)
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)
