### ISSUE TITLE
Do not delete backup file after closing the document

### ISSUE THREAD

**Issue by eight04** [notepad-plus-plus/notepad-plus-plus#1719]
Currently if you make any changes to a document, the backup feature will create a snapshot to `%appdata%\notepad++\backup`. If you close the file and discard changes, the snapshot will be delete too. I would prefer Notepad++ not deleting it, including unnamed files (i.e. new 1, new 2, ...).

Can we have an option to keep those snapshots?

Notepad++ v6.9

**Comment by donho** [comment]
Current behaviour is the concist way to keep this feature work, change the current behaviour could bring the regressions.

**Comment by eight04** [comment]
I'm not sure what is the regression here. But the advantage of this option is that, if the user accidentally closed his document, he can get it back from the backup folder (currently this feature only works if NPP crashed).
