### ISSUE TITLE
Regex replace and brackets

### ISSUE THREAD

**Issue by Tiax** [notepad-plus-plus/notepad-plus-plus#1720]
Unfortunately, I couldn't find any info on this - this has been bothering me for a while now:

When using the search+replace with regular expressions, why do I need to escape brackets in the "Replace with" string? I never seen any scripting/programming language where this was the case.

**Quick example**:

Find what: `(\w+)\\(\w+)`
Replace with: `list.push("$2")`

would replace an input string
`FOO\BAR`

with (note the missing brackets)
`list.push"BAR"`

instead of the expected
`list.push("BAR")`

while a "Replace with" `list.push\("$2"\)`
yields the expected result - but why?

**Comment by dail8859** [comment]
It is just how the regular expression engine works. Alot of characters have a special meaning. See [this](http://www.boost.org/doc/libs/1_55_0/libs/regex/doc/html/boost_regex/format/boost_format_syntax.html) for the full documentation of replacement strings.

**Comment by Tiax** [comment]
Ahh thanks - that makes (a little) more sense then. I assume there's currently no way to disable those "advanced" features and just have it substitute matched groups via $n, right?

**Comment by dail8859** [comment]
Nothing short of major changes like recompiling Scintilla.
