### ISSUE TITLE
Feature Request: Track last modified date/time for unsaved files

### ISSUE THREAD

**Issue by hyrmedia** [notepad-plus-plus/notepad-plus-plus#1721]
I **love** the fact that Notepad++ (usually) preserves unsaved files in their current state _even when the application is closed_!

However, this does often lead to a bit of **tab clutter** piling up (_I admit it -- I'm a digital hoarder_). Every few days I have to go through my tabs and see which of my "new" unsaved files what's just cruft and what needs to be saved for later reference.

It would be extremely useful for me to add a new column to the the "Windows" dialog -- **Date Modified**.

In the case of saved files, of course, this would just list the Date Modified provided by the file system; but in the case of New or Modified, unsaved files (any file that currently has an "asterisk" beside its name), this column would display the last date/time that any activity happened within the document (characters typed, backspacing/deleting, pasting from clipboard, document encoding changes, modified by a plugin, etc).

Of course this would also require the application to track the last time the tab had any activity -- probably a debounced keypress event or something like that, so that the timestamp is updated (a) a few seconds after the last keypress within the document, (b) when the user switches to another tab (assuming there's been any activity), or (c) when the user Alt-Tabs away from, or closes, the application.

**Comment by degerton** [comment]
Agreed! I found this request because I was googling for a way to see a last edit datestamp ... I have too many open windows !

**Comment by MetaChuh** [comment]
@hyrmedia 

in the newest versions of notepad++ you can rename any new, unsaved tab for immediate spotting.
(feature especially implemented for us "tab hoarders"😉)
this way we won't even have to consult the windows dialogue, except if we want to sort our unsaved tabs, which we have previously renamed to an alphabetically sortable, logical pattern.

if you wish, please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins if you are on 7.5.9 or below.
if your needs still persist, and it is still of relevance to you, please feel free to file a new issue as detailed and reproducible as possible.

thank you for your help and best regards.

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
(no extra account is needed, just use your github account to sign in)
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)
