### ISSUE TITLE
Feature Request: Tooltip (with partial file contents) for open Windows/tabs dialog

### ISSUE THREAD

**Issue by hyrmedia** [notepad-plus-plus/notepad-plus-plus#1723]
I'd like to suggest adding standard tooltips to the Windows dialog in Notepad++.

For the Path and Type columns, this would just display the content of the field, in case the column is too narrow and the contents are truncated (with an ellipsis).

However, when hovering over the Name column -- in addition to showing the full filename -- I would like it to also display the first, say, 20 lines or so **of the actual file contents.**

That way I can see exactly which files are which, especially in the case of unnamed "new" files or those with somewhat arbitrary filenames, and easily select and save the ones I need, or close the ones I don't need.

**Comment by MetaChuh** [comment]
@hyrmedia 

to show the full paths at the windows dialogue, please double-click on the column separator lines.

thank you for your support and best regards.

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
(no extra account is needed, just use your github account to sign in)
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)
