### ISSUE TITLE
Notepad++ fails to properly encode extended plane unicode characters

### ISSUE THREAD

**Issue by Groostav** [notepad-plus-plus/notepad-plus-plus#1727]
Hey guys,

I'm new to encoding but I'm pretty sure I've got this one down to a problem in notepad++. This might just be me realizing how silly I am.

However, I wanted to test our applications ability to work with unicode. I'm using a library called [largeText](https://github.com/fge/largetext) to scan files. That library specifies an encoding scheme, so i flipped it up to UTF-16BE and asked it to read a file containing the character `U+10330` which is `𐌰`, which is not in the standard plane. 

NotePad++ seems incapable of saving an extended-plane character to a text file properly.

To reproduce
1. open notepad ++
2. change encoding to UTF-16BE
3. paste in 𐌰 
4. notice that the character is correctly displayed.
5. save the file & close notepad++
6. re-open the file

**Actual**: notepad++ displays the single character `Ќ`
**Expected**: notepad++ displays the character `𐌰`

I _believe_ I'm getting the 'correct' behavior by opening the file under regular notepad, pasting in the text and saving. Upon opening that document in notepad++, i get the hex blocks `xED``xA0``x80``xED``xBC``xB0`, 6 bytes that i _believe_ correspond correctly to `U+10330`

**Comment by xylographe** [comment]
See #801, #1360, and #903.

You'll have to save files with characters outside the BMP in UTF-8 (or UCS-4) encoding.

**Comment by JTBlum** [comment]
I have a similar problem where I've saved a document as UTF-8, but multiplication and division signs are coming out as different characters.  To reproduce:

1. Open Notepad++
2. Ensure you are using a font that supports the multiplacation and division characters (Consolas for me)
3. Create a new document and ensure "Encode in UTF-8" is checked in the encoding menu
4. Paste in ×÷ (see http://www.fileformat.info/info/unicode/char/00d7/, http://www.fileformat.info/info/unicode/char/00f7/)
5. Save the file
6. Select File > Reload from Disk

**Expected**: You see a file with ×÷ in it.
![image](https://cloud.githubusercontent.com/assets/6411750/23621148/274448de-025f-11e7-89f6-a0e65d21e49c.png)
**Actual**: You see a file with ร—รท in it.
![image](https://cloud.githubusercontent.com/assets/6411750/23621119/114477e8-025f-11e7-95e6-455db0f7cec5.png)

**Comment by cup** [comment]
https://github.com/notepad-plus-plus/notepad-plus-plus/issues/1360
https://github.com/notepad-plus-plus/notepad-plus-plus/issues/1727
https://github.com/notepad-plus-plus/notepad-plus-plus/issues/801
https://github.com/notepad-plus-plus/notepad-plus-plus/issues/903

**Comment by MetaChuh** [comment]
first of all, our apologies for this very late reply:

@Groostav 

unfortunately this is a limitation on how the implemented scintilla component, which is an external project, handles and renders alternate endianness characters, and can currently not be fixed at the notepad++ part.
our apologies for that.

@JTBlum 

the autodetect character encoding feature can only estimate an encoding to its closest match.
the lesser information it has, the more probable it is that it will fail.
if you frequently have to handle such cases:

* please go to `settings > preferences > misc` and **disable** `auto detect character encoding` as seen at the screenshot below.

![settings - auto detect character encoding](https://i.imgur.com/9SZ5ufh.png)

* then go to `settings > preferences > new document` and set your preferred default encoding to e.g utf-8, as seen at the screenshot below.

![Imgur](https://i.imgur.com/AarYeSx.png)

after that you will be able to edit and reload your utf-8 files, like your given `×÷` example, without data corruption, nor being interpreted as tis-620 (thai).

many thanks for your help and support.

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
(no extra account is needed, just use your github account to sign in)
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)
