### ISSUE TITLE
Folder as Workspace suggest

### ISSUE THREAD

**Issue by hcqmaker** [notepad-plus-plus/notepad-plus-plus#1728]
1. add right menu refresh, some time i add a file in path, but can't found in Workspace
2. add recent open list
3. only open one level path, if a path to depth and has more files it will be slow

**Comment by speedoops** [comment]
I'd like to add one more wish, even though this issue is opened over 3 years.
4. Add right menu to quick add **"New Folder", "New File" and "Rename File"**

**Comment by donho** [comment]
> add right menu refresh, some time i add a file in path, but can't found in Workspace

Then it's a bug. please open a bug for it.
