### ISSUE TITLE
Dirty flag is wrong after closing notepad++ without saving a file.

### ISSUE THREAD

**Issue by sanastasiou** [notepad-plus-plus/notepad-plus-plus#173]
Reproducing this bug is quite easy.
1) Default backup settings.
2) Just open any file and edit it, e.g. press whitespace.
3) Close notepad++ instance without saving the file. ( A backup file is created ).
4) Open notepad++. Notice that the file's dirty flag is on and you can save it. ( Scintilla reports the file however as not modified )
5) Click Save, CTRL+S etc. to save the file.
Expected behaviour : File is saved, backup is removed, dirty flag is removed, save options disabled without further editing of the file.
Observed behaviour : File is saved, backup is removed. Drity flag remains active ( little disk on filename is red ), user can click save ad infinitum.
So there appears to be an incosistency between backup, dirty flags and whatever Scintilla reports.
I am writing a plugin about Notepad++ that's how I find this out.
If I can be of more help let me know.

**Comment by JolarEQ** [comment]
I've noticed this issue myself.  To add a little to it, if you close the file (just the file, not Notepad++) it then asks you if you'd like to save it.  Clicking yes will save it and then the next time you open and edit the file, it will then allow you to save.

This is after the file won't save when clicking Save (as mentioned in the post above.)
