### ISSUE TITLE
Shift + Ctrl + Z as a hot key for Redo

### ISSUE THREAD

**Issue by realplay69** [notepad-plus-plus/notepad-plus-plus#1731]
Hi. I use Notepad++ a lot but I keep screwing up trying to redo changes using Shift + Ctrl + Z. Then I have to type everything again.
Most of common editors use that key combination so it's hard to switch to another combination.
Is that possible to add it as hot key too?

**Comment by dail8859** [comment]
Already there in v6.9.1

**Comment by realplay69** [comment]
Awesome!!! Updated just now.

**Comment by triAlexIljin** [comment]
Just curious thing with this feature.
I just have upgraded Notepad++. The installer suggests to disable check spelling plugin due stability issues. But I do not have any issues with this plugin, therefore I have chosen to keep the plugin active.
Right after that notepad shows the change log and the check spelling plugin highlights a word at the 7th point.

> `7.  Add Ctrl+Shift+Z shorcut for Redo.`

So, I could notice a tiny issue spelling a line in the change log about the "Shift + Ctrl + Z undo" feature.
