### ISSUE TITLE
Block comment for SQL language

### ISSUE THREAD

**Issue by fernandozap2** [notepad-plus-plus/notepad-plus-plus#1732]
If you set a block comment in a block comment, the comment format is broken...
Example:
![npp_blockcommenterror](https://cloud.githubusercontent.com/assets/18337184/14367355/f8675f00-fced-11e5-916c-a3e750986f48.png)

**Comment by sfrey2** [comment]
Additionally, if the start of a block comment "/*" is within a column name, NPP starts the comment when it should not.

Example:
![image](https://user-images.githubusercontent.com/10929720/28580233-eaad37f4-712c-11e7-8436-d2c8d8f6cf2a.png)
![image](https://user-images.githubusercontent.com/10929720/28580255-f521dfb4-712c-11e7-950e-fc80f8b989fe.png)
but in NPP:
![image](https://user-images.githubusercontent.com/10929720/28580297-10ddcf74-712d-11e7-8cba-6d79b859c952.png)

This can be troublesome when dealing with SQL FOR XML PATH syntax, which may utilize column names with "/*" as below:
![image](https://user-images.githubusercontent.com/10929720/28580343-336fd820-712d-11e7-91fa-623ff57d85dd.png)

**Comment by donho** [comment]
It's about Scintilla behaviour but not Notepad++'s one.
