### ISSUE TITLE
Feature request: Navigate backward and forward

### ISSUE THREAD

**Issue by ig0rmin** [notepad-plus-plus/notepad-plus-plus#1733]
Many IDE text editors have a feature that allow you trace back all locations that you have seen in a document. 
For example I open a document then go with a search request to the line 100, then click to the function in the function list window and go to the line 200, then scroll screen and click to the line 230. 
Then I should be able to do "Navigate backward" and editor will focus on the previous line I've seen (in our example, line 200). Click once again and go to the line 100, and so on. 

For example in VS such a feature implemented as Ctrl+- shortcut. 

It would be nice if NPP support similar feature.

**Comment by drauch** [comment]
Would love to see that feature too!

**Comment by bakasmarius** [comment]
Me too!!

**Comment by hdnshare** [comment]
Please support this feature like Visual Studio.

**Comment by jlfdiaz** [comment]
There is a LocationNavi plugin for Notapad++ 32.  It would be nice to leverate this plugin to implement build-in navigate back forward feature.

**Comment by ppwebju** [comment]
Yes please implement this.
Such a good editor, so why does it lack such a basic navigation facility.

**Comment by isaacdavenport** [comment]
I would really like to see this available in the 64 bit version since locationnav is defunct.

**Comment by alucard-o** [comment]
Same here please !

**Comment by QBkGames** [comment]
Yes, I would like this feature too.

**Comment by fanblade** [comment]
The LocationNav plugin used to provide this feature, but it is incompatible with 64-bit Notepad++. Please add this feature to Notepad++!

**Comment by jamesford42** [comment]
Please add this feature. I'm constantly getting my documents mixed up when notepad++ tabs between them when i hit the mouse back/forward buttons, expecting it to be navigate back/forward like in visual studio.

Also, can i please disable the mouse button next/prev document binding? I don't see mouse shortcuts listed in the shortcut configure dialog window.

**Comment by Alexperte** [comment]
I would like this feature, too!

**Comment by PHermanov** [comment]
This feature would be cool to have.

**Comment by AlexSkuz** [comment]
The feature would be handy for daily using

**Comment by AndriiOzemko** [comment]
It would be helpful. Please, add this feature.

**Comment by iksa2** [comment]
One more vote for this feature from me

**Comment by donho** [comment]
Use concerning plugins.
