### ISSUE TITLE
[Request] AutoHotkey Syntax

### ISSUE THREAD

**Issue by Masonjar13** [notepad-plus-plus/notepad-plus-plus#1734]
AutoHotkey is getting more usage every day, and Notepad++ is (arguably) the best editor for its scripts. I personally use it exclusively. Syntax highlighting already exists and is maintained here: https://autohotkey.com/boards/viewtopic.php?f=7&t=50

However, I would greatly enjoy it being a default language.

**Comment by Masonjar13** [comment]
I noticed there was a failed attempt. Any hope of a proper implementation?

**Comment by Masonjar13** [comment]
Gonna give this a gentle bump..

**Comment by dail8859** [comment]
Unfortunately this would need to be a feature added to Scintilla (which is what Notepad++ uses to highlight code). For now your best option is to use the user defined language.

**Comment by Masonjar13** [comment]
Seems to just need a new lexer type, then implementation into the styles, correct? Doesn't seem too complicated for anyone who knows what they're doing. I'm not very good with C++, but I could take a crack at it.. If I knew what the functions defined were for. Is there any documentation available for writing these definitions? I've already been using the user defined language file for a few years, but I'd like for it to be officially supported, especially since it's incurring a popularity spike.

**Comment by dail8859** [comment]
Yes you would need a new lexer. [Here](https://github.com/notepad-plus-plus/notepad-plus-plus/tree/master/scintilla/lexers) is the current set of lexers.

> Is there any documentation available for writing these definitions?

Your best option is to look at existing lexers. You can always try posting to the [Scintilla](https://sourceforge.net/projects/scintilla/) project as well. Presumably no one else is currently working it but you never know.

**Comment by Masonjar13** [comment]
It appears that a lexer has already been made, but it's a bit outdated. Will it still work or does it require updating?
https://github.com/RaptorX/LexAHKL/blob/master/scintilla/lexers/LexAHKL.cxx

**Comment by dail8859** [comment]
No clue. You'll have to see if it compiles and how well it works. It makes me wonder though why someone would go to the trouble to make one and it not get built into the official Scintilla.

**Comment by Masonjar13** [comment]
The makefile appears to be of a different version. I've got VS Community 2015 with visual C++ support only (not mobile). Says it's unable to update the makefile as well. Is there something else I need? Windows 10 SDK or something? Sorry for the amateur problem.

**Comment by dail8859** [comment]
I'd recommend getting the latest version of Scintilla/SciTE (which does build with VS2015) and grab the required lexer/header/etc from that repo and get it working with SciTE. Once you do that you can probably submit a patch to the Scintilla project. Then whenever Notepad++ updates it's internal version of Scintilla (which doesn't really happen that often) that lexer will be available (with a bit more work within Notepad++)

**Comment by Masonjar13** [comment]
None of the makefiles work, but I was able to build it from the project file. Unfortunately, when I introduced LexAHKL.cxx, there were 102 errors, almost all of which are "undeclared identifier." While I haven't looked through them all, none of the other lexers appear to have objects, where this one does. Seems like a drastic API change by Scintilla.  It is over 3 years old.. I'll look into it, as much as I can anyway.

**Comment by Masonjar13** [comment]
Alright, well SciLexer.dll (32-bit) is built and working, but I'm not getting it to show up in N++. I took the changes from the failed pull request, made slight changes (naming convention, to match the lexer), and now I'm stuck.

**Comment by dail8859** [comment]
First of all keep in mind that the Notepad++ project doesn't accept patches for lexers/scintilla, it just uses it as is and updates it from time to time.

However you are certainly able to build a custom SciLexer.dll to use. There is a little bit of work within Notepad++ to get it fully working. I'd recommend taking a look at [this PR](https://github.com/notepad-plus-plus/notepad-plus-plus/pull/1439/files) adding a new lexer. Several files need some minor tweaks.

**Comment by MetaChuh** [comment]
please use one of the existing autohotkey udls.

many thanks and best regards.
