### ISSUE TITLE
Feature request: GLSL syntax highlighting.

### ISSUE THREAD

**Issue by TheZeus121** [notepad-plus-plus/notepad-plus-plus#1735]
I would like to see GLSL highlighting added to Notepad++.
I know that it isn't very problematic since there are available plugins which add GLSL, but on the other hand it would be much easier for users to get the highlighting, especially on fresh installations.
Also, it shouldn't be hard to implement.

**Comment by MetaChuh** [comment]
please use one of the availabe glsl user defined languages.

many thanks and best regards.
