### ISSUE TITLE
Notepad++ v6.9.1 crash after update destroying opened file

### ISSUE THREAD

**Issue by herbherb** [notepad-plus-plus/notepad-plus-plus#1736]
Hi all,
I have recently updated to v6.9.1. Just now Notepad++  has crashed, unfortunately leaving the .css file I was working on blank. I have been using Notepad++ for a  long time and  had the same problem years ago once - it seemed to have been fixed after a short time. The bug is very annoying, as it can destroy several hours of work if a file has not been backed up yet.

Here is the debug info:

Notepad++ v6.9.1
Build time : Mar 28 2016 - 19:48:40
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 7
Plugins : ClipboardHelper.dll ColorPicker.dll mimeTools.dll NppConverter.dll NppExport.dll NppFTP.dll PluginManager.dll 

Thanks

**UPDATE:**
It happened again. Having found how to recover the destroyed file as described below, it is not a big problem anymore for me personally, but I do see it as a serious bug. I must add that my system is stable and I did not have a similar issue with other programs.

_For my immediate need, after some searching I was able to resolve the problem of the lost file content  with the help of this page: [https://superuser.com/questions/521628/where-are-notepad-config-files] - I was able to find the last working version of the file in C:\Users<username>\AppData\Roaming\Notepad++\backup_
_

**Comment by sanastasiou** [comment]
Yeah I am noticing several crashes lately on different machines when files are added to directories/deleted or saved.. Something has gone terribly wrong.

**Comment by aplatypus** [comment]
Yes.  This has just happened to me.  I updated yesterday (2016-06-22).

This is annoying -- but the big problem is that I"ve lost half-a-day's work.  The file WAS saved on disk and somehow the crash has wiped it to ZERO length!

Is possible the file-date is 'on disk' but the file was truncated??  Any suggestions on how I might recover the data?

Does Notepad++ keep a temp file some place I can hack?

I have the "periodic backup" option set (7 seconds) .. And most of my file was there -- BUT given the nature of the crash and wiping the file, it is possible for the back-up to be wiped also.  May editors keep a working-file about in /tmp.  does notpad++ do something similar -- just in case?


Build: 21-Feb-2016 21:27:55

Which seems a bit dated, for a recent update???


DEBUG INFO pop-up shows:

Notepad++ v6.9
Build time : Feb 21 2016 - 21:27:55
Path : B:\dev\notepad++\v06.09\notepad++.exe
Admin mode : ON
Local Conf mode : OFF
OS : Windows 7
Plugins : mimeTools.dll NppConverter.dll NppExport.dll PluginManager.dll

**Comment by donho** [comment]
I believe this issue has been fixed since long time ago.
Update your Notepad++ to the latest version (v7.6.6).
If the issue persists, please create a new issue for it.
Thank you.
