### ISSUE TITLE
View shifts during vertical scrolling

### ISSUE THREAD

**Issue by HYBRID-BEING** [notepad-plus-plus/notepad-plus-plus#1737]
For some reason, when scrolling huge text up or down very fast with mouse wheel view seemingly randomly shifts horizontally to left or right respectfully. Does not happen when scrolling up at top or down at bottom.
Windows 7, Notepad++ 6.9, only standard plugins installed.

**Comment by donho** [comment]
I believe this issue has been fixed since long time ago.
Update your Notepad++ to the latest version (v7.6.6).
If the issue persists, please create a new issue for it.
Thank you.
