### ISSUE TITLE
Change of GUI for future versions of Notepad++

### ISSUE THREAD

**Issue by shiraz14** [notepad-plus-plus/notepad-plus-plus#1738]
Notepad++ is an extremely useful program, but I was hoping that someone in its development team would change its interface to a ribbon-like interface (using the WPF standard). The ribbon in WPF can also be minimized (according to the user's needs) should the user desire to do so.

**Comment by igorm6387** [comment]
I don't think this is a good idea. Changing interface to the ribbon don't introduce any additional features or make GUI more convinient. For my expirience such transition is only "god, where is this icon disappeared?". I always loved npp for it just works and solves my problem. Not for the need of re-educating myself every year or two for the completely new GUI.

**Comment by xylographe** [comment]
As I don't like the ribbon interface, I'm hoping donho will not implement this “feature”.

@shiraz14 Perhaps you could have a look at [BowPad](http://stefanstools.sourceforge.net/BowPad.html), which is also based on Scintilla.

**Comment by MetaChuh** [comment]
please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins if you update from version 7.5.9 or below.
if your issue still persists, and it is still of relevance, please feel free to file a new issue as easy to understand and reproducible as possible.

thank you for your help and best regards.
