### ISSUE TITLE
Toolbar has a drag handle on its left side which is always visible

### ISSUE THREAD

**Issue by Eldaw** [notepad-plus-plus/notepad-plus-plus#174]
The toolbar has a drag handle (vertical dotted line) permanently taking up space on its left side. This kind of drag handle is normally visible when toolbars are in an unlocked state so they can be rearranged, but in this case appears to serve no purpose whatsoever.

Currently there is unfortunately no way to lock the toolbar in order to make the pointless drag handle disappear.

**Comment by milipili** [comment]
See  4d20902
