### ISSUE TITLE
Fortran syntax highlighting broken with 6.9.1 update

### ISSUE THREAD

**Issue by Pecnut** [notepad-plus-plus/notepad-plus-plus#1741]
With the 6.9.1 update (supposedly now supporting Fortran77), the Fortran syntax highlighting (both 'free' and 'fixed') in Notepad++ no longer recognises lines starting with a 'c' as comments. It used to recognise lines beginning with "c", "C", or "!".

**Comment by WGriffing** [comment]
Is anyone already working on this issue? If not, I did some preliminary investigation and would like to keep working on this, but only if that's okay and nobody else is already doing it. 

I have never even attempted to contribute to a project before, so I'm trying not to step on anyone's toes. Please let me know if I'm doing something wrong.

**Comment by dail8859** [comment]
@WGriffing Things are kind of slow moving around here so feel free to help any way you like :) Also, keep in mind that if you shouldn't make any changes to anything under the `scintilla` directory. Notepad++ uses Scintilla as-is.

**Comment by WGriffing** [comment]
Thanks @dail8859. As you inferred, the change I was going to propose was within the `\scintilla\lexers\` directory. Now I know better than to try.

I will look to see if there is an alternative, but I'm guessing that I won't find one. If that is the case, I'll try to submit to scintilla.

**Comment by dail8859** [comment]
It may very well be fixed in the latest version of Scintilla.  The version Notepad++ uses is several versions behind.

**Comment by WGriffing** [comment]
Great minds think alike. 

When I saw your first reply, I retrieved the latest version of the file from their repository. It has received some updates that appear to be minor refactoring. The relevant section of the file is the same. Just to be sure, I also grabbed the newest version of SciTE (3.6.4) and it exhibits the same highlighting behavior.

**Comment by dail8859** [comment]
So I don't know fortran at all, but what exactly is the problem?

![capture](https://cloud.githubusercontent.com/assets/3694843/14691961/20f1ee48-0722-11e6-8aea-22d39463b00d.PNG)

**Comment by WGriffing** [comment]
Interesting. I get different results, but this gives some new avenues to explore. I suspect it shouldn't matter but I'm running Windows 10. Before digging into the code, I should have performed some basic troubleshooting.

But for the same of completeness, below is the behavior that I see:

**In free form:**
- `!` works as I expect...it can be used to start a comment at the beginning of a line or anywhere on the line. 
- `c` and `C` do not work for me...should start comment highlight when they are the first character on a line like your picture shows.

![freeform](https://cloud.githubusercontent.com/assets/18578940/14692333/67b33128-0724-11e6-96f5-d124c8020026.png)

**In fixed form:**
Neither `!` nor `c` nor `C` appear to work and for that matter none of the highlighting appears to be functional.

![fixedform](https://cloud.githubusercontent.com/assets/18578940/14692354/8d340576-0724-11e6-9f23-d7e324bce018.PNG)

**Comment by dail8859** [comment]
Try deleting (or removing if you want it saved)  your styles.xml file. Should fix it.

**Comment by WGriffing** [comment]
The issue with fixed form not doing any highlighting is theme related. I did a fresh install on another computer and the fixed form was working on the Default theme. As soon as I switched to Deep Black, the syntax highlighting stopped. A quick flip through the themes makes it look like it doesn't work for any theme other than the Default. But, on the Default theme the fixed form highlighting covers all 4 comment cases as expected. There is a bug of some kind, but we can ignore the fixed form case.

I tried renaming styles.xml in %appdata% on that same fresh install. It did recreate a styles.xml file, but it didn't impact the highlighting in free form or fixed form.

In your screenshot, did you have free form or fixed form selected?

**Comment by WGriffing** [comment]
And, after reviewing Fortran 90 commenting rules the standard is to use only `!` and not `c` or `C`. My company doesn't follow the standards so I picked up bad habits and I never knew until now.

To summarize:
-I think the fixed form has a theme-related bug that prevents any syntax highlighting in any theme except the Default.
-Free form syntax highlighting is behaving exactly as it is described in every standards reference I can find and I'm an idiot for thinking it should behave differently.

**Comment by dail8859** [comment]
> In your screenshot, did you have free form or fixed form selected?

Honestly, I'm not sure. Just picked one and pasted in the example.

> I think the fixed form has a theme-related bug that prevents any syntax highlighting in any theme except the Default.

You are correct. This is actually the case for quite a few other languages as well. Anytime a new languages is added, each theme *technically* needs all the styles added as well but that can be quite tedious so normally just the default theme is updated.

**Comment by WGriffing** [comment]
I can see how that would be tedious. I can at least add fortran77 to those files.

Is it simply the ones in `\PowerEditor\installer\themes\`?

**Comment by dail8859** [comment]
Yes.
