### ISSUE TITLE
After installation Notepad++ is running with user Administrator

### ISSUE THREAD

**Issue by pscdodd** [notepad-plus-plus/notepad-plus-plus#1744]
On windows 8.1 after installing v6.9.1 Notepad++ was restarted, but was running with user "Adminstrator". Instead Notepad++ should be started with the current user.

**Comment by wodim** [comment]
Consider using this NSIS plugin http://nsis.sourceforge.net/ShellExecAsUser_plug-in

**Comment by SinghRajenM** [comment]
The issue is fixed in latest version of Notepad++. Now after installing/updating N++ will be executed for current user.
Fixed in #2643

**Comment by SinghRajenM** [comment]
@donho and @dail8859 , this ticket also can be closed.
