### ISSUE TITLE
XML autocomplete creates double close tag

### ISSUE THREAD

**Issue by sorenfriis** [notepad-plus-plus/notepad-plus-plus#1745]
When typing a tag in an .xml file, the auto-complete puts in double close tags

Example:
Type: `<xml>`
Result:
`<xml></xml></xml>`

Version 6.9.1

**Comment by dail8859** [comment]
You have XML Tools installed and it is trying to autocomplete the tag as well.

**Comment by sorenfriis** [comment]
You are correct. I will close the issue.
