### ISSUE TITLE
Notepad++ problems when saving new documents

### ISSUE THREAD

**Issue by cmcesario** [notepad-plus-plus/notepad-plus-plus#1746]
I am facing a recurrent problem in Notepad++ when a try to save new documents. Even if I choose Save or Save As..., it seems that the Save dialog shows for less than a second and Notepad++ freezes. I've searched the issues list and found #973, which was closed due to lack of information.

I have already tried emptying the plugins folder, but the behavior is still the same. Just in case, my current plugins are:
- Compare, version 1.5.6
- Converter, version 3.0
- MIME Tools, version 1.9
- NppExport, version 0.2.8

I tested using a document with just the word "test", so the problem is not related with having a big document. I also tested running Notepad++ as administrator and the result is the same.

Mi environment is Windows 7 Professional SP1 64 bits. Notepad++ version is 6.9.1

Any clue?

**Comment by ClaudiaFrank** [comment]
Could you check debug info (available under ? menu)
Is Local Conf mode : ON or OFF?
If OFF, would you mind close npp and open explorer open %APPDATA%
and rename notepad++ directory. Restart npp and check again.
If this solves your problem would you mind zipping the *.xml files under
%APPDATA%\notepad++ directory and attach it to this thread?

**Comment by cmcesario** [comment]
Hi! Thanks because this procedure solved the problem!

I am attaching the xml files for both the renamed and the newly created %appdata%\notepad++.

Regards,
Cristiano

**Comment by cmcesario** [comment]
Sorry, I tried to attach, but although the file is in zip format, github still shows the message "Unfortunately, we don’t support that file type.  Escolher arquivos Try again with a PNG, GIF, JPG, DOCX, PPTX, XLSX, TXT, PDF, or ZIP."

**Comment by xylographe** [comment]
@cmcesario Try to append ".png" to the file name (e.g., "base-name.zip.png").

**Comment by cmcesario** [comment]
@xylographe , let's see if now it works! The file with "old" in its name is the one with the xml files from when npp was freezing. The other one has the xml files for the working configuration.

![notepad zip](https://cloud.githubusercontent.com/assets/2171695/14513707/eda2379e-01bf-11e6-895b-071f4b154cc0.png)
![notepad old zip](https://cloud.githubusercontent.com/assets/2171695/14513715/023cd6fa-01c0-11e6-8e11-6b2c5a8bcc47.png)

**Comment by xylographe** [comment]
It works. I can download both of them.

**Comment by ClaudiaFrank** [comment]
@cmcesario, sorry for answering so late.
May I ask you to make a further test?
Can you rename the new created notepad directory and put the old 
one into place again? Does so problem reoccur?

**Comment by cmcesario** [comment]
@ClaudaFrank, it worked!

**Comment by ClaudiaFrank** [comment]
That explains why I didn't have any issues using your config files.
So question is, why solves recreation of appdata directory different unexpected behaviors?
At least this gives the information which part of code needs to get investigated deeper.

**Comment by SinghRajenM** [comment]
@donho and @dail8859 , this ticket also can be closed I guess.
