### ISSUE TITLE
Resolution Changes when Notepad++ is Opened

### ISSUE THREAD

**Issue by laruatta** [notepad-plus-plus/notepad-plus-plus#1747]
Running Windows 7 Professional SP1, whenever I open Notepad++ my main monitor's resolution is changed to 640x480.  Notepad++ can be open already, with the resolution changed back to the default, and the resolution will again change when I use the "edit with Notepad++" right click context menu option.

Notepad++ is unusable for me in this current state.

**Comment by xylographe** [comment]
Looks like compatibility mode has been set for notepad++.exe.
Browse to the Notepad++ folder, select notepad++.exe, then select Properties in the context menu and look at the compatibility tab. Compatibility mode should be off (check box unchecked).

**Comment by laruatta** [comment]
Thanks, that's it exactly.  I have no clue how it got set in the first place though.

**Comment by SinghRajenM** [comment]
@donho and @dail8859 , this ticket can be closed I guess.
