### ISSUE TITLE
Blinking mouse pointer at some locations - Win10 NP++ V9.9

### ISSUE THREAD

**Issue by wolispace** [notepad-plus-plus/notepad-plus-plus#1748]
I have the Document switcher open in NP++ and after a while of use, when I hover my mouse over a document name, or a screen border or a panel splitter in NP++ (nowhere else), it blinks: from the expected cursor to the edit I-beam. 
When I am still it remains on the I-beam and each pixel I move it shows the expected cursor, then back to the I-beam.

I have found clicking on things (usually a document name) will restore normal cursor stability.

I have yet to switch to tabs, and I am yet to work out at what point it starts happening again (maybe after locking the (not after locking screen, a 5 min wait, min/maximizing NP++.. I am still testing things).

I think this might be related to when I remotely connect to my PC (so the screen resolution changes) I have icons and menus blinking on and off for ages (I think related to the number of document I have open).

I could not find a similar issue that is already raised but I thought I would mention it just in case.

**Comment by donho** [comment]
Could be fixed by this commit: https://github.com/notepad-plus-plus/notepad-plus-plus/commit/687c6486a347ff6eb36c77c1311c7a2f256b3e94
