### ISSUE TITLE
'Save' dialog doesn't appear centered on the Notepad++ window

### ISSUE THREAD

**Issue by Eldaw** [notepad-plus-plus/notepad-plus-plus#175]
Many of the dialogs/windows in Notepad++ (e.g. Save As, Find, etc) appear directly centered on the actual Notepad++ main window itself when they are invoked.

However, the 'Save' dialog (when trying to close unsaved files or when quitting while there are unsaved files), always appears in the center of the monitor, no matter where the main Notepad++ window is.

**Comment by milipili** [comment]
#176

**Comment by Eldaw** [comment]
milipili, it's not clear why you believe these are related. This issue is about the positioning of the little Yes/No/Cancel 'Save' dialog that appears initially, not the choice of which dialog gets used for 'Save As' where you get to enter a filename and choose a location, etc.

**Comment by milipili** [comment]
Oh sorry I thought you were talking about the system 'Save' dialog. The reference has been removed.

**Comment by colin-branch** [comment]
I have a related issues related dialog which gets worse when in a multiple (3 in my case) monitor setup.

This effects the system file dialogs as well as the save on close dialog.

Save on Close Dialog has different behavior depending on how the close is initiated:
Window X button : 1st or 2nd monitor corner
File Menu -> Close : 1st or 2nd monitor corner
Tab X button: centered on notepad++ window
Ctrl-W shortcut: centered on notepad++ window

The dialog sometimes appears for an instant than hops to another monitor.

The Open File, Save File Dialogs don't ever appear to be centered properly.
Moving the window from maximized back and forth between windows seems to help get the dialog working again but that can get annoying. But at some point in the future it gets out of sync again.

**Comment by Eldaw** [comment]
I really hope this enhancement can be implemented. When running Notepad++ on a large, high-resolution monitor, the dialog can appear quite far from the main Notepad++ window.

**Comment by Eldaw** [comment]
> However, the 'Save' dialog (when trying to close unsaved files or when quitting while there are unsaved files), always appears in the center of the monitor, no matter where the main Notepad++ window is.

@donho I see that in v7.8 you finally decided to fix this. Too bad that you closed my issue down years ago as "not reproducible". What nonsense.
