### ISSUE TITLE
Feature Request: draw diagonal line to closing bracket/brace when it is misaligned

### ISSUE THREAD

**Issue by JesseAdam** [notepad-plus-plus/notepad-plus-plus#1750]
I would like to see a diagonal red line from opening bracket/brace to closing bracket/brace when it is misaligned.

**Comment by MetaChuh** [comment]
notepad++ uses scintilla as editor component, which is an external project.

such feature would have to be filed at the [scintilla feature tracker](https://sourceforge.net/p/scintilla/feature-requests/).

many thanks and best regards.
