### ISSUE TITLE
Disable collision with &File / Se&nd To

### ISSUE THREAD

**Issue by EricHirst** [notepad-plus-plus/notepad-plus-plus#1752]
In Windows Explorer, I routinely use keystroke shortcut Alt + F,N  (File / Send To)   to push selected files to shortcuts and scripts that I maintain my my %APPDATA%\Roaming\Microsoft\Windows\SendTo (shell:sendto) collection.  It's a powerful & simple way to automate a lot of common tasks.

However, it also means that whenever I upgrade Notepad++, I end up having to edit my registry and modify HKEY_LOCAL_MACHINE\SOFTWARE\Classes\CLSID{B298D29A-A6ED-11DE-BA8C-A68E55D89593}\Settings\Title, changing it from "Edit with &Notepad++" to "Edit with Notepad++".

It would be nice to have a way of not having "Edit with &Notepad++" not clash with "Se&nd To", at least on upgrade installs.

**Comment by MetaChuh** [comment]
please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins if you update from version 7.5.9 or below.
if your issue still persists, and it is still of relevance, please feel free to file a new issue as easy to understand and reproducible as possible.

thank you for your help and best regards.
