### ISSUE TITLE
documentation problem

### ISSUE THREAD

**Issue by jonhp** [notepad-plus-plus/notepad-plus-plus#1753]
C:\Program Files (x86)\Notepad++\user.manual\documentation\notepad-user-manual\languages\user-defined-languages.html has a link to "user defined language files" which takes one to http://sourceforge.net/apps/mediawiki/notepad-plus/index.php?title=User_Defined_Language_Files . But there is nothing there when you arrive. Can someone tell me where these user defined language files are really kept? thanks, jon

**Comment by donho** [comment]
Outdated
