### ISSUE TITLE
Add support to drag a file out from "Folder as Workspace" panel to other programs

### ISSUE THREAD

**Issue by johnnytemp** [notepad-plus-plus/notepad-plus-plus#1754]
This is a common feature for a File-Explorer-like View.  It can really helps Notepad++'s "Folder as Workspace" panel to interact with other programs.  (E.g. the "Explorer" plugin have this feature too)  Thanks.

**Comment by MetaChuh** [comment]
please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins if you update from version 7.5.9 or below.
if your issue still persists, and it is still of relevance, please feel free to file a new issue as easy to understand and reproducible as possible.

thank you for your help and best regards.
