### ISSUE TITLE
Feature Request: Single button "copy down" for Search/replace

### ISSUE THREAD

**Issue by ZLoth** [notepad-plus-plus/notepad-plus-plus#1755]
Notepad++ v6.9.1
Build time : Mar 28 2016 - 19:48:40
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : ON
Local Conf mode : OFF
OS : Windows 7
Plugins : mimeTools.dll NppConverter.dll NppExport.dll NppFTP.dll NppTextFX.dll PluginManager.dll Tidy2.dll XMLTools.dll 

One of the things that I use Notepad++ for is documentation in technical support cases and reformatting text from a report I run for pasting into my worklog. Sometimes, this involves highlighting text to be placed into the search box, and then adding/manipulating the text in the replace field. It would be great if there was a "Copy Down" button where the text in "Find what:" box is copied downward to the "Replace with:" box and then I can add what changes are needed.

**Comment by MetaChuh** [comment]
please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins if you update from version 7.5.9 or below.
if your issue still persists, and it is still of relevance, please feel free to file a new issue as easy to understand and reproducible as possible.

thank you for your help and best regards.
