### ISSUE TITLE
Feature Request: Undo function in Search/Replace

### ISSUE THREAD

**Issue by ZLoth** [notepad-plus-plus/notepad-plus-plus#1756]
Notepad++ v6.9.1
Build time : Mar 28 2016 - 19:48:40
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : ON
Local Conf mode : OFF
OS : Windows 7
Plugins : mimeTools.dll NppConverter.dll NppExport.dll NppFTP.dll NppTextFX.dll PluginManager.dll Tidy2.dll XMLTools.dll 

I am using Notepad++ in order to write up documentation and clean up logs prior to pasting into my case worklog in a technical support environment. I'm using search/replace and Replace All to clean up the text. However, sometimes, the initial replace all doesn't work correctly, and I want to undo the changes. Control-Z does not work in the Search/Replace, so I have to exit search/replace, Control-Z the change, reselect the search text, then try again with the change. Can you implement a undo function in search/replace?

**Comment by inferno596** [comment]
This would be incredibly useful for me as well.

**Comment by runnerpack** [comment]
+1

**Comment by MetaChuh** [comment]
please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins if you update from version 7.5.9 or below.
if your issue still persists, and it is still of relevance, please feel free to file a new issue as easy to understand and reproducible as possible.

thank you for your help and best regards.

**Comment by sasumner** [comment]
Why not simply click give the editor tab the input focus with the mouse, press ctrl+z, then give the replace window focus again with the mouse?  I know there are "mouse" haters out there, but...
