### ISSUE TITLE
Feature Request: Remove multiple white space with single space

### ISSUE THREAD

**Issue by ZLoth** [notepad-plus-plus/notepad-plus-plus#1757]
Notepad++ v6.9.1
Build time : Mar 28 2016 - 19:48:40
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : ON
Local Conf mode : OFF
OS : Windows 7
Plugins : mimeTools.dll NppConverter.dll NppExport.dll NppFTP.dll NppTextFX.dll PluginManager.dll Tidy2.dll XMLTools.dll 

Please add a function under Edit -> Blank Operations so that instances of two or more space characters in the middle of a line can be trimmed down to be a single space. A possible additional function can be to instances of two or more whitespace characters (spaces, tab, etc, but NOT newlines) can be converted to space, although this can be accomplished with the function Tabs to Spaces, then using blank operations.

The current function "Remove unnecessary blank and EOL" does not serve this functionality, as it can combine multiple paragraphs into a single paragraph.

**Comment by slateraptor** [comment]
You can accomplished this with a simple regular expression find/replace: `[ \t]{2,}`

If you want to omit indentation, add a negative lookbehind: `(?<!\s)[ \t]{2,}`

**Comment by Fendorn** [comment]
Possible via AddOn called TextFX
Then Menu > TextFX > TextFX Edit > Trim Trailing Spaces

**Comment by MetaChuh** [comment]
please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins if you update from version 7.5.9 or below.
if your issue still persists, and it is still of relevance, please feel free to file a new issue as easy to understand and reproducible as possible.

thank you for your help and best regards.

**Comment by sasumner** [comment]
Closure is correct action.  User should be advised to record a macro invoking the replace function for this action.
