### ISSUE TITLE
Feature Request: Add Proper Case to existing Edit -> Convert Case To

### ISSUE THREAD

**Issue by ZLoth** [notepad-plus-plus/notepad-plus-plus#1758]
Notepad++ v6.9.1
Build time : Mar 28 2016 - 19:48:40
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : ON
Local Conf mode : OFF
OS : Windows 7
Plugins : mimeTools.dll NppConverter.dll NppExport.dll NppFTP.dll NppTextFX.dll PluginManager.dll Tidy2.dll XMLTools.dll 

Currently, Edit -> Convert Case To includes functions for UPPERCASE and lowercase. Consider adding Proper Case to this submenu. 

Note: This functionality is already existing in TextFX plugin under TextFX -> TextFX Characters -> Proper Case.

**Comment by dail8859** [comment]
Closed by f6e47cd536f5c940de0eb8c378b71801dbeb6ae7
