### ISSUE TITLE
Open files are not preserved after Notepad++ upgrade if "Remember Current Session for next launch" is not checked

### ISSUE THREAD

**Issue by ZLoth** [notepad-plus-plus/notepad-plus-plus#1759]
Notepad++ v6.9.1
Build time : Mar 28 2016 - 19:48:40
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : ON
Local Conf mode : OFF
OS : Windows 7
Plugins : mimeTools.dll NppConverter.dll NppExport.dll NppFTP.dll NppTextFX.dll PluginManager.dll Tidy2.dll XMLTools.dll 

In my configuration of Notepad++, I have Settings -> Preferences -> Backup -> Remember Current Session for next launch unchecked, as I want to have Notepad++ open up as a "fresh slate". However, if I then accept an upgrade package, Notepad++ performs the install, but then reopens with just the change notes and not my opened file. 

STEPS TO REPLICATE:
1. Install an older version of Notepad++.
2. Go to Settings -> Preferences -> Backup, and uncheck Remember Current Session for next launch.
3. Exit Notepad++
4. Right-click on a text file and Open With Notepad.
5. Check for Notepad upgrade package.
6. Allow install of updated Notepad++ package.

WHAT SHOULD HAPPEN: The selected file is reopened along with change notes.
WHAT REALLY HAPPENS: Only the recent note changes are opened. 

Possible suggestions:
- If Remember Current Session for next launch is not checked, then modify the upgrade dialogue to say that existing open files will not be reopened. 
- Download updated Notepad++, but don't install until after Notepad++ is existed.

**Comment by bardware** [comment]
I had this today. The update dialog appeared and notepadd++ eventually restarted. It stayed empty. The backup folder however contains alle the files.

Is it possible to restore the session?

**Comment by ddeamilivia** [comment]
Hi,
I have v7.5.10 on a Windows 10, and this started to happen to me yesterday (07-Dec-2017), without updating the application and without changing any Preference.
May it have anything to do with a Windows Update? Sounds weird, but it's the only thing that comes to my mind that could have changed...

**Comment by donho** [comment]
It's a "nice to have" feature, but it will make the logic more complex in the code, so it won't  be done unfortunately.
