### ISSUE TITLE
Use modern Common Item Dialog instead of old pre-Vista dialog

### ISSUE THREAD

**Issue by collinsauve** [notepad-plus-plus/notepad-plus-plus#176]
The SaveAs dialog in Notepad++ uses this dialog: https://msdn.microsoft.com/en-us/library/windows/desktop/ms646960(v=vs.85).aspx#_win32_Open_and_Save_As_Dialog_Box_Customization

Starting with Windows Vista (its been 8 years now :) you can use the "Common Item Dialog" to open and save files: https://msdn.microsoft.com/en-us/library/windows/desktop/bb776913(v=vs.85).aspx
This dialog has a number of features, including a far superior folder list on the left. Personally I rely on that folder list and custom favorites in it to quickly navigate to several folders.

Notepad++ appears to use the Common Item Dialog for opening files, just not for saving.

**Comment by milipili** [comment]
note: Notepad++ is still compatible with WinXP SP2. Thus this improvement will be possible only when this compatibility will be dropped (probably in the next major version).

**Comment by ariccio** [comment]
Also: The new dialog can use quite a bit of memory, as it loads all of the installed shell extensions (e.g. 7-zip, Realtek Bluetooth ~~bloatware~~ feature enhancements, Citrix receiver, overeager antimalware vendors, NVIDIA's 80,000 control panels, etc...), *and* trigger all sorts of disk thrashing.

I like the idea behind it, but with the newer dialog, we pay for a lot that we don't use.

**Comment by collinsauve** [comment]
Doesn't Notepad++ use the newer dialog for Open?

**Comment by andreas-jonsson** [comment]
It uses the new dialog for Open, the old one for Save/Save as.

I tried to replace the old one last month but failed. There is some magic logic (I think the comment in the code is "this line is cursed, don't touch it!" or something similar) which makes it possible for N++ to change the file extension combo in the save dialog, I couldn't get it working with the new dialog.

**Comment by ariccio** [comment]
I think you're referring to [this comment](https://github.com/notepad-plus-plus/notepad-plus-plus/blob/0774106a40cf55acb6653adefae7fcdde6e581a2/PowerEditor/src/WinControls/OpenSaveFileDialog/FileDialog.cpp#L370):

> 			// Don't touch the following 3 lines, they are cursed !!!
>			oldProc = (WNDPROC)::GetWindowLongPtr(hFileDlg, GWL_WNDPROC);
>			if ((long)oldProc > 0)
>				::SetWindowLongPtr(hFileDlg, GWLP_WNDPROC, (LONG_PTR)fileDlgProc);

...I have a bad feeling that it's a lurking bug

**Comment by ariccio** [comment]
Maybe this is why they're cursed: [they're wrong](http://blogs.msdn.com/b/oldnewthing/archive/2003/12/01/55900.aspx)?:

> So remember, the only things you can do with the values you get from `GetWindowLongPtr(hwnd, GWLP_WNDPROC)` are to (1) pass them to `CallWindowProc`, or (2) pass them back to `SetWindowLongPtr(hwnd, GWLP_WNDPROC)`.


...and of course, Notepad++ just calls `oldProc` directly in 4 places, instead of using [`CallWindowProc`](https://msdn.microsoft.com/en-us/library/ms633571.aspx).

**Comment by ariccio** [comment]
By the way: `GWLP_WNDPROC` and `GWL_WNDPROC` are both defined to be `-4`.

**Comment by milipili** [comment]
*reminder for code implementation*: as reported, applications aren't supposed to call the `WNDPROC` returned by `GetWindowLongPtr`.

> More info: http://blogs.msdn.com/b/oldnewthing/archive/2003/12/01/55900.aspx

**Comment by donho** [comment]
Commenting the following line makes new style dialog back:
//_ofn.Flags |= OFN_ENABLEHOOK;

Then I googled the concerning issue I found:
"You are correct that it is impossible to get the new look when you use a hook. Instead you need to use the IFileDialogCustomize interface to customise the dialog. This is less powerful but does result in appearance and behaviour that is more consistent with the standard part of the dialog."
in :
http://stackoverflow.com/questions/4731218/ofn-enablehook-modifies-the-look-of-getopenfilename

I guess this part should be recoded.

**Comment by stealthgyro** [comment]
Well at least I have my answer now. I'll be following this closely, can't wait for this to be implemented, what about doing it in the 64bit version since who really uses XP64? ... Any work around would be appreciated.

**Comment by sbrl** [comment]
Umm why is this closed, @donho?

**Comment by donho** [comment]
It's implémented.

**Comment by alive4ever** [comment]
Is it really implemented? Which commit does implement this feature?

Notepad++ 7.3.3 64 bit on Win 6.1.7601 still use old - pre Vista save as dialog.

**Comment by VVelda** [comment]
Nothing is implemented... :-(

**Comment by Tamarindo94** [comment]
This is not implemented as of version 7.3.3 and it is much needed. I think this issue should be reopened

**Comment by Tamarindo94** [comment]
Preferences->Default directory->Use new style save dialog

**Comment by VVelda** [comment]
Great. But, then... Why it isn't by default?

**Comment by Tamarindo94** [comment]
I'd guess because of its higher resource consumption...should be, though

**Comment by sbrl** [comment]
It's possibly for testing purposes, if I were to guess. It might also be the case if Windows XP is still supported, though I can't remember if that's the case.

**Comment by MaxKot** [comment]
Can this issue be re-opened? The dialogs have reverted to XP-style after version 7.5.5.
