### ISSUE TITLE
Bug with TDT (XML)

### ISSUE THREAD

**Issue by CamilleRoger** [notepad-plus-plus/notepad-plus-plus#1760]
Notepad++ can not recognize the full TDT.
When I want to hide it, just the first line is hide.

![bugnotepad](https://cloud.githubusercontent.com/assets/15185241/14561218/1a819eca-0315-11e6-84bf-1a6f5489f217.PNG)

![bugnotepad 2](https://cloud.githubusercontent.com/assets/15185241/14561217/1a7fa890-0315-11e6-8832-34167c9e8b6c.PNG)

**Comment by MetaChuh** [comment]
please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins if you update from version 7.5.9 or below.
if your issue still persists, and it is still of relevance, please feel free to file a new issue as easy to understand and reproducible as possible.

thank you for your help and best regards.
