### ISSUE TITLE
Links with "#" after the last slash in a website will not allow a proper link connection

### ISSUE THREAD

**Issue by looniez** [notepad-plus-plus/notepad-plus-plus#1762]
Example: The link below does not fully connect:
https://www.dahippo.com/bp/ship/#!30H691O1O0J5H0C341A1A4M4M0ZZ0ZZ0ZZ0ZZdC

The "#" after the "ship/" causes the link to only partially connect. Double clicking this link above results in bringing up: https://www.dahippo.com/bp/ship/

In other words, the link is truncated when it parses to the # 

This is an excellent tool. I'd love to see this fixed. My workaround is to copy the entire link and paste it in a browser but it would be nice to double click on it and bring up the correct link.

**Comment by ClaudiaFrank** [comment]
Problem is the exclamation mark.
Duplicate #1595
