### ISSUE TITLE
Invalid paths in recent files list

### ISSUE THREAD

**Issue by nplus-user** [notepad-plus-plus/notepad-plus-plus#1764]
There is a list of recent files in "File" menu - after last update to v.6.9.1 I see there invalid paths, see attachment. Some paths are valid and if I select one of them - it opens in Notepad++, but some are invalid and opens nothing when I select item with broken path. Some paths contain of valid and invalid parts.
![notepad](https://cloud.githubusercontent.com/assets/13237441/14582261/a8a5735c-0419-11e6-9b05-0a738c3d2002.png)
The system is Win7x64

**Comment by MetaChuh** [comment]
please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins if you update from version 7.5.9 or below.
if your issue still persists, and it is still of relevance, please feel free to file a new issue as easy to understand and reproducible as possible.

thank you for your help and best regards.
