### ISSUE TITLE
auto-complete box appears on second monitor

### ISSUE THREAD

**Issue by thbsp** [notepad-plus-plus/notepad-plus-plus#1766]
A minor issue, but I recently noticed that the auto-complete box will pop up on a different monitor (I use a dual-monitor system) if the text is at the end of one line and close to the other monitor's workspace. I've attached a screenshot of this. (Sorry for all the black, but I had to censor the article I'm working on as it hasn't been published yet.)
Not exactly a crippling bug, but I imagine having the auto-complete box appear anywhere outside the program window is undesired behaviour. In this case the program window was maximized on the left monitor (and thus not on the right monitor at all). If the right monitor was turned off or had some other program running with an always-on-top flag set then I wouldn't be able to the auto-complete box.

![auto-complete box - censored](https://cloud.githubusercontent.com/assets/18520229/14591064/ff5ac720-0544-11e6-9cf9-543f7e204f48.jpg)

**Comment by martinleben** [comment]
+1
I also have this issue. Using v7.5.8.

**Comment by MetaChuh** [comment]
please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins if you update from version 7.5.9 or below.
if your issue still persists, and it is still of relevance, please feel free to file a new issue as easy to understand and reproducible as possible.

thank you for your help and best regards.
