### ISSUE TITLE
Hang on start

### ISSUE THREAD

**Issue by Bartolomeus-649** [notepad-plus-plus/notepad-plus-plus#1769]
_[It does not work to attach files, let me know if I should provide them in any other way.]_

Version: 6.91 (Windows 8.1)

Whenever Notepad++ is started, it hangs.
The main window is created, but no menus or any other parts of the client area of the window is visible. So there is only a caption (*new 1 - Notepad++), the SysMenu (which is working) and the "system windows control buttons" in the top right of the window.
The caption changes to "*new 1 - Notepad++ (Not Responding)" after a while.

A [SysInternals ProcMon](https://technet.microsoft.com/en-us/sysinternals/processmonitor.aspx)¹ log file with all events produced with a ProcMon filter set to  ProcessName = "notepad++.exe"

Windows Error Reporting loges an event with eventId 1001 in the Windows Application log:
_The complete content of the Windows Reporting Report file is included as an attachement_

```
Log Name:      Application
Source:        Windows Error Reporting
Date:          2016-04-18 08:29:13
Event ID:      1001
Task Category: None
Level:         Information
Keywords:      Classic
User:          N/A
Computer:      XXXX
Description:
Fault bucket , type 0
Event Name: AppHangB1
Response: Not available
Cab Id: 0

Problem signature:
P1: notepad++.exe
P2: 6.9.1.0
P3: 56f96ebd
P4: d391
P5: 134217984

Analysis symbol: 
Rechecking for solution: 0
Report Id: dad36e00-052e-11e6-82dd-1c6f65390b4b
Report Status: 97
```

---
1. SysInternals ProcMon can be found here:<br />
   [https://technet.microsoft.com/en-us/sysinternals/processmonitor.aspx](https://technet.microsoft.com/en-us/sysinternals/processmonitor.aspx)

**Comment by donho** [comment]
I believe this issue has been fixed since long time ago.
Update your Notepad++ to the latest version (v7.6.6).
If the issue persists, please create a new issue for it.
Thank you.
