### ISSUE TITLE
Settings cannot be saved because read-only attribute is copied from model file to config file

### ISSUE THREAD

**Issue by MalcolmEvershed** [notepad-plus-plus/notepad-plus-plus#1770]
If config.model.xml is read-only, when Notepad++ copies it to config.xml, config.xml will also have the read-only bit set. This will prevent config.xml from being written to in the future, making it so that settings cannot be changed.
## Repro steps:
1. Extract npp*.zip to a new directory.
2. In the new directory, delete doLocalConf.xml.
3. In the new directory, make config.model.xml read-only by running attrib +R config.model.xml.
4. Run Notepad++ and it will create %APPDATA%\Notepad++\config.xml and by running attrib config.xml, you can see that the read-only bit is set.
5. Try to change some setting and exit Notepad++ and config.xml won't be changed. If you run Process Monitor, you can see that opening config.xml for write fails.

**Comment by MetaChuh** [comment]
please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins if you update from version 7.5.9 or below.
if your issue still persists, and it is still of relevance, please feel free to file a new issue as easy to understand and reproducible as possible.

thank you for your help and best regards.
