### ISSUE TITLE
UDL - not saved automatically

### ISSUE THREAD

**Issue by mwerle** [notepad-plus-plus/notepad-plus-plus#1772]
I created a UDL and on restart of Notepad++ (actually, computer rebooted) it was gone.

Furthermore, when "Exporting" a UDL, the file-extension is not automatically set to ".xml" even though the file type cannot be changed.  A subsequent "Import" then fails to find the previously exported UDL.

**Comment by MetaChuh** [comment]
please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins if you update from version 7.5.9 or below.
if your issue still persists, and it is still of relevance, please feel free to file a new issue as easy to understand and reproducible as possible.

thank you for your help and best regards.
