### ISSUE TITLE
UDL - does not use Global Styles

### ISSUE THREAD

**Issue by mwerle** [notepad-plus-plus/notepad-plus-plus#1773]
When defining a UDL, it does not use the global themes / styles.

Furthermore, when specifying a Default Style for a UDL, that does not propagate through to the rest of the UDL (keywords, separators, etc).

**Comment by MetaChuh** [comment]
please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins if you update from version 7.5.9 or below.
if your issue still persists, and it is still of relevance, please feel free to file a new issue as easy to understand and reproducible as possible.

thank you for your help and best regards.
