### ISSUE TITLE
Program hangs

### ISSUE THREAD

**Issue by lasseter** [notepad-plus-plus/notepad-plus-plus#1774]
When you open a text file (.txt), change the text, save the text, then minimize NP++, then modify the text files content with another program - then upon maximizing NP++ with the task bar button, a box comes up asking if you want to keep the old text or replace it with the new.  At this point NP++ hangs.  The buttons are not accessible.  NP++ has to be killed with Ctrl+Alt+Del.  If you never minimize NP++, the box comes up, but doesn't hang the program.

Notepad++ v6.8.8
Build time : Dec 10 2015 - 01:11:37
Path : C:\AMisc\Utilities Text\Notepad++\notepad++.exe
Admin mode : ON
Local Conf mode : ON
OS : Windows 7
Plugins : AnalysePlugin.dll autosave2.dll ClipboardHelper.dll CodeAlignmentNpp.dll ColorPicker.dll combine.dll ComparePlugin.dll CustomizeToolbar.dll docMonitor.unicode.dll DSpellCheck.dll Explorer.dll HexEditor.dll HTMLTag_unicode.dll LightExplorer.dll linefilter2.dll LocationNavigate.dll MenuIcons.dll mimeTools.dll MultiClipboard.dll NamedBookmarks.dll NppBookmarkManager.dll NppColumnSort.dll NppConverter.dll NppCrypt.dll NppExport.dll NppFTP.dll NppQCP.dll NppSaveAsAdmin.dll PluginManager.dll PreviewHTML.dll print.dll ReloadButton.dll RunMe.dll SpellChecker.dll TopMostU.dll

**Comment by dail8859** [comment]
First try a few things. Update Notepad++ to v6.9.1 (if possible). Also disable your plugins because it very well could be one of those causing it and not Notepad++.

**Comment by dail8859** [comment]
Closing due to no response.
