### ISSUE TITLE
Column editor - bug when wrapping

### ISSUE THREAD

**Issue by jsh562** [notepad-plus-plus/notepad-plus-plus#1775]
v6.5.3
When using column editor to write to several rows at once:
When I get to the end of the line and I continue typing and it wraps the text to the next line, the cursor continues from the beginning of the line of the current line and not the new wrapped line.
Basically, it continues typing whatever I was typing starting from a different section of the text than it is supposed to.

**Comment by tobsimon** [comment]
Confirming. I guess no one ever thought to activate line wrapping when typing in column mode.
Everything works as expected though, in Multi-Editing mode (CTRL-click to set another cursor, when activated under Settings > Preference > Editing).
Related:  #1711, #1414

**Comment by jsh562** [comment]
(and your report a bug link still links to sourceforge)

**Comment by dail8859** [comment]
It still has a sourceforge link because you are on a really old version of Notepad++.

**Comment by MetaChuh** [comment]
please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins if you update from version 7.5.9 or below.
if your issue still persists, and it is still of relevance to you, please feel free to file a new issue as easy to understand and reproducible as possible.

thank you for your help and best regards.

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
(no extra account is needed, just use your github account to sign in)
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)
