### ISSUE TITLE
Find in Finder pattern to match

### ISSUE THREAD

**Issue by cmeriaux** [notepad-plus-plus/notepad-plus-plus#1783]
Find in Finder dialog should set the pattern to match like the find function.

Consider that the original search set a pattern to match (example *.cpp). 
Consider that you use the new function "find in Finder", and you want to find specific string (example "foo"). 

That will return **every foo found on every file**   instead of **every foo found on every file.cpp** .

**Comment by MetaChuh** [comment]
please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins if you update from version 7.5.9 or below.
if your issue still persists, and it is still of relevance, please feel free to file a new issue as easy to understand and reproducible as possible.

thank you for your help and best regards.

**Comment by sasumner** [comment]
I think it works as intended.  You are finding "IN THE FINDER".  Wherever "foo" is in the finder, it should be found.  The workaround is to delete out (using the Delete key) any searches you no longer want in your Finder, before doing a search in it.

I just noticed the new user-level nomenclature for this is "Find in this found results..." (which IMO is rather lousy), it is no longer "Find in this Finder..." (or close to that; whatever it was before).
