### ISSUE TITLE
Multi-line tab settings [moving a tab]

### ISSUE THREAD

**Issue by MonteShaffer** [notepad-plus-plus/notepad-plus-plus#1787]
Hi,

I believe Notepad++ is a great service to the development community, thank you!

At times, I have 50 or more files open (remote files that automatically get updated via WinSCP when saved)... 

So I turn on the "multi-line" tab setting.

Sometimes, I want to organize the tabs, dragging a tab to be near another tab ... and the system goes crazy ... I can't find where I am, or where I am going.

Also, when I select a tab, this tab "row" or line gets moved down to the bottom (I guess the active layer).  This is BAD.  I can't ever find things.  Would it be possible to have another option "move-multi-line-row-on-hightlight" that behaves as-is for some users, but for others, "highlight" will not move the row.  

With 50 files open, I can keep track of them, if their tab location isn't moving.

Certainly using "projects" or something, I could maybe create a work around.  I am offering this idea as a fix for how I actually work.

Thanks in advance.

**Comment by MonteShaffer** [comment]
When I SELECT A TAB, I want it to highlight, not REARRANGE ROWS ...

**Comment by AngryGamer** [comment]
I suffer from the same frustration. Here's my solution for the rearranging rows problem:

Replace two lines:
`int multiLine = isMultiLine?(_isTraditional?TCS_MULTILINE:0):0;`
With:
`int multiLine = isMultiLine?(_isTraditional?TCS_MULTILINE|TCS_BUTTONS:0):0;`

Replace one line:
`SendMessage(_hwndArray[i], WM_TABSETSTYLE, isMultiLine(), TCS_MULTILINE);`
With:
`SendMessage(_hwndArray[i], WM_TABSETSTYLE, isMultiLine(), TCS_MULTILINE|TCS_BUTTONS);`

There's a drawback to this solution, though. You must have "Lock (no drag and drop)" enabled or the tabs are not selectable. If you want to reorder tabs, then you'll need to reorder with multi-line disabled.

**Comment by AngryGamer** [comment]
imo, the drawback is inconsequential. You can't reorder tabs either way in multi-line. They spasm out of control when moving them up or down a row (because of the rearranging rows problem).

**Comment by vlakoff** [comment]
Agree that clicking on a tab shouldn't change rows order.

**Comment by HonoredMule** [comment]
This is my number one issue with Notepad++.  It stands out so far above any other that I can't even think of what number two would be off-hand, despite using Notepad++ extensively on a daily basis.

**Comment by dail8859** [comment]
Closed by 9967c59912a05bfac57854e583d573877fdcb787
