### ISSUE TITLE
Copy to clipboard "\" escaped current file/folder path

### ISSUE THREAD

**Issue by sbocskai** [notepad-plus-plus/notepad-plus-plus#1788]
When you have to inclue the path to a file folder into a modern programming language string chain, the   special characters have to be escapted "\".

Example `"C:\Windows\System32"` would be `"C:\\Windows\\System32"`.

I would be nice to have this feature.
Thanks,
Stefan Bocskai

**Comment by MetaChuh** [comment]
as preserving the exact content of a clipboard is the main goal, such feature will not be implemented at the notepad++ core.

there are however various plugins that can escape your paths on selection.

thank you for your help and best regards.

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
(no extra account is needed, just use your github account to sign in)
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)

**Comment by sasumner** [comment]
@sbocskai A good solution to your problem is to record a macro that does a replace operation.
