### ISSUE TITLE
Remove Hungarian (ANSI) translation from installer

### ISSUE THREAD

**Issue by batagy** [notepad-plus-plus/notepad-plus-plus#1789]
Hi!

The ANSI version of Hungarian translation is not maintaned from long time.
It's not needed.
Please remove the ANSI version of Hungarian translation from the installer.

Note: Obviously, please keep the normal UTF version of Hungarian translation in installer!

Thanks a lot
György

**Comment by batagy** [comment]
Hi!

This issue is still present in version 7.3.
The ANSI version of Hungarian translation should be removed.

Thanks
György

**Comment by cmeriaux** [comment]
You should do a PR to remove the ANSI file.
I only see a UTF-8 file in the repository : PowerEditor\installer\nativeLang\hungarian.xml 
Where is the ANSI one ?

**Comment by batagy** [comment]
Hi @cmeriaux ,

Thanks! It's strange. The ANSI version appear during the installation wizard, during step "Choose Components", under Custom option, under Localization. I think the installer somehow adds it always automatically from the normal UTF-8 file PowerEditor\installer\nativeLang\hungarian.xml, Somewhere it's hardcoced. But where?

**Comment by batagy** [comment]
Hi again,

At least the ANSI version is referred at this point in repo:
notepad-plus-plus/PowerEditor/installer/nsisInclude/langs.nsh

**Comment by SinghRajenM** [comment]
Removed in PR #2954
