### ISSUE TITLE
Incorrect commenting in XMLTools plugin

### ISSUE THREAD

**Issue by NN---** [notepad-plus-plus/notepad-plus-plus#179]
```xml
<a>
 <b></b>
</a>
```

Select <b></b>
Press Ctrl+K you get:

```xml
<a>
 <!-- <b></b> -->
</a>
```

Now select everything, Ctrl+K, you get:

```xml
<!-- <a>
 <!-- <b></b> -->
</a> -->
```

This is an incorrect xml.
The commenting operation must take care of inner comments and change them accordingly.

**Comment by MAPJe71** [comment]
I guess this is an issue for the [Notepad++ Plugin Development forum on SourceForge](https://sourceforge.net/p/notepad-plus/discussion/482781/).

**Comment by dail8859** [comment]
Closing since this is due to a 3rd party plugin.
