### ISSUE TITLE
Google Search doesn't work if the first character you're trying to Google Search is "#"

### ISSUE THREAD

**Issue by tvman-123** [notepad-plus-plus/notepad-plus-plus#1790]
If you highlight:

"#00F"

and right click, and hit Google Search, it'll go to:

"https://www.google.com/webhp#00f", not searching anything.

If you try another query with "#" included, but not starting with, it'll still work.

Noticed this when searching for hex colors in CSS.

**Comment by guy038** [comment]
Hello, **tvman-123**,

As a work-around, you could use the syntax **`%2300F`** ! It should be OK :-)) ( indeed, the Unicode code of the **`#`** character is **\x{0023}** )

Best Regards,

guy038
