### ISSUE TITLE
Split View needs a one button/single command to close multiview.

### ISSUE THREAD

**Issue by HiTechHiTouch** [notepad-plus-plus/notepad-plus-plus#1792]
The help wiki page for Split View docs.notepad-plus-plus.org/index.php/Split_View has a major heading "How to turn Multi-View on & off" to answer the obvious question.  Unfortunately, the answer is do a bunch of dragging of tabs from one pane to the other until one pane disappears.

This awkward solution makes the user do a lot of work, and isn't easily automated.  Therefore a "Close Multiview" function would be quite useful.

One place to expose it is by right clicking the splitter bar, where " Rotate to right" and "Rotate to left" currently appear.  Another place would be on the menu bar View drop down.

**Comment by MetaChuh** [comment]
please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins if you update from version 7.5.9 or below.
if your issue still persists, and it is still of relevance to you, please feel free to file a new issue as easy to understand and reproducible as possible.

thank you for your help and best regards.

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
(no extra account is needed, just use your github account to sign in)
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)

**Comment by sasumner** [comment]
FWIW, a simple Pythonscript seems like it could do this job:

    file_info_list = notepad.getFiles()
    for (filename, bufferID, index, view) in file_info_list:
        if view == 1:
            notepad.activateIndex(view, index)
            notepad.menuCommand(MENUCOMMAND.VIEW_GOTO_ANOTHER_VIEW)
