### ISSUE TITLE
Feature Request: edit results of Find All in Current Document manually

### ISSUE THREAD

**Issue by exch-0930** [notepad-plus-plus/notepad-plus-plus#1794]
The search finds all the lines that I need to edit, but I have to edit manually since there is not a consistent pattern such that I can do a regular search and replace, even using regular expressions.  I am editing the data inside a particular tag in an XML file and other text files.

That would save many hours of work since we have to do it every day. 

Thanks

**Comment by exch-0930** [comment]
To clarify that, the search results displays all the lines I need to edit in one spot.  I would like to be able to edit all the lines in the results box instead of having to use find next to edit.

**Comment by MetaChuh** [comment]
this would be too complicated to implement, as editing needs always differ.

thank you for your help and best regards.

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
(no extra account is needed, just use your github account to sign in)
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)
