### ISSUE TITLE
Localization support for South Indian Kannada language

### ISSUE THREAD

**Issue by Dinesh357** [notepad-plus-plus/notepad-plus-plus#1796]
Hi,

When I installed npp I was expecting a localization support for South Indian Kannada language
Are there any plans for the support of this language
I see a lot of South Indian languages support but not Kannada

If required I can contribute.

Appreciate your response

Thanks
Dinesh

**Comment by MetaChuh** [comment]
localisation for languages other than our native, can only be contributed externally.

thank you for your help and best regards.

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
(no extra account is needed, just use your github account to sign in)
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)
