### ISSUE TITLE
Copy Line Cursor is On Without Selection

### ISSUE THREAD

**Issue by jsherwood-atcomm** [notepad-plus-plus/notepad-plus-plus#18]
Not sure I'm doing this correctly,  This a more a request than an issue.

I'd like to be able to copy a line to the buffer without having to select the line.  This is a very convenient option inside VS.

Thanks
Joe

**Comment by dail8859** [comment]
It is already possible. `Ctrl+Shift+T` is set to copy the current line. **However** in the recent versions of N++ `Ctrl+Shift+T` was also mapped to open the most recent tab. (There is a shortcut conflict currently). You must change either the shortcut for "Restore Recent Closed File" or for SCI_CUTLINE

**Comment by jsherwood-atcomm** [comment]
Thanks,  I got it working mostly.  
I'm sure you know, Visual Studios  Ctrl+C copies what is selected or if nothing selected copies the current line. It is an option you can turn on or off.   For me that would be better than having to remember a different key combination.

Joe

**Comment by dail8859** [comment]
Yes, *technically* it is possible. Notepad++ uses Scintilla as the underlying component to handle the text editing. There is a Scintilla option called [SCI_COPYALLOWLINE] (http://www.scintilla.org/ScintillaDoc.html#SCI_COPYALLOWLINE) that Notepad++ does not expose as an option to change (although maybe something worth adding to Notepad++). I believe the only way to enable this is through a plugin, something like NppExec or Python Script

**Comment by dail8859** [comment]
Nope! Disregard what I just said. Its not an option, its an actual command but it doesn't look like you can set up a shortcut for it...which is odd.

**Comment by jsherwood-atcomm** [comment]
I was just about to say, I should learn about plugins.

**Comment by MAPJe71** [comment]
Have a look at this plugin [Notepad-VisualStudioLineCopy](https://bitbucket.org/zastrowm/notepad-visualstudiolinecopy). The source for the .NET/C# variant can be found at [Npp-VisualStudio-LineCopy](https://code.google.com/p/npp-visualstudio-linecopy).

**Comment by jsherwood-atcomm** [comment]
Thank You, that was perfect.
