### ISSUE TITLE
Syntax highlighting has changed for the worse

### ISSUE THREAD

**Issue by EnginePod** [notepad-plus-plus/notepad-plus-plus#1800]
When I worked with .PHP and .HTML files about 1-2 years ago the syntax worked perfectly.

Whenever there was some CSS between <style></style> I always saw the highlighting for CSS.
When there was javascript on the page between <script></script>, I saw the JS highlighting which was great.

Nowadays that is gone.  I **only** see the highlighting for CSS in .CSS files and similarly JS highlighting is only in JS files.  This is makes the CSS and JS code on the page very hard to read since it's missing proper highlighting so you're forced to either see pure black text when you're working with the code or you'll have to copy the contents over to a pure CSS/JS file to see the highlighting.

Is there any way to get the old highlighting back for the inline JS/CSS?

**Comment by dail8859** [comment]
Try deleting your `stylers.xml` file most likely located in your %APPDATA% directory. If you have custom style changes then just move it or rename it temporarily.

**Comment by EnginePod** [comment]
I just did that but there aren't any changes.
CSS between the <style></style> in a .PHP file is still just plain black text.

**Comment by EnginePod** [comment]
Just a thought, if your highlighting is working properly can you upload your own stylizer.xml and I'll simply replace it with mine.

**Comment by dail8859** [comment]
If you delete yours then it will get replaced by a master copy so there wouldn't be any point providing another one.

**Comment by EnginePod** [comment]
I understand that, but as I wrote in my previous post it didn't help.
In other words, I deleted the stylers.xml and the CSS is still just black text without highlighting when displayed in .PHP or .HTML files.

**Comment by dail8859** [comment]
Inline Javascript works for me. 
![capture](https://cloud.githubusercontent.com/assets/3694843/14867831/78a54dc6-0c98-11e6-9907-76be04b299dc.PNG)

I rarely use CSS/HTML/PHP/Javascript at all but I'm not aware of it highlighting inline CSS at any point.

**Comment by EnginePod** [comment]
JS was fixed when I removed stylers.xml, but CSS is still just black text.
If I remember correctly there was highlighting for CSS before.

If there currently isn't any support for it then it shouldn't be hard to add since there already is highlighting available for CSS, all that needs to be done is to have it added between <style></style> with regex.

**Comment by dail8859** [comment]
The code that actually highlights the text is from the [Scintilla](http://scintilla.org/) project. This code is used as-is without any modifications so any changes as you suggest would have to be made to that project. AFAIK it isn't already implemented but I'll look into it a bit incase it isn't just as simple as an option to turn on in the HTML lexer.

> it shouldn't be hard to add since there already is highlighting available for CSS

It is alot more complicated than ;)

**Comment by EnginePod** [comment]
I didn't know about Scintilla, but again since there is syntax highlighting for CSS the only work needed would be to apply the same principles as for the embedded JS.

**Comment by wernerschka** [comment]
I support the feature of **syntax highlighting of inline CSS** very much. Since there's already working inline syntax highlighting for Javascript- and PHP-blocks within HTML files.

Because of that I opended a feature request at Scintilla's site:
https://sourceforge.net/p/scintilla/bugs/1904/

**Comment by MetaChuh** [comment]
please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins if you update from version 7.5.9 or below.
if your issue still persists, and it is still of relevance to you, please feel free to file a new issue as easy to understand and reproducible as possible.

thank you for your help and best regards.

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
(no extra account is needed, just use your github account to sign in)
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)
