### ISSUE TITLE
dealing with many open documents

### ISSUE THREAD

**Issue by frostbitten** [notepad-plus-plus/notepad-plus-plus#1801]
Been enjoying Np++ for many a-moon and want to bring up an issue I've been having.

I keep a lot of documents open at any time, from 10 to 30, or more. There are certain features that I've found helpful and others that I've found not to be. I've got a few suggestions so I'll just run the list down

| Feature | Comment |
| --- | --- |
| Tabs | Good for when a few documents are open or if you are editing documents near each other in the tabs panel. Not sure if it could be improved in any substantial way, other than not showing the `X` button on inactive tabs when the list is crowded. |
| Ctrl+Tab | Unusable imho. It seems to mimic how `alt+tab` works in Windows, but unfortunately the list of documents is not akin to the window thumbnails visible when `alt+tabbing`. Also, the font size is not legible on retina screens (the former issue was the main dealbreaker). It would make more sense to switch to the next document with each tap of the "tab" key, similar to how web browsers and many other tabbed applications handle that action. See `Screen 1` |
| Doc Switcher | The most effective tool when 15+ tabs are open. It can only be enabled through the preferences panel, however. As a user, I would expect this to be a check on/off switch within the windows menu, similar to adobe products. Also helpful would be a key combo to enable/disable it. See `Screen 2` |
#### Screen 1

![image](https://cloud.githubusercontent.com/assets/593791/14876558/06664fd4-0ce4-11e6-91ed-2f33f674a6e1.png)
#### Screen 2

![image](https://cloud.githubusercontent.com/assets/593791/14876710/10db23d0-0ce5-11e6-8be7-9af0241add9d.png)

**Comment by milipili** [comment]
A tab-switcher with incremental search would be indeed more effective

**Comment by milipili** [comment]
People, give your ideas !

**Comment by coxymla** [comment]
Just being able to open the Doc Switcher with a shortcut or toolbar button (or both) would be a godsend. Plugins like the JSTool often take over it.

**Comment by young-developer** [comment]
Hi guys, as alternative you could use NavigateTo plugin. It allows navigate between opened files very quickly.
https://github.com/young-developer/nppNavigateTo/releases
We discuss all features and enhancements here - https://notepad-plus-plus.org/community/topic/12892/navigateto-navigate-between-files-tabs-quickly-like-a-ninja-d

**Comment by MetaChuh** [comment]
please use the navigateto plugin.

many thanks and best regards.
