### ISSUE TITLE
Notepad++ doesn't close properly any more. Leaves a process running with high CPU. v6.9.1

### ISSUE THREAD

**Issue by clcii** [notepad-plus-plus/notepad-plus-plus#1802]
When I close the latest version it leaves a process in Background processes running with high CPU usage.  v6.9.1
![2016-04-28](https://cloud.githubusercontent.com/assets/1660143/14887457/f32512bc-0d23-11e6-9784-f51566124b1f.png)

**Comment by dail8859** [comment]
Try following these [steps](https://github.com/notepad-plus-plus/notepad-plus-plus/blob/master/CONTRIBUTING.md#reporting-issues).

**Comment by clcii** [comment]
Thanks. Fixed it. HTMLPreview plugin.
