### ISSUE TITLE
task switching takes a long time (>10seconds)

### ISSUE THREAD

**Issue by RealRaven2000** [notepad-plus-plus/notepad-plus-plus#1806]
When I switch to the notepad++ window it often takes 10seconds or more until the tabs/ documents are repainted or usable. It doesn't happen when I switch away to another task and immediately switch back, but it does if I wait for a minute or 2. My theory is that I am using the majority of my notepad files on a LAN network drive which is mapped in a windows library. 

Although all files are also available as local cached copies (you have to do this in order to allow the network drive to be added to a windows library) I believe that npp does some excessive file permissions checking (or other file operation) that causes windows to go back on the network when the task is activated. Is there any way this can be switched off to avoid this speed penalty?

What else might be leading to this delay? I do not experience this with any other software on my system and it is not a RAM issue - I have 8GB and do not often get close to using it all up.

**Comment by Gabr-F** [comment]
I think it's better that you make up a minimal test case with which it always happen (but I'm not a developer, maybe a developer can tell you what's wrong right away).

Be sure that you are not switching to a document with many collapsed folds, displaying them often takes a lot even with local files (I'm not sure if this has been already reported).
