### ISSUE TITLE
[bug] Docked Window Panes / Click and Drag Pane Title to Undock / Drags Erratically (Slowly & Delayed)

### ISSUE THREAD

**Issue by Leif-W** [notepad-plus-plus/notepad-plus-plus#1809]
Hello, apologies if this has already been reported or resolved.

Windows 7, NotePad++ 6.9.1, logged in as normal user, using NotePad++ in Administrator mode.

Edit: Still a problem in 6.9.2

~30 files open.

Find All in All Open Documents, finds ~40 occurrences.

I dragged split window pane up, covering my files to see more of the results, but I needed more space.

Therefore, I click the results pane title bar and drag the pane to undock it.  As I drag the new window around, it moves much slower, jitters around, and continues to move (along previous mouse movement path) after my hand has stopped moving.

The expected behavior is that when click and drag to undock a pane and turn it into a separate window, that the window will move as fast as my hand, remain at the position under the mouse, and not move when my hand has stopped moving the mouse.

Not sure if any other interface elements are docked by default that can later be undocked by click and drag, to test if this behavior affects them also.

Edit: Document Map has the same behavior: docked pane in existing editor window, click and drag to resize on edge, click and drag on title bar to undock and create a "child" window.  Same sluggish movement behavior.  Presumably (as I don't drink) resembles behavior of a severely drunken operator.

Non-docked dialog boxes (Find, Replace, Open Files, dialog, Settings, etc) all seem to work perfectly.

**Comment by MetaChuh** [comment]
please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins if you update from version 7.5.9 or below.
if your issue still persists, and it is still of relevance to you, please feel free to file a new issue as easy to understand and reproducible as possible.

thank you for your help and best regards.

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
(no extra account is needed, just use your github account to sign in)
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)

**Comment by Uhf7** [comment]
I can reproduce the same or a very similar problem with the current Notepad++ version 7.9 under Windows 10 1607. Can anyone confirm this behavior?

### Steps to Reproduce the Issue
- Unpack a `npp.7.9.portable.zip` into a new directory.
- Close all running applications on your computer, except File Explorer.
- Use File Explorer to start the newly unpacked Notepad++.exe.
- Display a Project Panel 1 (View -> Project Panels -> Project Panel 1).
- Make the Project Panel float by double-clicking it's header.
- Drag the Project Panel around a little to see, that everything works smoothly.
- Then, start a Windows UWP app. I tested
  - Alarms & Clock
  - Calculator
  - Calendar
  - the "classic" MS Edge Browser (The current MS Edge is a Win32 application).
- As soon as any Windows UWP app is running in non-minimized state together with Notepad++, then dragging around the Project Panel isn't smooth anymore.

### Debug Information
Notepad++ v7.9   (32-bit)
Build time : Sep 22 2020 - 03:24:22
Path : C:\Tools\Npp_79\notepad++.exe
Admin mode : OFF
Local Conf mode : ON
OS Name : Windows 10 Pro (64-bit) 
OS Version : 1607
OS Build : 14393.576
Current ANSI codepage : 1252
Plugins : mimeTools.dll NppConverter.dll NppExport.dll
