### ISSUE TITLE
Cursor takes wrong position after manual word completion (with one matching word) in alphabets other that latin (checked for cyrillics)

### ISSUE THREAD

**Issue by dzah** [notepad-plus-plus/notepad-plus-plus#1812]
Steps to reproduce:

```
Create a new file (UTF-8)
Type in some long enough word using cyrilics (say, "словосочетание")
Type first few characters of this word (say, "слов") elsewhere and press Ctro+Enter to activate manual word completion.
```

The word gets completed. However, the cursor doesn't jump to the end of the word, but rather takes some new position somewhere in the middle.

This happens only if (1) there is only one matching word, and (2) in cyrillics (other non-latin alphabets not checked)

I am using Notepad++ v6.9.1
Build time : Mar 28 2016 - 19:48:40
OS : Windows 7
Plugins : ClipboardHelper.dll ComparePlugin.dll CustomizeToolbar.dll Explorer.dll FingerText.dll HTMLTag_unicode.dll LightExplorer.dll mimeTools.dll NppColumnSort.dll NppConverter.dll NppCrypt.dll NppExec.dll NppExport.dll NppFTP.dll NPPGit.dll NppMenuSearch.dll NppSnippets.dll NppTextFX.dll PluginManager.dll PyNPP.dll PythonScript.dll RunMe.dll SourceCookifier.dll visimulator.dll XMLTools.dll

**Comment by MetaChuh** [comment]
please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins if you update from version 7.5.9 or below.
if your issue still persists, and it is still of relevance to you, please feel free to file a new issue as easy to understand and reproducible as possible.

thank you for your help and best regards.

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
(no extra account is needed, just use your github account to sign in)
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)
