### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by badphart** [notepad-plus-plus/notepad-plus-plus#1816]
I hope I am not alone but I often have putty / mobaXterm / PyCharm session open on one screen and Notepad ++ on the other.

Wouldn't it be nice if there was a configuration option to put whatever you highlight in NP++ into the clipboard and right click was a paste operation?

What do you think?

Effort : Appreciation > 1:1?

**Comment by donho** [comment]
Don't like Ctre-C ?

**Comment by sasumner** [comment]
Not to speak for @donho but what is described by @badphart is a simple ctrl+c operation in one application followed by a ctrl+v in another application.  Thus there is really nothing to be done for @badphart 's suggestion.

There have been other suggests for "automatic copy on select" but IMO that is problematic and annoying.
