### ISSUE TITLE
Would be much more efficient if support "Backspace Unindent" (for those who use spaces for indentation)

### ISSUE THREAD

**Issue by johnnytemp** [notepad-plus-plus/notepad-plus-plus#1817]
Many programmers hate type 4 backspace to delete an auto-indent, nor other composite key, than just ONE backspace (like when using tab chars for indentation).   :-)

Please reference this plugin:
http://www.virtualroadside.com/blog/index.php/2012/12/03/notepad-plugin-to-enable-unindent-on-backspace-key/

**Comment by johnnytemp** [comment]
I really think Backspace Unindent should be the default, because unindenting some auto-indentation contributes ~95% of the use case of "Backspace" purpose at the leading spaces area, in most programming languages.

If one need some non-tab-stop-aligned leading spaces, the user just either need to type a few space-bar keys to achieve, or press Shift + some Left arrows then "Backspace".  This is only ~5% of the use cases.

Furthermore, if it still seems necessary, the program can provide an option to uncheck default "Backspace Unindent".

Thank you for your reading.

**Comment by Marshallx** [comment]
+1, this is extremely frustrating

**Comment by tmvoss** [comment]
+1

**Comment by algoldst** [comment]
+1

**Comment by MetaChuh** [comment]
please use shift+tab to unindent a code selection.
shift+tab and tab on a code selection will also respect your spaces instead of tabs settings at `settings > preferences > language > tab settings`

thank you for your help and best regards.

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
(no extra account is needed, just use your github account to sign in)
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)

**Comment by sasumner** [comment]
@MetaChuh I think the closure reason is not a good one.  [I'm okay with closure but maybe with a better reason! :) ]

Use case:

Set N++ up for 4 space tabs, replace by space.
Create a .py file.
Type `def test():`
Press Enter
Press Tab
Press Backspace

OP wishes for the single Backspace press to remove 4 spaces.  Currently it removes 1 space.

**Comment by MetaChuh** [comment]
@sasumner 

the notepad++ guide states to use shift+tab to unindent a line or selection.
this also applies for spaced indentation.

it is by design to have full manual control of removing either a single space with backspace, or an indentation, regardless of its type, with shift+tab.

below is a screencast example of line unindent and block unindent for a .py file using spaced indentation.

as unindenting spaced indentation with a single keypress is an existing feature of notepad++, there will be no need to implement a different keyboard shortcut at the notepad++ core.

![unindent spaced indentations](https://user-images.githubusercontent.com/45773305/56579637-fdf7f700-65d0-11e9-9268-4d6dcd33e252.gif)

thank you for your help and best regards.

**Comment by sasumner** [comment]
I wish I knew how to post a screencast here.  I can make a .gif with ScreenToGif , but I don't know how to "get it in here". :)

Ah, okay, the original closure reason was that "You can do it with one keycombo, and that is what is being asked for".  That works for me as I already have a Pythonscript that does the Backspace key functionality being requested. :)

It may not satisfy the initial requester (Shift+Tab is much more awkward and maybe less intuitive than BS), but oh, well...

**Comment by johnnytemp** [comment]
If the author insist this is unimportant, just keep it.

However, note that many other editors like Sublime, VSCode, etc have Backspace to Unindent.

Futhermore, missing this feature is the main inconvenience when one user migrate from using Tab indentation to using space indentation.  This is because when using Tab indentation one can use Backspace to undo a Tab key, which is much more intuitive and fast in typing.  (You type how many keystrokes, backspace how many times undo it)

Thanks.

**Comment by johnnytemp** [comment]
> +1, this is still frustrating. Do any plugins/options exist yet to change this behavior?

See the link I provided in my first comment.  There is a plugin to download.

**Comment by sasumner** [comment]
For anyone interested, here's a Pythonscript (I call it BackSpaceOverride.py) that implements the behavior. To use it one would remap SCI_DELETEBACK being tied to the Backspace key in Shortcut Mapper's Scintilla section, and tie it to the script in the Shortcut Mapper's Plugins section.

    def BSO__main():

        if editor.getUseTabs(): editor.deleteBack(); return
        if editor.getSelections() > 1: editor.deleteBack(); return
        if editor.selectionIsRectangle(): editor.deleteBack(); return
        if editor.getSelectionStart() != editor.getSelectionEnd(): editor.deleteBack(); return
        curr_pos = editor.getCurrentPos()
        if curr_pos == 0: return  # at start of doc, nothing to the left of caret to delete
        curr_col = editor.getColumn(curr_pos)
        if curr_col == 0: editor.deleteBack(); return  # caret in first curr_column of line
        tab_width = editor.getTabWidth()
        if (curr_col % tab_width) != 0: editor.deleteBack(); return
        if editor.getCurLine()[:curr_col] != ' ' * curr_col: editor.deleteBack(); return
        for _ in range(tab_width): editor.deleteBack()

    BSO__main()

**Comment by dinkumoil** [comment]
I wrote a plugin that activates the "Backspace unindents" Scintilla feature. Its name is _ExtSettings_. You can download it [>>> here <<<](https://sourceforge.net/projects/extsettings/). It will also be available soon via _PluginsAdmin_.
