### ISSUE TITLE
Unclosed CDATA causes infinity loop (XML Tools -> Pretty print)

### ISSUE THREAD

**Issue by DerLeviathan** [notepad-plus-plus/notepad-plus-plus#1819]
When a file contains unclosed CDATA and Pretty print from XML Tools is triggered (with Ctrl+Shift+Alt+B) notepad++ enters some infinity loop (program hangs and CPU is wasted). I could reproduce this issue with a single file containing the string "aa<![CDATA[". The preciding two chars "aa" are needed to trigger the loop. Only one "a" is not enough...

notepad++ v6.8.2
upgraded to v.6.9.1 - Issue still present...

**Comment by dail8859** [comment]
Please report this to the developer of XML Tools.
