### ISSUE TITLE
The file named 'new  0.txt' is only ever created at startup, never for new tab

### ISSUE THREAD

**Issue by Eldaw** [notepad-plus-plus/notepad-plus-plus#182]
When launching a fresh instance of Notepad++ it creates a tab for 'new  0'. You can then create tabs for 'new 1', 'new 2', etc. If you close 'new 1' and 'new 2' and then create a new tab, it'll use the lowest possible number that's not already open, so in this example it'll recreate 'new 1'.

But if you close all the 'new x' tabs, and then create a new tab, it starts from 'new 1', i.e. it never tries to use 'new 0'. The only time 'new 0' is created is at initial startup. This can't be right. Either Notepad++ should start counting at 0 or at 1. Not sometimes at 0 and other times at 1.

**Comment by MarkMaldaba** [comment]
This is a regression, not an enhancement.  Old versions of Notepad++ (e.g. 6.2.1) would open with "new 1".  In the latest version (6.7.9.2) it opens with "new 0".  There was obviously a regression introduced somewhere between those two versions.  "new 1" is the correct numbering for humans,

**Comment by milipili** [comment]
It does not prevent the product from working, so it's not a bug. The labels will be modified soon anyway for a more complete set.

**Comment by milipili** [comment]
here it is ! :)

**Comment by MarkMaldaba** [comment]
I'm not sure that the definition of bug is that it stops the product from working (unless by 'not working' you mean 'exhibits incorrect behaviour', in which case that is exactly what is happening here), but either way I agree that 'regression' is a more appropriate label.
