### ISSUE TITLE
[bug] Notepad++ always crash when press F11 or F12 (once or twice) when there is a split view, with HexEditor plugin installed

### ISSUE THREAD

**Issue by johnnytemp** [notepad-plus-plus/notepad-plus-plus#1820]
In my test, the split view is a horizontal split.  (i.e. upper and lower documents)

I am on Windows 10 Pro 64-bit OS.
Notepad++ version : 6.9.1
### Testing steps
1. No split view at first
2. Opened 2 or more documents
3. Right-click one document's tab, and choose "Move to Other View"
4. Press F11 twice.
5. Crashes

**Comment by johnnytemp** [comment]
No one can reproduce?

**Comment by rushikesh90** [comment]
I tried the steps, not reproducible

**Comment by rushikesh90** [comment]
Btw I am using 6.9,2 can you try after upgrading

**Comment by johnnytemp** [comment]
Hi, I found the reason.  Version 6.9.1 only crashes if the HexEditor.dll plugin is installed in Notepad++'s "plugins" directory.  You could have a try.

**Comment by cubei** [comment]
For me not only Notepad++ crashes if F12 is pressed, but the complete OS. Need to restart the computer.

**Comment by donho** [comment]
It's plugin issue.

**Comment by sarahnorthway** [comment]
I've been running into this (split screen and HexEditor plugin installed, newest version of everything). I realize it's a plugin issue Notepad++ can't fix but just posting to say the easy workaround is to unbind F11 via Settings > Shortcut mapper. Manual fullscreen doesn't crash it, just the hotkey.
