### ISSUE TITLE
Show notification for changed/removed file only when actually showing the changed/removed file tab

### ISSUE THREAD

**Issue by chrischu** [notepad-plus-plus/notepad-plus-plus#1822]
Currently, whenever I tab into Notepad++ to look at some file, very often I get a couple of message boxes telling me that other files have changed/were removed and if I want to reload/close them.

This can be pretty annoying because besides the message box popping up, the changed/removed file also gets focused so I have to manually select the file I originally wanted to look at.

In my opinion it would be better to only show these changed/removed notifications when I actually focus the affected file so that the notifications don't interrupt my workflow when I'm not even interested if another file was changed/removed.

**Comment by dave004** [comment]
I would also like this feature. Unexpected popups are very distracting, time consuming and frustrating.

**Comment by chrischu** [comment]
Any update on this?

**Comment by 42degrees** [comment]
This is a duplicate of [1087](https://github.com/notepad-plus-plus/notepad-plus-plus/issues/1087)
