### ISSUE TITLE
Find/Replace dialog box is see-thru

### ISSUE THREAD

**Issue by writer0101** [notepad-plus-plus/notepad-plus-plus#1824]
The Find/Replace dialog box is hard to read because it shows the text behind it rather than being opaque. I know it was opaque in an earlier release but it became transparent several months ago so I cannot tell you in which release this issue began.
![find-replace-dialog-is-transparent](https://cloud.githubusercontent.com/assets/13625587/15031999/3eb0c846-122b-11e6-9eb6-5dc4888ffafb.PNG)

**Comment by cmeriaux** [comment]
Hello,
uncheck the "transparency option" (bottom right of the find/replace dialog) and you'll get what you wan't.

**Comment by writer0101** [comment]
Thank you. I must have hit that button by mistake at some point.

**Comment by Leif-W** [comment]
Alternatively, leave the "Transparency" checked and use the "On losing focus" radio button.  That can present a handy use case, when the Find/Replace dialog is slightly off to the side, possibly partially covering another window, which you want to see while editing from within NotePad++.
