### ISSUE TITLE
Updating doesn't work behind corporate proxy

### ISSUE THREAD

**Issue by DashNY** [notepad-plus-plus/notepad-plus-plus#1826]
I'm working for a company that uses HTTP proxy and installs its own HTTPS certificate on each machine.
When I do `? => Update Notepad++`, I get this error popup.

---

**Comment by tvdijen** [comment]
Exact same issue here.

**Comment by MetaChuh** [comment]
@DashNY 

please check your proxy settings at `? > set updater proxy`.
if your company has https wrapping, please consult with your local it department.

thank you for your help and best regards.

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
(no extra account is needed, just use your github account to sign in)
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)

**Comment by cocoon** [comment]
Just to add one more possible cause for this error message (as I had it now):

In a Windows 2019 Server VM I had the following Policy set (can be local or a domain policy):

Computer --> Security Settings --> Public Key Policies --> Certificate Path Validation Settings --> Network Retrieval:
Define: checked
Automatically update: unchecked
Allow issuer: unchecked

![2021-06-30_AD_GPO_Certificate_Path_Validation](https://user-images.githubusercontent.com/1071741/123940431-77ea4e80-d999-11eb-9e32-6cd6c251d5fe.png)
