### ISSUE TITLE
Toggle Single Line Comment should keep existing comments

### ISSUE THREAD

**Issue by eymre** [notepad-plus-plus/notepad-plus-plus#1829]
Toggle Single Line Comment should not un-comments any lines, while commenting out a group of lines. 

Steps to reproduce:
1. Create a new file 'test.cpp' and with the three lines below:
a
// b
c
2. Select all three lines and press Ctrl+/ (Toggle Single Line Comment)

Expected:
// a
// // b
// c

Actual:
// a
b
// c

Notes:
If all lines are already commented out, all should be un-commented. If one or more are un-commented, then all lines should be commented out together.

**Comment by eymre** [comment]
This issue is related to https://github.com/notepad-plus-plus/notepad-plus-plus/issues/428

Basically, requesting a single 'toggle line comments' command that will execute Ctrl+K or Ctrl+Shift+K as described in the notes above.

**Comment by Ray-Haynes** [comment]
Yes the Ctrl+K/Ctrl+Shft+K works correctly in that it adds and remove comments to all selected lines but the right click context menu has the toggle function which works as described above which is not very helpful. The right click context menu should have a Line Comment and Line Uncomment entries not the toggle function.

**Comment by MetaChuh** [comment]
@eymre 

this is a limitation of the toggle feature.
please use Ctrl+K or Ctrl+Shift+K for mixed line commented content.

thank you for your help and best regards.

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
(no extra account is needed, just use your github account to sign in)
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)
