### ISSUE TITLE
'new  0.txt' still gets created with 2 spaces in its filename

### ISSUE THREAD

**Issue by Eldaw** [notepad-plus-plus/notepad-plus-plus#183]
PR 140 changed 1 line of code in Notepad++ v6.7.9 in order that new files such as 'new 1', 'new 2', etc. only have 1 space in their name rather than 2.
https://github.com/notepad-plus-plus/notepad-plus-plus/pull/140

But this only partially fixed the issue. The first file that gets automatically created when launching a fresh instance of Notepad++, 'new  0.txt' still has 2 space in its name.

**Comment by milipili** [comment]
As a consequence, #97 is not resolved.
