### ISSUE TITLE
Box text selections offset by different text sizes

### ISSUE THREAD

**Issue by ghost** [notepad-plus-plus/notepad-plus-plus#1830]
(Hold alt and left click on a line, then drag your mouse up or down with alt held to make box selections.)

Box selections sometimes have problems due to text size differences. This is possible when defining a custom highlighting scheme where some text is given a different font size. For example, make lines of small and large text, then define a box selection (with no width) so whatever you type is prepended to these lines. Type many spaces. You'll see that small lines fall off and the spaces are sometimes erroneously inserted ahead of a few characters.

Operating system Windows 7 SP1 .
Notepad++ Edition: V6.6.4, but this is obscure and you should test it on the most recent version because chances are it's probably not fixed.
![box selection example](https://cloud.githubusercontent.com/assets/11749551/15065705/31095284-1317-11e6-84da-8c3d9175f9fa.png)

**Comment by MetaChuh** [comment]
please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins if you update from version 7.5.9 or below.
if your issue still persists, and it is still of relevance, please feel free to file a new issue as easy to understand and reproducible as possible.

thank you for your help and best regards.

**Comment by sasumner** [comment]
@ghost, it is only going to work visually nicely if you have a monospaced font selected.  In your screenshot examples you do NOT have such a font selected.
