### ISSUE TITLE
Where is the 'normal text' setting? :)

### ISSUE THREAD

**Issue by Presskopp** [notepad-plus-plus/notepad-plus-plus#1832]
https://cloud.githubusercontent.com/assets/18373563/15093140/850752ce-147e-11e6-9654-fad4a5ab129d.jpg

I was searching for the setting for 'normal text', and was confused where to find it, because I didn't know what phrase to search. Maybe you put this one at top level of the menu?

**Comment by aaaxx** [comment]
That's a good idea: at the top of the Language dropdown, with a separator line after it. I also remember having trouble finding it the first time.

And shouldn't it be called "Plain text" in English? Or maybe "None" since it's not really a "language"?

**Comment by MetaChuh** [comment]
please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins if you update from version 7.5.9 or below.
if your issue still persists, and it is still of relevance to you, please feel free to file a new issue as easy to understand and reproducible as possible.

thank you for your support and best regards.

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
(no extra account is needed, just use your github account to sign in)
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)
