### ISSUE TITLE
I am getting crashes when using File -> Open.

### ISSUE THREAD

**Issue by adamrrowe** [notepad-plus-plus/notepad-plus-plus#1835]
Notepad++ v6.9.1
Build time : Mar 28 2016 - 19:48:40
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10
Plugins : mimeTools.dll NppConverter.dll NppExport.dll PluginManager.dll 

It started happening a couple of weeks ago. If I open a file using the right click context menu, it opens ok. If I try to open a file from within NP++ using the File->Open menu or CTRL-O, it crashes.

I have tried:
- clearing recent file history
- uninstalling/reinstalling NP++
- renaming plugins directory

**Comment by icyblade** [comment]
Same here. "Edit with Notepad++" in context menu works, but File -> Open crashes the application.

- Version: Notepad++ v6.9.2
- Build time: May 18 2016 - 00:34:05
- Operation System: Windows 8.1 Pro 64bit enUS

Things I have tied:
- Remove all plugins
- Reinstall Notepad++
- Run Notepad++ as administrator

**Comment by donho** [comment]
I believe this issue has been fixed since long time ago.
Update your Notepad++ to the latest version (v7.6.6).
If the issue persists, please create a new issue for it.
Thank you.
