### ISSUE TITLE
Moved "hexeditor.dll" to disabled folder

### ISSUE THREAD

**Issue by markusrudolf** [notepad-plus-plus/notepad-plus-plus#1836]
...because of stability issues. 
I never experienced any issues, but I constantly have to move it manually from the disabled folder into the plugins directory on each tiny update of the software. 

Can I *please* be asked by the installer/updater if I want to move the plugin to the "disabled" folder due to stability issues or wanna continue on my own risk. 

It's so annoying!

Thanks!

**Comment by xylographe** [comment]
Rename `HexEditor.dll` in the `plugins` folder to `HexEditorOK.dll`.

**Comment by markusrudolf** [comment]
Great idea! Thx!
