### ISSUE TITLE
Debugging Feature

### ISSUE THREAD

**Issue by aakarshit-agarwal** [notepad-plus-plus/notepad-plus-plus#1837]
Please add debugging for languages like C,C++ and Python.

**Comment by donho** [comment]
??

**Comment by sasumner** [comment]
To expand upon @donho's comment:  Notepad++ is not (and doesn't aim to be) an IDE (integrated debugging environment).  IDEs already exist and can live nicely right alongside Notepad++ -- especially with the "file status detection" feature in Notepad++ and likely in any realistic IDE as well.
