### ISSUE TITLE
Macro Crashes while replacing

### ISSUE THREAD

**Issue by charlieb000** [notepad-plus-plus/notepad-plus-plus#1840]
The macro was to use find/replace lines in a DXFP file and convert to SRT format for subtitles on videos.
Firstly i would rather not record but write this macro (and able to save it as a file!!!!). 

There are like 18 or so replacements causing the file to increase to 4x the lines, running the macro caused npp do the 1000 or so lines and crash (i expected it to keep the macro recorded, but it did not keep it, so no i am not going to bother re-recording for now – so the title of the bug is vague). If it matters, i had the "document map" up.   Videos with subtitles were downloaded using youtube-dl from links that used *.akamaihd.net

Alters from / to (contains xml)
[new 3.txt](https://github.com/notepad-plus-plus/notepad-plus-plus/files/256530/new.3.txt)

you will probably want to write a new interface to quickly recreate the bug so here is a list of replacements (tab delineated, "" = null ).
[Book2.txt](https://github.com/notepad-plus-plus/notepad-plus-plus/files/256521/Book2.txt)

I would have tried a newer version than 6.8.5, but the site is crippled. Download links timeout (link given is: https://notepad-plus-plus.org/repository/6.x/6.9/npp.6.9.Installer.exe), and if i click on “Download” (at left) repeatedly i get: https://notepad-plus-plus.org/contribute/download/download/download/

[NppDump.zip](https://github.com/notepad-plus-plus/notepad-plus-plus/files/256488/NppDump.zip)

PS: the video card is a basketcase on this PC, ollydbg crashes it completely (need to go into standby to recover, but i found an option to cause it to do screen updates slower during scroll so its now fine), i also feel that the video card can effect the stability of some programs - so not sure if it is at fault here.

**Comment by MetaChuh** [comment]
please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins if you update from version 7.5.9 or below.
if your issue still persists, and it is still of relevance to you, please feel free to file a new issue as easy to understand and reproducible as possible.

thank you for your support and best regards.

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
(no extra account is needed, just use your github account to sign in)
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)
