### ISSUE TITLE
Notepad++ v6.9.1 crashes

### ISSUE THREAD

**Issue by bethEpperson** [notepad-plus-plus/notepad-plus-plus#1843]
Event Viewer entry:
Faulting application name: notepad++.exe, version: 6.9.1.0, time stamp: 0x56f96ebd
Faulting module name: ntdll.dll, version: 10.0.10586.122, time stamp: 0x56cc16f5
Exception code: 0xc0000005

I open the editor
Select to open an existing file and proceed to make edits (html file)
The application throws up an errr dialog stating that the app has failed and upon closing the dialog the app closes
When I reopen the app - the chosen file shows that it is empty. 
I select the file to open in the browser, the data renders, I close Notepad again and then try to open the file and the data displays within notepad

This is the 2nd time this has happened in the last 2 days.

Notepad++ v6.9.1
Build time : Mar 28 2016 - 19:48:40
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10
Plugins : mimeTools.dll NppConverter.dll NppExport.dll PluginManager.dll 

Fault bucket 129057038488, type 5
Event Name: FaultTolerantHeap
Response: Not available
Cab Id: 0

Problem signature:
P1: notepad++.exe
P2: 6.9.1.0
P3: 56F96EBD
P4: ffffbaad
P5: 
P6: 
P7: 
P8: 
P9: 
P10: 

Attached files:
C:\Windows\ServiceProfiles\LocalService\AppData\Local\Temp\FTH6FF1.tmp\fthempty.txt
C:\Windows\ServiceProfiles\LocalService\AppData\Local\Temp\WER7001.tmp.WERInternalMetadata.xml

These files may be available here:

Analysis symbol: 
Rechecking for solution: 0
Report Id: ef2118e3-16c2-11e6-b5b2-408d5cc5fd2a
Report Status: 0
Hashed bucket: 9df7fa568250b74bcf7b899a7bfc4966

Fault bucket 108089164290, type 1
Event Name: APPCRASH
Response: Not available
Cab Id: 0

Problem signature:
P1: notepad++.exe
P2: 6.9.1.0
P3: 56f96ebd
P4: ntdll.dll
P5: 10.0.10586.122
P6: 56cc16f5
P7: c0000005
P8: 000402fa
P9: 
P10: 

Attached files:
C:\Users\Beth\AppData\Local\Temp\WER706E.tmp.WERInternalMetadata.xml

These files may be available here:
C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_notepad++.exe_b2eef5bab74e1a1c7cdd12abfad99bcbc6e34e_5b00806a_6acc8c14

Analysis symbol: 
Rechecking for solution: 0
Report Id: c4c8b607-6cc8-4321-b28f-0a20dd5b76d5
Report Status: 0
Hashed bucket: 8d166dd435903118bfefe612f1f5a999

**Comment by ucffool** [comment]
I can confirm in Windows 7 the same crash style happens frequently, specifically that it saves a 0 byte file when you try and SAVE changes and the app crashes. In previous versions, any crash would simply forget the open tabs since last clean close, so not a huge deal. This crash is much worse with the 0 byte write. 

Be advised that the full file at time of Save/Crash is still in the ...AppData/Roaming/Notepad++/Backup folder, so it at least writes the backup in real-time before the 0 byte overwrite of the main file.

**Comment by dail8859** [comment]
Most likely #1930 has addressed this issue. If you still run into this problem again once v6.9.3 comes out, please feel free to reopen.
