### ISSUE TITLE
Incremental Search Next/Previous keyboard shortcuts

### ISSUE THREAD

**Issue by martbase** [notepad-plus-plus/notepad-plus-plus#1845]
I use the incremental search tool a lot especially for searching in multiple open documents.

It would be really nice if there were keyboard shortcuts for finding the next/previous search string instead of moving the mouse to the bottom of the edit window and clicking either of the buttons.

Suggested shortcut keys `Alt+<` for previous and `Alt+>` for next since they match the button captions.

**Comment by EmanNo1** [comment]
second this request. n++ 7.3.2 removed Ctrl+Alt+I nth times to loop through results. Would suggest Ctrl-Alt-> and Ctrl-Alt-<.

**Comment by sasumner** [comment]
I think the suggestion here is that the next/previous shortcuts, if added, are to work while the document being edited has focus, because when the Incremental find window has focus Enter is equivalent to pressing the > button and Shift+Enter is the same as pressing the < button.

**Comment by MetaChuh** [comment]
please use enter and shift enter for incremental search
