### ISSUE TITLE
have important constants files be available through an "iface" file like scintilla

### ISSUE THREAD

**Issue by kbilsted** [notepad-plus-plus/notepad-plus-plus#1846]
In order to make things easier for people making plugins, it would be nice if central constant files such as https://github.com/notepad-plus-plus/notepad-plus-plus/blob/master/PowerEditor/src/MISC/PluginsManager/Notepad_plus_msgs.h are generated from an ".iface" file similar to scintilla ( https://github.com/notepad-plus-plus/notepad-plus-plus/blob/master/scintilla/include/Scintilla.iface) 

Alternatively, or as a first step prefix each `#define` with a well-defined comment in a easily parseable format that can be extracted like the .iface file of scintilla.

For the C# plugin pack for notepad++ I have been able to code-generate many _thousands_ of lines of code from the scintilla iface file. See eg https://github.com/kbilsted/NotepadPlusPlusPluginPack.Net/blob/topic/editorgateway_v1/Visual%20Studio%20Project%20Template%20C%23/PluginInfrastructure/ScintillaGateway.cs https://github.com/kbilsted/NotepadPlusPlusPluginPack.Net/blob/topic/editorgateway_v1/Visual%20Studio%20Project%20Template%20C%23/PluginInfrastructure/IScintillaGateway.cs 
https://github.com/kbilsted/NotepadPlusPlusPluginPack.Net/blob/topic/editorgateway_v1/Visual%20Studio%20Project%20Template%20C%23/PluginInfrastructure/Scintilla_iface.cs

I would like to do the same for the notepad++ messages.

this will make it easy for pluginwriters across all languages to easily stay in sync and create a nice language specific gateway to notepad++

**Comment by MetaChuh** [comment]
please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins if you update from version 7.5.9 or below.
if your issue still persists, and it is still of relevance to you, please feel free to file a new issue as easy to understand and reproducible as possible.

thank you for your support and best regards.

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
(no extra account is needed, just use your github account to sign in)
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)
