### ISSUE TITLE
 [Notepad++V6.9.1] Marco Save as popup appering multiple time when user want to cancel  this popup

### ISSUE THREAD

**Issue by anstiwar** [notepad-plus-plus/notepad-plus-plus#1847]
Objective :  user want to record a macro and want to run this 100 times using “Run a Marco Multiple Times” options.

Below are the steps to reproduce this issue

Step 1#   User recorded  macro using start and stop macro option ----> No issue

Step 2#  Click on  “ Run a Marco Multiple Times” option  -----> No issue

Step 3#   User  set  100  for times and now select "Trim Trailing and Save "  from  “Macro to Run”  drop down to save this.  -----> No issue

Step 4# “Save As” popup appear .  If user provide all required Information and save this , then no issue seen.
But If user want to cancel this “ Save As”  popup , then user  have to cancel this “Save As”  popup 100 time (Equal to which we set value on "Run a Marco Multiple times" dialog).
which is not a good user experience to handle this situation, if this value is very large than it is very difficult to cancel this "Save As" dialog.

**Comment by MetaChuh** [comment]
please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins if you update from version 7.5.9 or below.
if your issue still persists, and it is still of relevance to you, please feel free to file a new issue as easy to understand and reproducible as possible.

thank you for your support and best regards.

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
(no extra account is needed, just use your github account to sign in)
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)
