### ISSUE TITLE
BUG: TextFX deleting unique lines

### ISSUE THREAD

**Issue by admclrk** [notepad-plus-plus/notepad-plus-plus#1849]
When sorting at column (both case sensitive/insensitive) using TextFX with 'sort UNIQUE columns' option active, the program can cause a unique element to be trimmed if it is both:
    a) at the bottom of the list
    b) 'similiar' to an item above it in the list

Below is a simple 10 line example test that will recreate the bug:

GAA_VDX10QFF
GAA_VDX10QFFX
VAA_X25QFFX
VAA_X3QFF
VAA_X5QFF
VAA_XCQFF
VAA_XEOQFF
VAA_X495QFF
VAA_X12QFF
VAA_X25QFF

In the example above line VAA_X25QFF will vanish when an column sort is applied. It appears that the program interprets that it is identical to VVA_X25QFFX. If you add another character the end of VAA_X25QFF, (e.g., VVA_X25QFFa), the program identifies it as unique as intended.

Windows 7 64 bit,  NP++ v6.9.1 build time Mar 28 2016 19:48:40

![image](https://cloud.githubusercontent.com/assets/19330844/15222395/1095ee54-1835-11e6-912d-35996a4677b0.png)

**Comment by dail8859** [comment]
This is a problem with the TextFX plugin and not Notepad++.

**Comment by phidrho** [comment]
I have expirienced bug too, but found out workaround, before you run plugin, you must add a newline at the end of list, then plugin works fine.

_**1st example -> 316 will be erased (bug)**_
--------------------
[row_num] text
--------------------
[1] 316/2
[2] 316/3
[3] 316
--------------------

_**2nd example -> 316 will NOT be erased (works as expected)**_
--------------------
[row_num] text
--------------------
[1] 316/2
[2] 316/3
[3] 316
[4]
--------------------
