### ISSUE TITLE
Error with SQL Syntax Highlighting

### ISSUE THREAD

**Issue by golaat** [notepad-plus-plus/notepad-plus-plus#1852]
Occurs in v6.9.1

1. Open a new Notepad++ tab. 
2. Set the language to SQL.
3. Paste the following line:

`print '1234' INSERT INTO LEGALENTITY (LegalEntity_Name, Entity_Number, Create_Date, User_Create_Sysname, Program_Update_Name) VALUES ('Barney Rubble','1234', GETDATE(), REPLACE(UPPER(SYSTEM_USER), 'DOMAIN\',''), 'MANUAL')`

Now paste the following additional line:

`print '2345' INSERT INTO LEGALENTITY (LegalEntity_Name, Entity_Number, Create_Date, User_Create_Sysname, Program_Update_Name) VALUES ('Fred Flintstone','2345', GETDATE(), REPLACE(UPPER(SYSTEM_USER), 'DOMAIN\',''), 'MANUAL')`

Notice how syntax highlighting on the second line is invalid.

![image](https://cloud.githubusercontent.com/assets/6027610/15230429/954656ba-1863-11e6-90fa-ce4ae4c5d42e.png)

Adding an (erroneous) trailing quote (') to the end of the first pasted line seems to resolve the syntax highlighting issue on the second line.

**Comment by xylographe** [comment]
Caused by the backslash in `'DOMAIN\'`.
