### ISSUE TITLE
[Feature Request] Encapsulating feature

### ISSUE THREAD

**Issue by jsh562** [notepad-plus-plus/notepad-plus-plus#1853]
Hello,

I use np++ exclusively for all my programming and i love it.
I would really like a feature that will allow me to encapsulate or surround a certain selected/highlighted "phrase" with a chosen character.

**ex. 1.**
double-click/highlight "click" and by pressing a certain combination of keys and the apostrophe key, it surrounds "click" with apostrophes.
i.e. 
1. `$(#button_calculate).on(click,function(e){`
2. `$(#button_calculate).on('click',function(e){`  

**ex. 2.**
similarly, allow me to highlight "#button_calculate" and by pressing the same combination of keys as above and the double quote key.
i.e. 
1. `$(#button_calculate).on('click',function(e){`
2. `$("#button_calculate").on('click',function(e){`  

I hope this is understandable and is a valid feature req! Thanks!

---

Additionally,
It would be awesome if you could incorporate parenthesis and brackets into this as well.
e.g. 
if you use the same combination of keys but it recognizes when the key has a separate start and end character such as for parenthesis and brackets, it will encapsulate the highlighted phrase with the appropriate start and end characters.
OR
use a slightly different combination of keys to achieve the same result.

**ex. 3.**
allow me to highlight "#button_calculate" and by using a combination of keys and the open parenthesis key.
i.e. 
1. `$#button_calculate.on('click',function(e){`
2. `$("#button_calculate").on('click',function(e){`

**Comment by MetaChuh** [comment]
please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins if you update from version 7.5.9 or below.
if your issue still persists, and it is still of relevance to you, please feel free to file a new issue as easy to understand and reproducible as possible.

thank you for your support and best regards.

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
(no extra account is needed, just use your github account to sign in)
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)

**Comment by sasumner** [comment]
@jsh562 If you still have interest in something like this, then I think maybe a scripted solution would be a good one.
