### ISSUE TITLE
Ctrl+C copies current line, when no text is selected

### ISSUE THREAD

**Issue by deangoddard** [notepad-plus-plus/notepad-plus-plus#1854]
*Suggestion* - I've become use to Visual Studio's Ctrl+C or Ctrl+X which copies or cuts the current line to the clipboard when no text is selected regardless of where along the line the current cursor resides.  And when you Ctrl+V, it will paste it as a new line, rather than as text from the current cursor place holder ie: insert a new line then paste from position 0.  I miss it from Notepad++

**Comment by xylographe** [comment]
[Visual Studio Line Copy plug-in](https://bitbucket.org/zastrowm/notepad-visualstudiolinecopy)

**Comment by deangoddard** [comment]
Awesome!  Thanks xylographe!  :)
