### ISSUE TITLE
Notepad++ Crash when saveing a new file while opening something

### ISSUE THREAD

**Issue by TPRammus** [notepad-plus-plus/notepad-plus-plus#1857]
Notepad++ crashes after you save a (new) file while opening an other file.

Video of it: https://www.youtube.com/watch?v=balHtvy4Toc

**Comment by gszo123** [comment]
Issue reproduced on 6.9.2.

This is due to Notepad++ trying to save an empty file "new 1" that was replaced with a newly open file and already cannot be accessed.

Core dump attached.
[NppDump.zip](https://github.com/notepad-plus-plus/notepad-plus-plus/files/288369/NppDump.zip)
