### ISSUE TITLE
Variable name for workspace folder

### ISSUE THREAD

**Issue by rishavs** [notepad-plus-plus/notepad-plus-plus#1863]
the way we define current directory as “$(CURRENT_DIRECTORY)” in Run command, can we also have "“$(WORKSPACE_DIRECTORY)” as a variable so that we can create customized run commands. 

This essentially allows me to use NPP as a lightweight IDE.

**Comment by frafall** [comment]
Bump, I use Folders as Workspace and macros to compile, currently I have to hardcode the root of the folder for the "make" command. Just having a $(WORKSPACE_DIRECTORY) would simplify macro writing on folders a lot as well as enabling generic macros cross multiple projects.
