### ISSUE TITLE
Implement user commands for moving the current file tab

### ISSUE THREAD

**Issue by pnedev** [notepad-plus-plus/notepad-plus-plus#1864]
Hello,

Now the only way to move a file tab (change its position in the files tab-bar) is to drag & drop the tab across the files tab-bar.
It will be very handy to have commands that accomplish that.

For example like we now have
`View / Tab / Next Tab` and `View / Tab / Previous Tab`
it will be great to have
`View / Tab / Move Tab Right` and `View / Tab / Move Tab Left`.

This will be very useful from user perspective and as a way to access this functionality from a plugin as well.

Thanks for considering that request.

Best Regards,
Pavel

**Comment by Yaron10** [comment]
Hello,

I'd like to add a related request: an option to move to the last active tab (i.e. move from the current tab to the previously active one).

Thank you.
BR

**Comment by cmeriaux** [comment]
Hello Pavel, I sorry but you may be wrong.
You can move a file to another tab with the contextuel menu of a file (tab bar) : "move to other view" or "clone to other view". 
Those 2 functions are also available in the shortcut mapper : main menu / item 137 and item 138

**Comment by pnedev** [comment]
Hello @cmeriaux ,

Thanks for commenting.

The functionality I'm talking about is not "Move to other View".
By "move" I was not referring to moving a file between MAIN view and SUB view.
I was referring to moving a file tab to the left or right in the same view,
in other words - changing the files order in one view (re-ordering files tabs if you will).

Thanks again.

BR

**Comment by pnedev** [comment]
Thank you guys.
