### ISSUE TITLE
Freeze with network files open & Workaround

### ISSUE THREAD

**Issue by PomDev2** [notepad-plus-plus/notepad-plus-plus#1866]
After opening one or more networked files (files on a windows network share), then switching to another application for a period of time, then switching back (e.g., to paste or make a note), NP++ freezes for about 15 seconds, perhaps per networked file (that could be 45 seconds for 3 opened files). This does not occur for files on the local disk. For this test, I renamed the plugin folder, and plugins are not available. So it is just the main app doing this.

This has been an issue for years. I believe issue 973 was the same issue. (I am tempted to build and debug this problem myself.) I agree with checking for updates on files when activating the app, but it shouldn't hang the app for so long (1 or 2 seconds at the most). Instead, it should happen on a separate thread.

**Comment by PomDev2** [comment]
Workaround Found

Well, it's been 8 days since the first post, so, being impatient, I downloaded the source and examined the software. AFAICT, the function Buffer::checkFileState() is called for every open buffer every time NP++ is reactivated. This function uses the PathFileExists() Windows API function *multiple times* to see if the file can be opened. This function is the topic of much discussion on the web. Apparently, it is very slow with UNC names. The MSDN documentation includes a note that the function can be used only for unc files, and not \\server or \\server\share, which has implications for creating new directories (e.g., for backup), etc. 

I was wondering how I would patch my copy of NP++, when I tried a little experiment. I mapped a drive letter to the network share I was using, and open the networked files only through that mapping instead of using a unc path. Closing then reopening NP++ (to pick up the mapping), then switching away from NP++ with three open file, browsing, etc., for an extended period of time, then reactivating (clicking on) NP++, there was no hang! Hooray! I can use my computer again!

Of course, this is not a real fix. I do need to be able to open files on network shares using unc paths, so I would vote to have this problem really addressed. I guess the answer is to replace the PathFileExists() function with something else that doesn't hang so badly using network shares. And to call it just once per function call (OK, twice if wow64 redirection is in effect) and save the result. 

I hope these posts are not too obnoxious. The good news is that using a drive mapping really eliminates the problem for files on a small number of machines (one drive letter each) that have to be open all day long and might be modified by another user or process. The notification still happens right away, which is great! Thank you all.

**Comment by saturdaywalkers** [comment]
A possibly related issue (or could be a new bug)

I'm editing (small) remote files on a Unix server using Windows 10 / DAV (client) and Apache / DAV (server). Usually I have a lot ( ~30) of files open.

Every so often, usually when switching from 1 files to another, or coming back to the file after doing something else, there a short 2 or 3 second freeze. Never the 15 sec freeze as mentioned above.

**Comment by javicaballero** [comment]
I have the same issue.. it freezes for about 2, 3 seconds when editing a network file.. it's very annoying.. any ideas?

**Comment by RoboBurned** [comment]
There should be an option to disable file state check if the file is on a network path.
I often edit files over a VPN connection and when I disconnect the network without closing all tabs Notepad++ just freezes.

**Comment by MetaChuh** [comment]
please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins if you update from version 7.5.9 or below.
if your issue still persists, and it is still of relevance to you, please feel free to file a new issue as easy to understand and reproducible as possible.

thank you for your support and best regards.

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
(no extra account is needed, just use your github account to sign in)
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)
