### ISSUE TITLE
Shortcut to reload open file from disk

### ISSUE THREAD

**Issue by burak-aksoy** [notepad-plus-plus/notepad-plus-plus#1867]
We use notepad++ to monitor log files. It is possible to reload file using file menu. It would be perfect if it is possible to reload the file using a keyboard shortcut or a button on button bar.

**Comment by xylographe** [comment]
Settings > Shortcut Mapper > Main menu > Reload from Disk ?

**Comment by TroudhuK** [comment]
You also have the ReloadButton plugin.

**Comment by dail8859** [comment]
Closing issue since:

- Monitoring of log files is available
- A shortcut can be easily assigned through the Shortcut Mapper
- ReloadButton plugin is available
