### ISSUE TITLE
Tab Switching Menu Incompatible With Ultra High Resolution Monitors

### ISSUE THREAD

**Issue by justinkterry** [notepad-plus-plus/notepad-plus-plus#1868]
I have an ultra high resolution monitor, which are starting to be REALLY popular (most macs have them now, though I use a PC). When I use the keyboard shortcut to bring up the tab-switching menu (for me it's ctrl+tab, I can't remember if that's default or not though), the menu is too small to really read. This is a common problem for little features of programs to have, because with ultra high resolution monitors you have to code the size of all windows and text relative to the screen size instead of in pure pixel size, because it otherwise will appear too small. You also have to use vector images, because the blown up rasterized graphics will look blurry and distorted. Please fix the tab menu so that I can use it on my laptop, because it's very helpful. Thank you. I'm going to attatch pictures so that you can see that it's too small to use on ultra high resolution monitors, and the exact menu in question Sorry they aren't print screens, but the button wouldn't work when I was holding down the keys to make the menu appear.  If you have any important questions, please contact me at inferno596 at gmail, because I don't regularly use github.
![np bug 1](https://cloud.githubusercontent.com/assets/19422700/15348541/b593df0c-1c99-11e6-8342-7ec5840b145c.jpg)
![np bug 2](https://cloud.githubusercontent.com/assets/19422700/15348542/b5956818-1c99-11e6-95eb-aad3b8a92c4d.jpg)

Thank you.

**Comment by inferno596** [comment]
Also, yes I'm using display scaling in windows 10.

**Comment by MetaChuh** [comment]
please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins if you update from version 7.5.9 or below.
if your issue still persists, and it is still of relevance to you, please feel free to file a new issue as easy to understand and reproducible as possible.

thank you for your support and best regards.

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
(no extra account is needed, just use your github account to sign in)
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)
