### ISSUE TITLE
CSHTML file as normal text file?

### ISSUE THREAD

**Issue by yzobairi** [notepad-plus-plus/notepad-plus-plus#1869]
Hello,

When I open a CSHTML file with Notepad++ it's opened as a normal text file. I think this kind of files must have its own language type or at least it should be opened as HTML file.

Thanks

**Comment by linquize** [comment]
`.cshtml`: ASP.NET MVC Razor syntax

**Comment by yzobairi** [comment]
>  linquize commented 20 minutes ago

> .cshtml: ASP.NET MVC Razor syntax

I don't understand the goal of your comment.

**Comment by dail8859** [comment]
His goal was probably to state what a CSHTML file is since I'm guessing most (including myself) have no idea what it is.

You can register that extension to open with HTML by using `Settings > Style Configurator`, under Language select HTML, and add `cshtml` in the User ext box.

**Comment by yzobairi** [comment]
Thanks a lot !!!

**Comment by arc95** [comment]
It still would be nice to have a style for `cshtml` files, as they can contain both HTML and server-side code.
