### ISSUE TITLE
Bug: Editing the document after searching by 'Find All in Current Document' and Double clicking on search result point to (Highlight) wrong word.

### ISSUE THREAD

**Issue by sharif-ahmad** [notepad-plus-plus/notepad-plus-plus#1872]
Steps to reproduce: 
1. Open a document.
2. Press Ctrl + F to open 'Find Dialog'.
3. Enter a word (that is present in the document) in 'Find What: ' edit box.
4. Click 'Find All in Current Document'.
5. Now Edit (add or remove some text) the document. _Note: you should modify prior to the found text._
6. Double click on one of the search result.

Observe that wrong word is highlighted in the document. Image is attached for clarity.
![image](https://cloud.githubusercontent.com/assets/2750010/15422213/326924b4-1e99-11e6-91af-69af872525e5.png)

**Use case:** 
This is very useful when user needs to search and edit the document in places where it matches the search pattern. It is not very practical to search again after each editing.

**Comment by hackwrench** [comment]
I've noticed this bug too and figured the fix would take rather long time
and effort, but it didn't bother me enough to say anything.

**Comment by MetaChuh** [comment]
please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins if you update from version 7.5.9 or below.
if your issue still persists, and it is still of relevance to you, please feel free to file a new issue as easy to understand and reproducible as possible.

thank you for your support and best regards.

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
(no extra account is needed, just use your github account to sign in)
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)

**Comment by sasumner** [comment]
Workaround:  Edit from bottom up.  Earlier search result positions will not move.  Otherwise...a rather difficult and long-standing problem to solve.
