### ISSUE TITLE
Make windows installer translateable

### ISSUE THREAD

**Issue by scootergrisen** [notepad-plus-plus/notepad-plus-plus#1873]
I would like everything in the Windows installer to be translateable.
As it is right now its a mixed experience to install Notepad++.
Most of the text in the installed is translated to my language but for example the list where you select what to install is in english like:
Context Menu Entry
Auto-completion Files
Plugins
...

**Comment by jtrent238** [comment]
So make it translate plugins?

**Comment by scootergrisen** [comment]
Make it possible to translate the string "plugins" yes.

**Comment by donho** [comment]
It needs a lot of coding effort to make all items translatable in installer, therefore it'll not be done.
