### ISSUE TITLE
Opening a blank file should use same encoding as for a new document

### ISSUE THREAD

**Issue by vlakoff** [notepad-plus-plus/notepad-plus-plus#1874]
Use case: I often create a new file by right-click in Windows Explorer, then open this file with Notepad++.
- When creating a new file in Notepad++, it uses the `New Document > Encoding` preference (default UTF-8 w/o BOM).
- Furthermore, if I open a file containing only ANSI characters, it uses UTF-8 as well.
- BUT, if I open a blank file, it doesn't use UTF-8, but ANSI...

This is inconsistent and definitely has had caused me some troubleshooting headaches!

**Comment by jtrent238** [comment]
So much problem. :pensive:

**Comment by vlakoff** [comment]
@jtrent238, I'm unsure, is it irony? Seriously, this charset thing already has caused me many troubles…

**Comment by jtrent238** [comment]
@vlakoff Does it do it on another computer? :question: 

> Don't have another computer Try [Virtual Box](http://bit.ly/OVMVB)!

**Comment by vlakoff** [comment]
I encounter the same behaviour using a fresh settings profile.

**Comment by jtrent238** [comment]
You got some screenshots?

**Comment by molhanec** [comment]
I run to this also. Notepad++ is my favourite text editor and this is for me quite annoying because I rarely create new files directly in it. @vlakoff  thanks for reporting. (I don't know if jtrent238 is trying to be funny, but he is clearly not).

**Comment by mzso** [comment]
[**@jtrent238**](https://github.com/jtrent238) commented on [2016. máj. 21. 22:07 CEST](https://github.com/notepad-plus-plus/notepad-plus-plus/issues/1874#issuecomment-220797782 "2016-05-21T20:07:08Z - Replied by Github Reply Comments"):
> You got some screenshots?

Why are you spamming? Try it yourself, and you'll see he's right.

I also got unpleasantly surprised by this a couple times...

**Comment by mzso** [comment]
So many new features in v7. Yet no capacity to fix this small, but nasty bug.

**Comment by jtrent238** [comment]
### **It don't do it for me.**

### **I haven't had an issue and I have not updated it.**


![](http://puu.sh/rkta7/e919516630.png)

**Comment by mzso** [comment]
[**@jtrent238**](https://github.com/jtrent238) commented on [2016. szept. 23. 00:10 CEST](https://github.com/notepad-plus-plus/notepad-plus-plus/issues/1874#issuecomment-249043006 "2016-09-22T22:10:34Z - Replied by Github Reply Comments"):
> ### **It don't do it for me.**
> 
> ### **I haven't had an issue and I have not updated it.**
> 
> [![](https://camo.githubusercontent.com/8f7806aef1e10d629e4c6fb31a38e39469d18657/687474703a2f2f7075752e73682f726b7461372f653931393531363633302e706e67)](https://camo.githubusercontent.com/8f7806aef1e10d629e4c6fb31a38e39469d18657/687474703a2f2f7075752e73682f726b7461372f653931393531363633302e706e67)

You don't understand the issue... Your screenshot only proves that. You don't even show a screenshot of the encoding menu, but the configuration menu which is meaningless...

Right click (in explorer) > new > Notepad++ Document > double click > check encoding.

**Comment by jtrent238** [comment]
I don't have New Notepad ++ Document

![](http://puu.sh/rlAi6/2fb715f319.png)

**Comment by vlakoff** [comment]
"New > Text Document". You get a 0-bytes empty "New Text Document.txt" file. Then you open this file with Notepad++.

Then please someone delete all this spam.

**Comment by mzso** [comment]
[**@jtrent238**](https://github.com/jtrent238) commented on [2016. szept. 24. 00:29 CEST](https://github.com/notepad-plus-plus/notepad-plus-plus/issues/1874#issuecomment-249317364 "2016-09-23T22:29:15Z - Replied by Github Reply Comments"):
> I don't have New Notepad ++ Document
> 
>https://camo.githubusercontent.com/57cfcc4facccd4d61defe0de50cdb1858e077d56/687474703a2f2f7075752e73682f726c4169362f326662373135663331392e706e67

You seriously make me miss github having a double-facepalm emoticon/reaction...
Anyway. It's been acnowledged and accepted now. So no need to keep going on about this now.
Maybe someday, you'll gain the capability to understand what the issue was and why it sucked.

**Comment by davidcie** [comment]
Please fix, like @mzso I almost exclusively create text files (and lots of them) using Total Commander's Shift+F4 combo. Coming from the excellent but abandoned Notepad2 was surprised that N++ does not behave the same (imho reasonable) way.

**Comment by vlakoff** [comment]
Possible fix in #2997.
