### ISSUE TITLE
Searching for $ in text

### ISSUE THREAD

**Issue by jamesfconroy** [notepad-plus-plus/notepad-plus-plus#1875]
Hi,

I have a text file where I want to find instances of the $ symbol. However, when I do the standard Ctrl+F, the $ symbol is not found, even though I can see it in the text with my own eyes.

I do not know if this also happens with other characters.

Thanks,

James

**Comment by army007** [comment]
This works fine for me. I can find $ symbol. I am using Notepad++ v6.9.1. Please mention your Notepad++ version and type of document you are trying to find in. If possible upload the document so that it can be reproduced.

**Comment by jtrent238** [comment]
If you are not using the latest version that may be the problem.

**Comment by vlakoff** [comment]
Maybe you have the "regular expression" search mode selected?
It also happens to me sometimes…
