### ISSUE TITLE
pushing artifact in Appveyor:

### ISSUE THREAD

**Issue by cmeriaux** [notepad-plus-plus/notepad-plus-plus#1877]
Fix a path problem while pushing artifact in Appveyor:
Artifacts in yaml config file (appveyor.yml) is useless.

Rename the binary into notepad++_debug.exe

log of my compil without error :+1: 
https://ci.appveyor.com/project/cmeriaux/notepad-plus-plus/build/1.0.22

**Comment by dail8859** [comment]
Closed by #2079
