### ISSUE TITLE
bug: Remapping an action of another shortcut

### ISSUE THREAD

**Issue by kbilsted** [notepad-plus-plus/notepad-plus-plus#1880]
when changing the hotkey for "incremental search" to ctrl+i I get not errors despite it conflicts with the split line action. Also when pressing ctrl+i no incremental search is performed.

  * validate that when chossing a hotkey no other actions has that hotkey assigned already
  * in case of a collision explain the collision and make the user choose to overwrite the setting or leave it at the existing action.

**Comment by dail8859** [comment]
Closed by 1abac157993685c4f6345443f6256403526858ad

**Comment by kbilsted** [comment]
How will this work when plugins define a shortcut that already exist? eg https://github.com/kbilsted/NppPluginCutNCopyLine/blob/master/Main.cs line 16

**Comment by dail8859** [comment]
No clue. You'll have to take a look at PR #2029 or ask there. I would assume that there is no functionality change, just GUI-based changes, but can't say for sure.

**Comment by A-R-C-A** [comment]
@kbilsted
You can mask shortcuts, the very first occurrence will perform the action. Entries listed before yours take precedence, entries listed after can be masked by you. The precedence order is as listed in the Shortcut Mapper (tabs: from left to right; entries: from top to bottom).
