### ISSUE TITLE
'Find all in current document' button does not have a shortcut key defined in the 'Find' dialog

### ISSUE THREAD

**Issue by joshburnett** [notepad-plus-plus/notepad-plus-plus#1885]
In the 'Find' dialog, the 'Find All in Current Document' does not have a shortcut associated with it (there are no characters underlined). Compare this to the 'Find All in All Opened Documents' button directly above it, as well as all of the other GUI controls in the dialog:

![find dialog](https://cloud.githubusercontent.com/assets/12973799/15474526/2adb505a-20d3-11e6-85e7-5de199ebd820.png)

**Comment by MetaChuh** [comment]
please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins if you update from version 7.5.9 or below.
if your issue still persists, and it is still of relevance, please feel free to file a new issue as easy to understand and reproducible as possible.

thank you for your help and best regards.

**Comment by assad-ebrahim-uk** [comment]
Or you can change it yourself: search in Npp\nativeLang.xml for 
```
<Item id="1641" name="Find All in Current Document"/>
```
Change it to:
```
<Item id="1641" name="Find &amp;All in Current Document"/>
```
Save > Close NPP > Launch NPP.

You will now see a Windows Accelerator on the button (Alt+A).  Voila.

--
_moderator edited reply to include code tags, so it's readable and meaningful_

**Comment by pryrt** [comment]
@assad-ebrahim-uk ,

> search in Npp\nativeLang.xml for [...]

I am assuming that you are using a shorthand.  But when people are looking for answers to questions, unless you have given more context, they might not understand that.  

_Assuming_ that the person has already chosen a localization other than English (which the screenshot above does _not_ indicate), then `nativeLang.xml` is either in `%AppData%\Notepad++\nativeLang.xml` (if you have a normal installation), or in the appropriate portable directory or directory set by -settingsDir or cloud directory.  Users should not go looking for a directory called "Npp" when trying to follow your advice.  But `nativeLang.xml` will **not** exist if they have set their localization to English (which is what the screenshot above _does_ imply) -- this would have likely confused the author of the issue, had you answered them thusly a decade ago when they asked the question, and would likely confuse any user who searched this Issue out, but like the original, had not changed their localization.

Further, it is not best to edit `nativeLang.xml` directly, as that will be overwritten the next time they choose a localization (even the _same_ localization) from the preferences.

Instead, users trying to follow the spirit of your advice should:
1. Open `C:\Program Files\Notepad++\themes\<localization_name>.xml` (or wherever your Notepad++ is installed) 
    - If you want to customize English text, like the screenshot in the original request implies, you need to edit `english_customizable.xml` instead, as it is highly recommended to not customize the default `english.xml` (as that file needs to stay as the "gold standard")
2. Make the edit that @assad-ebrahim-uk recommend, then save the file.  They don't need to exit Notepad++ at this point
3. Go to **Settings > Preferences > General**, and in the **Localization** pulldown, select the desired localization:
    - Again, if it's English, actually choose `English (customizable)`
    - If the localization you want is already selected, you still need to pop open the pulldown, and reselect the same file.
4. Notepad++ will copy the localization file to `nativeLang.xml`, and will immediately apply the updated text to the Notepad++ window and dialogs
