### ISSUE TITLE
Ability to hide scrollbars?

### ISSUE THREAD

**Issue by vexe** [notepad-plus-plus/notepad-plus-plus#1886]
Greetings,

In most the other editors I used, they all gave me options of hiding scrollbars and giving me a true full-screen editing experience without any extra fat on the sides.

It would be great if you exposed that option.

Thanks.

**Comment by MetaChuh** [comment]
please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins if you update from version 7.5.9 or below.
if your issue still persists, and it is still of relevance, please feel free to file a new issue as easy to understand and reproducible as possible.

thank you for your help and best regards.
