### ISSUE TITLE
syntax highlighting 

### ISSUE THREAD

**Issue by wwbenayed** [notepad-plus-plus/notepad-plus-plus#1887]
Notepad++ crashes when very long xml file are loaded for new syntax highlighting.
Attached example file for PRACTICE (change the extension to xml to try)

[practice.txt](https://github.com/notepad-plus-plus/notepad-plus-plus/files/278989/practice.txt)

**Comment by dail8859** [comment]
Opens fine for me. There is a bit of a performance hit since it has some very long lines (Notepad++ can't do anything about it because it is a Scintilla limitation). Make sure you have the latest N++ version and try disabling your plugins in case it is one of those causing the crash.

**Comment by dail8859** [comment]
Just realized you might have meant using is a UDL (as opposed to actually editing it), either way it still works fine for me.

**Comment by wwbenayed** [comment]
Yes I mean UDL not editing.

**Comment by jvdev15** [comment]
Notepad++ will crash after you open an with an extension of this language (*.cmm, *.men, *.men) or manually selecting the language from the menu. Verified with Notepad++ v6.9.1

**Comment by chcg** [comment]
Callstack:

 	notepad++.exe!__report_securityfailure(unsigned long FailureCode) Zeile 409	C
 	notepad++.exe!__report_rangecheckfailure() Zeile 498	C
>	notepad++.exe!ScintillaEditView::setUserLexer(const wchar_t * userLangName) Zeile 765	C++
 	[Externer Code]	
 	[Unten angegebene Rahmen sind möglicherweise nicht korrekt und/oder fehlen]	

at:

		temp[index++] = 0;

, but index is > array size of:

char temp[max_char];

with

const int max_char = 1024*30;

, but that restriction seems to be unchecked on UDL import.
