### ISSUE TITLE
Feature Request: regex SELECT text

### ISSUE THREAD

**Issue by sfgap** [notepad-plus-plus/notepad-plus-plus#1888]
Currently easy to use regex to MARK text (eg menu item Search > Mark...).

Need same for regex SELECT text (same functionality as mark but the results should be selected instead of marked).

Ideally available as menu item Search > Select..., or as a checkbox "select marked text" in Search > Mark...

Googled solutions are cumbersome and method not always consistant across different files, eg:

[https://notepad-plus-plus.org/community/topic/10839/copy-regular-expression-search-results-to-clipboard](url)

[http://stackoverflow.com/questions/2298962/how-to-copy-marked-text-in-notepad](url)

and many others.

**Comment by Mooni123** [comment]
+1

This would be great.
I also missing this function

**Comment by MetaChuh** [comment]
please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins if you update from version 7.5.9 or below.
if your issue still persists, and it is still of relevance, please feel free to file a new issue as easy to understand and reproducible as possible.

thank you for your help and best regards.

**Comment by sasumner** [comment]
Still going to be there in 7.6.6.  It's a valid thing to want to be able to do...
