### ISSUE TITLE
"File is too big to be opened by Notepad++" behavior is inconsistent between open and reload file

### ISSUE THREAD

**Issue by Mertsch** [notepad-plus-plus/notepad-plus-plus#1890]
I am able to open a ~250MB log file with Notepad++ and everything works fine (just slower).

When the log file changes and N++ askes me if I want to reload the file, I get the "file is too big" error and the file is not reloaded.

But the file is not too big for N++, as I can close the tab and just open the file again and it works.

**Comment by MetaChuh** [comment]
please update your notepad++ to the latest 64 bit version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins if you update from version 7.5.9 or below.
if your issue still persists, and it is still of relevance, please feel free to file a new issue as easy to understand and reproducible as possible.

thank you for your help and best regards.

**Comment by MetaChuh** [comment]
please update your notepad++ to the latest 64 bit version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins if you update from version 7.5.9 or below.
if your issue still persists, and it is still of relevance, please feel free to file a new issue as easy to understand and reproducible as possible.

thank you for your help and best regards.
