### ISSUE TITLE
find and replace string will stop at line 69906 on a file over 300k lines

### ISSUE THREAD

**Issue by myironman** [notepad-plus-plus/notepad-plus-plus#1891]
When do a find and replace on a very big file over 300k lines (500mb ++), even though the find and replace box shown up the total lines being replaced are 300k++ lines, but the actual replace action will stop at line 69906 and left the current line subtracted by the find string and NOT replace the new string. Line start from 69907 was not replaced even the find and replace box shown replaced.

**Comment by dail8859** [comment]
Try disabling all the plugins and turning off periodic backups to see if that helps at all.

**Comment by myironman** [comment]
No improvement after i uninstalled all plugins and disabled the periodic backups.
Interestingly, you can't do additional find and replace anymore after the first find and replace action and stop at the amount of 69906 lines.
To workaround that, i have to close the application and reopen it to do the "next" find and replace and repeat the whole process until all lines in the file get replaced. :)

**Comment by dail8859** [comment]
Since its really not feasible to send a 500MB file, can you possibly show a show snippet of the file and what you are using to search and replace?

**Comment by myironman** [comment]
I'm sorry i don't have a show capture tool installed but I hereby upload 2 images with some indications shows how the error occurs.
My latest found out that this is an intermittent issue. Not every text replacement has the said problem where other text replacement are working correctly.
![image 676](https://cloud.githubusercontent.com/assets/19581488/15646647/5b9c24d0-2691-11e6-9e53-47333339d7da.png)
![image 677](https://cloud.githubusercontent.com/assets/19581488/15646690/a4d4e15a-2691-11e6-8bcd-c1787d8635e6.png)
sorry for the "censorship" on 2nd image. 
Hope this help.

**Comment by dail8859** [comment]
Thanks. I'll see what I can do to recreate it.

**Comment by MetaChuh** [comment]
please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins if you update from version 7.5.9 or below.
if your issue still persists, and it is still of relevance, please feel free to file a new issue as easy to understand and reproducible as possible.

thank you for your help and best regards.
