### ISSUE TITLE
Close Files/Tabs that ends with <Extension>

### ISSUE THREAD

**Issue by loesler** [notepad-plus-plus/notepad-plus-plus#1893]
Hi,

I often load the full list of files of a folder for "multi-modifications". Sometimes, the folder (or sub-folders) contains ASCII files as well as binary files (e.g. images, class etc.). To avoid an undesired modification of the binary files, it would be nice, if I can close tabs by "Close Files/Tabs that ends with..." or even more general "Close Files/Tabs that matches "RegExp"".

/Micha

**Comment by MetaChuh** [comment]
please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins if you update from version 7.5.9 or below.
if your issue still persists, and it is still of relevance, please feel free to file a new issue as easy to understand and reproducible as possible.

thank you for your help and best regards.
