### ISSUE TITLE
Implement a command palette 

### ISSUE THREAD

**Issue by 5j9** [notepad-plus-plus/notepad-plus-plus#1894]
As you may already know sublime text has a built-in feature called "[command palette](http://docs.sublimetext.info/en/latest/extensibility/command_palette.html)".

Basically, what it does is a fuzzy search through a list of available commands and running them after selection. So if you don't know the keyboard shortcut to run a command, or maybe it does not have a shortcut, you can use the command palette to access it quickly. [This video](https://www.youtube.com/watch?v=QDajzykRdn0) by Jeffrey Way describes it perfectly.

I would very much like to see a similar feature on notepad++.

Thanks!

**Comment by cmeriaux** [comment]
You may try the plugin NppMenuSearch. This is exactly what you need
