### ISSUE TITLE
Jumplist support

### ISSUE THREAD

**Issue by MgSam** [notepad-plus-plus/notepad-plus-plus#1895]
NotePad++ doesn't take advantage of the jumplist feature in Windows. 

This is a feature request to add support for adding MRU documents to the NotePad++ jumplist.

**Comment by KOLANICH** [comment]
There is a plugin for that, but it is broken: it crashes npp on every exit (at least on the machine I work on).

**Comment by MetaChuh** [comment]
please use the nppjumplist plugin for extended jumplist functionality

![Imgur](https://i.imgur.com/oKCf0ua.png)

**Comment by KOLANICH** [comment]
@MetaChuh, does it cause a crash when npp exits? If it doesn't, could you force DEP for all the apps and retry?

**Comment by MetaChuh** [comment]
@KOLANICH 

no crashes with or without dep (required reboot done after every change).

no difference in behaviour with or without dep, no crash on exit, regardless of starting notepad++ from a jumplist entry, pinned entry, or from a desktop icon.

tested on 7.6.6 x86 installed and x64 portable, nppjumplist 1.2.2.0 installed via plugins admin.
windows 10 pro x64, 2880x1800 at 200%.

<img width="967" alt="Bildschirmfoto 2019-05-05 um 12 15 55" src="https://user-images.githubusercontent.com/45773305/57192358-e6553280-6f2f-11e9-9b87-63a76cff3f2e.png">

<kbd>Notepad++ v7.6.6   (32-bit)
Build time : Apr  3 2019 - 23:49:50
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10 (64-bit)
Plugins : ComparePlugin.dll HexEditor.dll mimeTools.dll NppConverter.dll NppExport.dll NppJumpList.dll</kbd>

<kbd>Notepad++ v7.6.6   (64-bit)
Build time : Apr  3 2019 - 23:52:32
Path : C:\Users\User\Desktop\npp.7.6.6.bin.x64\notepad++.exe
Admin mode : OFF
Local Conf mode : ON
OS : Windows 10 (64-bit)
Plugins : mimeTools.dll NppConverter.dll NppJumpList.dll</kbd>

best regards.

**Comment by KOLANICH** [comment]
@MetaChuh, thank you for the info!
