### ISSUE TITLE
Could you bring Notepad++ to the Windows Store?

### ISSUE THREAD

**Issue by raaomoka** [notepad-plus-plus/notepad-plus-plus#1896]
Windows 10 is rapidly growing (currently at 15.34% world-wide at the time of this post), and the Windows Store offers the long-wanted methodology for developers to make their Win 32 application seamlessly update. Could you consider bring Notepad++ to the store as it currently is, then gradually turn it into a UWP app?

**Comment by hackwrench** [comment]
While I wouldn't mind Notepad++ being on the Windows Store, your request reads like ad copy, and saying long-wanted sounds like either it's from a person whose first language is not English who meant the word long-awaited, or someone using a neologism. Notepad updates seamlessly enough for me and so have a lot of programs. Maybe Notepad++ could come to Steam too, for that matter.

**Comment by raaomoka** [comment]
Lol, why so nitpicky? You having a bad day or did your GF just ditch you? Calm your tits son...

BTW, that's a miserably inapt analogy comparing bringing a productivity application to a games store vs. an all-purpose store...

**Comment by hackwrench** [comment]
I'm American, so I have difficulty remembering rhat there are other nations that use some variation of the English languague.
But what rock have you crawled out from under?

Steam has been a general software store for quite some time now and they've even added videos for sale or rent.

**Comment by raaomoka** [comment]
It's still mostly known for games/entertainment, here on earth at least, and it's barely installed on anyone's computer unlike the Windows store, considering Windows 10 x64-Bit is already the most popular OS utilizing it:

http://www.windowscentral.com/windows-10-64-bit-now-most-used-os-steam-pc-gamers

Whereas Windows 10 is still less than half of Windows 7's world market share:

http://netmarketshare.com/

Again, inapt analogy, but nice try in making a point though...

**Comment by hackwrench** [comment]
Installation accompanying an OS hardly indicates usage patterns. I do things with Steam all the time, and would look there first for something and before that an internet search.

What you say about the preinstalled state of Windows Store makes about as much sense as saying that since Notepad comes preinstalled, why bother with Notepad++.

Oh, and sometimes I just like to grouse.

**Comment by hackwrench** [comment]
Oh and you just confused a plurality with a majority.
What is this "earth" you mention? If it's not in 'Murica, I'm not interested.

**Comment by raaomoka** [comment]
Ok. now I see how Drumpf is getting his votes...

**Comment by hackwrench** [comment]
I don't vote for reasons I don't care to mention and I can't speak for all of those supportive of Trump, but as I see it, Trump was behaving in a way that showed he understood how much of a farce the debates actually were. Cruz tried to ape Trump, but he only indicated he didn't understand why Trump was behaving the way he was in the first place.
Now when I made that 'Murica statement, I was juxtapositioning stereotypical American behavior with your statement that expressed the notion that the whole Earth was in agreement with you.
Also one way Trump could "make Mexico pay for the wall", is to charge all foreigners a border crossing fee, which is not that hard of a scenario to figure out.

**Comment by cmeriaux** [comment]
Don't fight but code and PR !

**Comment by hackwrench** [comment]
What We've learned:
Steam isn't just for games anymore.
It might not be a bad idea to put Notepad++ on some web stores.
Both treating America as if it's the only place good can be found and taking it for granted that the whole Earth is on your side is bad.
Just because something is bundled with an OS doesn't mean it gets used very much.
Pluralities are not majorities.

**Comment by michel-bosseaux** [comment]
Notepad++ on Windows Store will be necessary for Windows 10S users (what a mistake lol). This version of the system installs only the software from the store ...

**Comment by donho** [comment]
@hackwrench 
> What We've learned:
Steam isn't just for games anymore.
It might not be a bad idea to put Notepad++ on some web stores.
Both treating America as if it's the only place good can be found and taking it for granted that the whole Earth is on your side is bad.

Mind to develop it?

**Comment by donho** [comment]
Notepad++ doesn't judge, and is free for everyone - even for Trump's supporters and assholes.

**Comment by donho** [comment]
FYI: This task was in progress but it has been blocked, here is the further information:
https://notepad-plus-plus.org/community/topic/14734/notepad-uwp-package-in-windows-store-almost-there

Any idea is welcome.

**Comment by raaomoka** [comment]
Wow, thank you very much for your efforts @donho! I'll send a tweet to some microsoft reps and see if they actually care for such extraordinary software getting ino the Microsoft Store. Sorry, I'm not experienced enough to fully understand this error you're getting.

**Comment by gjsman** [comment]
I have done some work... 😃

**Comment by gjsman** [comment]
https://github.com/notepad-plus-plus/notepad-plus-plus/issues/3883

**Comment by MetaChuh** [comment]
as the available [unofficial notepad++ release](https://github.com/NightRi-se/notepad-plus-plus) at the microsoft store has unresolved issues, which do not happen at the regular installed versions, we will currently not pursue dealing with the same problems.

maybe some day in the future, but not now and not on demand.

thank you for your help and best regards.
