### ISSUE TITLE
Alt+Shift Column Selection counts wrapped Lines as Individual Lines

### ISSUE THREAD

**Issue by Doryforos** [notepad-plus-plus/notepad-plus-plus#1897]
v6.9.2 on WinXP-SP3+Updates

When trying to select columns (i.e. a block) of wrapped lines (i.e. with word wrap turned on), using the Alt+Shift keyboard shortcut, the down (or up) cursor arrow needs to be pressed as many times as the number of "soft" lines that physical lines are wrapped in (or held down), until the intended selection end is reached.

**Comment by MetaChuh** [comment]
please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins if you update from version 7.5.9 or below.
if your issue still persists, and it is still of relevance, please feel free to file a new issue as easy to understand and reproducible as possible.

thank you for your help and best regards.

**Comment by sasumner** [comment]
@Doryforos I don't understand what you are suggesting.  Column block select seems to work as I would expect with wrapped lines.  Can you explain further your ideas?
