### ISSUE TITLE
No Python code folding past level 1

### ISSUE THREAD

**Issue by HactarCE** [notepad-plus-plus/notepad-plus-plus#1898]
Alt + 1 works fine to collapse the first level of code, but Alt + 2-9 don't work (not do the menus). Everything is fine when using syntax highlighting for other languages. Manually collapsing the code (by hitting the [-] button by the line numbers) works fine, however.

**Comment by HactarCE** [comment]
So forgive me if I'm wrong, but a quick-and-dirty solution would be to divide the "FoldLevel" by 4?

**Comment by dail8859** [comment]
I looked deeper into the code and it seems to be based on indentation so it's not as easy as just dividing. Plus I'd hate to have to add a special case just for python. I submitted a bug report to Scintilla to see if the odd fold level is intended or not.

**Comment by cmeriaux** [comment]
Hello guys,
I also noticed the problem sometimes ago.
I did some test and my conclusions are : 
scintilla python lexers 
- doesn't support indentation with tabs.
- every line indented with 1 space will be attached on fold level 1
- every line indented with 2 spaces will be attached on fold level 2
- every line indented with n spaces will be attached on fold level n

So if your python code uses a 4 spaces tabulation, the first level level of indentation will be associated with the fold level 5.

@HactarCE your quick-and-dirty solution wouldn't be divide the "FoldLevel" by "tab size"
 ....

**Comment by dail8859** [comment]
> doesn't support indentation with tabs.

Tabs have always worked fine for me.

> every line indented with n spaces will be attached on fold level n

Yes this is the conclusion I came to as well. Also, indenting with a tab sets it to a fold level of 8 no matter what the width of the tab character is set to.

Here is the Scintilla bug [report](https://sourceforge.net/p/scintilla/bugs/1834/).

**Comment by dail8859** [comment]
The Scintilla author reports the Python lexer is working as intended. To properly fold the `n`th level of indentation is not straight forward. It is possible this kind of thing happens to other lexers.

**Comment by pembo13** [comment]
Any updates on this issue?

**Comment by victorclaessen** [comment]
I would really like this to work with tabs as well.

**Comment by MaxCorman** [comment]
I would seriously like this feature to be resolved since i use Notepad++ for normal text categorization as the Python, Nimrod, and Matlab languages are very convenient since they don't require putting characters everywhere for folding.

Is there some kind of workaround to this?

**Comment by MaxCorman** [comment]
@zufuliu What is all this code that you just submitted? And what is the code in the link? Are they scripts that can be used for a workaround to get proper indentation with tabs in Python in Notepad++ or are they actual re-coding of Scintilla. I am confused. Sorry for being a beginner programmer and not  understanding what is going on.

**Comment by zufuliu** [comment]
The code here and linked is what Notepad2 used to toggle fold n-level for Python, which works fine.

The level stack is used to compute how many levels current line is, regardless of what indentation is used.
That is: the first line that starts a fold has level 1, it's first child line that starts a fold has level 2, etc.
See the following code, each line has different indentation amount, apparently has only three levels.

```python
       def func():                       # line 1, level 1
          if True:                         # line 2, level 2
                   if True:                # line 3, level 3
                       # stmt1          # line 4
          if False:                        # line 5, level 2
                         if False:         # line 6, level 3
                             # stmt2    # line 7
```

The `EditFoldStack_Push` works by pop off all brother levels and their child levels. and set the stack top to level for current line. if a level is larger than the top level (no pop off), it must a child of top level. so the level count in the stack is the 1-based level number for current line.

**Comment by MaxCorman** [comment]
Ok got it. Thanks for the clarification @zufuliu. I thought Notepad2 was another name for Notepad++ since the '2' could denote the '++'. I did not realize they were two different programs.

So if its possible to get proper folding of tab indentations on all levels for Python or similar languages in Notepad++ then who would do it?

**Comment by sasumner** [comment]
>who would do it?

Anyone that wants to can tackle it and submit it for inclusion in Notepad++.  Whether or not it will be picked up and integrated is another matter.  Some submissions get adopted, others don't.

**Comment by MaxCorman** [comment]
So i guess the only thing i can do is just hope and wait. It could be a while if ever.

**Comment by sasumner** [comment]
Correct.  On the upside, if the Notepad++ developer picks it up and works on it, it is almost 100% to make it into a future release. :)

**Comment by zufuliu** [comment]
I made PR #5131.

**Comment by MaxCorman** [comment]
Wow that was fast @zufuliu. Amazing stuff! Thank you.

So what happens now? Do i just wait for the developer(s) to see if they pick it up and implement it in a future release? Would they notify us if they are going to pick it up? And how long would it take to be implemented if it is implemented?

**Comment by MaxCorman** [comment]
I'll take the binary from you @zufuliu.

But what exactly is the binary? Is it the same executable file found on the Notepad++ website or something else?

**Comment by zufuliu** [comment]
@MaxCorman you can install [Visual Studio Community](https://visualstudio.microsoft.com/vs/community/), clone the code, open `PowerEditor\visual.net\notepadPlus.vcxproj` with Notepad++, change `PlatformToolset` from `v140_xp` to `v141`, then open notepadPlus.vcxproj with Visual Studio to build Notepad++.

**Comment by MaxCorman** [comment]
Ok thanks @zufuliu. I will follow your instructions to see if it works. But i do have one question before proceeding. Where do i paste the code when i open notepadPlus.vcxproj?

**Comment by zufuliu** [comment]
The following binary is build by Visual Studio 2017 XP target supporting tool (v141_xp), for testing only (if it's not legal to attach binary here please delete them).
Backup you Notepad++ 7.6 folder, then replace files from zip:

32-bit  Unicode: [bin.zip](https://github.com/notepad-plus-plus/notepad-plus-plus/files/2674060/bin.zip)
64-bit Unicode: [bin64.zip](https://github.com/notepad-plus-plus/notepad-plus-plus/files/2674061/bin64.zip)

**Comment by MaxCorman** [comment]
Ok thanks a lot @zufuliu. I will also come here and let you know if it works out on my system just for confirmation.

**Comment by MaxCorman** [comment]
@zufuliu sorry to bother you again, but i am unable to unzip the files with WinRar. I get the message: Unknown method in bin\file names...

After the operation i only get an empty bin folder.

**Comment by MaxCorman** [comment]
Everything works like a charm @zufuliu. Thanks again for the coding. You are awesome.

**Comment by victorclaessen** [comment]
Works for me, and is totally awesome. Been hoping for this for years! Let's hope the developer incorporates this in the mainstream version soon.

FYI: I got one 'virus' hit on the 32-bit version (none on the 64) on [virustotal](https://www.virustotal.com/#/file/a8bd7d69c69f7957187ac46d503b0ec54877a31b1aba5695f244930b82c2b6f0/detection) but I'm willing to believe that is a false positive.

**Comment by MaxCorman** [comment]
I would like to mention that the proper folding works for all tab only indentation languages such as  Python, Matlab, Nimrod, Coffee Crisp, and Visual Basic.

**Comment by MaxCorman** [comment]
On a side note, if anyone out there is interested, to remove the horizontal lines when folding, you can download and use the LuaScript plugin and paste the following code into the startup script:
editor1.FoldFlags = 0

**Comment by victorclaessen** [comment]
@zufuliu If you have time, perhaps you could create a pull request from your repository to ask the developer to incorporate this fix into the mainstream version?

**Comment by zufuliu** [comment]
@victorclaessen  https://github.com/notepad-plus-plus/notepad-plus-plus/issues/1898#issuecomment-446489546

**Comment by victorclaessen** [comment]
> 
> 
> @victorclaessen [#1898 (comment)](https://github.com/notepad-plus-plus/notepad-plus-plus/issues/1898#issuecomment-446489546)

Great! Totally missed that (was searching open pull requests for keywords 'python' and 'folding', but not 'fold'). Hope it gets picked up soon.

**Comment by LordNyriox** [comment]
@MaxCorman:  If you want a precompiled binary for a change introduced by a Notepad++ PR, you can simply download the appropriate AppVeyor artifact, rename the file to `Notepad++.exe`, and replace your existing copy of Notepad++ with it. 

You should find the link under "All checks have passed", in the source PR. 

[<https://ci.appveyor.com/project/donho/notepad-plus-plus/builds/20982086>]

**Comment by MaxCorman** [comment]
@LordNyriox Thanks for the info and the link.
