### ISSUE TITLE
[ENHANCEMENT] Search Next/Previous dedicated buttons

### ISSUE THREAD

**Issue by gawkla** [notepad-plus-plus/notepad-plus-plus#1906]
I use very often the "Find" dialog. Currently to change search direction [Up / Down] Radio button is used. 
In my opinion it will be far more "productive" if there will be dedicated "Find next" and "Find previous" buttons. Like (in example) notepad2

**Comment by gawkla** [comment]
![notepad2](https://cloud.githubusercontent.com/assets/10233305/15650603/ff4426a4-2679-11e6-95ec-0ed503ffc91b.png)

**Comment by foreachthing** [comment]
Me, I'd rather have when at EOF (or end of find), loop back to first line of file - as notepad2 does.
I hate being stuck at the last find...

**Comment by MetaChuh** [comment]
please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins if you update from version 7.5.9 or below.
if your issue still persists, and it is still of relevance, please feel free to file a new issue as easy to understand and reproducible as possible.

thank you for your help and best regards.

**Comment by sasumner** [comment]
Hasn't this been around since like version 7.4.2?  Here's what it looks like in 7.6.6:

![image](https://user-images.githubusercontent.com/30118311/57074856-117f1e00-6cb3-11e9-8d26-1ea944166c90.png)
