### ISSUE TITLE
[ENHANCEMENT] "Find all in..." like classic GREP.

### ISSUE THREAD

**Issue by gawkla** [notepad-plus-plus/notepad-plus-plus#1908]
Hello Team.
Do anybody have idea how to provide simple visual-grep functionality for notepad++?
I using notepad++ to filter and view tons of logs. Very often I have to search file/folder for multiple patterns. This function is exactly provided by grep command. For grep I have to prepare input file with patterns to find. Each line - one pattern. Next I have to run grep on selected folder / file with pattern from previously prepared file. 
Some manual/batch work, but works great. I am thinking about integrate simple grep in notepad++. Way to enter multiple patterns (each line - one pattern) and execute search (in current document, in all opened documents, in folder...). Someone have any idea? Is there plugin for this, other ideas?

BTW, it would be great if "Find all in..." behaviour can be similar to grep. Currently, each pattern is search literally, and if pattern is found twice or more in same line, this line is visible twice or more in search results. Classic grep functionality is to show each line once. What do you think?

**Comment by dail8859** [comment]
There is a plugin called LineFilter2 that I use quite often for digging through large log files. It's not perfect and has room for improvement, but definitely something to take a look at.

**Comment by gawkla** [comment]
I know it. For me missing thing is multiple patterns search. Do you know if it is possible to search multiple patterns with this plugin?

**Comment by dail8859** [comment]
Like I said it has room for improvement. It doesn't do it as far as I know. You could always write one regular expression with all the patterns or'ed together.

**Comment by gawkla** [comment]
Thanks for this idea, I will try... :)

**Comment by cmeriaux** [comment]
What about using grep (from cygwin installation) through npp exec plugin

**Comment by gawkla** [comment]
Thanks for this idea, I will try... :) Looks promising :)

**Comment by gszo123** [comment]
Have you tried using AnalysePlugin?
It allows to define multiple search patterns, color the results, etc.

**Comment by gawkla** [comment]
I know this one. I'm using it. But pure grep is faster and simpler: only paste block of lines (patterns) to find and go.

**Comment by kasumiru** [comment]
https://superuser.com/questions/411071/grep-like-functionality-for-notepad

**Comment by donho** [comment]
I guess the link above has provided the solution.
