### ISSUE TITLE
Notepad++ hanging when reading large (32k and greater) files

### ISSUE THREAD

**Issue by MJSobol** [notepad-plus-plus/notepad-plus-plus#1910]
HI: I have noticed Notepad++ 6.9.0 frequently hangs when processing large files.
2 dump files attached for your investigation
Murray Sobol
murray.sobol@openlink.com

[notepad++.exe.1728.zip](https://github.com/notepad-plus-plus/notepad-plus-plus/files/291468/notepad.exe.1728.zip)

**Comment by MeiRct** [comment]
Can you please check with latest version 6.9.2? 
Or there's a reason you should stick to 6.9.0.

On my computer, with NP++ version 6.9.2, the file you attached inside the zip is opened flawlessly, without any delay.

The file opening can be affected from external paramters like low memory, high load on CPU, or a slow reading from the drive.

**Comment by MJSobol** [comment]
Hi:

                I tried with 6.9.2 – same behaviour.

                I suspect, as you suggest, that it may be “machine related” like low memory, high load on CPU, or a slow reading from the drive.

Are there any start-up parameters for Notepad++ that can alleviate this condition?

Thanks
Murray

**Comment by MeiRct** [comment]
What about the session? Are there any open tabs when you load the big file?
Also, perhaps you can disable or remove some plugins.

**Comment by informatorius** [comment]
Is it fixed with noteüad++ x64?

**Comment by atiq-cs** [comment]
reproduced with 7.5.7 my text is around 100 mb. It hangs notepad++ every time. Windows notepad opens ok

**Comment by Muhammad-Altabba** [comment]
I am facing the same problem with version 7.5.9.0

**Comment by be4ndr** [comment]
The same issue in NPP 7.6.6.
Looks lite the slowness\freezing causing by Word Wrap feature.
I tested in on a txt file 90Mb size.
With Word Wrap ON (View -> Word Wrap checked) going to then end taking about 10-15 sec (Ctrl+End) I have Core i7 processor and 16 GB of RAM.
When I unchecked it, the same procedure (Ctrl+End) took about 1-2 seconds.

**Comment by MetaChuh** [comment]
@MJSobol

we can not enhance the scintilla lexer speed.
things that make a huge speed difference are, to disable any spell checkers and disable word wrap on such files.

many thanks and best regards.

**Comment by alex1yaremchuk** [comment]
The same here, file 15MB 
1) Open file 15MB
2) Press Ctrl-End 
3) It hangs for tens of minutes (probably forever)

Notepad++ v7.8.2   (64-bit)
Build time : Dec  4 2019 - 01:39:49
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS Name : Windows 10 Enterprise 2016 LTSB (64-bit) 
OS Version : 1607
OS Build : 14393.3384
Plugins : mimeTools.dll NppConverter.dll NppExport.dll

**Comment by xylographe** [comment]
@alex1yaremchuk Did you turn off wrapping? What is the language (syntax) of the file?

**Comment by alex1yaremchuk** [comment]
> @alex1yaremchuk Did you turn off wrapping? What is the language (syntax) of the file?

You're right, it was a language issue (SQL). Setting N -> Normal Text completely solved this problem.

Thank you!

**Comment by x011** [comment]
temporary change file extension to `.txt` and it should work.

**Comment by judos** [comment]
So how about instead of hanging showing loading progress? Offerting the user to cancel the operation? Right now I have to choose between waiting (god knows how long) and killing notepad++ (loose all my changes in unsaved other tabs).
This issue is far from solved.
