### ISSUE TITLE
Copy & Paste confused when deleting line

### ISSUE THREAD

**Issue by wormuth** [notepad-plus-plus/notepad-plus-plus#1913]
Hi all,
I found a way to get the clipboard content "confused":

Given following text:
```
Line 1
Line 2
```

1. First select "Line 1" and press CTRL-C to copy "Line 1" to clipboard.
2. Then goto Line 2 and press CTRL-L to delete the line
3. Press CTRL-V to insert the clipboard contents.

Should insert "Line 1", but inserts "Line 2".

Using Notepad++ v6.9.2, Windows 7, no additional plugins, afaik.

Greetz,
Andree

**Comment by xylographe** [comment]
By default `Ctrl+L` is bound to SCI_LINECUT, while `Ctrl+Shift+L` is bound to SCI_LINEDELETE.

**Comment by wormuth** [comment]
Arrgh,
that was a gut shot ;-) 
Shouldn't file "bugs" in the morning, I guess - my apologies...
