### ISSUE TITLE
[ENHANCEMENT] *.psm1 extension should be mapped to Powershell Language

### ISSUE THREAD

**Issue by mmascolino** [notepad-plus-plus/notepad-plus-plus#1915]
Since .psm1 is the extension for writing Powershell modules, I think it should be giving the same default treatment as *.ps1

**Comment by anorhoads** [comment]
Agree.  Also .psm1  (PowerShell Module) and .psd1 (PowerShell Data File - Module Manifest).

**Comment by MetaChuh** [comment]
please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins if you update from version 7.5.9 or below.
if your issue still persists, and it is still of relevance, please feel free to file a new issue as easy to understand and reproducible as possible.

thank you for your help and best regards.
