### ISSUE TITLE
[Feature Request] Individual Text Direction Per Tab

### ISSUE THREAD

**Issue by MeiRct** [notepad-plus-plus/notepad-plus-plus#1917]
I don't find it comfortable that when I switch the text direction to RTL in one document, it remains at the whole NP++ window level and takes place among all other opened documents.

I think it should be saved only for the desired document, as well as in switching code language.

If this request is accepted, perhaps it will then make sense to have an additional setting in `Settings > Perfences > New Document`, for the default text direction for new documents.

**Comment by MeiRct** [comment]
@milipili I can see you're quite active around.
Any chance you can take some action here please? :)

**Comment by milipili** [comment]
lol I will see what can I do :)

**Comment by ezra100** [comment]
I just developed a plugin for that @MeiRct, check it out:
[RTL Manager](https://github.com/RTLManager/RTLManager/releases)

**Comment by MetaChuh** [comment]
we will currently not pursue rtl enhancements at the notepad++ core, also because many rtl+ltr issues have still not been fixed at the latest scintilla releases.

i hope that rtl manager plugin suits your needs.

many thanks and best regards.
