### ISSUE TITLE
Comments in CSS files

### ISSUE THREAD

**Issue by whitedream31** [notepad-plus-plus/notepad-plus-plus#1918]
When I open a CSS file and modify a /\* comment */ at the top of the file the rest of the content (rules, elements, etc) have the syntax colour removed. It has been doing this for quite some time.

**Comment by dail8859** [comment]
Works fine for me. Post a screenshot or exact steps to reproduce the issue.

**Comment by whitedream31** [comment]
I've done some checking and removed the plugins. It seems that when there is a www link in the comment and the return key is pressed further down the coloured syntax disappears.

Try this:
Create a new file and try the css below. Save it as a css file.

/*
http://www.website.com

(return pressed here)

*/

body {
	margin: 0;
	padding: 0;
	background: #FFFFFF;
	font-family: "Trebuchet MS", Arial, Helvetica, sans-serif;
	font-size: 14px;
	color: #000;
}



Debug Info:

Notepad++ v6.9.1
Build time : Mar 28 2016 - 19:48:40
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 7
Plugins : NppTextFX.dll PluginManager.dll

**Comment by dail8859** [comment]
Yeah I can reproduce it now. That's really odd.

**Comment by MetaChuh** [comment]
please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins if you update from version 7.5.9 or below.
if your issue still persists, and it is still of relevance, please feel free to file a new issue as easy to understand and reproducible as possible.

thank you for your help and best regards.
