### ISSUE TITLE
Select complete content of an XML or HTML tag completely by some shortcut or through menu

### ISSUE THREAD

**Issue by SanhatKhan** [notepad-plus-plus/notepad-plus-plus#1921]
Hi Notepad++ Team,

First of all a BIG THANKS to all of you who have developed such a nice editor and that too as open source. Really appreciable effort by you guys!

Notepad++ is already enriched with high end features already and is continuously evolving but I'd like to suggest one feature which is explained below:-
- We generally have very big XML or HTML files
- Sometimes it is required to select the complete content of some tag. Complete content means select whatever is there inside that tag from beginning of tag till closing of that tag.
- As of now Notepad++ highlights the beginning & closing tags whenever cursor is on either the beginning tag or closing tag. It is pretty amazing but when we want to select complete content inside that beginning & closing tag then we have to it manually. Manually selecting it is fine as far as we can see both the beginning & closing tag on the screen without scrolling but when closing is too way far from the beginning tag then it becomes difficult to select the content because as soon as you start scrolling it becomes hard to find the highlighted closing tag because file is too big and scrolling just by a millimeter moves so much of content that you can't identify the highlighted closing tag.
- So it would be great that whenever we want to select the entire content of a tag from beginning till end we just place the cursor anywhere inside the beginning & closing tag and hit some shortcut key that does the job of selecting the inside content of tag.

I hope I'm able to explain the feature as good as possible.
Kindly feel free to contact me if you need any further clarification.

Thanks,
Sanhat Khan

**Comment by MetaChuh** [comment]
please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins if you update from version 7.5.9 or below.
if your issue still persists, and it is still of relevance, please feel free to file a new issue as easy to understand and reproducible as possible.

thank you for your help and best regards.
