### ISSUE TITLE
Invisible cursor bug

### ISSUE THREAD

**Issue by sanastasiou** [notepad-plus-plus/notepad-plus-plus#1922]
Notepad++ v6.9.2
Build time : May 18 2016 - 00:34:05
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10
Plugins : CodeAlignmentNpp.dll mimeTools.dll NppConverter.dll NppExport.dll PluginManager.dll 

To reproduce do the following:

Close all documents. Close Npp.

Open new instance of NPP.

new 1 is opened.

Do not click inside the editor area, rather click on open file button and open any kind of file.

File is opened, first line is highlighted but cursor is nowhere to be seen. U can navigate with arrows/mouse type or whatever but cursor is still invisible.

To fix:

Remove focus from NPP and then click inside Editor area. Cursor will appear.

**Comment by SinghRajenM** [comment]
Could not reproduce with latest version Notepad++ v7.3.2.

**Comment by donho** [comment]
No reply, closed.
