### ISSUE TITLE
v 6.9.2 - 'Log Mornitoring' feature causes 100% CPU usage when monitored log file is automatically archived

### ISSUE THREAD

**Issue by Ywtktm** [notepad-plus-plus/notepad-plus-plus#1925]
Hi,
we're using Nlog to write our logs to files and automatcally archive these files above configured file size.

New feature Log Mornitoring (tail -f) causes an increased cpu usage by Notepad++ from the moment when monitored log file has been archived and content of the file has been cleared.

Nlog config example:
    <target xsi:type="File" name="file"
            fileName="C:/Logs/full_log.txt"
            archiveFileName="C:/Logs/Archives/full_log.{#####}.txt"
            archiveAboveSize="10240000"
            archiveNumbering="Sequence"
            concurrentWrites="true"
            keepFileOpen="false"
            encoding="UTF-8" />

![capture03061](https://cloud.githubusercontent.com/assets/19725896/15774941/61d49152-297f-11e6-8e6c-399b9fe5ced7.PNG)

**Comment by donho** [comment]
@Ywtktm What do you mean by "archived"? How can I reproduce it without using Nlog?

**Comment by Ywtktm** [comment]
Hi,
to reproduce this issue you can just delete from disk the file that is currently being monitored.

BR

**Comment by donho** [comment]
I have deleted a file which is being monitored.
I got "The file doesn't exist anymore. Keep this file in editor?"  Messagebox instead hanging.
There must be somethings missing to reproduce it. 
Any idea?

**Comment by donho** [comment]
Issue outdated + Absence of reply.
