### ISSUE TITLE
Find function together with Count function matching word(s)/characters

### ISSUE THREAD

**Issue by imon214** [notepad-plus-plus/notepad-plus-plus#1926]
Would be good if you hit Find when searching particular word(s), it will automatically count matching word(s) you are searching and no need to manually click the count button just to see how many such word(s) in the opened document. And showing it right beneath the "Find what:" input field and not in the status bar at the bottom edge, as it hardly to see the bottom status of the Find window (where the count shows-up) when it was moved (most probably moving it down to see the matching words) around the main notepad++ window.

**Comment by MetaChuh** [comment]
please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins if you update from version 7.5.9 or below.
if your issue still persists, and it is still of relevance, please feel free to file a new issue as easy to understand and reproducible as possible.

thank you for your help and best regards.

**Comment by sasumner** [comment]
For most users, Find Next and Count are distinct operations because they aren't needed simultaneously.
