### ISSUE TITLE
Incorrect character encoding when changing timezone

### ISSUE THREAD

**Issue by mrpapercut** [notepad-plus-plus/notepad-plus-plus#1927]
Platform: Windows10
N++ version: 6.8.3, 6.9.2

Steps to reproduce:
- Open a file in N++, make sure encoding is set to UTF-8
- Change system timezone to a different timezone-offset (important: your system time has to change. Selecting a different locale within the same timezone doesn't work)
- Go back to N++. It will mention the file has been changed on disc and needs reloading. The document encoding has been changed to ANSI (according to N++).
  If you close and reopen the file without changes, the encoding is still UTF-8 though

Tried on 2 computers and 2 different N++ versions

**Comment by chcg** [comment]
Related to  #215, regarding the issue that changing the timezone triggers a reload.

**Comment by chcg** [comment]
Or @mrpapercut could also close this.

**Comment by mrpapercut** [comment]
When changing timezones on Win10 with N++ 7.5.8, it does not say the file is changed and encoding remains the same. Will close, thanks all
