### ISSUE TITLE
Run minimized

### ISSUE THREAD

**Issue by aaaxx** [notepad-plus-plus/notepad-plus-plus#1928]
Is there any way to run N++ minimized?

**Comment by dail8859** [comment]
What do you mean exactly? You can run it from the system tray. 

`Settings > Preferences > MISC. > Minimize to System Tray`

**Comment by aaaxx** [comment]
I meant start it minimized. I set it up to run at Windows startup and the usual "Run: Minimized" option in shortcut Properties doesn't work.

**Comment by donho** [comment]
This feature is not done, and I don't think it will be done.
