### ISSUE TITLE
Error with Drag and Drop.

### ISSUE THREAD

**Issue by davidmachadoSP** [notepad-plus-plus/notepad-plus-plus#1929]
Hi I recently upgrade to 6.9.2 version and when I tried to Drag my xml file from windows folder to the notepad++ it didn't work!!! The file wasn't open.

**Comment by SinghRajenM** [comment]
Duplicate of #2641, #159, #556.

Issue is fixed in #2643 . Try latest version.

@dail8859 can we close this ticket?

**Comment by dail8859** [comment]
Closed by #2643
