### ISSUE TITLE
[Feature Request] UDL 2: Allow ((EOL)) in Open field

### ISSUE THREAD

**Issue by thdoan** [notepad-plus-plus/notepad-plus-plus#1931]
In Markdown (and possibly other languages) you can have two different patterns that are similar to line comments:
1. `# Headline`
2. `> Quoted text`

You can enter `# >` in the Open field of the comment line style section, but what if you want headlines and quoted text to have different styles? Right now, it can't be done reliably with UDL 2. To work around this, I suggest allowing the special symbol `((EOL))` in the Open field. This way, I can define a delimiter for quoted text like this:

```
Open: ((EOL))>
Escape:
Close: ((EOL))
```

Note that this could be related to issue #955.

**Comment by MetaChuh** [comment]
please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins if you update from version 7.5.9 or below.
if your issue still persists, and it is still of relevance, please feel free to file a new issue as easy to understand and reproducible as possible.

thank you for your help and best regards.
