### ISSUE TITLE
Coverity static analysis issues

### ISSUE THREAD

**Issue by gszo123** [notepad-plus-plus/notepad-plus-plus#1932]
I have added static analysis results of PowerEditor by Coverity here:
https://scan.coverity.com/projects/gszo123-notepad-plus-plus

I will be reviewing defects for false positives soon and try to fix outstandig defects.

**Comment by MetaChuh** [comment]
please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins if you update from version 7.5.9 or below.
if your issue still persists, and it is still of relevance, please feel free to file a new issue as easy to understand and reproducible as possible.

thank you for your help and best regards.
