### ISSUE TITLE
File menu width doesn't change after setting recent files maximum length

### ISSUE THREAD

**Issue by thdoan** [notepad-plus-plus/notepad-plus-plus#1935]
After setting the recent files maximum length to 10, the File menu width is not updated to reflect the new maximum length. Example:

![image](https://cloud.githubusercontent.com/assets/4110567/15880414/a8c482c8-2d5f-11e6-8f17-b5d04476d816.png)

**Comment by MetaChuh** [comment]
please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins if you update from version 7.5.9 or below.
if your issue still persists, and it is still of relevance, please feel free to file a new issue as easy to understand and reproducible as possible.

thank you for your help and best regards.

**Comment by sasumner** [comment]
Verified working fine in 7.6.6
