### ISSUE TITLE
Suggested changes to Style Configurator / Language labels

### ISSUE THREAD

**Issue by thdoan** [notepad-plus-plus/notepad-plus-plus#1936]
I propose the following changes to the language names in the Style Configurator / Language list (based on either the official homepage or the Wikipedia entry):
- asp → ASP ([source](https://en.wikipedia.org/wiki/Active_Server_Pages))
- autoIt → AutoIt ([source](https://www.autoitscript.com/))
- bash → Bash ([source](https://en.wikipedia.org/wiki/Bash_%28Unix_shell%29))
- CMakeFile → CMake or CMake file ([source](https://cmake.org/))
- DIFF → diff ([source](https://en.wikipedia.org/wiki/Diff_utility))
- GUI4CLI → Gui4Cli ([source](http://gui4cli.com/))
- ini file → INI file ([source](https://en.wikipedia.org/wiki/INI_file))
- InnoSetup → Inno Setup ([source](http://www.jrsoftware.org/isinfo.php))
- Javascript → JavaScript ([source](https://en.wikipedia.org/wiki/JavaScript))
- LISP → Lisp ([source](https://en.wikipedia.org/wiki/Lisp_%28programming_language%29))
- Makefile → makefile ([source](https://en.wikipedia.org/wiki/Makefile))
- Matlab → MATLAB ([source](http://www.mathworks.com/products/matlab/))
- Dos Style → NFO file ([source](https://en.wikipedia.org/wiki/.nfo))
- php → PHP ([source](http://php.net/))
- Postscript → PostScript ([source](https://en.wikipedia.org/wiki/PostScript))
- Search result → Search results
- VB / VBS → VB / VBScript ([source](https://en.wikipedia.org/wiki/VBScript))

On a related note, I notice under Fortran default extensions, `f77` is not there. This extension is defined in `langs.model.xml` in the latest version, and I copied this file to `langs.xml` already, so I was expecting it to be updated in the Style Configurator as well. I wonder if this should be filed as a bug.

**Comment by MetaChuh** [comment]
please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins if you update from version 7.5.9 or below.
if your issue still persists, and it is still of relevance, please feel free to file a new issue as easy to understand and reproducible as possible.

thank you for your help and best regards.
