### ISSUE TITLE
Bash syntax highlighting mistakes bitwise left shift operator for here document

### ISSUE THREAD

**Issue by echo-e** [notepad-plus-plus/notepad-plus-plus#1940]
The Bash/Shell syntax highlighting parses the bitwise left-shift operator (<<) as a Here document redirect and causes the remainder of the document to be highlighted as such. There is some example code:

for (( i=0 ; i<8 ; i++ ))
do
  if (( status1 & 1<<i ))
  then
    echo ${interrupts1[$i]}
  fi
done

**Comment by mat-m** [comment]
The HereDoc marker is usually defined with no space between the angle brackets and the end-of-text marker. 

Maybe npp could add some logic to consider a `<<` sign between `(( ))` as a bitwise rather than a Heredoc redirect. Else, the only way for it to detect the two cases is to always add a space when using the bitwise left-shift.

**Comment by echo-e** [comment]
Are you saying that adding a space after the angle brackets should change the npp highlighting? I tried this and it still produces HereDoc highlighting.

**Comment by mat-m** [comment]
Yeas, I thought so and prove myself wrong.
Apologies.

**Comment by MetaChuh** [comment]
please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins if you update from version 7.5.9 or below.
if your issue still persists, and it is still of relevance to you, please feel free to file a new issue as easy to understand and reproducible as possible.

thank you for your help and best regards.

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
(no extra account is needed, just use your github account to sign in)
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)

**Comment by echo-e** [comment]
This still isn't fixed (in v8.4.7). If the characters following the the bit shift operator are a variable label, npp treats it as the here doc terminator string. This doesn't happen if the characters are numeric or $, so a workaround is to let the shell do the substitution, e.g.: 

if (( status1 & 1<<$i ))

instead of 
if (( status1 & 1<<i ))

**Comment by alankilborn** [comment]
Here's how it appears in N++ 8.6:

![image](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/77065706/f240c4b2-6655-4866-ac9f-9cd677652bb1)

**Comment by echo-e** [comment]
Apologies for my poor bug commenting etiquette. I posted in haste without updating N++ first. Version 8.6 does indeed highlight my original example correctly, but I ran into a different variant of it again today with this code snippet:
```
for (( i=0 ; i<W_HID ; i=i+1 )); do
  s_hid=$(( s_hid + (((status & 1 << (W_HID - i - 1)) > 0)<<i ) ))
done
```

![image](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/2705389/4115111d-af7e-45b8-83cb-9a4aa3763162)

**Comment by alankilborn** [comment]
Probably best to report this to Scintilla as it is responsible for such lexing.
