### ISSUE TITLE
uncorrected copy and paste for right to left languages (i.e. Persian) when LTR Text Direction

### ISSUE THREAD

**Issue by darkhedmatim** [notepad-plus-plus/notepad-plus-plus#1941]
![copy_paste_bug_rtl_languages_in_ltr_textdirection_notepad](https://cloud.githubusercontent.com/assets/19830699/15918705/44b1b16c-2df9-11e6-91b4-2f8b5a179a08.jpg)
[Copy_Paste_Bug_RTL_Languages_in_LTR_TextDirection_Notepad++.txt](https://github.com/notepad-plus-plus/notepad-plus-plus/files/306105/Copy_Paste_Bug_RTL_Languages_in_LTR_TextDirection_Notepad.txt)
Images are perfectly expressed opinion error. In each image selected text in the first line  is copied on the second line. first image in LTR Text Direction Ctrl+Alt+L and second  image in RTR Text Direction Ctrl+Alt+R. first image has error.

**Comment by MetaChuh** [comment]
as rtl is part of the scintilla component, you would have to file your request at the [scintilla project feature requests](https://sourceforge.net/p/scintilla/feature-requests/).
thanks for understanding and best regards.

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
(no extra account is needed, just use your github account to sign in)
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)
