### ISSUE TITLE
Wrong font size when scaled through RDP

### ISSUE THREAD

**Issue by wseguin** [notepad-plus-plus/notepad-plus-plus#1944]
I have 4k monitors and I use 175% scaling so I can read actually text. Notepad++ tab fonts are scaled properly, but if I RDP to a remote server, which translates the scaling, everything is scaled properly except the text in the filename tab.

![image](https://cloud.githubusercontent.com/assets/10696533/15934590/1fbba406-2e32-11e6-9877-48ad35cb5039.png)

It looks normal because the screen cap is capturing at 4k resolution. Imagine the rest of the text being normal size, the tab label is barely legible.

**Comment by donho** [comment]
I believe this issue has been fixed since long time ago.
Update your Notepad++ to the latest version (v7.6.6).
If the issue persists, please create a new issue for it.
Thank you.
