### ISSUE TITLE
"Run commands" names do not support Unicode

### ISSUE THREAD

**Issue by dogancelik** [notepad-plus-plus/notepad-plus-plus#1947]
The file is encoded with UTF-8 (no BOM)
Run commands do NOT work when you encode the file with UTF-8 (with BOM).

![encoding](https://cloud.githubusercontent.com/assets/486818/15982639/4f7f2e38-2f95-11e6-91ef-7f55d457e3ba.png)

Here's what it looks like in Run menu:

![shortcuts_menu](https://cloud.githubusercontent.com/assets/486818/15982632/25f0b71c-2f95-11e6-9089-6e68245f5dc7.png)

![mapper](https://cloud.githubusercontent.com/assets/486818/15982650/95323056-2f95-11e6-97b4-16da974669dd.png)

Notepad++ version: 6.9.2 
Windows version: 8 (64-bit)

**Comment by xylographe** [comment]
Have you tried inserting (first line) an XML declaration `<?xml version="1.0" encoding="utf-8"?>`?

**Comment by dogancelik** [comment]
I tried now, doesn't work. You can try any non-latin character.

**Comment by xylographe** [comment]
If you modify the 'Name' in the shortcut mapper, NPP will store the non-ASCII characters as XML entities (`&xhh;`). Of course, that only works for characters that can be mapped to the codepage of your locale. But perhaps it might help as a work-around, until this ugly XML parser bug is fixed.

**Comment by MetaChuh** [comment]
please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins if you update from version 7.5.9 or below.
if your issue still persists, and it is still of relevance to you, please feel free to file a new issue as easy to understand and reproducible as possible.

thank you for your help and best regards.

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
(no extra account is needed, just use your github account to sign in)
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)
