### ISSUE TITLE
Add shortcuts to finder for collapse/open

### ISSUE THREAD

**Issue by GitMensch** [notepad-plus-plus/notepad-plus-plus#1951]
[+]/[-] on a node: (un-)collapse it
[SHIFT]+[+]/[-] on a node: (un-)collapse all

_edit_ (for reference) - already working shortcuts:
[DEL]: delete single node when on node, otherwise delete single line from finder

**Comment by MetaChuh** [comment]
implemented with:
collapse all: <kbd>alt</kbd> + <kbd>0</kbd>
uncollapse all: <kbd>alt</kbd> + <kbd>shift</kbd> + <kbd>0</kbd>

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)

**Comment by GitMensch** [comment]
Just did an update.

Then -> search all, resulting in "find results" being open using any of the mentioned shortcuts (and +/-) to collapse only a single result) did not work and the "compare 7.6.6 against current master" does not show a recent addition.

So "I'm not satisfied".
Debug Info:
~~~
Notepad++ v7.6.6   (32-bit)
Build time : Apr  3 2019 - 23:49:50
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10 (64-bit)
Plugins : mimeTools.dll NppConverter.dll NppExport.dll 
~~~


@MetaChuh : Did I miss something? If not: please reopen.
