### ISSUE TITLE
Crash open .nfo

### ISSUE THREAD

**Issue by NicoGH** [notepad-plus-plus/notepad-plus-plus#1952]
Hello!
I'm not a developer, but just a passionate user.
I use NotepadPlusPlus to edit my files, among which from.bat especially.
Today, NPP crashed at the opening of a .nfo file.
You will find attached the dump file.
Hope this helps you because NPP is really a top editor.
Best regards,
Nico

[NppDump.zip](https://github.com/notepad-plus-plus/notepad-plus-plus/files/310677/NppDump.zip)

**Comment by NicoGH** [comment]
Oops, the .nfo file can be useful for debugging crash Notepad Plus Plus.
[FFD_projet_test-NFO.zip](https://github.com/notepad-plus-plus/notepad-plus-plus/files/310734/FFD_projet_test-NFO.zip)

**Comment by Tmp341** [comment]
I've opened it without a problem. Check your plugins.
