### ISSUE TITLE
Detect duplicate keyboard shortcut

### ISSUE THREAD

**Issue by thdoan** [notepad-plus-plus/notepad-plus-plus#1954]
I assigned a keyboard shortcut recently and it wasn't working. After looking through all the assigned shortcuts I realized it wasn't working because there was already another shortcut assigned to this combo. It would be greatly appreciated if there is a routine to detect duplicate shortcuts.

[Geany](https://github.com/geany/geany) has a good shortcut mapper that is well categorized and has duplicate detection, so maybe it's something that can be used as a model.

**Comment by dail8859** [comment]
Closed by 1abac157993685c4f6345443f6256403526858ad
