### ISSUE TITLE
Notepad++'s formatting gets off on some python modules if it is open for 8 Hours.

### ISSUE THREAD

**Issue by AraHaan** [notepad-plus-plus/notepad-plus-plus#1956]
Sometimes the formatting gets screwed eg the end lines make it look wrong and the spacing and whatnot wrong as well. and must be repoened to fix it. And if they try to manually fix it in Notepad++ it would result in a IndentionError in Python.

It does look reproducable too.

**Comment by AraHaan** [comment]
Here is a image of what happens if you try to fix it and save when this bug happens. 
![cc45ecb4ee2914161391af71769259d5](https://cloud.githubusercontent.com/assets/15173749/16008635/8d4b2f1e-313e-11e6-8cfd-c44ef31c5905.png)

**Comment by Zoinkity** [comment]
It's not just python modules.  I've had UTF-8 text files do the same thing, and depending on the bytes misinterpretted this can cause a crash + complete file loss.
![capture](https://cloud.githubusercontent.com/assets/5980759/16159733/63d8a132-3492-11e6-829f-7de846ea355e.PNG)

**Comment by AraHaan** [comment]
yep confirmed even in exe files that are very large when opened in Notepad++. Nice pointign it out.

**Comment by dail8859** [comment]
When working with large files it is best to turn off periodic backups.

**Comment by Zoinkity** [comment]
Periodic backups are off.
Even small files--less than 100 lines--using multi-byte encodings will occasionally behave this way.

**Comment by dail8859** [comment]
> Periodic backups are off.

Good to know. I know there's been several reports that periodic backups of large files cause this exact symptom, that's why I mentioned it. The next best thing to try is disabling all the plugins to make sure it is not one of them causing it.

**Comment by MetaChuh** [comment]
please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins if you update from version 7.5.9 or below.
if your issue still persists, and it is still of relevance to you, please feel free to file a new issue as easy to understand and reproducible as possible.

thank you for your help and best regards.

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
(no extra account is needed, just use your github account to sign in)
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)
