### ISSUE TITLE
&& not showing up in javascript file with default style theme

### ISSUE THREAD

**Issue by borisplotkin** [notepad-plus-plus/notepad-plus-plus#1958]
When I edit javascript file that has && conditions they simply don't show up, just blank space. 
This can be very confusing and should be fixed.

Thank you for the great editor!

**Comment by dail8859** [comment]
This is a known issue and was fixed. Try [searching](https://github.com/notepad-plus-plus/notepad-plus-plus/issues?utf8=%E2%9C%93&q=is%3Aissue+ampersand) before posting a new issue ;)
