### ISSUE TITLE
Fix autocomplete adding un-wanted data when trying to go to a new-line and hiding when backspace is using...

### ISSUE THREAD

**Issue by Acecool** [notepad-plus-plus/notepad-plus-plus#1963]
When typing on the fly, the autocomplete can be useful in some situations but in 90% of situations it ends up turning end into endgogjo or some other nonsense along with other data...

In the impossible to use shortcut mapper, all of the auto-complete actions use CTRL + ENTER.but enter ( for new line ) still triggers the hint box.

Additionally, when you backspace a character the hint box disappears for the remainder of the word rather than subtracting a letter from the current partial and using that...

And, when a word is fully typed, it disappears from the list so you can't use the hint box to check short words to see if they exist in the document; if the full word is typed, and exists, it could be marked a different way or it could be kept in the box so if I go to a new-line after typing end then endlkjhdkjghdkjgf doesn't pop up....

CTRL + ENTER doesn't display the hint box again after backspace, or ever.. CTRL + SPACE doesn't either..

**Comment by MetaChuh** [comment]
please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins if you update from version 7.5.9 or below.
if your issue still persists, and it is still of relevance to you, please feel free to file a new issue as easy to understand and reproducible as possible.

thank you for your help and best regards.

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
(no extra account is needed, just use your github account to sign in)
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)
