### ISSUE TITLE
debugging C# plugins on v6.9.2 not working

### ISSUE THREAD

**Issue by kbilsted** [notepad-plus-plus/notepad-plus-plus#1964]
Im experiencing that I cannot in visual studio 2015 "debug -> attach to process" (notepad++.exe) anymore. My breakpoints are never hit so I cannot debug my plugins

Works fine on v6.9 + v6.9.1 - just downloaded and checked.

**Comment by dail8859** [comment]
I know it's not quite the same but I can at least confirm debugging C++ plugins work for VS2013 and VS2015 for v6.9.2

**Comment by dail8859** [comment]
Also tried VS2015 with a C# plugin and it did *not* work for me. FYI I'm no debugging expert so I probably can't be of much more help ;)

**Comment by kbilsted** [comment]
@dail8859  Well, debug -> attach to process -> notepad++.exe  - should hit your breakpoints... ;)

**Comment by kbilsted** [comment]
@dail8859  please fix as fast as you did with the crashing plugins :-P

**Comment by dail8859** [comment]
Tried to look into this more but oddly enough it is working fine for me now.

1. Cloned NppPluginGuidHelper
2. Built the Debug configuration
3. Manually copied the DLL to the plugin directory of N++ v6.9.2 (setting a post build event to `copy $(TargetPath) "C:\Program Files (x86)\Notepad++\plugins\"` also worked)
4. Set the N++ exe as the external program to launch for debugging
5. Set a breakpoint
6. Pressed F5
7. It worked

**Comment by kbilsted** [comment]
@dail8859  which windows? are you executing as administrator?

**Comment by dail8859** [comment]
Win7, yes

**Comment by sanastasiou** [comment]
@kbilsted  I'll try this today and give u feedback.

**Comment by sanastasiou** [comment]
I can debug just fine..

**Comment by sanastasiou** [comment]
Put this in your commandMenuInit subroutine:

Debugger.Launch();

It will launch the debugger every time you start your plugin. If you don't come this far, there's something else crashing the system before you get there, in which case, I suggest you build Npp yourself and start debugging that .. helped me in the past..
