### ISSUE TITLE
Incorrect behaviour when clicking past the end of the document

### ISSUE THREAD

**Issue by Hammerite** [notepad-plus-plus/notepad-plus-plus#1966]
Open a new document, and type a short string on a single line, say "aaaaaaaaaaaassssssssssssddddddddddddffffffffffff". Click somewhere in the middle of the string, say amidst the d's. The cursor moves to the location you clicked. Now click in the void below the end of the line, somewhere that is horizontally in the middle of the line, say amidst the s's.

Expected behaviour: The cursor moves within the line to the approximate horizontal location you clicked at (amongst the s's).

Actual behaviour: The cursor moves to the end of the line.

**Comment by SinghRajenM** [comment]
I don't see anything wrong with the behavior.
Consider a case: You have same string in two lines and trying the same steps. What would you expect from N++? which line it should pick?

P.S. It is most common behavior of popular editors such as notepad++, even window notepad.

**Comment by Hammerite** [comment]
Expected behaviour in the case you describe would be that the cursor would move to the correct horizontal location on the last line of the document. I'm almost sure the behaviour I am advocating was at one time the behaviour of Notepad++.

Consider that the behaviour I am advocating has the following benefit: if I have a single line of text (as for example, if I had copy & pasted from some other source) then if I want to position the cursor somewhere within the line, I don't have to pay great attention to the vertical position I click at to make sure it is "on the correct line" - I just have to click somewhere that is correct horizontally, which is what I'm naturally concentrating on since there is only one line of text. With the present behaviour, if I click slightly too low the cursor moves to the end of the line instead of where I meant it to go to. This is especially annoying if the line of text is long and I have word wrap turned off, as it causes the window to scroll horizontally, forcing me to scroll back to where I wanted to be.

Consider also that if the user really wants to reach the end of the document, they have alternative ways of doing that (for example they can press Ctrl+End).

**Comment by MetaChuh** [comment]
please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins if you update from version 7.5.9 or below.
if your issue still persists, and it is still of relevance to you, please feel free to file a new issue as easy to understand and reproducible as possible.

thank you for your help and best regards.

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
(no extra account is needed, just use your github account to sign in)
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)

**Comment by sasumner** [comment]
The correct behavior is:  You are clicking beyond the end of the document.  Thus the caret attempts to go to the right of the last character in the document, not to the middle of the last line just because the clicked position horizontally matches a point somewhere in that line.
