### ISSUE TITLE
Problem with zero-length regular expressions

### ISSUE THREAD

**Issue by bobf32** [notepad-plus-plus/notepad-plus-plus#1967]
Hi. There is a problem when searching for zero length REs such as ^ or ^$. When navigating to the the next match requires the text in the window to scroll, the search acts as if there are two instances of the RE at the same position. To test this, create a file consisting of newlines only and then resize the npp window so the file contents does not all display. Do a RE find for ^ and F3 until the text scrolls to the next match. At this point the next F3 will not find the next match but rather stays on the current match, until F3 is hit again

Has been an issue for a couple of years at least and is still an issue in 6.9.2. Non zero-length REs do not appear to exhibit this behaviour.

**Comment by MetaChuh** [comment]
please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins if you update from version 7.5.9 or below.
if your issue still persists, and it is still of relevance to you, please feel free to file a new issue as easy to understand and reproducible as possible.

thank you for your help and best regards.

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
(no extra account is needed, just use your github account to sign in)
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)

**Comment by sasumner** [comment]
I tested this issue in 7.6.6 and it still exists.  But as I am not the OP, I will not be the one creating a new issue. :)

Anyway, here is a screencast which shows the issue (findwhat was `^`, trying to press findnext button every 1 second, but not so successful at points...be assured that every time some sort of screen movement happens it is because of a findnext press):

![test](https://user-images.githubusercontent.com/30118311/56663480-2edd3800-6674-11e9-88b2-4544406e48c1.gif)
