### ISSUE TITLE
PluginManager crash when sourceforge.net is blocked

### ISSUE THREAD

**Issue by ryancu7** [notepad-plus-plus/notepad-plus-plus#1968]
Hi

The company I work for blocks sourceforge.net (all requests get 403) due to their [adware practices](http://www.lifehacker.com.au/2015/06/notepad-and-pale-moon-leave-sourceforge-over-adware-practices/). 

When the Notepad++ plugin manager notifies me that a plugin needs updating (e.g. NppFtp) and I click update, Notepad++ crashes as soon as it tries to start downloading the plugin. 

Problem Event Name:	APPCRASH
Application Name:	notepad++.exe
Application Version:	6.9.2.0
Fault Module Name:	PluginManager.dll
Fault Module Version:	1.3.5.0

**Comment by dail8859** [comment]
Please report this to the [PluginManager repository](https://github.com/bruderstein/nppPluginManager).
