### ISSUE TITLE
Unknown exception when trying to use a python plugin script. Advice please.

### ISSUE THREAD

**Issue by d-jas** [notepad-plus-plus/notepad-plus-plus#1969]
I installed a known working python plugin script to reverse the line order of lines in N++. Every time I try to use it I get an Unknown exception error message.

My N++ is v6.9.2 and I am running windows 7 64bit on a PC

The script can be see here http://pastebin.com/nG9zeBkW courtesy of the author, Reck Dickhard.

I believe the issue is not with the script but in my N++ setup to run it correctly.

Any advice as to how to get this to work properly will be appreciated. Thank you.

**Comment by dail8859** [comment]
Try reporting to bug to the [PythonScript](https://github.com/bruderstein/PythonScript) repo. Or possibly someone on the forum may be able to help.

**Comment by BugZappr** [comment]
See [Emmitio plugin issue 12](https://github.com/emmetio/npp/issues/12#issuecomment-155416270) as to why Python scripts referencing the standard Python library might not work.

**Comment by BugZappr** [comment]
`def reverseAllLines():
	lines	= editor.getText().splitlines()
	lines.reverse()
	eol = '\r\n'
	editor.setText(eol.join(lines))

def reverseSelectedLines():

	staline	= editor.lineFromPosition(editor.getSelectionStart())
	endline	= editor.lineFromPosition(editor.getSelectionEnd())
	start	= editor.positionFromLine(staline)
	end		= editor.positionFromLine(endline)+editor.lineLength(endline)

	text	= editor.getTextRange(start, end)
	
	eol = '\r\n'

	lines	= text.splitlines()
	lines.reverse()

	text	= eol.join(lines)+eol

	editor.setSelection(start, end)
	editor.replaceSel(text)
	editor.setSelection(start, end)	#keep selection after replace


editor.beginUndoAction()
if editor.getSelectionStart() == editor.getSelectionEnd():
	reverseAllLines()
else:
	reverseSelectedLines()
editor.endUndoAction()`

works
