### ISSUE TITLE
Monokai Theme colors undefined for Python

### ISSUE THREAD

**Issue by gnbl** [notepad-plus-plus/notepad-plus-plus#1970]
Monokai is a dark theme shipped with Notepad++. The styles for TRIPLE, TRIPLEDOUBLE, CLASSNAME and DEFNAME do not have a foregroundcolor defined for Python and are thus not visible:

https://github.com/notepad-plus-plus/notepad-plus-plus/blob/3ff59b2a70cd3d5e064131f0491189db9560fdff/PowerEditor/installer/themes/Monokai.xml#L348

Original theme:
http://www.monokai.nl/blog/2006/07/15/textmate-color-theme/
http://www.monokai.nl/blog/wp-content/asdev/Monokai.tmTheme

The original defines the following two colors for classes/functions and comments:

CLASSNAME, DEFNAME: R:166, G:226, B:46
TRIPLE, TRIPLEDOUBLE: R:117, G:113, B:94 (fgColor for COMMENTLINE and COMMENTBLOCK are properly defined)

Accept this issue to get a pull-request for https://github.com/gnbl/notepad-plus-plus/tree/gnbl-patch-1
Diff: https://github.com/notepad-plus-plus/notepad-plus-plus/compare/master...gnbl:gnbl-patch-1

**Comment by dail8859** [comment]
Go ahead and submit a PR.

**Comment by MetaChuh** [comment]
closed as part of the rejected pr https://github.com/notepad-plus-plus/notepad-plus-plus/pull/2004
