### ISSUE TITLE
Autocomplete not working properly

### ISSUE THREAD

**Issue by anil-shrestha** [notepad-plus-plus/notepad-plus-plus#1973]
vb.xml file contains like `<KeyWord name="If Then Else" />`
but autocomplete shows if then else in separate lines.

Please help

**Comment by anil-shrestha** [comment]
No body is replying anything. are you even looking? Due to this error I am not able to update the new version. I am stuck at version 5.8.3 where this bug is not there. Any help will be appreciated.

**Comment by MetaChuh** [comment]
please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins if you update from version 7.5.9 or below.
if your issue still persists, and it is still of relevance, please feel free to file a new issue as easy to understand and reproducible as possible.

thank you for your help and best regards.
