### ISSUE TITLE
Feature request: string hight light also visible in scrollbar

### ISSUE THREAD

**Issue by mjpvissers** [notepad-plus-plus/notepad-plus-plus#1974]
A very handy feature I find when selecting a string it becomes highlighted. My feature request if these can also become visible in the scollbar, which I marked red in the attached screenshot. In this way you can see at a glance where in the whole file this string appears and not only in the part currently visible .

![screenshot](https://cloud.githubusercontent.com/assets/19977305/16120323/5a52518e-33df-11e6-9a2d-4c00ca8cdcfa.png)

Regards,

MJP

**Comment by MetaChuh** [comment]
please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins if you update from version 7.5.9 or below.
if your issue still persists, and it is still of relevance, please feel free to file a new issue as easy to understand and reproducible as possible.

thank you for your help and best regards.
