### ISSUE TITLE
For replace function should be a checkbox to allow replace in readonly files

### ISSUE THREAD

**Issue by trivalik** [notepad-plus-plus/notepad-plus-plus#1975]
For replace function should be a checkbox to allow replace in readonly files. This would be more clear than the current behavior. At the moment appears the message that a file is readonly only milliseconds visible to user, in case other files replace properly. This makes it hard to find the cause.

**Comment by MetaChuh** [comment]
replace is now locked on read only files with a persisting red warning at the status bar.

please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins if you update from version 7.5.9 or below.

many thanks and best regards
