### ISSUE TITLE
Wrong plugin is reported during plugin crash. The FIRST plugin in the plugin folder is blamed

### ISSUE THREAD

**Issue by kbilsted** [notepad-plus-plus/notepad-plus-plus#1980]
Occasionally I make mistakes when developing plugins in C#. I've noticed that the `DSpellCheck` is being blamed although I was at fault. When my plugin err in the `beNotified()` method. 

The below error message I got from inserting into my plugin code  `throw new Exception("hello");`

![npp_plugin_crash](https://cloud.githubusercontent.com/assets/1616338/16180002/408007e8-3677-11e6-8a0c-8b80f9acff70.png)

I've observed this behaviour in v6.9, v6.9.1 and v6.9.2 (i have not tested other versions).

but it can explain why dspellcheck has a bad name - and I've never had dspellcheck crashing yet it is marked as unstable...

**Comment by dail8859** [comment]
Interesting...could you attach your C# plugin that intentionally throws the exception? I already have the DSpellCheck plugin.

I already see some obvious buffer overruns in the N++ code.

**Comment by kbilsted** [comment]
@dail8859  well, take any of my plugins on GH and insert the throw new Exception("hello"); and build.. but I was contemplating making a crash-plugin that can be configured to crash on events, on startup, shutdown etc to test the error handling ;)

you don't need Dspell.. just any plugin with a name with a lower rank than the crashing plugin ;)

**Comment by dail8859** [comment]
Ah OK, I'll just try something like that then.

**Comment by kbilsted** [comment]
@dail8859  let me know.. maybe I can be convinced to create the CrashPlugin some day ;)
