### ISSUE TITLE
.hh files are not recognized as C++

### ISSUE THREAD

**Issue by sirzooro** [notepad-plus-plus/notepad-plus-plus#1983]
When I open file with `.hh` extension in N++, it treats it as plain text instead of C++ and there are no syntax highlighting - I have to switch to C++ manually.

Notepad++ 6.9.2, windows

**Comment by slitazcn** [comment]
this is not a issue,you can open menu "Setting->style configuator",click the "C++",under the dialog there is default ext and user ext,add hh to user ext

**Comment by sirzooro** [comment]
Thanks, I will add it there. But `.cc` is already listed in default extensions, so its counterpart `.hh` should be there too. Please add it.

**Comment by shtse8** [comment]
any updates?

**Comment by donho** [comment]
It has been done since...
