### ISSUE TITLE
Supplementary Multilingual Plane Input

### ISSUE THREAD

**Issue by samhocevar** [notepad-plus-plus/notepad-plus-plus#1990]
It is still impossible to input supplementary multilingual plane characters using third-party keyboard tools. There are two possible solutions to this:
- update the Scintilla version (#1126)
- apply PR #1098 (which I submitted but then closed, thinking Scintilla would be updated…)

To test it with WinCompose, just type <kbd>Compose</kbd> <kbd>\ </kbd> <kbd>o</kbd> <kbd>/</kbd> which should print 🙌.

**Comment by MetaChuh** [comment]
please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins if you update from version 7.5.9 or below.
if your issue still persists, and it is still of relevance, please feel free to file a new issue as easy to understand and reproducible as possible.

thank you for your help and best regards.

**Comment by samhocevar** [comment]
Thanks, I can confirm the issue is completely fixed!
