### ISSUE TITLE
Compare plugin randomly overwrites last visible char with carriage return

### ISSUE THREAD

**Issue by rickertv** [notepad-plus-plus/notepad-plus-plus#1992]
After comparing a pair of text files terminated only with a linefeed, several of the lines are modified so that the last visible char is replaced with a carriage return. The linefeed remains

**Comment by dail8859** [comment]
Compare plugin issue tracker: https://github.com/pnedev/compare-plugin/issues

**Comment by xylographe** [comment]
@rickertv 
Try to reproduce with the [current development version](https://github.com/pnedev/compare-plugin/tree/master) (DLLs in [this folder](https://www.dropbox.com/sh/f42cxkqppuapa1j/AADvlcmqoK_myRmoOpeL1yGMa?dl=0)).

**Comment by rickertv** [comment]
@xylographe - this looks fixed now. Thank you.
