### ISSUE TITLE
Wrong language type when using explorer context menu

### ISSUE THREAD

**Issue by ClaudiaFrank** [notepad-plus-plus/notepad-plus-plus#1996]
When using explorer context menu _Edit with Notepad++_ opens file but sets wrong language type.
It is always set to L_FORTRAN_77, regardless which file type is selected.
Looks like copying cmdLineParam is the problem.

**Comment by J0celyn** [comment]
The bug report was originally posted here, and contains additional details (if needed):
https://notepad-plus-plus.org/community/topic/11932/fortran-syntax-highlighting-applied-to-my-php-files

**Comment by ClaudiaFrank** [comment]
already fixed
