### ISSUE TITLE
N++ automatically closes <?xml version="1.0"?> tag

### ISSUE THREAD

**Issue by sirzooro** [notepad-plus-plus/notepad-plus-plus#1999]
When I entered `<?xml version="1.0"?>`, N++ automatically added closing tag `</?xml>`, what is incorrect. Please fix this.

Notepad++ 6.9.2, windows

**Comment by sirzooro** [comment]
This solution is not complete, other XML Processing Instructions (see https://en.wikipedia.org/wiki/Processing_Instruction) are also affected. You can check if tag name starts with question mark, this should be enough to detect them.

**Comment by dail8859** [comment]
The bug as described was fixed. Open a new issue.

**Comment by sirzooro** [comment]
OK, I will do.
