### ISSUE TITLE
Font name and size

### ISSUE THREAD

**Issue by drdhaval2785** [notepad-plus-plus/notepad-plus-plus#2]
In the current setup, it is difficult to get to font name and size. (Settings -> Style Configurator)
If that can be placed on the toolbar, it would be great.
In such a graphically rich GUI, it is a bit odd to have to search for font name and size.

You can place it anywhere in the line below
![capture](https://cloud.githubusercontent.com/assets/5755132/7213971/51d770d0-e5b0-11e4-818f-f87ede152719.PNG)

**Comment by ariccio** [comment]
I don't think that Don Ho accepts PRs, as he mentioned in a comment:
https://sourceforge.net/p/notepad-plus/patches/656/#88ee/33da/fb13/55d4/2415/9056/2628/e6e7

The link seems broken, the comment is on the second page:

> github repo was created few days ago.
> And the push request is not accepted on github.
> I will find a better way to do that.


I wish he did too ;)

**Comment by ariccio** [comment]
...on the other hand: https://github.com/donho/notepad-plus-plus/pull/1

**Comment by MAPJe71** [comment]
-1
I don't see the relevance/need of the font name and size editable on the toolbar for a **programmers** editor.

**Comment by drdhaval2785** [comment]
It depends on the user. Who said it is only for programmers. It can also be
used as text editor for large text files lets say 10 mb or so. Usual
notepad opens after 3 4 minutes and editinv is out of question. Whereas it
is cakewalk with notepad++.

**Comment by MAPJe71** [comment]
Could you describe an example in which you use the requested feature?

**Comment by KrasnayaPloshchad** [comment]
Well, I got a text editor from [here](http://www.babelstone.co.uk/Software/BabelPad.html). This editor can supports the proper rendering of most complex scripts, and allows you to assign different fonts to different scripts in order to facilitate multi-script text editing, but it is not a GPL-based software.

**Comment by MAPJe71** [comment]
@KrasnayaPloshchad 
Selecting a single or composite font in BabelPad applies that font (and size) to all the text in the opened file. As of that moment the same font (and size) will be applied to any file opened.
For example: 
1. open a file of type 'Python script';
2. apply font e.g. Arial size 12;
3. open a file of type 'Batch script';
Notice the font is still Arial size 12 i.e. the font (and size) was not stored based on the file type (as Notepad++ does!).

@ all
IMO the requested feature ("*add selectable font type and size to toolbar*") is only relevant for word processors (e.g. MS Word, OpenOffice Writer) which store font information along the actual content of the file. Word processors even support different fonts for different parts of the content. Plain text editors like Notepad++ do none such things. However, Notepad++ stores font information based on file type i.e. file extension.

**Comment by drdhaval2785** [comment]
I think there is some confusion going around. I work with Indic languages
and their English counterparts side by side. It is too tedius to change
fonts from style configurator.
And in nitepad++ i see more than enough less used icons on toolbar. Font
does deserve to be on the toolbar

**Comment by h-h-h-h** [comment]
I would find it useful sometimes, but one should additionally be able to clear up his toolbar and choose this item optionally. See issue https://github.com/notepad-plus-plus/notepad-plus-plus/issues/573.

**Comment by donho** [comment]
@drdhaval2785 As you mentioned above, user can use Style Configurator for changing font & font size. And I don't think it's needed on toolbar for ajusting font all the time.
