### ISSUE TITLE
Default shortcut for File->Reload

### ISSUE THREAD

**Issue by NN---** [notepad-plus-plus/notepad-plus-plus#20]
Please add a default shortcut key for File->Reload.
It is very useful feature and I feel tired assigning shortcut key every time.

**Comment by DanAtkinson** [comment]
You should only need to assign the shortcut once. Are you also saying that it's losing the bindings?

**Comment by NN---** [comment]
I mean to assign some default shortcut for File->Reload.
The settings are stored correctly, but fresh installation doesn't have the key binding.

**Comment by AlBundy33** [comment]
a default shortcut (e.g. Alt+R) would be really nice.
Also a setting to go to end of file after the reload would be nice.
This would help to monitor logfiles with one shortcut. :-)

**Comment by chcg** [comment]
@donho See https://support.mozilla.org/en-US/kb/keyboard-shortcuts-perform-firefox-tasks-quickly#w_navigation, seems F5 or Ctrl+R (unused in N++ default installation until now 7.6.2) are commonly used for this task.
