### ISSUE TITLE
Find in files broken

### ISSUE THREAD

**Issue by dvdobrovolskiy** [notepad-plus-plus/notepad-plus-plus#2009]
![unspecified](https://cloud.githubusercontent.com/assets/5516919/16403612/09edc780-3d32-11e6-981e-533f6301bfa7.png)

6.9.2

**Comment by milipili** [comment]
Could you describe what you did to reproduce the problem ?

**Comment by dvdobrovolskiy** [comment]
just open Find in files put what to find and what to replace with
and pressed replace in files

**Comment by AshPriya** [comment]
i did this work.but my version have not this error.i can replace  words without bugs.

**Comment by dvdobrovolskiy** [comment]
I am not able to. 6.9.2 version

**Comment by donho** [comment]
I believe this issue has been fixed since long time ago.
Update your Notepad++ to the latest version (v7.6.6).
If the issue persists, please create a new issue for it.
Thank you.
