### ISSUE TITLE
Wrong mouse cursor over title bar, menu and document tabs

### ISSUE THREAD

**Issue by ygoe** [notepad-plus-plus/notepad-plus-plus#2010]
Every once in a while, I haven't found the trigger yet, the mouse cursor over the window title bar, the menu bar and the document tabs, so everything above the document content, is changed from the default arrow to the text input cursor. When moving the mouse cursor, the arrow flashes up shortly but is immediately replaced with the text mouse cursor as the mouse stops moving. Restarting Notepad++ resolves the issue. This happens when Notepad++ has been running for a day or longer and used all day (switching in and out, and between documents, opening and closing documents…)

Observed with version 6.9.1 but probably already before that.

**Comment by ygoe** [comment]
Happened again now.

**Comment by ygoe** [comment]
And again, just a few minutes after. Something's wrong here.

**Comment by Ede123** [comment]
Sounds a lot like what I discussed with @donho at f2cd7790669ec3867977293f5c83bdec235b81b5 and #1018.
Could you check if this is the case?

**Comment by ygoe** [comment]
Doesn't sound at all like the references you mentioned. I've had the issue a couple of times since my last report, most recently just now. It's still bugging me and I have to restart NPP to resolve it. Simply switching windows, either with Alt+Tab or by mouse interaction, is enough to run into this, it just takes a few days normal usage.

**Comment by MAPJe71** [comment]
Debug Info?

**Comment by ygoe** [comment]
@MAPJe71 What does that comment mean?

**Comment by MAPJe71** [comment]
In Notepad++ open `?` menu, select `Debug Info`, select `Copy debug info into clipboard`.
Post clipboard contents as a comment below :)

**Comment by ygoe** [comment]
> Notepad++ v6.9.2
> Build time : May 18 2016 - 00:34:05
> Path : C:\Program Files (x86)\Notepad++\notepad++.exe
> Admin mode : OFF
> Local Conf mode : OFF
> OS : Windows 10
> Plugins : mimeTools.dll NppConverter.dll NppExport.dll NppSaveAsAdmin.dll PluginManager.dll ScrollPastEOFUni.dll

**Comment by SinghRajenM** [comment]
I found the steps to reproduce the issue.

1. Open a file in (say a.txt) N++
2. Open the same file in windows Notepad. Now update and save it in Notepad.
3. Come to N++, it will ask you to reload the file.
4. As soon you click "Yes", we can see the reported behavior.

![cursor](https://cloud.githubusercontent.com/assets/14791461/23308724/2507eb96-fad2-11e6-8f24-e6c89cf60cab.gif)

**Comment by Ede123** [comment]
It can be worked around by clicking once into the text area... maybe an indication what has to be done to fix the issue?

**Comment by SinghRajenM** [comment]
@Ede123 , Thank you!
With the provided hit, I've submitted the PR. Let @donho take a call about the patch.

**Comment by ygoe** [comment]
The steps to reproduce don't work for me. When I come back to Notepad++, the file is automatically reloaded (as per my configuration, no confirmation dialog here) and the cursor continues to be correct everywhere. So this is not the issue I've reported. I still see my issue every once in a while. I'll try to click into the text area next time to see if that part helps for me.

**Comment by Ede123** [comment]
Automatic reload in fact would not be influenced from any of the workarounds proposed recently nor is it influenced by the code already present. Both are only executed if a confirmation window is shown.

If you find a way to reproduce that would be very helpful, otherwise it's basically impossible to debug. If you *can* reproduce it on your machine and clicking into the text area help the same workaround could be applied of course.

**Comment by Ede123** [comment]
Ah, one idea:
Could it be, that you had modified the file inside Notepad++ before it was modified on disk?
In that very specific case you should see a confirmation message, too, and then it would trigger the very same issue @SinghRajenM and I are seeing!

**Comment by ygoe** [comment]
No, I can't remember having seen that confirmation message in a long time. I rarely run into the situation that files are modified outside of Notepad++ in general.

**Comment by ygoe** [comment]
What a hack that commit is. Side note: It will clear the text selection, if there is any.

**Comment by SinghRajenM** [comment]
Is it not clearing text selection in previous version? Yes, it is.

Reload means => document will be reloaded completely. It might be the case only selected portion/part of selected is modified outside the N++ by other program. So there is no point in keeping the text selection.

**Comment by ygoe** [comment]
You may chose not to reload the document in the dialog. The selection will now be cleared anyways.

**Comment by ygoe** [comment]
Just YFI, I just had that wrong mouse cursor again, with no unsaved or elsewhere modified documents or dialog boxes involved anywhere near. Just alt-tabbing back from the web browser. Clicking into the document area once did resolve it for me. Good to know there is such an easy workaround available.

**Comment by Ede123** [comment]
I'd still love to know the cause of this issue...
I'm afraid I wasn't able to figure it out yet, though. 😞

**Comment by ygoe** [comment]
I think I've found another way to reproduce:

1. Open a plain text document
2. Enter a URL in the document
3. Double-click that URL to open it in a web browser
4. Alt+Tab back to Notepad++

Now the mouse cursor is flickering between default pointer and text input when hovering the entire window (except the editor area itself).

Clicking into the editor once restores normal mouse cursor appearance.

**Comment by Ede123** [comment]
I can confirm this. Also happens when not alt-tabbing back but using the mouse instead.

You should probably open a new issue for that. It's a case that is not handled by the workarounds that were applied and this issue certainly warrants further investigation.

**Comment by SinghRajenM** [comment]
I'm not able reproduce after the applying the fix.

**Comment by ygoe** [comment]
For the initial description of this issue, it is *not fixed*. I have just observed the very same effect again with version 7.3.3. So for the sake of correctness, and if you're willing to actually resolve this bug, please reopen the issue. The workaround of clicking into the editor once still works.

**Comment by ygoe** [comment]
Can you please try again: Write some text that contains a URL. Then **triple-click on that URL**. Three things happen:

1. The URL opens in the browser
2. The entire line is selected
3. The mouse cursor flickers as insert cursor over the entire window (especially title, menu and tabs)

New debug info:

Notepad++ v7.8.4   (32-bit)
Build time : Jan 29 2020 - 01:33:47
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS Name : Windows 10 Enterprise (64-bit) 
OS Version : 1803
OS Build : 17134.1304
Plugins : CustomizeToolbar.dll mimeTools.dll NppConverter.dll NppExport.dll NppSaveAsAdmin.dll

**Comment by kevinTOD** [comment]
I'm experiencing this cursor problem (line input rather than arrow over menu items) with the new release.

Notepad++ v7.8.5   (64-bit)
Build time : Mar  4 2020 - 11:08:34
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS Name : Windows 10 Home (64-bit) 
OS Version : 1909
OS Build : 18363.778
Plugins : DSpellCheck.dll mimeTools.dll NppConverter.dll NppExport.dll 

Closing Notepadd++ and reopening fixed the cursor

**Comment by Kleptoflax** [comment]
Original issue confirmed in v8.4.5 (64-bit) (Windows 7, admin mode both on and off). 
Furthermore, on top of the flickering pointer, mouse (movement) sensitivity is also affected (I run max pointer speed + enhanced precision, but it seemingly goes back to Windows default values when this bug hits).
