### ISSUE TITLE
Looking for a iPhone version

### ISSUE THREAD

**Issue by MomOf2Boys** [notepad-plus-plus/notepad-plus-plus#2011]
While looking for an iPhone version of Notepad++, I came across one, or so I thought.

Then I found out it wasn't. 

Notepad++ TextEditor by Terri Kaline
https://appsto.re/us/VMyAab.i

I would love to be able to use the Notepad++ on my iPhone.

Thanks!

**Comment by KamranMackey** [comment]
That is never going to happen. Notepad++ has and always will be a Windows-only application as far as I know.

**Comment by scootergrisen** [comment]
I don't think this qualifies as an issues but i would like to see a page being made where people could write what platform they would like to see Notepad++ on.
And where questions like this would be answers like:
Q: Will Notepad++ be available on iPhone
A: Of course not

So when people want to know other people could redirect to that page with the answers.

**Comment by milipili** [comment]
It makes sense to have n++ on macOS and Linux, but on iPhone not really sure. iPad maybe... But anyway it would be better to target those platforms before anything else.
