### ISSUE TITLE
Function List - JavaScript

### ISSUE THREAD

**Issue by shimscharf** [notepad-plus-plus/notepad-plus-plus#2012]
Hi all,
I've decided to add my changes to the Function List for javascript, to help you in your own developement. I believe it works better than the current inbuilt way, particularly for jQuery and other libraries. Let me know your thoughts?

```
        <parser id="js_function" displayName="Javascript" commentExpr="((/\*.*?\*)/|(//.*?$))">
            <function
                mainExpr="((^|[\(\){};:=,\s])function(\s+[$_\w]*|\()|(?:[$_A-Za-z][\w_$]*\s*\.\s*(|prototype\s*\.)\s*[$_A-Za-z][\w_$]*\s*|[$_A-Za-z][\w_$]*\s*)[=:]\s*\(*(?:function(\s+|\()))"
                displayMode="$className->$functionName">    
                <functionName>
                    <nameExpr expr="(?<=function)\s+[$_A-Za-z][\w_$]*|[$_A-Za-z][\w_$]*\s*[=:]"/>
                    <nameExpr expr="[$_A-Za-z][$_\w]*"/>
                </functionName>
                <className>
                    <nameExpr expr="[$_A-Za-z][$_\w]*\s*\.\s*"/>
                    <nameExpr expr="([$_A-Za-z][$_\w]*)*"/>
                </className>
            </function>
        </parser>
```

**Comment by Snuwerd** [comment]
I added it, but it gives me an error:

XML parsing error at line 135:
StartTag: invalid element name

Line 135 is the one with <nameExpr expr="(?<=function)\s+[$_A-Za-z][\w_$] etc.

**Comment by shimscharf** [comment]
I assume you replaced the original <parser id="js_function" block?
If not, just comment out the original block using html comments:

**Comment by Snuwerd** [comment]
Yes, I did comment out the other js parser. Now I tried removing it, also doesn't work. Can you send your entire parser file maybe?

Date: Sat, 25 Jun 2016 03:12:17 -0700

**Comment by shimscharf** [comment]
[SHIMfunctionList.txt](https://github.com/notepad-plus-plus/notepad-plus-plus/files/333022/SHIMfunctionList.txt)

rename file to functionList.xml
within your user\appData\roaming\notepad++\ directory

**Comment by Snuwerd** [comment]
Well, the weird thing is that now i get an error that there is content after line 86, when i save it. But if I just keep it as it is and load it in, it works. The functionlist for jquery looks nice so thanks for that!

**Comment by shimscharf** [comment]
Welcome !
When saving, ensure it is encoded as utf8. Without BOM

**Comment by Snuwerd** [comment]
I did save it as UTF-8 without BOM

**Comment by shimscharf** [comment]
Strange!
At least it works  :)

**Comment by MAPJe71** [comment]
You need to HTML-encode the less-then character within an attribute value, like so:

```xml
        <parser id="js_function" displayName="Javascript" commentExpr="((/\*.*?\*)/|(//.*?$))">
            <function
                mainExpr="((^|[\(\){};:=,\s])function(\s+[$_\w]*|\()|(?:[$_A-Za-z][\w_$]*\s*\.\s*(|prototype\s*\.)\s*[$_A-Za-z][\w_$]*\s*|[$_A-Za-z][\w_$]*\s*)[=:]\s*\(*(?:function(\s+|\()))"
                displayMode="$className->$functionName">    
                <functionName>
                    <nameExpr expr="(?&lt;=function)\s+[$_A-Za-z][\w_$]*|[$_A-Za-z][\w_$]*\s*[=:]"/>
                    <nameExpr expr="[$_A-Za-z][$_\w]*"/>
                </functionName>
                <className>
                    <nameExpr expr="[$_A-Za-z][$_\w]*\s*\.\s*"/>
                    <nameExpr expr="([$_A-Za-z][$_\w]*)*"/>
                </className>
            </function>
        </parser>
```

**Comment by MetaChuh** [comment]
please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins if you update from version 7.5.9 or below.
if your issue still persists, and it is still of relevance to you, please feel free to file a new issue as easy to understand and reproducible as possible.

thank you for your help and best regards.

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
(no extra account is needed, just use your github account to sign in)
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)
