### ISSUE TITLE
The autocomplete for factory-set pairs only works on new/clean lines.

### ISSUE THREAD

**Issue by EmanNo1** [notepad-plus-plus/notepad-plus-plus#2019]
This issue has been present in the last 5 or so versions. When there is no text to the right of the cursor the auto complete (), [], {}, works perfectly. When there is text to the right of the cursor the closing character is rarely is added.

For example, if I have the code " oFlle.open() " and I want to add " rsData("filename") " inside the (). N++ will not add a ) when I type rsData(.

I think logic was added to examine the text to the right and determine if the closing pair is needed.

Can an option be added to the preferences to override the logic and and have N++ insert the closing character no matter what is to the right of the cursor?

**Comment by devnull69** [comment]
I second this. I just opened another issue and it is really annoying for a developer to have this different than in the previous versions. Can you please do something about that?

**Comment by MetaChuh** [comment]
please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins if you update from version 7.5.9 or below.
if your issue still persists, and it is still of relevance to you, please feel free to file a new issue as easy to understand and reproducible as possible.

thank you for your help and best regards.

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
(no extra account is needed, just use your github account to sign in)
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)
