### ISSUE TITLE
Multi-editing: move with arrows

### ISSUE THREAD

**Issue by majicomajico** [notepad-plus-plus/notepad-plus-plus#2021]
When you point multiple cursors and then you use the arrows you lose the selection

**Comment by MetaChuh** [comment]
please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins if you update from version 7.5.9 or below.
if your issue still persists, and it is still of relevance, please feel free to file a new issue as easy to understand and reproducible as possible.

thank you for your help and best regards.

**Comment by sasumner** [comment]
@majicomajico This is an aspect of Notepad++ controlled by Scintilla.  When Notepad++'s Scintilla component is updated, this functionality will be improved.  Please watch for a change.log for Notepad++ that indicates Scintilla has moved to a newer version, and retest this functionality after that release.
