### ISSUE TITLE
Sort as integers doesn't work correctly for lines with two integers

### ISSUE THREAD

**Issue by vgiotsas** [notepad-plus-plus/notepad-plus-plus#2025]
Sorting lines as integers (Edit > Line Operations > Sort Lines as Integers Ascending) should produce the following output:
2 3
2 4
2 10
2 20

Instead it produces the following output:
2 10
2 20
2 3
2 4

Namely, after the first value it switches to lexicographic sorting instead of numerical. My Notepad++ version is v6.9.2 on Windows 7,

**Comment by nrecker** [comment]
It seems that behavior has changed to no longer differentiate based on integers after the first, but I can't find any later issue which mentions "Sort Lines as Integers". I would like to implement sorting by as many integers as exist at the beginning of the line. May I be assigned to this issue please?
