### ISSUE TITLE
Still no working Dspellchecker

### ISSUE THREAD

**Issue by un1versal** [notepad-plus-plus/notepad-plus-plus#2026]
**Im not on Windows 10** When using Windows, I use **Windows 7** with **Notepad++ 6.9.2** however I have read #427, and have moved the dll from the disabled folder and can use Dspellchecker.

However the main issue is when I add new words to the dictionary, these changes are 100% lost, 100% of the time, since these are re-occurring words often used, this is really a put off. 

its a little silly that the only alternative spellchecker is utterly useless as it is incomplete and requires further programs to be installed... So I wont even go there.

I would have thought that this would be a basic feature readily available/maintained or offered during first install/upgrade with an advanced text editor such as Notepad++,. I know its hard to get things done in opensource due to its voluntary nature, but would hope someone with the required skills would find it in their heart to finally, after months to kick this in...

Ill happily provide more information just no idea what or how to tbh, just let me know what you need and how to get that information and Ill post it ASAP.

Thanks.

**Comment by dail8859** [comment]
This would be best posted to the DSpellCheck issue tracker.

**Comment by un1versal** [comment]
Fair comment, do you know if anyone has already?

**Comment by un1versal** [comment]
Well here goes nothing https://github.com/Predelnik/DSpellCheck/issues/81
