### ISSUE TITLE
Feature request: BigData

### ISSUE THREAD

**Issue by Novo** [notepad-plus-plus/notepad-plus-plus#2027]
Compared to UltraEDIT, Notepad++ cannot handle very large files / search n replace, consuming much Memory (for example a 1GB big LogFile). Any idea how to deal with very large files?

**Comment by icegood** [comment]
i should say more: it even gives up comparing to windows notepad when dealing big files. Operations which fail so far with file of about 200Mb:
1) convert from unix to windows end line format
2) pasting text of about 1mb in the end.
3) goes to the end (ctrl+end)
4) navigationg there via up/down arrows.

**Comment by clfsoft** [comment]
npp can't handle 5m json file. it just freeze.

**Comment by MetaChuh** [comment]
please update your notepad++ to the latest 64 bit version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins if you update from version 7.5.9 or below.
if your issue still persists, and it is still of relevance to you, please feel free to file a new issue as easy to understand and reproducible as possible.

thank you for your help and best regards.

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
(no extra account is needed, just use your github account to sign in)
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)
