### ISSUE TITLE
Bugs in changing Encoding.

### ISSUE THREAD

**Issue by zviezdiulej** [notepad-plus-plus/notepad-plus-plus#2028]
New file created in ANSI Encoding. Every time I change encoding to UTF with BOM (menu Encoding -> Convert to UTF-8-BOM) active caret moves to the middle of text (in 5-6 lines file content). Sometimes, this action removes all file content.

Action in Windows 7 x64 Home Premium.

**Comment by Gabr-F** [comment]
I think it can be considered duplicate of issue #2017

**Comment by zviezdiulej** [comment]
That's right.
