### ISSUE TITLE
Some translation entries are missing

### ISSUE THREAD

**Issue by c-sanchez** [notepad-plus-plus/notepad-plus-plus#203]
There are many dialogues of notepad++ that are not available in the XML to be translated.
The second image is a curious bug that I saw, I show it with a gif.

http://s6.postimg.org/oqtw1tkj5/npp_translations0001.jpg
http://s6.postimg.org/o2l1ivltd/npp_translations0002.jpg
http://s6.postimg.org/3jzc5amnl/npp_Recent_Files_Gif.gif
http://s6.postimg.org/f7osm3mep/npp_translations0003.jpg
http://s6.postimg.org/wz0f0k1td/npp_translations0004.jpg
http://s6.postimg.org/68u4vbs4x/npp_translations0005.jpg
http://s6.postimg.org/tgof460xd/npp_translations0006.jpg
http://s6.postimg.org/ldq8sugc1/npp_translations0007.jpg
http://s6.postimg.org/4fr8706y9/npp_translations0008.jpg
http://s6.postimg.org/djpn7g8j5/npp_translations0009.jpg
http://s6.postimg.org/7lbtx7pkh/npp_translations0010.jpg
http://s6.postimg.org/jfjkuunu9/npp_translations0011.jpg
http://s6.postimg.org/4ib3tualt/npp_translations0012.jpg

**Comment by Tmp341** [comment]
Probably, there are untranslated lines in the lang file. I don't have any of them in Turkish, for example.

**Comment by c-sanchez** [comment]
I'm not sure they're untranslated lines in the file, as I can't get any of these mentioned in the XML, exept npp_translations0003.jpg, as I was translating based on "english npp 6.7.5 xml" as I was translating based on 6.7.7(the base english xml) that only adds this new line (Restore Recent Closed File)
Anyway, I've seen the same texts untranslated in Turkish, Including the bug on "Recent Files" text (first gif)
http://s6.postimg.org/p1odhvi29/npp_turkish_example01.gif
http://s6.postimg.org/tc31dgn5d/npp_turkish_example02.gif
http://s6.postimg.org/ho8ziwy0h/npp_turkish_example03.gif
http://s6.postimg.org/eiodspfe9/npp_turkish_example04.gif

Please check the the most recent english.xml
https://github.com/notepad-plus-plus/notepad-plus-plus/blob/master/PowerEditor/installer/nativeLang/english.xml

**Comment by Tmp341** [comment]
Which OS you're using?

**Comment by c-sanchez** [comment]
I'm using Windows XP SP3.

**Comment by Tmp341** [comment]
Design is different than mine, so that's why i asked your OS.
I hope somebody will find a solution.

**Comment by c-sanchez** [comment]
Heh, me too.
Here leave more lines that do not have lines to translate in english.xml
http://s6.postimg.org/gq1t83zg1/npp_translations0013.jpg
http://s6.postimg.org/pwk3ve4oh/npp_translations0014.jpg
http://s6.postimg.org/nujmh56pd/npp_translations0015.jpg
http://s6.postimg.org/tjzv1gcvl/npp_translations0016.jpg

And another curious bug, similar to "Recent Files" bug.
see the "Acoplar" "Dock"
http://s6.postimg.org/pc52spbg1/npp_Weird_Bug02.gif
and how you may notice "Dock" already has its corresponding translation, but not "Undock" on the english.xml.

**Comment by prclx323800** [comment]
These words (or at least some of them) are directly printed without checking the language file. So translating them is impossible unless the source code is changed.

By the way, I'd like to offer a pull request but my terminal examination is coming in 11 days...

**Comment by Tmp341** [comment]
Just as i thought. They are hardcoded :smile:

**Comment by c-sanchez** [comment]
Thanks for the replies guys.
More lines without translation possible
http://s6.postimg.org/gl42lu8tt/npp_translations0018.jpg
http://s6.postimg.org/7elryk3ld/npp_translations0019.jpg

and another wird bug :stuck_out_tongue:
http://s6.postimg.org/vwdvmg65t/npp_Weird_Bug03.gif

**Comment by chcg** [comment]
@c-sanchez Could you check which of your findings are still open with 7.6.2. Multiple changes in the meantime made more texts available for translation. As the images are not available any longer this issue seems outdated otherwise and I would close it as no further work is possible without new input.

**Comment by MetaChuh** [comment]
closed due to outdated missing translation issue (6.7.7)
