### ISSUE TITLE
Drag and drop both files and folders doesn't open anything

### ISSUE THREAD

**Issue by tersers** [notepad-plus-plus/notepad-plus-plus#2037]
A few days ago I noticed Notepad++ fails to open a combination of folders + files. During a train ride I devoted some time to fixing this issue, and I have a small pull request ready to go. The behaviour in the pull request now opens the folders in the directory viewer and the immediate directory files in editor windows.

**Comment by donho** [comment]
The current Current behaviour should be kept.
I will add an error message to notice users to disable Folder as Workspace dropping mode in order to enable the old feature. should be kept - please
