### ISSUE TITLE
Line ending encoding sounds like a Mexican restaurant

### ISSUE THREAD

**Issue by breyed** [notepad-plus-plus/notepad-plus-plus#2038]
On a Windows installation, in the status bar, the defaults encoding shows `Dos\Windows`. At least it's a well-lit restaurant with good views. :-) Still, the text would be better as `DOS/Windows`, or still better, given that its 2016, just `Windows`. A side benefit is that the slash grammar police won't get you.

There's also the issue that the encoding names displayed on the status bar don't match the ones in the context menu. They should be harmonized.

**Comment by ybungalobill** [comment]
Or just use "CR LF", "CR" and "LF". Shorter, unambiguous, and does not presume that LF can't be used on Windows.
