### ISSUE TITLE
Important return value ignored in Notepad_plus::process

### ISSUE THREAD

**Issue by ariccio** [notepad-plus-plus/notepad-plus-plus#204]
For the case `NPPM_GETCURRENTWORD`, one code path calls `lstrcpyn` (which itself is [*very evil*](https://randomascii.wordpress.com/2011/10/08/dangerous-documentation-part-1copying-strings/)) and then blindly returns `TRUE`:

```
					lstrcpyn((TCHAR *)lParam, str, wParam);
					return TRUE;
```

....but if `lstrcpyn` fails, the buffer in `lParam` is **NOT** null-terminated! Thus, a calling function will overrun the buffer.

**Comment by ariccio** [comment]
@milipili this is really not an enhancement, as it could cause all sorts of nasty buffer overruns.

**Comment by dail8859** [comment]
@ariccio Are you that pedantic you are concerned about a label? I certainly wouldn't consider it a bug...

**Comment by ariccio** [comment]
If `lstrcpyn` guaranteed null termination, then I could tolerate it, (partly) because callers could use this function without first zero initializing, and later sanity checking. Returning `TRUE` when the buffer isn't initialized isn't just lying, it's cause for Very Bad Things, if not an actual security bug.

**Comment by milipili** [comment]
A bug is a problem encountered by the user. The label "enhancement" can be seen as something more generic.

However, as explained in #207, this issue will be closed and reused for upcoming changes.
