### ISSUE TITLE
remove the snakes

### ISSUE THREAD

**Issue by jmichae3** [notepad-plus-plus/notepad-plus-plus#2040]
pythons are nasty. they bite and strangle at the same time. I and others don't like the idea of that. 
https://github.com/notepad-plus-plus/notepad-plus-plus/tree/master/scintilla/scripts
https://github.com/notepad-plus-plus/notepad-plus-plus/tree/master/scintilla/test
https://github.com/notepad-plus-plus/notepad-plus-plus/tree/master/scintilla/qt/ScintillaEdit
https://github.com/notepad-plus-plus/notepad-plus-plus/tree/master/scintilla/qt/ScintillaEditPy
 	Deep Black.xml
 	MossyLawn.xml
 	Obsidian.xml maybe, I just don't like black in my editor
 	Zenburn.xml
  BeSpin.xml

to learn how to use the cmd shell, help to list commands, and /? gives detailed help on individual commands like set /? and for /? and if /? and it does require cr+lf. also look at mingw-w64 compiler for 64-bit target compiler. I am currently waiting for them to finish some important bug fixes after their vacation. they have a mailing list.

**Comment by dail8859** [comment]
There's no need to remove the Python code. Nobody is forcing you to use the themes and many other use them.

Please try to construct more coherent messages issues.
