### ISSUE TITLE
change the url to the C# pluginpack on https://notepad-plus-plus.org/contribute/plugin-howto.html

### ISSUE THREAD

**Issue by kbilsted** [notepad-plus-plus/notepad-plus-plus#2042]
a newer much improved version can be found at https://github.com/kbilsted/NotepadPlusPlusPluginPack.Net 

it works for visual studio 2015 and is much less low-level than the UFO-version that is linked to at https://notepad-plus-plus.org/contribute/plugin-howto.html

**Comment by dail8859** [comment]
:+1:

**Comment by kbilsted** [comment]
Any problems adding the url to the  notepad++ homepage @donho  ?  @dail8859  can verify that its  solid work I've put many hours into.

**Comment by Ekopalypse** [comment]
done, can be closed -> see https://npp-user-manual.org/docs/plugins/#in-other-languages
