### ISSUE TITLE
Find in files is slow

### ISSUE THREAD

**Issue by turbanoff** [notepad-plus-plus/notepad-plus-plus#2043]
I love Notepad++ feature "Find in files". I use it a lot.
But I have noticed that speed of this feature is not good.
I compared it with grep (from cygwin) speed.
237 files 10 MiB each.

`grep -nrT 39262268 *` took 5 sec
`Find in files` took 40 sec

**Comment by dail8859** [comment]
Keep in mind that when Notepad++ searches files it has much more overhead than say grep would. It has to load it into a Scintilla document and use Scintilla's search options/features to do the actual searching.

To be clear I'm not stating it can't be improved at all...I certainly wouldn't argue if it was faster ;)

**Comment by nmpetkov** [comment]
The reason is that during search it is displayed every file in a window.
It was fast, but at one version it was introduced this window, and now is slow.
Please make a option to disable this and to return to old fast search!

**Comment by mirh** [comment]
#3562 and #4553 are probably good starting points.

**Comment by donho** [comment]
> To be clear I'm not stating it can't be improved at all...I certainly wouldn't argue if it was faster ;)

:)
