### ISSUE TITLE
[Feature Request] List JSON collections "_id" property into Function List.

### ISSUE THREAD

**Issue by diogocasado** [notepad-plus-plus/notepad-plus-plus#2045]
When dealing with JSON files to be imported into mongodb for example, it would be super nice to see a Function List being populated with all objects with "_id". Example bellow:

Functions: MyObj1, MyObj2

```Json
{
	"_id": "MyObj1",
	"property": {
	}
}
{
	"_id": "MyObj2",
	"property": {
	}
}
```

**Comment by MAPJe71** [comment]
Add the following to your FunctionList.xml and restart Notepad++

In the **\<associationMap\>**-node:

      <association langID="57" id="json_syntax" />

In the **\<parsers\>**-node:

      <parser id="json_syntax" displayName="JSON for MongoDb import" commentExpr="(?m-s)#.*?$" >
        <function mainExpr="&quot;_id&quot;\s*:\s*&quot;[\w]+&quot;\s*," >
          <functionName>
            <nameExpr expr=":\s*&quot;\K[\w]+" />
          </functionName>
        </function>
      </parser>

**Comment by MAPJe71** [comment]
It would be nice if you let us know whether the parser worked for you and when so you can close the issue.
Thanx

**Comment by diogocasado** [comment]
@MAPJe71 Thank very much!

That's why I use Npp. Awesome.

I removed the last comma from mainExpr though. It can be an empty object.

Thanks!
