### ISSUE TITLE
Feature request: Collapse individual case in switch statement in C and C++

### ISSUE THREAD

**Issue by sshahu-qualitrol** [notepad-plus-plus/notepad-plus-plus#2046]
![switch](https://cloud.githubusercontent.com/assets/19792561/16575781/715c4830-42a8-11e6-9892-4d9a3c6fac15.PNG)

collapsing each individual case will help when there are a lot of statements under each case.

**Comment by MetaChuh** [comment]
please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins if you update from version 7.5.9 or below.
if your issue still persists, and it is still of relevance, please feel free to file a new issue as easy to understand and reproducible as possible.

thank you for your help and best regards.
