### ISSUE TITLE
Missing Styles Missing Plugin

### ISSUE THREAD

**Issue by ghost** [notepad-plus-plus/notepad-plus-plus#2048]
Hello,

I have been using notepad++ for several years without any problems. I like it a lot.

But since upgrading to the latest version 6.9.2 I have had a few recurring problems.
(edit. Thinking i had these probs even before upgrade, thought upgrade would fix)
1. Opening a file by double clicking it, does not open it with any language syntax highlighting.
2. If I open the file using the context menu "edit with notepad++" it usually opens with highlighting (not always) but the textfx plugin is not present.
3. Smart highlighting seems to turn itself on and of from one session to the next.
4. Sometimes if I open 1(one) file, the files that I had open in the last session are also opened.

I tried an uninstall and reinstall 6.9.1 instead but still seem to have same probs,

**Comment by MetaChuh** [comment]
please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins if you update from version 7.5.9 or below.
if your issue still persists, please feel free to file a new issue as easy to understand and reproducible as possible.

thank you for your help and best regards.
