### ISSUE TITLE
N++ automatically closes  XML Processing Instruction tag

### ISSUE THREAD

**Issue by sirzooro** [notepad-plus-plus/notepad-plus-plus#2050]
I have realized that fix for #1999 should be more general, it should also properly handle XML Processing Instructions (https://en.wikipedia.org/wiki/Processing_Instruction). They have following syntax: `<?PITarget PIContent?>`. You can check if tag name starts with question mark, this should be enough to detect them.

**Comment by dail8859** [comment]
Can processing instructions also show up in HTML or is it restricted to XML only?

**Comment by sirzooro** [comment]
I see that HTML 4 specification mentions them in appending B https://www.w3.org/TR/html4/appendix/notes.html#h-B.3.6
Spec for HTML 5 does not mention them at all.
