### ISSUE TITLE
Bug notepad ++ in case of up-dating of a plug-in.

### ISSUE THREAD

**Issue by 7950** [notepad-plus-plus/notepad-plus-plus#2054]
Today, 06,07,2016 I opened notepad ++ (6.6.7 I understand that old, but doesn't want to check a bug in new) and saw a window of up-dating of a plug-in. without thinking I clicked "ok" - it was downloaded, gave 2 windows. 1 with one button "ok" and over it the 2nd, with the specifying "It Is Necessary to Restart Notepad ++". 1 I couldn't read wasn't in time). 2 - I couldn't click anything, it was disabled, as a result - generally couldn't make anything. It was necessary to close through "Ctrl + Alt + Del". After start, everything was updated as it is necessary, and was clarified: the file that it was open udadlitsya. COMPLETELY, and it was the file with "Passwords to the server". Also there was it in "SINGLE COPY". Fortunately for me by the adjacent machine there was older copy. I VERY MUCH HOPE THAT the BUG is FIXED in the latest version.

Sorry, if wrote not there where it is necessary.

**Comment by donho** [comment]
outdated.
