### ISSUE TITLE
Notepad++ crashes on latest (14379 and 14383) builds of Windows 10 preview

### ISSUE THREAD

**Issue by lowdeca** [notepad-plus-plus/notepad-plus-plus#2057]
Notepad++ 6.9.2 is terminating on the latest two builds of Windows 10 preview.
Host is now running Windows 10 Professional x64 (14383) on a system with 32Gb memory, with C & D internal, and E,F,G,H,I,,L & M drives connected via USB3 hub.

I can find no pattern to the failures. Some times I can use it heavily for an extended period, and at other times it will terminate after a couple of minutes.  Also, if I I leave notepad++ up and running in the background it will just terminate, even though I have not touched it for some time.  I suspect that it is related to the file system monitoring for changes, but can not prove it.

Of course now I am submitting a report, it is being stable for the moment.

**Comment by ZaphodBIII** [comment]
Notepad++ crashes always in case it is used for None-Admin Account of Windows 10. Maybe related to Plugin HexEditor.

**Comment by cmeriaux** [comment]
can you report the "debug information" ?
You may confirm your bug without any plugins

**Comment by ZaphodBIII** [comment]
Notepad++ v6.9.2
Build time : May 18 2016 - 00:34:05
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10
Plugins : HexEditor.dll HTMLTag_unicode.dll JSLintNpp.dll JSMinNPP.dll mimeTools.dll NotepadSharp.dll NppConverter.dll NppExport.dll NPPJSONViewer.dll PluginManager.dll XMLTools.dll

**Comment by ZaphodBIII** [comment]
The crash was related to HexEditor Plugin in my case.
The crash only happened if Notepad++ is used for a None-Administrator and local-only Windows 10 account.
After starting it takes approx. one minute to get an error messages:
"C:\Program File (x86)\Notepad++\plugins\HexEditor.dll
Failed to load
The plugin is not compatible with the current version of Notepad++"

(Note: it works fine in case of Administrator and signed in account)

**Comment by ZaphodBIII** [comment]
Host is Windows 10 Pro x64, Version 1607, OSBuild 14393.51, 8GB, i5

**Comment by donho** [comment]
Outdated.
