### ISSUE TITLE
Multi monitor and Search Window

### ISSUE THREAD

**Issue by abzalov** [notepad-plus-plus/notepad-plus-plus#2058]
Search Window is saved the last position and its monitor.

This is not very convenient when opened several instance of N++ (each in its own monitor). In this case Search Window showed on the last used monitor. Often not that monitor where the instance of N++ is located (instance caused the search).

It would be better if the dialog is appeared on the same monitor where the caused dialog N++ instance is located.

**Comment by MetaChuh** [comment]
please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins if you update from version 7.5.9 or below.
if your issue still persists, and it is still of relevance, please feel free to file a new issue as easy to understand and reproducible as possible.

thank you for your help and best regards.
