### ISSUE TITLE
Is this a bug?

### ISSUE THREAD

**Issue by OrkhanAlikhanov** [notepad-plus-plus/notepad-plus-plus#2065]
In [this ](https://github.com/notepad-plus-plus/notepad-plus-plus/blob/master/PowerEditor/src/ScitillaComponent/ScintillaEditView.cpp#L2300) function we have these lines in order to calculate the last line's number if Word wrap is enabled:

```
for (int i = firstVisibleLineVis + 1; i <= lastVisibleLineVis; ++i)
{
    int lineDoc = (int) execute(SCI_DOCLINEFROMVISIBLE, i);
    if (lineDoc == numLinesDoc)
        break;
    if (lineDoc == prevLineDoc)
        lastVisibleLineVis++;
    prevLineDoc = lineDoc;
}
```

but I think it should be:

```
for (int i = firstVisibleLineVis + 1; i <= lastVisibleLineVis; ++i)
{
    int lineDoc = (int) execute(SCI_DOCLINEFROMVISIBLE, i);
    if (lineDoc == numLinesDoc)
        break;
    if (lineDoc == prevLineDoc)
        firstVisibleLineVis ++;
    prevLineDoc = lineDoc;
}
lastVisibleLineVis = firstVisibleLineVis;
```

Because by increasing `lastVisibleLineVis` we go out of Lines on screen but in wrap mode it should be less, from `firstVisibleLineVis` to the last wrapped line.

**Comment by dail8859** [comment]
There would appear to be a bug somewhere (most likely what you pointed out) since the width increases before it needs to in some cases with word wrap turned on.

**Comment by donho** [comment]
Outdated
