### ISSUE TITLE
Improving types casts

### ISSUE THREAD

**Issue by NN---** [notepad-plus-plus/notepad-plus-plus#2066]
I suggest to add more restrictive casts in addition to standard C++ ones.
Example of casts which I have implemented some years ago [pointer_cast, safe_reinterpret_cat](https://rsdn.ru/forum/src/1871852.1) .
Their intend to be more restrictive by checking size and types in compile time.

Surely, the implementation can be greatly simplified since we are now with C++11.

**Comment by donho** [comment]
improved
