### ISSUE TITLE
Uncommenting (Ctr+Q) the first line of a file moves the caret to EOF

### ISSUE THREAD

**Issue by rascob** [notepad-plus-plus/notepad-plus-plus#2067]
The issue is there when both of the following apply:
-The first line is a single-line comment (e.g. starts with "//" in C)
-When Ctrl+Q is pressed, the caret is at the 1st character of the file
If both apply, after pressing Ctrl+Q, the 1st line is successfully uncommented, but the caret moves to the end of the file.

**Comment by A-R-C-A** [comment]
This issue is fixed here #2031.
