### ISSUE TITLE
Guidelines for language (atm PHP) code insight/syntax

### ISSUE THREAD

**Issue by Krzysiu** [notepad-plus-plus/notepad-plus-plus#2069]
I'd like to ask about guidelines of adding/modifying PHP code insight and syntax. The issue here is that such guidelines doesn't exist and I think they should be present, so users, including me, could propose better patches without controversies. If I'll be allowed by don Don to create something like that, I'm willing to write one, basing on the answers.

I'm not talking about some überlaw! I mean literally **guides** - helpers, not strict rules. In the square bracket I give my "vote".

I think that other languages may need something like that as well. Maybe I could create directory (where?) like `syntax_guides` and put there .md with basic points. That's the least important thing, anyways.

1) PHP 5.5 and newer functions, like - array_columns() - could I propose patch with such functions [yes]

2) PHP 7 only functions - is it ok to add it? [neutral]

3) Should two new operators in PHP7 be added? This is only syntax coloring issue, so I think it's less controversial that 2) point. I'm talking about `??` and `<=>`

4) Now most controversial, I guess. Functions deprecated since a long time _and_ removed in PHP7 (some deprecated aren't removed and devs change their mind, so I'm talking only about these already removed!), like `mysql_…` function set. Is it worth to keep it? I say [remove].

So what don Don thinks? And what's other opinion? If that's the wrong place to ask for it, then sorry. I'll move myself if you'd tell me where.

**Comment by MAPJe71** [comment]
AFAIK there's no PHP coding involved in Notepad++ so I don't understand where you'd want to add/modify.
Furthermore, inquiries and discussions are more suited for the [Community](https://notepad-plus-plus.org/community/) IMO.

**Comment by Krzysiu** [comment]
Read the title, please. Thanks for the tip, I'll ask there.

**Comment by MAPJe71** [comment]
I read the title. It appears to be to cryptically for me :)

**Comment by dail8859** [comment]
If you are talking about the PHP lexer then those changes need made to the Scintilla project. As for C++ coding guidelines it is all in the CONTRIBUTING.md file.
