### ISSUE TITLE
Write overrun in DefaultDirectoryDlg::run_dlgProc (security bug!)

### ISSUE THREAD

**Issue by ariccio** [notepad-plus-plus/notepad-plus-plus#207]
`nppGUI._defaultDirExp`, declared as:

```
TCHAR _defaultDirExp[MAX_PATH];	//expanded environment variables
```
is passed to `ExpandEnvironmentStrings`, as:

```
::ExpandEnvironmentStrings(nppGUI._defaultDir, nppGUI._defaultDirExp, 500);
```
...but `ExpandEnvironmentStrings`, declared as:

```
WINBASEAPI
_Success_(return != 0 && return <= nSize)
DWORD
WINAPI
ExpandEnvironmentStringsW(
    _In_ LPCWSTR lpSrc,
    _Out_writes_to_opt_(nSize, return) LPWSTR lpDst,
    _In_ DWORD nSize
    );
```

...expects that it can write all the way up to `nppGUI._defaultDirExp[499]`. Cue buffer overrun!

**Comment by milipili** [comment]
Thanks for all those opened issues to improve the code quality of n++. However, since we have to see the "big" picture, a major code refactoring is currently underway. And because of this refactoring, the issues will be marked as "won't fix". Not because they must not be fixed, but because we prefer to spend the short time we have to provide a more appropriate architecture as quickly as possible for upcoming features.

**Comment by ariccio** [comment]
Ummmm....ok? I think I understand. I'd love to hear more about this major code refactoring, as I've [tried to do such (on a smaler scale) myself, only to be rejected](https://github.com/notepad-plus-plus/notepad-plus-plus/pulls?q=is%3Apr+is%3Aclosed+author%3Aariccio).

**Comment by MAPJe71** [comment]
@milipili could you and/or @donho share some info on the big picture, refactoring and maybe the time-line?

**Comment by milipili** [comment]
First, we should improve the codebase to simplify the development and to provide more code isolation and flexibility. Then it will be easier to add new features requested by users

**Comment by ariccio** [comment]
....and robustness, too? Getting Notepad++ Microsoft SDL-compliant?

**Comment by milipili** [comment]
And robustness too.

**Comment by donho** [comment]
We will use Yuni as lib for preparing the cross-platform application:
https://github.com/libyuni/

**Comment by ariccio** [comment]
Cross-platform? Wait what?

**Comment by rugk** [comment]
Did anything result in that "cross-platform" statement here? Is it even tracked anywhere?
