### ISSUE TITLE
Jump to Next Mark (not bookmark) command?

### ISSUE THREAD

**Issue by Xpyder** [notepad-plus-plus/notepad-plus-plus#2070]
I'm looking for something like F3 and F2 but for the text marked using the "Find and Replace > Mark (Tab)" feature.

I've tried googling but no luck so far.

**Comment by cmeriaux** [comment]
Hello,
I found the solution few years ago. Now, i always use it.
Here is the solution :  

- mark a word with "search/mark all/using 1st style"
- navigate forward or backward with the function "search/Jump Up/1st style" of "search/jump down/1st style"

I mapped the function "mark all/n style", "jump up" and "jump down" to different shortcut. It's perfect.

**Comment by sasumner** [comment]
@Xpyder , @cmeriaux 's solution is a good one, but he didn't cover your exact case in his explanation.  Your case is when you "red-mark" some text using the Mark function.  For this case, the JumpUp or JumpDown submenus have a "Find Style" choice...use this.  Yes, I know it is not a great name for it. :)
