### ISSUE TITLE
Feature request: option to ensure file ends with newline

### ISSUE THREAD

**Issue by thdoan** [notepad-plus-plus/notepad-plus-plus#2073]
This would be a useful feature to have when you select Unix line endings. In fact, it would be even better if Notepad++ automatically ensures the file ends with a newline (`\n`) only when it's using Unix line endings.

If anyone has a solution they are happy with currently, please comment.

**Comment by MetaChuh** [comment]
please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins if you update from version 7.5.9 or below.
if your issue still persists, and it is still of relevance, please feel free to file a new issue as easy to understand and reproducible as possible.

thank you for your help and best regards.

**Comment by sasumner** [comment]
@thdoan Why limit this to only Unix line-endings. There should be an option to ensure that all files end with their proper line-ending.

For other references, see:
https://notepad-plus-plus.org/community/topic/14527/last-line-has-crlf-or-not
https://notepad-plus-plus.org/community/topic/16785/remove-duplicate-numerical-lines
