### ISSUE TITLE
Highlight gaps

### ISSUE THREAD

**Issue by BitSums** [notepad-plus-plus/notepad-plus-plus#2075]
![vskmmued1kipmztewkiua](https://cloud.githubusercontent.com/assets/20419550/16767408/00a41d20-4848-11e6-9ef6-f267df24aacb.jpg)

How to increase the fucking point?

gaps -> space

**Comment by BitSums** [comment]
![default](https://cloud.githubusercontent.com/assets/20419550/16767605/e7dbbb58-4848-11e6-8ea0-38347f435e25.png)

**Comment by dail8859** [comment]
Currently it is not possible to increase the size without the use of a plugin.

**Comment by BitSums** [comment]
Plugin?
Please, more information can be?

**Comment by dail8859** [comment]
Closed by e10847b429ea7799425e9e88925cb208ba14d4b6 as this makes the spaces much more visible.
