### ISSUE TITLE
Fail to search non-printable range by regexp

### ISSUE THREAD

**Issue by SergeyTru** [notepad-plus-plus/notepad-plus-plus#2076]
Notepad++ (version 6.9.2) finds all words by regexp "[\u0010-\u0010]+" or "[\u0011-\u0011]+", but should find only non-printable characters.
The search works correctly (finds nothing) on "\u0010+" or "\u0011+".

**Comment by MetaChuh** [comment]
please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins if you update from version 7.5.9 or below.
if your issue still persists, and it is still of relevance, please feel free to file a new issue as easy to understand and reproducible as possible.

thank you for your help and best regards.
