### ISSUE TITLE
'Operators 2' does not have a styler

### ISSUE THREAD

**Issue by breisfeld** [notepad-plus-plus/notepad-plus-plus#2077]
For a user-defined language, the 'Operators & Delimiters' | 'Operators 2' does not have its own Styler. Therefore all operators (1 and 2) have the same style. Introducing separate 'OPERATORS1 ' and 'OPERATORS2' lines into the xml file does not work at this point.

**Comment by MetaChuh** [comment]
please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins if you update from version 7.5.9 or below.
if your issue still persists, and it is still of relevance, please feel free to file a new issue as easy to understand and reproducible as possible.

thank you for your help and best regards.
