### ISSUE TITLE
Wrong screen position after tab switch (with word wrap)

### ISSUE THREAD

**Issue by brain-HUN** [notepad-plus-plus/notepad-plus-plus#2078]
I would like to report an annoying issue when using the word wrap feature. If you switch between documents while editing and you got the word wrap feature enabled, then the screen position is off.

Here is how to reproduce it:
Open a document with very long lines in it. Like this: <unwrapped.png>
Turn on word wrap and move to the end of the document. Like this <wrapped.png>
Then switch to another open document and switch back. And it will look like something like this: <wrapped_after_tabswitch.png>

Expected: The screen should go back to exactly where it was.
Result: The screen is off. The cursor is not visible on the screen. This doesn't happen when word wrap is off.
![unwrapped](https://cloud.githubusercontent.com/assets/20425110/16778127/d10cbbc4-486c-11e6-830a-a6b7f36b9116.png)
![wrapped](https://cloud.githubusercontent.com/assets/20425110/16778126/d10c9e82-486c-11e6-8852-7d16a2c88976.png)
![wrapped_after_tabswitch](https://cloud.githubusercontent.com/assets/20425110/16778128/d10fcbde-486c-11e6-9535-25eccfcb73ba.png)

**Comment by qdinar** [comment]
additional material:
[np-pp-sroll-position-bug.txt](https://github.com/notepad-plus-plus/notepad-plus-plus/files/908122/np-pp-sroll-position-bug.txt)
try to put cursor to "123" and change tab and return back to this tab. it does not open proper position with 1366 768 display, in win10.

**Comment by MaximilianKohler** [comment]
Ugh, a year later and still not fixed ._.

This is a pretty major issue... Definitely going to be looking for alternatives. Is there an older version or something we can use for now?

**Comment by ChrisAkridge** [comment]
Also running into this issue with N++ 7.5.4 32-bit.

**Comment by Arczi008TV** [comment]
N++ 7.5.9 (64bit) = no issue
N++ 6.0.0 (64bit) = jumping..

**Comment by sasumner** [comment]
@Arczi008TV 

>N++ 6.0.0 (64bit) = jumping..

So you are saying that for you this complaint is against version 6.0?

**Comment by brain-HUN** [comment]
I have just checked it v7.8.1 (64 bit) and the issue is still present.

**Comment by Arczi008TV** [comment]
I mean its happened again from v6.0 and up, they reverted fix because of some performance issue.  That is stupid..
