### ISSUE TITLE
Syntax Highlighting No longer works in version 6.7.9 inside of <script> and <style> tags

### ISSUE THREAD

**Issue by danielwells** [notepad-plus-plus/notepad-plus-plus#208]
In and HTML file, the syntax highlighting no longer works for the CSS and JavaScript that is embedded in an HTML file

**Comment by julian025** [comment]
I have the same problem

**Comment by didsun** [comment]
Yes, I have the same file in PHP.

**Comment by Rikk** [comment]
Note: commit https://github.com/notepad-plus-plus/notepad-plus-plus/commit/c0cd924c1ebb9dc0daccf4f28f5c305ac65a2b4a only fixed script blocks, style blocks are still in need.

**Comment by donho** [comment]
Fixed.

**Comment by LMLB** [comment]
`<style>` tags are still broken for me in v6.9.
