### ISSUE TITLE
php variables not correctly highlighted if contains __ near a point

### ISSUE THREAD

**Issue by madebycambiamentico** [notepad-plus-plus/notepad-plus-plus#2080]
examples:
```php
echo 'dir'.__DIR__; //__DIR__ correctly highlighted
echo 'dir'. __DIR__; //__DIR__ correctly highlighted
echo __DIR__ ."dir"; //__DIR__ correctly highlighted
echo __DIR__."dir"; //__DIR__ not highlighted!!!!!
```
whenever a variable `__XXX__` is placed before a point `.` it loses the highlight (blue in standard template)

**Comment by dail8859** [comment]
I can verify that it does not correctly highlight it in the last case. However this appears to be a Scintilla issue that is still present in SciTE v3.6.6, see below. 

![capture](https://cloud.githubusercontent.com/assets/3694843/16903661/49a4f1e4-4c52-11e6-8856-ac49d74c60da.PNG)

It would probably be best to report this issue to Scintilla's [issue tracker](https://sourceforge.net/p/scintilla/bugs/).
