### ISSUE TITLE
Cant paste huge amount of text from clipboard

### ISSUE THREAD

**Issue by trsiddiqui** [notepad-plus-plus/notepad-plus-plus#2081]
I am trying to paste generated logs from some application that I copy from another application. I am able to paste the text in notepad but not in notepad++. In fact, notepad++ doesn't do anything when I paste it. When I select an already present text and try pasting, it removes the text and do nothing then.

**Comment by dail8859** [comment]
Define "huge amounts of text", 100KB, 1MB, 100MB, more? Also, try disabling all of your plugins.

**Comment by trsiddiqui** [comment]
Over 18MB (thats the size I see when I save the text file)

**Comment by dail8859** [comment]
I haven't been able to reproduce it. Any other info you can provide would be helpful, file encoding, syntax, etc.

**Comment by MetaChuh** [comment]
please update your notepad++ to the latest 64 bit version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins if you update from version 7.5.9 or below.
if your issue still persists, and it is still of relevance, please feel free to file a new issue as easy to understand and reproducible as possible.

thank you for your help and best regards.
