### ISSUE TITLE
Feature request: Please collapse multiple RELOAD dialogs into one

### ISSUE THREAD

**Issue by quole** [notepad-plus-plus/notepad-plus-plus#2082]
I sometimes work with a large number of files that are updated all at once by an external program. Then I get one modal dialog after another popping up saying:

> **Reload** This file has been modified by another program. Do you want to reload it?

This is fine for one file, but it's tedious to click through a whole bunch of these popups.

Any chance these could be "collapsed" into a single dialog that lists all the files which have been changed?

This is related to #1484 / #848 (which both ask for a simpler "Reload all" button solution, which would be a good start)

It would good to also have a setting in preferences to always automatically reload tabs (at least ones which have not been dirtied/modified within notepad++).

<img width="1280" alt="notepadpp-reload" src="https://cloud.githubusercontent.com/assets/800133/16830044/c59cf8e8-49df-11e6-8ed1-05b62f3b6d7a.png">
Screenshot related (you get to see multiple dialog boxes at once by tabbing out and back into notepad++, otherwise they pop up sequentially)

**Comment by modulexcite** [comment]
If it helps, you can ask notepad++ to silently update the file without prompting you to do so using the following options (highlighted in the blue box).

![notepad _preferences_2016-07-14_08-13-11](https://cloud.githubusercontent.com/assets/12729391/16839055/df8e3c7a-499a-11e6-97b7-5181c1eda9fb.png)

**Comment by quole** [comment]
Thank you.

I did look for this setting but didn't find it at the time. It has no wording in common with the "reload" dialog that pops up. I imagine many users must go through a lot of frustration before they find the setting too (considering how many posts there are on this topic)

The main suggestion of this post (to collapse the dialogs into one) still isn't addressed though, nor the suggestion from other posts to have an "reload all" button.

Also, does "update silently" cause dirtied files to be reloaded? Perhaps the answer could be given in its tooltip in future.

**Comment by Duellmann** [comment]
@donho , first of all, thank you very much for a great product, N++ rocks, it's an everyday can't-do-without tool!

Imho this issue has been closed prematurely, and there are a number of duplicates and variations of the same issue.

The setting "Update silently" might reduce the number of prompts depending on scenario, but it doesn't solve the main problem of this issue that for all dirtied files, we are still getting one modal prompt per file, which is annoying and error-prone.

Looking at the cluster of related issues below, I think this would deserve some developer attention. Any improvement will be appreciated.

- #3320 Rework multiple reload prompts into one (same as this issue #2082)
- #848 Implement Reload All Files Button on Reload Prompt
- #3349 Don't open multiple reload prompts for *same* file
- #3160 Don't focus last reloaded file (also very irritating, e.g when you're coming from opening another file, then reload prompts divert you to an unrelated file)
- #1087 (same as #3160)
- #3599 (same as #3160)
- #3138 Display multiple modal reload prompts as a non-modal notification bar in each file tab instead (that looks like a very nice idea, but maybe modal prompt should still be optionally available for added safety/ error-prevention)
-  #745 app-modal reload or file gone prompt prevents dropping files (solutions e.g. #3138 non-modal per-tab notification bar, or tab-modal alert but that's just partial solution, I guess you really need to allow drop action to finish before showing any modal alerts)
- #1481 Per-file toggle of reload auto-detection (per file opt-out for reload prompt)
- #1564 Highlight externally updated tabs and show prompt only when tab is focused (But please make "blinking tab" optional, that can create a more annoying horror of having to click on every tab to get rid of blinking tabs)
- #3333 Cancelling Save-As dialogue triggers reload prompts for other files
- #2186 Option to *monitor* a file when *reload* is detected 
- #1653 Add an event to allow plugins to detect reloading/reloaded
- #2405 Files opened from a `subst` drive continually show "file changed" dialog

And finally, "File gone" prompts seem to suffer from the same design problems:
#1116 Dozens of "File doesn't exist" warnings prevent closing window (even with Update Silently enabled) and shown incorrectly with Network Share
