### ISSUE TITLE
Error message incorrect if big file can't be opened due to other open files

### ISSUE THREAD

**Issue by TilmanK** [notepad-plus-plus/notepad-plus-plus#2083]
Please analyse this together with #1890 since this might be a very similar issue.

I'm opening very large files in notepad++:

If I open a 340MB file, I cannot open another 280MB file since "File is too big to be opened in notepad++" is shown.

If I open the 340MB file and then close it, the 280MB file will open.

=> The error message is inconsitent. Notepad++ should check, if the file could be opened, if other files were closed and present a better error message to the user (it took some minutes to figure this out for me...)

**Comment by MetaChuh** [comment]
please update your notepad++ to the latest 64 bit version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins if you update from version 7.5.9 or below.
if your issue still persists, and it is still of relevance, please feel free to file a new issue as easy to understand and reproducible as possible.

thank you for your help and best regards.
