### ISSUE TITLE
Saving super-hidden files: fails the first time then success

### ISSUE THREAD

**Issue by ccleaud** [notepad-plus-plus/notepad-plus-plus#2085]
*\* The problem **
When saving a super hidden file (for instance, desktop.ini, genereted by Windows Explorer when you customize icon of a directory), Notepad++ will this message, suggesting the user to switch to admin mode:

```
---------------------------
Save failed
---------------------------
The file cannot be saved and it may be protected.
Do you want to launch Notepad++ in Administrator mode?
---------------------------
Yes   No   
---------------------------
```

Clicking `No`the saving again will success.

*\* How to reproduce **
1. create an empry direcotry on your desktop
2. create a simple text file `data.txt`, then open a command prompt in that directory
3. type this command `attrib -a -r +s +h data.txt"`
4. open the file using Notepad++, wou'll need to manually type its name in the open dialog
5. append some characters in the file
6. try to save

**Comment by MetaChuh** [comment]
please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins if you update from version 7.5.9 or below.
if your issue still persists, and it is still of relevance, please feel free to file a new issue as easy to understand and reproducible as possible.

thank you for your help and best regards.
