### ISSUE TITLE
ANSI File: ASCII -> HEX can't convert 0xFF

### ISSUE THREAD

**Issue by ryanafleming** [notepad-plus-plus/notepad-plus-plus#2087]
When converting bulk text from an ansi based file that contains binary data, it appears that it can convert every ascii character except 0xFF. The character in my file is show as a ÿ

If I select a large amount of bytes to convert it will work fine unless this character is present in the selection, thus it will do nothing.

When I go to the conversion table (Plugins -> ASCII -> HEX) and paste the character in there, it appears to do the correct conversions in here, showing that the value is 0xFF etc. and can be pasted over the original character.

Converter version: 3.0
notepad++ version: 6.9. Build Feb 21 2016

**Comment by james-kosin** [comment]
I've also posted an issue on the Converter GitHub repository for the Notepad ++ plugin.

https://github.com/npp-plugins/converter/issues/2

No responses there either.  Can you check your version and see if the NUL character 0x00 HEX gets improperly converted to 0x20 when you go ASCII -> HEX?

**Comment by MetaChuh** [comment]
please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins if you update from version 7.5.9 or below.
if your issue still persists, and it is still of relevance, please feel free to file a new issue as easy to understand and reproducible as possible.

thank you for your help and best regards.
