### ISSUE TITLE
re-issuing #489 "n++ is blocking the folder.."

### ISSUE THREAD

**Issue by Petewg** [notepad-plus-plus/notepad-plus-plus#2088]
Hi,
the problem reported with https://github.com/notepad-plus-plus/notepad-plus-plus/issues/489 is still present (Np++ 6.92 - Win7 pro Sp1)
and can be easily reproduced with these steps:

1. Create a folder ->  x:\test
2. Create a .txt file inside -> test.txt
3. Open the file with Np++
4. Do some editing..
5. Save and Close **file**, but **keep Np++ open**
6. Try to **delete** `x:\test` folder -> **it fails** with message "The action can’t be completed because the file is open in another program"
7. Now Close Np++ and repeat step 6. -> **success!** (folder deleted)

Remarks: 

1. Seems that Np++ "forget" to release **folder** (not file) handle when closing file.
2. There is a [sysinternals console utility, named 'handle'](https://technet.microsoft.com/en-us/sysinternals/bb896655.aspx) that shows "which program has a particular file or directory open".  You can use it, from command prompt, just typing: `handle "test"` and see the result. It clearly states \[notepad++.exe\] (along with explorer.exe)

regards,

**Comment by dail8859** [comment]
I've tried quite a few times and also followed the steps in #489 but can't reproduce this at all. FYI my debug info...

```
Notepad++ v6.9.2
Build time : May 18 2016 - 00:34:05
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : ON
Local Conf mode : OFF
OS : Windows 7
Plugins : ComparePlugin.dll DoxyIt.dll DSpellCheck2.dll GuidHelper.dll LuaScript.dll mimeTools.dll NppConverter.dll NppExport.dll NppFTP.dll PluginManager.dll 

```

**Comment by Petewg** [comment]
Well, after running Np++ as *Admin*, I also couldn't  reproduce it.  So, not sure, anymore, if it's a Np++ problem or it's related with OS privileges or even something else.  (What was puzzling me was the fact that after closing Np++ I was able to delete folder). 
Anyhow, for now, although I've no spotted what's happening,  let's regard the issue as 'closed'. Thanks for you reply!
