### ISSUE TITLE
Feature Requests

### ISSUE THREAD

**Issue by sng843ndf86nd8** [notepad-plus-plus/notepad-plus-plus#2090]
Don please don't be stupid, implement these good changes into NP++. Not as plugins, but inside features, as it should be.
I'm highly flustrated over past months, I even stopped learn to program, because of this crap. Please code new features into NP++. They are great and everybody will appreciate it. Please think about it.

1, Ability to remove Auto-Inserted part of dual characters (parentheses, brackets, braces, other used defined), when you delete first part of it (manually written). So Auto-Delete of Auto-Inserted part, by deleting it’s first half.
For example you are going to write: print(someting),
but you make mistake and you write: print[
NP++'s Auto-Complete’s Auto-Insert will make it like this: print[], with cursor between brackets. Now it would be easy to press Backspace and delete it all, if feature would be there.

2, Deletion of transformed Tabbed whitespaces (Tabs replaced by spaces) by only one keyboard hit of Backspace/Delete. By ‘transfered’ I mean Tab Settings in Preferences - for example four spaces for python. If one Tab press, will do four normal spaces, would be useful to let user delete it by one press of Backspace, not four times (Backspace/Delete).

3, Resetting key bindings/keyboard shortcuts to default from GUI. Not by some manual magic manipulation within files.

4, Exclude numbers from Auto-Completion. Exclude user specific strings from Auto-Completion per file or default for anything opened.

5, Enlarge Find and replace window (ctrl + h) for more comfortable multi lines operating. This window has in right down corner an enlarge mark, but it does not work (windows 7 ultimate 32 bit).
And maybe bug: When occurs Tab whitespace from very beginning of the line pasted into text fields, it is longer than same Tab whispace in middle of that text field. Try select two lines in code, where both start Tabbed and paste it into window’s text fields. Second Tab will be shorter.

6, I can’t describe this feature in general, so here is an example:
Dock Function List window to the left part of screen, below Folder as Workspace window. When I double click on window’s header, it attaches to right part of screen and overlap Document Map window. When I move and resise window manually, it’s not directly embedded to NP++ enviroment. Like this: http://i.imgur.com/IBgufyZ.png
It is floating, so it’s overlapping Folder window. Is possible to do it by hardcode editing some inner setting files ?

7, Ability to select more than one file in Folder as Workspace feature (file explorer).
Example: It does not support Shift or Ctrl selecting more than one files to open. When I need open 5 files from one folder, where is other 20 files lets say, I would pick them with Ctrl and press Enter.

8, Ability to set preferred side window opened on each opening.
Example: NP++ behavior is keeping last constellation of modified things. Some settings, some window placements, keeping on top last used windows. For example when I quit NP++ with last thing opened as Snippet plugin: http://i.imgur.com/Age8Ifd.png, it will show it again on next app start. But I need show document map by default on each start like this: http://i.imgur.com/QGiWDPl.png. But this particulary one plugin is forcing NP++ to be primary always on top. We need feature setting in NP++ which would overwrite plugin’s setting and let NP++ pick his choice.

9, Verify NppExec’s plugin, because last time when I was installing it, I saw it’s not verified: http://i.imgur.com/7N3MOyF.png

Please man, just do it. It's all awesome things. 
Many people will be very thankful to you for it. 
Those new features are important for all beginners. Because they use NP++ as IDE also with NppExec combo. 
Thank you very much

**Comment by cmeriaux** [comment]
It's asked with so much kindness .....
What about contributing yourself ...

**Comment by dail8859** [comment]
> Verify NppExec’s plugin

This is an issue with the PluginManager and not Notepad++.

Also, please do not repost issues. Yes, I know this is slightly different so I will close the older issues you have created.

**Comment by d0vgan** [comment]
If I was the topic starter, I would edit the initial post to make it more kind and respectful.
I don't know why, but sometimes users feel free to demand something from an open source developer - as if the developer owes to them. But does an open source developer really owes to any user of his free product? I don't think so.
Apart from that, some of the proposals above look really worthwhile.

**Comment by donho** [comment]
@sng843ndf86nd8  please don't be stupid, implement these good changes into NP++ as PR, then I will consider to including of them.
