### ISSUE TITLE
[ENHANCEMENT] Highlight matches in “Find All in Current/Opened Document”

### ISSUE THREAD

**Issue by aaaxx** [notepad-plus-plus/notepad-plus-plus#2094]
This small enhancement would make the matches much easier to spot.

**Comment by MetaChuh** [comment]
please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins if you update from version 7.5.9 or below.
if your issue still persists, and it is still of relevance, please feel free to file a new issue as easy to understand and reproducible as possible.

thank you for your help and best regards.

**Comment by sasumner** [comment]
@aaaxx This is what the "Mark" feature is for, although it is only for the current doc.
