### ISSUE TITLE
Horizontal scrolling is not working with the mouse Logitech MX Master (and more?)

### ISSUE THREAD

**Issue by ArtificialTruth** [notepad-plus-plus/notepad-plus-plus#2096]
The first 2 seconds of scrolling works, then it breaks. Another scrollbar appears and moves, but doesn't move the open content. It works fine when moving the horizontal scrollbar with the mouse.

Screen recording of the issue: https://my.mixtape.moe/qzdode.mp4
Notepad++ v6.9.2
Build time : May 18 2016 - 00:34:05
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10 Pro 64 bit 
Plugins : none (it also happens when plugins are loaded)

Tested with a [MX Master](https://assets.logitech.com/assets/55435/2/mx-master-gallery.png) with built in scroll weel for horizontal scrolling.
Also running Logitech Options.

**Comment by bkvamme** [comment]
Can confirm this issue. Exact same as demonstrated in the video.

**Comment by ArtificialTruth** [comment]
Are you using the same mouse?

**Comment by bkvamme** [comment]
Yes, the Logitech MX Master.

**Comment by altendorferka** [comment]
Can confirm this issue.
Using the MX Master...

**Comment by looperhacks** [comment]
Can confirm using the horizontal scroll feature of the Logitech Performance MX. You can push the scroll wheel to the side with this mouse. It scrolls only a little bit, but the alternative scrollbar is still moving. If I push the scroll view repeatedly, every push scrolls a little bit.

**Comment by looperhacks** [comment]
This seems to be an issue with the Logitech software. I use the older setpoint software for my Performance MX and the scrolling issue disappears when I stop the tool.

**Comment by altendorferka** [comment]
can confirm: Deinstalled Setpoint, now horizontal scrolling works as expected :)

**Comment by bkvamme** [comment]
Are any of you using Logitech Options? I'll try to uninstall it later to
see if this affects it, but this is not a long-term solution for me as I
need to customize the buttons.

Hilsen / Best regards,
Bjarte Odin Kvamme

**Comment by altendorferka** [comment]
Yes, works with Logitech options here

**Comment by ArtificialTruth** [comment]
Just tried with Logitech Options installed (not running in foreground) - same behavior as in the video.
Then I opened it in the foreground, and the wheel worked as a zoom in/out instead, even though it's not set to that in Logitech Options (it's set to horizontal scrolling).

**Comment by gifford** [comment]
I'm also having the same issue with the same mouse, it still happens exactly the same as when this was reported a year ago.  Would be great to get a fix.  Let me know if I can provide any information that would be useful for reproducing/debugging.

**Comment by eliot1785** [comment]
I am having the same issue described here, with the Logitech MX Master. Glad to see I am not the only one. In my case it doesn't even move a little bit at the beginning, otherwise same issue.

FWIW I never had any software called "Setpoint" installed, and I have the issue regardless of whether Logitech Options is open or not.

**Comment by KvalheimRacing** [comment]
I had an issue with the mx master horizontal scrolling in atom, fixed it when I uninstalled setpoint 6.67.83

**Comment by seppisback22** [comment]
I have found a solution that worked for me:
Make own settings for notepad++ in Logitech options. Then select no action (don't know the exact word for it, in the german version it is "Kein") for the thumbwheel (not horizontal scrolling).
After that horizontal scrolling worked, but I don't know why :smile: 
Hope that also works for you

**Comment by ArtificialTruth** [comment]
Not working for me, unfortunately.

**Comment by eliot1785** [comment]
Me either.

**Comment by seppisback22** [comment]
Tried it on a second pc, didn't work there. So I don't really have an idea why it worked for the first one.

**Comment by siraajahmed** [comment]
Getting same issue. MX Master and Notepad++ v7.4.2 (64-bit) on Windows 10. Alternative scroll bar comes up but you can't side scroll! Need anymore info let me know.

**Comment by YourGamesBeOver** [comment]
Can confirm still an issue.  N++ v7.3.3 (32-bit), win10, MX Master

**Comment by nguyencuonginfo** [comment]
I have same issue with my Master 2S mouse and Notepad++ 7.5.3
Sometime it works, sometime it's doesn't. I have to close all documents on Notepad++, then open files on notepadd++ again to let it work.
I'm using logitech options software.
Please help!

**Comment by ravemir** [comment]
Can also confirm it is also happening for me on 7.5.3.

Although for a moment it was working, immediately before I upgraded from 7.2.2.

**Comment by KvalheimRacing** [comment]
@nguyencuonginfo we came to a conclution eralier that it's a bug in the software on logitech's side. ...So just buy a mad catz rat 9 bluethooth or something..

**Comment by nguyencuonginfo** [comment]
To all: I don't know why but it's working well with my notepad++ while i'm writing this comment :-o 
@KvalheimRacing It's too expensive solution  :D

**Comment by nguyencuonginfo** [comment]
Hi All,
I have new update, a temporary solution:

Step1: Open “Document Map” in notepad++ by “View”->“Document Map”.
http://www.mediafire.com/file/os5vos6zo8kbesa/temporary_solution_step1.jpg

Step2: Use Thumb Scroll in “Document Map” area, then move back to document, you will be able to use Horizontal Scroll feature.
http://www.mediafire.com/view/a7gl3aq63bd2fhk/temporary_solution_step2.jpg

Waiting for a complete solution from Notepad++, Logitech or pro member.

**Comment by ravemir** [comment]
Looks like it works, @nguyencuonginfo, although it took a couple of tries to work.

**Comment by szymonk92** [comment]
Any updates?

**Comment by Drtrider** [comment]
> Hi All,
> I have new update, a temporary solution:
> 
> Step1: Open “Document Map” in notepad++ by “View”->“Document Map”.
> http://www.mediafire.com/file/os5vos6zo8kbesa/temporary_solution_step1.jpg
> 
> Step2: Use Thumb Scroll in “Document Map” area, then move back to document, you will be able to use Horizontal Scroll feature.
> http://www.mediafire.com/view/a7gl3aq63bd2fhk/temporary_solution_step2.jpg
> 
> Waiting for a complete solution from Notepad++, Logitech or pro member.

This worked for me.

**Comment by KvalheimRacing** [comment]
Nice, I occasionally use sublime aswell. Are you using Sublime Text 2 og 3 (or others)?

**Comment by geominorai** [comment]
I have not tried on older versions but I am currently using latest v3.1.1.

**Comment by MetaChuh** [comment]
please report this issue to logitech.

thank you for your help and best regards.

**Comment by xiaozhaolhg** [comment]
the problem still exist with my mx master and notepad++ v7.6.6, 
however, the  temporary solution (https://github.com/notepad-plus-plus/notepad-plus-plus/issues/2096#issuecomment-353589166) provided by @nguyencuonginfo works.

**Comment by faizan1990** [comment]
https://www.youtube.com/watch?v=bUBJa1xp3ZA

**Comment by sasumner** [comment]
@faizan1990 Why is that video relevant?

**Comment by faizan1990** [comment]
@sasumner because it tells how to fix MX Master scrolling bug?

**Comment by gifford** [comment]
@faizan1990 The bug in that video is completely different than the bug described here.

**Comment by faizan1990** [comment]
@sasumner @gifford Apologies, misunderstood. I have removed my comment.

**Comment by gifford** [comment]
@faizan1990 No problem - there was no harm in sharing the video, I was just letting you know that it was a different issue.

**Comment by napstercc** [comment]
Im having the same issue with the master MX 3, why is this ticket closed? It seems unresolved.
Is it a logitech bug or a notepad++ bug?

**Comment by KvalheimRacing** [comment]
Haha, love that they havent fixed it on the "Oh so big improved" MX 3 mouse, haha. @napstercc as you can read above, if you take the time, it is a logitech issue. The issue persits across many applications like atom, notepad++ and across different platforms. So I bet logiteh essentially only changed the design from the 2s to the 3. I don't see any feature improvements, not a shock considering their lousy engineering. Despite that, still love the 2s though.

**Comment by geominorai** [comment]
I also notice this exact same bug happening on Notepad3 from https://github.com/rizonesoft/Notepad3 so there may be a common problem with how the horizontal scrolling is implemented.

**Comment by napstercc** [comment]
I've opened a ticket with Logitech, lets see how this goes...

**Comment by zw-gb** [comment]
This is not an issue with the mouse hardware or driver. I have continued to notice that horizontal scrolling is broken in a number of development software.
Notepad++ is having some sort of context issue with the way that the mouse is scrolling horizontally. Obviously the app picks it up because it shows a secondary scroll bar on top of the real one.
Someone need to log out what action is being picked up and map it to the appropriate scrolling function.
This occurs in Visual Studio: If you have more than one pane open and then switch to a "non-active" pane and try to scroll horizontally, it either does nothing or scrolls the wrong pane.
I have also noticed similar oddities in blender, vscode, brackets, and others.
It seems to me that devs (including Microsoft ones 😑) are not properly capturing the event from the os. Or, maybe, the os has an issue and isn't properly reporting the horizontal scrolling event, depending on how it's triggered.
I would look into this but I do not have the expertise to troubleshoot notepad++ as I do not have much expertise in C++.
Thanks.

**Comment by zw-gb** [comment]
I have found a workaround for Logitech MX devices.
In Logitech Options, set the horizontal scroll speed to the lowest option, it appears as though the acceleration to the scroll wheel is causing some of the issue.

**Comment by Banchio** [comment]
@zw-gb do you mean thumb wheel sensitivity option? Thanks!

**Comment by ravemir** [comment]
> I have found a workaround for Logitech MX devices.
> In Logitech Options, set the horizontal scroll speed to the lowest option, it appears as though the acceleration to the scroll wheel is causing some of the issue.

It does work for N++! Unfortunately not for VS Code, but luckily we have app specific settings, so at least this one is taken care of.

Thanks!

**Comment by zw-gb** [comment]
@Banchio Yes. I use the MX Ergo. It's kind of a cruddy workaround but it's the only thing that works for me at the moment.

**Comment by JeretSB** [comment]
Good to know. @zw-gb Thanks for chiming in! Sounds like Logitech needs to look into this.

**Comment by CastagnaIT** [comment]
this Issue should be reopened, the problem is not solved
if keeping the document map open the problem apparently disappears, a definitive solution should be found, somewhere in the code there will be an inadequate implementation

**Comment by VL4DST3R** [comment]
Came here to report the same problem. Seems to happen at random.

**Comment by KvalheimRacing** [comment]
> this Issue should be reopened, the problem is not solved
> if keeping the document map open the problem apparently disappears, a definitive solution should be found, somewhere in the code there will be an inadequate implementation

@VL4DST3R 

It's a logitech problem. Not an atom or notepad ++ issue

**Comment by VL4DST3R** [comment]
@KvalheimRacing then how come it happens only in np++? everything else that i've tried it in like different browsers, paint.net, photoshop, even torrent clients: work as intended?

**Comment by maisyk** [comment]
I have had this issue with the Logitec MX master 1, 2, 3 now the damn thing works fine in every other app apart from Notepad++ anyone got a clue where that secondary horizontal scroll bar is coming from when you actually scroll horizontally?

**Comment by lipchev** [comment]
Hey guys, I'm coming from #4720- so I guess I won't be bringing much of new to the discussion- but does anybody know if this is somehow related to the issue that I described in my previous comment- regarding the scrollbar also not working for my own WPF apps (not like the N++'s "not working" behavior)- I mean it is supposed to work right out of the box right? I mean.. is it my TV or is it my mouse?...cause I'm not changing my mouse- have you tried "Win+Shift+Left/Right" keystrokes for left/right gestures- ooh it's a game changer!

**Comment by Bronnieanthony** [comment]
I have the same problem with most applications.  It particularly frustrates me when using a web  browser with content such as that in a Sharepoint List with many columns.  I can confirm it is not browser related, nor is it Sharepoint related.  I seem to get the same problem replication as most,  works for a couple of seconds, or about two scrolls then unresponsive.

**Comment by inspiretk** [comment]
I got it working. Logitech MX Master 3. When installing the software Logitech Options: https://support.logi.com/hc/en-001/articles/360025297893 make sure you DONT install any of the predefined settings! Then when installed, test horizontal is working. If you dont like the default direction (like me), I then opened the software, went to Thumb Wheel direction, and changed it to inverted. I then set up the other apps as custom. So for my browser Chrome, to set this I went to All Applications on top right corner, and click Add application. ONLY add the app you want. DONT add their visual code as that dont work. Its the logitech software thats stuffing it up. I added chrome. THEN I go to select chrome, and change App specific Point and Scroll settings to custom for that app, and I change the Thumb wheel direction to Default. Good Luck Everybody.

**Comment by inspiretk** [comment]
Never mind, it stuffed up. After computer reboot, it stops working. If I now go to vscode, it works for a horizontal scroll once, then it stops working. If I kill vs code, reopen, it works once and stuffs up. What a shame

**Comment by yur1xpp** [comment]
I still having this issue to this date, although temporary solution by @nguyencuonginfo works. How come logitech still haven't fix this in 2020. We need to spam them with this issue.

**Comment by VL4DST3R** [comment]
I still do not understand how is this a logitech issue... The mouse should provide an input, like any other peripheral. Its the program's job to interpret it and do whatever action is intended for it to be (in this case, horizontal scrolling).

I also decided to test this again today and i can seem to reproduce the issue, no matter what i try. Can anyone confirm? Maybe it's been fixed in a recent update.

**Comment by KvalheimRacing** [comment]
@VL4DST3R For some years ago I used a lot of time investigating into this problem, and after a lot of research I came to the conclusion that it's a firmware issue with logitech. Solutions has been to open a chrome page and then use the scroll whell, edit the scrolling speed etc. I came to this conclusion together with many others, and the problem exists across many platforms, ex atom beeing one of them. We raised an issue with logitech, but they didn't care. I actually tried reahing out to people at Logitech, but they didn't care. So I like many others, moved on and put my priorities elsewhere

**Comment by andreizah97** [comment]
i have the same issue

**Comment by dnanusevski** [comment]
Hi all
I think think that i have found the solution.
First close all the tabs in the notepad++. Leave only one tab opened.
After that close the notepad++.

Then turn it on again. Only one tab should exist. Try side scroll. Hope that somebody will find this helpful

**Comment by StarpTech** [comment]
Uninstalling "Logitech Options" solved it!

**Comment by lucasmshepherd** [comment]
I did everything here to no avail.  I fixed it by installing with none of the premade settings but until I turned off this setting I was unable to get horizontal scrolling to work properly across all apps:
![image](https://user-images.githubusercontent.com/6415520/105418641-4ef7ad80-5bf2-11eb-9af0-5bac4449a562.png)

**Comment by Drtrider** [comment]
> I did everything here to no avail. I fixed it by installing with none of the premade settings but until I turned off this setting I was unable to get horizontal scrolling to work properly across all apps:

I tried the setting both on and off, and still refuses to scroll in most apps.

**Comment by lucasmshepherd** [comment]
> > I did everything here to no avail. I fixed it by installing with none of the premade settings but until I turned off this setting I was unable to get horizontal scrolling to work properly across all apps:
> 
> I tried the setting both on and off, and still refuses to scroll in most apps.

Dang!  Well I am on my second day still working great in all apps including n++ (knock on wood)

**Comment by VL4DST3R** [comment]
It used to work for me well up till very recently when i upgraded and rebuilt my pc. Now again i'm getting the ghost scrollbar, regardless of my initial lead of having the document preview sidebar enabled helping in this regard.

**Comment by Gunshin82** [comment]
@dnanusevski, thanks for your comment, this help me out. It seems that this issue occurs when we have the option "Remember current session for next launch" enabled and that one of the tabs from previous session has the horizontal scroll bar. 

I've tested removing all files with horizontal scroll bar, closing Notepad++, reopening Notepad++ and horizontal scrolling worked fine.

**Comment by DietrichChristopeit** [comment]
For me, the only thing that worked is **_uninstalling the Logitech Options software_**. 
Afterwards the scroll wheel worked as expected - **shamefully _not_ in Excel** - this I guess can only be achieved by translating the horizontal scroll signals into "KEY-LEFT/-RIGHT" or "SHIFT/TAB" or similar. However, this can only be done through Logitech's Options Software unless you write your own piece of software.

Of course, principally cool features like inverting the horizontal scroll wheel and the notifications of key stati (if you use an Logitech keyboard as well) are not available anymore. 

It's really a shame that Logitech doesn't fix this for such pricey products.

**Comment by avielc** [comment]
Just wanted to report this issue still exists, 
MX 3 Masters, Windows 10, 64Bit latest version of NP++
the only work around I found is horizontal scrolling in chrome (it was open at this time) even if there's nothing to scroll
and then moving back to NP++ - 
Apparently as mentioned way at the start with the document map - 
if I horizontal scroll on the top menu section it create that "ghost" scrolling. 
Hope this gets a solution

**Comment by Jmuniak** [comment]
> I still do not understand how is this a logitech issue... The mouse should provide an input, like any other peripheral. Its the program's job to interpret it and do whatever action is intended for it to be (in this case, horizontal scrolling).
> 
> I also decided to test this again today and i can't seem to reproduce the issue, no matter what i try. Can anyone confirm? Maybe it's been fixed in a recent update.

Still an issue 6/22/21. I was sent a replacement MX3 to test against my original MX3. its still a software issue on logitech's side of things.

**Comment by Jmuniak** [comment]
> For me, the only thing that worked is **_uninstalling the Logitech Options software_**.
> Afterwards the scroll wheel worked as expected - **shamefully _not_ in Excel** - this I guess can only be achieved by translating the horizontal scroll signals into "KEY-LEFT/-RIGHT" or "SHIFT/TAB" or similar. However, this can only be done through Logitech's Options Software unless you write your own piece of software.
> 
> Of course, principally cool features like inverting the horizontal scroll wheel and the notifications of key stati (if you use an Logitech keyboard as well) are not available anymore.
> 
> It's really a shame that Logitech doesn't fix this for such pricey products.

But then Flow doesn't work between computers.

**Comment by VL4DST3R** [comment]
> 
> 
> > I still do not understand how is this a logitech issue... The mouse should provide an input, like any other peripheral. Its the program's job to interpret it and do whatever action is intended for it to be (in this case, horizontal scrolling).
> > I also decided to test this again today and i can't seem to reproduce the issue, no matter what i try. Can anyone confirm? Maybe it's been fixed in a recent update.
> 
> Still an issue 6/22/21. I was sent a replacement MX3 to test against my original MX3. its still a software issue on logitech's side of things.

Yep, could reproduce it as well, no idea how i managed it to get it working back when i made that post. I think i just got used to always using word wrap and i also bought a bigger screen eventually so this is no longer that much of an issue.

**Comment by VL4DST3R** [comment]
I'll also state again what i said in my original post: no matter what bullshit logitech software does to the input from the mouse, the fact that only NP++ is affected by this, and that it literally makes the UI display a **different scrollbar** when the bug is in effect, shows that it's definitely somethting on the way the program itself handles the input/ what container exactly it is attempting to scroll.

Maybe the framework used for getting the input or navigating the interface? i don't know.

Regardless, this ticket should at the very least be reopened and marked as "cannot fix" or similar so as to serve as a known, still present issue, for other people to be aware of.

**Comment by sasumner** [comment]
>Regardless, this ticket should at the very least be reopened and marked as "cannot fix" or similar so as to serve as a known, still present issue, for other people to be aware of.

I'll add a "won't fix" label for you.

**Comment by VL4DST3R** [comment]
That's... great. Maybe do the same for #3256?

**Comment by terrellgf** [comment]
Same issus with MX Master 3

**Comment by Jmuniak** [comment]
VS Code and Obsidian are two other apps its affecting

**Comment by lipchev** [comment]
Same with foobar2000

**Comment by VL4DST3R** [comment]
> 
> 
> VS Code and Obsidian are two other apps its affecting

strange, i just checked and it doesn't seem to be an issue with the regular VS

**Comment by DietrichChristopeit** [comment]
> I'll also state again what i said in my original post: no matter what bullshit logitech software does to the input from the mouse, the fact that only NP++ is affected by this, and that it literally makes the UI display a **different scrollbar** when the bug is in effect, shows that it's definitely somethting on the way the program itself handles the input/ what container exactly it is attempting to scroll.
> 
> Maybe the framework used for getting the input or navigating the interface? i don't know.
> 
> Regardless, this ticket should at the very least be reopened and marked as "cannot fix" or similar so as to serve as a known, still present issue, for other people to be aware of.



> I'll also state again what i said in my original post: no matter what bullshit logitech software does to the input from the mouse, the fact that only NP++ is affected by this, and that it literally makes the UI display a **different scrollbar** when the bug is in effect, shows that it's definitely somethting on the way the program itself handles the input/ what container exactly it is attempting to scroll.
> 
> Maybe the framework used for getting the input or navigating the interface? i don't know.
> 
> Regardless, this ticket should at the very least be reopened and marked as "cannot fix" or similar so as to serve as a known, still present issue, for other people to be aware of.

I have to disagree with the statement that ONLY notepad is affected by this behaviour. Excel and Sql Navigator show the same defect.  Sqlnavigator also has this ghost scrollbar and Excel simply does nothing.
However, Logitech's way of mapping the scroll wheel movement to key-combination pressed events in connection with  the underlying framework is somehow instantiating a second scrollbar on top of the existing, both pointing to the same event handler. This would possibly explain why the movement of the bar and it's ghost is somewhat erratic: I think of getting the same input from two different sources handled by the same handler reacting on whichever input arrives first.
However, this is just from the top of my head, I have not investigated anything of it.

**Comment by alibarut** [comment]
Notepad++ run as Administrator. Issue resolved for me.

**Comment by Gunshin82** [comment]
@alibarut 
Wow!! Thanks, this also works for another app I'm using, DBeaver.

**Comment by kabelux** [comment]
@alibarut Thank you so much! Obsidian is now working too with "Run as Admin"

**Comment by mjanofsky** [comment]
Had the same issue. I downloaded and ran the beta Logi Options+.  I set up NP++ application settings and turned off the horizontal scroll wheel... set it to Do Nothing. Tried it; it did nothing as expected.  I then set it to Horizontal Scroll, and poof... it works.  No more overlaid mystery scrollbar.

**Comment by worldsdream** [comment]
I have been having this issue for a long time.

I removed Logitech Options (https://www.logitech.com/en-us/software/options.html)

I installed the Logi Options+ (https://www.logitech.com/en-us/software/logi-options-plus.html)

Everything works as expected. No more horizontal issues in Notepad++ with Logitech MX Master 3.

Even though the Logi Options+ is shown as "Beta", I can tell that it works perfectly over here on my machine. 

You can also check the Logi Options+ changelog over here: https://support.logi.com/hc/en-us/articles/1500005516462

It should have all the features you already had in Logitech Options.

I hope this helps others.

Please let others know if it worked and which Logitech MX Master version you tried it on.
