### ISSUE TITLE
EOL info not updated after on-change reload

### ISSUE THREAD

**Issue by glebsts** [notepad-plus-plus/notepad-plus-plus#2099]
Hi, thank you for awesome software. Looked for similar issue but did not find one.
Npp 6.9.2
I have a file i.e. with Windows EOL, I open it with Npp and convert EOLs to Unix, save it, but don't close the file. Then I change file with other editor (for me it happened to be sourcetree .gitignore adding) back to Windows EOLs, save. Switch back to Npp window, it detects that file is changed, asks me if I want to reload it. I say Yes, and it is reloaded with Windows EOLs, but menu still shows Unix EOLs as disabled and Windows as enabled.
Guess EOL information is not updated after reload. If I close file and reopen it, menu updates well.

**Comment by GitMensch** [comment]
Same issue here with NPP 6.9.2. Additional information: the EOL information isn't updated as long as the file is open:

* create text file with Unix EOL
* open and save text file with Wordpad (reads both unix and win EOL but always stores with win EOL)
* NPP wants to reload, decline
* manually reload (File->Reload): EOL stays on unix

**Comment by dail8859** [comment]
Closed by 46d0f12c3e687c83efbaa04f7ebd95616678226c
