### ISSUE TITLE
Syntax Highlighting Heredoc,NowDoc PHP

### ISSUE THREAD

**Issue by ByHH** [notepad-plus-plus/notepad-plus-plus#210]
The error is mine

**Comment by walkinlake** [comment]
the new flexible heredoc/nowdoc syntax in php 7.3 (see https://wiki.php.net/rfc/flexible_heredoc_nowdoc_syntaxes or https://laravel-news.com/flexible-heredoc-and-nowdoc-coming-to-php-7-3) is not highlighted properly
