### ISSUE TITLE
style configurator > search result > selected line

### ISSUE THREAD

**Issue by limitlessnine** [notepad-plus-plus/notepad-plus-plus#2104]
Notepad++ 6.9.2 no longer perform "selected line" styling for rows in search result panel.
I think all versions higher than 5.6.8 exhibit this behavior. 

I have tested the styling rule defined at ( style configurator > search result > selected line ) is not functional in version 6.9.2 but works correctly in version 5.6.8.

Please review the visual snapshots and commentary at imgur:
http://imgur.com/a/4aaeQ

Additional Notes:
Using Windows 7

**Comment by MetaChuh** [comment]
please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins if you update from version 7.5.9 or below.
if your issue still persists, and it is still of relevance, please feel free to file a new issue as easy to understand and reproducible as possible.

thank you for your help and best regards.

**Comment by sasumner** [comment]
Verified as working in 7.6.6.
