### ISSUE TITLE
Enlarge the search dialog to cover the whole screen

### ISSUE THREAD

**Issue by valtih1978** [notepad-plus-plus/notepad-plus-plus#2106]
Normally, you set up a lot of search parameters and start the search. Normally, the search dialog must collapse when you start the search to leave some space for the user to see the located text. I see that the Notepad has chosen the opposite track -- you have a huge search dialog, with many options that refuses to collapse when I start the search. This results in my view is always obscured and I cannot see the most of search results when navigate over the with Next button. Can you leave only the Next/Prev+Expand button when you jump to a search result?

**Comment by MetaChuh** [comment]
please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins if you update from version 7.5.9 or below.
if your issue still persists, and it is still of relevance, please feel free to file a new issue as easy to understand and reproducible as possible.

thank you for your help and best regards.
