### ISSUE TITLE
Add support for X++ language 

### ISSUE THREAD

**Issue by kevinkabatra** [notepad-plus-plus/notepad-plus-plus#2107]
Please accept and I can make the necessary changes to the language file.

**Comment by ezzkht** [comment]
Check this out:
https://jrabascal.wordpress.com/2014/07/07/creating-user-defined-language-x-into-the-notepad/

**Comment by MetaChuh** [comment]
> Please accept and I can make the necessary changes to the language file.

closed due to missing follow up pull request.
