### ISSUE TITLE
BUG: Local Conf mode: OFF even the option is set during setup

### ISSUE THREAD

**Issue by logg-sar** [notepad-plus-plus/notepad-plus-plus#2108]
Hi there

I need an automatically installed NP++ with all files in one Directory!

When I start the setup and choose **"Don´t use %APPDATA%"** some files are still in %APPDATA%
The **_doLocalConf.xml_** is present (and btw will not be removed at deinstallation - this is also an error), but ?/Debug Info shows "Local Conf Mode ; OFF"

Second question:

What parameter accepts the NPP-Installer. I dont need the Auto-Update Function and would like to uncheck it during automated install. The installer is not very cooperative there...

**Comment by MetaChuh** [comment]
please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins if you update from version 7.5.9 or below.
if your issue still persists, and it is still of relevance, please feel free to file a new issue as easy to understand and reproducible as possible.

thank you for your help and best regards.
