### ISSUE TITLE
external file modification is not detected anymore

### ISSUE THREAD

**Issue by shaforostoff** [notepad-plus-plus/notepad-plus-plus#2112]
since i have updated notepad++ to 6.9.2 it doesn't suggest me reload a file from disk if it was changed externally.

1) open a file in notepad++
2) open it in another text editor, change it and save it
3) switch back to notepad++ with alt+tab

**Comment by dail8859** [comment]
Did you check your settings under `Setting > Preferences > MISC. > File Status Auto-Detection`?

Please provide [more info](https://github.com/notepad-plus-plus/notepad-plus-plus/blob/master/CONTRIBUTING.md#reporting-issues).

**Comment by dail8859** [comment]
Closing due to lack of info.
