### ISSUE TITLE
ctrl+shift+Z dont work in ubuntu

### ISSUE THREAD

**Issue by z-avanes** [notepad-plus-plus/notepad-plus-plus#2114]
hi
redo shortcut ctrl+shift+Z dont work in ubuntu 16.04

**Comment by dail8859** [comment]
With as little information as you provided there is really nothing to actually help you solve your issue. See [here](https://github.com/notepad-plus-plus/notepad-plus-plus/blob/master/CONTRIBUTING.md#reporting-issues).

I'm assuming you are using Wine? Are you also using VirtualBox? It could easily be one of those catching the shortcut as well.

**Comment by z-avanes** [comment]
sorry for poor information
my atom version is 1.8.0
no i am not useing wine and virtualbox , ubuntu is my main operation system
ctrl+z and ctrl+y work correcly but ctrl+shift+Z dont work

**Comment by z-avanes** [comment]
i am find where is problem
atom-autocomplete-php package overwrite ctrl+shift+Z !!!

**Comment by dail8859** [comment]
FYI this is the issue tracker for Notepad++ not Atom.
