### ISSUE TITLE
[Files] Notepad++ Defaults at \n line encodings for .txt, .py, and .bat files (which Windows and github does not like.

### ISSUE THREAD

**Issue by AraHaan** [notepad-plus-plus/notepad-plus-plus#2115]
It seems that Notepad++ defaults at `\n` it would be nice if there was a configuration setting that can change it to `\r\n` if you perfer it over `\n`.

This is a total issue when you have to reopen it in Windows Notepad and then respace it out like you see in Notepad++, and then reopen it in Notepad++ change view in ANSI to View in UTF-8 and then click convert to ANSI (does not work all the time especially when the file is empty / a python module).

**Comment by AraHaan** [comment]
hmm Seems to fix itself if you make a new file and then open it up in Notepad from Windows. Add a new line, save it. then open it in Notepad++, Copy everything from the file with ``\n`` to the new file. save it and it has ``\r\n`` then and replace the old file with the new one.

**Comment by dail8859** [comment]
> it would be nice if there was a configuration setting

`Settings > Preferences > New Document > Format` is for new documents. Notepad++ will also auto-detect line endings if there is already text in the file.

**Comment by AraHaan** [comment]
Also changing the line encodings of a already Existing file sometimes fails too keeping it at \n when you try to convert it to \r\n encodings.

**Comment by dail8859** [comment]
Not sure I follow. Is the setting I referenced not doing what you need? Can you provide an exact set of steps and your current settings for the format?

**Comment by AraHaan** [comment]
Lets say I open a UTF-8 encoded file and want to convert it to ANSI. It has the Encode in YTF8 option checked. And when and if I change it to ANSI before selecting to convert it to ANSI it then fails to change the line encodings of the opened file(s). All from the Encoding Menu.

**Comment by MetaChuh** [comment]
please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins if you update from version 7.5.9 or below.
if your issue still persists, and it is still of relevance to you, please feel free to file a new issue as easy to understand and reproducible as possible.

thank you for your help and best regards.

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
(no extra account is needed, just use your github account to sign in)
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)
