### ISSUE TITLE
Minor optimization on getCurrentFoldStates

### ISSUE THREAD

**Issue by OrkhanAlikhanov** [notepad-plus-plus/notepad-plus-plus#2118]
In [getCurrentFoldStates](https://github.com/notepad-plus-plus/notepad-plus-plus/blob/master/PowerEditor/src/ScitillaComponent/ScintillaEditView.cpp#L1665-L1681) we can evaluate `contractedFoldHeaderLine != -1` once instead of twice which, in turn, can increase performance slightly.

``` Cpp
while ((contractedFoldHeaderLine = static_cast<size_t>(execute(SCI_CONTRACTEDFOLDNEXT, contractedFoldHeaderLine))) != -1)
{
    //-- Store contracted line and Start next search with next line
    lineStateVector.push_back(contractedFoldHeaderLine++);      
}
```

**Comment by SinghRajenM** [comment]
@donho @dail8859  This issue can be closed now as new code is as below - 
``` C++
do {
		contractedFoldHeaderLine = static_cast<size_t>(execute(SCI_CONTRACTEDFOLDNEXT, contractedFoldHeaderLine));
		if (contractedFoldHeaderLine != -1)
		{
			//-- Store contracted line
			lineStateVector.push_back(contractedFoldHeaderLine);
			//-- Start next search with next line
			++contractedFoldHeaderLine;
		}
	} while (contractedFoldHeaderLine != -1);
```

**Comment by OrkhanAlikhanov** [comment]
@SinghRajenM the code was like that from day one. I had just offered reducing the code into 3 lines.

**Comment by SinghRajenM** [comment]
@OrkhanAlikhanov oh. I understood it in other way around. Sorry for creating confusion.

**Comment by OrkhanAlikhanov** [comment]
Closing as it's a mere optimization and due to inactivity.
