### ISSUE TITLE
Accessibility issues in Preferences dialog

### ISSUE THREAD

**Issue by sukiletxe** [notepad-plus-plus/notepad-plus-plus#2122]
I'm opening this here, as I can't seem to reply anymore to [This topic](https://notepad-plus-plus.org/community/topic/68/accessibility-problems). Something is wrong with my e-mail, which doesn't seem to receive any confirmation e-mail.

As plenty of time has passed, I was wondering if my recording was understandable. If not, here are some more steps to reproduce, with my current setup:
1. Go to http://nvaccess.org and download the NVDA screen reader (it won't install anything if you don't want it to).
2. Launch it and select any option, "keep running" or something similar will be enough.
3. Open the preferences window of Notepad++ and select the Misc tab.
4. Tab around.
5. Do the same thing in the general tab.

Ideally, the Misc tab should be coded in the same way as the general tab. In the Misc tab, there are many checkboxes labelled just "enable" with no context. But in the general tab, more context is given, as the items are "grouped", even if the "grouping" has one element, like in the language selection combo box.

**Comment by MetaChuh** [comment]
please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins if you update from version 7.5.9 or below.
if your issue still persists, and it is still of relevance to you, please feel free to file a new issue as easy to understand and reproducible as possible.

thank you for your help and best regards.

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
(no extra account is needed, just use your github account to sign in)
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)
