### ISSUE TITLE
Crash when shift-tabbing new CSS document

### ISSUE THREAD

**Issue by Superraiden** [notepad-plus-plus/notepad-plus-plus#2123]
### Description of the Issue

After pasting in CSS into a new document and the CSS language is selected, when pressing shift-tab to tab the text back to the left, Notepad++ crashes.

### Steps to Reproduce the Issue

1. Make a new text file
2. Set language to CSS
3. Paste in the text [here](http://pastebin.com/raw/Kc7k0jt4),
4. Select all (Ctrl A)
5. Shift tab to align to left. Notepad++ crashes.

### Expected Behavior

For the the selected text to move left, removing spaces.
### Actual Behavior

The bottom line succeeds in moving over, however Notepad++ crashes.

### Debug Information

Notepad++ v6.9
Build time : Feb 21 2016 - 21:27:55
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : ON
Local Conf mode : OFF
OS : Windows 7
Plugins : HexEditor.dll JSLintNpp.dll JSMinNPP.dll mimeTools.dll NotepadSharp.dll NppConverter.dll NppExport.dll NPPJSONViewer.dll PluginManager.dll PyNPP.dll Python Indent.dll PythonScript.dll 

Dump file below. Please rename from .txt to .dmp
[NppDump.txt](https://github.com/notepad-plus-plus/notepad-plus-plus/files/382915/NppDump.txt)

**Comment by dail8859** [comment]
I tried with v6.9.2 and wasn't able to make it crash at all. A few suggestions:

1. Disable your plugins. You can do this by renaming your `plugins` folder to something else temporarily.
1. Change your settings to see if using tabs vs. spaces makes any difference. 
1. If possible upgrade to [v6.9.2](https://notepad-plus-plus.org/news/notepad-6.9.2-released.html) (doubt this will change anything but you never know).

**Comment by chcg** [comment]
Can't reproduce either with:

Notepad++ v6.9.2
Build time : May 18 2016 - 00:34:05
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10
Plugins : AnalysePlugin.dll DSpellCheck.dll mimeTools.dll NppCCompletionPlugin.dll NppConverter.dll NppExport.dll NppFTP.dll NppTextFX.dll PluginManager.dll SpeechPlugin.dll Translate.dll
