### ISSUE TITLE
Find in Finder (Add marks like chrome)

### ISSUE THREAD

**Issue by SmileYzn** [notepad-plus-plus/notepad-plus-plus#2128]
Hi, please add marks in scrollbar like google chrome.

I hope that will help alot

**Comment by SmileYzn** [comment]
Some news?

**Comment by DedicatedTools** [comment]
I'd like this feature very much myself. It's present in several applications I use, and it's annoying not to have it in npp (which I use extensively throughout the day)...

Maybe some pictures will help explain what we mean...

In all apps mentioned below (as in Notepad++), when I select (of Find) some text, all occurrences of the same text are highlighted. This is very helpful to visualize where the same text is used on the current page. However, if some occurrences are outside of the current view (one has to scroll up or down to see them), there's no way to know about it in Notepad++.

Here's SQL Developer:
![selection_map_sql_developer](https://user-images.githubusercontent.com/6936601/52809698-df203600-305e-11e9-80d2-8dda035efff8.jpg)

Here's Visual Studio Code:
![selection_map_visual_studio_code](https://user-images.githubusercontent.com/6936601/52809747-fb23d780-305e-11e9-8c96-b56317bfbc0b.jpg)

Here's Google Chrome:
![selection_map_google_chrome](https://user-images.githubusercontent.com/6936601/52809764-02e37c00-305f-11e9-8b95-32c8e7fb1c97.jpg)

All of these display a (for lack of better term) "**match map**" (see the red rectangles on the right of each picture), making it easier to see where other occurrences are.

**Comment by donho** [comment]
This feature is limited by the component used by Notepad++(Scintilla). So I can do nothing about it.

**Comment by sasumner** [comment]
@DedicatedTools You changed @SmileYzn 's request into something else.
