### ISSUE TITLE
`///` comments in JavaScript display as "default style" instead of "commentdoc"

### ISSUE THREAD

**Issue by YellowAfterlife** [notepad-plus-plus/notepad-plus-plus#2133]
### Description of the Issue
`///` documentation comments are not recognized by JavaScript highlighter - instead of highlighting them as a documentation comment ("COMMENTDOC"), Notepad++ highlights them as "Global Styles - Default Style".

### Steps to Reproduce the Issue

1. Create a new document.
2. Switch language to JavaScript
3. Insert the test snippet

    ```
    // test 1
    /// test 2
    /* test 3 */
    /** test 4 */
    ```

### Expected Behavior
Have "test 2" line highlight in "commentdoc" style like "test 4" does, or at least highlight in plain "comment" style like "test 1" / "test 3".

### Actual Behavior
"test 2" is highlighted in default style used for plain text - not even the "default style" from JavaScript configuration, somehow.

### Debug Information
The fact of "default style" from "global styles" being used deducted through experimentation:
![gif](https://cloud.githubusercontent.com/assets/731492/17270341/1fe3d6f6-5669-11e6-907b-99cb070d5ef3.gif)
Curiously, JavaScript snippets included in HTML do not suffer from the same problem.

A very minor issue, obviously.

**Comment by dail8859** [comment]
Try deleting (or temporarily removing) your `stylers.xml` and `langs.xml` (probably located in your appdata directory) to see if this solves the issue. Several versions back JavaScript was changed a bit internally and sometimes the styles get a bit messed up.

**Comment by YellowAfterlife** [comment]
That helped, cheers.

The cause revealed to be that aside of the original `<LexerType name="javascript">`, a new `<LexerType name="javascript.js">` have been added at some point, but `stylers.xml` wasn't automatically patched to include the new section, apparently reverting to regular (now "embedded") JavaScript LexerType, which did not have a "Comment Line Doc" WordsStyle in it as such.
