### ISSUE TITLE
Spelling Mistake in Message box for Deleted from Outside

### ISSUE THREAD

**Issue by Ionman64** [notepad-plus-plus/notepad-plus-plus#2134]
### Description of the Issue
Text says "Do you wan to save file "<Filename>"?

### Steps to Reproduce the Issue

1. Open a file on disk
2. Open in Notepad++ and edit file (Do not save)
3. Delete File from disk
4. Notepad++ displays message box

### Expected Behavior
Text should be "Do you want to save file "<Filename>"?

### Actual Behavior
Text says "Do you wan to save file "<Filename>"?

### Debug Information
Version Number: 6.6.9
![save-message-box](https://cloud.githubusercontent.com/assets/9435314/17273653/cce952d6-56b4-11e6-9abf-f5d4527f559c.png)

**Comment by dail8859** [comment]
Closed since version 6.7 (see 1d92d189b30c49ed65372635cc2561ad76077894). Current Notepad++ version is 6.9.2
