### ISSUE TITLE
HTML syntax coloring alias for .wsf files

### ISSUE THREAD

**Issue by oxygen** [notepad-plus-plus/notepad-plus-plus#2136]
**Description:**
.wsf stands for Windows Script Files
It is a markup language similar to HTML (as far as Notepad++ is concerned) and contains JS.

Example:

```
<job>                                                               
    <reference object="WinSCP.Session"/>
    <script language="JScript">
        "use strict";

        var x=1;
    </script>
</job>
```

[https://en.wikipedia.org/wiki/Windows_Script_File](url)

**Request:**
Would be possible to have the .wsf file extension added as an alias of .html? (not XML, otherwise JS syntax coloring wouldn't be activated, I think).

**Comment by dail8859** [comment]
You can add custom extensions through the Style Configurator:

![capture](https://cloud.githubusercontent.com/assets/3694843/17314177/55dcc678-5830-11e6-80e6-34968db31092.PNG)

**Comment by oxygens** [comment]
That is great and really useful.

I meant have it by default in the shipping Notepad++, since it is a long existing and well documented file format extension.

**Comment by Crosis47** [comment]
That would be nonsensical to do with the WSF format. The format can contain multiple coding languages tagged as "jobs" in one file. For instance, while you use JScript, I use VBScript. The nice thing with WSF is that you can do something in one language then switch to another to do something else all in the same script.

**Comment by oxygen** [comment]
You're right.
It needs to be treated like an HTML file and the scripts be colored based on type, just like the script tag (which defaults to text/javascript) in .html files.

**Comment by oxygen** [comment]
So have .wsf files been aliased to HTML?
