### ISSUE TITLE
Find fails on concatenated value

### ISSUE THREAD

**Issue by pbeaven** [notepad-plus-plus/notepad-plus-plus#2137]
I'm using Notepad++  v6.9.2. If I press Ctrl-F to activate the "Find" dialog and enter "contract" as the value to find, Notepad++ highlights a number of "hits" but none that immediately follows or precedes another value, in other words Notepad++ does not find "contract" where "contract" is concatenated with an alphabetic value rather than a delimiter such as a space or comma.

Here is the text I am searching:
John Doe, Contract Specialist, Phone 222-333-4444
Jane M. DoeContract SpecialistPhoenix VA
Henry Doe, ContractSpecialist, Phone 666-777-8888

Here is a screen capture of the Find dialogue (note that **Match whole word only** is not checked): ![finddialog](https://cloud.githubusercontent.com/assets/20775221/17298378/be872c30-57d7-11e6-8a0b-b785e782e2e2.jpg)

I would expect to find "contract" highlighted in all three lines.

Instead, "contract" is highlighted only in line 1 as shown here: ![simple find results](https://cloud.githubusercontent.com/assets/20775221/17298386/c674e806-57d7-11e6-88ca-a343d65c133c.jpg). 

If I click **Find all in current document** all instances are highlighted, but only in the Search Results section at the bottom of the screen  - no instances within the text itself are highlighted (but that might be "normal" behavior). 
![find all in current document results](https://cloud.githubusercontent.com/assets/20775221/17298387/c991f7fe-57d7-11e6-9dfb-037607dad484.jpg)

**Comment by dail8859** [comment]
> Instead, "contract" is highlighted only in line 1 as shown here: 

That is from the smart highlighter, not due to the find dialog. If you click `Find Next` it will find all 3 matches. The smart highlighter finds complete *words* (e.g. valid variable names, etc)

**Comment by pbeaven** [comment]
Good to know! Helps to know just what you're seeing! Thanks.

**Comment by dail8859** [comment]
Closing since there isn't actually a problem.
