### ISSUE TITLE
F3 doesn't find next when Find dialog is open

### ISSUE THREAD

**Issue by adamroper007** [notepad-plus-plus/notepad-plus-plus#2138]
When the Find dialog is open, the keyboard shortcut 'F3' doesn't work.

This means that I have to Ctrl+F, enter the search text, press Enter, then close the Find dialog, and press F3 to start searching through the file.

Closing the dialog is a pain, and if F3 were associated with the Find Next button then there would be no issue.

**Comment by kamilrymarz** [comment]
Enter keyboard is associated with Find Next button, why do you need another key associated to same button? You can always close Find dialog with Escape.

The only difference is that Find Next button will not change focus to main window. If someone will accept this issue then I can assign F3 button with Find Next with additional functionality  to change focus on main window.

**Comment by jrheisey** [comment]
Visual Studio has always allowed the F3 key and Shift->F3 keys to function from the Find dialog. As far back as Visual C++.

The easiest way to code this is for the Find dialog to pass the F3 key message to its parent window instead of ignoring it. It may be useful for other keys to be passed on and possibly cause the focus to switch to its parent. I've done similar things in dialogs of other applications.

**Comment by Haftmann** [comment]
It's still a nasty misbehaviour. How can I help to implement that "feature"?

**Comment by sasumner** [comment]
>It's still a nasty misbehaviour

Disagree.  Keycombinations in editing tabs are remappable via the Shortcut Mapper.  These keycombos are NOT active when Find family of windows has input focus.  So hardbinding F3 in the Find window...does it really make sense? Not to me.

**Comment by jrheisey** [comment]
I agree that hard binding F3 is not appropriate. 

From my GUI development days we would have a dialog pass all unhandled keystrokes to its parent window.

- J.R.

**Comment by sasumner** [comment]
Related: https://notepad-plus-plus.org/community/topic/15023/f3-shift-f3-as-aliases-for-find-next-previous-while-find-dialog-is-active

**Comment by MetaChuh** [comment]
use enter and shift+enter as long as the find window is open

**Comment by alankilborn** [comment]
@donho 

What is your feeling about allowing the keybinding for _Find Next_ (and _Find Previous_) to do those functions, when the _Find_ window has input focus?  

Users don't like that they have to mentally adjust their workflow to pressing Enter (or Shift+Enter) in that circumstance.

If you'd like to see all of the references to user complaints over the years in that regard, I can put that together and post links here (otherwise I won't bother doing that).

**Comment by donho** [comment]
@alankilborn 
> If you'd like to see all of the references to user complaints over the years in that regard, I can put that together and post links here (otherwise I won't bother doing that).

**Don't bother doing it.**
But what I really mean is: I know why many people request this feature and we know all why F3 doesn't work with the focus on Find Replace dialog.
Now, if there's a PR can make Find Next command (F3) trough Find Replace dialog (or associate with "Find Next" button), and it is simple enough (yes, judged by me, it's subjective). I would say why not.

So no need to bother putting together all the requests. Let PR speak itself.

**Comment by alankilborn** [comment]
Of course, it shouldn't (necessarily) be F3; it should be whatever user has set up for _Find Next_ in the _Shortcut Mapper_.

**Comment by ozone10** [comment]
@donho @alankilborn 
Add `|| shortcuts[i].getID() == IDM_SEARCH_FINDNEXT || shortcuts[i].getID() == IDM_SEARCH_FINDPREV` to
https://github.com/notepad-plus-plus/notepad-plus-plus/blob/c823ca815056410a255ba7e62e870298c4be0968/PowerEditor/src/WinControls/shortcut/shortcut.cpp#L566

Add
```c++
case IDM_SEARCH_FINDNEXT:
case IDM_SEARCH_FINDPREV:
{
				if (HIWORD(wParam) != 1
					|| (getCurrentStatus() != DIALOG_TYPE::FIND_DLG
						&& getCurrentStatus() != DIALOG_TYPE::REPLACE_DLG))
				{
					return FALSE;
				}
				[[fallthrough]];
}
```
before 
https://github.com/notepad-plus-plus/notepad-plus-plus/blob/c823ca815056410a255ba7e62e870298c4be0968/PowerEditor/src/ScintillaComponent/FindReplaceDlg.cpp#L1538

**Comment by alankilborn** [comment]
@ozone did the work but for some reason didn't want to make it a PR ?

@donho If you want, assign me and I'll do the PR.

**Comment by ozone10** [comment]
@alankilborn 
you forgot 10 😊

I am away and I can't do PR. Feel free to do it.

**Comment by alankilborn** [comment]
> you forgot 10

10 ??

---

>Feel free to do it.

I will, but you took the fun part away (the figuring it out...the coding...)
