### ISSUE TITLE
Feature Request: Allow multiple clone/move to other view, with vertical/horizontal splitting

### ISSUE THREAD

**Issue by gri6507** [notepad-plus-plus/notepad-plus-plus#2140]
Currently, Notepad++ has the notion of "other view" which essentially vertically splits the window into two. This is a great feature.

```
+----------------------+----------------------+
|                      |                      |
|   Vertically split   |   Vertically split   |
|       (view 1)       |      (view 2)        |
|                      |                      |
|                      |                      |
+----------------------+----------------------+
```

This feature request is to allow more than one "other view", and make this "other view" be either in a vertically split or horizontally split window. For example, when splitting horizontally,

```
+---------------------------------------------+
|                                             |
|           Horizontally split (view 1)       |
|                                             |
+---------------------------------------------+
|                                             |
|           Horizontally split (view 2)       |
|                                             |
+---------------------------------------------+
```

This concept could be then taken to the next level, where any "view" can be split into any vertical/horizontal "subviews", like in this example where the main window is first split vertically, and the second view is then split horizontally.

```
+----------------------+----------------------+
|                      |  Horizontally split  |
|                      |     (view 2)         |
|   Vertically split   |                      |
|       (view 1)       +----------------------+
|                      |                      |
|                      |  Horizontally split  |
|                      |      (view 3)        | 
+----------------------+----------------------+
```

For reference, this is akin to VI's `:split` command (see http://vimdoc.sourceforge.net/htmldoc/windows.html for further information)

**Comment by MetaChuh** [comment]
please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins if you update from version 7.5.9 or below.
if your issue still persists, and it is still of relevance to you, please feel free to file a new issue as easy to understand and reproducible as possible.

thank you for your help and best regards.

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
(no extra account is needed, just use your github account to sign in)
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)

**Comment by sasumner** [comment]
It would be the same in a newer version. Apparently a design decision has be made to allow only one or two views simultaneously.  It's a decision that I am fine with.

**Comment by jmroyb** [comment]
I miss this feature. I usually have to check different parts of same large files. Now I have load same file twice and press press Ctrl + Tab. In a 50 lines file may be acceptable but in a 1000 lines is a pain. In this scenario I use Visual Studio

**Comment by kartikpodugu** [comment]
We should be able to split into multiple vertical and horizontal tabs as now we have 4k screens.
