### ISSUE TITLE
Avoid using folders in Start Menu

### ISSUE THREAD

**Issue by pquiring** [notepad-plus-plus/notepad-plus-plus#2143]
Installer places a folder with one item in it.  Avoid using folders in Start Menu for single items.  Looks bad in Windows 10.

**Comment by futal** [comment]
It seems that it only requires the following changes:

     CreateDirectory "$SMPROGRAMS\${APPNAME}"
     CreateShortCut "$SMPROGRAMS\${APPNAME}\Notepad++.lnk" "$INSTDIR\notepad++.exe"

To be replaced in [mainSectionFuncs.nsh](https://github.com/notepad-plus-plus/notepad-plus-plus/blob/a242214a28f9dfa2d7327c34054b74573de98258/PowerEditor/installer/nsisInclude/mainSectionFuncs.nsh#L276-L278) on lines 277-278 by:

     CreateShortCut "$SMPROGRAMS\Notepad++.lnk" "$INSTDIR\notepad++.exe"

The following line should be added x times: once in file [mainSectionFuncs.nsh](https://github.com/notepad-plus-plus/notepad-plus-plus/blob/a242214a28f9dfa2d7327c34054b74573de98258/PowerEditor/installer/nsisInclude/mainSectionFuncs.nsh) on line 265 ; and four times in the file [uninstall.nsh](https://github.com/notepad-plus-plus/notepad-plus-plus/blob/9733729bfbb4767269d63eedde7b35ac4536a138/PowerEditor/installer/nsisInclude/uninstall.nsh#L172-L174) on lines 166, 175, 199 and 208:

    Delete "$SMPROGRAMS\Notepad++.lnk"
