### ISSUE TITLE
Search from search dialog always fails

### ISSUE THREAD

**Issue by scott14468** [notepad-plus-plus/notepad-plus-plus#2144]
All searches for anything from the search dialog fail!  Searches with the dialog closed pressing F3 do work.  This applies to V6.9.2.

Scott

**Comment by dail8859** [comment]
Provide more info. There isn't near enough to go on here.

**Comment by scott14468** [comment]
I'm not sure what happened.  Everything I searched for with the dialog resulted in nothing found until I closed the dialog and used F3.  A few hours later, did basically the same thing and all cases worked OK.  Days later I can't reproduce the problem.  Sorry for the false alarm.

Scott




---- dail8859 <notifications@github.com> wrote: 

=============
Provide more info. There isn't near enough to go on here.

---

**Comment by dail8859** [comment]
It could have been something like having the wrong search mode, or having "Wrap around" not checked. Glad to hear it is working.
