### ISSUE TITLE
default extention

### ISSUE THREAD

**Issue by VbNetMatrix** [notepad-plus-plus/notepad-plus-plus#2145]
### Description of the Issue

When saving a file for the first time, "new 0" is selected as the file name and no extention is affected to it.  furthermore, in type combo, there is no ".txt" file you can select.  if we save, let's say on desktop and then double click on the file, windows will ask for default application because the file got no extention.
I believe this should be in option "preference" where we could be able to add our "prefered extention"
I do not want to associate no extention file to "notepad" or to any program for that matter
### Steps to Reproduce the Issue

1. open notepad
2. create a new file
3. attempt to save the file
### Expected Behavior

default extention
### Actual Behavior

no extention at all when saving new file (defined as _._)

**Comment by MetaChuh** [comment]
please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins if you update from version 7.5.9 or below.
if your issue still persists, and it is still of relevance to you, please feel free to file a new issue as easy to understand and reproducible as possible.

thank you for your help and best regards.

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
(no extra account is needed, just use your github account to sign in)
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)
