### ISSUE TITLE
Windows 10 - TabTib32/TabTib causes Notepad++ to crash on exit.

### ISSUE THREAD

**Issue by SanyaWaffles** [notepad-plus-plus/notepad-plus-plus#2150]
### Description of the Issue
Latest **Windows 10** update has caused many apps, including Notepad++ to crash.

Also, oddly, Windows 10 is being reported by Notepad++ as **Windows 8.**

### Steps to Reproduce the Issue

1.  Under Windows 10's latest major update **(the so-called _Anniversary Update_)**, open Notepad++
2.  Alt+F4 or Click the 'x' to exit the app - doesn't matter if documents are opened or not.
![image](https://cloud.githubusercontent.com/assets/1550098/17458673/017ca83a-5be8-11e6-9c05-121b007a0a6c.png)
3.  The crash occurs upon exiting the app.

### Expected Behavior
To close with no errors.

### Actual Behavior
Crashes upon exit, asks me to 'close' or 'debug' the app. (Screenshot below)

It does however start right back up with the session I had before.

It is more of an annoyance than a devastating bug, but it only occured after the latest update.

### Debug Information
```
Notepad++ v6.9.2
Build time : May 18 2016 - 00:34:05
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 8
Plugins : ComparePlugin.dll mimeTools.dll NppConverter.dll NppExport.dll NppTextFX.dll PluginManager.dll zoomdisabler.dll 
```

### Event Viewer Information

```
Faulting application name: notepad++.exe, version: 6.9.2.0, time stamp: 0x573b9c9e
Faulting module name: combase.dll, version: 10.0.14393.0, time stamp: 0x57898e4d
Exception code: 0xc0000602
Fault offset: 0x000d274d
Faulting process id: 0x30a4
Faulting application start time: 0x01d1f0142d4c5282
Faulting application path: C:\Program Files (x86)\Notepad++\notepad++.exe
Faulting module path: C:\WINDOWS\System32\combase.dll
Report Id: e612492e-041d-44f7-a85c-df8927b350e8
Faulting package full name: 
Faulting package-relative application ID:
```

### Screenshot of 'Crash'

![image](https://cloud.githubusercontent.com/assets/1550098/17458634/37c2b788-5be6-11e6-8abe-bfe15612a1dd.png)

### System Info As Reported By Speccy

This is just in case it's somehow relevant... not sure if it would be in this case, but I can never be too sure.

```
Windows 10 Pro 64-bit
Intel Core i7 4790K @ 4.00GHz Haswell 22nm Technology
16.0GB Dual-Channel DDR3 @ 815MHz (10-10-10-27)
ASUSTeK COMPUTER INC. MAXIMUS VII HERO (SOCKET 1150)
2047MB NVIDIA GeForce GTX 950 (EVGA)
```

**Comment by cudencuden** [comment]
I'm running win10x64 anniversary....cannot recreate your issue

**Comment by SanyaWaffles** [comment]
I might have found the culprit. I will report back on my findings

**Comment by SanyaWaffles** [comment]
I found the culprit.

And it does have to do with Windows 10 Anniversary Edition.

I have a Wacom Tablet for art, so it's loading TabTip and TabTip32.

when I manually shut these apps/services down, Notepad++ operates fine (usually by killing them in the Task Manager).

and it closes without any crashes.

Despite being a desktop gaming/media rig, Windows 10 is convinced that my computer is a tablet PC for some reason.

I consider the matter closed as I need to find a way to disable TabTip/TabTip32 without me having to kill it manually each time I log into Windows, but it might be something other users will encounter if they use a Wacom tablet.

**Comment by cudencuden** [comment]
have you verified that your tablet mode is set to off? http://www.laptopmag.com/articles/enable-tablet-mode-windows-10

**Comment by SanyaWaffles** [comment]
I followed the instructions you said and it's still reporting as a Tablet.

I did however set the Tablet PC/Tablet related services in services.msc to disabled and that fixed it.

Still, Notepad++ and other apps shouldn't crash if tablet mode is enabled... and I wonder why they would only after this recent update.

**Comment by SanyaWaffles** [comment]
I want to report back it's been amost 24 hours since I disabled the Tablet Input stuff and Notepad++ hasn't crashed.

However since other apps were crashing too, not just Notepad++ (Civilization V was another program) with this, I am chaulking it up to Windows 10: Anniversary Edition issue with TabTip/TabTip32 and related services, and not Notepad++, so I am closing this up and hoping Microsoft fixes this issue.
