### ISSUE TITLE
Notepad++ convert ANSI-file to UTF-? at opening

### ISSUE THREAD

**Issue by x-fuego** [notepad-plus-plus/notepad-plus-plus#2153]
Notepad++ unexpectedly convert ANSI-file to UTF-? at opening. File test.txt file and three images, that shows bug attached here.

Notepad++ v6.9.2
Build time : May 18 2016 - 00:34:05
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 7
Plugins : HexEditor.dll mimeTools.dll NppConverter.dll NppExport.dll NppTextFX.dll PluginManager.dll Tidy2.dll XMLTools.dll 

[test.txt](https://github.com/notepad-plus-plus/notepad-plus-plus/files/406030/test.txt)
![windows notepad](https://cloud.githubusercontent.com/assets/20897698/17469497/53712ddc-5d3c-11e6-9d92-8082437ef7d2.PNG)
![notepad _text](https://cloud.githubusercontent.com/assets/20897698/17469495/536f7d52-5d3c-11e6-83d2-5740323c0d23.PNG)
![notepad _hex](https://cloud.githubusercontent.com/assets/20897698/17469496/5370709a-5d3c-11e6-8aab-0b00957ed9d4.PNG)

**Comment by dail8859** [comment]
Try disabling `Settings > Preferences > New Document > Encoding > Apply to opened ANSI Files`

**Comment by x-fuego** [comment]
> Try disabling Settings > Preferences > New Document > Encoding > Apply to opened ANSI Files
A have disabled option
![default](https://cloud.githubusercontent.com/assets/20897698/17843665/6da0ad88-6839-11e6-98fc-a4e84b09940d.PNG)

**Comment by x-fuego** [comment]
I have found another problem with encodings. I have file in which parallely two encoding used - JS-script don not support UTF-8, but from such script will writen UTF-8-file. When I need write cyrillic in the ANSI-encoding, I choose form menu "Encodings" point "Encode as ANSI", and if I need modify cyrillic text in the UTF-8-encoding, I choose point "Encode as UTF-8". But in new versions it not worked. I roolbacked to older versions, and fou that NPP version 6.5 has no such problems. And problem descibed at this thread too.

**Comment by MetaChuh** [comment]
please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins if you update from version 7.5.9 or below.
if your issue still persists, and it is still of relevance to you, please feel free to file a new issue as easy to understand and reproducible as possible.

thank you for your help and best regards.

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
(no extra account is needed, just use your github account to sign in)
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)
