### ISSUE TITLE
NP++ Window resizes to just menu on selected text copy

### ISSUE THREAD

**Issue by simonbagley** [notepad-plus-plus/notepad-plus-plus#2155]
### Description of the Issue

The Notepad++ application window minimizes itself to just a very small portion of its menubar, when trying to copy some selected text using eith the context menu (right click) or the Edit menu.
Notepad++ is running on a Windows 10 PC.
### Steps to Reproduce the Issue

1. Open a new document
2. Type some text
3. Select some of the text
4. Right click on the text, and select copy
### Expected Behavior

I would expect the Notepad++ window to stay the same size, and the the selected text to be copied to the clipboard.
### Actual Behavior

The Notepad++ window resized itself to show just the Notepad++ icon, the maximise icon, and the close icon, and nothing else (see screenshot below). The text was copied to the clipboard as expected though.
### Debug Information

Notepad++ v6.9.2
Build time : May 18 2016 - 00:34:05
Path : D:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10
Plugins : ComparePlugin.dll JSMinNPP.dll mimeTools.dll NppConverter.dll NppExport.dll NppFTP.dll PluginManager.dll 

Here is a screen shot just before right clicking on the selected text and clicking copy:
![notepadpp_before_copy](https://cloud.githubusercontent.com/assets/13997517/17514299/bfa32580-5e29-11e6-8873-58ff84fc20eb.PNG)
Here is a screenshot just after copy was selected from the right click menu:
![notepadpp_after_copy](https://cloud.githubusercontent.com/assets/13997517/17514316/d84132f8-5e29-11e6-8a8b-9069a81167c4.PNG)

**Comment by dail8859** [comment]
Related: #1169 #417

I think there's a bit of discussion on the forum somewhere that Notepad++ doesn't play nice when using Nvidia's desktop manager (nview?). Do you happen to be using that as well?

**Comment by simonbagley** [comment]
I am using the Nvidia desktop manager.

**Comment by dail8859** [comment]
Good to know. AFAIK there isn't a solution, but I can't say I've followed the issue in that much detail.

**Comment by Raimatune** [comment]
I have been experiencing this issue as well and found the following solution.

1) Open the nView Desktop Manager
2) Go to the 'Applications' page from the page selection tree
3) Under "Applications using custom nView Desktop Manager settings", click the Add button.
4) In the Application textbox enter: notepad++
5) Click OK
6) Select the newly added item and click the Disable button
7) I chose to disable nView completely for notepad++ as I don't see how it's necessary, but after some testing, it seems that unchecking the "Enable nView title bar buttons and options menu" is enough to fix the issue.

My versions are:
Notepad++: v6.9.2
nView: v146.33

**Comment by simonbagley** [comment]
I just unchecked the Enable nView title bar buttons and options menu" as you suggested, and this has solved my problem.
Thanks.

**Comment by blue-sun-tech** [comment]
@Raimatune This solved the issue for me as well! Thanks!

**Comment by RobinLamacraft** [comment]
I am using the nVidia Control Panel for a QUAD 450. I have made the changes suggested and will report back if this chabge does not fix the ptoblem (I have another application that also was going wonky after a MW10 update so I have also disabled it in the nView.)

**Comment by cricrazy** [comment]
I had a similar issue and this had annoyed me for so longer. I am not sure why I did not search online for the fix earlier. It is working now. Thank you so much.

**Comment by ikalaushin** [comment]
https://community.notepad-plus-plus.org/topic/21895/faq-desk-huge-gaps-blank-areas-in-the-ui-borders
Add this comment to save time
