### ISSUE TITLE
Toggle comment (Ctrl+Q) doesn't work for auto-reloaded files

### ISSUE THREAD

**Issue by danny0838** [notepad-plus-plus/notepad-plus-plus#2156]
### Description of the Issue

Sometimes for an unknown reason the **Toggle comment (Ctrl+Q)** function becomes functionless for a file.
- When this happen, there is no action whether by pressing hotkey Ctrl+Q or by clicking the directive in menu list. The directive in the menu list is shown as normal (i.e. not in a disabled status).
- This issue seems to be bound to a file. When it happens, toggle comment doesn't work for only the file, and other files are not associated.
- Restarting notepad++ doesn't solve the issue.
- Restarting computer doesn't solve the issue.
- Closing the file and reopen it in notepad++ solves the issue. (i.e. the toggle comment function works for the file)
### Debug Information

Notepad++ v6.9.2
Build time : May 18 2016 - 00:34:05
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 7
Plugins : mimeTools.dll NppConverter.dll NppExport.dll NppFTP.dll PluginManager.dll

**Comment by dail8859** [comment]
It is based on the current syntax of the file. What type of file are you trying to comment

**Comment by danny0838** [comment]
I saw it at least happened on javascript, HTML, CSS, XML, Python, Shell Script (already confirmed that the current syntax highlight is correct for each file type).

**Comment by dail8859** [comment]
Do you have any type of reproducible test-case?

**Comment by danny0838** [comment]
It seems to be highly related with OS logout-login. Notepad++ remembers the last opened files, but after a logout-login those remembered files seems to have toggle comment non-working.

**Comment by danny0838** [comment]
I tested again and it seems that restarting notepad++ also triggers this issue.

**Comment by danny0838** [comment]
I found a procedure to reproduce the issue:

1. Prepare a file with javascript code in it. Let's call it demo.js.

2. Prepare a newly installed Notepad++

3. Open demo.js with Notepad++.

4. Check Ctrl+Q. It works now.

5. Shutdown Notepad++.

6. Start Notepad++, and demo.js is automatically loaded into the tab.

7. Switch to the tab of demo.js. Check Ctrl+Q. It doesn't work now.

8. Close demo.js.

9. Open demo.js with Notepad++ again.

10. Check Ctrl+Q. It works now.

**Comment by dail8859** [comment]
Haven't been able to reproduce the issue. You might try temporarily moving your `langs.xml` and `stylers.xml` (most likely in your %APPDATA% directory) and see if that fixes the issue.

**Comment by danny0838** [comment]
This issue does not 

Notepad++ v7.4.2   (32-bit)
Build time : Jun 18 2017 - 23:34:19
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 7 (64-bit)
Plugins : HexEditor.dll mimeTools.dll NppConverter.dll NppExport.dll PluginManager.dll

**Comment by WiliTest** [comment]
removing `langs.xml` worked
