### ISSUE TITLE
Feature request: finding First/Top and Last/Bottom occurences of a string with just one click

### ISSUE THREAD

**Issue by salvarani** [notepad-plus-plus/notepad-plus-plus#2158]
![notepad _improvementrequest_160810](https://cloud.githubusercontent.com/assets/6116182/17550414/2a7b00fa-5ef5-11e6-8137-63902e2ed0df.png)

### Steps to Reproduce the Issue

1. 
2. 
3.

**Comment by MAPJe71** [comment]
This (as I presume feature request) can already be achieved with available functionality:
- Put the cursor at the very top of the document, make sure you selected down for direction, select 'Find Next' to find the first match.
- Put the cursor at the very end of the document, make sure you selected up for direction, select 'Find Next' to find the last match.

**Comment by manathan123** [comment]
Even more simple: With "Warp around" enabled by starting from the top of the document, you can find the first occurrence by setting the direction to "Down", and then find the last occurrence by changing it to "Up".
