### ISSUE TITLE
Custom word chars gets reset

### ISSUE THREAD

**Issue by dail8859** [notepad-plus-plus/notepad-plus-plus#2159]
### Description of the Issue
Plugins are able to set a list of custom word chars (e.g. using [SCI_SETWORDCHARS](http://www.scintilla.org/ScintillaDoc.html#SCI_SETWORDCHARS)). When a link is double clicked this custom list of characters is reset.

### Steps to Reproduce the Issue

1. Have a file such as

    http://example.com
    $abc

2. Double click the `b`. Only `abc` is selected. (which is expected behavior)
3. Modify the word chars. For example use LuaScript and run

    editor.WordChars = editor.WordChars .. '$'

4. Repeat step 2. Now `$abc` is selected.
5. Double click the link.
6. Repeat step 2 again. Now only `abc` is selected.

### Expected Behavior
N++ should respect plugins setting a custom list of word chars.

### Actual Behavior
The custom list of word chars is getting reset when clicking on links.

### Debug Information
```
Notepad++ v6.9.2
Build time : May 18 2016 - 00:34:05
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : ON
Local Conf mode : OFF
OS : Windows 7
Plugins : DoxyIt.dll LuaScript.dll mimeTools.dll NppConverter.dll NppExport.dll PluginManager.dll 
```

**Comment by A-R-C-A** [comment]
Open NppNotification.cpp, navigate to 'case SCN_HOTSPOTDOUBLECLICK' and then add the following (not tested!):
```cpp
case SCN_HOTSPOTDOUBLECLICK:
{
	const size_t wordBufferSize = notifyView->execute(SCI_GETWORDCHARS, 0, 0) + 1;
	const size_t spaceBufferSize = notifyView->execute(SCI_GETWHITESPACECHARS, 0, 0) + 1;
	const size_t punctBufferSize = notifyView->execute(SCI_GETPUNCTUATIONCHARS, 0, 0) + 1;
	char * wordChars = new char[wordBufferSize];
	char * spaceChars = new char[spaceBufferSize];
	char * punctChars = new char[punctBufferSize];
	notifyView->execute(SCI_GETWORDCHARS, 0, reinterpret_cast<LPARAM>(wordChars));
	notifyView->execute(SCI_GETWHITESPACECHARS, 0, reinterpret_cast<LPARAM>(spaceChars));
	notifyView->execute(SCI_GETPUNCTUATIONCHARS, 0, reinterpret_cast<LPARAM>(punctChars));
	wordChars[wordBufferSize - 1] = '\0';
	spaceChars[spaceBufferSize - 1] = '\0';
	punctChars[punctBufferSize - 1] = '\0';

	. . .

		//notifyView->execute(SCI_SETCHARSDEFAULT);
	}
	notifyView->execute(SCI_SETWORDCHARS, 0, reinterpret_cast<LPARAM>(wordChars));
	notifyView->execute(SCI_SETWHITESPACECHARS, 0, reinterpret_cast<LPARAM>(spaceChars));
	notifyView->execute(SCI_SETPUNCTUATIONCHARS, 0, reinterpret_cast<LPARAM>(punctChars));
	delete [] wordChars;
	delete [] spaceChars;
	delete [] punctChars;
	break;
}
```
You need to store/restore all character sets, since SCI_SETWORDCHARS will reset them all. Zero termination is probably not needed, but should be tested first.

Alternatively you can try to change the approach how SCN_HOTSPOTDOUBLECLICK implementation currently works to something without SCI_SETWORDCHARS/SCI_SETCHARSDEFAULT.
