### ISSUE TITLE
Use ClearType only if enabled system-wide

### ISSUE THREAD

**Issue by milipili** [notepad-plus-plus/notepad-plus-plus#216]
ClearType, like any other system-related settings, should not be unconditionally enabled and should follow the system preferences.

Some hints:
https://msdn.microsoft.com/en-us/library/aa970267%28v=vs.110%29.aspx
https://msdn.microsoft.com/en-us/library/ms901156.aspx
original PR: #116 (Optimize font quality for LCD)

**Comment by DmFedorov** [comment]
Np++ 6.7.8 without Clear Type  . . . . . . Np++ 6.7.9 with Clear Type
![06 17 2015 21_23_32](https://cloud.githubusercontent.com/assets/11689701/8261073/08300250-16c8-11e5-9d7c-46bbf5621a15.gif)
I don't found where I can forbid Clear Type for Np++
You see in Tab-header - the same, but in main window - other.
ClearType is disabled in system, but Np++ now have Clear Type
