### ISSUE TITLE
Plug-In / Powershell Lexer / Externallexer.dll / Bug Report

### ISSUE THREAD

**Issue by fuerudo** [notepad-plus-plus/notepad-plus-plus#2161]
### Steps to Reproduce the Issue

1. Use Plugin-Manger
2. Choose "Powershell Lexer"
3. Choose Install and restart Notepad++

### Debug Information

Notepad++ crashes after installing "Powershell Lexer" while every restart!
Notepad++ Version: 6.9.2;
OS: Windows 10 - 64 Home ( with actual Updates);
Workaround to bring back Notepad++ usability:
Moving "NppExternalLexers.dll" from "~/plugins" - Path to "~/plugin/disabled" Path;

-------------- Germans Original Text --------------------------------------------
Nach Installation des "Powershell Lexer" Plugins, mittels des Plugin-Managers, stürzte Notepad bei jedem Neustart ab!
Erst das Verschieben der "NppExternalLexers.dll", aus dem ~/plugins Pfad in den ~/plugins/disabled Pfad, machte Notepad++ wieder startfähig!
Notepad++ - Version: 6.9.2;
System: Windows 10 Home 64 Bit (alle aktuellen Updates installiert);
Ich vermute eine schwerwiegende Inkompatibilltät des Plug-Ins, kann die tieferen Hintergründe dafür aber nicht analysieren, sorry!

**Comment by dail8859** [comment]
Since this is a 3rd party plugin this issue needs reported to the author of the PowerShell lexer. FYI Notepad++ has a built in lexer for PowerShell.
