### ISSUE TITLE
copy on select feature in notepad++

### ISSUE THREAD

**Issue by AshishNamdev** [notepad-plus-plus/notepad-plus-plus#2162]
### Description of the Issue

I Love to use NotePad++ and waiting for feature like **vim** where use can select the content to copy.

Selected content in editor should be copied to clipboard to paste. , this is a useful feature , which developers will love to have in NotePad++.

### Steps to Reproduce the Issue

1. Open any source/text file in NotePad++.
2. Select some content from the file to copy.
3. Content should be copied on select itself. 
### Expected Behavior

Selected content should be copied automatically to clipboard without doing **ctlr+v** or **right click + copy** in editor to copy the content.
### Actual Behavior

In current versions , user has to select the content then have to do **ctlr+v** or **right click + copy**
to copy content.
### Version Used

NotePad++ v6.9.2

**Comment by AshishNamdev** [comment]
@donho  can you please look into this issue ?
or any guideline or documents you can share for notepad++ contribution so i can work on to this and send pull request

**Comment by ljporljp** [comment]
i don't think this can be used by many people , but just given a choice to let users set . BECAUSE select and copy are just TWO different operation, and sometimes it will be annoying if i forget i have set this flag, and i want copy something but by the time do the "select" op , oh, cant be imaging.

**Comment by benpratt** [comment]
While I can't say how many people would use this feature I can say that I would love to have this option available. It was available when using the multiclipboard plug-in but until that plug-in is updated to x64 it is not available.

**Comment by tinyhare** [comment]
It is very useful for operation and maintenance engineers(Xshell  support it). it used for copy different  configurations，different IPs， domains and so on, and the small pieces of text will copy many times. if auto copy when select, it will convenience. it's better set a switch button on toolbar

**Comment by humanoid-gi** [comment]
I vote for this improvement!
It's default behavior for many console terminal applications like PuTTY, konsole, xterm etc and would be very useful for many engineers.

**Comment by iznogoud06** [comment]
I vote too ! Very useful

**Comment by sasumner** [comment]
Downvote.  Blech.

**Comment by dail8859** [comment]
This feature won't be implemented. There are too many problems that could arise from it (polluting the clipboard history, potentially lots and lots of data copied, and more than likely confusing users who aren't expecting the behavior, etc). In the end this feature would benefit only a *very* small percentage of users.

All this just to save a single shortcut key is not worth it.

For anyone still interested in this ~~feature~~ unique behavior can use a plugin such as PythonScript or LuaScript and do it in a few lines of code.

**Comment by sasumner** [comment]
>...use a plugin such as PythonScript...and do it in a few lines of code.

If one tries this and uses asynchronous callbacks in the approach, one is likely to encounter this problem: https://github.com/bruderstein/PythonScript/issues/85

**Comment by KubaDee** [comment]
Hey,
I made tiny plugin with copy-on-select feature. If anyone is interested, here is link:

https://github.com/KubaDee/SelectToClipboard/releases/tag/v1.0.1

It works as it should, but I didn't make any stress tests or so.
Thus plugin comes with no warranty :)

**Comment by consari** [comment]
thank you very much @KubaDee !!

**Comment by freezer2022** [comment]
> @rajamunr : It didn't work for me. Any suggestion?

I've just tested the newest version : https://github.com/KubaDee/SelectToClipboard/releases/tag/v1.0.3 and it works fine.
