### ISSUE TITLE
[BUG v6.9.2] StatusBar fields 2 and 3 clip contents.

### ISSUE THREAD

**Issue by sky5walk** [notepad-plus-plus/notepad-plus-plus#2166]
Please do not ignore this bug! It was not fixed by commit https://github.com/notepad-plus-plus/notepad-plus-plus/commit/7e299fdd31d4340588a70d4378f500065166f961.
Previous bug reports(Fixes #1536, fixes #356, fixes #366, fixes #539, fixes #1447) were closed so I made comments on those reports and opened this new issue for clarity.
![bug_notepad v692_statusbar](https://cloud.githubusercontent.com/assets/13093122/17632553/009a6944-6097-11e6-986e-fd645fd72550.PNG)
[BUG_Notepad++v692_statusbar.txt](https://github.com/notepad-plus-plus/notepad-plus-plus/files/415941/BUG_Notepad.v692_statusbar.txt)

**Comment by dail8859** [comment]
I'm assuming you have changed the system default font? Because normally the summary window and status bar do not use mono-spaced fonts.

**Comment by sky5walk** [comment]
You are correct. That is a requirement of my theme. Consolas does not break any other application I use? 
Why are the status bar fields constrained to fix widths? 
You can see they are only a few characters short for field 2 and 3. 
If Notepad++ requires proportional fonts for its status bar metrics, then apply one.
Thanks for your question.

**Comment by sky5walk** [comment]
Is it wrong to just increase the fixed width of fields 2 and 3 to solve this bug?
It is useful to know how many lines or characters are selected. :(

**Comment by MAPJe71** [comment]
IMO yes as the width of the fields in the status bar depend on dpi, content and for textual content also on language and font.

**Comment by sky5walk** [comment]
I fear this becomes a circular argument when the solution is simple. Fixed pitch fonts are not the enemy.

**Comment by MAPJe71** [comment]
Don't think the font is the biggest hurdle, it's just part of the equation :)
IMO using a fixed pitch font and discarding the other variables is a short term work around,  not a real solution.

**Comment by sky5walk** [comment]
What other variables? Field 1 is oversized and wastes space, while field 2 & 3 are clipped. Adding text width to field 2 & 3 is not a work around, but an actual solution. I'm not asking for dynamically sized statusbar fields? (Though I code that in my own apps.)

**Comment by MAPJe71** [comment]
You could contribute :)

**Comment by sky5walk** [comment]
I am by actively reporting issues. I cannot contribute source code to every bug I find in applications I use?

**Comment by MAPJe71** [comment]
You're right, one can't.
But as far as I can tell no one else seems to think the issue is worth their time to address it. 
IMO posting the issue multiple times doesn't help either.

**Comment by sky5walk** [comment]
Seriously? Why be a troll on a bug list?
This issue is marked OPEN. Save your opinions until the dev's mark it otherwise.

**Comment by dail8859** [comment]
Is it a bug? Yes.

Do all bugs get fixed? No. Especially ones that affect a very small percentage of users.

Keep in mind with the next release of N++ that it will probably cut off a bit more because some of those numbers will have commas in there.

When you use non-standard settings don't be surprised when you run across non-standard behavior.

**Comment by sky5walk** [comment]
Thanks for the bug clarification, but I disagree with "non-standard". The operating system allows me to can choose any font and size I prefer. Individual preferences are "standard" in modern applications.
In the meantime I found a work around for anyone else that modifies their Windows skin.
// If user has modified their Windows Desktop fonts to fixed pitch like Consolas or Courier?
Windows 7 "Personalize - Window Color and Appearance" gui has no option for StatusBar:
Change the StatusBar font in Regedit.exe.
HKEY_CURRENT_USER\Control Panel\Desktop\WindowMetrics\StatusFont --> Segoe UI
  Must cut and paste from another member's default font assignment.
//

**Comment by MetaChuh** [comment]
please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins if you update from version 7.5.9 or below.
if your issue still persists, and it is still of relevance to you, please feel free to file a new issue as easy to understand and reproducible as possible.

thank you for your help and best regards.

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
(no extra account is needed, just use your github account to sign in)
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)

**Comment by sky5walk** [comment]
Yes, I migrated to v766 and dropped my quest for a monotyped font theme.
All is fine for the conformists. 😏
