### ISSUE TITLE
Expand/collapse wrong if comment starts with "# if" in PHP code

### ISSUE THREAD

**Issue by mdrmdrmdr** [notepad-plus-plus/notepad-plus-plus#2168]
### Description of the Issue
When editing a PHP file which contains comments starting with "# if", an extra collapse mark is added which breaks the rest of the expand/collapse functionality

### Steps to Reproduce the Issue
For example edit this file:

`<?php`
`function test($a) {`
`   echo $a."\n";`
`   # blah blah`
`   echo $a."\n";`
`   # if blah blah`
`   echo $a."\n";`
`}`
`test("test");`
`?>`

### Expected Behavior
No collapse mark is added at the line "# if ..."

### Actual Behavior
Collapse mark is added at the line "# if ..."

### Debug Information
n/a

n/a

**Comment by dail8859** [comment]
This appears to be an issue with Scintilla, even in their latest version (v3.6.6). 

![capture](https://cloud.githubusercontent.com/assets/3694843/17646269/b762f886-6190-11e6-8477-a9d05423b0d1.PNG)

It is probably best to post this issue over to their project on [SourceForge](https://sourceforge.net/p/scintilla/bugs/).

**Comment by mdrmdrmdr** [comment]
done!
-> https://sourceforge.net/p/scintilla/bugs/1852/

**Comment by dail8859** [comment]
Quote from Scintilla author:

> Its a feature. From [feature-requests:#738](https://sourceforge.net/p/scintilla/feature-requests/738/) implemented by change set [c5f2e5](https://sourceforge.net/p/scintilla/code/ci/c5f2e55cf795ce36a6bfffb6d1ddc9b6e7fad903/).

So unfortunately there is nothing N++ can do about it.

**Comment by mdrmdrmdr** [comment]
Well, the feature request talks about "#region" and "#endregion". With no blanks between "#" and the text. But it does not talk about "# if" ...
Anyway, a cheap workaround is to use "# when..." :-) Once you know about the issue...

**Comment by dail8859** [comment]
I would agree that the "feature" is not correctly implemented...but who am I to say ;)
