### ISSUE TITLE
Plugin Python Indent wrong about update

### ISSUE THREAD

**Issue by WagnerGMD** [notepad-plus-plus/notepad-plus-plus#2170]
http://nsa37.casimages.com/img/2016/08/14/160814033507301606.png
Hello,

as you can see, the (Notepad++) Plugin Manager doesn't detect the version for the plugin Python Indent. That's why the program believes an update exist. And that's not true because I already have the version : "1.0".
Even after the reinstallation, the little trouble is (still) there. Then don't try to uninstall / reinstall the plugin, it doesn't work. 

Best regards.

PS : One reminder below :
NotePad++ version : "6.9.2"
NotePad++ Plugin Manager : "1.3.5.0"

**Comment by dail8859** [comment]
This has to do with the way the plugin was compiled (e.g. missing version info) or registered with the Plugin Manager. It would be best to report this to the author of the Python Indent plugin.
