### ISSUE TITLE
Repeated sequence of same characters omits carriage return (Enter)

### ISSUE THREAD

**Issue by kienerj** [notepad-plus-plus/notepad-plus-plus#2173]
### Description of the Issue

This issue is hard to describe and maybe it's a feature I don't know about. But bascially if you type a repeated sequence like `ABC` and press enter it works as expected. On the next line you repeat the exact same sequence and press enter and now the carriage return is committed. If you then repeat the sequence a second time and press enter, it does indeed at a new line. The behaviors is then consistent. For each lien the sequence must be repeated one more time until a carriage return is added leading to a pattern like this:

    ABC
    ABCABC
    ABCABCABC
    ABCABCABCABC

and so forth. I was testing barocdes and scanning same barcode multiple times...but the issue also happens with manual entry.

### Steps to Reproduce the Issue

1. Enter ABC Press Enter
2. Repeat above 10 times

### Expected Behavior

New line added after each press of enter

### Actual Behavior

New line is not always added after pressing enter.

### Debug Information

Notepad++ v6.9.2
Build time : May 18 2016 - 00:34:05
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : ON
Local Conf mode : OFF
OS : Windows 7
Plugins : ComparePlugin.dll HTMLTag_unicode.dll mimeTools.dll NppCCompletionPlugin.dll NppConverter.dll NppExport.dll NppFTP.dll NPPJSONViewer.dll NppTextFX.dll PluginManager.dll Python Indent.dll SpellChecker.dll Tidy2.dll XMLTools.dll 

(Issue also happens with plugins disabled)

**Comment by dail8859** [comment]
I am assuming this is because you have auto-complete turned on. After you type the first `ABC` then the next time you start typing it (and it tries to auto-complete it) then when you press `Enter` it is grabbed by the auto-complete window.
