### ISSUE TITLE
Feature request: backspace with "tabs replaced by spaces" deletes 1 tab's worth of spaces

### ISSUE THREAD

**Issue by gittymcgitface** [notepad-plus-plus/notepad-plus-plus#2176]
### Description of the Issue

Feature request such that when the preference for tabs to be replaced by spaces is enabled, any use of backspace should move the caret back by however many spaces are defined to make up 1 tab.

e.g. 

With tabs set to 4 spaces, tabbing out 3 times will get you to column 13.
At present if you press backspace 3 times, it will take you to column 10.
It should take you back to column 1 as you have deleted 3 tabs (encoded as spaces).

Also, if you go to column 14 for example, doing "shift tab" should take you back to column 13 but at present it takes you back to column 10!! This is really a separate bug, but I include it here in case the feature implementation is easily implemented at the same time.

Visual Studio can be configured this way and it saves you using your finger a lot!

Thanks.

**Comment by MetaChuh** [comment]
please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins if you update from version 7.5.9 or below.
if your issue still persists, and it is still of relevance to you, please feel free to file a new issue as easy to understand and reproducible as possible.

thank you for your help and best regards.

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
(no extra account is needed, just use your github account to sign in)
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)

**Comment by sasumner** [comment]
See also #1817

**Comment by dinkumoil** [comment]
I wrote a plugin that can activate the "Backspace unindents" Scintilla feature (and some more). Its name is _ExtSettings_. You can download it [>>> here <<<](https://sourceforge.net/projects/extsettings/). It will also be available soon via _PluginsAdmin_.

**Comment by gittymcgitface** [comment]
Thanks. Much appreciated.
