### ISSUE TITLE
No notification for not installed software

### ISSUE THREAD

**Issue by SinghRajenM** [notepad-plus-plus/notepad-plus-plus#2179]
### Description of the Issue

There is no notification for the user defined commands if there respective software is not installed.

### Steps to Reproduce the Issue

1. Open Notepad++
2. Open any file and select any text in it
3. Go to run and Click on (Launch in Firefox, Launch in Chrome, Launch in Safari or Send via Outlook). Make sure respective software is not installed.

### Expected Behavior

If the respective s/w is not installed, then user should get notification or error message.

### Actual Behavior

Nothing happens.

### Debug Information

Notepad++ v6.9.2
Build time : May 18 2016 - 00:34:05
Path : C:\Program Files\Notepad++\notepad++_org.exe
Admin mode : ON
Local Conf mode : OFF
OS : Windows 7
Plugins : DSpellCheck.dll mimeTools.dll NppConverter.dll NppExport.dll PluginManager.dll

**Comment by SinghRajenM** [comment]
Once changes (#2181) have been merged. This issue can be closed.

**Comment by SinghRajenM** [comment]
Closing the issue. Fix is submitted.

**Comment by christino156** [comment]
I use v7.2 of Notepad++ and I still have this problem (Windows 10).
When I select to Launch in Safari, absolutely nothing happens.

**Comment by SinghRajenM** [comment]
Fixed was submitted, but not merged. :(

**Comment by christino156** [comment]
Maybe we should re-open the issue then?
It is a bit frustrating when you select something and nothing happens.

**Comment by SinghRajenM** [comment]
I've submitted the fix again as N++ owner asked. Let's see what goes here. Thank you.
