### ISSUE TITLE
Macro character encoding regression

### ISSUE THREAD

**Issue by danielupstone** [notepad-plus-plus/notepad-plus-plus#2180]
### Description of the Issue

In previous versions, my macros for various commonly used symbols (e.g. en dash, em dash, trademark, etc.) worked fine. At some point (I suspect 6.9+) some of them started inserting a bunch of garbage symbols after them. When used in an ANSI document, they're fine, but I primarily work in UTF8. When inserting into other encodings, the encoding appears to break and multiple additional symbols are added. 
### Steps to Reproduce the Issue

1. Start recording new macro 
2. Enter Alt+0150 for an en dash
3. Stop recording new macro
4. Be in non-ANSI encoding
5. Playback macro
### Expected Behaviour

–
Only an en dash should be inserted.
### Actual Behaviour

–Iឤ𮊁ѽ:%
En dash followed by multiple broken encoding symbols is inserted.
### Debug Information

Notepad++ v6.9.2
Build time : May 18 2016 - 00:34:05
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10
Plugins : ComparePlugin.dll DSpellCheck2.dll mimeTools.dll NppConverter.dll NppExport.dll PluginManager.dll

**Comment by dail8859** [comment]
I can't seem to reproduce the issue. It always seems to work fine for me. My debug info...

```
Notepad++ v6.9.2
Build time : May 18 2016 - 00:34:05
Path : C:\npp.6.9.2.bin.minimalist\notepad++.exe
Admin mode : ON
Local Conf mode : ON
OS : Windows 7
Plugins : none
```

Maybe it is something specific to Win10.

**Comment by danielupstone** [comment]
Updating with new information.
This was happening at work and at home, both on Windows 10; however, my work system has recently received the version 1607 update, and since then this has stopped happening at work. It still continues at home. Both are running Notepad++ v6.9.2.
