### ISSUE TITLE
Syntax highlighting after opening from commandline

### ISSUE THREAD

**Issue by Koczka2** [notepad-plus-plus/notepad-plus-plus#2183]
### Description of the Issue

If I start the Notepad++ from command line as follows:

notepad++ -lMyLanguage myFile.ext
then the opened file does not take automatically the "user defined" language syntax.
### Steps to Reproduce the Issue
1. Define a "user defined language"
2. open a file from command line with that language name
### Expected Behavior

I would like to see the syntax-highlighted file wit my language
### Actual Behavior

file is opened without syntax highlighting
### Debug Information

Notepad++ v6.8.8
Build time : Dec 10 2015 - 01:11:37
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 7
Plugins : mimeTools.dll NppConverter.dll NppExport.dll PluginManager.dll 

Thank you!

**Comment by KptainBiwouak** [comment]
I have observed same issue using v6.9.2
It seems

**Comment by KptainBiwouak** [comment]
It seems syntax highlighting is not activated from command line

Le 19 août 2016 8:24 AM, "Kaptain Biwouak" <kaptain.biwouak@gmail.com> a
écrit :

> I have observed same issue using v6.9.2
> It seems
>

**Comment by Koczka2** [comment]
If I start from command line with a built-in language (e.g. xml), then it works. 
notepad++ -lxml myFile.ext
Only the "user defined language" seem to have an issue.

**Comment by MetaChuh** [comment]
please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins if you update from version 7.5.9 or below.
if your issue still persists, and it is still of relevance to you, please feel free to file a new issue as easy to understand and reproducible as possible.

thank you for your help and best regards.

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
(no extra account is needed, just use your github account to sign in)
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)
