### ISSUE TITLE
Default encoding setting ignored when opening a zero byte file.

### ISSUE THREAD

**Issue by mzso** [notepad-plus-plus/notepad-plus-plus#2185]
Hi!

I have UTF-8 set as the default, but when I open an empty 0 byte file either created by explorer via the context menu's "new" section or  with Total Commander NP++ uses ANSI instead.

The files should have whatever I set to default in NP++, because this is no different then opening a new file from within NP++.

**Comment by dail8859** [comment]
Duplicate of #1874.
