### ISSUE TITLE
Npp suddenly needs admin privileges

### ISSUE THREAD

**Issue by TBugReporter** [notepad-plus-plus/notepad-plus-plus#2189]
[This is probably the wrong place to post this, but all my attempts to sign up at notepad-plus-plus.org/community have failed.  In case someone can explain why the confirmation eMails aren't getting to me, my direct eMail is "the bug reporter @ gmail . com" (minus the quotes and spaces).]

### Description of the Issue
I have no idea why this started happening, but I can no longer use Npp on this computer unless I "Run as administrator".  Otherwise, the process starts, but seems to get stuck somehow, before I ever get a window/UI.

### Debug Information
I've tried uninstalling and reinstalling several times (which is how I discovered it needs admin privileges; it turns out the "Run Npp" option at the end of the install process runs it as admin, and for a while I thought the only way to run it a second time was to reinstall it.)  Anyone have a clue what could be going wrong here?

**Comment by dail8859** [comment]
Couple things to try. If you uninstall then make sure you remove any files hanging around either in the installation directory or in your %APPDATA% directory. Old settings and plugins may still hang around. Also try starting it with plugins disabled. You can either move the DLLs or start Notepad++ from the command line and pass in `-noPlugin`.

**Comment by TBugReporter** [comment]
I did these things the other times (or rather, I thought I did), plus I scanned the registry for leftovers (which is very difficult to do for a program named Notepad++; even searches for "npp" came up with hundreds of false positives), however, I chose to play along and went thru the routine again, and this time there were no problems.  Now I just have to reconstruct my many configuration tweaks - and hope that none of them puts me back where I was.

**Comment by dail8859** [comment]
Glad it is working. If you run across the issue again feel free to reopen.
