### ISSUE TITLE
issue

### ISSUE THREAD

**Issue by AshPriya** [notepad-plus-plus/notepad-plus-plus#2196]
When using session snapshots and file is cloned to second view, changes are no longer synced after restarting the application.
To reproduce:
1. Open file then select "Clone to Other View". Note how editing text in either view is reflected in both views.
2. Now without saving the file, restart Notepad++.
3. New changes are no longer synced between the views although though they refer to same file, even after saving.

**Comment by SinghRajenM** [comment]
I have a question here - 
How do you save file at step3?
1. If you simply use save, then notepad++ saves file only from single view. 
2. If you use Save All feature, then it will try to save two different files. But if you give the same name (over-write  existing), then both the views are synced.

And yes, if you make any change in saved file (opened in clone view as well) and restart the notepad without saving. This issue occurs, this time views are not synced :( .

**Comment by donho** [comment]
No reply, no treatment.
