### ISSUE TITLE
Plugin manager update - NP++ freezes when file is changed(reload confirm popup?) before confirmation restart

### ISSUE THREAD

**Issue by Canule** [notepad-plus-plus/notepad-plus-plus#2197]
### Description of the Issue

Plugin manager update, freezes when file is changed(reload confirm popup) before/while confirmation restart popup
### Steps to Reproduce the Issue
1. Wait for a plugin update (python indent) » click OK to update
2. Have an file modified just before/while the plugin manager ask for a restart(probably the reload modified file question popping up)
3. RIP
### Expected Behavior

Two pupups or "restart" popup closing the "file changed/reload" popup without freezing before showing up.
### Actual Behavior

Freezing np++ with the restart popup visible
After force quit/start, the restart confirm popup appears instant, w previous open files restored in tabs, n.p. to restart after OK
### Debug Information

Not found - win7 x64

**Comment by dail8859** [comment]
As of Notepad++ v7.5 the Plugin Manager is no long being shipped with Notepad++. See https://notepad-plus-plus.org/news/notepad-7.5-released.html

All Plugin Manager related issues should be reported to https://github.com/bruderstein/nppPluginManager/issues
