### ISSUE TITLE
Explorer 1.8.2 Locking up Notepad++ 6.9.2

### ISSUE THREAD

**Issue by jlar0che** [notepad-plus-plus/notepad-plus-plus#2198]
### Description of the Issue
The plugin Explorer (version 1.8.2) is not allowing Notepad++ to run. After launching Notepad++ the program never comes up, though it is listed in the process explorer. The fix for this is to place the Explorer plugin in the Disabled plugins directory.

### Steps to Reproduce the Issue

1. Install Explorer 1.8.2 plugin
2. Run Notepad++ 6.9.2

### Expected Behavior

Notepad++ should simply launch properly

### Actual Behavior

Program does not load up

### Debug Information

Notepad++ v6.9.2
Build time : May 18 2016 - 00:34:05
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 7
Plugins : mimeTools.dll NppConverter.dll NppExec.dll NppExport.dll NppFTP.dll NppSnippets.dll PluginManager.dll Python Indent.dll

**Comment by dail8859** [comment]
Looks like there is a discussion on the [forum](https://notepad-plus-plus.org/community/topic/12253/failure-to-launch/17). This issue needs reported to the author of Explorer.
