### ISSUE TITLE
Choice Chinese fonts name take no effect

### ISSUE THREAD

**Issue by efreeking** [notepad-plus-plus/notepad-plus-plus#220]
Click menu "Settings->Style Configurator", in "Style:" section, choice the "Default Style", in the "Font Style", if I choice the font which name with the Chinese characters, for example, "楷体", it take no effect.
![err1](https://cloud.githubusercontent.com/assets/3921471/8155508/917f727e-1377-11e5-8dba-1a4d006419cf.png)

**Comment by prclx323800** [comment]
After upgrading to 6.7.9 I also found this. No Chinese fonts can work in this version. Perhaps you should **uninstall 6.7.9 and reinstall 6.7.8(.2)** and wait for the bug to be solved.

**Comment by DongilKim** [comment]
Korean also.

**Comment by Lspeciosum** [comment]
Present version scintilla(x>3.5.3) accepts a font name only in utf-8.
But now npp font names are in CP_OEMCP.

> On Windows GDI, assume font names are encoded in UTF-8.

http://www.scintilla.org/ScintillaHistory.html
http://sourceforge.net/p/scintilla/bugs/1684/
https://groups.google.com/forum/#!topic/scintilla-interest/ti3PE4LDMNs/discussion

**Comment by DongilKim** [comment]
The same problem still occurs in version v6.7.9.2. in stylers.xml file, font is specified like this. The name of font is "나눔고딕코딩" and its UCS16LE expression is "98:B0:14:B2:E0:AC:15:B5:54:CF:29:B5".

<GlobalStyles>
<WidgetStyle name="Default Style" fontName="&#xB098;&#xB214;&#xACE0;&#xB515;&#xCF54;&#xB529;" />
</GlobalStyles>
