### ISSUE TITLE
The Notepad++ crashes when you try to click "Settings->Style Configurator"

### ISSUE THREAD

**Issue by uskovboris** [notepad-plus-plus/notepad-plus-plus#2200]
### Description of the Issue
The Notepad++ crashes when you try to click "Settings->Style Configurator"
### Steps to Reproduce the Issue
1. Launch NP++
2. Click on "Settings->Style Configurator" menu item with the Left Mouse Button

### Expected Behavior
The "Style Configurator" dialog is opened

### Actual Behavior
NP++ is crushed

### Debug Information

![nppstyleconf_bug](https://cloud.githubusercontent.com/assets/15656054/17883128/6158cd04-6919-11e6-87dc-b2de1e2c05ac.PNG)

**Comment by dail8859** [comment]
What commit are you using? Also, post the actual debug info under the `?` menu, it shows alot more information.

**Comment by uskovboris** [comment]
Notepad++ v6.9.2
Build time : May 18 2016 - 00:34:05
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : ON
Local Conf mode : OFF
OS : Windows 8.1
Plugins : none

**Comment by uskovboris** [comment]
Auh, I'm sorry. I had used a wrong build. I used x64 Unicode Release configuration when actually I had x86 editions of other NPP files. Now I downloaded x86 Unicode Release edition and will continue testing it. Thies is not a bug.
