### ISSUE TITLE
restart for update to windows, cancel restart and lose all open unsaved tabs and all open tabs.

### ISSUE THREAD

**Issue by davehorner** [notepad-plus-plus/notepad-plus-plus#2201]
### Description of the Issue

restart for update to windows, cancel restart and lose all open unsaved tabs and all open tabs.  this has happened a few times to me, but two times is pretty often. right after the cancellation of the restart, i will end up with one tab "new 1" and thats it.

all is not lost of course, it's easy to pull the backup from settings>preferences>Backup folder.
http://superuser.com/questions/975594/is-there-any-way-to-recover-unsaved-notepad-docs

though, if I can do that manually and now have two sets of files which represent my tabs at the last backup, you'd think notepad++ would have lost my tabs...
### Steps to Reproduce the Issue

1. Restart windows
2. Cancel restart
3. tabs are gone.
### Expected Behavior

the tabs i had unnamed, I had 36, I know a lot.
### Actual Behavior

1 tab. lost 36 tabs, some of which were unnamed.
### Debug Information

Notepad++ v6.9.2
Build time : May 18 2016 - 00:34:05
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 7
Plugins : mimeTools.dll NppConverter.dll NppExport.dll NppFTP.dll PluginManager.dll 

Thanks for a great tool.
--dave
http://dave.thehorners.com

**Comment by MetaChuh** [comment]
please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins if you update from version 7.5.9 or below.
if your issue still persists, and it is still of relevance to you, please feel free to file a new issue as easy to understand and reproducible as possible.

thank you for your help and best regards.

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
(no extra account is needed, just use your github account to sign in)
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)
