### ISSUE TITLE
Incorrect Folder As Workspace background color

### ISSUE THREAD

**Issue by uio139021** [notepad-plus-plus/notepad-plus-plus#2202]
### Description of the Issue

When awaken from S3 sleep, the Folder As Workspace view will sometimes use white(bright gray) background for erasing the areas surrounding the text instead of the selected text background color.
### Steps to Reproduce the Issue
1. Bring the Notepad++ window to front.
2. Put the computer to sleep.
3. Wake up the computer.
### Expected Behavior

The selected text background color.
### Actual Behavior

The white background.
### Debug Information

Notepad++ v6.9.2
Build time : May 18 2016 - 00:34:05
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 7
Plugins : mimeTools.dll NppConverter.dll NppExec.dll NppExport.dll NppFTP.dll PluginManager.dll 

![cc](https://cloud.githubusercontent.com/assets/21234143/17957351/b3ab4524-6a99-11e6-9ce2-db4b7e524095.PNG)

**Comment by hell-racer** [comment]
Also happens after PC lock-unlock, e.g.

1. Bring the Notepad++ window to front.
2. Lock the computer.
3. Unlock the computer.

**Comment by kireta** [comment]
Still an issue, using Obsidian theme. 

Notepad++ v7.5.6   (64-bit)
Build time : Mar 19 2018 - 00:23:17
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 7 (64-bit)
Plugins : DSpellCheck.dll mimeTools.dll NppConverter.dll

**Comment by DasLeo** [comment]
Same here with Zenburn

Notepad++ v7.5.6   (64-bit)
Build time : Mar 19 2018 - 00:23:17
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10 (64-bit)
Plugins : ComparePlugin.dll DSpellCheck.dll mimeTools.dll NppConverter.dll

**Comment by MetaChuh** [comment]
please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins if you update from version 7.5.9 or below.
if your issue still persists, and it is still of relevance to you, please feel free to file a new issue as easy to understand and reproducible as possible.

thank you for your help and best regards.

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
(no extra account is needed, just use your github account to sign in)
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)

**Comment by Mailzas** [comment]
Version 7.9.1
Plugins only default, same issue.

From tim e to time, software flashes, then I get incorrect workspace background color.

When I minimize / maximize it, it goes back to normal.
