### ISSUE TITLE
keybinding alt override windows default behavior

### ISSUE THREAD

**Issue by franzludilabel** [notepad-plus-plus/notepad-plus-plus#2205]
### Description of the Issue

If Im using the following keybinding : alt+l -> move cursor to the right (in scintilla commands tab), it does so but the menu Language (probably happening only on windows) is opening and dont close until I press escape key.
### Steps to Reproduce the Issue

1. go to keybindings, tab scintilla commands
2. select the line Name 'SCI_CHARRIGHT' and click the Modify button
3. adds the shortcut alt + l and save
4. go to your document, try to move the cursor to the right with alt + l, the menu Langage is opening and have the focus.
### Expected Behavior

If the user decides to set a keybinding with the alt key, its his responsability, the custom behavior should override the one opening the menu panel. 
### Actual Behavior

The menu is opening, preventing any other interaction with the editor until the panel is closed.
### Debug Information

![screenshot](https://cloud.githubusercontent.com/assets/11490568/17962966/9cd14208-6ab3-11e6-9c69-76aebdb3bb27.png)

**Comment by MetaChuh** [comment]
please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins if you update from version 7.5.9 or below.
if your issue still persists, and it is still of relevance to you, please feel free to file a new issue as easy to understand and reproducible as possible.

thank you for your help and best regards.

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
(no extra account is needed, just use your github account to sign in)
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)
