### ISSUE TITLE
_____NOTEPAD'S VULNERABILITY HACKED MY SYSTEM !!!!!_____

### ISSUE THREAD

**Issue by sng843ndf86nd8** [notepad-plus-plus/notepad-plus-plus#2207]
Nope. Lured. Sorry.

Wishlist with love to some professional C/C++ programmer with empathy.

1, [Auto-Delete of dual symbols]
Ability to remove Auto-Inserted part of dual characters (parentheses, brackets, braces, or other used defined), when user deletes the opening one (first half).
~Example~
User is going to write: print('this is python 3 syntax'), but he made a mistake while writing it as: print[.
NP++'s Auto-Complete’s Auto-Insert feature will make it like this: print[], with cursor between brackets. 
Now, it would be easy to press Backspace and delete both brackets, if feature would exist.

2, [Auto-Delete of tabbed spaces]
Ability to remove tabs replaced by spaces, by one keyboard hit of Backspace/Delete for each tab space. 
When it's set in Tab Settings in Preferences - four spaces means one tab length space in python (for example). 
~Example~
User made some tabbed spaces, but now want to delete a few from them. 
Not with Back-Tab (Shift + Tab shortcut), but simple Backspace/Delete key presses. 
Not four times (Backspace/Delete) button hit per each tab, but one per each tab if feature would exist.

3, [Reset Shorcut Mapper]
Ability to reset key bindings/keyboard shortcuts to default from GUI by mouse click. 
Not by some manual manipulation with files in NP++'s profile folder.

4, [Exclude numbers from Auto-Completion]
Ability to exclude numbers from Auto-Completion. 
And ability to exclude user specific strings/symbols from Auto-Completion per file or default for anything opened in future.

5, [Enlarge Find and Replace window]
Ability to enlarge Find and Replace window (Ctrl + H) for more comfortable multi lines operating. 
~Bug~
This window has in right down corner an enlarge mark, but it does not work (windows 7 ultimate 32 bit).
~Bug maybe~
When occurs tab space from very beginning of the line pasted into text field, it is visually longer than same tab space in middle of that text field. 

6, [Modify dock feature for mini windows]
~Example~
Dock Function List window to the left part of screen, below dock Folder as Workspace window. When it's double clicked on window’s header, it attaches to right part of screen and overlap Document Map window. 
When window is moved and resised manually, it’s not directly embedded to NP++ enviroment. Like this: [img]http://i.imgur.com/IBgufyZ.png[/img].
It is floating, so it’s overlapping Folder window. It needs to be docked/anchored.

7, [Multi-Select of objects in Foler as Workspace feature]
Ability to select more than one file object in Folder as Workspace feature (file explorer). With Ctrl, one by one and with Shift, as range.

8, [Set preferred side of mini windows]
Ability to set preferred side of screen for mini window opened on each start (plugin window for example).
NP++'s behavior is keeping last constellation of modified things (plugin windows too). 
Some settings, some window placements, is keeping on top of last used windows. 
~Example~
When user quits NP++ with last thing opened as Snippet plugin: [img]http://i.imgur.com/Age8Ifd.png[/img], it will shows again on next app start. 
But user needs to show Document map by default on each start like this: [img]http://i.imgur.com/QGiWDPl.png[/img]. 
so this particulary one plugin, is forcing NP++ to let him always on top (always up). 
It would need a feature setting, which would overwrite plugin’s settings and let NP++ decide what mini window will be always on top, based on user's choice.

9, [Verify NppExec plugin]
To verify NppExec’s plugin. During install, user sees it’s not verified: [img]http://i.imgur.com/7N3MOyF.png[/img].

10, [Python syntax highlighting]
For theme Ruby Blue. Nothing has been made so far for it. It's good theme between all dark ones and too colored ones.

11, [New Fold All/Unfold All keyboard shorcut]
To have one keyboard shorcut for both actions. Can be named like: “Toggle Fold All” (similar thing we have for comments. To toggle (Ctrl + Q)).
When user presses it once, it will do opposite as it is current situated in file (will fold everything in fresh opened document), when pressed again, will unfold everything back.
NP++ has two available keyboard shortcuts for it: Fold all (Alt + 0), Unfold all (Alt + Shift + 0).
It may be a waste or overkill for one type of action.
Nontheless, I have tried to bind both actions to one keyboard button. Didn’t work none of them.

12, [Warn user for conflict in Shortcut Mapper]
Ability to let know user for conflict situation, when same keyboard shorcut has been assigned to more than one action.
~Example~
When user installs plugin, which will have already binded some shortcut. It may be the same as user's personal keybind for other action.
Now, user have to go through all keybinds in Shortcut mapper manually. Moreover, NppMenuSearch plugin, won’t help anything in this situation (see point below).

13, [Improve NppMenuSearch plugin]
Because it can’t find keyboard shortcuts (Ctrl + D for Duplicate, for example). I tried it with modified search prompt - without spaces, first letter capital, or no capitals ...
User won't know which keybind (action name) is in conflict, so he has to search for keyboard shorcut (as Ctrl+D for example) and not for action name (Duplicate) !
OR

14, [New non-plugin search feature]
To have default NP++'s search feature inside of program, not as plugin. Plugin is not working as expected (explained above).
User is unable to get into place of searched thing. Unability to open pop-up related window, where found item is located + highlight it in that place.
~Example~
User searches for keyboard action “Fold all”. It finds it ok, but when he presses Enter to get to that place, nothing will happen.
I guess, it has no access to everything in NP++, as a plugin. Therefore, if this feature would be inside of NP++ as default part of program, it would open for user that Shortcut Mapper window, WITH highlighted row for searched “Fold all” keybind.

15, [Fix Shortcut Mapper for specific shortcut] 
I wanted to change shorcut keybind for Del Line Left and Del Line Right from default Ctrl + Shift + BackSpace and Ctrl + Shift + Delete to Shift + Backspace and Shift + Delete.
But it didn’t let me do do it for BackSpace one. It did let me for Delete one. But it didn’t work in praxis anyways.
So I edited it manually according to my needs.
See, that shortcut mapper sees it correctly from file:
[img]http://i.imgur.com/UcVjnzL.png[/img]
[img]http://i.imgur.com/h3Pe4lX.png[/img]
But it's still not working in praxis: DeleteLineLeft as Shift + Backspace and DeleteLineRight as Shift + Delete.
Here is correct keys for keyboard:
8 = backspace
46 = delete
2335 = del word left
2336 = del word right
2395 = del line left
2396 = del line right

16, [Improve NppExec plugin]
Ability to not adopt/take over/inherit/copy/pass on/transfer/transmit source text formatting from copied place (.pdf document for example).
~Example~
When user copy-pastes code snippet from other place into NppExec’s console, it will transfer also text source's formattings. Which is bad.

17, [Question: Multi-Edit]
How do a multi-editing, when NP++ shows same words in document, when user select one instance of them ?
Is this multi-highliting of same seleced word for some reason in NP++ ?
~Example~
If in a document, user has 8 times function name for example: my_function, and if user selects one instance of this name somewhere else in document, NP++ highlights all other instances of it in that file.
Is possible to edit all those instances in some time, at once, by editing just one example of it when all others are highlighted in that moment ?

18, [Question: How effectively continue in writing after finished parentheses]
Me, as a Python 3 beginner don't know what to do, when I face situations with finishing parentheses and then moving on with coding right after it.
Is best, to have turned off Auto-Insert for parentheses and write them manually from upper right sector of keyboard ? ; 
or have it turned on and try find End button with pinkie and lose base hand position for <jkl;> as for all 10 fingers writing ? ;
or some other way of non-known plugin for me or feature which other notepads have ?
I have looked into random code snippets and I see these are only possible actions after user writes something between parentheses:
- colon (after function definition, conditionals, loops)
- new line (after function call)
- 1 space (to continue write expressions in same line)
So computer won’t know what is user’s intention. Do you have any idea, how to solve it ?

More clear examples:
You either:
- Write manually function name: print, then write manually first parenthesis: (, and if turned on, NP++ will auto-insert closing one and put cursor in middle of them, so you may comfortably write an argument between parentheses.
But when you finish writing an argument between parenthesis, you have to either press Right arrow key or End key to be able continue write something else somewhere else. Which is not handy, because you have to use your pinkie and reach those buttons with effort and lose probably default all 10 finders writing position, because pinkie finger is short.
Simply you need to get to end of current text - current line.
or
- Write manually function name: print, then write manually first parenthesis: (, write manually argument: 'some_string_to_print', write manually closing parenthesis. Now, it' easy to continue with anything else in line, because you are already in the end of the line. But, you had to write closing parenthesis manually and there is place for mistakes (omitting closing ones in nesting for example).

So in ideal case, I would like to have parentheses auto-insert turned on, after argument is written, make computer somehow put cursor at the end of the line. So move cursor from middle of parentheses to right behind closing one ! Right behind it. To write colon, or Enter, or space, or tab.
How ? Is it possible anyhow ? 

Don Ho, if you are reading this and haven't time and interest to work on this project anymore, may you please make money contribution proposal on coding web site similar like Indiegogo or Kickstarter ? Some crowd funding site for coders who seek professional programmers to fill their requests for money.
I will propagate it and contribute money to it. You know, if I found urgent those things for NP++ and I'm just noobish coding beginner, it must be serious. I just don't understand why other experienced users were silent about it for years.
It's wasted time and I don't want just sit back and do nothing.

**Comment by donho** [comment]
Using  such title to draw attention is very bad practice.
After reading the first line I don't even bother to read the rest.
Sorry, I won't treat your FR.

**Comment by sng843ndf86nd8** [comment]
I was posting these (not all) requests for months. This is your first reply to it, ever.
You are the bad guy, not me.
And btw, nice excuse. You shouldn't be mainainer of this project anymore !
