### ISSUE TITLE
Intermittent crashes, files are usually saved, but painful nonetheless

### ISSUE THREAD

**Issue by cesinco** [notepad-plus-plus/notepad-plus-plus#2210]
### Description of the Issue
While working with Notepad++ (often when doing a "Search in files", but not necessarily - sometimes I just by setting focus on the app again), Notepadd++ stops working, a popup window appears with the text:

Notepad++ : a free (GNU) source code editor has stopped working

### Steps to Reproduce the Issue
1. Issue is intermittent - not sure what steps need to be taken to reproduce. It does appear to be an issue with plugins based on Visual Studio debugger.

### Debug Information
Notepad++ v6.9.2
Build time : May 18 2016 - 00:34:05
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10
Plugins : JSMinNPP.dll mimeTools.dll NppConverter.dll NppExport.dll NppFTP.dll NPPJSONViewer.dll NppTextFX.dll PluginManager.dll Tidy2.dll UniversalIndentGUI_NPP.dll XMLTools.dll XPatherizerNPP.dll 

### Also from Visual Studio debugger:

System.Runtime.InteropServices.COMException was unhandled
  Message=The handle is invalid. (Exception from HRESULT: 0x80070006 (E_HANDLE))
  Source=mscorlib
  ErrorCode=-2147024890
  StackTrace:
       at System.Runtime.InteropServices.Marshal.ThrowExceptionForHRInternal(Int32 errorCode, IntPtr errorInfo)
       at System.Runtime.InteropServices.Marshal.FreeHGlobal(IntPtr hglobal)
       at NppPluginNET.ClikeStringArray.Dispose()
       at NppPluginNET.ClikeStringArray.Finalize()
  InnerException:

**Comment by dail8859** [comment]
It is do to one of the plugins which use the NppPluginNET C# plugin code base. You'll have to figure out which one and report it to the plugin's developer.
