### ISSUE TITLE
Horizontal scroll bar does not get reset after making file empty

### ISSUE THREAD

**Issue by SinghRajenM** [notepad-plus-plus/notepad-plus-plus#2211]
### Description of the Issue

If a document has a horizontal scroll bar. The horizontal scroll bar does not get reset after clear all text (file is still saved, but no text). Even restarting notepad++ does not work in this case.
However, closing the file tab and reopening works fine.

### Steps to Reproduce the Issue

1. Open Notepad++
2. Type long text line until horizontal bar appears
3. Now remove all the text (either using backspace or ctrl+a and del)
4. Observe horizontal scroll bar

### Expected Behavior

When there is no text available in a file. horizontal scroll bar should not appear.

### Actual Behavior

Horizontal scroll bar continues to be there.

However, this is not the case with vertical scroll bar. Vertical scroll bar functionalities seems to be OK. 
### Debug Information

Notepad++ v6.9.2
Build time : May 18 2016 - 00:34:05
Path : C:\Program Files (x86)\Notepad++\notepad++_org.exe
Admin mode : ON
Local Conf mode : OFF
OS : Windows 7
Plugins : DSpellCheck.dll mimeTools.dll NppConverter.dll NppExport.dll PluginManager.dll 
![horizontalbar](https://cloud.githubusercontent.com/assets/14791461/17980774/74ae3914-6b1e-11e6-9230-49e6b62cfd83.png)

**Comment by A-R-C-A** [comment]
For performance reason scintilla does not narrowing the scroll width automatically. You can use one of the scripting plugins to update `SCI_SETSCROLLWIDTH` on your own.

**Comment by SinghRajenM** [comment]
ok

**Comment by RaphaelK12** [comment]
From https://superuser.com/questions/1098202/reset-horizontal-scroll-bar-width-in-notepad
Use the **Python Script** http://npppythonscript.sourceforge.net/ plugin with the following 1 line script:

`editor.setScrollWidth(1)`


This script has helped me a lot to get around this issue, but it would be nice to be able to perform this action when opening NP++, when reloading the file, having a button to perform this action, or running a background tread to check the length of the longest line in the file and then change the horizontal bar scale when needed.
