### ISSUE TITLE
Open File and Open an another instance has terrible functionality

### ISSUE THREAD

**Issue by SinghRajenM** [notepad-plus-plus/notepad-plus-plus#2212]
### Description of the Issue

Open File and Open an another instance under Run menu has terrible functionality. 

I'm saying terrible because of its behavior. I had a log file more than 10000 line. Unfortunately, I selected all the line (may for copy/paste). Then I tried to feature "open an another instance".
It ends up with showing multiple messaboxes after each other. I had no choice other than closing the whole process.

### Steps to Reproduce the Issue

1. Open a file in notepad++
2. Select few text or or whole text lines
3. Go Run -> Open an another instance
4. See the output

### Expected Behavior

It should open the same file in another instance of notepad++

### Actual Behavior

It gives n number of messageboxes (messagebox count is equal to total number of word selected in the file). saying file does not exist do you want to create or no..
If you say yes, it will create file in Notepad++ installation directory and shows messagebox for another word.
If no, then it shows messagebox for next word.

I personally feel that shortcut xml should be updated for "open file" and "Open an another instance".

### Debug Information

Notepad++ v6.9.2
Build time : May 18 2016 - 00:34:05
Path : C:\Program Files (x86)\Notepad++\notepad++_org.exe
Admin mode : ON
Local Conf mode : OFF
OS : Windows 7
Plugins : DSpellCheck.dll mimeTools.dll NppConverter.dll NppExport.dll PluginManager.dll 

![multiplemessagebox](https://cloud.githubusercontent.com/assets/14791461/17981553/ccc32b7a-6b21-11e6-85e8-5ac48b4a95f5.png)

**Comment by A-R-C-A** [comment]
Run commands are fully customizable, you can change them, delete them or add new ones. In your case replace CURRENT_WORD with FULL_CURRENT_PATH and you'll get the functionality you have described.

**Comment by SinghRajenM** [comment]
I know this. Just to avoid this kind of issue for other users. It is good to have CURRENT_WORD with FULL_CURRENT_PATH by default. 
Anyway, closing this request. As I know how to deal with it. :+1:
