### ISSUE TITLE
Syntax completion issues with inline html tags

### ISSUE THREAD

**Issue by pgibe** [notepad-plus-plus/notepad-plus-plus#2214]
### Description of the Issue

I've noticed a very odd issue in Notepad++ (version 6.9.2) using a PHP file with a string with inline html tags unclosed. The same issue is present in HTML files:

**the modify of an unclosed html inline tag changes the first html closing tag**.

n.b. Each Auto-insert flag in Auto-Completion menu is not checked.

### Steps to Reproduce the Issue

Try to write a simple code like this:
```html
    <html>
    <head>
    <link rel='a_closed_inline_link' />
    <link rel='an_opened_inline_link'>
    </head>
    </html>
```

### Expected Behavior

Change the second "link" tag in something other.
```html
    <html>
    <head>
    <link rel='a_closed_inline_link' />
    <something_other rel='an_opened_inline_link'>
    </head>
    </html>
```

### Actual Behavior

The first html closing tag is changed as well:
```html
    <html>
    <head>
    <link rel='a_closed_inline_link' />
    <something_other rel='an_opened_inline_link'>
    </something_other>
    </html>
```

### Debug Information

Notepad++ v6.9.2
Build time : May 18 2016 - 00:34:05
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10
Plugins : DSpellCheck2.dll mimeTools.dll NotepadSharp.dll NppConverter.dll NppExport.dll NppFTP.dll NppQCP.dll NppScripting.dll NppTextFX.dll PluginManager.dll SpellChecker.dll 

![20160826_notepad _bug_01](https://cloud.githubusercontent.com/assets/16954247/18006853/f50b9f1a-6ba1-11e6-8878-1ddaaeb55657.png)
![20160826_notepad _bug_02](https://cloud.githubusercontent.com/assets/16954247/18006857/f87c3dc6-6ba1-11e6-9f57-9cce8d5d63c8.png)

**Comment by dail8859** [comment]
This is not default behavior of Notepad++. It is one of your plugins doing it (Probably NotepadSharp)

**Comment by pgibe** [comment]
Thank you. I will perform some test after uninstalling the plugin and than I will report it to the developer of the plugin istelf.
