### ISSUE TITLE
[BUG] Individual replacements don't work with regex lookbehind

### ISSUE THREAD

**Issue by aaaxx** [notepad-plus-plus/notepad-plus-plus#2216]
### Description of the Issue

If there's a lookbehind in the search string, clicking the "Replace" button will skip to the next match without replacing anything. (Using "Replace All", however, works fine and replaces all matches.)
### Steps to Reproduce the Issue

Try searching for something like `(?<=a).` and replacing it with something by clicking the "Replace" button.
### Debug Information

Notepad++ v6.9.2
Build time : May 18 2016 - 00:34:05
Path : D:_D - apps\Notepad++ Portable\App\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : ON
OS : Windows 8.1
Plugins : combine.dll ComparePlugin.dll DSpellCheck.dll ElasticTabstops.dll IndentByFold.dll mimeTools.dll NppConverter.dll NppExport.dll NppFTP.dll NppTextFX.dll PluginManager.dll ScrollPastEOFUni.dll SnippetPlus.dll

**Comment by MetaChuh** [comment]
please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins if you update from version 7.5.9 or below.
if your issue still persists, and it is still of relevance to you, please feel free to file a new issue as easy to understand and reproducible as possible.

thank you for your help and best regards.

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
(no extra account is needed, just use your github account to sign in)
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)

**Comment by sasumner** [comment]
Lookbehind can't reasonably work when finding matches one at a time.  Replace All is the best strategy here.
