### ISSUE TITLE
issue about the File tab

### ISSUE THREAD

**Issue by nadeesh19** [notepad-plus-plus/notepad-plus-plus#2217]
### Description of the Issue

if we click the file tab in the menubar of the Notepad++ V 6.9.2 ,the content of that tab takes whole screen and it covers other tabs in menu bar. it is not like other tabs menu as Edit; Search; ... Notepad++ is running on windows 10.
### Steps to Reproduce the Issue

1. open Notepad++ 
2. click one tab of the menu bar without File tab.( to see different) 
3. then click File tab and see different between how to display File tab and other tabs. 
### Expected Behavior

I would expect the menu of the File tab also be other Tab menu.

these are the screenshot of  File tab and Edit tab 
![issue_01](https://cloud.githubusercontent.com/assets/10229154/18026692/4e27258a-6c6d-11e6-84e5-860003b827cb.png)
![issue_01_answertype](https://cloud.githubusercontent.com/assets/10229154/18026693/4e35cb3a-6c6d-11e6-95e4-114aeca96e85.png)

**Comment by MAPJe71** [comment]
Check your recent file history settings.

**Comment by nadeesh19** [comment]
until clear recent file , it happens . but i think it must be enhanced like fixed size of File tab content.

**Comment by MAPJe71** [comment]
Select menu `Settings`, select `Preferences...`, make sure `Recent File History` is active and change the settings in the `Display` area to get a narrow `File` menu.

For example:
![Recent File History Settings](https://c3.staticflickr.com/9/8251/28983119130_ffa4c08a51_b.jpg)
