### ISSUE TITLE
Newly opened file is not activated

### ISSUE THREAD

**Issue by Yaron10** [notepad-plus-plus/notepad-plus-plus#2220]
STR:
Have one file open.
Save Session (s1.ses).
Close that file.
Open another file.
Save Session (s2.ses).
Close that file.

Open s1.ses.
Open s2.ses.

Result:
s2.ses is not activated (`activeIndex="0">`).
IMO it's not the expected behavior.

---

A more common use-case:
Save a session of two files in both views

`<NotepadPlus>
    <Session activeView="0">
        <mainView activeIndex="0">
            <File firstVisibleLine="0" xOffset="0" scrollWidth="514" startPos="0" endPos="0" selMode="0" lang="JavaScript" encoding="-1" filename="C:\test1.js" backupFilePath="" originalFileLastModifTimestamp="1462018931" />
        </mainView>
        <subView activeIndex="0">
            <File firstVisibleLine="0" xOffset="0" scrollWidth="514" startPos="0" endPos="0" selMode="0" lang="JavaScript" encoding="-1" filename="C:\test2.js" backupFilePath="" originalFileLastModifTimestamp="1460153093" />
        </subView>
    </Session>
</NotepadPlus>
`

and another of two different files in both views

`<NotepadPlus>
    <Session activeView="0">
        <mainView activeIndex="0">
            <File firstVisibleLine="0" xOffset="0" scrollWidth="514" startPos="0" endPos="0" selMode="0" lang="JavaScript" encoding="-1" filename="C:\test3.js" backupFilePath="" originalFileLastModifTimestamp="1462018931" />
        </mainView>
        <subView activeIndex="0">
            <File firstVisibleLine="0" xOffset="0" scrollWidth="514" startPos="0" endPos="0" selMode="0" lang="JavaScript" encoding="-1" filename="C:\test4.js" backupFilePath="" originalFileLastModifTimestamp="1460153093" />
        </subView>
    </Session>
</NotepadPlus>
`

Open the first session file and then the second.
- The second pair of files are not activated.

Thank you.

**Comment by MetaChuh** [comment]
hi @Yaron10 

this is by design.

the current active tab maintains its focus if an additional session is loaded.
e.g. if we are editing one file and additionally want to load a bunch of other files from a session, the currently edited tab will stay in focus.

thank you for your help and best regards.

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
(no extra account is needed, just use your github account to sign in)
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)
