### ISSUE TITLE
Continue to Find after document end

### ISSUE THREAD

**Issue by alafr** [notepad-plus-plus/notepad-plus-plus#2224]
When I use the `Find (Ctrl+F)` function and I reach the document end, Notepad++ tells me that it couldn't find the text. Is there an option I could activate so that it starts over from the beginning of the document when this happens? There is the `Find Volatile Next` function in the menu, but I didn't see the same function in the `Find` dialog.
Thanks

**Comment by yoedstavi** [comment]
It's called "Wrap around".
It's a checkbox.
it's under "Match whole word only" and "Match case"

**Comment by alafr** [comment]
Thank you!
