### ISSUE TITLE
Garbage characters

### ISSUE THREAD

**Issue by victormunoz** [notepad-plus-plus/notepad-plus-plus#2226]
### When working with big text files (more than 10Mb), sometimes garbage characters appear suddenly while editing

Even though the option to show all characters is not activated, sometimes at a given unexpected time the garbage characters appear anyway. If I then activate the "all characters" option, more of this garbage characters appear, as expected (most of them end lines), and if I then deactivate the option, the added ones (end lines mostly) disappear also as expected, but the ones that appeared unexpectedly remain.

The garbage characters only appear starting from the line I am editing and down to the end of the file.

Once they appear, the file turns corrupt if you save it. I have to discard all the unsaved changes, close the file and reopen it again to continue working.

![sin titulo](https://cloud.githubusercontent.com/assets/12271074/18079244/e9adbff4-6e8f-11e6-8f2e-a0cf3416ebc3.png)

### Steps to Reproduce the Issue

It's hard to reproduce the issue, it just happens sometimes (not very frequent). I suspect it has something to do with the repetitive usage of combinations like Right, Ctrl+Right, Shift+Right, Ctrl+Shift+Right but I can't create a sequence of steps that always produces the garbage characters to appear.
### Debug Information

My actual version of Notepad is:
Notepad++ v6.9.2
Build time : May 18 2016 - 00:34:05
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 7
Plugins : ComparePlugin.dll mimeTools.dll NppConverter.dll NppExport.dll NppFTP.dll NppTextFX.dll PluginManager.dll XMLTools.dll 

This issue has been happening to me for a long time, in many versions. But I have never reported this... since now.

**Comment by dail8859** [comment]
In the past this is usually a symptom of having session snapshots enabled. I routinely work with large files and never used this option due to this exact problem. 

See if you have `Settings > Preferences > Backup > Enable session snapshot and periodic backup` turned on. If so turn it off and see if the issue reoccurs at all.

**Comment by victormunoz** [comment]
Yes, I have session snapshots turned on. I will try to turn it off and see if it works. Thank you

**Comment by donho** [comment]
I believe this issue has been fixed since long time ago.
Update your Notepad++ to the latest version (v7.6.6).
If the issue persists, please create a new issue for it.
Thank you.
