### ISSUE TITLE
Can't we have search file  option among opened tabs?

### ISSUE THREAD

**Issue by pran27gore** [notepad-plus-plus/notepad-plus-plus#2227]
### Description of the Issue

Currently we cannot search file with its name if there are multiple files open in tabs. We have to go through each tab. Can we provide such feature? Same feature is available in all other IDEs. Or we  can have dropdown listing all opened files.
### Steps to Reproduce the Issue

1. 
2. 
3. 
### Expected Behavior

Notepadd++ should have dropdown listing all opened files and search option to identify them.
### Actual Behavior

Currenlty we do not have any such feature.

**Comment by Golgothan3** [comment]
I'm having a bit trouble understanding what you're asking for (if I do understand, I like what you're saying, but I'm not sure if I'm understanding properly). Are you saying that when you use "Find" you want to be able to choose to search among all the open documents? Because that is a feature. However I may be misunderstanding. Sorry if so.

**Comment by cmeriaux** [comment]
Do a Ctrl+Tab then you'll have a dropdown list of opened file

**Comment by young-developer** [comment]
As alternative you could use NavigateTo plugin. It allows navigate between opened files very quickly.
https://github.com/young-developer/nppNavigateTo/releases
We discuss all features and enhancements here - https://notepad-plus-plus.org/community/topic/12892/navigateto-navigate-between-files-tabs-quickly-like-a-ninja-d

**Comment by MetaChuh** [comment]
please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins if you update from version 7.5.9 or below.
if your issue still persists, and it is still of relevance to you, please feel free to file a new issue as easy to understand and reproducible as possible.

thank you for your help and best regards.

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
(no extra account is needed, just use your github account to sign in)
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)
