### ISSUE TITLE
Find in files using mouse => popup failure and main window minification

### ISSUE THREAD

**Issue by v1nce** [notepad-plus-plus/notepad-plus-plus#2228]
Using mouse to activate menus under search/ work except for "find in files" (sorry I don't have the exact english terms, in french it's called "rechercher dans les sous-dossiers)"

Opening search dialog (by mouse or keyboard) and going to "find in files" (not translated by the way) is ok.

But

When I use the mouse to  activate menu Search/"find in files", the main window vanishes (width = around 150px,20px at 20,20 coordinates from top left of screen) and no popup opens.
After I resized the main window and used the keyboard shortcut (ctrl + shift + f) then the main windows is ok but the search popup appears at 0,0 and not at the last position.
Moving the dialog and escaping then reopening (Ctrl Shift F) the position is remembered

v6.6.9 windows 10 or windows 7
no fancy tool (keyboard hooks or window manager) of any sort except for greenshot (screenshot) and winxkill

**Comment by A-R-C-A** [comment]
Try the newest version 6.9.2 and see if it happens again.

**Comment by MetaChuh** [comment]
please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins if you update from version 7.5.9 or below.
if your issue still persists, and it is still of relevance to you, please feel free to file a new issue as easy to understand and reproducible as possible.

thank you for your help and best regards.

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
(no extra account is needed, just use your github account to sign in)
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)
