### ISSUE TITLE
Enhancement: squared selection

### ISSUE THREAD

**Issue by v1nce** [notepad-plus-plus/notepad-plus-plus#2229]
Please allow us to switch to squared selection AFTER we selected text.

Right now I always hit Alt a fraction of time after I started to select text so I got to retry and make sure i hit Alt before I select.

**Comment by dail8859** [comment]
As a solution for now you can install LuaScript (via the Plugin Manager) and select `Plugins > LuaScript > Edit Startup Script` and add the following:

```lua
editor1.MouseSelectionRectangularSwitch = true
editor2.MouseSelectionRectangularSwitch = true
```

This will allow you to press `Alt` after selecting to turn it into rectangular mode.

**Comment by szegi** [comment]
`-- Startup script
-- Changes will take effect once Notepad++ is restarted

editor1.MouseSelectionRectangularSwitch = true
editor2.MouseSelectionRectangularSwitch = true`

doesn't work for me:/

**Comment by dail8859** [comment]
Ah yeah you are right. Try this instead:

```lua
npp.AddEventHandler("OnReady", function()
    editor1.MouseSelectionRectangularSwitch = true
    editor2.MouseSelectionRectangularSwitch = true
end)
```

**Comment by szegi** [comment]
Still the same
ALT
makes Bar Menu visible

on default i have all menus hidden

**Comment by dail8859** [comment]
No clue then. Works fine for me.

**Comment by szegi** [comment]
Alt makes underscore when menu bar is active
i show on gif
maybe i make something wrong
![2016-09-12_14-54-32](https://cloud.githubusercontent.com/assets/12111506/18436512/02d1a338-78f9-11e6-9889-5bb704d114d2.gif)

**Comment by dail8859** [comment]
Oh...you'll have to press Alt *while* dragging. Unfortunately there's no easy way to change it afterwards.

**Comment by MetaChuh** [comment]
please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins if you update from version 7.5.9 or below.
if your issue still persists, and it is still of relevance to you, please feel free to file a new issue as easy to understand and reproducible as possible.

thank you for your help and best regards.

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
(no extra account is needed, just use your github account to sign in)
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)
