### ISSUE TITLE
HEX-Editor cannot use Insert key to switch INS/OVR mode

### ISSUE THREAD

**Issue by KrasnayaPloshchad** [notepad-plus-plus/notepad-plus-plus#2232]
### Description of the Issue
The current version of HEX-Editor cannot switch INS/OVR mode by Insert key.

### Steps to Reproduce the Issue
1. Open N++, press Insert key can switch INS/OVR mode
2. Click “View in HEX” button on the toolbar, or Plugin --> HEX-Editor --> View in HEX, the Insert key doesn’t work 
3.  Click “View in HEX” button (or Plugin --> HEX-Editor --> View in HEX) again, the Insert key work.

### Expected Behavior
The Insert key should also works with Hex Edit View, both INS and OVR mode should works in this view. I think [Madedit-Mod](https://sourceforge.net/projects/madedit-mod/) have set an good example on this.

**Comment by dail8859** [comment]
Since this is a problem with a 3rd party plugin you'll have to report this issue to that developer. (Though I doubt the HEX editor is being developed any more).

**Comment by KrasnayaPloshchad** [comment]
Thanks. 🤝
