### ISSUE TITLE
Automatic save/restore file's last used encoding

### ISSUE THREAD

**Issue by PauloFrancaLacerda** [notepad-plus-plus/notepad-plus-plus#2234]
Is there any option for making NP++ remember the last used encoding for an ANSI text file?

I have a text file that contains especial ANSI characters (correcly rendered by CodePage Win-1252), but NP++ won't store/load the last used encoding for the file. As it's ANSI, there's no BOM that NP++ could read. 

Currently, I am following these steps every time I open the file...
1. Click the [Encoding] menu;
2. Click the [Character Sets] submenu;
3. Click the [Western European] submenu;
4. Click the [Windows-1252] submenu.

...then the characters finally look like as it should.

I think NP++ should store this kind of information somewhere (user-defined location, preferably).
Is there such option already? 
P.S.: I don't want to go Unicode. I need my file to remain a "simple" Western European, Windows-1252 ANSI text file. :)

Thanks in advance.

**Comment by MetaChuh** [comment]
please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins if you update from version 7.5.9 or below.
if your issue still persists, and it is still of relevance to you, please feel free to file a new issue as easy to understand and reproducible as possible.

thank you for your help and best regards.

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
(no extra account is needed, just use your github account to sign in)
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)
