### ISSUE TITLE
Wrong C++ comments highlighting

### ISSUE THREAD

**Issue by slypiggies** [notepad-plus-plus/notepad-plus-plus#2235]
### Expected Behavior
"is not available on linux" should be highlighted with light green.

### Actual Behavior
See the screenshot.

### True Fact
This code do compile, without any error.

### Screenshot
![notepadpp](https://cloud.githubusercontent.com/assets/21236048/18168884/6a7b84da-708a-11e6-994a-d6934c613303.png)

**Comment by dail8859** [comment]
This is due to your custom theme "VS2012 Dark" not defining a style for preprocessor comments. Take a look at PR #1178 which added this into the built in themes. You'll probably have to edit your theme's xml manually to add that in.

**Comment by slypiggies** [comment]
### Thanks!
![notepadpp](https://cloud.githubusercontent.com/assets/21236048/18174622/aed9a506-70a0-11e6-8885-ef86043dd515.png)
