### ISSUE TITLE
Plugin receiving unexpected notification

### ISSUE THREAD

**Issue by dail8859** [notepad-plus-plus/notepad-plus-plus#2237]
### Description of the Issue

A plugin can receive a notification from a Scintilla instance that is _not_ one of Notepad++'s 2 Scintilla instances.  I happen to run across this when coding up a few of my plugins.

The screenshot below shows a plugin receiving a wrong notification:
![plugin](https://cloud.githubusercontent.com/assets/3694843/18187863/3ba87c4e-707b-11e6-9e80-ab0800d02592.png)

The marked parts of the image:
1. The handles of Notepad++ and it's 2 Scintilla instances.
2. At a breakpoint the `hwndFrom` is from some unknown handle.
3. The notification carries text from the _other_ plugin. It should never receive this.
### Steps to Reproduce the Issue
1. Have a plugin which during `setInfo()` uses `NPPM_CREATESCINTILLAHANDLE` and adds text to that newly return scintilla instance. 
2. Another plugin will receive `SCN_MODIFIED` notifications from the instance.

It seems that it only does it if it the text is added during `setInfo()` but is fine if the text is added when waiting until receiving `NPPN_READY`. 
### Expected Behavior

To receive notifications from either Notepad++ or one if it's 2 Scintilla instances.
### Debug Information

```
Notepad++ v7   (32-bit)
Build time : Sep  1 2016 - 02:21:07
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : ON
Local Conf mode : OFF
OS : Windows 7
Plugins : ComparePlugin.dll DoxyIt.dll DSpellCheck2.dll ElasticTabstops.dll GuidHelper.dll LuaScript.dll mimeTools.dll NppConverter.dll NppExport.dll NppFTP.dll PluginManager.dll 
```

**Comment by dail8859** [comment]
Partially related to #1500 which never got any explanation.

**Comment by dail8859** [comment]
Attached is a zip of a VS solution which creates 2 bare minimum plugins. One of them creates a scintilla instance and the other asserts that it doesn't receive a message from it. Build the solution and copy the 2 plugins over to Notepad++'s plugin directory. The one will cause an assertion error.

I tried digging into this since but I don't know enough to understand the entire sequence of events going on within Notepad++.

[PluginError.zip](https://github.com/notepad-plus-plus/notepad-plus-plus/files/452748/PluginError.zip)

**Comment by dail8859** [comment]
And now I also found out I'm receiving notifications from `_invisibleEditView`!

**Comment by donho** [comment]
The plugin could receive all the Scintilla created by Notepad++ (including _invisibleEditView) so it's necessary and important that plugin filters the scintilla controls (by using hwndFrom). This might be good on the plugin document, at least in the comment of plugin header.

**Comment by sasumner** [comment]
Is there any reasonable use by a plugin author for receiving notifications that aren't from one of the two user views?  If not, I'd think that N++ code should be changed to not send those.  But, what do I know? :)

**Comment by Ekopalypse** [comment]
@sasumner, yes, for example in cases like discussed [here](https://notepad-plus-plus.org/community/topic/17631/assign-language-by-line/22).

**Comment by dail8859** [comment]
Thanks @donho, was not sure if it was expected or not. Was just surprised when I first noticed the behavior.
