### ISSUE TITLE
coding format

### ISSUE THREAD

**Issue by zivsu** [notepad-plus-plus/notepad-plus-plus#2238]
### Description of the Issue

Does notepad++ support Uyghur language of chinese? I open the file, but show me is Arabic language(maybe)

### Steps to Reproduce the Issue

1. open the file include Uyghur language

### images
![image](https://cloud.githubusercontent.com/assets/8110132/18191101/49004db6-70fa-11e6-9f33-96d2773e8eb5.png)

**Comment by zivsu** [comment]
![image](https://cloud.githubusercontent.com/assets/8110132/18191096/3a2a0da4-70fa-11e6-8db3-262468e5da8d.png)

**Comment by PauloFrancaLacerda** [comment]
Have you already tried out the available encodings from the [Encoding -> Character Sets] menu?

**Comment by PauloFrancaLacerda** [comment]
I've just loaded a Uyghur text (from Wikipedia) into NP++ and chosed "Big5" from the [Encoding > Character Sets > Chinese] menu. The results are exactly as appears in Wikipedia:

`Uyghur: ئۇيغۇر تىلى, Уйғур тили, Uyghur tili, Uyƣur tili or ئۇيغۇرچە, Уйғурчә, Uygurche, Uyƣurqə`
