### ISSUE TITLE
Comments in Preprocessor Highlighted Incorrectly 

### ISSUE THREAD

**Issue by slypiggies** [notepad-plus-plus/notepad-plus-plus#2242]
This is the weirdest highlighting I have ever seen in a text editor!

### Screenshot
![untitled](https://cloud.githubusercontent.com/assets/21236048/18230622/cea57c68-72d3-11e6-93eb-5a5f74d07873.png)

The colour of `/*comment1*/` is wrong, while that of `/*comment2*/` is correct. Weird!

### Note
This code do compile, without any error.

**Comment by MAPJe71** [comment]
Is the same issue as or at least related to #2235 ?

**Comment by slypiggies** [comment]
No, I don't think so. That issue is also opened by me. In that case, the comments don't get any highlighting. In this case, the comments get the highlighting of preprocessors.

**Comment by dail8859** [comment]
> This is the weirdest highlighting I have ever seen in a text editor!

Also the weirdest coding style ;)

This issue appears to also be in the latest version of Scintilla (the component that does the parsing). You'll have to report this issue to that project [here](https://sourceforge.net/p/scintilla/bugs/).

**Comment by slypiggies** [comment]
Yo @dail8859, happy to see you again :D
As you mentioned, this issue appears to also be in the latest version of Scintilla. I do report it on [https://groups.google.com/d/forum/scite-interest](https://groups.google.com/d/forum/scite-interest), and a developer called KHMan replied,

> You've hit a dusty corner of the editor. The C/C++ syntax 
highlighting does not parse the source code exactly like a proper 
C/C++ compiler (as in following the parsing phases in the ISO C 
standards doc for instance), so for many syntax highlighting, 
there will be a number (or sometimes, a lot) of dusty corner 
cases. For some languages, reports such as yours are not uncommon 
(Perl comes to mind). 

> In normal use, dusty corner cases is rarely a problem. IMHO as a 
contributor to some syntax highlighting stuff in the editor, I do 
not target perfection. To be truly syntax-accurate, hundreds of 
man-hours will be needed. Folks here, of course, welcome 
contributions, patches, etc... 

After reading this, I am not sure if they are willing to fix this _dusty corner_. LOL.
Anyway, thanks @MAPJe71 and @dail8859 for the replies!
