### ISSUE TITLE
Latest versionin 

### ISSUE THREAD

**Issue by muratia** [notepad-plus-plus/notepad-plus-plus#2244]
Today while the file has been changed on background by other app it crashed. And in the Events Viewer it reports this.

Application: notepad++.exe Framework Version: v4.0.30319 Description: The process was terminated due to an unhandled exception. Exception Info: exception code e0434f4d, exception address 747996C2

**Comment by dail8859** [comment]
Most likely this is due to a plugin. Disable your plugins to see if this happens again. 

If it happens with them disabled please provide a set of steps to reproduce the issue and your debug info.
