### ISSUE TITLE
Update check dialog goes behind when "Always on top" option is active

### ISSUE THREAD

**Issue by snalesso** [notepad-plus-plus/notepad-plus-plus#2246]
### Description of the Issue

When the option "Always on top" is enabled, if you check or updates, and there is no newer version available, Notepad++ shows a dialog that says "No update is available.". But the dialog appears behind the editor, and the user may not notice it.
### Steps to Reproduce the Issue
1. Open Notepad++
2. Restore down the window, give it a medium size (height and width both >= 200 px) and center it
3.  Click on menu item "View"
4.  Check "Always on Top"
5. Click on menu item "?"
6. Click on "Update Notepad++"
7. If there are no available updates, you'll notice a window opened on the Windows taskbar, but it isn't visible since it is behind the Notepad++ window
### Expected Behavior

The "No update is available" message box should be visible on top of the Notepad++ window.
### Actual Behavior

The "No update is available" message box is visible behind the Notepad++ window.

![image](https://cloud.githubusercontent.com/assets/6681799/18243226/721a78c2-735a-11e6-8356-14bd991d62eb.png)

**Comment by MetaChuh** [comment]
please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins if you update from version 7.5.9 or below.
if your issue still persists, and it is still of relevance to you, please feel free to file a new issue as easy to understand and reproducible as possible.

thank you for your help and best regards.

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
(no extra account is needed, just use your github account to sign in)
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)
