### ISSUE TITLE
PHP 5 error level constants not highlighted

### ISSUE THREAD

**Issue by GreenReaper** [notepad-plus-plus/notepad-plus-plus#2247]
### Description of the Issue
PHP's syntax highlighter does not highlight the following [error level constants](http://php.net/manual/en/errorfunc.constants.php):
E_STRICT, E_RECOVERABLE_ERROR, E_DEPRECATED, E_USER_DEPRECATED

### Steps to Reproduce the Issue
1. Open a .php file, which is highlighted in PHP language mode.
2. Enter any of the above phrases.

### Expected Behavior
They should be highlighted, like E_WARNING.

### Actual Behavior
They are plain text.

### Debug Information
Notepad++ v6.9.2
Build time : May 18 2016 - 00:34:05
Path : C:\Program Files\Accessories\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows Vista
Plugins : ComparePlugin.dll docMonitor.dll mimeTools.dll NppConverter.dll NppExport.dll NppFTP.dll NppNetNote.dll NppTextFX.dll PluginManager.dll SpellChecker.dll

![phperrortypes](https://cloud.githubusercontent.com/assets/383043/18253840/f13d6f58-738f-11e6-96fb-f9f91f3a9be2.png)

**Comment by dail8859** [comment]
These were added in 5fa40fbf7e5c2385da2420014c89e8cc7fda059d (i.e. v6.8)

Deleting your `langs.xml` file should solve this but keep in mind this also stores extra settings such as additional keywords if you have set any. 

Related to #1205

**Comment by GreenReaper** [comment]
Indeed, it does! And I don't think I had, no.
