### ISSUE TITLE
Unable to open Notepad++ after installing powershell lexer plugin via plugin manager

### ISSUE THREAD

**Issue by preeyakrish91** [notepad-plus-plus/notepad-plus-plus#2251]
### Unable to open Notepad++
 After installing `powershell lexer` plugin using plugin manager, unable to open notepad++ 

### Steps to Reproduce the Issue
Set of steps to reproduce this issue
1. Install powershell lexer plugin via plugin manager. 
2. plugin installed and restarted the notepad++
3. Notepad starts, but automatically get crashed without any error message

### Expected Behavior
Notepad++ should start

### Actual Behavior
Notepad++ crashed

### Version
Notepad ++ - npp.6.9.2.Installer 
OS: Windows 10 64 bit
Plugin: Powershell lexer

**Comment by dail8859** [comment]
Since this is related to a 3rd party plugin you'll have to report it to the developer of the PowerShell Lexer.
