### ISSUE TITLE
New Feature Merge Lines in Coloumn Mode

### ISSUE THREAD

**Issue by Born2Root** [notepad-plus-plus/notepad-plus-plus#2252]
### Description of the Issue

In Coloumn Mode I want to merge several lines by pressing Delete button. That should remove the not printed \n behind each line.
### Steps to Reproduce the Issue

1. Open a new text document with the lines. Add the text

```
a
b
c
```
1. Now switch to Coloumn Mode, mark all three lines behind the letters.
2. Press Delete Button --> Nothing occurs
### Expected Behavior

After pressing Delete Button the line breaks should be deleted.
As a result the three lines should look like: `a b c`
AND the three Cursors of the Coloumn Mode should still be visible between the single letters (Switch to multi editing mode)
Visualized as | it should look like: `a | b | c`
Afterwards I can press any key, to insert additional signs, like in multi editing.
Result should be after pressing the plus key: `a + b + c`
### Actual Behavior

Nothing
### Debug Information

I switched from "Sublime Text" to Notepad++. In Sublime this function was implemented, and I'm missing it in Notepad. A Workaround through "Find And Replace" is possible, but it's more complicated and not so sweet like in coloumn mode.

See here a picture how it looks in Sublime
![unbenannt](https://cloud.githubusercontent.com/assets/8644900/18306736/77a4b6ba-74ed-11e6-8642-2abf65eb09a7.JPG)

**Comment by cmeriaux** [comment]
:+1:

**Comment by ThereOHM** [comment]
I really like that! 
I have one addition to that:
You desribed how to merge the lines in coloumn mode. I have often the need to put in blank lines.
So when I'm in Coloumn Mode the following behaviour would be nice.
1. Switch to Coloumn Mode (like your Step 1)
2. Press Return --> Blank Lines are inserted between lines

At the moment I use the workaround with Regular Expression Search & Replace.
Search for ^(.+)$ and replace with \n\1
But that's actually not really nice...

Would be really great, if the feature would be implemented!

**Comment by MetaChuh** [comment]
please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins if you update from version 7.5.9 or below.

then use multi editing as seen at the screencast below:

![7 6 6 multi editing](https://user-images.githubusercontent.com/45773305/57958072-cf82e880-78fe-11e9-94c5-115bb6ed610c.gif)

many thanks and best regards.
