### ISSUE TITLE
Column Edit (Paste) problem on long selection

### ISSUE THREAD

**Issue by HoarseHorace** [notepad-plus-plus/notepad-plus-plus#2253]
### Description of the Issue

Column edit (paste) over a section of text in a very long list doesn't paste correctly
### Steps to Reproduce the Issue

1. Start with ~75char wide, ~20k long list (Directory structure in my example); put replacement text portion in clipboard.
2. Go to EOF, or ~20k down a longer file
3. Place cursor at end of column edit section
4. go to top of file, Alt+Shift to start of column to select text to replace.
5. Paste from clipboard (Ctrl+V)
### Expected Behavior

Expected to paste clipboard contents in each line of text, replacing the selected column
### Actual Behavior

First ~50 lines are fine.
Strange line concatenations/characters
### Debug Information

Notepad++ v6.9.2
Build time : May 18 2016 - 00:34:05
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : ON
Local Conf mode : OFF
OS : Windows 7
Plugins : mimeTools.dll NppConverter.dll NppExport.dll PluginManager.dll 

Seed: (make ~20k line file of the following line)
4b960440ab31bae5bf04112cb4d199c7 *000000 Pack and go Comparison[vg-project] 000000 T-40-42-1 Compare\000000 T-40-4.2-1-496E9A4C0275.gz

column highlight "*000000 Pack and go Comparison"

paste with "#111111 Comparison Go and Pack"

(with line numbers)
48 4b960440ab31bae5bf04112cb4d199c7 #111111 Comparison Go and Pack[vg-project] 000000 T-40-42-1 Compare\000000 T-40-4.2-1-496E9A4C0275.gz
49 4b960440ab31bae5bf04112cb4d199c7 #111111 Comparison Go and Pack Compare\000000 T-40-4.2-1-496E9A4C0275.gz
![notepad issue](https://cloud.githubusercontent.com/assets/22056610/18319225/774e6c0e-74ea-11e6-8552-cf00f6aa5b35.JPG)

4b960440ab31bae5bf04112cb4d19
50 c7 #111111 Comparison Go and Pack Compare\000000 T-40-4.2-1-496E9A4C0275.gz
4b960440ab31bae5bf04112cb4d199c7 #111111 Comparison Go and

**Comment by dail8859** [comment]
Try turning off session snapshot. Quite possibly the same bug as #2226

**Comment by HoarseHorace** [comment]
Turning off session snapshot has resolved the issue. Thank you.

**Comment by MetaChuh** [comment]
please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins if you update from version 7.5.9 or below.
if your issue still persists, and it is still of relevance to you, please feel free to file a new issue as easy to understand and reproducible as possible.

thank you for your help and best regards.

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
(no extra account is needed, just use your github account to sign in)
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)
