### ISSUE TITLE
Windows Explorer Does not Refresh with Shell Extension Enabled

### ISSUE THREAD

**Issue by droz36** [notepad-plus-plus/notepad-plus-plus#2255]
### Description of the Issue

The ShellExtension for NP++ seems to keep Windows Explorer from refreshing on my windows 10 annic
### Steps to Reproduce the Issue
1. Install NP++ with Shell Extension enabled
2. create new folder in Explorer
   
   No folder appears until I hit F5 to refresh the screen.
### Expected Behavior

Windows Explorer should show the new folder or file
### Actual Behavior

Nothing. Well, the mouse turned to the circle for a bit, but that is about it
### Debug Information

Would be willing to work with folks on figuring out why this occurs.

**Comment by SinghRajenM** [comment]
This seems to be Win10 issue, rather than Npp. I've seen this issue in Win10 sometime back (note - Npp was not installed). This issue is no longer seen in latest Win10 build 1511 (I think build 10586) or check in redstone.

**Comment by TheLonerD** [comment]
It's not np++ issue. It's happens occasionally even on win7 and on new builds of win 10. I think it's a problem with "windows search" (when it's indexing folders) because it's very dependent from speed of hdd.

**Comment by MetaChuh** [comment]
not reproducible on notepad++ 7.6.6.

please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins.
if your issue still persists, and it is still of relevance to you, please feel free to file a new issue as detailed and reproducible as possible.

thank you for your help and best regards.

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
(no extra account is needed, just use your github account to sign in)
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)
