### ISSUE TITLE
Line Operations > Remove Empty Lines - corrupts large files (in editor) and crashes

### ISSUE THREAD

**Issue by tk627** [notepad-plus-plus/notepad-plus-plus#2256]
When editing a large XML file (77,000+ lines, length over 15,000,000 bytes) on a Windows 7 Lenovo ThinkPad laptop (Intel i7-4810MQ with 64bit OS and 32Gb RAM), it was too difficult to read with extra carriage returns throughout the file, so I found the Line Operations, and gave it a try... It corrupted the file, but I though I'd "save as", since it just looked like garbage at the end of the file... Notepad++ crashed (and lost all my temp scratch files in the process).
### Steps to Reproduce the Issue
1. Open a large XML file (greater than 1.5Mb) with many blank lines dispersed throughout
2. Select the "Edit" Menu, click on the "Line Operations", and select "Remove Empty Lines".
3. Wait for a short time as it works (and the GUI is completely unresponsive)
4. Jump to the end of the file, and see all the garbage lines
5. Select the "File" Menu, and click "Save As"... and lose all your work :(
### Expected Behavior

Expected operation to work without corruption. Sure didn't expect the crash when attempting to save.
### Actual Behavior

I've tried it since, and it won't crash if I just discard the corrupted file without saving... but it crashed when I did.
### Debug Information

Notepad++ v6.9.2
Build time : May 18 2016 - 00:34:05
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : ON
Local Conf mode : OFF
OS : Windows 7
Plugins : ComparePlugin.dll mimeTools.dll NppConverter.dll NppExport.dll NppFTP.dll nppplugin_solutionhub.dll nppplugin_solutionhub_ui.dll nppplugin_svn.dll PluginManager.dll SpellChecker.dll XMLTools.dll

**Comment by dail8859** [comment]
Try turning off session snapshot and see if that helps. If not try disabling your plugins. 

Possibly related to #2253 and #2226

**Comment by tk627** [comment]
Snapshots were set to every 7 seconds... Once disabled, it no longer corrupted the file in memory. Thank you!

**Comment by tk627** [comment]
If the snapshot could be held off for long processes/macros, this would be a great enhancement? Please consider this closed.

**Comment by dail8859** [comment]
There are mechanisms in the code to delay the backup but there are so many cases where it could potentially corrupt the file not all of them are handled. I'm going to keep this open because it is still a problem that needs addressed. 

The related issues have the same root cause. Either a single solution needs found or all these individual cases need handled.

**Comment by MetaChuh** [comment]
please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins if you update from version 7.5.9 or below.
if your issue still persists, and it is still of relevance, please feel free to file a new issue as easy to understand and reproducible as possible.

thank you for your help and best regards.
