### ISSUE TITLE
Web site typo

### ISSUE THREAD

**Issue by dilettante60** [notepad-plus-plus/notepad-plus-plus#2257]
### Description of the Issue

Web site typo
### Steps to Reproduce the Issue

https://notepad-plus-plus.org/download/v6.9.2.html
Does the monitoring function only work in the morning? :-)

### Debug Information

Text:
Notepad++ v6.9.2 new features and bug-fixes:
1. Add most wanted feature: Log Mornitoring (tail -f).

**Comment by donho** [comment]
The monitoring function not only work in the morning anymore ;)
