### ISSUE TITLE
Default location to save file is not consistent

### ISSUE THREAD

**Issue by msmigiel** [notepad-plus-plus/notepad-plus-plus#226]
When you first open Notepad++ and try to save the blank file, the default location is the "AppData/Local/Temp/nppLocalization" folder. If you hit cancel and try again, it goes to the Notepad++ installation folder. It should at a minimum save to the user's Documents folder but even better, save to the last used location as some other text editors do.

**Comment by MetaChuh** [comment]
closed due to:
* can be set at `settings > preferences > default directory > remember last used directory`
