### ISSUE TITLE
&& not showing in javascript file for white (default) theme

### ISSUE THREAD

**Issue by borisplotkin** [notepad-plus-plus/notepad-plus-plus#2260]
### Description of the Issue

&& signs not showing up in white theme (default)

### Steps to Reproduce the Issue

1.  Open notepad++
2. Type && 
3. Nothing shows up even when it's there.

### Expected Behavior

Should be visible && but not

### Actual Behavior

Nothing shows

### Debug Information

Notepad++ v6.9.2
Build time : May 18 2016 - 00:34:05
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10
Plugins : mimeTools.dll NppConverter.dll NppExport.dll NppFTP.dll PluginManager.dll 

http://i.imgur.com/g9Jc8Vo.png

**Comment by dail8859** [comment]
It is a [known issue](https://github.com/notepad-plus-plus/notepad-plus-plus/issues?q=is%3Aissue+ampersand+is%3Aclosed) with the source code pro font.
