### ISSUE TITLE
Unicode Existential Quantifier displayed incorrectly

### ISSUE THREAD

**Issue by BerserkCore** [notepad-plus-plus/notepad-plus-plus#2268]
### Description of the Issue

In some cases Unicode characters are displayed incorrectly. The example provided included uses of the existential quantifier in particular displayed incorrectly on some lines and correctly when certain other characters precede it
### Steps to Reproduce the Issue

Create a line with just the existential qualifier (backwards e, &#8707; or &exist ) to display it incorrectly.
Create a line with the universal quantifier (upside down A, \u2200) followed by the existential qualifier to display the existential qualifier correctly.
### Debug Information

[unicode_error.txt](https://github.com/notepad-plus-plus/notepad-plus-plus/files/465923/unicode_error.txt)

**Comment by benkean** [comment]
service mark (℠) has a similar problem, but it also has to do with what comes after the service mark instead of what proceeds it.

℠∀ and ∀℠ work but ℠ with does not display without being next to the ∀ character.

**Comment by MetaChuh** [comment]
please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins if you update from version 7.5.9 or below.
if your issue still persists, and it is still of relevance, please feel free to file a new issue as easy to understand and reproducible as possible.

thank you for your help and best regards.
