### ISSUE TITLE
Hangs (program not responding) when an open document on the network becomes unavailable

### ISSUE THREAD

**Issue by acshef** [notepad-plus-plus/notepad-plus-plus#227]
If I have a file like `\\PC_ON_LOCAL_NETWORK\c\dir\file.txt` open, and I shut down "PC_ON_LOCAL_NETWORK," Notepad++ will hang after about 60 seconds (application fades to white, Windows reports the program is not responding).

**Comment by CookiePLMonster** [comment]
After all these years, confirmed still happening with 7.5.4. Looks like a nasty issue, for me it hung after minimizing and maximizing again.

Shouldn't Notepad++ just notify that file is not available anymore, as if it was deleted?

**Comment by donho** [comment]
Update your Notepad++ to v7.6.6.
If this bug persists in the new release, please open a new issue with the debug information.
