### ISSUE TITLE
[Feature request] Colored tabs

### ISSUE THREAD

**Issue by sas33** [notepad-plus-plus/notepad-plus-plus#2271]
### Description of the Issue

i got lost sometimes when i work with large numbers of php pages or html. if i could group by colors
the tabs it will be more easier to reach what i want without searching for the filename in the tabs.
### Steps to Reproduce the Issue

1. 
2. 
3. 
### Expected Behavior

colored tabs by the choice of the user (red,blue, green, etc)
### Actual Behavior

they are all grey and indistinguishable

**Comment by Pyre909** [comment]
Why not set the color according to file type? Just food for thought.....

**Comment by sas33** [comment]
@Pyre909 ok but when i have like 15 php file types and i want to group them by colors this will come in handy

**Comment by spaxio** [comment]
It's old ticket, but I really needed this so I forked the repo and made it possible.
https://github.com/spaxio/notepad-plus-plus-colored-tabs/commit/db92d1fce38d110248cd6437e81ef8ba8c0ab422

https://i.imgur.com/Rlgt94T.png
We can select between 5 different colours. It works in dark/light mode.

I could open a pull request if @donho is interested, I'm pretty open to adjusting it more. 
But if not that's cool too. As I said I really needed this in my npp workflow :D

**Comment by donho** [comment]
@spaxio 
Please do a PR - I will try it out.
It looks very promising - from the aspect of GUI and simplicity of modification.

**Comment by alankilborn** [comment]
Would this color be saved in session?
Does this open the door to tab color by file type?

**Comment by spaxio** [comment]
https://github.com/notepad-plus-plus/notepad-plus-plus/pull/12098

>Would this color be saved in session?
Yes it's saved in session.xml file 
>Does this open the door to tab color by file type?
We have access to the file type so it's possible but we would need to add some simple algorithm calculating colour for given file extension (or parent folder)

**Comment by sas33** [comment]
Thank you!

**Comment by JergenRoss** [comment]
> We can select between 5 different colours. It works in dark/light mode.

um does User can use custom color will work? also more select 5 to up?

**Comment by JergenRoss** [comment]
> Why not set the color according to file type? Just food for thought.....

I think my suggest is name file type colored `.txt` `.bat` with tag instead tab

example:
tab yellow: `new document [.txt]` 

`[]` is colored by according to file type
`tab yellow` colored is user want to group them by colors.

User can prefer change color different file types 

Im not sure if who want color by file types or not.
