### ISSUE TITLE
[Feature request] Replace in the selected area

### ISSUE THREAD

**Issue by sas33** [notepad-plus-plus/notepad-plus-plus#2272]
### Description of the Issue

sometimes i need to replace words, letters in a certain area not an entire document

### Steps to Reproduce the Issue

1. 
2. 
3. 

### Expected Behavior

when i right click the selected area a new context menu called replace in selected text

**Comment by TheLonerD** [comment]
This?
![Replace dialog](http://i.imgur.com/6J2gpsl.png)

**Comment by sas33** [comment]
thx a lot!

**Comment by sas33** [comment]
@TheLonerD this just made my work easyer :+1:

**Comment by TheLonerD** [comment]
@sas33 could you please close this issue?
