### ISSUE TITLE
Calltips is not considering startFunc and endFunc for function start and end tags

### ISSUE THREAD

**Issue by joshmclean** [notepad-plus-plus/notepad-plus-plus#2274]
### Description of the Issue
I created a new XML API (AutoComplete / CallTips) and used '[' and ']' for startFunc and stopFunc respectively for the <Environment> node.

The tool tip appears as expected after typing in the '[' character. However, the tool tip shows '(' and ')' for function start and end tags which makes it confusing. The tags should be using startFunc and stopFunc characters. 

Example below

![image](https://cloud.githubusercontent.com/assets/22169356/18469410/6a472d12-79a8-11e6-8ea2-b5ce54bedd09.png)

**Comment by dail8859** [comment]
Could you provide your XML file, or even just a small subset of it. One function should be enough to reproduce this.

**Comment by dail8859** [comment]
I just modified an existing API file so need to provide it anymore.

**Comment by joshmclean** [comment]
Cool - thanks for fixing this so fast!
