### ISSUE TITLE
Strange behaviour of built-in environment variable $(CURRENT_DIRECTORY)

### ISSUE THREAD

**Issue by byzod** [notepad-plus-plus/notepad-plus-plus#2275]
### Description of the Issue

I just updated Npp 6.9.2 from 6.8.8, one of my frequently used shortcuts is broken.
This shortcut I added in shortcuts.xml works in 6.8.8

Command 1 "Tell me where we are" should display the content of $(CURRENT_DIRECTORY), for debugging.
Command 2 (broken) "Open containing folder" should open the current folder in explorer.
![](http://i.imgur.com/GLVLJUm.png)
### Steps to Reproduce the Issue

1. Create an empty file 1.txt in Q:\Down\ (in my situation, this folder is also the user folder Downloads), create an empty file 2.txt in Q:\RandomFolder\
2. Run command 1 and 2 separately for file 1.txt and 2.txt
### Expected Behavior

1. For both of them, command 1 should display their current directory path.
2. For both of them, command 2 should open the folder they're put in.
### Actual Behavior

1. For both of them, command 1 do display their current directory path.
2. For 2.txt which is in a normal folder, command 2 opens Q:\RandomFolder\
3. But when command 2 applied to 1.txt, Explorer opens a folder I didn't recognized.
   ![](http://i.imgur.com/xJVwfcl.gif)
### Debug Information

Notepad++ v6.9.2
Build time : May 18 2016 - 00:34:05
Path : K:\App\Something\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : ON
OS : Windows 10
Plugins : ComparePlugin.dll EmmetNPP.dll HexEditor.dll JSMinNPP.dll mimeTools.dll nppRegEx.dll NppTextFX.dll PluginManager.dll PythonScript.dll

**Comment by MetaChuh** [comment]
please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins if you update from version 7.5.9 or below.
if your issue still persists, and it is still of relevance, please feel free to file a new issue as easy to understand and reproducible as possible.

thank you for your help and best regards.

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
(no extra account is needed, just use your github account to sign in)
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)
