### ISSUE TITLE
Alt+O does not trigger "Replace All in All Opened Documents"

### ISSUE THREAD

**Issue by MartinNFuller** [notepad-plus-plus/notepad-plus-plus#2276]
### Description of the Issue

In the Replace dialog (Ctrl+H), the keyboard shortcut Alt+O does not trigger "Replace All in All Opened Documents".
### Steps to Reproduce the Issue
1. Open 1+ documents
2. Ctrl+H
3. Enter some search text that appears in the documents
4. Alt+O
### Expected Behavior

Alt+O should have the same effect as clicking the button "Replace All in All Opened Documents"
### Actual Behavior

Alt+O has no effect.
### Debug Information

Notepad++ v6.9.2
Build time : May 18 2016 - 00:34:05
Path : D:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10
Plugins : mimeTools.dll NppConverter.dll NppExport.dll NppFTP.dll PluginManager.dll

**Comment by krilbe** [comment]
Please note that #3699 would probably solve this issue. Clashes between Alt shortcut letters from invisible tabs should not be an issue, i.e. Notepad++ should never, in any dialog with multiple tabs, have shortcuts on invisible tabs swallow Alt letter shortcuts that appear on the active tab. It's not realistic to require that all Alt shortcuts be unique across all tabs. Being unique on the active tab should suffice and work as expected.
