### ISSUE TITLE
Opening Zero Byte Text Files doesn't obey the "New Document" Settings

### ISSUE THREAD

**Issue by c33s** [notepad-plus-plus/notepad-plus-plus#228]
opening a zero byte sized text file with notepad++ leads to an ansi file with windows file endings even if utf-8 without bom + linux file endings is set in the "new document" settings.

```
touch foo.txt
"C:\Program Files (x86)\Notepad++\notepad++.exe" foo.txt
```

see also http://ghisler.ch/board/viewtopic.php?p=297001

edit: 
a good thing would be to have command line switches to force encodings and line endings.

**Comment by Rikk** [comment]
> opening a zero byte sized text file with notepad++ leads to an ansi file with windows file endings even if utf-8 without bom + linux file endings is set in the "new document" settings.

+1

**Comment by c33s** [comment]
related #349

**Comment by CookiePLMonster** [comment]
Seems to be solved by now...

**Comment by c33s** [comment]
yes it is fixed.
