### ISSUE TITLE
Unable to Open File With nfo extension

### ISSUE THREAD

**Issue by jerrydfox** [notepad-plus-plus/notepad-plus-plus#2283]
I Right clicked on the context menu to open a file in  Notepad++. The program opens but I get an error message saying
Notepad ++ a free (GNU) source editor has stopped working. (I'm sure it is a windows message as it says Windows will close the program and gives me the option to debug by opening Visual Studio)
Notepad++ opens a new empty tab with the name of the file I was trying to open.
I am running Windows 10 and Notepad++ v6.6.9
I can right click the file and Sent It To Windows Notepad and it opens.
The file is a .nfo file associated with a movie download.
I will attach the file with the extension changed to txt so I can attach it.
Notepad++ opens the file OK when I change the extension to txt.
To re create the error you will need to change the file extension back to nfo
[_Overbooked.2012.WEBRip.x264-dEViANCe_newzNZB.txt](https://github.com/notepad-plus-plus/notepad-plus-plus/files/474610/_Overbooked.2012.WEBRip.x264-dEViANCe_newzNZB.txt)

**Comment by dail8859** [comment]
Please try the latest version of Notepad++ since you are still on a very outdated version.

**Comment by hxxr** [comment]
#1594
