### ISSUE TITLE
Just want to know why two installers for NPP

### ISSUE THREAD

**Issue by SinghRajenM** [notepad-plus-plus/notepad-plus-plus#2286]
### Question
Why there are two separate installers planned (x86 and x64) while it can be managed with single installer?
As far I  can think that user might be given flexibility to choose x86 installer for x64 bit machine, but again it can be handed within script as well.
So why two installers, any reason?

!ifdef ARCH64
OutFile ".\build\npp.${APPVERSION}.Installer.x64.exe"
!else
OutFile ".\build\npp.${APPVERSION}.Installer.x32.exe"
!endif

Also if both are required then x32 should be changed to x86, shouldn't it?

**Comment by MAPJe71** [comment]
> Also if both are required then x32 should be changed to x86

IMO `x32` and `x64` make more sense than `x86` and `x64`.
Otherwise it would be more correct to write `x86-32` and `x86-64`.
I'd use `32bit` and `64bit` or just `32` and `64`.

**Comment by leewz** [comment]
`x32` is not proper or popular. `x86` comes from the suffix "86" of a line of processors, and is the name of the instruction set. `x64` is short for x86-64, a 64-bit instruction set based on x86 (or a version of x86?). While `x64` is not proper, it is popular and in many official names. Also, [Linux uses x32 to refer to a way for x86-64 programs to use 32-bit pointers.](https://en.wikipedia.org/wiki/X32_ABI)

I agree with using `x86-32` or `32-bit`. People shouldn't need to know computer history to know what to download.

**Comment by ljporljp** [comment]
I think x86-32 and x86-64 is more properly correct

**Comment by SinghRajenM** [comment]
I agree with @leewz . x32 is not proper or popular. IMO, to avoid confusion or make it simpler win32 or win64 would be better choice e.g. npp-{version}-win32.exe. FYI - vlc installers use this concept.

Moreover, I'm still waiting for answer to my first question that why two separate installers are required?

**Comment by SinghRajenM** [comment]
Closing issue. 🔍
