### ISSUE TITLE
doc switcher auto update

### ISSUE THREAD

**Issue by frmadiot** [notepad-plus-plus/notepad-plus-plus#2290]
hi there.
on notepad++ doc switcher :
I have sorted my doc switcher list by double click on name column
 when i open new doc after sorting, the new doc appear at the end of the list so my list of open doc is not sorted.

I expect to have my list of open document always sorted.

Bonjour,
j'ai trié ma liste de documents ouvert dans le commutateur de document
quand j'ouvre un fichier après avoir trié ma liste, le fichier se place à la fin de la liste.
du coup, ma liste n'est plus triée alors que le petit triangle du dock commutateur de document me dit que ma liste est triée.

C'est possible d'avoir la liste triée en permanence ?

thanks & regards.
merci pour votre aide.
![sans titre](https://cloud.githubusercontent.com/assets/2905525/18593244/cd7c2150-7c3a-11e6-94a8-eb1f6a4cc653.png)

**Comment by MetaChuh** [comment]
please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins if you update from version 7.5.9 or below.
if your issue still persists, and it is still of relevance, please feel free to file a new issue as easy to understand and reproducible as possible.

thank you for your help and best regards.

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
(no extra account is needed, just use your github account to sign in)
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)
