### ISSUE TITLE
user defined language: code block trigger string doesnt work if starts with ";"

### ISSUE THREAD

**Issue by waskomo** [notepad-plus-plus/notepad-plus-plus#2291]
automatic code block folding needs two string signalling the start and end of each code block. if in a user defined language these strings start with a ";" the plus/minus signs on the left side dont appear. Notepad plus plus doesnt recognize these strings.
### Steps to Reproduce the Issue
1.  define a user defined language
2.  define codeblock start and end tags so that they start with ;
3.  now type in codelbock start/end strings in editor, notepad++ will not recognize them
### Expected Behavior

user defined codeblock strings should be recognized as codeblock strings even when they start with ";" in earlier versions this worked.
### Actual Behavior

notepad++ doesnt recognise user defined codeblock tags if they start with ";"

![np](https://cloud.githubusercontent.com/assets/9912035/18597761/b46b3272-7c4f-11e6-8f4c-e3e902df3274.png)

**Comment by MetaChuh** [comment]
please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins if you update from version 7.5.9 or below.
if your issue still persists, and it is still of relevance, please feel free to file a new issue as easy to understand and reproducible as possible.

thank you for your help and best regards.
