### ISSUE TITLE
Update english and french translation

### ISSUE THREAD

**Issue by cmeriaux** [notepad-plus-plus/notepad-plus-plus#2293]
### Description of the Issue

translation of ID 43033 -> 43037 and 43039 -> 43043 are wrong
The shortcut mapper is very confusing
![bugtranslation](https://cloud.githubusercontent.com/assets/12024941/18615787/f584ac00-7daf-11e6-868d-c6d7944b4db9.png)
### Steps to Reproduce the Issue

1. check the name in the shortcut mapper : main menu line 124 to 140
### Expected Behavior

```
<Item id="43033" name="Go to next 1st style"/>
<Item id="43034" name="Go to next 2nd style"/>
<Item id="43035" name="Go to next 3rd style"/>
<Item id="43036" name="Go to next 4th style"/>
<Item id="43037" name="Go to next 5th style"/>

<Item id="43039" name="Go to previous 1st style"/>
<Item id="43040" name="Go to previous 2nd style"/>
<Item id="43041" name="Go to previous 3rd style"/>
<Item id="43042" name="Go to previous 4th style"/>
<Item id="43043" name="Go to previous 5th style"/>
```
### Actual Behavior

```
<Item id="43033" name="1st style"/>
<Item id="43034" name="2nd style"/>
<Item id="43035" name="3rd style"/>
<Item id="43036" name="4th style"/>
<Item id="43037" name="5th style"/>

<Item id="43039" name="1st style"/>
<Item id="43040" name="2nd style"/>
<Item id="43041" name="3rd style"/>
<Item id="43042" name="4th style"/>
<Item id="43043" name="5th style"/>
<Item id="43044" name="Find style"/>
```
### Debug Information

Notepad++ v6.9.2   (32-bit)
Build time : Aug 24 2016 - 05:43:21
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10
Plugins : LightExplorer.dll linefilter2.dll mimeTools.dll NppConverter.dll NppExec.dll NppExport.dll NppFTP.dll NppMenuSearch.dll PluginManager.dll PythonScript.dll

**Comment by donho** [comment]
Outdated
