### ISSUE TITLE
Explorer integration for existing "Find in files..." feature

### ISSUE THREAD

**Issue by TLN2** [notepad-plus-plus/notepad-plus-plus#2296]
### Description of the Issue

When
right-clicking
OR
Shift + right-clicking
a folder in Windows Explorer there should be a context menu item named "Find in files with Notepad++...".
If you click that item, Notepad++ should pop up with its "Find in files" dialog open with the selected folder already entered.

In my personal opinion Shift + right-click would be the better choice (than just right-click) to avoid congestion of the context menu.
It might also be a good idea to make this feature optional so that users who don't want the menu item in their context menu at any time can untick a checkbox in Notepad++ options to achieve that goal.
### Debug Information

Notepad++ v6.9.2
Build time : May 18 2016 - 00:34:05
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 7
Plugins : mimeTools.dll NppConverter.dll NppExport.dll NppFTP.dll PluginManager.dll

**Comment by MetaChuh** [comment]
this feature will currently not be implemented at the notepad++ core and the installer.

thank you for your help and best regards.
