### ISSUE TITLE
Auto-Completion From 1 th character unchangable

### ISSUE THREAD

**Issue by treflip** [notepad-plus-plus/notepad-plus-plus#2297]
### Description of the Issue

Can't change the value from 1th character to say 4th character. Windows is making the beeping noise when trying to delete the '1' and input a new number.
### Steps to Reproduce the Issue
1.  Open Settings -> Preferences
2.  Select Auto-Completion option
3.  Enable auto-completion on each input check box
4.  Select the 1 in the '1th character' option
5. Try to change the value
### Expected Behavior

The value will change from 1-9.
### Actual Behavior

Windows Beep when trying to input any other value.
### Debug Information

Notepad++ v6.9.2
Build time : May 18 2016 - 00:34:05
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 8.1
Plugins : AnalysePlugin.dll ComparePlugin.dll mimeTools.dll NppCalc.dll NppColumnSort.dll NppConverter.dll NppExec.dll NppExport.dll NppFTP.dll NppTextFX.dll NppVHDL.dll PluginManager.dll XMLTools.dll 

![image](https://cloud.githubusercontent.com/assets/6201948/18609362/6ba0f76e-7cce-11e6-8685-71a3b129c6b3.png)

**Comment by ljporljp** [comment]
i think it is the windows's bug,

**Comment by anil-shrestha** [comment]
You just have to type value from 1-9 and press enter.

**Comment by anil-shrestha** [comment]
You just have to type value from 1-9 and press enter.

**Comment by treflip** [comment]
Still an issue. But found out more information. 

I am using a windows laptop with no number pad. When trying to input the 1-9 from the number keys (2nd to top row) the input is failing and making the windows beeping noise.

I tried copy and pasting the number in and still no results. There currently is no workaround for this (2018).

**Comment by chcg** [comment]
Can't reproduce the issue with N++ 7.6 on Win10. No difference between number block or numbers keys.
The beep sound is just hearable, if a invalid the user tries to input some invalid number like e.g. a double digit like 34. Additionally a popup appears if you try to input no digit.

**Comment by donho** [comment]
I believe this issue has been fixed since long time ago.
Update your Notepad++ to the latest version (v7.6.6).
If the issue persists, please create a new issue for it.
Thank you.
