### ISSUE TITLE
Move to VS2015

### ISSUE THREAD

**Issue by NN---** [notepad-plus-plus/notepad-plus-plus#230]
What about moving the project to VS2015 compiler ?
It is already RC and its license allows to use it even in Community edition.
It has XP compilation support as well as VS2013.
The compiler has better analysis and better optimizations, not to mention less bugs with Standard Library :)

**Comment by donho** [comment]
We will, but not so soon.
I think it'll be safe when VS2015 is in release. 
In the meantime, we use VS2013 :)

**Comment by NN---** [comment]
I use it at work and it works great.
I didn't see any problems with it yet.
It did fix some annoying compiler bugs:)

Then we'll wait for release.

**Comment by ichenq** [comment]
Perhaps better to add a make script(CMake or Premake) support, so people can generate their favoriate version of VS.

**Comment by NN---** [comment]
@ichenq 
I don't really think it is needed.
VS doesn't know to work with cmake , it means you must manually change the file..

Since the only change is platform toolset (vs100_xp, vs110_xp , vs120_xp , vs140_xp ) , it is easier to have simple script that changes the toolset and generates vcxproj for all versions :)

**Comment by NN---** [comment]
We have VS2015 release. What about moving now ?
Thanks.

**Comment by milipili** [comment]
No it is too early. VS has history about regressions (especially when you know the latest fixes for vs2015....) and anyway you can't take a product like for its first release.
But nothing should stop you for using it.

**Comment by NN---** [comment]
@milipili Do you know anything about regressions in VS2015 ?
I know about some known issues still,  but  they are not regressions.

**Comment by milipili** [comment]
In the very first preview version. And honestly I am tired of hunting down bugs from this compiler. So waiting a little will be good.
But do not worry i want 'constexpr' and vs2015 is required for that.

**Comment by donho** [comment]
I agree with @milipili - we might integrate VS2015, but it's too early to do it.

**Comment by NN---** [comment]
I think by 7.0 it will be stable enough :)

**Comment by milipili** [comment]
Lol

**Comment by ariccio** [comment]
Side note: Has everybody installed VS2013 Update 5?

**Comment by NN---** [comment]
@donho VS2015 Update 1 RTM is out.
What do you think about switching completely to VS2015 ?

Thanks
