### ISSUE TITLE
Closing "Folder as workspace" closes "Doc switcher" panel as well

### ISSUE THREAD

**Issue by SinghRajenM** [notepad-plus-plus/notepad-plus-plus#2301]
### Description of the Issue

Closing "Folder as workspace" closes "Doc switcher" panel as well. It is applicable vice versa also.
### Steps to Reproduce the Issue

1. Open Notepad++
2. Activate "Doc Switcher" from preference ->General->Document List Panel -> Check Show"
3. Activate "Folder as workspace" using toolbar
4. Now close "Folder as workspace" by clicking on x button (**_Not from tool bar_**). 
### Expected Behavior

Only "Folder as workspace" should be closed. "Doc Switcher" should remain in dock panel.
### Actual Behavior

Closing "Folder as workspace" closes both "Folder as workspace" and "Doc switcher".
### Debug Information

Notepad++ v6.9.2
Build time : May 18 2016 - 00:34:05
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : ON
Local Conf mode : OFF
OS : Windows 7
Plugins : DSpellCheck2.dll mimeTools.dll NppConverter.dll NppExport.dll PluginManager.dll 

This issue occurs vice versa. But, 
_1. Closing  "Folder as workspace" either from toolbar  or menu bar (menu->view->Folder as workspace) does not closes doc switcher. Also closing (in other words disabling) doc switcher from preference ->General->Document List Panel -> Check Show" does not closes "Folder as workspace".
2. If both "Doc switcher" and "Folder as workspace" are in difference dock panels, then this issue does not occur._

**Comment by dhowland** [comment]
This is a general problem with all of the dockable panels in Notepad++.  Closing one of them closes all of them.  It's a very strange break with common UI conventions.

**Comment by donho** [comment]
This is limit of dockable panels in Notepad++.
