### ISSUE TITLE
Closing "Doc Switcher" does not reflect on prefence UI

### ISSUE THREAD

**Issue by SinghRajenM** [notepad-plus-plus/notepad-plus-plus#2302]
### Description of the Issue

On closing "Doc switcher" by clicking on x button, respective setting on preference UI does get reset. 
### Steps to Reproduce the Issue

1. Open Notepad++
2. Activate "Doc Switcher" from preference ->General->Document List Panel -> Check Show"
3. Now close "Doc Switcher" by clicking on x button.
4. Try to follow step 2 again
### Expected Behavior

At step 4, Checkbox (Show) should be unchecked.
### Actual Behavior

At step 4, Checkbox (Show) is already checked. To enable "Doc Switcher", it has to be clicked twice.
### Debug Information

Notepad++ v6.9.2
Build time : May 18 2016 - 00:34:05
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : ON
Local Conf mode : OFF
OS : Windows 7
Plugins : DSpellCheck2.dll mimeTools.dll NppConverter.dll NppExport.dll PluginManager.dll

![docswitcher](https://cloud.githubusercontent.com/assets/14791461/18614943/fda6b17e-7db6-11e6-9d1c-4a848527ba81.png)

**Comment by donho** [comment]
I believe this issue has been fixed since long time ago.
Update your Notepad++ to the latest version (v7.6.6).
If the issue persists, please create a new issue for it.
Thank you.
