### ISSUE TITLE
Powershell Lexer causes NPP to not open after installation

### ISSUE THREAD

**Issue by asnyder91** [notepad-plus-plus/notepad-plus-plus#2307]
### Description of the Issue
After installing Powershell Lexer add in, NPP doesn't open

### Steps to Reproduce the Issue

1. Install Powershell Lexer add in
2. Don't open NPP because you can't
3. File bug report

**Comment by dail8859** [comment]
This is a problem with a 3rd party plugin. You'll have to report it to the developer of the power shell lexer.

**Comment by dail8859** [comment]
This is a problem with a 3rd party plugin. You'll have to report it to the developer of the power shell lexer.
