### ISSUE TITLE
Crash while recording a Macro in Notepad++ v7 (x64)

### ISSUE THREAD

**Issue by mareek** [notepad-plus-plus/notepad-plus-plus#2310]
### Description of the Issue
pressing enter key while recording a macro causes Notepad++ to crash

### Steps to Reproduce the Issue
1. Start recording a macro
2. Press enter

### Expected Behavior
Don't crash

### Actual Behavior
Crash

### Debug Information

Notepad++ v7   (64-bit)
Build time : Sep  7 2016 - 02:15:41
Path : C:\Users\MyLastName\Downloads\npp.7.bin64\notepad++.exe
Admin mode : OFF
Local Conf mode : ON
OS : Windows 10
Plugins : mimeTools.dll NppConverter.dll

**Comment by cmeriaux** [comment]
I can't reporduce it with my config

```
Notepad++ v6.9.2   (32-bit)
Build time : Sep 16 2016 - 10:11:20
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 7
Plugins : CodeAlignmentNpp.dll ComparePlugin.dll CustomizeToolbar.dll HexEditor.dll LightExplorer.dll MenuIcons.dll mimeTools.dll NppConverter.dll NppExec.dll NppExport.dll NppMenuSearch.dll NppVHDL.dll PluginManager.dll PythonScript.dll 
 
```
It may be specific to 64 bits version

**Comment by dail8859** [comment]
Can't reproduce it either:

```
Notepad++ v7   (64-bit)
Build time : Sep  7 2016 - 02:15:41
Path : C:\Users\xxxx\Desktop\npp.7.bin64\notepad++.exe
Admin mode : ON
Local Conf mode : ON
OS : Windows 7
Plugins : mimeTools.dll NppConverter.dll 

```

**Comment by mareek** [comment]
I've tried to reproduce the problem on a few computers and it seems to occur only with the 64 bits version on Windows 8.1 and 10 but not on Windows 7

**Comment by dail8859** [comment]
@mareek Thanks for the info. Personally I don't have access to those OSs so hopefully someone else can try this out. My only other suggestion is try out the official v7 release instead of the RC.

**Comment by mareek** [comment]
The official release doesn't fix the problem

**Comment by Ghasan** [comment]
I confirm it crashes. Here are my details.

Notepad++ v7   (64-bit)
Build time : Sep 21 2016 - 22:07:28
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10
Plugins : mimeTools.dll NppConverter.dll

**Comment by donho** [comment]
https://github.com/notepad-plus-plus/notepad-plus-plus/commit/8e9e8c04cd3a4fbc3556119cebfa9d4671eaf9b0

**Comment by cmeriaux** [comment]
@mareek there is a nightly build available here 
https://ci.appveyor.com/project/donho/notepad-plus-plus/build/1.0.402/job/0rrtf2da6yxl7389/artifacts

**Comment by mareek** [comment]
The nightly build fix the crash.
Thanks
