### ISSUE TITLE
urgent::: in replace window: why don't we have a textarea instead of this very uncomfort field, please do like others, it's very more easy to work with, 

### ISSUE THREAD

**Issue by engineerbaraazakariya** [notepad-plus-plus/notepad-plus-plus#2313]
urgent::: in replace window: why don't we have a textarea instead of this very uncomfort field, please do like others, it's very more easy to work with,

**Comment by Marcono1234** [comment]
Probably duplicates #563

**Comment by MetaChuh** [comment]
please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins if you update from version 7.5.9 or below.
if your issue still persists, and it is still of relevance, please feel free to file a new issue as easy to understand and reproducible as possible.

thank you for your help and best regards.
