### ISSUE TITLE
when multiselect lines , then pressing end button on keyboard, copy paste won't work for each line seperated, if you wish to understand it more, just try ST3 multi line selection and End write copy paste methods

### ISSUE THREAD

**Issue by engineerbaraazakariya** [notepad-plus-plus/notepad-plus-plus#2314]
when multiselect lines , then pressing end button on keyboard, copy paste won't work for each line seperated, if you wish to understand it more, just try ST3 multi line selection and End write copy paste methods

**Comment by MetaChuh** [comment]
please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins if you update from version 7.5.9 or below.
if your issue still persists, and it is still of relevance, please feel free to file a new issue as easy to understand and reproducible as possible.

thank you for your help and best regards.

**Comment by sasumner** [comment]
@engineerbaraazakariya WTF is ST3 ?

**Comment by engineerbaraazakariya** [comment]
> @engineerbaraazakariya WTF is ST3 ?

ST3  (known this way) = Sublime Text 3

**Comment by sasumner** [comment]
@engineerbaraazakariya OK...but people here and developers pretty much use, well, Notepad++.  And no one is going to install Sublime (if they don't have it already) in pursuit of your issue.  So I'd say you should just elaborate here on what you expect.  Then again, you created this issue coming up on 3 years ago, and it has received no action (except closure! doh!), so such elaboration might be like pushing a rope. ;)

**Comment by engineerbaraazakariya** [comment]
It was just an issue for me converting from other editors to np++ as developer, I don't think I am alone in this, but it's not a fatal error, and I did not say so, so maybe others just taking what they like more from other editors without even letting np++ knows it, for me I liked np++ so I informed about it....

**Comment by sasumner** [comment]
@engineerbaraazakariya Understood, and that's fine, except if you say "just see how some other product does it", it may not be that helpful.  Plus it makes you appear lazy (don't know if this is the case!).  A new Scintilla component will be integrated into Notepad++ soon, perhaps it will add the functionality you asked about!  Cheers.

**Comment by engineerbaraazakariya** [comment]
At that time I was impressed (still) by the multi-line selection which I was used to and it was helpful to me (maybe to some other developers too), but maybe I agree with you that I may be not needed to write that sentence, it was not needed as I think now, and I am still using np++ it's one of the best editors in my opinion. especially for macros (in my side). Cheers.
