### ISSUE TITLE
Add Powershell support to function List

### ISSUE THREAD

**Issue by mat-m** [notepad-plus-plus/notepad-plus-plus#2317]
Hello

Powershell is very structured and there is only one way to declare a function. It should be quite easy to detect function in powershell scripts.
Handling arguments may be harder, but that may be a second step.

Thanks

**Comment by MAPJe71** [comment]
Could you try this parser and let me know how it works out?

```XML
	<association id="powershell_funcfilt" langID="53" />

	<parser
		displayName="PowerShell"
		id         ="powershell_funcfilt"
		commentExpr="(?'MLC'(?s-m)&lt;#(?:[^#]|#[^&gt;])*#&gt;)|(?'SLC'(?m-s)#.*$)"
		version    ="0.1.0.0"
	>
		<function
			mainExpr="\b(?:function|filter)\b\s+(?:[A-Za-z_]\w*:)?[A-Za-z_][\w\-]*\s*[({]"
		>
			<functionName>
				<nameExpr expr="[A-Za-z_][\w\-]*(?=\s*[({])" />
			</functionName>
			<className>
				<nameExpr expr="[A-Za-z_]\w*(?=:)" />
			</className>
		</function>
	</parser>
```

**Comment by MAPJe71** [comment]
@mat-m any feedback would be appreciated.

**Comment by mat-m** [comment]
Sorry it took a long time.

This had no effect to powershell function detection. The list is still empty.

Is there a cache to clear or a setting to update or something like that ?

**Comment by MAPJe71** [comment]
Maybe you edited the wrong `functionList.xml` file as there might be more than one on your system.
Check for ...
1. `%ProgramFiles%\Notepad++\functionList.xml`;
2. `%ProgramFiles(x86)%\Notepad++\functionList.xml`;
3. `%AppData%\Notepad++\functionList.xml`
Furthermore, make sure to restart Notepad++ after you edited and saved the XML-file.

**Comment by mat-m** [comment]
Works in v7 !

Thanks for this

**Comment by MAPJe71** [comment]
Does FunctionList show the functions as expected?
When so, would you be so kind to close the issue.
Thanks

**Comment by mat-m** [comment]
yes. Just hoping it could be merged to be the default :)

**Comment by MAPJe71** [comment]
I'm working on updates for FunctionList.
I wanted confirmation (other than myself) about the parser before including it in a PR.
:+1:

**Comment by JoeBonifazi** [comment]
THANK YOU!!
Even something this small saved me time of rolling my own!

Small tiny miniscule insignificant comment:
The association keys were reversed from my default functionList.xml file for Notepad++ version 7.3.2

...
			<association langID="28" id="nsis_syntax"/>
			<association langID="53" id="powershell_funcfilt" />
...

This does not impede functionality.   I put them in the order above for consistency.
After restarting Notepad++ all my functions appeared in the list!

**Comment by MAPJe71** [comment]
@JoeBonifazi 
You're welcome!
FYI - excerpt of "Function List Update 2" change log:
```
* functionList.xml:
1. new layout of association map;
```
