### ISSUE TITLE
Enhance shell support in function List

### ISSUE THREAD

**Issue by mat-m** [notepad-plus-plus/notepad-plus-plus#2318]
### Description of the Issue

Currently functions are well detected, but some awk scripts are messing with the patterns.
### Steps to Reproduce the Issue
1. Remove .txt extension from attachment [test_npp.sh.txt](https://github.com/notepad-plus-plus/notepad-plus-plus/files/486709/test_npp.sh.txt)
   , and open it in npp
2. Check the function list
### Expected Behavior

Only the functions are listed.
### Actual Behavior

functions are listed, but awk-embedded blocks also are.
![npp_function_list](https://cloud.githubusercontent.com/assets/1039753/18740472/2933947e-80aa-11e6-9aa0-bcceff01fc72.png)
### My view

I think some patterns should be stricter
From [bash-hackers](http://wiki.bash-hackers.org/syntax/basicgrammar), grammar looks like:
`NAME ()          <COMPOUND_COMMAND> <REDIRECTIONS>`
`function NAME () <COMPOUND_COMMAND> <REDIRECTIONS>`
`function NAME    <COMPOUND_COMMAND> <REDIRECTIONS>`

So one point is that `()` should always be empty
another point is that we should exclude from functions NAME the list of reserved keywords like if, while...
### Debug Information

Notepad++ v6.9.2
Build time : May 18 2016 - 00:34:05
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : ON
Local Conf mode : OFF
OS : Windows 7
Plugins : ComparePlugin.dll mimeTools.dll NppCCompletionPlugin.dll NppConverter.dll NppExport.dll NppFTP.dll nppplugin_ofis2.dll nppplugin_solutionhub.dll nppplugin_solutionhub_ui.dll NppSaveAsAdmin.dll PluginManager.dll QuickOpenPlugin.dll XMLTools.dll

**Comment by MAPJe71** [comment]
There are only three function definitions in the attached file, right?
i.e. `VerifVarEnv()`, `HelpMessage()` and `Out`.

**Comment by MAPJe71** [comment]
Could you (or anyone else familiar with Bash/Shell) try this parser and let me know how it works out?
```XML
			<association id="bash_function" langID="26" />

			<parser
				displayName="Bash - Bourne-Again Shell"
				id         ="bash_function"
				commentExpr="(?x)
						# Single Line Comment
						(?-s:(?:^\#[^!]|^[\t\x20]*\#|[\t\x20]+\#).*$)
					|
						# String Literal - Double Quoted
						(?s:&quot;(?:[^&quot;\\]|\\.)*&quot;)
					|
						# String Literal - Single Quoted
						(?s:&apos;[^&apos;]*&apos;)
					|
						# Here Document (Type 1) and Here String
						&lt;{2,3}(?'ID'[A-Za-z_\x7f-\xff][\w\x7f-\xff]*\b)[^\r\n]*\R
						(?s:.*?)
						\R\k'ID'            # close with exactly the same identifier in the first column
					|
						# Here Document (Type 2)
						&lt;{2}-(?'ID'[A-Za-z_\x7f-\xff][\w\x7f-\xff]*\b)[^\r\n]*\R
						(?s:.*?)
						\R[\t\x20]*\k'ID'   # close with exactly the same identifier
					"
				version    ="2.0.0.0"
			>
				<function
					mainExpr="(?mx)
							^
							[\t\x20]*
							(?-i:function\s+)
							(?'VALID_ID'
								(?-i:\b(?!(do(ne)?)|(el(if|se)|esac)|(f(i|or|unction))|(if|in)|(select)|(t(hen|ime))|(until)|(while))\b)
								[A-Za-z_]\w*                # valid identifier
							)
							(?:\s*\([^)]*?\))?              # parentheses and arguments optional
							[^{}]*?\{                       # start of body
						|
							(?&amp;VALID_ID)
							(?:\s*\([^)]*?\))               # parentheses required, arguments optional
							[^{}]*?\{                       # start of body
						"
				>
					<functionName>
						<nameExpr expr="\b(?!function\b)\w+(?:\s*\([^)]*\))?" />
						<!-- comment out the following node to display the function with its parameters -->
						<nameExpr expr="\w+(?=\s*\()" />
					</functionName>
				</function>
			</parser>
```

**Comment by mat-m** [comment]
Sorry it took a long time.

This had no effect to bash function parsing, I still have the same results as in the screenshot. 
Is there a cache to clear or something like that ?

**Comment by MAPJe71** [comment]
See [#2317](https://github.com/notepad-plus-plus/notepad-plus-plus/issues/2317#issuecomment-251089236)

**Comment by mat-m** [comment]
This one is better but still jams with:
    `cat $FICRESULT | $AWK '{ if (length($0)>0) {print $0}}'	`
It shows `length` as a function. 
I think we can ask for the function name to be at beginning of line (modulo blanks). I don't know how to say this using the regexes.

**Comment by mat-m** [comment]
@MAPJe71 If I understand the code, the function list only uses the functionName block. I think it misses the anchor to begin of line (modulo indentation). Anyone trying to begin a function after a semi-colon does not deserve his function to be listed :-)
I will try to play with it.

**Comment by MAPJe71** [comment]
See updated parser above.

**Comment by mat-m** [comment]
Perfect !
Thank you for this.
It will help me greatly.

**Comment by mat-m** [comment]
@MAPJe71 : do you plan to submit a pull request for that & 2317 ?

**Comment by MAPJe71** [comment]
Yes I do.
