### ISSUE TITLE
Notepad++ searches and edits binary files by default?

### ISSUE THREAD

**Issue by Knocks** [notepad-plus-plus/notepad-plus-plus#232]
I had important rar files in the same directory as HTML files that I was working on, and after running a few "Find in Files" queries I realized Notepad++ was editing rar files and corrupting them.

Questions:

1) Since Notepad++ is mainly a text editor and not a binary or hex editor, shouldn't editing binaries be disabled by default?

2) If Notepad++ is obviously not good at editing RAR files (seeing that it's corrupting them), why enable this feature at all?

3) Which setting is responsible for opting in and out of editing binaries, so I can avoid losing my work in the future?

**Comment by Rikk** [comment]
Why are you opening binaries with Npp++?

**Comment by Knocks** [comment]
I think you just read the title of the question and skipped the details.  I am not opening binaries.  Notepad++ is opening and editing binaries.  That's the issue.

**Comment by xylographe** [comment]
If your folders contain a mixture of text and binary files, and they're not part of a repository, you might want to use a different multiple file search&replace tool—[grepWin](http://stefanstools.sourceforge.net/), for example.

Of course, if those rar files were really important, you would have had **back-ups**. :smile:

**Comment by Knocks** [comment]
Those RARs were a backup.  Of my HTML files.

My point still stands.  Notepad++ has no business editing RAR files.  It's a text and code editor.

**Comment by Rikk** [comment]
Do you also think it should not even try to search inside unsupported formats?

**Comment by Knocks** [comment]
I suppose it's OK to have that option in the settings for users who want to experiment.  But I personally would have it disabled and most users probably would too.

It's one thing to try to open an unknown format in an editor to study the file, but "Find and replace" should not be looking inside binaries.

**Comment by Rikk** [comment]
Imo, searching inside all files -- incl. binaries and unknown formats -- on disk is better being a task of external tools, eg. the fabulous [SearchMyFiles](http://www.nirsoft.net/utils/search_my_files.html).
Otherwise, Npp takes the risk of corrupting files, as revealed in this thread.

**Comment by macdjord** [comment]
How do you determine what is a 'binary file'? Too many high bits set? Fine for ASCII, but it'll fail on unicode files. Extensions? What about unrecognized ones?
Find In Files is a powerful but *dangerous* tool. You *have* to be aware, when using it, of exactly which files it is going to be touching and what's in them, or else you can easily change things you did not mean to - and this would be the case even if it was perfectly recognize and skip binary files.

**Comment by Knocks** [comment]
@macdjord You're making this overly complicated.  If it's a file type that Notepad++ natively knows how to edit, then "Find in files" should include those files.  If not, then it shouldn't.  And it should definitely not edit file types that are pretty much guaranteed to be ruined: exes, compressed files/archives, images, etc.

**Comment by Knocks** [comment]
Why wast his assigned the "invalid" label and closed?

**Comment by donho** [comment]
Because it's not an issue but the questions.

**Comment by Knocks** [comment]
It's an issue.  The issue is that this "feature" is corrupting files and needs to be either removed or have a setting added to disable it.

**Comment by macdjord** [comment]
@Knocks The problem is how exactly do you define 'file type that Notepad++ natively knows how to edit'? By file extension? Great - if you only ever work with native Windows data, where every file has a registered extension. But if you look at, say, source code from a unix application, you'll find tons of perfectly valid plain text files that have weird extensions or no extension at all. You can't have find/replace skipping every .gitignore file it finds because it might possibly be binary.

**Comment by bilbothebaggins** [comment]
@Knocks what is unclear to me here is: Did NPP edit/save the files by merely using the find-in-files dialog, or were the files corrupted after you actually opened the file(s) in NPP? Thanks.

**Comment by Knocks** [comment]
@macdjord At the very least Notepad++ should not be editing files with extensions that are known to signify binaries.  

@bilbothebaggins Not sure I understand the question.  When you use the "Find in files" command, you provide values for 'find' and 'replace' fields, and the app searches all files in the specified directory and edits them.

**Comment by DavidHansen-0x454d43** [comment]
@Knocks I agree with the comments saying that it is not N++'s job to determine if the file is binary. 

A couple suggestions:
1. Perhaps you could do a 'Find All' before the 'Replace in Files' to verify you won't be replacing in any files you know are binary
2. Or you could create a filter for the files that you _do_ want to modify (e.g. *.html;*.htm;*.css)

**Comment by lousyd** [comment]
I wish this issue hadn't been closed with "wontfix". It bugs me that I can't exclude binary files when I search. There are times when it's useful to find a string even if it's in a *.exe file, but those times are pretty rare. *.exe, *.jar, *.zip (unless it treats the files inside the zip as separate files unto themselves), *.dll. It's not too much of a problem to manually exclude those file types every time I search, but I do have to manually remember them and type them in every time. It would be convenient to be able to tell N++ to either exclude known binary file types (maybe with a setting to edit the list for yourself?) or to limit its search to file types with which the program is associated.

**Comment by Cerno-b** [comment]
I re-opened this idea by providing a possible solution to some of the ideas dismissed here.
https://github.com/notepad-plus-plus/notepad-plus-plus/issues/8857

I would love to see some improvement in the Find in Files dialogue because it is very helpful already and it would be awesome to make it a bit more powerful

**Comment by Cerno-b** [comment]
@lousyd This might interest you
