### ISSUE TITLE
Ignored text from translation in V7.0

### ISSUE THREAD

**Issue by schnurlos** [notepad-plus-plus/notepad-plus-plus#2320]
Some new text, even correctly translated and in the right files (german.xml f.e.) is not translated in Notepad++ V7, f.e.:
<Item id="41021" name="Restore Recent Closed File"/>
Some text is still not translatable, f.e.:
"Trim trailing and save" and for sure some more.

**Comment by cmeriaux** [comment]
Sometime, you must change the language twice to force the update : 
Change language From german to english
 Change one more time English to german

Do you still have the problem ?

**Comment by schnurlos** [comment]
No, that worked - thanks.
Didn't know about this.

**Comment by cmeriaux** [comment]
coul'd you close the issue ?

**Comment by schnurlos** [comment]
Some text is still not translatable, f.e.:
"Trim trailing and save" and for sure some more.
