### ISSUE TITLE
Feature Request -  Multiple 'shortcuts'

### ISSUE THREAD

**Issue by ReneMelek** [notepad-plus-plus/notepad-plus-plus#2322]
I'm a translator and love having lots of boiler-plate stuff on shortcut keys. Love it so much I've maxed out the mapping options. For years I've been renaming shortcuts.xml >>> LanguageAshorts.xml;
then renaming LanguageBshorts.xml >>> shortcuts.xml, and restarting NP++, again and again.

Could NP++ easily be tweaked so that on startup it could accept any xml filename beginning with the string 'shortcuts'? Users could then select from a dropdown box which file is the default shortcuts.xml for a particular session, stock several shortcut.xml variants in the AppData \ ... folder (shortcuts_French, shortcuts_German, etc.), and easily choose the right one for the current session. Restart probably still required, but oh so much quicker.

**Comment by cmeriaux** [comment]
An "import shortcuts" function would make the job,  Isn't it ?

**Comment by ReneMelek** [comment]
Yes, as you know, that is not possible now.

sent from my Avvio phone in PNG

**Comment by MetaChuh** [comment]
this feature will currently not be implemented at the notepad++ core.

if you need multiple shortcuts.xml, you can use multiple portable instances of notepad++, where each has an isolated shortcuts.xml.

thank you for your help and best regards.

**Comment by sasumner** [comment]
...or create a batch file to set up the correct shortcuts file before starting N++
