### ISSUE TITLE
Feature Request: Adjustable empty space after margin

### ISSUE THREAD

**Issue by Gitoffthelawn** [notepad-plus-plus/notepad-plus-plus#2323]
The border width setting comes close do doing what I want: to be able to adjust the empty space between the left border and the leftmost pixels of the text.

Instead of adding more empty space, however, that setting makes the border wider.

Can you add a setting (hidden or otherwise) to adjust the empty space between the left border and the leftmost pixels of the text?

(For RTL languages, replace "left" and "leftmost" with "right" and "rightmost", respectively.)

**Comment by NoneGiven** [comment]
This, please. Also between the top of the window and the topmost pixel of text. And between the cursor and the character to its left...

I hate to say it, but Windows Notepad's padding looks much nicer than NPP's:

Notepad++:

![padding1](https://cloud.githubusercontent.com/assets/2163967/25683537/a234dfd8-302a-11e7-8904-8d073657134e.PNG)

Notepad:

![padding2](https://cloud.githubusercontent.com/assets/2163967/25683540/a6f63b2a-302a-11e7-842a-2f1a57e00319.PNG)

**Comment by sasumner** [comment]
Closing as this is not worth doing.

**Comment by morozover** [comment]
«empty space between the left border and the leftmost pixels of the text»
I need this option too.

![image](https://user-images.githubusercontent.com/17902666/96148073-97773f00-0f10-11eb-99cd-7aaa255dee3d.png)

Would you please reopen this issue?

**Comment by sasumner** [comment]
It appears that there **_IS_** an existing Scintilla call for this that I overlooked:

https://www.scintilla.org/ScintillaDoc.html#SCI_SETMARGINLEFT

So I'll remove the "Scintilla dependent" label.

While I can't imagine why existing behavior would bother someone, that's just MO.

I'll reopen and I'll see what I can do for this.

**Comment by sasumner** [comment]
>Also between the top of the window and the topmost pixel of text

I've still no idea how that could be done -- ideas from anyone?

>And between the cursor and the character to its left...

Or this?

**Comment by sasumner** [comment]
It doesn't look all that great when text is selected:

![image](https://user-images.githubusercontent.com/30118311/96166338-d941be80-0eeb-11eb-8558-480b23b03bcf.png)

And, BTW, `notepad.exe` doesn't have anywhere near the big "gap" that @NoneGiven posted a screenshot of earlier; here's my experience with it:

![image](https://user-images.githubusercontent.com/30118311/96166533-1908a600-0eec-11eb-8e20-ca60c3291c61.png)

**Comment by morozover** [comment]
> It doesn't look all that great when text is selected:
> 
> ![image](https://user-images.githubusercontent.com/30118311/96166338-d941be80-0eeb-11eb-8558-480b23b03bcf.png)
> 
> And, BTW, `notepad.exe` doesn't have anywhere near the big "gap" that @NoneGiven posted a screenshot of earlier; here's my experience with it:
> 
> ![image](https://user-images.githubusercontent.com/30118311/96166533-1908a600-0eec-11eb-8e20-ca60c3291c61.png)

In Windows 7 Notepad has gap of 1 mm:

![image](https://user-images.githubusercontent.com/17902666/96168676-c51cb200-0f29-11eb-99b1-df1f2fe5c613.png)

**Comment by sasumner** [comment]
@morozover Hmm, 1mm, I have visions of you holding a ruler up to your screen...

I'm thinking that this would have to have a preference setting controlling it, because I'm sure it will be either a users-love-it or users-hate it kind of thing.

I'm thinking a checkbox turns it on or off.
For users that need more "granularity" than that, they leave it off and set it via plugin.

I'm thinking the preference belongs on the new `Margin/Border/Edge` sub-page in _Preferences_, so this issue will be dependent upon #8896 being done first.

**Comment by sasumner** [comment]
@donho, what's your feeling about this?

It has also come up a few times in the Community:  https://community.notepad-plus-plus.org/topic/20157/how-to-add-a-gap-between-letters-and-border-of-n-window/24

**Comment by donho** [comment]
@sasumner 
Yes, it's possible. Scintilla allows to set margin between border & text (for 4 sides, if my recall is good). 
I wanted to implement then I forgot as always :)
I'll try to find the API and implement it.

**Comment by donho** [comment]
I assign this issue to myself also so I can refind it easily.

**Comment by sasumner** [comment]
@donho You go ahead with this one.

**Comment by fml2** [comment]
Scintilla does not provide an option for the top gap. But it could be possibly implemented by rendering the scinitilla component a bit lower. This is just an assumption, I have not checked it.

**Comment by sasumner** [comment]
>Scintilla does not provide an option for the top gap. But it could be possibly implemented by rendering the scinitilla component a bit lower. This is just an assumption, I have not checked it.

I cannot see anybody wanting to put that kind of effort into achieving it.

**Comment by fml2** [comment]
Yes, absolutely true!
