### ISSUE TITLE
Feature Request: Run current opened script

### ISSUE THREAD

**Issue by jNizM** [notepad-plus-plus/notepad-plus-plus#2325]
Hey Don Ho,

first thanks for your work on Notepad++ and the new Version 7 with 64-Bit support.

My request is to integrate a function (a hotkey and or a button) to run the current opened script.
(Like the old RunMe Plugin from fstellari does)

Would be a nice feature, since I (and for sure many others too) use it daily.

greets
jNizM

**Comment by cmeriaux** [comment]
You can do that with nppExec plugin (32 bits only)

**Comment by jNizM** [comment]
Would be nice for 64 bits. And would be better if something like this is in npp implemented.

**Comment by MetaChuh** [comment]
please use the built in run feature to run your scripts.
for all run features that you might miss, please use plugins like nppexec.
