### ISSUE TITLE
Add SHA256 signature

### ISSUE THREAD

**Issue by wbsdty331** [notepad-plus-plus/notepad-plus-plus#2327]
Both Installer and Executable file

**Comment by einsteinsfool** [comment]
> Probably not GPG but sha256 will be provided in the next release (sha512 will be done as well in the future)

donho commented on Sep 2, 2017 (in #2524)

@donho 
Gimp recently switched from MD5 and SHA1 to SHA256 and SHA512. Older sums might be left alone but for new releases only SHA256 and SHA512 should be provided as MD5 and SHA1 provide false sense of security. They don't prove file hasn't been altered, they just decrease the probability it has.

**Comment by beerisgood** [comment]
*push* again

**Comment by alexhass** [comment]
https://support.comodo.com/index.php?/Knowledgebase/Article/View/1102/38/code-signing-certificates---sha-1-and-sha-256-information

> This restriction will not apply to the time-stamp certificate used to time-stamp the code-signing certificate or the certificate’s signature hash (thumbprint) until January 1, 2017. After this time, Windows will treat any code with a SHA-1 time-stamp or SHA-1 signature hash (thumbprint) as if the code did not have a time-stamp signature."

So all software should be signed with SHA256 only. SHA1 signatures are no longer needed as Windows 7 has full support for SHA256 and SHA1 is only required for WinXP/Vista and both are no longer suppored.

**Comment by sasumner** [comment]
@alexhass Clearly XP is no longer truly supported (by M$). There is some "waffling" about whether XP is supported in Notepad++ or not.  Lately it seems the answer is "it is".  Sadly, IMO.

**Comment by beerisgood** [comment]
See my repo for that: https://github.com/beerisgood/Notepad-plus-plus-integrity_stuff
I don't think the dev will change anything here

**Comment by alexhass** [comment]
Currently signing sha1 is faded out. Soon no CA will sign sha1... supporting xp is really a joke today. No browser supports it for about 1 year, too.

Still all no reason not signing with sha256.

**Comment by beerisgood** [comment]
Fixed since https://github.com/notepad-plus-plus/notepad-plus-plus/releases/tag/v7.6.3
