### ISSUE TITLE
Feature Request: tab size and style quick-switch hotkey

### ISSUE THREAD

**Issue by frank26080115** [notepad-plus-plus/notepad-plus-plus#2332]
Some people like tabs to be replaced by spaces, some people do not. Some prefer the size to be 2, some prefer 4, some even use 8.

I request that a simple hotkey be added to cycle through these simple 4 options.

We can all sympathize with working on projects where code comes from different sources and everybody has a different style.

Notepad2 has CTRL+T to change the tab settings. Notepad++ requires 3 mouse clicks just to get to the "Tab Settings" section of "Preferences", and then a few more clicks to get the job done.

Perhaps the current tab setting can be displayed beside the newline style section of the bottom status bar.

I would be happy if this was a plugin too.

Thanks

**Comment by MetaChuh** [comment]
while this is a nice and possible idea for plugins, it will currently not be implemented at the notepad++ core.

thank you for your help and best regards.
