### ISSUE TITLE
anchor in links

### ISSUE THREAD

**Issue by AleksandarPantic** [notepad-plus-plus/notepad-plus-plus#2334]
### Steps to Reproduce the Issue

1. start Notepad++ and open a new file
2. type: file:///C:/text/index.html#anchor_example
3. Create in folder C:\text  an html file named index.html with a following tag: <a name="anchor_example">Some text</a>
4. When double clicking on that link in Notepad++ the '#anchor_example' part of the address is disregarded and as a result the html file is not open at a desired location
### Expected Behavior

The file should be opened at the exact anchor location
### Actual Behavior

The file is opened at the beginning of the file

**Comment by MetaChuh** [comment]
not reproducible with web links like https://www.rapidtables.com/web/html/link/html-anchor-link.html#same-page on 7.6.6.

please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins if you update from version 7.5.9 or below.
if your issue still persists, and it is still of relevance, please feel free to file a new issue as easy to understand and reproducible as possible.

thank you for your help and best regards.

**Comment by cakepuller** [comment]
This issue persists in notepad++ v7.7.1.
I suspect when the url starts with HTTP*, the browser opens to the desired anchor.
However, when it is "file:///..." it doesn't.
