### ISSUE TITLE
Notepad ++ crashes everytime 

### ISSUE THREAD

**Issue by pshashank8** [notepad-plus-plus/notepad-plus-plus#2341]
### Description of the Issue

Whenever i open any file in notepad ++ it keeps crashing after 1,2 mins

I have other text editors also installed in the same machine, does this cause some conflict ? But i've selected notepad ++ to be my default editor
![npp](https://cloud.githubusercontent.com/assets/16872447/18828480/bfb6fa8c-83f5-11e6-8913-88fac189b5b4.PNG)

Please suggest a fix for this issue

**Comment by cmeriaux** [comment]
Please, report debug info available in "?" menu
You should confirm your porblem with the last version (V7)
You should try to remove plugins

**Comment by donho** [comment]
@pshashank8 You cannot just go to see the doctor by only telling him/her "Cure me please, I'm sick". 
So we can do nothing about your report. Please use issue template : 
https://github.com/notepad-plus-plus/notepad-plus-plus/blob/master/ISSUE_TEMPLATE.md
to report your crash (and reopen it of course).
