### ISSUE TITLE
Feature Request: tab re-ordering also re-orders Doc Switcher files

### ISSUE THREAD

**Issue by cslemmen** [notepad-plus-plus/notepad-plus-plus#2342]
### Description of the Issue

I use Doc Switcher (aka Document List Panel) nearly all the time as a way to quickly bring a doc tab to focus. I also often move doc tabs around; I tend to actively work with tabs that are right-most whereas left-most tabs are things pending, temporarily sidelined, or reference docs. This re-ordering of tabs does not also re-order the Doc Switcher doc names. This makes Doc Switcher much less useful as, without re-ordering anything, the Doc Switcher order matches the tab order - top Doc Switcher file is left-most tab, bottom file is right-most tab. If these could kept in sync the Doc Switcher would be even more useful. Perhaps it could be an option somewhere.
### Steps to Reproduce the Issue

1. Open 2 or more files.
2. Make the Doc Switcher panel appear: Settings > Preferences > General > Document List Panel > Show [X]
3. Move one of the files' tabs to a new position. Notice that the Doc Switcher order is unchanged.
### Desired Behavior

Ideally the Doc Switcher order would mirror the visible tab order, regardless of where one moves a doc's tab.
### Actual Behavior

Doc Switcher order does not change in response to moving doc tabs around.

Here's a capture before moving tabs around:
![npp_doc_switcher_pre_tab_move](https://cloud.githubusercontent.com/assets/18722778/18835376/d1596db0-83c8-11e6-9904-d1543db7a946.png)
And here's one after switching around the two tabs:
![npp_doc_switcher_post_tab_move](https://cloud.githubusercontent.com/assets/18722778/18835397/e74ef59a-83c8-11e6-8beb-a484870eb8a2.png)
Notice the Doc Switcher order remains the same. If it could change in response to tab moves life would improve markedly here.

Thanks for reading and for Notepad++ - it rocks.

-csl

**Comment by rmaus** [comment]
**_Work-around_**:
Arrange top-row file tabs as desired, then exit and re-open Notepad++.  Doc Switcher tabs top-down order now reflects top-row file tabs left-to right order.

**Comment by AngryGamer** [comment]
My pull request fixes this problem. Enjoy!

**Comment by pidgeon777** [comment]
Also interested.
