### ISSUE TITLE
Npp V7 is release but can't get via npp update

### ISSUE THREAD

**Issue by SinghRajenM** [notepad-plus-plus/notepad-plus-plus#2343]
### Description of the Issue

Notepad++ V7 is released, but it is not upgraded via notepad++.

### Steps to Reproduce the Issue

1. Open Notepad++6.9.2
2. Click on ? -> then "Update Notepad++"
3. Observe the messagebox

### Expected Behavior

It should ask to update to npp as npp7 is released.

### Actual Behavior

No update available.

**Comment by dail8859** [comment]
This is expected. The auto updater is delayed intentionally in case critical issues are found (which there has been).

**Comment by SinghRajenM** [comment]
Oh, I see. Thank you for confirmation.
Let me close this ticket.
