### ISSUE TITLE
In column mode only print the lines with carets

### ISSUE THREAD

**Issue by wang3522** [notepad-plus-plus/notepad-plus-plus#2345]
### Steps to Reproduce the Issue

1. Open a new file and type something
2. use Alt to select multiple rows
3. send to printer
### Expected Behavior

print the whole document
### Actual Behavior

only print out the active lines
### Debug Information

Notepad++ v6.9.2
Build time : May 18 2016 - 00:34:05
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 7
Plugins : mimeTools.dll NppConverter.dll NppExport.dll NppFTP.dll NPPJSONViewer.dll NppScripting.dll PluginManager.dll

**Comment by dail8859** [comment]
From looking at the code this is expected behavior which is not just limited to column mode, but if you have *any* selection.

Whether this is *good* behavior is a different question.

**Comment by MetaChuh** [comment]
please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins if you update from version 7.5.9 or below.
if your issue still persists, and it is still of relevance, please feel free to file a new issue as easy to understand and reproducible as possible.

thank you for your help and best regards.

**Comment by sasumner** [comment]
Who has an argument for why current behavior *isn't* good and correct behavior?
