### ISSUE TITLE
Possible Bug: Missing custom verbose backup folder prevents saving.

### ISSUE THREAD

**Issue by noido** [notepad-plus-plus/notepad-plus-plus#2346]
### Steps to Reproduce the Issue

0. Copy a whole bunch of configs from an old version. Maybe I broke something here.
1. Backup setting is verbose, to a custom folder that doesn't exist.
2. Try to save the file. "Save As" works. Regular Save (ctrl+S) doesn't.

### Expected Behavior

The file should save. Also, it should give a warning that the custom backup folder doesn't exist, or possibly even create that folder, then save.

### Actual Behavior

The file cannot save. Not from the menu Save, not from the ctrl+S shortcut. When the defined custom backup folder is created, the file can save. No save, no warning is a confusing outcome.

**Comment by LWChris** [comment]
Bug confirmed: I renamed my backup directory from "backup" to "_backup" before opening N++. Saving a new file works, changing it and saving it per Ctrl+S, the "File"-menu or the save dialog when closing N++ fails. As soon as I renamed the folder back to "backup", saving worked again.
