### ISSUE TITLE
%1 is not a valid Win32 application

### ISSUE THREAD

**Issue by suiwenfeng** [notepad-plus-plus/notepad-plus-plus#2350]
### Description of the Issue
cannot install any plugins for new installed nodepad++v7 for 64bit. it will prompt a messagebox and let me remove the dll from plugin folder.

### Steps to Reproduce the Issue
1. Download and install new v7 64bit installer
2. Download the plugin from https://sourceforge.net/projects/npppluginmgr/
3. Settings -> Import  -> Plugin(s) , then %1 is not a valid win32 application.

### Actual Behavior
![image](https://cloud.githubusercontent.com/assets/2735407/18882015/1c76c3f4-8510-11e6-9114-2be7aa630ff2.png)

### Debug Information
Notepad++ v7   (64-bit)
Build time : Sep 21 2016 - 22:07:28
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 7
Plugins : mimeTools.dll NppConverter.dll

**Comment by dail8859** [comment]
Notepad++ 64-bit cannot load 32-bit plugins (which most plugins have not been updated to support 64-bit). 

As I suspected this would soon be an issue I have #2348 currently in the works. It displays a proper errors message.

**Comment by suiwenfeng** [comment]
I can guess that`s the issue, but do we have the plugins can be used in 64bit. i cannot even install plugin manager. can you provide some guide how plugins installed in 64bit.

**Comment by dail8859** [comment]
> but do we have the plugins can be used in 64bit

Not sure what you are asking.

> i cannot even install plugin manager

The plugin manager is only 32 bit. 

> can you provide some guide how plugins installed in 64bit.

The exact same way as with 32 except the plugin *must* be compiled to support 64-bit Notepad++.
