### ISSUE TITLE
Support more encodings through ICU

### ISSUE THREAD

**Issue by garydgregory** [notepad-plus-plus/notepad-plus-plus#2357]
### Description of the Issue

I need supported for the IBM-1047 encoding. This can be done with http://site.icu-project.org/ which contains a gazillion encodings.
### Steps to Reproduce the Issue

There is such option
### Expected Behavior

Under Encodings/Character sets/I'd like to see an alphabetical list of encodings, not organized by country.
### Actual Behavior

Can't do it.
### Debug Information

N/A

**Comment by donho** [comment]
> Under Encodings/Character sets/I'd like to see an alphabetical list of encodings, not organized by country.

It's rather a feature request for re-organization of encoding menu, nothing to do with ICU.

Though ICU is a good project, I don't see the advantage to use it in Notepad++.
Currently there's no the same request for re-organization of encoding menu, so it won't be implemented.
