### ISSUE TITLE
New files are not being added in "Folder as Workspace"

### ISSUE THREAD

**Issue by miguelofbc** [notepad-plus-plus/notepad-plus-plus#2358]
### Description of the Issue

I'm working with Notepad++ using a Network Map Drive and when I open a "Folder as Workspace" the files created in the remote directory are not being showed in the "Folder as Workspace" window.

Is there any way to refresh the files inside those directories?

I was trying close Notepad++ and open the editor again and the files are being updated. But that should work without closing window.

Is this a known issue?

**Comment by SinghRajenM** [comment]
@miguelofbc  please provide debug information. (Menu -> ? -> Debug Info).
Have you tried with latest version?

**Comment by miguelofbc** [comment]
Do you mean 7?

**Comment by miguelofbc** [comment]
Yes, I'm seeing the same bug for Notepad++ 7 version...

**Comment by innocentliny** [comment]
I have same problem.
"Folder as Workspace" should automatically add new files into workspace.
This is needed.

[DebugInfo]
`Notepad++ v7.3.3   (32-bit)
Build time : Mar  8 2017 - 03:37:37
Path : D:\Downloads\Motepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : ON
OS : Windows 7 (64-bit)
Plugins : Explorer.dll mimeTools.dll NppConverter.dll NppExport.dll PluginManager.dll 
`

**Comment by Nuadin** [comment]
I'm seeing the same issue as well, and I really need to be able to use this function for the new folder/files I added in that section. The issue only seems to have started recently, as I was able to add something about a week or two ago. Here's my debugging info as well, in case the more info the better:

[Debug Info]
`Notepad++ v7.3.3   (32-bit)
Build time : Mar  8 2017 - 03:37:37
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10 (64-bit)
Plugins : mimeTools.dll NppConverter.dll NppExport.dll PluginManager.dll 
`

**Comment by MetaChuh** [comment]
please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins if you update from version 7.5.9 or below.
if your issue still persists, and it is still of relevance, please feel free to file a new issue as easy to understand and reproducible as possible.

thank you for your help and best regards.
