### ISSUE TITLE
switch to folded tab issue

### ISSUE THREAD

**Issue by ichenq** [notepad-plus-plus/notepad-plus-plus#236]
Notepad++ version: 6.7.8.2
OS: Windows 7 x64

When switch back to a folded tab, npp process hangs.

Step 1: Open a 500KB xml file
Step 2: Press Alt + 0 to fold all
Step 3: Switch to another tab and switch back

When I download the code and attach to running process, it seems that the regex module runs into a inefficient loop.

**Comment by ichenq** [comment]
![Uploading npp.png…]()

**Comment by ichenq** [comment]
![npp](https://cloud.githubusercontent.com/assets/238406/8178311/596a82f2-143f-11e5-8692-f2b11478fa92.png)

'TerranBuildingPrototype.xml' is a 887KB xml file, d.json is a small size json data file.

**Comment by dail8859** [comment]
Pull request #168 should fix this issue if/when it is merged.

**Comment by BrainJelly** [comment]
I think that this should be labeled as a bug not an enhancement.
