### ISSUE TITLE
Remove bookmarked lines performance issue

### ISSUE THREAD

**Issue by WillBee** [notepad-plus-plus/notepad-plus-plus#2362]
### Description of the Issue
Deleting many bookmarked lines takes an unexpected long time and totally freezes Notepad++.

### Steps to Reproduce the Issue
1. Use search/find/mark and enter some text to find
2. Check "Bookmark line" and click "Mark all"
3. In search/Bookmark, select "Remove Bookmarked lines"

### Expected Behavior
Line deletion is expected to be quick and responsive. (Or like any slow process should at least provide some progress or status feedback to the user).

### Actual Behavior
Deleting about 5000 bookmarked lines over a 20000 line files takes several seconds and totally freezes Notepad++ (on a multicore 2.66ghz cpu system)

### Debug Information
performance issue only
reproducible with V6.7.8.2 (32bits) and V7 (64bits).

**Comment by dail8859** [comment]
I would try disabling your plugins to see if that helps.

I created text file with 40,000 lines, randomly bookmarked ~10,000 lines and it took about 3 seconds. 

What kind of file is it? Does it use any syntax highlighting?

**Comment by jasmeet45** [comment]
it was reproducible in v 7.0 but in v 7.1 it is fixed
