### ISSUE TITLE
[Feature] Add Delete Current Line to Line Operations

### ISSUE THREAD

**Issue by martbase** [notepad-plus-plus/notepad-plus-plus#2363]
It will be convenient to have a Delete Line command preferably with a keyboard shortcut for removing entire lines when editing documents.

Currently you need to select the line first before deleting it which slows down edits where one needs to remove entire lines in a document.

An example
```
nav li {
  propertya: valuea;
  propertyb: valueb; // <-- Delete this line
  propertyc: valuec;
  propertyd: valued; // <-- Delete this line
  propertye: valuee;
}
```

**Comment by MAPJe71** [comment]
If I remember correctly this has been issued before (i.e. duplicate) but can't remember the number.

@martbase 
There are plugins that implement this functionality (neither are available through the PluginManager):
- [Mackenzie Zastrow's VisualStudioLineCopy plugin](https://bitbucket.org/zastrowm/notepad-visualstudiolinecopy/) (C++ Win32)
- [Kasper B. Graversen's CutNCopyLine plugin](kbilsted/NppPluginCutNCopyLine) (C#)

It can also be achieved by running the applicable script with one of the script plugin's (both are available through the PluginManager):
- [David Brotherstone's PythonScript plugin](https://github.com/bruderstein/PythonScript)
- [Dail's LuaScript plugin](https://github.com/dail8859/LuaScript/releases/tag/v0.5.1)

**Comment by dail8859** [comment]
There is a built in shortcut of `Shift+Ctrl+L`.

This can be changed through the shortcut mapper. `Settings > Shortcut Mapper... > Scintilla Commands > SCI_LINEDELETE`.

**Comment by martbase** [comment]
@dail8859 
Thanks, the shortcut works perfectly

I tried searching for the command and since it wasn't obvious from the available menu options I assumed it wasn't implemented.

@MAPJe71
I searched through the issues first before posting but I didn't get any that applies.

**Comment by martbase** [comment]
It would still be cool to add the command to the Line Operations to improve the User Experience especially for a new user not conversant/familiar with the keyboard shortcuts. This will also aid in learning the commands and their shortcuts.
