### ISSUE TITLE
Bookmark doesn't get removed

### ISSUE THREAD

**Issue by dail8859** [notepad-plus-plus/notepad-plus-plus#2366]
### Description of the Issue
When multiple bookmarked lines get merged it requires more than 1 click in the margin (or `Ctrl+F2`) to remove the bookmark.

### Steps to Reproduce the Issue

1. Open new document
2. Press `Enter` 5 times
3. Click bookmark margin on each line (don't move cursor) to turn on bookmarks
4. Press backspace
5. Click bookmark on line 5 (nothing happens)
6. Click again, bookmark gets removed

### Expected Behavior

Bookmark gets immediately cleared.

### Actual Behavior

Requires multiple attempts based on the number of lines that got merged.

### Debug Information

```
Notepad++ v6.9.2
Build time : May 18 2016 - 00:34:05
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 7
Plugins : mimeTools.dll NppConverter.dll NppExport.dll NppFTP.dll PluginManager.dll 
```

**Comment by jasmeet45** [comment]
it is fixed in v 7.1.
cheers!!
