### ISSUE TITLE
Feature Request: Set preferences inside files , e.g. word-wrap

### ISSUE THREAD

**Issue by saturdaywalkers** [notepad-plus-plus/notepad-plus-plus#2371]
### Description of the Issue

Add per-file preferences or inline-file preferences, a bit like vi.

At present, these settings are per-computer
- so they may be wrong on another computer (e.g. tab spacing)
- and different file-types my be best with different settings

A 'per-file' preference would be something like the below inside a comment being edited
# ++Notepad++ word-wrap: on
# ++Notepad++ tab-stop: 4

An 'inline-file' preference would be something like the below inside a comment being edited
- i.e. preference set / unset for a block

text not wrapped
# ++Notepad++ word-wrap: on

now its wrappped
# ++Notepad++ word-wrap: off

now its not wrapped
### Steps to Reproduce the Issue

n/a
### Expected Behavior

n/a
### Actual Behavior

n/a
### Debug Information

n/a

**Comment by MAPJe71** [comment]
Have a look at [EditorConfig](http://editorconfig.org/).

**Comment by sasumner** [comment]
For word wrap see:
https://notepad-plus-plus.org/community/topic/10985/file-specific-word-wrap-vs-global-enable
https://notepad-plus-plus.org/community/topic/16941/feature-request-word-wrap-per-tab
