### ISSUE TITLE
Feature Request: Sort Plugins Menu Items by Name

### ISSUE THREAD

**Issue by KAH777** [notepad-plus-plus/notepad-plus-plus#2372]
Hi.  Currently, it looks like the plugins listed under the Plugins menu item are sorted by DLL name ("tip of the hat" to Dail for that information).  Please see attached screen shot for an example.

Would you consider changing it to sort by menu item name?  This would make it more efficient to find the plugins that we need to use.

Thank you,

Kevin
![pluginslist](https://cloud.githubusercontent.com/assets/22547861/18999742/be1cb970-8704-11e6-9013-01f2cc98499a.png)

**Comment by dail8859** [comment]
Pending pull request #2347

**Comment by dail8859** [comment]
Closed by d64a525f3e7921b6bed735e4298e8e85f09c71c1

**Comment by Gitoffthelawn** [comment]
Is this patch working for others?  In v7.9.5 32-bit portable, *Plugins* menuitems appear in seemingly random order (not alphabetic).

**Comment by Gitoffthelawn** [comment]
I figured out the issue.  Some plugins provide a unique "friendly name" while others do not.  For example, NppConverter.dll provides the English "friendly" name "Converter", but Notepad++ sorts it under "N" for "NppConverter.dll".  This is a plugin distributed with Notepad++... LOL.

Npp needs to sort by the actual menu name being displayed if the intention is to sort by the actual menu name.

Please re-open, this is broken.

**Comment by Gitoffthelawn** [comment]
Note the `JSON Viewer` and `Customize Toolbar` plugins display the same behaviour as the included `Converter` plugin, so they can be used for testing as well.

**Comment by Gitoffthelawn** [comment]
@donho Let me know if you need more details.
