### ISSUE TITLE
Feature Request: Option for *not* Auto-Populating Search Box

### ISSUE THREAD

**Issue by KAH777** [notepad-plus-plus/notepad-plus-plus#2373]
When doing a Find (and/or Replace), I understand that it can be handy to have the search box auto-fill the text you are searching for with what is already highlighted.  However, there are many times that I want to bring up the Find window and have it search for the last item I searched for (or, sometimes I will switch from doing a Find to doing a "Mark All" or what have you).

Would it be possible and practical to modify Notepad++ with one of the following two behaviors?
  1.  Add an option in Settings to allow users like myself to turn off auto-populate (this is my #1 choice).
  2.  If no text is highlighted, then do not auto-populate search box.

Thank you for your consideration.

Kevin

**Comment by kashalot** [comment]
> there are many times that I want to bring up the Find window and have it search for the last item I searched for

Isn't that already the current behavior?

- When I call up the search or replace box with no text highlighted, it's populated with the last thing I searched for.
- The text in the Find box is pre-selected when the search window comes up, so if you want to search for something different you can just start typing and overwrite it.  Having a special setting to remove autofill wouldn't save you a single keystroke in this scenario.
- If you specifically need to repeat the previous search while you have another chunk of text highlighted (which seems odd, given that the search is going to discard your current highlighting, but let's roll with it), pressing the Down arrow scrolls through your search history, so you can get to the last search you performed with one keystroke.

**Comment by KAH777** [comment]
My apologies.  Using the version I have at home, I see that you are correct.  I'm not sure how I was missing that, unless my version at work has a plugin installed that is causing this behavior (unlikely, though).

Either way, it is clearly behaving as you describe.  Sorry to waste your time.  I will close the "issue".

Kevin

**Comment by imthenachoman** [comment]
It would still be a nice feature to not auto-populate search period. I know I can press the down arrow but from a productivity perspective, it slows me down having to move my right hand from the mouse to the down arrow. I'd rather it keep my previous search query.
