### ISSUE TITLE
Battery issue on background

### ISSUE THREAD

**Issue by varosi** [notepad-plus-plus/notepad-plus-plus#2374]
### Steps to Reproduce the Issue
1. Leave Notepad++ for longer time
2. Settings | Battery usage
3. It's on the first place of battery usage

### Expected Behavior
When on background to not use the battery so much.

### Actual Behavior
Use the battery in background.

Windows 10 
Notepad++ 6.9.2

![image](https://cloud.githubusercontent.com/assets/6051718/19013522/c9c02cda-87db-11e6-9e37-1f69152d5f52.png)

**Comment by dail8859** [comment]
I'd try disabling your plugins first to make sure its not one of them.

**Comment by jwallis43** [comment]
I have it in first place at 22%
