### ISSUE TITLE
Hide all, then unhide with find

### ISSUE THREAD

**Issue by uhammec** [notepad-plus-plus/notepad-plus-plus#238]
The IBM mainframe editor ISPF/PDF has a very powerful feature which I've never seen as well implemented in any other editor.  They called it EXCLUDE (see below for example commends).

The use case is simple:
1) Open a text file
.           (all lines are naturally shown)
2) Hide from view all or selected lines from the text file  (e.g. EXCLUDE ALL)
.           (the < > arrows in the left hand column show where there is hidden lines)
3) Find for some text
.           (the matching lines are all shown, and thus only those lines are automatically unhidden)

This is a very powerful feature that can really help when "grepping through" a file while keeping all the lines available in the original context (just selectively hidden from view).

It looks like Notepad++ is very very close to having that functionality, it just isn't a simple feature that can be remembered by the casual user pretty easily.

It would be fantastic to have the Find function be slightly extended to enable that concept.
   Thanks.    LOVE Notepad++ ... extremely useful tool!!!!

As a reference implementation for what I am suggesting, you might look at EXCLUDE here:

>  http://www.ruifeio.com/2013/01/18/ispf-useful-commands/
> CHANGE X string1 string2
> .   Changes string1 with string2 scanning only the lines that are excluded from the display
> CHANGE NX string1 string2
> .   Changes string1 with string2 scanning only the lines that are not excluded from the display
> DEL X
> .   Deletes all the lines that are excluded
> DEL NX
> .   Deletes all the lines that are not excluded
> EXCLUDE ALL
> .   Hides from view all the lines of the member being edited and replaces them with a dashed line. EXCLUDE string
> .   Hides from view the first line that contain a search string
> EXCLUDE string ALL
> .   Hides from view all the lines that contain the search string
> EXCLUDE string PREV
> .   Hides from view the line that contains the search string before the cursor
> EXCLUDE string NEXT
> .   Hides from view the line that contains the search string after the cursor
> EXCLUDE string PREFIX
> .   Hides from view the line that contains the search string as a prefix from a word

**Comment by ccrembil** [comment]
A similar feature already exists as part of the "TextFX Characters" plugin. 

After install it, just look for
TextFX, 
- TextFX Viz, 
- - Hide Lines without (Clipboard) text

**Comment by MetaChuh** [comment]
closed due to inactivity

**Comment by alankilborn** [comment]
See [HERE](https://community.notepad-plus-plus.org/topic/23929) for a related topic.
