### ISSUE TITLE
"Clear this result" should also be present

### ISSUE THREAD

**Issue by ranjan-ranjan** [notepad-plus-plus/notepad-plus-plus#2386]
### Description of the Issue

"Clear this result" should also be present
### Steps to Reproduce the Issue

1.  Find some word.
2.  See the output window
3.  On right clicking one of the result, "Clear this result" should also come.
### Expected Behavior

"Clear this result" should be one of the option to be reproduced in the above steps in the place as marked in the snapshot.
### Actual Behavior

There's no "Clear this result" option.
### 

![1](https://cloud.githubusercontent.com/assets/16834561/19065343/9f1f2eca-8a30-11e6-903e-d899753ea443.png)
Reference

**Comment by vlakoff** [comment]
Indeed, this functionality would be very helpful.

**Comment by cmeriaux** [comment]
you can click on the line you wan't to suppress and then "delete" key

**Comment by ranjan-ranjan** [comment]
Yes, this works. Thanks.

But, my point was to have it in context menu also.

**Comment by sasumner** [comment]
>have it in context menu also.

That *would* be great, if for nothing else than a reminder.  (I'd forgotten that the Delete key works in the Find-result panel!)

**Comment by vlakoff** [comment]
Agree too with the above.
