### ISSUE TITLE
Visible Zoom Level

### ISSUE THREAD

**Issue by sbsimonsen** [notepad-plus-plus/notepad-plus-plus#2388]
### Description of the Issue

Can you add showing of zoom level, when I use Ctrl- and mouse wheel? I would like to see that I'm back at 100% (or any other setting). I use this functionality in Outlook mails and other places. Zoom level should also be shown using Ctrl-Num+ and -
### Steps to Reproduce the Issue

1. 
2. 
3.

**Comment by vlakoff** [comment]
Just as a reminder, you can use <code>Ctrl + numpad "/"</code> to reset the zoom.
