### ISSUE TITLE
NPPM_DMMUPDATEDISPINFO has no effect

### ISSUE THREAD

**Issue by dail8859** [notepad-plus-plus/notepad-plus-plus#2389]
### Description of the Issue
NPPM_DMMUPDATEDISPINFO has no effect after changing the `tTbData` struct.

### Steps to Reproduce the Issue
Run this code:

```c
tTbData tbData;

tbData.uMask = DWS_DF_CONT_BOTTOM | DWS_ADDINFO;
tbData.pszName = TEXT("pszName");
tbData.pszAddInfo = TEXT("pszAddInfo");
tbData.dlgID = 0;
tbData.iPrevCont = -1;

SendMessage(_hParent, NPPM_DMMREGASDCKDLG, 0, (LPARAM)&tbData);
tbData.pszName = TEXT("abc");
tbData.pszAddInfo = TEXT("123");
SendMessage(_hParent, NPPM_DMMUPDATEDISPINFO, 0, (LPARAM)&tbData);
```

### Expected Behavior
The caption should update with the new name/info.

### Actual Behavior
The caption doesn't change.

### Debug Information

```
Notepad++ v7   (32-bit)
Build time : Sep 21 2016 - 22:00:56
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : ON
Local Conf mode : OFF
OS : Windows 7
Plugins : DoxyIt.dll ElasticTabstops.dll LuaScript.dll mimeTools.dll NppConverter.dll NppExport.dll PluginManager.dll 
```

I don't think `NPPM_DMMUPDATEDISPINFO` is use often so I doubt this effects many plugin developers but feel it at least needs documented here

**Comment by dail8859** [comment]
Nevermind ... I'm dumb.

**Comment by SinghRajenM** [comment]
I am in the same boat.
@dail8859, did you find any solution for this? I want to change the title of plugin based on the filename.
e.g. `Json Viewer Panel - new 1` to `Json Viewer Panel - new 2` when user switches from `new 1` to `new 2`

![image](https://github.com/user-attachments/assets/48a9403b-1b8d-4bf9-a8bb-0ad59f63909f)


cc: @donho

**Comment by donho** [comment]
@SinghRajenM 
This issue was opened and closed 8 years ago.
If you encountered the problem, please open a new issue and ping me.
I'll check it for sure.

**Comment by SinghRajenM** [comment]
@donho 

For me, it was question/help topic rather bug. Hence asked here if any solution @dail8859 has for this.
Nevermind, I got the solution on [community forum](https://community.notepad-plus-plus.org/topic/26091/how-to-update-title-of-plugin).
