### ISSUE TITLE
Closing of tab with middle mouse button broken

### ISSUE THREAD

**Issue by kczx3** [notepad-plus-plus/notepad-plus-plus#2390]
Since updating to v7, I find that I am no longer able to close an open file by clicking on it’s tab with my middle mouse button.

**Comment by kczx3** [comment]
It seems this only malfunctions when Notepad++ is ran as an Administrator...

**Comment by BestBeanC** [comment]
Couldn't replicate bug issue even when run as administrator.

**Comment by MetaChuh** [comment]
please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins if you update from version 7.5.9 or below.
if your issue still persists, and it is still of relevance, please feel free to file a new issue as easy to understand and reproducible as possible.

thank you for your help and best regards.
