### ISSUE TITLE
Notepad++ 64bit still doesn't handle properly very large files

### ISSUE THREAD

**Issue by SMH17** [notepad-plus-plus/notepad-plus-plus#2393]
Seems that even newer 64 bit version isn't able to open very large files. 

To fix this issue should be implement a dynamic incremental load of the file that avoid out of memory problems.

**Comment by donho** [comment]
64-bit version could handle more data in memory theoretically.
This issue regards the way scintilla process the data (no incremental load) but has nothing to do with x64 version.

**Comment by SMH17** [comment]
The main vantage to have 64 bit in a notepad is to handle memory intensive operations that a 32 bit version cannot do. If the notepad doesn't handle big files most of the vantage to have a 64 bit Notepad++ is lost. This is a problem that shouldn't be ignored.

**Comment by informatorius** [comment]
What is the problem with very large files on x64? Is notepad++ hung or an error popup shown?

**Comment by SMH17** [comment]
@informatorius  error popup with message "file is too big"

**Comment by informatorius** [comment]
How big is the file you try to load and how much memory does the notepad++ process use?

**Comment by informatorius** [comment]
@donho: I found it in the source code.
notepad-plus-plus-master\PowerEditor\src\ScitillaComponent\Buffer.cpp:1376
```
// As a 32bit application, we cannot allocate 2 buffer of more than INT_MAX size (it takes the whole address space)
if (bufferSizeRequested > INT_MAX)
{
		::MessageBox(NULL, TEXT("File is too big to be opened by Notepad++")
}
```
The limit should be "allocatable RAM". 

Can you reopen the issue?

**Comment by bandtank** [comment]
I'm having this issue with v7.4.2 32-bit and the file isn't even close to 2 GB. It's 791 MB.

**Comment by informatorius** [comment]
2 options: 
a) If your OS is 64bit then use notepad++ 64bit
b) If your OS is 32bit then patch the notepad++ executable using http://www.ntcore.com/4gb_patch.php

**Comment by dail8859** [comment]
@bandtank You are assuming Notepad++ needs to only allocate a single byte of memory for every byte in the file...which is far from correct.

**Comment by bandtank** [comment]
I made no such assumption. Previous comments in this thread provide enough context to make my comment clear.

**Comment by bandtank** [comment]
@informatorius thanks. I will try that.

**Comment by smndnv** [comment]
Same problem here. I'm using Notepad++ 64-bit on a 64-bit Windows 10 machine with 16GB of RAM. My text file is 5.25 GB and I get the error: File is too big to be opened by Notepad++

Please fix this!

**Comment by informatorius** [comment]
@smndnv: That is the 4GB limit of the underlying scintilla text editor. They do not fix it currently (not suported). I don't know any workaround for that.

**Comment by smndnv** [comment]
@informatorius: I tried Sublime Text. It loaded the whole file into memory, but at least is successfully opened it.

**Comment by MRatnam** [comment]
I don't understand why this is closed? We have home desktop systems with 32GB/64GB/128GB RAM and PCIe SSDs nowadays with ~3GB/s read speed (yes that is GIGABYTE/s). Why is there a 2GB file size limit?

**Comment by informatorius** [comment]
The problem is Notepad++ is based on Scintilla which has the 2GB file size limit. But Scintilla devs don't want to fix that. If somebody would fix it there then it would work in Notepad++ too.
https://sourceforge.net/p/scintilla/bugs/1595/

For those with programming skills: Scintilla code uses e.g. type int for filesize and structures in memory => 2GB limit. If that would be changed to some BigInt then problem could be solved. Or the file could be read and write in several 2GB chunks.

**Comment by ljcool2006** [comment]
I am having this issue as well; the file i'm trying to open isn't even 2GB, it's 1.7GB. I am using the 64-bit version of Notepad++.
