### ISSUE TITLE
Notepad++ 7.x installer - Please use "next" instead of "I agree" after GPL screen

### ISSUE THREAD

**Issue by jaalto** [notepad-plus-plus/notepad-plus-plus#2396]
There is a slight misunderstanding in the installer. The GPL is not an EULA and therefore button [I agree] is out of place.  If user would rather "I disagree", it is still OK to install GPL'd software as GPL is not something that has to bee agreed or disaggreed with. GPL gives rights, like delivering free software for anyone to use *and* install.

Simply use [Next] button after informative GPL message. This is what Audacity etc. projects use in similar installers that display GPL screen.

**Comment by donho** [comment]
A pull request could make such request more valuable. Otherwise I'm not a fanatic of software license to do a lot of effort for fixing it.

**Comment by jaalto** [comment]
Could you pint me to the directory where the installer is controlled? What installer is in use?

**Comment by pantosha** [comment]
Notepad++ installer is created by NSIS.

Titles and labels on license page are generated by NSIS Modern User Interface.
Text on agree button of license page can be changed with `MUI_LICENSEPAGE_BUTTON ` property.

For more information see http://nsis.sourceforge.net/Docs/Modern%20UI/Readme.html
