### ISSUE TITLE
Feature Request: Add listbox of open files to "find" and "replace" dialog to limit "...in all opened documents" functionality to certain open files

### ISSUE THREAD

**Issue by tds123** [notepad-plus-plus/notepad-plus-plus#2397]
This idea is based off what I originally thought issue #2227 was about. The "find in all opened documents" and "replace in all opened documents" are great features, but I think it would be great to have a listbox maybe to the right of the "find next" section of buttons (you could stretch the dialog out to accommodate space-wise) that lists the open files and when you select files in the listbox ("extended multi-selection" of course) it could change the text on the buttons to "Find All in All **Selected** Documents" and "Replace All in All **Selected** Documents" instead, and restrict the functionality to only those files. I think this would be extremely helpful. If this issue were to be accepted, I'd love to be assigned to it. 
![2e192eb6-950b-11e6-91c6-304f5c590b14](https://cloud.githubusercontent.com/assets/4001416/19969099/aa61533c-a1ad-11e6-862d-ac7a0eda1e06.PNG)
![2e1970b0-950b-11e6-93ea-3c82e5d23cc4](https://cloud.githubusercontent.com/assets/4001416/19969100/aa6cf516-a1ad-11e6-9cbe-a2e68edb3c11.PNG)

**Comment by MetaChuh** [comment]
please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins if you update from version 7.5.9 or below.
if your issue still persists, and it is still of relevance, please feel free to file a new issue as easy to understand and reproducible as possible.

thank you for your help and best regards.

**Comment by sasumner** [comment]
@MetaChuh Haha, for this one it is clear you should have just put the REJECT label on it. :)
