### ISSUE TITLE
Wrong folding (ALT+NUM) for YAML file

### ISSUE THREAD

**Issue by nowox** [notepad-plus-plus/notepad-plus-plus#2398]
### Description of the Issue

With the following file: 

```
Foo:
    Bar:
        FooBar: 42
```

The shortcuts `<Alt+2>` or `<Alt+1>` do no work. Only the first level work using `<Alt+0>` and `<Alt+Shift+0>`.
### Steps to Reproduce the Issue
1.  Run Notepad++ 7
2.  Paste the above example
3.  Select YAML language from menu Language/YAML
4.  Hit Alt + 1 to fold  `Bar:`
5.  Notice that `Bar:` is not folded.
### Expected Behavior

In the shortcuts `<Alt+Num>`, the corresponding `Num` level should be folded in the whole file.

**Comment by dail8859** [comment]
This seems to be the same type of issue that Python has (see #1898). Fold levers are based on number of leading spaces.

There are a couple temporary work-arounds though. You can multiply the fold level you want with the number of spaces. You can only fold the first 2 levels though. Alternatively you could change your indentation to use 2 spaces (which is the YAML specification) or 1, then you can fold more levels.

**Comment by zufuliu** [comment]
This was fixed by PR #5131.
