### ISSUE TITLE
[bug] extra wide file menu

### ISSUE THREAD

**Issue by CanadianJeff** [notepad-plus-plus/notepad-plus-plus#2399]
### Steps to Reproduce the Issue
1. click file
2. click empty recent files list
3. click file again
### Expected Behavior

the file menu would resize back to a normal size
### Actual Behavior

extra wide file menu
### Screenshot

http://i.imgur.com/6cQBQn5.png

**Comment by CanadianJeff** [comment]
updated to version 7.3.2 issue still persists

**Comment by dail8859** [comment]
@CanadianJeff You'll have to wait for the next version.

**Comment by CanadianJeff** [comment]
alot of software puts recent files list in a submenu that could have solved this problem ages ago

**Comment by dail8859** [comment]
In that case it was already solved a long time ago. It is in your preferences...

`Settings > Preferences... > Recent File History > In Submenu`

**Comment by CanadianJeff** [comment]
why not just have that as a default setting it really is common practice in alot of software
