### ISSUE TITLE
Bug in Notepad ++ for large files

### ISSUE THREAD

**Issue by khharut** [notepad-plus-plus/notepad-plus-plus#24]
I have encountered a bug in Notepad++ last version. When I replaced quotes (i. e. ") in a large text file and saved it I founded strange symbols at the end file that had not existed before replacement. Even more, some comas remained after replacement. I have used Notepad++ for two years and never seen anything like that. It is really good multipurpose editor. I think this bug has appeared since 6.3 version.

**Comment by ariccio** [comment]
[This is a known issue.](https://sourceforge.net/p/notepad-plus/bugs/5233/)

**Comment by ariccio** [comment]
#120 is a proposed semi-fix.

**Comment by khharut** [comment]
Thanks for mentioning solution.

**Comment by ariccio** [comment]
> Thanks for mentioning solution.

My pleasure! It helps everyone involved.

**Comment by ariccio** [comment]
I believe that this was fixed in 17e8ca3c15b151308e4ad68e85a878630dce793a ?

**Comment by khharut** [comment]
I do not know what version it is referred to, but the problem is fixed in 6.8 version of Notepad++. Thanks.

**Comment by ariccio** [comment]
Awesome. Close this issue?

**Comment by khharut** [comment]
Of course.
