### ISSUE TITLE
[Bug] NP++ v7 64bit uninstaller is removing wrong registry key

### ISSUE THREAD

**Issue by narutards** [notepad-plus-plus/notepad-plus-plus#2400]
### Description of the Issue
When uninstalling the 64bit version of NP++ the uninstaller will try to remove the information from the registry under "HKEY_LOCAL_MACHINE\SOFTWARE\Wow6432Node\Microsoft\Windows\CurrentVersion\Uninstall\Notepad++" instead of "HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\Notepad++" (see the "Wow6432Node" part).

This means that the registry still contains an orphaned entry of NP++ v7 which makes it look like the software is still installed, while it actually isn't.

### Steps to Reproduce the Issue
1. Install NP++ v7 64bit
2. Export registry key "HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\Notepad++"
3. Edit and import the registry file to "HKEY_LOCAL_MACHINE\SOFTWARE\Wow6432Node\Microsoft\Windows\CurrentVersion\Uninstall\Notepad++" with a changed "DisplayName"
4. Uninstall NP++ v7 64bit
5. See how the key from the "Wow6432Node" branch got removed while the original key is still present.

### Expected Behavior
Remove the correct key from the registry.

**Comment by dail8859** [comment]
This was recently fixed in 181b4875215d259e45a01ac0244eebcc0bd81ea1 and will be available in the next release.
