### ISSUE TITLE
when switching from mono-instance to multi-instance, user has to close each tab individually

### ISSUE THREAD

**Issue by bennetthaselton** [notepad-plus-plus/notepad-plus-plus#2403]
### Steps to Reproduce the Issue

1. With Notepad++ still in mono-instance mode (the default), open two or more files, say a.txt and b.txt. In mono-instance mode, a single instance of Notepad++ shows each file as a separate tab, as expected.
2. Go to Settings->Preferences->Multi-instance and switch from "Default (mono-instance)" to "Always in multi-instance mode".  Note the text at the bottom of the dialog: "*The modification of this setting needs to restart Notepad++".
3. Close Notepad++
4. In Windows Explorer double-click to open a text file.

(Note that Actual Behavior and Expected Behavior are switched below, because Expected Behavior involves several possibilities, each of which are variations on current Actual Behavior.)
### Actual Behavior

Notepad++ opens up still in mono-instance mode, with one tab for each file.  The files that you had open in step 1 above will still be open in tabs.  Even if you open another file, it will open as an additinoal tab.  As far as I can tell, in order to truly switch from mono-instance mode to multi-instance mode, you have to close each tab individually that is open in mono-instance mode, and then you can start opening files in multi-instance mode.
### Expected Behavior

I think there are several possibilities that would be more user-friendly:
(A) At minimum, if you want to keep current behavior, then I think the text at the bottom of the dialog box in step 2 above should say "Changing this setting requires Notepad++ to be restarted.  If you change from mono-instance mode to multi-instance mode, you must close each individual tab open in mono-instance mode, and then Notepad++ can be reopened in multi-instance mode."  This requires only a text change. (And fixes the bag grammar that is there now :) )
(B) After switching from mono-instance mode to multi-instance mode and closing Notepad++, next time you run it, open only the file that was opened (or a new file), without any tabs.  The drawback here is that the user may had several files open that they were working on, and now those files don't come back after re-starting Notepad.
(C) After switching from mono-instance mode to multi-instance mode and closing Notepad++, each file that was previously open in a tab should open in a new window.  This prevents the user from losing open documents, but some users don't find it a good experience if a bunch of windows open suddenly (even if it's the same documents they had open previously in tabs).
(D) After switching from mono-instance mode to multi-instance mode and closing Notepad++, next time you start Notepad++, give the user a choice between (B) and (C) above.  ("You switched Notepad++ from mono-instance to multi-instance.  Do you want to documents that you previously had open in tabs, and re-open each of them in separate windows?")  This is probably the most user-friendly but requires the most work.
### Debug Information

Notepad++ v7   (32-bit)
Build time : Sep 21 2016 - 22:00:56
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10
Plugins : mimeTools.dll NppConverter.dll NppExport.dll NppTextFX.dll PluginManager.dll

**Comment by MAPJe71** [comment]
Do you have `Remember current session for next launch` enabled?
(Can be found in menu `Settings`, sub-menu `Preferences...`, item `Backup`, group `Session snapshot and periodic backup`)

**Comment by bennetthaselton** [comment]
Thanks for replying.  In the "Backup" options currently:
- I have "remember current session for next launch" checked
- I have "Enable session snapshot and periodic backup" UN-checked
- In the "Backup on save" section I have "None" selected

These were the install defaults and I didn't change them.

For clarification, are you saying that depending on the options I'm selecting there, the current behavior of Notepad++ might be correct behavior?  Or did you just want to know?

I would say that regardless of what options are selected on that screen, the current behavior is still buggy.  At minimum the help text on the Multi-instance screen should say "Changing this setting requires Notepad++ to be restarted. If you change from mono-instance mode to multi-instance mode, you must close each individual tab open in mono-instance mode, and then Notepad++ can be reopened in multi-instance mode."

**Comment by MetaChuh** [comment]
please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins if you update from version 7.5.9 or below.
if your issue still persists, and it is still of relevance, please feel free to file a new issue as easy to understand and reproducible as possible.

thank you for your help and best regards.

**Comment by bennetthaselton** [comment]
I updated to 7.6.6 and the current behavior is still the same original buggy behavior that I reported.

I don't know why this bug was closed.  Was someone hoping the issue had just gone away by itself?
