### ISSUE TITLE
Files opened from a `subst` drive continually show "file changed" dialog

### ISSUE THREAD

**Issue by cawoodm** [notepad-plus-plus/notepad-plus-plus#2405]
1. Create a substituted drive in Windows as in:

```
subst g: c:\users\me\something
```
1. Now open the file g:\app.js and the file c:\users\me\something\app.js (i.e. the same file twice)
2. Modify one of these files and save it.
3. Alt+Tab to a different application
4. Alt+Tab back to NPP and you will get a warning:
   This file has been modified by another program.
   Do you want to reload it.

**Comment by dail8859** [comment]
That doesn't sound like a bug. If the file on disk has changed then it should notify you.
