### ISSUE TITLE
NPPN_DOCORDERCHANGED doesn't set the correct nmhdr.hwndFrom handle.

### ISSUE THREAD

**Issue by botman99** [notepad-plus-plus/notepad-plus-plus#2406]
### Description of the Issue

NPPM_INTERNAL_DOCORDERCHANGED doesn't pass the correct handle in nmhdr.hwndFrom when notifying plugins.

### Steps to Reproduce the Issue

1. Write a plugin that checks that (notifyCode->nmhdr.hwndFrom == nppData._nppHandle) and (notifyCode->nmhdr.code == NPPN_DOCORDERCHANGED) in the beNotified() callback function in the plugin.
2. Notice that when the nmhdr.code == NPPN_DOCORDERCHANGED, the nmhdr.hwndFrom is not the nppData._nppHandle (like it is for other NPPN_xxx notification messages).

### Expected Behavior

notifyCode->nmhdr.hwndFrom will be set to nppData._nppHandle.

### Actual Behavior

notifyCode->nmhdr.hwndFrom is set to the lParam value that was passed into Notepad_plus::process().

### Debug Information

If you look at something that works properly, like NPPN_BUFFERACTIVATED, you can see it sets the hwndFrom to getHSelf(), like so:

	SCNotification scnN;
	scnN.nmhdr.code = NPPN_BUFFERACTIVATED;
	scnN.nmhdr.hwndFrom = _pPublicInterface->getHSelf();
	scnN.nmhdr.idFrom = (uptr_t)bufid;
	_pluginsManager.notify(&scnN);

But for NPPN_DOCORDERCHANGED, it uses the wrong value for hwndFrom (also the comment is wrong :) ):

	case NPPM_INTERNAL_DOCORDERCHANGED :
	{
		BufferID id = _pEditView->getCurrentBufferID();

		// Notify plugins that current file is about to be closed
		SCNotification scnN;
		scnN.nmhdr.code = NPPN_DOCORDERCHANGED;
		scnN.nmhdr.hwndFrom = reinterpret_cast<void *>(lParam);
		scnN.nmhdr.idFrom = reinterpret_cast<uptr_t>(id);
		_pluginsManager.notify(&scnN);
		return TRUE;
	}

If the plugin beNotified() code ignores the nmhdr.hwndFrom and just checks the nmhdr.code value then things work properly, but it would be nice if this was fixed (so you can filter on the mhdr.hwndFrom to determine if notifications come from _nppHandle, _scintillaMainHandle, or _scintillaSecondHandle).

**Comment by dail8859** [comment]
I can confirm I'm seeing the same thing when catching the NPPN_DOCORDERCHANGED notification. According to the [documentation](https://github.com/notepad-plus-plus/notepad-plus-plus/blob/51797bf59e689b11d80998758790f8a4cade68eb/PowerEditor/src/MISC/PluginsManager/Notepad_plus_msgs.h#L459) (keep in mind it isn't 100% correct) the `hwndFrom` value does carry other info with certain notifications.

**Comment by botman99** [comment]
Okay, I guess since this is documented to work the way that is does, this issue is probably invalid.  :)

**Comment by dail8859** [comment]
I guess instead of checking `hwndFrom` you can see if `nmhdr.code` is >`NPPN_FIRST` and < "some value".

I'm glad you pointed this out though because I'm sure I would have ran into this before too long, because I was doing the same thing just filtering out messages purely based on `notifyCode->nmhdr.hwndFrom == nppData._nppHandle`
