### ISSUE TITLE
TabBar::activateAt() doesn't send TCN_SELCHANGE message.

### ISSUE THREAD

**Issue by botman99** [notepad-plus-plus/notepad-plus-plus#2407]
### Description of the Issue

TabBar::activateAt() builds a message to send, but never actually sends it.
### Steps to Reproduce the Issue

1. Write a plugin that subclasses the Notepad++ windows notification function (using nppData._nppHandle as the handle for notifications).
2. In the subclassed function in the plugin, check for WM_NOTIFY messages with nmhdr.code == TCN_SELCHANGE).
3. Drag/drop a tab from the sub view to the main view (or main view to sub view).
4. Note that you don't get the TCN_SELCHANGE message (because it is never sent).
### Expected Behavior

TabBar::activateAt() should send the TCN_SELCHANGE message.
### Actual Behavior

TCN_SELCHANGE message wasn't sent.
### Debug Information

Here's the current code from TabBar::activateAt():

```
void TabBar::activateAt(int index) const
{
    if (getCurrentTabIndex() != index)
        ::SendMessage(_hSelf, TCM_SETCURSEL, index, 0);

    TBHDR nmhdr;
    nmhdr.hdr.hwndFrom = _hSelf;
    nmhdr.hdr.code = TCN_SELCHANGE;
    nmhdr.hdr.idFrom = reinterpret_cast<UINT_PTR>(this);
    nmhdr.tabOrigin = index;
}
```

Notice it creates a nmhdr message, but doesn't call ::SendMessage().  :)

The work around for this is to check for TCN_TABDROPPEDOUTSIDE messages in the subclassed Notepad++ function and those do get sent properly.

**Comment by MetaChuh** [comment]
please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins if you update from version 7.5.9 or below.
if your issue still persists, and it is still of relevance, please feel free to file a new issue as easy to understand and reproducible as possible.

thank you for your help and best regards.

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
(no extra account is needed, just use your github account to sign in)
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)
