### ISSUE TITLE
x64: Installer contains two NppShell_06.dll

### ISSUE THREAD

**Issue by yamlfd** [notepad-plus-plus/notepad-plus-plus#2408]
### Description of the Issue

x64 Installer contains x64 component for no reason
### Steps to Reproduce the Issue
1. Open EXE installer with 7Zip
2. Review the content
3. See the x86 component that should not there as it is a x64 version
### Expected Behavior

No x86 Shell DLL in x64 installer. Same for x86 installer that should not contain both DLLs with the SAME name. If you need both, name at least the x64 as x64 in the name, please.
### Actual Behavior

Setup cannot easily extracted to build the MSI setup.

**Comment by SinghRajenM** [comment]
>No x86 Shell DLL in x64 installer

I agree. There is no need keep x86 NppShell_06.dll. However from user perspective, there should be no issue if it there.

>Same for x86 installer that should not contain both DLLs with the SAME name.

In this case both the Dlls are required. A user can install 32bit npp version on x64 bit machine, that time NppShell x64 bit is required. About dll name, it is internal to the npp and moreover, it is not exposed to the user. So the name should not matter.
About MSI, I think @donho may have a plan for it (refer: #2326).

**Comment by yamlfd** [comment]
On x86 installer you need both or you cannot use the shell extension under a x64 system. However the file should not have the same file name. I cannot extract the DLL automactically to build the MSI for all people. The DLL only exists inside the EXE installers and not in the binary ZIP. In the MSI setup on hass.de I have renamed then and named them properly to it is clear that has been installed. NppShell64.dll or NppShell.dll for x86.

Much better would be to drop the shit NSI and migrate to MSI.

**Comment by yamlfd** [comment]
To repro the issue run this and you see a duplicate file issue.

"%ProgramFiles%\7-Zip\7z" x npp.%version%.Installer.exe -o"%workdir%" "nppIExplorerShell.exe" "NppShell_06.dll" "updater\*"

**Comment by yamlfd** [comment]
Found a workaround to automate it.

# x86
```
"%ProgramFiles%\7-Zip\7z" x npp.%version%.Installer.exe -o"%workdir%" "NppShell_06.dll" "updater\*" -aou
copy "%workdir%\NppShell_06.dll" "%version%\%arch%\NppShell64.dll"
copy "%workdir%\NppShell_06_1.dll" "%version%\%arch%\NppShell.dll"
```
#x64
```
"%ProgramFiles%\7-Zip\7z" x npp.%version%.Installer.%arch%.exe -o"%workdir%" "NppShell_06.dll" "updater\*" -aos
copy "%workdir%\NppShell_06.dll" "%version%\%arch%\NppShell64.dll"
x64
```

However, this still suxxx and is not reliable without unique file names.
