### ISSUE TITLE
HTML inside of Script tag formatted incorrectly

### ISSUE THREAD

**Issue by Harmonickey** [notepad-plus-plus/notepad-plus-plus#2411]
### Description of the Issue

When there is a script tag inside of a section of html that happens to have the text type be text/html then the html inside is not correctly formatted as html.  It only appears to affect the first few lines and then returns back to html formatting.  It affects collapsing of div tags at the beginning and is somewhat uneasy on the eyes when trying to look at the top of the script section.  I am using the sort of script tag in knockout templating.
### Steps to Reproduce the Issue

1.  Create html file.
2.  Insert an opening script tag with text='text/html'
3.  Insert at least 10 lines of html inside of the script tag
4.  Insert the ending script tag.
### Expected Behavior

I expected the html inside of this type of script tag to be formatted entirely as html.
### Actual Behavior

The first few lines are not formatted correctly as html.
### Debug Information

Notepad++ v6.9.2
Build time : May 18 2016 - 00:34:05
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10
Plugins : mimeTools.dll NppConverter.dll NppExport.dll NppFTP.dll PluginManager.dll 

![image](https://cloud.githubusercontent.com/assets/3519788/19258398/2040c890-8f3d-11e6-8746-5e28f9c04048.png)

**Comment by dail8859** [comment]
This issue is also present in the latest version of Scintilla (which is what Notepad++ uses internally). 

![capture](https://cloud.githubusercontent.com/assets/3694843/19272046/109009ee-8f95-11e6-8a2c-39cb1a367764.PNG)


It seems that "text/html" is not recognized thus it is trying to color it as JavaScript. This should be reported to the [Scintilla project](https://sourceforge.net/projects/scintilla/).

**Comment by Harmonickey** [comment]
Thanks for the insight.  I have reported the bug to them.

**Comment by vatioz** [comment]
This problem is also somewhat present for XML files. You can reproduce it by creating new file, selecting XML as a language and inserting following text:
`<root><Script>/*</Script></root>`

You will see that `/*` combination inside `Script` tag effectively terminates the XML highlighting.

**Comment by DannyMeister** [comment]
Found another reproduction of oddities with tags named <script> inside of XML.  It depends on the length of the tag itself.
`<installation>
	<database>
		<files>
			<script file="C:\A\Really\Looooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooong Path.sql" />
		</files>
	</database>
	<sites />
</installation>`

That stops xml parsing and end  `</files>` element.  If you remove even one "o" from the path, then the whole file parses correctly.

I can't find where to submit a bug to Scintilla.  The sourceforge site is 404'ing with a message that it is in static offline mode.

**Comment by buzzy** [comment]
I assume this issue has not been fixed yet? Just stumble upon it and it's quite annoying :)

**Comment by Harmonickey** [comment]
Agreed, I originally put in the request almost two years ago and haven't seen the fix yet.

**Comment by MetaChuh** [comment]
this request has still not been handled at the scintilla project.
see the open issue: https://sourceforge.net/p/scintilla/bugs/1871/

there is nothing we can do at the notepad++ part.

thank you for your help and best regards.
