### ISSUE TITLE
Add 'await', 'async', 'dynamic' to CSharp

### ISSUE THREAD

**Issue by olego** [notepad-plus-plus/notepad-plus-plus#2413]
### Description of the Issue
These 3 keywords are missing from C#: async, await, dynamic.  Please add them to langs.xml

### Steps to Reproduce the Issue
Open C# file, and write:

public async Task MyFunction()
{
 dynamic var = await MyOtherFunction();
}

**Comment by dail8859** [comment]
According to the [MSDN documentation](https://msdn.microsoft.com/en-us/library/x53a06bb.aspx) they aren't actually *reserved* keywords. (Side note: there are quite a few other keywords missing). However it may not be a bad idea to add them anyways.

The C# lexer wouldn't be able to distinguish when the "contextual keywords" are applicable or not. Do you (or any one else familiar with C#) think this would be a problem? Meaning it would *always* highlight these contextual keywords.

**Comment by olego** [comment]
I do a bit of C# programming, mostly in Visual Studio, but sometimes in
Notepad++ for quick edits.  Of all the code I've been exposed to, I've
never seen anyone using contextual keywords as function or variable names.
Typically, the style is camelCased variables, almost always spelled out,
and almost always multi-word, so to answer your question, I don't think it
would be a problem to always highlight these contextual keywords.

I think I can also indicate the most frequently-used contextual words, in
order:

var await async
"yield return" "yield break"
where
dynamic

So even if you only add those, I'll be super-happy.  By the way, "yield
break" and "yield return": does Notepad++ support keywords with spaces in
them?  Unlike others, they are the only two that can't be rearranged.

**Comment by dail8859** [comment]
I agree that it would most likely be rare to see these keywords elsewhere in code. 

> does Notepad++ support keywords with spaces in them?

Not it does not.

**Comment by olego** [comment]
Hooray!  Many thanks!

**Comment by dail8859** [comment]
Since these updates won't be available until the next release (and just in case you aren't aware), you can go ahead and add these yourself. Go to `Settings > Style Configurator > C# > INSTRUCTION WORD` and add them to the "User-defined keywords" on the right.
