### ISSUE TITLE
"İ" not the lowercase

### ISSUE THREAD

**Issue by gevv** [notepad-plus-plus/notepad-plus-plus#2417]
hi,

İ character is not lowercase
### Debug Information

Notepad++ v6.9.2
Build time : May 18 2016 - 00:34:05
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows XP
Plugins : mimeTools.dll NppConverter.dll NppExport.dll PluginManager.dll 

![untitled 1](https://cloud.githubusercontent.com/assets/5096676/19324351/d37c0ab8-90c9-11e6-8a40-4ce664c641c7.png)

![untitled 2](https://cloud.githubusercontent.com/assets/5096676/19324356/d9a80a54-90c9-11e6-93e6-43d67aaf402e.png)

**Comment by SinghRajenM** [comment]
By any change are you using Turkish Keyboard? I could not reproduce this issue with english keyboard.
If yes, this issue is occuring with dotted (İ) and dotless (I) seems to work fine.

**Comment by guy038** [comment]
Hello,  **gevv**,

You're really **not lucky** for that matter :-(((

Indeed, it happens that, among **all** the **Latin**, **Greek** or **Cyrillic** **`capital`** letters, of the default **Courrier New** font, which have an **lower-case equivalent** letter, the capital Azerbaijani Turkish letter **İ** ( **`\x{0130}`** ) is the **`unique`** letter **without** an **`lower-case`** equivalent, in Notepad++ !!

Indeed, in the **Unicode 9.0 Latin-Extended-A** code-chart, for the item **LATIN CAPITAL LETTER I WITH DOT ABOVE** of code point **`0130`** it's specified that the **lower-case** form of the **capital** letter **İ** is, simply, the normal lower-case **i** ( **`\x69`** )

Refer to the link, below :

http://www.unicode.org/charts/PDF/U0100.pdf

Below, I gather a **sorted** ( in the **A** .. to .. **Z** way ) list, of all **Latin**, **Greek** and **Cyrillic** letters, of the default **Courrier New** font, in their **both** forms ( **upper-case** and **lower-case** )

---

**Capital** Latin letters :

    ¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯↓
    AÀÁÂÃÄÅĀĂĄǍǺẠẢẤẦẨẪẬẮẰẲẴẶÆǼBCÇĆĈĊČDÐĎĐEÈÉÊËĒĔĖĘĚẸẺẼẾỀỂỄỆFGĜĞĠĢHĤĦIÌÍÎÏĨĪĬĮİǏỈỊĲJĴKĶLĹĻĽĿŁMNÑŃŅŇŊOÒÓÔÕÖŌŎŐǑƠỌỎỐỒỔỖỘỚỜỞỠỢŒØǾPQRŔŖŘSŚŜŞŠƏTŢŤŦÞUÙÚÛÜŨŪŬŮŰŲƯǓǕǗǙǛỤỦỨỪỬỮỰVWŴẀẂẄXYŸÝŶỲỴỶỸZŹŻŽ

**Small** Latin Letters :

    ¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯↓
    aàáâãäåāăąǎǻạảấầẩẫậắằẳẵặæǽbcçćĉċčdðďđeèéêëēĕėęěẹẻẽếềểễệfgĝğġģhĥħiìíîïĩīĭįiǐỉịĳjĵkķlĺļľŀłmnñńņňŋoòóôõöōŏőǒơọỏốồổỗộớờởỡợœøǿpqrŕŗřsśŝşšətţťŧþuùúûüũūŭůűųưǔǖǘǚǜụủứừửữựvwŵẁẃẅxyÿýŷỳỵỷỹzźżž

**Capital** Greek letters :

    ΆΈΉΊΌΎΏΑΒΓΔΕΖΗΘΙΚΛΜΝΞΟΠΡΣΤΥΦΧΨΩΪΫ

**Small** Greek Letters :

    άέήίόύώαβγδεζηθικλμνξοπρστυφχψωϊϋ

**Capital** Cyrillic letters :
 
    ЁЂЃЄЅІЇЈЉЊЋЌЎЏАБВГДЕЖЗИЙКЛМНОПРСТУФХЦЧШЩЪЫЬЭЮЯҐҒҖҚҜҢҮҰҲҸҺӘӨ

**Small** Cyrillic letters :

    ёђѓєѕіїјљњћќўџабвгдежзийклмнопрстуфхцчшщъыьэюяґғҗқҝңүұҳҹһәө

Best Regards,

guy038

**Comment by MetaChuh** [comment]
please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins if you update from version 7.5.9 or below.
if your issue still persists, and it is still of relevance, please feel free to file a new issue as easy to understand and reproducible as possible.

thank you for your help and best regards.
