### ISSUE TITLE
file content destroyed upon file save attempt if file used in browser

### ISSUE THREAD

**Issue by USFbobFL** [notepad-plus-plus/notepad-plus-plus#2419]
in version 6.9.2, if you click the save button after making some changes, then try to use the file (say in a browser) before the save is completed, Notepad++ crashes and the content of the file is gone.  When you re-open Notepad++ there is no content in the file and it has a zero length in file explorer.  

The has happened to me three times now in the past couple of days and I've had to restore my file from a backukp, losing all of the changes made since then.  I backup a lot, so I didn't lost much.

During the development of PHP apps on my local PC (Windows 10), I have the app running in a Chrome browser.  After I save changes, I click the reload button in the browser so that I see the changes to the PHP code.  If I save a file and don't wait long enough (for the save to complete)  before clicking the browser reload button, this error occurs.
### Steps to Reproduce the Issue
1. load a PHP program into Notepad++ that is at least 24K in size
2. load the PHP program a Chrome browser on localhost
3.  make some changes to the PHP program in Notepad 6.9.2
4. click the "Save button" to save your changes
5. click the browser refresh button
### Expected Behavior

The file should save safely, even if an external program tries to read during the save, but if not, a recovery method should be automatic.
### Actual Behavior

If the save was still in progress as you clicked the browser refresh button, Notepad++ will crash, the browser won't load the PHP program.  The content of the PHP file will be completely missing.
### Debug Information

Notepad++ v6.9.2
Build time : May 18 2016 - 00:34:05
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10
Plugins : mimeTools.dll NppConverter.dll NppExport.dll PluginManager.dll

**Comment by USFbobFL** [comment]
This is comforting.  My PC processor and OS are of the 64-bit variety, so I'm going to get version 7!

Notepad++ 7 new features and bug-fixes:

7.  Fix file saving crash which can be reproduced through a specific way to save file.

**Comment by tobozo** [comment]
Notepad++ 7.5.1 regression, bug is still present, I paste this here but I'm uninstalling this software forever to make sure it has failed me for the last time.

Notepad++ v7.5.1   (32-bit)
Build time : Aug 29 2017 - 02:35:41
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10 (64-bit)
Plugins : ComparePlugin.dll Explorer.dll FallingBricks.dll GmodLua.dll JSLintNpp.dll JSMinNPP.dll mimeTools.dll NppConverter.dll NppEditorConfig.dll NppExport.dll NppFTP.dll NPPJSONViewer.dll PluginManager.dll WindowManager.dll

**Comment by MetaChuh** [comment]
please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins if you update from version 7.5.9 or below.
if your issue still persists, and it is still of relevance, please feel free to file a new issue as easy to understand and reproducible as possible.

thank you for your help and best regards.
