### ISSUE TITLE
A new plugin to opearte on lines within a boundary.

### ISSUE THREAD

**Issue by suchin26** [notepad-plus-plus/notepad-plus-plus#242]
Hi,

For my personal use, i have currently created a set of perl scripts which would extract only certain lines of the file by giving the start and end line. For eg:- if you provide start and end line say, 200 and 800, only the lines within these line numbers would be extracted and opened in a new file it would also serve the purpose of splitting a large file into multiple files , also there are scripts which does, find, replace operations only within the line numbers you mention.
i wanted to know if it is a feasible ( or useful ) idea to create a plugin for this in n++.

**Comment by sanastasiou** [comment]
It is definitely feasible. If it is useful, you'll be the judge of that :)
