### ISSUE TITLE
Command line options - Feature request. Set WindowTitle

### ISSUE THREAD

**Issue by simon33-2** [notepad-plus-plus/notepad-plus-plus#2422]
### Description of the Issue

Can we add a command line option to set the Window Title? A few other editors offer this and it is important for some people who I deal with use of N++ because the filename is set to something meaningless and it would be nice to preserve it while also knowing what is being edited. Preserving the filename allows the file to be saved without needing to exit N++ and the calling program can then still access the file. Some other otherwise less featured editors do have this option.

**Comment by samertufail** [comment]
Is this feature still required? Currently filename as well as the full path is displayed as a window title. Are you suggesting that a user defined title is set and preserved for the duration N++ is open?

**Comment by simon33-2** [comment]
That was what I was suggesting. In cases I was thinking of, knowing the filename doesn't tell you anything useful because you're editing a temporary file with a meaningless name.

It's a nice to have.

**Comment by samertufail** [comment]
Sure. Should the provided title also be persistent/same for all the subsequent tabs opened after as well or just for a particular tab the file in question is open in?

**Comment by sasumner** [comment]
> knowing the filename doesn't tell you anything useful because you're editing a temporary file with a meaningless name.

Dude, save the file, thus giving it a meaningful name!

**Comment by MetaChuh** [comment]
the title will show the current file or tab name.
if you have a new tab you can rename it without saving to set your title.

thank you for your help and best regards.
