### ISSUE TITLE
Theme cloud-sync breaks when user-folder name different between machines

### ISSUE THREAD

**Issue by JVimes** [notepad-plus-plus/notepad-plus-plus#2429]
### Description of the Issue

When my user-folder name is different between machines, then the cloud-synced theme setting breaks on one of the machines.

It's because the stylerTheme path always expands to a full, literal path and DropBox/OneDrive are under user-folder, by default.
### Steps to Reproduce the Issue
1. Set cloud-sync to a synced folder under the user folder.
2. Pick a non-default theme (e.g. solarized)
3. After cloud-sync, open Notepad++ on a machine where the user-folder name is different.
### Expected Behavior

Expect the new theme to show up on both machines.
### Actual Behavior

The new theme is only on one of the machines. The other machine has default theme.
### Debug Information

Notepad++ v6.9.2
Build time : May 18 2016 - 00:34:05
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10
Plugins : DSpellCheck2.dll JSMinNPP.dll mimeTools.dll NppConverter.dll NppExport.dll PluginManager.dll

**Comment by MetaChuh** [comment]
please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins if you update from version 7.5.9 or below.
if your issue still persists, and it is still of relevance to you, please feel free to file a new issue as easy to understand and reproducible as possible.

thank you for your help and best regards.

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
(no extra account is needed, just use your github account to sign in)
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)
