### ISSUE TITLE
Clear one result in Search Results Window

### ISSUE THREAD

**Issue by Bentoy13** [notepad-plus-plus/notepad-plus-plus#243]
There is a command to clear all search results, but not a command to delete a search. It would be nice to be able to clear one search (but of course not one result within a search).

**Comment by cmeriaux** [comment]
Hello,
I can already do that manually. Do you confirm ?

**Comment by Bentoy13** [comment]
Hi,

Cool to get a reply so soon ... :)

I am using n++ v6.7.8.2, I haven't check this on the latest version.

I try to clear one search with a right click, my context menu is the
following:

[image: Images intégrées 1]
So no clear for one search, only clear all searches.
Or do you know how to do that? I found no way in Search menu either.

Regards,

Benoît


2015-06-17 14:05 GMT+02:00 Christophe Meriaux <notifications@github.com>:

**Comment by Bentoy13** [comment]
The image is not shown here, sadly. I write down all my choices of the context menu:
- Collapse All
- Uncollapse All
- Copy
- Select All
- Clear All
- Open All

I would appreciate a Delete...

**Comment by cmeriaux** [comment]
Just click on the line you want to suppress, then press the Delete button

**Comment by Bentoy13** [comment]
I'm so ashamed, I didn't try this ...
Sorry to have posted this as an issue, I deeply apologize for that.
Thank you very much for your answer!
Benoît

**Comment by cmeriaux** [comment]
You're welcome.
Maybe one day, you'll be the one helping someone else
;-)
