### ISSUE TITLE
Plugin Manager is missing

### ISSUE THREAD

**Issue by evildog1** [notepad-plus-plus/notepad-plus-plus#2430]
### Description of the Issue
I don't have much to say but Plugin Manager is missing. I tried to manually install Plugin Manager and Compare but it does not work on 64 bit. Very disappointed because it is the easiest way to install plugins and i really need compare plugin. Please don't remove any random features for no reason like Google devs are doing that.

### Steps to Reproduce the Issue
1. Install latest version of Notepad++
2. Launch Notepad++
3. Open "Plugins"

### Expected Behavior
Plugin manager should be shown under "Plugins"

### Actual Behavior
Plugin Manager is gone

### Debug Information
Notepad++ v7.1   (64-bit)
Build time : Oct 15 2016 - 23:35:37
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : ON
Local Conf mode : OFF
OS : Windows 10
Plugins : mimeTools.dll NppConverter.dll 

![image](https://cloud.githubusercontent.com/assets/8687585/19420679/e403b62c-93f0-11e6-9906-a7e00930732f.png)

**Comment by MAPJe71** [comment]
Please search the existing issues next time first.

The PluginManager and many of the other plugins are not available in 64-bit yet.

**Comment by silaoA** [comment]
I'm also expecting the PluginManager for 64-bit。
when will it be available？？？

**Comment by dail8859** [comment]
Although the PluginManager is incredibly useful, it is developed by a 3rd party developer. The author of the PluginManager is aware of the need for 64-bit but no clue when that will be available.

**Comment by silaoA** [comment]
Got it, thanks!

**Comment by switit** [comment]
You can get the 64 bit compare plugin here and manually install it: https://github.com/pnedev/compare-plugin/releases/tag/v2.0.0

**Comment by agabrys** [comment]
Plugin Manager is available: https://github.com/bruderstein/nppPluginManager/releases

**Comment by ginosian** [comment]
they are not in 32 either, right now download 32bit installer, install, no plugin manager.

**Comment by UnicornBeards** [comment]
Installed 32bit here, no plugin manager for me either.  Using version 7.5.

**Comment by UnicornBeards** [comment]
FYI -- I uninstalled 7.5, went to 7.3 32bit and plugin manager was there.  Updated to 7.4.2 and was still ok.  Maybe was removed with 7.5 version??  Didn't see anything in new feature and bug-fixes list, but 7.3 and 7.4.2 for 32 bit work fine.  Will stick with this for now.

**Comment by dail8859** [comment]
As of Notepad++ v7.5 the Plugin Manager is no long being shipped with Notepad++. See https://notepad-plus-plus.org/news/notepad-7.5-released.html

All Plugin Manager related issues should be reported to https://github.com/bruderstein/nppPluginManager/issues

**Comment by evildog1** [comment]
^ removing feature like Google

**Comment by UnicornBeards** [comment]
But y tho??

This was a good feature, easy to use, easy to install a plugin.

**Comment by yesman85** [comment]
Why was this decision made? Notepad++ power IS the plugins that is comes with.

**Comment by NigelWhatling** [comment]
Agree with @yesman85. Would have been more helpful to continue with the existing manager until a replacement was available.

**Comment by sanjmishra** [comment]
Despite the fact that it is developed by an independent developer it can still be bundled in the installer. If the developer has time constrain we can contribute to help speed it up. It is a useful feature for uninitiated. Don't expect every user of notepad++ be a programmer.

**Comment by shaunjstokes** [comment]
Missing 'Plugin Manager' has been causing me problems for the last few days, glad I finally found this article, will be downgrading to a previous version.

The 'Plugin Manager' is a great tool, wouldn't use Notepad++ with-out it.

**Comment by mevsme** [comment]
came here because of plugin manager issue. Going to downgrade.

**Comment by genbish** [comment]
Downgrading too. Need plugin manager

**Comment by Turbine1991** [comment]
This is perhaps the worst design decision I've seen, next to Opera removing bookmarks due to design choice (added back in), Sumatra PDF removing themes (night mode).

**Comment by evildog1** [comment]
...Google removed Character Encoding from Chrome, Google removed night mode from Android OS, Google removed apps section from Play Store, Tunein removed ability to get song title from custom url (now required AirAPI), Microsoft removed Start button from Windows 8 (added back in 8.1)...

**Comment by CaptaPraelium** [comment]
The ads always concerned me. Gave the whole app a suspicious appearance. I look forward to the built-in version.

**Comment by chetanm11** [comment]
1. I went to : https://github.com/bruderstein/nppPluginManager/releases 
2. Downloaded the 64bit release PluginManager_v1.4.9_x64.zip
3. Stopped Notepad++
4. Opened the zip file and then copied the "PluginManager.dll" file to "C:\Program Files\Notepad++\plugins"
5. Then copied the "gpup" application to "C:\Program Files\Notepad++\updater"
6. Started Notepad++ up.
7. Got the Plugins to come up.
![image](https://user-images.githubusercontent.com/33566937/32687621-ab5b4d7e-c6e6-11e7-86a4-eaf5651c2dd8.png)
8. Installed XML plugin

**Comment by fchapman42** [comment]
@chetanm11 - thanks. Your instructions worked perfectly.

**Comment by gameangel147** [comment]
Just wanted to mention that the Plugin Manager doesn't seem to be compatible with V7.5.6.  It could not load it and asked me to remove it.

**Comment by fatcerberus** [comment]
If "Thanks to these people for hosting us" counts as an ad then your threshold for ads is pretty low.  Seems just like common courtesy to me.  I hate ads as much as the next guy but something like this is hardly an issue.  The lack of a plugin manager in the default distribution *is*, however.

**Comment by Uristocles** [comment]
Without an official built-in plugin manager we can still do things manually right? Is this the right place to be: http://docs.notepad-plus-plus.org/index.php/Plugin_Central

**Comment by jeffjensen** [comment]
The plugin manager is also a plugin, so manually install it and then it
works as usual: https://github.com/bruderstein/nppPluginManager

**Comment by Uristocles** [comment]
@jeffjensen Thx for the tip! (Still troubleshooting but it seems with n++ 32-bit installed it thinks the plugin manager dll is a 64-bit thing and kills it... and with n++ 64 installed, it thinks the plugin is a 32-bit thing and kills it haha.)

**Comment by jeffjensen** [comment]
Hmmm, I've not had any problems with it; I'm running v7.5.6 64bit.

I wonder if there are installation remnants affecting each one?  Perhaps use something like "Bulk Crap Uninstaller" to uninstall and remove all remnants and then install 64bit and the plugin?

**Comment by mcbsys** [comment]
Note that the plugins folder has moved to %localappdata%\Notepad++ as of 7.6:

https://notepad-plus-plus.org/news/notepad-7.6-released.html

**Comment by martinRocks** [comment]
I just updated to notepad++ 7.6 and all my plugins are not there.  In fact, the menu isn't there.  I have followed the instructions from chetanm11 of downloading the zip from https://github.com/bruderstein/nppPluginManager/releases and coping the files to %localappdata%\Notepad++\plugins and C:\Program Files\Notepad++\updater.  Still no plugins.  What am I missing?  

By the way, I was using the 32bit version when I did the update.  I have uninstalled the 32bit version when things didn't work.  I now have the 64bit version on my box.

**Comment by mcbsys** [comment]
You are missing my comment directly above yours.

**Comment by chcg** [comment]
With N++ 7.6 the replacement PluginAdmin is available see https://notepad-plus-plus.org/news/notepad-7.6-released.html

**Comment by thctlo** [comment]
👎  my 7.5.x was updated to 7.6, no plugins anymore. 
If i start notepad ++ as administrator is shows the plugin tab

**Comment by Purecoder** [comment]
> 
> 
> I had the same problem and did the following. It worked for me.
> 
>     1. I went to : https://github.com/bruderstein/nppPluginManager/releases
> 
>     2. Downloaded the 64bit release PluginManager_v1.4.9_x64.zip
> 
>     3. Stopped Notepad++
> 
>     4. Opened the zip file and then copied the "PluginManager.dll" file to "C:\Program Files\Notepad++\plugins"
> 
>     5. Then copied the "gpup" application to "C:\Program Files\Notepad++\updater"
> 
>     6. Started Notepad++ up.
> 
>     7. Got the Plugin Manager to come up.
>        ![image](https://user-images.githubusercontent.com/33566937/32687621-ab5b4d7e-c6e6-11e7-86a4-eaf5651c2dd8.png)
> 
>     8. Installed XML Tools plugin

Finally work ! thanks
