### ISSUE TITLE
HTTP links get high lighted, but context menu has no "copy link" option

### ISSUE THREAD

**Issue by ronww** [notepad-plus-plus/notepad-plus-plus#2435]
In a file with HTTP links, the text of the link is high lighted, but the context menu does not have a "copy link" action.
### Steps to Reproduce the Issue
1. Create a file and enter some sample text.
2. Include the text: http://example.com/file.html
3. Click else where in file
4. Hover mouse cursor over link text
5. Observe link text being high lighted
6. Right click on link text to get context menu
   7/ Observer there is no "copy link" option
### Expected Behavior

that the context menu would have a "copy link" option
### Actual Behavior

there was no "copy link" option
### Debug Information

Notepad++ v6.9.2
Build time : May 18 2016 - 00:34:05
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : ON
Local Conf mode : OFF
OS : Windows 7
Plugins : mimeTools.dll NppConverter.dll NppExport.dll NppFTP.dll NppTextFX.dll PluginManager.dll RunMe.dll XMLTools.dll

**Comment by MAPJe71** [comment]
The highlight of the links might just indicate that you have `Clickable Link Settings` enabled.
Double click on a link and the applicable page is opened in your default browser.

To copy the link: select the link text (left-mouse-down just before left most character of link text, drag mouse to right side of right most character in link text, let go of mouse button) and use Ctrl+C or context-menu's copy.

**Comment by ronww** [comment]
Thanks for your reply.

Yes, I know that, but "copy link" in the context menu is an increasingly
common feature. NP++ Seems to have the link recognition part working, so
makes sense to make the feature fully functional.

**Comment by Mxywes** [comment]
Any updates on this feature? Or is it possible to implement it as a plugin?

**Comment by KarenArzumanyan** [comment]
Good suggestion. I also need to copy the link. From the context menu it would be very good.

**Comment by RyouMisaki** [comment]
I also try everytime to find "copy url/link" option on links, since I mostly use private tabs on the browser, please add "copy link" option to context menu, it would be great value added

**Comment by sasumner** [comment]
@Uhf7 What do you think? You are the hyperlinks guru at the moment. :-)

**Comment by Uhf7** [comment]
@sasumner, it's a wish which I would share.

There are two ways:
- An extra entry in the context menu, which is only visible if there is a link under the cursor.
- Replace the "Copy" entry of the context menu with a "Copy Link" entry, if there is no selection active and there is a link under the cursor. (Without link under the cursor, it is grayed out anyway)

The code for this would have to be included in `ContextMenu::create`, which would get an additional parameter, telling it whether the cursor is over a link right now.
