### ISSUE TITLE
Crash on exit with versions 7.0 and 7.1 when CustomizeToolbar Plugin enabled

### ISSUE THREAD

**Issue by Gitoffthelawn** [notepad-plus-plus/notepad-plus-plus#2437]
### Description of the Issue
When exiting Npp v7.0 and v7.1, Npp will often crash.

This happens when the CustomizeToolbar Plugin is enabled.

The crash appears random: Sometimes launching and then closing Npp will work as expected; other times it will crash when closing.

### Steps to Reproduce the Issue
1. Copy Npp v7.1 from the 7z archive.
2. Copy the customizetoolbar.dll plugin to the appropriate directory.
3. Launch Npp.
4. Close Npp (no editing or opening files is required to elicit the crash).

### Expected Behavior
Exit Npp without crash.

### Actual Behavior
*Npp sometimes crashes with the following error:*
Problem signature:
  Problem Event Name:	BEX
  Application Name:	notepad++.exe
  Application Version:	7.1.0.0
  Application Timestamp:	5802a067
  Fault Module Name:	CustomizeToolbar.dll_unloaded
  Fault Module Version:	0.0.0.0
  Fault Module Timestamp:	569a5c06
  Exception Offset:	60862e78
  Exception Code:	c0000005
  Exception Data:	00000008

### Debug Information
Notepad++ v7.1   (32-bit)
Build time : Oct 15 2016 - 23:30:30
Path : C:\editor_test\notepad++.exe
Admin mode : OFF
Local Conf mode : ON
OS : Windows 7
Plugins : CustomizeToolbar.dll HexEditor.dll mimeTools.dll NppConverter.dll NppExport.dll NPPJSONViewer.dll PluginManager.dll TopMostU.dll

**Comment by dail8859** [comment]
Since that is from a 3rd party you need to report this to the developer of the Customize Toolbar plugin.

**Comment by cmeriaux** [comment]
I aslo have this plugin and I don't confirm your issue.

**Comment by Gitoffthelawn** [comment]
Just an added data point: Never had a crash with Notepad++ or CustomizeToolbar plugin until Notepad++ version 7.0 (and now 7.1).

**Comment by Gitoffthelawn** [comment]
BTW, what do you think about adding the ability to customize the toolbar natively in Notepad++?

It makes the GUI *much* more flexible.

**Comment by dail8859** [comment]
The way I see it is that it is completely functional as a stand-alone plugin, and there would really be no added benefit to having it natively supported (plus it would add more functionality that falls under the Notepad++ project to maintain).

Since the original bug report was related to a 3rd party plugin I'll go ahead and close this. Hope you get your issue resolved.

**Comment by Gitoffthelawn** [comment]
Benefits of having it natively supported:

- Does not require downloading a separate plugin, so would have the functionality out of the box.
- Fixing bugs like this would be easier since it would be the native code that is crashing instead of the interaction between a plugin and the native code.
- Larger audience = more testing in day-to-day situations.

Either way, I respect your decision.
