### ISSUE TITLE
Support of forward slashes as path separators

### ISSUE THREAD

**Issue by ghost** [notepad-plus-plus/notepad-plus-plus#2438]
### Description of the Issue

Support of unix path separator "/" in addition to windows back slash "\"
### Steps to Reproduce the Issue
1.  I pasted the following path into the "open file" => "filename" window: "C:/liferay/portal-setup-wizard.properties". 
2. Got the error message "filename is not valid" (my translation as I am using a german version)
### Expected Behavior

Opening the file from "C:\liferay\portal-setup-wizard.properties"
### Actual Behavior

Popup with error message (see above)
### Debug Information

Notepad++ v6.9.2
Build time : May 18 2016 - 00:34:05
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 7
Plugins : Explorer.dll HTMLTag_unicode.dll mimeTools.dll NppConverter.dll NppExport.dll NppFTP.dll NppTextFX.dll PluginManager.dll XMLTools.dll

**Comment by MojaveWastelander** [comment]
The issue is not with N++ but with Windows default open file/directory dialog that does not support forward slashes (while Windows in general support them). Is need to make an user-defined open file dialog that would parse slashes properly.

**Comment by ihnorton** [comment]
> Windows default open file/directory dialog that does not support forward slashes

At least on Win10/MSVC2015, it works fine when `OFN_NOVALIDATE` is set (see https://msdn.microsoft.com/en-us/library/windows/desktop/ms646839(v=vs.85).aspx). Then the validation must be done by the client.
