### ISSUE TITLE
Non-interactive uninstall doesn't work in version 7.1

### ISSUE THREAD

**Issue by alt36** [notepad-plus-plus/notepad-plus-plus#2439]
Up to version 7, it was possible to uninstall notepad++ totally silently/non-interactively by running "uninstall.exe /S" . As of 7.1, even with the /S flag the uninstaller prompts "Would you like to keep your custom settings?", which prevents running a non-interactive uninstallation.

**Comment by dail8859** [comment]
Closed by c58043ea0d71c1a7c9403a2f85eba8251c64b4d0
