### ISSUE TITLE
Arrow keys don't record

### ISSUE THREAD

**Issue by code-daemon** [notepad-plus-plus/notepad-plus-plus#244]
When trying to record a macro the arrow keys don't appear to get recorded.

To reproduce....
Have multiple line document.
(Record Macro)
Add text to start of line, move to next line
(Stop recording macro)
Reply macro and find it doesn't move the cursor.

Input:
A
B
C

Expected
1 A
1 B
1 C

Actual:
1 A
1 1 B
C

**Comment by sampalmer** [comment]
I couldn't reproduce this in Notepad++ 7.2 on Windows 10. Is this still an issue? What exactly did you press to record the "move to next line"? Down + Home?
