### ISSUE TITLE
Not updating registery when upgrading 32bit to 64bit

### ISSUE THREAD

**Issue by tknight0000** [notepad-plus-plus/notepad-plus-plus#2440]
Upgrading from the v6.x.x 32bit version to the v7.1 64bit version, via "Notepad++ Installer 64-bit x64", does not update the registry key in "Computer\HKEY_CLASSES_ROOT\Applications\notepad++.exe\shell\open\command". Which can be tricky to diagnose. As file associations just break and the bad registry reference prevents the application from being added to "Open With" window again.

**Previous Value**:
"C:\Program Files (x86)\Notepadd++\notepad++.exe" "%1"

![registry](https://cloud.githubusercontent.com/assets/22911684/19477157/c6718808-950a-11e6-8986-6546fd75edb1.jpg)

**New Needed Value**:
"C:\Program Files\Notepadd++\notepad++.exe" "%1"

My machine is Windows7 64bit (with windows updates on)

**Comment by alexfeigin** [comment]
I also had to fix similar an issue on my pc, in my case I found the bad entry for each users-id at:
HKEY_USERS\<user-id>\Software\Classes\Applications\notepad++.exe\shell\open\command
same behavior on win 7 - bad entry keeps me from re-adding notepad++ as an application to handle file extension association 
I understand from [this](https://msdn.microsoft.com/en-us/library/windows/desktop/ms724475(v=vs.85).aspx) that HKEY_CLASSES_ROOT is just a view over user/machine keys - so a fix might need to be on each user and not classes_root

**Comment by MetaChuh** [comment]
please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins if you update from version 7.5.9 or below.
if your issue still persists, and it is still of relevance, please feel free to file a new issue as easy to understand and reproducible as possible.

thank you for your help and best regards.
