### ISSUE TITLE
Translate "Edit with Notepad++" in Windows context menu

### ISSUE THREAD

**Issue by scootergrisen** [notepad-plus-plus/notepad-plus-plus#2444]
I would like the Notepad++ strings in Windows context menu and properly other places like start menu to be translateable.

If i right click a icon i see "Edit with Notepad++" in the context menu.

I would like to be able to translate that to my language for a more complete translation.

**Comment by scootergrisen** [comment]
The string seem to be here:
https://github.com/notepad-plus-plus/notepad-plus-plus/blob/51797bf59e689b11d80998758790f8a4cade68eb/PowerEditor/src/tools/NppShell/src/NppShell.cpp#L23

Perhaps better to call it "Open with..." instead of edit. like Windows writes it.
And you might just want to see the file without editing it.

**Comment by mbc07** [comment]
I was going to open a new feature request asking for exactly the same. Any update on this? I might be wrong but it seems trivial...

**Comment by t32768** [comment]
[http://docs.notepad-plus-plus.org/index.php/Explorer_Context_Menu](url)
Just replace the NppShell.dll with its exact name (in my case it was NppShell_06.dll)

**Comment by Tmp341** [comment]
> 
> 
> [http://docs.notepad-plus-plus.org/index.php/Explorer_Context_Menu](http://docs.notepad-plus-plus.org/index.php/Explorer_Context_Menu)
> Just replace the NppShell.dll with its exact name (in my case it was NppShell_06.dll)

You need to open CMD with admin rights of course.

**Comment by MetaChuh** [comment]
@scootergrisen 

usually the explorer context menu entry `Edit with Notepad++` is translated to the installer language you used, while installing notepad++.

if you wish to change the text to a localised translation you have the following options:

**1) re-install notepad++ and select a different installer language.**

-----

**2) context menu customisation via NppShell_06.dll:**
   * press the windows button and type `cmd` to search for cmd.exe.
   * run cmd.exe as administrator, as seen at the screenshot below:
   <img width="480" alt="" src="https://user-images.githubusercontent.com/45773305/56473820-118c4c00-6471-11e9-8dd2-7e7e8f48ab80.png">

   * change to your notepad++ folder, depending on your installed notepad++ location and architecture.
examples: `cd %ProgramFiles%\Notepad++` or `cd %ProgramFiles(x86)%\Notepad++`
   * enter `regsvr32 /i NppShell_06.dll` and edit `Menu Text` from `Edit with &Notepad++` to anything you like, as seen at the screenshot below:
   <img width="480" alt="" src="https://user-images.githubusercontent.com/45773305/56473841-852e5900-6471-11e9-9eb8-9ed011527ae8.png">

   * press <kbd>ok</kbd> and reboot.

-----

**3) editing your registry:**
   * run regedit and change the reg_sz string at
`HKEY_CLASSES_ROOT\CLSID\{B298D29A-A6ED-11DE-BA8C-A68E55D89593}\Settings\Title`
from `Edit with &Notepad++` to anything you like.

-----

thank you for your help and best regards.

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
(no extra account is needed, just use your github account to sign in)
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)

**Comment by mbc07** [comment]
Why the issue was closed? It's **not** fixed.

> usually the explorer context menu entry Edit with Notepad++ is translated to the installer language you used, while installing notepad++

Then the installer is bugged. I'm a long-time user of Notepad++ and the context menu entry is **always** in English, even if I select other language on the installer's initial prompt and have chosen to the full Notepad++ package. 

For now I workaround this by editing the registry key with a localized string manually, but the issue exists regardless and should be reopened until a proper fix is made.

**Comment by t32768** [comment]
I'm a Czech, and the installer doesn't offer Czech language at start.

Did you try the `regsvr32 /i NppShell_06.dll` route, of course running CMD as Administrator?
Working for me for ages, on every install I did (and there were lots).

**Comment by scootergrisen** [comment]
The installer is not translatable and according to https://github.com/notepad-plus-plus/notepad-plus-plus/issues/1873 will not be made translatable sadly.

Is the string common string "Edit with" or "Open with" perhaps already translated by the system or libraries used by Notepad++ or others stuff so that we can reuse translations since it is a common string used by many software.
Just like strings for common buttons like OK and Cancel might already be translated.

If the string "Edit with &Notepad++" is not translated then it would not matter when language is selected during installation.

Thanks for the regsvr32 /i NppShell_06.dll info but i am looking to improve the translations for all users not just on my system.

**Comment by scootergrisen** [comment]
> I'm a Czech, and the installer doesn't offer Czech language at start.

Is it not Čeština?

**Comment by mbc07** [comment]
> Did you try the regsvr32 /i NppShell_06.dll route, of course running CMD as Administrator?
Working for me for ages, on every install I did (and there were lots).

You're missing the point, I'm aware of other ways to translate the context menu entry (in fact I have a simple .reg file that I import manually whenever I update to a new version and it gets the job done), the issue is that Notepad++ should handle this automatically in some way, either directly on the installer or perhaps by embedding the translated strings on the ShellExt DLL and make Windows inherit the appropriate string by itself like a lot of other programs with multi-language support does...

**Comment by t32768** [comment]
> Is it not Čeština?
Yeah, indeed it is :-) My bad, I just thought about a different program with a similar problem.

Yes... and even if the whole installer runs in Czech, on Czech-only W10, and after install everything is perfectly Czech... the context menu is still in English

But the regsvr32 thing does really work for me:

![2019-04-21 20_47_50-](https://user-images.githubusercontent.com/49840411/56474216-0a683c80-6477-11e9-83ba-f089292e0227.png)
![2019-04-21 20_37_39-Window](https://user-images.githubusercontent.com/49840411/56474219-0e945a00-6477-11e9-89ea-4db350f73b16.png)
