### ISSUE TITLE
Installer: selecting minimalist and then user defined deselect everything

### ISSUE THREAD

**Issue by scootergrisen** [notepad-plus-plus/notepad-plus-plus#2445]
If i run the Notepad++ installer and select minimalist and then select user defined everything is deselected.

Perhaps add "Standard" option to the installer like in many other installers.

**Comment by MetaChuh** [comment]
@scootergrisen 

as users only have to set the installer preferences once, and all installer settings will be remembered for every update, there is currently no need for an installer change.

thank you for your help and best regards.
