### ISSUE TITLE
C++ keywords update request

### ISSUE THREAD

**Issue by pnedev** [notepad-plus-plus/notepad-plus-plus#2449]
Please make C++ _**nullptr**_ recognized as a keyword by the lexer (same as NULL perhaps?).
Thanks.

**Comment by dail8859** [comment]
It works fine for me. It is in the `langs.model.xml` file on [this line](https://github.com/notepad-plus-plus/notepad-plus-plus/blob/master/PowerEditor/src/langs.model.xml#L64)

**Comment by pnedev** [comment]
Hm, it is present in my _langs.model.xml_ also but it doesn't get highlighted.
I'll check on native Windows when I get the chance and write back.
Thanks.

**Comment by dail8859** [comment]
What about in your `langs.xml`? :)

**Comment by pnedev** [comment]
Right, got it! :)
You are right, it is working fine, thanks.
