### ISSUE TITLE
Explorer plugin makes Notepad++ slow

### ISSUE THREAD

**Issue by scootergrisen** [notepad-plus-plus/notepad-plus-plus#245]
I noticed that Notepad++ is much slower to startup and quit when the explorer plugin is open.

Example with a lot of files open:

Open Notepad++ with explorer plugin open : 30 seconds.
Open Notepad++ with explorer plugin closed : 10 seconds.

Quit Notepad++ with explorer plugin open : 30 seconds.
Quit Notepad++ with explorer plugin closed : 4 seconds.

I'm using Notepad++ 6.7.8 and Explorer 1.8.2.

**Comment by cmeriaux** [comment]
Hello,
do you have other application that could cause this slower startup ? As an example, Tortoise Git ou tortoise SVN can be invoked by the explorer shell to add icon status of your repository. In some configuration, tortoise can scan the complete repository shown in the explorer.
It 's just an idea

**Comment by scootergrisen** [comment]
I tried closing other programs, but its the same.

**Comment by cmeriaux** [comment]
even if you close tortoise program, they are automatically invoked by the shell explorer

**Comment by scootergrisen** [comment]
I dont have tortoise installed.
How would i know if any program would cause the problem?

**Comment by cmeriaux** [comment]
You can try Process Explorer ( https://technet.microsoft.com/en-us/sysinternals/bb896653.aspx ) and look at notepad++ properties, and look for threads that are executing. I could lead you to a clue
Sorry, I don't have other idea

**Comment by Tmp341** [comment]
I suppose your OS is Windows. Then, try Process explorer or process hacker. You can inspect your working applications or svchost.exe for example, with a better view (like connected with which services etc).

**Comment by scootergrisen** [comment]
I got 3 ntdll.dll!TpCallbackIndependent+0x238

If i have explorer plugin installed in the plugin folder i also got this one:
ntdll.dll!RtMoveMemort+0x5a5
And 3 of these:
Explorer.dll!beNotified+0x[number]

Notepad++.exe is the only one using up all the CPU resources on one core for as long as the program is trying to start or quit.

**Comment by ariccio** [comment]
Try [UIforETW](https://randomascii.wordpress.com/2015/04/14/uiforetw-windows-performance-made-easier/), along with...

**Comment by ariccio** [comment]
[manual wait analysis](https://randomascii.wordpress.com/2012/05/05/xperf-wait-analysisfinding-idle-time/)

**Comment by ariccio** [comment]
Did you get a chance to profile it?

**Comment by scootergrisen** [comment]
Not yet.

**Comment by dail8859** [comment]
Closing since this is for a 3rd party plugin.

**Comment by scootergrisen** [comment]
I have written to Jens Lorenz about it found on http://docs.notepad-plus-plus.org/index.php?title=Plugin_Central#E so maybe that person knows how to fix it.
