### ISSUE TITLE
.SQL file loses syntax highlighting if the three characters '\' are on a line

### ISSUE THREAD

**Issue by chrisgoldsmith** [notepad-plus-plus/notepad-plus-plus#2451]
Description.
Syntax highlighting on .sql files lose syntax highlight if the characters '\' are included

1. open a new .sql file
2. type some valid .sql
3. type '\'
4. syntax highlighting is lost
5. replace '\' with ':'
6. syntax highlighting returns

See screen shots
![bug2](https://cloud.githubusercontent.com/assets/22960017/19562903/0b29577e-96d6-11e6-9fed-951395df7366.JPG)
![bug1](https://cloud.githubusercontent.com/assets/22960017/19562904/0b2c96b4-96d6-11e6-8c84-f6727d68d778.JPG)

Expected Behavior
Syntax highlighting always remains

Actual Behavior
Syntax highlighting is lost

Debug info:
Notepad++ v6.9.2
Build time : May 18 2016 - 00:34:05
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : ON
Local Conf mode : OFF
OS : Windows 7
Plugins : mimeTools.dll NppConverter.dll NppExport.dll PluginManager.dll

**Comment by dail8859** [comment]
`Settings > Preferences > MISC > Treat backslash as escape characters for SQL`

**Comment by chrisgoldsmith** [comment]
thanks
