### ISSUE TITLE
Ctrl+V should not paste if clipboard does not contain text

### ISSUE THREAD

**Issue by Yaron10** [notepad-plus-plus/notepad-plus-plus#2452]
STR:
Copy an image to the clipboard (or clear the clipboard).
Select a word in NPP (the Paste command is disabled).
Press Ctrl+V.

Result:
NPP deletes the selection.

Expected result:
Standard behavior: ignore the action.

**Comment by SinghRajenM** [comment]
This issue occurs with every file type. Also if folder is copied on clipboard.

_Looks like if item from clipboard is not paste-able, then scintilla replaces with empty string or may be NULL which is considered as empty string. Sorry, I didn't debug the issue, it is just thought._

**Comment by Yaron10** [comment]
@SinghRajenM,
Thanks.

**Comment by MetaChuh** [comment]
unfortunately this still depends on scintilla.

many thanks and best regards.
