### ISSUE TITLE
[REQUEST] Exclude Filters in 'Find in Files'

### ISSUE THREAD

**Issue by circa84** [notepad-plus-plus/notepad-plus-plus#2453]
### Description of the Issue

In the 'Find in Files' Feature, it would be extremely useful to have an exclude Filter instead of just an include filter.  
### Steps to Reproduce the Issue

For example, I'm using an expression to find all guids in my development project to make sure we aren't overriding data in some instances.  However, the search is pulling data from everything including DLLs.  Although I know most of the instances will be in .cs files, it would be nice to just slowly take out types like *.dll and still see the GUIDs in config files etc.
1. 
2. 
3. 
### Expected Behavior

Search all files that are not in the excluded filter list.  Works the same as the Filters area, but have the exclude just below.
### Debug Information

Here are some other people looking for the same, not much on google to fix this.

http://superuser.com/questions/313300/advanced-usage-of-notepad-find-in-files-filter
http://superuser.com/questions/112548/notepad-excluding-find-filters

**Comment by bahusoid** [comment]
Added pull request #2501

**Comment by MetaChuh** [comment]
the find in files function serves its basic purposes, for being a small goodie inside notepad++.

we will not integrate features that are handled much better using specifically designed applications for that task.

you can e.g. use the free utility [FileSeek](https://www.fileseek.ca/Download/).
it has notepad++ integration and a lot of include/exclude, date and regex functions. much more than can ever be integrated into notepad++.

many thanks and best regards.
