### ISSUE TITLE
Regression in Windows installer for Notepad++ 7.1 : option to use old icon is missing

### ISSUE THREAD

**Issue by Zsar** [notepad-plus-plus/notepad-plus-plus#2456]
### Description of the Issue

Notepad++ 7.1 x64 installer for Windows [from here](https://notepad-plus-plus.org/download/v7.1.html)
Windows 10 Professional x64

On the fifth page of the installer window there ought to be four options in order:
1. Don't use %AppData% [...]
2. Allow plugins to be loaded from %AppData%\\notepad++\\plugins [...]
3. Create Shortcut on Desktop
4. Use the old, obsolete and monstrous icon [...]
Verified using installers for Notepad++ 6.4.5 and 6.9.2. In the installer for version 7.1 the fourth option is absent.

Reproducing the lost feature is not trivial, as the icon is stored in notepad++.exe, but only the selected option; e.g. in a fresh installation of Notepad++ 6.4.5 the file notepad++.exe contains _only_ the old icon if installed with option 4), or _only_ the new icon if without. Likewise, in a fresh installation of Notepad++ 7.1 the file contains _only_ the new icon.

Providing the icon in a seperate file (e.g. the copied and renamed old 6.4.5 executable) still requires use of registry hacks to have the icon be used in the context menu entry "Edit with Notepad++" and on files set to be opened with Notepad++ by default.

### Steps to Reproduce the Issue

1. Start installer.
2. Press Continue, Accept, Continue, Continue.
3. Count the available options and compare with earlier installers.

### Expected Behavior

Four options as previous, the last one being to use the old icon.

### Actual Behavior

Only the first three options are present. Post-installation, there is no way to use the old icon without resorting to hacks.
![installer7 1](https://cloud.githubusercontent.com/assets/9061998/19575684/363170de-9710-11e6-91bb-0f25a4ac3086.png)
![installer6 4 5](https://cloud.githubusercontent.com/assets/9061998/19575686/36489fd4-9710-11e6-89f0-feb629cb3dbf.png)

### Note
The terminology "old" and "new" may be misleading (compare e.g. [this thread](https://notepad-plus-plus.org/community/topic/10784/i-want-my-old-icon-back/8), where these terms seem to be used in inverse). The desired icon is *not green* and only uses a pleasantly bleak tone of yellow for its sole chromatic component. A _newer_ "new" icon with similarly pleasant look would make this feature obsolete - but of course then people would likely demand the option to return to the colourful green icon, because colour perception and sense of aesthetics are fundamentally individual values.

The Status Quo disturbed by this issue, which provided a choice between two rather different appearances was certainly a superior solution.

**Comment by MAPJe71** [comment]
It is not a regression, the author decided to have the icon removed and as a result the option in the installer is removed.
If you really want the obsolete icon in your environment there are other ways. Beside the registry "hacks" you already mentioned there are ways to patch the executable e.g. with tools like [ResourceHacker](http://www.angusj.com/resourcehacker/), [ResEdit](http://www.resedit.net/) and [Anolis Resourcer](https://anolis.codeplex.com/).

**Comment by Zsar** [comment]
Regrettable. But thank you for the hints.

**Comment by andyrwebman** [comment]
This is, I'm afraid, a poor choice by the author.

The new icon is incredibly indistinct. Whenever I went to another developer's desktop, I couldn't find notepad++. Now I'm finding it difficult to find the open window on my own.

Call me old fashioned, but a program should look like what it is. If I want a colour changing program, a chameleon icon is appropriate. If I want a text editor, a white notepad works for me.

**Comment by metal450** [comment]
Yikes - this is a major regression in my opinion too.  Just installed npp v7 on a new PC, and am very disappointed to find that the text editor can no longer have an icon that looks like that of a text editor.

Guess I'll revert to 6.9.2 if or until the icon is "fixed" (hopefully the author will reconsider...)

**Comment by MAPJe71** [comment]
Just for anyone who reads this topic and is wondering what the whining is all about ... old vs. new in the sizes 48x48, 32x32 and 16x16, all in True Color + Alpha channel (32 bits).

Old image | New image
--- | ---
![Notepad++ "Old"](https://cloud.githubusercontent.com/assets/6494038/20425675/e7326934-ad7b-11e6-8871-16807770ac59.png) | ![Notepad++](https://cloud.githubusercontent.com/assets/6494038/20425676/e7345ea6-ad7b-11e6-950d-331f47ed0057.png)

**Comment by Y-Less** [comment]
I just got the alert box to update my installation, so was doing so when I got to that same screen and had to cancel the install.  Came here to report the same thing.

**Comment by kevinkjt2000** [comment]
He said he wouldn't blame us for wanting the old icon back :(

**Comment by metal450** [comment]
Please follow up if this ever ends up getting fixed; I really would love to be able to use the current version of this software again.

**Comment by thunderbirdmoz** [comment]
Just adding my voice here that I prefer the old images too. When scrolling through thousands of different files in windows explorer I find the old images are easiler to tell apart than the new ones. I dont mind the 48x48 image with the chamelion but the old 16x16 is much more distinctive than the new 16x16 one.

**Comment by Y-Less** [comment]
Had to reinstall Windows and thus Notepad++ today, reminded of this again so bumping it.

**Comment by kevinkjt2000** [comment]
I had a conversation about this icon being removed from the installer again today.  It seems people really do prefer to keep the old icon.  Please fix this revert to previous behavior and allow the choice again.

**Comment by tushev** [comment]
+1. Please return the old icon.

**Comment by bloodev** [comment]
An old discussion, but is there any update on this? The new icon is so bad...

**Comment by andrewbranoff** [comment]
A horrible decision to remove the option - the Notepad++ chameleon is a monstrosity of graphic design... So much so people are resorting to hacking their registry to get around being forced to use it. This is made even worse by the fact that n++ uses the same icon for all file types registered to it, so a .cpp file and a .txt file look the same when registered to Notepad++!

**Comment by cihansol** [comment]
I prefer the old icon too!

**Comment by avengerx** [comment]
Why is it just me who thinks the old, obsolete and monstrous icon is this:
![image](https://user-images.githubusercontent.com/808610/176968248-1b255433-2cd4-4bc1-a533-279ba059cced.png)

I have downloaded the [PNG from wikipedia](https://www.tech-wiki.net/index.php?title=File:Notepad%2B%2B_logo.png), cropped it around to 512x512, and cropped parts of the pencil to make it a bit bigger, and transformed it into an icon using a "redketchup"'s icon converter online.

Then I needed to set up the icon to display in taskbar:
- open NPP's installation directory `c:\Program Files\Notepad++`
- create a shortcut for itself (`notepad++.exe`), you may need to create the shortcut somewhere else and copy it back to the directory due to admin perms required
- copy the icon file over the installation directory
- right click the shortcut, choose _change icon_ and select that icon file
- open and pin Notepad++ via this shortcut.

I hope that once I open it via assigned extensions/context menu, it would retain the shortcut and icons, or else I'll have to work a little more on that... :(

I'm sharing the icon I generated here shall anybody feel, like me, getting the "old, monstrous" icon back to npp.
[npp_logo.ico](https://www.dropbox.com/s/mngl5vhuovgp5xb/npp_logo.ico)

**Comment by metal450** [comment]
I gave up on updating this app. 6 years later, still using the old version from 2016, as the author seems inexplicably bent on forcing a weird, ugly lizard on all of his users, despite their obvious preference to the contrary.

**Comment by avengerx** [comment]
figures... I went out of my way to bring the chameleon _back_ as its desktop taskbar icon.

I could never link a paper sheet and a pencil to NPP, be it gray or green. 🤣

I think the ugly lizard (without paper, but perhaps the pencil) was the main icon in the first iterations of npp. So my guess is that they wanted to _force back_ the monstrous little funny green chamo.

**Comment by FyiurAmron** [comment]
> weird, ugly lizard

you know who's actually ugly? XD
