### ISSUE TITLE
File content is replaced by a random letter automatically w'out doing anything

### ISSUE THREAD

**Issue by gadapchetvoi** [notepad-plus-plus/notepad-plus-plus#2457]
This happens to me 10-20 times per day. Suddenly when I'm doing nothing but seeing at notepad++ 7 (windows 7 32bit) all my file content disappears and a random character (m, s, a, etc) appear as the only content of file. 

I can Ctrl+Z once or twice to recover my file content but sometimes it very troublesome.
Please track & fix. Thanks

**Comment by dail8859** [comment]
Please follow the provided template and provide a set of reproduceable steps and your debug information.
