### ISSUE TITLE
Notepad++ add hidden characters to files

### ISSUE THREAD

**Issue by Hokonpitty** [notepad-plus-plus/notepad-plus-plus#2458]
### Description of the Issue

Recently it happened that Notepad ++ added FFFF characters to the text/XML/batch file when I edited them in editor. I always used standard mode not the hex view mode, but finally I observer that in some cases Notepad++ ads extra FFFF to front of the first visible character. It is only visible in hex editors. This bug can be a big problem, because it can harm to a batch or to a xml file very well.

### Steps to Reproduce the Issue

1. 
2. 
3.

**Comment by dail8859** [comment]
Please follow the provided template and provide a set of reproduceable steps and your debug information.
