### ISSUE TITLE
64 bit version is without "Plugin Manager" (and NppExport)

### ISSUE THREAD

**Issue by grosorg** [notepad-plus-plus/notepad-plus-plus#2459]
### Description of the Issue

It is confusing that some options are (missing or) different between 64 and 32 bit.

### Steps to Reproduce the Issue

1.  Download 64 bit v7.1. and install it
2.  Go To Plugins menu.
</br>
Extra:
3. Repeat steps 1-2 for 32 bit v7.1.
4. With Plugin Manager, install TextFX plugin
5. Reinstall 64 bit version.
6. Start Notepad++ and see a message that 32bit TextFX plugin is not supported with 64bit Notepad++
![no32version](https://cloud.githubusercontent.com/assets/22980071/19598702/6f4a7000-979c-11e6-9a90-1571ce0ef513.jpg)

7. Reinstall 32 bit version

### Expected Behavior

Plugins Manager (and NppExport) is available under Plugins menu (so I'm able to install TextFX plugin)

### Actual Behavior

Plugins menu for 64 bit version has only 2 menu options. Converter and MIME Tools - "Plugin Manager" and NppExport is missing. 
Plugins menu for 32 bit version has 4 menu options. With "Plugin Manager" (and NppExport). (So I did install TextFX plugin through that)
![npp21 10_t1347](https://cloud.githubusercontent.com/assets/22980071/19597447/fa5609a0-9794-11e6-9371-304afd9b50f8.jpg)

### Debug Information

Notepad++ v7.1   (64-bit)
Build time : Oct 15 2016 - 23:35:37
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : ON
Local Conf mode : OFF
OS : Windows 7
Plugins : mimeTools.dll NppConverter.dll 

And

Notepad++ v7.1   (32-bit)
Build time : Oct 15 2016 - 23:30:30
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : ON
Local Conf mode : OFF
OS : Windows 7
Plugins : NppTextFX.dll mimeTools.dll NppConverter.dll NppExport.dll PluginManager.dll 

I've reinstalled 64 bit - and it looks like TextFX plugin is in a 32bit version. So I'm not able to use it anyway with v.64bit. So I reinstalled v 32bit again. And can live happy after.
And because I like Npp a lot, I've decided to write an issue.

**Comment by dail8859** [comment]
The Plugin Manager, although incredibly useful, is by a 3rd party developer so it is really up to that project. The Plugin Manager developer is working on 64-bit support however, see bruderstein/nppPluginManager#7

NppExport is also from a 3rd party developer. It hasn't been updated in about 6 years so I doubt it will get 64-bit support any time soon.

**Comment by grosorg** [comment]
Thank you dail8859 for the feedback.
From now on - I'll focus on a 32-bit version.

**Comment by a161803398** [comment]
(Just in case if some one want to use NppExport on 64-bit Notepad++)
I find a 64-bit version NppExport build on GitHub [(Project Link)](https://github.com/chcg/NPP_ExportPlugin)
You can download the binary file [HERE](https://ci.appveyor.com/project/chcg/npp-exportplugin/build/job/l1eku4c71gtrwvh5/artifacts). And then put it into plugins folder.
I have tested it on Notepad++ v7.2 (64-bit), and it works.
![default](https://cloud.githubusercontent.com/assets/7911601/20454938/c88ee58e-ae89-11e6-849e-b83d379c99b8.png)

**Comment by mzvast** [comment]
No plugin manager on 64bit version is quite inconvenient for guys like me who want get things from an official repo.~

**Comment by richdevboston** [comment]
Plugin Manager is really great, and a huge time saver.  No Plugin Manager is a currently big gap for the 64-bit version, since I rely on that to locate and install compatible plugins.  Please hurry with the 64-bit Plugin Manager.   Thank you.

**Comment by MikeCheel** [comment]
Where oh where did the plugin manager go?

**Comment by Reemh** [comment]
I also was surprised that the plugin manager is not there anymore for 64 bit version.

**Comment by CTimmerman** [comment]
Why is this issue closed? 64-bit Npp still doesn't include the PM like the 32-bit version does.

**Comment by dail8859** [comment]
As stated above the Notepad++ developers do not maintain these plugins. They are from **other** developers.

**Comment by CTimmerman** [comment]
I read that, but those developers are not responsible for creating Notepad++'s installer, are they?

**Comment by keyosuke** [comment]
I agree that if a 64-bit plugin manager is available and it's in the 32-bit version of the installer, this shouldn't be closed until it's put in the 64-bit installer.  If that's not possible at this time, there should be guidance on the download page explaining that by opting for 64-bit we're opting out of the experience we've become accustomed to.

**Comment by berndhahnebach** [comment]
I am not involved in any N++ community, but to me it is strange the plug-in manager is included in 32bin and not in 64bit. I was searching and searching for the plug-in manager in 64bit ... It took me an hour to find the simple reason ...  it is not included in 64 bit. 

I just installed 32bit ... 

bernd

**Comment by akousmata** [comment]
Just an FYI that there was a new version of the plugin manager released about a month ago.  Follow the instructions here and it should work for you.  Not all of the plugins are available yet but several of the ones I use (NppFTP and Compare) are available.  [https://notepad-plus-plus.org/community/topic/13661/plugin-manager-x64-available-submit-your-plugins](https://notepad-plus-plus.org/community/topic/13661/plugin-manager-x64-available-submit-your-plugins)

**Comment by eSilverStrike** [comment]
The website does mention on the downloads page that the plugin manger is not included but I missed it as well when I downloaded notepad++ for my new laptop.

I was surprised when I couldn't find it and had to do a google search. 

Maybe the website could be updated to highlight the missing plugins manager or include the new one just released a little while ago. Links should also be included to the list of available plugins for x86 and x64.

**Comment by yadavsachin** [comment]
If you want to use plugin manager with 64bit, you can download it from here

https://github.com/bruderstein/nppPluginManager/releases/tag/v1.4.9

**Comment by sharkoz** [comment]
There is a new open issue for this you can +1 here : #3264

**Comment by MahmoodShehab** [comment]
Another disappointment here, I came to know about this after upgrading notepad++ to 7.4.2 (64-bit)

**Comment by maggenti** [comment]
I might as well join the crowd, please do add it soon, all of us await the asdfasd oh darn where is the spell checker plugin anyway...

**Comment by ErPuneetGoel** [comment]
Solution:

Download the plugin manager zip folder from below link: [Github](https://github.com/bruderstein/nppPluginManager/releases/tag/v1.4.9)

Once downloaded, explore it and copy the files from the plugin folder to your Programming file > notepad++ > plugin folder

Similarly replace the existing GUP.exe or gpup.exe files from update folder as well.

Now I can see plugin manager for 64 bit as well.

**Comment by BrainSlugs83** [comment]
1.) Can you guys please mention that there is no support for the plugin manager in the 64-bit version before we go through the trouble of installing it? (like on the web page would be nice!)

2.) Alternately, if it is now available, (per @ErPuneetGoel above), can you guys please package it up with Notepad++ 64-bit?

**Comment by dail8859** [comment]
@BrainSlugs83 It does say it on the web site.

![capture](https://user-images.githubusercontent.com/3694843/29289454-8725e774-810a-11e7-8817-9eb8e4c90641.PNG)

**Comment by BrainSlugs83** [comment]
Ahh jeez, mea culpa! --  I looked right past that. -- Maybe consider something in bigger and bolder -
 and in bright red. -- Maybe a blink tag. -- As it seriously cripples the editor.

Also, per my second item (above) it appears the statement is incorrect now anyway. -- It's totally available.

**Comment by dail8859** [comment]
As of Notepad++ v7.5 the Plugin Manager is no long being shipped with Notepad++. See https://notepad-plus-plus.org/news/notepad-7.5-released.html

All Plugin Manager related issues should be reported to https://github.com/bruderstein/nppPluginManager/issues

**Comment by keyosuke** [comment]
You guys must really hate having happy customers.  I mean, we spent years using this product and liking it without the hassle of having to get a separate plugin manager, and it coming with one meant a unified plugin platform that was very much more accessible.  The passion with which the public continued to constantly post and complain about not having Plugin Manager distributed with the 64-bit version should have shown you that we rely on this feature as a critical part of the app.  There is competition for this app from things like Sublime Text, and for a time I was torn between which of them I would use, but if you're simplifying your lives by making it harder on the customer by making us download a separate plugin manager, I wouldn't be surprised if this app loses popularity.

Consider this: A person who relies on a plugin manager does so because they do not want the hassle of downloading and installing plugins via their web browser and filesystem.  If you cannot offer some integral plugin management support, and we users need to download and set something up to be able to easily manage plugins, you break expectations users have had since they chose this as their editing tool, years ago, and you condemn us to having to still manage at least one plugin, which is the plugin manager.  That extra overhead will drive away a whole class of your less technical users who aren't using this tool for programming.  Yes, those users exist - for now.

**Comment by billynair** [comment]
Well, I just installed the new 32 version, and, yeah, no Plugin Manager... The only one I could find was from 2011. I installed the 64 and didn't think it would KILL EVERYTHING I had written and tweaked to make it exactly how I wanted it to be (styles, languages, etc (yes, I know, back your $#!+ up, but, I was tired and done for the day, and just didn't want to deal with everything, and usually NPP doesn't do weird stuff and basically, I trusted it more than I should have, and yeah, years of tweaking, GONE, like, not even in the trash, just, POOF! So, they need to have "**Note that the most of plugins (including Plugin Manager) are not yet available in x32 either**"

**Comment by maggenti** [comment]
Wow, Sorry to hear that! Ya, I hardly ever back up NPP either it just works, right? What happened to the good old days when things just worked...

**Comment by stambertt** [comment]
same problem here but i manage to solve it. i just download the old version v7.2.1 and after installing it plugin manager exist again...then it will automatically download the current version. just dont lose hope hehe:)

**Comment by stambertt** [comment]
same problem here but i manage to solve it. i just download the old version v7.2.1 and after installing it plugin manager exist again...then it will automatically download the current version. just dont lose hope hehe:)

**Comment by jawn** [comment]
[This announcement](Useful background info: https://notepad-plus-plus.org/news/notepad-7.5-released.html) explains why the plugin manager is now also removed from the 32-bit version. Summary: It was showing ads.

**Comment by jaradc** [comment]
Removing something for showing ads is a **very good reason to remove it**. But, if that thing is used by many, the communication of its removal should be handled properly and proactively. I followed ErPuneetGoel to install package manager. It worked. I do see a "nexinto" business card link. There's a "Why is this here?" link that goes to [this explanation](https://bruderste.in/npp/pm/sponsor/).

**Comment by andyxxl** [comment]
Dear Gents,

I am really annoyed that plugin manager gone from newer NPP releases. I have tried to copy it manually and restart NPP but outcome is nothing! I am really fed up. Can anybody advise some older 64bit NPP which support plugin manager?I need textFX plugin badly to remove mess from my logfiles. Thanks. Regards

**Comment by MAPJe71** [comment]
@andyxxl TextFX plugin is not available in/for 64 bit.

**Comment by niras-nmr** [comment]
No plugin manager no notepad++; if it wasn't for the plugins i wouldn't use it at all ,,

**Comment by jucie** [comment]
I appreciate the observance of the "no ads" criteria, but I think we must be pragmatic sometimes. For a hugely successful software like Notepad++ bandwidth costs constitute a real problem and somebody must pay for it. ["Why is this here?" page](https://bruderste.in/npp/pm/sponsor/) provides a very good explanation. The software author not only provided for good software, but found a reasonable approach for financing as well. So, congratulations.

After installing the latest 64bit version I downloaded [the plugin manager](https://github.com/bruderstein/nppPluginManager/releases/tag/v1.4.9) and it works great. Thanks for everyone involved.

**Comment by Glxblt76** [comment]
Just to add something to a161803398 helpful post: 

The direct link where you can download the actual dll file is:
[This one](https://ci.appveyor.com/project/chcg/npp-exportplugin/build/job/39pucw169uspxvki/artifacts)

Worked for me. Simply click on "NppExport.dll" to download it and put NppExport.dll in the Plugins subfolder of Notepad++ folder.

**Comment by CiN1979** [comment]
He could remove plugin manager when new one is created. Now I see not reason to use it instead of windows notepad

**Comment by ErPuneetGoel** [comment]
Just to update my comment, you can use this link to download 64bit of Notepad++ from here [Notepad++-64](https://notepad-plus-plus.org/repository/7.x/7.0/npp.7.Installer.x64.exe)

Then Use the Plugin manager from above post of mine and use it.

**Comment by saurabhchawla** [comment]
Does TextFX plugin work with 64 bit Notepad++? Can anyone help me install it since Plugin Manager is not available

**Comment by zockons12** [comment]
For me this is present in: notepad++ 32 bit x86

**Comment by AntonioCS** [comment]
Hey,

I have been using Notepad++ for quite a few years on and off.
Today I wanted to add some plugins (treeview and some others) and I noticed that there was no way to add a plugin because the plugin manger is gone (Notepad++ 7.5.4 32bit)
I am sorry but this seems ridiculous to me, how something so crucial is missing.

If one of the great things about notepad++ is it's extensibility via plugins I would expect the devs would put great effort into making sure adding and removing plugins would be easy for the user.

Without a plugin manager this tasks difficulty increases greatly!
How did this project get to this point?

Please make sure future versions of notepad++ come with a plugin manager!

**Comment by RobertBouillon** [comment]
Is it really THAT hard to download a DLL and import it instead?

![image](https://user-images.githubusercontent.com/612152/36851113-79e9f9ec-1d36-11e8-80cf-3a6d209ee9f2.png)

Notepad++ author hasn't made a dime on ads, and has built the product on the premise. It seems rational not to include a plugin by default that violates those principles. An official plugin manager is coming. In the mean-time, the 3rd party plugin manager can still be downloaded and installed, it's just not there by default.

**Comment by AntonioCS** [comment]
@RobertBouillon It is a bit more complicated when the only way to get plugins I ever knew existed was via the plugin manager and I see that there have been quite a few versions of Notepad++.
So instead of doing a complicated plugin manger the author could just give us something simple.

And this might also be a lesson, maybe don't make the plugin manager a plugin but make it apart of the core functionality offered by Notepad++

**Comment by RobertBouillon** [comment]
You can't promise an ad-free experience and then include a plugin that shows ads.

Does it impact the end-user experience? Absolutely. That's why the new version will have one built-in.

Perhaps a more explicit note on the download page would help, since this seems to be a hot topic. I know I was fairly confused myself upon downloading the new version, which led me here.

**Comment by AntonioCS** [comment]
Yes I understand. I was not suggesting that the author now include a ad ridden plugin. 
I was merely saying that this should have been a top priority for him, but I do understand this might not be his main source of income so there might be other priorities :D

**Comment by MunkhdelgerMorhous** [comment]
is plugin manager available on 64bit ? right now?

**Comment by michael-milette** [comment]
Plugin Manage is not only not included with the 64-bit version but the 32-bit version as well. If you install v7.4.2 (32-bit) edition first, you will get the plugin manager. When Notepad++ first launches, it will prompt you to upgrade to the latest version (7.5.6 as of today). Allow it and you will end up with the most recent version of Notepad++ 32-bit including the Plugin Manager.

**Comment by CTimmerman** [comment]
64 bit Plugin Manager is now available
https://github.com/notepad-plus-plus/notepad-plus-plus/issues/3264
