### ISSUE TITLE
Under Help (?) "Forum" still points to SourceForge

### ISSUE THREAD

**Issue by teddgram** [notepad-plus-plus/notepad-plus-plus#246]
Nothing really to comment, just thought I would point that out since you've moved over here.

**Comment by donho** [comment]
Indeed! will be fixed in the next release.

**Comment by sanastasiou** [comment]
Side question : will the forum questions / knowledge be transfered here somehow ? Wiki ? Or somewhere?

**Comment by donho** [comment]
@teddgram Fixed in v6.7.9.2
@sanastasiou Bad news: AFAIK, there's no way to transfer the data from SF to reuse in GitHub.
Good news: we got a new Forum (Notepad++ Community):
https://notepad-plus-plus.org/community
