### ISSUE TITLE
Tab Settings malfunctioning on v7+

### ISSUE THREAD

**Issue by ChickenDuck** [notepad-plus-plus/notepad-plus-plus#2463]
### Description of the Issue
The Tab settings on v7+ is malfunctioning, it failed to respect the "replaced by space" settings when you do not change the "Tab size". It happens on v7+ both x86 and x64.

### Steps to Reproduce the Issue

1. Change the Tab Settings of any programming language by unchecking "Use default value"
2. Check "Replaced by space" (Don't change the "Tab size")
3. Press TAB in the corresponding language file
4. The TAB key is still outputting \t instead of SPACE
5. If you now alter the "Tab size", it will output the correct amount of SPACE

### Actual Behavior

The attached images show **strange location of the [Default] option** which is in the middle of the list and the list also duplicated itself
![tab settings-1](https://cloud.githubusercontent.com/assets/8293704/19604343/6b738ec6-97e7-11e6-866c-995820f55eba.png)
![tab settings-2](https://cloud.githubusercontent.com/assets/8293704/19604354/7349b0c6-97e7-11e6-9777-47f17ff4d9eb.png)

The outcome of the "Tab settings" opened in MS Notepad.
![outcome](https://cloud.githubusercontent.com/assets/8293704/19604363/771b9386-97e7-11e6-852d-4273809d5aa0.png)

### Debug Information

Notepad++ v7.1   (64-bit)
Build time : Oct 15 2016 - 23:35:37
Path : C:\Users\[Censored]\Desktop\npp.7.1.bin.minimalist.x64\notepad++.exe
Admin mode : OFF
Local Conf mode : ON
OS : Windows 10
Plugins : none

**Comment by guy038** [comment]
Hi, **ChickenDuck**

- I confirm all what you said, in my **Win Xp SP3 x32** configuration, with the last **v7.1** N++ version

- As for me, it's **OK** with Notepad++ **v7.0**

My **Debug** info :

Notepad++v7.1   (32-bit)
Build time : Oct 15 2016 - 23:30:30
Path : C:\_710\notepad++.exe
Admin mode : OFF
Local Conf mode : ON
OS : Windows XP
Plugins : mimeTools.dll NppConverter.dll NppExport.dll PluginManager.dll 

Best Regards,

guy038

**Comment by dail8859** [comment]
Closed by 2897dee54a8d265f588bafc1ca14fec06bba3ccd
