### ISSUE TITLE
low quality of icons for high definition monitors 

### ISSUE THREAD

**Issue by reza1615** [notepad-plus-plus/notepad-plus-plus#2466]
Tools' icons are too small at 4k monitors after increasing the display scale 150% it causes the icons shows with low-quality.
<img width="519" alt="untitled" src="https://cloud.githubusercontent.com/assets/2202483/19621957/ee7111ea-98aa-11e6-84b7-bbcc15306305.png">

for example, see these icons
<img width="528" alt="untitled2" src="https://cloud.githubusercontent.com/assets/2202483/19621974/4dd93f4a-98ab-11e6-89b2-7b39765ccef0.png">
please add  icons with higher quality.

**Comment by Tereos** [comment]
Hi there, found out useful tool to enlarge images don't know if this might work out for you.  http://www.imageenlarger.com/ 
![next icon original](https://cloud.githubusercontent.com/assets/17453657/20217355/728b51f4-a817-11e6-96c8-082df964bd46.png)
![next_icon-mitchell 2 10x10](https://cloud.githubusercontent.com/assets/17453657/20217358/75f9bdda-a817-11e6-89d8-3de4fcce1a01.jpg)
Those kind of adjustments with filtering are subjective so not sure if this going to work out.
Other way might be usage of interpolation, more complicated but might give better result

**Comment by reza1615** [comment]
The size of images or icons is no matter. To support full HD monitors  for photoshop Adobe uploaded new icons with high definition (High DPI) , Nodepade++'s Icons should have higher dpi to support Full HD monitors.
They could be vector instead of bitmap like SVG

**Comment by MetaChuh** [comment]
please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins if you update from version 7.5.9 or below.
if your issue still persists, and it is still of relevance to you, please feel free to file a new issue as easy to understand and reproducible as possible.

thank you for your help and best regards.

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
(no extra account is needed, just use your github account to sign in)
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)

**Comment by reza1615** [comment]
I updated and still the issue persists
