### ISSUE TITLE
"pin" certain recently edited files so that they always stay in the list

### ISSUE THREAD

**Issue by teddgram** [notepad-plus-plus/notepad-plus-plus#247]
This would be similar to what MS Office does with Excel/Word/etc.  This is handy for files that are frequently edited but not necessarily edited every day.  If you are using NP++ a lot like I do, the buffer of recently opened files tends to flush out the files that I edit every once in a while, but are buried in a folder structure that makes it time consuming to locate (or just damn near frustrating when you pick the wrong path when heading down the rabbit hole).

**Comment by cmeriaux** [comment]
:+1:

**Comment by mrpaulwass** [comment]
Was the Pin feature ever added?  I have Notepad++ version 7.3.2 (32bit) and I don't see any way to Pin files.

**Comment by alhowarth** [comment]
I came here to request this exact feature.

**Comment by b1k3rdude** [comment]
Same issue here, I have a few files I regularly open and would be extremely handy to not be able to close these, better still if the pinned tabs could be minimized that would seal the deal.

**Comment by MetaChuh** [comment]
closed due to:
* issue age
* can be done by saving favourite files sessions
* pinning can be done with NppJumpList
![Imgur](https://i.imgur.com/7j2Bu8a.png)

**Comment by jalle007** [comment]
#MetaChuh

> 
> 
> closed due to:
> 
>     * issue age
> 
>     * can be done by saving favourite files sessions
> 
>     * pinning can be done with NppJumpList
>       ![Imgur](https://camo.githubusercontent.com/0522aaa2c5535c4e204ae4db239bd9d305161f7a/68747470733a2f2f692e696d6775722e636f6d2f376a32427538612e706e67)

Are you serious ?? All 3 reasons given by you are true NONSENSE !
Especially last one , you must be dumb when you even think to attach that picture.

You are developer or some kind of joker ?
