### ISSUE TITLE
[REQUEST] LTR/RTL Caret

### ISSUE THREAD

**Issue by Yaron10** [notepad-plus-plus/notepad-plus-plus#2470]
Hello,

RTL users are used to a caret indicating the current text direction.

![InsertText](https://s21.postimg.org/mmbsdk76v/Caret.png)

Could you please add this option to NPP?

Thank you.

**Comment by iegik** [comment]
OS: Windows 10
The wrong caret position in word `НОМЕНКЛАТУ́РА` in Notepad++ app:
![](http://joxi.ru/52abw49CG5xX0A.png)

**Comment by MetaChuh** [comment]
@Yaron10 

rtl is still a big scintilla problem and not fixable from the notepad++ part.

thank you for your help and best regards.
