### ISSUE TITLE
Set caret position to context-menu's position 

### ISSUE THREAD

**Issue by Yaron10** [notepad-plus-plus/notepad-plus-plus#2472]
Hello,

STR:
Position the caret in line 1.
Right-click in line 3 (e.g. in order to paste some text there).

Result:
The caret position remains in line 1 and the desired context-menu commands are executed there.

I've been using NPP for a few years and I still find this behavior quite confusing.
Many editors change the caret position on right-clicking and set it to the context-menu's position (if there's no text selected).

Could you please modify NPP's behavior? Or add an option for that?

Thank you.

**Comment by guy038** [comment]
Hi, **Yaron**,

On my **XP SP3** configuration :

- The caret is, **automatically**, moved to the position where I **right**-clicked, for **context** menu

- If I use the **paste** command of the context-menu, the text of the **clipboard** is, then, added at the **caret location** and, at the end, the **caret**'s position is just **after** the **pasted** text !

May be, your behaviour is tied to the **Hebrew RTL** way of writing ?

Cheers,

guy038

**Comment by Yaron10** [comment]
Hello Guy,

I hope you're getting better. :)

Thank you very much for this reply.

I downloaded a portable NPP and, indeed, all was well.
I changed the layout to RTL and, still, no problem.

It turns out that the culprit is my SciLexer.dll.
Some time ago I posted the following lines in the forum:

>     Hello,
> 
>     When NPP 6.7 came out I updated to it from v6.5.4.
>     Somewhere between those version a change in the source-files introduced the following bug:
> 
>     Left-click in the Line-Margin (the line is selected).
>     Right-click in the same spot.
> 
>     Result:
>     In v6.5.4 the Edit commands in the context-menu are available.
>     From v6.7 the line is deselected and, as a consequence, the Edit commands are not available.
> 
>     I filed a bug at the time but, so far, it hasn’t been addressed.
>     This is important to my workflow and I’d like to change it myself.
> 
>     I’d appreciate your help finding the culprit. :)
> 
>     Thank you.

Someone kindly sent me a modified SciLexer.dll solving that issue.
At the time I did not notice the problem (described in this thread) it created, and when I did I wrongly assumed it was a NPP issue.

Lesson: test first with all original files.
**My sincere apologies.**

Best regards.
