### ISSUE TITLE
This is a major mistake that has brought me great inconvenience

### ISSUE THREAD

**Issue by byebvip** [notepad-plus-plus/notepad-plus-plus#2473]
![qq 20161024010650_](https://cloud.githubusercontent.com/assets/23015915/19628044/9f34792c-9987-11e6-86e5-caac4950d056.png)

As shown in the figure, when the number of rows selected is more than a certain number, it is not fully displayed

Is likely to be selected characters enough case! Is this the number of selected lines will be forgotten by the author?

But let me more puzzling is that the left side of the place actually also empty out a lot

I hope to solve this problem as soon as possible

I think this will let me in the next work more gratifying

**Comment by oatesch** [comment]
Very little information supplied, cannot easily reproduce bug. Please look at other users issues for guidance. Click-bait title is not useful: "Information in status bar clipped" would be more helpful.

Debug Information? (OS, np++ version, default system font)

Two possible workarounds:
Install TextFX plugin
Change system font to variable-width (e.g. Segoe UI)

**Comment by MetaChuh** [comment]
please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins if you update from version 7.5.9 or below.
if your issue still persists, and it is still of relevance to you, please feel free to file a new issue as easy to understand and reproducible as possible.

thank you for your help and best regards.

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
(no extra account is needed, just use your github account to sign in)
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)

**Comment by sasumner** [comment]
Gotta admit, it was a great issue title
