### ISSUE TITLE
When connected via RDP, Clicking File Menu on NPP crashes the RD computer

### ISSUE THREAD

**Issue by TheMissingNTLDR** [notepad-plus-plus/notepad-plus-plus#2474]
### Description of the Issue

When connected via remote desktop on a PC which has NPP then Clicking File Menu on NPP crashes the Remote PC
### Steps to Reproduce the Issue
1. Open a Windows PC which does not necessarily have NPP installed
2. Run MSTSC (Remote Desktop) in Windows
3. Connect to a remote PC which does have NPP installed
4. Just click the File Menu on the top in NPP
### Expected Behavior

File Menu should display
### Actual Behavior

The remote computer crashes and restarts
### Debug Information

This happened 3 time and is consistent with steps. Not sure we have to copy paste anything in NPP on remote PC but trying to save via file Menu crashes remote PC. It took a long time to work out what was happening as the RDP hangs and is not obvious on the screen that the remote PC actually crashed. There is something logged in the Windows Event Viewer but as I do not currently have access to those logs unable to paste it here. But I am sure this defect can be easily be reproduced by Devs.

**Comment by TheMissingNTLDR** [comment]
Reading on the net with similar applications (e.g. M$ notepad), I suspect this is due to "recent files opened list" in NPP where the path is not found on File Menu while on RD, hence the crash.

**Comment by MetaChuh** [comment]
please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins if you update from version 7.5.9 or below.
if your issue still persists, and it is still of relevance to you, please feel free to file a new issue as easy to understand and reproducible as possible.

thank you for your help and best regards.

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
(no extra account is needed, just use your github account to sign in)
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)
