### ISSUE TITLE
Setting Notepad ++as default

### ISSUE THREAD

**Issue by KJL9** [notepad-plus-plus/notepad-plus-plus#2476]
### Description of the Issue
Can't set Notepad ++7.1 64bit as a default. Will not come as a choice.

### Steps to Reproduce the Issue
As you normally setup default program.

### Expected Behavior
Nada

### Actual Behavior
Will not come up as choice.

### Debug Information
Notepad++ v7.1   (64-bit)
Build time : Oct 15 2016 - 23:35:37
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : ON
Local Conf mode : OFF
OS : Windows 7
Plugins : mimeTools.dll NppConverter.dll

**Comment by dail8859** [comment]
Duplicate of #2454

**Comment by LeadManPL** [comment]
Workaround in #2454

**Comment by KJL9** [comment]
It's a BAD BUG.

**Comment by dail8859** [comment]
Closing since it is a duplicate.
