### ISSUE TITLE
config.xml was destroyed when my C drive was completely full.

### ISSUE THREAD

**Issue by gladkikhartem** [notepad-plus-plus/notepad-plus-plus#2479]
### Description of the Issue

config.xml was destroyed when my C drive was completely full.
### Steps to Reproduce the Issue
1. Make your C drive completely full.
2. Try to write some files or connect to STFP server via nppFTP plugin and write files remotely.
3. Notepad should give error message that you need admin rights.
4. Close message & Exit Notepad.
5. Open Notepad and it will claim that config.xml was not found.
### Expected Behavior

Message that says that there is no space on C drive, make sure you have space, otherwise you could loose your temporary data.
### Actual Behavior

config.xml was destroyed, as well as remote nppFTP files became empty.
### Debug Information

Notepad++ v6.9.2
Build time : May 18 2016 - 00:34:05
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 7
Plugins : ComparePlugin.dll Explorer.dll IndentByFold.dll mimeTools.dll NppConverter.dll NppExport.dll NppFTP.dll PluginManager.dll 

For me fix is not important, just posted the bug for your information.

P.S. Thank you for such an awesome product! Using it for whole my professional life)

**Comment by MetaChuh** [comment]
please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins if you update from version 7.5.9 or below.
if your issue still persists, and it is still of relevance to you, please feel free to file a new issue as easy to understand and reproducible as possible.

thank you for your help and best regards.

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
(no extra account is needed, just use your github account to sign in)
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)
