### ISSUE TITLE
Display only one row in "Find All in Current Document"

### ISSUE THREAD

**Issue by VARGA-Peter** [notepad-plus-plus/notepad-plus-plus#2481]
### Description of the Issue

The "Find result" window displays each occurrences of the subject in one row.
![noptepad example](https://cloud.githubusercontent.com/assets/9625486/19682567/84ea7184-9aae-11e6-95b7-d825d495a15a.png)

There could be an option in the "Find" Window called something like "Group in one line" with which in the above example only 1 line would be displayed and the 3 occurrences would be marked three times in this line.

**Comment by moymike** [comment]
I /agree.  [[my post]](https://notepad-plus-plus.org/community/topic/15631/find-results-multiple-matches-per-line-would-like-non-duplicate-line-result-highlighting-every-match/2)

**Comment by sasumner** [comment]
Similar to #1499 so closing.

**Comment by sasumner** [comment]
This feature-request is REJECTED by the author of Notepad++ ( https://github.com/notepad-plus-plus/notepad-plus-plus/pull/9088#issuecomment-720016310 )
It will not be reconsidered.
Please do not open any new issues on this topic as they will be immediately closed.

The suggestion is to use this workaround:
* Set your _Search mode_ to _Regular expression_.
* Add the following to the end of your _Find what_ expression:  `(?-s).*`

Example 1: To show only the first hit on a line for `foo`, make your _Find what_ expression `foo(?-s).*`

If the literal text you are intending to search for contains regular expression metacharacters, add `\Q` to its start and `\E(?-s).*` at its end.

Example 2: To show only the first hit on a line for `*foo*`, make your _Find what_ expression `\Q*foo*\E(?-s).*`
