### ISSUE TITLE
Rexx highlighting

### ISSUE THREAD

**Issue by zatlas1** [notepad-plus-plus/notepad-plus-plus#2483]
The Rexx Language is a legitimate, open source language, available on Windows, Unix, Linux, Mac z/OS (several implementations and several variants for most or all platforms) and is popular among ex-IBMers.  Notepad++ does not know how to highlight it.

1.  My question is how hard would it be to teach Notepad++ to highlight this language correctly
2.  I would say that the most popular variant is OORexx (http://www.oorexx.org/)

**Comment by dknippers0** [comment]
There is an User-Defined Language File for Rexx @ http://docs.notepad-plus-plus.org/index.php/User_Defined_Language_Files

**Comment by TheIncorrigible1** [comment]
@zatlas1 Would just like to contribute and say REXX is also utilized for Radia (SCCM competitor, previously HP Client Automation) for its packages

**Comment by RomanSofyin** [comment]
> There is an User-Defined Language File for Rexx @ http://docs.notepad-plus-plus.org/index.php/User_Defined_Language_Files

Current link is https://npp-user-manual.org/docs/user-defined-language-system/#user-defined-languages-collection

**Comment by zatlas1** [comment]
The link is broken

Ze'ev Atlas

    On Tuesday, May 31, 2022, 12:15:18 PM EDT, Roman ***@***.***> wrote:  
 
 



There is an User-Defined Language File for Rexx @ http://docs.notepad-plus-plus.org/index.php/User_Defined_Language_Files


Current link is https://npp-user-manual.org/docs/user-defined-language-system/#user-defined-languages-collection
