### ISSUE TITLE
Bugged text replacing

### ISSUE THREAD

**Issue by xalalau** [notepad-plus-plus/notepad-plus-plus#2484]
When I replace all the "()" for "( )" this happens:

Before:
![1~](http://i.imgur.com/ApNGEZs.jpg)

After:
![2](http://i.imgur.com/m231A4r.jpg)

It's a bug, right? =<

And here is a bonus:
![bonus](http://i.imgur.com/tbTb0Cf.jpg)
The correct is *Suporte*, not *Siporte*.
Language: PT-BR (Portuguese from Brazil)

Sorry about the report formatation...
And thx for the awesome work!

**Comment by MAPJe71** [comment]
Set `Search Mode` to `Normal`?

**Comment by xalalau** [comment]
kk Normal is working. At least I found a bonus.
Thank you.

**Comment by MAPJe71** [comment]
@xalalau FYI the misspelled translation i.e. your *bonus* was already fixed.
