### ISSUE TITLE
"\&" does not display correctly with some languages

### ISSUE THREAD

**Issue by schtandard** [notepad-plus-plus/notepad-plus-plus#2486]
### Description of the Issue

When code highlighting for TeX is applied, "\&" is displayed as "\ " (backslash space), i.e. the "&" is not displayed.

The same issue also arises with some other languages, including Assmembly, C++, Fortran, Java, Matlab, Pascal and Perl. However, other languages including Batch, Makefile, Postscript and Shell do not cause this behavior.

### Steps to Reproduce the Issue

1. Open Notepad++
2. Type "\&"
3. Choose Language -> T -> TeX

### Expected Behavior

The "\&" should be displayed blue and bold, as all macros are.

### Actual Behavior

Only the "\" is displayed blue and bold, the "&" is not displayed at all.

### Debug Information

Notepad++ v6.9.2
Build time : May 18 2016 - 00:34:05
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10
Plugins : mimeTools.dll NppConverter.dll NppExport.dll NppFTP.dll PluginManager.dll

**Comment by dail8859** [comment]
This is a known issue with the Source Code pro font not displaying bold ampersands.

https://github.com/notepad-plus-plus/notepad-plus-plus/issues?utf8=%E2%9C%93&q=is%3Aissue%20ampersand%20is%3Aclosed%20
