### ISSUE TITLE
x64: Drag and drop with files dragged from 32-bit app

### ISSUE THREAD

**Issue by v777** [notepad-plus-plus/notepad-plus-plus#2487]
### Description of the Issue

With Notepad++ 7.1 x64, a file dragged from a 32-bit application is not open.
### Steps to Reproduce the Issue

1. Just drag and drop a file from any 32-bit application (e.g. FreeCommander) to the x64 edition of Notepadd++.
### Expected Behavior

The drag and drop should work with the x64 Notepad++ and a 32-bit application.
### Actual Behavior

I discussed this issue on Stackoverflow. Please see my answer here:
http://stackoverflow.com/a/39664759/4932147
### Debug Information

Notepad++ v7.1   (64-bit)
Build time : Oct 15 2016 - 23:35:37
Path : D:\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : ON
OS : Windows 10
Plugins : mimeTools.dll NppConverter.dll

**Comment by Maxxim69** [comment]
I, for one, would appreciate it if this bug were fixed.

Notepad++ v7.3.2   (64-bit)
Build time : Feb 12 2017 - 23:17:55
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10 (64-bit)
Plugins : mimeTools.dll NppConverter.dll

**Comment by MetaChuh** [comment]
please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins if you update from version 7.5.9 or below.
if your issue still persists, and it is still of relevance to you, please feel free to file a new issue as easy to understand and reproducible as possible.

thank you for your help and best regards.

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
(no extra account is needed, just use your github account to sign in)
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)
