### ISSUE TITLE
Implement double-click on view splitter and/or Alt+F8 keyboard shortcut to restore 50/50 split view

### ISSUE THREAD

**Issue by Duellmann** [notepad-plus-plus/notepad-plus-plus#2488]
### Description of the Issue

Notepad++ rocks! View splitter rocks! I like those arrow buttons on the view splitter that maximise one view to 100% of screen width or height. But then, when I want to share again between 2 views, I've often found myself wishing there could be an equally easy way of restoring a 50/50 shared view, rather than manually dragging the splitter and never getting exactly 50/50.
### Steps to Reproduce the Issue

1. Split View between 2 documents
2. Use left/right arrow on splitter to maximise one view
3. Try to return to 50/50 split view
### Expected Behavior

Please implement an easy way to restore 50/50 split view
- double-click on splitter to restore 50/50
- Alt+F8 keyboard shortcut to restore 50/50
### Actual Behavior

Could not find any easy way to restore 50/50 split view, only dragging splitter manually which is inconvenient and not precise

Thank you

**Comment by MetaChuh** [comment]
please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins if you update from version 7.5.9 or below.
if your issue still persists, and it is still of relevance to you, please feel free to file a new issue as easy to understand and reproducible as possible.

thank you for your help and best regards.

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
(no extra account is needed, just use your github account to sign in)
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)
