### ISSUE TITLE
AccessViolation on change back to notepad++

### ISSUE THREAD

**Issue by trivalik** [notepad-plus-plus/notepad-plus-plus#2489]
### Description of the Issue

I changed to the notepad++ windows and an access violation comes up.
The last visible file was an xml file which was changed outside of notepad++.
### Steps to Reproduce the Issue

I have no steps to reproduce.
### Expected Behavior

No crash.
### Actual Behavior

Crash. after dump creation.
### Debug Information

Notepad++ v6.9.2
Build time : May 18 2016 - 00:34:05
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : ON
Local Conf mode : OFF
OS : Windows 7
Plugins : DSpellCheck2.dll HexEditor.dll linefilter2.dll mimeTools.dll NppConverter.dll NppExport.dll NppFTP.dll PluginManager.dll 

Please find attached the dump of the crash.

[NppDump.zip](https://github.com/notepad-plus-plus/notepad-plus-plus/files/555209/NppDump.zip)

BTW
When you move the notepad++ down that is half window not on screen. Debug Information windows is not visible to user, because outside of screen.

**Comment by MetaChuh** [comment]
please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins if you update from version 7.5.9 or below.
if your issue still persists, and it is still of relevance to you, please feel free to file a new issue as easy to understand and reproducible as possible.

thank you for your help and best regards.

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
(no extra account is needed, just use your github account to sign in)
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)
