### ISSUE TITLE
Regular expressions do not change case of cyrillic letters

### ISSUE THREAD

**Issue by Ma8ter** [notepad-plus-plus/notepad-plus-plus#2490]
### Description of the Issue

Special characters such as \u, \l, \U, \L do not change case of cyrillic letters
### Steps to Reproduce the Issue

1. Type smth like "рУсСкИй тЕкСт eNgLisH tExT"
2. Open find-replace dialogue
3. Check radiobutton "regular expression"
4. Find what:(\w*)
5. Replace with:\L\u\1
### Expected Behavior

text is replaced by "Русский Текст English Text"
### Actual Behavior

text is replaced by "рУсСкИй тЕкСт English Text"
### Debug Information

Notepad++ v7.4.1   (32-bit)
Build time : May 18 2017 - 02:00:37
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : ON
Local Conf mode : OFF
OS : Windows 7 (64-bit)
Plugins : DSpellCheck2.dll mimeTools.dll NppConverter.dll NppExec.dll NppExport.dll PluginManager.dll

**Comment by MetaChuh** [comment]
please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins if you update from version 7.5.9 or below.
if your issue still persists, and it is still of relevance, please feel free to file a new issue as easy to understand and reproducible as possible.

thank you for your help and best regards.

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
(no extra account is needed, just use your github account to sign in)
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)

**Comment by VGBLTSK** [comment]
I can confirm that the issue is not fixed. Checked on the latest version of NPP+.
