### ISSUE TITLE
Crash when creating or saving new User Defined Language

### ISSUE THREAD

**Issue by TheAtomicOption** [notepad-plus-plus/notepad-plus-plus#2491]
### Description of the Issue
When using the Create New or Save As.. buttons in the user defined language dialog, the program crashes

### Steps to Reproduce the Issue

1. Open Notepad++ and select Language->Define your Language...
2. Click either the Create New... or Save As... buttons 
3. Enter any name and press ok.
4. Notepad++ crashes.

### Expected Behavior
I expected it to add a blank user language that I could then edit. 

### Actual Behavior
Notepad++ crashes

### Debug Information

Notepad++ v7   (64-bit)
Build time : Sep 21 2016 - 22:07:28
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10
Plugins : mimeTools.dll NppConverter.dll

**Comment by dail8859** [comment]
The 7.1 release notes:

> Fix x64 crash on new language dialog of UDL
