### ISSUE TITLE
Crash when filling text at end of lines by using "Column/Multi-Selection Editor"

### ISSUE THREAD

**Issue by ljungknut** [notepad-plus-plus/notepad-plus-plus#2492]
### Description of the Issue
If I have several lines I want to fill with text at end by first selecting the lines in "column mode" and the using "Column/Multi-Selection Editor", Notepad++ crashes.
This only happen if the "column mark" in one or several of the lines is byond its "end of line" character.

I'm currently using Notepad++ v6.1 (UNICODE) on Windows 7 but this happen also in earlier version of UNICODE. If I remember right this does NOT happen in ANSI version of Notepad++

### Steps to Reproduce the Issue

1. Having two lines in a document, first one with 5 characters and second one with 10 characters
2. Positioning the cursor at end of the second line (the longest line)
3. Enter column mode by pressing and holding Alt+Shift
4. Press up arrow key to also select the first line in column mode
5. Press right arrow key until only one column is selected (still with Alt+Shift pressed)
6. Open "Column/Multi-Selection Editor" (Alt+c)
7. Add some text in the textbox and press "OK"

### Expected Behavior
The text from the "Column/Multi-Selection Editor" is pasted at the end of both lines in straight column
E g:
```
if (A)        //My pasted comment
  TakeAction; //My pasted comment
```

### Actual Behavior
Notepad++ crashes

My workaround today is that between point 5 and 6 press space bar ones or several times (adding  spaces at end of each line) before open the "Column/Multi-Selection Editor". But sometimes I forgett this and ...

### Debug Information
**From system log:**
Faulting application name: notepad++.exe, version: 6.1.0.0, time stamp: 0x4f8332f3
Faulting module name: SciLexer.dll, version: 2.2.7.0, time stamp: 0x4f4d582f
Exception code: 0xc000000d
Fault offset: 0x0007dbdf
Faulting process id: 0x3c30
Faulting application start time: 0x01d230d9968c0ba9
Faulting application path: C:\Program Files (x86)\Notepad++\notepad++.exe
Faulting module path: C:\Program Files (x86)\Notepad++\SciLexer.dll
Report Id: eea81982-9ccc-11e6-8cb6-507b9de20b43

**Crash popup:**
![2016-10-28 07_50_31-_new 1 - notepad](https://cloud.githubusercontent.com/assets/23113868/19796258/4b89dda8-9ce3-11e6-8b37-9ae1d6616e6f.png)

**Comment by dail8859** [comment]
Update to the latest version of Notepad++. Reopen if the problem is still there.
