### ISSUE TITLE
[REQUEST] Incremental Replace

### ISSUE THREAD

**Issue by Slurm-McKenzie** [notepad-plus-plus/notepad-plus-plus#2493]
What i am missing is an option for incremental replace.
Just like the normal search and replace funktion, 
but with a special charakter in the replace string that will automatically be replaced with an incrementing number (integer). Preferably you can specifiy the starting value.

I want to search for a string like "Demo" and replace it with "Test_$1$" ,
and the replace dialog will take care of it and automatically replace $1$ with an incrementing integer.

Example:
-------- Before ---------
Demo
Demo
Demo

---------- After ----------
Test1
Test2
Test3

This is currently only possible with (python)scripts as far as i know and that is very inconvenient and slow in my case.
On x64 version of NP++ there is also the problem with the x32 only plugins.
Native support for this feature would be great.

**Comment by donho** [comment]
This feature is not so demanded, and not trivial to implement. So it won't be implemented in the future.

**Comment by sasumner** [comment]
Plus it isn't too hard to "script".  For instance, the Pythonscript documentation has just such an example.
