### ISSUE TITLE
Can't copy paths and line numbers from "find result" dialog

### ISSUE THREAD

**Issue by bahusoid** [notepad-plus-plus/notepad-plus-plus#2494]
I want to copy to clipboard some finder content including paths and lines where string were found. But all I can get in clipboard is the actual file content.
### Steps to Reproduce the Issue
1. Searh in files for some string via Find In Files dialog (Ctrl+Shift+F).
2. Try to select some lines in find result dialog including file paths and then right click -> Copy (another issue here is Ctrl+C doesn't work here)
3.  Paste the result in to new document.
### Expected Behavior

Ability to copy full info available in "find result" dialog including file path and line numbers. So I can share those results with someone else.
### Actual Behavior

Only file content is copied:

![nodetails](https://cloud.githubusercontent.com/assets/22025304/19827932/7ba5c482-9dc1-11e6-83da-eff18d97f8d1.png)
### Debug Information

Reproduced in multiple configurations including minimalistic install with no app data and no plugins:

My working configuration:
Notepad++ v7.1   (32-bit)
Build time : Oct 15 2016 - 23:30:30
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10
Plugins : ComparePlugin.dll CutNCopyLine.dll HTMLTag_unicode.dll mimeTools.dll NppConverter.dll NppExport.dll NppFTP.dll NppMenuSearch.dll NppSaveAsAdmin.dll NppTextFX.dll PluginManager.dll PoorMansTSqlFormatterNppPlugin.dll XMLTools.dll 

Clean install configuration:

Notepad++ v7.1 (32-bit)
Build time : Oct 15 2016 - 23:30:30
Path : C:\Programs\npp.7.1.bin.minimalist\notepad++.exe
Admin mode : OFF
Local Conf mode : ON
OS : Windows 10
Plugins : none

**Comment by cmeriaux** [comment]
I can't reproduce your bug

    Notepad++ v7   (32-bit)
    Build time : Oct  9 2016 - 08:23:15
    Path : C:\Program Files (x86)\Notepad++\notepad++.exe
    Admin mode : OFF
    Local Conf mode : OFF
    OS : Windows 10
    Plugins : LightExplorer.dll linefilter2.dll MenuIcons.dll mimeTools.dll NppConverter.dll NppExec.dll NppExport.dll NppFTP.dll NppMenuSearch.dll PluginManager.dll PythonScript.dll XMLTools.dll 

Try to remove test without plugin.
Try to clean config.xml

**Comment by bahusoid** [comment]
As you can see I'm using the latest 7.1 version. Did you try on it? I'm pretty sure that's something very recent. I just reproduced it on clean minimalistic insatll:
Notepad++ v7.1   (32-bit)
Build time : Oct 15 2016 - 23:30:30
Path : C:\Programs\npp.7.1.bin.minimalist\notepad++.exe
Admin mode : OFF
Local Conf mode : ON
OS : Windows 10
Plugins : none

**Comment by dail8859** [comment]
I tried and was able to produce it. FYI this is *not* a clean install. 

```
Notepad++ v7   (32-bit)
Build time : Sep 21 2016 - 22:00:56
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : ON
Local Conf mode : OFF
OS : Windows 7
Plugins : ComparePlugin.dll LuaScript.dll PluginManager.dll 
```

**Comment by cmeriaux** [comment]
I can't reproduce it on a clean install with the latest release (official) (but win7)

    Notepad++ v7.1   (32-bit)
    Build time : Oct 15 2016 - 23:30:30
    Path : C:\Program Files\Notepad++\notepad++.exe
    Admin mode : OFF
    Local Conf mode : OFF
    OS : Windows 7
    Plugins : mimeTools.dll NppConverter.dll NppExport.dll PluginManager.dll 

I think you config file may be broken ( C:\Users\user\AppData\Roaming\Notepad++\config.xml ) that could lead to unexcpected behavior. 
Backup every config files and try again with a clean config.

**Comment by bahusoid** [comment]
@cmeriaux It's not config related. I renamed appdata folder with configs just in case when tried on clean minimalistic install. And it's my understanding it was not used anyway becouse of:
Local Conf mode : ON

**Comment by cmeriaux** [comment]
I out of idea. Just in case : don't you have a third party software that enhance the clipboard ?

Other ideas : the clipboard from search panel couldn't work with a text that don't have default encoding

**Comment by bahusoid** [comment]
@cmeriaux Actually it's strange that you can't reproduce it. I found exact commit for this functionality:
https://github.com/notepad-plus-plus/notepad-plus-plus/commit/d6081a5f3785fe0565900fc4c7f6ce1a78e5c6ec

@donho Please consider adding back old functionality (ability to copy with all details provided in Find Result dialog). It was very convinient. May be it should be added as additional command.

**Comment by cmeriaux** [comment]
Sorry I did a huge mistake while reading you issue.
You're right, it's not an issue it's a feature already done.

Workaround: 
select all, copy with Ctrl+C shortcut, then paste wherever you want. you'll get path and line number

**Comment by bahusoid** [comment]
@cmeriaux Ctrl+C doesn't work at all in Find Result dialog. I mentioned it in step 2 in steps to reproduce.

**Comment by cmeriaux** [comment]
Like I said, It works well on my clean config.
If I use the **built-in copy** function of find dialog, i get the found element **without** path and line number.
If I click in the find dialog windows, select all, Ctrl-C and Ctrl-V in a buffer, I get found element **with** path and line number

# Screenshot.
![screenshot](https://cloud.githubusercontent.com/assets/12024941/19899898/01e44dfa-a062-11e6-8a44-2812a4bdc56c.jpg)

# debug info : 

    Notepad++ v7.1   (32-bit)
    Build time : Oct 15 2016 - 23:30:30
    Path : C:\Program Files (x86)\Notepad++\notepad++.exe
    Admin mode : ON
    Local Conf mode : OFF
    OS : Windows 10
    Plugins : LightExplorer.dll linefilter2.dll MenuIcons.dll mimeTools.dll NppConverter.dll NppExec.dll NppExport.dll NppFTP.dll NppMenuSearch.dll PluginManager.dll PythonScript.dll XMLTools.dll

**Comment by bahusoid** [comment]
@cmeriaux  Thanks! Indeed - Ctrl+C is working on clean install. I found a culprit that broke Ctrl+C inside Find Result dialog - https://github.com/kbilsted/NppPluginCutNCopyLine

**Comment by cmeriaux** [comment]
you're welcome. Can you close the ticket ?
