### ISSUE TITLE
Request: Formatting based on file type or even individual files

### ISSUE THREAD

**Issue by Jackalope-Gaming** [notepad-plus-plus/notepad-plus-plus#2495]
I am running version 6.9.2, so I apologize if this feature is in a newer version or if it's already available and I'm too blind to find it in the settings.

I would like the ability to manage how Notepad++ does color and other formatting based on the type of file opened, or even the ability to set different formats fir individual files.  This has come about because I've noticed sometimes while having a .txt file open that NP++ will format some of the text in the document, such as highlighting "20%" in magenta, changing the text color of the 6th character on a line to green, or changing such words as "in" or "value" to blue.

Is this already available in either the version I have or a newer version?  Or is this a bug with the version I have that might be fixed on a newer one?  In some of my other .txt files no color formatting is done whatsoever.

**Comment by dail8859** [comment]
>I would like the ability to manage how Notepad++ does color and other formatting based on the type of file opened, or even the ability to set different formats fir individual files. 

You can change colors under `Settings > Style Configurator` or set the language under the (no surprise) `Language` menu. Notepad++ should auto detect the file based on file extension and highlight the syntax. Try posting step by step examples or screenshots.
