### ISSUE TITLE
Code Folding and Delimiter Styles can't coexist (latest version 7.1)

### ISSUE THREAD

**Issue by LorneCash** [notepad-plus-plus/notepad-plus-plus#2497]
### Description of the Issue

Code Folding and Delimiter Styles don't coexist in this case (the case I need to work)
Here are my settings:

**Folder & Default**
Folding in code 2 style (separators needed):
    Open:
    "Start"

```
Close:
"End" "Error"
```

**Operators & Delimiters**
Delimiter 1 style:
    Styler Button: 
        Foreground:
        Black
        Background:
        White
    Open:
    Trace

```
Close:
(I pasted a Carriage Return here so it highlights the whole line but in the settings you can't visibly see anything)
```

Delimiter 2 style:
    Styler Button: 
        Foreground:
        Black
        Background:
        Red
    Open:
    Error

```
Close:
(I pasted a Carriage Return here so it highlights the whole line but in the settings you can't visibly see anything)
```
### Steps to Reproduce the Issue
1. Setup user defined Language as described above
2. Apply the user defined language to the following text:
   Trace | Main: Start
   Trace |     New: Start
   Trace |     New: End
   Trace |     Method1: Start
   Trace |         Method2: Start
   Trace |             Method3: Start
   Trace |                 Method4: Start
   Error |                     ## System.Exception
   Error |                     ## Message: Object reference not set to an instance of an Object
   Trace |                 Method4: End
   Trace |             Method3: End
   Trace |         Method2: End
   Trace |     Method1: End
   Trace | Main: End
### Expected Behavior

Rows starting with the word Error are highlighted in Red (This works)
Code folding (+) markers appear on every line that ends with "Start"
### Actual Behavior

Rows starting with the word Error are highlighted in Red (This works)
There are no Code folding (+) markers whatsoever
When the Delimiter style settings are removed the code folding works properly
### Debug Information

Notepad++ v7.1   (32-bit)
Build time : Oct 15 2016 - 23:30:30
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : ON
Local Conf mode : OFF
OS : Windows 8.1
Plugins : mimeTools.dll NppConverter.dll NppExport.dll PluginManager.dll XMLTools.dll

**Comment by LorneCash** [comment]
I've tried putting the Open for code folding to ": Start" but it seems that the colon causes it to not be recognized as the Open.

**Comment by MetaChuh** [comment]
please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins if you update from version 7.5.9 or below.
if your issue still persists, and it is still of relevance to you, please feel free to file a new issue as easy to understand and reproducible as possible.

thank you for your help and best regards.

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
(no extra account is needed, just use your github account to sign in)
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)

**Comment by LorneCash** [comment]
I'm not sure why this was closed, maybe just because it's old???  I just verified it's not fixed.  I followed the steps in the original post.

And YES this is still an important issue to me.
