### ISSUE TITLE
[REQUEST] "Page" Tabs

### ISSUE THREAD

**Issue by chemicalrush** [notepad-plus-plus/notepad-plus-plus#2499]
A way to add inner-document page tabs? Not like actual paper page-sized pages like MS Office, but an option to add a "page break," but instead of just adding a line or a space and making you scroll for ungodly amounts of time, you'd get numbered tabs at the top (like browser tabs).

Being able to name the pages on the tabs would be cool too.

I'm using it to keep track of my coding lessons, but holy cow, that list of notes is getting too long to scroll through fast. Having more "book-like" tabs at the top would be incredible, and no other programs are currently doing it.

Other possible option: add tabs but instead of creating new, separate pages within the document, create a scrolling feature (like on this page https://codepen.io/FreeCodeCamp/full/YqLyXB/  the buttons "About, Portfolio and Contact).

Not sure if possible, but would be pretty handy.

**Comment by MetaChuh** [comment]
please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins if you update from version 7.5.9 or below.
if your issue still persists, and it is still of relevance, please feel free to file a new issue as easy to understand and reproducible as possible.

thank you for your help and best regards.

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
(no extra account is needed, just use your github account to sign in)
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)
