### ISSUE TITLE
Feature request: language-triggered auto-completion

### ISSUE THREAD

**Issue by felherc** [notepad-plus-plus/notepad-plus-plus#250]
Auto-completion is nice when programming, but I find myself often being bogged down by auto-completion when simply entering numbers on text files or anything similar. If auto-completion would activate on demand (say by pressing Ctrl+space) or if it could detect I am not writing code (maybe from the file extension or the language selected) this would be nicer than making me go to settings and activating/deactivating the feature every time I change from text files to source code.

**Comment by sanastasiou** [comment]
I second this. There has to be extension specific auto completion options, not global as it is now.

I am writing a plugin, and it was really hard to override the default auto completion ( which is extremely slow on larger files ), and implement my own.

**Comment by MetaChuh** [comment]
closed due to inactivity
