### ISSUE TITLE
[Request] Close All Saved Files

### ISSUE THREAD

**Issue by AgentRev** [notepad-plus-plus/notepad-plus-plus#2500]
I use NPP with session saving, and over long timespans I open and create hundreds of files. These files obviously accumulate in the tabs bar, and once in a while I do a Close All to get rid of this mess.

However, I would like to keep unsaved files open to assess their situation afterwards (and possibly continue editing them) without explicitly saving. A "Close All Saved Files" option would be a simple and effective solution.

**Comment by bahusoid** [comment]
It's a duplicate of #335

**Comment by donho** [comment]
I don't think this feature can bring a good advantage.

**Comment by AgentRev** [comment]
Oh come on, this is actually my biggest problem with N++, a pull request was already made in the past and totally ignored 🙁
