### ISSUE TITLE
[feature request]: add 3 columns for open Menu/Window/Windows/tabs dialog

### ISSUE THREAD

**Issue by andzi** [notepad-plus-plus/notepad-plus-plus#2503]
### Description of the Requested Feature

open Menu/Window/Windows/tabs dialog has 3 additional columns for tabs sorting: 1) date/time created, 2) date/time modified, 3) extention type (txt; html; xml; py; ...)
### Expected Behavior

those additional columns sorts list, and after pressing **sort tabs** tabs are rearranged accordingly

**Comment by MetaChuh** [comment]
please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins if you update from version 7.5.9 or below.
if your issue still persists, and it is still of relevance, please feel free to file a new issue as easy to understand and reproducible as possible.

thank you for your help and best regards.
