### ISSUE TITLE
xml tools plugin - pretty print option runs forever

### ISSUE THREAD

**Issue by kauba** [notepad-plus-plus/notepad-plus-plus#2505]
### Description of the Issue

If a file ends with a comment that is not being closed, pretty print option runs forever

### Steps to Reproduce the Issue

1. create html file that ends with <!--
2. press ctrl+alt+shift+B

### Expected Behavior
file become formatted

### Actual Behavior
the action seems to be running forever and notepad++ freezes

**Comment by dail8859** [comment]
This is a 3rd party plugin. You need to report it to the author of XML Tools.

**Comment by MAPJe71** [comment]
@kauba Shortcut to the [XML Tools Plugin issues list](https://github.com/morbac/xmltools/issues).
