### ISSUE TITLE
Save btn does not work

### ISSUE THREAD

**Issue by sm-g** [notepad-plus-plus/notepad-plus-plus#2506]
### Description of the Issue
Save btn does not work (Save as... and Save copy as... work)

### Steps to Reproduce the Issue
1. Create new txt file
2. Type smth
3. Press File->Save

### Expected Behavior
File saved, UI updated

### Actual Behavior
Nothing happend

### Debug Information
Notepad++ v7.1   (32-bit)
Build time : Oct 15 2016 - 23:30:30
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 7
Plugins : ComparePlugin.dll JSMinNPP.dll mimeTools.dll NppConverter.dll NppExport.dll NppSaveAsAdmin.dll PluginManager.dll XMLTools.dll

**Comment by dail8859** [comment]
Take a look at #2346 which may be the same issue you are running into.

**Comment by sm-g** [comment]
Thanks, that is. Occured after updating to new version.
