### ISSUE TITLE
Notepad crashing while making new folder

### ISSUE THREAD

**Issue by RudivanHemert** [notepad-plus-plus/notepad-plus-plus#2508]
### Description of the Issue
Notepad crashes when making new folder

### Steps to Reproduce the Issue
1. wrote a simple HTML code
2. tried to save it, in saving window: create new folder
3. renaming folder, when pressing enter, Notepad crashes

### Expected Behavior
New folder with my given name shoul be made

### Actual Behavior
Notepad not responding and eventually had to force quit

### Debug Information
Notepad++ v7.1   (64-bit)
Build time : Oct 15 2016 - 23:35:37
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10
Plugins : mimeTools.dll NppConverter.dll 

![2016-10-31_1615](https://cloud.githubusercontent.com/assets/22394676/19859367/521f0c16-9f85-11e6-9aa7-63dfebf79dd6.png)

**Comment by emersonmellado** [comment]
The same thing is happening with me! It just happened, btw.

**Comment by atlason** [comment]
I have the same issue on Windows 10 and Notepad++ 7.3.2. Save As dialog window remains frozen for a couple of minutes when creating new folder.

**Comment by donho** [comment]
@RudivanHemert @emersonmellado @atlason I cannot reproduce it under my Windows 10 with both 32 and 64 bit Notepad++ - is there anything special in your configuration?

**Comment by RudivanHemert** [comment]
Just a standard install. I will try tomorrow when I'm at work if the issue still occurs. I see it was 4 months ago I made this post and forgot about it. Never needed the feature in that time. I will come back with results

**Comment by RudivanHemert** [comment]
I just tried to reproduce the problem but its gone. So I think an update of notepad did the trick
