### ISSUE TITLE
Cannot open a file with "NUL" values after version 6.1

### ISSUE THREAD

**Issue by yagamilighto** [notepad-plus-plus/notepad-plus-plus#2509]
### Description of the Issue
When I try to open a file which contains "NUL" values as in the snapshot below, it takes a very long time to process the file. There is no problem if I try to open the file with version 6.1. I have tried many versions after but they all have this problem.

### Expected Behavior
The file opened and can be edited without any slowness or freezing.

### Actual Behavior
The file takes a very long time to load and after loading, edit operations cause slowness and freezes.

![nulnulnul](https://cloud.githubusercontent.com/assets/23170860/19880812/21f72c42-a009-11e6-869d-61c5fd68f4fb.png)

**Comment by MetaChuh** [comment]
please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins if you update from version 7.5.9 or below.
if your issue still persists, and it is still of relevance, please feel free to file a new issue as easy to understand and reproducible as possible.

thank you for your help and best regards.

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
(no extra account is needed, just use your github account to sign in)
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)
