### ISSUE TITLE
Non-existent keyword "from" highlighted in JavaScript

### ISSUE THREAD

**Issue by skibulk** [notepad-plus-plus/notepad-plus-plus#2510]
The word "from" is highlighted in .js files, but it is not a keyword for the language.

**Comment by anshuman73** [comment]
After checking from multiple resources online, it seems that 'from' is indeed not a Keyword for the Javascript Language.
Awaiting for a confirmation from the repository admins by tagging this issue as ```Accepted``` to issue a pull request.

**Comment by skibulk** [comment]
Also, the words "null", "undefined", and "Infinity" are keywords in JS, but they are not highlighted in Notepad++.

**Comment by Slayer95** [comment]
It's a syntactical keyword in ``import`` statements

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/import

**Comment by anshuman73** [comment]
Ahh, it seems it was introduced in the ECMAScript6.
No wonder there were no (less?) mentions of this elsewhere on the net.
Well, I guess I'll withdraw my Pull Request.

**Comment by MetaChuh** [comment]
please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins if you update from version 7.5.9 or below.
if your issue still persists, and it is still of relevance, please feel free to file a new issue as easy to understand and reproducible as possible.

thank you for your help and best regards.
