### ISSUE TITLE
Save is no longer working

### ISSUE THREAD

**Issue by JanStolze** [notepad-plus-plus/notepad-plus-plus#2513]
After the last update of Notepad++ 
I'm no longer able to save a change in a txt file.
No error appears, it does simply do nothing.
Save as is working ok.

Notepad++ v7   (32-bit)
Build time : Sep 21 2016 - 22:00:56
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : ON
Local Conf mode : OFF
OS : Windows 7
Plugins : ComparePlugin.dll JSMinNPP.dll mimeTools.dll NppConverter.dll NppExport.dll NppFTP.dll NppTextFX.dll PluginManager.dll SpellChecker.dll XMLTools.dll

**Comment by cmeriaux** [comment]
clean your config.xml in application/roaming . It might be corrupted

**Comment by JanStolze** [comment]
Yes that fixed it alright.
Thanx.

**Comment by cmeriaux** [comment]
just in case, can you provide me the corrupted config.xml ?

**Comment by dail8859** [comment]
Most likely the same bug as #2346.

**Comment by JanStolze** [comment]
Yes it contained a non-existing backup dir.
