### ISSUE TITLE
Notepad++ doesn't save documents after last update

### ISSUE THREAD

**Issue by AlpDmr** [notepad-plus-plus/notepad-plus-plus#2515]
### Steps to Reproduce the Issue

1. Open a file
2. Edit
3. Press CTRL+S or floppy icon

### Expected Behavior

Save the file and red floppy icon becomes green
### Actual Behavior

Files don't changed, floppy icon is still red and there is no any warning on exit 
### Debug Information

I tried to disable auto-backup feature but there is no chance
Saving same files with "Save As" option is working.

**Comment by RutgerM** [comment]
Try this solution: https://github.com/notepad-plus-plus/notepad-plus-plus/issues/2513#issuecomment-257821743 :)

**Comment by dail8859** [comment]
Most likely same bug as #2346

**Comment by AlpDmr** [comment]
7.2 version is working as expected.
