### ISSUE TITLE
"Find in Files" dialog should be resizable

### ISSUE THREAD

**Issue by vlakoff** [notepad-plus-plus/notepad-plus-plus#2516]
The Ctrl+F dialog "Find in Files" dialog isn't resizable, despite it has a resize handle at bottom right.

When I try to use this handle, the dialog doesn't change size (by the way, it produces a bit of "flashing", like some resizing was happening but immediately reset).

It would be great to be able to resize this dialog, possibly the current size becoming a "minimum size" instead.

Use case: I frequently use long directory name and it would be very helpful to see them entirely.

**Comment by persona5** [comment]
+1
