### ISSUE TITLE
Custom Backup Directory no longer supports environment variables

### ISSUE THREAD

**Issue by m-wim** [notepad-plus-plus/notepad-plus-plus#2520]
### Description of the Issue

Setting the Custom Backup Directory using an environment variable like "%TMP%\..\backups\" does not work any more - it did in V6.*
If I try to save a file I get the following warning dialog:
---------------------------
File Backup Failed
---------------------------
The previous version of the file could not be saved into the backup directory at "%TMP%\..\backups\name.2016-11-03_120930.bak".

Do you want to save the current file anyways?
---------------------------
Yes   No   
---------------------------

### Steps to Reproduce the Issue

1. Just set the Custom Backup Directory  to %TMP%\..\backups\
2. Make sure that the folder exists
3. 

### Expected Behavior

Environment variables should be evaluated if given in the name of the Custom Backup Directory. (If the folder does not exist, it should be tried to create it?)

### Actual Behavior

A warning dialog appears, see description

### Debug Information

Notepad++ v7.2   (32-bit)
Build time : Nov  2 2016 - 11:26:20
Path : D:\_\Tools\NotePad++\notepad++.exe
Admin mode : ON
Local Conf mode : ON
OS : Windows 7
Plugins : mimeTools.dll NppConverter.dll NppExec.dll NppExport.dll NppTextFX.dll PluginManager.dll SpellChecker.dll WindowManager.dll XMLTools.dll

**Comment by donho** [comment]
@dail8859 is this regression is related to the commit:
https://github.com/notepad-plus-plus/notepad-plus-plus/commit/a82d9f9981271ae5230e145d8fdc5e86e6a6a42d
?

**Comment by dail8859** [comment]
@donho Yes most likely. I'm assuming SHCreateDirectory() doesn't handle environment variable expansion by default. I think using ExpandEnvironmentStrings() should fix it. I will look into this.

**Comment by dail8859** [comment]
@m-wim When you say set it to `%TMP%..\backups\` this would expand out to

> C:\Users\username\AppData\Local\Temp..\backups

Notice no backslash between `Temp` and `..`. Is this a typo in the bug report or is this the exact path you used previously?

**Comment by SinghRajenM** [comment]
@dail8859 , I doubt that this regression happened because of [a82d9f9](https://github.com/notepad-plus-plus/notepad-plus-plus/commit/a82d9f9981271ae5230e145d8fdc5e86e6a6a42d) as this issue can be seen with V7.1 also.

In V6.9.2, code was like
``` C++
::CopyFile(fn, fn_dateTime_bak.c_str(), FALSE);
```
which was changed to (may be v7.0)
``` C++
if (not ::CopyFile(fn, fn_dateTime_bak.c_str(), FALSE))
{
	return false;
}
```
because of this save (actual file save, not backup) didn't happen as doSave was not called. However, save backup with environment variable is not working with 6.9.2 also (even is %temp/backups directory exists), but it does not block the saving actual file. 

So I feel expanding environment variable is must.

**Comment by dail8859** [comment]
@SinghRajenM Good point. So most likely the commit *revealed* the problem as opposed to introducing a new problem.

I will submit a PR soon which expands the environment variables.

**Comment by m-wim** [comment]
Sorry, the \ behind % got lost. I have it there: %TMP%\..\backups\

**Comment by dail8859** [comment]
@m-wim Thanks for the info! Just wanted to make sure :)
