### ISSUE TITLE
Smart Highlight color appears dull on a black/dark background

### ISSUE THREAD

**Issue by ejwcobra** [notepad-plus-plus/notepad-plus-plus#2521]
### Description of the Issue
When using a black or other dark background, the Smart Highlighting colour is very dim even when the Smart Highlighting colour is set to a bright colour such as bright yellow or bright red.  It appears that the Smart Highlighting colour that is applied does not have full opacity.
![npp - dim smart highlight](https://cloud.githubusercontent.com/assets/23238977/19968727/cd8a5890-a1a3-11e6-816a-762c4db553a1.png)

Additionally, I noticed that the Smart Highlighting colour is somehow overlaid over the colour of the selected word.  This isn't really a problem for me, but I figured I'd point it out since it might be related.  Note the yellow border.
![npp - overlay](https://cloud.githubusercontent.com/assets/23238977/19968733/d3647b6a-a1a3-11e6-8a3d-bb48d2e48e4a.png)

Notepad++ version: 6.9.2

### Steps to Reproduce the Issue
Dim Smart Highlighting
1. Open Settings > Style Configurator
2. Select Global Styles > Default Style and set it to black
3. Select Global Styles > Smart Highlighting and set it to bright yellow (RGB 255,255,0)
4. Start a new document and type some words (e.g. "abc abc abc").
5. Double-click to select one of the words.  Note that the other words are a dim yellow.

Smart Highlighting colour overlaid over selected text highlight
1. Open Settings > Style Configurator
2. Select Global Styles > Default Style and set it to black
3. Select Global Styles > Smart Highlighting and set it to bright red (RGB 255,0,0)
4. Select Global Styles > Selected Text Colour and set it to bright yellow (RGB 255,255,0)
4. Start a new document and type some words (e.g. "abc abc abc").
5. Double-click to select one of the words.  Note that the selected word has a yellow border, but the word itself has an orange highlight (mixture of the Smart Highlighting colour and the Selected Text Colour).

### Expected Behavior
I expected the Smart Highlighting colour to be the exact colour I selected in the Style Configurator.

### Actual Behavior
The Smart Highlighting colour is a dim shade of the actual Smart Highlighting colour I selected in the Style Configurator.

**Comment by dail8859** [comment]
You are correct they do not have full opacity. In some cases if it was full opacity it makes text hard or impossible to see. Overlapping of these can also give a mix of the colors as you are seeing.

**Comment by ejwcobra** [comment]
As far as I can tell, every other style in the style configurator (e.g. "Brace highlight style", "Current line background", "Selected text colour", etc, etc) is applied at full opacity.  For the "Smart Highlight" style to use less than 100% opacity is inconsistent with how every other style operator works and is confusing and frustrating to the user.  While it is true that full opacity on words highlighted by the Smart Highlight feature could make them difficult to read, that could be true in many other instances other than Smart Highlighting.  For example, using a bright colour for the "Current line background" on a dark background with white text would make the current line very hard to read.  The issue in this example isn't a problem with how Notepad++ is applying the colours; it is a style configuration problem.  Similarly, if the Smart Highlighting colour is applied with full opacity, any reading difficulty is a style configuration issue.

Given the above, I'd again like to put forth that the Smart Highlight color should be applied at full opacity.

**Comment by dail8859** [comment]
> As far as I can tell, every other style in the style configurator (e.g. "Brace highlight style", "Current line background", "Selected text colour", etc, etc)

These work differently from the smart highlighting.

>  I'd again like to put forth that the Smart Highlight color should be applied at full opacity.

This would cause more problems for others than it would solve. Adding it to the GUI to allow the user to adjust it wouldn't be a bad idea though. 

Alternatively you could install a plugin to give you access to these settings and adjust them however you like.

**Comment by ejwcobra** [comment]
> Adding it to the GUI to allow the user to adjust it wouldn't be a bad idea though.
Adding a slider for the Smart Highlight opacity would solve this perfectly, and wouldn't be a breaking change for existing users.  I'm assuming this would go in Settings > Preferences > MISC > Smart Highlighting.

You mentioned a plugin to adjust this setting.  I've looked through the plugin list and haven't seen anything that sounds like it would do this.  Was there a specific plugin you were thinking of?

**Comment by dail8859** [comment]
You can do it with some of the scripting plugins. For example install LuaScript, edit it's startup script and add this:

```lua
editor1.IndicAlpha[29] = 255
editor2.IndicAlpha[29] = 255
```

FYI 29 is the internal number Notepad++ uses for it's smart highlighter style.

**Comment by ejwcobra** [comment]
Thanks, this works as a temporary work-around.

**Comment by MetaChuh** [comment]
please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins if you update from version 7.5.9 or below.
if your issue still persists, and it is still of relevance, please feel free to file a new issue as easy to understand and reproducible as possible.

thank you for your help and best regards.
