### ISSUE TITLE
Function names not display correctly in Function list for PHP, C and C++

### ISSUE THREAD

**Issue by dknippers0** [notepad-plus-plus/notepad-plus-plus#2522]
Function names that start with 'if', 'while', 'for' or 'switch'
in PHP, C and C++ do not show up in the Function List.

### Steps to reproduce:
- Open any PHP, C or C++ source file with function names prefixed with 'if', 'while', 'for' or 'switch'
- Display Function List

### Expected behaviour
- Have all function names in Function List

Fixed this by changing regex at #2523

**Comment by vlakoff** [comment]
Also reported in #981, #1103…

**Comment by donho** [comment]
https://github.com/notepad-plus-plus/notepad-plus-plus/commit/60b4aa6b75c60b436d1f3a539cd75956fbb98b3e
