### ISSUE TITLE
Very large file - Insert characters very slow

### ISSUE THREAD

**Issue by dnarmitage** [notepad-plus-plus/notepad-plus-plus#2531]
### Description of the Issue
When editing a very large CSV to add headers noticed that every time a character is inserted, takes a couple of seconds before UI responds again - file is almost 3m lines with 167m characters.
Inserting new lines seems OK, deleting characters is OK but inserting a character anywhere causes same slowdown.
Note - Typing text in another window, then copying and pasting in is actually normal, hugely faster than typing. 
### Steps to Reproduce the Issue
1. Load very large file
2. Insert new line at top
3. Type some characters and wait

### Expected Behavior
To be as quick as previous versions

### Actual Behavior
Each character is accompanied by a very significant delay of multiple seconds

### Debug Information
Notepad++ v7.1   (32-bit)
Build time : Oct 15 2016 - 23:30:30
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10
Plugins : mimeTools.dll NppConverter.dll NppExport.dll NppFTP.dll NPPJSONViewer.dll NppTextFX.dll PluginManager.dll Tidy2.dll XMLTools.dll

**Comment by marshall-ucsd** [comment]
I can confirm this issue remains in **7.5.4 (64-bit)** - trying to do the exact same thing as the original reporter, with a 19M-line (771MB) data file. The edits _do_ show up (eventually).

**Comment by MetaChuh** [comment]
please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins if you update from version 7.5.9 or below.

if you use very large files, please use the 64 bit release, disable word wrap and disable any spell checkers that might be active.

thank you for your help and best regards.
