### ISSUE TITLE
Crash/Bug - Right-click + Mouse Wheel document switching multiple lists

### ISSUE THREAD

**Issue by al2k4** [notepad-plus-plus/notepad-plus-plus#2534]
### Description of the Issue
When scrolling through documents using right-click and the mouse wheel, it will open lists repeatedly on each scroll when your cursor is not over the list, and if I do it enough times, it will crash eventually when too many lists are open. Each overlapping list requires a selection or right-click to close.

### Steps to Reproduce the Issue
1. Use right-click and wheel to open up list.
2. Move mouse cursor outside of the list.

### Expected Behavior
1. Scroll using the mouse wheel, no overlapping lists will open.
2. Select a document and list will close.

### Actual Behavior
1. Scroll using the mouse wheel - overlapping lists will open.
2. Selecting a document will select a document, but the other overlapped lists will still be visible. This requires multiple selects or enough right-clicks outside of the list to close them all. Sometimes an invisible list will still be open, requiring another right-click to close, otherwise more lists will open on scroll.
3. Too many scrolls/lists open will crash the entire application.

### Debug Information

Notepad++ v6.9.2
Build time : May 18 2016 - 00:34:05
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10
Plugins : none

Screenshot of overlapping lists: https://al2k4.s-ul.eu/Tp8M2K54
Screenshot of crash: https://al2k4.s-ul.eu/g2IKKs62

**Comment by CookiePLMonster** [comment]
Cannot reproduce anymore. @donho - close?

**Comment by MetaChuh** [comment]
please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins if you update from version 7.5.9 or below.
if your issue still persists, and it is still of relevance, please feel free to file a new issue as easy to understand and reproducible as possible.

thank you for your help and best regards.
