### ISSUE TITLE
Change timezone - Notepad acting crazy

### ISSUE THREAD

**Issue by kloentje2** [notepad-plus-plus/notepad-plus-plus#2535]
When I change my timezone, Notepad++ asks me on every file to reload it because another program has modified it.

Ik except notepad to continue with his current work, because I am working on a big project I have a lot of code open.

### Debug Information
Notepad++ v6.9.1
Build time : Mar 28 2016 - 19:48:40
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10
Plugins : mimeTools.dll NppConverter.dll NppExport.dll NppFTP.dll PluginManager.dll

**Comment by dail8859** [comment]
Duplicate of #215

**Comment by fplatel** [comment]
I have the same issue : I travel a lot for my job, and I don't often shutdown my laptop : I only use hibernation. Each time I change my timezone, notepad++ ask me to reload each file, I suppose it sees that the local time for last modified is different, it should perform checking against universal time, not local time.
