### ISSUE TITLE
bug for find in page

### ISSUE THREAD

**Issue by farshadsharifjob** [notepad-plus-plus/notepad-plus-plus#2536]
when you search for a capital  word by small letters, if you search it in current document, you can not find it
but when you search in all opened documents , it can find it

**Comment by dail8859** [comment]
Works fine for me. Please provide a set of reproducible steps and your debug info if it still occurs.

**Comment by farshadsharifjob** [comment]
Works fine for me. Please provide a set of reproducible steps and your debug info if it still occurs.

**Comment by farshadsharifjob** [comment]
Works not fine for me. Please provide a set of reproducible steps and your debug info if it still occurs.
