### ISSUE TITLE
Shortcut not working as expected.

### ISSUE THREAD

**Issue by roizpi** [notepad-plus-plus/notepad-plus-plus#2537]
### Description of the Issue
The shortcuts `ctrl+shift` and `ctrl+shift+tab` are not standarized. I mean, in other programs (such web navigators or IntelliJ) it works in a more comfortable way.

### Steps to Reproduce the Issue
1. Open 7 tabs at NotePad++.

2. Try to select with this shortcut the second closest file (forwards or backwards) to the one you are visualizing (if it works as you expected, select manually (click) another file and proceed in the same way, it may behave in a different way).

3. To complicate the issue, move manually (with the mouse) the tabs around, in this way it is impossible to guess how to get the tab located 3 positions further, without paying a lot of attention.

### Expected Behavior

Accordingly with other programs, if you shift the tabs (files) in this way, you should get any file in a fast way depending on how many times you have pressed the `tab` key, so that everytime you press it you add 1 to the "array" pointer, on the other hand if you press `shift` as well, you substract 1 to the "array" pointer allowing to shift positions backwards.
Furthermore the graphical interface when pressing this shortcut is confusing, because you get lost with the full paths, reading from left to right you take a lot of time to find the file name (IntelliJ doesn't show paths). 

### Actual Behavior
It is hard to get used to how it works, specially when you rearrange the tabs, if you do so, you can't expect how to obtain one of your files if it is +4 positions away.
If you are using 9 files I forget about using this functionallity.

### Debug Information

![Here is a screenshot](https://gyazo.com/a28937235d46e54307ee94dc695757cc)

~~

I hope someone is feeling the same as me when using this functionallity.

Kind regards,
Rodrigo Izquierdo.

**Comment by krilbe** [comment]
The behavior you want is on Ctrl+PgUp/PgDn. The behavior in NP++ for Ctrl+Tab/Ctrl+Shift+Tab is, I think, consistent with Visual Studio: The first Ctrl+Tab gets you to the most recently used (MRU) tab (the one you were on before switching to the current one. Hit Ctrl+Tab+Tab (i.e. twice) you get the next tab in MRU order. Holding Shift also moves you backwards in the "MRU order".

I personally would prefer to have the behavior you request, so I always use Ctrl+PgUp/PgDn instead. But having both variants means Ctrl+PgUp/PgDn is not available for the feature I would want it for: Jump to top of view/bottom of view, as in Visual Studio. I really miss that feature in NP++.

**Comment by Ekopalypse** [comment]
imho can be closed, current version and reconfiguration of shortcuts seems to do what is expected

**Comment by MetaChuh** [comment]
please go to `settings > preferences > misc` and disable `document switcher`.

once disabled, both <kbd>Ctrl</kbd>+<kbd>PgUp</kbd> / <kbd>Ctrl</kbd>+<kbd>PgDn</kbd> and <kbd>Ctrl</kbd>+<kbd>Tab</kbd> / <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>Tab</kbd> will be used to bring the next tab or previous tab into focus.

if your notepad++ behaves differently, please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins if you update from version 7.5.9 or below.

thank you for your help and best regards.

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
(no extra account is needed, just use your github account to sign in)
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)

**Comment by roizpi** [comment]
@krilbe In the current version I feel the usage of ctrl+tab is totally standardized. I am happy as it works now.
I remember how it worked back in the days and was really hard to get used to it.
@Ekopalypse @MetaChuh 

Now the behaviour is fixed. Thanks.
