### ISSUE TITLE
WordWrap Issue with Compare Plugin

### ISSUE THREAD

**Issue by bineshdobhal** [notepad-plus-plus/notepad-plus-plus#2538]
### Description of the Issue
Word wrap disable after file compare

### Steps to Reproduce the Issue

1. Word wrap text 
2. Compare Files with Alt+D
3. Press Ctrl+Alt+D to Clear results 

### Expected Behavior
Text Should be still word wrapped after clearing results. 

### Actual Behavior

Word Wrap disabled

**Comment by dail8859** [comment]
Since this is a 3rd party plugin you need to report it to that project.
