### ISSUE TITLE
word search issue

### ISSUE THREAD

**Issue by rahulsavan** [notepad-plus-plus/notepad-plus-plus#2540]
### Steps to Reproduce the Issue

<div id="extr-page">
	

<div id="main" role="main"  class="myLogin">

		
		
		<div id="content" class="container">
			<div class="row">
				
				
				<div class="col-xs-12 col-sm-12 col-md-7 col-lg-5">
					
					<div class="well no-padding">

						<form id="register-user" class="smart-form client-form">
							
							
							
							<footer>
								
								<div></div>
								
				
							</footer>

							
						</form>

					</div>
					
				</div>
			</div>
		
		
	
		
		
		
		</div>

	

	
</div>
</div>

### Expected Behavior
<div
</div count should match

<div = 7
</div = 6
### Actual Behavior
<div = 7
</div = 7

<div = 7
</div = 6
### Debug Information

ctrl + F  ---> find all in current document

**Comment by SinghRajenM** [comment]
Given sample does not have **--->**, rather it is **-->** which is working absolutely fine. Moreover, using proper error reporting template (along with screenshot if possible) might give clear picture.
