### ISSUE TITLE
official git plugin

### ISSUE THREAD

**Issue by amin007** [notepad-plus-plus/notepad-plus-plus#2542]
Hi. Right now i use un official git plugin from https://forum.lowyat.net/topic/1358320/all

I have google to find a similar git 

my server cannot support TortoiseGit-2.2.0.0-3

Thank you

**Comment by amin007** [comment]
what i mean is any plugin git for notepad++?

**Comment by dail8859** [comment]
Try using Google to see what you can find. Looks like you already found one.
