### ISSUE TITLE
Hidden attribute hinders HTML 

### ISSUE THREAD

**Issue by wargwargwarg** [notepad-plus-plus/notepad-plus-plus#2543]
### Description of the Issue
Notepad++ started about a month ago to change/differentiate some subtle quality of text, resulting in the HTML code being executed in a weird way.
I've saved an example of this: 2 small tables, apparently identical but which execute completely different.
Look at the first td row in both cases, they are written differently, the first executes ok, the second not.
I've tried copy paste in another html, copy paste to notepad (to loose hidden attributes).

The code in the second table is assembled by a macro in a long list. I've used this macro for 2 years, even yesterday it worked ok, on the same station. It happened also 2 weeks ago.

I am out of idees, Please help.

### Steps to Reproduce the Issue

1.  just run the attached file
2. 
3. 

### Expected Behavior
2 identically formatted rows

### Actual Behavior
the second row has altered structure, color, layout

[BAD.zip](https://github.com/notepad-plus-plus/notepad-plus-plus/files/577289/BAD.zip)

**Comment by dail8859** [comment]
This is not a Notepad++ related issue. (hint) You'd be surprised how easy you can find problems just by looking at syntax highlighting.
