### ISSUE TITLE
Can't select text properly after using links

### ISSUE THREAD

**Issue by mlatushko** [notepad-plus-plus/notepad-plus-plus#2547]
1. Follow any link like
**https://notepad-plus-plus.org/fr/contribute/ text text**
2. Return focus to Noteped's window (previously) or select any text at once

**Comment by dail8859** [comment]
@mlatushko Do you mean click and drag to select text or double click? Or what exactly?

**Comment by mlatushko** [comment]
Yes, I mean selecting with double click after notepad++ loses the focus
