### ISSUE TITLE
Status of Read Only files is ignored on Session Save/Load operations

### ISSUE THREAD

**Issue by terablade2001** [notepad-plus-plus/notepad-plus-plus#2548]
### Description of the Issue
Status of Read-Only marked files seems not to be saved when a session is saved into a file. Thus the next time the client is load a session from a file, all Read-Only files will be editable again!

### Steps to Reproduce the Issue
1. Create a new file, add some text to it and save it somewhere.
2. Set Read-Only status: Edit->Set Read-Only. Now the file can not be edited.
3. Save the current session from File->Save Session... somewhere in your disk.
4. Close notepad++ and reopen it.
5. Load the previous saved session from File->Load Session... and select the session file which was used before.

### Expected Behavior
The file which was marked as Read-Only (step 2) should be still be marked as Read-Only and should not be able to be edited.

### Actual Behavior
The file which was marked as Read-Only (step 2), is now NOT marked as Read-Only and can be edited.

### Debug Information
Notepad++ v7.1   (32-bit)
Build time : Oct 15 2016 - 23:30:30
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : ON
Local Conf mode : OFF
OS : Windows 7
Plugins : none

**Comment by thenlich** [comment]
I agree that this behavior is unexpected. Same for "Monitoring (tail -f)" feature.
Can reproduce on:

Notepad++ v7.5.3   (64-bit)
Build time : Dec  5 2017 - 10:47:54
Path : C:\Daten\Programme\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 7 (64-bit)
Plugins : DSpellCheck.dll mimeTools.dll NppConverter.dll
