### ISSUE TITLE
Inconsistent behavior of END and SHIFT+END when line wrap is enabled (same w/ HOME)

### ISSUE THREAD

**Issue by toffeles** [notepad-plus-plus/notepad-plus-plus#255]
With word-wrap on, END moves to the furthest right location on the current *display* line.  Pressing END again moves to the end of the *actual* line.  However, with SHIFT+END, the END only does the latter: extend selection to end of the actual line.  Similarly with HOME wrt the beginning of the display/actual line.  It would be nice if the behavior was consistent for movement and for selection. 

This can be fixed with the following:
* Remove Shift+End shortcut for SCI_LINEENDEXTEND, add it to SCI_LINEENDWRAPEXTEND.
* Remove Shift+Home shortcut for SCI_VCHOMEEXTEND, add it to SCI_VCHOMEWRAPEXTEND.

Should these changes be made to the default mappings?

**Comment by dail8859** [comment]
:+1: Totally agree the behavior is inconsistent and needs changed.

**Comment by Eldaw** [comment]
I agree.

**Comment by h-h-h-h** [comment]
:+1:

**Comment by dg9ngf** [comment]
The existing mapping cannot be removed. Then I added the same hotkey to the other command. Now both commands share the same hotkey and neither can be removed again. That looks like a problem to me.
