### ISSUE TITLE
Notepad++ Updates Windows Registry and Control Panel but does not upgrade Old Software (when running) during Silent installation

### ISSUE THREAD

**Issue by wingenius** [notepad-plus-plus/notepad-plus-plus#2551]
### Description of the Issue

When you silently deploy Notepad++ (using the ‘/s’ switch in Powershell), the installer can’t seem to tell if an older version is running, so the silent installer doesn’t close the old version or throw an exception that the process is running. 
Also when you silently deploy a new version of Notepad++ while an older version is running, the Notepad++ installer updates the Registry and the Control Panel information to match the new software details but does not upgrade the program itself. This issue is present even after rebooting a machine.

(as reported https://notepad-plus-plus.org/community/topic/12659/notepad-v7-2-released/6)

### Steps to Reproduce the Issue

1. Open Notepad++
2. Open up Powershell (or ISE)
3. Enter <path to Notepad++ Installer>\npp.7.2.Installer.x64.exe '/S' 
4. Open the Registry and navigate to HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\Notepad++
5. Go to Control Panel > All Control Panel Items > Programs and Features (or win+r, appwiz.cpl) and look for Notepad++. Under "Version," you will see the latest version of Notepad++.
6. Open Notepad++ and click F1. You will notice that the version did not update, as it says on the Registry or the Control Panel.
7. Reboot your machine and redo step 6. You will notice that nothing changed.

### Expected Behavior

When running npp.7.2.Installer.x64.exe '/S', and an old version of Notepad++ is already running, the installer should detect if a process is running and throw an exception.

If a process is running, the installation should stop without changing any information. If the process is not running, the installer should continue its course. 

_Note that this issue only exists when you try to install Notepad++ SILENTLY. It does not happen if you try to use the GUI installer._ 

### Actual Behavior

When running a silent install,

1. Registry Values for Notepad++ were updated to reflect the latest version.
2. Appwiz.cpl (Control Panel - Programs and Features) was updated to reflect the latest version.
3. Notepad++ itself did not upgrade (even after a reboot).

### Debug Information

Notepad++ v7   (64-bit)
Build time : Sep 21 2016 - 22:07:28
Path : C:\Program Files\Notepad++\notepad++.exe
OS : Windows 10

**This issue can be reproduced in NPP 7.1 and 7.2.**

![image](https://cloud.githubusercontent.com/assets/23267059/20108999/2c622972-a5ac-11e6-970c-079374dcf5e5.png)

**Comment by MetaChuh** [comment]
please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins if you update from version 7.5.9 or below.
if your issue still persists, and it is still of relevance, please feel free to file a new issue as easy to understand and reproducible as possible.

thank you for your help and best regards.

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
(no extra account is needed, just use your github account to sign in)
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)
