### ISSUE TITLE
Insert Cursor Instead of Arrow in Find Dialog Box

### ISSUE THREAD

**Issue by jhframe** [notepad-plus-plus/notepad-plus-plus#2554]
### Description of the Issue

In v7.1 on Windows 10 64-bit, when in the Find dialog, after entering the desired text the cursor that appears when hovering over the various action tiles (e.g. Find, Count, Close, etc.) is an insert cursor (as though one were going to type some text) instead of a selection arrow.  The cursor works, i.e. the user can execute the desired action, but it's non-standard and disconcerting.

### Steps to Reproduce the Issue

1. Open a file.
2. Bring up the Find dialog box.
3. Enter some search text.
4. Hover the mouse over one of the action tiles.
5. Observe objectionable behavior.

### Expected Behavior

I expect to have an arrow cursor when clicking on an action tile.

### Actual Behavior

I get a text insert cursor when clicking on an action tile.

### Debug Information

Notepad++ v7.1   (32-bit)
Build time : Oct 15 2016 - 23:30:30
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : ON
Local Conf mode : OFF
OS : Windows 10
Plugins : Explorer.dll mimeTools.dll NppConverter.dll NppExport.dll PluginManager.dll

**Comment by jhframe** [comment]
Update:  the issue isn't limited to the Find dialog, it appears to affect most (if not all) of the UI.  Insert cursor instead of arrow pretty much everywhere.

**Comment by jhframe** [comment]
Update:  upon reboot, the issue went away.  It was previously observed immediately following installation of v7.1 over a prior version, but a power-cycle and reboot fixed it.

**Comment by dail8859** [comment]
Definitely sounds more Windows related and probably too minor of an issue to worry about looking into.
