### ISSUE TITLE
Requesting option to omit line numbers from Find All results

### ISSUE THREAD

**Issue by TPucke** [notepad-plus-plus/notepad-plus-plus#2557]
The result of Find All operations includes something like Line Number: 1234 on each found line.  This is nice for some use cases but I have also found it very useful to copy/paste found results into another document, or even another application for further manipulation and for that use case the added Line Number text is like pollution, and removing that is usually tedious.  I am asking for a user selectable way (e.g. checkbox or separate Find All... button) in the Find dialog box to suppress the line numbers in the results pane.  Another way would be to show the line numbers in a separate control to the left of the actual found lines, so that when I copy found lines, it will not capture prepended line numbers to the clipboard.

**Comment by cmeriaux** [comment]
it's already implemented in latest release.
Right click on the result buffer, then use copy function. It will copy only the matched strings.

Click in the buffer, do a Ctrl-A (select all), Ctrl-C then Ctrl-V in a new buffer, you'll get matched strings with line numbers
