### ISSUE TITLE
virustotal detected  npp.7.2.bin.x64

### ISSUE THREAD

**Issue by zagk** [notepad-plus-plus/notepad-plus-plus#2558]
### Description of the Issue
https://www.virustotal.com/en/file/1df2203bc55728007218b67575a8a887a4950f3c48b2fcd69197134ce0290ba7/analysis/1478830716/

Baidu 	Win32.Trojan.WisdomEyes.16070401.9500.9991 

what is that mean ? 

### Steps to Reproduce the Issue

1. 
2. 
3.

**Comment by dail8859** [comment]
Since it is just one the it's probably a false positive.
