### ISSUE TITLE
[Feature Request] Move file...

### ISSUE THREAD

**Issue by ghost** [notepad-plus-plus/notepad-plus-plus#2559]
I work with databases a lot, and when downloading [exporting] the files, I don't want to go through selecting a save location or finding the file through explorer (I often just open them through chrome, with notepad++)... I noticed that Notepad++ already contains a function to move the file to the recycle bin. So I  thought, how about a function to move the file from its current location to another?

**Comment by wnewbery** [comment]
The "Rename" menu item can change directories as well

**Comment by donho** [comment]
Use Notepad++ as editor; not as explorer
