### ISSUE TITLE
Off-by-1 error in Preferences->Language Tab Settings

### ISSUE THREAD

**Issue by olego** [notepad-plus-plus/notepad-plus-plus#2561]
### Description of the Issue
Changing Tab Settings of a language in the UI actually changes the previous language

### Steps to Reproduce the Issue
Preferences->Language, Tab Settings.  Modify C# to be "Replace by space"

### Expected Behavior
In langs.xml, "cs" is changed to tabSettings="-1"

### Actual Behavior
"cpp" is actually changed.  When I edit "cs" langs.xml, and open Preferences->Language, it's displayed as "css" being "Replace by space".  And "cpp", "cs", and "css" are all next to each other.

### Debug Information
Notepad++ v7.1   (32-bit)
Build time : Oct 15 2016 - 23:30:30
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 8.1
Plugins : JSMinNPP.dll mimeTools.dll NppConverter.dll NppExport.dll NppTextFX.dll PluginManager.dll VisualStudioLineCopy.Unicode.dll XMLTools.dll

**Comment by dail8859** [comment]
Try with v7.2 I know there was a big or two fixed related to tab settings.

**Comment by olego** [comment]
Verified fixed in v7.2.
Thanks!
