### ISSUE TITLE
[Feature Request] Improve usability in Shortcut mapper

### ISSUE THREAD

**Issue by rillig** [notepad-plus-plus/notepad-plus-plus#2563]
When editing the shortcuts using the Shortcut mapper window, the workflow feels clumsier than necessary. It could be improved using the following ideas.

## Remove the numbers column

Currently there is a number column to the left of the Name column. It's purpose is not obvious. It might be a help for remembering the current position when scrolling in the list.

Removing this column provides more space for the remaining columns.

## Make the window resizable

Currently the list has a horizontal scroll bar. When clicking to the right, the number and Name columns disappear, leaving only the Shortcut column visible. Viewing only the shortcuts doesn't make sense.

When the window is resizable, it is possible to view all columns at a time.

## Make the columns resizable

When the columns are resizable, there is no need for the horizontal scrollbar to be shown by default. Initially the Shortcut column should be as wide as necessary, and the Name column should take the rest of the space.

## Faster mouse wheel scrolling

When scrolling via the mouse wheel, each click corresponds to a change of one line. Almost all other programs scroll 3 lines per click. Scrolling only a single line makes Notepad++ feel slow.

When scrolling with the mouse wheel, each click should scroll 3 lines.

## Don't change the view when clicking in a Shortcut cell

When I click in a Shortcut cell, the list scrolls to the right, so that the Name of the command disappears. This leaves me in question which command I am actually editing.

## Provide a single shortcut edit field

When editing a shortcut, a small dialog is shown.

Consider replacing the three checkboxes and the select box with a single input field where I can enter the shortcut directly.

## Rearrange the Shortcut editing controls

When editing a shortcut, a small dialog is shown.

The name field should not be a text box, but a label, since it is not editable anyway. For the purpose of copying the command name, the label text could be selectable.

The checkboxes should be arranged in a single row instead of a triangle, since the triangle arrangement doesn't have any meaning and deviates from common layout conventions.

The checkbox labels should be renamed so that they correspond to the names in the shortcuts, i.e. `Ctrl` instead of `CTRL`.

## Easier navigation between conflicting shortcuts

When there are shortcut conflicts, these lines have a red background, and in the text field below the list, the conflicting shortcuts are listed. But there is no easy way to navigate to these conflicting shortcuts, e.g. for assigning a different key combination to them.

**Comment by MetaChuh** [comment]
please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins if you update from version 7.5.9 or below.
if your issue still persists, and it is still of relevance, please feel free to file a new issue as easy to understand and reproducible as possible.

thank you for your help and best regards.

**Comment by rillig** [comment]
I compared Notepad++ 7.6.6 to all the features that I suggested.

One of them is resolved: the window is now resizable. Everything else is still the same as before.

**Comment by sasumner** [comment]
@rillig I like that you made them all individual issues!
