### ISSUE TITLE
NPP 7.2 (x64) + CAPS LOCK & RealVNC clipboard issue

### ISSUE THREAD

**Issue by drivetheory** [notepad-plus-plus/notepad-plus-plus#2564]
### Description of the Issue
NPP++ 7.2 (x64) when used through RealVNC instead of performing copy or paste when CAPS LOCK is activated enters in EXT and SYN instead of performing copy or paste.

### Steps to Reproduce the Issue
1. Install NPP 7.2 (x64) on 'server' computer
2. Install RealVNC Server 5.3.2 on 'server' computer
3. Use RealVNC Viewer to connect to 'server' computer
4. open NPP, copy & paste text inside while CAPS LOCK is activated

### Expected Behavior
normal copy paste functionality

### Actual Behavior
copy creates EXT and paste creates SYN (see attached screenshot)

![npp 7 2 x64](https://cloud.githubusercontent.com/assets/1679773/20240784/0a4b6f7e-a8ef-11e6-95fc-bc25ab471f07.jpg)

### Debug Information
none

**Comment by MetaChuh** [comment]
please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins if you update from version 7.5.9 or below.
if your issue still persists, and it is still of relevance to you, please feel free to file a new issue as easy to understand and reproducible as possible.

thank you for your help and best regards.

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
(no extra account is needed, just use your github account to sign in)
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)
