### ISSUE TITLE
Improper text display while installing update 7.1

### ISSUE THREAD

**Issue by miguelsuddya** [notepad-plus-plus/notepad-plus-plus#2568]
### Description of the Issue
Improper symbols are displayed after the user has selected Russian or Ukrainian language to install while updating Notepad++ to version 7.1

### Steps to Reproduce the Issue
1. Open Notepad++
2.  Accept the request to update.
3. Select Ukrainian as language to install and press 'Next'.

### Expected Behaviour
Text in Ukrainian is displayed on Installer.

### Actual Behaviour
Unreadable symbols are displayed.

### Debug Information
Notepad++ v6.9.2
Build time : May 18 2016 - 00:34:05
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10
Russian localisation
Plugins : ComparePlugin.dll CustomizeToolbar.dll JSLintNpp.dll JSMinNPP.dll LanguageHelp.dll mimeTools.dll NppConverter.dll NppExport.dll NppFTP.dll NPPJSONViewer.dll nppplugin_solutionhub.dll nppplugin_solutionhub_ui.dll nppplugin_solutiontools.dll NppSaveAsAdmin.dll NppScripts.dll PluginManager.dll RunMe.dll SpellChecker.dll sql.dll switcher.dll Translate.dll 

Screenshot: 
![2016-11-14_10h29_43](https://cloud.githubusercontent.com/assets/2588495/20258904/928b62e2-aa5a-11e6-9e12-c780ce7501ca.png)

**Comment by SinghRajenM** [comment]
@miguelsuddya Issue has been fixed and fixed version will be available in next release.

**Comment by dail8859** [comment]
Closed by bd6f7b4d2093392355cf94086dee52aa0f374cc0
