### ISSUE TITLE
curly brackets auto-insert in CSS

### ISSUE THREAD

**Issue by madebycambiamentico** [notepad-plus-plus/notepad-plus-plus#257]
hi there, a simple request for a missing auto-insert (preferences/auto-completion/):
if language is JAVASCRIPT, when opening curly brackets -> enter, the cursor auto tabs a new line between the brackets. this doesn't happen if language is CSS...

Example of what happen in javascript ( | = the cursor...)

```
if{
    |
}
```

Example of what happen in css

```
.class{
|}
```

**Comment by aaaxx** [comment]
Some people, me included, prefer the closing bracket in CSS indented (same level as CSS properties), so the current behaviour works great for me. Any chance this can be customisable if it gets "fixed"?

E.g.:
```CSS
body {
font-size: 14px;
    color: navy;
}
```

**Comment by Rikk** [comment]
Fixed in v6.8 actually (even though the commit above went before 6.7.9.2).

**Comment by aaaxx** [comment]
Damn, now *I'm* buggered.

Indentation should preferably be a customizable per-language setting.

**Comment by MetaChuh** [comment]
closed due to inactivity
