### ISSUE TITLE
Disable drag-and-drop text editing (NPP v6.3 and v6.6.9)

### ISSUE THREAD

**Issue by abdekker** [notepad-plus-plus/notepad-plus-plus#2571]
### Description of the Issue
In many text editors, you can drag-and-drop text from one place in the document to another. Some user may like the feature, others (such as myself) do not and wish the feature could be disabled. Unfortunately, there does not appear to be any way to do this.

### Steps to Reproduce the Issue
1. Open any text file
2. Select some text, click and drag, then release the mouse
3. The text is cut from the original and pasted to the new location

### Expected Behavior
The ability to turn this feature off (in Settings > Preferences)

### Actual Behavior
NA

### Debug Information
NA

**Comment by animalize** [comment]
I hope to have this option as well.

**Comment by brettonw** [comment]
I select the text in code files in order to focus while reading it, and would like to turn off drag and drop as well.

**Comment by CooperLi** [comment]
ommmmmg, **3 years** later and it's still openning

**Comment by Faq** [comment]
Why this is such a big deal?

**Comment by animalize** [comment]
> Why this is such a big deal?

Sometimes the text is unintentionally dragged, causing the text to be modified.

This is fatal when dealing with important text.

**Comment by sasumner** [comment]
>This is fatal when dealing with important text.

Umm...press "undo"?

>Sometimes the text is unintentionally dragged

As a data point:  In 4 years of using Notepad++, I have accidentally done this maybe twice.  (Obviously) a n undo fixed it up straight away.

But...I'm not against an enable/disable setting for this. :)

**Comment by animalize** [comment]
> Umm...press "undo"?

Sometimes I didn't notice the drag and saved file with other changes.

So I always disable this feature in editors.

**Comment by sasumner** [comment]
>Sometimes I didn't notice the drag 

Ah...makes sense.  That's why it is best to "talk out" these issues here.  What first might seem a not-important request can be made critically-important. :)

**Comment by anthroid** [comment]
/bump

Please add this feature. I have _never, ever_ done this on purpose, and I would never edit any code this way because it's error prone. So when it happens, it's always a mistake, and I always go looking for a switch to disable it, and it's not there.

**Comment by Saurabh702** [comment]
Temporary solution : https://github.com/Saurabh702/notepad-plus-plus
(*Disables the feature permanently*)

See the StackOverflow Question [here](https://stackoverflow.com/q/20700696/10155936) for more details

**Comment by abdekker** [comment]
> > This is fatal when dealing with important text.
> 
> Umm...press "undo"?
> 
> > Sometimes the text is unintentionally dragged
> 
> As a data point: In 4 years of using Notepad++, I have accidentally done this maybe twice. (Obviously) a n undo fixed it up straight away.
> 
> But...I'm not against an enable/disable setting for this. :)

Its more of an issue if you have a sensitive touchpad or edit a lot of files.

**Comment by Saurabh702** [comment]
> Temporary solution : https://github.com/Saurabh702/notepad-plus-plus
> (_Disables the feature permanently_)
> 
> See the StackOverflow Question [here](https://stackoverflow.com/q/20700696/10155936) for more details
@abdekker , @donho  this enhancement is scintilla-dependent

**Comment by donho** [comment]
Except that Scintilla makes it optional, it cannot be supported in Notepad++.
I encourage you do the feature request in [Scintilla project](https://www.scintilla.org/)

**Comment by sasumner** [comment]
@donho said:

>I encourage you do the feature request in Scintilla project

Already there, but inactive for 12+ years:
https://sourceforge.net/p/scintilla/feature-requests/184/

**Comment by natbraun** [comment]
As per my [comment](https://sourceforge.net/p/scintilla/feature-requests/184/#2848), I am implementing this feature. In the V0, I suggest adding to Notepad++ a flag that would disable drag-and-drop in Scintilla permanently (i.e., until Notepad++ is restarted). It is still better than not having this feature at all. Later on in V1, we can tackle toggling drag-and-drop without requiring restarting Notepad++.

**Comment by natbraun** [comment]
Hi all, I implemented the required feature in Scintilla. Please see https://sourceforge.net/p/scintilla/feature-requests/184.

When Scintilla is updated, I will upload a pull request for Notepad++.

@donho could you please re-open this feature request?

Thank you!

**Comment by natbraun** [comment]
Thanks @donho! Could you please assign this feature to me? Thanks!

**Comment by donho** [comment]
@natbraun 
I can always assign this issue to you.
But the feature will be in Scintilla v5.5.9, and it is not even released yet.

**Comment by natbraun** [comment]
@donho I see Scintilla v5.5.9 and v5.6.0 have been released and https://sourceforge.net/p/scintilla/feature-requests/184 was closed. What's next?

**Comment by natbraun** [comment]
> [@donho](https://github.com/donho) I see Scintilla v5.5.9 and v5.6.0 have been released and https://sourceforge.net/p/scintilla/feature-requests/184 was closed. What's next?

Happy to contribute the change to implement drag-and-drop toggling.

**Comment by natbraun** [comment]
Here is the first draft of my PR: https://github.com/notepad-plus-plus/notepad-plus-plus/pull/17800
