### ISSUE TITLE
"Save" button and menu no longer working.

### ISSUE THREAD

**Issue by dfgshdsfh** [notepad-plus-plus/notepad-plus-plus#2572]
### Description of the Issue

Since the latest update (7.1 32bit), the "save" function is not working. This includes both the button, and "File->Save"
Clicking the button or menu results in nothing happening at all that I can tell. The file remains unchanged, and closing with will result in any changes since opening lost.

"File-Save As" DOES work as expected.

### Steps to Reproduce the Issue

1. Open file
2. Make change
3. Click save button

### Expected Behavior

The files saves

### Actual Behavior

Nothing.

Also
>What actually happend

Unless I accidentally deleted a letter, "happend" should be "happened"

### Debug Information

Notepad++ v7.1   (32-bit)
Build time : Oct 15 2016 - 23:30:30
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 8.1
Plugins : ComparePlugin.dll CustomizeToolbar.dll mimeTools.dll NppConverter.dll NppExport.dll NppFTP.dll PluginManager.dll 

Saving as while running as administrator also does nothing.

**Comment by dail8859** [comment]
Most likely the same bug as #2346 which is fixed in v7.2

**Comment by dfgshdsfh** [comment]
Ah, shoot. I thought this was the most recent update. I must have gotten mixed up when my work computer updated.

I've installed 7.2 and the problem is gone. Thanks
