### ISSUE TITLE
"stylerTheme" path: no relative path possible

### ISSUE THREAD

**Issue by JayJayJazz** [notepad-plus-plus/notepad-plus-plus#2579]
### Description of the Issue
If you select a new theme (Style Configurator), the path is stored as an absolute path in the config file. This is a problem for the portable version of NPP, because (for example) the drive letter might not be the same on all machines when placed on a USB drive.
By default all theme files are located in the "themes" subfolder of NPP, so a relative path could be:
<GUIConfig name="stylerTheme" path="themes\mytheme.xml" />

### Steps to Reproduce the Issue
1. Place NPP on a USB drive
2. Place a theme in the "themes" subfolder
3. Configure NPP to use this theme
4. Connect the USB drive to another PC or assign it a different drive letter
5. Start NPP again. It will fallback to the default theme

### Expected Behavior
The manually selected theme should be selected.

### Actual Behavior
Fallback to default theme.

### Debug Information
I think no need for this issue.

**Comment by JayJayJazz** [comment]
Already reported as:
Theme setting is not portable #1589

**Comment by clonsberry** [comment]
https://github.com/notepad-plus-plus/notepad-plus-plus/issues/9409#issuecomment-1298496463
