### ISSUE TITLE
When NP++ crashes, it can't upload the crash dump file

### ISSUE THREAD

**Issue by GregUzelac** [notepad-plus-plus/notepad-plus-plus#258]
I like to send crash details to developers. So when NP++ crashes I always choose the option to send feedback & dump files. However, NP++ never appears to succeed at this. It displays something about error 5 (ERROR_ACCESS_DENIED??). Suggestions? I'm fluent with the likes of ProcMon, FileMon, and WinDbg.

**Comment by milipili** [comment]
From my point of view, I would prefer a description to reproduce the bug.
