### ISSUE TITLE
Display BOMs when Showing All Characters

### ISSUE THREAD

**Issue by bjartur** [notepad-plus-plus/notepad-plus-plus#2581]
### BOMs are invisible, even when "Show All Characters" is checked
While Unicode are not supposed contain a byte-order mark (BOM) except possibly as a first "character," malformed Unicode files might contain BOMs. For example, concatenated UTF-8-BOM files may incorrectly each start with a BOM.

This can be of interest to powerusers of Notepad++ (such as programmers). Spurious BOMs can cause unwanted behaviour in other programs. Usually, unwanted invisible characters can be found in Notepad++ by Checking View→Show Symbol→Show All Characters. This setting should toggle the display of BOMs as well.

### Steps to Reproduce the Issue
1. Create or obtain two UTF-8-BOM encoded files, a-bom.txt and nother-bom.txt.
2. In a CLI shell, `cat a-bom.txt nother-bom.txt > third-bom.txt` and open third-bom.txt in Notepad++. Or else find a way to copy a string containing a BOM into a new Notepad++ window.
3. Check (if unchecked) View→Show Symbol→Show All Characters.

### Expected Behavior
The BOM separating the two files shold be displayed in a gray box, just like NL would be. Showing the BOM at the start of the file would be nice as well.
### Actual Behavior
The BOM is present and can be selected, a caret can be positioned to the left side of a BOM and repositioned to the right by pressing the right arrow button. But it is considered a normal yet invisible character. It is even considered a part of the adjacent or surrounding word. Try typing a word adjacent to a BOM and retyping it elsewhere. Double-clicking the word adjacent to a BOM will not highlight any words not adjacent to a BOM.

Issue #1083 is most likely caused by this UI bug.

**Comment by dail8859** [comment]
A BOM is no longer a BOM if it is not at the beginning of a file.

**Comment by J0s3f** [comment]
But no matter what it is (probably garbage), it should be visible in Notepad++ if "Show All Characters" is enabled.

**Comment by gstavi** [comment]
So more generally this request should be 'don't have invisible characters when 'Show All Characters' is enabled.
In fact even without 'show all chars' invisible characters are bad business and should probably be shown somehow like symbols without a match in current font.
Not sure but I think this should be a request from Scintilla rather than NPP.

**Comment by wernerschka** [comment]
I totally support the solution of this issue: please make all unprintable Characters visible (including BOM-characters at the beginning of an UTF8-BOM file) if we turn on "Show all Characters"

**Comment by gstavi** [comment]
In my opinion first BOM at the beginning of the file should not be shown because it is not part of the document. It is something that is added automatically on 'save' and skipped automatically on 'open'.

**Comment by dail8859** [comment]
This discussion would probably be better to have on the Scintilla sourceforge page or mailing list, since there's not much N++ can do directly if Scintilla doesn't support some functionality.

**Comment by gstavi** [comment]
I started posting a ticket in Scintilla forum and decided to test it before posting.
So Notepad++ (and Scintilla) does show a middle BOM as an invalid char (which the font does not recognize). You can copy paste the BOM into the find dialog to find additional BOMs.
So while it may be nice to have to add BOM as special character I don't think it is worth the effort.

**Comment by jabcreations** [comment]
There are different types of byte order marks hence bjartur's request in the context of show all characters is correct.

https://en.wikipedia.org/wiki/Byte_order_mark#Byte_order_marks_by_encoding

**Comment by MetaChuh** [comment]
notepad++ is a text editor.
please use a hex editor to see bom.

thank you for your help and best regards.
