### ISSUE TITLE
Weird font/overlapping characters/unicode glitch depending on caret position

### ISSUE THREAD

**Issue by lgarczyn** [notepad-plus-plus/notepad-plus-plus#2582]
Can't really describe what happens, but it's _ugly._

1) Paste the following text without the into a new file:
"aaaaaaaaaaaabbbbbb(aaaaaaaaaaaaaaa)﻿"

(do copy-paste it, this is likely due to some invisible unicode characters)

2) Set the language to YAML. The bug persists on most, but not all languages.

3) Place the cursor at the end of the line, then go back one char.

4) Characters now overlap in an ugly mess.

I got into this mess by pasting comments from YouTube, would not recommend. The weird unicode thing survives being copy-pasted just about anywhere. Now I know rendering unicode can be a bitch, but I don't think caret position should affect it.

Notepad++ v7   (32-bit)
Build time : Sep 21 2016 - 22:00:56
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10
Plugins : mimeTools.dll NppConverter.dll NppExport.dll PluginManager.dll 
[bug.txt](https://github.com/notepad-plus-plus/notepad-plus-plus/files/601134/bug.txt)

**Comment by iegik** [comment]
OS: Windows 10
The wrong caret position in word `НОМЕНКЛАТУ́РА` in Notepad++ app:
![](http://joxi.ru/52abw49CG5xX0A.png)

**Comment by lgarczyn** [comment]
Reproduced with "НОМЕНКЛАТУ́РА" on:

Notepad++ v7.3.3   (32-bit)
Build time : Mar  8 2017 - 03:37:37
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10 (64-bit)
Plugins : mimeTools.dll NppConverter.dll NppExport.dll PluginManager.dll

**Comment by iegik** [comment]
https://github.com/ajaxorg/ace/issues/2548

**Comment by MattPaint** [comment]
boi

**Comment by lgarczyn** [comment]
Yeah... I should probably check if the bug is still there, will update in the afternoon.

**Comment by lgarczyn** [comment]
First bug is fixed, other is a duplicate of ajaxorg/ace#2548, marking as closed
