### ISSUE TITLE
Function list panel : small icon with UI scaling for high-resolution desktop displays

### ISSUE THREAD

**Issue by Cyrillev91** [notepad-plus-plus/notepad-plus-plus#2586]
### Description of the Issue
Function list panel : small icon with UI scaling for high-resolution desktop displays
Relative issue for other part of ui #629

### Steps to Reproduce the Issue
1. Open C++ source File (or other file with existing "function list" feature)
2. Open Function List Panel : View >> Function List
3. Icon in Function List Panel are very small (sort icon, update icon, + icon, - icon, file icon, class icon, function icon)

### Expected Behavior
"normal" size icon

### Actual Behavior
![functionlistsmallicon4k](https://cloud.githubusercontent.com/assets/12849364/20454558/a8ee1a6e-ae44-11e6-8633-c82766a255df.jpg)

### Debug Information
Notepad++ v7.2   (32-bit)
Build time : Nov  2 2016 - 11:26:20
Path : E:\Code\Notepad++Portable_7.2\App\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : ON
OS : Windows 10
Plugins : mimeTools.dll NppConverter.dll NppExport.dll PluginManager.dll

**Comment by MetaChuh** [comment]
please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins if you update from version 7.5.9 or below.
if your issue still persists, and it is still of relevance, please feel free to file a new issue as easy to understand and reproducible as possible.

thank you for your help and best regards.

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
(no extra account is needed, just use your github account to sign in)
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)
