### ISSUE TITLE
Style Configurator setting

### ISSUE THREAD

**Issue by sdarwin** [notepad-plus-plus/notepad-plus-plus#2589]
Hi,

This is a small "feature request".

If you go to Settings -> Style Configurator -> bash -> HERE DELIM and HERE Q

The color scheme is red on blue, or blue on red. With an otherwise white background page, this red/blue set of colors is jarring to the eyes, and it is not easy to read because of lack of contrast between the letters and the background.  Could it just be purple on white, or gray on white?

Checking many other languages in the Style Configurator (Javascript, Ruby, Python, and so on), almost no styles exist which are like this. In almost every case, the good sense has prevailed to have a legible color on a plain background. For every style. 

Yes, it can be changed by the end-user. But having reasonable default values is always a good idea. Also, in this particular case, there is a project whereby the customer may be called upon to review a "HERE DELIM" section, and it would be convenient if it "just worked", rather than have to be customized.

**Comment by MetaChuh** [comment]
please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins if you update from version 7.5.9 or below.
if your issue still persists, and it is still of relevance to you, please feel free to file a new issue as easy to understand and reproducible as possible.

thank you for your help and best regards.

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
(no extra account is needed, just use your github account to sign in)
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)
