### ISSUE TITLE
Blinking cursor position is confusing

### ISSUE THREAD

**Issue by rook747** [notepad-plus-plus/notepad-plus-plus#259]
The blinking cursor always stays in front of the "(" or on top of it. 
This is very confusing, any way to fix this ?

![select-cursor-issue-example2](https://cloud.githubusercontent.com/assets/12961985/8247458/a25f7936-1651-11e5-8b3d-ee18bce0d710.gif)
![select-cursor-issue-example1](https://cloud.githubusercontent.com/assets/12961985/8247457/a25d940e-1651-11e5-9665-c42e3a6d35ec.gif)

**Comment by milipili** [comment]
With another font ?
