### ISSUE TITLE
config.model.xml

### ISSUE THREAD

**Issue by krugiesv** [notepad-plus-plus/notepad-plus-plus#2590]
### Description of the Issue

Due to this being more a latley missing feature than a bug, it wouldn't make sense to follow the template.
In an professional environment, where the software is deployed centrally, it seems no longer possible to disable the auto update by manipulating the config.model.xml, because it doesn't exist anymore from version 7.2 onwards. The issue about is, that we would like to deploy it preconfigured to prevent userinteractions with the update/install process.
So there still may be an solution i didnt' figure out yet. maybe its possible to preconfigure the unattanded install, so the auto update never gets installed.

Thanks for looking into it,
krugiesv
### Steps to Reproduce the Issue

1. 
2. 
3.

**Comment by igpit** [comment]
+1 for a need to disable automatic update upon installation. 

any workaround found? (deleting "%programfiles%\Notepad++\updater" doesn't really seem like a good idea). 

as far as i understand the "%AppData%\Notepad++\config.xml" is generated per user, any way to set the defaults globally?

**Comment by krugiesv** [comment]
Since Version 7.5 there is a build in switch, so the updater doesn't get installed. 
https://notepad-plus-plus.org/download/v7.5.html
Under section: "Notepad++ v7.5 new features and bug-fixes:"

**Comment by igpit** [comment]
yeah, but that means there is no way for a user to do an update on-demand either. 

imho what should be implemented, is 
a) role out the updater, but have it silent/passive by default. if a user should have local admin rights, he can update as needed
b) in general: enable admin to supply default values during installation to be used when generating config.xml for each user upon first startup

**Comment by MetaChuh** [comment]
please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins if you update from version 7.5.9 or below.
if your issue still persists, and it is still of relevance to you, please feel free to file a new issue as easy to understand and reproducible as possible.

thank you for your help and best regards.

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
(no extra account is needed, just use your github account to sign in)
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)
