### ISSUE TITLE
[Enhancement] Use the better windows save window instead of the current horrible one

### ISSUE THREAD

**Issue by mzso** [notepad-plus-plus/notepad-plus-plus#2593]
Hi!

Np++ uses the annoying, cumbersome save window, which lacks both the favorites/my-computer/etc section at the side, the breadcrumbs and the searchbar. All of which makes life easier.

Here is what I mean by the "better" save window:
![save-window](https://cloud.githubusercontent.com/assets/4479090/20518280/e5829520-b09e-11e6-877f-6cca7f4ae341.PNG)
(via paint.net)

**Comment by redmanmale** [comment]
@mzso
In NPP 7.2.2 Save Window looks good (just like on this screenshot). What version are you running?
Maybe this issue is stale.

**Comment by PauloFrancaLacerda** [comment]
NP++ v7.31
![capture](https://cloud.githubusercontent.com/assets/17791112/22703692/c726475c-ed43-11e6-9b7a-32f3cfb4c5d1.png)

**Comment by mzso** [comment]
[**@redmanmale**](https://github.com/redmanmale) commented on [2017. febr. 7. 16:47 CET](https://github.com/notepad-plus-plus/notepad-plus-plus/issues/2593#issuecomment-278040149 "2017-02-07T15:47:24Z - Replied by Github Reply Comments"):
> [@mzso](https://github.com/mzso)  
> 
> In NPP 7.2.2 Save Window looks good (just like on this screenshot). What version are you running?  
> 
> Maybe this issue is stale.

It looks like it was changed in the meanwhile. Cool.
