### ISSUE TITLE
Underline and color normal text as if it is an hyperlink 

### ISSUE THREAD

**Issue by Lenormju** [notepad-plus-plus/notepad-plus-plus#2594]
### Description of the Issue

When typing some text while the cursor is hovering above an hyperlink that is located after the text being wrote, the text is visibly treated as an hyperlink.

### Steps to Reproduce the Issue

1. Open a new document.
2. On line 2, write : https://nodepad-plus-plus.org/
3. Go on line 1.
4. Put your mouse over the hyperlink. Do not click, just hover.
5. Write a character (whatever).
6. Write another character (whatever).
7. Write any number of characters (whatever which).

### Expected Behavior

The two characters are displayed as regular text.

### Actual Behavior

The two characters are displayed as hyperlink (colored + underlined).

### Debug Information

Notepad++ v7.2.1   (32-bit)
Build time : Nov 20 2016 - 22:42:51
Path : E:\programs\Notepad++\notepad++.exe
Admin mode : ON
Local Conf mode : OFF
OS : Windows 7
Plugins : mimeTools.dll NppConverter.dll NppExport.dll NppFTP.dll PluginManager.dll 

Screenshot of the result at step 6 : https://i37.servimg.com/u/f37/13/11/18/46/npp_bu11.png
I had the problem with NPP version 6.7 (or something like that) that I just updated to verify that the bug was still there.

**Comment by MetaChuh** [comment]
please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins if you update from version 7.5.9 or below.
if your issue still persists, and it is still of relevance to you, please feel free to file a new issue as easy to understand and reproducible as possible.

thank you for your help and best regards.

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
(no extra account is needed, just use your github account to sign in)
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)
