### ISSUE TITLE
How to avoid disabling unstable plugins during update?

### ISSUE THREAD

**Issue by effemmeffe** [notepad-plus-plus/notepad-plus-plus#260]
I use the Hex editor plugin.
Every time NPP get an update it disable that plugin due to instability, moving the file to the disabled folder.
And every time I have to move it back.
I don't know what are those instability, nor I do care.
I want to use that plugin and not being forced to fiddle with files at every upgrade.
Is there some way I can tell NPP not to disable unstable plugins?
TIA

**Comment by milipili** [comment]
Proposing a list of *invalid* plugins with checkboxes before performing the action might be a solution.

**Comment by pnedev** [comment]
@milipili, Are all plugins checked for validity and how is that accomplished if new plugins appear?

Wouldn't it be better to remove this check altogether? After all, the Plugin Manager shows the plugin stability when the user wants to install it. Also as it is now, the MultiClipboard plugin is considered to be unstable but it is actually working just fine. And there is no info why is it flagged as invalid.

**Comment by effemmeffe** [comment]
The consistency of the plugin is beyond the scope of this question, but since pnedved introduced the stability of another plugin I can add that in my experience the Hex editor plugin is completely stable, I used it a lot and never found any issue. YMMV.

**Comment by maddes-b** [comment]
The [Hex Editor plugin][1] works for me without any hassles.
I'm using [Notepad++][2] 6.8.8 with [Hex Editor][3] 0.9.5.

I only found one issue with the Hex Editor plugin, which is solvable, where Notepad++ fails to start correctly.
Notepad++ can be seen in Task Manager and that it is consuming more and more memory.
The reason for this behaviour is that the directory `%APPDATA%\Notepad++\plugins\config` is missing (e.g. for a newly created user).

To solve this:

 - End all the user's Notepad++ processes via Task Manager
 - Create the missing directory either via Windows Explorer or via the following command line<br>
`mkdir %APPDATA%\Notepad++\plugins\config`
 - After this Notepad++ will start normally again

Still it is a [bug in Hex Editor][4].
But in my point of view nothing to call the Hex Editor plugin unstable.
An option to exclude it from the "disable plugins check" of Notepad++'s installer would be great.

  [1]: http://docs.notepad-plus-plus.org/index.php?title=Plugin_Central#H
  [2]: https://notepad-plus-plus.org/
  [3]: https://sourceforge.net/projects/npp-plugins/files/Hex%20Editor/
  [4]: https://sourceforge.net/p/npp-plugins/bugs/215/

**Comment by dmmiller2k** [comment]
> The Hex Editor plugin works for me without any hassles.
> I'm using Notepad++ 6.8.8 with Hex Editor 0.9.5.

I too have been using _Hex Editor 0.9.5_ for some time, for many Notepad++ versions, going back to 5.x (maybe earlier) but now including 7.1, also no issues. Thank you, [maddes-b](https://github.com/maddes-b) for pointing out the simple solution to the one remaining issue with it.

Another plugin I depend upon which appears to be moved into the **`plugins\disabled`** directory due to some "stability issue" upon upgrading Notepad++ is [MultiClipboard](https://sourceforge.net/projects/npp-plugins/files/MultiClipboard/), which pops up a list of the 10 most recent clipboard items with the keystroke Ctrl-Shift-V, allowing one to select an item to paste. 

At one point several years ago, the then-new Plug-in Manager showed both plugins (among others) as having "some issues" in terms of stability but now shows them as "good." 

In my experience they actually are both good, so why is the Notepad++ installer still (re-)isolating them at every NPP update?  Couldn't the installer use the same plugin database as the NPP Plugin Manager?

**Comment by msdobrescu** [comment]
Well, regardless the plugin, I have 4 listed as unstable, this is highly annoying. I use them for years, so at each upgrade I have to deal with this. I accept even a question instead of notification, weather to move or not these unstable plugins, but please, do something!

**Comment by s-ne** [comment]
> PR #2752 fixes this issue.
Doesn't seem to fix anything here. A few plugins keep getting disabled every time I update, though I've never once had an issue with any of them. Please add an option to skip plugin check somewhere in the setup - anybody installing Notepad++ is sufficiently tech-savvy to figure that option out and accept the risk.

**Comment by effemmeffe** [comment]
Considering that the issue is three years old and quite a number of people has this problem I wonder what is needed for the developers to take care of it. Or, at least, mark this as won't fix and close the discussion.

**Comment by donho** [comment]
Just renaming the plugin will prevent it from being removed.

**Comment by windsurfer1122** [comment]
Really, renaming the plugin is your solution for this?

**Comment by s-ne** [comment]
Even if renaming does indeed work, I wouldn't be able to update the plugin in the update manager after that, would I? This is still breaking functionality.

**Comment by MetaChuh** [comment]
@windsurfer1122 @s-ne 

this old, outdated issue was related to version 6.8.8.

renaming .dlls, like `HexEditor.dll` is necessary for the old installer versions 7.5.9 and below, as it is the only way to prevent those installers from moving unstable plugins to disabled.

if you are already on 7.6.3 or above, and you have already migrated your plugins, you will have noticed, that the newer installers currently do not remove a migrated `HexEditor.dll` at the new plugin folder structure.

-----
```
general notes:

please close your issue as soon as you are satisfied,
to help keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and first
search if a related topics exists. you are welcome to post at either an eventually similar
topic, or create a new topic at Help Wanted or General Discussion of your choice.
```
[<kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd>](https://notepad-plus-plus.org/community/)

**Comment by s-ne** [comment]
> @windsurfer1122 @s-ne
> 
> this old, outdated issue was related to version 6.8.8.
> 
> renaming .dlls, like `HexEditor.dll` is necessary for the old installer versions 7.5.9 and below, as it is the only way to prevent those installers from moving unstable plugins to disabled.
> 
> if you are already on 7.6.3 or above, and you have already migrated your plugins, you will have noticed, that the newer installers currently do not remove a migrated `HexEditor.dll` at the new plugin folder structure.
> 

That can't be the case as I still had the issue when I reported it on, let's see, Dec 17 2018. The version that came out a few days before and would've prompted the auto-update is **7.61**.

**Comment by chcg** [comment]
I think for releasing a "stable" new version of Hexedit https://github.com/chcg/NPP_HexEdit/issues/1 needs to be fixed. This is probably the biggest show stopper and maybe https://github.com/chcg/NPP_HexEdit/issues/13
