### ISSUE TITLE
Disable right click + mouse wheel document switching

### ISSUE THREAD

**Issue by Grinderofl** [notepad-plus-plus/notepad-plus-plus#2603]
### Description of the Issue
Notepad++ features a facility where, when multiple tabs are opened, one can press and hold right mouse button, and use the mouse wheel to scroll through them. This opens a small popup window with the file names. I'm unable to speak for others, but I have never been able to get rid of that little popup without selecting a different document than my original one. This is a highly irritating feature and I would like to request a way to disable it completely, including the right click-scroll change tab behaviour that still persists even if you disable document switcher. It's far too easy for me to press this combination resulting in an unneeded document change. 

In addition, when it's the window popping up, it will stick even if you let go of the right mouse button. The whole reason I'm raising this bug request is that today my cup with this bug finally overfilled when I couldn't get rid of the popup window even after spamclicking it for five minutes straight trying different open documents to switch to. As this box blocks every other NPP functionality, including save, I lost a chunk of work as I had to kill the process. I cannot believe that I'd be the only user to whom this has been consistently happening ever since I started using it 6 years ago to the point of annoyance. 

### Steps to Reproduce the Issue
1. Open notepad++
2. Open more than one tab
3. Press and hold right mouse button in Notepad++ window and scroll the wheel
4. Let go of the right mouse button

### Expected Behavior
Document switcher closes, or does not open in the first place. My active tab does not change.

### Actual Behavior
Document switcher stays open. To get rid of it, I need to click on an entry. Same entry won't do it, has to be different, thus causing my tabs to switch.

### Debug Information
Windows, all the way from XP to 10, on all types of machines, vendor built, home built, macbook air+parallels/boot camp, imac 27"+parallels/boot camp, basically it doesn't matter where or what hardware or software, it just happens everywhere, because it's a built in feature. If you are unable to reproduce, I'm willing to record a video of this happening on a fairly consistent basis.

**Comment by SinghRajenM** [comment]
Additionally, notepad crashed in below case always.
Steps to reproduce

1. Open notepad++
2. Open more than one tab (two tabs are enough)
3. Press and hold right mouse button in Notepad++ window and keep scrolling the wheel

At step 3, shadow of doc switcher start increasing. After certain amount of shadow, npp crashes.

![npp_crash](https://cloud.githubusercontent.com/assets/14791461/20604876/a9ea5830-b28e-11e6-8433-4a07a5537912.png)

**Comment by SinghRajenM** [comment]
Additionally, notepad crashes in below case always.
Steps to reproduce

1. Open notepad++
2. Open more than one tab (two tabs are enough)
3. Press and hold right mouse button in Notepad++ window and keep scrolling the wheel

At step 3, shadow of doc switcher start increasing. After certain amount of shadow, npp crashes.

![npp_crash](https://cloud.githubusercontent.com/assets/14791461/20604876/a9ea5830-b28e-11e6-8433-4a07a5537912.png)

**Comment by SinghRajenM** [comment]
Additionally, notepad crashes in below case always.
Steps to reproduce

1. Open notepad++
2. Open more than one tab (two tabs are enough)
3. Press and hold right mouse button in Notepad++ window and keep scrolling the wheel

At step 3, shadow of doc switcher start increasing. After certain amount of shadow, npp crashes.

![npp_crash](https://cloud.githubusercontent.com/assets/14791461/20604876/a9ea5830-b28e-11e6-8433-4a07a5537912.png)

Notepad++ v7.2.1   (32-bit)
Build time : Nov 20 2016 - 22:42:51
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10
Plugins : DSpellCheck2.dll mimeTools.dll NppConverter.dll NppExport.dll PluginManager.dll

**Comment by MAPJe71** [comment]
Can't reproduce with...

Notepad++ v7.2.1   (32-bit)
Build time : Nov 20 2016 - 22:42:51
Path : C:\Program Files\Notepad++\Notepad++-7.2.1.0.exe
Admin mode : OFF
Local Conf mode : ON
OS : Windows XP
Plugins : CustomizeToolbar.dll EditorConfig.dll FunctionList.dll InsertLoremIpsum.dll LuaScript.dll PluginManager.dll PreviewHTML.dll PythonScript.dll TagsView.dll TextFX.dll VisualStudioLineCopy.dll XMLTools.dll

**Comment by Grinderofl** [comment]
One might not be able to reproduce it, but that doesn't change the fact that it happens. Frequently. I haven't looked at the code due to time constraints to know how easily it's changeable, but from experience of writing win32 apps and how I would expect they would behave, adding a mechanism to disable the interaction between scroll and mouse2 should be fairly easy.

**Comment by SinghRajenM** [comment]
@MAPJe71 
1. Crash is consistently happening on Win10. I couldn't investigate/debug further due to busy schedule. 
2. As @Grinderofl said, it openes multiple popup which overlap each other. Refer the screenshot.
![image](https://cloud.githubusercontent.com/assets/14791461/20632460/b53b978c-b363-11e6-86f2-7217229bcfb2.png)


@Grinderofl 
> Notepad++ features a facility where, when multiple tabs are opened, one can press and hold right mouse button, and use the mouse wheel to scroll through them. This opens a small popup window with the file names.

Disabling Document switcher  (Settings -> Preferences ->MISC ->Uncheck "Enable" under doc switcher) will solve the multiple popup occurring problem, but right click+mouse will continue to function for tab switching.

**Comment by SinghRajenM** [comment]
Another duplicates #1619 and #2828

**Comment by pandalion98** [comment]
This still happens despite commit 133977da678bdbe0fe70326deefaf81c031661c9

Steps to reproduce:
  1. Open 2 or more tabs (I have about 50+ tabs open)
  2. Hold right-click inside the text editor
  3. Scroll exactly 18 times
      - Direction does not matter. Issue can be reproduced with up-down-up-down scrolling

Notepad++ 7.3.2 32-bit
OS: Windows 10 Pro 64-bit version 1511 (10586.753)

**Comment by SinghRajenM** [comment]
It is fixed in vv7.3.3.

**Comment by MediaEU** [comment]
notepad++ 7.9.1
Still has this stupid issue!
@Grinderofl 
"I cannot believe that I'd be the only user to whom this has been consistently happening ever since I started using it 6 years ago to the point of annoyance."
You're not the only one, this nerves me for years!
The funny thing is they have "shortcut mapper and scintilla and what else not" but it's pretty useless if you can't disable mouse right + scroll. btw the docs for notepad++ are a joke too, try to build your own plugins while following instructions from docs

**Comment by Ekopalypse** [comment]
@MediaEU - what is wrong with the documentation about creating plugins? What is missing or unclear?

**Comment by mcreereg** [comment]
From what I can tell, there's still no option to disable right-click + scroll behavior that changes your active tab.  You can disable the popup from displaying, but you can't stop the editor from changing which tab is active.

Any chance that either #2603 or #9735 can be re-opened as a feature request to have an option to disable this behavior completely?

> Why don't you just not press the right mouse button and then scroll?

I never _mean_ to do this.  I do this accidentally a couple times a week when I try to scroll several pages rapidly with my big clumsy hands.  I understand that there are other ways to scroll through a document, but sometimes spamming the scroll wheel is how I want to do it, and this tab-switching behavior ends up biting me.

**Comment by Winsane** [comment]
If you're willing to compile your own npp version, this is what you comment out to disable the right click + scroll document switch. I'm not sure why shortcuts like these are still hardcoded.

https://github.com/notepad-plus-plus/notepad-plus-plus/blob/4555db8f9125965a469fa5ff0f8052809b9767e9/PowerEditor/src/NppBigSwitch.cpp#L1086-L1097

**Comment by Darkster1** [comment]
The right click scroll is so annoying, it happens to me too many times, I'm visually impaired sometimes i'm in the middle of reading something and by accident hit the right mouse button while scrolling. So scrolling a few tabs away from where I was at.
Now way to cancel the damn thing by escape or just clicking outside the switch list,  it's persistent. The only way is selecting the current file but with 20+ files open, for me that's compared to searching for a needle in a lot of haystacks! Search through al the options for a solution but nothing.

Now I read that it's hard coded so I guess I'm gonna try to compile it myself then.
Or switch to another editor.

**Comment by alankilborn** [comment]
>Now I read that it's hard coded so I guess I'm gonna try to compile it myself then. Or switch to another editor.

Another option would be to use the PythonScript plugin and run the following script (I call it `MouseWheelRightClickScrollDocSwitchDisable.py`) on startup:

    # -*- coding: utf-8 -*-

    import platform
    from ctypes import windll, WINFUNCTYPE
    from ctypes.wintypes import HWND, WPARAM, LPARAM, UINT, INT

    #-------------------------------------------------------------------------------

    running_32bit = platform.architecture()[0] == '32bit'
    user32 = windll.user32
    LRESULT = LPARAM
    GWL_WNDPROC = -4
    WNDPROCTYPE = WINFUNCTYPE(LRESULT, HWND, UINT, WPARAM, LPARAM)
    SetWindowLong = user32.SetWindowLongW if running_32bit else user32.SetWindowLongPtrW
    SetWindowLong.restype = WNDPROCTYPE
    SetWindowLong.argtypes = [HWND, INT, WNDPROCTYPE]
    WM_MOUSEWHEEL = 0x020A
    MK_RBUTTON = 2
    def LOWORD(x): return x & 0xFFFF

    #-------------------------------------------------------------------------------

    class MWRCSDSD(object):

        def __init__(self):
            npp_hwnd = user32.FindWindowW(u'Notepad++', None)
            self.new_npp_wnd_proc_hook_for_SetWindowLong = WNDPROCTYPE(self.new_npp_wnd_proc_hook)
            self.orig_npp_wnd_proc = SetWindowLong(npp_hwnd, GWL_WNDPROC, self.new_npp_wnd_proc_hook_for_SetWindowLong)

        def new_npp_wnd_proc_hook(self, hwnd, msg, wParam, lParam):
            if msg == WM_MOUSEWHEEL:
                if 0 != (LOWORD(wParam) & MK_RBUTTON):
                    return False  # keep N++ from processing this message by returning False
            return self.orig_npp_wnd_proc(hwnd, msg, wParam, lParam)  # let N++ process message as usual

    #-------------------------------------------------------------------------------

    if __name__ == '__main__': MWRCSDSD()

**Comment by Darkster1** [comment]
> > Now I read that it's hard coded so I guess I'm gonna try to compile it myself then. Or switch to another editor.
> 
> Another option would be to use the PythonScript plugin and run the following script (I call it `MouseWheelRightClickScrollDocSwitchDisable.py`) on startup:
> 
> ```
> # -*- coding: utf-8 -*-
> 
> import platform
> from ctypes import windll, WINFUNCTYPE
> from ctypes.wintypes import HWND, WPARAM, LPARAM, UINT, INT
> 
> #-------------------------------------------------------------------------------
> 
> running_32bit = platform.architecture()[0] == '32bit'
> user32 = windll.user32
> LRESULT = LPARAM
> GWL_WNDPROC = -4
> WNDPROCTYPE = WINFUNCTYPE(LRESULT, HWND, UINT, WPARAM, LPARAM)
> SetWindowLong = user32.SetWindowLongW if running_32bit else user32.SetWindowLongPtrW
> SetWindowLong.restype = WNDPROCTYPE
> SetWindowLong.argtypes = [HWND, INT, WNDPROCTYPE]
> WM_MOUSEWHEEL = 0x020A
> MK_RBUTTON = 2
> def LOWORD(x): return x & 0xFFFF
> 
> #-------------------------------------------------------------------------------
> 
> class MWRCSDSD(object):
> 
>     def __init__(self):
>         npp_hwnd = user32.FindWindowW(u'Notepad++', None)
>         self.new_npp_wnd_proc_hook_for_SetWindowLong = WNDPROCTYPE(self.new_npp_wnd_proc_hook)
>         self.orig_npp_wnd_proc = SetWindowLong(npp_hwnd, GWL_WNDPROC, self.new_npp_wnd_proc_hook_for_SetWindowLong)
> 
>     def new_npp_wnd_proc_hook(self, hwnd, msg, wParam, lParam):
>         if msg == WM_MOUSEWHEEL:
>             if 0 != (LOWORD(wParam) & MK_RBUTTON):
>                 return False  # keep N++ from processing this message by returning False
>         return self.orig_npp_wnd_proc(hwnd, msg, wParam, lParam)  # let N++ process message as usual
> 
> #-------------------------------------------------------------------------------
> 
> if __name__ == '__main__': MWRCSDSD()
> ```

Many thanks, that works like charm, was also writing a library via Delphi but got stuck and distracted so... but this works perfectly.
Thanks!

**Comment by sm-Fifteen** [comment]
Consider also the following: if you happen to have some form of kinetic scrolling, either implemented in software on some trackpads or in hardware on some higher-end mice, whenever you happen to right-click before the scrolling has come to a complete still, you will trigger the document switcher. If your scroll wheel has no detents (often called "precision scrolling"), it may move slightly with mouse movement and raise a scroll event while you're trying to do something else. If your trackpad uses both two-finger right-click and two-finger scrolling, I'm sure there are various ways to accidentally trigger document switching this way as well.

Switching documents with "next page"/"previous page" side-buttons on a mouse is something I can understand (those are meant to be slightly more out of the way), and the same goes for ctrl-scroll (which is generally more deliberate and requires 2 hands, even though kinetic scroll can still be a problem in that case), but putting that action on something like the scroll wheel combined with the secondary mouse button makes it far too easy to trigger by accident on various configurations and makes using Np++ a very frustrating experience every time I end up using it. Notepad++ is the only text editor I'm aware of that has such a behavior (in a way that cannot be disabled, no less: the best you can do is disable the document switcher window).

This isn't about crashing or losing focus, it's a usability problem. Please reopen this issue.

**Comment by lezpaul** [comment]
I solved this problem with 4 lines of AutoHotKey script


`#IfWinActive ahk_exe notepad++.exe`
`~RButton & WheelDown:: Return`
`~RButton & WheelUp:: Return`
`#If`


Just copy or link AHK script file in Windows AutoStart folder (maybe different based on your OS)
%appdata%\Microsoft\Windows\Start Menu\Programs\Startup

**Comment by jabcreations** [comment]
> I solved this problem with 4 lines of AutoHotKey script
> 
> `#IfWinActive ahk_exe notepad++.exe` `~RButton & WheelDown:: Return` `~RButton & WheelUp:: Return` `#If`
> 
> Just copy or link AHK script file in Windows AutoStart folder (maybe different based on your OS) %appdata%\Microsoft\Windows\Start Menu\Programs\Startup

This is the first time in years that I tried anything AutoHotKey that actually worked. It requires the "deprecated" 1.x release. After creating the script you need to run it. Then test it in Notepad++.

**Comment by biorpg** [comment]
I learned long ago to accept that people with hands shaped like mine, who use them with a mouse like I do, do not deserve consideration, let alone a whole function to disable a shortcut that only people with hands shaped like mine, who use them with a mouse like I do frequently trigger, but I will indulge the cruelty and let you know that it surprises us when it happens. Every time. In fact, the only time we are ever made aware that we have scrolled the mouse wheel while the right mouse button is held down is when we use Notepad++, so rest easy knowing that this unique experience is entirely your gift, and yours alone! <3

**Comment by pandalion98** [comment]
> This still happens despite commit [133977d](https://github.com/notepad-plus-plus/notepad-plus-plus/commit/133977da678bdbe0fe70326deefaf81c031661c9)
> 
> ### Steps to reproduce:
> 1. Open 2 or more tabs (I have about 50+ tabs open)
> 2. Hold right-click _inside_ the text editor
> 3. Scroll exactly 18 times
>    
>    * Direction does not matter. Issue can be reproduced with up-down-up-down scrolling
> 
> **Other observation:** No popups appear, yet Notepad++'s window loses focus
> 
> Notepad++ 7.3.2 32-bit OS: Windows 10 Pro 64-bit version 1511 (10586.753)

Replying to my 2017 self. Crash and/or popup getting stuck no longer occurs for me.

Currently using V8.4.8 64-bit on Windows 11 10.0 Build 22621.

**Comment by DeadByte42** [comment]
> Hope it helps other NP++ users

This is a lifesaver! In some update, the developer removed the option to disable the document switcher (I installed the latest version after reinstalling Windows, and now you can only disable the list display, but not the document switcher itself).
I generally support adding various unique features to programs that can be useful even for a very limited number of people, but they **should be disableable** so as not to annoy others.
