### ISSUE TITLE
Function list not working when JavaScript function name is followed by a space

### ISSUE THREAD

**Issue by Smile4ever** [notepad-plus-plus/notepad-plus-plus#2604]
### Description of the Issue
When you have a function name which is followed by a space before putting (), the function is not displayed in the function list.

### Steps to Reproduce the Issue

1. Show the Function list (View -> Function list)
2. Create a new file with these contents:

function bla(){}
function lala (){}

3. Save the file with a .js extension.

### Expected Behavior
bla and lala are displayed in the function list.

### Actual Behavior
bla is recognised and displayed in the function list.

### Debug Information
Notepad++ v7.2.1   (32-bit)
Build time : Nov 20 2016 - 22:42:51
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : ON
Local Conf mode : OFF
OS : Windows 10
Plugins : ComparePlugin.dll mimeTools.dll NppConverter.dll NppExport.dll PluginManager.dll

**Comment by MAPJe71** [comment]
See PR #2602.
