### ISSUE TITLE
New name for menu called "Window"?

### ISSUE THREAD

**Issue by scootergrisen** [notepad-plus-plus/notepad-plus-plus#2608]
The menu called "Window" in the translation does not seem to have anything to do with window/windows:
`<Item idName="Window" name="Window"/>`

Would it not be better to call it Tabs or Buffers or something like that?
Anyone have a good idea of what would be best?
I guess if tabs can be disabled that would not be the best.

If we don't want to change the name would it not be better to called it "Windows" what a "s"? Because there are (can be) mere then one?.

**Comment by vlakoff** [comment]
It seems to be standard, judging by these references:
* I have "Window" too e.g. in SmartGit ([screenshot](https://en.wikipedia.org/wiki/File:SmartGit_2.1_Windows_7.png))
* Search "Menu category names" in these [Microsoft guidelines](https://msdn.microsoft.com/en-us/library/windows/desktop/dn742392(v=vs.85).aspx)
* See also these [Apple guidelines](https://developer.apple.com/library/content/documentation/UserExperience/Conceptual/OSXHIGuidelines/MenuBarMenus.html)

**Comment by scootergrisen** [comment]
I suppose Notepad++ should follow the Microsoft way if the software can only be used on Windows system.
Anyone know of Microsoft software where we can see what they use? Software that can have multiple files opened.

**Comment by scootergrisen** [comment]
I don't see it on https://msdn.microsoft.com/en-us/library/windows/desktop/dn742392(v=vs.85).aspx

I see it on https://developer.apple.com/library/content/documentation/UserExperience/Conceptual/OSXHIGuidelines/MenuBarMenus.html but thats macOS.

**Comment by MetaChuh** [comment]
@scootergrisen 

the naming scheme is a design choice.
as the majority of notepad++ users is very used to it, it would cause confusion to change it, so we don't.

thank you for your help and best regards.

**Comment by sasumner** [comment]
Note also that YOU can change your copy to say whatever you think best.
