### ISSUE TITLE
Please make opening all previous opened file optional

### ISSUE THREAD

**Issue by Varun200864** [notepad-plus-plus/notepad-plus-plus#261]
I am using Notepad++ version 6.5 (UNICODE). Notepad++ opens all previously opened files when started. Please make this feature optional.

**Comment by jonandr** [comment]
Settings -> Preferences -> Backup -> Remember current session for next launch.

**Comment by Varun200864** [comment]
Thank you. I found that in Settings -> Preferences -> MISC. -> Remember current session for next launch
