### ISSUE TITLE
New style dialog "without file extension feature" seems to be with file extension feature

### ISSUE THREAD

**Issue by scootergrisen** [notepad-plus-plus/notepad-plus-plus#2610]
In translation file there is this:
`<Item id="6430" name="Use new style save dialog (without file extension feature)"/>`

Maybe i don't understand the string but in Windows 7 it seems that i am able to select the file type when using the new style so i don't understand why it would say "without file extension feature".

**Comment by MetaChuh** [comment]
@scootergrisen 

without file extension feature means, that the dialogue will reset itself to `all types (*.*)` after every opening.

thank you for your help and best regards.
