### ISSUE TITLE
"MAC" to "Mac" and "UNIX" to "Unix"

### ISSUE THREAD

**Issue by scootergrisen** [notepad-plus-plus/notepad-plus-plus#2616]
Suggestion to translation:
```
-                    <Item id="45002" name="Convert to UNIX Format"/>
+                    <Item id="45002" name="Convert to Unix Format"/>

-                    <Item id="45003" name="Convert to MAC Format"/>
+                    <Item id="45003" name="Convert to Mac Format"/>
```

So that is matches with:
```

                    <Item id="6403" name="Unix"/>
                    <Item id="6404" name="Mac"/>

```
I guess Unix could also be UNIX which ever way you prefer.

**Comment by scootergrisen** [comment]
popcorner wrote this in a pulll request that was closed:

> Actually, Mac might be an outdated name.
> Apple called it Mac OS many years ago
> and then renamed it to OSX
> 
> now it is called macOS
> （change mac to lowercase and remove the space）
> 

I don't know what the correct mac word would be.
But i think "Convert to Mac Format" is referring to a way of new lines used in old Mac systems.
They used "\r" on old Mac system i believe but have switched to using "\n" like Linux years ago i think but i'm not sure.
Maybe "Classic Mac" or what ever is most commonly used in other editors.

**Comment by MetaChuh** [comment]
@scootergrisen 

this was done a long time ago.
`<Item id="45002" name="Unix (LF)"/>'

thank you for your help and best regards.

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
(no extra account is needed, just use your github account to sign in)
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)
