### ISSUE TITLE
Server-side JScript syntax highlighting missing in ASP

### ISSUE THREAD

**Issue by z87** [notepad-plus-plus/notepad-plus-plus#2617]
ASP allows to specify language for server-side scripts. VBScript and PHP work as expected while JScript is not recognized. I believe the issue is within the editor because I have replaced SciLexer.dll with one from SciTE and got the same result.

Compare NP++ with SciTE at line 8:
![np vs scite](https://cloud.githubusercontent.com/assets/12435877/20641490/0045f456-b40a-11e6-80ea-c388806cb2b3.png)

Test case:
```
<%@ language="PHP" %>
<%
echo 'Hello world'; // php comment
%>

<%@ language="JScript" %>
<%
var x = 'test'; // js comment
%>

<%@ language="VBScript" %>
<%
dim x as long ' vb comment
%>

<script>
var x = 'test'; // client-side js
</script>
```

**Comment by MetaChuh** [comment]
please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins if you update from version 7.5.9 or below.
if your issue still persists, and it is still of relevance to you, please feel free to file a new issue as easy to understand and reproducible as possible.

thank you for your help and best regards.

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
(no extra account is needed, just use your github account to sign in)
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)
