### ISSUE TITLE
Minor bugs with macro

### ISSUE THREAD

**Issue by christino156** [notepad-plus-plus/notepad-plus-plus#2619]
I experimented a bit with macro and noticed some unorthodox behavior.
More specifically I found that:

1. Even though you can't record a macro without typing anything, if you do type something and then delete it you can record an empty macro and even save it. Obviously when you run it nothing happens, but I don's suppose there is a point in having an empty macro.

2. When you save a macro and assign a shortcut to it, if the shortcut already exists you get a warning of conflict but you are still allowed to assign the shortcut to as many macros as you want. In the end, the shortcut only works for the first macro you assigned, but it still appears to be the shortcut for all macros it was assigned to. For a reckless user that doesn't notice warnings it could prove very annoying or confusing as they would try to access a macro via a shortcut and instead they would access an old macro assigned previously to that shortcut (especially confusing if the macros were to be similar).

3. When you select to run a macro multiple times a box appears asking you how many times you want it to run. Should you choose for some reason to run it 0 times and hit run then the macro will run once instead of zero times. I understand that there is no point in running a macro 0 times but it seems like a mistake to run it once when specifically told otherwise. Maybe the user should not be allowed to enter 0 as a choice or maybe the "Run" button should not be activated in that case.

4. When you run a macro multiple times, there is a "Cancel" option which I perceive as cancelling the running of the macro. For example if I choose to run a macro 1000 times or more it should take some time to do so and in that time if I regret it I could press cancel and the macro would stop running. However, in my case that does not happen. If I press "Cancel" while running a macro a lot of times, not only is the macro not cancelled but the window also stops responding. 
In case I am mistaken and the "Cancel" button is there merely in order to close the window, then maybe it would be wise to rename it to "Exit" in order to avoid confusion.

The attached images are examples of cases 2, 3 and 4. 

This image shows that the user is allowed to create a conflict.
![conflict](https://cloud.githubusercontent.com/assets/20790332/20644051/34b23bb0-b431-11e6-9132-b6041130d5e9.JPG)

This image shows that the user is allowed in theory to run a macro 0 times.
![zero](https://cloud.githubusercontent.com/assets/20790332/20644053/34b7dce6-b431-11e6-8221-58abb5660e5e.JPG)

This image shows the window that stops responding when I press "Cancel" (while running a macro 5000 times).
![not responding](https://cloud.githubusercontent.com/assets/20790332/20644052/34b537fc-b431-11e6-84ee-a415def67834.JPG)

I should mention that I used a laptop with a quad-core processor and windows 10. 
Also tested my findings in another computer and I got the same results but the two computers don't have any major differences. 
In both cases I used version 7.1 of Notepad++.

**Comment by MetaChuh** [comment]
please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins if you update from version 7.5.9 or below.
if your issue still persists, and it is still of relevance to you, please feel free to file a new issue as easy to understand and reproducible as possible.

thank you for your help and best regards.

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
(no extra account is needed, just use your github account to sign in)
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)
