### ISSUE TITLE
Freeze On Close

### ISSUE THREAD

**Issue by BullyWiiPlaza** [notepad-plus-plus/notepad-plus-plus#262]
Sometimes when I close Notepad++ version 6.7.9 (the current newest version) the Window does not close but rather hang/freeze. Also the deinstaller hangs.

I posted more detailed information about this on [`Superuser`](http://superuser.com/questions/927733/notepad-hangs-on-close).

Please investigate why this might happen and let me know what I can do to help it. It seems like this has never happened before and is a bug that has been introduced lately.

**Comment by dail8859** [comment]
This issue has been reported at #239. It is related to the DSpellCheck plugin (there is a temporary update to the plugin you can try there), so this issue can be closed and you can feel free to move to that thread. If you think there is something else causing the problem, please keep this issue open. Thanks for the report.

**Comment by dail8859** [comment]
Also, not sure why the deinstaller would hang...it still may be related to the DSpellCheck plugin if it is not getting properly shutdown and the deinstaller cannot remove some locked files or something.
