### ISSUE TITLE
Html <nul> error

### ISSUE THREAD

**Issue by Geloraff** [notepad-plus-plus/notepad-plus-plus#2623]
### Description of the Issue

When typing HTML in computer science, multiple people as in like two or three of us got <nul> errors. So instead of having our html coding we got

<nul><nul><nul>and so on.

### Steps to Reproduce the Issue

1.  
2. 
3. 

### Expected Behavior

Open the desired document to begin html.

### Actual Behavior

Multiple <nul> errors on one line.

**Comment by dail8859** [comment]
Please provide your debug information and a set of reproducible steps. This doesn't sound like default Notepad++ behavior.
