### ISSUE TITLE
Notepad++ dont save when save menu is selected

### ISSUE THREAD

**Issue by Thor-Arne** [notepad-plus-plus/notepad-plus-plus#2624]
### Description of the Issue

I recently switched to my Windows7 64bit laptop, before I used Windows7 32bit.

After this Notepad++ don't save when I select save from the menu or press ctrl-S.
However Save-As saves the file just fine.

### Steps to Reproduce the Issue

1. Open a existing file
2,. Edit and select save

### Expected Behavior

I expected the file to be saved.

### Actual Behavior

Nothing happens, and the file is still marked as "changed" on the toolbar.

### Debug Information

Notepad++ v7.1   (32-bit)
Build time : Oct 15 2016 - 23:30:30
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 7
Plugins : HTMLTag_unicode.dll mimeTools.dll NppConverter.dll NppExec.dll NppExport.dll NppFTP.dll PluginManager.dll SpellChecker.dll XMLTools.dll 

Tried multiple file locations and file types, no change.

**Comment by dail8859** [comment]
Fixed in v7.2 and above.
