### ISSUE TITLE
Misleading size of scrollbar in Shortcut Mapper

### ISSUE THREAD

**Issue by christino156** [notepad-plus-plus/notepad-plus-plus#2625]
### Description of the Issue
In the shortcut mapper, all tabs with 19 or more rows have the same scrollbar which is very misleading and annoying to use.

### Steps to Reproduce the Issue

1. Go to Shortcut Mapper.
2. Select a tab with 19 or more rows (e.g. Plugin commands with default 22 rows)

### Expected Behavior
I expect the scrollbar's size to be proportionate to the number of rows.

### Actual Behavior
The scrollbar's size is exactly the same in every tab, regardless of how many rows it has.

### Examples
A tab with 19 rows:
![scroll](https://cloud.githubusercontent.com/assets/20790332/20653223/a88cd19e-b512-11e6-927f-3dd1254f615e.JPG)

A tab with 22 rows:
![scrollbar](https://cloud.githubusercontent.com/assets/20790332/20653224/a88ff2c0-b512-11e6-9b4e-80844ecaca1e.JPG)

A tab with 281 rows:
![scrolling](https://cloud.githubusercontent.com/assets/20790332/20653225/a8907bd2-b512-11e6-8a8c-059c1e403fdf.JPG)

Also, if you have a tab with 19 rows and you delete one of them, then the scrollbar disappears without returning to the top of the tab. Consequently, the first row disappears and can only be accessed by moving up the rows from the keyboard, which is slightly annoying.

An example of this behavior:
![no scrollbar](https://cloud.githubusercontent.com/assets/20790332/20653244/243318f8-b513-11e6-9188-0a4b99b3edf9.JPG)

### Debug Information
Notepad++ v7.2 (64-bit)
Build time : Nov 28 2016 - 02:28
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10
Plugins : default plugins

**Comment by pankcakeman** [comment]
hello

**Comment by MetaChuh** [comment]
please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins if you update from version 7.5.9 or below.
if your issue still persists, and it is still of relevance, please feel free to file a new issue as easy to understand and reproducible as possible.

thank you for your help and best regards.
