### ISSUE TITLE
64-bit: "Update Notepad++" does not work

### ISSUE THREAD

**Issue by valiko-ua** [notepad-plus-plus/notepad-plus-plus#2627]
Notepad++ v.7.2.1 64-bit, Windows 7 SP1.
Version 7.2.2 is available for download from the site but "Update Notepad++" menu item says:
```
---------------------------
Notepad++ update
---------------------------
No update is available.
---------------------------
OK   
---------------------------
```
The same applies to all previous 64-bit versions.

**Comment by dail8859** [comment]
Quote from the Notepad++ website:

> Auto-updater will be triggered in few days if there's no critical issue found.

**Comment by valiko-ua** [comment]
Sorry, missed that.
