### ISSUE TITLE
Add support for mailto:, tel:, and callto: as Clickable Links

### ISSUE THREAD

**Issue by bigd1182** [notepad-plus-plus/notepad-plus-plus#2629]
### Description of the Issue

Clickable Links only recognizes URIs containing ://
...hence, callto: mailto: and tel: will not be clickable

### Steps to Reproduce the Issue

1. Type callto:+18001234567
2. Type callto://+18001234567

### Expected Behavior

callto:+18001234567 should be clickable and allow the supporting application (ie. Skype) to open and recognize the format.

### Actual Behavior

Notice step 2 above will allow clicking and if you have an application installed that supports the protocol, it will open the application but will fail because the format is not correct due to the "//".

### Debug Information
Within the PowerEditor\src\Notepad_plus.h file, the following RegEx is defined for matching URLs...
#define URL_REG_EXPR "[A-Za-z]+://[A-Za-z0-9_\\-\\+~.:?&@=/%#,;\\{\\}\\(\\)\\[\\]\\|\\*\\!\\\\]+"

Perhaps using something like the following would allow the other 3 protocols...
#define URL_REG_EXPR "([A-Za-z]+://[A-Za-z0-9_\\-\\+~.:?&@=/%#,;\\{\\}\\(\\)\\[\\]\\|\\*\\!\\\\]+)|((mailto:|tel:|callto:).\*)"

**Comment by redmanmale** [comment]
There are much more shemes than just: mailto, tel and callto.
See https://www.iana.org/assignments/uri-schemes/uri-schemes.xhtml

**Comment by MetaChuh** [comment]
this feature will currently not be implemented.

thank you for your help and best regards.
