### ISSUE TITLE
Notepad++ Not Responding

### ISSUE THREAD

**Issue by TheHause** [notepad-plus-plus/notepad-plus-plus#263]
When I try to close Notepad++ with one saved document and one not saved (I don't need the not saved one), Notepad++ will freeze and never close, forcing me to end the program. I have not seen this in previous versions. (Version 6.7.9, Windows 8 64-bit)

**Comment by TheHause** [comment]
Just tested and it closes fine if I remove the 'DSpellCheck.dll' plugin.

**Comment by donho** [comment]
@TheHause Sergey (the author of DSpellCheck) has done some fixes. Could you try this build to confirm us if Notepad++hangs always on close?
https://notepad-plus-plus.org/repository/6.x/6.7.9.1.prerelease/npp.6.7.9.1.Installer.exe

**Comment by Razunter** [comment]
@donho Looks like bug is fixed in the new version, thanks.

**Comment by DarkArcherPrince** [comment]
I'm having this problem too but I've noticed that it only happens if Notepad++ gets closed with new1 displayed. Closing the program with an open file doesn't seem to cause any hanging.
