### ISSUE TITLE
64 bit version does not see any update

### ISSUE THREAD

**Issue by hervethouzard** [notepad-plus-plus/notepad-plus-plus#2635]
### Description of the Issue
Hello, on Windows 10 I'm using the 64bits version but it never see any update when there are.

### Steps to Reproduce the Issue
Install the 64 bits version and ask for any update.

### Expected Behavior
The program should update

### Actual Behavior
The program do not update

**Comment by dail8859** [comment]
What version are you on? and what version are you trying to update to? It will not find v7.2.2 yet.

Quote from the Notepad++ website:

> Auto-updater will be triggered in few days if there's no critical issue found.

**Comment by hervethouzard** [comment]
I was using a version 7.1 and wanted to use the last one

**Comment by dail8859** [comment]
It should work now that the auto-updater has been triggered to find v7.2.2
