### ISSUE TITLE
Link Highlight Color

### ISSUE THREAD

**Issue by Nidre** [notepad-plus-plus/notepad-plus-plus#2636]
### Description of the Issue
Blue Link Highlight in Dark themes is unreadable. I always have to move mouse out of the link to be able read. Especially problematic if I'm trying to click on a specific char on the link since I can't properly see the characters.

See screenshot for an example:
![image](https://cloud.githubusercontent.com/assets/6220948/20795141/3af584e6-b7d8-11e6-87b8-ec1ca9bea51d.png)

### Steps to Reproduce the Issue
1. Install/Apply any dark theme. 
1a. The issue can be clearly seen on the Theme that I'm authoring(see screenshot below). https://github.com/Nidre/VS2015-Dark-Npp/

### Expected Behavior
The link color should be changeable by the Theme files since theme background colors can easily make link color unreadable if the background and link has no contrast.

### Actual Behavior
Could not find a way to edit link color via Theme.

**Comment by dail8859** [comment]
![url](https://cloud.githubusercontent.com/assets/3694843/20861154/f42490cc-b956-11e6-9f77-db97c5958662.png)

It is settable via the style configurator. This is most likely a bug with the VS2015 Dark theme not including a line like [this](https://github.com/notepad-plus-plus/notepad-plus-plus/blob/master/PowerEditor/src/stylers.model.xml#L894).

**Comment by Nidre** [comment]
@dail8859 

Not sure how I've missed that one. :) Is there a way to change color of URL when it is not hovered? I've tried URL with no luck.

**Comment by dail8859** [comment]
No it just uses whatever the context of the link is, for example (with the default theme) comments are green so any links within comments will be green.

**Comment by Nidre** [comment]
@dail8859 got it thanks.
