### ISSUE TITLE
NP++ has issue changing status bar from ANSI to UTF-8 when the file is changed externally

### ISSUE THREAD

**Issue by andybantly** [notepad-plus-plus/notepad-plus-plus#2637]
### Description of the Issue
In notepad++ when a comma separated text files encoding changes from ANSI to UTF-8 with no byte order marker the status bar does not reflect the change.  The file needs to be closed and reopened for the status bar to reflect the change.

### Steps to Reproduce the Issue
1. Load the ANSI file into NP++
2. Use a text editor, other than NP++, that can save an ANSI file as UTF-8 with no BOM
3. Go back to NP++ and allow it to reload the externally change file and note that the encoding doesn't change from ANSI to UTF-8

### Expected Behavior
I expected the status bar to change from ANSI to UTF-8

### Actual Behavior
The status bar stayed displaying ANSI

### Debug Information
Notepad++ v7.1   (32-bit)
Build time : Oct 15 2016 - 23:30:30
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 7
Plugins : ComparePlugin.dll mimeTools.dll NppConverter.dll NppExport.dll NppFTP.dll PluginManager.dll

**Comment by vlakoff** [comment]
Great coincidence: maybe my recent #2633 would fix this.
