### ISSUE TITLE
Styler for user-defined highlighting crashes program when given arbitrary string

### ISSUE THREAD

**Issue by lkieliger** [notepad-plus-plus/notepad-plus-plus#2646]
### Description of the Issue

When defining new highlighting rules for a custom language, opening the "Styler dialog" and providing an arbitrary string in the inputs for the font options will crash the program

### Steps to Reproduce the Issue

1. Define a new language for highlighting keywords
2. Open the Styler dialog to edit text style
3. Instead of selecting a font name and font size from the combo-box, write directly an arbitrary string and press enter

### Expected Behavior
Either detect closest match for user input or leave input field empty

### Actual Behavior
Program crash

### Debug Information
Notepad++ v7.2.2   (32-bit)
Build time : Nov 27 2016 - 16:31:07
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10
Plugins : mimeTools.dll NppConverter.dll NppExport.dll PluginManager.dll 

![styler_crash](https://cloud.githubusercontent.com/assets/9282667/20885256/2304de98-baf0-11e6-9c1e-7f7e7fd1c732.png)

![styler_crash2](https://cloud.githubusercontent.com/assets/9282667/20885270/341ad5de-baf0-11e6-83b2-a30877ad093e.png)

**Comment by SinghRajenM** [comment]
This crash is irrespective of arbitrary string or combo selection. Crash happens only when you use "Enter" instead of mouse click on "Ok" button.

**Comment by CookiePLMonster** [comment]
Awesome! I should have tested more before saying I can't reproduce :/
