### ISSUE TITLE
Languages don't scroll with mouse scroll wheel

### ISSUE THREAD

**Issue by bakasmarius** [notepad-plus-plus/notepad-plus-plus#2648]
After noticing that languages are now all in one place I tried so scroll down with mouse scroll wheel, but nothing happens. I have to manually click the arrow icons in order to scroll down.

Also, it would be nice that for example, after typing "s" and "q" quickly one after another, it would select "Shell" after the first keystroke and "SQL" after the second one. I'm not sure how to title this feature, that's why I gave an example.

N++ 7.2.1 x64 / Windows 10 x64 (updating to N++ 7.2.2 didn't help)

**Comment by SinghRajenM** [comment]
Three solutions are already available - 
1. Make language menu compact => settings -> Preferences -> Language ->Check "language menu compact".
2. Use arrow key => Press Alt -> Press Key 'L' -> Navigate to desired language using UP/DOWN arrow keys
3. Use Character repeatedly => on language menu keep on pressing respective key. Example, If you want to navigate to SQL, then press 'S' key four times.

I keep language menu compact which is easy to use.

**Comment by bakasmarius** [comment]
Thank you SinghRajenM, your 3rd solution is perfectly acceptable for me.
