### ISSUE TITLE
New plugin versions announce

### ISSUE THREAD

**Issue by sanastasiou** [notepad-plus-plus/notepad-plus-plus#265]
Hi,

where shall one announce a new plugin / plugin version now that we moved to github? Still at sourceforge ? Or is there some other way to do this?

**Comment by bruderstein** [comment]
This is a good question. For the immediate future, we'll have to live without announcing, I think. However, I think with a bit of luck, this should be automatically taken care of in the new plugin admin system.  

When you release a new plugin there (i.e. by changing the current version number, and updating the download / install steps), it could automatically be announced via (for example) twitter. Possibly also in the gitter/slack channel.  After a few days it would then automatically be available via PM. Hopefully, if we can manage it, it will be available (almost) immediately via PM under a flag in PM ("allow install of newly released, untested plugins" or some such setting in the config).  

This isn't all going to come at once, but that would be one nice way to do it.

**Comment by StanDog** [comment]
Hi Dave (nice translation of you name btw ;-) )

The automatic notifications in your admin backend system is a good idea. How about using one issue entry (for example this one here) for announcements from us plugin developers (until your new system works fully)? Where no discussions but just announcements are posted so the issue tracker stays mostly clean without flooding everything. I recently moved my projects / plugins to GitHub too but I'm not sure / didn't tried if it is possible to make an issue "sticky" or if it moves to the top position if somebody writes a new comment.

**Comment by milipili** [comment]
Gitter may seem a good place for that in a first time.

**Comment by donho** [comment]
@sanastasiou  We got new Notepad++ Community now:
https://notepad-plus-plus.org/community/

**Comment by sanastasiou** [comment]
Yeah I saw it :) good job!
