### ISSUE TITLE
page scrolls on reload

### ISSUE THREAD

**Issue by UlrichScholz** [notepad-plus-plus/notepad-plus-plus#2653]
### Description of the Issue
reloading a file makes the page scroll

### Steps to Reproduce the Issue
1. load a file 
2.  go to the last line
3. reload the file

### Expected Behavior
lines shown should stay unchanged

### Actual Behavior
page jumps "upwards"

### Debug Information
Notepad++ v7.1   (32-bit)
Build time : Oct 15 2016 - 23:30:30
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10
Plugins : JSMinNPP.dll mimeTools.dll NppConverter.dll NppExport.dll NppFTP.dll NPPJSONViewer.dll PluginManager.dll

**Comment by PalashBansal** [comment]
For me, its working fine

Notepad++ **v7.2.2**   (32-bit)
Build time : Nov 27 2016 - 16:31:07
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 7
Plugins : mimeTools.dll NppConverter.dll NppExport.dll NppFTP.dll PluginManager.dll 

@UlrichScholz  Update your nppp to latest version, and check.
