### ISSUE TITLE
NPP crashes during certain instances

### ISSUE THREAD

**Issue by digger78** [notepad-plus-plus/notepad-plus-plus#2654]
### Description of the Issue
I am currently on v7.2.2 portable, 32-bit.  My NPP portable folder is stored on a network drive.

I have been having an issue once or twice a day since updating to v7.2. (Prior to v7.2, I would not experience this issue.) Every once in a while, NPP will just exit/crash. It won’t save my recent file lists or even any unsaved files.  There is no error message that appears on screen. The program simply closes.

So far, the crash occurs when I sometimes perform the following four actions:
*Drag a file into NPP from File Explorer to open it.
*Use CTRL+TAB to try to switch among the open NPP tabs.
*Attempt to open the NPP home page by going to "?," then "Notepad++ Home."
*Simply click on the NPP window to put it in focus when I am using another application.

(I *don't* mean all of the above actions need to be performed at the same time when the issue occurs.  Instead, I mean that the issue sometimes happens when the first action is performed, sometimes when the second action is performed, etc.)

It doesn't crash *every* time I do the above actions.  But those are the things I was doing when it did crash.  There might be other actions that would cause the crash that I am not aware of.

### Debug Information
Notepad++ v7.2.2   (32-bit)
Build time : Nov 27 2016 - 16:31:07
Path : \\fenoffc302\UsersA-Z\digregm\AppSense\Desktop Redirect\NPP\notepad++.exe
Admin mode : OFF
Local Conf mode : ON
OS : Windows 7
Plugins : mimeTools.dll NppConverter.dll NppExport.dll NppTextFX.dll PluginManager.dll QuickText.UNI.dll zoomdisabler.dll 

## Other info
I was speaking with someone named "cmeriaux" on the NPP Community Forum, and he said the following:

> I suspect this commit to be the source of your problems :
>
> Commit SHA-1: 39df01dab5e8bf1d3ebfe1ae81499b9255e3c1ab  
> * Add SmartHighLight node for config.xml generation
>

I'm not sure if that's correct, but I thought it might be helpful.

**Comment by digger78** [comment]
FYI--I am still experiencing this issue on v7.3.

**Comment by MetaChuh** [comment]
please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins if you update from version 7.5.9 or below.
if your issue still persists, and it is still of relevance, please feel free to file a new issue as easy to understand and reproducible as possible.

thank you for your help and best regards.
