### ISSUE TITLE
ClearType in tooltips despite windows settings

### ISSUE THREAD

**Issue by helperman** [notepad-plus-plus/notepad-plus-plus#2655]
### Description of the Issue

Tooltips are shown using ClearType despite Windows settings.

### Steps to Reproduce the Issue

1. Set Windows options to do not use ClearType, see screenshot: 
http://storage5.static.itmages.ru/i/16/1209/h_1481299959_1765014_d8a5d40f99.png
http://storage5.static.itmages.ru/i/16/1209/h_1481299871_5889809_dc43919b03.png
2. Hover mouse pointer over a tab name in Notepad++, see a screenshot: 
http://storage6.static.itmages.ru/i/16/1209/h_1481299623_9558856_849e167e5c.png
2. A tooltip appears under cursor.

### Expected Behavior

Tooltip shows without ClearType.

### Actual Behavior

Tooltips shows using ClearType.

### Debug Information

Notepad++ v7.2.2   (32-bit)
Build time : Nov 27 2016 - 16:31:07
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : ON
Local Conf mode : OFF
OS : Windows 8.1
Plugins : mimeTools.dll NppConverter.dll NppExport.dll PluginManager.dll

**Comment by MetaChuh** [comment]
please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins if you update from version 7.5.9 or below.
if your issue still persists, and it is still of relevance to you, please feel free to file a new issue as easy to understand and reproducible as possible.

thank you for your help and best regards.

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
(no extra account is needed, just use your github account to sign in)
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)
