### ISSUE TITLE
Where is the Plugin Manager?

### ISSUE THREAD

**Issue by Herby95** [notepad-plus-plus/notepad-plus-plus#2656]
Hello,
where can I find the plugin manager in Notepad++ 7.2.2? In older versions I found it in the Extensions menu. Now I cannot find it anymore, even though it should be installed out of the box:

![grafik](https://cloud.githubusercontent.com/assets/18163544/21060042/c9ca4788-be45-11e6-8bd2-548d52dcae7c.png)

**Comment by dail8859** [comment]
The plugin manager is not yet available for 64-bit Notepad++. Quote from the website:

> Note that the most of plugins (including Plugin Manager) are not yet available in x64
