### ISSUE TITLE
CSS inline comment

### ISSUE THREAD

**Issue by Drumstix42** [notepad-plus-plus/notepad-plus-plus#2657]
### Description of the Issue
Highlighting a partial line and using the comment hotkey(s) result in the entire line being commented out.

### Steps to Reproduce the Issue
1. Open a CSS file
2. Highlight a part of a line
3. Use (CTRL+K) or (CTRL+Q)

### Expected Behavior
I'd expect the /* comment */ block characters to be wrapped around the current cursor selection. This used to work correctly a couple versions ago.

### Actual Behavior
The entire line is wrapped in a block comment

**Comment by MetaChuh** [comment]
please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins if you update from version 7.5.9 or below.
if your issue still persists, and it is still of relevance to you, please feel free to file a new issue as easy to understand and reproducible as possible.

thank you for your help and best regards.

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
(no extra account is needed, just use your github account to sign in)
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)

**Comment by Drumstix42** [comment]
This issue still exists, exactly as explained above. Not sure why it was closed.

**Comment by sasumner** [comment]
@Drumstix42 said

>I'd expect the /* comment */ **_block_** characters...

Then shouldn't you use the "block" version of the comment command?:

![image](https://user-images.githubusercontent.com/30118311/57162675-ed0f6880-6dbc-11e9-9d76-64a7f7687afa.png)

Trying this seems to do the correct thing.

Ctrl+Q and Ctrl+K are both "single line" variants.

**Comment by Drumstix42** [comment]
> 
> 
> @Drumstix42 said
> 
> > I'd expect the /* comment */ **_block_** characters...
> 
> Then shouldn't you use the "block" version of the comment command?:
> 
> ![image](https://user-images.githubusercontent.com/30118311/57162675-ed0f6880-6dbc-11e9-9d76-64a7f7687afa.png)
> 
> Trying this seems to do the correct thing.
> 
> Ctrl+Q and Ctrl+K are both "single line" variants.

Thank you. This helps me out.
