### ISSUE TITLE
[Language] Rust is not detected in Notepad++

### ISSUE THREAD

**Issue by AraHaan** [notepad-plus-plus/notepad-plus-plus#2658]
### Description of the Issue
Notepad++ does not recognize rust code files.

### Steps to Reproduce the Issue
1. Install Rust.
2. use Cargo to create a new library in rust.
3. Open a rust source code file (`*.rs`)

### Expected Behavior
Syntax Highlighting and a Display on status bar saying `rust Source File`.

### Actual Behavior
Rust Source Files being treated like normal text files.

### Debug Information
```
Notepad++ v7.2.2   (32-bit)
Build time : Nov 27 2016 - 16:31:07
Path : E:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 7
Plugins : MenuIcons.dll mimeTools.dll NppConverter.dll nppcrypt.dll NppExec.dll NppExport.dll NppFTP.dll NPPJSONViewer.dll NppSaveAsAdmin.dll PluginManager.dll PyNPP.dll Python Indent.dll PythonScript.dll ReloadButton.dll Translate.dll ZenCoding-Python.dll zoomdisabler.dll 
```

**Comment by FrankSpitulski** [comment]
Rust is not officially supported by notepad++. You have to use a plugin if you want that feature.

**Comment by redmanmale** [comment]
@AraHaan 
Highlighting support for all languages are provided by Scintilla.
You shoud ask about it at [Scintilla's feature requests page](https://sourceforge.net/p/scintilla/feature-requests/search).
Or you could write your own custom language definition.

**Comment by dail8859** [comment]
Closed by 02bdd11700e6fb225157aa59f1f5f1a453865cee

**Comment by Moth-Tolias** [comment]
seems to be an issue as of this writing - a regression?

**Comment by spakecdk** [comment]
Still unsolved

**Comment by dail8859** [comment]
@spakecdk 

 Works for me. Please open an issue a new issue.

![image](https://user-images.githubusercontent.com/3694843/81596476-285e5300-9392-11ea-8eb5-5f49832c0c36.png)

**Comment by spakecdk** [comment]
my bad, somehow the issue is my theme (solarized light)
