### ISSUE TITLE
Opening file while NPP is minimized doesn't re-activate NPP window

### ISSUE THREAD

**Issue by dlandis** [notepad-plus-plus/notepad-plus-plus#266]
I coped this issue from sourceforge because I hope it isn't forgotten. It's really been annoying me over the past few months. I can confirm the defect is still present in 6.7.8.2. It always occurs, i.e. NPP always stays minimized after opening a file if it was already minimized. This is definitely a newish issue too.

Sourceforge description (#5132):
Bug has occurred since 6.6.9
If I have NPP minimized and open a new file, NPP just loads the file and stays minimized instead of restoring the window and moving it to the front like it did in the past.
However, if it isn't minimized and I open a new file the window is activated and brought to the front like usual.
OS: Windows 8.1 x64, Windows 7 x64

**Comment by dlandis** [comment]
This seems to be working properly now as of a few days ago. I thought I remembered installing an update but my build version is still showing 6.7.9.2. So not sure...maybe rebooting my machine temporarily has fixed the issue.

**Comment by jalgit** [comment]
I just noticed it in 6.9. I'm not sure whether it's in previous versions, as I've never noticed it before. Quite annoying!

**Comment by ifmihai** [comment]
i've updated to last version (7.2.1 x86)
this bug is still present
(i thought there's something wrong with my windows, not with NPP)
indeed, quite annoying

**Comment by stephancurran** [comment]
This is not an issue in 7.5.4. It might be time to close this issue.

**Comment by AngryGamer** [comment]
That's not completely accurate. If Notepad++ is opened with "run as administrator", and minimized, then it will not restore the window when opening a new file.

**Comment by stephancurran** [comment]
That appears to be true for other applications on Windows 7 too. I checked VLC, LibreOffice, Firefox, and Chrome; all will restore when a new file is opened from Explorer, unless they're in Administrator mode. Maybe it has to do with the way Windows treats Admin windows?

**Comment by CookiePLMonster** [comment]
Since, as stated, it seems to be standard Windows behaviour, I am bumping it and voting for closing the issue. With 2.000+ open issues in the project, things like this should really go since they are technically invalid for years by now.

**Comment by donho** [comment]
Update your Notepad++ to v7.6.6.
If this bug persists in the new release, please open a new issue with the debug information.
