### ISSUE TITLE
User Defined Language - Dialog too big for 1920x1080 laptop screen

### ISSUE THREAD

**Issue by assad-ebrahim** [notepad-plus-plus/notepad-plus-plus#2661]
The dialog box for Language > User-defined... is larger than 1080 pixels high, which means the bottom is cutoff a typical 1920x1080 screen.

### Steps to Reproduce the Issue

1. Install Notepad++ on a 1920x1080 or smaller screen
2. Language menu > User-defined...
3. 

### Expected Behavior

A dialog that was fully visible in the screen to appear.

### Actual Behavior

The dialog box was too big, so I could not see/change  lower-down fields.
### Debug Information

Notepad++ v7.2.2   (32-bit)
Build time : Nov 27 2016 - 16:31:07
Path : C:\totalcmd\ToolboxEditors\Notepad++\notepad++.exe
Admin mode : ON
Local Conf mode : ON
OS : Windows 8.1
Plugins : MathPad.dll mimeTools.dll NppCCompletionPlugin.dll NppConverter.dll NppExec.dll NppExport.dll NppFTP.dll NppSnippets.dll NPPTextFX.dll PluginManager.dll Pork2Sausage.dll RunMeU.dll ScrollPastEOFUni.dll SnippetPlus.dll SpeechPlugin.dll SpellChecker.dll TopMostU.dll

**Comment by julienm116** [comment]
+1

**Comment by MetaChuh** [comment]
not reproducible on 7.6.6

please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins if you update from version 7.5.9 or below.

thank you for your help and best regards.

<img width="1055" alt="" src="https://user-images.githubusercontent.com/45773305/57038976-9e968880-6c5b-11e9-8a8a-6660d4bcd3e1.png">
