### ISSUE TITLE
Find \A\Z inconsistent behaviour

### ISSUE THREAD

**Issue by KenYN** [notepad-plus-plus/notepad-plus-plus#2671]
When searching for an empty buffer, `\A\Z` is the recommended string, but pressing Find Next once matches, but pressing again gives "Find: Can't find the text \A\Z"

### Correct Behaviour

1. Select File/New, and press Ctrl+F to bring up find dialog.
2. Type `\A\Z` as the "Find what" string.
3. Press "Find Next" a few times and observe it finds OK, and prompts in green about wrapping round.

### Incorrect Behaviour

1. Open up an existing non-empty file or just type some text into the previous window.
2. Type `\A\Z` as the "Find what" string.
3. Press "Find Next" once and a tooltip at EOF incorrectly says "^ zero length match".
4. Press "Find Next" again and an error correctly says "Find: Can't find the text "\A\Z"".
5. Press "Find Next" again and we are back to the incorrect behaviour at 3.
6. Press "Find Next" again and the correct error reappears

### Expected Behavior
1. Open up an existing non-empty file or just type some text into the previous window.
2. Type `\A\Z` as the "Find what" string.
3. Press "Find Next" and an error correctly says "Find: Can't find the text "\A\Z"".
4. Press "Find Next" again and the same correct error appears.

### Debug Information
Notepad++ v7.2.2   (32-bit)
Build time : Nov 27 2016 - 16:31:07
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : ON
Local Conf mode : OFF
OS : Windows 7
Plugins : ComparePlugin.dll mimeTools.dll NppConverter.dll NppExport.dll NppFTP.dll NPPSvn.dll PluginManager.dll 

Also see [this StackOverflow answer](http://stackoverflow.com/a/41093958/1270789).

Note also that for Replace, "Find Next" then "Replace" exhibits incorrect behaviour, "Replace All" works as expected.

**Comment by MetaChuh** [comment]
please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins if you update from version 7.5.9 or below.
if your issue still persists, and it is still of relevance to you, please feel free to file a new issue as easy to understand and reproducible as possible.

thank you for your help and best regards.

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
(no extra account is needed, just use your github account to sign in)
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)
