### ISSUE TITLE
Problems handling mid to large files

### ISSUE THREAD

**Issue by foxmurder** [notepad-plus-plus/notepad-plus-plus#2677]
### Description of the Issue
The program is not able to efficiently search, replace, copy & paste, scroll up & down and in general operate when handling mid to large files (i.e. 100k to 5 million lines). Some times I have to open them in NOTEPAD (wtf!!) to copy and paste lines. There are situations in which it gets frozen by simple writing.  There should be no situations in which NOTEPAD is faster or better performing than NOTEPAD++

### Steps to Reproduce the Issue
1. Open any file with 3 million lines and try to perform common operations like go to the end on the document (Ctrl+End), copy and paste, write, etc.

### Expected Behavior
Editing should be very smooth and fast

### Actual Behavior
It becomes almost impossible to operate with large files

**Comment by dail8859** [comment]
> no situations in which NOTEPAD is faster or better performing than NOTEPAD++

You do realize Notepad++ does **so** much more than regular Notepad. I routinely edit large files. Here's what I've found out can improve performance:

- Disable word wrap
- Disable auto-complete for words
- Disable periodic backups
- And very importantly, check to see what plugins you have installed!!! Some of these are horrible at handling large files.

**Comment by foxmurder** [comment]
Thanks for your feedback. I certainly know notepad++ does much more that regular notepad and therefore, I could not believe how slow it was. I needed some help to make it improve. I'll implement what you commented.
Thanks again!

**Comment by foxmurder** [comment]
I just saw the problem is the language definition. Everything is fast when I disable it. I wouldn't like to have to disable it though, it's very useful. I'll try to see if I can simplify it

**Comment by MetaChuh** [comment]
please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins if you update from version 7.5.9 or below.
if your issue still persists, and it is still of relevance, please feel free to file a new issue as easy to understand and reproducible as possible.

thank you for your help and best regards.
