### ISSUE TITLE
Auto-complete in 7.2.2

### ISSUE THREAD

**Issue by ShorePatrol** [notepad-plus-plus/notepad-plus-plus#2678]
### Description of the Issue
Auto-complete inserts two closing tags instead of one closing tag

### Steps to Reproduce the Issue

1. Turn on html/xml close tag
2. Open new document, change to HTML language
3. Type < html > (or any tag) and you will see it inserts two < / html>< / html> tags

### Expected Behavior
Only 1 closing tag should be inserted

### Actual Behavior
Two closing tags inserted

**Comment by dail8859** [comment]
Please post your debug info. Most like you have XML Tools installed which is also automatically closing tags.

**Comment by ShorePatrol** [comment]
Debug info:
Notepad++ v7.2.2   (32-bit)
Build time : Nov 27 2016 - 16:31:07
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10
Plugins : ComparePlugin.dll Explorer.dll HTMLTag_unicode.dll mimeTools.dll NppConverter.dll NppExport.dll NppFTP.dll PluginManager.dll PreviewHTML.dll Snip2Code.dll

**Comment by ShorePatrol** [comment]
Ok, I fixed it - just needed to uncheck html/xml close tag - not sure why - but it works now.

**Comment by dail8859** [comment]
Most likely another plugin conflicting with Notepad++'s built in auto completion. If you disable your plugins that will tell you for sure.
