### ISSUE TITLE
Reset configurations on every update

### ISSUE THREAD

**Issue by spem** [notepad-plus-plus/notepad-plus-plus#2679]
### Description of the Issue
Every time Notepad++ is updated all my configurations of shortcuts and customize toolbar plugin, are reset to original.

### Expected Behavior
I expect to on update, no replace of the config files if exist, unless its real neded.

**Comment by cmeriaux** [comment]
please debug info
You should be in "Local Conf mode : OFF" so that settings are stored in application data

**Comment by MetaChuh** [comment]
please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins if you update from version 7.5.9 or below.
if your issue still persists, and it is still of relevance, please feel free to file a new issue as easy to understand and reproducible as possible.

thank you for your help and best regards.
