### ISSUE TITLE
Notepad++ autocomplete

### ISSUE THREAD

**Issue by batata004** [notepad-plus-plus/notepad-plus-plus#2685]
I am using autocomplete of Notepad++ and it's really good. But there is something that is really terrible compared with Dreamweaver autocomplete.

For example, if I type:

   `<div sty`

the notepad++ will show me a list of autocomplete options. If I just hit ENTER notepad++ will make this:

`<div style`

Great, it works. But in Dreamweaver the same happens but it does this:

`<div style=""`

You see? Dreamweaver already adds que = and double quotes and insert the cursor right in the middle of "" so I can continue typing the content. How can I make notepad++ make this?

**Comment by simon33-2** [comment]
Adding to this, when I used EditPlus autocomplete also provided functionality like this:

type "if ", you could tell it to insert this in its place:

if <cursor> then
<indent>
endif;

If you had this you would wonder why Python removed the block closing delimiters!

**Comment by simon33-2** [comment]
Oh actually, can't you edit the .xml under API/plugin or similar for <lang>.xml? @batata004

**Comment by batata004** [comment]
@simon33-2 I appreciate your help but after reading 3 times I didnt understand what you said. Could you tell me how can I mae notepad++ add 

=""

right after I type style?

**Comment by simon33-2** [comment]
In some subdirectory of the Notepad++ directory, there will be an xml file for that language. Let's say we are talking about html. Look for a file called html.xml. IIRC it is under API\plugins or plugins\API. I'm also unsure of the singular vs plural.

If you add the ="" to the style section of that file it would add it.

**Comment by batata004** [comment]
Ok, I found it at C:\Program Files (x86)\Notepad++\plugins\APIs and it worked. But there is a problem the cursor is moved to the right of the last quote. I would like this

style="<cursor>"

But I am getting this:

style=""<cursor>

Anyway to solve this?

**Comment by simon33-2** [comment]
Not any that I am aware of.

**Comment by batata004** [comment]
:( so I will stick with dreamweaver

**Comment by simon33-2** [comment]
Looks like there are a couple of plugins which do achieve it. Got it working with finger text. 

Close issue?

**Comment by batata004** [comment]
Obrigado, closed
