### ISSUE TITLE
Horizontal scrollbar does not change / disappear according to longest line when deleting

### ISSUE THREAD

**Issue by stonecrusher** [notepad-plus-plus/notepad-plus-plus#2687]
### Steps to Reproduce the Issue
1.  Turn linewrap off
2.  Write much text in one line
3.  Delete the text, beginning at the end

### Expected Behavior
The size of the scrollbar itself should change accordingly:
- Text exceeding window size just a bit ➡️ big scrollbar (big width). 
- Text exceeding window size a lot ➡️ small scrollbar
- Text not exceeding window size ➡️ horizontal scrollbar should disappear.

So actually it is just the inverse behaviour of writing a long line, where the scrollbar appears when window size is exceeded and then gets smaller, the longer the line is. Just like you're used to from other programs.

### Actual Behavior
The horizontal scrollbar stays always visible, even if there is no line anymore which exceeds the window size. The scrollbar does not resize, it can only become smaller.

### Debug Information
Notepad++ v7.2.2   (32-bit)
Build time : Nov 27 2016 - 16:31:07
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 8.1
Plugins : combine.dll ComparePlugin.dll HTMLTag_unicode.dll mimeTools.dll NppConverter.dll NppExport.dll NppFTP.dll NppTextFX.dll PluginManager.dll Tidy2.dll 

Also happens with plugins deactivated (folder renamed).

**Comment by stonecrusher** [comment]
I interchanged horizontal and vertical at first, so I couldn't find similar Issues #926 and #2211. Sorry.
I have no idea how to implement [A-R-C-A's answer](https://github.com/notepad-plus-plus/notepad-plus-plus/issues/2211#issuecomment-243297513).

**Comment by MetaChuh** [comment]
please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins if you update from version 7.5.9 or below.
if your issue still persists, and it is still of relevance, please feel free to file a new issue as easy to understand and reproducible as possible.

thank you for your help and best regards.

**Comment by sasumner** [comment]
IIRC this is a Scintilla issue and Scintilla maintainers strongly said they aren't going to fix the case where the scrollbar should disappear.  In other words, once the horizontal scrollbar appears, that's it, it stays.  Sorry I can't cite a reference to this.

**Comment by SirProdigle** [comment]
It is possible to add this behaviour with a plugin. Scintilla has functions to set scrollbar width, but you would need to frequently check longest line length and adjust accordingly which is presumably why they don't do it by default.
