### ISSUE TITLE
Application has generated an exception that could not be handled

### ISSUE THREAD

**Issue by DanAtkinson** [notepad-plus-plus/notepad-plus-plus#269]
I awoke the application from hibernation and Notepad++ presented me with the following exception:

> notepad++.exe - Application Error
> Application has generated an exception that could not be handled
> Process ID=0x34b8 (13946), Thread ID=0x34b8c (13452).
> Click OK to terminate the application.
> Click CANCEL to debug the application

![image](https://cloud.githubusercontent.com/assets/23440/8266631/c87ef814-1730-11e5-87da-83488021a784.png)

When I debug, the following is returned:

> System.Runtime.InteropServices.COMException was unhandled
> Message: An unhandled exception of type 'System.Runtime.InteropServices.COMException' occurred in mscorlib.dll
> Additional information: The handle is invalid. (Exception from HRESULT: 0x80070006 (E_HANDLE))

Any more information needed, please let me know.

I have a folder full of (169) crash reports that I can also provide if needed. I'm not sure of their worth however.

**Comment by ariccio** [comment]
That looks like a `C++/CX`, a `C#`, or a `CLI`/`.NET` exception.... What plugins do you have installed?

**Comment by gigamac** [comment]
I am getting the same problem:
{"The handle is invalid. (Exception from HRESULT: 0x80070006 (E_HANDLE))"}
debug info:
Notepad++ v7.3.1   (32-bit)
Build time : Jan 17 2017 - 00:21:10
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 7
Plugins : BracketsCheck.dll HexEditor.dll mimeTools.dll NppBookmarkManager.dll NppColumnSort.dll NppConverter.dll NppExport.dll NppRegExtractorPlugin.dll NppSaveAsAdmin.dll NppXmlTreeviewPlugin.dll PluginManager.dll PyNPP.dll RunMe.dll sql.dll XMLTools.dll XPatherizerNPP.dll

**Comment by cmeriaux** [comment]
try to disable plugins

**Comment by gigamac** [comment]
it stopped when xpatherizer was removed  -so yes u r right.
Sadly though xpatherizer is really useful for me in my work, so could do with an alternative...

**Comment by dail8859** [comment]
Closing since the original issue is most certainly plugin related.
