### ISSUE TITLE
Portable NPP deletes unsaved files of another portable instance

### ISSUE THREAD

**Issue by osoba** [notepad-plus-plus/notepad-plus-plus#2690]
### Description of the Issue
On win32 using the 7z package (that is, the portable version of NPP)
If you copy/paste the entire portable folder containing NPP and close the unsaved files in the copied instance, they will be deleted in the original instance too

### Steps to Reproduce the Issue
1. extract the 7z package somewhere on your pc
2. run NPP and open a new file and type some random text
3. close NPP and don't save the file (if you reopen NPP the file will still be there, open, unsaved)
4. copy the entire NPP folder somewhere else on your pc
5. run NPP from the copied place (it will still open the unsaved file)
6. now close the unsaved file and dont save it, then close NPP
7. run the original NPP (the one you copied from)
8. unsaved file will be gone from that instance too

### Expected Behavior
Portable instances should be independent of each other, the unsaved files should remain open and unsaved in the original portable instance

### Debug Information
Notepad++ v7.2.2   (32-bit)
Build time : Nov 27 2016 - 16:31:07
Path : D:\apps\npp.7.2.2.bin\notepad++.exe
Admin mode : OFF
Local Conf mode : ON
OS : Windows XP
Plugins : mimeTools.dll NppConverter.dll NppExport.dll PluginManager.dll

**Comment by MetaChuh** [comment]
please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins if you update from version 7.5.9 or below.
if your issue still persists, and it is still of relevance to you, please feel free to file a new issue as easy to understand and reproducible as possible.

thank you for your help and best regards.

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
(no extra account is needed, just use your github account to sign in)
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)
