### ISSUE TITLE
Unix script file: a flaw in string recognition

### ISSUE THREAD

**Issue by mikekaganski** [notepad-plus-plus/notepad-plus-plus#2691]
### Description of the Issue
In Unix script files (e.g. *.sh), a command like this:
`            @opts = split(/'/);`
results in wrong string recognition. Starting from apostrophe, and on following lines, everything becomes highlighted as string.

**Comment by PalashBansal** [comment]
Its a correct behavior from NPPP.
I guess, you are mistaking it with `@opts = split(\'\);`
Backslash( **\\** ) ignores quotes( **'** & **"** ), not forward slash( **/** ).
Compare on some online IDE like [https://www.tutorialspoint.com/execute_bash_online.php](https://www.tutorialspoint.com/execute_bash_online.php)

**Comment by mikekaganski** [comment]
http://opengrok.libreoffice.org/xref/core/autogen.sh#85

**Comment by mikekaganski** [comment]
Now I see. That's a perl file with a hack to be initially executed as shell script. Sorry for the noise.
