### ISSUE TITLE
 Incorrectly file show binary 

### ISSUE THREAD

**Issue by DariusBabrauskas** [notepad-plus-plus/notepad-plus-plus#2692]
### Steps to Reproduce the Issue

1.  Open file bad.txt
2.  File size must be 4096 but show 5875
3.  Incorrectly information show least characters must be 0xFF, but show 0xEF, or 0xBF ....
![bad](https://cloud.githubusercontent.com/assets/24562266/21173711/bcd01504-c1e1-11e6-9c2c-2049a66b3a65.png)

### Actual Behavior

[bad.txt](https://github.com/notepad-plus-plus/notepad-plus-plus/files/651024/bad.txt)

### Debug Information

Notepad++ v7.2.2   (32-bit)
Build time : Nov 27 2016 - 16:31:07
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : ON
Local Conf mode : OFF
OS : Windows 10
Plugins : ComparePlugin.dll mimeTools.dll NppConverter.dll NppExport.dll PluginManager.dll

**Comment by SinghRajenM** [comment]
Please refer below about file size. You can see this info by double clicking on length on status bar.

![image](https://cloud.githubusercontent.com/assets/14791461/21191924/c0fb3fd0-c24c-11e6-85b8-01b271fbf63f.png)

**Comment by DariusBabrauskas** [comment]
Problem that file context show incorectly...  last simbols must be xff...
Notepad ++ showing  xbf xfe ...!!!!!
File bad.txt size is 4096 but notepad++ showing 5875 !!!!
Its critical error...

2016 gruod. 14 19:01 "Rajendra Singh" <notifications@github.com> rašė:

**Comment by rmpressler** [comment]
Darius,

It sounds like you're mixing up character count and file size. The file size is 4,096 bytes. Notepad++ is not showing file size at the bottom of the window, it's showing you the number of characters (5,875 characters). Depending on encoding, this can vary from the actual file size in different ways.

**Comment by DariusBabrauskas** [comment]
It looks like critical error.  I attached picture bad_txt_show_ok . It show, how should be bad.txt  in hex format with good hex viewer.
![bad_txt_show_ok](https://cloud.githubusercontent.com/assets/24562266/21341818/253a99b6-c697-11e6-8daf-0a0aa2984ae6.png)
And how show same file notepad++. What it is?
![bad_hex](https://cloud.githubusercontent.com/assets/24562266/21341869/601dd4f8-c697-11e6-9bbf-653ef10298e9.png)
?

**Comment by MetaChuh** [comment]
this is not a file type notepad++ can or should process.

thank you for your help and best regards.
