### ISSUE TITLE
Plug-in to collapse hyperlinks

### ISSUE THREAD

**Issue by leosdad** [notepad-plus-plus/notepad-plus-plus#2694]
Hi, I wonder if someone could come up with a plug-in to collapse hyperlinks. For example, I have files with many lines like this:

- Effects render differently at different zooms (_https://affinity.serif.com/forum/index.php?/topic/31523-live-effect-defringe-looks-different-depending-on-zoom/_)

It would be very nice if Notepad++ optionally displayed them like this:

- Effects render differently at different zooms [(_link_)](url)

Is this feasible? Thanks.

**Comment by MetaChuh** [comment]
plugin requests are not processed at the notepad++ issue tracker.

thank you for your help and best regards.
