### ISSUE TITLE
Add  "End of line filled" scintilla option in Style configurator dialog box.

### ISSUE THREAD

**Issue by Cyrillev91** [notepad-plus-plus/notepad-plus-plus#2698]
Add  "End of line filled" scintilla option in Style configurator dialog box.

![eolfilled_styleconfigurator2](https://cloud.githubusercontent.com/assets/12849364/21285459/74b3d904-c439-11e6-8c16-0f8e07453026.jpg)

Many lexer use eolfilled option to Highlight string not close but not active in npp,

**Comment by MetaChuh** [comment]
closed as part of https://github.com/notepad-plus-plus/notepad-plus-plus/pull/2699
