### ISSUE TITLE
Numeric sorting

### ISSUE THREAD

**Issue by zhazho** [notepad-plus-plus/notepad-plus-plus#27]
Although Notepad++ native sort tend to lock on bigger files and one must use TextFX sorting which works just fine, there is still no way to sort files in numeric order.

Anyone know of any plugin (or some other way) to do that?

**Comment by einst3** [comment]
i use regex to change numbers to same format length with leading zeros then sort then regex it back to numbers. its a terrible workaround but it works.

**Comment by zhazho** [comment]
hi, einst3,

you sure deserve your username for that solution :). is it maybe possible for you to take some time and create macro to do this? i'm sure that crossed your mind? what i did was to create small c program that does this for me. but it's still annoying to have to use external program to sort file!!!

furthermore since we're all here because we love using n++ i think author should take this issue into consideration more seriously and implement it in next buid.

and it's really strange that there was no one else but you and me posted something like this years ago, don't you think?

**Comment by einst3** [comment]
i use the TextFX plugin to sort lines. no external program needed.
Menu - TextFX - TextFX Tools - sort lines case [in]sensitive (at column).
ps. im way to busy to write macros for one program. i have a txt regex script file i use for various find/replace. it works for almost any program i use.

**Comment by zhazho** [comment]
yes, yes, absolutely understandable...
thanx for your replies...

On 8 May 2015 at 20:02, Tony Paulos <notifications@github.com> wrote:

> i use the TextFX plugin to sort lines. no external program needed.
> Menu - TextFX - TextFX Tools - sort lines case [in]sensitive (at column).
> ps. im way to busy to write macros for one program. i have a txt regex
> script file i use for various find/replace. it works for almost any program
> i use.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/donho/notepad-plus-plus/issues/27#issuecomment-100314223>
> .
>



-- 
*Srdačan pozdrav,*
Saša Živković
Brazal agencija <http://brazal.net>

**Comment by donho** [comment]
Line Sorting is enhanced from v6.7.9.
