### ISSUE TITLE
Move 'Replace In Files' into dedicated tab

### ISSUE THREAD

**Issue by dev-101** [notepad-plus-plus/notepad-plus-plus#270]
Hi, I have a suggestion for search window to move 'Replace In Files' button on the separate/dedicated tab. I use first feature ('Find All') very frequently, and the last feature (Replace in Files') extremely rare, but due to the closeness of both buttons, couple of times accidentally hit `Replace in Files` instead of `Find All` button. You see how dangerous this can be if you work on a live files without any backup? Particularly, in case when `Replace with` field is blank, so there is no easy reversed way back. Thus, I think that this special function should be moved outside find block.

![notepad replace in files](https://cloud.githubusercontent.com/assets/5383059/8266763/908b940c-1740-11e5-8683-11d6df6a2cf5.png)

Also, while reorganizing tabs, this order could be more appropriate:

`Find - Find in Files - Replace - Replace in Files - Mark`

which would give enough spacing between the two.

I understand that this would require duplicating functionality and functions on tabs with some separation and removal of input fields (like removal of `Replace with` on `Find in Files` tab), but it would be much more user friendly and organized, without possibility for an accidental replacement.

Thanks

**Comment by h-h-h-h** [comment]
With these many tabs I would prefer the order:
```
Find - Replace - Mark - Find in Files - Replace in Files
```

But the last two could even completely disappear. Maybe checkboxes would be the best way to get the controls for file operations on the first two tabs. It should be somewhere away from the other options, maybe near the transparency checkbox.

**Comment by dev-101** [comment]
Hi h-h-h-h, yes, that could be even better, just move it out of search place, to be safe. I always get uncomfortable around that button.

**Comment by Graham-G** [comment]
It already does an "Are you sure?" dialog box when pressing `Replace in files`; I think this change is somewhat unnecessary.

**Comment by dev-101** [comment]
After 3 years?? I don't really remember how it worked then, maybe the dialog was added later.
Anyway, it's not important anymore ;)

**Comment by sasumner** [comment]
> You see how dangerous this can be if you work on a live files without any backup?

No, it is not "dangerous" because Replace in Files has a confirmation popup.

**Comment by JavaScriptDude** [comment]
FWIW, I completely agree it would be best to have the "Replace in Files" to a separate tab would be the ideal solution. That button has always scares the hell out of me and although there is a "are you sure" popup, its still possible for someone to accidentally hit the wrong buttons while not paying attention and have the world go to s#(%, even worse in Production. 

This issue is has me thinking of switching over to something like VS Code or Atom.

**Comment by sasumner** [comment]
@JavaScriptDude Hopefully people editing files "in Production" are actually "paying attention".  I think it ("Replace in Files") is OK where it is.  I've used Notepad++ for 4+ years now and have never "accidentally hit" this button by mistake (that I recall), and even if I did I'm certain that if I did I didn't confirm the action.

But...your opinon has been noted.  Cheers.
