### ISSUE TITLE
Notepad++ v7.2.2 never really closes anymore

### ISSUE THREAD

**Issue by michael-milette** [notepad-plus-plus/notepad-plus-plus#2700]
### Description of the Issue
Notepad++ never really closes. Only the UI disappears. The application remains in memory, running as a background process according to Windows task manager.

I first noticed this issue back when there was a problem with the Notepad++ 7.2.1 updater. On a side note, even with Notepad++ 7.2.2, I still had to manually update the updater itself. I am not sure if that issue was related to this one. I can't say whether the bug was in 7.2.0 as I skipped that version.

### Steps to Reproduce the Issue
1) Open Notepad++ version 7.2.2.
2) Notice that Notepad++ is running in the list of Windows 10x64 processes (as it should)
3) Close Notepad++ by clicking on the X in the upper right corner.
4) Notice that Notepad++ has disappeared from the screen. (as it should)
5) Notice that the instance of Notepad++ is still in the Windows task list but now listed as a background process.

If the problem doesn't show up, open any text file (mine happen to be PHP source code files) between step 2 and 3 above. Then it happens 100% of the time for me.

### Expected Behavior
When you close Notepad++, the user interface should close (as it is doing now) and the process should end without leaving anything running in the background.

### Actual Behaviour
When I close Notepad++, I notice that it still appears in the Windows task manager on the processes tab. It is listed under background processes. If I repeat the steps multiple times, a new instance of Notepad++ is added to the list each time but never removed.

This issue also affects Notepad++'s updater when it wants to restart Notepad++ after installing a plugin. The updater just hangs forever or until I manually close some of the many instances of Notepad++ that I find running in the Windows task manager.

### Debug Information
Notepad++ v7.2.2   (32-bit)
Build time : Nov 27 2016 - 16:31:07
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10
Plugins : ccc.dll ComparePlugin.dll CustomizeToolbar.dll DoxyIt.dll DSpellCheck.dll EmmetNPP.dll Explorer.dll FingerText.dll HTMLTag_unicode.dll JSLintNpp.dll NppColumnSort.dll NppConverter.dll NppExec.dll NppExport.dll NppPlates.dll NppPlugin_PluginMargin.dll NppSaveAsAdmin.dll NppTaskList.dll NppTextFX.dll PluginManager.dll PythonScript.dll SpeechPlugin.dll Tidy2.dll zoomdisabler.dll

**Comment by michael-milette** [comment]
Found another person who is experiencing the same issue. See:
https://notepad-plus-plus.org/community/topic/12841/closing-np-does-not-really-close-the-application-anymore

**Comment by dail8859** [comment]
Try disabling your plugins to see if it is one of those causing the issue. You can either temporarily rename your "plugins" folder, or launch Notepad++ from the command line and run:

> "C:\Program Files (x86)\Notepad++\notepad++.exe" -noPlugin

**Comment by michael-milette** [comment]
Thanks for the tip. I tracked it down to the most recent (2009) release of explorer.dll which is v1.8.2.

It's quite unfortunate that this plugin now has compatibility issues. I had been using it since mind 2015 without any problem and will really miss it.

Anyone know of another plugin that provides similar functionality?

**Comment by michael-milette** [comment]
I've tried using the Workspace feature however I work on a project that has over 16,000 files and the workspace feature just isn't able to handle that many files.

**Comment by cmeriaux** [comment]
Try "light explorer". It's light, it provides favorites
There is also sherloXplorer which is nice.

**Comment by dail8859** [comment]
Glad to hear you tracked it down and hope you can find an alternative solution. Closing since this is 3rd party plugin related.

**Comment by Przbl** [comment]
Thanks guys for the plugin hint, in my case I found the culprit to be the jN plugin (https://github.com/sieukrem/jn-npp-plugin). The project seems alive but I can't find a dll file there and have no idea how to build one.

**Comment by michael-milette** [comment]
Even though I removed  explorer.dll, I still find Notepad++ running in the background every once in a while. Because it is no longer consistent, I am finding it challenging to track down which plugin is the culprit.

Anybody know why this wasn't an issue for many years and now it is?
