### ISSUE TITLE
missing turkish xml

### ISSUE THREAD

**Issue by gamzeakmann** [notepad-plus-plus/notepad-plus-plus#2701]
### Expected Behavior
Item id="44085" name="Çalışma Alanı Olarak Klasör"
This line should be added to xml.

### Actual Behavior
Item id="44085" name="Folder as &amp;Workspace"
This line is still missing in turkish xml.

I want to add.

**Comment by mertcalik** [comment]
This is a helpful change. But the same issue is valid for the "Trim Trailing and save" object, also.

**Comment by gamzeakmann** [comment]
I don't find "Trim Trailing and save" in xml file. But I have resolved "Folder as &Workspace" and I created PR #2702.

**Comment by mertcalik** [comment]
There are other differences between english and turkish xml files. Can you add the other items to the turkish xml?

**Comment by mertcalik** [comment]
It is really a very nice and helpful contribution. Thank you so much.

**Comment by gamzeakmann** [comment]
@mertcalik Can you check the changes?

**Comment by SinghRajenM** [comment]
@MetaChuh  this is fixed.. latest turkish has the translation for it...
https://github.com/notepad-plus-plus/notepad-plus-plus/blob/b2191e9e6f5ad82774ff6dac589e8da9c5ff8091/PowerEditor/installer/nativeLang/turkish.xml#L237
