### ISSUE TITLE
Restore config.model.xml to distribution, for centralised deployment

### ISSUE THREAD

**Issue by MarkMaldaba** [notepad-plus-plus/notepad-plus-plus#2704]
It appears that NP++ v7 has removed config.model.xml, which is used to define default configuration values when deploying to multiple workstations from a central location.

Perhaps there is a new way to handle this kind of deployment, and if so this is a documentation issue.

Or alternatively, if this file is no longer used to initialise a new installation then I would like to request that it is re-instated so that we can deploy NP++ with custom configuration to all our new developers.

**Comment by MarkMaldaba** [comment]
For reference, this was removed in 0746d1f4f717dea6c080785725b7de2b25cf8981, with little explanation.  Hopefully it should simply be a matter of reverting that commit.

**Comment by MarkMaldaba** [comment]
@donho Any thoughts on this?  We are currently unable to upgrade NP++ at our organisation due to this issue.

**Comment by IveGotThePawa** [comment]
Please advise on this, we need it to automate organisational deployment with specific init values. Until then we must remain with version 7.1

Thanks

**Comment by MarkMaldaba** [comment]
@donho What is the status of this?  Is it on the roadmap somewhere, or is it something that you do not plan to fix?

The simplest way of implementing this is probably a good compromise, too;  it means there is still no burden of maintenance for the external config.model.xml within the project, but restores the utility of this file for automated custom deployments:

1. Initialise the config variables internally from within the code (as currently happens)
2. [new bit] If there exists a `config.model.xml` in the Notepad++ directory, load it using exactly the same logic as the main config.xml is loaded.
3. Load `config.xml` (as currently happens)

Is this something you would consider adding to the next release?

**Comment by MetaChuh** [comment]
config.model.xml is still deployable to fresh installs and can be used as a template to create the users config.xml.

the only difference is, that a config.xml with default settings, will be created by notepad++ itself, if no config.model.xml or config.xml is present.

to create config.model.xml, perform the desired settings, exit notepad++ for the settings to be saved, and copy config.xml to config.model.xml, which you can deploy.

**Comment by MarkMaldaba** [comment]
You're right!  Finally, we can upgrade!

It's a real, real shame that it took nearly two and a half years for this ticket to get a response, which was basically - "yup - it already works like that".

Is this feature documented anywhere?  If not, it should be as it's really important and really useful for organisational deployment.

**Comment by MarkMaldaba** [comment]
> Is this feature documented anywhere?

Here would be a good place: http://docs.notepad-plus-plus.org/index.php/Configuration_Files
