### ISSUE TITLE
Text fields for text to search and text to replace with can be blank during replacing

### ISSUE THREAD

**Issue by Marcono1234** [notepad-plus-plus/notepad-plus-plus#2707]
### Description of the Issue
When you try to replace parts of a long text the text field containing the text to search is blank during replacing if it contained regex patterns and the text field containing the text to replace with becomes always blank.

After Notepad finished replacing the text pieces the text fields contain the text again.

### Steps to Reproduce the Issue (Search field)

1. Paste a long text into a window
2. Select regex searching
3. Use for example `.` as text to search
4. Perform replacing

### Steps to Reproduce the Issue (Replace field)

1. Paste a long text into a window
2. Write any text to replace with
3. Perform replacing

Note: Literal characters will remain in the search field during replacing.

### Expected Behavior
The text fields would keep the text while performing the replacing.

### Actual Behavior
Both text fields did not show the text during replacing.

### Debug Information
Notepad++ v7.2.2   (32-bit)
Build time : Nov 27 2016 - 16:31:07
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 7
Plugins : mimeTools.dll NppConverter.dll NppExport.dll NppFTP.dll PluginManager.dll

**Comment by MetaChuh** [comment]
please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins if you update from version 7.5.9 or below.
if your issue still persists, and it is still of relevance, please feel free to file a new issue as easy to understand and reproducible as possible.

thank you for your help and best regards.

**Comment by Marcono1234** [comment]
@MetaChuh, this is still the case. Can you please reopen the issue?
Though it appears the part about "regex" was incorrect, I am going to update it.

```
Notepad++ v7.6.6   (32-bit)
Build time : Apr  3 2019 - 23:49:50
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 7 (64-bit)
Plugins : none
```

**Comment by sasumner** [comment]
@Marcono1234 Personally, I would use it to my advantage:  It is Notepad++ telling me to not do anything further until it is done doing what it is off doing. :)

**Comment by Marcono1234** [comment]
I would not really consider this intended and proper feedback. It would be better if Notepad remained responsive and showed a progress indicator or similar, but that is a different topic.

**Comment by sasumner** [comment]
@Marcono1234 You get what you pay for. ;)  Also, your issue has been open for 2.5 years--oh, wait, now it is closed.  This can't be a good sign that it will get fixed.  Cheers.

**Comment by Marcono1234** [comment]
There is no reason to directly become passive-aggressive. My previous comment wasn't very well worded, I did not mean it as reproach. My intention was to clarify that using incorrect behavior (empty fields) as solution for something else is in my opinion not so great.
