### ISSUE TITLE
Undoing replace displays line breaks and text incorrectly

### ISSUE THREAD

**Issue by Marcono1234** [notepad-plus-plus/notepad-plus-plus#2708]
### Description of the Issue
When you undo a replace operation an a long text starting at some line a carriage return (CR) will be missing and after that all line feed (LF) carriage return (CR) combinations are displayed as characters and as line break. Additionally the last line might get invalid.

### Steps to Reproduce the Issue

1. Paste about 60,000 times `ab\n` in a window (I used the Python code `print "ab\n" * 60000`)
2. Replace `b` with `c` using the replace dialog
3. Undo the replacing
4. Scroll down

Note: Sometimes it does not work with 60,000 lines, then you might want to try it with more.

Beginning of the bug:
![replace undo bug beginning](https://cloud.githubusercontent.com/assets/11685886/21335404/ebcaeba0-c65e-11e6-9866-9b19a5bc5cee.PNG)
Last line:
![replace undo bug last line](https://cloud.githubusercontent.com/assets/11685886/21335405/ebcb8088-c65e-11e6-888f-db2d467a8b10.PNG)

### Expected Behavior
The text would be like it was before pieces were replaced

### Actual Behavior
CR and LF were displayed as characters and the last line contained a character twice instead of `ab`.

### Debug Information
Notepad++ v7.2.2   (32-bit)
Build time : Nov 27 2016 - 16:31:07
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 7
Plugins : mimeTools.dll NppConverter.dll NppExport.dll NppFTP.dll PluginManager.dll

**Comment by dail8859** [comment]
It is a know issue when working with large files that the periodic backup setting can corrupt the file. I'd suggest turning this off.

**Comment by Marcono1234** [comment]
Looks like you are right. Do you know other reports than #1700 about this?

**Comment by dail8859** [comment]
A quick search shows some related issues #2253, #2226, #1412, #1371, #919, #834 and probably others.

**Comment by Lob98** [comment]
> It is a know issue when working with large files that the periodic backup setting can corrupt the file. I'd suggest turning this off.

I have this issue once a weak if working actively while working with documents not more than 15000 lines. Those are not large files really. I guess it should be easier to replicate if set auto-save interval to 1 second and repeatedly edit the document.

**Comment by MetaChuh** [comment]
not reproducible on 7.6.6 with 68404 lines of ab\n

please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins if you update from version 7.5.9 or below.
if your issue still persists, and it is still of relevance, please feel free to file a new issue as easy to understand and reproducible as possible.

thank you for your help and best regards.

**Comment by Marcono1234** [comment]
Cannot reproduce either anymore, probably because #4803 has been fixed
