### ISSUE TITLE
CR/LF should use whitespace color

### ISSUE THREAD

**Issue by leonard84** [notepad-plus-plus/notepad-plus-plus#271]
Currently the CR/LF characters are using the normal default text color, but since they are displayed in an inverted fashion, e.g., black box with white characters, they are really 'heavy' visually. It would be far easier on the eye if they would use the whitespace color.

**Comment by ivan-radic** [comment]
This is a limitation of Scintilla.

http://www.scintilla.org/ScintillaDoc.html#StyleDefinition

Relevant part from the above link:

    STYLE_CONTROLCHAR 	36 	This style sets the font used when drawing control characters.
    Only the font, size, bold, italics, and character set attributes are used and not the colour attributes.

So, colour attributes of control characters (new line chars included) are not accessible to user.
You might try to post feature request on Scintilla bug tracker: http://sourceforge.net/p/scintilla/bugs/
Even better discuss it on their google group: https://groups.google.com/forum/#!forum/scintilla-interest

**Comment by leonard84** [comment]
Thanks for the info, I'll close this issue then.
