### ISSUE TITLE
Ability to delete the line you'r currently on (Ctrl-X or something), the opposite of Duplicate line (Ctrl-D) !

### ISSUE THREAD

**Issue by Larphoid** [notepad-plus-plus/notepad-plus-plus#2710]
### Steps to Reproduce the Issue

1. 
2. 
3.

**Comment by dail8859** [comment]
`Ctrl+Shift+L` by default is mapped to SCI_LINEDELETE.

**Comment by Larphoid** [comment]
Aah thanks. Couldn't find it in the Edit menu under Line operations.
