### ISSUE TITLE
Basic substring search is broken in 7.2.2 [mistaken]

### ISSUE THREAD

**Issue by ezimin** [notepad-plus-plus/notepad-plus-plus#2711]
### Description of the Issue
When you try to search for some part of thw whole word (like searching for "maxim" from the word "maximum" ), it does not work.

### Steps to Reproduce the Issue
1. Create "something.j2" file and paste any text like "maximum-labels 5;"
2. Try to search for "maxim"
3. You will not be able to find anything

### Expected Behavior
It's expected, that search should work even for part of the word, not only the whole word.

### Actual Behavior
Search for some substring does not work.

### Debug Information
Notepad++ v7.2.2   (64-bit)
Build time : Nov 27 2016 - 16:35:52
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : ON
Local Conf mode : OFF
OS : Windows 10
Plugins : mimeTools.dll NppConverter.dll 
![npp](https://cloud.githubusercontent.com/assets/15369088/21393257/b72570ea-c7a4-11e6-96cb-a34cd3e0a594.png)

Screenshot attached.

**Comment by MAPJe71** [comment]
Hint: the solution/answer is in your screen dump.

**Comment by ezimin** [comment]
@MAPJe71 If you mean "direction" or "Search mode" (Regular/Extended/Reg.exp), changing these options has no effect.

**Comment by dail8859** [comment]
You have "Только целые слова" check marked.

**Comment by ezimin** [comment]
Oh sh... :) 
Sorry, guys. Let's close/remove this. Definitely my fault :)
