### ISSUE TITLE
"run macro multiple times" fails 4% of times when using clipboard.

### ISSUE THREAD

**Issue by Leaveyou** [notepad-plus-plus/notepad-plus-plus#2715]
### Description of the Issue
Notepad++ sometimes fails to copy to or paste from clipboard when running a macro multiple times.

### Steps to Reproduce the Issue

1.  Create a file containing 50 lines of the following text: "`aaaaaaaa,bbbbbbbb`"
2. Place cursor on first line, first character and start recording a macro
3. Do the following actions during macro recording: 
* press END
* press ctrl+shift+left (to select last word)
* press ctrl+x to cut
* press backspace to delete last coma
* press Home to move to start of row
* press ctrl + V to paste
* press comma to ad it
* press down to move to next row
4. Stop macro recording
5. Run the macro until end of file via menu "Macro" -> "run a macro multiple times"
### Expected Behavior
The file should contain the strings reversed: 
```
bbbbbbbb,aaaaaaaa
bbbbbbbb,aaaaaaaa
bbbbbbbb,aaaaaaaa
...
```
### Actual Behavior
Macro fails randomly and sometimes fails to copy-paste the text:
```
bbbbbbbb,aaaaaaaa
bbbbbbbb,aaaaaaaa
bbbbbbbb,aaaaaaaa
bbbbbbbb,aaaaaaaa
,aaaaaaaa
bbbbbbbb,aaaaaaaa
bbbbbbbb,aaaaaaaa
bbbbbbbb,aaaaaaaa
bbbbbbbb,aaaaaaaa
bbbbbbbb,aaaaaaaa
bbbbbbbb,aaaaaaaa
bbbbbbbb,aaaaaaaa
bbbbbbbb,aaaaaaaa
bbbbbbbb,aaaaaaaa
bbbbbbbb,aaaaaaaa
bbbbbbbb,aaaaaaaa
bbbbbbbb,aaaaaaaa
bbbbbbbb,aaaaaaaa
bbbbbbbb,aaaaaaaa
bbbbbbbb,aaaaaaaa
bbbbbbbb,aaaaaaaa
bbbbbbbb,aaaaaaaa
bbbbbbbb,aaaaaaaa
bbbbbbbb,aaaaaaaa
bbbbbbbb,aaaaaaaa
bbbbbbbb,aaaaaaaa
bbbbbbbb,aaaaaaaa
bbbbbbbb,aaaaaaaa
bbbbbbbb,aaaaaaaa
bbbbbbbb,aaaaaaaa
bbbbbbbb,aaaaaaaa
bbbbbbbb,aaaaaaaa
bbbbbbbb,aaaaaaaa
bbbbbbbb,aaaaaaaa
bbbbbbbb,aaaaaaaa
bbbbbbbb,aaaaaaaa
bbbbbbbb,aaaaaaaa
bbbbbbbb,aaaaaaaa
bbbbbbbb,aaaaaaaa
bbbbbbbb,aaaaaaaa
bbbbbbbb,aaaaaaaa
bbbbbbbb,aaaaaaaa
bbbbbbbb,aaaaaaaa
bbbbbbbb,aaaaaaaa
,aaaaaaaa
bbbbbbbb,aaaaaaaa
bbbbbbbb,aaaaaaaa
bbbbbbbb,aaaaaaaa
bbbbbbbb,aaaaaaaa
bbbbbbbb,aaaaaaaa
bbbbbbbb,aaaaaaaa
bbbbbbbb,aaaaaaaa
aaaaaaaa,bbbbbbbb
```

### Debug Information

Notepad++ v7.2.2   (64-bit)
Build time : Nov 27 2016 - 16:35:52
Path : D:\Google Drive\Programe\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : ON
OS : Windows 10
Plugins : mimeTools.dll NppConverter.dll

**Comment by MetaChuh** [comment]
please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins if you update from version 7.5.9 or below.
if your issue still persists, and it is still of relevance, please feel free to file a new issue as easy to understand and reproducible as possible.

thank you for your help and best regards.

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
(no extra account is needed, just use your github account to sign in)
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)
