### ISSUE TITLE
Add .mk to makefile extensions

### ISSUE THREAD

**Issue by Hendricks266** [notepad-plus-plus/notepad-plus-plus#2716]
I would like to propose adding .mk to the default list of Makefile language extensions. It is sometimes used  by projects instead of .mak, including by the Android NDK.

It would require changing the following line in **langs.model.xml**:

`        <Language name="makefile" ext="mak" commentLine="#">`

to:

`        <Language name="makefile" ext="mak mk" commentLine="#">`

Let me know if the project management would prefer a pull request despite this being a one-line change.

**Comment by deadrow** [comment]
I also have the same proposal. It's a bit annoying that every time I need to manually select the language.

**Comment by redmanmale** [comment]
@deadrow 

As a workaround you could add this extension in Settings -> Style Configurator menu.

![pic](https://puu.sh/tSr0C/8b84b57196.png)
