### ISSUE TITLE
.sh files color problem when using heredocuments

### ISSUE THREAD

**Issue by Benqzq** [notepad-plus-plus/notepad-plus-plus#2717]
This problem relates to editing **.sh** files in Notepad++ and I published it last month in a QA session in StackExchange SuperUser in a well detailed graphical explanation:

http://superuser.com/questions/1147461/removal-of-notepad-styles-possible-i-mean-to-the-style-configurators-langua

Basically, it's about the Heredoc coloring in .sh files.

**Comment by dail8859** [comment]
Same as #3202
