### ISSUE TITLE
What's about previous SF N++ posts ?

### ISSUE THREAD

**Issue by guy038** [notepad-plus-plus/notepad-plus-plus#272]
Hello **Don** and **All**, 

From the **recent** moving of the entire N++ project on **GitHub**, I suppose that, waiting for a **final** solution about N++ forums, we must, from now on :

- Create **discussion** posts, in **GitHub - Issues**, with the label "**Question**"

- Create **help** posts, in **GitHub - Issues** with, with the label "**Help**"

Am I right ? _I'm quite a **newby**, here, on GitHub_ !

By this mean, these posts would,'t be seen as "**real issue**" posts :-)

Don, an **important** question too :

What's about all the numerous N++ posts, previously created on **SourceForge** forums ? Are they definitively **lost** ?!

Indeed, I suppose that people, who created replies to **recent** posts, would like to go on discussing with the **authors** of these help or discussion posts.

A side-effect, is that every **link** to any previous **SF N++** post, that you have stored, for **further** reading, is, of course, **unreachable** :-(((

As for me, for instance, I still have a lot of SF forum links, to some **python** questions or scripts, just stored in a .txt file, for the time I'm ready to **fully** investigate the **python** language and plugins !! From now on, they seem all **obsolete** -(

Best regards,

guy038

**P.S.**

And what about the forums, per **language**, for people not acquainted with **English** language ?

**Comment by StanDog** [comment]
Didn't you asked this in the old forum and Don gave you an answer already?
https://sourceforge.net/p/notepad-plus/discussion/1290588/thread/9712e658/#d0f9

**Comment by guy038** [comment]
Hi **StanDog**,

You're perfectly right. The **Don**'s reply to my **SF** post was created **50mn before** my same post on **GitHub**, but I didn't look for SF forums till today.

It's just that I wanted to **try** posting something on this **new** site ( for me ! ) and to get used to the **GitHub**'s interface.

By the way, the **Github Markdown** syntax is very **similar** to the one used in **SF**. But I've never been able to get **underlined** text :-(( ( It should be something like `<u>......</u>` but that doesn't work ! )

Anyway, it's nice that Don can, still, keep a **read-only** link to our **old** posts on **SF** !

Best regards,

guy038

**Comment by donho** [comment]
@guy038 Could you come to 
https://gitter.im/notepad-plus-plus/notepad-plus-plus
so we could have a little chat on live?

**Comment by GitMensch** [comment]
The question could be closed (and tagged as question), couldn't it?

**Comment by donho** [comment]
@GitMensch  Hmm... Not yet. 
@milipili is working on it... hard.

**Comment by donho** [comment]
SourceForge was a good place; unfortunately, sometimes good places don't last. It was a privileged spot for Notepad++'s users to share their thoughts and to contribute. We now need more appropriate tools to focus our efforts on improving Notepad++. GitHub is now the central platform for development and bug reporting. Even recently gitter.im was integrated for online chatting. But this is not enough, the community still needs its meeting place.

Luckily NodeBB has found us. We love its sober design, efficiency and both rich/minimalist features. Come as you are, and use your (Facebook | Google+ | Github | Twitter) account to join us.
We are sure that you will enjoy it!

https://notepad-plus-plus.org/community/﻿

Thanks to @milipili !
