### ISSUE TITLE
Issues with Ctrl + Tab option

### ISSUE THREAD

**Issue by DeepanSridhar** [notepad-plus-plus/notepad-plus-plus#2720]
### Description of the Issue

While using the Ctrl + Tab option, able to notice that not all the documents are visible on the screen
![notepad error](https://cloud.githubusercontent.com/assets/24799770/21510222/fbaedf78-ccb6-11e6-8d27-92600566dceb.png)

### Steps to Reproduce the Issue

1. Open multiple tabs
2. Press Ctrl+TAB
3. Not all the tabs are listed

### Expected Behavior

A user friendly interface with a scrollbar could be easier

### Actual Behavior

Not all the tabs are visible while using Ctrl+Tab and hence it is not convinient to use the shortcuts

**Comment by young-developer** [comment]
Hi, @DeepanSridhar 
Try to use NavigateTo plugin before it will be fixed, It allows navigate between opened files very quickly.
https://github.com/young-developer/nppNavigateTo/releases

**Comment by SinghRajenM** [comment]
@MetaChuh this has already been fixed, but sorry I don't remember the version. However, switching to latest will fix the issue.
