### ISSUE TITLE
Double entries in Windows context menu after moving from 32-bits to 64-bits

### ISSUE THREAD

**Issue by asashour** [notepad-plus-plus/notepad-plus-plus#2721]
### Description of the Issue
When installing v7.2.2 32-bit, and then installing 64-bits, there is two entries in the windows context menu, I guess this is because of the 32-bits was incompletely removed.

### Steps to Reproduce the Issue
1. Install v7.2.2 32-bits
2. Install v.7.2.2 64-bits
3. Click 'yes' to uninstall 32-bits
4. Right click on file to open it with notepad++

### Expected Behavior
A single entry of editing with Notepad++

### Actual Behavior
Two entries for editing with Notepad++

### Debug Information
![image](https://cloud.githubusercontent.com/assets/2410127/21521077/c797be6a-ccf9-11e6-9c16-decb9f5d25da.png)

**Comment by MetaChuh** [comment]
please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins if you update from version 7.5.9 or below.
if your issue still persists, and it is still of relevance, please feel free to file a new issue as easy to understand and reproducible as possible.

thank you for your help and best regards.

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
(no extra account is needed, just use your github account to sign in)
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)
