### ISSUE TITLE
Fancy french translation : "zyva" ...

### ISSUE THREAD

**Issue by GrmpCerber** [notepad-plus-plus/notepad-plus-plus#2723]
### Description of the Issue

Relates to lines [PowerEditor/installer/nativeLang/french.xml#L383](https://github.com/notepad-plus-plus/notepad-plus-plus/blame/3924190fb17c1964a5fdfc4675be050ba9ee34cc/PowerEditor/installer/nativeLang/french.xml#L383) and 384

### Steps to Reproduce the Issue

1. "Ctrl + g" with french locale

### Expected Behavior

I'm not sure ;)

### Actual Behavior

Got a fancy translation for at least 2 buttons

### Debug Information

seen on NP++ 6.8.2 and 7.2.2

![2016-12-28_14h23_39](https://cloud.githubusercontent.com/assets/1545453/21522845/5631a2f8-cd09-11e6-9808-25e59dea85a8.png)

**Comment by earth75** [comment]
LOL! whoever did this....

**Comment by MetaChuh** [comment]
please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins if you update from version 7.5.9 or below.
if your issue still persists, and it is still of relevance, please feel free to file a new issue as easy to understand and reproducible as possible.

thank you for your help and best regards.

**Comment by jujumo** [comment]
since when its there ?
