### ISSUE TITLE
Wrong line when searching in files

### ISSUE THREAD

**Issue by yannik131** [notepad-plus-plus/notepad-plus-plus#2726]
### Description of the Issue

Sometimes when I use the "search in files" feature and notepad++ found a match, the line and match are displayed correctly in the "find results - x hits" box at the bottom, but something entirely different is marked grey on the screen upon double-clicking the match - different line, different text.
Screenshot: http://www.bilder-upload.eu/show.php?file=44a9e3-1482951142.png

### Steps to Reproduce the Issue

1. Press ctrl-f
2. click "search in files"
3. search for a few words
4. double-click the result

### Expected Behavior

Notepad++ should mark the right text and jump to the correct line upon double-clicking a result in "find in files"

### Actual Behavior

Notepad++ jumps in the right file, but to the wrong text/line (usually not far from the correct match and not always)

### Debug Information

Notepad++ v7.2.2   (32-bit)
Build time : Nov 27 2016 - 16:31:07
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : ON
Local Conf mode : OFF
OS : Windows 7
Plugins : mimeTools.dll NppConverter.dll NppExec.dll NppExport.dll NppTextFX.dll PluginManager.dll 

Screenshot: http://www.bilder-upload.eu/show.php?file=44a9e3-1482951142.png

**Comment by pyhalte** [comment]
I can confirm that this happens in 7.3.2. 

I suspect that this has something to do with file changing and Notepad++ doesn't notice it.

For example:
- Have files A and B open in tabs, with B visible.
- Change file A outside of Notepad++, for example, select different revision from source control.
- Search for something that can be found in A. Finds correct line, and shows it in results window.
- Double click the search results window; wrong position in file is selected.
- Run search again, select result again, correct position is now selected.

**Comment by pcpro178** [comment]
I was experiencing this problem again with 7.2.2 today, after running multiple find-in-file searches in my organizations source tree.  I closed Notepad++, updated to 7.3.2, and restarted the updated Notepad++.  The problem seems to have gone away (for now).  I've only seen the problem when running multiple find-in-file searches; it's never been the first search to the best of my recollection.  My guess is that it's some sort of caching problem when Notepad++ does it's find-in-files searches and that the (temporary) fix is to restart Notepad++.  Can anyone confirm that restarting Notepad++ temporarily resolves the problem?

**Comment by MetaChuh** [comment]
please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins if you update from version 7.5.9 or below.
if your issue still persists, and it is still of relevance, please feel free to file a new issue as easy to understand and reproducible as possible.

thank you for your help and best regards.

**Comment by sasumner** [comment]
This is going to be the same in ANY version of Notepad++.  Search results positions are only valid until the file is changed.  This is by design.

**Comment by yannik131** [comment]
If you look at the original problem description again, I didn't mention that this issue only occured when the file is changed. I experienced the problem with files that had not been changed recently before the search. I updated to the newest version 7.6.6 and easily recreated the problem 5 minutes ago with a file that I haven't touched EVER: https://www.bilder-upload.eu/bild-669047-1556814119.png.html
