### ISSUE TITLE
Notepad ++ crashes in case of temporary files is opened in notepad++ and system shuts down

### ISSUE THREAD

**Issue by kushalagrawal** [notepad-plus-plus/notepad-plus-plus#2730]
### Description of the Issue

Notepad ++ crashes in case of temporary files is opened in notepad++ and system shuts down.

### Steps to Reproduce the Issue

1.  Open few files in Notepad ++.
2. Open a file from outlook or any file which is temporary file.
3.  try to shut down windows as standard process.
4.  start your system again. 
5. Start notepad++
6. You will fined there are no tabs open which is available in normal case when you restart your system.

### Expected Behavior

Tabs should remain open whenever next time i open notepad++. which is default functionality of it.

### Actual Behavior

there are no tabs open which is available in normal case when you restart your system.

**Comment by creckord** [comment]
I'm not sure if this is the same, but whenever my Windows forces an unattended restart to apply updates, I lose all unsaved content (tabs for new and temporary files are gone, "regular" files are reopened but unsaved changes are lost).

If on the other hand, I just close Notepad++ (or even kill it hard through Task Manager), all unsaved content is restored from session.

**Comment by Gabr-F** [comment]
@kushalagrawal Does it really crash? From the rest of your message it looks like the problem is _just_ that the now-missing files are ignored when reloading the session.
Please fix the title and the post if it's so.

**Comment by Gabr-F** [comment]
@creckord Does Notepad++ crash whenever that (unattended restarts to apply updates) happens? Does it display the various messages that an exception occurred, that it will attempt to save any unsaved data etc.?

P.S. I'm not sure what you mean with unattended restarts, if you mean you're not in front of the PC I guess you can't verify this...

**Comment by GoRadioGo** [comment]
Yes, I saw the same thing today.
My Notepad++\backup directory was missing about 1/2 of my unsaved files.

It appeared to happen same way as @creckord 

N++ Auto-backup work(ed) flawless for me for over a year.
Today I stepped away from my computer for a while, and upon my return, saw that Windows 10 had restarted on it's own.
In opening N++, not all 'unsaved' files were restored. Yikes !

**Comment by donho** [comment]
It's not a crash issue.

**Comment by GoRadioGo** [comment]
As mentioned, my behavior was same as @creckord Feb 1

I have no evidence it was a crash. But Windows forced an unattended restart.
The main evidence is though that files were lost.

Granted the Subject line of this original issue may have been a misnomer.
But the issue is real. Surprised issue would be closed.

**Comment by creckord** [comment]
After just losing files for yet another time upon Windows restart, I dug around a bit, and I think I found out what went wrong for me: Sometimes, I lose my session backup configuration settings.

- I'm normally using Notepad++ in mono-instance mode and have session snapshot/periodic backup enabled
- Ever so often, I still need to launch a separate Notepad++ instance. I do this with -multiInst -nosession (I use this as my default editor for command-line Git)
- That separate Notepad++ instance has session snapshot/periodic backup disabled by default
- Depending on whether or not I have my regular mono-instance Notepad++ still running at the time and/or the order in which I close the two, this config change sticks and propagates to the mono-instance
- A subsequent restart (or killing Notepad++ any other way) naturally loses all new stuff...

I'm currently working around this by restoring the setting in config.xml via sed whenever the Git editor exits. Is there a way to separate the configs, e.g. specifying a separate config folder, or to tell Notepad++ that this is a one-off instance and it shouldn't persist config?

**Comment by donho** [comment]
Fix by https://github.com/notepad-plus-plus/notepad-plus-plus/commit/6000f3bb21a42a4d28d068617e0dc642ef739b26
