### ISSUE TITLE
Plugin Manager not loading plugin list

### ISSUE THREAD

**Issue by JacenBoy** [notepad-plus-plus/notepad-plus-plus#2733]
### Description of the Issue

When trying to open the Plugin Manager, the plugin list fails to load.

### Steps to Reproduce the Issue

1. Open Plugin Manager

### Expected Behavior

I expected a list of available plugins to load so I could find and install one.

### Actual Behavior

I received and error message telling me that the plugin list had failed to download.

### Debug Information

Notepad++ v7.2.2   (32-bit)
Build time : Nov 27 2016 - 16:31:07
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10
Plugins : BracketsCheck.dll ccc.dll HTMLTag_unicode.dll mimeTools.dll NppConverter.dll NppExport.dll NppFTP.dll NppSaveAsAdmin.dll PluginManager.dll zoomdisabler.dll 

Before  this issue started happening, I did update my Plugin Manager, and I have a feeling something in the update broke the manager. I can confirm that my internet connection is not the issue. Before I updated the Plugin manager, I was able to load the plugin list without any issues.
![pluginmanager](https://cloud.githubusercontent.com/assets/11392691/21575790/397a6c5a-cee7-11e6-94d2-5b42432c30e1.png)

**Comment by dail8859** [comment]
If you are still having trouble you should report this to the PluginManager project [here](https://github.com/bruderstein/nppPluginManager/issues).
