### ISSUE TITLE
Feature Rrequest: smart Auto-indent

### ISSUE THREAD

**Issue by pgostincar** [notepad-plus-plus/notepad-plus-plus#2736]
### Description of the Issue
After indented text I want few empty lines without indent.
Additional check box for Smart-Auto-indent

### Steps to Reproduce the Issue
Each CR makes Auto-indent even if previous lines are empty and without any spaces or text.

### Expected Behavior
No indent if previous line(s) is empty.

### Actual Behavior
Auto-indentation for all new lines.
I delete spaces and tabs in current line with no text, but pressing CR I get indentation in next new line.
So I make one dot in first line, so I don't get indentation in new empty lines.

**Comment by dcomtois** [comment]
I totally agree, it would be much better! I end up erasing useless empty spaces all the time.

**Comment by Beep6581** [comment]
Duplicate of #443

**Comment by shruthibalaji2307** [comment]
Has anyone picked this up? I would like to pick this up.

**Comment by MetaChuh** [comment]
this feature will currently not be implemented.

thank you for your help and best regards.

**Comment by sasumner** [comment]
This was actually fixed in N++ 7.6(.0).  Entry from change log: `Fix auto-indent issue by typing Enter on empty line.`
