### ISSUE TITLE
[Feature Request] Disable auto-save on document switch (leave the document)

### ISSUE THREAD

**Issue by Lob98** [notepad-plus-plus/notepad-plus-plus#2738]
### Description of the Issue
Please make an option to disable auto-save on document switch (when you leave a document).

I have thousands of files in reserve copy (as well as in session backup though) and auto-save on document switch give me HUGE lag everytime i leave an edited document. It freezes for 3-10 seconds. I bought NMVe SSD (benchmark highest) just to fight this problem, but it is still here. I am really tired. I work with thousands of documents every day and it always freeze every minute or more often (everytime i switch!!).
Please make disable auto-save on document switch option in settings.
Because i can set 999 seconds for auto-backup feature and it seems to work well-enough (not lag randomly anymore), but auto-save on document switch/leave NOT POSSIBLE to disable.

Thanks in advance.

**Comment by MetaChuh** [comment]
please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins if you update from version 7.5.9 or below.
if your issue still persists, and it is still of relevance, please feel free to file a new issue as easy to understand and reproducible as possible.

thank you for your help and best regards.

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
(no extra account is needed, just use your github account to sign in)
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)
