### ISSUE TITLE
"Follow current doc" follows Notepad++ current directory

### ISSUE THREAD

**Issue by nunoperalta** [notepad-plus-plus/notepad-plus-plus#2739]
### Description of the Issue
When using "Follow current doc", instead of putting the directory of the current opened document, it puts either:

C:\Program Files\Notepad++
or
C:\Program Files\Notepad++\updater

This is broken since the release of Notepad++ 64bit (I haven't tried on 32bit since that release).
Not running as Administrator.

### Steps to Reproduce the Issue
1. Open any file
2. Open "Find in Files" dialog
3. Check "Follow current doc"

### Expected Behavior
Directory should be changed to opened file's doc

### Actual Behavior
C:\Program Files\Notepad++
or
C:\Program Files\Notepad++\updater

![image](https://cloud.githubusercontent.com/assets/487079/21589300/56b47830-d0e8-11e6-8e5c-97ead0ed8d1f.png)

**Comment by donho** [comment]
It works fine for me with both 32bit and x64 Notepad++ v7.3 binary.
What's your debug info?

**Comment by nunoperalta** [comment]
Debug info:

Notepad++ v7.3   (64-bit)
Build time : Jan  1 2017 - 20:02:37
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10
Plugins : mimeTools.dll NppConverter.dll

**Comment by PaladinTheGreat** [comment]
Hi what is the solution for this issue? I had the same issue with x86 and x64.
Previously this feature was ok, but I can't remember when updating to certain version then "Follow current doc" no longer working for me.
Please kindly advise, thank you.

**Comment by nunoperalta** [comment]
In all my computers, different versions of Windows, I have this problem.

It only works when you open Notepad++ directly from a file. If you open through the Task Manager, for example, it will use whatever default working directory Notepad++ has.

Even if you open directly from a file, that option will not really "follow current doc". It will always use the location of the whatever file you opened Notepad++ with, which is the working directory Notepad++ is.

**Comment by PaladinTheGreat** [comment]
Hi, have you tried cleaning up your computer with something like CCleaner?
I was having same problem, but now it worked. I just delete the following folders:
C:\Users\(your user name)\AppData\Local\Notepad++
C:\Users\(your user name)\AppData\Roaming\Don HO don.h@free.fr
C:\Users\(your user name)\AppData\Roaming\Notepad++

But be careful when deleting the last one (\Roaming\Notepad++) as it will erase your configuration settings. So backup first, or try on non essential computer to see whether it work for you.

Also, try to reduce number of plugins you have installed. I was having several plugins but then I noticed I rarely use them, so I removed a lot unused plugins to make Notepad++ easier to load.

Good luck :)

**Comment by nunoperalta** [comment]
When I install Notepad++ on new machines, I get that problem no matter what. Those folders are obviously not there (i.e. clean) when I install Notepad++ on newly installed Windows.

The fix shouldn't be deleting those folders, but instead get Notepad++ itself fixed.

**Comment by PaladinTheGreat** [comment]
Well, it could be some settings become corrupted, but certainly I find it worked the first time I install Notepad++, and it should be worked on fresh new machine as well.
