### ISSUE TITLE
Wrong MD5 sum with Cyrillic text in dialog window

### ISSUE THREAD

**Issue by rddim** [notepad-plus-plus/notepad-plus-plus#2743]
### Description of the Issue

When I test the MD5 sum generator with cyrillic text it give me wrong sum
### Steps to Reproduce the Issue

1. Type (or copy/paste) `тест` in the main window of Npp
2. Select the text and go to `Tools` > `MD5` > `Generate into clipboard`
3. Paste the checksum - it is `ebb5e89e8a94e9dd22abf5d915d112b2`
4. Go to `Tools` > `MD5` > `Genetare...`
5. Type (or copy/paste) `тест` in the MD5 window
6. The generated checksum is `98554ea0cb509620815fe5bf980246ec`

### Expected Behavior

Proper md5 chechsums in cyrillic
### Actual Behavior

Wrong md5 checksums in cyrillic
### Debug Information

Notepad++ v7.3   (32-bit)
Build time : Jan  1 2017 - 20:04:42
Path : D:\Install\Office Programs\Notepad++\notepad++.exe
Admin mode : ON
Local Conf mode : ON
OS : Windows 7
Plugins : ComparePlugin.dll mimeTools.dll NativeLang.dll NppExport.dll NppHasher.dll NppTextFX.dll PluginManager.dll 

For the test I also use WinHasher and some online md5 generators

The wrong checksum is also generated with NppHasher.dll plugin

**Comment by batagy** [comment]
Hi!

I experienced the very same issue with special Hungarian characters.
Example: 

1. Type (or copy/paste) `Fájlnév` in the main window of Npp.
2.  Select the text and go to Tools > MD5 > Generate into clipboard
3. Paste the checksum - it is e2d72255c7341a5e4f684b9dd2ece36c.
4. Go to Tools > MD5 > Generete...
5. Type (or copy/paste) `Fájlnév` in the MD5 window.
6.  The generated checksum is 2a7ca5d580df9da7e7839acc39d4ea05.

### Debug data:
Notepad++ v7.3   (32-bit)
Build time : Jan  1 2017 - 20:04:42
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 8.1
Plugins : mimeTools.dll NppConverter.dll NppExport.dll NppTextFX.dll PluginManager.dll

**Comment by rddim** [comment]
Hi, @batagy 

Steps 1,2,3 with copy/paste `Fájlnév` are the same in me, but 4,5,6 generate `420ea7135787749b5edb2cd3c6f8a703`

**Comment by batagy** [comment]
Hi @rddim 

Strange that.
I checked once more. Steps 1,2,3 with `Fájlnév` gives again same e2d72255c7341a5e4f684b9dd2ece36c, and it doesn't change with system language. Apparantly it gives the same chechsum as online MD5 generators. 
Steő 4,5,6 gives again `2a7ca5d580df9da7e7839acc39d4ea05` to me, regardless if I use English or Hungarian system language. So it's not changing for me in Win8.1. Anyway it seems to be wrong when using the MD5 window.

Maybe it's also related to encoding, no sure.

**Comment by donho** [comment]
**Generate to Clipboard** command works with Unicode text, but not **Generate** command.
This issue will be fixed in the next release.

**Comment by rddim** [comment]
Hello again,

- In version 7.3.1 with ANSI file and word `тест` I get different sums - `ebb5e89e8a94e9dd22abf5d915d112b2` with `Generate...` and `98554ea0cb509620815fe5bf980246ec` with `Generate into clipboard`
In UTF-8 and UCS-2 the sums are `ebb5e89e8a94e9dd22abf5d915d112b2` with both options.

- In version 7.3 with ANSI file and word `тест` I get `98554ea0cb509620815fe5bf980246ec` with both options.
In UTF-8 and UCS-2 the sums are different - `98554ea0cb509620815fe5bf980246ec` with `Generate...` and `ebb5e89e8a94e9dd22abf5d915d112b2` with `Generate into clipboard`
