### ISSUE TITLE
Regex "(something)?a*anything" will match the whole file if there's a string of at least 9998 a's in the file

### ISSUE THREAD

**Issue by Runemoro** [notepad-plus-plus/notepad-plus-plus#2744]
### Description of the Issue

In regex search mode, the regex `(something)?a*anything`, where `something` and `anything` can be anything that's not inside the file, will match the whole file if the file contains a string of 9998 a's. If `a` is replaced with something else, such as `ab`, the match will only need 4999 repetitions of `ab` (so still 9998 total characters). In fact, `a*` can be replaced with any regex that can match a sequence of at least 9998 characters.

The `(something)?` can't be removed, but the `?` can be replaced with `*` or even `{0}`.

### Steps to Reproduce the Issue

1. Download test file here: http://pastebin.com/raw/J91rH8sG
2. Ctrl-F and enable Regular expressions
3. Enter "(something)?a*anything" in the box and click find next

### Expected Behavior

The match shouldn't return any result since "anything" is not in the file

### Actual Behavior

The whole file gets selected

### Debug Information

Notepad++ v7.2.2   (64-bit)
Build time : Nov 27 2016 - 16:35:52
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 8.1
Plugins : mimeTools.dll NppConverter.dll

**Comment by MetaChuh** [comment]
please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins if you update from version 7.5.9 or below.
if your issue still persists, and it is still of relevance, please feel free to file a new issue as easy to understand and reproducible as possible.

thank you for your help and best regards.

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
(no extra account is needed, just use your github account to sign in)
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)
