### ISSUE TITLE
Middle mouse click - close tab while Notepad++ was not in focus

### ISSUE THREAD

**Issue by vosManz** [notepad-plus-plus/notepad-plus-plus#2747]
### Description of the Issue
I have Notepad++ open in the background, and Internet Explorer on the foreground. The tab-bars of both programs are alligned. When I close the last tab in Internet Explorer using a middle-mouse-click on the tab, IE closes but also the tab in Notepad++ that was positioned under the mouse closes.

### Steps to Reproduce the Issue
1. Open Notepad++ and open 1 or more files
2.  Open Internet Explorer 11, so it has 1 tab open
3.  Align Internet Explorer 11 so the tabs are on the same position as the tabs from Notepad++
4. Use a middle-mouse-click (mouse wheel click) to close the tab in Internet Explorer 11

### Expected Behavior
Internet Explorer 11 closes

### Actual Behavior
Internet Explorer 11 closes, and a file in Notepad++ was closed.

### Debug Information
Notepad++ v7.3   (32-bit)
Build time : Jan  1 2017 - 20:04:42
Path : C:\Users\username\OneDrive\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : ON
OS : Windows 10
Plugins : ComparePlugin.dll CustomizeToolbar.dll DSpellCheck.dll EmmetNPP.dll HTMLTag_unicode.dll JSLintNpp.dll JSMinNPP.dll mimeTools.dll NppConverter.dll nppcrypt.dll NppExec.dll NppExport.dll NppFTP.dll NPPJSONViewer.dll NppPlugin_SciMarkerSymbol.dll NppTaskList.dll NppTextFX.dll NppToolBucket.dll PluginManager.dll PoorMansTSqlFormatterNppPlugin.dll PythonScript.dll SessionMgr.dll SourceCookifier.dll SpellChecker.dll Tidy2.dll UniversalIndentGUI_NPP.dll XMLTools.dll ZenCoding-Python.dll

**Comment by MetaChuh** [comment]
please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins if you update from version 7.5.9 or below.
if your issue still persists, and it is still of relevance, please feel free to file a new issue as easy to understand and reproducible as possible.

thank you for your help and best regards.

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
(no extra account is needed, just use your github account to sign in)
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)
