### ISSUE TITLE
RTL text selection selects wrong characters

### ISSUE THREAD

**Issue by erango** [notepad-plus-plus/notepad-plus-plus#2749]
### Description of the Issue
When selecting part of an RTL string, the wrong part of the string is selected. It appears to treat the RTL string as LTR.

### Steps to Reproduce the Issue
1. Have a document with an RTL string in it. Example of string:
<h2 class="contact-title">השאירו פרטים לקבלת מידע נוסף</h2>
2. Double click to select the word מידע
3. Observe: some substring is selected

### Expected Behavior
The word מידע is highlighted and selected. When copied to clipboard, the clipboard contents should be מידע.

### Actual Behavior
Some substring is selected, but it doesn't cover the whole word. It seems as though another word is selected. When copying the selection, the contents of the clipboard is not the double clicked word.

### Debug Information
Notepad++ v7.2.2   (32-bit)
Build time : Nov 27 2016 - 16:31:07
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10
Plugins : CodeAlignmentNpp.dll ComparePlugin.dll JSLintNpp.dll JSMinNPP.dll mimeTools.dll NppConverter.dll NppExport.dll NppFTP.dll NPPJSONViewer.dll PluginManager.dll Tidy2.dll WebEditU.dll XMLTools.dll 

### Screenshot
![image](https://cloud.githubusercontent.com/assets/6323368/21637750/03420354-d271-11e6-9325-791cddf4010b.png)

**Comment by erango** [comment]
Thanks for letting me know!

**Comment by Yaron10** [comment]
You're welcome.

**Comment by KrasnayaPloshchad** [comment]
Is it possible to intergrate FriBidi?

**Comment by KrasnayaPloshchad** [comment]
Scintilla is working on this, they are intended to handle right-to-left scripts using system resources, we can take focus on their discussions at Google Group.
https://groups.google.com/d/topic/scintilla-interest/6u5YFzkRzRE/discussion

**Comment by sagiro** [comment]
@KrasnayaPloshchad from looking at their posts it seems that they released a patch for review. Can some of us get an installable npp with this update to review if indeed it fixes the issue?

**Comment by KrasnayaPloshchad** [comment]
Scintilla announced version 4.1.0 released, this version adds experimental support for bidirectional text as used by Arabic and Hebrew on Win32, so we can try to fix it anyway.

**Comment by KrasnayaPloshchad** [comment]
@sagiro I think everyone can try SciTE to review now.

**Comment by zufuliu** [comment]
It's only available if Direct2D is enabled and DirectWrite is used. See also https://github.com/XhmikosR/notepad2-mod/issues/217.

**Comment by KrasnayaPloshchad** [comment]
We can try to use Direct2D/DirectWrite directly, alternatively, we can try to send a feature request to upstream to require another system calls.

**Comment by MetaChuh** [comment]
rtl + ltr issues can not be solved within notepad++ and rely on scintilla.
as of 4.1.4 many issues at the scintilla bug tracker have not been solved yet, so i don't expect this to really be fixable in the near future.

thank you for your help and best regards.
