### ISSUE TITLE
Auto-insert doesn't insert

### ISSUE THREAD

**Issue by hellsing71** [notepad-plus-plus/notepad-plus-plus#275]
Hi All,
I have set 2 auto-inserts: <> and ?? (php+HTML). The problem is that np++ inserts these chars only in that session when I set them. If I exit np++ and later restart, it doesn't auto-insert them.
If I check _Settings -> Preferences -> Auto completion_ tab, my settings are there. If I just click 'close' w/o changing anything then it uses my settings again - until I close np++. And I have to repeat it at every new session.
The factory-set pairs ((), [], {}, etc.) work perfectly.
I have np++ v6.7.8.2 on Win 8.1 x64.

**Comment by Rikk** [comment]
+1
Imo, this bug is somewhat important.

**Comment by hellsing71** [comment]
Thanks, guys,
One more point: sometimes the character pairs I set in np++ disappear. Today I got to work in np++, auto-insert didn't work (as usual in every new session), opened the settings panel and the chars weren't there.
It seems to me the auto-completion service has a bug deeper in its code.

**Comment by donho** [comment]
Update your Notepad++ to v7.6.6.
If this bug persists in the new release, please open a new issue with the debug information.
