### ISSUE TITLE
Not replacing regexes in multiple files (108000 files)

### ISSUE THREAD

**Issue by chopinesque** [notepad-plus-plus/notepad-plus-plus#2754]
### Description of the Issue
Tested with fewer files and it does perform the replacement. Tested with Find only with 108000 files, and it does find all instances. When trying Replace in Files, it mentions at the end that all 108000 instances were replaced, when in fact they were not. (It can also be confirmed by the fact that the Date modified remains the same).
The regex is a multiline match.

### Steps to Reproduce the Issue

1. 
2. 
3. 

### Expected Behavior
To replace in all files, even if they are many thousands.

### Actual Behavior
Reports that the replacements were made, but they were not. The 2nd screenshot is only so that you can see the actual regex, it was ran by first clicking Find in Files and then Replace in Files.
Edit: Same regex tested with EmEditor with exact same behaviour, which makes me think that it could be some sort of OS or regex engine limitation?

### Debug Information
Notepad++ v7.2.2   (32-bit)
Build time : Nov 27 2016 - 16:31:07
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10
Plugins : ComparePlugin.dll HTMLTag_unicode.dll mimeTools.dll NppConverter.dll NppExport.dll NppFTP.dll NppTextFX.dll PluginManager.dll PythonScript.dll SpellChecker.dll XMLTools.dll 

![2017-01-05_225542](https://cloud.githubusercontent.com/assets/10416842/21697152/c33aab6a-d399-11e6-81f8-60cbbf8465c2.png)
![2017-01-05_225754](https://cloud.githubusercontent.com/assets/10416842/21697180/de85e54c-d399-11e6-9a09-a7c449404331.png)
![2017-01-05_230745](https://cloud.githubusercontent.com/assets/10416842/21697491/4f55e320-d39b-11e6-98c7-014c400ba068.png)

**Comment by MetaChuh** [comment]
please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins if you update from version 7.5.9 or below.
if your issue still persists, and it is still of relevance, please feel free to file a new issue as easy to understand and reproducible as possible.

thank you for your help and best regards.

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
(no extra account is needed, just use your github account to sign in)
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)
