### ISSUE TITLE
[Feature Request] Option for one Notepad++ "mono-instance" per virtual desktop

### ISSUE THREAD

**Issue by MCGallaspy** [notepad-plus-plus/notepad-plus-plus#2755]
### Summary

I use Notepad++ extensively both for general text editing and writing code. My usage pattern on Windows 10 is to partition my work into several virtual desktops. I like the mono-instance behavior of Notepad++ in that when I open documents they become tabs in the mono-instance, but I find it jarring that when I open a new file I might be "yanked" into another virtual desktop. That said, changing it to multi-instance mode causes files I open in explorer to create a new Notepad++ instance, cluttering my work space.

I'd like to propose a new multi-instance mode for Notepad++ as per the title. I've got experience with C++, and I'm willing to get my hands dirty working on this. What I'd like to understand before undertaking any work is whether such a feature has a chance of being accepted. Any current maintainers willing to chime in?

### Current Behavior

Here's how to reproduce the "yanking" behavior that I find jarring:

1. Open Notepad++ in mono-instance mode.
2. Switch to a new virtual desktop.
3. Open another document (e.g. through the right-click context menu) in Notepad++.
4. Observe that you are switched to the virtual desktop on which the mono-instance is running.

### Desired behavior

Here's what I'd like to see:

1. Open Notepad++ in "one mono-instance per virtual desktop" mode.
2. Switch to a new virtual desktop.
3. Open another document (e.g. through the right-click context menu) in Notepad++.
4. A new "mono-instance" in that virtual desktop is started, and your document displayed there.

Any subsequent documents opened in a virtual desktop with a "mono-instance" running will be opened as tabs in that "mono-instance". However if you edit a document with Notepad++ in a virtual desktop that *doesn't* have a "mono-instance" then instead of adding it to an instance in another virtual desktop, it will create a new "mono-instance" specific to that virtual desktop.

**Comment by xiezhensheng** [comment]
+1.

I do feel this is an important feature, as I constantly using more than 1 virtual desktops.

**Comment by MetaChuh** [comment]
this is an interesting feature, but due to the complexity this will currently not be implemented.

thank you for your help and best regards.

**Comment by Nu11u5** [comment]
I worked around this by added `-multiInst` to a shortcut in the Start Menu.  This allows starting a new instance that appears on the active virtual desktop without switching over to an existing instance on a different virtual desktop.

Using "Open with Notepad++" will cause the file to open in the most recent active instance between all virtual desktops.
