### ISSUE TITLE
Part of settings is not read

### ISSUE THREAD

**Issue by Kdmeizk** [notepad-plus-plus/notepad-plus-plus#2757]
### Description of the Issue

config.xml
 
> GUIConfig name="delimiterSelection" leftmostDelimiter="40" rightmostDelimiter="41" delimiterSelectionOnEntireDocument="1"

=> "delimiterSelectionOnEntireDocument" is not read and Notepad++ resets it to the default value in the UI setting.

### Debug Information

Notepad++ v7.3.1   (32-bit)
Build time : Jan 17 2017 - 00:21:10
Path : %USERPROFILE%\Notepad++\notepad++.exe
Admin mode : ON
Local Conf mode : ON
OS : Windows 7
Plugins : ComparePlugin.dll NppConverter.dll PluginManager.dll

**Comment by dail8859** [comment]
Closed by 24a3acfcc874d639abddc491a96193807babb644

**Comment by Kdmeizk** [comment]
The fix works on the latest version: 7.3.3.
