### ISSUE TITLE
Feature request: 'Ignore comments' checkbox in the 'Find' dialog

### ISSUE THREAD

**Issue by thorn0** [notepad-plus-plus/notepad-plus-plus#276]
Wide popularity of the embedded documentation conventions like JSDoc and C#'s XML comments leads to a situation where comments often constitute the bigger part of a source file. This abundance of comments makes it extremely difficult to find anything in the source code proper. For example, while reading someone's code, we might want to know how and where a certain function is used. However, if we decide to conduct a search by its name, we might get lost in dozens of code samples in the comments and overlook some important case of its real usage. This somewhat undermines the habitual workflow of those who are used to rely a lot.on the search to read the code. Not sure if any other editor has it, but it would be great to have the 'Ignore comments' option in Notepad++'s search dialog.

**Comment by milipili** [comment]
Nice feature indeed. I want it :) However, it implies the search _understand_ the underlying format and its changes the code architecture. Hum very interesting actually I like it

**Comment by thorn0** [comment]
Notepad++ does understand what comments are. The search just needs to use this information somehow. For example, we can replace the content of all the comments with spaces and make the search internally work with this copy instead of the original text. The replacing with spaces is better than simply deleting because it wouldn't be required then to map the search results' positions in the copy to the ones in the original.

**Comment by aaaxx** [comment]
@milipili
While you're at it, would it be much of a stretch to add the option of ignoring tags in HTML/XML? So that it's possible to work on them like normal text.

**Comment by milipili** [comment]
No, but as I said, this implies to have understand the underlying language (for c++ for example, to use libclang to really parse the c++ file) but it would be nice for the function list as well.

**Comment by MetaChuh** [comment]
closed due to inactivity
