### ISSUE TITLE
Compile on UNIX/LINUX

### ISSUE THREAD

**Issue by deepakjeena** [notepad-plus-plus/notepad-plus-plus#2761]
How to compile and run np++ on UNIX/LINUX,
please provide complete steps.

**Comment by redmanmale** [comment]
There is no way to do it. NPP is heavily dependent on WinAPI.

If you are looking for some text editor for Linux with similar functions take a look at Sublime Text.

**Comment by ajyotirmay** [comment]
@redmanmale 

but NPP is a lot light and fluent in terms of performance. Is there any plan to port is to Unix/Linux systems in the near future?

**Comment by redmanmale** [comment]
@ajyotirmay 
> Is there any plan to port is to Unix/Linux systems in the near future?

I'm not a core NPP developer, but IMO it won't happen.

As I can see NPP is Scintilla + GUI based on WinAPI. So you could not port NPP, you should rewrite it almost from scratch.

**Comment by ajyotirmay** [comment]
@redmanmale 

> ... you should rewrite it almost from scratch.
That's a little sad to know, because this is a good software(my favourite one on Windows). Do you have any idea about the coupling and modularity of NPP? If it's not that tightly coupled to WinAPI, then I can try to write a Linux version.

**Comment by redmanmale** [comment]
> I can try to write a Linux version

Take a look at this: https://itsfoss.com/scite-the-notepad-for-linux.

**Comment by ajyotirmay** [comment]
Well, then it looks like that will be like re-inventing the wheel for a lot of good alternatives are there which fill in the void of NPP on Linux systems.

**Comment by EPrograming** [comment]
@redmanmale  Would it be possible to run it with wine?

**Comment by redmanmale** [comment]
@EPrograming I don't know. You could try and post results here.

**Comment by EPrograming** [comment]
@redmanmale Without configuring wine at all, and running the exe, it installs fine. When i run it, i get the following errors: `DLL signature virifaction falled` and `Authenticode check failed` and `SCINTILLA ERROR` 

According to [winehq](https://appdb.winehq.org/objectManager.php?sClass=version&iId=34717) it should work, but the page does not give instructions

**Comment by maverick74** [comment]
@deepakjeena , @ajyotirmay , @EPrograming 
I think Notepadqq ( [https://notepadqq.com](https://notepadqq.com) ) may make you happy :)

**Comment by maverick74** [comment]
@rugk what's the main features you miss in Notepadqq?

**Comment by rugk** [comment]
I think it just generally was not as usable as Notepad++.

**Comment by maverick74** [comment]
I, personally, don't complain :). For what i want them, they both work like a charm and there is nothing one has that i miss in the other.

But it would be good the be able to have one of them compiling in both OSs, so that i could discard the other for good :)

**Comment by MetaChuh** [comment]
if you are using ubuntu, please install notepad++ using the ubuntu software center.

**Comment by maverick74** [comment]
(openSUSE here)
