### ISSUE TITLE
Find and replace for 1st occurence of H1 tag

### ISSUE THREAD

**Issue by guy038** [notepad-plus-plus/notepad-plus-plus#277]
Hi **segarn** and **Loreia2**,

I'm going on, posting about our **previous** discussion on **SF** forums, at:

https://sourceforge.net/p/notepad-plus/discussion/331754/thread/186a67dc/#efe0

Ah, indeed ! the _Loreia2's_ regex is quite a **clever** regex and much more simple than mime !

However, **Loreia2**, in order your regex to work, you must add the **single line** modifier `(?s)` or click on the **. matches newline** option of the Replace dialog.

So, the **Loreia2**'s SEARCH regex `(?s)(.*?)<h1>.*?</h1>(.*)` just matches the **entire** file contents, _splitting it in **3 parts**_ :
- The part `(.*?)` **before** the **_first_** tag **<h1>**, stored as **\1**
- The **title** `<h1>.*?</h1>`, even written in **several** lines
- The **remainder** of the file contents `(.*)`, stored as **\2**

Of course, the REPLACE dialog is, simply, the regex `\1\2`

Anyway, **segarn**, the **main** thing, to keep in mind, is that my regex, as well as the Loreia's one,  must be executed _**ONE ONLY**_. Indeed, in case of _several_ blocks `<h1>....</h1>` in files, it would, otherwise, delete, _each time_, the **first** block `<h1>....</h1>` found !!

Cheers,

guy038

**Comment by MetaChuh** [comment]
hi @guy038 
just cleaning up a bit by closing some orphaned issues at the tracker.
see you later and happy cooking 👨‍🍳

**Comment by sasumner** [comment]
I don't even see why this WAS made into an issue! LOL
