### ISSUE TITLE
UDL.xml changes overwritten when Notepad++ is closed after using `Define your language...`

### ISSUE THREAD

**Issue by john-thomas-dotcms** [notepad-plus-plus/notepad-plus-plus#2772]
If you edit the userDefineLang.xml and save it, but also open the `Language` -> `Define your language...` menu option in the same session, then when Notepad++ closes it will overwrite any changes you've made to the file.

### Description of the Issue

If you make any changes in the `Define your language...` screen without hitting `Save As...`, those changes are written to userDefineLang.xml when Notepad++ is closed.  However Notepad++ doesn't check to see if the userDefineLang.xml file was changed, so if you've made any changes to the file between the time Notepad++ was opened and Notepad++ was closed, those changes will be overwritten when Notepad++ is closed.

### Steps to Reproduce the Issue

1. Select `Language` -> `Define your language...`
2. Make some changes and `Save As...` a new language.
3. Close the popup.
4. Open userDefineLang.xml inside Notepad++
    * Note: Any changes you made using `Define your language...` (step 2 above) do **not** show up when you open the file.
5. Edit the file.
6. Save changes to the file.
7. Close Notepad++.

_**Result:**_
* Any changes made and saved to the file outside the `Define your language...` screen (in step 5 & 6) are wiped out.

### Expected Behavior

Any of the following would be acceptable solutions:

1. Any changes made when you select `Language` -> `Define Your Language...` should just be appended to the file when Notepad++ closes.
    * This is preferred, since that will also preserve any comments or other text that may have been added to the file (which are currently also wiped out when the newly defined language is saved).
2. Notepad++ should recognize that the file has changed when you close and give you a warning that any changes will be overwritten.
    * A warning would be the simplest, and at least give you the option of making a backup before writing the new changes.
3. Whenever the userDefineLang.xml file is overwritten by Notepad++, make a backup copy of the original file.
    * (And ideally keep multiple backups if there's already a backup).

### Actual Behavior

All changes made (and saved) to userDefineLang.xml were wiped out (overwritten) when Notepad++ was closed.

### Debug Information

Notepad++ v7.2.2   (32-bit)
Build time : Nov 27 2016 - 16:31:07
Path : E:\LiberKey\Apps\Notepad++\App\Notepad++\notepad++.exe
Admin mode : ON
Local Conf mode : ON
OS : Windows 7
Plugins : ComparePlugin.dll DSpellCheck.dll mimeTools.dll NppConverter.dll NppExport.dll NppFTP.dll PluginManager.dll SpellChecker.dll

**Comment by MetaChuh** [comment]
please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins if you update from version 7.5.9 or below.
if your issue still persists, and it is still of relevance, please feel free to file a new issue as easy to understand and reproducible as possible.

thank you for your help and best regards.

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
(no extra account is needed, just use your github account to sign in)
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)
