### ISSUE TITLE
find/replace reset button-feature request

### ISSUE THREAD

**Issue by archlinux99** [notepad-plus-plus/notepad-plus-plus#2773]
when using search in find in files,replace, and find there should be a reset button
### Steps to Reproduce the Issue

1. 
2. 
3.

**Comment by MAPJe71** [comment]
To reset what exactly?

**Comment by archlinux99** [comment]
when you type something in the 
find what and replace with dialog
there should be a reset button
to get rid of text inside each dialog

**Comment by MetaChuh** [comment]
this feature will currently not be implemented.

thank you for your help and best regards.
