### ISSUE TITLE
add ctrl+e to map name SCI_LINEENDWRAP to move the cursor to the end of the line

### ISSUE THREAD

**Issue by archlinux99** [notepad-plus-plus/notepad-plus-plus#2783]
In notepad++ go to Settings-->Shortcut Mapper... Choose the Scintilla button at the top.

Map the name SCI_LINEENDWRAP

enter image description here

Select this item and click the Modify button.

Check the Ctrl checkbox and find 'E' in the drop down

Click the Apply button

**Comment by cmeriaux** [comment]
I can't reproduce your issue.
Please, provide your debug info.
Here is mine

    Notepad++ v7.3   (32-bit)
    Build time : Jan  2 2017 - 07:01:30
    Path : C:\Program Files (x86)\Notepad++\notepad++.exe
    Admin mode : ON
    Local Conf mode : OFF
    OS : Windows 7
    Plugins : CodeAlignmentNpp.dll ComparePlugin.dll CustomizeToolbar.dll HexEditor.dll LightExplorer.dll MenuIcons.dll mimeTools.dll NppConverter.dll NppExec.dll NppExport.dll NppFTP.dll NppMenuSearch.dll NppVHDL.dll PluginManager.dll PythonScript.dll XMLTools.dll 


Don't you have a conflict with 'Ctrl+E' shortcut ?

**Comment by archlinux99** [comment]
I have no conflict with ctrl+E
just want you to add ctrl+e to map name SCI_LINEENDWRAP 
by default

**Comment by rddim** [comment]
What is the problem with the `End` key which is by default. It is more easy to press one key instead 2 keys. Many programs use the `End` or `Page Down` key to go to the end of something. You can assign `Ctrl+E` for yourself. For example I add `F9` for `Stay on Top` and change the  `Incremental Search` with `Ctrl+Ins`.

**Comment by cmeriaux** [comment]
Debug Info please
