### ISSUE TITLE
The prompt dialog causes mouse icon to flicker between arrow pointer and text input when moving or hovering over tabs.

### ISSUE THREAD

**Issue by Leif-W** [notepad-plus-plus/notepad-plus-plus#2784]
### Description of the Issue
For the past several versions of NotePad++, the prompt dialog causes the mouse icon to rapidly flicker between an arrow pointer and text input (looks like a capital letter I (eye) ) when over tabs, and even over the menu bar and window title area.  The problem does not occur 100% of the time, it seems intermittent.

### Steps to Reproduce the Issue
1. Open NotePad++
2. In settings for 'Tab Bar' choose 'Multi-line', 'Reduce' and 'Darken inactive tabs', all other 'Tab Bar' settings off.  Not sure if it is important, but it replicates my configuration.  Also be sure that 'Settings->MISC->File Status Auto-Detection' is 'Enabled' with the other two options (Update Silently... and Scroll...) turned off.  Finally, hide toolbar, don't hide menu bar.
3. Open lots of files, until you have 2+ rows of tabs, 3-4 rows maybe better.  This just makes it easier to see the problem as you move all around tab bar area.
4. ALT-TAB switch to other applications, such as a Command Prompt or Windows Explorer, and delete one of the files.
5. When you switch back to NotePad++, you will be prompted with a yes/no dialog informing you that the file no longer exists, asking if you want to keep the file open.  Either answer is ok to trigger the issue.
6. Move the mouse over the tabs or the menu bar, possibly even the window title area, and you may see the mouse icon flicker from the correct 'arrow pointer' to the incorrect 'text input' icon.

### Expected Behavior
I expect the icon to display an arrow pointer over the user interface portion of tabs and menu bars, etc.
I expect the icon to display the text input when I am over the text input/editing portion of the user interface, or when entering text into dialogs (i.e. find, replace, settings, style, language, etc).

### Actual Behavior
Mouse icon flickers between arrow pointer and text input when over tab bar and menu bar after a prompt such as that which appears after a file has been deleted.

### Debug Information
Notepad++ v7.3   (32-bit)
Build time : Jan  1 2017 - 20:04:42
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : ON
Local Conf mode : OFF
OS : Windows 7
Plugins : HexEditor.dll mimeTools.dll NppConverter.dll NppExport.dll NPPJSONViewer.dll NppTextFX.dll PluginManager.dll

**Comment by MetaChuh** [comment]
please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins if you update from version 7.5.9 or below.
if your issue still persists, and it is still of relevance, please feel free to file a new issue as easy to understand and reproducible as possible.

thank you for your help and best regards.

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
(no extra account is needed, just use your github account to sign in)
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)
