### ISSUE TITLE
[Issues] Find All in Current Document - close its window automatically

### ISSUE THREAD

**Issue by sibojan9** [notepad-plus-plus/notepad-plus-plus#2785]
Once you click Search - **Find All in Current Document,** it will run the right command but the find windows closed automatically.  I have to open it again manually if I need to do a second search.
This is very annoying. 

I expect that windows will stay open until I close it manually. 
 
![snap48](https://cloud.githubusercontent.com/assets/11802171/21915688/94487ac4-d909-11e6-98f6-5903930cc9cc.jpg)

**Comment by psychicfork013** [comment]
+1

**Comment by MetaChuh** [comment]
this feature will currently not be implemented.

thank you for your help and best regards.
