### ISSUE TITLE
Add setting to scroll text up or down some lines before reaching bottom or top of window

### ISSUE THREAD

**Issue by marjanlivk** [notepad-plus-plus/notepad-plus-plus#2786]
### Description of the Issue

It will bi very usefull if text will begin to scroll up or down before cursor reach bottom or top line.
When entering the same chang in each line I wont to see some lines more.
Editing in last line and pressing down key and editing ... 
I mast over and over again undo changes made in new line which was not jet seen but I did not stop entering repeatable changes at the right moment/line.

### Steps to Reproduce the Issue

1. Copy this sample text in notepad++ and adjust window to display only 10 lines.
.
.
.
.
.
.
.
declare
  v_a1 number;
  v_a2 number;
  p_a3 number;
  p_a4 number;
  p_a5 number;
  p_a6 number;
  p_a7 number;
  p_a8 number;
  p_a9 number;
  p_a10 number;
  p_a11 number;
  p_a12 number;
  p_a13 number;
  p_a14 number;
  p_a15 number;
  p_a16 number;
  p_a17 number;

begin
  for r in 
.
.
.
.

2. Try to replace p_ into v_ using keyboard.

### Expected Behavior
It will be nice if scrolling begin for example 3 lines before cursor reach bottom line.

### Actual Behavior
Now when cursor reaches bottom line I still repeat entering p <Down> <Left> on 2 or 3 lines before I stop. Then I must undo changes.
Or I must stop entering changes, scroll text with mouse and start again.

**Comment by MetaChuh** [comment]
please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins if you update from version 7.5.9 or below.
if your issue still persists, and it is still of relevance, please feel free to file a new issue as easy to understand and reproducible as possible.

thank you for your help and best regards.

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
(no extra account is needed, just use your github account to sign in)
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)
