### ISSUE TITLE
Please fix this: <?php_egg_logo_guid

### ISSUE THREAD

**Issue by HaPet74** [notepad-plus-plus/notepad-plus-plus#279]
In php when starting a new document, or simply typing <?php, notepad++ will automatically suggest php_egg_logo_guid. This may not be considered as a bug, I am merely requesting that some kind of functionality to recognize if the <?php start tag is used, before suggesting php_egg_logo_guid to be added.

Steps to reproduce this problem:
1. Create a php document
2. Start the php tag by typing <?php
3. hit enter (here it will have added the suggestion to the code.)

Steps to avoid the problem:
3. instead of pressing enter, just press space and then enter.

![image](https://cloud.githubusercontent.com/assets/12991239/8273408/a74f8b76-186c-11e5-9507-43ca43b5ce78.png)

It may seem like a rather simple thing, but it's actually so annoying that I'm about to find an alternative to notepad++. So please, help me with this issue, I am literally begging.

**Comment by HaPet74** [comment]
Since the enhancement label has been added, I won't edit my initial post. But I came up with one more related suggestion... would it be possible to add auto ending tags just like the brackets?

![image](https://cloud.githubusercontent.com/assets/12991239/8273615/fe5731a4-1875-11e5-91c8-a457778fa4c7.png)

**Comment by milipili** [comment]
I don't know if it is possible, but please create another issue for that.

**Comment by cfman** [comment]
I was bugged by this problem too and found a solution here:
https://gist.github.com/jmc734/157ff4a4ee85f8e58102
Don't know if it is the right way to fix.
