### ISSUE TITLE
Plugin "Tidy2" is not "good" stability

### ISSUE THREAD

**Issue by ygoe** [notepad-plus-plus/notepad-plus-plus#2790]
The plugin manager shows a plugin named "Tidy2" and claims it has "good" stability. This is not true, the plugin outright fails to install with no additional details. The stability value should be changed to "broken" or the plugin removed altogether.

**Comment by dail8859** [comment]
This either needs reported to the PluginManager project or to the Tidy2 project.

**Comment by ygoe** [comment]
Where are they at home?

**Comment by dail8859** [comment]
Not sure what you mean. If you are looking for the Tidy2 project page try [here](https://github.com/bruderstein/NppTidy2).
