### ISSUE TITLE
Tab to tab marker when using spaces

### ISSUE THREAD

**Issue by jmeit** [notepad-plus-plus/notepad-plus-plus#2791]
I use 4 spaces instead of the TAB character. Currently the cursor moves by 4 spaces every time TAB (or Shift+TAB) is pressed.
It would be ideal for the cursor to jump to the next tab column, rather than 4 spaces forwards or back. 

### Steps to Reproduce the Issue

1. Turn on tab column markers: View > Show Symbol > Show White Space and TAB.
2. Set TAB to 4 spaces: Settings > Preferences > Language > Tab size: 4 & [x]Replace by space
3. Type any character, then hit TAB

### Expected Behavior

After the first random character is type and you hit TAB, there should only be 3 spaces produced, so that the cursor is then lined up with the first tab column, 4 spaces in.

### Actual Behavior

There are now 4 spaces after that first character, and the cursor is 5 character spaces in

**Comment by dail8859** [comment]
It works fine for me. Can you post your debug info (located under the `?` menu)?

**Comment by jmeit** [comment]
Notepad++ v7.2.2   (32-bit)
Build time : Nov 27 2016 - 16:31:07
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10
Plugins : ComparePlugin.dll dbgpPlugin.dll Explorer.dll InsertLoremIpsumNppPlugin.dll JSLintNpp.dll JSMinNPP.dll mimeTools.dll NppConverter.dll NppExport.dll NppFTP.dll NPPJSONViewer.dll NppJumpList.dll NppTextFX.dll PluginManager.dll SpeechPlugin.dll SpellChecker.dll Tidy2.dll

**Comment by dail8859** [comment]
I would try disabling your plugins to see if it is one of those. You can either rename your plugins folder or use `cmd` to run:

> "C:\Program Files (x86)\Notepad++\notepad++.exe" -noPlugin

**Comment by jmeit** [comment]
Thank you. You are correct. Now I have to disable them all and turn them back on, one at time, to figure out which one is causing the issue.
