### ISSUE TITLE
[Request] Find All in Current Document - Add the option of keeping the search window open

### ISSUE THREAD

**Issue by sibojan9** [notepad-plus-plus/notepad-plus-plus#2792]
Right now, once you click Search - Find All in Current Document, it will run the right command but the find windows closes automatically.  It has to be opened again manually if a second search is needed.
This is very annoying, especially when repeated searches occur. 
Please add the option of letting the search window stay open unless a close command is sent.
Thank you.

**Comment by psychicfork013** [comment]
+1

**Comment by MetaChuh** [comment]
this feature will currently not be implemented.

thank you for your help and best regards.
