### ISSUE TITLE
AccessViolationException in notepad++

### ISSUE THREAD

**Issue by neremin** [notepad-plus-plus/notepad-plus-plus#2794]
### Description of the Issue
While working with NppSharp installed (this plugin uses .NET) on any version of notepad++ it crashes unexpectedly when I try to change theme of theme settings.

### Steps to Reproduce the Issue

1. Take any x86 of NPP (I checked on 7.2.2 and 7.3)
2. Install NppSharp plugin http://nppsharp.codeplex.com/
3. Run NPP and go to Settings-> Style Configurator...
4. Change Font size and click Save & Close

### Expected Behavior
No crash should happen.

### Actual Behavior
Access violation exception inside notepad++ module. No traces of NppSharp on the stack trace.

### Debug Information
Notepad++ v7.2.2   (32-bit)
Build time : Nov 27 2016 - 16:31:07
Path : C:\npp.7.2.2.bin\notepad++.exe
Admin mode : OFF
Local Conf mode : ON
OS : Windows 10
Plugins : mimeTools.dll NppConverter.dll NppExport.dll NppSharp.dll PluginManager.dll 

Mini dump with heap and two messages logs from spy++ can be found here: 
http://bit.ly/2jhhiYK

1.sxl - log of messages when NppSharp is running and NPP crashes.
2.sxl - log of messages when NppSharp is not running and NPP works normally.

I have a branch of NppSharp on my machine, and I created converted it to a completely empty plugin with no functionality at all but using .NET. And Npp still crashes. So, my guess the problem migth be somewhere with .NET hosting inside NPP. Please, take a look at it as it might be a serious issue for many other users running .NET plug-ins.

**Comment by cmeriaux** [comment]
You'dd better report that issue to the plugin author. Here it is the wrong place.

**Comment by neremin** [comment]
As I mentioned at the end of debugging details section it appears to be
npp's issue with .NET. Plug-in is ok. Please read carefully.

пн, 16 янв. 2017 г. в 20:48, Christophe Meriaux <notifications@github.com>:

**Comment by MAPJe71** [comment]
@neremin Notepad++ does not use .NET.
The NppSharp plugin repository does not contain the latest Notepad++ Plugin Interface files which can lead to all kinds of unexpected problems. You'd better report the issue to the plugin author (as @cmeriaux already suggested) and/or resolve it with your fork of the repository.

**Comment by neremin** [comment]
You are right. I have isolated area where this plug-in crash.
