### ISSUE TITLE
[Improvement/Fix] - Make URL highlighting/formatting unicode aware by changing regex

### ISSUE THREAD

**Issue by ClaudiaFrank** [notepad-plus-plus/notepad-plus-plus#2798]
Current situation is that urls which contain unicode character aren't highlighted or formatted correctly.
The reason for that is the current regex used to identify urls.

Current regex: [A-Za-z]+://[A-Za-z0-9_\-\+~.:?&@=/%#,;\{\}\(\)\[\]\|\*\!\]+

To support urls containing unicode chars it would be needed to change the regex to e.g.

(?-s)[A-Za-z][A-Za-z0-9+.-]+://.*?(?=\s|$)

With this new regex a test has been done to check if urls containing any code point within the 
range 0x0 - 0x10FFFF would match - most of them did.

Tested scenarios:
start of file tests
-url at start of file (no additional text) (also end of file test)
-url at start of file (followed by tab)
-url at start of file (followed by space)
-url at start of file (followed by eol)
-url at start of file (followed by tab and text)
-url at start of file (followed by space and text)
-url at start of file (followed by eol and text)

end of file tests
-url at end of file (preceded by tab)
-url at end of file (preceded by space)
-url at end of file (preceded by eol)
-url at end of file (preceded by text and tab)
-url at end of file (preceded by text and space)
-url at end of file (preceded by text and eol)

in the middle of a file tests
-url in the middle of a file (preceded and followed by tab)
-url in the middle of a file (preceded and followed by space)
-url in the middle of a file (preceded and followed by eol)
-url in the middle of a file (preceded and followed by text and tab)
-url in the middle of a file (preceded and followed by text and space)
-url in the middle of a file (preceded and followed by text and eol)

Chars which "broke" (broke in terms of the match was reported until this char (char excluded)),
the tests are:

(the obvious ones)
0x0    = NULL
0x9    = TAB
0xA    = LineFeed
0xB    = VerticalTab
0xC    = FormatFeed
0xD    = CarriageRetrun
0x20   = Space
0x85   = Next Line 
0xa0   = No-Break Space
0x1680 = Ogham Space Makr
0x2000 = En Quad 
0x2001 = Em Quad 
0x2002 = En Space
0x2003 = Em Space 
0x2004 = Three-Per-Em Space 
0x2005 = Four-Per-Em Space 
0x2006 = Six-Per-Em Space 
0x2007 = Figure Space
0x2008 = Punctuation Space
0x2009 = Thin Space 
0x200A = Hair Space
0x200C = Zero Width Non-Joiner
0x200D = Zero Width Joiner
0x200E = Left-To-Right Mark
0x200F = Right-To-Left Mark
0x2028 = Line Separator
0x2029 = Paragraph Separator 
0x202f = Narrow No-Break Space
0x205f = Medium Mathematical Space 
0x3000 = Ideographic Space

and some unusual ones
(see the pattern 0x?0085, 0x?2028 and 0x?2029 !! ??)

0x10085 LINEAR B IDEOGRAM B105M STALLION
0x12028 Cuneiform Sign Al Times Ush     
0x12029 Cuneiform Sign Alan             

0x20085 CJK UNIFIED IDEOGRAPH
0x22028 CJK UNIFIED IDEOGRAPH
0x22029 CJK UNIFIED IDEOGRAPH

(code points are reported as unknown-unknown script by unicode.org,
which I guess means, valid but unused code point)
0x30085, 0x32028, 0x32029, 
0x40085, 0x42028, 0x42029,
0x50085, 0x52028, 0x52029,
0x60085, 0x62028, 0x62029,
0x70085, 0x72028, 0x72029,
0x80085, 0x82028, 0x82029,
0x90085, 0x92028, 0x92029,
0xa0085, 0xa2028, 0xa2029,
0xb0085, 0xb2028, 0xb2029,
0xc0085, 0xc2028, 0xc2029,
0xd0085, 0xd2028, 0xd2029,
0xe0085, 0xe2028, 0xe2029,
0xf0085, 0xf2028, 0xf2029,
0x100085, 0x102028, 0x102029

Nevertheless I think it is worth to change the regex.

Thank you
Claudia

**Comment by ClaudiaFrank** [comment]
As Guy pointed out, the \z switch could (should) be used to match the end of a buffer.
So new regex could be (?-s)[A-Za-z][A-Za-z0-9+.-]+://.*?(?=\s|\z)

**Comment by dail8859** [comment]
Hi @ClaudiaFrank

Couple questions: 

1. What's the reason for the additional `[A-Za-z0-9+.-]` before `://`. Is there particular case were just `[A-Za-z]+` is not sufficient?
2. In the later part, would `+` be better than `*`? That way it won't just match for example "`https://`"

So my suggested regex would be: `(?-s)[A-Za-z]+://.+?(?=\s|\z)`

**Comment by ClaudiaFrank** [comment]
Hi @dail8859,
1) yes, a scheme like http, https, file, etc... is specified that it must be start with a letter
but may contain numbers, dashes and dots. So something like z39.50s:// is absolutely valid.
2) I guess I don't get the point here. In your example it would match "https://[blank]" whereas with .*?
it wouldn't. But I see that it needs to be improved because otherwise a url containing a scheme followed by
:// only, would be formatted. Will follow up.

**Comment by ClaudiaFrank** [comment]
I guess this
(?-s)[A-Za-z]+://[^\s]+?(?=\s|\z)
would do the trick - will run the tests to see if it is the case.

**Comment by ClaudiaFrank** [comment]
tests passed, so actual proposal is to use
(?-s)[A-Za-z][A-Za-z0-9+.-]+://[^\s]+?(?=\s|\z)

**Comment by chcg** [comment]
Original discussion see https://notepad-plus-plus.org/community/topic/13027/notepad-url-processing-cyrillic-symbols/17

**Comment by ClaudiaFrank** [comment]
requirements could not be fullfilled
