### ISSUE TITLE
COBOL comment on column 7

### ISSUE THREAD

**Issue by nunoperalta** [notepad-plus-plus/notepad-plus-plus#280]
The COBOL parser doesn't make a comment green if there is a character just before the star (*).

In my environment, we put tags everywhere, and most of them have 6 characters, so most of the COBOL comments are not correctly parsed in Notepad++, and this creates a big confusion sometimes.

It is perfectly valid to have a tag of 6 characters and a star (*) just after that, and that should be parsed as a comment.

![sshot-2015-06-21-22-21-27-1](https://cloud.githubusercontent.com/assets/487079/8273402/e036598c-1863-11e5-8eaf-074fb33129f2.jpg)

Thank you,
Nuno

**Comment by GitMensch** [comment]
@nunoperalta You're right that you can insert anything in column 1-6 but I *think* this problem is a problem in the Scintilla components. I wonder if the fix to this bug in Scintilla https://sourceforge.net/p/scintilla/bugs/977/ was integrated into NPP?

**Comment by MetaChuh** [comment]
closed due to inactivity (4y)
