### ISSUE TITLE
[Code Cleanup] - Consider removing NPPM_ENCODESCI and NPPM_DECODESCI messages

### ISSUE THREAD

**Issue by ClaudiaFrank** [notepad-plus-plus/notepad-plus-plus#2804]
Currently it looks like the messages
NPPM_ENCODESCI
NPPM_DECODESCI
aren't used anymore. Both are having only a reference in
PowerEditor/src/MISC/PluginsManager/Notepad_plus_msgs.h
and are defined as possible "case" in switch loop in
PowerEditor/src/NppBigSwitch.cpp

**Comment by dail8859** [comment]
Though not used within Notepad++ it is still possible a plugin still uses it. (I think the HexEditor does.)

**Comment by ClaudiaFrank** [comment]
OK - I thought those messages get triggered by npp and consumed by plugins but if
it is allowed that plugins can trigger it than it must obviously stay.

**Comment by dail8859** [comment]
The naming convention is:

- if it starts with `NPPM` it is a *message* that a plugin can send to N++ (i.e. telling N++ to do something)
- if it starts with `NPPN` it is a *notification* Notepad++ sends to the plugin (i.e. N++ telling the plugin something just happened)

**Comment by ClaudiaFrank** [comment]
I see - thanx for clarification.
Very much appreciated.
