### ISSUE TITLE
Notepad++ Update using Automatic configuration script Proxy

### ISSUE THREAD

**Issue by AJ-Stevens** [notepad-plus-plus/notepad-plus-plus#2806]
### Description of the Issue
Notepad++ requires manual setting of proxy to update main program, however Plugin Manager is able to download and install plugins through our Autoconfiguration Proxy (PAC file), so why can't the main program update do this as well?

### Steps to Reproduce the Issue

1. Configure client to use an Automatic configuration script proxy, pac file in Internet Options in Windows.
2. Run Notepad++, use the ? -> Update Notepadd++ option in the menu.

### Expected Behavior
Notepad++ to pick up the system internet settings, use the pac file, determine the proxy server IP and port from the pac file, use them to connect to get the latest version of Notepad++.

### Actual Behavior
Notepad++ doesn't read proxy settings and attempts direct access, presents popup error message as it hits firewall, "Failed to connect to notepad-plus-plus.org port 443: Bad access".

### Debug Information
Notepad++ v7.2.2   (32-bit)
Build time : Nov 27 2016 - 16:31:07
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10
Plugins : ComparePlugin.dll mimeTools.dll NppConverter.dll NppExport.dll NppTextFX.dll PluginManager.dll SpellChecker.dll XMLTools.dll 

Odd that even with the proxy set, it doesn't off me an update to 7.3.1 from my 7.2.2, I presume the file it checks on the Notepad++ website has not been updated, or they're not urgent updates?

**Comment by buglessdr** [comment]
+1

**Comment by MetaChuh** [comment]
@AJ-Stevens 
automatic proxy settings will currently not be implemented.

thank you for your help and best regards.
