### ISSUE TITLE
move line up | move line down | line's text is selected sometime between 6.1 and 6.9

### ISSUE THREAD

**Issue by SgtSQL** [notepad-plus-plus/notepad-plus-plus#2807]
### Description of the Issue

Change or regression to "move line up" / "move line down" sometime between 6.1 and 6.9.
Still present in 7.2.2.

### Steps to Reproduce the Issue

Consider the following scenario
1. You have 3 lines of text (line 1, line 2, line 3)
2. Your cursor is somewhere on line 3
3. You hit Ctrl + Shift + Up Arrow to move line 3 above line 2
4. You then hit Backspace to move the current line to the end of the line above (line 1)

### Expected Behavior

1. In 6.1, after doing a "Move line up" or "Move line down", the text of the current line was not selected, the cursor was moved to the beginning of the current line, and hitting backspace moved the current line to the end of the line above it.

### Actual Behavior

2. Starting in at least 6.9 (maybe earlier), hitting backspace deletes the current line because the entire line's text is selected after moving the line up or down. Behavior is still present in 7.2.2.

### Debug Information

Notepad++ v7.2.2   (32-bit)
Build time : Nov 27 2016 - 16:31:07
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10
Plugins : ComparePlugin.dll mimeTools.dll NppConverter.dll NppExport.dll PluginManager.dll 

The use case that affects me:

I have scripts to generate and open .sql template files when I open support tickets.

The sql clauses are incomplete ending with WHERE x = 

Customer parameters are written to a sql support template file.

I then select the parameter text and  use "move line up" or "move line down" to move the parameters to
the line below the where clause. I used to hit backspace to move the parameter to the end of the WHERE clause.

After this change or regression occurred, I have to hit Left Arrow (Escape doesn't work) to deselect the text before hitting backspace to avoid deleting the current line.

Thanks for the great product. It makes me much more productive. If this was an intentional change and not a regression, I can adapt. 

Troy

**Comment by dail8859** [comment]
This behavior was changed in faf107a4efc201bc8e3e1846194a6d45ba0349bb (v6.9) which uses much more efficient calls for moving lines. The entire line being selected was a side effect of the new calls that (a) I overlooked, but mostly because (b) I thought it wouldn't matter. :)

I guess it would be up to @donho to either consider this a minor regression that needs fixed, or the new behavior is acceptable.

**Comment by ngreyling** [comment]
I also hope this problem with the unwanted selection can be fixed so it goes back to the way it was before v6.9. Whenever I move lines up or down, I now have to manually deselect the text each time, which is a pain.

**Comment by Eldaw** [comment]
I finally moved to VS Code, which handles the moving of lines perfectly. I can now move lines without selecting them -- what a concept!

This is just one example of several simple things that @donho has never cared about, which likely have no prospect of ever being fixed in Notepad++.

**Comment by ATgeir** [comment]
This is driving me nuts! I upgraded some weeks ago, and I'm still deleting lines all the time. Even if I do get used to it, it is not a sensible way for this to work. Please, please fix it, so that I don't have to change editor :-)

**Comment by SgtSQL** [comment]
Is this a beginner-friendly issue? I would think this is a one-liner to patch.

I'm a developer, but I've never submitted a GitHub pull request before, and I've never used C++.  I'm happy to submit a pull request for this issue if you think a dev who has never used C++ before could handle this without introducing a security bug or performance regression.

**Comment by dail8859** [comment]
@SgtSQL  In theory it should be an easy fix by just making a few calls extra to the Scintilla editor to position the cursor correctly after the lines have been moved. Though I can't say for certain if the current behavior is acceptable or does indeed need fixed.

**Comment by ATgeir** [comment]
I have no idea how this works myself, but if it is not a problem in Scintilla, that sounds very sensible. I think the cursor is positioned correctly after the move, so the only problem is that the text remains selected.

**Comment by SgtSQL** [comment]
**@dail8859** Thanks for the "quick-silver" follow up. In your original reply in January, you mentioned that you didn't think the change would matter. 

Do you know of a different workflow/scenario in which you prefer the current behavior? I don't want to submit a PR for something that was wanted by more people than don't want it...but if 3 other users found this thread and commented on GitHub, it likely impacted more users. This was a breaking change to existing editor behavior.

Would you be willing to mentor me if I run into any problems getting the project to build/submitting my first GitHub PR? I'm not needy...I always Google-search first. :)

**Comment by dail8859** [comment]
> you mentioned that you didn't think the change would matter.

I just never thought to check where the cursor ended up. In hindsight yes I wish I would have paid attention and kept the cursor in the same location after the lines were moved so that it wouldn't effect any users. But now it may be the case some users are use to the new behavior.

> Do you know of a different workflow/scenario in which you prefer the current behavior?

The only reason I really made the change was to make the code more efficient by replacing the code with a couple of simple calls to Scintilla directly. 

> Would you be willing to mentor me if I run into any problems getting the project to build/submitting my first GitHub PR?

I don't mind helping someone get started (assuming they are mostly self sufficient ;) ) Probably easiest to message me on [gitter](https://gitter.im/notepad-plus-plus/notepad-plus-plus).

**Comment by ATgeir** [comment]
Sorry, I said the cursor position was right, but I only thought about the case when I'm already at the start of the line. If the operation is started in the middle of a line, the cursor ends up at the start of the line.

Another behaviour that may be worth considering: If I select some text on one line, and leave the cursor at the start of the next line, only the first line will move. Before, both lines would be moved.

Keeping the lines selected while moving is very nice visually, to keep track of what is happening, but as soon as the move is done, the selection should go away, in my opinion.

**Comment by MetaChuh** [comment]
@SgtSQL 
please use <kbd>left</kbd> before hitting backspace on marked text, to avoid its deletion.

thank you for your help and best regards.
