### ISSUE TITLE
Remove border for a better and modern look

### ISSUE THREAD

**Issue by surajmandalcell** [notepad-plus-plus/notepad-plus-plus#2809]
### Description of the Issue

Notepad++ looks outdated since the release of windows 10 and other modern code editors. It'd be a nice addition if the notepad++ window didn't had any border so the themes could look more glossy and could give the editor a new life.

![npp no border](https://cloud.githubusercontent.com/assets/11650177/22173716/3cb12a42-dff1-11e6-8c4d-d5efb1c909ed.jpeg)

**Comment by MAPJe71** [comment]
Did you try changing the `Border Width` parameters of menu `Settings`, `Preferences...`, `Editing`?

**Comment by rddim** [comment]
Also you must to check the `No edge` option

**Comment by surajmandalcell** [comment]
Thanks @MAPJe71 ..problem solved.
  
![npp_border](https://cloud.githubusercontent.com/assets/11650177/22180398/6787ee0a-e095-11e6-8f67-8d47e466e633.jpeg)
