### ISSUE TITLE
Suggestion: Auto close PHP start tag. 

### ISSUE THREAD

**Issue by ghost** [notepad-plus-plus/notepad-plus-plus#281]
I saw that the brackets close automatically and if you press enter just after the first bracket, it will auto indent too... I personally think this would be an awesome feature if php start tag would automatically close itself too.

![image](https://cloud.githubusercontent.com/assets/12991239/8273615/fe5731a4-1875-11e5-91c8-a457778fa4c7.png)

**Comment by Deadooshka** [comment]
in most cases closing php-tag is not needed

**Comment by ifarbod** [comment]
@Deadooshka I Agree.

**Comment by MetaChuh** [comment]
closed due to inactivity.
