### ISSUE TITLE
Different MD5 and SHA-256 sums in ANSI file

### ISSUE THREAD

**Issue by rddim** [notepad-plus-plus/notepad-plus-plus#2812]
Hello again,

- In version 7.3.1 with ANSI file and word `тест` I get different sums - `ebb5e89e8a94e9dd22abf5d915d112b2` with `Generate...` and `98554ea0cb509620815fe5bf980246ec` with `Generate into clipboard`
In UTF-8 and UCS-2 the sums are `ebb5e89e8a94e9dd22abf5d915d112b2` with both options.

- In version 7.3 with ANSI file and word `тест` I get `98554ea0cb509620815fe5bf980246ec` with both options.
In UTF-8 and UCS-2 the sums are different - `98554ea0cb509620815fe5bf980246ec` with `Generate...` and `ebb5e89e8a94e9dd22abf5d915d112b2` with `Generate into clipboard`

Reference to #2743 

**Debug info:**
Notepad++ v7.3.1   (32-bit)
Build time : Jan 17 2017 - 00:21:10
Path : D:\Install\Office Programs\Notepad++\notepad++.exe
Admin mode : ON
Local Conf mode : ON
OS : Windows 7
Plugins : ComparePlugin.dll mimeTools.dll NppExport.dll NppHasher.dll NppTextFX.dll PluginManager.dll

**Comment by donho** [comment]
@rddim 
> In version 7.3.1 with ANSI file and word тест I get different sums - ...
Could you provide the ANSI file contains only  `тест` and a screenshot of this file opened in notepad++ (with the status bar)?

**Comment by rddim** [comment]
The txt file is inside the zip

[npp_md5_sum.zip](https://github.com/notepad-plus-plus/notepad-plus-plus/files/721979/npp_md5_sum.zip)

![npp_md5_sum](https://cloud.githubusercontent.com/assets/8998791/22183018/50055e58-e0bc-11e6-877e-a64cd9f31f46.png)

**Comment by donho** [comment]
![image](https://cloud.githubusercontent.com/assets/90293/22227980/8b2787d2-e1ce-11e6-8fef-d89d39efaebc.png)

I opened the file you provided, as Windows-1251 automatically...

**Comment by rddim** [comment]
Yes, if you have enabled `Autodetect character encoding` in `MISC.` preferences it is opened as `Windows-1251`, but if you disable this option, the file is opened as ANSI. I disable it because between 10.08-22.08.2015 we have a conversation in facebook about another problematic txt file which is recognized as `ISO 8859-7` and shows some cyrillic chars as Greek and Hebrew and everytime I must set it manually to `Windows-1251`. Then you suggest me to disable the `Autodect character encoding`

**Comment by MetaChuh** [comment]
@rddim 
i can not reproduce on 7.6.6, as i can not paste `тест` into an ansi file.
is this encoding dependent md5 issue for non utf-8 files still of relevance or can you close it ?

thank you for your help and best regards.

**Comment by rddim** [comment]
@MetaChuh 
Yes, the issue is with non utf-8 files

At the 1st part I check the `Autodetect character encoding` to get the `Windows-1251`
At the 2nd part I uncheck it to get the `ANSI`

![npp_md5](https://user-images.githubusercontent.com/8998791/57084837-b1649800-6d03-11e9-8442-2de0dcd7abc1.gif)

**Comment by donho** [comment]
@rddim  
Is it still the issue in v7.8.2 ?

**Comment by rddim** [comment]
@donho 
Yes, the issue still exist in v7.8.2

**Comment by donho** [comment]
@rddim 
Tested in Notepad++ v7.9.5, with "Automated character encoding" disabled, I've got the following result after open the file in question:
![image](https://user-images.githubusercontent.com/90293/113605994-b3e66f80-9647-11eb-819a-ab229462a809.png)

After settings the file to Windows 1251 encoding, selecting the right displayed character and copying the MD5 of selected into the clipboard, here is the pasted result: 

![image](https://user-images.githubusercontent.com/90293/113606564-7b936100-9648-11eb-909a-2ab623139cac.png)

So I consider the bug is fixed (by updating Scintilla I guess) in the latest version.
