### ISSUE TITLE
Settings not saved - Default directory

### ISSUE THREAD

**Issue by arthurritic** [notepad-plus-plus/notepad-plus-plus#2814]
Settings/Preferences/Default Directory: Use new style save dialog

The default setting for "Use new style save dialog" in version 7.3.1 is checked

If I uncheck this setting it automatically reverts to checked when I restart Notepad++

Have reverted to version 7.3

**Comment by AraHaan** [comment]
Same issue when you open Notepad++ with no memory where if it tries to read the settings but cant it will overwrite all of my settings to default which is total BS.

**Comment by ziffel** [comment]
Same problem - "Use new style save dialog"  option not saving. If I uncheck, it comes back checked next time I open N++. Other options changes are saved.

**Comment by LuaQ** [comment]
Hi, i'm a random stranger... #uhyah

**Comment by AstralTim67** [comment]
Same issue.  Cannot save default directory choice or custom backup directory choice.  Upon restarting the program it defaults to the previously saved setting, not the program default.  I really like this program?  Any chance it will be fixed soon?  expertinternetsecrets.com
