### ISSUE TITLE
Bug with transition from x86 to x64 version. Registration of the app turns out to be invalid.

### ISSUE THREAD

**Issue by zalima** [notepad-plus-plus/notepad-plus-plus#2817]
### Description of the Issue
If I have already installed and removed an x86 version, the installation of x64 version turns out to be buggy. The app looks as it is not registered in Windows OS: file associations do not work, and the "Open With" dialogue does not suggest Notepad++ as an option.

### Steps to Reproduce the Issue
1. Install x86 version.
2. Remove x86 version.
3. Install x64 version.
4. Try to associate Notepad++ with .txt by any standard way.

### Expected Behavior
It must allow to be associated with different file types like any other application.

### Actual Behavior
Standard ways do not work.

### Debug Information
This happens because the x86 version sets
[HKEY_CURRENT_USER\Software\Classes\Applications\notepad++.exe\shell\open\command]
@="\"C:\\Program Files (x86)\\Notepad++\\notepad++.exe\" \"%1\""
and the x64 installer does not change this.
If you manually change it to
[HKEY_CURRENT_USER\Software\Classes\Applications\notepad++.exe\shell\open\command]
@="\"C:\\Program Files\\Notepad++\\notepad++.exe\" \"%1\""
then associations by standard means of Windows work fine. (Though associations made from the options menu of Notepad++ seam do not work properly still. But the reason of this possibly is different. Possibly because they do not work properly from the standard user account. Some further investigation is neaded.)
So, when an x64 version is installed, the installer must re-register the application properly.

**Comment by MetaChuh** [comment]
please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins if you update from version 7.5.9 or below.
if your issue still persists, and it is still of relevance, please feel free to file a new issue as easy to understand and reproducible as possible.

thank you for your help and best regards.

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
(no extra account is needed, just use your github account to sign in)
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)
