### ISSUE TITLE
Error Dialog disables keyboard shortcuts

### ISSUE THREAD

**Issue by mattman00000** [notepad-plus-plus/notepad-plus-plus#2818]
### Description of the Issue
When an error dialog is open (for example "File is too big to be opened by Notepad++") keyboard shortcuts appear not to function. Ctrl+S for instance inserts [DC3] ASCII Device Control 3 character 0x13 because its caret notation is ^S, which is the same thing that happens if you change Save to another or no shortcut and press Ctrl+S

### Steps to Reproduce the Issue

1. Attempt to open a large file
2. Don't click OK on "File is too big to be opened by Notepad++"
3. With focus in editor, press Ctrl+S

### Expected Behavior
Functioning keyboard shortcuts

### Actual Behavior
Nonfunctioning keyboard shortcuts, insertion of control codes based on caret notation

### Debug Information

Notepad++ v7.2.2   (32-bit)
Build time : Nov 27 2016 - 16:31:07
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10
Plugins : ComparePlugin.dll mimeTools.dll NppConverter.dll NppExport.dll NppTextFX.dll PluginManager.dll 

Cause of problem discovered at http://superuser.com/a/211091

**Comment by MetaChuh** [comment]
please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins if you update from version 7.5.9 or below.
if your issue still persists, and it is still of relevance, please feel free to file a new issue as easy to understand and reproducible as possible.

thank you for your help and best regards.

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
(no extra account is needed, just use your github account to sign in)
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)
