### ISSUE TITLE
NPP crash during column mode number insertion

### ISSUE THREAD

**Issue by ffeldner** [notepad-plus-plus/notepad-plus-plus#2820]
### Description of the Issue

When using the number insertion in a new, empty document, NPP crashes when trying to insert the numbers.
Bug encountered on NPP 7.2.2 64bit on Win10 64bit

### Steps to Reproduce the Issue

1. Open a new, empty document in NPP
2. Press and hold Alt+Shift and Right Arrow once to select the one character in the column
3. Go to Edit > Column Editor...
4. Select Number to Insert and fill in 1 for Initial Number, 1 for Increase By, 16 for Repeat, Check Leading Zeros
5. Click OK

![npp_01](https://cloud.githubusercontent.com/assets/15093259/22252292/f569cdc4-e24d-11e6-81b9-d94f6cb9390a.png)

### Expected Behavior

To receive output or an error notification by NPP instead of a crash

### Actual Behavior

Notepad has stopped working... Error box appears

![npp_02](https://cloud.githubusercontent.com/assets/15093259/22252291/f5698206-e24d-11e6-940d-8147280813a6.png)

### Debug Information

Notepad++ v7.2.2   (64-bit)
Build time : Nov 27 2016 - 16:35:52
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10
Plugins : mimeTools.dll NppConverter.dll

**Comment by rddim** [comment]
NPP v7.3.1 x64 also crash, x86 did nothing on Win7 x64. Without step 2 in both x64 and x86 the output is digit 1
