### ISSUE TITLE
Installing/Updating plugins impossible without admin rights

### ISSUE THREAD

**Issue by spheenik** [notepad-plus-plus/notepad-plus-plus#2824]
### Description of the Issue
Trying to install/update plugins fails for users without elevated rights, even if Notepad++ is installed in the users home folder (or another folder user has write access to)

When clicking Plugins -> Plugin Manager -> Show Plugin Manager, Notepad++ gives a hint under "Settings", that "Plugins in user's AppData directory are disabled - to enable in Notepad++ version 5.9.7 onwards place an empty file called allowAppDataPlugins.xml in the Notepad++ directory." However placing that file does not change a thing. Moving the complete N++ folder to the Users folder or under APPDATA also does not help.

### Debug Information
Notepad++ v7.3.1   (32-bit)
Build time : Jan 17 2017 - 00:21:10
Path : C:\java\tools\np++\notepad++.exe
Admin mode : OFF
Local Conf mode : ON
OS : Windows 7
Plugins : mimeTools.dll NppConverter.dll NppExport.dll PluginManager.dll

**Comment by mrasp** [comment]
We've got the same problem. Our Notepad++ 6.6.9 x86 (yes I know, it's old) is under control of our IT department. The plugin manager asks for admin privileges.
The unzipped version of Notepad++ 7.3.2 x86 in my user home directory has a plugins folder and even the plugin manager of that "installation" asks for admin privileges to install a plugin.

**Comment by KOLANICH** [comment]
Thereis a workaround: you can edit gpup.exe with text editor, locate XML manifest there, replace ```"requireAdministrator"``` to ```"asInvoker"           ```. Of course digital signatures will be broken, but it worked. The drawback is that you will have to do this on every npp update (or make it read-only).

**Comment by chcg** [comment]
See https://notepad-plus-plus.org/community/topic/14315/notepad-7-5-release, PluginManager is no longer part of N++. https://github.com/bruderstein/nppPluginManager/issues is the place to report the problem.
