### ISSUE TITLE
Wrong regex error on a correct regex

### ISSUE THREAD

**Issue by brunoais** [notepad-plus-plus/notepad-plus-plus#2826]
### Description of the Issue

When trying to search inside a file using the following regex:

	e: h\(\) \{\s+dd\({(.*?)\n\s+}\);\s+\}

Notepad++ responds with an error:

> Find: Invalid regular expression

If, however I try to use the regex on any regex engine I can think of, including [https://regex101.com/](https://regex101.com/), I get that the regex expression is correct.
What am I doing wrong?

### Steps to Reproduce the Issue

1. Open search (Ctrl + F)
2.  Activate regex search (3rd option in the 3 options on the left)
3.  Type in the search as specified above.
4. Error message shows up (as above)

### Expected Behavior

A search using the regex expression specified above.
### Actual Behavior

Rejects the search stating the regex is invalid.
### Debug Information

Notepad++ v7.2.2   (32-bit)
Build time : Nov 27 2016 - 16:31:07
Path : [censored]\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10
Plugins : mimeTools.dll NppConverter.dll NppExport.dll NppSaveAsAdmin.dll PluginManager.dll

**Comment by MAPJe71** [comment]
Escape *all* curly brackets, like so: `e: h\(\) \{\s+dd\(\{(.*?)\n\s+\}\);\s+\}`

**Comment by brunoais** [comment]
Oh. Thanks. Sorry about that.
