### ISSUE TITLE
hangs on loading .js file

### ISSUE THREAD

**Issue by erict-powersoft** [notepad-plus-plus/notepad-plus-plus#2835]
### Description of the Issue

trying to open .js file in c:\program files (x86) space.  

### Steps to Reproduce the Issue

1.  File Open, or right-click in explorer and doing "Open with Notepad++"
2. 
3. 

### Expected Behavior

File can be edited 

### Actual Behavior

never-never land (Notepad++ had to be killed in taskmgr)
### Debug Information

tried with 7.2.2 (32-bit) run normal and as administrator, then upgraded to 7.3.1 (32-bit) -- no change.
[testJSON.zip](https://github.com/notepad-plus-plus/notepad-plus-plus/files/736443/testJSON.zip)

File can be edited without problems in Notepad (as admin, because file is in Prog Files x86)

**Comment by dail8859** [comment]
Works fine for me. Please follow the template and post your actual debug info from the `?` menu. Also disable your plugins since it could be one of those.
