### ISSUE TITLE
"Update Notepad++" not working since Notepad++ version 6.9 (32bit)

### ISSUE THREAD

**Issue by jlar0che** [notepad-plus-plus/notepad-plus-plus#2836]
### Description of the Issue
Updating Notepadd++ via the "Update Notepad++" button under the "?" menu has been returnin "No update is available" since version 6.9. For example, I am currently running version 7.2.2 (32bit) and I know the newest version at this time is 7.3.1.

### Steps to Reproduce the Issue
1. Run "Update Notepad++" on an installation that is not the current newest version available

### Expected Behavior
New version downloaded and Notepad++ updates.

### Actual Behavior
Dialog box stating "No update is available."

### Debug Information
Notepad++ v7.2.2   (32-bit)
Build time : Nov 27 2016 - 16:31:07
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : ON
Local Conf mode : OFF
OS : Windows 10
Plugins : mimeTools.dll NppConverter.dll NppExec.dll NppExport.dll NppFTP.dll NPPJSONViewer.dll NppSnippets.dll PluginManager.dll Python Indent.dll ScrollPastEOFUni.dll 

![broken-updates](https://cloud.githubusercontent.com/assets/1959495/22398676/54603664-e55b-11e6-8c17-56d9f0201308.jpg)

**Comment by dail8859** [comment]
Works for me...
![capture](https://cloud.githubusercontent.com/assets/3694843/22398953/1addc8de-e560-11e6-9671-c9ae687df182.PNG)

v7.2.2 is the newest version the auto-updater will find right now. Once new releases have been out for a little while and deemed fully stable, then the auto-updater will get triggered.

**Comment by donho** [comment]
It could be the newest version update is not triggered yet from the sever side.
