### ISSUE TITLE
.txt Files

### ISSUE THREAD

**Issue by AshlynKat** [notepad-plus-plus/notepad-plus-plus#2838]
### Description of the Issue
So last night my notepad ++ was working just fine, now I have to type .txt after what I name the file in order to make it .txt and not just a file

### Steps to Reproduce the Issue

I just name a file and don't type .txt

### Expected Behavior
I expected it to make the file .txt like it should

### Actual Behavior
It changed the .txt file to just a file. 

![screenshot 132](https://cloud.githubusercontent.com/assets/25410311/22401187/9ce4160c-e598-11e6-8ddd-d6df68bf3c52.png)

**Comment by dail8859** [comment]
Since you didn't post your debug info I'm assuming you are using v7.3.1. If so this is a known issue and will be fixed in the next release. See #2829 and #2814
