### ISSUE TITLE
Inconsistent character encoding detection on open vs reload

### ISSUE THREAD

**Issue by Darkwolfdude** [notepad-plus-plus/notepad-plus-plus#2843]
Hi, using version 7.3.1 (it was also bugged on a previous version) I've been working on some UTF-8 XML (this XML class that i'm working with only accepts UTF-8 input and will crash out otherwise - and also putting the file through phps libxml error detection to confirm if it's UTF-8 or not - which it is when this error occurs).

When I open a newly created file the document displays in UTF-8 as expected, however when it automatically refreshes the file or reload the file after it has been updated, the file encoding changes from UTF-8 to TIS-620. It appears that the character that is mainly bugging it out is the left accented a; "á" (in my testing at least).

I took a look at a couple of the other issues raised and I tried going Preferences -> Misc -> Autodetect character encoding and turned that off. It worked after closing the original file, opening it, changing it externally then reloading it (but it didn't fix it after just changing the option then reloading the file after changing it externally).

I also have Preferences -> New Document -> Encoding -> UTF-8 > Apply to opened ANSI files [ON] (altering this didn't seem to do anything for me - but may not have tested that properly).

*When I reference UTF-8, it's without BOM.

### Debug Information
Notepad++ v7.3.1   (64-bit)
Build time : Jan 17 2017 - 00:28:43
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10
Plugins : mimeTools.dll NppConverter.dll 

Screenshot1 (Expected):
![image](https://cloud.githubusercontent.com/assets/2396866/22408952/e688e684-e679-11e6-8ed7-4d77ee36090b.png)

Screenshot2 (Actual):
![image](https://cloud.githubusercontent.com/assets/2396866/22408959/f8091f1e-e679-11e6-82c3-b571eca25e3a.png)

**Comment by Gabr-F** [comment]
I don't know how Notepad++ attempts to detect UTF-8 files, but it's usually just possible to rule out that a file is _not_ UTF-8, if it contains codes illegal in UTF-8.
If you can you should really use BOMs for your unicode files, if you want to edit them conveniently with text editors; something that might be a BOM will probably always be regarded as a sure indicator of a unicode file, by unicode-aware editors.

(by the way your XML class will only crash if you happen to use illegal UTF-8 characters or sequences)
