### ISSUE TITLE
Notepad++ 7.3.1 64-bit, default font style replaced on small text

### ISSUE THREAD

**Issue by liviuconcioiu** [notepad-plus-plus/notepad-plus-plus#2844]
### Description of the Issue

The default font style is replaced on a small part of text/screen and also some part of the text is intercalated. I am using UTF-8 without BOM for files and as far as I can tell the only reason is a Norsk character, Ø. An exact image can be seen on the screenshot.

### Steps to Reproduce the Issue

1. Place a Ø character.

### Expected Behavior

The default font style (Courier New, 10) shouldn't be replaced.

### Actual Behavior

The default font style (Courier New, 10) is replaced on part of text (one line) where Ø is present.

### Debug Information

![untitled](https://cloud.githubusercontent.com/assets/25424343/22410405/5bfeb83c-e6a0-11e6-911f-eac10486dffd.png)
I use Notepad++ 7.3.1 64-bit version on Windows 10 Pro.

**Comment by dail8859** [comment]
Could you provide a small text file that has this issue?

**Comment by liviuconcioiu** [comment]
[sample.txt](https://github.com/notepad-plus-plus/notepad-plus-plus/files/738091/sample.txt)

**Comment by liviuconcioiu** [comment]
Just open the file with Notepad++. It will reproduce the exact same issue.

**Comment by liviuconcioiu** [comment]
While debugging the query in phpMyAdmin, I see it put a dot before Ø. Just paste the content from the sample.txt to phpMyAdmin SQL window.

**Comment by liviuconcioiu** [comment]
Also, Ø is the capital letter for ø.

**Comment by dail8859** [comment]
Everything looks fine to me. Using a hex editor there does appear to be a BOM marker (EF BB BF) right before the Ø.

**Comment by dail8859** [comment]
So can this issue be closed now?
