### ISSUE TITLE
LaTeX comments highlighting

### ISSUE THREAD

**Issue by softcoderuser** [notepad-plus-plus/notepad-plus-plus#2847]
### Description of the Issue
Syntax highlighting of comments in LaTeX is not supported by Notepad++

### Steps to Reproduce the Issue
Add % in front of something you want to comment out.

### Expected Behavior
When I start a row with % I expect all characters after it to be a different colour than the rest of the text

### Actual Behavior
The % sign is the same colour as other operators and what comes after is the same colour as ordinary text.

### Debug Information
I expected the entire line 23 to be in a different colour.
<img src='http://i.imgur.com/bBDx3P5.png'>

**Comment by AakaFosfor** [comment]
There seems to be a [workaround](https://sourceforge.net/p/notepad-plus/discussion/331754/thread/ecd1c591/#04d4) mentioned by fallino few years ago. The color can be also changed via the UI (Settings -> Style Configurator...)

**Comment by AakaFosfor** [comment]
@softcoderuser was it [tex](https://github.com/notepad-plus-plus/notepad-plus-plus/blob/0686435d1ac6caac55520b57b934f736593a7d4c/PowerEditor/src/stylers.model.xml#L1198) or [latex](https://github.com/notepad-plus-plus/notepad-plus-plus/blob/0686435d1ac6caac55520b57b934f736593a7d4c/PowerEditor/src/stylers.model.xml#L645) highlighting? The LaTeX one seems to work OK.

**Comment by MetaChuh** [comment]
please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins if you update from version 7.5.9 or below.
if your issue still persists, and it is still of relevance, please feel free to file a new issue as easy to understand and reproducible as possible.

thank you for your help and best regards.
