### ISSUE TITLE
Auto-detect XML type files

### ISSUE THREAD

**Issue by znakeeye** [notepad-plus-plus/notepad-plus-plus#285]
XML files are commonly used today, but very often they have arbitrary file extensions. I can see that many users in this forum have asked for more XML extension to be added. You can close all those requests in five minutes if you simply detect the xml-header of opened files.

E.g.
<?xml version="1.0" encoding="utf-8" standalone="yes"?>

Just check for "<?xml" after the BOM. If found, use XML syntax highlighting.

I've waited a year for this feature to show up, but it seems nobody ever thought of it. So here we go! :)

**Comment by cmeriaux** [comment]
Hello,
You may be able to do that with the python script plugin
Christophe

**Comment by znakeeye** [comment]
Please show me one modern text editor that doesn't handle the xml header... Let's start with Visual Studio.

No, this needs to be fixed.

**Comment by dail8859** [comment]
Closed by 9b91480
