### ISSUE TITLE
"Reload from Disk" doesn't say or do anything if the file is not present anymore

### ISSUE THREAD

**Issue by Gabr-F** [notepad-plus-plus/notepad-plus-plus#2853]
If a file loaded in Notepad++ is not present anymore "Reload from Disk" will not give you any notice about that and not even change the status of the buffer to "unsaved".
This will give the user the false impression that the file still exists and has been successfully reloaded.

### Steps to Reproduce the Issue
1. Open a file in Notepad++
2. Delete the file
3. Go back to Notepad++
3. If you had "File Status Auto-Detection" enabled you'll be asked whether to keep the file in the editor. Select "Yes".
4. Use the "File -> Reload from Disk" command in Notepad++

### Expected Behavior
There should be a notification that the file doesn't exist anymore, and the status of the buffer should be changed to "unsaved" (with a red icon on the tab instead of the blue one).

### Actual Behavior
Notepad++ doesn't do anything, so that it appears that the file was reloaded successfully.

The fact that the file status is left to saved means that you also won't be given a warning that the file is unsaved when you exit from Notepad++, so if the file had been deleted by mistake you'll lose your last copy of it.

Of course the issue is less problematic if you have the "File Status Auto-Detection" feature enabled, as you'll at least be given a warning the first time you go back to Notepad++ after the deletion.

---

Tested on Notepad++ v7.3.1 32-bit.

**Comment by szheng95** [comment]
I don't get a notification that the file doesn't exist anymore, either. That said, as soon as I click "yes" to keep the file, the tab color changes to unsaved. If I then try to close the application there is a prompt stating that your backup file cannot be found and asking if I want to save the file. So it's not exactly the best behavior, but doesn't seem like there's a large risk of data loss if deleted by mistake.

Notepad++ v7.3.1 32-bit Windows 10 x64

**Comment by MetaChuh** [comment]
please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins if you update from version 7.5.9 or below.
if your issue still persists, and it is still of relevance, please feel free to file a new issue as easy to understand and reproducible as possible.

thank you for your help and best regards.
