### ISSUE TITLE
Block Uncomment not working for Windows .cmd files either

### ISSUE THREAD

**Issue by jimshilliday** [notepad-plus-plus/notepad-plus-plus#2854]
### Description of the Issue
"Block uncomment" function not working in Windows .cmd files.

### Steps to Reproduce the Issue
1. In a Windows .cmd file, select a block, right-click, select "block comment," and "REM " appears at the beginning of each line.  
2. Select the same block, right-click, select "block uncomment," nothing happens.

### Expected Behavior
"REM " added to the benginning of each line.

### Actual Behavior
Nothing

### Debug Information
Notepad++ v7.1   (32-bit)
Build time : Oct 15 2016 - 23:30:30
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10
Plugins : mimeTools.dll NppConverter.dll NppExport.dll PluginManager.dll SpellChecker.dll

**Comment by jimshilliday** [comment]
Expected Behavior should have been "REM " removed from, not added to, beginning of line.

**Comment by redmanmale** [comment]
Only `Block Uncomment` doesn't work, all other (un)comment operations work just fine.
