### ISSUE TITLE
Some suggestions that would be very convenient.

### ISSUE THREAD

**Issue by jginfo** [notepad-plus-plus/notepad-plus-plus#2855]
Hello

Some suggestions that would be very convenient.

1) Horizontal scrolling of top Files tabs with thumbwheel (when the mouse pointer hovers over the Top Files tabs)
2) pop-up confirmation 'yes/no' for the option 'Close All BUT This' (when you right click on Top Files tab)

3) pop-up confirmation 'yes/no' for button 'Replace All in All Opened Documents' (in the pop-up 'Replace')

4)  in the pop-up 'Find' tab 'Mark'
make 2 buttons instead of the 'Clear' button
- button 'Clear Text' purging the marks in the text alone (NOT in the column of line numbers)
- button 'Clear Line' purging the marks in the column of line numbers

personally, I prefer the marking options in the 'Find' tab ... (As it was a time!)

I am French and below the French version
----------------------------------------------------
Quelques suggestions qui seraient bien pratique.

1) Pouvoir scroller horizontal les onglets des fichiers avec la molette (lorsque le pointeur de la souris survol les onglets des fichiers)
2) pop-up de confirmation 'oui/non' pour l'option 'fermer tout sauf ce fichier' (lorsque l'on click droit sur un onglet de fichier)

3) pop-up de confirmation 'oui/non' pour le bouton 'Remplacer dans tous les documents ouverts'
4) Dans la popup 'Cherche' onglet 'Marquer'
faire 2 boutons au lieu du seul bouton 'Purger'
- bouton 'Purge Texte' purgeant les marques dans le texte seul (PAS dans la colonne des n° de lignes)
- bouton 'Purge Lignes' purgeant les marques dans la colonne des n° de lignes

perso, je préférais les options de marquage dans l'onglet rechercher... (comme il fut un temps)

**Comment by MetaChuh** [comment]
please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins if you update from version 7.5.9 or below.
if your issue still persists, and it is still of relevance, please feel free to file a new issue as easy to understand and reproducible as possible.

thank you for your help and best regards.

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
(no extra account is needed, just use your github account to sign in)
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)
