### ISSUE TITLE
_isNoSession should always be set to true for instances after the first, irrespective of _multiInstSetting

### ISSUE THREAD

**Issue by Gabr-F** [notepad-plus-plus/notepad-plus-plus#2856]
Currently (v7.3.1) in WinMain cmdLineParams._isNoSession is always set to true if this is not the first instance (`TheFirstOne`) **only** `if (nppGUI._multiInstSetting == multiInst)`.

This doesn't seem to make sense, until session.xml correctly supports multiple instances (by saving all of them separately) the "rememberLastSession" thing should always be disabled for instances after the first.

I remind that using multiple instances with auto-backup enabled can easily result in the loss of files (e.g. #819).

#819 could probably be closed once this is fixed, although it would be much better to solve it by really supporting multiple instances in session.xml.

---

By the way, it's not very clean to override from the code CmdLineParams members, it results in some confusion: they are not really the "Command line params" (the parameters passed on the command line) anymore.

**Comment by Gabr-F** [comment]
<span id="x">xxx</span>

**Comment by donho** [comment]
It doesn't make sense to me that you say some code doesn't make sense.
It does make sense that you describe the bug behaviour and what you expect, then why not a PR of bug-fix.
But before that, your bug issue is not valid and neither your PR.
