### ISSUE TITLE
Plugin manager prints "destructing 4" to console

### ISSUE THREAD

**Issue by Pokechu22** [notepad-plus-plus/notepad-plus-plus#2859]
I'm creating this issue mostly for searchability purposes, as the actual issue is at bruderstein/nppPluginManager#34.  However, given that that repo is much smaller (and that plugin manager issues are within the scope of this tracker), it seems worthwhile to provide a link to that issue.  Here's a quote:

> ### Description of the Issue
> When closing the plugin manager, the following is printed to the console:
> 
> > ```
> > destructing 4
> > destructing 3
> > destructing 4
> > destructing 3
> > destructing 2
> > destructing 1
> > ```
> 
> These messages should not be printed, since they seem to be a leftover debug string and have no actual relevance to the user (although, the fact that `destructing 4` is printed twice is a bit worrisome).
> 
> ### Steps to Reproduce the Issue
> 
> 1. Start Notepad++ with a console attached.
>     
>     This is _probably_ the most difficult step.  The majority of the time, the console refuses to appear or to stay open.  However, it _does_ open when Notepad++ is launched through [Cygwin](http://cygwin.com/), such as [for use as a git commit message editor](http://stackoverflow.com/a/1635493/3991344).  No special flags are _actually_ needed; simply running `notepad++.exe` from bash makes it visible.
> 
>     Alternatively, if Cygwin is not an option, simply adding a call to `AllocConsole()` is enough to get the console to appear when debugging from visual studio.  Of course, in this situation, the console has to manually be opened; you wouldn't run into the issue that way from normal usage.
> 2. Open the plugin manager.
> 3. Close Notepad++ (Cygwin only &mdash; seems to be necessary to get the output to be flushed)
> 
> ### Expected Behavior
> 
> The console to remain blank.
> 
> ### Actual Behavior
> 
> The following is printed to the console:
> 
> > ```
> > destructing 4
> > destructing 3
> > destructing 4
> > destructing 3
> > destructing 2
> > destructing 1
> > ```
> 
> ### Debug Information
> 
> 
> <h4>Regular install</h4>
> 
> ```Notepad++ v7.2.2   (32-bit)
> Build time : Nov 27 2016 - 16:31:07
> Path : C:\Users\Pokechu22\Downloads\notepad++\notepad++.exe
> Admin mode : OFF
> Local Conf mode : OFF
> OS : Windows 10
> Plugins : DSpellCheck.dll mimeTools.dll NppConverter.dll NppExport.dll NppFTP.dll PluginManager.dll
> ```
> 
> <h4>From visual studio</h4>
> 
> ```Notepad++ v7.3.1   (32-bit)
> Build time : Jan 31 2017 - 21:46:54
> Path : C:\Users\Pokechu22\Downloads\notepad-plus-plus\PowerEditor\visual.net\Unicode Debug\Notepad++.exe
> Admin mode : OFF
> Local Conf mode : OFF
> OS : Windows 10
> Plugins : DSpellCheck.dll mimeTools.dll NppConverter.dll NppExport.dll NppFTP.dll PluginManager.dll
> ```
> 
> ### Cause
> 
> [Line 31 of `CancelToken.cpp`](https://github.com/bruderstein/nppPluginManager/blob/886e4fc2a4f0a157eaf0378da1f9301b320d0cdd/libinstall/src/CancelToken.cpp#L31) contains:
> 
> ```cpp
> printf("destructing %d\n", *m_refCount);
> ```
> 
> Removing that line should fix the issue.

**Comment by dail8859** [comment]
For such an incredibly minor issue this is best kept to the PluginManager repository.
