### ISSUE TITLE
Cannot setting global styles font to non-ASCII name of font since v6.7.9 

### ISSUE THREAD

**Issue by phasis68** [notepad-plus-plus/notepad-plus-plus#286]
I cannot set global styles font to the font which name is non-ASCII  since v6.7.9 

If the font name is "Courier New" or  "Times New Roman", the font style is changed.
But,  when I choose  "바탕체" or  "나눔고딕코딩", the font style is not changed.

v6.7.8.2 works fine.

**Comment by donho** [comment]
Update your Notepad++ to v7.6.6.
If this bug persists in the new release, please open a new issue with the debug information.
