### ISSUE TITLE
Cannot install XML Tool plugin 2.4.8 in Notepad v7.2.2 32 bit

### ISSUE THREAD

**Issue by ppeikelboom** [notepad-plus-plus/notepad-plus-plus#2860]
### Description of the Issue

Cannot install XML Tool plugin 2.4.8 in Notepad v7.2.2  32 bit
Previous XML Tool versions could be installed and worked OK
Windows 7 64 bit.

### Steps to Reproduce the Issue

1. After fresh install of XML Tool plugin in  Notepad++ it occurs.
2. After an update of XML Tool plugin to new version it occurs as well.
3. Other plugin could be installed without issue (e.g Compare)
4. 

### Expected Behavior

I would expect that XML Tool plugin could be installed as usual.

### Actual Behavior

I got an error message: "Installation of XML Tools failed"

### Debug Information

Notepad++ v7.2.2   (32-bit)
Build time : Nov 27 2016 - 16:31:07
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 7
Plugins : ComparePlugin.dll mimeTools.dll NppConverter.dll NppExport.dll PluginManager.dll sql.dll 

Tried to download the plugin from https://sourceforge.net/projects/npppluginmgr/files/v1.3.5/
But that does not work, it gives below error message:

Secure Connection Failed
An error occurred during a connection to downloads.sourceforge.net. SSL received a record that exceeded the maximum permissible length. Error code: SSL_ERROR_RX_RECORD_TOO_LONG
The page you are trying to view cannot be shown because the authenticity of the received data could not be verified.
Please contact the website owners to inform them of this problem.

**Comment by dail8859** [comment]
If this still isn't working it needs reported to the author of XML tools or the PluginManager.

**Comment by ppeikelboom** [comment]
It seems related to the server used at work.
From home I can install without issues.

But from at work I cannot, with an error message about SSL certificate.
I asked our IT dept to investigate.


2017-02-05 17:54 GMT+01:00 dail8859 <notifications@github.com>:
