### ISSUE TITLE
[7.3.1] 'Use new style save dialog' re-enables itself after restarting Notepad++

### ISSUE THREAD

**Issue by Keith94** [notepad-plus-plus/notepad-plus-plus#2863]
### Description of the Issue

'Use new style save dialog' re-enables itself after restarting Notepad++ 7.3.1. It works as expected in 7.3.

### Steps to Reproduce the Issue

1. Open Preferences >> Default Directory
2. Disable 'Use new style save dialog'
3. Close and re-open Notepad++
4. Save a new document

### Expected Behavior

Default file extension should be "txt" rather than blank

### Actual Behavior

Default file extension is blank (shows as All Types ".")

**Comment by MAPJe71** [comment]
Duplicate of #2814

Fixed by 1a0e6d7

This will be in the next release.

**Comment by Keith94** [comment]
Thanks @MAPJe71
