### ISSUE TITLE
Port to Universal Windows Platform

### ISSUE THREAD

**Issue by msfcolombo** [notepad-plus-plus/notepad-plus-plus#2864]
Please consider porting NPP to [UWP desktop device family](https://msdn.microsoft.com/en-us/windows/uwp/get-started/universal-application-platform-guide). This gives you the following benefits:

- You don't have to build and ship two editions (one for 32-bit, other for 64-bit).
- The above also applies to plugin developers, an important source of value in the NPP ecosystem.
- It will be easier to distribute your app in Windows Store and more people will see the glorious ratings and epic number of downloads.

I'm asking this because I like NPP 64-bit (mostly due to more stable Explorer integration) but cannot use it because my favorite plugins are not there.

**Comment by quantuumsnot** [comment]
+1, no plugins no fun :(

**Comment by bviktor** [comment]
-1 I can't see how porting ALL plugins AND Notepad++ to UWP is simpler than porting just the plugins to 64 bit. In most cases it should be trivial to patch anyway (unlike a Win32 to UWP conversion which is basically a rewrite).

**Comment by msfcolombo** [comment]
@bviktor  With all ported to UWP you don't need two builds (32 & 64) anymore. NP++ would always integrate well with Windows, no matter if it's 32 or 64 bit edition. That's the benefit.

If you have two builds, force every plugin dev to have two builds as well.

I'm not sure if porting to UWS is really a rewrite. Looks like [somebody started the work](https://github.com/UWP-Open-Source-Community/NotepadPlusPlus) and is [looking for permission to publish](https://github.com/notepad-plus-plus/notepad-plus-plus/issues/3196).

**Comment by donho** [comment]
FYI: This task was in progress but it has been blocked, here is the further information:
https://notepad-plus-plus.org/community/topic/14734/notepad-uwp-package-in-windows-store-almost-there

Any idea is welcome.

**Comment by MetaChuh** [comment]
the work on uwp has been dropped completely for the moment, due to its complexity and known issues currently arising with the existing, unofficial uwp ports.

note: work on uwp might get resumed some day, but for now it produces more problems than what it's worth.

many thanks for your understanding and best regards.
