### ISSUE TITLE
High CPU usage when using the scrollbars

### ISSUE THREAD

**Issue by quantuumsnot** [notepad-plus-plus/notepad-plus-plus#2869]
### Description of the Issue
While using the scrollbars in the editor, the CPU almost reaches 80% load (Intel i7)

### Steps to Reproduce the Issue
1. Write or open some code with many and long lines (but it happens on 600-700 LoC with largest line ~270 chars)

### Expected Behavior
1. No stuttering when using the scrollbars

### Actual Behavior
1. The whole system hiccups

### Debug Information
Notepad++ v7.3.1   (64-bit)
Build time : Jan 17 2017 - 00:28:43
Path : C:\npp\notepad++.exe
Admin mode : ON
Local Conf mode : ON
OS : Windows 7
Plugins : mimeTools.dll NppConverter.dll

**Comment by chcg** [comment]
On which type of file do you see it? 
cpp, xml, html, etc. or does it happen independent of the file type?
How much of the 80% cpu load is caused by n++?

**Comment by quantuumsnot** [comment]
Seen on .js and .php, around 70%

**Comment by quantuumsnot** [comment]
I'm considering that this issue is gone too hense closing it, the load now is around 15% when crazy scrolling (on the same machine/CPU) ~1200 LoC .js file
