### ISSUE TITLE
Per Monitor DPI Awareness support

### ISSUE THREAD

**Issue by M-Jup** [notepad-plus-plus/notepad-plus-plus#2871]
Notepad++ is currently only System DPI Aware, it should be also Per Monitor DPI aware.

My laptop screen and external monitors use different scaling. Notepad++ is blurry unless I sign out/sign in after docking/undocking. It's very annoying to do this...

For more information, please see this link: https://blogs.windows.com/buildingapps/2016/10/24/high-dpi-scaling-improvements-for-desktop-applications-and-mixed-mode-dpi-scaling-in-the-windows-10-anniversary-update/

**Comment by ouned** [comment]
Here are some tests i made recently: https://github.com/ouned/notepad-plus-plus/tree/pm-scaling

**Comment by h-h-h-h** [comment]
Important quote from linked article:

> Some applications would register themselves as being Per-Monitor-DPI Aware not because they actually were DPI aware, but because they didn’t want Windows to bitmap stretch them.
>
> These problems resulted in very few applications handling dynamic display scaling correctly. Many applications that registered themselves as being Per-Monitor-DPI Aware don’t scale at all and can render extremely large or extremely small on secondary displays.

**Comment by M-Jup** [comment]
@ouned Any news finishing the work? Thanks!

**Comment by ouned** [comment]
i didn't continue working on it because the win10 creators update basically fixes the problem by some kind of magic.
Just set DPI Scaling to System (Extended) in compatibility settings.
It's not perfect but very close.

**Comment by magixyu** [comment]
@ouned 
I have the issue to use the notepad++ in win10, my laptop monitor is HiDPI(1920x1080) and second monitor(extend Monitor) is Dell P2417H. The notepad++ is blurry on my second monitor. I checked that notepad++ is system aware of DPI. Can Notepad++ support "Per-monitor DPI"? 

Thanks,
Tristan

**Comment by ouned** [comment]
Try setting DPI Scaling options to "System (Extended)"

Like I said, it's not as perfect as it would be when actually wrote to support per-monitor scaling, but it's close.

**Comment by egwhoi** [comment]
I agree that this setting makes it look pretty good, at least in my case (I'm using integer scaling... 100% on one monitor and 200% on another, which is kind to the new GDI scaling).

Can we modify notepad++.exe.manifest so that this behavior is enabled by default?  I think this is what needs to be added inside the <assembly> tags:
<asmv3:application>
    <asmv3:windowsSettings xmlns="http://schemas.microsoft.com/SMI/2017/WindowsSettings">
      <gdiScaling>true</gdiScaling>
    </asmv3:windowsSettings>
  </asmv3:application>

(From https://blogs.windows.com/buildingapps/2017/05/19/improving-high-dpi-experience-gdi-based-desktop-apps/)

**Comment by magixyu** [comment]
@ouned 
Thanks for the information. It helps but it doesn't resove my issue. Any plan for resolve it by introduce the HDPI in notepad++?

Thanks,
Tristan

**Comment by magixyu** [comment]
I meant, I'd like to have more lines in the extended monitor, not just make it bigger:)

**Comment by iltar** [comment]
I have one monitor on 100% (primary) and my secondary at 125% (secondary). The font is extremely blurry on my secondary screen. Disabling the scaling makes it too small to read (full hd on 15")

**Comment by matthewpetch** [comment]
Exact same issue as @linaori 

I have a lapotop connected to 2 external monitors. All 3 screens are 1920x1080, but Windows scaling is set to 125% on the laptop screen (as it's smaller). Text is very blurry on the 2 external monitors, set to 100%

**Comment by MetaChuh** [comment]
i can not reproduce blurriness on notepad++ 7.6.6 on windows 10 build 1809 on multiple displays using different scaling factor combinations.

please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins if you update from version 7.5.9 or below.

note: also try to disable smooth font, by going to `settings > preferences > editing` and unchecking `enable smooth font` in notepad++, if it is enabled as seen at the screenshot below.

![Imgur](https://i.imgur.com/vFFvIOR.png)

if your blurriness persists, please right click on your notepad++ icon and select `properties > compatibility > change high dpi settings`, activate `override high dpi scaling behavior` and set `scaling performed by:` to `system (enhanced)`, as seen at the screenshot below.

![Imgur](https://i.imgur.com/qVQ4Bg8.png)

note: you can also choose the `system` scaler, for a classic notepad++ look on scaled displays, which will look like this:

![Imgur](https://i.imgur.com/WqSSpUo.png)

thank you for your help and best regards.

-----
```
general notes:

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
(no extra account is needed, just use your github account to sign in)
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)

**Comment by luigip** [comment]
Sorry you can't reproduce the issue, but it's definitely still there. I've made a picture to illustrate:
![notepad scaling](https://user-images.githubusercontent.com/1264679/57264406-911d3c00-7069-11e9-83b5-6307be88512b.PNG)

You might need to download this image and view it in Paint on your primary monitor, or adjust your browser zoom to see it at 1:1 pixels (which is important, obviously). The top left, middle right, and bottom right are sharp. The others aren't. "System (enhanced)" is best overall, but on the primary it is not as sharp as with override turned off.

I suggest this issue should be re-opened.

**Comment by luigip** [comment]
At 500% magnification the issue is clearer. The images below are just magnifications of the above from my Primary at 125%, with no override:
![Capture2](https://user-images.githubusercontent.com/1264679/57528106-4df0f080-7329-11e9-9452-8a1ae3aa7536.PNG)

and with System (enhanced) override:
![Capture](https://user-images.githubusercontent.com/1264679/57528125-5e08d000-7329-11e9-8f14-421d1fd55015.PNG)

**Comment by gaspardle** [comment]
I think this issue should be reopened, I have the same issue occuring, one monitor scaled at 175% and another at 100% and if I move the app to the other monitor, the text is blurry.

I recently had to deal with updating an app to be per-monitor aware in Windows 10.

Here are the basic steps I did:

Handle the WM_DPICHANGED message
 - resize the window to the suggested size received in lParam.
 - relayout the controls / font size in the window

Use the new dpi aware api (if they are available, only windows 10+) 
 - Change calls from GetDeviceCaps to GetDpiForWindow
 - GetSystemMetrics  -> GetSystemMetricsForDpi
 - (etc...)

Modify the application manifest to add: 

 - `<dpiAwareness xmlns="http://schemas.microsoft.com/SMI/2016/WindowsSettings">PerMonitorV2, System</dpiAwareness>`
 or
 - `<dpiAwareness xmlns="http://schemas.microsoft.com/SMI/2016/WindowsSettings">PerMonitorV2</dpiAwareness>`
 
 
More information is available here: https://docs.microsoft.com/en-us/windows/desktop/hidpi/high-dpi-desktop-application-development-on-windows

I'm not familiar enough with the code to send a pull request but it should help make the text sharp on any monitor.

**Comment by dmarlow** [comment]
Is it a known issue that the cursor position is broken when zoomed in to the text within NPP? Seems to jump around as well.

**Comment by adanski** [comment]
I can still reproduce the bug.

**Comment by matthewpetch** [comment]
> I can still reproduce the bug.

don't be silly, it's labeled as not reproducible despite clear instructions

**Comment by episource** [comment]
Sadly using DPI scaling mode "System (Enhanced)" does not work 100% perfect with two monitors having different scaling. Yes, the text is crisp on both monitors, as it should be, but special markup like url highlighting and text selection doesn't work properly:

 - This is a screenshot of an url without mouse hovering (looks as it should)
![grafik](https://user-images.githubusercontent.com/3219567/69006540-9fa9b180-0930-11ea-8223-84c106450d7b.png)
- This is the same url with mouse hovering (look at the underline)
![grafik](https://user-images.githubusercontent.com/3219567/69006547-af28fa80-0930-11ea-8bac-f6436ae66c92.png)
- And this is, how it looks when i add a quote at the end and hover over the url
![grafik](https://user-images.githubusercontent.com/3219567/69006555-cbc53280-0930-11ea-80d5-625a288f424e.png)
- Also text selection does not work properly; in the screenshot the whole word "distributed" is selected 
![grafik](https://user-images.githubusercontent.com/3219567/69006568-029b4880-0931-11ea-8d96-b907dc18fc2d.png)

I'm using version 7.8.1. Without rendering mode "System (enhanced)" the artifacts depicted above go away, but the text is blurry on the screen that is not main screen.

**Comment by ak1001uanic** [comment]
Notepad v 7.8.6
Main monitor: 2560x1440, font scaling 125% - sharp
Secondary : 1920x1080, font scaling 100% - blurry

Set override high dpi scaling behavior to SYSTEM
Main monitor:  ok, but not sharp
Secondary : ok

**Comment by unit-a-user** [comment]
Currently `System (Enhanced)` has pixelated quality.
