### ISSUE TITLE
[Enhancement] "Folder as workspace" follows edited file

### ISSUE THREAD

**Issue by sgallou** [notepad-plus-plus/notepad-plus-plus#2877]
Hi,

I post here after discussion with Claudia [from here](https://notepad-plus-plus.org/community/topic/13221/new-function-wish-folder-as-workspace-follows-edited-file).

### Expected Behavior
It will be nice that the edited file would be highlighted in the "folder as a workspace" view.
In other words : when switching from files (clic on tabs), the "folder as a workspace" view scrolls if necessary, and highlights the selected file.

This function should be disable-able by a configuration option.

working on a big project, the tree displayed in the FAWW (folder as workspace window) is big, all files/subDirs can not be displayed on a single page. When I’m working on a file (maybe not open by a clic on the FAWW, but for example by a drag-and-drop from explorer), I often need to access quickly to a sibling of this file (a file in the same directory).
MS Visual Studio has this function, automatically as an option, or manually with a button representing 2 horizontal arrows in the solution explorer window toolbar. Android Studio too, called “autoscroll from source” option. I found these options useful.

**Comment by jeffjensen** [comment]
Yes, this is a helpful feature.  I am regularly editing a file and navigating to its location to open another file in the same location.

**Comment by donho** [comment]
The following implementation is not what you want exactly, but it get job done:
https://github.com/notepad-plus-plus/notepad-plus-plus/commit/bc2b5ac2ce47ed8821525c534d16c19b5f239f1d

It'll be in v7.8.3 which will come out soon.
