### ISSUE TITLE
Editing \r\n in Extended Mode -- Regression

### ISSUE THREAD

**Issue by sujennings** [notepad-plus-plus/notepad-plus-plus#2879]
### Description of the Issue
I have been able to remove carriage return and new line characters from my XML document without any problems as long Extended Search Mode was selected.   I can no longer do so.  I receive the message "Find:  Can't find the text "\r\n" ".  

### Steps to Reproduce the Issue

1. Type in \r\n in the Find What: field. 
2. Select Extended search mode
3. Select Find Next button

### Expected Behavior
Find the next \r\n in the document.  There are more than 1 of course.

### Actual Behavior
Receive the message Find:  Can't find the text "\r"

### Debug Information
------------------------------------------
Notepad++ v7.2.2   (32-bit)
Build time : Nov 27 2016 - 16:31:07
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : ON
Local Conf mode : OFF
OS : Windows 7
Plugins : JSMinNPP.dll mimeTools.dll NppConverter.dll NppExport.dll NPPJSONViewer.dll NppTextFX.dll PluginManager.dll PoorMansTSqlFormatterNppPlugin.dll sql.dll sqlFormat.dll XMLTools.dll 
------------------------------------
Image.  The first line contains the string I am trying to search.  The cursor is on the first character in the line.

![image](https://cloud.githubusercontent.com/assets/3893117/22695011/40e4152e-ed17-11e6-8a9b-5743154adb49.png)

**Comment by dail8859** [comment]
The image you have shown does not contain newline characters. When you see "\r\n" in your text this is 4 characters. When you search for "\r\n" in extended mode you are searching for 2 characters. You need to switch to "Normal" search mode.
