### ISSUE TITLE
Fail colors because a "harmful quot"

### ISSUE THREAD

**Issue by alfroc** [notepad-plus-plus/notepad-plus-plus#288]
Look at image, please.
This bug appears in release 6.7.9 and persist.
![fallonp](https://cloud.githubusercontent.com/assets/12998380/8280608/2f61ccbe-18df-11e5-982d-ff3056b98e4e.png)

**Comment by Gheoan** [comment]
Easyest way to repdroduce:
```html
<script type="text/javascript">
"
</script>

<html>
```
It also seems to break Github's syntax highlighting.

**Comment by Rikk** [comment]
Not sure it is wrong...
This symptom seems to be a good way to find errors in the code.

**Comment by alfroc** [comment]
Rikk, in previous versions (6.7.8.2 or olders) not show the problem.

**Comment by dail8859** [comment]
Not sure what has changed but at least it seems fine now...

![capture](https://cloud.githubusercontent.com/assets/3694843/16212143/cdc25934-3713-11e6-8a55-a760125e815d.PNG)
