### ISSUE TITLE
Imposter Android Apps a concern, thought you should know

### ISSUE THREAD

**Issue by galaara98** [notepad-plus-plus/notepad-plus-plus#2880]
### Steps to Reproduce the Issue

1. 
2. 
3.

**Comment by galaara98** [comment]
Umm I wrote a bunch of content into the report that I don't see?

**Comment by galaara98** [comment]
Well suffice it to say, your good name and logo are being abuse at Google Play store.

**Comment by redmanmale** [comment]
@galaara98 
Could you provide link to that blasphemous app?
Your report is blank now.

**Comment by galaara98** [comment]
https://play.google.com/store/apps/details?id=com.note.pad
 Is the most offensive to me

But
https://play.google.com/store/apps/details?id=notepadsandbox.bitbot.el
Is not innocent either

**Comment by dail8859** [comment]
AFAIK neither the Notepad++ logo or "Notepad++" itself is trademarked or copyrighted, so in theory they can use it. Though I agree it is slightly misleading, none are claiming to be this project. If you do find these projects misleading or misrepresenting then you can report them to the Google Play store.
