### ISSUE TITLE
Notepad++ crash nulled the file

### ISSUE THREAD

**Issue by Anapher** [notepad-plus-plus/notepad-plus-plus#2883]
Hello,
after saving my php file, Notepad++ crashed and cleared the file to a size of 0 bytes. I wasn't able to find any cache or backup for that file. I'm a developer, I save my code frequently, I never thought that an issue could exist in Notepad++ which just erases the whole file on my HDD without any backup... 2 hours of work were destroyed there.

Anyways, that happend on Ctrl+S after I inserted XAML code into an HTML code tag like that:
```html
				<code class="xaml">
				<UserControl x:Class="ExtensionSpoofer.UserControl2"
             xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
             xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
             xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006" 
             xmlns:d="http://schemas.microsoft.com/expression/blend/2008" 
             xmlns:local="clr-namespace:ExtensionSpoofer"
             mc:Ignorable="d" 
             d:DesignHeight="300" d:DesignWidth="300">
    <Grid>
            
    </Grid>
</UserControl></code>
```

Two entries are found in the event log:
```
Name der fehlerhaften Anwendung: notepad++.exe, Version: 7.3.1.0, Zeitstempel: 0x587d55bc
Name des fehlerhaften Moduls: notepad++.exe, Version: 7.3.1.0, Zeitstempel: 0x587d55bc
Ausnahmecode: 0xc0000409
Fehleroffset: 0x000f4fdc
ID des fehlerhaften Prozesses: 0x4368
Startzeit der fehlerhaften Anwendung: 0x01d281f49d0c0806
Pfad der fehlerhaften Anwendung: C:\Program Files (x86)\Notepad++\notepad++.exe
Pfad des fehlerhaften Moduls: C:\Program Files (x86)\Notepad++\notepad++.exe
Berichtskennung: 6306db71-e7b5-44fb-9ff9-3a05982bb2fd
Vollständiger Name des fehlerhaften Pakets: 
Anwendungs-ID, die relativ zum fehlerhaften Paket ist: 
```

```
Fehlerbucket , Typ 0
Ereignisname: BEX
Antwort: Nicht verfügbar
CAB-Datei-ID: 0

Problemsignatur:
P1: notepad++.exe
P2: 7.3.1.0
P3: 587d55bc
P4: notepad++.exe
P5: 7.3.1.0
P6: 587d55bc
P7: 000f4fdc
P8: c0000409
P9: 00000005
P10: 

Angefügte Dateien:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERA9F9.tmp.WERInternalMetadata.xml

Diese Dateien befinden sich möglicherweise hier:
C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_notepad++.exe_678526702bd53c93d433be4b1c4366dde435bac_93099a2e_0385b071

Analysesymbol: 
Es wird erneut nach einer Lösung gesucht: 0
Berichts-ID: 6306db71-e7b5-44fb-9ff9-3a05982bb2fd
Berichtstatus: 97
Bucket mit Hash: 
```

In my applications I had problems like that when an error occured when serializing: I opened a file stream which overwrites a file and tries to serialize objects from the memory, something goes wrong, the file will be 0 bytes long and the objects in memory lost. My solution was that the file is not removed but moved to file.xml.backup and just removed when the serialization was successful. Would you consider doing something like that too (because I think that the errors might be equal)?

**Comment by donho** [comment]
Sorry for the crash.
Could you provide Debug information via menu `?->Debug Info...` ?

**Comment by Alkalinee** [comment]
Here you go:
Notepad++ v7.3.1   (32-bit)
Build time : Jan 17 2017 - 00:21:10
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10
Plugins : JSMinNPP.dll mimeTools.dll NppConverter.dll NppExport.dll NppTextFX.dll NppToolBucket.dll PluginManager.dll

**Comment by chcg** [comment]
Error code is STATUS_STACK_BUFFER_OVERRUN (0xc0000409), see e.g. https://blogs.technet.microsoft.com/srd/2009/01/28/stack-overflow-stack-exhaustion-not-the-same-as-stack-buffer-overflow/

**Comment by EnoraNedelec** [comment]
A similar bug happened to me. 
I was working on a file and then something similar to a power cut happened. When I restarted my computer, the file was filled with NULL (I don't remember the size of the file after the power cut). I had many files open in Np++ but only the file I was working on (the active tab) was corrupted. I  looked into Np++ temp folder but my file wasn't there (there  were many other temp file) probably because my file was saved just before the power cut. I couldn't recover my file. 

This is similar to [this question on superuser.com](https://superuser.com/questions/377904/recover-file-corrupted-due-to-power-cut-off). 

Here are the debug info:
```
Notepad++ v7.5.1   (32-bit)
Build time : Aug 29 2017 - 02:35:41
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10 (64-bit)
Plugins : ComparePlugin.dll CustomizeToolbar.dll docMonitor.unicode.dll jN.dll JSMinNPP.dll mimeTools.dll NppConverter.dll NppExport.dll NppFTP.dll NPPJSONViewer-win32.dll NppTextFX.dll PluginManager.dll PyNPP.dll RunMe.dll 
```

**Comment by markcity** [comment]
I had a similar problem. I found the issue to be zero disk space on my PC.
I edited 2 files and they just seemed to be 0 size.
Fortunately I had a backup, however my thinking is that notepad++ could check for low disk space periodically and not commit unless there is 3 x the current file disk pace free to allow for backup, transfer etc.
I know its probably not good to be doing this, but I was editing a file directly off my web server via winSCP - anyone else done this? It's good, except when your file is nulled, then its nulled on the server too :-(  

Notepad++ v7.5.4   (32-bit)
Build time : Jan  1 2018 - 01:47:45
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10 (64-bit)
Plugins : DSpellCheck.dll mimeTools.dll NppConverter.dll NppExport.dll

**Comment by guusjans** [comment]
After a Notepad++ crash with nullified file(mostly after save the file), you can try to restart notepad++! by executing the .exe directly. It comes up with a message that 'another program changed your nullified file' and it will ask to reload the file. **DON't** reload (it is nullified in the original map) but after give your answer (DON't reload) Notepad++ comes up with the nullified file: magical is not? Somewhere in memory it is keep alive!!
Hopefully this saved other people some headaches!! It was for me.

**Comment by ClaudiaFrank** [comment]
@guusjans 
curious, how is your setting for settings->preferences->multi-instance?

**Comment by guusjans** [comment]
The default (as after first install): mono-instance (my install language is dutch, so i had some trouble to find the setting, in dutch it is something as: 'all files opening in the same window' )

**Comment by stantonium** [comment]
duplicate issue of 4346?
