### ISSUE TITLE
Will Squirrel Language get supported by Notepad++?

### ISSUE THREAD

**Issue by ifarbod** [notepad-plus-plus/notepad-plus-plus#289]
[Squirrel](http://squirrel-lang.org) is a scripting language which doesn't have an official editor, Is there a chance that it gets supported by N++?

**Comment by ifarbod** [comment]
Two days, still no answer?

**Comment by milipili** [comment]
You would prefer 2 weeks ? :) If you're talking about syntax highlighting, you can propose an User Defined Language file.

**Comment by ifarbod** [comment]
The User Defined Language messes up with the theme i currently using (Solarized)

**Comment by fetr0509** [comment]
I've created a User Defined Language file and sent it to the email provided on the Wiki's "User Defined Language page"

**Comment by fetr0509** [comment]
No one ever got back to me about adding the language file to the Wiki.

**Comment by SamuXarick** [comment]
I need this too.

**Comment by donho** [comment]
Notepad++ uses Scintilla component so if Squirrel lexer is supported by Scintilla, Notepad++ will include it.
Otherwise, you can use Notepad++'s User Defined Language System to build it.
