### ISSUE TITLE
Smart Highlighting: Other-View is highlighted regardless of Settings

### ISSUE THREAD

**Issue by Yaron10** [notepad-plus-plus/notepad-plus-plus#2892]
STR:
Preferences -> Highlighting -> Smart Highlighting.
Check "Enable".
Uncheck the the three following options and check "Highlight another view".
Uncheck "Enable".

![image](https://cloud.githubusercontent.com/assets/10229320/22811521/f4445c28-ef47-11e6-9faf-1783b8658283.png)

Close NPP.
Open NPP and create files Test1 and Test2.
Type "Test" in both files and save them.
Move Test1 to the other view.
Select "Test" in that file.
Close NPP.
Restart NPP.

Result:
(The session is restored).
"Test" in Test2 is highlighted (it's "sticky": you can only remove it by closing the file).
***
Notepad++ v7.3.1   (32-bit)
Build time : Jan 17 2017 - 00:21:10
Path : C:\Users\---\Downloads\npp.7.3.1.bin\notepad++.exe
Admin mode : ON
Local Conf mode : ON
OS : Windows 7
Plugins : ComparePlugin.dll mimeTools.dll NppConverter.dll NppExport.dll PluginManager.dll 

Thank you.

**Comment by MetaChuh** [comment]
please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins if you update from version 7.5.9 or below.
if your issue still persists, and it is still of relevance, please feel free to file a new issue as easy to understand and reproducible as possible.

thank you for your help and best regards.

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
(no extra account is needed, just use your github account to sign in)
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)
