### ISSUE TITLE
Language selection mark doesn't work

### ISSUE THREAD

**Issue by redmanmale** [notepad-plus-plus/notepad-plus-plus#2897]
After opening any existing file or creating new one and selecting language style is applied (highlighting) but in menu selection doesn't show up for all langs excluding C-group.

![pic](https://puu.sh/tXhxX/51ec8f4dc9.png)
![pic2](https://puu.sh/tXhIn/9b3c51ee4f.png)

Notepad++ v7.3.1   (32-bit)
Build time : Jan 17 2017 - 00:21:10
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 8.1 x64
Plugins : DSpellCheck2.dll mimeTools.dll NppConverter.dll NppExport.dll NppFTP.dll NPPJSONViewer.dll PluginManager.dll

**Comment by MAPJe71** [comment]
Duplicate of #1095, closed by [389524d](https://github.com/notepad-plus-plus/notepad-plus-plus/commit/389524d23067a89348bc6e88f88736a2e982acdb)

**Comment by redmanmale** [comment]
I knew there is issue about that! Forget that check sign/selection mark varity.
