### ISSUE TITLE
CDATA containing "<" not working correctly in XML syntax highlighting.

### ISSUE THREAD

**Issue by foobar13373** [notepad-plus-plus/notepad-plus-plus#2898]
### Description of the Issue
In XML files a CDATA tag messes up the syntax highlighting when CDATA content contains an unmatched "<". Using Notepad++ 64Bit 7.3.1 default installation (no external plugins).

### Steps to Reproduce the Issue

1. open a XML file with CDATA tag containing a "<" character

### Expected Behavior
CDATA content should not treated as XML data

### Actual Behavior
CDATA content ist treated as XML content (opening brackets "<" are treatd as new tags, CDATA closing is not recognized corectly)

**Comment by MAPJe71** [comment]
Could you include an example file? Thx

**Comment by foobar13373** [comment]
@MAPJe71 
```
<?xml version="1.0" encoding="UTF-8"?>
<example>
	<![CDATA[<?php]]>
	<foo/>
</example>
```

**Comment by MAPJe71** [comment]
Seems to be related to the `<?` character combination within the CDATA block.

**Comment by gersonvagner** [comment]
It will complete 10 (ten) years in the next month that the issue was raised and I continue to see the same problem here. See Scintilla bug report [1078](https://sourceforge.net/p/scintilla/bugs/1078/).

Reproduced with:
-Notepad++ v.7.5.1

**Comment by MetaChuh** [comment]
we can't fix it, if it isn't going to be fixed at scintilla.

our apologies and best regards.
