### ISSUE TITLE
Add ownCloud to cloud options (webdav)

### ISSUE THREAD

**Issue by rakekniven** [notepad-plus-plus/notepad-plus-plus#29]
Please add ownCloud to cloud options.
Would be perfect to have an open source cloud integration.
ownCloud uses webdav. So maybe other providers would be working too.

**Comment by rakekniven** [comment]
Cannot assign label "enhancement".

**Comment by Croydon** [comment]
This would be awesome :)

**Comment by milipili** [comment]
The feature has been simplified.
