### ISSUE TITLE
Instance highlighting should be case-sensitive

### ISSUE THREAD

**Issue by jabcreations** [notepad-plus-plus/notepad-plus-plus#2903]
### Description of the Issue
On occasion I come across instances where browser vendors initially release software with the incorrect letter casing on methods, properties, etc.

```
else if (document.webkitExitFullscreen)
{
 document.webkitExitFullscreen();
 console.log('webkit lowercase s');
}
else if (document.webkitExitFullScreen)
{
 document.webkitExitFullScreen();
 console.log('webkit UPPERCASE S');
}
```

Another [example of the importance of case sensitivity](http://stackoverflow.com/questions/30272619/javascript-readasdataurl-is-not-a-function/30272620). A lot of us developers will work past our optimal processing time and overlook things such as case-sensitivity without knowing.

Double-clicking on one or the other highlights all instances even though the have different case-sensitivity.

I do think it would be desirable to allow users to have a choice as to highlight with or without case-sensitivity though it should be case-sensitive by default.

### Debug Information
Notepad++ v7.2.2   (32-bit)
Build time : Nov 27 2016 - 16:31:07
Path : C:\MEDIA\OFFICE\Notepad++\notepad++.exe
Admin mode : ON
Local Conf mode : OFF
OS : Windows 7 x64
Plugins : mimeTools.dll NppConverter.dll NppExport.dll PluginManager.dll

**Comment by dail8859** [comment]
`Settings > Preferences > Highlighting > Smart Highlighting > Match Case`

**Comment by jabcreations** [comment]
You guys just naturally rock. Thank you!
