### ISSUE TITLE
File name issue with 

### ISSUE THREAD

**Issue by benoitcoppens** [notepad-plus-plus/notepad-plus-plus#2904]
### Description of the Issue
When file name contains some non latin characters, the filename is correct in the tab but not in the window header

### Steps to Reproduce the Issue
1. Create a new text file - enter any content
2. Save the file as その他の用法については.txt
3. In the tab, under the icons, the filename is correctly displayed
4. In the window header, the filename appears as ???????????.txt

### Expected Behavior
The filename is correctly displayed in the window header

### Actual Behavior
Some characters are replaced by question marks (?)

### Debug Information
Notepad++ v7.3.2   (32-bit)
Build time : Feb 12 2017 - 23:15:39
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10 (64-bit)
Plugins : HexEditor.dll mimeTools.dll NppConverter.dll NppExport.dll NppTextFX.dll PluginManager.dll XMLTools.dll XPatherizerNPP.dll 
<img width="320" alt="2017-02-14_16-30-14" src="https://cloud.githubusercontent.com/assets/25772701/22935524/1ed41508-f2d3-11e6-9bb7-6067e2bcff4a.png">

**Comment by SinghRajenM** [comment]
Could not reproduce. Is there any specific scenario to reproduce the issue? 
Try without any plugin, you can just rename "C:\Program Files (x86)\Notepad++\plugins" and relaunch NPP.

![image](https://cloud.githubusercontent.com/assets/14791461/22942411/79e6348a-f30f-11e6-95aa-dcfb152e3757.png)


Notepad++ v7.3.2   (32-bit)
Build time : Feb 12 2017 - 23:15:39
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10 (64-bit)
Plugins : DSpellCheck2.dll mimeTools.dll NppConverter.dll NppExport.dll PluginManager.dll

**Comment by benoitcoppens** [comment]
I found the "guilty" plugin : TextFX
Can you reproduce with it?

**Comment by SinghRajenM** [comment]
Yes, with TextFX it can be reproduced. I feel there should be some setting to handle.
Anyway, plugin related issue should be reported to respective plugin.

**Comment by benoitcoppens** [comment]
Thanks - Not a Notepad++ issue but a TextFX plugin issue - Ticket can be closed
