### ISSUE TITLE
Looking For SMART Cursor Movement (ala TextPad)

### ISSUE THREAD

**Issue by TroglodyteGuy** [notepad-plus-plus/notepad-plus-plus#2906]
### Steps to Reproduce the Issue / Display Behavior:
I have been a long-time user of TextPad till recently. I'm just getting started using Notepad++., and I find that I am really liking Notepad++. However I find that I am missing a feature or 2 from TextPad that I really rely on when updating scripts and other files - something that I havne't seen anywhere else. It's the way cursor movement is handled when switching lines. It's a bit hard to describe, but it is very handy! I'll try to describe it below, but it's probably easier if you follow along by trying firsthand. You can do this by downloading Textpad (e.g. any version from textpad.com).

For example, say I have the following two lines, with the cursor positioned at the pipe:

  The quick | fox jumped
  over the lazy dog.

...and then I typed "brown", the cursor would end up here:

  The quick brown| fox jumped
  over the lazy dog.

...in most editors (including Notepad++), if I then pressed the down arrow, I'd wind up with this:

  The quick brown fox jumped
  over the lazy d|og.

However, TextPad ends up with this:

  The quick brown fox jumped
  over the l|azy dog.

This comes in very handy when doing multiple similar edits across multiple lines.

It seems the editor is keeping track of both the cursor's "current X position" and the "base X position", which is "the original X position before any editing occurred since the last horizontal cursor navigation command". Then, if you move the cursor up or down (with either up/down arrows, or pgup/pgdn), the cursor tries to keep as close to the original X position as possible, but within the current line's constraints. The base X position is updated next time you manually position the cursor horizontally (e.g. left/right arrows, mouse click, etc).

It's hard to appreciate the above cursor feature without trying TextPad. And it'd be awesome to see this feature added to what already looks to be a great editor. Or maybe added as a new Plugin?

One other feature I miss, though it's much less important to me, is the elimination of extra spaces when breaking a line by adding a CRLF to create a second line of text. For example, say I have the following line, with the cursor positioned at the pipe:

  The quick brown fox jumped| over the lazy dog.

...in most editors (including Notepad++), when I press the <RETURN> key, I'd wind up with this:

  The quick brown fox jumped
  | over the lazy dog.

...You'll notice a space at the beginning of line 2 (above). However, with TextPad, the extra space at the beginning of line 2 is removed like this:

  The quick brown fox jumped
  |over the lazy dog.

### Follow-up Comment
Maybe I've grown so accustomed to this behavior, but I'm wondering if it's also possible in Notepad++?

**Comment by MetaChuh** [comment]
please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins if you update from version 7.5.9 or below.
if your issue still persists, and it is still of relevance, please feel free to file a new issue as easy to understand and reproducible as possible.

thank you for your help and best regards.

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
(no extra account is needed, just use your github account to sign in)
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)
