### ISSUE TITLE
Enhancement - Add option within view to include timestamp for every line.

### ISSUE THREAD

**Issue by leftreal** [notepad-plus-plus/notepad-plus-plus#291]
Add option within view to include timestamp for every line.

Example: 
In a situation, when you create new lines within a document, have a timestamp with date/time every time you hit enter.

This can help you separate where you left off in a document as far as date/time.

Thanks,
Leftreal

**Comment by MattTheGeek** [comment]
So essentially, something like this?
```
My big text document

Notepad++ is so [Last Edit: 06/23/2015 02:13:30AM]
```
Or are you talking about storing the date and time when *each* line was modified, in some kind of database?

**Comment by milipili** [comment]
Maybe a mockup of your idea would help indeed.

**Comment by leftreal** [comment]
Something like this...

**Comment by leftreal** [comment]
Something like this:

**Comment by MetaChuh** [comment]
closed due to inactivity (3y)
