### ISSUE TITLE
SHIFT+TAB in a big Xml

### ISSUE THREAD

**Issue by samuelfac** [notepad-plus-plus/notepad-plus-plus#2914]
### Description of the Issue
Open a large formatted XML and press CTRL+A, after SHIFT + TAB to remove the spaces at the beginning of the line, from a point in the file some special characters are inserted into the file, and when you try to undo these characters do not disappear.

### Steps to Reproduce the Issue
1-Opened a large formatted XML (about 1Mb);
2-Press CTRL+A to select all
3-Press SHIFT+TAB repeatedly to remove the all spaces at the beginning of the line;
4-Check in the middle or end of the file if special characters appeared that were not in the original XML.

### Expected Behavior
Just remove the spaces before each line without adding special characters

### Debug Information
Notepad++ v7.3.2   (32-bit)
Build time : Feb 12 2017 - 23:15:39
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10 (64-bit)
Plugins : mimeTools.dll NppConverter.dll NppExport.dll PluginManager.dll

**Comment by dail8859** [comment]
Try turning off `Settings > Preferences > Backup > Enable session snapshot and periodic backups`

**Comment by samuelfac** [comment]
@dail8859 It's works!
