### ISSUE TITLE
Update Notepad++ never works

### ISSUE THREAD

**Issue by sickmetal** [notepad-plus-plus/notepad-plus-plus#2915]
### Description of the Issue
For years now, every time there's an update and I click Update, the app says that there's no update. I've got a screenshot of the showing this issue. I was on the previous version and manually updated to the current version.

### Steps to Reproduce the Issue

1.  Start Notepad++
2.  Click Help - Update

### Expected Behavior
The app asks if I want to download the latest version.

### Actual Behavior
The app says "No update is available"

### Debug Information
Notepad++ v7.3.2   (64-bit)
Build time : Feb 12 2017 - 23:17:55
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10 (64-bit)
Plugins : mimeTools.dll NppConverter.dll 

![notepad 1](https://cloud.githubusercontent.com/assets/25830050/23040531/813ec7e6-f446-11e6-9d5c-79d44a0d34ec.PNG)
![Uploading Notepad 1.PNG…]()

**Comment by dail8859** [comment]
New releases are not immediately available through the automatic update system. It normally takes a few days or longer depending on how stable the new release is. 

For example if you install an older version like v7.0 it will find a newer version (though not necessarily the newest on the website).
