### ISSUE TITLE
Add the jump list capability

### ISSUE THREAD

**Issue by sickmetal** [notepad-plus-plus/notepad-plus-plus#2916]
### Description of the Issue
Plz add the jump list capability so I can right-click on the pinned app and select previously opened files.

### Steps to Reproduce the Issue

1. 
2. 
3.

**Comment by MAPJe71** [comment]
There is a plugin [NppJumpList](http://sourceforge.net/projects/nppjumplist/) available in the PluginManager.

**Comment by MetaChuh** [comment]
please either use the windows 10 native jumplist or the jumplist plugin.

thank you for your help and best regards.

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
(no extra account is needed, just use your github account to sign in)
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)
