### ISSUE TITLE
Install package don't recognize the /D switch in 32bits

### ISSUE THREAD

**Issue by jucabr2002** [notepad-plus-plus/notepad-plus-plus#2917]
### Description of the Issue:
       The installer package "npp.7.3.2.Installer.exe" don't recognize the /D switch...

### Steps to Reproduce the Issue: ... In 32bits Windows, execute: 

           npp.7.3.2.Installer.exe /D="C:\APL\Notepad++" 

### Debug Information: See the function ".onInit" in the "nppSetup.nsi" file...
the 	${If} "$InstDir" != "" ... is treated only for ARCH64...

**Comment by SinghRajenM** [comment]
I could not reproduce the issue.
I think, you're running a wrong command. As per /d switch documentation, **it must not contain quotes even if the path contains blank spaces.** Try without quotes and let us know if issue still persists.

![image](https://cloud.githubusercontent.com/assets/14791461/23091545/8ef48030-f5de-11e6-8e2c-8fcea0613e41.png)


Refer [URL](http://nsis.sourceforge.net/Which_command_line_parameters_can_be_used_to_configure_installers) for more info.

**Comment by jucabr2002** [comment]
Really SinghRajenM, I was using "/D" switch in the middle... my mistake
I was for deploy silently and using: 
- **npp.7.3.2.Installer.exe /D="C:\APL\Notepad++" /S** 

but now I'll:
- **npp.7.3.2.Installer.exe /S /D=C:\APL\Notepad++**

I tested and works fine...

thanks for you help...
