### ISSUE TITLE
"SSL connection error" on project site

### ISSUE THREAD

**Issue by drewnoakes** [notepad-plus-plus/notepad-plus-plus#292]
This URL fails for me:

https://notepad-plus-plus.org/

![image](https://cloud.githubusercontent.com/assets/350947/8294035/6c5cd59e-1931-11e5-82ca-37533315062f.png)

**Comment by milipili** [comment]
Sorry for the inconvenience. We were experimenting some new features. Even if it were for a very short time, you may have this issue. But it should be fine now ?

**Comment by drewnoakes** [comment]
Yep, it's back now. No inconvenience -- just making sure you were aware.
