### ISSUE TITLE
Preserve line ending types during drag-and-drop

### ISSUE THREAD

**Issue by jay** [notepad-plus-plus/notepad-plus-plus#2923]
### Description of the Issue
Dragging and dropping text does not preserve line endings.

### Steps to Reproduce the Issue

1. File > New
2. View > Show Symbol > Show End Of Line
3. Edit > EOL Conversion > UNIX/OSX Format
4. Add some lines ending in CRLF and other lines ending in LF.
5. Select the lines ending in CRLF and drag-and-drop somewhere
6. Observe the line endings of selected text has changed to the default

### Expected Behavior
I expected the line endings would be preserved.

### Actual Behavior
The line endings are not preserved and change to the selected format.

### Animated GIF
![notepad drag-and-drop changes line endings](https://cloud.githubusercontent.com/assets/965580/23098781/1daa753c-f625-11e6-9062-5e6e86e196e3.gif)

**Comment by akr-dev** [comment]
I got some related issue: when pasting something in a unix style file, a single CR used in the script on a line far above the paste is changed to LF

**Comment by MetaChuh** [comment]
@jay 

please use `edit > paste special > copy binary content` and `edit > paste special > paste binary content` to preserve line endings.

thank you for your help and best regards.

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
(no extra account is needed, just use your github account to sign in)
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)

**Comment by jay** [comment]
> please use `edit > paste special > copy binary content` and `edit > paste special > paste binary content` to preserve line endings.

This is about drag-and-drop though. If it's within the same file can you preserve it as binary or is there any reason why that would not be a good idea?

**Comment by sasumner** [comment]
It might be a good idea, but drag-n-drop editing is controlled by Scintilla rather than Notepad++.  So it isn't easy to change, and isn't likely to be changed.  You can assign some shortcut keys to the "binary content" commands...somewhat ease your pain maybe.

**Comment by dinkumoil** [comment]
@jay 

I wrote a plugin that can turn off EOL conversion when pasting (and some other things). Its name is _ExtSettings_. You can download it [>>> here <<<](https://sourceforge.net/projects/extsettings/). It will also be available soon via _PluginsAdmin_.
