### ISSUE TITLE
[Feature/Cosmetic] : Start display line numbers at ...

### ISSUE THREAD

**Issue by bugith** [notepad-plus-plus/notepad-plus-plus#2925]
### Description of the Issue
Editing a json file that starts with a "{" one liner, I'd like to be able to choose line numbers begin at "1" for real line number is "2".
In fact this is not for me (I could remove the 1st line and add it back before saving) but for a friend I directed to notepad++ to help with translating strings for another software, and he isn't very easy with new tools (I use the online editor that doesn't show/take into account the header for numbering lines, when the friend can't use it and have to work offline on the json file, so when we speak of some string at line #n we always have to say whether we include header or not) .
Such a feature may be extended to detect standard headers for different formats/languages and allow us to choose whether we want to include or discard the header offset.
Thanks

**Comment by abhiccc5** [comment]
can you tell me the url of "the online editor that doesn't show/take into account the header for numbering lines" so that I can check out what you want, or just share a screenshot.

**Comment by MetaChuh** [comment]
the line numbering in notepad++ will stay bound to the physical lines.
