### ISSUE TITLE
Allow filenames to be atttached

### ISSUE THREAD

**Issue by EnSec4Git** [notepad-plus-plus/notepad-plus-plus#2930]
### Description of the Issue
Notepad++ does not allow for attaching **filenames** as opposed to **filename extensions** to languages for syntax highlighting. While this may seem trivial, the current trend in the DevOps community is to use **filenames** without extensions to indicate domain-specific languages - as prominent examples I can point to `Vagrantfile`, used by [Vagrant](https://vagrantup.com) and, even more importantly, the `Dockerfile`, used by [Docker](https://docker.com). Finally, this is the case with a much older standard - `Makefile`.

### Steps to Reproduce the Issue
1. Open Notepad++ (tested with v7.3.2)
2. Go to `Settings`->`Style Configurator`
3. Select `Ruby`

### Expected Behavior
The user is allowed to add filename patterns to `User ext.` - either by specifying the suffix (i.e. both `Vagrantfile` and `rb` can work) or by specifying wildcard patterns.

### Actual Behavior
The user is allowed to add only filename extensions to `User ext.`, preventing uses such as attaching `Vagrantfile` to `Ruby`

### Debug Information
Notepad++ v7.3.2   (32-bit)
Build time : Feb 12 2017 - 23:15:39
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 8.1 (64-bit)
Plugins : mimeTools.dll NppConverter.dll NppExport.dll PluginManager.dll

**Comment by MetaChuh** [comment]
i'm not sure i can exactly understand what you mean, but the naming convention will stay as it is.

many thanks and best regards.
