### ISSUE TITLE
UDL - Variable with numbers in the end are highlighted as number in parenthesis 

### ISSUE THREAD

**Issue by MaDill** [notepad-plus-plus/notepad-plus-plus#2932]
When I define a new UDL and want to highlight numbers in parenthesis, it also highlight names with numbers in the end like "Var1". Just the number part. Attached is some sample code and a sample UDL.

### Expected Behavior
I expect that really only numbers are highlighted as them.

### Debug Information
Notepad++ v7.3.1   (64-bit)
Build time : Jan 17 2017 - 00:28:43
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 7
Plugins : mimeTools.dll NppConverter.dll 

Exported UDL:
[bugreport.xml.txt](https://github.com/notepad-plus-plus/notepad-plus-plus/files/789346/bugreport.xml.txt)

Samplecode:
[bugreport_samplecode.txt](https://github.com/notepad-plus-plus/notepad-plus-plus/files/789347/bugreport_samplecode.txt)

Screenshot:
![bugreport](https://cloud.githubusercontent.com/assets/7298934/23154736/a7431574-f80f-11e6-9f09-83d4f96c7456.png)

**Comment by rddim** [comment]
Is this OK?

![npp_udl](https://cloud.githubusercontent.com/assets/8998791/23162307/2332990e-f836-11e6-94c7-08d7b57b1d4e.png)

**Comment by MaDill** [comment]
Both not. The "1" in Var1 is not a number. Only 123 and 42 are numbers.

**Comment by rddim** [comment]
Like this?

![npp_udl3](https://cloud.githubusercontent.com/assets/8998791/23177805/d9c4493a-f870-11e6-9360-bf0002c2c2cc.png)

**Comment by MaDill** [comment]
Yes, How did you make this? What I did wrong in my UDL configuration?

**Comment by rddim** [comment]
Well, I'm not sure is thат the proper way, but it work. So:

1. Go to `Operators & Delimiter` tab
2. Add `Var1` in `Operator 1` box
3. Click on `Styler` button for `Delimiter 1 style` (where you have "(" and ")")
4. Check the `Operator 1`

**Comment by MaDill** [comment]
Ah you made it special for "Var1"? This was just an example. It can be also Var2, MyTest47, Remove1, ..... Just every word with an attached number is not an number and should also not be highlighted as a number.

I need a way to handle this. A number is only a real number with +- and decimal separator.

**Comment by rddim** [comment]
You can see [here](http://ivan-radic.github.io/udl-documentation/) for more information. But for now I didn't find another way to not color the numbers. May be in the next version of UDL it will be better...
