### ISSUE TITLE
Problem in Plugin Manager in version 7.3.2

### ISSUE THREAD

**Issue by AlexKontou** [notepad-plus-plus/notepad-plus-plus#2933]
### Description of the Issue
I installed Notepad++ v7.3.2 (32-bit) and I update the "Plugin Manager" in order to get the plugin for compare. Everytime I was trying to get the "compare plugin" it was installing the "Plugin Manager", but the "compare" never appeared. I tried to installed other plugins but in vain.

### Steps to Reproduce the Issue

1. Installed Notepad++
2. Installed Plugin Manager
3. Installed any other plugin

### Expected Behavior
As I couldn't install any plugins I unistalled notepad++ v7.3.2
I installed instead v7.3.1 and everything worked fine. Obviously you have some issues with Plugin Manager in the final version of Notepad++.

**Comment by dail8859** [comment]
It is probably best to report this to the [plugin manager issue tracker](https://github.com/bruderstein/nppPluginManager/issues).
