### ISSUE TITLE
[Feature] Search inside or except in comments and strings

### ISSUE THREAD

**Issue by wzol** [notepad-plus-plus/notepad-plus-plus#2934]
Could you please add a feature to the search dialog to search inside/except in comments and/or strings?

It would really speed up finding the needed strings when you have many items inside strings/comments - like echos in PHP or because of testing you have many blocks commented out.

Thank you in advance.

**Comment by MetaChuh** [comment]
exclude comments in search would be depending on the implemented scintilla component lexers.

unfortunately scintilla is an external project, so you will have to file your feature requests at the [<kbd>scintilla feature-request tracker</kbd>](https://sourceforge.net/p/scintilla/feature-requests/).

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
(no extra account is needed, just use your github account to sign in)
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)

there is currently nothing we can do about this experience, at the notepad++ part.
we apologise for that.
