### ISSUE TITLE
place close button left of tab

### ISSUE THREAD

**Issue by verajosemanuel** [notepad-plus-plus/notepad-plus-plus#2935]
Add option to place closing button on left.
Would be very easy to close a bunch of tabs just placing mouse pointer and clicking instead of moving around because every document has a different name longitude and therefore, close buttons are placed on right at the end of name for every tab.

**Comment by AngryGamer** [comment]
Can't you just [center click mousewheel](https://blog.codinghorror.com/content/images/uploads/2008/03/6a0120a85dcdae970b0128777031da970c-pi.png)?

**Comment by MAPJe71** [comment]
Or right click on tab and select one of the close options in the pop-up menu: close, close all but this, close all to the left, close all to the right.

**Comment by MetaChuh** [comment]
@verajosemanuel 

changing the side of the close button of a tab, would be like moving the steering wheel of a car to the respective other side.

this change will not be done, as notepad++ users are accustomed to the position of the close button.

many thanks for your ideas and best regards.
