### ISSUE TITLE
Allow python multiline doc string folding

### ISSUE THREAD

**Issue by ClaudiaFrank** [notepad-plus-plus/notepad-plus-plus#2936]
### Description of the Issue
By using the pyLexer property "fold.quotes.python" multiline doc strings get folded correctly.

### Steps to Reproduce the Issue
1. open a new doc and set python lexer
2. put in the folowing code
```
def foo():
    '''
    some info
    to
    display
'''

```

### Expected Behavior
Folding of docstring should start at first ''' and end with last '''

### Actual Behavior
No folding of docstring at all

### Debug Information
Notepad++ v7.3.2   (32-bit)
Build time : Feb 12 2017 - 23:15:39
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : ON
Local Conf mode : OFF
OS : Windows 7 (32-bit)
Plugins : XMLTools.dll NppExport.dll ComparePlugin.dll NppConverter.dll PythonScript.dll NppExec.dll LuaScript.dll NppTextFX.dll mimeTools.dll PluginManager.dll ColorPicker.dll NppSnippets.dll 

Source code changes for ScintillaEditView::setPythonLexer add execute(SCI...
```
void setPythonLexer() {
    setLexer(SCLEX_PYTHON, L_PYTHON, LIST_0 | LIST_1);
    execute(SCI_SETPROPERTY, reinterpret_cast<WPARAM>("fold.quotes.python"), reinterpret_cast<LPARAM>("1"));
};
```

**Comment by dail8859** [comment]
Closed by f917abd1f4e5d76e844ab84610738f9a6f8a0c0a
