### ISSUE TITLE
Convert all XML files to similar encoding

### ISSUE THREAD

**Issue by dail8859** [notepad-plus-plus/notepad-plus-plus#294]
Per the conversation with @donho on gitter --  converting all XML config and lang files to a similar encoding can do away with the two versions of tinyxml. 

No idea how to do this...yet.

**Comment by dail8859** [comment]
I've done a bit of research. I'm certainly not an expert when it comes to character encodings. 

The reason this issue was discussed was to do away with the two versions of tinyxml, so that it can be more easily replaced with tinyxml2. Currently in the source code there are 2 "versions" of tinyxml, one to handle `TCHAR`s (tinyxml), and one for `char`s (tinyxmlA). The language files and context menu are read in using tinyxmlA and converted using `WcharMbcsConvertor::char2wchar()`. 

Everything I've found states that Unicode [should not be stored in `TCHAR`](http://stackoverflow.com/a/17871934) (i.e. `wchar_t`). Since all the language files have their own encoding due to their specific language, it would probably have to stay the way it is now with tinyxmlA reading it and using `char2wchar`. 

So if all the XML encodings were handled the same way it would mean that *all* XML files would have to be read by tinyxmlA as plain `char` strings and ran through the `WcharMbcsConvertor`. I'm not sure if this would be an acceptable alternative to (eventually) getting tinyxml2 integrated. (FYI tinyxml2 uses plain `char` pointers).

Hopefully someone is more knowledgeable about this subject or has some ideas.

**Comment by milipili** [comment]
It is something like that yes. I have opened the task #307 for that

**Comment by dail8859** [comment]
@milipili This question also relates to the XML files for configuration (config.xml, stylers.xml, etc) not just the XML file for translations.

**Comment by milipili** [comment]
oki but this would require different issues.

**Comment by dail8859** [comment]
What do you mean exactly? I guess through what I've read, and your most recent commit to the language files, I'd like this issue to determine whether: 

* We stay with the way things are now -- meaning two versions of tinyxml
* Or also convert the XML configuration files to UTF-8 (so that config and language files are treated the same way) and only have 1 version of tinyxml

**Comment by milipili** [comment]
This cleanup will be done in the upcoming 7.x branch. We're also considering alternatives to XML. Thus :

 - We stay with the way things are now in the current stable release 6.x
 - We can make things differently in 7.x, continuing with XML (but in utf-8 of course) or using something else, like json for example for its simplicity. But, unless some major bug exists, other things must be done first before modifying this part.

**Comment by dail8859** [comment]
Thank you for the clarification. I agree we just stay with the way things are for now, and wait to make any decisions regarding XML (or something else) for the 7.x update.
