### ISSUE TITLE
BaanC Replaced C in Custom Language Menu

### ISSUE THREAD

**Issue by Watilin** [notepad-plus-plus/notepad-plus-plus#2940]
### Description of the Issue

After the 7.3.2 update, my “C” language menu entry has been replaced with “BaanC”.

My language menu is custom, I hid many of the available languages. I’ve unchecked the “Make language menu compact” box. Here are the entries that were in the menu before the update:

* C
* CSS
* Diff
* HTML
* JavaScript
* Normal Text
* PHP
* Properties
* SQL
* XML

After the update, only the “C” entry has changed, 

1. Have a Npp version prior to 7.3.2 installed
2. Have a custom menu language showing the “C” entry
3. Uncheck “Make language menu compact” if checked
4. Update to 7.3.2
5. Observe “BaanC” instead of “C” in the language menu

### Expected Behavior

The “C” menu entry should have been left in place in the language menu.
### Actual Behavior

The “C” menu entry has been replaced with “BaanC”.
### Debug Information

```
Notepad++ v7.3.2   (32-bit)
Build time : Feb 12 2017 - 23:15:39
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 7 (32-bit)
Plugins : CodeAlignmentNpp.dll ComparePlugin.dll HTMLTag_unicode.dll JSLintNpp.dll mimeTools.dll NppConverter.dll NppEditorConfig.dll NppExport.dll NppFTP.dll NppSaveAsAdmin.dll PluginManager.dll 
```

### Additional Info
In the Preferences Dialog I saw that “C” simply has been put in the hidden languages section. I’ve been able to unhide it.

**Comment by MetaChuh** [comment]
please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins if you update from version 7.5.9 or below.
if your issue still persists, and it is still of relevance, please feel free to file a new issue as easy to understand and reproducible as possible.

thank you for your help and best regards.
