### ISSUE TITLE
Document view scoll outside of program

### ISSUE THREAD

**Issue by Byggnadskontoret-Halmstad-Kommun** [notepad-plus-plus/notepad-plus-plus#2941]
### Description of the Issue

When i move the window the document view scoll section dosn't follow the window.
It stuck at the previous position

### Steps to Reproduce the Issue

1. Open document view
2. Move window to new location
3. 

### Expected Behavior

I want it to be where it supposed to be in the window
### Actual Behavior

I dosn't move with the window
### Debug Information

![npp](https://cloud.githubusercontent.com/assets/1901374/23212256/2541aca0-f906-11e6-9c28-c44690d9eb5c.png)

**Comment by Byggnadskontoret-Halmstad-Kommun** [comment]
I forgot, i'm using version 7.3.2

**Comment by dail8859** [comment]
Duplicate of #440, #1247, #1317, #2763, #2840

**Comment by Byggnadskontoret-Halmstad-Kommun** [comment]
Okej, didn't find any when a searched
