### ISSUE TITLE
Increase Amount and Save All Search History Entries Feature

### ISSUE THREAD

**Issue by Troglo37** [notepad-plus-plus/notepad-plus-plus#2944]
Description of the Issue

When Notepad++ is closed and reopened, only 10 entries are saved in the search history. I think it should be infinite, but if that will pose a problem, no less than 100 entries.

Steps to Reproduce the Issue

1. Click on the binoculars or on the toolbar click Search > Find
2. Enter more than 10 search terms
3. Close and reopen Notepad++

Expected Behavior

That however many terms are entered into the search, it will save all of them after Notepad++ is reopened.

Actual Behavior

It erases all but 10 entries.

Debug Information
Notepad++ v7.3.2   (32-bit)
Build time : Feb 12 2017 - 23:15:39
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 7 (64-bit)
Plugins : mimeTools.dll NppConverter.dll NppExport.dll NppFTP.dll PluginManager.dll

**Comment by benjamin-rose** [comment]
I would love this feature. I was in a situation today where it would have saved me literally hours of time.

**Comment by DedupOperator** [comment]
++ I would like this feature to be added.

I have also tried increasing the values in the config file for example :"nbMaxFindHistoryFind" and then it won't save any history after reopening npp.
Please fix it.
(using V7.4.1 x86)

Thank you.

**Comment by celadyn** [comment]
+1 to wishing for this. I'd like the find history to be... infinite :) especially when there's regex in there! I've created some crazy regex over the years and would love to be able to look back on it.

**Comment by donho** [comment]
https://github.com/notepad-plus-plus/notepad-plus-plus/issues/4511#issuecomment-854985220
