### ISSUE TITLE
Bookmark indicators (blue circles by line #s) don't scale with zoom

### ISSUE THREAD

**Issue by programmer5000-com** [notepad-plus-plus/notepad-plus-plus#2945]
### Description of the Issue

![image](https://cloud.githubusercontent.com/assets/25020067/23249403/358fcada-f972-11e6-8450-39e83b8294ff.png)
When you zoom out and scroll to bookmark indicators, they overlap instead of scaling.
![image](https://cloud.githubusercontent.com/assets/25020067/23249429/5560ee3e-f972-11e6-8532-5ff2cdebe7c9.png)
When you zoom in and scroll to bookmark indicators, they are very small instead of scaling.

### Steps to Reproduce the Issue

1. Open a new file.
2. Press enter a few times to get some newlines.
3. Bookmark those lines.
4. Zoom in and out and look at the indicators.

**Comment by duc-le** [comment]
I notice that not just the bookmark indicators don't scale, other indicators such as code folding (the minus or plus) indicators don't scale neither.

**Comment by MetaChuh** [comment]
the way scintilla handles zoom, is by changing the font size.
everything that is not rendered as a font, like the bookmark indicators, will stay the same size.

many thanks and best regards.
