### ISSUE TITLE
Font defaulted to italic since 6.7.8.2

### ISSUE THREAD

**Issue by keith-collyer** [notepad-plus-plus/notepad-plus-plus#295]
Since I upgraded to 6.7.8.2, the only font I seem to be able to use is Courier italic (I think, might be another "computer text" style font, maybe Lucida Console as that is what I used to have as a default). I can Bold and Underline, but no other selections make any difference. I upgraded to 6.7.9.2 to check and the same there. Strangely, my portable version is at 6.7.9.1 and does not seem to have this problem

**Comment by milipili** [comment]
@keith-collyer still the issue ? The font has been modified in the last versions

**Comment by keith-collyer** [comment]
not happening now, should have come back and reported. Thanks for chasing
