### ISSUE TITLE
Windows 7 ver: 7.3.2 x64 No "Edit with notepad++" context menu

### ISSUE THREAD

**Issue by Justin-Bieber** [notepad-plus-plus/notepad-plus-plus#2953]
Even though it was selected during installation it just doesn't appear in the shell context menu. This is regarding a fresh install. If you upgrade it will most likely be there as I ssupect it is carried over from previous registry entries.

**Comment by SinghRajenM** [comment]
Could not reproduce this issue on Win10 x64 bit. 
Is the issue happening only on Win7 x64? Is there any specific scenario in which this issue occurs?

**Comment by Justin-Bieber** [comment]
Reported as the problem occurred on Win7 x64. Worked around by installing 32-bit same version number of Notepad++. Then removing it and installing the 64-bit back. You should either put this on hold until more potential reports from users arise and as a reference to fix/test when you feel like it or close the case. Thank you.

**Comment by MetaChuh** [comment]
please update your notepad++ to the latest 64 bit version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins if you update from version 7.5.9 or below.
if your issue still persists, and it is still of relevance, please feel free to file a new issue as easy to understand and reproducible as possible.

thank you for your help and best regards.
