### ISSUE TITLE
Wrong link in release note of 7.3.2

### ISSUE THREAD

**Issue by chcg** [notepad-plus-plus/notepad-plus-plus#2957]
### Description of the Issue
https://github.com/notepad-plus-plus/notepad-plus-plus/releases/tag/v7.3.2
wrong link in the release note to
https://notepad-plus-plus.org/news/notepad-7.3.1-released.html
instead of
https://notepad-plus-plus.org/news/notepad-7.3.2-released.html

### Steps to Reproduce the Issue
open https://github.com/notepad-plus-plus/notepad-plus-plus/releases/tag/v7.3.2

### Expected Behavior
link to https://notepad-plus-plus.org/news/notepad-7.3.2-released.html

### Actual Behavior
link to https://notepad-plus-plus.org/news/notepad-7.3.1-released.html

**Comment by dail8859** [comment]
This appears to be fixed now.
