### ISSUE TITLE
pre-6.7 auto-indent behavior

### ISSUE THREAD

**Issue by AntonKhorev** [notepad-plus-plus/notepad-plus-plus#296]
(not sure about the version number, probably related to "smart indent" mentioned [here](https://notepad-plus-plus.org/news/notepad-6.7-release.html))

There's two ways auto-indent can work:
1. just repeat a previous line indentation
2. try to be "smart" and guess what indentation level should be on the next line (and possibly fail, see below)

Notepad++ switched from 1. to 2. It would be nice to have an option for 1.

"Smart" auto-indent doesn't work consistently, which is another issue, but I'm mentioning it here to illustrate why I want behavior 1. Let's suppose I edit a javascript file. 
- I want an object literal. I type in an opening curly brace and press enter. The editor increases the indentation level.
- I want an array literal. I type in an opening square bracket and press enter. Unlike the previous case, the indentation level doesn't increase.

**Comment by AntonKhorev** [comment]
More reasons to implement this:

* works even if the editor doesn't know anything about the syntax.
* doesn't impose any particular indentation style (try auto-indenting a switch statement)
* can work the same way in different editors (Atom's auto-indent behaves differently on on that array literal example)

**Comment by AntonKhorev** [comment]
This is how `switch` statement looks like with Notepad++ auto-indent:

    switch (a) {
        case 0:
        std::printf("no\n");
        break;
        case 1:
        std::printf("yes\n");
        break;
    }

This is how I like it:

    switch (a) {
    case 0:
        std::printf("no\n");
        break;
    case 1:
        std::printf("yes\n");
        break;
    }

Some people prefer this:

    switch (a) {
        case 0:
            std::printf("no\n");
            break;
        case 1:
            std::printf("yes\n");
            break;
    }

Auto-indenter can't know what to do unless there's an option for this. You can add a lot of code formatting options for every language (IntelliJ IDEA does this, there are options like Settings / Code Style / Java / Wrapping and Braces / 'switch' statement / Indent 'case' branches) or you can do a much simpler thing: put back one option for auto-indent.

**Comment by AntonKhorev** [comment]
Here's how this option looks in other editors/IDEs:

### Komodo edit
dropdown with three options - Auto-indent style: 
Use Smart Indent
**Indent to first non-empty column**
Don't auto-indent

### jEdit
dropdown with three options - Automatic indentation:
none
**simple**
full

### Eclipse
checkbox - **Enter key adjusts the indentation on the new line**

### CodeBlocks
checkbox - **Smart indent**

**Comment by oliezekat** [comment]
And some few people (like me) prefer to indent as ;
```
switch (a) 
    {
    case 0:
        std::printf("no\n");
        break;
    case 1:
        std::printf("yes\n");
        break;
    }
```
And define a function as ;
```
function()
    {
    //code
    }
```

**JSHint, JSLint, and professional ISO standard allow these styles, why not Notepad++ ?**

I'm exhausted Notepadd++ impose only one indentation style since 6.7 release :o(

**Comment by oliezekat** [comment]
I found another reports about this problem ;
* http://stackoverflow.com/questions/28171514/notepad-curly-bracket-auto-outdenting
* https://notepad-plus-plus.org/community/topic/6819/return-auto-indent-to-old-settings
* https://notepad-plus-plus.org/community/topic/117/request-about-the-auto-indent-feature

We are not alone ^^

**Comment by oliezekat** [comment]
**I found a way to restore previous behaviour of Notepad++ (before 6.7 release)** which not impose K&R indenting style ;

 1. Disable *Auto-Indenting* into *Misc* preferences
 2. Install *NppAutoIndent* plugin
 3. Set NppAutoIndent with "Previous line" option if you like Allman style, or "Block Indent" if you prefer Whitesmiths style (requested by @Shikayaru).

Nb: NppAutoIndent "Smart Indent" option apply the same default behaviour of Notepad++ since 6.7 (and related to K&R style only).

**Comment by spokorski** [comment]
I would also like the "previous line" behavior back.

The NppAutoIndent plugin is a partial solution, but it also has its own problems.  When using a split view and pressing `enter`, the inactive pane will automatically scroll to the same line as the active pane.

this means I cannot have a file open in one pane looking at the constants/globals/wherever for reference, and also open in the other pane for my actual work. Anytime I press `enter` the other pane scrolls and my reference isn't displayed anymore.

**Comment by oliezekat** [comment]
@spokorski you hadn't this problem if you move your pane into a new window

**Comment by MetaChuh** [comment]
closed due to inactivity (3y)
