### ISSUE TITLE
Function list not working with PHP Traits

### ISSUE THREAD

**Issue by jinteractive** [notepad-plus-plus/notepad-plus-plus#2962]
### Description of the Issue
Function list not working with PHP Traits.

### Steps to Reproduce the Issue
1. Open PHP file containing Traits, example:
```
<?php
trait example {
	public function exa()
	{
		echo 'TEST';
	}
}
?>
```
2. Click menu View / Function list.

### Expected Behavior
List of all functions or tree of all triats and functions.

### Actual Behavior
Empty function list.

### Debug Information
Notepad++ v7.3.2   (32-bit)
Build time : Feb 12 2017 - 23:15:39
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10 (64-bit)
Plugins : DSpellCheck2.dll mimeTools.dll NppConverter.dll NppExport.dll NppFTP.dll PluginManager.dll SpellChecker.dll Translate.dll

**Comment by vlakoff** [comment]
Pending fix in #2621.
