### ISSUE TITLE
Function list doesn't work with Perl since 7.3.2

### ISSUE THREAD

**Issue by akela68** [notepad-plus-plus/notepad-plus-plus#2963]
### Description of the Issue
On perl-code the function list is empty
This doesnt't work for .pm and .pl files. 
On v7.3.1 of npp the recognition works fine.

### Steps to Reproduce the Issue
Open a file (.pl or .pm) with functions included

### Expected Behavior
List of function and classes

### Actual Behavior
Empty function list

### Debug Information
Notepad++ v7.3.2   (32-bit)
Build time : Feb 12 2017 - 23:15:39
Path : C:\editor\npp\notepad++.exe
Admin mode : OFF
Local Conf mode : ON
OS : Windows 8.1 (64-bit)
Plugins : ComparePlugin.dll DSpellCheck.dll FingerText.dll jN.dll MathPad.dll mimeTools.dll NppConverter.dll NppExec.dll NppExport.dll NppFTP.dll NPPJSONViewer.dll NppQCP.dll NppSnippets.dll NppTextFX.dll PluginManager.dll PythonScript.dll RunMe.dll SourceCookifier.dll SpellChecker.dll

**Comment by akela68** [comment]
I replace the functionList.xml with the version from 7.3.1 and function list works fine.

**Comment by donho** [comment]
@MAPJe71 It seems a regression due to this PR:
https://github.com/notepad-plus-plus/notepad-plus-plus/commit/9dc109f5990a707ca69235608fa2f1fbd223ea82
Could you check on it?

**Comment by akela68** [comment]
This solution not works for me. The function list for perl always empty.

**Comment by donho** [comment]
@akela68  
v7.3.1 work with your perl script, whereas v7.3.2 doesn't work. - could you confirm it?

**Comment by MAPJe71** [comment]
@donho Mea Culpa, my PERL-parser-in-progress slipped through.
I'll make a PR to correct this.

**Comment by donho** [comment]
@akela68 Could you provide your perl script for validating the fix please?

**Comment by akela68** [comment]
It work's perfect for me.
Thank you!
