### ISSUE TITLE
Please add Swift as a language

### ISSUE THREAD

**Issue by HoboRider** [notepad-plus-plus/notepad-plus-plus#2966]
### Description of the Issue
I'm not sure this is really an issue, more of a new feature. I would just like for Swift to be added as a language choice for Notepad++.  Is that something that is being work on or thought about? Or is the need not there to add it?

**Comment by joshi1999** [comment]
This would be very nice :)

**Comment by redmanmale** [comment]
@HoboRider 
Highlighting support for all languages are provided by Scintilla.
You shoud ask about it at [Scintilla's feature requests page](https://sourceforge.net/p/scintilla/feature-requests/search).
Or you could write your own custom language definition.

**Comment by dail8859** [comment]
Closed by c8969b773ff08065613076ac642830ccab586b8c

**Comment by ndreisg** [comment]
Today I updated to Notepad++ 7.5.7
Swift syntax highlighting does still not work.
I can select Swift from the language menu and code folding works, but syntax highlighting does not...

**Comment by RegisStGelais** [comment]
removing the langs and stylers xml, did not fix the lack of highlighting for me.
