### ISSUE TITLE
Color modifiers for added keywords and functions

### ISSUE THREAD

**Issue by skkkk** [notepad-plus-plus/notepad-plus-plus#2972]
Hi!
I use the LISP language and adore the NPP for it. 
I beg you to add another items in the sintax highlighting list. I create a few types of custom functions and I'd like to see them all in different colors. 
This is what I've managed to figure out about the issue: https://notepad-plus-plus.org/community/topic/11274/color-modifiers-for-added-keywords-and-functions-in-sql

Thanks in advance.
With love from Russia.

**Comment by MetaChuh** [comment]
please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins if you update from version 7.5.9 or below.
if your issue still persists, and it is still of relevance to you, please feel free to file a new issue as easy to understand and reproducible as possible.

thank you for your help and best regards.
