### ISSUE TITLE
Notepadpp 7.3.2 32bits and older version not save/write correctly but seems to do it

### ISSUE THREAD

**Issue by glorissonbrunch** [notepad-plus-plus/notepad-plus-plus#2973]
### Description of the Issue
I create a file in an admin directory like (C:\Windows\System32\sysprep), when i edit it with notepadpp and save, notepadpp seems to correctly save but it doesn't. I could confirm this opening this file with classic notepad.

### Steps to Reproduce the Issue
1. I create an empty TXT file on Windows 7 (64bits) at "C:\Windows\System32\sysprep\test.txt" using Administrator account.
2. I edit it within notepad (classic) typing "test" and i save.
3. I open it with notepadpp, i modify his contain typing "test next" and save. Notepadpp seems to have done it (file icon in notepadpp becomes blue without any alert or error).
4. I reopen it within classic notepad and file is not modified and still contains "test" message. 

### Expected Behavior
I expect an alert/warning or effective file save.

### Actual Behavior
Not saving modifications in the file used.

Regards

**Comment by MetaChuh** [comment]
please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins if you update from version 7.5.9 or below.
if your issue still persists, and it is still of relevance, please feel free to file a new issue as easy to understand and reproducible as possible.

thank you for your help and best regards.

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
(no extra account is needed, just use your github account to sign in)
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)
