### ISSUE TITLE
Dragging a new tab is not working

### ISSUE THREAD

**Issue by EMostafaAli** [notepad-plus-plus/notepad-plus-plus#2974]
### Description of the Issue

Draw a new tab outside the main window, in order to open it in a new window won't work. I noticed that this only affect new documents that haven't been saved.
### Steps to Reproduce the Issue

1. Double click to open a new tab
2. Drag the new tab outside notepad++
3. Nothing will happened (if it was dragged to another instance of notepad++, it will give a message saying this file is not created).

### Expected Behavior

The default behavior is open the tab in a new window.
### Actual Behavior

Nothing
### Debug Information

Notepad++ v7.3.2   (32-bit)
Build time : Feb 12 2017 - 23:15:39
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10 (64-bit)
Plugins : mimeTools.dll NppConverter.dll NppExport.dll NppFTP.dll PluginManager.dll

**Comment by MetaChuh** [comment]
you can not drag and drop an unsaved file to another notepad++ instance.
please save your file before dragging it to another notepad++ instance.

alternative: right-click on an unsaved tab and select `move to other view`.
this will open up split screen view at the same notepad++ instance, without the need of saving.
