### ISSUE TITLE
NPP Debug info: read version information from registry if available and use current version only as fallback

### ISSUE THREAD

**Issue by GitMensch** [notepad-plus-plus/notepad-plus-plus#2976]
Current debug info for the OS shows:
* `Windows 8.1` on on Windows Server 2012 R2 Standard 
* `Windows 10` on Windows 10 Pro

The OS info for the Server is obviously misleading, the OS info for Windows 10 is missing the important build number (and the concrete version).

**Suggestion**: Read this information from registry if possible.
The following key is available at least since Windows 7 (not checked older versions) and can be read with guest privileges, too: 

`HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion` in `ProductName`, `CurrentBuildNumber` and `UBR` (Update Build Revision). The last two values combined are the full "OS build" number mentioned in [MS Release list][1].

This provides:
* Windows Server 2012 R2 Standard / 9600 / 18543 on the server
* Windows 10 Pro / 14393 / 693 on the client, additional there is the `ReleaseId` (only Windows 10+) showing 1607

Using it for the debug info and using the current implementation only as a fall-back would lead to a string like `OS: Windows Server 2012 R2 Standard, Build 9600.18543` / `OS: Windows 10 (1607), Build 14393.693`.

[1]:https://technet.microsoft.com/en-us/windows/release-info

**Comment by SinghRajenM** [comment]
Fix is submitted to show OS name properly now. However, it will show only OS name and bit info (32/64 bit).
As this info is meant for Notepad++ Dev Team to investigate the issue further. I think there is no point to show build number or flavor such Home/Professional/Enterprise Edition etc.

**Comment by GitMensch** [comment]
Nice to have the OS name properly, the pull request makes the current implementation better.
Checking the current code there are some side effects of the current way of getting the OS which would be better with checking the registry:

* the current code is much more than the registry lookup (of a key that is officially documented and therefore unlikely to change and accessible for reading with nearly no rights)
* the current code doesn't apply to newer versions of windows - you'd always have to add code for this
* you don't get the flavor (this can be important as some features simply don't exist in minimal versions)
* for Windows 10+: you don't get the build number - after using Windows 10 including but not limited to the Insider builds I know that some strange behavior only exist in older builds (or in new Insider builds where some software just stops to work because MS changed something)

You may argue that NPP doesn't use these features but you don't know if this is true in the future and I wonder why it shouldn't show this information if it can get it reliable and more easy than the current implementation.

**Comment by donho** [comment]
It's nice to have bug-fix. However to fix this issue could bring some regression, so this bug won't be fixed.

**Comment by GitMensch** [comment]
You've closed the merge request - but this wasn't what I've original suggested. I suggested to *only*
 change the debug information (as this is the place where it is relevant). I suggested to replace the current debug info output by output the values of documented HKLM keys.
@donho Please re-open or drop a note concerning the original request. Thank you.
