### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by vijayyande** [notepad-plus-plus/notepad-plus-plus#2977]
### Description of the Issue

In find in files search source code files, text files, etc combo box should be there

### Steps to Reproduce the Issue

1. click search->find in files

Add combo box to search like search only Source code files, Text files, Log files and
if selected source code files then it should search only source code files like .c, C++, or other language.

**Comment by dail8859** [comment]
There is already a filter which is sufficient. There are way too many combinations and corner cases to make this useful.
