### ISSUE TITLE
How to trim trailing spaces automatically when saving all open documents? [Feature Request]

### ISSUE THREAD

**Issue by salvarani** [notepad-plus-plus/notepad-plus-plus#2978]
Is there an option (hidden somewhere in the configuration settings) to trim trailing spaces automatically when saving documents? (If yes, I could not find it)
If not, could it be possible to add this feature?

Currently I have to trim trailing blanks manually by selecting the "Edit"-"Blank Operations"-"Trim trailing spaces" menu option on each document, one by one... now imagine you want to do it on dozens of documents! Moreover, there's no hot key associated to the feature and it gets quite annoying having to click every time on the menu option to achieve that!

**Comment by Ede123** [comment]
You should have a macro ("Trim Trailing and Save") which by default has the shortcut Ctrl+Alt+s

**Comment by salvarani** [comment]
Thank you very much! I didn't notice that macro before... Pity that it works only on the current document and I'd like to apply it to about 50 open documents...
