### ISSUE TITLE
functionList.xml: extension based association not working

### ISSUE THREAD

**Issue by thdoan** [notepad-plus-plus/notepad-plus-plus#298]
[NOTE: I originally posted this on [SourceForge](https://sourceforge.net/p/notepad-plus/discussion/331754/thread/e1dce3aa/), but it was marked as "read only", so I'm opening a ticket here in hopes that someone is able to assist or verify that it is indeed a bug.]

Steps to reproduce:

1) Create a file called `sample.cfc` containing this code:

``` coldfusion
<cfcomponent>
  <cffunction name="someFunc" access="public" output="false">
    <cfset var n = 1>
    <cfreturn n>
  </cffunction>
</cfcomponent>
```

2) Add this to `functionList.xml` inside `<associationMap>` tag:

``` xml
      <association ext=".cfc" id="cf_function" />
```

3) Add this to `functionList.xml` inside `<parsers>` tag:

``` xml
      <parser id="cf_function" displayName="ColdFusion Function">
        <function
          mainExpr="&lt;cffunction[^&gt;]+&gt;"
          displayMode="$functionName">
          <functionName>
            <nameExpr expr="name=&quot;[^&quot;]+&quot;" />
          </functionName>
        </function>
      </parser>
```

4) Open `sample.cfc` from step 1 in Notepad++ and enable the Function List.

ISSUE: `name="someFunc"` is not displayed in the Function List.

**Comment by GitMensch** [comment]
What should "[^&gt;]+&gt;" match? In any case: you've changed the file in %APPDATA%, didn't you?

**Comment by thdoan** [comment]
`mainExpr="&lt;cffunction[^&gt;]+&gt;"` should match `<cffunction name="someFunc" access="public" output="false">` in sample.cfc.

I'm using the portable version of NPP, and I changed functionList.xml that is in the same folder as notepad++.exe. I've added custom definitions in the same file and they worked as expected; it's just this case that's not working as expected, and I'm scratching my head as to why.

**Comment by GitMensch** [comment]
Good to know that you're changing the correct functionlist (didn't thought about the portable version).
And yes, looks like a bug to me as I cannot get this (working) parser to be applied with 

```
<association ext=".cfc" id="cf_function" />
```
Does this work for you with other items? It looks like current functionlist only works with the built-in languages (I guess user defined languages will work too) but not with associations.

To verify that the parser works I've replaced the association line by

```
<association langID="0" id="cf_function" />
```
and set the style to "Normal Text". The result is fine.

**Comment by thdoan** [comment]
All my custom function list definitions that work relied on parsers with built-in langIDs. Yes, you are right: it seems this is not working only for definitions that rely on `<association ext="...">`. I'll update the heading.

**Comment by thdoan** [comment]
Hi guys, I just updated to v7.1 and this issue still exists.

**Comment by MetaChuh** [comment]
closed due to inactivity (3y)
