### ISSUE TITLE
Spurious characters injected when using column delete

### ISSUE THREAD

**Issue by RrnR** [notepad-plus-plus/notepad-plus-plus#2981]
### Description of the Issue

When a rectangular area of text is selected by holding Shift and Alt down together, and the keys are released, the characters in the selection are deleted, and a 1-character wide column of characters is inserted where the selection was.
### Steps to Reproduce the Issue

1. Start NPP and open a text file
2. click on a text location
3. press Alt and Shift (keep them held down)
4. use the cursor keys to move the cursor to another place in the file.  A rectangular selection should display as the cursor moves.

![npp1](https://cloud.githubusercontent.com/assets/14882434/23482201/17d265e0-ff33-11e6-8dcf-c85cebc52ff1.png)

5. release the Alt and Shift keys

### Expected Behaviour

Nothing
### Actual Behaviour

The selected text is deleted and replaced by a single column of a random character.

![npp2](https://cloud.githubusercontent.com/assets/14882434/23482011/6dd1068c-ff32-11e6-9a1e-ddbe36584396.png)

### Work-around

Usually when I am marking a column of text, it's so I can delete it.  My procedure for this is:

 - click on the left-hand top character of the desired selection
 - hold Shift and Alt Down
- click on the bottom right character of the desired selection
- release Shift and Alt
- press Del

The main point is that by using the above procedure it's possible to select the text without inserting the rogue column.

**Comment by dail8859** [comment]
Can you post your debug info?

**Comment by RrnR** [comment]
Notepad++ v7.3.1   (32-bit)
Build time : Jan 17 2017 - 00:21:10
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10
Plugins : ComparePlugin.dll mimeTools.dll NppConverter.dll nppcrypt.dll
NppExport.dll NppFTP.dll NppTextFX.dll PluginManager.dll

**Comment by cmeriaux** [comment]
I can't reproduce your issue.
Isn't it a plugin issue ? (nppCrypt as an example)


    Notepad++ v7.3.1   (32-bit)
    Build time : Feb  1 2017 - 07:28:03
    Path : C:\Program Files (x86)\Notepad++\notepad++.exe
    Admin mode : OFF
    Local Conf mode : OFF
    OS : Windows 10
    Plugins : CodeAlignmentNpp.dll ComparePlugin.dll FileSwitcher.dll LightExplorer.dll linefilter2.dll MenuIcons.dll mimeTools.dll NavigateTo.dll NppConverter.dll NppExec.dll NppExport.dll NppFTP.dll NppMenuSearch.dll PluginManager.dll PythonScript.dll XMLTools.dll

**Comment by RrnR** [comment]
I tried starting with the -noPlugins option and it still exhibits the
behaviour.  Just to be clear, the procedure for making it happen is:


   1. place cursor on text.
   2. depress the shift key
   3. depress the Alt key
   4. with these two keys held down, use the cursor right and cursor down
   keys to highlight a block of text
   5. release the Alt Key
   6. release the Shift key

The rogue column appears as a result of step 5.


On Fri, Mar 3, 2017 at 9:56 AM, Christophe Meriaux <notifications@github.com

**Comment by cmeriaux** [comment]
I still can't reproduce your issue with your procedure
I tried with the official version 

    Notepad++ v7.3.2   (32-bit)
    Build time : Feb 12 2017 - 23:15:39
    Path : D:\data\download\npp.7.3.2.bin\notepad++.exe
    Admin mode : ON
    Local Conf mode : ON
    OS : Windows 7 (64-bit)
    Plugins : mimeTools.dll NppConverter.dll NppExport.dll PluginManager.dll 


Can you try again with this portable version  https://notepad-plus-plus.org/repository/7.x/7.3.2/npp.7.3.2.bin.7z 

You may have something broken in your configuration. You can try a fresh install.
