### ISSUE TITLE
CTRL+SHIFT+RIGHT_ARROW marks too much, if there are spaces to the right of cursor

### ISSUE THREAD

**Issue by AndyyKayy** [notepad-plus-plus/notepad-plus-plus#2983]
### Description of the Issue
Function "Move to next word start on the right" (SCI_WORDRIGHT [CTRL+RIGHT_ARROW]) behaves different, when using SHIFT key or not.

SCI_WORDRIGHT [CTRL+RIGHT_ARROW] and SCI_WORDRIGHT in combination with SHIFT [CTRL+SHIFT+RIGHT_ARROW] jump to different position in text. This is **VERY** confusing, when marking parts of lines.

### Steps to Reproduce the Issue
Open Notepad++
1. let's take the following example-line: "Here's a space: text continues..."
2. place the cursor after the ":"
3. press CTRL+RIGHT_ARROW
    -> cursor jumps to the left of "t"ext. 
    -> Most text editors behave like this (also this web text editor). That's fine.
4. place the cursor after the ":"
5. press CTRL+**SHIFT**+RIGHT_ARROW
    -> Notepad++: cursor jumps to the END OF "text". Thus "text" is also marked.
    -> most text editors: cursor jumps to the left of "t"ext. Thus "text" is **NOT** marked.

### Expected Behavior
Notepad shall jump to same positions in text, no matter if you use SHIFT key or not.

### Actual Behavior
Notepad jumps to different positions (see " Steps to Reproduce the Issue")

**Comment by MAPJe71** [comment]
You can change the assignment of these shortcuts in `Settings` > `Shortcut Mapper...` > `Scintilla commands`.

**Comment by AndyyKayy** [comment]
@MAPJe71 
Perfect!!!!!!!!!!!!!
You made my day!!!!!

I applied the following:
SCI_WORDRIGHTEXTEND    to    CRTL+SHIFT+RIGHT
(And I set the following shortcut to NONE:   SCI_WORDRIGHTENDEXTEND)
