### ISSUE TITLE
Feature Request:  Add file pattern matching to file search feature

### ISSUE THREAD

**Issue by jkappel71** [notepad-plus-plus/notepad-plus-plus#2985]
Your file search feature is really great, and I can almost replace my favorite grep application with notepad++.  The only thing I need is the ability to search only certain file types in a directory.  Maybe you could add a file specification option that lets me supply like: *.txt, *.csv, *.cs, *.css, *.html

if I could limit the files I am searching, then the notepad++ file search feature will completely replace my need for Grep!  Keep up the great work.

**Comment by cmeriaux** [comment]
It'a already implemented
![npp](https://cloud.githubusercontent.com/assets/12024941/23526483/8015fdec-ff92-11e6-83d4-929784dfd9d2.png)

Did I understood well your request ?

**Comment by jkappel71** [comment]
lol, I don't know how I missed that!!  That rocks, thanks!
