### ISSUE TITLE
When changing a < inside a text field inside XML doc, NotePad++ crashes

### ISSUE THREAD

**Issue by jonquet** [notepad-plus-plus/notepad-plus-plus#2988]
<?xml version="1.0"?>
    <rdf:Description rdf:about="http://www.w3.org/2004/02/skos/core#altLabel">
        <DISPLAY_LABEL xml:lang="fr">label with a < </DISPLAY_LABEL>
    </rdf:Description>

If you edit the < caracter to change it by soemthing else (e.g., 	
&lt;) then the software crashes

**Comment by dail8859** [comment]
It works for me. Please post your debug info and also try disabling your plugins because it could be one of those causing the crash.

**Comment by jonquet** [comment]
It is a snick bug that I was expecting to reproduce on a simple file... but I can't either. 
Anyway, if I can do it again, I will log better.
