### ISSUE TITLE
Move settings and shortcuts to editable JSON

### ISSUE THREAD

**Issue by dwelle** [notepad-plus-plus/notepad-plus-plus#299]
Use JSON/ CSON/ *SON, for better UX. Also, the shortcuts should (also) be identified by `name`, or at least it should have such property, because e.g.:

```
<Shortcut id="42036" Ctrl="yes" Alt="yes" Shift="no" Key="65" />
```

Is not really friendly. Could look like this:

```
{
    "InternalCommands": [
        {
            "id": "42036",
            "name": "whateverThisShortcutIsFor"
            "Ctrl": "yes",  "Alt": "yes", "Shift": "no",
            "Key": "65"
        }
    ]
}
```

**Comment by cmeriaux** [comment]
Hello,
I've already done a pull request to do a part of what you want.
https://github.com/notepad-plus-plus/notepad-plus-plus/pull/70

**Comment by dwelle** [comment]
@cmeriaux cool, it's a step forward. Now someone needs to move us to `JSON` and named shortcuts/ settings, and all will be well :)

**Comment by Croydon** [comment]
:+1:

**Comment by MetaChuh** [comment]
closed due to inactivity (4y)
