### ISSUE TITLE
Win. v7.3.2 (32-bit): Windowed View After Pressing F11 Removes Title, Toolbar, and Tabs.

### ISSUE THREAD

**Issue by NezzyGuda** [notepad-plus-plus/notepad-plus-plus#2991]
### Description of the Issue

The title (file location at top), toolbar, and tabs for multiple files disappear if F11 is pressed for full-screen and then pressed again for windowed mode on Notepad++ v7.3.2 (Windows 32-bit).

### Steps to Reproduce the Issue

1.  Open file in notepad++
2.  Press F11.
3.  Pressing F11 again

### Expected Behavior

Full screen mode (F11) should hide the title, toolbar, and tabs. However, when pressing F11 again, the application should revert back to having these features in the windowed view.

### Actual Behavior

After reverting back from Full Screen mode after pressing F11, the windowed Notepad++ does not have the title, toolbar, and tabs and you cannot retrieve the toolbar by pressing [Alt + T]. Additionally, the application cannot be minimized (even when using the [windows key + D or windows key + M] command).

### Workaround Information
I have discovered that closing notepad++ and reopening it will reopen where I left off even if the files have not been saved. And reopening a new notepad++ resolves the issue. I am able to save and continue working on my project. This bug is not software breaking, but it is rather annoying.

**Comment by SinghRajenM** [comment]
I could not reproduce the issue. Please check with latest version.
If issue continue to persists, then paste debug info here (from N++ menu -> ? -> Debug Info)

**Comment by MetaChuh** [comment]
please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins if you update from version 7.5.9 or below.
if your issue still persists, and it is still of relevance, please feel free to file a new issue as easy to understand and reproducible as possible.

thank you for your help and best regards.
