### ISSUE TITLE
Find And Replace Cannot replace special characters anymore.

### ISSUE THREAD

**Issue by AraHaan** [notepad-plus-plus/notepad-plus-plus#2992]
### Description of the Issue

Before on v7.2.2 you chould replace the following characters in find and replace. ``%``, ``~``, ``\``, ``/`` but now it will not show that it find it even though they are present in the files. This is totally a bug from somewhere.

### Steps to Reproduce the Issue

1. open a file with those characters.
2. Try to replace them all with find and replace.
3. Cannot replace as it fails to find the characters it should.

### Expected Behavior

Find and replace to work on any character you tell it to find and replace or combination of characters.

### Actual Behavior

Before on v7.2.2 you chould replace the following characters in find and replace. ``%``, ``~``, ``\``, ``/`` but now it will not show that it find it even though they are present in the files. This is totally a bug from somewhere.

### Debug Information

Notepad++ v7.3.2   (32-bit)
Build time : Feb 12 2017 - 23:15:39
Path : E:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 7 (64-bit)
Plugins : MenuIcons.dll mimeTools.dll NppConverter.dll nppcrypt.dll NppExec.dll NppExport.dll NppFTP.dll NPPJSONViewer.dll NppSaveAsAdmin.dll PluginManager.dll PyNPP.dll Python Indent.dll PythonScript.dll ReloadButton.dll Translate.dll ZenCoding-Python.dll zoomdisabler.dll 

![ss 2017-03-04 at 02 54 11](https://cloud.githubusercontent.com/assets/15173749/23582197/8a7ff5ea-00ea-11e7-8511-22c7aa0ed1e9.png)

**Comment by MAPJe71** [comment]
Un-tick `Match whole word only`?

**Comment by AraHaan** [comment]
oh, thanks.
