### ISSUE TITLE
Request: Project Panel - A real directory is better than an XML tree

### ISSUE THREAD

**Issue by KSXGitHub** [notepad-plus-plus/notepad-plus-plus#300]
I usually create a project fit inside a directory

There's somewhat difficult to update the directory change, Add new folder for instance:

 - First, I must right-click in the folder (which was displayed in project panel) which contain the new folder
 - Then, I select 'Add Folder' to create a new "folder" in the project panel
 - Finally, select 'Add Files...' or 'Add Files from Directory...'

I don't see how an XML tree which save project information useful, but I see there manipulations are very complex.

So, I suggest you to make project panel easier to use: by auto updating directory tree or add an 'refresh' button.

**Comment by milipili** [comment]
+1

**Comment by dail8859** [comment]
Pull request #214 is related to this.

**Comment by dail8859** [comment]
"Folder as Workspace" feature covers this.
