### ISSUE TITLE
Plugin manager update loop

### ISSUE THREAD

**Issue by Fabian42** [notepad-plus-plus/notepad-plus-plus#3000]
### Description of the Issue
The plugin manager asks for an update every time I try to install an update.

### Steps to Reproduce the Issue
1. Open Plugins->Plugin Manager->Show Plugin Manager
2. Click on "Install" (no selection of Plugins needed)
3. Result: Popup "An update is available to Plugin Manager. It is *strongly* advised that the Plugin Manger is updated before any other plugin is installed or Updated. Would you like to update the Plugin Manager now?"
4. Click on "Yes".
5. Restart Notepad++ when it tells you to do it.
6. Go to Plugins->Plugin Manger->Show Plugin Manager again
7. Click on "Install" again
8. Result: The same popup.

In the "Updates" tab there is no update. First there was one for the plugin manager, then I installed that update before installing other plugins, now it's not in the list anymore, but it keeps asking.
Plugin manager version is 1.4.3.

### Debug Information
Notepad++ v7.3.2   (32-bit)
Build time : Feb 12 2017 - 23:15:39
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : ON
Local Conf mode : OFF
OS : Windows 7 (64-bit)
Plugins : ComparePlugin.dll CustomizeToolbar.dll MenuIcons.dll NppExternalLexers.dll NppSaveAsAdmin.dll PluginManager.dll RunMe.dll SpellChecker.dll mimeTools.dll NppConverter.dll NppExport.dll

**Comment by dail8859** [comment]
This would probably be best reported to the [Plugin Manager](https://github.com/bruderstein/nppPluginManager/issues/). You may want to search the issues there to see if any similar issues exist.
