### ISSUE TITLE
Confusing BOM menu and status line display

### ISSUE THREAD

**Issue by holgerlembke** [notepad-plus-plus/notepad-plus-plus#3003]
(Latest version, all good..)

I have problems to understand the concept of the status display of UTF-8 . If I select "Encoding-->Encoded in UTF-8 without BOM" the status line shows "UTF-8", if I select "Encoding-->Encoded in UTF-8" the status line shows "UTF-8-BOM".

![bom or not to bom](https://cloud.githubusercontent.com/assets/2034993/23667597/ad8d3590-035e-11e7-8c99-0ef860f920d2.png)

I would expect it the other way round, "-BOM", read "minus BOM" or "without BOM".

(German language screenshot, but same for english.)

**Comment by SinghRajenM** [comment]
How about?
UTF-8 => UTF-8
UTF-8 with BOM => UTF-8 + BOM or UTF-8 : BOM or no prefix at all UTF-8 BOM like below 

![image](https://cloud.githubusercontent.com/assets/14791461/23672534/0ce574ae-0395-11e7-8920-4389306b7df7.png)

**Comment by holgerlembke** [comment]
UTF-8 => UTF-8
UTF-8 with BOM => UTF-8 + BOM 

sound understandable to me.

**Comment by schnurlos** [comment]
I think that's fixed:
https://github.com/notepad-plus-plus/notepad-plus-plus/commit/fc9f0de7712af12091736f33dca1bba802746e6c

**Comment by MetaChuh** [comment]
please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins if you update from version 7.5.9 or below.
if your issue still persists, and it is still of relevance, please feel free to file a new issue as easy to understand and reproducible as possible.

thank you for your help and best regards.
