### ISSUE TITLE
Tab-closing error

### ISSUE THREAD

**Issue by chsn1** [notepad-plus-plus/notepad-plus-plus#3004]
### Description of the Issue
The handling of closing the tabs with clicking on the red Xs has some kind of misinterpretation where the actual mouse cursor is after closing the first tab.

Note: I didn't use the middle click! All of the clicks are left clicks.

### Steps to Reproduce the Issue
1. Open a few files with different filename-lenghts.
2. Close the first tab while clicking on its red X.
3. The next tab-name must be different in terms of length so that the red X to close it is not on the same spot as before.
4. Don't move the mouse, just click and the next tab will close, too.
5. The next tabes will do the same. You don't have to click the red X, just don't move the mouse and keep clicking.

### Expected Behavior
The expected behaviour was not closing the next tab like the one before, just mark it as active.

### Actual Behavior
While not moving the mouse the tabs will close when you click in the middle of the name after you closed a tab.

### Debug Information
Notepad++ v7.3.2   (32-bit)
Build time : Feb 12 2017 - 23:15:39
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 8.1 (64-bit)
Plugins : mimeTools.dll NppConverter.dll NppExport.dll NppFTP.dll PluginManager.dll

Different (older) versions of Notepad++ do the same.
Tested on Windows Server 2008 R2 and Windows 8.1 Pro.

![image](https://cloud.githubusercontent.com/assets/6362230/23677672/5d213f16-0381-11e7-80ca-d472df98472b.png)

**Comment by SinghRajenM** [comment]
I confirm, this is really an issue and require attention.

**Comment by SinghRajenM** [comment]
Issue is fixed, please verify the [nighty Build](https://ci.appveyor.com/api/buildjobs/yd066s6egnqqjf09/artifacts/Notepad%2B%2B.Win32.Unicode%20Release.exe)

**Comment by donho** [comment]
@chsn1 @SinghRajenM  I cannot reproduce it at all with x86 and x64 version. Any info to reproduce it  steadily?

**Comment by SinghRajenM** [comment]
@donho 
Steps to reproduce:
1. Open N++ open three tabs (say A.txt, BCDEFGHIJKLMNOPQRSTUVWXY.txt and Z.txt")
2. Current active doc is Z.txt
3. Close A.txt
4. Now observe **(without moving mouse)** BCDEFGHIJKLMNOPQRSTUVWXY.txt, Even mouse is not on "x" button but still "x" is highlighted. Now, just clicking it will close the document.

Recording is attached.
![tabissue](https://cloud.githubusercontent.com/assets/14791461/26790141/50a393f6-4a30-11e7-980d-df6bddf92a62.gif)

**Comment by donho** [comment]
@SinghRajenM Which version of Windows do you use?

**Comment by SinghRajenM** [comment]
I use Win10 x64 and x86 of npp. The recording was done with the same.
However, it can be reproduced with win7 x64 in my office Dev pc.

**Comment by donho** [comment]
@SinghRajenM Can't still reproduce it.
Could you post your debug info here?

**Comment by SinghRajenM** [comment]
Notepad++ v7.4.1   (32-bit)
Build time : May 18 2017 - 02:00:37
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10 (64-bit)
Plugins : DSpellCheck2.dll mimeTools.dll NppConverter.dll NppExport.dll PluginManager.dll

**Comment by AngryGamer** [comment]
I can't replicate this either on same OS and version.

**Comment by SvyatoslavRazmyslov** [comment]
I was able to reproduce.

Windows 10 x64; Notepad++ v7.4.2 (64-bit).

**Comment by donho** [comment]
@SvyatoslavRazmyslov Could you post your Debug Info like @SinghRajenM did ?

**Comment by donho** [comment]
OK, I can reproduce now.
