### ISSUE TITLE
HTML 5 : no syntactic coloring for tags <main>, <dialog> and <picture>

### ISSUE THREAD

**Issue by philippe77** [notepad-plus-plus/notepad-plus-plus#3005]
### Description of the Issue

Following HTML 5 tags main, dialog and picture are not recognized as html tag

### Steps to Reproduce the Issue

1. create a new file and save it with ".html" extension
2. write followings tags : 
&lt;!doctype html&gt;
&lt;html&gt;
    &lt;head&gt;
    &lt;/head&gt;
    &lt;body&gt;
        &lt;main&gt;
        &lt;/main&gt;
    &lt;/body&gt;
&lt;/html&gt;

3.  &lt;main&gt; and &lt;/main&gt; are written in black

### Expected Behavior

Following  html tags main, dialog and picture should be written in blue color by default when editing a html file
### Actual Behavior

Default color is black for these tags

**Comment by MAPJe71** [comment]
Most likely you need to delete (make a backup!) your `langs.xml` file in order for Notepad++ to pick up on the new changes. This file is most probably in `C:\Users\my_user_name\AppData\Roaming\Notepad++`.

**Note**: This file also stores custom settings if you have done things like extensions and keywords so those would be lost.

**Comment by philippe77** [comment]
Thank you. I used plugin manager and installed "html tags" plugins and now all works !
