### ISSUE TITLE
Multi-line tabs looks terrible in v7.3.3

### ISSUE THREAD

**Issue by rddim** [notepad-plus-plus/notepad-plus-plus#3007]
### Description of the Issue

In the new version 7.3.3 the opened tabs in multi-line mode looks terrible. There is no problem with previous v7.3.2. See the screenshots.

v7.3.3
![npp733](https://cloud.githubusercontent.com/assets/8998791/23728264/91af5cd4-0464-11e7-845f-aeadc71c11dc.png)
v7.3.2
![npp732](https://cloud.githubusercontent.com/assets/8998791/23728268/981e9d78-0464-11e7-9154-116bcc702006.png)

### Debug Information

Notepad++ v7.3.3   (32-bit)
Build time : Mar  8 2017 - 03:37:37
Path : D:\Install\Office Programs\npp\notepad++.exe
Admin mode : ON
Local Conf mode : ON
OS : Windows 7 (64-bit)
Plugins : mimeTools.dll NppConverter.dll NppExport.dll PluginManager.dll

**Comment by ilhanyumer** [comment]
I have the same issue with v7.3.3.

Notepad++ v7.3.3   (64-bit)
Build time : Mar  8 2017 - 03:39:58
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 8.1 (64-bit)
Plugins : mimeTools.dll NppConverter.dll

**Comment by fstellari** [comment]
Same issue

**Comment by rddim** [comment]
Well, the answer is in https://github.com/notepad-plus-plus/notepad-plus-plus/commit/e1125f0bbc6632f037c7511368c01e55bfaa447e#commitcomment-21052348
I will revert to the v7.3.2 and because of #3016

**Comment by jcaillon** [comment]
Same here, I really hope this can be fixed, I was so happy when I read the changelog announcing this feature ^^"

**Comment by AngryGamer** [comment]
The tabs don't look too bad unless you're referring to text being clipped in the tab for "change.log" If that's the case, then I made a pull request [#3023](https://github.com/notepad-plus-plus/notepad-plus-plus/pull/3023) which fixes that.

**Comment by rddim** [comment]
@AngryGamer No, it's not about the clipped text, it's about how the tabs look when you have 2+ rows. In one row they look normal, but this button style doesn't look as part of Notepad++ UI design. If it possible to look 'normal' (as normal I mean how it looks in previous multi-line versions) in one and 2+ rows will be great. Thanks for your work and PR, but I'm not a programmer and don't know how to compile for myself without installing tons of gigabytes of Visual Studio just for tests.

**Comment by rddim** [comment]
@AngryGamer Thank you, this is more usefull. I can reorder the buttons with Shift+Mouse wheel, but when I use Ctrl+MW or Ctrl+Shift+MW there is something like 'pulsation' of all buttons, with mouse clicks it's OK. So for me as functionality it is good. I hope that the button style UI can be fixed as original tab style UI.

**Comment by AngryGamer** [comment]
@rddim IDK if anyone likes this, but the appearance is slightly different with TCS_FLATBUTTONS

Darken inactive tabs ☑
![flat-buttons-darken](https://cloud.githubusercontent.com/assets/4331362/23864818/f1162594-07d0-11e7-8969-567891167eba.png)
Darken inactive tabs ☐
![flat-buttons-light](https://cloud.githubusercontent.com/assets/4331362/23864821/f2daeaea-07d0-11e7-870a-b5d33eea6ef3.png)

**Comment by rddim** [comment]
@AngryGamer the last one looks good, it's less obtrusive like a colors in flat Windows8+, but I think for this:

![npp_mockup](https://cloud.githubusercontent.com/assets/8998791/23868609/b1e8c4d2-0828-11e7-8c4f-15f082f7c075.png)
I make it in GIMP and don't know how it look in Windows8+. With this button style there is a moment of "WTF is this pressed button, where are my tabs?!?". I hope you or somebody else can understand me how I want to looks the "new" style - It's just about the old good one, with old good tabs, nothing more. But let other users say what they want.

**Comment by reddyshyam** [comment]
I will have to agree with rddim. With the extra space round the buttonish effect, it doesnot look like npp at all. Can someone fix this please?

**Comment by rajnisheu** [comment]
HI, the new multi line Tabs are awful in 7.3.3. Is there any way to go back to the previous version? Appreciate any help.

**Comment by appelgran** [comment]
I too think the tabs in 7.3.3 looks very unfortunate. Text is being clipped and the very small amount of blank space around the text makes the readability bad. 

I've never felt the need for the tabs to stay in position. But if you decide to keep this new feature I suggest you make it look like rddim suggests three posts above. It's clean, readability is good and it is what we are used to.

**Comment by esrat** [comment]
Thanks to rddim for pointing my issue (I created myself after I tried to live with this bug for some time ...) to this one.

I was surprised to read that this should be a feature?!
This possibility never appeared to me! On the machine where I use the automatic update feature I just agreed to download and install without having a change log. For me this was clearly a bug breaking the visual appearance. And now I just realised that it also breaks the functionality to drag tabs around!?!

I often have to reorder files using the mouse (e.g. to compare multiple files in the first and second view or just to group temporary and other files thematically) so this version’s usability is not that good for me.

Is there an option or way to cleanly downgrade the installed version to 7.3.2?
(On other machines I do use the zip package, so this shouldn’t be a problem.)

**Comment by rddim** [comment]
@esrat You welcome. The reordering is fixed, but we will see that in the next version, or you can compile N++ for yourself. I hope that the real tabs will be also fixed...

**Comment by maxicombina** [comment]
Still looking bad in 7.4.1 :(

**Comment by reddyshyam** [comment]
Yes! Looks like it will be ignored.

**Comment by AngryGamer** [comment]
@maxicombina @reddyshyam The tab button change was necessary to improve usability/functionality. To fix the cosmetic issues would mean regressing on the improvements. I'd say this is probably a WONTFIX. Check issue [#3273](https://github.com/notepad-plus-plus/notepad-plus-plus/issues/3273) for more info.

**Comment by reddyshyam** [comment]
@AngryGamer I understand your point of view but along with the functionality, UI appeal is also important. We do not want to go back to 80s with the 2020's functionality. Just my view, that's all.

**Comment by AngryGamer** [comment]
@reddyshyam I don't disagree with you, but I think most people would agree the uglier UI was worth the fixes to some very annoying issues.

**Comment by maxicombina** [comment]
I am very disappointed with this approach :(
As a developer myself I totally understand the 'prefer usability/functionality' approach. But when UI is affected (and in such horrible way), shouldn't we (well... maintainers) find a better solution?
My 2 cents.

**Comment by n-peugnet** [comment]
It was already better with  TCS_FLATBUTTONS in my opinion. Maybe it would look more like a tab if the clicked button border was outset instead of inset : 

![nppmultilinetabsoutset](https://cloud.githubusercontent.com/assets/23519418/26673520/7596c848-46bd-11e7-8ab6-d80d418338a5.png)

**Comment by avih** [comment]
I also think it's unexpected that tabs look like buttons. I don't disagree that it's functionally enough, but tabs, which are a pretty standard concept in UI, should look like tabs IMO, i.e. "connected" to the document. Personally I find the buttons unpleasant.

The buttons also feels (and possibly are) much "noisier" than normal tabs. Someone mentioned flat buttons, but I don't see where to enable it (looking at settings -> preferences -> general -> tab-bar).

FWIW, I'm on Windows 8.1 .

> The tab button change was necessary to improve usability/functionality. ... Check issue #3273 for more info.

Could someone please point to the issue/commit/discussions/reasons which resulted in changing the tabs to buttons? #3237 doesn't seem the reason to me but rather a result of this change, isn't it?

**Comment by AngryGamer** [comment]
@avih [#917](https://github.com/notepad-plus-plus/notepad-plus-plus/issues/917) [#1096](https://github.com/notepad-plus-plus/notepad-plus-plus/issues/1096) [#1787](https://github.com/notepad-plus-plus/notepad-plus-plus/issues/1787) [#1960](https://github.com/notepad-plus-plus/notepad-plus-plus/issues/1960) [#2241](https://github.com/notepad-plus-plus/notepad-plus-plus/issues/2241#issuecomment-246173192)

**Comment by JStinebaugh** [comment]
Is it possible to add a feature/option to allow us to choose between the button layout and the older tab layout (with the inherit drag/drop issue)?  I would prefer to continue to deal with the drag/drop issue and have the old tabs vs having the buttons that just don't look right.

**Comment by reddyshyam** [comment]
I would second @JStinebaugh. I don't drag drop much so if given us this choice, it would be great!

**Comment by AngryGamer** [comment]
@JStinebaugh @reddyshyam someone would need a PR for it. The main problem with tabs wasn't so much the drag and drop (although that was annoying too), but the fact rows weren't stationary when selected, the active row was always pulled to the front. This is confusing if you're expecting the position of tabs to stay where they are when selecting one.

**Comment by JStinebaugh** [comment]
I totally understand what you are saying as I regularly have 3-4 rows of tabs on a full screen window open, but still something I would like to have an option on.  As far as the PR, are you suggesting that I create a fork of the project, make the change option and then submit a PR to have it considered?

**Comment by VsevolodGolovanov** [comment]
Is there a fork with this change rolled back? The tab shifting problem never bothered me much, unlike the new confusing UI.

**Comment by maxicombina** [comment]
I have just stopped using Notepad++.
