### ISSUE TITLE
Add “Paste as HTML” to custom shortcuts

### ISSUE THREAD

**Issue by iyoossaev** [notepad-plus-plus/notepad-plus-plus#301]
Hi,

I am using “Paste as HTML” a freakin’ lot and I would welcome you implementing access for this function from the Shortcut Mapper (and, basically, all other elements from the menu – because why not?).

Regs,
iyoossaev

**Comment by nlsdg** [comment]
Is this still an issue? Paste HTML Content is available in the Shortcut Mapper in v7.5.1.

**Comment by iyoossaev** [comment]
Thanks for a prompt response ;) works like charm now, much obliged :)
