### ISSUE TITLE
Can not change the auto-complete character counter

### ISSUE THREAD

**Issue by MaDill** [notepad-plus-plus/notepad-plus-plus#3010]
### Description of the Issue
From the preferences I can not change the auto-complete character counter.

### Steps to Reproduce the Issue
1. Open the preferences and go to the "Auto-Completion"
2. Click on the blue number "From X th character"
3. Type in a number

### Expected Behavior
The number should be displayed and used

### Actual Behavior
When I type in a number the input field is getting blank and the number is not used. Instead it is set to 1.
![notepad _auto-complete_character_blank](https://cloud.githubusercontent.com/assets/7298934/23740480/13b9df1c-04a4-11e7-9aa9-76803ad455ae.png)

I changed it in the config.xml file instead

### Debug Information
Notepad++ v7.3.3   (32-bit)
Build time : Mar  8 2017 - 03:37:37
Path : C:\Users\mdill\Downloads\_PortablePrograms\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : ON
OS : Windows 7 (64-bit)
Plugins : ComparePlugin.dll Explorer.dll LanguageHelp.dll MenuIcons.dll mimeTools.dll NppConverter.dll NppExec.dll NppExport.dll PluginManager.dll

**Comment by snoopy78** [comment]
A possible problem source is shown in #4227. I have the same problem, but it could not be solved, by changing it to 100% and restart the program.
Notepad++ v7.5.8   (64-bit)
Build time : Jul 23 2018 - 02:06:36
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10 (64-bit)
Plugins : DSpellCheck.dll mimeTools.dll NppConverter.dll 
Language: German

**Comment by MetaChuh** [comment]
please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins if you update from version 7.5.9 or below.
if your issue still persists, and it is still of relevance, please feel free to file a new issue as easy to understand and reproducible as possible.

thank you for your help and best regards.

**Comment by snoopy78** [comment]
Sorry, but the bug still exists in 7.6.6.
I see the 1, but if I try to overwrite, I could not input something.
Where is the corresponping configuration file? I try to rename it. Maybe with a fresh configuration file the error disappears.

**Comment by Quailsnap** [comment]
Likewise having this issue.

**Comment by MetaChuh** [comment]
@Quailsnap 

please try the following, if any windows customisation and scaling factor combination cause this for you:

* exit notepad++ if it is running.
* right click on your notepad++ icon.
* select `properties > compatibility > change high dpi settings`.
* activate `override high dpi scaling behavior`.
* and set `scaling performed by:` to `system (enhanced)` instead of `application`, as seen at the screenshot below.

![Imgur](https://i.imgur.com/qVQ4Bg8.png)

after that, open notepad++ and try to change your autocompletion character value.

many thanks and best regards.

**Comment by snoopy78** [comment]
Thank you. This works for me, but why this happens?

Sincerely, Markus

**Comment by MetaChuh** [comment]
@snoopy78 

because of the vast amount of different possible windows desktop customisations and desktop scaling options.
the enhanced system scaler is more "aware" of custom windows appearance settings than the application scaler can be.

many thanks and best regards.

**Comment by pete312** [comment]
although this workaround works its less than ideal and probably should be still counted as a bug.  The setting System Enhanced setting is blurry.  you can set it back to Application and the setting remains. But again this still a bug in windows 10.
