### ISSUE TITLE
7.3.3 will open the changelog every time you launch NP++

### ISSUE THREAD

**Issue by strollingHeifer** [notepad-plus-plus/notepad-plus-plus#3014]
### Steps to Reproduce the Issue
Open up Notepad++ after installing the 7.3.3 version.
Read the changelog, then close it.
Open another document.
Close NP++.
Open it again.
You will find the changelog to be open again in a separate tab.

### Expected Behavior
The changelog should not open again after you closed it for the first time after updating.

I'm not sure if this is related to the 64-bit version, as I made the switch from 32-bit to 64-bit with the 7.3.3 update. So this might have happened on earlier releases of the 64-bit variant as well. It just never happened to me with the 32-bit variant.
I did remove my custom settings with the Uninstaller before installing the new version.

**Comment by dail8859** [comment]
Duplicate of #2979 and #2896.

See #2896 for a fix.

**Comment by strollingHeifer** [comment]
I'm sorry. I did search for it before creating this issue. But I only looked for issues containing "changelog" instead "change.log". Thanks for the quick respond though.
