### ISSUE TITLE
View is not maintained when toggling between different tabs with word wrap eanbled

### ISSUE THREAD

**Issue by fstellari** [notepad-plus-plus/notepad-plus-plus#3015]
### Description of the Issue

This appears a regression since NPP 7.3.
"Word wrap" needs to be set.
The text of a long file gets scrolled when switching to a different tab and then back.
[This was originally erroneously associated to AutoSave plugin when the option to save all files was selected since the plugin needs to switch tabs to perform some operations.]

### Steps to Reproduce the Issue

1.  Enable word wrap
2.  Open a first tab with enough text to exceed what can be displayed in a single view
3.  Scroll to the very bottom/end
4.  Switch momentarily to a different tab
5. Switch back to the previous tab
6. Observe that now the view show the content shifted so that the last lines are not visible

### Expected Behavior

The content of the tab should not scroll when switching among the tabs

### Actual Behavior

The content of the tab is scrolled when switching among the tabs

**Comment by mikhoul** [comment]
Just comment  to follow this issue to see when this annoying bug will be fixed. 

Regards :octocat:

**Comment by mikhoul** [comment]
@fstellari   You were right when you said it could be a bug from Scintilla.

I was switching from tab to tab in NP++ and the content shifted in the tab where I was at the bottom of the text/code. :cry: 

I was not knowing what was Scintilla but I've googled to learn about this component and found that the bug happen sadly in plain Scintilla editor with the February release here:  http://www.scintilla.org/Sc373.exe

**I've already opened a bug in Scintilla tracker on Sourceforge:** https://sourceforge.net/p/scintilla/bugs/1921/

Regards ! :octocat:

**Comment by MetaChuh** [comment]
please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins if you update from version 7.5.9 or below.
if your issue still persists, and it is still of relevance, please feel free to file a new issue as easy to understand and reproducible as possible.

thank you for your help and best regards.
