### ISSUE TITLE
Regression: Tab reordering not working

### ISSUE THREAD

**Issue by SinghRajenM** [notepad-plus-plus/notepad-plus-plus#3016]
### Description of the Issue

In latest version tab reordering is not working
### Steps to Reproduce the Issue

1. Open NPP and open few documents or create empty files
2. Enable multiple tab (Settings->preferences->General ->Tab bar -> check multiline)
3. Now try to reorder tabs (try to drag somewhere)

### Expected Behavior

Tab should be reordered based on drag n drop position.

### Actual Behavior

Tab reordering is not happening.

### Debug Information

Notepad++ v7.3.3   (32-bit)
Build time : Mar 10 2017 - 21:22:12
Path : F:\VS_Projects\DevBuild\PowerEditor\bin\notepad++.exe
Admin mode : OFF
Local Conf mode : ON
OS : Windows 10 (64-bit)
Plugins : DSpellCheck2.dll mimeTools.dll NppConverter.dll NppExport.dll PluginManager.dll 

**In V7.3.2 reordering is working properly**
I'm not sure  why condition in tabbar.cpp at line 579 is changed from `if (_doDragNDrop)` to `if (_doDragNDrop && !isMultiLine())`.

**Comment by MAPJe71** [comment]
See also commits [e1125f0](https://github.com/notepad-plus-plus/notepad-plus-plus/commit/e1125f0bbc6632f037c7511368c01e55bfaa447e) and [9967c59](https://github.com/notepad-plus-plus/notepad-plus-plus/commit/9967c59912a05bfac57854e583d573877fdcb787).

**Comment by rddim** [comment]
As a user, I don't like this way of tab reordering - If I want to reorder some tabs, I must to disable multi-line, to reorder them and after that to enable multi-line again if I want to have fast access to them?!? What about if I have 50 tabs and want No.38 to be No.8?

**Comment by AngryGamer** [comment]
As a user of the multi-line feature, I can tell you the previous multi-line behavior was far more annoying.

The rows moved around depending on which tab was selected, and this made it hard to keep track of where tabs are. As a consequence, tab reordering was basically broken and near impossible anyway. If you tried to move a tab to a different row, it would rapidly spasm between different rows (since the selected tab's row is always shown at the bottom) and the end position of the moved tab was uncertain and usually random.

The only way to stop selected tabs from moving to the bottom row was to change to the button style, which broke dragging tabs to reorder them.

Perhaps someone can figure out a way to fix dragging tabs with the button style. Alternatively, a more likely and potentially easier solution is to add hotkeys to shift the active/selected tab to the left or right.

**Comment by Archaeopteryx** [comment]
The instable tab order while dragging a tab could be prevented if tab doesn't get shown while being dragged but just an indicator for the drop position (e.g. vertical line between the new adjacent tabs, maybe even with an arrow down on the top).

**Comment by AngryGamer** [comment]
@Archaeopteryx: What do you think of hijacking the **shift+mwheel** hotkey to move tabs? the **ctrl+mwheel** and **ctrl+shift+mwheel** hotkeys are similar to the **shift+mwheel** hotkey anyway.

Compile & try out the changes [#3023](https://github.com/notepad-plus-plus/notepad-plus-plus/pull/3023)

**Comment by speedy1701** [comment]
Hi.

I too would like the feature the way it was in v7.3.2 and prior: selecting mutli-line should not disable drag & drop of tabs.

**Comment by AngryGamer** [comment]
@SinghRajenM @rddim @Archaeopteryx @speedy1701 I may have gotten drag and drop working with the new buttons style.

Compile [PR#3023](https://github.com/notepad-plus-plus/notepad-plus-plus/pull/3023) yourselves, or here's a compiled binary for other people to test.

[notepad++ v7.3.3 (PR3023).zip](https://github.com/notepad-plus-plus/notepad-plus-plus/files/840922/notepad.v7.3.3.PR3023.zip)

**Comment by rddim** [comment]
@AngryGamer Nice job, thank you very much. There is one little thing: It's possible to reorder only the active tab, if I want to move any other I must click once to make it active and 2nd click for move, i.e. it's not activate automatically.

**Comment by AngryGamer** [comment]
@rddim Nice catch! I've updated the [PR#3023](https://github.com/notepad-plus-plus/notepad-plus-plus/pull/3023) with a fix.

[notepad++ v7.3.3 (PR3023).zip](https://github.com/notepad-plus-plus/notepad-plus-plus/files/841285/notepad.v7.3.3.PR3023.zip)

**Comment by AngryGamer** [comment]
fixed. updated attachment.

**Comment by rddim** [comment]
Just perfect, I think that at this point we have fully worked multi-line fix. Thanks

**Comment by SinghRajenM** [comment]
@AngryGamer This is nice PR. I think you should bundle all the commits into single commit. 
You can use --amend switch for commit and -f to rewrite the full branch which will increase the chances of PR acceptance. 
Thank you.

**Comment by AngryGamer** [comment]
@SinghRajenM done, i think.

**Comment by SinghRajenM** [comment]
Fixed
