### ISSUE TITLE
Tabs flickers when reorder and long cursor move when drag it

### ISSUE THREAD

**Issue by rddim** [notepad-plus-plus/notepad-plus-plus#3017]
### Description of the Issue

Tabs flickers when reorder
### Steps to Reproduce the Issue

1. Make 2 file - one with short name and one with long name
2. Try to reorder the short tab
3. When reorder by draging the long tab name, I must to slide the cursor over the whole lenght.

### Actual Behavior

![npp_tab_flickering_and_long_cursor_move](https://cloud.githubusercontent.com/assets/8998791/23810202/46f0a362-05d9-11e7-863c-f4f00118714c.gif)

### Debug Information

Notepad++ v7.3.3   (32-bit)
Build time : Mar  8 2017 - 03:37:37
Path : D:\Install\Office Programs\Notepad++\notepad++.exe
Admin mode : ON
Local Conf mode : ON
OS : Windows 7 (64-bit)
Plugins : ComparePlugin.dll mimeTools.dll NppExport.dll NppHasher.dll NppTextFX.dll PluginManager.dll

**Comment by AngryGamer** [comment]
Dupe [#2771](https://github.com/notepad-plus-plus/notepad-plus-plus/issues/2771)

Proposed fix: [PR#3328](https://github.com/notepad-plus-plus/notepad-plus-plus/pull/3328)
