### ISSUE TITLE
CTRL Horizontal Scrolling Request

### ISSUE THREAD

**Issue by jabcreations** [notepad-plus-plus/notepad-plus-plus#3018]
I'd love to be able to horizontally scroll when scrolling by holding the CTRL key.

Currently while scrolling and holding CTRL the font-size changes. While that is a useful option I don't change the font-size often except from the default of 5px on poorly designed websites. CTRL+Scrollwheel for horizontal scrolling and perhaps migrate font-size to Shift modifier? I don't see any option for the scrollwheel in the Shortcut Mapper.

**Comment by cullub** [comment]
I would also benefit from this every day at work.  How about shift instead of CTRL though?  CTRL-scroll is pretty standard as zoom, whereas shift-scroll is generally horizontal scroll.

**Comment by jabcreations** [comment]
It really should be the modifier key of the _user's choice_, Control for me, Shift for you.

**Comment by MetaChuh** [comment]
please use shift+scrollwheel to scroll horizontally

thank you for your help and best regards.
