### ISSUE TITLE
NPP best but missing some sublime features

### ISSUE THREAD

**Issue by Noitidart** [notepad-plus-plus/notepad-plus-plus#302]
npp is awesome but its missing just a couple things from sublime i really rely on
- is there a way to get the expand selection functionality from sublime to npp?
- also is there a way to get the snippet/template functionality of sublime?
-  is there a way to get shift + arrow key to do the multi cursor (i know with npp we can use alt drag, i was just wondering if there was keyboard functionality)
- the npp function hint feature doesnt work. i do lots of js and wished that featured worked
- jump to matching tag/apostraphe/bracket/etc

**Comment by pnedev** [comment]
> also is there a way to get the snippet/template functionality of sublime?

There are several snippet plugins out there, have you tried one of those? Use Plugin Manager to find them.

> is there a way to get shift + arrow key to do the multi cursor (i know with npp we can use alt drag, i was just wondering if there was keyboard functionality)

Alt + Shift + Arrow does the thing for me. You can check Settings -> Shortcut Mapper for available shortcuts.

> jump to matching tag/apostraphe/bracket/etc

Jump to bracket works - on my setup when the cursor is positioned on a bracket Ctrl + B gets me to the corresponding complementary one. Again, check the shortcuts mapper.

About the matching tags, I think it is not directly supported by N++. Perhaps some plugin out there adds that feature though. You could check XML Tools from Plugin Manager for example.

**Comment by Noitidart** [comment]
Thank you @pnedev !! Those are real cool alt+shift arrow i cant believe i didnt try. Alt+B works awesome!! would be cool if we can get get it working for apostrophe(`'` `"`) and tags! :)

Do you know about fixing up the function hint'er for js?

**Comment by pnedev** [comment]
I'm glad that helps.

> Do you know about fixing up the function hint'er for js?

I don't, sorry.

**Comment by Yaron10** [comment]
Hello Noitidart  and Pavel,

The "HTMLTag Plugin" includes the "Find matching tag" feature.
http://chiselapp.com/user/vor0nwe/repository/npp_htmltag/home

Best regards.

**Comment by Noitidart** [comment]
Thanks @Yaron10  that is absolutely superb!! Are you the yaron from mozillazine? :)

**Comment by Yaron10** [comment]
Yes, I am.
Thanks again for your help yesterday. I'm glad I could reciprocate a bit. :)

**Comment by Noitidart** [comment]
Thanks @Yaron10 ! Ill help you out even more jsctypes is my thing I can write it for you in probably 20min :P Let me know if you need that help. :)

**Comment by Yaron10** [comment]
Thanks! Really kind of you. I'll post later in Mozillazine.
If you like using Toolbar Icons, try the "Customize Toolbar Plugin".
http://sourceforge.net/p/notepad-plus/discussion/482781/thread/535ad817/

Best regards.

**Comment by Noitidart** [comment]
Oh wow this plug in is so badly needed, i badly want to put labels on my buttons do you know how to do that @Yaron10  ?

**Comment by Yaron10** [comment]
Do you mean tooltips?

**Comment by Noitidart** [comment]
Like actual labels below the button, i can never tell which button is for what :(

**Comment by Yaron10** [comment]
I'm going to look for another link. I'll post shortly again.

**Comment by Noitidart** [comment]
Thanks @Yaron10 !

**Comment by Noitidart** [comment]
Actually @Yaron10  please forget that, with CustomizeButton i removed all the buttons im not familiar with, and im not familiar with what i dont use so no need for labels thank you very much though!

Is there a way to make the Edit > Blank Operations > Trim Functions act only the selected text? Right now it trims on whole document :(

**Comment by Yaron10** [comment]
AFAIK, you can't display labels below the buttons.
The tooltips display the command associated with the buttons.

A possible solution would be using clearer and more illustrative buttons.
http://sourceforge.net/p/notepad-plus/discussion/482781/thread/db6db280/
http://sourceforge.net/p/notepad-plus/discussion/482781/thread/dbea5d02/

If you need a specific button, let me know and I'll try working on it.

As for "Blank Operations": I'm not sure. Pavel would know better.

**Comment by Noitidart** [comment]
Thanks @Yaron10  this is so awesome. Lately at my new work we were on linux and i had to use sublime and i realized how awesome npp was and how i cant live without it.

@pnedev  do you know how to make the text functionalities like trim, work only on selection?

**Comment by Yaron10** [comment]
My pleasure. Enjoy NP++.

**Comment by pnedev** [comment]
> do you know how to make the text functionalities like trim, work only on selection?

Hm, I don't think that's possible. You'll need to do regular search and replace on selection to accomplish that.

**Comment by Noitidart** [comment]
Aw dang I think ill try to write some plugins.

Also the ctrl+alt+b expands selection only if on bracket which is a bit not awesome :( (minor issue: also it includes the bracket even though it says it only gets whats in between)

**Comment by Yaron10** [comment]
@Noitidart, With your speed and prolificacy, I bet the plugin will be ready soon. :)
Just noticed you got a new job. Best of luck.

**Comment by Noitidart** [comment]
Haha thanks @Yaron10 but im so busy with so many other projects I have little time to get into other stuff :( Thanks though for the faith! And the luck on the job! :)

**Comment by Yaron10** [comment]
Great. :)

**Comment by guy038** [comment]
Hi, **Noitidart**,

Indeed, the N++ **Blank** Operations, logically, work on the **totality** of the current file !

However, if you like to delete leading and/or trailing **horizontal blanks** characters, as spaces ( **\x20** ), tabulations ( **\x09** ) and the **No Break space** character ( **\xa0** ), _on selection ONLY_, use the **\h** escape sequence and follow these few steps below :

- *FIRST*, create a **selection** of the lines, where you want to apply the **trim** operation

- Open the Replace dialog ( **CTRL + H** )

- Enter the SEARCH regex `\h+$` for *trailing* blanks, `^\h+` for *leading* blanks and `^\h+|\h+$` for both

- Leave the REPLACE field **empty**

- Check the **In selection** option

- Click on the **Replace All** button

Et voilà !

Best regards,

guy038

**P.S**. : You need an N++ release,  **>= v6.0**, which uses the new **Boost C++ Regex** library, very similar to **PCRE** !

**Comment by Noitidart** [comment]
@guy038  thank you very very much for that info!! Is there any chance npp+ can incorporate this into their own blank operations? that would be absolutely superb as im not finding the time to learn then write plugin :(

**Comment by Noitidart** [comment]
btw i gave up on sublime, i got wine and installed npp and back to my super fast regular flow :)

just wish npp had those expand selection functionalities

**Comment by guy038** [comment]
Hello **Noitidart**

Thanks to **Don Ho**, we have, from now on, a **nice meeting** place for the **N++ community** ! Just follow this link, below :

https://notepad-plus-plus.org/community/topic/2/welcome-to-notepad-community

The **home** forum place can be found at :

https://notepad-plus-plus.org/community/

So, to find my **next** reply to you, just click on the link below :-))

https://notepad-plus-plus.org/community/topic/77/blank-trim-operations-on-a-text-selection-only

Cheers,

guy038

**Comment by i-cant-git** [comment]
Is there a way to maintain Cursor Position over multiple lines after pressing <kbd>Alt+Shift+Up</kbd>?

Because when I press that keyboard shortcut 4 times (it chooses 4 lines), if I press Left arrow, it loses all cursor positions and chooses 1 line only.

**Comment by MetaChuh** [comment]
closed due to inactivity (3y)
