### ISSUE TITLE
If saved to USB HDD/stick, 'Remember last used directory' to save files blocks device removal until N++ closed

### ISSUE THREAD

**Issue by Archaeopteryx** [notepad-plus-plus/notepad-plus-plus#3020]
Notepad++ 7.3.3 (also with 7.3.2; hadn't used that option before) on Windows 8.1

### Description of the Issue
If one saved a new file to HDD connected via USB and has Settings > Preferences > Default Directory set, the option 'Remember last used directory' will block the removal of the USB device using the Windows 'safe unplug' dialog after one has saved a file to it and closed it in Notepad++.

### Steps to Reproduce the Issue
1. Connect a removable device to the computer.
2. Set Settings > Preferences > Default Directory to 'Remember last used directory' ('Use new style save dialog' is checked and unchanged, 'Open All Files of Folder ...' is unchecked)
3. Hit Ctrl + N to create a new file.
4. Type something in it.
5. Save the file to a location on the USB device.
6. Close the file.
7. Use the 'Safe unplug' dialog from the icon in Windows' info try to try to safely remove the USB device without dataloss.

### Expected Behavior
Message that USB device can be unplugged.

### Actual Behavior
Message that USB device is in use (even after repeated triggering of that dialog).

### Debug Information
Notepad++ v7.3.3   (32-bit)
Build time : Mar  8 2017 - 03:37:37
Path : C:\Program Files (x86)\Programmierung\Editoren\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 8.1 (64-bit)
Plugins : mimeTools.dll NppConverter.dll NppExport.dll NppFTP.dll PluginManager.dll

**Comment by MetaChuh** [comment]
please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins if you update from version 7.5.9 or below.
if your issue still persists, and it is still of relevance, please feel free to file a new issue as easy to understand and reproducible as possible.

thank you for your help and best regards.

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
(no extra account is needed, just use your github account to sign in)
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)
