### ISSUE TITLE
Notepad v7.3.3 problem after clean installation on Windows 10 64-bit (latest version)

### ISSUE THREAD

**Issue by gzu88bv** [notepad-plus-plus/notepad-plus-plus#3022]
This problem can be reproduced ever since your version 7.3.1.

Enclosed screen shots are proof when I click the notepad start button
and I cannot figure out how to solve it.

Please advise. Thank you.

![notepad_01](https://cloud.githubusercontent.com/assets/26356673/23829955/32528250-0731-11e7-9a7b-92822ff110be.png)
![notepad_02](https://cloud.githubusercontent.com/assets/26356673/23829956/32529556-0731-11e7-82f3-49f3fa3ac71a.png)
![notepad_03](https://cloud.githubusercontent.com/assets/26356673/23829957/32531fda-0731-11e7-9639-1100941ac930.png)

**Comment by MrJithil** [comment]
Your app data files are missing. Extract and paste the attached xml files in to below location
* C:\Users\<your user name>\AppData\Roaming\Notepad++

**Comment by gzu88bv** [comment]
Dear Sir,

Thank you very much for your fast reply.

The workaround works, but I assume that you will go back to the initial 
installation procedure
in one of your next updates again, or not?
I force all my app installations ever since to C:\Programs (x86) and I 
did not recognize any
notepad directories that you mentioned below for present version 7.3.3. 
So I copied the attached
files into the root of my forced notepad directory.

Until v7.3.1 I also did receive a reduced page after installation, that 
I could even resize to my needs.
But now with the present version every time I start it, the previously 
resized page now appears as
a full page and I do not know where to fix that in your program.

Thanks again and have a good day,
Hans Meier


------ Originalnachricht ------
Von: "MrJithil" <notifications@github.com>
An: "notepad-plus-plus/notepad-plus-plus" 
<notepad-plus-plus@noreply.github.com>
Cc: "gzu88bv" <suizo_at_large@bluewin.ch>; "Author" 
<author@noreply.github.com>
Gesendet: 12.03.2017 19:53:42
Betreff: Re: [notepad-plus-plus/notepad-plus-plus] Notepad v7.3.3 
problem after clean installation on Windows 10 64-bit (latest version) 
(#3022)

**Comment by MetaChuh** [comment]
please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins if you update from version 7.5.9 or below.
if your issue still persists, and it is still of relevance, please feel free to file a new issue as easy to understand and reproducible as possible.

thank you for your help and best regards.
