### ISSUE TITLE
[Feature] [Context menu] Open directory as new "Folder as workspace" (as Project)

### ISSUE THREAD

**Issue by Avaray** [notepad-plus-plus/notepad-plus-plus#3028]
Context menu on folder or in folder's background > Open as new "Folder as workspace" (name it whatever you like; I will name it "Open as new project". Yes - it would be nice to have Projects, like in every modern editors).
It will open that folder in notepad++ as new instance of app, without files that are opened in other instances.
And project file will be automatically generated in that directory.

My feature is related to this:
https://github.com/notepad-plus-plus/notepad-plus-plus/issues/1646

**Comment by rddim** [comment]
You have projects in `View` > `Project` but I'm not sure is that the answer for your feature request.

**Comment by Avaray** [comment]
I know about workspaces.
I want to see it automated, modern, user-friendly... and would be nice to have some additional command line options.

**Comment by ArkadiuszMichalski** [comment]
@Avaray You can use Folder as Workspace future (for example by dragging a folder) or use this future via `-openFoldersAsWorkspace` argument. If necessary, you can manually add the appropriate entries in the system registry to have it at hand.
