### ISSUE TITLE
[Feature] Opened Files History Panel

### ISSUE THREAD

**Issue by Stretto** [notepad-plus-plus/notepad-plus-plus#3035]
It would be nice if we could have a complete history of all the opened files(clearable, of course, and probably partially(say, after one month or individuals)).

The recent files list is good but I tend to open a lot of small files often and the important files I am after get lost in the noise, so it is relatively useless. Having a panel like the documents panel but for all previously opened files so I can search for them rather than having to search the HD would be very useful to me and, I'm sure, others.

e.g.,

1. Every opened file is added to a history log, if it already exists in the log, it is removed first. 
2. The date is recorded with the file name and path.
3. The document switcher panel(as a "selectable option") or a new opened file history panel gives a list of all the previously opened files which can be sorted by date, name, etc.
4. One can remove entries individually(multiselect) or past some day. Simply deletes them from the opened file log.

Shouldn't be too hard to add, right? ;) If I knew how to create a plugin, I'd do it...

In fact, It would be nice to be able to group them by categories(record the category(e.g., /Motorbikes/TR432/Repairs/), if any, along with the name, date, etc).

I use notepad++ a lot(thanks for the hard work!) and usually use it for notes on many things. Being able to quickly recall those files would be useful instead of having to hunt them down(they are organized on the HD but still a bit of work). If one could make a hierarchy of files it would be easy to access them.

Thanks...

**Comment by MetaChuh** [comment]
please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins if you update from version 7.5.9 or below.
if your issue still persists, and it is still of relevance, please feel free to file a new issue as easy to understand and reproducible as possible.

thank you for your help and best regards.

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
(no extra account is needed, just use your github account to sign in)
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)
