### ISSUE TITLE
Restore -quitOnEmpty command line parameter

### ISSUE THREAD

**Issue by bavis-m** [notepad-plus-plus/notepad-plus-plus#3038]
### Description of the Issue
I want the option to be able to change the quitOnEmpty/Quit on Close Last Tab option on a per-execution basis. I use -quitOnEmpty when invoking Notepad++ as my git commit message editor (along with other command line flags that control program lifetime/behavior such as -multiInst -notabbar -nosession -noPlugin) but not to quit on empty when running the program as my usual text editor. Since this is a flag controlling program lifetime that fits in with the other programmatic flags that do the same (see above) I don't think it should belong to global user configuration (or at the very least, it should be toggle-able as a separate command line param that overrides the global configuration).

### Steps to Reproduce the Issue
1. Update to latest Notead++ version (7.3.2)
2. -quitOnEmpty flag no longer works

### Expected Behavior
Program should quit when the last tab is closed and -quitOnEmpty has been specified for this invocation.

### Actual Behavior
Program attempts to load a file called "-quitOnEmpty" (and pops a dialog when that file cannot be found). Program no longer quits when the last tab is closed

### Debug Information
Notepad++ v7.3.2   (32-bit)
Build time : Feb 12 2017 - 23:15:39
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10 (64-bit)
Plugins : none

**Comment by MetaChuh** [comment]
please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins if you update from version 7.5.9 or below.
if your issue still persists, and it is still of relevance, please feel free to file a new issue as easy to understand and reproducible as possible.

thank you for your help and best regards.

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
(no extra account is needed, just use your github account to sign in)
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)
