### ISSUE TITLE
Keyboard Macro's inserting text in the wrong place

### ISSUE THREAD

**Issue by grahamegrieve** [notepad-plus-plus/notepad-plus-plus#304]
Over the last few versions, keyboard macros - which used to be bullet proof - have become increasingly unreliable. A specific issue to report:

if you type the character " while recording a macro, you will get two "" inserted. When you replay the macro at a different location, the second " will be inserted at the *same place* as when the macro was first executed, not next to the one added during the macro execution

**Comment by grahamegrieve** [comment]
It would be really nice to have an option to automatically auto-insert while recording a macro

**Comment by maesfreek** [comment]
Noticed this problem too, it occurs for every auto-insert character. 
*Temporary solution*: when auto-insert is turned off **when creating the macro** it works okay, even when you turn auto-insert back on afterwards!

**Comment by lombas** [comment]
This bug is still present on version 6.8.1.  Very disappointing when trying to use the macro function.

Nevertheless, the app is great. :-)
