### ISSUE TITLE
[Feature Request] Search bar

### ISSUE THREAD

**Issue by zeufparis** [notepad-plus-plus/notepad-plus-plus#3040]
Since I met it (Notepad+) my life changed ! :)

Anyway, is it possible to add a search bar on the top left as I worked on .PHP files around 2000 lines (I know that is bad but it is my bad) ?

Thank you !!

**Comment by cmeriaux** [comment]
You can use "incremental search" : it's a search bar on the bottom of the main view.

You can also try this plugin : https://sourceforge.net/projects/nppmenusearch/?SetFreedomCookie 
It's a search bar to search among the function.

**Comment by zeufparis** [comment]
Thank you so much Christophe !
The "Incremental Search" (Recherche > Recherche Incrémentielle - CTRL + ALT + I)  is exactly what I meant....
And so sorry to be so lazy ....
