### ISSUE TITLE
Include NppExport in x64 version

### ISSUE THREAD

**Issue by Smile4ever** [notepad-plus-plus/notepad-plus-plus#3042]
Hi. I have found https://github.com/chcg/NPP_ExportPlugin/releases which has an x64 version of NppExport. Can this be included in official Notepad++ x64 builds?

**Comment by MetaChuh** [comment]
plugins can be downloaded via plugins admin of recent versions.

please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins if you update from version 7.5.9 or below.

thank you for your help and best regards.

**Comment by Smile4ever** [comment]
To summarize, NppExport is now available in the Plugin Manager for x64.
