### ISSUE TITLE
SREC highlighting not working - 7.3.3 x64

### ISSUE THREAD

**Issue by mzanders** [notepad-plus-plus/notepad-plus-plus#3043]
### Description of the Issue
Field highlighting for Motorola S-Rec files (added in 7.3.3) doesn't work.

### Steps to Reproduce the Issue
Save the example from https://sourceforge.net/p/scintilla/feature-requests/1091/ and repeated below as example.mot:

> S0040000FB00
> S10500004D5459
> S20600004D5468F0
> S30A00004D54686400110077
> S5030003F9
> S604000003F8
> S70500041234B0
> S804000412E5
> S9030004F8
> 
> S403ABCD84
> S0060000FB00
> S0040000FB001234
> S10500004D545A

Open the file in a fresh 7.3.3 x64 installation. Verify it is correctly interpreted as "Motorola S-Record binary data" in the status bar.

### Expected Behavior
Different fields of the file format highlighted. Similar to output of SciTE. See attached screenshot.

### Actual Behavior
All lines in std text, black. See attached screenshot.

### Debug Information
Notepad++ v7.3.3   (64-bit)
Build time : Mar  8 2017 - 03:39:58
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 7 (64-bit)
Plugins : mimeTools.dll NppConverter.dll 

![nppp_srec](https://cloud.githubusercontent.com/assets/16673350/23943448/d09d6d22-096f-11e7-8008-ca2792dd070c.png)

![scite_srec](https://cloud.githubusercontent.com/assets/16673350/23943454/d4214a68-096f-11e7-9979-0e422989e4e3.png)

**Comment by dail8859** [comment]
You probably have to delete your langs.xml and styles.xml located in your `%APPDATA%` directory. Keep in mind this will delete any custom word lists or styles you've set previously.
