### ISSUE TITLE
Even though it's not supposed to Auto Changing words

### ISSUE THREAD

**Issue by cassiereroni** [notepad-plus-plus/notepad-plus-plus#3047]
I know notepad++ doesn't autochange words but it keep happening to me.  I have no plugins so that is not the issue.  Every time I try to type in "Autopsy" it changes to "Autopay".  I can not get it to accept "Autopsy" no matter what I do. 

### Steps to Reproduce the Issue
1. Typed in Autopsy
2. Moved to next line
3. Word shows as Autopay

### Expected Behavior
Expected the word Autopsy to stay in the file and not change to Autopay

### Actual Behavior
Word Autopsy changed to Autopay.  It will not accept Autopsy

### Debug Information
Notepad++ v7.3.2   (64-bit)
Build time : Feb 12 2017 - 23:17:55
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10 (64-bit)
Plugins : mimeTools.dll NppConverter.dll

[notepad](https://cloud.githubusercontent.com/assets/26440887/23961538/3c493a66-0979-11e7-9594-15881b6abeb6.JPG)

**Comment by MetaChuh** [comment]
please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins if you update from version 7.5.9 or below.
if your issue still persists, and it is still of relevance, please feel free to file a new issue as easy to understand and reproducible as possible.

thank you for your help and best regards.

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
(no extra account is needed, just use your github account to sign in)
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)
