### ISSUE TITLE
Sometimes lose 'open-tabs' documents, and the 'recent documents' additions for the preceding session

### ISSUE THREAD

**Issue by maemmott** [notepad-plus-plus/notepad-plus-plus#3051]
### Description of the Issue
I've recently noticed that when I stared Notepad++ again, I don't always get a populated tab-collection of 'the documents I had open at close' [which is a pity, because I've come to rely on it].
At first, I thought 'this is a change between versions' [I first noticed it after installing (I think, v7.1)]
I particularly noticed that it happened after I allowed Windows Shutdown to close the notepad++ session for me.  [I have, for a long time, had the rather old-school habit, of shutting down all my apps by hand, before issuing Windows shutdown; it leads to fewer trip-ups, and stops my losing unsaved documents]
Having just tried to duplicate this, though, I found that shutdown doesn't reliably cause it.
I routinely run my PC by hibernating one session, repeatedly, for up to a fortnight.
In the last couple of days (having installed 7.3.3), I notice that sometimes it _doesn't_ have this issue, although for a couple of weeks beforehand, it seemed to show it every time I closed and restarted notepad++

### Steps to Reproduce the Issue

1. use notepad++ all day; opening several docs in the process
2. close down for the day (this might mean hibernating, might mean shutting Windows down)
3. in next Windows session, run notepad++ again.

### Expected Behavior

notepad++ to open with the same set of tabs it had in view before closing

### Actual Behavior

notepad++ opened with only the 'I'm just beginning', unsaved, new document tab open

### Debug Information

Notepad++ v7.3.3   (32-bit)
Build time : Mar  8 2017 - 03:37:37
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10 (64-bit)
Plugins : NppTextFX.dll PluginManager.dll XMLTools.dll

**Comment by MetaChuh** [comment]
please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins if you update from version 7.5.9 or below.
if your issue still persists, and it is still of relevance to you, please feel free to file a new issue as easy to understand and reproducible as possible.

thank you for your help and best regards.

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
(no extra account is needed, just use your github account to sign in)
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)

**Comment by donho** [comment]
Fix by https://github.com/notepad-plus-plus/notepad-plus-plus/commit/6000f3bb21a42a4d28d068617e0dc642ef739b26
