### ISSUE TITLE
Line-height different between vertical views

### ISSUE THREAD

**Issue by JaredEStoddard** [notepad-plus-plus/notepad-plus-plus#3052]
The line height (spacing) in vertical Views appears to be different (in this case, 22px left, 23px right).  Makes it difficult to compare.

![image1](https://cloud.githubusercontent.com/assets/15371483/24016425/b1aecbf8-0a51-11e7-97d2-a4a7985885f2.png)

**Comment by dail8859** [comment]
Please follow the provided template because there is not enough information to go on. Also make sure your zoom levels are the same for each view.

**Comment by JaredEStoddard** [comment]
Zoom was the problem.  I hadn’t realized I had zoomed [out] in the main window – so when I “Clone[ed] to other View” I expected the current environment/settings to apply to that view as well.  Perhaps this should be the default behavior?  Anyway, problem solved.  Thanks.

**Comment by dail8859** [comment]
> Perhaps this should be the default behavior?

Storing zoom levels per document (as opposed to per view) would probably cause more confusion. Glad to hear it is resolved.

**Comment by JaredEStoddard** [comment]
I didn’t mean to imply a zoom per document – would be a nightmare in a MDI…  My suggestion was that a newly created view should (arguably) assume the settings of the current view unless otherwise specified (after-the-fact).  For example, if I am zoomed at 80% in a single main view and spawn a new view (e.g., “Clone/Copy to new View”) – should it not default to 80% (current) rather than 100%?

 

Regardless, *brilliant* product.  I’ve been a developer for 30+ years, and was a long-time user of TextPad.  A number of years ago I found that it couldn’t keep up and was panicked to find a replacement:  NPP has become my go-to editor.  LOVE IT!  Thanks!
