### ISSUE TITLE
Deletes content of the file when converting ANSI to UTF-8

### ISSUE THREAD

**Issue by ilhanyumer** [notepad-plus-plus/notepad-plus-plus#3054]
### Description of the Issue
**This bug exists for at least few years**. And it is the most annoying bug of Notepad++. When I convert the encoding to UTF-8 (without BOM) it suddenly removes all content of the file. And it does not left undo and rendo. The worst part is if this usse appears not during the convertion but during the saving.

### Steps to Reproduce the Issue

1. Open a file which is ANSI
2. Add some UTF-8 content, like Ü, Ğ, Ö, İ etc
3. Convert the file to UTF-8

### Expected Behavior
Now the file is UTF-8.

### Actual Behavior
Now the file is empty.

### Debug Information
Notepad++ v7.3.2   (64-bit)
Build time : Feb 12 2017 - 23:17:55
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : ON
Local Conf mode : OFF
OS : Windows 8.1 (64-bit)
Plugins : mimeTools.dll NppConverter.dll 

I have encountered this usse when using Windows 7, Windows 10, Turkish Windows, English Windows, different Notepad++ versions.

I cannot reproduce the issue. I don't remember what number of new Unicode characters in what order I have entered. May be I need to restart the Notepad++, may be I need to move between few tabs. I have never been able to reproduce this bug.

**Comment by clb92** [comment]
Same problem here.
My temporary solution is to make a new file (don't save it), copy all the text over to it, convert it to UTF-8 there, change the original file to UTF-8 (not convert), paste the converted text from the new unsaved file back to the original, save it. Now it should be UTF-8.

**Comment by MetaChuh** [comment]
please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins if you update from version 7.5.9 or below.
if your issue still persists, and it is still of relevance, please feel free to file a new issue as easy to understand and reproducible as possible.

thank you for your help and best regards.

**Comment by clb92** [comment]
For what it's worth, I haven't experienced this bug since I commented back in 2017.

**Comment by rafaeldonado** [comment]
Same problem, last version here. It just happens with some files.

Notepad++ v7.7.1   (32-bit)
Build time : Jun 16 2019 - 21:14:50
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10 (64-bit)
Plugins : mimeTools.dll NppConverter.dll NppExport.dll

**Comment by Codeberg-AsGithubAlternative-buhtz** [comment]
I still can reproduce this error with Notepad++ 7.9.5 on Windows 10.

It is unclear for me why the Issue was not reopend after @clb92 's comment two years ago?!

**Comment by miika-prose** [comment]
Still relevant
Notepad++ 8.6.8, Win 11
Why this is closed?

**Comment by rportron** [comment]
> Still relevant Notepad++ 8.6.8, Win 11 Why this is closed?

There is a [new issue opened](https://github.com/notepad-plus-plus/notepad-plus-plus/issues/15324) about that strange behaviour.
