### ISSUE TITLE
Cannot drag and drop tabs since version (v7.3.3)

### ISSUE THREAD

**Issue by emi-le** [notepad-plus-plus/notepad-plus-plus#3055]
### Description of the Issue
Since updating to version v7.3.3. I cannot drag and drop the tabs anymore.
The check-box in the settings to disable the drag and drop option is not activated. (German display message: "Tabs nicht mit der Maus verschiebbar"). See screenshot. 

![2017-03-17_10h12_02](https://cloud.githubusercontent.com/assets/18303829/24036559/417015be-0afa-11e7-92b7-89f84e5097b1.png)

_activating - trying again - deactivating - trying again_ it had no effect.

### Steps to Reproduce the Issue
1.  Klick on a tab and try to drag it to another position

### Expected Behavior
it works

### Actual Behavior
it doesn't work. Tab is not moved at all.

### Debug Information
Notepad++ v7.3.3   (32-bit)
Build time : Mar  8 2017 - 03:37:37
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10 (64-bit)
Plugins : ComparePlugin.dll mimeTools.dll NppConverter.dll NppExport.dll NppTextFX.dll PluginManager.dll XMLTools.dll

**Comment by Diklabyte** [comment]
A little addition to this:
This Bug is only to reproduce if "Multi-Line" is also activated.

**Comment by TazzyT** [comment]
I am having the same issue and frankly its driving me nuts.  Will there be a patch with Diklabyte's fix coming soon?
If not do I need anything special to open that file and correct?
Thank you!

**Comment by Diklabyte** [comment]
@TazzyT First, I don't made this fix. @AngryGamer does this ;)
I guess the new Release, with this patch, will coming soon. I can't say when exactly.
For now, you can deselect the "Multi-Line" option, to reorganize your tabs.

**Comment by TazzyT** [comment]
@Diklabyte Ah yes, I didn't catch the name when I viewed the other page.  Thank you for pointing that out and crediting the correct person! 
I will turn off multi-line for now and just "try" to limit how many tabs I have open at once.  Hope it gets patched soon.   ;-)
Have a great weekend!

**Comment by gbutiri** [comment]
Went back to 6.9.2 However, the links on their site are backwards for 6.9.2 and 6.9.1. There were too many other issues I found with it as well. The shortest road is the one best known.

**Comment by cmeriaux** [comment]
It's fixed.  Try out the nightly build if you can't wait for the next
release.

**Comment by shubnigg** [comment]
Hello, Cannot drop and drag from search software (http://www.sowsoft.com/search.htm - freeware) to notpad++ v7.5 (64bits)

Notepad++ v7.5   (64-bit)
Build time : Aug 15 2017 - 23:06:39
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10 (64-bit)
Plugins : ComparePlugin.dll mimeTools.dll NppConverter.dll

**Comment by MetaChuh** [comment]
please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins if you update from version 7.5.9 or below.
if your issue still persists, and it is still of relevance, please feel free to file a new issue as easy to understand and reproducible as possible.

thank you for your help and best regards.

**Comment by shubnigg** [comment]
Hello, still cannot drop and drag search results from search software (http://www.sowsoft.com/search.htm - freeware v6.8.1) to notpad++ v7.6.6 (64bits)

Notepad++ v7.6.6   (64-bit)
Build time : Apr  3 2019 - 23:52:32
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10 (64-bit)
Plugins : mimeTools.dll NppConverter.dll

**Comment by SamBrigges** [comment]
Solution : on Windows 10 (had this issue even with v7.7)

step 1 : click windows **start button** , find Notepad++, 
step 2 : right click and select "more" and then select "**Open file location**"
step 3 : right click the shortcut of Notepad++ and select **properties**
step 4 : **clear** textbox in front of " **Start in:** "
step 5 : hit Apply 

it worked for me, hope it helps!
