### ISSUE TITLE
Replacing multiple highlighted text using 'in selection' does not work

### ISSUE THREAD

**Issue by u01jmg3** [notepad-plus-plus/notepad-plus-plus#3060]
### Description of the Issue
If I have `Multiple-Editing Settings` enabled and highlight multiple text (using <kbd>Ctrl</kbd> + Mouse click/selection) and then use the replace functionality with 'In selection' ticked, only the final highlighted text is replaced with the replacement text.

### Steps to Reproduce the Issue
![demo](https://cloud.githubusercontent.com/assets/1266205/24053192/2268d2ec-0b30-11e7-9c2d-bf34744ebb17.gif)

### Expected Behaviour
- All highlighted text should be replaced with the replacement text as 'In selection' has been ticked.

### Actual Behaviour
- Only the final highlighted text is replaced.

**Comment by dail8859** [comment]
The `In Selection` option is intended to be used only over a single contiguous section but I do understand the confusion and agree these types of situations could be better handled.

**Comment by notdodgeball** [comment]
per #7537, this issue should be now closed as fixed. Unless there is proper demand for a "In selection" implementation when a multiple selection is executed

**Comment by u01jmg3** [comment]
I wouldn't say this is fixed. The option has just been disabled.
