### ISSUE TITLE
[BUG Report]  NP++ (x86) issues with Config stuff still reading/writing to AppData even doLocalConf.xml is present.

### ISSUE THREAD

**Issue by MelchiorGaspar** [notepad-plus-plus/notepad-plus-plus#3065]
### Description of the Issue
I have been having an issue for a idk a couple of years
or so that is when I upgraded from using Windows XP to using Windows 7
 and wanted to finally report it...

I have an issue with NP++ still writing/reading config stuff to the
AppData folder even though I have it setup not to do this during install/updates.. 
ie.  doLocalConf.xml  is present

I have found the only workaround was to set the compatibility mode to
Windows XP SP3...   then it works right... 

however as updates progress using compatibility mode will become more... 
troublesome such as the NP++ main program update feature does not work
in the 32bit version because the program thinks its running on ok do to the
above workaround... 

### Steps to Reproduce the Issue
n/a I guess

### Expected Behavior
NP++ should write and read all config files and other files from
C:\Program Files (x86)\Notepad++\  
plus all sub folders for plugins and their config files when doLocalConf.xml is present in the main program folder...

### Actual Behavior
mentioned in above description.

### Debug Information
Notepad++ v7.3.3   (32-bit)
Build time : Mar  8 2017 - 03:37:37
Path : C:\Program Files (x86)\Notepad++\notepad++.exe

Admin mode : OFF              <-- While I do not have this enabled in the compatibility tab... 
                                                  I do have full permissions on the Program Files folder(s) 
                                                    so like in the in days...

Local Conf mode : ON

OS : Windows XP (64-bit)    <-- This is do to the use of compatibility mode as a workaround, I am using 
                                                   using Windows 7 Ultimate (64-bit)

Plugins : DSpellCheck2.dll mimeTools.dll NppConverter.dll NppCrypt.dll NppExec.dll NppExport.dll NppFTP.dll NPPJSONViewer-win32.dll PluginManager.dll ReloadButton.dll SecurePad.dll SpellChecker.dll 

n/a at this time..

**Comment by MelchiorGaspar** [comment]
I don't know if it works or not but or if its allowed... but.. bump..? ;) 
I do so because its been since March since I posted this, and no dev has seen it or replied :/

**Comment by MelchiorGaspar** [comment]
ok I'm gonna bump this again.. 
no one has replied to this ticket,
since I created it back in March 2017....

**Comment by MelchiorGaspar** [comment]
my work around was to reinstall NP++(x86) to C:\Notepad++ and then copy all the config data and plugins from the old Program FILES folder to the new location... and it works now...

**Comment by MetaChuh** [comment]
@MelchiorGaspar 

yes, your workaround is the correct way.
 
due to missing user write permissions at `%ProgramFiles%` and `%ProgramFiles(x86)%` notepad++ can not write the config files to these folders.
the newer version installers have the option `don't use %AppData%` greyed out for this reason, as soon as it detects, that it will be installed at a program files folder.

sorry for the inconvenience and many thanks for reporting back now.

best regards.
