### ISSUE TITLE
Notepad++ (x86) keeps being shipped with an outdated Plugin Manager (v1.3.5)(x86)

### ISSUE THREAD

**Issue by MelchiorGaspar** [notepad-plus-plus/notepad-plus-plus#3066]
### Description of the Issue
Plugin Manager 1.3.5 (32-bit x86 only)

I wanted to ask why an outdated Plugin Manager is  still being included
with each of your new NP++ updates..

The newest version located
https://github.com/bruderstein/nppPluginManager/releases
is v1.4.3  and the current beta is v1.4.4(pre-release)

### Steps to Reproduce the Issue
n/a

### Expected Behavior
the Plugin Manager included with NPP++ (x86) 
should be updated to v1.4.3 from v1.3.5
and when version v1.4.4 is ready including it for both x86 and x64 builds of NP++ 
please and thanks ;)

### Actual Behavior
n/a

### Debug Information
Notepad++ v7.3.3   (32-bit)
Build time : Mar  8 2017 - 03:37:37
Path : C:\Program Files (x86)\Notepad++\notepad++.exe

Admin mode : OFF              <-- While I do not have this enabled in the compatibility tab... 
                                                  I do have full permissions on the Program Files folder(s) 
                                                    so like in the in days...

Local Conf mode : ON

OS : Windows XP (64-bit)    <-- This is do to the use of compatibility mode as a workaround, I am using 
                                                   using Windows 7 Ultimate (64-bit)

Plugins : DSpellCheck2.dll mimeTools.dll NppConverter.dll NppCrypt.dll NppExec.dll NppExport.dll NppFTP.dll NPPJSONViewer-win32.dll PluginManager.dll ReloadButton.dll SecurePad.dll SpellChecker.dll 

n/a

**Comment by chcg** [comment]
Current version with various fixes and x64 support is https://github.com/bruderstein/nppPluginManager/releases/tag/v1.4.9, but will probably not be bundled with N++ anymore, according to donho.

**Comment by MelchiorGaspar** [comment]
NOT bundled? why on earth would he do that for? its one of NP++ most important things.... :/ 
it would throw a lot of people  a curve ball I guess...

**Comment by chcg** [comment]
Main reason the sponsorship advertisment (used to pay the server) on the PM window.

**Comment by MelchiorGaspar** [comment]
ooh... :/   and Don does not like that for some reason? :/

**Comment by dail8859** [comment]
As of Notepad++ v7.5 the Plugin Manager is no long being shipped with Notepad++. See https://notepad-plus-plus.org/news/notepad-7.5-released.html

All Plugin Manager related issues should be reported to https://github.com/bruderstein/nppPluginManager/issues

**Comment by MelchiorGaspar** [comment]
yeah lol I was doing my update check rounds a little while ago like less then 45 minutes.. sidetracked a lot lol ;) and yeah  I saw the v7.5 UPDATE :D :D lol ;) 
excited... I will manually add it back in for now and scrap it when Don gets HIS OFFICIAL one ready ;)
