### ISSUE TITLE
.\updater\gpup.exe included with NP++ (v7.3.3)(x86) portable build is crashing on plugin updating.

### ISSUE THREAD

**Issue by MelchiorGaspar** [notepad-plus-plus/notepad-plus-plus#3067]
### Description of the Issue
I noticed a second issue with the v7.3.3 release..
.\updater\gpup.exe  v1.3.5.0  285,872 Bytes  is crashing.

included with the (x86) .zip archived version is malfunctioning
it caused a NP++ crash every time when trying to update a couple of
addons..

I had to copy the gpup.exe from my installed NP++ v7.3.3
to my portable copy of NP++ on my USB flash drive..
that worked ie no crashing...
working copy .\updater\gpup.exe v1.4.3 272,896 Bytes

please look into this further for both x86 and x64 
portable builds...

also I use the updated Plugin Manager v1.4.3 (x86) as well...

### Steps to Reproduce the Issue
n/a

### Expected Behavior
gpup.exe should run updating plugins no issues.

so the gpup.exe included with the x86 portable build of NP++
needs to be updated.

### Actual Behavior
see above description.

### Debug Information
Notepad++ v7.3.3 (32-bit)
Build time : Mar 8 2017 - 03:37:37
Path : C:\Program Files (x86)\Notepad++\notepad++.exe

Admin mode : OFF <-- While I do not have this enabled in the compatibility tab...
I do have full permissions on the Program Files folder(s)
so like in the in days...

Local Conf mode : ON

OS : Windows XP (64-bit) <-- This is do to the use of compatibility mode as a workaround, I am using
using Windows 7 Ultimate (64-bit)

Plugins : DSpellCheck2.dll mimeTools.dll NppConverter.dll NppCrypt.dll NppExec.dll NppExport.dll NppFTP.dll NPPJSONViewer-win32.dll PluginManager.dll ReloadButton.dll SecurePad.dll SpellChecker.dll

**Comment by chcg** [comment]
Current version with various fixes and x64 support is https://github.com/bruderstein/nppPluginManager/releases/tag/v1.4.9, but will probably not be bundled with N++ anymore, according to donho.

**Comment by MelchiorGaspar** [comment]
NOT bundled? why on earth would he do that for? its one of NP++ most important things.... :/ 
it would throw a lot of people  a curve ball I guess...

**Comment by chcg** [comment]
See https://notepad-plus-plus.org/community/topic/14315/notepad-7-5-release, PluginManager is no longer part of N++. https://github.com/bruderstein/nppPluginManager/issues is the place to report the problem.

**Comment by MelchiorGaspar** [comment]
now and moving forward..   anyway
but I POSTED HERE because it was part of or at least bundled with NP++..
as I already mentioned above..  This was an issue  with the gpup.exe,
included with the portable/archived version of NP++....

so it might not be relevant anymore...
closing.!
