### ISSUE TITLE
[Feature] Don't halt search for skipped files when using Find in Files

### ISSUE THREAD

**Issue by bladeoflight16** [notepad-plus-plus/notepad-plus-plus#3068]
### Description of the Issue

If a file is "too large" for Notepad++ to search, it pauses the search, immediately opens a dialog with the following text, and waits for the user to press OK:

```
---------------------------
File open problem
---------------------------
File is too big to be opened by Notepad++
---------------------------
OK   
---------------------------
```

It would be very nice if this didn't pause the search. I have a fairly large git repository along with several other binaries (e.g., a large NuGet package) in my project directory, so I run into this fairly regularly. When I need to search *all* files, I have to make sure I do not leave the search unattended; if I do, it will stop in the middle until I come back and press OK.

### Steps to Reproduce the Issue

1. Create a directory and place a few large files in it, along with smaller ones.
2. Open the Find in Files dialog.
3. Type in a term to search for, choose the directory from step 1 as the search Directory, and press Find All.
4. Wait until the dialog pops up.

### Expected Behavior

Search should continue without interaction even after encountering the large files.

### Actual Behavior

Search pops up a dialog and is delayed until user presses OK

### Debug Information

Notepad++ v7.3.3   (32-bit)
Build time : Mar  8 2017 - 03:37:37
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : ON
Local Conf mode : OFF
OS : Windows 7 (64-bit)
Plugins : DSpellCheck2.dll mimeTools.dll NppConverter.dll NppExport.dll NppTextFX.dll PluginManager.dll XMLTools.dll

One option to consider would be to add a "skipped files" box to the search progress dialog. Files could be added as the search goes, and the progress dialog could stay open and require acknowledgement if any files were skipped. This would be the best of both worlds: someone watching closely would be immediately notified of the skip, and someone attending to other tasks wouldn't experience a delay in the completion of the search.

**Comment by bladeoflight16** [comment]
Duplicate of #1889, #2072

Pending PR #4151

**Comment by donho** [comment]
https://github.com/notepad-plus-plus/notepad-plus-plus/commit/cf8ddc18c9833fb8f19df1c44dc769926a274d47
