### ISSUE TITLE
Cython files recognition

### ISSUE THREAD

**Issue by crayxt** [notepad-plus-plus/notepad-plus-plus#3069]
### Description of the Issue
Cython files (.pyx, .pxd and .pxi) are not recognized by npp. The Cython keywords are
actually Python keywords + couple specific ones (cdef, cpdef) and also C types of data
should be highlighted too. I think that scintilla Python lexer supports Cython.

### Steps to Reproduce the Issue
1. Open any Cython file (rename python file *.py to *.pyx)
2. NPP says it is a Normal text file
3. Keyword are not highlighted, etc.

### Actual Behavior
npp is not recognizing cython files.

### Debug Information
None.

https://cython.readthedocs.io/en/latest/src/reference/language_basics.html

**Comment by natschluter** [comment]
Has this been addressed yet?

**Comment by Masud2017** [comment]
Can i make this solution using c or c++?

**Comment by GregoryMorse** [comment]
Python language is not adequate nor is C.  It has a special syntax where although Python is probably a better base, keywords like `cdef` `cpdef` and support for its template `[]` variation and cast variation `<>` are needed.  Raw C code can also appear in comment blocks in a special definition:
```
cdef extern from *:
    """
    """
```

**Comment by sasumner** [comment]
Lexing is done in the Scintilla component.  Until it is added there, nothing can be done in Notepad++.

**Comment by zufuliu** [comment]
Cython lexer is same as Python, and supported by SciTE.
https://sourceforge.net/p/scintilla/scite/ci/default/tree/src/python.properties

**Comment by Sasstraliss** [comment]
What is there left to be done?

**Comment by donho** [comment]
So the only difference between Cython & Python is 3 more keywords with extension pyx ?

**Comment by GregoryMorse** [comment]
It's obviously more than the keywords for example C has operators like ++, --, &&, ||, ? :, * dereference, +=, -=, *=, /=, %=, <<=, >>=, &=, |=, ^=

Comments use // or /*...*/ etc

Python is a base, some special keywords and then a good swath of C is needed
