### ISSUE TITLE
Use UTF-8 for all translation files

### ISSUE THREAD

**Issue by milipili** [notepad-plus-plus/notepad-plus-plus#307]
For simplicity sake, and to avoid encoding issues, all translation files should be re-encoded in UTF-8. Once this issue is resolved, all PR for updating translations must be in UTF-8

**Comment by milipili** [comment]
- [x] `afrikaans.xml` from `iso-8859-2` to `utf-8`
 - [x] `albanian.xml` from `iso-8859-2` to `utf-8`
 - [x] `arabic.xml` from `iso-8859-2` to `utf-8`
 - [x] `aragonese.xml` from `utf-8` to `utf-8`
 - [x] `aranese.xml` from `iso-8859-2` to `utf-8`
 - [x] `azerbaijani.xml` from `utf-8` to `utf-8`
 - [x] `basque.xml` from `ascii` to `utf-8`
 - [x] `belarusian.xml` from `windows-1251` to `utf-8`
 - [x] `bengali.xml` from `utf-8` to `utf-8`
 - [x] `bosnian.xml` from `iso-8859-2` to `utf-8`
 - [x] `brazilian_portuguese.xml` from `ibm855` to `utf-8`
 - [x] `bulgarian.xml` from `windows-1251` to `utf-8`
 - [x] `catalan.xml` from `iso-8859-2` to `utf-8`
 - [x] `chinese.xml` from `big5` to `utf-8`
 - [x] `chineseSimplified.xml` from `gb2312` to `utf-8`
 - [x] `croatian.xml` from `iso-8859-2` to `utf-8`
 - [x] `czech.xml` from `iso-8859-2` to `utf-8`
 - [x] `danish.xml` from `iso-8859-2` to `utf-8`
 - [x] `dutch.xml` from `iso-8859-2` to `utf-8`
 - [x] `english.xml` from `ascii` to `utf-8`
 - [x] `english_customizable.xml` from `ascii` to `utf-8`
 - [x] `esperanto.xml` from `utf-8` to `utf-8`
 - [x] `estonian.xml` from `iso-8859-2` to `utf-8`
 - [x] `extremaduran.xml` from `windows-1251` to `utf-8`
 - [x] `farsi.xml` from `utf-8` to `utf-8`
 - [x] `finnish.xml` from `windows-1255` to `utf-8`
 - [x] `french.xml` from `iso-8859-2` to `utf-8`
 - [x] `friulian.xml` from `iso-8859-2` to `utf-8`
 - [x] `galician.xml` from `windows-1251` to `utf-8`
 - [x] `georgian.xml` from `utf-8` to `utf-8`
 - [x] `german.xml` from `iso-8859-7` to `utf-8`
 - [x] `greek.xml` from `iso-8859-7` to `utf-8`
 - [x] `gujarati.xml` from `utf-8` to `utf-8`
 - [x] `hebrew.xml` from `windows-1255` to `utf-8`
 - [x] `hindi.xml` from `utf-8` to `utf-8`
 - [x] `hungarian.xml` from `utf-8` to `utf-8`
 - [x] `indonesian.xml` from `ascii` to `utf-8`
 - [x] `italian.xml` from `iso-8859-2` to `utf-8`
 - [x] `japanese.xml` from `shift_jis` to `utf-8`
 - [x] `kabyle.xml` from `utf-8` to `utf-8`
 - [x] `kannada.xml` from `utf-8` to `utf-8`
 - [x] `kazakh.xml` from `utf-8` to `utf-8`
 - [x] `korean.xml` from `euc-kr` to `utf-8`
 - [x] `kyrgyz.xml` from `utf-8` to `utf-8`
 - [x] `latvian.xml` from `iso-8859-8` to `utf-8`
 - [x] `ligurian.xml` from `iso-8859-2` to `utf-8`
 - [x] `lithuanian.xml` from `iso-8859-2` to `utf-8`
 - [x] `luxembourgish.xml` from `iso-8859-2` to `utf-8`
 - [x] `macedonian.xml` from `utf-8` to `utf-8`
 - [x] `malay.xml` from `ascii` to `utf-8`
 - [x] `marathi.xml` from `utf-8` to `utf-8`
 - [x] `mongolian.xml` from `utf-8` to `utf-8`
 - [x] `norwegian.xml` from `iso-8859-2` to `utf-8`
 - [x] `nynorsk.xml` from `iso-8859-2` to `utf-8`
 - [x] `occitan.xml` from `iso-8859-2` to `utf-8`
 - [x] `polish.xml` from `iso-8859-2` to `utf-8`
 - [x] `portuguese.xml` from `ibm855` to `utf-8`
 - [x] `romanian.xml` from `iso-8859-2` to `utf-8`
 - [x] `russian.xml` from `windows-1251` to `utf-8`
 - [x] `samogitian.xml` from `ascii` to `utf-8`
 - [x] `sardinian.xml` from `iso-8859-2` to `utf-8`
 - [x] `serbian.xml` from `iso-8859-2` to `utf-8`
 - [x] `serbianCyrillic.xml` from `windows-1251` to `utf-8`
 - [x] `sinhala.xml` from `utf-8` to `utf-8`
 - [x] `slovak.xml` from `utf-8` to `utf-8`
 - [x] `slovenian.xml` from `iso-8859-2` to `utf-8`
 - [x] `spanish.xml` from `iso-8859-2` to `utf-8`
 - [x] `spanish_ar.xml` from `iso-8859-2` to `utf-8`
 - [x] `swedish.xml` from `iso-8859-2` to `utf-8`
 - [x] `tagalog.xml` from `ascii` to `utf-8`
 - [x] `tajikCyrillic.xml` from `utf-8` to `utf-8`
 - [x] `tamil.xml` from `utf-8` to `utf-8`
 - [x] `tatar.xml` from `utf-8` to `utf-8`
 - [x] `telugu.xml` from `utf-8` to `utf-8`
 - [x] `thai.xml` from `tis-620` to `utf-8`
 - [x] `turkish.xml` from `iso-8859-2` to `utf-8`
 - [x] `ukrainian.xml` from `utf-8` to `utf-8`
 - [x] `urdu.xml` from `iso-8859-2` to `utf-8`
 - [x] `uyghur.xml` from `utf-8` to `utf-8`
 - [x] `uzbek.xml` from `utf-8` to `utf-8`
 - [x] `uzbekCyrillic.xml` from `utf-8` to `utf-8`
 - [x] `vietnamese.xml` from `utf-8` to `utf-8`
 - [x] `welsh.xml` from `iso-8859-2` to `utf-8`

**Comment by milipili** [comment]
Suspicious content to check:
 - [ ] aragonese.xml

**Comment by donho** [comment]
Done
