### ISSUE TITLE
Please treat folders (and files) beginning with '.' as hidden when searching with 'find in files'

### ISSUE THREAD

**Issue by ThosRTanner** [notepad-plus-plus/notepad-plus-plus#3070]
### Please ignore folders/files beginning with . where you'd ignore hidden files

Programs ported from unix (git, mercurial, etc, etc, etc) store preferences in folders/files beginning with . which is the way you hide folders from the casual peruser on unix. However when the programs are ported to windows, these folders are ported with the leading . and don't grow a hidden attribute.

This makes it incredibly frustrating when doing a search as not only do you get matches you were looking for, but you get matches all over the git/mercurial/etc data files, and the only work round is to search for files with every extension you can think off, which can be rather tedious not to mention dangerous if you miss one.

### Steps to Reproduce the Issue

1. Install git
2. Create a git repo
3. Add a file into the repository and commit it
4. Make changes to the file, by deleting some of the text you originally had.
5. Search for the text you deleted in all files

### Expected Behavior
To see no matches

### Actual Behavior

notepad++ found a match inside .git

### Debug Information

Notepad++ v7.3.3   (32-bit)
Build time : Mar  8 2017 - 03:37:37
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10 (64-bit)
Plugins : ComparePlugin.dll JSLintNpp.dll JSMinNPP.dll mimeTools.dll NppConverter.dll NppEditorConfig.dll NppExec.dll NppExport.dll NppFTP.dll NppTextFX.dll PluginManager.dll SpellChecker.dll XMLTools.dll

**Comment by MetaChuh** [comment]
please contact microsoft to file a feature request to hide . files from windows explorer
