### ISSUE TITLE
Tab columns settings don't get applied properly on startup

### ISSUE THREAD

**Issue by ThosRTanner** [notepad-plus-plus/notepad-plus-plus#3071]
### My default tab settings for javascript aren't applied on restart.

My default tab settings are every 4 columns, except for javascript which are every two columns. This works fine, except when I quit and restart. At this point, my JS files are displayed with tab stops every 4 columns, and I have to go back to preferences, to set the default tabs up again. It still says '2' for javascript, but I have to click the '2' and re-enter 2 into the pop box, and everything is fine again. Till I restart...

### Steps to Reproduce the Issue

1.  Set your default and javascript tab settings to 4 columns, replaced by space, and enable display of tab columns.
1.  Open a javascript file
1.  See the tab stops every 4 columns
1.  Set the Javascript tab settings to 2 columns. See the tab columns change.
1.  Exit notepad++ and start it up again

### Expected Behavior

The tabs would be displayed every two columns and the tab key should insert 2 spaces

### Actual Behavior

The tabs are displayed every 4 columns, tab key inserts 4 spaces

### Debug Information

Notepad++ v7.3.3   (32-bit)
Build time : Mar  8 2017 - 03:37:37
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10 (64-bit)
Plugins : ComparePlugin.dll JSLintNpp.dll JSMinNPP.dll mimeTools.dll NppConverter.dll NppEditorConfig.dll NppExec.dll NppExport.dll NppFTP.dll NppTextFX.dll PluginManager.dll SpellChecker.dll XMLTools.dll

**Comment by MetaChuh** [comment]
please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins if you update from version 7.5.9 or below.
if your issue still persists, and it is still of relevance to you, please feel free to file a new issue as easy to understand and reproducible as possible.

thank you for your help and best regards.

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
(no extra account is needed, just use your github account to sign in)
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)
