### ISSUE TITLE
STYLE FONT IS CHANGED WHEN THE EDITOR IS RESTARTED

### ISSUE THREAD

**Issue by claudiomariano** [notepad-plus-plus/notepad-plus-plus#3073]
### Description of the Issue
Text Editor: When you change the IDE style, and close the editor, in the next time that you open again, the font of the editor is changed.

### Steps to Reproduce the Issue
1. Open then notepad++ editor;
2. Change the style in Settings >> Style Configurator;
3. See the font and memorize;
4. Close the editor;
5. Reopen the editor and the font is altered.

### Expected Behavior
The expected behavior is when the editor is restarted the font style cannot be changed.

### Actual Behavior
The font style is changed when the editor is started.

### Debug Information
Notepad++ v7.3.3   (32-bit)
Build time : Mar  8 2017 - 03:37:37
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10 (64-bit)
Plugins : mimeTools.dll NppConverter.dll NppExport.dll NppFTP.dll PluginManager.dll sql.dll 

Font used by "Obsidian Style":
![image](https://cloud.githubusercontent.com/assets/26517469/24078997/d7e46664-0c5b-11e7-9b9f-f2036e14f0b3.png)

After Close and reopen the editor, the style font is changed.
![image](https://cloud.githubusercontent.com/assets/26517469/24079001/fdb39644-0c5b-11e7-9306-bc96f2b8ff9f.png)

**Comment by kenzen** [comment]
I encountered same issue, the global style settings cannot be remembered.

**Comment by Tythos** [comment]
Certain styles do not have a default font (or font size) assigned explicitly. Historically, I've addressed this by adding the appropriate fontName ("Courier New") and fontSize ("10") values to the "Default Style" <WidgetStyle/> element in my *themes/Obsidian.xml*.

See #364 and the solution (rejected, but useful for reference) in #2695

**Comment by xates** [comment]
Let's see if that's the good one...

**Comment by kenzen** [comment]
Thanks @Tythos 

I have added global override fontname and fontsize to my current theme "dark vim blue". It works now.

**Comment by GGillan** [comment]
I see this problem for both font name/size and for other items, such as foreground color and marking colors.

I set Style Configurator - Global Styles - Global override to Font name: Liberation Mono + Font size 10. Also Configurator - Default Style - Foreground colour to white. "Save & Close". Whether I do those settings all at the same time or individually does not matter: they appear to save, but when I exit and later open Notepad++ they have been reset (Font name blank, Font size blank, foreground color yellow). This is in text mode using the vim Dark Blue theme, but the same font name and size issue pertains in various languages. I have noticed that other color overrides (at least one markup color that was not visible against the vim Dark Blue background and needed changing) also do not save between sessions.

This is Windows 7 fully patched.
Notepad++ is v7.4.2 32-bit.

**Comment by GGillan** [comment]
Further information: I completely uninstalled/removed Notepad++ from this system, which included a reboot to remove the Notepad++ folder from Program Files (x86), then installed Notepad++ fresh. 

Style changes do seem to save properly now.

I had first installed Notepad++ on this computer ~2012 when this system was new. Possibly there is some cruft leftover from earlier versions/the version upgrade process/whatever that are behind this bug.

**Comment by antonmok** [comment]
There is no write permissions for *.xml files in Program Files (x86)\Notepad++\themes\
Add permissions to your user and changes will be saved.

**Comment by donho** [comment]
Cannot reproduce in v8.1.9.3 - I suppose the bug has transformed to butterfly and flied away.
