### ISSUE TITLE
Incremental Search Bar: Click Selects All

### ISSUE THREAD

**Issue by Yaron10** [notepad-plus-plus/notepad-plus-plus#308]
Hello Don,

Using the Incremental Search Bar's text field, I often find myself "Select All" and then "Paste".
How about making that field select all on click?

Thank you for your great work.

**Comment by MetaChuh** [comment]
hi @Yaron10 
just cleaning up a bit, by closing some orphaned issues at the tracker, to improve readability.
hope you don't mind after 4 years 😉
please feel free to reopen a new issue if this is still an issue for you
