### ISSUE TITLE
Stop continously checking non-in-view opened files

### ISSUE THREAD

**Issue by mirh** [notepad-plus-plus/notepad-plus-plus#3083]
I have some files opened from my second hard drive for... *later times*, and albeit now I'm working on others, it cannot find peace because every time n++ window gets active again (which happens pretty frequently) system has to unpark hdd. 

Also, it wouldn't hurt if you could work on #913 too. It's a PITA having to stop for 5-10 second because disk has to spin up.

**Comment by MetaChuh** [comment]
please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins if you update from version 7.5.9 or below.
if your issue still persists, and it is still of relevance, please feel free to file a new issue as easy to understand and reproducible as possible.

thank you for your help and best regards.

**Comment by mirh** [comment]
My congratulations, this is now fixed.
