### ISSUE TITLE
nginx files recognition and perhaps trouble with (un)comment

### ISSUE THREAD

**Issue by WagnerGMD** [notepad-plus-plus/notepad-plus-plus#3084]
Hello,

I'm just wonder if you believe one day NPP will be able to recognize nginx (like nginx.conf file, etc) ? At least, there's a way to (un)comment lines ? Apparently, it's doesn't work (with the multiple-editing at once) when I use the shorcut (ctrl + q), it's normal ?

Best regards.

**Comment by MetaChuh** [comment]
please use one of the available nginx udl language downloads
