### ISSUE TITLE
Support for Microsoft M?

### ISSUE THREAD

**Issue by Efsee21** [notepad-plus-plus/notepad-plus-plus#3085]
I would like to edit sources in Microsoft M 
https://msdn.microsoft.com/en-us/library/mt211003.aspx gives a reference to the syntax.
Is this language supported? Otherwise a suggestion.
"D" seems to be an approximation, I just found. Comments welcome

**Comment by r-k-b** [comment]
Lars of ssbi-blog.de has [an updated guide to getting M / Power Query support into NPP.](http://ssbi-blog.de/technical-topics-english/power-query-editor-using-notepad/) Might be useful?

**Comment by MetaChuh** [comment]
please use one of the available m udls.

many thanks and best regards.
