### ISSUE TITLE
Multi-line comment coloring issue in .sql files

### ISSUE THREAD

**Issue by ryan8720** [notepad-plus-plus/notepad-plus-plus#3086]
When using a multi-line comment in a .sql file, adding an extra asterisk makes the comment color go away.

For example:

```
/* Correctly colored comment */

/** Incorrectly colored comment */

/**
 * Incorrectly colored comment 
 */

/*******************************
 * Incorrectly colored comment *
 *******************************/
```

All of the above should be the same green color.

Screenshot from Notepad++ v7.3.3 (32-bit):
![image](https://cloud.githubusercontent.com/assets/136496/24211173/a44c307c-0f01-11e7-9a71-bd9b0629d07b.png)

**Comment by Khaos66** [comment]
I've got the same issue, but with a user defined language.
## Definition
![definition](https://cloud.githubusercontent.com/assets/4013009/25419949/ea6e5a66-2a55-11e7-8a9c-1a9a7c239896.PNG)

## Outcome
![comments](https://cloud.githubusercontent.com/assets/4013009/25419923/c92f2b78-2a55-11e7-9f38-b06e28ac16cc.PNG)
