### ISSUE TITLE
Why it can not handle very big files? Another software called EmEditor has 0 lag for over 3gb+ files

### ISSUE THREAD

**Issue by MonsterMMORPG** [notepad-plus-plus/notepad-plus-plus#3089]
My computer have dual SSD as raid 0 and 32 GB ram

I am using notepad++ 64 bit

I wonder why notepad++  can not open 3gb+ files or becomes extremely slow for 1gb+ files?

I mean text files

**Comment by frank-orellana** [comment]
There are some features I have noticed that make notepad++ slow with big files (even simple text files). Those are Auto-completion and clickable hyperlinks. There might be other features that make them slow too  (autodetect character encoding and smart highlighting maybe).

Other than that, it could also be the plugins you have installed. Anything that analyzes the text is a suspect (DSpellcheck for example).

Also I've noticed that the first time I open a big file it might take a while, after that it opens quickly. Not sure if that is a bug of windows memory allocation or Npp (or even my own computer).

Can you try to see if you have some of those features/plugins enabled and test with them turned off to see if they are the ones needing improvement? You can also share the debug info from the help menu.

**Comment by NN---** [comment]
Even 50MB is too big for Notepad++.

**Comment by MonsterMMORPG** [comment]
@frank-orellana EmEditor also have clickable hyperlink

it is still super duper fast

i dont have any plugins

**Comment by MetaChuh** [comment]
please update your notepad++ to the latest 64 bit version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins if you update from version 7.5.9 or below.
if your issue still persists, and it is still of relevance, please feel free to file a new issue as easy to understand and reproducible as possible.

thank you for your help and best regards.
