### ISSUE TITLE
mouse and pad scroll bug

### ISSUE THREAD

**Issue by madebycambiamentico** [notepad-plus-plus/notepad-plus-plus#309]
i have a notebook (acer aspire) with windows 7. if i switch from mouse to pad, then the scroll goes in "delay" of 1 scrolling. to reproduce the bug-bug-buggy:
a) scroll down with mouse
b) scroll down with pad
c) using either one of the device if i scroll 1 time up, it doesn't scroll at all.
d) if i scroll another time up, it scroll by 1 unit.
d) next scolls up ar right, 1 unit (as it should)
same problem if i invert the scroll direction.
to solve i can only close and restart np++

**Comment by donho** [comment]
Update your Notepad++ to v7.6.6.
If this bug persists in the new release, please open a new issue with the debug information.
