### ISSUE TITLE
When having more than one line of file tabs, they turn to buttons

### ISSUE THREAD

**Issue by esrat** [notepad-plus-plus/notepad-plus-plus#3090]
### Description of the Issue

With one of the last updates (apparently seen in v7.3.3) the visual appearance of multiple tab lines of open files broke! There is no problem if one has not enough files open to fill a complete line of tabs. But when the multi-line tab bar needs to show a second (or more) line(s), it does not show tabs anymore. The visual appearance switches to ugly, misaligned buttons with more or less free space between them.

### Steps to Reproduce the Issue

1. Open Notepad++ (configured with a multi-line tab bar)
2. Repeatedly hit [Ctrl]+[N] until the first line of tabs overflows

### Expected Behavior

The old behaviour / appearance should be preserved.

### Actual Behavior

Ugly buttons instead of tabs are shown.

### Debug Information

Notepad++ v7.3.3   (32-bit)
Build time : Mar  8 2017 - 03:37:37
Path : C:\TEMP\npp.7.3.3.bin\notepad++.exe
Admin mode : OFF
Local Conf mode : ON
OS : Windows 7 (64-bit)
Plugins : mimeTools.dll NppConverter.dll NppExport.dll PluginManager.dll 

(freshly downloaded current version with nothing more changed than the enabled multi-line tab bar)

Right before the first line overflows:
![np 1](https://cloud.githubusercontent.com/assets/23553210/24300681/8be748a2-10ad-11e7-8ab4-1d39b99813af.png)

One more file and there are no tabs anymore:
![np 2](https://cloud.githubusercontent.com/assets/23553210/24300741/b3348bc2-10ad-11e7-91a0-d7561650fd2b.png)

**Comment by rddim** [comment]
#3007

**Comment by MetaChuh** [comment]
please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins if you update from version 7.5.9 or below.
if your issue still persists, and it is still of relevance, please feel free to file a new issue as easy to understand and reproducible as possible.

thank you for your help and best regards.
