### ISSUE TITLE
Session snapshot and periodic backup path is not user-configurable

### ISSUE THREAD

**Issue by CollinChaffin** [notepad-plus-plus/notepad-plus-plus#3096]
### Description of the Issue
Despite the code written to make it appear to end-users that this path is configurable, lines 2374-2375 in preferenceDlg.cpp after all these years are still coded in such a way that this path is virtually hard-coded to a subdirectory named "backup" appended to the users' windows profile %appdata%\Roaming\Notepad++ root folder:
```
    generic_string backupFilePath = NppParameters::getInstance()->getUserPath();
    backupFilePath += TEXT("\\backup\\");
```

### Steps to Reproduce the Issue

1.   Open "Settings" then "Preferences"
2.   Navigate to the "Backup" category
3.   Enable the checkboxes for the "Session snapshot and periodic backup" control group

NOTE:  The Windows control assigned to display this parameter to the end-user is currently (and incorrectly/confusingly) the same ENABLED DISABLED TEXT BOX as also used just below in the "Backup on Save" / "Custom Backup Directory" field that is in the ENABLED state and allows user to change the param.  Because the control used is actually in the ENABLED state, it allows the user to click inside and select text etc. further giving the impression it can be changed, however  does not accept key input (if the control were in the DISABLED state, it would not show active cursor and selection etc.)

### Expected Behavior
Typing new path into the box with the flashing cursor.

### Actual Behavior
Flashing cursor and selectable (not grayed out and disabled) indicating user should be able to change path, however the path is read-only and cannot be changed.

### Other Issue Information
IMO this might normally be a (swallowing hard) "enhancement" request to simply ask that a param like this is simply added to the already long list of user-configurable params stored in the XML and/or registry, but because it is currently being presented to the end-user in a fashion that is very misleading and confusing would classify this as a bug.  At the very least, if one wanted to insist the user never could configure this path but still wanted to present the path to the user, that this windows control in the guides of UI best practices be changed to a DISABLED text box which would indicate visually via grayed out and making clear to the user that it is not just as changeable as the 2nd path text box right below it that actually does allow changing.

**Comment by dsayron** [comment]
Hi!

To manage this question, just go to settings - preferences - **CLOUD** 
Then, paste/type the desired path on: “Set your cloud location path here” textbox.

It will miraculously and automatically fill out "backup location" disabled box from Session snapshot and periodic backup frame.

**Comment by MetaChuh** [comment]
please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins if you update from version 7.5.9 or below.
if your issue still persists, and it is still of relevance, please feel free to file a new issue as easy to understand and reproducible as possible.

thank you for your help and best regards.
