### ISSUE TITLE
XML folding

### ISSUE THREAD

**Issue by rend3r** [notepad-plus-plus/notepad-plus-plus#3097]
I'm not sure is the sample valid xml but folding could not be applied to the blocks closed with /> tag.

<img width="629" alt="npp_folding" src="https://cloud.githubusercontent.com/assets/12601181/24326563/b269d070-11c1-11e7-9ef9-a7b45083c8ac.png">

[hidpi.txt](https://github.com/notepad-plus-plus/notepad-plus-plus/files/870407/hidpi.txt)

npp 7.3.3 x64

**Comment by donho** [comment]
Don't get what you mean.
Could you provide more description about your issue and reopen it?
