### ISSUE TITLE
Feature Request: Updater to allow for multiple instances / multiple users of NPP

### ISSUE THREAD

**Issue by Conan1989** [notepad-plus-plus/notepad-plus-plus#3098]
### Description of the Issue
Currently the updater for NPP doesn't seem to allow for situations where there are multiple instances of NPP open with multiple users. For example, a remote desktop server with multiple users logging in, each with an instance of NPP. If one user runs the update while another user has NPP open, update fails (expected)

### Steps to Reproduce the Issue
1. Have NPP open with multiple users accounts (users A, B)
2. Run the update check as user A, will prompt to close the user A's instance of NPP (while ignoring user B) before running the installer
3. The installer will throw an error attempting to overwrite a locked file (user B)

### Suggestion
NPP's updater could be aware of other instances, don't prompt to "update now" while anther instance is running.
Maybe have a flag that is made when an update is found, NPP checks that flag on exit. Checks if it's that last instance, if so, run the update

**Comment by MetaChuh** [comment]
please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins if you update from version 7.5.9 or below.
if your issue still persists, and it is still of relevance, please feel free to file a new issue as easy to understand and reproducible as possible.

thank you for your help and best regards.
