### ISSUE TITLE
Frustrating auto-[de]indent when entering braces

### ISSUE THREAD

**Issue by Marshallx** [notepad-plus-plus/notepad-plus-plus#3099]
### Description of the Issue
When typing in a closing brace, the current line indent changes - but I don't want it to.

### Steps to Reproduce the Issue
`if (a==b) {`
&nbsp;&nbsp;&nbsp;&nbsp;`foobar();`
Now enter a closing brace on that same line `}`
### Actual Behavior
On entering a closing brace, this happens:
`if (a==b) {`
`foobar(); }`
The line automatically deindents.

### Expected Behavior
The line should not have automatically deindented.

To clarify, in this example I had accidentally typed a closing brace and, rather than just typing backspace to fix my mistake, I have to also go to the beginning of the line and manually edit the indent. Another example that triggers this would be inline object literals that I haven't finished entering. 

All I want from auto-indenting is for an enter key press to auto-indent the new line to match the position of the first non-whitespace character of the previous line - nothing more. Every "smart" indent feature I have ever used (not just Notepad++ but all software) never works in a way that is helpful to me - it always slows me down and should be possible to disable.

Thank you.

### Debug Information
Notepad++ v7.3.3   (32-bit)
Build time : Mar  8 2017 - 03:37:37
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10 (64-bit)
Plugins : HexEditor.dll JSMinNPP.dll mimeTools.dll NppConverter.dll NppExport.dll PluginManager.dll

**Comment by MetaChuh** [comment]
please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins if you update from version 7.5.9 or below.
if your issue still persists, and it is still of relevance, please feel free to file a new issue as easy to understand and reproducible as possible.

thank you for your help and best regards.

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
(no extra account is needed, just use your github account to sign in)
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)

**Comment by AntonKhorev** [comment]
It also deindents if I type `}` inside a string or a comment. How does that makes sense?

    //}

    /*}

    "}
