### ISSUE TITLE
Tabs as word characters

### ISSUE THREAD

**Issue by Kulvar** [notepad-plus-plus/notepad-plus-plus#3100]
### Description of the Issue
When I try to select a word by double clicking it, tabs around it are considered word characters
When you select a word surrounded by tabs, it's not considered that the full word was selected.
It also affect same words highlighting. Selecting a word will not highlights the other identical words if they're surrounded by tabs. However, if you select a word with its surrounding tabs, any other identical words surrounded by identical tabs will be highlighted.

### Steps to Reproduce the Issue
1. Write a word with leading or ending tabs
2. Double click the word
3. See that it include tabs into the selection

### Expected Behavior
Tabs are not words characters.

### Actual Behavior
Tabs are words characters

### Debug Information
Notepad++ v7.3.3   (64-bit)
Build time : Mar  8 2017 - 03:39:58
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10 (64-bit)
Plugins : mimeTools.dll NppConverter.dll

**Comment by dail8859** [comment]
This bug hasn't been reported in a while and hopefully c63673a1d8f4774bfcbd01c11d7cb4fc09b9fb2c was the actual fix to it in v7.4 and afterwards. If you run into this issue again please reopen.
