### ISSUE TITLE
Function List for XML language 

### ISSUE THREAD

**Issue by gaabne** [notepad-plus-plus/notepad-plus-plus#3102]
### Description of the Issue
 XML Source file with tags with nothing else than a name ( like `<element>`) are not recognized.

### Steps to Reproduce the Issue

```
<Element>
  <Area Right="20">
   ....
  </Area>
</Element>
```

### Expected Behavior
The tag `<Element>` should appear in the Function List panel

### Actual Behavior
No tag of this format appear in the list

**Comment by MetaChuh** [comment]
please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins if you update from version 7.5.9 or below.
if your issue still persists, and it is still of relevance, please feel free to file a new issue as easy to understand and reproducible as possible.

thank you for your help and best regards.
