### ISSUE TITLE
JavaScript style expressions in template literal (STRINGRAW)

### ISSUE THREAD

**Issue by manake** [notepad-plus-plus/notepad-plus-plus#3103]
https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Template_literals

Feature request for ability to bold expressions like this:
<code>\`string text **${expression}** string text\`</code>

**Comment by MetaChuh** [comment]
please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins if you update from version 7.5.9 or below.
if your issue still persists, and it is still of relevance, please feel free to file a new issue as easy to understand and reproducible as possible.

thank you for your help and best regards.
