### ISSUE TITLE
Double-click a word selects more than the word

### ISSUE THREAD

**Issue by Marshallx** [notepad-plus-plus/notepad-plus-plus#3105]
### Description of the Issue
Double-clicking on a word selects more than just that word. This used to work ok, looks like it has been broken in a recent version.

### Steps to Reproduce the Issue
`function doSomething(lang) {`
Double-click the word "doSomething" or "lang"

### Expected Behavior
Double-clicking "doSomething" should select the text "doSomething"
Double-clicking "lang" should select the text "lang"
(e.g. try double clicking those words right now in your web browser - that's what should happen)

### Actual Behavior
Double-clicking "doSomething" selects the text "doSomething(lang"
Double-clicking "lang" selects the text "doSomething(lang"

### Debug Information
Notepad++ v7.3.3   (32-bit)
Build time : Mar  8 2017 - 03:37:37
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10 (64-bit)
Plugins : HexEditor.dll JSMinNPP.dll mimeTools.dll NppConverter.dll NppExport.dll npp_tabs.dll PluginManager.dll

**Comment by Inantermark** [comment]
I am seeing the same issue.
It looks like it is only separating the word on spaces, but ignores newline characters.
This means it highlights words on different lines.

See attached image for when you double click on the word 'hello'.

![notepadbug](https://cloud.githubusercontent.com/assets/5678241/24432906/a8451f9c-1481-11e7-871d-f16eba2ace2a.png)

**Comment by JeanPaulRouve** [comment]
Hi,

Similar report for 7.3.3 on a C source code:

a = variable;

Double-clicking on "variable" selects "variable;".

Collateral damage : it doesn't highlights occurences of "variable" not followed by ';'...

That's clearly a recent regression: it works fine on 7.3.1.

Best regards,

**Comment by ShelMi** [comment]
Similar for me on 7.3.3:  double-click selects way too much, sometimes spaces on both sides of word, sometimes more.
Retreated to version 7.3.1 (did not try 7.3.2) and problem is gone.

**Comment by zeppenfe** [comment]
Same problem here with 7.3.3, specifically opening parentheses are included when double-clicking a word directly before or after.

Reverted to 7.3.2 and the problem is gone.

Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10 (64-bit)
Plugins : GdbPlugin32.dll PluginManager.dll

**Comment by nik90000** [comment]
Same with 7.3.3
![screenshot_7](https://cloud.githubusercontent.com/assets/13693620/26286170/1e43fa88-3e67-11e7-9d14-871da26fe089.png)

**Comment by CptTwinkie** [comment]
I have the same
![image](https://user-images.githubusercontent.com/2079751/27149684-adffd8fa-5144-11e7-87e3-130c589a6b1f.png)
This is killing my productivity. Reverting....

**Comment by mohan-nade** [comment]
Looks like NPP 7.4.2 does not have this issue.
It was there with previous on the machine which was 7.3.3.

**Comment by dail8859** [comment]
This bug hasn't been reported in a while and hopefully c63673a1d8f4774bfcbd01c11d7cb4fc09b9fb2c was the actual fix to it in v7.4 and afterwards. If you run into this issue again please reopen.

**Comment by JDBurnZ** [comment]
I'm having a similar issue where when working in a plain text document, double-clicking any line highlights the whole document. Text in the document is simply:


468040
468046
468047
838365
468066
838368
468080
838366
468087
838367
468095
468098
468104
468110
466922
468136
468906

**Comment by dail8859** [comment]
@JDBurnZ if you read above you will see you need to update Notepad++ to a newer version.

**Comment by JDBurnZ** [comment]
Oy, apologies - i read most the posts, but must have missed the important one. :)
