### ISSUE TITLE
Search -> Replace Not Working

### ISSUE THREAD

**Issue by Cable321** [notepad-plus-plus/notepad-plus-plus#3106]
### Description of the Issue

Search menu -> Replace is not working, says "Replace All: # occurrences were replaced.", but nothing changes.

### Steps to Reproduce the Issue

1. Open a new tab, enter the text 

\\" \\" \\"

(one backslash, one quote), had to enter a double backslash to have the characters appear correctly in this ticket)

2. Replace \\" with "
3. Says "Replace All: 3 occurrences were replaced.", but nothing changes.

### Expected Behavior

\\" \\" \\" is turned into " " " 

### Actual Behavior

\\" \\" \\" still appears in the tab, not replaced with " " ".

### Debug Information

Notepad++ v7.3.3   (32-bit)
Build time : Mar  8 2017 - 03:37:37
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10 (64-bit)
Plugins : JSMinNPP.dll mimeTools.dll NppConverter.dll NppExport.dll NppFTP.dll NPPJSONViewer.dll PluginManager.dll XMLTools.dll

**Comment by frank-orellana** [comment]
Maybe you should uncheck the `Regular Expression` checkbox. That's the only way I could reproduce your problem. You should check either `Normal` or `Extended`, that way the replacement is correct.

![imagen](https://cloud.githubusercontent.com/assets/2250701/24425283/03e57318-13da-11e7-993f-aafe034cdffe.png)

**Comment by Cable321** [comment]
Damn, that did it - thx!
