### ISSUE TITLE
Suggest : Shutdown care + CTRL-Z History

### ISSUE THREAD

**Issue by OlivierHelden** [notepad-plus-plus/notepad-plus-plus#3107]
### Description of the Issue
- When my computer shutdown, and my workspace is unsaved i lose any change, i would keep it saved anytime like file modification, that's mean i'll never be scared about suddent shutdown.

- Ctrl Z / Y History works great, but when i close notepad++ without save, i can reopend it and file modification are keeped, but i can't CTRL - Z again to back in time like if i haven't close notepad++.

- I would like be able to create my proper "level" (like { and }) without put an if (true) { } in my code, i can hide line in just selecting it and select hide in the context menu, but i need to to this each time i want hide this code portion

Thanks for your works, sorry for my english, i don't know if i'm in the good section to post it.
Greetings, Helder.

**Comment by MetaChuh** [comment]
please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins if you update from version 7.5.9 or below.
if your issue still persists, and it is still of relevance, please feel free to file a new issue as easy to understand and reproducible as possible.

thank you for your help and best regards.
