### ISSUE TITLE
Notepad 7.3.3 Multi-row tab UI broken

### ISSUE THREAD

**Issue by maxicombina** [notepad-plus-plus/notepad-plus-plus#3109]
### Description of the Issue

In latest Notepad++ 7.3.3 the multi-row tab looks really ugly.
I am using window 10. Up to version 7.3.2 it looked just right.
I tried 32 and 64 bit versions.

### Steps to Reproduce the Issue

1.  Install Notepad++ 7.3.3 (32 or 64 bits)
2. Configure "Multi-line" under "General" preferences
3. Open several documents until the 2nd row is enabled

### Expected Behavior

Tabs should keep the look of 1-row. Same as version <= 7.3.2 of notepad++
### Actual Behavior

Tabs look really ugly.

### Debug Information

Sorry, I uninstalled version 7.3.3.

I hve screenshots:

Version 7.3.3 (wrong):
![npp_7 3 3](https://cloud.githubusercontent.com/assets/757122/24450641/ea3e97b2-147b-11e7-8769-9725de75f613.png)

Version 7.3.2 (corect)
![npp_7 3 2](https://cloud.githubusercontent.com/assets/757122/24450642/ea51631a-147b-11e7-9880-8da3a28c79a7.png)

**Comment by rddim** [comment]
#3007

**Comment by maxicombina** [comment]
Ops, sorry for the dupe.

**Comment by HackerMand** [comment]
1
