### ISSUE TITLE
Feature request --- Background color for tabulations

### ISSUE THREAD

**Issue by ghost** [notepad-plus-plus/notepad-plus-plus#3111]
To distinct more easily between spaces to tabs, I need that all tab indents (all tabulations) will have a nice background color. I don't find a way to do so in style configurator and assume it's a feature that can be added.

**Comment by MetaChuh** [comment]
please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins if you update from version 7.5.9 or below.
if your issue still persists, and it is still of relevance, please feel free to file a new issue as easy to understand and reproducible as possible.

thank you for your help and best regards.

**Comment by sasumner** [comment]
What's wrong with turning visible whitespace symbols on?  Once you do so it is very clear what whitespace is a tab and what is spaces.
