### ISSUE TITLE
Find in Files multiple directories

### ISSUE THREAD

**Issue by rowanbradley** [notepad-plus-plus/notepad-plus-plus#3114]
### Description of the Issue
It would be a real help to me to be able to search for text in files in more than one directory tree. My use case is that I am developing a web site in PHP. I have one public directory where the files that must be accessible to a browser are. I have another 'include' directory where I put all the files that are accessed by the application but need not be directly accessible to a browser, e.g. files that are included or required by another PHP file, function libraries etc. I often use Find in Files to find and replace all the occurrences of a string. This is an invaluable feature if for some reason you need to e.g. change the name of a variable. Currently I have to have two paths, and to do the Find in Files twice in order to find all the occurrences. It would be a lot easier if I could just include two or more directories in the Directories box, separated by ; (I suggest). Currently it doesn't seem to accept this. Could this feature be added?

### Steps to Reproduce the Issue

1. Enter the following in the Directories box:
\\SUE-PC\C-Users\RowanB\Documents\Inetpub\www.sylvesterbradley.org\include; \\SUE-PC\C-Users\RowanB\Documents\Inetpub\www.sylvesterbradley.org\public_html\swchoir
2. Click Find All
3. Nothing happens.

### Expected Behavior
It should search both directory trees.

### Actual Behavior
Nothing. It highlights the (it thinks) faulty directory string

### Debug Information
Notepad++ v7.3.3   (64-bit)
Build time : Mar  8 2017 - 03:39:58
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 8.1 (64-bit)
Plugins : mimeTools.dll NppConverter.dll 

Thank you - Rowan

**Comment by MetaChuh** [comment]
the find in files function serves its basic purposes, for being a small goodie inside notepad++.

we will not integrate features that are handled much better using specifically designed applications for that task.

you can e.g. use the free utility [FileSeek](https://www.fileseek.ca/Download/).
it has notepad++ integration and a lot of include/exclude, date and regex functions. much more than can ever be integrated into notepad++.

many thanks and best regards.

**Comment by sasumner** [comment]
>serves its basic purposes, for being a small goodie inside notepad++

Well said.

**Comment by kevinwkc** [comment]
I need this feature!

**Comment by bkisdi** [comment]
Me too!
It is not just about finding something. It is important to see the results _inside_ Notepad++, and to easily jump to any match.
It is asked elsewhere too: see [this](https://superuser.com/questions/887462/find-in-files-across-multiple-directories-with-notepad).
For Windows, semicolon is suggested as separator. (As in the PATH environment variable.)
The ... button right to the Directory field might be tough, but I'd be glad entering directory names manually. This is not very difficult, just cycle through directory names.
Thanks. :)

**Comment by Faq** [comment]
Or just use [Agent Ransack](https://www.mythicsoft.com/agentransack/)

**Comment by jikkujj** [comment]
Why is one guy just able to decide a feature that is so useful to so many people is unnecessary? This will just drive users away to some other editor.
