### ISSUE TITLE
Possible Feature Idea - Paste to existing tab

### ISSUE THREAD

**Issue by MitchellTurner2017** [notepad-plus-plus/notepad-plus-plus#3115]
Paste to > (Cascading menu which lists all other tabs)

What happens is, you right click any tab your working on, and select this option from the menu. The Cascading menu will display (each on it's own line) the names of all other currently open tabs. You select the one you want, and it copies (preferably without using the clipboard, in case you have something else copied that you need to keep copied) and the program would automatically copy everything in this tab to the one selected. The paste would occur at the very bottom of the document being pasted too.

So, say i was trying to make a text file listing a series of numbers (1, 2, 3, etc...) of all hex values, each on it's own line. and I needed to mass replace values to expedite the process. Copy 00000000 - 0000000A to a new tab, then replace 0000000 with 0000001 (creating 00000010 - 0000001A) then Paste to tab and then replace 0000001 with 0000002 and so on... this would make a lot of copy paste actions very much easier. I'd really love to see this feature. I do A LOT of repetitive copy/paste and this would truly speed things up quite a bit.

PS... You might even add a setting in preferences to paste to top of bottom of a document, but either way...
PSS... You might even add keyboard shortcuts )if possible) for the first 10 (0-9) tabs. :-)
Thank you for taking the time to read this!!!!

<3 Notepad++ <3 Notepad++ <3 Notepad++ <3

**Comment by MetaChuh** [comment]
thank you for your feature idea.
unfortunately we can not see the advantage for the majority of notepad++ users.

thank you for your help and best regards.

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
(no extra account is needed, just use your github account to sign in)
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)

**Comment by sasumner** [comment]
@MitchellTurner2017 If you are still interested I could probably help with scripting this functionality.
