### ISSUE TITLE
Dev help to add support for Javascript keywords

### ISSUE THREAD

**Issue by Lucas-C** [notepad-plus-plus/notepad-plus-plus#3117]
Hello.

### Description of the Issue
The `type2` Javascript keywords are currently not highlighted: [PowerEditor/src/langs.model.xml#L134](https://github.com/notepad-plus-plus/notepad-plus-plus/blob/master/PowerEditor/src/langs.model.xml#L134)
I think this because there is no [`SCE_C_`macro definition / `styleID`](https://github.com/notepad-plus-plus/notepad-plus-plus/blob/master/scintilla/include/SciLexer.h#L166) to attach this `keywordClass` to in [`stylers.xml`](https://github.com/notepad-plus-plus/notepad-plus-plus/blob/master/PowerEditor/src/stylers.model.xml#L455).

### Help wanted
How should I proceed to add support for highlighting `type2` Javascript keywords (issue already mentionned in #1351) ?

Regards.

**Comment by dail8859** [comment]
Just glancing at the code I *think* you'd have to add new style in [here](https://github.com/notepad-plus-plus/notepad-plus-plus/blob/master/PowerEditor/src/stylers.model.xml#L455-L473), and then add a bit extra logic [here](https://github.com/notepad-plus-plus/notepad-plus-plus/blob/b869163609473f05c4f5d1d72a579b9f6af66ccd/PowerEditor/src/ScitillaComponent/ScintillaEditView.cpp#L945-L972) to pull out and set the additional `type2` keywords. 

Not 100% sure this is all that is needed but definitely on the right track.

**Comment by Lucas-C** [comment]
It'd be awesome to simply add a `WordStyle` with a non-existing `styleID`.

Example with inline keywords:
```
<WordsStyle name="EXTRA KEYWORDS" styleID="30" fgColor="B58900" bgColor="FFFFFF" fontName="" fontStyle="" fontSize="">require module exports</WordsStyle>
```

Example with the `type2 keywordClass`  :
```
<WordsStyle name="EXTRA KEYWORDS" styleID="30" fgColor="B58900" bgColor="FFFFFF" fontName="" fontStyle="" fontSize="" keywordClass="type2"/>
```

Even if only the 1st example worked, that would make Notepad++ stylers way more extensible !

But I understand it is not easily doable du to the way [LexCPP.cxx](https://github.com/notepad-plus-plus/notepad-plus-plus/blob/master/scintilla/lexers/LexCPP.cxx) works.

---

As a quick solution, would you be ok to add the following in [SciLexer.h](https://github.com/notepad-plus-plus/notepad-plus-plus/blob/master/scintilla/include/SciLexer.h#L193) ?
```
#define SCE_C_WORD3 28
```

And the followinf in [LexCPP.cxx](https://github.com/notepad-plus-plus/notepad-plus-plus/blob/master/scintilla/lexers/LexCPP.cxx) :
```
// line 810
					} else if (keywords5.InList(s)) {
						sc.ChangeState(SCE_C_WORD3|activitySet);
```

...+ a few more changes in this file and `stylers.model.xml` that I could send as a PR.

**Comment by dail8859** [comment]
Just FYI anything within the `scintilla` directory is used as-is so it is rare changes are accepted to those files.

**Comment by Lucas-C** [comment]
Thanks @dail8859, I did not spot where those those keywords were passed to the lexer !

I don't quite get how the word-lists are passed to it neither :
https://github.com/notepad-plus-plus/notepad-plus-plus/blob/master/scintilla/lexers/LexCPP.cxx#L583

**Comment by dail8859** [comment]
The last part of the section of C++ code I linked are what set the keywords. I.e. the `SCI_SETKEYWORDS` command.

**Comment by Lucas-C** [comment]
Ah ok, good to know @dail8859.

Maybe the easier would be to merge the `type2` keywords into the `instre2` ones: [PowerEditor/src/langs.model.xml#L134](https://github.com/notepad-plus-plus/notepad-plus-plus/blob/master/PowerEditor/src/langs.model.xml#L134)

It's just 2 lines to change after all :) And they definitively fit as [`WINDOW INSTRUCTION`](https://github.com/notepad-plus-plus/notepad-plus-plus/blob/master/PowerEditor/src/stylers.model.xml#L459)

Can I submit a PR for that ?

**Comment by Lucas-C** [comment]
@dail8859 ah ok, I get it now. It doesn't seem extensible though.

**Comment by dail8859** [comment]
> Can I submit a PR for that ?

Yeah that's fine however @donho will have to decide if the changes are ok or not.

> It doesn't seem extensible though.

I don't think anyone would argue with that statement. :)
