### ISSUE TITLE
Indentation behavior differs depending on access

### ISSUE THREAD

**Issue by nweyand** [notepad-plus-plus/notepad-plus-plus#3122]
### Description of the Issue
When using the _Increase Line Indent_ feature from _Menu > Edit > Indent_, it behaves differently from its shortcut key (Tab).

### Steps to Reproduce the Issue

1. Use some block of code that is currently indented by 4 spaces.
2. Select it and indent if via _Menu > Edit > Indent > Increase Line Indent_ → All the spaces get converted to tabs and indentation is increased by 1 step.
3. Undo the last action
4. Select the block of code again and now hit _tab_ on your keyboard (which is the shortcut key shown in the menu used before).
5. Indentation is increased by 1 line of tabs. The spaces from the previous indentation **do not** get replaced by tabs.

### Debug Information
Notepad++ v7.3.3   (32-bit)
Build time : Mar  8 2017 - 03:37:37
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 7 (64-bit)
Plugins : mimeTools.dll NppConverter.dll NppExport.dll NppFTP.dll PluginManager.dll TabIndentSpaceAlign.dll XMLTools.dll

**Comment by MetaChuh** [comment]
please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins if you update from version 7.5.9 or below.
if your issue still persists, and it is still of relevance, please feel free to file a new issue as easy to understand and reproducible as possible.

thank you for your help and best regards.

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
(no extra account is needed, just use your github account to sign in)
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)
