### ISSUE TITLE
[Feature Request] Move/Clone to Other View (pick a side or be able to move)

### ISSUE THREAD

**Issue by jsh562** [notepad-plus-plus/notepad-plus-plus#3123]
I would like to be able to either choose which side to move/clone the document to (left or right side) or be able to move the document from one side to another.

I usually have a lot of files open at once and sometimes I need to clone one of them for a time period to work on different areas at once (duh).
What I want to do is be able to clone the document I need to the left side because that's how I prefer to work. 
When I clone one of the documents, it moves or clones to the right by creating a new "view" on the right side of the editor. I am not able to choose which side to create a new "view" on nor can I move the cloned document to the other side to create a new "view" there.
Now I am stuck with a zillion documents open on my left-hand view and my "temporary" document on my right, when I want it the other way around. My only solution is to manually move all documents in the left view to the right, but to have to move 50+ documents sucks =(

**Comment by MetaChuh** [comment]
please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins if you update from version 7.5.9 or below.
if your issue still persists, and it is still of relevance, please feel free to file a new issue as easy to understand and reproducible as possible.

thank you for your help and best regards.

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
(no extra account is needed, just use your github account to sign in)
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)
