### ISSUE TITLE
Windows 10 Creators Update affects font in Notepad++

### ISSUE THREAD

**Issue by Eldaw** [notepad-plus-plus/notepad-plus-plus#3124]
On each of my PCs where I've upgraded Windows 10 from v1607 (the Anniversary Update) to v1703 (the Creators Update), the font in Notepad++ has changed. It has become a lighter/thinner, or more 'wispy'.

I use Courier New, size 10, as the font.

**Comment by Eldaw** [comment]
I've changed to Consolas, size 10, and that renders correctly.

**Comment by thimo-seitz** [comment]
This is not limitied to Notepad++. I've noticed the same behaviour with putty, winmerge and WordPad.

**Comment by 1010101010101** [comment]
I usually zoom once in NP++ and though that the '2' were cut off.

Zoomed 1x
http://i.imgur.com/m57PLPw.png
Zoomed multiple times
http://i.imgur.com/VOIr7lC.png

**Comment by tbrosman** [comment]
I am also looking for a solution to this. I tried messing with the scaling settings (under Compatibility Mode) and got the same behavior for all three overrides. Disabling/changing the ClearType rendering settings for Windows did not help.

**Comment by Clonkex** [comment]
+100, I thought I was imagining things, it's pretty awful. Hurts my eyes, but I hate to change fonts...

**Comment by michalpl7** [comment]
Same issue is also in Putty, seems related to font Courier New ( broken? ) and ClearType technology ON. With ClearType disabled it looks ok, but fonts in different apps are worse looking.

**Comment by stevie6969** [comment]
Microsoft fiddled with the fonts -- in the German support section, a Microsoft person suggested that someone opens a ticket in their FeedbackHub and they did. If enough people vote for that ticket, Microsoft will eventually look into this, so please vote this up: https://aka.ms/O4qeld. Here's the original discussion (in German): https://answers.microsoft.com/de-de/windows/forum/windows_10-start/creators-update-1703-courier-new-schriftart-font/c6a91f0f-a1ee-45f1-89b9-34ec59d06743

**Comment by MetaChuh** [comment]
please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins if you update from version 7.5.9 or below.
if your issue still persists, and it is still of relevance, please feel free to file a new issue as easy to understand and reproducible as possible.

thank you for your help and best regards.
