### ISSUE TITLE
[Feature Request] Multiple line column marker

### ISSUE THREAD

**Issue by Gp741** [notepad-plus-plus/notepad-plus-plus#3128]
I'm using Notepad++ to edit text files for a program called Nastran.
 Nastran uses a very strictly positioned "card" language, so that each card takes exactly 8 characters wide.
It'd be helpful to have a vertical guide every 8 characters like EditPlus does.
Example: http://oi58.tinypic.com/rr1u0i.jpg
Can you implement this feature? It would be super useful for my jobs and  many other Nastran users in the world.

**Comment by crayxt** [comment]
Although this is possible in Scintilla (http://www.scintilla.org/ScintillaDoc.html#SCI_MULTIEDGEADDLINE), it appeared in Scintilla 3.7.0 while npp is still at 3.56

**Comment by johnferg** [comment]
+1

**Comment by dinkumoil** [comment]
I wrote a plugin that can add an arbitrary number of vertical lines to Notepad++ v7.7 and higher. Its name is _ExtSettings_. You can download it [>>> here <<<](https://sourceforge.net/projects/extsettings/). It will also be available soon via _PluginsAdmin_.

**Comment by johnferg** [comment]
Thank you! It's works great!

**Comment by johnferg** [comment]
It seems I spoke too soon :( The ExtSettings plugin appears to cause a problem when using Notepad++ in conjunction with Git. When I try to save a Git commit message in Notepad++ I get:

error: There was a problem with the editor 'notepad++'.
Please supply the message using either -m or -F option.

To reproduce:
1. Install the ExtSettings plugin
2. Add the following to your .gitconfig
[core]
   editor = notepad++
3. Try to commit a change to a project using Git

**Comment by sasumner** [comment]
@johnferg Please find an appropriate place to report problems with the ExtSettings plugin.  This isn't it.

**Comment by dinkumoil** [comment]
@johnferg 

You can report a bug at the project's site: https://sourceforge.net/projects/extsettings/

If you don't have and don't want to create a _SourceForge_ account go to the community forum to [this thread](https://notepad-plus-plus.org/community/topic/18214/new-plugin-extsettings):

**Comment by johnferg** [comment]
Thanks but I found a workaround, which others on this thread may potentially find useful. I used the -noPlugin flag in my git config as follows:

    editor = "'C:/Program Files/Notepad++/notepad++.exe' -noPlugin"

**Comment by johnferg** [comment]
Another option is to use the LuaScript plugin. (This is what I went with in the end as it can be used in conjunction with Git without having disable all plugins.)

See https://community.notepad-plus-plus.org/topic/17626/plugin-update-luascript-v0-9-supports-scintilla-v4-1-4

It even gives the example of setting multiple edge lines, i.e.

editor.EdgeMode = EDGE_MULTILINE
editor:MultiEdgeAddLine(40, 0x0000FF)
editor:MultiEdgeAddLine(60, 0x00FF00)
editor:MultiEdgeAddLine(80, 0xFF0000)

NOTE: The above script only works since LuaScript v0.9. There is a download link at the top of that page.

**Comment by thymaro** [comment]
This has been added as standard functionality in NPP v7.8.6.

Find it under `Preferences > Editing > Vertical Edge Settings`
