### ISSUE TITLE
[Feature Request] Auto convert language definition to upper case

### ISSUE THREAD

**Issue by murilocardoso** [notepad-plus-plus/notepad-plus-plus#3129]
I started to use notepad++ about 1 month ago. It's an incredible tool, but I miss an easy way to auto convert language definition to upper case. The old tool I used to code has a feature that converts to upper case while I'm typing.
I googled it and found some possible ways to do this, but not automatically as I expected.

**Comment by crayxt** [comment]
What is it, Caps Lock?

**Comment by murilocardoso** [comment]
Hi!
Yes, change some words defined in the language definition in upper case automatically while I am typing.

Here is a example:
Configure that "FUNCTION", "IF", and "END IF" are words that have to be change to upper case. 
When I type "function" and press space bar, automatically change "function" to "FUNCTION".

Thanks!

**Comment by MetaChuh** [comment]
please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins if you update from version 7.5.9 or below.
if your issue still persists, and it is still of relevance, please feel free to file a new issue as easy to understand and reproducible as possible.

thank you for your help and best regards.
