### ISSUE TITLE
Themes not available to all users after installation

### ISSUE THREAD

**Issue by daveloyall** [notepad-plus-plus/notepad-plus-plus#3130]
### Description of the Issue
The installer copies the `themes` directory and one `.xml` file for each theme to the *per user* `%AppData%` directory (under `Roaming\Notepad++`).

It only does that for the user that ran the installer.  Other users (non-admin users) can't load any of the theme files, because they are not installed anywhere under `C:\Program Files (x86)\Notepad++`.

### Steps to Reproduce the Issue
1. Use a computer with an administrative account and at least one non-administrative account.
1. Completely uninstall Notepad++ including per-user data under `%AppData%`.
1. Install Notepad++ using the admin user.  Make sure the checkbox for the Zenburn theme is selected.
1. After installation, run Notepad++ as a non-admin user.  You will be unable to select themes via the `Settings > Style Configurator...` menu.

### Expected Behavior
Themes!

### Actual Behavior
No themes!

### Debug Information
    Notepad++ v7.3.3   (32-bit)
    Build time : Mar  8 2017 - 03:37:37
    Path : C:\Program Files (x86)\Notepad++\notepad++.exe
    Admin mode : OFF
    Local Conf mode : OFF
    OS : Windows 10 (64-bit)
    Plugins : ComparePlugin.dll mimeTools.dll NppConverter.dll NppExport.dll PluginManager.dll

**Comment by AlanAlright** [comment]
While the following description does not solve the issue, it provides a workaround for it:
The admin user should login to their windows account and copy the "themes" folder from %AppData% Roaming/Notepad++/ and make the copy available for all users by pasting it in somewhere public, like the users/public/documents/ 
other users can access this location and copy the themes to their own %appdata% folders.

**Comment by The2rB** [comment]
Another workaround is to check the "Don't use %APPDATA%" option during installation.

![bilde](https://user-images.githubusercontent.com/5319973/35213348-9894e60a-ff5d-11e7-8307-65f476ef7763.png)

A bit unsure what the program will store in the install directory. So please make sure you check that before using this option if working on sensitive information. 
(For all I know all users then might share the currently open documents and recent documents. Might not be a good idea on a shared computer.)

**Comment by MetaChuh** [comment]
please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins if you update from version 7.5.9 or below.
if your issue still persists, and it is still of relevance, please feel free to file a new issue as easy to understand and reproducible as possible.

thank you for your help and best regards.
