### ISSUE TITLE
[feature request] syntax highlighting for windows commandline and AutoHotKey

### ISSUE THREAD

**Issue by JunkyardCat** [notepad-plus-plus/notepad-plus-plus#3133]
is it possible to inlcude these two language for notepad++?

**Comment by redmanmale** [comment]
@JunkyardCat 
There is syntax for windows cmd, it's called Batch.

**Comment by jNizM** [comment]
For AutoHotkey you can use this: https://autohotkey.com/boards/viewtopic.php?f=60&t=50

**Comment by MetaChuh** [comment]
please use one of the existing autohotkey udls.

many thanks and best regards.
