### ISSUE TITLE
Function List shows a wrong entry

### ISSUE THREAD

**Issue by jcrmatos** [notepad-plus-plus/notepad-plus-plus#3136]
Hello,

I have this code in a Python program
`if 'def ' in line and line.lstrip(' ')[0] != '#':`
and N++ considers it is a function and shows it in the Function List, like this
`'in line and line.lstrip(' ')[0] != '#':'`

My env is Win7P+SP1 x64, N++ 7.3.3 32b, Python 3.5.2 32b.

Best regards,

JM

**Comment by MAPJe71** [comment]
Thanks for reporting!
I will take it into account when updating the Python parser.

**Comment by ArkadiuszMichalski** [comment]
I can't reproduce above example in latest Notepad++ 7.9 RC4, but example from https://github.com/notepad-plus-plus/notepad-plus-plus/issues/1359 (should not be closed) still not works correct:
```
if 'def ' in line and line.lstrip(' ')[0] != '#':
     print("Hi")

def foo(x):
    return x * 10
#-- end def foo

def bar(y):
    return y / 10
#-- end def bar
```

Efect:

![a](https://user-images.githubusercontent.com/2730894/94348431-8c7d6d00-003c-11eb-83ba-a4d4f7f68b5b.gif)

**Comment by ArkadiuszMichalski** [comment]
I can't reproduce in latest 8.2.
![image](https://user-images.githubusercontent.com/2730894/149502443-ae02fed9-ee77-4eb1-aefc-3dd9c0382706.png)
