### ISSUE TITLE
Navigating with ctrl+left/right arrows will skip entire lines of text.

### ISSUE THREAD

**Issue by brotulix** [notepad-plus-plus/notepad-plus-plus#3137]
### Description of the Issue
When using ctrl+arrow keys in a normal text file with UTF-8 and Windows line endings I found that the cursor moved to the end of line instead of the expected one word over.

With a test file, I found that it will skip any (normal) word characters, and also full stops and spaces, but not CR, parentheses, colon, semicolon or comma.

Switching to Unix line endings, the cursor suddenly moves to the end of a line three lines down, so it seems LF is also a word character in this context.

### Steps to Reproduce the Issue
1. Create a new file (UTF-8, Windows LE). Write some text. I wrote:
```
Dette er en tekstfil. Den inneholder en tekst.
Dette er neste linje, og den inneholder også tekst, men nå med skandinaviske bokstaver og komma.
Dette er en linje med kolon. Kolon (:) og semikolon (;) er ganske like.
Denne linja har bare parentes (ingen kolon).
Denne linja har bare semikolon; ingen parentes.
Denne linja har bare: kolon.
Denne linja har to tegn med nokså lik funksjon; semikolon og komma, men komma er annerledes.

Denne linja er etter en tom linje.
```

2. Use ctrl + left/right arrow keys to move around the text and note where the cursor will stop:
- beginning and end of all lines
- before and after groups of punctuation, including ,:;(), but excluding . (full stop)

3. Switch to Unix LE.

4. Use ctrl + left/right arrow keys to move around the text and note where the cursor will stop:
- beginning of line 1, but not the end of any lines except EOF
- before and after groups of punctuation, including ,:;(), but excluding . (full stop)

### Expected Behavior
The cursor should stop at every transition from word and numerical characters (in my case the normal latin characters, plus my regional extras) to punctuation and spaces.

### Actual Behavior
The cursor skips spaces, full stops and LF, so moving two words forward becomes tedious.

### Debug Information
Notepad++ v7.3.3   (64-bit)
Build time : Mar  8 2017 - 03:39:58
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 7 (64-bit)
Plugins : mimeTools.dll NppConverter.dll

**Comment by goldenjm** [comment]
I'm experiencing this bug too and would love to see a fix.  I'm on Windows 10 and using Windows line endings.

**Comment by jasonmansfieldcf** [comment]
Also experienced this issue. Upgrading to v7.4.2 resolved it.

**Comment by goldenjm** [comment]
Thanks @jasonmansfieldcf!  I just upgraded to 7.4.2 as well and it resolved this issue for me too.

**Comment by brotulix** [comment]
Good to hear, @jasonmansfieldcf ! I'll upgrade and test at work tomorrow.

**Comment by dail8859** [comment]
This bug hasn't been reported in a while and hopefully c63673a1d8f4774bfcbd01c11d7cb4fc09b9fb2c was the actual fix to it in v7.4 and afterwards. If you run into this issue again please reopen.

**Comment by brotulix** [comment]
Sorry, hectic days and completely forgot to reply. It works for me, too, with 7.4.2. Thanks!

**Comment by nonplayer** [comment]
I am experiencing this exact issue with text files in 7.5.5. I had experienced it before last year, and upgrading fixed it. This time, nothing I do seems to bring about a resolution. Uninstall/reinstall neither.

7.5.5 x64 on Win10 pro
