### ISSUE TITLE
Parenthesis characters not used as delimiters for words

### ISSUE THREAD

**Issue by NeimadG** [notepad-plus-plus/notepad-plus-plus#3141]
### Description of the Issue

A double-click on a word followed or preceded by ')' and/or '(' selects the word + ')' and/or '('

### Steps to Reproduce the Issue

1. Fresh install of NP++ 7.3.3 64 French on Windows 10 64 pro
2. in a new text file, type
`this.function(parameter) stops
`
3. Double-click on "parameter"

### Expected Behavior

Selection should be "parameter"

### Actual Behavior

Selection is "function(parameter)"

Same with `this.function"parameter" stops
`

It works fine with {}'-[], I did not test more characters

**Comment by MetaChuh** [comment]
not reproducible in notepad++ 7.6.6
