### ISSUE TITLE
Notepad++ shouldn't print style background colors

### ISSUE THREAD

**Issue by sistormhawk** [notepad-plus-plus/notepad-plus-plus#3144]
### Description
When printing while using the style "Deep black" the blackgrounds gets printed which is a waste of ink or toner.

1. Select style "Deep black" 
2. Write any text
3. Print it

### Expected behavior
I expect that text gets printed the way it would be with default style. 

### Actual Behavior

###Debug Infos
Notepad++ v7.3.2   (32-bit)
Build time : Feb 12 2017 - 23:15:39
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10 (64-bit)
Plugins : mimeTools.dll NppConverter.dll NppExport.dll NppFTP.dll NppTextFX.dll PluginManager.dll XMLTools.dll

**Comment by donho** [comment]
Choose "no background color" in Preferences dialog's print section.

**Comment by stewartnjohnston** [comment]
On my version of Notepad++ V7.9.1 (64-bit) I need to restart the app before the print settings take affect.
