### ISSUE TITLE
escaped single quote always returns a match in a regex search

### ISSUE THREAD

**Issue by l00p0** [notepad-plus-plus/notepad-plus-plus#3146]
### Description of the Issue
escaped single quote always returns a match in a regex search

### Steps to Reproduce the Issue
1. Open a file that does not contain an apostrophe/single quote (ASCII=39)
2. (Ctrl+f) Search for: **\\'** and check _regex_ in the search type
3. You will get a match at the end of the file

### Expected Behavior
No match 

### Actual Behavior
empty match at eof

**Comment by MAPJe71** [comment]
I can confirm the issue.
However, there is no need to escape the single quote in a regular expression.
Just search for `'` or `\x27`.

**Comment by l00p0** [comment]
I thought this might point to an edge case that needs fixing up.

**Comment by MetaChuh** [comment]
don't escape `'` in regex searches with the current boost engine.

many thanks and best regards.

**Comment by sasumner** [comment]
Just why the heck DOES this match this way, anyhow?

**Comment by MetaChuh** [comment]
@sasumner 

an easter egg from the boost developers ? 😉

**Comment by sasumner** [comment]
I think there has to be more to it than that though...
