### ISSUE TITLE
Question: how to target PHP classes and functions when syntax highlighting?

### ISSUE THREAD

**Issue by u01jmg3** [notepad-plus-plus/notepad-plus-plus#3148]
How would you target syntax highlighting `render` (custom function) and `Exception` / `SomeException` (class)?

In N++, looking at the default `stylers.xml` for style configuration, there is no option to style functions or classes. 

`QUESTION MARK, DEFAULT, STRING, STRING VARIABLE, SIMPLESTRING, WORD, NUMBER, VARIABLE, COMMENT, COMMENTLINE, OPERATOR`

Is there a way? Here is my example code.

```php
<?php
    /**
     * Render an exception into an HTTP response.
     *
     * @param  \Illuminate\Http\Request $request
     * @param  \Exception               $exception
     * @return \Illuminate\Http\Response
     */

    public function render($request, Exception $exception)
    {
        if ($exception instanceof SomeException) {
            // return an HTTP response describing the exception...
        }


        return parent::render($request, $exception);
    }
```

**Comment by MetaChuh** [comment]
for non source code related questions, like customised lexer scripts, please visit us at the [<kbd>notepad++ community forum</kbd>](https://notepad-plus-plus.org/community/)

many thanks and best regards.
