### ISSUE TITLE
Add new menu

### ISSUE THREAD

**Issue by zyu47** [notepad-plus-plus/notepad-plus-plus#3149]
How do you add a new top-level menu like "File", "Edit"... in NPP?

**Comment by tergabri** [comment]
**notepad_plus.rc** is your starting point.

It reproduces the whole structure.
If you start with this you will be able to proceed


BEGIN
    POPUP "&File"
    BEGIN
        MENUITEM "&New",                             IDM_FILE_NEW
        MENUITEM "&Open...",                         IDM_FILE_OPEN
		POPUP "Open Containing Folder"
		BEGIN
            MENUITEM "Explorer",       IDM_FILE_OPEN_FOLDER
            MENUITEM "cmd",            IDM_FILE_OPEN_CMD
		END
		MENUITEM "Open Folder as Workspace...",      IDM_FILE_OPENFOLDERASWORSPACE
        MENUITEM "Re&load from Disk",                IDM_FILE_RELOAD
        MENUITEM "&Save",                            IDM_FILE_SAVE
        MENUITEM "Save &As...",                      IDM_FILE_SAVEAS
        MENUITEM "Save a Copy As...22",                IDM_FILE_SAVECOPYAS
        MENUITEM "Sav&e All",                        IDM_FILE_SAVEALL
        MENUITEM "Rename...",                        IDM_FILE_RENAME
        MENUITEM "&Close",                           IDM_FILE_CLOSE
        MENUITEM "Clos&e All",                       IDM_FILE_CLOSEALL
		POPUP "Close More"
		BEGIN
.....
      END
END

**Comment by SinghRajenM** [comment]
@MetaChuh this issue can be closed.
