### ISSUE TITLE
doesn't display Half-width kana japanese characters correctly

### ISSUE THREAD

**Issue by clfsoft** [notepad-plus-plus/notepad-plus-plus#3151]
### Description of the Issue
doesn't display Half-width kana japanese characters correctly
https://en.wikipedia.org/wiki/Half-width_kana
event npp doesent display correctly, npp do search the text correctly.

### Steps to Reproduce the Issue
1. copy {  ｴ  } to the new text file
2. npp just display a square box

### Expected Behavior
display {  ｴ  } not a {□} 

### Actual Behavior
display  {□}

**Comment by MetaChuh** [comment]
please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins if you update from version 7.5.9 or below.

<img width="964" alt="" src="https://user-images.githubusercontent.com/45773305/57084815-4747f500-6cfb-11e9-8e6f-f6805bdf6084.png">

thank you for your help and best regards.
