### ISSUE TITLE
'On Selection' MenuItem and it's subitems are not translated to pt_BR

### ISSUE THREAD

**Issue by hugonmelo** [notepad-plus-plus/notepad-plus-plus#3155]
### Steps to Reproduce the Issue

1. Open Notepad++;
2. Settings -> Preferences -> General;
3. Localization drop down -> select 'Português brasileiro' -> Close;
4. Verify that, under the 'Edit' menu, the 'On selection' item and it's subitems are in english.

### Expected Behavior
All MenuItems and subitems should be in brazilian portuguese.

### Actual Behavior
'On Selection' MenuItem and it's subitems are in english.

### Debug Information

Notepad++ v7.3.3 (32-bit)
Build time : Mar 8 2017 - 03:37:37
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : ON
OS : Windows 7 (64-bit)

![issue](https://cloud.githubusercontent.com/assets/3393479/24923991/ac543f76-1ec9-11e7-87c9-5adbe00045a7.png)

**Comment by MetaChuh** [comment]
please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins if you update from version 7.5.9 or below.
if your issue still persists, and it is still of relevance, please feel free to file a new issue as easy to understand and reproducible as possible.

thank you for your help and best regards.
