### ISSUE TITLE
auto completion function (BUG)

### ISSUE THREAD

**Issue by coldev** [notepad-plus-plus/notepad-plus-plus#3156]
hello i haves the last 7.3.3 notepad ...

my language haves more 20 custom functions...

auto complete only list first 10 definitions...

please help ..

my definition files xml to test...
[download](http://www.mediafire.com/file/gj0bph45l64buwi/notepad_test_autocompletion_bug.rar)

**Comment by coldev** [comment]
please help......

auto complete functions haves a Bug.. please Help...!!!

**Comment by MAPJe71** [comment]
Also posted and possibly answered on [forum](https://notepad-plus-plus.org/community/topic/13631/auto-completion-function-bug).

**Comment by coldev** [comment]
Thanks 4 your reply... God Bless You

Then i order the xml keys and works !!!

i use this tool to order..
https://github.com/gbsandeep/XmlSorter

sortxml.exe  -i ../bennugdClasified.xml -o ../bennugd.xml  -d 2
