### ISSUE TITLE
It has not been possible to validate the integrity of 'PluginManager.dll'

### ISSUE THREAD

**Issue by PKnaggs** [notepad-plus-plus/notepad-plus-plus#3159]
### Description of the Issue
> It has not been possible to validate the integrity of 'PluginManager.dll' needed to install
> or update a plugin

### Steps to Reproduce the Issue
Attempting to update the Plugin Manager plugin.

### Debug Information
Notepad++ v7.3.3   (32-bit)
Build time : Mar  8 2017 - 03:37:37
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : ON
Local Conf mode : OFF
OS : Windows 10 (64-bit)
Plugins : ccc.dll ComparePlugin.dll HTMLTag_unicode.dll JSMinNPP.dll mimeTools.dll NppConverter.dll NppExport.dll PluginManager.dll XMLTools.dll

**Comment by dail8859** [comment]
Please report this to the developers of the PluginManager [here](https://github.com/bruderstein/nppPluginManager/issues).
