### ISSUE TITLE
Better "Save as...." dialog on Windows 7

### ISSUE THREAD

**Issue by sbrl** [notepad-plus-plus/notepad-plus-plus#316]
In Notepad++ (Windows 7), is there a way to change the "Save As..."  Dialog Box? I would like to use the standard Windows 7 Save As dialog box instead.

Notepad++ uses this dialog box for saving: 
![Current save as dialog](https://cloud.githubusercontent.com/assets/9929737/8340056/dbe84de8-1ab3-11e5-8ed3-10348c1027af.png)

I would like to use the following dialog box: 
![enhanced save as dialog](https://cloud.githubusercontent.com/assets/9929737/8340024/9a9c3944-1ab3-11e5-9f56-46e783e4f13e.png)

*(This question is adapted from [here](http://stackoverflow.com/q/30714435/1460422) because I really want this.)*

**Comment by milipili** [comment]
see #176

**Comment by sbrl** [comment]
@milipili Thanks :)

**Comment by deelaka** [comment]
This needs to be addressed...

**Comment by sbrl** [comment]
@deelaka The issue #176 looks to be similar to this one.

**Comment by dail8859** [comment]
Currently implemented.

**Comment by GnstheGrain** [comment]
Is there some registry tweak for Windows User to force all application to use the new open-save dialog box  (or redirect any application calling for the old api, to the new one) .. ?

**Comment by sbrl** [comment]
@GnstheGrain I shouldn't think so. Each Open / Save box isa different API, IIRC.

**Comment by GnstheGrain** [comment]
@sbrl well, there are 2 Open / Save Api (as far as i know) on windows. Did you mean Each application has hard-coded calling implementation to those API ?
That's what I think, but i'm sure some Registry Guru somewhere found a way to redirect those call to the new "Open/Save item dialog" ... still google isn't a friend of us anymore ...

**Comment by sbrl** [comment]
@GnstheGrain Yep, they that is correct I believe. Each API is different, and so to support both you'd have to write a compatibility layer, which increases complexity.

The registry is used to store application and system settings. I can't see how you could use it to redirect calls from one API to the other. You would need to intercept the API calls and act as a proxy of sorts, but I have no idea how that would work. Learning C# + WPF might help you understand.

Note that this information comes from a C# + WPF background. Notepad++ may or may not use C#/ WPF / .NET, but the principal should be the same.
