### ISSUE TITLE
YAML/YML Should Open as UTF-8

### ISSUE THREAD

**Issue by sirberus** [notepad-plus-plus/notepad-plus-plus#3166]
### Description of the Issue
An opened YML file defaults to ASCII, should be UTF-8.

### Steps to Reproduce the Issue
1. Save a file as 'foo.yml' with a unicode character (I used the open book 📖)
2. Close NP++ and reopen.
Note: do not save as 'foo.yaml' as this is not presently recognized in NP++ as a YAML file extension.

### Expected Behavior
The file should contain 📖. Per the YAML specification, this behavior seems to be the expectation. Per [the documentation](http://www.yaml.org/spec/1.2/spec.html#id2771184): "The recommended output encoding is UTF-8. If another encoding is used, it is recommended that an explicit byte order mark be used, even if the first stream character is ASCII."

### Actual Behavior
You'll see the file will display as ASCII (I see ðŸ“–) despite being saved as UTF-8 and despite containing a unicode symbol (Settings -> MISC -> 'auto-detect encoding' fails to recognize)

**Comment by MetaChuh** [comment]
please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins if you update from version 7.5.9 or below.
if your issue still persists, and it is still of relevance, please feel free to file a new issue as easy to understand and reproducible as possible.

thank you for your help and best regards.

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
(no extra account is needed, just use your github account to sign in)
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)
