### ISSUE TITLE
Process locked up during upgrade if an open file is modified (Windows 10)

### ISSUE THREAD

**Issue by JakeQZ** [notepad-plus-plus/notepad-plus-plus#3167]
### Description of the Issue

If an open file is modified during upgrade of Notepad++, the process entirely locks up on Windows 10.

### Steps to Reproduce the Issue

1. Open some files in Notepad++
2. Close it.
3. Wait until a new version is available.
4. Open Notepad++ and see the dialog box 'A new version is available'
5. Modify one of the files open in Notepad++ via some other process.
6. Click 'Yes I want to update' (or whatever Notepad++ actually says)
7. Click 'I started this operation myself' (or whatever Windows actually says)

### Expected Behavior

Seamless upgrade to new version.

### Actual Behavior

Process was locked with two dialog boxes open (one about the upgrade, and one about the changed file), needed task manager to kill.

### Debug Information
I am not sure of the precise ordering of steps 5-7, but basically an open file was modified whilst N++ was about to be updated, and the symptoms and lockup seemed like the classic "you've got more than one dialog box open in Windows" problem.

**Comment by MetaChuh** [comment]
please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins if you update from version 7.5.9 or below.
if your issue still persists, and it is still of relevance, please feel free to file a new issue as easy to understand and reproducible as possible.

thank you for your help and best regards.

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
(no extra account is needed, just use your github account to sign in)
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)
