### ISSUE TITLE
[Question] Do NPP really improve using x64 version?

### ISSUE THREAD

**Issue by benyaminl** [notepad-plus-plus/notepad-plus-plus#3168]
Hello, I see the new NPP64 is realeased, but is it really working well or just another placebo effect and it's better to stick with 32bit version? Thanks

**Comment by MetaChuh** [comment]
we waited 2 years for the answer, to be able to tell you, that it has been proven to be fast and reliable for the last 2 years 😉

thanks, and our apologies for the delay.
