### ISSUE TITLE
Options-> Auto-Complete does not remember user defined Auto-Inserts for pair 1..3

### ISSUE THREAD

**Issue by ghost** [notepad-plus-plus/notepad-plus-plus#3171]
### Description of the Issue

I do use a user defined language setting for Code highlighting. 
Notepad++ is used with the German frontend.
Additionally I've set in Auto-Completion->Auto-Insert-> a Matched pair one with < and >
After closing and reopening notepad++ there is a >50% chance that the Matched pair setting is not more part of the configuration, instead you get again empty input fields.

### Steps to Reproduce the Issue

1. Open Settings->Preferences->Auto-Completion->Auto-Insert
2. Set for Matched pair 1 < and > 
![notepad-pp](https://cloud.githubusercontent.com/assets/27666805/25080959/afe76104-2347-11e7-83c9-cd560994d80e.PNG)
3. Close the window, make sure  settings are working
4. File-> Exit Notepad++
5. Start Notepad++ again
6. Auto completion for <> will not work anymore
7. If you check Settings->Preferences->Auto-Completion->Auto-Insert you will see that 
7.a your settings are lost (In this case you have to enter again the values)
7.b OR settings are still displayed but will not work.  (In this case, if you close now the window, you have the open completion settings working again)

### Expected Behavior

Auto-Completion->Auto-Insert->Matched Pair settings should be remembered after restart. 

### Actual Behavior

Auto-Completion->Auto-Insert->Matched Pair settings are lost

### Debug Information

N/A

**Comment by infomast** [comment]
Hello,
I have the same issue, with french frontend.

**Comment by rrizwanahmed** [comment]
facing same issue, any luck ? any solution?

**Comment by Ekopalypse** [comment]
Found that just opening/closing settings dialog is enough to make it working again.

Notepad++ v7.7.1   (64-bit)
Build time : Jun 16 2019 - 21:24:47
Path : D:\...\notepad++.exe
Admin mode : OFF
Local Conf mode : ON
OS : Windows 7 (64-bit)
Plugins : none

**Comment by rrizwanahmed** [comment]
> Found that just opening/closing settings dialog is enough to make it working again.
> Hopefully useful information to find out what might cause this.
> Tested on:
> Notepad++ v7.7.1 (64-bit)
> Build time : Jun 16 2019 - 21:24:47
> Path : D:...\notepad++.exe
> Admin mode : OFF
> Local Conf mode : ON
> OS : Windows 7 (64-bit)
> Plugins : none

whats the suggestion? every time open/ close preference?

**Comment by Ekopalypse** [comment]
@rrizwanahmed - did you read the second sentence?
I added this to give a c++ developer the information that the code is there and it is working but only
after opening the preference dialog. So it must be related to some kind of initialization I guess.
As I'm not really good in c++ this is as far as I can help.
