### ISSUE TITLE
Saving trouble

### ISSUE THREAD

**Issue by NeithaOsiris** [notepad-plus-plus/notepad-plus-plus#3176]
### Description of the Issue

when I try to save a file in my Notepad++ when I go to look for it again it isn't the kind of file I saved it as e.g when I try to save a HTML file I say that I want it saved but when I go to it later it doesn't have the .html name thing at the end I dunno if it's my computer being stupid or my version of notepad++

### Steps to Reproduce the Issue

honestly I don't know how to reproduce this but all I know is something is wrong with my version of this software or something is wrong with my computer
### Expected Behavior

I hoped that when I saved it as a specific file that it stays as that specific file instead of a general "All Types (*.*)" file
### Actual Behavior

every time I save something it goes to an All Types (*.*) not matter what I put in it
### Debug Information
Notepad++ v7.3.3   (32-bit)
Build time : Mar  8 2017 - 03:37:37
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10 (64-bit)
Plugins : mimeTools.dll NppConverter.dll NppExport.dll PluginManager.dll 

![notepad problem](https://cloud.githubusercontent.com/assets/27719990/25115521/45441fdc-244a-11e7-8887-8f589c5e0e4e.JPG)

**Comment by MetaChuh** [comment]
please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins if you update from version 7.5.9 or below.
if your issue still persists, and it is still of relevance, please feel free to file a new issue as easy to understand and reproducible as possible.

thank you for your help and best regards.

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
(no extra account is needed, just use your github account to sign in)
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)
