### ISSUE TITLE
Malayalam Translation

### ISSUE THREAD

**Issue by roshan0** [notepad-plus-plus/notepad-plus-plus#3178]
Hello Ho Don,

                      Here by i have attached Malayalam language binary translations file for Notepad++. So i kindly request you to accept Malayalami(Indian) language binary translations file for Notepad++ and include it in the future release.

Thank you.

With Regards,

Roshan Rathod.
[Malayalam.zip](https://github.com/notepad-plus-plus/notepad-plus-plus/files/927472/Malayalam.zip)

**Comment by SinghRajenM** [comment]
Create PR and close this issue.

**Comment by MetaChuh** [comment]
closing as outdated translation.
