### ISSUE TITLE
Small spelling mistake.

### ISSUE THREAD

**Issue by JimF42** [notepad-plus-plus/notepad-plus-plus#318]
In the Preferences dialog under "Delimiter selection settings", "blah" has been misspelled as "bla".

http://www.oxforddictionaries.com/us/definition/american_english/blah

Other than that, it seems perfect to me! :+1: (I figured it's worth at least a grin)

**Comment by MAPJe71** [comment]
:grin:

**Comment by MetaChuh** [comment]
after 4 years: closed with a grin 😁
