### ISSUE TITLE
Multi-line tab looks strange now

### ISSUE THREAD

**Issue by wilkowy** [notepad-plus-plus/notepad-plus-plus#3181]
The changelog states:
5. Improve multi-line tab: maintaining the selected tab position.

However the tab-bar looks ugly now (WinXP): https://s14.postimg.org/ihg9zbxm9/mlt.png
And this is even worse with longer filenames - it makes more lines (for example 3 instead of 2 for the same files opened).

Could we have an option to switch between normal tab bar and push-button version?

N++ 7.3.3 // WinXP 32b SP3

**Comment by MAPJe71** [comment]
Duplicate: #3007, #3090.

**Comment by ArkadiuszMichalski** [comment]
@donho @sasumner Is it still valid since the above duplicates have been closed?

**Comment by sasumner** [comment]
Regardless....closing.
