### ISSUE TITLE
Changing "Folder Margin Style" requires restart

### ISSUE THREAD

**Issue by wilkowy** [notepad-plus-plus/notepad-plus-plus#3182]
Changing "Folder Margin Style" requires N++ restart to take effect. Selecting different modes causes weird visual glitches on fold-marker margin (vanishing, showing only markers without lines) until N++ gets restarted.

N++ 7.3.3 // WinXP 32b SP3

**Comment by dail8859** [comment]
There is PR https://github.com/notepad-plus-plus/notepad-plus-plus/pull/2949 open that should address these issues if it gets merged.

**Comment by donho** [comment]
https://github.com/notepad-plus-plus/notepad-plus-plus/commit/b45b10385ff3b5a5966514d2d0cdd5f42c2771d3
