### ISSUE TITLE
Compiler identifier conflict between pluginsmanager and Scintilla

### ISSUE THREAD

**Issue by wnewbery** [notepad-plus-plus/notepad-plus-plus#3183]
### Description of the Issue
Was testing some personal plugin stuff against the current head 

### Steps to Reproduce the Issue
Compile any source file including both `powereditor/src/misc/pluginsmanager/Notepad_plus_msgs.h` and `scintilla/include/platform.h` (has stuff for external lexers).

https://github.com/notepad-plus-plus/notepad-plus-plus/blob/master/PowerEditor/src/MISC/PluginsManager/Notepad_plus_msgs.h#L49
https://github.com/notepad-plus-plus/notepad-plus-plus/blob/master/scintilla/include/Platform.h#L471

Change was made by 3dfe526019a66be4cac540affbf17dc833bf51b6

Note that while there is an optional `Scintilla` namespace using `SCI_NAMESPACE` (which only leaves their macros to worry about), notepad-plus-plus, `plugininterface.h` wont compile in that case.

### Expected Behavior
Identifiers should be unique within a given namespace.

### Actual Behavior
`error C2011: 'Platform': 'class' type redefinition` or similar depending on order and compiler.

### Workaround
Plugins can be compiled against an older or edited version of `Notepad_plus_msgs.h` with that change removed.

**Comment by MetaChuh** [comment]
please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins if you update from version 7.5.9 or below.
if your issue still persists, and it is still of relevance, please feel free to file a new issue as easy to understand and reproducible as possible.

thank you for your help and best regards.

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
(no extra account is needed, just use your github account to sign in)
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)
