### ISSUE TITLE
Add Scala syntax highlighting

### ISSUE THREAD

**Issue by gcoppex** [notepad-plus-plus/notepad-plus-plus#3184]
### Description of the feature request
Have the syntax highlighting support for the Scala language

**Comment by DavidHaslam** [comment]
Write your own custom language definition and submit it.

Oh look, someone already did. See [here](https://gist.github.com/MihailJP/4563140).

**Comment by chcg** [comment]
Otherwise support from a scintilla lexer would be required which is not available until now (v4.2.0)

**Comment by ArkadiuszMichalski** [comment]
Scintilla bug: https://sourceforge.net/p/scintilla/feature-requests/1084/.

**Comment by chcg** [comment]
The UDL mentioned above is also available at https://github.com/notepad-plus-plus/userDefinedLanguages/blob/master/UDLs/Scala_byMihailJP.xml.
