### ISSUE TITLE
NppExternalLexers.dll causes Notepad++ GNU Source code editor has stopped working.

### ISSUE THREAD

**Issue by James-Shaw** [notepad-plus-plus/notepad-plus-plus#3185]
### Description of the Issue
While using Notepad++ v7.3.3 (32-bit).
NppExternalLexers.dll causes Notepad++ GNU Source code editor has stopped working.

### Steps to Reproduce the Issue
1.  Have _Notepad++ v7.3.3 (32-bit)_ version installed.
2.  Have the _Plugin Manager_ updated to version 1.4.5.0.
3.  Choose the _Powershell Lexer_ stable version 1.0 from the available plugin list.
4.  Click _Install_. 
5.  Have the application restart immediately after the installation of the plugin.
6.  (Optional) Open Notepad++ from the start menu.

### Expected Behavior
Notepad++ should successfully restart and display the code editor.

### Actual Behavior
NppExternalLexers.dll dependency causes the _Notepad++ GNU Source code editor has stopped working_ exception preventing Notepad++ from executing.

### Debug Information
Notepad++ v7.3.3   (32-bit)
Build time : Mar  8 2017 - 03:37:37
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10 (64-bit)
Plugins : AutoSave.dll autosave2.dll ClipboardHelper.dll CodeAlignmentNpp.dll combine.dll ComparePlugin.dll EmmetNPP.dll Explorer.dll FingerText.dll HTMLTag_unicode.dll JSLintNpp.dll JSMinNPP.dll LightExplorer.dll MarkdownViewerPlusPlus.dll MenuIcons.dll mimeTools.dll MultiClipboard.dll NppAutoIndent.dll NppCalc.dll NppConverter.dll nppcrypt.dll NppExec.dll NppExport.dll NPPJSONViewer-win32.dll NppJumpList.dll NppRegExtractorPlugin.dll NppScripts.dll NppXmlTreeviewPlugin.dll PluginManager.dll PoorMansTSqlFormatterNppPlugin.dll Pork2Sausage.dll PythonScript.dll 

The _hotfix_ solution to getting Notepad++ to start up again without error is to remove the _NppExternalLexers.dll_ from the plugins folder.

**Comment by dail8859** [comment]
This either needs reported to the author of the NppExternalLexer DLL file or to the Plugin Manager developers to see if they want it removed from the list.

**Comment by James-Shaw** [comment]
Alright, thanks for responding so quickly dail8859!
