### ISSUE TITLE
multi-row tab isn't selected on right-click

### ISSUE THREAD

**Issue by jay** [notepad-plus-plus/notepad-plus-plus#3186]
### Steps to Reproduce the Issue
1. Right-click on a multi-row tab
2. Observe tab isn't selected
3. Select 'Move to recycle bin'
4. Observe prompt to move filename of currently selected tab to recycle bin

### Expected Behavior
When there is a single row of tabs and I right-click on a tab it is selected and then if I choose an action it applies to that selected tab. I would expect multi-row tabs to work the same way.

### Actual Behavior
multi-row tab isn't selected on right-click

### Debug Information
Notepad++ 7.3.3 32-bit

![multi-row tab isn't selected on right-click](https://cloud.githubusercontent.com/assets/965580/25213747/a17d5dc4-2560-11e7-9ad7-cffd3e33ce63.gif)

**Comment by AngryGamer** [comment]
I updated my pull request with a fix for this bug.

**Comment by jay** [comment]
Thanks, that works. Is the point of the pixels removal to make the border disappear or match the left border? On my screen at 125% it looks like this:

Before #3110:
![before](https://cloud.githubusercontent.com/assets/965580/25245988/458390e6-25d4-11e7-8418-6622a47e04c3.png)

After #3110:
![after](https://cloud.githubusercontent.com/assets/965580/25245993/4a8930a0-25d4-11e7-8acd-81d6fefada3c.png)

Same pixel width horizontal and vertical looks like something like this( I used mspaint):
![suggestion](https://cloud.githubusercontent.com/assets/965580/25246015/5991302a-25d4-11e7-94e2-2e9080342b16.png)

**Comment by AngryGamer** [comment]
> Is the point of the pixels removal to make the border disappear or match the left border?

@jay The objective was to mimic the tab style (single line of tabs). I believe the margin is relatively close to that. However, if you believe the mspaint mockup looks better, that can be done too.

**Comment by jay** [comment]
I don't know how it should look. I'd guess everyone has a different opinion. I posted the difference so you could see in case it was a bug. I have a display set at 125% and occasionally I find some quirks in programs because of that. So I figured I'd illustrate it since I wasn't sure of your intention. I've been using your CI PR build for the last hour or two and it seems to be working fine. Thanks again.
