### ISSUE TITLE
SQL language option treats \ as an escape character, when SQL does not (V7.3.3)

### ISSUE THREAD

**Issue by XLZ1787** [notepad-plus-plus/notepad-plus-plus#3187]
### Description of the Issue
When using the Language plugin for SQL, the \ character causes the 

### Steps to Reproduce the Issue
1.  Paste the following into a new file window.
SELECT 'X' from ATABLE
WHERE FILESTRING = 'C:\Temp\Folder\'
AND FILENAME = 'tempfile.txt'

2. Change the language to SQL

3. You'll see that the \ character causes the single quote text qualifiers to reverse for the next two lines of script. This is incorrect behavior for SQL.

4. To confirm this, delete the above script and paste in the following, noting the additional single quote
SELECT 'X' from ATABLE
WHERE FILESTRING = 'C:\Temp\Folder\''
AND FILENAME = 'tempfile.txt'

### Expected Behavior
\ characters within text strings should behave as they do in SQL.

### Actual Behavior
\ characters still act as escape characters even within SQL strings

**Comment by dail8859** [comment]
Settings > Preferences > MISC. > Treat backslash as escape character for SQL

**Comment by XLZ1787** [comment]
Why is it a preference when it's in direct contravention of the script language though?

**Comment by dail8859** [comment]
See: https://sourceforge.net/p/notepad-plus/patches/551/

Quote from the link:
> Backslash is an escape character in MySQL, but not in T-SQL and PostgreSQL.
