### ISSUE TITLE
64 bit Plugin Manager

### ISSUE THREAD

**Issue by bviktor** [notepad-plus-plus/notepad-plus-plus#3190]
7.3.3 still lacks the plugin manager. I can install 64 bit plugins (e.g. NppExec), they work fine when copied to the plugins directory manually, but it'd be handy to get the fancy UI back, thanks.

**Comment by dail8859** [comment]
You can manually download it here: https://github.com/bruderstein/nppPluginManager/releases

**Comment by bviktor** [comment]
Neat, there's already 7 "development" plugins available. Is there any good reason this isn't included in the Npp releases yet?

**Comment by bviktor** [comment]
Oh I see: https://github.com/bruderstein/nppPluginManager/issues/7

Is this the blocker for my issue?

**Comment by dail8859** [comment]
> Is there any good reason this isn't included in the Npp releases yet?> 

The 64bit version of the PluginManager is pretty recent. Even the 32bit version of the PluginManager hasn't been updated in a while, so I am not real sure as to any type of timeline.

**Comment by dail8859** [comment]
As of Notepad++ v7.5 the Plugin Manager is no long being shipped with Notepad++. See https://notepad-plus-plus.org/news/notepad-7.5-released.html

All Plugin Manager related issues should be reported to https://github.com/bruderstein/nppPluginManager/issues

**Comment by bviktor** [comment]
Ouch :)
