### ISSUE TITLE
Windows 10 4k 200% scaling - strange anti-aliasing look

### ISSUE THREAD

**Issue by milika** [notepad-plus-plus/notepad-plus-plus#3191]
### Description of the Issue
On win 10 (creators version) font looks strange, reddish to the extreme. With or without font smooting enabled in the app.
Clear-type is on but no other app exhibits this behavior.

### Steps to Reproduce the Issue
Open any file on win 10 creators on 200% scaling 4k display

### Expected Behavior
Normal anti-aliasing

### Actual Behavior
Strange reddish anti-aliasing..

### Debug Information
Notepad++ v7.3.3   (64-bit)
Build time : Mar  8 2017 - 03:39:58
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10 (64-bit)
Plugins : mimeTools.dll NppConverter.dll 

![npp](https://cloud.githubusercontent.com/assets/1072578/25262159/8341a166-2656-11e7-8365-2fb932fe1d68.png)

zoomed:
![npp2](https://cloud.githubusercontent.com/assets/1072578/25262211/c545f2ce-2656-11e7-82fa-d98aead0ebf8.png)

**Comment by MetaChuh** [comment]
please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins if you update from version 7.5.9 or below.
if your issue still persists, and it is still of relevance, please feel free to file a new issue as easy to understand and reproducible as possible.

thank you for your help and best regards.

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
(no extra account is needed, just use your github account to sign in)
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)
