### ISSUE TITLE
Restoring position after Ctrl+Tab does not take into account Word Wrap

### ISSUE THREAD

**Issue by sbil33** [notepad-plus-plus/notepad-plus-plus#3193]
Switching between (multi-page) documents using ctrl+tab with Word Wrap turned on and documents containing long (wrapped) lines does not restore document position correctly.

Steps to Reproduce:
(1) turn Word Wrap on,
(2) make line which is wrapped and copy-paste to form document several pages long,
(3) set position to the end or closer to the end of file,
(4) press ctr-tab to switch to any other document and then back.

Expected Behavior:
View is exactly the same as it was before switching to other document.

Actual Behavior:
Document is scrolled up, while cursor still remains at its position below visible part of document.

Looks like restoration of document position does not calculate wrapped lines.

**Comment by donho** [comment]
Cannot reproduce at all on my 32 bit version.

**Comment by sbil33** [comment]
Version 7.3.3 (32 bit).
Windows 8.1 64 bit.
Perfectly reproducible, at two different machines.

I understood the problem.
My window is unmaximized.
When window is maximized then it is not reproducible.
Visually it looks that right immediately document switched position is correct, but then a moment later goes repainting and scroll-bark jumps upward to invalid position.
