### ISSUE TITLE
Copyright year is ambiguous

### ISSUE THREAD

**Issue by mrrsn** [notepad-plus-plus/notepad-plus-plus#3195]
See the top line of
[PowerEditor/src/WinControls/Grid/BabyGrid.cpp](https://github.com/notepad-plus-plus/notepad-plus-plus/blob/51797bf59e689b11d80998758790f8a4cade68eb/PowerEditor/src/WinControls/Grid/BabyGrid.cpp)

**Comment by dail8859** [comment]
Please only report real issues.
