### ISSUE TITLE
Serious styling issue with notepad++ that has no serious solution in the style configurator

### ISSUE THREAD

**Issue by Benqzq** [notepad-plus-plus/notepad-plus-plus#3202]
In the last 2 years, and especially since [WSL](https://en.wikipedia.org/wiki/Windows_Subsystem_for_Linux) was released, I work much with `.sh` (Bash shell) scripts in Windows.

Sometimes, I organize these scripts as [heredocs](https://en.wikipedia.org/wiki/Here_document).

Heredocs in Notepad++ look just awful. Too awful to be worked with in their natural look:

![a](https://cloud.githubusercontent.com/assets/13021900/25304731/e33ba628-2775-11e7-801f-4d2649bbd9f8.PNG)

Now, imagine this file as much longer... All of it would be dyed like that...

Modifications with the style configuator **aren't helping** --- They make the edit to be unified in color, quite similar for editing a regular `.txt` file:

![76a86a36-2776-11e7-91a3-5ce649b4b874](https://cloud.githubusercontent.com/assets/13021900/25305773/098c4526-278a-11e7-82b2-ec448680eb87.PNG)

[Me and another N++ user tried to found a solution](https://superuser.com/questions/1147461/removal-of-notepad-styles-possible-i-mean-to-the-style-configurators-langua), but for vain.

# The solution I look forward to:

I want to work with `.sh` heredocuments without special styling. I don't want heredocuments to be styled in a special way, I want to enjoy the regular `.sh` graphics with heredocs, without any special styling for them.

**Comment by dail8859** [comment]
Heredocs are just normal strings. I'd assume under most circumstances it is not representing more Bash code, rather as arbitrary text. That being said...in some situations I can see why it is not useful for very large blocks to be a single color. Notepad++ uses a (mostly) unmodified version of [Scintilla](http://scintilla.org/) to do all the highlighting, so any changes would have to be accepted by that project (their issue tracker is [here](https://sourceforge.net/p/scintilla/bugs/))

**Comment by Benqzq** [comment]
I don't want to change anything in Scintilla, rather I just want their heredoc styling not to be implemented to my Notepad++. I would appreciate any solution you might have. It would be a most honored contribution.

**Comment by dail8859** [comment]
All that is hard-coded within Scintilla. There is no way to tell Scintilla to ignore or skip a style.

**Comment by dail8859** [comment]
Closing as this would have to be something implemented by Scintilla.
