### ISSUE TITLE
Double click select includes the comma as a letter in 7.3.3

### ISSUE THREAD

**Issue by dvdvideo1234** [notepad-plus-plus/notepad-plus-plus#3203]
### Description of the Issue
When a variable name is selected via double click it selects the variable name and the following comma

### Steps to Reproduce the Issue
1. Open notepad
2. Paste the following code inside a file
```lua
local stSpawn = asmlib.GetEntitySpawn(ePieceN,vTemp,model,pointid,actrad,spnflat,igntype,nextx,nexty,nextz,nextpic,nextyaw,nextrol)
```
3. Click on any function argument two times
### Expected Behavior
On double click only one function argument must be selected. For example when "actrad" is clicked it must select only it, not the entire line of arguments between "()"

### Actual Behavior
I double clicked on a variable name and the whole list of arguments got selected

### Debug Information
Not applicable

### Screenshot
[![mark_all.png](https://s9.postimg.org/yb445xmyn/mark_all.png)](https://postimg.org/image/p3bvp8fwb/)

**Comment by MRuy** [comment]
Same problem as #3192

**Comment by Manuela-Fereira** [comment]
And same as https://github.com/notepad-plus-plus/notepad-plus-plus/issues/3140

For me, the problem is irregular, may disappear after N++ restart, after Windows reboot, or after Windows update.

**Comment by dvdvideo1234** [comment]
@Manuela-Fereira 

Well it does not disappear after a notepad restart.
It is not even affected by the windows update, because at home I've got a new and old PC.
The older one I've disabled the Windows 7 updates and the newer one has all Windows 7 updates.
On both machines npp++ behaves the same way

**Comment by Yaron10** [comment]
This problem *occasionally* occurs on my machine too.
Restarting NPP solves the issue until next time.

**Comment by dvdvideo1234** [comment]
Installed the 32 bit version and now it works. Thank!
