### ISSUE TITLE
Data copied from Notepad++ to Ubuntu VPS is corrupted with CR chars and appear a bit messed up

### ISSUE THREAD

**Issue by Benqzq** [notepad-plus-plus/notepad-plus-plus#3205]
I am experiencing a problem related to copying files from Notepad++ to Nano:

I pasted the following script content into a script file in a remote Ubuntu 16.04 environment to which I SSH tunnel with WSL OpenSSH. I created the script file inside my remote system via:
`
nano ~/ses.sh && chmod +x ~/ses.sh && sh ~/ses.sh && rm ~/ses.sh`

The pasted content was corrupted with CR characters even though I canceled this in Notepad++ via `EOL conversion > Unix (LF)` and made sure all CRs are removed via `View > Show symbol > Show all characters`. 

The problem happens either if I use tabulations or not and seems to be caused by Notepad++, automatically adding these CR chars to the pasted data.

This is but part of the long script I pasted into nano in my remote machine (if you copy it for testing make sure to first transform all spaces to tabulations):

#!/bin/bash -x
function ses {

    # SETUP LAMP ENVIRONMENT:

		echo -e "\07" && echo -e "\077" # Insert password.
		apt-get install lamp-server^ -y && a2enmod rewrite && a2enmod deflate && a2enmod headers

		cat <<-'LAMPENV' >> /etc/apache2/apache2.conf
		#
		<Directory /var/www/>
		Options Indexes FollowSymLinks
		AllowOverride All
		Require all granted
		</Directory>
		#
		<ifmodule mod_expires.c>
		<Filesmatch "\.(jpg|jpeg|png|gif|js|css|swf|ico|woff|mp3)$">
		ExpiresActive on
		ExpiresDefault "access plus 8 days"
		</Filesmatch>
		</ifmodule>
		LAMPENV

In nano, I can see a Green box character wherever there is a Windows CR character. In the following image you can see a comparison with two phenomena. The first is the Green boxes added in pasting and the second is messing up of the data (some rows going up towards others) also a symptom of the corruption:

![image](https://cloud.githubusercontent.com/assets/13021900/25342060/78753cf6-2913-11e7-98f4-322c5b02f273.png)

I would appreciate your advice on how to best deal with this issue - If it is a bug, I will work cross platform with another editor until it is fixed. If I'm wrong and this problem can be solved from the program itself, please share how.

**Comment by dail8859** [comment]
To quote myself from another issue you already opened:

> ... whatever you are doing to get it into Bash (copy/paste, X11 fowarding, virtual machine, terminal emulator, etc) is more likely the cause.

There are too many other factors that could be the cause. If you feel Notepad++ is the problem, past the text into Windows' plain-old "Notepad" then inspect the file with a hex editor.

**Comment by Benqzq** [comment]
As I'm new to programming I don't have the knowledge to use hex editors at the moment though I might the usage soon. Anyway, When I paste it to a Windows Notepad `.txt` document there are no CR chars, so copy/paste isn't the cause. I don't use X11 or a Virtual machine. The last other option is the terminal emulator of CMD/WSL.
