### ISSUE TITLE
Find Next and Count fail to return all occurrences of overlapping instances of the search string

### ISSUE THREAD

**Issue by MarkBrodie** [notepad-plus-plus/notepad-plus-plus#3206]
### Description of the Issue

When using the 'Find Next' and 'Count' features in the find dialogue, finding specific substrings that overlap within the text being searched produces incorrect results, in that not all instances of the search string are found, and the number of matches reported by 'Count' is subsequently wrong as a result. (Found as a result of testing results of an assembly KMP string search implementation).

### Steps to Reproduce the Issue

1. Create a new blank document
2. Add the text 'aababcabcabcacbcabca' (no quotes)
3. Open the find dialog (Search -> Find... or Ctrl+F)
4. In the 'Find What:' field, enter 'abca' (no quotes)

5a. Press the 'Find Next' button several times, noting that only substrings starting at positions 3, 9 and 16 are highlighted, while the substring at position 6 is missed (using a 0 based position index).
5b. Press the 'Count' button, the status bar of the windows shows 'Count: 3 Matches.' where there are 4 matches in the document.

### Expected Behavior

For the case in 5a, all four substrings at positions 3, 6, 9 and 16 should be highlighted in sequence on subsequent presses of the 'Find Next' button.
For the case in 5b, the status bar of the windows should show 'Count: 4 Matches.' 

### Actual Behavior

For the case in 5a, pressing the 'Find Next' button several times resulted in only substrings starting at positions 3, 9 and 16  highlighted.
For the case in 5b, the status bar of the windows showed 'Count: 3 Matches.' 

### Debug Information

Notepad++ v7.3.3   (32-bit)
Build time : Mar  8 2017 - 03:37:37
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10 Pro (64-bit)
Plugins : HexEditor.dll mimeTools.dll NppConverter.dll NppExport.dll PluginManager.dll

**Comment by dail8859** [comment]
Though I can't say with certainty, I believe this is expected behavior as it only finds *non-overlapping* matches. I'm not aware of any other text editors that would find overlapping matches by default.

**Comment by MarkBrodie** [comment]
I did have a look at the source code after posting this, and indeed this behaviour does appear to be by design. It may be a candidate for a potential improvement in a future release, or even an option that can be toggled, but I guess my case was a little niche to be considered the default. Knowing the expected behaviour would have saved me a lot of headaches with attempting to debug my program though, so I thought it may be worth raising.

**Comment by dail8859** [comment]
> Knowing the expected behaviour

Documentation is very light when it comes to expected behavior :) so I understand the confusion. If you do need overlapping find/replace I'd suggest looking to some sort of scripting plugin for Notepad++ to do this for now. The one problem with overlapping matches would be replacing. In your example if you search "abca" there would be 4 overlapping matches but if you replace it with "xxxx" then there would only be 3 replacements...which may or may not be expected.

**Comment by MetaChuh** [comment]
the sequential nature of the find functions is as designed and expected.
while it could be an idea for a plugin, or a script+regex combination with e.g. the pythonscript or luascript plugins, it will not be implemented at the notepad++ core.

many thanks and best regards.
