### ISSUE TITLE
v7.3.3 - text "blinks / jitters / jumps" after cursor then typing. .php .html 

### ISSUE THREAD

**Issue by tcbend** [notepad-plus-plus/notepad-plus-plus#3207]
### Description of the Issue
When typing in an .html or .php document, all of the text after (below) the cursor blinks when I type. On each keystroke, the text "blinks". This can't be correct, as it's very distracting. I tried a few different files, and I saw the issue in .php and .html files, but NOT in .txt or .css files. I noticed the effect immediately after upgrading to v7.3.3 today. Video below.

### Steps to Reproduce the Issue

1. Open a .php or .html file
2. Type anywhere
3. Observe text

### Expected Behavior
Smooth non-blinking text when typing.

### Actual Behavior
Jittery distracting text after cursor (below) when typing, blinks on each keystroke.

### Debug Information
Notepad++ v7.3.3   (32-bit)
Build time : Mar  8 2017 - 03:37:37
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10 (64-bit)
Plugins : mimeTools.dll NppConverter.dll NppExport.dll PluginManager.dll 

VIDEO:
https://rogueeasyweb.tinytake.com/sf/MTU0NTA0Nl81MzQyNDM1

**Comment by MetaChuh** [comment]
please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins if you update from version 7.5.9 or below.
if your issue still persists, and it is still of relevance, please feel free to file a new issue as easy to understand and reproducible as possible.

thank you for your help and best regards.
