### ISSUE TITLE
Failed to play plugin from recorded macro

### ISSUE THREAD

**Issue by bero** [notepad-plus-plus/notepad-plus-plus#3211]
### Steps to Reproduce the Issue

I try to define a macro to replace `>` with `&gt;` etc

1. Load this text as XML
```xml
<?xml version="1.0" encoding="iso-8859-1"?>
<TableViewDefinition Name="View1">
  <ColumnDefinition Name="LateCancellation" Type="FLOAT"
        Ocl="buffPlannedTerms->select(termDescription = 'Late cancellation').currNetValue->sum">
  </ColumnDefinition>
  <ColumnDefinition Name="Loading" Type="FLOAT"
        Ocl="buffPlannedTerms->select(termDescription = 'Loading').currNetValue->sum">
  </ColumnDefinition>
  <ColumnDefinition Name="LongGoodsSurcharge" Type="FLOAT"
        Ocl="buffPlannedTerms->select(termDescription = 'Long goods surcharge').currNetValue->sum">
  </ColumnDefinition>
</TableViewDefinition>
```
2. Install XML Tools
3. Record macro to select text within "" ex
`  buffPlannedTerms->select(termDescription = 'Late cancellation').currNetValue->sum`
4. Select menu Plugins/XML Tools/Convert selection XML to Text
5. Stop record macro
6. Try play macro
### Expected Behavior

The replaced text should be 
```xml
      Ocl="buffPlannedTerms-&gt;select(termDescription = 'Late cancellation').currNetValue-&gt;sum">
```
### Actual Behavior

7. Replaced text is
```xml
        Ocl="b">
```

### Debug Information

Notepad++ v7.3.3   (32-bit)
Build time : Mar  8 2017 - 03:37:37
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 7 (64-bit)
Plugins : mimeTools.dll NppConverter.dll NppExport.dll NppFTP.dll PluginManager.dll SpellChecker.dll XMLTools.dll

**Comment by MetaChuh** [comment]
you can only use macros for internal functions
