### ISSUE TITLE
Feature Request: Left Cursor Movement to Stop at Left Margin

### ISSUE THREAD

**Issue by rodjt** [notepad-plus-plus/notepad-plus-plus#3212]
### Description of the Issue

I find that when moving the cursor left to the beginning of a line with the cursor [<-] left arrow the cursor will wrap to the end of the previous line if I move just one space to far. It is hard to judge just when to stop.

I am aware that I could always use the [home] key for this but when you are editing code close to the beginning of the line and moving around using the cursor keys it is much easier for it to stop on the margin than have to change to the [home] key.

There are other text editors that allow this and once you have used it, it becomes really important.
Of course the feature should be optional. Cursor stop on left margin [x] or [*].

I posted a request for this on the Notepad++ Community Plugin Development forum a couple of weeks ago and are very grateful to 'scott-sumner' for his help which lead to a solution via a Python script which I am currently using. The setup for this is fully summarized in the Community forum post.

**This request is for the 'Stop Left Wrap' function to be added to the NP++ Settings-Editor options. This would be much more simple than having to install the Python Plugin and script**

**Comment by alankilborn** [comment]
Implemented in N++ 8.4 as part of a "virtual space" feature.
See #11444 
Suggest that this issue be CLOSED.

**Comment by rodjt** [comment]
I have installed v8.4.4 and checked [Virtual Space] and it works a charm. For me this makes a huge improvement to the ease of use of Notepad++. Thanks to **alanlilborn** for this excellent addition. Now closed.
