### ISSUE TITLE
feature request: add "replace last" button in search and replace so don't jump past location of last desired replace

### ISSUE THREAD

**Issue by dvbrydon** [notepad-plus-plus/notepad-plus-plus#3214]
### Description of the Issue

When in the find and replace dialog, you click replace and it replaces that instance and jumps to the next.  But sometimes you are working on a local function and you come to the last replacement you want to make of that word, even though it appears later in the file.  You click replace, and it jumps you 300 lines down the file to the next instance.  

A replace last button in the dialog would replace that word and leave the cursor at the end of that word.

Ultraedit has this and it saves having to come back up the file to find the line you are working on.

### Steps to Reproduce the Issue

1.   ctrl+f to open find dialog.  click the replace tab.
2.  enter a word to find and a replacement.  click find.  click replace.  it jumps to next instance.

### Expected Behavior

3.  here we need the replace last button so the cursor will stay and not jump to the next instance.

### Actual Behavior

4.  it jumps down the file when I hit replace (correctly) but I have to come back up and find where I was.

**Comment by donho** [comment]
Implemented.

**Comment by dvbrydon** [comment]
This is awesome.  Thank you!!!
