### ISSUE TITLE
Use Byte Order Mark for .txt files with UTF-8

### ISSUE THREAD

**Issue by svrnwnsch** [notepad-plus-plus/notepad-plus-plus#3217]
### Description of the Issue

Txt-files with UTF-8 should use the [Byte Order Mark](https://en.wikipedia.org/wiki/Byte_order_mark) for UTF-8. This enables interoperability with other programs like LibreOffice.

### Steps to Reproduce the Issue

1. Create a new .txt file with just "ä" in it.
2. Save it to disc.
3. Open it with LibreOffice Writer
4. See Ã¤

### Expected Behavior

Safe file with correct Byte Order Mark `EF BB BF` at the beginning of the file.

### Actual Behavior

No Byte Order Mark in file.

### Debug Information

Notepad++ v7.3.3   (32-bit)
Build time : Mar  8 2017 - 03:37:37
Path : D:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 7 (64-bit)
Plugins : mimeTools.dll NppConverter.dll NppExport.dll NppFTP.dll PluginManager.dll 

[test-1.txt](https://github.com/notepad-plus-plus/notepad-plus-plus/files/960091/test-1.txt)
[test-1-bom.txt](https://github.com/notepad-plus-plus/notepad-plus-plus/files/960093/test-1-bom.txt)

**Comment by dail8859** [comment]
UTF-8 doesn't require a BOM, so there is a difference between "UTF-8" and "UTF-8-BOM". You can select the desired encoding under the `Encoding` menu. You can also set the default encoding for new files under `Settings > Preferences > New Document > Encoding`.

**Comment by svrnwnsch** [comment]
So this is a LibreOffice Writer bug?

**Comment by dail8859** [comment]
I can't say for sure. Some applications require a BOM, some do not. In some applications, if the file does not have a BOM then it tries to do a bit of analysis on the file (look at byte values, etc) to determine the encoding. It may be that the file is so small that LibreOffice has a hard time determining the encoding from just the 2 bytes...such that it shows `Ã¤` instead of `ä`.

**Comment by svrnwnsch** [comment]
Okay. This happened to a much larger file where I used notepad++ to remove all tabs. I reopened the [corresponding bug](https://bugs.documentfoundation.org/show_bug.cgi?id=60145) in bugzilla.
