### ISSUE TITLE
Auto-completion: Should list right (real) identifier only

### ISSUE THREAD

**Issue by KSXGitHub** [notepad-plus-plus/notepad-plus-plus#322]
1. For some reason, sometimes I must write "foo&bar", "for&&bar", "type&", "type\* ", "%foo%", "{foo}" ... Then, when I write that identifiers again, the auto-completion display "foo&", "foo&&bar", "type&", "type*", "foo%", "foo}" ... instead of "foo", "bar" and "type" which is real identifier.
2. When I write some word in string (i.e "Hello, World!!"), I don't want it list "Hello" and "World!!" (which is not identifier) when I write code outside of string. But it is pretty if they are displayed when I write inside of string.

**Comment by MetaChuh** [comment]
closed due to inactivity (4y)
