### ISSUE TITLE
Find in active/files returns same line multiple times

### ISSUE THREAD

**Issue by ecki** [notepad-plus-plus/notepad-plus-plus#3224]
### Description of the Issue
When I search in multiple files or in all active files I get a list of search results in the lower pane which is incredibly useful, thanks for this. However when using a search word which occurs multiple times in a line, it will show the line also multiple times (each time with another occurrence of the word higlited. In my cases for logfiles it is up to 10 times, which makes the result sometimes harder to read than the actual file.

I can see that this is sometimes useful, but most of the time it stops you from quickly scanning the list. So a feature in the search mask would be "report fond lines instead of found occurences" or something line that. From my point of view the new behavior would be the better default, but I am not sure what the motives for the current behavior is.

### Steps to Reproduce the Issue
Create 2 files in an empty dir, both containing
a
b b
a

Search for "b" in all files, you will receive 4 lines instead of 2:
file 1:
line 2: **b** b
line 2: b **b**
file 2
line 2: **b** b
line 2: b **b**

### Expected Behavior
Get a 
file 1
line 2: **b** **b**
file 2
line 2: **b** **b**

I see this in 7.3.2 32bit but it is like this for years.

**Comment by tergabri** [comment]
I don't think it is a bug because it make it easier to look for it.
For example if you look for b in a line with 1000 non 'b' characters, with one b in position 200 and 600 you will prefer to have it repeated. This will help you locate your 'b' characters.

I can try to implement something to fix it if we all agree it is a bug.

Hope that helps

**Comment by ecki** [comment]
This is a feature request (but I somewhat fail to see how this makes it any easier to see the multiple matches)

**Comment by bahusoid** [comment]
It helps you to find exact position in the string of each match by clicking on each result.
What is expected behavior on click with you suggested fix - select only first match?

**Comment by ecki** [comment]
Well, I only care about jumping to that line so I can see the context. selecting the first match (which would highlite the others) is a good choice. Selecting the whole line or nothing is also acceptable as long as the cursor is positioned in the line.

**Comment by nikunjbhatt** [comment]
I was also going to request for this feature.

If possible, what can/should be done is: show single line in search window and when clicked on a found string, the cursor should jump to clicked string in editor.

**Comment by sasumner** [comment]
@nikunjbhatt said:

>show single line in search window and when clicked on a found string, the cursor should jump to clicked string in editor.

First, that is exactly what already happens.

Second, I suppose you are meaning "show single line...when there are multiple hits in that same line".  Well, okay, but what does the editor do when it is going to "jump to clicked string in editor"?  Does it go to the first match, or...?  How would it know to go to different matches on the same line in order to show then all in sequence to you (a possible use case).

What most(?) people that want this feature don't consider is, what if your matches are dozens/hundreds/thousands of columns apart?  With the suggested change it would be very easy to lose (user) consideration of these matches.  Sure, for cases like the "b b" example above, it is super simple to visualize the matches because they are very close together.

**Comment by ecki** [comment]
> I suppose you are meaning "show single line...when there are multiple hits in that same line". 

This is what this bug is all about.

> Well, okay, but what does the editor do when it is going to "jump to clicked string in editor"? Does it go to the first match, or...? 

If you click the line where no match is, then go to the first match, if you click a highlite search term then go to that term. (For most Text files it won't make a difference anyway)

> What most(?) people that want this feature don't consider is, what if your matches are dozens/hundreds/thousands of columns apart? 

Most people want this as an additional option, because the "thousands long line" is not a use case for them but they understand that some people need it.

**Comment by ecki** [comment]
BTW since the hit lines are 1000 chars wide as well you have to scroll horizontally to find the right hit anyway, in that case you can also jump to the found line and then scroll to horizontally, doesn't make a difference.

**Comment by sasumner** [comment]
@ecki said:

>If you click the line where no match is, then go to the first match, if you click a highlite search term then go to that term

I kind of like this idea.  However, it doesn't take into account our keyboard-loving-mouse-hating users out there. :-)

**Comment by nikunjbhatt** [comment]
To @sasumner ,
My suggestion is almost same as of @ecki :

> If you click the line where no match is, then go to the first match, if you click a highlite search term then go to that term.

My additions to the suggestion:
1. Go to the same character-column position where user clicked on a result-line in the search panel.
2. Set the word-wrap in the search panel same as it is in the editor to avoid long-line problems.

> I kind of like this idea. However, it doesn't take into account our keyboard-loving-mouse-hating users out there. :-)

For keyboard-lovers, a checkbox can be provided (having label like "Show single line for found occurrences in search panel") in either search panel or in the find/replace dialog box. If the checkbox is checked then the multiple occurrences of the searched string will appear in single line in the search panel; and if it's unchecked then show the results how they are presently showing (multiple lines in search panel for multiple occurrences of the searched string in single line in editor/files).

**Comment by sasumner** [comment]
@nikunjbhatt When I was mentioning the keyboard-lovers, I wasn't talking about turning such a feature on or off, I was meaning how do they interact with the feature once it is turned on.  Basically, everywhere else that you mentioned "click" -- how do the keyboarders do it?

**Comment by nikunjbhatt** [comment]
If the checkbox is checked and user presses enter key on one of the search result then the cursor should go to the first occurrence in the line. If checkbox is not checked then search result should be shown and mouse/keyboard action should work as per the present behaviour.

**Comment by sasumner** [comment]
This feature-request is REJECTED by the author of Notepad++ ( https://github.com/notepad-plus-plus/notepad-plus-plus/pull/9088#issuecomment-720016310 )
It will not be reconsidered.
Please do not open any new issues on this topic as they will be immediately closed.

The suggestion is to use this workaround:
* Set your _Search mode_ to _Regular expression_.
* Add the following to the end of your _Find what_ expression:  `(?-s).*`

Example 1: To show only the first hit on a line for `foo`, make your _Find what_ expression `foo(?-s).*`

If the literal text you are intending to search for contains regular expression metacharacters, add `\Q` to its start and `\E(?-s).*` at its end.

Example 2: To show only the first hit on a line for `*foo*`, make your _Find what_ expression `\Q*foo*\E(?-s).*`
