### ISSUE TITLE
Feature request (with PR): "Remove lines containing..." in the FindReplace dialog

### ISSUE THREAD

**Issue by btomer** [notepad-plus-plus/notepad-plus-plus#3225]
### Feature description
The requested feature would allow to enter a search term (using the existing search modes) and having all lines that contain the search term deleted.
I find myself needing this feature all the time and I think it will be useful to others as well.

For example, for the following file:
```
Check is the first word of the document
Line without the search term 1
The last word in line is check
Line without the search term 2
A line in the middle that contains "check" in it
Line without the search term 3
Line without the search term 4
The last word in the document is check
```
Using the search term "check" (with match case disabled) and pressing "Remove containing lines" would result in the file:
```
Line without the search term 1
Line without the search term 2
Line without the search term 3
Line without the search term 4
```

### Status
I wrote the code for this feature, it compiles on my machine for x86 and for x64, and it passes the manual tests I put it through.

**Comment by donho** [comment]
https://www.youtube.com/watch?v=SiPLZzRqEwM
