### ISSUE TITLE
Suggestion: Consider adding a secondary Vertical Edge

### ISSUE THREAD

**Issue by jcrmatos** [notepad-plus-plus/notepad-plus-plus#3228]
Hello,

Please consider adding a secondary Vertical Edge.

In case of Python (have no idea in other languages) PEP8 recommends a maximum line length of 72 for comments and docstrings and a maximum line length of 79 for code.

It would be helpful if we could have both visible.

Thanks for a great editor.

Best regards,

JM

**Comment by MalcolmFinlayson** [comment]
JM

So you are looking to have something like the indent guide added.  I assume in an appropriate color. 

I would assume that this would need to be configurable, however are you looking to have it added to the Language styles? It makes sense.

Do you have an example of what you are looking for?

Thanks,

Malcolm

**Comment by jcrmatos** [comment]
Hello,

In attachment you will find the same feature configured in Visual Code.
The purpose of the 2nd vertical edge is for keeping with Python's PEP8 
recommendations.

"
Maximum Line Length

Limit all lines to a maximum of 79 characters.

For flowing long blocks of text with fewer structural restrictions 
(docstrings or comments), the line length should be limited to 72 
characters.
"
https://pep8.org/#maximum-line-length


Best regards,

João Matos

**Comment by sasumner** [comment]
Doesn't Scintilla newer than the one currently used in Notepad++ already support this?

**Comment by MalcolmFinlayson** [comment]
Sasumner, 
If it is in the newer Scintilla what is the community philosophy? Wait and see?
Thanks

**Comment by sasumner** [comment]
>If it is in the newer Scintilla

again, not sure, but I seem to recall it

> what is the community philosophy? Wait and see?

The developer decides when a newer Scintilla is migrated to, so to the rest of us, yes, it is wait-and-see

**Comment by dinkumoil** [comment]
I wrote a plugin that can add an arbitrary number of vertical lines to Notepad++ v7.7 and higher. Its name is _ExtSettings_. You can download it [>>> here <<<](https://sourceforge.net/projects/extsettings/). It will also be available soon via _PluginsAdmin_.

**Comment by dail8859** [comment]
This is now a native feature of Notepad++

![image](https://user-images.githubusercontent.com/3694843/92011520-293c3b80-ed19-11ea-9c5c-bf5f1cb14b98.png)
