### ISSUE TITLE
Find/Replace history is lost when value higher than limit is defined

### ISSUE THREAD

**Issue by Rikk** [notepad-plus-plus/notepad-plus-plus#323]
**Summary:** Find/Replace history is lost (synonyms: replaced by blank, not written, rewritten as null) when a value higher than allowed limit is defined in _config.xml_.

Currently, there are 4 settings that control find history limits for each kind, and they are limited to the following small values:
`nbMaxFindHistoryPath="30"`
`nbMaxFindHistoryFilter="20"`
`nbMaxFindHistoryFind="30"`
`nbMaxFindHistoryReplace="30"`

These limits are constants defined in _Parameters.h_, eg. `const int NB_MAX_FINDHISTORY_FIND    = 30;`

**Issue:** Any value higher than these will make the current history of the affected search type not to be written to config file.

**Mystery:**
_Parameters.cpp_ probably contains the affected algorithm...
Is this the culprit?

``` cpp
    (findHistoryRoot->ToElement())->Attribute(TEXT("nbMaxFindHistoryFind"), &_findHistory._nbMaxFindHistoryFind);
    if ((_findHistory._nbMaxFindHistoryFind > 0) && (_findHistory._nbMaxFindHistoryFind <= NB_MAX_FINDHISTORY_FIND))
    {
        for (TiXmlNode *childNode = findHistoryRoot->FirstChildElement(TEXT("Find"));
            childNode && (_findHistory._findHistoryFinds.size() < NB_MAX_FINDHISTORY_FIND);
            childNode = childNode->NextSibling(TEXT("Find")))
        {
            const TCHAR *fileFind = (childNode->ToElement())->Attribute(TEXT("name"));
            if (fileFind)
            {
                _findHistory._findHistoryFinds.push_back(generic_string(fileFind));
            }
        }
    }
```

Btw, it would be nice to have these options in UI, with more flexible limits.

**Comment by timzchang** [comment]
It seems the bug can be fixed just by removing the `(_findHistory._nbMaxFindHistoryFind <= NB_MAX_FINDHISTORY_FIND)` portion of the if statement mentioned in the above code.

Essentially if we get rid of the NB_MAX_* constants, it allows the user to set their own findHistory limit in the config.xml file.

This kind of brings up a question: why is there a self-imposed limit in the first place?

**Comment by tonyk24** [comment]
Can't find the config.xml file in the np++ root folder. There is a config.model.xml file, but no such options:
```
nbMaxFindHistoryPath="30"
nbMaxFindHistoryFilter="20"
nbMaxFindHistoryFind="30"
nbMaxFindHistoryReplace="30"
```

**Comment by donho** [comment]
Update your Notepad++ to v7.6.6.
If this bug persists in the new release, please open a new issue with the debug information.

**Comment by sch33n** [comment]
i am using 7.8.3 and bug still persists

**Comment by sasumner** [comment]
Verified ( as originally stated by @Rikk )  in 7.8.6
Reopening.

**Comment by sasumner** [comment]
> it would be nice to have these options in UI, with more flexible limits.

Candidates for this spot in the user interface?: #8131
