### ISSUE TITLE
Moving "Find Result" window hangs for several seconds

### ISSUE THREAD

**Issue by ericrrichards** [notepad-plus-plus/notepad-plus-plus#3231]
If the Find Results window is floating (i.e. not docked to the bottom of the main window) it consistently freezes Notepad++ when it is moved by dragging the title bar.  The whole application locks up, and the UI stops redrawing for several seconds.

![frozen_repainting_after_move](https://cloud.githubusercontent.com/assets/2787661/25590716/ab1ce2c8-2e7f-11e7-9e5e-2d0fe01e51a3.PNG)

**Comment by seeker25** [comment]
Same problem, happened to me last night. It froze my entire computer and the mouse refused to move at all.

**Comment by seeker25** [comment]
Not sure if this has anything to do with it:

https://www.reddit.com/r/Windows10/comments/5fkyxt/windows_10_lag_with_word_window_dragging/

There's also another issue for this: 
https://github.com/notepad-plus-plus/notepad-plus-plus/issues/3529

**Comment by MetaChuh** [comment]
please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins if you update from version 7.5.9 or below.
if your issue still persists, and it is still of relevance, please feel free to file a new issue as easy to understand and reproducible as possible.

thank you for your help and best regards.
