### ISSUE TITLE
Feature request - Copy mode: Copy without leading indents

### ISSUE THREAD

**Issue by ghost** [notepad-plus-plus/notepad-plus-plus#3232]
I need a way to strip leading indents (tabs and spaces) from data copied to clipboard from Notepad++.

The data in the Notepad++ document itself should keep having these leading indents and the data copied to clipboard should not.

---

This is what happens in Notepad++ when I mark the text regularly with the mouse (from left to right):

![1](https://cloud.githubusercontent.com/assets/13021900/25615411/abba4aa2-2f3f-11e7-86d4-203f108e55da.PNG)

This is what should be in clipboard after I clicked CTRL+C to copy the marked text:

![1 - copy](https://cloud.githubusercontent.com/assets/13021900/25615415/b1176804-2f3f-11e7-933d-e4fb1cd732ff.PNG)

Note: The image examples are just to better illustrate my need and my actual codes are longer.

---

Can you please add a feature that let a user copy regularly but without any leading tabs or leading spaces?

I guess it could be some **mode** a user should activate... Alternatively it could b e **key or a combo** that will mark all text in all rows of a colum in a similar way --- From the first letter in each column to the last in it...

**Comment by MetaChuh** [comment]
please hold the <kbd>alt</kbd> key when selecting a text.
this allows you to select and copy a block, which is offset to your indentation.

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)
