### ISSUE TITLE
Window doesn't interact properly with mouse when maximized on larger screen

### ISSUE THREAD

**Issue by virtmedia** [notepad-plus-plus/notepad-plus-plus#3233]
### Description of the Issue

The main window of the program 
### Steps to Reproduce the Issue

1. PC must have 2 screens, in my case left is a little bit bigger, and right is slave
2. Maximize program window on the left, bigger screen
3. Try to select some options from program menu

### Expected Behavior

The GUI should behave as normal
### Actual Behavior

Window Menu doesn't render properly, there is no reaction on clicking the window bar. Only way to make program working is to use shortcut: Left Alt+Space, and use arrow case to select "Restore size" from window context menu.

### Debug Information

Notepad++ v7.3.3   (32-bit)
Build time : Mar  8 2017 - 03:37:37
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10 (64-bit)
Plugins : ccc.dll CodeAlignmentNpp.dll ComparePlugin.dll EmmetNPP.dll HTMLTag_unicode.dll ImgTag.dll JSMinNPP.dll MathPad.dll mimeTools.dll NppCalc.dll NppConverter.dll nppcrypt.dll NppExport.dll NppFTP.dll NppPlates.dll NppToolBucket.dll PluginManager.dll PythonScript.dll regrexplace.dll SpellChecker.dll Tidy2.dll XMLTools.dll 

Graphic card: Nvidia GTX750Ti Driver: 381.65
![nppbug01](https://cloud.githubusercontent.com/assets/4068569/25626419/c0679700-2f5f-11e7-90f0-3f56e85aa2aa.png)
![nppbug02](https://cloud.githubusercontent.com/assets/4068569/25626423/c313b97a-2f5f-11e7-9fe7-3361bc1c3607.png)

**Comment by gianmaxfactor** [comment]
I also have two monitor, internal and external. When I maximize on the first one (the notebook one) all icons on the toolbar disappears and there is no mouse interaction with the toolbar (only with the text window. I have to press F11 twice to restore, but it will do the something after I close and reopen (automatically maximized).

**Comment by ChristophLindemann** [comment]
I have the same issue, in a configuration with 3 screens.

When I maximize on the main screen (which ever is selected as default in windows), the window is not rendered correctly, and the menu is not accessible with mouse.
![notepadpp_maximized_missing_menu](https://user-images.githubusercontent.com/16814858/34676227-6f30dab6-f48c-11e7-934b-e45c4e12ee96.PNG)


When I maximize on one of the other screens, it is rendered correctly
![notepadpp_maximized_ok_menu](https://user-images.githubusercontent.com/16814858/34676168-41e374e2-f48c-11e7-8cba-52964c0a6360.PNG)

**Debug Info**
Notepad++ v7.5.4   (64-bit)
Build time : Jan  1 2018 - 01:50:29
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10 (64-bit)
Plugins : DSpellCheck.dll mimeTools.dll NppConverter.dll

**Comment by gianmaxfactor** [comment]
I have not more the problem. Try with my portable copy of Notepad++ and see if it works well for you. Regards.  [https://www.dropbox.com/s/h3cy8apbn7o4563/%40Notepad%2B%2B.rar?dl=0](url)

**Comment by gianmaxfactor** [comment]
https://www.dropbox.com/s/h3cy8apbn7o4563/%40Notepad%2B%2B.rar?dl=0

**Comment by MetaChuh** [comment]
please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins if you update from version 7.5.9 or below.
if your issue still persists, and it is still of relevance, please feel free to file a new issue as easy to understand and reproducible as possible.

thank you for your help and best regards.
