### ISSUE TITLE
Add fuzzy search option to the search dialog based on Edit distance

### ISSUE THREAD

**Issue by DavidHaslam** [notepad-plus-plus/notepad-plus-plus#3236]
Suggestion for enhancement to the already excellent search dialog in Notepad++

Implement the **fuzzy search** algorithm used by Lucene search based on [edit distance](https://en.wikipedia.org/wiki/Levenshtein_distance) 

Lucene syntax uses a _tilde_ after a word for fuzzy matching.

Thus a search of the KJV Bible text for `tilgath~ AND paliser~` finds all seven instances of both spelling variants of the name, i.e. **Tiglath–pileser** as well as **Tilgath–pilneser** (the king of Assyria.)

btw. I deliberately misspelled the second part.

**Comment by 1manfactory** [comment]
This would be very handy.

**Comment by MetaChuh** [comment]
as main search functions are depending on the implemented boost engine, which is an external project, we can currently only rely on the features implemented at that engine.

thank you for your help and best regards.

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
(no extra account is needed, just use your github account to sign in)
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)
