### ISSUE TITLE
Can not save plugin options in minimalist package

### ISSUE THREAD

**Issue by antonbabkin** [notepad-plus-plus/notepad-plus-plus#3238]
### Description of the Issue
I am coming from this issue with JSToolNPP plugin: https://github.com/sunjw/jstoolnpp/issues/46

After manually installing the plugin into newly downloaded portable minimalist package, plugin becomes available, but it is not possible to save plugin options. Also tested with NppExec plugin.

Importantly, Issue does not apply to a non-minimalist portable version of Npp.

### Steps to Reproduce the Issue
1. Download [Npp minimalist package 32-bit v7.3.3](https://notepad-plus-plus.org/repository/7.x/7.3.3/npp.7.3.3.bin.minimalist.7z), unpack on desktop folder on Windows 10 machine.
2. Download [JSToolNpp](http://sourceforge.net/projects/jsminnpp/files/Uni/JSToolNPP.1.20.2.uni.32.zip/download) plugin, unpack the DLL into `plugins` subfolder. Alternatively, download [NppExec](https://sourceforge.net/projects/npp-plugins/files/NppExec/NppExec%20Plugin%20v0.5.3/NppExec_053_dll_Unicode.zip/download) and unpack into `plugins`.
3. Run notepad++.exe, try to change plugin options.

### Expected Behavior
Options should persistently change.

### Actual Behavior
Plugins show up in the plugins menu, and are functional. But changing options has no effect.

**Comment by vitaliylag** [comment]
Same problem. It was OK in 7.3.2 but when I return 7.3.2 back problem does not disappear. I guess it is not notepad fault but plugin manager fault because I updated plugin manager with notepad.

**Comment by vitaliylag** [comment]
I have installed Notepad++ first time on Windows 8.1. The version is 7.5.1 x86 (latest). Then I have copied TabIndentSpaceAlign plugin to the "plugins" folder. And settings cannot be saved. I should enable TISA style in the plugin settings after every Notepad++ restart.

@donho can you see?

**Comment by brinkibrinki** [comment]
create folders manually
create "plugins" in %appdata%\Roaming\Notepad++
create "config" in %appdata%\Roaming\Notepad++\plugins
then saving of options works

**Comment by vitaliylag** [comment]
@brinkibrinki I already have this folder. But first letter of "Config" folder is in uppercase. Can this cause the problem?

**Comment by brinkibrinki** [comment]
i had no folders in %appdata%\Roaming\Notepad++
seems, that the plugin was not able to create paths recursively.
you can try to rename it. on windows, i would assume upper/lower case does not matter.

**Comment by vitaliylag** [comment]
Renamed. Settings are not saved anyway.

**Comment by brinkibrinki** [comment]
can you try to create a JSMinNpp.ini file in %appdata%\notepad++\plugins\config with following content?

> Put CR=0
> Indent char=space
> Chars per indent=3
> New line before {=1
> Kepp top comment=0
> Indent in empty=0
> Disable version check=0

**Comment by vitaliylag** [comment]
It doesn't work too.

**Comment by MetaChuh** [comment]
please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins if you update from version 7.5.9 or below.
if your issue still persists, and it is still of relevance, please feel free to file a new issue as easy to understand and reproducible as possible.

thank you for your help and best regards.
