### ISSUE TITLE
Function list with Visual Basic files does not work

### ISSUE THREAD

**Issue by AleWin32** [notepad-plus-plus/notepad-plus-plus#3239]
Windows 7 SP1 Professional with Notepad++ 7.3.3 (64 bit)

Open a Visual Basic code file
Click on Language menu, V, Visual Basic
Click on View menu, Function List

It does not show any functions

**Comment by MAPJe71** [comment]
Function List does not support Visual Basic (.NET|Script|for Applications) yet.
I have two preliminairy parsers, let me know if you want to give them a try.

**Comment by AleWin32** [comment]
Yes, please, i try them if you tell me how to apply them to Notepad++.
Thanks

**Comment by MAPJe71** [comment]
Add the following associations and parsers to your `%APPDATA%\Notepad++\functionList.xml` and restart Notepad++ (presuming you used N++ to edit the XML file :-) ).

```xml
<association id= "visualbasic_syntax" langID="18" />
<!-- <association id= "visualbasic_subfuncprop" langID="18" /> -->
```
Note: the two associations are mutual exclusive hence one is commented out.

```xml
<parser
    displayName="[TODO] Visual Basic (.NET|Script|for Applications)"
    id         ="visualbasic_syntax"
    commentExpr="(?x)                                               # free-spacing
                    (?m-s:(?i:REM)(?:\h.+)?$)                       # Single Line Comment 1
                |   (?m-s:\x27.*$)                                  # Single Line Comment 2
                "
>
    <classRange
        mainExpr="(?'SCOPE'(?i:CLASS)).*?(?i:END\h\k'SCOPE')"
    >
        <className>
            <nameExpr expr="(?i:CLASS)\h+(?:[A-Za-z_]\w*\b)(?:[^\r\n]*(?:\r?\n|\n?\r))" />
            <nameExpr expr="\h+(?:[A-Za-z_]\w*\b)" />
            <nameExpr expr="[A-Za-z_]\w*" />
        </className>
        <function
            mainExpr="\h*(?i:(?:(?:PRIVATE|PUBLIC)\h+)?(?:STATIC\h+)?(?:SUB|FUNCTION|PROPERTY)).*?(?:\(|$)"
        >
            <functionName>
                <funcNameExpr expr="(?i:(?:(?:PRIVATE|PUBLIC)\h+)?(?:STATIC\h+)?(?:SUB|FUNCTION|PROPERTY)).*?(?:\(|$)" />
                <funcNameExpr expr="(?i:(?:SUB|FUNCTION|PROPERTY)).*?(?:\(|$)" />
                <funcNameExpr expr="[A-Za-z_]\w*(?=\h*\()" />
            </functionName>
        </function>
    </classRange>
    <function
        mainExpr="\h*(?i:(?:(?:PRIVATE|PUBLIC)\h+)?(?:STATIC\h+)?(?:SUB|FUNCTION|PROPERTY)).*?(?:\(|$)"
    >
        <functionName>
            <nameExpr expr="(?i:(?:(?:PRIVATE|PUBLIC)\h+)?(?:STATIC\h+)?(?:SUB|FUNCTION|PROPERTY)).*?(?:\(|$)" />
            <nameExpr expr="(?i:(?:SUB|FUNCTION|PROPERTY)).*?(?:\(|$)" />
            <nameExpr expr="[A-Za-z_]\w*(?=\h*\()" />
        </functionName>
    </function>
</parser>
<!-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
|   https://plus.google.com/+AliAlKhawaher/posts/19hx2ViAvnu
\-->
<parser
    displayName="[TODO] Visual Basic (.NET|Script|for Applications) by AliAlKhawaher"
    id         ="visualbasic_subfuncprop"
    commentExpr="(?x)                                               # free-spacing (see `RegEx - Pattern Modifiers`)
                    (?m-s:(?i:REM)(?:\h.+)?$)                       # Single Line Comment 1
                |   (?m-s:\x27.*$)                                  # Single Line Comment 2
                "
>
    <function
        mainExpr="(?:sub|function|property(?:\s+(?:get|let))?)\s+[[:alpha:]]\w(?:\s+lib\s+\x22\w+\x22(?:\s+alias\s+\x22\w+\x22)?)?\s*(?:\([^()]*|(?:\r?\n|\n?\r))"
    >
        <functionName>
            <!-- (re-)move the \K to display more or less of the function declaration -->
            <nameExpr expr="(?:(?:sub|function|property)\s+)?\K(?:(?:let|get)?\s+)?[\w\x22]+(?:\s+lib\s+\x22\w+\x22(?:\s+alias\s+\x22\w+\x22)?)?" />
        </functionName>
    </function>
</parser>
```

**Comment by AleWin32** [comment]
I pasted that to my functionList.xml and it worked, functions are listed correctly (although my code is not too big), thanks! But i don't understand what you told me about that one of the two VB parsers is commented, i see both codes without comments, i only see in comments an URL and an explanation.

So will you add this VB parser to Notepad++?

**Comment by MAPJe71** [comment]
> But i don't understand what you told me about that one of the two VB parsers is commented

The note was for the **association**'s not the parsers.
I posted two parsers, one with id "visualbasic_syntax" and one with id "visualbasic_subfuncprop".
You can only have _one_ of the parsers active i.e. associated with Visual Basic language (LangID="18").

The _active_ association i.e. parser "visualbasic_syntax" is **used** by the Function List engine:
```xml
<association id= "visualbasic_syntax" langID="18" />
```
The _inactive_ association i.e. parser "visualbasic_subfuncprop" is **NOT used** by the Function List engine:
```xml
<!-- <association id= "visualbasic_subfuncprop" langID="18" /> -->
```

> So will you add this VB parser to Notepad++?

Eventually I will yes, hence the `[TODO]` in `displayName`.

**Comment by Friedi** [comment]
Hi Menno,
thanks for your contributions! I tested these two vb-functionlists.
The first does not work for arrays and the second does not work at all properly(it recognizes only one sub out of 30) (sorry the browser I use is not supported and formatting does not work):
Sub test_subfolders()
    Dim a() As String
        
    i = fsGetSubfolders("c:\", a)
    For i = 0 To UBound(a)
        Debug.Print a(i)
    Next
End Sub

Function fsGetSubfolders(ByVal path As String, ByRef arySubfolders() As String)
    Dim fso, f, sf As Object
    Dim i As Long
    
    Set objFSO = CreateObject("Scripting.FileSystemObject")
    Set objOrdner = objFSO.GetFolder(path)
    Set colSubfolders = objOrdner.Subfolders
    
    ReDim arySubfolders(0)
    i = 0
    
    For Each sf In colSubfolders
        If (i = 0) And (UBound(arySubfolders) = 0) Then
        Else
            ReDim Preserve arySubfolders(i)
        End If
        
        arySubfolders(i) = sf
        'Debug.Print arySubfolders(i)
        'Debug.Print strGetParentFSOfolder(sf)
        i = i + 1
    Next
    Set objFSO = Nothing
    Set objOrdner = Nothing
    Set colSubfolders = Nothing
End Function



It seems you contribution 1.0.0.0 from 2013 works better, but I wondered if there was an update so I tried your two above.
here is the version you posted 2013:
<parser 
			id="vb_function" 
			displayName="Visual Basic (.NET|Script|for Applications)"  
			commentExpr="(?m:((?&lt;=&apos;).*?$)|((?i:REM)([\t ].*?)?$))"> 
			<classRange
				mainExpr="(?s:(?&lt;SCOPE&gt;(?i:CLASS|TYPE)).*?(?i:END[\t ]\k&lt;SCOPE&gt;))"
				displayMode="node" >
				<className>
					<nameExpr expr="(?i:CLASS|TYPE)[\t ]+(?:[A-Za-z_][\w]*\b)(?:.*?[\r\n])" />
					<nameExpr expr="[\t ]+(?:[A-Za-z_][\w]*\b)" />
					<nameExpr expr="[A-Za-z_][\w]*" />
				</className>
				<function
					mainExpr="(?m:^[\t ]*(?i:(?:(?:PRIVATE|PUBLIC)[\t ]+)?(?:STATIC[\t ]+)?(?:SUB|FUNCTION|PROPERTY)).*?(?:\(|$))" >
					<functionName>
						<funcNameExpr expr="(?i:(?:(?:PRIVATE|PUBLIC)[\t ]+)?(?:STATIC[\t ]+)?(?:SUB|FUNCTION|PROPERTY)).*?(?:\(|$)"/>
						<funcNameExpr expr="(?i:(?:SUB|FUNCTION|PROPERTY)).*?(?:\(|$)"/>
						<funcNameExpr expr="[A-Za-z_][\w]*(?=[\t ]*\()"/>
					</functionName>
				</function>
			</classRange>
			<function 
				mainExpr="^[\t ]*(?i:(?:(?:PRIVATE|PUBLIC)[\t ]+)?(?:STATIC[\t ]+)?(?:SUB|FUNCTION|PROPERTY)).*?(?:\(|$)" 
				displayMode="$functionName">
				<functionName>
					<nameExpr expr="(?i:(?:(?:PRIVATE|PUBLIC)[\t ]+)?(?:STATIC[\t ]+)?(?:SUB|FUNCTION|PROPERTY)).*?(?:\(|$)"/>
					<nameExpr expr="(?i:(?:SUB|FUNCTION|PROPERTY)).*?(?:\(|$)"/>
					<nameExpr expr="[A-Za-z_][\w]*(?=[\t ]*\()"/>
				</functionName>
			</function>
		</parser>

**Comment by Friedi** [comment]
<parser 
			id="vb_function" 
			displayName="Visual Basic (.NET|Script|for Applications)"  
			commentExpr="(?m:((?&lt;=&apos;).*?$)|((?i:REM)([\t ].*?)?$))"> 
			<classRange
				mainExpr="(?s:(?&lt;SCOPE&gt;(?i:CLASS|TYPE)).*?(?i:END[\t ]\k&lt;SCOPE&gt;))"
				displayMode="node" >
				<className>
					<nameExpr expr="(?i:CLASS|TYPE)[\t ]+(?:[A-Za-z_][\w]*\b)(?:.*?[\r\n])" />
					<nameExpr expr="[\t ]+(?:[A-Za-z_][\w]*\b)" />
					<nameExpr expr="[A-Za-z_][\w]*" />
				</className>
				<function
					mainExpr="(?m:^[\t ]*(?i:(?:(?:PRIVATE|PUBLIC)[\t ]+)?(?:STATIC[\t ]+)?(?:SUB|FUNCTION|PROPERTY)).*?(?:\(|$))" >
					<functionName>
						<funcNameExpr expr="(?i:(?:(?:PRIVATE|PUBLIC)[\t ]+)?(?:STATIC[\t ]+)?(?:SUB|FUNCTION|PROPERTY)).*?(?:\(|$)"/>
						<funcNameExpr expr="(?i:(?:SUB|FUNCTION|PROPERTY)).*?(?:\(|$)"/>
						<funcNameExpr expr="[A-Za-z_][\w]*(?=[\t ]*\()"/>
					</functionName>
				</function>
			</classRange>
			<function 
				mainExpr="^[\t ]*(?i:(?:(?:PRIVATE|PUBLIC)[\t ]+)?(?:STATIC[\t ]+)?(?:SUB|FUNCTION|PROPERTY)).*?(?:\(|$)" 
				displayMode="$functionName">
				<functionName>
					<nameExpr expr="(?i:(?:(?:PRIVATE|PUBLIC)[\t ]+)?(?:STATIC[\t ]+)?(?:SUB|FUNCTION|PROPERTY)).*?(?:\(|$)"/>
					<nameExpr expr="(?i:(?:SUB|FUNCTION|PROPERTY)).*?(?:\(|$)"/>
					<nameExpr expr="[A-Za-z_][\w]*(?=[\t ]*\()"/>
				</functionName>
			</function>
		</parser>

**Comment by Showboarder** [comment]
Could we add the archive content vb.xml in the functionlist folder, please?
[vb.zip](https://github.com/user-attachments/files/18128466/vb.zip)
I tried it and it looks quite fine.
