### ISSUE TITLE
Batch Convert Encoding

### ISSUE THREAD

**Issue by jporter-sdl** [notepad-plus-plus/notepad-plus-plus#324]
I use Notepad++ a lot in a corporate environment and we often have to change/convert the encoding of files. Notepad++ has a nice menu for this but if you have a lot of files to convert it can be a very tiresome job to do it manually one by one. Therefor we have thought of the below idea. Should be fairly simple to implement?

At the Encoding menu, make a "Batch Convert Encoding" so you can for example
- Convert encoding of all by Notepad++ opened files to encoding X
- Select external files/directory to convert encoding of multiple opened files to encoding X

Regards,
Jaimy

**Comment by Croydon** [comment]
I had this trouble a while ago also, while searching I noticed that A LOT of people are missing such a feature. Would be a nice thing :)

**Comment by jporter-sdl** [comment]
Is this feature on the list to be implemented? We would still after 2 years be VERY happy if this can be implemented. My colleague just almost had tears in his eyes when he saw the bulk of files he had to manually convert ;) anyway, hope this is still on the to-do list! Keep up the good work, Notepad++ is awesome.

**Comment by MetaChuh** [comment]
closed due to:
* minor relevance for the majority of users
* not expected to be used on a daily base
* can be easily done with external tools like [iconv](https://superuser.com/questions/69091/batch-change-encoding-ascii-files-from-utf-8-to-iso-8859-1)
