### ISSUE TITLE
Add support to Mac Roman encoding

### ISSUE THREAD

**Issue by ohmer1** [notepad-plus-plus/notepad-plus-plus#3240]
When I open a file created by a mac users, accentuated characters are not displaying correctly in Notepad++. I don't see support for Mac Roman encoding in the Encoding menu and Western European submenu.

**Comment by MetaChuh** [comment]
please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins if you update from version 7.5.9 or below.
if your issue still persists, and it is still of relevance, please feel free to file a new issue as easy to understand and reproducible as possible.

thank you for your help and best regards.
