### ISSUE TITLE
Remember the last used path to saved session

### ISSUE THREAD

**Issue by orjtor** [notepad-plus-plus/notepad-plus-plus#3241]
### Description of the Issue
It would be great if the np++ could remember the path to the previously saved/used session, even though I'm not using the option "Remember current session for next launch". That existing option will also save all my open files in a new session, but what I would like to have is my standard session of files that I often would like to open when I start np++.  It would be totally fine, even better, if I could open a session using a menu option like "Recently saved sessions..." in the File menu.

### Expected Behavior
Either remember the latest used path when saving a session, when you are supposed to load a session.
Even better present a list of recently saved sessions in a menu option under File, beside Load and Save session

### Actual Behavior
Today when I want to open my manually saved session I need to navigate in the Open dialogue to my folder, since np++ always starts in either "AppData\Local\Temp\nppLocalization" or in "C:\Program Files (x86)\Notepad++"

**Comment by evancamilleri** [comment]
I think it remembers only the path of the last open file. 

Sessions and Files should be treated as 2 separate things.  So it should remember both the last file and last session - depending on what is the action being chosen now.

**Comment by donho** [comment]
Implemented in #10935:
Set to "Open session in a new instance of Notepad++" option in Preference then all your modification of this session will be save automatically.
