### ISSUE TITLE
Enable save button after underlying file is changed externally

### ISSUE THREAD

**Issue by suchko** [notepad-plus-plus/notepad-plus-plus#3246]
### Description of the Issue
When a file is in the editor and it is changed by an external program, npp recognizes this and asks if you want to reload the file.  If you say no, it should enable the save button since the file is different than the one which is on the disk and is "dirty".

### Steps to Reproduce the Issue

1.  Open a file
1a  Change the file
1b  Save the file 
1c Note that save button is disabled since file is not dirty
2.  Change the file with another editor
3.  Answer no when asked if you want to reload it

### Expected Behavior
The save button should be enabled since file has changes which can be saved

### Actual Behavior
Save button is not enabled and I must make and undo a change in order to save to disk

**Comment by Colombino** [comment]
I just hit that bug (and created account only to comment). It's much dangerous than it looks.
My use case was:
1. Modified a file.
2. Reverted the entire directory and said 'no' to the question to reload.
3. Pressed Ctrl+S to overwrite this file only (I never click the button).
It took me some time to figure out, that the file is not saved.
When I closed the file (just to try, I had the change in the clipboard) it silently lost my changed buffer.
