### ISSUE TITLE
"Save All" button on exit with multiple file that have changes

### ISSUE THREAD

**Issue by jporter-sdl** [notepad-plus-plus/notepad-plus-plus#325]
Consider the following scenario:
1. Open 50 files
2. Search and replace some text in all opened files, some files have replacements, some don't.
3. Press the right top edge X to close Notepad++. 

Notepad++ will now ask to save each file individually. Add a "Save all" / "Save all changes" button on the first dialog so you don't have to press the Save button 20+ times.

I know there is a Save All button which can be pressed before closing Notepad++ but most users expect the save all to be there as it is in almost all other programs. As I said it would be an enhancement to make Notepad++ even better.

**Comment by MetaChuh** [comment]
closed due to:
* inactivity (4y)
* can be done by using save all from the menu

**Comment by Croydon** [comment]
You can't use this menu anymore as soon as you did click on close already.
For somebody familiar with the code base I think this isn't hard to implement yet it increases the user experience quit a lot
