### ISSUE TITLE
Updates: Allow postponing until program exit

### ISSUE THREAD

**Issue by kaelef** [notepad-plus-plus/notepad-plus-plus#3250]
Everyone knows N++ updates can get annoying and usually interrupt you at inopportune times.  Automatic update checking can be disabled, but this is not a desirable solution for obvious reasons.

The Paint.Net developers have come up with a reasonable compromise that I'm surprised I haven't seen adopted elsewhere, and I suggest N++ does so.

When Paint.Net detects an available update during startup, it prompts the user with two options: 1.) Install now, 2.) Install on program exit.

This let's me finish what I jumped into the program to do in the first place while also keeping the program up to date.

**Comment by MetaChuh** [comment]
please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins if you update from version 7.5.9 or below.
if your issue still persists, and it is still of relevance, please feel free to file a new issue as easy to understand and reproducible as possible.

thank you for your help and best regards.
