### ISSUE TITLE
Can you add "tab indentation space alignment" style?

### ISSUE THREAD

**Issue by vitaliylag** [notepad-plus-plus/notepad-plus-plus#3251]
Please make option to indent with tabs and align with spaces.

How it works:
- In beginning of a string tabs are used.
- After any not tab characters spaces are used.

I know there is a plugin for that but I want native support for such important feature (and also I cannot save plugin settings anymore https://github.com/notepad-plus-plus/notepad-plus-plus/issues/3238, please fix it).

**Comment by vrubleg** [comment]
Oh, yeah, it will be a very useful feature. Now I'm making it manually, pressing spaces as many times as needed, but automatic solution would be nice.

BTW, which plugin implements such behavior?

**Comment by vitaliylag** [comment]
@vrubleg, TabIndentSpaceAlign plugin

**Comment by vrubleg** [comment]
Unfortunately, TabIndentSpaceAlign is buggy. Sometimes it breaks default behavior of tab. But we need just "use spaces instead of tabs if there are other symbols than tabs on the left of the current line" behavior.

It would be nice if these "smart tabs" will be implemented natively in the Notepad++.

**Comment by vitaliylag** [comment]
@donho, can you see this issue? This is most important feature in text editor for program code.

**Comment by vitaliylag** [comment]
up

**Comment by vitaliylag** [comment]
@donho up

**Comment by donho** [comment]
If I do understand your need, what you want is using only TAB key, but in some specific situation it's white space which comes out ?

**Comment by vrubleg** [comment]
@donho 

When there are nothing or just tabs before cursor, the tab key should insert tabs. Examples:
→→|test
|test

When there are non-tabs before the cursor, it should insert spaces:
→→test•|=•1;
→→•|test

As an additional convenience, it could convert adjacent tabs to spaces in such situations:
→→test→|=•1;

Legend: → is a tab, • is a space, | is a cursor.

This behavior is very convenient for the case when tabs are used for indentation, and spaces are used for alignment. You can find examples here: https://dmitryfrank.com/articles/indent_with_tabs_align_with_spaces

**Comment by sasumner** [comment]
IMO this behavior would have to come from Scintilla to be an "as  you type" feature.  After-the-fact conversion functions could be in Notepad++, but without core Scintilla support for the dynamic case, conversions may be of lesser importance.

I did a little bit of searching but didn't see where Scintilla has any support for tab-indent-space-align behavior.  I could certainly be wrong about that, in which case I would appreciate someone pointing that out.

For now, I'm labeling this as depending on Scintilla.

**Comment by vrubleg** [comment]
Looked through the code of the Scintilla. It seems that it should be not hard to add this feature there. All the related code in the current version is here:
https://github.com/notepad-plus-plus/notepad-plus-plus/blob/master/scintilla/src/Editor.cxx#L3972

Can we patch it in the Notepad++ repo? Or should we persuade the Scintilla developers should make such changes first?

**Comment by vrubleg** [comment]
Created a feature request in the Scintilla bug tracker: https://sourceforge.net/p/scintilla/feature-requests/1385/

**Comment by sasumner** [comment]
>Can we patch it in the Notepad++ repo?

No

>Or should we persuade the Scintilla developers to make such changes first?

Yes.

**Comment by donho** [comment]
https://github.com/notepad-plus-plus/notepad-plus-plus/pull/12333#issuecomment-1430684990

**Comment by vrubleg** [comment]
@donho But this ticket is unrelated to that PR, it's about an absolutely different feature, so it shouldn't be closed with that rejected PR.

**Comment by donho** [comment]
@vrubleg 
I know what is about this feature.
But what I meant in the comment I've left is, a TAB keystroke should give a TAB and a space keystroke should give a white space - there's no ambiguity to the users. Users who request feature as this issue should look for the plugins that get such job done.

**Comment by vitaliylag** [comment]
@donho OK, can you then remove the option "Replace by space" please? As you said if the user want whitespaces he must press space not tab key. So remove "Replace by space" from settings please.

**Comment by vitaliylag** [comment]
Also there is not tab indent space alignment plugin on x64 version.
![изображение](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/12641771/0bd88b50-4b7d-446b-ae07-68acdfca6925)

I think it's better to remove x64 builds for some time. It's not can be used anyway. It's not a joke.

**Comment by alankilborn** [comment]
> can you then remove the option "Replace by space" please?

No

>remove x64 builds for some time

and no.

**Comment by donho** [comment]
> OK, can you then remove the option "Replace by space" please? As you said if the user want whitespaces he must press space not tab key. So remove "Replace by space" from settings please. If somebody needs this feature he can just install the plugin that adds this options.

These options have been there since long time ago, and also when the user check it, he/she knows what they are doing. So I don't see the reason to remove it.

> I think it's better to remove x64 builds for some time. It's not can be used anyway. People who installed x64 will have to remove it and install x86 build anyway :(

Except the plugins are harmful or they make crash, I see no reason to remove any plugin.

**Comment by vitaliylag** [comment]
@donho when the user check it, he/she knows what they are doing

My proposal is the same. My proposal was to add the option "Action on tab key" with this possible values:
* Paste tabulation character
* Paste spaces
* Use tab indent space alignment style (pastes tabulation at the start of the line, spaces if line contains non-tabulation character before the caret)

Or at least this:
* Replace with spaces (yes/no)
* Only at the start of the line (yes/no)

or
* Replace with spaces (yes/no)
* Only if line contains non-tabulation character before the caret (useful for tab indent space alignment style) (yes/no)

In this kind of option window he/she knows what they are doing too. Sorry if my proposal was not clear enough.
