### ISSUE TITLE
JavaScript styling breaks when inserting HTML with a tick

### ISSUE THREAD

**Issue by maxdemajo** [notepad-plus-plus/notepad-plus-plus#3252]
### Description of the Issue
The JavaScript styling breaks when HTML is inserted dynamically using a tick ( \` ). Notepad++ does not detect the tick as a form of multi-line quotation mark, and so assumes the code that follows is JavaScript, and not a string of text. This is an acceptable minor bug and is not really an issue, but as HTML is being inserted using the tick, when an ending delimiter is found (Ex: \</label>), Notepad++ assumes that the ending delimiter is the </script> delimiter and so reverts back to the HTML styling. The following JavaScript code is then incorrectly shown in the HTML style. From what I can see the problem lies within the check for the </script> delimiter. A check is made for the first occurrence of "</" instead of "</script>". This should be an easy fix by changing the check or recognizing the tick ( \` ) as a form of multi-line quotation. 

There is a quick fix for this by inserting a backslash in front of the forward slash, as such: "<\\/label>", although it did take some time to figure out what was going on and how to get around the issue. To my knowledge, this was not an issue in some earlier version of Notepad++, as I don't recall this happening while the code was initially being written.

See attached image as an example:
![bug](https://cloud.githubusercontent.com/assets/10404229/25788142/36f3224a-33a7-11e7-9713-08a9e8a84563.png)

The tick on line 260 is not registered as a form of quotation. The line at 264 breaks the styling. The following code is formatted for HTML.

### Steps to Reproduce the Issue
1.  Use the tick ( \` ) as a form of quotation within a JavaScript code block on an HTML page
2.  Use an HTML ending delimiter starting with "</" within the quotation
3.  Write some more code within the JavaScript code block after the quotation

### Expected Behavior
The tick is recognized as a quotation mark and grays out its contents. Notepad++ retains JavaScript styling thereafter.

### Actual Behavior
The tick is not registered as a form of quotation, Notepad++ attempts to style its contents to look like JavaScript. The "</" HTML delimiter is detected within the quote and the following JavaScript code is styled as if it is being coded as HTML.

### Debug Information
Notepad++ v7.3.3   (64-bit)
Build time : Mar  8 2017 - 03:39:58
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10 (64-bit)
Plugins : mimeTools.dll NppConverter.dll

**Comment by dail8859** [comment]
This issue would probably be best reported to the [Scintilla issue tracker](https://sourceforge.net/p/scintilla/bugs/) as it handles all the lexing. This issue may already be present there.

**Comment by maxdemajo** [comment]
That makes sense. Thanks, I'll post it there.

**Comment by donho** [comment]
https://github.com/notepad-plus-plus/notepad-plus-plus/issues/3822#issuecomment-697275450
