### ISSUE TITLE
Notepad++ crashed leaving empty files on saving files

### ISSUE THREAD

**Issue by brakkio86** [notepad-plus-plus/notepad-plus-plus#3253]
### Description of the Issue
I can't reproduce, but sometimes, when I save the files with CTRL+S shortcut, notepad crash. When I reopen the file is completely empty.

### Steps to Reproduce the Issue
Does not happen all the times. Open a file, make some modifications and then press CTRL+S.

### Expected Behavior
Save the files.

### Actual Behavior
Crash.

### Debug Information
This is the debug information of my installation:
Notepad++ v7.3.3   (64-bit)
Build time : Mar  8 2017 - 03:39:58
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 7 (64-bit)
Plugins : mimeTools.dll NppConverter.dll 

I also found this information on windows event manager (it is in italian, but I can translate if you cannot understand all the lines):
Nome dell'applicazione che ha generato l'errore: notepad++.exe, versione: 7.3.3.0, timestamp: 0x58bf6f51
Nome del modulo che ha generato l'errore: notepad++.exe, versione: 7.3.3.0, timestamp: 0x58bf6f51
Codice eccezione: 0xc0000417
Offset errore 0x000000000011bf39
ID processo che ha generato l'errore: 0x1bb0
Ora di avvio dell'applicazione che ha generato l'errore: 0x01d2c7c42b99ff73
Percorso dell'applicazione che ha generato l'errore: C:\Program Files\Notepad++\notepad++.exe
Percorso del modulo che ha generato l'errore: C:\Program Files\Notepad++\notepad++.exe
ID segnalazione: f29fcd8f-33c6-11e7-b702-54e091ebb112

**Comment by apalashkin** [comment]
I experienced the same issue. It has been reproduced some time ago on an old version and I didn't give an attention to it.

But yesterday it crashed twice and I nearly lose my day- work. Thanks I have restored it from pyc-file.

My Debug Info

Notepad++ v7.5.1   (32-bit)
Build time : Aug 29 2017 - 02:35:41
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : ON
Local Conf mode : OFF
OS : Windows 7 (64-bit)
Plugins : ComparePlugin.dll mimeTools.dll NppCCompletionPlugin.dll NppConverter.dll NppExport.dll NPPJSONViewer-win32.dll PluginManager.dll 

!!! I have a full crash dump of notepad++ process !!!
How can I send it?

**Comment by caseytp** [comment]
Checking in. Looks like this hasn't been looked at since Dec 2017. Any progress? Will take a look if necessary.

**Comment by eight04** [comment]
This still happens randomly. Fortunately, we can restore our files from the `%appdata%\Notepad++\backup` folder. Make sure to copy the backup before restarting Notepad++. Those files might be discarded when Notepad++ start.

Probably related: https://github.com/notepad-plus-plus/notepad-plus-plus/issues/1310, https://github.com/notepad-plus-plus/notepad-plus-plus/issues/1501, https://github.com/notepad-plus-plus/notepad-plus-plus/issues/2672, https://github.com/notepad-plus-plus/notepad-plus-plus/issues/2883, https://github.com/notepad-plus-plus/notepad-plus-plus/issues/4357

**Comment by MetaChuh** [comment]
please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins if you update from version 7.5.9 or below.
if your issue still persists, and it is still of relevance, please feel free to file a new issue as easy to understand and reproducible as possible.

thank you for your help and best regards.
