### ISSUE TITLE
No Scrollbar! User Defined Languange

### ISSUE THREAD

**Issue by kristi-alb** [notepad-plus-plus/notepad-plus-plus#3258]
### Description of the Issue
Just can't scroll down here.
![screenshot_32](https://cloud.githubusercontent.com/assets/26466974/25875576/8b1744f6-3518-11e7-963a-ffe4eec1f363.png)

### Steps to Reproduce the Issue

1.  Get an User Defined Lanugange with alot of groups;
2. Try to edit the groups on a 16:9 Screen.

### Expected Behavior

Have a scrollbar.
### Debug Information

Notepad++ v7.3.3   (32-bit)
Build time : Mar  8 2017 - 03:37:37
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : ON
Local Conf mode : OFF
OS : Windows 10 (64-bit)
Plugins : mimeTools.dll NppConverter.dll NppExport.dll PluginManager.dll

**Comment by rddim** [comment]
You can use the `Dock` button on the top right corner

**Comment by kristi-alb** [comment]
I see, Thanks.
