### ISSUE TITLE
Fatal error in backup procedure, please apply easy fix

### ISSUE THREAD

**Issue by robsiegen** [notepad-plus-plus/notepad-plus-plus#3259]
### Description of the Issue
I was working on Notepad++ the other day and I noticed my PC becoming unresponsive. As I had typed quite a bit of text I was anxious to get it saved. I just about managed to get my mouse cursor over the Save button and click it. Phew! My computer then froze completely and I had to do a hard reset (hold the power button).
To my dismay, after rebooting, my file had been filled with NULL.
Fortunately, I quickly discovered online that Notepad++ makes backups!
Unfortunately, if you save a file, Notepad IMMEDIATELY removes the backup…

As you can imagine, this was **extremely annoying,** and it took a long time to redo my work.

It seems to me that a very simple fix is available: please DO NOT delete the backup file even if it is saved. The amount of disk space this takes is small and anyway, if the user continues working, you will very quickly create a new backup file. So what is the point of deleting the backup in the first place?

The conclusion is that if I had NOT saved the file, I would still have had it after the reset. Rather counterintuitive!

### Steps to Reproduce the Issue

1. Make sure your PC is about to freeze up.... (I know, this can't be reproduced easily!)
2. Save your document in Notepad++
3. Do a hard reset

### Expected Behavior
I expected the backup file to be the last saved version of the file.

### Actual Behavior
The backup file was deleted BECAUSE I saved it. I do not really understand why. To save disk space for five minutes, until the next backup would be made?

### Debug Information

Notepad++ v7.3.3   (64-bit)
Build time : Mar  8 2017 - 03:39:58
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10 (64-bit)
Plugins : mimeTools.dll NppConverter.dll

**Comment by MetaChuh** [comment]
please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins if you update from version 7.5.9 or below.
if your issue still persists, and it is still of relevance, please feel free to file a new issue as easy to understand and reproducible as possible.

thank you for your help and best regards.
