### ISSUE TITLE
Double click to select word at end of line now includes the line-break following the word

### ISSUE THREAD

**Issue by mjw999** [notepad-plus-plus/notepad-plus-plus#3260]
### Description of the Issue

Double clicking to select a word at the end of the line now includes the line-break character when using Notepad++ v7.3.3.  It did not do this in previous versions.

### Steps to Reproduce the Issue

1. Find a line that has a word at the end of the line (not followed by any punctuation or other characters)
2. Double click on the word
3. The line-break following the word is also selected

### Expected Behavior

I expected just the word to be selected

### Actual Behavior

The line-break following the word was also selected

### Debug Information

I don't know if this was an intentional change, but I would never want the line-break following the word to be included if I select a word at the end of a line.  I have gone back to using Notepad++ v7.3.2 which does not have this behaviour.

**Comment by Manuela-Fereira** [comment]
Dup
https://github.com/notepad-plus-plus/notepad-plus-plus/issues/3192
https://github.com/notepad-plus-plus/notepad-plus-plus/issues/3203

**Comment by MetaChuh** [comment]
please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins if you update from version 7.5.9 or below.
if your issue still persists, and it is still of relevance, please feel free to file a new issue as easy to understand and reproducible as possible.

thank you for your help and best regards.
