### ISSUE TITLE
Restoring position after Ctrl+Tab does not take into account Word Wrap

### ISSUE THREAD

**Issue by sbil33** [notepad-plus-plus/notepad-plus-plus#3261]
Switching between (multi-page) documents using ctrl+tab with Word Wrap turned on and documents containing long (wrapped) lines does not restore document position correctly.

Steps to Reproduce:
(1) Unmaximize notepad++ window,
(2) turn Word Wrap on,
(3) make line which is wrapped and copy-paste to form document several pages long,
(4) set position to the end or closer to the end of file,
(5) press ctr-tab to switch to any other document and then back.

Expected Behavior:
View is exactly the same as it was before switching to other document.

Actual Behavior:
Document is scrolled up, while cursor still remains at its position below visible part of document.

Looks like restoration of document position does not calculate wrapped lines.

Version 7.3.3 (32 bit).
Windows 8.1 64 bit.

---

This was submitted recently, but steps were incomplete and it was closed as not reproducible.

**Comment by fml2** [comment]
This might be related to #3570.

**Comment by MetaChuh** [comment]
please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins if you update from version 7.5.9 or below.
if your issue still persists, and it is still of relevance, please feel free to file a new issue as easy to understand and reproducible as possible.

thank you for your help and best regards.
