### ISSUE TITLE
Column Mode too difficult to use

### ISSUE THREAD

**Issue by Genjar** [notepad-plus-plus/notepad-plus-plus#3263]
This has been a problem for several versions. Edit > Column Mode doesn't work anymore, it simply pops up a message now, telling you to use a key combo instead. 

The problem is, I have no idea what 'ALT + Mouse Selection' even means in this context, and I've never been able to get 'Alt + Shift + Arrow key' to work reliably. Sometimes it does toggle it on if I hammer those long enough, but usually it doesn't. So I'm pretty much unable to use it. Whenever I need it, I usually end up messing around with the keys for a while, trying to get it to work. And then give up and do the edits the hard way. 

There's no way to redefine those combos either, as far as I can see.

**Comment by rddim** [comment]
`ALT + Mouse Selection` means that firstly you must press and hold down the `ALT` key and then make a desired selection with the left mouse button. Also you can use `Alt + Shift + Mouse Selection`. The `Alt + Shift + Arrow key` is the same - press and hold down `Alt` key then press and hold down `Shift` key and then play with the `Arrow` keys.

**Comment by Genjar** [comment]
Thank you. I got the ALT + mouse selection working. My mistake was trying to press those simultaneously instead of in a sequence. Easy to use now that I know how.

Still can't get the arrow key combo to work, not that I need to, anymore. I suspect that it's getting overridden by something else that I'm using. Got a lot of accessibility software running.

**Comment by rddim** [comment]
Glad to read that it's working. For arrow key combo you can check the `Shortcut Mapper...` in `Settings` for duplicate shortcuts or something else. Or you have a hardware problem...

**Comment by sasumner** [comment]
@zubairy Enter and maintain column mode with keyboard by shift+alt+arrow. Leave column mode by arrowing with shift+alt.  Ultraedit probably maintains column mode status without something like shift+alt being done continuously; Notepad++ takes a different approach.

**Comment by chcg** [comment]
1. ALT + 2. mouse selection and
1. (Alt + Shift) + 2. Arrow key  working fine and sufficiently from my point of view.
