### ISSUE TITLE
MUST issue Loss of data warning for "New Workspace" menu item

### ISSUE THREAD

**Issue by MindFulVoice** [notepad-plus-plus/notepad-plus-plus#3267]
### Description of the Issue

Notepad++ MUST MUST MUST issue warning that all workspace content in the tree
will be lost, when the **"New Workspace"** menu item is selected. 
User must save the existing workspace if he/she wants to load it back. 

I have lost my whole workspace and had to reconstruct it again painfully. 

### Steps to Reproduce the Issue

1. Create a workspace, and add files to it.
2. Select the workspace and select, "New Workspace"
3. There is NO WARNING that you are going to loose the workspace content.
    This is a MUST.
    Notepad++ MUST warn the user that he/she is going to loose the current workspace data,
   if he had not saved it earlier. 
4. Another approach is to name the menu as "**Remove Workspace**" instead 
  of the current "New Workspace". I think that is more appropriate.
  "New Workspace" for most of the people is not destructive, but additive, 
  I thought it would create another new workspace, 
  never thought it will kill the current workspace. 
  
### Expected Behavior

(1) If you do not want to keep the "New workspace" menu.
A warning dialog should come up with the following warning when it is selected by the user. 
**"This operation will delete this workspace, you will not be able to get back 
the current workspace content if you have not saved it earlier" 
Are you sure you want to proceed?"** 
or just 
(2) Rename "New Workspace" to **"Remove Workspace"**
### Actual Behavior

After issuing the "New Workspace" menu item, I lost my workspace, 
and then painfully had to recreate it.

**Comment by DavidHansen-0x454d43** [comment]
I'm not sure if this is still an issue... in my testing, when choosing "New Workspace" the current workspace's content was not lost (the xml configuration file still remained and could be opened up again). 

Also, if "New Workspace" is selected on a new or modified workspace, then the following dialog is displayed:
![image](https://user-images.githubusercontent.com/26116146/31568214-cdb9a98e-b038-11e7-803b-5ac2041446c9.png)

In my opinion this is providing sufficient warning to the user. 

I believe that this issue can be closed.

**Comment by MetaChuh** [comment]
please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins if you update from version 7.5.9 or below.
if your issue still persists, and it is still of relevance, please feel free to file a new issue as easy to understand and reproducible as possible.

thank you for your help and best regards.
