### ISSUE TITLE
Lenny Face ( ͡° ͜ʖ ͡°) does not display correctly

### ISSUE THREAD

**Issue by ed588** [notepad-plus-plus/notepad-plus-plus#3269]
### Description of the Issue

The lenny face ( ͡° ͜ʖ ͡°) does not display correctly by default in notepad++. I think this is a terrible mistake and should be rectified as soon as possible
### Steps to Reproduce the Issue

1.  paste the ( ͡° ͜ʖ ͡°) into notepad++
2.  it doesn't display correctly and looks weird

### Expected Behavior

I expected it to display correctly, like I would see it anywhere else. (apart from comic sans or novelty fonts or whatever)
### Actual Behavior

This: 
![image](https://cloud.githubusercontent.com/assets/19167629/26034283/4b86b784-38b2-11e7-9bca-4ca1cd393515.png)

### Debug Information

none

**Comment by kuba160** [comment]
It's because of the font (default: Courier New) which is monospaced. Use non-monospace font like Arial to get lenny face displayed correctly.
![lenny](https://cloud.githubusercontent.com/assets/6359901/26034937/0006d0d8-38c5-11e7-9a5e-b0dde6a6dfb0.png)

**Comment by oliverh57** [comment]
This is a big deal guys

**Comment by ed588** [comment]
ok, how do I change the font?

(by the way, i may have been being slightly sarcastic 😄 )

**Comment by kuba160** [comment]
@ed588  
**Settings - Style Configurator** -> Font name
Remember to check `Enable global font`.
