### ISSUE TITLE
Scintilla 3.56 forcing anti-aliasing?

### ISSUE THREAD

**Issue by koogler** [notepad-plus-plus/notepad-plus-plus#327]
I'm having the same problem as [this user](http://superuser.com/questions/931881/how-to-disable-anti-aliasing-in-notepad-6-7-9-2). When I upgraded to version 6.7.9.2 my text went from this:

 ![not anti-aliased](http://i.imgur.com/vVTbMdi.png)

to this:

![anti-aliased](http://i.imgur.com/knvjPkW.png)

Version 6.7.8.2 works fine. I grabbed a copy of version 6.7.9 from FileHippo to see if it caused the same problem, and it did, which makes me think the new version of Scintilla may be responsible.

**Comment by Croydon** [comment]
Why is this a bad thing?

**Comment by tico-tico** [comment]
Same issue here. Anti-aliased Courier New looks awful.
Maybe related to changes in the Release 3.3.7 of scintilla (For DirectWrite, use the GDI ClearType gamma value.....).

**Comment by milipili** [comment]
Is this related to #216  ?

**Comment by jonandr** [comment]
@Croydon Anti-aliasing is accomplished by blurring text, which does not agree with every combination of eye and screen.

@koogler See @Yaron10's comment in #116 for a workaround. The fundamental issue is fixed in #311 which should hopefully be merged in the next release.

**Comment by zarakon** [comment]
I'm seeing this too.

@Croydon It's bad because 1. it should follow the system setting and it isn't, and 2. it just looks really bad to some people.

Luckily I was able to use @Yaron10's workaround and fix it before my eyes lost too much blood from looking at all the blurry rainbow-edged text.
