### ISSUE TITLE
NOTEPAD ++ code is automatically prompted for accessibility advice

### ISSUE THREAD

**Issue by dingpengyu** [notepad-plus-plus/notepad-plus-plus#3271]
NOTEPAD ++ code automatically prompted the accessibility recommendations hi, respected NOTEPAD ++ development group Hello, I am a Chinese blind user, is now using NOTEPAD ++ learning html, php, js, python, these few languages. Now encounter some of the more difficult problems, whether you can feedback about? At present, the code suggests that this problem is my most troublesome. Because, I rely on listening to the screen reader to read the contents of the computer to understand the information, then, because listening to reading did not read the reasons for high efficiency, followed by Braille display in China can be said that the existence of giant pandas. So, such as the above and so on, there is this letter. I am now mainly using NVDA, and fight the screen reading software that two screen readers, first of all, NVDA is an open source, free screen reader. Second, the struggle to read the screen software is a blind development of the Chinese people a screen reader, he is mainly business owners, but he has a version of the process can let the Chinese blind use. I mainly use NVDA more, then I am also optimistic about the development prospects of NVDA. Now the biggest problem is that the code suggests that NVDA can not read at all when I switch to html, js, php, python. These languages ​​and open the code automatically after the completion of. Enter the relevant label NVDA prompts to enter the English letters, and select the code list NVDA can not display and select. My operating environment is: Lenovo notebook, windows10-1703x64, notepad ++ 7.3.3 Finally, talk about why I chose NOTEPAD ++: In fact, I also installed and used Microsoft's vs, and so popular programming ide. Because vs huge complexity and other reasons so that I am at a loss, and then because it is to write some small projects, will not use too complicated features, so I chose NOTEPAD + +. Finally, because NOTEPAD strong scalability, and open source reasons to choose him. Here are some github code libraries for official reference only: NVDA official github: nvaccess / nvda https://github.com/nvaccess/nvda nvda-notepadPlusPlus https://github.com/derekriemer/nvda-notepadPlusPlus

**Comment by MetaChuh** [comment]
please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins if you update from version 7.5.9 or below.
if your issue still persists, and it is still of relevance, please feel free to file a new issue as easy to understand and reproducible as possible.

thank you for your help and best regards.
