### ISSUE TITLE
Notepad++ 7.4 Can't save file

### ISSUE THREAD

**Issue by hunabku94** [notepad-plus-plus/notepad-plus-plus#3272]
### Description of the Issue
When i ask to save or save to, Notepad++ warn me can't save   because don't have enough save or something.

### Steps to Reproduce the Issue
1. Install Notepad++ 7.4 x64 with installer, no theme, no plugin, french translation.
2. open or create a text file
3. add something on it
4. ask for save it

### Expected Behavior

I think the problem in about permissions.
I checked the space, no problem.
I tried to save on Desktop, same problem.

### Debug Information
Notepad++ v7.4   (64-bit)
Build time : May 14 2017 - 21:02:35
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : ON
Local Conf mode : OFF
OS : Windows 7 (64-bit)
Plugins : none

Screenshot : http://prntscr.com/f7y7pv

**Comment by hunabku94** [comment]
I tested on a fresh Windows 10, same problem.

**Comment by AngryGamer** [comment]
Related: https://notepad-plus-plus.org/community/topic/13820/weird-7-4-issue-unable-to-save-new-files

**Comment by hunabku94** [comment]
Fixed for me with the [proposed file](https://notepad-plus-plus.org/temp/notepad++.zip).
Thanks a lot.

**Comment by DingowithoutO** [comment]
Same to me. Windows 10 home x64 v14393, using npp 7.4 x64 from either installer or portable package as administrator. Can't save files, Says "not enough space?" :( 
Tried 7.3.3 and it worked as normal :)

**Comment by AngryGamer** [comment]
Fixed in [v7.4.1](https://notepad-plus-plus.org/news/notepad-7.4.1-released.html)

**Comment by fun29** [comment]
Unfixed in 7.7.1 (or somewhere in between 7.4.1 and 7.7.1, I did not check all versions)

In combination with Windows 10 version 1809

Cannot save small/basic .txt file on Desktop.

N++ first asks to run in admin mode, then in admin mode complains about disk space.
