### ISSUE TITLE
Tab headers rendering issue in multiline mode on XP after 7.4 update

### ISSUE THREAD

**Issue by KOLANICH** [notepad-plus-plus/notepad-plus-plus#3273]
1 Spacing between tab headers appeared.
2 Active tab header looks indented.

**Comment by AngryGamer** [comment]
Multi-Line?

The tabs in multi-line were changed to buttons in order maintain the active tab's row. This was done because the constant reordering of rows was confusing and also made tab drag and drop unusable.

**Comment by KOLANICH** [comment]
>Multi-Line?

Yes.

>The tabs in multi-line are now buttons in order to maintain the active tab's row. Previously, the active tab's row moved to the front/bottom which is confusing and caused reordering/sorting of tabs to be difficult.

I know. 
>The margins around button-tabs is an unfortunate limitation in Window's TabControl.

Could you explain more clearly why is it necessary to make tabs buttons?

**Comment by AngryGamer** [comment]
> Could you explain more clearly why is it necessary to make tabs buttons?

> Previously, the active tab's row moved to the front/bottom which is confusing and caused reordering/sorting of tabs to be difficult.

**Comment by KOLANICH** [comment]
>The tabs in multi-line are now buttons in order to maintain the active tab's row. Previously, the active tab's row moved to the front/bottom which is confusing and caused reordering/sorting of tabs to be difficult.

It's not an explanation. It is description. The explanation is the cause of that reordering.

>Window's TabControl has no other way. The other solution is to replace Window's TabControl with something else entirely.

So why this way have not been chosen? Do workarounds like creating an own TabControl instance per line and process dragging in npp code make much troubles?

**Comment by AngryGamer** [comment]
> So why this way have not been chosen? Do workarounds like creating an own TabControl instance per line and process dragging between different lines in npp code make much troubles?

Sounds like a lot of work. If you're up for the challenge and get something working, then you could always make a Pull Request.

**Comment by MetaChuh** [comment]
please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins if you update from version 7.5.9 or below.
if your issue still persists, and it is still of relevance, please feel free to file a new issue as easy to understand and reproducible as possible.

thank you for your help and best regards.
