### ISSUE TITLE
Highlighting not working correctly for tab-indented words

### ISSUE THREAD

**Issue by antony677** [notepad-plus-plus/notepad-plus-plus#3274]
### Description of the Issue
For programming javascript I need to highlight variables to see where they occur in the code (multiple times). In Notepad++ Version 6.7.7 it still works perfectly in a javascript file. In the current version it's buggy in javascript files. Words that are tab-indented are not highlighted with the green background color any more when double clicked.

### Steps to Reproduce the Issue
1. It is definitely reproducable in javascript files.
2. Since i uninstalled the buggy version I cannot say more.

### Expected Behavior
ALL occurings of the double clicked words should be highlighted.

### Actual Behavior
Words with tabs in front of them, I mean, tab-indented words are not highlighted.

### Debug Information
I had to install the older version 6.7.7. This cannot be the solution.

**Comment by AngryGamer** [comment]
I can't reproduce this problem in v7.4. Maybe upload an animated gif/video of the problem occurring? And maybe a test file?

**Comment by antony677** [comment]
Hi AngryGamer,

I hadn't seen the v7.4 yet. I just testet it and can't reproduce this problem either. It must have been fixed. Thanks to the community!
