### ISSUE TITLE
Detection of Perl functions doesn't work any more after 7.4 update (32 bits)

### ISSUE THREAD

**Issue by KptainBiwouak** [notepad-plus-plus/notepad-plus-plus#3276]
### Description of the Issue
Perl sub-functions are no more detected by showing 'Functions' menu

### Steps to Reproduce the Issue
1. Just load one perl module (".pm")
2. Select Function Menu

### Expected Behavior
Sub-Functions should be highlighted

### Actual Behavior
No sub-Function highlighted

### Debug Information

Notepad++ v7.4   (32-bit)
Build time : May 14 2017 - 20:35:30
Path : C:\tools\Notepad++\notepad++.exe
Admin mode : ON
Local Conf mode : ON
OS : Windows 7 (64-bit)
Plugins : DoxyIt.dll DSpellCheck.dll HexEditor.dll HTMLTag_unicode.dll mimeTools.dll MusicPlayer.dll NppConverter.dll NppExport.dll nppplugin_solutionhub.dll nppplugin_solutionhub_ui.dll nppplugin_svn.dll NppTextFX.dll NppVerilog.dll NppVHDL.dll PluginManager.dll PyNPP.dll Python Indent.dll PythonScript.dll SpellChecker.dll XMLTools.dll

**Comment by MAPJe71** [comment]
See #2964.

**Comment by ArkadiuszMichalski** [comment]
@KptainBiwouak Can you check if problem still exist in Notepad++ 7.9 RC http://download.notepad-plus-plus.org/repository/7.x/7.9.RC/ ?

**Comment by KptainBiwouak** [comment]
Hello,
I have successfully checked with the latest 7.9RC .
Thanks for your Help,
