### ISSUE TITLE
Notepad++ Ribbon GUI Request

### ISSUE THREAD

**Issue by ronovar** [notepad-plus-plus/notepad-plus-plus#3277]
I im using Notepad++ for all programming and editing all sort of txt files..and is fantastic piece of software....could you please update GUI of Notepad++ to be more Nice looking like redesigning Notepad++ style to windows ribbon gui? Like Office 2007 and newer version..this will be very nice.

Thanks.

**Comment by JosephNovak** [comment]
No, No, No!

**Comment by ronovar** [comment]
Why not? This way will be more nice looking.
