### ISSUE TITLE
JSON language format

### ISSUE THREAD

**Issue by pjbryant** [notepad-plus-plus/notepad-plus-plus#328]
Any thoughts of implementing a JSON layout feature that does something like http://jsonformatter.curiousconcept.com/.  Appreciate that's might be seen as duplication, but I just tried to do it, and found N++ didn't have JSON as a language option.  
Where is would be particularly useful is for large files as the website has a size limit.

Thanks!

**Comment by cmeriaux** [comment]
There is a plugin JSON Viewer that would help you

**Comment by pjbryant** [comment]
thanks, I really should have thought of that first.  Cheers!

**Comment by cpasmoi** [comment]
yea wondering why json files aren't colored :'(

**Comment by milipili** [comment]
It should work in the next release. See #336
