### ISSUE TITLE
Certificate error in 7.4 executable

### ISSUE THREAD

**Issue by tvdijen** [notepad-plus-plus/notepad-plus-plus#3284]
### Description of the Issue
After installing 7.4 x64 the application it won't start up anymore.
"Library verification failed - Authenticode check failed: signature or signing certificate are not recognized"

### Steps to Reproduce the Issue
1. Fallback to the 7.3 branch fixes this issue
2. Reinstalling 7.4 introduces it again

### Debug Information
The certificate of the executable seems to have been manipulated:
![afbeelding](https://cloud.githubusercontent.com/assets/841045/26100751/0ddc3e4e-3a2f-11e7-85dc-ed90fdad743e.png)
It is trusted though:
![afbeelding](https://cloud.githubusercontent.com/assets/841045/26100906/92d1ba3e-3a2f-11e7-8707-a58a7b66380e.png)

**Comment by AngryGamer** [comment]
Fixed in [v7.4.1](https://notepad-plus-plus.org/news/notepad-7.4.1-released.html)

**Comment by tvdijen** [comment]
Will try the 7.4.1 release later today to see if it fixed things

**Comment by tvdijen** [comment]
Fixed in 7.4.1
