### ISSUE TITLE
Error in starting Notepad++

### ISSUE THREAD

**Issue by bvvuz** [notepad-plus-plus/notepad-plus-plus#3285]
Error starting (installed version) Notepad++ (npp.7.4.Installer.exe, 32 bit), on Windows 2003 ru 32bit, old version (npp.7.3.2.Installer.exe) worked on this platforms.

![notepad bug 1](https://cloud.githubusercontent.com/assets/15726839/26101032/35511214-3a49-11e7-92ce-b7d0a42fc513.jpg)

![notepad bug 2](https://cloud.githubusercontent.com/assets/15726839/26101041/3c404cfc-3a49-11e7-8993-b7ad9617008a.jpg)

Howto fix this errors ??

P.S. Sorry my bad english =)...

Best, regards, sl.

**Comment by tvdijen** [comment]
Duplicate: https://github.com/notepad-plus-plus/notepad-plus-plus/issues/3284

**Comment by tvdijen** [comment]
Fixed in 7.4.1
