### ISSUE TITLE
Pasting does not close autocomplete suggestion window

### ISSUE THREAD

**Issue by adamzovits** [notepad-plus-plus/notepad-plus-plus#3287]
### Description of the Issue
Given a text file with existing words and some text on the clipboard, when a word is typed that could be autocompleted to a previously existing word but finished with pasting the contents from the clipboard, the autocomplete suggestion window stays open and pressing Enter will result in the suggestion overwriting the pasted text.

### Steps to Reproduce the Issue
1. Open a new file
2. Type for example "abcdefghijk" and press Enter
3. Copy to the clipboard some other text, for example "1234"
4. Type "abcdef"
5. At this point (depending on autocomplete settings) the suggestion window will be open
6. Paste using Ctrl-V or the Edit menu (pasting via the context menu works fine)
7. Now the second line will be "abcd1234" but the suggestion window is still open
8. Press Enter
9. The second line will be changed to "abcdefghijk"

### Expected Behavior
At step 7. the suggestion window should close, and at step 9. the second line should be "abcd1234"

### Actual Behavior
See under Steps to Reproduce

### Debug Information
Notepad++ v7.4   (64-bit)
Build time : May 14 2017 - 21:02:35
Path : C:\Users\t0168888\AppData\Local\Downloads\npp\notepad++.exe
Admin mode : OFF
Local Conf mode : ON
OS : Windows 7 (64-bit)
Plugins : none

**Comment by MetaChuh** [comment]
please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins if you update from version 7.5.9 or below.
if your issue still persists, and it is still of relevance, please feel free to file a new issue as easy to understand and reproducible as possible.

thank you for your help and best regards.
