### ISSUE TITLE
Crash opening specific textfile with double click in windows explorer

### ISSUE THREAD

**Issue by PeterCodar** [notepad-plus-plus/notepad-plus-plus#3288]
### Description of the Issue
Whenever I try to open such a simple textfile with a double click in windows 10 explorer, Notepad++ crashes

### Steps to Reproduce the Issue
1. Double click on the attached textfile

### Expected Behavior
Open the text file and show content as even the standard windows editor does it

### Actual Behavior
Crash when double click the file.
BUT: 
If you drag & drop the same file or open it through an already open Notepad++ with File -> Open, the same file will be opened fine.

### Debug Information
Notepad++ v7.4   (32-bit)
Build time : May 14 2017 - 20:35:30
Path : C:\Program Files (x86)\Tools\System\NotepadPP\notepad++.exe
Admin mode : OFF
Local Conf mode : ON
OS : Windows 10 (64-bit)
Plugins : ComparePlugin.dll HexEditor.dll mimeTools.dll NppConverter.dll NppExport.dll NppTextFX.dll PluginManager.dll 

[emerge.zip](https://github.com/notepad-plus-plus/notepad-plus-plus/files/1005159/emerge.zip)

**Comment by PeterCodar** [comment]
Workaround:
If I  deinstall the Hex-Editor Plugin (even though the stability for Hex-Editor v.0.9.5 is listed as "Good" in the Plugin Manager), the *.nfo files can be doubleclicked as expected.

**Comment by MetaChuh** [comment]
please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins if you update from version 7.5.9 or below.
if your issue still persists, and it is still of relevance, please feel free to file a new issue as easy to understand and reproducible as possible.

thank you for your help and best regards.

**Comment by jlegen** [comment]
This exact issue re-appeared in 7.7.1 - removing "Hex Editor" solves this (again) for now...

**Comment by chcg** [comment]
@PeterCodar @jlegen You may want to update\contribute to https://github.com/chcg/NPP_HexEdit/issues/13
