### ISSUE TITLE
The \r in the translationfiles is not replaced with a carriage return

### ISSUE THREAD

**Issue by MaDill** [notepad-plus-plus/notepad-plus-plus#3294]
### Description of the Issue
When in the translation string a **\r** to represent a carriage return this is not replaced and just displayed.

### Steps to Reproduce the Issue
Click for example in the menu Settings -> Edit Popup ContextMenu

### Expected Behavior
Replace **\r** from the translation file to a real carriage return. 

### Actual Behavior
Screenshot: ![backslash_r](https://cloud.githubusercontent.com/assets/7298934/26192749/2b76eaf0-3bb3-11e7-8581-1fbbbb578bf1.png)

### Debug Information
Notepad++ v7.4.1   (32-bit)
Build time : May 18 2017 - 02:00:37
Path : F:\_PortablePrograms\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : ON
OS : Windows 7 (64-bit)
Plugins : Explorer.dll LanguageHelp.dll LuaScript.dll MenuIcons.dll mimeTools.dll NppConverter.dll NppExec.dll NppExport.dll PluginManager.dll PythonScript.dll Scintillua++.dll

**Comment by rddim** [comment]
The solution for now is to replace `\r` with `&#x0A;`. See #3280
