### ISSUE TITLE
[Feature request] Select Next Occurrence

### ISSUE THREAD

**Issue by UziTech** [notepad-plus-plus/notepad-plus-plus#3295]
Sublime and atom have the ability to select the next occurrence of the current selection with `[ctrl] + [d]`

according to [this thread](https://notepad-plus-plus.org/community/topic/11360/multi-selection-and-multi-edit/3) the functionality can be added by updating Scintilla

**Comment by cmeriaux** [comment]
It's already implemented with "find volatile next". I set a shortcut to this function, and I use it everytime

**Comment by UziTech** [comment]
`Find (Volatile) Next` seems to do the same thing as `Select and Find Next`. It selects the next instance of the selected text but unselects the currently selected text.

I want it to select both the currently selected text and the next instance of the currently selected text. It would be the same thing as holding `[ctrl]` and selecting the next instance of the currently selected text with you mouse when `Multi-Editing` is enabled.

**Comment by UziTech** [comment]
is this possible yet?

**Comment by xylographe** [comment]
Yes, this is possible with the LuaScript plugin.

**Comment by UziTech** [comment]
@xylographe could you explain more about how to do this with the LuaScript plugin?

**Comment by UziTech** [comment]
found it https://dail8859.github.io/LuaScript/examples/selectionaddnext.lua.html

```lua
-- Select the next occurrence of the current word
npp.AddShortcut("Selection Add Next", "Ctrl+D", function()
    -- From SciTEBase.cxx
    local flags = SCFIND_MATCHCASE -- can use 0
    editor:SetTargetRange(0, editor.TextLength)
    editor.SearchFlags = flags

    -- From Editor.cxx
    if editor.SelectionEmpty or not editor.MultipleSelection then
        local startWord = editor:WordStartPosition(editor.CurrentPos, true)
        local endWord = editor:WordEndPosition(startWord, true)
        editor:SetSelection(startWord, endWord)
    else
        local i = editor.MainSelection
        local s = editor:textrange(editor.SelectionNStart[i], editor.SelectionNEnd[i])
        local searchRanges = {{editor.SelectionNEnd[i], editor.TargetEnd}, {editor.TargetStart, editor.SelectionNStart[i]}}
        for _, range in pairs(searchRanges) do
            editor:SetTargetRange(range[1], range[2])
            if editor:SearchInTarget(s) ~= -1 then
                editor:AddSelection(editor.TargetStart, editor.TargetEnd)
                editor:ScrollRange(editor.TargetStart, editor.TargetEnd)
                break
            end
        end
    end
end)
```

**Comment by sasumner** [comment]
@UziTech You didn't have to close it just because you found a solution via a plugin.  To me, although I don't think I'll use it, it seems like something that should be in the core Notepad++.  If you agree, reopen and let the developers judge.
