### ISSUE TITLE
"Treat backslash as escape characters for SQL" fails for SQLCMD mode :setvar script

### ISSUE THREAD

**Issue by JamieOglethorpeEPS** [notepad-plus-plus/notepad-plus-plus#3297]
### Description of the Issue
A :setvar command uses double quotes for the value part:
:setvar DefaultDataPath "C:\EPS\Data\\"

The backslash is treated as an escape character regardless of the setting.
This example was generated by SqlPackage.exe

### Steps to Reproduce the Issue
1. Create a new document (e.g. ctrl-n)
2. Set the language to SQL
3. Capture the following two lines:
"\\"
GO

### Expected Behavior
The GO command should be blue

### Actual Behavior
The GO command is grey.

### Debug Information

Screenshot:
![image](https://cloud.githubusercontent.com/assets/17747729/26247500/7267595e-3c9e-11e7-8d6a-bf03ac1b8316.png)

Reference: Issue 2451

**Comment by johnkeymer** [comment]
I also have encountered this problem. The easiest reproduction is:

![2018-04-09 09_50_21-_new 1 - notepad](https://user-images.githubusercontent.com/31100231/38488494-8d2cc386-3bdb-11e8-981e-77ec510817a1.png)

**Comment by dail8859** [comment]
Turn off  `Settings > Preferences > MISC > Treat backslash as escape character for SQL`

---

![image](https://user-images.githubusercontent.com/3694843/58263852-cce32180-7d4a-11e9-95e8-76b11ba3c9d0.png)

**Comment by idata-frank** [comment]
For anyone encountering this, this setting has moved to Preferences > Language

<img width="696" height="423" alt="Image" src="https://github.com/user-attachments/assets/5f51bad9-45c3-4cd6-b1f3-a4a6f9d8af1d" />
