### ISSUE TITLE
Hotkeys file shouldn't be present in the NPP folder, causes overwrites and loosing custom hotkeys

### ISSUE THREAD

**Issue by mzso** [notepad-plus-plus/notepad-plus-plus#3298]
<del>Hi!</del>

<del>I set "Save As" to Ctrl+Shift+S several times but, it always resets to default after some time. Not sure what causes it.</del>

The loss of hotkeys occurs because the portable package already includes the hotkey file with default values (unlike all other configuration files.) as such are overwritten when one updates a portable instance.

(May, or may not happen with the installed version, which I didn't try )

**Comment by mzso** [comment]
What's the point of setting a hotkey if it's not permanent? Today I noticed that it was reset to ctrl+alt+s again.

**Comment by cmeriaux** [comment]
your environment may be corrupted. you may tray a fresh install.

**Comment by mzso** [comment]
[**@cmeriaux**](https://github.com/cmeriaux) commented on [2018. febr. 9. 07:19 CET](https://github.com/notepad-plus-plus/notepad-plus-plus/issues/3298#issuecomment-364345908 "2018-02-09T06:19:36Z - Replied by Github Reply Comments"):
> your environment may be corrupted. you may tray a fresh install.

I doubt it. All my other settings persist. But it comes to me now that I recently upgraded NP++.

It seems like an NP++ design flaw. I see now that there's a shortcuts.xml included with the NPP 7z/zip package and even the installer. So every time someone upgrades the shortcuts are overwritten. Other config files seem to be generated as they are needed or they have a ".model" extension file with default values, so why not this?
(there a bunch of them: config.xml, langs.xml, session.xml, stylers.xml)

**Comment by mzso** [comment]
[**@cmeriaux**](https://github.com/cmeriaux) commented on [2018. febr. 9. 17:50 CET](https://github.com/notepad-plus-plus/notepad-plus-plus/issues/3298#issuecomment-364490213 "2018-02-09T16:50:14Z - Replied by Github Reply Comments"):
> I can't reproduce your problem. Try with the portable version.

What do you mean you can't reproduce it? You look into the 7z package and you see "shortcuts.xml".

As such when you unpack onto the local version it will overwrite custom hotkeys

**Comment by cmeriaux** [comment]
> I set "Save As" to Ctrl+Shift+S several times but, it always resets to default after some time. Not sure what causes it.
I can't reproduce this issue mentionned.

Check out this doc : 
http://docs.notepad-plus-plus.org/index.php/Configuration_Files 

I'm pretty sure you missed something obvious.

Like I said, try to reproduce the problem you mentionned at the top with the portable edition.

**Comment by mzso** [comment]
[**@cmeriaux**](https://github.com/cmeriaux) commented on [2018. febr. 9. 18:57 CET](https://github.com/notepad-plus-plus/notepad-plus-plus/issues/3298#issuecomment-364509457 "2018-02-09T17:57:58Z - Replied by Github Reply Comments"):
> > I set "Save As" to Ctrl+Shift+S several times but, it always resets to default after some time. Not sure what causes it.
> 
> I can't reproduce this issue mentionned.
> 
> Check out this doc :  
> 
> [http://docs.notepad-plus-plus.org/index.php/Configuration_Files](http://docs.notepad-plus-plus.org/index.php/Configuration_Files)
> 
> I'm pretty sure you missed something obvious.
> 
> Like I said, try to reproduce the problem you mentionned at the top with the portable edition.

If by portable you meant the 7z/zip archived packages, then that's what I've been using all along. (Otherwise there's no package explicitly called portable)

I'm quite sure it's not me who's missing the obvious. Is I said the package has the hotkeys file with default values, which always overwrites the customized one, when one unpacks its content. What's so incomprehensible about this?
It's clearly the file being used:
![npp-shortcuts](https://user-images.githubusercontent.com/4479090/36043269-0de9b35c-0dcf-11e8-97f6-cc537c9c4427.PNG)
(also there's nothing in appdata, so NP++ doesn't keep config files there with the 7z version.)

It takes one second to look into the official 7z package to verify this.

**Comment by cmeriaux** [comment]
Chill out, I'm trying to help you.
I'm trying to understand your working environnent. 

> If by portable you meant the 7z/zip archived packages, then that's what I've been using all along

So npp store every custom parameters locally (due to file doLocalConf.xml). when unzipping a new package, your custom parameters are lost. This is not a bug, this is the normal behavior.

here is two options : 

1. Use the installer instead the 7z archive
2. keep your environment as it is but remove the file doLocalConf.xml

For more informations, check out this doc :
http://docs.notepad-plus-plus.org/index.php/Configuration_Files

**Comment by cmeriaux** [comment]
you may be right. You can correct it and submit a Pull Request. In the mean time, you should consider using   one of the 2 suggestion I've made.

**Comment by mzso** [comment]
[**@cmeriaux**](https://github.com/cmeriaux) commented on [2018. febr. 10. 13:18 CET](https://github.com/notepad-plus-plus/notepad-plus-plus/issues/3298#issuecomment-364647752 "2018-02-10T12:18:26Z - Replied by Github Reply Comments"):
> you may be right. You can correct it and submit a Pull Request. In the mean time, you should consider using   one of the 2 suggestion I've made.

I would if I could. :) I hope someone will get to it sometime.

**Comment by MAPJe71** [comment]
> Also, how else would someone update a portable instance than unpacking the files from the newer version and overwriting the old files?

I use a diff/merge tool to compare and merge the contents of the installed version and the zip archive of the new version.

**Comment by mzso** [comment]
[**@MAPJe71**](https://github.com/MAPJe71) commented on [2018. febr. 10. 14:06 CET](https://github.com/notepad-plus-plus/notepad-plus-plus/issues/3298#issuecomment-364651285 "2018-02-10T13:06:19Z - Replied by Github Reply Comments"):
> > Also, how else would someone update a portable instance than unpacking the files from the newer version and overwriting the old files?
> 
> I use a diff/merge tool to compare and merge the contents of the installed version and the zip archive of the new version.

How does that help? You still have to know what files can and can't be overwritten. An still have to know why the extra files in the installed version are present. Any number of updated files might have changed between versions.

I think until it's fixed I'll set file permissions to prevent the accidentally overwriting the hotkeys file.

**Comment by CookiePLMonster** [comment]
As far as I understand, "portable" applications should be used for quick, "stateless" editing sessions. If you have your settings you can't afford losing, just switch to an installer version.

**Comment by mzso** [comment]
[**@CookiePLMonster**](https://github.com/CookiePLMonster) commented on [2018. febr. 10. 15:10 CET](https://github.com/notepad-plus-plus/notepad-plus-plus/issues/3298#issuecomment-364657743 "2018-02-10T14:10:28Z - Replied by Github Reply Comments"):
> As far as I understand, "portable" applications should be used for quick, "stateless" editing sessions. 

I'd say that's just a use-case.

**Comment by MAPJe71** [comment]
@mzso
> You still have to know what files can and can't be overwritten. ...

True, it was just _an_ answer to your question "how else".

> I'd say that's just a use-case.

And so is yours: _a_ use-case.

Nevertheless, I think we can all agree that a proper/improved mergeing of updated settings with customized settings is desirable (see also #1205).

**Comment by mzso** [comment]
I updated the title to so that it describes the actual issue.

@donho 
Can this be fixed? I really think this is a flaw. Because, unlike `shortcuts.xml` all other configuration files are either generated by the program, or supplied with .model suffix containing default values, so as to not overwrite configurations. It looks like the shortcuts file was simply forgotten, and not dealt with in a similar fashion.

**Comment by MetaChuh** [comment]
@mzso 

i can not reproduce, that an existing shortcuts.xml gets overwritten, if you use the notepad++ installer to update your existing notepad++.

unfortunately you did not provide us with your debug information, but if you are using a portable version of notepad++:
the portable versions do not come with an installer, which would automatically check for existing versions of your configuration files for you.
you will have to perform the installer's tasks manually, e.g. skip overwriting files that you don't want to be overwritten.

if you use windows (10) explorer to update a portable version:
as soon as you extract, or drag and drop the extracted files into your portable folder, the windows explorer will prompt you, that the destination has existing files with the same file names, which are going to be overwritten.
please read the prompts carefully, select `let me decide for each file` and do not press `replace the files in the destination`.

thank you for your help and best regards.

-----
```
general notes:

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
(no extra account is needed, just use your github account to sign in)
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)

**Comment by mzso** [comment]
@MetaChuh 
It's not only reproducible but problem is obvious.
Of course, If you don't bother to read even the description (or are incapable of comprehending it) you wouldn't know that. Hence your claiming utter nonsense.

**You just closed several issues that I saw, none with any merit. Honestly your activity here is just massively deleterious and toxic.
It's obvious you don't even understand half the issues you close.**

**Comment by CookiePLMonster** [comment]
So this place was better when it had 2.500 opened and unanswered issues?

**Comment by mzso** [comment]
[**@CookiePLMonster**](https://github.com/CookiePLMonster) commented on [2019. ápr. 21. 12:23 CEST](https://github.com/notepad-plus-plus/notepad-plus-plus/issues/3298#issuecomment-485240933 "2019-04-21T10:23:30Z - Replied by Github Reply Comments"):
> So this place was better when it had 2.500 opened and unanswered issues?

Yes. If they wanted to improve things they should label and structure issues. And only close actually invalid ones. (Or fixed ones, obviously)
