### ISSUE TITLE
Auto-completion when editing single occurence of a word

### ISSUE THREAD

**Issue by agaeb** [notepad-plus-plus/notepad-plus-plus#330]
When editing in the middle of a previously written word, autocompletion will kick in and suggest you the word you are actually typing, even if it does not occur anywhere else in the document. This is very distracting.

To reproduce, open a new document and type
`word_no_1`
then go to the letter o, delete it and start typing `umber`. After typing the u, `word_nu_1` will be suggested. 
In case of large documents, this may lead you to the belief that the incomplete word occurs already somewhere in the document and you may take it for a valid identifier although it is not.

My request would be that the word the cursor is currently in should not be considered a valid completion suggestion.

Thank you,
  Andreas

**Comment by h-h-h-h** [comment]
:+1:

**Comment by wfel** [comment]
It is much more annoying when editing some documents written in languages that do not use a space  to seperate words. I'm using npp 7.6.1 and the bug(feature?) is still there.

**Comment by wfel** [comment]
> @wfel: You might be able to turn it off altogether in the settings dialog.

Well...a temporary solution😂

**Comment by Uhf7** [comment]
> My request would be that the word the cursor is currently in should not be considered a valid completion suggestion.

It is possible to write about 15 new lines into `AutoCompletion::showWordComplete` to solve this. They work like this:
- Get the complete current word from `_pEditView`.
- After fetching the word list, but before using it, loop through the word list and erase the word that is equal to the current word. There is only one or no word matching the current word.

The result looks like this:

![ConsiderConsole](https://user-images.githubusercontent.com/40629737/81324919-f4d0af80-9097-11ea-9965-3b1f307d633a.png)

I typed `consider console con`, moved the cursor one character back, deleted the `o` and retyped it.

**Comment by Uhf7** [comment]
Sorry, my 1st solution was a bit complicated. I assumed, that Scintilla delivers the word list.

But the word list is build by Npp itself, so I reach the same result now by excluding the current word in `AutoCompletion::getWordArray`. I added a 3rd parameter to it (with the word not to be shown in the list), and modified the 2 calls of `getWordArray` accordingly.

I continue testing it.
