### ISSUE TITLE
Crashes when you multiselect with multiple cursors

### ISSUE THREAD

**Issue by GeraldNDA** [notepad-plus-plus/notepad-plus-plus#3304]
### Description of the Issue
When you select multiple words (with multiple cursors). It seems like at least on my system that this limit is 5. 4 selections works fine but the fifth one crashes  my notepad++.

### Steps to Reproduce the Issue
1. Enable multi-editing
2.  Ctrl+click 5 times

### Debug Information
Notepad++ v7.3.3   (32-bit)
Build time : Mar  8 2017 - 03:37:37
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10 (64-bit)
Plugins : EmmetNPP.dll JSLintNpp.dll mimeTools.dll NppConverter.dll NppExport.dll NppFTP.dll NppQCP.dll PluginManager.dll PreviewHTML.dll PythonScript.dll 
![image](https://cloud.githubusercontent.com/assets/11413630/26279315/58e87ffe-3d7e-11e7-98aa-75b283ab338d.png)
![image](https://cloud.githubusercontent.com/assets/11413630/26279322/69051eba-3d7e-11e7-8b90-aa92462874e7.png)

**Comment by MetaChuh** [comment]
please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins if you update from version 7.5.9 or below.
if your issue still persists, and it is still of relevance, please feel free to file a new issue as easy to understand and reproducible as possible.

thank you for your help and best regards.
