### ISSUE TITLE
Reload from disk request for file continue showing even if the previous was not processd

### ISSUE THREAD

**Issue by uskovboris** [notepad-plus-plus/notepad-plus-plus#3306]
### Description of the Issue

Reload from disk request for file continue showing even if the previous was not processd

### Steps to Reproduce the Issue

1. Create a new file. Open it in the Notepad++
2. Change the file in the other application. Notepad++ will request file reloading. Don't answer nor "yes" nor "no"
3. Change the file again. The new reqest will be shown. It may cause the npp to crash

![image](https://cloud.githubusercontent.com/assets/15656054/26297081/1a74f682-3eda-11e7-99bf-dc0b94314cd3.png)

### Expected Behavior
Only once request should be shown

### Actual Behavior
few requests were shown

### Debug Information
at least since 7.2

**Comment by uskovboris** [comment]
Also I know hot to fix this bug. I try to commit changes today

**Comment by SinghRajenM** [comment]
Could not reproduce. Is it happening without plugins as well?

Notepad++ v7.4.1   (32-bit)
Build time : May 18 2017 - 02:00:37
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10 (64-bit)
Plugins : DSpellCheck2.dll mimeTools.dll NppConverter.dll NppExport.dll PluginManager.dll

**Comment by donho** [comment]
Cannot reproduce it as well:
Notepad++ v7.4.1   (64-bit)
Build time : May 18 2017 - 19:30:55
Path : C:\sources\notepad-plus-plus\PowerEditor\visual.net\..\bin64\Notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10 (64-bit)
Plugins : mimeTools.dll NppConverter.dll
