### ISSUE TITLE
Provide option to disable automatic population of "Find what" text

### ISSUE THREAD

**Issue by NoneGiven** [notepad-plus-plus/notepad-plus-plus#3308]
### Feature request

When the Find dialog is opened with Ctrl+F, the find bar is automatically populated with text from the editor which is adjacent to the cursor or selected. This behavior can be useful, but it can also be really annoying. There should be an option to control if text is automatically populated, or if the Find just always retains your last query.

### Workaround?

It's possible to have the Find dialog remember your previous find query, but it basically requires deselecting any text and moving the cursor next to a punctuation character before you Ctrl+F. This is pretty janky, though it does prove that Find is capable of remembering the previous query already, it just tends to rudely overwrite it with text from the editor.

### I would be happy to submit a PR

If that would be acceptable.

**Comment by alankilborn** [comment]
Solution has been in place for a long time (current version tested in is 8.4.4); see "Settings" > "Preferences" > "Searching" > "Don't fill find field in Find dialog with selected word".

Suggest this issue be CLOSED.
