### ISSUE TITLE
Enable Simple Toggle for Light/Dark Theme

### ISSUE THREAD

**Issue by ghost** [notepad-plus-plus/notepad-plus-plus#3309]
### Description of the Issue
Provide a simple toggle switch in the program preferences.

### Steps to Reproduce the Issue
Set of steps to reproduce this issue:
1. Application Entry
2. Settings Menu ==>
3. Menu Option for High Visibility [dark theme]

### Expected Behavior
The Settings Menu requires an option to quickly toggle into dark theme.
Dark theme enables visibility for those that need dark background for high contrast.

### Actual Behavior
There exists a previously defined dark theme:
https://github.com/SeanCline/Npp-VS2012-Dark

### Debug Information
This option enables a gateway to accessibility.
Please enable the dark theme, it is critical for vision.

**Comment by ArkadiuszMichalski** [comment]
I assume that Dark Mode solves this problem.

![image](https://user-images.githubusercontent.com/2730894/140627315-bb804e60-b9e2-4f4f-ba1a-56c2500b9b36.png)
