### ISSUE TITLE
Menu bar, toolbar, tab bar and status bar extended beyond app border

### ISSUE THREAD

**Issue by bronkman** [notepad-plus-plus/notepad-plus-plus#3310]
### Description of the Issue
Menu bar, toolbar, tab bar and status bar are longer than windows app border in Windows 10. This occurs in maximized state as well.

### Steps to Reproduce the Issue

1. Fire up notepad++

### Expected Behavior

Length of menu bar, toolbar, tab bar and status bar should not exceed windows app width.

### Actual Behavior

Length of menu bar, toolbar, tab bar and status bar exceeded windows app width beyond the app border.

### Debug Information

![image](https://cloud.githubusercontent.com/assets/28916972/26389937/e85fa0fa-408e-11e7-8510-9ef024c9409e.png)
Image showing extended toolbar and tab bar

![image](https://cloud.githubusercontent.com/assets/28916972/26389947/f0103486-408e-11e7-8729-49b04b22b4d7.png)
Image showing extended status bar

**Comment by Jack-William** [comment]
Hi ! I'm new , I'm trying  to understand how work the big world of Github, can you help me to understand this issue ?

**Comment by DavidHansen-0x454d43** [comment]
@bronkman , I'm not able to reproduce this on Windows 8.1 (With 32-bit Notepad++, v7.5.1)

Can you please go to Notepad++'s Menu->?->Debug info, and paste that information into the thread?

**Comment by DavidHansen-0x454d43** [comment]
Oops, it looks like bronkman commented a while ago. 

@Jack-William are you able to reproduce this issue? If so, you can help by pasting your debug information into this thread.

**Comment by Jack-William** [comment]
@bronkman  I've try, but the problem didn't occur, this is the screenshot:

![toolbar](https://user-images.githubusercontent.com/25106662/32290945-e7accbac-bf3b-11e7-951f-fdc5ab51e53e.JPG)

the difference i think is the final delimiter line blue that I don't see in your image. 
Anyway these are my debug information:
Windows 10 
with 32 bit Notepad++ , v7.5.1

@DavidHansen-0x454d43  thanks for the explanation ! 👍  but i don't idea how resolve the issue,
 some help ?

**Comment by MetaChuh** [comment]
please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins if you update from version 7.5.9 or below.
if your issue still persists, and it is still of relevance, please feel free to file a new issue as easy to understand and reproducible as possible.

thank you for your help and best regards.
