### ISSUE TITLE
Ctrl+C to copy entire line when no text is selected

### ISSUE THREAD

**Issue by bronkman** [notepad-plus-plus/notepad-plus-plus#3311]
### Description of the Issue

Ctrl+C copies nothing when no text is selected - proposing feature to copy entire line when no text is selected

### Steps to Reproduce the Issue

1. Unselect any text
2. Ctrl+C
3. Ctrl+V (pastes last copied text)

### Expected Behavior

Proposing to copy entire line when no text is selected

### Actual Behavior

Ctrl+C copies nothing when no text is selected (may be due to Scintilla)

**Comment by alankilborn** [comment]
There's a plugin with this functionality:

![image](https://user-images.githubusercontent.com/77065706/182619196-a8075a71-7830-4e4f-815c-6d28b8ded907.png)

**Comment by notdodgeball** [comment]
This has been fixed, see #14296.

**Comment by NewEagleRaptor** [comment]
Fantastic, now it overwrites the paste content if I accidentally CTRL-C when I'm trying to paste. :(

**Comment by alankilborn** [comment]
@NewEagleRaptor From v8.6.5:

![image](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/77065706/80332c5b-b6ab-468a-b1dc-3e76ff362ff8)

It seems your choice is clear.

**Comment by NewEagleRaptor** [comment]
@alankilborn Thanks!
