### ISSUE TITLE
Installation of Plugin Manager failed.

### ISSUE THREAD

**Issue by rsubasic** [notepad-plus-plus/notepad-plus-plus#3313]
### When Updating PluginManager I get "Installation of Plugin Manager failed."

I am on Windows 10 Home, and version 7.4.1 32 bit of npp, and have uninstalled and reinstalled.  When I show PluginManager and click into the "Updates" tab, I show installed version of 1.3.5 and available version 1.4.5.  When I attempt to update this plugin, I get a popup window with a title of "Installation Error" that says, "Installation of Plugin Manager failed."  I have tried manually downloading and copying the newest version of PluginManager.dll, but apparently the one I found (PluginManager_1.3.5_UNI) is not the latest.

Note that I have tried this when running as admin and normal user, and I have tried uninstalling and re-installing.

### Steps to Reproduce the Issue

1.  Download and Install version 7.4.1 32-bit Notepad++ (this is on the morning of 2017-05-24)
2.  Click on Plugins-->Plugin Manager-->Show Plugin Manager
3.  Click on the "Updates" tab
4. Make sure that only "Plugin Manager" is checked, and click "Update"
5. Window pops up saying "downloading", and shortly thereafter another pops up saying "Installation of Plugin Manager failed."

### Expected Behavior

The update to Plugin Manger would succeed with no errors

### Actual Behavior

The update to Plugin Manger failed with "Installation of Plugin Manager failed." error

### Debug Information

Notepad++ v7.4.1   (32-bit)
Build time : May 18 2017 - 02:00:37
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10 (64-bit)
Plugins : DSpellCheck2.dll mimeTools.dll NppConverter.dll NppExport.dll NppFTP.dll NppTextFX.dll PluginManager.dll Tidy2.dll 

![image](https://cloud.githubusercontent.com/assets/3441042/26407371/ec376684-4068-11e7-8454-eb1180777582.png)

**Comment by dail8859** [comment]
As of Notepad++ v7.5 the Plugin Manager is no long being shipped with Notepad++. See https://notepad-plus-plus.org/news/notepad-7.5-released.html

All Plugin Manager related issues should be reported to https://github.com/bruderstein/nppPluginManager/issues
