### ISSUE TITLE
Number of columns box too small.

### ISSUE THREAD

**Issue by asr1** [notepad-plus-plus/notepad-plus-plus#3319]
### The number of columns window is too small to be usable.
Settings->Preferences->Editing-> (check "Show vertical edge")->Number of columns. The window is tiny.

![image](https://cloud.githubusercontent.com/assets/7102747/26481971/17974b18-41aa-11e7-9b0d-bb08d44e85e1.png)

You can change the text and hit enter, but if the height of the window were doubled, it would be a lot easier to use.

**Comment by ArkadiuszMichalski** [comment]
@sasumner This can be close, now setting column(s) looks different.

**Comment by sasumner** [comment]
@ArkadiuszMichalski I think it is strangely different depending upon the Windows version, but it is old so I'll close.

**Comment by ArkadiuszMichalski** [comment]
I mean now we have multiline box for this:

![a](https://user-images.githubusercontent.com/2730894/94064244-ab37f580-fde9-11ea-8924-067c8e525fc4.gif)

**Comment by sasumner** [comment]
Ah, yea.  True, true...
