### ISSUE TITLE
Cross Platform

### ISSUE THREAD

**Issue by hasibrm** [notepad-plus-plus/notepad-plus-plus#332]
Can we get enough people interested in making Notepad++ a cross platform tool? It is well understood that notepad++ was built with windows in mind and to re-compiling and re-coding to fit to linux and mac is a lot of work, but with the community support that Notepad++ has, I think it is doable. It will be extremely useful to have one tool and one familiar environment to work it when one switches operating systems.

**Comment by EvilDaveCanada** [comment]
I'm not a programmer but a notepad app that would work on Windows, Linux/BSD AND Android would be a very useful app indeed

**Comment by milipili** [comment]
We're thinking about it. But some work must be done before that.

**Comment by Zarggg** [comment]
Until such time, [SciTE](http://www.scintilla.org/SciTE.html) is already a Scintilla-based editor for Linux.

**Comment by Rikk** [comment]
Isn't Np++ built around Scintilla?
> Scintilla and SciTE are currently available for Intel Win32, OS X, and Linux compatible operating systems with GTK+. They have been run on Windows XP, Windows 7, OS X 10.6+, and on Ubuntu 10.10 with GTK+ 2.20

**Comment by milipili** [comment]
Scintilla is only one part of the project.

**Comment by ariccio** [comment]
It's too early to think about making `Notepad++` cross platform! `Notepad++` has major issues properly complying with the Windows API alone, There is massive technical debt that we need to pay off first!

Honestly, I think that running `Notepad++` under `WINE` is going to be far more robust & reliable for the foreseeable future.

In the mean time, see:

- ["SciTE: The Notepad++ for Linux"](http://itsfoss.com/scite-the-notepad-for-linux/)
- ["ScintillaEditorFamily"](http://texteditors.org/cgi-bin/wiki.pl?ScintillaEditorFamily)

**Comment by milipili** [comment]
Only complaining as always :)

**Comment by hasibrm** [comment]
The idea that it is too early to make NPP a cross platform tool because it has bugs is without merit. If anything, working on making the tool cross platform will help bring to surface a variety of problems and thus solutions to those problems making de-bugging much faster (3 times faster to be exact). It is not too early. It is just the right time. If we wait, NPP will become more and more complex which will make it harder to make it cross platform.

The big question is can we generate enough interest (I think we can) to bring dedicated people to start the process while at the same time having a team to maintain the current version and deploy updates.

**Comment by sanastasiou** [comment]
I'll have to agree with @ariccio  and another guy whose name I have forgotten :) who said that we'll need to split the functionality into smaller *testable* module. If we were to abstract those modules then with regards to specific OS APIs then our life would of course be simpler. But I think as it stands it would be counter productive to start porting anything to another platform.

**Comment by dail8859** [comment]
`<rant>`

> It's too early to think about making Notepad++ cross platform! Notepad++ has major issues properly complying with the Windows API alone, There is massive technical debt that we need to pay off first!

Honestly, N++ is one of the most stable programs I've used. Yes it has its occasional minor bug here and there, but what software doesn't. The majority of the bugs are simple logical errors...and I'm sure a few can be blamed on improper use of the API. If there were "major issues" then it would be much more unstable and problematic.

I'd suggest since there are "major issues", then file bug reports! Not just "this doesn't comply with xyz", but bugs the user will encounter. Since you are aware that something doesn't comply, then create reproducible steps to *make it fail*. 

`</rant>`

**Comment by ariccio** [comment]
> Only complaining as always :)

Well, you're not wrong :)

> If anything, working on making the tool cross platform will help bring to surface a variety of problems and thus solutions to those problems making de-bugging much faster (3 times faster to be exact)

@hasibrm - where did the "3 times faster" come from? Especially with such exactness?


> Honestly, N++ is one of the most stable programs I've used.

Well yeah, if you *catch* all the Access Violations, then the program won't crash in predictable, consistent, or obvious ways.

> The majority of the bugs are simple logical errors...and I'm sure a few can be blamed on improper use of the API.

The documentation for `lstrcpy`, `lstrcpyn`, `lstrcat`, `wsprintf`, all share "**Warning** Do not use" as the first line in their documentation. There *are* perfectly safe alternatives, usually drop-in replacements, but nonetheless, Notepad++ uses them ~65 times. I guess you could say that that's "improper use of the API".

> I'd suggest since there are "major issues", then file bug reports! Not just "this doesn't comply with xyz", but bugs the user will encounter. Since you are aware that something doesn't comply, then create reproducible steps to make it fail. 

@dail8859 Who is that directed at?

**Comment by hasibrm** [comment]
@ariccio there are 3 major platforms, windows, Linux and Mac OS. There would be three teams working on the project each team dedicated to one platform. Three people would be working on the same sets of problems through out and would effectively debug code nuances three times faster and three times more accurately. That's where the number 3 comes from.

**Comment by ariccio** [comment]
So, debugging speed is the reciprocal of the number of platforms involved?

I'm sold, let's support OS/2, Solaris, & AmigaOS!

----------

More seriously, what would *dis*prove your hypothesis?

**Comment by Croydon** [comment]
Not sure if this is helpful, but I just found https://github.com/notepadqq/notepadqq

**Comment by hasibrm** [comment]
@ariccio debugging speed is the reciprocal of the number of teams involved which is derived from the number of platforms involved. I don't care about OS/2, Solaris or AmigaOS. I care about Mac OS and Linux. If you are interested in developing npp for those, feel free to contribute to those.

It seems like you are interested in having an academic discussion for the sake of it rather than actually offering any real solutions. I am not interested in such activities. I am interested in diving into the project right away.

**Comment by milipili** [comment]
Cross-platform is somehow in the roadmap. However it requires a few modifications in the code architecture to allow a real start of the project on other platforms.

**Comment by Croydon** [comment]
Why is this closed and added to a milestone when it's obviously not done?

**Comment by milipili** [comment]
There is no need to keep this issue opened since it is a global task and it will be part of the refactoring. From now on, cross-platform is required in any new code.

**Comment by talregev** [comment]
I am vote 👍  for cross platform Notepad++

**Comment by LinuxFanatic777** [comment]
Dear Notepad++ developers team! Please, just use Winelib and release Notepad++ for Linux officially. Look at TeamViewer application - they started with Winelib and then switched to true-crossplatform. Start with Winelib!

**Comment by Croydon** [comment]
For the case that it helps anyone:

Somebody started Winepak, which bundles Windows applications with Wine packaged as Flatpaks

That is how I'm using Notepad++ on my Linux Fedora and it runs pretty well

https://winepak.org

https://github.com/winepak/applications

But be warned that it is no longer maintained. For my part it is fine to use an older Notepad++ version but that might not be the case for everyone.

This might also be a way how official support could look like.
Once Notepad++ is truly cross-platform you could just remove Wine and deploy the Linux binaries inside the flatpak. People would get the update and a smooth transition.

**Comment by DJCrashdummy** [comment]
i know it's far from finished or even perfect, but IMHO [**Notepad Next**](https://github.com/dail8859/NotepadNext) looks like a good start. :+1:
