### ISSUE TITLE
Rework file update message boxes into dialog

### ISSUE THREAD

**Issue by tobbi** [notepad-plus-plus/notepad-plus-plus#3320]
### Description of the Issue
When you have documents open in Notepad++ and these get changed on the filesystem before the window has focus, you keep getting a message box for each file that asks you whether you want to reload or not. This can get annoying if you have multiple files. 

My proposal is this: Have a dialog that contains all modified files. This dialog contains "reload all", "keep all" etc. buttons.

### Steps to Reproduce the Issue
1. Open multiple files in Notepad++
2. Change them with an external program (Notepad++ must not have window focus, I assume).
3. Give Notepad++ window focus.

### Expected Behavior
One dialog for all file changes

### Actual Behavior
One dialog for each file change -> Annoying.

**Comment by Duellmann** [comment]
This is one of the most remarkable annoying issues of Notepad++.
Worse, even for the same file you can get multiple prompts: issue 3349.
A fix would be much appreciated.

It's also very error-prone:
- The screen coordinates of the Yes button change according to file name length. Fast-clicking in the same spot user can easily end up clicking NO unintendedly for some of multiple alerted files.
- Same for repetitively pressing Enter to confirm the alerts: Your last Enter key presses can easily end up at a random position in a random document and unintendedly change content there.

**Comment by donho** [comment]
https://github.com/notepad-plus-plus/notepad-plus-plus/commit/ba60fbdd715d647aa5ce7be5b6b75182b4a52951
