### ISSUE TITLE
New tab(open file/New File) to start as being located next to active tab

### ISSUE THREAD

**Issue by DTHP** [notepad-plus-plus/notepad-plus-plus#3323]
Windows 10 Pro.

This is pretty straight forward request. I did search but couldn't find a similar request.

When you have a lot of tabs open and you want to open a new file you can pick a current opened file tab and when you select open, it opens a open file window in the same directory as where the active file is stored.

But then when you open some other file the new tab is being moved to the end of all current opened tabs instead of being next to the previously active tab. The same thing happens when you want to make a new file.

Could it not be made so that a new file-tab is being positioned right next to the now previously active tab.

Thanks for the great work.

**Comment by AngryGamer** [comment]
Dupe [#804](https://github.com/notepad-plus-plus/notepad-plus-plus/issues/804)

**Comment by ArkadiuszMichalski** [comment]
There was PR for this https://github.com/notepad-plus-plus/notepad-plus-plus/pull/3487, but reject.

**Comment by sasumner** [comment]
So we reject the whole idea.
