### ISSUE TITLE
No Autoscroll while drag-and-drop text editing

### ISSUE THREAD

**Issue by maattrix** [notepad-plus-plus/notepad-plus-plus#3325]
### Description of the Issue

When text is dragged outside visible window, the window should auto-scroll
### Steps to Reproduce the Issue

1. Open file which is larger than program window
2. Select text
3. Drag beyond window border

### Expected Behavior

Window should auto-scroll
### Actual Behavior

Mouse pointer changes to unavailable

**Comment by donho** [comment]
It's been fixed since long time ago by upgrading Scintilla component.
