### ISSUE TITLE
Red line highlighting 

### ISSUE THREAD

**Issue by JiminSA** [notepad-plus-plus/notepad-plus-plus#3326]
Once upon a time ...
... we used to be able to highlight the beginning and end of a clause action, by placing the cursor on the opening { character. Notepad++ would then insert a vertical red line which linked with the closing } character. I found this most useful, but recent versions no longer do it. Any chance of getting it back?

**Comment by SinghRajenM** [comment]
please check if it is disabled in setting by chance.
Setting -> Preferences -> Editing ->Folder Margin style. (It should not be marked none.)

If it is not disabled. Are you using any theme for notepad++? Also please share debug info (? ->Debug Info).

**Comment by JiminSA** [comment]
Thanks for your response @SinghRajenM
It was set to BoxTree. The connecting red line is active, but only in the BoxTree column - it used to align on the column where the cursor is positioned.
How would I find the debug info you asked me to share?

**Comment by JiminSA** [comment]
Incidently, I never adjust settings or themes, I just leave as per installation ...

**Comment by SinghRajenM** [comment]
> How would I find the debug info you asked me to share?

Mene -> ? -> Debug info

It is working fine for me. I'm using V7.4.1.

![image](https://cloud.githubusercontent.com/assets/14791461/26530660/bfda2086-43f6-11e7-9f7e-5fd1fe32b48a.png)

**Comment by JiminSA** [comment]
"Mene -> ? -> Debug info" ...
I can't find Mene!
"It is working fine for me. I'm using V7.4.1." ..
I am using a very recent auto updated version (must be the same).
Yes, it is fine for a none-indented section, but if you place the cursor on  the { character in (e.g.) line 557 the content red line does not indent, but remains leftmost - it used to indent.

**Comment by SinghRajenM** [comment]
> I can't find Mene!

sorry, it was typo, It is menu. You can see last menu is "?" and inside this "Debug info" exist.

> but if you place the cursor on the { character in (e.g.) line 557 the content red line does not indent, but remains leftmost - it used to indent.

I've seen the indented line. May be it was in older version which I didn't use. But it give clear instruction same can been seen in below screenshot.
![image](https://cloud.githubusercontent.com/assets/14791461/26567935/09cfbde6-451d-11e7-98ca-df95b48e2a73.png)

**Comment by JiminSA** [comment]
Aha ...Notepad++ v7.4.1   (32-bit)
Build time : May 18 2017 - 02:00:37
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 7 (32-bit)
Plugins : mimeTools.dll NppConverter.dll NppExport.dll NppFTP.dll PluginManager.dll 
Regarding my original question, yes it was an older version which indented the red line highlight, as well as highlighting the  { and } characters. I was wanting to draw this fact to the Developers' attention, in the hope that the aid could be re-introduced. Is there a more direct method of doing this?

**Comment by JiminSA** [comment]
When you have a condition action which extends over many lines of code, I found it most usfeul for trackingthe code ...

**Comment by josmanaba** [comment]
Same happened to me, I lost my hard drive, after reinstalling everything in a new one this red vertical line was gone. I am desperately seeking (not Susan!) how to get it back.

**Comment by josmanaba** [comment]
That red line you are talking about is activated through View -> Show Symbol -> Show indent guide. This option also displays other vertical gray lines, but the important thing is, you will get the red line between the braces, the one that moves when the braces move.

**Comment by josmanaba** [comment]
That red line you are talking about is activated through View -> Show Symbol -> Show indent guide. This option also displays other vertical gray lines, but the important thing is, you will get the red line between the braces, the one that moves when the braces move.

**Comment by sasumner** [comment]
>That red line you are talking about is activated through View -> Show Symbol -> Show indent guide.

I think the "red line" that is being discussed is the one in the "fold margin", which isn't controlled by the "indent guide" setting.
