### ISSUE TITLE
Request for option to disable autocomplete in comments

### ISSUE THREAD

**Issue by harrysarson** [notepad-plus-plus/notepad-plus-plus#3327]
This is a feature request rather than an issue - apologies if I am posting in the wrong place.

I think it could be a useful option to disable autocomplete in comments as when typing normal text in comments and inline documentation notepad++ suggests function/word completion which can be annoying.

I don't know how this feature works under the hood but as it is already the case that bracket completion is disabled in comments I am wondering if it would be possible to extend this to autocompletion.

Many thanks :)

Related SO question: 
https://stackoverflow.com/questions/26303741/notepad-disable-auto-complete-in-comments

**Comment by donho** [comment]
It's nice to have feature. However, the detection of the cursor position in comment zone is hard for over 80 supported language. This feature won't be implemented.

**Comment by basketshoe** [comment]
Isn't it possible to implement it like you implement the color of the commented text? Something like: the text is green ==> you are in a comment ==> disable auto completion?
