### ISSUE TITLE
Are there any plans to support the goalng language highlighting?

### ISSUE THREAD

**Issue by chuyangyang** [notepad-plus-plus/notepad-plus-plus#3330]
<h1>Are there any plans to support the goalng language highlighting?

**Comment by redmanmale** [comment]
@chuyangyang 
Highlighting support for all languages are provided by Scintilla.
And since Scintilla devs [refuse to implement it](https://sourceforge.net/p/scintilla/feature-requests/750) the only way is to write your own custom language definition and submit it.

**Comment by ArkadiuszMichalski** [comment]
@donho @sasumner Duplicate of https://github.com/notepad-plus-plus/notepad-plus-plus/issues/8090, maybe close this because of the short description and leaving only the newer one.

**Comment by sasumner** [comment]
Closing by suggestion
