### ISSUE TITLE
The ` Character in JavaScript

### ISSUE THREAD

**Issue by BionicRabbit3** [notepad-plus-plus/notepad-plus-plus#3331]
### Description of the Issue
There's a new feature in JavaScript (already available in the normal Google Chrome (non dev build or whatever)), the ` character.
You use it to write strings with some special features.
A problem in NP++ is that any line you edit inside this string it turned completely invisible,
it presumably changes the text color to the same one as the background color.

### Screenshot
[Link](http://i4.imgbus.com/doimg/3com7monf2191d2.png)

**Comment by BionicRabbit3** [comment]
Also, the coloring of the text should probably match the one of the normal " and ' strings, since it is a string after all.
But I guess that doesn't matter as much.

**Comment by donho** [comment]
https://github.com/notepad-plus-plus/notepad-plus-plus/issues/3822#issuecomment-697275450
