### ISSUE TITLE
Bug: Crash on Ctrl+Tab and Ctrl+Shift+Tab

### ISSUE THREAD

**Issue by alarimer** [notepad-plus-plus/notepad-plus-plus#3335]
### Description of the Issue
Issue appeared after updating to 7.4.1 (32 bit) on Windows 7 (64 bit).  Pressing Ctrl+Tab and Ctrl+Shift+Tab crashes the application.  Ctrl+Tab does not add an entry in the Event Log; Ctrl+Shift+Tab does add an entry to the Event Log.

Verified settings in Shortcut Mapper (162 & 163).  Ctrl+PageUp and Ctrl+PageDown work without issue.

Attempted rename of C:\Program Files (x86)\Notepad++\plugins directory.  No change.
Attempted running As Administrator.  No change.
**"C:\Program Files (x86)\Notepad++\notepad++.exe" -noPlugin** from command prompt.  No change.
Updated Plugin Manager.  Ctrl+Shift+Tab no longer generates Event Log entry; no other changes.

### Steps to Reproduce the Issue
1.  Open Notepad++ 
2.  Open two existing files.
3.  Press Ctrl+Tab or Ctrl+Shift+Tab to change the active window/tab/file.

### Expected Behavior
The active window/tab/file should change.

### Actual Behavior
Application crashes.

### Debug Information
Notepad++ v7.4.1   (32-bit)
Build time : May 18 2017 - 02:00:37
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 7 (64-bit)
Plugins : mimeTools.dll NppConverter.dll NppExport.dll PluginManager.dll 

```xml
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
<System>
  <Provider Name="Application Error" /> 
  <EventID Qualifiers="0">1000</EventID> 
  <Level>2</Level> 
  <Task>100</Task> 
  <Keywords>0x80000000000000</Keywords> 
  <TimeCreated SystemTime="2017-06-01T00:30:24.000000000Z" /> 
  <EventRecordID>22004</EventRecordID> 
  <Channel>Application</Channel> 
  <Computer>REMOVED</Computer> 
  <Security /> 
  </System>
<EventData>
  <Data>notepad++.exe</Data> 
  <Data>7.4.1.0</Data> 
  <Data>591ce479</Data> 
  <Data>PluginManager.dll</Data> 
  <Data>1.3.5.0</Data> 
  <Data>54bbbb11</Data> 
  <Data>40000015</Data> 
  <Data>00013fb8</Data> 
  <Data>8c4</Data> 
  <Data>01d2da6ab5908d18</Data> 
  <Data>C:\Program Files (x86)\Notepad++\notepad++.exe</Data> 
  <Data>C:\Program Files (x86)\Notepad++\plugins\PluginManager.dll</Data> 
  <Data>80679525-4661-11e7-830c-80000bb15ac5</Data> 
  </EventData>
  </Event>
```

**Comment by alarimer** [comment]
Will uninstall and reinstall no later than this weekend because this issue is killing productivity.

**Comment by AngryGamer** [comment]
I can't replicate this crash.

**Comment by alarimer** [comment]
It is now working.  Not sure what changed.  :-/
