### ISSUE TITLE
Duplicate menu shortcut for Save All and Close All

### ISSUE THREAD

**Issue by steronydh** [notepad-plus-plus/notepad-plus-plus#3336]
Using the menu with the keyboard, Save All and Close All both have E as their shortcut ("Sav&e All" and "Close&e All").

Suggest changing the "Reload from Disk" shortcut from L to R, and changing the "Save All" shortcut from E to L.

Version 7.4.1

**Comment by tarung65** [comment]
Fixed review my pull request #3484

**Comment by steronydh** [comment]
Version 7.5.3 64-bit still has this problem.

**Comment by dail8859** [comment]
@steronydh Which is why this issue is still open.

**Comment by steronydh** [comment]
@dail8859 The referenced PR was closed so I thought it would be fixed.

**Comment by MAPJe71** [comment]
@steronydh Read #3484 again, it was not merged and not closed by @donho.

**Comment by steronydh** [comment]
My mistake!

**Comment by steronydh** [comment]
Bump!

v7.5.6

**Comment by steronydh** [comment]
Happy birthday... ;)

**Comment by jamesjohnmcguire** [comment]
FYI: Visual Studio uses L
