### ISSUE TITLE
Notepad++ elevated save privileges

### ISSUE THREAD

**Issue by ariccio** [notepad-plus-plus/notepad-plus-plus#334]
As of commit 4cca41267e4d4fb0e2c6cc2ceb6187febc948f0a, on failure of `saveBuffer`, `Notepad++` [relaunches with elevated permissions](https://github.com/notepad-plus-plus/notepad-plus-plus/blob/4cca41267e4d4fb0e2c6cc2ceb6187febc948f0a/PowerEditor/src/NppIO.cpp#L384).

There are a number of issues with this:
1. `Notepad++` handles untrusted data _as part of its core functionality_, thus it has a massive attack surface, and by [running with elevated permissions](https://cwe.mitre.org/data/definitions/250.html), an attacker has an [easy route to `SYSTEM`-level pwnage](https://www.nowsecure.com/blog/2015/06/16/remote-code-execution-as-system-user-on-samsung-phones/). [That's bad](http://askubuntu.com/questions/16178/why-is-it-bad-to-login-as-root), and not debatably so.
   - `Notepad++` already has major security problems, and this defeats (one of) the last remaining security barriers for users!
2. For [the same reasons as number one, Running as an elavated process breaks drag & drop](http://blogs.msdn.com/b/patricka/archive/2010/01/28/q-why-doesn-t-drag-and-drop-work-when-my-application-is-running-elevated-a-mandatory-integrity-control-and-uipi.aspx). 
   - Sure, [we can bypass this security mechanism](https://helgeklein.com/blog/2010/03/how-to-enable-drag-and-drop-for-an-elevated-mfc-application-on-vistawindows-7/), but **_please, PLEASE, don't do this**_. I'm serious. 
     - Given how useful `Notepad++` is for developers & sysadmins, we really don't want to [make CNE easier](https://firstlook.org/theintercept/2014/03/20/inside-nsa-secret-efforts-hunt-hack-system-administrators/).

If you agree, please acknowledge your interest.

See discussion [here](https://github.com/notepad-plus-plus/notepad-plus-plus/commit/4cca41267e4d4fb0e2c6cc2ceb6187febc948f0a#commitcomment-11547636).

@jonandr 
@cmeriaux
@milipili 

Related issues:
#159

Sidenote:

_There are a lot of new levels of indentation in that commit!_

**Comment by Ede123** [comment]
I'm wondering why nobody mentioned the already existing plugin so far?
=> **[nppSaveAsAdmin](http://sourceforge.net/projects/nppsaveasadmin/)**

It works like a charm (to be honest much better than what was now implemented natively) and uses the approach to launch a small embedded executable with elevated rights.

Maybe this approach could be transferred to the core? If an additional executable seems inappropriate maybe the needed functionality can be built into Notepad++ via command line arguments or the like, so that an additional elevated instance of notepad (without GUI) can be launched temporarily to save the file.

**Comment by milipili** [comment]
Using an external program is kinda the same than initially proposed by @jonandr. But I like the idea of embedding it. On the other hand, I am not sure about antivirus/IDS tools concerning an executable with elevated permissions from nowhere (most probably from the temp folder).
My initial thoughts was using a special command line argument indeed (but without loading the universe). @jonandr had some concerns about security issue, even if I do not really see which one exactly, but I may miss something.

**Comment by jonandr** [comment]
@milipili It's just the [principle of least privilege](https://en.wikipedia.org/wiki/Principle_of_least_privilege). The N++ source is on the order of 4000 times bigger than the nppcopy program (122 000 lines vs 31 lines; counted using the naive method). If you accept that

* it's easier to reason about 31 lines of code than 122 000 lines, and
* you want as little code as possible running under administrator mode

then surely the choice is clear...?

Each of those 122 000 lines can potentially be executed when N++ is run, and each contains a potential bug. That bug's impact is potentially much greater when running as admin. I get that you propose to add special checks as soon as is possible in WinMain() when running under this new mode, but just how sure are you that the command-line parser (which, literally, does pointer arithmetic) is bug-free?

**Comment by ariccio** [comment]
I really like the threat modeling that  @jonandr is doing

**Comment by milipili** [comment]
Self elevation (with specific flags in some cases) is a common pattern even for MS programs. It is even part of their samples (https://code.msdn.microsoft.com/CppUACSelfElevation-5bfc52dd)

Security issue is not the same thing as bug. If the command-line parser is buggy, it is likely that the feature will just not work and it would be quite visible. Anyway a complete implementation would require more than that. It requires both read and write capabilities (and monitoring about external file modifications). So in both cases the process will be able to do some nasty things.

Actually I am not against this method. The COM Elevation Moniker is not suitable for me anyway. So as long as the programs are signed (we want code signing) and easily identifiable by the user, I don't really care if they are two separate program files or not.

BTW, how other editors do ?

**Comment by ariccio** [comment]
> Self elevation (with specific flags in some cases) is a common pattern even for MS programs. It is even part of their samples (https://code.msdn.microsoft.com/CppUACSelfElevation-5bfc52dd)

Just because it's common, or even exemplified doesn't mean that it's a ***good*** idea!

> Security issue is not the same thing as bug.

A bug is not necessarily a security issue, but a security issue **is** necessarily a bug! 

> If the command-line parser is buggy, it is likely that the feature will just not work and it would be quite visible. 

It's also very likely that it will [*work correctly most of the time*, but still have massive security bugs](https://en.wikipedia.org/wiki/Shellshock_(software_bug)).

> Anyway a complete implementation would require more than that. It requires both read and write capabilities (and monitoring about external file modifications).

I think you might have misunderstood? A program that does nothing other than parse `argc` arguments from `argv` is a pretty silly program! @jonandr is talking about memory safety issues, which are always a problem in a native language like `C`/`C++`, but most obvious when dealing with pointer arithmetic & friends.

**Comment by milipili** [comment]
Do not worry @ariccio, I perfectly understand. Please stop with all your "massive" or equivalent words and your links associated to it like that. I don't know if you're taking use for idiots but this way of writing becomes *really* irritating.
When we speak about bugs, it means problems for the user (aka crash). Of course a security issue is something to fix. We can call them security bugs if you want to make a proper distinction. But talking about pointer arithmetic issues in a command line parser is the least of the problems here (that do not mean to not take into consideration that a problem may arise, to the contrary).

That said, back to business, let's go deeper with this method and how it should work. I will assume that n++ is not able to read/write/access/whatever to a given file.
With the proposed architecture (aka a second process), it seems obvious how to read the content and how to modify it. However we should answer to the following questions:

 - Applying the changes in copying an intermediate file itself does not really please me. Generating intermediate IO access can be seen as a waste (with anti-virus working behind the scene and especially for medium/large files on network shares) but my primary and probably only concern is to ensure that the original metadata and/or ACL, especially on a Windows Server, are preserved. I would probably prefer that this subprocess handles the changes directly
 - What is the lifespan of the sub process : re-exec it for each action (thus always asking a confirmation from the user) or keep it opened for a while with an idle timeout ? (like sudo, and what should be the value of the timeout : 15 min like sudo ?)
 - How do we handle external changes ? The subprocess (if always alive) may handle it. Or should we detect it only before writing it and ask for a confirmation ?

**Comment by milipili** [comment]
And again it would be nice to have a comparison with other tools

**Comment by dg9ngf** [comment]
Unfortunately that plugin doesn't work for me. I still get that desktop message.

Is the elevation feature already available in a stable build? I see that version label assigned to it but don't get that behaviour in my installation. It still asks to save on the desktop.

I haven't seen any editors that support UAC in this natural way. All of them either ask for a different location to save, or bail out with an access denied message. I have some experience with file managers (Windows Explorer, Speed Commander) that support UAC. While Windows Explorer would ask for every single copied file (with the option to remember for all remaining files of the current batch), Speed Commander seems to have some timeout when it won't ask anymore. From what I've observed about Speed Commander, I believe it uses some COM activation thing, but I don't understand how these work. [My closest work in this regard](http://unclassified.software/apps/uacconsole) was using .NET WCF for that task, with a separate executable. (IIRC the separate executable was necessary for some reason.)

As you're talking about security concerns, I'm wondering how it can be ensured that the elevated process really does what it's supposed to do. If you're telling it the path through command line arguments, then how will the user know that these arguments haven't been tampered with? Sure the user can expand that UAC dialog window, but it's of limited size. The elevated process might display a confirmation message on the path. But then, what about the content itself?... Anyway, the path and content is ultimately defined by the non-elevated GUI part of the application, and that could always be manipulated. So this risk might not be possible to mitigate.

Do you think of supporting restricted read access files as well, or just restricted write access? If the non-elevated process can read and monitor the file, only the actual writing needs to be handled. The elevated process wouldn't necessarily need to be kept after it's done its job. Though it would be easier for the user if it were alive for as long as any affected document is still open. You need some IPC channel anyway to send the content to the elevated process. Not sure what C++ has to offer here.

Maybe it's better to concentrate on this write-only aspect first as it happens often when modifying system config files. Those files are mostly write-protected but publicly readable (think of that etc/hosts file).

**Comment by ariccio** [comment]
> I'm wondering how it can be ensured that the elevated process really does what it's supposed to do. 

Well, that's always the question with security ;) You might want to check out the Google Chrome/chromium sandbox & security model - it's phenomenal, and confronts all of the same problems.

> If you're telling it the path through command line arguments, then how will the user know that these arguments haven't been tampered with? 

Tell what about the path? How'd the user get involved in parsing command line arguments? This is the right kind of mindset for threat modeling, but specificity is necessary.

> Sure the user can expand that UAC dialog window, but it's of limited size.

Why does the UAC dialog's size matter?

> Anyway, the path and content is ultimately defined by the non-elevated GUI part of the application, and that could always be manipulated.

Eh? It's defined? Again, threat modeling, specifics. You might have the idea upside-down. I'll elaborate in a second comment.


> Do you think of supporting restricted read access files as well, or just restricted write access? If the non-elevated process can read and monitor the file, only the actual writing needs to be handled. 

Eh? There's no such thing as write-only access, like there's no such thing as write-only memory?

Giving non-privileged processes read access to privileged information is a different kind of vulnerability, albeit an arguably less severe one (information disclosure/information leak), and is a bad idea. Imagine leaking `/etc/passwd`. Sure it's hashed, but now the hashes have been leaked.

*Side note: If you need to edit a root-owned file on Linux, (here, gnome) use `gksudo`, not `sudo`. There's a lot of magic going on behind the scenes (in the X window system) to make the UNIX security model work with a GUI.*


> You need some IPC channel anyway to send the content to the elevated process. Not sure what C++ has to offer here.

Well, I'm certain that any IPC implementation (in any language other than assembly) is `C`/`C++` *at the bottom*. It wont be easy, but c'mon, this is `C++`. Most things are hard in `C++`. 

> Maybe it's better to concentrate on this write-only aspect first as it happens often when modifying system config files. 

Comments upcoming.

**Comment by dg9ngf** [comment]
> Why does the UAC dialog's size matter?

Because it can only display so much of the command line arguments which include the path to write to. This is probably the only place where the user could reliably verify the elevated action.

But as I think I already concluded, as long as things are controlled from a non-elevated process, nothing can be guaranteed. So the elevated process might as well be dumb and just do the work, a simple helper process. If you don't trust your computer _and_ your user session, you should probably not be an administrator. Problem solved (sufficiently for now). If you don't agree to this level of security, don't use that feature and start the whole GUI as admin instead. With all its improved security and its usability disadvantages. Most people can live with it.

> Eh? It's defined? Again, threat modeling, specifics.

Eh? Please specify your question.

> There's no such thing as write-only access

Because you made it up. I never said that. I said "restricted write access", short "write-protected" which my dictionary says means "protected against writing (but free to read)".

I don't know how gksudo is implemented so I can't say anything about that. I'm not a regular with Linux desktops, I'm only working in the shell over there.

**Comment by MetaChuh** [comment]
closed due to inactivity (4y)
