### ISSUE TITLE
New "Save" dialog style should default to "*.txt" not to "*.*"

### ISSUE THREAD

**Issue by trejder** [notepad-plus-plus/notepad-plus-plus#3341]
### Description of the Issue

When _Settings > Preferences > Default Directory > Use new style save dialog (without file extension feature)_ option is **disabled**, every time a new document is saved, the `*.txt`  (Text Files) option / file type is selected as default. User must only enter filename and hit enter to save new document under `*.txt` extension.

When _Settings > Preferences > Default Directory > Use new style save dialog (without file extension feature)_ option is **enabled**, every time a new document is saved, the `*.*` (All Files) option / filetype is selected as default. User must manually enter extension as well, each time saving new document or must always manually select correct extension before saving file.

### Arguments

This is wrong, because:

1. Notepad++ is a **text** editor at first and thus _Text Files_ file type should be default in both "Save" dialog styles.
2. Both "old" and "new" save dialogs should be equal in functionality and should require user to perform the same steps to achieve the same results.
3. This is confusing. Forgetting to select (or manually write) extension in case of "new" save dialog style causes Notepadd++ to save file without extension (by default).

There aren't many situations in which users would like to have file without extension so currently Notepad++ defaults / supports by default solution used by a very limited group of users.

### Proposed solution / feature request

In the best case scenario this would be configurable -- i.e. a possibility to select (in _Settings > Preferences > Default Directory_) default file extension for saving. This would suit the biggest group of users.

But, since most likely this causes to much effort, at least unify that both styles of "Save" dialog defaults to  `*.txt`  (Text Files) option / file type.

**Comment by jacktose** [comment]
I suspect that's what (without file extension feature) means (though I can't find any documentation), and I infer that the reason the option is there is because for some reason N++ can't set a default file type in the new style dialog.
If it can, I'm in strong support of this issue.

My take is corroborated by #2884, in which people say to deselect that box to enable default extensions.
A possible workaround is [here](https://superuser.com/questions/546315/default-save-extension-in-notepad), but I suspect that may assume the box is deselected first.

**Comment by trejder** [comment]
> A possible workaround is [here](https://superuser.com/questions/546315/default-save-extension-in-notepad), but I suspect that may assume the box is deselected first.

This isn't a workaround for me, because I have a "Normal Text" set as default language and according to this answer and to Notepad++ configuration it should already save files in .txt format.

You may be correct with the suggestion that Notepad++ is unable to set default file extension in the "new" dialogs' style.

The true workaround that works for me is to remember to hit following keyboard combination:

- <kbd>Tab</kbd>,
- <kbd>Arrow down</kbd> (twice),
- <kbd>Enter</kbd> (twice),

after entering a filename in the "new" style "Save" or "Save as" dialog. This will save the file under the name that I have provided and will "magically" change "All types" to "Text files" prior to saving.

Other, most likely faster solution is to learn oneself to always type `.txt` after providing filename and prior to hitting <kbd>Enter</kbd>.

**Comment by taptapper** [comment]
I agree with this issue.  Files defaulting to no extension has had me going nuts.  Setting default language to normal text has no effect.  This "feature" has negated an existing feature so I call it a bug.

**Comment by adwokatpawlak-lodz** [comment]
I agree, if you press ctr+s it should add automatically ".txt"

now every person changes this default when starts using notepad++ behaviour regardless of utilities

**Comment by MDagni** [comment]
This issue was created 2 years ago and nothing has changed since then. It's ridiculous to not have a default extension when saving a new file. If the language is selected as XML, extension should be xml. If no language is selected, txt should be default. It's just simple.

I don't think that setting a default extension is not possible when using the new style save dialog. Every other program can do this, so why not Notepad++?

**Comment by sasumner** [comment]
@MDagni said:

>It's just simple

Well, since you opened it up to something other than `.txt` (by mentioning XML), how would you propose handling languages that have many possible extensions, the best example maybe being C or C++, with `.c`, `.h` and `.cpp`, `.hpp`, `.cxx` ...

**Comment by MDagni** [comment]
It already gives a default extension if you use the old style save as dialog. Probably using the first extension in the language definition? Right or wrong, it's better than nothing.

**Comment by sasumner** [comment]
>Probably using the first extension in the language definition

I suppose that's fair.

(Nobody cares but) my whole "solution" to the issue is just type the desired extension and move on with my life. :-)

**Comment by sasumner** [comment]
Notepad++ 7.8.7 has released new functionality in this area.
Let's close this old issue while the new functionality is being evaluated by users.
If need be, a new issue can be opened.
