### ISSUE TITLE
File path to Clipboard no working while monitoring (tail -f) is on

### ISSUE THREAD

**Issue by kehtabp** [notepad-plus-plus/notepad-plus-plus#3344]
### Description
File path to Clipboard function is copying an empty string to clipboard instead of the expected filename/path/dir path

### Steps to Reproduce the Issue

1. Open file
2. Enable monitoring (View - Monitoring (tail -f))
3. Try any of the three options to copy file name full path or dir path (Edit -> Copy to clipboard -> any of the three)

### Expected Behavior
File path/dir path/filename is copied to clipboard

### Actual Behavior
Empty string is copied to clipboard

### Debug Information

Notepad++ v7.4.1   (32-bit)
Build time : May 18 2017 - 02:00:37
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 7 (64-bit)
Plugins : mimeTools.dll NppConverter.dll NppExport.dll NppFTP.dll PluginManager.dll

**Comment by donho** [comment]
Tested under v7.8.5, cannot be reproduced.
