### ISSUE TITLE
Close All Saved

### ISSUE THREAD

**Issue by Eldaw** [notepad-plus-plus/notepad-plus-plus#335]
When right-clicking a tab, it would be useful to have a command 'Close All Saved'.

**Comment by drakosvlad** [comment]
Pull request with this feature was sent

**Comment by VVelda** [comment]
And what about Close All? (For situation, when you open Notepad++ and previous session isn't important)

**Comment by MetaChuh** [comment]
closed as duplicate of rejected https://github.com/notepad-plus-plus/notepad-plus-plus/pull/404 and https://github.com/notepad-plus-plus/notepad-plus-plus/issues/2500
