### ISSUE TITLE
CAN NOT open the "*.lnk" file correctly  

### ISSUE THREAD

**Issue by gitatw** [notepad-plus-plus/notepad-plus-plus#3351]
### Description of the Issue

can not open the "*.lnk" file correctly

### Steps to Reproduce the Issue

1.  drag&drop the "*.lnk" file to the npp

### Expected Behavior

can open the linked file

### Actual Behavior

open the just ITSELF "*.lnk" file
(can open the linked file correctly when File->Open *.lnk file from Menu)

**Comment by wynxel** [comment]
Hello, I am new to Github and I would like to contribute on notepad++. Is this issue free? If so, could somebody help me with this issue? I suppose that I should find DragDrop event handler, check if filename is '.lnk' and if so, resolve path.

**Comment by redmanmale** [comment]
@gitatw 
I think NPP does what it's expected when opening file — it opens this file.
If you want to open file, not link to it — just use your OS, grab linked file and open it.

**Comment by donho** [comment]
It's OS issue due to Windows doesn't allow some types of file dropped in any application.
