### ISSUE TITLE
For [-] button behavior needs change such that the live code is visible in case of #if #else #endif construct.

### ISSUE THREAD

**Issue by puranikgn** [notepad-plus-plus/notepad-plus-plus#3358]
### Description of the Issue

![image](https://cloud.githubusercontent.com/assets/29196110/26778800/6829ac84-4a00-11e7-9344-952df7c337e9.png)
When I press the [-] then entire code starting from the next line of #if 0 is getting folded/invisible.
Instead it has to fold only the #if 0 part and not the code that is alive.
For that another [-] button should be provided at #else also.
Thanks.

**Comment by ArkadiuszMichalski** [comment]
@puranikgn What language did you used?

**Comment by donho** [comment]
It's a normal behaviour to me.
