### ISSUE TITLE
Exportar e Importar lenguaje

### ISSUE THREAD

**Issue by susanacg72** [notepad-plus-plus/notepad-plus-plus#3360]
### Description of the Issue
In Spanish languaje, the bottoms "Exportar" e "Importar" a ser-defined languaje works in inverse open

### Steps to Reproduce the Issue
1.  Lenguaje
2. Define your lenguaje
3. Exportar (works like Importar)
4. Importar (works like Exportar)

### Actual Behavior
3. Exportar (works like Importar)
4. Importar (works like Exportar)

![image 110](https://cloud.githubusercontent.com/assets/29205257/26789878/fec2acca-4a11-11e7-85e2-36b665cd81bf.png)

**Comment by frank-orellana** [comment]
Don't have that issue over here:

![image](https://user-images.githubusercontent.com/2250701/27270136-261a302c-548a-11e7-8b56-86136adb6682.png)

What version are you using? if it is the latest maybe deleting NativeLang in %APPDATA% would help (or maybe just change the language in preferences and then revert to spanish)

**Comment by susanacg72** [comment]
Thank you. i deleted the file and update de versión. Now it os Ok
