### ISSUE TITLE
Ability to "pin" recent files in file menu

### ISSUE THREAD

**Issue by jscarano** [notepad-plus-plus/notepad-plus-plus#3362]
It would be nice to pin recent opened files in the file menu so they would stay there until removed. Or maybe a way to keep a list of favorite files.

**Comment by donho** [comment]
Due to the technical issue (UI part is hard to be done), this feature won't be implemented.

**Comment by alankilborn** [comment]
> Or maybe a way to keep a list of favorite files.

FYI: This can be done with the _Explorer_ plugin.
