### ISSUE TITLE
Error open file

### ISSUE THREAD

**Issue by Alex1720** [notepad-plus-plus/notepad-plus-plus#3364]
File opened as empty. Example file
https://cloud.mail.ru/public/eGby/BzBbFTd6e

**Comment by orenleto** [comment]
It's file excelent opened: 
![image](https://user-images.githubusercontent.com/2300067/26876835-5a6a8b16-4ba1-11e7-8e65-8c4f70db8078.png)

**Comment by dail8859** [comment]
Works fine for me. If you still have problems you need to provide more info because there is nothing to even guess what the problem might be.
