### ISSUE TITLE
notepad++ freezes frequently after upgrade

### ISSUE THREAD

**Issue by swaingyanranjan** [notepad-plus-plus/notepad-plus-plus#3365]
### Description of the Issue

notepad++ freezes frequently after upgrade

### Steps to Reproduce the Issue

1.  Whenever you open a file. Doesnt matter if it is txt file or a log file.
2. 
3. 

### Expected Behavior

Should open seamlessly

### Actual Behavior

freezing while trying to open.

### Debug Information

Notepad++ v7.4.1   (32-bit)
Build time : May 18 2017 - 02:00:37
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : ON
Local Conf mode : OFF
OS : Windows 7 (64-bit)
Plugins : mimeTools.dll NppConverter.dll NppExport.dll NppTextFX.dll PluginManager.dll

**Comment by MetaChuh** [comment]
please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins if you update from version 7.5.9 or below.
if your issue still persists, and it is still of relevance, please feel free to file a new issue as easy to understand and reproducible as possible.

thank you for your help and best regards.
