### ISSUE TITLE
Open double extension files with syntax highlighting

### ISSUE THREAD

**Issue by ghost** [notepad-plus-plus/notepad-plus-plus#3366]
I can't set notepad to open files with double extension as one of languages (using style configurator).
Example: c.m4, xml.m4...

**Comment by kirsan31** [comment]
Yea, it's very annoying, for example in log files:

> log.20180323.log

Strange to have this bug so long...

**Comment by ArkadiuszMichalski** [comment]
Duplicate of https://github.com/notepad-plus-plus/notepad-plus-plus/issues/10405.
