### ISSUE TITLE
[Enhancement] Add XAML to Language Menu

### ISSUE THREAD

**Issue by sometowngeek** [notepad-plus-plus/notepad-plus-plus#3369]
### Description of the Issue

XAML is missing from the Language menu.

### Steps to Reproduce the Issue

1. Click on the Language menu.
2. Only XML shows up

### Expected Behavior

While I understand XAML is inherited from XML, but I don't think everyone realizes that. Would it be possible to add XAML to the Language menu? Here are two ideas of how I think this could be approached:
#### Language
- ...
- T >
-- ...
- V >
-- ...
- X >
-- XAML / XML

#### Language
-  ...
- T >
-- ...
- V >
-- ...
- X >
-- XAML 
-- XML

### Debug Information

Notepad++ v7.3.3   (32-bit)
Build time : Mar  8 2017 - 03:37:37
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10 (64-bit)
Plugins : mimeTools.dll NppConverter.dll NppExport.dll PluginManager.dll 

![notepadplusplusenhancement](https://user-images.githubusercontent.com/11671755/26841818-572f6d14-4ab0-11e7-94e1-5b7a84de2707.png)

**Comment by ArkadiuszMichalski** [comment]
@donho @sasumner There is no sense add another entry when XAML would still use XML lexer. There are tons of XML applications out there, and adding a separate entry for each would just make a mess. Maybe close this?

**Comment by donho** [comment]
@ArkadiuszMichalski 
Agree.
