### ISSUE TITLE
Edit, close without saving, reopen -> Saving won't work

### ISSUE THREAD

**Issue by Thaigun** [notepad-plus-plus/notepad-plus-plus#337]
If you edit a document, then close NPP and reopen it, you can see the edited file as you left it (brilliant feature by the way!). But if you try to Ctrl+S it before doing any more modifications, it won't save and the tab remains red.

I have version 6.7.9.2 on Windows 8 64-bit, but this appeared already in the previous version I had.

**Comment by sanastasiou** [comment]
I think this is similar to the bug I mentioned here : https://github.com/notepad-plus-plus/notepad-plus-plus/issues/173

**Comment by blocknot** [comment]
add:
create tab, put some text, save -> file saved.
BUT after that the program for this saved tab does not accept the any changes, tab-indicator does not change color, ctr-s do not save changes.

**Comment by ValentinSteiner** [comment]
For me, the file does get saved correctly and has the right content (check in other editor). It is just Notepad++'s idea of the file being changed that is off.

**Comment by blocknot** [comment]
I confirm it. 
at home save-status works correctly, but in the office problems with this. 
may be other settings or installed plugins influence. 
I use npp only at work in the office, at home I do not use, so almost a year these problems, sometimes lost hours of work. I tried to reinstall, but kept the old settings and plug-ins too. So I think that bug in the program.
npp 6.7.9.2
plugins: session mgr, xml tools, xpatherizer.
in settings turn off Save session, on save backup, and other settings.

**Comment by ctubio** [comment]
if you close npp with unsaved files, to save this reopened unsaved files, we are forced to modify the content and [CRTL]+[Z], then save function works again.. (it refuses to save modifications from reopened files, presumably because it only saves a file when npp detects modifications in the current session without caring if the file is saved or not)

**Comment by xaminmo** [comment]
This seems to be related to the newish "Session snapshot & periodic backup".

When the time interval passes, it saves one backup file, and then never updates the backup file again.  It never lets you set the tab red again.  It never lets you save the contents again through file-> save or Ctlr-s.

If you turn off both checkboxes for that, then save and dirty flag seem to work  normally - changed files can be saved, and the red flag only clears when it's been saved.

**Comment by donho** [comment]
Update your Notepad++ to v7.6.6.
If this bug persists in the new release, please open a new issue with the debug information.
