### ISSUE TITLE
Loses syntax highlights after clearing file compare results.

### ISSUE THREAD

**Issue by mohammadul** [notepad-plus-plus/notepad-plus-plus#3370]
### Description of the Issue
Syntax Highlights are lost after clearing the file compare results.

### Steps to Reproduce the Issue
1. Open 2 syntax highlight-able files (e.g. C++ files). [Both of them are now C++ syntax highlighted.]
2. Move one of them to the other view.
3. Click Plugins>Compare>Compare (Alt+D).
4. Click Plugins>Compare>Clear Results (Ctrl+Alt+D). [Now both of them loses the highlights.]

### Expected Behavior
Retain the original syntax highlights after Step 4 above. 

### Actual Behavior
Syntax highlights are lost and default colour is set to the text contents.

### Debug Information
None.

**Comment by dail8859** [comment]
This needs reported to the authors of the Compare plugins [here](https://github.com/pnedev/compare-plugin).
