### ISSUE TITLE
Checking with PVS-Studio static analyser

### ISSUE THREAD

**Issue by SvyatoslavRazmyslov** [notepad-plus-plus/notepad-plus-plus#3373]
To demonstrate the capabilities of our analyzer, we regularly perform analysis of open source projects. We had recently checked the Notepad++ project.

Here is the link to the article about it: [Checking Notepad++: five years later](https://www.viva64.com/en/b/0511/)

If you have any questions, or if you are interested in the evaluation of our static analyzer or in any other source code quality control services that our company provides, please contact us at support@viva64.com.

**Comment by SvyatoslavRazmyslov** [comment]
https://github.com/notepad-plus-plus/notepad-plus-plus/pull/3399

**Comment by SvyatoslavRazmyslov** [comment]
https://github.com/notepad-plus-plus/notepad-plus-plus/pull/3402

**Comment by SinghRajenM** [comment]
#3463 
FindReplaceDlg.cpp: Release dynamically allocated memory.
BabyGrid.cpp: lpcs variable assigned twice successively.
FileDialog.cpp: An exception should be caught by reference rather than by value.
ProjectPanel.cpp: A memory leak is possible.
TreeView.cpp: Wrong value is returned.
