### ISSUE TITLE
Not displaying function list for Perl language.

### ISSUE THREAD

**Issue by Abhinickz** [notepad-plus-plus/notepad-plus-plus#3374]
### Description of the Issue
Not displaying Function list for Perl language.

### Steps to Reproduce the Issue
1. Open or create any .pl or .pm file in which some Functions (Perl subroutines) are written.
2. Click on **Function List**  button.

### Expected Behavior

- I should have get the Functions list tree with filename as root for every supported language.

### Actual Behavior

- I can only see the filename without any child functions for Perl language, I checked for C++ and it working as expected.
 
- It is also possible that in case of some others language, Function list aren't being displayed.

### Debug Information
```
Notepad++ v7.4.1   (32-bit)
Build time : May 18 2017 - 02:00:37
Path : D:\Abhasker\Softwares\npp.7.4.1.bin\notepad++.exe
Admin mode : OFF
Local Conf mode : ON
OS : Windows 7 (64-bit)
Plugins : autosave2.dll ComparePlugin.dll FileSwitcher.dll HexEditor.dll JSLintNpp.dll JSMinNPP.dll LightExplorer.dll linefilter2.dll MathPad.dll MenuIcons.dll mimeTools.dll MultiClipboard.dll NppBookmarkManager.dll NppCalc.dll NppColumnSort.dll NppConverter.dll nppcrypt.dll NppExec.dll NppExport.dll NppFTP.dll NPPJSONViewer-win32.dll NppTextFX.dll NppXmlTreeviewPlugin.dll PluginManager.dll PoorMansTSqlFormatterNppPlugin.dll PreviewHTML.dll Python Indent.dll PythonScript.dll SpeechPlugin.dll Tidy2.dll TopMost.dll XMLTools.dll 
```

![image](https://user-images.githubusercontent.com/10339494/26876407-a4174360-4ba3-11e7-86d3-b23577198a59.png)

**Comment by MAPJe71** [comment]
Duplicate of #2963, see also #2964.

**Comment by ArkadiuszMichalski** [comment]
@Abhinickz Can you check if problem still exist in Notepad++ 7.9 RC http://download.notepad-plus-plus.org/repository/7.x/7.9.RC/ ?

**Comment by Abhinickz** [comment]
Yes, This problem still exists in Notepad++ 7.9 RC.

Please check this screenshot:
![image](https://user-images.githubusercontent.com/10339494/93531903-9a0c6600-f95d-11ea-832d-25bc38d17ab2.png)


#### Debug Information

```
Notepad++ v7.9   (64-bit)
Build time : Sep 14 2020 - 23:02:17
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS Name : Windows 10 Pro (64-bit) 
OS Version : 2004
OS Build : 19041.508
Current ANSI codepage : 1252
Plugins : mimeTools.dll NppConverter.dll NppExport.dll 
```

**Comment by Abhinickz** [comment]
> @Abhinickz Can you check if problem still exist in Notepad++ 7.9 RC http://download.notepad-plus-plus.org/repository/7.x/7.9.RC/ ?

@ArkadiuszMichalski Yes, This problem still exists in Notepad++ 7.9 RC.

Please check this screenshot:
![image](https://user-images.githubusercontent.com/10339494/93531903-9a0c6600-f95d-11ea-832d-25bc38d17ab2.png)


#### Debug Information

```
Notepad++ v7.9   (64-bit)
Build time : Sep 14 2020 - 23:02:17
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS Name : Windows 10 Pro (64-bit) 
OS Version : 2004
OS Build : 19041.508
Current ANSI codepage : 1252
Plugins : mimeTools.dll NppConverter.dll NppExport.dll 
```

**Comment by ArkadiuszMichalski** [comment]
I have no knowledge of Perl, but `sun` is the correct word, I can't find documentation for it.?

**Comment by Abhinickz** [comment]
> @Abhinickz I have no knowledge of Perl, but `sun` is the correct word? I can't find documentation for it.

Sorry, my bad, at the time of taking a screenshot, misspelled `sub`.

Here is the correct screenshot:

![image](https://user-images.githubusercontent.com/10339494/93533277-333c7c00-f960-11ea-8a2c-ba53397ce034.png)

**Comment by ArkadiuszMichalski** [comment]
Looks like you manually change some NPP files, but not all, and program use old files (I mean `functionList.xml`) from some your profile directory. Please download .zip or .7z folder and run (as portable) and check once again if not work (in my setup it works).

**Comment by ArkadiuszMichalski** [comment]
@Abhinickz Can you check if you don't use old `functionList.xml` probably in `%AppData%\notepad++\`? If yest then remove it (if you haven't made your own changes) and repeat test.

**Comment by Abhinickz** [comment]
@ArkadiuszMichalski ,

Just checked this on Windows Sandbox with [Notepad++ 7.9.RC2](http://download.notepad-plus-plus.org/repository/7.x/7.9.RC2/)


Now this works.

![image](https://user-images.githubusercontent.com/10339494/93793904-0edcea00-fc55-11ea-9db2-2654b927918b.png)

**Debug Information:**

```
Notepad++ v7.9   (64-bit)
Build time : Sep 14 2020 - 23:02:17
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : ON
Local Conf mode : OFF
OS Name : Windows 10 Enterprise (64-bit) 
OS Version : 2004
OS Build : 19041.508
Current ANSI codepage : 1252
Plugins : mimeTools.dll NppConverter.dll NppExport.dll 
```

**Comment by ArkadiuszMichalski** [comment]
So maybe close this bug and reopen in future if will stil exist?

**Comment by Abhinickz** [comment]
> So maybe close this bug and reopen in future if will stil exist?

Closing this as It seems to be fixed now.
