### ISSUE TITLE
Adding a way to compare files.

### ISSUE THREAD

**Issue by rogersb93427** [notepad-plus-plus/notepad-plus-plus#3375]
No file compare was loaded in visual studio.  Activating the source control did not provide file compare.

going to notepad++ in the plugins section has an item called "Compare"

### Description of the Issue

After installing "compare" over 5 times?  there is no "compare" feature to be found on notepad++

### Steps to Reproduce the Issue

1.  open notepad++
2.  go into plugins and update and click to install 'compare'
3.  nothing will happen, nothing is installed, no error message

### Expected Behavior

compare would be installed in notepad++

### Actual Behavior

nothing was installed, nothing changed, there is no compare feature in any page of any menu. 
### Debug Information

any other info?  If I said that, people would get mad at me.

**Comment by dail8859** [comment]
This needs reported to the authors of the Plugin Manager [here](https://github.com/bruderstein/nppPluginManager) or the Compare plugin [here](https://github.com/pnedev/compare-plugin) depending on what is causing it.

> any other info? If I said that, people would get mad at me.

Believe it or not the more info you provide the easier it is for people to debug it.
