### ISSUE TITLE
Feature suggestion: Color files named "crontab" as .sh files

### ISSUE THREAD

**Issue by ghost** [notepad-plus-plus/notepad-plus-plus#3377]
Feature suggestion: Color files named "crontab" as `.sh` files

crontab is the common file name for the general cron file in Nix systems. It acts as a scheduled script file. You right scheduled instructions and these are being executed basically just as they would be executed in a script.

Can you please somehow let these be colorized  similarly to `.sh` files even thought he crontab doesn't have a `.sh` extension?

**Comment by MAPJe71** [comment]
Are these files targeted by the [Contrab lexer](https://github.com/notepad-plus-plus/notepad-plus-plus/blob/51797bf59e689b11d80998758790f8a4cade68eb/scintilla/lexers/LexCrontab.cxx)?

**Comment by Benqzq** [comment]
I believe they aren't. I don't have the time to go in depth of this now but I could say this: The file bash.bashrc sits in the same directory of `/etc` in Linux and yet that files does have, seemingly, the `.sh` coloring; A similar initiation for crontab could do well (maybe it's just a reference needed to be added to some list?).
