### ISSUE TITLE
plugin update should be not interrupt flow

### ISSUE THREAD

**Issue by Stretto** [notepad-plus-plus/notepad-plus-plus#3379]
Why have this process:

1. Go to install a plugin through the pluginmanger.

2. Spend time to find the plugin(since there is no search for some odd ball reason).

3. Select plugin, click install:

WHAM! Notepad says you have to update the plugin manager, which requires restarting notepad..

this requires one to repeat the same steps.

Why not record which plugins where to be installed, then install them after the update rather than requiring the user to jump through the same hoops for no apparent reason?

**Comment by dail8859** [comment]
You need to report this to the Plugin Manager issue tracker [here](https://github.com/bruderstein/nppPluginManager/issues).
