### ISSUE TITLE
Toolbar chevron is missing when there is no space for all toolbar icons

### ISSUE THREAD

**Issue by bahusoid** [notepad-plus-plus/notepad-plus-plus#3385]
### Description of the Issue

Currently there is no way to execute toolbar command if it's not fitted on the screen:
![npp7 3 3nochevron](https://user-images.githubusercontent.com/22025304/27011587-2f49e4a8-4ec7-11e7-882a-a7729d39b2d3.png)

### Steps to Reproduce the Issue

1. Start  notepad++.
2.  Resize window to make it small - so not all toolbar icons are present.
3. All not fitted icons are simply clipped.

### Expected Behavior

In [version 6.6.9](https://notepad-plus-plus.org/download/v6.6.9.html) I see chevron with all missing commands (working fine with [minimalist package](http://notepad-plus-plus.org/repository/6.x/6.6.9/npp.6.6.9.bin.minimalist.7z)):
![npp6 6 9chevronpresent](https://user-images.githubusercontent.com/22025304/27011593-4f466164-4ec7-11e7-8b7d-24809f1c5de9.png)
I expect the same behavior for latest version.

### Debug Information

Notepad++ v7.3.3   (32-bit)
Build time : Mar  8 2017 - 03:37:37
Path : D:\Programs\npp.7.3.3.bin.minimalist_test\notepad++.exe
Admin mode : OFF
Local Conf mode : ON
OS : Windows 10 (64-bit)
Plugins : none

**Comment by MAPJe71** [comment]
Install `Customize Toolbar` plugin.

**Comment by bahusoid** [comment]
@MAPJe71 With version 6.6.9 it's working without any plugins installed.  Doesn't it mean that something get broken in later builds?

**Comment by bahusoid** [comment]
I tracked it down to the following commit (ironically it's chevron fix commit):
 https://github.com/notepad-plus-plus/notepad-plus-plus/commit/659a9387350fbb3ea9b5a5fbdf9d1f97a49047a0

The problem code:
```
#if _MSC_VER > 1400 // MS Compiler > VS 2005
#define REBARBAND_SIZE REBARBANDINFO_V3_SIZE
#else
#define REBARBAND_SIZE sizeof(REBARBANDINFO)
#endif
```

Chevron is back if I change it to:
`#define REBARBAND_SIZE sizeof(REBARBANDINFO)`
