### ISSUE TITLE
Add .editorconfig to the source code

### ISSUE THREAD

**Issue by magol** [notepad-plus-plus/notepad-plus-plus#3389]
### Description of the Issue

When I translated, I discovered that there is a mixture of spaces and tabs in the XML files. For example, see https://github.com/notepad-plus-plus/notepad-plus-plus/blob/master/PowerEditor/installer/nativeLang/english.xml#L126

I suggest adding a [.editorconfig](http://editorconfig.org/) file so that it will be right at least for those who use editors who support it. Then we have to decide what's right (tabs and spaces are used different in different xml files).

**Comment by donho** [comment]
> I suggest adding a .editorconfig file so that it will be right at least for those who use editors who support it. Then we have to decide what's right (tabs and spaces are used different in different xml files).

@magol Could you provide me a concert example for the advantage of adding this file?

**Comment by MAPJe71** [comment]
For example:
A developer contributes to three open source projects and each requires different settings for indentation. The first project requires tabs with a width equivalent to four spaces, the second project requires tabs with a width equivalent to eight spaces and the third project requires 4 spaces for each indent. The developer has a hard time remembering to apply the correct settings to the IDE/editor for each project, especially when frequently switching between the projects. 

Wouldn't it be nice/handy if the required settings are applied automatically when opening the project in its IDE or even better, opening any file from the project's tree in his favorite text editor?

It is possible by using [EditorConfig](http://editorconfig.org/). It's not a tool it's a file format for defining coding styles, is natively supported by e.g. GitHub, TortoiseGit and Visual Studio and supported through a plugin by e.g. Code::Blocks, Emacs, Notepad++ and Visual Studio Code.

The developer has added an `.editorconfig` file to the root of each project. Each file with the project specific settings. He no longer needs to remember to change settings when switching projects nor does he need to remember/lookup which project requires which settings. Each (upstream) project could benefit from having their `.editorconfig` file in the repository as it enables style consistency among its contributors (and less annoyance for the project owner 😉 ).

**Comment by magol** [comment]
@donho As I wrote in my initial text, and as @MAPJe71 described so well, today there is a big mix between different indent methods in the source code. Today it's hard to know what to use as it's so different between different files and even the same file.

I realize it was not that smart to do a big bang update like i did in #3392. But I think it might be good at least to clearly declare what to use so everyone has something to follow. Then we can slowly make the source code more uniform in terms of indentation. That will be a benefit for everyone.

**Comment by MAPJe71** [comment]
BTW existing whitespace is not effected, `.editorconfig` settings only apply to new files and edited lines of existing files.

**Comment by rugk** [comment]
And to be able to code Notepad++ in Notepad++ easily, it would be very nice if Notepad++ would support editorconfig, so an editorconfig file in Notepad++'s repo can be read out-of-the-box by Notepad++.

Wait, did not understand this sentence? :stuck_out_tongue_winking_eye: 

Oh, I mean this: https://github.com/notepad-plus-plus/notepad-plus-plus/issues/6183

**Comment by chcg** [comment]
See plugin https://github.com/editorconfig/editorconfig-notepad-plus-plus/issues/33

**Comment by rugk** [comment]
People (or @chcg) wait, no. Let's not confuse these issues:
* this here (https://github.com/notepad-plus-plus/notepad-plus-plus/issues/3389) is about **adding an editorconfig file** to the Notepad++ _source code_
* https://github.com/editorconfig/editorconfig-notepad-plus-plus/issues/33/ respectively https://github.com/notepad-plus-plus/notepad-plus-plus/issues/6183, which was, I assume, closed out of error as a dupe (of this one here), is about **having editorconfig support** in Notepad++

These are two fundamental different things!

Maybe @magol or some maintainer could edit the title of this issue here to clarify the difference. :smile:

**Comment by magol** [comment]
@rugk Good point. I have now updated the title to better explain what it is about

**Comment by donho** [comment]
It's not a good idea to follow the outside rules - once the rules change, our code should follow too.
This feature won't be implemented as built-in feature. User can always use the plugin:
https://github.com/editorconfig/editorconfig-notepad-plus-plus

**Comment by rugk** [comment]
Just to reiterate what this issue was about:
> this here (#3389) is about adding an editorconfig file to the Notepad++ source code

Given your message, you seem to talk about something else.
So please re-open.

**Comment by donho** [comment]
@rugk 
Adding `.editorconfig` file implies to:
1. support editorconfig as built-in feature
2. or include editorconfig plugin in Notepad++ official distribution

Both cases are not possible, so I don't see the advantage to do so.

**Comment by sasumner** [comment]
@donho

Is there some confusion here?
I don't think what is being asked for is editorconfig features in Notepad++, nor the editorconfig plugin as part of the N++ distro.
What is wanted is a single file added to the N++ github repository.  And that file is a "root level" `.editorconfig` file that defines the attributes of the N++ source project.
Does that make sense?

**Comment by rugk** [comment]
Indeed, adding an `.editorconfig` file to _your GitHub repo_ implies nothing – at least not for the software itself. (Think of an editorconfig file in the source of, say, e.f. the FLOSS game 0 A.D. or [the editorconfig file of git](https://github.com/git/git/blob/master/.editorconfig) – git may include a built-in text editor [it does not, but let's imagine it does], but that does not imply that text editor supports `.editorconfig`.)

So TL;DR: The configuration file only applies to your source code – just like any tooling/file you use for your development process.
E.g. [the gitignore](https://github.com/notepad-plus-plus/notepad-plus-plus/blob/master/.gitignore) also does not imply your software supports git… – [there are plugins for git support in Notepad++ though](https://stackoverflow.com/questions/3490505/is-there-a-notepad-with-github-plugin).
The [appveyor file](https://github.com/notepad-plus-plus/notepad-plus-plus/blob/master/appveyor.yml) also does not imply your software supports YAML – or that specific format/syntax that is used for that.
etc. etc.

It's just a little convenience feature, especially for contributors. Nothing to discuss a lot about, really, especially as it is likely 10 lines long or so at most.

**Comment by mere-human** [comment]
> What is wanted is a single file added to the N++ github repository. And that file is a "root level" `.editorconfig` file that defines the attributes of the N++ source project.

I just want to add that the `.editorconfig` feature is supported out of box without any extensions in Visual Studio:
![image](https://user-images.githubusercontent.com/9664141/113760320-c1225d80-971e-11eb-82e1-d0aa365cac68.png)
