### ISSUE TITLE
Notepad crash causing the selected tab file losing all its contents

### ISSUE THREAD

**Issue by aprovent** [notepad-plus-plus/notepad-plus-plus#339]
The issue comes sometimes when i press Ctrl + S to save the file. Notepad++ crash, nothing can be done expect closing the program.

It append 4 times since the installation of v6.7.9.2 yesterday. 
The file cannot be restored. It never append before (i'm using Notepad++ for years).  
I cannot reproduce the bug.

I'll try to take a snapshot the next time.

I'm under Windows 7 x64

**Comment by ariccio** [comment]
Did `Notepad++` offer to save a dump file?

**Comment by aprovent** [comment]
No sorry. It was windows "check for a solution and close the program" window. Is there anything i can do to help you the next time it append ?

**Comment by jamesrhfellows** [comment]
I've just experienced this issue myself. 6.7.8.2, no problems at all in the years before. The one difference I can offer is that a backup was successful made in AppData and after I found it was there, re-created the file from that. Perhaps it's a combined issue of a save bug and then not being able to find the backup of the active contents afterwards?

**Comment by donho** [comment]
@aprovent  Could you provide your plugin list please?

**Comment by aprovent** [comment]
here they are
![npp_plugins](https://cloud.githubusercontent.com/assets/11990709/8402577/ab29da96-1e3c-11e5-9e2d-f07eca77d01f.png)

**Comment by aprovent** [comment]
@jamesrhfellows thank you very much, i didn't know the presence of AppData backups. I found my lost backup file !

**Comment by jack-lewin** [comment]
I just encountered this problem too, on v6.7.8.2. Thanks a lot @jamesrhfellows for the AppData backup tip!

Here's a list of my installed plugins, if it helps:

![image](https://cloud.githubusercontent.com/assets/13153399/8481455/149ca63e-20db-11e5-8401-d3509b596490.png)

**Comment by ariccio** [comment]
@aprovent *if* you have WinDbg installed, you can attach to `notepad++.exe` and try to reproduce the crash.

**Comment by donho** [comment]
Can anyone provide the instructions to reproduce the crash?

**Comment by LPology** [comment]
This happened to me twice today. It also happened back in December or January. 

I don't know how to reproduce the crash. It happened, I believe, while I was trying to save the file that I lost. I don't recall doing anything out of the ordinary. Notepad++ froze, and then exited on its own. When I opened it back up, my file was blank. I had probably 15 tabs open. About half were saved files, half or so were unsaved new docs. All 15 were fine, only the selected tab was lost.

I'm using version 6.8.3 on Windows 7. I did not get the  "check for a solution and close the program" box, it just closed. Here is my plugin list:

![nppplugins](https://cloud.githubusercontent.com/assets/2237504/10627463/c38d8e1c-7787-11e5-8afb-4974b96b2048.png)

**Comment by milipili** [comment]
@LPology I am not able to reproduce it. Is it still happening ?

**Comment by badrelmers** [comment]
Yes it is still happening :(
**The bug: the tabs that are opened get lost**
never happened before using npp.6.7.9.1.Installer.exe
I had this bug when I updated to v7.3.3 portable then I downgraded to v6.8.8 portable and I had the same bug.
it happens in 2 situations:
1- when I open np++ as administrator while it is opened as normal user, but I couldn t reproduce this manually !
2- when I format (I use the portable version so the AppData is not used and temp files are saved in my portable folder), sometimes when I format (recover full pc image) I lose the tabs too.

I hope we can catch this mouse :)
but thanks to God at less files are not lost you can reopen them from Appdata or you portable folder if you configured notpad++ to be portable...

**Comment by donho** [comment]
Update your Notepad++ to v7.6.6.
If this bug persists in the new release, please open a new issue with the debug information.
