### ISSUE TITLE
Save not adding filename extension

### ISSUE THREAD

**Issue by kaosengr** [notepad-plus-plus/notepad-plus-plus#3390]
### Description of the Issue

Filename extension is not being added when a file is saved.

### Steps to Reproduce the Issue

1. Open a new empty file.
2. Enter some text
3. Press the 'Save' icon.
4. Name the file, "save me!", Save as type: (default shown is Normal text file (*.txt)
5. Press Save button
6. Look for saved file in Windows file manager or use Save as to see file saved without extension.

### Expected Behavior

The extension .txt should be added to the filename.
### Actual Behavior

The extension .txt was not added when certain character(s) are the last character of a filename (e.g., '!').
Exclamation mark is the only character tested by accident.
Not always reproducible, went back to test again and it now adds the extension.

### Debug Information

Notepad++ v7.4.1   (32-bit)
Build time : May 18 2017 - 02:00:37
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10 (32-bit)
Plugins : mimeTools.dll NppConverter.dll NppExport.dll NppFTP.dll NppTextFX.dll PluginManager.dll SpellChecker.dll

**Comment by kaosengr** [comment]
I tried it again and could not get it to act up. :(
![extension not added bad save timestamp as i saved un-extension file after manually adding txt for save as](https://user-images.githubusercontent.com/4968128/27045285-03ea75e4-4f66-11e7-865c-1a10879255e2.JPG)

**Comment by lucas-engen** [comment]
My notepad++ is working with correctly. See ...

![image](https://user-images.githubusercontent.com/13322110/27106328-55c4d4dc-5069-11e7-9f57-baac199048c8.png)

![image](https://user-images.githubusercontent.com/13322110/27106466-e76a252c-5069-11e7-9de4-7f0c8ea480fc.png)

![image](https://user-images.githubusercontent.com/13322110/27106487-f5e160d4-5069-11e7-8e2c-3b54bb22688d.png)

**Comment by kaosengr** [comment]
I think I may have determined the cause.  It happened again to me and here's the Save As.. dialog
![notepad not adding extension txt to filename](https://user-images.githubusercontent.com/4968128/27529292-85c927c8-5a19-11e7-8cc6-8ddac119e9a9.JPG)
Look back at my original bug submission notice the similarity?

There's a dot, '.', in the filename I entered each time the .txt extension was not added.  Double checked to verify this anomaly -- or my SNAFU.  If a file has no '.' in the filename entered the extension is appended; however, if there's a '.' in the filename entered into the File name box, no extension is added.

**Comment by irgendsontyp** [comment]
I consider this a bug. We could check whether there is a " " (space) after the last ".". Would that be enough? Alternatively we could use WinAPI's [PathFindExtension](https://msdn.microsoft.com/en-us/library/windows/desktop/bb773587(v=vs.85).aspx) but that exists from Windows 2000 on. But regarding "PowerEditor/src/Parameters.cpp", line 851:

`int FileDialog::_dialogFileBoxId = (NppParameters::getInstance())->getWinVersion() < WV_W2K?edt1:cmb13;`

I assume Windows versions < Windows 2000 should also be supported so the API function wouldn't be an option.

**Comment by irgendsontyp** [comment]
See PR #3470.

**Comment by kaosengr** [comment]
I was just expecting when I have a "Save as type" selected that this extension would always be added to the end of the filename.  If I didn't want an extension to be added, I'd have to change the "Save as type" to *.*

**Comment by grusshauf** [comment]
I am finding this same issue.  Is there a way for Notepad++ to automatically add the extension when I pick a particular type (in my case it is json)?

Thanks in advance.

**Comment by kaosengr** [comment]
I know the problem I had was that the filename already contained a period character.  Notepad++ thinks the extension has already been keyed in thus does not add the extension you’ve selected for the Save As Type extension.  Remove any periods in the filename and the extension will be added when you click the Save button.  If you need the periods in the filename before the extension of the named file, you’ll have to key-in the extension for it to be saved with the “.json” extension.

**Comment by donho** [comment]
Cannot reproduce it with v7.8.5 under Windows 10

**Comment by sasumner** [comment]
@donho I can reproduce this in your same setup:

First, assure this setting:

![image](https://user-images.githubusercontent.com/30118311/78134488-3f527280-73ee-11ea-8887-925d0f6799e5.png)

Then, create new file, modify it, and save it, giving it a name with an interior `.`, for example, `new_1.5.3` :

![image](https://user-images.githubusercontent.com/30118311/78134683-87719500-73ee-11ea-8a3a-8dd41af77fb3.png)

Pressing save will result in the file `new_1.5.3` being saved (and NOT `new_1.5.3.txt` )

Repeating steps but naming the file `new_153` results in new_153.txt` being saved.

**Comment by donho** [comment]
Believe or not, it's a feature but not a bug.
If user wants to set his/her file ext and ignore the set type, he/she can add any extension so the set type is overridden.

**Comment by sasumner** [comment]
@donho said:

>If user wants to set his/her file ext and ignore the set type, he/she can add any extension so the set type is overridden.

Yes, but that isn't the point here.  Clearly (from a human viewpoint) in my example just above the desired extension is NOT `.5.3` or even `.3`.

BUT, there really is no possible way to implement what is wanted.  Meaning, there is no way for Notepad++ to know what is or is not an extension when the _File name_ includes one or more period ( `.` ) characters.

Thus the best solution is to do nothing, and if a user saves a filename like `new_1.5.3`, they will (hopefully) see in the tab that their new file does not have the `.txt` extension and they can then use the Rename command to add it.

Or, what I do, every single time I've ever created a new file, is to just type the extension myself after the _File name_ in the box.  I've never really understood what the big deal is about having an extension automatically added by virtue of the _Save as type_ selection.
