### ISSUE TITLE
Crash on sort by column when selection beyond eol

### ISSUE THREAD

**Issue by AGlezB** [notepad-plus-plus/notepad-plus-plus#3391]
### Description of the Issue
When using Sort Lines with column mode NPP crashes if the selected column is greather than the eol of any line.

### Steps to Reproduce the Issue
1. In a blank tab type 2 lines of text, one short and one long.
2. Use column selection on any column beyond the end of the short line.
3. Use Edit/Line Operations/Sort Lines Lexicographically Ascending

Selected between _e_ and _f_:
![20170612-152852-000541 npp crash](https://user-images.githubusercontent.com/12277525/27051470-3f5ac336-4f84-11e7-9fba-1e2cef6d1c88.png)

### Expected Behavior
Lines sorted.

### Actual Behavior
NPP displays "invalid string position" in a messagebox titled "General exception", performs recovery and quits.

### Debug Information
Notepad++ v7.3.3   (64-bit)
Build time : Mar  8 2017 - 03:39:58
Path : D:\tools\npp\notepad++.exe
Admin mode : OFF
Local Conf mode : ON
OS : Windows 8.1 (64-bit)
Plugins : none

**Comment by chcg** [comment]
@sachinjegaonkar Would you like to provide a PR with your fix?

**Comment by sachinjegaonkar** [comment]
Yes. I think I have already created a PR (#3771) for this an year ago. Please merge those changes if you have access to do so.
