### ISSUE TITLE
Use SetMenuItemInfo() instead of ModifyMenu()

### ISSUE THREAD

**Issue by Yaron10** [notepad-plus-plus/notepad-plus-plus#3396]
Hello @SinghRajenM,

I hope you're doing well.

May I request your help again? - I'd appreciate it.

The MenuIcons plugin (by Franco Stellari) adds icons to NPP menu and Shell-icons to the files in the Recent Files list.

I find this addition very useful and helpful. I'm quite sure many other users value this plugin.

https://github.com/notepad-plus-plus/notepad-plus-plus/commit/4a0e880557f8cf515b93d8828f887292a1a669a2 included in v7.4.1 has turned MenuIcons useless.
Whenever you open a file from the Recent List, the menu is modified and the icons disappear.

Franco has suggested the following solution:
In [shortcut.cpp](https://github.com/notepad-plus-plus/notepad-plus-plus/blob/master/PowerEditor/src/WinControls/shortcut/shortcut.cpp) replace
```
::ModifyMenu(_hAccelMenu, cmdID, cmdFlags, cmdID, csc.toMenuItemString().c_str());
```
with
```
MENUITEMINFO mii;
mii.cbSize = sizeof(MENUITEMINFO);
mii.fMask = MIIM_STRING;
std::basic_string<TCHAR> sMenu = csc.toMenuItemString().c_str();
mii.dwTypeData = &sMenu[0];
::SetMenuItemInfo(_hAccelMenu, csc.getID(), FALSE, &mii);

```
and
```
::ModifyMenu(_hAccelMenu, id, MF_BYCOMMAND, id, menuItem.c_str());
```
with
```
MENUITEMINFO mii;
mii.cbSize = sizeof mii;
mii.fMask = MIIM_STRING;
std::basic_string<TCHAR> sMenu = menuItem.c_str();
mii.dwTypeData = &sMenu[0];
::SetMenuItemInfo(_hAccelMenu, id, FALSE, &mii);
```
If you have some free time, could you please review it and submit a PR?
Thank you very much.

See: https://notepad-plus-plus.org/community/topic/13863/menuicon-problem-with-latest-version-of-npp/4.
Thank you Franco and all contributors in that thread. 

Best regards.

**Comment by SinghRajenM** [comment]
I'm in remote location and don't have my Dev pc with me. I'll be back by
this month end. Be assured I will check it once I come back.

**Comment by Yaron10** [comment]
Hello @SinghRajenM,

Thank you very much.
I appreciate your kindness.

Best regards.

**Comment by donho** [comment]
@Yaron10 
Is it still an issue to you?

**Comment by Yaron10** [comment]
@donho,

It's not an issue for my personal use. I've reverted https://github.com/notepad-plus-plus/notepad-plus-plus/commit/4a0e880557f8cf515b93d8828f887292a1a669a2.

But the MenuIcons plugin (by @francostellari) is currently useless for most users.
This is your decision.

Thank you.

**Comment by Yaron10** [comment]
To Whom Might Be Interested:

Looking into it again - https://github.com/notepad-plus-plus/notepad-plus-plus/commit/4a0e880557f8cf515b93d8828f887292a1a669a2 is not related and has no effect on MenuIcons.
It's only the two `ModifyMenu` instances in [shortcut.cpp](https://github.com/notepad-plus-plus/notepad-plus-plus/blob/master/PowerEditor/src/WinControls/shortcut/shortcut.cpp).
