### ISSUE TITLE
When having a big text file (1,6 GByte) and using 64 bit version of Notepad++, marking text via mouse is chaotically

### ISSUE THREAD

**Issue by martin2606** [notepad-plus-plus/notepad-plus-plus#3398]
### Description of the Issue
When having a big text file (1,6 GByte) and using 64 bit version of Notepad++, version 7.3.3,
marking text via mouse is chaotically. Goint to "Start of File" display is suddenly flickering. Then no more reaction.

### Steps to Reproduce the Issue
I am using Notepad++, version 7.3.3. 64 Bit version.
I am opening a 1,6 GByte text file (logfile, I know it is big),
I can open it without problem. When I am in line 17858419,
which is almost at the end, the mouse movement is not more correct.
Marking area of text is jumping up and down, when I mark some characters, one after the other.
(with the mouse).
When I go to pos 1 (start of file) suddenly display start flickering, changing from correct content
to white screen. Flickering takes a long time, suddenly it works again, displaying correct content.

At line 16897500 it looks like every second line is working, 
all other mark lines below or above the line selected via mouse???

File has in total 17.858.xxx lines. Length 1.636.348.103. Windows (CR LF). UTF8.

### Expected Behavior
Correctly marking of characters, no flickering of text file content

### Actual Behavior
See steps to reproduce.

**Comment by dail8859** [comment]
Notepad++ uses Scintilla v3.5.6 (this is what handles the low level text editing). In version 3.7.2 of Scintilla it fixes this bug.

Relevant line in the Scintilla v3.7.2 changelog:

> Use more precision to allow selecting individual lines in files with more than 16.7 million lines

**Comment by martin2606** [comment]
Many thanks for your answer!
Is there already a plan to switch to Scintilla v3.7.2 (or newer)?

**Comment by martin2606** [comment]
Additional question: Do you perhaps know of any other editor (or at least viewer),
64 bit, which can open such big files and uses Scintilla v3.7.2 (or newer).
So I can retest now (and use it perhaps as workaround till suitable Notepad++ is available)?

**Comment by dail8859** [comment]
> Is there already a plan to switch to Scintilla v3.7.2 (or newer)?

None I am aware of.

> Do you perhaps know of any other editor (or at least viewer),

If you want to use something specifically Scintilla based I'd recommend [SciTE](http://www.scintilla.org/SciTE.html) (this is from the developers of Scintilla). 

If you are just wanting something to view the large file that has better performance then there are other text editor specifically made to do that, a simple Google search can find them.

**Comment by martin2606** [comment]
> None I am aware of.
Not good, but ok.
> based I'd recommend SciTE
Already tried it, but this is only 32bit and when trying to open big file, 
unfortunately it just displays nothing. But many thanks for the hint.

**Comment by ArkadiuszMichalski** [comment]
@martin2606 Do you still have this problem in actuall Notepad++? Base on https://github.com/notepad-plus-plus/notepad-plus-plus/issues/3398#issuecomment-308417125 it was fixed and Notepad++ use a newer version of Scintilla.

**Comment by ArkadiuszMichalski** [comment]
I'm closing it, there is no response so I assume that the problem is solved. If necessary, . I will re-open it again.
