### ISSUE TITLE
EntryPoint GetTickCount64 not found in kernel32.dll on startup

### ISSUE THREAD

**Issue by TekBear** [notepad-plus-plus/notepad-plus-plus#34]
An auto plugin update triggered today and this error occurred when npp restarted . Initially it referred to snippets add on so I removed that. The error title then changed to "Notepad++.exe" so I updated to v6.7.7 but the error is still there.  Maybe add on is causing it but how to I figure out which one it is?  Can I disable all plugins temporarily?

platform: win xp sp2 32bit
![npp entrypoint gettickcount64 not found in kernel32 dll](https://cloud.githubusercontent.com/assets/5044866/7509391/974b7db6-f4c2-11e4-99cb-71290d32eb24.png)

.This is why I dislike updating more than one app and the same time ;-)

**Comment by TekBear** [comment]
Update:I went through all the DLL using a dll viewer ad found the only library with that EP is libcurl.dll in main npp dir. If I remover this dll the problem goes away, so what will break I remove this? Is there a 32 bit version I can use - can I pull one from an older npp version?

![npp libcurl dll ep problem](https://cloud.githubusercontent.com/assets/5044866/7509691/c2d7ba9a-f4c6-11e4-8c89-00f4a06106a0.png)

**Comment by andreas-jonsson** [comment]
You can disable all plugins temporarily by renaming C:\Program Files (x86)\Notepad++\plugins to something else.

**Comment by andreas-jonsson** [comment]
http://notepad-plus-plus.org/news/notepad-6.7-release.html

"Note that all versions before Windows XP SP2 are not supported any more by Notepad++."

Not sure if this means that XP SP2 itself isn't supported.

**Comment by ariccio** [comment]
Did you say ***SP2***???!? Holy crap, what the hell? *Not even SP3?!?*

I just hope that computer isn't involved in the Healthcare or Financial sectors. If you are, then you're probably in serious legal trouble, or are at risk of it.

**Comment by donho** [comment]
@andreas-jonsson I confirm that XP SP2 itself is supported.

**Comment by TekBear** [comment]
@ariccio  unfortunately sp3 fails to load eventually the hardware will die and it will become history. It has minimal exposure to Net. There are many systems that have this problem  ;-p

The libcurl.dll must be installed by one of my add on but I don't know how to find which one it is. Obviously I can just uninstall everything and incrementally add each add on till the DLL appears again. Is there no quicker way?

**Comment by donho** [comment]
@TekBear 
I tried launch v6.7.7 on my XP SP2 without any issue.
 Could you try the zip package?

**Comment by MAPJe71** [comment]
I got the missing procedure entry point for GetTickCount64 message after upgrading the XMLTools plugin to version 2.4.5.
Notepad++ v6.7.7 on WinXPSp3.

**Comment by milipili** [comment]
Is the issue still around ?

**Comment by MAPJe71** [comment]
Notepad++ v6.9.2 with XMLTools v2.4.8 on WinXPSp3: no problem.
