### ISSUE TITLE
Show White Space and TAB keyboard shortcut

### ISSUE THREAD

**Issue by cristianadam** [notepad-plus-plus/notepad-plus-plus#340]
Currently "Show White Space and TAB" doesn't have a keyboard shortcut mapped.

Visual Studio uses Ctrl+Shift+8. This would make Visual Studio (current and former) users happy if you would use it by default.

**Comment by Rikk** [comment]
I would set it to "Show All Characters" just like MS Word.

**Comment by milipili** [comment]
I like the "Show all characters"

**Comment by glennfromiowa** [comment]
Note that this can be **manually** accomplished with current functionality using the Shortcut Mapper. Is this enhancement to map the "Show All Characters" to Ctrl + Shift + 8 **by default**? If so, would this apply to _upgraded_ **and** new versions of Notepad++, _or_ would it **only be applied to new installations**?

My preference would be to map "Show White Space and Tab" to Ctrl + Shift + 8; "Show End of Line" to Alt + Shift + 8; then "Show All Characters" could be mapped to the intersection of those at Ctrl + Alt + Shift+ 8. Or perhaps just the first one to correlate to the **Visual Studio** shortcut. I'm not sure why the preference for an MS Word setting over a Visual Studio setting that _programmers_ would use.

**Comment by MetaChuh** [comment]
closed due to:
* inactivity (2y)
* keyboard shortcut can be done using the shortcut mapper
