### ISSUE TITLE
Changelog tab always opens on startup

### ISSUE THREAD

**Issue by kirk-rs** [notepad-plus-plus/notepad-plus-plus#3404]
### Description of the Issue

v7.4.1 (latest as of 2017-06-16) always opens changelog.txt on startup, even after I close it.  
AFAIK, this has never happened before.

### Steps to Reproduce the Issue

1. Open NPP
2. Changelog.txt appears as the farthest right-hand tab
3. Click on "X" to close changelog.txt
4. Close NPP
5. Restart NPP
6. Changelog.txt appears as the farthest right-hand tab (ENDLESS LOOP!)

### Expected Behavior

1. Open NPP
2. Changelog.txt appears as the farthest right-hand tab
3. Click on "X" to close changelog.txt
4. Close NPP
5. Restart NPP
6. Changelog.txt no longer loads (until next version update installed)

### Actual Behavior

1. Open NPP
2. Changelog.txt appears as the farthest right-hand tab
3. Click on "X" to close changelog.txt
4. Close NPP
5. Restart NPP
6. Changelog.txt appears as the farthest right-hand tab (ENDLESS LOOP!)

### Debug Information

Notepad++ v7.4.1   (32-bit)
Build time : May 18 2017 - 02:00:37
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10 (64-bit)
Plugins : mimeTools.dll NppConverter.dll NppExport.dll NppTextFX.dll PluginManager.dll 

![image](https://user-images.githubusercontent.com/6557630/27228914-69472202-525e-11e7-845d-cc2b199b0d76.png)

**Comment by ei** [comment]
I am also suffering from this on the reverted v7.3.3 on my Windows 7 laptop. On my other Windows 10 laptop I do not have this issue at all, on any NP++ version.

**Comment by auge8472** [comment]
I can confirm the problem but also the solution which @xv posted. Away from the fact, that Microsoft hides the properties of shortcuts in the quick start bar *very* good, I saw the link to the changelog file and was able to remove it from the link target.

It's only a workaround but it does it's job. Thank you.

**Comment by ArkadiuszMichalski** [comment]
Is this issue can still can be reproduce? How the `changelog.txt` file was added to the shortcut, by system or user?

**Comment by donho** [comment]
Since the cause has been found, I think this issue can be closed.
