### ISSUE TITLE
"Find Previous" for the Find window

### ISSUE THREAD

**Issue by robotboy655** [notepad-plus-plus/notepad-plus-plus#3409]
### Description of the Issue
Perhaps we can have a quick "Find Previous" functionality somewhere in the "Find" window.

The problem is as follows.
* There's F3 and SHIFT+F3 that can do this. The problem is that this requires to change focus from the Find window to the Editor itself (i.e. pressing F3 in the Find window does nothing)
* There's the "Direction" setting in the Find window. The problem with that is that it takes time to switch and its very annoying (moving cursor is very hard work), especially if you need to rapidly change direction for whatever reason.

My proposed solutions:
* Make F3 and SHIFT+F3 focus the editor automatically when used in the Find window or just work from while Find window is focused
* Add a small button somewhere near "Find Next" that will find previous
* Add a rightclick/mouse3/mouse4/whatever action for "Find Next" button to find previous

On a side note, not being able to use CTRL+G while Find window is focused (and CTRL+F while Go To... window is focused) is super annoying as well.

**Comment by bahusoid** [comment]
You can search in opposite direction via Shift+Enter from Find Window dialog.

**Comment by robotboy655** [comment]
Thanks!
