### ISSUE TITLE
New hover preview feature seems to slow restore from minimize

### ISSUE THREAD

**Issue by PH0lder** [notepad-plus-plus/notepad-plus-plus#3410]
### Description of the Issue
Since the addition of the new feature that causes the popup picture of a tab when you hover over it, the restoring of the window from minimized state has become measurable slower.

### Steps to Reproduce the Issue
1.  Have many tabs open (like 200+)
2. Minimize the window to a button on the taskbar.
3. Click on the button on the taskbar to restore the window.

### Expected Behavior
It should remain as fast as it was before.  It should always be fast to use a text editor.

### Actual Behavior
There are times when I can count to nearly 5 before the window fully restores.  It is very clearly laggy, and makes it super annoying when you are copying and pasting between some other window into a text tab.

### Debug Information
Notepad++ v7.4.1   (64-bit)
Build time : May 18 2017 - 02:02:28
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10 (64-bit)
Plugins : mimeTools.dll NppConverter.dll 

If, as I suspect, the new feature is responsible for this slow down, then I would like the option to disable this feature, or have it moved into a plug-in or something similar.  As a temporary measure, if this is not already the case, assuming the minimization is causing the discarding of the images used for the previews, and a restore is causing them to be re-generated, then I would prefer said regeneration occurs as a background event after the restore, because odds are when I restore I am not immediately going to need the hover images.

**Comment by MetaChuh** [comment]
i can not reproduce a significant slowdown issue when minimising and restoring notepad++ with 100 tabs and tab document peeker enabled on notepad++ 7.6.6.

please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins if you update from version 7.5.9 or below.

if your issue still persists on your system, please go to `settings > preferences > misc. > document peeker` and disable `peek on tab`.

thank you for your help and best regards.
