### ISSUE TITLE
Changed window find and replace in v7.4.2: Line break in german language

### ISSUE THREAD

**Issue by JackyRyan** [notepad-plus-plus/notepad-plus-plus#3415]
### Description of the Issue
In german language there is a poor line break in "find and replace" dialog (Weitersuche-n):  

![1](https://user-images.githubusercontent.com/29531994/27271478-453476a8-54c5-11e7-8aa5-7bf112754cab.PNG)

### Steps to Reproduce the Issue

1. Set language to german
2. Open find and replace dialog ctrl-f
3. See poor linebreak on right upper corner

### Expected Behavior
No line break

### Actual Behavior
Poor line break

### Debug Information
n/a
### In addition one further question:
Are the 2 arrows "<<" on find button your purpose? (I'd rather leave them...)

**Comment by AndNovAtor** [comment]
I have similar behavior with Russian language (and "<<Find" button is also not translated). With English (text "Find next" ) this button is displayed normally.
It may be necessary to increase the width of the right column (column of "find" buttons).

**Comment by JackyRyan** [comment]
OK, now I understand
"<< Find" is searching backward
"Find next" searching forward

![2](https://user-images.githubusercontent.com/29531994/27376160-9cf72f7c-5671-11e7-88f6-a5552109d830.PNG)

Why don't use a radio button to change between forward / backward? Why use arrows on search backward and "no arrows" on forward (don't like "Find >>"?)? Furthermore I'm used to click on first button after textbox to search and wondered why it only searches backward - but now I understand that there are 2 buttons forward / backward (other programs only have one button and use a radio box to change it).

Please update german text and button width:
"<< Suchen"
"Weitersuchen" + extend width (or just write "Suchen" and leave the width)

**Comment by AndNovAtor** [comment]
Radio buttons was removed in THIS update.... https://notepad-plus-plus.org/download/v7.4.2.html

**Comment by JackyRyan** [comment]
I only see:
3. Enhance Find Replace dialog (resizable & remove search direction radio buttons)

But what about changing the text and the arrows etc.? Was there any discussion?

**Comment by AndNovAtor** [comment]
Hmm. For example: https://github.com/notepad-plus-plus/notepad-plus-plus/pull/3414
So, it will be fixed.

**Comment by AndNovAtor** [comment]
Hm, i'm wrong. It is "custom" pull request. So, it is still bug.

**Comment by Ilis** [comment]
The same in Russian

![npp_find](https://user-images.githubusercontent.com/1223140/27380386-4d64f418-5698-11e7-9099-effae756fe71.jpg)

**Comment by JackyRyan** [comment]
Allright, I'm not the only one having the problem. I hope the guys are working on it 😃

**Comment by AraHaan** [comment]
An option is to have a config file determine the size of the controls and the locations and then when the user selects an language that would normally present the issue size the dialog up apropriately and the button. This would then solve the issue entirely.

**Comment by JackyRyan** [comment]
In English you've got "<< Find" and "Find >>". Why don't just translate to the proper language with arrows?
OK, in German it would be "<< Suchen" and "Suchen >>", which would need a bit more width.
So, you mean to check the word in the appropriate language, calculate its width, store it in a config file and then resize the button width?
I don't know if a config file is really needed, but resizing dependend on language word width is good idea 👍

**Comment by rddim** [comment]
I have the same problem with Bulgarian language, but I make an improvisation

Bulgarian:
![npp-bg](https://user-images.githubusercontent.com/8998791/27452379-05710d6e-579b-11e7-9211-cae418ec0fb4.png)

Russian:
![npp-ru](https://user-images.githubusercontent.com/8998791/27452406-1a63c9dc-579b-11e7-8076-01cfa1de94bc.png)

German:
![npp-de](https://user-images.githubusercontent.com/8998791/27452420-25400532-579b-11e7-8e35-65565950f06e.png)

English:
![npp-en](https://user-images.githubusercontent.com/8998791/27452432-2caf2ce4-579b-11e7-9370-656828693b43.png)

**Comment by AraHaan** [comment]
@rddim I think that would work.

**Comment by JackyRyan** [comment]
@rddim Yes, the words are short enough 😃 In German I'd rather use "Zurück" and "Weiter" or "Rückwärts" and "Vorwärts".

**Comment by dinkumoil** [comment]
I think is was an ill-considered decision to remove the radio buttons for the search direction preference. As a result we are not only in the situation of having undersized buttons (he guys, English is not the only language in the world!), furthermore we lost the option to **replace** backwards and that's the worst thing about this story. 

So **please**, revert this stuff in the next release!

**Comment by dinkumoil** [comment]
And no, to add another two buttons for the replace function is **not** a good idea!

**Comment by allainsim45** [comment]
It also lacks an identifier to allow the translation of "<< Find" in version NP ++ 7.4.2

>           <Dialog>
>              <Find title="" titleFind="Find" titleReplace="Replace" titleFindInFiles="Find in Files" titleMark="Mark">
>                   **<Item id="??"   name="Find Previous"/>**
>                  <Item id="1"    name="Find Next"/>
>                  <Item id="2"    name="Close"/>
>                  <Item id="1620" name="Find what:"/>
>                  <Item id="1603" name="Match &amp;whole word only"/>
>                  <Item id="1604" name="Match &amp;case"/>
>                  <Item id="1605" name="Regular &amp;expression"/>
>                  <Item id="1606" name="Wrap aroun&amp;d"/>
>                  <Item id="1612" name="&amp;Up"/>
>                  <Item id="1613" name="&amp;Down"/>
>

**Comment by dinkumoil** [comment]
Seems to be reverted. See 4d921b7
