### ISSUE TITLE
"Keep non existing File": Broken Network connections: very long timeout - for each file. Please allow "Keep this file in Editor" by default

### ISSUE THREAD

**Issue by schittli** [notepad-plus-plus/notepad-plus-plus#3419]
### Description of the Issue

Good afternoon

If notepad++ has multiple files open from the same Network Device the Network Connection gets lost, then notepad++ startes getting annoying: it starts testing each individual file and waits about 90seconds - even if different files are on the same network connection.
The "Keep non existing File" Dialog is "Not Responding".

### Steps to Reproduce the Issue
1. Open different Files from the same Network Share
2. Cut the Network connection
3. notepad++ is not responding and asking for each file if it should be kept in the Editor

### Expected Behavior
I propse:
1. Please allow us to configure that Files from broken network devices should automatically be kept in the Editor. (Without asking)
3. If possible, please don't start the same "Is the file available" for all other Files on the same Network drive. If File a.txt on a Network drive is no longer accessible because the Share is disconnected, then File b.txt on the same network share will probably disconnected, too.
2. Maybe, there would be a better solution to test if a network File still exists than to wait for the Network Timeout (I think it's 90 seconds)

### Actual Behavior
The "Keep non existing File" ends in notepad++ not responding

**Comment by donho** [comment]
![image](https://github.com/user-attachments/assets/0cb96fc5-5e77-40d9-855c-0e326fb44926)
