### ISSUE TITLE
Find or replace extended newlines problem

### ISSUE THREAD

**Issue by RickZeeland** [notepad-plus-plus/notepad-plus-plus#3421]
**version 7.4.1**

### Extended find or replace
Only double occurrences of Windows line ending style can be found.

### Steps to Reproduce the Issue
Search extended for \r\n

**Comment by dail8859** [comment]
There was an issue with find/replace with v7.4.1 that may be the cause of this. Try the newly release v7.4.2 to see if it occurs again. Also make sure that your file is actually using Windows line endings.

**Comment by RickZeeland** [comment]
I updated to **7.4.2** but the issue still isn't fixed, however I found that the portable version **7.3.3** works as expected.

**Comment by dail8859** [comment]
I can't reproduce it at all. It is working fine for me.

**Comment by RickZeeland** [comment]
That's weird, on my other Windows 7 machine it works ok, on my Windows 10 machine I have the problem.
I'm using English, no strange language configurated.

**Comment by irgendsontyp** [comment]
I'm on Windows 10 64-bit and it works for me, too.

Can you provide an example file?

**Comment by RickZeeland** [comment]
@irgendsontyp just text with Cr+Lf line endings. But the only machine I have this problem is a development machine with Windows 10 Pro, could it be related to the VC++ runtimes installed ?

**Comment by wonkawilly** [comment]
I'm really sorry if I'm bothering you all, but maybe the participants to this thread would want to give their opinion about this new and rich proposal about the improvement of the Find and Replace dialog at this link: #9627. Which will be a great improvement and perhaps even a real game changer for all of us that use N++ for more advanced uses than just editing the shopping list.
Please partecipate and ask others to. More opinion are welcome. Thank you all.

**Comment by alankilborn** [comment]
Suggest this old issue be CLOSED as it appears to be working fine in N++ 8.4.4 (current version as of this writing).
