### ISSUE TITLE
Block mark by keystrokes

### ISSUE THREAD

**Issue by BasDeBlok** [notepad-plus-plus/notepad-plus-plus#3422]
### Description of the Issue
Make block mark possible by key strokes only.
For instance:

Alt - Arrow-Right
Alt - Arrow-Down
Alt - Arrow-Left
Alt - Arrow-Up
Alt - Page-Down
Alt - Page-Up

### Expected Behavior
BlaBla BlaBla BlaBla BlaBla BlaBla BlaBla BlaBla BlaBla BlaBla More Bla Bla More Bla Bla
BlaBla BlaBla **_Some text to be markedSome text to be marked_** More Bla BLa
BlaBla BlaBla **_Some text to be markedSome text to be marked_** More Bla Bla More Bla Bla
BlaBla BlaBla **_Some text to be markedSome text to be marked_** More Bla Bla
BlaBla BlaBla BlaBla BlaBla BlaBla BlaBla BlaBla BlaBla BlaBla More Bla Bla More Bla Bla

### Actual Behavior
Now only possible by Alt-Mouse Click / Move

**Comment by dail8859** [comment]
Use `Ctrl+Alt` instead of just `Alt`.
