### ISSUE TITLE
Update Notepad++ button is broken

### ISSUE THREAD

**Issue by EMostafaAli** [notepad-plus-plus/notepad-plus-plus#3424]
### Description of the Issue

Recently, I noticed that "Update Notepad++" button always says "No update is available" even if a newer version has been released
### Steps to Reproduce the Issue

1. Use an old version (say v7.4.1)
2. Go to ? => Update Notepad++

### Expected Behavior

Update for the newer version (currently 7.4.2)
### Actual Behavior

A message box says "No update is available"
### Debug Information

Notepad++ v7.4.1   (64-bit)
Build time : May 18 2017 - 02:02:28
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10 (64-bit)
Plugins : mimeTools.dll NppConverter.dll 

![image](https://user-images.githubusercontent.com/11354102/27347758-f127340c-55ae-11e7-95fe-f657929cc00d.png)

**Comment by dail8859** [comment]
Quote from the [Notepad++ website](https://notepad-plus-plus.org/news/notepad-7.4.2-released.html):

> Auto-updater will be triggered in few days if there's no critical issue found.
