### ISSUE TITLE
Windows installer: Per user install (feature request)

### ISSUE THREAD

**Issue by doodadjs** [notepad-plus-plus/notepad-plus-plus#3425]
### Description of the Issue
Notepad++ always requires Administrative privileges to install/update and I personally find it dangerous.

### Steps to Reproduce the Issue
Install Notepad++ on Windows, or update Notepad++, or install/update one of its addons.

### Expected Behavior
No administrative privileges required.

### Actual Behavior
Requires administrative privileges.

### Debug Information

N/A

N/A

**Comment by MetaChuh** [comment]
an installation will always need elevated rights.
for user level usage, please use the portable zip versions of notepad++

thank you for your help and best regards.
