### ISSUE TITLE
Some files look empty when opened in NPP even though they are not

### ISSUE THREAD

**Issue by KOLANICH** [notepad-plus-plus/notepad-plus-plus#3428]
Today I have opened a file in NPP, it looked empty (yes, looked the same a new completely empty file looks: a single emply line and it also looked empty in hex-editor plugin). But the file was not empty. I have done some research with slicing the file and found that this effect is ***sometimes*** caused by ```0xF9 0xFX``` sequences of bytes present in a file where ```X``` is a hex digit from the set ```{0, 2, 4, 7, 8, 9, A}```.

**Comment by KOLANICH** [comment]
@donho

**Comment by alankilborn** [comment]
@KOLANICH Still an important issue to you?
If not, suggest CLOSING.

**Comment by ArkadiuszMichalski** [comment]
If this is still a problem, let me know. I will reopen.

**Comment by KOLANICH** [comment]
>Still an important issue to you?

No, I have stopped using NPP because Wine is explicitly unsupported.
