### ISSUE TITLE
Notepad++ (ver.: 6.7.8.2) functionlist. Commentaries between head and body dissfunction

### ISSUE THREAD

**Issue by Chrissstrahl** [notepad-plus-plus/notepad-plus-plus#344]
The function list does NOT list a function, if there is a commentary between the function Head and the function Body, as shown bellow.

void main()
//------- commentary here
{
}

I have tried several approaches with the regular expression in a new UDL but they do not change this issue. I have been told that it might be a bug and that it can be circumvented by placing at least 2 withe spaces before the comment starts.

**Comment by Rikk** [comment]
Although I also see it as a bug,
what an uncommon place to place a comment!

If I write it like this:
```cpp
void main()
// This would make the open brace be commented out: {
	//failed-func-body
}
```

```cpp
void main()
/* This looks better */ {
	//func-body
}
```

```cpp
void main()
// In this case I should not forget to start a new line...
{
	//func-body
}
```

**Comment by Chrissstrahl** [comment]
Well, game developers tend to do funky things, you should see some of the comments in the scripts or game c++ code. I suppose it helps to release the pressure they are under. I this case it was done to have descriptions for each function in Visual Studio 6 or something alike.

**Comment by GitMensch** [comment]
Quoting @MAPJe71 from Gitter:
> This was my answer @Chrissstrahl:

```xml
      <parser 
          id         ="stef2_morpheurs_script" 
          displayName="stef2_morpheurs_script" 
          commentExpr="(/\*.*?\*/)|(//.*?$)"
        >
        <function
            mainExpr   ="^[\t ]*(?'FUNCTYPE'(?-i:entity|float|string|vector|void)\s+)(?'FUNCNAME'(?!(?-i:if|while|for)\b)[A-Za-z_]\w*)\s*(?'FUNCARGS'\([^()]*\))[^\r\n;]*(?'EOL'\r?\n|\r)"
            displayMode="$functionName"
          >
          <functionName>
            <nameExpr expr="(?'FUNCNAME'(?!(?-i:if|while|for)\b)[A-Za-z_]\w*)\s*(?'FUNCARGS'\([^()]*\))"/>
            <!-- comment out the following node to display the method with its parameters -->
            <nameExpr expr="[A-Za-z_]\w*"/>
          </functionName>
        </function>
      </parser>
```

However, current FunctionList implementation has a problem with comment boundaries. Single-line comments should be preceded by an empty line and inline comments should be preceded by at least 2 spaces.
The following function will not be listed:

```c
void facilityEntraceTunnel()
//open the fence to allow player entering the duct
{
    ... body ...
}
```

but write it like this

```c
void facilityEntraceTunnel()

//open the fence to allow player entering the duct
{
    ... body ...
}
```

or like this

```c
void facilityEntraceTunnel()
  //open the fence to allow player entering the duct
{
    ... body ...
}
```

and the function will be listed.

This issue is solved in my FunctionList improvements patch (#548) on SourceForge.
However, I'm not able to check whether it still builds (stuck on VS2010) with present source in the GitHub repository. So no PR for the patch yet.

**Comment by MAPJe71** [comment]
[FunctionList improvement patch (#548)](https://sourceforge.net/p/notepad-plus/patches/548/)

**Comment by ian1632** [comment]
Still an issue in 6.8.

**Comment by RussellBai** [comment]
Still an issue in 7.5.1

**Comment by MetaChuh** [comment]
closed as less active duplicate to https://github.com/notepad-plus-plus/notepad-plus-plus/issues/4094

**Comment by GitMensch** [comment]
@MetaChuh : please reopen and close #4094 instead as this issue:

* is older
* has more discussion
* even has patches available

Thank you.
