### ISSUE TITLE
Upgrade pbm with Plugin Manager

### ISSUE THREAD

**Issue by sutnor** [notepad-plus-plus/notepad-plus-plus#3443]
### Description of the Issue
I was prompted to upgrade Notepad++, so I did - to v7.4.2.  After the upgrade, my Hex Editor plugin had disappeared, so I opened the Plugin Manager, which also wanted to be upgraded, so I clicked the necessary buttons and upgraded it.  In order to complete, it wanted to restart NPP, and did, but then I still wanted my Hex Editor, so I opened Plugin Manager again, and again, it wanted to be upgraded.  I repeated this loop four times in case there were incremental upgrades each time, but it became apparent that it was simply stuck in a loop - upgrade, restart NPP, open Plugin Mgr, upgrade, restart, etc.

### Steps to Reproduce the Issue

1. OS : Windows-7 SP1 
2. PC : Fujitsu Lifebook 64, Intel Core i3
3. I have not yet rebooted the PC, but at the moment, I am unable NOT to reproduce the issue.

### Expected Behavior
I expected plugin manager to be happy with its first upgrade after restarting NPP.

### Actual Behavior
As explained above

### Debug Information
n/a

**Comment by dail8859** [comment]
This needs reported to the plugin manager project.

See this issue https://github.com/bruderstein/nppPluginManager/issues/45
