### ISSUE TITLE
Crashes regularly (but the file is large - 16MB)

### ISSUE THREAD

**Issue by ggthomason** [notepad-plus-plus/notepad-plus-plus#3444]
### Description of the Issue

Notepad++ first shows LF characters is white on black on half the screen, then on further editing, it crashes and stops working. This has been happening for well over a year with many previous versions.. I am currently on 7.4.1. With each new update I had hoped that this would have been fixed ...

### Steps to Reproduce the Issue

1. It just happens as I edit. Admittedly the file is large (16MB). It may be possible to reproduce it by giving it work to do while it is working (e.g. searching).
2.  I am almost certain it is a threading issue. I hope you understand semapahores  are the key to writing multi-threaded applications. It is no good just testing whether a thread is active as the information is instantly out of date. And polling for information on another thread is bad practice. Use message sequence diagrams to get the design right, with semaphores to wait on a thread as necessary. Never assume the probability of a window of vulnerability is low - it never works out like that. Get the design right and watertight,
3. 

### Debug Information

I have a screenshot
![nplpl](https://user-images.githubusercontent.com/29690749/27517182-fa1b33fa-59bf-11e7-8a8b-5725635b60d1.jpg)

**Comment by dail8859** [comment]
Try turning off periodic backups to see if that helps.

**Comment by ggthomason** [comment]
I've turned periodic backups and it hasn't crashed since then (and I have used it quite a lot). Thanks for the suggestion.
