### ISSUE TITLE
Getting the CRLF and LF chars at random moments. 

### ISSUE THREAD

**Issue by janthonyl** [notepad-plus-plus/notepad-plus-plus#3446]
Been using Notepad++ for years but not as a power user, I just take notes trying to educate myself on various topics. Most of of my note files are less than 500 KB but some as high as 5 MB. 

Just got a new machine with Windows 10 pro. I'm running the latest Notepad++  ( don't see Help > About for the version#). Seemingly at random, while I'm typing (this has probably happened 100 times now so I'm likely to abandon Notepad ++ or rollback), the CRLF and LF appear  starting from the line below the cursor and running down to the bottom of the document (none of that exists above the cursor even if I am midway through the document). This has nothing to do with the paragraph-option on the toolbar (doesn't fix it) or the Show Symobol options (those aren't turned on). I have to close the document and reopen to return to normal. 

I wish I knew how to reproduce it but I can't figure out the exact sequence of keystrokes that trigger it.  As far as I can see, I'm just typing regular sentences with periods and quote marks, no special chars, when it happens.

**Comment by dail8859** [comment]
In cases where uses report files getting corrupted with mixed CRLF and LF is normally due having periodic backups enabled. Try turning those off and see if it helps solve the issue.

**Comment by janthonyl** [comment]
I went to Settings > Preferences > Backup and unchecked that option. Needs more testing but seems to be working. Thank you!
