### ISSUE TITLE
Better tail

### ISSUE THREAD

**Issue by pacionet** [notepad-plus-plus/notepad-plus-plus#3448]
I am using Notepad++ 7.3.3 on Windows 7 and I notice that "tail" doesn't work properly.
If I opened 2 o 3 log files (which are on remote Windows servers) every time the file is reloaded I have to wait several seconds (20-30 seconds) to see the updates: in such interval notepad++ is "hang"
Can you handle better the tail feature?

**Comment by donho** [comment]
Use monitoring feature.
