### ISSUE TITLE
7.4.2 cert error "Authenticode check failed"

### ISSUE THREAD

**Issue by punknubbins** [notepad-plus-plus/notepad-plus-plus#3449]
### Description of the Issue
NP++ 7.4.2 fails to load after update. Giving "Authenticode check failed" error message.

### Steps to Reproduce the Issue

1. Installed https://notepad-plus-plus.org/repository/7.x/7.4.2/npp.7.4.2.Installer.exe as of 6/27/2017 ~10:00AM CDT
2. unable to launch NP++

### Debug Information

Reinstalling 7.3.3 resolves the issue.

**Comment by kmonson** [comment]
I'm having the same problem. Rolling back to 7.3.3 resolves the issue.

Running in Windows 7 Pro.

**Comment by jaycuse** [comment]
Having same issue with both x86 and x64 on Win 7 Pro.

**Comment by MetaChuh** [comment]
this behaviour is not reproducible on newer versions of notepad++.

please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins if you update from version 7.5.9 or below.

thank you for your help and best regards.
