### ISSUE TITLE
Highlighted text in tabs

### ISSUE THREAD

**Issue by dminion909** [notepad-plus-plus/notepad-plus-plus#345]
Hi,

I'll start out by saying that I love Notepad ++ and will never use another text editor again. Thank you for all you do.

I typically have about 10 different tabs open with text that I copy to paste in other locations. I would open N++ and all the text would already be highlighted as it was when I closed it. Unfortunately, this doesn't happen anymore. If I highlight text on a tab and then switch to another tab and back again, the text is no longer highlighted.

Can you fix this please?

Thanks!

**Comment by jonandr** [comment]
Seems to work for me. Are you running any plugins? Try renaming C:\Program Files (x86)\Notepad++\plugins to something else temporarily, restarting N++ and seeing if the problem still remains.

**Comment by dminion909** [comment]
I removed all plugins. I found that the XML plugin was the issue.

Thanks!

**Comment by dail8859** [comment]
Also see #331. It seems lately XML Tools doesn't play nice with the newer versions of N++ for some reason. Try disabling "Set XML type automatically".
