### ISSUE TITLE
Language meniu is too long

### ISSUE THREAD

**Issue by savornicesei** [notepad-plus-plus/notepad-plus-plus#3454]
The language meniu is too long and it breaks UX. 
It would be nicer if the menu would be displayed on 2-3 columns such that scrolling up and down would not be required.

![npp_01](https://user-images.githubusercontent.com/917232/27680589-ea973624-5cc4-11e7-9485-8ea4a89f1a3b.png)

**Comment by dinkumoil** [comment]
You can use the option "Make language menu compact" to reduce the size of this menu:

![grafik](https://user-images.githubusercontent.com/24699812/27706956-e40ffe5e-5d13-11e7-9b87-117a0be8edd7.png)

**Comment by savornicesei** [comment]
Didn't know about that setting. Yes, it's exactly what I wanted
