### ISSUE TITLE
BuildBoost.bat fails to set BOOSTPATH if toolset flag is used

### ISSUE THREAD

**Issue by Gusgus01** [notepad-plus-plus/notepad-plus-plus#3455]
### Description of the Issue

When you utilize the --toolset flag on the BuildBoost.bat, the batch script fails to set the BOOSTPATH. This causes the script to fail.

### Steps to Reproduce the Issue

1. Follow the README steps up to "To Build SciLexer.dll with Boost"
2. Use the --toolset flag while trying to build boost e.g. BuildBoost.bat --toolset mvsc-12.0 C:\sources\boost_1_55_0 -x64

### Expected Behavior

The BuildBoost.bat script to utilize the toolset I selected and build boost. 

### Actual Behavior

The script echoed the USAGE block explaining how to format the command.

**Comment by ArkadiuszMichalski** [comment]
Outdated issue.
