### ISSUE TITLE
Maximized window extends onto second monitor

### ISSUE THREAD

**Issue by Germs2004** [notepad-plus-plus/notepad-plus-plus#3457]
### Description of the Issue
When I maximize the Notepad++ window, I notice a thin white vertical line on the left edge of my second monitor.  Apparently, it's the right edge of the Notepad++ window.  It goes away when I minimize or move the Notepad++ window.  It seems that the Notepad++ window has a too-thick border or something.  It's distracting to see the white line on my second monitor.

### Steps to Reproduce the Issue
1. On a computer with two monitors in "extend mode," open Notepad++ on the primary monitor
2. Maximize the window if it's not already maximized
3. Notice that a slim part of Notepad++ extends onto the secondary monitor

### Expected Behavior
Notepad++ should behave like all other Windows programs.  When maximized, it should fill the active monitor but not be visible at all on other monitors.

### Actual Behavior
Notepad++ appears on multiple monitors when maximized.

### Debug Information
Notepad++ v7.4.2   (32-bit)
Build time : Jun 18 2017 - 23:34:19
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10 (64-bit)
Plugins : mimeTools.dll NppConverter.dll NppExport.dll NppFTP.dll PluginManager.dll 

![screenshot1](https://user-images.githubusercontent.com/5519340/27708221-2e14c832-5ce6-11e7-96be-adaae51fba03.png)
![screenshot2](https://user-images.githubusercontent.com/5519340/27708222-2e17fa70-5ce6-11e7-94f0-e3da86bb03cc.png)

**Comment by MetaChuh** [comment]
i can not reproduce this on notepad++ 7.6.6 on windows 10 build 1809.

please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins if you update from version 7.5.9 or below.

if your maximised window still overlaps the bordering display by one or more pixels, please right click on your notepad++ icon and select `properties > compatibility > change high dpi settings`, activate `override high dpi scaling behavior` and set `scaling performed by:` to `system (enhanced)`, as seen at the screenshot below.

![Imgur](https://i.imgur.com/qVQ4Bg8.png)

you can also choose the `system` scaler, for a classic notepad++ look on scaled displays, which will look like this:

![Imgur](https://i.imgur.com/WqSSpUo.png)

note: it is recommended to disable smooth font for the classic scaler look, by going to `settings > preferences > editing` and unchecking `enable smooth font` in notepad++, if it is enabled as seen at the screenshot below.

![Imgur](https://i.imgur.com/vFFvIOR.png)

thank you for your help and best regards.

-----
```
general notes:

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
(no extra account is needed, just use your github account to sign in)
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)
