### ISSUE TITLE
can't show UFT-8 character

### ISSUE THREAD

**Issue by Subfire** [notepad-plus-plus/notepad-plus-plus#3458]
can't show some  UFT-8 character, like "✓"

![image](https://user-images.githubusercontent.com/16792880/27723841-8ce533ae-5da1-11e7-9c73-4a3f4d3aec13.png)

**Comment by MetaChuh** [comment]
please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins if you update from version 7.5.9 or below.
if your issue still persists, and it is still of relevance, please feel free to file a new issue as easy to understand and reproducible as possible.

thank you for your help and best regards.
