### ISSUE TITLE
Session and settings are lost after Windows restart

### ISSUE THREAD

**Issue by ygoe** [notepad-plus-plus/notepad-plus-plus#3459]
### Description of the Issue
Notepad++ is configured to remember the last session (opened documents). This works fine when quitting and restarting Notepad++. But afte a Windows restart, everything is lost. No documents are open and the recently opened documents list in the File menu also doesn't contain the recently opened documents. It's as if a disk virtualisation would be reset to its initial state. Which of course is not the case because everything else is there just like before.

This started to happen with the update from 7.3.3 to 7.4.2. I'm now back on the old version.

### Debug Information
Notepad++ v7.3.3   (32-bit)
Build time : Mar  8 2017 - 03:37:37
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 7 (64-bit)
Plugins : mimeTools.dll NppConverter.dll NppExport.dll NppFTP.dll PluginManager.dll

**Comment by irgendsontyp** [comment]
As far as I can see, Notepad++'s default file for storing session information is %APPDATA%\Notepad++\session.xml. Can you verify that the contents of this file are the same after restarting Windows?

**Comment by ygoe** [comment]
That file is gone after restarting Windows. Still with the old version. Is that a temporary file that is not backed to disk but only resides in memory?

**Comment by ygoe** [comment]
Oh my, our administrator has inadvertently changed the CCleaner configuration and that tool wants to delete that file by default. Pretty aggressive.

**Comment by klepsydra** [comment]
This is still a problem.   NPP 7.8.2 32bit

Microsoft Windows 10 Pro x64
10.0.18362 N/A Build 18362

**Comment by ygoe** [comment]
@klepsydra Then it's probably a new issue that will be hard to handle in this entry.

**Comment by donho** [comment]
Fix by https://github.com/notepad-plus-plus/notepad-plus-plus/commit/6000f3bb21a42a4d28d068617e0dc642ef739b26
