### ISSUE TITLE
關於自動換行有bug啊!

### ISSUE THREAD

**Issue by HuJK** [notepad-plus-plus/notepad-plus-plus#3460]
如果啟用自動換行，當「字元數超過螢幕寬and行首有空格」，第二行開頭也會被補上空白。
![image](https://user-images.githubusercontent.com/15907444/27726993-44fe50a8-5daf-11e7-9f15-25108b7888d2.png)

如果是中文，會更奇怪。我只有在行首打上空白，它卻幫我自動換行，如圖所示
![image](https://user-images.githubusercontent.com/15907444/27727323-9d9a7d1c-5db0-11e7-9c7f-94cc8067920b.png)

**Comment by emedws** [comment]
Go to Settings > Preferences > Editing > Line Wrap, and switch to default

**Comment by HuJK** [comment]
Most text editor will avoid split a single word to 2 different lines.
For example:
![image](https://user-images.githubusercontent.com/15907444/27766862-3609f24a-5f13-11e7-8eb8-6cc2ae205d31.png)

If we have a long words,It will looks like this:
![image](https://user-images.githubusercontent.com/15907444/27766870-621ce874-5f13-11e7-9511-b8c76b361fd8.png)

But Chinese don't need it!
Because Chinese have not space between word and word!
![image](https://user-images.githubusercontent.com/15907444/27766874-7fe64314-5f13-11e7-9065-d0d749182833.png)

If we write a Chinese sentence,Notepad++ will see it as a single words,and try to put it in a single line.

I think Notepad++ should detect if the language is Chinese,then disable the function.

Not only Chinese,but also Japanese,Korean and any language not split words with space.

**Comment by HuJK** [comment]
Same as https://github.com/notepad-plus-plus/notepad-plus-plus/issues/5524
