### ISSUE TITLE
Display 125% scale issue

### ISSUE THREAD

**Issue by k0st1x** [notepad-plus-plus/notepad-plus-plus#3462]
### Description of the Issue
my notebook monitor has 125% scaling and notepad++ on monitor has glitches

### Actual Behavior
screenshot shows the blur
![2017-06-30_1427](https://user-images.githubusercontent.com/1209649/27734180-5b0be7d2-5da2-11e7-894b-63f6672007a8.png)
and the [video](https://www.screencast.com/t/rkOlysCtWY) shows animated closing tag :)

**Comment by MetaChuh** [comment]
please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins if you update from version 7.5.9 or below.
if your issue still persists, and it is still of relevance, please feel free to file a new issue as easy to understand and reproducible as possible.

thank you for your help and best regards.
