### ISSUE TITLE
Project for visual Studio 2017

### ISSUE THREAD

**Issue by tarung65** [notepad-plus-plus/notepad-plus-plus#3467]
### Description of the Issue
Unable to Build project in Visual Studio 2017 

### Steps to Reproduce the Issue

1. Open notepadPlus.vs2015.vcxproj in visual Studio 2017
2. Build the project
3. Compilation failed

### Expected Behavior

A new project to be created for Visual studio 2017

**Comment by irgendsontyp** [comment]
As a workaround, which works for me, you can modify the notepadPlus.vs2015.vcxproj by changing "v140_xp" to "v141" and then try again.

**Comment by bahusoid** [comment]
If the only thing that needs to be changed is  "Platform Toolset" then I think separate project is an overkill for VS 2017. I think it's better to adjust existing vs2015 project to calculate proper "Platform Toolset". I don't have VS 2017 but I prepared prototype for such project:

[notepadPlus.vs2015.vcxproj.zip](https://github.com/notepad-plus-plus/notepad-plus-plus/files/1122331/notepadPlus.vs2015.vcxproj.zip)

Could you please check if it works with VS 2017?

**Comment by tarung65** [comment]
But as the newer version of visual studio is rolling out it is always better to switch to that and community version of Visual Studio 2017 is free so why we are using its older version.It is always better to upgrade to the latest tools.

**Comment by bahusoid** [comment]
I'm not saying that you shouldn't use it. But why to force it? Adding additional solution is additional burden to support. And what the benefits?

**Comment by tarung65** [comment]
if that is the reason then the older version of project also should be removed

**Comment by bahusoid** [comment]
If for VS 2013  it's also only about "Platform Toolset" - it's easy doable too. Could you please confirm that my changes work with VS 2017?

**Comment by tarung65** [comment]
Yes, your changes works but we have to ignore warnings.

**Comment by bahusoid** [comment]
Ok. Thanks. If I understand correctly build is failing due to warnings (so you need to disable Treat Warnings as Error flag) That's actually a no go. I will check how can I make it build without warnings.

**Comment by dail8859** [comment]
Closing as it is now buildable with VS2017

**Comment by chcg** [comment]
See https://github.com/notepad-plus-plus/notepad-plus-plus/pull/5306 for compilation issues with platform toolset of VS2017 v141 or v141_xp.
