### ISSUE TITLE
German search dialog next button translation fails to be consistent

### ISSUE THREAD

**Issue by ophian** [notepad-plus-plus/notepad-plus-plus#3474]
NPP 7.4.2
See attached file for behaviour

![npp-7 4 2-search-dialog-de](https://user-images.githubusercontent.com/1105372/27784532-b62db82c-5fda-11e7-82c7-0b03748e8f15.png)

I think <<Finde | Finde>>, or <<Suche | Suche>>, or even untranslated would be just fine.
Thanks

**Comment by arctic-blue** [comment]
>> fwd    &   << rwd    should be international. no need to translate it

**Comment by schnurlos** [comment]
https://github.com/notepad-plus-plus/notepad-plus-plus/pull/3471

**Comment by dinkumoil** [comment]
Seems to be reverted. See 4d921b7
