### ISSUE TITLE
User-defined language highlighting

### ISSUE THREAD

**Issue by bReathl3sS** [notepad-plus-plus/notepad-plus-plus#3475]
Hi there,
the following bug occured for me:

### Description of the Issue
I created a user defined language and set specific file extensions (like .log) to be set to the user defined language by default. Whenever I drag a file which uses this user defined language by default out of np++ to open in a new np++ window, the language is set back to default (no highlighting at all). When I drag the file from the other np++ instance back to the main np++ instance, it gets highlighted again in the correct user defined language

### Steps to Reproduce the Issue
1. Create User defined language, set some highlighting there, set a default file extension like 'test'
2. Create a file with the 'test' extension, fill it with some highlighting, open with np++
3. You'll see the correct highlighting
4. Drag that file out of the main np++ instance, e.g. to desktop --> a new np++ instance will be opened
5. No highlightin in new np++ instance
6. Drag back to main np++ instance, highlighted again.

### Expected Behavior
I expected that highlighting will stay the same when I drag a file out to a new instance. This is also the default for standard languages like 'bat'-files and so on.

### Actual Behavior
For files opened with a user-defined language highlighter, the language is set back to default when dragging out to a new np++ instance.

### Debug Information
Notepad++ v7.4.2   (64-bit)
Build time : Jun 18 2017 - 23:38:43
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 7 (64-bit)
Plugins : mimeTools.dll NppConverter.dll

**Comment by dinkumoil** [comment]
Seems to be the same like #3451

**Comment by ArkadiuszMichalski** [comment]
@sasumner This is duplicate to https://github.com/notepad-plus-plus/notepad-plus-plus/issues/3451, as mention above.
