### ISSUE TITLE
Same description in tooltip on new search window(Next and Prev buttons)

### ISSUE THREAD

**Issue by Oplkill** [notepad-plus-plus/notepad-plus-plus#3476]
### Description of the Issue

In updated Search dialog window, tooltips of NextButton and PreviosButton are the same, but they should be different 

### Steps to Reproduce the Issue

Just see tooltips of NextButton and PrevButton, in SearchDialogWindow

### Expected Behavior

Should be writted "...Ctrl+Enter..." in NextButton tooltip

### Actual Behavior

They have the same descriptions

http://i.imgur.com/FXgysln.png
http://i.imgur.com/5R4fbjE.png

**Comment by tarung65** [comment]
The tool tip provided is wrong.Shift+ Enter is used only to switch the direction of Search .If we are searching in forward direction Shift+ Enter switches the direction of search to Backward direction and if we are searching in for Backward Direction it will switches the search direction to forward.

**Comment by ArkadiuszMichalski** [comment]
Out of date.
