### ISSUE TITLE
Indicate file encoding if not default encoding

### ISSUE THREAD

**Issue by buechner-4m** [notepad-plus-plus/notepad-plus-plus#3480]
### Description of the Issue
Actually I don't have an indicator how the opened file is encoded. 

### Steps to Reproduce the Issue
1. Create a new file in windows explorer
2. Open the file in Notepad++ and you got an ANSI encoded file 
3. This often results in character errors in large projects as the new file has a different encoding than the rest of the project (Most likely all the )

### Expected Behavior
Visual Indicator when not default encoding (p.e. A bar on top of the editing area that indicates the current encoding)

### Actual Behavior
You have to open the Encoding menu to inspect the current file encoding

**Comment by dinkumoil** [comment]
If you activate the status bar of the Notepad++ window

![grafik](https://user-images.githubusercontent.com/24699812/27819101-f2d8a82c-6098-11e7-83b1-2bf6c6a007f5.png)

 you will get the indicator you want:

![grafik](https://user-images.githubusercontent.com/24699812/27819120-04a4aeca-6099-11e7-8365-f707cc638b76.png)
