### ISSUE TITLE
The text for Find Next doesn't fit in button in Russian localization

### ISSUE THREAD

**Issue by Vorvule** [notepad-plus-plus/notepad-plus-plus#3481]
### Steps to Reproduce the Issue

1. Install russian version of NP++;
2. Press Ctrl+F.

### Actual Behavior

![default](https://user-images.githubusercontent.com/25710018/27821234-3cc7a01c-60aa-11e7-9812-79a5a40d09f9.png)

**Comment by ElpyDE** [comment]
Same for German...

![npp-search-7 4 2](https://user-images.githubusercontent.com/13076019/27841996-f6571142-6105-11e7-8421-8c9446d37148.png)

**Comment by nymos85** [comment]
Same for Italian

![cattura](https://user-images.githubusercontent.com/30112460/28112093-0e5a96e0-66f8-11e7-974e-d681af86a08b.JPG)

Moreover the tooltip that appears on both buttons is the same, and the "Shift+Enter" combination suggested only works for the "<<Find" button.

**Comment by schnurlos** [comment]
As this translation text in english is introduced here https://github.com/notepad-plus-plus/notepad-plus-plus/commit/fb998007d7eaff074d990ff528026f94f21aeafc the first time, updated here https://github.com/notepad-plus-plus/notepad-plus-plus/commit/f162181fba03d8e456d3369b97facc96152e1233 this reflects to ALL languages. The translators have to fix or update that and then you have to wait for the rollout.

**Comment by dinkumoil** [comment]
Seems to be reverted. See 4d921b7
