### ISSUE TITLE
Crash when clicking "Remove unmarked lines"

### ISSUE THREAD

**Issue by crypto-rsa** [notepad-plus-plus/notepad-plus-plus#3482]
### Description of the Issue
Notepad++ crashes when removing unmarked lines in a large file (or trying to undo this action).

### Steps to Reproduce the Issue

1. Open the text of [Pride and Prejudice](https://www.gutenberg.org/files/1342/1342-0.txt)
2. Open the Find window, go to the Mark tab
3. Type *Bingley* in the search box
4. Make sure the `Bookmark line` checkbox is checked
5. Click `Mark All`
6. Click Search - Bookmark - Remove Unmarked lines

### Expected Behavior

Only the lines containing the search term should be visible.

### Actual Behavior

Notepad++ crashes. Sometimes it does produce the desired output, but reliably crashes when I click Undo after that.

### Debug Information

Notepad++ v7.4.1   (32-bit)
Build time : May 18 2017 - 02:00:37
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10 (64-bit)
Plugins : ComparePlugin.dll HTMLTag_unicode.dll LocationNavigate.dll mimeTools.dll NppColumnSort.dll NppConverter.dll NppExport.dll NppFTP.dll NppTextFX.dll NppToolBucket.dll PluginManager.dll PythonScript.dll XmlNavigator.dll XMLTools.dll

**Comment by SinghRajenM** [comment]
Could not reproduce.
Please check this issue after disabling all the plugin. You can disable plugin just by renaming folder "plugins" in path "%programfiles(x86)%\Notepad++". It can be re-enable just by undo rename.

**Comment by kkayal** [comment]
Just to add my test results. I hope it helps:

I tested the procedure above. It worked as expected including the undo. No crashes in my case.

My configuration:

Notepad++ v7.3.2   (32-bit)
Build time : Feb 12 2017 - 23:15:39
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 7 (64-bit)
Plugins : ccc.dll CodeAlignmentNpp.dll FingerText.dll HTMLTag_unicode.dll mimeTools.dll NppConverter.dll NppExport.dll NppTextFX.dll PluginManager.dll PoorMansTSqlFormatterNppPlugin.dll SpellChecker.dll sql.dll Tidy2.dll XMLTools.dll 

Encoding UTF-8
Language: Normal text

**Comment by crypto-rsa** [comment]
@SinghRajenM You're right, I found out the crash occurs in the [Location Navigate](https://sourceforge.net/projects/locationnav/files/) plugin.
