### ISSUE TITLE
File looks corrupted when replacing tabs immediately after open

### ISSUE THREAD

**Issue by vdeconinck** [notepad-plus-plus/notepad-plus-plus#3485]
### Description of the Issue
When opening a big file and removing all tabs by replacing the extended char '\t' by an empty string, the file display gets garbled half way.

### Steps to Reproduce the Issue
1. Open a big file containing lots of tab characters (e.g. file in attached zip)
2. Immediately replace (CTRL-H) the tab char (\t) by nothing, with the "Extended char" option checked
3. Scroll down the file

### Expected Behavior
The file should remain the same, with only the tabs removed.

### Actual Behavior
Half way through the file, the file looks corrupted, with wrong line wrap and CR LF appearing in the middle of lines. See this video: https://www.screencast.com/t/Y3TDDlNj

### Debug Information
(Err, I have no Debug Info under under the "?" menu...)

More info:
- the file does not seem to really be corrupt if you save and reopen it, only the display is.
- this only seem to happen if the file and/or number of tabs is large
- sometimes, if you first scroll through the file (probably initializing enough buffer memory), then the bug doesn't seem to trigger

[sample_notepad++_bug_cannot_replace_tab_by_empty4.zip](https://github.com/notepad-plus-plus/notepad-plus-plus/files/1122093/sample_notepad._bug_cannot_replace_tab_by_empty4.zip)

**Comment by MetaChuh** [comment]
many thanks for your test file, and sorry for the very late response.

i can not reproduce this on notepad++ 7.6.6 using your test file and replacing all tabs with an empty string immediately after loading the file, without previously scrolling down, as seen at the screencast below:

![#3485 7 6 6  tab rebplace ok](https://user-images.githubusercontent.com/45773305/57294983-a1fd9a00-70c9-11e9-8027-0d4baef63662.gif)

if you are still using an older version of notepad++, which might show this behaviour, please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins if you update from version 7.5.9 or below. for larger file support up to 2gb, please uninstall any 32 bit versions of notepad++ and choose the newest 64 bit version.

thank you for your help and best regards.

**Comment by sasumner** [comment]
@vdeconinck Please check your _Backup_ settings, set to _None_ if it is not already, and try your problem case again.

**Comment by vdeconinck** [comment]
Hi. I can't reproduce the bug anymore with 7.6.6, so I guess it's fixed :-)
