### ISSUE TITLE
Please incorporate hex editor functionality into notepad++

### ISSUE THREAD

**Issue by GunAlm** [notepad-plus-plus/notepad-plus-plus#3489]
### Description of the Issue
The Hex editor plugin have been available for years but for every new notepad++ version it gets' disabled and I have to "reinstall" it. Could you please incorporate the hex edit functionality into notepad++ so I don't need to reinstall every time.

**Comment by kkayal** [comment]
In my opinion, it would be better to keep this functionality as a plugin and not to incorporate it as a built-in feature. For hex editing, there are excellent dedicated freeware programs. I use HxD frequently.

The attempt to incorporate such specific functionality in a general purpose text editor would increase the size of the executable, which would increase the time it takes to launch the editor. I personally really appreciate how quick this editor starts.

It would also introduce the risk that hundreds of new bugs and feature requests related to it would be added. By looking at the pull requests here at github, the developers seem to be more focused on fixing bugs related to the core functionalities. I appreciate that too.

**Comment by integritysphere** [comment]
Can you make it not go to disabled after each update? It is annoying. I haven't seen any stability issues with this plugin yet.

**Comment by MetaChuh** [comment]
the hex editor plugin is no longer removed by the current versions of notepad++, beginning with 7.6.
e.g. if you update from 7.6.4 to 7.6.6, a hexeditor.dll at the new plugin folder structure will not be moved to disabled.

note: this might change in the future, if plugin issues arise.

many thanks and best regards.
