### ISSUE TITLE
New tabs are ignoring the style configuration theme

### ISSUE THREAD

**Issue by luiscla27** [notepad-plus-plus/notepad-plus-plus#3490]
### Description of the Issue
New tabs are ignoring the style configuration theme, it seems to be related to the "Default language" configuration.

Plugin http://www.sqlinform.com/download-free-notepad-plugin/ needs to be installed for this issue to happen.

### Steps to Reproduce the Issue
1. Go to the menu \ Settings \ Style configuratior \
2. Select a different theme, then Save & Close
3. Go to the menu \ Settings \ Preferences \ New Document
4. Select SQL as defaul language and press Close
5. Add a new TAB and write some SQL query string...
6. Close NPP
7. Open NPP and see the TAB

### Expected Behavior
The SQL look & feel should be as specified by the selected theme at step 2

### Actual Behavior
The SQL look & feel is the factory one. I've attached a video.

[ThemeIgnoredBUG.zip](https://github.com/notepad-plus-plus/notepad-plus-plus/files/1128312/ThemeIgnoredBUG.zip)

![nppversion](https://user-images.githubusercontent.com/29953012/27918611-149774aa-6235-11e7-8eac-ce91c804f8ad.png)

**Comment by ArkadiuszMichalski** [comment]
Not reproducible on current version Notepad++ v8.4.7.
