### ISSUE TITLE
Saving to empty files fails with error suggesting there is no disk space

### ISSUE THREAD

**Issue by Elaskanator** [notepad-plus-plus/notepad-plus-plus#3491]
### Description of the Issue
When I edit an empty (existing) file with NPP, saving fails with the error "Failed to save file. Not enough space on disk to save file?"
But when I edit a non-empty file (or save from untitled) it works fine.
Also, reloading from disk when file was empty in NPP does not work and I have to manually close and reopen the file (e.g. if I clear a log file and something populates it in the background).

The only option I have changed is Preferences > MISC. > File Status Auto-Detection to enabled.

Additionally, when I task switch out of NPP after getting the above error then back to NPP, it says it detected the file content changed and asks if I want to reload from disk. The file then reverts to being empty.

### Steps to Reproduce the Issue

1.  Create an empty file (e.g. right click in Windows Explorer > New > Text Document)
2.  Open the file in NPP (either by right click > Edit with Notepad++ or dragging onto an instance of NPP)
3.  Type something
4.  Save

### Expected Behavior
File saves.

### Actual Behavior
"Failed to save file. Not enough space on disk to save file?"

### Debug Information
v7.4 x64 build time May 14 2017 - 21:02:35

Please see the attached PSR output (Problem Steps Recorder, a utility app included with Windows):
[NPP fails to save to previously empty files.zip](https://github.com/notepad-plus-plus/notepad-plus-plus/files/1128701/NPP.fails.to.save.to.previously.empty.files.zip)

**Comment by AngryGamer** [comment]
update notepad++

**Comment by Elaskanator** [comment]
I uninstalled NPP and deleted everything in its install directory under C:\Program Files then reinstalled and it's working now.

**Comment by danparsonson-if** [comment]
This appears to be happening again on build 8.4.2 (64-bit) on Windows 10, but for me only in directories managed by OneDrive. I can create and edit files there using Windows notepad, but NPP gives me the error above if I try the same thing.
