### ISSUE TITLE
Compatibility with Windows RT

### ISSUE THREAD

**Issue by mypetcow** [notepad-plus-plus/notepad-plus-plus#3497]
### Description of the Issue
Notepad++ is not compatible with Windows RT as only x86 and x64 binaries are available.

### Steps to Reproduce the Issue
1. Download the Notepad++ x86 or x64 installer
2. Double-click

### Request
Compile and make Notepad++ available with ARM support for Windows RT ( e.g. Microsoft Surface 2)

**Comment by VVelda** [comment]
Two things:
1. Windows RT is clinical dead, isn't it?
2. Notepad++ is Win32 based. Does have Windows RT Win32 API? I don't think so.

**Comment by MIvanchev** [comment]
@VVelda this is not correct, Windows RT is all about having a Win32 API on ARM. @mypetcow I guess you don't need it anymore, but I a [fork of Notepad++ compiling ARM](https://github.com/MIvanchev/notepad-plus-plus/tree/arm_build). I haven't tried it with Windows, but I use it on the Raspberry Pi with Wine daily. Also checkout [this article](https://gist.github.com/MIvanchev/14de59fa2552d315ac74c30cf1c0b01e) I recently published. Regards

**Comment by MetaChuh** [comment]
there are no plans for porting notepad++ to rt.

many thanks and best regards.
