### ISSUE TITLE
Hide Block With Comments Minor Bug JavaScript Syntax

### ISSUE THREAD

**Issue by Cpecific** [notepad-plus-plus/notepad-plus-plus#3498]
### Description of the Issue
Doesn't hide block as expected because of comments with JavaScript syntax

### Steps to Reproduce the Issue
1. Code like this:
```
function(){
	if (false){
		//if (true){
		//}
	}
	else{
	}
}
```
Or like this
```
function(){
	//if (false){
	//}
	else{
	}
}
```

2. Try hiding entire function

### Expected Behavior
Entire function should be hidden

### Actual Behavior
Only hides first 5 lines (before `else`)

**Comment by MAPJe71** [comment]
FYI these seem to work:
```JavaScript
function(){
	if (false){
		//if (true){
		// }
	}
	else{
	}
}

function(){
	//if (false){
	// }
	else{
	}
}

function(){
	if (false){
//		if (true){
//		}
	}
	else{
	}
}

function(){
//	if (false){
//	}
	else{
	}
}
```
