### ISSUE TITLE
an option to limit the context menu in windows 7 64bit

### ISSUE THREAD

**Issue by malis2007** [notepad-plus-plus/notepad-plus-plus#3502]
### Description of the Issue

Hello there,
First of all, thanks for reading <3
i would like there to be a built-in option to limit the notepad++ context menu option called: "Edit with Notepad++" that is sadly aggressively global to almost all file extensions. (i know that it could be done manually in registry, but having it built-in would be nice and is much safer)

what i want is:
1)a list of allowed file extensions inwhich this context menu could appear(so that i could customize it to my choice) e.g. .exe, .dll, .bin, .vbs, .bat, .com ...etc
2)obviously, remove this context menu from image, video and audio files..
3)an option to remove it all together from all file extensions.
Thanks for reading and your help in-advanced.

### Steps to Reproduce the Issue

1. right clicking any file with an extension
2. a context menu appear with the "Edit with Notepad++"
3. isn't removable currently(no built-in option) unless by doing it manually via registry.

### Expected Behavior

to find a built-in option to limit this context menu..
### Actual Behavior

i didn't find an option to limit it or even remove it unless by doing it manually via registry.
### Debug Information

Notepad++ v7.4.2   (32-bit)
Build time : Jun 18 2017 - 23:34:19
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 7 (64-bit)
Plugins : ComparePlugin.dll EmmetNPP.dll Explorer.dll mimeTools.dll NppConverter.dll nppcrypt.dll NppExport.dll NppFTP.dll NppTextFX.dll PluginManager.dll PythonScript.dll 

http://i.imgur.com/qD0Ui9g.png

**Comment by donho** [comment]
Such feature request is hard to implement. And people usually want to be able to edit all types of file, so this option won't be implemented.
