### ISSUE TITLE
NPP 7.4.2 Error after installation

### ISSUE THREAD

**Issue by aurum-aeolus** [notepad-plus-plus/notepad-plus-plus#3504]
### Description of the Issue

After install the program start with error in Scintilla component.

Library verification failed.
Authenticode  check failed: signature or signing certificate are not recognized.
Exception On WM_CREATE ScintillaEditView::init : SCINTILLA ERROR - Can not load the dynamic library

Win32Exception
An exception occurred. Notepad++ cannot recover and must be shut down.
The exception details are as follows:
Code: 0xC0000005
Type: Access violation
Exception address: 0x0038E4A8
[NppDump.zip](https://github.com/notepad-plus-plus/notepad-plus-plus/files/1133578/NppDump.zip)

### Steps to Reproduce the Issue

1. Install NPP 7.4.2 with default options
2. 
3. 

### Expected Behavior

Run the program normally.
### Actual Behavior

The program crash with error in Scintilla component.
### Debug Information

Debug from NPP 7.4.1

Notepad++ v7.4.1   (32-bit)
Build time : May 18 2017 - 02:00:37
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : ON
Local Conf mode : OFF
OS : Windows 7 (32-bit)
Plugins : ComparePlugin.dll mimeTools.dll NppConverter.dll NppExport.dll NppFTP.dll PluginManager.dll 

The NPP 7.4.2 create dmp file.

**Comment by IvanKostyuk** [comment]
How to resolve this issue? I did a workaround to comment `VerifySignedLibrary(sciLexerPath, SCINTILLA_SIGNER_KEY_ID, SCINTILLA_SIGNER_SUBJECT, SCINTILLA_SIGNER_DISPLAY_NAME, false, false);
` out in **ScintillaEditView.cpp**.
If this is a solution, may I provide a pull request?

**Comment by Lujaina95** [comment]
1. if you tried to debug the project and it shows to you the following message: 
   " ScintillaEditView::init : SCINTILLA ERROR can not load the dynamic library "
   this message mean that you do not have scilexer.dll after you build scilexer.dll with boost 
   so,what you have to do? 
   -you need to back to VS2017 and click on project properties to tell the linker where to look for libraries to link to.
   To access this setting:
    - right-click on the project name in the Solution Explorer window,
    - then Properties ? Linker ? General ? Additional Library Directories.
    - Enter <boost_path>\stage\lib
    - you need to change x64 to X86 which is in Visual studio because Notepad++ v7.5.4 (32-bit) it just work with x86
2. Also, you need to download SDK which you can find it at the following link:  
   https://developer.microsoft.com/en-us/windows/downloads/windows-10-sdk


these steps will be helpful for who use:
Notepad++ v7.5.4 (32-bit)
operating system x64
Windows 10
VS2017

**Comment by MetaChuh** [comment]
please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins if you update from version 7.5.9 or below.
if your issue still persists, and it is still of relevance, please feel free to file a new issue as easy to understand and reproducible as possible.

thank you for your help and best regards.
