### ISSUE TITLE
Clean up the inconsistent Windows UI style usage

### ISSUE THREAD

**Issue by arnowelzel** [notepad-plus-plus/notepad-plus-plus#3508]
### Description of the Issue

When using Notepad++ in Windows 10, the extended style WS_EX_TOOLWINDOW for dialog windows to avoid the visibility of a system menu in dialog boxes is not a good idea. Many dialog windows now don't have a frame at all and are just white boxes in front of a white editor window.

Furthermore when checking the code behind that it seems that there is really a inconsistent in combination of window styles: WS_EX_TOOLWINDOW is used nearly for all windows, most also use DS_SETFONT (why?) and so not the system fonts for dialogs are being used, but only "MS Shell Dlg" at the fixed size of 8.

Some windows use "3D" style with grey background, others don't. Some are "popup" windows, other's aren't. It's really not clear why all these mixed styles are in use.

### Steps to Reproduce the Issue

1. Open several dialog windows (e.g. "Preferences" and "Find" and "Shortcut mapper") and compare it to the design of standard Windows applications (e.g. file properties in Windows explorer or the "Run" dialog of Windows).

### Expected Behavior

Dialog windows have a consistent design and not abusing styles to hide standard UI elements like the system menu in modeless dialog windows.

### Actual Behavior

Dialog windows are designed as "toolbox window" even though they are just plain modeless windows. Some dialog windows use a grey background in Windows 10, others use a white background.

### Debug Information

Notepad++ v7.4.2   (64-bit)
Build time : Jun 18 2017 - 23:38:43
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10 (64-bit)
Plugins : mimeTools.dll NppConverter.dll 

Preferences dialog - white window in front of white editor and no border at all:

![grafik](https://user-images.githubusercontent.com/6613614/27995163-24c3b1b2-64ca-11e7-8934-7f9cda33516a.png)

Find dialog - resizable but also with status bar and tabs in front of white background:

![grafik](https://user-images.githubusercontent.com/6613614/27995165-2aae47cc-64ca-11e7-9012-cb3ed3374b7e.png)

But the shortcut mapper has a grey background and some strange font mixture of "MS Shell Dlg" and something else. But it has a proper "close" box since it one of the few dialog windows which don't use WS_EX_TOOLWINDOW:

![grafik](https://user-images.githubusercontent.com/6613614/27995166-3a92b90c-64ca-11e7-95db-e9ef8d4322a3.png)

And the "run" dialog also has a grey background:

![grafik](https://user-images.githubusercontent.com/6613614/27995172-4b5664fa-64ca-11e7-8646-84525a86e127.png)

Just for references - this is how dialog windows usually look like in Windows 10:

Modeless:

![grafik](https://user-images.githubusercontent.com/6613614/27995222-cd33e57e-64ca-11e7-901f-e9d0166f7aa2.png)

![grafik](https://user-images.githubusercontent.com/6613614/27995224-d42fc348-64ca-11e7-87de-9be98db2e175.png)

And modal:

![grafik](https://user-images.githubusercontent.com/6613614/27995228-e4a85500-64ca-11e7-93de-b21a7c4d13ee.png)

**Comment by kkayal** [comment]
@arnowelzel I guess the technical content is correct, because you seem to know the technical details. As a frequent notepad++ user, I would also appreciate some improvements to the UI.

However, if I was one of the delevopers, I would not really feel motivated to do so after reading this kind of bug report. It should be polite.

To be more constructive, I suggest to use neutral wording such as "inconsistent" instead of rather aggressive ones like "... really a mess ...". Similarily, I would replace the "... it is obvious ..." with a modest expression like "I guess" or "It seems".

Additionally, I would remove speculations about why certain implementations have been done the way they are in the first sentence. Even if it was true, it doesn't help the understanding about what is wrong. It just feels bossy and leaves a negative feeling. I would suggest to turn that kind of thought to a normal question in a later part of the bug report. I believe the chances that your bug report gets positive feedback would increase this way.

**Comment by arnowelzel** [comment]
You are right - sorry for my harsh tone here. I just changed this. When I find some time I try to clean up things a bit. My first pull request got rejected since the WS_EX_TOOLBAR was only used to hide the standard system menu icon and removing it will bring it back of course. I created this issue here so other people may contribute as well.

**Comment by thdoan** [comment]
I would like to add that the [x] close icons are inconsistent in some panels like Find and Run. Other panels like the shortcuts manager look OK though.

**Comment by arnowelzel** [comment]
@thdoan Yes - the shortcut mapper is a standard window with a system menu (which is visible when you press [Alt]+space bar). The other windows are styled as "tool window".

**Comment by mewickham** [comment]
I would like to add my vote to this, particularly the Preferences window. With no border, it blends it with white pages in the background and is more difficult to use.

**Comment by MetaChuh** [comment]
we like the "current" design.

i believe that we, as well as many notepad++ users, have reached an age, where we actually like new versions to look exactly and continuously the same way as older versions, but with new features.

many thanks and best regards.

**Comment by arnowelzel** [comment]
The current design was ok for older Windows Version up to Windows 7. But is literally broken under Windows 10 as I described, since Windows 10 does **not** show the dialog windows as older Windows versions did. So at least the "preferences" dialog window should have borders - which has to be fixed by Notepad++. This is not a matter of personal taste but more a matter of how to implement dialog windows properly.

**Comment by gurpal2000** [comment]
Nothing rude or harsh about this. Totally agree with @arnowelzel 
Let's make the product even better than it is! That's all.

**Comment by sasumner** [comment]
The big complaint in this thread seems to be a lack of borders on the Preferences window.  I can see where other things are cosmetic complaints, but a window without borders and the same color as what is behind it (e.g. an empty "new" document) is more of a real problem.  However, in my Win 10 I see no such problem with the Preferences window; this is with N++7.7:

![image](https://user-images.githubusercontent.com/30118311/58653632-223ba780-82e4-11e9-9b59-136d3385b421.png)

**Comment by gurpal2000** [comment]
Just general UI consistency. Look at that dialog and then look at the about box for example. Where's the X? Minor I know, but still.

**Comment by arnowelzel** [comment]
@sasumner there is no border. Your screenshot shows a shadow. But when you disable windows shadows, the same window is just just "white on white" without any border, as you can see here with a current version - and an application should not require certain UI effects in the OS to be activated just to be able to see the window borders:

![grafik](https://user-images.githubusercontent.com/6613614/58657060-caba2d80-831d-11e9-82a0-e34a3ef55ead.png)

**Comment by sasumner** [comment]
@arnowelzel Good point!

**Comment by mewickham** [comment]
And you have hit on the cause of the problem. If a user has "Show 
shadows under windows" deselected in Advanced System Settings> 
Performance, there is no way to tell where the Preferences window ends 
and the background window begins, because the Preferences window has no 
border.

Mike Wickham

**Comment by sasumner** [comment]
Which was what I "good point"-ed.  :)

**Comment by arnowelzel** [comment]
And just for completeness: my complaint was not only the missing border in the preferences window but the inconsistent use of window styles in general. Just see the screenshots in my original issue with different background styles, different title bar styles (some are "toolbar" windows, others are not etc.).
