### ISSUE TITLE
Bitwise-OR operator precedence in Accelerator::updateMenuItemByCommand

### ISSUE THREAD

**Issue by ariccio** [notepad-plus-plus/notepad-plus-plus#351]
As noted by `/analyze`, there's [a very concerning line of code in `Accelerator::updateMenuItemByCommand`](https://github.com/notepad-plus-plus/notepad-plus-plus/blob/master/PowerEditor/src/WinControls/shortcut/shortcut.cpp#L583):

```
    cmdFlags = MF_BYCOMMAND | (cmdFlags&MF_CHECKED) ? ( MF_CHECKED ) : ( MF_UNCHECKED );
```

...the problem is that [bitwise-or has higher precedence than the conditional-expression operator](https://msdn.microsoft.com/en-us/library/83x2a3tw.aspx), thus the function is equivalent to:

```
void Accelerator::updateMenuItemByCommand(CommandShortcut csc) {
    int cmdID = (int)csc.getID();

    //  Ensure that the menu item checks set prior to this update remain in affect.
    UINT cmdFlags = GetMenuState(_hAccelMenu, cmdID, MF_BYCOMMAND );
    cmdFlags = MF_BYCOMMAND
    if (cmdFlags&MF_CHECKED)
    {
        cmdFlags |= ( MF_CHECKED );
    }
    else
    {
        cmdFlags |= ( MF_UNCHECKED );
    }

    ::ModifyMenu(_hAccelMenu, cmdID, cmdFlags, cmdID, csc.toMenuItemString().c_str());
}
```

Is that the intended behavior? [The documentation for `ModifyMenu`](https://msdn.microsoft.com/en-us/library/windows/desktop/ms647993.aspx) says that `MF_BYCOMMAND` may be combined with `MF_CHECKED` or `MF_UNCHECKED`, so it seems so. Please clarify this in the source, something like:

```
    cmdFlags = MF_BYCOMMAND | ( (cmdFlags&MF_CHECKED) ? ( MF_CHECKED ) : ( MF_UNCHECKED ) );
```

**Comment by Rikk** [comment]
Clean more:
`cmdFlags = MF_BYCOMMAND | ( cmdFlags&MF_CHECKED ? MF_CHECKED : MF_UNCHECKED )`

**Comment by ariccio** [comment]
The parenthesis around `MF_CHECKED` and `MF_UNCHECKED are not necessary. I left them there because:

1. Mixing bitwise and ternary operators is very confusing!
2. As a (good) habit, I ensure that all usage of operators in expressions involves only *primary expressions*. This is also strongly advised in my copy of MISRA C 2012 (it's rule 12.1).
3. Parenthesis are cheap!

Otherwise, it's totally cool to drop them.

**Comment by CookiePLMonster** [comment]
It's mid-2018, this issue is still open and this line has been modified since.

Can anybody close it as resolved?

**Comment by MetaChuh** [comment]
closed due to inactivity and by request
