### ISSUE TITLE
Plugin updater 

### ISSUE THREAD

**Issue by CoR--** [notepad-plus-plus/notepad-plus-plus#3510]
### Description of the Issue

I'm using win10pro and N++ v.7.4.2 32bit

### Steps to Reproduce the Issue

1. Download new .zip N++ and extract it
2. Go to plugin manager and try to install any plugin
3. Plugin manager asks to be updated. (why if I just downloaded latest version)
4. Let it update.
5. Try to install plugin, and Plugin manager asks to be updated again... 

### Expected Behavior

I expected to have latest Plugin manager after unziping N++. 
Than I expected it to remember it's update state. 

### Actual Behavior

PM is asking to update itself constantly...

### Debug Information

May be important:
I never use installer. Always .zip portable versions.
I have two separate folders for two instances of N++ at the same time.
N++pads have different styles, and different working folders.

**Comment by chcg** [comment]
See https://notepad-plus-plus.org/community/topic/14315/notepad-7-5-release, PluginManager is no longer part of N++. https://github.com/bruderstein/nppPluginManager/issues is the place to report the problem. This one is fixed with version 1.4.9, which was never bundled with N++ deliveries.
