### ISSUE TITLE
7.4 search/replace ALL lacks compatibility with 7.3.3 and before

### ISSUE THREAD

**Issue by gaby52co** [notepad-plus-plus/notepad-plus-plus#3511]
### Description of the Issue

From 7.4.2 "Find all in current document" / "Replace All" runs only from cursor to end of file.
In 7.3.3 and before, they were working on the whole file as expected
It is a result of adding "Find Forward" and "Find Backward" - but this is a bad side-effect
I have found no way to obtain a real Replace All without going first to Beginning of file

### Steps to Reproduce the Issue

1.  Upgrade to 7.4.2 (from 7.3.3)
2.  Move inside a file - having a known string before and after the cursor
3. Use "Replace All" to replace the string by something else

### Expected Behavior

I expect "Find all in current document" to find ALL occurrences
I expect "Replace All" to replace ALL occurrences

### Actual Behavior

"Find all in current document" finds occurrences from cursor ONLY
"Replace All" replaces occurrences from cursor ONLY

**Comment by taylorsmurphy** [comment]
I believe you simply need to check off  the "Wrap around" box on the search dialog. 

![image](https://user-images.githubusercontent.com/1223478/28048301-e9171902-65a4-11e7-84aa-47617fe3eb73.png)

**Comment by gaby52co** [comment]
Great! How did I miss it?

Anyway, Notepad++ is a wonderful product, and I will continue to use it and support it actively!

Gaby
