### ISSUE TITLE
Enable Spell Check Plug-in by default

### ISSUE THREAD

**Issue by mancoast** [notepad-plus-plus/notepad-plus-plus#3512]
Greetings Notepad++ Community members,

I wish to congratulate all on a Fantastic and Speedy development with the Notepad++ system.
As an engineer, your software enables note-taking at a whole new level.
In general, I prefer to always keep Operating Systems and Application settings at system default on engineering workstations.

Recently, we have re-imaged all the engineering systems with the latest and greatest.
However, the notepad++ no longer provides spell check features for quick and dirty note-taking.

Please consider my request to modify the notepad++ system defaults to include Spell Check Plug-in on initial installation.

Thanks,
coast

**Comment by SinghRajenM** [comment]
Duplicate #2095

**Comment by mancoast** [comment]
Greetings,
I appreciate the crosslink. 
We now know this issue pre-exists. 

Please advise required changes. 
Given hint/instructions I can immediately implement. 

Thanks,
Coast

**Comment by SinghRajenM** [comment]
Actually, it was already there in older version. I guess, 6.5 or older. It was Dspellchecker which is now available via plugin manager.
If I remember correctly, there was an crash reported by MS to Notepad++ owner. This crash occurred due to spell checker. From that time onward, this was removed from Notepad++ installer, but still available via plugin manager.

**Comment by mancoast** [comment]
Perhaps the time is ripe to reintroduce the spell checker?  If it instigates instability, the root cause of the failure requires development. Spell checker adds incredible valuable, in my opinion.  

Do you know the commit checksum where it was disabled?  How about the github issue correlating to the failure of dspellchecker?

**Comment by SinghRajenM** [comment]
>Spell checker adds incredible valuable, in my opinion.

I second it.

Not sure about checksum, but you can see related issues and discussion at
https://github.com/notepad-plus-plus/notepad-plus-plus/issues/427
https://github.com/Predelnik/DSpellCheck/issues/70
https://notepad-plus-plus.org/community/topic/9956/dspellcheck-and-windows-10

**Comment by jay** [comment]
[DSpellCheck](https://github.com/Predelnik/DSpellCheck) has some problem still, even built from master I'm able to reproduce deadlocks by repeatedly opening and closing Notepad++. I'd hold off on enabling it by default. Refer to https://github.com/Predelnik/DSpellCheck/issues/92

**Comment by mancoast** [comment]
Any plans for resolution?

**Comment by mancoast** [comment]
https://github.com/Predelnik/DSpellCheck
