### ISSUE TITLE
Sort Lines Lexicographically does nothing after a Find/Replace All that inserts newlines

### ISSUE THREAD

**Issue by arpsmack** [notepad-plus-plus/notepad-plus-plus#3513]
### Description of the Issue
After performing a find/replace all replacing "," with "\n", I end up with a file containing multiple lines.  When I try to sort those lines, the Edit > Line Operations > Sort Lines Lexicographically commands do nothing.  Other line operations, such as Join Lines, seem to work fine.

If I CTRL+A, copy the text, and paste it into a new document, the sorting commands work fine.

### Steps to Reproduce the Issue

1. Create a new text document containing
```
C,B,A,Z,Y,X
```
2. Do a find/replace all replacing ',' with '\n' (make sure to use the Extended search mode)
3. You should now have this in your editor
```
C
B
A
Z
Y
X
```
4. Select all the text and run Edit > Line Operations > Sort Lines Lexicographically Ascending

### Expected Behavior
The lines get sorted and the document looks like
```
A
B
C
X
Y
Z
```

### Actual Behavior
The document remains unchanged.

### Debug Information
Notepad++ v7.4.2   (32-bit)
Build time : Jun 18 2017 - 23:34:19
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10 (64-bit)
Plugins : JSMinNPP.dll mimeTools.dll NppConverter.dll NppExport.dll PluginManager.dll Tidy2.dll 

(I also tried renaming my plugins folder as the guidelines suggest and the bug still happens)

**Comment by MAPJe71** [comment]
Did you try replacing the `,` with `\r\n`?

**Comment by arpsmack** [comment]
I hadn't tried that.  I just did it now and that works.  Also, using '\n' in the find/replace and then switching the line endings to Unix (LF) causes the subsequent sort to work.

I'm not quite sure why creating a new document and then copy/pasting the text into it works though, since the new document is in Windows (CR LF) mode, unless Notepad++ converts the '\n' to '\r\n' somewhere in the copy/paste process.

Sounds like this just might be an error on my part.  Thanks!

**Comment by dail8859** [comment]
> unless Notepad++ converts the '\n' to '\r\n' somewhere in the copy/paste process.

It does in fact do this to make sure the file always has consistent line ends even if you copy paste from somewhere else.

**Comment by pjm4github** [comment]
This is a behavioral anomaly AFAIC since it doesnt do what I expect it to do.  The only way for me to get it to work is to mangle the \n with \r\n and back again.  Yuck.

**Comment by jdhenckel** [comment]
I ran into this same issue.  **The work around is:**  After search and replace with '\n', cut and paste all the lines *into the same file at the same place*.  Then you can sort them.  The action of cut/paste will fix the line endings.

Why is this **CLOSED**?  Why not just fix it, so the workaround it not necessary?

**Comment by nebosite** [comment]
I just ran into this problem.  I searched for ';' and replaced with '\n' and sort wouldn't work.  The cut/paste workaround successfully resolved the problem.

**Comment by MisterTickle** [comment]
> I ran into this same issue. **The work around is:** After search and replace with '\n', cut and paste all the lines _into the same file at the same place_. Then you can sort them. The action of cut/paste will fix the line endings.
> 
> Why is this **CLOSED**? Why not just fix it, so the workaround it not necessary?
> 
> Three possible fixes:
> 
> 1. Fix the "sort lexicographically" to use either \n or \r\n as a line ending regardless of the mode
> 2. Fix the search and replace to auto insert \r before \n if the file is DOS mode
> 3. Warn the user that after the s&r if the line endings are inconsistent with the file mode

Thankyou for this. I can't believe this is closed, and still not fixed, 18 months later! Absolutely incredible.

**Comment by sasumner** [comment]
>I can't believe this is closed

I think it is closed because people are mixing line-endings via replace and this creates a bad situation for sort.  As long as line-endings are uniform, sort doesn't have any problems (well, the complained-about problem at least).

**Comment by jpstotz** [comment]
Search and replace is a regular function of Notepad++ and line sorting, too.
Using these function in any order with any parameter(s) should work, otherwise it is a bug. 

Therefore the only possible conclusion is that the line sorting function has  a bug and should be fixed. 
--> This issue should be re-opened.

**Comment by sasumner** [comment]
Search and replace has nothing to do with it...except apparently it is a vehicle to get mixed-line endings in there...which is not a valid scenario.

**Comment by CollinChaffin** [comment]
Why is this closed?!  A line sort function that flat out DOES NOT WORK.  As stated above, a totally LEGAL operation is a simple replaceall with newline (from spaces). At that point, this GUI is broken and no longer can perform a simple line sort.  How is that not a bug and an open issue?

**Comment by woctezuma** [comment]
For people stumbling on this thread from a search engine, I would like to point out that the workaround is:

![workaround](https://i.imgur.com/l4j0SLU.png)

**Comment by ProxyPlayerHD** [comment]
i still have the same exact issue with the newest version.

even when ALL the line-endings are `\n` or `\r` it wouldn't work, it exclusively works with `\r\n` only...
"remove duplicate lines" is also effected by this.

why can't this just be fixed instead of having to use a workaround?
i'm so confused why the line-ending matters at all, `\n` `\r\n` `\r` should all be treated equally and interchangeably. so it's weird to see some specific functions that don't do that.

**Comment by sasumner** [comment]
>even when ALL the line-endings are \n or \r it wouldn't work, it exclusively works with \r\n only..."remove duplicate lines" is also effected by this.

It does NOT work exclusively with `\r\n` line-endings only.
These functions work entirely based upon the line-ending type identified by the software (or specified by the user) as shown on the status bar; example:

![image](https://user-images.githubusercontent.com/30118311/117572699-09c49200-b0a2-11eb-8bb7-7db6d8edc4df.png)

Even if all line-endings are "consistent" in the document, if this consistency doesn't match the status bar reporting, there's going to be a "problem" when sorting.  It isn't a problem with the software, however.

>why can't this just be fixed instead of having to use a workaround?

There is no workaround.
There is nothing to fix.

This could, however, be better described in the user manual; I will open an issue on that.

**Comment by ProxyPlayerHD** [comment]
yea, atleast there should be an error message telling the user why it didn't work (and maybe giving them the option to change the line ending and rerun the function in the same window for convenience), instead of just doing nothing and leaving the user confused...

it's still such a strangely specific limitation of the line operations though.
