### ISSUE TITLE
Search direction missing

### ISSUE THREAD

**Issue by wormuth** [notepad-plus-plus/notepad-plus-plus#3516]
### Description of the Issue
It is not possible to set the search direction anymore in search dialog.

### Steps to Reproduce the Issue
1. Hit Ctrl+F

### Expected Behavior
It should be possible to set the search direction.

### Actual Behavior
The formerly available search direction options in search dialog are missing, see screenshots.

### Debug Information
Notepad++ v7.4.2   (64-bit)
Build time : Jun 18 2017 - 23:38:43
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10 (64-bit)
Plugins : ComparePlugin.dll JSMinNPP.dll mimeTools.dll NppConverter.dll XMLTools.dll 

![image](https://user-images.githubusercontent.com/2778069/28071086-48e3dd0c-664f-11e7-96c1-38c1df59e252.png)

**Comment by MAPJe71** [comment]
The search direction option is no longer needed as the single "find" button has been replaced by two buttons i.e. "<< Find" and "Find Next" (see your screenshot).

**Comment by wormuth** [comment]
Touché 👍

**Comment by powdermnky007** [comment]
Is there an option to set the find buttons like they were in the last release?  I like the backwards and forwards button like in the screenshot above.

**Comment by MAPJe71** [comment]
@powdermnky007 No.

**Comment by powdermnky007** [comment]
Ok, I really loved that.  Thanks for your response.

**Comment by micktion** [comment]
I'm using v7.5.1 
![image](https://user-images.githubusercontent.com/4677284/30839674-bf46c2fe-a2b6-11e7-8ea6-6c5684f8f815.png)

No direction group box and no << Find button

**Comment by Dakshya** [comment]
> 
> 
> I'm using v7.5.1
> 
> ![image](https://user-images.githubusercontent.com/4677284/30839674-bf46c2fe-a2b6-11e7-8ea6-6c5684f8f815.png)
> 
> No direction group box and no << Find button....
> 
> EDIT: OK I just noticed there is a backward direction checkbox.
> You guys keep changing it...

thank you so much

**Comment by chcg** [comment]
With newer N++ version there is a checkbox to the right of "Find Next" to toggle between the normal mode and the 2 button mode.
