### ISSUE TITLE
Crash every time after I close NPP and reopen it

### ISSUE THREAD

**Issue by zhiweiv** [notepad-plus-plus/notepad-plus-plus#3518]
Here is the steps to reproduce my issue:
1 Right click a text file and click Edit with NPP.
2 Close NPP window by click X at the top-right cornor.
3 Right click the text file and click Edit with NPP again, it will take a few seconds and finally pops up a crash window.
4 After I click "Close the progream" on crash window, it pops up again, I have to click "Close the progream" again.
5 After step 4, I can open the text by "Edit with NPP" successfully.

I reproduced this issue on different machines, and I tried 32bit, 64bit, different OSs.

Debug Info
Notepad++ v7.4.1   (32-bit)
Build time : May 18 2017 - 02:00:37
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 8.1 (64-bit)
Plugins : PluginManager.dll XMLTools.dll

Any ideas?

Thanks

**Comment by zhiweiv** [comment]
Seems unable to upload images, here is crash details,

Problem signature:
  Problem Event Name:	APPCRASH
  Application Name:	notepad++.exe
  Application Version:	7.4.1.0
  Application Timestamp:	591ce479
  Fault Module Name:	notepad++.exe
  Fault Module Version:	7.4.1.0
  Fault Module Timestamp:	591ce479
  Exception Code:	c0000005
  Exception Offset:	00063b8a
  OS Version:	6.3.9600.2.0.0.256.48
  Locale ID:	1033
  Additional Information 1:	8a3a
  Additional Information 2:	8a3a053bdd62e53b7d62bc40dce502f1
  Additional Information 3:	f567
  Additional Information 4:	f567b6bfbaba08aab93c5235dff5a962

**Comment by AngryGamer** [comment]
You might want to try updating Notepad++

**Comment by cmeriaux** [comment]
You also may do a fresh install. Sometimes, configuration files are corrupted

**Comment by zhiweiv** [comment]
I have tried all with no luck, I returned to 6.9.1 and disabled auto updater just now, it works perfect.
