### ISSUE TITLE
Mysterious ghost tab appearing in tab bar

### ISSUE THREAD

**Issue by aarongreig** [notepad-plus-plus/notepad-plus-plus#3520]
### Description of the Issue
I have  a strange blank tab sitting in my tab bar. It appears to act exactly like whatever the last normal tab I had open was (i.e. I can switch to another tab and back to the ghost tab and nothing will change), everything I've tried (editing, saving, running a few macros) has functioned exactly as if I had that other tab open.

### Steps to Reproduce the Issue

1. I was moving a tab around on the end of the tab bar
2. I moved in such a way that I wasn't holding my mouse button in but the tab was still moving with my mouse (don't know exactly what happened here, sorry)
3. I closed the tab and that little page icon you get when you drag a tab off the window appeared on my mouse
4. I dropped it on the tab bar

### Expected Behavior

Tab closes, weirdness ends.
### Actual Behavior

Tab becomes a spooky ghost, weirdness continues even as I write this bug report.
### Debug Information

Notepad++ v7.4.2   (32-bit)
Build time : Jun 18 2017 - 23:34:19
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 7 (64-bit)
Plugins : mimeTools.dll NppConverter.dll NppExport.dll NppTextFX.dll PluginManager.dll 

find also attached a screengrab of the tab in its natural habitat, note that the file along the top of the window is the last tab I had open (the one to the left of it)
![capture](https://user-images.githubusercontent.com/22745976/28117165-34d118b0-6704-11e7-92b4-a826862bfd53.PNG)

**Comment by achrapko** [comment]
I have experienced this issue as well, though when moving the tab I simply clicked and dragged it across the tab bar. 
As soon as I dragged it far enough to swap positions, the document name blanked out of the tab.
Once the tab was blank, I could no longer access the document that it had been previously, and I can also not close notepad++ other than killing the process.

**Debug Information**
Notepad++ v7.5.9   (32-bit)
Build time : Oct 14 2018 - 15:02:52
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : ON
Local Conf mode : OFF
OS : Windows 7 (64-bit)
Plugins : mimeTools.dll NppExport.dll DSpellCheck.dll Explorer.dll HexEditor.dll IndentByFold.dll LocationNavigate.dll NppGTags.dll PluginManager.dll 

On attempting to move the blank tab to a new instance I get the following error

![image](https://user-images.githubusercontent.com/6821819/50490727-a956bd80-09dc-11e9-8c73-3dc558f2306e.png)

When clicking through the Recovery dialog, after the 'successful recovery' dialog box, I get another error:
![image](https://user-images.githubusercontent.com/6821819/50490918-9bee0300-09dd-11e9-86fa-798fce03033a.png)

Dump Summary
------------
Dump File:	NppDump.dmp : C:\Program Files (x86)\Notepad++\NppDump.dmp
Last Write Time:	12/27/2018 1:42:24 PM
Process Name:	notepad++.exe : C:\Program Files (x86)\Notepad++\notepad++.exe
Process Architecture:	x86
Exception Code:	0xC0000005
Exception Information:	The thread tried to read from or write to a virtual address for which it does not have the appropriate access.
Heap Information:	Not Present

**Comment by MetaChuh** [comment]
the old ghost tab issue is no longer reproducible on notepad++ 7.6.6

please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins if you update from version 7.5.9 or below.

thank you for your help and best regards.
