### ISSUE TITLE
Bug 'Find Next' button text - ptbr

### ISSUE THREAD

**Issue by evertonloffi** [notepad-plus-plus/notepad-plus-plus#3523]
### Description of the Issue
The text into 'Find next' button is out of bounds in ptbr (Localizar próximo).

### Steps to Reproduce the Issue

1. Configure to pt-BR npp language.
2. Open Find Window
3. The text into 'Find next' button is out of bounds in ptbr (Localizar próximo).

### Expected Behavior
Full text into button 

### Actual Behavior
The text into 'Find next' button is out of bounds in ptbr

![npp-bug](https://user-images.githubusercontent.com/30176810/28211397-d30bcab0-6872-11e7-9b5f-7fb2e53b60f3.png)

**Comment by figobert** [comment]
Also occurs when language is German.

![image](https://user-images.githubusercontent.com/30253492/28302556-5f8ce9f6-6b8e-11e7-95bb-98373b462914.png)

**Comment by dinkumoil** [comment]
Seems to be reverted. See 4d921b7
