### ISSUE TITLE
NPP 7.4.2 Generate "Unknown Exception" after an opened file is modified outside of NPP

### ISSUE THREAD

**Issue by roytrubshaw** [notepad-plus-plus/notepad-plus-plus#3524]
### Description of the Issue

I run Npp under wine 1.8.6 (64bit) on CEntOS 6.8, and until this last update Npp would handle the file change with no problems, reloading the file after first seeking user conformation. With Npp 7.4.2 there is now an "Unknown Exception" error (which I guess is the default behaviour for an uncaught exception).

### Steps to Reproduce the Issue

1. Install Npp 7.4.2 under wine 1.8.6(64bit) on CEntOS 6.8
2. Open a file
3. Modify it outside of Npp

### Expected Behavior

Npp confirms that the file should be reloaded, and does so after the user confirms that this is what is required.

### Actual Behavior

Npp display an "Unknown Exception" message and then enters the default file recovery mode before exiting.

### Debug Information

Notepad++ v7.4.2   (64-bit)
Build time : Jun 18 2017 - 23:38:43
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : ON
Local Conf mode : OFF
OS : Windows 7 (64-bit)
Plugins : mimeTools.dll NppConverter.dll 

![screenshot_npp](https://user-images.githubusercontent.com/4293193/28211458-ade93e9e-6894-11e7-8955-0ad8f0c8ea9c.jpg)

**Comment by MetaChuh** [comment]
please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins if you update from version 7.5.9 or below.
if your issue still persists, and it is still of relevance, please feel free to file a new issue as easy to understand and reproducible as possible.

thank you for your help and best regards.

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
(no extra account is needed, just use your github account to sign in)
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)
