### ISSUE TITLE
Error "Bad allocation", Notedpad++ crash while comparing two CSV files using Compare plugin

### ISSUE THREAD

**Issue by RandomUser0815** [notepad-plus-plus/notepad-plus-plus#3525]
### Description of the Issue
Notedpad++ 7.4.1 and 7..4.2 (Windows 10) and 7.3.3 (Windows 10) crash while comparing two files. Error "Bad Allocation" is displayed.

### Steps to Reproduce the Issue

1. Use Compare plugin 1.5.6.2 or 2.0
2. Use Plugin Manager 1.3.5 or 1.4.5
3. Compare two CSV files of 330 kb and 394 kb size.

### Expected Behavior
I would expect that the differences between both files are displayed. Unfortunately I can not share the files.

### Actual Behavior
![notepad _crash](https://user-images.githubusercontent.com/30178968/28214848-31bd72fa-68ac-11e7-899f-850ae3e01d4b.png)

### Debug Information
Notepad++ v7.4.1   (32-bit)
Build time : May 18 2017 - 02:00:37
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 7 (64-bit)   (actually Windows Server 2008 R2)
Plugins : ComparePlugin.dll NppColumnSort.dll sql.dll 

Notepad++ v7.4.1   (32-bit)
Build time : May 18 2017 - 02:00:37
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 7 (64-bit) (locally on my Laptop)
Plugins : ComparePlugin.dll mimeTools.dll NppColumnSort.dll NppConverter.dll NppExport.dll PluginManager.dll sql.dll

**Comment by dail8859** [comment]
As this exception is coming from the Compare plugin, this issue needs reported to the developers of the plugin [here](https://github.com/pnedev/compare-plugin/issues).

**Comment by qian-jiahong** [comment]
Notedpad++ 7.5.8, This problem also occurs when Compare is not installed.

**Comment by sasumner** [comment]
Why don't you elaborate on what exactly is going on when "this problem also occurs when Compare is not installed"?
