### ISSUE TITLE
Preferences->General->Document List Panel->Show should have toggle in View menu

### ISSUE THREAD

**Issue by drankinatty** [notepad-plus-plus/notepad-plus-plus#3526]
### Description of the Issue

`Preferences->General->Document List Panel->Show` should have toggle in `View menu` to allow the `'Doc Switcher'` panel to be shown or hidden with a shortcut key assigned to the menu item. Similar to what can be done with the `'Document Map'` entry in the View menu. It is currently awkward to have to open Preferences to check or uncheck the `"[x] Show"` checkbox in the Document List Panel group.

The current `'Doc Switcher'` panel is fantastic, but you need to be able to **show/hide** it with a shortcut to provide full-window editing without having to open Preferences each time.

### Steps to Reproduce the Issue

1. Check the `"[x] Show"` checkbox in the `Document List Panel` group (in Preferences->General)
2. Now try and find a convenient way to show/hide the `'Doc Switcher'` panel to provide additional editing space.
3. (cannot currently be done)

### Expected Behavior

Some View menu 'Doc Switcher' or 'Document Panel' toggle that could be assigned a shortcut

### Actual Behavior

Searched diligently but no way other than opening Preferences and unchecking `[x] Show` could be found to hide the `'Doc Switcher'` panel.

### Debug Information

**No debug Info -- Just a feature request** `:)`

Keep up the great work. NPP is a good package.

**Comment by dhowland** [comment]
I agree with this.  It has always bothered me that you have to go into preferences to open the doc switcher, unlike every other dockable panel).  Why???

**Comment by MAPJe71** [comment]
I have done the following:
1. installed the `LuaScript` plugin;
2. added the following snippet to `startup.lua`:
```lua
npp.AddShortcut("Toggle Doc Switcher", "", function()
    npp:ShowDocSwitcher( not npp:IsDocSwitcherShown() )
end)
```
3. installed the `Customize Toolbar` plugin;
4. "created" a toolbar icon: ![toolbar-docswitcher](https://user-images.githubusercontent.com/6494038/34535180-7df4978c-f0c1-11e7-822c-3490a0e6bf0e.png)

5. added the following line to `CustomizeToolbar.btn`:
```
Plugins,LuaScript,Toggle Doc Switcher,,Toolbar-DocSwitcher.bmp
```

Note: only possible for Notepad++ 32-bit as the `Customize Toolbar` plugin is not available for Notepad++ 64-bit (AFAIK).

**Comment by drankinatty** [comment]
Hey, that's progress. Somehow the body of configuration settings should be consistent between the 32 and 64 bit packages. I haven't pawed through the source to see how it is handled, but ideally some kind of common struct holding the various toolbar and panel options could provide native ability to do this without needing a plugin? That's just an off-the-cuff thought. Keep up the great work with npp.

**Comment by bpersonick** [comment]
:+1:   This needs to happen!  I was just about to write my own enhancement request for this!

**Comment by mb1280** [comment]
Reply to:  MAPJe71

Thank you for this macro!

Here's what I ran into, and some clarifications:

4. "created" a toolbar icon Toolbar-DocSwitcher.bmp: toolbar-docswitcher

. . . This goes in:  plugins / Config /
. . . Then, why doesn't the icon show in the toolbar?  All it gives me a question mark.

If I save the icon to Desktop, it's a .dib file:
34535180-7df4978c-f0c1-11e7-822c-3490a0e6bf0e.dib

What if I create another copy in the folder with the .bmp extension?
No change

Can I find a fix for this in the documentation?
Customize Toolbar Discussion . . . https://sourceforge.net/p/npp-customize/discussion/1813236/thread/f6304b3528/?limit=25#7d12

Not the documentation - much easier - explanation is in the comments:

ltdeta - 2023-03-13

preferences \ general \ toolbar
- Fluent UI modes are not working, showing an Question mark
- only Mode "Standard Icons" is working
