### ISSUE TITLE
Only prompt for reloading file if it's tab is selected

### ISSUE THREAD

**Issue by tweimer** [notepad-plus-plus/notepad-plus-plus#3528]
### Description of the Issue
Could you please add an option "Only prompt for reloading file if it's tab is selected"?
It is currently very annoying.

###Example
For example, I have multiple files open in Notepad++. One of them get's changed in the background.
Now I open another file, e.g. from Windows file explorer. notepad++ opens the new files, but it switches tabs automatically and prompts me if I want to reload it. I have to click Yes or no and then switch tab back to the file I have just opened.

**Comment by BenHagaman** [comment]
I came looking to write this exact request - this is 100% how I believe the default should function, and this is the most annoying part of using notepad++ hands down - only prompt for reload when you switch to the tab.

Just as an example: If I have 10+ project files open and run a git checkout of a new branch - when I try to open a log file I have to dismiss 10 prompts, and then try to find the original tab. It's extremely disruptive.
