### ISSUE TITLE
3 weeks' day off

### ISSUE THREAD

**Issue by donho** [notepad-plus-plus/notepad-plus-plus#353]
FYI:
I am in holiday during 3 weeks so I will be less active for issues & pr.

**Comment by milipili** [comment]
Hum... I don't really know... Bug or question ? :+1:

**Comment by GitMensch** [comment]
Thank you for this information

**Comment by donho** [comment]
@milipili We need a new label "fxxk it, I'm in holidays" :)

**Comment by Tmp341** [comment]
@donho That is one h*ll of a holiday :)

**Comment by guy038** [comment]
Hello **Don**, 

I wish you **very nice** holidays Have a **good time** ! Just a little think for all people, working **hard** on their projects, with your **"baby"** !

Cheers

guy038
