### ISSUE TITLE
Add 'RETURNING' keyword to SQL language

### ISSUE THREAD

**Issue by tcostin** [notepad-plus-plus/notepad-plus-plus#3536]
### Description of the Issue
This keyword (particular to the [Firebird](https://www.firebirdsql.org/file/documentation/reference_manuals/fblangref25-en/html/fblangref25-dml-insert.html) dialect) is listed in sql.xml, but not in langs.model.xml, so it is not highlighed as a keyword. 

### Steps to Reproduce the Issue
1. Create a new file.
2. Set language to SQL
3. Write a query that includes the keyword. For instance:
`INSERT INTO People (FirstName, LastName) VALUES ('John', 'Smith') RETURNING Id;`

### Expected Behavior
Blue coloring for SQL keywords: 'INSERT', 'INTO', 'VALUES', 'RETURNING'

### Actual Behavior
Blue coloring for keywords 'INSERT', 'INTO', 'VALUES', but not for 'RETURNING'

**Comment by ArkadiuszMichalski** [comment]
Only `RETURNING` is missing.

https://livesql.oracle.com/apex/livesql/file/content_C3DBYO1P9SPL57Y0128NCP1KL.html
https://dzone.com/articles/use-returning-clause-to-avoid-unnecessary-sql-stat
