### ISSUE TITLE
Keyboard shortcut for "Replace in Files" button not working

### ISSUE THREAD

**Issue by bobopalmtree** [notepad-plus-plus/notepad-plus-plus#3539]
### Description of the Issue

In the "Find in Files" dialog, the button "Replace in Files" has a underlined "R" indicating that the button can be activated by pressing Alt+R. This does not work. 

This is in V7.4.2 32bit

### Steps to Reproduce the Issue

1. Just open Find in Files dialog and try to do a Replace in Files by pressing Alt+R.

### Expected Behavior

The find and replace should run.

### Actual Behavior

The find and replace does not run.

**Comment by Graham-G** [comment]
Does not reproduce in v7.5.8 (32-bit).

**Comment by ClaudiaFrank** [comment]
Old thread, imho can/should be closed.

**Comment by bobopalmtree** [comment]
Just downloaded  7.5.8 and still face the same issue. 
Open Notepad++
Press Ctrl+Shift+f
Enter 'foo' in Find what text box
Enter 'bar' in Replace with text box
Enter '*' in Filters
Select directory where the files are
Press Alt+r

**Comment by bobopalmtree** [comment]
Oops, did not mean to close.
Continuing my previous post:
After Alt+r nothing happens 

All other acceleration keys in this dialog work for me except Alt+r.

**Comment by bobopalmtree** [comment]
Been playing around some more and it seems the shortcut does work, but only when either the 'Find All' or the 'Close' button has the focus.

**Comment by ClaudiaFrank** [comment]
Could it be that you are using ATI graphic cards and their manager - as far as I remember this application
has a global shortcut set.

**Comment by bobopalmtree** [comment]
I don't see no ATI graphics card in this laptop, so I don't think that's it.
Something else may have hijacked these shortcuts but then why does it work when either of those two buttons are selected?

**Comment by ClaudiaFrank** [comment]
Didn't see your reply about the fact that it works when your mentioned buttons do have the focus.
We must have posted nearly simultaneously.

Could you give it  a try to see if it works by using https://notepad-plus-plus.org/repository/7.x/7.5.8/npp.7.5.8.bin.minimalist.7z 

or https://notepad-plus-plus.org/repository/7.x/7.5.8/npp.7.5.8.bin.minimalist.x64.7z if switched to x64?

**Comment by bobopalmtree** [comment]
I'm at home now on a different computer, but trying both versions above, I keep seeing the same behaviour.

**Comment by ClaudiaFrank** [comment]
Can confirm reported behavior - will try to find out what is causing it.

**Comment by ClaudiaFrank** [comment]
The issue is that the replace button from the replace dialog and the replace control from the find_in_files_dialog do share the same accelerator but it looks like no code within the find_replace_dialog handles this conflict. There is a function enableFindInFilesControls which could be used I guess.
By introducing something like

`
...
	if (isEnable)
	{
		::ShowWindow(::GetDlgItem(_hSelf, IDREPLACE), SW_HIDE);
		::SetWindowText(::GetDlgItem(_hSelf, IDREPLACE), _T("Replace"));
	}
	else
	{
		::ShowWindow(::GetDlgItem(_hSelf, IDREPLACE), SW_SHOW);
		::SetWindowText(::GetDlgItem(_hSelf, IDREPLACE), _T("&Replace"));
	}
...
`
the accelerator can be used with both buttons. 
From my understanding this would temporarily remove the accelerator from the Replace button
if the find in files dialog opens and put it back if the controls do get disabled again.
But I'm sure there is some other better/cleverer way to solve this.

**Comment by krilbe** [comment]
Please note that #3699 would probably solve this issue. Clashes between Alt shortcut letters from invisible tabs should not be an issue, i.e. Notepad++ should never, in any dialog with multiple tabs, have shortcuts on invisible tabs swallow Alt letter shortcuts that appear on the active tab. It's not realistic to require that all Alt shortcuts be unique across all tabs. Being unique on the active tab should suffice and work as expected.

**Comment by Obscuris** [comment]
Alt+E selects option 'Backward direction' or input-field for 'Directory' depending on focused/visible replace dialog-tab. Issue still persists for using Alt+R in 'Find in Files' (v7.7.1 64-bit).
