### ISSUE TITLE
Multiple lines Bookmarking

### ISSUE THREAD

**Issue by LaurentDecool** [notepad-plus-plus/notepad-plus-plus#3541]
### Description of the Issue
When trying to keep only some text (multi-line) with a regexp, bookmarking only bookmark the first line of the text block

### Steps to Reproduce the Issue
1. Have a file that contains :
TEST1xxxx
blabla
TEST2xxxx
blabla
TEST1xxxx
blabla
TEST1xxxx
blabla
TEST1xxxx
blabla
2. Use the following Regexp in the Mark Tab : TEST1.*\r\n((?!TEST).)*\r\n
3. Check the bookmark line
4. Click Mark All

### Expected Behavior
All the 
"TEST1xxxx
blabla"
Should be bookmarked

### Actual Behavior
Only TEST1xxxx are marked as bookmarked

### Debug Information
N/A

![notepad](https://user-images.githubusercontent.com/30271925/28336399-c9452386-6bcf-11e7-8298-7e132875b3e1.JPG)

**Comment by MetaChuh** [comment]
please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins if you update from version 7.5.9 or below.
if your issue still persists, and it is still of relevance, please feel free to file a new issue as easy to understand and reproducible as possible.

thank you for your help and best regards.

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
(no extra account is needed, just use your github account to sign in)
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)
