### ISSUE TITLE
Remove Unnecessary Blank and EOL behaves as EOL to Space

### ISSUE THREAD

**Issue by spike411** [notepad-plus-plus/notepad-plus-plus#3543]
[test.txt](https://github.com/notepad-plus-plus/notepad-plus-plus/files/1159177/test.txt)
[test-result.txt](https://github.com/notepad-plus-plus/notepad-plus-plus/files/1159179/test-result.txt)

### Description of the Issue
‘Blank Operations: Remove Unnecessary Blank and EOL’ seems to behave pretty much the same as ‘Blank Operations: EOL to Space’

### Steps to Reproduce the Issue

1. Create/open a text file with Windows line-endings and several lines of text.
2. Execute the action Blank Operations: Remove Unnecessary Blank and EOL.

### Expected Behavior

A text file with no extra EOLs and empty lines.

### Actual Behavior

A single line of text with EOL replaced by spaces.

### Debug Information

Notepad++ v7.4.2   (64-bit)
Build time : Jun 18 2017 - 23:38:43
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10 (64-bit)
Plugins : mimeTools.dll NppConverter.dll

**Comment by MetaChuh** [comment]
please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins if you update from version 7.5.9 or below.
if your issue still persists, and it is still of relevance, please feel free to file a new issue as easy to understand and reproducible as possible.

thank you for your help and best regards.

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
(no extra account is needed, just use your github account to sign in)
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)
