### ISSUE TITLE
Doing a CTRL+F For Find in Notepad++ 7.4.2 Triggers Norton Internet Security to Pop-Up

### ISSUE THREAD

**Issue by astrohart** [notepad-plus-plus/notepad-plus-plus#3544]
I am using Windows 7 Professional Service Pack 1 and Notepad++ 7.4.2.  

![notepad-version](https://user-images.githubusercontent.com/8261875/28389446-025d18c0-6c8b-11e7-9ec5-5d4be394022a.png)

![windows-version](https://user-images.githubusercontent.com/8261875/28389451-05cd6a28-6c8b-11e7-8daf-27be172c81b6.png)

The following issue does not show up when I invoke a Find In Files, Replace, or a Replace in Files, but simply a Find (by pressing CONTROL and F keys at the same time).

![find-dlg](https://user-images.githubusercontent.com/8261875/28389470-173dafe8-6c8b-11e7-92b7-b17297980519.png)

This only started happening when I installed version 7.4.2 of Notepad++, and I have a 32-bit version of the software installed, even though my OS is 64-bit (if I install 64-bit Notepad++ then I lose the Plugins support and I love the Plugins.  Plugin Manager does not work in 64-bit Notepad++) 

Anyhoo...

I have Norton 360 Premier installed as my personal firewall/antivirus tool.  I am not sure if some of the new code for the Enhanced Find dialog box in Notepad++ is making my Norton software think Notepad++ is a virus or something, but 100% of the time I hit CONTROL and F keys on the keyboard -- and this is after I've installed Norton but before I've "activated" it, by the way -- the Norton software shows the "Norton 360 Subscription" window like it's detected a virus or other issue and it's trying to get me to finish installing it so it can then warn me about a threat.

![norton](https://user-images.githubusercontent.com/8261875/28389264-49675718-6c8a-11e7-9fc3-d6e1cef1b568.png)

So, then I respond to the Norton screen and sign in for my "subscription " with them, and then I go back to Notepad++ and do a CONTROL and F keys, and then my computer seems to behave as normal. This is very weird.  It only began happening with Notepad++ v7.4.2.

![about-norton](https://user-images.githubusercontent.com/8261875/28389330-922aecee-6c8a-11e7-84bf-feaecd4c20df.png)

This would not really be a huge issue, however, I am in IT management and we do the same thing at work, and we install several machines using scripts, and I love opening my scripts in Notepad++ before the computer is hooked to the network to edit my scripts, and every, every, every single time I do a CONTROL+F in the latest Notepad++, there is Norton, reminding me that my subscription is expired and that I need to activate.  It doesn't seem to happen pressing any other kind of key combination, at least, none that I can think of.

**Comment by bahusoid** [comment]
Did you try hitting Ctrl+F without launched Notepad++? And what if you open Find dialog via menu Search -> Find?

**Comment by subchannel13** [comment]
Showing subscription window is poor way of alerting a user about a threat (virus, worm, other malware). There is no proof about found threat and as you said after you filled in subscription details the issue disappeared. I think you are seeing Norton 360 Premier bug/"feature" first and foremost.

**Comment by dail8859** [comment]
Doing a quick google search shows this is not specific to Notepad++ for example see: https://answers.microsoft.com/en-us/windows/forum/windows_10-performance/norton-grabbing-ctl-f-resolved-by-uninstalling/388232de-a7d5-40cc-876e-0436586b1c49

**Comment by couponstechie** [comment]
I have tried this many time but in my system, i don't have any msg like this. href="https://www.couponstechie.com
