### ISSUE TITLE
Clear all marks also removes bookmarks

### ISSUE THREAD

**Issue by W1Ko** [notepad-plus-plus/notepad-plus-plus#3546]
### Description of the Issue

_Clear all marks_ also removes bookmarks

### Steps to Reproduce the Issue

1. In textfile: bookmark a line (CTRL+F2)
2. Choose _Find_ (CTRL+f) > tab _Mark_ > _Clear all marks_

### Expected Behavior

Bookmarked line is still bookmarked

### Actual Behavior

Bookmark is removed

### Debug Information

Notepad++ v7.4.2   (32-bit)
Build time : Jun 18 2017 - 23:34:19
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10 (64-bit)
Plugins : ComparePlugin.dll mimeTools.dll NppConverter.dll NppExport.dll PluginManager.dll

**Comment by sasumner** [comment]
I agree fully that this is an issue; best workaround I've found is to quit and restart Notepad++ to get rid of the (red)marking while keeping the bookmarking.

**Comment by W1Ko** [comment]
Usually, I disable setting _Remember current session for next launch_, so my bookmarks are lost after reopening a file with NP++. As an alternative for your workaround, I use the _Save session_-option, which also saves bookmarked lines. These bookmarks will be restored with the _Load session_-option...

**Comment by sasumner** [comment]
What is thought about changing the functionality to this?:

* `Bookmark line` unticked: `Clear all marks` button press clears only all redmarking
* `Bookmark line` ticked: `Clear all marks` button press clears all redmarking and all bookmarks

If it is desired to clear bookmarks without also clearing redmarking. then one would use `Search` -> `Bookmark` -> `Clear All Bookmarks`.

It is a bit obscure, but it avoids changing the user interface.

**Comment by Ekopalypse** [comment]
Sounds very good to me

**Comment by sasumner** [comment]
Hoping to still hear what the OP thinks, as well as any others that want to chime in...

Side note:  I sure would like it if github notification emails would be triggered to be sent with upvotes/downvotes.  Grrr.

**Comment by xylographe** [comment]
Makes perfect sense to me. When setting marks, while “Bookmark line” is unticked, you don't expect any changes to the bookmarks. Hence, when clearing marks, while “Bookmark line” is unticked, the bookmarks should also remain as they are.
