### ISSUE TITLE
Closing a monitored file without switching to it causes an access violation

### ISSUE THREAD

**Issue by CodeCasterNL** [notepad-plus-plus/notepad-plus-plus#3549]
### Description of the Issue
Notepad++ crashes when you close a tab with a file that's being monitored, if you don't switch to that tab first.

### Steps to Reproduce the Issue
1. Open a file which is being written to (couldn't repro if the file was static).  
2. Enable the built-in monitoring by clicking the eye icon (_"Monitoring (tail -f)"_) in the toolbar.
3. Open another file. You now have two tabs open: the first is the file being monitored (indicated by the eye icon), the second is the newly opened file.
4. Without switching to the first tab, close the first tab. That can be done by scroll-clicking the tab, or by clicking its red X.

### Expected Behavior
I would expect the eye icon to disappear and Notepad++ not to crash.

### Actual Behavior
The eye icon indicating the file is being monitored moves to the tab of the secondly opened file (now being the first tab). After a while (a few seconds up till a minute), Notepad++ crashes with an access violation.

### Debug Information
Notepad++ v7.4.2   (32-bit)
Build time : Jun 18 2017 - 23:34:19
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10 (64-bit)
Plugins : ComparePlugin.dll JSMinNPP.dll mimeTools.dll NppConverter.dll NppExport.dll NppTextFX.dll PluginManager.dll XMLTools.dll

**Comment by MetaChuh** [comment]
please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins if you update from version 7.5.9 or below.

thank you for your help and best regards.
