### ISSUE TITLE
view->zoom do not work with keyboard shortcut

### ISSUE THREAD

**Issue by luweitest** [notepad-plus-plus/notepad-plus-plus#355]
I am using a notepad (thinkpad x61), the keyboard shortcut ctrl+  ctrl- do not work with version 6.7.9

**Comment by MetaChuh** [comment]
closed due to:
* thinkpad x61 does not have a physical number keypad, so <kbd>ctrl</kbd> + <kbd>num +/-</kbd> is not available
* can be user solved, by using <kbd>ctrl</kbd> + <kbd>mouse wheel</kbd>, or by setting another keyboard shortcut, or by using a physical num pad.
