### ISSUE TITLE
Document Map Dragging Slow Painting and Slow Movement

### ISSUE THREAD

**Issue by josh08287** [notepad-plus-plus/notepad-plus-plus#3550]
### Description of the Issue
Popping out the Document map and dragging the document map causes an extreme delay.

### Steps to Reproduce the Issue
1. Open document map (starts docked).
2. Undock document map into its own window.
3. Grab title bar of document map and start dragging around.
4. Mouse seems to be slowed down and document map doesn't follow speed of mouse.

### Expected Behavior
I would expect the document map to behave like any other window when dragging and move with the speed of the mouse.

### Actual Behavior
Document map is slowed down and seems to be repainting every movement then re-applying the transparency to the window. I have transparent windows setting on in windows. 

It looks like it may be related to the dockable dialog. If the grabber is checking for docking ability on every mousemove event we would be checking at 1000 times per second for a high reporting mouse. This may need to be throttled or moved to a different design.

### Debug Information
Notepad++ v7.4.2   (32-bit)
Build time : Jun 18 2017 - 23:34:19
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : ON
Local Conf mode : OFF
OS : Windows 7 (64-bit)
Plugins : ComparePlugin.dll DSpellCheck2.dll MarkdownViewerPlusPlus.dll mimeTools.dll NppConverter.dll NppExport.dll PluginManager.dll PyNPP.dll Python Indent.dll SourceSwitch.dll XBrackets.dll

**Comment by josh08287** [comment]
This is still present in 7.5.1 both x86  and x64 versions.

**Comment by josh08287** [comment]
Still present (though seemingly slightly better) in 7.5.3.

**Comment by CookiePLMonster** [comment]
Still present in 7.5.4. The window is leaving marks on the parent window (like dragging windows did on pre-Vista when the window was frozen...) and it feels like it can't keep up with movements...

Replying so I can track this issue easier, as it may be worth investigating.

**Comment by josh08287** [comment]
It appears that this is fixed in 7.7 (64bit) (built May 19, 2019). There are still artifacts of the borders of the windows but they are much more manageable.
