### ISSUE TITLE
pointer-events in CSS not styled correctly

### ISSUE THREAD

**Issue by knalleDK** [notepad-plus-plus/notepad-plus-plus#3551]
In CSS markup "pointer-events" is never styled like e.g. "display" or "height". Any reason for that?

**Comment by ArkadiuszMichalski** [comment]
@knalleDK You still have this problem in latest Notepadt++? I can't reproduce it:

![kk](https://user-images.githubusercontent.com/2730894/93677766-27aa9b80-faad-11ea-8af3-67a7283da888.gif)

As we can see above `pointer-events` is treated the same as `display`.

**Comment by donho** [comment]
Outdated.
It's already fixed.

**Comment by knalleDK** [comment]
Actually I still see pointer-events unstyled. I have the latest notepad++ installed. Anything else I need to update? Or try?

**Comment by ArkadiuszMichalski** [comment]
Probably you use old `langs.xml` in your profile settings (here `%AppData%\notepad++\` in Windows). Remove it.

**Comment by knalleDK** [comment]
Perfect, I deleted it from dropbox (cloud settings).
