### ISSUE TITLE
Crash on pressing insert when text is selected

### ISSUE THREAD

**Issue by paul70078** [notepad-plus-plus/notepad-plus-plus#3556]
### Description of the Issue
Notepad++ freezes and crashes

### Steps to Reproduce the Issue
1. select a piece of text
2. press [insert]

### Expected Behavior
nothing

### Actual Behavior
Freeze/crash of Notepad++ 

### Debug Info
Notepad++ v7.4.2   (32-bit)
Build time : Jun 18 2017 - 23:34:19
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10 (64-bit)
Plugins : autosave2.dll ClipboardHelper.dll ComparePlugin.dll CustomizeToolbar.dll DoxyIt.dll mimeTools.dll NppCCompletionPlugin.dll NppConverter.dll NppExec.dll NppExport.dll NppFTP.dll NPPGit.dll NppSaveAsAdmin.dll PluginManager.dll Tidy2.dll VisualStudioLineCopy.Unicode.dll

**Comment by AngryGamer** [comment]
I can't replicate this crash. Maybe try without plugins enabled?

**Comment by dail8859** [comment]
Works for me. Try without plugins.
