### ISSUE TITLE
changing file line endings is not correctly updated in statusbar

### ISSUE THREAD

**Issue by DexterHaslem** [notepad-plus-plus/notepad-plus-plus#3557]
### Description of the Issue
If a file is externally modified and only the line endings change, the line ending indicator is not updated

### Steps to Reproduce the Issue
1. open a file in eg, CRLF line ending in notepad++
2. modify line endings of opened file with `dos2unix` tool
3. when notepad++ prompts to reload externally changed file, click yes

### Expected Behavior
The line ending type in status bar to update to the new 'Unix (LF)' value

### Actual Behavior
Status bar still said Windows (CR LF) line endings which caused some confusion

### Debug Information
if you close and reopen the file it will correctly report the line ending type.
Notepad++ v7.4.2   (32-bit)
Build time : Jun 18 2017 - 23:34:19
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 7 (64-bit)
Plugins : mimeTools.dll NppConverter.dll NppExport.dll PluginManager.dll

**Comment by CookiePLMonster** [comment]
Should be fixed with #4077

**Comment by CookiePLMonster** [comment]
Fixed by 46d0f12c3e687c83efbaa04f7ebd95616678226c
