### ISSUE TITLE
Find In Files - Multi-Threaded

### ISSUE THREAD

**Issue by msunde-aurea** [notepad-plus-plus/notepad-plus-plus#3562]
### Description of the Issue
Would it be possible to have Find In Files executed the search using multiple threads / in parallel. Currently running on an i7 CPU with an SSD drive and searching in several thousand files for particular words. Watching the Windows 10 task manager, it does not appear to be maxing out the system. Having a setting to increase the parallelism for Find in files would hopefully speed things up. Thank you.

### Steps to Reproduce the Issue

1.  Search / Find In Files
2. Enter a word and directory to search, click Find All
3. Watch disk and CPU usage in Windows 10 task manager.

### Expected Behavior
Use multiple CPUs / max out the SSD drive to speed up the find in files.

### Actual Behavior
Only using 1 CPU and SSD drive not maxed out.

### Debug Information
Notepad++ v6.9.2
Build time : May 18 2016 - 00:34:05
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10
Plugins : ComparePlugin.dll mimeTools.dll NppColumnSort.dll NppConverter.dll NppExport.dll NPPJSONViewer.dll PluginManager.dll

**Comment by msunde-aurea** [comment]
Same behavior with:
Notepad++ v7.4.2   (64-bit)
Build time : Jun 18 2017 - 23:38:43
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10 (64-bit)
Plugins : mimeTools.dll NppConverter.dll

**Comment by CookiePLMonster** [comment]
Sounds like a good candidate to use Thread Pools:

https://msdn.microsoft.com/en-us/library/windows/desktop/ms686766(v=vs.85).aspx

Main point towards using them would be high level of abstraction - no need to manage threads manually nor even care how many of them are going to be utilized - just split the task into jobs, schedule them and let the OS decide how many threads to involve.

Sadly, thread pools are only available since Windows Vista. Worst case, we'd fall back to synchronous (existing) code on XP?

**Comment by chrisaige** [comment]
Has any progress been made here?

**Comment by Sil20** [comment]
The Multi-thread search should also allow the user to keep using the Editor during search.

**Comment by Faq** [comment]
@donho is this planned in some near future? Would really increase performance by using multi threading.

**Comment by bbommer** [comment]
This is the **only feature I'm missing** in np++ for a decade: Have the find-in-files search run in it's own thread, and output it's progress where the search results get listed. I wouldn't even need multiple threads/searches, just not blocking the GUI.
In 99% of the times I use the find-in-files (with a probably badly guessed regex on ~20k files) I try to find that file manually in parallel. But I can't open any files while the search is running.

**Comment by donho** [comment]
Scintilla is not thread safe, hence find in file cannot be asynchronous.

**Comment by mirh** [comment]
Scintilla used to [blame you](https://sourceforge.net/p/scintilla/bugs/1194/?page=1) actually. 
And regardless of whose fault it is, having the program die on search is still a massive bug.

**Comment by sasumner** [comment]
@mirh

>Scintilla used to blame you actually.

How so?  Specifically.

**Comment by mirh** [comment]
The user was complaining about slow opening times, suggested multithreading, and he was replied that loading wasn't up to them. 
And even if it required spawning multiple processes, again I don't see why hanging everything down to the UI should be accepted.

**Comment by xylographe** [comment]
@mirh When you select multiple files in Explorer, then choose "Edit with Notepad++", Explorer will start a new instance of NPP for each selected file. When opening multiple files in NPP from a command line interpreter there's no problem. For example,
`npp @(git ls-tree --name-only HEAD PowerEditor/installer/APIs/)` in powershell.

**Comment by mirh** [comment]
I know, I'm saying that (when it comes to searching) even something as convoluted as this "fix" would still be better at the end of the day than the status quo of a locked up UI.

**Comment by TAbdiukov** [comment]
> Has any progress been made here?

It's been 5 years, and no progress

**Comment by mirh** [comment]
Bruh, it seems like steps forward for asynchronicity were made
https://sourceforge.net/p/scintilla/feature-requests/1427/

**Comment by BX442** [comment]
The steps must be tiny :)

**Comment by nyamatongwe** [comment]
> @donho: Scintilla is not thread safe, hence find in file cannot be asynchronous.

Scintilla does not have to be thread-safe to use a secondary thread for find in files. SciTE has performed multi-threaded find in files since 2005. It works by sending the results of the find in files operation to the main thread for display and is implemented by calling code similar to `SendMessage(hwndOutput, SCI_APPENDTEXT, len, text)` from the search thread. `SendMessage` synchronizes between threads, running the `SCI_APPENDTEXT` on the UI thread.

**Comment by donho** [comment]
Thank you @nyamatongwe for the information.
I will check the code SciTE and see what I can do for Notepad++.

**Comment by kekko-dos** [comment]
I hope these issues are not a show stopper, personally I use this feature a lot, on large folders; even on a fairly new pc it took several minutes to search through 40k files. 
What if function findInFilelist uses plain _fopen_ instead?  This should settle any thread safety issues.

**Comment by donho** [comment]
I checked again the find in files code in Notepad++ for evaluating the feasibility of multi-thread.
Unfortunately, it's not possible - if we want to keep the current features.

**Comment by TAbdiukov** [comment]
Agent Ransack can search in a multi-threaded manner, but Notepad++ cannot. Considering that some of us have big projects - this is sad.
