### ISSUE TITLE
TextFX Insert Date & Time has a coding error with Uft8 encoding on Notepad++ Chinese Version

### ISSUE THREAD

**Issue by aunhappy** [notepad-plus-plus/notepad-plus-plus#3564]
I have encountered a character coding problem，when I inserted time in the Utf8 encoded file . As you can see , it give 7:15 2017/7/24 чǚһ and not 7:15 2017/7/24 星期一(Monday) . It is normal in ANSI encoded files . Is there anything can do to help?

**Comment by dail8859** [comment]
This is related to the TextFX plugin and not Notepad++
