### ISSUE TITLE
In multi-screen machine, the Find window opens on the screen Npp was originally opened in, not the one it's currently on

### ISSUE THREAD

**Issue by vkarosas** [notepad-plus-plus/notepad-plus-plus#3565]
### Steps to Reproduce the Issue

1. On a machine with more than one screen, open Notepad++
2. Drag it to another screen
3. Ctrl+F

### Expected Behavior

The Find window opens on the same screen where Notepad++ is

### Actual Behavior

It opens on the original screen, where Notepad++ was first opened. This is quite confusing, especially when the two screens are far enough away from each other. It can then seem that the Find window hasn't appeared at all. Even if I see it, I have to turn my head or move my gaze to another screen to interact with the Find window.

### Debug Information

Notepad++ v7.4.2   (32-bit)
Build time : Jun 18 2017 - 23:34:19
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10 (64-bit)
Plugins : mimeTools.dll NppConverter.dll NppExport.dll NppFTP.dll PluginManager.dll

**Comment by dail8859** [comment]
I'm not saying this isn't a bug, but at least for now as a work around if you press `Ctrl + F` again it will move the find window to the center of where Notepad++ is.

**Comment by wistlo** [comment]
Wish I'd found  dail8859 's comment a year ago.   That works, two `Ctrl F` and it's right in front of me.

On occasion I do want the default behavior where it opens on a different screen.  Best of both worlds.

**Comment by sasumner** [comment]
@wistlo

A change was made to 7.8.5 and later such that the find window's last known position is remembered from run to run of Notepad++.  This includes handling multi-screens.  If you are finding this is not the case, please let us know.

Here is the issue for that: #905
The PR: https://github.com/notepad-plus-plus/notepad-plus-plus/pull/7898
and the N++ commit:
https://github.com/notepad-plus-plus/notepad-plus-plus/commit/4cc6215e6359a1cd7bb184ed96129cc0e7e023d8

I'm closing this now as one that should've been closed with the above commit but was obviously forgotten.
