### ISSUE TITLE
Fortran Language if Make language compact is checked

### ISSUE THREAD

**Issue by Cyrillev91** [notepad-plus-plus/notepad-plus-plus#3566]
### Description of the Issue
If in preference>>Language>>Make language compact menu is **checked** : 
in Language Menu you can select : 
       - "Fortran (free form)"
       - "Fortran (fixed form)"

If in preference>>Language>>Make language compact menu is **not checked** : 
in Language Menu you can select only
       - "Fortran"                 _(= free form)_

Expected : 
       - "Fortran (free form)"
       - "Fortran (fixed form)"

### Debug Information
Notepad++ v7.4.2   (32-bit)

**Comment by MAPJe71** [comment]
My **compact** language menu looks like this:

![capture-2017-07-20-21 14 482017-07-26-21 08 02](https://user-images.githubusercontent.com/6494038/28638928-b86e8638-7246-11e7-91f0-f46742d51c7b.png)

**Comment by Cyrillev91** [comment]
I have corrected my post

**Comment by Cyrillev91** [comment]
![fortran](https://user-images.githubusercontent.com/12849364/28639910-2f31d524-724a-11e7-9d1a-21313732de83.jpg)
