### ISSUE TITLE
Scroll position is changed for very long wrapped lines

### ISSUE THREAD

**Issue by ygoe** [notepad-plus-plus/notepad-plus-plus#3570]
### Description of the Issue
When the user switches between file tabs, the scroll position of the file is not kept. So the user sees another part of the file than where they previously left the tab.

### Steps to Reproduce the Issue
1. Activate automatic line wrapping and scrolling beyond the last line
2. Open or create a file with a very long line that wraps over more than a screen page of display lines
3. Add a few more shorter lines
4. Scroll the view so that it begins with some of the (not all) wrapped lines and following complete lines are also visible
5. Open or create another file
6. Switch back to the other file

### Expected Behavior
The vertical scrolling should be where I left it, i. e. wrapped lines are at the top and the following lines are also visible.

### Actual Behavior
The scrolling is reset so that the beginning of the wrapped line is at the top (can be seen at the line numbers) and the following lines are not visible because they're too far down. The cursor position is not affected by this. So if the cursor was previously visible in one of the following lines, it now no longer is.

### Debug Information
Notepad++ v7.4.2   (32-bit)
Build time : Jun 18 2017 - 23:34:19
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 7 (64-bit)
Plugins : mimeTools.dll NppConverter.dll NppExport.dll NppFTP.dll PluginManager.dll

**Comment by fml2** [comment]
I can confirm this with NP++ v. 7.5.1 (official download) on Win XP.
