### ISSUE TITLE
authenticode  and scintilla errors after upgrading to 7.4.2

### ISSUE THREAD

**Issue by punknubbins** [notepad-plus-plus/notepad-plus-plus#3573]
![authenticode_error](https://user-images.githubusercontent.com/6868903/28731860-37146476-739b-11e7-89c0-6568830f9a05.png)
![scintilla_error](https://user-images.githubusercontent.com/6868903/28731866-3ac3d6ba-739b-11e7-9c02-82e15706badf.png)

### Description of the Issue

OS version: Win7 Enterprise 64bit
App version: notepad++ 7.4.2 32bit

After installing the latest version of the notepad++ (32bit to retain plugin compatibility) the application fails to launch.

Possibly related: I am on a corporate network with a transparent web proxy and corporate mandated middleman cert so if your application is validating a cert against a web cert, the application will always get a mismatch.

### Steps to Reproduce the Issue

1. Install 7.4.2
2. Launch
3. receive errors, application closes after errors are dismissed

### Expected Behavior

Application would launch

### Actual Behavior

Received error on launch then app closes after error is dismissed

### Debug Information

Workaround was to downgrade back to 7.3.3

**Comment by ArkadiuszMichalski** [comment]
@punknubbins Do you still have this problem in latest Notepad++ version?

**Comment by donho** [comment]
Outdated.
