### ISSUE TITLE
"hide sybol" in theme files

### ISSUE THREAD

**Issue by TekBear** [notepad-plus-plus/notepad-plus-plus#3578]
### Description of the Issue
While making changes to theme/style I noticed the style label was "HIDE SYBOL"  (seen it on batch and asp style xml code. (Npp v6.7.7)

### Steps to Reproduce the Issue
1. Open xml files  
2. search for "sybol"

Notepad++ v6.7.7 (32-bit)
Build time : Apr 16, 2015 - 00:41:52
Path : C:\Program Files\npp\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows (32-bit)
Plugins : 
- AutoSaveU.dll           
- CustomizeToolbar.dll    
- DSpellCheck.dll         
- HTMLTag_unicode.dll     
- mimeTools.dll           
- MultiClipboard.dll      
- NppConverter.dll        
- NppExport.dll           
- NppFTP.dll              
- NppSnippets.dll         
- NppTextFX.dll           
- PluginManager.dll       
- ReloadButton.dll        
- XBrackets.dll           
- XMLTools.dll  

Is this a spelling error? If so can I edit and change the value to "HIDE SYMBOL" 
If the spelling error is still in the current release should this be changed in the (20+) XML theme files  for a future releases?

**Comment by ArkadiuszMichalski** [comment]
@donho This exist in all themes for `<LexerType name="batch" desc="Batch" ext="">`, it's intentional? If yes maybe close this bug?

**Comment by TekBear** [comment]
So i guess it means hide symbol
