### ISSUE TITLE
"Send via Outlook" crashes Outlook on new, unsaved document

### ISSUE THREAD

**Issue by robmcl4** [notepad-plus-plus/notepad-plus-plus#3579]
### Description of the Issue

Outlook crashes when the "Send via Outlook" menu item is clicked.

### Steps to Reproduce the Issue

1. Open Outlook
2. Open Notepad++, open a new document (ctrl+n)
3. Click Run -> Send via Outlook

### Expected Behavior

Outlook should not crash. Maybe Notepad++ displays an error message telling me to save first.

### Actual Behavior

Notepad++ crashed

### Debug Information

Outlook version: 1707 (Build 8326.2058)

```
Notepad++ v7.3.3   (32-bit)
Build time : Mar  8 2017 - 03:37:37
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10 (64-bit)
Plugins : mimeTools.dll NppConverter.dll NppExport.dll PluginManager.dll 
```

**Comment by MetaChuh** [comment]
the outlook function has been completely removed.
