### ISSUE TITLE
Is this project alive?

### ISSUE THREAD

**Issue by manake** [notepad-plus-plus/notepad-plus-plus#3580]
v.7.4.2

1. "gpup has stopped working" when trying to install "XML Tools" from plugin manager (Windows 10).
2. "Plugin manager needs to be updated" is a persistent message that doesn't disappear even after updating it.
3. "There are still some pending actions to complete installing or removing some plugins. Would you like to do these now (Notepad++ will be restarted)?" persists and doesn't disappear for me.
4. TextFX plugin should be removed from the plugins repository because most of its features don't work and crash Notepad++. (E.g. TextFX HTML Tidy feature doesn't work at all.)
5. FingerText is a highly useful plugin but its UI is all broken and unusable anymore on high PPI screens.
6. Template literals in JS don't get proper highlighting.
7. Ctrl+q doesn't properly comment/un-comment code in <script> tags and <style> tags in HTML documents.
8. NppFTP has too small UI on 4k+ screens.
9. A highly necessary "\n" doesn't work in regex anymore (already reported elsewhere by someone else).

And there are 1,693 other open bugs for years.

This software starts to become obsolete and fixes are not coming. I'm just wondering if there are any plans to continue development or will it not be updated anymore?

**Comment by manake** [comment]
I think instead of having 1600 not resolved bugs you should open a voting board and list bugs and features.

E.g.
1. \n not working +1000 upvotes
2. NppFTP UI on 4k +200 upvotes
3. XML Tools less problematic installation +10 upvotes
4. etc.
such voting ranking made by users would indicate where to focus development resources. Some users who like Notepad++ like me could even donate to other developers who could code this.

**Comment by dail8859** [comment]
1, 2, 3, 4, 5, 8 are related to 3rd party plugins and need reported to the respective plugin projects.

9 works fine for me.

**Comment by Nightfirecat** [comment]
Seems clear based on commit history that the codebase is still being updated: https://github.com/notepad-plus-plus/notepad-plus-plus/commits/master. Keep in mind that [this project is maintained by exactly one person](https://github.com/orgs/notepad-plus-plus/people) so given its popularity, it is not possible for him to get around to every issue in as timely a manner as we would like.

**Comment by chcg** [comment]
- 1, 2, 3, are fixed with https://github.com/bruderstein/nppPluginManager/releases/tag/v1.4.9, but that version was never accepted to be bundled with N++. See https://notepad-plus-plus.org/community/topic/14315/notepad-7-5-release, PluginManager is no longer part of N++. So the user has to update on his own.
- 8, already reported as https://github.com/ashkulz/NppFTP/issues/171
- 4, TextFX is outdated, see http://docs.notepad-plus-plus.org/index.php/TextFX's_Future

as all this is just voluntary work, don't expect professional service.

Cleaning up all this N++ issues would be work for a full time ticket manager for quite some time, just to get them to a updated state, not talking about fixes.

**Comment by MetaChuh** [comment]
please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins if you update from version 7.5.9 or below.
if your issue still persists, and it is still of relevance, please feel free to file a new issue as easy to understand and reproducible as possible.

thank you for your help and best regards.

**Comment by sasumner** [comment]
>And there are 1,693 other open bugs for years.

1132 is the current count.  PROGRESS!
