### ISSUE TITLE
New feature: Autocomplete in Batch

### ISSUE THREAD

**Issue by marcoM32** [notepad-plus-plus/notepad-plus-plus#3585]
## Description of the Issue
Why in the batch language the autocomplete is not present?

## Steps
1) Open a new document
2) Select Batch language
3) Write "pause" or any other keyword

## Actual Behavior
4) The autocomplete pop-up is correctly present

## Expected Behavior
4) The pop-up not appear because the functionality is not implemented

![batch](https://user-images.githubusercontent.com/16719549/28861222-3121b500-7760-11e7-9a10-c0f6121a23e7.png)

Please consider my pull requests ![#3157](https://github.com/notepad-plus-plus/notepad-plus-plus/pull/3157)

**Comment by dail8859** [comment]
Closed by de648eff622d9d5799b35335536b13e507cd931c
