### ISSUE TITLE
(bug) Encoding change from UTF-8 to TIS-620 when saving and closing

### ISSUE THREAD

**Issue by rebusx** [notepad-plus-plus/notepad-plus-plus#3588]
### Description of the Issue
When I create and save a text file containing only the text "Хз." (in Russian), which has Windows string ending and UTF-8 w\o BOM encoding, it transforms to TIS-620 encoding, and containing text becomes "ะฅะท." Seems to not happen with longer texts inside files. Also doesn't happen if you change "Хз" to some other two letters, for ex. "Чо", "Иа", "Ха" (in Russian).
Checked on versions 7.3.3 (32bit) and 7.4.2 (64bit).
Plugins disabling makes no effect.
OS is Windows 7 64-bit.

### Steps to Reproduce the Issue
1. Create a file with Windows string ending and UTF-8 w\o BOM encoding
2. Write "Хз." in it (in Russian)
3. Save and close
4. Reopen this file

### Debug info
Notepad++ v7.4.2   (64-bit)
Build time : Jun 18 2017 - 23:38:43
Path : D:\Program Files\Notepad++\notepad++.exe
Admin mode : ON
Local Conf mode : OFF
OS : Windows 7 (64-bit)
Plugins : mimeTools.dll NppConverter.dll

![screen](https://user-images.githubusercontent.com/30683227/28908433-4ca34f38-782c-11e7-86e7-24200e5ff55b.png)

**Comment by rddim** [comment]
Hello, this known bug from very long time. For now you can disable the `Autodetect character encoding` in `MISC.` preferences.

**Comment by CookiePLMonster** [comment]
This particular issue is fixed when uchardet is updated!

**Comment by rebusx** [comment]
Checked on 7.6.6 x64. Nothing changed. Can this be opened?

**Comment by DalBrar** [comment]
Can confirm, this is happening to me on NPP v7.6.6, built time: Apr. 3, 2019 - 23:49:50
