### ISSUE TITLE
add command line option to import UDL

### ISSUE THREAD

**Issue by CWempe** [notepad-plus-plus/notepad-plus-plus#3590]
It would be great if there was an easy option to install/import UDL files via command line.

Something like this:

```
notepad++.exe --import-UDL /path/to/my-first-udl.xml
notepad++.exe --import-UDL /path/to/my-second-udl.xml
```

This would make setting up a new PC much easier.

Yes, I know I could just copy my `userDefineLang.xml`.

**Comment by donho** [comment]
Now every UDL can have its own file so import feature is no more need:
https://npp-user-manual.org/docs/user-defined-language-system/#udl-file-locations
