### ISSUE TITLE
Plugin Manager will not display once i loaded the plugins

### ISSUE THREAD

**Issue by kwinford1** [notepad-plus-plus/notepad-plus-plus#3593]
### Description of the Issue
I downloaded all the plugins for Notepad++. However after I downloaded the plugins, I needed to go back and delete some of the plugins. So I went back into plugins, find the Plugin Manager, clicked on Show Plugin Manager and then NOTHING. The Plugin Manager won't come up. So why won't the Plugin Manager come up anymore after downloading plugins?  I even tried going in as Run As Administrator and Nothing. 

Plugin Manager will no longer come up.

### Steps to Reproduce the Issue

1. 
2. 
3.

**Comment by dail8859** [comment]
As of Notepad++ v7.5 the Plugin Manager is no long being shipped with Notepad++. See https://notepad-plus-plus.org/news/notepad-7.5-released.html

All Plugin Manager related issues should be reported to https://github.com/bruderstein/nppPluginManager/issues
