### ISSUE TITLE
Update Style Configurator TCL INSTRUCTION_WORD Default keywords

### ISSUE THREAD

**Issue by m7j4k9** [notepad-plus-plus/notepad-plus-plus#3596]
### Description of the Issue

The default keywords for Tcl are out of sync with the current release (8.6.6).

### Steps to Reproduce the Issue

1. Create a new file and set its language to Tcl
2. Enter these lines
```
# new commands in 8.4
lset is not a default keyword

# new commands in 8.5
apply is not a default keyword
chan
dict
lassign
lrepeat
lreverse
unload

# new commands in 8.6
coroutine
lmap
tailcall
throw
try
yield
yieldto
zlib

# for comparison
after is a default keyword
append is a default keyword
...
```
3. Look at the colors / highlighting

### Expected Behavior

The new command names should be highlighted just like the old command names.

### Actual Behavior

The new command names are not highlighted.

### Debug Information

Notepad++ v7.4.2   (64-bit)
Build time : Jun 18 2017 - 23:38:43
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 7 (64-bit)
Plugins : mimeTools.dll NppConverter.dll 

### References to new command names

- Changes in Tcl/Tk 8.4 http://wiki.tcl.tk/3099
- Changes in Tcl/Tk 8.5 http://wiki.tcl.tk/10630
- Changes in Tcl/Tk 8.6 http://wiki.tcl.tk/21276

**Comment by MetaChuh** [comment]
please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins if you update from version 7.5.9 or below.
if your issue still persists, and it is still of relevance, please feel free to file a new issue as easy to understand and reproducible as possible.

thank you for your help and best regards.

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
(no extra account is needed, just use your github account to sign in)
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)
