### ISSUE TITLE
Labels overflow in search dialog find button (italian)

### ISSUE THREAD

**Issue by eng-marani** [notepad-plus-plus/notepad-plus-plus#3597]
The italian translation of "<< Find" and "Find >>" button is inaccurate. The text "Trova Successivo" is too much long and this causes an ugly button label overflow
![image](https://user-images.githubusercontent.com/14199364/28963128-4b794554-7908-11e7-9c30-bc0840330047.png)
I suggest to change the label as "<< Trova" and "Trova >>" instead of "<< Find" and "Trova Successivo"

Hope this helps,

**Comment by dinkumoil** [comment]
Seems to be reverted. See 4d921b7
