### ISSUE TITLE
PowerShell language parser confused by escape character.

### ISSUE THREAD

**Issue by munrobasher** [notepad-plus-plus/notepad-plus-plus#3598]
### Description of the Issue
The language parser gets confused by a PowerShell escape string and shows the rest of the text in light grey, i.e. it's not recognising the end of the string correctly.

### Steps to Reproduce the Issue
Copy and paste the following into a ps1 file:
$oneString = "`"" # not spotting end of string
if ($oneString) {Write-Host "If statement shown in light grey and this string is highlighted incorrectly"}

### Expected Behavior
Parser should identify the end of the $oneString correctly and display the comment in green.

### Actual Behavior
End of string not recognised so following comment shown in grey.

A workaround is to not use the ` escape character and change to $oneString = """"

### Debug Information
Notepad++ v7.4.2   (32-bit)
Build time : Jun 18 2017 - 23:34:19
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10 (64-bit)
Plugins : mimeTools.dll NppConverter.dll NppExport.dll PluginManager.dll SpellChecker.dll 

![image](https://user-images.githubusercontent.com/13134946/28963379-d4f10b6c-7900-11e7-90b8-cfa20004a335.png)

**Comment by plasticsteak1** [comment]
I've run into this problem as well. Thanks for posting.

**Comment by dail8859** [comment]
Fixed in Notepad++ v7.7 since it updated to Scintilla v4.1.4
