### ISSUE TITLE
Notepad++ is locking files in my Google Drive folder

### ISSUE THREAD

**Issue by Eldaw** [notepad-plus-plus/notepad-plus-plus#360]
Google Drive has been periodically crashing on my Windows 7 PC for some unknown reason. So I decided to uninstall it.

To my suprise, the uninstaller told me that it could not get exclusive access to this file:
C:\Users\%username%\AppData\Local\Google\Drive\user_default\sync_config.db

So I used a program called Unlocker to have a look at what application currently has files open in that location. Guess what?

Notepad++ has locks on 3 files in that folder:
sync_config.db-shm
sync_config.db-wal
sync_config.db

So I suspect Notepad++ is the culprit responsible for Google Drive crashing all the time.

In my Notepad++ settings, 'Settings on cloud' is currently set to 'No Cloud' and I've never changed it to anything else.

**Comment by milipili** [comment]
If Google Drive crashes, it is not the fault of notepad++, it is a bug for Google Drive. However we would have to check if n++ really uses this file (and not that this file is used by the system open dialog for example).

Anyway, AFAIK, the "settings on Cloud" will be removed by a more simpler method.

**Comment by Eldaw** [comment]
Yes, whether the crash is directly caused by this behaviour or not, Notepad++ should definitely not be interfering with the configuration files of Google Drive, especially since I've never configured it to do anything with Google Drive.

My suspicion about the cause of the crash is that Google Drive is probably not expecting its configuration files to be locked by another application. And when Google Drive itself is then unable to write to its own configuration files, bad things happen. That's my theory.

**Comment by milipili** [comment]
Indeed.

**Comment by ariccio** [comment]
> Anyway, AFAIK, the "settings on Cloud" will be removed by a more simpler method.

Can you elaborate?


> My suspicion about the cause of the crash is that Google Drive is probably not expecting its configuration files to be locked by another application. And when Google Drive itself is then unable to write to its own configuration files, bad things happen. That's my theory.

Did you ever get a dump of the crashing Google Drive?

**Comment by milipili** [comment]
@ariccio We don't care here of a crash of Google Drive. I agree that n++ should not keep a lock for some reasons on an external file.

AFAIK maintaining this kind of feature is kinda hard. These products always break the API and we always have to catch up, which is really annoying for users. Anyway since n++ only uses local files on a mounted remote folder, be able to simply select a target folder is probably more efficient and quite less error-prone.

**Comment by ariccio** [comment]
> AFAIK maintaining this kind of feature is kinda hard. These products always break the API and we always have to catch up, which is really annoying for users. Anyway since n++ only uses local files on a mounted remote folder, be able to simply select a target folder is probably more efficient and quite less error-prone.

I actually agree. [I'm on the "minus 100 points"](http://blogs.msdn.com/b/ericgu/archive/2004/01/12/57985.aspx) side of things. If it helps, so is Raymond Chen.

**Comment by ariccio** [comment]
> We don't care here of a crash of Google Drive.

Oh I know, but I'm (personally) curious about that crash. It's unusual for file-locking issues to *crash* a process.

I'm wondering, maybe a plugin is at fault? I've seen all sorts of weird plugin locking issues... a plugin once wouldn't let go of the *loader lock*, so I could break into notepad++.exe in the debugger!

**Comment by milipili** [comment]
See 5e240147c51b6c27f1accbcfa191d9ddc4967e68
