### ISSUE TITLE
Color for inactive selected elements

### ISSUE THREAD

**Issue by KlausiD** [notepad-plus-plus/notepad-plus-plus#3600]
### Steps to Reproduce the Issue

1. Open a few documents
2. open Doc Switcher
3. open Function List
4. Doubleclick  on a function in the funktion list
   or click a file in the doc switcher

-> now the focus is in the document.
     the selected element in the the Doc switcher or Function List can not be seen very bad!
see also  https://github.com/notepad-plus-plus/notepad-plus-plus/issues/715

### Expected Behavior
can you change the color for selected elements that have no focus.
For win7 there was the trick to change the 3D-Collor see:
https://www.windows-7-forum.net/threads/farbe-fuer-inaktive-markierungen-sic.16104/
 Contribution 12	

Now i have win10
and unfortunately I do not know how I can change it there.

Can not these colors be set in the program as with style settings?

**Comment by GaryBloom** [comment]
This seems to be related to the default theme settings in stylers.model.xml. 
In almost all the other themes (except maybe for "Solarized-light," which uses the same exact "problematic" background color), there is no issue seeing the selected function name when the Function List pane does not have focus. So, changing the selected theme via "Settings / Style Configurator..." is a workaround...

**Comment by GaryBloom** [comment]
The other themes look better, not because they change this strange color, but rather they all choose pane background colors that have better contrast with the unchanging field background color, which I guess is inherited from the OS, as I don't see anyway to find it or change it. At least not yet.

**Comment by GaryBloom** [comment]
So this color is inherited from the Windows theme. Changing the Windows theme can make the unfocused function selection more visible. On Win 10, there's no easy way to change this setting. A quick look into editing the Win 10 registry was unsuccessful.
It's not ideal as it is now, but it's usable. If unable to view the selected function name while the function list pane is not selected, the user can always click on the Function List title bar to restore focus to the Function List pane and view the selected function.
Also, the user can improve selected function name visibility either through changing the NPP theme or the Windows theme.
To fix this programmatically, the user would need the ability to override the system theme settings, at least for this one application of 3D Objects in the Function List pane and any other panes which exhibit similar trouble.

**Comment by GaryBloom** [comment]
But maybe a good workaround is as simple as changing the style assigned to those function list names to a style which does not use the system 3D Objects background color.

**Comment by ozone10** [comment]
Fixed in https://github.com/notepad-plus-plus/notepad-plus-plus/commit/d3b026bfeb96eb39e0402673d68dd04e640e2e1e

**Comment by alankilborn** [comment]
Suggest CLOSING this issue.
