### ISSUE TITLE
using control key locks notepad++ up

### ISSUE THREAD

**Issue by dexonter** [notepad-plus-plus/notepad-plus-plus#3602]
### Description of the Issue

using w7 64 pro - up to date
notepad++ - up to date
no plugins or something installed, just the program that was downloaded through ninite
### Steps to Reproduce the Issue

1. open notebad++ from start menu
2. go into a file
3. press somewhere in the text the control key
4. program locks up

### Expected Behavior

not locking up?
### Actual Behavior

program just hangs
### Debug Information

IF i start notepad++ as an administrator, this does not happen

### Additional Info
no keystroke modification program present on PC except Logitech SetPoint for the keyboard, but ctrl key is unmapped/not used
the ctrl key works normally and as expected in all other applications including windows

**Comment by dail8859** [comment]
This seems to be unrelated to N++ as no one else has reported this behavior and it behaves differently for you in admin mode.
