### ISSUE TITLE
Modified Date not updated on networked drive (webdav)

### ISSUE THREAD

**Issue by jhettinger** [notepad-plus-plus/notepad-plus-plus#3604]
### Description of the Issue
I'm running Notepad++ v7.4.2 64bit on Windows 7 Professional.  Works great, no known issues on most drives, but on my encrypted network drive, which uses webdav, the Modified Date does not get updated.  The file is saved, everything else is OK, as far as I know, except the Modified Date doesn't change.  Other programs, such as Notepad, do update the Modified Date.  The encrypted drive is managed and served by cryptomator:  https://cryptomator.org/

### Steps to Reproduce the Issue
1. Install Cryptomator on a Windows 7 OS.
2. Create Cryptomator vault and map to drive, for example z:
3. Create text file z:\foo.txt
4. Open z:\foo.txt with Notepad++
5. Open z:\ with Windows Explorer
6. Edit and save changes to z:\foo.txt within Notepad++, note that the Modified Date does not change
7. Edit and save changes to z:\foo.txt in any other editor, such as Notepad, and the Modified Date is updated.

### Expected Behavior
See step 7 above.

### Actual Behavior
See step 6 above.

### Debug Information
Not applicable.

I am a developer and would be willing to commit some time to this issue if someone would point me in the right direction, or at least verify this is really a problem with Notepad++ and not some odd webDav issue or something else I'm not aware of.  Thanks.

**Comment by MetaChuh** [comment]
please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins if you update from version 7.5.9 or below.
if your issue still persists, and it is still of relevance, please feel free to file a new issue as easy to understand and reproducible as possible.

thank you for your help and best regards.

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
(no extra account is needed, just use your github account to sign in)
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)
