### ISSUE TITLE
Different Icons for different source files

### ISSUE THREAD

**Issue by lostwithouthope** [notepad-plus-plus/notepad-plus-plus#3606]
### Description of the Issue
this is a very, very low priority issue.  But as NP++ is such an awesome editor it would be nice if it could install different icon for different file type (at least the most common once). I could imagine the standard icon but without the pen and instead an acronym like "c" or "h" on the green sheet.

### Steps to Reproduce the Issue
Install NP++, and use it as default editor for various source files and have a look at different source in the file explorer of your choice

### Expected Behavior
Different icons at least for the most common file types, e.g. .c, .cpp, .h, .hpp, .bat and so

### Actual Behavior
Just a single icon for all files.

**Comment by dev-101** [comment]
+1

This is exactly what I'm dealing with right now. All files have the same icon. Under older OS like Win XP we could easily override and set custom file types icons, but this is such a pain in newer Windows versions. I like to have visual cue about file types mixed in a single folder.

**Comment by reese64** [comment]
I'm surprised that after 4+ years we still don't have an option to keep original icons or set custom icons per extension. Some tricks with early versions of Windows 10 worked but it's almost impossible to do it now (if we don't count cloning _notepad++.exe_ as a solution).

:(

**Comment by donho** [comment]
I suppose you're talking about the system icons.
I'm not for changing them as the most of users. So this feature won''t be implemented.
