### ISSUE TITLE
Prevent "may be protected" on hidden files on samba share

### ISSUE THREAD

**Issue by bammab** [notepad-plus-plus/notepad-plus-plus#3607]
### Description of the Issue
It is not possible to save an hidden file on a samba netshare. If you try, you get following message:
"The file cannot be saved and it may be protected.
Do you want to launch Notepad++ in Administrator mode?"

I found the reason and could also fix the problem. 
The reason is the mapping of the hidden flag for files beginning with an dot (setting hide dot files). Notepad++ try to remove the flag, because the windows api (createfile and so fopen) fails to open a hidden file in write mode without the needed hidden/system flag, but it is not possible to remove the flag in real!
The fix is to open (only) such files in read mode with write permission, clearing the content and then writing to file (a manuell truncate, like opening in writemode does).

You can see the fix unter my fork: 
https://github.com/bammab/notepad-plus-plus/tree/hiddenfilefixToMaster

I have read your guideline, but first of all, I am not an c/c++ programmer. But it's a small fix, so hopefully I don't break anything :-)
If something is formated wrong, I would fix this (e.g. the brackets were now in its own lines...). This is my first time I use GitHub - so it would be awesome if you could help a little bit.
If the bug is accepted I would create a pull request  (and rebase one more time to be at current state), where we could discuss possibly needed changes.

I searched for issues with "hidden" and "protected" and issue #2085 could be the same problem, but here I don't have the system flag, so I made a new bug report - sorry if a duplicate.

### Steps to Reproduce the Issue
1. Create a file ".gitignore" on a Samba share with hide dot files option
2. Open file in notepad++ and write text "Hello World!"
3. Try to save the file
4. You got a message, that the file could not be saved, because it may be protected...

### Expected Behavior
Could save the file!

### Actual Behavior
Could not save the file and only the message to get admin-rights (which don't help!) pop up.

### Debug Information
Notepad++ v7.4.2   (32-bit)
Build time : Jun 18 2017 - 23:34:19
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10 (64-bit)
Plugins : ComparePlugin.dll HexEditor.dll JSMinNPP.dll mimeTools.dll NppConverter.dll NppExport.dll NppFTP.dll PluginManager.dll XMLTools.dll

**Comment by MetaChuh** [comment]
please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins if you update from version 7.5.9 or below.
if your issue still persists, and it is still of relevance, please feel free to file a new issue as easy to understand and reproducible as possible.

thank you for your help and best regards.

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
(no extra account is needed, just use your github account to sign in)
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)
