### ISSUE TITLE
Text does not fit on the button

### ISSUE THREAD

**Issue by coaperator** [notepad-plus-plus/notepad-plus-plus#3608]
Text does not fit on the button
![default](https://user-images.githubusercontent.com/6645911/29101965-48f7bb38-7ccf-11e7-9291-9506af7f17c5.PNG)

In older versions, the button was wider and was lower

**Comment by MAPJe71** [comment]
The language file needs to be updated to translate "<< Find" and "Find >>".

**Comment by rddim** [comment]
#3415

**Comment by dinkumoil** [comment]
Seems to be reverted. See 4d921b7
