### ISSUE TITLE
Using cmake for building notepad++

### ISSUE THREAD

**Issue by milipili** [notepad-plus-plus/notepad-plus-plus#361]
roadmap: the 7.x branch will use `cmake` as configure tool
- As already proposed, we will decompose the projet in several sub-libraries (see #116)
  (files and folders will be moved later)
- the whole compilation process must be handled (boost included)
- cmake >= 3.0 will be required

notes: see #230

**Comment by Croydon** [comment]
:+1:

**Comment by NN---** [comment]
Any progress about cmake ?

**Comment by milipili** [comment]
It is not far from working. I will finish next week when i will be back

**Comment by NN---** [comment]
The only drawback is that you cannot add files using VS IDE.
Can you open a cmake project using CLion IDE ?

**Comment by milipili** [comment]
CLion requires cmake projects afaik.

**Comment by milipili** [comment]
VS2015: `/Zc:throwingNew`
http://blogs.msdn.com/b/vcblog/archive/2015/08/06/new-in-vs-2015-zc-throwingnew.aspx

**Comment by Faq** [comment]
Any update here?

**Comment by MetaChuh** [comment]
closed due to inactivity, cross referenced to pull https://github.com/notepad-plus-plus/notepad-plus-plus/pull/2477 and commit https://github.com/notepad-plus-plus/notepad-plus-plus/commit/b39c9a1848460720eba78481737111279fa37bd4

**Comment by Croydon** [comment]
How stable are CMake builds? Readme still doesn't mention CMake
