### ISSUE TITLE
No option to add total number of pages to footer. 

### ISSUE THREAD

**Issue by rjbcollege** [notepad-plus-plus/notepad-plus-plus#3610]
### Description of the Issue

This is a request for a feature / notification that an expected feature isn't available.
In headers and footers in the Settings / Preferences dialogue box there is an option to add a notepad++ variable for the number of the current page but nothing for the total number of pages.  When you have a multi-page print there is some point,  but a somewhat limited point, to knowing only the number of the page in your hand.  The issue then is you don't know if there are any following it.  Normally, for example in Word, you would say:
Page 3 of 6.  
In Notepad++ you can only put the Page 3 part of that.

### Steps to Reproduce the Issue

I am using Notepad++ version 7.4.2 64bit,  I recall I had the same issue in the same version number for 32 bit.

1. Open the Settings / Preferences dialogue box. 
2. Select Print from the list of areas in the left hand box.
3. From the drop down list in the Header and Footer section, select Page
4. In any of the boxes to the right, 3 for header, 3 for footer, click to set the location.
5. Click Add. 
6. When you print the document, you only get the current page number, as expected from the variable name which is:  $(CURRENT_PAGE_NUMBER).

### Expected Behavior

From the drop down list above I would expect to see Page as exists and below that, another option which says:
Page x of y.
That would then be expected to produce something like the following:
Page $(CURRENT_PAGE_NUMBER) of $(TOTAL_NUMBER_OF_PAGES).

### Actual Behavior

The only option is $(CURRENT_PAGE_NUMBER) which merely gives the current page number, which you can build into a phrase as desired, (e.g. Page $(CURRENT_PAGE_NUMBER)) but you can't add that total as I would expect.

### Debug Information

N/A

**Comment by ToBeFree** [comment]
I agree that this is an issue.

**Comment by Hiltronix** [comment]
I would also very much appreciate this feature being added.

**Comment by Secif** [comment]
I really don't understand why this variable is not implemented. rjbcollege add this issue in august 2017, he has done a description of the issue, he describes steps to reproduce the issue, he even gives what would be the name of the variable.

Is it really so hard to add this variable ?
Or maybe, we have to be severall (but more than only two others) to say we want this ?

*copy past mode ON*
I would also very much appreciate this feature being added.

**Comment by sasumner** [comment]
@Secif said:

>copy past mode ON I would also very much appreciate this feature being added.

First, this sounds like a separate issue.  If truly so, then MAKE IT A SEPARATE ISSUE.  Don't bury it in this (unrelated AFAICT) issue where it will surely be ignored.  Second, describe it more; I don't understand what "copy past mode ON" means.

**Comment by ToBeFree** [comment]
@sasumner seriously? :) The user copied and pasted that text from a comment above. That's what it means. No separate feature request.

**Comment by Secif** [comment]
@sasumner For the first point, no, I assure you, it isn't  a separate issue. This is exactly this issue that @rjbcollege write in august 2017. For the second point, @ToBeFree is right, I just copy/past the text that @Hiltronix write in january of this year. Habitually, I end by a "copy past mode OFF", but I forget (and I don't talk about Guy ^^)
By the way, thanks to both of you for replying this topic.

**Comment by sasumner** [comment]
Hmmm.  Okay, I totally missed picking up on that I guess.  We have a lot of english-is-not-first-language contributers here that also are very terse in their writing--makes it tough to know what is being said/asked-for sometimes.  If I would have seen it this way I would've got it:

copy/paste mode ON
blah...blah...
copy/paste mode OFF

Note that it is "paste" not "past", adding to my initial confusion.

But really, why not just say "I too would appreciate it" or even better, just "upvote" the original?

**Comment by Secif** [comment]
@sasumner hehe, you see that english isn't my first langage ^^
and yes, you're right, I too would appreciate it (bizarrely, I would say I would appreciate it too)

**Comment by jdadwilson** [comment]
Wow, 3 1/2 years and still not completed. Can I get a refund on my contribution?

**Comment by mere-human** [comment]
> Wow, 3 1/2 years and still not completed.

Well, you can add thumbs up and hope some of the developers will get to it someday.

**Comment by sasumner** [comment]
@jdadwilson commented on the live-support channel:

>New to Notepad++ ABSOLUTELY LOVE IT!!! Small feature request. In the Settings -> Preferences -> Print area include an option to indicate the total number of pages with the page count so that a footer could contain something like... Page $(CURRENT_PRINTING_PAGE) of $(TOTAL_PRINTING_PAGES) to give "Page 2 of 4".

And then said here:

>Can I get a refund on my contribution?

This is a very inflammatory statement.  
No one loves 100% of the way any program works.
You can probably get a refund, but hopefully that comes with an agreement that you'll stop using N++ and find some other similar product that meets 100% of your need.

**Comment by donho** [comment]
@jdadwilson 
If you have done donation, pass your transaction number to me.
I will do a refund.

**Comment by jdadwilson** [comment]
Don, I sincerely apologize for the comment. My attempt at humor was totally
inappropriate. I sincerely LOVE the product. If you do have the opportunity
to add the feature request let me know and I'll make another donation.

Again, I apologize for the comment.

* -- *
*James A Wilson*
"*A wise man’s heart inclines him to the right,*
*but a fool’s heart to the left.*" Ecclesiastes 10:2 (ESV)

**Comment by sasumner** [comment]
@donho 

Closure?  Is this saying "No" to the feature request, forever?  (If so, maybe add Reject label)

**Comment by donho** [comment]
@sasumner 
I did try to do this feature when I implemented print footer/header (yes, it was long time ago), but it's not simple as it seems. I won't go deep into the code to find a way for this feature - there are a lot of other stuffs more interesting to do in this project. 
Yes, you're right. I'll add reject label.

**Comment by CORpsER1981** [comment]
So after all this time, no one has offered you a workaround? Well, I have one for you... This will accomplish exactly what you are trying to do. Since you already know how to add the current printing page via settings -> preferences -> Print | Header and Footer dialog by using the expression "$(CURRENT_PRINTING_PAGE)" 

So go ahead and print the document to a PDF, and make note of how many total pages the pdf has. Let's say for instance the pdf has 69 pages, go back to the Header and Footer dialog and add this to your expression "Page $(CURRENT_PRINTING_PAGE) of 69".

You can obviously customize how you want the current page and total page called out. I just wanted to share my workaround for those of us who use Notepad++ every day for almost everything.

Hopefully, this is helpful.

**Comment by allanwmacdonald** [comment]
@CORpsER1981:  I actually figured out this workaround myself and landed here to see if there was a better way and there's not but frankly, it is a bit of a kludge for those who routinely need to make source listings.  The extra step of printing to a PDF, going back to change the page total and printing again is a waste of time and may get forgotten.  I wish this was going to be considered at some point instead of just being dismissed out of hand.  (Maybe the bug can be labled "later" or "help wanted" instead of "reject"?)
