### ISSUE TITLE
Document map causing weird behavior on multi-desktop setups (and has display bugs)

### ISSUE THREAD

**Issue by Schttopup** [notepad-plus-plus/notepad-plus-plus#3612]
### Description of the Issue
This describes two issues with the document map, the first when using several desktops on one screen, and the other being a display bug when scrolling beyond the last line of a document.

## First Issue
When using two desktops with one screen on Windows 10, under certain circumstances Notepad++ forces the focus on itself when isn't expected to, thus switching back to the desktop where it is open. This seems to only happen when the document map is active.

### Steps to Reproduce the Issue
1. Activate the document map (clicking the "Document map" button on the toolbar).
2. Ensure you have more than one desktop on one screen with Windows 10.
3. Having Notepad++ not minimized (focus on it is not required), switch to the other desktop, then here minimize a window to the task bar.

### Expected Behavior
Nothing more than that should happen.

### Actual Behavior
Notepad++ forces the focus on itself (even though it may not have had the focus before), and you are switched back to its desktop.
Note that on the second desktop, the document map overlay is visible over the windows

## Second Issue
If "scrolling beyond last line" option is enabled, the document maps shows display bugs when actually scrolling beyond the last line.

### Steps to Reproduce the Issue
1. Activate this option (Settings -> Preferences -> Editing)
2. Have a file long enough (more than 1 screen)
3. Look at the document map while you scroll beyond the last line

### Expected Behavior
The highlited area representing what we see of the document should scroll beyond the last line, too.

### Actual Behavior
The highlited area jumps up a bit, then scrolls down while its size decreases.

### Debug Information
Screenshots :
http://puu.sh/x7b0w/d1c1db585a.png
http://puu.sh/x7b1l/590a62cef6.png
http://puu.sh/x7b1P/3c3c481611.png

**Comment by MetaChuh** [comment]
please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins if you update from version 7.5.9 or below.
if your issue still persists, and it is still of relevance, please feel free to file a new issue as easy to understand and reproducible as possible.

thank you for your help and best regards.

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
(no extra account is needed, just use your github account to sign in)
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)
