### ISSUE TITLE
Wrong language when use the new 'Open in Default Viewer' feature

### ISSUE THREAD

**Issue by rddim** [notepad-plus-plus/notepad-plus-plus#3617]
### Description of the Issue

First, this is very nice feature and I like it.

In this case Notepad++ is set as **default viewer** for `*.xml`, `*.lsp`, `*.ini`, `*.nfo`, `*.scr` files. By default they are highlighted in `XML` for `*.xml`, `LISP` for `*.lsp`, `INI file` for `*.ini`, `MS-DOS Style` for `*.nfo` and UDL for `*.scr` languages. When I use `Open in Default Viewer` feature, normally they are opened in Notepad++ but all files are highlighted in `ASN.1` language.
### Steps to Reproduce the Issue

1. Open some files in Notepad++ that use it as default viewer
2. Open these files by `Open in Default Viewer` feature

### Expected Behavior

Expect to open files with their own language instead of `ASN.1`
### Actual Behavior

![npp_odv](https://user-images.githubusercontent.com/8998791/29249207-d2a0223c-8033-11e7-802e-0e7ddd42b85d.gif)

### Debug Information

Notepad++ v7.4.2   (32-bit)
Build time : Aug 13 2017 - 10:11:34
Path : D:\Install\Office Programs\Notepad++\Notepad++.Win32.Unicode Release.exe
Admin mode : ON
Local Conf mode : ON
OS : Windows 7 (64-bit)
Plugins : AutoSave.dll ComparePlugin.dll mimeTools.dll NppExport.dll PluginManager.dll VisualStudioLineCopy.Unicode.dll

**Comment by SinghRajenM** [comment]
Could not reproduce it.
> In this case Notepad++ is set as default viewer for *.xml, *.lsp, *.ini, *.nfo, *.scr files.

So as per the code, if default viewer is notepad++, then "Open in Default Viewer" will not be enabled.
I have question here, how did you set "Notepad++" as default viewer for these languages?

![image](https://user-images.githubusercontent.com/14791461/29249468-b368701c-804d-11e7-955f-b17809bd74c3.png)

**Comment by Cyrillev91** [comment]
The option "Open in Defaut Viewer" is not enable if  defauft viewer is notepad++.exe...
But the code detect this only if exe is "notepad++.exe" (or xxxxxxnotepad++.exe) not "Notepad++.Win32.Unicode Release.exe" :-(

This improvement can be done later

**Comment by SinghRajenM** [comment]
@Cyrillev91 right. I didn't notice path.

**Comment by rddim** [comment]
@Cyrillev91 yes, you are right. If I rename `Notepad++.Win32.Unicode Release.exe` to `notepad++` everything work normally.

@SinghRajenM I use Notepad Replacer downloaded before many years from the official N++ site, but now I can't find it. It is 18kb exe that replace the original notepad.exe and may be I make some file associations for some of the files, I'm not sure. If you have interested I can upload this replacer here.

So I will close this issue. Sorry for the panic.
