### ISSUE TITLE
App freeze when network files are open over slow connection

### ISSUE THREAD

**Issue by marcelinojorgeromero** [notepad-plus-plus/notepad-plus-plus#3619]
### Description
The app is unresponsive when having open files from a network drive over a very slow and faulty VPN connection.

### Steps to Reproduce the Issue

1. Connect to a very slow and faulty network and have a network drive
2. Open a file
3. Then close the editor
4. Try to open the editor when the network is unresponsive and the app will freeze

### Expected Behavior
I expect to not freeze at least should show the file as "red" (not saved)

**Comment by silid** [comment]
This is also a problem when not connected to the network the file is stored on. For example when you have a file open while connected to the network then continue to use the application while connected to a different network, for example VPN or between home and work networks.

**Comment by TiE10** [comment]
I am also experiencing this issue, not just on opening as mentioned above, but also when switching between windows. That is:

- Connect to slow network drive, e.g. over VPN
- Open files
- Edit the file or simply click on another window (e.g. web browser)
- Click back onto Notepad++: freezes for around 10 seconds before finally responding, longer if the network connection is worse.

This is problematic when searching the web or using an external program to run the code, then coming back to make edits.

No problems with freezing like this when accessing local files, or network files on a good connection.

**Comment by MetaChuh** [comment]
please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins if you update from version 7.5.9 or below.
if your issue still persists, and it is still of relevance, please feel free to file a new issue as easy to understand and reproducible as possible.

thank you for your help and best regards.
