### ISSUE TITLE
"Normal" mode and "Input" mode. Possible?

### ISSUE THREAD

**Issue by Mikhail22** [notepad-plus-plus/notepad-plus-plus#3621]
Hello, I am a new Notepad++ user. 
I am not sure it is the correct branch for this question, 
but I haven't found easier way to ask.

I have been using Notepad++ (v7.5) for a few days now and I
am giving very positive feedback. I have heard about N++ earlier 
but did not tried it before, shame. So I started just with a pair of color setups and
everything works just fine!

Many GUI features are classy, even compared to the modern 
products like VSCode. 
And the speed!!   I love such software.

But now I have a bit of confusion though, I come from Vim (my first editor), 
and I can't find the information, whether N++ supports Normal/Input mode?
To be correct, I am not awaiting 100% Vim emulation or something complex.
Just  something that allows me to bind e.g. the Space key to line-select for
example, without needing to define it as CTRL+key combination.

Are such things possible at all with N++?
Like for example, in Vim I can select text without clicking the mouse 
button, I can have a key to select the line and such features absolutely 
making a comfortable workflow. 
Navigation, etc, so one has the whole keyboard to play with and whole
bunch of internal commands to make selections.

I feel now like "without hands". I want some ergonomics, but 
in this 'always insert mode' paradigm, it seems just impossible.

Any suggestions if this is achievable (in a standard build)? 
If not, should it be made into a feature proposal? 

Comments please welcome.
And just in case:  I cannot work on the implementation, sorry.

Mikhail

**Comment by MAPJe71** [comment]
>I have been using Notepad++ (v7.5) for a few days now

LOL v7.5 has been released only a few hours ago.

**Comment by Mikhail22** [comment]
LOL yes. Probably I have started with other version. Anyway, ""few days was ca. 3 days
altogether in my case.

**Comment by sasumner** [comment]
A better forum for this question would be the Notepad++ Community web site:  https://notepad-plus-plus.org/community/

**Comment by MetaChuh** [comment]
closed as a better forum for this question would be the notepad++ community web site: https://notepad-plus-plus.org/community/

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
(no extra account is needed, just use your github account to sign in)
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)
