### ISSUE TITLE
Easily copy current line / remove current empty line

### ISSUE THREAD

**Issue by Wroxi** [notepad-plus-plus/notepad-plus-plus#3623]
### Windows standard shortcuts
**Ctrl+X:** Cut selected text
**Ctrl+C:** Copy selected text

### Request for NPP (behavior of Visual Studio)
**Ctrl+X:** Cut current line if no text is selected
**Ctrl+C:** Copy current line if no text is selected

### UI change proposal
Additional checkbox for dialog "Shortcut mapper" (menu "Settings"):

![checkboxnpp](https://user-images.githubusercontent.com/31067955/29363106-ebdd7bde-828e-11e7-82a2-660c57166b9e.JPG)
_Image correction:_ "Remove" should be "Cut"

**Comment by MAPJe71** [comment]
See #18, #1854, Community topic [13732](https://notepad-plus-plus.org/community/topic/13732/feature-smart-cut-copy-current-line-when-there-is-no-selection) or add the following snippet to the `startup.lua` script for the LuaScript plugin:
```lua
-- Mimic Visual Studio's "Ctrl+C" that copies the entire line if nothing is selected
npp.AddShortcut("Copy Allow Line", "Ctrl+C", function()
    editor:CopyAllowLine()
end)

-- Mimic Visual Studio's "Ctrl+X" that cuts the line if nothing is selected
npp.AddShortcut("Cut Allow Line", "Ctrl+X", function()
    if editor.SelectionEmpty then
        editor:CopyAllowLine()
        editor:LineDelete()
    else
        editor:Cut()
    end
end)
```

**Comment by Wroxi** [comment]
@MAPJe71: Thanks, just installed plugin https://bitbucket.org/zastrowm/notepad-visualstudiolinecopy, works like a charm!
