### ISSUE TITLE
Excluding additional languages doesn't get saved into config file

### ISSUE THREAD

**Issue by vbojan** [notepad-plus-plus/notepad-plus-plus#3624]
I'm not big fan of compact Language menu and had excluded majority of languages that I never use.

When I try to exclude any additional language through Settings->Preferences->Language, it initially disappears from the Language menu, but it doesn't persist.
When Notepad++ is closed and launched again, the excluded language is back in the menu.
It appears the config file doesn't get updated.

Here's the related part of my config.xml:
> `<GUIConfig name="langsExcluded" gr0="188" gr1="76" gr2="229" gr3="255" gr4="251" gr5="127" gr6="255" gr7="249" langMenuCompact="no" />`

I noticed this in v7.5 as it introduced few more languages which made the menu much longer, but then checked v7.4.2 and found the same behavior.

It appears this is the only place where langsExcluded is used:
https://github.com/notepad-plus-plus/notepad-plus-plus/blob/master/PowerEditor/src/Parameters.cpp
It looks like it's using 8Bytes bitmask which covers up to 64 languages whereas v7.5 has 83 languages in langs.xml, so it feels that's the source of the issue.

**Comment by MAPJe71** [comment]
See also Community topic [14315](https://notepad-plus-plus.org/community/topic/14315/notepad-7-5-release/6).

**Comment by vbojan** [comment]
I can confirm this was fixed in v7.5.1 and can be closed.
