### ISSUE TITLE
Dropbox and Onedrive is not detected in Windows 7 Ultimate 64bit (Service Pack 1)

### ISSUE THREAD

**Issue by SoiTrang** [notepad-plus-plus/notepad-plus-plus#363]
All mention in the title

![image](https://cloud.githubusercontent.com/assets/13106714/8414791/96c01790-1ec4-11e5-989f-6f1ade7f56ef.png)

**Comment by ariccio** [comment]
Xref: #106 
Xref: #135 
Xref: #6

**Comment by Arbitel** [comment]
Just curious will this ever be fixed ?

**Comment by milipili** [comment]
AFAIK, this feature should be replaced by a more simpler one. We can't catch up anyway all API changes from those tools. The common denominator is to be able to select a folder for saving the settings. I think @donho will take care of this as soon as he's back from vacations.

**Comment by milipili** [comment]
See 5e240147c51b6c27f1accbcfa191d9ddc4967e68
