### ISSUE TITLE
Language list shows disabled languages

### ISSUE THREAD

**Issue by dnlw07** [notepad-plus-plus/notepad-plus-plus#3631]
### Steps to Reproduce the Issue

1. Settings/Preferences.../Languages/Disable all languages excelt SQL, C#, Java, JSON, HTML, CSS and Python

### Expected Behavior
After disabling chosen languages in settings. N++ should remember settings and don't list disabled languages.

### Actual Behavior
Despite of disabling chosen languages in settings some of them are still enabled after N++ restart.

**Comment by MetaChuh** [comment]
the bug not remembering the disabled status of higher language ids was fixed some time ago.

please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins if you update from version 7.5.9 or below.

thank you for your help and best regards.
