### ISSUE TITLE
Plugin Manager is missing

### ISSUE THREAD

**Issue by richardhauer** [notepad-plus-plus/notepad-plus-plus#3632]
### Environment
Windows 10 Creators x64
Surface Pro 4

### Installed
Using the `Download` button on the download page which has installed the **32-bit** version of the app on the machine (correctly).
Version is 7.5, 32-bit
Confirmed in Help->About

### Issue
There are 3 plugins available:
- Converter
- MIME Tools
- NppExport

### Expected Behaviour
Would have expected the plugin manager to be there as per the doco.

**Comment by dail8859** [comment]
As of Notepad++ v7.5 the Plugin Manager is no long being shipped with Notepad++. See https://notepad-plus-plus.org/news/notepad-7.5-released.html

All Plugin Manager related issues should be reported to https://github.com/bruderstein/nppPluginManager/issues

**Comment by richardhauer** [comment]
Huh.  Fair enough too.  A note on the download page is probably be in order when such a significant change is made to the app.  Would avoid this sort of "bug" being logged (I don't imagine too many people actually read release notes).

**Comment by darthwalsh** [comment]
@dail8859 until the PluginManager is reintroduced into NotePad++, it would be awesome to include a additional menu item to Plugins like "Where's the PluginManager" with a link to https://htmlpreview.github.io/?https://github.com/bruderstein/nppPluginManager/blob/master/doc/index.html#install, because many other users will probably be confused by this :\

**Comment by Vankog** [comment]
I just had the same issue. I was looking for the Plugin Manager. Even uninstalled and reinstalled several times just to be sure. The front page does not have any information about this neither.

It should really be noted somewhere (beside the particular release notes). It confused the heck out of me...

**Comment by kamikazzi1** [comment]
super annoying!!! 

Just FYI: you take the files that you download and drop them into the appropriate folders that are in your install directory for notepad++.. ie.. the plugin.dll goes in the plugins folder

**Comment by darthwalsh** [comment]
The high-quality plugins for text formatting, etc, were the reason I stick with Notepad++ instead of switching completely to a more modern editor like Visual Studio Code. If Notepad++ doesn't consider a good plugin experience as integral to the experience, I might need to find a new editor :(

**Comment by Vankog** [comment]
@darthwalsh 
Don't worry. The release notes state that there will be a dedicated plugin manager in an upcoming release.

**Comment by TAGC** [comment]
Any day now...

**Comment by jefflafay** [comment]
I used notepad++ for the plugins. I used it as a toolbox of sorts for all sorts of text processing/testing tasks. But now I have to hunt for all of these plugins and figure out how to install/configure them. Notepad++ lost a lot of value without the ability to easily extend it.

**Comment by dail8859** [comment]
For people that aren't aware, you can still install the PluginManager manually.

See:  http://bruderste.in/npp/pm/#install

**Comment by darthwalsh** [comment]
Yes, it's always been possible to install plugins manually, but I prefer
using a tool that doesn't make you download DLLs from random websites :\

Installing the PluginManager by hand on all my new machines is more onerous
than just installing VS Code and syncing all my extensions (and preferences
(and keyboard shortcuts).)

**Comment by ChromiumDomium** [comment]
Download and install version 7.4.x Which has the plugin manager first. I didn't let it update itself straight away. I then installed a random plugin at that point. - Not sure if it is necessary, but it forces an update to the plugin manager. Then do an update to 7.5.x make sure plugins is checked in the installer and all is happy.

**Comment by 9527KKK** [comment]
"A built-in Plugin Manager is in progress, and I will do my best to ship it with Notepad++ ASAP."

May you please keep the existing one before new one arrives? Otherwise, I bet lots of people needs rollback to 7.4

Thanks.
