### ISSUE TITLE
Installer doesn't install plugins manager

### ISSUE THREAD

**Issue by abek42** [notepad-plus-plus/notepad-plus-plus#3634]
### Description of the Issue
Fresh install using the 7.5 (32-bit installer : https://notepad-plus-plus.org/repository/7.x/7.5/npp.7.5.Installer.exe) doesn't install gpup.exe and Plugins Manager.

### Steps to Reproduce the Issue

1. Fresh install of Notepad++ using the installer from https://notepad-plus-plus.org/repository/7.x/7.5/npp.7.5.Installer.exe
2. Plugins list contains only three options only.
3. Manual addition of plugins leads to message that mentions missing gpup.exe

### Expected Behavior
Plugin manager is available.

### Actual Behavior
Plugin manager is not available

### Debug Information
Notepad++ v7.5   (32-bit)
Build time : Aug 15 2017 - 23:02:57
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10 (64-bit)
Plugins : mimeTools.dll NppConverter.dll NppExport.dll

**Comment by MAPJe71** [comment]
See Community topic [14315](https://notepad-plus-plus.org/community/topic/14315/notepad-7-5-release) or better yet read the second paragraph [here](https://notepad-plus-plus.org/news/notepad-7.5-released.html) (i.e. "You may notice...")

**Comment by abek42** [comment]
Thanks for pointing that out. I hate ads too. Love Notepad++ though.

However, I think fewer plugins are installed by default and the update folder was empty too.
Is this by design too? (or gpup is part of plugin manager?)

If that's expected behaviour, that's fine with me (ok to close this)

**Comment by dail8859** [comment]
@abek42 Yes `gpup.exe` is part of the plugin manager. You can still use the plugin manager with a clean install of v7.5 but you have to install the plugin manager manually. See [these instructions](https://htmlpreview.github.io/?https://github.com/bruderstein/nppPluginManager/blob/master/doc/index.html#install).

**Comment by smittysauce** [comment]
https://notepad-plus-plus.org/news/notepad-7.5-released.html

This seems like a misstep removing the plugin manager before shipping with a replacement. Additionally if the author is so against advertising, why do I see a slack advertisement on the bottom left corner of https://notepad-plus-plus.org? I also see advertising periodically show on other parts of his website.

**Comment by 9527KKK** [comment]
"A built-in Plugin Manager is in progress, and I will do my best to ship it with Notepad++ ASAP."

May you please keep the existing one before new one arrives? Otherwise, I bet lots of people needs rollback to 7.4

Thanks.

**Comment by pritishtechguru** [comment]
I have tried 7.5 version i could not find  later I switched to 6.8.8 old version there I can see all Plugin
