### ISSUE TITLE
Multi-Editing (Ctrl+Click) collides with auto-selecting words

### ISSUE THREAD

**Issue by 2chg** [notepad-plus-plus/notepad-plus-plus#3637]
I'm a big fan of the Multi-Editing-Feature in NPP, but for a while now this feature has some quirks:

When I am Multi-Selecting positions with no adjacent words, then Ctrl-Click correctly adds one position after the other for editing, so that I can type on this various positions synchronously. But in this very moment, when there is any adjacent word, the Ctrl-Click instantaneously selects the whole adjacent word, so any following typing results in deleting this wrongly selected words first. :(

Example (`|` shows my Ctrl+Click-Positions):

    This | is more | than ever.

and typing `fun` results correctly in 

    This fun is more fun than ever.

but

    This | is |damential.

(where the second bar is a Crtl+Click!) and typing `fun`results in 

    This fun is fun.

deleting the `damential` part!

Is there some magic option that I'm missing to deactivate? I can't find anything.
I'm pretty sure this behaviour wasn't there from the begin of the Mutli-Editing-Feature.

**Comment by dail8859** [comment]
Works fine for me. Please post your debug info as it might be related to an old version of Notepad++ or one of your plugins installed.

**Comment by sasumner** [comment]
I'm finding, from a fresh N++ 7.5 (32bit) unzip, but of course with the addition of "Multi-Editing" Enable'd, that I can't duplicate the behavior you are seeing.  It adds the 2nd, 3rd, etc carets without doing any text selecting.

**Comment by 2chg** [comment]
OK. Thanks for your fast response.

Yes, I'm using quite a lot of plugins. Maybe I should install a fresh notepad++-installation and check after installing one plugin after another. 

```
Notepad++ v7.4.2   (32-bit)
Build time : Jun 18 2017 - 23:34:19
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 7 (64-bit)
Plugins : AnalysePlugin.dll CodeAlignmentNpp.dll DSpellCheck.dll FingerText.dll HTMLTag_unicode.dll LocationNavigate.dll NppAutoIndent.dll NppFTP.dll nppplugin_solutionhub.dll nppplugin_solutionhub_ui.dll nppplugin_solutiontools.dll nppplugin_svn.dll nppRegEx.dll NppSaveAsAdmin.dll NppTaskList.dll NppTextFX.dll PluginManager.dll PythonScript.dll SourceCookifier.dll Tidy2.dll XMLTools.dll XPatherizerNPP.dll ZenCoding-Python.dll mimeTools.dll NppConverter.dll NppExport.dll SpellChecker.dll 
```

**Comment by cmeriaux** [comment]
@2chg you can try with the portable edition https://notepad-plus-plus.org/repository/7.x/7.5/npp.7.5.bin.zip 

Your bug may be due to  FingerText  plugin or NppAutoIndent plugin

**Comment by 2chg** [comment]
Thanks a lot for your help!

Indeed, a plugin 'SourceCookifier' was to blame. In its configuration there is an option to

> Go to definition by pressing ctrl + left mousebutton

Deactivating this option restored the desired behavior.

**Comment by dail8859** [comment]
Thanks for the info. Glad you got it figured out.
