### ISSUE TITLE
c/c++ code collapsing bug

### ISSUE THREAD

**Issue by refigh** [notepad-plus-plus/notepad-plus-plus#3638]
### Description of the Issue
in c/c++ code, collapsing has a bug and collapses wrongly by mixing with comments.

### Steps to Reproduce the Issue
make a .h file and copy paste below simple code.  then just try to collapse the empty class:

class myclass
{
  //}
};

### Expected Behavior
I expect that the class is collapsed from first { to last }. 

### Actual Behavior
but it collapses from first { to the } inside comment line!. if I put a space before the } in comment line (meaning //} to // }) it works properly.

**Comment by dail8859** [comment]
Late reply, but this isn't a bug. It's a confusing [feature](https://sourceforge.net/p/scintilla/bugs/1676/) of Scintilla. There are ways of turning it off with a plugin though if it is too annoying.
