### ISSUE TITLE
Style configuration doesn't remember font & size

### ISSUE THREAD

**Issue by kobalicek** [notepad-plus-plus/notepad-plus-plus#364]
I'm having an issue with Style Configurator.

I switched to a dark theme (obsidian), but when I close notepad++ and run it again it shows a wrong font (not monospace at all). If I go to "Style Configurator - Global Styles - Default Style" and set the font to "Courier New" the problem gets fixed for the current session, but even if I "Save & Close" next time I run notepad++ I have to do the same, the configuration is lost.

**Comment by milipili** [comment]
Maybe related to #220

**Comment by kobalicek** [comment]
Not sure, I selected "Courier New", which doesn't seem to have any unicode issues.

**Comment by Tmp341** [comment]
Do you have admin rights?

**Comment by kobalicek** [comment]
I think it has nothing to do with admin rights. It remembers the dark theme I selected, but it screws up the font by some reason.

**Comment by kobalicek** [comment]
But to answer to your question - yes, I have.

**Comment by Tmp341** [comment]
I had this issue that when i try to install a theme from desktop, it doesn't show up in the style config.I had to go to %Appdata%\Notepad++\themes and paste them.Didn't check it with the latest. Try this, go to %Appdata%\Notepad++\themes and open obsidian with npp. See the default style's fontName. And change it through style config and see if it changes there too.

**Comment by alfrrr** [comment]
@kobalicek I posted an answer inside the issue #1299 that maybe fixes your problem

**Comment by mjohnsonengr** [comment]
I have the same issue with the same theme -- Obsidian -- when I open Notepad++ as administrator, the font renders correctly as a monospaced font (Courier New I presume), but definitely not monospace in normal non-admin mode:

![image](https://cloud.githubusercontent.com/assets/7274059/13366667/04322118-dc9a-11e5-81af-27fa88d46d9b.png)

**Comment by donho** [comment]
Cannot reproduce it.

**Comment by xates** [comment]
@donho This happens only with Obsidian theme and you need to close and reopen Notepad++ to notice that. My patch #2695 that you rejected actually fixes this bug.

**Comment by ttreadwellscs** [comment]
I have the same problem trying to use downloaded font 'M+ 1m medium' in Obsidian theme. Every time I restart Notepad++ I have to go to Settings > Style Configurator and reselect Obsidian theme to get the M+ font to show up. I tried the patch #2695 but it did not solve it.

**Comment by QAnders** [comment]
+1
I have this problem too...

**Comment by MichaelEugeneYuen** [comment]
I had same issue saving configuration. So I create a shortcut to open Notepad++ as Administrator. Problem solved.

**Comment by reyandme** [comment]
Same issue still exists... 4 years already...

**Comment by bouzas** [comment]
Yep. it happens to me also. And using Courier New
