### ISSUE TITLE
Backward-direction checkbox enabled with Reg Exp search mode (at N++ startup)

### ISSUE THREAD

**Issue by sasumner** [notepad-plus-plus/notepad-plus-plus#3640]
### Description of the Issue
In Notepad++ 7.5, with the introduction of the "Backward direction" checkbox in the Find dialog, the checkbox is sometimes enabled when the search mode is Regular Expression.  It should never be enabled when the search mode is Reg Exp.

### Steps to Reproduce the Issue
1. Start Notepad++ 7.5 (32-bit) from a fresh unzip of the portable install.
2. Execute any Find operation with Regular Expression as the search mode (note that when the search mode is changed to Reg Exp the "backward direction" checkbox becomes disabled--correct behavior).
3. Quit and restart Notepad++ 7.5.
4. Invoke the Find dialog.  Note that the search mode is Reg Exp but the "backward direction" checkbox is now incorrectly enabled.

### Expected Behavior
Any time the search mode is set to Reg Exp (including if this is the case when Notepad++ starts up), the "backward direction" checkbox needs to be disabled.

### Actual Behavior
See point 4 above.

### Debug Information
Notepad++ v7.5   (32-bit)
Build time : Aug 15 2017 - 23:02:57
Path : ...\npp.7.5.bin_UNCHANGED\notepad++.exe
Admin mode : OFF
Local Conf mode : ON
OS : Windows 7 (64-bit)
Plugins : mimeTools.dll NppConverter.dll NppExport.dll 

![image](https://user-images.githubusercontent.com/30118311/29536587-6b70e77c-868c-11e7-98d2-c90bbe6be311.png)

**Comment by dinkumoil** [comment]
Related to #3533.

**Comment by sasumner** [comment]
Not related to #3533; see my comment there.  This current issue has to do with a deviation from consistent behavior since version 6.3.

**Comment by sasumner** [comment]
Added "at N++ startup" to issue title to hopefully clarify.  This is only a problem at startup when Reg Exp search mode was the last search mode used in the prior N++ run of the program.  [The search mode gets saved into the find-history, and is restored in the next N++ run.  However, the enabled/disabled state of the backward-direction checkbox isn't set at next startup after the code restores the search mode.]

**Comment by dinkumoil** [comment]
It is related to #3533 in that sense that if #3533 would be considered as a bug the issue here would be not a bug (and vice versa).

**Comment by sasumner** [comment]
This issue (and the related 3533) is antiquated.  I will do a PR that will keep the `Backward direction` checkbox enabled regardless of the `Search mode` setting...to fix this issue.  

To the time of this writing the `Backward direction` checkbox will go disabled if `Search mode` is set to `Regular expression`, even though the "up" arrow in this control set will not be disabled:

![image](https://user-images.githubusercontent.com/30118311/70264531-990b9e80-1766-11ea-8248-f5e6815a849a.png)

...and even though a backward direction regex search via `Search` > `Find Previous` also remains enabled.

It is hereby judged (from a somewhat high hill?) that backward searching regex searches are fine. :-)

Even though the results of searching this (as an example):

`to the test they travelled`

for `t\w+` results in 5 `Find Next` hits when traversing it in the forward direction, and (I think) 16 hits when traversing in the backward direction (with Shift+F3)!  This makes me slightly uncomfortable as it is intuitive to think that a search should find the same things in either direction. :-)

**Comment by dinkumoil** [comment]
This logic is strange.

There is an inconsistency in GUI behaviour that allows users in some cases to perform actions that produce invalid results.

Instead of fixing the GUI inconsistencies in order to allow only valid user actions, you suggest a change that makes the GUI consistent in a way that users are **always** allowed to perform actions that produce invalid results.

That's not making things better, it's declaring a bug as a world-standard.

**Comment by sasumner** [comment]
@dinkumoil:

You've demonstrated before that you don't like my logic.  Not sure there is a resolution to that, but I encourage you to contribute code of your own to the Notepad++ project, so that you can promote your opinions on how things should be with something concrete.

Originally (4 years ago?) I championed not allowing backwards regex searches, but since that time they have always been allowed, just not via the backward-direction checkbox.  And...nobody has really cared enough to say or do anything about it.

So this is just an attempt to clean up that little annoyance, not to restart the whole discussion.  But...I suppose I am up for more discussion if we really want to go there.

Is it your suggestion to disallow backward regex searches via the mechanisms that currently allow them?  If so, I can hear the complaints from the customer community already.  :-)

**Comment by dinkumoil** [comment]
@sasumner 

> I encourage you to contribute code of your own to the Notepad++ project, so that you can promote your opinions on how things should be with something concrete.

I can promote my opinion with words, is that not understandable enough? Or do you mean I'm not allowed to promote my opinion unless I contribute code to the project?

> nobody has really cared enough to say or do anything about it.

Isn't it better to act proactively instead of only reacting to user complaints? Maybe the reason why nobody noticed the current behaviour is that people work with the dialog's buttons instead of using menu entries and their keyboard shortcuts.

> Is it your suggestion to disallow backward regex searches via the mechanisms that currently allow them?

I don't know what you mean with that. To clarify what **I** mean: If in the _Search & Replace_ dialog regex search is activated, the menu item for searching backwards should be disabled. I'm not sure if in a fresh installation of Notepad++ there is a toolbar button for searching backwards or if this button is only available when using the _Customize Toolbar_ plugin. But this button should be disabled as well when regex search is activated. Maybe this happens automatically when disabling the menu entry.

> I'm not convinced the results are "invalid", one just has to understand why certain actions produce certain results.

I'm not a native speaker, so maybe "invalid" is a too strong expression. But you gave an example in your comment above where a regex search in backward direction produces presumeably 16 results though the same search in forward direction only produces 5 results. The 16-results-set is not reasonable and no one would expect it. That's what I mean with "invalid". With your PR such searches are allowed but I can not imagine that anybody wants or needs unreasonable search results (again, I'm not a native speaker, maybe even "unreasonable" is the wrong word, but I think it should be clear what I mean).

**Comment by xylographe** [comment]
@sasumner 
I cannot reproduce [your example](https://github.com/notepad-plus-plus/notepad-plus-plus/issues/3640#issuecomment-562273006) with **`to the test they travelled`** and **`t\w`**. It doesn't seem to make a difference if "Backward direction" is on or off. Also, no difference between clicking forward or backward button repeatedly. What am I missing?

**Comment by Ekopalypse** [comment]
>What am I missing?
@xylographe - the plus sign in the regex :-) - makes a huge difference when used.

**Comment by sasumner** [comment]
@xylographe Hopefully @Ekopalypse 's hint about the `+` will get you working...and that you follow it up with an opinion on this subject. :-)

**Comment by xylographe** [comment]
Thank you, @Ekopalypse & @sasumner. I did overlook the `+`. My eyesight is not as good as it used to be when I was young — in the Stone Age. :)

Yes, the results of forward/backward regex searching are different. But, the backward searching does make sense, it is certainly not smth completely unexpected. Hence, I don't see a problem with Scott's way to resolve the current incostistency in PR #7702.

**Comment by sasumner** [comment]
Work on this issue is on-hold pending #7928 , which simplifies implementing this issue.  While it could have been combined with the work on this issue, doing 7928 as a separate issue makes the changes more atomic.

**Comment by fml2** [comment]
Can someone please explain the search results for the case above (text `to the test they travelled` and search pattern `t\w+`)? Because I don't understand the logic behind them.

Instead of disabling backward search with regex, could it be possible to make the search results more "logical"?

**Comment by sasumner** [comment]
@fml2 said:

>Can someone please explain the search results for the case above (text to the test they travelled and search pattern t\w+)? Because I don't understand the logic behind them.

Do you mean to explain the search results of that for a _forward_ search?  
Or explain it for a _backward_ search? 

>Instead of disabling backward search with regex, could it be possible to make the search results more "logical"?

Can you explain a bit more about what that means?
"Make the results a bit more logical?"

**Comment by fml2** [comment]
(I'm on NP++ 7.8.6).

I mean the backward search. If the cursor is at the end of the text and I search backwards, the first occurrence found (and selected) is `travelle`. After another click on "search" it is `travell`. And so forth. Each time one letter is chopped. I'd expect the next word (in the backward direction, i.e. `they`) be selected at the "find previous", not just one letter be cut off.

**Comment by sasumner** [comment]
>Each time one letter is chopped. I'd expect the next word...

Right; that's why we're disabling backward regex search; because you don't get what you'd expect.
What you'd expect is the results in reverse for the same search in a forward direction.
What you actually get is "correct" (oh, if you don't want `travelle` the next match that satisfies is `travell` -- is that what you want? no? ok, the next best match is `travel`, etc).

As to "making the results a bit more logical", do you have any specific suggestions for how to do that, that fit into the framework of the existing code?

**Comment by fml2** [comment]
> do you have any specific suggestions for how to do that, that fit into the framework of the existing code?

I've tried it with two other programs (exact the same text and regex, backwards search), both work as one (well, me at least :-)) would expect, i.e. at each search the previous word is selected.

So is it a question of the regex search library used? I don't know how it's implemented in NP++. Is it an own implementation? Then it could be possible to change it. Or is it something wired into a third party library that NP++ uses (Scintilla?)? Then it would be harder. Does the library allow to somehow customize how the search works?

Why I'm bothered? NP++ is a very nice text editor. Hence, in my opinion, it should do things with text perfectly.

**Comment by sasumner** [comment]
Regular expression searching in Notepad++ is done through Scintilla and then on into the Boost regex engine:

Notepad++ ---> Scintilla ---> Boost

The Scintilla interface allows some customization of how search works, but not something that would solve this issue being discussed.  It would have to be solved on the Notepad++ side but it would require some serious reworking of searching on that side.

I believe the "right" way to do this type of searching is not to search backwards, but to notice that the user _wants_ to search backwards, and then search the file from the beginning, building up a list of all match points.  When the original caret position has been considered in this list-building effort, the searching can stop and then the list is examined.  The match in the list that is "less than" the current caret position could then be declared the match that is wanted.

The described approach would be one way (there could be others) that would guarantee that the matches are the same whether or not the user traverses forward or backward through them.

**Comment by fml2** [comment]
Absolutely! This might be not very efficient computation wise but it would bring a consistent user experience. With modern computers and not too large files the user would not notice a difference.

**Comment by sasumner** [comment]
A commit to partially allow backward regex search:  https://github.com/notepad-plus-plus/notepad-plus-plus/commit/5e262c8122cba71aec34edc9cde8994356a2ea46

**Comment by alankilborn** [comment]
I'm not sure where to document this, so I'll do it here; I think I found another example of where regex searching in a backward direction doesn't work correctly; STR in 8.7.5:

* enable `regexBackward4PowerUser="yes"` in `config.xml` (restart if needed to change)
* open into a N++ tab some file with many lines in it
* invoke _Find_ via Ctrl+f
* set _Find what_ to `^`, _Search mode_ to _Regular expression_, checkmark _Wrap around_
* press _Find Next_ several times; notice N++ finds the beginnings of lines and shows the calltip `^ zero length match` (this is all correct behavior)
* checkmark _Backward direction_ and press _Find Next_; observe `Find: Can't find the text "^" in entire file` in _Find_ dialog status bar (INCORRECT behavior)

At first I thought this incorrect behavior might happen for all zero-length assertion matches, but no, e.g. `\b` works fine in either search direction.
