### ISSUE TITLE
Find dialog needs a progress bar and a 'cancel search' button

### ISSUE THREAD

**Issue by garydgregory** [notepad-plus-plus/notepad-plus-plus#365]
When I search a giant file, I want to cancel the search when I realize that I am searching with a typo.

**Comment by h-h-h-h** [comment]
Related issue: https://github.com/notepad-plus-plus/notepad-plus-plus/issues/685

**Comment by mjramtech** [comment]
Can the following issue please be considered along side this? When you Find in Files, having accidently left In All Sub-Folders ticked when you're at the top of a large file tree, you're basically left with no choice but to kill the task. There's obviously some potentially lengthy processing takes place before the progress/cancel dialog is displayed.

Thanks.

**Comment by donho** [comment]
it's been done since previous versions ago.

**Comment by mjramtech** [comment]
This isn't resolved for Find in Files, as per my comment from May 2017. If you start a find in files with "In all sub-folders" ticked, and there are many sub-folders below your selected search directory, you can be sat waiting for what seems forever with an unresponsive app and no option to cancel the search - all you can do is end task. As pointed out before, there's some potentially lengthy process taking place BEFORE the cancel option is displayed.
