### ISSUE TITLE
Plugin manager not available

### ISSUE THREAD

**Issue by sandy9999** [notepad-plus-plus/notepad-plus-plus#3651]
The plugin manager is not available in both 32 bit and 64 bit versions of notepad++ on the website.

![image](https://user-images.githubusercontent.com/17477947/29719459-b9b2f872-89d3-11e7-94d1-c5ce0e5eb885.png)

As in this image, the plugin manager is not displayed under Plugins when it is supposed to.

**Comment by dail8859** [comment]
As of Notepad++ v7.5 the Plugin Manager is no long being shipped with Notepad++. See https://notepad-plus-plus.org/news/notepad-7.5-released.html

Note that you can still use the plugin manager with v7.5 you just have to install it manually. (or upgrade from a previous version of Notepad++ that already has it installed)
