### ISSUE TITLE
How do I compile and run a C++ program from within Notepad++

### ISSUE THREAD

**Issue by sandy9999** [notepad-plus-plus/notepad-plus-plus#3653]

**Comment by protector1990** [comment]
I think that this should be discussed on the forums, and not be opened as an issue.

**Comment by nlsdg** [comment]
Notepad++ is not a compiler. But you can use the Run menu to start external programs. You can also add your own custom commands.
So you can start your compiler and give it the path to the currently open file as a parameter. See http://docs.notepad-plus-plus.org/index.php/External_Programs
