### ISSUE TITLE
On Npp focus-in, update changed files not satisfying

### ISSUE THREAD

**Issue by keigra** [notepad-plus-plus/notepad-plus-plus#3654]
### Description of the Issue

Open multple files on Notepad++, e.g. an open-source software project, and preferably using filename TABs. Then use some other tool to modify the same files. At this point you may close the Npp application before saving changes on the files on the other tool.
Next time Npp is opened, it ask to update the changed files. to this point everything is correct.
What I'm not completely satisfied with, is:

1) a file list dialog could be used to indicate how many files Npp will update. Merge options may be provided for each file separately to accept or discard edits either on Npp or the filesystem, like the separate pop-up dialogs currently do; or to keep both files with different names (if both have conflicting edits, and an external file comparison tool of the user's liking may then be used to merge the files.)
It is not problem that the file merge will trigger file change notification again, as long as the file tab selection is kept.

2) After the open files are updated, Npp should return focus to the file the used originally requested, which may be a the file which was last focused on Npp, or a new file the user double-clicked on the filesystem, and thus caused launching the new instance Npp.

### Steps to Reproduce the Issue

1. Open multiple files on Npp
2. Use another tool to modify one or more of the same files.
3. Select Npp as the active window.

or

1. Open multiple files on Npp
2. Close the Npp application
3. Use another tool to modify one or more of the same files.
4. Select a text file on the filesystem and select 'Edit in Notepad++' on the Explorer context menu.

### Expected Behavior

Keep the last selected file active on Npp, since the file updates occur in random order, anyway.

### Actual Behavior

Multiple pop-up dialogs may appear to indocate changed files.
The last updated file is selected active on Npp.

### Debug Information

Notepad++ v7.5   (64-bit)
Build time : Aug 15 2017 - 23:06:39
Path : C:\APPS\NPP7.5.5\notepad++.exe
Admin mode : OFF
Local Conf mode : ON
OS : Windows 7 (64-bit)
Plugins : mimeTools.dll NppConverter.dll

**Comment by donho** [comment]
The current version has the expected behaviour of this issue.
