### ISSUE TITLE
Default TAB level

### ISSUE THREAD

**Issue by keigra** [notepad-plus-plus/notepad-plus-plus#3656]
### Description of the Issue

Write line of ordinary text or source code, indented with TABs and add empty lines.
the last indent level is automatically assumed.  Textual Lists or Multi-line statements in C/C++ language may have indented continuation lines, and it confuses the Npp editor.

### Steps to Reproduce the Issue

1. Write line of ordinary text or C/C++ source code, indented with TABs.
2.  Add multiple empty lines by repeatedly pressing Enter key.
3. Write the next line of text.

### Expected Behavior

Usually, after inserting one blank line I want to start ordinary text on the first column, or the text baseline level (the first column containing text), and source code on the previous open curly braces level + one TAB.

### Actual Behavior

 TABs are automatically added on all empty lines to the indent level on the last text line.
When some extra lines are deleted, the next existing text line after the blank lines is also automatically indented to the indent level on the previous text line. Both are incorrect as long as there exist blank lines between these two text blocks.

### Debug Information

Notepad++ v7.5   (64-bit)
Build time : Aug 15 2017 - 23:06:39
Path : C:\APPS\NPP7.5.5\notepad++.exe
Admin mode : OFF
Local Conf mode : ON
OS : Windows 7 (64-bit)
Plugins : mimeTools.dll NppConverter.dll

**Comment by ygoe** [comment]
This is probably related to #443.

**Comment by MetaChuh** [comment]
please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins if you update from version 7.5.9 or below.
if your issue still persists, and it is still of relevance, please feel free to file a new issue as easy to understand and reproducible as possible.

thank you for your help and best regards.

**Comment by sasumner** [comment]
Fixed in Notepad++ 7.6(.0).  See changes for that version: `Fix auto-indent issue by typing Enter on empty line.`
