### ISSUE TITLE
Autocompletion is too eager

### ISSUE THREAD

**Issue by keigra** [notepad-plus-plus/notepad-plus-plus#3658]
### Description of the Issue

Auto-completion is getting annoying as it tries to complete any word, even if the letter or word already is complete, or there has not been any occurrence of the correct word to be intduduced for the dictionary yet.

### Steps to Reproduce the Issue

1. On Preferences, set Auto-completion to Function only.
2. Write any word on TXT or source code file, and Npp will auto-complete it.

### Expected Behavior

Option to discard the auto-completion without extra key-presses.

### Actual Behavior

Npp suggests auto-completion to plain words and single letters. Often the words it suggests do not even come from the current file(s), and they are not library function names either.
Function parameter completion would otherwise be useful, so having to disable the auto-completion completely is a loss.

### Debug Information

Notepad++ v7.5   (64-bit)
Build time : Aug 15 2017 - 23:06:39
Path : C:\APPS\NPP7.5.5\notepad++.exe
Admin mode : OFF
Local Conf mode : ON
OS : Windows 7 (64-bit)
Plugins : mimeTools.dll NppConverter.dll

**Comment by donho** [comment]
Cannot reproduce in v7.8.2
