### ISSUE TITLE
UI Tweak Needed.

### ISSUE THREAD

**Issue by NileshGawai** [notepad-plus-plus/notepad-plus-plus#3659]
**Fancy tab styles** are very necessary, **smooth UI** is needed.
... of course, **_no doubt about performance_**.

**Comment by MetaChuh** [comment]
please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins if you update from version 7.5.9 or below.
if your issue still persists, and it is still of relevance, please feel free to file a new issue as easy to understand and reproducible as possible.

thank you for your help and best regards.

**Comment by sasumner** [comment]
>Fancy tab styles are very necessary, smooth UI is needed.

Nah!
