### ISSUE TITLE
Status bar cuts off "lines" count

### ISSUE THREAD

**Issue by garydgregory** [notepad-plus-plus/notepad-plus-plus#366]
See screenshot.

![image](https://cloud.githubusercontent.com/assets/1187639/8418931/1b4aed0a-1e6b-11e5-9065-6d5db9f6a1c4.png)

**Comment by sky5walk** [comment]
How many times must I resubmit this BUG report?! It is still broken as of v6.9.2.
![bug_notepad v692_statusbar](https://cloud.githubusercontent.com/assets/13093122/17600878/89088046-5fd3-11e6-94fc-073a32a5e30a.PNG)
[BUG_Notepad++v692_statusbar.txt](https://github.com/notepad-plus-plus/notepad-plus-plus/files/413970/BUG_Notepad.v692_statusbar.txt)
