### ISSUE TITLE
Update proxy not working

### ISSUE THREAD

**Issue by asimkumar2222** [notepad-plus-plus/notepad-plus-plus#3662]
### Steps to Reproduce the Issue

1.  Set a update proxy
2. Try to update
3. Or open the update proxy, it will show as 0.0.0.0

**Comment by jm009** [comment]
I had this issue on Windows Server 2008. The proxy is not saved, no matter if I open the dialog from the menu or by ``gup -options``
If I call ``gup -options`` from cmd.exe started as Administrator, it works.
What I would hope to see improved is the fact, that there is no error message. if there was an error message like "Could not be saved, no permission", this would be a hint for what to do next.

**Comment by juengling** [comment]
Same here with Windows 10, np++ v7.6, 64bit. Setting `127.0.0.1:3128` (it's cntlm behind) is ignored as described by @asimkumar2222.

**Comment by MetaChuh** [comment]
please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins if you update from version 7.5.9 or below.

run notepad++ as administrator to change your proxy setings.

thank you for your help and best regards.
