### ISSUE TITLE
Function List has no parser for Pascal/Delphi

### ISSUE THREAD

**Issue by dinkumoil** [notepad-plus-plus/notepad-plus-plus#3664]
### Description of the Issue
There is no parser available for Pascal/Delphi source code files in Function List. Therefor the Function List pane remains empty.

### Steps to Reproduce the Issue
1. Open a Pascal/Delphi source file.
2. Activate Function List pane.

### Expected Behavior
The Function List pane should display the syntax tree of the opened source file.

### Actual Behavior
The Function List pane remains empty.

### Debug Information
Notepad++ v7.5   (32-bit)
Build time : Aug 15 2017 - 23:02:57
Path : D:\Daten Entwicklung\privat\Delphi\AutoCodepage\AutoCodepage V1.0 [DXE2]\AutoCodepage\_npp\Win32\notepad++.exe
Admin mode : OFF
Local Conf mode : ON
OS : Windows 7 (64-bit)
Plugins : AutoCodepage.dll CustomizeToolbar.dll DSpellCheck.dll Explorer.dll LanguageHelp.dll mimeTools.dll NppConverter.dll NppEventExec.dll NppExec.dll NppExport.dll NppFTP.dll NppSaveAsAdmin.dll PluginManager.dll ReloadButton.dll XMLTools.dll 

Applies also to the 64-bit version.

**Comment by plagoni** [comment]
Hi
I'm a long term user of Delphi Pascal and has used UltraEdit for years. I'm new to NotePad++ but it looks like a great alternative to UE with the only exception so far that the function list does not work (it is blank for a pas file in version 7.5.3 32bit).
I have searched the Net intensively and my best search result is this page.
I can see that I have no chance of fixing it myself (RegExp experience very limited) and has tried to figure out how to include the code from this site into my local FunctionList.xml.
Is there any guidelines how-to-do-it? Or will there be a new np++ version available soon with the pascal functionality included?

Thanks in advance and Happy New Year
Per
