### ISSUE TITLE
Changes are lost without warning when 'Remember current session for next launch' is disabled

### ISSUE THREAD

**Issue by JohnCalin** [notepad-plus-plus/notepad-plus-plus#3666]
### Description of the Issue

Many features of Notepad++ are broken when 'Remember current session for next launch' is disabled.
During automatic restart, Notepad++ should remember/restore the current session even when this option is turned off.

As an example, restarting as administrator (in order to save a modified file you do not have write access to) will without warning lose all your changes.

While the rest of this bug focuses on the above example, the issue impacts any feature that includes an automatic restart of Notepad++.  

### Steps to Reproduce the Issue

1.   Open npp without admin rights
2.   Ensure 'remember current session for next launch' is not enabled
3.   Open a file you do not have write access on
4.   Edit the file
5.   Save - this will fail, and prompt you to restart with admin rights
6.   Click Okay to restart with admin rights

### Expected Behavior

Npp should be restarted, preserving my changes and allowing me to save with admin rights

### Actual Behavior

Npp is restarted, reloading the file from disk and losing my changes

**Comment by MetaChuh** [comment]
please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins if you update from version 7.5.9 or below.
if your issue still persists, and it is still of relevance, please feel free to file a new issue as easy to understand and reproducible as possible.

thank you for your help and best regards.
