### ISSUE TITLE
Word's separation marks bug for Armenian

### ISSUE THREAD

**Issue by brolny** [notepad-plus-plus/notepad-plus-plus#3669]
There are 6 punctuation marks in the Armenian 
՝ « » ։ ․ ֊
which not recognised by Notepad+ as word's separation marks.
May be just a hyphen "֊" not needs that behavior.
First 5 are never part of words.

https://en.wikipedia.org/wiki/Armenian_alphabet#Punctuation

**Comment by uskovboris** [comment]
Good morning!
Thank you for bug reporting! 
I was unable to reproduce this behaviour with the random Armenian text I've found in the Internet.
It is possible that the problem in specific codepage or something like this. 

Can you provide us with a sample file to reproduction.

Thank you in advance!

**Comment by brolny** [comment]
Really, you don't need even Armenian texts. 
1. Just copy-paste the line below to the program.
"Good  morning՝«»։․֊  all."
2. Make a double click on the word "morning".
3. You will see that 6 chars after the word also selected.

**Comment by ArkadiuszMichalski** [comment]
@brolny You still have this problem in latest NPP? I can reproduce it.

![aa](https://user-images.githubusercontent.com/2730894/93668093-b659f100-fa8a-11ea-8c56-4122f77e01ab.gif)

**Comment by donho** [comment]
Outdated.
