### ISSUE TITLE
Feature request: Remember scroll/cursor position in a previously opened file

### ISSUE THREAD

**Issue by JohnVeness** [notepad-plus-plus/notepad-plus-plus#3671]
It would be very useful to me if NPP could remember the scroll and cursor position that was last used in a file, when re-opening that file.

As an analogy, if you're familiar with it, consider how Excel remembers the last position which is the behaviour I would like. Compare this to how Word does not remember the position, always opening at the top of the document, which is the current NPP behaviour.

Actually, Excel remembers the last position at which the file was **saved** - I would prefer NPP to remember the last used position at the point that the file is closed (or NPP is quit), even if the user hadn't made any changes.

As another analogy, Adobe Acrobat Reader has this as a setting called "Restore last view settings when reopening documents".

Please note that I am not talking about the "Remember current session for next launch" feature, which I have unticked and don't want to tick. I would like NPP to somehow remember the last used position in _closed_ files, that I may not have opened for several days. The position would have to be stored somewhere separate than in the file itself - in the Excel analogy given above, the position is stored within the spreadsheet file itself, but I realise that won't be an option with text files.

To avoid getting out of control, you would probably want to limit this to, say, the last 100 used files.

For privacy purposes, you should probably implement this as a setting, so that people can turn it off if they're worried about bad actors being able to find out what were the users, say, 100 last used files and where within that file they were last viewing/editing.

In an ideal world, I suggest storing the scroll position and the cursor position separately. So for example the cursor may be at the bottom of the window, or it may be at the top, or in the middle, but in any case the file would re-open looking as identical as possible as when the user last closed it. Obviously if the user has resized the window in the meantime, things can't be recreated exactly, and note that I'm not suggesting remembering the window size or position on screen.

**Comment by flawiddsouza** [comment]
I made this https://github.com/flawiddsouza/Remember-Cursor-Position out of frustration. It's not perfect but it works.

**Comment by JohnVeness** [comment]
Many thanks for this. I'll open a new issue in your github, if that's OK.

**Comment by solf** [comment]
I want to 'upvote' this issue.
I was very surprised to realize that Notepad++ doesn't do this :(

**Comment by sasumner** [comment]
@solf, Did you try the plugin above? Maybe it meets your need.

Regardless, something like this isn't going to be implemented in Notepad++ itself.  Sorry.

**Comment by solf** [comment]
FWIW the plugin above doesn't appear to be working on NotepadPlusPlusPortable_7.8.1.paf.exe

**Comment by sasumner** [comment]
@solf I will see what I can do to work up a Pythonscript that implements desired behavior.

**Comment by solf** [comment]
@sasumner much appreciated!

**Comment by sasumner** [comment]
Following up...  I've been using this Pythonscript for a bit now and it seems to do the job.

I "install" it from my `startup.py` via:

```
import ClosedFileInfoMemory
ClosedFileInfoMemory.ClosedFileInfoMemoryObject()
```

The script, named `ClosedFileInfoMemory.py`:

```
# -*- coding: utf-8 -*-

# remember stuff about files no longer open in Notepad++, so that if they are ever reopened, things like last-known caret position can be restored

from Npp import editor, notepad, NOTIFICATION, SCINTILLANOTIFICATION
import os
import json
import time

class ClosedFileInfoMemoryObject(object):

    def __init__(self):
        dir_to_use = notepad.getNppDir()
        #dir_to_use = os.environ['TEMP']
        self.data_pathname = dir_to_use + os.sep + 'ClosedFileInfoMemory.json'
        try:
            with open(self.data_pathname, 'r') as f: self.data_dict = json.load(f)
        except:
            self.data_dict = {}
        self.opening_buffers_list = []
        editor.callback(self.updateui_notify, [SCINTILLANOTIFICATION.UPDATEUI])
        notepad.callback(self.fileopened_notify, [NOTIFICATION.FILEOPENED])
        notepad.callback(self.bufferactivated_notify, [NOTIFICATION.BUFFERACTIVATED])
        notepad.callback(self.shutdown_notify, [NOTIFICATION.SHUTDOWN])

    def fileopened_notify(self, args):
        bid = args['bufferID']
        opened_file_path = notepad.getBufferFilename(bid)
        if not os.path.isfile(opened_file_path): return  # don't run for files like "new 3" (maybe don't need this check?)
        if opened_file_path not in self.opening_buffers_list: self.opening_buffers_list.append(opened_file_path)

    def bufferactivated_notify(self, args):
        bid = args['bufferID']
        activated_file_path = notepad.getBufferFilename(bid)
        if activated_file_path in self.opening_buffers_list:
            self.opening_buffers_list.remove(activated_file_path)
            if activated_file_path in self.opening_buffers_list: self.opening_buffers_list.remove(activated_file_path)  # for cloned doc?
            if activated_file_path in self.data_dict:
                if 'current_pos' in self.data_dict[activated_file_path]:
                    cp = self.data_dict[activated_file_path]['current_pos']
                    if cp >= editor.getTextLength(): cp = 0
                    editor.setEmptySelection(cp)
                    editor.scrollCaret()  # Ensure the caret is visible
                if 'first_visible_line' in self.data_dict[activated_file_path]:
                    fvl = self.data_dict[activated_file_path]['first_visible_line']
                    if fvl >= editor.getLineCount(): fvl = 0
                    editor.setFirstVisibleLine(fvl)  # Scroll so that a display line is at the top of the display

    def updateui_notify(self, args):
        current_file_path = notepad.getCurrentFilename()
        if current_file_path not in self.data_dict: self.data_dict[current_file_path] = {}
        d = self.data_dict[current_file_path]
        d['current_pos'] = editor.getCurrentPos()
        d['first_visible_line'] = editor.getFirstVisibleLine()
        d['day_last_seen'] = self.get_time_in_days()

    def shutdown_notify(self, args):
        if 1:  # check for and remove very old entries
            current_time_in_days = self.get_time_in_days()
            to_del_list = []
            for file in self.data_dict:
                if 'day_last_seen' in self.data_dict[file]:
                    if current_time_in_days - self.data_dict[file]['day_last_seen'] > 90:
                        to_del_list.append(file)
            for file in to_del_list: del self.data_dict[file]
        try:
            with open(self.data_pathname, 'w') as f: f.write(json.dumps(self.data_dict, sort_keys=True, indent=1, default=str))
        except:
            pass

    def get_time_in_days(self): return int(time.time() / 60 / 60 / 24)
```

**Comment by solf** [comment]
@sasumner 
Huge thanks for posting this! It works perfectly for me so far!
