### ISSUE TITLE
Playback recorded macro with Find Previous crashes NPP

### ISSUE THREAD

**Issue by byronigoe** [notepad-plus-plus/notepad-plus-plus#3679]
The latest version (7.4.2) changed the Find dialog to have Find Next and Find Previous buttons instead of a radio button to indicate find direction. This seems to have introduced a bug when using macros.

### Description of the Issue
Playback of a recorded macro that contains a Find Previous command, that is the new button that looks like "<< Find", results in Notepad++ crashing.

### Steps to Reproduce the Issue
1. Record a macro
2. Ctrl-F
3. Enter some text to find
4. Click "<< Find" to find the previous occurrence
5. Click "Close"
6. Stop Recording
7. Playback

### Expected Behavior
It should work

### Actual Behavior
Runtime Exception - Internal error: unknown saved command!
Recovery Initiating - Notepad++ will attempt to save any unsaved data. However, dataloss is very likely.
Recovery Success - Notepad++ was able to successfully recover some unsaved documents...
Notepad++ : a free (GNU) source code editor has stopped working

### Debug Information
Notepad++ v7.4.2   (32-bit)
Build time : Jun 18 2017 - 23:34:19
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10 (64-bit)
Plugins : ComparePlugin.dll IndentByFold.dll mimeTools.dll NppConverter.dll NppExport.dll NppFTP.dll PluginManager.dll

**Comment by dinkumoil** [comment]
Please consider an update, this was fixed in Npp v7.5. Also the two "Find" buttons have been reverted to one button.

**Comment by byronigoe** [comment]
The only reason I updated to 7.4.2 was because the automatic update check suggested it. Then going to ? -> Update Notepad++ said that no update was available. I have manually updated to 7.5.1 and verified that this issue is fixed.

It is frustrating for an update to be pushed (via the auto-update mechanism) when it has known bugs that have already been fixed.
