### ISSUE TITLE
Drag and Drop into npp

### ISSUE THREAD

**Issue by illumi** [notepad-plus-plus/notepad-plus-plus#368]
Dragging and dropping files into the NPP window doesn't seem to work as it once did.

Expected (and I believe previous behaviour) was the ability to multi select files and drop them into the npp frame for them to be opened for editing.

**Comment by cmeriaux** [comment]
No problem with my notepad++
Try to remove temporarily your plugins.

**Comment by illumi** [comment]
Ah, it was a plugin issue. Thanks.

**Comment by ariccio** [comment]
Any idea which plugin?

**Comment by illumi** [comment]
No, what I did was:

Closed npp
Removed the plugins folder
Started npp
Checked drag+drop functionality (which was working)
Put the plugins folder back
Restart npp
Functionality was still working

End result is all plugins are still there and it works again.

**Comment by milipili** [comment]
No WizMouse nor synergy nor something using some mouse hooks somewhere ? Or n++ launched as admin and trying to drag&drop from a non-admin process ?

**Comment by illumi** [comment]
I really don't know what was causing it. I don't have any mouse software installed and npp was launched as normal. Perhaps something with the update process caused it to stop responding to drag/drop.
