### ISSUE TITLE
batch.xml is missing from installer

### ISSUE THREAD

**Issue by yamlfd** [notepad-plus-plus/notepad-plus-plus#3680]
Title says all. In 7.5.1 ZIP files it exists.

**Comment by SinghRajenM** [comment]
Fix #3677 has been already submitted.

**Comment by yamlfd** [comment]
I cannot see the code change in https://github.com/notepad-plus-plus/notepad-plus-plus/blob/master/PowerEditor/installer/nsisInclude/autoCompletion.nsh

**Comment by MAPJe71** [comment]
@yamlfd [here](https://github.com/notepad-plus-plus/notepad-plus-plus/pull/3677/commits/6bc9a7d7b30936ca311a5a474228a0dd90e30bcc) it is.

**Comment by yamlfd** [comment]
This is not in master... so it is not in the project.

**Comment by yamlfd** [comment]
Is https://github.com/MAPJe71/NPP-Plugin-PluginManager_Fork this the place where the new plugin manager it will be developed? So I can file issues?

**Comment by MAPJe71** [comment]
@yamlfd 
>This is not in master... so it is not in the project.

Yep correct and @SinghRajenM has submitted a fix for it (the mentioned pull-request #3677).
When PR #3677 is accepted and merged, the next Notepad++ release will have this issue fixed.

>Is https://github.com/MAPJe71/NPP-Plugin-PluginManager_Fork the place...

No, that's my fork of the [present PluginManager plugin by @bruderstein](https://github.com/bruderstein/nppPluginManager). The new plugin-manager is developed in the [pluginManager branch](https://github.com/notepad-plus-plus/notepad-plus-plus/tree/pluginManager) of this Notepad++ repository (you're reading in it now) and as it will be part of the Notepad++ product you can report issues [here](https://github.com/notepad-plus-plus/notepad-plus-plus/issues).
