### ISSUE TITLE
Feature request: Zoom view of document map like in Kate

### ISSUE THREAD

**Issue by durgaprasadpv** [notepad-plus-plus/notepad-plus-plus#3684]
New feature request: Document map is a good feature. If we can get zoomed view when mouse is hovered over map at any place so that we can quickly go through the text.

This feature is available in Kate editor as shown in attached image.

Please go through and implement if it is possible.

-Durgaprasad
![kate](https://user-images.githubusercontent.com/31503820/29913393-b1681430-8e52-11e7-8446-3db44227c23d.png)

**Comment by MetaChuh** [comment]
if you click on any part at the document map, the full content will be shown and editable at the editor panel.

it will not be necessary to display its contents a third time.

many thanks and best regards.
