### ISSUE TITLE
authenticode and scintilla errors after upgrading to 7.5.1

### ISSUE THREAD

**Issue by punknubbins** [notepad-plus-plus/notepad-plus-plus#3686]
### Description of the Issue
OS version: Win7 Enterprise 64bit
App version: notepad++ 7.5.1 32bit

After installing the latest version of the notepad++ (32bit to retain plugin compatibility) the application fails to launch.

This is the same behavior I reported in [issue 3573](https://github.com/notepad-plus-plus/notepad-plus-plus/issues/3573)

Possibly related: I am on a corporate network with a transparent web proxy and corporate mandated middleman cert so if your application is validating a cert against a web cert, the application will always get a mismatch.

### Steps to Reproduce the Issue

1. Install 7.5.1
2. Launch
3. receive errors, application closes after errors are dismissed

### Expected Behavior
Application would launch

### Actual Behavior
Received error on launch then app closes after error is dismissed

### Workaround
downgrade back to 7.3.3

**Comment by ArkadiuszMichalski** [comment]
@punknubbins Do you still have this problem in latest Notepad++ version?

**Comment by donho** [comment]
Outdated.
