### ISSUE TITLE
portable, additional fonts folder

### ISSUE THREAD

**Issue by Arnaudv6** [notepad-plus-plus/notepad-plus-plus#3687]
At work I am to use Windows. And have no admin rights.
But it is OK for notepad++ has a portable version and enlightens my days.

I should very much like to use my favorite font though.
And of course it is not installed, and I am not allowed to install it.

It would be nice if Notepad++ would search fonts also in a portable directory, like the GIMP does.

**Comment by MetaChuh** [comment]
notepad++ can only use fonts installed on your system.

please use fonts that are available on all machines you work on.

many thanks and best regards.

**Comment by Arnaudv6** [comment]
Too bad.

**Comment by sasumner** [comment]
> I am not allowed to install it.

You can't request from your I.T. department that it be installed for you?

**Comment by Arnaudv6** [comment]
To be honest I don't work there anymore. So I am not impacted as I used to. But I still think this feature is a major plus for a portable version.

**Comment by sasumner** [comment]
I think that carrying fonts along goes above and beyond what Notepad++ should do, but opinions may vary.  Cheers.

**Comment by Arnaudv6** [comment]
To be honest I don't work there anymore. So I am not impacted as I used to be. But I still think this feature is a major plus for a portable version.

**Comment by Arnaudv6** [comment]
Sorry...was posting from my telephone and it went twice.  
BUT... The bug report is not about packing the fonts with n++, so much as allowing for a custom fonts directory to be searched (or a directory relative to n++ binary's folder)
