### ISSUE TITLE
PluginManager.dll is missing in 32-bit 7.5 and 7.5.1 releases

### ISSUE THREAD

**Issue by genderquery** [notepad-plus-plus/notepad-plus-plus#3690]
The installer and zip files from the [main download page](https://notepad-plus-plus.org/download) for the 32-bit 7.5 and 7.51 releases are missing PluginManager.dll. It is, however, present in the 7.4.2 release.

**Comment by MAPJe71** [comment]
Please read the second paragraph [here ](https://notepad-plus-plus.org/news/notepad-7.5-released.html).

**Comment by genderquery** [comment]
That make sense. It wasn't listed in the changes in the download area, but I didn't think to check the news. Thanks.
