### ISSUE TITLE
Feature Request: add more options to bar style search box as many as possible

### ISSUE THREAD

**Issue by X1353135** [notepad-plus-plus/notepad-plus-plus#3692]
It would be nice if bar style search box supports options on Find(Replace) dialog box as many as possible.
bar style search box currently supports only incremental search, but I personally feel that the bar style search box is more useful than popup style Find(Replace) dialog box, because it doesn't cover over editing area.

**Comment by X1353135** [comment]
This is a nice example of another editor.

![kate_find_replace](https://user-images.githubusercontent.com/29348192/30000602-39867f06-90a5-11e7-91ff-d0ea90bf9bd6.PNG)

**Comment by sasumner** [comment]
Incremental search and the regular Find/Replace search are different features, and thus have different attributes.
