### ISSUE TITLE
Notepad++ 64bits 5.7.1 function list dont work on javascript

### ISSUE THREAD

**Issue by albertci** [notepad-plus-plus/notepad-plus-plus#3696]
### Description of the Issue

Notepad++ 64bits 5.7.1 function list dont work on javascript
### Steps to Reproduce the Issue

1. Open a js file
2. Function List is empty, but there is a lot on functions
3.

**Comment by MAPJe71** [comment]
Try Notepad++ 7.5.1 64 bits.

Give us some examples of functions that you do not see in the Function List tree.

**Comment by Yaron10** [comment]
I have the same problem with a fresh NPP 7.5.1 portable.

```
function togglePB(click)
{
	var newWin = OpenBrowserWindow({ private: ! PrivateBrowsingUtils.isWindowPrivate(window) });

	if(click.button == 0)
		newWin.addEventListener("focus",  function switchWindows() { window.focus(); BrowserTryToCloseWindow(); newWin.removeEventListener("focus", switchWindows); });
}

```
Modifying `<association id=  "javascript_function"   langID="58"` to `<association id=  "javascript_function"   langID="19"` solves the problem.

***
Notepad++ v7.5.1   (32-bit)
Build time : Aug 29 2017 - 02:35:41
Path : C:\Users\---\npp.7.5.1.bin\notepad++.exe
Admin mode : ON
Local Conf mode : ON
OS : Windows 7 (32-bit)
Plugins : mimeTools.dll NppConverter.dll NppExport.dll

**Comment by albertci** [comment]
I have the same problem by change 59 by 19 on line 91 of functionList.xml

			<association id=  "javascript_function"   langID="19"                          />
