### ISSUE TITLE
Make Find and Replace tab more the same

### ISSUE THREAD

**Issue by scootergrisen** [notepad-plus-plus/notepad-plus-plus#3698]
Pressing Ctrl+F and Ctrl+H brings up the Find and Replace tabs.
But the button order is not the same.

In the Find tab we got:
"... in all open documents"
"... in current documents"

But in Replace tab the buttons are in the opposit order:
"Replace all"
"... in all open documents"

So i suggest to switch the button in the Find tab:
"... in current documents"
"... in all open documents"

So the "... current ..." button is the first and "... all open ..." is the second in both tabs.

Also i suggest to either change:
"Find all in all open documents"
To:
"Find all"

Or:
"Replace all"
To:
"Replace all in all open documents"

That way both Find and Replace tabs use the same style.

**Comment by uhammec** [comment]
I'd agree - with tabbed views, it is very disorienting to have buttons flip places and have different wordings.

**Comment by MetaChuh** [comment]
@scootergrisen 

please don't forget, that the majority of users are very used to the order it has been for years.
we can not change this design, as notepad++ is specifically designed for users that do not want to re-learn an applications usage, and re-orientate for their used workflow, when updating an application like notepad++.

thank you for your help and best regards.

**Comment by sasumner** [comment]
@scootergrisen Also note that "Replace all" is not equivalent to "Replace all in all open documents", so changing it thus doesn't make sense.

**Comment by sasumner** [comment]
> the Find and Replace tabs.
But the button order is not the same.

#8413 makes the button order the same.

Regarding text on the buttons, as this is user changeable, make it what you want it to be! :-)
