### ISSUE TITLE
Plugin HTML Tag is Wrong in Notepad++ V6.7.9.2

### ISSUE THREAD

**Issue by bardcrack** [notepad-plus-plus/notepad-plus-plus#370]
Update to version v6.7.9.2 and when trying to use a command to HTML Tag Plugin Ctrl + Shift + T, instead of selecting the piece of code that is between the HTML tags, what it does is move to another Note Pad ++ file that is currently open.

**Comment by cmeriaux** [comment]
What about your shortcut config ? "Ctrl + Shift + T" has been reallocated to another shortcut ?
Check out your config.

**Comment by bardcrack** [comment]
Thanks so Much. You Right.

**Comment by cmeriaux** [comment]
You're welcome. Don't forget to close the ticket if you're satisfied.
