### ISSUE TITLE
Language styles ignored when file is sent to Notepad++ from Windows Explorer

### ISSUE THREAD

**Issue by WallyWaffles** [notepad-plus-plus/notepad-plus-plus#3704]
### Description of the Issue
Whenever I send a code file via double-clicking or another program (e.g. an FTP client), it is displayed as a regular plain text file, without any language-specific styles.  (There are no issue when I directly open a file via the "Open" or "recent file" commands.)  To get the styles to display, I have to either manually select the language, or close the file and then open it from the recent file list.

I checked the style configurator, and the default-installed language-to-extension associations are in place, with no user modification.

This issue began with one of the recent updates.

### Steps to Reproduce the Issue
Open a CSS, JavaScript, or PHP file by double-clicking it in Windows Explorer.

### Expected Behavior
Notepad++ should automatically select the language associated with the file extension and display the relevant styles.

### Actual Behavior
Notepad++ does not automatically select the language associated with the file extension.  It instead displays the default plain text styles.

### Debug Information
Notepad++ v7.5.1   (64-bit)
Build time : Aug 29 2017 - 02:38:44
Path : F:\Program Files\Notepad++\notepad++.exe
Admin mode : ON
Local Conf mode : OFF
OS : Windows 7 (64-bit)
Plugins : mimeTools.dll NppConverter.dll

**Comment by ArkadiuszMichalski** [comment]
@WallyWaffles Have you stiil get this problem in latest Notepad++? I can't reproduce it.

**Comment by donho** [comment]
Outdated.
Cannot be reproduced.

**Comment by WallyWaffles** [comment]
I am happy to report that this is no longer an issue.
