### ISSUE TITLE
Never fix the Cyrillic bug in 7 version which wasn't in 6 version?

### ISSUE THREAD

**Issue by Geograph-us** [notepad-plus-plus/notepad-plus-plus#3705]
Bug in windows-system with Russian Cyrillic letters.
I still use 6.4.5 version because it is last version without this bug.
In new versions Notepad++ autoselect Macintosh-encoding for Ansi-files in Windows. So Cyrillic letters show incorrect. Only manual select right encoding help, but it's not solution.
How it **right** looks in old version:
![6 4 5](https://user-images.githubusercontent.com/7619691/30106115-e8fc0594-9313-11e7-870a-3435bc2d2c71.png)

How it's **wrong** looks in new versions
![7 5 1](https://user-images.githubusercontent.com/7619691/30106128-ee10af26-9313-11e7-86da-5e88427377ba.png)

How I can delete Macintosh-encoding from Notepad++?

**Comment by XX-J** [comment]
#431

**Comment by CookiePLMonster** [comment]
Fixed by #4925
