### ISSUE TITLE
Selected text and Cursor position incorrect on a 4K display

### ISSUE THREAD

**Issue by benamada** [notepad-plus-plus/notepad-plus-plus#3707]
### Description of the Issue

On a 4K display at the recommended 250% zoom level on Windows 10 Creators Update running Notepad++ 7.5 32-bit edition, there are 2 related issues:

- The visible cursor position is not actually where the cursor is.
- If I select/highlight text either with the mouse or keyboard, the visible selected text is different from what's actually selected.

In the screenshot below, I double clicked on the word `consectetur`, and you can see what's visibly selected is off by a couple of characters.  In reality, `consectetur` is actually selected because if I do a Ctrl-C to copy the selected text and paste it elsewhere, what gets pasted is the exact text `consectetur`.

### Expected Behavior
I expect that the cursor position I see is the actual cursor position and the selected text I see is what is actually selected.

![notepad _4k_display_text](https://user-images.githubusercontent.com/8443403/30128189-ec6f14c0-936b-11e7-945d-5055149c702a.png)

**Comment by simonhearn** [comment]
I have this issue as well. I just posted a reply on a different thread... https://github.com/notepad-plus-plus/notepad-plus-plus/issues/4746

**Comment by MetaChuh** [comment]
i can not reproduce this on notepad++ 7.6.6 on windows 10 build 1809 using 250% or any other scaling factor.

please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins if you update from version 7.5.9 or below.

if your cursor position still does not match the real position, please right click on your notepad++ icon and select `properties > compatibility > change high dpi settings`, activate `override high dpi scaling behavior` and set `scaling performed by:` to `system (enhanced)`, as seen at the screenshot below.

![Imgur](https://i.imgur.com/qVQ4Bg8.png)

you can also choose `system` for a classic notepad++ look on scaled displays, which will look like this:

![Imgur](https://i.imgur.com/WqSSpUo.png)

note: it is recommended to disable smooth font for the classic scaler look, by going to `settings > preferences > editing` and unchecking `enable smooth font` in notepad++, if it is enabled as seen at the screenshot below.

![Imgur](https://i.imgur.com/vFFvIOR.png)

thank you for your help and best regards.

-----
```
general notes:

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
(no extra account is needed, just use your github account to sign in)
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)

**Comment by benamada** [comment]
Hi @MetaChuh, thanks for looking into this.  I tried `system (enhanced)` and still had the same problem, but changing it to `system` and the highlighting works correctly.

To explain my configuration a bit more, my Windows "primary" monitor is at 1920x1080 (full HD) at 100% zoom level.  When I move Notepad++ to my "non-primary" 4k display at 250% zoom level is when the highlight mismatch occurs.  Not sure if this is applicable here but I read before that some apps will incorrectly use the primary monitor settings at all times even when the app is on a different monitor where settings specific to that monitor should be used instead.  For now I'm happy to have this resolved using the `system` high dpi scaling option, and I'm glad you brought that to my attention.
