### ISSUE TITLE
CMakeLists.txt does not generate usable project files

### ISSUE THREAD

**Issue by TBladen** [notepad-plus-plus/notepad-plus-plus#3709]
### CMakeLists.txt does not generate usable project files
CMakeLists.txt misses a number of source files and library dependencies, meaning it cannot generate project files for a succesful build.
```
.\PowerEditor\src\Notepad_plus.h(53): fatal error C1083: Cannot open include file: 'pluginsAdmin.h': No such file or directory (compiling source file .\PowerEditor\src\ScitillaComponent\Buffer.cpp)
```
Initially the compiler will show errors as above, but if these files are manually added to the VS project then the linker will throw undefined reference errors for a number of Windows library functions (such as in Crypt32).

I found this issue after trying to make the supplied VS2015 project file work in VS2017 without success and trying CMake, but think that having a working CMake setup may be useful to other developers too (especially for any attempts to go cross-platform).

### Solution
I have a commit ready to make a pull-request for (if you think it is needed) that updates CMakeLists.txt to create a working build (it does not add support for building SciLexer though) available [here](https://github.com/TBladen/notepad-plus-plus/commit/98b329703d5965d2418db9e2ea605f6b2f819090?diff=split).
 
Let me know what you think! Hopefully making an issue first was the right thing to do - I'm just starting out in open-source contributions!

**Comment by MetaChuh** [comment]
please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins if you update from version 7.5.9 or below.
if your issue still persists, and it is still of relevance, please feel free to file a new issue as easy to understand and reproducible as possible.

thank you for your help and best regards.

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
(no extra account is needed, just use your github account to sign in)
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)
