### ISSUE TITLE
Suggestion: Show keyboard shortcuts in tooltips and context-menus

### ISSUE THREAD

**Issue by Rikk** [notepad-plus-plus/notepad-plus-plus#371]
Just adding this as a suggestion (I haven't found similar)...
The display of keyboard shortcuts not only inside menus, but also in buttons' tooltips and context-menus.

![tipcuts](https://cloud.githubusercontent.com/assets/2916485/8440946/da35be8a-1f4b-11e5-909c-3a71f2cb6841.png)

![contextcuts](https://cloud.githubusercontent.com/assets/2916485/8441082/81353788-1f4c-11e5-8889-ed4bf4dd90a4.png)

**Comment by MetaChuh** [comment]
closed due to inactivity (4y)
