### ISSUE TITLE
Allow session periodic backup independent of remember current session for next launch

### ISSUE THREAD

**Issue by yusnielb** [notepad-plus-plus/notepad-plus-plus#3711]
### Description of the Issue
Now is only possible to use the session periodic backup if remember current session for the next launch is enabled.

### Steps to Reproduce the Issue
1. Go to Preferences
2. Backup section
3. Session snapshot and periodic backup group

### Expected Behavior
Be allowed to use session periodic backup in case of crash without need to remember the session in case of proper closing

**Comment by ArkadiuszMichalski** [comment]
Duplicate of https://github.com/notepad-plus-plus/notepad-plus-plus/issues/5218.
