### ISSUE TITLE
Syntax highlighting incorrectly identifies file type

### ISSUE THREAD

**Issue by Angew** [notepad-plus-plus/notepad-plus-plus#3716]
### Description of the Issue

After upgrading to Notepad++ 7.5.1 (64-bit), opening any sets its highlighting languageto `ASN.1`, regardless of its name or extension. I've observed this with `CMakeLists.txt`, `*.cmake`, and `*.cpp` files, but it probably happens with all file types.

### Steps to Reproduce the Issue

1. Using Notepad++ 7.5.1 (64-bit), open any file.

### Expected Behavior

Highlighting language for the file is set according to its name or extension (e.g. CMake for `CMakeLists.txt` or `*.cmake`, C++ for `*.cpp` etc.)

### Actual Behavior

Highlighting language for the file is set to ASN.1

### Debug Information

Notepad++ v7.5.1   (64-bit)
Build time : Aug 29 2017 - 02:38:44
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : ON
Local Conf mode : OFF
OS : Windows 7 (64-bit)
Plugins : none

This only started happening when I upgraded to 7.5.1 from my previous version (not sure which exact version that was, but it was recent).

**Comment by ArkadiuszMichalski** [comment]
@Angew Have you stiil get this problem in latest Notepad++? I can't reproduce it.

**Comment by donho** [comment]
Cannot reproduced in the latest version.
