### ISSUE TITLE
Wildcards not possible for path in "Find in Files"

### ISSUE THREAD

**Issue by Hompe** [notepad-plus-plus/notepad-plus-plus#3717]
### Description of the Issue
Search and Replace / "Find in Files":
Wildcards work for file filter but not for search directory. 

Is this a bug or are wildcards in general not possible for pathes?

### Steps to Reproduce the Issue
I have directories for every day:
...
C:\LogFiles\Day\20170830\
C:\LogFiles\Day\20170831\
C:\LogFiles\Day\20170901\
C:\LogFiles\Day\20170902\
...
each with many log and other files
I want to search only for September, not the rest of the year.
I type for search directory:
C:\LogFiles\Day\201709*

### Expected Behavior
Search in all Log files of September.

### Actual Behavior
No search happens. Obviously the path with the asterix is wrong.

### Debug Information
Notepad++ v7.5.1 (32bit)
Windows 10 Version 1703

**Comment by bahusoid** [comment]
Yep.  Pattern search only applies for file names... With your requirements you are better off with some more specialized app. I know for sure that Total Commander can do it.

**Comment by Hompe** [comment]
Thanks for your suggestion. Unfortunately the decision about installing apps is not mine. I'm very glad to have Notepad++ at least.
And honestly spoken I don't see the point why wildcards in filename is a common feature while wildcards in path should be a uncommon special thing ... ;-)

**Comment by mirh** [comment]
Related to #3114

**Comment by MetaChuh** [comment]
the find in files function serves its basic purposes, for being a small goodie inside notepad++.

we will not integrate features that are handled much better using specifically designed applications for that task.

you can e.g. use the free utility [FileSeek](https://www.fileseek.ca/Download/).
it has notepad++ integration and a lot of include/exclude, date and regex functions. much more than can ever be integrated into notepad++.

many thanks and best regards.

**Comment by jportoles** [comment]
For the people Googling this, take a look at VSCode, it does the job exceedingly well. You can even replace chunks of code with new lines in them, without painstakingly replacing every new line with "\n ".

**Comment by yury-kozlov** [comment]
> the find in files function serves its basic purposes, for being a small goodie inside notepad++.
> 
> we will not integrate features that are handled much better using specifically designed applications for that task.
> 
> you can e.g. use the free utility [FileSeek](https://www.fileseek.ca/Download/). it has notepad++ integration and a lot of include/exclude, date and regex functions. much more than can ever be integrated into notepad++.
> 

This is frustrating, if the requested feature is implemented it will surely make life easier for many people
