### ISSUE TITLE
Shortcuts for SCI_CUT, COPY, UNDO, REDO, etc are not saving

### ISSUE THREAD

**Issue by vitaliylag** [notepad-plus-plus/notepad-plus-plus#3720]
Steps to Reproduce:
1. Click Settings –> Shortcut mapper.
2. Choose "Scintilla commands" tab.
3. Double click on "SCI_CUT".
4. Check Alt and X. Leave Ctrl and Shift unchecked.
5. Press "Add" to add this shortcut to the list. This will be third shortcut.
6. Press "OK".
7. Close shortcuts window. Added shortcuts work yet.
8. Restart the Notepad++.

Expected Behavior:
Shortcuts are saved in shortcuts.xml and work after restarting Notepad++.

Actual Behavior:
Shortcuts are not saved in shortcuts.xml and do not work after restarting Notepad++.

**Comment by cmeriaux** [comment]
Can you post your debug info please ?

**Comment by vitaliylag** [comment]
In OS 1:
```
Notepad++ v7.5.1   (32-bit)
Build time : Aug 29 2017 - 02:35:41
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 8.1 (64-bit)
Plugins : mimeTools.dll NppConverter.dll NppExport.dll PluginManager.dll TabIndentSpaceAlign.dll 
```

In OS 2:
```
Notepad++ v7.5.1   (32-bit)
Build time : Aug 29 2017 - 02:35:41
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 8.1 (32-bit)
Plugins : mimeTools.dll NppConverter.dll NppExport.dll TabIndentSpaceAlign.dll
```

The bug occurs in both OS.

**Comment by cmeriaux** [comment]
Problem fixed.
The New shortcuts was correctly written in shortcuts.xml. The problem was on the configuration loading side.
