### ISSUE TITLE
Screen flicker continuously when last line = 999

### ISSUE THREAD

**Issue by user202729** [notepad-plus-plus/notepad-plus-plus#3722]
### Description of the Issue
The screen flicker continuously. This also happens in older version npp7.3.3.

### Steps to Reproduce the Issue
1. Set screen resolution to 1280x800. (which is the default for some computers)
2. Open Notepad++, maximize the window.
3. Enter more than 1000 newlines.
4. Go to line 1, enter 150 characters, which should just fit the window. (if you enter 1 more character the horizontal scrollbar will appear)
5. (Assuming the scrollbar does not appear now) Go to (use Ctrl+G) line 999.

### Expected Behavior
The screen show the horizontal scrollbar.

### Actual Behavior
The horizontal scrollbar flicker, and so is the screen.

### Debug Information
Notepad++ v7.5.1   (32-bit)
Build time : Aug 29 2017 - 02:35:41
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10 (32-bit)
Plugins : none

**Comment by gstavi** [comment]
Reproduced it. On older version on Linux with wine.

From observation what happens is:
Line 1000 should be barely visible at bottom of visible area.
Horizental bar should be set to have almost but an "hair" to the right.

On screen refresh
1. Decide that horizental bar is now required. Add horizental bar --> screen refresh.
2. Horizental bar reduces vertical space, line 1000 is dropped out of view so left margin is shrinked --> screen refresh.
3. Horizental bar is no longer required -> screen refresh.
4. Line 1000 is back in view -> left margin is expended -> screen refresh.
5. Goto 1.

**Comment by MetaChuh** [comment]
not reproducible on notepad++ 7.6.6 at 1280x800 or higher resolutions, with word wrap disabled and enabled.

<kbd>Notepad++ v7.6.6   (32-bit)
Build time : Apr  3 2019 - 23:49:50
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10 (64-bit)
Plugins : mimeTools.dll NppConverter.dll NppExport.dll NppJumpList.dll</kbd>

please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins.
if your issue still persists, and it is still of relevance to you, please feel free to file a new issue as detailed and reproducible as possible.

thank you for your help and best regards.

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
(no extra account is needed, just use your github account to sign in)
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)

**Comment by gstavi** [comment]
Not that I care too much but I was able to reproduce it with v7.6.6 over wine.

Steps to reproduce:
Fill notepad with long lines, but make sure they still fit horizontally on screen:
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ

Scroll down so line 1000 is visible at bottom of screen.
Drag window bottom edge up until only line 999 shows but just before Notepad++ shrinks the line number area.
Drug window right edge slowly to the left.
Just when original slider should appear, screen will begin to flicker.

**Comment by victormunoz** [comment]
This problem still happens in notepad 7.6.6 (windows 10), not always, but sometimes it happens. It's difficult to find the steps to reproduce the problem,
