### ISSUE TITLE
NPPN_FILEBEFORECLOSE received when moving a tab to the 2nd view

### ISSUE THREAD

**Issue by ezra100** [notepad-plus-plus/notepad-plus-plus#3724]
### Description of the Issue

So I'm working on some plugin for NPP and I just noticed that when moving a tab from one view to the other the function [doClose()](https://github.com/notepad-plus-plus/notepad-plus-plus/blob/master/PowerEditor/src/NppIO.cpp) runs and sends the NPPN_FILEBEFORECLOSE notification. Is that the expected behavior or should I try to fix it?

### Steps to Reproduce the Issue

1. Open 2 files
2. Move one of them to the 2nd view.

### Expected Behavior

No notification should be sent to the plugins.

### Actual Behavior

NPPN_FILEBEFORECLOSE and NPPN_FILECLOSED are sent to the plugins.

**Comment by donho** [comment]
It's a normal behaviour.
