### ISSUE TITLE
? / Extensions (Erweiterungen) menu opens outdated wiki

### ISSUE THREAD

**Issue by ke352802081770314** [notepad-plus-plus/notepad-plus-plus#3729]
### Description of the Issue
When I click on the menu entry ? / Erweiterungen (likely ? / Extensions in the English version), the web page http://docs.notepad-plus-plus.org/index.php/Plugin_Central is opened in my browser. This page is from 2014, and does not mention 64bit at all.

### Steps to Reproduce the Issue

1. click on the menu entry ? / Erweiterungen

### Expected Behavior
I expect a web page that gives me an up-to-date list of plugins, including 64bit compatibility data on each one.

### Actual Behavior
I get a webpage saying "This page was last modified on 10 October 2014, at 17:13" which does not inspire confidency in the accuracy of the given version numbers, and it makes no mention of 64-bit or x64 in its entirety, including not a caution that unless stated otherwise plugins may work for 32bit only.
In the case of Compare, the link points to https://sourceforge.net/projects/npp-compare/ and a comment by ghaustwre on that page says " If you need 64 Bit Plugin please refer to GIT. They modded the code to match 64 Bit." but it has no link so I haven't a clue where I should look for this "GIT". 
As much as I agree with your no-ad policy, removing the plugin helper deserved a more helpful replacement than a link to an obsolete Wiki page.

### Debug Information
not needed

**Comment by MetaChuh** [comment]
fixed

**Comment by chcg** [comment]
Fix was removal of the menu entry. N++ contains since 7.6.x Plugin Admin for a list of currently available plugins which is managed via https://github.com/notepad-plus-plus/nppPluginList.
