### ISSUE TITLE
Numbers

### ISSUE THREAD

**Issue by Zeckay** [notepad-plus-plus/notepad-plus-plus#3730]
My numbers are changed by wierd signs

**Comment by dail8859** [comment]
Try choosing a different font in the style configurator to see if that fixes it.

**Comment by Zeckay** [comment]
nope i tired and still wierd signs

**Comment by Zeckay** [comment]
tried**

**Comment by dail8859** [comment]
Can you try to provide any more useful information other than you have weird signs?

**Comment by Zeckay** [comment]
![image](https://user-images.githubusercontent.com/31831669/30253695-5f50b3b0-9658-11e7-964b-9227fe396912.png)
if you can see the screen shot, those sign appears when i press 0

**Comment by user202729** [comment]
Are you sure that you're using English keyboard? The "FRA" at the lower right corner may be a problem.
If you switch that to English (ENG) and it works, then that is not Notepad++ problem.
Also consider turning off all French keyboard helper programs.

**Comment by MetaChuh** [comment]
please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins if you update from version 7.5.9 or below.
if your issue still persists, and it is still of relevance, please feel free to file a new issue as easy to understand and reproducible as possible.

thank you for your help and best regards.
