### ISSUE TITLE
Application Crashes on copying content from Hex Editor and closing

### ISSUE THREAD

**Issue by sadimadh** [notepad-plus-plus/notepad-plus-plus#3733]
Application Version: 7.3 32bit
Environment: Windows 7 32bit OS on Intel core i5 6400U 2.4GHz processor
User Level: Domain User with no Admin privilege (corporate environment), no ability to update version.

### Description of the Issue
Notepad application crashes with windows exception when user is in Hex Editor mode, copies content (Ctrl+C) and closes application

### Steps to Reproduce the Issue
1.  Open notepad editor (default)
2.  Type in some text
3.  View content in Hex Editor (Ctrl+Alt+Shift+H)
4.  copy the hex content (Ctrl+C)
5. Close the application

### Expected Behavior
Application must exit as it exits the normal text mode

### Actual Behavior
Following exceptions are encountered

### Debug Information

Notepad++ v7.3   (32-bit)
Build time : Jan  1 2017 - 20:04:42
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 7
Plugins : ComparePlugin.dll HexEditor.dll mimeTools.dll NppConverter.dll NppExport.dll NppFTP.dll PluginManager.dll SpellChecker.dll XMLTools.dll 

![image](https://user-images.githubusercontent.com/31941576/30407111-339b3862-98ab-11e7-8833-b38f650695ad.png)

![image](https://user-images.githubusercontent.com/31941576/30407121-3dfdebba-98ab-11e7-985e-eb8243b47ba8.png)

**Comment by sasumner** [comment]
This feels like a plugin issue to me, not a core Notepad++ issue--in which case maybe reporting it as an issue here is not the right thing to do?  (I'm asking)

**Comment by dail8859** [comment]
I agree this needs reported to the hex editor project, as there's nothing Notepad++ can do about it since it crashed inside the `notify()` call.
