### ISSUE TITLE
URL highlighting error while space inserted in

### ISSUE THREAD

**Issue by yzumis** [notepad-plus-plus/notepad-plus-plus#3735]
Currently when you write an URL and after that a text before that URL the link includes the URL and the text before the URL

### Steps to Reproduce the Issue

1. Write an URL like https://url
2. Write something before the URL like: beforehttp://url
3. Introduce an space between both like: before http://url

### Expected Behavior

The link should be only hightlighted (_) in the word _http://url_ not in the word _before_

### Actual Behavior

The link is currently highlighted (_) in both words

### Debug Information

Notepad++ v7.5.1   (32-bit)
Build time : Aug 29 2017 - 02:35:41
Path : D:\Programs\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10 (64-bit)
Plugins : mimeTools.dll NppConverter.dll NppExport.dll 

![image](https://user-images.githubusercontent.com/24419355/30433937-1f5258c0-9966-11e7-8a4a-00762f1db797.png)

**Comment by HairyPhil** [comment]
Just to confirm, this is still an issue 2 years later.

**Comment by Uhf7** [comment]
It works correctly in 7.8.7.

Could verify it in 7.8.6., it is gone in 7.8.7.
