### ISSUE TITLE
Add in C++ Code checking to Check C++ code and see if it conforms to ISO Code standards.

### ISSUE THREAD

**Issue by AraHaan** [notepad-plus-plus/notepad-plus-plus#3736]
### Description of the Issue

I would like some sort of C++ code checking for checking things like the sandard length of lines and things for C++ code. I want to see how well my code would be against the code guidlines set in for the C++ standards code people (like checking for lines over 80 characters or other things gond bad).

### Expected Behavior

An option to check C++ code or even extensionless C++ header files I am writing that I might want to eventually go into the C++ standard.

### Actual Behavior

No option to check C++ code or even extensionless C++ header files I am writing that I might want to eventually go into the C++ standard.

### Debug Information

```
Notepad++ v7.5.1   (32-bit)
Build time : Aug 29 2017 - 02:35:41
Path : E:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 7 (64-bit)
Plugins : MenuIcons.dll mimeTools.dll NppConverter.dll nppcrypt.dll NppExec.dll NppExport.dll NppFTP.dll NPPJSONViewer.dll NppSaveAsAdmin.dll PluginManager.dll PyNPP.dll Python Indent.dll PythonScript.dll ReloadButton.dll Translate.dll ZenCoding-Python.dll zoomdisabler.dll 
```

**Comment by sasumner** [comment]
More explanation on closure:  Code checking such as described is outside of the realm of what Notepad++'s core mission is, and thus won't be supported.
