### ISSUE TITLE
enable spell check

### ISSUE THREAD

**Issue by mancoast** [notepad-plus-plus/notepad-plus-plus#3739]
https://github.com/Predelnik/DSpellCheck

disable hesitation!
enable spellcheck. https://github.com/Predelnik/DSpellCheck/issues/92
@donho @Predelnik
move forward, do not fear failure!

**Comment by mancoast** [comment]
any updates regarding the spell check plugin?

**Comment by dail8859** [comment]
The DSpellCheck plugin has been added back in for v7.5.2

**Comment by mancoast** [comment]
Thanks!
