### ISSUE TITLE
7.5.1 No search loop

### ISSUE THREAD

**Issue by robotboy655** [notepad-plus-plus/notepad-plus-plus#3742]
### Description of the Issue
After the 2 button search thing and its revert, you can no longer "search loop", i.e. when you reach the last occurrence of the searched text, it will just say "Can't find the text", instead of going to the first search result.

This is a problem because lets say you have a huge file with functions, you search and find a function in the middle of the file. Now you want to quickly find a function in the "upper" part of the file. The search will say that it can't find the text, so you have to either manually search in the opposite direction, or move your cursor to the first line every time you want to search something in the file without having to probe the up and down direction manually every time.

Also the "Find next" button is now 1 pixel too low compared to the search bar.

### Steps to Reproduce the Issue
```

test

notwork
notwork
notwork
notwork

test

```
Try searching "Test" here 3 times or if you set your cursor after the second "test".

### Expected Behavior
After reaching the last occurrence, it should go to the first one next time you search.

### Actual Behavior
After reaching the last occurrence, the search stops.

**Comment by dail8859** [comment]
It is called the "Wrap around" option and has been there for years.

![capture](https://user-images.githubusercontent.com/3694843/30481645-cdeb1520-99ed-11e7-8184-c67e5b867cf7.PNG)
