### ISSUE TITLE
Feature Request - Jump to the next occurrence of a word

### ISSUE THREAD

**Issue by KlausAstner** [notepad-plus-plus/notepad-plus-plus#3744]
### Description of the Request

Can you add a feature to jump to the next occurrence of a word, just like in programming languages

**Comment by MAPJe71** [comment]
Why not use "Find" (Ctrl+F) or "Incremental Search" (Ctrl+Alt+I)?

**Comment by dail8859** [comment]
Have you tried `Search > Select and Find Next` which is tied to `Ctrl + F3` by default?

**Comment by KlausAstner** [comment]
Because im on a word and will jump to the next, without copying it. It is
very useful on xmlfiles

**Comment by cmeriaux** [comment]
you may try python script. You'll be able to do what you want and assign your script to a shortcut

**Comment by KlausAstner** [comment]
Thank you

**Comment by dail8859** [comment]
@KlausAstner I'm not sure I understand. You want to copy it **and** jump to the next occurrence?

**Comment by KlausAstner** [comment]
No, just jump with a shortcut to the next occurrence oft the word on which
I'm currently

**Comment by dail8859** [comment]
You said above `without copying it` and that command does not copy it to the clipboard.

If instead you were meaning "selecting" it then you can record a macro that de-selects the word after jumping to it.

1. Start recording a macro
2. Press `Ctrl + F3`
3. Press `Left Arrow` (or right if you want the cursor after the word)
4. Stop recording
5. Save macro

**Comment by KlausAstner** [comment]
Thanks for the answer, but I'm not meaning something like this. In Delphi
there is this function

**Comment by dail8859** [comment]
Then I haven't a clue what you are trying to do.

**Comment by dail8859** [comment]
Closing. I recommending trying out `Select and Find Next` or `Find (Volatile) Next`. If neither of these work please better describe the expected behavior.
