### ISSUE TITLE
Please rethink the string "Wrap around" in Search window because is not suggestive

### ISSUE THREAD

**Issue by florinbuda85** [notepad-plus-plus/notepad-plus-plus#3752]
### Description of the Issue
the string "Wrap around" in Search window because is not suggestive - i wanted this functionality for several years and now i'm amazed to find that is was allays there.

### Steps to Reproduce the Issue
Ctrl-F 

### Expected Behavior
Might be "Circular search" or something,

### Actual Behavior
x

### Debug Information
x

**Comment by sasumner** [comment]
I doubt such a change will ever be made.  In software development, there is something called "continuity"--you don't change an established norm that people are used to unless there is a very serious compelling reason to do so, and this doesn't qualify.  Anyway, you as a user can customize the text of the Find dialog box windows to have whatever you want (within space limits)--for example, here is what mine is configured to look like:
![image](https://user-images.githubusercontent.com/30118311/30644141-70fdd5b4-9ddf-11e7-8186-c18da4915801.png)

**Comment by ArkadiuszMichalski** [comment]
@donho @sasumner This bug is needed? If necessary, anyone can slightly modify this name in xml file.

**Comment by sasumner** [comment]
The _Wrap around_ box provides multiple services.
When doing _Find Next_ and the end of the file is reached and the search "wraps around" to the start of file -- that's where the name makes the most sense.
But, the software can't predict if the user is going to press _Find Next_, or, for example _Replace All_.
If the software knew that you were going to replace-all, it could change the text on the checkbox to "Affect Entire document" or something like that.
But I've yet to hear a short-enough label for this checkbox that would cover all circumstances well.
Plus, users can change the text to whatever they want, as mentioned, so... CLOSING!
