### ISSUE TITLE
PDF syntax highlighting and folding

### ISSUE THREAD

**Issue by KOLANICH** [notepad-plus-plus/notepad-plus-plus#3753]

**Comment by MetaChuh** [comment]
No description provided.

**Comment by KOLANICH** [comment]
>No description provided.

The header is self-descriptionary. I am sure that even if there was an (IMHO completely unneeded) description text in this issue, it would have been closed anyway, because it is clear that it is impossible to implement all >1000 of issues for this project and that work is done to close as many issues without an action as possible, essentially doing "issue bankruptcy".
