### ISSUE TITLE
Notepad++ 32bit v7.5.1 doesn't have a Plugin Manager

### ISSUE THREAD

**Issue by ntfshard** [notepad-plus-plus/notepad-plus-plus#3756]
### Description of the Issue
Clean installation && portable version miss a plugin manager dll file

### Steps to Reproduce the Issue
1. download portable || install latest 32
2. check plugins in dir || plugins menu

**Comment by eibanez** [comment]
https://notepad-plus-plus.org/news/notepad-7.5-released.html

> You may notice that Plugin Manager plugin has been removed from the official distribution. The reason is Plugin Manager contains the advertising in its dialog. I hate Ads in applications, and I ensure you that there was no, and there will never be Ads in Notepad++.
> A built-in Plugin Manager is in progress, and I will do my best to ship it with Notepad++ ASAP.
>

**Comment by ntfshard** [comment]
Ok. But it can confuse. At least it could be a dummy plugin for a while.

**Comment by divinity76** [comment]
until a new official plugin manager comes along, note that it can still be installed manually, get it at https://github.com/bruderstein/nppPluginManager/releases

**Comment by Engelito** [comment]
I am having issues installing it manuelly. How do you install it? I tried going to the settings tab and clicking import plugin.

**Comment by divinity76** [comment]
@Engelito just extract the archive in whatever folder notepad++ was installed in (on my system, its `C:\Program Files (x86)\Notepad++`, the DLL's location is `C:\Program Files (x86)\Notepad++\plugins\PluginManager.dll`)

**Comment by borekon** [comment]
The plugin only shows a little sponsor in the main window. IMHO it's not an ad itself

**Comment by DRSDavidSoft** [comment]
#3264
