### ISSUE TITLE
Sort lines on column crashes N++ if range includes lines shorter than selected col

### ISSUE THREAD

**Issue by sasumner** [notepad-plus-plus/notepad-plus-plus#3757]
### Description of the Issue
Notepad++ can sort lines using a selected column as the sorting "key".  However, if some of the lines are short (have less length than the starting column number of the selection), a crash of N++ will result.

### Steps to Reproduce the Issue

1. Create a new document tab and paste the following:

aaa

bbbbbb

cccccccc

abcabcabcabc
Lines that look empty above ARE truly empty (only contain their line-ending characters)

2. Make a column block with the start column in any column greater than col 1, for example:
![image](https://user-images.githubusercontent.com/30118311/30646053-a9ca867a-9de5-11e7-8fcb-9ec113549112.png)

3. Execute Edit (menu) -> Line Operations -> Sort Lines Lexicographically Ascending

### Expected Behavior
I expect Notepad++ not to crash.  :)

### Actual Behavior
Notepad++ crashes (closes on its own) with the following series of popups before the "closing":
![image](https://user-images.githubusercontent.com/30118311/30646157-10b69040-9de6-11e7-8358-8ba2e3365cc2.png)
![image](https://user-images.githubusercontent.com/30118311/30646167-18813e9c-9de6-11e7-87de-2e1fa3a174a9.png)
![image](https://user-images.githubusercontent.com/30118311/30646180-2275c274-9de6-11e7-81f9-c86660a7d690.png)

### Debug Information
Notepad++ v7.5.1   (32-bit)
Build time : Aug 29 2017 - 02:35:41
Path : C:\xxxx\Utilities\npp.bin\_SAS_NPP_Stuff\Releases\npp.7.5.1\npp.7.5.1.bin\notepad++.exe
Admin mode : OFF
Local Conf mode : ON
OS : Windows 7 (64-bit)
Plugins : mimeTools.dll NppConverter.dll NppExport.dll

**Comment by danieltallentire** [comment]
duplicates #3391 so this should fix that issue too.

**Comment by sasumner** [comment]
Closed as perfect duplicate of #3391
