### ISSUE TITLE
Dragging files or folders onto NPP in an extended desktop doesn't work

### ISSUE THREAD

**Issue by rudolf81** [notepad-plus-plus/notepad-plus-plus#3758]
### Description of the Issue

With a second monitor connected in extended desktop mode, if NPP window is on secondary monitor, you cannot drag a file or folder into NPP to open the file, or list the folder in the "Folder as workspace" pane.

If you move the NPP window onto the primary monitor, then this works fine.

The monitor from which you drag the file/folder (Windows Explorer) does not change the observed behavior.

### Steps to Reproduce the Issue

1. Connect second monitor, set windows 10 display settings to "extend"
2. Run NPP v7.5.1, 32bit
3. Drag NPP window onto secondary (extended) monitor
4. Attempt to drag a file into NPP to open it
5. Observe file not opened

### Expected Behavior

Expect NPP to open files and folders from dragging, as per on primary monitor.

### Actual Behavior

While NPP is on secondary monitor in a multi-monitor extended desktop configuration, dragging files and folders into NPP has no effect, and NPP does not open files or folders.

### Debug Information

Notepad++ v7.5.1   (32-bit)
Build time : Aug 29 2017 - 02:35:41
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10 (64-bit)
Plugins : AnalysePlugin.dll mimeTools.dll NppConverter.dll NppExport.dll NPPJSONViewer-win32.dll PluginManager.dll XMLTools.dll

**Comment by TinTans** [comment]
I've just come across this (in Windows 10).  I think it may be a scaling issue.

My exact setup is as follows:
Monitor1 no scaling
Monitor2 4k with scaling
Monitor3 no scaling (main)
Monitor4 no scaling

Dragging files into notepad++ works on all monitors except for Monitor2 which has scaling.

Now the interesting part is that if I maximise notepad++ (or even just make the window sufficiently large) on Monitor2, dragging files into notepad++ DOES work so it seems to me that notepad++ thinks the window is somewhere else.

This means when you try to drag and drop into the window, it thinks you've missed the window even when you haven't.  When you make the window larger, where the window is and where notepad++ thinks the window have a better chance of overlapping, thereby making it more likely for drag and drop to work

**Comment by MetaChuh** [comment]
i can not reproduce a drag and drop issue on notepad++ 7.6.6 on windows 10 build 1809 using mixed scaling factors any more.

please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins if you update from version 7.5.9 or below.

if drag and drop still misses the scaled notepad++ window, please right click on your notepad++ icon and select `properties > compatibility > change high dpi settings`, activate `override high dpi scaling behavior` and set `scaling performed by:` to `system (enhanced)`, as seen at the screenshot below.

![Imgur](https://i.imgur.com/qVQ4Bg8.png)

thank you for your help and best regards.

-----
```
general notes:

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
(no extra account is needed, just use your github account to sign in)
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)

**Comment by TinTans** [comment]
The above sort of worked for me, interestingly I had to set it to **scaling performed by: application** and then it worked just fine!

Thank you!
