### ISSUE TITLE
CRITICAL regression: gpup.exe requires UAC for plugins, but should not

### ISSUE THREAD

**Issue by yamlfd** [notepad-plus-plus/notepad-plus-plus#376]
If I install a plugin per user the UAC dialog comes up and the plugin cannot installed to the users AppData directory. My users are complaining a lot that they cannot install and update existing plugins.

Can you remove the UAC, please?

NPP Version: Je suis Charlie Editon

**Comment by yamlfd** [comment]
I'm wondering that there are regression releases and nothing happens to this regression here, too.

**Comment by GitMensch** [comment]
The UAC in gpup is likely a result of a manifest (=always run be Windows), and not by an elevating command. And yes: it would be actual nice to only request administrative privileges if the install is done to the main program directory.

**Comment by GitMensch** [comment]
This issue is only indirect related to NPP any more and should be closed in favour of https://github.com/gup4win/wingup/issues/18

**Comment by donho** [comment]
gpup.exe is not part of Notepad++ project, but provided by a plugin of Notepad++ named "Plugin Manager".

**Comment by yamlfd** [comment]
How can we reach out to the maintainer?

**Comment by donho** [comment]
Search "Plugin Manager for Notepad++" in github

**Comment by chcg** [comment]
The correct place is https://github.com/bruderstein/nppPluginManager/issues/, maybe related to https://github.com/bruderstein/nppPluginManager/issues/35
