### ISSUE TITLE
Cancelling autocomplete with escape key inserts "ESC" character ()

### ISSUE THREAD

**Issue by Fabian42** [notepad-plus-plus/notepad-plus-plus#3760]
### Description of the Issue
Closing the autocomplete list (tested with word autocomplete) using the escape key inserts the character '', shown as a color inverted "ESC". This character looks like a left arrow in this text box.
### Steps to Reproduce the Issue
1. Set the word autocomplete (59th entry) key to anything in Settings->Shortcut Mapper… (tested with Ctrl+Space, Alt+Space, Ctrl+D)
2. Enter "abc abd a" into a file and press the autocomplete key.
3. Press escape to close the list.
### Expected Behavior
List closes
### Actual Behavior
List closes and character '' gets inserted.
### Debug Information
Notepad++ v7.3.3   (32-bit)
Build time : Mar  8 2017 - 03:37:37
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : ON
Local Conf mode : OFF
OS : Windows 7 (64-bit)
Plugins : ComparePlugin.dll CustomizeToolbar.dll NppSaveAsAdmin.dll PluginManager.dll RunMe.dll

**Comment by sasumner** [comment]
Not reproducible with portable v7.3.3 and portable v7.5.1, both 32 bit.

**Comment by MetaChuh** [comment]
please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins if you update from version 7.5.9 or below.

thank you for your help and best regards.

**Comment by Fabian42** [comment]
I forgot to mention in the original report that I was using Linux and Wine, Wine just made Notepad++ believe that I was on Windows 7.

For autocomplete this is fixed now, but it still happens when pressing Alt to go to the menu and then cancelling that with Esc. This does not happen on a real Window 7 system. Is this report still valid then?

**Comment by MetaChuh** [comment]
@Fabian42 

this does not happen on ubuntu and notepad++ 7.6.6 installed from the ubuntu software center.
pressing <kbd>alt</kbd> and exiting with <kbd>esc</kbd>, regardless of opening a menu, or just  highlighting and escaping one, does not insert any characters at the editor field.

this is not a valid bug report, as it works on windows, as well as on newer and clean wine setups.

please try the notepad++ 7.6.6 package from the ubuntu software center, or check and update your wine installation.

many thanks and best regards.

**Comment by Fabian42** [comment]
You're right, both work fine on Ubuntu (just made a VM to try that). But on my Debian laptop it enters the special character whenever I close the menu with Esc.

**Comment by MetaChuh** [comment]
intriguing, this does not happen on e.g. wine 2.1.2 on mac or ubuntu, but we do not have debian machines to check the debian differences, regarding desktop environment keyboard handling.

one thing you can try, is to sudo snap install notepad-plus-plus on your debian laptop (or on a fresh debian vm beforehand)

best regards.

**Comment by MetaChuh** [comment]
-----

```
general notes:

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
(no extra account is needed, just use your github account to sign in)
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)

**Comment by Fabian42** [comment]
On my regular Debian system that command hangs at »`Automatically connect eligible plugs and slots of snap "notepad-plus-plus"`«. In the VM I get »`error: cannot perform the following tasks:
- Mount snap "notepad-plus-plus" (202) (cannot find required base "core18")`«
