### ISSUE TITLE
"Open in Default Viewer" executes files from np++ folder

### ISSUE THREAD

**Issue by Hiro5** [notepad-plus-plus/notepad-plus-plus#3761]
### Description of the Issue
When I try to execute a bat/cmd file with the option "Open in Default Viewer"
npp executes the file from the Notepad++ folder.

I think it should be executed from the folder of the file, not from the np++'s one.
...like when you double-click a file.

It's specially dangerous if you are working with the files (moving... deleting...) thinking that you are in the right folder, but instead, you are in the np++ folder.

### Steps to Reproduce the Issue
1. As an example, try a test.bat file with these 2 lines:
```
@cd
@pause
```
2. And use the "Open in Default Viewer"

### Expected Behavior
It shows the np++ folder, but it should show the file's folder.

Tested with npp++ v7.5.1, Windows7

**Comment by Cyrillev91** [comment]
Hi,

we could disable the option for some extension
or we could ask for confirmation before opening files with a particular extension

extension list: .bat, .cmd, .py, .exe

**Comment by srhtrip** [comment]
how can I get the source code for the module?

**Comment by MetaChuh** [comment]
please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins if you update from version 7.5.9 or below.
if your issue still persists, and it is still of relevance, please feel free to file a new issue as easy to understand and reproducible as possible.

thank you for your help and best regards.
