### ISSUE TITLE
Tab size for Python should default to 8 

### ISSUE THREAD

**Issue by nlc-gene** [notepad-plus-plus/notepad-plus-plus#3768]
### Description of the Issue
By default the tab size is 4 chars.
The python 2 interpreter itself expands tabs to 8 chars, not 4.
The Linux terminal ('cat' a python source file) and Windows (type a python source file) also expand tabs to 8 spaces.
It would be useful if Notepad++ had a separate indent setting apart from the tab setting, as many editor do. That way tabs can be 8 to match the python interpreter, and we can indent to 4 spaces which is a good amount. And expected when coding python 3.

### Steps to Reproduce the Issue

Open a .py python source file, the tabs are expanded to 4, not 8 spaces.

### Expected Behavior
Tab should be 8 spaces.

### Actual Behavior
Tabs are 4 spaces.

### Debug Information
Notepad++ v7.3.3   (64-bit)
Build time : Mar  8 2017 - 03:39:58
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 8.1 (64-bit)
Plugins : mimeTools.dll NppConverter.dll

**Comment by dail8859** [comment]
Just FYI Python's [official style guide](https://www.python.org/dev/peps/pep-0008/#indentation) says to use 4 spaces.

You can also set tabs to be 8 spaces for Python by using `Settings > Preferences > Language`

**Comment by nlc-gene** [comment]
The python says one should indent to 4 spaces, but does not state how big a tab is. The *python interpret itself expands tab to 8 spaces*. So it I edit some python source code with tabs set to 4 spaces the python interpreter will interpret the code is a different way than is shown in the editor.

**Comment by azlux** [comment]
The python idle have also a default of 4 space.
And like @dail8859 said : the PEP8 is the best to do ("Use 4 spaces per indentation level.")

**Comment by nlc-gene** [comment]
[tab-test.zip](https://github.com/notepad-plus-plus/notepad-plus-plus/files/1331267/tab-test.zip)
I've just used Python and Idle v2.7.13  and it make tabs 8 spacs in the Shell window as the Python 2 interpreter does. In the Editor windows a tab inserts 4 spacs, not a tab. Idle editor interprets tabs as 8 spaces, see the attached file. (i had to .zip it as github won't allow one ot uploda .py files.

**Comment by TeamSpen210** [comment]
In Python 3, mixing tabs and spaces is an error, and so there isn't any equivalent between the two. The 8 spaces value is really an internal thing (and not accurate), likely to allow storing the number of tabs and spaces on a line in one variable.

See the [docs](https://docs.python.org/3/reference/lexical_analysis.html#indentation), for official word on the matter.

**Comment by KOLANICH** [comment]
I insist on `wontfix`ing this.

**Comment by MetaChuh** [comment]
@nlc-gene 

the notepad++ default tab size for python will not be changed from 4 to 8 spaces.

many thanks and best regards.
