### ISSUE TITLE
XML plugin not installed to user plugin folder

### ISSUE THREAD

**Issue by yamlfd** [notepad-plus-plus/notepad-plus-plus#377]
If a user installs the XML Plugin he ends with a corrupted install. Please make sure the XML Plugin save the xml lib not to notepadd++ program files folder. It need to be added to the users plugin folder on appdata\notepad++

**Comment by milipili** [comment]
Unless I miss something, which is highly possible here, if the problem is related to XML Plugin, it should be reported to the author of the plugin.

**Comment by yamlfd** [comment]
Sure, but where?

**Comment by Tmp341** [comment]
Open it up with npp and see if there is a contact info. If not, try searching it's name online.

**Comment by milipili** [comment]
maybe this one : http://irvingduran.com/2011/08/installing-xml-plugin-in-notepad/

**Comment by yamlfd** [comment]
I'm wondering that npp maintainers are not aware who provides the plugins they distribute

**Comment by milipili** [comment]
Ask @donho he should know, but he is currently in vacations :)

**Comment by yamlfd** [comment]
Looks like a new release has been published. This means the xml tools plugin is maintained. But how to contact him?

**Comment by yamlfd** [comment]
Fault

**Comment by dail8859** [comment]
Try [this](https://notepad-plus-plus.org/community/topic/125/plugin-update-xmltools-2-4-7) forum. I'm assuming it is the author that started this post.
