### ISSUE TITLE
Notepad++ hangs and cannot be started when javascript is set to use tabs

### ISSUE THREAD

**Issue by joeyhub** [notepad-plus-plus/notepad-plus-plus#3770]
Change javascript.js to use tabs instead of spaces (64bit). Have a JS file open and in view.

**Comment by RoboBurned** [comment]
I have the same issue with the following values for javascript js
Use default values = false
Tab size = 2
Replace by space = true

**Comment by donho** [comment]
@joeyhub @RoboBurned 
I cannot reproduce it at all.
Could you provide the instruction complete to reproduce it please?
