### ISSUE TITLE
When using "Folder as workspace", all top-level folders are expanded upon starting the program. I wish they would collapse instead.

### ISSUE THREAD

**Issue by SacredDuckwhale** [notepad-plus-plus/notepad-plus-plus#3773]
### Description of the Issue

Title; I'd like for them to be minimized (optionally, if need be, but certainly by default) because it is impractical to have it this way and not the other way around. As a user, I want to work on one project at a time (obviously), so the others are of no interest to me and I have to manually click each folder to hide the tree view.

There's an ugly workaround to at least reduce the visual clutter: Since only the top-level children are being expanded, I could create a new folder in the project root directory, so that all subfolders and files are hidden and only ROOT and ROOT\container are expanded. That really isn't a clean solution, though, and it's entirely unnecessary.

### Steps to Reproduce the Issue

1. Enable "Folder as workspace"
2. Add some projects (usually more than one, although the issue is apparent with any number of projects being added)
3. Restart the program ("FAW" feature must still be enabled)

### Expected Behavior

The most intuitive thing is to have all folders being collapsed - this is actually the default behaviour for the "old" workspace feature, too.

Ideally, I would actually like the current project(s) to be opened, where "current project" means "the workspace which contains the currently opened file/s" (can be several if my session spans across projects) so that I can resume work right away. If the file is not part of any project, or there is no file being opened (empty editor window/New file) then having all projects collapsed seems like the sensible thing to do.

### Actual Behavior

As described, all projects will be opened and expand to display anything placed directly in the root directory, with all files included on that level. All other subfolders are (thankfully) collapsed, but not the top-level ones.

### Debug Information

>Notepad++ v7.5.1   (32-bit)
Build time : Aug 29 2017 - 02:35:41
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : ON
Local Conf mode : OFF
OS : Windows 7 (64-bit)
Plugins : MarkdownViewerPlusPlus.dll mimeTools.dll NppConverter.dll NppExport.dll PluginManager.dll QuickText.UNI.dll 

### Screenshots and Notes

I've added some screenshots of the "Folders as workspace" pane to clarify the issue.

Actual behaviour: [Screenshot](https://imgur.com/IJV6gCF)
*Note: This is the issue I am describing. It looks like this no matter what file is being opened, or even if a session is being resumed.*

Expected behaviour: [Screenshot](https://imgur.com/veZxG11)
*Note: This should be the default behaviour, particularly if no project files have been opened.*

Expected behaviour (alternative): [Screenshot](https://imgur.com/8QY8zsZ)
*Note: In the example I opened up the file ".pkgmeta" from said project **outside of NPP** so it would start with the respective project expanded.
The highlighting is just me helping you spot the file I opened manually. It is not helpful to do this automatically, especially if many files are being opened.*

**Comment by rsawoseyin** [comment]
I also find this default behaviour a nuisance. I wonder why it has not been addressed in recent updates. It is simply illogical to open up all folders in the workspace at startup.

**Comment by dvdvideo1234** [comment]
@rsawoseyin 
I find this rather strange too. I have more than one project in my work-space and they are all expanded on startup. It must be for the user to define whenever he wants them to be closed or not.

![image](https://user-images.githubusercontent.com/9112662/41521345-6d879b06-72da-11e8-9323-5c1d0935dba4.png)

I have to manually close each one just to work on the one I want.

**Comment by bubbajdf** [comment]
Another option (in my opinion), would be when adding the folders initially, allow the user to pick the default state (ie collapsed or expanded).

**Comment by sulliwk06** [comment]
I use many folders this way and it's terribly annoying to have to collapse each one.  I would settle for a "collapse all" button.  For now I make do by using the down and left arrow keys to quickly collapse them all.

**Comment by chriva** [comment]
Add me to the list of people that find this behavior less than ideal :)

**Comment by CrystalFyre** [comment]
+1 to adding this feature, please.

**Comment by donho** [comment]
3 new features added in Folder as workSpace:
Select & show the current editing file: bc2b5ac2ce47ed8821525c534d16c19b5f239f1d
Fold all: e0d995c1a6a045c8effb9f412325ba14f0d329d1
Expand all: 703a49b32304e9ab09931493db9e1ca972e896f3

They will come out with 7.8.3 which will be available soon.
