### ISSUE TITLE
Add the possibility to change some parameters regarding find/replace from within the preferences GUI

### ISSUE THREAD

**Issue by xates** [notepad-plus-plus/notepad-plus-plus#3774]
### Description of the Issue
There are four parameters in the config.xml file that control the find/replace history limits: `nbMaxFindHistoryPath`, `nbMaxFindHistoryFilter`, `nbMaxFindHistoryFind`, `nbMaxFindHistoryReplace`.

These parameters are only configurable by manually editing the config file. Please allow users to manage these settings from within the program in the preferences or find/replace GUI instead of having them to manually discover and edit them in the config file.

### Steps to Reproduce the Issue
Be in need to disable find/replace history or to have more elements in it.

### Expected Behavior
Be able to change the settings from the preferences or the find/replace window.

### Actual Behavior
Think that it is not possible to customize this, then eventually find out that you can actually edit these parameters, but only by editing a config file buried in some user directory that no one knows about.

### Debug Information
No need.

**Comment by hillcf** [comment]
Needed this - and had to search here to find they was a complex way, if you were a non-IT developer, to fix it. This is really needed, and is simple to implement.

**Comment by wonkawilly** [comment]
Sorry for the OT, I'm also really sorry if I'm bothering you all, but maybe the participants to this thread would want to give their opinion about this new and rich proposal about the improvement of the Find and Replace dialog at this link: #9627. Which will be a great improvement and perhaps even a real game changer for all of us that use N++ for more advanced uses than just editing the shopping list.
Please partecipate and spread the word asking others to partecipate as well. More opinions are welcome. Thank you all.

**Comment by pryrt** [comment]
I wonder if originally, the developers didn't think there would be much reason to change this, and didn't want to clutter up the limited Find dialog or Preferences dialog.  But now that the Preferences dialog has the Searching tab (as of 84ea510 in v7.9.0), I would think there would be room to add these settings to the GUI.  Since he's done a lot of the searching-based improvements recently, I wonder if @sasmner has an opinion on this setting getting added to the GUI.

**Comment by sasumner** [comment]
@pryrt Again perhaps it goes back to original intent of these maximums.  Sure, we could add it to the _Preferences_, and I would add it at a constant 30 and have just one GUI setting control all, for simplicity.  But, what does @donho want, as he has been around longer and knows original intent of the limits...

**Comment by donho** [comment]
https://github.com/notepad-plus-plus/notepad-plus-plus/issues/4511#issuecomment-854985220
