### ISSUE TITLE
Panes width not equal

### ISSUE THREAD

**Issue by pnedev** [notepad-plus-plus/notepad-plus-plus#3776]
### Description of the Issue

When the two Scintilla views are opened side by side they do not have equal widths.

### Steps to Reproduce the Issue

1. Turn on the Wrap mode.
2. Clone the default 'New 1' empty file to other view (views must be in side by side mode, not top-bottom).
3. Start typing in one of the views until the line wraps. You'll notice that the Sub view will wrap earlier (due to the difference in the panes width).

### Expected Behavior

When both panes are initially opened in side by side mode they should have equal widths.

### Actual Behavior

They don't have equal widths in that case.

### Debug Information

I suspect that the separator (border) width between the views is not taken into account when deciding the initial panes widths. For example if the total editor view width is 2x the border is positioned at 2x / 2 = position x but it (the border) has size b so the Sub view has resulting size x - b while Main view is with size x.

**Comment by pnedev** [comment]
Strange, both views appear to have the same zoom level when I'm testing ...

**Comment by jmbockhorst** [comment]
Alright, after some more testing, it seems that you are correct. I will look into it.
