### ISSUE TITLE
Wrong bit version when updating

### ISSUE THREAD

**Issue by Igor-Yavych** [notepad-plus-plus/notepad-plus-plus#3779]
For some reason, x64 version keeps downloading x32 version when updating.
Version 7.4.2 and 7.5
Win 7x64

**Comment by MetaChuh** [comment]
please update your notepad++ to the latest 64 bit version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins if you update from version 7.5.9 or below.
if your issue still persists, and it is still of relevance, please feel free to file a new issue as easy to understand and reproducible as possible.

thank you for your help and best regards.
