### ISSUE TITLE
&aacute

### ISSUE THREAD

**Issue by matahombres** [notepad-plus-plus/notepad-plus-plus#3781]
### Description of the Issue
In html if you add html code of special caracter and you don't separate the closing tag the text uncolored closing tag

### Steps to Reproduce the Issue
1. Create a new file html
2. In one tag add &aacute or &ntile... one html code in special caracter
3. Do not separate the closing tag

### Expected Behavior
Color no remove

### Actual Behavior
The html code not afect it's. But... the color and the system for a identify tags. 

### Debug Information
Example Images:
With space in the closing tag and text: http://es.tinypic.com/view.php?pic=34fl945&s=9#.WczjYlu0OM8
Error remove color: http://es.tinypic.com/view.php?pic=28mp7b&s=9#.Wczjb1u0OM8

**Comment by MetaChuh** [comment]
please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins if you update from version 7.5.9 or below.
if your issue still persists, and it is still of relevance, please feel free to file a new issue as easy to understand and reproducible as possible.

thank you for your help and best regards.
