### ISSUE TITLE
How to enable tab indent space align?

### ISSUE THREAD

**Issue by vitaliylag** [notepad-plus-plus/notepad-plus-plus#3784]
I read all settings but didn't found how to enable tab indent space align.

What I found is "Tab size" and "Replace by space". Why should I replace tab by space. It makes no sense.

If I uncheck "Replace by space" then all spaces are replaced by tabs! It doesn't make any sense too!

I don't want my tabs to be replaced by spaces and spaces to be replaced by tabs. How can I do it?

**Comment by sasumner** [comment]
This is not an issue (yet).  This is a question.  Perhaps it is better to ask it here:  https://notepad-plus-plus.org/community/

**Comment by vitaliylag** [comment]
Well, if I can't, can this feature be added?

Now this is issue :) (I guess)

**Comment by sasumner** [comment]
Well, I was hoping to get some discussion going about it where a lot more people will see it (on that website I linked), and maybe someone will understand what you are meaning (I don't).  If it is decided to be an issue, it can always come back here with a refined explanation.

**Comment by vitaliylag** [comment]
Sorry, I don't understand what you mean.

I opened the forum you said but there's no good category I can post this issue.

> what you are meaning (I don't).

I didn't understand what you didn't understand (>_<)
Didn't you understand what is "TAB INDENT SPACE ALIGN"? If you didn't you can see it in google.com.
Or didn't you understand why I didn't create a topic on that forum? (sorry for my English)

> If it is decided to be an issue, it can always come back here with a refined explanation.

I guess there is full explanation in the first post. Is it unclear? How can I make it more clear?

**Comment by sasumner** [comment]
Okay, I think I understand.  You want a capability to convert your text so that only tab characters exist before the first non-whitespace character on each line, with any tab characters existing after the first non-whitespace character to be converted to spaces.  That could be a menu item--to run that conversion on existing text.  Or do you want this capability dynamically, like this is a "setting" for the current file, and as you type the above rules are enforced?  Or maybe you'd like to see  both...

**Comment by vitaliylag** [comment]
>  You want a capability to convert your text

No. I want this:

When I press tab key, Notepad++ should determinate if current line contains at least one non-tab character (even space!), but only on the left side from current cursor position.
- If there is at least one non-tab character, 4 spaces should be inserted (or less, if CUR_COLON % 4 > 0).
- If there is only tab characters or no any characters, 1 tab character should be inserted.

<br><b>Examples:</b>
- AABBCC❚DDEE — 2 spaces should be inserted after pressing TAB
- AABBCCD❚DEE — 1 space should be inserted after pressing TAB
- AABBCCDD❚EE — 4 spaces should be inserted after pressing TAB
- ❚AABBCCDDEE — 1 TAB should be inserted after pressing TAB
- _❚AABBCCDD — 3 spaces should be inserted after pressing TAB (because string already contains one SPACE on the left side from cursor, ans space is non-tab character)
- ×××❚AABBCC — 1 TAB should be inserted after pressing TAB (because there is only tabs on the left side from cursor)

<br><b>Example in the real code:</b>
```
if (true) {
×const ab = 5;   //some comment
×             ❚//is continied on the next line
}
```
In this example two spaces should be inserted because line contains spaces on the left side from cursor. Yeah, that line will contain 1 tab and 16 spaces after pressing TAB. That means every line may contain spaces and tabs at the same time. That's because I use tabs for indent and spaces for align. Indent and align are NOT SAME THINGS. YOU SHOUDN'T USE TABS FOR ALIGNMENT OR SPACES FOR INDENT. YOU SHOULD USE TABS FOR INDENT AND SPACES FOR ALIGNMENT.


<br><b>What I want</b>
I don't want to functions to replaces character; it can be automatically done by other tools or plugins. I want the right working after pressing TAB key.

PS. When I press Shift+Tab Notepad++ should delete 1 tab from the beginning of a line. If line contains spaces at the beginning, they should not be deleted because spaces are used for the alignment not indent.

Optionally I would add combination to replace all the beginning spaces with tabs in the selected text. For example, after pressing Ctrl+T the windows opened where I should type how much spaces equal one tab (4 by default). This will be convenient feature to make stranger's code indented right way. Of course, this is dangerous feature because Notepad++ cannot be sure some spaces are used for indent not alignment. Example:
```
if (true) {
    const a = 5,
          b = 6;
}
```

After auto-conventing this will be converted to
```
if (true) {
×const a = 5,
×× b = 6;
}
```

It's wrong conversion because if someone uses spaces instead of tabs Notepad++ cannot know it. Of course if someone always use spaces instead of tabs it's wrong too. People can have different tab size if alignment will be broken. Nobody should use tabs instead of spaces.

<br><b>Big problem</b>
Very big problem is Notepad++ always inserts tab or always inserts spaces. It's VERY WRONG.

**Comment by vitaliylag** [comment]
I guess many people don't know what is tab indent space align style, what different between alignment and indentation and why nobody should use spaces instead of tabs and tabs instead of spaces.

I though everybody know it. Do you think I should recreate this issue? This is very important feature Notepad++ doesn't have.

**Comment by MAPJe71** [comment]
> I would say it is basic feature people can't program without.

FYI people have been programming for decades without the feature.

**Comment by vitaliylag** [comment]
Well, you are right and what I said is not true :) Of course everybody can program even without TAB key on the keyboard :) That's what I'm doing right now :) It's not convenient.

**Comment by dail8859** [comment]
Duplicate of #3251

**Comment by vitaliylag** [comment]
> one of those features that causes more problems/confusion when not implemented correctly

I don't understand you. Implementing is very easy, Notepad++ should just insert tabs in the beginning of a string and spaces if at least one non-tab character was typed (including space).

**Comment by sasumner** [comment]
Why did you create this current issue when you are the author of #3251 ?  Ugh...adds to the clutter in this issues list...

**Comment by vitaliylag** [comment]
Because nobody respond me a long time. I wouldn't duplicate any issue except very and very critical bugs, vulnerability and features.

**Comment by vitaliylag** [comment]
Actually there is 3 styles of code:
1. All with tabs — very bad style and should not be used by anyone.
2. All with spaces — very bad style and should not be used by anyone.
3. Indent with tabs and align with spaces — very good style without any defects.

And... what do you think? Notepad++ supports first two styles and does not support third style.

Great)

**Comment by sasumner** [comment]
Perhaps you should consider another editor that meets your need better.  Regardless, I think you have defined your desire well and it will be taken under consideration for implementation.  If you have more comments after a period of time elapses, please add them to THIS issue and don't create another new one.

**Comment by vitaliylag** [comment]
up

**Comment by VsevolodGolovanov** [comment]
Very strange that this is missing from an editor that's aimed at programmers.

Any self-respecting open source project has code style guidelines, including indentation style. NPP makes following them difficult.

**Comment by vitaliylag** [comment]
up

**Comment by Naheulf** [comment]
up ?

**Comment by Naheulf** [comment]
down ?

**Comment by donho** [comment]
https://github.com/notepad-plus-plus/notepad-plus-plus/pull/12333#issuecomment-1430684990
