### ISSUE TITLE
Line sorting does not work correctly with Windows newlines

### ISSUE THREAD

**Issue by scootergrisen** [notepad-plus-plus/notepad-plus-plus#3788]
It seems if i sort lines when the text is using Windows newlines (\r\n) they are not sorted correctly.
But converting to UNIX newlines (\n) and then sorting again it sort correctly.

**Comment by sasumner** [comment]
Can you provide an example?

**Comment by scootergrisen** [comment]
If i enable show all characters i can see the newlines.
Some lines end with CFLF and others end with LF.
It seem the LF is inserted at the beginning of the highlighted text copied from the result for the string i have searched for.

So if i search in all files for "abc" the search result might have:
`some text some text some text some text abc some text some text`

"abc" is highlighted in the search result so on copy paste it (sometimes) becomes:
```
some text some text some text some [LF]
text abc some text some text
```

When the tab is set to Windows newlines (CR LF) or Mac (CR) the sorting command do not sort correct as the lines are seen on the screen because they dont sort lines ending with LF.
But when the tab is set to Linux [LF] it sorts correctly as seen on screen because each line ends with LF.

So i guess the question is:
Why does LF get inserted before highlighted search text when copied from search reasult.
And why does it only happen some times.

Try sorting this file when newlines is set to Windows of Mac.
Enable show all characters so you can see the newlines.
[notepadsortnewlineproblem.txt](https://github.com/notepad-plus-plus/notepad-plus-plus/files/1444281/notepadsortnewlineproblem.txt)

**Comment by sasumner** [comment]
So when considering the topic issue, if I try sorting your sample file with Notepad++, it sorts correctly as far as I can tell.  The mixed line endings remain and don't seem to cause any sorting order problems, for me.

As to how you get mixed line endings in the first place, that is unclear to me from your description.

**Comment by scootergrisen** [comment]
The LF's comes from the search result highlights.
Sometimes.
I made a little mistake in the above where is says some text [LF] abc but i have fixed it now.
See the [LF] right before "abc" on the next line. That comes from the search results when i have searched for "abc" in all files (Ctrl+Shift+F).

**Comment by sasumner** [comment]
I did some testing with copying out of the Find result panel and pasting into an editor window.  I didn't see any inconsistent line-ending behavior with doing this--the pasted text always had line-endings that followed whatever line-ending type was set for the file.  Thus, although I'm not saying I don't think it is happening the way you say it is for you, I can't duplicate your behavior.

**Comment by scootergrisen** [comment]
It only happens sometimes it seems when copying from the result list.
But you can try the other thing i described using the file i uploaded.

**Comment by sasumner** [comment]
Okay, the sort after undo as discussed above does not seem to do a valid sort.  This is fairly obscure.  Mixing line ending types in a single document is ill-advised at best.  Normally you shouldn't do this on your own and Notepad++/Scintilla in most cases will convert data pasted with improper line endings to line-endings of the current configuration.  There are some cases where you can get Linux line-endings into a Windows document (example: copying from a Pythonscript console window, and then pasting into an editor tab via the Clipboard History panel), but really it is pretty rare.  Maybe we should discuss further how you are getting inconsistent line-endings in your doc--try to pin that down?

**Comment by scootergrisen** [comment]
I see two problems.

1: Sometimes [LF] from search result highlights gets copy pasted into tab even though there are no reason why a [LF] should be there at the beginning of each highlight when copy pasting.

2: Notepad++ shows [LF] and [CR] as newlines in the tab even though the newline setting is set to use Windows style [CRLF]. So if the tab is set to use Windows newlines then why does Notepad++ show both [LF] and [CR] as newlines? It should not.

**Comment by sasumner** [comment]
for 1:  I think you have to try to quantify the "Sometimes" part to something more specific before someone can help or even think about trying to fix something in the source code.

for 2: This can happen and I think it is valid/okay.  N++ isn't going to stop you if you really want to have mixed line-ending types in your document.  I know this is not what YOU want, though.

I still think nailing down the original source of the non-Windows line-endings getting in is key; my 2c.

**Comment by demongolem** [comment]
I find this a problem sometimes with cut/paste from documents in the wild as well.  Even when it appeared that the line endings were consistent (for example I do find/replace to try to make things consistent), still there was a problem.  When I then choose Edit/EOL Conversion and say choose Unix line endings, sort suddenly works as expected.  There appears to be something beyond what is visible which mucks things up.  I am on v 7.6 64 bit on WIndows 10.

**Comment by MetaChuh** [comment]
@scootergrisen 

i can not reproduce this on notepad++ 7.6.6. with the given information.

thank you for your help and best regards.
