### ISSUE TITLE
Feature request: Highlight doubleclicked line in "Find results"

### ISSUE THREAD

**Issue by cajuncool** [notepad-plus-plus/notepad-plus-plus#3794]
### Description of the Issue
After using "Find All in Current Document" I can doubleclick a result line in the "Find results" window to jump to this line in the document window, but the doubleclicked line in "Find results" is not highlighted/marked. Even if I click again to highlight it, the highlighting is no longer visible when I change to the document window and "Find result" is no longer in focus. This is very annoying when you try to go from one line to the other (which one did I doubleclick before?).

### Steps to Reproduce the Issue
1. Use "Find All in Current Document"
2. Doubleclick on a result line in "Find result"
3. Change to the document window

### Expected Behavior
The doubleclicked line in "Find result" should be and remain highlighted.

### Actual Behavior
No permamnent highlighting in "Find result", so you cannot see which line you doubleclicked.

**Comment by sasumner** [comment]
Workaround:  From an active editor tab window, if you use the F7 (the default) keystroke for Search (menu) -> Search Results Window, it will take you back to the Find Result panel and place the highlight where it last was.  From there it is easy to go to the next/previous one.  Even better, don't go to the Find Result panel at all--use F4 or Shift+F4 to go to the next or previous search result without leaving the active editor tab.  See Search (menu) -> Next Search Result and Search (menu) -> Previous Search Result

**Comment by cajuncool** [comment]
Indeed, using F4 and F7 almost covers all my needs. Thank you very much, sasummer!
Still, it would be nice to always see the doubleclicked line highlighted, not only after F7.

**Comment by sasumner** [comment]
Agreed.  However I thought I'd present the "workaround" so that you wouldn't suffer (in case you [or other readers] didn't know about it...) while you are waiting for your perfectly reasonable feature request to be implemented.

**Comment by alankilborn** [comment]
In recent versions of N++ (e.g. 8.4.4 where I tested it) the default "highlighting" (really the background selection color) of the double-clicked line in _Search results_ is still rather light (in default theme mode).  However, this can easily be changed in "Preferences" > "Style Configurator" here:

![image](https://user-images.githubusercontent.com/77065706/182642921-1b43a5c5-6643-4974-8acf-6b1698f6fca6.png)

Suggest CLOSING this issue.
