### ISSUE TITLE
Notepad-plus-plus forces you to save newly created tabs (ctrl+N) upon exit 

### ISSUE THREAD

**Issue by JaspalMarway** [notepad-plus-plus/notepad-plus-plus#3795]
### Description of the Issue
One of the great features of notepad++ was that you could create new tabs (using Ctrl +N) and not have to save them when exiting notepad++

When you launched notepad++ all the tabs and the associated data would still be there.

With the latest release, when you exit notepad++  you are forced to save data to disk for each of the tabs that you created using Ctrl + N

As a developer I greatly valued the feature that allowed me to return to tabs that I had previously created without having to save them to disk.

Could you please consider reintroducing this great feature. 

### Expected Behaviour
When you exit notepad++ you are not forced to save newly created tabs.
When you relaunch notepad++ all the tabs and associated data should still be there.

### Actual Behaviour
When you exit notepad++  you are forced to save data to disk for each of the tabs that you created.

### Debug Information
Not a bug.
Feature that seems to have been depreciated.

**Comment by sasumner** [comment]
Not a deprecated feature.  Check Settings -> Preferences -> Backup.  Tick "Enable session snapshot and periodic backup".  With that ticked Notepad++ will not prompt you to save unsaved tabs, and will still have them when you run Notepad++ the next time.

**Comment by GuyPaddock** [comment]
It appears that this setting gets turned off between updates, then. Twice now, after updating Notepad++, I not only lost any unsaved tabs from my prior session but also was required to save new ones before exiting.

**Comment by ashleedawg** [comment]
Is this occurring again or is it just my system?

**Comment by samalcorn** [comment]
It's happening to me with that box checked.

**Comment by VoltairesPuppet** [comment]
@samalcorn You also need to have single session enabled.   Annoyingly "New #" files are not saved and referenced from within explicitly named sessions on the command line.   I am thinking of raising this as a separate issue.   

Ideally this should be provided as an option to change when saving unsaved New files.

**Comment by MetaChuh** [comment]
please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins if you update from version 7.5.9 or below.
if your issue still persists, and it is still of relevance, please feel free to file a new issue as easy to understand and reproducible as possible.

thank you for your help and best regards.
