### ISSUE TITLE
Wrong theme in portable version

### ISSUE THREAD

**Issue by qx87** [notepad-plus-plus/notepad-plus-plus#3796]
### Description of the Issue
I use portable Np++ on my USB stick. And my favourite theme is standard Deep Black. But every time I plug USB stick into an other computer (and it gets new drive letter) I see orange background -- something is broken with themes. I believe Np++ keeps absolute path to theme file rather then relative. Portable version in idea should keep relative path.

### Steps to Reproduce the Issue
1. Unpack portable version onto USB stick.
2. Set any standard theme, say Deep Black.
3. Replug that USB such that it has another drive letter (try to plug it into another computer, or plug another stick first and then Np++ stick, or just copy Np++ portable directory to local drive and unplug the stick).
4. Start Np++ and behold.

### Expected Behavior
Deep Black theme.

### Actual Behavior
Default theme in Style Configurator and orange background. 

![default](https://user-images.githubusercontent.com/16620214/31117889-f122977e-a844-11e7-8ea5-a226b3add6cc.png)

**Comment by MetaChuh** [comment]
on portable versions, you have to replace stylers.xml with the theme.xml of your choice and keep the theme setting at default (stylers.xml).

thank you for your help and best regards.
