### ISSUE TITLE
Find not working in some cases v7.4.1

### ISSUE THREAD

**Issue by kaundalsajan10** [notepad-plus-plus/notepad-plus-plus#3799]
### Description of the Issue
Some time Find not working with notepad++ i notice the case more than 3 times while working.

### Steps to Reproduce the Issue
1. Copy text.
2. Ctrl + F , enter text.
3. Hit search.

### Expected Behavior
it should highlight the text

### Actual Behavior
Nothing found

**Comment by sasumner** [comment]
Your description lacks sufficient detail.  There are a number of valid reasons why what you've described would result in "Nothing found".  See this:  https://notepad-plus-plus.org/community/topic/14567/search-and-replace-failed/3

**Comment by dail8859** [comment]
Please provide better details and reopen if you have a reproducible set of steps.
