### ISSUE TITLE
NpWiki++ Hosting of the Plugin Web Descriptions is broken

### ISSUE THREAD

**Issue by MichaelAtOz** [notepad-plus-plus/notepad-plus-plus#3801]
### Description of the Issue
Hosting of the Plugin Web Descriptions is broken
(I don't know whether web issues should be logged here, if not please point me in the right direction)
### Steps to Reproduce the Issue
1.  Go to http://docs.notepad-plus-plus.org/index.php/Plugins_By_Category 
2.  Click on a plugin name

### Expected Behavior
Details of the plugin

### Actual Behavior
Not Found
The requested URL /index.php was not found on this server.
e.g. Target http://npp-wiki.tuxfamily.org/index.php?title=Plugin_Central#JSON 

### Other Information
Plugins_By_Category page says 'It provides direct links to Plugin Central', clicking that link gets there.

**Comment by DavidHansen-0x454d43** [comment]
It looks like the links could be updated from:
http://npp-wiki.tuxfamily.org/index.php?title=Plugin_Central#
to:
http://docs.notepad-plus-plus.org/index.php/Plugin_Central#

Unfortunately, I am also not able to sign in/register for the wiki, so I can't make the change (see issue #3540) 

Does anyone else have an account on the wiki, or know how to create one?

**Comment by donho** [comment]
NpWiki++ is not available and replaced by npp-user-manual.org now.
