### ISSUE TITLE
syntax coloring for R

### ISSUE THREAD

**Issue by ironv** [notepad-plus-plus/notepad-plus-plus#3802]
### Description of the Issue

Syntax coloring for R is messed up in version 7.5.1 (64-bit).  It was fine in version 7.4.2 (64-bit).

### Steps to Reproduce the Issue

1. open any .R file and type   require(ggplot2) in both versions.

**Comment by Cyrillev91** [comment]
Removing the default extension 'r' from the REBOL item in langs.xml.
#3650
