### ISSUE TITLE
Removing blank lines clears all bookmarks

### ISSUE THREAD

**Issue by trathor001** [notepad-plus-plus/notepad-plus-plus#3803]
### Description of the Issue
All the bookmarks which have been set gets cleared after textfx is used to remove blank lines.

### Steps to Reproduce the Issue

1. add bookmarks at several places
2. select all text
3. textfx > edit > remove blank lines

### Expected Behavior
None of bookmarks should have been removed. Similar to the behavior when we remove blank lines manually.

### Actual Behavior
All bookmarks have been removed. 

### Debug Information
Notepad++ v7.5.1   (32-bit)
Build time : Aug 29 2017 - 02:35:41
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : ON
Local Conf mode : OFF
OS : Windows 7 (64-bit)
Plugins : mimeTools.dll NppConverter.dll NppExport.dll NppTextFX.dll PluginManager.dll

**Comment by sasumner** [comment]
TextFX is a plugin, and not included in the Notepad++ distribution.  Consequently, bugs or feature requests regarding it should be reported elsewhere.  This list is for core Notepad++ issues.  Recommend closure of this issue.

**Comment by DavidHansen-0x454d43** [comment]
From Notepad++'s [reporting guidelines](https://github.com/notepad-plus-plus/notepad-plus-plus/blob/master/CONTRIBUTING.md):

3. Only report an issue with a plugin if it is one of the standard plugins included in the Notepad++ installation. **Any other plugin issue should be reported to its respective issue tracker.** The standard plugins include (for v6.8.3):
- NppFTP
- NppExport
- Plugin Manager
- Converter
- mimeTools

Unfortunately for you trathor, TextFX [hasn't been maintained for almost a decade](http://docs.notepad-plus-plus.org/index.php/TextFX%27s_Future), so no one is going to be addressing your issue. 

Fortunately though, that functionality (removing blank lines) seems like it would be pretty easy to implement with the PythonScipt Plugin. You can ask for help with doing that [here](https://sourceforge.net/p/npppythonscript/discussion/).

**Comment by sasumner** [comment]
Well, Pythonscript might even be overkill here, if simply looking for an alternate way to remove blank lines.  How about Notepad's native Edit (menu) -> Line Operations -> Remove Empty Lines choices (there are TWO of them)?
