### ISSUE TITLE
Regex Replace

### ISSUE THREAD

**Issue by Andref0** [notepad-plus-plus/notepad-plus-plus#3806]
### Description of the Issue
While working on a regex to remove a part of my text I found that the button replace did not alter my text only when I used replace all that it presented the altered text.

### Steps to Reproduce the Issue
This is just a short sample of my file, I'm working on adapting a MySQL INSERT from one database to another with different values. But it is enough to show what I mean...

(699301,27066,'05276900','VIA ANHANGÜERA, KM 25,2','');
(699300,34325,'70631902','EPAC','');
(699302,25422,'01305904','RUA AUGUSTA, 1029','');
(699303,21733,'08745900','AVENIDA SARAIVA, 400','');
(699304,16552,'13088901','AVENIDA FRANCISCO XAVIER ARRUDA CAMARGO, 300','');
(699305,36180,'88330904','RUA 500, 16','');
(699306,14037,'89211901','RUA BARRA VELHA, 100','');
(699307,12796,'59075901','AVENIDA AMINTAS BARROS, 3003','');

I used the following regex to match for the fields that I'll change.
FIND WHAT: (?<='\d{8}',')([^,']+)(.+);
And this is how I replaced it!
REPLACE: \1'\);

I used the "Find Next" and "Replace" buttons as a "Replace All" makes the program stop responding for some time before getting the results.

### Expected Behavior
I was wanted this result
(699301,27066,'05276900','VIA ANHANGÜERA');
(699300,34325,'70631902','EPAC','');
(699302,25422,'01305904','RUA AUGUSTA, 1029','');
(699303,21733,'08745900','AVENIDA SARAIVA, 400','');
(699304,16552,'13088901','AVENIDA FRANCISCO XAVIER ARRUDA CAMARGO, 300','');
(699305,36180,'88330904','RUA 500, 16','');
(699306,14037,'89211901','RUA BARRA VELHA, 100','');
(699307,12796,'59075901','AVENIDA AMINTAS BARROS, 3003','');

### Actual Behavior
But nothing happened
(699301,27066,'05276900','VIA ANHANGÜERA, KM 25,2','');
(699300,34325,'70631902','EPAC','');
(699302,25422,'01305904','RUA AUGUSTA, 1029','');
(699303,21733,'08745900','AVENIDA SARAIVA, 400','');
(699304,16552,'13088901','AVENIDA FRANCISCO XAVIER ARRUDA CAMARGO, 300','');
(699305,36180,'88330904','RUA 500, 16','');
(699306,14037,'89211901','RUA BARRA VELHA, 100','');
(699307,12796,'59075901','AVENIDA AMINTAS BARROS, 3003','');

### Debug Information
Notepad++ v7.3.3   (32-bit)
Build time : Mar  8 2017 - 03:37:37
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10 (64-bit)
Plugins : mimeTools.dll NppConverter.dll NppExport.dll PluginManager.dll 

When I use "Replace All" it works fine and I get a result like this:

(699300,34325,'70631902','EPAC');
(699301,27066,'05276900','VIA ANHANGÜERA');
(699302,25422,'01305904','RUA AUGUSTA');
(699303,21733,'08745900','AVENIDA SARAIVA');
(699304,16552,'13088901','AVENIDA FRANCISCO XAVIER ARRUDA CAMARGO');
(699305,36180,'88330904','RUA 500');
(699306,14037,'89211901','RUA BARRA VELHA');
(699307,12796,'59075901','AVENIDA AMINTAS BARROS');

But when you are working with a file with 738332 lines it's not viable to test if my regex replacement is perfect with the entire document.

Thanks in advance and if it is a feature I apologise.

**Comment by sasumner** [comment]
Suggest you change your replacement text to \1'\); and try again.  Note the \) where you only had ) 

boost::regex 1.42–1.65 truncates the replacement string when encountering a closing parenthesis without a matching opening parenthesis
