### ISSUE TITLE
Plugin Manager and 64 bit issue

### ISSUE THREAD

**Issue by pedro2555** [notepad-plus-plus/notepad-plus-plus#3807]
Ok, this ain't really a bug and I realize the plugin manager is a third party add on. To be honest I've never realised that the plugin manager wasn't a in house product.

Notepad++ used to be the perfect notepad replacement, just install the latest version install the StarterPlugin and done, all my machines have had that setup.

This last time, wait no plugin manager!! Why?!? Oh it's a 3rd party add on, right! Then why was it distributed with the main program and all of sudden its not!? This is a mess in terms of usability to be honest, and you guys should really think twice before removing something, even more when its not code you control.

Took me about 15 minutes, of downloading, installing, and uninstalling Notepad++ versions, until the PluginManager finally appeared in one of the old version. Currently stuck on that old version, whatever than happens to be, which far from ideal.

Just my opinion, really pissed.

**Comment by sasumner** [comment]
You were right with your first sentence.  Recommend closure of this issue.  
"really pissed" -> You do realize Notepad++ comes to you for $0.00?  I guess even for that price you can be pissed, but probably better to internalize that viewpoint.

**Comment by pedro2555** [comment]
@sasumner I do realize it's free, as is the time I'm spending here pointing out something I think is incorrect. I'm not under valuating your time, do don't it yourself.

My opinion I think is easy to understand, from a user perspective is not OK to remove features, specially true if no alternative is given, as is the case.

And I also like to stress that, although I understand the PluginManager is a 3rd party addon, that is a technical issue, as such a technical solution is needed, and not an excuse to the user.

I'm not telling you to close the shop, I telling you, you should work to avoid this.

**Comment by sasumner** [comment]
It's all pointless as the plugin mgr is on its way toward being an inhouse product...it is being rewritten currently.

**Comment by pedro2555** [comment]
ok man. I'm cool with it. Just trying to be helpful, sorry if I failed somehow.

**Comment by sasumner** [comment]
It's all good.  Just gotta wait on it...
