### ISSUE TITLE
When notepad-plus-plus has lost focus it still displays an input cursor

### ISSUE THREAD

**Issue by maemmott** [notepad-plus-plus/notepad-plus-plus#3808]
### Description of the Issue
I commonly write notes in notepad by switching backwards and forwards with another application:  I have Visual Studio's list of pending changes in display 2, and a commit message, half-written, in notepad-plus-plus in display 1.

I commonly find that I glance at notepad-plus-plus, see the cursor, infer that it has focus, begin typing, and write all over the code in the differencing tool.

It would be so nice, not to see a cursor in notepad-plus-plus, infer that it didn't have focus, allowing me to set focus in it, before beginning typing again.

### Steps to Reproduce the Issue
1. On a two-display PC, set up a source of something to review in one display, and notepad-plus-plus in the other.
2. Begin a document containing the review, in notepad-plus-plus.
3. Perform actions in the source-of-something-to-review (navigate, display sub-items of interest, ...)
4. Allow the mouse pointer to pass over any part of the notepad-plus-plus window, without clicking in that window, so that it doesn't gain focus.
5. Look towards notepad-plus-plus
6. Notice the cursor within it
7. Infer that notepad-plus-plus has the focus.
8. Start typing
9. Discover that you have typed all over the material you are reviewing, and not into your notepad-plus-plus document.

### Expected Behavior
When notepad-plus-plus loses focus, I hope it will cease to display an input-position cursor, or, alternatively, it will grey it out.

### Actual Behavior
When focus leaves notepad-plus-plus, then the input position cursor disappears, but, if the mouse-pointer passes over notepad-plus-plus' window (without it regaining focus), then the cursor comes back, including blinking.

### Debug Information
Notepad++ v7.5.1   (32-bit)
Build time : Aug 29 2017 - 02:35:41
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10 (64-bit)
Plugins : NppTextFX.dll PluginManager.dll XMLTools.dll 

I may not have characterised this issue exhaustively.  While writing this report, I noticed that passing the mouse pointer over the notepad-plus-plus window began the input-position cursor blinking again; but there might be other triggers which I haven't noticed.  I am surprised if this turns out to be the only trigger, because I suffer from the issue more often than (I imagine) I pass the mouse-pointer over the notepad-plus-plus window.

**Comment by sasumner** [comment]
FWIW, doesn't reproduce in my Win7(64):

Notepad++ v7.5.1   (32-bit)
Build time : Aug 29 2017 - 02:35:41
Path : C:\xxxxx\npp.7.5.1.bin\notepad++.exe
Admin mode : OFF
Local Conf mode : ON
OS : Windows 7 (64-bit)
Plugins : mimeTools.dll NppConverter.dll NppExport.dll

**Comment by theREALdebater** [comment]
I have this issue on Windows 10 64-bit. I suffer exactly the same effect as the OP, and often end up typing into the wrong window. 

I would recommend that, when the Notepad++ window does not have focus, the cursor is displayed differently (for example, greyed and steady, as suggested by the OP). I do not recommend that it is hidden, because it may be very important to (continue to) be able to see where it is. 

I would ask for this issue to be pushed up the priority list, please. (Perhaps _everybody_ asks for this!)

**Comment by sasumner** [comment]
Although I'm not affected by the "problem" part, I sort of like the idea to see where the caret is when N++ doesn't have the input focus, but only if it is, as @theREALdebater suggests, visually different from the normal input caret (so I don't get tricked into thinking anything I type will go into N++).  Presume this is a Scintilla concern so we may be barking up the wrong tree...

**Comment by Ekopalypse** [comment]
Current version, 7.7,  seems not to have this issue anymore and therefore should be closed.

**Comment by theREALdebater** [comment]
Part of the problem remains: although the caret disappears when Notepad++ does not have focus, it shows nothing to indicate where the current insertion position is (although it shows the current line). 
I would prefer that the current insertion position or selection remained indicated, but in a subdued way. 
Admittedly, this does not seem to be done by many Windows programs, but I still think it would be useful and not cause a problem for anyone.

**Comment by sasumner** [comment]
@theREALdebater 

A nice idea (unless you are just debating/trolling). :)

However I just tried the Scintilla demo app SciTE v4.1.4 and it does NOT do this, at least by default.  Scintilla would have to support this for it to work in N++.

**Comment by MetaChuh** [comment]
we can not reproduce a cursor appearance, when notepad++ is out of focus, while hovering over its window.
tested on notepad++ 7.7.

many thanks and best regards.
