### ISSUE TITLE
Ctrl+Backspace in Find dialog doesn't backspace

### ISSUE THREAD

**Issue by blackboxlogic** [notepad-plus-plus/notepad-plus-plus#3809]
### Description of the Issue
In the "Find" dialog (opened by pressing ctrl+f) in the "Find what" field, pressing ctrl+backspace doesn't remove the previous word, it adds a rectangle symbol. 

### Steps to Reproduce the Issue
1. Press Ctrl+f (to open find dialog with focus in the "find what" field)
2. Type a word (like "hello")
3. Press Ctrl+backspace (observe that the previous word isn't removed)
Note that I observe this behavior for all text fields in the "Find" dialog.

### Expected Behavior
The word before the cursor should be removed.

### Actual Behavior
Adds a rectangle "backspace" symbol.
Makes developer sad.

### Debug Information
Notepad++ v7.5.1   (32-bit)
Build time : Aug 29 2017 - 02:35:41
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10 (64-bit)
Plugins : ComparePlugin.dll JSMinNPP.dll mimeTools.dll NppConverter.dll NppExport.dll PluginManager.dll sql.dll XMLTools.dll

**Comment by sasumner** [comment]
Where does your expectation that ctrl+backspace should remove the previous word come from?  Maybe a bad example, but in Microsoft's Notepad.exe, in the Find box, ctrl+backspace also adds a rectangle symbol.

**Comment by blackboxlogic** [comment]
Good question, I hadn't considered that it might be useful/expected. Personally, I expect ctrl+backspace to remove the previous word in any standard text entry field. I can find many examples in other software of ctrl+backspace adding a rectangle, and I consider all of them bugs that slipped through QA.

A short list of locations and my observation of the behavior of ctrl-backspace:
- Notepad++: Main window (remove word)
- Notepad++: Open dialog (remove word) but I understand this dialog is borrowed from the OS
- Notepad++: Preferences dialog (rectangle)
- Notepad++: Find dialog (rectangle)
- Chrome: Every field I can find in the interface (remove word)
- MS Outlook: Every field I can find does (remove word)
- MS Word: Every field I can find does (remove word)
- Visual Studio: Find dialog (rectangle), everywhere else (remove word)
- WordPad: Find dialog (rectangle), everywhere else (remove word)
- Notepad: All dialogs (rectangle)

My primary questions:
- Is there a design document specifying (rectangle) behavior?
- Does anyone actually want/use (rectangle) behavior? (and how could we find out?)
- Is it useful to search a document for this symbol. A symbol which is so uncommon that it cannot be easily typed into the document.

**Comment by sasumner** [comment]
The only reason that it removes the word in the N++ main window is that it is tied to the Scintilla command for SCI_DELWORDLEFT in the default keymapping.  If you unmap it via the Shortcut Mapper, it will also insert a "rectangle" in the N++ main window.  This rectangle appears to be a character with byte value 127/0x7F, at least in my trial.  Anyway, you are free to ask for this change in functionality, and you've certainly built a case for it, but I just wanted to point out that, in general, don't expect keycombos that work in normal editing mode to work for the other controls in the N++ user interface.  These controls are normally just simple Windows controls, and as such, don't have extra functionality (I wasn't surprised that N++'s find box and Notepad.exe's Find box handle ctrl+bs the same way).

**Comment by blackboxlogic** [comment]
I understand (rectangle) is natural to the computer.
My opinion is that (remove word) is natural to User (and therefore, worth implementing).
Would this suggestion be more palatable as a feature request instead of a bug report?

**Comment by sasumner** [comment]
It isn't unpalatable.
Issues can be feature-requests or bug-reports.
It's fine.

**Comment by scootergrisen** [comment]
So how do i remove words in the find if not Ctrl+backspace?
I need to remove words a lot in the find dialog so i would really for this to be possible.

**Comment by sasumner** [comment]
@scootergrisen I think it probably could be scripted if you have interest in that kind of solution.

**Comment by blackboxlogic** [comment]
Being new to open-source, what's the next step on an issue like this?
- Gather community consensus on if the change should be made
- Wait for an authoritative voice to assert that the change should be made
- Wait for someone to make the change
- Try to make the change myself, and let people argue over the pull request?

**Comment by scootergrisen** [comment]
I guess im just used deleting words with Ctrl+Backspace from Firefox so i thought that was the norm.
But i see Windows 7 insert that 7f character but when editing document and in search dialog.
If there is a way to delete words i would like to know.

**Comment by sasumner** [comment]
@blackboxlogic I don't really know what to say to your bullet point list, but a positive for the first half of #4 is that you would be taking action that doesn't depend upon anyone but you.  :)
And at the very least you would always have those changes and could make a patched version of Notepad++ any time you wanted.

**Comment by sasumner** [comment]
Someone else pointed out to me that Shift+Ctrl+LeftArrow followed by Delete will approximate the desired behavior...maybe a workaround...

**Comment by blackboxlogic** [comment]
Yes... also as a work around you can also extend your index finger and repeatedly press the backspace key until the offending word is gone. That's how it's been done ever since we crawled out of the primordial goop.

This ticket was intended as a usability improvement over that process (now that we have opposable thumbs)

**Comment by sasumner** [comment]
Yep, but this area is for all types of discussion about the title topic.  And noting some workarounds (to shorten the obvious way of doing things) if they exist might be useful to some future readers.  [I couldn't tell if you were being funny or insulting my comment (from the high quality of your earlier posts you don't fit the mold for the latter).]  Cheers.

**Comment by blackboxlogic** [comment]
Oh, I was just hoping that the existence of a less-than-perfect work-around wouldn't make the suggested change any less valuable. Yes, my last comment was composed with far less care than deserved. You caught me.

**Comment by sasumner** [comment]
It's a good request.  I hope it gets implemented as well.

**Comment by blackboxlogic** [comment]
Related: https://stackoverflow.com/questions/1124639

**Comment by blackboxlogic** [comment]
After a brief attempt at fixing this issue, I've found that the UI framework, and the controls involved do not natively support the desired behavior. Writing code to handle change events would be messy and probably isn't worth it.
Details:
The control is a [ComboBox](https://docs.microsoft.com/en-us/windows/desktop/Controls/combo-boxes), which internally has an [EditControl](https://docs.microsoft.com/en-us/windows/desktop/Controls/edit-controls). Neither of them support the autocompletion feature I was looking for, thinking it would enable ctrl-backspace removing a whole word.

**Comment by blackboxlogic** [comment]
Dear @donho, @evelance and @alef162,
I send you my greatest appreciation for your contribution to society.
