### ISSUE TITLE
Installer should use previous options when upgrading

### ISSUE THREAD

**Issue by robertlabrie** [notepad-plus-plus/notepad-plus-plus#381]
I've got npp installed in a lot of places, you get pretty tired clicking "English" --> Next --> Agree --> Next --> Next --> Check off use old icon and click Install --> then finally finish. It's NSIS right? Can't you just save my selections somewhere and replay them if I'm doing an upgrade?

**Comment by MetaChuh** [comment]
closed due to:
* outdated, not applicable to newer installer versions
