### ISSUE TITLE
[BUG v756] Replace dialog scary with keyboard input!

### ISSUE THREAD

**Issue by sky5walk** [notepad-plus-plus/notepad-plus-plus#3813]
### Description of the Issue
While clicking desired replacements 1 by 1, no problems.
But, if you hit the 'R' key with 'Replace' window open, you are prompted to replace all within a given folder and extension. Very bad, since 'R'eplace is underlined in the dialog button for Replace.

### Steps to Reproduce the Issue
1. Hit [Ctrl+h] for replace window.
2. Click the Replace button as normal.
3. Then decide to use the keyboard 'R' to select the Replace button and FAIL!

### Expected Behavior
I expect the Replace button to respond to the keyboard input 'R'.

### Actual Behavior
I am prompted with:
"Are you sure you want to replace all occurrences in : 
~myfolder
for file type : *.'my ext'"

### Debug Information
Notepad++ v7.5.1   (32-bit)
Build time : Aug 29 2017 - 02:35:41
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10 (64-bit)
Plugins : ComparePlugin.dll mimeTools.dll NppConverter.dll NppExport.dll PluginManager.dll XMLTools.dll

**Comment by sasumner** [comment]
This is because the Find/Replace/Files/Mark dialog defines "underlined-R" twice, once on the Replace page, and once on the Files page.  It just so happens that the processing for the Files page happens first, so that's what happens in your scenario.  This would be a simple fix--just eliminate the duplication.  While you are waiting for this fix to be implemented you can redefine the "underline" keys yourself to avoid your "scary" situation--see here for how to do this:  https://notepad-plus-plus.org/community/topic/11041/new-alt-shortcuts-in-the-find-dialog-for-default-english-language

**Comment by credomane** [comment]
>This is because the Find/Replace/Files/Mark dialog defines "underlined-R" twice, once on the Replace page, and once on the Files page. It just so happens that the processing for the Files page happens first, so that's what happens in your scenario. This would be a simple fix--just eliminate the duplication.

Duplication isn't the issue. If you pressing `R` while the `replace` button on the `replace` tab has focus THEN notepad++ actually triggers the `replace` button on the hidden `Find in Files` tab. If anything else (excluding the text inputs, obviously) on the `replace` tab has focus then pressing `R` triggers the `replace` button on the `replace` tab as expected. 

Yet if you switch to the `Find in Files` tab and try all the above steps then pressing `R` does absolutely nothing at all but all the other keys work for that tab.

This is definitely a coding error somewhere. The fact that `Match whole word only` & `Match case` are on both tabs, are using the same shared keys in both tabs and work perfectly fine is proof of that.

**Comment by sasumner** [comment]
Assuming we are talking about a Localization that is "English"-like, I found that if you switch to "English (customizable)" in a default install, the "Replace in Files" no longer has an underline key in it.  This gives us some more insight (and can work around the original problem).  The original problem IS real, no doubt, which may stem from the Find window's general oddness.  For example, the checkboxes that appear visually to be common among tabs are truly only ONE checkbox in the code (which kind of goes contrary to how you'd think it would be laid out at design time--normally a "tab" is a container, and its children belong ONLY to it...).  A lot of history here, I think...

**Comment by sky5walk** [comment]
Any resolution to this bug?

**Comment by donho** [comment]
Cannot reproduce this bug in 7.8.5
Obviously it's fixed.
