### ISSUE TITLE
SQL Server file: Improper parsing/handling of Single Quote count where the syntax looks to be part of the string but it is not..

### ISSUE THREAD

**Issue by FHankFreeman2** [notepad-plus-plus/notepad-plus-plus#3816]
### Steps to Reproduce the Issue

1. Create a simple SQL Server syntax with single quotes
CTE_POLISH AS (SELECT 
	ISNULL(REPLACE(REPLACE(REPLACE(SUBSTRING(B.Manager, 1, CHARINDEX('OU=',B.Manager,1)),',O',''),'\',''),'CN=',''),'')  AS [Manager]
	FROM CTE_AD_USER A
	LEFT JOIN [dbo].[AD_Info_Data_SQL_ALL] B ON REPLACE(A.[User],'NA\','') = B.[User] 
)
2.  had to add -- ' to end of two lines
CTE_POLISH AS (SELECT 
	ISNULL(REPLACE(REPLACE(REPLACE(SUBSTRING(B.Manager, 1, CHARINDEX('OU=',B.Manager,1)),',O',''),'\',''),'CN=',''),'')  AS [Manager] --'
	FROM CTE_AD_USER A
	LEFT JOIN [dbo].[AD_Info_Data_SQL_ALL] B ON REPLACEa.[User],'NA\','') = B.[User] --'
)
3. 

### Expected Behavior
To properly show syntax when there are single quotes

### Actual Behavior
Not showing syntax properly

### Debug Information
Yes See Second script #2 above

![cte-error](https://user-images.githubusercontent.com/32682076/31400388-645e1dc6-adbd-11e7-8807-0a269af38058.PNG)

**Comment by FHankFreeman2** [comment]
The Syntax of the file is correct and in the short example you should be able to see and fix the problem.
[test_CTE - Copy.txt](https://github.com/notepad-plus-plus/notepad-plus-plus/files/1372765/test_CTE.-.Copy.txt)

**Comment by dail8859** [comment]
`Settings > Preferences > MISC. > Treat backslash as escape character for SQL`

---

![capture](https://user-images.githubusercontent.com/3694843/31455544-eb21c38a-ae85-11e7-896d-bd0416e726f7.PNG)
