### ISSUE TITLE
Styles of Tokens lost when moving to new instance

### ISSUE THREAD

**Issue by polus314** [notepad-plus-plus/notepad-plus-plus#3819]
### Description of the Issue
Any text that I highlighted using the context menu "Style token->Style 1" lost its coloring (style) when I then moved that file into another instance.

### Steps to Reproduce the Issue
1. Open a file with any amount of text.
2. Highlight some text.
3. Right click on your selection and chooose "Style token->Style 1"
4. Right click on the current file's tab at the top of the program and choose "Move to New Instance"

### Expected Behavior
File would be opened in a new window with everything the same.

### Actual Behavior
File was opened in a new window without any of my "styling"

### Debug Information
Notepad++ v7.5.1   (32-bit)
Build time : Aug 29 2017 - 02:35:41
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 7 (64-bit)
Plugins : mimeTools.dll NppConverter.dll NppExport.dll NppFTP.dll PluginManager.dll 

Not a huge deal, but thought I would point it out

**Comment by alankilborn** [comment]
As "styling" isn't a persistent feature, I'd say it isn't really reasonable to expect this behavior and this issue should be REJECTED and CLOSED.

**Comment by ArkadiuszMichalski** [comment]
Same/similar was discussed and rejected: https://github.com/notepad-plus-plus/notepad-plus-plus/issues/4808 ([reason](https://github.com/notepad-plus-plus/notepad-plus-plus/issues/4808#issuecomment-826423221)).
