### ISSUE TITLE
Distribute a pdb along with the release version of Notepad++?

### ISSUE THREAD

**Issue by ariccio** [notepad-plus-plus/notepad-plus-plus#382]
Distributing `pdb`s with `Notepad++` would be quite useful for debugging, and `Notepad++`'s `pdb`'s are not that large. Any reason why we don't distribute them & install alongside the executable?

**For the debug build:**

Uncompressed, they total ~20MB:

![notepad _pdb_size](https://cloud.githubusercontent.com/assets/2142308/8470660/e38c3dee-205c-11e5-90a8-19522d1c621c.PNG)

After compressing with `7-zip`, they total ~2.5MB:
![notepad _pdb_size_compressed](https://cloud.githubusercontent.com/assets/2142308/8470668/0ecf23ae-205d-11e5-9b12-4cf9d35294b0.PNG)

**Comment by ariccio** [comment]
The release build is *slightly* smaller (no surprise there), and thus more amenable to distribution.

![notepad _pdb_size_unicode_release](https://cloud.githubusercontent.com/assets/2142308/8470734/f6244450-205d-11e5-8b23-57680c24a922.PNG)

`vc120.pdb` is marginally smaller. Not enough to warrant a screenshot :)

**Comment by Rikk** [comment]
Because usually only debug versions of programs distribute files used only for development purposes.
Programmers usually send debug versions to users that are having problems hard to reproduce.

**Comment by ariccio** [comment]
*That* I understand. Chrome, for example, has 800MB (!) symbol files, so distributing them to everyone would waste insane amounts of drive space.

Maybe it could be an option during installation?

**Comment by milipili** [comment]
From my point of view, it is quite useless but I don't see any reasons to not do it. But not from the installer. It can be available like other downloads.

**Comment by dail8859** [comment]
I agree making them available would be nice but just as milipili suggested, make it a separate download since > 99% [citation needed] of people wouldn't need it.

**Comment by ariccio** [comment]
Any decision? I'm ok with it being a separate download (as long as it's right next to the normal download), and it'd make debugging much better (for issues like #372 ).

**Comment by ariccio** [comment]
....any update? Having *something* would be nice.

**Comment by Rikk** [comment]
<h6><sub>(if you ask again, donho will give himself another "vacation" lol)</sub></h6>

**Comment by NN---** [comment]
I suggest to add a separate zip with pdb files.
And to upload pdbs to http://www.symbolsource.org/  , it can also host source files for easier crash analysis .

**Comment by donho** [comment]
@Rikk lol

**Comment by donho** [comment]
It will add on more task on each release.
I will consider it but I promise nothing.

**Comment by milipili** [comment]
I am considering an automatic build . But i need to check first for licensing issues. If someone has good knowledge about it, help would be much appreciated (VM on kvm, win7, 8 & 10)

**Comment by NN---** [comment]
@milipili What is your question ? 
What exactly you want from VMs ? 
If you ask about license then VMWare Player is free for non-commercial use.

**Comment by ariccio** [comment]
Forgive my confusion - licensing?

Also... Why symbolsource.org? Why not just use the normal distribution mechanism?

**Comment by NN---** [comment]
@ariccio What do you mean by normal distribution ?
symbolsource.org is a symbols and a source server.
It means you don't need to download pdb files, neither to clone the git repository with the right revision.
You just add it to your symbols path and you can debug crashes, hangs and so on.

**Comment by milipili** [comment]
No vmware player. I want a windows on a VM on a server and i know there are some restrictions (for example only professional versions are allowed)

**Comment by Rikk** [comment]
Use a VPS running Windows?

**Comment by milipili** [comment]
It is also a possible solution indeed.

**Comment by ariccio** [comment]
> What do you mean by normal distribution ?
 symbolsource.org is a symbols and a source server.
 It means you don't need to download pdb files, neither to clone the git repository with the right revision.
 You just add it to your symbols path and you can debug crashes, hangs and so on.

That's *exactly* what I was asking. How'd I never hear about that!!?!

**Comment by milipili** [comment]
The PDB files could be pushed by appveyor.

**Comment by SamB** [comment]
@donho: Naturally, none of us want to add a manual step to the release process.

Unfortunately, I'm having difficulty locating the master script to build & package a release :-(.

**Comment by cmeriaux** [comment]
The build script is in appveyor.yml ( https://github.com/notepad-plus-plus/notepad-plus-plus/blob/master/appveyor.yml )

**Comment by donho** [comment]
@milipili is not active on Notepad++ project on GitHub.
I don't really see the point to provide such file.

**Comment by xomx** [comment]
@donho 

> I don't really see the point to provide such file.

Distributing also the relevant PDB files for all the released N++ binaries is beneficial, when one needs to analyze a problem that happened on a user PC and at the same time it is difficult to reproduce the problem (at another computer/configuration or even again on the same user's PC). Also some powerusers are evidently able to help us analyzing a problem by working with a possible N++ crashdump themselves. Look e.g. here #12448  (..."Crash dump analysis output follows. I tried looking for debugging symbols for Notepad++ but they didn't seem to be available in the Releases page or elsewhere."...)
