### ISSUE TITLE
Can't open two different files whose canonic names are the same

### ISSUE THREAD

**Issue by GiottoVerducci** [notepad-plus-plus/notepad-plus-plus#3820]
### Can't open two different files whose canonic names are the same
https://en.wikipedia.org/wiki/Unicode_equivalence#Normalization

### Steps to Reproduce the Issue
1. Create a file called "é.txt" (C form)
2. Create a file called "é.txt" (D form)
Open the first file. Open the second file.

### Expected Behavior
It should open a new tab for the second file.

### Actual Behavior
The tab of the first file is selected.

### Debug Information
Notepad++ v7.5.1   (32-bit)
Build time : Aug 29 2017 - 02:35:41
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : ON
Local Conf mode : OFF
OS : Windows 10 (64-bit)
Plugins : mimeTools.dll NppConverter.dll NppExport.dll NppTextFX.dll PluginManager.dll XMLTools.dll 

![image](https://user-images.githubusercontent.com/4416696/31540880-2895240e-b00d-11e7-93a3-c55c45a8c6c9.png)

**Comment by CookiePLMonster** [comment]
Confirmed still happening in v7.5.4. Visual Studio Code handles those filenames correctly (opens two tabs).

**Comment by donho** [comment]
My question is, how can I create these 2 files in the same directory.

**Comment by CookiePLMonster** [comment]
They are not the same though - they **look** the same but they are not identical. Try copypasting the two example file names from the issue report and you'll notice you can have both next to each other, but notepad++ treats them as if they had the same name.

**Comment by donho** [comment]
@CookiePLMonster I do understand that they are not the same (Unicode vs ANSI).
My question is how to create an ANSI é since my system is in Unicode.

**Comment by CookiePLMonster** [comment]
Honestly, I don't know. I copied file names from here and the fact Windows allowed me to create those two and vscode handled them fine was enough reasons so look into it IMO.

**Comment by GiottoVerducci** [comment]
As I indicated in the issue message, the names use two different way to encode "é" in Unicode (Form C and D). They are represented the same way, but they are different.
