### ISSUE TITLE
Support template literal (template strings) in Javascript

### ISSUE THREAD

**Issue by fietronic** [notepad-plus-plus/notepad-plus-plus#3822]
### Javascript (ES6) 

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals

New JS now supports multi-line strings. It uses back ticks and you can include variables like ${foobar}

```
console.log(`Fifteen is ${a + b} and
not ${2 * a + b}.`);
```

**Comment by fietronic** [comment]
Just found this is a duplicate of: https://github.com/notepad-plus-plus/notepad-plus-plus/issues/1055

... that was from 2015 and it's still broke.

**Comment by fietronic** [comment]
And I don't think Scintilla is going to do anything about it.

https://sourceforge.net/p/scintilla/feature-requests/1112/

**Comment by igorgaj** [comment]
Expand red line not show corectly and end highlighted bracked with new ES6 template literal strings with multiline, example:
	
![att](https://user-images.githubusercontent.com/19238063/48869753-9bf75380-edde-11e8-8cb0-aee2f39c72fa.png)
Vue.component('slot-component',{    //this bracket not show highlighted end
		template: `
			<div class="card">
				<h3>{{title}}</h3>
				<slot></slot>
			</div>
			`,
		props: {
			title : String
		}
	});

**Comment by ArkadiuszMichalski** [comment]
@donho  @sasumner Let say this bug will be for template literals (template strings) in Javascript (dependent on Scintilla https://sourceforge.net/p/scintilla/feature-requests/1112/ bug). 

There are too many bugs for the same thing:
https://github.com/notepad-plus-plus/notepad-plus-plus/issues/3252
https://github.com/notepad-plus-plus/notepad-plus-plus/issues/7879
https://github.com/notepad-plus-plus/notepad-plus-plus/issues/3331
https://github.com/notepad-plus-plus/notepad-plus-plus/issues/6193
https://github.com/notepad-plus-plus/notepad-plus-plus/issues/4106
https://github.com/notepad-plus-plus/notepad-plus-plus/issues/8421
Maybe close all of them and when Scintill finally (I hope) support this future  then open/accept new (if something will still not working)?

**Comment by donho** [comment]
@ArkadiuszMichalski  Agree. Closing.
