### ISSUE TITLE
bug : NPP HANGS : in full_screen_mode ,  Alt_key_down + mouse_click_right

### ISSUE THREAD

**Issue by stanpetit** [notepad-plus-plus/notepad-plus-plus#3823]
### Description of the Issue
In full_screen_mode (F11) and post_it_mode (F12), on Alt_key_down + mouse_click_right, NPP HANGS,  after a random lapse of time ( ~~ 5 seconds, sometimes immediately )

### Steps to Reproduce the Issue
1. full_screen_mode (F11)
2. Alt_key_down + mouse_click_right

### Expected Behavior
It was a bad gesture of mine : while pasting a selected block in block_selection_mode (alt select) from the mouse menu, I have kept the Alt key pressed.
It is a wrong action : I assume : click_right with alt_key_down (still pressed) produces nothing but escaping the block_selection_mode, and the mouse_menu as well ...

Whatever : it shouldn't make the NPP hang this way !
It reproduces always

### Actual Behavior
It hangs the app.

### Debug Information
Notepad++ v7.5.1   (32-bit)
Build time : Aug 29 2017 - 02:35:41
Path : C:\PAPPZ\NPP\npp.7.4.2\notepad++.exe
Admin mode : OFF
Local Conf mode : ON
OS : Windows 7 (64-bit)
Plugins : autosave2.dll ColorPicker.dll ComparePlugin.dll CustomizeToolbar.dll DSpellCheck.dll ElasticTabstops.dll Explorer.dll LanguageHelp.dll MarkdownViewerPlusPlus.dll mimeTools.dll NamedBookmarks.dll NppAutoIndent.dll NppCalc.dll NppColumnSort.dll NppConverter.dll nppcrypt.dll NppDocShare.dll NppExec.dll NppExport.dll NPPFSIPlugin.dll NppGTags.dll NPPJSONViewer-win32.dll NppMenuSearch.dll NppPlugin_PluginMargin.dll NppQCP.dll nppRegEx.dll NppSaveAsAdmin.dll NppTextFX.dll NppXmlTreeviewPlugin.dll OpenSelection.dll PluginManager.dll PreviewHTML.dll PyNPP.dll PythonScript.dll QuickOpenPlugin.dll regrexplace.dll RunMe.dll SourceCookifier.dll XMLTools.dll 

Best, Stan.

**Comment by dail8859** [comment]
Can't reproduce it on my system. I would suggest trying with plugins disabled as you have quite a few installed which may be causing this issue rather than Notepad++ itself.

**Comment by stanpetit** [comment]
hi Dail.

Thanks for the feedback

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Garanti
sans virus. www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

2017-11-13 21:54 GMT+01:00 dail8859 <notifications@github.com>:
