### ISSUE TITLE
"Modern skin" - think about that twice.

### ISSUE THREAD

**Issue by Sephirothbahamut** [notepad-plus-plus/notepad-plus-plus#3828]
I'm not a very active programmer but this issue just cought my attention:
(https://github.com/notepad-plus-plus/notepad-plus-plus/issues/622)
And please, please, if a "modern ui" is being developed, make it available as an option, and not as a replacement. Allow people to use the classic style.
Many people prefer the older style, not everyone likes to have overly oversized buttons which fill 1/5 of the window. Don't make the same mistake Microsoft did with Office.

**Comment by dail8859** [comment]
Please keep comments in relavant issues or threads. There's not really a need to open a new issue. 

You can also discuss this [here](https://notepad-plus-plus.org/community/topic/250/it-s-time-for-ui-update)
