### ISSUE TITLE
Allow forward slashes as directory separators in path names

### ISSUE THREAD

**Issue by KvanTTT** [notepad-plus-plus/notepad-plus-plus#3840]
### Description of the Issue

Allow forward slashes in file path names

### Steps to Reproduce the Issue

1. Press Ctrl + O (Open file)
2. Insert absolute file name with one or more forward slashes `F:\Temp/text.txt`
3. Click "Open"

### Expected Behavior

Notepad++ opens a file without problems. It's possible to replace forward slashes with backslashes if required.

### Actual Behavior

Notepad++ does not open file with messages `The file name is not valid`.

**Comment by sasumner** [comment]
Just asking...why would this be useful?

**Comment by KvanTTT** [comment]
During cross-platform development. Linux and MacOS use a forward slash separators. In some cases, it's convenient to copy the file path from Linux and paste it to Notepad++.

**Comment by KvanTTT** [comment]
Moreover, Windows Explorer itself opens files with mixed slashes.

**Comment by MattyJacques** [comment]
Are you sure? I just tried on my windows 10 machine it won't even let me rename a file to have slashes in it.

See "Naming Conventions" from [here](https://msdn.microsoft.com/en-us/library/windows/desktop/aa365247(v=vs.85).aspx)

**Comment by KvanTTT** [comment]
I'm sure. You can not rename the file because of slashes are restricted in file names: https://stackoverflow.com/a/31976060/1046374 This is related not only to Windows 10.

**Comment by sasumner** [comment]
Suggest title change for this issue:  "Allow forward slashes as directory separators in pathnames"

**Comment by KvanTTT** [comment]
On a note: VSCode also has such feature request: https://github.com/Microsoft/vscode/issues/29128

**Comment by axaharman** [comment]
for people working in cross-platform projects (e.g. Linux and Windows) is just a hell having to convert manually this separators, for people that don't need the feature it does not hurt at all since / is not allowed anyway in a path in windows. Also a shortcut "toggle path separator" would help for the issue, by toggle meaning convert all forward or all backward.

**Comment by sasumner** [comment]
Suggestion while waiting for implementation:
Two one-line Pythonscripts. 
One like this:
`editor.replaceSel(editor.getSelText().replace('\\', '/'))`
The other like this:
`editor.replaceSel(editor.getSelText().replace('/', '\\'))`

**Comment by KvanTTT** [comment]
This is an obvious suggestion that can be implemented in any other language. Anyway, it's not so convenient as native forward slashes support.

**Comment by sasumner** [comment]
Yep but no other language except a Notepad++ scripting one is going to be as convenient WITHIN Notepad++.  I was just pointing that out as a workaround for those that may not know about the scripting support, or others that think feature requests are quick to be adopted.  Cheers.

**Comment by ihnorton** [comment]
Ref #2438

**Comment by githiremojo** [comment]
Powershell accepts both / and \ as directory pat separators

When working with various tools, a file path may be provided in either mode

It is a hassle to have to run a conversion from \ to  / on each file I need to open

**Comment by ocroquette** [comment]
For those wondering how to use this feature, you need to disable in the settings "Default directory" / "Use new style dialogs".

Here is a screenshot: https://community.notepad-plus-plus.org/topic/15942/opening-unix-style-file-paths
