### ISSUE TITLE
Collapse top level not working in some cases in .js

### ISSUE THREAD

**Issue by Vipiao** [notepad-plus-plus/notepad-plus-plus#3845]
### Description of the Issue
Some cases when trying to collapse functions and other collapsables it seems to treat some curlybrackets in the comments as if it were not in the comment

### Steps to Reproduce the Issue
1. Make a new .js document
2. Paste in the following:
function a(){
	// {
	//}
}
function b(){
	
}
3. Press "alt + 1" to attempt collapsing the top level

### Expected Behavior
The functions collapse like this:
function a(){
function b(){

### Actual Behavior
The functions collapse like this:
function a(){
}
function b(){
	
}

### Debug Information
Notepad++ v7.5.1   (64-bit)
Build time : Aug 29 2017 - 02:38:44
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10 (64-bit)
Plugins : mimeTools.dll NppConverter.dll 

Working unfolded
https://ibb.co/jj8Uvm

Working folded
https://ibb.co/nggXFm

Not working unfolded:
https://ibb.co/eoSpvm

Not working folded:
https://ibb.co/f5q9vm

**Comment by dail8859** [comment]
This is a "feature" with the way Scintilla (the component Notepad++ uses to handle the text editing) folds code. You can put `//}` or `//{` to manually create your own fold points. 

Take a look at [this post](https://notepad-plus-plus.org/community/topic/12907/fold-line-breaks-after-update-to-notepad-7-2-2) on the forum for a solution.
