### ISSUE TITLE
Notepad++ cannot be built with GCC/MinGW

### ISSUE THREAD

**Issue by marcows** [notepad-plus-plus/notepad-plus-plus#385]
This seemed to be possible once because there are already adaptions available including a makefile.

**Comment by milipili** [comment]
CMake will be used in the near future for the master branch. Please keep you changes for creating a new PR as soon as it is possible to compile with the new cmake.

**Comment by milipili** [comment]
note : C++11/14 is now required
note : avoid any code change as much as possible

**Comment by marcows** [comment]
I know about the switch to CMake, but it's not there yet. I initially submitted these patches on December 2014 (see [Sourceforge patches](http://sourceforge.net/p/notepad-plus/patches/632/)), so this work already was existing before the CMake plans I think.

Also at that time it built properly without the C++11/14 compiler flag, so there might be some commits, which are not necessary now anymore, I just kept them to avoid destroying work.

I only added changes necessary for a more or less clean build. Do you mean I should remove the patches fixing general build warnings and warnings not relevant with C++11/14 anymore and just keep the fixes for build errors? I will do it, but it's sad due to the invested time.

**Comment by milipili** [comment]
Can you come on gitter ?

**Comment by milipili** [comment]
CMake should be available during this week.
Changes related to a clean build is a separate matter. And for consistency with other PR I would prefer only a strict fix for the current subject.
After I will take a tour of all issues/pr related to build fixes (#386 included) to integrate them if possible.

**Comment by marcows** [comment]
I could also create a new pull request with reduced commits after the CMake integration if you prefer. By merging the whole branch instead of selectively picking the commits, the logical relation to the GCC build of all the separate changes will be preserved in the repository history.

**Comment by milipili** [comment]
Oki not this week, I was a bit delayed :)

**Comment by ariccio** [comment]
I'm curious, does this mean that you're dropping support for the native toolchain?

**Comment by milipili** [comment]
Oh no, VS2013 will be still the official compiler for n++. But with cmake we will be able to test VS2015, mingw... And since we should be able to easily compile n++ with both mingw and vs, more warnings should arise.

**Comment by marcows** [comment]
It seems CMake will not be integrated in the near future, so I rebased my patch series, eliminating all commits which are not strictly necessary (compile warning fixes) as suggested by @milipili.

**Comment by mzbab88** [comment]
Um, can somebody update makefiles and/or code again? Because mingw failes to build for me. You can see error and details here https://notepad-plus-plus.org/community/topic/11701/how-to-compile-notepad-with-mingw-or-clang

**Comment by marcows** [comment]
See #1663

**Comment by marcows** [comment]
And for Scintilla see #1656

**Comment by mzbab88** [comment]
Oh, so they weren't merged?

Sorry, how can I download those pull requests locally? I'm a total noob with git.

**Comment by marcows** [comment]
No, not yet.

```
git clone https://github.com/marcows/notepad-plus-plus.git
cd notepad-plus-plus
git checkout -t origin/gcc-fixes
```
For everything else see Git documentation.

Note that the MinGW build of Notepad++ is not successful currently even with those patches.

**Comment by mzbab88** [comment]
My mingw complains about undefined _locale_t in PowerEditor/src/MISC/Common/Common.cpp stodLocale, what can I replace it with? Or, how should I define it?

It's only used internally with _wcstod_l, https://msdn.microsoft.com/en-US/library/kxsfc1ab.aspx and just converts string to number based on current locale, or something.

and externally in PowerEditor/src/MISC/Common/Sorters.h DecimalCommaSorter::convertStringToNumber(const and DecimalDotSorter::convertStringToNumber

Somebody also told me something about locale_t being a posix thing, and that it's weird to see it in a windows programs, I didn't really understood what he meant.

**Comment by marcows** [comment]
See #1229 for the MinGW package I used. Maybe you chose another one, I don't get your errors.

Repeating `mingw32-make -j4` (or a higher number for less iterations) until most files are compiled successfully should only leave these files remaining:

    fileBrowser.cpp
    ReadDirectoryChangesPrivate.cpp
    ReadDirectoryChanges.cpp

with following error message:

    ReadDirectoryChanges.h:46:21:_ fatal error: atlbase.h: No such file or directory

ATL (used in new feature File browser) is not supported in MinGW.

**Comment by mzbab88** [comment]
I just went on reading mentioned in src/PowerEditor/src/WinControls/ReadDirectoryChanges/ReadDirectoryChanges.h blogposts https://qualapps.blogspot.ru/2010/05/understanding-readdirectorychangesw.html and https://qualapps.blogspot.ru/2010/05/understanding-readdirectorychangesw_19.html , and the only place they mention ATL is this paragraph:

> ReadDirectoryChangesW is a "W" routine, so it does everything in Unicode. There's no ANSI version of this routine. Therefore, the data buffer is also Unicode. The string is not NULL-terminated, so you can't just use wcscpy. If you are using the ATL or MFC CString class, you can instantiate a wide CString from a raw string with a given number of characters

So, quite possibly the only reason for usage of ATL in this class is for the CString class, which easies working with widechar unicode strings a bit. So probably it's relatively easy to make it work without this dependency. I should try it tomorrow... Really not sure if I'll manage to do anything.

By the way, how this File browser feature works? I don't know where to turn it on in notepad++ , I'd like to at least look at it once.

**Comment by marcows** [comment]
@mzbab88 I just searched for this feature myself with the now working MinGW build with stub FileBrowser. Invoke menu "File -> Open Folder as Workspace". After chosing a directory, for the MinGW build the sidebar only shows the heading, which is expected and what I hoped for without crashing.

**Comment by mzbab88** [comment]
I tried this, and it actually compiled, awesome! But it doesn't start, only shows messagebox with "Entry point _ZNKSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE4dataEv not found in DLL library libstdc++-6.dll"

Maybe you know what I must download this time? Search results for dlls are incredibly suspicious, I don't know where to get the last version. Sorry for troubling you.

**Comment by marcows** [comment]
Nothing to download, NotepadPP.exe just has to find the needed dlls. You either have to copy them to the bin/ directory or expand the PATH variable accordingly. Affected files are libgcc_s_sjlj-1.dll, libstdc++-6.dll, libwinpthread-1.dll, SciLexer.dll. See also gcc/readme.txt where it wrongly only talks about Wine usage.

**Comment by mzbab88** [comment]
Everything seems to work, I can now start hacking the source, thanks!

**Comment by mzbab88** [comment]
Actually, no. It saves config.xml wrong.

It reads this:

```
<?xml version="1.0" encoding="Windows-1252" ?>
<NotepadPlus>
    <GUIConfigs>
        <!-- 3 status : "large", "small" or "hide"-->
        <GUIConfig name="ToolBar">standard</GUIConfig>
        <!-- 2 status : "show" or "hide"-->
        <GUIConfig name="StatusBar">show</GUIConfig>
        <!-- For all attributs, 2 status : "yes" or "no"-->

```

and turns it into this:

```
<?xml version="1" encoding="W" ?>
<N>
    <G>
        <!-- -->
        <G n="T" v="y">s</G>
        <!-- -->
        <G n="S">s</G>
        <!-- -->
        <G n="T" d="y" d="y" d="y" r="y" c="y" d="n" v="n" m="n" h="n" />
        <!-- -->

```

This results in him telling me that "Load config.xml failed" every time I start it. Actually, starting it first time is fine, and starting it after deleting config.xml is fine too, because it just reads config.model.xml instead. But every time after that, this happens.

**Comment by marcows** [comment]
I know, but haven't investigated because I was satisfied with the state for developing and never considered to use the MinGW build productively.

session.xml is affected as well and probably all other xml files whenever they are written.

**Comment by mzbab88** [comment]
I changed %s to %S in all generic_fprintf functions in PowerEditor/src/TinyXml/tinyxml.cpp, and it worked. Not sure if this is the best solution though, and not sure what it actually did. Reference: http://stackoverflow.com/questions/17700797/printf-wprintf-s-s-ls-char-and-wchar-errors-not-announced-by-a-compil

I wonder if %s and %S mean different things on different OSes and different compilers. I wonder if changing %s to %S will break compilation for other compilers. I wonder what tinyXmlA folder is for.

Don't know how to commit and send push request on github, so I"ll just write about it here.
