### ISSUE TITLE
part of sorted view in Notepad++ Windows dialog frozen

### ISSUE THREAD

**Issue by ebouden** [notepad-plus-plus/notepad-plus-plus#3850]
### Description of the Issue
Notepad++ V7.5.1 32 bit.
The Windows dialog freezes the lower series of the sorted filenames when having more than 27 files open.

### Steps to Reproduce the Issue
menu > Window > Windows
sort on any column
when having more than 27 files open, only the first 27 files are displayed sorted, while the rest of the view is frozen to the old contents.
Selecting one (or all: Crtl-A) of these frozen filenames reveals the correctly sorted filename underneath it.
So sorting happens correctly, but the view freezes the 27++ portion

### Expected Behavior
The view showing all filenames after a sort operation.

### Actual Behavior
Only the first 27 filenames are showed after a sort operation.

### Debug Information
-

**Comment by MetaChuh** [comment]
please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins if you update from version 7.5.9 or below.
if your issue still persists, and it is still of relevance, please feel free to file a new issue as easy to understand and reproducible as possible.

thank you for your help and best regards.
