### ISSUE TITLE
Crash on macro playback or text replace in moderate large file

### ISSUE THREAD

**Issue by dragnag** [notepad-plus-plus/notepad-plus-plus#3853]
### Description of the Issue
When I record simple macro (add few characters to text in single line) and try to playback it multiple times in a text file with many lines (sometimes 100 times is enough, sometimes "Until end of the file" must be used to reproduce this bug), Notepad++ crashes.

Similarly, when I use Text Replace (Ctrl+H) on file with many lines, Notepad++ also dies, so it might be the same bug.

I attached file with 5000 lines, in which I experienced this problem, but even less should be enough. 

### Steps to Reproduce the Issue

1. Open attached file [raw_ids.txt](https://github.com/notepad-plus-plus/notepad-plus-plus/files/1421795/raw_ids.txt)

2. Place cursor at the beginning of the file and hit "Start recording macro" button on toolbar
3. Extend text in the first line so it changes from `1203457` to `{0x00, 0x00, 0x01, 0x20, 0x34, 0x57},` and move cursor to the beginning of next line
4. Press "Stop recording"
5. Press "Run a Macro multiple times..." button on the toolbar and choose "Run until the end of the file"
6. Shortly after starting the job Notepad++ crashes.

To reproduce problem with Text Replace open the same file and perform standard text replace of phrase `120` to `ddd`. Similarly, Notepad++ crashes shortly after hitting `Replace all` button.

The same problems occur, when text is pasted to a new file (instead of loading it from disk).

The problem appears since quite long time afair.

### Expected Behavior
Well, I would expect, that Notepad++ does the job without crashing :)

### Actual Behavior
A system dialog opens, informing, that "Notepad++: a free (GNU) source code editor stopped working" with choice of debugging the app or terminating it.

### Debug Information
Notepad++ v7.5.1   (32-bit)
Build time : Aug 29 2017 - 02:35:41
Path : D:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10 (64-bit)
Plugins : LocationNavigate.dll mimeTools.dll NppConverter.dll NppExport.dll PluginManager.dll

**Comment by dail8859** [comment]
It worked fine for me. Try disabling your plugins, more specifically LocationNavigate has been known to cause issues with alot of edits being made by macros and search/replace.

**Comment by dail8859** [comment]
Closing for now. If you disable your plugins and still have the problem, reopen the issue.
