### ISSUE TITLE
Repalcing is not done correctly

### ISSUE THREAD

**Issue by teswarchandra** [notepad-plus-plus/notepad-plus-plus#3854]
when i am trying to replace some path it is not been replaced and when searching the same path it is not showing the correct files. 
### Description of the Issue

when the content of some files is as follows :

**cp some_file   \Home\ \ anotherfile**

and i am trying to replace _**\Home\ \ anotherfile**_ as **\Home\anotherfile**
I was not able to replace and the count is not correct in the file 

**Note** : There is no space between the slashes( \ ). Just to represent Here i written like that.

### Steps to Reproduce the Issue

1. keep some thing in file as shown above in some file 3 to 4 files and try to replace it with single ' \ ' 

### Expected Behavior

I expected that i would replace the double slash ( \ ) with single slash ( \ )

### Actual Behavior

Not happening as it expected
### Debug Information

Notepad++ v7.3.3   (32-bit)
Build time : Mar  8 2017 - 03:37:37
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 8.1 (64-bit)
Plugins : mimeTools.dll NppConverter.dll NppExport.dll PluginManager.dll

**Comment by sasumner** [comment]
@teswarchandra 

What is your "Search mode" setting?  If it is not "Normal" you will get exactly what you've described and that is correct behavior.

**Comment by dail8859** [comment]
Try the normal mode as @sasumner suggested. If you still have problems please reopen with a screenshot of your search dialog.
