### ISSUE TITLE
New window goes out of screen

### ISSUE THREAD

**Issue by Ankeraout** [notepad-plus-plus/notepad-plus-plus#3855]
### Description of the Issue

When creating a new editor window, the window is placed out of screen.
This behaviour has been experienced on 2 different computers with windows 7 x64.

### Steps to Reproduce the Issue

1. Right-click on a file tab
2. Choose "open in a new window"
3. Enjoy the invisible window

### Expected Behavior

I expected the new window to be visible on the screen.
To make it visible, I have to select it in the bottom menu of Windows, then select "maximize" and it becomes visible.

### Actual Behavior
The window is out of screen.

### Debug Information

Notepad++ v7.5.1   (64-bit)
Build time : Aug 29 2017 - 02:38:44
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 7 (64-bit)
Plugins : mimeTools.dll NppConverter.dll 

![image](https://user-images.githubusercontent.com/15966256/32133114-b5f04520-bbd1-11e7-9b2a-1e96d2fdfb5c.png)
^ This window shows correctly
![image](https://user-images.githubusercontent.com/15966256/32133118-c05c8578-bbd1-11e7-8cfc-223e2f9766f2.png)
^ I have selected Notepad++, but it does not show on the screen.
![image](https://user-images.githubusercontent.com/15966256/32133126-df112492-bbd1-11e7-9b8f-39312bb460ea.png)
^ I have to maximize it to make it visible.

**Comment by MetaChuh** [comment]
please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins if you update from version 7.5.9 or below.
if your issue still persists, and it is still of relevance, please feel free to file a new issue as easy to understand and reproducible as possible.

thank you for your help and best regards.
