### ISSUE TITLE
7.4.2 64bit doesn't remember opened tabs after restart and sessions are not saved

### ISSUE THREAD

**Issue by quantuumsnot** [notepad-plus-plus/notepad-plus-plus#3857]
7.4.2 64bit doesn't remember opened tabs after restart
Just restarted the Windows 7 SP1 64bit while npp was opened with ~15 tabs and after starting it again no tabs were saved

**Comment by sasumner** [comment]
How is your 
Preferences -> Backup -> Remember current session for next launch
configured?  Checkbox checked or unchecked?

**Comment by quantuumsnot** [comment]
Checked, I should noted that. I'm using N++ since 2004

**Comment by MetaChuh** [comment]
not reproducible on 7.6.6 with the given information.

please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins if you update from version 7.5.9 or below.
if your issue still persists, please feel free to file a new issue as easy to understand and reproducible as possible.

thank you for your help and best regards.

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).
please file an issue as easy to understand and reproducible as possible.

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
(no extra account is needed, just use your github account to sign in)
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)
