### ISSUE TITLE
RegEx replace bug

### ISSUE THREAD

**Issue by thanhminhmr** [notepad-plus-plus/notepad-plus-plus#3859]
### Description of the Issue
RegEx replace not work correctly.
(Sorry I don't know how to describe it more clear, but just follow the step)

### Steps to Reproduce the Issue

1. Open this file: [DefaultLayouts.txt](https://github.com/notepad-plus-plus/notepad-plus-plus/files/1425068/DefaultLayouts.txt)
2. **Search > Replace**, or **Ctrl-H**
3. Find what:
~~~~
(\Q<StartLayout\E\s(?:(?:.|\R)*?)\>)(?:(?:.|\R)*?)(\Q</StartLayout>\E)
~~~~
Replace with:
~~~~
$1$2
~~~~
![capture](https://user-images.githubusercontent.com/31412085/32143995-ac5d8e1e-bce4-11e7-93e6-e0f9af0fead7.PNG)
4. **Replace All**, should replace 24 occurrences.

### Expected Behavior
Get this result:
[DefaultLayouts_after.txt](https://github.com/notepad-plus-plus/notepad-plus-plus/files/1425082/DefaultLayouts_after.txt)

### Actual Behavior
Should be this: (tested with [RegEx101](https://regex101.com/))
[DefaultLayouts_correct.txt](https://github.com/notepad-plus-plus/notepad-plus-plus/files/1425079/DefaultLayouts_correct.txt)

### Debug Information
Notepad++ v7.5.1   (32-bit)
Build time : Aug 29 2017 - 02:35:41
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10 (64-bit)
Plugins : JSMinNPP.dll mimeTools.dll NppConverter.dll NppExport.dll PluginManager.dll

**Comment by MAPJe71** [comment]
When corrected to (removed one backslash)...
Find what: `(\Q<StartLayout\E\s(?:(?:.|\R)*?)>)(?:(?:.|\R)*?)(\Q</StartLayout>\E)`
Replace with: `$1$2`
it seems to work just fine.

**Comment by MAPJe71** [comment]
Please close issue as it's not a bug.

**Comment by thanhminhmr** [comment]
I search around a bit, and find lots of page said something like: after a slash, it is some special thing, or it match exactly the next character.
It is a bug (or a missing feature?) in current NPP's RegEx.

http://www.gnu.org/software/emacs/manual/html_node/emacs/Regexp-Backslash.html
https://docs.microsoft.com/en-us/dotnet/standard/base-types/character-escapes-in-regular-expressions

**Comment by MAPJe71** [comment]
Notepad++ uses the Boost::RegEx library v1.55 which interprets `\>` as a special character meaning `assert position at the end of a word`.
If you wanted the `\>` to be interpreted exactly as a `>` you should have just used `>`, no need for the backslash i.e. escape character. Not a bug nor a missing feature, just incorrect use of NPP's RegEx.

**Comment by thanhminhmr** [comment]
Thanks for fast reply. Now I realise it is not NPP fault, it just a misused.
I think to prevent someone misused RegEx again, we should put this link somewhere in the search and replace GUI.
http://www.boost.org/doc/libs/1_63_0/libs/regex/doc/html/boost_regex/syntax/basic_extended.html
