### ISSUE TITLE
Automplete detecting unwanted symbols

### ISSUE THREAD

**Issue by Vipiao** [notepad-plus-plus/notepad-plus-plus#3861]
### Description of the Issue
The autocomplete detects symbols it should not detect as variables in .js files. This has multiple times caused me to get random symbols in my code, that I did not intend to be there.

### Steps to Reproduce the Issue
1. Make a .js file.
2. Write the following:
// somevar}
somev
3. "somevar" should autocomplete to "somevar}"

### Expected Behavior
I expected the autocomplete to omit the "}" symbol.

### Actual Behavior
The autocomplete did not omit the "}" symbol.

### Debug Information
Notepad++ v7.5.1   (64-bit)
Build time : Aug 29 2017 - 02:38:44
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10 (64-bit)
Plugins : mimeTools.dll NppConverter.dll 

Problem:
![slett](https://user-images.githubusercontent.com/25079722/32147558-ccadfdac-bce9-11e7-8230-7a41f5152d39.png)

**Comment by MCCshreyas** [comment]
Hey,
Give some space in between some var and }.
It will work then.
