### ISSUE TITLE
Ctrl+A keyboard shortcut doesn't work in the MD5 generator

### ISSUE THREAD

**Issue by vlakoff** [notepad-plus-plus/notepad-plus-plus#3863]
In the "Generate MD5 Digest" window ("Tools > MD5 > Generate..."), the Ctrl+A keyboard shortcut doesn't work. That's quite surprising, and this shortcut would be very useful (for selecting the current input, letting easily delete/replace it, which is currently tedious).

Note that most other shortcuts (e. g. Ctrl+C) do work already.

* Work : Ctrl + X (cut), C (copy), V (paste), Z (undo)
* Don't work : Ctrl + A (select all), Y (redo) (maybe this one would be harder to implement?)

Notepad++ 7.4.2

**Comment by vlakoff** [comment]
Refs the PR by luisffranca: #3898

**Comment by donho** [comment]
https://github.com/notepad-plus-plus/notepad-plus-plus/pull/6034
