### ISSUE TITLE
Is it possible to build notepad++.exe and SciLexer.dll on Microsoft Visual studio 2017?

### ISSUE THREAD

**Issue by operasfantom** [notepad-plus-plus/notepad-plus-plus#3864]

**Comment by sasumner** [comment]
This is not an "issue".  Ask this as a question here: https://notepad-plus-plus.org/community/

**Comment by dail8859** [comment]
Supposedly 40163e0338878c649804b3aa3d6a5dc4a4c1f70f added some sort of support for 2017
