### ISSUE TITLE
Autocomplete with c library function strcpy works wrong

### ISSUE THREAD

**Issue by Morgan-iv** [notepad-plus-plus/notepad-plus-plus#3866]
### Description of the Issue

Autocomplete with c library function strcpy works wrong - NPP writes stpcpy instead of strcpy
### Steps to Reproduce the Issue

1.  Write "st"
2.  Choose "strcpy" in autocomplete list and press tab
3.  Get the stpcpy instead of strcpy

### Expected Behavior

Autocomplete to strcpy
### Actual Behavior

Autocomplete to stpcpy
### Debug Information

Notepad++ v7.5.1   (32-bit)
Build time : Aug 29 2017 - 02:35:41
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10 (64-bit)
Plugins : mimeTools.dll NppConverter.dll NppExport.dll PluginManager.dll

**Comment by dail8859** [comment]
Works fine for me.
![strcpy](https://user-images.githubusercontent.com/3694843/32299894-99c50318-bf2d-11e7-8f47-a34502b201ca.gif)

```
Notepad++ v7.5.1   (32-bit)
Build time : Aug 29 2017 - 02:35:41
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : ON
Local Conf mode : OFF
OS : Windows 7 (64-bit)
Plugins : BetterMultiSelection.dll DoxyIt.dll DSpellCheck.dll ElasticTabstops.dll LuaScript.dll MarkdownViewerPlusPlus.dll NppEditorConfig.dll PluginManager.dll Scintillua++.dll SurroundSelection.dll 
```

**Comment by mwishoff** [comment]
Works fine for me as well.

**Comment by Runner666** [comment]
strcpy

**Comment by dail8859** [comment]
Closing for now. If you are have any additional info please reopen.
