### ISSUE TITLE
Notepad++ occasionally loses indentation, but also sometimes it comes back

### ISSUE THREAD

**Issue by lighth7015** [notepad-plus-plus/notepad-plus-plus#3867]
### Description of the Issue
After leaving Notepad++ open for days on end (My preferred code editor is Notepad++, so it stays open constantly.) sometimes while working in PHP or C++ or whatever, I will all of a sudden **lose** indentation- e.g. I'll be in the middle of a tab-indented line 4 or 5 tabs deep and it will suddenly forget that it was indenting altogether and insert a simple newline instead of keeping the indent going. I have verified behavior this on two separate computers.

### Steps to Reproduce the Issue
1. Leave Notepad++ running for several days.
2. It will automatically stop tab indenting.

### Expected Behavior
1. It keeps using tab indentation.

### Actual Behavior
1. It fails to indent code.

### Debug Information
```Notepad++ v7.5.1   (32-bit)
Build time : Aug 29 2017 - 02:35:41
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : ON
Local Conf mode : OFF
OS : Windows 10 (64-bit)
Plugins : PluginManager.dll 
```

**Comment by MetaChuh** [comment]
please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins if you update from version 7.5.9 or below.
if your issue still persists, and it is still of relevance, please feel free to file a new issue as easy to understand and reproducible as possible.

thank you for your help and best regards.
