### ISSUE TITLE
Icons in Explorer doesn't match files types

### ISSUE THREAD

**Issue by ILPlais** [notepad-plus-plus/notepad-plus-plus#387]
Hello,
I have some issues with the Explorer in Notepad++. Some icons doesn't match they own file-types.
I don't know why and how to reproduce :(
I wish you a nice day.

![2015-07-02 15_26_33-notepad](https://cloud.githubusercontent.com/assets/2880695/8478030/f2b30754-20ce-11e5-80f2-ff1586a7d715.png)

**Comment by MetaChuh** [comment]
closed due to:
* inactivity (4y)
* related to windows explorer
