### ISSUE TITLE
verbose backup- adding computer name to backup filename

### ISSUE THREAD

**Issue by svsdeveloper** [notepad-plus-plus/notepad-plus-plus#3874]
Hello,
we work with NPP in the team to process many sql files.

Now we are usint the verbose backup of NPP to get a complete archive of all changed files. But after some work and saving a lot of files with verbose backups, no one can say who saved a particular file because the filename does not include the identity of the person.

Is it possible or will it be possible to add the computer name to the file name of the backup file in verbose backup?
That would greatly simplify the work!

Thank you for your hard work and best regards,
svsdeveloper

**Comment by sasumner** [comment]
Have you considered scripting this?  I ask because it would be fairly easy to script and is a pretty obscure usage--meaning unlikely to be adopted (but I don't decide what does/doesn't get adopted).

**Comment by svsdeveloper** [comment]
Thanks for the suggestion but i do not know how to script this. The verbose backup is moving the original file to the backup folder and renaming the backup file. How can i change this functionality by script?
Thanks a lot for any hint!

**Comment by sasumner** [comment]
So is your team all willing to use the 32-bit version of Notepad++ and the Pythonscript plugin?  For what I have in mind you would turn OFF the normal verbose backup functionality and just set up a script to run on every save of a file.  Note that this would be slightly different from the verbose backup function--that creates a copy of the file BEFORE changes--the script idea would create a snapshot of the file in its current state.  Depending upon your need that might be better anyway.  Anyway if that is all acceptable the script is rather trivial so let me know and I'll help you move forward.

**Comment by svsdeveloper** [comment]
We are all using the 32-bit version of NPP, so that is no problem. So why not giving a try for Pythonscript!? Do you have a small example script for saving a copy of the current file to another directory?
That would be great! Thanks a lot for the suggestion. It is maybe the better way to save a file after making changes..

**Comment by dail8859** [comment]
> Now we are usint the verbose backup of NPP to get a complete archive of all changed files. But after some work and saving a lot of files with verbose backups, no one can say who saved a particular file because the filename does not include the identity of the person.

I would argue this is more "abuse" of the feature as opposed to its intended use :) 

There are other tools that are more well suited to this kind of version control.

I'll close for now but you are welcome to continue the discussion here or move to the [Notepad++ discussion forum](https://notepad-plus-plus.org/community/) (which seems to be down currently)

**Comment by sasumner** [comment]
@dail8859, yea, everybody thinks the specific way they want to do things should be made a feature in the standard product.  But...open-minded people like the OP of this issue can see the wisdom of other means.  I'll give them a little Pythonscript example here soon to help get them on their way.  This need is similar to something I already do, so pretty easy to help.

**Comment by dail8859** [comment]
> everybody thinks the specific way they want to do things should be made a feature in the standard product.

Which is why I (and obviously you, and several others) are huge proponents of customizing through scripting 👍

**Comment by sasumner** [comment]
This bit of code should do it.  Questions on it are welcome.  Basically, if you put this in Pythonscript's startup.py (or put it in another file and call it from startup.py), it will install a hook to the FILESAVED event to do the custom actions.  Specifically, given a file MYFILE.SQL, it will copy it, upon user-save, to:

`C:\Temp\NPP_Backup\MYFILE__2017-11-09_092856__MYCOMPUTERNAME.SQL`

    import os  # for os.sep
    import time
    import re
    from shutil import copyfile

    def callback_notepad_FILESAVED(args):
        backup_dir_path = r'C:\Temp\NPP_Backup'
        curr_buffer_id = notepad.getCurrentBufferID()
        notepad.activateBufferID(args['bufferID'])
        file_to_be_backedup_pathname = notepad.getCurrentFilename()
        match = re.match(r'(.+' + os.sep * 2 + r')([^.\r\n]+)(\..+)?', file_to_be_backedup_pathname)
        if match:
            dir = match.group(1)
            file_base = match.group(2)
            optional_dot_plus_ext = match.group(3)
            if optional_dot_plus_ext == None: optional_dot_plus_ext = ''
            mod_time = os.path.getmtime(file_to_be_backedup_pathname)
            mod_local_time = time.localtime(mod_time)
            mod_time_ymdhms_str = time.strftime("%Y-%m-%d_%H%M%S", mod_local_time)
            pc_name = os.environ['COMPUTERNAME']  # see https://stackoverflow.com/questions/799767/getting-name-of-windows-computer-running-python-script
            backup_file_pathname = r'{d}\{f}__{m}__{pc}{dpe}'.format(d=backup_dir_path, pc=pc_name, f=file_base, m=mod_time_ymdhms_str, dpe=optional_dot_plus_ext)
            #print 'backup_file_pathname:{0}'.format(backup_file_pathname)
            try:
                copyfile(file_to_be_backedup_pathname, backup_file_pathname)
            except IOError:
                notepad.messageBox('Error during file backup!\r\n\r\nDOES BACKUP DIRECTORY EXIST?:\r\n\r\nCheck this directory:\r\n"{0}\\"'.format(backup_dir_path))
        notepad.activateBufferID(curr_buffer_id)

    notepad.callback(callback_notepad_FILESAVED, [NOTIFICATION.FILESAVED])

**Comment by svsdeveloper** [comment]
Super, thanks a lot. This is what we are looking for! 

And yes, i know, that having a version control would be the best way for sure but it was not my decision to vote against. 
And so this script is helping a lot. Thank you!
