### ISSUE TITLE
Missed items in language files (even in English)

### ISSUE THREAD

**Issue by Timon34** [notepad-plus-plus/notepad-plus-plus#3875]
Text at screenshot has no other thanslation except English (current english.xml file doesn't contain these items)

![notepad](https://user-images.githubusercontent.com/15920911/32547062-09e7dcc4-c492-11e7-9176-5833ff0b8041.jpg)

**Comment by MetaChuh** [comment]
this has been added in newer versions of notepad++.

```
<DoCloseOrNot title="Keep non existing file" message="The file &quot;$STR_REPLACE$&quot; doesn't exist anymore.
Keep this file in editor?"/>
```

thank you for your help and best regards.

-----
```
general notes:

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).
please file an issue as easy to understand and reproducible as possible.

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
(no extra account is needed, just use your github account to sign in)
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)
