### ISSUE TITLE
Double-clicking-and-copy-dragging attempts lead to triple-clicked outcome

### ISSUE THREAD

**Issue by maemmott** [notepad-plus-plus/notepad-plus-plus#3876]
### Description of the Issue
I commonly want to double-click an item, and <ctrl>-drag it to copy it elsewhere, for example, an irritatingly untypable identifier.

Whenever I try this, it always fails. 
### Steps to Reproduce the Issue

The motions for 'double-click' and copy-drag are:
-- double-click
-- press-and-hold <ctrl>
-- click-again-and-drag

I've been typing for a few years.  It's quite quick.  It wouldn't surprise me if the 'click-again-and-drag' fell inside the 'wait for multiple clicks to cease' timeout.  I have set mine slightly longer than the Windows default.

### Expected Behavior

I expected a duplicate of the highlit word to be created and positioned at the end-point of the drag.

### Actual Behavior

The whole line of text got selected.

### Debug Information

Notepad++ v7.5.1   (32-bit)
Build time : Aug 29 2017 - 02:35:41
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10 (64-bit)
Plugins : NppTextFX.dll PluginManager.dll XMLTools.dll 

I can see that this is rather a fringe issue.  How many expect to select a word and drag-copy it elsewhere?
I can also anticipate that it might be rather hard to tackle.  I don't code in C++, only C#, and in the only case where I had to try to get to this level of detail (Silverlight), access to this detail of event wasn't available.  Perhaps it is more transparent in C++.
It seems to me that the key discriminator between the double-click-and-copy-drag, and a triple-click, is that the control key has been pushed down after the double-click, and before the click-to-drag.
This has been annoying me occasionally, for a few years, but only today did I get that 'moment of insight', where I realised what was happening mechanically.  Before today, I had developed a 'fog of confusion' over it: I knew it never worked, but I had never realised what alternative intention it was trying to fulfil.

**Comment by sasumner** [comment]
Should your "motions" list be?:
-- double left-click word
-- left-click and hold the selected area
-- optionally press ctrl to copy rather than move
-- drag to new location and release
(really I just deleted "click-again" in your third line, because I don't think it is correct)

So trying it myself (at least what I think you are doing), I didn't find it in any way odd or irritating, which makes me think that I am not doing it right ("right" being how you are doing it)....just trying to understand....

**Comment by maemmott** [comment]
Sorry for the delay in responding.
I missed out a word in my original report.  Where I wrote 'press-and-hold', I had intended to write 'press-and-hold <ctrl>'.  How unhelpful to have left it out.

It seems to me that the only way of distinguishing between:
1)  'double-click' on a word to 'select-word', then 'click-on-the-selected-word' to drag it
and
2)  'triple-click' on (a word which happens to be in) a line
.. is that timing of the <ctrl> key-press.
_If_ notepad++ does 'its own' double-click versus triple-click handling, then it seems possible to detect that intervention of the <ctrl> key-press between the second and third click.
But, if notepad++ delegates distinguishing double-click from triple-click to another system, then that other system might not provide any method for detecting the intervention of the <ctrl>-keypress during the multiple-clicking event.

Did I mention, I can work around this, by (forcing myself to) waiting some moments before the click-to-drag.  The 'natural' thing to do, is to ram all the physical motions as close together in time as possible, mouse-click, mouse-click, <ctrl>-keypress, mouse-click.  I'm pretty sure that that third mouse-click is falling within the wait interval for deciding 'that possibly-double click is actually a triple-click'.

**Comment by sasumner** [comment]
@maemmott 
I don't know if that is the "natural" thing.  I like to double-click, pause to make sure what is now selected is what I want, then click it and drag it somewhere else.  :)

**Comment by MetaChuh** [comment]
@maemmott 

the double click and drag timing works as designed and expected.

thank you for your help and best regards.

**Comment by sasumner** [comment]
@maemmott Maybe of some interest, or maybe not:  https://notepad-plus-plus.org/community/topic/17462/select-grab-and-move-faster-way
