### ISSUE TITLE
TextFX wrongly deletes last unique line on Sort lines, output unique lines

### ISSUE THREAD

**Issue by JMM72** [notepad-plus-plus/notepad-plus-plus#3877]
### Description of the Issue

On certain cases, when TextFX sorts lines while the setting 'output unique lines' is in effect, So far it's only on a certain set of steps with a careful editing, but it shows that there's something wrong in there and who knows when more lines could be deleted.

### Steps to Reproduce the Issue

1. Create a new document with four lines:
Word [C] (Data)
X-Word  [C] (Data)
Zword 2 [C] (Data)
Zword [C] (Data)
2. Ensure that settings in TextFX Tools 'sort ascending' and 'output unique lines' are enabled.
3. Select all text, TextFX Tools, Sort Lines (case sensitive).
4. Delete past the brackets on the last two lines, so the text looks like:
Word [C] (Data)
X-Word  [C] (Data)
Zword 2
Zword
5. Select all text, TextFX Tools, Sort Lines (case sensitive).
6. Last line is deleted.

### Expected Behavior

Last line should have been moved above third line.
### Actual Behavior

Last line was deleted

### Debug Information

Notepad++ v7.5.1   (32-bit)
Build time : Aug 29 2017 - 02:35:41
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : ON
Local Conf mode : OFF
OS : Windows 7 (64-bit)
Plugins : ComparePlugin.dll HTMLTag_unicode.dll mimeTools.dll NotepadStarterPlugin.dll NppCalc.dll NppColumnSort.dll NppConverter.dll NppExport.dll NppFTP.dll NppTextFX.dll PluginManager.dll ReloadButton.dll RunMe.dll 

This example is easily fixed by adding a last empty line after the fourth; then the line is not deleted. However the bug is not 'last line is deleted if there's not an empty line after it', because you can use any random text to sort and the last line is not deleted. I have also tried mimicking the behaviour without adding the brackets and parentheses, but again removing them from all lines doesn't show the bug. Moreover, if you do not sort first and then edit like this, the line is still not deleted. It's a strange combination of factors.

I first noticed it after applying a regular expression that removed any text past brackets in a list of names, that was causing an incorrect sorting order, and then the line being sorted in the wrong place disappeared on next sorting. (I know a bracket goes after numbers, the sorting was not bugged, it was just not happening as I needed.)

**Comment by dail8859** [comment]
This plugin is not maintained by the Notepad++ developers. This needs reported to the plugins author
