### ISSUE TITLE
mistaked error "permission denied"

### ISSUE THREAD

**Issue by nebaz** [notepad-plus-plus/notepad-plus-plus#3880]
### Description of the Issue
notepad cached permissions and I do not access to files.

### Steps to Reproduce the Issue
1. touch myFile
2. chmod 600 myFile
3. try to open myFile through plugin NppFTP of notepad++ (not root) and get error "Download of myFile failed"
4. chmod 666 myFile
5. try to open and also get error

### Expected Behavior
I can open myFile

### Actual Behavior
I do not have access to myFile

### temp solution
restart notepad++

**Comment by dail8859** [comment]
If you are using `chmod` are you on Windows?

**Comment by dail8859** [comment]
Oh gotcha should have realized that :)

This sounds like an issue with the NppFTP plugin and needs reported to the author of that plugin.
