### ISSUE TITLE
The N++ website seems to be down

### ISSUE THREAD

**Issue by DFrostedWang** [notepad-plus-plus/notepad-plus-plus#3881]
It's not strictly related to the product itself, but the website is down and there's no way to get the installer. You guys probably already know, but maybe not and I'm just trying to be helpful. :)

**Comment by DavidHansen-0x454d43** [comment]
The domain name is still registered (Expires On 2018-05-29), so I'm guessing its a problem with the webhost. 

@donho When you are looking at this issue, can you please also look at #3801 & #3540 also? 
There are many people that would like to contribute to documentation be cannot.

**Comment by KOLANICH** [comment]
BTW, why not to use GH pages for the website (it's static anyway)?

**Comment by dail8859** [comment]
Closing as everything appears to be functioning normally the past several hours.
