### ISSUE TITLE
Find a word in .html file

### ISSUE THREAD

**Issue by miklos25** [notepad-plus-plus/notepad-plus-plus#3884]
### Description of the Issue
Find function not makes yellow marking all hits or makes yellow mark another word.

### Steps to Reproduce the Issue

1. open a .html file, then Ctrl+F
2. type a word (eg. td), then "Find All in Current Document"
3. See the yellow marks in the lower wondow

### Expected Behavior
If the "Count" says 204 hits, I expect 204 yellow marks.
Like Ctrl+F> Mark tab >Find All makes 204 purple marks on rigt words
[1987foglal.txt](https://github.com/notepad-plus-plus/notepad-plus-plus/files/1463774/1987foglal.txt)

### Actual Behavior
Fewer right word are marked with yellow, or wrong words are marked with yellow

### Debug Information

Notepad++ v7.5.1   (32-bit)
Build time : Aug 29 2017 - 02:35:41
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10 (32-bit)
Plugins : ComparePlugin.dll mimeTools.dll NppConverter.dll NppExport.dll NppFTP.dll PluginManager.dll 

![npp_find](https://user-images.githubusercontent.com/33573236/32689971-d939989c-c6ee-11e7-8adf-5f123b31170e.png)

**Comment by sasumner** [comment]
I don't see any inconsistency with how the feature works and what your screenshot shows....can you maybe explain exactly where (in the screenshot) you aren't seeing what you expect to see?

**Comment by miklos25** [comment]
I expect yellow marks all the hits in the lower window (Find function). I made red circles in the picture where  I expect them. All the "td"-s and all the "TD"-s.
The upper window with purple highlights are correct, but it is the Mark function, not Find function.
![npp_findred](https://user-images.githubusercontent.com/33573236/32742098-a9761ebc-c8a8-11e7-9530-8431a8ed8d09.png)

**Comment by sasumner** [comment]
The "Find result" panel lists exactly one hit in each if its lines.  Notice that it has TWO line 10, TWO line 11, and at least FOUR line 20 (I think there will be 9 line 20 in total).  This is expected current behavior.  The way I think you expect to see it, there should be unique line #s in the Find result panel, with multiple yellow highlighting per line.  This is okay if you are making a feature/change request, but I still think what it shows is consistent with how it currently is designed to work.  Just pointing it out...

**Comment by dail8859** [comment]
As described above, this is working as intended.
