### ISSUE TITLE
Program freezes when searching in specific file

### ISSUE THREAD

**Issue by fjay69** [notepad-plus-plus/notepad-plus-plus#3885]
### Description of the Issue
Program freezes when searching in specific file.

### Steps to Reproduce the Issue
Open this file https://yadi.sk/i/XCUqWFOG3PYUX4, and Ctrl+F for "励". First times clicking "Find next" goes fine, but then program is freezing.

**Comment by fjay69** [comment]
Checked v.7.5.1 64-bit

**Comment by MetaChuh** [comment]
please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins if you update from version 7.5.9 or below.
if your issue still persists, and it is still of relevance, please feel free to file a new issue as easy to understand and reproducible as possible.

thank you for your help and best regards.
