### ISSUE TITLE
When there are splited windows, N++ will crash to toggle fullscreen

### ISSUE THREAD

**Issue by yehuohan** [notepad-plus-plus/notepad-plus-plus#3886]
### Description of the Issue
When there are splited windows, N++ will crash to toggle fullscreen.

### Steps to Reproduce the Issue
1. Split windows
2. Press <F11> to toggle fullscreen or from view.

### Expected Behavior
Be fullscreen.

### Actual Behavior
Crashed.

### Debug Information
Notepad++: a free(GNU) source code editor 已停工作（In Englist: had stoped work）.

**Comment by dail8859** [comment]
Please post your debug info and any additional information you have because it is working fine for me.

**Comment by yehuohan** [comment]
Thank you. I found the problem from the crash information. That's because the HexEditor plugin. Remove HexEditor and fullscreen will work fine.

And I test that in windows8.1 with N++7.5.1.0.
