### ISSUE TITLE
Notepad++ keep crashing while loading the xml file

### ISSUE THREAD

**Issue by lancelim002** [notepad-plus-plus/notepad-plus-plus#3887]
### Description of the Issue

Notepad++ unable to detect the appropriate format that should be included for each theme file. In our input file, we have simply entered the Unicode characters of "\u0042" (translated to latin character 'B') multiple times. Due to the incomplete format of the xml theme file, Notepad++ will not be able to successfully compile the theme file, and result in an unhandled exception error.

### Steps to Reproduce the Issue

1. Create an input file with following input:
"\u0042\u0042\u0042\u0042\u0042\u0042\u0042\u0042\u0042\u0042"
2. Save it in an Extensible Markup Language(XML) format
3.  Close notepad++
4. Copy xml file to into the specified the path:
C:\Users\”user”\AppData\Roaming\Notepad++\themesC:\Users\”user”\AppData\Roaming\Notepad++\themes
5. Open notepad++
6. Click Setting -> Style Configurator ->Select theme
7. Choose input (input.xml)
8. Click Save & Close

### Expected Behavior

It should show a display of warning error saying that is an invalid format and allow the user to rectify the input.

### Actual Behavior

Notepad++ just crashes repeatedly.
### Debug Information

I have used Microsoft Visual Studio debugger 2015 and the error says "Unhandled exception at 0x002d251b in notepad++.exe: 0xC000041D: An unhandled exception was encountered during a user callback.”

**Comment by nlsdg** [comment]
Is there a schema for the style files? (I couldn't find it.) If there is, or someone makes it, it would be possible to check the input xml file against the schema. If it doesn't conform refuse to load the style.

**Comment by donho** [comment]
Please get the Debug Information from menu "?->Debug Info..."

**Comment by MetaChuh** [comment]
please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins if you update from version 7.5.9 or below.
if your issue still persists, and it is still of relevance, please feel free to file a new issue as easy to understand and reproducible as possible.

thank you for your help and best regards.
