### ISSUE TITLE
Character Escaping within the file tab

### ISSUE THREAD

**Issue by Yourealizardharry** [notepad-plus-plus/notepad-plus-plus#3888]
### Description of the Issue
File names with special characters are read properly by notepad++, but displayed properly not by the filename tab.

### Steps to Reproduce the Issue
1. Create a file called "1 & 2.[any extension]"
2. Open it in Notepad ++
3. Look at the filename tab.

### Expected Behavior
A filename to be shown that matches the filename.

### Actual Behavior
The & is not escaped, so the filename reads "1 _2".

**Comment by moisesJurado** [comment]
It is working for me. 
![image](https://user-images.githubusercontent.com/9367899/32730690-e48bded6-c855-11e7-952f-99ac4485d5a0.png)

**Comment by Yourealizardharry** [comment]
Ah, I tried to be helpful but forgot to check the version.

We have an old version deployed on our IT.

![bug](https://user-images.githubusercontent.com/33623918/32733962-fa8d7e34-c890-11e7-8c11-cd7e8c98d37a.png)
