### ISSUE TITLE
Notepad++ automatically changing files from ANSI to UTF-8

### ISSUE THREAD

**Issue by cfuselier74** [notepad-plus-plus/notepad-plus-plus#3889]
Current Version: 7.5.1

When I open a file in Notepad++ regardless of the encoding of the file Notepad++ is defaulting to UTF-8 and when I save the files it is causing issues as I need the files to be encoded with the correct version.

### Steps to Reproduce the Issue
Pre-req: file saved in ANSI

1. Open file in Notepad++
2. Validate Encoding of file. Notice it is set to UTF-8
3. Save the file. 

### Expected Behavior
File should be saved with original encoding

### Actual Behavior
File is saved in UTF-8

### Debug Information

Notepad++ v7.5.1   (32-bit)
Build time : Aug 29 2017 - 02:35:41
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 7 (64-bit)
Plugins : HTMLTag_unicode.dll ImgTag.dll JSLintNpp.dll JSMinNPP.dll mimeTools.dll NppConverter.dll NppExport.dll NPPJSONViewer-win32.dll PluginManager.dll XMLTools.dll

**Comment by dail8859** [comment]
Do you have  `Settings > Preferences > New Document > Encoding > UTF-8 > Apply to opened ANSI files` check marked?

**Comment by cfuselier74** [comment]
Hi,
That was the issue.
Thank you.

**Comment by RahlForge** [comment]
Thank you! Solved my problem, too!

> Do you have `Settings > Preferences > New Document > Encoding > UTF-8 > Apply to opened ANSI files` check marked?

**Comment by ChairmanMeowJP** [comment]
I'm having the same issue but I cannot find "Do you have Settings > Preferences > New Document > Encoding > UTF-8 > Apply to opened ANSI files check marked?"

**Comment by sasumner** [comment]
>cannot find...

Even someone as dumb as me can follow that progression (start in Settings menu):

![image](https://user-images.githubusercontent.com/30118311/56749363-94eabd80-674f-11e9-97c6-be827a482bc4.png)
