### ISSUE TITLE
Freezing

### ISSUE THREAD

**Issue by buggsdummy** [notepad-plus-plus/notepad-plus-plus#3891]
### Description of the Issue

This has been freezing pretty consistently 

### Steps to Reproduce the Issue

1. Leave something unsaved or saved and move around windows and try to go back to it
2. 
3. 

### Expected Behavior

Not to freeze

### Actual Behavior

Freezing not responding till after 2 seconds

### Debug Information

Notepad++ v7.5.1   (32-bit)
Build time : Aug 29 2017 - 02:35:41
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10 (64-bit)
Plugins : mimeTools.dll NppConverter.dll NppExport.dll PluginManager.dll

**Comment by Cajs** [comment]
+1, Also getting this issue. 

Cannot actually seem to reproduce it, just seems to freeze as I'm using it.

I'm using Window 10 64bit with version 7.5.1 (32bit) Aug 29 2017 - 02:35:41

**Comment by SchwiftyPython** [comment]
I have this problem on my home PC (WIndows 7 x64) and my work PC (Windows 10 x64). 
It's guaranteed to be unresponsive if I leave it open and not touch it for a few hours.

**Comment by stomydent** [comment]
+1, Also getting this issue. Just moving back and forth between browser and npp window.

**Comment by cisbrh** [comment]
+1 however if the find window is open the problem disappear...

**Comment by codeowl1** [comment]
+1 I am also getting this issue.  Very frustrating.....

**Comment by MetaChuh** [comment]
please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins if you update from version 7.5.9 or below.
if your issue still persists, and it is still of relevance, please feel free to file a new issue as easy to understand and reproducible as possible.

thank you for your help and best regards.
