### ISSUE TITLE
I think the undo option is reverting changes on complete page of code or file,but my suggestion is if we select the particular line then it has to undo for that particular line only 

### ISSUE THREAD

**Issue by prashantraut1992** [notepad-plus-plus/notepad-plus-plus#3894]
### Steps to Reproduce the Issue

1. 
2. 
3.

**Comment by dail8859** [comment]
This is the way every undo feature works that I know of. It operates on the entire file. If you need to undo changes line by line you probably need some sort of version control (such as git) for tracking changes in your files.
