### ISSUE TITLE
Add "Prompt to Save File on Exit" preference

### ISSUE THREAD

**Issue by einst3** [notepad-plus-plus/notepad-plus-plus#39]
Some where there should be a "Prompt to Save File on Exit". It asks you to save a file on exit when you have "Enable settings snapshot and periodic backup" turned off in the "Backup" preferences but it does not ask you to save the file on exit if you have the preference turned on. Maybe add it as a separate option under it or as a global "Misc" setting.

**Comment by MetaChuh** [comment]
closed due to inactivity (3y)
