### ISSUE TITLE
Font-Size with 4k/1k Multi-Monitor Setup

### ISSUE THREAD

**Issue by user-cw** [notepad-plus-plus/notepad-plus-plus#3900]
### Description of the Issue
Font-size or -scaling is inconsistent.

### Steps to Reproduce the Issue
1. Use a computer/notebook with 4k resolution and triple-monitor setup (dual screen might work too)
2. Set resolution of all displays to full HD (1920x1080) with scaling of 100%

### Debug Information
see screenshots:

![npp_issue_01](https://user-images.githubusercontent.com/20438979/33016972-d8b190f6-cdf0-11e7-8f10-eac607b702ce.png)
![npp_issue_02](https://user-images.githubusercontent.com/20438979/33016973-d8e02ace-cdf0-11e7-896f-75cf015a9c62.png)

**Comment by MetaChuh** [comment]
i can not reproduce this on windows 10 using notepad++ 7.6.6. with 2-3 displays set to 1920x1080 and 100% scaling.

please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins if you update from version 7.5.9 or below.

thank you for your help and best regards.
