### ISSUE TITLE
Consider adding an "on demand" vertical guideline

### ISSUE THREAD

**Issue by DedicatedTools** [notepad-plus-plus/notepad-plus-plus#3902]
May I suggest an "on demand" vertical guideline (edge), which can be toggled on and off, at the current cursor position.

At times I need to align text on different lines that are far apart from each other. The workaround is to notice the cursor position in one line, then place the text at the same position in the other line.
It would be great to be able to place the cursor at the position I'd like the text to be aligned at, press a key-combination/shortcut to toggle on a vertical guideline that is visible throughout the entire file (top to bottom, similar to the vertical edge) and align the text in the other line according to the guideline. Once done I could press the same key-combination/shortcut to make the guideline disappear.

**Comment by sasumner** [comment]
FWIW, this is a one-liner using the Pythonscript plugin:
`editor.setEdgeColumn(editor.getColumn(editor.getCurrentPos()))`

...or okay, a bit more if you want it to toggle on/off, but I'd say use it and then put it away at column 1 when you are done.  :-)

**Comment by DedicatedTools** [comment]
@sasumner ,
Thank you very much. I just installed Pythonscript plugin and added your command as a new script.
It does work. However, it moves the "original" vertical edge (which I still need ;-) to the new position. To move it back to the place it used to be, I have to "fix" the preferences. I was hoping this will add a "new" guideline. It's OK to move it to the 1st position too (vs. turning it off).

**Comment by sasumner** [comment]
I'm not 100% sure on this but I think Scintilla (which Notepad++ uses as its underlying text editing component) only supports a single vertical edge.  I could be wrong, but if not then your feature request would have to go to the Scintilla feature request process before N++ could even consider adding it.

Regarding "move it back", the Python code could be changed to toggle between where you want it NOW and where you want it NORMALLY.  :-)

**Comment by DedicatedTools** [comment]
@sasumner ,
I see. I wouldn't know how to find out what N++ is using to display the vertical edge...
On your suggestion about toggling the vertical edge between "now" and "normal", I created another script to set back to "normal":

editor.setEdgeColumn(120)

Now I need to map these 2 scripts to individual key-combinations/shortcuts (otherwise it's even more work than in my initial workaround ;-). I checked "Plugin commands" tab under "Shortcut mapper" window, but found no options for individual scripts. Any suggestions?

Again, thank you for your time and help.

**Comment by dail8859** [comment]
> I'm not 100% sure on this but I think Scintilla (which Notepad++ uses as its underlying text editing component) only supports a single vertical edge.

The current version of Scintilla (v3.5.6) only supports one vertical edge. However newer versions of Scintilla (v3.7.0+) supports multiple edges.

I'll close this issue for now since this feature probably wouldn't be that useful to alot of people, and the PythonScript is a good solution to the problem. You are welcome to continue the discussion here or on the forum.

**Comment by sasumner** [comment]
@DedicatedTools 
See here for how to assign keyboard shortcuts so that they run Pythonscripts:  https://notepad-plus-plus.org/community/topic/14703/run-python-script-pythonscript-plugin-with-a-shortcut
It seems like you now have a pretty good solution...maybe not ideal, but pretty good.  :)

**Comment by DedicatedTools** [comment]
@sasumner ,
Thank you so much. This is perfect. I now have Ctrl+Alt+E for setting vertical edge at the current cursor position, and Ctrl+Alt+Shift+E for setting it to "normal" (in case someone looks for a "good" key combination). I'm off to learning some Python now ;-) ...
Happy holidays everyone!
