### ISSUE TITLE
the bar flickers

### ISSUE THREAD

**Issue by bgo272** [notepad-plus-plus/notepad-plus-plus#3903]
I'm kind of new to programming and notepad++,and i found something that really annoys me.
when i move my cursor on the tab(not clicking or dragging) the upper tab flickers.
someone knows how to fix?
if i did something wrong like opening the thread in the wrong place,my apologies.
--tried to search for an answer and did'nt found-

**Comment by dail8859** [comment]
Not sure what you mean exactly but it works fine for me:

![tabs](https://user-images.githubusercontent.com/3694843/33047538-509e6b10-ce24-11e7-9242-84dcf97fab8e.gif)

Please reopen if you have any more details and try to follow the template so you can provide enough information to reproduce the issue.

**Comment by clarkleach** [comment]
I'm seeing something similar that has persisted over the last several updates.  The difference is that my 
cursor flickers between the "I" editing cursor and the arrow cursor whenever it's outside of an editing window.  This seems to only happen when notepad++ has been running for quite some time and goes away with a restart of notepad++. @dail8859 , I'm wondering what tool you use to capture video of portions of the screen like this.

**Comment by dail8859** [comment]
http://www.screentogif.com/

**Comment by clarkleach** [comment]
I captured this with movavi:

![notepad_glitch](https://user-images.githubusercontent.com/8323175/34954406-5640e52a-f9ee-11e7-8111-d80720b844db.gif)

**Comment by clarkleach** [comment]
I captured this with screentogif:

![notepad_pp](https://user-images.githubusercontent.com/8323175/34954810-d370256e-f9ef-11e7-9b50-2258cf0acd24.gif)

**Comment by dail8859** [comment]
Without a set of steps to reproduce it then there really isn't much to go on.
