### ISSUE TITLE
Can not load the dynamic library

### ISSUE THREAD

**Issue by operasfantom** [notepad-plus-plus/notepad-plus-plus#3904]
### Description of the Issue
Succesfully running -x86 configuration in Visual Studio 2015, but not on -x64

### Steps to Reproduce the Issue

1. nmake NOBOOST=1 DEBUG=1 -f scintilla.mak
2. run Visual Studio 2017
3. open notepadPlus.vcxproj
4. build -x64 Unicode Debug configuration (v140_xp)

### Expected Behavior
Succesfully running npp

### Actual Behavior
ScintillaEditView:SCINTILLA ERROR - Can not load the dynamic library

### Debug Information

Windows 10 (64 bit)

**Comment by dail8859** [comment]
This means that the SciLexer.dll file is not located in the correct location. It has to be in the same directory as the Notepad++ executable. If I recall the 64 bit build is in a fairly different location than the 32 bit build.

**Comment by operasfantom** [comment]
Excuыe me, but SciLexer.dll is contained in both directories

**Comment by dail8859** [comment]
Take a look [here](https://notepad-plus-plus.org/community/topic/14054/certificate-required-for-building-notepad) and see if that helps.

**Comment by dail8859** [comment]
Also if you are still having problems make sure you are building the `SciLexer.dll` file as 64-bit if you are using 64-bit Notepad++.
