### ISSUE TITLE
Trying to do a search and replace clicked on option to use extended search mode and put in the search \n\n to replace with \n it cannot seem to find two newlines and replace it with a single newline. I have tried restarting and reistalling but to no avail

### ISSUE THREAD

**Issue by Sirvice** [notepad-plus-plus/notepad-plus-plus#3905]
### Steps to Reproduce the Issue

1. 
2. 
3.

**Comment by sasumner** [comment]
Ok, so this isn't an "issue", this is you not knowing how to use the software.  In the future please don't clutter the already overwhelmed issues list with stuff like this.  This is a question and is best asked on either the Live Support forum (https://gitter.im/notepad-plus-plus/notepad-plus-plus) or the Community forum (https://notepad-plus-plus.org/community/), both of which you can access via the "?" menu inside Notepad++.

In the event you do have a true issue, to be taken seriously you have to follow the template for reporting an issue, not jam your issue details all in the title of the issue and leave the template empty.

Moderator:  PLEASE CLOSE THIS ISSUE.

Ok, so as to your real problem, it is very likely that you are editing files with Windows line endings, thus you have to search for `\r\n\r\n` and replace with `\r\n` to do what you are attempting in Extended search mode.
