### ISSUE TITLE
Feature request: Font, Font Style and Font Size options for Tabs in Style Configurator

### ISSUE THREAD

**Issue by vovkasolovev** [notepad-plus-plus/notepad-plus-plus#391]

**Comment by dg9ngf** [comment]
If only to get rid of that badly readable MS Sans Serif from the old times. The rest of the UI seems to use 8pt Tahoma (better). From Vista on, the default font is 9pt Segoe UI (even better) which is used for the menu only.

**Comment by MetaChuh** [comment]
closed due to inactivity (4y)

**Comment by vovkasolovev** [comment]
🤷‍♂️

**Comment by ygoe** [comment]
I guess the Notepad++ codebase is so old it's impossible to maintain it and bring it to today's standards. It would probably require a complete rewrite of the GUI to make it support today's needs such as high DPI, multi-monitor DPI, adaptive i18n text layout and accessibility. Nobody is going to do that. A new editor application has to be created.

**Comment by vovkasolovev** [comment]
Tabs already have color style settings in Style Configurator, and only don't have some font settings that is grayed right now. (Other elements have both color and font settings).
