### ISSUE TITLE
FunctionList (classRange parser?) - single line comment is broken

### ISSUE THREAD

**Issue by dimaal** [notepad-plus-plus/notepad-plus-plus#3910]
Notepad v. 7.5.2. (32 bit)
Windows 7 SP1 Professional

### Steps to Reproduce the Issue

Having Java as the selected language, the function list correctly parses this java class :

```
public class Car
{
	public int doSomething (int num)
	{
		return 1;
  	}
}
// something must be here ;)
```
add one commented out line now:

```
public class Car
{
//}  -- this line breaks the function list parser
	public int doSomething (int num)
	{
		return 1;
  	}
}
// something must be here ;)
```
### Expected Behavior
line `//}  -- this line breaks the function list parser` should be ignored

### Actual Behavior
the function list is broken.

This behaviour can be observed with other classRange based languages, with or as well without  open/closeSymbole in the classRange definition.

**Comment by encore0117** [comment]
Can you show the screenshot of the function list you are getting?

It seems find on my end.

**Comment by encore0117** [comment]
[This website](https://notepad-plus-plus.org/community/topic/12691/function-list-with-java-problems) shows the issue is known and has been working on.

**Comment by operasfantom** [comment]
Why ScintillaEditView::setLineIndent does call when you print '}', but not after pasting '}' for example? Where does it refresh?

**Comment by dimaal** [comment]
@encore0117 
> This website shows the issue is known and has been working on.

As i wrote, this issue is not only Java (java parser) relevant - it can be observed on every single language

**Comment by operasfantom** [comment]
Another interesting case
![default](https://user-images.githubusercontent.com/31903947/33171021-a0fe12b6-d05b-11e7-82b0-e0a6ec7a7aa8.PNG)

**Comment by operasfantom** [comment]
I repaired that in LexCPP.cxx (scintilla folder). This file is also responsible for Java :D

**Comment by dail8859** [comment]
@operasfantom That's not a bug. That's a feature of Scintilla.

**Comment by dimaal** [comment]
@operasfantom 
I  think you have repaired some other problem (folding?). 

As i wrote, this issue is not only Java/C++ relevant - it can be observed on every single language with the class parser (User defined languages also - here i've seen this issue the first time and have thought my parser had an error) and has nothing to do with folding but with the internal logic of the function list parser.

**Comment by operasfantom** [comment]
@dail8859  Why do you think so?

**Comment by dail8859** [comment]
@operasfantom See https://sourceforge.net/p/scintilla/bugs/1676/

This is a bug report on the Scintilla tracker.

**Comment by operasfantom** [comment]
@dail8859 Hmm... But how can I disable feature in Notepad++ setting?

**Comment by dail8859** [comment]
To turn it off you have to set the lexer property. To do that you either need to modify the Notepad++ sourcecode, similar to this section:

https://github.com/notepad-plus-plus/notepad-plus-plus/blob/c978a18894228e1265428253011ef5814b97088f/PowerEditor/src/ScitillaComponent/ScintillaEditView.cpp#L948-L952
---
Or you can set this property with a plugin, such as using LuaScript and running:

```lua
editor.Property["fold.cpp.comment.explicit"] = "0"
```

**Comment by operasfantom** [comment]
OK, that's great! But I meant: what should user do in Notepad++ environment?

**Comment by dail8859** [comment]
Not type `//{` or `//}` I guess.  Not sure what you mean.

**Comment by dail8859** [comment]
This 'feature' of scintilla has now been turned off by default. 33a0587a65fb19a67068c5f9556fa8b43727e62a
