### ISSUE TITLE
Missing the last part in the clickable links

### ISSUE THREAD

**Issue by WagnerGMD** [notepad-plus-plus/notepad-plus-plus#3912]
```
## Just a few examples :
https://duckduckgo.com/?q=windows+delete+"GameBarPresenceWriter.exe"
https://duckduckgo.com/?q=windows+delete+"GameBarPresenceWriter.proxy.dll",
## The cause seem's to be : "
## The links are broken because it will open the same url :
https://duckduckgo.com/?q=windows+delete (as you can see the filename is missing)
```
Hello,

in fact, the link won't be open (not with the complete request). Because Notepad++ didn't see the last part (I'm meaning the filename just after **+"**)
Then I'm wonder if you could correct the trouble ? With Notepad++_v7.5.1 the links aren't fully recognize.

Kind regards.

**Comment by operasfantom** [comment]
What file extension do you use?

**Comment by WagnerGMD** [comment]
Usually, it's the **Normal Text File** (by default when I create new .txt file). But I had try also with Python (and as you can guess none change).
