### ISSUE TITLE
Default folder in Find In Files

### ISSUE THREAD

**Issue by T3rm1** [notepad-plus-plus/notepad-plus-plus#3913]
One of the most annoying things to do when you want to use the find in files dialog is to set the folder in which to search.
In 99,99% of all cases I open a file and want to search in the directory or in any subdirectory of that file. 

Please set the default folder to the one of the currently opened file.

**Comment by sasumner** [comment]
It would be totally awesome if, on the Find in Files dialog, maybe near the area where you set the folder to search in, if there was maybe a checkbox (suggested name: "Follow current doc") that would pre-populate the folder edit box with the path of the currently active file.

**Comment by T3rm1** [comment]
Oops, you are right.
