### ISSUE TITLE
batch coloring problem

### ISSUE THREAD

**Issue by niviman** [notepad-plus-plus/notepad-plus-plus#3915]
In batch if-else clauses, np++ colors the parentheses in "else (" only if they are changed to "else do (", however, else does not require a "do", and might in fact intrefere it.

**Comment by operasfantom** [comment]
What programming language do you use?

**Comment by sasumner** [comment]
@operasfantom I believe that @niviman is talking about Windows' Batch files programming language.  https://en.wikipedia.org/wiki/Batch_file

**Comment by niviman** [comment]
@sasumner True, if you can call that a programming language ;)

**Comment by sasumner** [comment]
@niviman I don't judge!  :)

**Comment by encore0117** [comment]
I guess if the text is "else(", the parenthesis will change color? ( meaning without the space in between )

**Comment by niviman** [comment]
@encore0117 false, and that will also raise an error.

**Comment by ArkadiuszMichalski** [comment]
@niviman Do you still have this problem in latest Notepad++ version? If yes then put some example as code.

**Comment by niviman** [comment]
@ArkadiuszMichalski 
hi, i don't recall which code caused the last problem, but for example, the following code:
```
@echo off
echo 1
if (1==1) (echo "hi") else (echo "hello")
```
colors "(echo" in blue, and by adding spaces anywhere you can tell the code is not consistent.
using version 7.9 (currently latest)

**Comment by ArkadiuszMichalski** [comment]
@niviman Thx, this was fixed in Scintilla, probably by https://sourceforge.net/p/scintilla/bugs/1997/. In the latest SciTE it works fine, so we are waiting for Notepad ++.

Last SciTE:

![test](https://user-images.githubusercontent.com/2730894/94993319-60a83d00-0590-11eb-877c-7d85fde6a7a0.gif)

**Comment by vinsworldcom** [comment]
@donho 
@sasumner 

I can confirm this is fixed in Notepad++ 7.9.3 Unicode Debug using the latest Scintilla 4.4.6 DLL.

Cheers.

**Comment by sasumner** [comment]
Closing based upon @vinsworldcom confirmation.  Thanks!
