### ISSUE TITLE
Macro repetition failing randomly

### ISSUE THREAD

**Issue by rogeriodec** [notepad-plus-plus/notepad-plus-plus#392]
This image shows the problem:
A single macro containing some keystrokes to create a batch file to rename some files.
Several lines are faulty.
This happens if I press "ctrl +shift+p" too fast or if I use automatic repeat macro.
If I wait a minimum time between each ctrl + shit + p, the problem does not happen.

![2015-07-02_150713](https://cloud.githubusercontent.com/assets/11199752/8484098/fd2aad02-20cb-11e5-9f7c-52ac4243c884.jpg)

This is an old bug that so far has not been resolved.

**Comment by sampalmer** [comment]
I just tried to reproduce this using some of your data in Notepad++ 7.2 under Windows 10. Does this problem still happen?

**Comment by chrisblizz** [comment]
I have encountered the same problem under Windows 10. Using the same Notepad++ and macro under Windows 7 everything is fine.

**Comment by r3d-shift** [comment]
I encountered this issue today. A screen recording is available here:  https://1drv.ms/u/s!Ak-E89g_B8i_uTiMN4qb8mbRlX8B

My macro was configured to copy the text on a given line then paste the number thrice, with a tab character between each (creating four total columns with the same text in each column).

The macro appears to have missed pasting the copied data in the third "column," as you can see in the video.

**Comment by donho** [comment]
Update your Notepad++ to v7.6.6.
If this bug persists in the new release, please open a new issue with the debug information.
