### ISSUE TITLE
Rename "utf8" to "utf8 with bom" in main menu

### ISSUE THREAD

**Issue by Yanpas** [notepad-plus-plus/notepad-plus-plus#3926]
Everywhere in the program there are encodings "uft8" and "utf8 with bom", but in the main menu the naming is inversed.

Language russian.

**Comment by milbrandt** [comment]
Same issue in German language of 7.5.5. 
id="6407" name="UTF-8 ohne BOM"
id="45005" name="UTF-&amp;8-BOM"

**Comment by MetaChuh** [comment]
the russian utf-8 translation inconsistencies have been fixed.

<img width="904" alt="" src="https://user-images.githubusercontent.com/45773305/57287636-3fe86900-70b8-11e9-99b6-8f829b1040c0.png">

please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins if you update from version 7.5.9 or below.

thank you for your help and best regards.

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).
please file an issue as easy to understand and reproducible as possible.

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
(no extra account is needed, just use your github account to sign in)
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)
