### ISSUE TITLE
The vertical scrolling is broken (not smooth)

### ISSUE THREAD

**Issue by dibyenshu** [notepad-plus-plus/notepad-plus-plus#3932]
### Description of the Issue
The vertical scrolling is very jerky and jumpy. I have set the number of lines to scroll at a time 6, so whenever is use the touchpad to scroll there is a threshold of swipe(two-finger swipe)  on the touchpad after which it suddenly jumps 6(depends on system setting) lines instead of a smooth continuous action.
It can be reduced by setting the number of lines to scroll as 1 in the settings but this makes scrolling very slow in other applications hence not an option.

### Steps to Reproduce the Issue

1. open a text file with minimum 2-3 pages 
2. keep the number of lines to scroll greater than 5 in settings to see the huge bug in action
3. use touchpad gesture to swipe (windows precision touchpad preferred) 

### Expected Behavior
The vertical scrolling should work as the horizontal scrolling on the touchpad/ trackpad.

### Actual Behavior
The vertical scrolling is broken as instead of scrolling smoothly it jumps multiple lines at a time

###It is a game changer as it turns me off from using it as my daily text editor as I can't keep up with the scrolling in the long text files.

#Update:
The issue seems to be with Scintilla. I used SciTE and the same problem existed but with sublime, the problem doesn't exist.

**Comment by Hydroque** [comment]
Smooth scrolling is really unrelated and the reason I switched from chrome to firefox and I love firefox then and love it even more now since their big overhaul recently that set it way over Edge and Chrome

**Comment by dibyenshu** [comment]
@Hydroque I don't know how you think the smooth screen is unrelated but while scrolling through thousands of lines of code line by line if I am unable to follow the lines while scrolling it is just enough for me to think about something else or some other editor.

**Comment by Hydroque** [comment]
Oops underrated*

**Comment by MetaChuh** [comment]
the scrolling behaves as designed at the implemented scintilla component.

thank you for your help and best regards.

**Comment by Enlight432** [comment]
@dibyenshu
I have the same problem, did you find a solution sir?
