### ISSUE TITLE
Wrong tab focus - very annoying 

### ISSUE THREAD

**Issue by smqureshi** [notepad-plus-plus/notepad-plus-plus#3934]
### Description of the Issue

1 - On opening a file from a folder, focus goes to another tab/file that is to be reloaded (after changes from another source).
2 - A file/tab is opened and np++ focus lost, back to np++, focus should be on opened file but it again goes to file/tab that is changed by another source.
### Steps to Reproduce the Issue

1. 
2. 
3.

**Comment by chcg** [comment]
This might be a duplicate of #1087 (Do not switch tab on file modification).
and another dup: #3160 focusing on changed file issue

**Comment by Cerno-b** [comment]
There is a commit which resolves this issue in #1087, but it's not in the release yet
