### ISSUE TITLE
NppFTP: Save to FTP periodically fails, followed by FTP directory list failure

### ISSUE THREAD

**Issue by MCLoweDallas** [notepad-plus-plus/notepad-plus-plus#3937]
### Description of the Issue

When editing an online source (.php for example) and making frequent changes, the file is uploaded to the remote host automatically every time you save the file in NPP.  This also causes a refresh of the list of remote files in the NppFTP window.

Seemingly unrelated to the time since a previous save (it can be seconds or minutes or more) this post-save upload will fail, producing the following error in red in the output window:

Upload of C:\Users\xxxxx\AppData\Roaming\Notepad++\plugins\Config\NppFTP\Cache\xxx@yyy.com\public_html\zzzz\jobs\qqq.php failed

But if you immediately make an arbitrary change to the file (like adding then removing a space) and save it again, it will upload this time, but then the directory listing will fail to populate, producing the following red failure text in the output window:

Failure retrieving contents of directory /public_html/zzzz/jobs

and leading to another quick change and save to the file to repopulate the directory listing.

It appears as if we have lost the connection to the FTP host, but the plugin should handle that and reconnect and deal accordingly as it usually does.

When this occurs, a partial version of the file is left on the remote server that can't be executed.  In fact, your first clue that something isn't right is usually when you try to display said .php file in a browser.  All you will see is a white page and a blank stare from your browser.

The serious downside of this bug is that you have to meticulously make sure each save uploads properly or you risk losing changes you just made if you close the file and walk away after a failed upload.  When you're in the heat of it, you don't always look down and notice that it failed, because 99% of the time it works!  NOT GOOD!!!!!

### Steps to Reproduce the Issue

1. Edit a file all day long and save from time to time.
2. Wait for the post-save upload to fail.
3. I know these steps suck.  But this is the nature of the issue.  :-)

### Expected Behavior

Whenever I save the file locally, it should also be completely uploaded to the remote FTP server, dealing with connection issues as necessary.

### Actual Behavior

A partial version of the file is left on the remote server (which will not properly execute in the case of PHP) and I have to force a new save and remote directory population.

### Debug Information

Notepad++ v7.5.1   (32-bit)
Build time : Aug 29 2017 - 02:35:41
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 8.1 (64-bit)
Plugins : ComparePlugin.dll mimeTools.dll NppConverter.dll NppExport.dll NppFTP.dll PluginManager.dll 

I guess I will have to continue to deal with this issue, because I see there are hundreds (thousands) of issues and mine is just one tiny little one.  :-D

**Comment by sasumner** [comment]
NppFTP is not distributed with Notepad++.  Thus bug reporting for it doesn't belong here anyway (only N++ and packaged plugins issues belong here).  Suggest you contact author of NppFTP.  The upside is that the issues list for that plugin is likely shorter than this one.  :)  If you suspect this is some sort of interaction issue between N++ and the plugin (can't tell, don't use it myself), then I suppose the issue belongs in both places.

**Comment by dail8859** [comment]
As suggested please report this the to developer of NppFTP to have them investigate this, and reopen if it is anything N++ related.
