### ISSUE TITLE
v7.5.2: View > Summary is Crippled

### ISSUE THREAD

**Issue by Doryforos** [notepad-plus-plus/notepad-plus-plus#3939]
Up to v7.5.1 View > Summary displayed full file path, creation and modification dates and file size in bytes on top of the text statistics. This is no longer the case in v7.5.2:

### Steps to Reproduce the Issue

1. Install Notepad++ v7.5.2
2. Open a text file
3. Select View > Summary from the Notepad++ menu bar

### Expected Behavior [screenshot from v7.5.1]
![6 2 2-summary](https://user-images.githubusercontent.com/894977/33406329-f322fe9e-d574-11e7-9d53-b1b48d28f20b.jpg)

### Actual Behavior [screenshot from v7.5.2 (same file)]

![7 5 2-summary](https://user-images.githubusercontent.com/894977/33406347-0f73f2ba-d575-11e7-88b7-1d51515e8fa8.jpg)

Clearly a bug, since no such change is mentioned under “Notepad++ v7.5.2 bug-fixes and enhancement” on the download page.

**Comment by sasumner** [comment]
Works okay for me (7.5.2 x86 portable).  What you are seeing is consistent with the operation on a never-saved file, for what that's worth.  The stuff you aren't seeing is generated inside the following "if" block:

```
int fileLen = curBuf->getFileLength();
if (fileLen != -1)
{
// generate file-system info about the file
}
```

For a never-saved file getLength() will return -1.  Not saying this is what you're seeing, just my observations.

**Comment by Doryforos** [comment]
I would not expect a file path for a never-saved buffer!

My system is MS-WinXP-SP3+Updates, same as what I had installed v7.5.1 on and up to v7.5.1 things were normal.

**Comment by Doryforos** [comment]
v7.5.9 on MS-WinXP-SP3+Updates [32bit] — still!
Fixed, for me.
