### ISSUE TITLE
7.5.2  x32.. crashed just deleting some text.

### ISSUE THREAD

**Issue by aj664** [notepad-plus-plus/notepad-plus-plus#3940]
### Description of the Issue
select some text.  press delete key..  long pause.   crash.

### Steps to Reproduce the Issue
1.  select some text
2. press delete key
3. crashed

### Expected Behavior
no crash

### Actual Behavior
crashed.

### Debug Information
Notepad++ v7.5.2   (32-bit)
Build time : Nov 27 2017 - 00:13:16
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 7 (64-bit)
Plugins : ComparePlugin.dll DSpellCheck.dll HexEditor.dll JSLintNpp.dll JSMinNPP.dll mimeTools.dll NppConverter.dll NppExport.dll NppFTP.dll NppTextFX.dll PluginManager.dll switcher.dll Tidy2.dll XMLTools.dll

**Comment by aj664** [comment]
tried again,  this time  instead of pressing delete.  pressed spacebar (to replace the selected with a single space char..   no crash.

**Comment by SinghRajenM** [comment]
Could not reproduce. Check it again without plugins. you can just rename plugins folder (C:\Program Files (x86)\Notepad++\plugins) and check.
Later you can rename it again as "plugins".

**Comment by dail8859** [comment]
Cannot reproduce. If this happens again I'd recommend disabling plugins to see if it one of those causing the issue.
