### ISSUE TITLE
NSIS Language color sheme - single quote unreadable

### ISSUE THREAD

**Issue by movedoa** [notepad-plus-plus/notepad-plus-plus#3941]
### Description of the Issue
The NSIS color sheme has a problem with single quoted strings.
Text in single quotes is just white and therefore very hard to read in most conditions.
The editor makes the background darker when the cursor is not in the line but while editing the text is unreadable.

### Steps to Reproduce the Issue
Set language to NSIS and type in some text in single quotes

### Expected Behavior
Single quoted strings should have a readable color

Here is a screenshot of the problem:
![grafik](https://user-images.githubusercontent.com/13309951/33433161-d52dff5e-d5da-11e7-93d2-51bd8acf9ce9.png)

**Comment by SinghRajenM** [comment]
@movedoa looks like this is no longer an issue in latest version.

**Comment by dail8859** [comment]
![image](https://user-images.githubusercontent.com/3694843/58298041-05fdaf00-7da8-11e9-95b7-15a097a8305b.png)
