### ISSUE TITLE
v7.5.2: File is changed by Another Application but Notepad++ does not detect this

### ISSUE THREAD

**Issue by Doryforos** [notepad-plus-plus/notepad-plus-plus#3944]
### Description of the Issue
File is changed by another application but Notepad++ v7.5.2 does not detect this; file needs to be reloaded manually, even though Settings > Preferences > MISC. > File Status Auto-Detection > Enable is checked.

### Steps to Reproduce the Issue

1. Open a file in Notepad++ v7.5.2 while having enabled the File Status Auto-Detection, as above
2. Open the same file in another application, change something and save the file
3. Switch to Notepad++

### Expected Behavior
Notepad++ v7.5.2 should pop a dialogue box up, telling the file has changed and offering to reload it.

### Actual Behavior
Notepad++ v7.5.2 does nothing; the file has to be manually reloaded for the changes to be visible by the application.

**Comment by DavidHansen-0x454d43** [comment]
I feel certain I have seen this before too, but it doesn't happen often. I just tried to reproduce it and failed (N++ 7.5.1 working as expected). 

Can you give us some more details about how you are reproducing? 
- Debug Info...
- What external application are you editing with? 
- What file type are you editing?

**Comment by Doryforos** [comment]
v7.5.1 [on MS-WinXP-SP3+Updates, same as what I have installed v7.5.2 on] worked for me as well.

I don’t know how to get the debug info, kindly tell me.

Whatever other application I ever used, Notepad++ worked fine up to v7.5.1.

Happens with any plain text file [csv, log, txt, html, hash files which I save with an extension respective to the algorithm used (.MD5, .SHA1, …)], either ANSI or UTF-8.

**Comment by DavidHansen-0x454d43** [comment]
@Doryforos you can access the debug information from inside Notepad++, by going to the menu -> ? -> Debug Info...

It seems really strange it works on 7.5.1, but not on 7.5.2. As far as I can tell there, there is only one 1-line change between the two version. 

Can anyone else confirm its not working on 7.5.2?

**Comment by Doryforos** [comment]
Thanks!

Here it is:

>Notepad++ v7.5.2   (32-bit)
Build time : Nov 27 2017 - 00:13:16
Path : &lt;DriveLetter&gt;:\Program Files\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows XP (32-bit)
Plugins : DSpellCheck.dll Explorer.dll HexEditor.dll LightExplorer.dll mimeTools.dll NppConverter.dll NppExec.dll NppExport.dll NppFTP.dll NppTextFX.dll PluginManager.dll 

Nobody can confirm — or deny — this on my side.

**Comment by DavidHansen-0x454d43** [comment]
I wouldn't be surprised if this was an issue with XP...

**Comment by Doryforos** [comment]
I, on the other hand, would not be surprised if it was the same case as the following, reported by yours truly, which is still standing tall, two and a third years later:

>#534 **v6.8: Backward Search does not work for UTF-8 Characters in a [Normal] Text File**

see also:

>#3939 **v7.5.2: View > Summary is Crippled**

In other words, once again, some good — and expected! — functionality broken for no apparent reason, but hush-hush and will never fix.

Hence, I have uninstalled v7.5.2 and I am back to v7.5.1 — back to sanity — as good as it gets…

![7 5 1-modified-reload](https://user-images.githubusercontent.com/894977/33503409-471ae0de-d6ec-11e7-861e-0596e7e702c4.jpg)

Looking forward to be proven wrong… and growing old, torn and frayed… I’m afraid…

&lt;bitterSigh&gt;

**Comment by juntalis** [comment]
I've also been encountering this issue for the last few months. Assumed it was an issue that affected all users, and figured it'd be fixed in the next few updates, but no such luck.

```
Notepad++ v7.5.6   (32-bit)
Build time : Mar 19 2018 - 00:26:59
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : ON
Local Conf mode : OFF
OS : Windows 7 (64-bit)
Plugins : ActiveX.dll ComparePlugin.dll CustomizeToolbar.dll Explorer.dll JSLintNpp.dll JSMinNPP.dll mimeTools.dll NppFTP.dll NppTextFX.dll NppXmlTreeviewPlugin.dll PluginManager.dll PythonScript.dll SourceCookifier.dll Translate.dll XMLTools.dll
```

**Comment by Doryforos** [comment]
v7.5.9 on MS-WinXP-SP3+Updates [32bit] — still!
Fixed, for me.
