### ISSUE TITLE
Portuguese translation: translated text too long to fit (settings > preferences > editor)

### ISSUE THREAD

**Issue by jjeffman** [notepad-plus-plus/notepad-plus-plus#3947]
### Description of the Issue

The Preferences window of Notepad++ is hiding text on 120 ppi.

I am running Notepad++ on a laptop which has a 120 ppi screen at 1920 x 1080 resolution and Windows 10 pro. Windows 10 has change the ppi value to 96, but when I was using Windows 7 Pro it was 120ppi.

### Steps to Reproduce the Issue

1. Get a computer which has a 120 ppi monitor running Windows 10
2. Run Notepad++
3. Open the Preferences Window ( Settings->Preferences )

### Expected Behavior

The Preferences window showing all text and options or a scroll bar to get access to the hidden text
### Actual Behavior

The Preferences window do not show all the text.
### Debug Information

Notepad++ v7.2.2   (64-bit)
Build time : Nov 27 2016 - 16:35:52
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10
Plugins : mimeTools.dll NppConverter.dll 

![incomplete_screen](https://user-images.githubusercontent.com/14930607/33483089-41642e20-d683-11e7-91e2-015fdb7c54a2.png)

**Comment by MetaChuh** [comment]
@jjeffman 

some portuguese translations are too long to fit the field.
this still happens in 7.6.6, regardless of the scaling factor.

a portuguese or brazilian contributor will be needed to abbreviate the concerning entries.

note: i have changed the issue title from:
`Preferences window hide text on 120 ppi`
to:
`Portuguese translation: translated text too long to fit (settings > preferences > editor)`
to raise the chances that a translator might find this issue.

many thanks and best regards.

**Comment by ArkadiuszMichalski** [comment]
Out of date.
