### ISSUE TITLE
Console window - Dark theme

### ISSUE THREAD

**Issue by Yousha** [notepad-plus-plus/notepad-plus-plus#3949]
### Description of the Issue
Unable to read texts in **Console** window - readability is reduced due to using wrong colors

### Steps to Reproduce the Issue
1. Change Windows theme to **Dark**
2. Open Notepad++
3. Open console windows

### Expected Behavior
Those text colors must be same as Windows text native color

### Actual Behavior
Since i'm using **Dark** theme in my Windows, I cant see Texts in **Console** window!
Because those text are Black and its background color is Dark
SS:
http://s2.zipupload.ir/direct/uid_1_fid3007_1396-09-11_16_35_07_164971432.png

### Debug Information
Notepad++ v7.5.1   (32-bit)
Build time : Aug 29 2017 - 02:35:41
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : ON
Local Conf mode : OFF
OS : Windows 7 (64-bit)
Plugins : ComparePlugin.dll NppExec.dll NppTextFX.dll PluginManager.dll 

http://s2.zipupload.ir/direct/uid_1_fid3007_1396-09-11_16_35_07_164971432.png

**Comment by sasumner** [comment]
This is not the place to report problems with plugins that are not bundled in with Notepad++ itself.  Recommend closure.

**Comment by Yousha** [comment]
Well, so I can't use it as editor+compiler anymore...
For me, it's just a Simple editor now

**Comment by Yousha** [comment]
@dail8859 http://s2.zipupload.ir/direct/uid_1_fid3051_1396-09-17_21_28_48_396097570.png
Search and About window

**Comment by sasumner** [comment]
@Yousha you said you preferred not to use it anymore 5 days ago...what brought you back? :)  Technically your new complaint is totally separate and different than your earlier one.  At least then new one involves the standard product but you should probably change the title of the issue as a console window is not involved anymore.

**Comment by Yousha** [comment]
@sasumner why you are answering me with you useless comments?

It's not your biz,  stay away kid.

**Comment by dail8859** [comment]
@Yousha 

You opened the issue regarding a plugin that is not related to this project, thus it was closed. If you have an issue with the actual Notepad++ program (which it appears you do), please open a new issue. And let's keep the comment civil please.
