### ISSUE TITLE
Problem displaying backslash in CSS identifiers

### ISSUE THREAD

**Issue by stonecrusher** [notepad-plus-plus/notepad-plus-plus#3952]
### Description of the Issue

In a CSS file with syntax highlighting activated, some themes fail to display `\` (backslash) in identifier names correctly.  
They display a capital crossed out W instead. It still behaves like a backslash.

Colon needs to be escaped like this in some cases where it doesn't introduce a pseudo class but is just part of the identifier name (yes, surprisingly that is allowed and used).

### Steps to Reproduce the Issue

/edit: Use Win7, Win8.x, WinServer2008 or WinVista
1. Create a .css file (in my case UTF-8 without BOM)
2. Change theme to Bespin
3. Write `#\` or `.\` or `:\` (more practical `#foo\:bar`, `.foo\:bar`)

### Expected Behavior

Backslash should appear when typed

### Actual Behavior

Crossed out capital W appears

### Debug Information

```
Notepad++ v7.5.1   (32-bit)
Build time : Aug 29 2017 - 02:35:41
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 8.1 (64-bit)
Plugins : mimeTools.dll NppConverter.dll NppExport.dll 
```

![aaaaaaa](https://user-images.githubusercontent.com/1388389/33529475-b3432628-d871-11e7-8b82-53f6f950331e.PNG)
Happens with following themes:
* Bespin
* Black board
* Choco
* Deep Black
* Hello Kitty
* Mono Industrial
* Monokai
* Plastic Code Wrap
* Vibrant Ink
* vim Dark Blue

Does *not* happen with the rest of the standard themes.

**Comment by encore0117** [comment]
Sorry, I could not reproduce the error.
![untitled](https://user-images.githubusercontent.com/6385118/33692308-a8fc9c80-daba-11e7-8ba9-f657ee3f177a.png)

Version: 7.5.1 64-bit
OS: Win 10

**Comment by stonecrusher** [comment]
Make sure you chose CSS as language. If your file isn't a .css (screenshot shows .log) you have to choose it manually under `Language --> C --> CSS`. I can reproduce also in Win7 VM.

**Comment by encore0117** [comment]
I have selected CSS.
It was just a previous file I created.

**Comment by stonecrusher** [comment]
Can't believe you, I can reproduce every time, even [in a fresh VM](https://i.imgur.com/7JkI6wu.gif).  
The order of preference changes and writing doesn't matter. As soon as the three things (Bespin, CSS-Syntaxhighlighting and `:\`) are met, it happens.

NPP x32 and x64 on `Win8.1 x64`, and NPP x32 on `Win7 x32`.
Would be strange if it's the OS's fault.

**Comment by stonecrusher** [comment]
Update: Still occurs with 7.6.6

**Comment by dail8859** [comment]
Which is why this issue is still open.

**Comment by Ekopalypse** [comment]
Goto style configurator - select CSS in language, TAG in Style and set a proper font name
problem should be soved.

**Comment by donho** [comment]
Can't reproduce it on v7.6.6

**Comment by stonecrusher** [comment]
@donho Did you try it with Win7, Win8.x, WinServer2008 or WinVista?
Those seem to have the faulty version of the font "[Batang](https://docs.microsoft.com/en-us/typography/font-list/batang#batang)".

**Comment by Ekopalypse** [comment]
@donho - the reason why you can't reproduce it might be simply by the fact that your windows installation does not have the Batang font installed. 
I agree to @stonecrusher, it doesn't look like it makes sense to keep this font as, 
for example, a standard windows 10 installation doesn't have it preinstalled anyway,
at least not the ones I've tested. Might be just some kind of area which could create strange issues.
My two cents.

**Comment by Ekopalypse** [comment]
Just for info - here the info from [MS](https://docs.microsoft.com/en-us/typography/font-list/batang).
Seems that font isn't installed for any Windows 10 anymore.

**Comment by donho** [comment]
Indeed, it should be removed definitely.
Thank you for the info @Ekopalypse

**Comment by ian-wallace** [comment]
I had this problem for months.  What finally fixed it was Settings->Style Configurator->"Enable global font".
