### ISSUE TITLE
SCI_SETFIRSTVISIBLELINE message scrolls to invalid line number when line wrapping is enabled

### ISSUE THREAD

**Issue by Mesaryb** [notepad-plus-plus/notepad-plus-plus#3953]
1. Download this  project [BugPlugin.zip](https://github.com/notepad-plus-plus/notepad-plus-plus/files/1525183/BugPlugin.zip)
2. open  it  in visual studio
3. build, copy  result  dll file to  notepad++ plugins  folder.
4. open  this  file  in notepad++ [Document  with very very long  line.txt](https://github.com/notepad-plus-plus/notepad-plus-plus/files/1525185/Document.with.very.very.long.line.txt)
5. This file should be visible at this step
6. Enable line wrapping!!!
7. Click Plugins->Notepad++ plugin template->BUG
8. Notepad++ must scroll to 3 line, but it  scrolls wrong  pos. (Like line  wrapping  disabled)

Main computer:
Notepad++ v7.5.2   (32-bit)
Build time : Nov 27 2017 - 00:13:16
Path : C:\Programs\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 7 (64-bit)
Plugins : ComparePlugin.dll DSpellCheck.dll mimeTools.dll NppConverter.dll NppExport.dll NppFTP.dll NppPluginTemplate.dll NppTextFX.dll PluginManager.dll XMLTools.dll 

Also  tested in clean VMware machine:
Notepad++ v7.5.2   (32-bit)
Build time : Nov 27 2017 - 00:13:16
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10 (64-bit)
Plugins : DSpellCheck.dll mimeTools.dll NppConverter.dll NppExport.dll NppPluginTemplate.dll 

Goal code  in attached  demo project is  in DownloadedProcject\src\PluginDefinition.cpp Line 113 -> Line 125

If you're afraid of backdoors in attached demo project, you can make your own plugin with this code
```

	int which = -1;
	::SendMessage(nppData._nppHandle, NPPM_GETCURRENTSCINTILLA, 0, (LPARAM)&which);
	if (which == -1)
		return;
	HWND curScintilla = (which == 0) ? nppData._scintillaMainHandle : nppData._scintillaSecondHandle;

	int LineToScroll = 2;
	::SendMessage(curScintilla, SCI_SETFIRSTVISIBLELINE, LineToScroll, 0);

```

**Comment by dail8859** [comment]
First a reference to the Scintilla documentation regarding [`SCI_SETFIRSTVISIBLELINE`](http://www.scintilla.org/ScintillaDoc.html#SCI_SETFIRSTVISIBLELINE) (emphasis mine):

> These messages retrieve and set the line number of the first visible line in the Scintilla view. The first line in the document is numbered 0. The value is a **visible line** rather than a **document line**.

The key here is visible vs document line. The way you used `SCI_SETFIRSTVISIBLELINE` is working appropriately. A "document" line can be broken into multiple "visible" lines due to wrapping (in my case ~14 document lines for the first visible line). 

I'm not sure exactly what you are wanting...but for example if you are wanting line `3` to be at the top then you'd have to try something like this (this exact code is untested but tried the same thing with Lua):

```cpp
int LineToScroll = 3;

// Subtract 1 since lines start at 0
int VisibleLine = ::SendMessage(curScintilla, SCI_VISIBLEFROMDOCLINE, LineToScroll - 1, 0);
::SendMessage(curScintilla, SCI_SETFIRSTVISIBLELINE, VisibleLine, 0);
```

**Comment by Mesaryb** [comment]
Thanks, that's works for  me:
```
		int Line = ::SendMessage(curScintilla, SCI_LINEFROMPOSITION, myPosition, 0);
		int VisibleLine = ::SendMessage(curScintilla, SCI_VISIBLEFROMDOCLINE, Line, 0);
		::SendMessage(curScintilla, SCI_SETFIRSTVISIBLELINE, VisibleLine, 0);
```
P.S. possible I should read the documentation more carefully

**Comment by dail8859** [comment]
Glad it's working for you.
