### ISSUE TITLE
hanging npp on user defined language v 7.51 and 7.5.2

### ISSUE THREAD

**Issue by primer97** [notepad-plus-plus/notepad-plus-plus#3954]
### Description of the Issue
when selecting hpprime user defined languag, notepad++ 7.5.1 or 7.5.2 hangs.
please note, you don't need to open an exiting file, just a new empty file makes it hang !
very frustrating...

I've uninstalled my old 7.5.1, and instaled the new v7.5.2 but it behaves the same.
language definition is here : 
[hpprime.txt](https://github.com/notepad-plus-plus/notepad-plus-plus/files/1525227/hpprime.txt)

### Steps to Reproduce the Issue
1. import hpprime language defnition
2. create a new file
3. change to hpprime language definiton

### Expected Behavior
just not hanging...

### Actual Behavior
It hangs, 
you have to kill notepad++

### Other Information

note : I don't know if it's usefull but I have these extentions : 
converer, dspellcheck, mime tools, Npp Export.
my theme is VS2015-Dark.xml

**Comment by sasumner** [comment]
How do you know your UDL is okay? Was it working with an earlier version of Notepad++?

**Comment by primer97** [comment]
Hello,

the URL was created by notepadd++ itself !

It's a user language I update from time to time to add new functions 
directly in npp,
last changes was to setup color (to match dark colors theme),
few weeks after I switched to npp 7.5.1 and it started to hang npp.

I never used any other tool to generate UDL, I only used the "export" 
function of npp to get the file.

note : I don't have any previous version of the UDL file (I exported the 
current version for the 1st time to report it to you)
But UDL is supposed to be valid when outputed by npp itself, no ?

**Comment by MetaChuh** [comment]
@primer97 

i can not reproduce any crashes using the vs2015-dark theme and your adapted hp prime udl on notepad++ 7.6.6.

screenshot:
<img width="1027" alt="" src="https://user-images.githubusercontent.com/45773305/57283225-f9dad780-70ae-11e9-9f91-1f774922d12a.png">

please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins if you update from version 7.5.9 or below.

thank you for your help and best regards.

-----
```
general notes:

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
(no extra account is needed, just use your github account to sign in)
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)
