### ISSUE TITLE
7.5.2 Shell Extension Error on installation

### ISSUE THREAD

**Issue by x2on** [notepad-plus-plus/notepad-plus-plus#3956]
### Description of the Issue
The NppShell.dll Extension doesn't install with version 7.5.2.
The following error is shown:

![error](https://user-images.githubusercontent.com/195724/33547068-135d112e-d8e3-11e7-9154-db67738589cc.png)

### Steps to Reproduce the Issue

1. Download Notepad++ 7.5.2 
2. Start Admin CMD
3. npp7.5.2.Installer.exe /S

### Expected Behavior
Shell extension is installed and shown in explorer

### Actual Behavior
Error and shell extension is not installed

**Comment by SinghRajenM** [comment]
Issue has been fixed in PR #3942 . Let's wait to get this PR merged.

**Comment by x2on** [comment]
Workaround: Run the setup twice.

**Comment by SinghRajenM** [comment]
Workaround will work only for shell extension. Themes and localizations can't be added anymore with latest version.

**Comment by dail8859** [comment]
[v7.5.3](https://notepad-plus-plus.org/news/notepad-7.5.3-released.html) has been released which should fix the issue.
