### ISSUE TITLE
Find in files feature to find in remote linux machine

### ISSUE THREAD

**Issue by Varun200864** [notepad-plus-plus/notepad-plus-plus#396]
I am using **Notepad++** version 6.5(UNICODE). **Find in files** feature of Notepad++ is very powerful. Can we use this feature on remote Linux machine?

**Comment by milipili** [comment]
You can mount a share with SSHFS for Windows (one examplel: http://igikorn.com/sshfs-windows-8/)
SMB is also possible, NFS...
