### ISSUE TITLE
Some zoom steps don't actually zoom

### ISSUE THREAD

**Issue by Fabian42** [notepad-plus-plus/notepad-plus-plus#3960]
### Description of the Issue
There are some zoom steps that change neither the vertical, nor the horizontal size of the text. There are also many that only change one of those.

### Steps to Reproduce the Issue
1. Enter some text
2. Zoom in and out
3. Compare the zoom steps with the next higher/lower zoom step

### Expected Behavior
Every zoom step having a unique character width and character height

### Actual Behavior
Only a few zoom steps change both, most one or none.

### Debug Information
Notepad++ v7.3.3   (32-bit)
Build time : Mar  8 2017 - 03:37:37
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : ON
Local Conf mode : OFF
OS : Windows 7 (64-bit)
Plugins : ComparePlugin.dll CustomizeToolbar.dll NppSaveAsAdmin.dll PluginManager.dll RunMe.dll
![screenshot 2017-12-06 13 35 21](https://user-images.githubusercontent.com/10481506/33662061-c9f598f4-da8a-11e7-8e20-40350c2936b3.png)
![screenshot 2017-12-06 13 35 27](https://user-images.githubusercontent.com/10481506/33662095-e528a152-da8a-11e7-9e6b-f0f1c8c673b1.png)
![screenshot 2017-12-06 13 35 40](https://user-images.githubusercontent.com/10481506/33662063-ca537ffa-da8a-11e7-9a95-db14cb36ba92.png)
![screenshot 2017-12-06 13 35 43](https://user-images.githubusercontent.com/10481506/33662064-ca8090f8-da8a-11e7-959d-d4cdf76a68ab.png)

**Comment by Fabian42** [comment]
Is this still a valid bug here, even though it's a Scintilla problem? If no, why is this report still open?

**Comment by MetaChuh** [comment]
@Fabian42 

as the zoom function can only set the font sizes, the available zoom steps will vary, depending on the available sizes for that font.
there will be a difference in available zoom steps, depending on the used themes, as some change the fonts from courier new to other fonts.

> why is this report still open?

we forgot about closing it back then, my apologies.

thank you for your help and best regards.
