### ISSUE TITLE
Access violation when closing notepad++ with a file open

### ISSUE THREAD

**Issue by PCMedic67** [notepad-plus-plus/notepad-plus-plus#3961]
**Machine**
Computer: HP Elitebook 850 G3
OS:win7 Pro 64-bit
Notepad++: v7.5.3,v7.5.2(v7.5.1 close successful)

**Description of the Issue**
If I have any text file open then close Notepad++, whether I save the file or not, I get 2 popup message boxes, pop up messagebox(exception,Access violation).  If I just open Notepad++ to a blank file and close it the issue does not occur. Issue #3959 is same.

**Steps to Reproduce the Issue**
download and install notepad++
after install run notepad++
close notepad++ with tab change.log, access violation.

**Expected Behavior**
close successful

**Actual Behavior**
pop up messagebox Access violation

And just reinstalling 7.5.1 over 7.5.3 resolves the issue.

**Debug Information**
Notepad++ v7.5.3   (32-bit)
Build time : Dec  5 2017 - 10:45:46
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : ON
Local Conf mode : OFF
OS : Windows 7 (64-bit)
Plugins : DSpellCheck.dll mimeTools.dll NppConverter.dll NppExport.dll

**Comment by startewho** [comment]
I have the same problem,And asking for a solution

**Comment by psyrus** [comment]
Same issue here. 
<img width="359" alt="notepadpp_access_violation" src="https://user-images.githubusercontent.com/8152287/34193745-ab7f16ca-e598-11e7-93e4-841035428c8c.png">

**Machine**
Computer: Surface Pro 4
OS: Windows 10 Pro (64bit)
Notepad++: v7.5.3
Antivirus: Symantec Endpoint Protection

**Debug info**
Notepad++ v7.5.3   (64-bit)
Build time : Dec  5 2017 - 10:47:54
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10 (64-bit)
Plugins : DSpellCheck.dll mimeTools.dll NppConverter.dll

**Comment by na8esin** [comment]
I use Notepad++ v7.5.3(64-bit)

I deleted the following file
```
C:\Program Files\Notepad++\plugins\DSpellCheck.dll
```

Access violation problem ceased to occur

**Comment by psyrus** [comment]
> I deleted the following file
> C:\Program Files\Notepad++\plugins\DSpellCheck.dll
> Access violation problem ceased to occur

That solved the issue for me as well! I guess we lose some of that spell checking, but I am not using np++ for writing documents, just code so it's all good for me! 😀

**Comment by dail8859** [comment]
@Predelnik Thoughts? Should v1.3.3 possibly fix this?

**Comment by Predelnik** [comment]
@dail8859 It's possible but technically plugin doesn't try to write settings on exit so maybe it's something else.

Anyway I encourage anyone having that problem to download:
https://github.com/Predelnik/DSpellCheck/releases/tag/v1.3.3

And if this message box still appears, create a dump using Task Manager (Ctrl+ Shift + Esc)
![image](https://user-images.githubusercontent.com/2133957/34261028-d46ad520-e678-11e7-8628-748bf51fed9e.png)
And send it to me by any means comfortable to you.
If it does not happen with 1.3.3 please still comment here to signify that it fixed issue for you.

**Comment by stonecrusher** [comment]
DSpellCheck 1.3.3 (via plugin manager update) fixed it for me.
```
Notepad++ v7.5.3   (32-bit)
Build time : Dec  5 2017 - 10:45:46
OS : Windows 8.1 (64-bit)
```

**Comment by petergloor** [comment]
Same issue here:
Notepad++ v7.5.3   (32-bit)
Build time : Dec  5 2017 - 10:45:46
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10 (64-bit)
Plugins : ComparePlugin.dll CSScriptNpp.dll DSpellCheck.dll mimeTools.dll NppConverter.dll NppExport.dll NppFTP.dll PluginManager.dll XMLTools.dll

**Comment by stonecrusher** [comment]
@petergloor Did you make sure you have DSpellCheck.dll updated to version 1.3.3?

**Comment by mk2** [comment]
Hi.

Same issue occurred on my machine, and updating DSpellCheck.dll to 1.3.3 was not solution. (On the other hand, removing DSpellCheck.dll was good method for me.)

----
Notepad++ v7.5.3 (32-bit)
Build time : Dec 5 2017 - 10:45:46
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10 (64-bit, home edition)
Plugins : DSpellCheck.dll NppEditorConfig.dll mimeTools.dll NppConverter.dll NppExport.dll PluginManager.dll

**Comment by Predelnik** [comment]
@mk2 Can you please try to save and send me a dump file as I have written in above comment?

**Comment by mk2** [comment]
@Predelnik  I send you the dump file (7-zipped) via e-mail!

**Comment by Predelnik** [comment]
@mk2 
Thank you very much for the dump file! It has proven to be of tremendous usefulness!
It would be really great if you check if replacing plugin with version from the link below fixes the issue
https://drive.google.com/uc?export=download&id=1_6dqXWr_hJwOM6_0CuYdKWYpZJ0Hsag_

Anyone else having this issue can check too but it's x86 version, if you need x64 I will be glad to provide it.

**Comment by mk2** [comment]
@Predelnik  Thanks! But... the link destination is a 404 error. Did not you forget permission for download?

**Comment by stonecrusher** [comment]
@mk2 You need to include the underscore at the end into the url: [link](https://drive.google.com/uc?export=download&id=1_6dqXWr_hJwOM6_0CuYdKWYpZJ0Hsag_)

**Comment by mk2** [comment]
@stonecrusher Thanks!! 

@Predelnik I have downloaded and it works fine! Thank you very much!

**Comment by Predelnik** [comment]
@mk2 Thank you very much for checking it out! And sorry for this runaway underscore.

**Comment by Predelnik** [comment]
I release version 1.3.4 with fix for this issue:
https://github.com/Predelnik/DSpellCheck/releases/tag/v1.3.4

Some technical details about the problem:
Apparently some notifications for plugins could come in certain cases after supposedly final notification NPPN_SHUTDOWN. I assumed that it never happens.

**Comment by petergloor** [comment]
It looks like the 1.3.4 version of DSpellCheck definitely solved the issue for me. Thank you.

**Comment by Predelnik** [comment]
I had broken some things in 1.3.4 accidentally. So I had to release 1.3.5, it most likely should be fine in regards to this problem, but I just wanted to make sure.
https://github.com/Predelnik/DSpellCheck/releases/tag/v1.3.5
Sorry for the inconvenience!

**Comment by donho** [comment]
@petergloor @mk2 @PCMedic67 @startewho @psyrus @na8esin 

Could you please download DSpellCheck v1.3.5
https://github.com/Predelnik/DSpellCheck/releases/tag/v1.3.5  (same link of above provided by @Predelnik )
And confirm that issue has been fixed in this version?

Thanks a lot.

**Comment by mk2** [comment]
@donho Yes it works! v1.3.5 also good like v1.3.4.

**Comment by petergloor** [comment]
@donho It works. Great job! Thank you.

2017-12-27 18:20 GMT+01:00 Don HO <notifications@github.com>:

**Comment by wysocki** [comment]
I'm getting access violation when I start npp, also when I open and close a file. I deinstalled the spell check plugin but no change.
