### ISSUE TITLE
C/C++ collapse bugs - 

### ISSUE THREAD

**Issue by bmcdonnell-ionx** [notepad-plus-plus/notepad-plus-plus#3962]
### Description of the Issue
Incorrect collapsing behavior in certain situations. Related to macros, braces, K&R brace style.

Using Allman brace style works-around this bug.

### Steps to Reproduce the Issue

1. Paste this code into a new file in Notepad++.

```
#if defined(__THING__)
void func1(void) {
#else
void func2(int param) {
#endif
    // do stuff...

}

// other stuff...
```

2. Either choose `Language` --> `C++` from the menu, or save it as a `.h` or `.cpp` file.
3. Use the `-` / `+` icons between the line numbers and text to collapse and uncollapse sections of text.

### Expected Behavior
- Clicking collapse on line 1 (`#if` macro) should hide lines 2-5 (through `#endif`, inclusive).
- Clicking collapse on line 4 (`func2()`) should hide lines 5-8 (through `}`, inclusive).

This is honestly what I expected, but would it cause unexpected behavior elsewhere? What smarts would be required? Is it a fair expectation for a text editor?

Hypothetically, NPP could see that the brace is opened in both conditions of the `#if`, and so could count it as one. But then what happens if there is no `#else`, or if not all cases open a brace?

### Actual Behavior
- Clicking collapse on line 1 (`#if` macro) hides all other lines.
- Clicking collapse on line 4 (`func2()`) hides only line 5 (`#endif`).

### Debug Information
Notepad++ v7.5.3   (32-bit)
Build time : Dec  5 2017 - 10:45:46
Path : C:\Users\bmcdonnell\Downloads\npp.7.5.3.bin.minimalist\notepad++.exe
Admin mode : OFF
Local Conf mode : ON
OS : Windows 10 (64-bit)
Plugins : none

Notepad++ v7.5.1   (32-bit)
Build time : Aug 29 2017 - 02:35:41
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10 (64-bit)
Plugins : mimeTools.dll NppConverter.dll NppExport.dll

**Comment by bmcdonnell-ionx** [comment]
Note, #3638 was another code collapsing bug related to apparently unbalanced braces.

**Comment by dail8859** [comment]
> What smarts would be required?

An actual IDE which knows whether or not `__THING__` is defined. Notepad++ has no way of knowing which preprocessor block it should actually use, thus it is messing up the folding.

#3638 isn't a bug, it is a (confusing) [feature](https://sourceforge.net/p/scintilla/bugs/1676/#5b1a) provided by Scintilla. Any bugs/fixes that need made to the C++ lexer would have to be posted on the Scintilla issue tracker.

---

As a side note you can kind of fix the folding a bit abusing the feature above. If you use this code instead:

```cpp
#if defined(__THING__)
void func1(void) { //}
#else
void func2(int param) { //}
#endif
//{
    // do stuff...

}

// other stuff...
```

You will see the folding behaves a little better (but not perfect).

![capture](https://user-images.githubusercontent.com/3694843/33670299-b8c99598-da72-11e7-9d13-5ae849572f1c.PNG)

**Comment by Ekopalypse** [comment]
Should be closed. @dail8859 provided a workaround and an explanation why this can't be solved by npp/scintilla.
