### ISSUE TITLE
Easter egg "Anonymous #152" should start with "An" instead of "A"

### ISSUE THREAD

**Issue by Fabian42** [notepad-plus-plus/notepad-plus-plus#3963]
What the title says. Since "SQL" is pronounced "es kju el", it starts with a spoken vowel, so the indefinite article is "an".
One examples source: https://en.wikipedia.org/wiki/Article_(grammar)#Indefinite_article

**Comment by Vanderdecken** [comment]
Many people pronounce it "sequel", which would make starting with "A" correct.
https://en.wikipedia.org/wiki/SQL
https://english.stackexchange.com/a/7234

There is no standard and it's a matter of preference, so if Don pronounces it as a word not an abbreviation, I guess he's not going to change it. Not that he's probably worried about the grammar of Easter eggs...

**Comment by MetaChuh** [comment]
@Fabian42 

the real easter egg was omitting the "n", and you have successfully found it. 😉👍

thank you for your help and best regards.

**Comment by Fabian42** [comment]
Why "wontfix"?
