### ISSUE TITLE
HTML/XML tag highlighting fails because comments are not ignored

### ISSUE THREAD

**Issue by kozuch** [notepad-plus-plus/notepad-plus-plus#397]
In an HTML file, if a tag contains comment, which contains an unclosed tag, then tag highliting on the parent tag is not working properly. It looks like the commens are not ignored properly. See screenshots.

Version: notepad++ v6.7.7

Cursor on the closing parent div:
![image](https://cloud.githubusercontent.com/assets/1474153/8497212/bc12e3ec-217b-11e5-8086-59a774d94116.png)

Cursor on the opening parent div:
![image](https://cloud.githubusercontent.com/assets/1474153/8497242/ed6d3aa0-217b-11e5-9f46-a2490edb9d70.png)

**Comment by jsuar** [comment]
I was able to replicated this issue (v6.7.8.2). However, I noticed that the div attributes won't highlight if an end tag is included.

![Issue replicated](https://cloud.githubusercontent.com/assets/3450619/8500006/4f79558c-2166-11e5-920d-60c0623e3c1f.png)

![End tag included](https://cloud.githubusercontent.com/assets/3450619/8500011/55b0d006-2166-11e5-9d64-d9a6cce4e9fd.png)

**Comment by milipili** [comment]
The comments seem completely ignored :)

**Comment by jsuar** [comment]
Apologies. I overlooked that the OP specified the issue was for an unclosed tag.

**Comment by kozuch** [comment]
I think I forgot to mention the issue also occurs in XML documents.

**Comment by kozuch** [comment]
Can we expect any progress here? Or has this been fixed already?

**Comment by donho** [comment]
I believe this issue has been fixed since long time ago.
Update your Notepad++ to the latest version (v7.6.6).
If the issue persists, please create a new issue for it.
Thank you.
