### ISSUE TITLE
Crash when searching and opening a file

### ISSUE THREAD

**Issue by Gaktan** [notepad-plus-plus/notepad-plus-plus#3970]
### Description of the Issue

Noticed while doing a file search that opening a file in explorer by double clicking on it will crash notepad++.

### Steps to Reproduce the Issue

1. Use CTRL+SHIFT+F to search in files
2. While the search is processing, open a file by double clicking on it
3. Notepad++ should crash

### Expected Behavior

File should open normally. Either during or after the search is finished

### Actual Behavior

Crash

### Debug Information

Notepad++ v7.5.1   (32-bit)
Build time : Aug 29 2017 - 02:35:41
Path : E:\Programs\Notepad++\notepad++.exe
Admin mode : ON
Local Conf mode : OFF
OS : Windows 10 (64-bit)
Plugins : HexEditor.dll mimeTools.dll NppConverter.dll NppExport.dll NppFTP.dll PluginManager.dll XMLTools.dll

**Comment by SinghRajenM** [comment]
Could not reproduce with Notepad++ v7.5.9   (32-bit).

**Comment by VirtuosGaetan** [comment]
I can confirm this is fixed in v7.5.9 (32-bit)

**Comment by Gaktan** [comment]
I can confirm this is fixed in v7.5.9 (32-bit)
