### ISSUE TITLE
Erased Whole File

### ISSUE THREAD

**Issue by GoukaRyuu** [notepad-plus-plus/notepad-plus-plus#3974]
### Description of the Issue
I use NotePad++ to edit my save file for Crusader Kings 2. Very rarely, I think this is the second ever time it has happened, I was changing something and the program froze for a moment and then crashed. Checking, the file was now completely empty. While I did have a backup to that game, I had lost 12 hours worth of play time.

### Steps to Reproduce the Issue
I don't know.

### Expected Behavior
I expected to be able to go in and edit the save like I have done dozens of times before.

### Actual Behavior
NotePad++ crashed and the entire file was wiped clean.

**Comment by MetaChuh** [comment]
please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins if you update from version 7.5.9 or below.

thank you for your help and best regards.
