### ISSUE TITLE
Error on saving and reopening file

### ISSUE THREAD

**Issue by KiarEL** [notepad-plus-plus/notepad-plus-plus#398]
Hi, 
Just signed up to cry out that something is definitely wrong in notepad++ when saving files (maybe while the auto backup function is activated.)
This is the second time (when I realize it) when I do a "Ctrl+shft+S" (Save all) then close the npp and shut down my laptop to reopen it the next day and to find that my entire work for hours (and months this time) is lost !!!  :((
Maybe you'll get an idea and help me figure out what's wrong to search and resolve it - this is how I use npp:
- I keep opened all the time a lot of files: conf, logs, worklogs, ideas logs, etc  (around 100 files more or less)
- I have the auto  backup option activated (every 7 seconds) as I also keep a lot of temporary "new" opened and unsaved files.
- From time to time I do collect the work from those "new"  or other files to save it in a dedicated file.
  This happened again yesterday, I did the collect  and saved it in a new file created at noon and I kept working until late evening . And today when opening it I've found only the first 5 (five!!!) lines which I did paste in the beginning. The file shows the saved hours as 14h17... or I have last saved it at ~ 20h00.
  And I do use a lot of "Ctrl+shift+S" trough the day, as the other time it happened I thought maybe it was my fault that i did not save my work somehow (though as I already mentioned it, I have activated the auto backup option and always did a lot of "Ctrl+Shift+S")

The worst part is that only the collector file is not saved... the others are saved without the collected text so I cannot  recover my works and ideas collected/saved in their initial files in the last months .

Has anyone else heard at least of such behavior? 

Thanks a lot for any helping tips.

NB: 
(1) In the backup path I have found nothing of use but there are files dating more then a year ago (the oldest: "new  2@2014-05-28_134727" )
(2) I don't use the "Backup on save " function
(3) I don't use windows rescue / restore point on the working partition (only on system's partition)
(4) (4th but not the last) I do appreciate notepad++ and its developers :)
(5) I always updated it when asked me - today I've manually updated to the last version though it did not asked me

**Comment by cmeriaux** [comment]
Hello,
do you have some exotic plugin ? You may try to remove them.
Do you save your collector file in a dedicated file or do you keep it in a backup file ?

**Comment by KiarEL** [comment]
Hello, 
Thanks for your interest.

(1) Hm, I may have an "exotic" plugin now that you reminded me (please see attached pic)
I see it stopped working ... I may have it for more thne a year ...or two

![npp_plugs](https://cloud.githubusercontent.com/assets/13163143/8498629/b53d34b2-2191-11e5-851e-e84c6722da78.png)

(2) Hm, again you may be right... It is possible that the "collector" file was one of those unsaved but auto backup-ed file, I did not pay attention to this as I was saving with "Ctrl+alt+s" or ctrl+s...
Could this trigger the abnormal (for me) behavior?

Thanks again, 
Catalin

**Comment by KiarEL** [comment]
To avoid this behavior I've finally activated verbose backup in a designated directory.
I don't want to think about how much other work could be also lost without me to notice it.
I'm still interested in what could have caused that behavior, maybe later I'll do some tests with what "cmeriaux" have said (2).

**Comment by KiarEL** [comment]
it's still happening :(.
This is how to reproduce:
1) Create new file (the tab writings is black)
2) write something in file (the tab writings is red now)
3) save file with a name
4) start to cut & paste your tens hours work from the last days.
5) save again your precious work and close the app ( I use Ctrl+shft+s )

Now (or next day) open again that  file aaaand surprise!  you only have the text you enter it at step (2)
because after the step (3) the color on the tab name stayed black as you were never modified it.
This should be related to some internal mechanism that should signal an edited file but as you dont look every second to that tab or tag name or whatever it is called... you don't know your about to loose everything, no matter how many backups you had until that point.

So yet again I lost almost everything I worked on a project a month ago, precious info and step by step self-notes.
Really, am I the only one having this issue for the last 2-3 years?

thanks

**Comment by mauriciolp** [comment]
I am also facing this bug, which is really annoying and it made me loose valuable hours of work because of it. I also use the Session Manager.
Still no update on it?
It seems similar to issue #529 .

**Comment by donho** [comment]
Update your Notepad++ to v7.6.6.
If this bug persists in the new release, please open a new issue with the debug information.

**Comment by mauriciolp** [comment]
I tried updating my Notepad++ as suggested, but the problem persists: New files created inside Notepad++ do not have the "Save (Ctrl + S)" command available.

It is like the program can not recognize that changes have been made, so this command never becomes available. Note, you can save the first time, when the file is actually created, but further modifications are not saved.

**Debug Information**

> Notepad++ v7.6.6   (64-bit)
Build time : Apr  3 2019 - 23:52:32
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10 (64-bit)
Plugins : DSpellCheck.dll JSMinNPP.dll mimeTools.dll NppConverter.dll NppExport.dll SessionMgr.dll
