### ISSUE TITLE
Add file count searched to Find-result panel entry

### ISSUE THREAD

**Issue by KelvinKam** [notepad-plus-plus/notepad-plus-plus#3980]
### Description of the Issue
Find All in All Opened Documents "in $x file" count is wrong

### Steps to Reproduce the Issue
1. Open 10 files, 9 of them contains "one two", 1 of them contains "one two three"
2. Drag them in Notepadd++
3. Search "three" 
4. Result will return "1 hit in 1 file", but not 10 (But we opened 10 documents, it should be 1 hit in 10 files)

### Expected Behavior
Result will return 1, but not 10 (But we opened 10 documents, it should be 1 hit in 10 files)

### Actual Behavior
I do remember it will show "1 hit in 10 files" on old version

### Debug Information
Notepad++ v7.5.3   (64-bit)
Build time : Dec  5 2017 - 10:47:54
Path : C:\Users\UserName\Desktop\Kelvin Kam\Software\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : ON
OS : Windows 7 (64-bit)
Plugins : DSpellCheck.dll mimeTools.dll NppConverter.dll

**Comment by sasumner** [comment]
If the text you search for isn't found in any files, it says "0 hits in 0 files".  This leads me to believe that the "in x files" part tells the number of files **_with hits_**, not the total number of files examined.  If that's the case, then maybe a nice enhancement would be to change it to output "x hits in y files (z files searched)" or some such...

**Comment by KelvinKam** [comment]
@sasumner It is a great enhancement if Notepad++ team can make it works, then we can use this function to check hits in many files.

**Comment by sasumner** [comment]
I like it as an enhancement.  Maybe change title of issue to "Add file count searched to Find-result panel entry"?  Or maybe this already exists as another issue (I didn't check).

**Comment by KelvinKam** [comment]
@sasumner Title has been changed, I will be very happy if you work on this update ^^

**Comment by sea51930** [comment]
2017年12月11日 上午3:39，"KelvinKam" <notifications@github.com>寫道：

@sasumner <https://github.com/sasumner> Title has been changed, I will be
very happy if you work on this update ^^

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/notepad-plus-plus/notepad-plus-plus/issues/3980#issuecomment-350575691>,
or mute the thread

**Comment by sasumner** [comment]
This new feature would help the situation where you have not set the correct "Filespec" to search for on the Find-in-Files tab--if you have this wrong you at first may be led to believe that your find-what expression is wrong or there were no hits.  If it said "0 files searched" that would be a big clue that the filespec or the starting directory is wrong and the find-what expression is fine.

**Comment by sasumner** [comment]
So as a workaround to see how many files will be impacted by a search you can run a Find-in-Files or a Find-All-in-All-Open-Docs on the regular expression `(?-s).\Z`.  This will generate output of "(N hits in N files)" where N is the number of non-zero-length files searched.

**Comment by sasumner** [comment]
It seems that the simpler `\z` works as well for this workaround.
