### ISSUE TITLE
File Status Auto-Detection somehow broken

### ISSUE THREAD

**Issue by siubb** [notepad-plus-plus/notepad-plus-plus#3981]
### Description of the Issue

https://notepad-plus-plus.org/repository/7.x/7.5.3/npp.7.5.3.bin.minimalist.7z
I think the name of this feature does not really describe itself, so...
it is (or was) the feature that prompt user a file opened in notepad++ get changed outside of notepad++, e.g. a log file. It does not work in version 32-bit 7.5.3. (or earlier version)

### Steps to Reproduce the Issue

1. Open a text file in notepad++
2. Change the text file with windows notepad, or eclipse, or mathlab, or alphazero.
3. When user get back to notepad++, there used to be a prompt to ask if the user want to get the file updated, or the file is already updated silently. Now there is nothing.

### Expected Behavior

1.When user get back to notepad++, there used to be a prompt to ask if the user want to get the file updated, or the file is already updated silently. Now there is nothing.

### Actual Behavior

1.When user get back to notepad++, there used to be a prompt to ask if the user want to get the file updated, or the file is already updated silently. Now there is nothing.

### Debug Information

Notepad++ v7.5.3   (32-bit)
Build time : Dec  5 2017 - 10:45:46
Path : R:\google\npp.7.5.3.bin.minimalist\notepad++.exe
Admin mode : OFF
Local Conf mode : ON
OS : Windows XP (32-bit)
Plugins : none

Thank you very much. This is a great program.

**Comment by sasumner** [comment]
Works for me; I get prompted.  Try a freshly unzipped portable install of 7.5.3 32-bit and see if that works for you?

**Comment by siubb** [comment]
Completely fresh unzip of npp.7.5.3.bin.minimalist.7z does not work. 
Maybe this only happens on specific env? 
Mine is XP SP3 32-bit, the file is on a ramdisk, timestamp and content get updated. No update in npp.

**Comment by sasumner** [comment]
The oddball thing might be the ramdisk, try removing that from the mix if you can?

**Comment by dail8859** [comment]
@siubb 

What are your settings regarding file status auto-detection?
![capture](https://user-images.githubusercontent.com/3694843/33834809-509c0c10-de52-11e7-8774-cca5acff4ea0.PNG)

**Comment by siubb** [comment]
@dail8859 
The npp I used to verify this issue is a freshly unzipped one, everything default, should be the same as your screenshot.

@sasumner 
Thanks for the suggestion, Just moved the npp and the file to a normal storage and tried again, same issue.
I was using npp 6.x.x a few weeks back, it prompted me updated files even on a ramdisk env.
So, the oddball maybe XP.

**Comment by kkirochkagi** [comment]
I have the same problem.
**Notepad++ File Status Auto-Detection not working**
https://notepad-plus-plus.org/community/topic/15089/notepad-file-status-auto-detection-not-working
**Recorded on video**
https://www.youtube.com/watch?v=kT8DyXEGYtI

**Comment by ClaudiaFrank** [comment]
Update:
this is the last working one

_Language menu and Style configurator sorted alphabetically and use the same language name in the Style configurator as the language menu._

https://ci.appveyor.com/project/donho/notepad-plus-plus/build/1.0.1526

this is the first which breaks it

_Switch to VS 2015_

https://ci.appveyor.com/project/donho/notepad-plus-plus/build/1.0.1530

There were no build from 1.0.1527 to 1.0.1529 due to errors.

**Comment by MetaChuh** [comment]
@siubb 

windows xp is no longer supported, and i can't reproduce this file status auto detection problem on 7.6.6 using windows 7 or 10.

if you are still on windows xp, you can try to update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins if you update from version 7.5.9 or below, but without plugins admin and updater functionality.

thank you for your help and best regards.

-----
```
general notes:

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
(no extra account is needed, just use your github account to sign in)
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)
