### ISSUE TITLE
Add some math operation

### ISSUE THREAD

**Issue by mrTonyyM** [notepad-plus-plus/notepad-plus-plus#3982]
### Description of the Issue

I want to make some math operations when I open some text with data. also I would be select a column and apply some math operation to whole column.

**Comment by sasumner** [comment]
That is not a great feature request.  What math operations?  What is a "column" (a rectangular selection?)?

**Comment by dail8859** [comment]
I see this as an unbounded feature request. Simple things could be added (addition, subtraction, multiplication, division) then users would want more complex operations (conditional statements, formulas, floating point, exponential, etc). Then allowing users how to define columns (tab/space/comma delimited, strip white space, etc). This would be difficult to maintain and is outside the scope of Notepad++. 

So your options would be:
- Use a different program (e.g. Microsoft Excel, LibreOffice Calc)
- Find a plugin that does this
- Create a plugin yourself
- Use a scripting language within Notepad++, such as LuaScript or PythonScript
