### ISSUE TITLE
OEM 737 encoding broken from version 7.5.2

### ISSUE THREAD

**Issue by lourdas** [notepad-plus-plus/notepad-plus-plus#3983]
### Encoding to Greek OEM 737 character set is broken
Up until version 7.5.1, the display conversion to OEM 737 (Greek DOS codepage) worked fine. From version 7.5.2 this conversion function is broken.

### Steps to Reproduce the Issue
1. Open a file that contains Greek written from a DOS window (copy con ....) in Notepad++ 7.5.2+.
2. Click on Encoding -> Character Sets -> Greek -> OEM 737.
3. You should see the Greek characters displayed, but instead you see another character set.

### Debug Information
Notepad++ v7.5.3   (64-bit)
Build time : Dec  5 2017 - 10:47:54
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 7 (64-bit)
Plugins : DSpellCheck.dll mimeTools.dll NppConverter.dll

**Comment by lourdas** [comment]
Screenshot from version 7.5.1 (correct display):
![1](https://user-images.githubusercontent.com/397916/33818311-c475ff8e-de4c-11e7-921a-fa292ada46da.png)

Screenshot from version 7.5.3 (broken display):
![2](https://user-images.githubusercontent.com/397916/33818326-d63701c8-de4c-11e7-9eab-fa265891b591.png)

**Comment by dail8859** [comment]
It would help if you could upload a file you used instead of hoping someone can correctly create the Greek characters to reproduce the issue.

**Comment by lourdas** [comment]
I'm attaching a file with a line in English and the corresponding text in Greek.
[test.txt](https://github.com/notepad-plus-plus/notepad-plus-plus/files/1548125/test.txt)

**Comment by lourdas** [comment]
And this is how Notepad++ should display the file (version is 7.5.1):

![npp-greek](https://user-images.githubusercontent.com/397916/33839321-878d32ce-de9a-11e7-8ad2-e010d528c5e6.png)

**Comment by hubaishan** [comment]
see this also https://github.com/notepad-plus-plus/notepad-plus-plus/issues/4009
