### ISSUE TITLE
Notepad++ 7.5.3: Function list broken for Javascript files

### ISSUE THREAD

**Issue by AleWin32** [notepad-plus-plus/notepad-plus-plus#3984]
Function list does not work anymore for Javascript files in last version of Notepad++ (7.5.3), it works on 7.4.2 at least.

Just open a Javascript file with a function inside and it will not be shown on Function list window (View menu, Function list).

**Comment by sasumner** [comment]
If you are just reporting it, that's fine; I'm sure it is a known issue here somewhere in the issues list.  However if it something that is driving you crazy constantly, you can workaround it yourself until it is fixed, probably by following the information here:  https://notepad-plus-plus.org/community/topic/14860/function-list-empty-for-js-files

**Comment by MAPJe71** [comment]
See also #2924

**Comment by ArkadiuszMichalski** [comment]
@AleWin32 do you still have this problem in latest Notepad++ version?

**Comment by donho** [comment]
Works to me in v7.9:
![image](https://user-images.githubusercontent.com/90293/93757469-1d041980-fc07-11ea-9438-2926d1d01a9c.png)
