### ISSUE TITLE
UTF-8 Bug

### ISSUE THREAD

**Issue by malitech** [notepad-plus-plus/notepad-plus-plus#3986]
### Steps to Reproduce the Issue

1. Preferences > New document > Check UTF-8 (Apply to opened ANSI files)
2. Create a new file and save it in UTF-8 encoding. Close notepad++
3. Open notepad++. Encoding shows UTF-8. Drag the new file that you created and the encoding changes to ANSI.

### Expected Behavior

The encoding should be set to UTF-8 as default. File was saved in UTF-8 and the default encoding setting is UTF-8. So, the dragged file should be shown in UTF-8 encoding.
### Actual Behavior

Any saved files dragged to notepad shows up in ANSI encoding even though it was saved in UTF-8 and even when the default encoding is set to UTF-8
### Debug Information

Notepad++ v7.5.3   (32-bit)
Build time : Dec  5 2017 - 10:45:46
Path : D:\C\Notepad ++\notepad++.exe
Admin mode : ON
Local Conf mode : ON
OS : Windows 7 (64-bit)
Plugins : ComparePlugin.dll DSpellCheck.dll mimeTools.dll NppConverter.dll NppExport.dll NppFTP.dll PluginManager.dll PreviewHTML.dll 

The windows notepad shows the file in utf-8 format but when I drag it to notepad++, it shows in ANSI.

**Comment by dail8859** [comment]
Possible fix in #3922

**Comment by malitech** [comment]
Does it mean the next version will include the fix?

**Comment by dail8859** [comment]
Hopefully

**Comment by dail8859** [comment]
Closed by 1002865144aa6588b6bef0cb1d4250597d3fe0e7

This fix will be in the next release.

**Comment by malitech** [comment]
The issue persists in v7.5.4 build.

**Comment by CookiePLMonster** [comment]
Since you mentioned ANSI files not showing as UTF-8, #4124 possibly fixed it.

**Comment by malitech** [comment]
UTF-8 files show as ANSI after saving and reopening.

**Comment by CookiePLMonster** [comment]
But only if they don't have UTF-8 characters in them, I guess? If you try to saving for example with this

Ą

then it should be detected as UTF-8 fine.

**Comment by malitech** [comment]
For example, save this,
😍😸
and you can reproduce the issue.

**Comment by CookiePLMonster** [comment]
Ah! Then it's related to several issues: #675, #671, #813 and #4056 - and maybe more.

**Comment by malitech** [comment]
But it works fine if I save as UTF-8 BOM

**Comment by jabcreations** [comment]
Couldn't we just please have an option to force-open files as a certain type of encoding with a select /drop-down list that includes UTF-8 and other encoding choices? ...and make it optional for those who work with multiple different encodings who'd prefer not to have this on by default?

I _absolutely can not_ have BOM and I have _must use_ UTF-8.
