### ISSUE TITLE
Feature Request: Adding command line switches for "print" and "printto" to mimic notepad.exe

### ISSUE THREAD

**Issue by dodmi** [notepad-plus-plus/notepad-plus-plus#3987]
### Description of the Issue
I've replaced Notepad with Notepad++ [according to the official guide](http://docs.notepad-plus-plus.org/index.php?title=Replacing_Notepad).
This is working fine for opening documents. But the windows context menu also provides methods for printing files, associated with Notepad.exe and also some programs rely on these command line switches, which will fail if you replaced Notepad.exe.
`notepad.exe /P <filename>`
`notepad.exe /PT <filename> <printername> <driverdll> <port>`
It would be great if you could implement these command line switches to Notepad++ 

### Steps to Reproduce the Issue
1.  Replace Notepad by Notepad++ (by any method)
2.  Right click a text file and select "Print"

### Expected Behavior
The file gets printed without any further notification and closed afterwards (i.e. if Notepad++ wasn't already running, it will be closed afterwards, maybe a new instance should be used?)

### Actual Behavior
A message appears, that the file "C:\p" doesn't exist and if you like to create ist.

### Debug Information
Notepad++ v7.5.3   (32-bit)
Build time : Dec  5 2017 - 10:45:46
Path : C:\Program Files (x86)\Office\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10 (64-bit)

**Comment by donho** [comment]
I will see what I can do about it.

**Comment by Big--Mike** [comment]
Thank you :)

**Comment by donho** [comment]
@Big--Mike So could we consider this feature has been done by https://github.com/notepad-plus-plus/notepad-plus-plus/pull/4620 ?

**Comment by Big--Mike** [comment]
@donho It's partly done. https://github.com/notepad-plus-plus/notepad-plus-plus/pull/4620 emulates the /P parameter, not /PT. 

I'm using a Software which uses the command in the windows "PrintTo" context menu to convert various file types to pdf by sending them to a virtual PDF printer. The default for textfiles is **%SystemRoot%\system32\notepad.exe /pt "%1" "%2" "%3" "%4"**.
So, I have a use case, and Notepad++ will still not work in this situation. But this feature requires more changes as renaming the existing **-quickprint** to **/P**.

It would be nice to have support for this feature, but I understand, that the benefit is low compared to the feature in https://github.com/notepad-plus-plus/notepad-plus-plus/pull/4620, which helps many people to simply replace Notepad.

I can't implement it myself. So it's up to you, to decide if you decline the second part of the request or add the feature for full command line compatibility with the default Notepad.

**Comment by klepp0906** [comment]
just found this due to working on replacing notepad on a few systems myself.  I assume we're still able to get /p but not /pt then?   -quickPrint works for the former, but no switch for the latter has gone in?

**Comment by dodmi** [comment]
@klepp0906 That's true. If you need this functionality, you may like to have a look at [my replacement script](https://github.com/dodmi/NPP-Addons/tree/master/notepadReplacement). 
- It circumvents the limitation by setting the default printer to the printer specified with /pt and resets the default printer afterwards.
- You need to set the debugger to the replacement script (see the comments in the script header for instructions)

I'll close my issue, since after over three years it doesn't seem likely, that it will get implemented - and I have a workaround for my needs.
