### ISSUE TITLE
Active tab text :  Fonts disabled

### ISSUE THREAD

**Issue by octaviobernal** [notepad-plus-plus/notepad-plus-plus#3988]
### Description of the Issue
Unable to change Active tab text styles,  Under Style Configurator Font style fields are disable, specifically "Font name" and "Font size"

### Steps to Reproduce the Issue
1) Go to Settings -> Style Configurator
2) In the Popup Window at the left side under "Language": select "Global Style"
3) In the same Popup Window at the left side under "Style": select "Active Tab Text"
4) In the same Popup Window at the right side under "Global Styles: Active tab text" Font style fields are disable, specifically "Font name" and "Font size"

### Expected Behavior
Be able to change Active tab text styles.

### Actual Behavior
Not able to change Active tab text styles.

### Debug Information
![screenshot](https://user-images.githubusercontent.com/34452830/33842280-afe4af08-de5f-11e7-93f0-8b34c9b8776c.png)

**Comment by donho** [comment]
This feature offers only color change.
