### ISSUE TITLE
Feature request: add the "hide tabs panel when only one tab is opened" setting

### ISSUE THREAD

**Issue by YakovL** [notepad-plus-plus/notepad-plus-plus#3989]
For now we only have an option to always show or hide tabs panel but it's a very reasonable behaviour (available, for instance, in Explorer++) to hide it when there's only one tab and show if there's more. This makes the interface much clearer and one doesn't have to switch the option for different windows when some contain one tab and some contain multiple.

**Comment by YakovL** [comment]
Any comments regarding status of this?

**Comment by Shoggomo** [comment]
I'd also like to see this feature as other editors like kate also have it.

**Comment by ArkadiuszMichalski** [comment]
@sasumner 
Duplicate https://github.com/notepad-plus-plus/notepad-plus-plus/issues/6098, maybe close this, in the newer you provided an example solution.

**Comment by sasumner** [comment]
Closing this one in favor of the newer 6098
