### ISSUE TITLE
CoTaskMemFree should be called when using `SHGetSpecialFolderLocation`

### ISSUE THREAD

**Issue by milipili** [notepad-plus-plus/notepad-plus-plus#399]
According https://msdn.microsoft.com/en-us/library/windows/desktop/bb762203%28v=vs.85%29.aspx, `CoTaskMemFree` should be called when calling `SHGetSpecialFolderLocation`

**Comment by Rikk** [comment]
`[SHGetSpecialFolderLocation is not supported and may be altered or unavailable in the future. Instead, use SHGetFolderLocation.]`

**Comment by CookiePLMonster** [comment]
It's an old issue, but I assume it's still a thing? As of February 2018, `SHGetSpecialFolderLocation` is **still** in use and `pidl` is still not being freed. Plus it has that dreaded MAX_PATH arbitrary limit.
