### ISSUE TITLE
Autodetect empty files as UTF-8 without BOM (or add an option for such behaviour)

### ISSUE THREAD

**Issue by YakovL** [notepad-plus-plus/notepad-plus-plus#3990]
For now, empty files are autodetected as ANSI. I use AutoHotKey to create a timestamped empty file and open it in n++ and I need it to be in UTF-8 without BOM instead. It would be very nice not to switch encoding each time, so please change encoding autodetection algorithm or implement an option which governs encoding detection to act this way.

**Comment by dail8859** [comment]
`Settings > Preferences > Editing > New Document > UTF-8 > Apply to Opened ANSI Files`

**Comment by YakovL** [comment]
I have this option enabled, that doesn't help. Too early to close the issue.

**Comment by dail8859** [comment]
Possible fix in #3992

**Comment by dail8859** [comment]
Closed by 1002865144aa6588b6bef0cb1d4250597d3fe0e7

This fix will be in the next release.

**Comment by YakovL** [comment]
yeap, confirming that in 7.5.4 the issue is gone
