### ISSUE TITLE
Character encodings are broken

### ISSUE THREAD

**Issue by dnakamura** [notepad-plus-plus/notepad-plus-plus#3991]
### Description of the Issue
The heart of the issue lies in the way the menu item IDS interact with the EncodingMapper. IE a constant is subtracted from the ID and used as an index into the encoding map
https://github.com/notepad-plus-plus/notepad-plus-plus/blob/e339c0f600295267db7a8df01598d1cdb8f1c5cc/PowerEditor/src/NppCommands.cpp#L2174-L2177

However with the recent removal of a number of unused character encodings (60f1137), causes this to breakdown. the command IDs remain the same, however the indexes in the Encoding map have changed. This means that any encoding with a command id greater than the first deleted encoding, no longer behaves as expected.

**Comment by dail8859** [comment]
Possibly the cause of #3983

**Comment by dnakamura** [comment]
@dail8859  yeah was just looking at that. 100% is the cause
