### ISSUE TITLE
is this a bug with edit..column editor?

### ISSUE THREAD

**Issue by gartha1** [notepad-plus-plus/notepad-plus-plus#3995]
suppose I have a large text file

http://ge.tt/5ydxahn2

200,000 lines 

I want to insert a number to the left, 1,...200,000

So I click for the cursor to be at the beginning, and I click edit...column number, and I click ok..

But here is one problem, notice that when the line number reaches 100,000 then the space goes..

https://i.imgur.com/BeAvSem.png

And here is another problem that happens near the end of the file, 

https://i.imgur.com/0UdKn8s.png

And there is nothing unusual about the file it's just ASCII With CRLF

**Comment by sasumner** [comment]
First problem stems from the fact that the field with is assumed to be six (arbitrary choice?)
Second problem not reproducible with 7.5.3 32-bit portable.

**Comment by bocolo1** [comment]
thanks, I think maybe my version of notepad++ was 7.3 that was why.. now updated to 7.5.3 and seems to be ok.
