### ISSUE TITLE
Stuck at opening after XML folding

### ISSUE THREAD

**Issue by HispidaBytes** [notepad-plus-plus/notepad-plus-plus#3996]
### Description of the Issue
Notepad++ gets stuck at opening when there is a session with a folded XML file.
As a workaround, i have to delete the "session.xml" file in the "%appdata%/notepad++" folder.
Disabling all the plugins doesn't solve the problem.

### Steps to Reproduce the Issue
1. Start notepad++.
2. Open an XML file (for testing i've used a 2MB XML file)
3. Select from the menu View->Fold all
4. Close notepad++.
5. Open notepad++ again.
Here notepad++ is unable to open (I've waited more than 4 minutes and nothing happens).

### Debug Information
Notepad++ v7.5.3   (32-bit)
Build time : Dec  5 2017 - 10:45:46
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10 (64-bit)
Plugins : DSpellCheck.dll mimeTools.dll NppConverter.dll NppExport.dll NPPJSONViewer-win32.dll NppTextFX.dll PluginManager.dll XMLTools.dll 

Please feel free to ask if more informations are needed!
Thank you

**Comment by dail8859** [comment]
Is it possible to provide an example XML file that causes this issue? Also, try disabling your plugins as this might be part of the cause.

**Comment by HispidaBytes** [comment]
Hi, thank you for your response :)
I've tried to disable all the plugins but the problem still remains.
Here I upload to you a test xml file with which you can see the problem (the file is generated with [this tool](http://www.xml-benchmark.org/generator.html)). However you can reproduce the problem with any XML file that is at least 1MB big.

[nppTest.zip](https://github.com/notepad-plus-plus/notepad-plus-plus/files/1555939/nppTest.zip)

**Comment by SinghRajenM** [comment]
I tried with with attached xml, I could not reproduce. However, I noticed slight delay in opening if "fold all" is performed in previous instance (even without any plugin).

**Comment by HispidaBytes** [comment]
Yes the problem occurs only if "fold all" was selected in the previous instance. 
Except that I've tried in 3 different machines and with all 3 of them notepad gets stuck at opening (so it's not only getting a slight delay)

**Comment by ccammack** [comment]
I just tested this and my pull request #4386 fixes this issue and allows the fully-folded sample file to open in around 2 seconds on my machine. I'm running the fix in version 7.5.6 and would appreciate guidance on how to get the fix accepted.
