### ISSUE TITLE
auto-complete only works with API file, should work for builtin-languages in any case

### ISSUE THREAD

**Issue by GitMensch** [notepad-plus-plus/notepad-plus-plus#3998]
### Description of the Issue
If a language is supported (defined in langs[.model].xml) but no API\\\${lang}.xml is available the keywords given for the language should be used for auto-complete "function completion".

### Steps to Reproduce the Issue
1. Activate auto-completion with "function completion only"
2. Create a new file and choose COBOL highlighter (as there is no API shipped)
3. try to use auto-completion

### Expected Behavior
If no API\\\${lang}.xml is available is available but langs[.model].xml defines the current language the entries under `Keywords` should be used for auto-completion.

### Actual Behavior
No function completion is done if API\\\${lang}.xml is missing.

### Debug Information
Notepad++ v7.5.3 (32-bit)
Build time : Dec 5 2017 - 10:45:46
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10 (64-bit)
Plugins : ComparePlugin.dll DSpellCheck.dll LocationNavigate.dll mimeTools.dll NppConverter.dll NppExport.dll NppSaveAsAdmin.dll PluginManager.dll SourceCookifier.dll

**Comment by donho** [comment]
Auto-completion list is not necessary the same with the keywords of syntax highlighting. In some languages like COBOL  it could be the case but in the others they may need some different standard libraries' API, which are not in the keyword list.

**Comment by GitMensch** [comment]
> Auto-completion list is not necessary the same with the keywords of syntax highlighting. In some languages like COBOL it could be the case but in the others they may need some different standard libraries' API, which are not in the keyword list.

@donho I see. What do you think about using the keywords if API\${lang}.xml is missing?

**Comment by GitMensch** [comment]
Ping @donho I completely understand you're very busy with this project alone, not even taking life into account. Just want to recheck "What do you think about using the keywords for the built-in languages if, and only if their API${lang}.xml is missing?" (this is what the issue is about, not about the case where an api file exists).

**Comment by GitMensch** [comment]
Second thought: I vote to let the debugbuild open an msgbox if a builtin-language doesn't have an API file - this way the API file can simply be extracted from the keywords of the builtin-language and everything should be fine in the release builds, without the need (or a use) for a fallback.
Opinions?
