### ISSUE TITLE
Menu bar disappear after 126 tab created not saved

### ISSUE THREAD

**Issue by fredatgithub** [notepad-plus-plus/notepad-plus-plus#3999]
### Description of the Issue
 I have created 126 tabs without saving them and when I open NotePad++, the menu bar disappear and I cannot close the program, I have to kill the process

### Steps to Reproduce the Issue

1. Open Notepad++V7.5.3
2. Create 126 new tabs with text inside without saving them
3. close Notepad++
4. open Notepad++ and the menu bar disappear and close button doesn't work

### Expected Behavior
Menu bar still appears and close button works

### Actual Behavior
the menu bar disappear and close button doesn't work

### Debug Information
no debug info because the menu bar disappear 
screenshot:
![image](https://user-images.githubusercontent.com/6720055/33888637-f3490016-df4d-11e7-84cc-afb546b1cd70.png)

**Comment by SinghRajenM** [comment]
I could not reproduce. Issue may occur in something plugin.

Provide debug info. If you are not able to open notepad++ anymore, delete %appdata%/Notepad++/session.xml, then you must to able to open notepad++.

**Comment by sasumner** [comment]
I had fun trying to reproduce and crash it--couldn't, stopped around 300 tabs...  :)

**Comment by dail8859** [comment]
As suggested, please post your debug info and try disabling plugins as one of those might be the cause. Please reopen with any additional info.
