### ISSUE TITLE
Add encoding context menu on status bar 

### ISSUE THREAD

**Issue by justanotheranonymoususer** [notepad-plus-plus/notepad-plus-plus#400]
Recently, [this commit](https://github.com/notepad-plus-plus/notepad-plus-plus/commit/251e987a715cdb7ff829e23319677e849705a6b8#commitcomment-11999121) added 2 context menus on status bar:

> Add language context menu and EOL conversion context menu on status bar.

A natural addition to this would be the encoding menu.

**Comment by vlakoff** [comment]
+1,
I was just about to request this too!

**Comment by MetaChuh** [comment]
closed due to inactivity (3y)
