### ISSUE TITLE
Make the Preferences Window a bit taller?

### ISSUE THREAD

**Issue by mploug** [notepad-plus-plus/notepad-plus-plus#4001]
Hi,
I use the danish version of Notepad++.
Is it possible to make the Preferences Window a bit taller?
It is not easy to read all of the text.
I use version 7.5.2.
See the image attached.

![notepad](https://user-images.githubusercontent.com/34502347/33945828-6222ed8a-e020-11e7-96ef-3da778748472.png)

Kind regards, 
Martin

**Comment by sasumner** [comment]
Maybe make the Danish version of whatever text that is shorter?  :)

**Comment by mploug** [comment]
Yes, maybe the text could be just "Automatisk opdatering" instead?

**Comment by sasumner** [comment]
If it really bothers you (which would surprise me---but you've made an issue of it, so....)...did you know that you can change it yourself for your current setup?  In the danish.xml file in the localization folder, look for id="6323".  Change the text to whatever you want, then (possibly) restart and (possibly) reselect Danish as your language choice...should do it.

**Comment by mploug** [comment]
Yes, I know that it does not matter for functionality and it is not that important.
I have tried to  Change the text but it does not change anything.
At first I was not able to save the xlm file - see the image attached.
I had to change security in the  properties for the xml file.
But still it does not change anything.
![notepad xml](https://user-images.githubusercontent.com/34502347/33949266-6511db60-e029-11e7-9ff1-1a8220e02628.png)

**Comment by SinghRajenM** [comment]
Updating danish.xml does not effectively applied. Follow below steps.
1. First modify the danish.xml.
2. Now change language to English or any other (Settings->preferences->General->Localization).
3. Restart notepad++ and now change language again to Danish.

Or 
you can directly copy updated danish.xml to "%appdata/Notepad++" and rename it to "nativeLang.xml".

Hope this will help you.

**Comment by mploug** [comment]
I can not make it work.
Could you consider changing the text by default in future versions?
Otherwise, just forget it

Thanks for the help anyway.

**Comment by rddim** [comment]
#3058
#3223

**Comment by Faq** [comment]
should be fixed with https://github.com/notepad-plus-plus/notepad-plus-plus/commit/bbb21cd29967de48109a98174b6ae801e599c220

**Comment by MetaChuh** [comment]
fixed with https://github.com/notepad-plus-plus/notepad-plus-plus/commit/bbb21cd29967de48109a98174b6ae801e599c220
