### ISSUE TITLE
Find/Replace highlighter does not highlight all matches

### ISSUE THREAD

**Issue by MarcoMengoli** [notepad-plus-plus/notepad-plus-plus#4006]
### Description of the Issue
When searching for all occurrences of a string, not all of them are highlighted, although all of them are effectively found (end even replaced).

### Steps to Reproduce the Issue
1. Open the Find/Replace window
2. Insert the string to search
3. Put the cursor at the top of the file
4. Verify that the "Match whole word only" is not checked
5. Press the "Find next" button
6. Check if all the occurrences are effectively highlighted

### Expected Behavior
All occurrences of the searched string are actually highlighted.

### Actual Behavior
Not all occurrences of the searched string are actually highlighted.

### Debug Info
Notepad++ v7.3.3   (64-bit)
Build time : Mar  8 2017 - 03:39:58
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : ON
Local Conf mode : OFF
OS : Windows 7 (64-bit)
Plugins : mimeTools.dll NppConverter.dll 

### Example

Text:
`{
    ParameterA
	{
            "Caption" : "ParameterA",
            "Value"   : "0.01"
    },
	ParameterA_COPY
    {
			"Caption" : "ParameterA" ;
            "Value"   : "0.02" ;
	}
}`

Find
- Find what: "ParameterA"
- Press the "Count" button
- 4 instances are found
- 3 instances are highlighted

![errornotepadplusplus1](https://user-images.githubusercontent.com/11218341/33984931-70e83fe8-e0b9-11e7-845a-4dc8d89b0ef8.PNG)
![errornotepadplusplus2](https://user-images.githubusercontent.com/11218341/33984938-7487d262-e0b9-11e7-8ac3-623a1050f7a7.PNG)
![errornotepadplusplus3](https://user-images.githubusercontent.com/11218341/33984943-774e543a-e0b9-11e7-9ac2-61cf14792695.PNG)

**Comment by sasumner** [comment]
Don't mix up the "Find" feature with the "Smart Highlighting" feature.  They are 2 separate things that are totally unconnected.  That being said if you go into the Preferences for Highlighting and untick "Match whole word only", suddenly the inconsistency you describe will go away.  But again, unrelated, and no bug.  Recommend closure of this issue.

**Comment by MarcoMengoli** [comment]
You're perfectly right, thank you for your answer. I'm closing the [non] issue.
