### ISSUE TITLE
Error using vs2013 compile

### ISSUE THREAD

**Issue by softmgr** [notepad-plus-plus/notepad-plus-plus#4008]
### Description of the Issue
After compiling SciLexer.dll, I open the PowerEditor\visual.net\notepadPlus.vs2013.vcxproj, and then compile the project. ---- Json.hpp file error.

**Comment by SinghRajenM** [comment]
Json.hpp support many new features (C++11 and C++14) and few of them are not supported in VS2013. Now you need VS2015 or VS2017 to compile Notepad++.

**Comment by softmgr** [comment]
@SinghRajenM 
So please remove the file "PowerEditor\visual.net\notepadPlus.vs2013.vcxproj, so as not to cause 
misunderstandings, thank you!

**Comment by chcg** [comment]
notepadPlus.vs2013.vcxproj removed with https://github.com/notepad-plus-plus/notepad-plus-plus/commit/d14cb43e9d3c58d02af97149cd573c81bd862c47#diff-91f7886abd2e7f21c7fa79557be379c9555d51a8df7353811ec7d1476e04b261

and VS2017 is required, see https://github.com/notepad-plus-plus/notepad-plus-plus/blob/master/BUILD.md
