### ISSUE TITLE
OEM 720 encoding not working on  ver 7.5.x

### ISSUE THREAD

**Issue by hubaishan** [notepad-plus-plus/notepad-plus-plus#4009]
When saving a text file in OEM 720 encoding to use In Arabic DOS batch files. It saves in incorrect encoding

but ver 7.4.x works fine

**Comment by dail8859** [comment]
This is a known issue with v7.5.2 and v7.5.3. I recommend you stay with v7.5.1

Related issues #4014, #3991, #3990, #3986, #3983

Fix in #3992

**Comment by dail8859** [comment]
Closed by 1002865144aa6588b6bef0cb1d4250597d3fe0e7

This fix will be in the next release.
