### ISSUE TITLE
Crashes when pasting large content into a file

### ISSUE THREAD

**Issue by GaurangTandon** [notepad-plus-plus/notepad-plus-plus#401]
**What I did**
1. Took my CSS file. 715 lines.
2. Minified it online at cssminifer.com
3. Paste the contents back into the file.

**What happened** 
NPP crashed automatically. I did save a dump file.

**What I want**
Please fix it :-)

**Comment by ariccio** [comment]
How big?

**Comment by GaurangTandon** [comment]
@ariccio 715 lines, just as I said before.

**Comment by milipili** [comment]
The main issue here is probably very long lines since the content has been minified

**Comment by GaurangTandon** [comment]
@milipili Yes you are right. The minified file has around 8600 characters. But, I have bigger JS files and the issue doesn't arise when pasting them. That's strange!

**Comment by donho** [comment]
Update your Notepad++ to v7.6.6.
If this bug persists in the new release, please open a new issue with the debug information.
