### ISSUE TITLE
Notepad++ can't handle long lines (v. 7.5.2 and 7.5.3)

### ISSUE THREAD

**Issue by rng-58** [notepad-plus-plus/notepad-plus-plus#4010]
### Description of the Issue

I have a text file that contains a very long line (200000 lowercase letters). I can open it with v.7.5.1, but I can't open it with v.7.5.2 or 7.5.3.

### Steps to Reproduce the Issue

1. Create a text file (using v. 7.5.1). The file contains 200000 random lowercase letters, followed by a newline. Save it.
2. Install v.7.5.3, and try to open it by double-clicking the file.

### Expected Behavior

We can successfully open the file.

### Actual Behavior

Notepad++ freezes.

**Comment by CookiePLMonster** [comment]
Are you sure this is the exact repro path? I generated a text file consisting of 200000 random ASCII characters and a newline - and my v7.5.3 opens it instantly. Same with v7.5.4.

**Comment by trigifu** [comment]
I am having a similar issue. 
The line in question is much longer (38M characters).
It is mostly XML, so I am wondering if one of the plugins is the issue.
Is there a way to turn off Plugins and very this?

**Comment by AngryGamer** [comment]
[v.7.5.2+ reintroduced DSpellCheck.dll as a default plugin](https://notepad-plus-plus.org/community/topic/14846/notepad-7-5-2-release/4)

**Comment by jamesjohnmcguire** [comment]
Examples (unfortunately) I have run into are opening large SQL dump files that were made with extended inserts, so 1000s of records are all stored on 1 line.   Also, a XML file from a large de-zipped Excel file, which seems to be all on one line.  This has been going on since v6.*.* days, at least.

**Comment by MetaChuh** [comment]
please update your notepad++ to the latest 64 bit version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins if you update from version 7.5.9 or below.
if your issue still persists, and it is still of relevance, please feel free to file a new issue as easy to understand and reproducible as possible.

thank you for your help and best regards.
