### ISSUE TITLE
NPP FTP file load issue due to pathname + filename length

### ISSUE THREAD

**Issue by rwsss** [notepad-plus-plus/notepad-plus-plus#4011]
### Description of the Issue
Unable to load and open some files vie NPP FTP. Looks like the problem is caused by the length of a pathname.

### Steps to Reproduce the Issue
Seems like length combined with the filename causes the issue. 
I have a path that looks like /www.example.com/folder/subfbolder/ ... /filename.php (pathname + filename = 154 chars) and it loads just fine. It keeps loading fine if the pathname + filename are no longer than 159 chars.
However if there is a file long enough to make the pathname + filename 160 chars long (like /www.example.com/folder/subfbolder/ ... /filename111111.php ), then I see a quick load progress bar and then nothing.
If the filename + pathname is more than 160 chars long then file load doesn't even start.

### Expected Behavior
I expected a php file loaded and open in the editor.

### Actual Behavior
With this issue NPP keeps working just fine, no crashes or freeses. It just cant load those long file + pathnames.

### Debug Information
Notepad++ v7.5.3   (32-bit)
Build time : Dec  5 2017 - 10:45:46
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10 (64-bit)
Plugins : DSpellCheck.dll IndentByFold.dll mimeTools.dll NppConverter.dll NppExport.dll NppFTP.dll PluginManager.dll

**Comment by dail8859** [comment]
NppFTP is a 3rd party plugin and is not developed by this project. You will have to report this issue to the NppFTP developer.
