### ISSUE TITLE
"Find in finder" localization bug

### ISSUE THREAD

**Issue by softmgr** [notepad-plus-plus/notepad-plus-plus#4012]
### Description of the Issue
in "NppBigSwitch.cpp" code:

		case NPPM_INTERNAL_FINDINFINDERDLG:
		{
			const int strSize = FINDREPLACE_MAXLENGTH;
			TCHAR str[strSize];
			Finder *launcher = reinterpret_cast<Finder *>(wParam);

			bool isFirstTime = not _findInFinderDlg.isCreated();

			_findInFinderDlg.doDialog(launcher, _nativeLangSpeaker.isRTL());

			_pEditView->getGenericSelectedText(str, strSize);
			_findReplaceDlg.setSearchText(str);
			setFindReplaceFolderFilter(NULL, NULL);

			if (isFirstTime)
				_nativeLangSpeaker.changeFindReplaceDlgLang(_findReplaceDlg);  //BUG: This function statement does not implement the localisation of the window.

			return TRUE;
		}

### Steps to Reproduce the Issue

1. 
2. 
3.

**Comment by softmgr** [comment]
I fixed the problem...
To fix the problem, 3 files need to be modified. 
///////////////////////////////////////////////////////////////
//Modified code in NppBigSwitch.cpp:

		case NPPM_INTERNAL_FINDINFINDERDLG:
		{
			const int strSize = FINDREPLACE_MAXLENGTH;
			TCHAR str[strSize];
			Finder *launcher = reinterpret_cast<Finder *>(wParam);

			bool isFirstTime = not _findInFinderDlg.isCreated();

			_findInFinderDlg.doDialog(launcher, _nativeLangSpeaker.isRTL());

			_pEditView->getGenericSelectedText(str, strSize);
			_findReplaceDlg.setSearchText(str);
			setFindReplaceFolderFilter(NULL, NULL);

			if (isFirstTime)  //added by softmgr
				_nativeLangSpeaker.changeDlgLang(_findInFinderDlg.getHSelf(), "FindInFinder");  //added by softmgr
			//if (isFirstTime)
			//	_nativeLangSpeaker.changeFindReplaceDlgLang(_findReplaceDlg);  //BUG!!

			return TRUE;


///////////////////////////////////////////////////////////////
//Modified code in FindReplaceDlg.cpp:

void FindInFinderDlg::doDialog(Finder *launcher, bool isRTL)  //20171218:修改"Find in finder"窗口打开方式
{
	//added by softmgr
	_pFinder2Search = launcher;
	if (!isCreated())
	{
		_isRTL = isRTL;  //private added
		create(IDD_FINDINFINDER_DLG, isRTL);
	}
	::SetFocus(::GetDlgItem(_hSelf, IDFINDWHAT));
	display(true);
	return;


	
	/*
	_pFinder2Search = launcher;
	if (isRTL)
	{
		DLGTEMPLATE *pMyDlgTemplate = NULL;
		HGLOBAL hMyDlgTemplate = makeRTLResource(IDD_FINDINFINDER_DLG, &pMyDlgTemplate);
		::DialogBoxIndirectParam(_hInst, pMyDlgTemplate, _hParent, dlgProc, reinterpret_cast<LPARAM>(this));
		::GlobalFree(hMyDlgTemplate);
	}
	else
		::DialogBoxParam(_hInst, MAKEINTRESOURCE(IDD_FINDINFINDER_DLG), _hParent, dlgProc, reinterpret_cast<LPARAM>(this));
	*/
}


///////////////////////////////////////////////////////////////
//Added code in Notepad_plus.cpp:

bool Notepad_plus::reloadLang()
{
  //..............
	if (_findInFinderDlg.isCreated())
	{
		_nativeLangSpeaker.changeDlgLang(_findInFinderDlg.getHSelf(), "FindInFinder");
	}
  //..............
}

///////////////////////////////////////////////////////////////
Then add content to the language file, and the following:

            <FindInFinder title="Find in finder">
                <Item id="1711" name="......"/>
            </FindInFinder>

**Comment by softmgr** [comment]
To fix the problem, 3 files need to be modified. 
///////////////////////////////////////////////////////////////
//Modified code in NppBigSwitch.cpp:

		case NPPM_INTERNAL_FINDINFINDERDLG:
		{
			const int strSize = FINDREPLACE_MAXLENGTH;
			TCHAR str[strSize];
			Finder *launcher = reinterpret_cast<Finder *>(wParam);

			bool isFirstTime = not _findInFinderDlg.isCreated();

			_findInFinderDlg.doDialog(launcher, _nativeLangSpeaker.isRTL());

			_pEditView->getGenericSelectedText(str, strSize);
			_findReplaceDlg.setSearchText(str);
			setFindReplaceFolderFilter(NULL, NULL);

			if (isFirstTime)  //added by softmgr
				_nativeLangSpeaker.changeDlgLang(_findInFinderDlg.getHSelf(), "FindInFinder");  //added by softmgr
			//if (isFirstTime)
			//	_nativeLangSpeaker.changeFindReplaceDlgLang(_findReplaceDlg);  //BUG!!

			return TRUE;


///////////////////////////////////////////////////////////////
//Modified code in FindReplaceDlg.cpp:

void FindInFinderDlg::doDialog(Finder *launcher, bool isRTL)
{
	//added by softmgr
	_pFinder2Search = launcher;
	if (!isCreated())
	{
		_isRTL = isRTL;  //private added
		create(IDD_FINDINFINDER_DLG, isRTL);
	}
	::SetFocus(::GetDlgItem(_hSelf, IDFINDWHAT));
	display(true);
	return;


	
	/*
	_pFinder2Search = launcher;
	if (isRTL)
	{
		DLGTEMPLATE *pMyDlgTemplate = NULL;
		HGLOBAL hMyDlgTemplate = makeRTLResource(IDD_FINDINFINDER_DLG, &pMyDlgTemplate);
		::DialogBoxIndirectParam(_hInst, pMyDlgTemplate, _hParent, dlgProc, reinterpret_cast<LPARAM>(this));
		::GlobalFree(hMyDlgTemplate);
	}
	else
		::DialogBoxParam(_hInst, MAKEINTRESOURCE(IDD_FINDINFINDER_DLG), _hParent, dlgProc, reinterpret_cast<LPARAM>(this));
	*/
}


///////////////////////////////////////////////////////////////
//Added code in Notepad_plus.cpp:

bool Notepad_plus::reloadLang()
{
  //..............
	if (_findInFinderDlg.isCreated())
	{
		_nativeLangSpeaker.changeDlgLang(_findInFinderDlg.getHSelf(), "FindInFinder");  //added by softmgr
	}
  //..............
}

///////////////////////////////////////////////////////////////
Then add the following content to the language file: 

            <FindInFinder title="Find in finder">
                <Item id="1711" name="......"/>
            </FindInFinder>

**Comment by softmgr** [comment]
I fixed the problem...
To fix the problem, 3 files need to be modified. 
///////////////////////////////////////////////////////////////
//Modified code in NppBigSwitch.cpp:

		case NPPM_INTERNAL_FINDINFINDERDLG:
		{
			const int strSize = FINDREPLACE_MAXLENGTH;
			TCHAR str[strSize];
			Finder *launcher = reinterpret_cast<Finder *>(wParam);

			bool isFirstTime = not _findInFinderDlg.isCreated();

			_findInFinderDlg.doDialog(launcher, _nativeLangSpeaker.isRTL());

			_pEditView->getGenericSelectedText(str, strSize);
			_findReplaceDlg.setSearchText(str);
			setFindReplaceFolderFilter(NULL, NULL);

			if (isFirstTime)  //added by softmgr
				_nativeLangSpeaker.changeDlgLang(_findInFinderDlg.getHSelf(), "FindInFinder");  //added by softmgr
			//if (isFirstTime)
			//	_nativeLangSpeaker.changeFindReplaceDlgLang(_findReplaceDlg);  //BUG!!

			return TRUE;


///////////////////////////////////////////////////////////////
//Modified code in FindReplaceDlg.cpp:

void FindInFinderDlg::doDialog(Finder *launcher, bool isRTL)
{
	//added by softmgr
	_pFinder2Search = launcher;
	if (!isCreated())
	{
		//_isRTL = isRTL;  //added to private, if you need it.
		create(IDD_FINDINFINDER_DLG, isRTL);
	}
	::SetFocus(::GetDlgItem(_hSelf, IDFINDWHAT_FIFOLDER));
	display(true);
	return;


	
	/*
	_pFinder2Search = launcher;
	if (isRTL)
	{
		DLGTEMPLATE *pMyDlgTemplate = NULL;
		HGLOBAL hMyDlgTemplate = makeRTLResource(IDD_FINDINFINDER_DLG, &pMyDlgTemplate);
		::DialogBoxIndirectParam(_hInst, pMyDlgTemplate, _hParent, dlgProc, reinterpret_cast<LPARAM>(this));
		::GlobalFree(hMyDlgTemplate);
	}
	else
		::DialogBoxParam(_hInst, MAKEINTRESOURCE(IDD_FINDINFINDER_DLG), _hParent, dlgProc, reinterpret_cast<LPARAM>(this));
	*/
}


///////////////////////////////////////////////////////////////
//Added code in Notepad_plus.cpp:

bool Notepad_plus::reloadLang()
{
  //..............
	if (_findInFinderDlg.isCreated())
	{
		_nativeLangSpeaker.changeDlgLang(_findInFinderDlg.getHSelf(), "FindInFinder");  //added by softmgr
	}
  //..............
}

///////////////////////////////////////////////////////////////
Then add the following content to the language file: 

            <FindInFinder title="Find in finder">
                <Item id="1711" name="......"/>
            </FindInFinder>

**Comment by sasumner** [comment]
You're going at it backward.  You need to describe the issue here (following the template is a big clue as to how to do it), not solve it.  And no, '"Find in finder" localization bug' is not a sufficient issue description.

**Comment by softmgr** [comment]
@sasumner 
It took me 3 days to look at the source code of notepad++...
There are a lot of software problems, the code is very messy, and I don't know how the engineers of the software maintain it...

**Comment by dail8859** [comment]
Submitting a pull request is the best way to propose actual code changes. Pasting snippets of code is tedious, error prone, and not easy to see what has changed.

**Comment by sasumner** [comment]
@softmgr Software projects of any decent size and/or longevity tend to look "messy" to outsiders.  But that's irrelevant to how users should report issues and attempt to add work (for acceptance) to the project.
