### ISSUE TITLE
Auto-updater breaks with admin instance running

### ISSUE THREAD

**Issue by gjsmo** [notepad-plus-plus/notepad-plus-plus#4013]
### Description of the Issue

With an instance of Notepad++ which has been given admin privileges, trying to run the auto-updater prompts to close Notepad++ before updating and hangs. Notepad++ can be manually closed which allows it to continue.

### Steps to Reproduce the Issue

1. Open Notepad++ (older than previous version)
2. Open file which requires admin privileges to edit
3. Make a change and attempt to save, allow admin privileges when requested. Notepad++ restarts
4. Auto-update pops up - allow it
5. Updater asks to close Notepad++ - click Yes

### Expected Behavior

Auto-updater will close Notepad++ instances

### Actual Behavior

Auto-updater hangs

**Comment by MetaChuh** [comment]
not reproducible on newer notepad++ installer versions.
running 7.6.3 as administrator and invoking update to 7.6.6 will close the running notepad++ instance as expected.

please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins if you update from version 7.5.9 or below.

thank you for your help and best regards.

-----
```
general notes:

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).
please file an issue as easy to understand and reproducible as possible.

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
(no extra account is needed, just use your github account to sign in)
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)

**Comment by gjsmo** [comment]
Just tried this, running Windows 10 build `18890.rs_prerelease.190426-1618` and NPP `7.6.3`. Auto-updater definitely still hangs in the same way trying to go to 7.6.6.

Is there a log I can provide regarding this issue?
