### ISSUE TITLE
OEM 852 not working

### ISSUE THREAD

**Issue by JESTERHACK212** [notepad-plus-plus/notepad-plus-plus#4014]
### Steps to Reproduce the Issue

1. 
2. 
3.

**Comment by dail8859** [comment]
This is a known issue with v7.5.2 and v7.5.3. I recommend you stay with v7.5.1

Related issues #4009, #3991, #3990, #3986, #3983

Fix in #3992

**Comment by dail8859** [comment]
Closed by 1002865144aa6588b6bef0cb1d4250597d3fe0e7

This fix will be in the next release.
