### ISSUE TITLE
Plugin Manager Missing

### ISSUE THREAD

**Issue by gbiagomba** [notepad-plus-plus/notepad-plus-plus#4017]
### Description of the Issue
The past few releases I noticed the plugin manager was no longer present and when I tried to install the plugin manually it would not let me. I kept getting a prompt telling me the file wasn't compatible with this version. 

### Steps to Reproduce the Issue

1. Download the extension: https://sourceforge.net/projects/npppluginmgr/
2. Extract the file to %APPDATA%\notepad++\plugins
3. Restart notepad++

### Expected Behavior

Notepad++ to open/run as it normally does

### Actual Behavior

![image](https://user-images.githubusercontent.com/5851606/34272987-7917c678-e660-11e7-8eee-b42023d5b7c0.png)

### Debug Information

Notepad++ v7.5.3   (64-bit)
Build time : Dec  5 2017 - 10:47:54
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : ON
Local Conf mode : OFF
OS : Windows 7 (64-bit)
Plugins : DSpellCheck.dll mimeTools.dll NppConverter.dll

**Comment by dinkumoil** [comment]
You are running a 64 bit version of Notepad++ so you have to use the 64 bit version of the plugin manager too. You can download it [here](https://github.com/bruderstein/nppPluginManager/releases) (take the x64 version).

The plugin manager was removed from Notepad++ in v7.5 (see [here](https://notepad-plus-plus.org/news/notepad-7.5-released.html))

**Comment by gbiagomba** [comment]
@dinkumoil thank you sir and sorry for the late response
