### ISSUE TITLE
Function list for perl (both .pl and .pm) files empty

### ISSUE THREAD

**Issue by xbedax** [notepad-plus-plus/notepad-plus-plus#4019]
### Description of the Issue

Npp 7.5.3 (newly installed from scratch) shows empty function list.
There is no problem with exactly the same files on ver. 7.5.1

### Steps to Reproduce the Issue

1. Open a .pl file
2. Turn the func. list on (either using menu or toolbar)

### Expected Behavior

see the function list window filled with function names

### Actual Behavior

empty list window, jus the filename at the very first line

### Debug Information

Notepad++ v7.5.3   (32-bit)
Build time : Dec  5 2017 - 10:45:46
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 7 (64-bit)
Plugins : DSpellCheck.dll mimeTools.dll NppConverter.dll NppExport.dll 

according to bottom status line, the perl source is correctly detected

**Comment by MAPJe71** [comment]
See #2964.

**Comment by xbedax** [comment]
Thx a lot. As soon as I fixed the right functionlist.xml (in user profile, not the one in the npp directory) evrything worked fine :-) Sorry for missing the 2963 post.
