### ISSUE TITLE
Lua block comments not folding correctly

### ISSUE THREAD

**Issue by sparklicorn** [notepad-plus-plus/notepad-plus-plus#402]
In Lua, block comments are expressed as --[=*[(comment text)]=*] , where the opening and closing **have the same number** of zero to many equal signs.
Notepad++'s structural highlighting appears to get this correct, but the folding/collapsing functionality does not.
Notepad++ folds the block comment at the first ]=*] it sees, and not the expected closing brackets that have the same number of equal signs as the opening.

![np luaerror](https://cloud.githubusercontent.com/assets/10274296/8508208/7cd4ff98-2235-11e5-9eee-3cce33a1bb33.png)

**Comment by MetaChuh** [comment]
closed due to inactivity (4y)
