### ISSUE TITLE
"Find in Files" search does not give result

### ISSUE THREAD

**Issue by david-rougier** [notepad-plus-plus/notepad-plus-plus#4020]
### Description of the Issue
A "Find in Files" search with specific filter does not give result.

### Steps to Reproduce the Issue
1. Create a folder
2. Create X subfolders in the folder
3. Create a file named "Données A Saisir.txt" in a subfolder
4. Write "Test" in the file
5. Copy the file into the other subfolders
6. Do the following "Find in Files" search :
   - Find what : Test
   - Filters : Données A Saisir.txt
   - Directory : Path of the folder
   - In all sub-folders : Selected

### Expected Behavior
Find result : X hits in X files

### Actual Behavior
Find result : 0 hits in 0 files

### Debug Information
Notepad++ v6.5.5
Build time : Mar 7 2014 - 00:17:56

**Comment by dail8859** [comment]
Please don't submit big reports for a version nearly 4 years old.
