### ISSUE TITLE
Notepad++ crashes when disabling spell checking

### ISSUE THREAD

**Issue by natenho** [notepad-plus-plus/notepad-plus-plus#4022]
### Description of the Issue
Notepad++ crashes when disabling spell checking

### Steps to Reproduce the Issue

1. Click "Spell Check Document Automatically" button on toolbar

### Expected Behavior

Red underline spell errors along the text should be gone.

### Actual Behavior

Application crashes and close.

### Debug Information

Notepad++ v7.5.3   (64-bit)
Build time : Dec  5 2017 - 10:47:54
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10 (64-bit)
Plugins : DSpellCheck.dll mimeTools.dll NppConverter.dll 

![image](https://user-images.githubusercontent.com/4236481/34382789-794e70d2-eaf8-11e7-9a9f-2f0e9fe43e78.png)

**Comment by Predelnik** [comment]
Can you please check if updating Spell-checking plugin fixes the issue?
https://github.com/Predelnik/DSpellCheck/releases/tag/v1.3.5

**Comment by natenho** [comment]
Actually, installing Plugin Manager automatically updated DSpellCheck to 1.3.3 and solved the problem. Thanks
