### ISSUE TITLE
Unable to set KOI8 encoding to files

### ISSUE THREAD

**Issue by HYBRID-BEING** [notepad-plus-plus/notepad-plus-plus#4023]
### Steps to Reproduce the Issue
1. Create new file;
2. Input "Наличные";
3. Encode to Cyrillic - KOI8-R, KOI8-U, Macintosh.

### Expected Behavior
Status bar shows KOI8-R/KOI8-U encoding. Line is encoded in KOI8-R/KOI8-U/Macintosh.

### Actual Behavior
Nothing happens. Status bar shows the same encoding and line is still "Наличные".

### Debug Information
Notepad++ v7.5.3   (32-bit)
Build time : Dec  5 2017 - 10:45:46
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10 (64-bit)
Plugins : DSpellCheck.dll mimeTools.dll NppConverter.dll NppExport.dll NppFTP.dll PluginManager.dll Python Indent.dll

**Comment by HYBRID-BEING** [comment]
Ah, this is probably related to #3992, i guess.

**Comment by dail8859** [comment]
Closed by 1002865144aa6588b6bef0cb1d4250597d3fe0e7

This fix will be in the next release.
