### ISSUE TITLE
CJK ideographs instead of Russian on OEM 866 charset

### ISSUE THREAD

**Issue by green-AV** [notepad-plus-plus/notepad-plus-plus#4026]
### Description of the Issue
Recently updated from 7.5.1 to 7.5.3, and something changed. When Cyrillic **OEM 866** character set is being used, no more Russian letters appear in an opened document. Instead of Russian letters, CJK ideographs, sometimes followed by **€**, appear.
`-noPlugin` gives no effect on the issue.
### Steps to Reproduce the Issue
Open any text file, saved in OEM 866 codepage, and containing Russian letters. Then change charset to **Cyrillic > OEM 866**. Where the letters are?
### Debug Information
Notepad++ v7.5.3   (32-bit)
Build time : Dec  5 2017 - 10:45:46
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : ON
Local Conf mode : OFF
OS : Windows 7 (64-bit)
Plugins : ComparePlugin.dll CustomizeToolbar.dll DSpellCheck.dll mimeTools.dll NppColumnSort.dll NppConverter.dll NppExport.dll NppFTP.dll NppTextFX.dll PluginManager.dll ShtirlitzNppPlugin.dll SpeechPlugin.dll zoomdisabler.dll

**Comment by dinkumoil** [comment]
A fix is on its way. See #3992.

**Comment by dail8859** [comment]
This is fixed in v7.5.4
