### ISSUE TITLE
[Bug or Issue] After using HexEditor causes n++ to freeze using certain menus

### ISSUE THREAD

**Issue by wonkawilly** [notepad-plus-plus/notepad-plus-plus#4027]
### Description of the Issue

Notepad ++ freezes when I use hexadecimal editor (Hex Editor) (H icon) and I try to use certain menus of the standard menu bar:
File
Edit
Search
View

Other menus work normally

When n++ freezes I have to terminate the process with task manager.
It freezes in both scenarios if H (Hex viewer) is still active when I use such menus and even if I activate the hex viewer and I close it and than I use menus (after closing it).

### Steps to Reproduce the Issue

1. Just turn on and off the Hex editor
2. Use one of the listed menus

### Expected Behavior
To not freeze

### Actual Behavior
Freezes and I have to close the application

### Debug Information
Notepad++ v7.3.1   (32-bit)
Build time : Jan 17 2017 - 00:21:10
Path : E:\Software\npp.7.3.1.bin\notepad++.exe
Admin mode : OFF
Local Conf mode : ON
OS : Windows 7
Plugins : CodeAlignmentNpp.dll combine.dll ComparePlugin.dll CSScriptNpp.dll DSpellCheck.dll ElasticTabstops.dll Explorer.dll gtagfornplus.dll **HexEditor.dll** HTMLTag_unicode.dll ImgTag.dll JSLintNpp.dll JSMinNPP.dll linefilter2.dll mimeTools.dll MultiClipboard.dll NppAutoIndent.dll NppCCompletionPlugin.dll NppColumnSort.dll NppConverter.dll NppExec.dll NppExport.dll NppFTP.dll NppMenuSearch.dll NppQCP.dll NppTextFX.dll NppToolBucket.dll PluginManager.dll PreviewHTML.dll PythonScript.dll QuickOpenPlugin.dll RunMe.dll SourceCookifier.dll WebEditU.dll XBrackets.dll ZenCoding-Python.dll

**Comment by ArkadiuszMichalski** [comment]
@sasumner
This is probably for the plugin author (or some actual fork, like https://github.com/chcg/NPP_HexEdit).

**Comment by wonkawilly** [comment]
> @sasumner
> This is probably for the plugin author (or some actual fork, like https://github.com/chcg/NPP_HexEdit).

Thank you: published on https://github.com/chcg/NPP_HexEdit/issues/49
