### ISSUE TITLE
[Feature Request] Adding a new button to Find and Replace dialog

### ISSUE THREAD

**Issue by wonkawilly** [notepad-plus-plus/notepad-plus-plus#4029]
### Description of the New feature Request
Add a new button to the Find and Replace and Find in Files Dialog to allow switching of the Searched text with the Replacement text and viceversa. See the image bellow for more clarifications:

![n](https://user-images.githubusercontent.com/34818345/34460527-88a1c400-ee11-11e7-8df0-a99b56d03e41.png)

**Comment by sasumner** [comment]
Closing this as the more-recent #6010 is a perfect duplicate.

**Comment by wonkawilly** [comment]
> Closing this as the more-recent #6010 is a perfect duplicate.

Yes thanks sasumner.

**Comment by sasumner** [comment]
There is no "delete".  These things are permanent.  The only thing that can be done is to close it as I did 11 hours earlier.

**Comment by wonkawilly** [comment]
> There is no "delete". These things are permanent. The only thing that can be done is to close it as I did 11 hours earlier.

Good enough for me ;-) Thank you
