### ISSUE TITLE
Importing an User defined language doesn't check for existing languages with the same name

### ISSUE THREAD

**Issue by gallegretti** [notepad-plus-plus/notepad-plus-plus#403]
In the User Defined Language Dialog, whenever you `Create new...` or `Save as...` or `Rename`, N++ checks if there already is an existing language with the name you selected. If so, you get an error. But if you `Import...`, the check is not made. This can lead to multiple User Defined Languages with the same name.

Steps:
Open N++
Navigate to Language->Define your language->Import
Select a valid file and click open
Import the same file again

Actual result: N++ now has two languages with the same name.
Expected result: Error dialog, as presented [here](https://github.com/notepad-plus-plus/notepad-plus-plus/blob/master/PowerEditor/src/ScitillaComponent/UserDefineDialog.cpp#L1259) and [here](https://github.com/notepad-plus-plus/notepad-plus-plus/blob/master/PowerEditor/src/ScitillaComponent/UserDefineDialog.cpp#L1307). Btw, both of them have the same typo: "Err" insted of "Error".

**Comment by prclx323800** [comment]
+1. At the same time, I request an option to **replace** the old User Defined Language with the new one, That would be convenient for me if I have changed a language on one computer and want to apply it on another computer. Currently I have to delete the old one and then import the new one.

**Comment by milipili** [comment]
A dialog box asking to overwrite the user defined language should answer to both requests.

**Comment by donho** [comment]
Update your Notepad++ to v7.6.6.
If this bug persists in the new release, please open a new issue with the debug information.
