### ISSUE TITLE
Very very slow when I open an mysql script file dumped with mysqldump,

### ISSUE THREAD

**Issue by chjq68** [notepad-plus-plus/notepad-plus-plus#4036]
### Description of the Issue

I dumped a sql script with mysqldump, in which there is lines very long with insert statement of multi values. When open the file with notepad++, notepad++ become very very slow. 
### Steps to Reproduce the Issue

1.  Make a sql script file with line length over 1000000 chars (utf8)
2.  open it with notepad++
3. search with ctrl+F

### Expected Behavior

I want it faster.

**Comment by MetaChuh** [comment]
not reproducible on 7.6.6 with the given information.

please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins if you update from version 7.5.9 or below.
if your issue still persists, and it is still of relevance, please feel free to file a new issue as easy to understand and reproducible as possible.

thank you for your help and best regards.

-----
```
general notes:

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).
please file an issue as easy to understand and reproducible as possible.

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
(no extra account is needed, just use your github account to sign in)
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)

**Comment by architpuri** [comment]
It can be reproduced by dumping a database having file data. (BLOB)
With > 10 files at least.
