### ISSUE TITLE
RegEx Find fails

### ISSUE THREAD

**Issue by IEales** [notepad-plus-plus/notepad-plus-plus#4039]
### Description of the Issue
RegEx ' \(.*\)' without '' fails and misses  ) until last

When a GI platoon lands on the beaches of Italy during World War II, the troops face uncertainty and danger with every step. Those who survive the initial landing, including Sgt. Tyne **_(Dana Andrews) and Sgt. Ward (Lloyd Bridges)_**, pursue a mission to take control of a farmhouse and blow up a nearby bridge. When the soldiers are not involved in enemy engagements,they pass the time in conversation while marching through the Italian countryside, but they always keep their objectives in mind.

### Steps to Reproduce the Issue
1. open file with multiple items in parenthesis
2. Open Replace dialog
3. Enter RegEx ' \(.*\)' without quotes ''
3. Hit Find

### Expected Behavior
find each item in parenthesis

### Actual Behavior
misses first ) and selects everything between first ( and last )

### Debug Information
Notepad++ v7.5.3   (32-bit)
Build time : Dec  5 2017 - 10:45:46
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10 (64-bit)
Plugins : ComparePlugin.dll CustomizeToolbar.dll DSpellCheck.dll LightExplorer.dll mimeTools.dll NppConverter.dll NppExport.dll NppFTP.dll NppGTags.dll NppTextFX.dll PluginManager.dll SourceCookifier.dll SourceSwitch.dll SpellChecker.dll XMLTools.dll

**Comment by DavidHansen-0x454d43** [comment]
.* is a greedy quantifier, which means it does exactly what you are seeing.... 
you probably want to use a lazy quantifier: .*?

**Comment by DavidHansen-0x454d43** [comment]
@IEales  Also, I'm not sure if you are escaping your parenthesis. 
To match **(Dana Andrews)** and **(Lloyd Bridges)**, I had to use the expression:
\(.*?\)

**Comment by IEales** [comment]
On 1/2/2018 13:00, David Hansen wrote:
    
    
      .* is a greedy quantifier, which means it does exactly what you
        are seeing....
        you probably want to use a lazy quantifier: .*?
      —
        You are receiving this because you authored the thread.
        Reply to this email directly, view it on GitHub, or mute the thread.
      
        
          
          
        
        
      
      {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/notepad-plus-plus/notepad-plus-plus","title":"notepad-plus-plus/notepad-plus-plus","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/notepad-plus-plus/notepad-plus-plus"}},"updates":{"snippets":[{"icon":"PERSON","message":"@DavidHansen-0x454d43 in #4039: .* is a greedy quantifier, which means it does exactly what you are seeing.... \r\nyou probably want to use a lazy quantifier: .*?\r\n"}],"action":{"name":"View Issue","url":"https://github.com/notepad-plus-plus/notepad-plus-plus/issues/4039#issuecomment-354874097"}}}
    
    Thanks! Adding ? worked.
    
    -- 

- Ian

**Comment by sasumner** [comment]
@IEales , try asking such a simple thing on one of the forums next time.  So many issues we don't need more pure clutter here.
