### ISSUE TITLE
The names of the UTF-8 encodings in the Menu bar and in the Status bar are different

### ISSUE THREAD

**Issue by pfparesseux000** [notepad-plus-plus/notepad-plus-plus#4040]
### Description of the Issue

In notepad++ with English localization, the names of the UTF-8 encodings in the Menu bar and in the Status bar are different.

### Steps to Reproduce the Issue

- Encode in UTF-8 without BOM
1. Select Menu bar > Encoding > Encode in UTF-8 without BOM,
2. It displays UTF-8 in Status bar.

- Encode in UTF-8 with BOM
1. Select Menu bar > Encoding > Encode in UTF-8,
2. It displays UTF-8 BOM in Status bar.

- Convert to UTF-8 without BOM
1. Select Menu bar > Encoding > Convert to UTF-8 without BOM,
2. It displays UTF-8 in Status bar.

- Convert to UTF-8 with BOM
1. Select Menu bar > Encoding > Convert to UTF-8,
2. It displays UTF-8 BOM in Status bar.

### Expected Behavior

- Encode in UTF-8 without BOM
When selecting Menu bar > Encoding > Encode in UTF-8 without BOM, it should display "UTF-8 without BOM" in Status bar.

- Encode in UTF-8 with BOM
In Menu bar > Encoding, "Encode in UTF-8" shoud be replaced with "Encode in UTF-8 with BOM".
And it should display "UTF-8 with BOM" in Status bar.

- Convert to UTF-8 without BOM
When selecting Menu bar > Encoding > Convert to UTF-8 without BOM, it should display "UTF-8 without BOM" in Status bar.

- Convert to UTF-8 with BOM
In Menu bar > Encoding, "Convert to UTF-8" shoud be replaced with "Convert to UTF-8 with BOM".
And it should display "UTF-8 with BOM" in Status bar.

It will be more clearer.
Not like Windows Notepad, and its Save as UTF-8.

### Actual Behavior

- When selecting Menu bar > Encoding > Encode in UTF-8 without BOM, it displays UTF-8 in Status bar.
- When selecting Menu bar > Encoding > Encode in UTF-8, it displays UTF-8 BOM in Status bar.
- When selecting Menu bar > Encoding > Convert to UTF-8 without BOM, it displays UTF-8 in Status bar.
- When selecting Menu bar > Encoding > Convert to UTF-8, it displays UTF-8 BOM in Status bar.

### Debug Information

Notepad++ v7.5.4   (32-bit)
Build time : Jan  1 2018 - 01:47:45
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10 (32-bit)
Plugins : DSpellCheck.dll mimeTools.dll NppConverter.dll NppExport.dll

**Comment by dail8859** [comment]
This is what I am seeing:

![utf8](https://user-images.githubusercontent.com/3694843/34524327-305d4328-f069-11e7-8ed0-86c46831d79a.png)

---

![utf8bom](https://user-images.githubusercontent.com/3694843/34524332-35faced6-f069-11e7-849a-59df1d0b1c08.png)


```
Notepad++ v7.5.4   (32-bit)
Build time : Jan  1 2018 - 01:47:45
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 7 (64-bit)
Plugins : BetterMultiSelection.dll ComparePlugin.dll DoxyIt.dll DSpellCheck.dll ElasticTabstops.dll FingerText.dll LuaScript.dll MarkdownViewerPlusPlus.dll NppEditorConfig.dll NppExport.dll PluginManager.dll Scintillua++.dll SurroundSelection.dll 
```

**Comment by pfparesseux000** [comment]
@dail8859, I confirm your screenshots. It's OK for me in English localization.
I'm testing from the beginning and I'ill give news.

**Comment by pfparesseux000** [comment]
I tested again and I found how to reproduce the issue.

First, I explain why I created this issue.

I created this issue because in Notepad++ with French localization, the names of the encodings in the Menu bar and in the Status bar were different.
I tried to find where the problem come from, in the French localization or in the English localization ?


Now, when the names of the UTF-8 encodings in the Menu bar and in the Status bar are different ?

I change the localization from French to English without restarting Notepad++.
The names of the encodings in the Menu bar and in the Status bar are different.
But after restarting Notepad++, the names of the encodings in the Menu bar and in the Status bar are finally identical.


### Steps to Reproduce the Issue

1. If it's not already the case, use Notepad++ with French localization.
- Go to Menu bar > Settings > Preferences...
- The Preferences Window appears.
- Go to General > Localization.
- Select Français.
- Click Fermer.

2. In French localization, the names of the encodings in the Menu bar and in the Status bar are different.
I'll create a new issue for this problem next time.
- Select Menu Bar > Encodage > Encoder en UTF-8 (sans BOM), it displays UTF-8 in Status bar.
- Select Menu Bar > Encodage > Encoder en UTF-8, it displays UTF-8 BOM in Status bar.
- Select Menu Bar > Encodage > Encoder en UTF-16BE, it displays UCS-2 BE BOM in Status bar.
- Select Menu Bar > Encodage > Encoder en UTF-16LE, it displays UCS-2 LE BOM in Status bar.
- Select Menu Bar > Encodage > Convertir en UTF-8 (sans BOM), it displays UTF-8 in Status bar.
- Select Menu Bar > Encodage > Convertir en UTF-8, it displays UTF-8 BOM in Status bar.
- Select Menu Bar > Encodage > Convertir en UTF-16BE, it displays UCS-2 BE BOM in Status bar.
- Select Menu Bar > Encodage > Convertir en UTF-16LE, it displays UCS-2 LE BOM in Status bar.

3. Change to English Localization.
- Go to Menu bar > Paramétrage > Préférences...
- The Préférences Window appears.
- Go to Général > Langue.
- Select English.
- Click Close

4. Do not restart Notepad++.

5. In English localization, the names of the encodings in the Menu bar and in the Status bar are different.
- Select Menu Bar > Encoding > Encode in UTF-8 without BOM, it displays UTF-8 in Status bar.
- Select Menu Bar > Encoding > Encode in UTF-8,it displays UTF-8 BOM in Status bar.
- Select Menu Bar > Encoding > Convert to UTF-8 without BOM, it displays UTF-8 in Status bar.
- Select Menu Bar > Encoding > Convert to UTF-8,it displays UTF-8 BOM in Status bar.

6. Restart Notepad++.

7. In English localization, the names of the encodings in the Menu bar and in the Status bar are finally identical.

**Comment by SinghRajenM** [comment]
Reproduce steps really helped to analyze this issue.

_**Root Cause:**_
When language is changed, npp creates a copy of desired language as (nativeLang.xml) in %appdata%/Notepad++ and use it further reflect same on the UI immediately. As there was error in translated string xml (English.xml), it causes this issue.

Why issue does not occur in English when npp is restarted?
npp does not load nativeLang.xml when English is your preferred language. It just uses strings directly from binary itself.
