### ISSUE TITLE
When shutdown windows,  notpad++ show "Access violation"

### ISSUE THREAD

**Issue by chjq68** [notepad-plus-plus/notepad-plus-plus#4044]
### Description of the Issue

Open some files and new some files (about 10 windows opened)
### Steps to Reproduce the Issue

1.  Shutdown windows 10 when notpad++ did not closed
### Actual Behavior

2. Notpad++ popup "Access violation" multi times
### Debug Information

Notepad++ v7.5.3   (32-bit)
Build time : Dec  5 2017 - 10:45:46
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10 (64-bit)
Plugins : DSpellCheck.dll mimeTools.dll NppConverter.dll NppExport.dll

**Comment by dail8859** [comment]
This is due to a bug with the DSpellCheck plugin. You can either install Notepad++ v7.5.4 (which contains a fixed version of the plugin) or manually download the plugin [here](https://github.com/Predelnik/DSpellCheck/releases/tag/v1.3.5).
