### ISSUE TITLE
Error in RC File highlighting Issue

### ISSUE THREAD

**Issue by SinghRajenM** [notepad-plus-plus/notepad-plus-plus#4047]
Syntax highlighting is not proper in RC file if the string contains escape sequence.

### Steps to Reproduce the Issue

1. Open notepad++
2. Create new file and copy below text
3. Change Language as resource file

### Expected Behavior

All the line should look similar to first line. I mean should be treated as string contents.

### Actual Behavior

Highlighting is not proper. Refer screen shot.

### Debug Information

Notepad++ v7.5.4   (32-bit)
Build time : Jan  1 2018 - 01:47:45
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10 (64-bit)
Plugins : DSpellCheck.dll mimeTools.dll NppConverter.dll NppExport.dll 

![image](https://user-images.githubusercontent.com/14791461/34575056-5f2ddf46-f19f-11e7-97ef-1541f81e0246.png)

**Comment by dail8859** [comment]
Is that the correct syntax to use for escaping the quotes? In normal C/C++ you'd use something like:

```c
"Add \"%s\" to Dictionary"
```

Not sure if the same applies to resource files. Also, the [MSDN documentation](https://msdn.microsoft.com/en-us/library/windows/desktop/aa381050(v=vs.85).aspx) says:

> To embed quotes in the string, use the following sequence: ""

**Comment by SinghRajenM** [comment]
Created sample app and added ```Add "%s" to Dictionary``` in stringtable using built-in resource editor. Microsoft adds
``` "Add ""%s"" to Dictionary1" ``` in rc file. However changing as ``` "Add \""%s\"" to Dictionary" ``` also works fine as it is working in DSpellCheck. But this rc is generated using ResEdit which might saved using escape character.

**Comment by SinghRajenM** [comment]
Closing.
