### ISSUE TITLE
Save as dialog freezes up.  

### ISSUE THREAD

**Issue by wboswall** [notepad-plus-plus/notepad-plus-plus#4048]
### Description of the Issue

When clicking save as or using the key combination of 'Save As' to save files to desktop the save as window freezes up.   
### Steps to Reproduce the Issue

1. Click Save or save as 

### Expected Behavior

window dialog freezes up
### Actual Behavior

actually freezes up and have to kill it. 
### Debug Information

couldn't find any.

![noteplusplus](https://user-images.githubusercontent.com/34065293/34587503-f5c5b31e-f17e-11e7-8ab7-9ec9a57f9db3.PNG)
This happens in all of the x86, x64, and the non-installer distributions for this program. 
This has been happening for a while and can't figure out what could be causing it.  Any suggestions are much appreciated.

**Comment by andreszs** [comment]
It looks more like a system issue. Anyway, you can try to completely uninstall and manually erase the reg settings, restart, and install N++ again as a brand new setup.

**Comment by wboswall** [comment]
I have done that but it keeps doing that.  I've even tried it again when after a cold boot up so it's not a computer problem.

**Comment by MetaChuh** [comment]
please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins if you update from version 7.5.9 or below.

go to `settings > preferences > default directory` and activate `use new style dialog`. 
if your issue still persists, and it is still of relevance, please feel free to file a new issue as easy to understand and reproducible as possible.

thank you for your help and best regards.

**Comment by wboswall** [comment]
Thank you for looking into it.  It has since automatically updated itself and doesn't seem to do it anymore.  Also your right that it could be an OS problem.  But Microsoft Windows does freeze up which is not surprising since it is a resource intensive OS.  Unlike Linux or Mac that doesn't freeze up rarely.
