### ISSUE TITLE
Pane jumps on mouse-down on close button

### ISSUE THREAD

**Issue by Eldaw** [notepad-plus-plus/notepad-plus-plus#405]
Steps to reproduce:
1.) Enable 'Show close button on each tab'
2.) Have 2 files open.
3.) Right-click the tab of one of them and 'Move to other view', so that you've got 2 panes with files open.
4.) Manually adjust (drag) the position of the splitter separating the two panes.
5.) In the second pane (i.e. the one on the right, or the one at the bottom) click the close button on the tab of the open file. To see what happens more clearly, don't release the mouse button -- keep an eye on what happens on the mouse-down event.

If the second pane was on the right, then the entire pane jumps slightly to the left (the splitter moves to the left), so that your mouse cursor is no longer even over the close button. If the second pane was at the bottom, the entire pane moves slightly up (the splitter position moves up).

**Comment by jsuar** [comment]
I was able to replicate this issue. Even if you collapse the left side completely (with the black arrow at the top of the center divider), clicking the close button makes the window jump to the right.
