### ISSUE TITLE
NppTextFX.dll

### ISSUE THREAD

**Issue by michelg77** [notepad-plus-plus/notepad-plus-plus#4050]
### Description of the Issue
double opening/running of notepad++ with xp/sp3 
and a very slow processor

### Steps to Reproduce the Issue
1. xp/sp3 loading, launch notepad++
2. a few seconds later, launch notepad++ again,
while xp/sp3 loading programs
3. look at the 2 messages.

### Expected Behavior
no message at all.

### Actual Behavior
see the 2 attached files.

### Debug Information
none.

![image](https://user-images.githubusercontent.com/35131446/34599550-4b740a44-f1f3-11e7-9992-60fd34d0761a.png)
![image](https://user-images.githubusercontent.com/35131446/34599559-5c1d8398-f1f3-11e7-99d1-9be4f5534a78.png)

**Comment by sasumner** [comment]
This is not an issue (at least for THIS issues list).  Please close.

**Comment by michelg77** [comment]
I'm not used to github.com.
I had just made a few years ago my website with PHP and MySQL.
Please move this on the right place if it isn't.
I'm too old now to spend a lot of time to do that.

**Comment by michelg77** [comment]
But I'm really "mad" about notepad++.
It's a pity it doesn't exist for my pixi 3 tablet.
