### ISSUE TITLE
CTRL-F  Search

### ISSUE THREAD

**Issue by tmieske** [notepad-plus-plus/notepad-plus-plus#4052]
When I press CTRL-F, the program 'crashes! 
I completely deleted the program, saved options & program directory

I'm running Win 7 64-Bit

**Comment by yut45390** [comment]
I cannot reproduce.
When I press Ctrl-F, the Find Dialog box appears.
Which version of notepad++ are you using?
I am using windows 10 and notepad++ 7.5.3

**Comment by tmieske** [comment]
It started about 5 versions back.  I uninstalled it completely today,reboot and installed today's new release.  Sam problem.
-ted

**Comment by cmeriaux** [comment]
Try to do a fresh install (remove your user files C:\Users\xxxx\AppData\Roaming\Notepad++ ) 
Your saved configuration may be corrupted and generates silent exceptions.

You also can try the protable version https://notepad-plus-plus.org/repository/7.x/7.5.4/npp.7.5.4.bin.zip

**Comment by tmieske** [comment]
See note below:

**Comment by cmeriaux** [comment]
don't forget to close the issue.

**Comment by tmieske** [comment]
Sorry, I'm old, cold and slow!!  Please send me a link so I can closethis issue.  Thanks, Ted
