### ISSUE TITLE
(CTRL+F) Option to Swap "Find what :" ... "Replace what: " ...

### ISSUE THREAD

**Issue by themaverick** [notepad-plus-plus/notepad-plus-plus#4055]
### Description of the Issue
I would like to be able to swap the values in both these text boxes.
Ex: Need to find all the cats and replace with dogs.
Find what : cats.cmd
Replace what : dogs.cmd

Now I need to do the opposite. 

No such easy option as to having to retype all the potential syntax etc.

Pretty easy fix programmatically. It could either be a button or a shortcut on the keyboard or both! :D

**Comment by andreszs** [comment]
Nice idea, but you can forget about it because Npp will never alter its GUI, not even for the slightest improvement. More on this [here](https://notepad-plus-plus.org/community/category/2/general-discussion).

**Comment by DavidHansen-0x454d43** [comment]
@andreszs do you have a link to a specific thread where this is discussed? Are you referring to "[Feature request: enable key bindings without modifier keys](https://notepad-plus-plus.org/community/topic/14686/feature-request-enable-key-bindings-without-modifier-keys)"? 

I'm just wondering if that is your opinion or if @donho has stated as much...

**Comment by ArkadiuszMichalski** [comment]
@sasumner Not dupliacate for https://github.com/notepad-plus-plus/notepad-plus-plus/issues/6010?

**Comment by sasumner** [comment]
Closing as the aforementioned duplicate.
