### ISSUE TITLE
Inconsistent display of certain Unicode symbol characters

### ISSUE THREAD

**Issue by hockeyguy2** [notepad-plus-plus/notepad-plus-plus#4056]
### Description of the Issue
Certain symbol characters (set A) are displayed inconsistently, depending on whether certain other symbol characters (set B) appear on the same line.  If set A characters are present without any set B characters, they are displayed as the fallback "box" glyph (which looks like U+25AF ▯).  If any set B characters are present, the set A characters (as well as the set B characters) are displayed with the appropriate glyphs.

I haven't experimented extensively to see how many characters fall into each category, but here are the ones that caused me to notice this issue:

Set A:
  U+26A0 ⚠ (warning triangle)
  U+26D4 ⛔ (do not enter symbol )

Set B:
  U+2713 ✓ (checkmark)
  U+2764 ❤ (heart symbol)
  U+2794 ➔ (right arrow)

### Steps to Reproduce the Issue
General steps (seem to be completely context-independent):
1. On a blank line, insert one of the "set A" characters
2. Notice that the character is displayed a the fallback "box" glyph
3. Insert one of the of the "set B" characters on the same line
4. Notice that both characters are now displayed with their proper glyphs, rather than the fallback.

Not sure if this will work in the web app, but I'll give it a try:
  Step 2 looks like this: ▯
  Step 4 looks like this: ⚠✓

If for some reason the steps don't work in a particular setup, here's a complete, specific set of steps:
1. Start with a clean install of Notepad++, using all the default installation settings
2. Open a new tab
3. Copy the U+26A0 character from another application and paste it into Notepad++
4. Notice the fallback glyph
5. Copy the U+2713 character from another application and paste it into Notepad++
5. Notice the proper glyphs for both characters.

### Expected Behavior
I would expect that the "set A" characters would be displayed consistently.  If they are supported in the relevant font, I would expect them to be displayed with their proper glyphs.  If they are not supported in the relevant font, I would expect them to be displayed with the fallback glyph.  I would not expect the display of the "set A" characters to be affected by the presence of other characters on the same line.

### Actual Behavior
Fallback glyph is displayed when "set A" characters appear on a line without "set B" characters, but this changes to the proper glyph is a "set B" character is inserted on the same line.

### Debug Information
Notepad++ v7.5.4   (64-bit)
Build time : Jan  1 2018 - 01:50:29
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10 (64-bit)
Plugins : DSpellCheck.dll mimeTools.dll NppConverter.dll 

Note that I also repeated the above scenarios with all plugins disabled, and I saw identical results.

**Comment by chcg** [comment]
Seems to be related to https://github.com/notepad-plus-plus/notepad-plus-plus/issues/675

**Comment by hockeyguy2** [comment]
Thanks to the comments noted above, I was able to identify this as being the same underlying issue as for #675 and #813.  However, the titles of those items are somewhat less clear as to the scope of the issue, namely that glyphs are being chosen inconsistently depending on the **context** of the code points in question.

I also tried various fonts and discovered that this problem disappears with many font selections.  (This is easy to check, thanks to the N++ feature of "previewing" any change to the default font selection, rather than having to click OK to see the results.)

After some additional research, I'm guessing this has to do with script-detection logic that isn't working exactly as intended.  Perhaps for reasons of efficiency, font fallback for unsupported code points does not appear to be done on a per-character basis, but rather by detecting the script for a block (i.e. line, as it appears in this case).  This would explain why adding certain characters would change the display, as they would affect the detected script for the line.

Maybe someone with better knowledge of font fallback and script detection can provide a more definitive explanation.

**Comment by MetaChuh** [comment]
please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins if you update from version 7.5.9 or below.
if your issue still persists, and it is still of relevance, please feel free to file a new issue as easy to understand and reproducible as possible.

<img width="966" alt="" src="https://user-images.githubusercontent.com/45773305/57084257-46629380-6cfa-11e9-899a-463c060d78ea.png">

thank you for your help and best regards.
