### ISSUE TITLE
Save As dialog: buttons are too small on high DPI display

### ISSUE THREAD

**Issue by zzort** [notepad-plus-plus/notepad-plus-plus#4058]
### Description of the Issue
On a high DPI display the button icons at the top right of the Save As dialog are too small.
I'm using Notepad++ 7.5.1 on a Dell XPS 13 with a 3200x1800 screen and Windows 10 Home.

### Steps to Reproduce the Issue
1. Open Notepad++
2. In the menu choose File then Save As...

### Expected Behavior
The buttons at the top of the dialog should be a similar size to other buttons in Notepad++.

### Actual Behavior
The buttons in the dialog are tiny.

![scaling](https://user-images.githubusercontent.com/262589/34687932-5e35d74c-f47e-11e7-8d0e-8e60560e476e.png)

**Comment by justsimpleuser** [comment]
Hi Richard Corner, 
I don't see any feedback on your problem here.
Have you found a solution via some other forum, site or setting in NPP and/or Windows?
Cheers

**Comment by MetaChuh** [comment]
please go to `settings > preferences > default directory` and activate the scaleable `use new style dialog`, as seen at the screenshot below.

![Imgur](https://i.imgur.com/fibS0kv.png)

alternatively, if you want to keep using the old style file dialog, please right click on your notepad++ icon and select `properties > compatibility > change high dpi settings`, activate `override high dpi scaling behavior` and set `scaling performed by:` to `system (enhanced)`, as seen at the screenshot below.

![Imgur](https://i.imgur.com/qVQ4Bg8.png)

thank you for your help and best regards.

-----
```
general notes:

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
(no extra account is needed, just use your github account to sign in)
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)
