### ISSUE TITLE
Double-click splitter to resize both panes to equal size

### ISSUE THREAD

**Issue by Eldaw** [notepad-plus-plus/notepad-plus-plus#406]
It would be nice if it was possible to double-click the splitter dividing 2 panes and have it automatically move the splitter to the middle, making both panes exactly equal in size.

**Comment by MetaChuh** [comment]
implemented in https://github.com/notepad-plus-plus/notepad-plus-plus/commit/4f24f81eb8e0d1adc87da8d047531504d1b8232e
