### ISSUE TITLE
Notepad++.exe process not closed after quitting application

### ISSUE THREAD

**Issue by favorini** [notepad-plus-plus/notepad-plus-plus#4062]
### Description of the Issue

Orphaned notepad++.exe process is left behind after quitting application using Alt-F4 or close window button. This is using Notepad++ 7.5.4 x32 (and 7.5.3 and maybe since 7.5) on Windows 7 x64.

### Steps to Reproduce the Issue

1. Open Notepad++
2. Quit application
3. Notice notepad++.exe is still present in Task Manager processes tab

### Expected Behavior

Process should end and not be orphaned.

### Actual Behavior

Process does not end, nor is it re-used.

### Debug Information

Notepad++ v7.5.4   (32-bit)
Build time : Jan  1 2018 - 01:47:45
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 7 (64-bit)
Plugins : DSpellCheck.dll JSMinNPP.dll mimeTools.dll NppConverter.dll NppExport.dll NppMenuSearch.dll NppSaveAsAdmin.dll NppTextFX.dll PluginManager.dll VisualStudioLineCopy.Unicode.dll

**Comment by dail8859** [comment]
Closes fine for me. Try disabling your plugins in case it is one of those.

**Comment by favorini** [comment]
Problem appears to be NppMenuSearch.dll. Had version 0.9.0. Upgraded to 0.9.2 (latest) and problem is still there. I will report it to the plugin's developer.

**Comment by jckleinbourg** [comment]
The plugin 'Explorer' (last version v1.8.2) causes also the same issue.

**Comment by sasumner** [comment]
> The plugin 'Explorer' (last version v1.8.2) causes also the same issue.

I have been using this version of Explorer plugin for a long time with no such issue.  Doesn't mean anything, I guess, but I like this plugin a lot and don't want to see its reputation sullied.  :-P

**Comment by jckleinbourg** [comment]
> > The plugin 'Explorer' (last version v1.8.2) causes also the same issue.
> 
> I have been using this version of Explorer plugin for a long time with no such issue. Doesn't mean anything, I guess, but I like this plugin a lot and don't want to see its reputation sullied. :-P

I finally found that the issue was caused because of the corruption of the Explorer.ini file (it was containing a NUL character in the lastpath line with a dead link, also chinese characters at the end(!)).

I like this plugin too, but we can agree that it would need an update to check and reset the ini file in case of corruption instead of 'bugging' like this.

**Comment by jckleinbourg** [comment]
> > The plugin 'Explorer' (last version v1.8.2) causes also the same issue.
> 
> I have been using this version of Explorer plugin for a long time with no such issue. Doesn't mean anything, I guess, but I like this plugin a lot and don't want to see its reputation sullied. :-P

I confirm the issue by removing and installing the plugin several time, also deleting Explorer.ini file doesn't fix.

I found that it was an issue from this plugin by tracking the dll like explained here: https://superuser.com/questions/675789/how-to-kill-a-task-that-is-lacking-an-instance

Bug appears on Windows 10.0.17134 x64 when using npp x86.

**Comment by jckleinbourg** [comment]
> > The plugin 'Explorer' (last version v1.8.2) causes also the same issue.
> 
> I have been using this version of Explorer plugin for a long time with no such issue. Doesn't mean anything, I guess, but I like this plugin a lot and don't want to see its reputation sullied. :-P

I confirm the issue by removing and installing the plugin several time to be sure that it was the case, also deleting Explorer.ini file doesn't fix.

I found that it was an issue from this plugin by tracking the dll like explained here: https://superuser.com/questions/675789/how-to-kill-a-task-that-is-lacking-an-instance

Bug appears on Windows 10.0.17134 x64 when using npp x86.

And I like this plugin too, I would appreciate that it would not cause this issue. I use Light Explorer now instead.
