### ISSUE TITLE
Reg exp replace with group not working in Notepad 7.5.4

### ISSUE THREAD

**Issue by holeinvoid** [notepad-plus-plus/notepad-plus-plus#4066]
### Description of the Issue
Using Search / Replace with reg exp and groups does not work

### Steps to Reproduce the Issue
In document write 1 2
Goto Search / Replace, toogle Regular expression on
Find what: (\d+)
Replace with: $0
Click Replace and note that digit disappers, group $0 is seemingly empty. Samething happen if Replace with: /0 and $1,/1. 

### Expected Behavior
Digit should no disapper

### Actual Behavior
It disapperd
### Debug Information
Notepad++ v7.5.4   (64-bit)
Build time : Jan  1 2018 - 01:50:29
Path : D:\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10 (64-bit)
Plugins : DSpellCheck.dll mimeTools.dll NppConverter.dll

**Comment by sasumner** [comment]
The `$0` and `$1` cases work fine for me.  The others (`/0`) and (`/1`) don't make much sense, although if the `/1` is supposed to be `\1` then that one also works ok for me.

**Comment by holeinvoid** [comment]
Sorry for writing wrong regarding slashes, I just reinstalled 7.5.4 to try it myself and it still fails here with $0 and $1. Added Debug information to issue.

**Comment by dail8859** [comment]
Works fine for me:
![srdemo](https://user-images.githubusercontent.com/3694843/34878545-82788742-f778-11e7-8473-d92709bc9da1.gif)

```
Notepad++ v7.5.4   (32-bit)
Build time : Jan  1 2018 - 01:47:45
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 7 (64-bit)
Plugins : none
```

**Comment by holeinvoid** [comment]
So strange, but I also noticed that 7.5.4 on my computer was very slow for instance when changing tabs. Downgraded to 7.5.3 (64 bit) and everything is fine again.
