### ISSUE TITLE
Update British speller

### ISSUE THREAD

**Issue by marcoagpinto** [notepad-plus-plus/notepad-plus-plus#4068]
Hello!

I am maintaining the British Hunspell speller.

I was wondering if you could include it in the latest release.

I do monthly updates of it.

Here are the pages:
http://proofingtoolgui.org (Proofing Tool GUI project)

https://github.com/marcoagpinto/aoo-mozilla-en-dict (GitHub with the most recent English spellers)

Thank you!

**Comment by MetaChuh** [comment]
@marcoagpinto 

many thanks for your work.

the dspellcheck plugin is an external project, not maintained by the notepad++ team.
please visit the [dspellcheck project's issue tracker](https://github.com/Predelnik/DSpellCheck/issues), to submit your questions, regarding the integration of your hunspell dictionaries at the dspellcheck plugin.

thank you for your help and best regards.
