### ISSUE TITLE
Don't want Google Search in context menu

### ISSUE THREAD

**Issue by scootergrisen** [notepad-plus-plus/notepad-plus-plus#407]
I see "Google Search" have been added in the context menu in version 6.7.9.2 :crying_cat_face: 

I would very much like no to see this every time i use the context menu.

I don't like a particular company/search engine being forced upon the user.

**Comment by Rikk** [comment]
You know you can remove it from `shortcuts.xml`, right?

**Comment by cmeriaux** [comment]
or you can edit the file contextMenu.xml to remove what you don't want

**Comment by milipili** [comment]
#466

**Comment by scootergrisen** [comment]
Is it possible to use the default search engine, that the user have set in the default browser?

That way the menu item could be called something like "Search online" or something like that.

**Comment by milipili** [comment]
hum possibly. It would require to use the default search engine of the default web browser.

**Comment by donho** [comment]
I got no intetion to force people to use Google Search Engine. I personally need this feature so I have done it. If anyone got idea to use the default search engine, please let me know - I'll certainly implement it.

**Comment by Rikk** [comment]
Maybe a url like `? search terms` could do it in default browser. Seems to work in IE/FF at least, not sure about Chrome.

**Comment by donho** [comment]
https://github.com/notepad-plus-plus/notepad-plus-plus/commit/e451efbd290f36300fe08a3b5be5460c5dd94f84
