### ISSUE TITLE
Allow custom coloring of line endings

### ISSUE THREAD

**Issue by Dinoguy1000** [notepad-plus-plus/notepad-plus-plus#4070]
Currently, when "Show End of Line" or "Show All Characters", under View --> Show Symbol, is selected, the glyphs used for EOL characters are the same color as normal text. This is extremely distracting; these glyphs should instead either use the same color/styling as other whitespace characters, or have their own separate color/styling with a sane default (even if that default is identical to that for other whitespace).

I am aware that display of EOL characters can be disabled by just selecting "Show White Space and TAB", but there are legitimate reasons for displaying EOL characters, and it doesn't make sense to punish those who need or choose to have the characters displayed.

**Comment by stephengeorgewest** [comment]
Upvoting this. I like to leave it on, but would love low contrast, like I have for other whitespace. It works great for tabs/spaces, but they super standout for line endings.
![image](https://user-images.githubusercontent.com/1442484/137490499-b32f4c98-9fee-4e61-adf8-9c2bffeada71.png)

**Comment by alankilborn** [comment]
Recommend CLOSURE as this was implemented in 8.4.4
