### ISSUE TITLE
[Feature Request] "Do for all items" checkbox in "This file has been modified" dialogue

### ISSUE THREAD

**Issue by alex-slover** [notepad-plus-plus/notepad-plus-plus#4072]
I frequently work with large numbers of open files (tabs) in Notepad++, and change all of them at once outside the program (usually when changing branches in git). This means I have to click or Enter through a large number of modal "This file has been modified by another program. Do you want to reload it?" dialog boxes, and most of the time I want the same choice for every file. It's especially annoying when I want to get to one particular file that wasn't even part of the operation and the affected files are irrelevant noise.

Please consider adding a "Remember this choice for all files" checkbox to this dialog, or possibly "Yes to All"/"No to all" buttons to make this a lot faster. 

Same goes for the "The file `foo` doesn't exist anymore. Keep this file in editor?" box.

**Comment by briansandall** [comment]
Yes, please.

A simple checkbox to 'do for all' would be immensely helpful when switching between git branches in a project with lots of files loaded.

It could either apply to all dialogs at once or still have each specific dialog (e.g. file changed, file no longer on disk, etc.) and able to check the box on each dialog to apply to all similar instances. The latter is probably the better general solution.
