### ISSUE TITLE
Apparently impossible to register as user for registering a new plugin

### ISSUE THREAD

**Issue by alf-p-steinbach** [notepad-plus-plus/notepad-plus-plus#4074]
### Description of the Issue

Following the steps at (https://bruderste.in/npp/pm/#developer) I've tried twice to register a user at (https://npppm.bruderste.in/), for the purpose of registering my plugin (https://github.com/alf-p-steinbach/NPP-plugin-Empty-files-as-Unicode).

That web page just informs that a mail has been sent for activating the account.

No mail has been received (yes, I've checked the GMail spam-box), and attempting to log in fails.

### Steps to Reproduce the Issue

Try to create an account for registering a plugin.

### Expected Behavior

Receive a mail with account activation link.

### Actual Behavior

No mail.

**Comment by dail8859** [comment]
The Plugin Manager is not part of the Notepad++ project. You'll have to report this to the developer of the Plugin Manager.
