### ISSUE TITLE
Hanging if network file is not available.

### ISSUE THREAD

**Issue by TristisOris** [notepad-plus-plus/notepad-plus-plus#4080]
### Steps to Reproduce the Issue

1. open any file on network share. (local network, without access from outside)
2. connect to VPN tunnel. (outside network)
3. NP instantly hangs up or crash.
4. if turn off the VPN, NP would work normal again.

Need option like on missing local files - file is unavailable, save it or close.

**Comment by peyremorgan** [comment]
Had the same issue : our W2K12 server crashed and my N++ started hanging for periods of 20 to 40 seconds when switching to (or closing) tabs pointing to unreachable files.

Windows 10 Pro 16299.125
Notepad++ v7.5.4 (32-bit)

**Comment by Valijon** [comment]
Had the same issue. I have opened several tabs and 1 of them points to network file, (once VPN disabled) entire program hangs up 20 - 60 seconds or crash.

Solution: Check file availability, sincronization, etc.. when active tab is selected. It would welcome any progress bar / text notification, Cancel action, etc...

Thank you

Windows 8.1
Notepad++ v7.5.4 (32-bit)

**Comment by MetaChuh** [comment]
please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins if you update from version 7.5.9 or below.
if your issue still persists, and it is still of relevance, please feel free to file a new issue as easy to understand and reproducible as possible.

thank you for your help and best regards.
