### ISSUE TITLE
Notepad++ File Status Auto-Detection not working

### ISSUE THREAD

**Issue by kkirochkagi** [notepad-plus-plus/notepad-plus-plus#4081]
Hello everyone, I’m from Ukraine. Sorry for my English.

Notepad++ stopped monitoring file changes.

Settings > Preferences… > MISC.
File Status Auto-Detection
[v] Enable

It used to work, it stopped after it was updated. The settings are enabled.
Notepad++ v7.5.4 (32-bit) for Windows XP LOL ;)

Please help, how can I fix it?

My text:
LINK_1: https://notepad-plus-plus.org/community/topic/15089/notepad-file-status-auto-detection-not-working
Someone has the same problem:
LINK_2: https://github.com/notepad-plus-plus/notepad-plus-plus/issues/3981

**Comment by dail8859** [comment]
Please do not open duplicate issues.

**Comment by kkirochkagi** [comment]
Okay, I'm sorry
