### ISSUE TITLE
The ↘ symbol is not shown

### ISSUE THREAD

**Issue by YakovL** [notepad-plus-plus/notepad-plus-plus#4086]
So I open a file in n++, encoding set to UTF-8 without BOM, I have editor font set to Consolas and I paste the ↘ symbol into n++.

What I expect is – the symbol is displayed normally: it is supported by Consolas and is displayed properly in (Windows) Notepad.

What actually happens – well, the "question in a square" symbol is displayed – I believe, this one: ⍰. (but if I copy the symbol and paste here, it's ↘ again, so this is a display issue, not some bad converting).

### Debug Information
Notepad++ v7.5.4   (32-bit)
Build time : Jan  1 2018 - 01:47:45
Path : C:\1my\tools_and_components\in_use_or_used\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10 (64-bit)
Plugins : AutoSave.dll ComparePlugin.dll DSpellCheck.dll mimeTools.dll NppConverter.dll NppExport.dll PluginManager.dll PythonScript.dll

**Comment by CookiePLMonster** [comment]
Seems related to #675

**Comment by YakovL** [comment]
and may be to #671

**Comment by HorizonNL** [comment]
does anyone know how to fix it yet ?

**Comment by ValZapod** [comment]
1) You use Courier New by default.
2) There is no U+2198 in Consolas (latest 7.0), Notepad uses other font to render that symbol 
Main discussion is in #3747.

**Comment by YakovL** [comment]
@donho is it safe to say that the problem is expected to be solved in the version next to 7.8.7?

**Comment by donho** [comment]
@YakovL 
Sorry, I just copy the wrong number.
This is not the bug in Notepad++.
As @ValZapod said,  Consolas doesn't support ↘ , if you use Courer New it will display it correctly.

**Comment by YakovL** [comment]
hm, that's funny, I've retested it and now it actually displays ↘ correctly in Consolas, so this is closed properly

**Comment by YakovL** [comment]
Hm.. today I have ↘ not dispalyed properly, but if it goes after ↓, it is displayed..

**Comment by ValeZAA** [comment]
Just enable DirectWrite.

**Comment by YakovL** [comment]
@ValeZAA thanks, this seems to be the solution!

For those interested: it's Settings > Preferences > MISC > Use DirectWrite
