### ISSUE TITLE
NotePad++ for Linux

### ISSUE THREAD

**Issue by AhmedNazir** [notepad-plus-plus/notepad-plus-plus#4088]

**Comment by CookiePLMonster** [comment]
Since the repo contains a full source code, I'm sure authors are more than happy to see you contribute to a task like this.

**Comment by sasumner** [comment]
Ugh, WHY oh WHY is this issue clogging the list??

**Comment by dail8859** [comment]
You can run Notepad++ with WINE so I suggest using that as running Notepad++ on Linux natively would require a complete rewrite.

**Comment by BurhanDanger** [comment]
Use notepadqq or inside wine. Simple
