### ISSUE TITLE
Notepad++ crashes and loses file content

### ISSUE THREAD

**Issue by tobozo** [notepad-plus-plus/notepad-plus-plus#4089]
All text editors always maintain a "backup" of files being edited, just in case, you know, a crash.
Sometimes it's a .swp file, sometimes it's a hidden file.

This basic software humility seems to not exist in Notepad++, so every once in a while, whether it's the NSA, Microsoft, or my own clumsiness on the keyboard that makes the editor crash (especially when saving a file), I lose all my progress, and I also lose the content of the file.

So please, do as Vi, Nano, EMACS, or any other decent text editor and make Notepad++ create a backup of what's being edited, just in case, you know, the editor crashes.

Steps to reproduce: see #2419

**Comment by sasumner** [comment]
@tobozo, maybe you should use a more stable and reliable text editor.  Just a suggestion.

**Comment by dail8859** [comment]
Please do not open duplicate issues.

**Comment by tobozo** [comment]
@sasumner yep I'm back to a more stable editor now

![notepadbuild](https://user-images.githubusercontent.com/1893754/34991773-1cbfa97a-facb-11e7-9d08-c53a034a1e22.GIF)

**Comment by tobozo** [comment]
@dail8859 using references to other issues in a feature request does not make it a duplicate.

**Comment by dail8859** [comment]
You provided no useful additional information to try to actually debug the problem. The only other thing you suggested was to save a backup, which Notepad++ does if enable the setting.

**Comment by tobozo** [comment]
@dail8859 debug information is in #2419 where the regression has been pointed out
