### ISSUE TITLE
Greek OEM869 Encoding lost on v7.5.3 (32bit).

### ISSUE THREAD

**Issue by Bourtoulameos** [notepad-plus-plus/notepad-plus-plus#4091]
### Brief Description
I used to check and edit text files from a Toshiba 4690 OS system that uses IBM PC 869 code page for Greek language. That was compatible to your Greek OEM869 char-set via Encoding menu. On version 7.5.3 (32b) this does not work.

### Steps to Reproduce the Issue
1.  Open a file that uses IBM PC869 Greek code page (preferably a 4690 OS edited one in Greek)
2. Goto ENCODING tab 
3. Select Charsets-->Greek-->OEM 869

### Expected Behavior
In previous versions < v7.5.3 32b, that worked perfect

### Actual Behavior
IBM cp869 Greek appear as Chinese instead of Greek

### Debug Information
No sure

**Comment by Bourtoulameos** [comment]
I used to check files from a Toshiba 4690 OS system that uses IBM PC 869 code page for Greek language. That was compatible to your Greek OEM869 char-set via Encoding menu. On version mentions this is lost. Can anyone help pls ?

**Comment by dail8859** [comment]
This is fixed in v7.5.4
