### ISSUE TITLE
the count displaying for length in the status bar  is wrong

### ISSUE THREAD

**Issue by alagammai-annamalai** [notepad-plus-plus/notepad-plus-plus#4095]
![untitled](https://user-images.githubusercontent.com/35523262/35034607-c0f6e3ae-fb94-11e7-99dc-a5994e237405.png)

**Comment by sasumner** [comment]
You're going to have to be more detailed in your issue report for anyone to understand it.  For example, it is valid for the caret to be in column 30 and the overall length to be 31.
