### ISSUE TITLE
Find in Files option to ignore .git subdirectory

### ISSUE THREAD

**Issue by vinriviere** [notepad-plus-plus/notepad-plus-plus#41]
It would be nice to have an option in the Find in Files dialog to ignore the .git subdirectory.

**Comment by tushevorg** [comment]
agreed

**Comment by milipili** [comment]
.svn {subversion} / .hg {mercurial} ...
Actually an option to ignore UNIX hidden files (all filenames starting with a dot) might be easier and more effective.

**Comment by vinriviere** [comment]
And also CVS directories (not starting with a dot).

**Comment by cmeriaux** [comment]
I think we need something more generic to ignore some directory as we wish.
In my favorite difftool, you can describe complex filter :

`*.xml;-.\.git\;-.\.settings\`

that means :

1. allow only xml file
2. ignore every .git folder
3. ignore every .settings folder

I think that's what we need.
Christophe

**Comment by cmeriaux** [comment]
Hy guy,
bad news for us, "Find in Files ignore" system is inside scintilla. So we have to ask in SciTE team this evolution.

**Comment by donho** [comment]
.git subdirectory is, normally a hidden directory under windows. So if you don't check "in hidden directory", find in files command will not search in .git subdirectory.
