### ISSUE TITLE
Can we develop it's Android version?

### ISSUE THREAD

**Issue by thismahbub** [notepad-plus-plus/notepad-plus-plus#410]
It will be helpfull for Software Engineer to use this app in android phone.

**Comment by turbanoff** [comment]
There are a lot of native editors for android. Why do you need another one?
Creating android version of notepad++ mean - rewriting half of the code. And it makes editor slower on both platforms.

**Comment by milipili** [comment]
We're thinking about multi-platform and we're heading this way. But not now.

**Comment by milipili** [comment]
(sorry for the commit - not really woken up...)

**Comment by Croydon** [comment]
See #332.
