### ISSUE TITLE
When I compiler the source code of notepad++, it occurs this exception. Why?

### ISSUE THREAD

**Issue by jiesince1998** [notepad-plus-plus/notepad-plus-plus#4101]
![image](https://user-images.githubusercontent.com/24897529/35108864-a2557c8c-fcaf-11e7-85e6-612daff18dc7.png)

It says that " Assertion [::GetCurrentThreadld()==::GetWindowThreadProcessld(reinterpret_cast<ScintillaWin*>(ptr)->MainHWNd(),NULL)] failed at ScintiallaWin.cxx 3240"

**Comment by ufengli** [comment]
Have you solved this issue?

**Comment by Ekopalypse** [comment]
@jiesince1998 - is this still an issue with npp 7.7?

**Comment by MetaChuh** [comment]
please visit our [notepad++ community](https://notepad-plus-plus.org/community/), to exchange your build experiences and questions.

if you will still struggle to build notepad++ with the given available community information, please download and use our prebuilt binaries or installers.

many thanks and best regards.
