### ISSUE TITLE
Javascript template strings in template string

### ISSUE THREAD

**Issue by Fuzzyma** [notepad-plus-plus/notepad-plus-plus#4106]
### Description of the Issue
The javascript syntaxhighlighting breaks when you use template strings in template strings or similar

### Steps to Reproduce the Issue
Input one of the following:

```js
var text = `Hello ${name == null ? 'Stranger' : `${name}, How are you?`}`
var text = `Markup with `markdown code` in it`
```

### Expected Behavior
Do not disable string-highlighting at the second occurrance of "`"

### Actual Behavior
Highlighting stops at the second occurrance of "`"

Beside this: Placeholders in template strings should be highlighted as regular javascript code (because they are) and not be in the same color as the whole string. Do I need to open another issue for this case?

**Comment by MAPJe71** [comment]
See [Scintilla repository feature request no. 1112](https://sourceforge.net/p/scintilla/feature-requests/1112/)

**Comment by Fuzzyma** [comment]
Thx for linking. Unfortunately it seems like the issue on their site is stalled, too

**Comment by zufuliu** [comment]
It's not, I made a new/duplicate one at https://sourceforge.net/p/scintilla/feature-requests/1221/

Just need someone to implement it.

**Comment by donho** [comment]
https://github.com/notepad-plus-plus/notepad-plus-plus/issues/3822#issuecomment-697275450
