### ISSUE TITLE
FTP File upload

### ISSUE THREAD

**Issue by freesouldesign** [notepad-plus-plus/notepad-plus-plus#4110]
If you upload a file to the server, during the uploading the file is not completed and if it's parsed it will probably generate errors until the upload is finished. 

It would be better on my opinion to automatically upload the file with a different name and at the end after that the upload is completed, the old file is deleted and the updated file is renamed with the right name, I suppose that this last operation would require a lot less time than the upload itself, and  the probability that an uncompleted file is parsed would be lower.

**Comment by dail8859** [comment]
A) Please follow the provided template
B) I'm assuming you are talking about the NppFTP plugin
C) That plugin is not part of this project

**Comment by freesouldesign** [comment]
A) Sorry
B) Yes
C) In according to [the guidelines described in [https://github.com/notepad-plus-plus/notepad-plus-plus/blob/master/CONTRIBUTING.md] NppFTP it is a standard plugin and so it should be part of the project.
From the guidelines:
.....
3. Only report an issue with a plugin if it is one of the standard plugins included in the Notepad++ installation. Any other plugin issue should be reported to its respective issue tracker. The standard plugins include (for v6.8.3):
NppFTP
NppExport
Plugin Manager
Converter
mimeTools

.......

**Comment by dail8859** [comment]
Unfortunately that list has not been updated in a long time.

**Comment by freesouldesign** [comment]
ok, thank you, I will close the thread
