### ISSUE TITLE
Stata syntax coloring

### ISSUE THREAD

**Issue by bholtemeyer** [notepad-plus-plus/notepad-plus-plus#4116]
### Description of the Issue

I have 2 "Stata Commands" syntax coloring requests: 

1) I request that "globals" be highlighted/colored. For example, if typed into Stata, `foo' would be colored (it colors locals) but $foo is not colored (because globals are not colored)

2) The punctuation that marks the end of a local is not colored when that punctuation repeats. For example, if I typed into Stata, `foo_`bar'' , then the following characters would be colored: `foo_`bar'

Notice that the last ' mark is not colored. 

![2018-01-23 14_08_59-_d__users_bholtemeyer_dropbox ifpri _brian_kyrgyzstan_lik_do_master_0122 do - n](https://user-images.githubusercontent.com/21350451/35295375-fcffa168-0046-11e8-91cd-10915712d3c9.png)

### Steps to Reproduce the Issue
issue 1: look at the coloring when you type $foo
issue 2: look at the coloring when you type `foo_`bar''

**Comment by MAPJe71** [comment]
Do you use a UserDefinedLanguage because Notepad++ does not support syntax coloring for Stata?

**Comment by bholtemeyer** [comment]
@MAPJe71 yes, you're right. Sorry!
