### ISSUE TITLE
Changing text/backround color globally shouldn't effect syntax text/highlights coloring

### ISSUE THREAD

**Issue by mzso** [notepad-plus-plus/notepad-plus-plus#4117]
### Description of the Issue
When I set a background or text color globally the syntax coloring and highlights are vanquished.
This makes no sense to me. I think these shouldn't be effected by whatever I set as the background/text color globally. Or at least an option should exist.
(I prefer not to have an eye scorching white background and black text)

### Steps to Reproduce the Issue

1. Change the foreground/background color
2. Check the checkboxes to enable them
3. Note that the syntax coloring is gone.

### Expected Behavior
The background color and the default text color changes, but not the syntax colored text and highlights.

### Actual Behavior
All syntax coloring is gone.

**Comment by dail8859** [comment]
You can change the background color while still keeping syntax highlighting.

If you change the foreground color then you *loose all the syntax's color* because you have just overridden it.

**Comment by mzso** [comment]
That's not quite true. Syntax coloring includes highlighting for a few things, which is is gone when I change the background color. This option should only change the default background/foreground (white/black) color.

For example:
![npp-syn1](https://user-images.githubusercontent.com/4479090/35410165-c2b66bf2-0214-11e8-8f0b-d7bd1a0ce5ff.png) ![npp-syn2](https://user-images.githubusercontent.com/4479090/35410166-c2d46328-0214-11e8-99aa-fd53a988a7d4.png)

**Comment by dail8859** [comment]
Can you provide exact steps with specific instances (e.g. code) that it doesn't work for you? 

Also I'm not sure what your example is showing?

**Comment by mzso** [comment]
[**@dail8859**](https://github.com/dail8859) commented on [2018. jan. 25. 21:21 CET](https://github.com/notepad-plus-plus/notepad-plus-plus/issues/4117#issuecomment-360588678 "2018-01-25T20:21:32Z - Replied by Github Reply Comments"):
> Can you provide exact steps with specific instances (e.g. code) that it doesn't work for you? And also post your debug information?
> 


That is what the pictures are about...
Watch for the highlights, that are removed when I changed the background color. "@param" part in the first one, and stuff between %-s in the second.

Judging by stylers.xml it's quite common to have syntax based highlights.

**Comment by mzso** [comment]
[**@dail8859**](https://github.com/dail8859) commented on [2018. jan. 25. 21:21 CET](https://github.com/notepad-plus-plus/notepad-plus-plus/issues/4117#issuecomment-360588678 "2018-01-25T20:21:32Z - Replied by Github Reply Comments"):
> And also post your debug information?

It's not of any relevance, but here:
```
Notepad++ v7.5.4   (32-bit)
Build time : Jan  1 2018 - 01:47:45
Path : D:\Programok\Notepad Plus\notepad++.exe
Admin mode : OFF
Local Conf mode : ON
OS : Windows 8.1 (64-bit)
Plugins : ComparePlugin.dll DSpellCheck.dll jN.dll mimeTools.dll NppConverter.dll NppExport.dll NppFTP.dll NppTextFX.dll PluginManager.dll SelectNLaunch.dll SpellChecker.dll 
```

**Comment by dail8859** [comment]
> Watch for the highlights

Well if you are overriding the background color then the background color will get changed.

> It's not of any relevance, but here:

You'd be surprised that some people are on a 2 year old version of N++ and submit bugs. That's why this is requested in the issue template.

**Comment by mzso** [comment]
[**@dail8859**](https://github.com/dail8859) commented on [2018. jan. 25. 21:48 CET](https://github.com/notepad-plus-plus/notepad-plus-plus/issues/4117#issuecomment-360595628 "2018-01-25T20:48:08Z - Replied by Github Reply Comments"):
> > Watch for the highlights
> 
> Well if you are overriding the background color then the background color will get changed.
> 

Well this was the point of the issue. That NPP wouldn't do this. Just set the color to the specified color, then apply the syntax coloring.
(Though see a complication with this. For some languages such JS and PHP the default background color seems to have been changed without any relevance for syntax for some reason as such they'd require special treatment)

> > It's not of any relevance, but here:
> 
> You'd be surprised that some people are on a 2 year old version of N++ and submit bugs. That's why this is requested in the issue template.

Must have missed it.

**Comment by dail8859** [comment]
> Just set the color to the specified color, then apply the syntax coloring.

Unfortunately it is not as simple as "draw the background color" and then "draw the syntax coloring on top". Each syntax style has its own configurable background color. Normally you don't see this because it is all the same color, but for some cases (as you have pointed out) the background color is different, so it looks like it is "highlighted".

**Comment by mzso** [comment]
[**@dail8859**](https://github.com/dail8859) commented on [2018. jan. 25. 22:10 CET](https://github.com/notepad-plus-plus/notepad-plus-plus/issues/4117#issuecomment-360601506 "2018-01-25T21:10:02Z - Replied by Github Reply Comments"):
> > Just set the color to the specified color, then apply the syntax coloring.
> 
> Unfortunately it is not as simple as "draw the background color" and then "draw the syntax coloring on top". Each syntax style has its own configurable background color. 

Well, if this would be the case it would actually make it simpler. Just change the default color and be done with it.

But it seems to me that every element has the background colour specified in JS. (I had to change all of them to get a typical white  background for JS, when I tested.)

**Comment by dail8859** [comment]
I agree that would make it easier in some cases but that would be a change that would be need to be implemented by the Scintilla project (which is what Notepad++ uses internally).

**Comment by MetaChuh** [comment]
please do not use global overrides if they do not suit your needs.

thank you for your help and best regards.

-----
```
general notes:

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
(no extra account is needed, just use your github account to sign in)
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)
