### ISSUE TITLE
AntiVirus Alert

### ISSUE THREAD

**Issue by Gryffen1971** [notepad-plus-plus/notepad-plus-plus#4120]
[ComodoLogEvent(26_Jan_18_04_32_05).zip](https://github.com/notepad-plus-plus/notepad-plus-plus/files/1667292/ComodoLogEvent.26_Jan_18_04_32_05.zip)

### Description of the Issue
I received an Alert from Commodo Internet Security about a Virus. 
Alert Time; 2018-01-26 04:32:05
Malware/Virus name;  TrojWare.Win32.TrojanDownloader.Tovkater.ID@452171600
Location; C:\My Program Files\Notepad++\uninstall.exe
Program was not running at the time this occured.
Attached is the Antivirus Event as a ".htm" document with the same info provided above

### Steps to Reproduce the Issue

1. Don't know want too!
2. 
3. 

### Expected Behavior
Unknown, program was not running at time.

### Actual Behavior
Anti-Virus caught, Quarantined and Disinfected file with program NotePad++ not running.

### Debug Information
No Debug info need. This happened while program was not running.

**Comment by dail8859** [comment]
What version of Notepad++ are you using and is it 32 or 64 bit? It is very likely it is a false positive.

www.virustotal.com shows the uninstallers for v7.5.4 are clean. Results:

- [32bit uninstaller](https://www.virustotal.com/#/file/84810d00344ec4a3c9e68498e98e974a262232cf07b4f21b6157efdb5d36a845/detection)
- [64bit uninstaller](https://www.virustotal.com/#/file/c6a12aeae1f7121c91fa4053b3f7fc408753edaa4d5fe6b74b2e3e8ba2c1241c/detection)

**Comment by SinghRajenM** [comment]
> It is very likely it is a false positive.

Looks like false alarm only, if the installer (32bit or 64 bit) is downloaded from official site. File ```C:\My Program Files\Notepad++\uninstall.exe``` is auto generated by installer which seams very less likely virus infected.

**Comment by Gryffen1971** [comment]
This was on my system for some time. It was downloaded from your secure site. I believe a virus tried and failed to infect your file. I wanted to report it to you. So, you that you would be aware of this. I know that you and your team have a secure site and that all of your files are safe. This was an 'FYI'. I was just looking out for ya.
