### ISSUE TITLE
Typo in contextMenu.xml

### ISSUE THREAD

**Issue by Ullallulloo** [notepad-plus-plus/notepad-plus-plus#4123]
In [contextMenu.xml](https://github.com/notepad-plus-plus/notepad-plus-plus/blob/master/PowerEditor/src/contextMenu.xml), there is a typo on [line 4](https://github.com/notepad-plus-plus/notepad-plus-plus/blob/master/PowerEditor/src/contextMenu.xml#L4):
> It may be more **convinient** to access to your **frequent** used commands via context menu than via the top menu.

"conv**i**nient" should be "conv**e**nient"  
"frequent" should be "frequently"

Also, [line 3](https://github.com/notepad-plus-plus/notepad-plus-plus/blob/master/PowerEditor/src/contextMenu.xml#L3) is awkward:
> By modifying this file, you can customize your context menu **popuped as right clicking** on the edit zone.

I'm guess it should be like, "...context menu that is popped up by right clicking..."

And if I'm being picky, [line 13](https://github.com/notepad-plus-plus/notepad-plus-plus/blob/master/PowerEditor/src/contextMenu.xml#L13) is awkward:
> The values should be in English but not in translated language.

It should be "... in English, not in a translated language."

**Comment by dail8859** [comment]
This is really kind of pedantic to worry about misspellings in comments and just causes noise in the issue list. If you look hard enough you will find dozens more. If you are really that concerned open a PR with the fixes.
