### ISSUE TITLE
Open 64-bit instead of 32-bit command-line prompt on 64-bit OSs.

### ISSUE THREAD

**Issue by jurko-gospodnetic** [notepad-plus-plus/notepad-plus-plus#4125]
### Description of the Issue
Currently when you choose the `Open Containing Folder in cmd` tab context menu item on a 64-bit system, it starts a 32-bit `cmd.exe` process (typically from `C:\Windows\SysWOW64\cmd.exe`). What I'd like it to do, or at least to be made configurable is to run a 64-bit `cmd.exe` process in such cases (typically from `C:\Windows\System32\cmd.exe`).

If you run both such command prompt windows at the same time, you can for instance see that they do not merge into a single Windows start group, as they are not generated by the same executable.

### Debug Information

```
Notepad++ v7.5.4   (32-bit)
Build time : Jan  1 2018 - 01:47:45
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10 (64-bit)
Plugins : DSpellCheck.dll FileSwitcher.dll HexEditor.dll JSMinNPP.dll mimeTools.dll NppConverter.dll NppExport.dll PluginManager.dll XMLTools.dll 
```

**Comment by CookiePLMonster** [comment]
I'm pretty sure this is going to behave correctly if 64-bit Notepad++ is used.

**Comment by jurko-gospodnetic** [comment]
Confirmed. When running 64-bit Notepad++ the expected `cmd.exe` version gets run.

I haven't looked for it in a while, and seem to have remembered incorrectly that a 64-bit version is not available.
