### ISSUE TITLE
 Always Encoding ANSI TO Shift JIS ? Problem

### ISSUE THREAD

**Issue by Vegeta780** [notepad-plus-plus/notepad-plus-plus#4127]
Hello My Problem is Encoding Shift JIS 
When I Load A new Document It's Encode With ANSI Not Shift JIS 
I Already Choose Option  With  Shift JIS from New Document Option 
Thanks A lot

**Comment by dail8859** [comment]
You did not post your debug information as the template stated...so I am not sure what version you are using. However there were some issues with the encoding in previous versions so if you are not using Notepad++ v7.5.4 then I highly recommend updating to that version.

**Comment by CookiePLMonster** [comment]
It would also be handy to see the faulty file in question.

**Comment by Vegeta780** [comment]
Thanks a lot Autodectect is not good I guess one by one convert to SHIFT-JIS Is Pain in Neck Is there a short key for encode to SHIFT-JIS ?

**Comment by dail8859** [comment]
You can manually set a shortcut key by using `Settings > Shortcut Mapper` and find the "Shift-JIS" under the "Main Menu" tab.

**Comment by Vegeta780** [comment]
Thanks a lot It's Works Sorry I thought it was a Bug
