### ISSUE TITLE
Notepad++ gets jitters when code pasted in (specific)

### ISSUE THREAD

**Issue by dougcouch** [notepad-plus-plus/notepad-plus-plus#4130]
### Description of the Issue
Note: I'm posting the problem here as FYI to discover for future Notepad++ development, including the code involved. I will respond to inquiries related to this, but really all the info is here already...and I will not be monitoring this board online.

Pasted the code content of epanel/core_functions.php (from a WordPress account) into a new document in Notepad++ (v.5.8.7 UNICODE). Instantly, the editor code content started rapidly shifting from left to right and not stopping until the code was removed or document closed.

### Steps to Reproduce the Issue

Pasting in the code starts the (repeatable) behavior.

### Expected Behavior
Expected code to simply arrive in the document to be edited.

### Actual Behavior
Left-Right jitters.

### Debug Information
No debug was attempted if it was indeed possible?

### Additional Info:

File is 426 lines long with php code. Discovered that the jittery behavior is only present when the document content is scrolled down past line 395. Scroll back up and it stops.

Tried pasting in only the upper 395 lines and adding other lines (other than those usually in the file from line 396 onward)...and the resulting 790 lines do not repeat this behavior.

However, if I repeat the above but add one blank line before pasting the second half, it behaves differently >> 1) Does not jitter after 2nd paste, but if I then do a Ctrl+Z and remove the pasted material, it begins the jittery behavior again...UNTIL...I use the backspace key and remove the single added line...then the behavior stops.

Tried the same as above, but pasting in lines of non-code text, and the behavior did nor recur.

### Attached: plain text file saved in Notepad++ with the entire code content of core_functions.php used during the above tests. This file has been saved, closed and reopened in Notepad++ with the same behavioral characteristics in the saved/reopened file.

Note: This same code was pasted into the generic program Notepad and did not have this behavior in that program. Additionally, after pasting it into generic Notepad, and did a copy of the code while it was in Notepad, and pasted that back into Notepad++...and it still presented the same jittery behavior.

Ah the life...just when we thought we had everything figured out!

[ You do not need to figure this out to solve a problem for me. It is FYI for development only ]
[test-core_functionsPHP-paste.txt](https://github.com/notepad-plus-plus/notepad-plus-plus/files/1684269/test-core_functionsPHP-paste.txt)

**Comment by dail8859** [comment]
> new document in Notepad++ (v.5.8.7 UNICODE)

Do not open bugs for a version that is 7 years old.
