### ISSUE TITLE
[Bug]? Plugin Manager not available at install

### ISSUE THREAD

**Issue by kludikovsky** [notepad-plus-plus/notepad-plus-plus#4134]
**This is more a question:**

I just installed NP++ but there is no plugin manager anymore.
Neither in 64 bit not 32 bit version.

Did I miss something, or is there an issue?

**Comment by MAPJe71** [comment]
I guess you missed the search option.

**Comment by sasumner** [comment]
@kludikovsky 
The Plugin Manager is missing "by design" of the author of Notepad++.  Thus it is not, and cannot be, an issue.  Please close this issue.

**Comment by kludikovsky** [comment]
@sasumner 
It has been included in all the other installation I have made before. And I have done several of them.
But ok, "you never stop learning".
Thx.

**Comment by sasumner** [comment]
@kludikovsky Sure, but one has to respect that the author/owner of a piece of software has the right to make design decisions for their product, even if unpopular.  This is even more true when said s/w costs $0.00  :-)
If you still haven't found the Plugin Manager, and need it:
FAQ: How do I get the Plugin Manager back?? See http://bruderste.in/npp/pm/#install

**Comment by kludikovsky** [comment]
@sasumner 
Accepted without dispute.
I am just wondering why the PM was always in my previous installation automatically and worked without any other activiation.

I have now installed it manually and don't get any plugins listed (I know how it should look like).

![image](https://user-images.githubusercontent.com/6077916/35736678-329b4162-0829-11e8-8b14-1567c2cf8e7a.png)

**Comment by sasumner** [comment]
@kludikovsky 
I don't know; currently the window gets populated when I try it.  Maybe better to purse on this forum where more people will see it (and thus your help-potential is increased):  https://notepad-plus-plus.org/community/

**Comment by kludikovsky** [comment]
@sasumner 
Problem solved: Run installation of NPP as administrator.
thx
