### ISSUE TITLE
Cursorposition gets lost when switching between tabs

### ISSUE THREAD

**Issue by d-g-w** [notepad-plus-plus/notepad-plus-plus#414]
If I position the cursor in the middle of a file and then switch to other tab and back to the first tab the cursor is positioned on the first line of the file.
This is simply annoying.
I am using Notepad++ 6.7.9.2

**Comment by milipili** [comment]
It works for me (Windows 10, from a fresh install). Can you try in disabling your plugins and then publish a little screencast of the issue ?

**Comment by d-g-w** [comment]
I am on Windows 8.1 and currently trying to reproduce this myself ... unsaved buffer, saved buffer. Right now I cannot reproduce the problem. I'll try to recreate it while working on my project.
I installed four plugins recently ... I'll disable them and investigate further.

**Comment by Zarggg** [comment]
Do any of the conditions I described in #264 apply to your issue?

**Comment by b3wii** [comment]
i have the same problem.. it started happening after an update(unfortunately i dont know which version exactly). when switching between tabs the cursor position gets lost and is set to the beginning of the file. this is very annoying because you always need to scroll to the position from before again.

current npp version: v6.7.9.2 
os: windows 8.1

**Comment by dail8859** [comment]
This has most likely been happening due to XML Tools. Try disabling "Set XML type automatically".

**Comment by b3wii** [comment]
@dail8859 Your right, when "Set XML type automatically" is disabled the cursor is not set to the beginning. Thnx.

**Comment by bethloe** [comment]
Hi, I had the same issue and I can cofirm that if I disable the `Set XML type automatically` function, the bug is fixed

**Comment by aki143s** [comment]
Me too. 
Disabled Set XML type automatically in Plugins->XML Tools.
And it works.

**Comment by sansjunk** [comment]
I disabled all plugins and still seeing this issue on v6.9.2. Attached is a screen cast.
[ScrollIssue.zip](https://github.com/notepad-plus-plus/notepad-plus-plus/files/444051/ScrollIssue.zip)

**Comment by dail8859** [comment]
Most likely this is due to having word wrap enabled. You can turn it off temporarily to verify this. You are probably running into the same issue as #2078

**Comment by sansjunk** [comment]
Yes, you are correct. If I turn off word-wrap then it's all fine.

**Comment by qdinar** [comment]
i have attached a test text in https://github.com/notepad-plus-plus/notepad-plus-plus/issues/2078 , also there are screensots.

**Comment by MetaChuh** [comment]
closed due to being caused by the XMLTools plugin with enabled `Set XML type automatically`
