### ISSUE TITLE
Codebase incompatible with /Zc:strictStrings

### ISSUE THREAD

**Issue by CookiePLMonster** [notepad-plus-plus/notepad-plus-plus#4146]
For info on `/Zc:strictStrings` see:
[https://msdn.microsoft.com/en-us/library/dn449508.aspx](url)

By default, Visual Studio allows for nonstandard C++ behaviour by allowing to assign string literals to non-const qualified types. For example, this is **not** standard:

`TCHAR *nbCharLabel = TEXT("Characters (without blanks): ");`

Standard requires such literal is const, so by definition it should not be possible to assign them like this. It's more than likely an attempt to write to the value pointed to by `nbCharLabel` will cause access violation.

`/Zc:strictStrings` enforces VS compiler to follow standard behaviour. Thus, it may be feasible to enable this switch for all compilation options (it's not exposed to project settings in 2015/2017, so it needs to be manually added to `Command Line` tab. When done, code will refuse to compile, throwing lots of errors (sadly, some of them are in `ScintillaComponent` - is it fine to fix things in there from within Notepad++). However, it's safe to just correct them - as if the code was relying on non-constness of such literals already, we'd end up with a crash any time code attempts to write to it. Thus, the only places which are not going to be trivially fixable (by adding a `const` qualifier to parameters and variables) are potential bugs in the code.

EDIT:
#3918 seems to reference this issue - tagging @chcg

**Comment by CookiePLMonster** [comment]
UPDATE: First problem seems to be `LVCOLUMN` - it expects the string passed to be non-const, not sure why yet. Nonetheless, this is potentially the first candidate for fixing, as we can't really guarantee it never caused any issues.

**Comment by chcg** [comment]
@CookiePLMonster 
See  #2478 and #1663 as gcc is issue warnings on this. Some of them handled in #3918, but already #1663 would have fixed a lot of them. As it never got merged they are still in the codebase.

The used scintilla version is 3.5.6 with n++ specific adaptations (see also #1655 #1656). So a newer scintilla might have fixed that already.

**Comment by CookiePLMonster** [comment]
That looks fairly unfortunate... however, maybe it makes sense to redo this specific work again. All the other issues you linked concern general gcc compilation errors, whereas a change only concerning constness of string literals would naturally be of a narrower scope, and thus easier to maintain.

I have const'ified some stuff already in the code and yet to encounter any issues - I guess I'll take a closer look in a few days from now.

**Comment by CookiePLMonster** [comment]
See #4150 - I'll self-review this PR to mark which changes are not just trivial prepend of `const` to the var type.
