### ISSUE TITLE
Notepad++ forgets open files when shutting down windows while a not saved file exists

### ISSUE THREAD

**Issue by AlainArachnid** [notepad-plus-plus/notepad-plus-plus#4148]
### Description of the Issue
Notepad++ lose the “session” (list of open files) when closing because windows is shutting down (or closing windows session) and there is an unsaved file

### Steps to Reproduce the Issue
open some files in Notepad++
create a new tab, type some chars but do not save
logout the windows session
the logout is blocked by Notepad++ asking to save or not
**at this point, Notepad++ has closed the other (not modified) files**
choose to ignore the modifications
(notepad++ crashed for 32 bits version)
close windows session
open a new windows session
open Notepad++
Notepad++ opens on a blank new file
the list of open files is lost

### Expected Behavior
List of open files should be preserved

### Configuration
Windows 10
Double installation : 64 bits and 32 bits
Notepad++ 64 7.5.4
Notepad++ 32 7.5.3
Both version have the issue. In addition, 32 bits version crash when closing after I ignore the changes

**Comment by amezick** [comment]
I have 7.5.5 64  bit on Windows 10 and having the same issue.
Even worse, the "Backup path" in Preferences->Backup is locked to "C:\Program Files (x86)\Notepad++\backup\" and can't be edited.
My account is not an admin on this system.  Creating the missing directory did not help.

**Comment by wangqr** [comment]
I had the same issue on 7.5.6 64bit.
I tried to reinstall Notepad++ (without uninstalling the current one), and the issue gets resolved.

**Comment by chojrak11** [comment]
Same here. Notepad++ (v7.5.9) regularly resets this setting. I want it enabled, but it disables it some time later. After reboot? I'm not sure:

![image](https://user-images.githubusercontent.com/15248889/49444544-c29a8e80-f7cf-11e8-85bd-31e696930dc7.png)

**Comment by sasumner** [comment]
@chojrak11 If you use multiple instances of Notepad++ and don't close the 2nd, 3rd, etc instances BEFORE finally closing the original instance, your yellow setting will be unticked when you next run Notepad++, regardless of how you had it.  Could this be affecting you?

**Comment by chojrak11** [comment]
I think not. I can only run one instance of Notepad++. It's been set this way forever.

![image](https://user-images.githubusercontent.com/15248889/49445635-aa783e80-f7d2-11e8-94db-ae9f12774089.png)

**Comment by donho** [comment]
Fix by https://github.com/notepad-plus-plus/notepad-plus-plus/commit/6000f3bb21a42a4d28d068617e0dc642ef739b26
