### ISSUE TITLE
Tabs Locked in place 

### ISSUE THREAD

**Issue by mansuramin** [notepad-plus-plus/notepad-plus-plus#4153]
### Description of the Issue
The tabs are locked in place without selection the option to lock. This happens when selecting the option for multi line. 

### Steps to Reproduce the Issue
1. Settings - Preferences - General - UN-CHECK Multi-line, UN-CHECK Lock
2. Verify tabs can be moved to different spots on top bar (i.e. not locked)
3. Settings - Preferences - General - CHECK Multi-line, UN-CHECK Lock
4. Tabs can be accessed in multiple lines ( good) 
5. Tabs Locked despite having the lock box unchecked. ( bad)

### Expected Behavior
File Tab Bar should be not be locked upon checking multi line 

### Actual Behavior
File Tab bars are locked when multi line is selected. 

### Debug Information
Notepad++ v7.3.3   (32-bit)
Build time : Mar  8 2017 - 03:37:37
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 7 (64-bit)
Plugins : mimeTools.dll NppConverter.dll NppExport.dll PluginManager.dll

**Comment by CookiePLMonster** [comment]
Failed to reproduce on v7.5.4, so either it's fixed or those repro steps aren't sufficient. Please verify your issues against **the newest** version before submitting them.

**Comment by dail8859** [comment]
This sounds like an issue from a few releases ago. So update N++ and if the issue still persists, reopen the issue.
