### ISSUE TITLE
Reuse Find-result window for new search

### ISSUE THREAD

**Issue by HvWinkel** [notepad-plus-plus/notepad-plus-plus#4158]
### Description of the request
When I want to do a "find" request that I did before, I have to do the full request again.
It woult be nice to do a new request from the find-result window. Possibly thru a double (or right) click on the search header.

**Comment by ArkadiuszMichalski** [comment]
Same as https://github.com/notepad-plus-plus/notepad-plus-plus/issues/11231, I will leave a newer request.
