### ISSUE TITLE
7.5.4 Style list is empty when run as normal user

### ISSUE THREAD

**Issue by gokeefe** [notepad-plus-plus/notepad-plus-plus#4159]
### Description of the Issue
When Notepad++ 7.5.4 is run as an Administrator, the list of styles in Style Configurator is fully populated. When run as a regular user, the style list contains only Default.

### Steps to Reproduce the Issue
1. Run Notepad++
2. Open Style Configurator window
3. Try to select a style other than Default

### Expected Behavior
See a list of style options

### Actual Behavior
Only Default style is listed unless run as Administrator

### Debug Information
Notepad++ v7.5.4   (32-bit)
Build time : Jan  1 2018 - 01:47:45
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 7 (64-bit)
Plugins : ComparePlugin.dll DSpellCheck.dll mimeTools.dll NppConverter.dll NppExport.dll NppTextFX.dll PluginManager.dll Tidy2.dll 

![000037 style configurator](https://user-images.githubusercontent.com/126059/35930990-b21b2b94-0bf0-11e8-9535-e9dce1609654.png)

**Comment by CookiePLMonster** [comment]
Unable to reproduce on Win10 64-bit.

**Comment by ArkadiuszMichalski** [comment]
@gokeefe Do you still have this problem in latest Notepad++ version?

**Comment by donho** [comment]
Not reproducible

**Comment by gokeefe** [comment]
> @gokeefe Do you still have this problem in latest Notepad++ version?

Nope, looks fine on 7.8.9 (32bit). Thanks
