### ISSUE TITLE
Version 6 and Newer and App-V

### ISSUE THREAD

**Issue by hiddenfrem** [notepad-plus-plus/notepad-plus-plus#416]
I'm trying to sequence the newest version of NPP with App-V 4.6, which seems to go well, until I try to have my clients stream it. I get "invalid destination" with the bookmarks (Desktop and Start Menu) created, and my clients don't have access to the install drive (Q:) which is standard for MS Virtualization. The previous major version of NPP (5) sequenced just as easily with no problems on the client side, either. What is it about version 6+ that's rendered it impossible for me to virtualize?

**Comment by PLogFinder** [comment]
App-V 5 has been around and matured now for several years.  Has NPP been sequenced in App-V 5 successfully, and if so, is being able to sequence in App-V 4.6 still needed?

**Comment by hiddenfrem** [comment]
Nope. Got over it :P
What I did, actually, was sequence a script to copy the file from the DP to the user's APPDATA, then creating a bookmark on their desktop...

**Comment by donho** [comment]
Outdated.
