### ISSUE TITLE
Selection reset on moving to another line or bookmark

### ISSUE THREAD

**Issue by lazair** [notepad-plus-plus/notepad-plus-plus#4160]
### Description of the Issue

While working with big log files it is handy to have a way to extend initial selection to location that is far enough to scroll to. Consider this issue to be a FEATURE and see expected behavior

### Steps to Reproduce the Issue

1. Select part of text
2. Go to line after the selection
3. Press Ctrl + mouse left click (to extend selection to this line)
### Expected Behavior

Extend initial selection up to needed line
### Actual Behavior

Cursor position changed but initial selection lost 
### Debug Information

Notepad++ v6.9
Build time : Feb 21 2016 - 21:27:55
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : ON
Local Conf mode : OFF
OS : Windows 7
Plugins : mimeTools.dll NppConverter.dll NppExport.dll PluginManager.dll PythonScript.dll XMLTools.dll

**Comment by sasumner** [comment]
@lazair 

It already works perfectly if I follow your 3 steps, except with the substitution of "Shift" for "Ctrl" in your 3rd step.

Ctrl+Lclick (plus the implied subsequent drag) is already used for the feature that allows you to create two or more non-contiguous selections.

**Comment by dail8859** [comment]
Something that may be of use to you is the "Begin/End Select" feature.

1. Set your cursor where you want the selection to start.
2. Run `Edit > Begin/End Select`
3. Move around the document, scroll, click, edit, do whatever you want
4. Place your cursor at the end of where you want the selection
5. Run `Edit > Begin/End Select` again

**Comment by lazair** [comment]
sasumner, thank you.
It was what I needed, forgot to look at shortcuts
