### ISSUE TITLE
Горячая клавиша и пиктограмма - "Перезагрузить с диска"

### ISSUE THREAD

**Issue by rus21andrey** [notepad-plus-plus/notepad-plus-plus#4161]
### Steps to Reproduce the Issue

1. Прошу назначить ГОРЯЧУЮ КЛАВИШУ для команды "Перезагрузить с диска" "ctrl+f5"
2. 
3.

**Comment by CookiePLMonster** [comment]
Translated with my limited Russian knowledge:

> Please add a hotkey for "Reload from disk" command as "Ctrl+F5".

**Comment by sasumner** [comment]
@rus21andrey 
Assign it yourself in Shortcut Mapper.
PLEASE CLOSE THIS ISSUE.
