### ISSUE TITLE
Problem with Copying and Inserting

### ISSUE THREAD

**Issue by DSV182** [notepad-plus-plus/notepad-plus-plus#4167]
I wanted to edit the PDF file in Notepad ++.
While I deleted and entered - there were no problems.
When I copied a piece of code, then I inserted and saved it - pdf stopped displaying properly in the viewer.
And if you insert a piece of code through Ctrl + B - all is normal, if through the context menu of the mouse - something is broken.
If you copy all the text, delete and paste from the buffer back (via Ctrl + B or mouse) - again a problem!
If it's a bug-fix it please, if I do not know something-tell me please.
------------------------------------------
Я хотел отредактировать пдф файл в Notepad++.
Пока я удалял и вписывал -- проблем не было.
Когда я скопировал кусок кода, затем вставил и сохранил -- пдф перестал отображаться вьювером должным образом.
Причём если вставлять кусок кода через Ctrl+V -- всё нормально, если через контекстное меню мыши -- что-то нарушается.
Если скопировать весь текст, удалить и вставить из буфера обратно (через Ctrl+V или мышкой) -- опять проблема!
Если это баг -- исправьте пожалуйста, если я чего-то не знаю -- подскажите пожалуйста.

**Comment by sasumner** [comment]
You should not be edting PDF files in Notepad++

**Comment by dail8859** [comment]
PDF files contain binary data that specifies formats, fonts, sizes, images, etc. You cannot safely edit a PDF file and ensure that it is a valid afterwards.
