### ISSUE TITLE
Syntaxis error in Batch scripts.

### ISSUE THREAD

**Issue by miermontoto** [notepad-plus-plus/notepad-plus-plus#4169]
### Description of the Issue
When coding batch scripts, the command IF's arguments will be taken as mistakes or misplaced if between brackets when in reality it works perfectly and sometimes is mandatory.

### Steps to Reproduce the Issue
1. Select "Batch".
2. Input "if [whatever] (argument & argument) ELSE (argument)

### Expected Behavior
The first argument in the bracket should be marked as a normal command.

### Actual Behavior
Sometimes is marked as a mistake, others it marks the command's argument as the actual command.

### Debug Information
http://prntscr.com/id6t92
Note that in the screenshot, 'echo' is marked differently than 'goto'.

http://prntscr.com/id6tsf
In this screenshot, Notepad++ takes 'ELSE' as a command and completely skips the other arguments.

In both cases, the script is working as expected with no error messages whatsoever.

**Comment by dail8859** [comment]
Can you provide:
1. The debug info from Notepad++ (as the template requested)
2. The theme you are using
3. The *actually* text you used in your screenshots.

**Comment by GijonDev** [comment]
I used the 'Twilight' theme. As for the _actual_ text, I think that it is pretty clear.

I'm working on the debug info.

**Comment by dail8859** [comment]
This bug is also present in SciTE v4.0.2 which means this is a problem with Scintilla. This needs reported to the Scintilla issue tracker.

SciTE screenshot:
![capture2](https://user-images.githubusercontent.com/3694843/36078776-01e371bc-0f49-11e8-9412-492ed0f3badf.PNG)

**Comment by GijonDev** [comment]
Regarding your comment, I've created a ticket in the "Scintilla" bug tracker.
https://sourceforge.net/p/scintilla/bugs/1997/

**Comment by adarce** [comment]
@dail8859: In @GijonDev's linked Scintilla ticket, the bug has been closed as fixed as of 2020-04-27. When can we expect Notepad++ to pick up the Scintilla fix?

**Comment by dail8859** [comment]
@adarce No clue. When ever the scintilla version is updated to 4.3.3 or later. I dont control any of that so it could vary between weeks or years.

**Comment by ArkadiuszMichalski** [comment]
Fixed when [upgrade Scintilla from v4.2.0 to v4.4.6](https://github.com/notepad-plus-plus/notepad-plus-plus/issues/8900).
