### ISSUE TITLE
can't assign shortcut with shift and special key

### ISSUE THREAD

**Issue by cmeriaux** [notepad-plus-plus/notepad-plus-plus#4171]
### Description of the Issue

We can't assign a shortcut 

- Shift + return
- Shift + space
- Shift + back
- Shift + ....

Those shortcut are marked as invalid, "OK" button is not clickable.

### Steps to Reproduce the Issue

1.  Open Shortcut Mapper
2. Edit a shortcut and assign "Shift + Enter"
3.  OK button is not clickable.

### Expected Behavior

OK button must be clickable

### Actual Behavior

OK button isn't clickable

### Debug Information

Notepad++ v7.5.4   (32-bit)
Build time : Feb  7 2018 - 22:59:45
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10 (64-bit)
Plugins : CodeAlignmentNpp.dll ComparePlugin.dll FileSwitcher.dll LightExplorer.dll linefilter2.dll MenuIcons.dll mimeTools.dll NavigateTo.dll NppConverter.dll NppExec.dll NppExport.dll NppFTP.dll NppGTags.dll NppMenuSearch.dll PluginManager.dll PythonScript.dll XMLTools.dll

**Comment by donho** [comment]
It's an intentional behaviour to me

**Comment by alankilborn** [comment]
> It's an intentional behaviour to me

This issue should probably be tagged with the label "not bug but feature".
