### ISSUE TITLE
Web config comments issue

### ISSUE THREAD

**Issue by anilgulwani** [notepad-plus-plus/notepad-plus-plus#4176]
### Description of the Issue

Xml tag is showing commented without closing comment when line just below is commented.
### Steps to Reproduce the Issue

1.

**Comment by dail8859** [comment]
Nobody is going to try to reproduce your issue with a 1 sentence description. Sorry.

There is a template to follow for a reason. Also posting screenshots, actual text, and a set of steps to recreate the issue greatly helps others debug the problem.
