### ISSUE TITLE
enhance ShortcutMapper behavior while resizing

### ISSUE THREAD

**Issue by cmeriaux** [notepad-plus-plus/notepad-plus-plus#4179]
- keep centered buttons while resizing
- set minimum width and height because if the dialog is too small, buttons disappear.

![capture_shortcut_mapper](https://user-images.githubusercontent.com/12024941/36172612-b6027d64-1106-11e8-983e-3d00486d609c.gif)

checkout out PR #4178 
Checkout original screenshot done by @dail8859 in #3787

**Comment by sasumner** [comment]
I'm confused.  My shortcut mapper in 7.5.4 is not resizeable at all.  Does this issue (and PR) add resizing or does it enhance it?  Does it really need sizing capability?  Sure, it's not a negative if it sizes, but the default size seems pretty good (in other words I've never had a complaint-thought about it while using).

**Comment by cmeriaux** [comment]
@sasumner it's very useful to maximize the frame. Shortcut mapper is resizeable on the last commit which is not yet delivered

**Comment by dail8859** [comment]
Closed by 7572015bda1591b1d1ec7d3b283e4bc0708ef0ee
