### ISSUE TITLE
New "yes to all" and "no to all" options would be nice

### ISSUE THREAD

**Issue by oldyellowcat** [notepad-plus-plus/notepad-plus-plus#4180]
### Description of the Issue
When many files are open and they all got changed by some other processes, npp would as you to reload one by one --- please allow "yes to all" or "no to all"

Similarly , when close npp, if many files are not saved, npp would prompt one by one ...please allow "yes to all" or "no to all"

### Steps to Reproduce the Issue

see above

**Comment by dail8859** [comment]
Use the search feature. There are numerous duplicates of this.

**Comment by dail8859** [comment]
Closing in favor of one of the many other duplicates.

**Comment by sasumner** [comment]
Notepad++ 7.8 adds the "No to All" and "Yes to All" functionality to the Save dialog, but not to the Reload dialog.
