### ISSUE TITLE
[feature request]don't hangs on save

### ISSUE THREAD

**Issue by lesto** [notepad-plus-plus/notepad-plus-plus#4181]
When the underline FS is slow (slow device or remote disk) saving will hang notepad++ until the operation is completed. 
This make very bad experience, because I would like to continue editing my file, or at least be able to edit OTHER file

### Description of the Issue
if you save a file on a slow device, notepad++ is unresponsive until the save is complete

### Steps to Reproduce the Issue
1.  open a remote folder with a bad connection
2. save a file

### Expected Behavior
the file will be saved in background while i can still edit the file.

### Actual Behavior
The whole program hang

### Other info
i understand could be hard to display waht have been and what has not been saved (and maybe the concurrency between save).

Another good idea would be to be able to set up a different temp file folder for remote disk, as this seems to create some sporadic little hangup

**Comment by MetaChuh** [comment]
a file has to be saved completely to be sure it is saved.
slower remote drives will result in slower saving.
please wait for the files to be saved before resuming work.

best practice is to make a local copy of your needed files, and copy them back to your remote folder when you are finished.

thank you for your help and best regards.

**Comment by mltony** [comment]
I would like to second this feature request.
1. VSCode already does this when editing files over SSH.
2. Freezing my Notepad++ window for a couple of seconds every time I hit Control+S doesn't sound to me like best practice.
3. If user is informed that loss of data is possible with asynchronous saving - it becomes a reasonable tradeoff: either you deal with frozen Notepad++ window every so often, or you have a rsik of losing data if your Internet goes down at the wrong moment.
4. It is often impratical to copy all the files to local computer. I am working with a giant monorep, that wouldn't fit on any reasonable hard drive. Even if I copy part of it - then I would have to deal with syncing issues - run a command to sync files every time I need to sync them. Asynchronous save in NPP would be a much more appealing option.
