### ISSUE TITLE
FEATURE REQUEST: Add option to close window/program when last tab is closed

### ISSUE THREAD

**Issue by vertigo220** [notepad-plus-plus/notepad-plus-plus#4184]
### Description of the Issue

I would like an option (not a forced change in behavior, as I'm sure there are those that prefer it the way it is) to close Notepadqq if the close button is clicked on a tab when it's the only one open.

### Steps to Reproduce the Issue
1. Open N++
2. Type something, then save it and close the tab
3. N++ stays open with a blank tab/document

### Expected Behavior

Not really expected, but preferred behavior would be for N++ to close when the last tab is closed.

### Actual Behavior

If there's just one file open, if the tab for it is closed, Notepadqq stays open with a blank tab/document.

### Debug Information

N/A

**Comment by Rejjell** [comment]
Hello. As I can see on the latest version this option is already implemented. To enable this go to Options->Settings->General->Exit on last tab closing (last option in the Tab Panel block).

**Comment by vertigo220** [comment]
So it is. My apologies, I didn't have the latest version installed. I see the other feature I requested has also been implemented. Thanks!
