### ISSUE TITLE
Open and Save dialogs should have the same style

### ISSUE THREAD

**Issue by rillig** [notepad-plus-plus/notepad-plus-plus#4188]
### Description of the Issue
In the Open dialog, the folder path field is editable.
In the Save As dialog, the folder path field is not editable.
Therefore I cannot copy a path in the Open dialog and paste it into the Save dialog.
Both dialogs should be the system dialogs and follow the same style.

![image](https://user-images.githubusercontent.com/3233724/36224296-7018f1cc-11c7-11e8-8d8b-64aaad5f1cd6.png)

![image](https://user-images.githubusercontent.com/3233724/36224338-93e5d1f6-11c7-11e8-82e7-83b642ea5bf9.png)

### Debug Information
Notepad++ v7.5.4   (64-bit)
Build time : Jan  1 2018 - 01:50:29
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10 (64-bit)
Plugins : DSpellCheck.dll mimeTools.dll NppConverter.dll

**Comment by muqadar-ali-jamali** [comment]
@rillig I am a beginner, I want to contribute to this. I have cloned the project. Can you guide me through this? This is the first time for me.

**Comment by dail8859** [comment]
This can be changed with:

`Settings > Preferences > Default Directory > Use new style save dialog`

![capture2](https://user-images.githubusercontent.com/3694843/36342898-fa7c7976-13d2-11e8-8440-1f974bc04b5f.PNG)
