### ISSUE TITLE
yaml extension for YAML files

### ISSUE THREAD

**Issue by Karsonito** [notepad-plus-plus/notepad-plus-plus#419]
"yml" extension is not enough.
Please add "yaml" too.

**Comment by dail8859** [comment]
Currently implemented.

**Comment by sirberus** [comment]
Contrary to the above comment, this is not implemented, at least not in my environment.

On a fresh install of 7.3.3 on Windows, do the following to replicate:
    - Save a file as 'foo.yaml' and note no folding appears.
    - Rename file to 'foo.yml' and note it now has folding in the left margin.

**Comment by MAPJe71** [comment]
@sirberus 
You probably need to update your `langs.xml`. Rename it to backup custom settings and restart N++. 
N++ will create a new `langs.xml` based on `langs.model.xml` which defines both `yml` and `yaml` as valid extensions for YAML files.
