### ISSUE TITLE
Open Readonly with Notepad++   >> in context menu

### ISSUE THREAD

**Issue by dwbehror** [notepad-plus-plus/notepad-plus-plus#4190]
If possible please add this feature in Notepad++

This is daily uses feature for almost programmers

None software has this simple and useful feature.

Thanks in advance I know this feature will be added by you because it is very easy nice feature.

Regards:
Anjay (webdesk)

![npp need](https://user-images.githubusercontent.com/13920095/36264124-f6383932-1291-11e8-8fc1-a6555a8f4116.jpg)

### Steps to Reproduce the Issue

1. 
2. 
3.

**Comment by sasumner** [comment]
Notepad++ has a -ro command line argument.  You can create your own right-click context menu (or a SendTo menu) item this way.

**Comment by dail8859** [comment]
I don't see how many people would find this useful at all. I agree since there are ways of launching Notepad++ in a read-only mode currently, that it would be a better solution to do as @sasumner suggested.

**Comment by dwbehror** [comment]
@sasumner Thanks for your valuable reply. When a programmer only need to see old code or function which is sensitive than it becomes necessary to open file in read-only mode. Will you please share way (method) to add option "Open Readonly in Notepad++" in context menu.

**Comment by dail8859** [comment]
If you are worried about "accidentally" modifying a file, then I recommend you not open it up in a tool made to edit files. There are much better mechanisms to ensure file integrity such as Operating System level permissions, backups, or version control software.

**Comment by sasumner** [comment]
@dwbehror I can share with you what *I* do, maybe you want to do it the same, maybe not.  First, I don't allow Notepad++ to manage file associations as I see no need for that.  I create two Explorer right-click menu options (one for normal "Edit with N++", and one for read only "Open RO with N++"; I do this using the general technique show here:  https://www.howtogeek.com/howto/windows-vista/add-open-with-notepad-to-the-context-menu-for-all-files/ .  The command line for running Notepad++ for the editable case is the N++ exe path plus `%1` and for the read-only case you simply add `-ro` to the command line: N++ exe path plus `-r0 %1`.

**Comment by dwbehror** [comment]
@sasumner Thanks for your valuable reply.

**Comment by taedev** [comment]
Thanks for the suggestion @dwbehror . I used your suggestion and although i could not edit registry due to lack of permission I created a bat file with "C:\...\notepad++ -ro %1" and associated my specific file types to open with this program (.bat)

**Comment by Psuedomonas** [comment]
I found another potentially useful guide
https://www.techspot.com/guides/1670-windows-right-click-menu/
Apparently there is third party software to do this too. I tried the available one briefly but found them tedious
