### ISSUE TITLE
Close All Tabs option on tabs context menu

### ISSUE THREAD

**Issue by ericrrichards** [notepad-plus-plus/notepad-plus-plus#4192]
### Description of the Issue
Close All Tabs option on tabs context menu would be helpful

### Steps to Reproduce the Issue

Currently, to close all open tabs, you need to:
1. Right click a tab, and select "Close All BUT This".
2. Close the remaining tab.
![image](https://user-images.githubusercontent.com/2787661/36277965-5ca8db22-1260-11e8-82e1-408d7ab78ec6.png)

or use the File -> Close All menu option.

### Expected Behavior

It would be very nice to have a Close All option in the tab right-click context menu.

**Comment by proeng** [comment]
I am looking for things to do to get more familiar to the code base, this got me excited seemed simple to do. Yet sadly the functionality is already there. Under File->Close all. Or using shorthand that is displayed next to it, on windows it is: Ctr-Shift-W.

**Comment by badearobert** [comment]
Created pull request #4387

**Comment by ArkadiuszMichalski** [comment]
It's strange that this command not exist in context menu for tab (next to the other closing commands), but in other hand we have:
- button in Toolbar
- commnad in File menu, so we can add this to standard context menu manually.

@donho Above PR was reject, so if there is actually no chance of adding this command then maybe close this bug?

**Comment by donho** [comment]
"Close All" is not related to the context (this document), that's why the PR is rejected, as well this feature request.

> Above PR was reject, so if there is actually no chance of adding this command then maybe close this bug?

You're right. closed.
