### ISSUE TITLE
Stops responding when loading an 8M binary file

### ISSUE THREAD

**Issue by samirgunic** [notepad-plus-plus/notepad-plus-plus#4193]
### Description of the Issue
Stops responding when loading an MDF or an LDF file from the context menu in File Explorer if one of them is already open. These are the database and the transaction log files as used by the ASP.NET Core project template in Visual Studio 2017 (IIS Express). The files do not need to be populated with real user data.

### Steps to Reproduce the Issue
1. Create a dummy ASP.NET Core project in Visual Studio 2017.
2. Navigate to the location of the MDF and LDF files in File Explorer.
3. Right click on the MDF file and select _Edit with Notepad++_.
4. Right click on the LDF file and select _Edit with Notepad++_.

### Expected Behavior
Each file is a binary file and no more than 8.00 MB in size. I expect Notepad++ to handle loading these files. I know it can handle much larger files than this, so it is odd that it can't load in these files. I tried doing the same with Sublime Text, and it loaded both files just fine, but it displays them as Hex table by default, unlike Notepad++ which displays them as ASCII.

### Actual Behavior
The first file is loaded in Notepad++ effortlessly and Notepad++ window gets focus. The second file, whichever it is (MDF or LDF) does not load in Notepad++ and Notepad++ stops responding. When the second file is being loaded, Notepad++ does not get focus sometimes. When it doesn't get focus, and you click on the Notepad++ button on the task bar to bring it to focus or you minimize the windows of other running programs that are obscuring it in order to bring the Notepad++ window to the front, the Notepad++ window is rendered as per screenshot exhibit B.

### Debug Information

Notepad++, v. 7.5.4, x86
Windows 10, v. 1709 (Build 16299), AMD64
Visual Studio Community 2017, v. 15.5.5
Intel Core i5-6200U Skylake, 8 GB RAM

Exhibit A
![exibita](https://user-images.githubusercontent.com/3742529/36279738-54195710-1298-11e8-9e12-12d9c83f8375.png)

Exhibit B
![exibitb](https://user-images.githubusercontent.com/3742529/36279954-0fcd29f0-1299-11e8-83b0-d29a9732b04b.png)

**Comment by MAPJe71** [comment]
You're not suppost to load binairy files with Notepad++ as it's a text editor.
Please close the issue.

**Comment by samirgunic** [comment]
@MAPJe71 would you please provide some background information on this? Why should we not use Notepad++ to load binary files? I mean there are many text editors, past and current, that support loading and editing binary files. Some of them even come with a Hex editor built right in, and in case of Notepad++ there has been at least one third party Hex editing plugin.

**Comment by MAPJe71** [comment]
From the [Notepad++ website](https://notepad-plus-plus.org/):
> Notepad++ is a free **source code editor** and Notepad replacement that supports several languages.

and from the [Scintilla website](http://www.scintilla.org/) (the core component used by Notepad++):
> Scintilla is a free source code editing component. ... Scintilla includes features especially useful when editing and debugging source code. ...

> I mean there are many text editors, past and current, that support loading and editing binary files. Some of them even come with a Hex editor built right in

Then why not use one of those?
I use [HxD](https://mh-nexus.de/en/hxd/) for those rare occasions.
> in case of Notepad++ there has been at least one third party Hex editing plugin.

Emphasis on third party. AFAIK unstable and no longer maintained.

**Comment by samirgunic** [comment]
Fair enough! I will keep this in mind for the next time I am tempted to load a binary file. Thank you!
