### ISSUE TITLE
the buffer passed to GetFullPathName was too small

### ISSUE THREAD

**Issue by IliaAnastassov** [notepad-plus-plus/notepad-plus-plus#4194]
### Error when opening a file with a long file path
When opening a file that has a very long file path, I get the error: "the buffer passed to GetFullPathName was too small.

### Steps to Reproduce the Issue
1. Create a file that has a long file path
2. Open it

### Expected Behavior
Open the file with no problems

### Actual Behavior
Throws an error

### Debug Information
the buffer passed to GetFullPathName was too small

![error_1](https://user-images.githubusercontent.com/18194451/36310165-deca4148-132f-11e8-81f1-28783b2240b1.png)
![error_2](https://user-images.githubusercontent.com/18194451/36310166-dee7ab0c-132f-11e8-8212-133d31aa3855.png)

**Comment by CookiePLMonster** [comment]
Likely related to #4078 - even if you're not on Windows 10, that covers the same topic (and would be fixable the same way).

I'll look into it later nonetheless.

**Comment by dail8859** [comment]
@IliaAnastassov 

Since you didn't provide *any* info about what Notepad++ version you are using, and no debug info I'm going to assume you are on an old version (older than v6.7.8) because there is nothing in the code any more that creates this message. Plus it was already reported and fixed (~3 years ago).

**Comment by CookiePLMonster** [comment]
While this specific issue may indeed be out of date, I do think it would be beneficial to gradually phase out `MAX_PATH` from the codebase... Especially seeing comments like this:

`const rsize_t longFileNameBufferSize = MAX_PATH; // TODO stop using fixed-size buffer`

In fact, removing cases like this would be trivial - all cases like this

```
TCHAR fullpath[MAX_PATH];
::GetFullPathName(filename, MAX_PATH, fullpath, NULL);
```

would need to be replaced by one call to `GetFullPathName` to determine required buffer size, memory allocation and then another call to `GetFullPathName` to actually query data. Trivially wrapper-able.

**Comment by dail8859** [comment]
I agree that there is an underlying problem with how paths are handled. Since this issue is in regards to the dialog box showing up (which no longer exists), I'll close this particular issue and any further info and discussion should be done on #4078
