### ISSUE TITLE
Editor jitters with extra digit in line numbers

### ISSUE THREAD

**Issue by ChaosinaCan** [notepad-plus-plus/notepad-plus-plus#420]
When line numbers are enabled, it is possible to get the editor into a state where the entire editor jitters back and forth horizontally. It looks like it is looping through the following:
1. Adjust the scroll position so that the last line in the window requires an extra digit. (I got this to occur at line 1000. It probably happens for 100, 10000, etc.)
2. The line number section expands to accommodate the extra digit. All text in the editor shifts to the right.
3. The horizontal scrollbar appears momentarily. (This might require the window to be a specific size as well.)
4. The horizontal scrollbar now covers the last line in the window. It no longer requires as many digits to display the line numbers, so the line number section shrinks and all text in the editor shifts to the left.
5. The horizontal scrollbar disappears, uncovering the line number. Return to step 2.

**Comment by szheng95** [comment]
Replicated on 10,000 lines.
Not an issue on 100 lines because the line number section doesn't need to expand.

**Comment by sanastasiou** [comment]
I can confirm this as well with 1000 lines.

**Comment by Mygao** [comment]
I can confirm this too with 1000 lines.
Replicated by adjusting window "width" to specific size so that the horizontal scrollbar is not appeared at 999 lines but appears on 1000 lines.

**Comment by donho** [comment]
Update your Notepad++ to v7.6.6.
If this bug persists in the new release, please open a new issue with the debug information.
