### ISSUE TITLE
plugins cannot show the correct status of the opened files

### ISSUE THREAD

**Issue by KlausiD** [notepad-plus-plus/notepad-plus-plus#4201]
plugins cannot show the correct status of the opened files after startup. 
The plugins are not notified until the status of a file changes after opening npp.
The plugins must be able to check the correct status of the files when loading.
For this purpose, there are no query possibilities for readonly modified and dirty flag of the files
show the Plugin Windowsmanager and Navigate To

open a session with readonly Files and you see in this Plugins all Files are writable.
Please add following NPP-Messages:
NPPM_GETREADONLYFROMPOS
NPPM_GETMODIFYFROMPOS
NPPM_GETDIRTYROMPOS

**Comment by donho** [comment]
Could you provide the complete description for this request?

**Comment by KlausiD** [comment]
### Description of the Issue
plugins cannot show the correct status of the opened files after startup.
The plugins are not notified until the status of a file changes after opening npp.
The plugins must be able to check the correct status of the files when loading.
For this purpose, there are no query possibilities for readonly modified and dirty flag of the files
show the Plugin Windowsmanager and Navigate To

### Steps to Reproduce the Issue
- use npp.8.1.2.portable
- add https://github.com/young-developer/nppNavigateTo/releases/tag/1.12.4
- start npp
- open a file
- change the file, but no save the file
- start the plugin navigateto
     --> at the navigatto windows is the change File read.
- close navigateto
- close npp
- start npp
 --> the loaded changed file is red
 - start the plugin navigateto
     --> at the navigatto windows is the change File not read!


with the pull request #4242 you can change the plugin navigatto so that it marks the files correctly on startup.

### Debug Information
Notepad++ v8.1.2   (32-bit)
Build time : Jul 16 2021 - 01:56:21
Path : D:\Download\pn\npp.8.1.2.portable\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : ON
Cloud Config : OFF
OS Name : Windows 10 Home (64-bit) 
OS Version : 2004
OS Build : 19041.1110
Current ANSI codepage : 1252
Plugins : mimeTools.dll NavigateTo.dll NppConverter.dll NppExport.dll 

@donho: is that what you meant?

**Comment by donho** [comment]
@KlausiD 
Thank you for your detailed info.
So are you the dev of NppNavigateTo ?

**Comment by KlausiD** [comment]
@donho
no, i'm not the dev of NppNavigateTo.
But I am a user and often have many files open in Npp++. That's why I often use NppNavigateTo.
So I extended NppNavigateTo with this function for me.

**Comment by donho** [comment]
[Your PR](https://github.com/notepad-plus-plus/notepad-plus-plus/pull/4242) adds the new capacity (`NPPM_GETBUFFERSTATUS `). However, to solve the problem, it needs the dev of NppNavigateTo use this API, right?

**Comment by KlausiD** [comment]
Yes, but I changed the NppNavigateTo for me.
But this is only the first step. There are other problems: 
If a file is saved under a different name, or a file is moved to the other view, this is also not recognized correctly.

The best would be, if the functionality of NppNavigateTo would be integrated into the document list of npp++. 
Then you would not need this plugin anymore. 
This would only require a filter field and a sort button like in the list function.
This would be the best solution in my opinion.

**Comment by donho** [comment]
@KlausiD 
I would like solve your problem, but it doesn't work like that.
[The notification `NPPN_SNAPSHOTDIRTYFILELOADED`](https://github.com/notepad-plus-plus/notepad-plus-plus/blob/master/PowerEditor/src/MISC/PluginsManager/Notepad_plus_msgs.h#L591) is already there for plugins to notify plugins that a snapshot dirty file is loaded on startup. 
You need create an issue in NppNavigateTo for reporting the bug, and notifying the author to use this notification message to fix it.
