### ISSUE TITLE
Unable to drag text to start of line for any line# > 35

### ISSUE THREAD

**Issue by nebosite** [notepad-plus-plus/notepad-plus-plus#4205]
(Note: can't reproduce after rebooting OS)

### Description of the Issue
If I have a document longer than 35 lines, if I try to drag a line from one part of the document to the beginning of a line > 35, then I am unable to drop the text.

### Steps to Reproduce the Issue

1.   Create a document 60 lines long with a little bit of text at the start of each line
2.  Select all of line 10
3.  Drag to the first character of line 40 and release mouse cursor

### Expected Behavior
Text should be dragged from line 10 and inserted at line 40

### Actual Behavior
Text does not move.  Instead there is an icon that seems to indicate that dragging cannot happen.  (I've seen two icons so far, one is a page with a red "slash" circle, and the other is a normal document icon. ) The icon appears only after line 34 and only when dragging to the first two characters of the line.  If I drag to the 3rd character, it works normally.   It does not matter from where I start the drag operation. 

### Debug Information

Notepad++ v7.5.4   (32-bit)
Build time : Jan  1 2018 - 01:47:45
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10 (64-bit)
Plugins : DSpellCheck.dll mimeTools.dll NppConverter.dll NppExport.dll PluginManager.dll 

I've tried re-starting notepad and I've also tried on several different documents and the behavior is consistent.   This started happening only recently.   I rebooted OS and the problem went away.

**Comment by MetaChuh** [comment]
not reproducible on 7.6.6

thank you for your help and best regards.
