### ISSUE TITLE
Folder as Workspace

### ISSUE THREAD

**Issue by CoR--** [notepad-plus-plus/notepad-plus-plus#4213]
### Description of the Issue

Sometimes Folder as Workspace does not show all files. 
Restarting N++ always help. 

### Steps to Reproduce the Issue

1. Use N++ for few days, 
2. have 4-5 folder depths
3. open folder and you'll see 1 or 2  files instead of 3 or 4.

### Expected Behavior

I expect to see all files in a folder.

### Actual Behavior

Folder as workspace, sometimes show all files, but sometimes shows just few files.

### Debug Information

Notepad++ v7.5.4   (32-bit)
Build time : Jan  1 2018 - 01:47:45
Path : D:\Soft\N++\notepad++.exe
Admin mode : OFF
Local Conf mode : ON
OS : Windows 10 (64-bit)
Plugins : ComparePlugin.dll DSpellCheck.dll JSLintNpp.dll JSMinNPP.dll mimeTools.dll NppConverter.dll NppExport.dll zoomdisabler.dll

**Comment by donho** [comment]
Cannot reproduce in v7.8.2
