### ISSUE TITLE
Styler crashes Notepad ++

### ISSUE THREAD

**Issue by gdeckler** [notepad-plus-plus/notepad-plus-plus#4215]
On Windows 10, 64-bit version of Notepad++. When defining a new, user defined language, clicking on any of the Styler buttons crashes Notepad++

### Steps to Reproduce the Issue

1. Open Notepad++ (64-bit, latest version)
2. In menu, click on Language | Define your language
3. In "Folding in comment style" area click Styler

### Expected Behavior
That the Styler would open

### Actual Behavior
Notepad++ : a free (GNU) source code editor has stopped working. A problem caused the program to stop working correctly. Windows will close the program and notify you if a solution is available.

### Debug Information
Notepad++ v7.5.4   (64-bit)
Build time : Jan  1 2018 - 01:50:29
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10 (64-bit)
Plugins : DSpellCheck.dll mimeTools.dll NppConverter.dll

**Comment by CookiePLMonster** [comment]
Can't reproduce.

**Comment by gdeckler** [comment]
Reboot seems to have resolved.

Gregory J. Deckler
Cloud Practice Manager
[MVP_Logo_Avatar_Preferred_Cyan300_CMYK_72ppi] Data Platform – 2016-2017

440 Polaris Parkway, Suite 500
Westerville, OH 43082
Mobile:    614.558.3688
www.fusionalliance.com<http://www.fusionalliance.com/>

[linkedin]<https://www.linkedin.com/in/gregdeckler> [twitter] <https://twitter.com/GregDeckler>
Rethink Opportunities. Realize Possibilities.
Top Workplaces 2017: Indianapolis ● Columbus ● Cincinnati
[https://fusionalliance.sigstr.net/uc/57235cc855756200238d1580/img]<https://fusionalliance.sigstr.net/uc/57235cc855756200238d1580>
