### ISSUE TITLE
Mouse constantly switching between select/text-input when hovering over selectable elements.

### ISSUE THREAD

**Issue by gitmeister** [notepad-plus-plus/notepad-plus-plus#4217]
### Description of the Issue
This only happens when Notepad++ is being used. Hover over the file tabs and instead of the cursor showing a constant "arrow" it switches between arrow/text-input. It does this also when in the file open dialog when perusing directories and files to open.

Notepad++ 7.5.4 64-bit

Windows 7

**Comment by sasumner** [comment]
I see a similar behavior but not on the GUI elements you do.  I see it when trying to grab the sizers for adjacent subwindows.  It is annoying but I can still grab it and do the sizing I intend to do.

**Comment by gitmeister** [comment]
Yes, it's exactly #2010 and the problem also goes away if I restart N++.

Will try to find the trigger and post info here or will start a new PR if that's better.

**Comment by MetaChuh** [comment]
@gitmeister 

i believe that all but one cause of the cursor change flickering have been solved in 7.6.6.
the remaining, but already fixed issue (#5529 > b2191e9), was triggered by double-click opening an url.

please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins if you update from version 7.5.9 or below.

note: the remaining url fix will be available at the next release.

thank you for your help and best regards.

**Comment by Bluesman74** [comment]
Hi, I'm getting this problem in version 7.7.

Again like for the previous people, closing and reopening Notepad++ fixes this.

It was especially noticeable when "Move to other View" had been performed and you are hovering over the splitter
