### ISSUE TITLE
Feature Request: Remember the last session state across updates

### ISSUE THREAD

**Issue by richrice** [notepad-plus-plus/notepad-plus-plus#422]
It would be nice not to have to choose between getting a new update or keeping the current file(s) loaded. I know there is an option to remember the last session, but I don't need this functionality most of the time. Also, instead of just reloading the files after an update, it would be nice to remember the exact cursor position state and any modifications. 

Here is a typical scenario: I load a file to read/edit and get a notification for an update. Now, I want the update, but I'm still interested in my task with the file. Being that I need the latest and greatest, I accept the update, then hunt down the text file using whatever launch method I used before, then get back to it.

Thank you for considering.

**Comment by donho** [comment]
I believe this issue has been implemented since long time ago.
Update your Notepad++ to the latest version (v7.6.6).
If the issue persists, please create a new issue for it.
Thank you.
