### ISSUE TITLE
Feature request: Delete N x columns at current cursor position

### ISSUE THREAD

**Issue by ZtrevorZ** [notepad-plus-plus/notepad-plus-plus#4225]
Would be nice if the ALT + C popup also had an option to delete N x cols from the current cursor position onward, instead of just inserting options. The alt + shift + arrow (and mouse) options tend to freeze up for very big files. Mine is 0.7gig with 9m lines. (I couldn't find a duplicate request easily... Please say if I submitted this wrongly)

**Comment by sasumner** [comment]
You could use Begin/End Select instead of alt+shift_arrows or mouse...

**Comment by ZtrevorZ** [comment]
Hi thanks, how would I use this to select e.g. only the 1st column of the file? It selects the full rows in between. Menu > edit > column mode tells me to use alt + mouse selection instead.

**Comment by sasumner** [comment]
@ZtrevorZ 
So do the "begin" select like you would think you would (put the caret at top-left of your desired column first).  Then get your desired end-point on-screen and click it while holding Alt.  Then invoke the "end" select.  Note that the begin and end are both the same command ("Begin/End Select").  This should result in a column block being selected.

**Comment by ZtrevorZ** [comment]
Thanks again, this makes sense.  It now almost succeeds, the grey selection stops about 10 lines before the very end but then npp freezes up. I just wonder if a functionality (without undo, and which forces a save) might avoid RAM usage and therefore succeed relatively quickly.  My file is very tall (9.5m lines, 58 chars wide) but it is an actual example. In the meantime I will have to run a script to read & write the whole file, if I want to delete a column. But npp does everything else I want. Much appreciated

**Comment by alankilborn** [comment]
Recommend CLOSURE of this item.
