### ISSUE TITLE
Auto-Completion From nth character input field is broken in 125% display scaling

### ISSUE THREAD

**Issue by Pigu-A** [notepad-plus-plus/notepad-plus-plus#4227]
### Description of the Issue
In 125% display scaling, no numbers could be entered into this input field. I assume that limiting the number to 1 - 9 is done by matching the text length. Which is a dumb thing to do.
![image](https://user-images.githubusercontent.com/7795387/36666010-cb65023e-1b1b-11e8-93d2-af7ebb110fec.png)

### Steps to Reproduce the Issue
1. Change the display scaling to 125% in display settings.
2. Open Notepad++, it should scale the UI to match the scaling (not display as a blurry resized 100% scaling).
3. Go to preferences then go to Auto-Completion tab.
4. Try changing the number in "From nth character" text.

### Expected Behavior
The number from 1 - 9 could be typed in like in 100% and other display scales

### Actual Behavior
No numbers could be typed in and acts like the text is too long (ding sound is played)

### Debug Information
Notepad++ v7.5.4   (32-bit)
Build time : Jan  1 2018 - 01:47:45
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10 (64-bit)
Plugins : DSpellCheck.dll mimeTools.dll NppConverter.dll NppExport.dll

**Comment by snoopy78** [comment]
It's a dublicate of bug #3010.

**Comment by MetaChuh** [comment]
please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins if you update from version 7.5.9 or below.

<img width="1258" alt="" src="https://user-images.githubusercontent.com/45773305/57076336-b3216200-6ce9-11e9-8493-be88aa0123c3.png">

thank you for your help and best regards.

**Comment by pete312** [comment]
This is still not working for me on version 7.8.5. Can you please verify its working now ?

**Comment by snoopy78** [comment]
I have verified it with v7.8.5 (x64). It's working for me with Win 10. Tested with 125%.
