### ISSUE TITLE
Sessions feature enhancement

### ISSUE THREAD

**Issue by mkliemann** [notepad-plus-plus/notepad-plus-plus#4228]
### Description of the Issue
When working with more than one project, we often need to quickly switch between them, and the session in use should be also switched.
By clicking a Notepad++ session file, that session will be loaded - that's ok. However, the session is not automatically updated - you must remember to save it manually before exiting (and this is a pain).
On the other side, the automatic session backup feature works on an unique "global" session.
So, the feature I request is to allow automatically updates to the session´s file Notepad++ was started with.

**Comment by thowalt** [comment]
Also view aspects are not saved within the sessions context.
For example if you used the "Open Folder as Workspace" Option this view is not retained when saving/loading the session. Other views might be impacted too.

**Comment by ZenTurnip** [comment]
Upvote at least first point.

**Comment by donho** [comment]
Implemented in #10935:
Set to "Open session in a new instance of Notepad++" option in Preference then all your modification of this session will be save automatically.
