### ISSUE TITLE
always reload silently, ask for reload every 100 times

### ISSUE THREAD

**Issue by sl5net** [notepad-plus-plus/notepad-plus-plus#4232]
### Description of the Issue

My scripts write to a logfile. Its opened in Notepad++ to see any new content. its reloads automatically (if it gots focus again). But sometimes then i got the message: "your file is open in another program would you reload it" i always press enter. 

### Expected Behavior
reload silently (without msgbox).

### Actual Behavior
reload silently 200 or 1000 times. and then some days (onca a day or so) it ask for reloading 

### Debug Information
Notepad++ v7.5.4   (64-bit)
Build time : Jan  1 2018 - 01:50:29
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : ON
Local Conf mode : OFF
OS : Windows 10 (64-bit)
Plugins : DSpellCheck.dll mimeTools.dll NppConverter.dll 

https://stackoverflow.com/questions/48963142/how-reload-notepad-without-press-enter-sometimes

**Comment by donho** [comment]
You can turn reload silently on via preference dialog.
