### ISSUE TITLE
Can't save file on mounted sftp drive

### ISSUE THREAD

**Issue by aunriz** [notepad-plus-plus/notepad-plus-plus#4234]
### Description of the Issue

Notepad++ is unable to save or edit any text file on the drive mounted using a software SFTP Net Drive 2017, saving and editing of files work using windows notepad or netbeans.

### Steps to Reproduce the Issue

1. Intall SFTP Net Drive 2017, connect to any sftp account and mount it as a drive
2. Open the mounted drive, create new text doucment, edit the file with notepad++.
3. Write anything and save.

### Expected Behavior

It should save the file

### Actual Behavior
Dialog box saying, The file cannot be saved and it may be protected, Do you want to launch Notepad++ in Administrative mode?
On yes, it opens in administrative mode, saving again it says, please check if this file is opened in another program.
It does not save the file
On just attempting to save the file, it clears the content of the file, and saves it as empty file, while checking with other editor like windows notepad or netbeans

### Debug Information

Notepad++ v7.4.1   (64-bit)
Build time : May 18 2017 - 02:02:28
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : ON
Local Conf mode : OFF
OS : Windows 10 (64-bit)
Plugins : mimeTools.dll NppConverter.dll

**Comment by CookiePLMonster** [comment]
You're on a very outdated version, does this still happen on 7.5.4?

**Comment by aunriz** [comment]
Same thing happens on 7.5.5
I tried connecting a different sftp server, the problem does not occur on the other server, apparently the problem is related to OpenSSH that I am using on my sftp server, whatever might be the case the other editors ie, notepad and netbeans worked fine. I am closing this issue.
