### ISSUE TITLE
Some(?) preferences are not saved

### ISSUE THREAD

**Issue by tgschultz** [notepad-plus-plus/notepad-plus-plus#4237]
### Description of the Issue
Preferences to not persist across restarts of Notepad++.

### Steps to Reproduce the Issue
Settings->Preferences->New document => Set "Format (Line ending)" to "Unix (LF)"
Settings->Preferences->Editing => Select "[Default]" under "Tab Settings" and check "Replace by space"
Close Notepad++
Open Notepad++ and select File->New
Hit tab, a \t is inserted instead of spaces
Edit->EOL Conversion => notice that "Windows (CR LF)" is selected.

### Expected Behavior
Changes to preferences should be saved and persisted either automatically or via explicit "Save Preferences" button or menu item. Saving the session does not save these settings either.

### Actual Behavior
The preferences were not saved.

### Debug Information
Notepad++ v7.5.4   (32-bit)
Build time : Jan  1 2018 - 01:47:45
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10 (64-bit)
Plugins : ComparePlugin.dll DSpellCheck.dll mimeTools.dll NppConverter.dll NppExport.dll NppFTP.dll nppnim.dll NppTextFX.dll PluginManager.dll

**Comment by bahusoid** [comment]
I think something wrong with you config.xml  (%appdata%\Notepad++\config.xml). Try to rename it and check if problem still exists. Closing preferences window and exiting Notepad++ saves all those settings for me.

**Comment by tgschultz** [comment]
Yes, that seems to work correctly.

Aside from the history entries and minor settings differences there are two additional "PluginDlg" lines, "Notepad++::InternalFunction" and "dummy", as well as a lone "<FileBrowser />" tag in the old config.xml.

**Comment by dail8859** [comment]
@tgschultz If you still have the old config.xml file it would be interesting to take a look at it and see if someone could replicate the issue and find the problem. Ideally it would be nice to have the exact original but if you feel better you could remove some of the more personal info such as recently used files and find/replace history.

**Comment by tgschultz** [comment]
I've removed the history lines and verified that it had no effect on the behavior.
[config.xml.txt](https://github.com/notepad-plus-plus/notepad-plus-plus/files/1768881/config.xml.txt)

**Comment by cmeriaux** [comment]
config.xml is corrupted from line 69
GUIConfig name="stylerTheme" is duplicated in the corrupted tail of the file

**Comment by tgschultz** [comment]
Pretty obvious now that it's pointed out. I wonder if multi-instance could be responsible?

**Comment by dail8859** [comment]
So nothing seems odd about the file. I tried it out and it worked fine for me.

However you mentioned multi-instance. Some quick testing shows that modifying settings while using multi-instance does have problems. For example if you start instance 1, modify some settings, then start instance 2, it does not see these *new* settings. I would guess that further testing would show that when each instance closes it writes its own settings to the xml file.

**Comment by tgschultz** [comment]
Alright, so I just retried it and I didn't have a problem either. Which is inexplicable to me. I was thinking maybe I made a mistake shuffling it around for testing, so I went and pulled a copy from yesterday's backup. That copy had no differences from the one I have marked as the broken one. So I went another day back, and that was also identical save for the very final newline being ```CR LF``` in the backup and just ```LF``` in the copy I made when it was broken. So I tried the backup copy and it is working fine now too.

Unless I imagined the whole thing, it seems there was some other factor at play here. I did all my testing with a single instance running at a time. I do use multiple instances frequently, which was my hypothesis for how it could have been corrupted, but I don't think multi-instance alone explains what I was experiencing.

Anyways, since I can't reproduce the problem anymore and don't really have a good idea what caused it, unless someone else wan's me to try something I guess this can be closed.

**Comment by cmeriaux** [comment]
imagine you have two instance running. Then you shutdown your computer without closing manually NPP. On closing, each instances writes config.xml. They could be corrupted.

**Comment by tgschultz** [comment]
But it isn't corrupted, which is the weird part. The corruption happened at some point between when I initially copied the broken config and uploading it here. Unless there was an invisible Notepad++ process hanging around during testing, I'm quite sure I was only using a single instance.

**Comment by blitzvergnugen** [comment]
I am also having issues with preferences not being saved when using -multiInst. I launch Notepad++ with "-multiInst -nosession -notabbar" to edit my git commit messages. I would like to use the "Exit on close the last tab" option, but it infrequently sticks. Most times after a computer restart, the setting is lost on my next commit edit. My default usage of Notepad++ uses mono-instance, so maybe that's conflicting?

Sorry if I'm hijacking this bug report, I'll open a new one if needed. Just seemed my issue was relevant to the current conversation.

**Comment by khdetwei** [comment]
It does not save Preferences no matter what I try. For example, if I "Enable session snapshot and periodic backup" it is not saved.

**Comment by alankilborn** [comment]
> It does not save Preferences no matter what I try. For example, if I "Enable session snapshot and periodic backup" it is not saved.

You should update to something newer than v 7.5.4 (the version discussed in this thread, so we have to assume it is your version too) and try again.  Post back if the problem persists.
