### ISSUE TITLE
Comment command not working...

### ISSUE THREAD

**Issue by EverestSoftwareLLC** [notepad-plus-plus/notepad-plus-plus#4239]
Hello,

Since updating to 7.5.4, the comment menu commands do not work. CTRL+Q, right click and select any comment command, no joy.

This feature worked in the last version I used.

Language encoding set to Javascript. It worked when I tried Java and HTML.

Notepad++ v7.5.4 (64-bit)
Build time : Jan 1 2018 - 01:50:29
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : ON
Local Conf mode : OFF
OS : Windows 7 (64-bit)
Plugins : DSpellCheck.dll mimeTools.dll NppConverter.dll

Ideas?

Mark

**Comment by EverestSoftwareLLC** [comment]
Just tested with 7.5.5, same problem.

**Comment by Watilin** [comment]
On a 32bit system, I can reproduce consistently.

1. Open new buffer
2. Set language to JavaScript
3. Write something, e.g. `"use strict;"`
4. Try commenting by either way: menu commands and keyboard shortcuts
5. Nothing happens.

> Notepad++ v7.5.4   (32-bit)
> Build time : Jan  1 2018 - 01:47:45
> Path : C:\Program Files\Notepad++\notepad++.exe
> Admin mode : OFF
> Local Conf mode : OFF
> OS : Windows 7 (32-bit)
> Plugins : CodeAlignmentNpp.dll ComparePlugin.dll DSpellCheck.dll HTMLTag_unicode.dll JSLintNpp.dll MarkdownViewerPlusPlus.dll mimeTools.dll NppConverter.dll NppEditorConfig.dll NppExport.dll NppFTP.dll NppSaveAsAdmin.dll PluginManager.dll

**Comment by MAPJe71** [comment]
No problem here with Notepad++ 7.5.**5**  (32-bit):
![togglecomment](https://user-images.githubusercontent.com/6494038/37523535-88ae6312-2927-11e8-9c7a-dd8f1d440d85.gif)

**Comment by EverestSoftwareLLC** [comment]
I installed 7.5.5 64 bit on a VM that never had Notepad++ and Javascript line comment command worked.
On the machine that had Notepad++ installed, I installed 7.5.5 64 bit and Javascript line comment command **did not** worked.
