### ISSUE TITLE
EOL deduction from file contents needed during opening the file

### ISSUE THREAD

**Issue by UniqueQueue** [notepad-plus-plus/notepad-plus-plus#424]
I use win-sshfs which mounts a remote UNIX partition on my Windows machine. When I open UNIX file, the 'EOL Conversion' set is 'Windows Format'. Saved Shell files appear broken in case you forgot to switch to UNIX EOL.

**Comment by CookiePLMonster** [comment]
This is in place for a very long time. Please close.
