### ISSUE TITLE
There's no `restrict ` keyword highlighting in **C**

### ISSUE THREAD

**Issue by badryasuo** [notepad-plus-plus/notepad-plus-plus#4245]
There's no `restrict ` keyword highlighting in **C**

`someFunc(const char *restrict s1, const char *restrict s2)`

**Comment by chcg** [comment]
@MetaChuh Seems to be part of C99 https://en.wikipedia.org/wiki/Restrict.

**Comment by chcg** [comment]
@MetaChuh Seems to be part of C99 https://en.wikipedia.org/wiki/Restrict.
