### ISSUE TITLE
64bit version got plenty problems

### ISSUE THREAD

**Issue by stAn47** [notepad-plus-plus/notepad-plus-plus#4248]
1. i installed 64 bit version 7.5.5 on windows 10 pro running inside KVM virtual machine and shortcuts such as "ctrl shift O" do not work - they rather insert a special characters. 

2. i could not get plugin manager to be shown or useful and i could not install plugins like "compare" even by copying them from 32bit installation version - does this mean that 64bit version cannot run 32bit version plugins ? 

3. plugins -> plugin manager is now gone on both of my 32 and 64 versions

hope this helps to make notepad++ even better. 

feature request: it would be really nice to show side of the opened file (right or left) when pressing ctrl+shift+O as when having 100 files opened (some on both sides) it would make the navigation much easier between left or right view and tabs.

**Comment by sasumner** [comment]
UGH.
1. Who ever said ctrl+shift+o does something?
2. Basic tenet of Windows knowledge is that 64-bit exes can't run 32-bit dlls (and vice versa)
3. Being removed by design is not a "problem"
Please CLOSE this issue.

**Comment by stAn47** [comment]
well, ok, i am sorry to polute it here, i thought that reporting that 64bit version behaves completely different than 32bit version would be a good bug report. 

maybe removing 

> Take this one if you have no idea which one you should take.

from download section x64 area would make it easier for starters. 

i have no clue about DLLs since my windows is only used for notepad++ editing php files on remote servers.

**Comment by sasumner** [comment]
> 64bit version behaves completely different than 32bit version
This is untrue.

>Take this one if you have no idea which one you should take.
Both the 32-bit version and the 64-bit version say this.  It IS confusing.  :)
It is an evolution, though; someday the 32-bit version will go away (I suppose)
