### ISSUE TITLE
Some ANSI extended characters not counted in selection counter

### ISSUE THREAD

**Issue by vlad417** [notepad-plus-plus/notepad-plus-plus#425]
In the informational bar at the bottom of the dialog, the "Sel:" counter for character count appears to not count ANSI characters valued 128-191.  I checked the upper boundary, but not the lower. Several characters within the range are not counted.  Changing encoding does not mitigate the issue.

Notepad++ v6.7.9.2
Windows 7 Pro x64

**Comment by guy038** [comment]
Hello **Vlad417**,

Yes, you're perfectly **right** ! I already notice that **issue** :-((

See my post on **SourceForge.net** N++ forums ( **2015/04/05** ), at the address, below :

https://sourceforge.net/p/notepad-plus/discussion/331753/thread/8eea2b53/#5aff

Best Regards

guy038

**Comment by GitMensch** [comment]
Just re-encountered this issue with `§` not being counted when the encoding is ANSI (it is in every other encoding).
@milipili Can you please move this to a recent milestone list (6.x would have been nice but the error is still in 7.5.4).

Note: The "real" bug here seems to be the character set as `§` is not part of ANSI. If the encoding is converted from UTF-8 (where `§` is counted) to ANSI the `§` is not counted. When I change the character set to ISO-8859-1 (which is the actual character set you see and enter...) the character `§` is counted.
This would be OK if we could set the default of ANSI files to an encoding, but it isn't possible (only for new files). Taken the file using ISO-8859-1 character set, save+close it, reopen it... and you're back to the plain ANSI encoding where the `§` is not counted :-(

**Comment by donho** [comment]
Update your Notepad++ to v7.6.6.
If this bug persists in the new release, please open a new issue with the debug information.
