### ISSUE TITLE
Monitoring (tail -f) not working on Windows XP

### ISSUE THREAD

**Issue by KantorZsolt** [notepad-plus-plus/notepad-plus-plus#4250]
### Description of the Issue
Monitoring (tail -f) is not working.

### Steps to Reproduce the Issue
**Test 1:**
Created a test.log file. Opened with Notepad++, activated the Monitoring (tail -f) function. Opened the same file with Windows notepad, wrote some lines, saved, closed. Checked Notepad++. The log file was empty. Closed Notepad++, opened the log file again with Notepad++, the changes were there.

**Test 2:**
From the cmd line executed the following command ping -t 127.0.0.1 > test.log. Opened the log file with Notepad++ and activated monitoring, but nothing happened.

### Expected Behavior
When the Monitoring feature is enabled, the content of the file should be visibly updated periodically.

### Actual Behavior
Activating Monitoring does actually nothing.

### Debug Information
Notepad++ v7.5.5   (32-bit)
Build time : Feb 27 2018 - 21:44:21
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows XP (32-bit)
Plugins : DSpellCheck.dll mimeTools.dll NppConverter.dll NppExport.dll

**Comment by SinghRajenM** [comment]
**On Windows 10**
Case 1 works perfectly for me.
In case 2, the file is updated as soon ping command exits (Ctrl+C). This also seems to be fine. Because even in directory (where monitoring file is kept), file status info is not changed unless cmd releases the file. Once ctrl+C is pressed, both in npp and in windows explorer file is updated.


Debug Info:
Notepad++ v7.5.5   (32-bit)
Build time : Feb 27 2018 - 21:44:21
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10 (64-bit)
Plugins : DSpellCheck.dll mimeTools.dll NppConverter.dll NppExport.dll

**Comment by KantorZsolt** [comment]
Yes, I understand what you are saying, I have another machine with Windows 7 on it. I need to try there also, maybe the underlying system layers are the cause. Maybe XP in this sens works differently compared to newer Windows versions. I will write after I tested it on Windows 7. Thanks for your comment.

**Comment by KantorZsolt** [comment]
I've tried test method 1 on the Windows 7 machine. The Monitoring feature works excellent.
Now this should mean that the underlying system (flushing, syncing . . .)  on Windows XP behaves differently compared to newer Windows versions. In other words the tail -f function is not compatible with Win XP. There are still peoples that are using XP (like me for example), and would be happy to have this feature on their machines. How can I 'push' this issue toward the notepad++ author?

Debug info:
Notepad++ v7.5.5   (32-bit)
Build time : Feb 27 2018 - 21:44:21
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 7 (64-bit)
Plugins : DSpellCheck.dll mimeTools.dll NppConverter.dll NppExport.dll PluginManager.dll

**Comment by KantorZsolt** [comment]
I become aware that support for Windows XP was dropped with version 7.5.1. I tried out tail -f with v7.5.1 on XP and it works fine! So this is not an issue, just support was dropped for XP. I will close the issue.
