### ISSUE TITLE
Add more specific ASN.1 UDL

### ISSUE THREAD

**Issue by r3code** [notepad-plus-plus/notepad-plus-plus#4252]
I want to contribute with my UDL of ASN.1 it's more specific that bundled in NPP now.
Please take it form here https://github.com/r3code/npp-udl/blob/master/ASN.1.UDL.npp.xml

**Comment by ArkadiuszMichalski** [comment]
@r3code You can do this in dedicated repo https://github.com/notepad-plus-plus/userDefinedLanguages.
