### ISSUE TITLE
"Open Folder as Workspace" argument when running from command line

### ISSUE THREAD

**Issue by ergaziz** [notepad-plus-plus/notepad-plus-plus#4253]
### Description of the Issue
Just like VS Code and Atom and some other editors, Notepad++ can also give ability to open folder as workspace, and better to provide this when running from command line.
Noticed it when trying to put an enhancement to Github Desktop project in [this PR](https://github.com/desktop/desktop/pull/4120)

### Expected Behavior
There can be an argument like `"-openAsWorkspace"`. When running notepad++ with this argument, it should open given folder as workspace.
```cmd
C:\Program Files (x86)\Notepad++>"notepad++.exe" -openAsWorkspace "C:\newfolder"
```

### Actual Behavior
It opens every file recursively. Especially when opening a software project solution folder, it warns about opening thousands of files. 
![npp_act2](https://user-images.githubusercontent.com/1378526/36897786-049f2ce0-1e29-11e8-9b95-7581511aa6cf.JPG)

**Comment by WorkShop-Office** [comment]
I not look bitmap

**Comment by WorkShop-Office** [comment]
cmd.to

**Comment by Alarm-Siren** [comment]
Can I just bump this feature request? It would be extremely useful to be able to get integration into GitHub Desktop, and as best I can tell this command-line aspect is the only thing preventing such integration from being possible.

**Comment by TCWORLD** [comment]
I'm interested in having NP++ work with GitHub Desktop as well.

I had a play around to see how easy it would be to get openning as workspace working. I've commited a potential solution here: https://github.com/TCWORLD/notepad-plus-plus/commit/4199cdc

Basically I added an extra flag (```-dirAsWorkspace```) to tell NP++ to treat any directory as a workspace. Of course that would still mean finding a way to get GitHub Desktop to call NP++ with the CLI flag.

Perhaps a simple batch file that desktop calls to load NP++, e.g.
```
@echo off
call "notepad++.exe" -dirAsWorkspace %*
```

**Comment by ithielnor** [comment]
@TCWORLD Perhaps you could PR that back to the master. Flag this issue, maybe they'll include it in a future build. I think if that goes in desktop/desktop#4120 can be finished.

**Comment by TCWORLD** [comment]
@ithielnor I thought about that, but based on notepad-plus-plus/CONTRIBUTING.md it says not to create pull requests until an issue has an "Accepted" label.

**Comment by TCWORLD** [comment]
I've added the pull request regardless (https://github.com/notepad-plus-plus/notepad-plus-plus/pull/5100), we shall see what happens.

**Comment by John-Christ** [comment]
Hi there, 
I would like to know how I can run a folder as a workspace on a browser for testing?
