### ISSUE TITLE
Feature Request: File Open Containing Folder be split into two menu items

### ISSUE THREAD

**Issue by raymondlaw** [notepad-plus-plus/notepad-plus-plus#4258]
### Description of the Issue

Hey this is just a request, I know i'll eventually train myself to use one of the workarounds, but I do want to make an argument at why I think this menu should be split in two.

![z](https://user-images.githubusercontent.com/2231426/36940683-4f4b4db2-1f16-11e8-8aa7-ff929f8029c5.PNG)

Getting from File to "Open Contain Folder in Explorer" via mouse is a real pet peeve of mine.  Especially since the files in my history will have arbitrary file length which makes the mouse travel distance highly variable. If you track my mouse movements from File to Explorer this can be a real pain if the longest file name in my history is very long, because the movement needs to be very precise or I will lose the dropdown.

I don't see the point of having a contextual menu with 2 items in it, especially when the previous menu already has so many, if space is an issue, you could cut history down from 10 to 9 and you'd easily recoup the lost space.

### Workarounds

* Right click the tab instead.
* ALT + F, Down, Down, Right, Enter

**Comment by ArkadiuszMichalski** [comment]
@raymondlaw You can also add this command to `contextMenu.xml` or set shortcut for them. This will be faster than select them from File menu.

**Comment by donho** [comment]
They both are in the tab bar popup menu.

**Comment by sasumner** [comment]
To illustrate what @donho said, right-click the desired tab and you'll see:

![image](https://user-images.githubusercontent.com/30118311/94152939-292be900-fe4a-11ea-8957-ce0a4946465f.png)
