### ISSUE TITLE
SmartHighlighter: whole word limitation?

### ISSUE THREAD

**Issue by Tiax** [notepad-plus-plus/notepad-plus-plus#426]
This has bothered me for a while now: it's about the constraints the SmartHighlighter has in place, i.e. finding occurrences in the active editor, when text is selected.

I would expect it to automatically highlight all occurrences of "FOO" in a snippet like

> 1 **FOO** BAR
> 2 **FOO**BAR
> 3 BAR**FOO**
> 4 **FOO**-BAR
> 5 BAR_**FOO**

when any of the "FOO"s is selected, yet it only highlights the one succeeded by the minus in line 4 and only when selecting any "FOO" surrounded by word-boundaries.

From the SmartHighlighter.cpp

```cpp
//The word has to consist if wordChars only, and the characters before and after something else
```

```cpp
FindOption fo;
fo._isMatchCase = nppGUI._smartHiliteCaseSensitive;
fo._isWholeWord = true;
```

I assume the whole word matching is there for performance reasons? Could we get a switch for this anyway, as already exists for the case-sensitive option?

**Comment by milipili** [comment]
For performance no, but probably the most appropriate value for the most users.

**Comment by Tiax** [comment]
OK I see, thanks - would be great to see this as an option in a future release. I'm sure I cannot be the only one preferring the "match whatever I select, regardless of word-boundaries" option ;)

Just for reference: behaviour in Notepad++ vs. Programmer's Notepad

![snapshot](https://cloud.githubusercontent.com/assets/2846305/8559237/08b95aa4-250b-11e5-8393-39ea1837b7d0.png)

**Comment by Rikk** [comment]
I would like it too.

**Comment by cmeriaux** [comment]
Hello,
SmartHighlighter can use the whole word option of find dialog. That's what markAll function (FindReplaceDlg::markAll - mark all using 1st style) does. So everybody could choose.

**Comment by Tiax** [comment]
@cmeriaux I'm aware of the search dialog's "Mark" feature. This is specifically about automatically highlighting currently selected text, though.

**Comment by dail8859** [comment]
:+1: Would love to see this! Possibly as a user option.

**Comment by Tiax** [comment]
FYI: Just created a pull request for this change.

**Comment by Tiax** [comment]
I'd like to revive this topic: any chance to get this integrated anytime soon?

**Comment by Tiax** [comment]
Closing this, as #2262 was merged - thanks everyone.
