### ISSUE TITLE
highlighting misses some words on duplicated view

### ISSUE THREAD

**Issue by DrDragonKiller** [notepad-plus-plus/notepad-plus-plus#4261]
### Description of the Issue
Not every word gets highlighted (by selecting a word) on a duplicated view: see images
selected word on the right side
![normal](https://user-images.githubusercontent.com/17345712/36948529-67d3b556-1fdc-11e8-9be6-9e66a0dcf971.png)
selected word on the left side
![bug](https://user-images.githubusercontent.com/17345712/36948530-67fdb55e-1fdc-11e8-994d-4924e02657a4.png)

Three words on the top left are not highlighted when selecting a word on the left side

### Steps to Reproduce the Issue

1. create a duplicted view of a file
2. select a word on the original (left) view 

### Expected Behavior
every word of that instance should be highlighted in the duplicted view as well

### Actual Behavior
not highlighting all instances

### Debug Information
Notepad++ v7.5.1   (32-bit)
Build time : Aug 29 2017 - 02:35:41
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10 (64-bit)
Plugins : JSMinNPP.dll mimeTools.dll NppConverter.dll NppExport.dll PluginManager.dll

**Comment by DrDragonKiller** [comment]
It seems like to be connected with the words beeing in the actuall view on the left side
-> The top 3 'hello's are not visible on the left side

**Comment by ArkadiuszMichalski** [comment]
I can confirm this in latest Notepad 7.9. Basically if we select `helo` in left side then all `helo` in left side get color (regardless of scrolling), but in right side only visible `helo` get color (scroll down right side and you will see this). Also when we scroll left side then color in right side will dynamically change.

**Comment by sasumner** [comment]
I find that if you leave that file open (in both views) and restart Notepad++, after the restart it isn't possible to reproduce the bug with that same file.

However if you create a `new 2` file on the left side and populate it with `hello` lines, and clone it, the `new 2` that opens on the right-hand side WILL again have the problem.

But using `new 2` on the left and `new 1` on the right will not have the problem.

Very strange indeed...

**Comment by ArkadiuszMichalski** [comment]
Not same as https://github.com/notepad-plus-plus/notepad-plus-plus/issues/7910?

**Comment by sasumner** [comment]
Yes, same as #7910 so let's close this one.
