### ISSUE TITLE
Unable to build with either VS2013 or VS2017

### ISSUE THREAD

**Issue by seishun** [notepad-plus-plus/notepad-plus-plus#4262]
### Description of the Issue

Getting lots of errors when building either `notepadPlus.vcxproj` or `notepadPlus.vs2013.vcxproj` in either VS2013 or VS2017.

### Steps to Reproduce the Issue

1. Open `notepadPlus.vcxproj` or `notepadPlus.vs2013.vcxproj` in VS2013 or VS2017.
2. Press F5.

### Expected Behavior

Project builds.

### Actual Behavior

`notepadPlus.vcxproj` in VS2013:

![image](https://user-images.githubusercontent.com/988441/36971743-77789212-2075-11e8-96c0-97ece0d3dfc5.png)

`notepadPlus.vs2013.vcxproj` in VS2013:

![image](https://user-images.githubusercontent.com/988441/36971793-a1e51c78-2075-11e8-8e1e-d88559dfd201.png)

`notepadPlus.vcxproj` in VS2017:

![image](https://user-images.githubusercontent.com/988441/36971870-e10a3528-2075-11e8-891e-72ece8229d91.png)

`notepadPlus.vs2013.vcxproj` in VS2017:

![image](https://user-images.githubusercontent.com/988441/36971968-25605f72-2076-11e8-95d4-522b9a1f6c96.png)

I'll be glad to provide detailed logs etc if needed.

**Comment by bidy** [comment]
I had to retarget the solution.
Right click the solution in the solution explorer. Click 'retarget solution'

**Comment by dail8859** [comment]
Currently buildable with VS2017

**Comment by chcg** [comment]
@donho I think we should remove https://github.com/notepad-plus-plus/notepad-plus-plus/blob/master/PowerEditor/visual.net/notepadPlus.vs2013.vcxproj now, as we moved forward to VS2017.

Also https://github.com/notepad-plus-plus/notepad-plus-plus/blob/master/PowerEditor/visual.net/notepadPlus.vcxproj should be updated from toolchain v140_xp (aka VS2015) -> v141_xp (aka VS2017)

I guess the issue arises if just VS2017 is installed and no VS2015 toolchain is available.
