### ISSUE TITLE
Local and Global Variables List within Function List(.C) -- Feature Request

### ISSUE THREAD

**Issue by ptrailblazer89** [notepad-plus-plus/notepad-plus-plus#4264]
Function List - Okay Properly Enumerates "all"-(Some times can miss?) the Functions in a .c file
Very Useful Wanted Feature would be to List all Local and Global Variables used by a particular function within the given .c File ( This  helps to visualize or Create Data Flow Diagrams More Easily -> Or Still Better draw a DFD itself for at-least a given function?)
Visual Studio does list Global Variables Used but doesn't Show Relationships to Functions or Show the Local Variables used by the Functions

![image](https://user-images.githubusercontent.com/37077548/36982716-812630a8-20b6-11e8-8e94-8a2a18b6edc1.png)

**Comment by MAPJe71** [comment]
It will no longer be a **Function** List when local and global variables are included.
Try any of the plugins that already include those i.e. TagsView, Gtag Search, NppGTags, Source Cookifier, TagLEET.

**Comment by ptrailblazer89** [comment]
Hello MAPJe71 
Thank You For The Reply...
I Was Looking Equivalent to Function List... but which opens side bar(e.g.DFD View List?) showing Results
+Source Cookifier: Does Shows the {Local,Global} Variables but doesn't show it with relationship to Functions(which DFD should show).

**Comment by dail8859** [comment]
This is well outside the scope of the function list. It is best to use a dedicated plugin as suggested.
