### ISSUE TITLE
error in http://docs.notepad-plus-plus.org/index.php/Command_Line_Switches for noPlugin

### ISSUE THREAD

**Issue by GitMensch** [notepad-plus-plus/notepad-plus-plus#4268]
### Description of the Issue
http://docs.notepad-plus-plus.org/index.php/Command_Line_Switches specifies the option as `-noPlugins` while the user manual https://github.com/notepad-plus-plus/npp-usermanual/blob/master/command-line.md specifies `-noPlugin`.

This was reported in 2015 by @imbrish https://github.com/notepad-plus-plus/notepad-plus-plus/issues/372#issuecomment-118010602

Just rechecked: It still is the same, only `-noPlugin` works.

### Debug Information
Notepad++ v7.5.4   (32-bit)
Build time : Jan  1 2018 - 01:47:45
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10 (64-bit)
Plugins : none

**Comment by Ekopalypse** [comment]
done, can be closed - see https://npp-user-manual.org/docs/command-prompt/
