### ISSUE TITLE
Clear a text file while monitoring (tail)

### ISSUE THREAD

**Issue by nmoreaud** [notepad-plus-plus/notepad-plus-plus#4269]
Hello, while debugging a Program, I use the log file in notepad++.
The monitoring feature (tail) is a great help, but when it is enabled, I cannot clear the file content (eg Ctrl+A, del).
The file is is readonly whereas I excepted it to be read/write.
Can you do something about this ?

**Comment by dail8859** [comment]
The tail feature is intentionally made to be a read only mode for viewing the file as it changes.

**Comment by musaffar-patel** [comment]
Agree with the original request to allow file to be cleared without having to switch off file monitoring
