### ISSUE TITLE
Condense comment options

### ISSUE THREAD

**Issue by vgturtle127** [notepad-plus-plus/notepad-plus-plus#428]
It doesn't make sense to have multiple hotkeys and menu items when you could just make a toggle for both and not have to worry about all that extra fuss.

So you would have toggle single line comment and toggle block comment. Then if the user makes a mistake, he can just toggle it back. If he wants to remove it, just hit the toggle key, and it will toggle it off.

This could just be a personal thought of mine, and maybe everybody likes having it separate. But nobody mentioned it, so I thought I would.

This should be a simple fix if your GUI code is good. :smiley:

**Comment by vgturtle127** [comment]
Oh, and also you could add a menu option to switch between the two, that way you easily update comments that way.

The reason I brought this up is because I am currently going through a project with over 100,000 lines of code and changing all the comments from block comments to line comments. It is boring and monotonous, but it will make the project better in the long run I suppose.

**Comment by mbilloo** [comment]
Regarding your first comment, are you suggesting a "Toggle Block Comment" similar to the "Toggle Single Line Comment" that already exists? 

Regarding your second comment, are you suggesting a single menu option/hotkey to go through the current active source file, and convert block comments into single line comments, and vice versa?

**Comment by vgturtle127** [comment]
@mbilloo This was years ago, but I basically wanted to condense all of the comment options from "add this" and "remove this" to "toggle". This eliminates an option, frees up a hotkey, and cleans up the user interface.

Notepad++ now has both of those options and a toggle for single line comments, and both options for block comments. I suggest removing all of the options and just using the "toggle" function, because it does the same thing but is more UI/UX friendly and makes more sense than having 2 or 3 options for one action.

The options also need to ensure that selected lines change to whatever the opposite of what they use to be was, if you know what I mean?

Anyway, that's what I think should happen now.

**Comment by MetaChuh** [comment]
we are closing this issue due to its age and multiple newer notepad++ versions since it was filed.

please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html).
if your issue persists, and it is still of relevance to you, please feel free to file a new issue.

thank you for your help and best regards.

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
```
[<kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd>](https://notepad-plus-plus.org/community/)
