### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by Gadget57** [notepad-plus-plus/notepad-plus-plus#4280]
### Description of the request

Would it be possible to add an "Auto Save" feature so that all the currently open files are automatically saved to disc every so often, such as 5 minutes, 10 minutes, etc?

I have a set of notes I use and I would like to store them on my Dropbox so that I could access them on any of my computers and know I am using the latest version.

Thanks,
Mike

**Comment by dinkumoil** [comment]
There is already a plugin named AutoSave which seems to do what yout want. You can install it via PluginManager.

Since the PluginManager was removed from Notepad++ installer in v7.5 you might miss it on your machine. In this case you can download PluginManager from [here](https://github.com/bruderstein/nppPluginManager/releases) and install it manually.

**Comment by Gadget57** [comment]
Thank you. That will work perfectly.


---

Mike McClellan

C-702-449-8321

O-702-748-9034

F-702-843-0444



Dynamic Web Shop









---- On Thu, 08 Mar 2018 09:07:04 -0800 Andreas Heim &lt;notifications@github.com&gt; wrote ----




There is already a plugin named AutoSave which seems to do what yout want. You can install it via PluginManager.

Since the PluginManager was removed from Notepad++ installer in v7.5 you might miss it on your machine. In this case you can download PluginManager from here and install it manually.

**Comment by Gadget57** [comment]
Hi Andreas,



Since the last update to Notepad++, I noticed that my autosave stopped working. I went to reinstall it, but the only one listed only has a time interval to do the auto save, however, it never triggers. Can you tell me what happened to the autosave that worked? I'd really like to get it back.



Thanks,

Mike
---

Mike McClellan

C-702-449-8321

O-702-748-9034

F-702-843-0444



Need to book an appointment? https://dynamicwebshop.youcanbook.me/.

http://dynamicwebshop.com/











---- On Thu, 08 Mar 2018 09:07:04 -0800 Andreas Heim <notifications@github.com> wrote ----



There is already a plugin named AutoSave which seems to do what yout want. You can install it via PluginManager.

Since the PluginManager was removed from Notepad++ installer in v7.5 you might miss it on your machine. In this case you can download PluginManager from https://github.com/bruderstein/nppPluginManager/releases and install it manually.

**Comment by sasumner** [comment]
@Gadget57 Probably best to take further discussion over to wherever the Autosave plugin is supported.

**Comment by dinkumoil** [comment]
@Gadget57 

I guess the _AutoSave_ plugin you used previously was the one by Franco Stellari. You are lucky, some days ago the author published an updated version of this plugin which should be compatible with the requirements of the new _PluginsAdmin_.

Either you can wait for the next release of Notepad++ for the plugin to be included in the official plugin list of _PluginsAdmin_ or you go to [the plugin authors site](https://sites.google.com/site/fstellari/nppplugins) to obtain a copy of the plugin and install it manually.
