### ISSUE TITLE
Access violation when running a macro

### ISSUE THREAD

**Issue by byronigoe** [notepad-plus-plus/notepad-plus-plus#4282]
### Description of the Issue
I have a macro that only does search-and-replace operations, and I have been using this macro successfully in NPP for years. The auto-updater recently upgraded my version of NPP, and now I get a Win32Exception Access Violation when running this macro.

### Steps to Reproduce the Issue
1. Run the "GA routes clean" macro (attached) on almost any file

### Expected Behavior
No exception. Worked perfectly fine in previous version.

### Actual Behavior
Win32Exception
An exception occurred. Notepad++ cannot recover and must be shut down.
The exception details are as follows:
Code: 0xC0000005
Type: Access violation
Exception address: 0x7714FCED

### Debug Information
Notepad++ v7.5.4   (32-bit)
Build time : Jan  1 2018 - 01:47:45
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10 (64-bit)
Plugins : ComparePlugin.dll DSpellCheck.dll IndentByFold.dll mimeTools.dll NppConverter.dll NppExport.dll NppFTP.dll PluginManager.dll 

Here is a dump file (by the way, the default location for the dump file should be outside of Program Files, so it doesn't require elevated privileges):
[NppDump.zip](https://github.com/notepad-plus-plus/notepad-plus-plus/files/1797362/NppDump.zip)

Here's my macro file:
[shortcuts.zip](https://github.com/notepad-plus-plus/notepad-plus-plus/files/1797375/shortcuts.zip)

![image](https://user-images.githubusercontent.com/10134042/37212191-547c6004-237c-11e8-83ca-757543964851.png)

**Comment by dinkumoil** [comment]
Seems like @donho already fixed this [(see here)](https://github.com/notepad-plus-plus/notepad-plus-plus/commit/9b565319e341341c2378e61feeaea733677b1c64).

You could try the preview build (its **only** the Npp EXE file) from [here](https://ci.appveyor.com/project/donho/notepad-plus-plus/build/1.0.1916) and see if it works for you.

**Comment by byronigoe** [comment]
Yep, [that](https://github.com/notepad-plus-plus/notepad-plus-plus/commit/9b565319e341341c2378e61feeaea733677b1c64) solved it!
