### ISSUE TITLE
Misspelled word and poor grammar in Replace dialog

### ISSUE THREAD

**Issue by KLGalloway** [notepad-plus-plus/notepad-plus-plus#4283]
### Description of the Issue

Misspelled word in Replace dialog, Occurrence as occurence after last replacement is made. Full sentence:
Replace: 1 occurrence was replaced. The next occurence was not found

Better phrasing:
Replace: 1 occurrence was replaced. No more occurrences were found.

### Steps to Reproduce the Issue

1. Replace some text and the line will appear at the bottom of the dialog after the last replacement.

### Expected Behavior

Correct spelling and grammar which always provides confidence that the product is carefully crafted.

### Actual Behavior.

Incorrect spelling and grammar.

**Comment by sasumner** [comment]
"...provides confidence that the product is carefully crafted."  :)
This is a good issue!
