### ISSUE TITLE
Error when building

### ISSUE THREAD

**Issue by levimatheri** [notepad-plus-plus/notepad-plus-plus#4284]
### Description of the Issue
I'm getting this error when trying to build from VS2017 Community:

fatal error C1083: Cannot open include file: 'atlbase.h': No such file or directory

How to fix?

**Comment by HorizonNL** [comment]
Did you try to check your project properties : platform tool-set ?  this could be an issue also, try to turn off your warning finder the W4/ 
these are not the problem fix but things my be the problem

**Comment by mere-human** [comment]
@levimatheri or @sasumner could you, please, close this issue?
We have up to date build instructions here https://github.com/notepad-plus-plus/notepad-plus-plus/blob/master/BUILD.md
