### ISSUE TITLE
Problem with new lines and character spacing

### ISSUE THREAD

**Issue by jdixon1986** [notepad-plus-plus/notepad-plus-plus#4285]
When I write batch files, Notepad++ will show line by line code.  When that same script is opened with notepad, its all one continuous line.  When I fix it in Notepad and reload it in Notepad++, there are now blank lines between each line of code

1. I am not sure how to reproduce as this doesnt appear to be a consistent issue.  I can upload the file, if that helps.

### Expected Behavior
I expect each line to actually be on each line.
### Actual Behavior
All lines are really one continuous line
### Debug Information

Notepad++ v7.5.5   (64-bit)
Build time : Feb 27 2018 - 21:50:06
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : ON
Local Conf mode : OFF
OS : Windows 7 (64-bit)
Plugins : DSpellCheck.dll mimeTools.dll NppConverter.dll 

I got nothing on how to reproduce this, but its seriously frustrating when my scripts fail due to this problem.  I have wasted 60 hours on a script, 20-30 of that was just trying to figure out why random errors were occurring....sorry, just venting.

**Comment by TeamSpen210** [comment]
Your problem is line endings - NP++ supports the different methods used in different OSes, but NP only understands the Windows method. There's a button in the menus to convert them (Edit I think).

**Comment by sasumner** [comment]
Look at the NPP status bar when your file is loaded and active (in the current editing tab).  If it doesn't say "Windows CR LF" it probably says "Linux LF".  You want it Windows for running batch files.  Double click that area of the status bar and a little window will pop up where you can select Windows.  Do that, save your file, then open in NP and you will see exactly what you were looking at in NPP.  20+ hours is a lot of time to spend on this!

**Comment by alankilborn** [comment]
Recommend CLOSING this item.
