### ISSUE TITLE
無法把 Notepad++ x64 設為預設開啟程式

### ISSUE THREAD

**Issue by danny0838** [notepad-plus-plus/notepad-plus-plus#4287]
### Description of the Issue

無法把 Notepad++ x64 設為預設開啟程式

### Steps to Reproduce the Issue

1. 安裝 Notepad++ 64 位元版本。
2. 右擊任一檔案格式 → [開啟檔案] → 選擇預設程式。
3. Notepad++ 未出現在「建議的程式」及「其他程式」列表中，點擊 [瀏覽] 並選擇 Notepad++ 作為開啟程式。
4. Notepad++ 仍未出現在「建議的程式」及「其他程式」列表中，之後雙擊檔案仍不是以 Notepad++ 開啟。
5. 對 Notepad++ 32 位元版本重複 1-3，Notepad++ 32 位元版本會出現在「建議的程式」及「其他程式」列表中，選擇後可成功設為預設開啟程式。

### Debug Information

Notepad++ v7.5.5   (64-bit)
Build time : Feb 27 2018 - 21:50:06
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 7 (64-bit)
Plugins : DSpellCheck.dll mimeTools.dll NppConverter.dll 

![2018-03-11 21_11_09-greenshot](https://user-images.githubusercontent.com/531417/37253887-a36af232-2572-11e8-8482-dd9f27ae32b3.png)
![2018-03-11 21_13_08-](https://user-images.githubusercontent.com/531417/37253891-af1f754e-2572-11e8-9ae5-82f64db2a0fa.png)
![2018-03-11 21_14_03-](https://user-images.githubusercontent.com/531417/37253889-aba851f6-2572-11e8-85c2-25cdcb49a648.png)
![2018-03-11 21_14_21-](https://user-images.githubusercontent.com/531417/37253890-ad937f40-2572-11e8-84c8-2ab588f15595.png)

**Comment by MetaChuh** [comment]
@danny0838 

here is a guide how to open your .txt or other files in notepad++ with a double click in windows explorer:

* close notepad++ if it is open

* right click on your notepad++ icon and choose "run as administrator"
(make sure you see `[Administrator]` at the top bar of your notepad++ window (see screenshot)

* go to `settings > preferences > file association` and make sure your needed extensions, like .txt are visible at the registered extensions panel (last panel on the right) as seen on this screenshot:

![Imgur](https://i.imgur.com/m0St1R0.png)

* hit close and exit notepad++

* now reopen notepad++ normally, and go to `settings > preferences > file association` again, and make sure your needed extensions are also visible for the standard user account.

* then exit notepad++ again

* right click on any .txt file and choose `open with > choose other app` and select notepad++ from this list.

* select `always use this app to open .txt files`and hit ok.

* close notepad++ again and retry opening your .txt file by double clicking on it.

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)

**Comment by danny0838** [comment]
> @danny0838
> 
> here is a guide how to open your .txt or other files in notepad++ with a double click in windows explorer:
> 
>     * close notepad++ if it is open
> 
>     * right click on your notepad++ icon and choose "run as administrator"
>       (make sure you see `[Administrator]` at the top bar of your notepad++ window (see screenshot)
> 
>     * go to `settings > preferences > file association` and make sure your needed extensions, like .txt are visible at the registered extensions panel (last panel on the right) as seen on this screenshot:
> 
>     * hit close and exit notepad++
> 
>     * now reopen notepad++ normally, and go to `settings > preferences > file association` again, and make sure your needed extensions are also visible for the standard user account. 
>     (...)

Unfortunately, it doesn't work.

I added `.css` using the administrator account, and then followed your guide to close the dialog and exit Notepad++.
![圖片](https://user-images.githubusercontent.com/531417/56054434-681acb80-5d89-11e9-9a22-24ca6d72dcda.png)

Then, I opened Notepad++ using the normal user, and `.css` doesn't show up:
![圖片](https://user-images.githubusercontent.com/531417/56054497-94364c80-5d89-11e9-9956-abbdb3b63089.png)

Notepad++ v7.5.9   (64-bit)
Build time : Oct 14 2018 - 15:19:55
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 7 (64-bit)
Plugins : DSpellCheck.dll mimeTools.dll NppConverter.dll
