### ISSUE TITLE
english.xml is not match to GUI texts

### ISSUE THREAD

**Issue by yasmise** [notepad-plus-plus/notepad-plus-plus#4294]
### Description of the Issue
1. Some texts of `english.xml` is not same as GUI texts.
2. A lot of accelerator keys are missing in `english.xml`, while they exist when you launch Notepad++ in English.

### Steps to Reproduce the Issue

1. Launch Notepad++ and change language to English. Then restart.
2. Press Alt key and you'll see `Macro` menu of main menu has accelerator key (under line) for `M`.
3. Open Preferences and change language to other than English, then change back to English.
4. `Macro` menu doesn't have accelerator key.

### Expected Behavior

Texts and accelerator keys of `english.xml` should be same as hard-coded GUI texts.

### Actual Behavior

Some contents of `english.xml` is not updated.

### Debug Information

Notepad++ v7.5.5   (64-bit)
Build time : Feb 27 2018 - 21:50:06
Path : D:\softs\notepad\notepad++.exe
Admin mode : OFF
Local Conf mode : ON
OS : Windows 10 (64-bit)
Plugins : DSpellCheck.dll mimeTools.dll NppConverter.dll

**Comment by yasmise** [comment]
I checked differences between english.xml and GUI by seeing, and [here is the result](https://github.com/notepad-plus-plus/notepad-plus-plus/compare/master...yasmise:acckey_update).

I'm not sure how should this be fixed (by fixing english.xml or by fixing source codes), so at this point, I didn't open a pull request. Please let me know if it is okay to open a pull request by the commit above.

**Comment by donho** [comment]
Hi @yasmise  the english.xml should following UI.
Feel free to do the PR please. Thank you.

**Comment by yasmise** [comment]
@donho OK, pull request is ready at #4297 .
