### ISSUE TITLE
When CR/LF is changed outside the editor, the editor does not notice the change

### ISSUE THREAD

**Issue by alwynallan** [notepad-plus-plus/notepad-plus-plus#4300]
### Description of the Issue

Eg. I created a logrotate.conf file in Notepad++ and saved it to a shared location to be used in Linux. The windows CRLF caused an error, and I fixed it with dos2unix . When focus returned to Notepad++ it detected a change and offered to reload the file, but after reloading it did not update the notice at the bottom of the screen reflecting the change.

### Steps to Reproduce the Issue

1. Save a file with CRLF format on a share accessible by Linux, and leave it open in Notepad++
2. In Linux change it to LF format with dos2unix
3. Return to Notepad++ and accept the offer to reload.

### Expected Behavior

The "Windows (CR LF)" at bottom right should change to "Unix (LF)"

### Actual Behavior

No change.

### Debug Information

Notepad++ v7.5.4   (64-bit)
Build time : Jan  1 2018 - 01:50:29
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10 (64-bit)
Plugins : DSpellCheck.dll mimeTools.dll NppConverter.dll 

Best editor keep getting better, thanks!
****

**Comment by CookiePLMonster** [comment]
Has been fixed in v7.5.5.
