### ISSUE TITLE
Windows 10 UNC Drives Inaccessible

### ISSUE THREAD

**Issue by GWCata** [notepad-plus-plus/notepad-plus-plus#4301]
### Description of the Issue

Network drives connected to my Windows 10 desktop system are no longer visible after the latest notepad++ update.  UNC drives are accessible with File Explorer and other facilities (i.e. command prompt, browsers, other utilities).
### Steps to Reproduce the Issue

1. Need Windows 10/64bit system with UNC mapped drives
2. Attempt to view UNC resources via the Notepad++ tool

### Expected Behavior

UNC drives would be displayed in dropdown list 
### Actual Behavior

The dropdown list does not display any UNC mapped resources
### Debug Information

Notepad++ v6.8.8
Build time : Dec 10 2015 - 01:11:37
Path : C:\Apps\Tools\Notepad++\notepad++.exe
Admin mode : ON
Local Conf mode : OFF
OS : Windows 10
Plugins : HTMLTag_unicode.dll JSLintNpp.dll JSMinNPP.dll mimeTools.dll NppConverter.dll NppExport.dll NppFTP.dll PluginManager.dll SpellChecker.dll sql.dll XMLTools.dll 

![image](https://user-images.githubusercontent.com/25019682/37353389-3fa3bc84-26ad-11e8-8504-fb64c129e978.png)

**Comment by CookiePLMonster** [comment]
> after the latest notepad++ update

> Notepad++ v6.8.8
Build time : Dec 10 2015 - 01:11:37

???

Or is it that it used to work on 6.8.8 and breaks on 7.5.5?

**Comment by MAPJe71** [comment]
Your steps to reproduce the issue are incomplete/unclear ...

> Attempt to view UNC resources via the Notepad++ tool

1. Attempt how?
2. Which Notepad++ _tool_ or is _tool_ a reference to Notepad++ itself?

> UNC drives would be displayed in dropdown list
> The dropdown list does not display any UNC mapped resources

What dropdown list exactly?

**Comment by GWCata** [comment]
If you use the File Open feature, which is normally how you would open a file, which will bring up an File Explorer dialog.  Any of the features for Notepad++ which bring up the file explorer dialog do not show any of the UNC mapped directories.

**Comment by GWCata** [comment]
That is correct regarding the change from 6.8.8 to 7.5.5; it was working correctly prior to the update.

**Comment by MAPJe71** [comment]
Did you try changing the dialog style?
i.e. see `Settings` > `Preferences...` > `Default Directory` > `Use new style dialog (without file extension feature & Unix style path capacity)`

**Comment by GWCata** [comment]
Did not make any difference.

**Comment by GWCata** [comment]
This is not the only application that has this issue, so I am investigating whether there is a desktop configuration setting that needs to be set/unset to eliminate this issue.

**Comment by GWCata** [comment]
I discovered that if I enter the UNC name (\\share name\directory\...) that I can access the resources located on the mapped directories; I just can't see the mappings in the drop down list.

**Comment by GWCata** [comment]
I was able to find the solution which turned out to be a setting in the registry. Computer\HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System
Add the DWORD KVP (EnableLinkedConnections=1).
