### ISSUE TITLE
Monitoring file always goes to last line (even if that options is off)

### ISSUE THREAD

**Issue by ArkadiuszMichalski** [notepad-plus-plus/notepad-plus-plus#4314]
In option `File Status Auto-Detection` I set `Enable` and `Update silently`, last option for scroll is off. When now start monitoring big file (by press eye icon) and change file in other editor then Notepad++ update view on this file but always goes to last line. This is very anoing, is there any solution to stay on actuall cursor position?

**Comment by dail8859** [comment]
Monitoring is a separate feature from auto detection. The whole point of using the tail feature is to see the end of the file.
