### ISSUE TITLE
'Save All' keyboard shortcut not working.

### ISSUE THREAD

**Issue by Fefo6644** [notepad-plus-plus/notepad-plus-plus#4315]
### Description of the Issue

While working with a single or multiple documents, if you try to save all the modified documents via keyboard shortcut `Ctrl+Shift+S` nothing happens. If you use the menu item it works perfectly.

### Steps to Reproduce the Issue

1. Open some files.
2. Modify any.
3. Press `Ctrl+Shift+S`.

### Expected Behavior

Each file should be saved automatically.

### Actual Behavior

None of the files are saved.

### Debug Information

Notepad++ v7.5.5   (64-bit)
Build time : Feb 27 2018 - 21:50:06
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10 (64-bit)
Plugins : DSpellCheck.dll mimeTools.dll NppConverter.dll PluginManager.dll 

Video here: https://youtu.be/lzON4Ud-_0c

**Comment by sasumner** [comment]
FWIW:  `Ctrl+Shift+s` works perfectly fine for me in the same version of Notepad++.
The only obvious difference is that I don't have the PluginManager....

**Comment by whitten** [comment]
Where in the code is the Ctrl+Shift+s  keypress event handled?

**Comment by sasumner** [comment]
@whitten You might try a search on the code for `IDM_FILE_SAVEALL`...

**Comment by SuperSandro2000** [comment]
Can confirm that it does work on the latest notepad version with plugin manager and dspellcheck installed.

**Comment by Fefo6644** [comment]
Well, it doesn't work for me, with or w/o plugins. I show how it doesn't work here: https://youtu.be/lzON4Ud-_0c

**Comment by sasumner** [comment]
@Fefo6644 maybe a dumb question, but are you sure it is mapped correctly via Shortcut Mapper?

**Comment by Fefo6644** [comment]
@sasumner Yes, I even tried de-referencing the shortcut and referencing it again, nothing happened.

**Comment by Fefo6644** [comment]
Okay, I was on Visual Studio and apparently it's something about **MY** system setup I am not able to figure out, because it happens the exact same thing on Visual Studio ('Save All' keyboard shortcut is also `Ctrl+Shift+S`), and I am being really skeptic about VS **AND** Npp having the same bug and performing in other peoples' systems (which they seem not to do).

PS: I tried to replicate the bug in a Win7 x86 system (not VM, with plugins) and it worked as it should, this supports the before mentioned idea.
There's no bug to fix, just a misunderstanding.
