### ISSUE TITLE
non-English characters not appearing correctly

### ISSUE THREAD

**Issue by sunk818** [notepad-plus-plus/notepad-plus-plus#432]
I'm having an issue where NotePad++ is showing some non-English characters incorrectly.

I turned off the Auto Detect encoding feature you suggested here (https://notepad-plus-plus.org/community/topic/71/misinterpreted-file), but it doesn't change how the characters appear.

![150708-08-07](https://cloud.githubusercontent.com/assets/6989799/8574823/84fa2002-254d-11e5-9395-ab76bd9695d0.jpg)

**Comment by milipili** [comment]
Could you attach a text file (or part of it) to reproduce the bug ? (the file provided in NodeBB is a .bin file for me)

**Comment by sunk818** [comment]
Can you download this file? 
https://www.dropbox.com/s/fdl7pca1w1tjwzk/insert_maxprop.txt?dl=0

**Comment by milipili** [comment]
TextEdit (MacOS 10.7) seems to have the same problem (but not vim):

> ![macos-textedit](https://cloud.githubusercontent.com/assets/5516919/8577278/e343eb34-25a7-11e5-80e7-361912e73b47.png)

**Comment by Masud2017** [comment]
### Oh my god it's a complex issue

**Comment by donho** [comment]
Update your Notepad++ to v7.6.6.
If this bug persists in the new release, please open a new issue with the debug information.
