### ISSUE TITLE
Opening mdf-file

### ISSUE THREAD

**Issue by salminej** [notepad-plus-plus/notepad-plus-plus#4321]
### Description of the Issue
Cannot open Notepad++.

### Steps to Reproduce the Issue
1. Open mdf-file with Notepad++. 

### Expected Behavior
Nothing really. I accidentally opened the file. Not sure if this happens with every mdf-files.

### Actual Behavior
The software freezes and cannot be opened again. Now I guess I have to reinstall Notepad++.

**Comment by dail8859** [comment]
No clue what an mdf file is. Please provide more info if you want any hope of someone helping.

**Comment by SuperSandro2000** [comment]
MDF is German for "Mitteldichte Holzfaserplatte" or in software similar to iso files or it is a SQL database file.
