### ISSUE TITLE
Display glitch when dragging Converter window

### ISSUE THREAD

**Issue by thdoan** [notepad-plus-plus/notepad-plus-plus#4322]
### Description of the Issue

When dragging the Converter plugin's Conversion Panel window, it repaints itself repeatedly as you're dragging.

### Steps to Reproduce the Issue

1. Click Plugins / Converter / Conversion Panel
2. Drag the Conversion Panel window around

### Expected Behavior

A normal drag behavior.

### Actual Behavior

The dragging was slow and jittery because of the repainting glitch.

### Debug Information

Notepad++ v7.5.6   (64-bit)
Build time : Mar 19 2018 - 00:23:17
Path : C:\portable\NPP\notepad++.exe
Admin mode : OFF
Local Conf mode : ON
OS : Windows 10 (64-bit)
Plugins : DSpellCheck.dll mimeTools.dll NppConverter.dll 

I will attach a screen recording if you cannot reproduce this.

**Comment by ArkadiuszMichalski** [comment]
@thdoan Do you still have this problem in latest Notepad++ version? I can't reproduce...

**Comment by donho** [comment]
It behaviours like all dockable panels. I cannot see repainting glitch mentioned above.
