### ISSUE TITLE
regsvr32 still displaying dialog when /s specified. Shell extension not installed for headless installs

### ISSUE THREAD

**Issue by craig-sco** [notepad-plus-plus/notepad-plus-plus#4324]
### Description of the Issue
If you install notepad++, via a headless deployment tool such as ansible, the shell extension 'Open with notepad++' will not be present.
If you try to workaround this by launching regsvr32 /s /i  NppShell_06.dll, it displays a confirmation dialog. This means if you try and run the regsvr32 remotely (via an ansible command), it will hang indefinitely. The /s flag should not display a dialog.

### Steps to Reproduce the Issue

Use ansible to install a notepad windows binary
1.  - name: install notepadpp 
      win_package:
      path: "{{temp_path}}\\{{notepad_pp_binary}}"
      product_id: "{{notepad_pp_product_id}}"
      arguments: /S /D={{notepad_pp_path}}
  - name: try activating shell extension manually
    win_shell: regsvr32 /s /i NppShell_06.dll
    args:
      chdir: "{{notepad_pp_path}}"
      executable: cmd

Alternatively if you just run regsvr32 /s /i NppShell_06.dll from the notepad install path you will see that it is not 'silent' but displays a dialog.

### Expected Behavior

Ideally, the first command would succeed, and shell integration would be present. However, I'd be happy enough if the second command was needed, but did not hang.

### Actual Behavior

The first command installs notepad plus plus without shell integration. The second command hangs because notepad shell extension dll does not honour the /s (silent) flag, but displays a dialog.

**Comment by andrecool-68** [comment]
flag /s removes this window

![1](https://user-images.githubusercontent.com/3471892/56432359-b114d780-62d5-11e9-8043-197b0f7a2f3d.png)

**Comment by MetaChuh** [comment]
please use the supported silent install using the notepad++ installer.
7.6.6 32 bit example: `npp.7.6.6.Installer.exe /S /D=%ProgramFiles(x86)%\Notepad++\`

note:
if you use regsvr32.exe from a script, always provide the full path of the .dll.
"regsvr32.exe /s C:\Program Files (x86)\Notepad++\NppShell_06.dll"

-----
```
general notes:

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
(no extra account is needed, just use your github account to sign in)
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)

**Comment by andrecool-68** [comment]
@MetaChuh 
I have registered these commands in the "Run" menu.

		<Command name="Add Notepad++ to the context menu" Ctrl="no" Alt="no" Shift="no" Key="0">regsvr32 /s /i NppShell_06.dll</Command>
		<Command name="Remove Notepad++ from the context menu" Ctrl="no" Alt="no" Shift="no" Key="0">regsvr32 /u NppShell_06.dll /s</Command>
	</UserDefinedCommands>

**Comment by MetaChuh** [comment]
@andrecool-68 

yes, the answer was for the author of this issue.

**Comment by andrecool-68** [comment]
@MetaChuh 
The only problem ... if the operating system is x64, then the NppShell_06.dll file should also be x64 (even for Notepad++ x32)

**Comment by straff** [comment]
Turns out the '/i' switch for regsvr32 causes interactive prompting with dialogue box despite '/s'. Dropping '/i' but keeping '/s' makes it slient. For unregistering it seems '/s' is honoured when '/u' is specified.
Specific task I've used in Ansible 2.7 to Win Server 2016:
- name: Put notepad++ in explorer dropdown
  win_command: "C:/Windows/Syswow64/regsvr32.exe /s \"{{explorer_settings.npp_path}}/NppShell_06.dll\""

and vars:
explorer_settings:
  npp_path: C:/Program Files (x86)/Notepad++

(fwiw using 32bit npp since can't get compare plugin silently installed on 64bit npp)
