### ISSUE TITLE
Monitoring a log file with lots of writting hangs Notepad++

### ISSUE THREAD

**Issue by nmoreaud** [notepad-plus-plus/notepad-plus-plus#4325]
Hello, I'm trying to monitor a file in witch I add 160 lines every 4 seconds.
Notepad++ cannot follow the rythm :
- The scrollbars flicker
- The statusbar flickers
- The editor is not updated, I don't see the file updates :-/
- The GUI doesn't respond to clicks

I must kill the process that writes log to be able to interract again with Notepad++

(Notepad++ 7.5.4 64bit)

**Comment by CollinChaffin** [comment]
Same cause as #4276 this is the same auto-refresh routine that also causes unresponsive freezing when opened docs are stored on a remote network location.

**Comment by MetaChuh** [comment]
@nmoreaud 

please disable `view > word wrap` and disable or remove all spell checker plugins, to monitor these kind of files.

-----
```
general notes:

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
(no extra account is needed, just use your github account to sign in)
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)
