### ISSUE TITLE
Closing minimized n++ from taskbar resets window size to zero

### ISSUE THREAD

**Issue by gusarov** [notepad-plus-plus/notepad-plus-plus#4328]
### Description of the Issue
When I close N++ in minimized state - it is not preserves original window boundaries and previous window state.

### Steps to Reproduce the Issue

1. Launch notepad++.exe
2. Move window to some particular place and remember that place
3. Maximize window
4. Minimize window
5. Close window (from a task bar)
6. Launch notepad++.exe

### Expected Behavior

Window should be maximized. When I click restore - should be restored to previous remembered position.

### Actual Behavior

Window is zero in size, unusable until I stretch the window manually by mouse.

v6.3.2 Windows 7

**Comment by CookiePLMonster** [comment]
Failed to reproduce on v7.5.5. What OS are you on? What version have you
tested it with?

**Comment by gusarov** [comment]
Just realized it is v6.3.2 2013 :( I'm suffering from this for years

**Comment by sasumner** [comment]
When you report a bug make sure you are using the current version.  Nobody cares about a bug in 5 year old software--unless the current version *IS* 5 years old--in which case nobody cares anyway because it is dead software.
