### ISSUE TITLE
Stop popping on file change

### ISSUE THREAD

**Issue by JeanCollas** [notepad-plus-plus/notepad-plus-plus#4329]
Current behavior:
Whenever you come back to notepad++, if a file has changed, it comes in front and asks if you want to reload. This is extremely annoying, even more when you are in explorer and click on a file "edit in notepad++", it opens and once opened it redirects you to another file. 

Proposed behavior:
- 3 colors of file instead of 2 (currently blue = "saved", red = "unsaved", could add for example orange for "changed on disk")
- pop-up only when tabbing to the file that has changed. If not, don't bother the user with a popup.
- make that popup tab-scoped = you can change of tab without answering, and you will see it again next time you go on the tab.

**Comment by HBerni** [comment]
Not exactly like your proposal but have a look at #1564 and #1087

**Comment by JeanCollas** [comment]
Indeed not exactly the same but almost, at least it has the same spirit: stop bothering the user. 
Your changes look great, why haven't they been accepted on the main branch? Probably needs some improvement, but it is already itself a huge improvement.
I must admit I don't compile my own notepad++ and would be glad to have it in the official update.

I am using notepad++ to open log files sometimes and those popups are very counterproductive.


This is the same kind of bothering behavior as the "please update" popup on every start, which should be an "in-app notification" , not stopping the work in progress...

**Comment by HBerni** [comment]
All my colleges like notepad++ much, but had been annoyed by the "update dialog" when working with trace and source files concurrently. This forced me to dig into compiling my version. I posted a pull request, which is, afaik, the proposed way to get features into the official build. My changes are not very big and I would be very pleased to see them included, but I don't know how to push on this.
