### ISSUE TITLE
GPL issue: requirement to agree to licence terms to install software is wrong

### ISSUE THREAD

**Issue by SlySven** [notepad-plus-plus/notepad-plus-plus#4333]
### Description of the Issue
The current NSIS installer ***requires*** the user to accept the terms of the license to **install** the software - but the GPL does not place any restrictions on installation and **use** of software that is so licensed - only on the distribution and access to the source code.
![inappropriate terms of installer](https://user-images.githubusercontent.com/6163092/37836285-040c6496-2eaa-11e8-9150-c25d3c5a7547.png)

  So the section high-lighted in red is totally inappropriate - especially when you consider the content shown in green that points out that the GPL says nothing about **running** the software which is what using the installer is suppose to be facilitating. Whilst the GPL FAQ does not say that an install can not demand the user to accept the GPL it does explicitly say [here](https://www.gnu.org/licenses/old-licenses/gpl-2.0-faq.html#ClickThrough) in the GPL 2.0 FAQ:
> #### Can software installers ask people to click to agree to the GPL? If I get some software under the GPL, do I have to agree to anything?
> Some software packaging systems have a place which requires you to click through or otherwise indicate assent to the terms of the GPL. This is neither required nor forbidden. With or without a click through, the GPL's rules remain the same.
> Merely agreeing to the GPL doesn't place any obligations on you. You are not required to agree to anything to merely use software which is licensed under the GPL. You only have obligations if you modify or distribute the software. If it really bothers you to click through the GPL, nothing stops you from hacking the GPLed software to bypass this.

*That last sentence also raises an interesting point in that it ought to be possible to get around this issue by modifying the installer to change the wording so that it perhaps says something like "Ok" rather than "I agree" in the button and the red marked paragraph to "You do not have to accept this agreement to install and use the software and you may give copies of it freely to others in accordance with the above terms." ...*

**Comment by MetaChuh** [comment]
@SlySven 

if you decide, that a requirement to agree to license terms to install software is wrong, please don't press on <kbd>i agree</kbd>.

many thanks and best regards.

**Comment by SlySven** [comment]
> if you decide, that a requirement to agree to license terms to install software is wrong, please don't press on "i agree".

🤦‍♂️ *\*thinks\*: does @ MetaChuh believe in a software installation fairy or some other magic thinking arrangement where the only way to get something done is to do the exact opposite of what is written?*

I *don't* have to agree to the licence to install and use the software so pressing a button that says "I do" in order to install the software makes about as much sense as some of Donald Trump's assertions about ~~COVID-19~~ a *number of things*...
