### ISSUE TITLE
Please add more kinds of the proxy settings

### ISSUE THREAD

**Issue by CHN-STUDENT** [notepad-plus-plus/notepad-plus-plus#4334]
As we know,in China,we can not download somethings normally without some tools.So i hope you can add the proxy settings for the Plugin Manager just like notepad++ Update proxy settings.
Thanks!

**Comment by CHN-STUDENT** [comment]
Sorry i find the Plugin Manager can use the proxy by notepad++ Update proxy settings.
Here are the solve way.
https://stackoverflow.com/questions/34629646/configure-proxy-settings-in-notepad-via-plugin-manager

**Comment by CHN-STUDENT** [comment]
But what kinds of the proxy it supposed?We have used the `sock v5` but i tested it can not work?Hope you can add more kinds of the proxy settings.

**Comment by dail8859** [comment]
You need to report the issue to the author of the Plugin Manager.

**Comment by CHN-STUDENT** [comment]
@dail8859 No,i mean the i hope can have more kinds of proxy like `socks v5` on the proxy settings.
By the way, i found the proxy setting can not save normally?
Could you understand me?I hope you can help me,thanks!
