### ISSUE TITLE
GPL Issue: installer display of GPL 2.0 details are truncated

### ISSUE THREAD

**Issue by SlySven** [notepad-plus-plus/notepad-plus-plus#4335]
### Description of the Issue
The GPL v2.0 displayed in the Installer "Agreement" has been truncated -  it omits the last section, specifically:

>### How to Apply These Terms to Your New Programs
> If you develop a new program, and you want it to be of the greatest possible use to the public, the best way to achieve this is to make it free software which everyone can redistribute and change under these terms.
>
> To do so, attach the following notices to the program. It is safest to attach them to the start of each source file to most effectively convey the exclusion of warranty; and each file should have at least the "copyright" line and a pointer to where the full notice is found.
>
>    one line to give the program's name and an idea of what it does.
>    Copyright (C) yyyy  name of author
>
>    This program is free software; you can redistribute it and/or
>    modify it under the terms of the GNU General Public License
>    as published by the Free Software Foundation; either version 2
>    of the License, or (at your option) any later version.
>
>    This program is distributed in the hope that it will be useful,
>    but WITHOUT ANY WARRANTY; without even the implied warranty of
>    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
>    GNU General Public License for more details.
>
>    You should have received a copy of the GNU General Public License
>    along with this program; if not, write to the Free Software
>    Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
>
>Also add information on how to contact you by electronic and paper mail.
>If the program is interactive, make it output a short notice like this when it starts in an interactive mode:
>
>    Gnomovision version 69, Copyright (C) year name of author
>    Gnomovision comes with ABSOLUTELY NO WARRANTY; for details
>    type `show w'.  This is free software, and you are welcome
>    to redistribute it under certain conditions; type `show c' 
>    for details.
>
>The hypothetical commands 'show w' and 'show c' should show the appropriate parts of the General Public License. Of course, the commands you use may be called something other than 'show w' and 'show c'; they could even be mouse-clicks or menu items--whatever suits your program.
> You should also get your employer (if you work as a programmer) or your school, if any, to sign a "copyright disclaimer" for the program, if necessary. Here is a sample; alter the names:
>
>    Yoyodyne, Inc., hereby disclaims all copyright
>    interest in the program `Gnomovision'
>    (which makes passes at compilers) written 
>    by James Hacker.
>
>    signature of Ty Coon, 1 April 1989
>    Ty Coon, President of Vice
>
> This General Public License does not permit incorporating your program into proprietary programs. If your program is a subroutine library, you may consider it more useful to permit linking proprietary applications with the library. If this is what you want to do, use the GNU Lesser General Public License instead of this License.

It may not be obvious to some but this last section is part of the license and as the opening part at the top makes clear:

> Everyone is permitted to copy and distribute verbatim copies of this license document, but changing it is not allowed.

**modifying** it - by *omitting* **part of it** is not permitted...

**Comment by MetaChuh** [comment]
@SlySven 

the separator line `END OF TERMS AND CONDITIONS` at https://www.gnu.org/licenses/gpl-2.0.html marks the end of terms and conditions.

this is followed by implementation guidelines named `How to Apply These Terms to Your New Programs`.

if you fear that others can misinterpret this line, please contact https://www.gnu.org and ask them to put the section `How to Apply These Terms to Your New Programs` into a separate page.

many thanks and best regards.

**Comment by sasumner** [comment]
@MetaChuh , it appears the GPL police are out and about...  OMG.  Who has *that* much time on their hands??

**Comment by SlySven** [comment]
Well I do get bugged by **installers** that demand I **agree** to the GPL before I can install an application - when it has no relevance to *using* the software but only on **distribution** of it to others...

It was a while ago and I don't recall that this project had made *that* mistake but seeing any GPL licence mentioned in places where proprietary software puts in an EULA - that demands the right to take ownership of your first-borne - raises my Spidey-sense for these thing. :grinning: 

Anyhow I may be wrong (sadly it does happen :woman_facepalming:) but in other cases I have always seen that last section included as well - (*including, most recently in an "Licences" item in the UI for a Toshiba TV (made by Vestel) that I had to reinstalled the firmware in* :stuck_out_tongue_closed_eyes:) - I would note that those last three sentences in that part might be informative to users/developers/forkers...
