### ISSUE TITLE
[Language] Turkish localization stays English after latest update

### ISSUE THREAD

**Issue by Tmp341** [notepad-plus-plus/notepad-plus-plus#4336]
### Description of the Issue

After the latest 7.5.6 update, Turkish language file isn't effective. Even though it is (Turkish.xml) locally presents. There was no problem before this.

### Steps to Reproduce the Issue

1. Installing latest update.
2. Changing to Turkish language.

### Expected Behavior

Language changed to Turkish.

### Actual Behavior

Language stays as English.

### Debug Information

Notepad++ v7.5.6   (32-bit)
Build time : Mar 19 2018 - 00:26:59
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10 (64-bit)
Plugins : ComparePlugin.dll nppcrypt.dll NppTextFX.dll PluginManager.dll Tidy2.dll 

![2](https://user-images.githubusercontent.com/1683388/37862187-d53932ba-2f59-11e8-8a74-95c1466641b8.jpg)

**Comment by rddim** [comment]
The problem is that you have missing `>` at line 949 `</FindInFinder` must be `</FindInFinder>`
Also you have incorrect strings at line 1033 `<ÇevirOpenInAdminMode` must be `<OpenInAdminMode` and at line 1165 `<Çevirfinder-find-in-finder` must be `<finder-find-in-finder`

**Comment by Tmp341** [comment]
How could i've missed those? 👍

**Comment by Tmp341** [comment]
There is still an error or Notepad++ doesn't work with copy paste localizations. No change, even after locally error fixing.

**Comment by SinghRajenM** [comment]
> No change, even after locally error fixing.

Follow below steps - 
1. Switch to English language (Settings->Preferences->General->Localization->English)
2. Update the Turkish localization in "%programfiles%\Notepad++\localization" or "%programfiles(x86)%\Notepad++\localization" based on your system architecture.
3. Now switch back to your localized language (similar to step 1).

It should work.

**Comment by SinghRajenM** [comment]
Also there is one more issue around line 473.

```
<ShortcutMapperSubDialg title="Kısayol">
                <Item id="1" name=Tamam"/>
```

```name=Tamam"``` should contain quote after sign =.

**Comment by Tmp341** [comment]
Because of those lines, my localization isn't working. I have to figure out my mistakes.

**Comment by nesbilisim** [comment]
Solved,
Please add attached file in to localization.
[turkish.zip](https://github.com/notepad-plus-plus/notepad-plus-plus/files/1847175/turkish.zip)

**Comment by Tmp341** [comment]
@nesbilisim What is the difference?

**Comment by nesbilisim** [comment]
i found different wrong code too and i added and corrected all of them. now we have ready translation copy without problem.  would you please add it to your global version of notepad++. if you do so person who downloaded this software use this software without problem in Turkish.

**Comment by Tmp341** [comment]
Oh thanks. It was an encode problem. I don't know how it is messed up.

**Comment by Tmp341** [comment]
Added to PR #4338

**Comment by nacarx** [comment]
Teşekkürler nesbilisim (Erdinc Yesilyurt) kardeşim. Güzel ve tam çeviri olmuş. Ben de başlamıştım ama sizinkini görünce üşendim, bırakıp sizinkini kullandım. Ne varsa yine bizde var :)
* - * - * - * - *
Thank you nesbilisim (Erdinc Yesilyurt).
It is complete 100% and correct translation file.
