### ISSUE TITLE
Incorrect syntax highlighting in PowerShell

### ISSUE THREAD

**Issue by User2834** [notepad-plus-plus/notepad-plus-plus#4337]
### Description of the Issue

PowerShell syntax highlighting gets confused with certain string literals. Related languages like C# may also be affected.

### Steps to Reproduce the Issue

1. Create .ps1 file containing the following code-snippet

if($email -match "[~!€§°#%^&*\\``+=|\`\(){}`[\`]:;<>?,\`$'\`"äöüÄÖÜß]+" -or $email -match "ü" -or $email -match "ß") {}

2. Open file and set highlighting language to PowerShell if necessary

3, Syntax highlighting gets confused in the long string at   `"   . 
Removing   `"   in the long string solves the Problem.

### Debug Information

Notepad++ v7.5.4   (32-bit)
Build time : Jan  1 2018 - 01:47:45
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10 (64-bit)
Plugins : ComparePlugin.dll DSpellCheck.dll JSMinNPP.dll mimeTools.dll NppConverter.dll NppExport.dll PluginManager.dll 

### notes
Also observed on Windows Server 2012 R2 and 2016

**Comment by dail8859** [comment]
Fixed in Notepad++ v7.7 since it updated to Scintilla v4.1.4

--- 

![image](https://user-images.githubusercontent.com/3694843/58267432-9ceb4c80-7d51-11e9-9365-8c0925d7d35d.png)
