### ISSUE TITLE
Ability to quick preview files in a workspace / project without having to double click to open.

### ISSUE THREAD

**Issue by pdaigneault** [notepad-plus-plus/notepad-plus-plus#434]
When working with files in a workspace / project, it would be very useful to have a quick preview feature that allowed a user to view and edit the contents of the file simply by selecting the file in the project panel list. 

At the moment you have to _double click_ the file to open it and it opens the file useing a new tab which when working with a lot of files (and making many small changes to each) can leave you will lots of open tabs.

**Comment by donho** [comment]
Thank you for the FR.
Such feature could bring some confusion to users so it won't be implemented.
