### ISSUE TITLE
Find in Files Issue

### ISSUE THREAD

**Issue by DeepanSridhar** [notepad-plus-plus/notepad-plus-plus#4343]
### Description of the Issue
Currently the Find in Files option performs the search in the Foreground. If the search has to be performed on a lot of files/folders, it prevents the user from carrying out other activities. If we try to select already opened file, it goes into Not Responding status and most often we need to force close the application. To avoid this Can the 

### Steps to Reproduce the Issue
1. Open a couple of files in Notepad++
2.  Click Find in Files icon
3. Specify a bigger search range (E.g. C:\ to reproduce the issue)
4. Click on the already opened file

### Expected Behavior
The search should be running in the background by default or should provide the user with an option to explicitly search in the background similar to Eclipse. Multi threading should be enabled to perform such operations.

### Actual Behavior
Notepad++ goes into Not responding status until the search is complete and unable to use until search is complete.

### Debug Information

Not Applicable

**Comment by mirh** [comment]
If you could please update the title with something a slight more.. flashy, it wouldn't hurt.

**Comment by Faq** [comment]
related to #3562

**Comment by donho** [comment]
Scintilla is not thread safe, hence find in file cannot be asynchronous.
