### ISSUE TITLE
Feature Request: Display size of all open files

### ISSUE THREAD

**Issue by githubuser00** [notepad-plus-plus/notepad-plus-plus#4347]
Please add size column here for open files:

![f1](https://user-images.githubusercontent.com/7738909/37912518-b16ef882-30e0-11e8-836b-26cebbe09693.PNG)

![f2](https://user-images.githubusercontent.com/7738909/37912519-b17ac9b4-30e0-11e8-81ec-4a1e06bfeff5.PNG)

**Comment by ArkadiuszMichalski** [comment]
@sasumner 
This was add https://github.com/notepad-plus-plus/notepad-plus-plus/commit/b9af79f86c7cc7c264bc942c23c1a39f483d1adc.

**Comment by sasumner** [comment]
Feature available in N++ 7.8.5 and later.
