### ISSUE TITLE
fail to bulid Boost 

### ISSUE THREAD

**Issue by Lujaina95** [notepad-plus-plus/notepad-plus-plus#4348]
I follow the steps to build boost which are in https://github.com/notepad-plus-plus/notepad-plus-plus
but this what i get in the first step : 
C:\Program Files (x86)\Microsoft Visual Studio\2017\Community>cd C:\Users\analo\source\notepad-plus-plus-master\scintilla\boostregex

C:\Users\analo\source\notepad-plus-plus-master\scintilla\boostregex> BuildBoost.bat C:\Users\analo\source\boost_1_55_0 -x64

***************************************************************
Building tool to check boost version
***************************************************************

Microsoft (R) Program Maintenance Utility Version 14.13.26129.0
Copyright (C) Microsoft Corporation.  All rights reserved.

        del /q .\bin\getboostver.exe
        cl -O1 -MT -DNDEBUG -GL -nologo -IC:\Users\analo\source\boost_1_55_0    getboostver.cpp /link -OPT:REF -LTCG -nologo KERNEL32.lib USER32.lib /OUT:.\bin\getboostver.exe
getboostver.cpp
Generating code
Finished generating code

***************************************************************
Boost version in use: 1_55
***************************************************************

***************************************************************
Building Boost::regex
***************************************************************

link.jam: No such file or directory
Performing configuration checks

    - has_icu builds           : no  (cached)
...patience...
...found 541 targets...
link.jam: No such file or directory
Performing configuration checks

    - has_icu builds           : no  (cached)
...patience...
...found 541 targets...
No correctly built boost regex libraries could be found.
Try specifying the MSVC version on the command line.

Boost is available free from www.boost.org

Unzip the file downloaded from www.boost.org, and give the absolute path
as the first parameter to buildboost.bat

e.g.
buildboost.bat d:\libs\boost_1_55_0

To build 64 bit version, add "-x64" flag after the full file path.
e.g.
buildboost.bat d:\libs\boost_1_55_0 -x64

You can specify which version of the Visual Studio compiler to use
with --toolset.
Use:
  --toolset msvc-8.0     for Visual studio 2005
  --toolset msvc-9.0     for Visual Studio 2008
  --toolset msvc-10.0    for Visual Studio 2010
  --toolset msvc-11.0    for Visual Studio 2012
  --toolset msvc-12.0    for Visual Studio 2013

e.g.  To build with boost in d:\libs\boost_1_55_0 with Visual Studio 2008

        buildboost.bat --toolset msvc-9.0 d:\libs\boost_1_55_0
   

and this what i get in the second step :

C:\Users\analo\source\notepad-plus-plus-master\scintilla\boostregex>cd C:\Users\analo\source\notepad-plus-plus-master\scintilla\win32

C:\Users\analo\source\notepad-plus-plus-master\scintilla\win32>nmake -f scintilla.mak

Microsoft (R) Program Maintenance Utility Version 14.13.26129.0
Copyright (C) Microsoft Corporation.  All rights reserved.

        link -OPT:REF -LTCG -DEBUG -LIBPATH:\release\link-static\runtime-link-static\threading-multi -DEF:Scintilla.def -DLL -OUT:..\bin\Scintilla.dll .\AutoComplete.obj .\CallTip.obj .\CaseConvert.obj .\CaseFolder.obj .\CellBuffer.obj .\CharacterCategory.obj .\CharacterSet.obj .\CharClassify.obj .\ContractionState.obj .\Decoration.obj .\Document.obj .\EditModel.obj .\Editor.obj .\EditView.obj .\Indicator.obj .\KeyMap.obj .\LineMarker.obj .\MarginView.obj .\PerLine.obj .\PlatWin.obj .\PositionCache.obj .\PropSetSimple.obj .\RESearch.obj .\RunStyles.obj .\Selection.obj .\Style.obj .\UniConversion.obj .\ViewStyle.obj .\XPM.obj .\HanjaDic.obj .\ScintillaBase.obj .\ScintillaWin.obj .\BoostRegexSearch.obj .\UTF8DocumentIterator.obj .\ScintRes.res KERNEL32.lib USER32.lib GDI32.lib IMM32.lib OLE32.LIB OLEAUT32.LIB
Microsoft (R) Incremental Linker Version 14.13.26129.0
Copyright (C) Microsoft Corporation.  All rights reserved.

LINK : fatal error LNK1104: cannot open file 'libboost_regex-vc120-mt-s-1_55.lib'
NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.13.26128\bin\HostX64\x64\link.EXE"' : return code '0x450'
Stop.

i am using windows 10 
visual studio 2017
notepad++ 64 bit 
boost_1_55_0

**Comment by MAPJe71** [comment]
If you're new to programming and/or lack the abbility to analyse basic compiler/linker message as posted above you might be better of with starting on a different/easier project.

Duplicate/related to issue #1228, Community topics [13959](https://notepad-plus-plus.org/community/topic/13959/building-notepad-with-visual-studio-2015-2017) and [15457](https://notepad-plus-plus.org/community/topic/15457/issue-with-buildboost).
