### ISSUE TITLE
Open file doesn't incude extension, and wants to create new txt file.

### ISSUE THREAD

**Issue by ArtisticPhoenix** [notepad-plus-plus/notepad-plus-plus#4349]
### Description of the Issue
When opening an existing file through the file>open menu it does not include the extension in the filename.  The effect this has is to ask if you want to create a new .txt file with the same name.  Which I don't.

The workaround is to open files in notepad++ by right clicking on them and doing "open with > notepad++"

It's very irritating because once the create new .txt dialog shows up and you click no, you lose where you had browsed for the file.  So you have to go back though the process of finding the file and then right click and use windows context menu to open it.

### Steps to Reproduce the Issue
Open a file using the file menu or Ctrl+O

### Expected Behavior
Open my file without having to add the extension

### Actual Behavior
Ask me to create a new text file (.txt)

### Debug Information
Notepad++ v7.5.6 (32-bit)
OS  - Win10 pro v1709( OS Build 16.299.214)

**Comment by SinghRajenM** [comment]
You can enable this feature using below setting. 

![image](https://user-images.githubusercontent.com/14791461/48303625-5612d380-e532-11e8-83aa-172cfc19bea2.png)

**Comment by ArkadiuszMichalski** [comment]
Please update Notepad ++ to the latest version.
