### ISSUE TITLE
Move to other view uses incorrect font size

### ISSUE THREAD

**Issue by sbrynen** [notepad-plus-plus/notepad-plus-plus#435]
When you select a window and move or clone to another view, the 2nd (right) window appears to be one point (font size) larger. This occurs both in default mode and with the global font size/style set.

See attached screenshot where line 10 lines up with line 9
![image](https://cloud.githubusercontent.com/assets/6089770/8583946/813da130-2586-11e5-817e-ec2a00a6e124.png)

**Comment by aneasystone** [comment]
I suppose that font size of the cloned view always be set to default, which is larger than your original.

**Comment by sbrynen** [comment]
No, the cloned view is not the default font size; it's the current (left hand) size + 1.  In fact the bug is much easier to see if you set the global font size down to 8 or so, because 8->9 is a much bigger different than 12->13

**Comment by hypherion2** [comment]
I think this only happens if your zoom settings are different (under View->Zoom). The two views (Main view and Cloned view) keep their own, separate zoom settings. If you reset the zoom to default for both then issue is no longer reproducible.
I wouldn't say it's a bug.

**Comment by sbrynen** [comment]
You're right, this appears to be the issue. I'll close this.
