### ISSUE TITLE
Issues with opening files via command line

### ISSUE THREAD

**Issue by KemoAli** [notepad-plus-plus/notepad-plus-plus#4351]
When I tried to open a file via command line the unsave contents get discarded. A file that is open in another editor with unsave changes, if I tried to open the same file via cmd (eg start notepad++ myfile.txt), the unsave changes disappears.

**Comment by sasumner** [comment]
I think you're going to have to clarify a bit.  The way I read it, you have a file open in another editor and you have unsaved changes there.  Then you open the same file in Notepad++ and you are surprised that in Notepad++ you don't see the unsaved changes you are working on with the other editor.  Is that right?
