### ISSUE TITLE
Run with several open files

### ISSUE THREAD

**Issue by sinsedrix** [notepad-plus-plus/notepad-plus-plus#4352]
Hi Don,

### Description of the Issue
I wish I could run an external tool with several open files.
For example to use a file comparison tool: "merge file1.txt file2.txt"

I found an old doc dealing with environment variables I was expecting:
http://home.ku.edu.tr/maaron/public_html/Notepad++/plugins/doc/NppExec.txt
It says you could use $(#N), $(LEFT_VIEW_FILE), $(RIGHT_VIEW_FILE) but they are not replaced when command is run. I just can use $(FULL_CURRENT_PATH).

Would you consider restoring these environment variables in Notepad++?

Thanks

**Comment by dail8859** [comment]
What you are referencing is documentation for a plugin, not Notepad++ itself. I would contact the author of the plugin if something is not working for you.

**Comment by sasumner** [comment]
So you are talking about features of the NppExec plugin, not Notepad++ itself, which is fine, but has no relation to "Don", as NppExec is not packaged with Notepad++ (probably it once was, but no longer).  So you could request that these special strings be added to base Notepad++...but history shows that functionality that exists in a plugin rarely if ever goes "native".

But the good news is that when I tried these special strings in NppExec version 0.6 beta 1....they WORK!  Give them a try and see if that doesn't solve your problem and allow you to close this issue.

**Comment by sinsedrix** [comment]
It doesn't seem I'm using a plugin since NppExec is not in my plugin list.
I can see "Run -> Launch in Firefox, Launch in IE, ...": is it using NppExec?
Or does the NppExec plugin is installed as default (and hidden).

**Comment by sasumner** [comment]
@sinsedrix You cited "NppExec.txt".  Perhaps if you would install the NppExec plugin your problem would be solved?

**Comment by sinsedrix** [comment]
So you mean the run menu is native to Notepad++ but needs NppExec to work?

**Comment by sasumner** [comment]
No.  I'm not sure how you are inferring that.

NppExec has its own "run" mechanism--it calls it "Execute".  You get to it via Plugins (menu) -> NppExec -> Execute...  
It is there that the $(LEFT_VIEW_FILE), etc stuff works.

Of course, all this relies on one actually installing NppExec.
As of this time, the newest version of NppExec is found here:
https://github.com/d0vgan/nppexec/releases
NppExec v0.6 beta 1
