### ISSUE TITLE
error message bug in v7.5.6

### ISSUE THREAD

**Issue by pryrt** [notepad-plus-plus/notepad-plus-plus#4354]
### Description of the Issue

The second dialog box of the "file too big" in v7.5.6 (32-bit) says `Can not open file "$STRT_REPLACE$".` instead of `Can not open file "c:\path\to\bigfile.txt".`

([see Forum #15515](https://notepad-plus-plus.org/community/topic/15515/can-not-open-file-strt_replaces).  Forum user @ChillerThon reported the problem, and I was able to replicate it.)

### Steps to Reproduce the Issue

1. make a 1Gb file (or otherwise too large for 32bit Notepad++)
2. run Notepad++ 7.5.6 32-bit
3. open the 1Gb file `bigfile.txt`
4. click OK on the `File Open Problem` => `File is too big to be opened by Notepad++` dialog
5. the second error that shows up is: 
![Imgur](https://i.imgur.com/vZ7aQSH.png)
This should list the name of the file, not `$STRT_REPLACE$`.
6. Following those same steps in Notepad++ 7.5.4 32-bit, and I get
![Imgur](https://i.imgur.com/84vn1PL.png)
This correctly lists the name of the file

#### 7.5.6 (BUG)

	Notepad++ v7.5.6   (32-bit)
	Build time : Mar 19 2018 - 00:26:59
	Path : C:\Users\peter.jones\AppData\Local\Temp\npp.7.5.6.bin\notepad++.exe
	Admin mode : OFF
	Local Conf mode : ON
	OS : Windows 10 (64-bit)
	Plugins : DSpellCheck.dll mimeTools.dll NppConverter.dll NppExport.dll 

#### 7.5.4 (WORKING)

    Notepad++ v7.5.4   (32-bit)
    Build time : Jan  1 2018 - 01:47:45
    Path : C:\Program Files (x86)\Notepad++\notepad++.exe
    Admin mode : OFF
    Local Conf mode : OFF
    OS : Windows 10 (64-bit)
    Plugins : ComparePlugin.dll dbgpPlugin.dll DSpellCheck.dll MarkdownViewerPlusPlus.dll mimeTools.dll NppConverter.dll NppExec.dll NppExport.dll NppFTP.dll PluginManager.dll PreviewHTML.dll PythonScript.dll XMLTools.dll

**Comment by MAPJe71** [comment]
It should be `$STR_REPLACE$` in the `<language>.xml` i.e. you have a superfluous `T`.

**Comment by fhaut** [comment]
this error happens here too...

I'm check the file `<language>.xml` and not found any ` $STRT_REPLACE$` only `$STR_REPLACE$`

Using 

```
Notepad++ v7.5.6   (32-bit)
Build time : Mar 19 2018 - 00:26:59
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10 (64-bit)
Plugins : CodeAlignmentNpp.dll ComparePlugin.dll DSpellCheck.dll mimeTools.dll NppConverter.dll NppExport.dll NppSnippets.dll PluginManager.dll XMLTools.dll 

```

**Comment by MAPJe71** [comment]
There's a superfluous T [here](https://github.com/notepad-plus-plus/notepad-plus-plus/blob/01cfe5d083d096a71e5a86b3f24ba125770fb18a/PowerEditor/src/NppIO.cpp#L399).
