### ISSUE TITLE
Loosing temporary notes after crashes

### ISSUE THREAD

**Issue by mlatushko** [notepad-plus-plus/notepad-plus-plus#4357]
### Description of the Issue
Some unexpected crashes because of some reason (like: too large file is being processed with "string operations" option or with regexp). Sometimes it causes almost critical errors and even less the loss of a temporary file.

Two times I've lost files with portable version of a program during update. Just sudden error - and temporary savings gone.

One last time (Notepad++ about 7.4.0 installer version) I've lost physically saved file and its backup-version (.bak) during the saving operation.
Just:
   - Save - Crash - Open again - (file is empty, zero bytes, no traces, no backup).

### Steps to Reproduce the Issue

1. More often it happens by accident with portable version of a program (about once a year).

Program may crash during the "Line|blank operations" with the large file. Regular expressions do the same more safely.
This process ("Line|blank operations") can be frozen and realized only partially for the file. And sometimes it ends with a crash.

### Expected Behavior

Saved file.

### Actual Behavior

Lost file.

### Debug Information

It happened with not powerful netbook (Intel Atom processor), with notebook (Intel i7), with normal PC (Intel i5 | Quad Core). There were enabled option "remember current session for next launch" (all these cases).

**Comment by MetaChuh** [comment]
please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins if you update from version 7.5.9 or below.
if your issue still persists, and it is still of relevance, please feel free to file a new issue as easy to understand and reproducible as possible.

thank you for your help and best regards.
