### ISSUE TITLE
Open With not working

### ISSUE THREAD

**Issue by Cristiian** [notepad-plus-plus/notepad-plus-plus#4359]
### Description of the Issue
Notepad++ cannot be selected in open with window, I believe the issue started when upgraded to x64 version of notepad++ 

### Steps to Reproduce the Issue

1.  rigth click in text file
2.  open with
3.  choose default program
4.  navigate to program files and choose notepad++ exe
5. window closes and does not select notepad++

### Expected Behavior
 choose notepad++ as default text editor

### Actual Behavior
 the selection window does not select notepad++

### Debug Information

![imagen](https://user-images.githubusercontent.com/5752018/38218071-2f26fc74-3696-11e8-9614-a862f7b3e4e2.png)
![imagen](https://user-images.githubusercontent.com/5752018/38218112-53e81fb6-3696-11e8-8aac-dce12871d8e7.png)

**Comment by direc85** [comment]
This is not a bug, but a "feature" of Windows. Because the binary is in a different folder, and/or the installed application is different (it counts as different to Windows), so you have to browse to it once. Then it should appear on the list.

PS I have added Notepad++ to my Send To menu, and I love it :)

**Comment by glhez** [comment]
I have the same problem on Windows: could you explain the "feature" ? Because the folder name is Notepad++ and the exe notepad++.exe.

However, if I create a symlink (as admin), it works:

```
   C:\Program Files\Notepad++> mklink notepadplusplus.exe notepad++.exe
```

I'm more for a "windows feature" about the `++`  which might not be liked by Windows at all.

**Comment by donho** [comment]
It's rather a system issue than Notepad++'s one.
