### ISSUE TITLE
NPP hangs when Full Screen and RMB is clicked

### ISSUE THREAD

**Issue by faulknermano** [notepad-plus-plus/notepad-plus-plus#4362]
### Description of the Issue
When in Full Screen mode (F11), click on right mouse button will make N++ unresponsive.

### Steps to Reproduce the Issue

1. Press F11 to go to Full Screen mode
2. Right click on any text.

### Expected Behavior
Context menu should go up, N++ shouldn't hang.

### Actual Behavior

N++ hangs for a long time (couple of minutes) then comes back on again.

### Debug Information

```
Notepad++ v7.5.6   (32-bit)
Build time : Mar 19 2018 - 00:26:59
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : ON
Local Conf mode : OFF
OS : Windows 7 (64-bit)
Plugins : ComparePlugin.dll DSpellCheck.dll FileSwitcher.dll IndentByFold.dll jN.dll JSMinNPP.dll LanguageHelp.dll LocationNavigate.dll MarkdownViewerPlusPlus.dll mimeTools.dll NppBookmarkManager.dll NppConverter.dll NppExec.dll NppExport.dll NppFTP.dll NPPJSONViewer-win32.dll NppTextFX.dll OpenSelection.dll PluginManager.dll SessionMgr.dll SnippetPlus.dll SourceCookifier.dll TagsJump.dll TagsView.dll 
```

Processor is constantly at 13% when the hang happens. N++ comes back in about 2-3 minutes.

**Comment by dail8859** [comment]
You have quite a few plugins installed so it's likely it could be one of those and not Notepad++. Try disabling them.

**Comment by faulknermano** [comment]
@dail8859 thank you very much for your suggestion. I've indeed tracked down the problem to the plugin **Open Selection**.
