### ISSUE TITLE
2018 and Arabic text not supported yet.

### ISSUE THREAD

**Issue by SomeoneCares11** [notepad-plus-plus/notepad-plus-plus#4365]
Any update on this issue?
when i select any arabic word, the highlight is wrong, i was getting this issues since i knew notepad++, years ago.

i was waiting for an update to solve it.

arabic text to try : 
السلام عليكم ورحمة الله وبركاتة

![2018](https://i.imgur.com/nH8AGcf.png)

**Comment by SomeoneCares11** [comment]
@xv yes but who write code in thats mode? i want to write Arabic text inside programming languages.
like the normal notepad! xD

**Comment by Abady321x123** [comment]
I think you can just switch to an IDE like (vscode, atom) and don't waste your time trying to program in a notepad..

**Comment by KrasnayaPloshchad** [comment]
See: https://github.com/notepad-plus-plus/notepad-plus-plus/issues/2749

**Comment by zufuliu** [comment]
RTL is only available since Scintilla 4.1.0, when Direct2D is enabled and DirectWrite is used. See also https://github.com/XhmikosR/notepad2-mod/issues/217.

see https://github.com/notepad-plus-plus/notepad-plus-plus/tree/master/scintilla, Notepad++ current used version is 3.5.6?

**Comment by Dramex** [comment]
@zufuliu I'm not talking to the rtl here, i'm talking to the selection of the text.
i can easily switch to rtl, but it hard to read codes in the RTL mode,
we want to fix the known issue of the selection

**Comment by zufuliu** [comment]
@Dramex so what's the expected result? The selection went to wrong direction when move cursor?

![bidi-sel](https://user-images.githubusercontent.com/2289926/43938164-9f211b22-9c94-11e8-885a-acc34252256a.PNG)

On line 2, when press <kbd>Home</kbd> cursor goes to line end; when press <kbd>End</kbd> it goes to line start (near the line number).
Is **highlight is wrong** means selection is wrong (e.g. because cursor move to the reversed direction when move cursor)?

**Comment by zufuliu** [comment]
What about using <kbd>Shift</kbd> + Left or Right arrow to select text? Is using this method correctly select text? Following is what I tested:

<kbd>Shift</kbd> + Left Arrow (←): selection goes to line  end.
<kbd>Shift</kbd> + Right Arrow (→): selection goes to line  start (near line number).

**Comment by zufuliu** [comment]
@Dramex delete the "first" word in line 2 (under https) works fine, screenshort made by Notepad++ 7.5.8 (enable RTL var: View -> Text Direction RTL) and [Notepad2](https://github.com/zufuliu/notepad2) build from latest master (enable RTL var: Settings -> Rendering Technology -> Direct2D; Settings -> Bidirectional -> Right to Left).
What is the "first" word? "تة" or "ال"?

![bidi-first](https://user-images.githubusercontent.com/2289926/43965612-4b842d0c-9cf2-11e8-948f-70651bc75adc.png)

The screenshot of Notepad2 matches Windows vanilla Notepad.

**Comment by zufuliu** [comment]
RTL for follwing in Firefox, Notepad++ and [Notepad2](https://github.com/zufuliu/notepad2):

```html
<html>
<head>
<meta charset="utf-8">
<title>RTL</title>
</head>
<body>
https://github.com/notepad-plus-plus/notepad-plus-plus/issues/4365
<p>السلام عليكم ورحمة الله وبركاتة</p>
</body>
</html>
```

![bidi-html](https://user-images.githubusercontent.com/2289926/43967261-95ce28c8-9cf6-11e8-98f5-a308d896b12a.png)

Screenshot of change to `<p dir="rtl">السلام عليكم ورحمة الله وبركاتة</p>`:
![bidi-rtl-html](https://user-images.githubusercontent.com/2289926/43967523-24318f92-9cf7-11e8-8f44-89422e5188ec.png)

The screenshot of Notepad++ really surprised.

**Comment by Dramex** [comment]
@zufuliu are we still talking about highlight and selection of the arabic text ?
see in vanila notepad 
![selection](https://i.imgur.com/me1YZnj.png)
when i deleted the selected word : 
![notepad](https://i.imgur.com/RoZgYmz.png)

As you see vanilla notepad better than both notepad++ and notepad2, 
i don't have this issue with any writer/IDE but these two programs.

**Comment by zufuliu** [comment]
@Dramex thank you for the screenshot, now I understand it's a bug of Scintilla, and has nothing with bidirectional.

I created a ticket at https://sourceforge.net/p/scintilla/bugs/2032/, please check it to see if there are something I not (correctly) described.

**Comment by Dramex** [comment]
@zufuliu yeah that's right, thank you for your time regarding this issue.

**Comment by zufuliu** [comment]
Hi Dramex, what's your test result for https://sourceforge.net/p/scintilla/bugs/2032/ using https://www.scintilla.org/wscite410.zip
after enable D2D and RTL/LTR using follwing configuration in SciTEGlobal.properties:
L2R:
```
buffered.draw=0
#phases.draw=2
if PLAT_WIN
	technology=1
	bidirectional=1
#font.quality=3
```

or RTL:
```
buffered.draw=0
#phases.draw=2
if PLAT_WIN
	technology=1
	bidirectional=2
#font.quality=3
```

technology can be set to 1, 2 and 3.
SciTEGlobal.properties can be opened using external tools or using SciTE's menu Options -> Open Global Options File. After edit this file, SciTE need restart to take effect (https://sourceforge.net/p/scintilla/feature-requests/1228/).

**Comment by mnumanuyar** [comment]
Hello 
I wanted to say this still is a problem,
I couldn't test on scintilla because when I copy paste arabic, chars appears as '?'. and I am not familiar with scintilla

**Comment by donho** [comment]
It's a Scintilla limitation.
