### ISSUE TITLE
Scrollbar markers have disappeared some time ago

### ISSUE THREAD

**Issue by KOLANICH** [notepad-plus-plus/notepad-plus-plus#4366]
### Description of the Issue
Some time ago scrollbar markers have disappered on the PC I work on (Win XP). On Windows 7 everything is OK. But I remember that the last time the updates were installed was long before they have gone, so it was not updates. It's also not bit rot - windows mechanisms of checking integrity of system components should be triggered in that case. Is some kind of registry key involved?

### Steps to Reproduce the Issue
1.  create text with repeating tokens
2. double-click one of th

### Expected Behavior
There must havs appeared the markers on scrollbars indicating the positions of the same tokens

### Actual Behavior
They have not.

### Debug Information
It's not a version issue: I have tried different versions including the ones I remember this have been working.

![npp1](https://user-images.githubusercontent.com/240344/38295856-0cab7cca-37df-11e8-85b7-a59c420ecbb4.png)

**Comment by dail8859** [comment]
I don't ever recall this being natively supported by Notepad++. Can you provide a screenshot where it is working and post your debug info?

**Comment by KOLANICH** [comment]
@dail8859 thank you for the hint. It seems it is really implemented via [a plugin](https://github.com/sieukrem/jn-npp-plugin/blob/master/deploy/%5BNotepad%2B%2B%20Directory%5D/plugins/jN/includes/SmartHighlighter.js)! I'll try to look into it tommorow.
