### ISSUE TITLE
When trying to find a file, it opens 50 or more files

### ISSUE THREAD

**Issue by madmonarchs** [notepad-plus-plus/notepad-plus-plus#4367]
### Description of the Issue
When I try to open one file in the file open dialog box, I usually type something like &#42;bos&#42;.htm and then a list appears with files matching this & I can choose which file I need. Since the recent update, however, this results in OPENING ALL FILES THAT MATCH THE &#42; (*), resulting in opening over 50 files.

### Steps to Reproduce the Issue

1.  File Menu, choose "open"
2.  In dialog box file name type   &#42;*a*&#42;.htm
3.  Press "Open"

### Expected Behavior

That the dialog box would show me a list of files that match &#42;a&#42;.htm, so I can choose which file I need. For example: I want to open a_new.htm , but not a_old.htm or ape.htm or hare.htm.

### Actual Behavior

It opened all files matching &#42;a&#42;.htm, so all .htm files with an  a  in the name, which where over 50 files.

**Comment by madmonarchs** [comment]
All the stars have disappeared in describing the issue.

**Comment by cslemmen** [comment]
Happening here too, Notepad++ 32-bit for Windows ver. 7.5.6. 

You can get this behavior back again (why this is now the default is odd):

Settings > Preferences... > Default Directory > [x] Use new style dialog...

Checked the box and now when I enter EG *.xml I see a list of only XML files. Yay!
