### ISSUE TITLE
ShellExecute failed error when using "Edit with Notepad++" R-click context menu option

### ISSUE THREAD

**Issue by chaosblad3** [notepad-plus-plus/notepad-plus-plus#4368]
### Description of the Issue
I wanted Notepad++ to always "run as administrator", so I found the .exe and checked that option on the compatibility tab, but now whenever I try to open a file with the right-click > Edit with Notepad++ option I get the error message "Notepad++ Extension: Error", "ShellExecute Failed (2): Is this command correct?" with the path to the Notepad++ exe on the next line followed by the path to the file I was trying to open...

### Steps to Reproduce the Issue

1. Check the "Run this program as an administrator" option in the exe properties menu
2. try to open any file using the "Edit with Notepad++" option in the windows right-click context menu.

### Expected Behavior

The file opens, with notepad++ in administrator mode

### Actual Behavior

I get the following and the program does not open.
![screenshot of error](https://i.imgur.com/liNRA41.png)

### Debug Information

Notepad++ v7.5.6   (32-bit)
Build time : Mar 19 2018 - 00:26:59
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : ON
Local Conf mode : OFF
OS : Windows 10 (64-bit)
Plugins : DSpellCheck.dll mimeTools.dll NppConverter.dll NppExport.dll PluginManager.dll

**Comment by direc85** [comment]
You are running a 32-bit Notepad++ on 64-bit operating system. Does installing 64-bit version make that possible?

I use only Send To menu (you have to add it manually) and a quick test result was positive: I ticked notepad++.exe to be run as administrator (current user only) and tried to edit a file. I got a UAC prompt, and Notepad++ title bar ends with [Administrator].

**Comment by chaosblad3** [comment]
I didn't realize I had installed the 32bit version, but regardless installing the 64bit version did not fix the issue.

I appreciate that your "Send To" method might work fine for you, but like you said that requires adding manually whereas the "Edit with NotePad++" function is there by default and that's the method that I made this report about, suggesting an alternate method is certainly appreciated but it doesn't change the fact that the other method is still broken.

**Comment by go361** [comment]
**Perhaps you can solve your problem using the method in the Youtube Video.**
[HOW TO FIX ShellExecute failed 2 / EXTENTION ERROR in notepad++ ](https://www.youtube.com/watch?v=hYoBRTzFINo)
I have solved it on my computer
- Notepad++ v7.5.6 (64-bit)
- Path : C:\Program Files\Notepad++\notepad++.exe
- OS : Windows 10 (64-bit)

**Comment by direc85** [comment]
@go361 That result in Notepad++ being run not as administrator, so it is the opposite of the goal here.

I created a workaround using registry modifications and a VBScript file to actually trigger the UAC prompt. I get a "native" user experience with this one, but nevetrheless it's still a workaround.

I have a 64-bit Notepad++ installed in a 64-bit Windows, so the paths may need adjustment. The .vbs file must be placed in the Notepad++ installation directory, and for me at least it survives the update process. You might want to remove and re-install Notepad++ without shell extension ticked to avoid duplication in the shell context menu.

Please review the .reg and .vbs files before using them. I'm not responsible if you lose your data.

[notepad-runas.zip](https://github.com/notepad-plus-plus/notepad-plus-plus/files/1976509/notepad-runas.zip)

**Comment by Drauku** [comment]
The solution was posted over at SuperUser here: https://superuser.com/a/1269546

Save the below snippets as .reg files and execute them. The first two add context menu entries, the third removes the original (non-working with admin priv) context menu entry.

The first is for the Admin menu item only:

```
Windows Registry Editor Version 5.00

[HKEY_CLASSES_ROOT\*\shell\OpenWithNotepad]
@="Edit with &N++ [Admin]"
"icon"="C:\\Program Files (x86)\\Notepad++\\Notepad++.exe"

[HKEY_CLASSES_ROOT\*\shell\OpenWithNotepad\Command]
@="\"C:\\Program Files (x86)\\Notepad++\\Notepad++.exe\" \"%1\""
[HKEY_LOCAL_MACHINE\SOFTWARE\Classes\CLSID\{B298D29A-A6ED-11DE-BA8C-A68E55D89593}\Settings]
"ShowIcon"=dword:00000000
```

The second is for both items on the menu:

```
Windows Registry Editor Version 5.00

[HKEY_CLASSES_ROOT\*\shell\OpenWithNotepad]
@="Edit with &N++ [Admin]"
"icon"="C:\\Program Files (x86)\\Notepad++\\Notepad++.exe"

[HKEY_CLASSES_ROOT\*\shell\OpenWithNotepad\Command]
@="\"C:\\Program Files (x86)\\Notepad++\\Notepad++.exe\" \"%1\""
[HKEY_LOCAL_MACHINE\SOFTWARE\Classes\CLSID\{B298D29A-A6ED-11DE-BA8C-A68E55D89593}\Settings]
"ShowIcon"=dword:00000001
```

The third is to remove the Admin item entirely:

```
Windows Registry Editor Version 5.00

[HKEY_CLASSES_ROOT\*\shell\OpenWithNotepad]
"icon"=-

[HKEY_CLASSES_ROOT\*\shell\OpenWithNotepad\Command]
@=""

[-HKEY_CLASSES_ROOT\*\shell\OpenWithNotepad\Command]

[-HKEY_CLASSES_ROOT\*\shell\OpenWithNotepad]

[HKEY_LOCAL_MACHINE\SOFTWARE\Classes\CLSID\{B298D29A-A6ED-11DE-BA8C-A68E55D89593}\Settings]
"ShowIcon"=dword:00000001
```

**Comment by Drauku** [comment]
> Thanks @Drauku, that worked for me. Anyone know how to get rid of the original "Edit with Notepad++" entry?

You should be able to use the third code-snippet I listed previously to do that.

**Comment by darkdex52** [comment]
This is still an open issue in Dec 2019 btw. Following the steps listed here fixed my problem, but being able to run Notepad++ with admin priviledges from context menu should be a default from the install, not a regedit tweak.

**Comment by sohosynergy** [comment]
The solution @collinsauve provided was the simplest and worked like a charm for Notepad++ v7.8.4 64 bit on Windows 10 64bit.

> I was able to fix this for myself by removing the `Computer\HKEY_CLASSES_ROOT\*\shellex\ContextMenuHandlers\ANotepad++64` key.

**Comment by TroniPM** [comment]
> I was able to fix this for myself by removing the `Computer\HKEY_CLASSES_ROOT\*\shellex\ContextMenuHandlers\ANotepad++64` key.

this broke my installation. :@

**Comment by avanlex** [comment]
@go361, thanks
> **Perhaps you can solve your problem using the method in the Youtube Video.**
> [HOW TO FIX ShellExecute failed 2 / EXTENTION ERROR in notepad++](https://www.youtube.com/watch?v=hYoBRTzFINo)
No need to watch the video
Steps:
             1. First Go To Desktop (Or To Start Menu In My Case)
             2. Then Find Notepad++ Icon.
             3. Then Click Right Mouse Button.
             4. Now Click On Properties.
             5. Now Click Compatibility.
             6. Now Disable/Untick The  "**Run This Program As An Administrator**" Option .
             7. Now Click "**Apply**" And Then Click "**Ok**".
