### ISSUE TITLE
Ghost typing needs too much CPU cycles, maybe move -qSpeed3 to -qSpeed10 and add more speeds?

### ISSUE THREAD

**Issue by GitMensch** [notepad-plus-plus/notepad-plus-plus#4375]
### Description of the Issue
Ghost typing on `-qSpeed3` takes more than a complete core (`-qSpeed2`).

### Steps to Reproduce the Issue
1. Update to latest NPP
2. Logon to a fresh created profile (only standard settings/plugins)
3. call `notepad++.exe -qfconfig.model.xml -qSpeed3`

### Expected Behavior
* Ghost typing of the file in a speed one can still follow (even when reading may be not possible that fast).
* CPU not heavily used

### Actual Behavior
* one complete CPU core at 100%
* Ghost typing on `-qSpeed3` *may* be too fast (because of the CPU consumption + limit it gets much slower when a language hint `-lxml` is given).

### Debug Information
Notepad++ v7.5.6   (32-bit)
Build time : Mar 19 2018 - 00:26:59
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10 (64-bit)
Plugins : ComparePlugin.dll DSpellCheck.dll LocationNavigate.dll mimeTools.dll NppConverter.dll NppExport.dll NppSaveAsAdmin.dll PluginManager.dll SourceCookifier.dll XMLTools.dll

**Comment by MetaChuh** [comment]
@GitMensch 

as this is mainly a gag feature, and there's a massive lack of time, there will currently be no update to this feature.

best regards and thank you for your support.

**Comment by GitMensch** [comment]
I totally agree with you here.
