### ISSUE TITLE
URL highlighting underlines the wrong line

### ISSUE THREAD

**Issue by stalkermar** [notepad-plus-plus/notepad-plus-plus#4378]
### Description of the Issue
URL highlighting underlines the wrong line

### Steps to Reproduce the Issue
1. Press CTRL+N
2. Paste the following content:
> Some text
> http://localhost:1234/AnyLink.html
3. Hover your mouse over the link until it becomes blue and underlined.
4. Don't move the mouse cursor, leave it on the url. 
5. Press up arrow on your keyboard. This will move your cursor to the first line.
6. Type "some more text"

### Expected Behavior
![screenshot](https://user-images.githubusercontent.com/7525008/38409792-705952bc-398b-11e8-8c54-d937abac771d.png)

### Actual Behavior
![screenshot](https://user-images.githubusercontent.com/7525008/38409757-483c3e70-398b-11e8-92f1-d67ece12eae6.png)

**Comment by Uhf7** [comment]
It works correctly in 7.8.7.

I could verify it in 7.8.6, but it is gone in 7.8.7.
