### ISSUE TITLE
"Folder as Workspace" newly created folder doesn't show up in NPP

### ISSUE THREAD

**Issue by tarekahf** [notepad-plus-plus/notepad-plus-plus#4379]
### Description of the Issue

After you use the feature open folder as workspace in NPP, then when you create a new folder from Windows Explorer, the new folder doesn't show up in the tree view under NPP "Folder as Workspace".

### Steps to Reproduce the Issue

1. View --> Folder as Workspace
2. Drag and drop a folder to the workspace panel
3. Use File Explorer to create a new folder under the main folder of the workspace created in NPP
4. Switch to NPP, and the new folder is not visible 

### Expected Behavior

The new folder must show
### Actual Behavior

The new folder didn't show
### Debug Information

Notepad++ v7.5.6   (32-bit)
Build time : Mar 19 2018 - 00:26:59
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 7 (64-bit)
Plugins : ComparePlugin.dll CustomizeToolbar.dll DSpellCheck.dll JSLintNpp.dll JsMapParser.NppPlugin.dll JSMinNPP.dll mimeTools.dll NppConverter.dll NppExport.dll NppFTP.dll NPPJSONViewer-win32.dll NppTextFX.dll PluginManager.dll SourceCookifier.dll Tidy2.dll XMLTools.dll

**Comment by tarekahf** [comment]
OK, great! I tried the same steps, and still the same issue. I think because the fix wasn't deployed yet. How I can verify if the fix is applied on my PC?
Tarek

**Comment by dpaterson** [comment]
If I do a "Save As" of a file I opened in the workspace folder and save it to a new name in the same folder I do not see the new file, this bug should be reopened I feel.

**Comment by sasumner** [comment]
@dpaterson said:

>I do not see the new file

I see it if I try it.  N++ 7.7.1.

**Comment by caseydalpal** [comment]
regression does not work when the path of the folder is  a unc path like \\\\foobar.local\notepad\files
