### ISSUE TITLE
I wonder is there a way to better user defined languages

### ISSUE THREAD

**Issue by anotherglitchinthematrix** [notepad-plus-plus/notepad-plus-plus#438]
As you know we can define our languages for highlighting and we should stylize syntax colors with bare hand, this isn't the problem but syntax colors is not compatible with other themes, is there a better way to define our language with the selected theme's colors? I know each language in the Npp has different syntax and must be seperated but when I compare the languages I saw common colors. Can we think to define a color palet in the style configurator and after maybe optional user select appers for each keyword in language like " Select defined color from Main Theme ", I don't mean we should change the specific color feature, we should keep it for specific change.

Edit:
And I think if that will be happen; User Defined Languages must be like plugins, easy accessible and applicable in the plugin manager.

 I am sorry if I made a mistake, my english isn't good. Thank you.

**Comment by jamesford42** [comment]
The ability to share languages as if they were plugins in the plugin manager would be GREAT.

**Comment by donho** [comment]
Unfortunately there's no other convenient way in UDL to match other themes.
