### ISSUE TITLE
Unable to save to network drive

### ISSUE THREAD

**Issue by rmutchler** [notepad-plus-plus/notepad-plus-plus#4380]
### Description of the Issue
When trying to save to a network drive in N++, my network drives do not show up.  This only occurs when running as an Administrator.

### Steps to Reproduce the Issue
1. File > Save As...
2. Find network drive, but it is missing
3. 

### Expected Behavior
Network drive available for saving

### Actual Behavior
No network drives show

### Debug Information
Notepad++ v7.5.6   (64-bit)
Build time : Mar 19 2018 - 00:23:17
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : ON
Local Conf mode : OFF
OS : Windows 10 (64-bit)
Plugins : DSpellCheck.dll mimeTools.dll NppConverter.dll

**Comment by donho** [comment]
Does this issue persist in the latest (v8.1.9.3) version?

**Comment by donho** [comment]
It's not Notepad++ issue. Please see:
https://superuser.com/questions/690287/command-prompt-in-administrator-mode-doesnt-see-mapped-drives
