### ISSUE TITLE
FunctionList feature not working

### ISSUE THREAD

**Issue by KptainBiwouak** [notepad-plus-plus/notepad-plus-plus#4384]
Hi,

I am using Notepad++ for many years and would like to thank you for all your work keeping this tool up to date.

BUT, I have to to say that:
FunctionList not working: no function listed for Perl or Python scripts

I used regularly Notepad++ and regularly FunctionList feature is not working.

Could you explain what has to be done just after Notepad++ to guarantee that these basic features will be functional?

I am using ".pl", ".pm" or ".py" files. I do not understand why FunctionList is not working

### Debug Information
Notepad 7.5.6 (64bits) on Windows 7 Pro

Thanks for your help,

**Comment by sasumner** [comment]
Works for me:

![image](https://user-images.githubusercontent.com/30118311/38496099-3ed55808-3bca-11e8-94f2-834314559067.png)

**Comment by KptainBiwouak** [comment]
The only difference I see is the version of Notepad++ in my case: 64bits
instead of 32bits.

Waiting for your feedback, I will check from my side if problem persists
using 32bits release

2018-04-09 13:47 GMT+02:00 sasumner <notifications@github.com>:

**Comment by KptainBiwouak** [comment]
By using 32bits version, Function list works for Python script but not for
Perl Scripts.

Could you help me to explain why?

I have attached functionList.xml files provided with tool:


2018-04-10 10:47 GMT+02:00 Kaptain Biwouak <kaptain.biwouak@gmail.com>:

**Comment by ArkadiuszMichalski** [comment]
@The author Do you still have this problem in the current version of the Notepad++? If no then please close this bug.

**Comment by donho** [comment]
Outdated.

**Comment by KptainBiwouak** [comment]
Issue is fixed with 7.9RC Thanks
