### ISSUE TITLE
Close all tabs without saving

### ISSUE THREAD

**Issue by mlatushko** [notepad-plus-plus/notepad-plus-plus#4385]
### Description of the Issue
New feature:

### Expected Behavior
Option at "Save" window to discard of saving every file.

![2018-04-09_155804](https://user-images.githubusercontent.com/23335312/38499071-24a24c94-3c0f-11e8-88e8-b5487722e69a.jpg)

**Comment by sasumner** [comment]
This is a desired feature.  A possible workaround might be to hold down the key that represents "No"...not sure what that is in your language.

**Comment by badearobert** [comment]
Cannot be done that simple, as the messagebox is part of MFC and a custom popup it's not that easy to be implemented. Maybe a new option such as "Close all without saving"

**Comment by badearobert** [comment]
Created pull request, added the command "Close all without saving" in both the File menu and in the context (right click on tab) option.

**Comment by kemmis** [comment]
Please add this feature! It's driving all of us heavy notepad++ users crazy! There's even a pull request from almost a year ago! Someone, please review and merge it. Pretty please!

**Comment by sasumner** [comment]
@kemmis, Sure I understand frustration that this isn't released yet, but have you tried my workaround from above? Why would you let it "drive you crazy" ?

**Comment by grvstr** [comment]
Imagine that you have opened 1000+ files and made a change in every single one of them. Then you realized you have to undo your changes so you are trying exit without saving. Notepad would ask you 1000+ times if you want to save the changes. Holding down the key for "N" can be time-consuming.

**Comment by grvstr** [comment]
@sasumner Imagine that you have made a change in 1000+ files and you realized there was a mistake and you have to undo your changes by exiting without saving. You will be prompted 1000+ times, and pressing down the key for "No" can be time-consuming.

**Comment by kemmis** [comment]
Exactly. I use the app all day as a scratch pad and constantly add new
files mostly as temporary use that I don’t want to save. Eventually I end
up with a hundred files/tabs open and it’s time to clean house. I’m not
able to just “close all without saving”. Instead I get the prompt for every
friggin file.

**Comment by donho** [comment]
> BTW, I've always agreed (maybe only in my head) about having a "no to all" option for this

Yes, a "not to all" button is better than " Close all tabs without saving" command IMO.
Here is the binary with implemented feature. Please confirm me it's what you want:
https://notepad-plus-plus.org/temp/npp32.saveYesNoToAll.zip

**Comment by sasumner** [comment]
>a "no to all" button is better than "Close all tabs without saving" command IMO.

Safer, too.  If you have a "Close all no save" menu item, someone will accidentally click on it unintentionally (I am surprised how many "bad" mouse actions I make during the day).

I am happy to have the functionality implemented as "No to all".

However, someone in the future will certainly say "I want to close all modified files without saving in a macro, and I don't want to be prompted".  :)

**Comment by kemmis** [comment]
+1 “no to all” button

**Comment by santusourav** [comment]
Found easy options to close all open notepad++ tabs. Close all tabs without saving
![image](https://user-images.githubusercontent.com/47564095/107135385-79d44800-68fa-11eb-8c2b-b5cb3a9359d2.png)
![image](https://user-images.githubusercontent.com/47564095/107135390-822c8300-68fa-11eb-815c-4493613b88c1.png)

**Comment by mlatushko** [comment]
Thank you!
The main problem is when we may forgetfully close the window with opened tabs (want to get rid of everything quickly), and then it is only possible to make an "emergency crash" through Ctrl+Shift+Esc (or die closing a thousands tabs).

**Comment by sasumner** [comment]
>The main problem is when we may forgetfully close the window with opened tabs (want to get rid of everything quickly), and then it is only possible to make an "emergency crash" through Ctrl+Shift+Esc (or die closing a thousands tabs).

I don't see how this applies, now that we have a `No to all` button.
Can you explain?

**Comment by mlatushko** [comment]
Sorry, I was wrong. I had to write "it was earlier." Everything is fine now, it works. Thanks!
