### ISSUE TITLE
Crash on second paste of large amount of data from clipboard

### ISSUE THREAD

**Issue by iburda** [notepad-plus-plus/notepad-plus-plus#4389]
### Description of the Issue

Notepad++ 64 bit (ver. 7.5.6.0) crashed during attempt to paste large amount of data from clipboard.
The PC has plenty of RAM, so memory was not maxed out. This was the second paste attempt.
The first one succeeded. The data contained over 38 million lines of ASCII text. Each line was about 30 characters long, for the total size a little over 1GB.
### Steps to Reproduce the Issue

1. Copy about 1GB worth of text data into Windows Clipboard using a third party editor or a separate instance of Notepad++.
2. Paste it into new instance on Notepad++.
3. Paste it again.
4. Observe the crash.

### Expected Behavior

Not crash. Ideally it should just succeed copying and pasting of large amounts of data as much
as OS and hardware support. As a second choice an error message and avoid  the crash.
### Actual Behavior

Crash.
### Debug Information

Notepad++ v7.5.6   (64-bit)
Build time : Mar 19 2018 - 00:23:17
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 7 (64-bit)
Plugins : DSpellCheck.dll mimeTools.dll NppConverter.dll 

![crash report screenshot](https://user-images.githubusercontent.com/38256568/38569260-5302d948-3cda-11e8-93b6-72973b70b369.JPG)
![crash screenshot 2](https://user-images.githubusercontent.com/38256568/38569261-5318ae12-3cda-11e8-88c6-8fb9e246ffb4.JPG)
![crash screenshot](https://user-images.githubusercontent.com/38256568/38569262-5336d69e-3cda-11e8-9f2f-4681b33dde92.JPG)
![failed to create dump file](https://user-images.githubusercontent.com/38256568/38569263-534ce506-3cda-11e8-833f-7531777ed9c4.JPG)

**Comment by badearobert** [comment]
Scintilla copy strings like it was developed by java programmers ^^

**Comment by AngryGamer** [comment]
Does it crash without the DSpellCheck plugin?

**Comment by iburda** [comment]
Yes, it crashes without DSpellCheck plugin, although the crash address is different.
![crash without spell check plugin](https://user-images.githubusercontent.com/38256568/38692500-6b9f02a2-3e73-11e8-9db1-65bad19d4d6a.JPG)

**Comment by MetaChuh** [comment]
please update your notepad++ to the latest 64 bit version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins if you update from version 7.5.9 or below.
if your issue still persists, and it is still of relevance, please feel free to file a new issue as easy to understand and reproducible as possible.

thank you for your help and best regards.
