### ISSUE TITLE
Missing keyword in Java syntax highlight

### ISSUE THREAD

**Issue by marcoM32** [notepad-plus-plus/notepad-plus-plus#4390]
### Description of the Issue
On the new release of Java (v10) was added a new keyword in the syntax ("var") for now this keyword is not recognized by Notepad++, is possible add it?

### Steps to Reproduce the Issue
1.  Set Java as language
2.  Write "var"

### Expected Behavior
"var" is correctly recognized as a keyword

### Actual Behavior
"var" is not recognized as a keyword

**Comment by ArkadiuszMichalski** [comment]
https://developer.oracle.com/java/jdk-10-local-variable-type-inference.html
It's strange that no one has added yet :)
