### ISSUE TITLE
menu name problem

### ISSUE THREAD

**Issue by nablas** [notepad-plus-plus/notepad-plus-plus#4393]
### Description of the Issue
A spell mistake in french version of last version of npp

### Steps to Reproduce the Issue

Install application in french, go to menu "paramétres" (french for parameters)

### Expected Behavior
should be paramètres, not paramétres

### Debug Information
When you think that the autor is french ...

**Comment by hibyguy** [comment]
Grammar fixed!

**Comment by donho** [comment]
9210bd37b6254988dce9fb1966e6d25a72332f85

**Comment by hibyguy** [comment]
??
