### ISSUE TITLE
Excluding temporary folder files from Recent list

### ISSUE THREAD

**Issue by direc85** [notepad-plus-plus/notepad-plus-plus#4395]
### Background
I use Notepad++ mostly "just as a notepad" and in conjunction with WinSCP. When connecting WinSCP to a site and editing a remote file, it saves the file to a temporary directory; e.g. C:\Users\username\AppData\Local\Temp\scp00001\path\of\file\filename.ext and opens that file in Notepad++. This all works fine, but as I also tend to use the recent files menu a lot, it gets cluttered with the non-existing temp files, which WinSCP deletes after use.

### Description of the Issue
Files opened from WinSCP (and others?), which are transient files in temp folder, are added to recently opened files list. This results in cluttered and possibly rotated-to-temp-files-only recent files list.

### Steps to Reproduce the Issue
1. Install WinSCP
2. Set Notepad++ as default editor
3. Connect to a site
4. Edit a remote file (this starts Notepad++)
5. Close the file
6. Exit WinSCP

### Expected Behavior
7. In Notepad++, see that the file is not added in recent files list

### Actual Behavior
7. In Notepad++, see the file in File menu in recently opened files
8. Try to open the file again from the said menu
9. Fail, the file doesn't exist anymore (as expected)
10. Note that the recent files list gets cluttered with said temp files

### Debug Information
I believe debug information is not necessary.

### Suggenstions
I see three possible solutions to this:
1. Do not add files opened from %TEMP% or its subfolders to recent files list (possibly add a setting to the functionality in order to add custom folders - this could be handy in many other cases, too)
2. When clicking a non-existent file in recent file list, offer deleting the item from the list (this would apply to any other moved/deleted/renamed file, too, but would require a lot of clicking and wouldn't prevent rotating out files from the end of the list)
3. Offer a cleanup command for the list, that would remove non-existing files from it (least elegant, could be very slow in network mapped drive use cases)

I consider number 1. the best solution.

Thank You!

**Comment by johanponken** [comment]
I also work through a lot of files.
But have no handy common denominator like %TEMP%.
So I definitely want the cleanup command (3.).
There is a cleanup command "Empty Recent Files List", under the menu item "File".
Just below that would be a great place for "Clean Recent Files List".

**Comment by donho** [comment]
"Empty Recent Files List" has been added since longtime ago, so this issue can be closed.
