### ISSUE TITLE
Unable to move untitled / dirty files from one n++ instance to another

### ISSUE THREAD

**Issue by badearobert** [notepad-plus-plus/notepad-plus-plus#4396]
### Description of the Issue
Unable to move untitled / dirty files from one n++ to another, as it requires closing the tab and reopening via a new n++ instance

### Steps to Reproduce the Issue

1.  write something on "new 1"
2.  create "new 2", write something else
3.  drag one of the files into a different window

### Expected Behavior
File to be moved accordingly

### Actual Behavior
Nothing happens, as it has early return on dirty files

**Comment by donho** [comment]
Unfortunately, such limit cannot be removed.
