### ISSUE TITLE
Bug in Search/Replace function

### ISSUE THREAD

**Issue by Turtletronic** [notepad-plus-plus/notepad-plus-plus#4397]
### Description of the Issue

Bug in search and replace function (here: one specific German character)

### Steps to Reproduce the Issue

1. Take any text (preferably German locale, but English text is okay too!)
2. Search for the German Umlaut char "ß" a.k.a. "s-sharp" and replace it with the HTML code `&szlig;`
3.  Every occurence of s-sharp (if present) as well as all plain double 's', as in 'message' are replaced.

### Expected Behavior

The search / search replace should ONLY affect the Umlaut char s-sharp in it's 'ß' form.

### Actual Behavior

The search / search affected the Umlaut char s-sharp (correct) but also affected the non-related occurrence of doube 's' letters, as in words like 'message',

### Debug Information

Notepad++ v7.5.6   (64-bit)
Build time : Mar 19 2018 - 00:23:17
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 7 (64-bit)
Plugins : DSpellCheck.dll mimeTools.dll NppConverter.dll NppExec.dll 

The German s-sharp character 'ß' can - under certain circumstances - be written out as 'ss'; this however does not mean that every ocurrance of a double 's' should result in a s-sharp. That is one matter. The second is that Notepad++ replaces 'ss' completely out of context as I was searching for 'ß', not 'ss'.

**Comment by guy038** [comment]
Hi, **Turtletronic**,

See my reply on **N++ Community**, below :

https://notepad-plus-plus.org/community/topic/16454/how-long-before-bugs-are-even-acknowledged-6-months-counting/2

Best Regards,

guy038

**Comment by sasumner** [comment]
@Turtletronic Given Guy's writeup on the Community, if you agree that Notepad++ is acting acceptably in this regard, please close this issue.

**Comment by dinkumoil** [comment]
@sasumner 

@guy038 only gave a workaround how one can deal with the current buggy behaviour. But this is not a real solution. Currently Notepad++ is **not** acting acceptably and this should be fixed. Unfortunately only german-writing users are affected by this bug, I guess this won't speed up fixing it...

**Comment by sasumner** [comment]
@dinkumoil , you seem adept, and you understand this problem it seems...how about diving in and coming up with a PR that fixes it?  :)

**Comment by dinkumoil** [comment]
@sasumner : I would do it if I were a C++ dev. Unfortunately  more than 25 years ago I've switched from C (my "first love" beside MC68K assembly ;) ) to Pascal and later on to Delphi instead to C++. Nowadays this language is blown up in a disastrous way, I don't want to learn it anymore.

**Comment by sasumner** [comment]
@dinkumoil Well, not to get too far off-topic, but your story sounds a lot like my story. :-)  Except for the Pascal/Delphi part:  I went the C++ Builder route, but in truth never delved too deeply into C++ (stuck to the basics of it that give you the biggest advantages...to avoid the "blown up" part you hint at).  Nowadays I'm more often called upon to do Python and that's OK with me.  I'm sure you would be comfortable working in the Notepad++ source code (IMO it is "very light" C++), but that's all I'll say.

**Comment by MetaChuh** [comment]
@Turtletronic 

scintilla follows the unicode standard for locale independent case folding to do case insensitive searching.
this standard specifies that `ß` matches `ss` when searching/replacing case insensitive.

so your choices are:
* use **case sensitive** when searching/replacing, which will correctly identify any `ß`.
* use **regex** search, as it uses another engine. (boost)
* file an issue at the [**scintilla project bug tracker**](https://sourceforge.net/p/scintilla/bugs/).
* use an editor that is not scintilla based. (none of these: [Software based on Scintilla](https://en.wikipedia.org/wiki/Scintilla_(software)#Software_based_on_Scintilla))

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
(no extra account is needed, just use your github account to sign in)
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)

**Comment by sasumner** [comment]
There was another issue on the same topic recently...too bad this one and that other one weren't cross-linked.

**Comment by MetaChuh** [comment]
referenced to: #1245 #4397 #4496
