### ISSUE TITLE
X button (close) shown that does nothing.

### ISSUE THREAD

**Issue by thebothead** [notepad-plus-plus/notepad-plus-plus#4399]
There is an X button displayed in the tool bar that seems to do nothing.

![x-button](https://user-images.githubusercontent.com/4582556/38638904-ae880f54-3d9d-11e8-889a-68414e46d075.png)
![notepad-version](https://user-images.githubusercontent.com/4582556/38638956-d98dbbb8-3d9d-11e8-851c-6fb82837b4f0.png)

**Comment by Anujg935** [comment]
X button does nothing when the new file you are working on is empty but if there is anything in your file and you click on that X button you will get a prompt to save your existing work or discard it.

**Comment by sasumner** [comment]
@Anujg935 Actually, that's not quite right.  This part: "X button does nothing when the new file you are working on is empty".  Well okay, it's right but maybe for the wrong reason.

If there is only a single tab open and it is an unnamed file (e.g. new 1), the reason the X seems to do nothing is that one tab must ALWAYS be open in Notepad++.  

If you have 2 or more "new _" files open and none of them have been modified, that X will close the one that currently has focus.  You can repeat pressing the X and closing "new _" files until you get down to the last remaining one, which will not close.

Thus the X will close "new _" files that are empty, just not in the case where you only have one tab.

**Comment by SinghRajenM** [comment]
@thebothead Try with below setting and see the magic. 👇 

![image](https://user-images.githubusercontent.com/14791461/38735267-f54346da-3f45-11e8-95ca-4f606d72c32b.png)

@sasumner 
>If there is only a single tab open and it is an unnamed file (e.g. new 1), the reason the X seems to do nothing is that one tab must ALWAYS be open in Notepad++.

It is user's choice what he/she wants to achieve when only one tab is left and he/she keep on pressing X button. Option is provided. 😄

**Comment by sasumner** [comment]
@SinghRajenM Yes good point; I got the feeling that @thebothead didn't want Notepad++ itself to close in the originally described scenario.

**Comment by thebothead** [comment]
Thanks for all the detailed answers!!!  I mostly did not understand what
that button was for, and now I do thanks to all of you, as well as all the
settings for it :)
