### ISSUE TITLE
Highlight in Document Map visible on screen when Notepad++ minimized

### ISSUE THREAD

**Issue by aaaxx** [notepad-plus-plus/notepad-plus-plus#440]
Happens only with "Minimize to system tray" enabled in Preferences.

**Comment by milipili** [comment]
Could you provide a little screenshot ? :)

**Comment by aaaxx** [comment]
Sure.
http://i.imgur.com/nWhSXeu.jpg
http://i.imgur.com/N2rl5Cn.jpg

It stays in the same place and you can't interact with anything under it, but it can be stacked above or below other windows.

**Comment by atiris** [comment]
I have the same problem with Document Map slider which exists separate of Notepad++ window.
You can see it in video here: https://youtu.be/xV3naT_7GFU

**Comment by Aaron216** [comment]
Issue also occours when using multiple virtual workspaces in Windows 10 and Notepad++ is open on another workspace.

**Comment by jubjamie** [comment]
Has any progress been made on this? I've just come across it and, while I know that it's old, it's still an issue!

**Comment by rivermont** [comment]
Can confirm, this is still a problem. I was going to create another issue but it seems this is still open.

**Comment by donho** [comment]
Update your Notepad++ to the latest version (v7.6.6).
If the issue persists, please create a new issue for it.
Thank you.

**Comment by ArmandDelessert** [comment]
This issue is still happening to me with Notepad++ v7.6.6.

**Comment by sasumner** [comment]
@ArmandDelessert I guess then that you are the lucky person that has to follow the directions:  "If the issue persists, please create a new issue for it."

**Comment by ArmandDelessert** [comment]
@sasumner I did it [here a year ago](https://github.com/notepad-plus-plus/notepad-plus-plus/issues/4549). This issue is still opened [here](https://github.com/notepad-plus-plus/notepad-plus-plus/issues/1247), [here](https://github.com/notepad-plus-plus/notepad-plus-plus/issues/1317), [here](https://github.com/notepad-plus-plus/notepad-plus-plus/issues/2763), [here](https://github.com/notepad-plus-plus/notepad-plus-plus/issues/3612) and [here](https://github.com/notepad-plus-plus/notepad-plus-plus/issues/5294). I will avoid creating an umpteenth duplicate.

The same issue is closed here: #2840, #4740
Related issue: #3204

**Comment by sasumner** [comment]
@ArmandDelessert Oh...well I guess they just haven't gotten to closure of all those umpteenth duplicates yet--I presume they will, with the same "If the issue persists, please create a new issue for it." boilerplate as above.

**Comment by MetaChuh** [comment]
@ArmandDelessert 
we apologise for the cleanup, which causes some issues to be closed, even if they are still valid, like yours last year as duplicate merger, and this one now.

i have verified and reproduced this and your issue at #5294 
we will also verify and merge all identical and "related same cause" duplicates soon, closing all other related issues but one, to get a better focus at a single issue, if possible.

note: as notepad++ is a fairly small team of volunteers, notepad++ also relies very much on the help of you and other members of the notepad++ community, e.g. by re-testing issues on newer versions, if an original issue is quite old and still unhandled.

@sasumner 
a big 👍 and ❤️ for where we can't do that.

best regards to all, and thank you for your support, patience and understanding.

ps: our hope is, that at least a few users have noticed, that notepad++ development and issue solving&prevention has gotten a bit more structured, more reliable and quicker.
we will try to continue improving as much as we can, but it will take time.

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
(no extra account is needed, just use your github account to sign in)
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)
