### ISSUE TITLE
Spanish translation: Search dialog items do not fit (translated texts too long)

### ISSUE THREAD

**Issue by borjafg** [notepad-plus-plus/notepad-plus-plus#4401]
### Description of the Issue
There is an item in the search dialog that is not visible.

### Steps to Reproduce the Issue
1.  Open search dialog

### More information
See this screenshot.

![captura](https://user-images.githubusercontent.com/6740268/38671729-6ecce4a2-3e4c-11e8-941d-fada6302dad7.png)

**Comment by sasumner** [comment]
Sure looks visible to me, if you mean what's in the yellow highlight.

**Comment by borjafg** [comment]
Yes, I mean what's in the yellow highlight.

The full text is not visible.

**Comment by sasumner** [comment]
I don't know that there are any guarantees that *translated* (i.e., non-English) text will fit.  This is a tough problem to solve (limited space on the GUI and translations often differ greatly in length).  If you have a suggestion for shorter but still meaningful text for this field that will fit, by all means please indicate what that is--it may be adopted for future releases.

**Comment by borjafg** [comment]
A provisional solution can be to add a toolTip.

A better solution is to modify the size of the panel to adapt it to the content. In that case, you would have to put a maximum size so that it doesn't collide with other elements.

**Comment by sasumner** [comment]
I wouldn't be hopeful about a such a solution.  The unwritten design rule seems to be "optimize the sizes for English; other languages are shortened if needed to fit".  Just my observation.

**Comment by MetaChuh** [comment]
@borjafg 

unfortunately the translators for spanish.xml have missed that the translation of `. matches newline` does not fit into the field.

note: i have renamed your issue from: `Search dialog -- Item not visible`
to: `Spanish translation: Search dialog items do not fit (translated texts too long)`
so that spanish translating contributors can find this issue at all.

best regards.
