### ISSUE TITLE
Notepad++ loses all open files on Windows shutdown

### ISSUE THREAD

**Issue by TLN2** [notepad-plus-plus/notepad-plus-plus#4402]
Normally Notepad++ remembers all open files when it's closed. It even remembers _unsaved_ documents and restores them the next time you start it after it was killed or crashed. This is a very useful feature that I rely on a lot because I have several configuration files I have to access regularly.
However, when you get asked whether to save an unsaved particular file upon Windows shutdown and answer "No", Notepad++ in the latest version usually forgets all open files.

### Steps to Reproduce the Issue on my system:
1. Open a couple of existing files in Notepad++.
2. Close Notepad++.
3. Open it again.
4. All files are remembered. -> Correct behavior, the feature works.
5. With the couple of files still open, click "New" and type something. Do not save this dummy document.
6. Choose "Log off" or "Shutdown" or "Restart" in Windows. (Windows 7 in this case)
7. Wait until Windows complains about Notepad++ preventing the log off/shutdown/restart operation.
8. Click "Cancel" on that Windows dialog to be able to access Notepad++ to fix the problem.
9. Notepad++ has a message box open where it asks if the file "new 1" should be saved.
10. Click "No".
11. Notepad++ is still open, but all previously open files are suddenly closed, Notepad++ is as if freshly started, that is with an empty document named "new 1". Everything else is closed, no existing files are open anymore.
12. Finish the log off/shutdown/restart operation in Windows.
13. Log on/restart again and start Notepad++.
14. Notepad++ starts with the blank document, all previously open files are forgotten. If you want them open again, you have to look for them manually again. -> Bug

### Expected Behavior
Expected behavior is one of the following three:
1. When I press "No" in step 10. above, Notepad++ closes without saving the document it asked about.
2. When I press "No" in step 10. above, Notepad++ closes the document but not itself so that on the next shutdown attempt in Windows Notepad++ can close without asking anything back.
3. When I press "No" in step 10. above, Notepad++ leaves the document open but remembers this choice for the next attempt to log off/shutdown/restart so that it doesn't block this operation again.

In all three cases the expected behavior is that Notepad++ opens all previously open documents again when it is started the next time. The only exception should be documents that I explicitly closed myself.

### Actual Behavior
See above: Notepad++ does not just take my choice "No" for not saving the one particular unsaved document but also closes everything else in the course and it does not get opened again when Notepad++ is started the next time.

### Debug Information
Notepad++ v7.5.6   (32-bit)
Build time : Mar 19 2018 - 00:26:59
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 7 (64-bit)
Plugins : DSpellCheck.dll mimeTools.dll NppConverter.dll NppExport.dll NppFTP.dll PluginManager.dll

**Comment by Dunkhan** [comment]
Thanks for reporting this, this has been really bugging me and actually cost me work in the past.
It seems to me that the main issue here is that Notepad++ behaves differently when the program is asked to close by windows shutdown than by other sources. If I follow the steps above, replacing step 6 with simply "Close notpad++" the issue is not reproduced.
Another way to write the expected behaviour would be : the application should behave in the same way when windows OS shutdown calls it to close, as when called to close by any other source

**Comment by squelart** [comment]
I just encountered this issue.

Interestingly, I later force-closed Notepad++ ("End task" in Windows' Task Manager), and when reopening the previously-opened files reappeared! So the information is still there somewhere...

**Comment by MetaChuh** [comment]
please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins if you update from version 7.5.9 or below.
if your issue still persists, and it is still of relevance, please feel free to file a new issue as easy to understand and reproducible as possible.

thank you for your help and best regards.
