### ISSUE TITLE
How to add a shortcut for a language?

### ISSUE THREAD

**Issue by xziruss** [notepad-plus-plus/notepad-plus-plus#4407]
![default](https://user-images.githubusercontent.com/38354859/38740150-78ffc392-3f3f-11e8-9b2d-d0ebb667ca0a.jpg)

**Comment by sasumner** [comment]
I like the picture but I am unsure what it is saying.  The title of the issue perhaps gives a better hint.  You'd like to see each individual language (e.g. javascript, python, c, the list goes on...) as individually assignable shortcut keys?

**Comment by xziruss** [comment]
> You'd like to see each individual language (e.g. javascript, python, c, the list goes on...) as individually assignable shortcut keys?
YES!
I usually use "J" - JavaScript оr Java.

**Comment by dinkumoil** [comment]
As far as I know it is not possible to assign keyboard shortcuts directly to the entries of the `Language` menu. But you can emulate it.

1. Install the NppExec plugin.
2. Now you can write oneliner scripts to send a Windows message to Notepad++ to simulate a mouse click on a certain menu entry. To do this go to menu `Plugins - NppExec - Execute...`
3. After that you can assign these scripts to entries in the `Macro` menu. To do this go to menu `Plugins - NppExec - Advanced options...`
4. Finally you can assign keyboard shortcuts to these entries via the shorcut mapper as usual.

A NppExec script to simulate a click to the `Java` menu entry would be

`npp_sendmsg WM_COMMAND IDM_LANG_JAVA`

You can find the `IDM_LANG_XXX` constants for all languages in a file that will be copied to your machine when installing the NppExec plugin. This file is stored under

`<Notepad++ installation directory>\plugins\NppExec\menuCmdID.h`

Search for `IDM_LANG`, below this line you will find all language constants.

**Comment by xziruss** [comment]
@dinkumoil, thank you!!!

All works, but after executing the script the "Console" window pops up:
![default](https://user-images.githubusercontent.com/38354859/38772241-df57091a-403a-11e8-8a16-b0b734c80c2c.jpg)



How can I turn it off?

**Comment by dinkumoil** [comment]
Add to every NppExec script the following code as first line:

`npp_console ?`

This makes NppExec to keep the current state of its console window - if it was hidden it will stay hidden.

For further questions please consult the comprehensive help of NppExec under menu `Plugins - NppExec - Help/Manual`. The console window also provides an online help for every command by typing `help <command>`. Typing only `help` displays a brief introduction to the features of NppExec.

**Comment by xziruss** [comment]
@dinkumoil,  SUPER !!!!

**Comment by zhangyuhangk** [comment]
Awesome!

**Comment by mirovingin** [comment]
Fabulous!

**Comment by MetaChuh** [comment]
closed, as this customisation can be done by using nppexec as described by @dinkumoil .

many thanks and best regards.

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
(no extra account is needed, just use your github account to sign in)
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)
