### ISSUE TITLE
Compare edit save undo failed

### ISSUE THREAD

**Issue by informatorius** [notepad-plus-plus/notepad-plus-plus#4408]
### Description of the Issue
When comparing 2 files with compare plugin and edit one file and save it then undo is not possible anymore.

### Steps to Reproduce the Issue

1.  Open 2 files and compare
2.  Edit one file and save it
3.  Try to undo the edit => failed

### Expected Behavior

The edit can be undo.

### Actual Behavior

Undo not possible anymore

### Debug Information

Notepad++ v7.5.6   (32-bit)
Build time : Mar 19 2018 - 00:26:59
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : ON
Local Conf mode : OFF
OS : Windows 7 (64-bit)
Plugins : ComparePlugin.dll DSpellCheck.dll mimeTools.dll NppConverter.dll NppExport.dll PluginManager.dll

**Comment by dail8859** [comment]
The Compare plugin is a 3rd party plugin and needs reported to its developer.

**Comment by informatorius** [comment]
Downloaded latest Compare plugin beta from https://ci.appveyor.com/project/pnedev/compare-plugin/history and it is fixed already
