### ISSUE TITLE
How to remove 3d effect outside document

### ISSUE THREAD

**Issue by burgerface** [notepad-plus-plus/notepad-plus-plus#4414]
![untitled](https://user-images.githubusercontent.com/38399793/38778712-504fb60e-40c6-11e8-8514-4c7ebce88d9c.png)
see that 3d effect? is there any way to disable it and make it flat, like most Windows 10 programs? if not plz add an option to do it.

**Comment by dail8859** [comment]
![capture](https://user-images.githubusercontent.com/3694843/38785487-b6e2eb2a-40ee-11e8-91f4-d84d048ffef3.PNG)

Make sure "No Edge" is check-marked and the "width" set to your liking.
