### ISSUE TITLE
Parsing error reported by XML Tools plugin.

### ISSUE THREAD

**Issue by NudeSpoons** [notepad-plus-plus/notepad-plus-plus#4418]
https://github.com/notepad-plus-plus/notepad-plus-plus/blob/9210bd37b6254988dce9fb1966e6d25a72332f85/PowerEditor/src/stylers.model.xml#L965
The angle brackets `<` and `>` surrounding `<TITLE HEIGHT=100>` cause an XML parsing error to be reported by XML Tools plugin (version 2.4.9.2 unicode 64bit).

**Comment by Huastecote** [comment]
I have a single line XML file size ~5KB (i.e. 5K characters long line). It was generated by an accounting system. I used Notepad++ Plugin “XML Tools 3.0.3.3” to make it readable. 
In about column 3K in the original file I see clearly the tag sequence:

<cfdi:Emisor RegimenFiscal="123" Rfc="XXXXXX" Nombre="XXXXX XXXX XXXX"></cfdi:Emisor>

But when I press Shift + Ctrl + Alt + B to reformat it, the ending tag </cfdi:Emisor> is gone! The same thing happens to another couple of tags!

**Comment by sasumner** [comment]
@Huastecote Probably best to try the support site for the _XML Tools_ plugin.

**Comment by Huastecote** [comment]
Ok, Thanks, Done: https://github.com/morbac/xmltools/issues/50 
Sorry for the distraction Notepad++/sasummer.

**Comment by Ekopalypse** [comment]
Issue can be closed - see https://github.com/notepad-plus-plus/notepad-plus-plus/blob/master/PowerEditor/src/stylers.model.xml#L993
