### ISSUE TITLE
Characters from Unicode block "Block Elements" show as question marks

### ISSUE THREAD

**Issue by aaaxx** [notepad-plus-plus/notepad-plus-plus#442]
Most of the characters, actually, and even when they're present in font (Consolas).
Regular Windows Notepad, in comparison, displays them all fine.

Before you ask, the encoding is set to UTF-8.

**Comment by milipili** [comment]
Could you provide a text file for reproducing the bug ?

**Comment by aaaxx** [comment]
Just copy and paste this (https://en.wikipedia.org/wiki/Block_Elements):

▀
▁
▂
▃
▄
▅
▆
▇
█
▉
▊
▋
▌
▍
▎
▏
▐
░
▒
▓
▔
▕
▖
▗
▘
▙
▚
▛
▜
▝
▞
▟

**Comment by aaaxx** [comment]
Damn. I closed the issue accidentally and don't know how to undo.

**Comment by aaaxx** [comment]
Oh, there it is.

**Comment by milipili** [comment]
Do not worry, I would have reopened it otherwise :)

**Comment by Marcono1234** [comment]
Possibly duplicated by #1621

**Comment by donho** [comment]
I believe this issue has been fixed since long time ago.
Update your Notepad++ to the latest version (v7.6.6).
If the issue persists, please create a new issue for it.
Thank you.

**Comment by ValZapod** [comment]
@Marcono1234 

> which causes the ones in front of them to render

Not in front also after as well.
