### ISSUE TITLE
SQL file take long time to reach to line 10103

### ISSUE THREAD

**Issue by TKkhan** [notepad-plus-plus/notepad-plus-plus#4420]
### Description of the Issue

If file having .sql extension has lot of code of a package it took ~5 min to reach to line 10103. in normal file it is ok. 

### Steps to Reproduce the Issue

1.  Get some sample Oracle package body code which has at least 10361 line of valid and compile able code in .sql file extension.
2. Open the file in Notepad++ from your SVN repository
3. Scroll normally till line 500
4. Press Ctrl +G from keyboard and type 10103, it will make the notepad++ in a hang(Not responding) state and will recover after 4-5 min when it reaches to required line.

### Expected Behavior

It should reach to desired line in less then a sec as it is doing for the .java file

### Actual Behavior

It is Okay with all other files

### Debug Information

One information I would like to add is that my SQL file contains a lot of regular expression and a lot of commas and after line no 1761 the colors of sql file are gone and rest of the code looks that it is all written with in the single quote but code is compile able and error free in Oracle database

**Comment by MetaChuh** [comment]
please update your notepad++ to the latest 64 bit version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins if you update from version 7.5.9 or below.

disable word wrap and remove spell checker plugins when using large files, and try again.

thank you for your help and best regards.
