### ISSUE TITLE
Open Unsaved File in New Instance

### ISSUE THREAD

**Issue by markvincentcaro** [notepad-plus-plus/notepad-plus-plus#4423]
Being able to Move a file to a new instance of Notepad++ is very useful when working with dual monitors.

However, you are only able to do so with a Saved file (the file already exists on your machine).

With Newly Created files, you first have to Save them before you can open them in a new instance of Notepad++, which is a bit cumbersome when you do not plan to keep said files in the first place.

Can this feature be implemented in the future?

**Comment by SinghRajenM** [comment]
Somewhat duplicate of #4396

**Comment by donho** [comment]
Unfortunately, such limit cannot be removed.
