### ISSUE TITLE
DSpellCheck doesn't work in Notepad++ 7.5.6

### ISSUE THREAD

**Issue by huserbg** [notepad-plus-plus/notepad-plus-plus#4425]
Performed clean installations of **Notepad++ 7.5.6** on both **Windows 10** and **Windows 7** machines.
Nothing is underlined and no suggestions when you right click on a misspelled word.
**Find Next Misspelling** (Alt+N) works, though.

The same behavior is seen in **Notepad++ 7.5.5** but it works OK in **7.5.4**.

**Comment by SinghRajenM** [comment]
It works fine for me:

Notepad++ v7.5.6   (32-bit)
Build time : Mar 19 2018 - 00:26:59
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10 (64-bit)
Plugins : DSpellCheck.dll mimeTools.dll NppConverter.dll NppExport.dll 


![image](https://user-images.githubusercontent.com/14791461/39092368-e5a1d652-4629-11e8-8ca4-368daf529fe4.png)


Please paste you debug info and DspellCheck version here.

**Comment by cganchev** [comment]
Notepad++ v7.5.6   (32-bit)
Build time : Mar 19 2018 - 00:26:59
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10 (64-bit)
Plugins : DSpellCheck.dll mimeTools.dll NppConverter.dll NppExport.dll 

![image](https://user-images.githubusercontent.com/4682153/39219218-ca6bee40-4831-11e8-866c-6bc590dd822b.png)

**Comment by huserbg** [comment]
I found what is causing this issue.
For some reason, when you clean install Notepad++ 7.5.5/6 or upgrade existing installation, the "Spell Check Document Automatically" option is unchecked "automatically".
