### ISSUE TITLE
Localization problem

### ISSUE THREAD

**Issue by ykdsoft** [notepad-plus-plus/notepad-plus-plus#4430]
Hi,

Notepad ++ 7.5.6 and Notepad ++ 7.5.5 (tested as 32bit and 64bit) do not work when I select Turkish as localization, do not give any error but the language is not active. I had to go back to version 6.9.2.

**Comment by rddim** [comment]
it is fixed in #4338

**Comment by nacarx** [comment]
I am using v7.5.6, 32bit
I am select the top menu Setting, Localization and Turkish but does not work language options.

**Comment by ykdsoft** [comment]
@nacarx Merhaba, sanırım Türk'sünüz o sebepten türkçe yazıyorum.

İlgili hatayı ben 6.9.x versiyona geçerek çözdüm ama eski versiyona dönmek istemezseniz aşağıdaki linkte çözümü mevcut.

https://github.com/notepad-plus-plus/notepad-plus-plus/issues/4336
İlgili hata notepad++ ın türkçe dil dosyası olan turkish.xml dosyasında ki bir tırnaktan kaynaklı sanırım,

 <Item id="1" name=Tamam"/>
bu kodu (T harfinden önce çift tırnak ekleyerek):
 <Item id="1" name="Tamam"/>

bu şekilde düzenleyip deneyebilirsiniz.
