### ISSUE TITLE
Pressing Escape key while in document switcher has unexpected behaviour

### ISSUE THREAD

**Issue by rogepa** [notepad-plus-plus/notepad-plus-plus#4432]
### Description of the Issue

While the document switcher is open and I press the Escape key, the Start menu shows up, takes fokus, and the switcher window stays open. When switching the focus back (with the keyboard) navigating with the up/down keys does no longer work.

### Expected Behavior

It would really be helpfull if NPP intercepts this key combo in a way that it just closes the document switcher panel without switching to another tab!

Thanks in advance.

**Comment by ArkadiuszMichalski** [comment]
@rogepa Do you still have this problem in latest Notepad++ version?

**Comment by donho** [comment]
Cannot reproduce this issue.
