### ISSUE TITLE
Notepad++ slows down if I zoom in

### ISSUE THREAD

**Issue by hujhax** [notepad-plus-plus/notepad-plus-plus#4436]
### Description of the Issue
If I zoom in on a text window, working with text gets very very slow.  Even simple tasks like selecting paragraphs of text become noticeably slower.  

### Steps to Reproduce the Issue

1. Open a new text file and set it to the default zoom level.
2. Add the 'lorem ipsum' text listed below.
3. Go to the top of the file, and hold down ctrl-shift-right arrow to select the text a word at a time.
4. Time how long it takes to get to the end of the paragraph.
5. Zoom to maximum by typing ctrl-numpad-plus twenty times.
6. Repeat steps 3 & 4.
7. Compare the timings.

As promised, here's the text:
> Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.

### Expected Behavior

I expect the two timings to be roughly the same, as I'm doing the same task.

### Actual Behavior

On my machine, it goes from 4 seconds (unzoomed) to 8 seconds (zoomed) -- slow enough to be really annoying.  You may notice slowdowns in the menu behavior, and even in highlights disappearing once text is deselected.

### Debug Information

Notepad++ v7.5.6   (32-bit)
Build time : Mar 19 2018 - 00:26:59
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10 (64-bit)
Plugins : DSpellCheck.dll mimeTools.dll NppConverter.dll NppExec.dll NppExport.dll

**Comment by MetaChuh** [comment]
no speed lag is visible using notepad++ 7.6.6.

please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins if you update from version 7.5.9 or below.

if a performance issue still persists on your machine, please disable or remove the dspellcheck plugin.

many thanks and best regards.
