### ISSUE TITLE
Missing Highlight or Color in Ruby code

### ISSUE THREAD

**Issue by edwinacunav** [notepad-plus-plus/notepad-plus-plus#4439]
**Description of the Issue**

Well, notepad++ stops highlighting or coloring text if I am working on a Ruby file. This happens right after I type stuff like %= operator, the trailing text is treated as normal text and does not get any special color, neither background nor foreground color. **if, unless, while and until** modifiers go through the same situation. (Those one uses to the right hand side, not at the beginning of the line.)

**Comment by ArkadiuszMichalski** [comment]
https://sourceforge.net/p/scintilla/bugs/1255/
https://sourceforge.net/p/scintilla/bugs/2182/

**Comment by rdipardo** [comment]
Duplicate of #9918

This was fixed in Lexilla 5.2.3 and can be closed: ScintillaOrg/lexilla@1e347a1ab265f67013a37703e4c216cf52b32341

**Comment by chcg** [comment]
Fix available since N++ release v8.5.1 .
