### ISSUE TITLE
VS2015 version fails to compile due to sqlite3 file references

### ISSUE THREAD

**Issue by BrainJelly** [notepad-plus-plus/notepad-plus-plus#444]
The VS2015 project has file references to the ..\src\sqlite\sqlite3.c and ..\src\sqlite\sqlite3.h files.
Since these were deleted in commit 5e240147c51b6c27f1accbcfa191d9ddc4967e68 NPP fails to compile. :)

**Comment by donho** [comment]
sqlite3 has been removed from Notepad++ project.
