### ISSUE TITLE
NppExport "Copy HTML to clipboard" not working

### ISSUE THREAD

**Issue by kirsan31** [notepad-plus-plus/notepad-plus-plus#4442]
### Description of the Issue
"export to html" work well, but it export all file, and I am need only selected piece of code. As I Understand, "copy html to clipboard" must do the trick - copy selected text with highlighting **as html code**. But it do nothing for me - clipboard is empty :(

### Steps to Reproduce the Issue

1. Open any file with Syntax Highlighting.
2. Select some text.
3. Press: Plugins -> NppExport -> Copy HTML to clipboard

### Expected Behavior
Html code with highlighting of selected text must be copied to clipboard.

### Actual Behavior
Clipboard is empty.

### Debug Information

Notepad++ v7.5.6   (32-bit)
Build time : Mar 19 2018 - 00:26:59
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 7 (64-bit)
Plugins : CustomizeToolbar.dll DSpellCheck.dll mimeTools.dll NppConverter.dll NppExport.dll PluginManager.dll

**Comment by bahusoid** [comment]
Go to Edit menu -> Paste Special -> Paste HTML Content

Explanation:
Clipboard is not empty. There is multiple clipboards in Windows - each one  can be with specific format (one clipboard with HTML content; another with plain text or RTF and so on). By default plain text clipboard is pasted - which is empty in this case.
If you try to paste in app that supports multiple clipboards (like Microsoft Word) - formatted text will be pasted as expected.

**Comment by kirsan31** [comment]
@bahusoid Thank you. I understand my mistake. I thought that "Copy HTML to clipboard" - copy plain text html code to clipboard. But it copy html formatted text with :( So, to achieve my goal I must to do 4 steps:

1. Copy HTML to clipboard
2. Create new file
3. Paste HTML Content
4. Copy it

So, we need from NppExport one more function, something like : "Copy HTML **code** to clipboard" :)
