### ISSUE TITLE
Virus found on file: uninstaller.exe (version 7.5.6, 32-bit)

### ISSUE THREAD

**Issue by gars** [notepad-plus-plus/notepad-plus-plus#4443]
### Steps to Reproduce the Issue

1. Download the 32bit installer from https://notepad-plus-plus.org/download/v7.5.6.html.
2. Install it (right click, Run As Administrator, and grant elevation privilege for installer)
3. Run notepad++.
4. Anti-virus catches the "win32-malware-gen" inside the file uninstall.exe

### Expected Behavior

Notepad++ running without viruts

### Actual Behavior

Virus detected

### Debug Information

![image](https://user-images.githubusercontent.com/422404/39101935-c1b74e88-4675-11e8-8e25-843c1f4fe571.png)

**Comment by SinghRajenM** [comment]
This is false alarm. Uninstall.exe is auto generated nsis script (which is popular script to create installers including commercial setups). I feel it can be reported to Avast too.
