### ISSUE TITLE
Find all occurence of text improvement

### ISSUE THREAD

**Issue by livius2** [notepad-plus-plus/notepad-plus-plus#4445]
### Description of the Issue

Find all occurence of text work ok when it work with simple text.
But when we enter regex - then will be good to see finded text on the list.

### Steps to Reproduce the Issue

1.  Open some english document.
2. press Ctrl+F enter regex "and.{0,30}"
3. press find all occurences in current document

### Expected Behavior

Finded list should contain finded text e.g.
"and someone eat.."
"and the weather..."
...

### Actual Behavior

Now list show some starting word of the finded line but this is not what we try to find.
If this is simple find we know what we can find.
e.g we look for "dog" then this is obvious that resulted lines do not contain dog word.
But with regex this is unknow what we find as a result.

**Comment by sasumner** [comment]
It is not "unknown what we find as a result".  The "Find result" panel shows what makes up the hits in special color (default is red foreground and yellow background).

![image](https://user-images.githubusercontent.com/30118311/39124630-1dca581a-46ca-11e8-8749-2874b4fc2e63.png)

**Comment by livius2** [comment]
Them must be relation to file context
When i do this on exe file content i do not see this but for simple text file i see good result
Look at image - on the top it is for simple text file and work ok
on the bottom same for exe file and it is not so usefull
![image](https://user-images.githubusercontent.com/14888294/39174208-54889316-47a7-11e8-963d-d18551f2ab64.png)

**Comment by sasumner** [comment]
Ummm...well, Notepad++ is a _text_ editor, not a _hex/binary/exe_ editor...  It is not going to do things well that are out-of-scope...

![image](https://user-images.githubusercontent.com/30118311/39184597-f20bab16-4791-11e8-8428-924c77191a7d.png)

**Comment by alankilborn** [comment]
Recommend CLOSURE of this item.
