### ISSUE TITLE
Whole OS hangs when opening more than two files at a time

### ISSUE THREAD

**Issue by Big--Mike** [notepad-plus-plus/notepad-plus-plus#4447]
### Description of the Issue
I have associated txt files with Notepad++, the command line is **"C:\Program Files (x86)\Office\Notepad++\Notepad++.exe" "%1"**

Selecting one or two files in explorer at a time and open them by pressing Enter works fine. Three or more files lead to a hang of my whole operating system. The user interface gets unresponsable. If Notepad++ is already open, all works fine.
 
### Steps to Reproduce the Issue
1. Associate txt files with Notepad++ 
2. Create a bunch of little text files
3. Make sure, Notepad++ is closed 
4. Select them all in explorer and press enter

### Expected Behavior
Notepad++ opens a tab for each text file (works fine with one or two files here)

### Actual Behavior
The UI gets unresponsible, the whole Operating System hangs

### Debug Information
Notepad++ v7.5.6   (32-bit)
Build time : Mar 19 2018 - 00:26:59
Path : C:\Program Files (x86)\Office\Notepad++\Notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10 (64-bit)
Plugins : none

**Comment by Big--Mike** [comment]
This problem still happens with Notepad++ 7.5.7 here...

**Comment by isshininu** [comment]
7.5.8. x64
Windows 10, 1809, x64.

I too have this problem.
Even If i trying to open only 2 files - Windows shell became unresponsible until I Ctrl + Alt + Del and logout of system.
As a workaround - in Notepad++ settings change the way program open new files. Change it to open each file in new window (instead of opening all files in tabs). Works for me.

**Comment by MetaChuh** [comment]
@Big--Mike 

we can not reproduce a freeze, when opening 3 or more files simultaneously in notepad++ 7.6.6 x86 and x64, via windows explorer on win7 pro x64 and win10 pro x64 (build 1809).

we can only see a normal lag, if a local or network drive is hibernated, while trying to open files located on that drive/share.

if your issue persists, please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html).
if possible, conduct a uninstall and clean install, preferably with the 64 bit version of notepad++, if you don't need any old plugins that do not exist for 64 bit, as notepad++ x64 can also deal with larger files.

please also check the full path lengths of the concerning files, and that the total path length of all files that were used when testing, can be handled by windows explorer.

thank you for your help and best regards.

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
```
[<kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd>](https://notepad-plus-plus.org/community/)
