### ISSUE TITLE
UI wording: "Search"→"Find in Files" should have ellipsis

### ISSUE THREAD

**Issue by Explorer09** [notepad-plus-plus/notepad-plus-plus#4448]
### Description of the Issue
The "Search"→"Find in Files" item in the menu bar does not have an ellipsis suffix, despite the fact it pops up a dialog instead of doing an immediate action.

Tested in Notepad++ v7.5.6.

### Steps to Reproduce the Issue
1. Make sure you set Notepad++ language to English. (It may not be applicable to other localizations, but I find it also wrong for Chinese (Traditional).)
2. Click "Search" in the menu bar and see the "Find in Files" item.

### Expected Behavior
The item should be named "Find in Files..."

### Actual Behavior
"Find in Files" (without ellipsis)

**Comment by sasumner** [comment]
If you have never changed the Localization setting, the ellipsis is present.  However, changing it to _English_ (even though it says it is already set to _English_) or _English (customizable), or probably many other possible choices, results in NO ellipsis (same for things like File -> Open and File -> Save and probably others...no ellipsis after the text).

**Comment by ArkadiuszMichalski** [comment]
@sasumner Can be close, ellipsis exist in actual English:
![a](https://user-images.githubusercontent.com/2730894/94132305-651d7900-fe5f-11ea-9abe-1983acd92535.gif)
