### ISSUE TITLE
File Save Issue in drives or environment variable paths

### ISSUE THREAD

**Issue by h0cus** [notepad-plus-plus/notepad-plus-plus#4449]
### Description of the Issue

When browsing to paths or folders within Notepad++, the editor is trying to create the folder instead of navigating to it. 
### Steps to Reproduce the Issue

1. Create a dummy file.
2. File - Save or File - Save As
3. Choose %userprofile% or say D:\

### Expected Behavior

Expect Notepad++ to browse to the folder or path rather than try create a file there .

### Actual Behavior

Creates a text file with value of %userprofile% environment variable.txt i.e. if my %userprofile% contains testuser it creates testuser.txt in current path. If I choose D:\ then it tries to create D:.txt 

### Debug Information

Notepad++ v7.5.6   (64-bit)
Build time : Mar 19 2018 - 00:23:17
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : ON
Local Conf mode : OFF
OS : Windows 7 (64-bit)
Plugins : DSpellCheck.dll mimeTools.dll NppConverter.dll

**Comment by mere-human** [comment]
In version 7.9.3 file dialogs have been upgraded so this problem isn't reproducible anymore.
Now the environment variables are handled correctly: the dialog navigates to the specified folder.
@sasumner Could you, please, close this issue?
