### ISSUE TITLE
Keyboard shortcut for "Reload from Disk"

### ISSUE THREAD

**Issue by T-Reagan** [notepad-plus-plus/notepad-plus-plus#4450]
It would be helpful if there was a keyboard shortcut for reloading a file from disk.  Sometimes I open a log file for a process and would like to see how it is progressing without having to point and click through the menu each time or minimize and maximize the window itself.

**Comment by sasumner** [comment]
Pick one you like and add it!

![image](https://user-images.githubusercontent.com/30118311/39196257-a0faa556-47af-11e8-881e-2bba575598cc.png)

**Comment by dail8859** [comment]
As suggested, you can add it yourself.

**Comment by sasumner** [comment]
@T-Reagan , another point: consider using the **View** (menu) -> **Monitoring (tail -f)** feature for what you are doing manually with the reload command?
