### ISSUE TITLE
Suggestion: use default Windows 10 open file dialog.

### ISSUE THREAD

**Issue by volsend** [notepad-plus-plus/notepad-plus-plus#4457]
### Description of the Issue
When opening a file in _notepad++_ in _Windows 10_, the open file dialog used does not allow manual editing of current folder's path.

### Steps to Reproduce the Issue
1.  Press _Ctrl+O_ or menu item _File / Open..._.
2.  Try pressing _Alt+D_.

### Expected Behavior
Address bar should become focused and path should become editable like usual text.

### Actual Behavior
Nothing happens.

Default file dialogs, like the ones that browsers use, would be very helpful in cases when a file is placed somewhere deep in file structure and you can Copy/Paste this path through the clipboard or for those, who mostly uses a keyboard.

This is how it currently looks like:
![image](https://user-images.githubusercontent.com/11583611/39294166-ae319474-4943-11e8-833a-7f103180d0d6.png)

This how it is supposed to be:
![image](https://user-images.githubusercontent.com/11583611/39294109-876c4596-4943-11e8-82c2-2987d184cbb5.png)

**Comment by MAPJe71** [comment]
Suggestions:
1. search `Settings` > `Preferences...` for applicable option;
2. search repository and community forum for equal/simular issues before posting;

Please close issue.
