### ISSUE TITLE
Doesn't start on Fedora after the installation with Snapd

### ISSUE THREAD

**Issue by Warmuser** [notepad-plus-plus/notepad-plus-plus#4459]
Fedora 27, latest updates and latest kernel.

**Comment by sasumner** [comment]
Notepad++ is a Windows application.  Please close this issue.

**Comment by Warmuser** [comment]
I'm sorry but I'm not totally wrong, it was these package called "Notepad plus plus" on Snapd store, so I thought it was yours. Look:

https://snapcraft.io/notepad-plus-plus
https://notepad-plus-plus.org

**Comment by MAPJe71** [comment]
The Notepad++ snap app is created by Taqi Raza (as mentioned on [Snapcraft](https://snapcraft.io/notepad-plus-plus)) and AFAIK not affiliated with the Notepad++ team. Post you issue in his [repository](https://github.com/mmtrt/notepad-plus-plus) (contact link as provided on aforementioned Snapcraft site).

See also [forum topic](https://notepad-plus-plus.org/community/topic/15377/notepad-as-a-linux-snap-app).
