### ISSUE TITLE
search & replace but only bookmarked lines

### ISSUE THREAD

**Issue by WJSNLuda** [notepad-plus-plus/notepad-plus-plus#4460]
Is it possible to search & replace only bookmarked lines?

**Comment by sasumner** [comment]
No.  And you are asking a question, not reporting an issue.  Questions don't belong here.  

If you are making a feature request, please put the effort in to make it sound like a feature request, fill out more details, etc.

**Comment by sasumner** [comment]
Closed due to inactivity / lack-of-interest.
