### ISSUE TITLE
Closing the program is tedious when multiple unsaved editor tabs are open and session snapshot backups are disabled

### ISSUE THREAD

**Issue by jkrv** [notepad-plus-plus/notepad-plus-plus#4462]
### Description of the Issue
**Preconditions**:
- Settings > Preferences > Backup > ‘Enable session snapshot and periodic backup’ is disabled.
- There are unsaved nonempty new files open in tabs.

**Trigger**: Program is closed OR ‘Close All’ action is triggered.

**Problem**: For each unsaved tab, confirmation dialog to save the file is shown. If there are tens or even hundreds of such files, it can get really tedious to click ‘no’ for all of them. 

Note: if cancel is clicked for any of the opened dialogs, all the tabs will be still open even if no was already answered in confirm dialog for that specific file.

### Steps to Reproduce the Issue
0. Disable ‘Enable session snapshot and periodic backup’ setting.
1. Close all the open tabs, close program, restart the program
--> there should be one empty tab with name ‘new 1’
2. Click ‘Start Recording’ icon in toolbar (starts macro recording)
3. Click File > New
4. Enter string “abc” in the just opened editor tab
5. Click ‘Stop Recording’ icon (stops macro recording)
6. Click ‘Run a Macro Multiple Times…’ icon
7. Enter value 98 in Run field and then click ‘Run’ button 
--> there should now be 100 open tabs with some text content
8. Exit the program (via File menu or via window close icon)
9. Click through the hundred dialog and click no in each 
--> The program will exit eventually but it may take some time.

### Expected Behavior
There to be some shortcut to close all the files and exit quickly.

### Actual Behavior
All the opened dialogs must be clicked through to exit.

### Suggestions for fix
- Add checkbox ‘repeat for all’ in Save confirm dialog on program exit or when clicking ‘Close All’.

#### Manual file removal
- Enable ‘Enable session snapshot and periodic backup’ setting
- Wait some time so that backups are saved
- Close the program (should not ask anything)
- Remove the following backup directory manually:
C:\Users\<user>\AppData\Roaming\Notepad++\backup
- Reopen program and disable ‘Enable session snapshot and periodic backup’ setting

#### Using a macro
- Start macro recording
- Click left mouse in first editor tab
- Press Ctrl + A
- Press Delete key
- Click File > Close
- Stop macro recording
- Execute the macro as many times as there are unsaved editor tabs

### Debug Information
Notepad++ v7.5.6   (32-bit)
Build time : Mar 19 2018 - 00:26:59
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10 (64-bit)
Plugins : DSpellCheck.dll JSMinNPP.dll mimeTools.dll NppConverter.dll NppExport.dll PluginManager.dll

**Comment by MetaChuh** [comment]
please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins.
if your issue still persists, and it is still of relevance to you, please feel free to file a new issue as detailed and reproducible as possible.

thank you for your help and best regards.

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)
