### ISSUE TITLE
Feature Request: Initialize Lexer for Perl6

### ISSUE THREAD

**Issue by ultra-gitsome** [notepad-plus-plus/notepad-plus-plus#4465]
### Description of the Issue

Please initialize a lexer for Perl 6 to allow new P6 keywords and autocomplete to go under the proper .xml file.
 
### Steps to Reproduce the Issue

1.  Perl 6 has different syntax than Perl 5.
2.  IMO, the lexer can be initially barebones - empty container.
3.

**Comment by zufuliu** [comment]
Lexer for Perl6 is not yet available:

https://sourceforge.net/p/scintilla/feature-requests/1207/

**Comment by ultra-gitsome** [comment]
Not looking for a complete lexer. That would be a big ask. Is there a reason that the lexer cannot be initialized so others can add to it?
Maintaining my own syntax fork seems the only other alternative.

**Comment by hankache** [comment]
Lexer for Raku (previously known as Perl 6) has been added to Scintilla

**Comment by hankache** [comment]
@donho and n++ team. Anything specific should be done? Or should we just wait until n++ updates Scintilla to 4.3.0 and we'll be set? Thanks
