### ISSUE TITLE
Feature Request: For accessibility, make the active tab the same color as the rest of the tabs.

### ISSUE THREAD

**Issue by LAPIII** [notepad-plus-plus/notepad-plus-plus#4466]
I have Windows High Contrast theme on and I cannot see that text in the active tab:

<img width="480" alt="n" src="https://user-images.githubusercontent.com/7947363/39448873-6689f838-4c94-11e8-8786-bf1f8c70970c.PNG">

**Comment by sasumner** [comment]
...and you had no luck changing the colors to something acceptable using Style Configurator?

**Comment by ArkadiuszMichalski** [comment]
@LAPIII do you solve your problem through Style Configurator window? If yest then please close this bug.
