### ISSUE TITLE
Search fail with match whole words only: Inverted question mark problem

### ISSUE THREAD

**Issue by DavidHaslam** [notepad-plus-plus/notepad-plus-plus#4470]
I have a Spanish text that contains lots of sentences that begin with "¿", the **Inverted Question Mark** character U+00BF, as is normal in Spanish punctuation.

Knowing that the word "Oiste" only occurs _once_ in the whole text, I was surprised that when I did a search using Notepad++ for this word with **Match whole words only** and **Match case** ticked, the word was not found.

It turns out that the word immediately follows the **Inverted Question Mark**, viz.
```
\v 8 ¿Oiste tú el secreto de Dios, que detienes en ti solo la sabiduría?
```

This word ought to have been found.

For the purposes of searching, the "¿" character should be classed as a **punctuation mark**, not as a word character.

cf. Searching for "¿Oiste" with the same options does find the word.

NB. The same problem also occurs with "¡" - the Inverted Exclamation Mark U+00A1.

**Comment by sasumner** [comment]
Possibly related to #4255

**Comment by MetaChuh** [comment]
this is a limitation of the implemented boost engine, which is an external project.
there is currently nothing we can do at the notepad++ part.

thank you for your help and best regards.

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
(no extra account is needed, just use your github account to sign in)
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)
