### ISSUE TITLE
Vertical edge is not drawn correctly if the font is resized dynamically

### ISSUE THREAD

**Issue by Zingam** [notepad-plus-plus/notepad-plus-plus#4471]
### Description of the Issue

Vertical Edge Settings don't work if a Theme is chosen and the font is resized with the mouse dynamically. I need to reselect the theme for the vertical edge to be drawn correctly.

**Comment by ClaudiaFrank** [comment]
I use twodark theme and the edge line for quite some time now but never encountered such issue.
Could you provide more details? Does this happens always? If so, can you provide the exact steps
to replicate the reported behavior? Which npp version do you use (debug-info)?

**Comment by Zingam** [comment]
And here I just re-applied the theme from style configurator and the vertical line was drawn correctly. I suspect the line is drawn at the default position of the default font size when Notepad++ is opened and does not respect the zoom level that I have set by zooming the document with the mouse wheel.
![capture](https://user-images.githubusercontent.com/3337419/39650844-64ff309e-4ff2-11e8-963b-fa432d1b801d.PNG)

**Comment by Zingam** [comment]
And here apparently Notepad++ fails to apply the Courier New font (I guess) and uses some font with variable width for this .bat file:
![capture](https://user-images.githubusercontent.com/3337419/39651216-b118e406-4ff3-11e8-92b8-3d0361abbce4.PNG)
Here is the same file. I just changed the theme:
![capture](https://user-images.githubusercontent.com/3337419/39651268-e77915fc-4ff3-11e8-9dca-ff32cae7c4f5.PNG)

**Comment by Zingam** [comment]
Well, it is not the Zoom-in feature. It is probably the Obsidian theme as the above doesn't happen with other themes that I've tried.

**Comment by ClaudiaFrank** [comment]
Ok, I guess I understand.
It it not the theme itself which causes this but the font being used.
Non-mono-spaced fonts do have different width therefore the edge line seems to jump.
I would suggest, to use mono-spaced fonts then this shouldn't be an issue anymore and
to make it happen you either have to tick the **enable global font** check box or you have to
set it for every style id independently.

**Comment by Zingam** [comment]
I did that but there is an issue though:
In the .bat file the line is at col 81
![capture1](https://user-images.githubusercontent.com/3337419/39661820-281f80ce-5061-11e8-8094-cbe19f20b08b.PNG)
In the Python file it is drawn at col 80
![capture2](https://user-images.githubusercontent.com/3337419/39661825-3dd9085e-5061-11e8-8a44-9b0e33addb17.PNG)
Well actually apparently the fonts are not properly drawn. Notice how the new line of "#" is offset to the left a little bit and it ends at col 81 but the old line:
![capture3](https://user-images.githubusercontent.com/3337419/39661840-70bfff52-5061-11e8-86d5-ac1bc197d855.PNG)

**Comment by Zingam** [comment]
Here is basically the whole line:

The highlighted line is the one I added after I noticed that the vertical edge is not drawn at the appropriate place.

![capture](https://user-images.githubusercontent.com/3337419/39661876-f3bb5a28-5061-11e8-947f-1119228d3ee3.PNG)

**Comment by ClaudiaFrank** [comment]
If you refer to Col:81 of the statusbar this means the cursor is in front of that column.
If, for example, you would put the cursor to the start of the line, it would report Col:1

What is done is this, scintilla, the underlying control which does all of that, calculates
the position of the edge line by taking the width of the space character of the default style - done.

If the font has different width of different characters then this doesn't really work at all.
Same is true for "mono-spaced fonts". One could imagine that a mono-spaced font uses
always the same width for each character but, unfortunately, this isn't true always. The Roboto Mono
font, I recently started to use, seems to have a different width of the space character compared to
all other characters. I hope this clarifies the situation a bit.

**Comment by Zingam** [comment]
How come Courier New is not monospaced? This is what a multi-line selection looks like:
![capture](https://user-images.githubusercontent.com/3337419/39664971-f3cb1660-5094-11e8-8f94-3a23c8b61653.PNG)
![capture1](https://user-images.githubusercontent.com/3337419/39665010-58567638-5095-11e8-9a48-d964108343c1.PNG)
![capture2](https://user-images.githubusercontent.com/3337419/39665011-5a70cef0-5095-11e8-94cd-9755e1b8cc7b.PNG)

**Comment by Mikhail22** [comment]
if you use different fonts in syntax customization then it is expected behaviour - so I can't see why do you  call this an issue. When *only* monospaced font is used then you'll have vertical alignment everywhere. If that is what you need, just use monospaced font for all syntax groups or apply use global font option. Seem you just haven't got completely familiar with style configurator and how it works.

**Comment by MetaChuh** [comment]
not reproducible on notepad++ 7.6.6.
using themes like obsidian with courier new, shows the vertical edge when zooming in and out repeatedly.

many thanks and best regards.
