### ISSUE TITLE
New Logo

### ISSUE THREAD

**Issue by talentlessguy** [notepad-plus-plus/notepad-plus-plus#4477]
<!DOCTYPE html>
<html>
<h1>It's time to update the logo. Now it looks old.</h1>
<h3>Here are some variants of the improved logo</h3>
<img src='https://78.media.tumblr.com/546f8638be8c79e69bcff398bf22ad74/tumblr_pa0bh9SLmX1war8pho1_1280.png' width='50%' height='50%'>
<img src='https://78.media.tumblr.com/3643606c6f64d791497398559973c36c/tumblr_pa0bh9SLmX1war8pho2_1280.png' width='50%' height='50%'>
<img src='https://78.media.tumblr.com/f187a6acfe661b6aa5ffc906bc44b2c5/tumblr_pa0bh9SLmX1war8pho3_1280.png' width='50%' height='50%'>
<a href='instagram.com/talentlessguy'><h2>Contact Me</h2></a>
</html>

**Comment by magol** [comment]
I agree that the logo should be updated to a more modern version. But I think it should be based on the old one.

**Comment by PauloFrancaLacerda** [comment]
I like it the way it is now. Looks "modern" enough to me.

**Comment by talentlessguy** [comment]
@magol I can create a new logo that is based on old one. Okay?

**Comment by magol** [comment]
@talentlessguy 
Do not worry, I do not take it badly. It's good to be able to discuss. :-)
I see in you example that the icon actual do have a high resolution version, I should have check it up beter before I write my comment  :-)

I understand exactly what you mean, and actually agree with you.
But you can see an icon as a brand logo, and I do not think you should change a branded logo too much. When companies design new brands, they usually base the new brand on the old one, and that's exactly what I mean should be done with the Notepad ++ icon to. People who see the new icon should  recognize the icon as Notepad++, and not as a completely different product.

**Comment by bfridkis** [comment]
The iguana (at least, I think it's an iguana) is quite charming indeed...

**Comment by MAPJe71** [comment]
FYI: it's a cameleon.

**Comment by bfridkis** [comment]
Ah yes. That's what I meant. :)

**Comment by talentlessguy** [comment]
I understood that the chameleon should stay, so I can re-design the icon
without changing a construction, just add some flat style and so on. Is it
okay?

вт, 8 мая 2018 г., 1:13 Magnus Österlund <notifications@github.com>:

**Comment by talentlessguy** [comment]
Hey guys I added some variants, what are the ideas? Do you like any of them? Or want the another?

**Comment by MetaChuh** [comment]
many thanks for your design ideas.

we actually like the way the old notepad++ logo looks.
but keep up the good work.

thank you for your help and best regards.
