### ISSUE TITLE
When case insensitive sorting will be added in Notepad++ x64 (without TextFX)?

### ISSUE THREAD

**Issue by PiotrMP006** [notepad-plus-plus/notepad-plus-plus#4479]
When case insensitive sorting will be added in Notepad++ x64 (without TextFX)?

insensitive sorting vs sensitive sorting

A A
a B
B C
b a
C b
c c

**Comment by sasumner** [comment]
Related Community posting:
https://community.notepad-plus-plus.org/topic/19659/sort-case-insensitive-on-64-bit

**Comment by Corey-Keller** [comment]
NOTE: This is just some armchair code ideas from someone who hasn't done ANYTHING C(++) in 10+ years, so it may be completely invalid. If so, please let me know.

[Here](https://github.com/notepad-plus-plus/notepad-plus-plus/blob/0bf3eea08ae83c9abcfbef722c51a994b3800bac/PowerEditor/src/MISC/Common/Sorters.h#L80) is the code that is used for lexicographic sorting. Couldn't you either:

1. Just make a new duplicate class ("LexicographicSorterCaseInsensitive") 
2. add a parameter (bool isCaseSensitive, like there already is for ascending/descending)

where the comparison function contents changes `return a.compare(b) < 0;` to `return toupper(a).compare(toupper(b)) < 0;`?

**Comment by sasumner** [comment]
@Corey-Keller 
It's a bit more involved than that in the Unicode world, but it's certainly doable of course.
I'll be working on it.

**Comment by Corey-Keller** [comment]
> 
> 
> @Corey-Keller
> It's a bit more involved than that in the Unicode world, but it's certainly doable of course.
> I'll be working on it.

Right. After posting I saw [this](https://qr.ae/TW8wnX) that points out just how difficult it can be with non-English languages, much less all of the extra issues dealing with the full Unicode 13 set.

**Comment by deus-e-x** [comment]
I think it would be sufficient to support case insensitive sorting of the English character set only.

I just checked with NppTextFX, it sorts lines containing special foreign characters like ‘ß’ or ‘Ф’ at the top of a sort result. I.e. NppTextFX does not try to sort such lines but places them at a prominent place for the user to easily get aware.

**Comment by sasumner** [comment]
@donho Does implementing this leave us open to everyone wanting/expecting something different out of it?  And a lot of future "issues" created when it doesn't do what individual users expect?

I'm not opposed to putting effort into it, but I'd like to have an "approved" direction on it before doing so.

Possible proposal, to test it out and see how well it is received:  Use the existing `OrdinalIgnoreCaseCompareStrings` function as the compare basis? @donho what do you think?  Otherwise, suggestions?

**Comment by donho** [comment]
@sasumner 
> Does implementing this leave us open to everyone wanting/expecting something different out of it? 

Not necessary. 

> And a lot of future "issues" created when it doesn't do what individual users expect?

What kind of future "issues" we could have?

> Possible proposal, to test it out and see how well it is received: Use the existing OrdinalIgnoreCaseCompareStrings function as the compare basis?

Isn't `LexicographicSorter`function we should extend? From my naive eyes we should just reuse and modify slightly the algorithm in "Sort Lines Lexicographically Ascending/Descending".

**Comment by sasumner** [comment]
@donho 

>What kind of future "issues" we could have?

People could have varied expectations on what it should do to _their_ data.
When it doesn't do what they want ----> issue entry
It's not a terrible thing, but reading the same issues over and over again gets boring/annoying.

Well, I meant use `OrdinalIgnoreCaseCompareStrings` as the "bottom level" function to judge "this string sorts BEFORE this other string".  The model for sorting is already existing with the other sorting functions.  It is a copy+paste+change-the-bottom-level-compare-function effort.

I'll give something a try to see if it is "liked".
It is not a lot of effort to do so.

**Comment by donho** [comment]
> reading the same issues over and over again gets boring/annoying.

We can put them together in the comment (with Github's reference system) for seeing if the feature is worth to do.

> I'll give something a try to see if it is "liked".

Thank you, I saw the new PR. I will check it.
