### ISSUE TITLE
Add left margin to typing area

### ISSUE THREAD

**Issue by aaaxx** [notepad-plus-plus/notepad-plus-plus#448]
Having a left margin of at least half a character in the typing (code) area would be really helpful. Right now the text butts up to bookmark bar, line number bar, or window frame (depending on what's set up to be displayed in Preferences) and it's hard to select a piece of it at the beginning of a line without placing a bookmark or selecting the whole line by clicking on line number.

**Comment by donho** [comment]
I prefer the current behaviour.
