### ISSUE TITLE
navigation with arrows near end of large file is misbehaving

### ISSUE THREAD

**Issue by malytomas** [notepad-plus-plus/notepad-plus-plus#4482]
### Description of the Issue

Up arrow always skips one line. Down arrow does nothing.

It is only happening on couple last lines in the file (approximately one last screen).

### Steps to Reproduce the Issue

1.  open large file (mine is 142 MB large log from a program, over 900 000 lines)
2.  press ctrl+end to go to the very end of the file
3.  start navigating with arrows

### Debug Information

Notepad++ v7.5.6   (32-bit)
Build time : Mar 19 2018 - 00:26:59
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10 (64-bit)
Plugins : DSpellCheck.dll mimeTools.dll NppConverter.dll NppExport.dll 

I may not upload the file since it may contain sensitive data. Hopefully someone else can reproduce the bug with other files.

**Comment by sasumner** [comment]
Do you have any of the "backup" features turned on?  If so, can you try turning them off and then trying your scenario again as a test?  It is a known issue that the backup feature can cause similar behavior to what you are seeing.

**Comment by malytomas** [comment]
I have tried it with several different backup configurations, including all backup options turned off, and none of them had any impact on the issue.

**Comment by dail8859** [comment]
Tested with Notepad v7.7 and cannot reproduce issue. 118MB file with nearly 2.8 million lines. It is likely the new version of Scintilla fixed this issue.
