### ISSUE TITLE
Notepad++ cannot open text file with long filename

### ISSUE THREAD

**Issue by evanpetridis** [notepad-plus-plus/notepad-plus-plus#4483]
### Description of the Issue
Notepad++ cannot open text file with long filename

### Steps to Reproduce the Issue
1.  Double click on .txt file in Windows Explorer. Notepad++ has been started as administrator
2. The full path including filename is 106 characters long
3. Paths longer than 260 characters have been enabled on WIndows 10
4. The file has a size of 189 bytes

### Expected Behavior
Text file should open in notepad++

### Actual Behavior
1. notepad++ displays a dialog (contents of dialog below Ctrl+C)
---------------------------
Cannot open file
---------------------------
-long path on a shared drive\README.txt- cannot be opened:
Folder -long path on a shared drive- doesn't exist.
---------------------------
OK   
---------------------------

### Debug Information
Notepad++ v7.5.6   (32-bit)
Build time : Mar 19 2018 - 00:26:59
Path : D:\Program Files\Notepad++\notepad++.exe
Admin mode : ON
Local Conf mode : OFF
OS : Windows 10 (64-bit)
Plugins : DSpellCheck.dll mimeTools.dll NppConverter.dll NppExport.dll NppFTP.dll PluginManager.dll TakeNotes.dll XMLTools.dll 
![image](https://user-images.githubusercontent.com/3453511/39735314-9f915c24-52ad-11e8-8cf8-2e306cd2e7dc.png)

**Comment by bfridkis** [comment]
I wasn't able to reproduce this error, but did note the following:

I saved a file with the maximum number of "1"s followed by .txt (so 11111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111.txt), and when opened from the desktop, the file loaded as such:

![image](https://user-images.githubusercontent.com/32713413/39960528-1475d6d4-55ea-11e8-8ab7-c22adc85afb9.png)

Then I tried opening the same file from a sub-directory, and it opened like so:

![image](https://user-images.githubusercontent.com/32713413/39960541-44af16b2-55ea-11e8-8e63-a40c11978259.png)

The same was observed with a file with the maximum number of "a"s followed by .txt (so aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa.txt). From desktop:

![image](https://user-images.githubusercontent.com/32713413/39960549-689bbf08-55ea-11e8-9111-c78180d2e600.png)

From sub-directory (note the a's are capitalized below):

![image](https://user-images.githubusercontent.com/32713413/39960569-a7067d50-55ea-11e8-8962-1b2bc6bb2f34.png)

I am running the same version on Windows 10 and installed the same plugins as listed above. For "Admin mode" do you mean running as administrator (which I also tried) or something else? If so, how do we enable the admin mode to which you refer? Also, how do we ensure "Local Conf mode" is off?

**Comment by MetaChuh** [comment]
@evanpetridis

not reproducible on notepad++ 7.6.6.

please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins if you update from version 7.5.9 or below.
if your issue still persists, and it is still of relevance, please feel free to file a new issue as easy to understand and reproducible as possible, with detailed examples of your exact path to recreate it.

thank you for your help and best regards.

-----
```
general notes:

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
(no extra account is needed, just use your github account to sign in)
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)
