### ISSUE TITLE
CSScriptNpp.x86.dll issue while starting notepad++

### ISSUE THREAD

**Issue by FabioCurti** [notepad-plus-plus/notepad-plus-plus#4484]
### Description of the Issue
After an update i found out that an error message is shown after launching Notepad++:

![2018-05-08 08_33_54-exception](https://user-images.githubusercontent.com/39079335/39741780-713bd2a8-529b-11e8-9015-ac0804fce687.png)

it's just an "Exeption" messagebox with the message "Unknown Exeption".
After this, Notepad++ starts correctly and it seems there are no problems.  

Looking at the .dll files in Notepad++ folder on my pc, i noticed that the last dll updated is the CSScriptNpp.x86.dll .

Removing it from the installation folder (C:\Program Files (x86)\Notepad++\plugins) the error message is not shown anymore.

### Steps to Reproduce the Issue
1. You must have the CSScriptNpp.x86.dll (version 1.7.8.0) installed
2. Launch Notepad++
3. The error happens

**Comment by dinkumoil** [comment]
1. If you want to report a bug in Notepad++ please also provide debugging informations. They are available via "Menu ? -> Debug Info...".
2. There is a newer version of the CS-Script plugin available (v1.7.9.0).
3. This is a bug in the CS-Script plugin and thus here is the wrong place for reporting it. Go instead to [this](https://github.com/oleg-shilo/cs-script.npp/issues) site.
