### ISSUE TITLE
Smart Highlighting Multi instance limited to intersection of visible lines when viewing cloned view

### ISSUE THREAD

**Issue by ghost** [notepad-plus-plus/notepad-plus-plus#4486]
### Description of the Issue

I want to use multi instance highlighting as I review a section of code that is listed together at the top of the document and then spread out in pieces in the rest of the document but the highlighting is not working as I thought it should
### Steps to Reproduce the Issue

1. Open a document that has been saved already.
2. right click on the tab and click "Clone to another View"
3. I then highlight my phrase and start to scroll down in the cloned view and as soon as the top instance of the phase is no longer visible in the cloned view, 

### Expected Behavior

I Expected to see the highlighting across original and cloned views not be affected by what is visible in the other.

### Actual Behavior

As I scroll down then the original view highlighting turns off on that instance as soon as the cloned view instance is out of sight.
This behavior does not repeat for views of unsaved documents, only ones that have been saved. 

### Debug Information

Notepad++ v7.5.5   (64-bit)
Build time : Feb 27 2018 - 21:50:06
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : ON
Local Conf mode : OFF
OS : Windows 7 (64-bit)
Plugins : DSpellCheck.dll mimeTools.dll NppConverter.dll 

![image](https://user-images.githubusercontent.com/8683446/39781299-044f48f6-52cc-11e8-8697-a2ef4ddb7566.png)

![image](https://user-images.githubusercontent.com/8683446/39781321-16bdf456-52cc-11e8-8551-307729c5476b.png)

**Comment by bfridkis** [comment]
I concur that highlighting in the original view highlights the same line in the clone as expected, but if the same line goes out of view in the original, the clone's line loses its highlighting.

**Comment by FRohde** [comment]
Bug is annoying when you want to use one tab for inspecting a class or long function and the other for searching for instantiations of the class/calls of the function in the same file.

**Comment by ArkadiuszMichalski** [comment]
This was fixed by https://github.com/notepad-plus-plus/notepad-plus-plus/pull/8905.
