### ISSUE TITLE
NPPM_DESTROYSCINTILLAHANDLE may lead to crash npp

### ISSUE THREAD

**Issue by ClaudiaFrank** [notepad-plus-plus/notepad-plus-plus#4487]
### Description of the Issue
When a plugin is using NPPM_CREATESCINTILLAHANDLE to get a valid buffer
and NPPM_DESTROYSCINTILLAHANDLE to destroy it, every next action which would request
a new buffer leads to a crash

### Steps to Reproduce the Issue

1. send NPPM_CREATESCINTILLAHANDLE
2. send NPPM_DESTROYSCINTILLAHANDLE
3. open a new empty document

### Expected Behavior
no crash

### Actual Behavior
crash

### Debug Information
Notepad++ v7.5.6   (64-bit)
Build time : Mar 19 2018 - 00:23:17
Path : D:\Tests\npp\756_64_with_pluginmanager\notepad++.exe
Admin mode : OFF
Local Conf mode : ON
OS : Windows 7 (64-bit)
Plugins : PluginManager.dll PythonScript.dll 

Simple python script to demonstrate it

sci = notepad.createScintilla()
notepad.destroyScintilla(sci)
notepad.new()

**Comment by MetaChuh** [comment]
please return to notepad++, update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins if you update from version 7.5.9 or below, and post a hello at the community.

thank you for your help and best regards.

**Comment by ClaudiaFrank** [comment]
This problem still exists on the latest, aka 7.6.6, version but I leave it to the community to decide whether
it is worth to fix or not.
