### ISSUE TITLE
Add bounty support on GitHub

### ISSUE THREAD

**Issue by einsteinsfool** [notepad-plus-plus/notepad-plus-plus#4488]
There are a lot of issues in this repo. Perhaps it would speed up resolving them if they had bounties.
Users could cash in for issues they want to be resolved the most. The more money people would give, the more likely it would be that someone fixes the issue.

Bounties can be integrated with GitHub (using Bountysource) as you can read [here](https://webapps.stackexchange.com/questions/84152/how-to-enable-bountysource-plugin-on-github-to-have-integration-with-issues).

**Comment by CookiePLMonster** [comment]
Wouldn't hurt to try, I guess! After all, if it backfires it could be easily revoked back.

**Comment by zwik** [comment]
Who will pay for it? Also looking trough the issues is a pain because there's not categorization of what kind of issues it actually is.

**Comment by einsteinsfool** [comment]
@zwik As I mentioned, users will. I'd pay for some issues to be resolved. Imo that's how the open source world should work. There are many outstanding projects but sometimes their development is slowed down because of lack of funding (which translates to time). Of course one can just donate to a project but imo it would be more convincing if people knew that their money will be given if a feature they want is implemented.

**Comment by MetaChuh** [comment]
@zwik 

nice idea, but notepad++ prefers help driven by enthusiasm and voluntarism.

thank you for your help and best regards.
