### ISSUE TITLE
Legibility in the find/replace dialog

### ISSUE THREAD

**Issue by Rosseiro** [notepad-plus-plus/notepad-plus-plus#449]
Hi, 
I love Notepad++ but it appears that it's a little more difficult to use the find/replace dialog as it was supposed to be. Specially for us getting old, reading the input field in that default (unchangeable, as far as I know) font is hard. Especially when we're typing a regex, sometimes I can't see if I typed that pipe in the right place. So my suggestion is: allow us to change that font in the "find" field to a more readable, monospace font. 

Also, even with the transparency, it's sometimes tedious to switch between the dialog and the main window. Other editors have a built-in find/replace dialog in the main interface, some even with a highlight-as-you-type feature.

Thanks!

**Comment by milipili** [comment]
It should be a fixed-width font anyway by default.

**Comment by DavidBailey100** [comment]
I wish this dialog would have explicit search up and search down buttons. Sure you can set the direction to 'up', but then that remains set and thus easily messes up subsequent searches.

**Comment by dail8859** [comment]
I'd even be ok with shift+enter or shift+"click search" to do a reverse search...although it's not a very intuitive solution.

**Comment by DaveyD** [comment]
I triple David's suggestion..... Would be a very useful feature

**Comment by alexhenzell** [comment]
@DavidBailey100
Just raised this issue (#506): Optional auto-reset of 'Find/Replace/Find in Files/Mark' settings
May be relevant to comment regarding 'up' direction

**Comment by h-h-h-h** [comment]
@Rosseiro:
> allow us to change that font in the "find" field to a more readable, monospace font.

Issue https://github.com/notepad-plus-plus/notepad-plus-plus/issues/563 adds some suggestions as light gray text background.
>Other editors have a built-in find/replace dialog in the main interface, some even with a highlight-as-you-type feature.

Actually, there is a feature like this. You make it appear by hitting <kbd>Ctrl</kbd>+<kbd>Alt</kbd>+<kbd>I</kbd>. There are additional suggestions for this feature in issue https://github.com/notepad-plus-plus/notepad-plus-plus/issues/811.

@DavidBailey100:
> I wish this dialog would have explicit search up and search down buttons. Sure you can set the direction to 'up', but then that remains set and thus easily messes up subsequent searches.

Not a bad idea! What about this:
```
+-----------+ +---+
| Find Next | | ^ |
+-----------+ +---+
+-----------------+
|      Count      |
+-----------------+
```

---
Other issues discussing the appearance of the find-and-replace dialog: https://github.com/notepad-plus-plus/notepad-plus-plus/issues/452 ([comment](https://github.com/notepad-plus-plus/notepad-plus-plus/issues/452#issuecomment-128483383)), https://github.com/notepad-plus-plus/notepad-plus-plus/issues/722, https://github.com/notepad-plus-plus/notepad-plus-plus/issues/773, https://github.com/notepad-plus-plus/notepad-plus-plus/issues/776, https://github.com/notepad-plus-plus/notepad-plus-plus/issues/778

**Comment by dg9ngf** [comment]
Could the find/replace input fields just use the default editor font? So it looks consistent with no additional configuration.

**Comment by h-h-h-h** [comment]
> @dg9ngf:
Could the find/replace input fields just use the default editor font? So it looks consistent with no additional configuration.

I agree; a monospace font is what's suggested in the first two comments and in issue https://github.com/notepad-plus-plus/notepad-plus-plus/issues/563, too, although I would make it smaller than the editor font.

**Comment by dg9ngf** [comment]
Not smaller. The editor font I chose is good the way it is.

**Comment by h-h-h-h** [comment]
I only meant there should be an option to let it appear different than the editor font. I would use that option.

**Comment by dg9ngf** [comment]
Why not.

**Comment by MetaChuh** [comment]
we are closing this issue due to its age and multiple newer notepad++ versions since it was filed.

please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html).
if your issue persists, and it is still of relevance to you, please feel free to file a new issue.

thank you for your help and best regards.

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
```
[<kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd>](https://notepad-plus-plus.org/community/)
