### ISSUE TITLE
When time zone is changed in Windows 10, Notepad++ says that all open files have been modified

### ISSUE THREAD

**Issue by kripper** [notepad-plus-plus/notepad-plus-plus#4491]
### Description of the Issue

When time zone is changed in Windows 10, Notepad++ says that all open files have been modified

### Steps to Reproduce the Issue

1.  Open files
2.  Change timezone

### Expected Behavior

NotePad++ should NOT ask if the file shuold be reloaded.

### Actual Behavior

Notepad++ offers reloading all open files.

**Comment by SinghRajenM** [comment]
Duplicate of #3969 and #215.

**Comment by CookiePLMonster** [comment]
I got a proper-ish fix for that, will be submitting a PR soon.
