### ISSUE TITLE
"Search/replace" for german special character ß not correctly working

### ISSUE THREAD

**Issue by schultz-it-solutions** [notepad-plus-plus/notepad-plus-plus#4496]
### Description of the Issue
When trying to replace the  ß  with "& s z l i g ;"  in a html-document, the "search" function finds BOTH the "ss" and the "ß". This is wrong from a gramatical point of view, as "not every ss is to be replaced by ß"

### Steps to Reproduce the Issue
1) create a new empty document
2) use the word  " ausschließlich"  (exclusively) for example. 
3) search for "ß"

### Expected Behavior
only the "actual" ß should be found, not the first "ss"

### Actual Behavior
the first "ss" is "found", and also the actual "ß" 

### Debug Information
Notepad++ v7.5.4   (64-bit)
Build time : Jan  1 2018 - 01:50:29
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 7 (64-bit)
Plugins : DSpellCheck.dll mimeTools.dll NppConverter.dll 

Kind regards
Ruediger Schultz, Schultz IT Solutions

PS: I really like notepad++ it is a wonderful product!!!

**Comment by ClaudiaFrank** [comment]
I assume you are using some unicode, probably utf8 (?), encoding, if so, temporary workaround check **Match case** box.

**Comment by tcmaps** [comment]
btw.: Does not affect ANSI but UTF-8 w/ or w/o BOM

**Comment by MetaChuh** [comment]
@schultz-it-solutions 

scintilla follows the unicode standard for locale independent case folding, to do case insensitive searching.
this standard specifies that `ß` matches `ss` when searching/replacing case insensitive.

your currently available choices are:
* use **case sensitive** when searching/replacing, which will correctly identify any `ß`.
* use **regex** search, as it uses another engine. (boost)
* file a feature request at the [**scintilla project feature-request tracker**](https://sourceforge.net/p/scintilla/feature-requests/).
* use an editor that is not scintilla based.

many thanks and best regards.

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
(no extra account is needed, just use your github account to sign in)
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)
