### ISSUE TITLE
The UI interface is too ugly. Can we improve it.

### ISSUE THREAD

**Issue by alongL** [notepad-plus-plus/notepad-plus-plus#4502]
I think the UI interface is too ugly, although it is open source software.
Does anyone think UI should be improved?

**Comment by DavidHansen-0x454d43** [comment]
@alongL, if you search the existing issues you will find other people thinking the UI should be improved: #622 #972 #3828 Also, there is [this long thread](https://notepad-plus-plus.org/community/topic/250/it-s-time-for-ui-update/81) over on the support forums. 

I'd recommend adding your suggestions to the thread on the support forums, or even better, implement you improvement and submit a pull request.

**Comment by sasumner** [comment]
I second the opinion: "implement your improvement and submit a pull request"

**Comment by alongL** [comment]
I am thinking about this. It will take some time.




------------------ 原始邮件 ------------------
发件人: "sasumner"<notifications@github.com>;
发送时间: 2018年5月17日(星期四) 上午7:58
收件人: "notepad-plus-plus/notepad-plus-plus"<notepad-plus-plus@noreply.github.com>;
抄送: "along"<v6543210@gmail.com>; "Mention"<mention@noreply.github.com>; 
主题: Re: [notepad-plus-plus/notepad-plus-plus] The UI interface is toougly. Can we improve it. (#4502)




I second the opinion: "implement your improvement and submit a pull request"

**Comment by MetaChuh** [comment]
@alongL 

take your time, no hurry.
in the meantime we like it the way it is.

thank you for your help and best regards.

**Comment by ikoshura** [comment]
I made a Fluent UI theme for Notepad++, I used the VS Code color scheme along with the Windows 11 Mica effect. You can take a look at my theme over here: https://github.com/ikoshura/Fluent-Npp

![image](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/100127946/d4e7ce9a-dc93-4506-a274-7e1c20d671b4)
