### ISSUE TITLE
Javascript highlight bug with commented brackets

### ISSUE THREAD

**Issue by XCanG** [notepad-plus-plus/notepad-plus-plus#4504]
### Description of the Issue
In javascript files Notepad++ wrongly recognize closing brackets inside comments, so that they broke all highlighting after it, take a look for screenshot:
![](https://a.safe.moe/pfg9pru.png)

### Expected Behavior
Notepad++ ignore commented closed brackets as actual closed brackets.

### Actual Behavior
Notepad++ think what commented bracket close function and futher mark after it shifted and looks broken.

### Debug Information
Notepad++ v7.5.6, 32 bit
Windows 10

**Comment by ArkadiuszMichalski** [comment]
@XCanG Do you still have this problem in latest Notepad++ version? If yest then please update description (put some code as example).

**Comment by XCanG** [comment]
@ArkadiuszMichalski hm, there was screenshot, HTML code for image is still there, but it lead to dead end now.
I tried to reproduce this issue at current version, but was unable with several tests. It may be fixed or I didn't repeat it 1 to 1.

This issue is stale, so it's better to just close and if something will happen, then just create new one.
