### ISSUE TITLE
XML end tags display incorrectly in "Text Direction RTL" mode of NP++

### ISSUE THREAD

**Issue by rdrolfegh** [notepad-plus-plus/notepad-plus-plus#4506]
### Description of the Issue

The following pertains to this line of XML:
`<para paraID="10"><language langCode="000" emphasize="no">15673<nb/>102</language></para>`
And how it is displayed in Text Direction RTL.

### Steps to Reproduce the Issue

1. Insert above text in NP++ while in Text Direction LTR
2. Set Language to "XML"
3. Change to Text Direction RTL

### Expected Behavior

Once the Direction is RTL is should display as follows:
`<para/><language/>102</nb>15673<"no"=emphasize "000"=langCode language><"10"=paraID para>`

### Actual Behavior

Instead it displays:
`<language></para/>102</nb>15673<"no"=emphasize "000"=langCode language><"10"=paraID para>`

Notice the language and para end tags are 
1. displayed in the wrong order,
2. the end para tag has two (2) slashes `</para/>` ,
3. the end language tag has no slash at all `<language>`. 

Also notice that when one puts the cursor in the beginning `<para>` tag, the line is highlighted at the end at where the `<para/>` should be displayed
![image](https://user-images.githubusercontent.com/39412492/40256715-a59e5740-5aa8-11e8-8563-6d31226f058f.png)

and when you place the cursor in the beginning `<language>` tag, the line is highlighted at the end where the `<language/>` tag should be.

![image](https://user-images.githubusercontent.com/39412492/40256758-c587ec74-5aa8-11e8-8267-e1e44800e9ea.png)

Everything else is correct.

**Comment by MetaChuh** [comment]
@rdrolfegh 

this is a known ltr-rtl limitation of the currently implemented scintilla component.
unfortunately scintilla is an external project, so you will have to file your issue at the [<kbd>scintilla bug tracker</kbd>](https://sourceforge.net/p/scintilla/bugs/).
there is nothing we can currently do at the notepad++ part.
we apologise for that.

-----
```
general notes:

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if a related topics exists. you are welcome to post at either an eventually similar
topic, or create a new topic at Help Wanted or General Discussion.
```
[<kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd>](https://notepad-plus-plus.org/community/)
