### ISSUE TITLE
"cut" problem

### ISSUE THREAD

**Issue by uniquepengpeng** [notepad-plus-plus/notepad-plus-plus#451]
Hi:
    In more recent versions, about notepad++ I encountered following problem:select a line,cut it("ctrl + x") .and the item entrys system clipboard .but it's empty occasionally ! i must undo it and do it again,and it's ok.(current version:v6.6.9 win7x86)

**Comment by donho** [comment]
I believe this issue has been fixed since long time ago.
Update your Notepad++ to the latest version (v7.6.6).
If the issue persists, please create a new issue for it.
Thank you.
