### ISSUE TITLE
In the search results area, I double-click on the search result and it will jump to the text area. However, I don’t know which row was used in the search results area.

### ISSUE THREAD

**Issue by fengchen-github** [notepad-plus-plus/notepad-plus-plus#4510]
In the search results area, I double-click on the search result and it will jump to the text area. However, I don’t know which row was used in the search results area.

### Description of the Issue

The first step below
![ntp1](https://user-images.githubusercontent.com/16919103/40289531-80bf3760-5ceb-11e8-8740-a374ce664029.png)

The second step below
![ntp2](https://user-images.githubusercontent.com/16919103/40289532-80f12cd4-5ceb-11e8-8e7b-2321e0b21398.png)

### Steps to Reproduce the Issue

1. In the search results area
2.  I double-click on the search result and it will jump to the text area
3.  However, I don’t know which row was used in the search results area.

### Expected Behavior

After the second step, the search result area still shows which row is selected
### Actual Behavior

After the second step, I do not know which line is selected in the search result area
### Debug Information

nothing

nothing

**Comment by sasumner** [comment]
Agreed that this is annoying.  And it is an easy enhancement:  In FindReplaceDlg.cpp there are two references to SCI_SETCARETLINEVISIBLE.  If these are changed to SCI_SETCARETLINEVISIBLEALWAYS then it provides your "Expected Behavior".

**Comment by fengchen-github** [comment]
I don't have a build environment here. Will the next version fix this problem?

**Comment by Yaron10** [comment]
@sasumner,

:+1: 
Just playing a bit with `SCI_SETCARETLINEVISIBLEALWAYS`, I think it should be *added* to  `SCI_SETCARETLINEVISIBLE` and not replace it.

I also think it's an important enhancement.

@fengchen-github,

> Will the next version fix this problem?

This is up to the developer.

**Comment by sasumner** [comment]
@Yaron10 
My experimentation with the source showed that replacement was fine, but obviously adding it does no harm.  In fact, currently I run unmodified N++ with a Pythonscript that can only add the SCI_SETCARETLINEVISIBLEALWAYS call.

**Comment by Yaron10** [comment]
@sasumner,

Replacing

`_pFinder->_scintView.execute(SCI_SETCARETLINEVISIBLE, 1);`
and
`pFinder->_scintView.execute(SCI_SETCARETLINEVISIBLE, 1);`

with

`_pFinder->_scintView.execute(SCI_SETCARETLINEVISIBLEALWAYS, 1);`
and
`pFinder->_scintView.execute(SCI_SETCARETLINEVISIBLEALWAYS, 1);`

results in the current line (in the Find Results window) not being highlighted at all.

Did you do anything different?
Can you retest it?

Thanks.

**Comment by sasumner** [comment]
@Yaron10, It was a bit of time ago that I tried it; perhaps my memory is faulty.  If you are trying it now and it needs both, that is good data for anyone really attempting to add this feature enhancement in a PR--you?  Unfortunately I no longer have a build environment set up to re-test it.

**Comment by Yaron10** [comment]
> It was a bit of time ago that I tried it; perhaps my memory is faulty.

No problem. I happens to all of us.

> in a PR--you?

Not me, sorry. You? :)

Thanks.

**Comment by sasumner** [comment]
@Yaron10 
>You? :)
Without a build environment, clearly the answer to that is No.

**Comment by Yaron10** [comment]
@fengchen-github,

You can open a thread in [NPP Forum](https://notepad-plus-plus.org/community/).
@sasumner could help you fix the problem with a Python Script.

**Comment by cmeriaux** [comment]
as a matter fact, you should replace SCI_SETCARETLINEVISIBLE with SCI_SETCARETLINEVISIBLEALWAYS.
You must add a new line 
`XXX->_scintView.execute(SCI_SETCARETLINEVISIBLEALWAYS, true);`
Checkout scintilla help : https://www.scintilla.org/ScintillaDoc.html#SCI_GETCARETLINEFRAME 
I fixed it in my branch. I'll do a pull request ASAP.

**Comment by Yaron10** [comment]
@cmeriaux,

> as a matter fact, you should replace SCI_SETCARETLINEVISIBLE with SCI_SETCARETLINEVISIBLEALWAYS.
You must add a new line

I don't understand your statement.
You add a new line and *do not replace* `SCI_SETCARETLINEVISIBLE`.

Thanks for the PR.

**Comment by cmeriaux** [comment]
@Yaron10 
`I don't understand your statement.`
Sorry I did a typo that lead to a big misunderstanding. I modified my comment.

**Comment by Yaron10** [comment]
@cmeriaux,

Thanks for the clarification.
***
The Find Dialog is far too large IMO. I often need to move it to different sides in order to see various parts of the document.

Would you be interested in implementing an option to dock the Dialog and submit a PR?
I can help with adapting the elements it to a docked window. 

I've already implemented a much smaller Dialog (not docked) with a `Show More/Less` option: show/hide the `Search Mode` and `Transparency` area.

Could you enable Issues in your fork? We can further discuss it there.

Thank you.

**Comment by cmeriaux** [comment]
@Yaron10 sorry but I'm not interested. My skills in Windows API and C++ are too limited.
moreover, It's very hard to have a PR accepted and integrated, so it's not motivating.
Checkout plugins npp Gtags https://github.com/pnedev/nppgtags. Its front end might be interesting for you.
Sorry.

**Comment by Yaron10** [comment]
@cmeriaux,

> My skills in Windows API and C++ are too limited.

Unfortunately, so are mine.

Thank you.

Best regards.

**Comment by sasumner** [comment]
@Yaron10 @cmeriaux 
My C++ windows programming skill is up to most tasks, but it's the "very hard to have a PR accepted" thing which brings my desire to a dead stop...

**Comment by Yaron10** [comment]
@sasumner,

:+1: :)

**Comment by fengchen-github** [comment]
@cmeriaux 

> nightly build is available here : https://ci.appveyor.com/project/cmeriaux/notepad-plus-plus/build/1.0.476/job/nqi1p1r6a8cgewx8/artifacts

![npp](https://user-images.githubusercontent.com/16919103/40600588-939bb8e2-6284-11e8-8fda-15287c7eb0bc.png)

Cannot find the requested object
I downloaded and tried it, but reported the above error

**Comment by cmeriaux** [comment]
Don't use dll of artifacts because it's not officially signed with npp key. Just use the exe of the artifacts.

**Comment by fengchen-github** [comment]
@cmeriaux 
Thank you.
Replace the exe file just fine, and solved my problem.
In addition, can you compile a 64 bit?

**Comment by cmeriaux** [comment]
It's already available. On the appveyor link, there is a job selection area. Select the 64bit release job.

**Comment by fengchen-github** [comment]
@cmeriaux Yes, thank you very much
