### ISSUE TITLE
Find dialog only remembers the last 10 search terms, can we have more?

### ISSUE THREAD

**Issue by davidheff** [notepad-plus-plus/notepad-plus-plus#4511]
The *Find what* text box on the **Find** dialog remembers the last 10 search terms.  This is very useful but I frequently find that 10 is insufficient.

It's not uncommon to spend some time crafting a complex regex.  Perhaps then you are distracted by some other task.  When you return to continue searching with this regex, it's dropped of the bottom of the list of remembered search terms.

Could the number of remembered items be increased?

**Comment by sasumner** [comment]
I understand that this is a feature request and that you'd probably like to see a nice "preference" setting for the # of remembered search terms.  At the moment the known workaround is to change the nbMaxFindHistoryFind value in config.xml.

**Comment by davidheff** [comment]
Thanks. That helps me solve my problem.

I guess more broadly that this would be a useful feature to have discoverable UI for. At least in my opinion that is so.

**Comment by sasumner** [comment]
@davidheff You are not alone.  There is probably already an issue open about this; I didn't search.

**Comment by vlakoff** [comment]
Refs #323, #2944 and #3774.

**Comment by davidheff** [comment]
Thanks for those other issues. I had tried to search for existing issues but clearly didn't find the right search terms.

And yes, I've just discovered that modifications to config.xml are not persistent, so that is no workaround.

**Comment by vlakoff** [comment]
That may be because Notepad++ is precisely using the config file you are editing, so when you close Notepad++ it overwrites the file.

Make a copy of the file and edit this copy, then close Notepad++ and replace the main file with the copy.

**Comment by Suncatcher** [comment]
any progress with that?

**Comment by sasumner** [comment]
>I've just discovered that modifications to config.xml are not persistent, so that is no workaround.

>That may be because Notepad++ is precisely using the config file you are editing, so when you close Notepad++ it overwrites the file.

Correct.  You need to edit `config.xml` with Notepad++ not running.

It works; you can currently get these maximums (reflected [HERE](https://github.com/notepad-plus-plus/notepad-plus-plus/blob/949a777ee58895797da8117b736135a7a906b3e8/PowerEditor/src/Parameters.h#L944) in the source code) by setting the values in config.xml:

```
nbMaxFindHistoryFind -> 30
nbMaxFindHistoryReplace -> 30
nbMaxFindHistoryFilter -> 20
nbMaxFindHistoryPath -> 30
```

**Comment by pryrt** [comment]
@sasumner: since there are (and has been) 30 available rather than the 10, shouldn't this issue and #2944 have been closed? Unless you had intentionally left these open, because the max-30 that's available is less than the suggested max-100 from #2944

**Comment by sasumner** [comment]
@pryrt On this one, I left it open (I'm supposing) because it wouldn't bother me personally if there was a higher number, but I don't know the original intent of the maximum values.  Perhaps @donho will comment and can close if the current situation is satisfactory.

**Comment by donho** [comment]
The current max values are reasonable to me. For the power users who need max values, they can always modify config.xml.

**Comment by sasumner** [comment]
>The current max values are reasonable to me. For the power users who need max values, they can always modify config.xml.

So I think there are users that want more than the `config.xml` values allow, but it doesn't bother me not to support that.

**Comment by donho** [comment]
@sasumner 
I do understand your point. However, my goal is always to keep settings as simple/clean as possible.

**Comment by mere-human** [comment]
Maybe, Notepad++ should have the `Advanced` tab in Preferences? It even could be invisible by default but can be enabled using some rituals.
For example, do you know how to enable developer mode in Android?
> To enable developer options, tap the Build Number option 7 times.
