### ISSUE TITLE
Find (and remove) duplicated rows

### ISSUE THREAD

**Issue by magol** [notepad-plus-plus/notepad-plus-plus#4512]
### Description of the Issue
Please add a feature to find (and remove) duplicated rows in a text file.

**Example**
If I have following text:

> A
> B
> A
> C
> B

I want the feature to remove all duplicated lines, so the text file become as following:
> A
> B
> C

Maybe it can be settings if it should ignore differences in spacing.

**Comment by sasumner** [comment]
Duplicate of #3329 and I'm sure others.  Please search for existing issues before creating new ones.

**Comment by magol** [comment]
I searched if there were others with the same idea, and was surprised I could not find any. I must have been blind.
