### ISSUE TITLE
CTRl+TAB

### ISSUE THREAD

**Issue by Daijobou** [notepad-plus-plus/notepad-plus-plus#4514]
Here are different issues with CTRL+TAB

1. I can't cancel it (like with CTRL+ESC). I must select now a file.

2. The order of files in CTRL+TAB should be the order of horizintal tabs. Actual its very random.

**Comment by SinghRajenM** [comment]
> The order of files in CTRL+TAB should be the order of horizintal tabs. Actual its very random.

Did you try disabling MRU behavior?

![image](https://user-images.githubusercontent.com/14791461/40321362-68fc197a-5d4c-11e8-8f0b-b27baabe8bae.png)

**Comment by Daijobou** [comment]
Ah thanks, that fixed point 2.

**Comment by SinghRajenM** [comment]
About is point 1. I am just trying to understand what is expected here. 
As soon you leave <kbd>Ctrl</kbd>, it will just open the file which was highlighted in MRU list.

If you don't like this behavior, you can disable complete doc switcher feature (refer previous screenshot). After disabling if you use <kbd>Ctrl</kbd>+<kbd>Tab</kbd> or <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>Tab</kbd>, then it will change the tab (forward and backward).

If you don't like this also, you have an another option. Just hold the <kbd>Ctrl</kbd> key and scroll the mouse (both up and down) on tabs.

In both the above cases you can see tab switching is happening. Could you explain more what else is expected?

**Comment by VVelda** [comment]
It is standard behaviour of Ctrl+Tab for switching in MRU order across apps. As is Alt+Tab.
For in-order switching is Ctrl + PgDn/PgUp key shortcut, again, standard behaviour across programs.
You can cancel it by Ctrl + shift Tab (reverse order) – again standard behaviour.
