### ISSUE TITLE
Don't delete dragged text when dropped into another app

### ISSUE THREAD

**Issue by h-h-h-h** [notepad-plus-plus/notepad-plus-plus#4517]
### Description of the Issue

I often want to get parts of the text of a buffer into other applications, e.g., into the browser to perform a Google search with it. Drag and drop is great for that, especially when the windows are arranged side by side via the Windows 10 snap feature. However, when you copy the text over into the other application via drag and drop, the text will be deleted in the Notepad++ buffer. This is contrary to the expectations of a user!

### Steps to Reproduce the Issue

1. Select text in buffer.
2. Drag-and-drop it into the search bar of a browser window, e.g. Firefox.

### Expected Behavior

The Notepad++ buffer should remain unchanged.

### Actual Behavior

The selected text is replaced with an empty string.

### Debug Information

Notepad++ v7.5.6   (32-bit)
Build time : Mar 19 2018 - 00:26:59
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10 (64-bit)
Plugins : DSpellCheck.dll ElasticTabstops.dll JSLintNpp.dll MenuIcons.dll mimeTools.dll NppConverter.dll NppExec.dll NppExport.dll NppFTP.dll NppScripts.dll NppTextFX.dll PluginManager.dll

**Comment by sasumner** [comment]
I don't see this issue in 7.5.6 ; for me the text remains in Notepad++ and only a copy is put in the address bar of (in my case, Chrome).  Perhaps a clue would be in the "Debug Information" you didn't supply.

**Comment by h-h-h-h** [comment]
> Perhaps a clue would be in the "Debug Information" you didn't supply.

I'm sorry. I didn't know what that meant. Just found it in the `?` menu and edited the previous comment.

---

There is different behavior as I just experienced:

- When I drop the text into the Firefox search bar (that's *just* for searching, not an omnibar!), the text in Notepad++ is deleted.
- When I drop the text into the GitHub comment `<textarea>` where I typed *this* text in you're reading just now, the text in Notepad++ is not deleted.

**Comment by zufuliu** [comment]
See https://docs.microsoft.com/en-us/windows/desktop/api/oleidl/nf-oleidl-idroptarget-dragenter

Hold on <kbd>Ctrl</kbd> will copy the selected text, the default behavior is move.

Relevant code is in `DWORD ScintillaWin::EffectFromState(DWORD grfKeyState)`.

**Comment by MetaChuh** [comment]
please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins if you update from version 7.5.9 or below.
if your issue still persists, and it is still of relevance, please feel free to file a new issue as easy to understand and reproducible as possible.

thank you for your help and best regards.
