### ISSUE TITLE
Saved Find & Replace strings

### ISSUE THREAD

**Issue by aaaxx** [notepad-plus-plus/notepad-plus-plus#452]
This would be really useful. Just a flyout menu somewhere with a list of saved Find & Replace pairs and a "Save Search" option which lets you name it.

It should work with all search functions (Find | Replace | Find in Files | Mark) in such a way that it saves all available fields and settings for the active search function, and when loaded in a different search function it loads only the applicable ones.

**Comment by milipili** [comment]
From #564:

> Please enable to save the text of the search and replace textboxes of the search-and-replace dialog as named pairs that you can view and select again at a later time. The options of check boxes and radio buttons should also be saved for a named pair. (A pair would be usable for search-only, too.)

> This feature would make Notepad++ much more useful with regard to developing a chain of regular expressions that you have to apply, especially in combination with this feature: #563 .

**Comment by h-h-h-h** [comment]
It would be helpful to be able to group the named pairs. You could, e.g., type \ while giving the name. Then a top menu is created and a subitem that you can click. If that is possible, there could be a right-aligned x to delete the item. Of course an item would be updated when you choose it, edit it and click "Save" that could reside in the top menu for named pairs.

**Comment by h-h-h-h** [comment]
I think it will help and accelerate delelopment if we do some designing here already. I have created a design as text. It also addresses issue https://github.com/notepad-plus-plus/notepad-plus-plus/issues/563.
![design](https://cloud.githubusercontent.com/assets/13482553/9121567/4abb141c-3c83-11e5-9a09-e634a14a8b98.png)
If someone wants to change it, here's the source code. Use font *Consolas.*
```
╔═════════════════════════════════════════════════════════════════════════════════════════════════════╗
║                           Replace——Some replacements ► *Replacement two                             ║
╠═════════════════════════════════════════════════════════════════════════════════════════════════════╣
║ (Tabs)                                                 (* means edited)
║ [×] Multiline
║               ┌────────────────────────────────────────────────┐       ┌───────────┐
║    Find what: │ (?x)                                         ▼ │       │ Find Next │
║               │ (?<one>  # Group number one                    │       └───────────┘
║               │     (                                          │        (...)
║               │         \w{5}                                  │
║               │         \s*                                    │
║               │     )+                                         │
║               │ )                                              │
║               │ (?<two>  # Group number two                    │
║               │     (                                          │
║               │         \d+                                    │
║               │         \s+                                    │
║               │     )*                                         │
║               │ )                                              │ _____
║               └────────────────────────────────────────────────┘ │ ► │┌──────────────────────────┐
║               ┌────────────────────────────────────────────────┐ ‾‾‾‾‾│ Replace something    / Ш │
║ Replace with: │ $+{two}$+{one}                               ▼ │      │ Some replacements  ► / Ш │┌────────────────────────┐
║               │                                                │      │ Find something       / Ш ││ Replacement one    / Ш │
║               │                                                │      ├──────────────────────────┤│ Replacement two    / Ш │
║               │                                                │      │ Save                     ││ Replacement three  / Ш │
║               │                                                │      │ Save as...               │└────────────────────────┘
║               │                                                │      └──────────────────────────┘
║               │                                                │       (/ means pen symbol for renaming and moving)
║               │                                                │       (Ш means trashcan)
║               │                                                │
║               │                                                │
║               │                                                │
║               │                                                │
║               │                                                │
║               └────────────────────────────────────────────────┘
║               [×] Word wrap (replacement)
║
```

**Comment by MetaChuh** [comment]
we are closing this issue due to its age and multiple newer notepad++ versions since it was filed.

please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html).
if your issue persists, and it is still of relevance to you, please feel free to file a new issue.

thank you for your help and best regards.

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
```
[<kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd>](https://notepad-plus-plus.org/community/)
