### ISSUE TITLE
windows 10 blue screen

### ISSUE THREAD

**Issue by SteveSmales** [notepad-plus-plus/notepad-plus-plus#4523]
### Description of the Issue
after dicking around ive narrowed it down to this, thought it may have been (dont print line numbers but it wasnt)
- had a file with long sentences
- performed, edit->line operations->split lines
- DID NOT SAVE, (all went well finally when the doc was saved then printed)
- went to print as pdf
- new windows 10 pretty BSOD

the failing component was win32Kbase, (reported on BSOD)

windows 10 pro up to date as of today.

Regards
Steve
love notepad++

**Comment by MetaChuh** [comment]
this is not related to the notepad++ source code itself, sorry.

thank you for your help and best regards.

-----
```
general notes:

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
(no extra account is needed, just use your github account to sign in)
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)
