### ISSUE TITLE
Suggestion: Right-align line numbers in "find results"

### ISSUE THREAD

**Issue by Layarion** [notepad-plus-plus/notepad-plus-plus#4524]
https://i.imgur.com/8utYPwk.png please study this image I linked. The program on the left, is Notepad++, and the program on the right is EditPad Pro 7.6.4

I feel that EditPad Pro did it right. Not having the line number aligned makes them a distraction. If you think it'll be a problem for the general public, then add it as an option in the settings somewhere.

**Comment by sasumner** [comment]
A pretty good suggestion--I'd recommend implementation without cluttering the Preferences with an option--just always do it.

**Comment by Layarion** [comment]
I wonder if this was ever implemented, I haven't used notepad++ for these task in at least a year so I wouldn't know.

**Comment by alankilborn** [comment]
Implemented in 8.4.  See #11119.
Recommend CLOSURE of this item.
