### ISSUE TITLE
Multiple dialogs on Plugin Crash

### ISSUE THREAD

**Issue by CPerTheFirst** [notepad-plus-plus/notepad-plus-plus#4528]
### Description of the Issue
This is an old issue that many applications have had over the years. An application crashes and keeps generating dialogs until it runs out of resources to do so. If you close one of them, usually the top one, then it just opens another one. You usually have to kill the process to stop it.

In this case a plugin crashed, I think it was 'Compare Plugin 1.5.6'.
I believe the dialogs title was "Plugin Crashed" with an 'OK' button.

### Expected Behavior
1. Only one dialog should popup.
2. When you press 'OK' it should do something useful - like shutting down gracefully if possible.
3. When you restart Notepad++, it should remember all the tabs that you keep open.

### Actual Behavior
1. A plugin crashed and dialogs started cascading across my screen. The ones toward the end of the stack do not have any text displayed in them, because the app is running out of resources. If you close one of them, then another will automatically popup to take its place.
2. Stopped pressing 'OK' and used the task manager to kill the application.
3. Restarted Notepad++ and discovered that several tabs did not reappear. Some of them might have been notes that I did not bother to save to a named file - you've spoiled me with that feature.

### Debug Information
I do not know how to reproduce the issue.
I have fixed this same issue in the past by creating a static flag that is set when the dialog is created. If the dialogs flag is set, then do not create a second instance of the dialog.

**Comment by caesarchad** [comment]
I think Compare Plugin had updated to 2.0, Maybe you can just try to install this plugin in NotePadd++

**Comment by sasumner** [comment]
Given the nature of how the plugin architecture is done in Notepad++, I don't know that it is a fair request to say "N++ should always act gracefully when any bad plugin does bad things".  I mean, you CAN say it, and WANT it as a feature request, but...

>...notes that I did not bother to save to a named file - you've spoiled me with that feature
Bad idea to use this workflow...if you care about your data...(my opinion only!)

**Comment by MetaChuh** [comment]
for plugin questions, please contact the plugin author.

thank you for your help and best regards.
