### ISSUE TITLE
Switch to semantic versioning for 7.x

### ISSUE THREAD

**Issue by ariccio** [notepad-plus-plus/notepad-plus-plus#453]
For the 7.x milestone, maybe Notepad++ could switch to [Semantic Versioning](http://semver.org/)?

I find it easier to understand (and even GitHub recommends it!), so maybe it'd ease things a bit for users?

Thoughts?

**Comment by milipili** [comment]
I intended to really use semver from 7.x but I've to discuss of it with @donho since it requires a more fine-grained process to handle issues and PR.

**Comment by Croydon** [comment]
Semantic versioning would be really reasonable. I never understood the current version scheme.

**Comment by donho** [comment]
(Sigh) It means I cannot enjoy anymore to release funny version such as : 
https://notepad-plus-plus.org//news/notepad-666-friday-13th.html

From v6.8 Notepad++ will apply Semantic Versioning.
