### ISSUE TITLE
Find dialog: Add short key for button 'Find All in Current Document'

### ISSUE THREAD

**Issue by jannick0** [notepad-plus-plus/notepad-plus-plus#4531]
English version of npp 7.5.6: In the `Find` dialog there is no short key (displayed by underscoring the character in the string of the button `Find All in Current Document`) to be invoked together with ALT instead of clicking on the button.

Please add a short key such that, e.g. `ALT + d` invokes the search in the current document. I believe there is a short key in some locale of npp (other than English).

I hope I am not missing something trivial here to do it myself in some config.

Many thanks.

**Comment by sasumner** [comment]
You ARE missing something.  :)

Here's what I do:  edit .\\localization\\english_customizable.xml and put `&amp;` just before the desired character in the "Find All In Current Document" string (or change the string to something else entirely if you want--but the important part is to put the `&amp;` in.  Then, in Preferences -> General -> Localization, set it to English (customizable).

**Comment by jannick0** [comment]
@sasumner Many thanks for this.

Probably beneficial to add this to the standard English configuration like for other languages (see PR #4533).

**Comment by sasumner** [comment]
So I really don't know the history on this, but I presume at one time some but not all keys were given an "alt" shortcut in the Find family of tabs.  Then later when the ability to change the text and/or add "alt" key combinations at the "user" level came into existence (okay, you have to edit a file...), having the developers pick and maintain all of these (across many different languages) basically dropped to zero importance level.

**Comment by jannick0** [comment]
Understand. Let's see if the PR comes thru.

**Comment by donho** [comment]
Will be in the next release
