### ISSUE TITLE
txt2tags? Txt2tags?

### ISSUE THREAD

**Issue by pdache** [notepad-plus-plus/notepad-plus-plus#4538]
### Description of the Issue

The first letter of all languages is uppercase. But txt2tags is a lower case letter.
Could not the first spelling of txt2tags be in upper case in the language setting?
### Steps to Reproduce the Issue

1.  Run Notepad++.
2.  Enter the T field of the language field.
3.  Make sure that the first letter of txt2tags is lowercase.

### Expected Behavior

Want Txt2tags for consistency.
### Actual Behavior

txt2tags

**Comment by wogns7534** [comment]
I am curious about this too. Which is right?

**Comment by ArkadiuszMichalski** [comment]
Probably txt2tags:
https://txt2tags.org/ << oficial page.
https://en.wikipedia.org/wiki/Txt2tags << funny, URL has Txt2tags, but content use txt2tags.
