### ISSUE TITLE
Bash syntax highlighting not applied on startup

### ISSUE THREAD

**Issue by svaccari** [notepad-plus-plus/notepad-plus-plus#4539]
### Description of the Issue

Bash syntax highlighting not applied on startup, or even on "Reload from disk"

### Steps to Reproduce the Issue

1. create or load a bash script ("test.sh")
2. close Notepad++
3. open Notepad++

### How to fix the issue

Close the file and open it again (by menu or drag&drop)

### Expected Behavior

Text should be colored...

### Actual Behavior

Text is all the same color

### Debug Information

Notepad++ v7.5.6   (32-bit)
Build time : Mar 19 2018 - 00:26:59
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10 (64-bit)
Plugins : DSpellCheck.dll HTMLTag_unicode.dll JSLintNpp.dll JSMinNPP.dll mimeTools.dll NppColumnSort.dll NppConverter.dll NppExport.dll NppFTP.dll PluginManager.dll SpellChecker.dll XMLTools.dll

**Comment by CookiePLMonster** [comment]
Notepad++ doesn't have syntax colouring for Bash. You are welcome to add one yourself.

**Comment by CookiePLMonster** [comment]
Unable to reproduce -- n++ correctly sets this file to Unix script file and performs syntax highlighting.

**Comment by svaccari** [comment]
"Unix script file" and "bash" are synonyms for me. Syntax highlighting is not applied if file has ".sh" extension

**Comment by CookiePLMonster** [comment]
Well, I have tested it and got syntax highlighting. It may not be complete, but it's there.

**Comment by svaccari** [comment]
![test](https://user-images.githubusercontent.com/7923589/40833709-fa818d68-658e-11e8-8ecb-2cc7e1f52fd2.gif)

**Comment by ArkadiuszMichalski** [comment]
Also for me no problem, above code got syntax highlighting in Notepad++ 7.9 RC (when reload file or restart NPP).
@sasumner maybe close and reopen if autor still have this problem and give more detail?

**Comment by svaccari** [comment]
I can close the issue, no problems with build:

Notepad++ v7.8.9   (32-bit)
Build time : Jul 15 2020 - 20:26:50
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS Name : Windows 10 Enterprise (64-bit) 
OS Version : 1903
OS Build : 18362.1082
Current ANSI codepage : 1252
Plugins : HexEditor.dll HTMLTag_unicode.dll JSLintNpp.dll JSMinNPP.dll mimeTools.dll NppConverter.dll NppExport.dll NPPJSONViewer.dll NppXmlTreeviewPlugin.dll XMLTools.dll
