### ISSUE TITLE
Homepage Language select Issues

### ISSUE THREAD

**Issue by Hyeon9mak** [notepad-plus-plus/notepad-plus-plus#4545]
### Description of the Issue

On the Notepad++ homepage, If select a language other than English and move the menu,
get back to English again.
same problem on every language other than English.

### Steps to Reproduce the Issue

1. On the homepage, select a language (other than English).
2. and select any left side menu
3. then homepage get back to English again.

### Expected Behavior

continue to choose language without going back to English.

### Debug Information

recorded the problem page and uploaded it on YouTube.
https://youtu.be/cbPocqpmW98
https://youtu.be/_t6GGiiYv3E

**Comment by wogns7534** [comment]
There is a big problem on the homepage. This seems to require resolution.

**Comment by Ekopalypse** [comment]
Can be closed, [new homepage](https://notepad-plus-plus.org) doesn't offer different languages anymore
