### ISSUE TITLE
Homepage [Korean] Language Additional requests

### ISSUE THREAD

**Issue by Hyeon9mak** [notepad-plus-plus/notepad-plus-plus#4547]
# Notepad++ Korean language Additional requests
![2018-06-04 2 11 15](https://user-images.githubusercontent.com/37354145/40899908-2a58bbd4-6804-11e8-985a-f9e0044e7b8b.png)

I did were translated most of the pages & menu.
(References to French and Chinese language pages)

The translation request page is total 12 pages :
A, B, C, D, E, F, FF, G, H, I, II, J

## A - Home
![homepage](https://user-images.githubusercontent.com/37354145/40901622-00d9ba62-680c-11e8-9c7c-91e5796de260.png)

### A_1. 
홈화면
다운로드
뉴스
기능구성
리소스
기여
기부
커뮤니티
기여해주신분들
참고링크

##### Notepad++는?
Notepad++는 다양한 언어를 지원하는 무료 (“언론의자유”나 “공짜맥주”처럼) 소스코드 편집기이자 메모장을 대체하는 프로그램입니다. 마이크로소프트 윈도우 환경에서 실행되는 Notepad++을 사용하는 동안 GPL라이센스가 적용됩니다.

Notepad++ 는 강력한 편집구성요소인 Scintilla를 기반으로하여 C++을 통해 개발 되었으며, 더 빠른 실행속도와 가벼운 프로그램이 되기 위해 Win32 API와 STL만을 이용해 제작되었습니다.
Notepad++는 사용자의 편의성을 잃지 않고 가능한 많은 루틴을 최적화함으로서 세계의 이산화탄소 배출을 줄이기 위해 노력하고 있습니다. CPU의 사용량이 적을 땐, PC가 자동으로 종료되게 하고 전력 소비량을 줄여 친환경적 환경을 조성하는데 도움이 될 수 있습니다.

### A_3.
Notepad++를 즐겨주길 바랍니다 :)

### A_4.
다른언어 보기

### A_5.
News : 뉴스
more News : 다른뉴스 보기

## B - download
![download](https://user-images.githubusercontent.com/37354145/40901887-034a6458-680d-11e8-8e8c-ff29f86f6aa0.png)

### B_1.
download : 다운로드
* Current Version : 현재 버전
* All versions : 모든 버전들

### B_2.
Home > download > v7.5.6 - Current Version
: 홈화면 > 다운로드 > v7.5.6 - 현재 버전

## C - news
![news](https://user-images.githubusercontent.com/37354145/40902069-9609732e-680d-11e8-93c2-c372efde4ea8.png)

### C_1.
news : 뉴스

### C_2.
최근 뉴스

### C_3.
Home > News
: 홈화면 > 뉴스

## D - Features
![features](https://user-images.githubusercontent.com/37354145/40902142-eb055c26-680d-11e8-889f-0b6f76950dec.png)

### D_1.
features : 기능구성
* Document Map : 문서 맵
* Function List : 함수 목록보기
* Multi-editing : 다중 편집기능
* Column Mode Editing : 다중열 편집기능
* Ghost Typing : 고스트 타이핑

### D_2.
기능구성
* 구문 강조 및 접기
* 사용자 정의 구문 강조  및 접기
* PCRE (Perl 호환 정규식) 검색 / 바꾸기
* 완벽하게 사용자 정의 가능한 GUI : 미니 버튼, 닫기 버튼이있는 탭, 다중 행 탭, 수직 탭 및 수직 문서 목록
* 문서 맵
* 자동 완성 : 단어 완성, 기능 완료 및 기능 매개 변수 힌트
* 다중 문서 (탭 인터페이스)
* 다중보기
* WYSIWYG (인쇄)
* 확대 및 축소
* 다국어 환경 지원
* 서표
* 매크로 기록 및 재생
* 다른 인수로 시작

### D_3.
Home > Features
: 홈화면 > 기능구성

## E - Resources
![resources](https://user-images.githubusercontent.com/37354145/40902298-820a244e-680e-11e8-9d45-99788f4685b5.png)

### E_1.
resources : 리소스

### E_2.
리소스

#### 온라인 도움말
* Notepad++ 커뮤니티 : 지원 및 질문에 대한 답변을 찾을 수 있는곳
* Notepad++ 대화방 : 실시간 도움을 받을 수 있는 곳 (GitHub 액세스 필요)
* NppWiki++ : Notepad++ 위키

#### 소스코드 저장소 접근
Notepad++ 소스코드 저장소는 GitHub에 있습니다.
https://github.com/notepad-plus-plus/notepad-plus-plus

귀하의 의견제시(Pull requests)를 환영합니다. 그러나, 항상 모든 의견제시가 받아들여 지는 것은 아닙니다.
의견제시 (Pull requests)에 대한 가이드라인은 다음과 같습니다.

1. Notepad++의 코딩스타일을 벗어나지 말 것.
2. 하나의 commit에서 여러기능을 commit 하지 않을 것.
3. 수정은 간결하게 - 요청에 소스코드를 다시 포맷하지 않을 것. 코드 재검토가 어려워진다.
: 코드 재검토가 쉬워질수록 의견제시가 받아들여질 확률이 높아짐.

#### Notepad++ ECCN
노트패드는 “전세계에서” 만들어지며 미국 영토 외 (소스코드와 바이너리)에도 배포되므로 ECCN 문제가 없어야 합니다.
ECCN 번호는 미국 법률에 부합해야합니다. 번호는 : EAR99

#### 언어 번역
언어 번역 페이지에서 필요한 언어를 얻을 수 있습니다.
자세한 정보를 얻으려면 언어 번역 twoto를 참조하십시오.

#### 플러그인
v3.1부터, Notepad++은 플러그인 시스템을 지원합니다. 플러그인 설치 방법 및 개발 방법을 배우려면 Plugins HOWTO를 참조하십시오.

플러그인 목록은 NpWiki++에 유지되며 완료되어야합니다. 이 목록을 이용하여 플러그인을 추가 및 업데이트를 할 수 있지만, 필수는 아닙니다.
플러그인 관리자플러그인은 Notepad++ 릴리즈에 포함되어 있습니다.

필요한 플러그인을 찾을 수 없다면 직접 개발하십시오.

#### 사용자 정의 언어 파일
사소한 이유로 일부 언어가 Notepad++ 에서 지원되지 않는 경우, User Language Define System이 사용자를 도와줄 수 있습니다. 이 시스템은 사용자가 자신의 언어를 정의할 수 있게 해줍니다 : 구문 강조 키워드 정의 뿐만 아니라 구문 접기 키워드 정의, 주석 키워드 정의 및 연산자 정의 등.

사용자 언어 정의 대화 상자를 통해 언어를 정의 할 수 있습니다. 그러나 사용자 정의 언어 목록에 다른 사용자에 의해 이미 정의되어있을 수도 있습니다.

#### 기본 프로그램 변경
이 포럼에서 가장 많이하는 질문 중 하납니다. NpWiki++ 에 Notepad++를 기본 프로그램으로 교체하는 방법에 대한 많은 참고자료가 있습니다.

#### Notepad++ Cheat sheet
Andrés Gomez가 공유한 Casanova :
단어 형식
PDF 형식

### E_3.
Home > Resources
: 홈화면 > 리소스

## F - Contribute 
![contribute](https://user-images.githubusercontent.com/37354145/40902527-3cca19f6-680f-11e8-9ff5-7b71e4cefe8c.png)

### F_1.
contribute : 기여
* Binary Translation HowTo : 번역참여 방법
* Binary Translations : 번역참여
* Shop : 상품샵
* Plugin HowTo : 플러그인 제작 방법

#### 기여
Notepad++ 프로젝트에 기여하는 여러가지 방법들
* 버그 리포트, 기능추가 및 버그수정 요청 / 새 기능 추가
* 온라인 지원에 대한 도움
* Nodepad++ 프로그램을 귀하의 언어로 번역
* 개발한 플러그인 공유
* 개발한 테마, UDL 또는 자동 완성 기능 공유
* “Notepad++는 굉장해!” 라고 입소문 내기
* 당신의 할머니나 3살짜리 아들이 Notepad++을 사용하도록 설득하기
* Notepad++ 상품 구매하기

### F_3.
Home > Contribute
: 홈화면 > 기여

## FF - contribute > Shop
![contribute_shop](https://user-images.githubusercontent.com/37354145/40902735-02c8db56-6810-11e8-8831-dc378ba54615.png)

### FF_1.
same as F_1.

### FF_2.
Notepad++ 샹품샵으로 이동하면 머그컵과 옷과 같은 잡화들을 구매 할 수 있습니다.

### FF_3.
Home > Contribute > Shop
: 홈화면 > 기여 > 상품샵

## G - Donate
![donate](https://user-images.githubusercontent.com/37354145/40902806-3eb0621a-6810-11e8-8e48-967a555bec2c.png)

### G_1.
donate : 기부
* Donate Notepad++ : Notepad++에 기부하기

### G_2.
Donate : 기부
왜 기부해야하죠?
(picture)
이 작디 작은 개발자의 프로그램이 당신에게 유용하다고 생각한다면, 기부를 해주세요.
귀하의 기부와 감사표현은 Notepad++ 프로젝트 개발을 이어나가는 동기부여가 됩니다.

지금 기부해주세요!

### G_3.
Home > Donate
: 홈화면 > 기부

## H - community
community : 커뮤니티

## I - contributors
![contributors](https://user-images.githubusercontent.com/37354145/40903013-e86b8abe-6810-11e8-93e6-b2680a93acd5.png)
### I_1.
기여해주신분들
* 총개발자

### I_2.
Contributors : 기여해주신분들
Author: Don Ho  ::::: 총개발자 : Don Ho
Code Contributors : 코드 개발자분들
More contributors : 더 많은분들

### I_3.
Home > Contributors
: 홈화면 > 기여해주신분들

## II - Contributors > Author
![author](https://user-images.githubusercontent.com/37354145/40903173-7a5a15f8-6811-11e8-9e66-5c56bb480846.png)

### II_1.
* Author : 총개발자

### II_2.
Notepad++ Author : Notepad++ 총개발자
Software Engineer : 소프트웨어 엔지니어 
Curriculum Vitae : 이력 및 경력서
Contact me : 연락방법
(칭찬 및 찬양 연락만 받습니다. 지원요청 및 버그신고 일체 금지)

### II_3.
Home > Contributors > Author
: 홈화면 > 기여해주신분들 > 총개발자

## J - links
![links](https://user-images.githubusercontent.com/37354145/40903287-ddec48a2-6811-11e8-8dfe-c0952b45f917.png)
### J_1.
links : 참고링크

### J_2.
Links : 참고링크
* Scintilla : Notepad ++의 주요 구성 요소. 매우 강력합니다.
* WinGup : Windows 용 일반 업데이터. LGPL 라이센스하에있는 메모장 ++ 업데이트 구성 요소는 유연하고 사용하기 쉽습니다.
* TinyXml : Xml (DOM). 메모장 ++에서 구성 xml 파일을 읽고 쓸 때 사용하는 구성 요소, 작지만 효율적입니다.
* Blue Bison : 귀여운 메모장 + 카멜레온 로고가 여기에서옵니다.
* famfamfam.com : 메모장 ++ 도구 모음 아이콘 (작은 아이콘).
* MODX :이 사이트를 구축하는 데 사용 된 CMS입니다.
* Ecreate :이 웹 사이트의 디자이너.
* ATD Fourth World : 2010-2011 년 동안 Notepad ++ 프로젝트에서 지원하는 인도주의 NGO.
* Notepad ++ UDL 온라인 문서 : Notepad ++ User Defined Language 온라인 문서.
* DigiCert : DigiCert 덕분에 Notepad ++ 패키지에 서명했습니다.

### J_3.
Home > Links
: 홈화면 > 참고링크

---------------------------------------------------------------------------------------------

I tried to translate as many Korean as possible by referring to Chinese and French pages.
I want to be sure that the above translation will be reflected on the homepage as soon as possible.
Thank you.

**Comment by pdache** [comment]
Wow! I think  this translation is good for Korean! :)

**Comment by wogns7534** [comment]
As Koreans, I really like this issue.

**Comment by Ekopalypse** [comment]
I assume can be closed, as new homepage doesn't offer multiple languages anymore.
