### ISSUE TITLE
Macros in Notepad++

### ISSUE THREAD

**Issue by FSERET** [notepad-plus-plus/notepad-plus-plus#4548]
### Description of the Issue

When I save a macro.
I can run it many time when I stay in Notepad++
If I close it, My macro is still there but I can't run it using a shortcut.
Impossible to see the script of the macro.

### Steps to Reproduce the Issue

1. Macro begin a save
2. Make some operations
3. Close the macro
4. Save it and give it a shortcut.
5. If you run immediatly the macro It's Ok
6. If you close Notrepad++ you are able to see you macro but impossible to run it and to control if there script in it.

### Expected Behavior

Be able to run a macro saved with zny document

### Actual Behavior

Nothing

### Debug Information

Notepad++ v7.5.6   (32-bit)
Build time : Mar 19 2018 - 00:26:59
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 7 (64-bit)
Plugins : DSpellCheck.dll mimeTools.dll NppConverter.dll NppExport.dll

**Comment by cmeriaux** [comment]
I can't reproduce your issue with the Zip package.

Notepad++ v7.5.6   (32-bit)
Build time : Mar 19 2018 - 00:26:59
Path : D:\download\npp.7.5.6.bin\notepad++.exe
Admin mode : OFF
Local Conf mode : ON
OS : Windows 10 (64-bit)
Plugins : DSpellCheck.dll mimeTools.dll NppConverter.dll NppExport.dll 

You may have something corrupted in your config files. Try to do a fresh install or the zip package
