### ISSUE TITLE
Microsoft is acquiring GitHub! What's next for Notepad++?

### ISSUE THREAD

**Issue by rddim** [notepad-plus-plus/notepad-plus-plus#4550]
@donho did you plan to move the project to another resource like `GitLab`, `BitBucket` or something else? What's the users opinion/suggestion?

**Comment by CookiePLMonster** [comment]
Why?

**Comment by rddim** [comment]
Because M$ and "open source" are not the same. Because we saw what happened with Skype and Nokia. We will see what will happen with LinkedIn, it is still "young" for M$. I don't insist to move the project, it's just interested situation for me.

**Comment by MetaChuh** [comment]
@rddim 

i believe this issue leads to nowhere at the moment.
it is a topic rather to be discussed at our community level, instead of at the source code related issue tracker, as it refers to hosting, and not to the code itself.

would you agree to close this topic ?

**Comment by donho** [comment]
I just don't think MS is stupid to ruin a huge community.
While Github is opened and free for open source project, Notepad++ stays.
