### ISSUE TITLE
Feature Request: Advanced Mark

### ISSUE THREAD

**Issue by azjio** [notepad-plus-plus/notepad-plus-plus#4551]
The native syntax creation tool greatly limits the ability to create complex analyzers because of the lack of regular expressions. If you use regular expressions, you do not need to use a different type of keyword. No numbers, keywords, operators, delimiters are needed. Enough regular expression and style of design.

XML contains the name of the syntax in which a regular expression is associated with a display style. On the “Mark” tab is a combo with a selection of names.
https://notepad-plus-plus.org/community/topic/15498/feature-request-advanced-mark

**Comment by sasumner** [comment]
I doubt I am alone -- I have no clue what is being asked for here.  Probably no one responded to the "community" link from 2 months ago because nobody could understand it.  Sorry.  You can try to rephrase or elaborate...

**Comment by azjio** [comment]
About UDL
my suggestion was not at the top, I'm afraid it was lost in the archive
https://github.com/notepad-plus-plus/notepad-plus-plus/issues/1713

**Comment by sasumner** [comment]
So you think the best way to get attention in an already brimming issues archive is to open yet another issue?

**Comment by azjio** [comment]
Made a plugin to solve my problem
http://file.sampo.ru/2jnv8s
http://rgho.st/6bgC4ZmCY

**Comment by MetaChuh** [comment]
many thanks for your feature request.

unfortunately we have not been able to understand it, but we are glad, that you were able to write a plugin to solve your problem.

thank you for your help and best regards.
