### ISSUE TITLE
Lexer for wikitext

### ISSUE THREAD

**Issue by magol** [notepad-plus-plus/notepad-plus-plus#4559]
[Wikitext ](https://en.wikipedia.org/wiki/Help:Wikitext) is used by the most popular wiki platform Mediawiki (used eg. by Wikipedia). I'm missing syntax highlight for wikitext.

I found some alternative on http://docs.notepad-plus-plus.org/index.php/User_Defined_Language_Files
but they are not working perfectly. 
They do not always match `{ `and `}` when it is complex templates, but maybe you can not blame the lexer for that.

**Comment by MetaChuh** [comment]
@magol 
unfortunately we don't have time to do that, hence also the very delayed reply.
thanks for understanding and best regards.
