### ISSUE TITLE
Notepad++ Fails to start - access violation

### ISSUE THREAD

**Issue by reillyjohn** [notepad-plus-plus/notepad-plus-plus#4561]
### Description of the Issue

I have stopped downloading Notepad++ updates because the recent versions won't start - they just come up with an error.
This morning I took time out to download the 64-bit version and it also has the same error on my computer.  Tested more versions as follows:-
7.5.5  Access Violation
7.5.3  Access Violation
7.5    Unknown Exception
7.4.2 Unknown Exception
7.3.3 Runs OK

I am continuing to operate using V7.3.3.
By the way, the installer downloads 32-bit on my pc, which is 64-bit.

### Steps to Reproduce the Issue

1. Start Notepad++
See attached Picture to view the message (part of the module name is in the form title)

![notepad error](https://user-images.githubusercontent.com/39986282/41026545-5b49198a-6964-11e8-8891-8b27a3bad17c.PNG)

### Actual Behavior

A dialog from appears which tells me that there is an access violation and it does not start.

### Debug Information

Using debugger for VS2017 I get the following:-
Unhandled exception at 0x000000013F95CAE1 in notepad++.exe: 0xC000041D: An unhandled exception was encountered during a user callback. occurred

Adding details about my computer:-
Computer is 64-bit, 
[ComputerInfo.txt](https://github.com/notepad-plus-plus/notepad-plus-plus/files/2075607/ComputerInfo.txt)

Here is the result of SYSTEMINFO.EXE
![notepad systeminfo](https://user-images.githubusercontent.com/39986282/41027172-e271cd98-6965-11e8-817f-987348c086fc.PNG)

and an (mostly) anonymised version of MSINFO32.EXE
![notepad computermoredetails](https://user-images.githubusercontent.com/39986282/41027369-5851bfe6-6966-11e8-9b67-045910b380fa.PNG)

**Comment by cmeriaux** [comment]
Your config file may me corrupted. Try out a fresh install or try out the zip package ( https://notepad-plus-plus.org/repository/7.x/7.5.6/npp.7.5.6.bin.zip )

**Comment by sasumner** [comment]
And just because you have a 64-bit Windows, it doesn't mean you must (or even should) run 64-bit Notepad++ as you seem to think...32-bit N++ will run just fine (well, once you get past your current issue).

**Comment by CookiePLMonster** [comment]
@sasumner are symbols for v7.5.6 available anywhere? It would then be possible to see where it crashes exactly.

**Comment by reillyjohn** [comment]
Thanks for the replies.
To verify the versions I have uninstalled and reinstalled numerous versions while writing the incident report.
I tried the 64 bit because of the error in the 32-bit version - trying to cover as many bases as possible.
I can get the symbols if you could tell me where to find them.  I am currently running V7.3.3.  
One question - I have retained the personal data each time I uninstall (maybe wrong terminology) - does this mean that I am retaining my config file?
The incoming mails went into my Junk, so it wasn't until I went looking for mails that I found them.

**Comment by MetaChuh** [comment]
please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins if you update from version 7.5.9 or below.
if your issue still persists, and it is still of relevance, please feel free to file a new issue as easy to understand and reproducible as possible.

thank you for your help and best regards.
