### ISSUE TITLE
Freezes on browsing large text file (+170MB)

### ISSUE THREAD

**Issue by aliha** [notepad-plus-plus/notepad-plus-plus#4562]
When I open a large text file and either scroll down to the end of the file or hit ctrl+end, notepad++ freezes and starts consuming a huge amount of memory until I kill it (allocated memory goes beyond 25GB!). In one instance, I let it run, and it repeatedly gradually allocated memory up to ~36GB then release it and starts again. 

### Steps to Reproduce the Issue
Notepad++ 7.5.6 (64 bit) on windows 7 
1. Open a large file (sorry cannot share mine!)
2. Scroll down towards then end

### Actual Behavior
freezes.

**Comment by KrasnayaPloshchad** [comment]
Scintilla announced they released v4.0.5 which adds experimental support for documents larger than 2 GB, maybe it would be helpful.

**Comment by MetaChuh** [comment]
please update your notepad++ to the latest 64 bit version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins if you update from version 7.5.9 or below.

disable word wrapping and all spell check plugins on large files.

if your issue still persists, and it is still of relevance, please feel free to file a new issue as easy to understand and reproducible as possible.

thank you for your help and best regards.
