### ISSUE TITLE
Problems using N-th Tab shortcuts

### ISSUE THREAD

**Issue by pdache** [notepad-plus-plus/notepad-plus-plus#4565]
### Description of the Issue
When you want to move tabs, you may want to use shortcut keys. However, pressing the N-th numpad and Ctrl keys on the tab will not cause any movement.

### Steps to Reproduce the Issue

![image](https://user-images.githubusercontent.com/37354733/41053107-ac09a18c-69f5-11e8-9571-9c3760d58891.png)

1. Run Notepad ++ and enter the View menu.
2. Enter the tab section.
3. Check the tab shortcuts Ctrl + Numpad 1, Ctrl + Numpad 2, and so on.
4. Try shortcuts in notepad ++.

### Expected Behavior

When you press Ctrl + Numpad 2 on the first tab, it moves to the second tab.
### Actual Behavior

Tab navigation does not occur using hotkeys.

**Comment by jeffreyhc** [comment]
I try this issue on my computer, and the shortcut works fine when num_lock is on.
My notepad++ vesion is v7.5.6 (32-bit) on win8.1.

**Comment by MetaChuh** [comment]
please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins if you update from version 7.5.9 or below.
if your issue still persists, and it is still of relevance, please feel free to file a new issue as easy to understand and reproducible as possible.

thank you for your help and best regards.

-----
```
general notes:

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).
please file an issue as easy to understand and reproducible as possible.

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
(no extra account is needed, just use your github account to sign in)
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)
