### ISSUE TITLE
Percentage of zooming in and out

### ISSUE THREAD

**Issue by wogns7534** [notepad-plus-plus/notepad-plus-plus#4566]
### Description of the Issue
When expanding or shrinking in Notepad ++, it would be better to display the percentage in the lower right corner as in Word. There is a key to restore the default, but it would be more convenient if it represented a percentage.

### Steps to Reproduce the Issue
1. Write the code for zooming in and out.
2. Apply it to Notepad ++.
3. It is possible to enlarge and reduce more conveniently than before.

### Expected Behavior
It is more convenient to zoom in and out without having to use the default restore key.

### Actual Behavior
The percentage of zoom in and out is displayed in the lower right corner (next to UTF-8).

### Debug Information
![image](https://user-images.githubusercontent.com/37335948/41055027-17d38180-69fb-11e8-8eab-63812c8391fe.png)

**Comment by sasumner** [comment]
The "zoom" is controlled by the Scintilla editing component so there isn't much Notepad++ development can do to (reasonably) change it.  

As to displaying the zoom level in the status bar, you might see this: https://notepad-plus-plus.org/community/topic/15679/seeing-the-zoom-level-with-pythonscript
That could be probably be adapted to display some sort of percentage but you'd have to figure out a reasonable algorithm for that.

**Comment by donho** [comment]
We have obvious way to zoom in/out on UI. Not on status bar anyway.
