### ISSUE TITLE
No "special caracter / symbol" in the description of a ftp-profile

### ISSUE THREAD

**Issue by Ricci1969** [notepad-plus-plus/notepad-plus-plus#4567]
By craating of a ftp-profile you can name or rename it. I have some ftp additions for example to 1&1. I can save a description of a ftp-profile, but when i choose this profle from the "connect" dialog, there ist only "11" instaed of "1&1".

**Comment by sasumner** [comment]
Notepad++ has no native FTP functionality (it belongs to a plugin), so this is not the correct place to report a problem involving it.  Please close this issue.

**Comment by Ricci1969** [comment]
You're right.
