### ISSUE TITLE
Notepad++ does not include a function from a C file in the "Function list" window

### ISSUE THREAD

**Issue by AleWin32** [notepad-plus-plus/notepad-plus-plus#457]
Hi,

I open a C file (.c extension) in Notepad++ 6.7.9.2, then i can see the list of functions the file has in the "Function List" window (View menu, Function List), but there is a function that does not appear in the list.
I know where is the problem, it fails when the function return a pointer to pointer to anything (short \*\*, char \*\*, int \*\*, etc). Here it is the function prototype i have:

```C
char** PrintConversations ( UINT *rows, output_format format, ...)
```

If i delete an asterik from the double asterisk, it works and it show the function in the list:

```C
char* PrintConversations ( UINT *rows, output_format format, ...)
```

Can this be fixed? THANKS!

**Comment by DavidBailey100** [comment]
A related problem is that the function list does not include functions whose declarations start
extern "C" .........

**Comment by dail8859** [comment]
Or where the return value is on the line before the name/parameters...

**Comment by Rikk** [comment]
There is also a discussion on Community -- with proposed solutions -- about another case where C functions are not detected in Function List:
https://notepad-plus-plus.org/community/topic/170/function-list-doesn-t-detect-c-functions-that-have-function-pointers-in-the-argument-list
