### ISSUE TITLE
Rebol lexer has incorrect lexer definition

### ISSUE THREAD

**Issue by ClaudiaFrank** [notepad-plus-plus/notepad-plus-plus#4572]
### Description of the Issue
stylers.(model).xml contains an incorrect entry which corrupts the xml

### Steps to Reproduce the Issue
1.  Open stylers.xml and goto rebol lexer
2.  Check value `"TAG { <TITLE HEIGHT=100> }" `

### Expected Format
`"TAG { &lt;TITLE HEIGHT=100&gt; }"`

### Actual Format
`"TAG { <TITLE HEIGHT=100> }" `

### Debug Information
Notepad++ v7.5.6   (64-bit)
Build time : Mar 19 2018 - 00:23:17
Path : D:\Repositories\_cf\Builds\Release\x64\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 7 (64-bit)
Plugins : PluginManager.dll PythonScript.dll

**Comment by ClaudiaFrank** [comment]
seems to be fixed already

**Comment by ClaudiaFrank** [comment]
seems to be fixed already

**Comment by ne0fyt** [comment]
This bug remains in Notepad++ v7.6 and still needs to be fixed.

**Comment by chcg** [comment]
Confirmed the bug is still there, see https://github.com/notepad-plus-plus/notepad-plus-plus/blob/master/PowerEditor/src/stylers.model.xml#L966.

**Comment by chcg** [comment]
See also discussion:
https://notepad-plus-plus.org/community/topic/16693/invalid-structure-of-stylers-model-xml/5
