### ISSUE TITLE
Opening all files in a directory

### ISSUE THREAD

**Issue by RiverOx** [notepad-plus-plus/notepad-plus-plus#4574]
### Description of the Issue

Using the open file dialog to open files, all in the same directory,
if I cherry pick certain files, then the editor opens these - every file selected.
If I block highlight all files (using shift + click under windows), none of the files 
are opened in the editor when I choose "Open"

### Steps to Reproduce the Issue

1. Click File menu, open
2. Browse the file open dialog to a directory holding multiple files
3. Click to select the first file
4. Click + SHIFT (or as apt on your O/S, I'm on windows10) to select the last file and 
    all files between first and last (inclusive)
5. Click the dialog "Open" button
6. Look on in bemusement as no files opened.

### Expected Behavior

I expected all files to appear in the editor

### Actual Behavior

No files were opened

### Debug Information

As mentioned above, editor correctly opens files if I cherry pick instead,
but ONLY if I cherry pick all but one file.  As soon as I dare to select every single file in 
the directory - nothing opens!

**Comment by RiverOx** [comment]
I should have added I'm using Notepad++ v7.5.6 (64-bit) build time/date Mar 19 2018 -- 00:23:17

**Comment by RiverOx** [comment]
Closing as I can't reproduce

I must have done something wrong - or was too tired to understand something

**Comment by OfekShilon** [comment]
@RiverOx  Tried your steps to the letter, couldn't reproduce. Notepad++ 7.5.6 64 bit on Win 10.

**Comment by RiverOx** [comment]
Thanks for trying:

I just tried it again now and the issue does not arise.
But I've so far encountered in on 2 independent PCs; even though 1 of those is where I just 
tried - a few seconds ago - to reproduce the problem.

There must be more steps, steps I haven't yet understood, needed to get into this wierd state

If I learn more I'll let you know, for now it's too intermittent / not understood.

**Comment by MetaChuh** [comment]
please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins if you update from version 7.5.9 or below.
if your issue still persists, and it is still of relevance, please feel free to file a new issue as easy to understand and reproducible as possible.

thank you for your help and best regards.

-----
```
general notes:

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).
please file an issue as easy to understand and reproducible as possible.

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
(no extra account is needed, just use your github account to sign in)
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)
