### ISSUE TITLE
Function List: non function included in list

### ISSUE THREAD

**Issue by lijhello** [notepad-plus-plus/notepad-plus-plus#4575]
![npp](https://user-images.githubusercontent.com/9011764/41226985-d99d64a4-6da5-11e8-8680-8d192d6e9719.png)
![si](https://user-images.githubusercontent.com/9011764/41226986-d9fb24ea-6da5-11e8-8cde-293f97773629.png)

The entry "trial_ascent" after plan is a function call instead of a function definition.
Source Insight doesn't have this problem.

**Comment by MAPJe71** [comment]
Noted. Thanks.

**Comment by sasumner** [comment]
Closing as duplicate; leaving 4794 open
