### ISSUE TITLE
Style Configurator loading list of themes twice

### ISSUE THREAD

**Issue by EdwardGray953** [notepad-plus-plus/notepad-plus-plus#4581]
### Description of the Issue
NP++ V 7.5.6 (32-bit)

After loading the Style Configurator, the drop down to change themes loads the list of themes twice.

### Steps to Reproduce the Issue

1. Settings -> Style Configurator
2. Click on "select theme" drop down to view all available themes

### Expected Behavior
Should only be loading the list of themes once.

### Debug Information
Notepad++ v7.5.6   (32-bit)
Build time : Mar 19 2018 - 00:26:59
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : ON
Local Conf mode : OFF
OS : Windows 7 (64-bit)
Plugins : DSpellCheck.dll mimeTools.dll NppConverter.dll NppExport.dll NppFTP.dll PluginManager.dll SpellChecker.dll 

![image](https://user-images.githubusercontent.com/35969254/41346509-9a8d06a2-6efe-11e8-9320-8473cab326f3.png)

**Comment by ArkadiuszMichalski** [comment]
@EdwardGray953 Do you still have this problem in latest Notepad++ version?

**Comment by donho** [comment]
Cannot be reproduced.
