### ISSUE TITLE
[Wish] Let highlighted item in Search result tab when go back to text frame.

### ISSUE THREAD

**Issue by DenisFR** [notepad-plus-plus/notepad-plus-plus#4582]
### Description of the Wish
When you run a search in all files then select a result item to go to line.
The item is not highlighted.

### Steps to Reproduce the Issue
1. Search in all file a text
2. Double click on result item
3. The cursor is on text frame but item is not highlighted. It's hard to found it again.

### Expected Behavior
Result item stay highlighted even if cursor is in text frame.
Now, only unfold icon stay red.

**Comment by sasumner** [comment]
Is this what you are talking about?  #4518

**Comment by DenisFR** [comment]
Yes, sorry, don't find issue before.
Waiting PR merged.
