### ISSUE TITLE
npp.7.5.6.Installer.x64 install NppShell_06 instead of NppShell_07

### ISSUE THREAD

**Issue by dcsobral** [notepad-plus-plus/notepad-plus-plus#4589]
### Description of the Issue
On installing Notepad++ with npp.7.5.6.Installer.x64, NppShell_06 instead of NppShell_07 is installed. I presume this is an issue because the context menu for "Edit with Notepad++" does not work, though Open With then Notepad++ does.

### Steps to Reproduce the Issue

Install Notepad++ using npp.7.5.6.Installer.x64.

The installation I did was over a directory that did contain some plugins DLLs from a previous installation, but did not contain NppShell_06. The plugins I have installed are HTML Tag, COnverter, DSpellCHeck, LuaScript, MIME Tools, Npp Xml Treview and NppExec, and Xml Tools external DLLs (version 2.4.9.2) were also left in the original directory.

### Expected Behavior
NppShell_07.dll is installed.

### Actual Behavior
NppShell_06.dll is installed.

### Debug Information

Notepad++ v7.5.6   (64-bit)
Build time : Mar 19 2018 - 00:23:17
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10 (64-bit)
Plugins : DSpellCheck.dll HTMLTag.dll LuaScript_64.dll mimeTools.dll NppConverter.dll NppExec.dll NppXmlTreeviewPlugin.dll XMLTools.dll

**Comment by SinghRajenM** [comment]
NppShell_07.dll is not yet released. Latest version is NppShell_06.dll.

**Comment by SinghRajenM** [comment]
@donho or @dail8859 this is not a bug. I feel this can be closed.
