### ISSUE TITLE
Notemad++ preferences for auto-complete cannot be changed to another number.

### ISSUE THREAD

**Issue by dvdvideo1234** [notepad-plus-plus/notepad-plus-plus#4596]
### Description of the Issue
I tried to edit the length of auto-complete function in NPP, but I cannot change the number from **1** to **3** .

### Steps to Reproduce the Issue

1. Setting -> Preferences -> Auto-Completion
2. ( Left plane ) Auto-Completion

![image](https://user-images.githubusercontent.com/9112662/41639975-b1648d7c-7468-11e8-8de9-b1826dc59199.png)

### Expected Behavior
I expect NPP to change the value from **1** to **3**

### Actual Behavior
The text-box stays the same no matter what digit I press.

### Debug Information
NPP v7.5.6 (32-bit) 
![image](https://user-images.githubusercontent.com/9112662/41640084-1c25b424-7469-11e8-9f3b-b4616900ceb4.png)

**Comment by sasumner** [comment]
Did you try backspacing first to remove the `1`?  Or do you not get a caret in that box?

**Comment by dvdvideo1234** [comment]
@sasumner 
Yes I did. The box does not allow me to remove the value with backspace.

**Comment by dvdvideo1234** [comment]
Yes, I did. The value is removed with backspace, but when a digit is pressed, it does not fill up the box.

**Comment by levimatheri** [comment]
Using v7.5.7 32-bit works. Try and upgrade. If not, then it might be one of the plugins causing the issue

**Comment by snoopy78** [comment]
It's a dublicate of bug #3010. The problem source is described in bug #4227.

**Comment by dvdvideo1234** [comment]
> 
> 
> Using v7.5.7 32-bit works. Try and upgrade. If not, then it might be one of the plugins causing the issue

On 7.5.9 does not work also.

**Comment by MetaChuh** [comment]
please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins if you update from version 7.5.9 or below.
if your issue still persists, and it is still of relevance, please feel free to file a new issue as easy to understand and reproducible as possible.

thank you for your help and best regards.
