### ISSUE TITLE
Find Dialog: "Backwards Direction", two button check box etc

### ISSUE THREAD

**Issue by koolraap** [notepad-plus-plus/notepad-plus-plus#4600]
7.5.6 The find dialog box has some issues:

1. Move the "[ ] Show << and >> buttons" check box so it's in the same location as all the other options, providing a consistent location for options affecting searching. From a UI perspective it's certainly a unique approach having it over on the right by itself without a label describing what it does (it's not very attractive, besides IMO)

2. Rename "Backward direction" so it makes sense or at least describes what it does in a way that's obvious.  "Search backwards", or "Find backwards", "Search up", "Find Up".

3. "Backwards direction" doesn't work in two button mode. When checked I'd expect the << button to search forward and the >> button search backwards (as well shift+click the buttons behaving the same).

4. Missing accelerators.

**Comment by sasumner** [comment]
1. Really, it makes sense where it is, especially because it changes the find-next button into 2 buttons (and back again).  If you hover over it, a tool tip describes what it does.  Exactly what is not "attractive" about it.

2. Historically, there used to be a 2-radio button box that controlled search direction.  I think I liked that better (and from your description I would guess that you would agree).  But I doubt we'll be evolving back to that.  However you can change the text of the checkbox to be anything you want for YOU (edit the appropriate language .xml file, e.g. english_customizable.xml).

3. It's not supposed to work like that.

4. Missing accelerators for what exactly?  Add your own like I described for changing control text.

**Comment by koolraap** [comment]
@sasumner: I politely disagree. Point by point

1. It makes sense to have a check box with no text? What do screen readers make of it (I don't have any installed at the moment)? The mouseover pop up text is useless for keyboard people.

I suspect most people will have a preference and never change the checkbox again -- which makes it a good candidate for the Preferences dialog, saving some real estate. Or even add a Preferences tab on the Find dialog.

2. "Backward direction" is ambiguous, I had no idea what it meant. Search for reversed words? HELLO vs OLLEH? I still think "Search backward(s)" or similar makes the intent of the option clearer, and it's a pretty common thing to see in search dialogs.

3. So by design "Backward direction" only applies in Single Button Mode? Weird.  If that's the case the option should be disabled in Two Button Mode -- makes it clear the behaviour is inconsistent.

4. OOTB there are no accelerators for at least the following: 
   << 
   >>
   Find all in current document (there's an issue for this already)
   Backward direction

**Comment by sasumner** [comment]
@koolraap Good luck in getting your suggestions realized.  :)

**Comment by koolraap** [comment]
@sasumner just trying to make a great product better.

**Comment by koolraap** [comment]
Sorry to spam. I just noticed @sasumner said "What's not attractive about [the checkbox next to the Find << >> button(s)]".

Use the keyboard. Tab (because no accelerators when in 2 button mode) to the unlabelled checkbox. The focus ring around blank text -- that's not attractive. It just doesn't make sense from a UI/UX perspective. Why is a seldom used setting given such prominence?

(and the << and >> text isn't centred in the buttons. Arrghhh!)

**Comment by sasumner** [comment]
@koolraap , maybe we're just a little more "laid back" in the Notepad++ world...and maybe we don't sweat the tiny stuff.  Again, wish you success in getting your voice heard...

**Comment by koolraap** [comment]
> maybe we don't sweat the tiny stuff.
Again I politely disagree. Usability/user experience is the entire point of a tool like Notepad++. The more we users don't notice it, the better it it is.

? vs Help. Is it better? Is breaking convention better? What's the upside?
"Backward direction" vs "Search up". Which is better? Which makes me think?
"[ ]" vs "[ ] two buttons" which is better? Which makes a user think?

I've reviewed endless UX/UI and code, and my mantra is "Don't make me think". Don't be different for the sake of being different. Be different to be better.

Provide some arguments Notepad++ approach is better.

**Comment by sasumner** [comment]
@koolraap 

>Provide some arguments Notepad++ approach is better.

It's all very subjective.  Truth be told, I thought creating a "Backward direction" checkbox (versus the previous 2-radio button [direction: "up" / "down"]) approach was not as good, but the author of Notepad++ liked it (apparently).

The upside is that the author gave us the ability to change the text on most controls (for multilanguage support mainly, but we can use it for changing what we don't like), so when I don't "sweat the small stuff" I mean I say "meh" to the "backward direction" thing, change the text if I don't like it, and mentally move on.  As I said, you're free to have your preference, you've created an issue around it...let's see what happens...

**Comment by koolraap** [comment]
@sasumner why did you close this? All my minds are still valid. It's not subjective. My any measure the Notepad++ search dialog isn't as good as it could be.

"Backward direction" is meaningless. There's no verb. "Search backward" is gives the user a hint about what will happen. "Backward Direction", it's just naff.

Read Norman Diamond's the Design of Everyday Things. Then take a long hard look at Notepad++, and taps and doors. It's an amazing book.

http://www.nixdell.com/classes/HCI-and-Design-Spring-2017/The-Design-of-Everyday-Things-Revised-and-Expanded-Edition.pdf

**Comment by koolraap** [comment]
Notepad++'s author hates users who use a screen reader? Use tab to navigate the Search dialog box. If you see a checkbox with no text, that's pretty much confirmation.

**Comment by sasumner** [comment]
>why did you close this?

Because I can? :)  Seriously, though, just because there is an "issues" site where users can log things, doesn't mean every suggestion is acted upon (people seem to be surprised by this, followed by anger...).  This is one of those cases where it won't be, sorry.  Thank you for your input, though.

>It's not subjective

Yes, it is. :)

>Notepad++ search dialog isn't as good as it could be

Surely.  Nothing (of non-trivial complexity) is ever as good as it could be.

>"Backward direction" is meaningless.

So as mentioned before, change it in your copy via the language xml files.

>Norman Diamond's the Design of Everyday Things

Thanks for the link; I for one will have a read.

>Notepad++'s author hates users who use a screen reader?

It's a strong statement, and it is not true.
