### ISSUE TITLE
Menu: Rename ? to Help. Settings: rename MISC. to Miscellaneous

### ISSUE THREAD

**Issue by koolraap** [notepad-plus-plus/notepad-plus-plus#4601]
Every Windows app ever uses Help rather than a ? for the help menu. Change to &Help

The other thing that has been annoying me for years is "MISC." in the Settings dialog. There's no need for it to be an uppercase abbreviation. There's enough room to use Miscellaneous.

**Comment by sasumner** [comment]
If Notepad++ were just like "every Windows app ever"...where would the innovation be?  :)

**Comment by koolraap** [comment]
The innovation should be in the remainder of the amazing application named Notepad++.

Having a small target is frustrating for people with less than perfect motor control. What do screen readers render "?" as?

Help should be easy to find. There's no upside to using ?.

(as an aside: Office 2007 "innovated" by removing the File Menu and turned it into a marketing logo. I saw a very savvy 8 year girl cry because she could no longer find "Print". "Innovation" at work).

**Comment by MetaChuh** [comment]
@koolraap 

you can change all menu items at `localization\yourlanguage.xml` to adapt them to your personal needs.

thank you for your help and best regards.

-----
```
general notes:

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).
please file an issue as easy to understand and reproducible as possible.

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
(no extra account is needed, just use your github account to sign in)
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)

**Comment by koolraap** [comment]
@MetaChuh that's a workaround, not a fix. I raised a defect.

I can understand somebody might prefer "?" instead of Help menu even though I presented it's an accessibility issue. But "MISC."? that's so out-of-character for the entire interface it should just get fixed.
