### ISSUE TITLE
NPP updater gup.exe uses libcurl.dll which is built incompatible to WinXP (imports GetTickCount64)

### ISSUE THREAD

**Issue by JoachimHenze** [notepad-plus-plus/notepad-plus-plus#4603]
### Description of the Issue
When you start up Notepad 7.5.6 on Windows XP or Win2003 or ReactOS there will be an error-box
"
GUP.exe
The procedure entry point GetTickCount64 could not be located in the dynamic link library kernel32.dll
"

### Steps to Reproduce the Issue
simply start up Notepad++ 7.5.6
Notepad++ 6.9.2 was not affected yet.

### Expected Behavior
Updater Gup runs and works without that messagebox.

### Actual Behavior
The undesired messagebox appears. Gup.exe does not work.

### Debug Information
Please build libcurl.dll in a Windows XP compatible way.
"mode mutlithreaded with XP compatibility"
(or use an older version of libcurl.dll alternatively)
The dll must not import GetTickCount64() and InitializeCriticalSectionEx().
Those kernel32-exports are only available in Windows Vista and newer.
It's easy to double-check that with msdepends.

**Comment by sasumner** [comment]
FYI Notepad++ has dropped Windows XP compatibility officially.  Not sure how important your issue will be to developers given that; I would guess not very.

**Comment by sasumner** [comment]
@JoachimHenze Good luck with getting your request implemented.

**Comment by CookiePLMonster** [comment]
> Rather easy to make millions of users happier here.

I think you are overestimating an amount of people who do **all** of the following:
- use Windows XP
- care about having their software as up to date as possible
- cannot handle the fact software phases out XP support over 4 years after the system stopped being supported

**Comment by dinkumoil** [comment]
@CookiePLMonster : It's not about Windows XP, it's about ReactOS which unfortunately seems to use a code basis which mimics Windows XP ore even some older version of Windows.

I'm not involved in the ReactOS project and don't use it, just my 50 cents.

**Comment by bahusoid** [comment]
>FYI Notepad++ has dropped Windows XP compatiblity officially.

@sasumner Where did you get this official statement?

And why  XP platform toolset is still used if support is dropped?
https://github.com/notepad-plus-plus/notepad-plus-plus/blob/63261156623bbc84d271b7727d66c552512395c1/PowerEditor/visual.net/notepadPlus.vcxproj#L30

**Comment by sasumner** [comment]
>Where did you get this official statement?
Don Ho said it a while ago.

>And why XP platform toolset is still used if support is dropped?
maybe a remnant?

**Comment by maf-soft** [comment]
This just happened to me in 7.6.6 (32 bit) under Windows Server 2003.

**Comment by MetaChuh** [comment]
@JoachimHenze

wingup and plugins admin are not supported on windows xp.
no plans of making wingup compatible with retro operating systems are currently pursued.
please use older notepad++ versions on matching older operating systems.

many thanks for your help and best regards.
