### ISSUE TITLE
Function List (PHP) Breaks Completely When Using "string/*" literal

### ISSUE THREAD

**Issue by victor-david** [notepad-plus-plus/notepad-plus-plus#4606]
### Description of the Issue
When a class has a function that uses a string literal such as:
`$target =  '/path/to/files/*';`
or
`$target =  '/path/to/files/*.jpg';`
The function list breaks completely. No functions are displayed. 

Remove the asterisk like so:
`$target =  '/path/to/files/';`
or comment out the offending line like so:
`// $target =  '/path/to/files/*.jpg';`
and all is well again.

Seems likely that this is because of clash with the /* comment syntax 

### Steps to Reproduce the Issue
1. Put a line of code in any function as shown above.

### Expected Behavior
The function list still works

### Actual Behavior
The function list feature breaks completely. No functions are displayed.

### Workaround
`$target =  '/path/to/files/' . '*.jpg';`

### Note
Per other notes I've seen on function list problems, I removed **functionList.xml** from the *C:\Users\UserName\AppData\Roaming\Notepad++* directory and let NPP copy its latest one in there. Didn't help.

Also, since the workaround is pretty simple, I realize this probably isn't hi-pri. However, I hope that maybe this will help others who are wondering why function list doesn't work on certain files. Thanks so much for NPP.

### Debug Information
Notepad++ v7.5.6   (64-bit)
Build time : Mar 19 2018 - 00:23:17
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 7 (64-bit)
Plugins : DSpellCheck.dll mimeTools.dll NppConverter.dll

**Comment by MAPJe71** [comment]
Please try my updated PHP parser posted [here](https://notepad-plus-plus.org/community/topic/15124/php-function-list-and-abstract-functions/11).

**Comment by victor-david** [comment]
Thank you. That fixes it. I also like the extra bonus of being able to display the method/function parms. Very nice! Much appreciated.

**Comment by ArkadiuszMichalski** [comment]
@victor-david You still have this problem in latest Notepad++ version? If yes then put some short example code.

**Comment by victor-david** [comment]
Yes. I think  #4712 is correct in that it takes the string literal _and_ a block comment (which I didn't notice originally) to cause this problem.

~~~php
$target = '/path/to/files/*';

/* some block comment */
~~~

The parser from @MAPJe71 fixed it for me and I've been using it ever since.
