### ISSUE TITLE
Pasting a blank line after using Ctrl+L following Ctrl+X

### ISSUE THREAD

**Issue by tiger0tank** [notepad-plus-plus/notepad-plus-plus#4607]
### Steps to Reproduce the Issue

1. Cut a non-blank line via Ctrl + X;
2. Remove the line where the content has been cut via Ctrl + L
3. Paste the content somewhere via Ctrl + V

### Expected Behavior

Paste the line I've cut.

### Actual Behavior

Paste a new but blank line

**Comment by alankilborn** [comment]
Can't replicate in N++ 8.4.4 (current version as of this writing).
@tiger0tank if this is still a problem, please post here in this issue again.
Otherwise, recommend CLOSURE of this item.
