### ISSUE TITLE
Industrial Robot Languages for NPpp

### ISSUE THREAD

**Issue by LangHH** [notepad-plus-plus/notepad-plus-plus#4610]
### Description of the Issue
Hey Developers of Notepad++,

I have created a User-Defined-Language for VAL3. Until now there are no specific robot programing languages supported natively by NPpp. Is it possible to insert such languages into the release? I could help with some languages like:

•	Stäubli VAL3
•	(Mitsubishi)
•	Kuka – KRL
•	Fanuc KAREL / TP
•	(Motomann)

Others may come:
•	ABB
•	KUKA – iwaa

Also a Codesys implementation might be interesting. What do you need for an integration?

[VAL3_NotepadPP_bunt.txt](https://github.com/notepad-plus-plus/notepad-plus-plus/files/2144636/VAL3_NotepadPP_bunt.txt)

**Comment by tanisto** [comment]
Hello, I am very interesting in it. Especially for Karel - Fanuc. Your idea is already finished, what do I need to install so I could use notepad++ :) Thank u ...

**Comment by ArkadiuszMichalski** [comment]
@LangHH If yu still interested maybe add them to dedicate repo https://github.com/notepad-plus-plus/userDefinedLanguages?
