### ISSUE TITLE
Selecting text with 'Alt'-modifier and then moving lines with Ctrl+Shift corrupts text

### ISSUE THREAD

**Issue by Morten242** [notepad-plus-plus/notepad-plus-plus#4614]
### Description of the Issue
As in the title

### Steps to Reproduce the Issue
1. Open a new text document
2. copy-paste (including blanks):
```
!abc!

.
```
3. Select "abc" while holding ALT
4. Press CTRL+SHIFT+DOWN
5. See something like the image below
![notepad _2018-06-29_12-59-05](https://user-images.githubusercontent.com/6974432/42089099-37afbcf0-7b9c-11e8-9a38-71433f4a9752.png)

### Expected Behavior
To move the full lines I have a selection in (probably?)

### Actual Behavior
Moves the characters selected and produces invalid/corrupted characters.

### Debug Information
Notepad++ v7.5.6   (32-bit)
Build time : Mar 19 2018 - 00:26:59
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10 (64-bit)
Plugins : DSpellCheck.dll mimeTools.dll NppConverter.dll NppExport.dll PluginManager.dll

**Comment by levimatheri** [comment]
Seems like it has to do with [this](https://github.com/notepad-plus-plus/notepad-plus-plus/blob/51797bf59e689b11d80998758790f8a4cade68eb/scintilla/src/Editor.cxx) file. It works okay but cannot think of how the NUL FF are getting inserted

**Comment by alankilborn** [comment]
Can't reproduce in current version of Notepad++ (8.4.4).
@Morten242 if this is still a problem, please post again in this issue.
Otherwise recommend CLOSURE of this item.
