### ISSUE TITLE
Remove XML folded section with triple click

### ISSUE THREAD

**Issue by HarelM** [notepad-plus-plus/notepad-plus-plus#4615]
### Description of the Issue
When trying to delete a folded XML section with triple click it only removes the opening tag.

### Steps to Reproduce the Issue
1. Fold a XML section
2. Mark the XML section line with triple click
3. Press backspace or delete

### Expected Behavior
The entire section will be deleted.

### Actual Behavior
This creates a badly formed XML since I just deleted the beginning of a section and not the whole section.

**Comment by MetaChuh** [comment]
please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins if you update from version 7.5.9 or below.
if your issue still persists, and it is still of relevance, please feel free to file a new issue as easy to understand and reproducible as possible.

thank you for your help and best regards.

-----
```
general notes:

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).
please file an issue as easy to understand and reproducible as possible.

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
(no extra account is needed, just use your github account to sign in)
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)

**Comment by HarelM** [comment]
I have checked this win npp 7.6.6 and I can still reproduce the issue.

**Comment by sasumner** [comment]
@HarelM I don't know that it is an "issue".  A folded block is a margin and visual thing, not a text editor buffer thing.  I think it works as intended by the developers.

**Comment by HarelM** [comment]
@sasumner I don't think this is the intended behavior as far as I understand.
The following scenarios, as far as I understand should produce the same results:
Scenario 1:
1. Fold and xml section
2. Drag-select a full line that is a folded xml section (Click with the mouse on the line start and drag the mouse until the line end)
3. Click delete or backspace.
What happens - the entire xml section is deleted
Doing almost the same, as described in the fist comment of this bug only deletes the section opening element and creates an invalid xml.

I believe both operations should produce the same results, either valid or invalid xml...
@MetaChuh can you please reopen?

**Comment by sasumner** [comment]
Perhaps I should have said:  Triple-click is designed such that it will select only one line (including the line-ending), always. This has the same effect as single-clicking a line-number in the margin.

>Drag-select a full line that is a folded...drag the mouse until the line end

This is rather a handy special case for folded lines, as it will effect the entire folded section (as you correctly pointed out). However, its handiness is somewhat reduced by the time consumed to do it, and the preciseness required to make an accurate selection.  Perhaps record a macro that does the keyboard equivalent actions to select the same text, and bind it to a keycombo for speed's sake?

**Comment by HarelM** [comment]
@sasumner I don't fully follow... All I'm saying is that drag-select which selects the entire folded section is great, It would be even greater if the same functionality was available with triple click, line click on the margin or clicking <kbd>Home</kbd>, <kbd>Shift</kbd>+<kbd>End</kbd> or any other method that selects a full line.
i.e. selecting a full line in case of a folded section should be equivalent of selecting the full section.
I hope I made my point clearer now...

**Comment by sasumner** [comment]
@HarelM 

>I hope I made my point clearer now...

I've understood your point from the beginning.  And I can even agree with your point (haven't decided yet!).  But it matters little, because Notepad++ doesn't control this functionality to the best of my knowledge.  Perhaps this should have been said earlier, but this is Scintilla functionality rather than Notepad++ functionality.  

> selecting a full line in case of a folded section should be equivalent of selecting the full section

I've done some further investigation and I think I have bad news for you.  Trying these same actions in a newer Sc.exe editor (I tried Sc414.exe) shows that it has even less of the functionality you like than Notepad++ 7.6.6 (with its older Scintilla) does.  For example, if I try your steps 2&3 from earlier today, Sc414.exe does not delete the block but just the first line.  What this means is that when Notepad++ updates its Scintilla (actively being worked on), as far as we can tell right now, it will lose even the step 2 functionality you like from N++...and it won't gain the triple-click folded block select either.

However, in both existing Notepad++ and Sc414.exe cases if you select the full folded line from start to end, and then you add one more right arrow press to add to the selection, in this case you WILL delete the entire folded section with a Delete key press.

**Comment by HarelM** [comment]
@sasumner Ok, now I understand :-) Thanks for the extra info!
I hope Scintilla will improve their support for folded sections, visual studio does this very well and I like how it behaves there...
Well... it was worth a shot :-)

**Comment by sasumner** [comment]
So maybe not as good as a triple-click, but I was able to macroize this as:

* alt+home
* shift+end
* shift+right

That can be tied to a keycombo (again, maybe not as awesome as triple-click to select a folded block).
