### ISSUE TITLE
Feature [Alt]+letter in buttons

### ISSUE THREAD

**Issue by cmbarros** [notepad-plus-plus/notepad-plus-plus#4616]
### Description of the Issue

To implement [Alt]+letter in buttons - i.e. Find / Replace window

### Steps to Reproduce the Issue

1. 
2. 
3.

**Comment by sasumner** [comment]
Wow, a lot of effort you went to to put that issue in.  The Find/Replace window already implements "alt+letter" functionality, but maybe I misunderstand what you are talking about because you didn't say much.  Cheers.

**Comment by cmbarros** [comment]
Sorry, I didn't say much in fact!

I was saying the part in picture here attached.
Windows pgms used to put one letter to be alt-ed underlined...

It would be very much useful in case of making lots of finds in a file, and 
this is the only moment we have to stop typing to go to mouse.

Best regards,
Mauricio Barros







A 8 de julho de 2018 09:21:08, sasumner <notifications@github.com> escreveu:
| Wow, a lot of effort you went to to put that issue in. The Find/Replace 
window already implements "alt+letter" functionality, but maybe I 
misunderstand what you are talking about because you didn't say much. Cheers.
| —
| You are receiving this because you authored the thread.
| Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by sasumner** [comment]
Sorry I don't see a "picture here attached".  So I'll put my own picture here to show some Alt+letter keycombos in the Find window:

![image](https://user-images.githubusercontent.com/30118311/42421249-7efea660-82a0-11e8-9550-ba78356f17b0.png)
