### ISSUE TITLE
Hex editor

### ISSUE THREAD

**Issue by pps83** [notepad-plus-plus/notepad-plus-plus#4618]
This is a feature request. I love notepad++, this is my editor of choice for quick stuff.
But I don't want to update it ever, because it each update cripples my install and disables hex editor.
Can you please stop doing that at least for the hex editor or perhaps fix hex editor if it's unstable (I didn't have major issues with it in many years)?

**Comment by 9527KGG** [comment]
+1,

I don't update it for the same reason. BTW, is it possible to have an official hex editor?

**Comment by 9527KGG** [comment]
BTW, hex editor is my #1 plugin for my NPP.

**Comment by 9527KGG** [comment]
I've update NPP x64 from 7.5.6 to latest 7.6.3. HexEditor_0.9.5.19_x64 (https://sourceforge.net/projects/npp-plugins/files/Hex%20Editor/) stopped working. I've to rollback.

Could you please fix the issue.

**Comment by chcg** [comment]
@9527KGG Seems you have https://github.com/chcg/NPP_HexEdit/releases/tag/0.9.5.19 installed.
With 7.6.3 you are facing the changed install folder behaviour of N++. Beyond the plugin folder the plugin dll itself needs to be in a subfolder named like the plugin. So .../plugins/HexEditor/HexEditor.dll. There is a request to integrate Hexeditor into PA, see https://github.com/chcg/NPP_HexEdit/issues/9

**Comment by 9527KGG** [comment]
@chcg Thanks. It's working now. BTW, could you please add it to PluginAdmin? I remember long ago hex editor was in plugin manager. Then later some one removed it from plugin manager, which is very annoying because every NPP upgrade would disable it :(

**Comment by MetaChuh** [comment]
closing now.

if you are already on 7.6.3 or above, and you have already migrated your plugins, you will notice, that the newer installers currently do not remove a migrated HexEditor.dll at the new plugin folder structure.
