### ISSUE TITLE
Notepad++ can crash by launching it with specific commandline

### ISSUE THREAD

**Issue by CookiePLMonster** [notepad-plus-plus/notepad-plus-plus#4621]
### Description of the Issue
If running Notepad++ in mono-instance mode, it is possible to crash the instance by trying to open a new one with specific commandline arguments. A quick scan through the code reveals that commandline arguments are passed between instances via `WM_COPYDATA` - but it also tries to pass two fields of type `std::string`! Since it's illegal to move pointers between applications like this, code attempting to assign said strings will crash a currently opened Notepad++ instance. Therefore, it is technically possible to write a "npp killer" batch script.

### Steps to Reproduce the Issue
1. Make sure your Notepad++ is running in mono-instance mode.
2. Open any file via Notepad++ - without using any commandline arguments, like so:
```notepad++.exe file1.txt```
3. Open another file - this time, passing a file name and a valid string-based commandline argument (like `-L`):
```notepad++.exe -Lpl file2.txt```
4. Observe a crash.

### Expected Behavior
Notepad++ opens a new file in currently opened instance.

### Actual Behavior
Notepad++ crashes.

### Debug Information
I have verified the bug on released v7.5.6 and also on self-compiled up to date code, so v7.5.7 does not fix it.

Notepad++ v7.5.6   (64-bit)
Build time : Mar 19 2018 - 00:23:17
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10 (64-bit)
Plugins : DSpellCheck.dll mimeTools.dll NppConverter.dll

Since this is also a problem on current version, I will follow with a PR fixing this shortly.

**Comment by CookiePLMonster** [comment]
Fixed with #4622

**Comment by donho** [comment]
@CookiePLMonster I can reproduce the crash. Thank you.
How come `-Lpl` make Notepad++ crash?

**Comment by CookiePLMonster** [comment]
The structure which was passed contained a non-POD type, std::string. Passing data is obviously a shallow copy, so with `-Lpl` this string held a "pl" string - thus, shallow copy of std::string passed pointers of instance A to instance B, but not their contents. Thus, trying to access the string crashed.

I created this DTO object as a PDO type, which can be safely copied around. I could have also passed those strings safely, but they are **not** used after being passed to a new instance anyway.
