### ISSUE TITLE
Building Notepad++

### ISSUE THREAD

**Issue by levimatheri** [notepad-plus-plus/notepad-plus-plus#4623]
### Description of the Issue
I'm trying to build Notepad++ on vs2013 using notepadPlus.vs2013.vcxproj

I am getting errors on json.hpp such as:

`Error	1	error C3646: 'noexcept' : unknown override specifier (..\src\WinControls\PluginsAdmin\pluginsAdmin.cpp)	E:\Source\notepad-plus-plus\PowerEditor\src\json\json.hpp	172	1	Notepad++
`   I had tried building in vs2017 but Building scilexer.dll failed

**Comment by ClaudiaFrank** [comment]
@bfridkis was so kind to describe in detail what needs to be done [here](https://github.com/bfridkis/Building-Notepad-Plus-Plus-from-Source-A-Beginners-Guide)

**Comment by levimatheri** [comment]
Thanks!
