### ISSUE TITLE
search and replace of "\" doesn't work

### ISSUE THREAD

**Issue by 54696d21** [notepad-plus-plus/notepad-plus-plus#4625]
I run version 7.5.6 on Win 10 64bit

I tired search and replace of "\" with "\\" in the string listed below

 but it doesn't work for this character although it says that it replaced 8 instances

C:\Users\me\AppData\Local\Programs\Python\Python36\python.exe 

![notepadd_plus_plus_bug](https://user-images.githubusercontent.com/24454966/42215965-7c50f776-7ec0-11e8-85f6-6d178746e21e.JPG)

**Comment by ClaudiaFrank** [comment]
use Suchmodus Normal instead of the Erweitert.

**Comment by 54696d21** [comment]
ok, thanks :) But why does it report that there were 8 instances replaced?

**Comment by ClaudiaFrank** [comment]
Actually you replaced the existing backslashes by backslashes.
By defining the extended (Erweitert) search mode the replace part (Ersetzen durch) treats the first backslash as a escaping char for the next char.

**Comment by 54696d21** [comment]
I see. Thank you and I'm sorry for taking your time.
