### ISSUE TITLE
English.xml has superflous spaces before colon (:)

### ISSUE THREAD

**Issue by ordtrogen** [notepad-plus-plus/notepad-plus-plus#4628]
For example line 346:                &lt;Item id="1620" name="&amp;amp;Find what :"/&gt;

Note there is a space character before the colon at the end of the line.  This is standard practice in French, for example, but not in English.  The space before colon is not there everywhere in english.xml, only 16 occurrences

Suggestion: remove these spaces in english.xml and only add them in the translation to a language that requires them.

**Comment by ArkadiuszMichalski** [comment]
@donho 
In most case in english.xml this additional space is not added, only in:
```<Item id="1620" name="&amp;Find what :"/>
<Item id="1611" name="Rep&amp;lace with :"/>
<Item id="1654" name="Filter&amp;s :"/>
<Item id="1655" name="Dir&amp;ectory :"/>
<Item id="6217" name="Width :"/>
<Item id="6219" name="Blink rate :"/>
<Item id="6411" name="Default language :"/>
<Item id="6306" name="Max. number of entries :"/>
<Item id="6803" name="Directory :"/>
<Item id="6814" name="Valid value : 1 - 9"/>
<Item id="8006" name="Macro to run :"/>
<Item id="2030" name="Initial number :"/>
<Item id="2031" name="Increase by :"/>
<Item id="2036" name="Repeat :"/>
<Item id="1711" name="&amp;Find what :"/>
<replace-in-files-confirm-directory value="Are you sure you want to replace all occurrences in :"/>
<replace-in-files-confirm-filetype value="For file type :"/>
```
It's intentional? If not it can be easy fix and close this bug.
