### ISSUE TITLE
Inconsistent terminology: mixes 'folder' and 'directory' in english.xml

### ISSUE THREAD

**Issue by ordtrogen** [notepad-plus-plus/notepad-plus-plus#4629]
Why mix "folder" and "directory" in the UI? They seem like synonyms to me. Suggestion: use "folder" consistently.

In one place, they are even used in the same sentence:
"You can only drop files or folders but not both, because you're in dropping Folder as Project mode.
you have to enable &amp;quot;Open all files of folder instead of launching Folder as Workspace on folder dropping&amp;quot; in &amp;quot;Default Directory&amp;quot; section of Preferences dialog to make this operation work."
            
(Yes, "directory" has an additional meaning, as in "directory services", "Microsoft Active Directory", but that doesn't seem to be intended in NPP)

**Comment by donho** [comment]
Default Directory is the name of section, so I don't think that makes users confused.
