### ISSUE TITLE
High hard drive load when opening files from Recent Files menu

### ISSUE THREAD

**Issue by hozuki** [notepad-plus-plus/notepad-plus-plus#463]
Has anybody bump into the problem that the hard drive load runs to 50% when opening documents from Recent Files? I have to wait 30 secs for loading a 1 KB source code file.
Other ways of loading the same file are fine, such as drag-and-drop, from the Explorer context menu, or simply double-click it (through command line).

---

Additional:
This problem occurs after an update published this year, 6.7.8 I'm afraid.

**Comment by ariccio** [comment]
This sounds like a job for [`UIforETW`](https://github.com/google/UIforETW)! 
Try to repro under `UIforETW`?

**Comment by donho** [comment]
Cannot reproduce it.
