### ISSUE TITLE
if statement never evaluates to true

### ISSUE THREAD

**Issue by Solomon1732** [notepad-plus-plus/notepad-plus-plus#4634]
### Description of the Issue
The function base64ToAscii in [Parameters.cpp](https://github.com/notepad-plus-plus/notepad-plus-plus/blob/master/PowerEditor/src/Parameters.cpp) has the following if statement:
```
if ((uc0 == -1) || (uc1 == -1) || (uc2 == -1) || (uc3 == -1))
    return -1;
```
However, this statement will never evaluate to `true`, since all the `uc*` variables are `UCHAR`, which can never expand to `-1` due to `UCHAR` being an unsigned type (smaller than an `int`) that doesn't have a sign to extend. Therefore the `if` statement will never evaluate to `true`. Therefore the function never returns the `-1` like it should in some cases.

The problem originates from the initialization code directly above it, which uses the `int` typed lookup table named `base64IndexArray`, which is used in the following manner:
```
UCHAR uc0, uc1, uc2, uc3, p0, p1;

uc0 = (UCHAR)base64IndexArray[base64Str[j]];
uc1 = (UCHAR)base64IndexArray[base64Str[j+1]];
uc2 = (UCHAR)base64IndexArray[base64Str[j+2]];
uc3 = (UCHAR)base64IndexArray[base64Str[j+3]];
```

Some of the entries in `base64IndexArray` are `-1`, which loses the sign information when cast to `UCHAR`.

**Comment by donho** [comment]
obsolete.
