### ISSUE TITLE
Feature request: anchored recent file

### ISSUE THREAD

**Issue by wh11204** [notepad-plus-plus/notepad-plus-plus#4639]
Sometimes a file is frequently edited but hard to locate due to deep paths or virtual folders (example: the hosts file in Windows 10). Sometimes when you need to edit again that file it has dissapeared from the recent files list.

I propose adding the possibility of anchoring the file to the recent file list or creating an anchored file list.

**Comment by sasumner** [comment]
How about setting a favorite file with the Explorer plugin?

**Comment by ArkadiuszMichalski** [comment]
@wh11204 What about with buld-in Project(s) if you don't want Explorer plugin:)

**Comment by sasumner** [comment]
I think Explorer plugin solves it nicely, plus we never heard more from the OP, so, closing.
