### ISSUE TITLE
Problem opening url enclosed with '()'

### ISSUE THREAD

**Issue by teh-botol** [notepad-plus-plus/notepad-plus-plus#4643]
### Description of the Issue
The format link for github is enclosed with '()'. When open the link from N++, the trailing ')' end up as part of the url.
```
Example:
[Notepad++ Contributors](https://notepad-plus-plus.org/contributors)
Browser:
Url -> "https://notepad-plus-plus.org/contributors)"
```
This behavior is visible through underline of the link.

### Steps to Reproduce the Issue
1. Open any *.md from git
2. Double click any link enclosed by '()'

### Expected Behavior
The trailing ')' is NOT considered part of the url. 

### Actual Behavior
The trailing ')' is considered part of the url. 

### Debug Information
Notepad++ v7.5.6   (32-bit)
Build time : Mar 19 2018 - 00:26:59
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : ON
Local Conf mode : OFF
OS : Windows 7 (64-bit)
Plugins : Explorer.dll LightExplorer.dll mimeTools.dll NppConverter.dll PluginManager.dll 

Best Regards,
Adit

**Comment by Yaron10** [comment]
If anyone is going to work on this.

A similar common issue:
If a dot (.) is added at the end of the URL, it is not interpreted correctly.

And a related issue.
STR:
Double-click a URL. 
Return to NPP.

Result:
Hovering over *any area* in NPP, the mouse cursor is an "edit-cursor" until left-clicking somewhere.

Thank you.

**Comment by ArkadiuszMichalski** [comment]
Similar to https://github.com/notepad-plus-plus/notepad-plus-plus/issues/5029.

**Comment by Yaron10** [comment]
Can be closed. Thanks.
