### ISSUE TITLE
Issue: Default session's unsaved files are lost (from session's XML file) after closing Notepad++ in a different session

### ISSUE THREAD

**Issue by ghost** [notepad-plus-plus/notepad-plus-plus#4648]
### Description
The checkbox for “Enable session snapshot and periodic backup” becomes unchecked if I close any session other than the default session.

This leads to the default session's unsaved files being foregone the next time it's loaded.

Note: **The problem was introduced between versions 7.1 and 7.2**

### Steps to Reproduce
[_using Notepad++ version 7.5.7_]

1. Open the **default** session.
2. Create a new file and write something inside it.
3. Go to Settings->Preferences->Backup and ensure 'Enable session snapshot and periodic backup' is checked
4. [_optional_] Create a **different** session to be used in step 6. For example, save an XML file containing the following:

```
<NotepadPlus>
    <Session activeView="1">
        <mainView activeIndex="0" />
    </Session>
</NotepadPlus>
```

You may save it as something like 'notepad++_different_session.XML' to anywhere you can access easily.

5. Close the **default** session. Do not save the file created on step 2 before doing so. (This requires no action. There will not be a dialog asking you to save the file from step 2 if you followed step 3.)
6. Open a **different** session (e.g. use 'notepad++_different_session.XML' as described in step 4).
7. Close this session and reload Notepad++'s **default** session.

### Expected Behavior
The default session should reload with all unsaved files remaining.

Note: The checkbox for “Enable session snapshot and periodic backup” is automatically disabled within any session other than the default session. Therefore, this setting should not be saved upon closing for any session other than the default session. This is exactly how it behaved in version 7.1!

### Actual Behavior
The default session does not reload with all unsaved files remaining.

### Debug Information
Notepad++ v7.5.7   (64-bit)
Build time : Jun 29 2018 - 00:53:58
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 7 (64-bit)
Plugins : DSpellCheck.dll mimeTools.dll NppConverter.dll

**Comment by molten-cyborg-legs** [comment]
The problem was introduced between versions 7.1 and 7.2

**Comment by bigharm** [comment]
A different session can be opened by a GIT commit with Notepad++ as the default editor. So this issue can happen very often for a GIT user.

**Comment by toasty-hdds** [comment]
So what's going on?

**Comment by toasty-hdds** [comment]
You may read https://github.com/notepad-plus-plus/notepad-plus-plus/issues/5063#issuecomment-444662448 for further details.

**Comment by Ron2** [comment]
I ran into this problem as a git user. People who use Notepad++ with git by following answers on StackOverflow are going to have a bad experience when they lose their default Notepad++ session unexpectedly.

What if the -nosession flag caused the “Enable session snapshot and periodic backup” user preference to be disabled in the Preferences dialog box, and that this preference would not be persisted by this instance of Notepad++?

**Comment by MetaChuh** [comment]
@Ron2 

> People who use Notepad++ with git by following answers on StackOverflow are going to have a bad experience when they lose their default Notepad++ session unexpectedly.

yes you are correct, it is recommended to recheck stack information with the notepad++ community, due to the higher knowledge of the internals of notepad++. 

i agree that it would be best to disable multi instance as an option as well as ignore the -nosession
-multiinst cli arguments, as soon as snapshot is enabled, as both are not compatible.
either one or the other should be greyed out at the settings.

ps: did you have time to try using an isolated notepad++ instance for git, as you saw at the community ?

best regards

**Comment by Ron2** [comment]
Thank you, @MetaChuh , for instructions on how to properly use Notepad++ with git until this bug can be fixed. I haven't personally tried that work-around, but I expect that it would work. In case others find this post, here are those instructions: https://notepad-plus-plus.org/community/topic/16488/enable-session-snapshot-and-periodic-backup-box-unchecked/16

**Comment by toasty-hdds** [comment]
https://github.com/notepad-plus-plus/notepad-plus-plus/issues/5449

**Comment by donho** [comment]
Fixed by https://github.com/notepad-plus-plus/notepad-plus-plus/commit/b3a6638b936c097c5323814fe046b6ddc75695cc
