### ISSUE TITLE
Save File dialog not working as expected

### ISSUE THREAD

**Issue by BernieStn** [notepad-plus-plus/notepad-plus-plus#4651]
### Description of the Issue
When a path is pasted into the SaveFile dialog, Notepad++ reports that the path already exists instead of changing the working directory to that path.

### Steps to Reproduce the Issue
1. Start Notepad++
2. Enter some arbitrary characters
3. Click the "Save" button in the toolbar or press Ctrl+S
4. The SaveAs dialog opens.
5. Paste an existing path to the "Filename" field and hit return, e.g. C:\Windows\Temp

### Expected Behavior
Like in other Windows applications (I'm using Notepad++ on Windows), I expect that the SaveFile dialog changes the working directory to the path which I pasted. Once it is changed, I can type the filename to save the file, which will then be saved in the pasted directory.

### Actual Behavior
After hitting the return key, a message box appears:

Temp ist bereits vorhanden. (engl: Temp already exists)
Möchten Sie sie ersetzen? (engl: Do you want to replace it?)
[Ja] [Nein] (engl: Yes, No)

This worked fine in previous releases of Notepad++. Since some months, this doesn't work anymore

### Debug Information
Notepad++ v7.5.7   (64-bit)
Build time : Jun 29 2018 - 00:53:58
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 7 (64-bit)
Plugins : none

**Comment by sasumner** [comment]
Try changing the setting on the "Use new style save dialog..." checkbox in Preferences and see if it behaves differently.

**Comment by levimatheri** [comment]
@sasumner Your solution works on mine. This should be closed now

**Comment by sasumner** [comment]
@levimatheri YOU have the power to close this issue; I don't.

**Comment by levimatheri** [comment]
I didn't open this issue. I don't know what you're talking about

**Comment by sasumner** [comment]
@levimatheri Oops, sorry.  
If @BernieStn agrees, he should close it.

**Comment by BernieStn** [comment]
Ok, thanks all for your support. I agree and close the issue.
