### ISSUE TITLE
Double dash in XML comment is not allowed and should be highlighted as error.

### ISSUE THREAD

**Issue by boldandfunny** [notepad-plus-plus/notepad-plus-plus#4652]
### Description of the Issue
Example of illegal XML comment below:

### Steps to Reproduce the Issue
Use comment above in a valid  .XML file. 
"--" should be highligted as an XML error

### Expected Behavior
Usual XML syntax error behaiviour.

### Actual Behavior
"--" and the rest of comment is shown as valid comment.

### More info:
From the standards document:

http://www.w3.org/TR/REC-xml/#sec-comments

[Definition: Comments may appear anywhere in a document outside other markup; in addition, they may appear within the document type declaration at places allowed by the grammar. They are not part of the document's character data; an XML processor may, but need not, make it possible for an application to retrieve the text of comments. For compatibility, the string " -- " (double-hyphen) must not occur within comments.] Parameter entity references must not be recognized within comments.

**Comment by ArkadiuszMichalski** [comment]
@donho Notepad++ doesn't validate the syntax, it's not an area for plugins, like https://github.com/morbac/xmltools?

**Comment by donho** [comment]
@ArkadiuszMichalski 
Agree with you.

@boldandfunny 
Please use plugin `xmltools` as XML validation tool.
