### ISSUE TITLE
Folder as Workspace: Double clicking a file doesn't move focus to edit area

### ISSUE THREAD

**Issue by Antti29** [notepad-plus-plus/notepad-plus-plus#4656]
### Description of the Issue
As far as I know, there are three ways to open a file from Folder as Workspace:

1. Double click a file
2. Right click a file -> Open
3. Select a file and press Enter

Of these, the double click method is the only one that doesn't move focus to the edit area.

### Expected Behavior
The focus should move to the edit area.

### Actual Behavior
Focus remains in the Folder as Workspace area.

**Comment by ArkadiuszMichalski** [comment]
I can confirm this bug, it's still exist:
```
Notepad++ v7.8.6   (32-bit)
Build time : Apr 21 2020 - 15:17:06
Path : D:\_test\NPPClean\notepad++.exe
Admin mode : ON
Local Conf mode : ON
OS Name : Windows 7 Ultimate (64-bit) 
OS Build : 7601.0
Plugins : none

```
