### ISSUE TITLE
Mousewheel support on the tabbar for Next/Prev Tab

### ISSUE THREAD

**Issue by XeonG** [notepad-plus-plus/notepad-plus-plus#4657]
Basically mousewheel up/down does absolutely nothing when the cursor is over the tabbar.. this should ideally switch the active tab document.

Notepad++ provides shortcut hotkeys like [ctrl]+[pgup]/[pgdn] for back/forth /cycling through tab documents.. sadly you can't map mouse buttons in the shortcut mapper otherwise I would have done this already...  ie [ctrl]+[mousewheel up/down]  

Though that would work anywhere in notepad++... ideally having the tabbar register mousewheel changes when the mouse cursor is actually over the tabbar would be better!

**Comment by rddim** [comment]
Which version of N++ did you use? In the latest 7.5.7 `ctrl`+`mousewheel up/down` provide tabs cycling and the `shift`+`mousewheel up/down` move the selected tab back/forward.

**Comment by MetaChuh** [comment]
please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins if you update from version 7.5.9 or below.

thank you for your help and best regards.

**Comment by sasumner** [comment]
@XeonG There is a good description of tab switching under #4514 ; does any of that solve your problem by explaining how things work?

**Comment by XeonG** [comment]
> @XeonG There is a good description of tab switching under #4514 ; does any of that solve your problem by explaining how things work?

... I've  already explained how it should work with the mouse wheel over the tabbar to switch active document tab. Pretty simple feature to implement and far more useful for switch/comparing documents, directly without having to use the and more and useless ctrl+tab implementation which is really only useful for a different type of workflow of document switching... the I've described is far quicker for document switching and or comparing quickly.

Anyway holding ctrl+ mousewheel over the tabbar does work.... seems kinda silly, having to hold ctrl for it to work, its not like mousewheel over the tabbar does anything else, instead of just working without mousewheel while cursor is over the tabbar, I guess at least its somewhat of a implementation that works better than ctrl+tab... for switching.

**Comment by sasumner** [comment]
>seems kinda silly, having to hold ctrl for it to work

Maybe it is a safety mechanism: Maybe you are mousewheel scrolling your document and you are near (X,Y) the tab bar and then you accidentally slip INTO the tab bar area with your mouse X,Y...and then WTF happened...how did I even get into this doc???

**Comment by XeonG** [comment]
I've never had that problem in any other app that has supported mousewheel on a tabbar for switching... sure it could happen, but then you just mousewheel the opposite direction and you are back.. but I've never  ever in decades had to do that, for starters, most people who are using the mousewheel aren't even moving the mouse position..... so they' have to drunk to be moving the mousewheel up towards the tabbar and using the mousewheel at the same time to scroll the page...

seriously if anyone thought that making that an operation that can only be used with ctrl+mousewheel because of that is on something.. but whatever at least notepad++ actually has a tab bar that supports a multibar tabbar and  actual mousewheel changing of tabs even if it does have to use a ctrl modifier... unlike vscode... just terrible how bad that is for a tabbar implementation... I wonder how many years it will take MS to add support for that.. ridiculous really, so just one of the reasons I'll still use notepad++

can close the issue.. unless someone could actually just remove the ctrl modifier for when the cursor is over the tabbar and the mouseewheel is used...I don't see a valid reason for the ctrl modifier personally.

**Comment by sasumner** [comment]
@XeonG Well, we've considered your perspective, but it's pretty clear from your posting that that's all you've considered, or even can consider.  Cheers, mate.  BTW, I wouldn't hold your breath waiting for a behavior change in Notepad++.
