### ISSUE TITLE
Converting "NUL" from ASCII to Hex results in "20" (space) instead of "00".

### ISSUE THREAD

**Issue by NOYB** [notepad-plus-plus/notepad-plus-plus#4658]
### Description of the Issue
Converting "NUL" from ASCII to Hex results in "20" (space) instead of "00".

### Steps to Reproduce the Issue
Using Plugins -> Converter
Converting "00" from HEX to ASCII results in "NUL" as expected.
Converting "NUL" from ASCII to HEX results in "20" instead of "00".
Converting "20" from HEX to ASCII results in " " (space).
Converting " " (space) from ASCII to HEX results in "20" (space).

### Expected Behavior
Converting "NUL" from ASCII to HEX resulting in "00"

### Actual Behavior
Converting "NUL" from ASCII to HEX results in "20" instead of "00".

### Debug Information
Notepad++ v7.5.7   (64-bit)
Build time : Jun 29 2018 - 00:53:58
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 8.1 (64-bit)
Plugins : DSpellCheck.dll mimeTools.dll NppConverter.dll

**Comment by levimatheri** [comment]
Seems the converter sees NUL as Space instead of \x0

**Comment by MetaChuh** [comment]
@NOYB 

as this is plugin related, please visit and use the plugin's issue tracker at https://github.com/npp-plugins/converter/issues
please also see the opened issue https://github.com/npp-plugins/converter/issues/5 as mentioned above.

thank you for your help and best regards.

-----
```
general notes:

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
(no extra account is needed, just use your github account to sign in)
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)
