### ISSUE TITLE
Vertical Tab option with Horizontal Title - enhancement

### ISSUE THREAD

**Issue by mariusft** [notepad-plus-plus/notepad-plus-plus#4661]
### Description of the Issue
Preferences -> General -> Tab - Bar - Vertical
Will move the tabs to the left but the titles are Vertically named and is hard to read their titles.
Tabs should have the option to have the titles horizontally and stacked one under/over each other.

### Steps to Reproduce the Issue
1. Preferences 
2. General
3. Tab Bar
4. check Vertical

### Expected Behavior
Tabs to stacked and titles on horizontal

### Actual Behavior
Tabs titles are vertical and hard to read them

### Debug Information
Valid with NotePad++ 7.5.7

**Comment by AngryGamer** [comment]
Settings->General->Document List Panel->Show ✔

Ctrl+shift and Page Up/Down hotkey to re-arrange while tab bar is hidden. Otherwise you can use tab bar to re-arrange in Doc Switcher.

**Comment by mariusft** [comment]
@AngryGamer good alternative, thank you.

**Comment by token0** [comment]
Document switcher is a very bad alternative. You can't close tab by middle mouse button. Also you can't rearrange tabs with mouse. And try to rearrange tabs with drag'n'drop on tab bar with document switcher opened (to see the issue, open a lot of files). On each change of tab position, document switcher will bubble-sort entire list. That's inefficient and time-consuming.

**Comment by KnIfER** [comment]
It's achievable via [custom tab control.](https://github.com/KnIfER/MyTabControl32/blob/main/tab.cpp)


![image](https://user-images.githubusercontent.com/11593903/115498953-77eb1580-a2a9-11eb-89e1-c6d2060996f8.png)

**Comment by jan-vandenberg** [comment]
This looks like what  I want @KnIfER ! But your link is broken?

**Comment by gmikhaile** [comment]
> This looks like what I want @KnIfER ! But your link is broken?

Haha, perfect timing, I was lookin for this kind of orientating as well

**Comment by gmikhaile** [comment]
> This looks like what I want @KnIfER ! But your link is broken?

Check [this](https://github.com/notepad-plus-plus/notepad-plus-plus/issues/949)

**Comment by Nexusmeister** [comment]
Is there any progress or an update on this? Visual Studio has this feature and I miss it very badly in NotePad

**Comment by alankilborn** [comment]
"Document list" is probably so close an alternative that devs won't bother implementing anything similar.

**Comment by jan-vandenberg** [comment]
Yes, second that.  The Document List is what I have been using also.
My only request for the Doc List would be to be able to sort by last modified (i.e. so my last editted files are always on top). 
Now you can only manually sort the files in the Notepad++ Document List with CTRL-SHIFT-PAGE-UP/DOWN (putting this here for future reference)

**Comment by Nexusmeister** [comment]
@alankilborn Ahhh didn't know this feature exists. That's what I was looking for. Thx!

**Comment by alankilborn** [comment]
Maybe @mariusft could close this issue?

**Comment by khatrig** [comment]
If you can't find Document List in the General, Go to **View** and select **Document List** to enable it.

**Comment by donho** [comment]
Use Document list instead.

**Comment by Luckz** [comment]
> Use Document list instead.

How is this "completed" given https://github.com/notepad-plus-plus/notepad-plus-plus/issues/4661#issuecomment-583831021 ?

**Comment by Wizzergod** [comment]
> If you can't find Document List in the General, Go to **View** and select **Document List** to enable it.

thank so much, i cant find it i know one time i enable it but not remember where is and cant find because so stupid is in View-documentlist wtf why not in setting tab vertical lol

**Comment by alankilborn** [comment]
>why not in setting tab vertical 

Because Document List is something totally different than tabs being vertical.

**Comment by Gaddy** [comment]
How can we re-open this request ? For me it's really the one missing feature of notedpad++ (after using it for years)
And no, document list is not the same at all, it misses plenty of tab bar options.

**Comment by gunir** [comment]
Please re-open, Document List ISN'T that answer, it can't drag drop to re-order.

**Comment by stefandascalu64** [comment]
Even if Document List is the answer pretending the vertical option is not a broken feature is absurd.
Notepad++ is not used on phones, it's used on desktop PCs and you're always going to have a lot more horizontal real-estate than vertical real-estate. Having the tab text display in vertical form is an absurd solution, even if it was legible which is very much isn't it makes managing multiple files even more cumbersome.
If it can't be fixed I'd argue for removing the option is the next best choice since we at least stop pretending it's not a bug.
