### ISSUE TITLE
multiple Saved Notes

### ISSUE THREAD

**Issue by 2635599** [notepad-plus-plus/notepad-plus-plus#4662]
i'd like to know if there is or if it is possible to have multiple notes open when i click on one. for instance i have the following that i would like to all open at the same time "chrome - comodo extensions.txt" "firefox addons.txt" "current tv series.txt" and "upcoming tv series.txt". the reason is that generally when i'm updating info in one i also update info in the other three. thanks

**Comment by sasumner** [comment]
You could write a script (e.g. with Pythonscript or Luascript...) to do this kind of thing.

**Comment by 2635599** [comment]
not interested in learning to write code

**Comment by sasumner** [comment]
Well your request is so specific to you that writing code to do it is extremely likely your only option.

**Comment by 2635599** [comment]
while the .txt files i want to group together may be specific to me wanting the ability to open multiple .txt files with a single click is not specific to me alone. plus plenty of programs have the ability to open a saved group / set of files.

**Comment by sasumner** [comment]
good luck

**Comment by sasumner** [comment]
Yea, sometimes it takes a bit of back-and-forth discussion to ferret out what someone is really asking for.  And then often it turns out to be something Notepad++ can already do, or close to it.  If existing functionality works good enough for you, please close this issue.  Cheers.
