### ISSUE TITLE
Can't use TextFX hex-to-decimal in a macro

### ISSUE THREAD

**Issue by pmthompson** [notepad-plus-plus/notepad-plus-plus#4664]
### Description of the Issue
I put the "TextFX / Convert / Convert Hex number to decimal" sequence in a Macro. When I replay that Macro the hex-to-decimal conversion inserts weird characters

### Steps to Reproduce the Issue

1. Start Recording
2. Select TextFX / Convert / Convert Hex Number to Decimal
3. Stop Recording
4. Select a Hex number sequence ("0x00000013").  Playback macro.

### Expected Behavior
Expected to see "0x00000013" converted to "19".  This is what happens if I select the hex string and execute the sequence to do TextFx Hex conversion manually.

### Actual Behavior
Notepad++ changes "0x00000013" to "1{NUL}" where "{NUL}" is an ASCII NULL character.

### Debug Information
Notepad++ v7.5.7   (32-bit)
Build time : Jun 29 2018 - 00:46:55
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10 (64-bit)
Plugins : ComparePlugin.dll JSLintNpp.dll NPPJSONViewer.dll NppTextFX.dll PluginManager.dll Tidy2.dll XMLTools.dll DSpellCheck.dll mimeTools.dll NppConverter.dll NppExport.dll

**Comment by sasumner** [comment]
You can't complain about TextFX issues here, this is for Notepad++ issues only.  Please close this issue.

**Comment by MetaChuh** [comment]
@pmthompson 

please contact the author of the textfx plugin for textfx support.

thank you for your help and best regards.
