### ISSUE TITLE
Save As dialog doesn't recognize an existing directory

### ISSUE THREAD

**Issue by al--** [notepad-plus-plus/notepad-plus-plus#4665]
### Description of the Issue
If you put the path (either full or relative) of an existing directory into the File name textbox and press Save, a "do you want to replace" dialog is displayed. Instead, it should change to that directory, display the content, reset the File name textbox and let the user go on.

### Steps to Reproduce the Issue
(Windows 7)
1. File | Save As
2. -> opens Save As dialog
3. put the path of an existing directory into the "File name" textbox
4. click "Save"
5. -> gives you a dialog saying:
  $DIRECTORY already exists.
  Do you want to replace it?

### Expected Behavior
Instead, it should
  - recoginize the existing directory
  - change to that directory
  - display the content of that directory
  - reset the "File name" textbox to the default new filename
     (that was there when the Save As dialog opened)

This is standard behavior (at least in Windows).

### Actual Behavior
dialog box
  $DIRECTORY already exists.
  Do you want to replace it?
is displayed.

### Debug Information
Notepad++ v7.5.6   (32-bit)
Build time : Mar 19 2018 - 00:26:59
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 7 (32-bit)
Plugins : ComparePlugin.dll DSpellCheck.dll Explorer.dll FingerText.dll mimeTools.dll NppConverter.dll NppExport.dll PluginManager.dll QuickText.UNI.dll Tidy2.dll XMLTools.dll 

![step1](https://user-images.githubusercontent.com/1458456/42720868-f669d9c0-872f-11e8-9388-f1bf4c1bd075.png)
![step2](https://user-images.githubusercontent.com/1458456/42720871-fd700014-872f-11e8-9246-5765d2df28f6.png)

**Comment by sasumner** [comment]
Please search for existing issues before creating duplicates... #4651

**Comment by ArkadiuszMichalski** [comment]
@sasumner Still needed this, previous was closed.

**Comment by mere-human** [comment]
This also has a duplicate #4698
In version 7.9.3 file dialogs have been updated so this problem isn't reproducible anymore.
@sasumner Could you, please, close this issue?
