### ISSUE TITLE
Find \n (extended search mode) or . (regex search mode, . matches newline) not working with Windows or Macintosh type EOL 

### ISSUE THREAD

**Issue by pavelpetrovic** [notepad-plus-plus/notepad-plus-plus#4669]
### Description of the Issue

Searching using usual Find dialog does work properly when using \n in extended search mode or period character in regex search mode while the ". matches newline" checkbox is selected, if the file has the EOL in the Windows format - CR LF, or Macintosh format - CR. The search works with Unix line endings - LF.

### Steps to Reproduce the Issue
1. open new file
2. enter five characters 1 2 1 1 2 - each on a separate line, terminate with ENTER after each
3. press CTRL-F, select Search Mode - Extended
4. enter "1\n1" in "Find what:" input control
5. press the Find Next button 

alternate scenario:

1. & 2 - as above
3. press CTRL-F, select Search Mode - Regular expression
4. select the ". matches newline" checkbox
5. enter "1.1" in "Find what:" input control
6. press the Find Next button 

### Expected Behavior
The two consecutive lines containing number 1 should be located and selected.

### Actual Behavior
Find dialog displays "Find: Can't find the text "1\n1" or  "Find: Can't find the text "1.1"

### Debug Information
Notepad++ v7.5.7   (64-bit)
Build time : Jun 29 2018 - 00:53:58
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10 (64-bit)
Plugins : DSpellCheck.dll mimeTools.dll NppConverter.dll 

When the file is converted to Unix EOL, the find operation works as expected.

**Comment by dinkumoil** [comment]
As you already mentioned, Windows EOL format is CR+LF (carriage return + line feed) which is encoded as `\r\n`. The Macintosh EOL format is CR (carriage return only) which is encoded as `\r`.

Why do you expect that the **two** characters `\r\n` (Windows EOL format) are found by the **single character** search expression `\n` or `.`? And why do you expect that the character `\r` (Macintosh EOL format) is found by the search expression `\n`?

With Macintosh EOL format in your example the search expression `1.1` succeeds.

Everything works like expected, please close this issue.

**Comment by pavelpetrovic** [comment]
Well, just to answer your question, one would expect it becdause printing \n in C code on Windows produces a Windows new line CR LF. So how should one guess that here it does not mean the same? 
But I accept your explanation.

Still the 1.1 regular expression could work for Windows EOL too. How could one type a new line as a regular expression? It is needed when the extended syntax search mode is not sufficient.

Feel free to close the issue if you are responsible for that.

**Comment by dinkumoil** [comment]
I'm not responisble for anything, I'm just a guy.

I agree that the built-in english localization could be missleading as it speaks of ". matching newline":

![grafik](https://user-images.githubusercontent.com/24699812/42755610-37fd25ca-88f9-11e8-9f8e-31170c318bae.png)

Maybe you should close this issue and report another issue concerning this ambiguous expression. But don't be too optimistic that it gets resolved... Just my 2 cents.

**Comment by pavelpetrovic** [comment]
Thanks. 
You are right, it's probably just been a Monday morning issue :) 
I close it.
