### ISSUE TITLE
Notepad++ - Memory cannot be written on shutdown

### ISSUE THREAD

**Issue by RofWh00** [notepad-plus-plus/notepad-plus-plus#4671]
### Description of the Issue
randomly when I shut down Notepad++ I get the following error dialog 
---------------------------
notepad++.exe - Application Error
---------------------------
The instruction at 0x00000000089531FE referenced memory at 0x00000000089531FE. The memory could not be written.

Click on OK to terminate the program
Click on CANCEL to debug the program
---------------------------
OK   Cancel   
---------------------------

### Steps to Reproduce the Issue

1. I am editing INF ,CMD and INI files and using Notepad++ v7.5.7 
2. I save the file I am working on and exit notepad ++
3. I get the error dialog mentioned above

### Expected Behavior
The software would exit without any errors

### Actual Behavior
NP++ shuts down followed by the error dialog

### Debug Information
Notepad++ v7.5.7   (32-bit)
Build time : Jun 29 2018 - 00:46:55
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10 (64-bit)
Plugins : ComparePlugin.dll DeruniCrypt.dll JSMinNPP.dll NppFTP.dll NppInfSearch.dll nppplugin_ofis2.dll nppplugin_solutionhub.dll nppplugin_solutionhub_ui.dll nppplugin_solutiontools.dll nppplugin_svn.dll NppTextFX.dll NPP_CacheHelper.dll PluginManager.dll SelectNLaunch.dll SpellChecker.dll wikieditor.dll XMLTools.dll ________________________nppplugin_solutionhub_ui.dll DSpellCheck.dll mimeTools.dll NppConverter.dll NppExport.dll 

Visual Studio 2017 offers the following info
Unhandled exception at 0x064531FE in notepad++.exe: 0xC0000005: Access violation executing location 0x064531FE.
and 
![image](https://user-images.githubusercontent.com/41296958/42763850-76d7d176-8914-11e8-9089-ff69437f68bb.png)

hope the info helps

**Comment by DavidHansen-0x454d43** [comment]
@RofWh00, it is probably one of your plugins causing this error. I'd suggest disabling them all and seeing if you can still reproduce the error. If you can't then try adding them back in one at a time until you _can_ reproduce it again. I'd suggest starting with NppInfSearch, as it sounds like the most likely culprit.

**Comment by ArkadiuszMichalski** [comment]
@RofWh00 Nice plugins list, do you still have this problem in latest Notepad++ version, but please test it without plugin:)
