### ISSUE TITLE
New NPPM_ message needed to remove assigned shortcut keys.

### ISSUE THREAD

**Issue by ClaudiaFrank** [notepad-plus-plus/notepad-plus-plus#4674]
Plugins like PythonScript which do create dynamic menus,
may need an additional message to inform npp that a certain shortcut 
has been invalidated and can be removed from npps internal list 
as well as from shortcuts.xml.

Reason for asking of this:
Using PythonScript plugin one can assign a shortcut key
for every new script which gets assigned as a new dynamic menu item.
If this dynamic menu item gets deleted afterwards, currently,
there is no way to inform npp that the assigned shortcut key is not valid anymore.
On next npp start the entries in shortcuts.xml may be falsely assigned
to the remaining scripts(dynamic menu items).

If there is any other idea how to solve this mismatch I would be glad to hear/discuss it.

**Comment by sasumner** [comment]
A long-standing problem for Pythonscript; hopefully the Notepad++ side can do what is necessary to allow it to be fixed.
