### ISSUE TITLE
v7.5.1 Control-K failed for R script

### ISSUE THREAD

**Issue by chaoyang218** [notepad-plus-plus/notepad-plus-plus#4675]
### Description of the Issue
On v7.5.1, I tried Ctrl-K on multiple lines in R script and semicolons were prepended. However, semicolons are not comment tags for R (should be hashtag/pound sign #)

### Steps to Reproduce the Issue

1.  Create an R script called hello.r
2.  Create several lines (e.g. apple <- c('red','green','yellow')
print(apple)
print(class(apple)))
3. Highlight those lines and do Ctrl-K

### Expected Behavior

I expect hashtag/pound sign (#) to prepend those lines

### Actual Behavior

I got semicolon signs (;) prepended on those lines

**Comment by ClaudiaFrank** [comment]
Works for me on 7.5.6.
Are you sure you don't have another lexer like scheme, asm etc... active, which uses the semicolon as comment char? If so, check your langs.xml file for this line

`<Language name="r" ext="r s splus" commentLine="#">`

**Comment by MetaChuh** [comment]
please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins if you update from version 7.5.9 or below.

thank you for your help and best regards.

-----
```
general notes:

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).
please file an issue as easy to understand and reproducible as possible.

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
(no extra account is needed, just use your github account to sign in)
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)
