### ISSUE TITLE
Stutter in resizing Explorer Windows and columns

### ISSUE THREAD

**Issue by TheRealDadbeard** [notepad-plus-plus/notepad-plus-plus#4676]
### Description of the Issue
After installing newest version of Notepad++ resizing windows and resizing colums in explorer stutter heavily.

### Steps to Reproduce the Issue

Just installling with default settings with added german translation

### Expected Behavior
Nothing
### Actual Behavior
Stutter everywhere

**Comment by sasumner** [comment]
Are you saying that Notepad++ is using a high amount of CPU cycles, from Windows Explorer in your case?  If so, can you put some data to that?

**Comment by TheRealDadbeard** [comment]
No just installing 7.5.7 with default settings adding german language resizing windows and the columns in them stutter like crazy.

Just installed 7.5.6 and no issues at all.

Installing 7.5.7 without context menu entry makes the issue dissapear too

**Comment by MetaChuh** [comment]
please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins if you update from version 7.5.9 or below.

thank you for your help and best regards.

-----
```
general notes:

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).
please file an issue as easy to understand and reproducible as possible.

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
(no extra account is needed, just use your github account to sign in)
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)
