### ISSUE TITLE
Exception thrown on rendering file content

### ISSUE THREAD

**Issue by greaka** [notepad-plus-plus/notepad-plus-plus#4678]
### Description of the Issue
On almost every rerender of a file content in a specific file, I get an exception as shown below: 
![image](https://user-images.githubusercontent.com/2805834/42892456-2d183fcc-8ab2-11e8-8b15-074c0f9f825e.png)
I provided the file below. Originally, it is a compiled shader *.spv but since Github doesn't like this ending, I renamed it to *.log. It is also throwing exceptions with *.log.
[frag.log](https://github.com/notepad-plus-plus/notepad-plus-plus/files/2206430/frag.log)

I even renamed my plugins folder temporarily and restarted n++, same result.

Since I don't know if someone could abuse this to execute code or something, I reported it here.

### Steps to Reproduce the Issue
1. view the provided file
2. If you like, you can also try to scroll or switch tabs etc, same outcome.

### Expected Behavior
Not throwing an exception.

### Actual Behavior
Throwing an exception

### Debug Information
Notepad++ v7.5.6   (64-bit)
Build time : Mar 19 2018 - 00:23:17
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10 (64-bit)
Plugins : ComparePlugin.dll DSpellCheck.dll mimeTools.dll NppConverter.dll PluginManager.dll

**Comment by MetaChuh** [comment]
please remove the dspellcheck plugin.

thank you for your help and best regards.
