### ISSUE TITLE
CTRL+F4 does not close tab

### ISSUE THREAD

**Issue by nivs1978** [notepad-plus-plus/notepad-plus-plus#4679]
### Description of the Issue
When I press CTRL+F4 the currently open tab does not close.

### Steps to Reproduce the Issue
Open a few files and press CTRL+F4 to close the active tab/file.

### Expected Behavior
The currently active tab should close.

### Actual Behavior
Nothing happens

### Debug Information
Almost all Windows applications support the CTRL+F4 to close the current document/tab. Web browsers, Microsoft Word/Excel, OpenOffice, Adobe Reader etc. all support this shortcut that is just as generic as CTRL+C and CTRL+V in WIndows applications. Notepad++ should support this also.
It is on the official Windows Shortcut list: https://support.microsoft.com/en-us/help/12445/windows-keyboard-shortcuts

**Comment by sasumner** [comment]
Dude, change it in the shortcut mapper...to Ctrl+F4...or whatever you like.

**Comment by jrheisey** [comment]
As this is a Windows application I request that the default behavior default to the Windows standard of CTRL-F4 to close a tabbed view. Note that CTRL-F4 has been the Windows standard since Tabbed Views were implemented in Windows about 20 years ago.

**Comment by sasumner** [comment]
@jrheisey Sure, but if it isn't acted upon, don't let it ruin your life if you want it -- remap it via the Shortcut Mapper...I did.  :)

**Comment by MetaChuh** [comment]
@nivs1978 

please use ctrl+w to close the current tab.

thank you for your help and best regards.

**Comment by IanKemp** [comment]
You can get this working using the NppExec plugin:

1. Go to Plugins -> NppExec -> Execute...
2. Paste the following snippet into the textbox:

```
NPP_SENDMSG WM_COMMAND IDM_FILE_CLOSE
```

3. Click `Save...` and name the script something like "Close current file".
4. Go to Plugins -> NppExec -> Advanced Options...
5. Under `Menu item` in the bottom-left, type something like "Close current file" into the `Item name` textbox.
6. From the `Associated script` dropdown, select the "Close current file" script, then click `Add/Modify`.
7. Click OK and the dialog will prompt you to restart Notepad++, do so.
8. Once NPP has restarted, go to Settings -> Shortcut Mapper... and select the `Plugin commands` tab.
9. Scroll down to the bottom and the new `Close current file` command should be there. Select its row and double-click, or click `Modify` to bring up the key binding dialog. Select CTRL and F4 as your shortcut, click OK.

Voila!

**Comment by sasumner** [comment]
@IanKemp Overcomplicated and unnecessary.  See my earlier comments about Shortcut Mapper.

**Comment by IanKemp** [comment]
@sasumner Updated comment to clarify.

**Comment by sasumner** [comment]
I personally like ctrl+F4 for closing.  ctrl+w is too useful to me as either "select current **w**ord" or "**w**rap toggle" to be "wasted" on something like close. :)
