### ISSUE TITLE
Document List Panel settings bug

### ISSUE THREAD

**Issue by LordRibblesdale** [notepad-plus-plus/notepad-plus-plus#4682]
### Description of the Issue
On Notepad++ 32bit version (tested on 7.5.6 and 7.5.7), the program crashes while setting up Document List Panel

### Steps to Reproduce the Issue
1. Open Setting -> Preferences
2. Check Show in Document List Panel
3. Check and uncheck Disable extension column

### Expected Behavior
Extension bar on the left should disappear, as do on 64bit version

### Actual Behavior
The program crashes

### Debug Information
Notepad++ v7.5.7   (32-bit)
Build time : Jun 29 2018 - 00:46:55
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10 (64-bit)
Plugins : DSpellCheck.dll mimeTools.dll NppConverter.dll NppExport.dll

**Comment by Yaron10** [comment]
@LordRibblesdale,

This is very interesting.
Did you build the binary yourself or you're using the official/original notepad++.exe?

See: https://notepad-plus-plus.org/community/topic/15438/multiple-errors-building-npp-7-5-6/11

**Comment by LordRibblesdale** [comment]
Using official notepad++ from official installer from website!

**Comment by Yaron10** [comment]
Thanks.

The crash does not occur on every machine or in any constellation.
But the issue should certainly be investigated.

**Comment by AngryGamer** [comment]
I can't replicate this issue. Try out a [fresh portable copy](https://notepad-plus-plus.org/repository/7.x/7.5.7/npp.7.5.7.bin.x64.zip) extracted to a random directory so it's using stock settings, does the crash still happen?

**Comment by LordRibblesdale** [comment]
On my system, also portable build still crashes

**Comment by AngryGamer** [comment]
Can have I see debug info on the portable copy to ensure "Local Conf mode : ON"?

**Comment by LordRibblesdale** [comment]
Notepad++ v7.5.7   (32-bit)
Build time : Jun 29 2018 - 00:46:55
Path : C:\Users\Green\Downloads\npp.7.5.7.bin\notepad++.exe
Admin mode : OFF
Local Conf mode : ON
OS : Windows 10 (64-bit)
Plugins : DSpellCheck.dll mimeTools.dll NppConverter.dll NppExport.dll 

Windows 10 Version 1607 14393.2363

**Comment by AngryGamer** [comment]
Based on the Version, I'm guessing Win10 Enterprise or Education? I wonder if anyone else has a working copy they could use to check whether the crashes also happen on their Win10 Enterprise/Education. Otherwise I'll probably grab an evaluation copy of Win10 Enterprise to check myself.

**Comment by LordRibblesdale** [comment]
Enterprise. I think that my build could have some corrupted libraries. This would explain some strange behaviours that my system is having. Btw I'll try on other systems and see what happens

**Comment by SinghRajenM** [comment]
I am able to reproduce this easily with the given steps above. And I feel, I have fixed the issue. Please validate once in the reported systems [nighty build](https://ci.appveyor.com/api/buildjobs/uah3v6gb41dafj1j/artifacts/Notepad%2B%2B.Win32.Unicode%20Release.exe).

**Comment by Yaron10** [comment]
Building NPP 7.5.6 with https://github.com/notepad-plus-plus/notepad-plus-plus/pull/4684, the crash does not occur.

**Comment by LordRibblesdale** [comment]
I can confirm that the crash does not occur with nightly build shared by SinghRajenM
