### ISSUE TITLE
cannot remove wakatime plug-in.

### ISSUE THREAD

**Issue by vonp** [notepad-plus-plus/notepad-plus-plus#4689]
### Description of the Issue
plug-in mgr appears to begin removal and then stalls at deleting the dll.

### Steps to Reproduce the Issue
1.  install
2.  remove

### Expected Behavior
removal

### Actual Behavior
mgr failed: still there upon re-start

### Debug Information
N/A

**Comment by sasumner** [comment]
Neither plugin-manager nor wakatime is part of Notepad++.  This issues list is for Notepad++ issues only.  Please find a different/better place to report this problem.  Please close this issue.

**Comment by vonp** [comment]
it seems as though you are saying that NP++ provides the hooks to incorporate plug-ins and nether vets them for acceptability nor provides a means to report plug-ins that are not working.

maintaining the integrity of NP++ militates against the existence of such policies. moreover, my long-time knowledge re how sincerely the developer views his responsibility for the complete product has never revealed that the attitude inherent in such policies has actually ever come into play.
