### ISSUE TITLE
how about add Rust language lexer?

### ISSUE THREAD

**Issue by slitazcn** [notepad-plus-plus/notepad-plus-plus#469]
so many issue,i don't know someone else have commit this ,if  yes,please close this

**Comment by Croydon** [comment]
Nobody has yet, at least the search doesn't give any matches :)
Rust support would be indeed great.

**Comment by Croydon** [comment]
Maybe we can reuse @pfalabella's work: https://github.com/pfalabella/Rust-notepadplusplus (I'm not sure how complete this is).

**Comment by dail8859** [comment]
There is actually a [Rust lexer](https://github.com/notepad-plus-plus/notepad-plus-plus/blob/master/scintilla/lexers/LexRust.cxx) already provided by Scintilla, it's just not wired up for Notepad++ to use it yet.

**Comment by Croydon** [comment]
Could get closed because of #1258
