### ISSUE TITLE
Tidle

### ISSUE THREAD

**Issue by RKXETTER** [notepad-plus-plus/notepad-plus-plus#4692]
### Description of the Issue

When I'm pressing tilde it's not showing up and when I'm pressing delete it replaces last letter.

### Steps to Reproduce the Issue

1. 
2. 
3.

**Comment by walkeb7** [comment]
In version 7.5.7, I am able to add a tilde character in a new file.
What version are you using? What is the selected 'Language' setting? Is there more information about your settings or the steps to replicate that you could provide?
