### ISSUE TITLE
Any plan for plist file support?

### ISSUE THREAD

**Issue by shahdhiren** [notepad-plus-plus/notepad-plus-plus#4693]
### Description of the Issue
Is there any plan to support Apple Plist file support which is available after compilation? Currently, if we open the compiled plist file in windows in Notepad ++ (v. 7.5.3), some of the characters are junk characters in dark black.

### Steps to Reproduce the Issue

1. Take any compiled plist file from Apple/MacOS and try to open

### Expected Behavior
It should display the xml structure of plist same as in MacOS environment

### Actual Behavior
It displays the junk characters in between texts.

### Debug Information
Notepad++ v7.5.3   (32-bit)
Build time : Dec  5 2017 - 10:45:46
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10 (64-bit)
Plugins : DSpellCheck.dll mimeTools.dll NppConverter.dll NppExport.dll NppFTP.dll PluginManager.dll

**Comment by MetaChuh** [comment]
@shahdhiren 

there is a difference between an xml plist and a binary plist (bplist).

xcode does a header parsing to decide which file format a .plist file has.
to use binary plist files in notepad++, you also need a parser, which can differentiate, if a .plist file is in plain text or in binary format.

please use the NppBplistPlugin, which is available from the `plugins > plugins admin` menu of notepad++ 7.6.6.

thank you for your help and best regards.

-----
```
general notes:

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
(no extra account is needed, just use your github account to sign in)
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)
