### ISSUE TITLE
Handling of Huge files (not loading all file to memory)

### ISSUE THREAD

**Issue by jpmartins** [notepad-plus-plus/notepad-plus-plus#4694]
### Description of the Issue
Unable to open handle/edit a huge file (>1GB for example).

### Steps to Reproduce the Issue
1. create of find a file bigger then 1GB
2.  Open With Notepad++

### Expected Behavior
Opening the file for edition normaly (or with a warning for large file, will replicate disk space usage of the file, for example). Sugestion on implementation stratagy only open parte of the file (maybe the first 50MB) and the keeping in memory a sliding window over a shadow copy of the file being edited.

### Actual Behavior
Erro messange: "File is too big to be opened by Notepad++"

### Debug Information
Notepad++ v6.6.8

![cannotopenfile](https://user-images.githubusercontent.com/378596/43081323-4adb387a-8e81-11e8-83d7-4310501d2fa6.png)

**Comment by sasumner** [comment]
Why don't you try a 64-bit version and something newer than 6.6.8 ? It still won't be able to open HUGE files but probably will do better with LARGE files.  :)

Also, seems like you have some ideas about implementation....maybe take the source code and modify it and create a pull request implementing a HUGE file capability?

**Comment by jpmartins** [comment]
Thanks for the suggestion. Limited in a work environment on witch versions to use. But the issue is not to fix my pain, i will have to work around, but to contribute to ease someone else pain in the future. My cpp is very rusty... would need lots of time i do not currently have.

**Comment by donho** [comment]
Outdated.
The current version (x64) can support file > 2 GB.
