### ISSUE TITLE
Feature request: Customizable user path

### ISSUE THREAD

**Issue by ildar-shaimordanov** [notepad-plus-plus/notepad-plus-plus#4696]
To this moment N++ supports two locations for loading/storing its configuration:
* the folder where N++ is placed in the system and
* a user home path

I suggest to implement a new feature that allows to customize the configuration location via command line. It could be similar to the `--user-dir` or `--user-data-dir` options or something else similar them supported by other applications allowing to store their configuration in another user-defined folder. 

Pros:
* better portability (besides PortableApps that is not convenient)
* easy way to migrate to a new version for those who like to update applications manually

**Comment by sasumner** [comment]
Another option is cloud:

![image](https://user-images.githubusercontent.com/30118311/43136046-7846838e-8f15-11e8-9a04-eef29a259417.png)

**Comment by ildar-shaimordanov** [comment]
@sasumner 
It is not the thing I requested. I meant possibility to specify the path to all configuration files (config.xml, styles, sessions and any kind of user defined settings).

**Comment by fixpointfloater** [comment]
I'am really missing this freature.
Specifying the config path by command line would allow e.g. custom menues/user commands, skins etc. depending on the project/make/debug environment.

**Comment by pryrt** [comment]
related to #5317 "Not all XML config files saved to local path (Cloud setting)"

**Comment by donho** [comment]
https://github.com/notepad-plus-plus/notepad-plus-plus/commit/7874f8dab3509e1df0470ab6bf083c9ccecf5650

**Comment by donho** [comment]
(Mini-specs)

Currently the settings could be:
1. Beside of Notepad++ installation if **doLocalConf.xml is present**
2. In `%APPDATA%\Notepad++` if **doLocalConf.xml is absent**
3. In path define in **\cloud\choice** in Notepad++ installation or in `%APPDATA%\Notepad++`, it depends on if doLocalConf.xml exist.

To add:
4. command line argument `-settingsDir"E:\myNppSettings"` : All the above configurations will be ignored, Notepad++ will load (and write) `config.xml` and the other configuration xml files from (into) "E:\myNppSettings\".

Any complement information is welcome.

**Comment by ArkadiuszMichalski** [comment]
But what if in `E:\myNppSettings` some files are missing? Shouldn't check the above as fallback (for read)? I'm also favor for my own setting folder, because now I have to be careful not to overwrite my changed files located directly in the NPP folder (portable).

**Comment by donho** [comment]
@ArkadiuszMichalski 
> But what if in E:\myNppSettings some files are missing? Shouldn't check the above as fallback (for read)? 

If you are giving `-settingsDir"E:\myNppSettings"` command line argument, then I suppose you know what you're doing. So there'll be no check. But after all, there's no harm about it. Notepad++ doesn't check `config.xml` since it uses the default values and will write this file before it quits. It will ask and copy `langs.xml` & `stylers.xml`, the remain xml files will be generated before quitting as well.

**Comment by ArkadiuszMichalski** [comment]
I'm more interested in folders, like `userDefineLangs,functionList,autoCompletion,themes`.  Will they always be localized/loaded from the main NPP folder or they can be overridden by our folders from our settings folder?

**Comment by ildar-shaimordanov** [comment]
@donho 
Regarding the option 4. It's the approach very close to the initial request. Let's say, the application is run as (manually or via a shortcut): `npp --settingsDir="some\path\targetDir"`. So:

- if the path exists and all necessary files exist, all the settings will be used
- if the path exists but some files are missing, default values will be used, and absent files will be created with default values
- if the path doesn't exist, it will be created and all necessary files will be created

If during one of the above steps the application fails, show a dialog box with error and make attempt to create setting storage accordingly the running mode (in the same directory next to the executable or in `%APPDATA%\Notepad++`).

**Comment by donho** [comment]
@ArkadiuszMichalski 
> I'm more interested in folders, like userDefineLangs,functionList,autoCompletion,themes. Will they always be localized/loaded from the main NPP folder or they can be overridden by our folders from our settings folder?

"Settings on Cloud" is for overriding `%APPDATA%\Notepad++\`.  So this policy won't be change in implementation of this feature "Customizable user path".

OTOH, I just made function list xml file overridable in `%APPDATA%\Notepad++\functionList\` (already in master), so please check if it's overridable for the other xml files. You can always create the issue if it's not case and I will do it.

**Comment by donho** [comment]
@ildar-shaimordanov 
> if the path exists and all necessary files exist, all the settings will be used
if the path exists but some files are missing, default values will be used, and absent files will be created with default values
if the path doesn't exist, it will be created and all necessary files will be created

This is a little bit too much. I will try but I promise nothing.

**Comment by ildar-shaimordanov** [comment]
I am not familiar with c  . So my finding would be absolutely wrong. Is it correct way to set the CLI parameter (let say `--user-data-dir`) and further check it as follows:

PowerEditor/src/Parameters.h

```cpp
struct CmdLineParams
{
...
	generic_string _user_data_dir;
...
```

PowerEditor/src/Parameters.cpp

```cpp
generic_string NppParameters::getSettingsFolder()
{
	if (_user_data_dir != '')
		return _user_data_dir;
...
```

**Comment by ArkadiuszMichalski** [comment]
@donho 
Can this argument express something like `profile`, as we have in browsers? I meant that if we use it then settings will be save/read here, but also other folder will be loaded from here (if exists), like themes/userDefineLangs/autoCompletion etc. In general, I mean that NPP first tries to load these files from `-settingsDir` arg (or any other name, like `-profile`), and if they do not exist, look for them elsewhere (like now, in Cloud, %APPDATA%\Notepad++ or Notepad++ installation dir).

Currently there is no convenient way to change individual themes, autocompletion, and possibly a few others as well. Having a profile folder, I can simply choose not to pass it as argument or rename it and then I will use the default files. Thanks to this, when updating, I could just unpack the entire NPP content and not worry about something being overwritten.

**Comment by donho** [comment]
@ArkadiuszMichalski 
> Can this argument express something like profile, as we have in browsers?

Yes, for the most of (maybe all?) xml files. No for all executable files (all plugins) for the sake of security.

> Currently there is no convenient way to change individual themes, autocompletion, and possibly a few others as well. Having a profile folder, I can simply choose not to pass it as argument or rename it and then I will use the default files. 

As I answered before:
> OTOH, I just made function list xml file overridable in %APPDATA%\Notepad++\functionList\ (already in master), so please check if it's overridable for the other xml files. You can always create the issue if it's not case and I will do it.

You're welcome to create issues about that, I'll consider for sure.

**Comment by ArkadiuszMichalski** [comment]
@donho 
Sure, I thought about plugins, but that can be too cumbersome, but possibly loading the rest of the XML files would be great. I will open a separate bug.

**Comment by alexhass** [comment]
Why exists a new command line argument without beeing able to set the same via GPO / registry?

**Comment by donho** [comment]
@alexhass 

`-settingsDir=c:\yourpath` doesn't work GPO? How come?

**Comment by alexhass** [comment]
This is not a registry key. I need a setting in registry where the path can be set.

This is a command line argument only (bad).

**Comment by donho** [comment]
I see. 
> In path define in \cloud\choice in Notepad++ installation or in %APPDATA%\Notepad++, it depends on if doLocalConf.xml exist.

The cloud settings point to local path. So you can use "cloud settings" to deploy the settings path you want.

**Comment by alexhass** [comment]
I cannot deploy settings to an xml file via GPO. Microsoft GPOs do not have thos feature. A registry key will work great.
