### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by lazair** [notepad-plus-plus/notepad-plus-plus#4701]
Folding a block of commented lines in any target language would help save time while analyzing foreign code.

### Description of the Issue
Fold commented text block

### Steps to Reproduce the Issue
1. Select block of text
2. Press Ctrl+Q to comment it (use Asssembly as Language)

### Expected Behavior
A shortcut to fold entire commented block (or all previously commented blocks)

### Actual Behavior
None

### Debug Information
Notepad++ v7.5.7   (32-bit)
Build time : Jun 29 2018 - 00:46:55
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10 (64-bit)
Plugins : IndentByFold.dll iTimeTrack.dll NavigateTo.dll nppcrypt.dll NppXmlTreeviewPlugin.dll PluginManager.dll PythonScript.dll XMLTools.dll DSpellCheck.dll mimeTools.dll NppConverter.dll NppExport.dll

**Comment by sasumner** [comment]
I'd think you'd *want* the comments when doing this...

**Comment by lazair** [comment]
I found handy to comment block of code that is not part of implemented algorithm, but handles possible errors. So you could clearly see the normal code execution path and not worrying about errors handling. It is useful for analyzing asm code, where you can simply ignore error handling parts of code by commenting them and hiding (folding out). Later, when you need to dig deeper you could just press Ctrl+Q and further analyze new portion of code. That is idea!

**Comment by lazair** [comment]
By the way, you can see desired functionality in Visual Studio. Comment some consecutive lines of code and folding indicator will appear at left.

**Comment by lazair** [comment]
Found a good alternative for proposed feature: "Hide lines".
Close the thread.

**Comment by sasumner** [comment]
Yea...except the Hide Lines feature is not really usable in its current form (my opinion only).
