### ISSUE TITLE
Cannot Run An .html Documnet In FireFox When FireFox Is Installed

### ISSUE THREAD

**Issue by ghost** [notepad-plus-plus/notepad-plus-plus#4710]
### Description of the Issue
When trying to run a .html document in firefox, it will give an error saying that the "firefox" cannot be found

### Steps to Reproduce the Issue

1. Open HTML Document
2. Go to run
3. Click on "Launch In FireFox"

### Expected Behavior
The HTML Document will open in FireFox

### Actual Behavior
An error will popped up saying that the command "firefox" cannot be found

### Debug Information

Notepad++ v7.5.8   (64-bit)
Build time : Jul 23 2018 - 02:06:36
Path : E:\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : ON
OS : Windows 10 (64-bit)
Plugins : DSpellCheck.dll mimeTools.dll NppConverter.dll 

![error](https://user-images.githubusercontent.com/37266538/43368502-2f8da030-935e-11e8-998a-6975f07ae352.PNG)

**Comment by SinghRajenM** [comment]
Is firefox installed in the system?

I get the same error when I try to launch in Chrome as I don't have Chrome installed in my system.

![image](https://user-images.githubusercontent.com/14791461/43368662-62c7b5d8-937e-11e8-92e1-a3ea281124fd.png)

**Comment by MisterTeeXD** [comment]
Yes i have FireFox installed

**Comment by Big--Mike** [comment]
Is Firefox in your path? What Notepad++ does is simply executing **firefox file.html**.
Either add your firefox installation folder to the path or modify **%AppData%\Notepad++\shortcuts.xml** and replace "firefox &quot;$(FULL_CURRENT_PATH)&quot;" with "<Path to your Firefox>\firefox.exe &quot;$(FULL_CURRENT_PATH)&quot;"

**Comment by sasumner** [comment]
These "Run" menu items of this sort are really just examples.  Edit at will to make them work for YOUR system.
