### ISSUE TITLE
Syntax highlighting not working when dragging between Instances

### ISSUE THREAD

**Issue by acenturyandabit** [notepad-plus-plus/notepad-plus-plus#4711]
### Description of the Issue

Syntax highlighting is not enabled when dragging tabs between different instances

### Steps to Reproduce the Issue

1. Open 2 .py files in Instance1 + some random filler files to keep first instance open
2. (for me) right click tab -> Move tab to new instance for one of the .py files
3. Drag the 2nd .py file to the new instance
### Expected Behavior

2nd py file should still be nice and syntax-highlighted.
### Actual Behavior

2nd py file does not have syntax highlighting
### Debug Information

Notepad++ v7.5.8   (32-bit)
Build time : Jul 23 2018 - 02:03:53
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10 (64-bit)
Plugins : Explorer.dll IndentByFold.dll LightExplorer.dll nppRegEx.dll PluginManager.dll XMLTools.dll DSpellCheck.dll mimeTools.dll NppConverter.dll NppExport.dll

**Comment by chcg** [comment]
@acenturyandabit Closed this one in favour of #4769 as some more information is available already there. Copied the information from here.
