### ISSUE TITLE
Notepad++ 7.5.8: Function list is broken with PHP file (string is confused with comment)

### ISSUE THREAD

**Issue by AleWin32** [notepad-plus-plus/notepad-plus-plus#4712]
```PHP
<?php

class MyClass
{
	public function myFunc1()
	{
		myFunc2 ('/*.js'); // The slash followed by an asterisk in the string makes Notepad++ not showing function list
	}

	public function myFunc2 ($name)
	{
		return $name;
	}

	/* This block comment with the string in myFunc1 makes Notepad++ not showing Function list */
}
?>
```

Function list is not shown with this piece of PHP code in the last version of Notepad++.

The problem is with the string in myFunc1, it makes Notepad++ believe we are starting a block comment (because it starts by /*) but actually it is a simple string.

**Comment by AleWin32** [comment]
One note, this bug does not happen with Java files:

```Java
public class MyClass
{
	public static void myFunc1()
	{
		myFunc2 ('/*.js'); // The slash followed by an asterisk in the string makes Notepad++ not showing function list
	}

	public static myFunc2 (String name)
	{
		return name;
	}

	/* This block comment with the string in myFunc1 makes Notepad++ not showing Function list */
}
```

**Comment by campZero** [comment]
While this is a bit of a necro, the issue persists in 7.8.7:

This breaks the function list:
`$files = glob("./languages/*.xml");`

This works (due to no /* being present:
`$files = glob("./languages/"."*.xml");`

I tried different qutation marks, but to no avail.

**Comment by MAPJe71** [comment]
No problem for me with [this parser](https://github.com/MAPJe71/Languages/blob/master/PHP%20-%20Personal%20Home%20Page%2C%20PHP%20Hypertext%20Preprocessor/Config/functionList-PHP.xml).

**Comment by Entretoize** [comment]
> No problem for me with [this parser](https://github.com/MAPJe71/Languages/blob/master/PHP%20-%20Personal%20Home%20Page%2C%20PHP%20Hypertext%20Preprocessor/Config/functionList-PHP.xml).

How to use that parser ?
