### ISSUE TITLE
Selection of "working" tab is lost after restart so the first tab is always selected (by default?)

### ISSUE THREAD

**Issue by cristian-sulea** [notepad-plus-plus/notepad-plus-plus#4716]
### Description of the Issue

When reopening Notepad++ (with session snapshot enabled) the selected file (tab) at closing time is not reselected. It seems that in the session snapshot is not included anymore the "working" tab, so at reopening time the first tab is selected by default.
This was working in 7.4.x versions (i have 7.4.2 and is working) but in 7.5.x is not working any more.

### Steps to Reproduce the Issue
1. Open Notepad++
2. Open some files (so we have some tabs)
3. Select last opened file (tab) (but the bug can be reproduced with any tab)
4. Close Notepad++ (Preferences/Backup/Session snapshot -> is enabled)
5. Reopen Notepad++

### Expected Behavior
The tab selected at step 3 should be selected after reopening. 

### Actual Behavior
The first tab is always selected after reopening.

### Debug Information
Notepad++ v7.5.8   (64-bit)
Build time : Jul 23 2018 - 02:06:36
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10 (64-bit)
Plugins : DSpellCheck.dll mimeTools.dll NppConverter.dll

**Comment by cristian-sulea** [comment]
today i updated to latest version and bug is still there ... uninstall

**Comment by sasumner** [comment]
>today i updated to latest version and bug is still there 

@cristian-sulea Dude, seriously? A fix was committed 8 days ago but a release containing that commit hasn't happened yet.  WTF.

**Comment by cristian-sulea** [comment]
SinghRajenM committed on Jul 31 -> the bug was fixed on JUL 31

**Comment by SinghRajenM** [comment]
@cristian-sulea wait till next release happens. If you can't wait, then get the nightly build binary and replace it to the notepad installation directory.

https://ci.appveyor.com/api/buildjobs/5u4vljudt309nx33/artifacts/Notepad%2B%2B.X64.Unicode%20Release.exe
