### ISSUE TITLE
Notepad installed via Win 10 store does not offer open with

### ISSUE THREAD

**Issue by JohanLarsson** [notepad-plus-plus/notepad-plus-plus#4717]
### Description of the Issue
Here is trying to open a .csproj file
![image](https://user-images.githubusercontent.com/1640096/43443893-8d930afe-94a2-11e8-9547-3b179c139ede.png)

Notepad++ is not listed under 'Chose another app'

### Expected Behavior
Would be nice to have notepad++ offered as an open with alternative for { .csproj .sln .xaml .config .ruleset } files by default.
Notepad++ should be listed under 'Chose another app'

**Comment by sasumner** [comment]
This is NOT the "Notepad++ installed via the store"!
UGH, see people, why the store fork should have been given a vastly different name!?
Please close this issue.
