### ISSUE TITLE
Notepad installed via Win 10 store does not have plugin manager

### ISSUE THREAD

**Issue by JohanLarsson** [notepad-plus-plus/notepad-plus-plus#4718]
### Description of the Issue
I can't find Plugin Manager in Notepad++ installed via the store.

### Expected Behavior
Would be nice if plugin manager was installed by default if possible.

**Comment by sasumner** [comment]
This is NOT the "Notepad++ installed via the store"!
UGH, see people, why the store fork should have been given a vastly different name!?
Please close this issue.

**Comment by JohanLarsson** [comment]
Where is the home of the store guy?
