### ISSUE TITLE
Horizontal scroll from mouse not working

### ISSUE THREAD

**Issue by akprof2000** [notepad-plus-plus/notepad-plus-plus#4720]
### Description of the Issue

Horizontal scrolling does not work if you scroll using the left mouse wheel 

### Steps to Reproduce the Issue

1. Put cursor on large length string
2. Rotate the left mouse wheel
3. A different horizontal scroll bar will appear and scroll not work

### Expected Behavior

The screen will scroll horizontally

### Actual Behavior

Displays a different horizontal scrolling from the standard and the screen remains in place

### Debug Information

Notepad++ v7.5.7   (32-bit)
Build time : Jun 29 2018 - 00:46:55
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10 (64-bit)
Plugins : HTMLTag_unicode.dll JsMapParser.NppPlugin.dll JSMinNPP.dll PluginManager.dll XMLTools.dll DSpellCheck.dll mimeTools.dll NppConverter.dll NppExport.dll 

My mouse is Logitech MX Master and I am use Logitech set point

![not correct](https://user-images.githubusercontent.com/35367334/43460137-6fc4b03c-94d8-11e8-88f4-c7cce134b12c.PNG)
Not correct scrollbar

![correct](https://user-images.githubusercontent.com/35367334/43460138-7152dd5c-94d8-11e8-9171-33b4f3838e8c.PNG)
Correct scrollbar

**Comment by Nighthawk117w** [comment]
Same issue with Logitech MX Anywhere 2

**Comment by gadaszewski** [comment]
Recorded that action:
[https://gfycat.com/firmdangeroushoneyeater](url)

**Comment by Ekopalypse** [comment]
Looks like this is an issue in windows 10 only, as I don't see a different scrollbar in windows 7.
Or it may be related to not having a left mouse wheel instead I was using my single mouse wheel and pressed the shift button while scrolling.

**Comment by MetaChuh** [comment]
i can not reproduce a misbehaviour of the horizontal scroll bar on mouse wheel, as seen at the screenshot below.

please check your mouse driver settings for custom scroll behaviour and adapt it accordingly.
alternative to the second wheel, if you can not set the required wheel parameters at your mouse driver, you can use the top wheel while holding <kbd>shift</kbd>.

![scroll hor ver](https://user-images.githubusercontent.com/45773305/56357382-e50bd200-61db-11e9-9b8e-d38e74e47673.gif)

<kbd>Notepad++ v7.6.6   (32-bit)
Build time : Apr  3 2019 - 23:49:50
Path : C:\Users\User\Desktop\npp.7.6.6.bin\notepad++.exe
Admin mode : OFF
Local Conf mode : ON
OS : Windows 10 (64-bit)
Plugins : mimeTools.dll NppConverter.dll NppExport.dll</kbd>

thank you for your help and best regards.

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
(no extra account is needed, just use your github account to sign in)
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)

**Comment by lipchev** [comment]
I am experiencing the same issue with MX Master 3 & Logitech Options- it seems as if the "current/local" value of the scroll-bar (the actual one, not a different one) is set, but without it triggering the binding. I conclude this from the fact that the moment I either hover over the scroll bar, or change the actual position-value (either by moving the cursor, or shift-scrolling)- the scrollbar immediately snaps back to the correct position.
Other then Notepad++ the horizontal scrolling seems to work for most apps- the exception being (so far as I've found)- XAML Designer & my own WPF Apps(?!) - in both cases it just doesn't work.
Unfortunately Logitech Options doesn't allow for mapping Shift + Vertical Scroll- but as a workaround I currently have it configured (for Notepad++) to toggle the "ctrl+left/right" combination- which of course is not the same- but still pretty useful (like holding "shift" and scrolling becomes the equivalent to "ctrl+shift+left/right" which requires both hands on the keyboard).

Notepad++ v7.8.4   (64-bit)
Build time : Jan 29 2020 - 01:31:03
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS Name : Windows 10 Pro (64-bit) 
OS Version : 1809
OS Build : 17763.973
Plugins : ComparePlugin.dll DSpellCheck.dll mimeTools.dll NppConverter.dll NppExport.dll 

Logitech Options 8.10.84
PS Will try it out on a PC without it later this week.

**Comment by lipchev** [comment]
Ooop, sorry - had #2096 opened in the next tab over :)

**Comment by Jmuniak** [comment]
MX 3 HORIZONTAL SCROLL / THUMB WHEEL non responsive while Options software is installed. VS Code and Obsidian are the two main applications I use in my day to day work and horizontal scroll is not functional in those with the software installed. Without Options installed the thumb wheel does scroll horizontally. Can't use Flow without the software and can't scroll with the software. what a joke.

**Comment by terrellgf** [comment]
Same issue with Logitech MX Master 3

**Comment by worldsdream** [comment]
Same issue over here with mx master 3. Can’t use the mouse scrollbar for horizontal scrolling.

**Comment by ozwaldDunlop** [comment]
Same issue with Logitech MX Master 3 (and previous MX Master 1)

**Comment by hfellner** [comment]
@ozwaldDunlop  I tried your suggestion - then Notepad++ actually zooms in/out, still no horizontal scroll. I absolutely see Notepad++ as the guilty party here, as horizonal scroll works just fine with any other application I use, just not with Notepad++.

**Comment by ozwaldDunlop** [comment]
@hfellner apologies. I've retried, and it no longer works (and wondering if it was a dream when I got it working 😉)

**Comment by JenTonUg** [comment]
I'm running the Logi+ Beta and my horizontal scroll seems to be working in Notepad++, set to "Horizontal scroll". Now if only I could set the scroll wheel speed higher than 100%. :-)

**Comment by chrajeshdagur** [comment]
facing smooth scrolling issue in windows, when I scroll, it scrolls all the way down and skips lines.
it is supposed to work like when I use a mouse to stick on the scrolling bar, to scroll the lines smoothly.

please find the attached GIF file to understand it, I'm using windows 10.

GIF Screenshot:
![rr](https://user-images.githubusercontent.com/18675963/174451193-48560b7f-f376-4cb0-8ed5-16f0703bae18.gif)

Please suggest a fix for it.
