### ISSUE TITLE
Crash when highlighting opening tag in a big file

### ISSUE THREAD

**Issue by okainov** [notepad-plus-plus/notepad-plus-plus#4721]
### Description of the Issue
NPP hangs while trying to type a symbol

### Steps to Reproduce the Issue
1. Open attached .gpx file in NPP
[bug_track.zip](https://github.com/notepad-plus-plus/notepad-plus-plus/files/2246601/bug_track.zip)
Some background here: it's one `<trk>` with several `<trkseg>` sections. What I wanted is to wrap each trkseg with its own trk.
2. Search for `</trkseg>` (it will be somewhere in the middle of the file)
2.1. As an alternative, initially I tried to fold first trkseg and go to this place instantly w/o search.
3. Insert `<trk><name>10.10.2017</name>` before beginning of the next trkseg
4. Ctrl+С - Ctrl+V `<trk>`
5. Insert it near existing `<trk>` you've just inserted (so new content should look like `<trk><trk><name>10.10.2017</name>`
6. Put cursor after the first angle bracket
7. Try to type "/" symbol.
8. NPP hangs.

It feels like NPP tries to search for the opening tag to perform proper open-closed tag highlighting, but it either takes some huge time (this is just an extract from the file, initially I observed this with 40mb track, but even with this 4mb it's still there) or just hangs. I waited for ~5 minutes and nothing...

Probably it also relates in general to something like "improve big files support". Currently NPP is almost unusable for editing files more than ~5Mb and completely unusable for files more than 50Mb (sql dumps, logs).

Ref #3996, #1841, #3089, #2027

### Debug Information
Notepad++ v7.5.8   (32-bit)
Build time : Jul 23 2018 - 02:03:53
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10 (64-bit)
Plugins : DSpellCheck.dll mimeTools.dll NppConverter.dll NppExport.dll

**Comment by MetaChuh** [comment]
i can not reproduce this on notepad++ 7.6.6 x64

please update your notepad++ to the latest x64 version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins if you update from version 7.5.9 or below.
if your issue still persists, and it is still of relevance to you, please feel free to file a new issue as easy to understand and reproducible as possible.

thank you for your support and best regards.

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
(no extra account is needed, just use your github account to sign in)
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)
