### ISSUE TITLE
Return functionality of previous NP++ Versions - File Dialog no longer uses native windows method - can't search or get path

### ISSUE THREAD

**Issue by bpersonick** [notepad-plus-plus/notepad-plus-plus#4724]
### Description of the Issue
In previous versions of NP++ the file open/save dialogs used the native windows explorer functionality, allowing you a full directory tree to expand/collapse, the ability to run searches and select files from them, and the ability to copy/paste file/folder paths directly into the path bar.

Recently a change has been made and we no longer get the nice windows method invoked to browse the local file system, and instead get one of those annoying non-native type dialogs that don't allow to copy/paste the path in them, nor allow you to search.

  I understand if you might be considering replacing calls to native windows functions to support porting it to another OS down the line, or something, and you may have unified the code to the less functional method because of os this.

 However the old code obviously did/does exist, so I suggest putting in an option as to which method you want to use for NP++so that windows users can continue to use the more featureful method that NP++ originally used, and the code could detect on the fly if it is on a non-windows system, or it could default on the less functional method but have a setting we as windows users could toggle on to allow us to use the more functional method.

  If such a method does already exist, I haven't found it despite looking for such a setting, so if you know how I can get it back without installing older versions of NP++ and turning off the upgrade feature, please let me know.

**Comment by ClaudiaFrank** [comment]
Goto Settings->Preferences->Default Directory
and check **Use new style dialog ...**

**Comment by bpersonick** [comment]
Thanks Claudia, this was not at all intuitive as it sounded like it was advertising to explicitly use the behavior I was seeing where a linux/java app doesn't have the niceties we get out of windows explorer integration.

  Why not have a radio button option instead "Use Old Style Windows Explorer Integration" or "Use New Style No Windows Explorer Integration" and set the previous functionality to default?

**In any case, is there a registry setting we can apply through our domain group policy to stop our end users from hounding the helpdesk guy?**

**Comment by ClaudiaFrank** [comment]
>Why not have a radio button option instead "Use Old Style Windows Explorer Integration" or "Use New Style No Windows Explorer Integration" and set the previous functionality to default?

I would prefer such approach too.

>In any case, is there a registry setting we can apply through our domain group policy to stop our end users from hounding the helpdesk guy?

Except for those features which do need to be stored in registry, like extension assignment, npp stores
it configuration in xml files. The one you are looking for is config.xml and the section in question is

`<GUIConfig name="MISC" fileSwitcherWithoutExtColumn="yes" backSlashIsEscapeCharacterForSql="yes" **newStyleSaveDlg="no"** isFolderDroppedOpenFiles="yes" docPeekOnTab="no" docPeekOnMap="no" />`

Of course adapted to your needs.

**Comment by bpersonick** [comment]
Thanks Claudia, Strangely this issue is still open, but my other issue, which is still a problem in NP++ last I checked (a couple months ago) is closed without getting any response. While this one is effectively reoslved (thanks again!) Weird.

**Comment by MetaChuh** [comment]
@bpersonick 

many thanks, we have missed out this issue.

as you have already seen, the fixed udl issue had both fix and close responses, but github will only send you a notifying mail about the closing. sincere apologies for that.

thank you for your help and best regards.
