### ISSUE TITLE
files with utf8mb4 chars e.g. 🆔 not detected as utf8 (unless you include a BOM)

### ISSUE THREAD

**Issue by garyrowswell** [notepad-plus-plus/notepad-plus-plus#4730]
### Description of the Issue
The presence of any utf8mb4 character in a utf8 file and Notepad++ opens the file with ANSI encoding.

### Steps to Reproduce the Issue
1. Create a file in utf8 encoding (without BOM) with a utf8mb4 character e.g. 🆔
2. Save

### Expected Behavior
File should open in utf8 encoding

### Actual Behavior
File is opened as ANSi encoding

If it’s technically not possible to correctly detect as UTF8 without using a BOM, is it possible to define a default/assumed encoding?

**Comment by dinkumoil** [comment]
> ...is it possible to define a default/assumed encoding?

You can do that in the preferences dialog:

![grafik](https://user-images.githubusercontent.com/24699812/43541994-1aab4c2e-95cc-11e8-8db6-3dce98ebf417.png)

This effects **all** file types.

If you want to be more specific you can use my [AutoCodepage](https://sourceforge.net/projects/autocodepage/) plugin (available also via PluginManager) to define UTF-8 as encoding for certain file types only.

**Comment by garyrowswell** [comment]
But that encoding preference is only for new files?

It’s when the file is reopened that it reverts to ANSI if it has a utf8mb4 character in the file.

(The file is saved correctly as utf8)

**Comment by dinkumoil** [comment]
> But that encoding preference is only for new files?

No, it's not. If you set the options mentioned above and a file's encoding could be UTF-8 **or** ANSI, Notepad++ will choose UTF-8. I was able to verify this with "normal" text files without any special characters.

I guess your issue derives from the long-known problems in the automatic-encoding-detection feature of Notepad++. Maybe my plugin could be a workaround for you. I don't know any other solution and I don't think that we will see a fix for the problem in the near future nor if it is possible to fix it at all.

**Comment by CookiePLMonster** [comment]
For archival purposes, could somebody try and list all duplicates of this issue? @sasumner maybe?

**Comment by CookiePLMonster** [comment]
Uhm...

```
else // more than 16 bits are not allowed here
```

Looks like this code breaks on a 2002 assumption that utf-8 characters cannot be this long? Let's see if a quick fix for this is going to remedy all those outstanding issues.

If it does, then it'd be weird nobody fixed it over the years.

**Comment by dinkumoil** [comment]
@CookiePLMonster 

> For archival purposes, could somebody try and list all duplicates of this issue?

The number of **maybe** related issues has reached a far too high amount, I don't have time to test them. But I spent some time with searching for related issues.

I've searched for issues with the following filter `is:issue is:open encoding` and found the following ones which seem to be related to the bug (I've stopped digging deeper when the results became 2 years old or even older):

#4878, #4767,  #4428, #4246, #3705, #3441, #3405, #3172, #2153

Additionally #3759 reports the following: #940, #2843, #3188, #3222, #3588

I'm sure one will find much more by using different search terms.

**Comment by dinkumoil** [comment]
@CookiePLMonster 

Would be very good if you would grab responsibility for these annoying bugs. It seems that very often people are affected by this issue which live in countries where cyrillic characters are used. Since just from these people come some very useful contributions to the Notepad++ universe (e.g. plugins) they deserve some attention (just my 2 cents).

**Comment by CookiePLMonster** [comment]
> Would be very good if you would grab responsibility for these annoying bugs.

After both my PR's are merged, most of them should be gone! I, in fact, would go as far as closing **all** issues related to broken encoding (except the ones mentioning `§` character, since we **know** that one will still be an issue), so it forces people to re-test and submit new issues.

However, that is up to @donho to decide.
