### ISSUE TITLE
[DBGp] error "List index out of bounds (0)"

### ISSUE THREAD

**Issue by Toralf-AHK** [notepad-plus-plus/notepad-plus-plus#4733]
### Description of the Issue

When trying to debug an autohotkey script with DBGp Plugin, I get the error "List index out of bounds (0)". And DBGp is not Debugging.

### Steps to Reproduce the Issue

1. Notepad++ v7.5.8   (32-bit)
2. DBGp plugin 0.0.13.27 
3. AutoHotkey 1.1.29.01
4. AHK script
```
foo = 1
bar := foo . "test"
obj := {2:foo, 5:bar}
```

5. Run
`"C:\Path\Autohotkey.com" /Debug "$(FULL_CURRENT_PATH)"`

### Expected Behavior

Debugging is possible with DBGp

### Actual Behavior

error "List index out of bounds (0)". And DBGp is not Debugging.

### Debug Information

Notepad++ v7.5.8   (32-bit)
Build time : Jul 23 2018 - 02:03:53
Path : C:\LokaleDaten\Apps\npp.7.5.8.new\notepad++.exe
Admin mode : OFF
Local Conf mode : ON
OS : Windows 7 (64-bit)
Plugins : CodeAlignmentNpp.dll ComparePlugin.dll dbgpPlugin.dll LanguageHelp.dll NppExec.dll NppTaskList.dll NppTextFX.dll RunMe.dll XMLTools.dll DSpellCheck.dll mimeTools.dll NppConverter.dll NppExport.dll

**Comment by sasumner** [comment]
Is there anything specifically related to a problem in Notepad++ with this?  If not please CLOSE and report this issue somewhere else (suggest DBGp issues list?...if there is one...)

**Comment by Toralf-AHK** [comment]
I can not tell if this is an issue of DBGp or Notepad++.
I have posted this issue at DBGp list as well.

**Comment by Toralf-AHK** [comment]
I found the reason for my issue. I had a german AE = “Ä” in the path of the script. Without that character in the path DBGp works as expected.
