### ISSUE TITLE
Cursor too big/ small when hovering over line numbers wrong on some monitors

### ISSUE THREAD

**Issue by ekoschik** [notepad-plus-plus/notepad-plus-plus#4737]
Windows scales the cursor depending on the monitor that it is shown on, such that monitors of different DPIs don't appear to have different size cursors (though in reality this is done by making the cursor sized differently on each display).

When an app creates a custom cursor (which notepad++ is doing for the backwards arrow), it usually gets additional 'DPI cursors' created for it. This is skipped, however, if the app finds itself calling the private API user32!DisableDpiCursorScalingForProcess.

If this API is called, additional sizes aren't created, and when the cursor is shown on a monitor that is set to a DPI that is different from the on it was sized for, it will appear too large/ small.

### Steps to Reproduce the Issue

1.  Set the primary monitor to 200%, logout, back in
2. Launch notepad++, hover over line numbers (should be the right size)
3. Settings->system->display->click on primary, 'change the size of text...', set to 100%
4. Hover over line numbers again, cursor should be gigantic (2x size)

There's no good reason notepad++ should be calling the API DisableDpiCursorScalingForProcess… so stop doing so.

**Comment by MetaChuh** [comment]
i can not reproduce cursor scaling issues on notepad++ 7.6.6 on windows 10 build 1809 using 200% or any other scaling factor.

please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins if you update from version 7.5.9 or below.

if your cursor scaling is still not correct, after logout and login, please right click on your notepad++ icon and select `properties > compatibility > change high dpi settings`, activate `override high dpi scaling behavior` and set `scaling performed by:` to `system (enhanced)`, as seen at the screenshot below.

![Imgur](https://i.imgur.com/qVQ4Bg8.png)

thank you for your help and best regards.

-----
```
general notes:

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
(no extra account is needed, just use your github account to sign in)
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)
