### ISSUE TITLE
Some mathmatical characters arent always displayed

### ISSUE THREAD

**Issue by y-spreen** [notepad-plus-plus/notepad-plus-plus#474]
I have a very strange issue with my npp when I try to put a ∈ [element of], ∘ [small circle] or ⌀ [average] in a document. These characters are only displayed when I put a ○ [large circle] or ⊥ [bottom] character in the same line behind them, otherwise they are just blank squares.
These are of course only the characters I tested, there are probably a lot more.

Here is a gif of the bug in action: (¬ ω π to show that only the 3 are affected)
![gif](http://i.imgur.com/qoHwwfC.gif)
I'm just putting in or removing the character, it changes instantly

Am I the only one with these issues?

Test it yourself by putting this in your npp:

```
∈
∘
⌀

∈  ○
∘  ○
⌀  ○

∈  ⊥
∘  ⊥
⌀  ⊥
```

edit: ℕ ℤ ℚ ℝ ℂ ℍ are also part of the displayed only sometimes crew

**Comment by nO-OnE-910** [comment]
Test it yourself by putting this in your npp:

    ∈
    ∘
    ⌀
    
    ∈  ○
    ∘  ○
    ⌀  ○
    
    ∈  ⊥
    ∘  ⊥
    ⌀  ⊥

**Comment by Rikk** [comment]
Interestingly, this also happens on [notepad2 v4.2.25](http://www.flos-freeware.ch/notepad2.html), [notepad2-mod](https://github.com/XhmikosR/notepad2-mod), but not on [notepad2 v5.0.26-beta4](http://www.flos-freeware.ch/development-releases/) nor SciTE (original Scintilla editor).
Shall I deduct Np++ is a descendant of notepad2 4.2-series?

**Comment by zufuliu** [comment]
This bug not occurs when font (in *Global Style* -> *Default Style*) is set to DejaVu Sans Mono (v2.3.7, https://dejavu-fonts.github.io/).

**Comment by donho** [comment]
It's rather a font issue so change your font to adapt your need.

**Comment by y-spreen** [comment]
I beg to differ. This inconsistency with different characters seems to be rooted in the editor, not the font. @donho

**Comment by zufuliu** [comment]
@y-spreen I think it's a bug in GDI font fallback.
If you use font contains these characters (like DejaVu Sans Mono), the bug disappears.
Also no bug in Direct2D (as your tested SciTE or Notepad2 5 beta) with font not contains these characters.
Windows Notepad use GDI and Uniscribe, doesn't has this bug.
