### ISSUE TITLE
Query "Hide pointer while typing" Windows setting

### ISSUE THREAD

**Issue by vlakoff** [notepad-plus-plus/notepad-plus-plus#4741]
Please see this question on superuser.com: [What does the “Hide pointer while typing” feature actually do?](https://superuser.com/questions/928839/what-does-the-hide-pointer-while-typing-feature-actually-do)

And the [accepted answer](https://superuser.com/questions/928839/what-does-the-hide-pointer-while-typing-feature-actually-do#1179078), that gives great technical details.

So, in Windows I have *unchecked* this setting, so that the cursor is always displayed. (the cursor constantly disappearing/reappearing while typing is quite annoying...)

Apparently, Notepad++ currently ignores the setting. To test it, open a search window and note the disappearing cursor while typing in the "Find what" input.

(as a side note, Windows Notepad itself doesn't honor the setting...)

<br> Platform: Windows 7 64-bit, Notepad++ 7.4.2 32-bit

**Comment by Smartcom5** [comment]
I love, i NEED this feature so bad! :100:
> (as a side note, Windows Notepad itself doesn't honor the setting...)

No, it _doesn't_. It completely ignores the setting and hides the cursor on its own, no matter what the global Windows-setting is preset at.

**Comment by donho** [comment]
https://github.com/notepad-plus-plus/notepad-plus-plus/commit/cc1a3c826be32fec1b69de270b98210655edd3f8

**Comment by vlakoff** [comment]
Refs the Scintilla ticket on SourceForge: [#2333 [Scintilla] Mouse cursor visibility when typing starts](https://sourceforge.net/p/scintilla/bugs/2333/)
