### ISSUE TITLE
syntax highlighting: sql : literal string 

### ISSUE THREAD

**Issue by Vittaly** [notepad-plus-plus/notepad-plus-plus#4743]
Good day!

### Description of the Issue
In PLSQL file syntax highlighting has bug:
in case then string contains symbol \ before end of string ('), notepad think that it is not  the end of literal string and continue it until next symbol '.

### Steps to Reproduce the Issue
1. Set syntax to sql
2. type:
var1 := 'asdfasdf\\';
var2 := '123123123'; 

### Expected Behavior
highlight of the literal string ends after \ symbol 

### Actual Behavior
asdfasdf\';
var2 :=  - will be highlight as one string

**Comment by ClaudiaFrank** [comment]
This is because the sql lexer defines a property sql.backslash.escapes which is set to 1 per default.
In order to get your wanted behavior it needs to be set to 0.

![grafik](https://user-images.githubusercontent.com/16170444/43731476-ed746268-99ae-11e8-8885-9ca90f23a300.png)

**Comment by ClaudiaFrank** [comment]
Looks like this is already addressed by scintilla with the newest sql lexer

![grafik](https://user-images.githubusercontent.com/16170444/43732324-acd39f6e-99b1-11e8-8445-11203d6ae6c4.png)

**Comment by ClaudiaFrank** [comment]
Hello Vittaly,

>What it is mean? Problem already fixed in npp or will be fixed soon?

Neither nor, first it is an info for you that you can make it work if you set the property with
a scripting language plugin like python script/lua script etc ..., akthough I'm not sure if this is sufficient 
for you and an info to the all other fellows that an updated lexer has already addressed this issue.

If or when this is going to be fixed is beyond my power.

**Comment by Vittaly** [comment]
ClaudiaFrank Thank you! Please tell me, can I save changed properties in some config file?  Or will I be need change the property after every next time start of program?

**Comment by ClaudiaFrank** [comment]
Depends, how did you solve it for you? Did you install/use python script plugin, lua plugin, NppExec ... ?

**Comment by Vittaly** [comment]
I do not use them. Thank you! I will try to use NppExec

**Comment by dail8859** [comment]
Turn off `Settings > Preferences > MISC. > Treat backslash as escape characters for SQL`

---

![image](https://user-images.githubusercontent.com/3694843/58263196-922cb980-7d49-11e9-87a7-006d3742a606.png)
