### ISSUE TITLE
cursor not aligned correctly?

### ISSUE THREAD

**Issue by qKeyboard** [notepad-plus-plus/notepad-plus-plus#4746]
I have the current version of npp, 7.5.8.

I notice that the cursor seems to be getting positioned a little to the left of where it should be. So, if I put it at the end of a sentence with a period ending it, the cursor looks like it is to the left of the period, not to the right of it.

I changed fonts, no help. Calibri, Dajavu Sans, Times New Roman all did the same thing.

I checked another editor (BabelPad) and it is not happening there, so it's not some weird system problem. 

This is very confusing, it makes me want to arrow-over around the period, but the arrow won't move the cursor of course, since it's already at the end of the line.

**Comment by ClaudiaFrank** [comment]
Can't see this on my side.

![grafik](https://user-images.githubusercontent.com/16170444/43730809-ea8410d2-99ac-11e8-8043-b5a8d1749c4a.png)

**Comment by simonhearn** [comment]
I have the same issue and it's driving me crazy. I'm using a laptop with 3840x2160 resolution at 300% scaling. When I plug into an external monitor at 1920x1080 (100%) I don't have this issue. Seems like it's due to High-DPI scaling.

Here is a sample...

It looks like the cursor is before the the dot, right?

![npp1](https://user-images.githubusercontent.com/42153938/43736794-d768298e-99b6-11e8-8dd0-f20e459d45c3.png)

Nope. The cursor was after the dot, and after writing 'here' the cursor looks like it is in front of the e when it's actually at the end.

![npp2](https://user-images.githubusercontent.com/42153938/43736793-d751e41c-99b6-11e8-86a6-1daecc5088ff.png)

It seems to get worse the longer the line. Also lines which have been formatted heavily through language settings.

**Comment by ClaudiaFrank** [comment]
So I assume qKeyboard does also have HighDPI issue, unfortunate I don't have such a nice monitor to
confirm that it is related to HighDPI.

**Comment by qKeyboard** [comment]
No, my laptop has a 1280 x 800 screen and is quite old. What is weird is that NPP didn't do this before.In addition, I am finding that when I use special characters like accented letters, phonetic symbols and special punctuation marks, NPP acts like these are "combining modifiers", and if you arrow-through a word, sometimes the cursor pauses on symbols which are NOT combining ones, AS IF they were.It is almost as though NPP is mis-interpreting the Unicode specifications, and somehow thinks it is not supposed to advance the cursor when it really should.On August 6, 2018 at 3:39 PM ClaudiaFrank <notifications@github.com> wrote:  So I assume qKeyboard does also have HighDPI issue, unfortunate I don't have such a nice monitor to confirm that it is related to HighDPI.—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by qKeyboard** [comment]
Simon, your example is exactly what happens with me. Tell me, did you notice this happening just recently or has it been doing this for a while?

**Comment by simonhearn** [comment]
Only since getting a new laptop with high DPI screen - about four weeks ago. I mostly use NPP when plugged into a monitor and it doesn’t have this issue in that case, only when using the laptop screen.

Simon.

**Comment by qKeyboard** [comment]
Wow, I think I found it.  I have been able to get it to fail consistently. I was testing this with a document in Calibri font, and got the weird behavior. I then using Ctrl+mouse wheel to enlarge the font, and the problem went away. Everything was normal. When I used Ctrl + mouse wheel again to make the font smaller, the problem came back.

Conclusion: NPP has a bug with font sizing. Perhaps it is retaining font metrics from a prior screen resolution, and when the screen font is resized, it is failing to recalculate, and is positioning things as if the font were its "former" size rather than its "current" size.

**Comment by simonhearn** [comment]
Zooming the text didn’t resolve the issue for me. The sample I showed yesterday was while zoomed right in. 

>

**Comment by wooden-utensil** [comment]
A scaling issue I think?

**Comment by MetaChuh** [comment]
i can not reproduce this on notepad++ 7.6.6 on windows 10 build 1809 using 125% to 300% scaling factors.

please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins if you update from version 7.5.9 or below.

if your cursor position still does not match the real position, please right click on your notepad++ icon and select `properties > compatibility > change high dpi settings`, activate `override high dpi scaling behavior` and set `scaling performed by:` to `system (enhanced)`, as seen at the screenshot below.

![Imgur](https://i.imgur.com/qVQ4Bg8.png)

you can also choose `system` for a classic notepad++ look on scaled displays, which will look like this:

![Imgur](https://i.imgur.com/WqSSpUo.png)

note: it is recommended to disable smooth font for the classic scaler look, by going to `settings > preferences > editing` and unchecking `enable smooth font` in notepad++, if it is enabled as seen at the screenshot below.

![Imgur](https://i.imgur.com/vFFvIOR.png)

thank you for your help and best regards.

-----
```
general notes:

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
(no extra account is needed, just use your github account to sign in)
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)

**Comment by BrettHolton** [comment]
I am still seeing this issue in NPP 7.9.5 on a 4k monitor scaled to 300%.
The really odd bit is that the cursor will stay in the correct place as I type then 'step back' towards the beginning of the line a moment after I stop typing.
![NPPCursor](https://user-images.githubusercontent.com/4261575/115440884-18b3d500-a1c5-11eb-950e-9a9147379f69.JPG)
