### ISSUE TITLE
Why is NUL appearing in between records.

### ISSUE THREAD

**Issue by hanu412** [notepad-plus-plus/notepad-plus-plus#475]
I am writing some data into a flat file. To write the data,I am using the memory mapped file class from the .Net framework. Usually the file contains close to several thousands of records. Since we have a large number of records,we are using chunking. Recently I noticed NUL appearing at the start of each new chunk. This NUL appears to me whenever I open the flatfile/ .txt file in Notepad++. Also I noticed at the end of every chunk I see CR but not CR LF as the line terminator. 

Does anybody have any idea on what CR means here? Is it something related to the encoding standards? Btw, Notepad++ is an awesome editor. We love it.

![image](https://cloud.githubusercontent.com/assets/11040896/8634731/50aca4dc-2822-11e5-857a-85c04e2221d0.png)

**Comment by Rikk** [comment]
Could you post an example file?

**Comment by DavidBailey100** [comment]
CR stands for carriage return (ASCII decimal code 13), LF stands for line feed (ASCII decimal code 10).

Windows text lines normally end with CR LF, although most software doesn't care if the CR is missing. Unix/Linux text lines end in LF only. The NUL is a character with Ascii code 0.

Clearly this problem has nothing to do with Notepad++, it is an error in your program. I would use a hex editor, such as XV132 to explore this.
