### ISSUE TITLE
Crash on disable spell check

### ISSUE THREAD

**Issue by EzeKees** [notepad-plus-plus/notepad-plus-plus#4752]
### Description of the Issue
When you deactivate spell check, notepad ++ closes without warning

### Steps to Reproduce the Issue
1. Open a document
2. Disable spell check
3. Crash

### Actual Behavior
Crash

### Debug Information
Notepad++ v7.5.8   (64-bit)
Build time : Jul 23 2018 - 02:06:36
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10 (64-bit)
Plugins : DSpellCheck.dll mimeTools.dll NppConverter.dll 

![](https://storage.googleapis.com/gustfront_images/rep/1808/ddg.gif)

**Comment by ClaudiaFrank** [comment]
As this doesn't happen to me and maybe doesn't happen to others as well may I ask you if you can 
share the document you are using to replicate this? Or does this happen with any document, even empty ones?

**Comment by EzeKees** [comment]
it's a common XMl file, it happened to me with everyone. Now I tried it again and it did not happen again. I think it was an error other than Notepad ++

**Comment by ClaudiaFrank** [comment]
We can't say for sure but without having a reproducible way it is hard to say if npp or the plugin or something else was the culprit - did you, by any chance, update the spell checking plugin recently?
Then it might explain why it can not be reproduced anymore.

**Comment by EzeKees** [comment]
Not at all. I have not installed any add-on, it only has the ones that it brought from the factory. The error is quite rare.

**Comment by noncom** [comment]
Happening to me too. Whenever I press the menu button to disable the spellcheck in a blank or any other document, I get the Windows "Program stopped working..." message. It happens 100% of times. It did never fix itself, like EzeKees is saying.

Notepad++ v7.5.8   (32-bit)
Build time : Jul 23 2018 - 02:03:53
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10 (64-bit)
Plugins : DSpellCheck.dll mimeTools.dll NppConverter.dll NppExport.dll

**Comment by donho** [comment]
Could you update DSpellCheck to the latest version in Notepad++ then let me know if crash still happens?
https://github.com/Predelnik/DSpellCheck/releases
THX

**Comment by noncom** [comment]
@donho So I have downloaded the latest 64-bit 1.4.6 version and manually replaced the dll in the "plugins" directory of Notepad++. Now the error is gone, the plugin can be disabled and enabled without any problem. I think this can be considered a solution.

**Comment by donho** [comment]
@noncom Thank you for your confirmation.

@EzeKees Could you give it a try and provide me the result?

**Comment by EzeKees** [comment]
@donho  Fixed!
I did the same procedure as @noncom and it was fixed. Thank you very much

**Comment by ExDomino** [comment]
How to uninstall this addon? I don't want to update it, I want to disable it!

**Comment by sasumner** [comment]
@ExDomino  It's in the file DSpellCheck.dll.  If you rename it to something that doesn't have a .dll extension, that'll disable it.  (I like to zip a plugin I don't want at the moment to a .zip file and then remove the original .dll file; I can always put it back by simply unzipping)

**Comment by ExDomino** [comment]
No option inside Notepadd++ to disable a plugin?
Humm, is that a request feature? I think so...

**Comment by sasumner** [comment]
@ExDomino said

>is that a request feature? I think so...

Well, I guess you'd have to create a new issue and be explicit about the request, rather than leaving it buried in this chain where it will not be taken seriously.

Some plugins have an Enable option but it is by no means a standard or required thing.  It seems you are talking about a disable/enable at the Notepad++ level anyway, not at the plugin level.

Plugin Manager and the whole plugin subsystem is under rework currently (and has been for some time).  Probably a good time to get that feature request in, if you're inclined to.  I'm happy just to rename a DLL file (I don't consider it a big deal, although not everyone knows that that is what you can do).

**Comment by guielebo** [comment]
Great @sthag 🥇 

Tks.

**Comment by guielebo** [comment]
#4891 solve this.
