### ISSUE TITLE
update plugin manager link on wiki

### ISSUE THREAD

**Issue by perNyfelt** [notepad-plus-plus/notepad-plus-plus#4754]
### Description of the Issue

The pluginmanager entry in the Plugin central list at http://docs.notepad-plus-plus.org/index.php/Plugin_Central is outdated. It should point to 
https://github.com/bruderstein/nppPluginManager/releases

### Steps to Reproduce the Issue

1. Click ? -> Get More Plugins
2.  Navigate to the PluginManager plugin
3. Click the PLugin manager link on the left side

### Expected Behavior

Want to end up at https://github.com/bruderstein/nppPluginManager/releases

### Actual Behavior

Ended up in https://sourceforge.net/projects/npppluginmgr/

**Comment by sasumner** [comment]
The "bruderstein" plugin manager used to be "sanctioned" by N++.  Now that it isn't (scheduled to be replaced at some future date), pointing to it probably isn't going to happen.  Where exactly it SHOULD point is, I suppose, TBD.

**Comment by Ekopalypse** [comment]
as the new plugins admin is used now, shouldn't this be closed?
