### ISSUE TITLE
activeIndex in session.xml ignored

### ISSUE THREAD

**Issue by drderiv** [notepad-plus-plus/notepad-plus-plus#4755]
### Description of the Issue
In session.xml, there is \<mainView activeIndex="x"\>, where "x" is a integer \>= 0 and represents the index of the \<File...\> tag that was last active during the prior session.  In prior versions, the session would reload and the activeIndex tab would be the active tab upon startup.  Now it's always activeIndex 0 that is active upon startup, regardless of the activeIndex value.

### Steps to Reproduce the Issue
1.  Create a session with two or more files open.
2.  Select any tab other than the first as the active tab.
3.  Close NP++.
4.  Open NP++.
5.  The first tab (activeIndex 0) will be the active tab, despite the activeIndex being > 0.

### Expected Behavior
The most recent active tab should once again be active upon the next startup.

### Actual Behavior
The first tab (activeIndex 0) is always the active tab upon restart.

### Debug Information
Notepad++ v7.5.7   (64-bit)
Build time : Jun 29 2018 - 00:53:58
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10 (64-bit)
Plugins : ComparePlugin.dll NppFTP.dll PluginManager.dll DSpellCheck.dll mimeTools.dll NppConverter.dll

**Comment by SinghRajenM** [comment]
PR #4722 should fix this issue as well. Please try nightly build once to verify it -

https://ci.appveyor.com/api/buildjobs/5u4vljudt309nx33/artifacts/Notepad%2B%2B.X64.Unicode%20Release.exe
