### ISSUE TITLE
Custom Syntax Highlighting Not Working

### ISSUE THREAD

**Issue by AtmaX** [notepad-plus-plus/notepad-plus-plus#4756]
About a month or so ago, Notepad++ stopped showing my custom AutoHotkey syntax highlighting altogether.  All the correct settings are still present in the "Define your language..." dialog.  I don't know what's happening.  Can someone help me?

**Comment by ClaudiaFrank** [comment]
If you would have provided the information you were asked for when creating this issue,
then probably someone could have given some adivce. But without knowing your setup ...

**Comment by AtmaX** [comment]
What information is that?

**Comment by sasumner** [comment]
@AtmaX , when you click the "New Issue" button, the form that opens is pre-populated with a template to be filled in.  I believe this is what @ClaudiaFrank means.

**Comment by ArkadiuszMichalski** [comment]
@AtmaX Do you still have this problem in latest Notepad++ version?

**Comment by donho** [comment]
Please create a new issue with complete info, if the issue is persistent in the latest version.
