### ISSUE TITLE
Function List toolbar icon uses Adobe Flash "F" (or lookalike)

### ISSUE THREAD

**Issue by Explorer09** [notepad-plus-plus/notepad-plus-plus#4764]
### Description of the Issue
The "Function List" toolbar icon (specifically [this](https://github.com/notepad-plus-plus/notepad-plus-plus/blob/master/PowerEditor/src/icons/functionList.bmp) and [this](https://github.com/notepad-plus-plus/notepad-plus-plus/blob/master/PowerEditor/src/icons/functionList.ico) in the source) uses a red "F" that somehow looks like [Adobe Flash logo](https://commons.wikimedia.org/wiki/File:Adobe_Flash_Player_v11_icon.png).

Putting the trademark problem aside, I think this would confuse user about the meaning of the icon, mistaking it to something related to Flash.

![npp-function-list-icon](https://user-images.githubusercontent.com/2487263/44011536-c3222fc6-9eeb-11e8-9e17-69bbb57f8b6a.png)

I suggest the icon should be changed. At least don't use red or that specific typeface for the "F", in order to avoid the confusion.

**Comment by sasumner** [comment]
Now Adobe "Flash" owns the letter "F"?  This reminds me of the discussion that the Notepad++ icon was too "green" and hence looked too much like an Excel green icon and should be changed.

**Comment by Explorer09** [comment]
@sasumner
It's the typeface and color combined that makes the "F" symbol confusing. No offense, actually.

**Comment by MetaChuh** [comment]
@Explorer09 

the function icon is based on the math function symbol, as seen at the screenshot below:

![](https://user-images.githubusercontent.com/45773305/57262110-ff163300-706a-11e9-9269-6a20941bd0f7.jpeg)

thank you for your help and best regards.

**Comment by Explorer09** [comment]
@MetaChuh Oh please, what I was requesting is to change the shape a little so that it would look more closely to the f(x) symbol as you mentioned. For example change the one-sided bar of the 'f' to two sides, which can help avoid the confusion.

I know this might sound insane to you, but it's really the coincidence of glyph design that caused the confusion. (With the strong identity of the Flash logo, creating a coincidence is not a good idea, unless you really want your command to mean "export to flash/SWF file", "create ActionScript file" or something like that.)

**Comment by Explorer09** [comment]
@MetaChuh My complaint is actually about usability than a mere question of "what does this button do". Icons generally convey poorly the meaning of the buttons (and don't tell me about hover text - user seldom wait for it to popup and read), and so unless you are accompanying the icons with text, as a general rule you are to design icons that follow user's expectations rather than be creative with them.

**Comment by sasumner** [comment]
> I know this might sound insane to you

Yep, super insane.  Notepad++ developers and support people work long hours. Please don't waste their valuable time with such dumb and trivial matters.

**Comment by ianleeder** [comment]
+1
I was wondering why NotePad++ had a Flash button.  That is not a generic "function" F, that's a specific brand styling.
![Comparison of NotePad++ F and Adobe Flash F](https://user-images.githubusercontent.com/8241300/110389507-b9887e00-80b8-11eb-9d51-4a64319c8dff.png)
