### ISSUE TITLE
Convert the entire file to upper case truncates file

### ISSUE THREAD

**Issue by gafajardogr** [notepad-plus-plus/notepad-plus-plus#4765]
### Description of the Issue

The file is opened, everything is selected and the edit menu is converted to CAPS, the file is revised and it is no longer complete
### Steps to Reproduce the Issue

1. The file is opened
2. everything is selected (Ctrl-A)
3. the edit menu is converted to CAPS
4. the file is revised and it is no longer complete

### Expected Behavior

The file must be complete
### Actual Behavior

truncate rows
### Debug Information

Notepad++ v7.5.8   (32-bit)
Build time : Jul 23 2018 - 02:03:53
Path : C:\Apps\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 7 (64-bit)
Plugins : PluginManager.dll DSpellCheck.dll mimeTools.dll NppConverter.dll NppExport.dll

**Comment by gafajardogr** [comment]
please try large files

**Comment by ClaudiaFrank** [comment]
Can you provide information how large such a file should be to encounter this issue?

**Comment by gafajardogr** [comment]
Size : 88.494.283 bytes 837668 Text Lines, truncate last line

![imagen](https://user-images.githubusercontent.com/30834211/44404326-4465f500-a51c-11e8-93e7-4318f1690d25.png)

**Comment by gafajardogr** [comment]
Size : 88.494.283 bytes 837668 Text Lines, the last line is incomplete

imagen
![imagen](https://user-images.githubusercontent.com/30834211/44404811-5a27ea00-a51d-11e8-8882-2fc27e55638c.png)

**Comment by ClaudiaFrank** [comment]
Was able to convert even a bigger file without that issue BUT only on a x64 version

![grafik](https://user-images.githubusercontent.com/16170444/44425798-39977880-a58d-11e8-8e6e-9c73123b6f1e.png)

on 32bit I encountered a freeze - I'll try to dig deeper.
