### ISSUE TITLE
Funtion List empy if App opened through file

### ISSUE THREAD

**Issue by solsbarry** [notepad-plus-plus/notepad-plus-plus#4766]
### Description of the Issue
If NPP is closed and I open it by double clicking a file with a associated file extension, then my Function List is empty for all files and never populates.

If I open NPP by clicking on the program's shortcut, then Function List is populated for all files i subsequently open. 

File type does not seem to matter (c, python, etc)

### Steps to Reproduce the Issue

1. Open NPP by double clicking a file with an associated extension.
2. 
3. 

### Expected Behavior
The file opens in NPP, and the function List is populated with the functions.

### Actual Behavior
NPP opens the file but the function list is empty.

### Debug Information
Notepad++ v7.5.8   (64-bit)
Build time : Jul 23 2018 - 02:06:36
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10 (64-bit)
Plugins : DSpellCheck.dll mimeTools.dll NppConverter.dll

**Comment by ClaudiaFrank** [comment]
Works for me, [see here](https://i.imgur.com/rn6NGwx.png).
Would you mind trying the steps I've asked for [here](https://github.com/notepad-plus-plus/notepad-plus-plus/issues/4753)?

**Comment by ArkadiuszMichalski** [comment]
@solsbarry Do you still have this problem in latest Notepad++?

**Comment by solsbarry** [comment]
Yeah I don't have this issue anymore. I have a different version of NPP and a new computer. Sorry I never responded to the first response. I honestly barely remember this.
