### ISSUE TITLE
File encoding determination issue

### ISSUE THREAD

**Issue by Chebroller** [notepad-plus-plus/notepad-plus-plus#4767]
### Description of the Issue
There is a text file of Windows-1251 encoding which is displayed properly (File_A.m in the attachment). There is exactly the same file but one byte longer than the first one (File_B.m in the attachment), which is displayed incorrectly (wrong characters appear) due to Notepad++ determines its encoding as Macintosh. Both files are similar except the last byte and both were created in MATLAB on Windows platform. Both files are displayed properly in all other text editors that I tried (standard Windows notepad, MS Word, WardPad, Visual Studio).

### Steps to Reproduce the Issue

1. Open File_A.m and see no problem with cyrillic symbols as well as with encoding determined as Windows-1251.
2. Open File_B.M and see wrong characters in many places and encoding determined as Macintosh.

### Expected Behavior
Notepad++ has to determine encoding of the both files as Windows-1251. As a result, no incorrect characters should appear.

### Actual Behavior
Encoding of the File_B.m is determined as Macintosh. As a result, many cyrillic symbols in File_B.m are displayed incorrectly, while the File_A is displayed properly.

### Debug Information
Described probles was observed on two machines:

Notepad++ v7.5.8   (32-bit)
Build time : Jul 23 2018 - 02:03:53
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 7 (64-bit)
Plugins : PluginManager.dll DSpellCheck.dll mimeTools.dll NppConverter.dll NppExport.dll 

Notepad++ v7.5.6   (64-bit)
Build time : Mar 19 2018 - 00:23:17
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10 (64-bit)
Plugins : DSpellCheck.dll mimeTools.dll NppConverter.dll 

![file_a](https://user-images.githubusercontent.com/42390637/44118266-34f9e066-a01e-11e8-9537-69186aa08d65.PNG)

![file_b](https://user-images.githubusercontent.com/42390637/44118282-3facc5fa-a01e-11e8-8833-6faf9f6ea6f0.PNG)

[Files_A_and_B.zip](https://github.com/notepad-plus-plus/notepad-plus-plus/files/2288474/Files_A_and_B.zip)

**Comment by rddim** [comment]
Disable the `Autodetect character encoding` in `Settings` > `Preferences...` > `MISC.`

#940, #2843, #3188, #3222, #3588, #4591
