### ISSUE TITLE
Dragging files to new instance loses their language

### ISSUE THREAD

**Issue by burnchar** [notepad-plus-plus/notepad-plus-plus#4769]
### Description of the Issue
Dragging a file to a separate instance loses its language (as in the Language drop-menu, not the encoding or spoken language).
### Steps to Reproduce the Issue

1. Open a file such as test.cs whose language would be set automatically by the file name, or any other file and set its language manually
2. Create a new instance of Notepad++, e.g. using Run--> Open [a file] in another instance
3. Notice that the language is set to C# in the original instance but not in the new instance

### Expected Behavior
New instance uses the same logic as the original to automatically set language.
If the language was set manually, new instance inherits that setting.

### Actual Behavior
File is displayed as plain text with no color or collapsible areas

### Debug Information
Notepad++ v7.5.8   (32-bit)
Build time : Jul 23 2018 - 02:03:53
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : ON
Local Conf mode : OFF
OS : Windows 7 (64-bit)
Plugins : JSMinNPP.dll NPPJSONViewer-win32.dll NppTextFX.dll PluginManager.dll XMLTools.dll DSpellCheck.dll mimeTools.dll NppConverter.dll NppExport.dll

**Comment by CookiePLMonster** [comment]
If you select Open in New Instance or Move to New Instance, language settings inherit properly.

I seem to be unable to use Run -> Open in another instance to move an opened file to another instance. It seems to try to open a file whose name corresponds to text I highlighted instead.

**Comment by burnchar** [comment]
I believe I experienced the same problem. I didn't know that highlighted text was related, but the first few times I tried to Run-->Open, NPP told me that a seemingly random (highlighted text, perhaps) file name did not exist. This may be a feature, though perhaps it should be split into a separate menu item to avoid this confusion.

**Comment by dinkumoil** [comment]
Duplicate to #4711

**Comment by spunkyjethro** [comment]
I'm also experiencing this issue. I drag and drop open tabs to create multiple instances of NPP, but it does not remember the file's language. This was not an issue in the past.

**Comment by chcg** [comment]
From #4711 

> 
> 
> 
> ### Description of the Issue
> 
> Syntax highlighting is not enabled when dragging tabs between different instances
> 
> ### Steps to Reproduce the Issue
> 
> 1. Open 2 .py files in Instance1 + some random filler files to keep first instance open
> 2. (for me) right click tab -> Move tab to new instance for one of the .py files
> 3. Drag the 2nd .py file to the new instance
> ### Expected Behavior
> 
> 2nd py file should still be nice and syntax-highlighted.
> ### Actual Behavior
> 
> 2nd py file does not have syntax highlighting
> ### Debug Information
> 
> Notepad++ v7.5.8   (32-bit)
> Build time : Jul 23 2018 - 02:03:53
> Path : C:\Program Files (x86)\Notepad++\notepad++.exe
> Admin mode : OFF
> Local Conf mode : OFF
> OS : Windows 10 (64-bit)
> Plugins : Explorer.dll IndentByFold.dll LightExplorer.dll nppRegEx.dll PluginManager.dll XMLTools.dll DSpellCheck.dll mimeTools.dll NppConverter.dll NppExport.dll 
> 
>

**Comment by ArkadiuszMichalski** [comment]
@burnchar Do you still have this problem in latest Notepad++ version? Looks like same as https://github.com/notepad-plus-plus/notepad-plus-plus/issues/4883.

**Comment by donho** [comment]
I
