### ISSUE TITLE
Wrong "Smart Highlight" marks after "Collapse Current Level"

### ISSUE THREAD

**Issue by Yaron10** [notepad-plus-plus/notepad-plus-plus#4774]
**STR:**
1) Disable/Uncheck (all boxes) in `Preferences -> Highlighting -> Smart Highlighting`.
2) Copy and paste the following code and set the language to C++.
```
switch(current)
{
	case 'r':
		result[j] = '\r';
		break;
	case 'n':
		result[j] = '\n';
		break;
	case '0':
		result[j] = '\0';
		break;
}
```
3) Select the word `case`.
4) Click on `-` in the margin (Collapse Current Level).
5) Click on `+` in the margin (UnCollapse Current Level).

**Result:**

![default](https://user-images.githubusercontent.com/10229320/44308744-e0c8b400-a3c3-11e8-960b-82868fe44ad9.png)

**Suggestion:**

Replace the following line in `SmartHighlighter.cpp`
`if (pHighlightView->execute(SCI_GETSELECTIONEMPTY) == 1)`
with
`if (!nppGUI._enableSmartHilite || pHighlightView->execute(SCI_GETSELECTIONEMPTY) == 1)`

This should fix some other "Smart Highlight" issues as well (e.g. https://github.com/pnedev/compare-plugin/issues/168).

Feel free to fix or submit a PR.
Thank you.

**Comment by pnedev** [comment]
Good job @Yaron10 !
Looking at the code the same misbehavior will appear if you disable smart highlight select `case` in your example and then zoom in or out the scintilla view (Ctrl+mouse wheel in the view for instance).

**Comment by pnedev** [comment]
Hello @Yaron10 ,

It is OK this way - the code will clear or set highlights depending on the setting which is more robust.
Thank you :+1: 

Thank you @donho .

BR
