### ISSUE TITLE
Golang languages

### ISSUE THREAD

**Issue by freesoft0000** [notepad-plus-plus/notepad-plus-plus#4778]
Syntax highlighting for Golang languages is not supported by default

And the reading display of the MD file does not support

**Comment by newpost** [comment]
When syntax highlighting for Golang languages is not supported by default?

**Comment by iota77** [comment]
@donho please, add golang

**Comment by MetaChuh** [comment]
please use one of the golang udls like: https://gist.github.com/blinksmith/99e5234ea601af8ba8bfab35c8fbebef

thank you for your help and best regards.
