### ISSUE TITLE
Incorrect commenting XML

### ISSUE THREAD

**Issue by NN---** [notepad-plus-plus/notepad-plus-plus#478]
``` xml
<a> <b></b> </a>
```

Select
Press Ctrl+K you get:

``` xml
<a> <!-- <b></b> --> </a>
```

Now select everything, Ctrl+K, you get:

``` xml
<!-- <a> <!-- <b></b> --> </a> -->
```

This is an incorrect xml.
The commenting operation must take care of inner comments and change them accordingly.

XMLTools plugin does it correctly but Notepad++ built-in feature doesn't.

**Comment by Rikk** [comment]
I think this thing happens for all languages, also when using the "block comment"...

**Comment by Jack-William** [comment]
I've followed your instructions but the problem didn't occur.
 My final result is:

`<!-- <a> <b></b> <a> -->`

I have 32 bit Notepad++  v7.5.1

**Comment by donho** [comment]
I believe this issue has been fixed since long time ago.
Update your Notepad++ to the latest version (v7.6.6).
If the issue persists, please create a new issue for it.
Thank you.
