### ISSUE TITLE
Feature Request: Make Search in Files (and Replace) use all CPU Cores  

### ISSUE THREAD

**Issue by chrisaige** [notepad-plus-plus/notepad-plus-plus#4780]
Maybe make it configurable (how many cores should be used).
And also you could make an option to automaticly balance it depending on how much the drive is used. Lets say I use 1 core (CPU1: 100%, Drive: 33%) would automaticly balance to use 3 Cores (if availible) so the drive is fully utilized (I know it doesnt work exactly that way but something along those lines)

Currently its really slow when I want to search big directories because it only does one file at a time, even tho I have a big workstation that could spare the extra cores and the drive is utilized at 10%

I wrote a short Java Program that does this for me, but I think it would be a nice feature to add to nodepad++ directly.

What do you guys think? Or might this have unwanted consequences?

**Comment by ClaudiaFrank** [comment]
duplicate, should be closed
See #3562 - update/upvote accordingly
