### ISSUE TITLE
Notepad++ is crashing for opening file larger than 200MB

### ISSUE THREAD

**Issue by prasoon23** [notepad-plus-plus/notepad-plus-plus#4781]
### Description of the Issue
Notepad++ is crashing while opening large text file like 200MB and above.

### Steps to Reproduce the Issue

1. Open a text file of size more than 200MB in notepad++. 

### Expected Behavior
Notepad should able to open the file without any problem.

### Actual Behavior
Notepad++ is taking more than 20 minutes but still file is not getting loaded.

**Comment by MetaChuh** [comment]
please update your notepad++ to the latest 64 bit version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins if you update from version 7.5.9 or below.
if your issue still persists, and it is still of relevance, please feel free to file a new issue as easy to understand and reproducible as possible.

thank you for your help and best regards.
