### ISSUE TITLE
Environment variable not interpreted in Save As Dialog box

### ISSUE THREAD

**Issue by viewpointsa** [notepad-plus-plus/notepad-plus-plus#4785]
### Description of the Issue
When you use env var in save dialog box, variable is not interpreted

### Steps to Reproduce the Issue
1. Create New file
2. Append some text
3. File > Save
4. Fill filename textbox with %TEMP% type enter

### Expected Behavior
Go to %TEMP% folder

### Actual Behavior
Save file as %TEMP%.txt

**Comment by brianjbowers** [comment]
Yes, this bug drives me crazy!

**Comment by sasumner** [comment]
It's not a bug.  It is a feature that some other programs have that doesn't exist in Notepad++.

**Comment by MetaChuh** [comment]
@viewpointsa 

please go to `settings > preferences > default directory` and activate `use new style dialog`, as seen at the screenshot below.

after that, you can use %temp%, %appdata%, etc. at the open and save dialogues.

![Imgur](https://i.imgur.com/fibS0kv.png)

thank you for your help and best regards.

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
(no extra account is needed, just use your github account to sign in)
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)

**Comment by brianjbowers** [comment]
> It's not a bug. It is a feature that some other programs have that doesn't exist in Notepad++.

Not really. It is expected behavior for Windows applications.

**Comment by sasumner** [comment]
Ah...new style, old style...sure causes a lot of "issues" for users!  Too bad one of those can't go away...but we know you can't ever remove features from software, or too many people will cry.  (Actually, I didn't know about evars being available in the new-style dialog).
