### ISSUE TITLE
Add Discord Rich Presence

### ISSUE THREAD

**Issue by Bartuzen** [notepad-plus-plus/notepad-plus-plus#4787]
Title explains all. I want you to add Discord Rich Presence support.

**Comment by DavidHansen-0x454d43** [comment]
@Bartuzen I feel like the title _doesn't_ explain it all. I did a few minutes of research and am kinda confused why you'd like to include an API designed for games into a text editor. 

Maybe you can tell us briefly what "Discord Rich Presence" is... or
What Discord Rich Presence  features do you want to access in Notepad++

**Comment by Bartuzen** [comment]
If you don't understand the title, it is means that you don't know Discord. Here is a few example of 298732173129 other non-game programs' Rich Presence. If you are still not satisified, I can still find hundereds of these.
[Imgur](https://imgur.com/a/f1S0Z72)

**Comment by DavidHansen-0x454d43** [comment]
@Bartuzen, I know discord is a voice chat server mostly used for gaming. I've used it before, but I still don't know why you would want to integrate it into Notepad++. Can you please give us a use case for how you would like to use rich presence in Notepad++?

Also your imgur link appears broken...  and wtf does this mean:
> Here is a few example of 298732173129

**Comment by DavidHansen-0x454d43** [comment]
@Bartuzen, ok I am able to open the link now, and I can kinda see how this could be useful for remote pair programming. 

However, if you can't even take 5-10 minutes to articulate what your requested feature does, or why it would be useful. then how can ask someone to spend 5-10 hours implementing it?

**Comment by cwongmath** [comment]
Discord RP Integration with Notepad ++ would allow other Discord members to see what you are working on. It would be similar to Visual Studio's DiscordRPCVS extension, where it says what you are developing and from which project.

**Comment by coooool123** [comment]
bump

**Comment by Bartuzen** [comment]
Btw i made RPC for Notepad++ with Python but unluckily there is no `how to use` yet.
https://github.com/Bartuzen/NotepadRPC.py

**Comment by SocraticBliss** [comment]
> Btw i made RPC for Notepad++ with Python but unluckily there is no `how to use` yet.
> https://github.com/Bartuzen/NotepadRPC.py

Seems to have a few problems when the dependencies are not installed (also, may want to print out that it isn't compatible with python 2.7?)

**Comment by MetaChuh** [comment]
@Bartuzen 

many thanks for your ideas.
while this could be a nice add on as a plugin, discord rpc will not be integrated into the notepad++ core.

thank you for your help and best regards.

**Comment by 2cwldys** [comment]
How. Extremely. Unfortunate.

**Comment by sasumner** [comment]
@MetaChuh was nice about closing/rejecting it.  This is a Dumb idea with a capital "D", with an original requester that couldn't, after multiple solicitations, even attempt to talk about why this might be beneficial for Notepad++ (it wouldn't be).  Then the original requester threw together some "thing" that he couldn't even take the time to make a "how to use" for -- and he wants Notepad++ developers to spend serious time on this as a new feature?  Ugh.  Why would I want to "allow other Discord members to see what (I am) working on"?  Anybody ever heard of the concept of privacy?

**Comment by DavidHansen-0x454d43** [comment]
@sasumner, it appears like the author _has_ updated the project with a "how to" since their post. 

I don't really use Discord and only have a fuzzy grasp why this might be useful, but from the number of thumbs up it looks like the _someone_ does. 

I want to commend @Bartuzen for making this, encourage them to polish it up and submit it to the official plug in list... I think many people would appreciate it. 

@2cwldysm I agree with @MetaChuh that this doesn't belong in N++ Core (it isn't in the Visual Studio core).

**Comment by Flame-0** [comment]
bump

**Comment by sasumner** [comment]
bump of closed/rejected issue is pointless

**Comment by PalmoliveDev** [comment]
This feature is important and it should be added. This issue should not be closed. It would be important in programming Discord servers or programming with friend or in teams. Although, I understand that there are already plugins which accomplish this, it would be nice to have this built-in.

**Comment by dail8859** [comment]
@PalmoliveDev What would be the benefit if having it built-in rather than a plugin?

**Comment by grian32** [comment]
ease of use

**Comment by VladPutinEu** [comment]
> @PalmoliveDev What would be the benefit of having it built-in rather than a plugin?

It would be better if it was built-in. This would be a big step, making Notepad++ the only major text editor with a built in rich presence.

**Comment by MikeCoder96** [comment]
I've created a plugin for notepad++
https://github.com/MikeCoder96/NotePad-Discord-Rich-Presence-Plugin
I hope in community contributions ❤️
