### ISSUE TITLE
No diskette icon in Doc Switcher (x64 installer, 7.5.8)

### ISSUE THREAD

**Issue by a95s** [notepad-plus-plus/notepad-plus-plus#4789]
After I've updated Notepad to x64 7.5.8 with the installer version (only with convert plugin), there were no diskette icons in Doc Switcher. They didn't appear after relaunch (didn't test the reboot though).

After I've updated to x32 7.5.8 installer version (minimalist), they've appeared again (thanks god).

Not critical but may be irritating to someone.

**Comment by Hafureluspatha** [comment]
Probably related issue: #944

**Comment by MetaChuh** [comment]
please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins if you update from version 7.5.9 or below.
if your issue still persists, and it is still of relevance, please feel free to file a new issue as easy to understand and reproducible as possible.

thank you for your help and best regards.

-----
```
general notes:

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).
please file an issue as easy to understand and reproducible as possible.

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
(no extra account is needed, just use your github account to sign in)
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)

**Comment by a95s** [comment]
The issue didn't occur in further versions.
