### ISSUE TITLE
Automatic indentation detection

### ISSUE THREAD

**Issue by Ede123** [notepad-plus-plus/notepad-plus-plus#479]
A _really_ helpful feature for Notepad++ would be automatic indentation detection (e.g. tabs or spaces? 2 or 4 spaces? etc.)

In fact we already have a patch for that!
- Original patch was at https://sourceforge.net/p/notepad-plus/patches/645/
- A pull request (that predates the project's move to GitHub) is at https://github.com/mirror/notepadplus/pull/1
- The (slightly outdated) forked repository is at https://github.com/john-peterson/notepadplus/commits/indent

Questions:
- @ project maintainers: Could this finally be considered for merging? It is one of those long-standing issues where a volunteer has put in considerable time and effort, but that (for whatever reason) was never merged by Don back then.
- @john-peterson: Would you be willing to update the pull request? (Of course I'd understand if you where hesitant, unless there's some positive feedback by maintainers)

**Comment by john-peterson** [comment]
k

**Comment by john-peterson** [comment]
done https://github.com/notepad-plus-plus/notepad-plus-plus/pull/480

**Comment by Ede123** [comment]
Great! Let's hope it can be merged finally. :+1:

**Comment by dail8859** [comment]
I haven't had a chance to look at the PR yet but I'm curious if there would be any performance impact. Especially loading large (200MB+) files. With 64bit N++ it will be able to load even larger files.

**Comment by milipili** [comment]
Please read the CONTRIBUTING.md... Anyway this PR can not be merged like that, but this code can be used for the feature. I will see that after I've finished with cmake.

**Comment by vincepare** [comment]
If you can't wait for this feature to be merged, you can use this python script as a workaround : [Automatic indentation detection for Notepad++](https://gist.github.com/vincepare/8a204172d959defb2122) (requires [Python Script](http://sourceforge.net/projects/npppythonscript/files/Python%20Script%201.0.8.0/) extension).

After installing Python Script, put the startup.py file either into `%appdata%\Notepad++\plugins\config\PythonScript\scripts` (user script) or into `C:\Program Files\Notepad++\plugins\PythonScript\scripts` (machine script).

Then, go to Notepad++ : Plugins > Python Script > Configuration, select the `startup.py` script and choose `ATSTARTUP` as Initialisation to run the script at notepad++ startup.

**Comment by MetaChuh** [comment]
we are closing this issue due to its age and multiple newer notepad++ versions since it was filed.

please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html).
if your issue persists, and it is still of relevance to you, please feel free to file a new issue.

thank you for your help and best regards.

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
```
[<kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd>](https://notepad-plus-plus.org/community/)
