### ISSUE TITLE
[Feature request] File status auto-detection improvement

### ISSUE THREAD

**Issue by TroudhuK** [notepad-plus-plus/notepad-plus-plus#4791]
### Description of the Issue

For me the worst feature of Notepad++ in everyday life is the "File status auto-detection" and its very annoying popups and tabs changing, if you keep a lot of "living" tabs (logs, configuration files...). The functionality is very useful but the way to notify it is too annoying.

![image](https://user-images.githubusercontent.com/11449740/44536589-1ee41180-a6fd-11e8-96a1-5b157014063c.png)

### Steps to Reproduce the Issue
For example, have 3 tabs, edit the 3 files out of Notepad++ then try immediatly to open a fourth file with Notepad++: the fourth tab is opened BUT you have to click on 3 popups and it's the only way to be notified of external changed AND have the choice to reload or not.

### Expected Behavior

We need an intermediate way between modal popup + tab switching and auto-update, because we want to know that the real file changed, but keep the last opened version for some reasons and manually reload later (thanks to Reload Button shortcut for File -> Reload from disk).

It can be an icon color (a yellow one? we have the red icon when the file is edited and not saved), and why not a top bar appearing with a reload button... Or, at least, the popup should be only tab-modal and not disturb the work on an other tab.

**Comment by dinkumoil** [comment]
I guess this is a case that is very difficult to solve in a way that all or at least **nearly** all users of Notepad++ are satisfied. In the past there have been suggestions for a dialog box where users can choose between `Reload`, `Reload All`, `Ignore` and `Ignore All`, but that wouldn't fit user's requirements in all situations.

Have you tried to turn off file status auto-detection and using the file monitoring feature (the eye in the toolbar) on a per-tab basis?

**Comment by donho** [comment]
https://github.com/notepad-plus-plus/notepad-plus-plus/commit/ba60fbdd715d647aa5ce7be5b6b75182b4a52951
