### ISSUE TITLE
Plugins > Mime Tools > SAML Decode doesn't work

### ISSUE THREAD

**Issue by starrychloe** [notepad-plus-plus/notepad-plus-plus#4792]
### Description of the Issue
The SAML decode doesn't work. It inserts a bunch of NUL values in the text. You can compare to an online SAML debugger: https://rnd.feide.no/simplesaml/module.php/saml2debug/debug.php

### Steps to Reproduce the Issue
1.  Copy the sample encoded SAML request from the online decoder.
2.  Paste into Notepad++
3.  Select the text and select Plugins > Mime Tools > SAML Decode

### Expected Behavior
The same text as the online SAML debugger

### Actual Behavior
![image](https://user-images.githubusercontent.com/1039276/44545909-52ff0880-a6e4-11e8-8827-6dfafffe3976.png)

### Debug Information
Mime tools 2.1
Notepad++ 7.5.6
```
Notepad++ v7.5.6   (64-bit)
Build time : Mar 19 2018 - 00:23:17
Path : c:\program files\notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 8.1 (64-bit)
Plugins : DSpellCheck.dll mimeTools.dll NppConverter.dll NPPJSONViewer-x64.dll 
```

**Comment by starrychloe** [comment]
It would figure I'm the only one who would use that feature https://github.com/notepad-plus-plus/notepad-plus-plus/issues?utf8=%E2%9C%93&q=is%3Aissue+saml

**Comment by dail8859** [comment]
As this is plugin related, please open a ticket over here: https://github.com/npp-plugins/mimetools
