### ISSUE TITLE
Close All needs verification pop up

### ISSUE THREAD

**Issue by jrheisey** [notepad-plus-plus/notepad-plus-plus#4795]
### Description of the Issue
When clicking the "Close All" toolbar button by accident it is very inconvenient to remember each file and where to find them in a large project. 
I had about 20 open files.

### Steps to Reproduce the Issue
1. Open a set of files
2. Click the "Close All" button on the toolbar
3. All files are immediately closed without any confirmation

### Expected Behavior
I expect a pop up dialog confirming to close all the tab views.

### Actual Behavior
Tabbed views are immediately closed

### Debug Information
N/A

**Comment by donho** [comment]
Not like "Save All" which needs a warning popup because the operation modifies all the open files' content, "Close All" close all opened file without modification. A popup will be annoying for the most users.
Save your session for opening all your files so the problem solved.
