### ISSUE TITLE
Place Newly-Opened Tabs Adjacent to the Current Tab

### ISSUE THREAD

**Issue by PSMc** [notepad-plus-plus/notepad-plus-plus#4800]
### Description of the Issue
When a file is opened from within Notepad++, please open the new tab adjacent to the currently-selected tab instead of (all the way) at the end of the strip of tabs.

### Steps to Reproduce the Issue
1. Open four or more files in Notepad++.
2. Select the second tab.
3. Click "Open..." from the toolbar to open a new file.
4. Notice that the tab dedicated to the new file appears at the end of the strip of tabs, and not adjacent to the second tab, which would be more intuitive and pragmatic while reflecting behavior associated with tab-based browsing (on the web, for instance).

### Expected Behavior
I would expect the new tab to be opened just to the right of the current (second) tab. If my regional settings were set to Farsi standards, then I would expect the tab to appear just to the left.

### Actual Behavior
The new tab appeared at the end of the (long) strip of tabs.

### Debug Information
N/A

**Comment by PSMc** [comment]
It would be nice if new, empty tabs spawned from the "New" button of the toolbar were also placed adjacent to the currently-selected tab.

**Comment by ArkadiuszMichalski** [comment]
@sasumner Same as https://github.com/notepad-plus-plus/notepad-plus-plus/issues/3323, was rejected.
