### ISSUE TITLE
Exiting application needs to have a cancel option

### ISSUE THREAD

**Issue by jrheisey** [notepad-plus-plus/notepad-plus-plus#4801]
### Description of the Issue
If you initiate an Exit by accidentally clicking the close button on the Caption Bar and if multiple Tabs are 'dirty' causes a multiple popups asking whether to save the tab and no way to cancel the Exit.

### Steps to Reproduce the Issue
1. Open several files and edit a couple without saving them
2. Click the red Close button on the upper right of the Caption Bar.

### Expected Behavior
I suggest a more comprehensive dialog where each 'dirty' file is listed with the button:
'Save All and Exit'
'Cancel Exit' - no save action is taken and the Exit is not performed.

In addition I suggest providing a way to select one or more 'dirty' files in the list and click one of these buttons:
'Save Changes'
'Discard Changes'
As each Save or Discard is performed the file is removed from the list.

### Actual Behavior
You will get multiple popups asking whether to save and no way to cancel the Exit if it was accidental.

**Comment by CookiePLMonster** [comment]
> You will get multiple popups asking whether to save and no way to cancel the Exit if it was accidental.

But Cancel button already exists and does exactly what you want, or I am terribly misunderstanding your report?

![image](https://user-images.githubusercontent.com/7947461/44955007-50eb3580-aeac-11e8-8643-682c9cd62c60.png)

**Comment by MetaChuh** [comment]
@jrheisey 

if your notepad++ version does not have a cancel button on exit, please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins if you update from version 7.5.9 or below.

thank you for your help and best regards.

-----
```
general notes:

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).
please file an issue as easy to understand and reproducible as possible.

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
(no extra account is needed, just use your github account to sign in)
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)
