### ISSUE TITLE
Backup problem.

### ISSUE THREAD

**Issue by congaman59** [notepad-plus-plus/notepad-plus-plus#4802]
### Description of the Issue
I used N++ v7.5.8 to save some notes I was taking to use in the future. I went back to the file name I saved it under and there was no text there. I tried going to the backup for that file name but it had a few lines of text that I didn't recognize. I know the information was in the file. I just can't figure out what happened. I have the save backup turned on. Is there anything else I can do to find the info? I'm running windows10.
I hope I posted in the right place. It's the first time I have used this forum.

**Comment by MetaChuh** [comment]
@congaman59 

sorry for the delay.

i hope you have found our [notepad++ community forum](https://notepad-plus-plus.org/community/) back then, which treats non source code related questions.

many thanks and best regards.

**Comment by sasumner** [comment]
@congaman59 Good info on how the backup feature of Notepad++ works is found:
https://notepad-plus-plus.org/community/topic/16930/backup-not-work-3-04-45-pm-sunday-january-13-2019
and
https://notepad-plus-plus.org/community/topic/17447/updated-and-lost-all
