### ISSUE TITLE
Bug: Wrong char !

### ISSUE THREAD

**Issue by Jackghd** [notepad-plus-plus/notepad-plus-plus#4805]
### Description of the Issue
npp display this character wrong (utf8): §. 

### Steps to Reproduce the Issue
1. Utf8 selected and using an italian keyboard, type the char § in a file and save
2. Close the file
3. Open the file

### Actual Behavior
It display some indian char instead of §

### Debug Information
Win8 / Npp 7.4.2 64bit

**Comment by ClaudiaFrank** [comment]
Probably you activated autodetect character encoding under Settings-> Misc. Can this be?

**Comment by ClaudiaFrank** [comment]
Well that is exactly the issue - to few chars to detect an encoding.
The used detection library is, by the way, mozillas chardet lib.

**Comment by Jackghd** [comment]
Oh mozilla, long time ago, good guys... I suppose I can close this issue
