### ISSUE TITLE
Close All as well as Close All BUT This

### ISSUE THREAD

**Issue by rcwwilliams** [notepad-plus-plus/notepad-plus-plus#4806]
Hi

Thank you all so much for Notepad++ I have been using it for all code development and plenty for several years and it is brilliant!

It would be really create to have a "Close All" option for the right click dropdown menu for a tab (as well as "Close All BUT This" etc).

Thanks very much.

Kind regards

Robin

**Comment by sasumner** [comment]
Just a check:  You do know that there is a "Close All" on the "File" menu, right?  Same number of actions as if it were on a tab's right-click...  I think it is not on a tab's right-click because it isn't related to the current tab, while the other actions are.

**Comment by rcwwilliams** [comment]
Yes, know that, but would be great to have it on the right-click too.  Chrome dev tools has it and it’s really useful.

**Comment by ClaudiaFrank** [comment]
Just another check: you know that you can modify the **context menu** of the **document**?
Not the tab context menu.

**Comment by rcwwilliams** [comment]
Thanks for the comment - appreciated.

If you think my request is reasonable and easy to put in a future release, that would be great.

**Comment by ClaudiaFrank** [comment]
Just for clarification as I'm unsure about your respond on my comment.
You can have what you want in the context menu of the document **right now**
but not in the context menu of the tab.

**Comment by sasumner** [comment]
It's also available as an assignable keycombination in shortcut mapper.....but people want what they want...  :-)

**Comment by sasumner** [comment]
Just a side note:  Personally I think Close All (and similar) this way are a bit dangerous as it is easy to "stutter" with the mouse and accidentally choose it when unintended.  If you have many dozens of tabs open (that you WANT to have open) and no saved session, there is no confirmation...your files get closed--boom.

**Comment by rcwwilliams** [comment]
Fine - I am very happy with your suggested workaround, so please close this issue if you wish to.

Thanks again :)
