### ISSUE TITLE
More intuitive Spell Check for Spanish language with characters "¡" and "¿"

### ISSUE THREAD

**Issue by Ricosoft** [notepad-plus-plus/notepad-plus-plus#4807]
![npp bad spell check](https://user-images.githubusercontent.com/39334698/44841044-f8106880-ac31-11e8-9613-ddec5ea501e1.png)
![npp ok](https://user-images.githubusercontent.com/39334698/44841045-f8106880-ac31-11e8-8404-737ea2e42fdd.png)

### Description of the Issue
In Spanish language, we use characters "¡" and "¿" to open a phrase terminated with ! or ?. 
But with the default configuration, the word next to the open-phrase character is marked as a mistake.
rem = ¡Hola!
rem = ¿mayor que cero?
rem = Hello!
rem = greater than zero?

There is a workaround for this bug. The user can fix it in configuration options (menu DSpellCheck > Settings; tab Advanced; Delimiters).

### Expected Behavior
Consider "by default" (installation time) both characters "¡" and "¿" as delimiters (syntactic behavior exactly like ? and !), with no need for an user configuration action to enable this characters as delimiters.

### Actual Behavior
With the default configuration, the word next to ¡ or ¿ includes the character as a part of the word, and the word is marked as mistake (see attached image).

Thanks in advance, and congratulations on your excelent work.
Yours sincerely,
Jose Luis Rico Lazaro

**Comment by ClaudiaFrank** [comment]
Isn't this something for the [author](https://github.com/Predelnik/DSpellCheck/issues)of this plugin
or do I miss something here?
If it is feature request for DSpellCheck plugin then I would ask for closing this issue.
