### ISSUE TITLE
problem opening link to file with C$

### ISSUE THREAD

**Issue by kobygold** [notepad-plus-plus/notepad-plus-plus#481]
Hi,
There is a problem opening a link to file which uses C$ in it's path (or D$ etc.).
For example, a link like this doesn't work (doesn't open the file when you double click it):
 file://PC_NAME/C$/temp/filename.txt

It looks like that the $ sign breaks the link into 2 strings, and thus doesn't link to the right location.

Can you please add the support for the $ sign to work correctly?

Thanks,
Koby

**Comment by kobygold** [comment]
Any idea if this problem will be treated anytime soon...?

Thanks,
Koby

**Comment by tonyk24** [comment]
Hi,

I tried a file like this, and I saw no problem: 
...
C:\Users\Tony\Desktop\C$\temp
...

Tried open the file both from the file dialog, and from double-clicking.

**Comment by donho** [comment]
I believe this issue has been fixed since long time ago.
Update your Notepad++ to the latest version (v7.6.6).
If the issue persists, please create a new issue for it.
Thank you.
