### ISSUE TITLE
Installer setting to include Notepad++ directory in %PATH%

### ISSUE THREAD

**Issue by clisc** [notepad-plus-plus/notepad-plus-plus#4814]
### Description of the Issue
One of the first things I do after installing Notepad++ is add the install directory to the %PATH% user environment variable.  This makes it easier to invoke Notepad++ from the Windows command prompt.  It would be convenient if the installer had a check box I could select to have the installer do it for me.

Bonus:  It would be nice if there was a shortcut npp.cmd and/or npp.exe which simply invoked Notepad++.exe so that I could use "npp" as shorthand for "notepad++" when opening files from the command prompt.

Thanks!

**Comment by MetaChuh** [comment]
@clisc 

we don't like to change unnecessary system settings from within notepad++, as many notepad++ users do not like applications, that fiddle around with their system.

as your procedure to set your system's path is a one time procedure, and you already know how to do it, there will be no logical need to do that from within notepad++.

thank you for your help and best regards.
