### ISSUE TITLE
Opening fonts dir makes Notepad++ unresponsive

### ISSUE THREAD

**Issue by NSoiffer** [notepad-plus-plus/notepad-plus-plus#4815]
### Description of the Issue
Trying to open c:\windows\fonts causes NotePad++ to become unresponsive (can't close open file dialog, etc). Task monitor says it is burning CPU time.

### Steps to Reproduce the Issue

1.  Choose open (ctrl+o)
2.  In file name, either type `c:\windows\fonts` or type `c:\windows` and then navigate to `fonts`.
3.  Click `Open`

### Expected Behavior
Expected to see list of fonts in directory.

### Actual Behavior
The value in `File name` flickers "forever". Task monitor shows CPU is being heavily used. Can't close `Open` dialog or do anything else. The program must be killed off.

### Debug Information
Notepad++ v7.5.8   (32-bit)
Build time : Jul 23 2018 - 02:03:53
Path : C:\Software\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10 (64-bit)
Plugins : NppFTP.dll PluginManager.dll DSpellCheck.dll mimeTools.dll NppConverter.dll NppExport.dll

**Comment by dinkumoil** [comment]
I can confirm this issue as long as the old Save dialog is used. If you switch to the new one (under menu Settings -> Preferences -> Register "Default Directory" -> Checkbox "Use new style dialog ...") an error message pops up that states "You do not have permission to access this file...".

Could be related to #4785 and #4788.

**Comment by CookiePLMonster** [comment]
Further proves that old save dialog is a nuisance...

@donho Given the amount of issues this gives, wouldn't it be the time to either:
1) Say goodbye to the old style dialog
2) Make new style dialog a default

?

**Comment by dinkumoil** [comment]
> ...wouldn't it be the time to either:
> 
 > 1. Say goodbye to the old style dialog
 > 2. Make new style dialog a default

Wouldn't it be time instead to introduce a more strict policy for merging PRs into to release branch of Notepad++? It is very common to see in this project that things get broken because of obviously poorly tested changes to the code base.

**Comment by CookiePLMonster** [comment]
> Wouldn't it be time instead to introduce a more strict policy for merging PRs into to release branch of Notepad++? It is very common to see in this project that things get broken because of obviously poorly tested changes to the code base.

Flow of accepting new PRs to the project is slow as-is, your suggestion would put the project in even bigger hiatus than it is right now.

**Comment by dinkumoil** [comment]
> Flow of accepting new PRs to the project is slow as-is

That's one reason more to test more thoroughly. The fixes for bugs introduced by changes of already existing features may block PRs with improved or new features.

**Comment by CookiePLMonster** [comment]
I believe this is not a regression however, and it's just never been tested well enough.

**Comment by MetaChuh** [comment]
@NSoiffer 

please go to `settings > preferences > default directory` and activate `use new style dialog`, as seen at the screenshot below.

after that, you can use %temp%, %appdata%, etc. at the open and save dialogues.

![Imgur](https://i.imgur.com/fibS0kv.png)

thank you for your help and best regards.

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
(no extra account is needed, just use your github account to sign in)
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)
