### ISSUE TITLE
Smart Highlighting Issue

### ISSUE THREAD

**Issue by tolkensak** [notepad-plus-plus/notepad-plus-plus#4820]
![smart-highlighting-issue](https://user-images.githubusercontent.com/42959545/45017424-634ea600-b049-11e8-82ee-997db2d17da2.png)

**Comment by rddim** [comment]
It works fine on me. What are your settings in `Preferences` > `Highlighting` ?

**Comment by sasumner** [comment]
In the 7.5.8 version of N++, I can replicate @tolkensak 's behavior if the "Match whole word only" option is unticked and there is no line-ending on the last "222" line.

**Comment by tolkensak** [comment]
OS: windows 7 professional service pack 1

settings in Preferences > Highlighting:
![settings in preferences highlighting](https://user-images.githubusercontent.com/42959545/45164531-6fd32a00-b214-11e8-9efb-6a6027b76ab7.jpg)

about Notepad++:
![about notepad](https://user-images.githubusercontent.com/42959545/45164544-7661a180-b214-11e8-9ecc-02a279b67ab1.jpg)

**Comment by tolkensak** [comment]
Find dialog:
![find dialog](https://user-images.githubusercontent.com/42959545/45164826-35b65800-b215-11e8-961f-efa1d6f621d2.jpg)

I think we cannot count the line ending into whole word, isn't it?

**Comment by rddim** [comment]
In my case the `Match whole word only` is checked as @sasumner said above. I don't know about counting...

**Comment by sasumner** [comment]
Still reproducible in 7.6.6 with the OP's data and the info in my Sep 6 2018 comment above.
