### ISSUE TITLE
Fullscreen mode

### ISSUE THREAD

**Issue by dogslife** [notepad-plus-plus/notepad-plus-plus#4821]
### Steps to Reproduce the Issue

1. Launch notepad++7.5.8 32bit
2. key F12 for fullscreen mode
3. Toggle between screens using ALT+TAB release upon selection

### Expected Behavior

Screen should navigate to selected screen
### Actual Behavior

Screen stays on notepad++ but loses focus on the fullscreen

**Comment by dogslife** [comment]
Ste,

Thanks for your super speedy response. Confirmed working and apologies for waiting your valuable time. Ignorance is such a powerful tool when wielded by the incompetent.

But, now that I have a person to actually write to Ste, just wanted to commend you and all others involved - totally fantastic and responsive product. Just wished you'd have done a replacement for MS Word - cause it suck, more than ten sucking things.

Regards

Reggie The Dog

On 06/09/2018 11:26, Stephen Griffiths wrote:

Hi dogslife,

F12 is Post-it mode which causes N++ to be "Always-on-top". Fullscreen mode is triggered with F11 (See the View menu).

Please try using F11 for fullscreen and verify that Alt-Tab works as expected :)

Thanks
Ste

**Comment by SteGriff** [comment]
Hey Reggie,

Funnily enough I am not a contributor, just another user who was in the right place at the right time! I love this project too 🙂 I'm sure the devs will see your kind words.

Cheers
Ste

**Comment by Codextor** [comment]
This issue is resolved and can be closed, right?

**Comment by SteGriff** [comment]
Yes, resolved.
