### ISSUE TITLE
Why does good old Ctrl-F4 not work in Notepad++ on a PC? It SHOULD!

### ISSUE THREAD

**Issue by GrantHorizons** [notepad-plus-plus/notepad-plus-plus#4824]
### Description of the Issue

ctrl-f4 is a Microsoft standard that closes a tab since, well Windows 2? ALL Windows programs should follow it. Why Notepad++ doesn't is a mystery - and really annoying to ahve to use the stupid and slow mouse to do something a keyboard can do much better!

### Steps to Reproduce the Issue

1. Pressed ctrl-f4
2. 
3. 

### Expected Behavior

close the window!
### Actual Behavior

nothing!

**Comment by sasumner** [comment]
Since keyboard shortcuts became configurable in Notepad++, there has been a lack of caring about what the defaults are...or aren't.  Close has a default keyboard shortcut of ctrl+w for apparently historical reasons, but you can easily assign a different one (maybe ctrl+f4) in the "Shortcut Mapper".

**Comment by nlsdg** [comment]
Indeed, many programs use ctrl-w to close documents. Changing the shortcut would make people that like it the way it is unhappy. You can't please everybody.
In any case: it is configurable.

**Comment by sasumner** [comment]
@nlsdg You CAN please everyone where keyboard shortcuts are concerned--you make it configurable--BOOM:  everyone pleased... (except those that just like to complain...everyone else adjusts the shortcut to what they like and moves on with their lives).

**Comment by GrantHorizons** [comment]
**thanks** to those who informed me of the keyboard mapping - didn't know that!
Still think ctrl-f4 should be the default and changeable to whatever you like! :)
And no I don't like to just complain - in fact I rarely do. AND I do tech support as part of my job and get to deal with real complainers!
