### ISSUE TITLE
Feature Request: support session xml files in UTF-8/16 (with BOM or not)

### ISSUE THREAD

**Issue by andry81** [notepad-plus-plus/notepad-plus-plus#4831]
### Description of the Issue
Session files for the Notepad++ hard to construct from poor languages like Windows Batch scripts (.bat/.cmd), for example, if input files for a session are in different encoding in file names. Windows Batch can not manipulate `&#xXXXX;` characters, but instead it still can use utf-8/16 as a raw strings for output or redirection.

### Steps to Reproduce the Issue
Construct session.xml in utf-8/16 (with BOM or not) encoding and file paths in different languages.

### Expected Behavior
Construct session xmls with utf-8/16 encoding and open it as is without file paths conversion into unicode point characters (&#xXXXX;&#xYYYY; and so on).

### Actual Behavior
Does not work.

### Debug Information
N/A

**Comment by MetaChuh** [comment]
> Session files for the Notepad++ hard to construct from poor languages like Windows Batch scripts (.bat/.cmd)

please do not construct session files from poor languages.

thank you for your help and best regards.
