### ISSUE TITLE
Getting .bak files appearing all the sudden which persist

### ISSUE THREAD

**Issue by mzso** [notepad-plus-plus/notepad-plus-plus#4832]
### Description of the Issue
I never had this before. But whenever I open a text file now .bak files appear.
It's curious because I didn't change anything in the settings. I reinstalled the OS under the portable instance of NP++ I use.

### Expected Behavior
Not sure what happened before, but I'm quite sure not this.

### Actual Behavior
Weird .bak files appearing that persist even when I close the files in NPP, and exit the program.

**Comment by sasumner** [comment]
Can you show what your settings are in Settings (menu) -> Preferences... -> Backup

**Comment by mzso** [comment]
[**@sasumner**](https://github.com/sasumner) commented on [2018. szept. 9. 15:15 CEST](https://github.com/notepad-plus-plus/notepad-plus-plus/issues/4832#issuecomment-419715285 "2018-09-09T13:15:03Z - Replied by Github Reply Comments"):
> Can you show what your settings are in Settings (menu) -&gt; Preferences... -&gt; Backup

Yes:
![npp-backup](https://user-images.githubusercontent.com/4479090/45265358-fd4b8f80-b449-11e8-8d2c-2060142756f9.PNG)

So, maybe one of these settings changed erroneously?

**Comment by mzso** [comment]
[**@sasumner**](https://github.com/sasumner) commented on [2018. szept. 9. 16:21 CEST](https://github.com/notepad-plus-plus/notepad-plus-plus/issues/4832#issuecomment-419719203 "2018-09-09T14:21:29Z - Replied by Github Reply Comments"):
> Yes, with those settings you _WILL_ get a .bak file in the same folder for every file you change and save with Notepad++.  Simplest solution is to select "None" instead (if you don't want ANY backups made).

What is the verbose option supposed to do? I can't see anything happening when I have that selected. (at least without setting a directory)

**Comment by mzso** [comment]
Not sure what caused the setting being changed, more than once. But it didn't happen for a long time now. I guess there's no reason to keep this open.

**Comment by 537mfb** [comment]
I just noticed this happened to me today - never noticed it before
I've changed that setting back to none - thanks @sasumner

Maybe an update of Notepad++ changes that setting? I had never went into the preferences window - so maybe the default changed at some point?

**Comment by ArkadiuszMichalski** [comment]
@537mfb Because now it's default https://github.com/notepad-plus-plus/notepad-plus-plus/issues/10725.

**Comment by allensmith81** [comment]
This has been messing up my program and I only just discovered why.. Please DO NOT automatically create any files in the directory of the code I am editing! turned this off

**Comment by jdx-john** [comment]
Why are the BAK files appearing in the same folder as the files they backup? I now have loads of these things all over the place in a folder structure that is auto-synced to other machines.

This seems a dreadful default behaviour to me. I can't even delete all BAK files because it's such a common file-extension some of them might be from others programs that I _want_.

**Comment by Felderburg** [comment]
Are the .bak files meant to last forever? Why don't they disappear when a session ends? (Similar to the MS Office behavior where a temporary file is made, until the actual file itself is saved and closed.)

**Comment by alankilborn** [comment]
>Are the .bak files meant to last forever? 
Yes.

>Why don't they disappear when a session ends?
Because that's not the design of _Simple Backup_ .
