### ISSUE TITLE
Notepad++ : a free (GNU) source code editor has stopped working

### ISSUE THREAD

**Issue by Pascal666** [notepad-plus-plus/notepad-plus-plus#4834]
I've been using Notepad++ for a while now without problem.  Today I hit crtl-shift-s to save all open files (although only the foreground one had actually changed) and got the above error dialog.  "View problem details" shows:

Problem signature:
  Problem Event Name:	BEX
  Application Name:	notepad++.exe
  Application Version:	7.5.8.0
  Application Timestamp:	5b551bcf
  Fault Module Name:	notepad++.exe
  Fault Module Version:	7.5.8.0
  Fault Module Timestamp:	5b551bcf
  Exception Offset:	00128d2e
  Exception Code:	c0000417
  Exception Data:	00000000
  OS Version:	6.1.7601.2.1.0.256.1
  Locale ID:	1033
  Additional Information 1:	09be
  Additional Information 2:	09be4a851e4981aec230285080b760cb
  Additional Information 3:	647f
  Additional Information 4:	647faef0cebfc2b600ba5e64e1c455d1

Debug info from ? menu:
Notepad++ v7.5.8   (32-bit)
Build time : Jul 23 2018 - 02:03:53
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 7 (64-bit)
Plugins : PluginManager.dll DSpellCheck.dll mimeTools.dll NppConverter.dll NppExport.dll 

After I restarted Notepad++ I received a "Reload" dialog saying:
"C:\Users\Pascal\Documents\todo\20180907.txt"
This file has been modified by another program.
Do you want to reload it and lose the changes made in
Notepad++?
Yes/No

I could see my data behind the dialog box, but when I checked the file on disk it was 0 bytes.  I clicked "No" and do not appear to have lost any data.  Ctrl-shift-s works fine again.

**Comment by MetaChuh** [comment]
please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins if you update from version 7.5.9 or below.

thank you for your help and best regards.

-----
```
general notes:

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
(no extra account is needed, just use your github account to sign in)
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)
