### ISSUE TITLE
N++ Not responding

### ISSUE THREAD

**Issue by AldebaraanMKII** [notepad-plus-plus/notepad-plus-plus#4836]
### Description of the Issue
Whenever i type any letter in the far left corner of a line, then immediately try to delete it, N++ will hang for several seconds in the "Not responding state". 

Is this because my file has over 80k lines and it's over 4MB? I'm dealing with .py files btw.

### Steps to Reproduce the Issue
1. Open a very large .py file with over 80k lines or size over 4MB
2. Try to type something in the beginning left corner of a line and then quickly try to delete it

If needed i will provide one of the files having the issue.

Here's a [screenshot](https://i.imgur.com/dD0B9vw.png) (sorry for my lack of talent in paint :) ).

**Comment by MetaChuh** [comment]
please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins if you update from version 7.5.9 or below.
if your issue still persists, and it is still of relevance, please feel free to file a new issue as easy to understand and reproducible as possible.

thank you for your help and best regards.

-----
```
general notes:

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).
please file an issue as easy to understand and reproducible as possible.

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
(no extra account is needed, just use your github account to sign in)
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)
