### ISSUE TITLE
Installed plugin manager update - now no plugins show at all

### ISSUE THREAD

**Issue by wwendorf** [notepad-plus-plus/notepad-plus-plus#4837]
### Description of the Issue
Plugin manager warned me that it was out of date, and I should update.  I did so, and then nothing showed up in the plugin manager list afterwards.

**Comment by sharuzzaman** [comment]
Verified the issue. Now already installed plugin also shown as:

Unknown plugin - please let us know about this plugin on the forums
Stability:

**Comment by sharuzzaman** [comment]
I can see that Plugin Manager is now working properly. @wwendorf can you verify? if it is OK, we should close this ticket

**Comment by wwendorf** [comment]
I will check tomorrow. Thank you!

**Comment by wwendorf** [comment]
Issue seems to be resolved!

Thanks!
Wade
