### ISSUE TITLE
Good features to have

### ISSUE THREAD

**Issue by prog20901** [notepad-plus-plus/notepad-plus-plus#4843]
### Description of the Issue

Indexing is one of the feature which doesn't exist in Notepad++. We are forced to use multiple tools one for indexing, one for searching and one for other usage. It would be great if Notepad++ comes by a configurable option to index the file contents in a folder and perform a search faster. 

Let's say a folder has 50,000 or 1k files and it takes more time to search for a text. It would be better if there is an option to index and do a search.

Working in a project usually has same files to search. If at all the user can be provided to re-index the folder if required it again. Also, following options would be awesome,

type-ahead search,
number of hits
auto-complete suggestion

### Steps to Reproduce the Issue

1. Select a folder which has 50,000 or 1k txt files
2. Type a searcheable text or word
3. Search

### Expected Behavior

Getting results very fast and Options are available like type-ahead, auto-completion etc.,

### Actual Behavior

Time delay and Options are available like type-ahnot ead, auto-completion etc.,

**Comment by sasumner** [comment]
The philosophy seems to be that if you want really sophisticated searching, turn to another tool.  However, @jkathir , nothing stops you (or others with some interest) from working on this and submitting a pull request.

**Comment by chcg** [comment]
@prog20901 See https://github.com/pnedev/nppgtags, maybe this plugin already provides you parts of your needed functionality.

**Comment by prog20901** [comment]
I already seen this and don't find the dll file. please attach the same to
the project

**Comment by cmeriaux** [comment]
@prog20901  checkout the release tab 
https://github.com/pnedev/nppgtags/releases 

or direct link to assets :
https://github.com/pnedev/nppgtags/releases/download/v4.4.1/NppGTags_v4.4.1_X64.zip
 https://github.com/pnedev/nppgtags/releases/download/v4.4.1/NppGTags_v4.4.1_x86.zip

**Comment by prog20901** [comment]
I got the files..Thanks a lot..However don't know the next steps.

Could u pls help me or guide me with the screenshots?

**Comment by sasumner** [comment]
@prog20901 This really isn't a hand-holding forum for plugin installation.  @cmeriaux Is there any reason you didn't direct @prog20901 to just install this via plugin mgr?

**Comment by chcg** [comment]
@prog20901 Did you read https://github.com/pnedev/nppgtags on installation and usage?
