### ISSUE TITLE
[FEAT] Parse GCC logs for warnings and errors

### ISSUE THREAD

**Issue by Kochise** [notepad-plus-plus/notepad-plus-plus#4846]
Hi, coding like a monkey (Notepad++, make, gdb) I'd like to know if there is a possibility to parse a gcc output, find the warnings/errors and open a 'Find result' window with all the files/lines displayed on the said errors, perhaps even open them all if not already open in my favorite editor. That would save my life.

i.e. : e:\app_main_tst.c:623:40: warning: taking address of temporary [-fpermissive]

Alternative :

Alt+O, paste a path\file:line, open file, do an automatic Ctrl+G on line

i.e. : e:\app_main_tst.c:623

**Comment by sasumner** [comment]
Suggest seeing NppExec plugin...if that works for you please close this issue.

**Comment by sasumner** [comment]
Closing due to age and lack of response.
