### ISSUE TITLE
Suppress reload dialog when monitoring is enabled

### ISSUE THREAD

**Issue by dougbreaux** [notepad-plus-plus/notepad-plus-plus#4847]
### Description of the Issue

Sometimes - it appears to be maybe when I have more than one file monitored at the same time - I get regular reload dialogs when the monitored files change. Sometimes - maybe when I have only one monitored - this doesn't occur. And clearly the desired behavior is to not see such dialogs when monitoring.

### Steps to Reproduce the Issue

1.  Monitor one or more files
2.  Have those files change externally

### Expected Behavior

Keep updating file with no reload dialogs appearing

### Actual Behavior

Reload dialogs appear frequently

### Debug Information

Notepad++ v7.5.8   (32-bit)
Build time : Jul 23 2018 - 02:03:53
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : ON
Local Conf mode : OFF
OS : Windows 10 (64-bit)
Plugins : NPPJSONViewer.dll XMLTools.dll DSpellCheck.dll mimeTools.dll NppConverter.dll NppExport.dll 

Pull request #4527 seems to be about the same thing, code there might be relevant.

**Comment by dinkumoil** [comment]
Can you confirm that the following setting is **NOT** checked while monitoring?

![grafik](https://user-images.githubusercontent.com/24699812/45509015-a968df80-b796-11e8-8740-b715a425b6f3.png)

**Comment by dougbreaux** [comment]
No, it's checked. I do want detection of non-monitored files. Or am I misunderstanding something?

**Comment by dinkumoil** [comment]
If the setting above is turned off you won't get reload confirmation dialogs anymore, this is my experience. But I agree that this behaviour isn't comfortable and should be changed. Maybe you should extend your report and include this fact.
