### ISSUE TITLE
Feature request: add the Find (ctrl+F) dialog to the context menu

### ISSUE THREAD

**Issue by jpanzgit** [notepad-plus-plus/notepad-plus-plus#4848]
Please add the find dialog to the context menu for a highlighted item. Currently I highlight and hit ctrl+f but it would nice to be able to do all of the searching with the mouse.

**Comment by sasumner** [comment]
@jpanzgit 

Edit contextMenu.xml and put this line in it, at a reasonable place:
`<Item MenuEntryName = "Search" MenuItemName = "Find..." >`

Restart Notepad++ and like magic a `Find...` entry appears in your right-click context menu.

If this meets your need, please close this issue.
