### ISSUE TITLE
Attempting to move a rectangular text selection generates garbage text

### ISSUE THREAD

**Issue by wrincewind** [notepad-plus-plus/notepad-plus-plus#4849]
[alt, shift, and up to select multiple lines, then ctrl+shift to move multiple lines. 

### Description of the Issue
If you use alt+shift+arrow keys to select a square of text (or multiple solid lines), then attempt to move that selection about with ctrl+shift+arrows, sections of text are either discarded or replaced with garbage. 

the command in question is SCI_LINEDOWNRECTEXTEND (and sci_line up/left/right rect extend, too)

### Steps to Reproduce the Issue
1. open any file in notepad++. (I've been using plain old .txt files)
2. select multiple rows/lines with alt+shift+up.
3. move the selection around with ctrl+shift+up
4. there will be a bunch of garbage in its place.

### Expected Behavior
i expected the multiple lines to be treated as a single segment and moved around like a single line would (either by the whole line(s) being selected as they are when you use shift+arrows, or by the segment being effectively 'sliced' and moved up into the gap above or below)

### Actual Behavior
the section was replaced with various random charactrs, including NUL and some other odd digits, for example 
 #Dݿ gƾ\             t        [��t��ٶI\     Ë>\   赼蠈t    `t                           

### Debug Information

Notepad++ v7.5.8   (32-bit)
Build time : Jul 23 2018 - 02:03:53
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : ON
Local Conf mode : OFF
OS : Windows 7 (32-bit)
Plugins : autosave2.dll NppCCompletionPlugin.dll NppFTP.dll PluginManager.dll sql.dll zoomdisabler.dll DSpellCheck.dll mimeTools.dll NppConverter.dll NppExport.dll 

Example screenshot: 
![image](https://user-images.githubusercontent.com/1457878/45498102-457ff000-b771-11e8-806c-b9dbe613384f.png)

**Comment by sasumner** [comment]
Without Alt in the keycombination, you are not selecting a rectangular block of text.  Unless your lines happen to all have the same length...so it appears rectangular, but it is not a true rectangular block.

**Comment by dail8859** [comment]
The text corruption is fixed in Notepad v7.7 since it upgraded to a new version of Scintilla.

*Please note*: The fix does not give you the expected results of moving the lines (it simply just doesn't work with a rectangular selection)...this is something that would need addressed by the Scintilla project.
