### ISSUE TITLE
NPP Updater crashes when a transition from 7.5.7 to 7.5.8 is made

### ISSUE THREAD

**Issue by dvdvideo1234** [notepad-plus-plus/notepad-plus-plus#4851]
### Description of the Issue
Error "Cannot open the file for writing" when NPP is updated via the updater

### Steps to Reproduce the Issue
1. Install NPP <= v7.5.8
2. Install the update using the updater

### Expected Behavior
Updater to do its job and I must not have to download the update manually

### Actual Behavior

![image](https://user-images.githubusercontent.com/9112662/45540234-9268d280-b814-11e8-8eee-08bbe9d59ed1.png)

![image](https://user-images.githubusercontent.com/9112662/45539647-07d3a380-b813-11e8-85d2-070066d59de3.png)

### Debug Information

![image](https://user-images.githubusercontent.com/9112662/45539685-233eae80-b813-11e8-85b4-7760b9b42e23.png)

**Comment by dvdvideo1234** [comment]
Turns out when NPP is closed, `GUP.exe` continues to run for some reason, and you have to manually stop it.

**Comment by MetaChuh** [comment]
please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins if you update from version 7.5.9 or below.
if your issue still persists, and it is still of relevance, please feel free to file a new issue as easy to understand and reproducible as possible.

thank you for your help and best regards.

**Comment by pwnoobz** [comment]
Exactly the same issue here. I have this problem for a long time. Every time I update it says it has a problem with GUP.exe.
