### ISSUE TITLE
No Way to Register at Notepad++ Community and HTML Tag Editor Dialog

### ISSUE THREAD

**Issue by MarkRH** [notepad-plus-plus/notepad-plus-plus#4854]
I was trying to register at https://notepad-plus-plus.org/community/ but there seems to be no way to register and trying the Twitter thing fails. This seems to be the only other place to ask a question.

Anyway, is there some plugin that could pop up a dialog box to edit the attributes of a HTML Tag.  In an old program called Homesite, pressing F4 while on an `img` tag would bring up something like: 

![image](https://user-images.githubusercontent.com/8035962/45577896-f6ef5600-b843-11e8-8d59-17b696d41a1f.png)

Just wondered if something like this was possible with Notepad++?

**Comment by dinkumoil** [comment]
You can't register for the community forum. Currently logging in is only possible with the credentials of a GitHub account. So, you need to sign up for a GitHub account.

**Comment by MarkRH** [comment]
Ah, that did work. Thanks.  I'll close this and ask this question in a separate thread.
