### ISSUE TITLE
Opening big .xml files takes too long

### ISSUE THREAD

**Issue by h4uja2** [notepad-plus-plus/notepad-plus-plus#4857]
### Description of the Issue

Opening big .xml files (10mb) takes more than a minute.

However, if I change file extension to .txt and remove the very first line (`<?xml version="1.0" encoding="UTF-8"?>`) it opens instantly. And if I manually enable xml syntax highlighting it doesn't freeze and works perfectly.

### Debug Information

Notepad++ v7.5.7   (64-bit)
Build time : Jun 29 2018 - 00:53:58
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : ON
Local Conf mode : OFF
OS : Windows 7 (64-bit)
Plugins : none

**Comment by h4uja2** [comment]
Fixed by disabling "Function List"

**Comment by sasumner** [comment]
Processing takes time.  There is nothing to "fix".
