### ISSUE TITLE
Replace CreateThread() with _beginthreadex()?

### ISSUE THREAD

**Issue by pnedev** [notepad-plus-plus/notepad-plus-plus#486]
Hi,

According to MSDN documentation (https://msdn.microsoft.com/en-us/library/windows/desktop/ms682453(v=vs.85).aspx) **_beginthreadex()** should be used instead of **CreateThread()** when the thread function uses the C run-time library.

In *Notepad_plus.cpp* **threadTextTroller()**, **threadTextPlayer()** and **backupDocument()** are thread functions and all of them call CRT APIs so their threads should be created with **_beginthreadex()** instead of **CreateThread()**.

BR,
Pavel

**Comment by milipili** [comment]
n++ will use libyuni in the near future.

**Comment by ariccio** [comment]
> n++ will use libyuni in the near future.

For clarity, what's the proper way to do this in `libyuni`? (also: why not just use standard C++?)

**Comment by ariccio** [comment]
I hope I'm not being pushy... Why use `libyuni`, and not standard C++?
