### ISSUE TITLE
Color scheme "Mariana" for Notepad++

### ISSUE THREAD

**Issue by kanlukasz** [notepad-plus-plus/notepad-plus-plus#4862]
_I tried made this post on N++ forum but there i have a error "You do not have enough privileges for this action", so i make this here_

Hello everyone.

I looking for color syntax scheme that look exactly like a "Mariana" scheme in Sublime Text (as much as possible)

This blue background and all this delicate colors balance is great, espaccialy for people with astigmatism like me

Examples:
![Alt text](https://images91.fotosik.pl/41/7b4438961b3537dfgen.png)
![Alt text](https://i2.wp.com/omgfoss.com/wp-content/uploads/2017/12/linux.png?fit=1280%2C748)

I work with html, css, php, js, bash, sql, xml, json
Does anyone seen something like this one?

**Comment by Codextor** [comment]
Hi @kanlukasz 
I have a theme which looks similar to Mariana, but not exactly like it. [Material Theme for Notepad++](https://github.com/Codextor/npp-material-theme)
Have a look at it. You might like it.

**Comment by Codextor** [comment]
Hi @kanlukasz 
I went ahead and ported the Mariana theme to Notepad++.
You can find it [here](https://github.com/Codextor/npp-mariana-theme)
If you give it a try, do provide feedback.

**Comment by kanlukasz** [comment]
This is awesome and looks pretty. Thank you, i will testing that asap

**Comment by kanlukasz** [comment]
This is awesome and looks pretty. Thank you, i will testing that asap
