### ISSUE TITLE
Feature Request: Add support for tabSettings in UDL

### ISSUE THREAD

**Issue by ameer1234567890** [notepad-plus-plus/notepad-plus-plus#4864]
Currently, there is no way to set an indentation style (tab setting) for User Defined Languages (UDL), except for changing the default indentation style, which would affect all other languages forcing the user to set manual indentation styles for any other languages used.

This is a request to add support for `tabSettings` key in UDL.
This would be specifically useful since Notepad++ does not have language support for some languages like `golang`.

Further discussions of this can be found below:
* https://notepad-plus-plus.org/community/topic/12036/save-tab-size-for-a-specific-language-different-from-default-value/10
* https://stackoverflow.com/questions/6051919/how-do-you-setup-tab-settings-for-user-defined-file-types-in-notepad

**Comment by MetaChuh** [comment]
unfortunately we currently don't have time to do that, hence also the delayed reply.
thanks for understanding and best regards.
