### ISSUE TITLE
Any way to monitor Npp/Scintilla's WM_NOTIFY messages from a separate process?

### ISSUE THREAD

**Issue by Vismund-Cygnus** [notepad-plus-plus/notepad-plus-plus#4865]
I've been writing a bit of a Npp wrapper/helper with AutoHotkey (that being the only programming skills I have) and have figured out most of the NPPM_* messages, but it seems like a bit of a pain to be able to check things like WM_NOTIFY messages. I'd have to do a dll injection it seems. I wouldn't even know where to begin with writing an actual Npp plugin.

So I was wondering if there are any Npp messages or other dll functions I could maybe call from an external process in order to receive these WM_NOTIFY messages. I was trying not to rely on any extra software besides my AHK script, but I suppose if there were a Npp plugin that I could simply have send out a WM_COPYDATA message to my script on any WM_NOTIFY would be great. I don't particularly need to stop/change the events while they're happening - just knowing that they're happening would be very cool.

(Also - not Npp specific, but I'm also wondering the same thing about Scintilla. I know Scintilla has a few more messages directed at interfacing with it, so I just wanted to make sure I'm not missing anything obvious to make it easier to catch notifications from an external process/thread.)

**Comment by sasumner** [comment]
That's not an "issue"...that's a question.  Why don't you just copy and paste that over to here and see if you get some responses:  https://notepad-plus-plus.org/community/

If that suggestion is acceptable, please close this issue to help keep down the clutter.

BTW, anybody that has done the programming that you've described above shouldn't have any trouble working on a real plugin, IMO.  :-)
