### ISSUE TITLE
Bug in Coloring in SQL Code 

### ISSUE THREAD

**Issue by leefordjudes** [notepad-plus-plus/notepad-plus-plus#4866]
### Description of the Issue
i used notepad ++ for writing sql stored procedure, 
Sample SP
=============
USE [TempDb]
Go
CREATE PROCEDURE [dbo].[Test]
@GID INT
,@Path VARCHAR(MAX)
,@Level INT
BEGIN
	SET NOCOUNT ON;
	
	IF @GID = 1 
			BEGIN
			   SET @Path = '$\' 
			   SET @Level = 1 
			END
		ELSE 
			BEGIN 
				SET @Path = (SELECT Path FROM [FilePaths] WITH (NOLOCK) WHERE GID = @GID)
				SET @Path = @Path + CONVERT(VARCHAR(10), @GID) + '\'
				SET @Level =(SELECT Level FROM [FilePaths] WITH (NOLOCK) WHERE GID=@GID)
				SET @Level = @Level + 1
			END
END
=====================

in the above code, when notepad++ encounters 2nd single quote(')  =>  SET @Path = '$\' 
it treats with same color; that is color of string.
see that image.
I used VS2015-Dark as style theme & it shows the same in default color scheme also.

![image](https://user-images.githubusercontent.com/13608248/45914981-89a67b00-be6a-11e8-83ec-f8de15a89f4e.png)

![image](https://user-images.githubusercontent.com/13608248/45915006-eefa6c00-be6a-11e8-92f0-62e46983787e.png)
![image](https://user-images.githubusercontent.com/13608248/45915034-57494d80-be6b-11e8-8cef-af149fec49c9.png)

thank you

### Steps to Reproduce the Issue

1.  simple paste the above code in npp and store it as file.sql 
2. use vs2015-dark color scheme
3.

**Comment by dinkumoil** [comment]
As a workaround you could use the user defined language highlighter for T-SQL.

1. Download it [on this site](http://docs.notepad-plus-plus.org/index.php?title=User_Defined_Language_Files). Search for `T-SQL (MS Server 2008R2)`, right-click the link and choose "Save as..." or something like that (depends on your browser).
2. Now you have to import the file into Notepad++ via `menu "Language" -> Define your language...` (UDL dialog pops up)` -> Button "Import..."`.
3. Customize the highlighter to your needs via the UDL dialog. I personally don't like the underlined text style provided by the default configuration. **Note:** Switching highlighting and background colors via themes doesn't work with user defined languages, you have to change the colors via the UDL dialog too.

**Comment by dail8859** [comment]
Turn off `Settings > Preferences > MISC. > Treat backslash as escape character for SQL`

---

![image](https://user-images.githubusercontent.com/3694843/58262687-b89e2500-7d48-11e9-8b8d-f3809346f67f.png)
