### ISSUE TITLE
Swedish translation of "Hide menu bar" too long to fit UI

### ISSUE THREAD

**Issue by bolligerm** [notepad-plus-plus/notepad-plus-plus#4868]
### Description of the Issue

Swedish translation of "Hide menu bar" is too long to fit UI

### Steps to Reproduce the Issue

1.  Settings > Preferences > General
2.  Select Localization: "Svenska" (Swedish)
3.  Note how the text on the bottom right (for "Hide menu bar (use Alt or F10 key to toggle)") is too long to fit the space allocated to it in the UI.

### Expected Behavior

Expected a perfect-looking UI.

### Actual Behavior

Text gets word-wrapped and its top and bottom parts get cut away.
![swedish text too long](https://user-images.githubusercontent.com/43510923/45924917-02154680-bf14-11e8-9678-777500997a96.png)

**Comment by ordtrogen** [comment]
Very well written bug report! It looks like it has been resolved though:

![image](https://user-images.githubusercontent.com/15184875/55030315-6e304e80-500c-11e9-95b3-8565a9236d21.png)

**Comment by ordtrogen** [comment]
Maybe the word "använd" is unnecessary. What else should you do with the Alt or F10 key? :-)

**Comment by chcg** [comment]
@bolligerm @ordtrogen With which versions of N++ are you working?

Seems the fix was done with PR #4777

**Comment by ordtrogen** [comment]
I'm still on 7.6.3

**Comment by ArkadiuszMichalski** [comment]
@donho This was fixed and can be close. In 7.9 we have what we seen in @ordtrogen picture.
