### ISSUE TITLE
[SFTP] Connection failed : kex error : no match for method server host key algo: server [ssh-rsa,rsa-sha2-512,rsa-sha2-256], client [ecdsa-sha2-nistp256] 

### ISSUE THREAD

**Issue by jr3074** [notepad-plus-plus/notepad-plus-plus#4870]
I get this error "[SFTP] Connection failed : kex error : no match for method server host key algo: server [ssh-rsa,rsa-sha2-512,rsa-sha2-256], client [ecdsa-sha2-nistp256] "
I want to connect  ubuntu 18.04 but failed.

**Comment by sasumner** [comment]
I don't use it, but the FTP plugin is not part of Notepad++, so I think a better place to report an issue would be on the issues list for the FTP plugin?

**Comment by chcg** [comment]
@jr3074 The correct place is https://github.com/ashkulz/NppFTP/issues. Seems similar to e.g. https://github.com/ashkulz/NppFTP/issues/164

**Comment by chcg** [comment]
@jr3074  You may want to test current release https://github.com/ashkulz/NppFTP/releases/tag/v0.28.0 which contains updated libssh version 0.8.6 with support for additional algorithms.
