### ISSUE TITLE
Opening large XML files on startup hangs app

### ISSUE THREAD

**Issue by Lokiare** [notepad-plus-plus/notepad-plus-plus#4871]
### Description of the Issue

When I close notepad++ it remembers the files that are open. When I re-open it, it tries to open those files. One of those files is a very large XML file (over 7MB). It hangs for at least 10 minutes (I remove the file from the startup list after that).

### Steps to Reproduce the Issue

1. Open XML file over 7MB in size.
2. Close Notepad++.
3. Re-open Notepad++.

### Expected Behavior

I expected the UI and the program to fully load before trying to load the files so that I can manually close the file that has a problem loading without having to go into the npp startup files.

### Actual Behavior

The program hangs for 10+ minutes (I close at that point).

### Debug Information

Can't access the menu, the program hangs.
![screenshot 2018-09-23 11 28 56](https://user-images.githubusercontent.com/1618213/45930289-df8b2980-bf23-11e8-858e-99d02013b178.png)

**Comment by ccammack** [comment]
I'm making some assumptions here, but would you try a quick test?

Temporarily move or rename the XML file so Notepad++ can open without hanging, then open the XML file again, press Alt-Shift-0 to unfold the contents, and restart Notepad++ to see if it still hangs.

For me, Notepad++ can reopen a 5MB XML file instantly as long as it wasn't folded when I closed Notepad++, but even a 1MB XML file takes over 15 minutes to reopen if it was folded when I closed the program.

Another thing that might help is to keep a small dummy file open as the leftmost tab, and open the XML file in a rightward tab. Notepad++ appears to save the folding state for the first tab only, so if you keep the XML file to the right, it seems to speed things up some.
