### ISSUE TITLE
'Save As' doesn't add file extension

### ISSUE THREAD

**Issue by quantuumsnot** [notepad-plus-plus/notepad-plus-plus#4876]
### Steps to Reproduce the Issue
1.  Open a new tab
2.  Paste some code, ie javascript
3.  Ctrl+S and in the save window pick 'save as type -> JavaScript file (*.js)'
4. Hit 'Save' button
5. File is saved without an extension, ie test instead of test.js

### Expected Behavior
Files to be saved with their extension

### Actual Behavior
Files are not saved with their extension

### Debug Information
Notepad++ v7.5.4   (64-bit)
Build time : Jan  1 2018 - 01:50:29
Path : C:\npp\notepad++.exe
Admin mode : ON
Local Conf mode : ON
OS : Windows 7 (64-bit)
Plugins : ComparePlugin.dll CsvQuery.dll DSpellCheck.dll mimeTools.dll NppConverter.dll NppSnippets.dll PluginManager.dll

**Comment by sasumner** [comment]
What is your setting for Preferences -> Default Directory -> Use new style dialog...   ?

**Comment by quantuumsnot** [comment]
Checked

**Comment by sasumner** [comment]
FWIW, if you uncheck that option, you get the behavior you desire, although at the expense of the other "new style dialog" features, I suppose.

**Comment by quantuumsnot** [comment]
Yep, but this is retarded in the sense of UX - an option that has more rights than the user manually choosing his file extension

**Comment by sekkuar** [comment]
Unchecking "use new style" does not override user input for file extensions.
The save dialog is pretty smart.

If you type only a filename without extension ("javascript") it will automatically add whatever extension is selected under "type" below the filename (it also automatically selects the correct type based on the "language" chosen previously in the application, or defaults to .txt if none was selected).
However if you type the complete filename and type ("javascript,js") it will save the file with your specified extension, regardless of what is the "type" or "language" selected (it also updates the editor to select the new language for syntax highlight).

**Comment by sasumner** [comment]
@sekkuar I think what you are saying is, "just type the darn extension yourself".  And I fully agree with that.  :-)

**Comment by quantuumsnot** [comment]
@sasumner Yep, every f.kin time

**Comment by satovey** [comment]
I am using Notepad++ 7.6.6 x64 and I was having this same behavior until I unchecked the new style parameter.
Thanks for the solution.

I may have picked up on this if the text in the preference panel was larger and I didn't need to pick up a magnifying glass to read it. But, despite the fact that I created a Windows Theme with a larger font size, Microsoft only allows the font to be adjusted on certain areas and not all, so the font size in some programs are still small. 

But I have to ask: why would you want to save the file without the file extension?
Is there a group of geeks claiming that the use of file extensions is discriminatory and biased?

Typically, the operating system determines a files type based on the file extension and that extension is associated with a given program which then opens any file with that extension.

I am highly suspect of those that clamor for some new way of doing things at the expense of everyone and everything that has gone before including the good and the excellent.

Regardless, I am of the opinion that the behavior is incorrect.
Even with new style checked, if a user types in a file name then selects a file type in the drop down box, the extension should be added to the file name. There is no logic behind not adding the .js extension to a JavaScript file given the fact that the file will typically be used on a web server. In addition, Notepad++ uses that extension to determine which language is being used and applies the applicable coding style and debugging solutions. So, not adding a file extension is counter productive when it comes to the layout style of the text within Notepad++.

That's all I'm going to say on this.

**Comment by sasumner** [comment]
>...if a user types in a file name then selects a file type in the drop down box, the extension should be added to the file name.

The file extension filter is only there to allow you to see existing names of files with a given extension, in the off chance that the name you are about to provide for your new file is already in use.  Sure it will also tell you that it is in use if you actually try to name it the same, but this can head that off.  IT ISN'T THERE TO PUT AN EXTENSION ON YOUR FILE.  The first time you save a file, you have to give it a complete name, including the extension.

>That's all I'm going to say on this

Let's see. :)
