### ISSUE TITLE
Impossible preview in browser of a non-saved HTML file

### ISSUE THREAD

**Issue by acs-ferreira** [notepad-plus-plus/notepad-plus-plus#4879]
### Description of the Issue
Create a new file, paste some HTML in it, try to preview it in browser (Firefox)

### Steps to Reproduce the Issue
1. Open Notepad++
2. Paste some HTML
3. Go to Run > Launch in Firefox

### Expected Behavior
File is executed in browser, after been saved in TEMP

### Actual Behavior
Firefox trows an error.

2 options:
- Save file in TEMP and execute it,
- Or disable execution if file is not saved yet.

**Comment by sasumner** [comment]
Option #3:  User saves the file with proper extension, then launches in browser.  :-)
(That's the intended use-case for the "launch in browser" commands)

**Comment by acs-ferreira** [comment]
The command shouldn't then be available if the conditions aren't met IMO.

**Comment by sasumner** [comment]
So these commands are user-buildable.  The browser launch ones are provided with Notepad++ as examples of what you can do with the Run menu (for example, not everyone will have Chrome, but yet that command is there as an example, and isn't greyed out if one doesn't have Chrome).

Perhaps if one uses $(FULL_CURRENT_PATH) etal. in the command definition, it could be a signal that the command should be greyed out when the file has NO path on disk...hmmm...

**Comment by MetaChuh** [comment]
browser view at `view > view current file in > browser name` are automatically disabled and greyed out, on the newest versions of notepad++, if a file is not saved.

please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins if you update from version 7.5.9 or below.

alternatively use the preview html plugin which you can download via the built in `plugins > plugins admin` menu.
this plugin will live preview your html files without saving.

thank you for your help and best regards.

-----
```
general notes:

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).
please file an issue as easy to understand and reproducible as possible.

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
(no extra account is needed, just use your github account to sign in)
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)

**Comment by sdudnic** [comment]
still an issue in 2020... preview plugin does not preview the unregistered files....

**Comment by sasumner** [comment]
@sdudnic Not really an issue.  Just save the file.

**Comment by sdudnic** [comment]
> Not really an issue. Just save the file.

if I save the file, I don't need Notepad++, I have Chrome.
Imagine a situation, I have in clipboard a HTML node I took from somewhere, I just need a preview to copy the displayed text (dusplayed text, not HTML code). I paste it in Notepad++, preview, copied the text, and its all... If is to save to harddisk, so, the Notepad++ role to save a file is not necessary...

**Comment by sasumner** [comment]
For my purposes, I just keep a `%temp%\preview.html` file open among my active tabs.
Your needs/desires may be different.

**Comment by sdudnic** [comment]
> For my purposes, I just keep a `%temp%\preview.html` file open among my open tabs.
> Your needs/desires may be different.

I mean, you say _is not an issue_. I say, this is a problem. Surely I can save the file, but this would be another problem. My problem is that I can't preview **unsaved** files, and this is a problem.
