### ISSUE TITLE
Notepad++ Hangs when Moving File Tabs

### ISSUE THREAD

**Issue by simple-gifts** [notepad-plus-plus/notepad-plus-plus#4882]
### Description of the Issue
Hi, folks. I'm running Windows 10. Every few days, Notepad++ will hang when I move (rearrange) the top file tabs. The file name in the tab will become blank or filled with Chinese characters, then Notepad++ stops responding.

I typically have 3 or 4 sessions open, with perhaps 15 open files, and often drag-and-drop files from one session to another.

### Steps to Reproduce the Issue
Generally happens after running Notepad++ for several days.

### Expected Behavior
File tabs can be rearranged

### Actual Behavior
Occasionally Notepad++ crashes when rearranging tabs within one session. This problem has been occurring for several months.

### Debug Information
Notepad++ v7.5.8   (32-bit)
Build time : Jul 23 2018 - 02:03:53
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10 (64-bit)
Plugins : NppFTP.dll NppSnippets.dll PluginManager.dll DSpellCheck.dll mimeTools.dll NppConverter.dll NppExport.dll 

Thanks for your help. Notepad++ is a fantastic editor.

**Comment by dinkumoil** [comment]
May be related to #4885.

**Comment by MetaChuh** [comment]
please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins if you update from version 7.5.9 or below.
if your issue still persists, and it is still of relevance, please feel free to file a new issue as easy to understand and reproducible as possible.

thank you for your help and best regards.
