### ISSUE TITLE
File moved from one instance to another loses syntax coloring.

### ISSUE THREAD

**Issue by Moorelife** [notepad-plus-plus/notepad-plus-plus#4883]
### Description of the Issue

When a .h header file is moved from one instance of Notepad++ to another, then the file which was previously syntax colored suddenly loses that feature

### Steps to Reproduce the Issue

1. Open NPP with three files which are syntax colored (.h will do).
2. Move one to the desktop to create a new instance of NPP
3. Note this retains syntax coloring.
4. Now move another syntax colored file to the second instance
5. Note this file looses all syntax coloring.
6. Workaround: go to Language and set the correct language again. 

### Expected Behavior

I expect the moved file to always maintain syntax coloring, since the file has not changed type.

### Actual Behavior

Syntax coloring is lost.

### Debug Information

Notepad++ v7.5.8   (32-bit)
Build time : Jul 23 2018 - 02:03:53
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10 (64-bit)
Plugins : DSpellCheck.dll mimeTools.dll NppConverter.dll NppExport.dll

**Comment by 10manjunath** [comment]
Could you please elaborate step 2?
How do you create a new instance?

**Comment by Moorelife** [comment]
I basically create a new instance by dragging the tab of one of the open .h files, and dragging it onto my Windows desktop outside the Notepad++ window.

**Comment by jamesod-martin** [comment]
I've had this issue as well, and it seemed to start around the time you opened it.

**Comment by ArkadiuszMichalski** [comment]
@Moorelife @jamesod-martin
Can you confirm that this isue is still presents? I can't reproduce in NPP 7.9 RC.

**Comment by Moorelife** [comment]
This issue no longer appears on 7.9RC. I will 7.9RC installed for further testing in the coming weeks...   :-)

**Comment by Moorelife** [comment]
As far as I am concerned, this can be closed.
