### ISSUE TITLE
Incorrect behavior for "unindenting" a line of text

### ISSUE THREAD

**Issue by tommai78101** [notepad-plus-plus/notepad-plus-plus#4888]
### Description of the Issue

![gif](https://user-images.githubusercontent.com/6444116/46228193-4f881e00-c32f-11e8-8c01-b35f65b47148.gif)

As shown here, I inserted a few <kbd>Tab</kbd> characters, then used <kbd>Shift</kbd>+<kbd>Tab</kbd>.

I believed this is the correct behavior, because when "unindenting" the line, the line is already at the very beginning of the row.

![gif](https://user-images.githubusercontent.com/6444116/46228324-bad1f000-c32f-11e8-9ceb-5637ecc33a65.gif)

But if I insert tabs in the beginning of the row, then "unindent" from somewhere in the middle of the line of text, I should expect the entire line to start "unindenting" immediately, not when the cursor caret is next to the "indents" and start "unindenting" from there.

### Steps to Reproduce the Issue

1. Type anything, as shown in the GIFs.
2. Use only <kbd>Tab</kbd> and <kbd>Shift</kbd>+<kbd>Tab</kbd>.
3. Observe how "indentation" works between various instances of where the cursor caret position is at on the line of text.

### Expected Behavior

One single <kbd>Shift</kbd>+<kbd>Tab</kbd> hotkey should "unindent" the entire line immediately, when possible.

### Actual Behavior

One single <kbd>Shift</kbd>+<kbd>Tab</kbd> hotkey is not enough to "unindent" the entire line until the cursor caret is next to an "indent".

### Debug Information

Notepad++ v7.5.8   (64-bit)
Build time : Jul 23 2018 - 02:06:36
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10 (64-bit)
Plugins : DSpellCheck.dll mimeTools.dll NppConverter.dll

**Comment by sasumner** [comment]
So I'm fairly sure that this behavior is governed by Scintilla (the Scintilla demo app SciTE has the same behavior), and a quick search of the Scintilla configuration functions didn't show anything related to this.  

But I could be wrong on both counts.  :)

In the event I'm NOT wrong, you'd have to make this request of the Scintilla component (on THEIR issues/feature-request list), and then hope that Notepad++ updates the version of Scintilla that it is using (very infrequent) to pick up the change, and possibly have code changes of its own to implement for this.

**Comment by tommai78101** [comment]
> In the event I'm NOT wrong, you'd have to make this request of the Scintilla component (on THEIR issues/feature-request list), and then hope that Notepad++ updates the version of Scintilla that it is using (very infrequent) to pick up the change, and possibly have code changes of its own to implement for this.

I see. Well, when attempting to create a ticket, this prompt appears:

![](https://i.imgur.com/uMdYRWe.png)

So, I might as well just say, "Yeah, it's working as intended."

**Comment by MetaChuh** [comment]
unfortunately scintilla is an external project, so you will have to file your issue at the [<kbd>scintilla bug tracker</kbd>](https://sourceforge.net/p/scintilla/bugs/).

there is currently nothing we can do about this experience, at the notepad++ part.
we apologise for that.
