### ISSUE TITLE
Windows: File-Open Dialog: Unix-Pathdelimiter '/' is invalid in NotepadPP but windows supports it

### ISSUE THREAD

**Issue by mschwehl** [notepad-plus-plus/notepad-plus-plus#4890]
### Description of the Issue
Windows-Path with '/' instead of '\\' not possible

### Steps to Reproduce the Issue

1. file open
2. type path c:/temp
3. Popup-Dialog with error

### Expected Behavior
Windows can handle / in path as well

### Actual Behavior
popup-Dialog with error

**Comment by sasumner** [comment]
This depends upon the setting for Preferences->Default Directory->Use new style dialog...

I'm not sure why we can't have it all at the same time (e.g. "new style" and Unix style paths).  :-(

**Comment by MetaChuh** [comment]
please adapt `settings > preferences > default directory > use new style dialog` to your requirements.
disable it to use unix style path syntax.

many thanks and best regards.
