### ISSUE TITLE
NotePad++ close when try disable spell check using theme VS2015

### ISSUE THREAD

**Issue by guielebo** [notepad-plus-plus/notepad-plus-plus#4891]
### NotePad++ close when try disable spell check using this theme:
[Theme Link](https://github.com/jpdillingham/VS2015-Dark-Npp/blob/master/VS2015-Dark.xml)

### Steps to Reproduce the Issue

1. Config this theme.
2. Click disable spell check

### Expected Behavior

NotePadd++ unexpected close

**Comment by sthag** [comment]
I also cannot diable spell check.
But I do not use the mentioned theme.

I made a basic installation from an Administrator account.
Everythings fine under this account and spell check is disabled.
If I run Notepad++ from another user account, spell check is enabled and Notepad++ just closes when I try to disable it.
If I run Notepad++ as Administrator, from the user account, spell check is again also disabled.

**Comment by chcg** [comment]
@guielebo @sthag N++ comes with a quite old version of Dspell out of the box. Could you check the behaviour with current release:
https://github.com/Predelnik/DSpellCheck/releases/tag/v1.4.6

**Comment by guielebo** [comment]
@chcg great 🥇 

I update NotePad++ and solve this issue.

Tks.
