### ISSUE TITLE
Feature Request: Add the Tomorrow Theme

### ISSUE THREAD

**Issue by zag2me** [notepad-plus-plus/notepad-plus-plus#4894]
### Feature Request
A while ago I wrote a [blog](https://zag4me.wordpress.com/2015/06/02/setting-up-notepad-to-look-like-codeacademy/) on how to make notepad++ to have the same visual style as the codeacademy website (I work in education and it was important for the students to have a similar look for their code editor). I would like to request the inclusion of the 'tomorrow_night' style in the default install so we don't always have to mess around with XML files all the time.

https://github.com/chriskempson/tomorrow-theme

**Preview**
![helloworld](https://user-images.githubusercontent.com/1050512/46404552-72368000-c6fd-11e8-8b39-a0d32ece6fec.png)

**Comment by ArkadiuszMichalski** [comment]
@sasumner Probably can be close, these theme was drop in 2015.
