### ISSUE TITLE
{FunctionList request] Split functionList.xml into multifile in functionList Folder

### ISSUE THREAD

**Issue by DenisFR** [notepad-plus-plus/notepad-plus-plus#4896]
Hello,

As explain in Title, I wish to have one file by language in the same folder.
So it will be more easy to change or update them, copy/past from different sources or get them in git repo, etc.

**Comment by jay1109** [comment]
It would be great if that is possible.

**Comment by lifenjoiner** [comment]
Can't agree more!
Like `autoCompletion` and `userDefineLangs`, we need user defined `functionList` stored standalone. That is friendly for upgrading. Or it could be overwritten easily.

**Comment by ArkadiuszMichalski** [comment]
@donho 
Have you considier (even in the future) to break this one single file into separate files for each language. If for some reason not then maybe close this bug?

**Comment by donho** [comment]
@ArkadiuszMichalski 
Yes, indeed.
I will see what I can do about it.

**Comment by ArkadiuszMichalski** [comment]
Correlation with https://github.com/notepad-plus-plus/notepad-plus-plus/issues/3769.

**Comment by donho** [comment]
Could anyone confirm the file extension of User Defined Language still working in Function List?

For example:
```
<association id= "krl_function"   ext=".src"/>
<association id= "krl_function"   ext=".sub"/>
```
in
https://github.com/notepad-plus-plus/notepad-plus-plus/blob/master/PowerEditor/src/functionList.xml#L101

**Comment by ArkadiuszMichalski** [comment]
Works for me:

![image](https://user-images.githubusercontent.com/2730894/95563274-7c429600-0a1d-11eb-94a3-772a14949af4.png)

**Comment by donho** [comment]
@ArkadiuszMichalski If you remove both line, it works as well.
```
<association id= "krl_function"   ext=".src"/>
<association id= "krl_function"   ext=".sub"/>
```

**Comment by ArkadiuszMichalski** [comment]
@donho Yes, without this line also works. Looks like rules from UDL are taken:
```
<UserLang name="KRL" ext="src dat sub" udlVersion="2.1">
```

When bring back 2 above and change:
```
UserLang name="KRL" ext="" udlVersion="2.1">
```
also works but I need manually select KRL and refresh list.

**Comment by donho** [comment]
@ArkadiuszMichalski 
The picture you provided is already applied to the UDL:
![image](https://user-images.githubusercontent.com/90293/95626414-82b32b00-0a7a-11eb-940e-e720d183cd2b.png)

**Comment by ArkadiuszMichalski** [comment]
I was wrong, I misunderstood the question, extensions in the `functionList.xml` for UDL do not work. But I saw on the forum that this has already been established.

**Comment by donho** [comment]
The extensions in the functionList.xml for UDL did work I guess (I don't really remember this feature). But now I reconsider the interface (xml file), it's redundant so I will remove it.

**Comment by MAPJe71** [comment]
@donho IMO it's not redundant, defining an (dummy) UDL is used as a workaround to solve the problem with FL ext.

**Comment by ArkadiuszMichalski** [comment]
@MAPJe71 
But setting extension as here https://github.com/notepad-plus-plus/notepad-plus-plus/issues/298 has any sense? Even if it work for opened file, what if we change language to other (get new FL results), and how back to our parsers again (if we can't choose it
)?

Setting extensions for in-build language can be done in other file. Setting extensions in parsers is needed?

**Comment by MAPJe71** [comment]
@ArkadiuszMichalski 
Associating a file extension(s) with a FunctionList parser make sense to me.
Not having that option means an UDL has to be defined for _every_ non-in-build-language FL parser.
Every UDL ends up in the Language menu which can't be compacted for UDL's resulting in a very very long menu when having a lot of parsers.

**Comment by ArkadiuszMichalski** [comment]
Well, this could be an argument. Regardless of the extensions support, a compact menu for UDL (even one entry) would be advisable (I have to find out if such a bug exists).

**Comment by donho** [comment]
The new interface is cleaner and easier to use:
https://github.com/notepad-plus-plus/notepad-plus-plus/pull/8991/files#diff-4301281aea7275c6a6e921a58019ba4c

Let's see if the ext support is really needed then we will consider it?

**Comment by vlakoff** [comment]
Refs the subsequent #9134, which tweaked the loading behaviour.
