### ISSUE TITLE
Color scheme dictates paper prints.

### ISSUE THREAD

**Issue by ArunMKumar** [notepad-plus-plus/notepad-plus-plus#4900]
### Description of the Issue
I use the dark color scheme (white on black background), activated from the style configurator.

### Steps to Reproduce the Issue
1.  Settings -> Style Configurator
2.  change the color scheme to blackboard
3.  Text comes up in white background black.
4. Take a print out of the text.
5. The sheet is blank.
6. Change the color scheme to default.
7. Take a paper print.
8. Text appears.

### Expected Behavior
Despite the color scheme which was to aid in long hours at the monitor, the print was expected to be black as this behavior is more in line with a word processor than a code editor.

### Actual Behavior
Color schemes dictate the color seen on prints, in case of B&W prints, all text (comments, variables or otherwise) appearing on screen do not get printed.

This is also applicable when the text is printed to a PDF.

### Debug Information
Observed on v7.5

**Comment by ArunMKumar** [comment]
already resolved, sorry for the inconvenience.

**Comment by dinkumoil** [comment]
If it's resolved please close this issue.
