### ISSUE TITLE
Feature request: Better looking lesser contrast [CR] [LF] line endings

### ISSUE THREAD

**Issue by andry81** [notepad-plus-plus/notepad-plus-plus#4902]
Current look and feel of the line ending are a bit of ugly and annoying, because of too much contrast with the ordinal text.

I am always using the show line endings and white print characters to control space vs. tabulation and unix/windows line endings characters along with the ordinal text. And will be much useful to reduce contrast of control character in case if you are reading not a binary file.

Take a look at the Araxis Merge application and it's control character representation for a good example.

**Comment by andry81** [comment]
The feature request at scintilla tracker: https://sourceforge.net/p/scintilla/bugs/2050/

**Comment by sasumner** [comment]
@andry81 Did you search on the Scintilla tracker site for this type of request, either currently open or closed with refusal?  [I'm remembering now that it has been brought up before and denied (in a strong way) by the lead author of Scintilla.]

**Comment by andry81** [comment]
If you have any links to it, then add it here.

**Comment by sasumner** [comment]
@andry81 If I had any, I certainly would have.

**Comment by MetaChuh** [comment]
@andry81 

as this is controlled by scintilla, we can unfortunately not do anything about that, until it is eventually integrated at the scintilla project.

many thanks for filing your issue at the scintilla feature tracker.
best regards.
