### ISSUE TITLE
Plugin development only for 32-bit notepad++?!

### ISSUE THREAD

**Issue by aglaiawong** [notepad-plus-plus/notepad-plus-plus#4903]
### Which platform does notepad++ plugin support? 
When I run the demo from: http://notepad-plus.sourceforge.net/commun/pluginDemoTemplate/NppPluginTemplate.zip
And tried to compile it into dll, which is then transferred under the plugin folder, the following error msg occurs: "cannot load 32-bit plugin NppPluginDemo_DebugA.dll is not compatible with the current version of Notepad++"
So I'm wondering if currently notepad only support 32-bit plugin development? How can I develop a plugin on Win10 in 64-bit? 

Thank you!

**Comment by sasumner** [comment]
This is not an "issue".  This is a "question".  Please ask questions here:  https://notepad-plus-plus.org/community

Please close this.

**Comment by aglaiawong** [comment]
> 
> 
> This is not an "issue". This is a "question". Please ask questions here: https://notepad-plus-plus.org/community
> 
> Please close this.

OK. sorry for posting in wrong place. Thanks for the redirection!
