### ISSUE TITLE
Feature Request: Command line key to enable seamless edit of read only files

### ISSUE THREAD

**Issue by andry81** [notepad-plus-plus/notepad-plus-plus#4904]
### Description of the Issue
If you ever has been trying to open multiple files at once, then you have already know how is that annoying to clear all these file state read only flags to just, for example, change line endings in all files together.

I am suggesting to add a command line key to ignore read only flag as a file attribute and directly edit files w/o requirement to clear it off before the input. The idea is to not change the state at all until an actual write would happend.

Currently, a solution from deeps of internet suggests to install a python plugin and run a command like this:

    for f in notepad.getFiles():
       notepad.activateFile(f[0])
       notepad.runMenuCommand('Edit','Clear Read-Only Flag')

This one has it's issues like:
* script does not work for localizations other than english, so has to be fixed before install
* slowness
* applies to every opened file, while the save can happen not for all

To save a file, Notepad++ can, for example:

1. remove the flag
2. save file
3. restore flag

For an ability to differentiate between readonly not changed and read only changed file, there is a need to redesign the tabs view, because there is about 3 versions of an icon:

1. read only file
2. read/write not changed
3. read/write changed

When needs 4:

1. read only not changed
2. read only changed
3. read/write not changed
4. read/write changed

### Steps to Reproduce the Issue
Open multiple read only files by accident or intentionally to change them massively from, for example, Search/Replace dialog.

### Expected Behavior
No need to do manual job work of clearing infinite set of read only states.

### Actual Behavior
Not a bit

### Debug Information
N/A

**Comment by sasumner** [comment]
Meh....  Files with read-only attribute set at the OS level deserve a special level of protection.  Notepad++ currently respects this level of protection.  IMO, existing behavior seems appropriate.

**Comment by MetaChuh** [comment]
@andry81 

this behaviour on files without write permissions is per design for security reasons.
while alterations can be done using plugins, a file permission change, or fake removing of the internal read only flag will not be integrated at the notepad++ core.

many thanks and best regards.
