### ISSUE TITLE
Would like to have...

### ISSUE THREAD

**Issue by bbotz** [notepad-plus-plus/notepad-plus-plus#4908]
### Description of the Issue

Feature request: Ability to pin Favorites File to the Open menu

### Expected Behavior

I use Notepad++ a lot and open lots of files. But, I have a handful of files that I use over and over. To open them, I have to hunt them down if they're not in the previous file list. 

So, if you could put a 'pin' next to a file name in the File-Recent File list to make it easier to keep important files just a click away, it would be appreciated.

Thanks!

**Comment by EzeKees** [comment]
+1

**Comment by dinkumoil** [comment]
@bbotz 

1. Lightwight solution: There is a plugin called [NppFavorites available](https://github.com/heldersepu/nppfavorites), might be sufficient for you.
2. Full-blown solution: There is the [Explorer plugin](https://sourceforge.net/projects/npp-plugins/files/Explorer/) which has among a lot of other useful things a favorites feature.

**Comment by dinkumoil** [comment]
@sasumner You are right, I've missed that these plugins don't provide a 64 bit version. Since I'm used to use the 32 bit version of Notepad++ just because of poor 64 bit plugin support I forget this important criteria sometimes.

**Comment by dinkumoil** [comment]
**Update:** The [NppFavorites plugin](https://github.com/heldersepu/nppfavorites) is available as 64 bit version now (and can also downloaded as 32 bit version from the same site, I have to admit that one had to switch to a forked repository to do that before).

**Comment by jagganath69** [comment]
> @bbotz When I do File -> Open I get a window that opens that has a "Favorites" "star" on it. This isn't a Notepad++ feature, but rather a Windows feature. Perhaps that is of some use to you. Otherwise, I also have some files that I use over and over--I just always keep them open in a tab. :-)

That would entail going out of NPP, and probably opening explorer and sorting through the lefthand panel (Recent, Favorites, Network, etc.)
