### ISSUE TITLE
Double clicking on search results failing in some cases

### ISSUE THREAD

**Issue by niente0** [notepad-plus-plus/notepad-plus-plus#491]
Hello, sometimes double-click on search results doesn't open the corresponding file.
This happens when the search string is found inside a long text line (more than 1000 chars without line breaks).

**Comment by donho** [comment]
I believe this issue has been fixed since long time ago.
Update your Notepad++ to the latest version (v7.6.6).
If the issue persists, please create a new issue for it.
Thank you.
