### ISSUE TITLE
Bug report: Hovering over renamed document in document list panel still shows it's old name.

### ISSUE THREAD

**Issue by elvedin-hamzagic** [notepad-plus-plus/notepad-plus-plus#4910]
### Description of the Issue

If we open some document or create a new one, then save it under different name, the name is updated correctly in document list panel. But when hover over it it still shows the old name.

### Steps to Reproduce the Issue

1.  Open a document or create a new one.
2. Save it under different name.
3. Hover over this document's name listed in document list panel. (The document list panel must be enabled in preferences.

### Expected Behavior

The new name should be shown.

### Actual Behavior

The old name is shown.

**Comment by sasumner** [comment]
What is shown in the hover is the _path_ to the file, so a clarification to Expected Behavior is _The new path should be shown_ and Actual Behavior should be _The old path is shown_.

**Comment by sasumner** [comment]
@elvedin-hamzagic Nice observation...yes, I see same behavior.  Sure would be nice if it were consistent.

**Comment by SinghRajenM** [comment]
Adding one more behavior:
> It the document is not open and you open it (from Notepad++ or windows explorer), when you hover over it it will show just the name of the document.

If you reposition the tab, then it will show full path instead of file name. 😉

**Comment by elvedin-hamzagic** [comment]
@SinghRajenM Probably it just need an update to the text which is initially displayed.
