### ISSUE TITLE
Minor issue on 'Close ALL BUT This'

### ISSUE THREAD

**Issue by morbac** [notepad-plus-plus/notepad-plus-plus#4911]
### Description of the Issue
Hi, I noticed a strange behaviour while using the function "Close ALL BUT This" in certain circounstances. The issue occures on NPP 7.5.8 64-bits.
Here is how to reproduce it:

### Steps to Reproduce the Issue
1. Open a existing file, say "hello.txt"
2. Create a new file and write some stuff in it
3. Move this new file on other view (Right-clic on new file tab and select "Move to Other View")
4. Right-click on "hello.txt" tab and select "Close ALL BUT This"
5. NPP prompts if new file should be saved -> answer "Yes" or "No" (if Yes, you'll have to specifiy the destination file name)

### Expected Behavior
Expected Behavior would be that "hello.txt" is now the only opened file

### Actual Behavior
In reality, all files are closed (even the "hello.txt") but the new one.

The issue is not blocking but behaviour is surprising.
Thanks

**Comment by CookiePLMonster** [comment]
.

(Leaving a comment just so I can track this issue easier)

**Comment by CookiePLMonster** [comment]
Just FYI, I reproduced this behaviour locally. Good find!
