### ISSUE TITLE
Default FTP / Remote Edit Support

### ISSUE THREAD

**Issue by seansan** [notepad-plus-plus/notepad-plus-plus#4913]
Hi there, sorry to log this here. But I thought I'd share this here. Our whole team uses Notepad++ whilst I use Editplus a lot and just cannot switch. What I have seen for myself is that this boils down to 1 feature: 

I editplus I can remote edit files over FTP (have remote FTP fav files, quick opens, browse in left panel)

Now I have seen there is an extension that does similar things. But not native and as fast and as complete. 

So my question is: would it be possible to add native remote FTP editing in the future?

**Comment by chcg** [comment]
Maybe you want to try https://github.com/ashkulz/NppFTP/releases first to find out if really something is missing for your usecase.
