### ISSUE TITLE
Selection of "working" tab is lost after restart so the first tab is always selected (by default?)

### ISSUE THREAD

**Issue by cristian-sulea** [notepad-plus-plus/notepad-plus-plus#4915]
### Description of the Issue

When reopening Notepad++ (with session snapshot enabled) the selected file (tab) at closing time is not reselected. It seems that in the session snapshot is not included anymore the "working" tab, so at reopening time the first tab is selected by default.
This was working in 7.4.x versions (i have 7.4.2 and is working) but in 7.5.x (7.5.8) is not working any more.

**This issue was fixed and closed ( <https://github.com/notepad-plus-plus/notepad-plus-plus/issues/4716> ) but the bug is still there.**

### Steps to Reproduce the Issue
1. Open Notepad++
2. Open some files (so we have some tabs)
3. Select last opened file (tab) (but the bug can be reproduced with any tab)
4. Close Notepad++ (Preferences/Backup/Session snapshot -> is enabled)
5. Reopen Notepad++

### Expected Behavior
The tab selected at step 3 should be selected after reopening. 

### Actual Behavior
The first tab is always selected after reopening.

### Debug Information
Notepad++ v7.5.8   (64-bit)
Build time : Jul 23 2018 - 02:06:36
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10 (64-bit)
Plugins : DSpellCheck.dll mimeTools.dll NppConverter.dll

**Comment by SinghRajenM** [comment]
@cristian-sulea wait till next release happens. If you can't wait, then get the nightly build binary and replace it to the notepad installation directory.

https://ci.appveyor.com/api/buildjobs/5u4vljudt309nx33/artifacts/Notepad%2B%2B.X64.Unicode%20Release.exe

Also closing this defect will reduce the bug list.

**Comment by cristian-sulea** [comment]
it seems it was fixed, even if i received many updates through updater
https://github.com/notepad-plus-plus/notepad-plus-plus/issues/4716
