### ISSUE TITLE
Multiple empty tabs wrong backup deleted

### ISSUE THREAD

**Issue by cjgt4hub** [notepad-plus-plus/notepad-plus-plus#4916]
### Description of the Issue
If i open several new tabs which I leave blank, then enter some text in the last open tab, a backup is created for that single tab. If I then I close any of the previous blank tabs, the backup that was created for the used tab is deleted. This does not seem to be related to tab number as if drag a higher numbered blank tab to the left of the tab in use, then close that higher numbered tab, this also deletes the backup for the used tab.

### Steps to Reproduce the Issue

1.  Create a new tab and leave it blank (tab1)
2. Create another tab and enter text in it (tab2)
3. Wait for the backup to run
4. Close tab1

Alternative

1. Create a new tab and leave it blank (tab1)
2. Create another tab and enter text in it (tab2)
3. Create another tab and leave it blank (tab3)
4. Drag tab 3 to the left of tab 2
5. Wait for the backup to run
6. Close tab3

e.g. I create tabs 1, 2, and 3 blank. Create tab 4 and enter text in it, then create 5, and 6 as blank.

In the above circumstance, if I close tab 1, 2, or 3 then the backup for tab 4 will delete. 
If I recreate the situation above, but this time drag 1 or both of tabs 5 and 6 to the left of tab 4, then close tab 5 or 6 this will also cause the backup for tab 4 to delete.

If  do as the above, but in tabs 4, 5 and 6 i enter some text, then close one of the empty tabs to the left, it deletes the backup for the highest numbered tab. This is definitely highest numbered rather than right-most tab, as if I switch tabs 5 and 6 around, backup 6 still gets deleted.

### Expected Behavior
Backup for the used tab remains

### Actual Behavior
Backup is deleted

### Debug Information
Notepad++ v7.5.8   (32-bit)
Build time : Jul 23 2018 - 02:03:53
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 7 (64-bit)
Plugins : ComparePlugin.dll NppEditorConfig.dll NPPJSONViewer-win32.dll PluginManager.dll XMLTools.dll DSpellCheck.dll mimeTools.dll NppConverter.dll NppExport.dll

**Comment by MetaChuh** [comment]
not reproducible on 7.6.6

please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins.
if your issue still persists, and it is still of relevance to you, please feel free to file a new issue as detailed and reproducible as possible.

thank you for your help and best regards.

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)
