### ISSUE TITLE
One instance could contain multiple separate windows

### ISSUE THREAD

**Issue by sorein** [notepad-plus-plus/notepad-plus-plus#4917]
### Description of the Issue

This is a helpful app, but is it so hard to generate a new "window" (with multiple tabs) inside the same "instance"? Just like the "commonplace" Chrome or any other browser? 

### Steps to Reproduce the Issue

1.  Open one window with 3 tabs.
2.  Open another window with 2 tabs.
3.  Windows 8 crashes.
4. Windows 8 opens.
5. Try to recover the work in Notepad++, but only one window is recovered.

### Expected Behavior

 Both windows/instances should reopen.
### Actual Behavior

 Only one window/instance repopens
### Debug Information

 .....

**Comment by MetaChuh** [comment]
please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins if you update from version 7.5.9 or below.
if your issue still persists, and it is still of relevance, please feel free to file a new issue as easy to understand and reproducible as possible.

thank you for your help and best regards.

-----
```
general notes:

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).
please file an issue as easy to understand and reproducible as possible.

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
(no extra account is needed, just use your github account to sign in)
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)

**Comment by sorein** [comment]
You have no idea about what I explained, have you? Let somebody else deal with it.
