### ISSUE TITLE
FileManager::_nextBufferID appears useless

### ISSUE THREAD

**Issue by Rseding91** [notepad-plus-plus/notepad-plus-plus#4918]
### Description of the Issue
In the file Buffer.h in the class "FileManager" the property "_nextBufferID" appears to be useless. Every place it is used the value is immediately thrown away and replaced by the actual useful value.

Additional information:

In the 3 places "_nextBufferID" is used the current value is stored inside a new "Buffer" and then the value is overwritten by the address of the new buffer.

```
Buffer* newBuf = new Buffer(this, _nextBufferID, doc, DOC_REGULAR, fullpath);
BufferID id = static_cast<BufferID>(newBuf);
newBuf->_id = id;
...
++_nextBufferID;
```

Where internally the constructor of "Buffer" uses the value given by "_nextBufferID" and stores it in "_id".

Buffer::_id is an alias for "Buffer*" so in all 3 places where it's set newBuf->_id == newBuf making the "_id" property also useless. Buffer::getID() could simply return "this" and the "_nextBufferID" could be removed and it would result in the same code in the end.

**Comment by CookiePLMonster** [comment]
If you can comment on your changes well enough, then feel free to issue a PR correcting those!
