### ISSUE TITLE
Unable to drag and drop files from Total Commander

### ISSUE THREAD

**Issue by IIIypuk09** [notepad-plus-plus/notepad-plus-plus#4929]
### Description of the Issue
Unable to drag and drop files from Total Commander to Notepad++ when Notepad++ and Total Commander bitness do not match.

### Steps to Reproduce the Issue
1. Notepad++ x86 and Total Commander x64
2. Drag and Drop files from TC to NPP.
3. And Vise versa Notepad++ x64 and Total Commander x86 the same behavior.

### Expected Behavior
Dragged files are opened.

### Actual Behavior
Dragged files are NOT opened.

### Debug Information
Notepad++ v7.5.9   (64-bit)
Build time : Oct 14 2018 - 15:02:52
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 8.1 (64-bit)
Plugins : DSpellCheck.dll mimeTools.dll NppConverter.dll NppExport.dll 

### Commnets
I debug it a little function dropFiles() and found that function DragQueryPoint returns a point p with negative coordinates and function DragQueryFile returns 0 dragged  files.

**Comment by IIIypuk09** [comment]
Yeah, I understood that arch mismatching leads this behavior.

> You can drag file from Total Commander to other area (title bar, menu bar, toolbar, status bar) other than the edit window.

It doesn't work for me. I Just install NPP 32-bit instead of 64-bit, because I use Total Commander x86.

**Comment by zufuliu** [comment]
This (drag file from 32-bit TC to 32-bit N++ not works) sounds very strange.
As Total Commander has 64-bit now, what about drag file from 64-bit TC to 64-bit N++?
https://www.ghisler.com/download.htm
