### ISSUE TITLE
Spelling mistake underlining too fine / hardly visible

### ISSUE THREAD

**Issue by thany** [notepad-plus-plus/notepad-plus-plus#4930]
### Description of the Issue
Spelling mistake underline is not well enough visible.

### Steps to Reproduce the Issue
1. Make sure you've got a sufficiently high-DPI monitor. For me, that's 4K on 15 inch.
2. Make a spelling mistake

### Expected Behavior
The spelling mistake underline should be visible and distingishable from the background, and from a straight red underline.

### Actual Behavior
The spelling mistake underline looks like a straight line. My pixels are waaaay to small to see this underline as intended. The underline is also dark red, on a dark blue background, further diminishing its visibility.

### Debug Information
Notepad++ v7.5.8   (64-bit)
Build time : Jul 23 2018 - 02:06:36
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10 (64-bit)
Plugins : DSpellCheck.dll mimeTools.dll NppConverter.dll 

### Screenshot
![capture](https://user-images.githubusercontent.com/152227/47020117-f0ad0c00-d158-11e8-9958-582de424c17b.PNG)
(it's probably quite big if you're not on a 4K screen)

**Comment by MetaChuh** [comment]
@thany 

please file an issue at the dspellcheck plugin issue tracker.
https://github.com/Predelnik/DSpellCheck/issues

**workaround**: please right click on your notepad++ icon and select `properties > compatibility > change high dpi settings`, activate `override high dpi scaling behavior` and set `scaling performed by:` to `system (enhanced)`, as seen at the screenshot below.
this might g

![Imgur](https://i.imgur.com/qVQ4Bg8.png)

if you want the underlining as thick as at low dpi displays, you can also choose the `system` scaler, for a classic notepad++ look on scaled displays, which will look like this:

![Imgur](https://i.imgur.com/WqSSpUo.png)

note: it is recommended to disable smooth font for the classic scaler look, by going to `settings > preferences > editing` and unchecking `enable smooth font` in notepad++, if it is enabled as seen at the screenshot below.

![Imgur](https://i.imgur.com/vFFvIOR.png)

thank you for your help and best regards.
