### ISSUE TITLE
[Feature Request] Secondary Vertical Edge

### ISSUE THREAD

**Issue by LeonCheung** [notepad-plus-plus/notepad-plus-plus#4937]
A second vertical edge (better with color setting) is kind of useful in some cases. Highly appreciated!
![qq 20181019102431](https://user-images.githubusercontent.com/494788/47194280-51229000-d389-11e8-80d5-14520351e6a6.png)

**Comment by sasumner** [comment]
@LeonCheung This would have to be supported by Scintilla, there is nothing Notepad++ can do about it without Scintilla support.  So normally I would say move your request first to the Scintilla bug/feature list, but...IIRC a newer Scintilla version than Notepad++ currently uses (IIRC 3.5.6) DOES support a secondary vertical edge...just have to wait for Notepad++ to adopt a newer Scintilla.

**Comment by LeonCheung** [comment]
@sasumner Thank you very much for the information!

**Comment by jcrmatos** [comment]
Hello,

Any progress with this issue? That secondary Vertical Edge would be very nice.

Thanks,

JM

**Comment by jcrmatos** [comment]
Hello,

The current version of Scintilla is 4.1.3 (2019-01-10).
Version 3.7.0 is old, it's from 2016-10-16!
If N++ is using an older version of Scintilla, what version is it using?!

Thanks,

JM

**Comment by MAPJe71** [comment]
Notepad++ is now (2019/01/21) using Scintilla 3.5.6.
Scintilla 3.7.0 is the first version to support displaying multiple vertical edges (as @chcg mentioned above).

From the [Scintilla homepage](https://www.scintilla.org/):
> Current development occurs on the default branch as 4.* which requires a recent C++ compiler that supports C++17.
>
> For projects that need to work with older systems, a LongTerm3 branch is available which uses only features from C++11. 

As the default branch (4.*) *might* require major changes in Notepad++, the LongTerm3 branch is more likely to be integrated and that's at version [3.10.2](https://groups.google.com/forum/#!topic/scintilla-interest/jL0pqZBC9UA) at the moment.

**Comment by Ekopalypse** [comment]
Npp 7.7 uses scintilla 4.x which has support for such a feature.
By using a scripting language like pythonscript or luascript it can be implemented like this
SCI_SETEDGEMODE, EDGE_MULTILINE
SCI_MULTIEDGEADDLINE, column1, colour1
SCI_MULTIEDGEADDLINE, column2, colour2 ...

**Comment by dinkumoil** [comment]
I wrote a plugin that can add an arbitrary number of vertical lines to Notepad++ v7.7 and higher. Its name is _ExtSettings_. You can download it [>>> here <<<](https://sourceforge.net/projects/extsettings/). It will also be available soon via _PluginsAdmin_.

**Comment by dail8859** [comment]
This is a native feature of Notepad++ now.

![image](https://user-images.githubusercontent.com/3694843/92011060-87b4ea00-ed18-11ea-9694-5277dcf5aa23.png)
