### ISSUE TITLE
Setting / Preferences / Language Menu / Disabled items problem

### ISSUE THREAD

**Issue by RDENR** [notepad-plus-plus/notepad-plus-plus#4938]
### Description of the Issue
"Setting / Language Menu / Disabled items" makes no effect.

### Steps to Reproduce the Issue
1. Open the file with extension .erl. NPP recognize it as "Erlang file" and highlight syntax for it. 
2. Go to Setting / Preferences  / Language and put Erlang to the "Disabled items".
3. Close NPP and open again with .erl file. NPP still recognize it as "Erlang file".

### Expected Behavior
Disable highlight syntax for .erl file

### Actual Behavior
NPP still recognize .erl it as "Erlang file" 

### Debug Information
Notepad++ v7.5.9   (64-bit)
Build time : Oct 14 2018 - 15:19:55
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10 (64-bit)
Plugins : DSpellCheck.dll mimeTools.dll NppConverter.dll 

![image](https://user-images.githubusercontent.com/42372227/47199768-a2804e80-d38c-11e8-9156-6143c1136e84.png)

**Comment by stanciuadrian** [comment]
I am not sure the `Disabled items` option is related to disabling the lexer itself. It seems to offer customization of the `Language` menu. If `Erlang` is in that list then the `Language -> E -> Erlang` menu item is no longer visible.

But you can "disable" the lexer by removing the `erlang` section from `%AppData%\Notepad++\langs.xml`. Editing `stylers.xml` may have the same result, YMMV.

**Comment by ArkadiuszMichalski** [comment]
@sasumner This still needed? Bassicaly `disabled is correct`, all this settings is apply only to `Language Menu` (even the outline indicates it), this does not mean disabled detecting/recognizing language when open files.
