### ISSUE TITLE
Misspelling in Dialog

### ISSUE THREAD

**Issue by mist83** [notepad-plus-plus/notepad-plus-plus#494]
Update Notepad++ and cancel before the download is complete. "aborted" is misspelled.

![screenshot 2015-07-14 17 40 56](https://cloud.githubusercontent.com/assets/4060053/8687615/85f97e60-2a4f-11e5-93c1-a16950f5819f.png)

Found in V 6.7.7 (can't test with the newest version because there's nothing to download/cancel).

**Comment by vgturtle127** [comment]
It should also say "Update stopped" instead of all that text. It is a bit redundant.

We can assume it is the user because only the user can stop an update. If it was an error or something, it wouldn't be the user anyway.

**Comment by donho** [comment]
It's Notepad++ Updater issue and it's fixed in WinGup projet:
https://github.com/gup4win/wingup/commit/ba47aeaacb434b94d00b3834a67e533cb4137be8
