### ISSUE TITLE
Save sometimes does not work (file changes are not detected)

### ISSUE THREAD

**Issue by c33s** [notepad-plus-plus/notepad-plus-plus#4949]
### Description of the Issue
in very seldom cases the save button/shortcut does nothing. i thought it was gone after i updated to 7.5.4 but it happend again 2 times in the last 2 weeks. 

### Steps to Reproduce the Issue
for me it isn't really reproduceable, it just happens sometimes. 
1. have open about 30 text files (some saved, some never saved at all)
2. open a new file from windows (totalcommander shift + f4)
3. write some text "hello"
4. ctrl + s
5. write more text " world"
6. ctrl + s
7. close notepad++
8. reopen notepad (previous session is reopened)

### Expected Behavior
the file should contain "hello world"

### Actual Behavior
the file contains only "hello"
interesting fact is that before `3.` the save icon in the menu is blue, after `4.` the color change to grey (nonclickable) and writing more text normally would change it back to blue but it stays grey. this is no problem if you use the mouse for saving but if you use ctrl + s there is a very high chance you wont recognize it.

### Debug Information
```
Notepad++ v7.5.4   (32-bit)
Build time : Jan  1 2018 - 01:47:45
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 7 (64-bit)
Plugins : DSpellCheck.dll JSLintNpp.dll JSMinNPP.dll mimeTools.dll NppConverter.dll NppExport.dll NPPJSONViewer.dll NppTextFX.dll NppToolBucket.dll PluginManager.dll SessionMgr.dll XMLTools.dll 
```

**Comment by shimscharf** [comment]
I can confirm this bug is a regular occurrence. Every time.

1) Create new file.
2) write text "hello"
3) save "filename.ext"
4) continue writing text "world"
5) save
6) close notepad
7) look at file --> only contains "hello"

In the last 2 versions of Notepad++ this has been occurring.

I have been been getting around it by:
1) create new file
2) write "hello"
3) save file
4) close file
5) open file
6) write "world"
7) save file

**Comment by dsonewald** [comment]
Also in Notepad++ v7.5.8   (32-bit)
Build time : Jul 23 2018 - 02:03:53
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10 (64-bit)
Plugins : DSpellCheck.dll JSMinNPP.dll mimeTools.dll MultiClipboard.dll npp.connections.dll NppFTP.dll NPPGit.dll NPPJSONViewer.dll NppSnippets.dll NppTaskList.dll NppTextFX.dll NppXmlTreeviewPlugin.dll PluginManager.dll SessionMgr.dll XMLTools.dll NppExport.dll

**Comment by MetaChuh** [comment]
@dsonewald 

i can not reproduce this issue on notepad++ 7.6.4.

please download the portable version 7.6.4. from [>>> here <<<](https://notepad-plus-plus.org/repository/7.x/7.6.4/npp.7.6.4.bin.zip), extract it to your desktop, and start `notepad++.exe` inside of your extracted `npp.7.6.4.bin` folder.

can you reproduce this issue with this fresh and clean portable version ?

**Comment by sasumner** [comment]
dsonewald, You have A LOT of plugins -- I would suspect some plugin interaction issue is causing this.  Follow MetaChuh's advice.

**Comment by dsonewald** [comment]
The issue did appear after installing the plugins. The issue has not appeared so far after upgrading to 7.6.4. If it reappears I'll try sequentially removing plugins.

**Comment by shimscharf** [comment]
Occurred again on fresh copy of 7.6.6

Steps to reproduce:
1. Press New file
2. Type "Hello"
3. Press Save
4. **Change file type to eg save as .php**
5. Type Hello
6. Save
7. Close Notepad++
8. Open file --> only containts 'Hello'


I figured out that if default file type isn't changed this didn't occur.


Debug Info:

Notepad++ v7.6.6   (64-bit)
Build time : Apr  3 2019 - 23:52:32
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10 (64-bit)
Plugins : ComparePlugin.dll DSpellCheck.dll JsMapParser.NppPlugin.dll JSMinNPP.dll mimeTools.dll NppConverter.dll NppSnippets.dll NppTaskList.dll SessionMgr.dll _CustomizeToolbar.dll

**Comment by sasumner** [comment]
I tried @shimscharf 's recent steps with a fresh 7.6.6 and could not reproduce (my file had HelloHello in it after restarting.

**Comment by cmeriaux** [comment]
Is backup feature enabled ?

**Comment by shimscharf** [comment]
session is enable, but backup is on save is on none.

I tried it using a fresh portable version --> no issue.
However, the save dialogue is different. On my installed local version, when I set a default document type, the extension is added automatically, whilst in the portable version it remains without an extension, has save as type "all (*.*)", and only adds the file extension after the dialogue is closed. I assume this is why it is different and working.

 I'll try on a fresh clean install in the next few hours to see if it occurs on that.

![Portable Save As Dialogue](https://user-images.githubusercontent.com/5055939/57739345-9546fa80-76f6-11e9-8203-7f398104646b.png)

![Local Save Dialogue](https://user-images.githubusercontent.com/5055939/57739215-f7ebc680-76f5-11e9-9e55-e35cfcda20d8.png)

**Comment by c33s** [comment]
please reopen, the problem still exists even if it is difficult to reproduce. also if a plugin is the reason for the problem the exact cause would be interesting. maybe a plugin should not be able to prevent saving.

**Comment by sasumner** [comment]
@shimscharf You might want to see what effect, if any, this option has on your testing of your issue:

![image](https://user-images.githubusercontent.com/30118311/57772659-fe714280-76e3-11e9-94e4-454822caf7a8.png)

**Comment by shimscharf** [comment]
I wasn't aware of that setting --> it was unticked, but when I ticked it, exited the settings, and created a new file, Notepad++ CRASHED ! Dump file couldn't be created (Error 5).

![crash](https://user-images.githubusercontent.com/5055939/57778965-8d27a300-7768-11e9-8a2f-f5bdae664097.png)

**Comment by shimscharf** [comment]
That's it !!!

@sasumner nailed it !
I can now toggle the problem on and off using this checkbox

When checked --> that setting allows me to replicate the no save error
