### ISSUE TITLE
Problematic call of loadSciLexerDll in a static initializer

### ISSUE THREAD

**Issue by MIvanchev** [notepad-plus-plus/notepad-plus-plus#4952]
The following line

https://github.com/notepad-plus-plus/notepad-plus-plus/blob/ec340000ccde72debc8d0ac721ec376d07dec3e4/PowerEditor/src/ScitillaComponent/ScintillaEditView.cpp#L50

is potentially dangerous, but the opinion of a C++ expert is required. The logic behind the method is quite complex and uses the standard library, including streams. As far as I understand, the order of static initialization in C++ is specified only within the same module so the standard library might not be ready yet. This could have serious implications and I recommend the call not to be made in the static initializer, but for example in `ScintillaEditView::init`.

**Comment by MIvanchev** [comment]
I found additional information: https://isocpp.org/wiki/faq/ctors#static-init-order.

**Comment by CookiePLMonster** [comment]
If I recall correctly, CRT inits prior to C++ static initializers - but that may be an implementation detail.

**Comment by donho** [comment]
No bug regarding the issue you pointed so far.
If yes, reopen it please.

**Comment by CookiePLMonster** [comment]
To counter this, it's also something undefined  - unless C++ CRT initializes before user code, it may change from compiler to compiler. Maybe it works on Visual Studio 2015, but not Visual Studio 2017? Maybe works with Visual Studio up to version 15.7 but breaks with 15.8? Maybe it breaks with GCC 4.8 but not with GCC 4.7?

**Comment by MIvanchev** [comment]
Yes, it's a gamble, the currently correct initialization order might break in the future, but it would probably be noticed by the maintainer immediately. I can understand the reluctance to fix cosmetic issues, it had probably led to trouble in the past.
