### ISSUE TITLE
Monitoring (tail -f) is not working 

### ISSUE THREAD

**Issue by dia-susca** [notepad-plus-plus/notepad-plus-plus#4955]
### Description of the Issue
I use notepad++ to monitor Websphere application logs, on Windows x64. If I choose the monitor option, the files aren't actually monitored. I still have to right-click on the tab and choose Reload for the file to get updated. 
The automatic updates have a delay that is too big compared to what monitoring should do.

I have version  7.5.9 (64-bit) of notepad++

### Steps to Reproduce the Issue
1. Open a log-file that is written by another (java) application
2. Click the monitor button
3. The log is continuously updated externally

### Expected Behavior
I expect notepad++ to act as a tail -f command

### Actual Behavior
But it actually reloads files just as it did before, whenever it detects a change after a longer time interval

I have tried to manually refresh the file faster, but it is cumbersome to keep right-clicking the file tab. And there is no option in the file editing context-menu to reload the file.
As a work-around, I assigned a shortcut to "Reload From Disk" in Settings/Shortcut Mapper, but it does not work -  I keep pressing the keys without any effect. Only right-clicking the tab and clicking Reload does the expected refresh.

**Comment by SinghRajenM** [comment]
It works fine for me.

Could you save below content in bat file and run the batch file. Then monitor the `time.txt` and see the result. If this works fine, then there might be issue with java logging mechanism.

```Batch
@echo off
setlocal

:loop
echo %time% >> time.txt
timeout /t 2
goto :loop
```


![capture](https://user-images.githubusercontent.com/14791461/47433856-e2956600-d7be-11e8-9c46-41faf947242e.gif)

**Comment by dinkumoil** [comment]
I personally gave it up to use Notepad++ for file monitoring. I found a utility called TailSharp, it can be downloaded [here](http://oette.info/) (look in the right side bar entitled "Downloads"). 

This utility is able to monitor the file created with the script posted by @SinghRajenM above even if you omit the `timeout /t 2` command.

**Comment by dia-susca** [comment]
You are correct that your example works fine. But, for java applications, it doesn't. So it is still a bug.

Here's a sample application that uses log4J (runnable jar, cfg file and sources) that proves that notepad++ monitoring does not work. The file is updated only if you right-click on the file tab.

[TestJavaLogs.zip](https://github.com/notepad-plus-plus/notepad-plus-plus/files/2518367/TestJavaLogs.zip)

Other monitoring apps like BareTail work on windows, so it must be fixable.

Thank you

**Comment by sasumner** [comment]
It's my personal experience that file monitoring (tail) in Notepad++ doesn't work well right at the moment when you need it most, despite "fixings" to the code since the feature was introduced.  IMO it is one of those things that were better off NOT introducing into Notepad++ and leaving to other tools.  Notepad++ is an editor, and one typically doesn't edit files that one uses tail on, so why not have a separate tool for this function?  So I'm with @dinkumoil on this one.  I haven't tried TailSharp (I've been using glogg) but I will.  Of course this is not to say the feature couldn't be made to always work in Notepad++, and I'm in no way trying to belittle this bug report.

**Comment by dinkumoil** [comment]
@sasumner 

glogg seems to be more powerful than TailSharp. Thanks for this hint, I'll give it a try.

**Comment by nzain** [comment]
I'm facing the same issue when writing my own log files from one program (my own code) and trying to monitor those files with Notepad++ (excellent program btw).

- When I reload manually, the content is updated.
- When I switch to some random app (e.g. browser) and back to Notepad++ it correctly detects that the file has changed and asks me to load it (even during tail -f)
- However, the monitoring itself does nothing.

Maybe this is related to how programs usually write files: open the file stream once, write data, flush, write, flush, and then.. at some point in the future, close the file stream. The batch example will always close the stream and probably update LastWriteTime and similar properties.

**Comment by AyrA** [comment]
I just run into the same issue. The problem is how some applications write to the stream (actually many of them do it).

The `echo Text>>Filename`  example works because the stream is closed after each write. Some logger don't close the file after each write, mostly because it's very inefficient and you are not guaranteed to be able to open it again.

Notepad++ has problems updating with writers that don't close after each write.

Multiple fixes come to mind:

- Periodically check if the file position is no longer at the end.
- Check if the file size or write time changed.

After experimenting, I found the first method more reliable.

Below is C# test code that can catch up with the log file at any time:

    using (var FS = File.Open(
        @"C:\Path\To\Your\file.log",
        FileMode.Open,
        FileAccess.Read,
        FileShare.ReadWrite))
    {
        using (var SR = new StreamReader(FS))
        {
            while(true)
            {
                while(!SR.EndOfStream)
                {
                    Console.WriteLine(SR.ReadLine());
                }
                System.Threading.Thread.Sleep(500);
            }
        }
    }

**Comment by MarekR22** [comment]
> 
> 
> It works fine for me.
> 
> Could you save below content in bat file and run the batch file. Then monitor the `time.txt` and see the result. If this works fine, then there might be issue with java logging mechanism.
> 
> ```batchfile
> @echo off
> setlocal
> 
> :loop
> echo %time% >> time.txt
> timeout /t 2
> goto :loop
> ```
> 
> ![capture](https://user-images.githubusercontent.com/14791461/47433856-e2956600-d7be-11e8-9c46-41faf947242e.gif)

This example is invalid as mentioned above.

Proper example is to write this batch script `test.bat`:
```batchfile
@echo off
setlocal

:loop
echo %time%
timeout /t 2
goto :loop
```
And run it like with redirect of stdout:
```batchfile
test.bat > time.txt
```
Now contents of file in Notepad++ is refreshed only when switching focus back to Notepad++ (but this is also done when `tail` option is disabled).

**Comment by minig0d** [comment]
confirmed.  experiencing exact same issue.  Example file is windows firewall logging %systemroot%\system32\LogFiles\Firewall\pfirewall.log

(and assuming this bug could ever be resolved) would be nice to add the equivalent of a -n flag so you could show the latest 10 lines only etc.  but that's wishful thinking...

**Comment by Personwithhat** [comment]
Same issue when monitoring dumps from large applications, e.g. lua/database/etc. log outputs from an EXE.

Will not update when Notepad++ is focused, and will not update when  not focused. I have to select notepad, then select another window, then select notepad again. This is useless for monitoring purposes.........

**Comment by gapkalov** [comment]
Confirmed

**Comment by sensboston** [comment]
This pretty easy to solve feature request remains re-appearing periodically. Yes, we already know about Windows bug/feature to do not raise event on opened streams changing, but this shouldn't be an issue. Why not use timer (with configurable interval) to monitor file changes? I never worked on Notepad++ development and don't have time to issue a PR with that feature, but this feature implementation for experienced Notepad++ developers should be easy (I think so). For example, Far Manager team fixed this a long-long time ago.

**Comment by minig0d** [comment]
> This pretty easy to solve feature request remains re-appearing periodically. Yes, we already know about Windows bug/feature to do not raise event on opened streams changing, but this shouldn't be an issue. Why not use timer (with configurable interval) to monitor file changes? I never worked on Notepad++ development and don't have time to issue a PR with that feature, but this feature implementation for experienced Notepad++ developers should be easy (I think so). For example, Far Manager team fixed this a long-long time ago.

Agree.  Sounds like a very reasonable approach to working around the limitation.  And from a user perspective, even if it was only polling the filesystem every ~5 seconds, I think that would be a pretty acceptable compromise (imagining there are likely issues with network fs's and latency and buffering type problems that could arise if polled at too close of an interval),  When I'm viewing log files typically I'm not needing to see the result in realtime but just in fairly close proximity so I like the idea of this as a quick fix solution.

**Comment by gapkalov** [comment]
> only polling the filesystem every ~5 seconds
polling the filesystem <configurable value> default 5 seconds.

**Comment by sensboston** [comment]
Polling interval should be a configurable setting, and it's up to customer how often to update.

**Comment by AyrA** [comment]
How did the actual tail command solve this? I use tail from cygwin on Windows for days at a time and it works fine.

**Comment by Personwithhat** [comment]
Not related to issue at hand. 

Just need to get Notepad++ monitoring working properly.

**Comment by AyrA** [comment]
> Not related to issue at hand.

Very related. Notepad++ monitoring and `tail -f` are literally the same thing. It even says so in the tooltip and the behavior is the same as `tail -f` documents. Since the Notepad++ variant is not working properly we might want to outright toss it out and replace it with the code from the tail utility that does file monitoring.

**Comment by sasumner** [comment]
>we might want to outright toss it out 

And maybe leave such a function to other tools

**Comment by Personwithhat** [comment]
It's useful to edit/view logs in real time, not something I would just 'leave to other tools'.

And no, it's not related.
Just because functionality should be the same does not mean implementation is. You can't just "replace it" with code from another utility, much less one that depends on Cygwin or other POSIX-style environments.

**Comment by AyrA** [comment]
> You can't just "replace it" with code from another utility, much less one that depends on Cygwin or other POSIX-style environments.

You definitely can. A cygwin utility is bound to the same restrictions as any other utility on Windows is. They can't just magically ignore them. All we need to do is have a look at how the file monitoring is done in that utility and add that part of the code to the notepad++ monitoring function. We don't need to import the cygwin library at all for this.

**Comment by jrocha** [comment]
@AyrA  @Personwithhat  just made a new PR (https://github.com/notepad-plus-plus/notepad-plus-plus/pull/7969)

**Comment by cawoodm** [comment]
Which release was this fixed in?

**Comment by darkmatter2222** [comment]
i had this issue, updated to 8.4.8, works fine now.

**Comment by snlehton** [comment]
I'm using 8.5.3 and it's absolutely not working at all. Not sure what is the issue, but whenever I really need the tail feature, it simply does not work and renders Npp unusable. Sometimes I need to kill the process to be able to use Npp again.

![npp_tail_f](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/5459058/1e0555f2-ba3c-46aa-80dc-6b47674929b1)
