### ISSUE TITLE
New File

### ISSUE THREAD

**Issue by gbiagomba** [notepad-plus-plus/notepad-plus-plus#4959]
### Description of the Issue
I upgraded and lost all my unsaved pages, and to make it worse now when i open a new tab, if I dont save the tab and close the application. When I open it I lose the tab, is there anyways we can bring back the tab function where I do not need to save the files to keep the tab?

### Steps to Reproduce the Issue

1. Open notepad++
2.  Create a new tab
3. Close notepad++
4. Re-open notepad++

### Expected Behavior
I expected my new unsaved tabs to be kept

### Actual Behavior
The new unsaved tabs where gone, only the save files remained

### Debug Information

Notepad++ v7.5.9   (64-bit)
Build time : Oct 14 2018 - 15:19:55
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : ON
Local Conf mode : OFF
OS : Windows 7 (64-bit)
Plugins : DSpellCheck.dll mimeTools.dll NppConverter.dll

**Comment by MilkyWay90** [comment]
I tried reproducing on 6.4.4 but didn't work. Try going to 6.4.4 version and trying it again.

**Comment by gbiagomba** [comment]
@MilkyWay90 Just to make sure I am reading you correctly, you are recommending me to downgrade to version 6.44?

**Comment by MilkyWay90** [comment]
Yes, I am. Actually 6.9.4, I misread the debug info.

**Comment by gbiagomba** [comment]
I reinstalled the applcation and it works fine now
