### ISSUE TITLE
Add "proper case" and sentence case to convert case menu

### ISSUE THREAD

**Issue by vgturtle127** [notepad-plus-plus/notepad-plus-plus#496]
"Proper case" looks like this:

The Quick Brown Fix Jumps Over The Lazy Dog

Sentence case looks like this:

The quick brown fox jumps over the lazy dog.

Seems easy enough to implement, and it would add additional features to Notepad++.

Again, as I completely re-write a PS1 emulator, I keep finding things I really wish I had.

Thanks for reading! :smile:

**Comment by milipili** [comment]
Wow is it really an useful feature ? :)

**Comment by Eldaw** [comment]
I agree that it would make sense to have these extra case-changing options built directly into Notepad++. They currently exist in the TextFX plugin, and I've used them a few times.

**Comment by vgturtle127** [comment]
Yeah, my problem with adding tons of functionality to Notepad++ with plugins is that many of them haven't been updated since we switched to GitHub, if not for a very long time.

Also, some plugins still come in multiple versions, or have newer versions elsewhere, or have older versions through the plugin manager but not anywhere else. All very confusing.

**Comment by milipili** [comment]
Do not worry we will do something about plugins. Many feature requests should be implemented as plugins and not in the main core. But a few things remain to be done first.

**Comment by vgturtle127** [comment]
Good to hear! I wish the hex editor plugin worked better. I kind of like it better than most other hex editors that are dedicated. :disappointed:

**Comment by dail8859** [comment]
Closed by f6e47cd536f5c940de0eb8c378b71801dbeb6ae7

**Comment by vgturtle127** [comment]
@dail8859 Thank you!
