### ISSUE TITLE
Crash when using find in files multiple times

### ISSUE THREAD

**Issue by Pokechu22** [notepad-plus-plus/notepad-plus-plus#4963]
### Description of the Issue
When using "find in files", notepad++ will sometimes crash.  This seems to happen if there is already a find results window open; simply closing the find results window seems to prevent the crash.

### Steps to Reproduce the Issue

1. Use find in files once, making sure there are results.
2. Use find in files a second time
3. Notepad++ will crash.

For reference, the files I am searching in are java files, and I have the filter configured to use `*.java`.  Additionally, this can happen without changing any of the parameters to find-in-files.

### Expected Behavior
No crash.

### Actual Behavior
A failed assertion:

```
---------------------------
Microsoft Visual C++ Runtime Library
---------------------------
Assertion failed!

Program: C:\Users\Pokechu22\Downloads\notepad++\SciLexer.dll
File: C:\projects\notepad-plus-plus\scintilla...\LexAccessor.h
Line: 168

Expression: pos >= startSeg

For information on how your program can cause an assertion
failure, see the Visual C++ documentation on asserts

(Press Retry to debug the application - JIT must be enabled)
---------------------------
Abort   Retry   Ignore   
---------------------------
```

Sometimes notepad++ crashes without an assertion message, too.

### Debug Information
Notepad++ v7.5.9   (32-bit)
Build time : Oct 25 2018 - 08:06:56
Path : C:\Users\Pokechu22\Downloads\notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10 (64-bit)
Plugins : DSpellCheck.dll mimeTools.dll NppConverter.dll NppExport.dll NppFTP.dll PluginManager.dll 

This is a development build, which I'm using to test whether #4339 is fixed (I haven't yet experienced this issue on that version).  This did not happen on the stable build I was using beforehand, although I do not remember which build that was (it's probably noted in my comments on that issue, though).

**Comment by Pokechu22** [comment]
This is still an issue as of 412c5986.

**Comment by MetaChuh** [comment]
please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins if you update from version 7.5.9 or below.
if your issue still persists, and it is still of relevance, please feel free to file a new issue as easy to understand and reproducible as possible.

thank you for your help and best regards.
