### ISSUE TITLE
Allow EOL Conversion to a text file's already detected line endings mode

### ISSUE THREAD

**Issue by RKSimon** [notepad-plus-plus/notepad-plus-plus#4966]
### Description of the Issue
In cases where the EOL have become mixed (this often occurs during svn/git merges) and we want to 'normalize' it back, its currently necessary to change the EOL to something else (as the detected EOL is ghosted out) and then change it back again.

### Steps to Reproduce the Issue
1. Create a Unix (LF) text file
2. Concat a Windows (CRLF) text file to the end
3. Attempt to set the EOL to Unix (LF) to correct the line endings

### Expected Behavior
You should still be able to set the EOL to Unix (LF), fixing all line endings - while still retaining some way to indicate that its the detected EOL mode.

### Actual Behavior
Unix (LF) is ghosted out and can't be selected to correct the line endings.

**Comment by MetaChuh** [comment]
just switch to windows (cr lf) and back
