### ISSUE TITLE
Spelling errors in default Spell-Checker

### ISSUE THREAD

**Issue by fade2gray** [notepad-plus-plus/notepad-plus-plus#4971]
"prepend" and "prepended" are valid English words. I don't want them replaced with "perpend" or "perpended".

Edit: these are acutally ommisions and not spelling errors. Sorry for the misleading title.

**Comment by dail8859** [comment]
This is a plugin issue and not applicable to the main Notepad++ application. Feel free to open a ticket here: https://github.com/Predelnik/DSpellCheck
