### ISSUE TITLE
Could everyone tell me how can use notepad++ plugins by a script

### ISSUE THREAD

**Issue by CHN-STUDENT** [notepad-plus-plus/notepad-plus-plus#4972]
Hi,everyone,i get a idea about writing a script which use the nppexport plugin to open a code file then export to a RTF or html file.

But i do not know how can use notepad++ plugins by a script,so could everyone tell me how to do?

Thanks!

**Comment by CHN-STUDENT** [comment]
![image](https://user-images.githubusercontent.com/21209416/47711606-9049be80-dc70-11e8-80eb-17629a1e7d86.png)

The current solution is that I have customized the shortcuts, but I still need to do the operation, is there anyone else who has a better solution?

**Comment by sasumner** [comment]
Those are QUESTIONS, not ISSUES, and this forum is only for ISSUES.  Please find a different place for QUESTIONS (suggest: https://notepad-plus-plus.org/community/).  Please press the CLOSE button on this issue.

**Comment by CHN-STUDENT** [comment]
@sasumner OK,thanks!
