### ISSUE TITLE
file modification time stamps and the need to reload

### ISSUE THREAD

**Issue by chanlists** [notepad-plus-plus/notepad-plus-plus#4973]
Since npp 7.5.8 or 7.5.7, something seems to have happened in the way that npp checks whether a file needs to be reloaded or not. For files located on the AFS network file system, since 7.5.8 or 7.5.7, npp will save the file I am editing, and if I leave it alone for a moment, do something else and then go back to npp, it will say that the file has been changed and ask whether I want to reload. In fact there are never any external changes to the file. What can I do? Thanks,

Christian

**Comment by MetaChuh** [comment]
@chanlists 

please mount the volumes, with files to edit in notepad++, as smb on your mac.
changed extra attributes and spotlight may trigger an unexpected file change though the file handling api layer.
additional information will be stored as extra files on smb volumes and will not reflect at the actual files themselves.

best regards.

**Comment by chanlists** [comment]
This is not a mac... this is a windows 10 desktop with the OpenAFS filesystem installed. OpenAFS provides an IFS redirector to access files using a UNC syntax (\\afs\your.domain.name\jfkls\fhjlkas\some_file.txt). I can give you access if you would like to try out the symptoms....
