### ISSUE TITLE
No results for unsaved pages in a Full search.

### ISSUE THREAD

**Issue by jimlynnjulian** [notepad-plus-plus/notepad-plus-plus#4974]
Hello,

   The "Find In All Opened Documents" function works for all saved files. 
If, however, a tab such as "new1" has not been saved, the search results will contain a line number but no filename. The returned result when clicked will not open the page, and scroll to the linked search term.

To duplicate:
Open a saved text file. Open a new page/tab. Write different words to each page/tab.
Do a full search as mentioned above, for the word in the saved file.
The name of the file and the term will be returned. Click on the term to got to the found term.
Try this with the "new1" tab/page and the task will fail. No page name is returned and no link is made to the term.

**Comment by sasumner** [comment]
They really should change the name on the button to "Find All in All User-Named Tabs"...but that's a bit unwieldy.  :-)

**Comment by jimlynnjulian** [comment]
...as long as the issue is addressed...

**Comment by sasumner** [comment]
It's been noted...whether or not it gets addressed is TBD.  :-)

**Comment by jimlynnjulian** [comment]
...are you the author? If so:
Last night, I happened to notice the event is inconsistant. 
If not, "...."
Good luck.

**Comment by sasumner** [comment]
> are you the author?
No.

Why did you close this???
