### ISSUE TITLE
Incorrect prompt for unsaved file showing $STR_REPLACE instead of 'new N'

### ISSUE THREAD

**Issue by antonylu** [notepad-plus-plus/notepad-plus-plus#4975]
### Description of the Issue

Incorrect prompt for unsaved file showing $STR_REPLACE instead new N

### Steps to Reproduce the Issue

1.  create a new file
2.  type something
3.  try to close the file

### Expected Behavior

The prompt shall show "Do you want to save 'new 7'?
### Actual Behavior

The prompt shows "Do you want to save '$STR_REPLACE'?
### Debug Information

Notepad++ v7.5.9   (64-bit)
Build time : Oct 14 2018 - 15:19:55
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10 (64-bit)
Plugins : DSpellCheck.dll mimeTools.dll NppConverter.dll JSMinNPP.dll

**Comment by sasumner** [comment]
FWIW, I cannot reproduce this with same version on Win7.  I get 'Save file "new 7" ?'.

**Comment by CookiePLMonster** [comment]
What language are you experiencing it with?

**Comment by antonylu** [comment]
The OS is Windows 10, Traditional Chinese.
![image](https://user-images.githubusercontent.com/22133035/47826304-13bef900-ddb2-11e8-9315-18b7c79e0f26.png)

**Comment by antonylu** [comment]
Tried with English interface, the issue is gone. 
So yes, it looks like a localization issue, introduced by this new version v7.5.9 I just installed.
