### ISSUE TITLE
Text search not working for the word "underline"

### ISSUE THREAD

**Issue by bntabor** [notepad-plus-plus/notepad-plus-plus#4976]
### Description of the Issue
Search css style sheet for text, "underline"

### Steps to Reproduce the Issue

1.  Open CSS Style Sheet, Control F, type in, or paste in the word "underline", hit "Find Next"
2.  Returns result " Can't find the text "underline" "
3.  See snapshot

### Expected Behavior
Find the text "underline"

### Actual Behavior
Can't find the text "underline" / Have not had any other problems (that i know of) of finding any other words / text.

### Debug Information
Notepad++ v7.5.9   (64-bit)
Build time : Oct 14 2018 - 15:19:55
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10 (64-bit)
Plugins : DSpellCheck.dll mimeTools.dll NppConverter.dll 

![underline](https://user-images.githubusercontent.com/6926286/47764551-ae74e600-dc93-11e8-909d-b331419f7916.jpg)

![underline](https://user-images.githubusercontent.com/6926286/47764695-52f72800-dc94-11e8-9dcf-1edf4dc58465.jpg)

**Comment by GordonAitchJay** [comment]
I was unable to reproduce your issue. Have you tried updating to 7.6.3? Do you still have the same issue?

My debug info:
Notepad++ v7.6.1   (64-bit)
Build time : Dec 12 2018 - 01:22:05
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10 (64-bit)
Plugins : ComparePlugin.dll DSpellCheck.dll HTMLTag.dll JSMinNPP.dll mimeTools.dll NppConverter.dll nppcrypt.dll NPPJSONViewer.dll NppXmlTreeviewPlugin.dll SurroundSelection.dll XMLTools.dll

**Comment by sasumner** [comment]
How did you get "underline" in the Find what text box?  Try this: Close the Find window. Put your caret on "underline" in your editor tab.  Press ctrl+f.  "underline" should appear in the Find what box when the Find window opens.  Press "Find all in current document".  See if that works any differently.

**Comment by bntabor** [comment]
> 
> 
> I was unable to reproduce your issue. Have you tried updating to 7.6.3? Do you still have the same issue?
> 
> My debug info:
> Notepad++ v7.6.1 (64-bit)
> Build time : Dec 12 2018 - 01:22:05
> Path : C:\Program Files\Notepad++\notepad++.exe
> Admin mode : OFF
> Local Conf mode : OFF
> OS : Windows 10 (64-bit)
> Plugins : ComparePlugin.dll DSpellCheck.dll HTMLTag.dll JSMinNPP.dll mimeTools.dll NppConverter.dll nppcrypt.dll NPPJSONViewer.dll NppXmlTreeviewPlugin.dll SurroundSelection.dll XMLTools.dll

No, i have v. 7.5.9 (64 bit). clicking the "update notepad ++" under the ? drop down yields "no update is available".

I'll update and see if that solves the problem. Thank You.

**Comment by bntabor** [comment]
Yea, success! The update fixed it. not sure why it told me there were no updates?? I'll keep a closer eye on the website.

Thanks a million!

**Comment by GordonAitchJay** [comment]
> Yea, success! The update fixed it. not sure why it told me there were no updates?? I'll keep a closer eye on the website.
Yeah I've noticed the same thing. I haven't looked into it. Maybe someone's already created an issue for it.
