### ISSUE TITLE
AutoHotKey Language inclusion into N++ (dark theme)

### ISSUE THREAD

**Issue by b16r05** [notepad-plus-plus/notepad-plus-plus#4980]
### Description of the Issue

AutoHotkey WITH Dark Theme

### Steps to Reproduce the Issue

1. Open file with .ahk extension
2. See no highlight
3. With various solutions... things change such as font size, white background, etc.

### Expected Behavior

Autohotkey highlights with background being which ever theme is selected (IF Zenburn is selected, then background stay grey)
 
### Actual Behavior

Autohotkey highlights with background being WHITE (IF Zenburn is selected, then background CHANGES to white)

### Solution Information

The solution is _discussed_ here: https://autohotkey.com/board/topic/62392-notepad-syntax-highlighting-color-scheme/
The solution is _available_ here: http://panofish.net/pics/userDefineLang.xml

There is no reason users have to "pull ninja" to get this working. Solution works beautifully with Zenburn. 

AutoIt is in there but not AutoHotKey... this is wrong : )

**Comment by MetaChuh** [comment]
please use a udl that matches your theme.

many thanks and best regards.
