### ISSUE TITLE
7.5.9 cannot open files with spaces in path

### ISSUE THREAD

**Issue by garfieldbanks** [notepad-plus-plus/notepad-plus-plus#4981]
Double clicking "D:/Folder/Another Folder/file.txt" opens fine on 7.5.8, but not on 7.5.9

**Comment by garfieldbanks** [comment]
Using minimalist package x64

**Comment by garfieldbanks** [comment]
![image](https://user-images.githubusercontent.com/12904270/47856645-503c2600-ddad-11e8-8e34-6b11b51ae934.png)

**Comment by garfieldbanks** [comment]
![image](https://user-images.githubusercontent.com/12904270/47856693-6b0e9a80-ddad-11e8-998b-06e630e7535b.png)

**Comment by garfieldbanks** [comment]
![image](https://user-images.githubusercontent.com/12904270/47856784-a3ae7400-ddad-11e8-963c-2c7f9b8b06ee.png)

**Comment by garfieldbanks** [comment]
Meanwhile on 7.5.8:
![image](https://user-images.githubusercontent.com/12904270/47856954-0dc71900-ddae-11e8-997b-4123483aa54e.png)

**Comment by garfieldbanks** [comment]
Something must have gone wrong when adding support for the debugger regedit hack.

**Comment by CookiePLMonster** [comment]
I just upgraded from 7.5.8 to 7.5.9 and didn't reproduce it with description given above (aka "any path with spaces in it outside Program Files won't work).

**Comment by CookiePLMonster** [comment]
Not off top of my head. If you have Process Explorer, can you check how does notepad++.exe process spawn? What commandline arguments does it have when you launch it by doubleclicking a TXT file?

**Comment by garfieldbanks** [comment]
I used Process Explorer and tested both 7.5.8 and 7.5.9 and they use the same commandline arguments:

"D:\Apps\Notepad++\notepad++.exe" D:\Folder\Another Folder\file.txt

**Comment by garfieldbanks** [comment]
I tested in program files and it doesn't work there either. Can't remember why I originally titled it like that.

**Comment by garfieldbanks** [comment]
Based on the second popup error message, it seems to be tacking on an extra \Folder\ between \Another Folder\ and \file.txt when it should just be looking for \Another Folder\file.txt

**Comment by CookiePLMonster** [comment]
Have you checked with a non-minimalist package? Admitedly, I have no idea how is the minimalist one different from a regular one.

**Comment by garfieldbanks** [comment]
Just tried the regular zip package with the same result.

**Comment by garfieldbanks** [comment]
And now I've also tried the installer version as well. Does not change anything.

**Comment by garfieldbanks** [comment]
Installer version also has the same result.

**Comment by MilkyWay90** [comment]
Im using Notepad++ 6.4, but I'm guessing when you open a file, put double-quotes around "Another Folder"

**Comment by garfieldbanks** [comment]
@MilkyWay90 I'm not opening it in a terminal or anything. I'm just double clicking it from file explorer.

**Comment by garfieldbanks** [comment]
> Are you sure?
Yes.

I checked both 7.5.8 and 7.5.9 with both commands. 7.5.8 works with both. 7.5.9 only works with the quoted one.

The problem however is that double clicking uses the unquoted version and therefore fails on 7.5.9

**Comment by garfieldbanks** [comment]
> Are you sure?

Yes.

I checked both 7.5.8 and 7.5.9 with both commands. 7.5.8 works with both. 7.5.9 only works with the quoted one.

The problem however is that double clicking uses the unquoted version and therefore fails on 7.5.9

**Comment by cmeriaux** [comment]
@garfieldbanks I can't reproduce your issue.
can you post debug information ? Issue may be related to OS.

After double clic on the file, here is the command invoked by OS to start npp:

    "C:\Program Files (x86)\Notepad++\notepad++.exe" "D:\space folder\file.cpp"

OS have add double quotes to protect the path that contains spaces.

Here is my debug info

	Notepad++ v7.5.9   (32-bit)
	Build time : Oct 16 2018 - 09:29:35
	Path : C:\Program Files (x86)\Notepad++\notepad++.exe
	Admin mode : OFF
	Local Conf mode : OFF
	OS : Windows 10 (64-bit)
	Plugins : CodeAlignmentNpp.dll ComparePlugin.dll FileSwitcher.dll LightExplorer.dll linefilter2.dll MarkdownViewerPlusPlus.dll MenuIcons.dll mimeTools.dll NavigateTo.dll NppConverter.dll NppExec.dll NppExport.dll NppFTP.dll NppGTags.dll NppMenuSearch.dll PythonScript.dll XMLTools.dll

**Comment by garfieldbanks** [comment]
Process Explorer (procexp64.exe) tells me that the command used (on Windows 10) is:

"D:\Apps\Notepad++\notepad++.exe" D:\Folder\Another Folder\file.txt

Is there some other debug information I can provide for you? (How do I obtain it?)

**Comment by cmeriaux** [comment]
@garfieldbanks  open menu "?" then start menu "debug info"

**Comment by garfieldbanks** [comment]
Notepad++ v7.5.8   (64-bit)
Build time : Jul 23 2018 - 02:06:36
Path : D:\Apps\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : ON
OS : Windows 10 (64-bit)
Plugins : none

Notepad++ v7.5.9   (64-bit)
Build time : Oct 14 2018 - 15:19:55
Path : D:\Apps\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : ON
OS : Windows 10 (64-bit)
Plugins : none

**Comment by MilkyWay90** [comment]
Don't double click the file. When in File Explorer, type in the PATH of the file at the top-middle section, then hit ENTER.

**Comment by MilkyWay90** [comment]
And use quotes there.

**Comment by garfieldbanks** [comment]
@MilkyWay90 Are you suggesting a workaround or something? For now I'm just using 7.5.8

The bug is in the commit that simplified command line parsing (74d39b1).

**Comment by garfieldbanks** [comment]
It might help to identify what part of the code is causing the issue to know that every added space in the path adds a new popup error message.

**Comment by CookiePLMonster** [comment]
Are you using a custom shell? Or default explorer.exe? I just checked and usually doubleclicking should invoke
```program.exe "%1"```
so lack of quotes on your end imply something wrong with this action itself.

**Comment by garfieldbanks** [comment]
Default Windows 10.

**Comment by bronc3buster842001** [comment]
I have sorta the same issue. Only happens when the file name has a space in it.

**Comment by garfieldbanks** [comment]
I was able to fix it by adding quotes around all the %1 using regedit. I had previously changed all the notepad.exe references to notepad++.exe. Some of them were missing quotes.

**Comment by CookiePLMonster** [comment]
Have you done it manually? Then that'd be an user error, since it's not
invalid for applications to expect paths to be quoted. It's standard.

**Comment by garfieldbanks** [comment]
Considering the old command line parsing was able to handle it, I don't really understand why the new way can't be modified to work as well. But now that I know how to fix it I'm fine if that's what you really want.

**Comment by CookiePLMonster** [comment]
I guess it could. However, behaviour you want is now a part of `-notepadStyleCmdline` commandline switch.

**Comment by archerarcher1** [comment]
Ahem, same here, since v7.5.9 x86 on Win 10 x64.
v7.6.0 still has this issue. 

v7.5.8 works well.

**Comment by aviolov** [comment]
I also experienced this issue with 7.5.9 on Windows 10. This would not work 
` start notepad++ "\\S7\remote logs\s8\Trader20190204.txt" `
I got the "cannot open "\\S7\remote"" error dialog and no amount of quoting seemed to help. I tried putting the quotes around "remote logs" then around the the file before .txt (as some googling suggested. Nothing worked. Downgrading to 7.1 works.

**Comment by archerarcher1** [comment]
Yes, the bug is still present on Win 10. 
I'm not a coder but I cannot imagine why this cannot be fixed. Other texte eitors do nort have this issue.

**Comment by MetaChuh** [comment]
not reproducible on notepad++ 7.6.6. x64, portable, minimalist and installed.

please check for all paths being in `"` double quotes at your registry custom command and all eventual batch command lines that should start notepad++ on your system.

wrong: 
```
"D:\Apps\Notepad++\notepad++.exe" D:\Folder\Another Folder\file.txt
"D:\Apps\Notepad++\notepad++.exe" %1
```

correct:
```
"D:\Apps\Notepad++\notepad++.exe" "D:\Folder\Another Folder\file.txt"
"D:\Apps\Notepad++\notepad++.exe" "%1"
```

-----
```
general notes:

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
(no extra account is needed, just use your github account to sign in)
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)

**Comment by shodanx2** [comment]
Hello,
For some strange reason, I have this exact bug with notepad++ v8.4.9 and I don't understand why !

When I start notepad++ via the notepad.exe debugger redirect, it does not pass the filename correctly !

On the good PC and on my test PC, I have the same registery entry

Computer\HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\notepad.exe
Debugger
REG_SZ
"C:\Program Files\Notepad++\notepad++.exe" -notepadStyleCmdline -z

On my good PC it works just fine.

Notepad++ v8.5   (64-bit)
Build time : Mar  6 2023 - 02:18:13
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : -notepadStyleCmdline -z "C:\Windows\system32\NOTEPAD.EXE" D:\shodan\Desktop\notepadpp notepad.exe  replacement debugger trick bug.txt
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 10 Pro (64-bit)
OS Version : 22H2
OS Build : 19045.2604
Current ANSI codepage : 1252
Plugins : 
    ComparePlugin (2.0.2)
    mimeTools (2.9)
    NppConverter (4.5)
    NppExport (0.4)

On the the test PC

Using Edit with notepad++ on txt file context menu

Notepad++ v8.4.9   (64-bit)
Build time : Jan 27 2023 - 03:11:16
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : "D:\todo (2).txt"
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 10 Pro (64-bit) 
OS Version : 22H2
OS Build : 19045.2006
Current ANSI codepage : 1252
Plugins : 
    mimeTools (2.9)
    NppConverter (4.5)
    NppExport (0.4)

Using Edit on txt file context menu

Notepad++ v8.4.9   (64-bit)
Build time : Jan 27 2023 - 03:11:16
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : -notepadStyleCmdline -z "C:\Windows\system32\NOTEPAD.EXE" D:\todo (2).txt
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 10 Pro (64-bit) 
OS Version : 22H2
OS Build : 19045.2006
Current ANSI codepage : 1252
Plugins : 
    mimeTools (2.9)
    NppConverter (4.5)
    NppExport (0.4)

**Comment by alankilborn** [comment]
Known issue; fixed in 8.5.

**Comment by shodanx2** [comment]
Thanks, updated to 8.5 and it's fixed !

**Comment by vlakoff** [comment]
(some googling brought me here.)

Refs #13032.
