### ISSUE TITLE
Notepad++ copy paste not working

### ISSUE THREAD

**Issue by ifstatement0029** [notepad-plus-plus/notepad-plus-plus#4988]
When I copy any text from Notepad++ and paste it somewhere else, either in the same file or even in other applications such as an internet browser, it does not paste what I copied but instead pastes something like this: qp4vtx7s6psqynry0l0llk6fllsyyrtw6s2djxrkjh

**Comment by MilkyWay90** [comment]
What exactly are you pasting? Is it normal ASCII or extended ASCII or what?

**Comment by ifstatement0029** [comment]
I am pasting the following code from my Free Pascal file (.pas) to the same Free Pascal file on a different line: 

usableitm7[quickbarm1[mo[7],quickbarm[mo[7],3],mo[5]]]
Those are arrays of multiple dimensions within arrays of multiple dimensions. In fact, I just tried to copy from Notepad++ and paste in this email the variable declarations for the above but I get this: 

qp4vtx7s6psqynry0l0llk6fllsyyrtw6s2djxrkjh

The issue seems to happen randomly, and regardless of where I paste the data (different file, software, etc.), but once it happens it keeps happening, no matter what line I copy and paste, until I close all files from Notepad++ and reopen one or all of them. Closing one file is not enough to make the problem stop, I need to close all of them from within Notepad++ and then reopen them. 

I am not using any encoding that I am aware of. 


Sebastien 

    On Tuesday, 6 November 2018, 18:35:31 GMT, MilkyWay90 <notifications@github.com> wrote:  
 
 
What exactly are you pasting? Is it normal ASCII or extended ASCII or what?

**Comment by ifstatement0029** [comment]
I can confirm that I got this problem after updating to version 7.5.9 also. 

However, the corrupted content for me is always from a file open in Notepad++. Outside of that I don't have any problems copying and pasting with other software (internet browser, MS Word, etc.).
Also Notepad++ does not freeze for me. Inspite of having the files open in Notepad++ for several hours. 

My OS: Win 10 Pro. 

Sebastien 

    On Wednesday, 7 November 2018, 11:48:27 GMT, tolstiakov <notifications@github.com> wrote:  
 
 
I can report the same issue. I have multiple text files open in npp 7.5.9 32bit and clipboard content gets corrupted randomly while copying and pasting plain text between the files. The issue appeared after update to 7.5.9. Files are UTF-8, but content is plain ANSI. Amazingly, the corrupted content appears to be originating from files not currently open in npp, but present on the filesystem in "close vicinity" to the files opened in npp. The issue becomes more severe (frequent) the longer I continue to work. At one point npp froze ("Not Resonding..." message in title bar), but recovered after a minute or so (MEM/CPU usage OK, ~22Meg of RAM). OS is Win7 x64 SP1. I restarted npp and will monitor future behavior.

**Comment by MilkyWay90** [comment]
@tolstaiakov, seems like you need to upgrade to Windows 10 then

**Comment by sasumner** [comment]
> seems like you need to upgrade to Windows 10 then

This is not a useful reply.

**Comment by ifstatement0029** [comment]
I rolled back too but after seeing a different font than the usual npp font, I uninstalled npp from Apps & features (Add/remove programs). I then reinstalled the latest version of npp and have not had any issues so far. 

Sebastien 

    On Friday, 9 November 2018, 11:25:34 GMT, tolstiakov <notifications@github.com> wrote:  
 
 
New information: I rolled back to version 7.5.8 and I still have the issue. Corrupt clipboard content is outside of npp so I suspected that some obnoxious Win7 update (company policy, can't turn them off) broke the Windows clipboard, but Sebastian says he's on Win10. And I haven't noticed clipboard issues outside of npp so far. Can it be a stale file/component that still hangs around from 7.5.9? I'm lost at the moment, and the issue is persistent and annoying. If there's any debugging/logging that I could do, I'd be happy to assist if instructed.
I'm using DSpellCheck 1.4.7 btw.
PS: I'm one of those people that sleep/hibernate their computers every time, so my npp stays open for weeks, if not months (I actually restart it only when there's an update).

**Comment by ifstatement0029** [comment]
So I've been doing some more programming today using Notepad++ and noticed that when I copy and paste the following either in Notepad++ (same or new file) or in any other program (MS Word, Firefox, Paint, etc.): 
quickbarm1[mo[7],quickbarm[mo[7],3],mo[5]]

what gets pasted is this: 
qp4vtx7s6psqynry0l0llk6fllsyyrtw6s2djxrkjh

But when I copy the same thing without the ] at the end: 
quickbarm1[mo[7],quickbarm[mo[7],3],mo[5]

the same text copied gets pasted fine. 

I've also noticed that if I type from scratch the following in a web browser or MS Word, etc.:
quickbarm1[mo[7],quickbarm[mo[7],3],mo[5]]

and then copy and paste it in the web browser or MS Word, etc. I get: 
qp4vtx7s6psqynry0l0llk6fllsyyrtw6s2djxrkjh

So it seems the issue is not with Notepad++. It could be Windows. I don't know.

**Comment by tolstiakov** [comment]
Whatever we say here ain't gonna draw any attention until more people report the same issue. AFAICS so far we're alone.

When I noticed the issue first time, I had ~20 files open in npp, and I can say for sure the issue occurred within npp alone. Last two days I reduced the open files count to ~10, and the issue is less frequent (although still present). I also had some MS Office apps open like MS Word, but can't say for sure if it had any influence.

**Comment by MetaChuh** [comment]
please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins if you update from version 7.5.9 or below.
if your issue still persists, and it is still of relevance, please feel free to file a new issue as easy to understand and reproducible as possible.

thank you for your help and best regards.
