### ISSUE TITLE
Notepad++ not able to show Unicode character 266579, splits it to 2 characters

### ISSUE THREAD

**Issue by ghost** [notepad-plus-plus/notepad-plus-plus#4990]
### Description of the Issue
When I upload a Unicode character above 256, it splits it into two characters.

### Steps to Reproduce the Issue

1. Get Unicode character 266579
2. Copy it
3.  Paste in in Notepad++

### Expected Behavior

It to upload Unicode character 266579
### Actual Behavior

It split it to two characters, making the file size larger.
### Debug Information

Notepad++ v6.9.2
Build time : May 18 2016 - 00:34:05
Path : C:\Users\(my name is here)\Desktop\Programming Websites\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10
Plugins : HexEditor.dll PluginManager.dll mimeTools.dll NppConverter.dll NppExport.dll

**Comment by ArkadiuszMichalski** [comment]
I can't reproduce this. Btw, Unicode character 266579 is not to large? Last Unicode 13.0.0 covers 143,859 characters.
