### ISSUE TITLE
Add w/ BOM and remove w/o BOM in Russian locale 

### ISSUE THREAD

**Issue by SerVB** [notepad-plus-plus/notepad-plus-plus#4992]
### Description of the Issue
There is a confusion of `UTF-8-BOM` and simple `UTF-8` in the Russian localization.

This is because:
* `UTF-8` was named as `UTF-8 without BOM` (in Russian: `UTF-8 без BOM`).
* `UTF-8-BOM` was named as `UTF-8`.

So many users (that don't know what BOM is) who use Russian UI think that they should select `UTF-8` to work with simple `UTF-8` but they actually work with `UTF-8-BOM`. It has been happening for many years! Actually, I also stepped on these rakes when I started to learn programming many years ago.

I propose to change the localization file to the [English file](https://github.com/notepad-plus-plus/notepad-plus-plus/blob/f4460075e6fe6400a7d595fa82bab54693d01929/PowerEditor/installer/nativeLang/english.xml#L263) style. Now:
* `UTF-8` is named as `UTF-8`.
* `UTF-8-BOM` is named as `UTF-8 with BOM` (in Russian: `UTF-8 с BOM`).

Also I added `with BOM` (in Russian: `с BOM`) to `UCS-2` encodings (again as in the English file).

I edited only the `<all menu item>` block because the `<NewDoc>` block had been already translated properly: it has the same style (check [this block](https://github.com/notepad-plus-plus/notepad-plus-plus/blob/f4460075e6fe6400a7d595fa82bab54693d01929/PowerEditor/installer/nativeLang/russian.xml#L687)).

### PR
I don't understand the status of #4605. Is it accepted and merged or not?

**Comment by Deadooshka** [comment]
45008 - w/o BOM
45005 - with BOM

**Comment by SerVB** [comment]
@Deadooshka, yeah, I removed "w/o BOM" in 45008 and added "with BOM" in 45005.

**Comment by MetaChuh** [comment]
fixed with https://github.com/notepad-plus-plus/notepad-plus-plus/commit/2439a4eec0285fdf33f48965c126b98421bc7075
