### ISSUE TITLE
Upper case letter in auto completion does not work

### ISSUE THREAD

**Issue by abdulbadii** [notepad-plus-plus/notepad-plus-plus#4998]
Upper case letter in 'RegExp' on auto completion feature cannot show up to suggest, but work if it's in the middle, e.g. getAttributeNS

**Comment by PopeSpaceous** [comment]
Hi @abdulbadii, I just had a couple questions as I'm trying to reproduce this issue. 
Is this issue happening across all file types (eg. .html .css .cpp etc)?
Which uppercase letter is not showing up in "RegExp" the R or E?
If RegExp is already written in the file and you try to write it again using auto completion, are you doing this:
1) RegE...        or
2) rege...         or
3) Rege...        or
4) regE...         

I tested with a lower case character to start like example 2 or 4 and the auto complete won't show up. 
Please let me know, the more information the better 👍 
Thanks.

**Comment by PopeSpaceous** [comment]
Interesting.
I'm having no problem with it on my version, I'm Running v7.5.9 (32bit) On Windows 10.
Would you be able to put your version up, and if possible put a snippet or screen shot of the code?

I would like to try to reproduce this, so I'm trying to figure out the steps.
Thanks.

**Comment by ArkadiuszMichalski** [comment]
To reproduce please set only `Function completion` in `Preferences >> Auto-Completion` (for 1 char). Open new file, switch to Javascript language and write `R` char. We get `random` keyword, not Radio. 
![a](https://user-images.githubusercontent.com/2730894/93721461-c3f99e80-fb90-11ea-81e2-557ced96f2fc.gif)
![aa](https://user-images.githubusercontent.com/2730894/93721462-c65bf880-fb90-11ea-91d0-bb30a503752d.gif)
But if we check `Function and word completion` this works correct, but we get all other (unnecessary) words from current file.
![aaa](https://user-images.githubusercontent.com/2730894/93721501-058a4980-fb91-11ea-823a-0457d100c1f7.gif)

Here was similar problem for CSS https://github.com/notepad-plus-plus/notepad-plus-plus/issues/8502#issuecomment-694493689

**Comment by ArkadiuszMichalski** [comment]
@donho Any reason why Javascript does not include the above rules? In fact it's case sensitive language, and has mixed case words in `javascript.xml`.

**Comment by donho** [comment]
@ArkadiuszMichalski It seems for all languages but not only Javascript.
I'll check it.

**Comment by ArkadiuszMichalski** [comment]
https://github.com/notepad-plus-plus/notepad-plus-plus/issues/3997#issuecomment-653275244 << nice description for different Auto-Completion settings related to `ignoreCase`.

**Comment by GitMensch** [comment]
@donho said end of 2020:
> @ArkadiuszMichalski It seems for all languages but not only Javascript.
> I'll check it.

Thanks's Don for that. Any update for this and the related issue?
