### ISSUE TITLE
Copy copies wrong word in Arabic

### ISSUE THREAD

**Issue by DJDoena** [notepad-plus-plus/notepad-plus-plus#500]
This is my name just for fun in arabic:

كارستن سشرامم

It consists of two words:

كارستن
سشرامم

When you paste them as one line into Npp and then select the first one (which is the right one) and press copy, it will put the unselected second one (the left one) into the clipboard (and vice versa)

**Comment by DJDoena** [comment]
Npp 7.3.3 still does that

**Comment by DJDoena** [comment]
[https://youtu.be/vOgwZRBrqNw](video demonstrating the issue)

**Comment by Ghasan** [comment]
You will need to switch to RTL view (View > RTL) before copying it, and it works fine. But yeah, it should also work on LTR with proper directions.

**Comment by donho** [comment]
I believe this issue has been fixed since long time ago.
Update your Notepad++ to the latest version (v7.6.6).
If the issue persists, please create a new issue for it.
Thank you.

**Comment by DJDoena** [comment]
Not closed, new issue: https://github.com/notepad-plus-plus/notepad-plus-plus/issues/5504
