### ISSUE TITLE
PowerShell: Missing keywords

### ISSUE THREAD

**Issue by Paebbels** [notepad-plus-plus/notepad-plus-plus#5004]
### Description of the Issue
The PowerShell lexer doesn't recognize some (new?) keywords.

* try
* catch
* throw
* finally

#### Example 1
```powershell
try
{	Write-Host "try"
}
catch [ExceptionTyp]
{	Write-Host "catch"
}
catch
{	Write-Host "catch"
}
finally
{	Write-Host "finally"
}
```

#### Example 2
```powershell
if ($test)
{	throw "Error message"
}
```

### Expected Behavior
Show the listed keywords with highlighting

### Actual Behavior
The mentioned keywords are not highlighted.

### Debug Information
Notepad++ v7.5.9   (32-bit)
Build time : Oct 14 2018 - 15:02:52
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10 (64-bit)
Plugins : DSpellCheck.dll mimeTools.dll NppConverter.dll NppExport.dll ComparePlugin.dll MarkdownViewerPlusPlus.dll NPPJSONViewer-win32.dll nppplugin_solutionhub.dll nppplugin_solutionhub_ui.dll PluginManager.dll XMLTools.dll

**Comment by ArkadiuszMichalski** [comment]
https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_try_catch_finally?view=powershell-7.3
