### ISSUE TITLE
[Feature Request] Close unchanged tabs

### ISSUE THREAD

**Issue by frankmohaupt** [notepad-plus-plus/notepad-plus-plus#5007]
### Description of the Issue
I have a lot of tabs open in Notepad++. 
Sometimes I would like to close tabs which don't have any changes made on them.

So I'm missing the feature to close all open unchanged tabs.

### Expected Behavior
If I right-click on a tab there should be an additional option "Close all unchanged"
If I click on this option all tabs with documents which don't have any changes will be closed.

**Comment by sasumner** [comment]
Not a bad idea.  If you don't want to wait for this to be considered, accepted, implemented, and released you could consider using the Pythonscript plugin with this short script:

    for (filename, bufferID, index, view) in notepad.getFiles():
        notepad.activateFile(filename)
        if not editor.getModify(): notepad.close()

**Comment by jmbockhorst** [comment]
I can work on implementing this.
