### ISSUE TITLE
korean named font can't apply...

### ISSUE THREAD

**Issue by clonextop** [notepad-plus-plus/notepad-plus-plus#501]
Old version of this can use korean named font. (ex, 돋움체)
But newest version can't...
I don't know what is changed...
But every korean named fonts have same shape now.
Anyone can fix it?

**Comment by ardiefox** [comment]
Version 6.8.1 seems to have this issue fixed. Check the latest version out, @clonextop.

**Comment by ardiefox** [comment]
@milipili, this looks like a duplicate of #220.

**Comment by milipili** [comment]
Indeed :)
