### ISSUE TITLE
Please integrate nppgtags to notepad++ by default

### ISSUE THREAD

**Issue by prog20901** [notepad-plus-plus/notepad-plus-plus#5011]
Please integrate nppgtags to notepad++ by default

**Comment by chcg** [comment]
@prog20901 Why? You can install nppgtags with N++ 7.6 via new PluginAdmin easily.

**Comment by ArkadiuszMichalski** [comment]
@sasumner There is nice (actual) plugin https://github.com/pnedev/nppgtags and some old https://sourceforge.net/projects/gtagfornplus/?source=navbar for GNU Global. Apart from the Function List, I don't think anything new (especially external) would be added. Maybe close this bug?

**Comment by donho** [comment]
> You can install nppgtags with N++ 7.6 via new PluginAdmin easily.

Agree
