### ISSUE TITLE
Release 7.6 have broken all the plugins, including nppPluginList.dll

### ISSUE THREAD

**Issue by KOLANICH** [notepad-plus-plus/notepad-plus-plus#5014]
None of plugins work, except some shipped with npp. Even https://sourceforge.net/projects/jsminnpp/files/Uni/JSToolNPP.1.1810.3.uni.32.zip/ doesn't.

**Comment by sasumner** [comment]
This really isn't a helpful issue.  Please close and follow the discussions (and/or participate) about the new way that plugins work on this site: https://notepad-plus-plus.org/community/
