### ISSUE TITLE
Why show/hide line numbers now becoming far more difficult

### ISSUE THREAD

**Issue by abdulbadii** [notepad-plus-plus/notepad-plus-plus#5018]
Why if user want to toggle line numbers to show or hidden is far more difficult on the latest notepad++ ? I waste an hour in vain just for the damn. How to do so?

**Comment by sasumner** [comment]
What do you mean by "far more difficult"?  If someone looks at this after time goes by, "on the latest Notepad++" is meaningless (state the specific version).

**Comment by chcg** [comment]
Settings -> Preferences... -> Editing ->Display line number
Google Search https://www.google.com/search?q=Display+line+number+n%2B%2B&ie=utf-8&oe=utf-8 e.g.
https://www.bleepingcomputer.com/tutorials/how-to-show-and-hide-line-numbers-in-notepad-plus-plus/

**Comment by abdulbadii** [comment]
That's setting preference not toggling, you havent read question attentively
"user want to toggle line numbers to show/hidden.." meant at most a click or a key press!

**Comment by sasumner** [comment]
@abdulbadii So you write some short thing that confuses everyone and then you complain that they haven't read the question attentively.  Ugh.  With that kind of attitude you are lucky you get any kind of response and not just a simple closure of your ticket.  You still haven't followed directions and provided the Notepad++ version you are using.

Are you saying in that some earlier version of Notepad++ that it was possible to toggle line #s on/off in a simpler way and now it is different?

**Comment by Ekopalypse** [comment]
No response in more than 6 month I guess it can be closed.

**Comment by xylographe** [comment]
Just for the record, this can be implemented with existing plug-ins. For eample with LuaScript,
```
npp.AddShortcut("Toggle Line Numbers", "Ctrl+Shift+N", function()
      npp:MenuCommand(IDM_VIEW_LINENUMBER)
end)
```
