### ISSUE TITLE
Single step build for entire project using VS2017

### ISSUE THREAD

**Issue by dshuman52** [notepad-plus-plus/notepad-plus-plus#5028]
### Description of the Issue

Offer to provide MS solutions/projects, etc to compile notepad++ with VSExpress2017
    TO notepad++ for inclusion in the project (if desired)
              compiles both SCINTILLA and POWEREDITOR  (boost via nuget) in a single build
               appears to allow run and debug from VS2017
                          (provided dll signing is turned off for release version)
                          (I crippled dll signed load in release in my version could provide code if necessary)
               does not provide dll signing at all 
   Quirks  requires load of V140 (2015?)  c++ compiler and resources
               uses NuGet Boost library v1.68.0 (not current recommended version)
               this seems to work for me but it has not been thoroughly tested

WARNING:
I will not send this to anyone other than the Notepad++ team so they can test it appropriately before including it for others.  I cannot state this solution compiles the application completely correctly.

### Steps to Reproduce the Issue

1. 
2. 
3.

**Comment by MetaChuh** [comment]
thank you for your build offer.

> I will not send this to anyone other than the Notepad++ team so they can test it appropriately before including it for others.

don't worry, feel free to publish details about your techniques anywhere you like.

thank you for your help and best regards.

**Comment by dshuman52** [comment]
Thanks for the offer but because I no not know the full validity of my process I am not going to share what could be a faulty process with those that may not understand my limited testing.  Closing is a good idea.

    On Monday, May 6, 2019, 5:44:04 PM EDT, MetaChuh <notifications@github.com> wrote:  
 
 
Closed #5028.
