### ISSUE TITLE
highlighting and executing http link not ignoring trailing (closing) bracket

### ISSUE THREAD

**Issue by jannick0** [notepad-plus-plus/notepad-plus-plus#5029]
### Description of the Issue
* When parsing a http links a trailing closing bracket `)` is not ignored and highlighted. Moreover, the trailing bracket is passed on to the browser when double-clicking it.
* Use case: E.g., markdown syntax for web links  `[ABC](http://www.abc.com)` or web references enclosed in brackets.
* I am not sure if brackets in an URI are required to be matching acc. to the standard. 

### Steps to Reproduce the Issue

1. Type `[Google](http://www.google.com)`
2. Doube-click on link

### Expected Behavior

* Link highlighed in NPP should **not** include trailing bracket.
* Trailing bracket in link passed to browser should be discarded.

### Actual Behavior

* Link highlighed in NPP **does** include trailing bracket.
* Trailing bracket in link passed to browser *not* discarded.

**Comment by sasumner** [comment]
Possibly related to #3353

**Comment by jannick0** [comment]
- [RFC3986](https://tools.ietf.org/html/rfc3986#section-3): Uniform Resource Identifier (URI), Generic Syntax, Section 3.
- If matching brackets are the issue, recursive regular expressions could help. It might be even possible to put the formal URI definition into a lengthy regex definition (cf., e.g., [URI regular expression](jmrware.com/articles/2009/uri_regexp/URI_regex.html) ... untested).
- It would be great if someone could point (me) to the NPP code snip where the link parsing is happening (regexp, manual parsing, etc). Probably worth while looking at that in the light of the increasing usage of markdown et al. (#3353 is definitely related). Many thanks!

**Comment by PopeSpaceous** [comment]
Hi! I have been looking into this issue. 
It seems like the regular expression for finding the url in the text editor could use some work. 
Currently it is this "[A-Za-z]+://[A-Za-z0-9_\\-\\+~.:?&@=/%#,;\\{\\}\\(\\)\\[\\]\\|\\*\\!\\\\]+"
Essentially it says.
[A-Za-z]+                       ://               [A-Za-z0-9_\\-\\+~.:?&@=/%#,;\\{\\}\\(\\)\\[\\]\\|\\*\\!\\\\]+
I'll take any number of alphabetical characters until :// then any number of alphanumeric, _ -,+~.:?&@=/%#,; and brackets. 
So to fix your issue we need a better regular expression. 
I was looking into how vscode works, and I'm fairly certain they don't use just one regex to catch the url they have several. 

The other fix I was thinking of was adding a trimming function to the URLCtrl.cpp file that removes singleton brackets from the url string that it picks up. 

If anybody has any thoughts or suggestions I would be up for them. Or if you want to shoot me a better regex, I'll change it and fix it. 
Thanks

**Comment by jannick0** [comment]
Hi.

RFC3986 does not prevent any brackets in a URI, they needn't be balanced even.

Agree to the idea using a trimming function: If the regex includes any possible leading `(`, then check if there are both a leading `(` and a trailing `)`. If so, drop both of them. 

You could amend the regular expression currently in place as follows (simply prepend `(?`)
```
(?[A-Za-z]+://[A-Za-z0-9_\-\+˜.:?&@=/%#,;\{\}\(\)\[\]\|\\!\\]+
```
to have it see any potential leading `(`.

HTH.

**Comment by sasumner** [comment]
@jannick0 

> simply prepend (?

Bad form.  If I understand correctly what you are implying I think you want `\(?`

@PopeSpaceous 

>I was looking into how vscode works, and I'm fairly certain they don't use just one regex to catch the url they have several.

If you like what vscode is doing, why not put the specifics of it here so others don't have to seek it out...then it could be used as a basis for possible inclusion into Notepad++ logic (or at least as a discussion basis).

**Comment by PopeSpaceous** [comment]
@sasumner from what I found in vscode, is that they have several regex checks and they split the url up into several  parts, eg. (protocol, domain, parameters etc..) and they run each through their own regex. Then piece them together afterwards. 
I don't think this is completely necessary. 
I'm writing up some code to validate the link before creating a clickable one. Essentially trimming the end if it is "] } ) . ," 
I know I use url's when I'm typing notes in npp and sometimes use punctuation after them which in turn gets picked up in the link creation.

**Comment by sasumner** [comment]
@PopeSpaceous 

>I know I use url's when I'm typing notes in npp and sometimes use punctuation after them which in turn gets picked up in the link creation.

YES! Me, too.  I'm in the habit of doing `(` `space` `URL` `space` `)`

:-)

**Comment by jannick0** [comment]
@sasumner @PopeSpaceous 

* Just let me know if PR #5108 works for your use cases. I tested it for a small number of samples.
* Given that unmatched brackets of all sorts are allowed in a URI according to the URI standard, we cannot decide if unmatching trailing brackets are part of the URI or not.
* Inserting leading and trailing spaces should not be required any more. ;)

**Comment by PopeSpaceous** [comment]
@jannick0  Have you built notepad++ from the gitRepo on windows? I'm having a heck of a time trying to get it running.  I've been following [these notes](https://github.com/bfridkis/Building-Notepad-Plus-Plus-from-Source-A-Beginners-Guide/blob/master/Building%20Notepad%2B%2B%20from%20Source%20-%20A%20Beginners%20Guide%20-%20OPTION%20A.pdf)
But the scintilla solution has problems looking for the older versions of boost and if you remove those lines then you get "ScintillaEditview::init SCINTILLA ERROR  - Cannot load dynamic library"

Let me know if there is a better tutorial? I'm just trying to test my code.

Thanks

**Comment by PopeSpaceous** [comment]
> @sasumner @PopeSpaceous
> 
> * Just let me know if PR #5108 works for your use cases. I tested it for a small number of samples.
> * Given that unmatched brackets of all sorts are allowed in a URI according to the URI standard, we cannot decide if unmatching trailing brackets are part of the URI or not.
> * Inserting leading and trailing spaces should not be required any more. ;)

@jannick0 The code looks good. 
There are a couple test cases that I think should be considered too. 
http://google.com.    //extra period gets picked up. as well if you replaced '.' with ','
http://google.com)   //brackets still get caught if there's no leading bracket. 
I have a copy of your changes, I'll hopefully create a branch on my repo with some changes that I think could work well. 
Let me know if you get a fix for it before me.

**Comment by jannick0** [comment]
@PopeSpaceous Thanks for testing!

> http://google.com. //extra period gets picked up. as well if you replaced '.' with ','

This is doable, but let me look into the standard first before hastily implementing something.

> http://google.com) //brackets still get caught if there's no leading bracket.

This is a nasty one: What if the closing bracket is part of the URL (e.g., https://en.wikipedia.org/wiki/Saw_(2003_film))? We could look at the nested bracket level in the last path segment. Anyone with a reasonabe altenative? The github editor I am typing into right now gets this right! ;)

**Comment by PopeSpaceous** [comment]
@jannick0 the code that I was writing up had 3 regexs in it for each bracket [{()}] 
"\\[[^\\]+\\]$"  For square brackets or we loop through from the back and look for a leading bracket. 
We have options haha.

**Comment by jannick0** [comment]
@PopeSpaceous After rethinking things again, I decided to have regular expressions do the hard parsing work. So I just pushed a new implementation (#5108) from scratch using regexps (with subroutines to cope with forcedly balanced brackets). It includes the feature that the URL style is removed from a range if the URL shortened (e.g. add a `)` after `o` in `(http://abc.com)`)

In terms of performance I am not sure if scintilla cashes regular expressions, since otherwise compiling a regexp with every call with the same regexp would be redundant and time consuming.

Everyone welcome to test!

**Comment by PopeSpaceous** [comment]
@jannick0 It looks good! covers the use cases we were looking at. 
(http://abc.com))
http://abc.com)
http://abc.com.
http://abc.com,
etc...
Awesome job. 
---------------------------------------------------------------------------------------------------

Update: Halfway through writing this response. 
All the links have died and are not clickable. Not sure what was happening. 
I was testing it, was just about to post a response saying it was all good and I haven't had a problem with it, the all the links stopped being clickable. It was working great when I first started it. 
I closed and reopend npp, but only 1 link out of close to 10 valid URL's were clickable. 

I'm wondering if its taking too much computation to constantly check for url's and test their validity. 
Let me know if you can reproduce this issue.

**Comment by jannick0** [comment]
@PopeSpaceous Thanks for testing!
 
> All the links have died and are not clickable. Not sure what was happening.

Bummer: This is happening here when the document is reparsed. I removed the last commit 86aebf1 and everything was golden again.

I'll update the PR soon. I think the approach in ad7b005 needs an improvement.

**Comment by jannick0** [comment]
@PopeSpaceous Please have a look at the newly pushed version of #5108 which works well for my tests. It includes a faster approach to remove the URL style when the URL is shortened. Could you please test again? If fine then this is done.
