### ISSUE TITLE
User plugins dont stay loaded in V7.6

### ISSUE THREAD

**Issue by bronc3buster842001** [notepad-plus-plus/notepad-plus-plus#5030]
User installed plugins load with new launch of Notepad++ v7.6. Can Import them but they dont show when reopening Notepad++

**Comment by chcg** [comment]
Import issue fixed with https://github.com/notepad-plus-plus/notepad-plus-plus/commit/f03ce289d34a44671ba518273220e0785eeaed80, so with next release probably 7.6.1.

**Comment by ArkadiuszMichalski** [comment]
@bronc3buster842001 Do you still have this problem?

**Comment by donho** [comment]
Outdated.
Please reopen it if this issue can be reproduced in latest version.
