### ISSUE TITLE
Horizontal scrolling exception "vector<T> too long"

### ISSUE THREAD

**Issue by biswadeep-sarkar** [notepad-plus-plus/notepad-plus-plus#5031]
![image](https://user-images.githubusercontent.com/33215011/48693704-55e49900-ec00-11e8-95df-2b06bb56f751.png)

**Comment by sasumner** [comment]
See http://lmgtfy.com/?q=site%3Ahttps%3A%2F%2Fnotepad-plus-plus.org%2Fcommunity%2F+vector%3CT%3E+too+long

**Comment by chcg** [comment]
See https://github.com/Predelnik/DSpellCheck/issues/151

**Comment by CoR--** [comment]
Same error here. It happens ONLY if I collapse all (alt+0) in .js file.

**Comment by chcg** [comment]
@CoR--  Could you provide debug information of your installation (see N++menu ?->Debug Info ...). Which version of dspellcheck plugin do you use?

**Comment by CoR--** [comment]
I was just reading some js file. That file had 11000 chars long line of png data.
N++ was ok until I folded all (alt+0). Than everything slowed down, Exception error start popping 5 or more times as I moved horizontal scroll bar.
I tried to split png data to 1000 chars lines but same error.
Best thing was just renaming DSpellCheck.dll-no . Kill spell checker and all's well :) That spell checker should just skip too long words. There are cases with very long words. png data, cdata, url get requests, encrypted strings... 

DSpellCheck 1.4.6.0 version that came with N++ as I downloaded it.
I am not using installed N++, always .zip version in multi-instance mode.


Notepad++ v7.6   (32-bit)
Build time : Nov 12 2018 - 23:51:42
Path : D:\Soft\N++\notepad++.exe
Admin mode : OFF
Local Conf mode : ON
OS : Windows 10 (64-bit)
Plugins : DSpellCheck.dll mimeTools.dll NppConverter.dll NppExport.dll

**Comment by chcg** [comment]
@CoR-- 
See https://github.com/Predelnik/DSpellCheck/releases for updated version, which should contain a fix for the issue you observed.
With next update of the plugin list the new release will be available.

**Comment by CoR--** [comment]
Yes, that helped. Thanks!
I am sorry to say that I missed /releases link. Otherwise I would updated it myself and avoid all this trouble.

**Comment by rolinger** [comment]
I am getting the above error:

My environment:
Notepad++ v7.5.9   (32-bit)
Build time : Oct 14 2018 - 15:02:52
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 7 (64-bit)
Plugins : DSpellCheck.dll mimeTools.dll NppConverter.dll NppExport.dll ComparePlugin.dll Explorer.dll HTMLTag_unicode.dll JSLintNpp.dll JSMinNPP.dll NppEditorConfig.dll NppFTP.dll NPPJSONViewer.dll PluginManager.dll regrexplace.dll ScrollPastEOFUni.dll SpellChecker.dll XBrackets.dll XMLTools.dll 

Which version of DSpellCheck should have this fix.  Mine is v1.4.6.0

**Comment by rolinger** [comment]
nevermind, turns out I wasn't getting the updates and I was several revs behind on the Plugin Manager which was preventing me from getting latest DSpellCheck version.  Seemingly fixed now.
