### ISSUE TITLE
Feature Request: register as notepad.exe menu entry

### ISSUE THREAD

**Issue by xakepp35** [notepad-plus-plus/notepad-plus-plus#5033]
You introduced a [great way to replace notepad](https://notepad-plus-plus.org/features/replace-notepad.html). However it is "way too hard / takes long time" to open command promt and typing the commands there. Average user should not bother with running command line as admin and typing magic text there. That is what we, programmers, are for! So I think it would be a great feature to automate this.

You may have these 2 commands in menu, for example "**?**", or under "**settings>preferences**".
That may be implemented like 2 menu lines or buttons, like "**register as notepad.exe**" and "**restore notepad.exe**"
Or even some simple detection code: 

	// todo: add some error checking ;-)
	HKEY hk;
	const auto npKeyPath[] = TEXT("SOFTWARE\\Microsoft\\Windows NT\\CurrentVersion\\Image File Execution Options\\notepad.exe");
	if(RegOpenKeyEx(HKEY_LOCAL_MACHINE,npKeyPath, 0,KEY_QUERY_VALUE, &hk ) == ERROR_SUCCESS ) {
		RegDeleteKeyW(hk);
		RegCloseKey (hk);
		MessageBox(0, TEXT("Original notepad.exe restored"), TEXT("notepad++"), MB_ICONINFORMATION);
	}
	else {
		RegCreateKey(HKEY_LOCAL_MACHINE, npKeyPath, &hk);
		//TCHAR szFileName[MAX_PATH + 1]; // = TEXT("C:\Program Files\Notepad++\notepad++.exe");
		//GetModuleFileName(NULL, szFileName, MAX_PATH + 1);
		TCHAR data = TEXT("\"C:\\Program Files\\Notepad++\\notepad++.exe\" -notepadStyleCmdline -z";
		RegSetValueEx(hk, TEXT("Debugger"), 0, REG_SZ, data, _tcslen(data));
		MessageBox(0, TEXT("Replaced notepad.exe with np++"), TEXT("notepad++"), MB_ICONINFORMATION);
	}

ALSO! to mention this could require admin rights. AS WELL AS shell extenstions registration. 
Yes, a bit offtopic (can create separate issue) but i will post it here for now, as it is closely related to elevation.

"**Preferences>>Settings>>File Assiciations**" was always great source of PITA: 

1. Run app **not** as admin (I am not seeing a hint to "runas admin" anywhere!)
2. Spend next 10-15 minutes adding extensions (thinking what to open with it, navigating submenus..)
3. press "close" and close app
4. PROFIT!!! nothing was saved! try to feel calm.. ;-)

There are two solutions:
	
* "foobar2000 way" - is to open file associations menu. [Should look like this](https://news.softpedia.com/images/extra/WINDOWS3/large/foobar2000/foobar2000%20file%20type%20manager.png)
* notify user ad try to elevate. [And a code which shows this approach](https://www.codeproject.com/Articles/320748/Haephrati-Elevating-during-runtime)
	
Second approach could also allow registry tweak, featured above.

**Comment by MetaChuh** [comment]
we prefer this option as hidden as it is, to avoid inexperienced users to accidentally mess up their system.

best regards.
