### ISSUE TITLE
Extensions are not visible for Users

### ISSUE THREAD

**Issue by Basti890** [notepad-plus-plus/notepad-plus-plus#5038]
### Description of the Issue
When installing Notepad++ silent under User A and than logging in as new User B, there is no Extension option.

### Steps to Reproduce the Issue
1. Installing Notepad++ silent wit Parameter "/S" and controll Installation (start notepad++)
2. Loggin with an other domain User and start notepad++
3. No Extension (Plugin) Option is visible and 

### Expected Behavior
![new issue notepad-plus-plus_notepad-plus-plus - firefox enercity edition esr 5-2018-11-20 09_46_12](https://user-images.githubusercontent.com/11937981/48761713-9ba96c00-eca9-11e8-9952-bd4ee5c4742f.png)

### Actual Behavior
![c__users_public_desktop_viclient_testmodus cmd - notepad administrator -2018-11-20 09_43_57](https://user-images.githubusercontent.com/11937981/48761750-b380f000-eca9-11e8-9d2d-6db13a3e5e3e.png)

#### Expected Behavior Debug:
Notepad++ v7.6   (32-bit)
Build time : Nov 12 2018 - 23:51:42
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : ON
Local Conf mode : OFF
OS : Windows 7 (32-bit)
Plugins : DSpellCheck.dll mimeTools.dll NppConverter.dll NppExport.dll 

#### Actual Behavior Debug:
Notepad++ v7.6   (32-bit)
Build time : Nov 12 2018 - 23:51:42
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : ON
Local Conf mode : OFF
OS : Windows 7 (32-bit)
Plugins : none

**Comment by Basti890** [comment]
Oh what i forgot to mension, the Plugins are copied via active setup into the useres %appdata%\Notepad++ Pluginsdir

**Comment by chcg** [comment]
Known issue with plugin admin related changes, see https://notepad-plus-plus.org/news/notepad-7.6-released.html. For the dicussion see https://notepad-plus-plus.org/community/topic/16645/new-plugins-home-where-notepad-will-load-from and https://notepad-plus-plus.org/community/topic/16621/notepad-7-6-new-plugins-admin

**Comment by MetaChuh** [comment]
the 7.6 issue of missing plugins for other users, on the same machine, has been fixed in newer versions of notepad++.

please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins if you update from version 7.6.

thank you for your help and best regards.
