### ISSUE TITLE
Codex with Version 7.6 (Germany) wrong!

### ISSUE THREAD

**Issue by Tomcatfhw** [notepad-plus-plus/notepad-plus-plus#5040]
Hi all,
i have codex problems with Notepad++ from Version 7.6, the old 7.5.9 works without this codex problem.

### Description of the Issue
from Version 7.6, I see Codex "ISO 8859-3"
In Version 7.5.9 I can see "ANSI" <= That is correct, an other editor tells me also it's "ANSI"

### Steps to Reproduce the Issue
1. Read wir Notepad++ 7.5.9 and can see Codex "ANSI" is okay and conform with another editor.
2. I deinstall Notepad++ and install Version 7.6, I open the same file and see Codex "ISO 8859-3", but is incorrect it's "ANSI"

### Expected Behavior

Correct Version in Codex "ANSI" not the Unknown Codex "ISO 8859-3"

### Actual Behavior

By Version 7.6 I see the most time a ISO Code, but nor "ANSI", ANSI is correct

### Debug Information

Notepad++ v7.6   (64-bit)
Build time : Nov 13 2018 - 00:12:05
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10 (64-bit)
Plugins : DSpellCheck.dll mimeTools.dll NppConverter.dll

![grafik](https://user-images.githubusercontent.com/45198599/48773429-a1ae4580-ecc7-11e8-9ee5-a0af1ba494d0.png)

**Comment by Tomcatfhw** [comment]
The problem is third with a lot of different files

**Comment by chcg** [comment]
See https://www.freedesktop.org/wiki/Software/uchardet/. This component is used to predict which type of file you have depending on the chars found in the text. See https://de.wikipedia.org/wiki/ISO_8859-3, so maybe some turkish/esperanto chars are part of your text. Could that be the case? 

What is your setting under 
settings -> preferences ... -> New Document?
![grafik](https://user-images.githubusercontent.com/12630740/48792445-93c2e980-ecf4-11e8-8f4c-11ad22e1ef7e.png)

**Comment by Tomcatfhw** [comment]
Hi thanks for answer,

I don't think so, the older Versions works also perfect, but if I update to version 7.6 I have problems with the codexindication, but only in version 7.6.

In version 7.6 it was the same setting, but I use now 7.5.9 because I have very trouble with the codexindication...
![grafik](https://user-images.githubusercontent.com/45198599/48831157-8d755180-ed76-11e8-9fa5-5443e74bdd1d.png)

**Comment by MetaChuh** [comment]
fixed in https://github.com/notepad-plus-plus/notepad-plus-plus/commit/486e2188b2d4f5e897d5ffffa9b3dcd23b3ae2d6
