### ISSUE TITLE
NP++ freeze / increase memory usage when decoding specific base64 string (MIME TOOLS)

### ISSUE THREAD

**Issue by ro0ter** [notepad-plus-plus/notepad-plus-plus#5042]
### Description of the Issue
Notepad++ was opened with several documents, about 150mb of ram used...

### Steps to Reproduce the Issue

1. navigate to https://wiki.openssl.org/index.php/Command_Line_Elliptic_Curve_Operations
2. copy the first block of base64-encoded string - e.g.:
MIIBIAIBAQQYd8yhaE899FaH3sw8aD4F/vtpMVBLfVqmoIHKMIHHAgEBMCQGByqG
SM49AQECGQD////////////////////+//////////8wSwQY////////////////
/////v/////////8BBgiEj3COVoFyqdCPa7MyUdgp9RiJWvVaRYDFQDEaWhENd6z
eMS2XKlZHipXYwWaLgQxBH0pd4EAxlodoXg3FliNziuLSu6OIo8YljipDyJjczcz
S0nctmptyPmXisp2SKlDsAIZAP///////////////3pi0DHIP0KU9kDsEwIBAaE0
AzIABBsl8ZSGJqcUpVoP8zekF92DGqDBMERcHhCXmgPXchP+ljybXbzYKINgxbp5
0g9/pw==
3. Paste it into a new Notepad++ document

### Expected Behavior
simply decode it... Plugins < MIME Tools > Base64 Decode

### Actual Behavior
np++ decodes it but it stops responding.. eventually it reaches 2gb+ of ram (when entire system starts to be unresponsive), barely got my back saved by killing np++, task manager started very slowly...
after restart, np++ has the (untitled) document with the decoded string... no phishy behaviour this time..

### Debug Information
Notepad++ v7.5.6   (64-bit)
Build time : Mar 19 2018 - 00:23:17
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : ON
Local Conf mode : OFF
OS : Windows 7 (64-bit)
Plugins : BetterMultiSelection_64.dll ComparePlugin.dll DSpellCheck.dll mimeTools.dll NppConverter.dll nppcrypt.dll NppExport.dll NppGTags.dll NPPJSONViewer.dll NppJumpList.dll NppQrCode64.dll NppToolBucket.dll NppXmlTreeviewPlugin.dll PluginManager.dll PythonScript.dll SelectQuotedText.dll SurroundSelection_64.dll 

![base64 encoded string.txt](https://github.com/notepad-plus-plus/notepad-plus-plus/files/2599857/base64.encoded.string.txt)
![screenshot-2018-11-20--15-21-07](https://user-images.githubusercontent.com/10808665/48776881-b8f62e80-ecd9-11e8-9bee-090ee42eeab8.png)
![screenshot-2018-11-20--15-21-50](https://user-images.githubusercontent.com/10808665/48776896-c7444a80-ecd9-11e8-93b7-258a8719dc2f.png)
![screenshot-2018-11-20--15-22-43](https://user-images.githubusercontent.com/10808665/48776906-d0cdb280-ecd9-11e8-8f2c-dab21be7869a.png)

**Comment by chcg** [comment]
As this is a mime tool issue the right place is https://github.com/npp-plugins/mimetools/issues.
@ro0ter Could you please move the issue to the plugin queue.

**Comment by ro0ter** [comment]
chcg - how do I do that? There seems to be no easy way..

**Comment by ro0ter** [comment]
Still reproducible with mimeTools 2.1 (npp7.6):

Notepad++ v7.6   (64-bit)
Build time : Nov 13 2018 - 00:12:05
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : ON
Local Conf mode : OFF
OS : Windows 7 (64-bit)
Plugins : DSpellCheck.dll mimeTools.dll NppConverter.dll

**Comment by mak0t0san** [comment]
I am running into the same issue and this does not seem to be plug-in related.  This happens in UTF-8 encoding, but is fine in ANSI.  Here's another way to reproduce this issue:
"Encoding -> Encode in ANSI", then paste in the Base64 text from the example given in this issue.  Base64 Decode the text.  Everything should be fine so far.  Now change the encoding to UTF-8 ("Encoding -> Encode in UTF-8"), then start typing.  It will freeze when you start typing.

**Comment by MetaChuh** [comment]
closed due to:
triggered by a combination of DSpellCheck and MIME Tools.
not reproducible on notepad++ 7.6.6 with MIME Tools 2.5 with or without the now optional DSpellCheck 1.4.10.
not reproducible on older notepad++ version 7.5.6 without DSpellCheck.
