### ISSUE TITLE
Line numbering broken when folding functions

### ISSUE THREAD

**Issue by pohar** [notepad-plus-plus/notepad-plus-plus#5043]
### Description of the Issue

Line numbering broken, sometimes only the last 3 digits are clearly visible.

### Steps to Reproduce the Issue

1. Open a C source file, which is more than 1000 lines
2. Fold some functions (before line 1000)
3. Goto line 1000 and see the numbering
4. If you scroll down, then the numbering is good (for me it is after line 1300)
5. Unfold some function, numbering might be fixed

### Expected Behavior

All digits of line number are visible

### Actual Behavior

After folding some functions in a C source file, the line numbering broke around line 1000

### Debug Information

Notepad++ v6.2.2

**Comment by dail8859** [comment]
Your version is 6 years old.
