### ISSUE TITLE
FunctionList PHP parser can't handle abstract classes with abstract functions

### ISSUE THREAD

**Issue by TutoInformatik** [notepad-plus-plus/notepad-plus-plus#5045]
### Description of the Issue
FunctionList doesn't work with abstact function and classes (ie missing some abstract functions and functions) 

Sample PHP code :
`
abstract class PageGrille extends PageMotsBleus{
	abstract function GetTypeGrille() ;  // blabla blabla
	abstract function GetGrilleJSON($p_grilleId);  // Retourn  JSON 
	
	function CleanStr($pStr){
		return str_replace ( "\\" , "" , $pStr);
	}
	
	function GetJavascriptMajax() {
		return "ABC";
	}
}
`

**Comment by donho** [comment]
@TutoInformatik Do you mind I integrate your parser and adding the Unit-tests, or you wanna do by yourself?
