### ISSUE TITLE
Syntax highlighting not applied in some cases

### ISSUE THREAD

**Issue by niente0** [notepad-plus-plus/notepad-plus-plus#5046]
### Description of the Issue

Sometimes syntax highlighting is not applied to file even if it should

### Steps to Reproduce the Issue

1. **Right-click** on a HTML file and select "Open with Notepad++"
2. After file is opened in N++, go back to Windows Explorer and this time **left-double-click** on another html file
3. If you drag-n-drop the same file on N++ (instead of double-clicking on it), syntax is highlighted correctly

### Expected Behavior

Syntax highlighting is applied also on second file opened

### Actual Behavior

Syntax highlighting is not applied to second file

### Debug Information

Notepad++ v7.5.9   (32-bit)
Build time : Oct 14 2018 - 15:02:52
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10 (64-bit)
Plugins : DSpellCheck.dll mimeTools.dll NppConverter.dll NppExport.dll ComparePlugin.dll NppFTP.dll NppTextFX.dll PluginManager.dll WindowManager.dll 

![screenshot2](https://user-images.githubusercontent.com/168951/48905912-179ae400-ee63-11e8-8264-829e3aa21b1c.png)

**Comment by ArkadiuszMichalski** [comment]
Looks like simillar to https://github.com/notepad-plus-plus/notepad-plus-plus/issues/4883
@niente0 Can you confirm that this isue is still presents?

**Comment by donho** [comment]
Outdated.
Please reopen it if this issue can be reproduced in latest version.
