### ISSUE TITLE
plugin menu do not show if not admin user.

### ISSUE THREAD

**Issue by thinksource** [notepad-plus-plus/notepad-plus-plus#5048]
I try to use as normal user of windows system. But there is no plugin menu only I switch to admin user I can see the plugins.
maybe some plugins can not use for normal user but like I just want to use compare why it can not work.

### Description of the Issue
plugin menu do not show if not admin user.

### Steps to Reproduce the Issue
1. user normal user
2. no plugin menu

![image](https://user-images.githubusercontent.com/2766693/48963005-be0af480-efdd-11e8-9c5b-2321934cf320.png)

### Expected Behavior
have plugin menu but disable some plugins which need admin authority.

### Actual Behavior
No plugin menu show

**Comment by MetaChuh** [comment]
please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html).

if your issue still persists for non admin users, please visit us at our notepad++ community for installation help on your system (link at the bottom).

thank you for your help and best regards.

-----
```
general notes:

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).
please file an issue as easy to understand and reproducible as possible.

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
(no extra account is needed, just use your github account to sign in)
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)
