### ISSUE TITLE
Feature Requests: Drop to Find Dialog and Find Prev Button

### ISSUE THREAD

**Issue by ottovonfrankfurt** [notepad-plus-plus/notepad-plus-plus#5049]
I'm referring to recently downloaded Notepad++ v7.5.9 and have 2 "minor" requests.

I'm very new to Notepad++ and see Drag/Drop works well for loading files.
Kudos to the development team... I'm loving it so far

1.) Add Drop to the Find Dialog:
I can't Drag/Drop to/from the Find Dialog combos.

I use a lot of complex regex and normally develop (ie. think) in another text file, then copy/test.
It just helps keep my mind straight and I can make extensive notes.
It would be great if I could Drop text to the Find/Replace boxes vs. copy/paste.

2.) Add Find Prev Button:
Shift-F3 works very well, but I have to focus the text first.
It would be very handy to have a Find Previous button on the dialog. There appears to be room for it.

I would suggest between the "Replace" and "Replace All" buttons to avoid my wandering mouse.
I work on multiple screens and typically concentrate on the text, ignoring the mouse cursor.
"Find Prev" would be used much less and I would be watching more closely as well.

These are just handy features, but they would save a lot of clicks, time, and aggravation over an 8-hour shift.

Sometimes it's the "little things" that separate good work from the really great.

I would appreciate your consideration, and again, kudos...

**Comment by chcg** [comment]
ad 2, You could activate the two button mode with the checkbox next to find next and get:

![grafik](https://user-images.githubusercontent.com/12630740/48967463-2ad3be00-efe1-11e8-97f7-eceaf2262b76.png)

**Comment by ottovonfrankfurt** [comment]
Sorry about that, I just noticed it and was about to edit my post. 

It seems the tooltip doesn't always display, or maybe just once per session (yea! I'm not real fond of them either). 
Buttons are perfect just the way they are. Anyway thanks for the heads-up.

Are there any plans for drop to the comboboxes?

Another REALLY picky thing I noticed is the active area for the left 4 checkboxes extends nearly to the right edge of the "Search Mode" group box. It's just a nasty habit I have ...clicking in open areas... and I inadvertently turned Match Case off. There's a sizeable area there that isn't really "open".

**Comment by sasumner** [comment]
>Sometimes it's the "little things" that separate good work from the really great.

Yes, but we have to keep in mind that what one person thinks is "great", other people might think "not so much".  :-)

Your feature request for dropping remains, but let's leave that as the SINGLE request for this issue (easier to work with that way if it is ever to be acted upon).  If you have other unrelated requests, open new issues.

> I noticed is the active area for the left 4 checkboxes extends nearly to the right edge of the "Search Mode" group box

The reason for this is that different languages may have words describing the characteristic that are of different length than the words in your language.  Also, these fields are customizable by the end-user to say anything you want; the space is there for that as well.  Not sure how difficult it would be for the code to detect the screen-size of the text currently active and then reduce the click-area to just that size...but again, this would be a separate/new issue from the current one.

**Comment by ottovonfrankfurt** [comment]
Got it, and I fully understand.
Now that I know, I'll try to avoid my self abuse.

Thanks again... Great job, and great responses!

**Comment by sasumner** [comment]
It made no sense to close this; you had a perfectly valid feature request in the "drop" stuff.

**Comment by chcg** [comment]
@sasumner #5050 was created with the first point
