### ISSUE TITLE
Feature Request: Drop to Find/Replace Dialog

### ISSUE THREAD

**Issue by ottovonfrankfurt** [notepad-plus-plus/notepad-plus-plus#5050]
I'm referring to recently downloaded Notepad++ v7.5.9 and have a minor request.

I'm very new to Notepad++ and see Drag/Drop works well for loading files.
Kudos to the development team... I'm loving it so far

Add Drop to the Find Dialog:
I can't Drag/Drop to/from the Find Dialog combos.

I work with a lot of complex regex and normally develop (ie. think) in another text file, then copy/test.
It helps keep my mind straight and I can make extensive notes.
It would be great if I could Drop text to the Find/Replace boxes vs. copy/paste.

**Comment by sasumner** [comment]
Copy/paste suffices.
