### ISSUE TITLE
Improve Backup

### ISSUE THREAD

**Issue by vertigo220** [notepad-plus-plus/notepad-plus-plus#5053]
I like to backup settings for programs to make them easier to set up on other computers, and preferably on my (secondary) data drive vs the OS drive. I've found N++ to be lacking in this regard. Here's what I've found, and my suggestions to make it better:

- Not all of the settings are included in the config.xml file, and therefore backed up. For example, the cloud settings (enabled/disabled and location) aren't included, nor is the selected theme. And there are quite possibly others. Also, layout configurations aren't included AFAICT (e.g., panels/panes, such as document map). So most, but not all, of the configuration will be carried over to a new install.

- Some things are stored in the cloud location (config.xml, langs.xml, stylers.xml, and possibly some other xml files) but others aren't (session.xml, themes). This caused me to lose the color configurations I'd done, because I assumed they were included in the files stored in the cloud location. Basically, this means that even when using the cloud option you still have to manually back up some things, which makes the cloud function _almost_ pointless. All configuration files should be stored in the cloud location.

- The "Preferences > Backup > Session snapshot and periodic backup" path should be able to be configured independently instead of being based on the cloud directory. If I use the cloud feature, it means I can't have a N++ folder with a "Settings" and a "Backup" subfolder, since the "Backup" folder is automatically under the main N++ cloud folder (which would be the "Settings" folder in my scenario, ideally). And while that's a minor issue, which simply prevents me from organizing things in my preferred manner, the bigger problem is that I can't disable the cloud feature, due to the previous issue, and still keep the file backups on my data drive. Because of the resulting scattered files from using the cloud feature, I thought I'd just leave them in the AppData directory and periodically back them up, but then my concern is if my OS drive fails, I'll lose any unsaved work. But in order to have those files backed up to my data drives (two mirrored drives), I _have_ to use the cloud feature. So I either have to have all files in one place, on the OS drive, with no realtime backup, or I have to scatter the files so I can have the backup. And again, it makes no sense that session.xml is kept in the AppData directory, since the settings dialog implies it would be stored in the backup path, which is where it would make sense to be stored.

I've also lost files before due to not saving them and relying on the session backup but then having it not work. At least once, when checking the settings in trying to figure out why it didn't work, I found that, despite having previously checked the "Enable session snapshot and periodic backup" option, it was no longer checked. And I wonder if the reason for this is because of the scattered settings files causing me to accidentally replace/overwrite some of them. Regardless, it's unfortunately caused me to lose confidence in N++'s ability in this regard.

**Comment by mpratt14** [comment]
*bump*

I think it's essential that a rolling log of session.xml is saved in the specified cloud folder. The date at time the file is generated can be appended to it. It can be done exactly the way that backup-on-save is done.

**Comment by mpratt14** [comment]
@chcg I would be willing to file the pull request to apply some of these things if I could figure out which part of the source code is for the cloud backup function...

**Comment by TehPsychedelic** [comment]
I would add I have two computers using Notepad++ installable version. On one of them, it seems the "Enable session backup and periodic backup" setting stays forever, I have unsaved tabs there from last year so let's say I trust that one 100%.
However on a work laptop, the setting seems to reset whenever it wants (normally after a blue screen or an automatic reboot for updates) so I have ended up losing myriads of info, so much, I've started to just use OneNote since I cannot rely on notepad++ backup feature.

**Comment by TehPsychedelic** [comment]
Nope, I don't. In neither, I use multiple instances.

However, yesternight I found out something after writing my reply: On the desktop, I have been running a portable installation AND saving to the cloud (I had forgotten).
So immediately I tried that configuration on the work laptop (portable + cloud) and it may seem as I got bingo and the settings persist. Maybe something to do with being in the cloud the app is not able to bug out on the file streams before forcibly being shut down vs local harddrive. Also unlike the OP with a portable installation maybe there is something special regarding permissions (vs program files folder on a regular install) that doesn't allow the app to bug out when saving or dealing with whatever settings are local and not in the cloud.

**Comment by vertigo220** [comment]
Since posting this, I've lost files multiple times due to having unsaved files not be there after reboot and, just recently, lost my entire session after a Windows update. Just checked and the 'Enable session snapshot and periodic backup' setting was unchecked, AGAIN. Fortunately, I had saved the session a couple months ago, so I got most of the tabs back, but I'm sure there's one or two that were added since that I forgot, and I don't even remember if I had any unsaved tabs that are now lost. I've lost all faith in N++ at this point and am again looking for a replacement. I've lost more work and notes from using N++ than any other program, and it would be foolish to continue.

**Comment by sasumner** [comment]
@vertigo220 Sorry to hear about your troubles.  I know you're "moving on", but had you considered simply not using the feature that allows you to exit with unsaved tabs?  After some data loss years ago, I decided that feature simply wasn't something I wanted to continue to use.  Sure, it's a feature, and it should work right, but...  Anyway, cheers and good luck.

**Comment by TehPsychedelic** [comment]
@vertigo220 give portable mode a go (make sure after that there is nothing on x:\program files\xxxx and %appdata% -shouldn't be). As you can see by my replies it seems portable + cloud (from OP you already mentioned cloud to be enabled) seems to be somewhat stable for session backup. You could even try to have the portable installation directly running from cloud drive (but it could be potentially buggy if you open it twice from different computers).

**Comment by afwn90cj93201nixr2e1re** [comment]
Could i ask something?
![изображение](https://user-images.githubusercontent.com/9306996/100398126-10f06a00-3045-11eb-83e0-35293fd87914.png)
Like c'mon... Isn't better (i guess you are already setting them, but...) to set changed date to same as creation date? Sometimes they are completely different.

![изображение](https://user-images.githubusercontent.com/9306996/100398188-5876f600-3045-11eb-8990-2468d2c7bd37.png)


Any thoughts?
@donho

**Comment by afwn90cj93201nixr2e1re** [comment]
https://github.com/notepad-plus-plus/notepad-plus-plus/blob/d80816f930c41d6dbb40a2ef689a071c38d025c2/PowerEditor/src/ScitillaComponent/Buffer.cpp#L850-L914


So, i guess we should add SetFileTime https://docs.microsoft.com/fr-fr/windows/win32/api/fileapi/nf-fileapi-setfiletime.

**Comment by afwn90cj93201nixr2e1re** [comment]
@dail8859

**Comment by dail8859** [comment]
@afwn90cj93201nixr2e1re

Hello

**Comment by afwn90cj93201nixr2e1re** [comment]
xD

**Comment by dail8859** [comment]
@afwn90cj93201nixr2e1re 

Personally I dont use the backup features myself so I'm not very familiar how they work.

If you feel you can make improvements to the code feel free to open a pull request.

**Comment by afwn90cj93201nixr2e1re** [comment]
Tbh, im not sure that this is gonna be accepted, can ask donho about it? Coz for me it's seems like a typo/mistake/forgotten stuff. 


And one more, do u planning to get old installation parameters on update stage? Coz it's also annoying...

**Comment by dail8859** [comment]
> Tbh, im not sure that this is gonna be accepted

I'm not sure either. I haven't given it any thought what the correct behavior should be. 


> And one more, do u planning to get old installation parameters on update stage? Coz it's also annoying...

Not sure what you are referring to.

**Comment by afwn90cj93201nixr2e1re** [comment]
> Not sure what you are referring to.

Like where there's an update notification, and we r pressing process, then installer ask us to choose dir and blablabla, and we should reset all of those specific stuff every time, it's anoying when u r using different settings than original one.

@donho, any thoughts about files? Could i delete my comment? Did u fully read that?

**Comment by dail8859** [comment]
Why delete all your posts??
 
 
  On Fri, Nov 27, 2020 at 8:48 PM, shel<notifications@github.com> wrote:   


Tbh, im not sure that this is gonna be accepted, can ask donho about it? Coz for me it's seems like a typo/mistake/forgotten stuff.

And one more, do u planning to get old installation parameters on update stage? Coz it's also annoying...

**Comment by afwn90cj93201nixr2e1re** [comment]
I guess you already sam them, that's why.

**Comment by donho** [comment]
@afwn90cj93201nixr2e1re 
> @donho, any thoughts about files?

I just checked my backup files and their dates are set correctly so I have no idea about it. Maybe the horologe of your PC has been changed?

**Comment by afwn90cj93201nixr2e1re** [comment]
No man (it's couldn't became changed at random points, right? As you could see there's some chance of getting this issue at random files i guess), as i showed there's random file with different CHANGEd dates, which are less than creation date, so i suggested to manually set create/edited/changed date to current/created date on backup creation one more time.
https://docs.microsoft.com/fr-fr/windows/win32/api/fileapi/nf-fileapi-setfiletime

There's screenshot, one more time:

![image](https://shelru.ru/2.png)

I guess windows just don't gurantee that changed date gonna be set properly as creation one without manual setting.

There's mine settings:

![image](https://shelru.ru/3.jpg)

**Comment by afwn90cj93201nixr2e1re** [comment]
I accidentaly got my old mozilla session, lol...
![image](https://shelru.ru/4.png)

So, here's backup.

**Comment by vertigo220** [comment]
I looked a while back for a replacement to N++, and while I found one very promising candidate (Atom, I think, though it's been a while), it had a long unresolved issue involving data loss, and I didn't want to leave one program due to that issue only to go to another with a similar issue, possibly even worse. So, against my better judgement, I've stuck with N++ the past couple years, and so far haven't had any more issues (knock on wood). I don't know if it's because there was some random glitch or bug that caused the session snapshot option to be randomly unchecked or, more likely I suspect, because after spending a good bit of time getting everything set up properly and really figuring out the complex web of settings files, I've got everything how it needs to be, whereas before I probably inadvertently changed something.

This leads me to a few points:

- I did not, as suggested by @sasumner, try disabling the feature that allows for exiting with unsaved tabs, because I use that feature a lot, not to mention I appreciate the protection afforded by it when the computer crashes (or Windows decides it wants to restart to apply updates, my own preferences on the matter be damned).
- Assuming my problem before, which happened multiple times, was indeed my fault due to replacing or moving files without fully understanding which files where did what, that just goes to show how important it is to simplify things, so users can more easily figure it out and, more importantly, don't screw it up trying to do what should be simple.
- I wrote a batch script to go through and back up all the various settings, as well as one to restore them (for setting up on a new computer or after a fresh install), and also made a scheduled task for backing up the unsaved files regularly to help prevent issues related to N++ losing those. I'd like to share these so others can use them (they should be fairly universal, though no guarantees), but not sure what the best way to do it is. Should I just copy/paste them into code blocks? Or should I change the extension to .txt and upload the files?

**Comment by Korb** [comment]
Maybe it would be appropriate to turn on the list of what will be included in backup? By analogy, how in Mozilla Firefox the user chooses what is included in the cloud synchronization:

> Choose What To Sync
> Changes to the list of items to sync will be reflected across all your connected devices.
> 
> - Bookmarks
> - History
> - Open tabs
> - Passwords
> - Payment methods
> - Add-ons
> - Settings

On the one hand, the user will receive a clear list of what, in principle, can be saved, and can include some data for backup, not including the rest.

**Comment by donho** [comment]
The backup has been improved in the previous versions.
And also it seems the issue https://github.com/notepad-plus-plus/notepad-plus-plus/issues/6133 has been fixed by https://github.com/notepad-plus-plus/notepad-plus-plus/commit/bbeaafac8bde911d3268f2d40b90329feb5c57f4
