### ISSUE TITLE
Feature request: F3 opens find dialog window.  Thanks.

### ISSUE THREAD

**Issue by somebadhat** [notepad-plus-plus/notepad-plus-plus#5054]
F3 opens find dialog window.  Thanks.

**Comment by sasumner** [comment]
Notepad++ gives you the capability to remap the key combos at the user level.  See Settings (menu) -> Shortcut Mapper...

PLEASE CLOSE THIS ISSUE as a non-issue.

**Comment by dinkumoil** [comment]
@somebadhat 

To open _Find_ dialog press _Ctrl+F_. The _F3_ shortcut is in Windows programs commonly used as "Continue search" and **not** as "Start search". If you don't like that you can change the shortcuts to your needs, like @sasumner already wrote.

Please close this issue.

**Comment by somebadhat** [comment]
THANKS.
