### ISSUE TITLE
Installation(s) destroyed by 7.6 update

### ISSUE THREAD

**Issue by CollinChaffin** [notepad-plus-plus/notepad-plus-plus#5058]
I literally have re-written this issue so many times I'm just opening it with this - this zero backward compatible move to whole new totally unneeded complex plugin structure, killed all our working NPP installs.  Mass rollbacks to 7.59 have been the answer for now.

**Comment by MetaChuh** [comment]
we apologise for your experience.
however 7.6 was never released as an auto update, and the official download page clearly stated the changes. 

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)
