### ISSUE TITLE
Show All Characters

### ISSUE THREAD

**Issue by JonathanRowell** [notepad-plus-plus/notepad-plus-plus#5062]
### Description of the Issue

Using UTF8 files without a BOM. If one creates a file with a BOM sequence somewhere in the file, the Show All Characters command does not show the BOM or any other indication that the file is corrupt.
### Steps to Reproduce the Issue

1. Create a file without a BOM
2. Create a second file with a BOM
3. Copy the second file onto the end of the first and save. Then reload and call up "Show All Characters".

### Expected Behavior

Some indication of the EF BB BF sequence in the middle of the file.
### Actual Behavior

No indication, so one thinks that the file is OK.

**Comment by sasumner** [comment]
The situation described is a Scintilla limitation so I'm tagging this issue as such.
I'm also closing as I doubt Scintilla will ever support showing this situation without additional intervention (such as below).

But, this link will show a method for having this situation be shown to the user, as a ZWNBSP character:
https://community.notepad-plus-plus.org/topic/14045/invisible-characters-unwanted

**Comment by donho** [comment]
FYI: the BOM is read by Notepad++, and it remove it, put the rest content into Scintilla and tell Scintilla how to interpret the content according the read BOM.
If user need to see the BOM (normally they don't need because Notepad++ shows which kind of data is interpreted on the status bar), they can use tier plugin (ie. HexEdit) to get the info of 3 bytes.

**Comment by sasumner** [comment]
@donho 
I had added the Scintilla dependent label because the user wanted to _see_ the hex characters generated from this "BOM" (which is no longer a BOM after what the user did to it in the STR).  Because these bytes are actually a ZWNBSP (Zero Width Non Breaking Space) when they occur in the middle of a document, and Scintilla normally doesn't display that.  Personally, I think Scintilla _should_ show zero-width characters by default.  That's all.

**Comment by donho** [comment]
@sasumner At this viewpoint, you're right, I'm adding this label back.

**Comment by sasumner** [comment]
@donho 

What do you think about an option to show such zero-width characters for UTF-8 encoded files?
I think showing the user what is really in their data is always a good idea (well, except for line-endings unless you REALLY want/need to see them).

With the option turned on it could look like this:
![image](https://user-images.githubusercontent.com/30118311/94340514-6e7a2300-ffd0-11ea-96b1-97c81da0d8ec.png)

(not the cyan in the last line, oops)

**Comment by JonathanRowell** [comment]
> What do you think about an option to show such zero-width characters for UTF-8 encoded files?
I think showing the user what is really in their data is always a good idea (well, except for line-endings unless you REALLY want/need to see them).

It IS a good idea, particularly if you are doing cross platform development - Linux, Windows and Mac

**Comment by sasumner** [comment]
>It IS a good idea, 

Thanks. :-)

>particularly if you are doing cross platform development

I'm not sure what that has to do with it.
Files are files are files...

**Comment by donho** [comment]
@sasumner 
> What do you think about an option to show such zero-width characters for UTF-8 encoded files?
I think showing the user what is really in their data is always a good idea (well, except for line-endings unless you REALLY want/need to see them).

As I said "too many options, no option". So let's keep the current behaviour.

**Comment by sasumner** [comment]
>"too many options, no option"

No, you seem to like (preference) options (whereas I don't).
But it is OK for you to not like this idea.
I think that in the future user questions will only increase about characters in their data that they can't see.
We'll monitor that I guess.

**Comment by donho** [comment]
> I think that in the future user questions will only increase about characters in their data that they can't see.

OK, if it's the case, then we'll reconsider it.

**Comment by sasumner** [comment]
@donho 

Here's one request to add to the list:  #8530
I tagged it as Scintilla dependent but really Scintilla's answer is to use the SCI_SETREPRESENTATION api from the host program.

**Comment by donho** [comment]
@sasumner  Thank you for the info.
I still don't think it's a "must have" feature.

**Comment by sasumner** [comment]
@donho I will just keep building the case with comments to this issue as more users either complain or ask questions. :-)

**Comment by alankilborn** [comment]
Here's a relevant user experience with characters he can't see:  https://community.notepad-plus-plus.org/topic/23935/view-show-all-characters-not-showing-all
