### ISSUE TITLE
'enable session snapshot' gets disabled occasionally

### ISSUE THREAD

**Issue by appar1tion** [notepad-plus-plus/notepad-plus-plus#5063]
=======

### Description of the Issue

i use notepad++ heavily at work, and sometimes the 'enable session snapshot and periodic backup' option gets disabled without warning.

### Steps to Reproduce the Issue

unfortunately, i don't have repro steps for this.
i want to blame windows 10, since i was on win7 for years and never had this problem.
i don't know if it has something to do with running as admin in win10, but sometimes i'll go to close n++ and it will prompt me for unsaved content, which is my only indication that the session backup is disabled.
this does not happen every time, and i don't know what causes it. i re-enable the setting and i'm fine for maybe two weeks until it happens again.
the 'remember current session' and 'backup on save' options are always as i set them, it's on the snapshot and periodic backup that gets disabled.

### Expected Behavior

for the session snapshot setting to remain enabled until i manually turn it off (which is never for me).

### Debug Information

Notepad++ v7.5.9   (32-bit)
Build time : Oct 14 2018 - 15:02:52
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : ON
Local Conf mode : OFF
OS : Windows 10 (64-bit)
Plugins : DSpellCheck.dll mimeTools.dll NppConverter.dll NppExport.dll NppTextFX.dll ScrollPastEOFUni.dll 

======

**Comment by sasumner** [comment]
Repro steps (one possible way to do it):

1. With one instance of Notepad++ running (with "Enable Session Snapshot..." ticked), be editing a named (not an unsaved) file
2. Right click the file's tab and choose Open In New Instance.  Observe a 2nd instance of Notepad++ opens along with the correct file.
3. Go to the 2nd instance's Preferences and see that "Enable Session Snapshot..." is **_unticked_**.
4. Close **_first_** instance of Notepad++.
5. Close only remaining instance of Notepad++.
6. Restart Notepad++.

END RESULT: Go to Preferences and see that "Enable Session Snapshot..." is unticked.

-------------

However, if you do it this way, you get a different (and to you, a more-desired) end result:

1. With one instance of Notepad++ running (with "Enable Session Snapshot..." ticked), be editing a named (not an unsaved) file
2. Right click the file's tab and choose Open In New Instance.  Observe a 2nd instance of Notepad++ opens along with the correct file.
3. Go to the 2nd instance's Preferences and see that "Enable Session Snapshot..." is unticked.
4. Close **_second_** instance of Notepad++.
5. Close only remaining instance of Notepad++.
6. Restart Notepad++.

END RESULT: Go to Preferences and see that "Enable Session Snapshot..." is **_ticked_**.

**Comment by appar1tion** [comment]
wow, you might have just nailed it.
that's a bug, right?
i'm always worried when developers 'expect' a certain behavior, since it means it might not get fixed >_>

**Comment by sasumner** [comment]
My guess would be that it is intentionally disabled for the 2nd+ instances run.  The problem comes in when a 2nd+ instance is the LAST instance closed.  The settings from that instance get stored and are restored upon next run.  So I suppose it *is* a bug.  For myself I just stay away from multi-instances--I see no advantage to using it.  But that's just me.

**Comment by toasty-hdds** [comment]
Issue was already described here:
https://github.com/notepad-plus-plus/notepad-plus-plus/issues/4648

Still no progress.

**Comment by sasumner** [comment]
If my hypothesis about it being intentionally disabled is correct (see above), then perhaps there won't ever be any progress.  :-)

**Comment by toasty-hdds** [comment]
No, it's a regression. There can only be a single session with 'Enable session snapshot and periodic backup' enabled i.e. the default session. Notepad++ must disable this feature when operating with any session other than the default session; however, the setting should not be manipulable within the Preferences/Backup tab during these sessions. Also, neither should its temporary state be stored.

It worked correctly before Notepad++ 7.2 was released. See

https://github.com/notepad-plus-plus/notepad-plus-plus/issues/4648

**Comment by Phroneris** [comment]
I met this problem when starting a new session from my session file (`*.npps`, named on preference) and closing old instance.
This is a serious bug for session file users. I hope this will be fixed.

Environment: Windows 7 64bit, Notepad++ 7.5.9 64bit

**Comment by mladenb** [comment]
One more way to reproduce it:

Open NPP, make sure that "Enabled session snapshots" is checked and create several files without saving them and then close NPP. Run NPP again, but using an external tool like git (I tested with git, using NPP as my default editor - simply doing "git rebase -i ..." would open a new NPP instance for me), and close NPP.

Now, run NPP manually, like the first time, and you'll see that option unchecked.

**Comment by xylographe** [comment]
Is this not fixed by commit b3a6638b936c097c5323814fe046b6ddc75695cc?
