### ISSUE TITLE
'default directory' setting is ineffective

### ISSUE THREAD

**Issue by appar1tion** [notepad-plus-plus/notepad-plus-plus#5064]
### Description of the Issue

the 'default directory' option is ignored.
i'm on windows 10, running as admin FWIW.

### Steps to Reproduce the Issue

1. set a default save directory in settings -> preferences -> default directory
2. save a file to a different directory
3. save a new file, it defaults to the directory that was just saved in, not the default directory.

### Expected Behavior

always default to the 'default directory'

### Debug Information

Notepad++ v7.5.9   (32-bit)
Build time : Oct 14 2018 - 15:02:52
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : ON
Local Conf mode : OFF
OS : Windows 10 (64-bit)
Plugins : DSpellCheck.dll mimeTools.dll NppConverter.dll NppExport.dll NppTextFX.dll ScrollPastEOFUni.dll

**Comment by MetaChuh** [comment]
please go to `settings > preferences > default directory` and make sure that `use new style dialog` is activated, to use a fixed default directory.

optionally update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins if you update from version 7.5.9.

thank you for your help and best regards.

-----
```
general notes:

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
(no extra account is needed, just use your github account to sign in)
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)
