### ISSUE TITLE
PHP: Support styling of complex variables in strings

### ISSUE THREAD

**Issue by bakedpotat0** [notepad-plus-plus/notepad-plus-plus#5065]
The PHP lexer in Scintilla v3.6.5 already detects complex variables in strings (`SCE_HPHP_COMPLEX_VARIABLE` value `104`). However, **stylers.model.xml** doesn't target this styleID anywhere, thus a default installation of Notepad++ will cause such variables to fall back to the global default text style (with no way to change the style solely via the GUI).

As a matter of convenience, **stylers.model.xml** should be modified so that Notepad++ ships with a way to easily customize the style of these variables. Something like:

`            <WordsStyle name="COMPLEX VARIABLE" styleID="104" fgColor="808080" bgColor="FEFCF5" fontName="" fontStyle="1" fontSize="" />`

**Comment by dail8859** [comment]
Closed by 184a6f6ce5896440d93374e8ba8d7673fa877e8c

**Comment by ArkadiuszMichalski** [comment]
@dail8859 Any hint why this PR disappeared https://github.com/notepad-plus-plus/notepad-plus-plus/pull/5066#issuecomment-699924232?
