### ISSUE TITLE
Since the NPP version 7.5.8 something is broken in UDL.

### ISSUE THREAD

**Issue by hiveliberty** [notepad-plus-plus/notepad-plus-plus#5068]
### Description of the Issue
Since the NPP version 7.5.8 something is broken in UDL.
I use AEL UDL (https://github.com/xilitium/AEL-Syntax-Highlighting-Notepad-Plus-Plus).
When I open *.ael files from the local disk -> UDL coloration is apply.
When I open *.ael through WinSCP from remote host -> UDL coloration is not applied.
This is not issue like https://github.com/notepad-plus-plus/notepad-plus-plus/issues/2722 or https://github.com/jcaillon/3P/issues/88, because in NPP version 7.5.7 and below UDL coloration works correctly. Also, in both cases I use the same instance NPP (portable).

### Steps to Reproduce the Issue

1. Create portable instance NPP 7.5.8 or above
2. Import AEL UDL
3. Set this instance as default editor for WinSCP
4. Try to open *.ael through WinSCP from remote host.

**Comment by MetaChuh** [comment]
please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins if you update from version 7.5.9 or below.
if your issue still persists, and it is still of relevance, please feel free to file a new issue as easy to understand and reproducible as possible.

thank you for your help and best regards.

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
(no extra account is needed, just use your github account to sign in)
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)

**Comment by hiveliberty** [comment]
Sorry, I forgot about this issue.
UDLs works fine after npp 7.6.2 , as far as i remember..
