### ISSUE TITLE
Drag and drop tabs bug

### ISSUE THREAD

**Issue by Blue-Tech-PS** [notepad-plus-plus/notepad-plus-plus#5072]
### Steps to Reproduce the Issue

1. Click on a tab (tab1)
2. Drag it and drop it at a point where you are hovering over another tab (tab2)
3. The other tab (tab2) will be shown as selected, but the contents of the tab that was dragged and dropped (tab1) will be shown

### Notepad++ v7.6   (64-bit)
Build time : Nov 13 2018 - 00:12:05
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 8.1 (64-bit)
Plugins : DSpellCheck.dll mimeTools.dll NppConverter.dll 

What the file tab1 first looked like
![image](https://user-images.githubusercontent.com/38621789/49179764-ecc0fc00-f34a-11e8-9880-34211ca0841a.png)
What the file tab2 first looked like
![image](https://user-images.githubusercontent.com/38621789/49179795-fcd8db80-f34a-11e8-8a00-09b33e5c418d.png)
After dragging and dropping tab1, it showed that tab2 was selected, and showed the content of tab1
![image](https://user-images.githubusercontent.com/38621789/49179887-36114b80-f34b-11e8-8938-7c87b7b5ac09.png)

**Comment by SinghRajenM** [comment]
Very specific case, but can be reproduced.
You need to slightly drag the tab (left to right or vice versa), and release it as soon tab position is changed. Issue is reproduced. Switching tabs resolves the issue.

If you go further left to right or other direction, then it works fine.

**Comment by Blue-Tech-PS** [comment]
Thanks for the help!

**Comment by Blue-Tech-PS** [comment]
Is there any way that this minor issue can be fixed?

**Comment by SinghRajenM** [comment]
@donho 
I feel, this regression is caused by  c6e1a95 . 
Also, I could not reproduce the issue #4885 for which this PR was submitted.

**Comment by cmeriaux** [comment]
@SinghRajenM  This bug was there before the commit you mentioned

**Comment by SinghRajenM** [comment]
@cmeriaux Oh, it is. I am not able to reproduce if I revert that commit. May be I'm missing something.

**Comment by Blue-Tech-PS** [comment]
Ok thanks I'll check this bug out in more detail.

**Comment by Blue-Tech-PS** [comment]
This minor issue was introduced in the 7.5.9 release.

**Comment by cmeriaux** [comment]
@SinghRajenM I can't  reproduce the issue with v7.6. I think I'm missing something. A video may help to understand the steps to reproduce. There is probably a dependency with a configuration parameter.

Anyway, the commit you mentioned https://github.com/notepad-plus-plus/notepad-plus-plus/commit/c6e1a95098ada4db56dd9032bd5b2d4fa92458a7 was supposed to fix #4339 but it's not (occurrence is twice per month).  

cheers

**Comment by Blue-Tech-PS** [comment]
OK I will try taking a screen record.

**Comment by Blue-Tech-PS** [comment]
> @donho
> I feel, this regression is caused by [c6e1a95](https://github.com/notepad-plus-plus/notepad-plus-plus/commit/c6e1a95098ada4db56dd9032bd5b2d4fa92458a7) .
> Also, I could not reproduce the issue #4885 for which this PR was submitted.

You must be correct. I will write if I find a solution.

**Comment by Blue-Tech-PS** [comment]
A video of the issue
![bandicam 2018-12-12 20-37-24-724](https://user-images.githubusercontent.com/38621789/49897528-57476100-fe4e-11e8-9478-04aa532f4678.gif)
