### ISSUE TITLE
[Translation] Translatable menu items are not part of language files (except russian)

### ISSUE THREAD

**Issue by dinkumoil** [notepad-plus-plus/notepad-plus-plus#5074]
### Description of the Issue
In the _View_ menu there are the following 3 entries which are translatable but except _russian.xml_ no other language file contains them.

* Hide Line Number Margin
* Hide Bookmark Margin
* Hide Folder Margin

### Steps to Reproduce the Issue
1. Open _View_ menu.
2. Pay attention to the last 3 entries at the lower border of the menu.

### Expected Behavior
The text of the entries should be translated to the current UI language set in _Preferences_ dialog.

### Actual Behavior
Except in russian locale these entries appear always in english.

### Required Entries for _english.xml_
````XML
<Item id="44212" name="Hide Line Number Margin"/>
<Item id="44213" name="Hide Bookmark Margin"/>
<Item id="44214" name="Hide Folder Margin"/>
````

### Debug Information
Notepad++ v7.6   (32-bit)
Build time : Nov 12 2018 - 23:51:42
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 7 (64-bit)
Plugins : mimeTools.dll nppConverter.dll NppExport.dll Pork2Sausage.dll

**Comment by sasumner** [comment]
I'm confused.  I'm running the portable version, but I see no such menu entries:

![image](https://user-images.githubusercontent.com/30118311/49223092-b9628980-f3ab-11e8-90cb-22869b0c5403.png)

**Comment by dinkumoil** [comment]
@sasumner 

You are right, these entries are created by the _Customize Toolbar_ Plugin, **but** in _russian.xml_ there are entries to translate them (search e.g. for 44212 in all files of the _localization_ directory of a portable installation) and if I add equivalent entries to _german.xml_ the menu items get translated.

Because there are entries in _russian.xml_ I never thought that the menu items could be related to a plugin, shame on me.

I will close this issue and the related PR. Thank you for hinting me to that mistake.
