### ISSUE TITLE
no plugin menu anymore

### ISSUE THREAD

**Issue by vladtepesch** [notepad-plus-plus/notepad-plus-plus#5076]
### Description of the Issue
After an (automatic? i have not manually installed 7.6) update of np++ no plugin menu shows up.
I also could find no entry of an plugin manager.
I searched and moved the complete pluginfolder to %localappdata%\Notepad++
Without any success.
Also when running as Admin there is no menu.

### Debug Information
Notepad++ v7.6   (32-bit)
Build time : Nov 12 2018 - 23:51:42
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 7 (64-bit)
Plugins : none

**Comment by chcg** [comment]
The info about the necessary manual movement of the plugins could be found here: https://notepad-plus-plus.org/news/notepad-7.6-released.html. Unfortunately you need to create also subdirs for each of the plugins.

**Comment by vladtepesch** [comment]
> The info about the necessary manual movement of the plugins could be found here: https://notepad-plus-plus.org/news/notepad-7.6-released.html. Unfortunately you need to create also subdirs for each of the plugins, so just moving the plugins dir is not sufficient.

As I stated: 
I've done that already, but the complete plugin-menu was gone and also creating sub olders an dmoving plugins did not work.

> 
> Seems this one could be closed as you already created #5077 and used a reinstallation as "workaround".
The other Issue is completely unrelated and describes an error of the plugins update mechanism, that is unrelated to  the migration issues

**Comment by mohannad-abwah** [comment]
I'm seeing this too. Fresh new install on a brand new machine (installed x64 version, with the 'don't use APPDATA' option checked), and there is no plugin menu. It just doesn't show up. I did select it in the installation dialog, and I have no custom plugins, this is just broken on a clean install.

![image](https://user-images.githubusercontent.com/2223788/49474963-dabbdf00-f7ca-11e8-9c8c-6bc91214a06e.png)

**Comment by chcg** [comment]
@mohannad-abwah 
I think a bug. See https://notepad-plus-plus.org/community/topic/16621/notepad-7-6-new-plugins-admin/75 and all the other posts regarding this topic.

**Comment by x9t9** [comment]
I also do not see any plugin-manager.
i am not using installer but the " portable" versions.
i have tried x64, x32, both *.zip and *.7z that are provided in the [download section](https://notepad-plus-plus.org/download/v7.6.html)
I do not even know where on the UI I should see this ( I presume under `Plugin `menu ..)

**Comment by sasumner** [comment]
Sure would be great if people would stop opening issues about "design changes".  Did anybody ever say the "Plugin Manager" would live forever?  And, if you are going to update, READ the release notes.

**Comment by Aidolii** [comment]
Plugin Admin is not in portable releases, and this is not really mentioned anywhere easily accessible. I had to dig into this thread. https://notepad-plus-plus.org/community/topic/16494/new-built-in-plugin-admin-plugin-manager-is-ready/53

It's stupid that they didn't solve this before releasing it, and even stupider that it's not disclosed in the patch notes or even on the Plugin Admin page.

**Comment by x9t9** [comment]
@Aidolii - thanks for the pointer. In fact it appears to be missing in the zip distributions, although by reading the thread I must say that I did not understood the reason, nor the reason for plugin install under a system folder like <%AppData > or any other for that matter. IMHO keeping the same old plugin folder as previous would be much simpler. But I guess that's not for this issue. Thanks again.

**Comment by MetaChuh** [comment]
@vladtepesch 

7.6.3 and above solved many issues regarding plugins and `plugins admin`.
note: the old `plugin manager` is not compatible with any version from 7.6 and above. please do not use it on newer versions of notepad++.

please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins if you update from version 7.5.9 or below.

thank you for your help and best regards.

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
(no extra account is needed, just use your github account to sign in)
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)

**Comment by lcwong82** [comment]
the plugin admin is missing after update to 7.6.6 , left only "open plugin folder" , in win 7 x64 . You're annoying.
I had to uninstall & using back old version.
next time, don't simply launch something before test properly

**Comment by xantiva** [comment]
After update to 7.6.6 all plugins are "uninstalled" here (Win 7 x64). I had to re-install all.

**Comment by vladtepesch** [comment]
> 
> 
> Sure would be great if people would stop opening issues about "design changes". Did anybody ever say the "Plugin Manager" would live forever? And, if you are going to update, READ the release notes.

this ticket is not about design change and not about the "Plugin Manager". It is about the completely  missing plugin functionality (not even a plugin menu is shown anymore) after an automatic update.

**Comment by sasumner** [comment]
>not even a plugin menu is shown anymore

screenshot of that please

**Comment by vladtepesch** [comment]
mohannad-abwah posted one above. but this ticket is closed and quite old now, sorry shouldn't have posted again here
