### ISSUE TITLE
pluginAdmin "update plugin" removes plugin

### ISSUE THREAD

**Issue by vladtepesch** [notepad-plus-plus/notepad-plus-plus#5077]
### Description of the Issue
After reinstalling np++ (because no plugins (and no plugin-menu) were available after update)
-  opened the plugin admin, 
- checked the two entries on the update page
- hit the update button
  -->npp says it have to restart.
- after restart the two checked plugins were gone

The new plugin system is a great mess :angry: 

Edit:
this seems to happen, if updater has no internet access (e.g because the proxy settings were not saved, after updating them)

so there are two problems:
1. the updater gives no feedback of download progress at all, or if it even can reach the repository
2. if it fails downloading, the old plugin version is deleted.

**Comment by donho** [comment]
It's been fixed and will be in the next release.
