### ISSUE TITLE
Project window background gets white when a new windows explorer window opened

### ISSUE THREAD

**Issue by canergoksel** [notepad-plus-plus/notepad-plus-plus#5086]
### Description of the Issue
I am using np++ with a dark background. Whenever I open a new Windows Explorer window, background of side windows (Project, Folder as Workspace etc.) gets white background.

### Steps to Reproduce the Issue

1. Open Project view window - Click View\Project\Project Panel 1
2. Change np++ theme from style configurator to a dark background one,
3. Open an existing file on np++,
4. Sight click on the file tab and click Open containing folder in Explorer

### Expected Behavior
My project window background to does't change.

### Actual Behavior
My project window background changes to white.

### Debug Information
Notepad++ v7.5.8   (64-bit)
Build time : Jul 23 2018 - 02:06:36
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 7 (64-bit)
Plugins : DSpellCheck.dll mimeTools.dll NppConverter.dll 

![before](https://user-images.githubusercontent.com/20395522/49294935-6977e580-f4c5-11e8-85e0-c16d9d1ee4f5.PNG)
![after](https://user-images.githubusercontent.com/20395522/49294940-6bda3f80-f4c5-11e8-85a6-dd3b4fa6d0f9.PNG)

**Comment by ArkadiuszMichalski** [comment]
@canergoksel You still have this problem in last NPP version? I can't reproduce in NPP 7.9 RC.

**Comment by donho** [comment]
Cannot reproduce either.
Please reopen it if this issue can be reproduced in latest version.
