### ISSUE TITLE
Feature request: search text in a scope

### ISSUE THREAD

**Issue by ferenczy** [notepad-plus-plus/notepad-plus-plus#5089]
It would be great to have a **possibility to limit text search to a specific scope**. A scope would be a language element like comment, keyword, string, etc.

Notepad++ already knows about those scopes - they correspond to language elements which syntax highlighter is using to colorize the text. Any element the syntax highlighter knows might be used as a scope. Obviously, it depends on the currently active language.

The list of scopes in the _Find text_ dialog would be dynamic, it would simply display elements defined by the currently active language (you can see them in the _Style_ list box in the _Style Configurator_ dialog). Only some of those elements would make sense, for example comment, keyword, identifier, string, etc. Other elements like number, operator, etc. wouldn't be very useful but it's not a big deal I guess.

So it's just a new usage of something Notepad++ already has (language elements). Some editors have such feature.

What do you think? I would appreciate additional thoughts on this.

**Comment by MetaChuh** [comment]
unfortunately we currently don't have time to do that, hence also the delayed reply.
thanks for understanding and best regards.
