### ISSUE TITLE
On Restart, .JS files seen as Normal Text File

### ISSUE THREAD

**Issue by brandpeter** [notepad-plus-plus/notepad-plus-plus#5091]
### Description of the Issue
When restarting NotePad++ any previously open files with a .js extension are loaded as "Normal Text Flile" and are not styled with the JavaScript style.

### Steps to Reproduce the Issue
1. Open a .js file
2.  Close and Reopen NP++
3. View the .js file, wrong style "Normal text" is applied
4. Close and reopen .js file -note that correct "JavaScript file" style is applied.

### Expected Behavior
.js File should open as "JavaScript file" and be styled accordingly.

### Actual Behavior
.js File opens as "Normal Text File"

### Debug Information
Notepad++ v7.5.9   (32-bit)
Build time : Oct 14 2018 - 15:02:52
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10 (64-bit)
Plugins : mimeTools.dll NppExport.dll ComparePlugin.dll CustomizeToolbar.dll dbgpPlugin.dll DSpellCheck.dll Explorer.dll NppFTP.dll NppTextFX.dll PluginManager.dll

**Comment by chcg** [comment]
Can't reproduced this issue. 
- Is this a new issue starting to happen with N++ 7.5.9?
- Are just js files affected? Or is this also happening for e.g. html files.

Could you check %AppData%\Roaming\Notepad++\session.xml
and for your file the lang="XY" tag, e.g.

 `           <File firstVisibleLine="0" xOffset="0" scrollWidth="6572360" startPos="66974" endPos="0" selMode="0" lang="JSON" encoding="-1" .... />
`

**Comment by brandpeter** [comment]
Yes, it seems to be recent behavior, and just restricted to .js files.
On closing NP++ the entry for the js file in session.xml has its attribute lang="".
All other languages are fine; css, html, php, xml, sql.
I have recently changed the functionList.xml (attached), could it be something in that?
[functionList.zip](https://github.com/notepad-plus-plus/notepad-plus-plus/files/2636243/functionList.zip)

**Comment by brandpeter** [comment]
On opening NP++, I noticed that language "JavaScript" was missing from Language menu. After adding it back using the Preference Settings, this issue has now been resolved.
