### ISSUE TITLE
hide&unhide option on "Folder as Workspace" (collapsible)

### ISSUE THREAD

**Issue by sevdimali** [notepad-plus-plus/notepad-plus-plus#5096]
### Description of the Issue

it will be very usefull with hide and unhide option.
For example adding liitle button to the left of the 'x' button.
When clicked this button, "Folder as Workspace" window will hide.
When move mouse over this window then it will expand.

It will give more editor space to user. when user needs to navigate files then simply move mouse "Folder as Workspace" then it will expand, after moving mouse from this window it will shrink to left.

### Steps to Reproduce the Issue

1. 
2. 
3.

**Comment by donho** [comment]
3 new features added in Folder as workSpace:
Select & show the current editing file: bc2b5ac2ce47ed8821525c534d16c19b5f239f1d
Fold all: e0d995c1a6a045c8effb9f412325ba14f0d329d1
Expand all: 703a49b32304e9ab09931493db9e1ca972e896f3

They will come out with 7.8.3 which will be available soon.
