### ISSUE TITLE
Option to save session with relative pathnames for current drive

### ISSUE THREAD

**Issue by peripatetes** [notepad-plus-plus/notepad-plus-plus#5098]
### Description of the Issue

When notepad++ is used on a portable drive, it would be a great benefit to make all session references to files on the same drive relative rather than absolute paths. This is perhaps an extension of issue #1587.

### Steps to Reproduce the Issue

1. Use portable Notepad++ on a removable drive. Save some files on same removable drive.
2. Close Notepad++, saving session and backups.
3. Do something which causes the drive to have another drive letter - move to another computer, insert another removable drive, etc.
4. Launch Notepad++ again.

### Expected Behavior

Notepad++ launches with saved session, including all the previously open files on the same removable drive.

### Actual Behavior

Notepad++ finds that it can't locate the files from the saved session, and opens an empty session instead.

If you have sufficient user privileges and nothing open on any conflicting disk, you can work around this by going into Disk Management and changing drive letters around - but only if you remember to do that before launching Notepad++. If you launch Notepad++ first and then remember you needed to do that, it's too late - the saved session file has been overwritten with a blank one.

**Comment by badrelmers** [comment]
this is a must,please add it.

**Comment by donho** [comment]
This feature won't be implemented due to the huge impact with its all functionality.
