### ISSUE TITLE
lowercase "L" and "1" are Identical

### ISSUE THREAD

**Issue by Marcus-Mitchell** [notepad-plus-plus/notepad-plus-plus#5099]
The lowercase "L" and "1" are indistinguishable. This could be fixed by slanting the line on the top of the "1"

**Comment by Myrcellion** [comment]
Actually, Notepad++ uses standard fonts (the font defines the appearance of the characters). If you don't like the default font, you can follow those steps to change it:

1. Click on the 'settings' tab
2. Click on the 'Style configurator' option
3. Select 'Global styles' as 'language' and 'Default style' as 'style'
4. Pick a font that suits you in the list (You can clearly see the difference between 1 and l in Arial for example)

**Comment by sasumner** [comment]
Please close as a non-issue.

**Comment by niente0** [comment]
Hi, I had the same problem. I solved it by switching to "Liberation Mono" font.

![abc-10822_7e2d7e3e9dea97f3d09aeec7354d61af](https://user-images.githubusercontent.com/168951/49516679-75372380-f89a-11e8-8814-2942ed317bfe.png)

**Comment by sasumner** [comment]
Many many fonts will meet this need.  Enough said.  Let's not turn this into a font-suggestion forum. :-)
