### ISSUE TITLE
Ctrl+z add new `"` character.

### ISSUE THREAD

**Issue by Naheulf** [notepad-plus-plus/notepad-plus-plus#5107]
### Description of the Issue

Undo a twin double quote write a third double quote.

### Steps to Reproduce the Issue

1. Create new blank file (Ctrl+n)
3. Write `""` (press the double quote key two times)
4. Undo last action (Ctrl+z)

### Expected Behaviour

File should contain a single double quote (`"`) or a twin double quote with cursor between theses quotes.

### Actual Behaviour

File contain a triple double quote (`"""`)

### Debug Information

Notepad++ v7.5.9   (32-bit)
Build time : Oct 14 2018 - 15:02:52
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 8.1 (64-bit)
Plugins : DSpellCheck.dll mimeTools.dll NppExport.dll ccc.dll CodeAlignmentNpp.dll ComparePlugin.dll DoxyIt.dll ImgTag.dll JSMinNPP.dll NppFTP.dll NPPJSONViewer.dll NppVHDL.dll PluginManager.dll PoorMansTSqlFormatterNppPlugin.dll Python Indent.dll TabIndentSpaceAlign.dll XMLTools.dll 

I saw this in python script but the same behaviour also occur with others languages...

**Comment by sasumner** [comment]
For me your step 3 removes both `"` and leaves nothing in the file.  It is likely you have a plugin interaction problem--try removing some/all and see if the problem remains, maybe?

**Comment by Naheulf** [comment]
I remove all my additional plugins but the behaviour stay the same. Can it caused by some user config ?

##Debug Information (updated)
Notepad++ v7.5.9   (32-bit)
Build time : Oct 14 2018 - 15:02:52
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 8.1 (64-bit)
Plugins : DSpellCheck.dll mimeTools.dll NppExport.dll PluginManager.dll

**Comment by dail8859** [comment]
Ran into this as well.

```
Notepad++ v7.7   (32-bit)
Build time : May 19 2019 - 13:08:20
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10 (64-bit)
Plugins : none
```

**Comment by sasumner** [comment]
I do NOT confirm (a triple double quote) with fresh clean portable 7.7.  I get an empty file after the undo. Note that I don't necessarily agree with @Naheulf 's "Expected Behavior".  I think a resultant empty file is fine.

Notepad++ v7.7   (32-bit)
Build time : May 19 2019 - 13:08:20
Path : C:\....\npp.7.7.bin\notepad++.exe
Admin mode : OFF
Local Conf mode : ON
OS : Windows 10 (64-bit)
Plugins : mimeTools.dll NppConverter.dll NppExport.dll

**Comment by MetaChuh** [comment]
@sasumner 

it only happens, if `settings > preferences > auto-completion > auto-insert` has the closing `" "` activated.

pressing `"` twice and then undo once, will produce `"""`

**Comment by sasumner** [comment]
>auto-completion > auto-insert has the closing " " activated

Ah, after that I do confirm it.  Having that mentioned somewhere earlier in the issue would have helped. :)

In hindsight, the OP's "twin double quote with cursor between theses quotes" now makes sense. :)

**Comment by Naheulf** [comment]
Thanks @MetaChuh for finding the setting that causes this behavior.
For fun I tested with symmetrical auto-Insert twin characters.
Typing `(`, `)` and `ctrl+z` produce `())`
Typing `[`, `]` and `ctrl+z` produce `[]]`
Typing `{`, `}` and `ctrl+z` produce `{}}`

**Comment by sasumner** [comment]
@dail8859 Can you attempt verification in N++ 7.8.9 and close if problem is resolved?

**Comment by donho** [comment]
@sasumner 
I can confirm that the behaviour remain the same in v7.9.
The 2nd strok of `"` is delete by auto-completion routine so for scintilla the last action is deleting of `"` . Cttr-Z restore the deleted `"`. I have no idea to fix it, and OTOH, it's not really a bug to me.
