### ISSUE TITLE
Function list hiding functions after a regexp in php file

### ISSUE THREAD

**Issue by Entretoize** [notepad-plus-plus/notepad-plus-plus#5110]
### Description of the Issue
I have a php file that is a class, and the function list show functions out of the class and not show all functions.

### Steps to Reproduce the Issue
1. open a php file
2. add these lines:
function func()
{
     $var=preg_replace('#<br/*>#i','\n',$var);
}
3. refresh the function list

### Expected Behavior
All functions should be listed and all must be inside the class.

### Actual Behavior
Functions after the line are not listed.
Some function are listed outside the class.

### Debug Information
Notepad++ v7.5.8   (32-bit)
Build time : Jul 23 2018 - 02:03:53
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10 (64-bit)
Plugins : CodeAlignmentNpp.dll ComparePlugin.dll DSpellCheck.dll HTMLTag_unicode.dll NppConverter.dll PluginManager.dll PythonScript.dll mimeTools.dll NppExport.dll

**Comment by ArkadiuszMichalski** [comment]
@Entretoize Do you still have this problem in latest Notepad++ version? I can't reproduce for code:
```
<?php

class MyClass
{
	function func()
	{
	$var=preg_replace('#<br/*>#i','\n',$var);
	}

	function func2(){
			
	}	
	
	public function myFunc1()
	{
		$target = '/path/to/files/*';
	}

	public function myFunc2 ($name)
	{
		return $name;
	}

}
?>
```

Efect:

![a](https://user-images.githubusercontent.com/2730894/94348295-29d7a180-003b-11eb-8a41-5697666daa6c.gif)

**Comment by Entretoize** [comment]
Donho (or must I call you Lucky Luke ?) can you reopen ? There's many things that breaks the function list and the issue is still there, half of my class files doesn't show a complete function list or even a list at all.
Here an example:

```
<?php


class PARTENAIRE extends HEADLESS
{
	public function __construct()
	{
		curl_setopt($this->cs, CURLOPT_HTTPHEADER,array('Accept: */*; q=0.8');
	}


	function TraitementRDV()
	{
		if ($r && $r['timestamp']>$datestartlimit)		/*comment*/
		{

		}
	}
	
}

?>
```

**Comment by Entretoize** [comment]
Finally as the title is not realt true, I created another issue, I close this one.
