### ISSUE TITLE
Feature Request: Search and Replace working with Column Selections

### ISSUE THREAD

**Issue by slposey** [notepad-plus-plus/notepad-plus-plus#5113]
### Description of the Issue
I want to be able to Search and Replace text within column selections just as I do withing ordinary stream selections.

I see there are previous instances of folks asking about this (Issue #94 and #760 in particular). These appear to have been closed without any clear mention of a resolution to the problem. 

Can this be done? Is it on the radar? Is there something preventing it working?

### Expected Behavior
I expect to be able to make a column selection and summon the Search and Replace dialog (CTRL+H) and be able to use the "In Selection" checkbox to replace strings within the column selection.

### Actual Behavior
The "In Selection" checkbox is disabled when the column selection mode is active.

**Comment by sasumner** [comment]
Can this be done? YES
Is it on the radar? APPARENTLY NOT
Is there something preventing it working? NOPE

>I see there are previous instances of folks asking about this (Issue #94 and #760 in particular). These appear to have been closed without any clear mention of a resolution to the problem.

I suppose closure of these prior issues means that the developers choose not to implement, so I'm not sure what good opening a new issue is.  :-)

**Comment by slposey** [comment]
Well it would be nice to have words to that effect rather than simply
closing the item with no commentary.

**Comment by sasumner** [comment]
I agree but the Notepad++ developer does what he wants.

**Comment by glv1** [comment]
I want this feature also.  I often edit sql scripts constructed from copied text and this feature would help me to align columns of text quickly

**Comment by sasumner** [comment]
@glv1 Can you give an example of how this would "help align columns of text quickly".  I think I may know already, but maybe you have a different idea in mind....

**Comment by slposey** [comment]
I first encountered the ability to do this in UltraEdit.

A simplistic example of the sort of thing *I* frequently use it for is something like the following. Say I have multiple lines from, e.g. a .CSV style file:

```
LASTNAME,FIRSTNAME,MI,AGE,WEIGHT
Moose,Bullwinkle,J,32,1024
Squirrel,Rocky,J,24,12
Simpson,Homer,J,45,212
Robinson,Edward,G,112,185
```

I want to convert this into a fixed width format, one approach I can use is to search and replace all the commas with a fixed number of spaces, say 10:

```
LASTNAME          FIRSTNAME          MI          AGE          WEIGHT
Moose          Bullwinkle          J          32          1024
Squirrel          Rocky          J          24          12
Simpson          Homer          J          45          212
Robinson          Edward          G          112          185
```

Now, to get the fixed width fields, it's convenient if I can column select something like so:

```
LASTNAME |          F|IRSTNAME          MI          AGE          WEIGHT
Moose    |       Bull|winkle          J          32          1024
Squirrel |          R|ocky          J          24          12
Simpson  |         Ho|mer          J          45          212
Robinson |          E|dward          G          112          185
```

And replace spaces with nothing, leaving me with:

```
LASTNAME FIRSTNAME          MI          AGE          WEIGHT
Moose    Bullwinkle          J          32          1024
Squirrel Rocky          J          24          12
Simpson  Homer          J          45          212
Robinson Edward          G          112          185
```

Does that make sense?

**Comment by glv1** [comment]
@sasumner
> @glv1 Can you give an example of how this would "help align columns of text quickly". I think I may know already, but maybe you have a different idea in mind....

same idea as slposey above.  

initial text might be (containing spaces):
a        1       dog         radish
b            2           cat               carrot    

select a column using 
a  |      1      | dog         radish
b  |          2  |         cat               carrot    

then replace spaces with nothing:
a  |1| dog         radish
b  |2|         cat               carrot    

repeat with other columns to obtain
a  1   dog   radish
b  2   cat    carrot

**Comment by glv1** [comment]
@slposey
> I first encountered the ability to do this in UltraEdit.
Just download it and that is exactly the feature I'm after.

I might have to kick my notepad habit.

**Comment by sasumner** [comment]
It may be simpler to script a solution than to wait for Notepad++ to be given this feature natively.  :(

**Comment by sasumner** [comment]
Closing, see https://github.com/notepad-plus-plus/notepad-plus-plus/issues/8450#issuecomment-648776881

**Comment by rpvaz** [comment]
> Can this be done? YES Is it on the radar? APPARENTLY NOT Is there something preventing it working? NOPE
> 
> > I see there are previous instances of folks asking about this (Issue #94 and #760 in particular). These appear to have been closed without any clear mention of a resolution to the problem.
> 
> I suppose closure of these prior issues means that the developer chooses not to implement, so I'm not sure what good opening a new issue is. :-)

It's unbelievable that so many people is asking for this feature and it's not even "on the radar" !! 
Seems to me a mere whim of the developer... :(

**Comment by alankilborn** [comment]
I had some offline discussion with @sasumner about this at one time.  He was working on the solution to this, but gave up because he was told (he said) by the Notepad++ author that such a change would not be accepted if it "changed a lot of code".  The work was abandoned because he didn't want to put the non-trivial effort in, only to have it rejected as "too big of a change".  Again, my interpretation of what he said.

Anyway, I scripted a solution to this.  See [HERE](https://community.notepad-plus-plus.org/topic/22180) if you are interested in that.

**Comment by rpvaz** [comment]
> I had some offline discussion with @sasumner about this at one time. He was working on the solution to this, but gave up because he was told (he said) by the Notepad++ author that such a change would not be accepted if it "changed a lot of code". The work was abandoned because he didn't want to put the non-trivial effort in, only to have it rejected as "too big of a change". Again, my interpretation of what he said.
> 
> Anyway, I scripted a solution to this. See [HERE](https://community.notepad-plus-plus.org/topic/22180) if you are interested in that.

Thank you for the script, I'll try it asap.
Well, looks like it's really a mere whim of the author !
