### ISSUE TITLE
Polish characters incorrectly displayed on 7.6

### ISSUE THREAD

**Issue by Arczi008** [notepad-plus-plus/notepad-plus-plus#5116]
If I open txt file with notepad++ 7.6 its display strange symbols.
```
Mysz/Dźwięki/ObrazLogowania/
//===ENGINE DŹWIEK FX===\\
```
![](https://i.postimg.cc/QMPbX9M5/bug-1.png)

**Comment by jad986** [comment]
@Arczi008 Please select: Menu -> Encoding -> Encode in UFT-8 (Menu -> Format -> Koduj w UFT-8) and check if is correct.

**Comment by Arczi008** [comment]
and its UTF not UFT

**Comment by Arczi008** [comment]
I tried that before posting, and its UTF not UFT.
Endocing > Character Set > Central European > Windows 1250 seems fix that. But you need to do this everytime

Notepad should open *.txt as ANSI, but it detect words like "dźwignia", "żołędzie" and opening in different encoding. ISO 8859-1. Thats stupid.

**Comment by Arczi008** [comment]
I tried that before posting, and its UTF not UFT.

Anyway..
Notepad should open *.txt as ANSI, but it detect words like "dźwignia", "żołędzie" or other (but some works correctly) and opening in different encoding. Like ISO 8859-1. Thats stupid.

**Comment by Arczi008** [comment]
I tried that before posting, and its UTF not UFT.

Anyway..
Notepad should open *.txt as ANSI, but it detect words like "dźwignia", "żołędzie" or other (but some works correctly) and opens in different encoding. Like ISO 8859-1. Thats stupid.

**Comment by Arczi008** [comment]
I tried that before posting, and its UTF not UFT.

Anyway..
Notepad should open *.txt as ANSI, but it detect words like "dźwignia", "żołędzie" or other (some works correctly) and opens in different encoding. Like ISO 8859-1. Thats stupid. It should open always in ANSI, when txt are saved as ANSI. No matter what the words are used.

**Comment by Raintek** [comment]
I have the same problem since the last update. Using it for 5 years now, first-time problems with it. Encoding method doesn't help at all.

**Comment by chcg** [comment]
@Raintek Last update means 7.6?
There was a change to update uchardet to 0.0.6 https://github.com/notepad-plus-plus/notepad-plus-plus/commit/bfb7e863cc6cd20f9f32389bee289607a212b12b.
The automatic detection could be switched off at settings -> preferences:

![grafik](https://user-images.githubusercontent.com/12630740/49902084-435a2a00-fe63-11e8-90fe-2846d02f63c7.png)

**Comment by Arczi008** [comment]
That helped

**Comment by Raintek** [comment]
> @Raintek Last update means 7.6?
> There was a change to update uchardet to 0.0.6 [bfb7e86](https://github.com/notepad-plus-plus/notepad-plus-plus/commit/bfb7e863cc6cd20f9f32389bee289607a212b12b).
> The automatic char encoding detection could be switched off at settings -> preferences:
> 
> ![grafik](https://user-images.githubusercontent.com/12630740/49902084-435a2a00-fe63-11e8-90fe-2846d02f63c7.png)

That helped, thanks!

**Comment by chcg** [comment]
So to fix this problem the uchardet component from https://www.freedesktop.org/wiki/Software/uchardet/ would need to corrected/change it. 
You might create an issue at their bugtracker.
