### ISSUE TITLE
Enhancement Request: heredoc/nowdoc syntax higlighting for PHP 7.3

### ISSUE THREAD

**Issue by bigboy06** [notepad-plus-plus/notepad-plus-plus#5117]
The syntax highlighting for PHP is currently broken after a closing tag of a heredoc/nowdoc block which doesn't start at col 1 of its line.
If the heredoc/nowdoc block is at a lower level in the code, there should be an indentication which can't be applied here for the reason above.
But now with the flexible heredoc and nowdoc syntax of PHP 7.3 it would even more be helpful to have this handcap lifted to be able to profit from that new flexibility.
The new flexibility means that one can write:
<?php
class abc {
     function something() {
        $var = <<<HEREDOC
          This is text.
            This too.
          HEREDOC
    }
}
?>
With PHP 7.3 the output will be:

This is text.
  This too.

and in NPP the syntax highlighting for PHP should not be broken.
-hc

**Comment by ArkadiuszMichalski** [comment]
@sasumner Can be close, invalid example, newest exist https://github.com/notepad-plus-plus/notepad-plus-plus/issues/5264 (aslo poor but with some links).
