### ISSUE TITLE
Feature request: Shift/Ctr + double-click should map to Search MarkAll 

### ISSUE THREAD

**Issue by freedaun** [notepad-plus-plus/notepad-plus-plus#5122]
### Feature Request

```
Ctrl   + double-click           => apply Search MarkAll style 1 to the word selected 
LShift + double-click           => apply Search MarkAll style 2 to the word selected 
Ctrl   + LShift + double-click  => apply Search MarkAll style 3 to the word selected 
RShift + double-click           => apply Search MarkAll style 4 to the word selected 
Ctrl   + RShift + double-click  => apply Search MarkAll style 5 to the word selected 
```
*) => reads as "results in"

### Motivation

Markings are typically applied to a file when a new version becomes available. Currently that is cumbersome, as the markings do not persist after a refresh. To redo markings is a lot of work and can't be macro-fied easily. 

The suggestion makes adding markings _very_ easy, so easy that persistent markings (per file), though desirable, would not be needed. 

### Downsides

I don't know of any downsides. If there are I presume they involve an unwanted interaction with doing a selection.

**Comment by sasumner** [comment]
Record macros (5 of them) and assign to keystrokes (suggestion: the keystrokes should include "1" thru "5" in them to correspond to the 5 styles).  Problem solved.

Note that assigning to the mouse is problematic; a lot of mouse clicking actions are already assigned to other behavior.

**Comment by freedaun** [comment]
I didn't know of the possibility to save a Macro to a shortcut, thanks!

For anyone wishing to do the same:

1. Record a macro:
    a) Macro->Start Recording
    b) Ctrl+F to the word you want highlighted (otherwise c) applies to anything selected!)
    c) Seach->MarkAll->Style
    d) Macro->Stop Recording
    [include more styling as necessary]
2. Map the macro to a shortcut:
    a) Settings->Shortcut Mapper...
    b) Find "Save Current Recorded Macro" (entry 267 in my list)
    c) Assign a shortcut key

**Comment by ebouden** [comment]
Tip: when using plugin PythonScript, modify startup.py (see attached), having 1..n words at a deterministic line (e.g. preceded with a unique tag), then these **Styles** can be **applied** **automatically** w/o pressing any key upon launching Notepad++ with a specified file (I launch it from the command line).
Note1: don't use plugin Manager to install PythonScript, instead use the .msi for this.
Note2: the coloring is done case sensitive, which I don't want (already posted an issue for this today).
Note3: the startup.py is executed on the first open file (in the saved session or argument from command line) of a freshly started Notepad++.
Note4: the full file path of my startup.py is:
    C:\Program Files (x86)\Notepad++\plugins\PythonScript\scripts\startup.py
and you need administrator privileges to change it.
Remark: This solution is far from optimal, but it works (I have only limited experience with PythonScript)
[startup.py.txt](https://github.com/notepad-plus-plus/notepad-plus-plus/files/2685695/startup.py.txt)

**Comment by sasumner** [comment]
Closing issue because the proposed solution seemed to have been acceptable.
