### ISSUE TITLE
Folding for Levels 2 to 8 dont work for Python, Matlab, Nimrod.

### ISSUE THREAD

**Issue by MaxCorman** [notepad-plus-plus/notepad-plus-plus#5123]
Hello, just as the title says, the collapse/uncollapse by level operation in the menu or using keyboard shortcuts doesn't work past level 1 for Python, Matlab, Nimrod, or any language that only uses tabs for indentation.

I tried it with Notepad++ versions 7.5.1 32-bit and 7.5.9 32-bit on a second machine and it still did not work. I also posted the issue on the Notepad++ Forum and someone else had the same issue. And there was some other thread on this forum that addressed the issue 2 years ago.

Any chance this issue will ever get fixed or any chance of a workaround? I would seriously like to have this feature since i do a lot of normal text categorization and using languages like Python that indent every tab is very handy.

Thanks.

Max.

**Comment by MaxCorman** [comment]
Ok so the folding by level applies to spaces and not tabs. That is, each space is a level. This of course is not proper since spaces are too close together.

Would this be an easy fix such as simply re-coding the feature to use tabs or 4 spaces instead of one space or is it a more difficult undertaking that would require too much work?

**Comment by sasumner** [comment]
I'm not super close to this one, but in #1898 dail seems to indicate that this is a Scintilla issue (that has been rejected for fixing) and not a Notepad++ issue.  Thus there really isn't anything that can be done, to my knowledge.  Maybe someone else will kick in with a different opinion, but really this discussion should be in #1898 and not here.

**Comment by MaxCorman** [comment]
Thanks for the clarification @sasumner. I tried reading #1898 but couldn't fully understand it due to my ignorance.

For anyone reading this post just discard it and refer to #1898 from now on. Sorry for the mixup.

**Comment by sasumner** [comment]
No problem, @MaxCorman -- if you would, will you CLOSE this one?

**Comment by MaxCorman** [comment]
Sure, how do i close it?
