### ISSUE TITLE
Saved Sessions lost

### ISSUE THREAD

**Issue by SnowmanDK** [notepad-plus-plus/notepad-plus-plus#5129]
### Description of the Issue
Notepad++ overwrites the saved session when LOADING a session, and replaces it with an EMPTY session.
Running on Windows 10 Pro x64.
I have set Notepad++ to save session files as ".nps" and set up so a doubleclick on an ".nps" file will open it AS A SESSION in Notepad++. This NORMALLY works perfectly.

### Steps to Reproduce the Issue
I am not sure how to provoke this bug, but I suspect 2 possible reasons:
EITHER it happens if one of the session files have become SMALLER since the session was saved.
OR it happens as a result of a delay connecting to the network drive that the files are on.

### Expected Behavior
I expected that the 4 files in my session opened in Notepad++.

### Actual Behavior
It just opened a blank (new) document, AND overwrote my session with an empty session.

**Comment by TheKeck** [comment]
I have experienced the same since the last update, I think.  It used to always reopen all of the files I had, including ones that were not saved.  Now I just get a single new empty file.  I double checked and I still have the "Remember current session for next launch" option checked.

**Comment by toasty-hdds** [comment]
https://github.com/notepad-plus-plus/notepad-plus-plus/issues/4648
https://github.com/notepad-plus-plus/notepad-plus-plus/issues/5063#issuecomment-444662448

**Comment by jespersh** [comment]
Ran into this issue after getting a new SSD and moving some of the files in the session-file referred to onto the new drive then loading the session. And I just thought I could then modify the session file with the new locations. Nope, empty.

1. Save a session file with X number of tabs open
2. Close npp
3. Move the files referenced by the session file to a new location
4. Open npp
5. Load session file
6. Notice the session file has been overwritten with less files referenced.

**Comment by smartree** [comment]
Maybe Notepad++ should give users a REAL Session Snapshot option for session.xml file, Eg: session-Last.xml for LastDay or LastClose, session-7Minutes.xml, session-1Hour.xml and a on-off for other people. Windows 10 edition needed it.

**Comment by donho** [comment]
Fixed by https://github.com/notepad-plus-plus/notepad-plus-plus/commit/b3a6638b936c097c5323814fe046b6ddc75695cc
