### ISSUE TITLE
Plugin Admin only available in installer

### ISSUE THREAD

**Issue by Aidolii** [notepad-plus-plus/notepad-plus-plus#5134]
Plugin Admin is not in "portable" releases, and this is not really mentioned anywhere easily accessible. I had to dig into this thread. https://notepad-plus-plus.org/community/topic/16494/new-built-in-plugin-admin-plugin-manager-is-ready/53

It's stupid that this wasn't solved before releasing it, and even stupider that it's not disclosed in the patch notes or even on the Plugin Admin page.

**Comment by rddim** [comment]
https://notepad-plus-plus.org/community/topic/16789/support-for-plugins-admin-npppluginlist-round-2

**Comment by chcg** [comment]
@Aidolii Yes, but it is fixed now by https://notepad-plus-plus.org/download/v7.6.2.html
