### ISSUE TITLE
Escape preset text when search (^F) with regular expression

### ISSUE THREAD

**Issue by Haftmann** [notepad-plus-plus/notepad-plus-plus#5136]
### Description of the Issue
When searching for selected text, the text is captured into the Search edit box. But when "regexp search" is selected, that would lead to an incorrect regular expression which is almost never what the user expects.

### Steps to Reproduce the Issue
1.  Press ^F, select "regular expression", and ESC do exit the search dialog box
2.  Enter some text containing special characters like ()^$.?[]*\ and select it. For example "$(abc)". Typical for makefiles.
3.  Press ^F and then try to search for that

### Expected Behavior
Selected special regexp characters should be auto-escaped on ^F. For example "\$\(abc\)".
So searching will find another occurences of the selected string as-is promptly.

### Actual Behavior
No auto-escape will help the user, and searching will find nothing (as $ means end of line)
and the user has to click onto "normal search" first, or must escape all regexp characters manually

### Debug Information
I's also helpful when same behaviour occurs when the user changes from "normal search" to "regexp search" and vice versa, to auto-escape and auto-unescape (latter if possible) the search string/expression.
As a benefit, beginners in regexp get some idea how to form a valid regexp when special characters are present.

**Comment by sasumner** [comment]
I think you hit on the solution to this problem when you said 'the user has to click onto "normal search" first'.  :-)

**Comment by Haftmann** [comment]
So, in case not using a mouse, how? The "normal search" has no hotkey in English, and a somewhere doubled hotkey "l" in German: The radio button gets highlighted (= dotted rectangle) but doesn't act. So neither language setting works. (Among other bugs concerning keyboard navigation in this dialog, check yourself the unexpected TAB behaviour and intermittant transparency function.)

**Comment by sasumner** [comment]
Sure, there are problems with these type of accelerators.  :-)  You can edit your language's xml file to reassign these to what you'd like.  Ideal? Nope. But it works.  But that is a different issue.

**Comment by sasumner** [comment]
Closing due to being a non-issue.
