### ISSUE TITLE
Translation of "Restore Recent Closed File” still not possible

### ISSUE THREAD

**Issue by schnurlos** [notepad-plus-plus/notepad-plus-plus#5137]
The bug with the line

_Item id=“41021” name=“Restore Recent Closed File”_

as described here https://github.com/notepad-plus-plus/notepad-plus-plus/issues/1476 is still pending.
The only way to get it translated is switching to english and back to f.e. german language.

Additional the text _"Trim Trailing Space and Save"_ still is not translatable.
All the text starting with _"Lauch in Firefox"_ to _"Send via Outlook"_ also is not translatable.

**Comment by chcg** [comment]
Macro -> "Trim Trailing Space and Save"
Run ->  "Launch in Firefox" to "Send via Outlook"

**Comment by SinghRajenM** [comment]
@schnurlos 

> Item id=“41021” name=“Restore Recent Closed File”

For this PR #5557 has been submitted. Hope it will be accepted. 
> Additional the text "Trim Trailing Space and Save" still is not translatable.

This is not supported via localized xml. But it can be localized "Settings->Shortcut mapper->Macros", now just double click on it and change the name as per your convenience. 

> All the text starting with "Lauch in Firefox" to "Send via Outlook" also is not translatable.

These options are removed from the latest version.
