### ISSUE TITLE
Feature Request:  Run Software from CD-ROM

### ISSUE THREAD

**Issue by mistrb01** [notepad-plus-plus/notepad-plus-plus#5140]
### Allow Notepad++ to run from a read-only device such as CD ROM

Would like be able run the minimalist version of the software from a CD ROM.  If the software opens and can't read the XML files for settings, then write them to the users' profile in Windows.

### Steps to Reproduce the Issue

1.  Open software from CD-ROM
2. Program crashes
3. 

### Expected Behavior

Software to open 

### Actual Behavior

Software crashes

**Comment by sasumner** [comment]
Some related discussion:  https://notepad-plus-plus.org/community/topic/16506/is-it-possible-to-run-notepad-from-cd

**Comment by mistrb01** [comment]
I am the OP on that thread.  I am now getting around to making a feature request.

**Comment by sasumner** [comment]
@mistrb01 Good luck with that!

**Comment by MetaChuh** [comment]
please use the minimalist version on a usb drive with write access.
direct run from a read only media will not be supported.

for cd rom, create an sfx archive that extracts to `%temp%\npp\` and starts notepad++.exe from there.

thank you for your help and best regards.
