### ISSUE TITLE
Reload triggered by File Status Auto-Detection purges Undo buffer

### ISSUE THREAD

**Issue by Davidebyzero** [notepad-plus-plus/notepad-plus-plus#5141]
### Description of the Issue
When a file that is open in Notepad++ is externally modified, it prompts the user whether to reload the file from disk. If a "Yes" answer is given, it not only reloads the file, but purges the Undo buffer.

This is extremely inconvenient. I had gotten accustomed to the Microsoft Visual Studio behavior. In MSVS, when a file is externally modified and I answer its confirmation dialog telling it to reload the modified version, I can Undo that action, and can in fact even undo edits done before that. The Reload action essentially acts just like any other edit.

### Steps to Reproduce the Issue
1. Make sure that Preferences → MISC. → File Status Auto-Detection is Enabled, and not silent.
2. Open a file in Notepad++.
3. Keep the Notepad++ session open. Open the same file in a different application, modify it, and save it to disk.
4. Go back to the Notepad++ session.
5. A dialog box should pop up saying "This file has been modified by another program. Do you want to reload it?" Answer Yes to this dialog box.
6. Try to Undo using Ctrl+Z or Edit→Undo and realize that this is impossible, because the entire Undo buffer has been purged.

### Expected Behavior
The action of reloading a modified file from disk should act like any other edit operation; Ctrl+Z should undo it, and a subsequent Ctrl+Shift+Z or Ctrl+Y should redo it. Furthermore, after undoing it, the entire previous undo history that was present before reloading the file should still be accessible.

The same should apply whether the reload is triggered by answering yes to a File Status Auto-Detection dialog box or using File → Reload from Disk.

However, if Preferences → MISC. → File Status Auto-Detection → "Update silently" is enabled, perhaps the undo buffer should still be purged as is currently done, because the reload was no longer a manual action and can't really be thought of as an "edit" operation.

### Actual Behavior
Reloading a file from disk always purges the undo buffer irretrievably.

**Comment by sasumner** [comment]
I'm pretty sure the implied definition of "reload" means there is no undo.  Sure you can ask for it...

**Comment by Davidebyzero** [comment]
> I'm pretty sure the implied definition of "reload" means there is no undo. Sure you can ask for it...

Well as I said, MSVS already does this. And it's so convenient that I really miss it now that I've started using Notepad++.

One example of a way in which I rely on this behavior: Running a script I wrote that programmatically changes the source code file I'm currently working on. If I then test the program and it doesn't work correctly, I need to be able to Undo to an earlier, working, state.

There are other scenarios in which I've found this behavior to be useful as well, like with resetting to different commits in git, but I don't remember the exact details.

It also just makes me really uncomfortable to lose that safety net that I've taken for granted for many years working in MSVS. There's no good reason not to implement it in Notepad++ too.

**Comment by DavidHansen-0x454d43** [comment]
@Davidebyzero, I have a similar situation where the files I am working on are modified by an external script, and nuking the undo buffer his bitten me also. 

This would be an incredibly nice enhancement in my opinion.

**Comment by sasumner** [comment]
For the record, with exposure to additional information, I now like this feature request. :-)

**Comment by wqweto** [comment]
Here is one more horror story.

I was working on a .bat file and after testing everything was compelte just needed to impl usage help screen, so that when no params are supplied to explain which and what is required. A simple couple of lines like this:
```
:usage
echo usage: %~nx0 ^<input_file^> ^<output_folder^>
echo.
echo     c:> %~nx0 "c:\path\to\input.txt" "c:\path\to\complete"
exit /b 1
```
Happy with the result I just executed my `super_userful.bat` with no arguments only to find upon return to N++ that my precious codes are missing!

Did you spot my mistake in the source above?

Yes, in `echo     c:> %~nx0 "c:\path\to\input.txt" "c:\path\to\complete"` the `>` is not *escaped* with `^>` it just redirect to `%~nx0` which is. . . ooo, my!

And in horror I started to realise that I switched on `Update silently` in `File Status Auto-Detection` a couple of months ago. . . and there is no undo, and there is no copy in `%APPDATA%\Notepad++\backup` as the file is not unnamed.

Awful feeling!

**Comment by Davidebyzero** [comment]
Ouch, [this fix was reverted](https://github.com/notepad-plus-plus/notepad-plus-plus/issues/5595). This is really, really bad. I need this, and I tend to lose work irretrievably without it, and that's exactly what happened when I unwittingly upgraded. I have had to revert to Notepad v7.6.6 and won't be able to upgrade until this is brought back.

Ideally this feature would be implemented as diffing the version before the reload with the reloaded version, and saving only those differences in the undo buffer. But even as the enhancement stands, I'd much rather have high memory usage than lose work. Just make it an option for now, please!
