### ISSUE TITLE
No confirmation for Closing an emptied new file when an undo buffer is present

### ISSUE THREAD

**Issue by Davidebyzero** [notepad-plus-plus/notepad-plus-plus#5142]
### Description of the Issue
Notepad++ almost always asks for user confirmation when the user Closes a file that has been edited. However, if it's a new file (that does not exist as an actual file on disk), and some edits were done, followed by clearing everything, and then a Close is done, there is no confirmation, and the file is instantly closed, even though there actually was data in the Undo buffer that might have been important.

I consider this to be dangerous, as I have become accustomed to reliable Undo buffers and always being prompted before closing anything that has been edited. Having an exception to the rule like this is unexpected and could result in unintended loss of work.

Microsoft Visual Studio handles this in the way I prefer. On the other hand, Windows Notepad handles this in the same flawed way as Notepad++.

### Steps to Reproduce the Issue
1. Create a New file in Notepad++
2. Type something into the new file
3. Select All, then press Backspace or Delete
4. Close the file
5. Notepad++ instantly closes the file, without prompting for confirmation.

### Expected Behavior
When there is unsaved data in the Undo buffer, and the file has not been saved in its current edited state, Notepad++ should always ask for Close File confirmation, regardless of whether it is a named file on disk or a not-yet saved new file.

### Actual Behavior
In the scenario described in "Steps to Reproduce" above, Notepad++ discarded potentially valuable data in the Undo buffer without asking for user confirmation.

Contrast this with another situation: open or create a file in Notepad++, clear all its contents, and then save it to disk. Now, if the file is Closed, there should be no confirmation (and there isn't, which is correct), because it has already been saved (indicating there was actual user intent to erase the file's contents) and no edits have been subsequently done. But if edits were done after the clearing of its contents, a File Close should trigger a confirmation dialog (and it does, which is correct).

Also, if a named file on disk is being edited in Notepad++, and is saved as a zero-byte, empty file, and then subsequently edited to be non-empty (without being saved), then cleared of its contents (without being saved), a subsequent File Close prompts the user for confirmation. This is the correct behavior, and Notepad++ should continue doing the same thing in this scenario.

And finally, in the situation of creating a new file in Notepad++ (e.g. with File→New) and then closing it without having done any edits, it should be instantly closed with no confirmation. This is currently being done and is the correct behavior.

**Comment by sasumner** [comment]
>Notepad++ discarded potentially valuable data in the Undo buffer without asking for user confirmation.

This is asking a bit much...

**Comment by Davidebyzero** [comment]
> So you do an intentional act (delete all text) and you are staring at a blank buffer, and then you do another intentional act (close the tab) while you are looking at no data...and you still expect Notepad++ to bother you with a prompt at this point--seriously? I guess you are serious or you wouldn't have typed ~500 words about it. You certainly are free to ask for what you want in Notepad++ here...best wishes.

1. The main scenario I'm thinking of is this: I might clear the contents of a new file that I've previously typed some things in, switch to some other apps, do some other stuff for a while, then come back to the empty Notepad++ window later. It'll look like it's just empty and I never did anything in it. So I Close it, and it instantly closes. I probably won't realize at this point that it even had some things in its undo buffer.
2. Close can be clicked or pressed accidentally. If I'm juggling a lot of tasks, this could potentially cause the scenario I've described to happen.
3. It's just more logical and intuitive to make it work the way I described it should. When software works in ways that are illogical / unexpected, it makes me like that software less.

And apparently you feel strongly about this too, if you found it worth writing ~80 words.

**Comment by sasumner** [comment]
>And I don't understand why you apparently felt strongly enough to seemingly argue...

This is just an open area for people to express ideas and opinions (and of course additional information when it applies) about issues which may be under consideration for implementation.  That's it.  By "arguing" I brought out such additional information from you, which may be an "oh, yea!" tipping point (which takes it from a "this is dumb" reaction from a developer, to a "gotta do" reaction) if/when this is considered for implementation!  :-)

**Comment by Davidebyzero** [comment]
Okay, you make a good point :) Actually perhaps the "New Issue" template should contain a new field, "Why is it important that this issue should be addressed?"

I mean, I was actually leaning towards shirking the whole "New Issue" template, because it did force me to be more redundant in my description of the issue than I would have liked... but then I reconsidered, that sticking to the format might increase the chances of it being addressed. However you're right, it wasn't until you argued against it that I voiced some more reasons why it's important to fix.

**Comment by DavidHansen-0x454d43** [comment]
@Davidebyzero, I agree that this should be a small change and that it would help prevent data loss.

**Comment by donho** [comment]
If user wants to save somethings he/she should restore information then close it to save.
Close an empty (even dirty) document and ask user to save it - it doesn't seems a smart behaviour to me.
The current behaviour will be kept as it is, sorry.

**Comment by sasumner** [comment]
@donho

My own comment on this from December of 2018 (above) was:  `This is asking a bit much...` so, you can see, I didn't like it originally.

But recently something happened to me in Visual Studio (which supports this behaviour) where it helped me to not lose data that I could have lost.
So I remembered this old issue and looked for it.

Another plus:  It would bring Notepad++ in line with Visual Studio editor behavior.  I'm not always in favor of echoing VS behavior, but in light of my experience, I've changed my mind about this aspect.

But, as always, your call. :-)
And the code change is always recorded here (in the PR) for possible future use.

**Comment by donho** [comment]
@sasumner 
It's quite subject, but when I doubt a behaviour in Notepad++, I check other editor. OTOH, If a behaviour is intuitive and natural to me, I won't be influenced by other popular editor/IDE - As I've never adapt to 2 modes editing, even Vim is a reference.
So here for me there's no doubt: If user wanna keep what he/she has typed, he/she should restore the content, otherwise it's a [PBKAC](https://img.devrant.com/devrant/rant/r_226222_AUU4C.jpg).
