### ISSUE TITLE
JSTool plugin can't be installed

### ISSUE THREAD

**Issue by hinst** [notepad-plus-plus/notepad-plus-plus#5145]
### Description of the Issue
JSTool plugin can't be installed in Notepad++ 7.6.1, 64 bit

### Steps to Reproduce the Issue
1. Install latest Notepad++ from installer
2. Go to Main Menu / Plugins / Manage plugins
3. Search for JSTool, check the checkbox for JSTool
4. Click Install. Notepad says it "Will be restarted". Click Yes. Notepad++ is closed

### Expected Behavior
Notepad++ is started; the JSTool plugin is present

### Actual Behavior
Notepad++ is not started; the JSTool plugin is absent

### Debug Information

```
Notepad++ v7.6.1   (64-bit)
Build time : Dec 12 2018 - 01:22:05
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10 (64-bit)
Plugins : DSpellCheck.dll mimeTools.dll NppConverter.dll PluginManager.dll 
```

**Comment by chcg** [comment]
@hinst Seems you used PluginManager for installation. See https://github.com/bruderstein/nppPluginManager/issues/139 , so this is the wrong place to report this issue.
Maybe you want to use the builtin PluginAdmin for installation.

**Comment by hinst** [comment]
The result is same when using both built-in plugin admin and PluginManager. I only installed PluginManager after I tried to install JSTool with the built-in plugin manager, and was unsuccessful

**Comment by hinst** [comment]
Tried again today. Can't reproduce. (neither 32 bit nor 64 bit.) JSTool plugin is installed successfully

**Comment by cam-eld** [comment]
had the same issue, found that sourceforge was blocked by our company... :(
