### ISSUE TITLE
Notepad++ checks for file existence even if the File Status Auto-Detection option is disabled

### ISSUE THREAD

**Issue by frank-orellana** [notepad-plus-plus/notepad-plus-plus#5146]
### Description of the Issue
Notepad++ checks for file existence even if the File Status Auto-Detection option is disabled. This generates constant freezes specially on network files.

### Steps to Reproduce the Issue

1. Open a network file
2. Disable File Status Auto-Detection
3. Move to another tab and go back to the network file
4. You will probably notice a little freeze depending on the speed of the connection

### Expected Behavior
No freeze at all. No checking for file existence if the option is disabled.

### Actual Behavior
The program freezes when switching to a file on a network, specially if the network is slow, you can even wait more than several seconds.

I checked with at least two programs to see if there was any network activity when switching to a network file and indeed I could see spikes in the Task Manager and several packets on wireshark being sent exactly when switching to these files.

You can see in this GIF that even having that option disabled it will use some network and have some lag to display the file, sometimes it takes longer and you cannot use the program meanwhile.

![notepad netprob](https://user-images.githubusercontent.com/2250701/50064932-964d1d80-0192-11e9-9299-32685e2919a9.gif)

It is important to note that if I have this option disabled and delete the file, it will not show an alert saying that the file has been deleted, which is what I would expect, but it will still freeze for a while, that's why I say that it is that functionality that causes the problem.

### Debug Information
Notepad++ v7.6   (64-bit) **But this has happened in all versions!, even in the new 7.6.1 and the one below**
Build time : Nov 13 2018 - 00:12:05
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10 (64-bit)
Plugins : DSpellCheck.dll mimeTools.dll NppConverter.dll NppExport.dll 

Notepad++ v7.5.9   (64-bit)  
Build time : Oct 14 2018 - 15:19:55
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10 (64-bit)
Plugins : mimeTools.dll ComparePlugin.dll DSpellCheck.dll JSMinNPP.dll NppConverter.dll nppcrypt.dll NppExport.dll NPPJSONViewer.dll PluginManager.dll PythonScript.dll XMLTools.dll

**Comment by frank-orellana** [comment]
So, I tried to investigate where is this happening but haven't had much luck.

Although I found this, I think this code is fired when switching to a tab:

https://github.com/notepad-plus-plus/notepad-plus-plus/blob/647651b7eed7b6349f2f4f98639e9517f0c189e5/PowerEditor/src/Notepad_plus.cpp#L3725-L3728

From what I can tell, if that reload flag is set, then it will reload the file, so maybe that is what happens, instead of just checking the file existence it reloads the entire file every time?

I tried to track to where the flag is set but only found it here on line 450, which doesn't makes much sense to the problem (at least to me):

https://github.com/notepad-plus-plus/notepad-plus-plus/blob/acb30b9e610bd5ff759318de0fca63116196c96e/PowerEditor/src/NppIO.cpp#L449-L451

Any ideas?

**Comment by pasha0077** [comment]
When tab is switched, `bool Notepad_plus::activateBuffer(BufferID id, int whichOne)` is called and in this function, `notifyBufferActivated(id, whichOne);` is called, which calls `checkDocState();`

And in this function, a check is made for existence of the file at line
`bool isFileExisting = PathFileExists(curBuf->getFullPathName()) != FALSE;`

the above bool, `isFileExisting`, is used to set menu commands
```
	enableCommand(IDM_FILE_DELETE, isFileExisting, MENU);
	enableCommand(IDM_FILE_RENAME, isFileExisting, MENU);
	enableCommand(IDM_FILE_OPEN_CMD, isFileExisting, MENU);
	enableCommand(IDM_FILE_OPEN_FOLDER, isFileExisting, MENU);
	enableCommand(IDM_FILE_RELOAD, isFileExisting, MENU);
```
The "File Status Auto-Detection" setting is used to check if the contents of file are changed or not but has nothing to do with checking the existence of file. If checking the existence of file needs to be disabled then that would be a new feature (but that would affect the setting of above menu commands).
So, it seems this is working as per design

**Comment by pasha0077** [comment]
If the new feature introduced provides option to disable the checking and the user chose it then the menu items shouldn't be enabled (as file delete, file rename makes no sense if notepad++ doesn't know if the file exists). And if you've opened a file and after code execution comes to the file existence logic (which i guess happens periodically) if it is disabled then the app marks your file as modified and asks for you to save it manually even if you didn't modify as app can't check that because you've disabled it.

**Comment by frank-orellana** [comment]
I do not understand the "And if you've opened a file and after code execution comes to the file existence logic" comment.

As for the menus, the problem would be, for example, that the delete file would always be enabled when you check this option, even when the file was deleted outside notepad++, this should be just a minor inconvenience, since if you click that option and the file is already deleted nothing should happen, and would only happen IF you check the new option.

The files opened are stored in memory and in the backup folders anyway in case the file is deleted or modified from the outside. I think Notepad++ already checks if the file is different from the one opened when saving anyway.

**Comment by MetaChuh** [comment]
the file status autodetection has been revised in 7.6.6.
i can not reproduce network activity spikes, or lags when switching between tabs, with files on network drives, using 7.6.6.

please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins.
if your issue still persists, and it is still of relevance to you, please feel free to file a new issue as detailed and reproducible as possible.

thank you for your help and best regards.

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
(no extra account is needed, just use your github account to sign in)
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)
