### ISSUE TITLE
Updater (GUP) that comes with 64-bit NPP installs 32-bit version!

### ISSUE THREAD

**Issue by AnilGupte** [notepad-plus-plus/notepad-plus-plus#5147]
I originally installed a 64-bit Notepad++.  Today I tried to update it using ...\notepad++\updater\GUP.exe and it appears to have installed the 32-bit version - even after I said No on the warning.  Of course, it is my mistake thinking that if I said No to the 32-bit it would install the  64-bit (I was in a hurry and not paying attention).  Now it is giving warnings about my plugins not being compatible with the current version.

**Comment by MetaChuh** [comment]
do not use gup.exe without providing the parameters needed for your local installation, as its defaults are set to 32 bit.

thank you for your help and best regards.

**Comment by AnilGupte** [comment]
This should be filed under bugs.
