### ISSUE TITLE
Applying Style Tokens is case sensitive until search is done

### ISSUE THREAD

**Issue by ebouden** [notepad-plus-plus/notepad-plus-plus#5148]
### Steps to Reproduce the Issue

Preparation to default case insensitive search:
1. Open Notepad++
2. Press Crtl-N  (create a new file)
3. type next text:
Case
case
CASE
Case
caSE
4. press Crtl-F, uncheck [Match case]
5. Press [Find Next]
6. press Escape
7. save the file (with some valid name on some valid path)
8. Close Notepad++
Now reproduce the issue with this case-insensitive default setting:
9. Open Notepad++ (it opens with the earlier saved file)
10. Right-click on the first word ("Case") in this same file > Style Token >  Using 1st Style
11. Now check that only the two exact occurrences of the word "Case" are highlighted in blue.
12. Press Crtl-F, Press Find Next, Press excape
13. Right click the 2nd word "case" in this same file > Style Token > Using 1st Style
14. Now check that ALL occurrences of the word "case" are highlighted in blue, no matter their case.

### Expected Behavior

I expected that all occurrences were already colored blue after executing step 10.

### Actual Behavior

They were not colored blue after executing step 10, instead, some occurrences that did not exactly match the case were skipped.
The correct coloring only happened after step 13, so when a case insensitive search was done before it.

### Debug Information

Notepad++ v7.5.9   (32-bit)
Build time : Oct 14 2018 - 15:02:52
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10 (64-bit)
Plugins : DSpellCheck.dll mimeTools.dll NppConverter.dll NppExport.dll AnalysePlugin.dll NppTextFX.dll PluginManager.dll PythonScript.dll 

Motivation:
I created a search engine (launched with hotkey in Notepad++) operating on a structured text file which produces a "search result"-file - a simple text file - as result, which is then opened by launching a fresh Notepad++ instance with it. Plugin PythonScript is installed. Its Startup.py is modified, such that it searches every opened file for some tags (which are only present in the specific search result file).
The script reads the tags and some keywords (which were used by the search engine), then it applies Style Tokens to the first 5 keywords. But as the colors are currently only applied to the case-exact matches of the keywords, the search overview is not complete (and the hot-keys Crtl-1..Crtl-5 will only jump to the colored ones). I'd like to see all cases to be colored - and so usable with Crtl-1..Ctrl-5.

**Comment by sasumner** [comment]
I'm not understanding your complaint here, can you help clarify?  For me when I try it, the behavior follows the state of the Match Case checkbox.  If that is ticked when a Style command is invoked, only exact case matches are stylized.  If that is unticked when Style is run, then all any-case versions are stylized.  I believe this is how it is supposed to work and I see no inconsistency.

**Comment by sasumner** [comment]
Oh...I think I see it now.  Programmatic control over the Match Case checkbox would solve your problem here.  :-)

**Comment by ebouden** [comment]
Ok, great, let me know the outcome J

**Comment by sasumner** [comment]
> Ok, great, let me know the outcome

So I don't know what this means.  If there is further activity on your issue, you will see it here.

**Comment by ebouden** [comment]
I think next is the case here:
The default case-sensitivity used by the Style Token coloring feature after starting Notepad++ is always case-sensitive and can differ from the case-sensitivity as shown in a subsequent Find-dialog, which is **unexpected**. 
Only after having opened that Find-dialog (or having pressed Crtl-F3), the case-sensitivity setting of the Find-dialog is copied into the case-sensitivity of the Style Token feature, and from that moment on, the case-sensitivity of the Find-dialog and the Style token feature are the same, which is **expected**.

**Comment by ebouden** [comment]
I accidentally closed the issue, sorry.

**Comment by ebouden** [comment]
The issue is solved by @Alan-Kilborn using a work-around, which even results in nicer code.
(so the "bug" is still there, but I got a solution to my problem)
By doing the search ourselfs using "editor.research()" and color the instances one by one instead of letting Notepad++ doing the Style Token searching and coloring for us, it is achieved that the initial case sensitivity setting is not needed at all.
The color is now correctly applied to all occurrences, case insensitive. Next piece can be integrated into startup.py:

import re

def style(x): return 26 - x

def match_found(m):
    editor.setIndicatorCurrent(style(1))
    editor.indicatorFillRange(m.span(0)[0], m.span(0)[1] - m.span(0)[0])

editor.setIndicatorCurrent(style(1))
editor.indicatorClearRange(0, editor.getTextLength())
editor.research(r'\Qhello...there', match_found, re.I)

# hello...there
# Hello...There
# HELLO...THERE

**Comment by sasumner** [comment]
@ebouden The issue may be solved for YOU via a workaround, but the actual issue still exists.  Please reopen.

**Comment by ebouden** [comment]
The issue is solved by @Alan-Kilborn using a work-around, which even results in nicer code.
(so the "bug" is still there, but I got a solution to my problem)
By doing the search ourselfs using "editor.research()" and color the instances one by one instead of letting Notepad++ doing the Style Token searching and coloring for us, it is achieved that the initial case sensitivity setting is not needed at all.
The color is now correctly applied to all occurrences, case insensitive. Next piece can be integrated into startup.py:

import re

def style(x): return 26 - x

def match_found(m):
    editor.setIndicatorCurrent(style(1))
    editor.indicatorFillRange(m.span(0)[0], m.span(0)[1] - m.span(0)[0])

editor.setIndicatorCurrent(style(1))
editor.indicatorClearRange(0, editor.getTextLength())
editor.research(r'\Qhello...there', match_found, re.I)

# hello...there
# Hello...There
# HELLO...THERE

**Comment by ebouden** [comment]
Reopened because despite my issue is being solved, the bug is not yet solved. Thanks @sasumner .

**Comment by donho** [comment]
https://github.com/notepad-plus-plus/notepad-plus-plus/commit/0dbdef320f8ce89d348959c3224210444f992532
