### ISSUE TITLE
Mac notepad++, Please!

### ISSUE THREAD

**Issue by lefwell** [notepad-plus-plus/notepad-plus-plus#515]
All my notes are written by notepad++, I do like it. But why there is no Mac edition.... ~_~_~_~_~_~_~

**Comment by milipili** [comment]
Notepad++ is currently not cross-platform but we're thinking about it.
winbottler: https://www.youtube.com/watch?v=k0nKurJKNbM

**Comment by lefwell** [comment]
Finish think'ng, just do it~~~~  ^_^

**Comment by milipili** [comment]
lol

**Comment by Croydon** [comment]
See #332.

**Comment by ariccio** [comment]
Also: See links in [my comment on #332](https://github.com/notepad-plus-plus/notepad-plus-plus/issues/332#issuecomment-115416873)
