### ISSUE TITLE
Functionlist breaks with this small string for php files

### ISSUE THREAD

**Issue by TheiAndy** [notepad-plus-plus/notepad-plus-plus#5150]
### Description of the Issue
I looked over the other Functionlist issues and didn't see this particular problem.  I believe I've broken it down as much as possible:
 
Functionlist has an issue showing any functions inside classes when this string is present (and the functions are private, protected or public) in a php file:

`$string = "\"{";`

### Steps to Reproduce the Issue
1.  Create a test.php file
2.  copy paste the following into it:

```
<?php
class test{
	protected function blah(){
		$string="\"{";
	}
}
?>
```

3. Save the file, then look at the function list. Next, take out the word "protected" or comment out the string, save, and then the function list works again.

### Expected Behavior
I was expecting it to show the functions in the file even with that string in the function. I can work around it by adding a chr(123) to any string that needs an open bracket (and is followed by an escaped double quotes), but it would be nice if I didn't have to do that. 

### Actual Behavior
No functions were shown in the list.

**Comment by MAPJe71** [comment]
Please try my updated PHP parser posted [here](https://notepad-plus-plus.org/community/topic/15124/php-function-list-and-abstract-functions/11).

**Comment by TheiAndy** [comment]
Hi MAPJe71, it works fine with your parser.  I'll use your parser and let you know if any issues come up with it. Thanks for making that.  

Just FYI, I had to change the displayName to "PHP" like it was on the old parser for it to work. (I'm guessing because I didn't change anything else besides the parser)
