### ISSUE TITLE
How to make Tab in Group

### ISSUE THREAD

**Issue by ardianzack** [notepad-plus-plus/notepad-plus-plus#5154]
How to make Tab in Group or how to manage tab with group, example
I have 2 project, let see Project A and Project B

In Project A, I open 2 files, tab1, tab2
If I want to open Project B, show tab group Project B let see in Project B, I open 3 file, Tab1,Tab2,Tab3
If I want to open Project A, show tab group Project A, tab1, tab2

Workspace cant deliver it..., this like multi desktop in linux

**Comment by MetaChuh** [comment]
@ardianzack 

i am sorry, but we can not understand your question.
please visit our notepad++ community, to work out your question.

thank you for your help and best regards.

-----
```
general notes:

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).
please file an issue as easy to understand and reproducible as possible.

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
(no extra account is needed, just use your github account to sign in)
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)
