### ISSUE TITLE
Holding any key while hitting tab will duplicate the characters after the cursor

### ISSUE THREAD

**Issue by jdbaker** [notepad-plus-plus/notepad-plus-plus#5155]
### Description of the Issue
Holding any key while hitting tab will duplicate the characters after the cursor.
It only works for lines 63 or fewer characters long. It doesn't have to be the first line.

### Steps to Reproduce the Issue

1. Create a line of text 63 or fewer characters long.
2. Place the cursor at position 0
3. Hit any character key (I used 'g' )
4. Hit Tab.

### Expected Behavior
I expect 'g' '\t' to be entered into the document as text.

### Actual Behavior
The command inserts 'g' followed by all characters from the cursor to the end of line.

### Debug Information
Version 7.4.2
No plugins

**Comment by sasumner** [comment]
Probably should point out that this only happens (well, for me when I tried it) with Auto-Completion enabled with a 1 in the "From _ th character".  These are the default settings.

I guess I'd say it's a bug, but is Tab supposed to do _anything_ when the auto-complete dropdown box is open?  I can't say as I can't stand the Auto-Completion feature and have never left it enabled for any longer duration than is necessary to notice it is "on" and to go turn it "off".  :-)

**Comment by jdbaker** [comment]
@DavidHansen-0x454d43 

It's not a real bug. Auto complete is replacing the substring from the cursor with the full line: thus "appending" the text from the cursor to the end. There is some limit to how long a line the auto complete will attempt to guess. Looks like 63 characters.
