### ISSUE TITLE
feature request : javascript language add let keyword in syntax highlighter. 

### ISSUE THREAD

**Issue by darkworks** [notepad-plus-plus/notepad-plus-plus#5157]
### Description of the Issue

when i open javascript file in notepad++ then i can see "var" high lighter in bold blue color i wish that it do for "let"

### Steps to Reproduce the Issue
1.   open notepad++
2.  from language menu select javascript 
3.  type var you will see that its written in bold blue color  if your write let it not bold or any color to indicate that its js keyword.

**Comment by hiteshgaur** [comment]
Isn't 'let' keyword already there? Check line numbers 180 and 183 in language model XML file.[https://github.com/notepad-plus-plus/notepad-plus-plus/blob/master/PowerEditor/src/langs.model.xml](url)

**Comment by darkworks** [comment]
you can see its not highlighted 

![image](https://user-images.githubusercontent.com/12841788/50352200-573e1400-0566-11e9-91e3-886d5783eaa4.png)

**Comment by hiteshgaur** [comment]
I am sorry mate. you can see it's highlighted.. at my system

![image](https://user-images.githubusercontent.com/12425225/50352727-c33f5e80-050b-11e9-8463-b5633d13a096.png)

**Comment by darkworks** [comment]
hmmmm why not it my notepade it looks highlighted , i have installed fresh windows and fresh notepad ++   
![image](https://user-images.githubusercontent.com/12841788/50357647-7cd41900-0578-11e9-8a65-6ab24fac4d63.png)

**Comment by hiteshgaur** [comment]
From your previous screen-shot, it looks like you had selected 'java' as your language, not 'javascript'..

![image](https://user-images.githubusercontent.com/12425225/50362088-eb3eba00-052b-11e9-923c-cf05096f9a3b.png)

**Comment by darkworks** [comment]
no i checked it its javascript selected , beside this when i open dot js files it same

**Comment by ArkadiuszMichalski** [comment]
In NPP 7.9 RC `let` keywords is interpretated as `var`.

![test](https://user-images.githubusercontent.com/2730894/93654395-83c5df00-fa1d-11ea-87a6-6d26c3e5c30a.gif)

@darkworks @SoiTrang You still have this problem?

**Comment by donho** [comment]
I think this issue is outdated.

**Comment by darkworks** [comment]
> I have the same problem with @darkworks. Some keywords is display correctly, but some (include **let**, **setTimeout**, ...) are not.

oh sorry for late reply , well ya i have same issue 


![image](https://user-images.githubusercontent.com/12841788/93666961-d219c300-fa9b-11ea-8aa6-5a324e264e99.png)

note pad version

![image](https://user-images.githubusercontent.com/12841788/93666939-9d0d7080-fa9b-11ea-95ef-21b4d865f9e3.png)


am not sure why this concurring just with me  LOL , in 2018 i had another latop now  in 2020 i have new laptop and it have same issue too.

**Comment by ArkadiuszMichalski** [comment]
@darkworks  Looks like your NPP version use some old config files. Please download .zip or .7z folder http://download.notepad-plus-plus.org/repository/7.x/7.9.RC/, unpack, run (as portable, just run `notepad++.exe`, but close all other notepad++ instance if you have any open) and check once again if your file not work (in my setup it works).

**Comment by darkworks** [comment]
ok i tried but same issue

![image](https://user-images.githubusercontent.com/12841788/93668954-caf9b180-faa9-11ea-8ac0-16550be6b953.png)


![image](https://user-images.githubusercontent.com/12841788/93668963-d4831980-faa9-11ea-8ab9-e6d98da03728.png)


can u tell where are its config files so that is possible manually it can be changed

**Comment by SoiTrang** [comment]
@ArkadiuszMichalski 
My current npp (v.7.8.9 32bit) still have this issue. But I've tried to download 7z portable as you mention, and it works correctly. Maybe the installed version has old configuration. Thanks.

**Comment by darkworks** [comment]
> @ArkadiuszMichalski
> My current npp (v.7.8.9 32bit) still have this issue. But I've tried to download 7z portable as you mention, and it works correctly. Maybe the installed version has old configuration. Thanks.

hmmm that mean something wrong with npp ,  npp team should update the installer so that it flush old settings of languages

**Comment by ArkadiuszMichalski** [comment]
@darkworks https://npp-user-manual.org/docs/config-files/ Probably here `%AppData%\notepad++\`. Where you unpac this .zip version, to own folder or to Program Files? Unpack to own folder and run, and give info form `? >> Debuging Info...`

**Comment by SoiTrang** [comment]
> > @ArkadiuszMichalski
> > My current npp (v.7.8.9 32bit) still have this issue. But I've tried to download 7z portable as you mention, and it works correctly. Maybe the installed version has old configuration. Thanks.
> 
> hmmm that mean something wrong with npp , npp team should update the installer so that it flush old settings of languages

I think the installer should not flush old settings of languages, because user might change something to fit their needs.

**Comment by ArkadiuszMichalski** [comment]
On the one hand, it's good that it does not change (because these are user settings), but on the other hand it generates a lot of such unnecessary bugs.

**Comment by darkworks** [comment]
LOL looks like am living in 2014 

![image](https://user-images.githubusercontent.com/12841788/93742386-72d8c180-fc07-11ea-9b03-b928737a1707.png)

seems like during migration my old notepadd++ settings were copied too.

and its not updated since 2014

can u tell where is config location in repo : https://github.com/notepad-plus-plus/notepad-plus-plus
so that i can copy from it

**Comment by ArkadiuszMichalski** [comment]
Here https://github.com/notepad-plus-plus/notepad-plus-plus/blob/master/PowerEditor/src/langs.model.xml, you can manually copy content of this file to your `langs.xml`.
