### ISSUE TITLE
Lines Filter dialog - Feature Request

### ISSUE THREAD

**Issue by antonmilev** [notepad-plus-plus/notepad-plus-plus#5165]
<img width="522" alt="scrrenshot" src="https://user-images.githubusercontent.com/46096854/50426842-c4241780-08a0-11e9-9ab6-620415dd9cf0.png">
Hello.

I frequently use this and need a simple way to filter text lines. Since I am developer by myself I added such filter dialog in the latest Notepad++ which I got from GitHub.

I added a new menu item "Filter Lines" in Edit->Line Operations, it opens the dialog (see attachment). When button is clicked it remove/leave only lines meeting the chosen condition, depending if Not is checked. There are so far only 3 conditions - "Begins With", "Ends With" and "Contains". 

Even as it may looks simple it is quite useful in many cases. Source is complete but it needs review and I have some questions about the project organization (like GUI ids).

Please let me know if I can add this feature to Notepad++ because is not convenient to merge it after each release.

Thanks.

**Comment by antonmilev** [comment]
These means that B also should remain/removed if there are only spaces or tabs before it.  -

**Comment by justanotheranonymoususer** [comment]
> Remove if starts with

`^B.*\r?\n`

> ends with

`^.*B\r?\n`

> contain

`^.*B.*\r?\n`

>  Remove if not starts with

`^[^B\r\n].*\r?\n`

> ends with

`^.*[^B\r\n]\r?\n`

> contain

`^[^B\r\n]*\r?\n`

> These means that B also should remain/removed if there are only spaces or tabs before it.

`^[ \t]*B.*\r?\n`
`^.*B[ \t]*\r?\n`
`^.*B.*\r?\n` (same)
`^[ \t]*[^B\r\n \t].*\r?\n`
`^.*[^B\r\n \t][ \t]*\r?\n`
`^[^B\r\n]*\r?\n` (same)

**Comment by antonmilev** [comment]
Ok,  thanks. 

Very well.
^.*[^B\r\n \t][ \t]*\r?\n - this is actually "leave only ending to B or B with trailing spaces or tabs"

It is good these to be placed somewhere.

**Comment by antonmilev** [comment]
^.*BB.*\r?\n - remove only lines containing BB

**Comment by sasumner** [comment]
This is an "issues" list not a "questions" forum.  Suggest you close this and take questions to https://notepad-plus-plus.org/community/

**Comment by MetaChuh** [comment]
-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
(no extra account is needed, just use your github account to sign in)
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)
