### ISSUE TITLE
CARET DISPLAY

### ISSUE THREAD

**Issue by ROBTWARREN** [notepad-plus-plus/notepad-plus-plus#5166]
May I suggest a simple feature improvement for a future release. Currently the insert caret can be a full block but the overwrite caret is limited to a thin underline. Many times it is difficult to see this thin underline caret regardless of color. I would propose having an option to make the overwrite caret also a full block and having the insert and overwrite carets optionally different colors.

**Comment by MetaChuh** [comment]
this is depending on the implemented scintilla component.
unfortunately scintilla is an external project, so you will have to file your feature requests at the [<kbd>scintilla feature-request tracker</kbd>](https://sourceforge.net/p/scintilla/feature-requests/).
we apologise for that.

many thanks and best regards.

**Comment by sasumner** [comment]
For reference: https://sourceforge.net/p/scintilla/feature-requests/1217
