### ISSUE TITLE
Crash after switching the language to "Normal Text" and then again to "Makefile"

### ISSUE THREAD

**Issue by aka-sps** [notepad-plus-plus/notepad-plus-plus#5170]
### Description of the Issue
Notepad ++ crashes (for some makefiles) when the "Language" manually changed to a "Makefile".

### Steps to Reproduce the Issue

1.  Load more or less complex Makefile (for example https://github.com/Reference-LAPACK/lapack/blob/master/BLAS/SRC/Makefile)
2.  Select menu "Language/Normal Text"
3.  Select menu "Language/Makefile"
4. Wait. Notepad++ hangs, consumes memory and then crashes without any notification.

### Expected Behavior

Normal Language switching.

### Actual Behavior

Crash.

### Debug Information

Notepad++ v7.6.1   (64-bit)
Build time : Dec 12 2018 - 01:22:05
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10 (64-bit)
Plugins : DSpellCheck.dll mimeTools.dll NppConverter.dll NppRegExTractorPlugin.dll NppXmlTreeviewPlugin.dll XMLTools.dll 

Notepad++ v7.6.2   (64-bit)
Build time : Jan  1 2019 - 00:02:38
Path : c:\Program Files\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10 (64-bit)
Plugins : DSpellCheck.dll mimeTools.dll NppConverter.dll NppRegExTractorPlugin.dll NppXmlTreeviewPlugin.dll XMLTools.dll

**Comment by SinghRajenM** [comment]
Not able to reproduce with v7.6.6

**Comment by MetaChuh** [comment]
@pike168 

we can not reproduce a crash, when opening a makefile, like the provided example makefile downloaded as raw data, and switching forth and back between text and makefile language lexer, in notepad++ 7.6.6 x86 and x64, via windows explorer on win7 pro x64 and win10 pro x64 (build 1809).

if your issue persists, please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html).
if possible, conduct an uninstall, purging of all notepad++ folders and plugins of installed versions, and clean install. 

note: you can also test non destructively, with a separate portable version, before you make a clean install:

* download the notepad++ 7.6.6. 64 bit portable version from [>>> here <<<](https://notepad-plus-plus.org/repository/7.x/7.6.6/npp.7.6.6.bin.x64.zip).
(the portable version does not require any installation and runs completely independent and isolated from your installed version. all custom settings, as well as any stuff you might want to try at the portable version, will not modify your installed version)

* extract `npp.7.6.6.bin.x64.zip` to e.g. your desktop.

* **important note:** make sure to close all instances of notepad++ that might be running, before starting the portable version at the next step, to be sure you are using the portable version for this test.

* open the extracted `npp.7.6.6.bin.x64` folder and start this portable version by double-clicking on `notepad++.exe` inside this folder.
(note: notepad++.exe will just be seen as notepad++, if you have enabled to hide all known file extensions at your explorer settings)

* test any makefile at this portable version of notepad++.

thank you for your help and best regards.

-----
```
general notes:

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
```
[<kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd>](https://notepad-plus-plus.org/community/)

**Comment by aka-sps** [comment]
I like your quick response. After four months, you have solved this question in just one hour.

Confirm: Not able to reproduce with v7.6.6. Try reproduce with v7.6.1
