### ISSUE TITLE
Cannot disable auto-update per machine

### ISSUE THREAD

**Issue by alexhass** [notepad-plus-plus/notepad-plus-plus#5173]
I need to disable auto-update per machine, not just per user. How can this done?

Background: The user has no permission to install newer version of the software. Every user needs PluginAdmin and the auto-update for his _per User_ plugins need to be enabled, but he cannot update NPP itself.

NPP 7.6.1

**Comment by MetaChuh** [comment]
make your settings at one user account.

copy `%AppData%\Notepad++\config.xml` of this user account to the notepad++ program folder of all machines you want to deploy these settings, and rename it to `config.model.xml`.

config.model.xml will now be used as template, to create a cnofig.xml for all new users, or at the first notepad++ start of an existing user.

**Comment by alexhass** [comment]
Please reopen this case. This template still allows users to re-enable it. As admin i cannot force disable updates. This need to work via GPOs.

This issue is not fixed and not outdated.

**Comment by donho** [comment]
@alexhass 
You can remove GUP.exe from `C:\Program Files\Notepad++\updater`.
By doing so, user will lost the capacity of PluginAdmin.

**Comment by alexhass** [comment]
That is no solution. The users need to plugin manager to install the plugins per user.

**Comment by donho** [comment]
@alexhass 
Sorry for late reply, I didn't see your answer.
In gup.xml (which is beside of GUP.exe), modify the following line:
`<InfoUrl>https://notepad-plus-plus.org/update/getDownloadUrl.php</InfoUrl>`
to 
`<InfoUrl></InfoUrl>`
This will stop update for GUP.exe

**Comment by alexhass** [comment]
Thanks for your answer. This stops npp update only, but plugin updates not?

**Comment by donho** [comment]
@alexhass 
My bad, 
`<InfoUrl>` cannot be empty. so just give it a random URL, in my case, I just remove `e` from `update`:
`<InfoUrl>https://notepad-plus-plus.org/updat/getDownloadUrl.php</InfoUrl>`

That will give the following result when users try to update manually:
![image](https://user-images.githubusercontent.com/90293/98398544-6c8c9080-2061-11eb-9f3b-32d7c0a6ec10.png)

And Plugins can be installed/updated/uninstalled via PluginAdmin without problem.

**Comment by alexhass** [comment]
Thanks for testing this.

How about implementing a clean solution?

**Comment by donho** [comment]
@alexhass 
> How about implementing a clean solution?

The clean solution is to remove GUP.exe - So it's rather IT's job.

**Comment by alexhass** [comment]
Removing GUP will stop plugin manager from my understanding. That is the problem. Npp update should be disabled, but plugin updates via plugin manager should still work. Plugins need to be installed PER USER, not per machine.

**Comment by alexhass** [comment]
Can you reopen the case, please?

**Comment by alexhass** [comment]
1. If GUP.exe ist removed the **Plugin Admin** is no longer available.
2. Notepad++ update itself need to be disabled, but PluginAdmin need to work.
3. Plugin Admin need to install Plugins to %APPDATA folder, not the machine (user has no permission).

**Comment by donho** [comment]
@alexhass 
The clean solution is to remove GUP.exe, but this will disable plugin admin. 
The workaround solution is modify the following tag in gup.xml to:
`<InfoUrl>https://notepad-plus-plus.org/updat/getDownloadUrl.php</InfoUrl>` which can be accomplished by PUSH action on the per machine I believe.

That's all I can offer. Hope you do understand.

**Comment by alexhass** [comment]
What you write is not the way how it works. That means additional code is needed.

1. Plugin admin need to work. That means gup need to stay where it is.
2. Npp update need to be disabled.
3. Removing or changing the info url breaks plugin admin. It cannot download and install plugins than.
4. An extra tag seems to be needed or a registry key (what is best). e.g. DisableNPPUpdate = 1
