### ISSUE TITLE
FunctionList C++ unitTest.expected.result is incorrect

### ISSUE THREAD

**Issue by Baptistou** [notepad-plus-plus/notepad-plus-plus#5176]
### Description of the Issue

The file [unitTest.expected.result](https://github.com/notepad-plus-plus/notepad-plus-plus/blob/master/PowerEditor/Test/FunctionList/cpp/unitTest.expected.result) is incorrect.
For example, the result doesn't contain the following functions from the unitTest file :
- LocalizationSwitcher::getLangFromXmlFileName
- LocalizationSwitcher::getXmlFilePathFromLangName

### Expected Behavior
The C++ parser should recognize these functions such as below :
![image](https://user-images.githubusercontent.com/16428197/50541009-35174800-0b9d-11e9-89fa-442b19043377.png)

### Actual Behavior
The actual C++ parser doesn't recognize every functions.

Related PR : [Update functionList.xml C++ parser #5175](https://github.com/notepad-plus-plus/notepad-plus-plus/pull/5175)

**Comment by ArkadiuszMichalski** [comment]
@donho Not fixed by https://github.com/notepad-plus-plus/notepad-plus-plus/pull/5175?

**Comment by Baptistou** [comment]
Yes fixed !
