### ISSUE TITLE
7.6.1 installer (32bit) detected as infected by Spybot Search & Destroy

### ISSUE THREAD

**Issue by caviidae** [notepad-plus-plus/notepad-plus-plus#5182]
Gen:Variant.Application.FileFinder.5 infection!
Spybot has identified and blocked the following application process as harmful to your computer:
npp.7.6.1.Installer.exe
Signed by: Notepad++

I downloaded the latest 32bit installer and my anti-spyware/virus complains about it when I try to run it. The same does not happen for the 7.6.1 64bit installer or the 7.6 32bit installer.

Is this a false positive? I could not find any information online about "Gen:Variant.Application.FileFinder.5"

**Comment by caviidae** [comment]
I also checked the hash against the website and github and all checked out

**Comment by ArkadiuszMichalski** [comment]
There were no other reports so I suspect this was false positive.
