### ISSUE TITLE
File associations set incorrectly

### ISSUE THREAD

**Issue by nthallen** [notepad-plus-plus/notepad-plus-plus#5192]
### File associations are not being set correctly
In v7.5.9, when I attempt to set file associations then exit Notepad++ and return, the file associations are not what was set. Specifically, I tried to set associations for .c, .cc, .h, and when I returned to the dialog, it appears that all extensions starting with '.c' had been assigned: (.c, .cc, .cda, .cdmp, .cdx, .cdxml, ...)

### Steps to Reproduce the Issue
1. Open Settings -> Preferences
2. Select File Association
3. Select '.c' and '->' to move it to registered extensions
4. Select '.cc' and '->'
5. Select '.h' and '->'
6. Select 'Close'
7. Exit Notepad++
8. Restart Notepad++
9. Open Settings -> Preferences
10. Select File Association
11. Observe current associations

### Expected Behavior
I expect the selected associations to remain unchanged.

### Actual Behavior
Additional file associations were set.

### Debug Information
Notepad++ v7.5.9   (32-bit)
Build time : Oct 14 2018 - 15:02:52
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10 (64-bit)
Plugins : DSpellCheck.dll mimeTools.dll NppConverter.dll NppExport.dll DoxyIt.dll NppFTP.dll NppTextFX.dll PluginManager.dll 

Windows 10 Home Edition

**Comment by DarkNami** [comment]
Try execute Notepad++ and set File Association with administrative rights.
Maybe #5000 will fix this issue.

**Comment by SinghRajenM** [comment]
@donho FYI
