### ISSUE TITLE
there are bug remains with plugin development

### ISSUE THREAD

**Issue by gurikbal** [notepad-plus-plus/notepad-plus-plus#5195]
### so i have to get know the status of file is just saved or not 

![capture-20190104-002158](https://user-images.githubusercontent.com/36083297/50656871-a8182880-0fba-11e9-8d54-5db1b8d0761f.png)

1. NPPN_FILEBEFORESAVE not works for me there
2. NPPN_FILESAVED not works for me there

**Comment by dail8859** [comment]
You'll have to be more specific. Such as how you are handling it and why you think you are not getting notified. Not sure what the image is for either.

I did a test with LuaScript and it is able to handle the notifications of files being saved:

![save](https://user-images.githubusercontent.com/3694843/50718697-43170e00-1060-11e9-9835-a0cda58e705c.gif)


Debug info:
```
Notepad++ v7.6.2   (32-bit)
Build time : Jan  1 2019 - 00:00:08
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : ON
Local Conf mode : OFF
OS : Windows 7 (64-bit)
Plugins : DSpellCheck.dll LuaScript.dll mimeTools.dll NppConverter.dll NppExport.dll NppLSP.dll 
```

**Comment by gurikbal** [comment]
[how to define save , save All , Undo or Redo button is currently Disabled or Enabled](https://github.com/notepad-plus-plus/notepad-plus-plus/pull/4242)

[after 3 years also did't he get a answer here](https://notepad-plus-plus.org/community/user/jeff-kelly)

**Comment by gurikbal** [comment]
where i found sci_modify but at startup not work
