### ISSUE TITLE
Ctrl key combination weird behavior

### ISSUE THREAD

**Issue by githubcatw** [notepad-plus-plus/notepad-plus-plus#5196]
### Description of the Issue
For some reason, Ctrl combinations behave strange.
For example, when selecting `ert` in `qwerty` and pressing Ctrl+C, I get `qwcy` with `ert` still being in the clipboard.

### Steps to Reproduce the Issue

1. Write `The quick brown fox jumps over the lazy dog`.
2. Select the word `lazy`.
3. Press Ctrl+C.
4. Go to the space between `quick` and `brown`.
5. Press Ctrl+V and add a space.

### Expected Behavior
`The quick lazy brown fox jumps over the lazy dog`

### Actual Behavior
`The quick lazyv brown fox jumps over the c dog`

### Debug Information
```
Notepad++ v7.6.1   (32-bit)
Build time : Dec 12 2018 - 01:24:22
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10 (64-bit)
Plugins : DSpellCheck.dll mimeTools.dll NppConverter.dll NppExport.dll 
```
[Here is my workspace](https://github.com/notepad-plus-plus/notepad-plus-plus/files/2728108/workspace.txt) (txt)

[Here is my session](https://github.com/notepad-plus-plus/notepad-plus-plus/files/2728117/session.txt) (txt)

**Comment by githubcatw** [comment]
Well, no one remembers that someone posted this issue. I reinstalled NPP and it still is present.

**Comment by githubcatw** [comment]
Hello?

**Comment by sasumner** [comment]
@githubcatw If your expectation here is responsiveness like a chat forum you are likely to be disappointed.  Maybe try posting at https://notepad-plus-plus.org/community as that is a more "interactive" place.

**Comment by githubcatw** [comment]
Nope, I was just asking if you can fix this problem. But I might try posting to the community.

**Comment by SinghRajenM** [comment]
I could not reproduce this with v7.6.6 both 32 and 64 bit - 

Notepad++ v7.6.6   (64-bit)
Build time : Apr  3 2019 - 23:52:32
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10 (64-bit)
Plugins : DSpellCheck.dll mimeTools.dll NppConverter.dll

**Comment by MetaChuh** [comment]
@githubcatw 

we are glad you got it fixed reportedly at the [community](https://notepad-plus-plus.org/community/topic/16915/ctrl-key-combination-weird-behavior).

thank you for your help and best regards.

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
```
[<kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd>](https://notepad-plus-plus.org/community/)
