### ISSUE TITLE
Run "Trim trailing space and save" with multi files

### ISSUE THREAD

**Issue by Cutetlaem** [notepad-plus-plus/notepad-plus-plus#5197]
Hello,
I want to ask how to run "Trim trailing space and save" with multi files (about 20 files) at the same time?
Going to each file and pressing the shortcut takes too much time.

**Comment by sasumner** [comment]
"Issues" really isn't a proper place to ask questions such as this.  Why don't you try this site?:  https://notepad-plus-plus.org/community

**Comment by ArkadiuszMichalski** [comment]
@sasumne All new actions performed on all files are potentially risky, as they usually cannot be undone in groups. This should be done via plugin, so maybe close this bug?
