### ISSUE TITLE
Notepad++ v7.5.9

### ISSUE THREAD

**Issue by Gauvreau** [notepad-plus-plus/notepad-plus-plus#5198]
### Description of the Issue

Updating to this version of Notepad++ overlaid the windows desktop app: Notepad.exe.  When I try to access the Notepad, I get to Notepad++ instead.  This is probably due to the following note under the changes.log:

Add 2 command line flags "-notepadStyleCmdline" and "-z" for the replacement of notepad.exe.

This also caused the XMLTools to disappear and the JSON viewer no longer works.
 
The XMLTools has been corrected internally at this time.

### Steps to Reproduce the Issue

1. See above
2. 
3. 

### Expected Behavior

I would expect that Notepad++ would work as expected AND that the desktop app Notepad would still  be available
### Actual Behavior

See above
### Debug Information

Notepad++ v7.5.9   (32-bit)
Build time : Oct 14 2018 - 15:02:52
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10 (64-bit)
Plugins : NppExport.dll XMLTools.dll DSpellCheck.dll mimeTools.dll NppConverter.dll NPPJSONViewer.dll PluginManager.dll

**Comment by MetaChuh** [comment]
if you have accidentally set notepad++.exe as replacement for notepad.exe:

* open up cmd as administrator.

* enter `reg delete "HKLM\Software\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\notepad.exe" /v "Debugger" /f` and press enter.

* reboot and try to run `notepad.exe`

if you need more help about usage, or about resetting the replacement, please visit us at our notepad++ community.

thank you for your help and best regards.

-----
```
general notes:

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
(no extra account is needed, just use your github account to sign in)
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)
