### ISSUE TITLE
Access rights to directory %ProgramData%\Notepad++\plugins are still set incorrectly by the installer

### ISSUE THREAD

**Issue by dinkumoil** [notepad-plus-plus/notepad-plus-plus#5199]
### Description of the Issue
Access rights to directory `%ProgramData%\Notepad++\plugins` are still set incorrectly by Notepad++ installer. Thus, normal Windows users are still allowed to write files to it or its subdirectories. It was the intention of commit 589e21151dc87acb523fb17c0a9e5ee3bfd2a73a to change that but it was done in the wrong way.

### Steps to Reproduce the Issue
1. Install Notepad++ v7.6.2.
2. Create a Windows user account without admin rights.
3. Log on as the user created in step 2.
4. Navigate to directory `%ProgramData%\Notepad++\plugins`.
5. Try to copy a file to that directory.

### Expected Behavior
A UAC dialog should pop up where you have to provide credentials of an admin user because normal users should not be able to drop files to `%ProgramData%\Notepad++\plugins`.

### Actual Behavior
Copying the file as normal user works without any problem, no UAC dialog pops up.

### Debug Information
Applies to Notepad++ v7.6.2

### Additional informations
The directory `%ProgramData%\Notepad++\plugins` inherits access rights from the `%ProgramData%` directory. There, the user group `CREATOR OWNER` is configured to have **all** access rights. That means that **every user account can write NEW files and subdirectories** to `%ProgramData%` and its subdirectories. Furthermore, **every user account can only delete/overwrite/change files and subdirectories which had been created by itself**.

It is not possible to simply remove this access right from `%ProgramData%\Notepad++\plugins` or to replace it with a restricted access right like it was tried in commit 589e21151dc87acb523fb17c0a9e5ee3bfd2a73a. Instead ownership of the directory has to be set to the `ADMINISTRATORS` user group,  the **access rights inheritance** has to be removed from the directory and a **manually configured set of access rights** has to be set because after removing access rights inheritance the directory has no access rights at all.

I already elaborated about that in [this comment at the community forum](https://notepad-plus-plus.org/community/topic/16645/new-plugins-home-where-notepad-will-load-from/53). Another user stated the same in [this comment at the community forum](https://notepad-plus-plus.org/community/topic/16645/new-plugins-home-where-notepad-will-load-from/63).

Additionally the access rights of the directory `%ProgramData%\Notepad++\plugins\config` have to be reconfigured in a way that writing to it is allowed for **all** user accounts in order to be able to update the file `nppPluginList.dll`.

Suggested access rights for directory `%ProgramData%\Notepad++\plugins`:

* Owner: ADMINISTRATORS user group
* SYSTEM -> Full access
* ADMINISTRATORS -> Full access
* USERS -> Read & Execute, List folder contents, Read

Suggested access rights for directory `%ProgramData%\Notepad++\plugins\config`:

* SYSTEM -> Full access
* ADMINISTRATORS -> Full access
* USERS -> Full access for files and directories **in it**

**Comment by donho** [comment]
Thank you for the info.
With the new scheme we don't need any more to change ACL :
https://github.com/notepad-plus-plus/notepad-plus-plus/commit/9fecbae030f33a31b131a75cf41b243c6ea36751
