### ISSUE TITLE
Delete/modify Shortcut/Macro menu with 0 items results in crash

### ISSUE THREAD

**Issue by Zeriph** [notepad-plus-plus/notepad-plus-plus#520]
Not sure how long this has been an issue, but in 6.7.9.2, if you go to 'Settings'->'Shortcut Mapper' and in the 'Macros' and 'Run Commands' grids, if there are no items and 'Modify' or 'Delete' is clicked, N++ crashes due to a null pointer reference on an invalid index and it can't recover due to a pure virtual function call error (probably due to the stack being messed up afterwards). I already have a patch and will do a pull request (it's in BabyGrid.cpp, BabyGridWrapper.h and ShortcutMapper.cpp).

**Comment by donho** [comment]
I believe this issue has been fixed since long time ago.
Update your Notepad++ to the latest version (v7.6.6).
If the issue persists, please create a new issue for it.
Thank you.
