### ISSUE TITLE
The strange behavior of the cursor in the Notepad + + window

### ISSUE THREAD

**Issue by andrecool-68** [notepad-plus-plus/notepad-plus-plus#5200]
The strange behavior of the cursor in the Notepad + + window, it constantly flickers when hovering over the menu and buttons. There is no such thing in other applications. 
I have seven 32-bit, no viruses, the system is not dirty, Notepad + + updated to the latest version. This has been going on for a long time and on all versions of Notepad + +. Reboot Notepad + + and all disappears flicker, and then again appears this jamb. The axis for as long as the years were re-installed and Notepad + + was updated, the problem still remained.
It was the same in safe mode.

![6og3j-gigbo](https://user-images.githubusercontent.com/3471892/50728951-4e3e6c80-113a-11e9-87a9-9c27355149b8.gif)

![t1do0-gp9yb](https://user-images.githubusercontent.com/3471892/50729138-55b34500-113d-11e9-8955-7d3296a71c32.gif)

I reinstalled the operating system. It just happened again. I watched what was in the task manager (QTranslate, Google Chrome, Notepad ++, Everything)
closed QTranslate and the disappearance was gone, Notepad ++ was open at this time.
Maybe the reason is the QTranslate translator?

![default](https://user-images.githubusercontent.com/3471892/50794481-e91e7e80-12d3-11e9-8578-82de9d81a7f8.png)

Perhaps this option makes the problem?
But I often need this option in the translator.
It takes time to prove the guilt of QTranslate, perhaps this is a temporary coincidence.

![_2019_01_25_16_09_55_701](https://user-images.githubusercontent.com/3471892/51750887-0fa62d00-20bc-11e9-91f9-047d8908a44b.gif)

Help solve this problem, the cursor artifacts are enraged by the terrible.

Notepad++ v7.6.2   (64-bit)
Build time : Jan  1 2019 - 00:02:38
Path : C:\Tools Servis\Notepad++\notepad++.exe
Admin mode : ON
Local Conf mode : ON
OS : Windows 7 (64-bit)
Plugins : ComparePlugin.dll DSpellCheck.dll HTMLTag.dll JSMinNPP.dll mimeTools.dll NppConverter.dll NppSnippets.dll XMLTools.dll _CustomizeToolbar.dll 

Reinstalling Windows 7 (64-bit) does not help!

**Comment by MetaChuh** [comment]
closed with https://github.com/notepad-plus-plus/notepad-plus-plus/commit/687c6486a347ff6eb36c77c1311c7a2f256b3e94
