### ISSUE TITLE
Auto Detect UTF-8 Encoding for French is broken in Notepad++ 7.6.x (detects vietnamese windows-1258)

### ISSUE THREAD

**Issue by MetaChuh** [notepad-plus-plus/notepad-plus-plus#5202]
### Description of the Issue
Auto Detect UTF-8 Encoding for French is broken in Notepad++ 7.6.x

### Steps to Reproduce the Issue
1. create a new utf-8 document in notepad++
2. paste or write the word "Mosaïque" in it
3. save as test.txt
4. close test.txt in notepad++ and reopen it
(or close notepad++ and reopen it if sessions are enabled)

same for this file (direct download link to paquet.xml):
https://zone.spip.net/trac/spip-zone/export/HEAD/spip-zone/_plugins_/mosaique/trunk/paquet.xml

further information and files to test, submitted by Franckybleu, at: https://notepad-plus-plus.org/community/topic/16873/encodage/3

### Expected Behavior
test.txt should be detected as utf-8

### Actual Behavior
test.txt is detected as vietnamese windows-1258

### Debug Information
Notepad++ v7.6.2   (32-bit)
Build time : Jan  1 2019 - 00:00:08
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 7 (64-bit)
Plugins : DSpellCheck.dll mimeTools.dll NppConverter.dll NppExport.dll

Edit:
if you write the word “Réservation” to a new utf-8 file and save and reopen it it is also detected as vietnamese.

@guy038 has discovered, that the sentence "Cette mosaïque était jolie" in a new utf-8 file will be detected correctly as utf-8
but further tests show that a utf-8 file only containing one of the words mosaïque or était will be detected as vietnamese, so only the combination of in this example an existing ï and an existing é will detect correctly.

same vietnamese detection happens with spanish, except if an ñ is present.
german characters seem to work fine

**Comment by chcg** [comment]
See also #431. So the better place for this would be https://bugs.freedesktop.org/enter_bug.cgi?product=uchardet as uchardet 0.0.6 was included  with https://github.com/notepad-plus-plus/notepad-plus-plus/commit/bfb7e863cc6cd20f9f32389bee289607a212b12b

**Comment by MetaChuh** [comment]
@chcg 
thanks for the info.

i submitted this issue here, due to a french user at the community which provided good examples that lead to further testings at the community.

it is of course yours and dons choice if you commit a regression or wait for a fix at ucharted, so that there is no more fallback to vietnamese if there is a trigger but no certainty.

**Comment by MetaChuh** [comment]
@chcg @donho 

i've just compiled and tested uchardet 0.0.6 as stand-alone cli and it does not produce this issue.
all files and samples listed above are detected correctly as utf-8, for example [paquet.xml](https://zone.spip.net/trac/spip-zone/export/HEAD/spip-zone/_plugins_/mosaique/trunk/paquet.xml)
so there is no need to open an issue about that at freedesktop.org

![Imgur](https://i.imgur.com/knrY3ki.png)

@chcg 
did you test the steps to reproduce listed above, or did you just assume that the original uchardet 0.0.6 code could be the source of this issue ?
please test the steps to reproduce listed above and also uchardet 0.0.6 as stand alone on the same files if you have the time.

**Comment by chcg** [comment]
@MetaChuh I didn't test it, but thought as the checkin https://github.com/notepad-plus-plus/notepad-plus-plus/commit/bfb7e863cc6cd20f9f32389bee289607a212b12b contains the released version from https://www.freedesktop.org/software/uchardet/releases/uchardet-0.0.6.tar.xz (with some differences for compiler warnings and line endings) that the behaviour would be identical.

If this is not the case :-( and has to be investigated.

Seems you used some precompiled version from ubuntu, is this correct?
Did you compile also compile the commandline version for windows and checked the examples there?

**Comment by MetaChuh** [comment]
btw: thanks for looking into it and sorry for my sometimes very direct way of asking for things.
i'm a very thorough tester, and once i have enough information and an explicit reproducibility, i tend to forget to communicate it with more patience and politeness to devs.

note: i behave differently, with almost exhaustless patience and politeness, towards notepad++ users and newbies with a question, even if it has been asked a (perceived) million times before.
i sincerely apologise for not showing the same behaviour internally, but i'm working on that ... i promise ;-)

**Comment by MetaChuh** [comment]
completely off topic and triggered by a thumbs up:

@sasumner we still miss you.

if your first thought is, that 4 years+ of exhaustless, patient and productive support is enough, and it's time to move on, thinking many (but by far not all) things you've taught have already been already assimilated by other readers, you're right ...

... but nevertheless, even if you decided you don't want to read or answer any more questions, i think you can imagine what it would mean, once a year or so, to hear a comment or hello from teacher to alumni, regardless if it's sarcastic or not 😉

**Comment by MetaChuh** [comment]
hi @donho, @SinghRajenM, @chcg, an all

i have continued testing, because i still can't understand why the same uchardet 0.0.6 source code behaves differently on windows than on ubuntu or mac.

in addition to the ubuntu and mac uchardet test builds i made, i've built uchardet.exe cli tool on windows (native not cygwin), using the **same, identical, official source code** from
here: https://www.freedesktop.org/software/uchardet/releases/uchardet-0.0.6.tar.xz
(clean and newly extracted from the tarball)
as suggested by @chcg ...



... and the result has to be a **work of evil, evil witch-craft** 😉:

the **same source code** behaves **completely different on windows**, than on ubuntu and mac !!! 

the linuxoid builds detect all files i've tested correctly, but the windows uchardet.exe cli build shows the same, multiple, erroneous mismatches, on the same test files from above, as the notepad++ implementation does !?!?!?! 🤔❓

**only one** of the 4 test files is detected **correctly** on **windows**.
but on **linuxoid builds, all 4 files are detected correctly**. 



here is the screenshot of the windows cli tests of the same files from above:

![Imgur](https://i.imgur.com/FZDyj4Y.png)

and here again on ubuntu (same uchardet 0.0.6 source code, same files) for direct comparison:

![Imgur](https://i.imgur.com/knrY3ki.png)

-----

heeeeeeelp ... i'm getting bonkers over this phenomenon, as i don't understand it at all.
i currently feel like a maggot that tries to understand the big bang theory 😉😂 .

greetings and best regards, metachuh

**Comment by SinghRajenM** [comment]
> 
> 
> completely off topic and triggered by a thumbs up:
> 
> @sasumner we still miss you.
> 
> if your first thought is, that 4 years+ of exhaustless, patient and productive support is enough, and it's time to move on, thinking many (but by far not all) things you've taught have already been assimilated by other readers, you're right ...
> 
> ... but nevertheless, even if you decided you don't want to read or answer any more questions, i think you can imagine what it would mean, once a year or so, to hear a comment or hello from teacher to alumni, regardless if it's sarcastic or not 😉

Very surprising... Still not able to understand, why. 🤔

**Comment by MetaChuh** [comment]
@SinghRajenM 
> Very surprising... Still not able to understand, why. 🤔

is scott the only part of this issue you have read and noticed ? 😂😂👍

then i guess, that noone has any idea, or explanation, why the same uchardet 0.0.6 source code behaves differently on windows than on ubuntu.
maybe it really is evil, evil witch-craft 🤔

i think it will be best to regress to the old code, as no one understands this 0.0.6 phenomenon yet.

**Comment by Franckybleu** [comment]
Hello :-)
@MetaChuh The version 0.0.6 at two years, the problem is still present with master ?
https://gitlab.freedesktop.org/uchardet/uchardet/tree/master
Thanks for your help and sorry for my english :-(

**Comment by MetaChuh** [comment]
hi @Franckybleu 

i did not, but @vlakoff already has compiled the latest nightly from about yesterday, and it apparently has even worse results on windows than 0.0.6.

see his results here: https://github.com/notepad-plus-plus/notepad-plus-plus/issues/5310#issuecomment-464447576

> Thanks for your help and sorry for my english :-(

never worry, your english is better than my french, and both our language capabilities are still better than the current "uchardet on windows" auto-detection 😂😂😂

**Comment by MetaChuh** [comment]
@donho 

as the 7.6.4 release is probably near:

could you please disable "autodetect character encoding" as a default setting on notepad++ fresh installs and all portable versions, until a fix for UCharDet 0.0.6 on windows, or a regression to the old autodetect code is done ?

reason:
the broken autodetect is currently the most frequent incident topic over at the notepad++ community.

(we will cope with all requests of people that still have autodetect enabled, so it's not necessary to implement any force-disable of autodetect on update, if the user has autodetect still enabled)

here are some search results if you need a better overview of the amounts.
(note: there are more, those are only the searches that have the explicit words "character encoding" in their topics)

[notepad++ community search for "character encoding"](https://notepad-plus-plus.org/community/search/character%20encoding?in=titlesposts&sortBy=timestamp&sortDirection=desc&showAs=posts)

[google notepad++ community site search for "character encoding", limited to the time since notepad++ 7.6 release on 2018.11.13](https://www.google.com/search?safe=off&client=safari&rls=en&biw=1199&bih=812&tbs=cdr%3A1%2Ccd_min%3A11%2F13%2F2018%2Ccd_max%3A3%2F4%2F2019&ei=qp59XMaXCemLmwWwkZfoCw&q=site%3Anotepad-plus-plus.org+character+encoding&oq=site%3Anotepad-plus-plus.org+character+encoding&gs_l=psy-ab.12...0.0..15521...0.0..0.0.0.......0......gws-wiz.SEVu0r7vYtM)

thank you for your eventually possible consideration, or a short heads up if you have a reason not to, or any other doubts.
i respect and i'm grateful for any of your decisions regarding this.
