### ISSUE TITLE
There is no item in the context menu of Notepad++ Base64 Encode\Base64 Decode\Copy Text with Syntax Highlighting

### ISSUE THREAD

**Issue by andrecool-68** [notepad-plus-plus/notepad-plus-plus#5205]
**Notepad++  7.6.2  zip package 64-bit x64:**

![64](https://user-images.githubusercontent.com/3471892/50766565-67eacb80-1282-11e9-85a3-b102cdefeced.png)

**Notepad++  7.6.2  Installer 64-bit x64:**

![64](https://user-images.githubusercontent.com/3471892/50766570-6de0ac80-1282-11e9-810c-2be0f9ec37f3.png)

**The contextMenu.xml file has all these items!**

**Comment by donho** [comment]
I have tested latest version v**7.6.3** 64 bits zip package. Work for me.

**Comment by andrecool-68** [comment]
> Я проверил последнюю версию v **7.6.3** 64-битный пакет ZIP. Работа для меня.

There is no option "Copy Text with Syntax Highlighting"

![_2019_01_29_19_13_16_597](https://user-images.githubusercontent.com/3471892/51926494-16a1a800-23fa-11e9-8f9f-3ba965bf97f0.gif)

**Comment by chcg** [comment]
@andrecool-68 "Copy Text with Syntax Highlighting" depends on availability of plugin NppExport.dll.
mimeTools.dll provides the Base64 Encode\Base64 Decode functionality. So these plugins need to be available to have the context menu entries.

**Comment by andrecool-68** [comment]
I don't understand what you're talking about, these plugins are installed by default (by Notepad++ author)

**Comment by chcg** [comment]
@andrecool-68 Checked the reported plugins from your debug infos posted above:

64bit
Plugins : DSpellCheck.dll mimeTools.dll NppConverter.dll
vs.
32bit
Plugins : DSpellCheck.dll mimeTools.dll NppConverter.dll NppExport.dll

The NppExport.dll is just available for 32bit from the installation files, but not for 64bit.

You might want to take a look here: https://github.com/chcg/NPP_ExportPlugin/releases
, if you need a 64bit version of NppExport.dll

**Comment by andrecool-68** [comment]
@chcg I did not even notice that this plugin is missing. 
Thanks for help!

**Comment by andrecool-68** [comment]
![_2019_02_05_13_15_16_768](https://user-images.githubusercontent.com/3471892/52269969-37ad5000-2948-11e9-8170-8a345e248bba.gif)
Thanks for help!
