### ISSUE TITLE
Scroll Tab Bar with mouse wheel

### ISSUE THREAD

**Issue by Zeriph** [notepad-plus-plus/notepad-plus-plus#521]
When there's a lot of tabs open, it'd be nice to be able to scroll the tab bar view similar to how Firefox scrolls it's tabs to pick one when not using the Window Manager/Doc switcher. 

I've added this functionality in to TabBar.cpp (just added a couple of members and a case statement for the WM_MOUSEWHEEL event) and will submit for a pull request.

**Comment by dogancelik** [comment]
Would be a nice addition, very useful :+1:

**Comment by harigat** [comment]
This feature is really needed.
