### ISSUE TITLE
Plug in Manager only installs for current user

### ISSUE THREAD

**Issue by chessmate198** [notepad-plus-plus/notepad-plus-plus#5210]
### Description of the Issue
Plug in Manager and Plug in Directory install only for the current user and not All Users when installing Notepad++

We use a product called Quest KACE for patching in my company. KACE patches Notpad++ however it does so with TrustedInstaller system level permissions. When Notepad++ updates VIA KACE or a support tech installs it with "Run As" (as we keep our users workstations locked down) Access is lost to the plug-in manager and the plugin directory %localuserdata%\Notepad++\Plugins

As a result the User no longer has access to the plugin manager nor to the plugin directory

**Comment by MetaChuh** [comment]
plugin manager is not part of the notepad++ project.

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)
