### ISSUE TITLE
open *.arxml as *.xml Highlighted

### ISSUE THREAD

**Issue by EbATpy** [notepad-plus-plus/notepad-plus-plus#5215]
### Description of the Issue
arxml is AutoSAR  XML file 
https://www.autosar.org/

### Steps to Reproduce the Issue

1. Open *.arxml file
2. no Highlighted as xml file
3. 

### Expected Behavior
open *.arxml as *.xml Highlighted

### Actual Behavior
unknow file extenstion

### Debug Information

this is some exapmle arxml file

```

<?xml version="1.0" encoding="utf-8"?>
<!--Created with SystemDesk 4.5.0.8623-->
<AUTOSAR xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://autosar.org/schema/r4.0" xsi:schemaLocation="http://autosar.org/schema/r4.0 AUTOSAR_4-2-2.xsd">
	<AR-PACKAGES>
		<AR-PACKAGE>
			<SHORT-NAME>AUTOSAR</SHORT-NAME>
			<AR-PACKAGES>
				<AR-PACKAGE>
					<SHORT-NAME>Platform</SHORT-NAME>
					<AR-PACKAGES>
						<AR-PACKAGE>
							<SHORT-NAME>BaseTypes</SHORT-NAME>
							<ELEMENTS>
								<SW-BASE-TYPE>
									<SHORT-NAME>boolean</SHORT-NAME>
									<LONG-NAME>
										<L-4 L="EN">boolean</L-4>
									</LONG-NAME>
									<CATEGORY>FIXED_LENGTH</CATEGORY>
									<BASE-TYPE-SIZE>8</BASE-TYPE-SIZE>
									<BASE-TYPE-ENCODING>BOOLEAN</BASE-TYPE-ENCODING>
								</SW-BASE-TYPE>
								<SW-BASE-TYPE>

```

**Comment by sasumner** [comment]
That kind of thing is what THIS box is for:

![image](https://user-images.githubusercontent.com/30118311/50898885-7cdc7180-13de-11e9-94cc-8592380aa8a6.png)

Just do this:

![image](https://user-images.githubusercontent.com/30118311/50898914-954c8c00-13de-11e9-9fc0-97da176c56de.png)

**Comment by EbATpy** [comment]
Hello I found out , that new version of notepad++ is automatically detecting the xml file by opening now!
This issue can be close now!
