### ISSUE TITLE
Trying to generate SciLexer.dll without boost 

### ISSUE THREAD

**Issue by viveksejpal** [notepad-plus-plus/notepad-plus-plus#5216]
I'm a beginner trying to generate local Notepad-plus-plus exe file using source code.
I'm able to generate Notepad++.exe using visual Studio 2017, but unable to generate  SciLexer.dll file.

It might be a silly thing that I'm missing, but at my current level I'm unable to figure Out.

Thanks in advance. 👍 
The error log is as below:

### While trying to generate SciLexer.dll without boost: 
I'm getting the below error:
C:\sources\notepad-plus-plus-7.6.2\scintilla\win32>nmake NOBOOST=1 DEBUG=1 -f scintilla.mak

Microsoft (R) Program Maintenance Utility Version 14.16.27026.1
Copyright (C) Microsoft Corporation.  All rights reserved.

        link  -OPT:REF -LTCG -DEBUG -LIBPATH:\debug\link-static\runtime-link-static\threading-multi -DEF:Scintilla.def -DLL -OUT:..\bin\Scintilla.dll .\AutoComplete.obj .\CallTip.obj .\CaseConvert.obj .\CaseFolder.obj .\CellBuffer.obj .\CharacterCategory.obj .\CharacterSet.obj .\CharClassify.obj .\ContractionState.obj .\Decoration.obj .\Document.obj .\EditModel.obj .\Editor.obj .\EditView.obj .\Indicator.obj .\KeyMap.obj .\LineMarker.obj .\MarginView.obj .\PerLine.obj .\PlatWin.obj .\PositionCache.obj .\PropSetSimple.obj .\RESearch.obj .\RunStyles.obj .\Selection.obj .\Style.obj .\UniConversion.obj .\ViewStyle.obj .\XPM.obj .\HanjaDic.obj .\ScintillaBase.obj .\ScintillaWin.obj .\BoostRegexSearch.obj .\UTF8DocumentIterator.obj .\ScintRes.res KERNEL32.lib USER32.lib GDI32.lib IMM32.lib OLE32.LIB OLEAUT32.LIB
Microsoft (R) Incremental Linker Version 14.16.27026.1
Copyright (C) Microsoft Corporation.  All rights reserved.

**LINK : fatal error LNK1104: cannot open file 'libboost_regex-vc141-mt-s-x32-1_66.lib'
NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\bin\HostX86\x86\link.EXE"' : return code '0x450'
Stop.**

**Comment by sasumner** [comment]
More people that are willing to help will see this if you post this here?:  https://notepad-plus-plus.org/community

**Comment by viveksejpal** [comment]
> More people that are willing to help will see this if you post this here?: https://notepad-plus-plus.org/community

Thanks! I've now posted it over there.

**Comment by chcg** [comment]
@viveksejpal See 
https://github.com/notepad-plus-plus/notepad-plus-plus/blob/master/scintilla/boostregex/nppSpecifics.mak#L10

Do you have (..\boostregex\boostpath.mak)?

**Comment by viveksejpal** [comment]
> @viveksejpal See
> 
> https://github.com/notepad-plus-plus/notepad-plus-plus/blob/master/scintilla/boostregex/nppSpecifics.mak#L10
> 
> Do you have (..\boostregex\boostpath.mak)?

yes. I have that file.
The content of the file boostpath.mak is as below,:

# Autogenerated file, run BuildBoost.bat [path_to_boost] to generate 
BOOSTPATH=D:\libs\boost_1_55_0 
BOOSTLIBPATH=D:\libs\boost_1_55_0\bin.v2\libs\regex\build\msvc-12.0 
BUILDTARGETPATH=architecture-ia64\

**Comment by chcg** [comment]
@viveksejpal As long as this file is available NOBOOST will not be used. So you have to rename or delete it.

Furthermore it is possible to use C++11 regex, but that is not implemented yet. See
https://www.scintilla.org/ScintillaHistory.html Release 3.5.2
-  Include support for using C++11 <regex> for regular expression searches. Enabling this requires rebuilding Scintilla with a non-default option. This is a provisional feature and may change API before being made permanent.

N++ used modified scintilla 3.5.6 right now.

Additionally see https://github.com/notepad-plus-plus/notepad-plus-plus/pull/139, but don't remember how the build for CXX11_REGEX worked or not.

**Comment by chcg** [comment]
@viveksejpal Guess this is the issue with the signed scintilla.dll you need, if n++ is build as release version. Either you use n++ from a debug build or you have to modify the sourcecode at:

https://github.com/notepad-plus-plus/notepad-plus-plus/blob/fdf954f714325b41a86b745f3e3525277ba17ca4/PowerEditor/src/ScitillaComponent/ScintillaEditView.cpp#L205-L221

**Comment by viveksejpal** [comment]
> isOK

I tried the above approach. I prevented the if conditions by changing code.
I'm building my exe with Unicode debug configuration for x64.
But i get the below error:
![image](https://user-images.githubusercontent.com/10363530/51675881-00ab7600-1ffb-11e9-9d01-bf5f0b69d994.png)

**Comment by sasumner** [comment]
Closing due to age and it not really being an "issue".
