### ISSUE TITLE
Move current line up/down in a macro shifts up/down 2 lines

### ISSUE THREAD

**Issue by Dream-Painter** [notepad-plus-plus/notepad-plus-plus#5217]
### Description of the Issue

When running a macro, which you just made by recording, and it contains a MoveUpCurrentLine or a MoveDownCurrentLine, the result of this macro will be as if these 2 commands have been run twice, while the rest of the macro works as expected. While using the commands manually, shifts the line(s) only by 1, as expected.

### Steps to Reproduce the Issue

1. have a tab open with multiple lines in it
2. have the cursor in any line (or select some line, effect does not depend on this)
3. record a macro which contains MoveUpCurrentLine or MoveDownCurrentLine
4. run the macro
5. see that the current/selected line(s) has been moved up/down 2 lines

### Expected Behavior

I expected the current/selected lines to only move 1 line, like it does when I run the command manually(either by selecting from the edit menu, or by pressing [Ctrl]+[Shift]+[Up/Down])

### Actual Behavior

every MoveDownCurrentLine which is contained in a recorded macro results in the selection having shifted 2 lines down
every MoveUpCurrentLine which is contained in a recorded macro results in the selection having shifted 2 lines up

### Debug Information

Notepad++ v7.5.9   (32-bit)
Build time : Oct 14 2018 - 15:02:52
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : ON
Local Conf mode : OFF
OS : Windows 7 (64-bit)
Plugins : NppConverter.dll NppExport.dll CodeAlignmentNpp.dll ComparePlugin.dll HexEditor.dll NotepadStarterPlugin.dll NppTextFX.dll NppToolBucket.dll OpenSelection.dll PluginManager.dll Python Indent.dll regrexplace.dll ReloadButton.dll XMLTools.dll

**Comment by sasumner** [comment]
First, I found that you are correct!

Second, I noticed that this macro is recorded like this:

    <Action type="0" message="2621" wParam="0" lParam="0" sParam="" />
    <Action type="2" message="0" wParam="42015" lParam="0" sParam="" />

If you manually edit the macro in shortcuts.xml, and remove the `type="0"` line, then it appears to work correctly.  So...I guess you can work around it this way until it is fixed.  :)

**Comment by Dream-Painter** [comment]
I did not even know you can find edit the macro's like that !!!!

to me they were only ever blackbox macros.

Ohhhh, i'm gonna be having fun with this. thanks.

Does this mean it'll actually get fixed, or are was this just to put on more pressure?

**Comment by sasumner** [comment]
>Does this mean it'll actually get fixed...?

It does NOT mean anything of that sort.  All you can do is log an issue here like you did and wait to see what happens.  Or if you have the skills, you can "dig in" and fix it yourself, and then present the code changes for inclusion into N++ master sources (doing that also results in a waiting game to see if/when those changes are approved).

**Comment by Dream-Painter** [comment]
Ok, thanks for the clarification.

**Comment by alankilborn** [comment]
Tested in N++ 8.4.4 (current version as of this writing) and problem still exists.
