### ISSUE TITLE
Performance problems with medium large json files and syntax highlight

### ISSUE THREAD

**Issue by Spamme1** [notepad-plus-plus/notepad-plus-plus#5223]
### Description of the Issue
Editing a medium large json file (50 Kb, 300000 lines) cause notepad++ to not respond any more with a CPU usage of 20% and also waiting 30 minutes doesn't solve the problem.

If the syntax highlight is disable (user-defined) there is no issue.

### Steps to Reproduce the Issue
1. Open a medium large json file (50 Kb, 300000 lines)
2. Scroll in the middle of the file and hit the enter key a couple of times to create some space to add content
3. Notepad++ doesn't respond any more, the CPU usage raises to 20%, waiting also 30 minutes doesn't solve the problem

Note: It seems that the "enter" key is the problem, trying to create some space by hitting it a couple of times triggers the issue. 

### Expected Behavior
Notepad++ doesn't hang up, or at least not longer than 10-15 seconds.

### Actual Behavior
Notepad++ doesn't respond any more, the CPU usage is 20% and waiting also 30 minutes doesn't solve the problem.

### Debug Information
Notepad++ v7.5.9   (32-bit)
Build time : Oct 14 2018 - 15:02:52
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10 (64-bit)
Plugins : ComparePlugin.dll DSpellCheck.dll JSMinNPP.dll mimeTools.dll NppConverter.dll NppExport.dll

**Comment by donho** [comment]
With 7.8.2's new Scintilla component, this issue should be solved.
