### ISSUE TITLE
Plugins should not be stored in C:\ProgramData

### ISSUE THREAD

**Issue by ohmer1** [notepad-plus-plus/notepad-plus-plus#5226]
I'm upgrading Notepad++ from v7.5.9 to v7.6.2. I notice that the plugin directory were in %installdir%\plugins and this has been moved to C:\ProgramData\Notepad++\plugins. 

This directory is by default writable for all users, so our Software Restriction Policy blocks executable (including dll files) from this path for security reason (in fact, we are running a white list scheme, so this path is just not whitelisted). This directory is not the place to store dll, this is a place for data used by the application that need write permission for all users of the computer.

Because of that, when an user open Notepad++, he receive an error message (multiple errors, one for each DLL) because the access to the DLL is blocked by the group policy.

**Comment by chcg** [comment]
See https://notepad-plus-plus.org/community/topic/16645/new-plugins-home-where-notepad-will-load-from and PR #5199 
and
https://notepad-plus-plus.org/community/topic/16790/notepad-7-6-1
https://notepad-plus-plus.org/community/topic/16848/notepad-v7-6-2-yellow-vest-gilet-jaune-edition/19

**Comment by donho** [comment]
@ohmer1 could you provide me the white list so we (notepad++ community) could decide where to install plugins ?

**Comment by donho** [comment]
@ohmer1 could you provide me the white list so we (notepad++ community) could decide where to install plugins ?

**Comment by ohmer1** [comment]
I think it was correctly located before in the install directory. After all, plugins are executable and part of the installation of notepad++.

I have many directories in the whitelist (like C:\Program Files, C:\Program Files (x86), parts of C:\Windows). All theses directories have one thing in common, theirs defaults permissions doesn't allow user to write/modify, only read permission. So they can't execute anything not approved by IT.

**Comment by zhfreal** [comment]
jesus, just make it portable and simple to use.
the plugin manager would not work on the latest npp(portable edition). I tried the npp exec location, %appdata%\notepad++, %programdata%notepad++. none of them worked.
I dont know the exact reasons that you guys made the decision to change the location of plugins. But it apparently make things more complicated and npp not portable any more. for me, I have to stay with 7.5.x .

**Comment by donho** [comment]
@zhfreal Portable package works with another scheme, which is coherent with portable mode.

**Comment by donho** [comment]
https://github.com/notepad-plus-plus/notepad-plus-plus/commit/9fecbae030f33a31b131a75cf41b243c6ea36751
