### ISSUE TITLE
Feature request - alphabetize Plugins in Plugins Admin

### ISSUE THREAD

**Issue by Clyfton** [notepad-plus-plus/notepad-plus-plus#5233]
Please alphabetize the list of plugins in the Plugins Admin page.
It looks like the plugins in the INSTALLED tab are alphabetized.

**Comment by chcg** [comment]
See also https://github.com/notepad-plus-plus/nppPluginList/issues/46

**Comment by donho** [comment]
https://github.com/notepad-plus-plus/notepad-plus-plus/commit/fd32585c14836b46a1b40c79bce706cd96767526
