### ISSUE TITLE
Serious memory leak in release 7.6.2

### ISSUE THREAD

**Issue by fufu65** [notepad-plus-plus/notepad-plus-plus#5234]
### Description of the Issue
Opening many pdf or zip files (and probably other file types) a memory allocation error occurs, and the program continues to allocate memory. It is necessary to terminate the program from the task manager.

### Steps to Reproduce the Issue
Try to open many pdf or zip files.

### Expected Behavior
View the content of the file.

### Actual Behavior
The contents are often displayed, but the program does not respond and an increasing allocation of memory occurs.

### Solution
Uninstall v. 7.6.2 and install v. 7.6.1 (installing 7.6.1 over 7.6.2 does not work).

Tested on:
- Windows 7 Ultimate x64, npp 7.6.2 x64
- Windows XP Professional x86, npp 7.6.2 x86

**Comment by chcg** [comment]
@fufu65 I this happening with just the standard plugins of the installer or are other plugins installed? Do you have a rough number of pdf/zip to open to observe this behaviour?

**Comment by fufu65** [comment]
Uhm... I've now installed 7.6.2 over 7.6.1 and the problem has disappeared.
The problem was presented on a machine I had upgraded from 7.5.9 to 7.6.2, and on another from an older version.
By uninstalling and reinstalling version 7.6.2 the problem does not seem to reoccur.

**Comment by fufu65** [comment]
I can confirm the problem on a third machine (Windows 7 Ultimate x64; old npp version: 7.5.9 x86).
Uninstalling 7.5.9 x86 (keeping configs) and installing 7.6.2 x64 the problem appears; uninstalling and reinstalling 7.6.2 solves.
Into the attached test.zip file there is a rar file (with some Windows XP system files) that triggers the problem (I can't attach directly the rar file... extract it from the zip first). This was one of many other files...
Trying to open this file the program hangs, in 30 seconds are allocated 8 GB of ram... it is necessary to terminate the program from the task manager.

[test.zip](https://github.com/notepad-plus-plus/notepad-plus-plus/files/2759308/test.zip)

**Comment by MetaChuh** [comment]
@fufu65 

i can not reproduce any hang or memory leak while opening your `XP-boot.rar` file as raw data in notepad++ 7.6.6 x86 and x64.

unfortunately we don't have your debug info, but i suppose you will have a spell checker plugin like dspellcheck on the machines that produce this excessive memory consumption.
try disabling or removing any plugins, that analyse the contents of your file.

thank you for your help and best regards.

-----
```
general notes:

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).
please file an issue as easy to understand and reproducible as possible.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
(no extra account is needed, just use your github account to sign in)
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)
