### ISSUE TITLE
japanese translation of “find in file” window tabs broken

### ISSUE THREAD

**Issue by project-flower** [notepad-plus-plus/notepad-plus-plus#5236]
### Description of the Issue
japanese translation of “find in file” window tabs is broken if ctrl+shift+f is pressed immediately after starting notepad++

### Steps to Reproduce the Issue
(tested on notepad++ version 7.6.2, 64-bit)
1. set notepad++ localization to japanese
2. exit notepad++
3. open notepad++ again
4. immediately press ctrl+shift+f
now the tabs of the" find in file" window are shown in english, the rest of the window is shown in japanese. tabs will remain untranslated until notepad++ is closed and opened again.
![image](https://user-images.githubusercontent.com/12604087/51246058-ca537280-19cc-11e9-9dc3-83e047dce33d.png)

### Expected Behavior
“find in file” window tabs should be in japanese

### Actual Behavior
“find in file” window tabs are shown in english, rest of the window is shown in japanese.
this will stay until notepad++ is closed and opened again.

### Debug Information
Notepad++ v7.6.2   (64-bit)
Build time : Jan  1 2019 - 00:02:38
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10 (64-bit)
Plugins : DSpellCheck.dll mimeTools.dll NppConverter.dll

**Comment by chcg** [comment]
![grafik](https://user-images.githubusercontent.com/12630740/51349141-dad71c00-1aa4-11e9-85e8-d2c0c5f42fd4.png)
