### ISSUE TITLE
show file url in unicode

### ISSUE THREAD

**Issue by reza1615** [notepad-plus-plus/notepad-plus-plus#5237]
### Description of the Issue

When the name of subfolders is in Unicode. Nodepad++ shows ???? at the top of the window.

![image](https://user-images.githubusercontent.com/2202483/51257500-c3e5dc00-1975-11e9-925a-d16076b9e947.png)

**Comment by ArkadiuszMichalski** [comment]
@reza1615 Can you give the name of that folder? And by the way, check if the problem still exists in the latest Notepad++?

**Comment by donho** [comment]
It works for me.
It's rather your system lacks the needed font to display it.

**Comment by reza1615** [comment]
Thanks. Now it works.
