### ISSUE TITLE
*New feature* -  Funtion List Highlighting

### ISSUE THREAD

**Issue by demetrio72** [notepad-plus-plus/notepad-plus-plus#5238]
### Description of the Issue
I'm writing about a new feature request, I don't know if this is the right place (and sorry for my poor english)
I'd like to have some kind of function list highlighting. The function where the cursor is in, should be highlighted.
A live highlighting would be great, but heavy. A button to force highlighting could be enough.
This is greatly useful in case of large funtions inside a very big file. Let's suppose you find a word you were looking for, and you want to know, quickly, which function uses it (impact analysis) 

### Steps to Reproduce the Issue

1. take a source file, having a lot of big functions
2. put the cursor somewhere in then middle
3. Which function I am in?

### Expected Behavior

The function raw where I'm in, is highlighted, or I just need to push a button on top of function list to do that.

### Actual Behavior

Nothing happens, I don't know where I am

**Comment by MAPJe71** [comment]
Already implemented in N++ 7.5.6 (see [item 2 of change list](https://notepad-plus-plus.org/download/v7.5.6.html)), allthough it lacks contrast.

**Comment by chcg** [comment]
See #715 with corresponding PR

**Comment by demetrio72** [comment]
tx.
by the way, I found a workaround, changing default background color to get a contrast with foreground function higlight
