### ISSUE TITLE
Emoji's not working in notepad++

### ISSUE THREAD

**Issue by coooool123** [notepad-plus-plus/notepad-plus-plus#5239]
### Description of the Issue

Copy and pasting / importing a .txt from notepad or any other source should just simply display the emojis on npp and not show a bunch of question marks or weird texts in place of them, unless i'm not doing something wrong.
### Steps to Reproduce the Issue

1. i copied them from notepad
2. then i pasted them into notepadd++
3. then i just get a bunch of "????" or "ðŸ’"(if i imported a .txt that contained emoji's) in place of the emoji's

### Expected Behavior

The emoji's to import/paste properly 
### Actual Behavior

No emoji's but instead a bunch of question marks or sometimes I even get these weird lettered things like: ðŸ’ when I attempt to open a .txt via npp

**Comment by chcg** [comment]
@coooool123 
Which N++ version?
What encoding do you used? UTF-8?
Could you add an example of the broken emoji's here.
What font do you use for notepad compared to notepad++?

**Comment by sasumner** [comment]
Test again in Notepad 7.8.9 after enabling the Direct Write preference.

**Comment by Hosseingsd** [comment]
what if I paste plain text but notepad++ convert and shows emoji automatically? like I paste `ðŸ’€` but see 🍀 instead?
