### ISSUE TITLE
Make version string in About dialog selectable/copyable

### ISSUE THREAD

**Issue by gnbl** [notepad-plus-plus/notepad-plus-plus#524]
Because nothing is more annoying than typing off the screen!
(There may be other information dialogs where being able to select and copy displayed data may be convenient.)

**Comment by Rikk** [comment]
Why you need to copy just "6.7.9.2"?

**Comment by dail8859** [comment]
A better idea might be to make a block of text selectable that contains Notepad++ version, OS version, and list of plug-ins (with version).  That way that block of text can be included when possible when submitting an issue. Many other applications do a similar thing.

**Comment by Rikk** [comment]
> list of plug-ins (with version)

and which ones are enabled/disabled. That would be useful.

**Comment by dail8859** [comment]
Agreed. And any other relevant information. Especially if/when there is a 64bit version, that will be nice to know too.

**Comment by gnbl** [comment]
Sure, more information is better, but also more work. 
Making the existing text "label" selectable or using an (ugly) input field should be the easiest to implement.

**Comment by Rikk** [comment]
It would be much harder task for Donho just to implement that than for anyone to just press a few keys.

**Comment by milipili** [comment]
It would be nice to directly have something selectable, with the version and the list of all plugins. It would help for bug reporting.

**Comment by Rikk** [comment]
So, I made a fix for this "Issue".

I think it would be nice to add the Git commit hash to build info, so user know what is the exact source used to build it.
I know [Media Player Classic](https://github.com/mpc-hc/mpc-hc) guys have a nice and complex script for doing that, but it's too hard for me.

**Comment by donho** [comment]
I don't think it's needed to be improved in About dialog.

**Comment by Croydon** [comment]
Hint: Better use the label "wontfix" instead of "invalid".
It's not an invalid request, but was denied :)

**Comment by Rikk** [comment]
:astonished:

**Comment by ariccio** [comment]
> Hint: Better use the label "wontfix" instead of "invalid".

+1

**Comment by Rikk** [comment]
<h6><sup>Now donho pretends he's not reading our comments. Why is it so hard to give a word?</sup></h6>

**Comment by Croydon** [comment]
Be more patient ;)

**Comment by ariccio** [comment]
> Now donho pretends he's not reading our comments. Why is it so hard to give an answer?


> Be more patient ;)

Yah, he's busy... And always assume that there's a good reason.

**Comment by Rikk** [comment]
![connectingtodonho](https://cloud.githubusercontent.com/assets/2916485/9158314/ee4e017a-3eea-11e5-9dc3-13ecec3454be.jpg)
https://www.youtube.com/watch?v=4CQYN0zAVI8

**Comment by donho** [comment]
Sorry for not replying immediately. I have a family with a 7-year-old child who needs his father constantly, and a daily job for filling up the fridge as all ordinary men, I got also some friends and am trying to have a social life.

There's nothing needed change in About box. Instead, I believe #694 responds better the need.

**Comment by Rikk** [comment]
Yes, #691 was meant as a simple workaround until that happens.

**Comment by ariccio** [comment]
Whoa everybody! [Chill pill](http://www.urbandictionary.com/define.php?term=Chill+Pill) time!

**Comment by Rikk** [comment]
Was just quoting Npp deeply embedded wisdom.

**Comment by h-h-h-h** [comment]
> https://github.com/notepad-plus-plus/notepad-plus-plus/pull/543 Good for kids.

That's right ironically! More people should vote down.

**Comment by milipili** [comment]
You're not fun peole :)
