### ISSUE TITLE
After installing update of  notepad++ 7.6.2 ,the old plugins get removed.how can i preserve the old plugins ?

### ISSUE THREAD

**Issue by 01mrunalshinde** [notepad-plus-plus/notepad-plus-plus#5243]
### Steps to Reproduce the Issue

1. 
2. 
3.

**Comment by sasumner** [comment]
This is a question, not an issue; questions are better asked here: https://notepad-plus-plus.org/community

**Comment by chcg** [comment]
@01mrunalshinde See https://notepad-plus-plus.org/news/notepad-7.6.1-released.html about new plugin folder.
