### ISSUE TITLE
"File Is Open" Error

### ISSUE THREAD

**Issue by ChaosOrdeal** [notepad-plus-plus/notepad-plus-plus#5247]
### Description of the Issue
When trying to overwrite a file with the same name as another file in the "Save As" dialogue, Notepad++ fails to save, incorrectly reporting that the file is already open in Notepad++.

### Steps to Reproduce the Issue
1. Open a file in Notepad++
2. Open the "Save as..." dialogue in Notepad++
4. Rather than changing to the intended destination directory in the Save As... dialogue, type the fully qualified filename in the File Name: blank.  Choose a file that is in a different directory from the open file, but has the same filename, so you will be overwriting a file.
5. Click "Save"
6. In the "Confirm Save As" message window, click "Yes" (choosing to overwrite a file)
7. Notepad++ generates the following window: "Error.  The file is already open in Notepad++."

### Expected Behavior
The open file should overwrite the file of the same name.

### Actual Behavior
Error is generated.  The error is nonsensical.  a) the file to be overwritten is NOT already open in Notepad++;  b) Open files are intended to be overwritten, otherwise you could not make and save edits with N++
Somehow the files having the same name seems to be confusing the overwrite/file-integrity logic of N++.

### Debug Information
Notepad++ v7.5.9   (64-bit)
Build time : Oct 14 2018 - 15:19:55
Path : D:\Applications\Notepad++\notepad++.exe
Admin mode : ON
Local Conf mode : OFF
OS : Windows 10 (64-bit)
Plugins : DSpellCheck.dll mimeTools.dll NppConverter.dll 

I was working with a .json file.  Probably not important, but . . .

**Comment by ChaosOrdeal** [comment]
Couldn't reproduce, and I'll go ahead and guess that you won't be able to either, but it was persistent on first appearance.  Obviously, I could work around by saving under another filename, then deleted and renaming, but it was an odd one.  If you can't repro, feel free to close this as yet another Windows one-time oddity.

**Comment by SinghRajenM** [comment]
@MetaChuh I feel this ticket can be closed.

**Comment by mrance8** [comment]
I get this issue all of the time.  It's really annoying!

**Comment by sasumner** [comment]
If I try to reproduce with the SaveAs target name existing but NOT open as another tab in Notepad++, all works as expected (or at least my interpretation) with N++ 7.7.1.

If I try to reproduce with the SaveAs target name existing AND OPEN as another tab in Notepad++, I get the "The file is already opened in the Notepad++" popup with N++ 7.7.1 and the contents of the SaveAs target don't change but the open tab is made active after closing the popup.  Is this the desired behavior? Or should the SaveAs be allowed to proceed for this case, saving to the open tab file?

**Comment by xylographe** [comment]
First off, I think, the current behaviour (refuse with "file is already opened") is quite reasonable.

However, a slightly more user-friendly approach, might be,

1. Notify user about existing file (normal behaviour).
2. If overwrite confirmed, do not refuse, perform the save.
3. Close the active tab.
4. Activate the "already opened" tab.
5. If "file status auto-detection, update silently" in preferences is activated, then reload the saved file in this tab without asking. In any other case (including "file status auto-detection, disabled") notify user in the usual way, and ask confirmation for reload.
