### ISSUE TITLE
Bug in "Find All in Current File"

### ISSUE THREAD

**Issue by goksoy66** [notepad-plus-plus/notepad-plus-plus#5249]
### Description of the Issue

I've found a bug in "Find All in Current File" property. I was trying to find a gene pattern (like CAACTTCCA) in a DNA sequence (like following). My program is expected to return first indices of given pattern in sequence.

GACAACTTCCAACTTCCAACTTCCCGTCCCAACTTCACAACTTCGGCCCAACTTCCATGCAACTTCACCATCAACTTCGCTCGAAGCTGCCTTCCACTCCAACTTCACAACTTCCTCAACTTCCTCACCAACTTCAGCAACTTCTCTAGGGCCAACTTCCAACTTCTCAACTTCTCAACTTCCAACTTCCGACAACTTCTCCTGGCAACTTCCAACTTCCAACTTCAATACAACTTCGCAGACAACTTCCGCAACTTCGAACAACTTCCAACTTCCCCAACTTCCAACTTCCAACTTCGCCAACTTCCAACTTCCAACTTCCCAACTTCAGATAGCAACTTCGATCTTACACAACTTCACGCAACTTCTCCAACTTCCAACTTCTGTGCAACTTCTCTGAACAACTTCCTCAACTTCCAACTTCGCAACTTCCCCAACTTCCTCAACTTCATGCAACTTCGAGGCAACTTCCCAACTTCGCAACTTCCTATTCCCAACTTCTGTGGCAACTTCTCAACTTCTGGACAACTTCTATGCCCAACTTCACAACTTCCCCAACTTCTTTACAACTTCGACAACTTCATCAACTTCTAGTCAACTTCTGGTCCAACTTCCAACTTCCCCAACTTCCAAAGTGCCGCAACTTCGTAACAACTTCACGCGCTCAACTTCAACCAACTTCTTTTCCCGCAACTTCGCAACTTCACAACTTCTAATCAACTTCCAACTTCGGATCAACTTCCAACTTCGCCAACTTCCAACTTCCAACTTCTCCAGGGACAACTTCAAGTACAACTTCCAACTTCGCAACTTCACAACTTCCCAACTTCGCAACTTCTACACGCAACTTCCAACTTCTGGTCCCAACTTCATCAACTTCAGTCAACTTC

### Steps to Reproduce the Issue

1. 
2. 
3. 

### Expected Behavior

3 10 49 153 176 206 213 262 278 285 301 308 371 411 608 624 718 736 752 759 793 845

### Actual Behavior

3 49 153 176 206 262 ...

10 and 213 is missing. It means that Notepad++ starts the new search from the end of already found pattern. 

new index = (first index of pattern) + (length of pattern)

**Comment by chcg** [comment]
You will also find this behaviour with:
![grafik](https://user-images.githubusercontent.com/12630740/51492242-715f5200-1db1-11e9-8f38-23df79404117.png)
, but is this a real world use case of a text editor with "normal" space separated languages?

**Comment by Myrcellion** [comment]
This is the normal behaviour, the result is the same in **Atom** and **LibreOffice Writer**. Either it is the way it should be or those two and many others are wrong as well.
However you can include the repetitions of your pattern in the result if you search for a regular expression rather than a string. For your example the regular expression would be **C(AACTTCC)+A**. For the **c** thing it could be **(ccc)+**. The amount of hits won't be what you expect but the repeated patterns will be fully highlighted.
![regex](https://user-images.githubusercontent.com/13684783/51548087-e2614100-1e67-11e9-8c32-6e41211bc12f.png)

**Comment by goksoy66** [comment]
Thank you very much. It's very clarifying explanation.

**Comment by goksoy66** [comment]
And thank you for all.

**Comment by arm-in** [comment]
The behavior that you are describing is a feature. "Naive" Search has a quadratic running time of order O{M*N}
The algorithms of Knuth-Morris-Pratt, Boyer-Moore, etc. show a linear running time of order O{N}, which is faster. But they will skip over the text. See
https://en.wikipedia.org/wiki/String-searching_algorithm
https://en.wikipedia.org/wiki/Knuth%E2%80%93Morris%E2%80%93Pratt_algorithm
https://en.wikipedia.org/wiki/Boyer%E2%80%93Moore_string-search_algorithm
