### ISSUE TITLE
Logo Usage Guidelines

### ISSUE THREAD

**Issue by imposhster** [notepad-plus-plus/notepad-plus-plus#5251]
### Description of the Issue
Looking to get direction on the usage of the Notepad++ logo. I'd like to use the logo in an application to provide a better user experience by placing it next to the Name and Version of the current Notepad++ release. I will not be redistributing the Notepad++ software, but merely linking to said software for users to download

### Steps to Reproduce the Issue
n/a

### Expected Behavior
n/a

### Actual Behavior
n/a

### Debug Information
n/a

**Comment by donho** [comment]
OK, no problem to me.
