### ISSUE TITLE
Can't undo replaced text

### ISSUE THREAD

**Issue by ElSchiffer** [notepad-plus-plus/notepad-plus-plus#5253]
Notepad++ v7.5.9
Build time : Oct 14 2018 - 15:02:52
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
OS : Windows 10

### Description of the Issue
When user search and replace some text to another and accidentally click "Replace all in all opened document" user can't undo all document that replaced

### Steps to Reproduce the Issue
1.  Open find and replace
2. Click "Replace all in all opened document"
3.

**Comment by sasumner** [comment]
It's possible to undo, you just have to move to each document and execute Undo.  Not great, but not catastrophic either.

**Comment by Myrcellion** [comment]
But now "Replace All in All Opened Documents" sounds like a dangerous feature, maybe it should ask for confirmation before executing the replacement.

**Comment by sasumner** [comment]
>did dev noticed this issue?

Did you happen to notice that there are 2476 open issues?  It's really hard to "notice" a specific one within the context of that many.

**Comment by donho** [comment]
As @sasumner said:
> It's possible to undo, you just have to move to each document and execute Undo. Not great, but not catastrophic either.

**Comment by sasumner** [comment]
@donho I guess the each-doc-undo is okay for sane people like you and me :) that run with a small number of tabs. There are others that have hundreds (I'd guess).  Maybe requesting confirmation is not a bad idea (although obviously not to apply if RAOD occurs in a macro). Reconsider? But it's nothing to me! :)

**Comment by keanerickson** [comment]
Much love for notepad++ but this feature is really a terrible liability and I wish I could remove this button entirely.

**Comment by MetaChuh** [comment]
@keanerickson 

if you don't know what you are doing, when pressing a certain notepad++ button, please don't press it.

as all files can be undone, as long as notepad++ is not closed, the only liability sits between keyboard and chair in this case.

note: if you only notice human errors after a while and not immediately, please enable verbose backup, so that you can always revert to any older save state of any specific file.

many thanks and best regards.

**Comment by keanerickson** [comment]
How about putting a button for an incredibly niche feature more than 10 pixels away from a button that is viable for every day use?

**Comment by sasumner** [comment]
Released in N++ version 7.8.8
