### ISSUE TITLE
Open with ... does not work

### ISSUE THREAD

**Issue by eduardo-mior** [notepad-plus-plus/notepad-plus-plus#5254]
### Description of the Issue
I installed the notepad ++ 64-bit x64 v7.6.2 on my Windows 7 ultimate 64-bit. It works normally, but will not appear in the "open with". I can not associate file extensions to open automatically. I installed the 32 bit x86 version and managed to do this normally.

### Steps to Reproduce the Issue
1. Right click on the file.
2. Select the "open with" option.
3. Select the "Search ..." option
4. Select notepad ++ .exe

### Expected Behavior
I expected the notepad ++ to be displayed in the program list after I select it. However, selecting it and pressing Ok does not appear in the list of programs.

### Actual Behavior
Nothing happened, it just does not appear on the list.

### Debug Information

1. http://prntscr.com/maq4c4
2. http://prntscr.com/maq4p6
3. http://prntscr.com/maq4zk
4. http://prntscr.com/maq59q
System Info: http://prntscr.com/maq5hb

**Comment by Faq** [comment]
Dublicate of #2454 and therefore should be closed.

**Comment by andrecool-68** [comment]
I have a portable version, with the help of this VBS-script I add the item to the context menu. This works on all platforms and on all versions of Notepad + +.

Dim objShell, Racey, intCount
Set objShell = CreateObject("WScript.Shell")
'Add Item to context menu
objShell.Run "regsvr32 /s /i NppShell_06.dll"
'Remove an item from the context menu
' objShell.Run "regsvr32 /u NppShell_06.dll /s

The NppShell_06. dll file is taken from the Notepad + + installer, taking into account the system's bit capacity.

![default](https://user-images.githubusercontent.com/3471892/52163557-5ca58700-26ec-11e9-9c17-bdabfd50ca72.png)

**Comment by RUSHyoutuber** [comment]
> I have a portable version, with the help of this VBS-script I add the item to the context menu. This works on all platforms and on all versions of Notepad + +.
> 
> Dim objShell, Racey, intCount
> Set objShell = CreateObject("WScript.Shell")
> 'Add Item to context menu
> objShell.Run "regsvr32 /s /i NppShell_06.dll"
> 'Remove an item from the context menu
> ' objShell.Run "regsvr32 /u NppShell_06.dll /s
> 
> The NppShell_06. dll file is taken from the Notepad + + installer, taking into account the system's bit capacity.
> 
> ![default](https://user-images.githubusercontent.com/3471892/52163557-5ca58700-26ec-11e9-9c17-bdabfd50ca72.png)

Mine also has that option.
But I wanted it to open automatically when I click 2 times on top.

**Comment by andrecool-68** [comment]
@RUSHyoutuber You can make file associations
![_2019_02_03_16_59_13_253](https://user-images.githubusercontent.com/3471892/52178289-3576b480-27d5-11e9-92f7-d848306dbd5b.gif)

**Comment by eduardo-mior** [comment]
> @RUSHyoutuber You can make file associations
> ![_2019_02_03_16_59_13_253](https://user-images.githubusercontent.com/3471892/52178289-3576b480-27d5-11e9-92f7-d848306dbd5b.gif)

It worked! thank you very much!
