### ISSUE TITLE
Minor doc error

### ISSUE THREAD

**Issue by morbac** [notepad-plus-plus/notepad-plus-plus#5255]
Hi, I found a little typo in "Messages and notifications" documentation page available here: http://docs.notepad-plus-plus.org/index.php/Messages_And_Notifications

The message `NPPM_GETGETCURRENTVIEW` does not exist. Correct name is `NPPM_GETCURRENTVIEW`.

**Comment by nlsdg** [comment]
Please close this issue, as the pull request has been merged.
