### ISSUE TITLE
Is SCFIND_CXX11REGEX beneficial?

### ISSUE THREAD

**Issue by KOLANICH** [notepad-plus-plus/notepad-plus-plus#5257]
>When using SCFIND_CXX11REGEX more features are available, generally similar to regular expression support in JavaScript. See the documentation of your C++ runtime for details on what is supported.

In theory. In practice I heard some rumours that the impl in G++ stdlib may be incomplete. Should it be used?

**Comment by MAPJe71** [comment]
SCFIND_CXX11REGEX might be benifical to improve upon the default RegEx engine of Scintilla but last time I looked it does not improve on Boost::Regex.

If I remember correctly there has been a discussion about Cxx11Regex (more specific replacing Boost::Regex library with PCRE2 library) on the Community forum.

**Comment by chcg** [comment]
@KOLANICH @MAPJe71 The main blocking point against just using the std c++11 regex (https://en.cppreference.com/w/cpp/regex/syntax_option_type) was the missing feature of perl  regex style of boost (https://www.boost.org/doc/libs/1_55_0/libs/regex/doc/html/boost_regex/ref/syntax_option_type/syntax_option_type_synopsis.html) used by N++.

See https://github.com/notepad-plus-plus/notepad-plus-plus/pull/139
and
https://notepad-plus-plus.org/features/

> PCRE (Perl Compatible Regular Expression) Search/Replace

**Comment by KOLANICH** [comment]
Thank you for the info.
