### ISSUE TITLE
N++ crashes when sorting lines with numbers longer than 20 digits

### ISSUE THREAD

**Issue by SothoTalKer** [notepad-plus-plus/notepad-plus-plus#5261]
### Description of the Issue
Notepad crashes with "stoll argument out of range" when sorting integers if number is too large (likely >64 bit)

### Steps to Reproduce the Issue
1. create a file with 2 numbers on two lines, one with more than 20 digits
2. select both and use Edit -> Line operations -> Sort Lines as Integers Ascending
3. Notepad++ crashes

### Expected Behavior
At least Notepad++ should not crash, even if sorting is not possible.

### Debug Information
Notepad++ v7.6.2   (64-bit)
Build time : Jan  1 2019 - 00:02:38
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : ON
Local Conf mode : OFF
OS : Windows 10 (64-bit)
Plugins : DSpellCheck.dll mimeTools.dll NppConverter.dll

**Comment by Myrcellion** [comment]
The sequence of messages appearing before Notepad++ closes:
![crash](https://user-images.githubusercontent.com/13684783/51645242-a6b39d80-1f73-11e9-90c3-9b7123968b73.png)
The responsible part of the code seems to be the **NaturalSorter** created in **NppCommands.cpp** around line 606 and the **NaturalSorter** in **Sorters.h** line 119 and following.

https://github.com/notepad-plus-plus/notepad-plus-plus/blob/master/PowerEditor/src/MISC/Common/Sorters.h#L119
https://github.com/notepad-plus-plus/notepad-plus-plus/blob/master/PowerEditor/src/NppCommands.cpp#L606

The problem only occurs if lines are sorted as integers.

**Comment by SothoTalKer** [comment]
std::stoll seems the issue here, when the used value exceeds the limit for unsigned long long value:
ULLONG_MAX | Maximum value for a variable of type unsigned long long | 18446744073709551615 (0xffffffffffffffff)

Btw: It would be nice to actually make it a signed comparison, so that negative integers get sorted correctly aswell.

**Comment by mdnaufalh** [comment]
We could solve this by treating integers >= ULLONG_MAX as strings and not try to convert them to long long. A simple sort on strings would then be enough to sort as such. There would be a performance hit, yes but not noticeable.

P.S: This is my first Github Comment. Could someone help me along the issue to tackle this problem ?

**Comment by SothoTalKer** [comment]
An possibly easy fix for the crash is amending the checks of the bools aChunkIsNum and bChunkIsNum to also check if the number does not exceed the maximum allowed value of ULLONG_MAX.

https://github.com/notepad-plus-plus/notepad-plus-plus/blob/master/PowerEditor/src/MISC/Common/Sorters.h
There are 4 checks in total, on lines 146,147 and 196,197
