### ISSUE TITLE
tab sizes are wrong (not consistent)

### ISSUE THREAD

**Issue by craftwar** [notepad-plus-plus/notepad-plus-plus#5263]
### Description of the Issue
Notepad++ v7.6.1 64bit
some tab sizes are 1 space, not 4 spaces in setting
line 6, tab display as 4 space (correctly).
line 7~9, tab display as 1 space only.

### Steps to Reproduce the Issue
open this file on Windows 10 1803, system code page 932
https://github.com/craftwar/suspend/blob/master/suspend/README.txt

### Actual Behavior

![image](https://user-images.githubusercontent.com/16416710/51658177-32641300-1fe2-11e9-94ea-ac89a4ab1495.png)

**Comment by polluks** [comment]
I cannot see an issue with Shift-JIS, which font are you using?

**Comment by craftwar** [comment]
![image](https://user-images.githubusercontent.com/16416710/51978907-92692680-24c6-11e9-941a-048410f38602.png)
I get the same problem in Curier New. What else font should I try?

**Comment by ArkadiuszMichalski** [comment]
@craftwar Links to reproduce is not valid, have you other example?

**Comment by polluks** [comment]
How about this? https://github.com/craftwar/suspend/blob/bf23afd0510f8731a526e26fdc23d310eb898e56/qt/README.txt

**Comment by ArkadiuszMichalski** [comment]
For me also no problem in Notepad++ 7.9 RC.

**Comment by donho** [comment]
Cannot be reproduced for me either.

**Comment by craftwar** [comment]
can't be reproduced on 7.8.9, may be fixed
