### ISSUE TITLE
flexible heredoc/nowdoc syntax in php 7.3 is not highlighted properly

### ISSUE THREAD

**Issue by walkinlake** [notepad-plus-plus/notepad-plus-plus#5264]
the new flexible heredoc/nowdoc syntax in php 7.3 (see https://wiki.php.net/rfc/flexible_heredoc_nowdoc_syntaxes or https://laravel-news.com/flexible-heredoc-and-nowdoc-coming-to-php-7-3) is not highlighted properly

_Originally posted by @walkinlake in https://github.com/notepad-plus-plus/notepad-plus-plus/issues/210#issuecomment-457236268_

**Comment by ArkadiuszMichalski** [comment]
https://sourceforge.net/p/scintilla/feature-requests/1378/

**Comment by ivan-u7n** [comment]
The attached [LexHTML.patch.txt](https://github.com/notepad-plus-plus/notepad-plus-plus/files/6834700/LexHTML.patch.txt) (against master) changes lexer to recognize the relaxed heredoc/nowdoc syntax in PHP 7.3+. The patch also includes the support for optional double quoting of delimiters and adds an underscore as the valid character for numbers. It doesn't have the same robust checks as PHP does, but at least it makes such a syntax usable in Notepad++.

The patch was tested via compiling Notepad++ with mingw64 gcc 8.1 and opening 
[test.relaxed-heredoc.php.txt](https://github.com/notepad-plus-plus/notepad-plus-plus/files/6834708/test.relaxed-heredoc.php.txt) in the compiled editor.

I will try to post it to Scintilla as well, but I can't guarantee it if I have to register at SourceForge for this.

**Comment by ArkadiuszMichalski** [comment]
@ivan-u7n Add your fix in https://github.com/ScintillaOrg/lexilla, this repo holds the lexers for Scintilla (you don't need SourceForge account).

**Comment by ivan-u7n** [comment]
The relevant changes are in Lexilla now, although not in any released version yet. All what's left to do is to update Nodepad++'s version of Scintilla and Lexilla… But it can turn out to be not so easy thanks to recent changes in Scintilla.

**Comment by ArkadiuszMichalski** [comment]
Fixed by https://github.com/notepad-plus-plus/notepad-plus-plus/commit/a61b03ea8887e21c6e1b7374068962f635b79b80.
