### ISSUE TITLE
Global override style does not override line number margin font

### ISSUE THREAD

**Issue by Nisto** [notepad-plus-plus/notepad-plus-plus#527]
I have had this issue for as long as I can remember. When I open the style configurator and switch themes (to one of the pre-installed themes that is) and then manually change the font name/size to my own desired settings on the "global override" page, the font for the line number margin is not updated. Additionally, .nfo files always seem to have a separate font for the line number margin for some reason? Maybe that's intended though..

Notepad++ version: 6.7.9.2
OS: Windows XP SP3

**Comment by donho** [comment]
I believe this issue has been fixed since long time ago.
Update your Notepad++ to the latest version (v7.6.6).
If the issue persists, please create a new issue for it.
Thank you.
