### ISSUE TITLE
error messege !

### ISSUE THREAD

**Issue by gurikbal** [notepad-plus-plus/notepad-plus-plus#5270]
![capture-20190125-202057](https://user-images.githubusercontent.com/36083297/51753297-6a9d4b80-20df-11e9-9e96-b5ef0141aae6.png)
![capture-20190125-202241](https://user-images.githubusercontent.com/36083297/51753320-76890d80-20df-11e9-8f54-d8992e50e820.png)

### Description of the Issue
after auto update 3p plugin give error messeges

### Debug Information
Notepad++ v7.6.1   (32-bit)
Build time : Dec 12 2018 - 01:24:22
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 7 (32-bit)
Plugins : 3P.dll Console_output.dll DSpellCheck.dll mimeTools.dll NppConsole.dll NppConverter.dll NppFTP.dll NppToolBucket.dll PythonScript.dll Remove_dup_lines.dll

**Comment by sasumner** [comment]
Closing was an excellent decision.
