### ISSUE TITLE
A request that makes Notepad ++ even more better than ever.

### ISSUE THREAD

**Issue by MrKiller01** [notepad-plus-plus/notepad-plus-plus#5271]
### Steps to Reproduce the Issue

1. 
2. 
3. 

### Debug Information

Hi, I have a request as stated above, 
The one thing I can't seem to find is editing files next to each other. Lets say I need to compare two files, I load both files in Notepad ++ and the other one too, then I have to switch all the time between file 1 and 2 to tell the difference. It would be nice if they could be both on one screen.
On top of that, a compare option would be too good to be true, so, I'm not suggesting that, yet.
Thanks

**Comment by sasumner** [comment]
Open File1. Open File2.  Right-click tab of File2 and choose "Move to Other View".  You are now side-by-side (or one-over-the-other).

>compare option

There is a Compare plugin for this purpose, but it is not part of official Notepad++, so questions about it are best addressed elsewhere.

**Comment by MrKiller01** [comment]
Wow, thanks, and then to know that I thought I'd search the whole program, must have missed that option huge....
