### ISSUE TITLE
Global Styles override is dysfunctional, its results are widely unpredictable.

### ISSUE THREAD

**Issue by mzso** [notepad-plus-plus/notepad-plus-plus#5275]
### Description of the Issue
First there is #4117, where syntax based highlights are butchered. But that's not all, when you change font size the line spacing is also butchered. It's nice and roomy by default in the default theme, but when I change the font size it becomes very cramped. 

### Expected Behavior
Only override the relevant setting that is changed. Font size, background color, etc

### Actual Behavior
Unpredictable other things are overridden. Background color change destroys syntax based highlights, Font size changed ruins line spacing.
And who knows what else. These came up by only changing properties that I was interested in changing.

**Comment by MetaChuh** [comment]
@mzso 

please do not use global overrides if they do not suit your needs.

thank you for your help and best regards.

-----
```
general notes:

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
(no extra account is needed, just use your github account to sign in)
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)

**Comment by mzso** [comment]
One might understand lack of time to work on this. But pretending it's not a bug is ridiculous.
