### ISSUE TITLE
Style color changes aren't saved

### ISSUE THREAD

**Issue by pasztorpisti** [notepad-plus-plus/notepad-plus-plus#5278]
### Description of the Issue

I switched to a darker theme (Solarized) and customized the color of the whitespace characters. After restarting the editor the theme switch was saved (it was still Solarized) but the customization of whitespace character color was gone.

### Steps to Reproduce the Issue

1. Switch to a non-default style.
2. Change an individual color of that style (like whitespace character color).
3. Restart notepad++.

### Actual Behavior

Based on my experience and reading some other error reports here is my guess of what the problem is and how I worked it around.

I guess the source of the problem is that my windows users (intentionally) don't have write access to the Notepad++ installation and notepad++ tries to save the style changes to the install location. Some people worked around their issues (like not being able to set font) by giving write access to their users to the notepad installation (`"c:\Program Files\notepad++`) which is a bad hack.

My workaround: I've noticed that I can change and save individual colors in my style by selecting the "Default (stylers.xml)" style because that one is located in the user folder (`c:\Users\[username]\AppData\Roaming\Notepad++\stylers.xml`) to which the program has write access. For this reason I have chosen the "Default (stylers.xml)" style and overwritten my `c:\Users\[username]\AppData\Roaming\Notepad++\stylers.xml` file with `c:\Program Files\notepad++\themes\Solarized.xml` and then modified the whitespace color and I could save my changes.

Although my workaround is solid/clean it isn't intuitive or user friendly.

### Expected Behavior

I'd like notepad++ to either save my styles in a WYSIWYG style or report an error if saving isn't possible for some reason (but this really shouldn't happen under normal circumstances).

The problem I've described can be solved in many ways but here is what I think would be a reasonably good solution:

- Notepad shouldn't try to write files in it's own install folder. It should write modified settings the home folder of the current user.
- In my opinion the Default theme should be a read-only xml file just like the other themes (`c:\Program Files\notepad++\themes\Default.xml` or a virtual - but still readonly - theme based on the current system color settings of windows) and the user's style settings should always be saved to his/her own `c:\Users\[username]\AppData\Roaming\Notepad++\stylers.xml` file. Selecting a theme (Default or something else) would simply populate/reset the users's own settings that could optionally be customzied and then saved to his/her own config files somewhere under the home folder.

### Debug Information

```text
Notepad++ v7.6.2   (64-bit)
Build time : Jan  1 2019 - 00:02:38
Path : C:\Program Files\notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10 (64-bit)
Plugins : none
```

**Comment by MetaChuh** [comment]
@pasztorpisti 

this is fixed in newer versions of notepad++.

user themes are now used from `%AppData%\Notepad++\themes\` and your theme customisations will be saved there.
a fresh install will not create `%ProgramFiles%\Notepad++\themes\`.

please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins if you update from your reported version 7.6.2, as the plugins folder structure has changed once more since 7.6.3 and above.

note: make sure that themes are selected when (re)installing.

thank you for your help and best regards.
