### ISSUE TITLE
Removing an non-plugin-admin-managed plugin causes whole plugins folder to disappear

### ISSUE THREAD

**Issue by TaoK** [notepad-plus-plus/notepad-plus-plus#5279]
### Description of the Issue

When using plugin admin to remove a plugin that is not supported by plugin admin (yet), it seems that the plugin admin system accidentally removes the whole "plugins" folder.

### Steps to Reproduce the Issue
1. Install v7.6.3 (32-bit) with default options, so you have the Plugins menu with plugin admin and the default plugins
2. Add the Poor Man's T-Sql Formatter plugin (eg download from  http://architectshack.com/GetFile.aspx?Page=PoorMansTSqlFormatter&File=SqlFormatterNppPlugin.1.6.10.b.zip, put it the right place)
3. Restart NPP, confirm Poor Man's T-SQL Formatter is available
4. Open plugin admin, find Poor Poor Man's T-SQL Formatter in the "installed" tab
5. "Remove" it, accepting the restart warning, and the admin-mode popup thing

### Expected Behavior

When Notepad++ restarts, the one plugin you requested to remove should be gone.

### Actual Behavior

When Notepad++ restarts, the entire Plugins menu is gone, including plugin admin.

**Comment by Nu11u5** [comment]
Reproduced this issue exactly with the older Scout-Soft CSV SQL plugin (http://www.scout-soft.com/sql/).

NPP v7.6.4 (32-bit).

**Comment by chcg** [comment]
Maybe this is not an issue directly within N++ PA, but from https://github.com/notepad-plus-plus/wingup. This needs to be further investigated.

**Comment by MetaChuh** [comment]
duplicate reference #5576

**Comment by SinghRajenM** [comment]
>Maybe this is not an issue directly within N++ PA, but from https://github.com/notepad-plus-plus/wingup. This needs to be further investigated.

@chcg Nope, this is not an issue with N++ PA. Actual issue lies within npp. Npp must handle this special case......

**Root Cause:**
For manually installed plugins, there is no value for `folder-name` in npp code. So `i->_folderName` is empty which could not make path as `C:\Program Files\Notepad++\plugins\AutoSave`. So the remove directory remains `C:\Program Files\Notepad++\plugins\` which does magic to remove complete plugin folder rather than `plugin\AutoSave`
```
else // op == pa_remove
{
	// add folder to operate
	updaterParams += TEXT(" \"");
	updaterParams += i->_folderName;
	updaterParams += TEXT("\"");
}
```


```
{
			"folder-name": "mimeTools",
			"display-name": "Mime tools",
			"version": "2.2",
			"id": "c89b2bb4ca3e8ae5e3f6d3169fcbe830165b330b1c4639ecb4149ed91fabba06",
			"repository": "https://github.com/npp-plugins/mimetools/releases/download/v2.2/mimetools.v2.2.zip",
			"description": "MIME plugin for Notepad++ implements several main functionalities defined in MIME (Multipurpose Internet Mail Extensions).",
			"author": "Don HO",
			"homepage": "https://github.com/npp-plugins/mimetools"
		},

```
