### ISSUE TITLE
How do all "Find in files" features work ?

### ISSUE THREAD

**Issue by sickle2** [notepad-plus-plus/notepad-plus-plus#528]
How do all "Find in files" features work ? When I do such a search, no result window appears.

**Comment by Rikk** [comment]
From Donho's catacombs: http://docs.notepad-plus-plus.org/index.php/Searching_And_Replacing#Find_in_files_specific_features

**Comment by FriendFX** [comment]
> When I do such a search, no result window appears.

I just had the same problem. Then I found that the upper edge of Find Results panel was just positioned right at the bottom of the Notepad++ window, so I only needed to drag this edge up for the Find Results panel to become visible.

**Comment by sickle2** [comment]
It does nothing for me ! Is it supposed to open a search result window ?

**Comment by sickle2** [comment]
That’s it ! Thanks,
