### ISSUE TITLE
Linux / Zorin OS / typing is slow, delayed, missing letters

### ISSUE THREAD

**Issue by jasonbrown1965** [notepad-plus-plus/notepad-plus-plus#5281]
### Keyboard lag / slow response to key strokes / missing strokes / linux

Using Zorin OS. My very first file, no added plugins, the keyboard was very slow to respond, and kept missing letters. An example: "Programme" typed as "Pgam". Typing slower did not improve things much, and is not really an option for busy offices.

Tried uninstalling D-spell as per online advice but no improvement. A pity, loving full screen, and lots of options.

Notepad++ was installed via original Zorin Software app. 

### Steps to Reproduce the Issue
1. Install Notepad++ 
2. Launch Notepad++
3. Start typing

### Expected Behavior
To be able to type at a normal speed.

### Actual Behavior
App very slow to respond to keystrokes - also missing letters, about 50/50

### Debug Information

Notepad++ v7.6.2   (32-bit)
Build time : Jan  1 2019 - 00:00:08
Path : Z:\home\jason\snap\notepad-plus-plus\174\notepad-plus-plus\notepad-plus-plus.exe
Admin mode : ON
Local Conf mode : OFF
OS : Windows 7 (32-bit)
Plugins : NotepadStarterPlugin.dll 

_Hmmm, identifying as Windows 7 32 on a Linux (64-bit) ?_

Lemme know if there is any system info you might need.

**Comment by sasumner** [comment]
I dunno, I always thought when you are running under an OS that isn't exactly Windows, you are sorta on your own with these types of things.  Certainly a developer on Notepad++ isn't going to do anything about this.  Perhaps better might be posting here:  https://notepad-plus-plus.org/community/

**Comment by jasonbrown1965** [comment]
> I dunno, I always thought when you are running under an OS that isn't exactly Windows, you are sorta on your own with these types of things. Certainly a developer on Notepad++ isn't going to do anything about this. Perhaps better might be posting here: https://notepad-plus-plus.org/community/

Aw, gee, sorry Github guy, wasn't aware, sorry for my mistake. Will ensure never to make another in the history of the Windows-only world, ever. Thanks for link !

**Comment by sasumner** [comment]
@jasonbrown1965 Well, I don't know what to say. A developer might say, "Retest this problem on machine with only a Notepad++ supported OS on it.  If problem exists there, continue this thread by stating that. Otherwise, close this issue."

**Comment by abdulbadii** [comment]
Geany on linux is about as good as notepad++

**Comment by jasonbrown1965** [comment]
Apologies for late closure!
