### ISSUE TITLE
Partial switch to Russian localization in the Search window.

### ISSUE THREAD

**Issue by andrecool-68** [notepad-plus-plus/notepad-plus-plus#5288]
In the Search window (when the search comes from the Folder as a project) and the File menu does not always switch to Russian, although the localization file is fine.

This happens on all versions of Notepad++  and does not depend on the system bitness.

![default](https://user-images.githubusercontent.com/3471892/52108626-41128180-2603-11e9-90db-8a6ca09c54ca.png)

![2](https://user-images.githubusercontent.com/3471892/52108823-f6453980-2603-11e9-9e78-437721ad75d6.png)

**Comment by ArkadiuszMichalski** [comment]
@andrecool-68 You still have this problem? Maybe you used old translation file. `Restore Recent...` was fixed in https://github.com/notepad-plus-plus/notepad-plus-plus/issues/6180.

![a](https://user-images.githubusercontent.com/2730894/93655634-0bfbb280-fa25-11ea-9ba2-ca8b341bc376.gif)

**Comment by andrecool-68** [comment]
@ArkadiuszMichalski It is not linked at all in the localization file!
