### ISSUE TITLE
Cannot start notepad++ with inaccessible network file in session.xml

### ISSUE THREAD

**Issue by plarus** [notepad-plus-plus/notepad-plus-plus#5289]
### Description of the Issue
If "C:\Users\%%LOGIN%%\AppData\Roaming\Notepad++\session.xml" file contain some path that are not currently available (shared folder over network) notepad++ cannot start correctly.

### Steps to Reproduce the Issue
1. Close Notepad++
2. Use the "session.xml" file below
3. Try to open Notepad++

### Expected Behavior
Start Notepad++ without not accessible files

### Actual Behavior
User interface is not display (Process do not respond). Processus should be killed.
A timeout on file opening is missing?

### Debug Information
Operating system : Windows 7 x64
Notepad++ version : 7.4.1 (32 bit)

My "session.xml" file :
`<NotepadPlus>
    <Session activeView="0">
        <mainView activeIndex="27">
            <File firstVisibleLine="1531" xOffset="0" scrollWidth="2323" startPos="69446" endPos="69452" selMode="0" lang="Ada" encoding="-1" filename="\\10.23.253.82\file.txt" backupFilePath="" originalFileLastModifTimestamp="1540981849" mapFirstVisibleDisplayLine="-1" mapFirstVisibleDocLine="-1" mapLastVisibleDocLine="-1" mapNbLine="-1" mapHigherPos="-1" mapWidth="-1" mapHeight="-1" mapKByteInDoc="1141080064" mapWrapIndentMode="-1" mapIsWrap="no" />
        </mainView>
        <subView activeIndex="0" />
    </Session>
</NotepadPlus>`

**Comment by Faq** [comment]
Firstly before reporting, why not update N++ to latest and retest yourself and then make issue if still problem there?

**Comment by plarus** [comment]
I have checked with the latest N++ version (7.6.3) and I get the same result!

(Sorry but due to network filtering it was not easy for me to download new setup version)

**Comment by MetaChuh** [comment]
@plarus 

a freeze/crash issue is not reproducible on the most recent version 7.6.6.

if multiple files are loaded from a mapped network drive and/or unc path, then notepad++ is closed, the network cable or wifi connection is disabled, and notepad++ is reopened, notepad++ will skip opening all previously opened files, which are currently not accessible.

please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html).

thank you for your help and best regards.

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
(no extra account is needed, just use your github account to sign in)
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)

**Comment by gair** [comment]
This is still an issue in 7.8.2.

`<NotepadPlus>
    <Session activeView="0">
        <mainView activeIndex="0">
            <File firstVisibleLine="687" xOffset="0" scrollWidth="2390" startPos="35316" endPos="35316" selMode="0" lang="HTML" encoding="-1" userReadOnly="no" filename="\\192.168.1.200\Archive\MovieCollection.html" backupFilePath="" originalFileLastModifTimestamp="-358365696" originalFileLastModifTimestampHigh="30786650" mapFirstVisibleDisplayLine="-1" mapFirstVisibleDocLine="-1" mapLastVisibleDocLine="-1" mapNbLine="-1" mapHigherPos="-1" mapWidth="-1" mapHeight="-1" mapKByteInDoc="15991027" mapWrapIndentMode="-1" mapIsWrap="no" />
        </mainView>
        <subView activeIndex="0" />
    </Session>
</NotepadPlus>`
