### ISSUE TITLE
"Save" not available after editing a file

### ISSUE THREAD

**Issue by AdrianHHH** [notepad-plus-plus/notepad-plus-plus#529]
I think I have found a fault in the way files are overwritten by the save and save-as commands. In some cases edits done after the first save are not detected and so the "save" command is not shown. The behaviour appears to be dependant on the file type. The fault appeared when overwriting a file where the name ends with ".bat" or a ".pl". The fault did not appear with a filename ending in ".txt" or ".webtest".

Using Notepad++ version 6.7.9.2
Settings -> backup -> "Remember current session ..." is not selected.

To demonstrate the fault:

Start Notepad++.
Type some text into the empty "new 0" tab, which is the only tab shown, leave the cursor at the end of the new text.
File -> Save (or save-as)
In the "Save as" window select an existing file, click Save.
On the "Confirm save as" window asking if you want to replace an existing file, click Yes.
Continue typing into the window. (Do not click in the window before typing.)

Observe that the "save" icon and the save command in the File menu both stay greyed out.
Click the red "X" in the top right-hand-corner to close Notepad++, observe that Notepad++ closes without warning about unsaved changes to the file.

**Comment by ptbrown** [comment]
:+1: 

I find this happens when I save a file using an extension different than the current language. After saving the language is updated to the new type, but changes to the file do not set the "dirty" flag. As well, the styler doesn't always update for the file. i.e. set the language to Perl then save as "file.php" and colors disappear. However, going from Text to PHP styles correctly, though the no-save bug still occurs.

Version 6.8
Plugins: CCompletion, EditorConfig, HTML Tag, NppJumpList,Spell-Checker, XBrackets Lite.
Remember current session enabled. Backups disabled.

**Comment by ptbrown** [comment]
I have determined that the problem is with the [Session Manager](http://mfoster.com/npp/SessionMgr.html) plugin.

**Comment by milipili** [comment]
@AdrianHHH Can you confirm that ?

**Comment by AdrianHHH** [comment]
I confirm that the fault is related to Session Manager. It was installed when I first reported the fault. Removing it makes the fault go away, after reinstalling it the fault reappears.

Steps I used to reproduce the fault.

Start notepad, observe that there is just the "New 0" tab showing.
Open a file named "zz2.webtest", my file only contains 18 characters on one line.
Click "New" and in the "New 1" tab type a few characters.
Use menu => File => SaveAs, saving to a file named "zz3.pl". Click yes to agree to overwriting an existing file.
Type some more characters into the window just saved.
Observe that the tab does not change to show that the window has been altered.

**Comment by mauriciolp** [comment]
I am also facing this bug, which is really annoying and it made me loose valuable hours of work because of it. I also use the Session Manager.
Still no update on it?
It seems similar to issue [#398](https://github.com/notepad-plus-plus/notepad-plus-plus/issues/398).

**Comment by donho** [comment]
I believe this issue has been implemented since long time ago.
Update your Notepad++ to the latest version (v7.6.6).
If the issue persists, please create a new issue for it.
Thank you.
