### ISSUE TITLE
Notepad++ Encoding Detection can be dangerous / is dodgy w. Unicode6.0

### ISSUE THREAD

**Issue by masbaehr** [notepad-plus-plus/notepad-plus-plus#5293]
Hi, I've noticed this behaviour with Notepad++ and i think this should be changed or bad things can happen...I'll explain

When opening a file without UTF-8 BOM which contains both ASCII and Unicode6.0 e.g emojis like  🚦 N++ will open it as Windows-1252 without any warning about it. Saving will then potentially damage that file. 

I think a warning should be added when N++ is not sure about which encoding to use instead of falling back to cp1252.

![image](https://user-images.githubusercontent.com/38694044/52259534-5b11d400-2923-11e9-83bb-c1dd50208f64.png)

I already messed up a lot of files due to this. Notepad.exe does it a lot better, as it will "guess" UTF8 which in today's world is a lot safer.

Of course it is possible to disable this behavior by setting this config, but a better solution should be found in my opinion.

![image](https://user-images.githubusercontent.com/38694044/52259572-75e44880-2923-11e9-8b04-1d8a326e3ea9.png)

**Comment by PauloFrancaLacerda** [comment]
I've noticed that too, and have also messed up some files of mine unknowingly.
the last safe version is v7.5.9 -- which I'm using since the bug was first noticed.

**Comment by MetaChuh** [comment]
fixed in https://github.com/notepad-plus-plus/notepad-plus-plus/commit/486e2188b2d4f5e897d5ffffa9b3dcd23b3ae2d6
