### ISSUE TITLE
Feature Request: Enable/disable auto-complete based on specific file / file type

### ISSUE THREAD

**Issue by Hammer2000** [notepad-plus-plus/notepad-plus-plus#5296]
I like the auto complete feature, but if I'm writing a straight up text file it tends to be more annoying than helpful despite altering the letter count before attempting to auto-complete. 

It would be great to add a way to enable or disable auto-completion for specific file types. 

Additionally it would be excellent to be able to enable or disable auto-completion for specific files as well.

**Comment by expectmiu** [comment]
I have the same idea. Auto-completion function will produce a bad user experience in editing normal pure-text article, especially in Chinese and other language which don't split words with separator such as space. 
These two situations usually appear. They are main reasons of bad user experience.
- Once I trigger auto-completion, long and meaningless text segment will appear and disturb inputting. 

![Snipaste_2019-09-20_10-37-49](https://user-images.githubusercontent.com/26505276/65295107-eaa68300-db92-11e9-968f-4b67035e5dfa.png)

- Once I fix some words in the middle of text, auto-completion will jump out, and hint me the whole text. 

![Snipaste_2019-09-20_10-38-17](https://user-images.githubusercontent.com/26505276/65295135-f8f49f00-db92-11e9-9ddf-73b6e185e577.png)
![Snipaste_2019-09-20_10-38-49](https://user-images.githubusercontent.com/26505276/65295148-001bad00-db93-11e9-98a1-9e367ab08e6b.png)


(My first language is Chinese, I'm sorry if there are some grammar or spelling mistakes. )

**Comment by donho** [comment]
For disabling auto-completion in all text files, it needs only choose "Function completion" in Preferences:

![image](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/90293/5b9ef7f4-35c3-4d73-aaa7-ae83ebbfb158)
