### ISSUE TITLE
Shortcut and menu command mismatched mapping for SCI_SELECTIONDUPLICATE and SCI_LINEDUPLICATE

### ISSUE THREAD

**Issue by UNIVAC-Colonel-Panic** [notepad-plus-plus/notepad-plus-plus#5298]
### Description of the Issue
1. [bug to fix] Shortcut mapper links control-d to SCI_SELECTIONDUPLICATE but it should map to SCI_LINEDUPLICATE instead.
2. [fyi] Menu command *Edit->Line Operations->Duplicate Current Line* does invoke SCI_LINEDUPLICATE, however the shortcut shown under *Edit->Line Operations->Duplicate Current Line* says control-d. Cosmetically this is OK.
3. [bug to fix] SCI_SELECTIONDUPLICATE isn't available to be mapped to a customized button.

### Steps to Reproduce the Issue

1. Select multiple lines of text and do control-D. The multi-line **selection** gets duplicated.
2. Select multiple lines of text and do *Edit->Line Operations->Duplicate Current Line*. The **single line** where the cursor is at gets duplicated.
3. Go to Customize Toolbar toolbar plugin and under "Available toolbar buttons" double-click on "Duplicate Current Line."
### Expected Behavior

I expected to press the custom button and have it emulate **control-d** (SCI_SELECTIONDUPLICATE), because **control-d** is what the GUI shows.
### Actual Behavior

Pressing the custom button does SCI_LINEDUPLICATE.

### Debug Information

Notepad++ v7.5.9   (32-bit)
Build time : Oct 14 2018 - 15:02:52
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10 (64-bit)
Plugins : DSpellCheck.dll mimeTools.dll NppConverter.dll NppExport.dll CodeAlignmentNpp.dll JSMinNPP.dll MarkdownViewerPlusPlus.dll NPPJSONViewer-win32.dll NppTextFX.dll PluginManager.dll Tidy2.dll _CustomizeToolbar.dll 

![screenshot 2019-02-05 at 10 08 41 pm](https://user-images.githubusercontent.com/492973/52387568-9dc8ce80-2a3f-11e9-8478-8bb2d041afa6.png)

[notepad-duplicate-current-line.zip](https://github.com/notepad-plus-plus/notepad-plus-plus/files/2839125/notepad-duplicate-current-line.zip)

Screen recording is in attached file notepad-duplicate-current-line.zip which can be viewed with [Screencastify](https://chrome.google.com/webstore/detail/screencastify-screen-vide/mmeijimgabbpbgpdklnllpncmdofkcpn) on Chrome _or_ using [VLC media player](https://www.videolan.org/vlc/).

Yes, I know how confusing this is. :D There are two bugs to fix.

You can see original discussion between me and [Meta Chuh](https://notepad-plus-plus.org/community/user/meta-chuh) by going [here](https://notepad-plus-plus.org/community/topic/17047/customize-toolbar-plugin-and-duplicate-current-line-plugin/5).

**Comment by taa1** [comment]
Note that [Keyboard And Mouse Shortcuts - Notepad++ Wiki](http://docs.notepad-plus-plus.org/index.php/Keyboard_And_Mouse_Shortcuts) also has the discrepancy. Search for 'ctrl-d' and 'ctrl+d'. SCI_SELECTIONDUPLICATE is showing for 'ctrl+d'. If you can tell me how to register to make changes on the Wiki, I'll be glad to update the table.

**Comment by alankilborn** [comment]
OK, first, forget the stuff about any plugin.  Unless and until core Notepad++ works correctly, the plugin is unimportant.

I did some testing with N++ 8.4.4 (current version as of this writing) and here are my observations:

* Executing the menu choice for "Edit" > "Line Operations" > "Duplicate Current Line" will duplicate only the line of the caret, no matter what selection of text is made first.

* Executing Ctrl+d (with the default keymapping unchanged) will, if no selection is currently active, duplicate the current line

* Executing Ctrl+d (with the default keymapping unchanged) will, if a selection is currently active, duplicate the selected text

Conclusions:

* Since the menu entry reports that its keycombo is Ctrl+d, the fact that the menu invocation vs. the keyboard invocation does different things is wrong.

* There is no real description in the Scintilla docs about what SCI_DUPLICATESELECTION does when no selection is made (should it duplicate the current line in this case?)

* THERE IS A PROBLEM HERE that should be addressed.

**Comment by NeilS-Wpg** [comment]
The present behavior of SCI_DUPLICATESELECTION (default Ctrl+d) :

- If text is selected, dup it
- Else, dup the line containing the caret

is excellent.

I recommend that the menu invocation be changed to do the same, and that it's description be changed to:

- **Duplicate Current Selection XOR Line**

I can _imagine_ a user selecting either text on a line or text spanning multiple lines, and then wanting/needing to dup only the line containing the caret, but only when the bluest of blue moons is floating in the night sky.

**Comment by alankilborn** [comment]
@NeilS-Wpg said:

>The present behavior of SCI_DUPLICATESELECTION (default Ctrl+d)...is excellent

Well... the overall behavior is NOT excellent if running the menu item (that indicates equivalence to Ctrl+d) by selecting it from the menu, acts differently from invoking via Ctrl+d.  And it does.

**Comment by alankilborn** [comment]
I had said earlier:

>it may help to search the codebase in regex mode for occurrences of SCI_(LINE|SELECTION)DUPLICATE, although that really didn't reveal the problem to me. 

Ctrl+d is tied to SCI_SELECTIONDUPLICATE:

https://github.com/notepad-plus-plus/notepad-plus-plus/blob/6b34f9ce085b796eab134e7d3eda6a2dfe9db8b3/PowerEditor/src/Parameters.cpp#L475

Which leads to this Scintilla function call:

https://github.com/notepad-plus-plus/notepad-plus-plus/blob/6b34f9ce085b796eab134e7d3eda6a2dfe9db8b3/scintilla/src/Editor.cxx#L3974

which in turns leads to:

https://github.com/notepad-plus-plus/notepad-plus-plus/blob/6b34f9ce085b796eab134e7d3eda6a2dfe9db8b3/scintilla/src/Editor.cxx#L3071-L3074

**Comment by alankilborn** [comment]
Thus, the unifying solution to this issue, is to change:

https://github.com/notepad-plus-plus/notepad-plus-plus/blob/6b34f9ce085b796eab134e7d3eda6a2dfe9db8b3/PowerEditor/src/NppCommands.cpp#L1747-L1749

to:

_pEditView->execute(***SCI_SELECTIONDUPLICATE***);

**Comment by alankilborn** [comment]
In the end, I think what is best for this issue is to simply move the tie of IDM_EDIT_DUP_LINE from the Scintilla shortcut for SCI_SELECTIONDUPLICATE over to SCI_LINEDUPLICATE ... and leave the shortcut for SCI_LINEDUPLICATE unassigned by default.  Note that this will cause the menu item for _Edit_ > _Line Operations_ > _Duplicate Current Line_ to show no shortcut by default (but there's no problem with that).

**Comment by Yaron10** [comment]
@NeilS-Wpg: https://github.com/notepad-plus-plus/notepad-plus-plus/issues/5298#issuecomment-1326735141.
@alankilborn: https://github.com/notepad-plus-plus/notepad-plus-plus/issues/5298#issuecomment-1327478615.

👍 

Note that on partially selected line(s), only the selected part should be duplicated. And it makes sense.

**Comment by Yaron10** [comment]
@alankilborn,

That's correct.
But why not fix the specific issue and improve the command? - Many users are "mouse-oriented". :)

**Comment by alankilborn** [comment]
>...and improve the command?

The command refers to line duplication and is in the _Line Operations_ submenu.
I think this should be exactly what the user gets.

Now, if there's a need for a menu command that duplicates a selection or the line if there's no selection, I suppose that's fine, but IMO it should be a separate menu command.

**Comment by Yaron10** [comment]
> The command refers to line duplication and is in the Line Operations submenu.

👍 

Can you test the "Move Current Line Up/Down" commands?

**Comment by Yaron10** [comment]
It's true that the "Move Current Line Up/Down" commands move partially selected line(s) as well.

But in Duplicate the common use would also be no selection or several selected lines.

**Comment by alankilborn** [comment]
Please don't talk this one to death.
Let's just get a long-standing problem fixed
:-)

**Comment by Yaron10** [comment]
I'm taking the vow of silence. :)
