### ISSUE TITLE
Confirmation prompt for "Close All"?

### ISSUE THREAD

**Issue by InvisibleUp** [notepad-plus-plus/notepad-plus-plus#53]
When I am dealing with tabs I often want to close them. I do this by right clicking on the tab and hitting "Close". However, if I accidentally click on the one below that, "Close All BUT This", it annoyingly closes every single file I had open, which forces me to go back and reopen them all back up. It would be nice if you could add an "Are You Sure?" dialog, or at least move it somewhere else on the list so you can't accidentally click on it.

**Comment by MAPJe71** [comment]
I don't want a confirmation prompt when I knowingly and willingly want to "Close All BUT This", "Close All to the Left" or "Close All to the Right".

To close a single file one can
1. use the close function from the File menu;
2. use a shortcut (Ctrl+W);
3. use the close button in the toolbar.
4. double click on the tab (presuming this option has been enabled in the preferences);

Alternatives 2 and 4 won't let you close all files by accident, for alternative 3 it can be prevented by rearranging the toolbar buttons using the Customize Toolbar plugin.

**Comment by PalashBansal** [comment]
@MAPJe71  Yes it will be troublesome with extra prompt when knowingly closing multiple tabs.
But options-

- use the close function from the File menu;
- right click on tab > Close

buttons are given and are meant to be used. End user(newbies) may not be aware of 'shortcuts' and 'preferences tab double click' and can accidently select wrong option.

**One way can be to put a prompt by default and 'an option in Settings>preferences tab to disable prompt'.** what is your suggestion on this?

**Comment by MAPJe71** [comment]
No prompt by default (i.e. current situation) and an option in preferences to enable prompt.

**Comment by donho** [comment]
Use close button instead context menu for closing file then.
Such behaviour won't be implemented.
