### ISSUE TITLE
v6792 does not remember last window position at startup.

### ISSUE THREAD

**Issue by sky5walk** [notepad-plus-plus/notepad-plus-plus#530]
How to force Notepad++ to remember last window position on startup?

**Comment by Rikk** [comment]
Mine remembers... Isn't it something from Windows? Do you have this with some other program?

**Comment by Rikk** [comment]
It writes a line like this in `config.xml` file. Make sure Np++ has write access to that file.
```xml
<GUIConfig name="AppPosition" x="151" y="152" width="1064" height="666" isMaximized="yes" />
```

**Comment by Rikk** [comment]
If that was the issue, could you please close the Issue?

**Comment by sky5walk** [comment]
Thanks, but the file date/time is changing so I assume Notepad++ has write access.
If I change the window position/size, it is not stored to config.xml.
If I manually edit the config.xml file for my desired position then that is used on Startup.

These files are modified when I close Notepad++
"C:\Users\{myusername}\AppData\Roaming\Notepad++\shortcuts.xml"
"C:\Users\{myusername}\AppData\Roaming\Notepad++\Compare.ini"
"C:\Users\{myusername}\AppData\Roaming\Notepad++\config.xml"
"C:\Users\{myusername}\AppData\Roaming\Notepad++\session.xml"

**Comment by sky5walk** [comment]
Wait, now it is updating after I deleted the config.xml file!
(Actually, renamed it to config1.xml in case Notepad++ did not recreate it.)
I can close this now, but Notepad++ should give an error message if it cannot write out its settings?
Hopefully, this helps anyone else with similar problem.

**Comment by Rikk** [comment]
> I can close this now, but Notepad++ should give an error message if it cannot write out its settings?

Yes, I tested it running from a folder it could not write to, and received these 2 dialogs: (after that Npp opened itself but with a strange appearance (wrong toolbar icons, strange menus, default theme etc.)
![untitled-2](https://cloud.githubusercontent.com/assets/2916485/8819362/2bf58f02-3022-11e5-8029-c640184ec8e2.png) (Sim = Yes)
![untitled-3](https://cloud.githubusercontent.com/assets/2916485/8819363/2dc5458e-3022-11e5-8842-4372d2eb4afe.png)
