### ISSUE TITLE
Setup fuzzing of NPP and Scintilla using https://github.com/google/oss-fuzz

### ISSUE THREAD

**Issue by KOLANICH** [notepad-plus-plus/notepad-plus-plus#5302]

**Comment by MetaChuh** [comment]
_No description provided._

**Comment by KOLANICH** [comment]
I don't see it implemented.

**Comment by sasumner** [comment]
@KOLANICH I suspect that is because _No description provided_ but that is probably not the only reason.

**Comment by KOLANICH** [comment]
I suppose that all the info needed is contained in the title of the issue, so it is probably another reason.

**Comment by sasumner** [comment]
@MetaChuh Closure was the right call.
