### ISSUE TITLE
Freeze/hangs when network drive has bad connection 

### ISSUE THREAD

**Issue by z3rone** [notepad-plus-plus/notepad-plus-plus#5304]
### Description of the Issue

Notepad++ freezes while I'm editing a file on a network drive (not just when saving, also while editing). The internet connection is indeed poor but the software should not crash because of that.
### Steps to Reproduce the Issue

1. Setup a network drive via SFTP NetDrive (Win10)
2. Open a file from the network drive
3.  Get a really bad internet connection
4. Notepad++ freezes

### Expected Behavior

Notepad++ should keep responding to user input and warn if saving times out.

### Actual Behavior

Notepad++ freezes completely and does not recover from this state. Restart of software required.

### Debug Information
OS: Win10
Notepad++ v7.5.9
Network drive software: SFTPNetDrive

**Comment by MetaChuh** [comment]
@z3rone 

a freeze/crash issue is not reproducible on the most recent version 7.6.6.

if multiple files are loaded from a mapped network drive and/or unc path, then notepad++ is closed, the network cable or wifi connection is disabled or the connection has deteriorated completely, notepad++ will alert you "the file does not exist anymore. keep this file in editor?", on all files which are currently not accessible, when switching tabs.

please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins if you update from version 7.5.9 or below.

thank you for your help and best regards.

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
(no extra account is needed, just use your github account to sign in)
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)

**Comment by cyrilh** [comment]
I have this issue with a drive on a NAS... one of the raid drives has a problem, and Windows explorer will often freeze while changing folder or refreshing... 

But as z3rone said, this should not happen on the best of editors while simply editing a file... for me Notepad++

Experienced on notepad++ version 7.8.4

**Comment by axipher** [comment]
This is still an issue when I had a text file open form a network drive and that network drive went offline.  Now Notepad++ won't even open.

I had to delete "%appdata$\Notepad++\session.xml" to even be able to open Notepad++ again.
