### ISSUE TITLE
Feature Request for window placement

### ISSUE THREAD

**Issue by Pookalton** [notepad-plus-plus/notepad-plus-plus#5308]
ATM windows appear in the last location a notepad++ window was.
Can you guys make it so they appear in the last location of a window which had a file opened with the same extension was closed?
I'm an "always multi-instance" user who opens 4 different file extensions all day long as I process GNSS data.  Would be great if they opened on the same section of the same screen.  Save me dragging them around.

-Pook

**Comment by Faq** [comment]
Would you mind posting example picture of expected result?

**Comment by Pookalton** [comment]
That when I open a .txt file the window opens in the last location a .txt file window was, and when I open a .something file it's window opens in the last location a .something file was.

**Comment by Pookalton** [comment]
I usually look at files with 3 different extensions, have two on half of one monitor and one on another.  Then close all three and open another three and have to place them where I need them as they will all open in the location of the last window I closed.

**Comment by MetaChuh** [comment]
thank you for your feature ideas.

the implemented design structure only allows saving of the last closed notepad++ window in config.xml.

storing that information for every instance, as if they would be each a separated portable version of notepad++ will not be implemented.

thank you for your help and best regards.

-----
```
general notes:

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
(no extra account is needed, just use your github account to sign in)
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)
