### ISSUE TITLE
LICENSE in source is GPL2 but the website points at GPL3.

### ISSUE THREAD

**Issue by nevdelap** [notepad-plus-plus/notepad-plus-plus#5309]
### Steps to Reproduce the Issue
1. Click the GPL link in: https://notepad-plus-plus.org/

### Expected Behavior
It should go to: http://www.gnu.org/licenses/gpl-2.0.html because https://github.com/notepad-plus-plus/notepad-plus-plus/blob/master/LICENSE is version 2.

### Actual Behavior
It goes to: http://www.gnu.org/copyleft/gpl.html

So I'm just suggesting to change the link on the website.

**Comment by SGADDIPA** [comment]
Hi nevdelap,

Looks when we click on GPL it goes to http://www.gnu.org/copyleft/gpl.html as expected.

regards,
GSR

**Comment by Faq** [comment]
@SGADDIPA read again what is written under "Expected Behavior".

**Comment by nevdelap** [comment]
Hi @sgaddipa, what you way is expected is what I said is the problem. It is opening the gplv3 page when the software is gplv2.

**Comment by SGADDIPA** [comment]
You are right, my apology for that.

**Comment by ArkadiuszMichalski** [comment]
@donho Maybe fix this tn the meantime? The correct license version may be important for someone.

In https://notepad-plus-plus.org/ you point to v3 https://www.gnu.org/licenses/gpl-3.0.html
![aa](https://user-images.githubusercontent.com/2730894/93655111-fafd7200-fa21-11ea-91fb-04e00281b5a3.gif)

But in repo you point to v2 https://github.com/notepad-plus-plus/notepad-plus-plus/blob/master/LICENSE
![image](https://user-images.githubusercontent.com/2730894/93655143-2da76a80-fa22-11ea-806d-2bb7d283d877.png)

If necessary link for v2 still exist https://www.gnu.org/licenses/old-licenses/gpl-2.0.html.

**Comment by donho** [comment]
It's fixed and committed. The site will be updated soon.
