### ISSUE TITLE
UTF-8 detection failing

### ISSUE THREAD

**Issue by vlakoff** [notepad-plus-plus/notepad-plus-plus#5310]
How to reproduce:
* Create a file containing `exécuter`, encoded as UTF-8 without BOM.
* Open this file with Notepad++.

Current behaviour:
* File is detected as ISO 8859-9 and displayed content is `exÃ©cuter`.

Expected behaviour:
* File should be detected as UTF-8.

Noteworthy note:
* If there is one less character (e.g. content is `exécute`), the file is properly detected as UTF-8.

I encountered the issue on Notepad++ 7.6.1 and 7.6.3. If I recall correctly, I wasn't having the issue with some older versions, so this might be a relatively recent regression.

Of course, "UTF-8 > Apply to opened files" is checked in my preferences.

**Comment by MetaChuh** [comment]
@vlakoff 

yes, this is a known issue.
autodetect character encoding is broken since notepad++ version 7.6.

currently you have to disable `settings > preferences > misc > autodetect character encoding` as seen at the screenshot below.

![settings - auto detect character encoding](https://i.imgur.com/9SZ5ufh.png)

**Comment by vlakoff** [comment]
If the issue has been introduced in 7.6,
I see two possible culprits: ac09857656caf15752ea170d9cd4a080a6a58147 and/or bfb7e863cc6cd20f9f32389bee289607a212b12b

ping @CookiePLMonster :)

**Comment by MetaChuh** [comment]
@vlakoff 
yes, the culprit is bfb7e86 UCharDet 0.0.6.
the same compiled source code runs fine on ubuntu and mac, detecting all my test files correctly with various languages, but if the same (!) source code is compiled on windows, it behaves very erratically.

easiest to reproduce with the compiled standalone uchardet command line checker tool.
once compiled on ubuntu and windows, both will have very different detection results on the same files.

**Comment by vlakoff** [comment]
I have compiled nightly of ucharset using these [instructions](https://github.com/BYVoid/uchardet/issues/39#issuecomment-353829624) and tried it.
Sadly it seems to also have the issue, and to be even worse…

ucharset nightly:
* `ééé`: UTF-8
* `exécuter`: WINDOWS 1250
* `exécute`: WINDOWS 1250
* `xécuter`: IBM852

Notepad++ 7.6.3 (ucharset 0.0.6):
* `ééé`: UTF-8
* `exécuter`: ISO 8859-9
* `exécute`: UTF-8
* `xécuter`: UTF-8

**Comment by CookiePLMonster** [comment]
This is very upsetting. Upgrade broke detection in some cases but it was
done to fix it elsewhere - so what would mean the library introduced
regressions. I'm not sure how to proceed with that, seems like a lose-lose
situation...

**Comment by vlakoff** [comment]
Apparently the issues happen only on Windows builds,
so there should be some obscure bug on the uchardet side that really should be found and fixed…

Meanwhile, would it be technically doable to manually increase the priority of UTF-8? :thinking:
As an ugly, ugly and ashaming workaround. :sweat_smile:

**Comment by MetaChuh** [comment]
@CookiePLMonster

> This is very upsetting. Upgrade broke detection in some cases but it was done to fix it elsewhere - so what would mean the library introduced regressions. I'm not sure how to proceed with that, seems like a lose-lose situation...

yes, i agree with you, and i suppose anything (regression, fix attempts) would be better than to leave it like it is.
we would gladly offer as much time as needed, to help with any fix attempt tests, using all our documents, collected from personal tests, and reports at the notepad++ community.

-----

the strangest thing is that indeed the same uchardet 0.0.6 source code behaves differently when compiled on windows than to ubuntu.

a linux uchardet cli build detects all files we've tested correctly as utf-8, but the windows uchardet.exe cli build shows the same, multiple, erroneous mismatches as notepad++ 7.6+ does, on the same test files 🤔❓

here is a screenshot of 4 windows uchardet cli tests:

![Imgur](https://i.imgur.com/FZDyj4Y.png)

and here again on ubuntu (same uchardet 0.0.6 source code, same files) for direct comparison:

![Imgur](https://i.imgur.com/knrY3ki.png)

**Comment by MetaChuh** [comment]
@CookiePLMonster and all
did you make up your mind on how to proceed with this issue ?

if not you are very welcome to join everyone at the notepad++ community, and answer at least 25% of the issue reports, as soon as the [auto updater url](https://notepad-plus-plus.org/update/getDownloadUrl.php?version=7.59) will be set from 7.5.9 to 7.6.4, deploying the current UCharDet 0.0.6. implementation to millions of users ;-)

**Comment by CookiePLMonster** [comment]
Perhaps it should be just rolled back then? Clearly there is something
about charset detection which makes it ridiculously hard to cover all cases
flawlessly.
