### ISSUE TITLE
tab renamed then Notepad++ crash

### ISSUE THREAD

**Issue by Victlafa** [notepad-plus-plus/notepad-plus-plus#5313]
Notepad++ v6.7.1
Build Time : Dec 21 2014 - 20: 13: 12
Windows 7

### Description of the Issue
Sometimes, while editing files stored on network thanks to clearcase, when I move the tab on the very right of a view, it is renamed mostly with Asian signs, and some other characters. When I move it again and switch its position with an other tab, the name of the second tab becomes the name of the first tab (with Asian signs). I cannot use the tab when they are renamed, the cross button does not respond and when I do File -> Close, Notepad++ crashes.
The problem doesn't often appear when I move the tabs, but in one week it happened twice.
The last time it happened, a message appeared to say a pure virtual function had been called.
When I open again the files with Notepad++ after closing it, they have their original name.

### Steps to Reproduce the Issue
1. Open different tabs.
2. Move the last tab on the right to the left.
3. Sometimes it is renamed with Asian signs.
4. Switch its position with an other tab, the second tab as now the same name of the first one.

### Expected Behavior
Tab to be moved and files to be editable.

### Actual Behavior
Tabs are renamed, files cannot be edited again, if I try to close the file through the menu, Notepad++ crashes, and the cross button of the tab doesn't answer at all. Sometimes, when I try to clos Notepad++ after the bug, its window can not be closed, even when I do Ctrl+Alt+Suppr and I try to kill the processus.

The first time it happened, I managed to reproduce the issue and the new name of the tab was the same. But when the issue came back several days later, the name given changed a bit.

I asked the ServiceDesk of my company some help but they had no idea why this happened.

In "files_renamed.png" : on the top you have the first time the bug appears, and then what happened after switching the position of the tabs several times.
In "files_renamed.png" : the name given to the files when it happened again. 
In "error_message.png" : the message that appeared when I tried to quite Notepad++ after I reproduced the bug.

**Comment by Faq** [comment]
Please update your notepad

**Comment by donho** [comment]
Please update your notepad++ to v7.6.3, please open a new issue if the bug is reproducible in the new version.
