### ISSUE TITLE
Notepad++ crash if network resource is not available anymore

### ISSUE THREAD

**Issue by dojo90** [notepad-plus-plus/notepad-plus-plus#5315]
### Steps to Reproduce the Issue
1. Open a file on network
2. close Notepad (not the file)
3. Remove network resource or switch into another subnet
4. Open Notepad
5. It will try to open the last used file
6. App freezes und crashes

### Expected Behavior
Popup with alert "opening file .." and an optional "cancel" button

### Actual Behavior
Notepad freezes / crashes

### Debug Information
Notepad++ v7.5.9   (32-bit)
Build time : Oct 14 2018 - 15:02:52
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10 (64-bit)
Plugins : DSpellCheck.dll mimeTools.dll NppConverter.dll NppExport.dll

**Comment by Faq** [comment]
dublicate atleast of #4877 and #5304

**Comment by MetaChuh** [comment]
@dojo90 

a freeze/crash issue is not reproducible on the most recent version 7.6.6.

if multiple files are loaded from a mapped network drive and/or unc path, then notepad++ is closed, the network cable or wifi connection is disabled, and notepad++ is reopened, notepad++ will skip opening all previously opened files, which are currently not accessible.

please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins if you update from version 7.5.9 or below.

thank you for your help and best regards.

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
(no extra account is needed, just use your github account to sign in)
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)
