### ISSUE TITLE
Fortran syntax highlighting only works on fixed-form code

### ISSUE THREAD

**Issue by louisrousseau** [notepad-plus-plus/notepad-plus-plus#532]
As per title, the syntax highlighting only works with 72 column code.
In fixed-form code the first six characters on a line have a significant meaning, which they don't in free-form Fortran 90 and later revisions.
Also, language keywords are not treated as such beyond the 72nd column.

Ideally, distinguish between the two types via file extensions: .f and .for for fixed-form, f90 f95 f2k for free.

**Comment by dail8859** [comment]
Closed by #1381
