### ISSUE TITLE
Feature request: Select the next occurrence - shortcut

### ISSUE THREAD

**Issue by remoteme** [notepad-plus-plus/notepad-plus-plus#5322]
In intelij there is Alt+J its working like ctrl+f3 in notepad++ -  Select and Find Next
the diffrent is the previous selected text is still selected and this function is named
Select the next occurrence
Since Notepad++ is supporting multi-editing it should not be a big issue, and I think its great feature, and helps a lot while changing the code

Regards,
Maciek

**Comment by remoteme** [comment]
better title

**Comment by sasumner** [comment]
This has been scripted as a possible solution.  See here: https://notepad-plus-plus.org/community/topic/11360/multi-selection-and-multi-edit

**Comment by remoteme** [comment]
Thanks i will check it out :)

**Comment by sasumner** [comment]
You probably shouldn't have closed this if you'd like to see it implemented natively in Notepad++.

**Comment by remoteme** [comment]
OK reopened, since at the link i wasnt get how i wanted to work, so still waiting for imlemented natively :)

**Comment by sasumner** [comment]
I think you'd better be clearer on how you want it to work.  It is not that clear to me at least.

**Comment by remoteme** [comment]
here showed very clearly
[https://s2.gifyu.com/images/multiEditVSCode.gif](https://s2.gifyu.com/images/multiEditVSCode.gif)
