### ISSUE TITLE
Change behavior of **? > Get More Plugins** menu item (or remove that menu entry altogether)

### ISSUE THREAD

**Issue by pryrt** [notepad-plus-plus/notepad-plus-plus#5325]
In Gerald Kirchner's [2019-02-16T22:54:10.388 post](https://notepad-plus-plus.org/community/topic/17084/udl-block-comment-in-one-line-error/23) in the "[UDL: /* block comment in one line, error */](https://notepad-plus-plus.org/community/topic/17084/udl-block-comment-in-one-line-error)" thread in the Community Forums, it became obvious that the **? > Get More Plugins** menu item is more dangerous than helpful, in Notepad++ v7.6.3:

The **? > Get More Plugins** menu item takes you to [Plugin Central](http://docs.notepad-plus-plus.org/index.php/Plugin_Central), but Plugin Central is out of date.  The correct place to go to get new plugins for modern Notepad++ is to click on the **Plugins > Plugins Admin** menu item.  Directing people to Plugin Central, where the links are years out of date, where the plugins are all 32-bit, and where any links that are still valid will likely be to zipfiles that have the wrong folder structure causes users more confusion than not having that particular menu button.

My recommendation is to do one of these three things to the **? > Get More Plugins** menu item in Notepad++ excecutable.  Personally, I think #3 is best, but any would be better than the current situation in 7.6.3.
1) change the **? > Get More Plugins** menu item to just open **Plugins Admin**
2) change the **? > Get More Plugins** menu item to open a dialog which tells the user to use **Plugins > Plugins Admin** instead
3) or just delete the **? > Get More Plugins** menu item.

**see also**: This is similar to, but (IMO) distinct from, issue #4754.  I believe this is different because @perNyfelt was just asking for the link to the old Plugin Manager plugin to be changed on the Plugin Central page.  My issue is asking for a change to the Notepad++ codebase itself.

**Comment by MetaChuh** [comment]
can this be closed with https://github.com/notepad-plus-plus/notepad-plus-plus/commit/4472620f3039d3e6fd61da8b2095b7f3c9b02551 ?

**Comment by pryrt** [comment]
yep, I agre; closed with 4472620
