### ISSUE TITLE
open a File from a mapped Networkshare which includes a blank in the path

### ISSUE THREAD

**Issue by apavic-tgm** [notepad-plus-plus/notepad-plus-plus#5329]
Hi all!

I've attached the problem below.

THANKS!
kr tony
[issue.pdf](https://github.com/notepad-plus-plus/notepad-plus-plus/files/2879926/issue.pdf)

**Comment by MetaChuh** [comment]
@apavic-tgm 

it is most likely, that you have a left over "shell open command" from an older notepad++ installation
(one where the path argv `%1` is not passed to notepad++.exe as `"%1"` within double-quotes)

please open regedit.exe and browse to the following keys:
HKEY_CLASSES_ROOT\Applications\notepad++.exe\shell\open\command
HKEY_CLASSES_ROOT\Notepad++_file\shell\open\command
HKEY_CURRENT_USER\Software\Classes\Applications\notepad++.exe\shell\open\command
HKEY_LOCAL_MACHINE\SOFTWARE\Classes\Notepad++_file\shell\open\command

check the entries and make sure that the argument values are within double-quotes at the default (standard) REG_SZ value of all these keys:
`"C:\Program Files (x86)\Notepad++\notepad++.exe" "%1"`
(make sure it is **not** `C:\Program Files (x86)\Notepad++\notepad++.exe %1` )
for the 32 bit version.

or `"C:\Program Files\Notepad++\notepad++.exe" "%1"` if you are using the 64 bit version

(you did not provide your mandatory debug information, so we are not aware of which release of 7.6.3 you are using)
