### ISSUE TITLE
v6.8: Search for CommaCRLFCRLF finds nothing in a WinDOS UTF-8 [Normal] Text File

### ISSUE THREAD

**Issue by Doryforos** [notepad-plus-plus/notepad-plus-plus#533]
Notepad++ v6.8 on MS-WinXP Pro + SP 3 + Updates

Doing a regex search [CTRL+F] for ,\r\n\r\n produces no results in a WinDOS UTF-8 Normal Text file, even though this string exists many times in this file; but, doing the same search for ,\n\n (i.e. omitting the CR's) finds every occurrence of a comma at the end of a line, followed by an empty line, in the same file (!). Also, a regex search for \r\n, \r, \n and \r\n\r\n, produces the expected results.

Notepad++ v6.7.9.2 performed the same search OK.

**Comment by Rikk** [comment]
Seems to work here... does it happens only in one file?
Btw, if not using regex in search but only new line symbols, I think using Extended mode should be a bit faster.

**Comment by AdrianHHH** [comment]
What does Menu => **View** => **Show Symbols** => (tick) **Show end of line** reveal about the contents of the file?

**Comment by Doryforos** [comment]
I seem unable to reproduce this in any file.

I double-checked what is suggested here -- the file that this occurred in [if at all] has no mixed EOL [and never had] and is definitely a CR/LF file: all 3 searches for \r\n, \r and \n, produce[d] the exact same count of No of lines minus one, i.e. what is expected.

The issue might be due to something else -- I cannot tell.

Thank you all and let's consider this a non-issue.
