### ISSUE TITLE
Notepad++ shows error when opening a file from context menu

### ISSUE THREAD

**Issue by MaikaiLife** [notepad-plus-plus/notepad-plus-plus#5331]
### Description of the Issue
With prior versions of Notepad++ if you added a context menu entry using the following registry keys, you would get this menu item and it opened without error.

[HKEY_CLASSES_ROOT\*\shell\Notepad++\command]
@="C:\\Program Files (x86)\\Notepad++\\notepad++.exe %1"

![image](https://user-images.githubusercontent.com/36651116/53047612-a5c53d00-3447-11e9-984e-8bc8c1c2e081.png)

### Steps to Reproduce the Issue
1.  Install the context menu registry 
2. Right-click a file and try to open from the context menu.

### Expected Behavior
File opens in notepad++

### Actual Behavior
Error is displayed saying
![image](https://user-images.githubusercontent.com/36651116/53048434-9b0ba780-3449-11e9-9cfb-f13912911c16.png)

### Fix
Change -> @="C:\\Program Files (x86)\\Notepad++\\notepad++.exe %1"
to -> @="C:\\Program Files (x86)\\Notepad++\\notepad++.exe \"%1\""

It seems the %1 now needs wrapped in double quotes but didn't need this in prior versions.

**Comment by sasumner** [comment]
>It seems the %1 now needs wrapped in double quotes but didn't need this in prior versions.

Yes.  It is a design change.

But it really isn't an "issue".  Any objection to closing this?

**Comment by MaikaiLife** [comment]
I couldn't find reference to this change so I wasn't sure if this was intended or unintended behavior.  Sounds like it's intended based on your comment so I'm satisfied.  

Thank you for the clarification.

**Comment by sasumner** [comment]
@MaikaiLife I'm pretty sure it was a change in 7.5.9.
