### ISSUE TITLE
Extended Search mode in Find not reinitialized at start

### ISSUE THREAD

**Issue by wonderkatn** [notepad-plus-plus/notepad-plus-plus#5333]
### Description of the Issue
After Restarting Notepad++ I see the option for Extended search (using \n,\r ect.) is selected in the GUI, but search does not preform as such until it is deselected and re selected.

### Steps to Reproduce the Issue
1.  Select Extended Search mode
2.  Restart Notepad++
3.  Search for CR+LF using \r\n
4. Select Regex and re select extended search mode and repeat step 3

### Expected Behavior
on Step 3 you should be able to find a CR+LF

### Actual Behavior
Nothing is found

### Debug Information
Notepad++ v7.5.9   (32-bit)
Build time : Oct 14 2018 - 15:02:52
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10 (64-bit)
Plugins : DSpellCheck.dll mimeTools.dll NppConverter.dll NppExport.dll

**Comment by wonderkatn** [comment]
reproduced with this version
Notepad++ v7.6.3   (64-bit)
Build time : Jan 27 2019 - 17:16:47
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10 (64-bit)
Plugins : DSpellCheck.dll mimeTools.dll NppConverter.dll

**Comment by sasumner** [comment]
Sounds like some startup weirdness perhaps like the lonely #3640 that has never gotten fixed.

**Comment by MetaChuh** [comment]
@wonderkatn 

an extended search mode misbehaviour on restart is not reproducible on 7.6.6, as seen at the screencast below..

please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html).

![#5333 ok, 7 6 6 extended search on startup](https://user-images.githubusercontent.com/45773305/57219102-58dd1580-6ff7-11e9-9370-b1a6b25af498.gif)

if your experience still persists, please test the following, to verify, if a clean notepad++ (without any plugins that could cause this) would work on your system.

* download the notepad++ 7.6.6. 64 bit portable version from [>>> here <<<](https://notepad-plus-plus.org/repository/7.x/7.6.6/npp.7.6.6.bin.x64.zip).
(the portable version does not require any installation and runs completely independent and isolated from your installed version. all custom settings, as well as any stuff you might want to try at the portable version, will not modify your installed version)

* extract `npp.7.6.6.bin.x64.zip` to your desktop.
(copy `npp.7.6.6.bin.x64.zip` from your download folder to your desktop, right-click on it, select `extract all` from the explorer context menu, and press `extract` to extract it to a folder called `npp.7.6.6.bin.x64` on your desktop)

* **important note:** make sure to close all instances of notepad++ that might be running, before starting the portable version at the next step, to be sure you are using the portable version for this test.

* open the extracted `npp.7.6.6.bin.x64` folder and start this portable version by double-clicking on `notepad++.exe` inside this folder.
(note: notepad++.exe will just be seen as notepad++, if you have enabled to hide all known file extensions at your explorer settings)

* retry steps 1-3 on this portable notepad++

thank you for your help and best regards.

-----
```
general notes:

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
(no extra account is needed, just use your github account to sign in)
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)
