### ISSUE TITLE
Confusing and unexpected response to read-only attribute. (Keystrokes are ignored; "save" is ignored)

### ISSUE THREAD

**Issue by netpog** [notepad-plus-plus/notepad-plus-plus#5334]
### Description of the Issue

NPP's handling of read-only files is unusual, unexpected, and confusing.  It ignores edits, and the Save command.  Every other editor seems to accept the edits, and then provide the Save-As dialog in response to any attempt to save.  

This design bug can easily create the illusion of a programming error, when NPP doesn't respond to keystrokes in the document.

### Steps to Reproduce the Issue

1. Create a text.txt document and set the read-only attribute. (e.g. in Win-7 SP1 Pro, x64, using Windows Explorer)
2. Open it in NPP
3. Attempt to type into that document.
4. Attempt to save that document, with control-S
5. Look for indications that explain why nothing happens.

### Expected Behavior

3.  When I edit a read-only file, I expect to see the edits appear.  
4.  When I "Save" a read-only file, I expect the Save-As dialog & UX.
5.  When I open a read-only file, I expect text in the title bar:  "Read Only".
MS-Office does all the above.  OG-Notepad does the first two.

### Actual Behavior

3. Keystrokes are ignored
4. Ctrl-S gives no response
5. There's a differently-colored icon, which is not explained (e.g. by redundant-but-helpful text that mentions "read only", anywhere)

Users who are unaware that they've opened a read-only file will be mystified, and are likely to imagine that they've found a programming bug.

**Comment by MetaChuh** [comment]
@netpog 

please choose `save as` for a read only file before editing.
this behaviour is by design, to prevent editing, and only noticing that it can't be saved to the original location, at the end.

thank you for your help and best regards.

-----
```
general notes:

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
(no extra account is needed, just use your github account to sign in)
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)
