### ISSUE TITLE
Language detection from simple session file w/o lang property is broken

### ISSUE THREAD

**Issue by andry81** [notepad-plus-plus/notepad-plus-plus#5338]
### Description of the Issue
If try to open a generated session file like this:
```
<?xml version="1.0" encoding="utf-8"?>
<NotepadPlus>
    <Session>
        <mainView>
            <File filename="&#xXXXX;..." />
        </mainView>
    </Session>
</NotepadPlus>
```
The editor does no more detect the language. If try to save the session, the lang field will contain a value "Simple Text" but in localized text version.
Was working in 7.6.1, broken in 7.6.3.

### Steps to Reproduce the Issue
1. Create manually a session file above
2. Load it
3. Observe uncolored text in opened files because of undetected language

### Expected Behavior
Language autodetect w/o `lang` field property in a session file

### Actual Behavior
Language detection disappear

**Comment by MetaChuh** [comment]
i can not reproduce this language detection problem using  simplified session files on version 7.6.6.

please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html).
if your issue still persists, and it is still of relevance to you, please feel free to file a new issue as easy to understand and reproducible as possible.

thank you for your help and best regards.

-----
```
general notes:

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
(no extra account is needed, just use your github account to sign in)
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)

**Comment by andry81** [comment]
I still can repro in 7.6.6 x86 in Windows 7 x64:

Save into the root of the `d:` drive these files:

*111.bat*

```
@echo off

setlocal

set a=1
```

*111.xml*

```
<?xml version="1.0" encoding="utf-8"?>
<NotepadPlus>
    <Session>
        <mainView>
            <File filename="d:\111.bat" />
        </mainView>
    </Session>
</NotepadPlus>
```

Oen the notepad++ session from the `111.xml`.
Observe an uncolored text.

**Comment by andry81** [comment]
I can repro this in 8.6.1 x64 in Windows 8 x64.
