### ISSUE TITLE
It is not obvious how to remove Alt+H (Hide Lines)

### ISSUE THREAD

**Issue by tilkinsc** [notepad-plus-plus/notepad-plus-plus#5343]
I can't seem to remove Alt+H (Hide Lines) via shift alt + H or any other combo. Nothing under the view menu specifies how to undo this. I must restart the program.

The hidden lines should go away.

**Comment by sasumner** [comment]
You remove them by clicking on the arrows that are placed in the margins by the hiding operation.  

Unfortunately, when using the hidden lines feature you will not get very far into it before realizing how bad it is (IMO)--it needs work to be usable.

**Comment by tilkinsc** [comment]
![image](https://user-images.githubusercontent.com/7494772/53345678-74cf8700-38e3-11e9-828d-65b60c5132ce.png)
What arrows?

**Comment by sasumner** [comment]
![image](https://user-images.githubusercontent.com/30118311/53345928-faebcd80-38e3-11e9-844a-03ab973ad03d.png)

Even more evidence for the hide-lines feature being "unfinished":  Arrows are not visible in a dark theme?

**Comment by tilkinsc** [comment]
Confirmed.

**Comment by tilkinsc** [comment]
Why was this closed? It was fixed?

**Comment by sasumner** [comment]
I think for it to be "fixed" there would have to be more work put into the entire feature, sadly.

**Comment by alankilborn** [comment]
>Arrows are not visible in a dark theme?

No, that's not it.

The reason that @tilkinsc didn't see the green arrows in the screenshot [HERE](https://github.com/notepad-plus-plus/notepad-plus-plus/issues/5343#issuecomment-467041206) was that the bookmark margin wasn't enabled in the preferences (and the hide lines feature and the bookmark feature share the same margin).

**Comment by tilkinsc** [comment]
This was before the darkmode theme was created.

**Comment by alankilborn** [comment]
@tilkinsc You must have been using a dark theme back then anyway (e.g. obsidian) to have achieved your prior screenshot.  You no longer have the issue because you have turned on the _Bookmark_ margin here (in 8.4.1) since the screenshot was made:

![image](https://user-images.githubusercontent.com/77065706/170822593-7cb613d6-e5b6-4f64-b4c6-4186d9ee9a07.png)

**Comment by tilkinsc** [comment]
I've done no such changes from what I remember. I used the default mode with customer coloration. Issue is closed.
