### ISSUE TITLE
Error message seen if launched from command line

### ISSUE THREAD

**Issue by masberg** [notepad-plus-plus/notepad-plus-plus#5345]
Hi, this is mostly a cosmetic issue. I use Cygwin a lot at work and I often launch Notepad++ from the Cygwin shell and for the last couple of versions I can see this error printed in the console when I launch it:

$ error: C:\Users\masberg\AppData\Roaming\Notepad++\plugins\Config\Hunspell\en_US.usr: cannot open

I believe the issue can be reproduced in any shell. I am using the 64-bit version of Notepad++ under Windows 10. Default installation, no localizations.

**Comment by sasumner** [comment]
That comes from a spell checker plugin.  Disable it?

**Comment by SinghRajenM** [comment]
@MetaChuh This is coming from plugin (spell checker)....

**Comment by MetaChuh** [comment]
@masberg 
please remove the DSpellCheck plugin as this is caused by this plugin.

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
(no extra account is needed, just use your github account to sign in)
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)

**Comment by PhilipOakley** [comment]
Fuller description, with workarounds, at https://github.com/notepad-plus-plus/notepad-plus-plus/issues/5301
