### ISSUE TITLE
Dupplicated quote

### ISSUE THREAD

**Issue by Xwilarg** [notepad-plus-plus/notepad-plus-plus#5346]
Hi,
I noticed that in https://github.com/notepad-plus-plus/notepad-plus-plus/blob/3546268c235780a6ba15266e7685aab7f6d6ce7f/PowerEditor/src/Notepad_plus.cpp the quote Anonymous 105 (line 6255) is the same as the quote Anonymous 151 (line 6301)

**Comment by donho** [comment]
https://github.com/notepad-plus-plus/notepad-plus-plus/commit/1af4d0f7f4b50b016e47b31fc9264f389045445b
