### ISSUE TITLE
Plugin Manager Missing

### ISSUE THREAD

**Issue by cyberwani** [notepad-plus-plus/notepad-plus-plus#5347]
### Description of the Issue
When installing plugin with built-in Plugin Manager, and when it restarts after installing plugin, Plugin Manager gets disappeared.

### Steps to Reproduce the Issue
1. Install new N++.
2. Install plugin.
3. After restart, there is no Plugin Manager in plugins menu.

**Comment by donho** [comment]
https://notepad-plus-plus.org/community/topic/16996/new-plugins-home-round-2
