### ISSUE TITLE
Copy and paste on multiple lines block instead on single lines

### ISSUE THREAD

**Issue by Sivanime** [notepad-plus-plus/notepad-plus-plus#5348]
In the editor 1, I have :

```
A
B
C
```
In the editor 2, I have :

```
1
2
3
4
5
6
7
```
When I try copy and paste on multiple lines from editor 1 to 2, the result is :

```
1A
B
C
2A
B
C
3A
B
C
4A
B
C
5A
B
C
6A
B
C
7A
B
C
```

Instead of :

```
1A
2B
3C
4A
5B
6C
7A
```
This feature works well on PhpStorm (IDE).

**Comment by sasumner** [comment]
It works OK for me to get your "instead of" result.  How EXACTLY are you doing what you are doing?

**Comment by Sivanime** [comment]
Hi,

If you keep pressing on 'ALT' button, then selecting with the mouse on the end of 7 lines (containing number 1,2 ... 7) and paste the result 

![image](https://user-images.githubusercontent.com/20860188/53740587-d324d880-3e94-11e9-9ce6-1c93c90fb32a.png)

**Comment by sasumner** [comment]
Sorry, makes no sense to me.  I can't help further.  Anyone else?

**Comment by Faq** [comment]
He means, that now is acting like this:
![n](https://user-images.githubusercontent.com/322016/54075222-89c5f600-42a5-11e9-96fa-533909b9b1de.gif)

Instead of :
```
1A
2B
3C
4A
5B
6C
7A

```

**Comment by MetaChuh** [comment]
@Sivanime 

you have **copied** the multiline content from your "a,b,c" example **including line feeds**.

* please press and hold [alt] **before** selecting your a,b,c example lines vertically.
* then press [ctrl]+[c] to copy the content to your clipboard.
* go to your "1,2,3" example tab.
* place your cursor after the number 1
**note: you don't need to [alt] select at your "paste" target, it is only required at the "copy" source.**
* press [ctrl]+[v] to insert your multiline text.

if you've done everything correctly, the result will be this:

```
1A
2B
3C
4
5
6
7
```

**additional note:** 
if you need to fill up the rest of the lines, repeat the multiline paste, by putting the cursor behind number 4, then press [ctrl]+[v] again, etc.

**Comment by Sivanime** [comment]
Yes it works indeed. But as you noticed :

> if you need to fill up the rest of the lines, repeat the multiline paste, by putting the cursor behind number 4, then press [ctrl]+[v] again, etc.

Some IDE like PhpStorm permit that multi-line paste. Thanks.
