### ISSUE TITLE
Macro submenus feature request

### ISSUE THREAD

**Issue by s9901470** [notepad-plus-plus/notepad-plus-plus#5349]
I have many macros and would like to be able to organise them into sub-menus, rather than scrolling through a single long list. Could this be added to a future version please?

**Comment by sasumner** [comment]
I think one-level of submenuing is a great idea, given my own person trouble here:  https://github.com/notepad-plus-plus/notepad-plus-plus/issues/8401#issuecomment-642316068

Perhaps this could be implemented on a manual basis, something like how the right-click context menu is customized.  It could even use the same `FolderName=` type of syntax.
