### ISSUE TITLE
Syntax highlighting failing for DIRECTORY_SEPARATOR variable

### ISSUE THREAD

**Issue by netinial** [notepad-plus-plus/notepad-plus-plus#5351]
### Description of the Issue
Syntax highlighting failing for DIRECTORY_SEPARATOR variable if there is a "." (dot) at the end.

works good
'text'. DIRECTORY_SEPARATOR . 'text' 
'text' .DIRECTORY_SEPARATOR . 'text'
does not work
'text'. DIRECTORY_SEPARATOR. 'text'

### Steps to Reproduce the Issue

1.  Create new test.php file 
2. Paste following code to the test.php
'text'. DIRECTORY_SEPARATOR . 'text' 
'text' .DIRECTORY_SEPARATOR . 'text'
'text'. DIRECTORY_SEPARATOR. 'text'
3. Open with notepad++
4. You will see that 3rd line DIRECTORY_SEPERATOR is not blue.

**Comment by MetaChuh** [comment]
@netinial 

this is a limitation of the currently implemented scintilla component.
unfortunately we can not fix this lexer glitch at the notepad++ part at the moment.
we apologise for that.

thank you for your help and best regards.

-----
```
general notes:

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
(no extra account is needed, just use your github account to sign in)
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)
