### ISSUE TITLE
High CPU when I Type

### ISSUE THREAD

**Issue by trollmad3** [notepad-plus-plus/notepad-plus-plus#5352]
I have no idea why this started but now whenever I type on notepad++ the CPU goes very high.

Video: [https://streamable.com/210ig](https://streamable.com/210ig)

**Comment by Faq** [comment]
@trollmad3  what the point of your report here as you didnt provide any debug info.
Any report who deletes issue template should be closed asap.

**Comment by trollmad3** [comment]
@Faq 
```
Notepad++ v7.6.3   (64-bit)
Build time : Jan 27 2019 - 17:16:47
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10 (64-bit)
Plugins : DSpellCheck.dll mimeTools.dll NppConverter.dll 
```

**Comment by MetaChuh** [comment]
we can not reproduce a high cpu load when typing on notepad++ 7.6.6.

please check if removing the dspellcheck plugin solves this for you.

please also update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html).

thank you for your help and best regards.

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
(no extra account is needed, just use your github account to sign in)
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)
