### ISSUE TITLE
write 0xffffffff, display with HEX-Editor and TextF is error

### ISSUE THREAD

**Issue by changtj** [notepad-plus-plus/notepad-plus-plus#5353]
### Description of the Issue

write 0xffffffff, display with HEX-Editor and TextF is error.

i wite twice
fstream: shared_ptr value.
long lt = 0xffffffff;
fstream->write((char*)&lt, sizeof(lt));
fstream->write((char*)&lt, sizeof(lt));
fstream->flush();

HEX-Editor( TextF)display
c3 bf c3 bf c3 bf c3 bf c3 bf c3 bf c3 bf c3 bf  

UltraEdit and HxD display 
FF FF FF FF FF FF FF FF

### Steps to Reproduce the Issue

1. 
2. 
3. 

### Debug Information

![default](https://user-images.githubusercontent.com/4907258/53536392-37683500-3b41-11e9-8954-9ec1f525377c.png)

![default](https://user-images.githubusercontent.com/4907258/53536429-55359a00-3b41-11e9-9fe3-6ec5f42337cc.png)

the file

![文件](https://user-images.githubusercontent.com/4907258/53536650-1ce28b80-3b42-11e9-934b-e9ce9dad6272.jpg)

**Comment by sasumner** [comment]
This isn't a place to report bugs in HexEditor. Please find where that plugin is supported and move your issue there. Please close this one. (This area is only for issues relating to what gets installed with a "clean" install of Notepad++, and HexEditor plugin is not part of that).

**Comment by changtj** [comment]
> This isn't a place to report bugs in HexEditor. Please find where that plugin is supported and move your issue there. Please close this one. (This area is only for issues relating to what gets installed with a "clean" install of Notepad++, and HexEditor plugin is not part of that).

i am sorry.
thus,  is there othen plugin for hex display correctly?

**Comment by chcg** [comment]
@changtj See https://sourceforge.net/projects/npp-plugins/files/Hex%20Editor/ and the ticket tab there. But as the hexeditor seems to be not actively maintained you may want to edit a issue at https://github.com/chcg/NPP_HexEdit
