### ISSUE TITLE
[7.6.3] custom backup dir setting - not working at all

### ISSUE THREAD

**Issue by zdroju** [notepad-plus-plus/notepad-plus-plus#5354]
### Description of the Issue

I set new custom backup dir but all the new files are still being written to old backup path

### Steps to Reproduce the Issue

1.  Setting --> Preferences --> Backup-->Backup on save -->[x] Custom backup Directory
2. enter the path

### Expected Behavior

all new files (temp files) should be created in Custom backup Directory instead of old backup path 

### Actual Behavior

Backup dir (new files) are still written in directory from settings --> Session Snaphot and Periodic Backup --> Backup path
moreover this Backup path is not editable at all

### Debug Information

Notepad++ v7.6.3   (64-bit)
Build time : Jan 27 2019 - 17:16:47
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10 (64-bit)
Plugins : DSpellCheck.dll mimeTools.dll NppConverter.dll 
![npp_error](https://user-images.githubusercontent.com/48085624/53554328-c6744d80-3b3f-11e9-8d5e-927a6b7f6bf0.jpg)

**Comment by MetaChuh** [comment]
@zdroju 

the "backup on save" has a completely different function than the "session snapshot".

the session snapshot folder, is the folder where unsaved files are stored.
the path is fixed to either `%AppData%\Notepad++\backup\` on an installed notepad++, or `your_path_to\npp.7.6.3.bin.x64\backup` on a portable version.

the path you have specified at "backup on save" on the other hand, will do exactly that: it will **backup on save** and only that.
as soon as you save a file, and have backup on save enabled, notepad++ will backup the previous version of this file to your specified backup folder, so you will be able to revert to the previous version, if you encounter any bugs after editing and saving.

the verbose backup will keep **all** previous versions, as soon as you hit save, at your specified custom backup directory location.
(or, if you do not specify a custom backup directory, the versioned backups will be at the original file's location, inside a folder called nppBackup.)
this will allow you to have a look at (or revert to) any previous version of this file.
(the oldest available version will begin at the moment you enable verbose backup and will continue to backup on save, as long as you keep verbose backup enabled)

**Comment by zdroju** [comment]
Thank you for your explanation. Ok. So .... is there any chance for you to ALLOW to edit this "session snapshot folder" setting ??? if not by key/choose directory dialog, then maybe by editing some ini/xml file or some keys in windows registry ??? I am asking about this because for me it looks like hardcoded ( I didn't find any setting ), but I want to change this dir setting to have all the files in two directories that are backuped two times a day :)

**Comment by MetaChuh** [comment]
@zdroju 

> is there any chance for you to ALLOW to edit this "session snapshot folder" setting ???

yes, you can change the snapshot folder from within the "cloud" option at the preferences:
* first, use windows explorer to create an empty folder at any location where you want your snapshots and periodic backups to be written to.
(**important**: it's recommended to use a local drive location only, as a network drive that is offline for just less than one second can lead to session data loss)
* go to `settings > preferences > cloud`, select `set your cloud location path here` and browse to the folder you have created, as seen at the screenshot below:

![Imgur](https://i.imgur.com/xAXO1OS.png)

* now restart notepad++ and go to `settings > preferences > backup` and you will see that the session snapshot backup path has been set to a backup folder inside your custom path, which you have set as "cloud" path.
from now on, all your snapshots and periodic session backups will reside there. (see screenshot below)

![Imgur](https://i.imgur.com/UbnkPQ0.png)

* **note:** this custom folder (cloud folder) will also contain all your settings, custom context menus and custom shortcuts/run menu entries, so those will also be saved twice a day on your machine.

hope this helps.

please don't forget to close this issue, if you are satisfied with the result, to help keeping the notepad++ issue list clean.
