### ISSUE TITLE
Spelling mistake in nppSetup.nsi

### ISSUE THREAD

**Issue by JL2210** [notepad-plus-plus/notepad-plus-plus#5358]
https://github.com/notepad-plus-plus/notepad-plus-plus/blob/1dfa92c4b7e3f4acb26fe6dbfb632618c7a21d43/PowerEditor/installer/nppSetup.nsi#L279

You forgot a leading period.

**Comment by MetaChuh** [comment]
@JL2210 

> You forgot a leading period.

a leading period would be:
`".The best things in life are free`

a closing period would be:
`So Notepad++ is the best."`

a periodic inconsistency would be:
`Th.e b.es.t thin.gs in li.fe are f.ree` 😉

would you like to close this issue, or do you really take this missing dot as a serious matter ?

**Comment by JL2210** [comment]
Sorry, I meant closing period. I could go for periodic inconsistency,
though.

**Comment by SinghRajenM** [comment]
@MetaChuh I feel it also can be closed.

**Comment by JL2210** [comment]
Could you please fix the typo? If it's already been fixed, feel free to
close this.

**Comment by MetaChuh** [comment]
@JL2210 

unfortunately the closing period pr commit got rejected at #5403, so i have to close this literarily without a period

my apologies
