### ISSUE TITLE
Extend keyboard shortcut for FoldAll / UnfoldAll to numpad zero

### ISSUE THREAD

**Issue by henrygab** [notepad-plus-plus/notepad-plus-plus#5363]
### Description of the Issue
Code folding keyboard shortcuts don't support numpad digits.

### Steps to Reproduce the Issue
1. Open a file that supports code folding (such as the .CPP file in commit) in notepad++
2. Choose menu option "View"
3. Note "Fold All" has keyboard shortcut Alt-0 (zero, not letter)
4. Note "Unfold All" has keyboard shortcut Shift-Alt-0 (zero, not letter)
5. Hit ESC to close menu options
6. Press Alt-0 using number pad
7. Press Shift-Alt-0 using number pad

### Expected Behavior
Number pad digit 0 can be used for this shortcut.

### Actual Behavior
Nothing happens.

### Debug Information
Notepad++ v7.5.9   (32-bit)
Build time : Oct 14 2018 - 15:02:52
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10 (64-bit)
Plugins : NppExport.dll DSpellCheck.dll mimeTools.dll NppConverter.dll NppEditorConfig.dll NppFTP.dll PluginManager.dll XMLTools.dll 

#### Cause
Only the "normal" digit 0 key (above letters o and p on US QWERTY) appear to be supported.
The digit 0 key on the number pad is considered a different key from the normal digit 0 key.
#### Pros
End users (who are not PC coders) will fail to recognize there is a difference between keyboard shortcuts needing the number pad digit keys, vs. keyboard shortcuts needing standard digit keys.  Adding this shortcut will reduce user frustration.
#### Cons
Unfortunately, there are five existing shortcuts that would result in a conflict if globally desiring to treat the numpad digit keys the same as the normal digit keys:

- [`CTRL-VK_[1..5]` as `IDM_SEARCH_GONEXTMARKER[1..5]`](https://github.com/notepad-plus-plus/notepad-plus-plus/blob/master/PowerEditor/src/Parameters.cpp#L213-L217)
- [`CTRL-VK_NUMPAD[1..5]` as `IDM_VIEW_TAB[1..5]`]( https://github.com/notepad-plus-plus/notepad-plus-plus/blob/master/PowerEditor/src/Parameters.cpp#L248-L252)

#### Fix
The fix, if the issue is approved, would be trivial:
See https://github.com/notepad-plus-plus/notepad-plus-plus/commit/fb25f0407e158fc1440575093bed5533b769d9fb

Simply add two mappings for ALT-VK_NUMPAD0 and SHIFT-ALT-VK_NUMPAD0.

**Comment by victorel-petrovich** [comment]
> Code folding keyboard shortcuts don't support numpad digits.
Have you tried defining your own new shortcut `Alt + Numpad 0` with the Shortcut Mapper in Settings ?

**Comment by alankilborn** [comment]
>The digit 0 key on the number pad is considered a different key from the normal digit 0 key.

Yes, and this is obviously by design, as both types of zero are distinctly currently supported in the _Shortcut Mapper_.
