### ISSUE TITLE
shortcut mapper conflict doesn't display right when filtered

### ISSUE THREAD

**Issue by pryrt** [notepad-plus-plus/notepad-plus-plus#5374]
### Description of the Issue

When the shortcut mapper view is filtered, it doesn't display a keystroke conflict correctly.  (See [this Community post](https://notepad-plus-plus.org/community/topic/17222/nppexec-f6-not-working/5) for context)

### Steps to Reproduce the Issue

1. Have a conflict with one of the plugin shortcuts.  In my example, both **Main Menu [3]: `Explorer`** and **Plugin Commands: NppExec.dll `Execute...`** were mapped to `F6`
2. In Shortcut Mapper, on the Plugin commands tab, scroll normally to `Execute...` and see it's red, and the message box shows `Main menu  |  3   Explorer  ( F6 )`.  This is expected behavior.  ![](https://i.imgur.com/UTuH3yK.png)
3. Filter by `Execute`, then click on one of the others (like "save all files on execute") then back on the red-highligted `Execute...` row: the message box now shows `No shortcut conflicts for this item.`, even though there is still a conflict, and it's properly highlighted red. ![](https://i.imgur.com/fr8jB0W.png)

### Expected Behavior

Showing `Main menu  |  3   Explorer  ( F6 )` whether the filter is applied or not

### Actual Behavior

Correctly shows `Main menu  |  3   Explorer  ( F6 )` when no filter applied, but claims `No shortcut conflicts for this item.` when there is a filter applied

### Debug Information

```
Notepad++ v7.6.3   (64-bit)
Build time : Jan 27 2019 - 17:16:47
Path : C:\usr\local\apps\notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : ON
OS : Windows 10 (64-bit)
Plugins : ComparePlugin.dll DSpellCheck.dll MarkdownViewerPlusPlus.dll mimeTools.dll NppConverter.dll NppExec.dll NppFTP.dll PythonScript.dll XMLTools.dll 
```

**Comment by jmbockhorst** [comment]
I can confirm that this is a bug that I was able to reproduce.

**Comment by Faq** [comment]
@jmbockhorst on what version?

**Comment by jmbockhorst** [comment]
@Faq v7.6.4
I have identified the problem and am working on a fix.

**Comment by pryrt** [comment]
Confirmed: in v7.6.6, conflicts properly show up, even when filtered.  Thanks!

**Comment by pryrt** [comment]
Per https://community.notepad-plus-plus.org/post/64528, this problem may have come back.  My experiments seem to show this problem with v7.9.5.  I will try to find some time later today to confirm in other versions (including making sure it was really gone in v7.6.6, because #5453 never seems to have been accepted, so I'm not sure how v7.6.6 was able to fix it -- it may have been that I ran the experiment wrong in v7.6.6, because my v7.9.5 experiments show it only happens if the filtered number doesn't match the unfiltered number), and maybe even bisect to determine which version number started the regression.  Once I have more data, I will decide whether to re-open this issue or not.

**Comment by pryrt** [comment]
I have confirmed: it was **not** fixed in v7.6.6 like I originally said.  My experiment two years ago must have been mistaken.
```
Notepad++ v7.6.6   (64-bit)
Build time : Apr  3 2019 - 23:52:32
Path : C:\usr\local\apps\npp\npp.7.6.6.bin.x64\notepad++.exe
Admin mode : OFF
Local Conf mode : ON
OS : Windows 10 (64-bit)
Plugins : mimeTools.dll NppConverter.dll 
```

Procedure: 
1. Fresh unzip of v7.6.6-64bit portable
2. Settings > Shortcut Mapper
3. Filter = `new`
4. Set `Move to New Instance` to `Ctrl+E`: says no conflicts: 
![image](https://user-images.githubusercontent.com/17455758/113158435-a2890780-91f0-11eb-9798-da07247d06cb.png)
5. click **OK** and still shows no conflicts
6. click **Modify** and it shows conflicts with itself at `Main Menu | 153 Move to New Instance (Ctrl+E)`:
![image](https://user-images.githubusercontent.com/17455758/113158674-d82df080-91f0-11eb-84ab-6ca64d5dec66.png)
7. click **OK** to get out of the Modify dialog, and it's back to not listing any conflicts.
8. remove the filter, scroll down to row 153 `Move to New Instance (Ctrl+E)`, which still says no conflict.
9. **modify** when it's at row 153, and it correctly shows conflict: 
![image](https://user-images.githubusercontent.com/17455758/113159294-5be7dd00-91f1-11eb-9297-196949fe0976.png)

So step 6 incorrectly shows a conflict with itself.  

If I switch to a fresh unzip of v7.9.5-64 portable, it gives the same results (except the conflict is with row 167, because there are more menu entries in v7.9.5):
![image](https://user-images.githubusercontent.com/17455758/113159823-c436be80-91f1-11eb-9cf3-15eeb9d11de9.png)
```
Notepad++ v7.9.5   (64-bit)
Build time : Mar 21 2021 - 02:13:17
Path : C:\usr\local\apps\npp\npp.7.9.5.portable.x64\notepad++.exe
Admin mode : OFF
Local Conf mode : ON
OS Name : Windows 10 Enterprise (64-bit) 
OS Version : 1903
OS Build : 18362.1256
Current ANSI codepage : 1252
Plugins : mimeTools.dll NppConverter.dll NppExport.dll 
```

I don't know if @jmbockhorst's fix #5453 will still work for this issue.  But the issue still exists, and was reported "in the wild" in https://community.notepad-plus-plus.org/topic/20967/macro-ignores-python-script-erratic-shortcut-mapper (the "erratic shortcut mapper" portion of that discussion)

**Comment by pryrt** [comment]
In my experiments, if you happen to pick a shortcut mapper entry that stays in the same place whether or not it's filtered... like by going to the **Plugin commands** tab, and setting `4 Base64 Encode by line` to `Ctrl+E`, it won't show up, even when you filter by `encode` or `mime`.  My assumption is because the row-number stays the same at 4, whether it's filtered or not.  If I change the filter to `line`, so it now shows as line 1 when filtered, clicking **Modify** will show the conflict, as described at step#6 above.

(My guess is that this is what happened when I "confirmed" that 7.6.6 fixed it two years ago -- I probably filtered by something that left the row-number the same for the entry I was trying.)

**Comment by pryrt** [comment]
@donho,

There were two related problems in the filtered view
1. When there was a real conflict (as shown with the `F6` example at the [top](https://github.com/notepad-plus-plus/notepad-plus-plus/issues/5374#issue-416884412)), it wouldn't show the conflict that was there.
2. When there is really no conflict, but you are editing the shortcut that you just created while filtered (like the `Ctrl+E` [example](https://github.com/notepad-plus-plus/notepad-plus-plus/issues/5374#issuecomment-811109261)), it would show a conflict in the smaller dialog, even though there isn't a real conflict.

When I saw this issue was closed, I downloaded "current-build" version of Notepad++.x64.Debug.exe from https://ci.appveyor.com/project/donho/notepad-plus-plus/build/job/70kdie3kiajbw2fu/artifacts to verify that it worked right:

	Notepad++ v8.1.2   (64-bit)
	Build time : Aug  3 2021 - 11:41:09
	Path : C:\usr\local\apps\npp\npp.8.1.2.portable.x64\Notepad++.x64.Debug.exe
	Command Line : 
	Admin mode : OFF
	Local Conf mode : ON
	Cloud Config : OFF
	OS Name : Windows 10 Enterprise (64-bit) 
	OS Version : 1903
	OS Build : 18362.1256
	Current ANSI codepage : 1252
	Plugins : mimeTools.dll NppConverter.dll NppExport.dll 

(I verified that the "current build" I linked to includes the commit 8a77b07 which was your commit referenced in #5374)

The "current build" fixed #1 (thank you!), but does _not_ fix #2 -- it still shows a conflict with itself.  

I recorded an animated screenshot to show the problem still exists:

![](https://i.imgur.com/B3hLb5W.gif)

* So if I am not filtered: 
    * I can create a new shortcut on 174 "Move to New Instance", with no conflict; 
    * when I come to the main list, it shows no conflict; 
    * when I edit that one again, it still shows no conflict.
* If I am filtered (by `new`): 
    * I can create a new shortcut on 2 "Move to New Instance", with no conflict;
    * when I come to the main list, it shows no conflict;
    * when I edit that one again, it shows "CONFLICT FOUND" in the small dialog box, and the outer dialog box shows the conflict with `Main menu | 174 Move to New Instance (Ctrl+E)` -- so it still shows a conflict with itself.

**Comment by donho** [comment]
@pryrt 
It should be fixed now in https://github.com/notepad-plus-plus/notepad-plus-plus/commit/14a104ad4691f99ebc6c99ab533686e0e5f0758f

**Comment by pryrt** [comment]
@donho,

Thanks, that fixed it.
