### ISSUE TITLE
Crash when searching and opening a file from context menu

### ISSUE THREAD

**Issue by fz0000** [notepad-plus-plus/notepad-plus-plus#5376]
### Description of the Issue
Similar to #3970 . But in step 2, just open the file from context menu instead of double clicking or dragging in.

### Steps to Reproduce the Issue

1. Use CTRL+SHIFT+F to search in files
2. While the search is processing, right click a file and select "Edit with Notepad++".

### Expected Behavior

File should open normally after the search is finished.
### Actual Behavior

Crash
### Debug Information

Notepad++ v7.6.3   (64-bit)
Build time : Jan 27 2019 - 17:16:47
Path : D:\Program Files\Notepad++\notepad++.exe
Admin mode : ON
Local Conf mode : ON
OS : Windows 7 (64-bit)
Plugins : ComparePlugin.dll DSpellCheck.dll HexEditor.dll JSMinNPP.dll mimeTools.dll NppConverter.dll NPPJSONViewer.dll PluginManager.dll XmlTools.dll

**Comment by SinghRajenM** [comment]
Again could not reproduce. 
Will you trying after disabling all the plugins?

**Comment by fz0000** [comment]
Oh... Yes this issue does not occur when all the plugins are disabled.
And after I re-install some available plugins from Plugins Admin, it doesn't crash, either.
It should be caused by the old plugin HexEditor.dll
Thanks a lot.

**Comment by fz0000** [comment]
don't want to take part in any political project. so delete my issue. sorry for any inconvenience.
