### ISSUE TITLE
Crash when typing (It's first error I met)

### ISSUE THREAD

**Issue by ChenYouRen** [notepad-plus-plus/notepad-plus-plus#5382]
![2019-03-06_094021](https://user-images.githubusercontent.com/26375712/53850888-bb199a00-3ff7-11e9-8349-0d24b1137fbb.png)
![2019-03-06_094106](https://user-images.githubusercontent.com/26375712/53850899-c1a81180-3ff7-11e9-8bd8-c814c9a4c387.png)

![2019-03-06_094824](https://user-images.githubusercontent.com/26375712/53850908-c66cc580-3ff7-11e9-8f1d-0d8eaf7aa989.png)
Version: v7.6 (64bit)

Your email "don.h@free.fr": 
> 550 spam detected

by gmail

Is my email spam ?

**Comment by Faq** [comment]
@ChenYouRen add debug info from menu ?->Debug info...

**Comment by MetaChuh** [comment]
we can not reproduce your crash issue on notepad++ 7.6.6 with the given information.

please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins if you update from version 7.5.9 or below.
if your issue still persists, and it is still of relevance to you, please feel free to file a new issue as easy to understand and reproducible as possible.

thank you for your help and best regards.

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
(no extra account is needed, just use your github account to sign in)
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)
