### ISSUE TITLE
XML Highlihgt bug

### ISSUE THREAD

**Issue by lmerega** [notepad-plus-plus/notepad-plus-plus#5384]
Hi all, XML highlight syntax is not case sensitive while XML language is.
Is it possibile to correct?
![hlkmjjhcwc](https://user-images.githubusercontent.com/8739142/53876094-587bca80-4006-11e9-81bc-ac735095d6df.png)

**Comment by donho** [comment]
Unfortunately, it depends on Scintilla component.
