### ISSUE TITLE
Menu and tabs flicker when Windows enables/disables Night Light

### ISSUE THREAD

**Issue by jawilkins** [notepad-plus-plus/notepad-plus-plus#5385]
### Description of the Issue

There is a noticable amount of redrawing/flickering when the Night Light feature of Windows 10 is turned on or off (which may be manually or on a timer).

It seems to flicker once for each step of the animation, which is like once a second for 30-60 seconds.

I am not sure if it is because I have a lot of tabs open (over 100 atm).

### Steps to Reproduce the Issue

1. Might need to open a lot of tabs. Might depend on CPU/GPU speed.
2. Enable or disable Night Light (can be found at the bottom of the notification area)

### Expected Behavior
No flicker at all. The colors are changing, but I believe this is done by the Compositing Window Manager, not by redrawing the screen. It seems like Notepad++ is responding to some even by redrawing. It could mitigate this by not clearing the background before drawing, not drawing in multiple steps, or just not being so aggressive about redrawing.

### Actual Behavior
Visible flickering once a second as the Night Light feature turns on or off.

**Comment by Faq** [comment]
@jawilkins You forgot to add debug info.

**Comment by jawilkins** [comment]
Notepad++ v7.5.9   (32-bit)
Build time : Oct 14 2018 - 15:02:52
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10 (64-bit)
Plugins : DSpellCheck.dll mimeTools.dll NppConverter.dll NppExport.dll PluginManager.dll

**Comment by Faq** [comment]
1) those 100 tabs are saved or temp ones? How big are those files?
2) Did you tried to disable addons? Any changes?
3) If notepad is closed problem remains?
4) Why not use 64bit N++ on 64bit w10? Also wondering if the same will happen with v7.6.4

**Comment by jawilkins** [comment]
Happens with just a new file open. The menu flickers too, not just the tabs.
As far as I know, I do not have any add-ons enabled. Is there a way to make sure?
Do you mean if I restart notepad? Yeah, it isn't a problem that goes away if I restart notepad.
I upgraded now. Not sure why I grabbed the 32-bit version. The flickering persists.

Notepad++ v7.6.4   (64-bit)
Build time : Mar  6 2019 - 02:58:24
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10 (64-bit)
Plugins : mimeTools.dll NppConverter.dll

**Comment by jawilkins** [comment]
I figured out the plug-in situation. Problem remains when they are disabled.

Notepad++ v7.6.4   (64-bit)
Build time : Mar  6 2019 - 02:58:24
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10 (64-bit)
Plugins : none

**Comment by jawilkins** [comment]
Wanted to add that this flickering also occurs if you change the wallpaper background color.

It seems to be related to how Notepad++ handles the system metrics change message, although I think Microsoft is at fault for also sending so many when it does it's fancy fades.

I think I have written applications that respond to this message by invalidating all of the device contexts, so I should go back and see if they have a similar problem.
