### ISSUE TITLE
7.6.4 Customize Toolbar Won't Install

### ISSUE THREAD

**Issue by dave47** [notepad-plus-plus/notepad-plus-plus#5387]
Notepad 7.6.4
1. Customize Toolbar will not install
2. 
3.

**Comment by DavidHansen-0x454d43** [comment]
@dave47 
Are you installing manually or through the plugin manager? 
Do you see any error messages or pop-ups?
Where is your debug information? (Notepad++->Menu->?->Debug Info...)

**Comment by sasumner** [comment]
@DavidHansen-0x454d43 
Hopefully you meant "Plugin Admin" and not "Plugin Manager".

**Comment by DavidHansen-0x454d43** [comment]
@sasumner  Well...  _I'm_ still using Plugin Manager (on 7.5.9) . I might not be the only one. :/
I just feel like @dave47 didn't really give us enough information to do anything with this issue.

**Comment by sasumner** [comment]
@DavidHansen-0x454d43 : @dave47 said he was using 7.6.4 so I'm thinking proper references for that version should be "Admin" and not "Manager".  That's all I meant.  And yes, about all @dave47 gave us WAS the version number--thus I'm surprised anyone (you) even commented on it. :)

**Comment by DavidHansen-0x454d43** [comment]
@sasumner, I probably wouldn't have but the customize toolbar misbehaved for me this week causing me to remove it.  (it filled my toolbar up with non-responsive buttons)

My thinking was _maybe_ this issue is related and wanted to get more details from @dave47 about what he was seeing.

**Comment by sasumner** [comment]
@DavidHansen-0x454d43 , I guess you're not going to get those details... :)
