### ISSUE TITLE
Synchronize active line between two views 

### ISSUE THREAD

**Issue by iriman** [notepad-plus-plus/notepad-plus-plus#5388]
Hi, Is it possible to synchronize active line (=highlighted line) between two views? Any setting or plugin?
If no, could you please put it in your plan?

**Comment by Faq** [comment]
Something like this should be asked on forum first.

**Comment by iriman** [comment]
Sorry, I hadn't noticed to the website 'community'. I'll ask there.

**Comment by sasumner** [comment]
You shouldn't have closed this unless/until you get a satisfactory answer on the Community site.
