### ISSUE TITLE
The status bar does not adjust the individual segments to the (scaled) string size on HiDPI systems

### ISSUE THREAD

**Issue by l-c-g** [notepad-plus-plus/notepad-plus-plus#539]
When using a monitor with a higher DPI than the usual 96 DPI and Windows 8.1 scaling set to >100%, Notepad++ typically scales rather well.
The status bar segments for the line ending type and the encoding are too small, however, and the labels "Dos/Windows" and "UTF8 w/o BOM" are cut off, see the attached screenshot. Other status bar labels may be affected as well, I have only seen it for these two, though.
<img width="468" alt="notepadpp" src="https://cloud.githubusercontent.com/assets/13457399/8835994/3ffe1248-30be-11e5-9170-ed1e5dd61ca6.png">

**Comment by sky5walk** [comment]
How many times must I resubmit this BUG report?! It is still broken as of v6.9.2.
![bug_notepad v692_statusbar](https://cloud.githubusercontent.com/assets/13093122/17600908/a11f610e-5fd3-11e6-8d64-b01559acc23e.PNG)
[BUG_Notepad++v692_statusbar.txt](https://github.com/notepad-plus-plus/notepad-plus-plus/files/413971/BUG_Notepad.v692_statusbar.txt)

**Comment by donho** [comment]
Update your Notepad++ to v7.6.6.
If this bug persists in the new release, please open a new issue with the debug information.
