### ISSUE TITLE
7.6.4 regression: double-clicking on a "find all in current document" result for an unsaved doc prompts to save it

### ISSUE THREAD

**Issue by bughit** [notepad-plus-plus/notepad-plus-plus#5393]
### Description of the Issue
double-clicking on a "find all in current document" result for an unsaved doc prompts to save it

### Steps to Reproduce the Issue

1. start np++
2. enter some text into the empty new doc
3. "find all in current document" the entered text
4. double click on the first and only find result 

### Expected Behavior
no prompt to save the doc

### Actual Behavior
prompt to save the doc

### Debug Information

```
Notepad++ v7.6.4   (32-bit)
Build time : Mar  6 2019 - 02:52:22
Path : C:\tmp\npp.7.6.4.bin.minimalist\notepad++.exe
Admin mode : OFF
Local Conf mode : ON
OS : Windows 7 (64-bit)
Plugins : none
```

![image](https://user-images.githubusercontent.com/895588/53921561-d9ef4f00-403e-11e9-9456-ebff66f76aa3.png)

**Comment by bughit** [comment]
@donho Do you look at bug-reports here? Or only on on the forum?

**Comment by SinghRajenM** [comment]
@donho I suspect commit 011aa960fb2400526c61299d8df89876be329cec caused this issue. specially removing of below snippet in file NppIO.cpp. 

```C++
  size_t res = gs_fileName.find_first_of(UNTITLED_STR);

    if (res != string::npos && res == 0) // it can happen when a document named "new #", which is dragged from another instance, is dropped into this instance
    {
        // it's meaningless to show empty "new #" document, so just return null
		return nullptr;
    }
```

Now please note, we can't relay only on `UNTITLED_STR` as unsaved tab may contains any name (because of rename tab feature). So we need to figure out the alternative. Hope this will help.

**Comment by donho** [comment]
@SinghRajenM 
It is indeed. I've fixed locally and I will commit it this evening.
The modif (removal) is due to wrong judgement while reviewing the your commit for the new feature rename untitled tab. I take in charge of the fix/enhancement in this new feature.

**Comment by donho** [comment]
https://github.com/notepad-plus-plus/notepad-plus-plus/commit/6580255a2b6809a1fa951db44ec8be29698b8540

**Comment by bughit** [comment]
@donho this regressed again, present in 8.3.1
