### ISSUE TITLE
操 马勒戈壁 说好的备份呢？

### ISSUE THREAD

**Issue by 54huige** [notepad-plus-plus/notepad-plus-plus#5395]
一天写的代码就这么没了？说好的备份呢？崩溃后 就没这个文件的备份 打开后还让重载？你是傻逼吗？重载一个空文件是我想要的吗？你自己也不去判断一下  备份里有数据 结果自动重载的时候 你要重载一个空文件覆盖备份里的数据 不不不 你是删除了备份 放一个空文件 你是脑子有洞？哪个傻x写的重载功能 你要害死人 技术不是用来害人的 操 你自己没遇到过吗

**Comment by andry81** [comment]
Lets translate this mambo jambo work with google translate: [translate.google.com](url)

`Title`: Mare Gobi says good backup?
`Content`:
The code written in one day is gone? Say good backup? After the crash, there is no backup of this file. Is it still overloaded after opening? Are you stupid? Is overloading an empty file what I want? You don't have to judge yourself. There is data in the backup. When the result is automatically reloaded, you have to overload an empty file to overwrite the data in the backup. No, no, you deleted the backup. Put an empty file. Do you have a hole in your brain? Which stupid x writes the overload function? You want to kill the dead. Technology is not used to harm people. Have you ever encountered it?

**Comment by sasumner** [comment]
@andry81 I'm not sure that helped much! :)

**Comment by andry81** [comment]
It seems that the file was zeroed after a crash by your SSD itself because that fail was there for ages and nobody seems noticed it yet (i have had a couple of times the same fail).
DO NOT use SSD next time for edit an important work.

**Comment by sasumner** [comment]
@andry81 How does SSD come into it? (confused).

**Comment by andry81** [comment]
Many SSDs still does not have correct transacted save upon a crash. Files becomes zeroed before a save. If crash happens between a moment of last write then u lose everything.

**Comment by sasumner** [comment]
@andry81 It seems a bold claim. I use SSD all the time without problems. Do you have weblinks that illustrate the prevalence of this SSD problem?

**Comment by andry81** [comment]
It is your right to not believe but i have lost my work several times because of SSD fail.

**Comment by donho** [comment]
His/her windows or Notepad++ crashes then all the backup files have gone. The remain stuffs are expletive insulting words.
I've got user's report before for the same issue windows crash (or forced restart due to its update).
I'll see what I can do about it (backup's backup? damn backupinception).

**Comment by andry81** [comment]
> @andry81 It seems a bold claim. I use SSD all the time without problems. Do you have weblinks that illustrate the prevalence of this SSD problem?

You can find some related problem to this:
https://superuser.com/questions/1346590/files-disappeared-from-ssd-and-recovery-is-recovering-zero-filled-files

But i don't think you can find any better info than that.
