### ISSUE TITLE
Error when running a silent install

### ISSUE THREAD

**Issue by EvilGrinUK** [notepad-plus-plus/notepad-plus-plus#5396]
### Description of the Issue

When I try and uninstall I get a NSIS error.

### Steps to Reproduce the Issue

1. Install Notepad++ 
2. Attempt to uninstall Notepad++ via an elevated command line using the command 'uninstall /s'

### Expected Behavior

Notepad++ should be uninstalled.

### Actual Behavior

An error dialog stating 'Error launching installer' appears 

### Debug Information

![image](https://user-images.githubusercontent.com/2217729/54032420-77ff2880-41a9-11e9-9bb4-105e00ace6bf.png)

**Comment by SinghRajenM** [comment]
@EvilGrinUK give a try as `uninstall.exe /S`. Note: flag `/S` is capital. And provide debug info from "menu->?->Debug Info...".

**Comment by EvilGrinUK** [comment]
I tried `uninstall.exe /S` from an elevated command prompt. There was no error. However nothing was uninstalled.

![image](https://user-images.githubusercontent.com/2217729/54195951-ee589f00-44b7-11e9-8a3f-21fb3c2d2a4f.png)

Debug info is:

Notepad++ v7.6.4   (64-bit)
Build time : Mar  6 2019 - 02:58:24
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10 (64-bit)
Plugins : DSpellCheck.dll mimeTools.dll NppConverter.dll

**Comment by SinghRajenM** [comment]
@EvilGrinUK sorry, I could not reproduce.

![image](https://user-images.githubusercontent.com/14791461/54362874-c328a800-468f-11e9-91d5-21f074150f85.png)

**Comment by EvilGrinUK** [comment]
I found the issue. This is not Notepad++'s fault. The AppLocker settings on the machine were preventing the uninstaller writing to %TEMP%.
