### ISSUE TITLE
.*\n (regexp search) is non-greedy with CRLF (Windows EOL)

### ISSUE THREAD

**Issue by Dominik-K** [notepad-plus-plus/notepad-plus-plus#540]
Doing this regular expression search `.*\n` in a Windows text file with `CRLF` at the end of line does not highlight/find the text before CR & LF, as well. 
Is it just an Notepad++ bug (tested with version 6.8) or in the Boost library?

**Comment by dail8859** [comment]
I'd say its due to your regular expression. `.*` is allowed to match nothing. Even doing it lazily using `.*?` is allowed to match nothing. So you might need a bit more specific regular expression.

**Comment by tico-tico** [comment]
I think N++ treats `\r` (`CR`) as a line break character, therefore `.` won't match them. You want something like `.*\r\n` or `.*\R`

**Comment by Dominik-K** [comment]
Hmm, did you test it? For example:

    Hello world!CRLF

will indeed highlight `CR`, as well as `LF`, but not everything before. Compare with e.g. regex101.com.
Here's the important part from the [Boost library doc](http://www.boost.org/doc/libs/develop/libs/regex/doc/html/boost_regex/syntax/perl_syntax.html):

    The single character '.' when used outside of a character set will match any single character except:

    The NULL character when the flag match_not_dot_null is passed to the matching algorithms.
    The newline character when the flag match_not_dot_newline is passed to the matching algorithms.
   
Notepad++ [uses this library](http://docs.notepad-plus-plus.org/index.php/Regular_Expressions), right?

**Comment by dail8859** [comment]
You are correct. But as I said before `.*` means 0 or more characters...meaning it will match 0 characters. If you want the entire line you can use `^.*?\r\n` because it is forced to start at the beginning of the line.

**Comment by Dominik-K** [comment]
Oh, now there's a small hint implemented displaying `^ zero length match`. Nice :+1 So, the current behavior is like you, @dail8859, said.
BUT: That's neither the conventional behavior nor what's in the documentation:

[Notepad++ doc](http://docs.notepad-plus-plus.org/index.php/Regular_Expressions#Multiplying_operators):
"`*`  This matches 0 or more instances of the previous character, **as many as it can**."

[Boost C++ doc](http://www.boost.org/doc/libs/develop/libs/regex/doc/html/boost_regex/syntax/perl_syntax.html#boost_regex.syntax.perl_syntax.non_greedy_repeats):
"The normal repeat operators are "greedy", that is to say they will consume as much input as possible."

**Comment by dail8859** [comment]
Do you have `. matches newline` checked?

**Comment by MetaChuh** [comment]
we are closing this issue due to its age and multiple newer notepad++ versions since it was filed.

please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html).
if your issue persists, and it is still of relevance to you, please feel free to file a new issue.

thank you for your help and best regards.

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
```
[<kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd>](https://notepad-plus-plus.org/community/)
