### ISSUE TITLE
UDL: If a user defined language's name contains () brackets, like Markdown (Default), the language bullet will not be set correctly to that specific udl.

### ISSUE THREAD

**Issue by MetaChuh** [notepad-plus-plus/notepad-plus-plus#5400]
### Description of the Issue

if a user defined language contains () brackets in its name, for example `Markdown (Default)`, the language bullet will not be set correctly.

### Steps to Reproduce the Issue

1. open up any file.
2. go to the `language` menu and select `Markdown (Default)` or any other udl that has `()` brackets in it's name.
3. go to the `language` menu again and watch where the bullet, which defines the current language, is placed.

### Expected Behaviour

the language bullet is expected to be at the currently selected udl, e.g. `Markdown (Default)`.

### Actual Behaviour

the language bullet is shown at the `User-Defined` template udl, as shown at the screenshot below:

![Imgur](https://i.imgur.com/KcljFhS.png)

### Debug Information

Notepad++ v7.6.4   (32-bit)
Build time : Mar  6 2019 - 02:52:22
Path : C:\Users\User\Desktop\npp.7.6.4.bin\notepad++.exe
Admin mode : OFF
Local Conf mode : ON
OS : Windows 7 (64-bit)
Plugins : mimeTools.dll NppConverter.dll NppExport.dll 

**note**: this behaviour apparently dates back and applies to all older versions which have an udl editor.
i've only discovered this recently by coincidence, as the latest `Markdown (Default)` udl contains `()` brackets in its name, my apologies for that.

**additional note** this issue might also be related to https://github.com/notepad-plus-plus/notepad-plus-plus/issues/4714

predicted issue priority for the majority of users: low.
predicted issue priority for power users: low to medium.

**Comment by MetaChuh** [comment]
**update and more apologies**:

i have just retested issue https://github.com/notepad-plus-plus/notepad-plus-plus/issues/4714 , and the `Markdown (Default)` issue is **solely based on an udl name of 15 characters or more.**
the `()` brackets are not the cause, sorry about my premature assumption.

**Comment by bpersonick** [comment]
Hey Meta, I'm glad I was able to help you determine the root cause of your issue by having described mine and my testing of it.  Hopefully someone gives these a look. :)

**Comment by MetaChuh** [comment]
and i'm glad you write the way you do, so it was very easy to find, very easy to read and relate to the issue i've encountered while testing the deployment issues of the now distributed `Markdown (Default)` udl.

yes, hopefully someone gives these a look.
we might accept bets over at the notepad++ community whether ...
* udl name input field will be limited to 14 chars.
* udl name lenght limit will be corrected to use the full 21 chars everywhere.
* the included `Markdown (Default)` udl will be renamed to `Markdown` to make it shorter, the rest stays the same. 😉

greetings, metachuh

**Comment by bpersonick** [comment]
> and i'm glad you write the way you do, so it was very easy to find, very easy to read and relate to the issue i've encountered while testing the deployment issues of the now distributed `Markdown (Default)` udl.
> 
> yes, hopefully someone gives these a look.
> we might accept bets over at the notepad++ community whether ...
> 
> * udl name input field will be limited to 14 chars.
> * udl name lenght limit will be corrected to use the full 21 chars everywhere.
> * the included `Markdown (Default)` udl will be renamed to `Markdown` to make it shorter, the rest stays the same. wink
> 
> greetings, metachuh

Thank you @MetaChuh for the huge compliment on my writing! :)

Looks like they have fixed the issue now as more users are running into it. :)
