### ISSUE TITLE
File menu "Load Session..." and "Save Session..." are both "Save Session..."

### ISSUE THREAD

**Issue by C4rb0n** [notepad-plus-plus/notepad-plus-plus#5402]
### Description of the Issue
"Load Session..." option, under the File menu, does not actually load a saved session and instead performs the exact same function as the "Save Session..." option, thereby overwriting a saved session.

### Steps to Reproduce the Issue
1. Make sure you have two Windows accounts available for testing (Account1 and Account2).
2. In Account1: (where you sufficient Notepad++ session information, select "File" --> "Save Session..." and save the session file to a USB flash drive 
3. In account1: also copy any files in the Notepad++ backup path to the USB flash drive
4. In Account2: first make sure you are OK with losing your Notepad++ session and backup files
5. In Account2: copy the Notepad++ backup files from Account1 to your Account2 backup path
6. In Account2: (where the Notepad++ session is significantly different, or nonexistent, from that of Account1), select "File" --> "Load Session..." and choose the session file from Step 2 to load.
7. Notice that Account1 session did not get loaded.
8. Notice also that the Account1 session file on the USB flash drive got overwritten with the Account2 session.

### Expected Behavior
"Load Session..." should perform as the name suggests and should not be performing the same operation as "Save Session..."

### Actual Behavior
"Load Session..." behaves exactly the same as "Save Session..."

### Debug Information
Notepad++ v7.6.4   (32-bit)
Build time : Mar  6 2019 - 02:52:22
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10 (64-bit)
Plugins : DSpellCheck.dll mimeTools.dll NppConverter.dll NppExport.dll

**Comment by MetaChuh** [comment]
i can not reproduce this on notepad++ 7.6.6

please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins if you update from version 7.5.9 or below.
if your issue still persists, and it is still of relevance to you, please feel free to file a new issue as easy to understand and reproducible as possible.

thank you for your help and best regards.

-----
```
general notes:

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
(no extra account is needed, just use your github account to sign in)
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)
