### ISSUE TITLE
[Request]: Open UDL Language(s) Folder...

### ISSUE THREAD

**Issue by rddim** [notepad-plus-plus/notepad-plus-plus#5404]
### Description of the Issue

Hello,
I would like to see this feature in the `Language` menu, in the `Define your language...` section. The same as `Plugins` > `Open Plugins Folder...` but for opening the `userDefineLangs` folder.

### Debug Information

Notepad++ v7.6.4   (64-bit)
Build time : Mar  6 2019 - 02:58:24
Path : D:\Install\Office Programs\Notepad++\notepad++.exe
Admin mode : ON
Local Conf mode : ON
OS : Windows 7 (64-bit)
Plugins : AutoSave.dll ComparePlugin.dll VisualStudioLineCopy.dll 

### Other Info

I also open the same request at the Community: [[Request]: Open Language(s) Folder...](https://notepad-plus-plus.org/community/topic/17271/request-open-language-s-folder)

**Comment by rddim** [comment]
@SinghRajenM or @pnedev 
Could you take a look here please :)

**Comment by SinghRajenM** [comment]
@rddim , just trying to understand why do we need the folder location at first place? Because layman should not bother about it and also "import" and "Export" options are given on UDL dialog.
So any specific reason for this need?

**Comment by rddim** [comment]
@SinghRajenM with this option I can manage more easily the separated UDL files: fast access, copy, paste, share, edit, add, remove and etc. For example I have created some UDLs that I want to share with other users and it is more easily to tell the user: Go to the `Language > Open UDL folder` and just put it in that folder, instead of: Go to the `Language > Define your language... > Import...` and navigate to the UDL file. Also with the `Import...` option on UDL dialog I loose the abillity to have UDLs in separated files.

**Comment by donho** [comment]
@rddim I'm not sure the menu item in Language menu is the right place for this feature.

**Comment by xylographe** [comment]
Perhaps, an "Open UDL folder..." button in the "User Defined Language" dialogue, between the "Export..." button and the "Ignore case" check box?

**Comment by rddim** [comment]
@donho and @xylographe 
My wish for the `Open UDL Folder...` was inspired by the `Open Plugins Folder...` item which is in `Plugins` menu and not in `Plugins Admin...` dialogue. In this case you save 2 clicks - 1 for opening the `UDL` dialogue and 1 for closing it.
@donho what is your suggestion for the right place?

**Comment by pnedev** [comment]
IMO, @rddim 's suggestion sounds very reasonable.
