### ISSUE TITLE
Notepad++ crashing

### ISSUE THREAD

**Issue by TimonMi** [notepad-plus-plus/notepad-plus-plus#5407]
### Description of the Issue
I created a new draft a few minutes ago and wrote some content into it. Nothing special, just a few lines of normal notes.
about half an hour later i cut the text out and pasted it somewhere else. I already noticed that the tab of the draft had no name and no symbol. Then Notepad++ crashed.

### Steps to Reproduce the Issue
I did not manage to reproduce it.
It just happened once so far. I'll update if it happens again.

### Expected Behavior
Notepad++ shows the empty draft and i am able to close it.

### Actual Behavior
Notepad++ crashes and recently closed tabs are opened again.

### Debug Information
Notepad++ v7.5.8   (32-bit)
Build time : Jul 23 2018 - 02:03:53
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 7 (32-bit)
Plugins : DSpellCheck.dll mimeTools.dll NppConverter.dll NppExport.dll 
![npp_crash_20190312_09_26](https://user-images.githubusercontent.com/12981672/54185627-ceba7a00-44a9-11e9-8c56-b57a180c86ca.PNG)

**Comment by donho** [comment]
v7.5.8 ?
Sorry, but we don't support the old version.
Please update to v7.6.4.
