### ISSUE TITLE
Result area for Find all in current document shows the same line for all the hits.

### ISSUE THREAD

**Issue by saiabinesh** [notepad-plus-plus/notepad-plus-plus#5408]
### Description of the Issue
When I click Find all in current document, it returns all hits, but shows the same line for all the hits.

### Steps to Reproduce the Issue

1. Open document https://1drv.ms/u/s!AmjT3Nssiy80nEUwjcUmYg7-eSGX
2. Press Ctrl + F to open find window
3. In the Find_what: field, type image_
4. Uncheck the "Match whole_word only" checkbox
5. Click Find All in Current Document
6. Result will show 9921 hits, but the same line 'Line 1: {"image...' for all hits

### Expected Behavior

I expected the preview below will show all the different lines where it occured, including Line1:, Line 9 ...

### Actual Behavior

The results window showed the same hit 9921 times. 
![notepad++_error_log](https://user-images.githubusercontent.com/12128767/54198557-b0ab4480-44be-11e9-99fa-edf789407dc3.png)

### Debug Information

Notepad++ v7.5.9   (64-bit)
Build time : Oct 14 2018 - 15:19:55
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10 (64-bit)
Plugins : DSpellCheck.dll mimeTools.dll NppConverter.dll

**Comment by sasumner** [comment]
Why do you think there is more than 1 line in your file?

**Comment by MetaChuh** [comment]
@saiabinesh 

your provided example file has only one line

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
(no extra account is needed, just use your github account to sign in)
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)
