### ISSUE TITLE
Links not working with UTF-8 characters

### ISSUE THREAD

**Issue by peich1** [notepad-plus-plus/notepad-plus-plus#5410]
### Description of the Issue
Links doesn't open correctly when there are umlauts and some special characters (possibly UTF-8) in the line. 

### Steps to Reproduce the Issue

1. Disable "Autodetect character encoding", so umlauts are correctly shown in UTF-8 files.
2. Clicking in a link with umlauts. 

### Expected Behavior

The whole line should be underlined and the link should open correctly.

### Actual Behavior

The link is underlined partially (till the umlaut) and only the first half of the link is transferred to Chrome.

### Debug Information
Notepad++ v7.6.4   (64-bit)
Build time : Mar  6 2019 - 02:58:24
Path : C:\PROGRAMS\Notepad++\notepad++.exe
Admin mode : ON
Local Conf mode : ON
OS : Windows 10 (64-bit)
Plugins : HexEditor.dll mimeTools.dll NppConverter.dll

**Comment by SalviaSage** [comment]
Hey, are you talking about the URL links?
This is not a bug.

You just need to escape the characters using a URL encoder.
The apostrophe is %27 for example, open bracket ( is %28, close bracket ) is %29 etc.

Try this converter: https://meyerweb.com/eric/tools/dencoder/

**Comment by peich1** [comment]
Hi!
I do think it's a bug, Notepad++ should be able to understand that the link doesn't end till there is a space or a carriage return. An UTF-8 character should not be a reason to "end" a link, and I think N++ should be able to understand this without the need for escapes (furthermore, it's quite impractical having to modify every new file just to be able to correctly open the file!).

**Comment by SalviaSage** [comment]
Hmm. I also have to agree with you, but that probably means extra coding that
simply is not there. This would be more of a feature request.

I am sure that Notepad++ can be configured to recognize links and underline them in some way.
If the developer puts that code in there.

In the meantime, use the URL encoder, that is how I make all of my links work in notepad++ and
github gists and other areas.

**Comment by MetaChuh** [comment]
hi @SalviaSage & @peich1 and all

> Try this converter: https://meyerweb.com/eric/tools/dencoder/

i've just tested it and unfortunately this converter's results will not work on all browsers.

if you take the link: http://www.kombüse.de and encode it, it would be http://www.komb%C3%BCse.de which is incorrect and will not work in some browsers like internet explorer.

the correct conversion, which is compatible to all browsers is: http://www.xn--kombse-6ya.de

if you need to convert the special chars urls as a workaround, i've just found this one that does the job:

https://www.internet-marketing-inside.de/Umlaut-URL-Konverter-Online-Tool.html?anzeige-url=www.kombüse.de#result
