### ISSUE TITLE
Regex non-greedy matching 

### ISSUE THREAD

**Issue by DavidHaslam** [notepad-plus-plus/notepad-plus-plus#5413]
Might the Search Mode area for ‘Regular expression’ be enhanced by a further tick box labelled “Non-greedy”.

Yes - I know that each relevant part of a regex can be modified by the ‘?’ qualifier. 

But being able to toggle search between greedy (default) and non-greedy would be a really useful enhancement.

**Comment by sasumner** [comment]
Perhaps this is interesting.  How do you propose this would work (i.e. maybe some examples where in one case show the "unticked" regex and then the "ticked" regex?)

**Comment by DavidHaslam** [comment]
It might help to understand where the idea comes from. 

I’m a heavy user of TextPipe Standard from DataMystic. 

The replace filters in TextPipe support PCRE and each such filter has a tick box that toggles between greedy and non-greedy matching. 

The usefulness is that the same search pattern can be processed in two different ways “under the hood”.

If you’ve a pattern with several ‘+’ qualifiers (or ‘*’ qualifiers) you can change how the search matching works without having to edit each such qualifier in the pattern. 

I’ve lost count of the number of times that this feature has been useful for me.

**Comment by sasumner** [comment]
Ah, so it just seeks out the `+` and the `*` and changes all occurrences to `+?` and `*?` respectively (or the other way around).

**Comment by DavidHaslam** [comment]
It doesn’t visibly change what the user has entered in the UI - so how it works must be entirely “under the hood” so to speak.

**Comment by MetaChuh** [comment]
@DavidHaslam 

thank you for your feature idea.
this will currently not be implemented, as the used regex engine is an external project.
please use ? for non greedy.

thank you for your help and best regards.

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
(no extra account is needed, just use your github account to sign in)
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)
