### ISSUE TITLE
website downloads page: mark "portable" downloads

### ISSUE THREAD

**Issue by pryrt** [notepad-plus-plus/notepad-plus-plus#5415]
On the https://notepad-plus-plus.org/download/ page, it might be nice to use the word "portable" on the "zip", "7zip", and "minimalist" entries

As noted [in the Community Forums](https://notepad-plus-plus.org/community/topic/17269/how-to-replace-whole-paragraph-with-extended-replacement/9), even seasoned regulars don't realize that the "zip" entries are "portable", and thus use the portableapps.com re-bundling (or worse), instead of getting the safe and clean portable version directly from notepad-plus-plus.org.  

By having them clearly marked as "portable", it might mean more people download from the official source, rather than looking for portable versions elsewhere.

**Comment by pryrt** [comment]
[Another instance](https://notepad-plus-plus.org/community/topic/17463/autosave-not-working-in-v-7-6-6/) of someone getting the portableapps.com re-bundle, instead of getting the zip/7z/minimalist directly from the official website.  

This is a frequent problem.  We need to get the phrase "portable Notepad++" associated with the official download page, because right now, [Google searches list](https://i.imgur.com/32YdAP8.gif) PortableApps as the #1 link for downloading "portable Notepad++".  The best way of doing that is to have all the official download pages include the word "portable" and/or the phrase "portable Notepad++", so that as Google indexes the download page(s), it improves your position in the ranking.

**Comment by MetaChuh** [comment]
todo:

-----

* [ ] **add** the word **`portable`** to zip and 7z packages.
(to avoid that new users believe, that notepad++ portable is only available at portableapps.com)

   e.g.:
Notepad++ zip package 32-bit x86: Don't want to use installer? Check this **`portable`** one.

   ~~instead of:~~
~~Notepad++ zip package 32-bit x86: Don't want to use installer? Check this one (zip format).~~

-----

* [ ] **remove** the **google+** link at the bottom of each page
(deprecated, since the google+ service has been shut down)

   <img width="475" alt="Bildschirmfoto 2019-04-24 um 09 24 06" src="https://user-images.githubusercontent.com/45773305/56640582-ae1e3c00-6673-11e9-8858-499c6471bde7.png">

-----

**Comment by pryrt** [comment]
[Here](https://notepad-plus-plus.org/community/topic/17506/saving-style) is another instance of someone's problem being caused because they downloaded an unofficial build rather than the official build.

**Comment by ArkadiuszMichalski** [comment]
@donho Do you consider adding this `portable` word in somwhere in download section (or add some clarification that .7z and .zip can be treate as portable version), even for better position in Google (https://github.com/notepad-plus-plus/notepad-plus-plus/issues/5415#issuecomment-484504336). If there is no such need, maybe close this bug?

**Comment by donho** [comment]
Sorry I didn't see this issue (and a lot of others).
Yes, it's a good idea. 
How about such modification?
https://notepad-plus-plus.org/downloads/v7.8.4/

The current site is "mobile-friendly", so we've got the restriction of width (to avoid the wrap). OTOH, keeping them short is not a bad idea. Any better suggestion?

**Comment by ArkadiuszMichalski** [comment]
In my opinion it is sufficient, short and to the point. @pryrt @MetaChuh what do you think?

@donho  Format for links/filses will not change, I mean still will be:
https://github.com/notepad-plus-plus/notepad-plus-plus/releases/download/v7.8.4/npp.7.8.4.bin.zip
https://github.com/notepad-plus-plus/notepad-plus-plus/releases/download/v7.8.4/npp.7.8.4.bin.7z
https://github.com/notepad-plus-plus/notepad-plus-plus/releases/download/v7.8.4/npp.7.8.4.bin.minimalist.7z

?

**Comment by pryrt** [comment]
Looks good to me.  Makes it much more clear that the zip is portable.

Thanks!

**Comment by donho** [comment]
@ArkadiuszMichalski 
> Format for links/filses will not change, I mean still will be:
https://github.com/notepad-plus-plus/notepad-plus-plus/releases/download/v7.8.4/npp.7.8.4.bin.zip
https://github.com/notepad-plus-plus/notepad-plus-plus/releases/download/v7.8.4/npp.7.8.4.bin.7z
https://github.com/notepad-plus-plus/notepad-plus-plus/releases/download/v7.8.4/npp.7.8.4.bin.minimalist.7z
?

Good question, my first think is keeping file names format. But if there are advantages to change them, we can always do it in the futures release. What advantage will we get by changing the file name format?

**Comment by ArkadiuszMichalski** [comment]
I would rather not change, because it may spoil the automation for someone. But I don't know if the change in URL would be better due to SEO, basically `portable` in the content should be enough.

**Comment by donho** [comment]
@ArkadiuszMichalski 

It costs little effort for doing it. Let's rename them in the future as following:
* npp.7.9.portable.zip
* npp.7.9.portable.7z
* npp.7.9.portable.minimalist.7z

**Comment by donho** [comment]
The fixed on web will published with new release 7.9
