### ISSUE TITLE
"Update Notepad++" doesn't find 7.6.4

### ISSUE THREAD

**Issue by KommX** [notepad-plus-plus/notepad-plus-plus#5417]
### Description of the Issue

I have installed 7.6.3 (64 bit). I know that 7.6.4 is the newest version, but the updater doesn't find it.

### Steps to Reproduce the Issue

1. Install 7.6.3
2. Menu --> ? --> Update Notepad++

### Expected Behavior

Some kind of message that 7.6.4 is available should appear.

### Actual Behavior

A message "No update is available" appears.

### Debug Information

Notepad++ v7.6.3   (64-bit)
Build time : Jan 27 2019 - 17:16:47
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10 (64-bit)
Plugins : DSpellCheck.dll mimeTools.dll NppConverter.dll

**Comment by donho** [comment]
Please read the release news.

**Comment by KommX** [comment]
@donho 
I guess, you're referring to the sentence:

> Auto-updater will be triggered in few days if there's no critical issue found.

I had a similar situation with 7.5.9 where I was stuck.
After which time do you think it would be appropriate to reopen this issue?
