### ISSUE TITLE
NPP jumps to the beginning of a wrapped line after switching between tabs

### ISSUE THREAD

**Issue by Yaron10** [notepad-plus-plus/notepad-plus-plus#5418]
**STR:**
Check `View -> Word wrap`.
Open [langs.model.xml](https://github.com/notepad-plus-plus/notepad-plus-plus/files/2959078/langs.model.zip).
Scroll to the middle of line 8.
Switch to another tab.
Switch back to `langs.model.xml`.

**Result:**
 NPP jumps to the beginning of line 8.

This may cause a selected word/search-term not to be visible.

**Comment by MetaChuh** [comment]
hi @Yaron10 

yes, you are correct as usual.

we only have very crude workarounds for that at the community, so if you find any quicker workaround, until it is eventually looked at, i'd appreciate it a lot.

if it is wanted to preserve the current word selection:
switch to any tab and then back to the langs.model.xml tab.
press ctrl+f3 and then ctrl+shift+f3 to trigger select and find next and select and find previous to go back.
(the document will then jump back to the place where it was before switching the tabs, the previously selected word or section will still be marked)

if it is only wanted to jump back to the cursor position:
switch to any tab and then back to the langs.model.xml tab.
hit [cursor right] and then [cursor left]
(the document will jump back to the cursor where it was before switching the tabs)

best regards
metachuh

**Comment by Yaron10** [comment]
Hello @MetaChuh,

Thank you for the useful tips and also for your contribution in general.
:+1: 

"Mouse-Oriented" users can go to the caret position by assigning a toolbar button to the following Python-Script:
```
editor.verticalCentreCaret()
```
:)

Best regards.

**Comment by Yaron10** [comment]
Fixed. If I remember correctly in 7.8.3.
