### ISSUE TITLE
[Feature Request] SHIFT+ENTER or CTRL+ENTER to create a new line with no indentation

### ISSUE THREAD

**Issue by ARecurringProblem** [notepad-plus-plus/notepad-plus-plus#5421]
### Description of the Issue
Auto-indent can be incredibly frustrating when working with things like XML files that may require unindented lines within indented tags.  I see a couple other issues open for more elaborate changes to the auto-indent system in this vein; I think a simple keyboard shortcut like SHIFT+ENTER or CTRL+ENTER to add an unindented line would be an ideal band-aid fix that can be implemented super easily while you work on adding more customization to the auto-indent system.

**Comment by MetaChuh** [comment]
@ARecurringProblem 

many thanks for your feature request.

this is depending on the implemented scintilla component.
unfortunately scintilla is an external project, so we can currently not solve this at the notepad++ part.
we apologise for that.

thank you for your help and best regards.

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
(no extra account is needed, just use your github account to sign in)
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)
