### ISSUE TITLE
Publish binaries into GitHub Releases too

### ISSUE THREAD

**Issue by KOLANICH** [notepad-plus-plus/notepad-plus-plus#5424]
It makes sense to publish binaries and signatures into GH Releases too.

**Comment by MetaChuh** [comment]
why ?

**Comment by LordNyriox** [comment]
@MetaChuh:  

>why ? 

Because the layout of the official Notepad++ website is a mess to navigate, when you just want to download the current version.

**Comment by MetaChuh** [comment]
@KOLANICH 

please bookmark this link: https://notepad-plus-plus.org/download/

this link will always redirect you to the most current version's download page directly.
(this way you do not have to navigate the website manually again)

**Comment by KOLANICH** [comment]
>why ?

1. It is a backup source. It worths nothing to publish here, so why not?
2. GH has API, NPP website doesn't.

**Comment by MetaChuh** [comment]
@KOLANICH 

sorry, currently we can't publish the binaries at github, as [github only allows 1gb traffic per month](https://help.github.com/en/articles/about-storage-and-bandwidth-usage).
this quota would be exceeded in far, far less time.

@LordNyriox

off topic: <kbd>cmd</kbd> == `<kbd>cmd</kbd>` 😉

**Comment by KOLANICH** [comment]
@MetaChuh it is about Git LFS, not about Releases
