### ISSUE TITLE
Language menu for translated strings

### ISSUE THREAD

**Issue by Ices-Eyes** [notepad-plus-plus/notepad-plus-plus#5428]
Hi Don,
I recevied an email from a user using Notepad++ and my italian translation, that pointed me out to a problem that I never really investigate, but actually could be a little misleading. The language menu aggregate languages based on the first letter of the language, but based on the english string, that could be different in other translations. I.e. “Normal text” (N) become “Testo normale” (T) in italian, but it stay on the N menu aggregation. Do you think it would be feasible to change the aggregation of the menu based on the translated string and not the original one?

Thanks,
Luca

**Comment by Faq** [comment]
For such questions, isnt better to use forum?

**Comment by Ices-Eyes** [comment]
Posted on the forum and advice to post it here 😂
It's a sort of feature request...

**Comment by MetaChuh** [comment]
@Faq 

@Ices-Eyes is at the correct place. 😂
this is directly related to his own commit from 2018.12 and is related to the automatic grouping of computing languages from a-z, which is part of the main code.

explanation:
if a user has `make language menu compact` selected, and a computing language has a translation that starts with a different letter than the english name, it will still be categorised at the letter of the english original spelling.

@Ices-Eyes 

currently the only workaround, without any needed code change, is to translate it to `Normale (Testo)`.

(ps: this workaround at your italian.xml, would apply, if you want or have to get it fixed quicker, as you could do that autonomously)

**Comment by chcg** [comment]
See https://github.com/notepad-plus-plus/notepad-plus-plus/blob/b75ccd29e201519b74cb3c3cd74aa27bd50fd597/PowerEditor/src/Notepad_plus.rc#L780
and https://github.com/notepad-plus-plus/notepad-plus-plus/blob/b75ccd29e201519b74cb3c3cd74aa27bd50fd597/PowerEditor/src/Notepad_plus.rc#L691

The order of the menu entries is hardcoded within the resource file, so this couldn't be easily changed without changing the standard windows menu handling.
