### ISSUE TITLE
Add Support for Visual encoding for RTL languages

### ISSUE THREAD

**Issue by bsagal** [notepad-plus-plus/notepad-plus-plus#5436]
Please add support for Visual encoding for rtl languages (ie the ability to disable the BIdi algorithm)

I need to deal with old files in the OEM862 code page which encodes Hebrew visually (not logically like modern encodings)

In modern logical endings such as CP1255 or UTF-8 the word שלום is encoded as:
1. ש
2. ל 
3. ו
4. ם

The bidi algorithm is applied the the text and the editor correctly prints the letter from Right to left

however with old visual encoding the text is encoded as:
1. ם
2. ו 
3. ל
4. ש

The editor does not need to apply and bidi algorithm as it is encoded in an order that will print correctly if printed from left to right.

At the moment it is very difficult to read the files as the bidi algorithm is being applied and everything is back to front

**Comment by MetaChuh** [comment]
as rtl is part of the scintilla component, you would have to file your request at the [scintilla project feature requests](https://sourceforge.net/p/scintilla/feature-requests/).
thanks for understanding and best regards.
