### ISSUE TITLE
Trouble with path argument enclosed in single-quotes

### ISSUE THREAD

**Issue by monoblaine** [notepad-plus-plus/notepad-plus-plus#5437]
### Description of the Issue

Notepad++ cannot open a file if the path to the file contains spaces and the path argument is enclosed in single-quotes.

The following command works: (Tested it to make sure a request to open a file using path-within-single-quotes as the path argument is actually a normal thing)

```
notepad.exe 'C:/path with spaces/foo.txt'
```

This one doesn't work:

```
"C:\Program Files (x86)\Notepad++\notepad++.exe" 'C:/path with spaces/foo.txt'
```

Notepad++ seems to ignore single-quotes and tries to open `C:/path`

#### Why am I doing this? (Trivia)

I've configured git to use Notepad++ as the default editor. (`core.editor` config) Using the regular CMD, I've executed `set GIT_TRACE=1` and executed another git command that launches the editor as a result. This what I saw:

```
hint: Waiting for your editor to close the file... 19:58:53.880614 run-command.c:643       trace: run_command: GIT_INDEX_FILE=.git/index ''\''C:/Program Files (x86)/Notepad++/notepad++.exe'\'' -multiInst -nosession -noPlugin' 'C:/some other path with spaces/.git/COMMIT_EDITMSG'
```

### Debug Information

```
Notepad++ v7.5.9   (32-bit)
Build time : Nov  5 2018 - 10:20:39
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10 (64-bit)
Plugins : mimeTools.dll NppConverter.dll NppExport.dll JSMinNPP.dll LocationNavigate.dll MarkdownViewerPlusPlus.dll NppFTP.dll PluginManager.dll 
```

I'm not totally sure but issue #4981 might be related with this one.

**Comment by monoblaine** [comment]
(Same in v7.6.4)

```
Notepad++ v7.6.4   (32-bit)
Build time : Mar  6 2019 - 02:52:22
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10 (64-bit)
Plugins : mimeTools.dll NppConverter.dll NppExport.dll 
```

**Comment by sasumner** [comment]
notepad.exe 'C:/path with spaces/foo.txt'

I can't reproduce your success with the above with 7.5.9.  With double-quotes it works fine, with single quotes I get this:

![image](https://user-images.githubusercontent.com/30118311/54558424-105c9080-4994-11e9-82a1-0f40f0fc87d8.png)

**Comment by MetaChuh** [comment]
@sasumner 

i guess the success was only for the windows notepad.exe.

@monoblaine 

i do not use or read msysgit, but is it possible to set `git config --global core.editor` to use double quotes instead of single quotes for argv[1] ?

did you try to use the following config: `git config --global core.editor \
"'C:/Program Files (x86)/Notepad++/notepad++.exe'"` with single quotes in double quotes and omitting any switches ?
(maybe this triggers msysgit to use double quotes for it's core.editor argv)

as i have read on the quick, some users also call a batch script instead of notepad++, where they can wrap the argv within double quotes, before passing it to notepad++.
(quick and dirty, but i guess people did it that way, because of so many contradicting solutions regarding notepad++ integration, where one user says it works perfectly, and the other one says it does not work at all).

ps: the stackoverflow page about that, which looks most promising at first glance, is: https://stackoverflow.com/questions/10564/how-can-i-set-up-an-editor-to-work-with-git-on-windows

**Comment by sasumner** [comment]
> i guess the success was only for the windows notepad.exe.

Ha. I totally missed that!  I thought the OP was somehow making N++ do it. :)  Why does everybody think that notepad.exe is the base spec for notepad++.exe ?

**Comment by MetaChuh** [comment]
@sasumner 

>  I thought the OP was somehow making N++ do it. :)

yes, and that is still the o.p.'s goal, if i didn't misunderstand something vital.
the windows notepad.exe is just a crosscheck, if single quotes would work with any other program.

> Why does everybody think that notepad.exe is the base spec for notepad++.exe ?

😂😂😂
not so much everybody, and most definitively not in this case.
but i agree, that it would be less funny, if we wouldn't hear such associations from "first time" notepad++ users every once in a while. 😉

**Comment by monoblaine** [comment]
>  Why does everybody think that notepad.exe is the base spec for notepad++.exe ?

Hey @sasumner just like what @MetaChuh said, I didn't mean it that way :smiley:  (There's no need to express my true feelings about that piece of :hankey: ) 

@MetaChuh thanks for the suggestions. I hope I'll try them tomorrow (I've been dealing with my silently failing hard-drive for the past 24 hours.)

**Comment by MetaChuh** [comment]
hi @monoblaine 
good luck with your hdd, i can relate and feel with you 😳🙏😳

**Comment by monoblaine** [comment]
@MetaChuh 

> i do not use or read msysgit, but is it possible to set `git config --global core.editor` to use double quotes instead of single quotes for argv[1] ?
>
> did you try to use the following config: `git config --global core.editor \ "'C:/Program Files (x86)/Notepad++/notepad++.exe'"` with single quotes in double quotes and omitting any switches ?
> (maybe this triggers msysgit to use double quotes for it's core.editor argv)

I think what I said about git sending paths enclosed in single-quotes was not exactly true.

I've added the following line into the beginning of function `parseCommandLine` in `winmain.cpp` to find out how Notepad++ is executed:

```cpp
::MessageBox(NULL, commandLine, TEXT("Args"), MB_OK | MB_ICONINFORMATION);
```

When my `core.editor` is one the following:

```
'C:/Program Files (x86)/Notepad++/notepad++.exe'
'C:/Program Files (x86)/Notepad++/notepad++.exe' -multiInst -nosession -noPlugin
```

I see the following pop-up (Obviously, `-multiInst -nosession -noPlugin` is only added when the second one is used):

```
"C:\Program Files (x86)\Notepad++\notepad++.exe" -multiInst -nosession -noPlugin "\"C:/path with spaces/foo.txt\""
```

I think git (or msysgit?) adds double quotes around the given path *twice* and that's the problem. So we can say the current behavior of Notepad++ is OK. `\"C:/path with spaces/foo.txt\"` is not a proper path anyway.

BUT, I'm reeeeeealy curios. Why does this happen? Is this a bug in Git for Windows? Where should I report it?

And for the moment I've created a very stupid `npp.sh` script and updated `core.editor` to use it instead:

```sh
#!/bin/sh

# Delete \" from the beginning of path
path=${1#\"};
# Delete \" from the end of path
path=${path%\"};

"C:/Program Files (x86)/Notepad++/notepad++.exe" -multiInst -nosession -noPlugin "$path"
```

**Comment by monoblaine** [comment]
Yeah I don't think this has anything to do with Notepad++. I've created an issue in git for windows repo:

https://github.com/git-for-windows/git/issues/2136

Closing this one.
