### ISSUE TITLE
Add multicursor line up and down

### ISSUE THREAD

**Issue by jmbockhorst** [notepad-plus-plus/notepad-plus-plus#5439]
Now that we have added the ability for multicursor left and right movement, the next step is moving the cursor up and down lines. This function will override the current SCI_LINEUP and SCI_LINEDOWN commands that only work for a single cursor.

**Comment by sasumner** [comment]
@jmbockhorst Was your closure of this based upon Don's comment on and closure of #5441 ? :

![image](https://user-images.githubusercontent.com/30118311/54820707-6cfeca80-4c76-11e9-9b73-2c94385446f1.png)

Meaning that soon(!) we will get the functionality via Scintilla.

**Comment by jmbockhorst** [comment]
Yep, this functionality will be built in (presumably) with Scintilla.
