### ISSUE TITLE
Files do not open if notepad++ is already running with admin rights

### ISSUE THREAD

**Issue by Ben136KBC** [notepad-plus-plus/notepad-plus-plus#5444]
I have my notepad++ configured to always use multiple instance and we also pass -multiInst on the command line where ever possible. With no instance open, in File Explorer I right click on a txt file and choose to open it with notepad++. No issues, the file opens in notepad++. Right click on another text file and choose to open it with notepad++. It opens the second file in the same notepad++ instance. Ok, that is unexpected, but fine it opens the file for you.

Close all notepad++ instances. Now run notepad++ with administrator rights, so that is shows [Administrator] in the title bar. Right click on a .txt file in Windows File Explorer and choose to open it with notepad++. The admin instance already running gets focus, but it does NOT open the file nor does it start a new instance of notepad++ to open the file for you.

I would expect the "always in multi-instance mode" setting to perhaps start another instance of notepad++, but it does not. Also, if you edit the "open with" settings in Windows, you cannot add another explicit -multiInst there, I tried that as well.

I am guessing that when you open a file with notepad++, it check to see if there is already an instance running, and if so, asks it to open the file, but if that instance is running with admin rights, the messages doesnt go through due to Microsoft security settings.

Also, in this situation, it does not seem to respect the multiinst setting.

I work in an environment where I use notepad++ lots, and sometimes that environment starts it up with admin rights to edit a file. If you dont want to lose that information but you also need to open another file in notepad++, it does not work.

Maybe the "open with" notepad++ code should check and if that other instance is running with different rights, then hey, start another instance, especially if the multi instance option is set.

I did discover that you can open the registry editor, go to "Computer\HKEY_CLASSES_ROOT\Applications\notepad++.exe\shell\open\command" and add the -multiInst in there, and then if you already have an admin instance running, it will open another instance for you. But why should I have to struggle and figure out to do that if I already set the "always in multi-instance mode" setting?

**Comment by MetaChuh** [comment]
if you use multi instance and need elevated instances, you will have to disable windows uac.
please keep in mind that disabling uac may present a security risk for non power users, as your whole user account will then run elevated.

**Comment by Ben136KBC** [comment]
There is no UAC window that comes up, I do not think UAC is an issue here. You can see the notepad++ instance running with admin right flicker and get focus, but the file is not opened. Ideally the "open with" instance will detect that the other instance is running with different privileges and do something different to open the model, or hey, actually start up another instance as per the setting.
