### ISSUE TITLE
AODA Compliant 

### ISSUE THREAD

**Issue by hussien-hammad** [notepad-plus-plus/notepad-plus-plus#5447]
To Whom It May Concern:

We are reaching out to you regarding the accessibility of your application Notepad ++. As you are aware, Elections Ontario (EO) uses your application and we must abide by AODA legislation (https://www.ontario.ca/laws/statute/05a11). As such, applications in use at EO must meet accessibility WCAG 2.0 Level AA Guidelines.

With that being said, Is your application accessible? If not, do you have plans and/or timelines for when your application will be made accessible?

If it is accessible, do you have existing accessibility compliance reports for your application? Can you share them please?

Thank you for your time

**Comment by sasumner** [comment]
>As you are aware, Elections Ontario (EO) uses your application

Are we aware of this?? I guess we are now. :)

**Comment by hussien-hammad** [comment]
To Whom It May Concern:

We are reaching out to you regarding the accessibility of your application Notepad ++. As you are aware, Elections Ontario (EO) uses your application and we must abide by AODA legislation (https://www.ontario.ca/laws/statute/05a11). As such, applications in use at EO must meet accessibility WCAG 2.0 Level AA Guidelines.

With that being said, Is your application accessible? If not, do you have plans and/or timelines for when your application will be made accessible?

If it is accessible, do you have existing accessibility compliance reports for your application? Can you share them please?

Thank you for your time.


Hussien Hammad
Senior Technical Agile Business Analyst
Office: 416.212.7516

Elections Ontario  elections.on.ca
1.888.668.8683    Fax: 416.326.6200

**Comment by hussien-hammad** [comment]
Hi Friends

If you are the incorrect contact, please let me know who I can reach out to that can help me with my request.

Thank you

Hussien Hammad
Senior Technical Agile Business Analyst
Office: 416.212.7516

Elections Ontario  elections.on.ca
1.888.668.8683    Fax: 416.326.6200

**Comment by sparkchaser** [comment]
Based on my reading, the WCAG are _**Web Content**_ Accessibility Guidelines.  Seeing as Notepad++ is a traditional program and not a web application, these guidelines do not appear to be applicable to this program at all.  Did you file this ticket against the correct piece of software?

**Comment by MetaChuh** [comment]
as pointed out by @sparkchaser , notepad++ is not a web application

**Comment by Ekopalypse** [comment]
@hussien-hammad - a [VPAT](https://notepad-plus-plus.org/assets/files/ITI-VPAT.DOC) has been released,
is this something you can use as well?

**Comment by hussien-hammad** [comment]
Yes please, can you please share it with us?

Thank you for your time.

Hussien Hammad
Senior Technical Agile Business Analyst

Elections Ontario  elections.on.ca
1.888.668.8683    Fax: 416.326.6200

**Comment by Ekopalypse** [comment]
@hussien-hammad, the VPAT, in my previous post, is a link pointing to the document :-)

**Comment by hussien-hammad** [comment]
Thank you very much!

Hussien Hammad
Senior Technical Agile Business Analyst
Office: 416.212.7516

Elections Ontario  elections.on.ca
1.888.668.8683    Fax: 416.326.6200
