### ISSUE TITLE
I can't type $200C character in Windows!

### ISSUE THREAD

**Issue by mlk0000** [notepad-plus-plus/notepad-plus-plus#5456]
I can't type $200C character in Windows!
I can't type "zero width non-joiner" character by "Ctrl + Shift + 2" by Persian language in Windows!

**Comment by MetaChuh** [comment]
> I can't type "zero width non-joiner" character by "Ctrl + Shift + 2" by Persian language in Windows!

i think on a persian keyboard, the zero width non-joiner (u+200c) might not be at <kbd>ctrl</kbd> + <kbd>shift</kbd> + <kbd>2</kbd> like on an english keyboard.

some sites report, that it should be <kbd>shift</kbd> + <kbd>space</kbd> on windows 8.1 and above, but i can't try that out to verify.

you can check and try out multiple keyboard combinations in windows notepad.exe, or notepad++.
if you found the correct keyboard combination for the zwnj character, it will be presented like this: `…` (a triple dot in a single character)

maybe you can also have a look at this page and find how to get zwnj to work on your specific windows version.
https://ehsanakhgari.org/article/miscellaneous/2008-06-11/standard-persian-keyboard-for-windows

**Comment by mlk0000** [comment]
Thank u. But ...
I mean, I can not type that character in Notepad++ (by Persian keyboard) !
Ctrl + Shift + 2 worked in Win Notepad on Persian keyboard.

*shift + space not work totally on win 10 v1809 :(
