### ISSUE TITLE
Improper file save if file tab position is changed

### ISSUE THREAD

**Issue by shivammanjunath** [notepad-plus-plus/notepad-plus-plus#5457]
### Description of the Issue
Opened a saved text file, say, saved as File_1.txt.
Edited the File_1.txt, shown with the red icon in tab.
Created a new text through Ctrl + N (File_1.txt is not saved yet)
Type something in 'new 1' file.
Now exchange the tab positions of 'File_1.txt' and 'new 1'
Focus the File_1.txt and try to save the file through Ctrl + S.
New file save window is opened instead of silent save since it is already saved to disk.

### Steps to Reproduce the Issue
1. Opened a saved text file, say, saved as File_1.txt.
2. Edited the File_1.txt, shown with the red icon in tab.
3. Created a new text through Ctrl + N (File_1.txt is not saved yet)
4. Type something in 'new 1' file.
5. Now exchange the tab positions of 'File_1.txt' and 'new 1' (through tab drag using mouse pointer)
6. Focus the File_1.txt and try to save the file through Ctrl + S.
7. New file save window is opened instead of silent save since it is already saved to disk.

### Expected Behavior
Irrespective of tab position of the file in app window, files should be saved properly.

### Actual Behavior
Already created and edited file save pops up Save As window

**Comment by MetaChuh** [comment]
@shivammanjunath 

i can not reproduce this issue on notepad++ 7.6.4, following your step by step instructions carefully and repeatedly.

please close your installed notepad++.
then download [>>> this portable 7.6.4. version <<<](https://notepad-plus-plus.org/repository/7.x/7.6.4/npp.7.6.4.bin.zip),
extract it to your desktop,
and start it by double clicking on `notepad++.exe` inside the `npp.7.6.4.bin` folder on your desktop.
then try to reproduce your steps on the portable version.

note: the portable version will be completely isolated from your installed version, so all settings and tests you conduct there, will not influence or modify your installed version.

for any further help, we would need the debug information of your installed version.
(it is missing at your description from above)

**Comment by sasumner** [comment]
Closing due to lack of response.
