### ISSUE TITLE
bug - Remove Consecutive Duplicate Lines

### ISSUE THREAD

**Issue by Robbie3** [notepad-plus-plus/notepad-plus-plus#5462]
### Description of the Issue
"Remove Consecutive Duplicate Lines" removes to many lines
(tested version V7.6.4 64b)

### Steps to Reproduce the Issue

1. Create new input file (copy the following 3 lines as a new file)
text 3 4
text 3 4
text 3 4 5
2. Execute "Remove Consecutive Duplicate Lines" from the "Edit", "Line Operations" menu
3. Watch results

### Expected Behavior
I expect the following result:
text 3 4
text 3 4 5

### Actual Behavior
What i got is:
text 3 4 5

### Debug Information
Notepad++ v7.6.4   (64-bit)
Build time : Mar  6 2019 - 02:58:24
Path : C:\My Documents\Util\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : ON
OS : Windows 10 (64-bit)
Plugins : mimeTools.dll NppConverter.dll 

Thank your for your attention
Regards Rob

**Comment by sasumner** [comment]
Why did you expect the result you did?  It is called "Remove Consecutive Duplicate Lines" and it seems to me like that is exactly what it did.

**Comment by MetaChuh** [comment]
this seems a bug if the 3rd line has the whole 2nd line at the beginning of its content.

**correctly working example:**
```
abc
abc
def
```
after removing consecutive duplicate lines, the result will be:
```
abc
def
```

**example producing this issue:**
```
abc
abc
abcdef
```

after removing consecutive duplicate lines, the result will be:
```
abcdef
```
also deleting the single, deduplicated `abc` line, that should remain. 

**workaround:**
don't use the complete content of a line at the beginning of the next consecutive line, if you use the function remove consecutive duplicate lines. 😉
