### ISSUE TITLE
Can't send some type of Scintilla message with macro

### ISSUE THREAD

**Issue by crash5** [notepad-plus-plus/notepad-plus-plus#5463]
### Description of the Issue
I try to add a macro to set the "virtual space" options in Scintilla, but it looks like the message not sent or something is went wrong. (Another Scintilla message like "move cursor left" works.)

The same message works with the NppExec plugin script: `SCI_SENDMSG 2596 3 0` [(source)](https://superuser.com/a/402405)

### Steps to Reproduce the Issue
Edit **shortcuts.xml** add this code snippet inside the `<Macros>...</Macros>` tag:
```xml
<Macro name="Enable virtual space" Ctrl="no" Alt="no" Shift="no" Key="0">
    <Action type="0" message="2596" wParam="3" lParam="0" sParam="" />
</Macro>
<Macro name="Move cursor left" Ctrl="no" Alt="no" Shift="no" Key="0">
    <Action type="0" message="2308" wParam="0" lParam="0" sParam="" />
</Macro>
```

### Expected Behavior
After run the "Enable virtual space" macro I can put the caret beyond line end with mouse.

### Actual Behavior
Nothing.

### Debug Information
```
Notepad++ v7.6.4   (32-bit)
Build time : Mar  6 2019 - 02:52:22
Path : D:\npp\notepad++.exe
Admin mode : OFF
Local Conf mode : ON
OS : Windows 10 (64-bit)
Plugins : DSpellCheck.dll mimeTools.dll NppConverter.dll NppExport.dll 
```

**Comment by sasumner** [comment]
It is my guess that it was never intended to work via this method. Your "cursor left" example working may not be relevant. Any problem with doing this with NppExec (you seem to know how)?

**Comment by crash5** [comment]
The cursor movement and the virtual-space macro option are both "scintilla message" (the nppexec method too) so i think it works the same way.

I found a similar snippet on the [Npp wiki - Useful Macros](http://docs.notepad-plus-plus.org/index.php/Useful_Macros) page from 2010. (there is no proof that it was worked but i think it is maybe just a regression?)

I'm looking for the macro way because i don't want to install a plugin just for this and sometimes run npp with plugins disabled. (-noPlugin)

**Comment by sasumner** [comment]
You should have pointed to that wiki entry earlier. I now agree with you. It is a regression. I tried it on my daily-use Notepad++ (v7.2.2) and that technique will allow it to enter virtual space mode. Trying in a scratch copy of 7.6.4 I find (as you did) that it doesn't work.  I'll leave it to you or someone else to track down exactly which version breaks it. :)

**Comment by chcg** [comment]
See
https://github.com/notepad-plus-plus/notepad-plus-plus/blob/ef13902206f80e00dcfd7d85b342066ed6f86d66/scintilla/include/Scintilla.h#L885

with docu ( also newer than the used scintilla of N++)
https://www.scintilla.org/ScintillaDoc.html#SCI_SETVIRTUALSPACEOPTIONS

With 3  being SCVS_RECTANGULARSELECTION=1 & SCVS_USERACCESSIBLE=2

With default:
https://github.com/notepad-plus-plus/notepad-plus-plus/blob/cf35168491aa373b583f52f8d1baf58143928cba/PowerEditor/src/Notepad_plus.cpp#L323-L325

**Comment by sasumner** [comment]
@chcg Yes, but maybe I miss the point you are making?

**Comment by crash5** [comment]
The macro works in the version 7.6.3. So this is a regression from 7.6.3 to 7.6.4 :)

**Comment by crash5** [comment]
I think this message (`SCI_SETVIRTUALSPACEOPTIONS `) is missing from the switch in [shortcut.cpp: recordedMacroStep::isMacroable()](https://github.com/notepad-plus-plus/notepad-plus-plus/blob/master/PowerEditor/src/WinControls/shortcut/shortcut.cpp#L688)

**Comment by sasumner** [comment]
@crash5 Add it in, test it, if it works, make a PR. :)
