### ISSUE TITLE
Feature Request: Include "In Selection" tick box in Find dialog

### ISSUE THREAD

**Issue by echo-e** [notepad-plus-plus/notepad-plus-plus#5464]
I want to be able to use the Count button in the Find dialogue to count number of occurances of a pattern within a selection block. Thus, I feel the "In Selection" tick box should be included in the standard Find dialogue, not just the Replace dialogue.

**Comment by sasumner** [comment]
Good suggestion.  Want a (lame) workaround?  Do a replace-in-selection with the same text as the find, and then the status bar of the Replace dialog will tell you how many occurrences. :)

**Comment by sasumner** [comment]
Implemented due to issue #722 being implemented.
