### ISSUE TITLE
"Find All in All Opened Documents" for unsaved documents shows an error - wrong directory

### ISSUE THREAD

**Issue by bffrahul** [notepad-plus-plus/notepad-plus-plus#5468]
### Description of the Issue

Double clicking on a result in "Find result window" after "Find All in All Opened Documents" doesn't take to the document.

Version: NPP 7.6.4 (32 bit)

### Steps to Reproduce the Issue

1. Start npp
2. Have a couple of unsaved documents opened
3. Hit CTRL+F and type a string
4. Click on "Find All in All Opened Documents"
5. Double click on any result

### Expected Behavior

Takes to the document where the search result was found

### Actual Behavior

Displays an error: "C:\Program Files (x86)\Notepad ++\new 1" doesn't exist. Create it?

### Debug Information

![Notepad++ Bug - 20190329 - Find All in All Opened Documents - wrong directory](https://user-images.githubusercontent.com/1521851/55265199-884c7580-5234-11e9-8473-be6dada69f08.png)

**Comment by MetaChuh** [comment]
@bffrahul 

yes, you are correct.
this was a known bug in 7.6.4. which has been fixed.
this fix will be available at the upcoming 7.6.5 release.

details: https://github.com/notepad-plus-plus/notepad-plus-plus/commit/6580255a2b6809a1fa951db44ec8be29698b8540

**Comment by SinghRajenM** [comment]
@MetaChuh it should be closed.
