### ISSUE TITLE
Ampersands are not displayed with new Font (Source Code Pro)

### ISSUE THREAD

**Issue by uli-a** [notepad-plus-plus/notepad-plus-plus#547]
If the new font (Source Code Pro) is used, ampersands (&) are not displayed for certain languages (e.g. JavaScript, C, Fortran, R) :
![missing ampersand](https://cloud.githubusercontent.com/assets/13470788/8855284/b927c0be-3164-11e5-82f0-b6e7c1f98fde.png)
For other languages it is fine (e. g. XML or HTML)
![displayed ampersand](https://cloud.githubusercontent.com/assets/13470788/8855361/1337013c-3165-11e5-9585-b86c824e6dcc.png)
 I used the default stylers.xml. For other themes (I tried Mono Industrial and Black Board) it seems to work event if the font is changed to Source Code Pro.

**Comment by donho** [comment]
I cannot reproduce the bug:
![1557712_763221057056202_8141006547373112469_n](https://cloud.githubusercontent.com/assets/90293/8863223/01d1394e-3197-11e5-9e69-adaebd8e2dd6.jpg)
I know there might be nothing to do with plugins, but could you remove "plugins" directory then try again to make sure it's not about plugins issue?
Also it'll help if you can provide the info of your environment.

**Comment by uli-a** [comment]
I just downloaded the 7zip-Archive of version 6.8 and tried with a fresh install (no plug-ins, no configuration changes). The issue is still there.

I am running Notepad++ on Windows 7 SP1 64bit.

Is #552 the same issue?

**Comment by donho** [comment]
@uli-a I did some changes for this issue but I'm not sure if it is fixed since I cannot reproduce it.
Could you download this file:
https://notepad-plus-plus.org/temp/npp.7z
unzip it into a new created folder, then launch notepad++.exe.
Please let me know the result.

**Comment by donho** [comment]
@uli-a Any input about it?

**Comment by uli-a** [comment]
@dunho Sorry for the late answer: The problem was still there. Then I replaced the existing font SourceCodePro with the four files from your archive. Now the & is displayed correctly, even for the version of Notepad++ that I have installed.

The version of the font I had installed has only two files (SourceCodePro-Bold.ttf and SourceCodePro-Regular.ttf, both 102KB, from March 26th, 2013)

**Comment by donho** [comment]
@uli-a So you have installed Source Code Pro BEFORE you use Notepad++ v6.8. Could you confirm me that?

**Comment by tico-tico** [comment]
@donho
I see that you included Italics in the test version. Just FYI before something bad happens. I don't think that scintilla uses Italics font at all (I can't see handles for Italics in Process Explorer), scintilla creates them out of regular or bold. Beside that it would be a disaster since SourcePro Italics does not support Cyrillic and Greek characters AFAIK.

**Comment by uli-a** [comment]
The fonts were installed before I used Notepad++ v6.8 and I did not see the included .otf file. I don't know which software installed the font, though.

**Comment by donho** [comment]
Your installed Source Code Pro font doesn't handle & well. Update it will fix this issue.

**Comment by h-h-h-h** [comment]
Reference: issue https://github.com/notepad-plus-plus/notepad-plus-plus/issues/729

**Comment by chindi-ap** [comment]
Under Style Configurator > Default(stylers.xml) > Font Style > select or de-select the "Bold" check-box will make the ampersand (&) operator appear and disappear.

![style configurator dialog box](https://cloud.githubusercontent.com/assets/14323130/9923214/c2570578-5d24-11e5-881e-ff6222a63077.jpg)

**Comment by donho** [comment]
@chindi-ap https://notepad-plus-plus.org/community/topic/9855/notepad-6-8-3-released

**Comment by h-h-h-h** [comment]
@donho: Just out of curiosity: Isn't the ever-growing number issues becoming an issue?

**Comment by donho** [comment]
@h-h-h-h Sorry, don't get you. Could you elaborate it?

**Comment by h-h-h-h** [comment]
@donho: The number of issues was first 100, then 200, 300, 400, and now nearly 500, whereas the progress of closed issue was much slower. I was wondering whether at some point in the future there are so many topics of issues that users wanting to report issues just need to comment on existing ones, or if the number of issues won't stop growing.

**Comment by donho** [comment]
@h-h-h-h I'll do my best to close them.

**Comment by h-h-h-h** [comment]
@donho: Fine! :+1:

**Comment by faiyip** [comment]
hi, I was having the same issue with javascript file.  I backup my stylers.xml , and then close notepad++, and delete the stylers.xml.  Once notepad++ open, the problem is gone.  I am using 6.8.8 on windows 10.

**Comment by nshew** [comment]
FWIW, I see the same issue (non-displayed, bold "&") using Source Code Pro in PhpStorm. That would seem to indicate the font, not N++.

**Comment by dzenanz** [comment]
I have been hit by the same issue (ampersands not visible in C++ code). I noticed it after the most recent automatic update (I don't think it was here before). Suggestion from @faiyip helped (deleting stylers.xml). I am on Win7 x64.

**Comment by thenakos** [comment]
Well it is 2017 and still happening. I changed the style te Helly Kitty and it shows & since then... jk I use some serious design, but still... it is funny how a font called "Source Code Pro" kills one of the most important symbols :D
