### ISSUE TITLE
Valid Regex expression marked as invalid

### ISSUE THREAD

**Issue by Mohammad-Haris** [notepad-plus-plus/notepad-plus-plus#5474]
### Shows syntax error on a syntactically correct Regex expression.
Regex expression, specifically look behind assertion not working as expected.
I'm not so sure about the correctness of the syntax, as RegExr and Regex101 show error but expression works in VS Code and Regexstorm. Seems pretty correct to me though. I think it is a JavaScript issue with RegExr and Regex101.

### Steps to Reproduce the Issue

1. Write the following lines in a text file:
> somespecificword first second specificword select
somespecificword first second third specificword toselect
somespecificword first second third fourth specificword selection

2. Write the following Regex expression in the find dialog box with _Regular expression_ checked:
`(?<=somespecificword .* specificword )(.*)`

3. Click _Find Next_.

### Expected Behavior

Last word of each line should be selected on each subsequent _Find Next_.

### Actual Behavior

Notepad++ marks expression as syntactically incorrect.
> Find: Invalid regular expression

### Debug Information

Notepad++ v7.5.9   (64-bit)
Build time : Oct 14 2018 - 15:19:55
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 7 (64-bit)
Plugins : DSpellCheck.dll mimeTools.dll NppConverter.dll 

### Screenshot
![image](https://user-images.githubusercontent.com/34305911/55289411-f6816b80-53df-11e9-83d0-7019a451e7db.png)

**Comment by Ekopalypse** [comment]
Npp uses [boost::regex](https://www.boost.org/doc/libs/1_69_0/libs/regex/doc/html/boost_regex/syntax/perl_syntax.html#boost_regex.syntax.perl_syntax.lookbehind)
Lookbehind must be of fixed length

**Comment by Mohammad-Haris** [comment]
@Ekopalypse Thanks for the info.
