### ISSUE TITLE
.json

### ISSUE THREAD

**Issue by usereewrjrjeejr** [notepad-plus-plus/notepad-plus-plus#5475]
How do I get notepadd++ to always up .json files?

**Comment by rddim** [comment]
What do you mean?

**Comment by Tmp341** [comment]
I guess he means opening it with Npp++ default by double click.

**Comment by MetaChuh** [comment]
@usereewrjrjeejr 

unfortunately we do not have your debug information, so here is a more extensive guide how to open your .json files with a double click in windows explorer:

* close notepad++ if it is open

* right click on any .json file and choose `open with > choose other app` and select notepad++ from this list.

* select `always use this app to open .json files`and hit ok.

* close notepad++ again and retry opening your .json file by double clicking on it.

if you are not able to select notepad++.exe form the choose other app list above:

* close notepad++ if it is open

* right click on your notepad++ icon and choose "run as administrator"
(make sure you see `[Administrator]` at the top bar of your notepad++ window (see screenshot)

* go to `settings > preferences > file association` and make sure your needed extensions, like .json are visible at the registered extensions panel (last panel on the right) as seen on this screenshot:

![Imgur](https://i.imgur.com/m0St1R0.png)

* hit close and exit notepad++

* now reopen notepad++ normally, and go to `settings > preferences > file association` again, and make sure your needed extensions are also visible for the standard user account.

* then exit notepad++ again

* right click on any .json file and choose `open with > choose other app` and select notepad++ from this list.

* select `always use this app to open .json files`and hit ok.

* close notepad++ again and retry opening your .json file by double clicking on it.

-----

```
general notes:

please mark your issue as solved, as soon as you are satisfied, to help keeping the
notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).
```
