### ISSUE TITLE
Remove unnecessary null pointer checks

### ISSUE THREAD

**Issue by elfring** [notepad-plus-plus/notepad-plus-plus#5476]
[An extra null pointer check is not needed in functions](https://isocpp.org/wiki/faq/freestore-mgmt#delete-handles-null "Do I need to check for null before delete p?") like the following.
- [Accelerator](https://github.com/notepad-plus-plus/notepad-plus-plus/blob/52a4e21af5c7197926cf32a45f4b96f015ccc2d3/PowerEditor/src/WinControls/shortcut/shortcut.h#L356 "Destructor for Accelerator")
- [AutoCompletion](https://github.com/notepad-plus-plus/notepad-plus-plus/blob/ef13902206f80e00dcfd7d85b342066ed6f86d66/PowerEditor/src/ScitillaComponent/AutoCompletion.h#L64 "Destructor for AutoCompletion")
- [main](https://github.com/notepad-plus-plus/notepad-plus-plus/blob/ef13902206f80e00dcfd7d85b342066ed6f86d66/PowerEditor/src/tools/xmlUpdater/xmlUpdater.cpp#L206 "main() function")

**Comment by dail8859** [comment]
For code changes please open a pull request that can be reviewed.
