### ISSUE TITLE
Split screen mode, window does not maintain postion

### ISSUE THREAD

**Issue by dwhawkins** [notepad-plus-plus/notepad-plus-plus#548]
When using spit screen mode and multiple tabs are open in each screen, sometimes switching between left and right screens, the scroll position will go back to top of page when returning back to other screen.  This doesn't always happen.  But once it starts it continues to happen.  Sometimes closing Notepad++ solves the problem, sometimes not.  Sometimes reducing the number of tabbed windows fixes the problem.

**Comment by mgroetan** [comment]
Happens without split screen mode as well, but with many tabs. Still behaves this way with just 11 open tabs. Using 6.7.9.2 version.

**Comment by milipili** [comment]
Indeed. Could you check without any plugins ?

**Comment by donho** [comment]
I believe this issue has been fixed since long time ago.
Update your Notepad++ to the latest version (v7.6.6).
If the issue persists, please create a new issue for it.
Thank you.
