### ISSUE TITLE
In offical website, it is not appropriate to use a national flag to represent all countries that use the language

### ISSUE THREAD

**Issue by CHN-STUDENT** [notepad-plus-plus/notepad-plus-plus#5480]
![image](https://user-images.githubusercontent.com/21209416/55445670-0a4eec80-55ef-11e9-909b-12a07d37fe6b.png)

@donho 

Np++ is a nice software. But we think it is not appropriate to use a national flag to represent all countries that use the language. **Please do not cause ambiguity and unnecessary disputes.**

**And when referring to a language, general standards should be used like zh-cn (Simplified Chinese) or zh-tw(Traditional Chinese).**

Please fix this problem.
~~Please respond as soon as possible.~~

Thanks.

see here:https://notepad-plus-plus.org/community/topic/17339/%E5%82%BB%E9%80%BC%E8%BD%AF%E4%BB%B6%E5%90%A7-%E4%B8%AD%E6%96%87%E6%8C%89%E9%92%AE%E6%94%BE%E7%9A%84%E4%BB%80%E4%B9%88%E5%9B%BD%E6%97%97

**Comment by donho** [comment]
The site is in traditional Chinese but not in simplified Chinese, so the flag is Taiwan flag but not China flag.

**Comment by CHN-STUDENT** [comment]
@donho No i mean if you use taiwan's flag to refer to traditional Chinese, you should use "traditional Chinese" not only "Chinese" . I am sure you will know why it leads to the uprising

**Comment by donho** [comment]
I’ve got your point.
With your argument, I should change “English” to “British English”

**Comment by CHN-STUDENT** [comment]
If you think notepad++ website does not have simplified Chinese so using Taiwan's flag means traditional Chinese (Chinese). I can do help you to do it free of charge. 

And almost software and website use zh-cn (Simplified Chinese) or zh-tw(Traditional Chinese) mean 简体中文 and 繁体中文

If you need, i can do this.

Because i am one of notepad++ users.

Thanks!


![image](https://user-images.githubusercontent.com/21209416/55470488-4eb3aa00-563a-11e9-97d4-7550b8a73033.png)

**Comment by DavidHansen-0x454d43** [comment]
@donho, having studied in both mainland China and Taiwan, I can appreciate @CHN-STUDENT's point. Its a little different than British vs American English, because Simplified and Traditional Chinese often use a completely different character encoding (GB vs Big5). 

If CHN-STUDENT was advocating the removal of the Taiwan flag, then I'd say it was politically motivated... but I have to agree that just using "Chinese" is ambiguous and that the standard is to specify whether it is Traditional or Simplified. 

That being said, I think little China is best China! Long live Taiwan ;D

**Comment by CHN-STUDENT** [comment]
@DavidHansen-0x454d43 Thanks for your opinion. Because of the reason, we know if we can not handle this problem better, it will leads to the ambiguity.

I think my opinion to provide detailed description of language and region by using the  current standard won't make this trouble. Almost people do same thing, so i hope the author would like to do this too.

Perhaps i am a Chinese, so you will think i do this thing as politically motivated. **No! As a notepad++ user, i really to want to it be better.**  If this problem can be solved very well, There will be more people using notepad++ and praise the author's contribution. 

That being said,Enjoying in China or Taiwan as a passenger.
