### ISSUE TITLE
Add offical website Chinese translate version

### ISSUE THREAD

**Issue by CHN-STUDENT** [notepad-plus-plus/notepad-plus-plus#5481]
This is Simplified Chinese translation.

About
关于 Notepad++

Notepad++ is a free (as in "free speech" and also as in "free beer") source code editor and Notepad replacement that supports several languages. Running in the MS Windows environment, its use is governed by GPL License.
Notepad++ 是一款 Windows 环境下遵循 GPL 协议开源代码编辑软件。

Based on the powerful editing component Scintilla, Notepad++ is written in C++ and uses pure Win32 API and STL which ensures a higher execution speed and smaller program size. By optimizing as many routines as possible without losing user friendliness, Notepad++ is trying to reduce the world carbon dioxide emissions. When using less CPU power, the PC can throttle down and reduce power consumption, resulting in a greener environment.
Notepad++ 使用 C++ 语言编写，使用编辑组件 Scintilla 作为框架，并且使用系统原生 API 和 STL 容器实现的轻量化软件，以便能够更快更轻便运行在您的电脑上，方便您使用。

You're encouraged to translate Notepad++ into your native language if there's not already a translation present in the Binary Translations page.
欢迎您将软件翻译成自己的语言。

I hope you enjoy Notepad++ as much as I enjoy coding it.
感谢您使用这款软件。

**Comment by donho** [comment]
Thank you for your translation.
However, the site content doesn't accept the contribution.

**Comment by CHN-STUDENT** [comment]
yeah it is your chosen. I accpet.

Thank you for listening.
