### ISSUE TITLE
Feature request: Increase font size in npp gui itself (fix or as new option)

### ISSUE THREAD

**Issue by wedman1968** [notepad-plus-plus/notepad-plus-plus#5486]
### Description of the Issue
I need to increase the font size in the npp gui (navigation bar , menus …) itself (like File, Edit, Search…) and all native npp dialog boxes (like preferences, find …) due of ergonomics reasons. In the moment the font size is fix defined in the code with 8 px high.

There are handicap people working in our company with npp. They have big troubles while using npp with the small font size of 8 px. Please see also Standard ISO 9241-303 – 5.5.4

Can you please make some investigations how it can be solved

1)  increase char size in code fix just from now 8px to 9px (or 10px); that would be good enough for ISO 9241-303 – 5.5.4, and could be changed fast in the code

2) create new possibility to choose gui char size from a fixed set of standard sizes (normal (8px) or high (10px)  / small (8px) - normal (9) - high (10px)) 
I assume that the effort is a little big greater than in 1), but there would be more comfort for the users.

3) create new possibility for the users to define font size in the gui completly free
Example: Opensource software "freeplane" (mind mapping) 
I suspect that the effort therefor is high, and this would create some other impacts and is not a good solution at all. 
 

P.S.
 I know the hack of the notepad++.exe with the Resource Hacker tool, but this is annoying to to do every build release, and I didn’t find there every gui element .

### Steps to Reproduce the Issue

1. 
2. 
3. 

### Expected Behavior

The font size in the npp gui is a little big greater than now (fix or as new possibility in preferences)

### Actual Behavior

The font size in the npp gui itself is too small for handicaped people.

### Debug Information

![Freeplane_Pref_Appearance_Menu_Size](https://user-images.githubusercontent.com/49236700/55544559-a2ba9f00-56cb-11e9-9107-c3e7790e687f.png)

**Comment by frost-byte** [comment]
Well at least some feedback was given on why this wouldn't be implemented...
