### ISSUE TITLE
Problem with antivirus in npp 7.6.6 x64

### ISSUE THREAD

**Issue by gerard-durand** [notepad-plus-plus/notepad-plus-plus#5487]
Antivirus software (or antimalware) erase notepad executable.

### Description of the Issue

When I execute npp 7.6.6 x64 the first time after installation, notepad++.exe in my "program files" and even the installer npp.7.6.6.Installer.x64.exe is destroyed. Probably a problem with an antivirus/antimalware software, but I don't know which one. I have McAfee LifeSafe, but also malwaresbytes and spybot (last releases) and my PC runs undes Windows 7. If I try to analyse individually the executables with each one, all is OK : no viruses nor malwares detected ! And when the exe are suppressed, I have no displayed messages, so I don't know which software installed on my PC cause the problem. Strange... So, I switched back to 7.6.4 version and all is OK again. 

### Steps to Reproduce the Issue

1. Install npp.7.6.6.Installer.x64.exe
2. execute Notepad++

**Comment by donho** [comment]
I guess it's more clear now.

![mcafee](https://user-images.githubusercontent.com/90293/55566697-8551f900-56fc-11e9-9589-abf069a9edc3.png)

**Comment by MetaChuh** [comment]
@gerard-durand 

> When I execute npp 7.6.6 x64 the first time after installation, notepad++.exe in my "program files" and even the installer npp.7.6.6.Installer.x64.exe is destroyed ...

> ... but I don't know which one. I have McAfee LifeSafe, but also malwaresbytes and spybot

neither the notepad++ installer, nor any content of it, has a false positive trigger on any of the currently 71 anti virus/anti malware engines, used by the [<kbd>virustotal.com</kbd>](https://www.virustotal.com) service, including mcafee.
(see screenshot and links below)

so we couldn't really tell what's the reason for this on your machine, and i don't recall any similar reported incidents.

![Imgur](https://i.imgur.com/qGetNE5.png)

detailed [<kbd>virustotal.com</kbd>](https://www.virustotal.com) reports:

npp.7.6.6.Installer.x64.exe:
[<kbd>www.virustotal.com/#/file/f19f407f0c2ec95f176f09df7816b6382b8ebad7e6d69004221e4a3d078a7add/detection</kbd>](https://www.virustotal.com/#/file/f19f407f0c2ec95f176f09df7816b6382b8ebad7e6d69004221e4a3d078a7add/detection)


npp.7.6.6.Installer.exe:
[<kbd>www.virustotal.com/#/file/9582fec10e6ca488ab506a96dfeb5da56c9425ca32a8481e060bd06893fb1b3e/detection</kbd>](https://www.virustotal.com/#/file/9582fec10e6ca488ab506a96dfeb5da56c9425ca32a8481e060bd06893fb1b3e/detection)

**Comment by lf-novelt** [comment]
Where did you download your installer from? Was the https certificate secured (no warning) when you went on notepad-plus-plus.org?
Maybe you were the victim of a man in the middle attack, so can you give us the hashsum of the exe you downloaded or compare it to the one in https://notepad-plus-plus.org/repository/7.x/7.6.6/npp.7.6.6.checksums.sha256

**Comment by gerard-durand** [comment]
I have downloaded the installer from official site https://notepad-plus-plus.org/download/v7.6.6.html and the npp.7.6.6.Installer.x64.exe sha-256 is the same the one found with your link : SHA256: F19F407F0C2EC95F176F09DF7816B6382B8EBAD7E6D69004221E4A3D078A7ADD
So the problem is obviously somewhere on my PC with an antivirus and/or antimalware software (a false positive !). But as told previously, when I check the files with each of these software, they declare the installer and the notepad++.exe file as clean.

**Comment by Tinase-nau** [comment]
But what about Windows Defender? There may be additional scanner present too somewhere.
BUT have you checked log files of each AV tool? Usually they keep logs of their activity. Unless they are really poorly designed, or you disabled logging.
As an alternative, with Process Monitor you can figure out what exactly deletes N++ executables.
https://docs.microsoft.com/en-us/sysinternals/downloads/procmon

**Comment by gerard-durand** [comment]
Windows defender is not activated on this PC. As version 7.6.4 works without problems, I think I'll wait the next version. If I have still the problem, I'll try to investigate more deeply.

**Comment by donho** [comment]
It's not Notepad++ issue, therefore it's closed.
