### ISSUE TITLE
Feature Request: Return previous finding mechanism

### ISSUE THREAD

**Issue by Tinase-nau** [notepad-plus-plus/notepad-plus-plus#5492]
### Description of the Issue
Notepad++ v7.6.6 lacks ability to Find in whole file. Now it Finds from cursor position to end of file only. Which means if I want to jump to all occurrences in whole file I now always have to set cursor back to beginning of file.
It's even more annoying to use Replace All feature! With current mechanism, it should say "Replace all from current cursor to end of file."
Loss of ability wastes valuable time. Who asked for this?
If this is intentional, could we have options to tell N++ to
1. Find to start from beginning of file if file end was reached?
2. Replace All to start from beginning of file?

### Steps to Reproduce the Issue
1. Have a text file where words repeat occasionally.
2. Set cursor in middle of file.
3. Either 1. Find to find some string, or 2. Replace All to replace all occurrences of a string.

### Expected Behavior
1. For Find to jump next occurrence starting from top if file end was reached.
2. Replace All to actually replace all and not from cursor to end of file only.

### Actual Behavior
1. Stops at end of file.
2. Replaces only from cursor to end of file.

### Debug Information
Notepad++ v7.6.6   (32-bit)
Build time : Apr  3 2019 - 23:49:50
Path : J:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : ON
Local Conf mode : OFF
OS : Windows 7 (64-bit)
Plugins : DSpellCheck.dll mimeTools.dll NppConverter.dll NppExport.dll

**Comment by Ekopalypse** [comment]
Are you sure you haven't, accidentally, unchecked the **wrap around** flag in find window?

**Comment by sasumner** [comment]
People should learn to read and understand the user interface.

**Comment by Tinase-nau** [comment]
Ahh, so that's what "Wrap around" does. Never knew. Doesn't show a hint. 
I am unable to locate anything related to help manual in N++. Under which function is it?

**Comment by sasumner** [comment]
Please close this issue.
