### ISSUE TITLE
[Feature Request] Use "Ctrl" + "[" "]" To Indent Line

### ISSUE THREAD

**Issue by alienfxfiend** [notepad-plus-plus/notepad-plus-plus#5493]
### Description of the Issue

The above shortcut to quickly indent a line wherever the caret may be. The one feature of Brackets editor (JS-based) which is missing in Notepad++ —would be nice. Currently you have to hit Home or select the line & hit Tab key. Please add this in a future update, would save me tons of effort while coding [for AutoHotkey.] Ctrl + ] moves the tab indentation (current line) forward while Ctrl + [ moves it backwards. Thanks in advance.

### Steps to Reproduce the Issue

1. 
2. 
3.

**Comment by sasumner** [comment]
Sure, but while you are waiting have you considered writing a script to get this functionality?

**Comment by alienfxfiend** [comment]
> 
> 
> Sure, but while you are waiting have you considered writing a script to get this functionality?

If only I knew how to...

**Comment by sasumner** [comment]
So here's a short Pythonscript that does the "indent" case.  You'd need a second script for the "dedent" case, but the logic for that is also included in the script.

    indent_not_dedent = True
    cp = editor.getCurrentPos()
    lfp = editor.lineFromPosition(cp)
    tw = editor.getTabWidth()
    li = editor.getLineIndentation(lfp)
    if indent_not_dedent:
        new_col = ((li / tw) + 1) * tw
    else:
        new_col = ((li - 1) / tw) * tw
        if new_col < 0: new_col = 0
    editor.setLineIndentation(lfp, new_col)

**Comment by MetaChuh** [comment]
and here's the
[<kbd>Guide: How to install the PythonScript plugin on Notepad++ 7.6.3, 7.6.4 and above</kbd>](https://notepad-plus-plus.org/community/topic/17256/guide-how-to-install-the-pythonscript-plugin-on-notepad-7-6-3-7-6-4-and-above)
in case you are on notepad++ 7.6.3 or higher.

-----
```
general notes:

please close your issue as soon as you are satisfied,
to help keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).
please also do some searching of the issues beforehand, to check if a similar issue
already exists. (sas)

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and first
search if a related topics exists. you are welcome to post at either an eventually similar
topic, or create a new topic at Help Wanted or General Discussion of your choice.
```
[<kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd>](https://notepad-plus-plus.org/community/)

**Comment by alienfxfiend** [comment]
> 
> 
> So here's a short Pythonscript that does the "indent" case. You'd need a second script for the "dedent" case, but the logic for that is also included in the script.
> 
> ```
> indent_not_dedent = True
> cp = editor.getCurrentPos()
> lfp = editor.lineFromPosition(cp)
> tw = editor.getTabWidth()
> li = editor.getLineIndentation(lfp)
> if indent_not_dedent:
>     new_col = ((li / tw) + 1) * tw
> else:
>     new_col = ((li - 1) / tw) * tw
>     if new_col < 0: new_col = 0
> editor.setLineIndentation(lfp, new_col)
> ```

Thanks, but without specific instructions, I don't know how to do this. I'll wait for the feature to be added.

**Comment by sasumner** [comment]
@alienfxfiend said:

>I'll wait for the feature to be added

Well...did you know that probably most feature requests get passively denied by inaction?  So, you can either take the (small amount of) time to figure out how to do scripting and have your desire TODAY...or you can wait/hope/pray it is implemented in the future, with the full foreknowledge that it may NEVER be implemented.

I for one am already happily using the above script.  Note (if you decide to use it) that it should only be run for indent/dedent of the SINGLE line of the caret.  If you make a selection across multiple lines and then expect the script to work on ALL of the selected lines, it won't.  And there's a good reason for that: If you have a selection that (even partially!) covers more than one line, pressing the Tab key (or Shift+Tab) will perform the desired action.  It is only for the single line case that the script is necessary.

>Or please provide full code for both

No idea what you mean by this.

**Comment by alienfxfiend** [comment]
OK thanks I will try it out !

**Comment by alienfxfiend** [comment]
Thank you very much !

**Comment by sasumner** [comment]
@alienfxfiend So... @tojaroslaw created a PR. This means nothing to seeing a change in a Notepad++ release. Unless a Notepad++ developer reviews it and agrees with it and decides to merge it into the master sources. So probably closing this issue was premature.

**Comment by sasumner** [comment]
Originally I thought there was more to this request, but after looking at the proposed PR my thinking is now that this is just an end-user *Shortcut Mapper* configuration?  Am I missing something?

**Comment by donho** [comment]
The PR doesn't work for 2 points:
1. Ctrl is not even set.
2.  "Ctrl" + "[" "]" have already taken. So please find another shortcut and create a new request with the available shortcut.

**Comment by xylographe** [comment]
@alienfxfiend 
1. Open the ‘Plugins Admin’ dialogue (**Plugins > Plugins Admin...**).
2. Install LuaScript plug-in.
3. Select **Plugins > LuaScript > Edit Startup Script**.
4. Add following lines to the Startup Script, and save the file (**File > Save**).
```lua
-- Mimic Brackets editor's "Ctrl+]"
npp.AddShortcut("Increase Indentation", "Ctrl+]", function()
  local pos = editor.CurrentPos
  local lnn = editor:LineFromPosition(pos)
  local ipos = editor.LineIndentPosition[lnn]
  editor.LineIndentation[lnn] = editor.LineIndentation[lnn] + editor.TabWidth
  editor.CurrentPos = pos - ipos + editor.LineIndentPosition[lnn]
end)

-- Mimic Brackets editor's "Ctrl+["
npp.AddShortcut("Decrease Indentation", "Ctrl+[", function()
  local pos = editor.CurrentPos
  local lnn = editor:LineFromPosition(pos)
  local lni, tw = editor.LineIndentation[lnn], editor.TabWidth
  if tw <= lni then
    local ipos = editor.LineIndentPosition[lnn]
    editor.LineIndentation[lnn] = lni - tw
    editor.CurrentPos = pos - ipos + editor.LineIndentPosition[lnn]
  end
end)
```
5. Restart Notepad++ to activate the modified LuaScript Startup Script.
6. Verify the new entries in **Plugins > LuaScript** menu.
6. Open the ‘Shortcut mapper’ dialogue (**Settings > Shortcut Mapper...**).
7. Select ‘Scintilla commands’ tab.
8. Change or clear the shortcuts for SCI_PARAUP and SCI_PARADOWN.

**Comment by alienfxfiend** [comment]
Thanks you so much, that worked !!!

**Comment by sasumner** [comment]
Sigh, not enough gumption to put any effort into the Pythonscript solution provided 3 months ago...wanted to be spoon-fed...I guess they got that.
