### ISSUE TITLE
Notepad++ doesn't record menu operations in macro

### ISSUE THREAD

**Issue by Lokiare** [notepad-plus-plus/notepad-plus-plus#5494]
### Description of the Issue

When trying to record a DSpellCheck (find next misspelled word) macro using the menu, it doesn't record anything.

### Steps to Reproduce the Issue

1. Install DSpellCheck plugin
2. Macro->Record then Plugins->DSpellCheck->Find Next Misspelling
3. Macro->Stop Recording

### Expected Behavior

I expected the macro to be recorded and to get to name the macro and set it to a hotkey

### Actual Behavior

Macro was not recorded.

### Debug Information

Notepad++ v7.6.5   (32-bit)
Build time : Mar 29 2019 - 02:46:18
Path : E:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10 (64-bit)
Plugins : DSpellCheck.dll mimeTools.dll NppConverter.dll NppExport.dll NPPParsePlugin.dll

**Comment by MetaChuh** [comment]
@Lokiare 

unfortunately you can not record external plugin menu items like `plugins > dspellcheck > find next misspelling` as a macro.

if it suffices you, to have a keyboard shortcut for `find next misspelling`:
go to `settings > shortcut mapper > plugin commands`,
enter `spell` at the search filter,
double-click on `find next misspelling` and set a keyboard  shortcut that is not yet used,
e.g. <kbd>ctrl</kbd>+<kbd>alt</kbd>+<kbd>f1</kbd>.
