### ISSUE TITLE
Extension problem

### ISSUE THREAD

**Issue by Klubenn** [notepad-plus-plus/notepad-plus-plus#5496]
### Description of the Issue

The extension of the newly made file does not apply even when you choose one from the drop-down menu. It is still needed to type it manually after the name of the file

### Steps to Reproduce the Issue

1. New file
2. Save as
3. Set file type to Normal text file (*.txt)
4. Save

### Expected Behavior

The file should be saved as txt file with *.txt extenion

### Actual Behavior

The file was saved without extension

### Debug Information

Notepad++ v7.6.6   (32-bit)
Build time : Apr  3 2019 - 23:49:50
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10 (64-bit)
Plugins : mimeTools.dll NppConverter.dll NppExport.dll 

https://ibb.co/gyQDfLy
https://ibb.co/rZgMLHX

**Comment by rddim** [comment]
Uncheck the `Settings` > `Preferences...` > `Default Directory` > `Use new style dialog`

**Comment by Klubenn** [comment]
> Uncheck the `Settings` > `Preferences...` > `Default Directory` > `Use new style dialog`

Thank you for explanation. This setting wasn't obvious at all, so i'd suggest making this box unchecked by default.

**Comment by MetaChuh** [comment]
referenced to: https://github.com/notepad-plus-plus/notepad-plus-plus/issues/5495
