### ISSUE TITLE
Broken folding when using LF instead of CRLF. [N++ v. 7.6.6 64-bit]

### ISSUE THREAD

**Issue by Fiooodooor** [notepad-plus-plus/notepad-plus-plus#5499]
### Description of the Issue
When using custom language settings the folding won't work with defined delimiter and EOL symbol set to Linux-style **LF**. Works ok with Windows-style end of line **CR LF**. The same as issue nr #350. 

### Steps to Reproduce the Issue

1. Define custom language with 'folding in code 1 style' opener '**{**' and closure '**}**'. 
2. Define 'delimiter 1 style' with opener and closure set to quotation marks (the **"** sign). 
3. Preview a sample file with EOL defined as 'LF' sign.

### Expected Behavior

Begin and end of folding in lines containing the '{' and '}' signs.

### Actual Behavior
Folding behave randomly and change dynamically depending on changes made to the document. Example with user-defined language and only two setted as bellow:
'**Folding in code 1 style**' to 
**open**: { 
**close**: } 
'**Delimiter 1 style**' to
**open**: " 
**close**: " 
![notepadpp_7_6_6](https://user-images.githubusercontent.com/45114904/55738608-b8abc500-5a27-11e9-8abe-9cd00ac02403.png)
.

### Debug Information

Notepad++ v7.6.6   (64-bit)
Build time : Apr  3 2019 - 23:52:32
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10 (64-bit)
Plugins : mimeTools.dll NppConverter.dll 

Deleting all the 'tab' symbols changes the behavior of folding mechanism, but all the time the detection of open and close symbol works fine as in the image below:
![notepadpp_7_6_6_1](https://user-images.githubusercontent.com/45114904/55739064-9c5c5800-5a28-11e9-823b-d303acea771c.png)

**Comment by rmcurtis** [comment]
Also see #2873 and #3372 for similar (maybe duplicate?) issues.

I've confirmed this issue still persists in 7.6.6.

**Comment by lifenjoiner** [comment]
I also met this with NPP v7.6.6 on win7 and win10.

Reproducing can be generated as Fiooodooor descripts in "Actual Behavior". But I think mess up is not randomly:
![NPP-folding-bug-scr](https://user-images.githubusercontent.com/19585474/57616192-21023f00-75b0-11e9-8759-1b189b1fc0d9.png)

**Comment by bReathl3sS** [comment]
Very annoying issue and it was very hard to find out what the problem was causing. UDL folding works with CRLF but not with LF. With LF very strange things occur depending on whether you have blank space/tab stops, indenting, mixed CR/LF, ...
Still persists in 7.9.1

**Comment by Diogo-Rossi** [comment]
Still persists in N++ 7.9.5

**Comment by Fiooodooor** [comment]
As I mentioned, the bracket highlighting works as expected, so shouldn't it be used as algorytm for items folding?
