### ISSUE TITLE
Document List Panel - add move from file to file by arrow keys

### ISSUE THREAD

**Issue by szegi** [notepad-plus-plus/notepad-plus-plus#55]
It would be nice feature i guess
to add moving from file to file just by using arrow keys when focus on
Document List Panel

**Comment by MetaChuh** [comment]
closed due to:
switching from file to file in doc switcher, aka. document list panel, with a keyboard is done with:
<kbd>ctrl</kbd>+<kbd>page up</kbd> and <kbd>ctrl</kbd>+<kbd>page down</kbd>
 (tab switching)
