### ISSUE TITLE
Confusing "Remove unmarked lines"

### ISSUE THREAD

**Issue by wilkowy** [notepad-plus-plus/notepad-plus-plus#5502]
```
<Item id="43021" name="Remove Bookmarked Lines"/>
<Item id="43051" name="Remove Unmarked Lines"/>
```
The "Remove Unmarked Lines" is confusing and it should state "remove not bookmarked lines" as it has nothing to do with marking from find/replace menu, unless bookmarking is checked. (yes, I know it is in "Bookmark" submenu, but still…)

**Comment by alankilborn** [comment]
Tested in N++ 8.4.4 (current version as of this writing) and the problem still exists.
Could someone change the English text to be different (i.e., better) than `Remove unmarked lines` (see suggestions above)?

**Comment by ArkadiuszMichalski** [comment]
Fixed by https://github.com/notepad-plus-plus/notepad-plus-plus/pull/13149.
