### ISSUE TITLE
Idea for ADS NTFS and other)))

### ISSUE THREAD

**Issue by YaShumoff** [notepad-plus-plus/notepad-plus-plus#5505]
I don `t know where to write ideas, I hope correctly =)
1) In general, in the NTFS file system there are "Alternative Data Streams" that are not visible. Add a button(?) or simply display the list of threads in the file. (Or is this already in the program?) =)
The cunning people thrust an alternative stream into the text file and it would be more convenient to work if it were possible to quickly switch them.
2) The simplest hex editor. Am I completely crazy?? This is a code editor! =D
3) Automatic definition of syntax by "features" in the code.

**Comment by MetaChuh** [comment]
@YaShumoff 

thank you for sharing your ideas.

the right place for ideas would be our notepad++ community, to work them out with a wider audience of developers and power users, and to check if they are of relevance for the majority of notepad++ users around the world.

once all ideas have been verified to be of interest to the community, and possible ways of implementing them have been worked out, please come back here and file another issue.

-----
```
general notes:

please close your issues as soon as you are satisfied,
to help keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post at either an eventually similar
topic, or create a new topic at Help Wanted or General Discussion.
```
[<kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd>](https://notepad-plus-plus.org/community/)

**Comment by YaShumoff** [comment]
1) Do you mean this? https://notepad-plus-plus.org/community/
2) How to register there? (sorry, maybe I'm blind))).
3) What topic should I write? "General Discussion"?
Thanks for the answers! =)

**Comment by MetaChuh** [comment]
1. yes, this is the link provided above (the long button with the text "click here to visit the notepad++ community forum")
2. you don't have to. just press login and select your github account (click on the icon that looks like a cat)
3. general discussion is good.
please don't forget to ask for the community user's opinion about ideas, to get a feedback from a wider range of people.

**Comment by YaShumoff** [comment]
Thanks for the tips, you quickly respond)))
It says here I have to close the topic, but I don `t know how to do it, sorry.
