### ISSUE TITLE
[Suggestion] Purge undo & redo buffer manually

### ISSUE THREAD

**Issue by ft525** [notepad-plus-plus/notepad-plus-plus#5507]
When I coding to a stable stage,
I usually reload the file to reset the undo & redo buffer, then continue to next coding stage.
But now notepad++ can't do this.

Is there any way to purge undo & redo buffer manually?
Or make an option let us choose what clear or keep the undo & redo buffer when reloading the file.

**Comment by wqweto** [comment]
You can try <kbd>Ctrl</kbd>+<kbd>W</kbd> and <kbd>Alt</kbd>+<kbd>F</kbd>, <kbd>1</kbd> to close and reopen last closed file.

**Comment by MetaChuh** [comment]
@ft525 
<kbd>ctrl</kbd>+<kbd>w</kbd> followed by <kbd>ctrl</kbd>+<kbd>shift</kbd>+<kbd>t</kbd> will also close and reopen a file, causing the undo buffer to be flushed.

note: a manual purge feature will probably not be implemented, but we will leave this request open for brain storming ideas for a while.

one of the main reasons of the new feature "keeping the undo buffer after a reload", is to prevent editing loss, when a file was reloaded by accident.
a "counter feature" to purge the undo buffer would currently contradict this design.

@wqweto 
very good cross thinking 👍

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
(no extra account is needed, just use your github account to sign in)
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)
