### ISSUE TITLE
Show actual encoding instead of ANSI (was: #987)

### ISSUE THREAD

**Issue by Lin-Buo-Ren** [notepad-plus-plus/notepad-plus-plus#5508]
### Description of the Issue
The reference of "ANSI" in the encoding menu is a [Microsoft historical mistake](http://stackoverflow.com/questions/701882/what-is-ansi-format) and should be renamed as the proper charset used by the system codepage.

![screenshot](https://user-images.githubusercontent.com/13408130/55853142-62a76080-5b92-11e9-8d90-8ae7414c4d2c.png)

### Debug Information
```
Notepad++ v7.6.6   (64-bit)
Build time : Apr  3 2019 - 23:52:32
Path : Z:\home\brlin\snap\notepad-plus-plus\202\notepad-plus-plus\notepad-plus-plus.exe
Admin mode : ON
Local Conf mode : OFF
OS : Windows 7 (64-bit)
Plugins : mimeTools.dll NppConverter.dll 
```

**Comment by donho** [comment]
What's your suggestion?

**Comment by Lin-Buo-Ren** [comment]
@donho Display whatever the charset is used by the system codepage, for example on CP950 environment it should display `BIG5`.

**Comment by donho** [comment]
> @donho Display whatever the charset is used by the system codepage, for example on CP950 environment it should display `Encode/Convert to BIG5`.

It'll be difficult  technically to display current codepage dynamically.
I would say "current codepage" instead of ANSI, which is more correct, but the term might be less familiar for the users. Let's keep this misleading term to continue to guide users correctly.

**Comment by Lin-Buo-Ren** [comment]
> It'll be difficult technically to display current codepage dynamically.

Isn't that making a known codepage `<->` encoding mapping and fallback to "current codepage" sufficient to fix this problem?  Not that I am currently able to make a patch for it but this seems rather straightforward to me, just my two cents.
