### ISSUE TITLE
Legibility of characters typed in the find/replace dialog

### ISSUE THREAD

**Issue by ghost** [notepad-plus-plus/notepad-plus-plus#5509]
### Legibility of characters typed in the find/replace dialog
This is derived from [Issue 449](https://github.com/notepad-plus-plus/notepad-plus-plus/issues/449), which has been recently closed because the version back in 2015 was 6.7. The suggestion, albeit not implemented, was and is still relevant. Here it goes:

I love Notepad++ but it appears that it's a little more difficult to use the find/replace dialog as it was supposed to be. Specially for us getting old, reading the input field in that default (unchangeable, as far as I know) font is hard. Especially when we're typing a regex, sometimes I can't see if I typed that pipe in the right place. So my suggestion is: allow us to change that font in the "find" field to a more readable, monospace font.

### Steps to Reproduce the Issue
1.  Open any file;
2. Hit Ctrl+F
3. Type something into the search box.

### Expected Behavior
User can easily read what was just typed.

### Actual Behavior
User cannot easily read what was just typed because of the proportional font used by the search/replace dialog, which was supposed to be a monospaced type.

### Debug Information
Notepad++ v7.6.6   (64-bit)
Build time : Apr  3 2019 - 23:52:32
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10 (64-bit)
Plugins : DSpellCheck.dll mimeTools.dll NppConverter.dll 

![difficulty](https://user-images.githubusercontent.com/4718797/55858054-1255e180-5b45-11e9-94fc-b9a3f2d1343a.jpg)

**Comment by sasumner** [comment]
I understand this pain.  If it continues to not be dealt with, perhaps this provides somewhat of a workaround:  https://notepad-plus-plus.org/community/topic/16743/find-window-font-size

**Comment by Rosseiro** [comment]
Thanks, I followed the instructions and applied the changes with the Resource Hacker. This was the result:
![consolas](https://user-images.githubusercontent.com/4718797/55900851-8375b300-5b9e-11e9-9cd0-d3d4d8fcc26e.jpg)
As you can see, changing that line will also change the font for all that dialog's elements. I agree this is a valid workaround, but that is still a valid suggestion for a future release: the remainder of the elements were supposed to stay in the default font.
Thanks!

**Comment by sasumner** [comment]
>(issue is) still a valid suggestion for a future release

Absolutely!

**Comment by alankilborn** [comment]
>reading the input field in that default (unchangeable, as far as I know) font is hard.

In Notepad++ 7.8.1, the ability to change the font was added as a preference setting:

![image](https://user-images.githubusercontent.com/77065706/182942561-521c7c96-7bdc-4056-adf0-957522757f9a.png)

At some later point in time, this setting was moved to the "Searching" subpage of the "Preferences":

![image](https://user-images.githubusercontent.com/77065706/182942791-f4975bd9-7c66-4d81-9f05-679169ab95af.png)

As a way exists to make the indicated area of the UI more readable (tick the box shown in yellow color), recommend CLOSURE of this item.

**Comment by donho** [comment]
The font size on text field of Find dialog has been increased since long time ago, so this issue has been fixed.
