### ISSUE TITLE
CMake syntax severly out of date

### ISSUE THREAD

**Issue by Flamefire** [notepad-plus-plus/notepad-plus-plus#5511]
Follow up of https://github.com/notepad-plus-plus/notepad-plus-plus/issues/732

### Description of the Issue
CMake highlighting and code folding is broken for newer (CMake 3.x) CMake language features. An example is `function`/`endfunction` which is not recognized as keywords and misses folding.

This is an upstream issue (scintilla) but could as well be fixed here. At least the function support should be added. Updating scintilla in the process would also be a good idea. 4.x branch uses c++17 so if this is not wanted using the latest 3.x with the patches applied would be great.

**Comment by Ekopalypse** [comment]
@Flamefire - npp 7.7 is available now, I assume this issue can be closed, right?

**Comment by Flamefire** [comment]
Was there any progress on this issue? I hadn't  seen it but can check if this is fixed

If you have a commit where this was fixed?

**Comment by Ekopalypse** [comment]
Yes, there was. Forgot to mention that npp 7.7. uses scintilla 4x now.

**Comment by Flamefire** [comment]
Checking the source this is still not resolved: https://github.com/notepad-plus-plus/notepad-plus-plus/blob/23dd65549a57c5d4fa0c2ab9afdc8eaa1bc11963/scintilla/lexers/LexCmake.cxx#L86

`function`/`endfunction` is not part of the lexer. I'll check with upstream

**Comment by Flamefire** [comment]
I created a feature request upstream: https://sourceforge.net/p/scintilla/feature-requests/1289/

Besides that new keywords from CMake 3 should also be supported. Scite uses https://sourceforge.net/p/scintilla/scite/ci/default/tree/src/cmake.properties to get them. Those can probably automatically converted to https://github.com/notepad-plus-plus/notepad-plus-plus/blob/master/PowerEditor/installer/APIs/cmake.xml and https://github.com/notepad-plus-plus/notepad-plus-plus/blob/master/PowerEditor/src/langs.model.xml

**Comment by donho** [comment]
> Besides that new keywords from CMake 3 should also be supported. 

Create a PR for adding the new keywords the it will be accepted.

**Comment by Flamefire** [comment]
Thanks, done. A patch for scintilla is available (see https://sourceforge.net/p/scintilla/feature-requests/1289/) but not yet applied upstream. I could apply it to the PR though. As it is likely to be accepted by scintilla it should not cause any trouble. Else wait for scintilla to accept the patches

**Comment by Flamefire** [comment]
Can this be left open until upcoming scintilla 3.16 is used? This will add the folding information for `function`

**Comment by sasumner** [comment]
>Can this be left open until upcoming scintilla 3.16 is used?

Think you mean Scintilla **_5_**.16

Given that N++'s Scintilla sat at 3.56 for years before moving to 5.14, it might be a long time before another such Scintilla component update is done...?

**Comment by Flamefire** [comment]
Yes, typo

But this issue cannot be resolved without that update
