### ISSUE TITLE
Linux vim displays [neol] of a file edited by notepad++ (v 7.5.9) 

### ISSUE THREAD

**Issue by jimchenphri** [notepad-plus-plus/notepad-plus-plus#5512]
### Description of the Issue
After a file (originally created in Linux with vim editor) has been modified and saved by Notepad++, opening the modified file in vim in Linux again and vim would warn about [noeol]. 

### Steps to Reproduce the Issue
1. From a CentOS 6.10 Linux terminal, use 'vim testEol' to create a simple new file (filename: testEol) with three lines of simple text. Note, version of vim is vim-enhanced-7.4.629-5.el6_8.1.x86_64
2. In vim, use ':wq' to save the file with 3 lines
3. From the  CentOS 6.10 Linux terminal: run command: cp -p testEol  testEol.bak
4. From Windows 10, launch Notepad++ v 7.5.9 
5. Open the file testEol created in Step 1 with Notepad++ (this file is accessed via Samba share)
6. Clicks line 4 (cursor is now at the begining of line 4), type some simple text in line 4.
7. (without press the ENTER key) use Ctrl+s to save the file
8. Close Notepad++
9. From the same CentOS 6.10 Linux terminal (used in Step 1), use 'vim testEol' to open the same file. Now we will see the '[noeol]' in vim
10. From the same CentOS 6.10 Linux terminal (used in Step 1), run the command: 
      diff testEol.bak testEol  
    we will see:  \ No newline at end of file

Note: if in Step 6 we do '6a', then the warning about '[noeol]' will not be displayed:
6a.  Clicks end of line 3 (cursor is now at the end of line 3) -> press ENTER key ->  type some simple text in line 4.

### Expected Behavior
Do not see the '[noeol]' in vim
Do not see "\ No newline at end of file" when running the Linux 'diff' command. 
Note: using step 6a we will get the Expected Behavior. 
[testEol.docx](https://github.com/notepad-plus-plus/notepad-plus-plus/files/3065183/testEol.docx)

### Actual Behavior
See the '[noeol]' in vim
See the "\ No newline at end of file" when running the Linux 'diff' command. 

### Debug Information
Notepad++ v7.5.9   (64-bit)
Build time : Oct 14 2018 - 15:19:55
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10 (64-bit)
Plugins : DSpellCheck.dll mimeTools.dll NppConverter.dll

**Comment by sasumner** [comment]
Notepad++ gives you the ability to NOT end a file with and end-of-line character.  It's a feature.  It isn't going to be changed to always have it there.

But personally I wish there was a configuration preference (ticked/unticked; unticked by default) to **Ensure line-ending at EOF**.  

If you agree with that, the you might want to rework your issue a bit and ask for that.  All the stuff about Linux showing some sort of warning is a complaint against Linux not adhering to Postel's Law rather than Notepad++ doing something wrongly.

**Comment by jimchenphri** [comment]
OK, If it is a feature to give a user the "ability to NOT end a file with and end-of-line character", then I agree with comment by sasumner. 

I would like to request the  configuration preference mentioned by sasumner. 

Thanks
jimchenphri

**Comment by sasumner** [comment]
> I would like to request the configuration preference mentioned by sasumner.

As I see the "won't fix" label has been added, I would not count on it.  Sad.  :(

**Comment by jimchenphri** [comment]
Another thought: if one looks at the differences between Step 6 vs. Step 6a, there is a very tiny difference, Unless a user is very meticulous, he will not be able to remember to put the cursor at the end of 3rd line and then press ENTER. So I would appeal to whoever put the 'nofix' label to re-consider. 
Thanks
jimchenphri

**Comment by sasumner** [comment]
Some choices:

- Turn on visible line-endings

- Script a solution that will add a missing line-ending if one is detected upon file save (if there is interest, I can provide such a script as I already have one)

**Comment by jimchenphri** [comment]
Hi, sasumner, 

Please provide the your script. Really appreciated. 

Thank you very much.

**Comment by sasumner** [comment]
>provide your script

I felt like I had done this somewhere before, and it took a bit of research... the script is in this Community discussion thread:  https://notepad-plus-plus.org/community/topic/14527/last-line-has-crlf-or-not

**Comment by MetaChuh** [comment]
@jimchenphri 

notepad++ has to be able to generate a file, without adding any appending characters automatically.
a switchable setting would only shift the user's focus from having to be aware of an eol before eof, to having to be aware which eol settings are currently active, to know if a eol will be added automatically, eventually adding a second lf by accident.

it is a user choice to manually add a (cr)lf to the last line or not, making it able to create a zero length files, like you would do with `touch test.txt`, or a single string text line without line breaks.
as you're also very aware of any missing noeol, you will spot it immediately at the last line number,
and most current linux releases should not have issues with neol files if you forget one.

i do however think that such function could be a nice, external plugin or script.
a possible idea for the `NeolChecker` plugin or script would be, to colour the eol mode `Unix (LF)` section at the status bar in red, as long as no eol is found at the last line, green if it is found, and no colour if this plugin or script is disabled for that file type.

many thanks and best regards

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)

**Comment by xoyteam** [comment]
I'll just leave it here.
https://pubs.opengroup.org/onlinepubs/9699919799/basedefs/V1_chap03.html#tag_03_206
