### ISSUE TITLE
Edit "Run/Modify Shortcut path"

### ISSUE THREAD

**Issue by KungPhoo** [notepad-plus-plus/notepad-plus-plus#5514]
### Custom Run command string can't be edited.
When you link a "run" command to a keyboard shortcut, you only can change the shortcut, but not the command that is executed. Can you please make it editable?

Also, please add an option "Save file before running". That would be very convenient.

**Comment by MetaChuh** [comment]
@KungPhoo 

you have to edit or add your custom run commands at `%AppData%\Notepad++\shortcuts.xml`.

save file before running external programs can be achieved by creating a macro, or by plugins like nppexec.

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)

**Comment by ezxpro** [comment]
@MetaChuh not only is this relevant as of august 2022 (no way to edit/view the command used by shortcut), but also, the indicated file `%AppData%\Notepad++\shortcuts.xml` doesn't save any data pertaining to the shortcut. I can find this file both under the said path, as well as under the install folder, both are identical and as clean as when notepad++ was first installed.
For instance, this is the content of mine:
```
<?xml version="1.0" encoding="UTF-8" ?>
<NotepadPlus>
    <InternalCommands />
    <Macros>
        <Macro name="Trim Trailing Space and Save" Ctrl="no" Alt="yes" Shift="yes" Key="83">
            <Action type="2" message="0" wParam="42024" lParam="0" sParam="" />
            <Action type="2" message="0" wParam="41006" lParam="0" sParam="" />
        </Macro>
    </Macros>
    <UserDefinedCommands>
        <Command name="Get PHP help" Ctrl="no" Alt="yes" Shift="no" Key="112">https://www.php.net/$(CURRENT_WORD)</Command>
        <Command name="Wikipedia Search" Ctrl="no" Alt="yes" Shift="no" Key="114">https://en.wikipedia.org/wiki/Special:Search?search=$(CURRENT_WORD)</Command>
        <Command name="Open selected file path in new instance" Ctrl="no" Alt="yes" Shift="no" Key="117">$(NPP_FULL_FILE_PATH) $(CURRENT_WORD) -nosession -multiInst</Command>
    </UserDefinedCommands>
    <PluginCommands />
    <ScintillaKeys />
</NotepadPlus>
```
It displays nothing related to the my shortcuts, even though I have a dozen of them that I can't modify (except if I delete and recreate them, which is, or course, not an optimal solution).

All in all, I think this issue should be reconsidered.

**Comment by alankilborn** [comment]
@ezxpro Suggest you talk through your specific issue using the support forum https://community.notepad-plus-plus.org/
