### ISSUE TITLE
Resizing panes allows automatic resizing of Other View

### ISSUE THREAD

**Issue by andrewlvaldez** [notepad-plus-plus/notepad-plus-plus#5516]
### Steps to Reproduce the Issue
1. Open the Other View along with the search results pane.
2. Resize the height of the results pane then mouse over the splitter between Views left to right.

### Expected Behavior
It is expected that mousing over the splitter does nothing.

### Actual Behavior
The Views resize without actually clicking on the splitter.

This happens when you resize any of the other panes, ie document map, functions list, search results.

Using v7.6.6 on Windows 7.

Originally reported as issue #680 using v6.7.9 on Windows 7.

**Comment by MetaChuh** [comment]
@andrewlvaldez 

verified as reproducible.

**view splitter bar** displaces and responds to **mouseover without mousedown**,
after resizing a **docked** search result panel, as seen at the screencast below.

steps to reproduce:
* resize a docked search result (find result) panel, when multi-view is enabled.
* release the left mouse button and slowly hover over the splitter without holding any mouse button.
* **the splitter will shift to the right, and only to the right**.
(note: the screen recorder also does not detect a mouse up release)
* after clicking somewhere else, all reverts to normal.

![#5516 andrewlvaldez, Resizing panes allows automatic resizing of Other View](https://user-images.githubusercontent.com/45773305/55989749-53b1d280-5ca6-11e9-93ef-be99c45529b1.gif)

<kbd>Notepad++ v7.6.6   (64-bit)
Build time : Apr  3 2019 - 23:52:32
Path : C:\Users\User\Desktop\npp.7.6.6.bin.x64\notepad++.exe
Admin mode : OFF
Local Conf mode : ON
OS : Windows 7 (64-bit)
Plugins : mimeTools.dll NppConverter.dll</kbd>

<kbd>Notepad++ v7.6.6   (32-bit)
Build time : Apr  3 2019 - 23:49:50
Path : C:\Users\User\Desktop\npp.7.6.6.bin\notepad++.exe
Admin mode : OFF
Local Conf mode : ON
OS : Windows 7 (64-bit)
Plugins : mimeTools.dll NppConverter.dll NppExport.dll</kbd>
