### ISSUE TITLE
Bug/Unfriendy behavior: Column Editor insert text not only within selected lines, nor to the whole document

### ISSUE THREAD

**Issue by johnnytemp** [notepad-plus-plus/notepad-plus-plus#5518]
No matter the document has text selection or not, Column Editor always insert text from current line up to the end of the document.

A more intuitive and friendly behavior is to insert only for the selected lines when there is a selection.
### Steps to Reproduce the Issue
1. Open a normal text document of over 10 lines.
2. Forward select the lines from the 4th to 6th.
3. Menu -> Edit -> Column Editor..., then input "// " into "Text to insert" and press OK.
### Expected Behavior

"// " is inserted to the beginning of line 4, 5 and 6.
### Actual Behavior

"// " is inserted to the beginning of line 7, 8, 9 and so on unto the end.
### Debug Information

Notepad++ version 7.6.6 (64-bits) on Windows 10

**Comment by johnnytemp** [comment]
Seems Notepad++'s Edit -> "Column Editor..." is intended to that behavior  (i.e. always operate on current cursor column up to the end of document).  E.g. not allow specify a range of lines to operate on.  Thus, closing this issue.

**Comment by johnnytemp** [comment]
To me, a more intuitive way is:
1. if selection is not empty, treat them as selected lines range to limit to operate on.
2. If selection is empty, operate on all lines of the whole document.
3. "Column Editor" popup should have a numeric field to specify the column position to operator on (default to current cursor position)

**Comment by sasumner** [comment]
@johnnytemp 

You need to do a column selection of zero-width on lines 4-6 at column 1 before your step 3.

Example:  Move caret to line 4 column 1.  Hold shift+alt and press down arrow twice.  Then proceed with your step 3 (or even better, just type `//` in the case of your example!).

The key point is that if you want to limit the lines the column-editor affects, you must invoke it when you are already in column-select mode, with the multi-line caret (or rectangular selection) touching the lines (or rect. area) to affect.

**Comment by johnnytemp** [comment]
@sasumner Thank you for clarifying.

Because "Column Editor" seems can operate on empty selection (i.e. without column selection), I have a wrong impression and thought that it is an alternative (independent) tool to do some column editing.  Thus, I have not thought that it could use normal Column Selection to limit the line range before (since only making a Column Selection and typing can do the job of radio option 1 to insert some text).  Thanks.
