### ISSUE TITLE
Russian Translation of Tab Context Menu "Close All Unchanged" is missing.

### ISSUE THREAD

**Issue by andrecool-68** [notepad-plus-plus/notepad-plus-plus#5519]
Not working option "Close All Unchanged"

Notepad++ v7.6.6   (64-bit)
Build time : Apr  3 2019 - 23:52:32
Path : C:\Users\Uzeer\Desktop\npp.7.6.6\x64\notepad++.exe
Admin mode : ON
Local Conf mode : ON
OS : Windows 7 (64-bit)
Plugins : ComparePlugin.dll ComparePlus.dll DSpellCheck.dll HTMLTag.dll JSMinNPP.dll mimeTools.dll NppConverter.dll NppExec.dll NppExport.dll VisualStudioLineCopy.dll XMLTools.dll _CustomizeToolbar.dll 

![Запись_2019_04_12_14_43_02_982](https://user-images.githubusercontent.com/3471892/56034915-66bdb480-5d31-11e9-82e6-73165d365fc6.gif)

**Comment by Ekopalypse** [comment]
Andre, this is doing exactly what it should do. It does NOT close it as all of your files visible are changed.
Unchanged files are basically saved files.

**Comment by andrecool-68** [comment]
@Ekopalypse 
What a silly option "Close All Unchanged" ...which should close ...but it doesn't close anything?

**Comment by sasumner** [comment]
"unchanged" is perhaps ambiguous.  It could mean "never modified after loading", "modified but currently saved", and probably some other things.  I prefer "mod but currently saved".

@andrecool-68 When you post, you are going to have to type more so people understand what you are talking about. A screencast is awesome as supplementary info but (in all except the simplest cases) it can't stand on its own.

**Comment by MetaChuh** [comment]
hi @andrecool-68 

i believe this 5th closing feature is excellent.
it closes all saved files and empty tabs.
it leaves all unsaved files and tabs open.
is the russian translation incorrect ?

ps: how's the weather at antarctica 😉

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)

**Comment by sasumner** [comment]
>ps: how's the weather at antarctica

Says the guy who tells other people not to be irrelevantly chatty here on the issues list! :)

**Comment by Ekopalypse** [comment]
Karma strikes back

**Comment by andrecool-68** [comment]
@MetaChuh 
In Russian it translates as you need to close all Windows regardless of whether these files have changed or not.

**Comment by sasumner** [comment]
@andrecool-68 

An opportunity for you to suggest Russian text to make that better.  Simple PR to do.  Most of these types of PR are accepted by @donho quickly.

**Comment by andrecool-68** [comment]
@sasumner 
I don't see any point in this option at all ...

**Comment by MetaChuh** [comment]
@sasumner

> Says the guy who tells other people not to be irrelevantly chatty here on the issues list! :)

true, my apologies to both of you. 🙏
we have our community place to be chatty.

@andrecool-68 
[Close All Unchanged] is currently not translated to russian (7.6.6).
Russian Translation of Tab Context Menu Entry [Close All Unchanged] is missing.

current pull with updated russian translation: https://github.com/notepad-plus-plus/notepad-plus-plus/pull/5497
if accepted it will fix the translation.
see: https://github.com/notepad-plus-plus/notepad-plus-plus/pull/5497/files

> I don't see any point in this option at all ...

if you don't see any point in that option: please don't use it 😉

**Comment by andrecool-68** [comment]
@MetaChuh 
>
> current pull with updated russian translation: #5497
> if accepted it will fix the translation.
> see: https://github.com/notepad-plus-plus/notepad-plus-plus/pull/5497/files
>
>

What's new? I did exactly the same translation! Other users over time repeats my question ...why this option does not work!!!

**Comment by Tmp341** [comment]
Am I the only one who sees all those tabs contain changed strings etc?

**Comment by MetaChuh** [comment]
hi @Tmp341 

all of us see that.
the original issue title was: Not working option "Close All Unchanged".
as this is true this issue would be invalid and not reproducible and would be closed by now.

but knowing andre, i've then checked how it can come to that misunderstanding from him, and seen that the translation to russian is not yet accepted, and andre is not good at english, so he does not yet understand the meaning of this menu entry feature.

i then modified this issue to: Russian Translation of Tab Context Menu "Close All Unchanged" is missing,
instead of closing it.

i will close this "morphed" issue as soon as the pr is merged or superseeded.

**Comment by andrecool-68** [comment]
@MetaChuh 
> i've then checked how it can come to that misunderstanding from him, and seen that the translation to russian is not yet accepted, and andre is not good at english, so he does not yet understand the meaning of this menu entry feature.

Don't you know what I'm talking about?
I've seen this translation ...this does not correspond to the value of this operation!
And do not make me an idiot here.

**Comment by MetaChuh** [comment]
@andrecool-68 

my apologies, but this menu entry is not yet translated to russian, as you can see at the screenshot below.

the menu close all unchanged, however, does exactly what it should:
it closes all unchanged files, meaning all files that are open but not edited, as clearly explained above by eko and scott.

<img width="967" alt="Bildschirmfoto 2019-04-12 um 22 09 38" src="https://user-images.githubusercontent.com/45773305/56063611-0a2dba00-5d70-11e9-92ef-4700b57f1aff.png">

**Comment by andrecool-68** [comment]
@MetaChuh 
It's hard to talk when you just don't want to understand ...and it's not about my English

**Comment by MetaChuh** [comment]
@andrecool-68 
i respect you and i want to understand, but i'm not able to understand with the given information.
i need your help to understand, or a human translator that understands you, to be able to understand the way you understand this menu entry topic.

**Comment by donho** [comment]
So it's not an issue.
