### ISSUE TITLE
The "&" character is not appearing at the Java archives

### ISSUE THREAD

**Issue by VictorJanikian** [notepad-plus-plus/notepad-plus-plus#552]
Since this last version, I mean.

**Comment by donho** [comment]
I cannot reproduce the bug:
![1557712_763221057056202_8141006547373112469_n](https://cloud.githubusercontent.com/assets/90293/8863223/01d1394e-3197-11e5-9e69-adaebd8e2dd6.jpg)
I know there might be nothing to do with plugins, but could you remove "plugins" directory then try again to make sure it's not about plugins issue?
Also it'll help if you can provide the info of your environment.

**Comment by donho** [comment]
@VictorJanikian I did some changes for this issue but I'm not sure if it is fixed since I cannot reproduce it.
Could you download this file:
https://notepad-plus-plus.org/temp/npp.7z
unzip it into a new created folder, then launch notepad++.exe.
Please let me know the result.

**Comment by VictorJanikian** [comment]
@donho No problems! Sorry for taking too much time to answer, this issue happened in my job's computer, so I'll take this procedures as soon as I back there : )

**Comment by donho** [comment]
@VictorJanikian Thank you! Please let me know the result as you can!

**Comment by VictorJanikian** [comment]
@donho No good news. I first removed all the plugins, and had no positive results. After I used this version you provided, but had no results again. Sorry : (

This PC uses Windows 7 professional, version 6.1.7601 Service Pack 1 Compilation 7601.
It's a x64-based PC.
The CPU is Intel Core I5-2400, 4 cores.

Any other information you need, just say it : )

**Comment by donho** [comment]
@VictorJanikian  I believe that Source Code Pro had been installed in your system (before you use Notepad++ 6.8). Could you check in your font directory and confirm me this fact?

**Comment by donho** [comment]
@VictorJanikian your installed Source Code Pro font should be updated.

**Comment by h-h-h-h** [comment]
Reference: issue https://github.com/notepad-plus-plus/notepad-plus-plus/issues/729
