### ISSUE TITLE
Make all I/O asynchronous

### ISSUE THREAD

**Issue by Borkason** [notepad-plus-plus/notepad-plus-plus#5520]
As per https://github.com/notepad-plus-plus/notepad-plus-plus/issues/913#issuecomment-481480999 this is the new ticket, as issue #913 still exists with the version 7.6.6.

> All disk I/O operations should be made asynchronous. This means that the UI thread remains responsive when the disk access takes longer than an instant. Common cases are disk drives that are currently in standby and need a moment to wake up. My primary drive is an SSD and there's an additional hard disk (10 seconds to wake up) and a NAS drive (up to 30 seconds to wake up). Slow network connections (like a Windows folder share over DSL/UMTS) may also lead to this.

> Notepad++ becomes unresponsive and will not update or even show the entire window as long as it's waiting for a disk drive. This includes saving changes to the file, and checking the file for modifications when the minimised window is restored.

> I run into this situation every few days, sometimes also a few times a day, depending on my activity pattern.

> While the disk operation is in progress, a non-modal (or at least a modal) activity indicator should be displayed. This might be in the status bar like for example in Microsoft Word. So at least the editor window will show up when it's still waiting for a device.

> Saving or refreshing files in the background (i.e. allowing the user to continue typing while the snapshot is being saved or checked for updates) would be a welcome bonus but is not required in the first step.

Notepad++ v7.6.6   (64-bit)
Build time : Apr  3 2019 - 23:52:32
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10 (64-bit)
Plugins : BetterMultiSelection.dll mimeTools.dll NppConverter.dll

**Comment by MetaChuh** [comment]
@Borkason 

many thanks for your feature request.

asynchronous file handling will currently not be implemented, due to the proven data reliability of the current file handling design.

thank you for your help and best regards.

**Comment by mirh** [comment]
It's not about data reliability.. it's about not hanging?
