### ISSUE TITLE
Base64Encode: Generate mail-ready blobs by breaking lines at 76 characters

### ISSUE THREAD

**Issue by DRSpalding** [notepad-plus-plus/notepad-plus-plus#5521]
### Description of the Issue
I may be missing a way to do this automatically in Notepad++ and/or the MIME plugin, but that said...

I do a lot of spam reporting and as such, I have to decode base64 encoded MIME blobs in emails to pull out URLs and to mask email addresses.  Encoding them back into base64 means I have one long line of base64 text that I end up having to manually (or use a macro) split it into 76 character chunks like the quoted-printable blocks sans the ‘=’ at the end of the lines.  Could you add in an option to do that automatically when encoding?  It would streamline my use of it and lessen the amount of time it takes to report such spams.

**Comment by MetaChuh** [comment]
this is a non source code related question.
please visit our notepad++ community to discuss this with a wider range of developers and power users.

thank you for your help and best regards.

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
(no extra account is necessary, just use your github account to sign in)
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)

**Comment by DRSpalding** [comment]
It was a feature request.  However, I'll check in the plugin development forum on the community site first.
