### ISSUE TITLE
Hyphenation algorithm should not be applied on chinese.

### ISSUE THREAD

**Issue by HuJK** [notepad-plus-plus/notepad-plus-plus#5524]
Most text editor will use hyphenation algorithm avoid split a single word to 2 different lines.
For example:
![image](https://user-images.githubusercontent.com/15907444/27766862-3609f24a-5f13-11e7-8eb8-6cc2ae205d31.png)

If we have a long words,It will looks like this:
![image](https://user-images.githubusercontent.com/15907444/27766870-621ce874-5f13-11e7-9511-b8c76b361fd8.png)

But Chinese don't need it!
Because Chinese don't use space to split words!
![image](https://user-images.githubusercontent.com/15907444/27766874-7fe64314-5f13-11e7-9065-d0d749182833.png)

If we write a Chinese sentence,Notepad++ will treat a sentence as a single words,and try to put it in a single line.

I think Notepad++ should detect if the language is Chinese,then disable the function.

Not only Chinese,but also Japanese,Korean that any language not split words with space.

**Comment by MetaChuh** [comment]
@HuJK 

thank you for your report.

chinese rendering, as well as other non, or zero width spaced languages, are depending on the implemented scintilla component.

unfortunately scintilla is an external project, so you will have to file your issue at the [<kbd>scintilla bug tracker</kbd>](https://sourceforge.net/p/scintilla/bugs/).

there is currently nothing we can do about this experience, at the notepad++ part.
we apologise for that.

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
(no extra account is needed, just use your github account to sign in)
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)

**Comment by Phroneris** [comment]
After this issue was closed, HuJK reprinted it at the Scintilla bug tracker as MetaChuh had told:
https://sourceforge.net/p/scintilla/bugs/2096/

and got a link as an answer:
https://www.scintilla.org/ScintillaDoc.html#SCI_SETWRAPMODE
Though I'm not sure about NPP implementation, this item seems to be saying that Scintilla already has its option to select wrap mode not only for Latin-character languages but also for CJK ones.

Then, should this issue still be closed?
Is it impossible to develop it?
I also want this feature as a Japanese user.
(Even if not a perfect one for CJK languages, at least "line-break-anywhere" mode.)

**Comment by Ekopalypse** [comment]
You might give @dinkumoils [ExtSettings](https://sourceforge.net/projects/extsettings/) plugin a chance
and see if it results in what you want.

**Comment by Phroneris** [comment]
@Ekopalypse Thanks, I didn't know that plugin.
But I couldn't import it because it's 32 bit.
I use 64-bit NPP.

**Comment by Ekopalypse** [comment]
Depending on the current npp version you use, you can goto Plugins->Plugins Admin and select ExtSettings to install it.
On 64bit npp, which I use as well, this will install the 64bit version of that plugin.

**Comment by Phroneris** [comment]
@Ekopalypse Thanks again.
I updated to latest v7.8.1, could install the plugin and it worked rather fine.
Then, my last question (not to you) is whether the MetaChur's answer saying that it's an issue of Scintilla was correct...
But, anyway, the feature itself can be used. Thanks again again.

**Comment by HuJK** [comment]
I installed ExtSettings plugin, it seems there no option that can apply Hyphenation algorithm only for Asian languages.
![image](https://user-images.githubusercontent.com/15907444/68608978-286abc80-04ef-11ea-9f20-c032103fb186.png)

I don't know where is the differences between **Word boundaries** and **Whitespace characters**:
![image](https://user-images.githubusercontent.com/15907444/68608980-2c96da00-04ef-11ea-909b-f913e48d7457.png)
![image](https://user-images.githubusercontent.com/15907444/68608988-302a6100-04ef-11ea-8785-0b035b19a743.png)

I think the ideal mode can do this:
![image](https://user-images.githubusercontent.com/15907444/68609035-46d0b800-04ef-11ea-92a4-90e47488e6a1.png)

Only apply Hyphenation algorithm on languages which listed in **Space as word separator** scetion in this table:

  | Space as word separator | Other word separator | Syllable separator | No separator
-- | -- | -- | -- | --
Wraps words | Amharic (ethiopic)\*, Arabic, Armenian, Bengali, Cherokee, Dhivehi (thaana), English (latin), English (deseret), Fula (adlam), Georgian, Greek, Gujarati, Hebrew, Hindi (devanagari), Inuktitut (UCAS), Kannada, Korean (hangul)\*, Malayalam, Mandaic, Mandinka(n’ko), Oriya, Panjabi (gurmukhi), Russian (cyrillic), Sinhala, Syriac, Tamil, Tedim (pau cin hau), Telugu | Samaritan |   | Khmer, Lao, Myanmar, Thai
Wraps syllables | Eastern Cham, Korean (hangul)\*, Sundanese |   | Vietnamese (latin), Tibetan | Balinese, Batak, Chinese, Javanese, Western Cham
Wraps characters |  | Amharic (ethiopic)* |   | Japanese, Vai

*Archaic scripts are much more likely to use a scriptio continua approach (ie. no word or syllable breaks), although in modern texts describing them you may find spaces separating units of text. Older versions of the scripts mentioned may also use different rules for word division and line breaking.*
Source:  https://www.w3.org/International/articles/typography/linebreak


Should I submit a pull request to Scintilla? or it already provided this mode but **ExtSettings** not showing them?

**Comment by Ekopalypse** [comment]
@HuJK - sorry, no this setting affects the whole document, not only parts of a document.
If this was your initial request, which I haven't understood, then sorry for confusion but this is nothing
scintilla can provide at the moment. As far as I understand the code. 

The differences in WORD and WHITESPACE wrapping is seen when having text with different styles.
For example:
If you have a python f-string like 

~~~
f'some text and a {variable} which gets resolved'
~~~

If the window is small enough and wrapping is set to WHITESPACE it might wrap to something like 

~~~
f'some text and a 
{variable} which gets 
resolved'
~~~

with the same window width but rapping on WORD it will result in

~~~
f'some text and a {variable
} which gets resolved'
~~~

**Comment by Phroneris** [comment]
I found that ExtSettings is not satisfactory for me because shortcut keys cannot switch line display mode between no wrap and any-char wrap.
This is what I finally want to do.
I also tried macro but it didn't help.

**Comment by xylographe** [comment]
@Phroneris 
Install _LuaScript_ plugin. Select **Plugins > LuaScript > Edit Startup Script**. Add these lines,
```
npp.AddShortcut("Toggle Wrap Mode", "Alt+Ctrl+Shift+W", function()
  local wrapmode = editor.WrapMode
  if wrapmode == SC_WRAP_NONE then wrapmode = SC_WRAP_CHAR else wrapmode = SC_WRAP_NONE end
  editor.WrapMode = wrapmode
end)
```
Set the shortcut (`Alt+Ctrl+Shift+W`) to your liking. Restart NPP.

**Comment by Phroneris** [comment]
@xylographe Thank you.
It's wonderful and really unexpected solution.
But, it has another problem that the line scroll position gets different forward after switching back from any-char wrap mode, if some long lines enough to wrap exist above the top of display.
It doesn't occur when using default wrap feature or ExtSettings' one.
I assume that `editor.FirstVisibleLine`, `editor:DocLineFromVisible()` and `editor:VisibleFromDocLine()` might help, but I couldn't invent any concrete code to solve it as far as I tried.
This plugin is really cool, anyway.

**Comment by xylographe** [comment]
Perhaps,
```lua
  if editor.WrapMode == SC_WRAP_NONE then
    editor.WrapMode = SC_WRAP_CHAR
  else
    local cl = editor:LineFromPosition(editor.CurrentPos)
    local vo = editor:VisibleFromDocLine(cl) - editor.FirstVisibleLine
    editor.WrapMode = SC_WRAP_NONE
    local fl = editor:VisibleFromDocLine(cl) - vo
    if fl < 0 then fl = 0 end
    editor.FirstVisibleLine = fl
  end
```
Not exact, as it doesn't take into account that the current line might have been wrapped too.

**Comment by Phroneris** [comment]
Thanks, but it results in the same.

----

Fortunately I've found that, when on any-char wrap mode, the default "Word wrap" command works with correct line position though it necessarily switches to word-boundary wrap mode.
And note that there's no problem when executing `editor.WrapMode = SC_WRAP_CHAR` directly to switch from no wrap mode to any-char wrap mode.

So, this is the final solution for me:

```lua
npp.AddShortcut(
  "Wrap on any character", -- Is this English correct?
  "Alt+R",
  function()
    local function ww() npp:MenuCommand(44022) end -- "View" -> "Word wrap"
    if editor.WrapMode == SC_WRAP_CHAR then
      ww()   -- to SC_WRAP_WORD
      ww()   -- to SC_WRAP_NONE
    else
      if editor.WrapMode == SC_WRAP_WORD then
        ww() -- to SC_WRAP_NONE
      end
      editor.WrapMode = SC_WRAP_CHAR
    end
  end
)
```

It's....... *satisfactory*.
Thanks a lot, xylographe.

**Comment by xylographe** [comment]
@Phroneris 
LuaScript understands NPP macros defined in [`menuCmdID.h`](https://github.com/dail8859/LuaScript/blob/master/src/Npp/menuCmdID.h).
You could replace `44022` with `IDM_VIEW_WRAP`.

P.S. `"Wrap between any characters"` :)

**Comment by microka** [comment]
> Archaic



> I installed ExtSettings plugin, it seems there no option that can apply Hyphenation algorithm only for Asian languages.
> ![image](https://user-images.githubusercontent.com/15907444/68608978-286abc80-04ef-11ea-9f20-c032103fb186.png)
> 
> I don't know where is the differences between **Word boundaries** and **Whitespace characters**:
> ![image](https://user-images.githubusercontent.com/15907444/68608980-2c96da00-04ef-11ea-909b-f913e48d7457.png)
> ![image](https://user-images.githubusercontent.com/15907444/68608988-302a6100-04ef-11ea-8785-0b035b19a743.png)
> 
> I think the ideal mode can do this:
> ![image](https://user-images.githubusercontent.com/15907444/68609035-46d0b800-04ef-11ea-92a4-90e47488e6a1.png)
> 
> Only apply Hyphenation algorithm on languages which listed in **Space as word separator** scetion in this table:
> 
>  	Space as word separator	Other word separator	Syllable separator	No separator
> Wraps words	Amharic (ethiopic)*, Arabic, Armenian, Bengali, Cherokee, Dhivehi (thaana), English (latin), English (deseret), Fula (adlam), Georgian, Greek, Gujarati, Hebrew, Hindi (devanagari), Inuktitut (UCAS), Kannada, Korean (hangul)*, Malayalam, Mandaic, Mandinka(n’ko), Oriya, Panjabi (gurmukhi), Russian (cyrillic), Sinhala, Syriac, Tamil, Tedim (pau cin hau), Telugu	Samaritan	 	Khmer, Lao, Myanmar, Thai
> Wraps syllables	Eastern Cham, Korean (hangul)*, Sundanese	 	Vietnamese (latin), Tibetan	Balinese, Batak, Chinese, Javanese, Western Cham
> Wraps characters	 	Amharic (ethiopic)*	 	Japanese, Vai
> _Archaic scripts are much more likely to use a scriptio continua approach (ie. no word or syllable breaks), although in modern texts describing them you may find spaces separating units of text. Older versions of the scripts mentioned may also use different rules for word division and line breaking._
> Source: https://www.w3.org/International/articles/typography/linebreak
> 
> Should I submit a pull request to Scintilla? or it already provided this mode but **ExtSettings** not showing them?

Hi @HuJK , i am wondering if you find the workaround to let notepad++ display Chinese and English words correctly at the same time? Just like the capture you uploaded. ![image](https://user-images.githubusercontent.com/15907444/68609035-46d0b800-04ef-11ea-92a4-90e47488e6a1.png)
