### ISSUE TITLE
Don't open same file in multiple instances

### ISSUE THREAD

**Issue by Yay295** [notepad-plus-plus/notepad-plus-plus#5526]
### Description of the Issue
If you have multiple N++ instances, and reopen an already opened file, it will be opened in the last instance you were using instead of switching to the already opened instance.

### Steps to Reproduce the Issue
1. Open a file.
2. Open a second file.
3. Move the second file to a new instance.
4. Minimize the new instance's window.
5. Select the original instance's window.
6. Reopen the second file using the OS's file explorer (don't use the File menu in N++).

### Expected Behavior
The second instance will be maximized since this file is already open there.

### Actual Behavior
The second file is reopened in the first instance.

### Debug Information
Tested with a fresh install of v7.6.6 on 64bit Windows 10.

**Comment by donho** [comment]
There's no way to know the if the open files in any instance, so this behavior is a limit and won't be fixed.
