### ISSUE TITLE
Blinking cursor in Notepad++

### ISSUE THREAD

**Issue by andrecool-68** [notepad-plus-plus/notepad-plus-plus#5529]
Help find the cause of the cursor flickering in Notepad++, reinstalling different versions of Notepad++ does not solve the problem. Reinstalling the operating system does not solve the problem either. When there is a flicker of the cursor that helps only restart Notepad++. This is not the first time I have raised this issue!

In other programs this does not happen!!!

![2](https://user-images.githubusercontent.com/3471892/56099566-5e26d300-5f17-11e9-99c9-514966f011f8.gif)

Notepad++ v7.6.6   (64-bit)
Build time : Apr  3 2019 - 23:52:32
Path : C:\Users\Uzeer\Desktop\npp.7.6.6\x64\notepad++.exe
Admin mode : ON
Local Conf mode : ON
OS : Windows 7 (64-bit)
Plugins : ComparePlugin.dll DSpellCheck.dll HTMLTag.dll JSMinNPP.dll mimeTools.dll NppConverter.dll NppExport.dll VisualStudioLineCopy.dll XMLTools.dll _CustomizeToolbar.dll

**Comment by donho** [comment]
How can we reproduce it?

**Comment by andrecool-68** [comment]
@donho 
I don't know why this is happening. And it can happen at any time.

**Comment by donho** [comment]
Please keep us posted if you find the way to trigger it.

**Comment by Ekopalypse** [comment]
@andrecool-68 
I discovered something similar and at this time npp had a lot of cpu time. 
At the end I found out, that a plugin, which was hooking the message queue, didn't act correctly.
Maybe this might be your problem too?

**Comment by donho** [comment]
@andrecool-68 What's your debug info please?

**Comment by andrecool-68** [comment]
@donho 
I wrote it in the first message.

**Comment by andrecool-68** [comment]
@Ekopalypse 
What plugin are you talking about? 
I don't have any plugin crashes.

**Comment by andrecool-68** [comment]
I can just browse through the contents of the open file and then start to notice this behavior of the cursor.

**Comment by Ekopalypse** [comment]
@andrecool-68, I did not have any crash either. It just occurred that repainting and overall responsiveness
was not good at this time. The plugin was my first try to write an c++ plugin.
Concerning your issue, the one which instantly seems to be the suspicious is the _CustomizeToolbar.dll.
Did you experience the same without having _CustomizeToolbar.dll installed?

**Comment by andrecool-68** [comment]
@Ekopalypse 
I have it permanently installed, without it I haven't checked.

**Comment by sasumner** [comment]
I sometimes experience a similar issue with the mouse cursor when trying to get to the splitter bars between the various subwindows (between an editing tab and the Find result panel, between view0 and view1, etc.).  The cursor keeps changing to something other than the updown or leftright cursor, right when I get near where I need to be to do my desired resizing. I never considered the possibility that a plugin could be involved.  I will also have to look into that more.

**Comment by donho** [comment]
@andrecool-68 Sorry, I mean @Ekopalypse 

@Ekopalypse Your debug info please?

**Comment by andrecool-68** [comment]
@Ekopalypse 
Removing the `_CustomizeToolbar` plugin did not solve the problem.

**Comment by Ekopalypse** [comment]
@donho, at that time I was using
~~~
Notepad++ v7.6.5   (64-bit)
Build time : Mar 29 2019 - 02:43:47
Path : D:\...\notepad++.exe
Admin mode : OFF
Local Conf mode : ON
OS : Windows 7 (64-bit)
Plugins : PythonScript.dll 
~~~
But just to be sure, my issue has been solved by removing my shitty-programmed plugin. 
I just wanted to make clear that such an issue might caused by npp plugins as well.

**Comment by sasumner** [comment]
@andrecool-68 That means, remove other plugins, one at a time, and see if you can find at what point the bad behavior stops (if it does).

**Comment by andrecool-68** [comment]
@sasumner 
There is no other way, now turned off DSpellCheck

**Comment by Yaron10** [comment]
@andrecool-68,

Does it happen after double-clicking a link?

**Comment by andrecool-68** [comment]
@Yaron10 
I just tested it ... made a double click on the link ... and the cursor began to flicker!
But the flicker of the cursor used to appear without clicking on the links)

**Comment by andrecool-68** [comment]
@donho 
Double clicking on a link in the file text causes the cursor to flicker.

**Comment by MetaChuh** [comment]
@Yaron10 
i can still not reproduce this.
double-click on a link, does not trigger cursor flicker, when hovering to/over toolbar icons.
(7.6.6. x86/x64 on w7 and w10.)

can it be a combination of installed **translator** software and double-clicking a link ?

**Comment by andrecool-68** [comment]
@MetaChuh 
Leave my translator alone, he has long been disconnected)))

**Comment by donho** [comment]
Fixed. Please try this 32 `notepad++.exe`:
https://notepad-plus-plus.org/temp/fixFlickering.7z

**Comment by Ekopalypse** [comment]
@donho, I can confirm that I'm unable to reproduce the flickering issued by double-clicking links.
~~~
Notepad++ v7.6.6   (32-bit)
Build time : Apr 16 2019 - 13:02:22
Path : D:\...\notepad++.exe
Admin mode : OFF
Local Conf mode : ON
OS : Windows 7 (64-bit)
Plugins : mimeTools.dll NppConverter.dll NppExport.dll 
~~~

**Comment by andrecool-68** [comment]
@donho 
In the updated version of Notepad ++ with a double click there is no flicker of the cursor!

**Comment by andrecool-68** [comment]
@donho 
After correcting this error, you can close both of these questions: https://github.com/notepad-plus-plus/notepad-plus-plus/issues/5529    https://github.com/notepad-plus-plus/notepad-plus-plus/issues/5200

**Comment by Yaron10** [comment]
@andrecool-68,
Thank you for testing.

@donho,
There seems to be a regression in the file you've uploaded:
the first visible line is selected instead of the link (requires some more testing).

Changing the following code in `NppNotification.cpp` fixes the flickering on double-clicking a link.
```
//  Comment lines.
// Select the entire link
//notifyView->execute(SCI_SETANCHOR, startPos);
//notifyView->execute(SCI_SETCURRENTPOS, endPos);

generic_string url = notifyView->getGenericTextAsString(startPos, endPos);
::ShellExecute(_pPublicInterface->getHSelf(), TEXT("open"), url.c_str(), NULL, NULL, SW_SHOW);

//  Fix flickering cursor.
HWND hEditView = _pEditView->getHSelf();
::PostMessage(hEditView, WM_LBUTTONDOWN, 0, 0);
::PostMessage(hEditView, WM_LBUTTONUP, 0, 0);
::PostMessage(hEditView, SCI_SETSEL, startPos, endPos);

break;
```
Thank you.
 
@MetaChuh,
I have no idea why the flickering is not reproducible on your machine.
Thank you.

**Comment by Yaron10** [comment]
@andrecool-68, @MetaChuh,

Could you please download the latest `notepad++.exe` from https://ci.appveyor.com/project/donho/notepad-plus-plus (Platform -> Artifacts)?

Isn't the first visible line selected instead of the link?

**Comment by MetaChuh** [comment]
@Yaron10  @donho 
yes, the first visible line is marked after a double-click on a link,
not the link itself.

additionally the x86 artifact produces an exception for me. can someone verify this ?

**Comment by Yaron10** [comment]
@MetaChuh,

Thank you for testing and confirming.
I think the link's selection should be executed *after* the Left-Down/Up.

> additionally the x86 artifact produces an exception for me.

My system is Win 7 32-bits. No exception.

**Comment by andrecool-68** [comment]
@Yaron10 
I myself made the assembly of the revised project (x32 and x64), there is no flicker of the cursor!
Now I'm testing your build.

**Comment by andrecool-68** [comment]
Now I tested your build project: 
With new files SciLexer.dll  does not start the program and gives an error:

```Authenticode check failed: signing certificate or hash is not recognized```

I used the old files SciLexer.dll, the program works fine with them ..and there is no flickering of the cursor

**Comment by Yaron10** [comment]
@andrecool-68,

Thank you for the thorough testing. :+1:

**Comment by andrecool-68** [comment]
I noticed that with a double click on the link in the old and new selection of the current line are in different places!

Old build:

![старый](https://user-images.githubusercontent.com/3471892/56248491-e2608e00-60b0-11e9-982b-4db81aa5b69d.gif)

New build:

![новый](https://user-images.githubusercontent.com/3471892/56248496-e68cab80-60b0-11e9-94ad-4528df5807fd.gif)

**Comment by Yaron10** [comment]
@andrecool-68,

That's exactly what I asked to confirm some posts above. :)

> Isn't the first visible line selected instead of the link?

**Comment by andrecool-68** [comment]
@Yaron10 
Sorry ... it's dark and hard to see at night)))

**Comment by donho** [comment]
I prefer to call it "random feature" :)

Anyway thank you for spotting it, a fix is available here:
https://notepad-plus-plus.org/temp/fixFlickering2.7z

Please let me know if you find any other random feature.

**Comment by andrecool-68** [comment]
@donho 
Now it works well ...and the new "random feature" is not visible :)
Many thanks for the support!

**Comment by Yaron10** [comment]
@donho,
The link is not selected now. Is that intentional or random? :)
Thank you.

@andrecool-68,
> Sorry ... it's dark and hard to see at night)))

And English is not our native language. :)
.חג שמח

**Comment by donho** [comment]
> The link is not selected now. Is that intentional or random? :)

@Yaron10 it's an intentional random feature or a random intentional behaviour - choose one randomly! :)

**Comment by sasumner** [comment]
Whichever it is, you watch, existing N++ users aren't going to like the change.  :)

**Comment by andrecool-68** [comment]
@Yaron10 
My mother tongue is Russian)
!חג שמח

**Comment by Yaron10** [comment]
@donho,
I'm intentionally selecting "random" as "intentional" would actually be "a worse random". :)
Anyway, thank you for fixing the flicker. :+1:

**Comment by MetaChuh** [comment]
@sasumner et al.

hmmmh, i actually like this random intentional new behaviour.

i bet that users have inadvertently overwritten their links after opening them in the past, as they were still selected, when they returned from their internet browser.

as far as i can guess, only few people used a double click to select the text part of a link.
i think the typical user behaviour is to avoid opening a link, when one just wants to copy/paste it somewhere else, so i'm not sure if the majority of users will miss the link text selection after a double click at all.
