### ISSUE TITLE
UDL Comment Folding Malfunctions

### ISSUE THREAD

**Issue by AtmaX** [notepad-plus-plus/notepad-plus-plus#553]
UDL comment folding tree figures are absent in many places they should be and are in many places they shouldn't.  Comments should be able to be folded by block (from my understanding).  These are just a few examples:
![image](https://cloud.githubusercontent.com/assets/9388832/8863757/7bcdb494-3169-11e5-99b9-542bbb06d5d4.png)
![image](https://cloud.githubusercontent.com/assets/9388832/8863794/c2c028c8-3169-11e5-8143-600067fa5be6.png)
![image](https://cloud.githubusercontent.com/assets/9388832/8863815/e054d924-3169-11e5-865c-9e62ce09b7a2.png)
![image](https://cloud.githubusercontent.com/assets/9388832/8863830/05820708-316a-11e5-98b9-1fa247b9eaa9.png)

**Comment by xvitus** [comment]
+1. I also was trying to create a simple UDL, but when blocks contain nested delimited sections or comments then the folding structure is completely wrong.
I suppose the problem is in LexUser.cxx. Anyone who already worked on this file?

**Comment by donho** [comment]
I believe this issue has been fixed since long time ago.
Update your Notepad++ to the latest version (v7.6.6).
If the issue persists, please create a new issue for it.
Thank you.
