### ISSUE TITLE
Awk syntax highlighting

### ISSUE THREAD

**Issue by cup** [notepad-plus-plus/notepad-plus-plus#5530]
reposting since previous issue was closed in error

**Comment by cup** [comment]
https://github.com/notepad-plus-plus/notepad-plus-plus/issues/1620

**Comment by MetaChuh** [comment]
@cup 

our apologies for closing your issue without providing the required information.

syntax highlighting lexers, other than user defined languages, will depend on the scintilla component.
 
unfortunately scintilla is an external project, which currently has no known plans of implementing awk.
see example request: https://sourceforge.net/p/scintilla/feature-requests/780/

if you want awk being implemented, you will have to try to file your feature request at the: [<kbd>scintilla feature tracker</kbd>](https://sourceforge.net/p/scintilla/feature-requests/).

for now you will have to use an udl, like the awk udl provided by @it3xl at your old issue, or similar.

there is currently nothing we can do about this at the notepad++ part.
we apologise for that.

-----
```
general notes:

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
(no extra account is needed, just use your github account to sign in)
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)

**Comment by it3xl** [comment]
As I see, Notepad++ is now accessible on Linux.
I've installed it yesterday on Ubuntu 18.04.
But I'm still using the VisualBasic language selection to edit awk files.

**Comment by cup** [comment]
https://github.com/stefankueng/BowPad/issues/31

**Comment by cup** [comment]
@MetaChuh will you please reconsider. Awk has been implemented with at least 3
other Scintilla based editors:

- https://github.com/ProgerXP/Notepad2e/blob/302735c/src/Styles.c#L1629
- https://github.com/rizonesoft/Notepad3/blob/master/src/StyleLexers/styleLexAwk.c
- https://github.com/zufuliu/notepad2/blob/master/src/EditLexers/stlAwk.c

**Comment by sasumner** [comment]
>will you please reconsider

There is nothing to reconsider as this is not a Notepad++ thing.  It is a Scintilla thing.  When Notepad++ migrates to a Scintilla version that supports it (current scheduling for that is unknown), it will be there.  Until that time there is nothing that can be done in Notepad++.

**Comment by cup** [comment]
@sasumner yeah there absolutely is because it's been done in 3 projects already.

It's only a matter if NPP I willing to do it. I appreciate your fast response, but it's disingenuous to just say it's not possible.

**Comment by sasumner** [comment]
OK, apparently one must quantify:  _It is not possible given the way that support for lexing has previously been decided to be done in Notepad++_.  That support comes via Scintilla.  If other Scintilla-based editors choose to go outside Scintilla to provide lexing for certain languages, that is their purview.  Based upon the closure of not just one but two Notepad++ issues on this topic now, I'd say that the decision isn't going to be revisited.

You can certainly write a UDL (as previously suggested) or custom lexer; there are scripting solutions to this that can be used as models (although I don't recall one specifically for awk).

**Comment by cup** [comment]
@sasumner as you currently have 0 commits on this repo

https://github.com/notepad-plus-plus/notepad-plus-plus/commits?author=sasumner

you will understand if i dont take your point of view seriously. cheers

**Comment by sasumner** [comment]
>0 commits on this repo

Through a long period of observation, I've seen how very few user-submitted PRs on Notepad++ get accepted.  Thus I choose not to contribute (why put the effort in if it isn't going to be accepted).  However, also because of this long observation, I see how things "go" so I feel qualified to comment (sometimes).  If an issue is closed without a lot of comment, and someone interested in the issue wonders why, I might try to fill in a gap.  Or point someone to a scripting solution, so that they can have what they want today, as opposed to waiting forever for something that just isn't going to happen.  That's all.  But I've already been told that I'm not taken seriously, so Cheers to you as well, mate.
