### ISSUE TITLE
No option to run files in browser...

### ISSUE THREAD

**Issue by Apeoples** [notepad-plus-plus/notepad-plus-plus#5531]
### Steps to Reproduce the Issue

1. 
2. 
3.

**Comment by MetaChuh** [comment]
please update to notepad++ 7.6.6.

you will find this feature at the notepad++ menu `view > view current file in > [browsername]`,
as seen at the screenshot below.

![Imgur](https://i.imgur.com/psnbpg4.png)

-----
```
general notes:

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
(no extra account is needed, just use your github account to sign in)
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)
