### ISSUE TITLE
Open File should remember the "Files of type:" field between executions

### ISSUE THREAD

**Issue by jimjones48** [notepad-plus-plus/notepad-plus-plus#5533]
### Description of the Issue
Open File should remember the "Files of type:" field from run to run

### Steps to Reproduce the Issue
1. Click on Open File Icon
2. Change the "Files of type" box to something like "*.lua"
3. Choose a file
4. Exit the program
5. Restart the program
6. Click on Open File Icon

### Expected Behavior
I expected to see the same value in the "Files of type" box that
I entered in step 2.

### Actual Behavior
I saw the default value for "Files of type" box :  "All types(*.*)".

**Comment by MetaChuh** [comment]
@jimjones48 

this is a design feature, to quickly change file types, either after notepad++ restart, or immediately after every file open command.

currently you have the following options:

* new style dialog:
the file type filter will default to `*.*` after every `file > open`
if you type `*.lua` into the file name field, and press <kbd>enter</kbd>, your view will be filtered, showing only .lua files and all sub-folders.

* old style dialog:
the file type filter, e.g. `*.lua` will be remembered after the first `file > open`, until you exit notepad++.
if you type `*.lua` into the file name field, and press <kbd>enter</kbd>, all .lua files at the current location will be loaded into notepad++.

as those two options are the most used, and this is an isolated request, no third option will be implemented for now.

many thanks and best regards

-----
```
general notes:

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
(no extra account is needed, just use your github account to sign in)
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)
