### ISSUE TITLE
Down arrow stops moving cursor down on large files

### ISSUE THREAD

**Issue by Wyer-Byter** [notepad-plus-plus/notepad-plus-plus#5534]
### Description of the Issue
When scrolling down through a file with a large number of lines (well more than a million) using the down arrow, the cursor eventually stops and will not go down further using the down arrow.

It is possible to page down or use the scroll bar to get further or select with a mouse or use the Go To command.

The line that seems to start the area with issues is 1118483. Once the down arrow stops moving occasionally down motion can be restarted by moving up and trying again.

Size of file doesn't seem to be an issue. I have seen this with a file that had more than two million lines, but at most one character per line. 

### Steps to Reproduce the Issue
1. Create a file with a large number of lines. One method, in windows, from the root directory run this command "dir /s>dir.txt"
2. Open the file.
3. Go to a point towards the end of the file (beyond 1118483)
4. Press the down arrow. If it does not stop try moving up and then down again.

### Expected Behavior
Down arrow always move cursor down

### Actual Behavior
Down arrow does not always move cursor down toward end of files with large number of lines.

### Debug Information
Notepad++ v7.6.6   (64-bit)
Build time : Apr  3 2019 - 23:52:32
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10 (64-bit)
Plugins : DSpellCheck.dll mimeTools.dll NppConverter.dll 

Have tried with plugins disabled.

**Comment by MetaChuh** [comment]
please remove the DSpellCheck plugin and check if it makes any difference.
DSpellCheck is known to produce performance issues on large files

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
(no extra account is needed, just use your github account to sign in)
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)

**Comment by Wyer-Byter** [comment]
I am still getting the same behavior. I am getting it on  another machine as well. The numbers aren't quite the same on the other machine, but the same behavior.

**Comment by MetaChuh** [comment]
@Wyer-Byter 

many thanks for your report.

please disable word wrapping on very large files, especially if they have very long lines.
please also set your language to normal text.

if above is set, i can not reproduce a lag with a locally stored 2.8mio lines test file.

note: if enabled word wrapping, or a highlighting lexer is the reason for your lag experience on files with a high line count, there would be nothing we could do at the notepad++ part, as this depends on the external project scintilla.

test machine:
<kbd>Notepad++ v7.6.6   (64-bit)
Build time : Apr  3 2019 - 23:52:32
Path : C:\Users\User\Desktop\npp.7.6.6.bin.x64\notepad++.exe
Admin mode : OFF
Local Conf mode : ON
OS : Windows 10 (64-bit)
Plugins : mimeTools.dll NppConverter.dll</kbd>

**Comment by Wyer-Byter** [comment]
Both of those are set that way.

I want to make sure I'm clear, it is not a lag. The down arrow stops working. Holding down the down arrow, suddenly the cursor stops moving, like it hit the end of the file, even when the cursor is in the middle of the file and screen. It is only the down arrow. I can proceed past that point Page Down, Right Cursor, using the scroll bar.

I did receive different results with a different machine (line where it seemed to start), which would seem to indicate a memory issue, but I have reproduced it in a file that was only 16 Mbs. And with the smaller file the line it stopped on was the same as the much larger file.  

I have also opened the same file with the Scintilla example editor without issue. I did use the 3.5.6 version.

But if it can't be found, it can't be found.

Thanks for your help.

**Comment by MetaChuh** [comment]
@Wyer-Byter 

many thanks for your understanding.

i can not reproduce a cursor stop when keeping <kbd>cursor down</kbd> pressed.
here's a short video. i can hold it down for ages without any stop, starting from e.g. line 2mio.
(file size: 122mb, lines: 2.8mio)

![scroll cursor down](https://user-images.githubusercontent.com/45773305/56305112-de2f8180-613f-11e9-9d70-8d49baee4ca0.gif)

best regards.
