### ISSUE TITLE
Theme bug in portable version v2

### ISSUE THREAD

**Issue by qx87** [notepad-plus-plus/notepad-plus-plus#5535]
I use portable version of NP++ on my USB flash stick. And I use non-default theme (Settings->Style configurator). Almost every time when I insert USB flash into another computer, I do not see my chosen theme.

That is because theme setting uses absolute file name. As far as I can see it is located in config.xml. Something like this:

`<GUIConfig name="stylerTheme" path="H:\Programs\Notepad++\themes\Deep Black.xml" />`

And of course after inserting USB flash into a computer its hosting OS imperatively assigns random drive letter for USB flash. Then NP++ fails finding selected theme and uses default one.

But portable version must avoid using absolute names anywhere. I think whether this setting should use relative name starting from NP++ path, such as

`<GUIConfig name="stylerTheme" path="themes\Deep Black.xml" />`

or portable NP++ should provide some environment variable like COMMANDER_PATH in Total Commander.

**Comment by qx87** [comment]
...and yes, it still persists in 7.6.6.

**Comment by sasumner** [comment]
Wasn't something supposed to be after "Something like this:" ?

**Comment by MetaChuh** [comment]
@qx87 

if you want to theme a portable version of notepad++, please do the following:
* set your style configurator to `Default (stylers.xml)`.
* replace your `Notepad++\stylers.xml` with `Notepad++\themes\Deep Black.xml`.
* restart notepad++.
* test the theme portability, by exiting notepad++, changing your usb drive letter, and starting notepad++ again from the new location.
you can also customise your now themed default stylers.xml to your needs.

note: as notepad++ portable shares the binary of the installed version, a switch to relative paths, to allow themes on portable versions, will not be done.

thank you for your help and best regards.

-----
```
general notes:

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
(no extra account is needed, just use your github account to sign in)
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)
