### ISSUE TITLE
remove consecutive duplicate lines in 7.6.6 removes all lines but one w/ this file. 1million line limit & EOL affects function as well

### ISSUE THREAD

**Issue by jawz101** [notepad-plus-plus/notepad-plus-plus#5538]
file is 2.7million lines long and it just removes everything but 1 line
[uniq_list.zip](https://github.com/notepad-plus-plus/notepad-plus-plus/files/3086139/uniq_list.zip)

This app can remove duplicates from the same file and in like a few seconds, though I don't know if it's perfect.
http://akelpad.sourceforge.net/en/index.php

**Comment by MetaChuh** [comment]
@jawz101 

verified and reproducible.
(7.6.6. x64 & x86)

remove consecutive duplicate lines will remove all lines but one on the given file (2'796'707 lines)


* 7.6.6. x64: only line 2438629 stays, rest is removed.
(freemarker/core/NonExtendedHashException)
* 7.6.6. x86: only line 2640801 stays, rest is removed.
(net/sourceforge/jeval/EvaluationHelper)

additional notes:
* if file ending is converted from `lf` to `cr lf`, **all lines are removed**.
* if file is trimmed to the firs 1'000'000 lines, all works as expected.

<kbd>Notepad++ v7.6.6   (32-bit)
Build time : Apr  3 2019 - 23:49:50
Path : C:\Users\User\Desktop\npp.7.6.6.bin\notepad++.exe
Admin mode : OFF
Local Conf mode : ON
OS : Windows 7 (64-bit)
Plugins : mimeTools.dll NppConverter.dll NppExport.dll</kbd>

<kbd>Notepad++ v7.6.6   (64-bit)
Build time : Apr  3 2019 - 23:52:32
Path : C:\Users\User\Desktop\npp.7.6.6.bin.x64\notepad++.exe
Admin mode : OFF
Local Conf mode : ON
OS : Windows 10 (64-bit)
Plugins : mimeTools.dll NppConverter.dll</kbd>

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
(no extra account is needed, just use your github account to sign in)
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)

**Comment by CookiePLMonster** [comment]
Does it stil happen on 7.7.1 with an upgraded Scintilla?

**Comment by sasumner** [comment]
@CookiePLMonster Is there a tie-in with this feature and Scintilla?  Seems like it would be all coded into Notepad++ core...

**Comment by CookiePLMonster** [comment]
Admittedly I don't know, I didn't check the code yet - but always worth to check something as simple, right?

**Comment by jawz101** [comment]
Personally, I wish the file didn't have to be sorted to remove the duplicates.  Perhaps sort & remove dups in one click, similar to how gedit for Linux does it.

**Comment by CookiePLMonster** [comment]
Still happens on v7.7.1.

**Comment by CookiePLMonster** [comment]
So removing duplicated lines is done by executing a following regular expression:
```
^(.*(\\r?\\n|\\r))(\\1)+
```

and it **is** done by Scintilla - and the crash happens somewhere inside it. I'm not sure how to gracefully get around signature checks (would like to avoid uncommenting code) so not sure if I can try with a self compiled Scintilla.

**Comment by jawz101** [comment]
I tried the above regex and it didn't work.  While I was at it I also tried several other regexxes from various posts suggested on stackexchange:

TOTAL LINES IN ORIGINAL FILE 2,797,650

^(.*?)$\s+?^(?=.*^\1$)
REPLACE WITH    NONE
RESULTING LINES 1,763,861
PERFORMANCE     SLOW

^(.*\r?\n)(\1)+  1,763,861 (fast)
REPLACE WITH    \1
RESULTING LINES 1,763,861
PERFORMANCE     FAST

(?-s)(^.+\R)\1+  1,763,861 (fast)
REPLACE WITH    \1
RESULTING LINES 1,763,861
PERFORMANCE     FAST

FIND            ^(.*)(\r?\n\1)+$
REPLACE WITH    \1
RESULTING LINES 1,763,861
PERFORMANCE     FAST

**Comment by AngryGamer** [comment]
@CookiePLMonster 
> I'm not sure how to gracefully get around signature checks (would like to avoid uncommenting code) so not sure if I can try with a self compiled Scintilla.

Simply compile .exe as debug rather than release. See [3cb8bc85](https://github.com/notepad-plus-plus/notepad-plus-plus/commit/3cb8bc85a1c64fd886d30388542380d172745147#diff-7fec46067447d7e861ce9c86d169fd4cR209)

**Comment by CookiePLMonster** [comment]
> @CookiePLMonster
> 
> > I'm not sure how to gracefully get around signature checks (would like to avoid uncommenting code) so not sure if I can try with a self compiled Scintilla.
> 
> Simply compile .exe as debug rather than release. See [3cb8bc85](https://github.com/notepad-plus-plus/notepad-plus-plus/commit/3cb8bc85a1c64fd886d30388542380d172745147#diff-7fec46067447d7e861ce9c86d169fd4cR209)

That actually doesn't help. `bool isSignatureOK = securityGard.checkModule(updaterFullPath, nm_gup);` still executes in Debug.

**Comment by AngryGamer** [comment]
> That actually doesn't help. `bool isSignatureOK = securityGard.checkModule(updaterFullPath, nm_gup);` still executes in Debug.

I guess 3baef49 broke it. Well that's too bad, that's how people usually avoided the signature checks. You could always make a new PR adding "#ifndef _DEBUG" around it. 😋

**Comment by CookiePLMonster** [comment]
> You could always make a new PR adding some "#ifndef _DEBUG" logic. 😋

#5884 :)

**Comment by dleborgne** [comment]
Been able to reproduce a similar problem with a [Unix (LF) 44073 lines file](https://github.com/notepad-plus-plus/notepad-plus-plus/files/3573350/roles.txt) and Notepad++ 7.7.1 (64 bits). The file is alphabetically sorted.  Using "Remove Consecutive Duplicate Lines" removed everything but 3 lines instead of 9 expected lines.

**Comment by sasumner** [comment]
@dleborgne I ran the operation on your data file under control of the debugger, and it seems that this operation is overwhelming the regular expression engine, in a similar manner to #4761.  

By this I mean that after a call to SCI_SEARCHINTARGET, SCI_GETSTATUS is not called to check for an error, so possibly (and definitely in your case) this type of error is not detected.  If I add in some logic to call SCI_GETSTATUS, I can see that it is returning a non-zero result (which indicates the error).

**Comment by sasumner** [comment]
As to a non-regular-expression rewrite of the functionality, here's a variant (definitely not tuned for speed) that could do the job (not ready to make a PR of this but wanted to keep track of it):

    void Notepad_plus::removeDuplicateLines()
    {
        _pEditView->execute(SCI_BEGINUNDOACTION);
        auto workingLineNumber = _pEditView->execute(SCI_GETLINECOUNT);
        auto workingLineContents = _pEditView->getLine(workingLineNumber);
        while (workingLineNumber > 0)
        {
            auto previousLineContents = _pEditView->getLine(workingLineNumber - 1);
            if (previousLineContents == workingLineContents)
            {
                auto workingLineStartPos = _pEditView->execute(SCI_POSITIONFROMLINE, workingLineNumber);
                auto previousLineStartPos = _pEditView->execute(SCI_POSITIONFROMLINE, workingLineNumber - 1);
                _pEditView->execute(SCI_DELETERANGE, previousLineStartPos, workingLineStartPos - previousLineStartPos);
            }
            else
            {
                workingLineContents = previousLineContents;
            }
            --workingLineNumber;
        }
        _pEditView->execute(SCI_ENDUNDOACTION);
    }
