### ISSUE TITLE
Status bar Toggle Shortcut

### ISSUE THREAD

**Issue by iori3000** [notepad-plus-plus/notepad-plus-plus#5540]
### Description of the Issue

Status bar has no color theme, // If we could, it would be good though
So To Using Dark Theme ppl, it could be eye strained by contrast,
So Normally I would like to turn Off the Status bar, of course I like longer edit window though,
but sometimes we need status bar,
But it takes too much steps to change On/Off, actually it takes 5 steps and some mouse moves?.
So, I suggest Show Status bar Toggle Shortcut

Hide Menu Bar shortcut Alt or F10 is so good,
How about F10 to Status Bar?

**Comment by Ekopalypse** [comment]
Do you know that you can already do this by using one of the scripting plugins and/or NppExec plugin?

**Comment by MetaChuh** [comment]
@iori3000 

thank you for your option idea of toggling the status bar.

this option will currently not be implemented as a default feature of notepad++ for all users.
if you wish, please visit us at the notepad++ community (link at the bottom) and, if possible, we could work out a personal script for your status bar.

thank you for your help and best regards.

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
(no extra account is needed, just use your github account to sign in)
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)

**Comment by sasumner** [comment]
I thought I already posted a script for this...I guess not.  Well here it is, in Pythonscript, each time it is run it will toggle the visibility of the status bar:

    try:
        show_status_bar
    except NameError:
        show_status_bar = True

    show_status_bar = True if not show_status_bar else False
    notepad.hideStatusBar(show_status_bar)
