### ISSUE TITLE
Trying to open a folder on a remote computer throws error

### ISSUE THREAD

**Issue by shahareldad** [notepad-plus-plus/notepad-plus-plus#5541]
### Description of the Issue
When opening a file, when trying to open a folder on a remote computer like this:
\\[SOME IP]\c$\some_folder I get back a message saying:
"c:\[SOME IP]\c$\some_folder cannot be opened
folder c:\[SOME IP]\c$\some_folder doesn't exist."

### Steps to Reproduce the Issue
1. press CTRL+O (or click open file from the menu)
2. In the file name enter a folder name which is located on a remote computer, e.g. 
    \\10.10.10.10\c$\inetpub\wwwroot
3. Get a message like so:
    "c:\10.10.10.10\c$\inetpub\wwwroot cannot be opened
    folder c:\10.10.10.10\c$\inetpub\wwwroot doesn't exist."

### Expected Behavior
The folder should be opened and I should be able to select a file from that folder

### Actual Behavior
I get an error message

### Debug Information
Notepad++ v7.6.6   (32-bit)
Build time : Apr  3 2019 - 23:49:50
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10 (64-bit)
Plugins : mimeTools.dll NppConverter.dll NppExport.dll XMLTools.dll 

This feature is very important as I need to open files in admin mode on a remote computer and currently I can't drag files in when the Notepad++ is in administrator mode.

**Comment by shahareldad** [comment]
Forgot one important thing... It used to work!!!
Thanks

**Comment by MetaChuh** [comment]
@shahareldad 

thank you for your detailed information.

please go to `settings > preferences > default directory` and activate `use new style dialog`, as seen at the screenshot below.

![Imgur](https://i.imgur.com/fibS0kv.png)

then try `file > open` again and enter an unc path like your example: `\\10.10.10.10\c$\inetpub\wwwroot`.
 if it exists, you should now be presented as usual, with the windows credential dialogue, or directly with your remote share content.

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
(no extra account is needed, just use your github account to sign in)
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)
