### ISSUE TITLE
Multiple Plugins not compatible with the latest Notepad ++ Version

### ISSUE THREAD

**Issue by Dardwizzle** [notepad-plus-plus/notepad-plus-plus#5544]
There are too many plugins that dont work to list. They either are not compatible with the latest version or not 64 bit compatible. 

i thought I would help myself on this issue, and see if I could compile some of them with the latest build environment, but I was not able to find where I can get this. 

This is highly frustrating. I understand that the app is free, and i totally respect the Dev perspective, but I don't understand why the plugin versions are all over the place as far as when and what versions they support (which all the ones I was looking for are not maintained). if I could assist with trying to build them against the latest buil;d env I would but I can not find the latest on that either :( Suggestoins?
Thanks

**Comment by MetaChuh** [comment]
please contact the plugin developers for support on plugins, as well as newer versions which are compatible with the latest versions of notepad++.

to install a selection of compatible plugins, please go to the notepad++ menu `plugins > plugins admin...` and search for your needed plugins.

thank you for your support and best regards.

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
(no extra account is needed, just use your github account to sign in)
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)
