### ISSUE TITLE
Should use JavaScript comment inside the script tag of HTML files

### ISSUE THREAD

**Issue by eight04** [notepad-plus-plus/notepad-plus-plus#5545]
### Description of the Issue

When using Ctrl+Q command to toggle one line comment inside a `<script>` tag, NPP injects an HTML comment.

See also #1850.

### Steps to Reproduce the Issue

1. Create an HTML file with the following content:
    ```html
    <!DOCTYPE html>
    <html lang="en">
    <head>
      <meta charset="UTF-8">
      <meta name="viewport" content="width=device-width, initial-scale=1.0">
      <meta http-equiv="X-UA-Compatible" content="ie=edge">
      <title>Document</title>
      <script>
        var foo;
      </script>
    </head>
    <body>
    </body>
    </html>
    ```
2. Put the cursor after `var foo;`.
3. Press Ctrl+Q

### Expected Behavior
The line should be changed to `// var foo;`.

### Actual Behavior
The line changed to `<!-- var foo; -->`.

### Debug Information
Notepad++ v7.6.6   (32-bit)
Build time : Apr  3 2019 - 23:49:50
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 7 (64-bit)
Plugins : mimeTools.dll NppConverter.dll NppExport.dll 

Maybe relate: https://github.com/notepad-plus-plus/notepad-plus-plus/issues/2411

**Comment by MetaChuh** [comment]
@eight04 

the scintilla editor component can not handle two different lexers at the same time, based on a section within a html file.

you have to switch to javascript to highlight, comment and uncomment your javascript section within your html file.

best regards.

**Comment by eight04** [comment]
Shouldn't this issue be marked as a bug (blocked by upstream) or feature request (to support nested language) instead of a question?

**Comment by MetaChuh** [comment]
similar topics have been filed as bugs or feature requests at the [scintilla tracker](https://sourceforge.net/p/scintilla/feature-requests/).

feel free to browse and/or file a new request at the scintilla project.
other than that, we can not solve this at the notepad++ part, and we don not have influence at the scintilla project.

many thanks and best regards.

**Comment by eight04** [comment]
Cross reference: https://sourceforge.net/p/scintilla/bugs/2103/

**Comment by eight04** [comment]
The dev suggested using `SCI_GETSTYLEAT` at the caret position. If the style is `SCE_HJ_*` then the cursor locates in a script tag and we can use a different comment style. It sounds like a simple workaround. WDYT?

**Comment by eight04** [comment]
@MetaChuh The scintilla bug is closed.

> Closing as this is application functionality that can be achieved with Scintilla.

**Comment by eight04** [comment]
Can still reproduce with Notepad++ 8.7
