### ISSUE TITLE
Bug: Function List parser require one additional whitespace after last '}', otherwise whole class's functions won't show

### ISSUE THREAD

**Issue by johnnytemp** [notepad-plus-plus/notepad-plus-plus#5546]
Notepad++ version: 7.6.6 (64-bit) on Windows 10.

E.g. Function List show nothing, i.e. no class & functions, with this Java Code (The file's last character is '}'), unless you add a newline after the last '}':

```
public class A {
    void f1() {
    }
    void f2() {
    }
}
```

**Comment by MAPJe71** [comment]
See of #1232, #1861, #2910 and #3095.

**Comment by ArkadiuszMichalski** [comment]
@sasumner Duplicate of https://github.com/notepad-plus-plus/notepad-plus-plus/issues/2910, maybe close this bug?
