### ISSUE TITLE
Find All in... feature request (formerly #1499)

### ISSUE THREAD

**Issue by DanielTheGreat** [notepad-plus-plus/notepad-plus-plus#5547]
MetaChuh closed this issue without any good explanation why, so I'm re-opening it, as suggested for unresolved issues.  S/he suggested I try Notepad++ version 7.6.6, which I did, but with no change to the unwanted behaviour.  If it was closed because the requested improvement was not thought worthy of doing, then please say so.

I don't use it often, but I like Notepad++ for the occasional coding (hobby) project! Just one little thing slightly annoys me, so I wondered whether others would agree to a small change to the way the 'Find All in...' feature operates...

I sometimes use 'Find All in All Opened Documents' (or the other one) to find all occurrences of a particular string that I want to check and/or edit. But if I search for a string (perhaps a variable or register name) that occurs twice (or more) in one line, the search results pane shows that line twice (or more). This simply clutters the search results, and seems to serve no useful purpose.

Here's an example:
define vca25 vca2_addr.bit.b5 // Voltage detection 0 enable bit

If I'm searching for 'vca2' to find everywhere the register is accessed, I don't need to see that line appear twice in the results; I just want to know every file and every line where that register appears.

Would it be practical (and acceptable to most users) to change the 'Find All' code such that when a string is identified in a particular file/line, that line is then skipped from further searching so it appears only once in the results pane?

I realise this will complicate the code a little, since I presume there is much common code between 'Find All in...' and 'Replace All in...' functions, whereas for 'Replace All in...' you do want every instance found, not just the first per line!

Thanks, Daniel
(Gerroa, Australia)

**Comment by krilbe** [comment]
I think this change should be optional, if implemented. I often use this type of search in Visual Studio, which also shows every occurrence on every line. This is great when the purpose is to find all references to something in order to assess if the reference needs to be modified due to some change to it or its semantics.

The V File Viewer also shows every occurrence on every line, I think.

**Comment by DanielTheGreat** [comment]
krilbe, I think you might have misunderstood the problem I'm commenting on...

Of course we want the Search to find every occurrence of a search term, but we don't need to have the same line DISPLAYED TWICE just because the search term appears twice in that one line.  I can't see that that achieves anything useful.

Daniel

**Comment by sasumner** [comment]
Check out my workaround presented in #1499

**Comment by sasumner** [comment]
This feature-request is REJECTED by the author of Notepad++ ( https://github.com/notepad-plus-plus/notepad-plus-plus/pull/9088#issuecomment-720016310 )
It will not be reconsidered.
Please do not open any new issues on this topic as they will be immediately closed.

The suggestion is to use this workaround:
* Set your _Search mode_ to _Regular expression_.
* Add the following to the end of your _Find what_ expression:  `(?-s).*`

Example 1: To show only the first hit on a line for `foo`, make your _Find what_ expression `foo(?-s).*`

If the literal text you are intending to search for contains regular expression metacharacters, add `\Q` to its start and `\E(?-s).*` at its end.

Example 2: To show only the first hit on a line for `*foo*`, make your _Find what_ expression `\Q*foo*\E(?-s).*`
