### ISSUE TITLE
problem with encoding 1253

### ISSUE THREAD

**Issue by tipasergio** [notepad-plus-plus/notepad-plus-plus#5548]
### Description of the Issue

Hi,
I fouind interesting think. When I save file with encoding 1253(GREEK) “ΚΠΖ” letters. Next time i open file is opens as OEM 855 encoding.
There is no any probliem if I write any other word in greek. My system is windows 7…
P.S. windows notepad does not have same problem.
### Steps to Reproduce the Issue

1. save file with encoding 1253(GREEK) “ΚΠΖ” letters.
2. reopen file

### Expected Behavior
file is opens as ansi encoding.
### Actual Behavior
file is opens as OEM 855 encoding.

**Comment by andrecool-68** [comment]
Disable `Autodetect character encoding`
`Settings > Preferences > MISC. > Autodetect character encoding`
This may improve the situation a little

**Comment by MetaChuh** [comment]
@tipasergio 

> P.S. windows notepad does not have same problem.

windows notepad.exe does not handle windows 1253 (greek) encoding. it would show up as `ÊÐÆ` in windows notepad.exe.

for compatibility to notepad.exe and similar applications, please use the standardised utf-8 file format, to create your file in either windows notepad.exe or notepad++.

> Expected Behavior
file is opens as ansi encoding.

**ansi encoding is not capable of handling these characters**, please use the standardised utf-8 file format, to create your file in either windows notepad.exe or notepad++.
**note**: windows notepad.exe will also warn you about unicode character loss when trying to save `ΚΠΖ` as ansi.

if you are on notepad++ 7.6.6, you will be able to open an utf-8 file containing `ΚΠΖ`.
as utf-8 it will also be detected correctly if you have autodetect character encoding enabled.
for all other scenarios, e.g. if you need windows 1253 to edit specific files of an older program, you will have to switch to it manually.
(in such case it is best is to have one file in utf-8 for editing, and exporting it to another file in windows 1253 when needed)

thank you for your help and best regards.

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
(no extra account is needed, just use your github account to sign in)
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)
