### ISSUE TITLE
SQL Language color gets confused 

### ISSUE THREAD

**Issue by RTSpeiss** [notepad-plus-plus/notepad-plus-plus#5551]
### Description of the Issue

The color of any code after '\' is the STRING2 color even though the string has been closed

### Steps to Reproduce the Issue

1. Enter the following code and save as Sample.SQL
SELECT * FROM ABC -- Color is correct
SELECT *, '\' AS DEF FROM ABC  -- Color after \ is incorrect
SELECT * FROM ABC -- Color is incorrect
2. Remove the backslash but not the quotes and the color changes to the correct color.
4. It seems the mere presence of the \ inside the single quotes is the trigger

### Expected Behavior

Correct colors ;)
### Debug Information

Notepad 7.6.6

**Comment by MetaChuh** [comment]
`\` is escaping `'` so the string is never closed with an second `'`

<img width="595" alt="" src="https://user-images.githubusercontent.com/45773305/56385173-aa775900-621e-11e9-9603-8d16832fe5df.png">

**Comment by RTSpeiss** [comment]
I don't believe T-SQL uses \ as an escape trigger and since the 
colorizing should believe that it is working with SQL I don't think the 
\ should trigger the color change.  I could certainly understand that 
for other languages but not SQL

The original SQL that I noticed this one was

   SELECT @sDBFilePath = LEFT(@sDBFilePath,LEN(@sDBFilePath) - 
charindex('\',reverse(@sDBFilePath),1) + 1)

In this case the '\' has to coded like this and is not intended (or 
understood by the SQL engine) as an escape character.

It's not a fatal problem but it does make my code look strange

Richard

**Comment by dail8859** [comment]
@RTSpeiss 

Disable `Treat backslash as escape character for SQL` then reopen the file.

---


![Untitled](https://user-images.githubusercontent.com/3694843/56536185-6ab8b600-652b-11e9-9964-e20c32529938.png)

**Comment by tcplomp** [comment]
The option moved to the Language page in preferences:
![2021-03-16 12_04_45-Preferences](https://user-images.githubusercontent.com/2871661/111232361-d8a28500-864f-11eb-8535-673379ef7cf0.png)
