### ISSUE TITLE
Horizontal position bug when replay a keyboard macro that moves 1 line down

### ISSUE THREAD

**Issue by JanDoggen** [notepad-plus-plus/notepad-plus-plus#5559]
I was editing a batch file for renaming some image files.
Notepad++ was not in column mode.
With the cursor in the position of the asterisk in the block of text directly below, I started recording a macro with these 3 keys:
   Backspace 1 DownArrow
So: Replace the second 0 with a 1, then move one line down.

ren IMG_20190422_132531.jpg 001.jpg
ren IMG_20190422_132544.jpg 002.jpg
ren IMG_20190422_132551.jpg 003.jpg
ren IMG_20190422_132601.jpg 004.jpg
ren IMG_20190422_132608.jpg 005.jpg
ren IMG_20190422_132618.jpg 006.jpg
ren IMG_20190422_132625.jpg 007.jpg
ren IMG_20190422_132635.jpg 008.jpg
ren IMG_20190422_132642.jpg 009.jpg
ren IMG_20190422_132819.jpg 00*0.jpg
ren IMG_20190422_132832.jpg 001.jpg
ren IMG_20190422_132840.jpg 002.jpg
ren IMG_20190422_132845.jpg 003.jpg
ren IMG_20190422_132851.jpg 004.jpg
ren IMG_20190422_132902.jpg 005.jpg
ren IMG_20190422_132910.jpg 006.jpg
ren IMG_20190422_132922.jpg 007.jpg
ren IMG_20190422_132933.jpg 008.jpg
ren IMG_20190422_132940.jpg 009.jpg

The bug:
Replay the keyboard macro (either with Ctrl-Shift-P or by clicking on the toolbar icon)
This is what you end up with:

ren IMG_20190422_132819.jpg 010.jpg
ren IMG_20190422_132832.jpg 011.jpg
ren IMG_20190422_132840.jpg 102.jpg
ren IMG_20190422_132845.jpg1003.jpg
ren IMG_20190422_132851.jp1 004.jpg

The horizontal cursor position is not properly maintained.
Correct behaviour would be:

ren IMG_20190422_132819.jpg 010.jpg
ren IMG_20190422_132832.jpg 011.jpg
ren IMG_20190422_132840.jpg 012.jpg
ren IMG_20190422_132845.jpg 013.jpg
ren IMG_20190422_132851.jpg 014.jpg

Running Notepad 7.6.6 under Windows 10

**Comment by dail8859** [comment]
This issue lies with the Scintilla component that Notepad++ uses internally...meaning it is outside the scope of the Notepad++ team. However, this exact issue is fixed in Scintilla v4.0.5 so whenever Notepad++ updates its version of Scintilla (which is currently in the works) this issue will not be present.

Scintilla change log for v4.0.5 states:

    Set the last X chosen when SCI_REPLACESEL called to ensure macros work when text insertion followed by caret up or down.
