### ISSUE TITLE
code color for .Htaccess

### ISSUE THREAD

**Issue by benchbiba** [notepad-plus-plus/notepad-plus-plus#5562]
Hi, 
Its simple suggestion, add color please to .htaccess files.

**Comment by ArkadiuszMichalski** [comment]
@ Possible solution: https://stackoverflow.com/questions/704025/htaccess-in-notepad. Also check UDL (https://github.com/notepad-plus-plus/userDefinedLanguages/blob/master/UDLs/Htaccess_bySilasBrill.xml).

**Comment by donho** [comment]
@benchbiba  In here you can even have dark theme:
https://github.com/notepad-plus-plus/userDefinedLanguages/blob/master/udl-list.md
