### ISSUE TITLE
README file is outdated and doesn't tell you how to build notepad++ on modern systems

### ISSUE THREAD

**Issue by tojaroslaw** [notepad-plus-plus/notepad-plus-plus#5566]
### Description of the Issue
I tried to follow the instructions to build notepad++ in visual studio, I even tried downgrading to a more compatible version, but I could never get it to build.  I'm running Windows 10, I tried clicking the links, but several of the links in the readme file are dead links.

### Steps to Reproduce the Issue
following the readme file

### Expected Behavior
To be able to build notepad++

### Actual Behavior
couldn't build notepad++

**Comment by MetaChuh** [comment]
@tojaroslaw 

our apologies for the outdated build documentation due to extensive lack of time.

please visit our notepad++ community to get and discuss the changing build procedures with internal and external devs.
example link: https://notepad-plus-plus.org/community/topic/13959/building-notepad-with-visual-studio-2015-2017

thank you for your help and best regards.

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
(no extra account is needed, just use your github account to sign in)
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)

**Comment by tojaroslaw** [comment]
@MetaChuh Thanks for your helpful and timely response!  Perhaps I'll try to resolve the issue myself since I finally got the project to build (although I'm not sure how).  You guys do a great job!

**Comment by tabarnakos** [comment]
I just ran into similar issues myself. I just started fresh with the latest [Win10 Hyper-V virtual machine](https://developer.microsoft.com/en-us/windows/downloads/virtual-machines/). It comes pre-installed with Visual Studio community edition, which is free to use for individuals or companies contributing to open-source software.

As a first step, I propose to change the wording of [Build.md](https://github.com/notepad-plus-plus/notepad-plus-plus/blob/master/BUILD.md#to-build-notepadexe) to be a bit more specific:

> 2. Build Notepad++ like a normal Visual Studio project.

Would become:

2. Build Notepad++ using Visual Studio 2017 for C++. If using a newer version of Visual Studio, you must install the *MSVC v141 - VS 2017 C++ x64/x86 build tools* component.

Unless you would prefer the *MSVC v141 - VS 2017 C++ x64/x86 Spectre-mitigated libs* ?

**Comment by tabarnakos** [comment]
In any case, I wanted to start contributing to some open-source projects, a maintainer could assign the issue to me.
