### ISSUE TITLE
OS hangs when opening more than two files at a time

### ISSUE THREAD

**Issue by Big--Mike** [notepad-plus-plus/notepad-plus-plus#5569]
### Description of the Issue
I have associated txt files with Notepad++, the command line is **"C:\Program Files (x86)\Office\Notepad++\Notepad++.exe" "%1"**

Selecting one or two files in explorer at a time and open them by pressing Enter works fine. Three or more files lead to a hang of my whole operating system. The user interface gets unresponsable. If Notepad++ is already open, all works fine.

### Steps to Reproduce the Issue
1. Associate txt files with Notepad++
2. Create a bunch of little text files
3. Make sure, Notepad++ is closed
4. Select them all in explorer and press enter

### Expected Behavior
Notepad++ opens a tab for each text file (works fine with one or two files here)

### Actual Behavior
The UI gets unresponsible, the whole Operating System hangs

### Debug Information
Notepad++ v7.6.6   (32-bit)
Build time : Apr  3 2019 - 23:49:50
Path : C:\Program Files (x86)\Office\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10 (64-bit)
Plugins : none

### Further information
I file a new issue, as this happens still on my system with the latest version. This is the same report as [4447](https://github.com/notepad-plus-plus/notepad-plus-plus/issues/4447), which was closed.
According to the closing message:
- I'm using Windows 10 x64, version 1809 at the moment
- As you see in the ne debug report, I'm also using the latest Notepad++ version 7.6.6
- I'm having this issue with local files, no network shares are involved
- The hang is not temporary, the whole operating system gets unusable
- I have the issue even with empty 0 Byte files, so file size doesn't matter
- I created the test files on my Desktop (Right click -> New...) and by copying the empty file a few times, so explorer limitations should not matter in this case

I know it's hard to find the problem if you can't reproduce it. What information could be helpful in addition?

**Comment by Big--Mike** [comment]
I have additional information for my special situation:
The problem happens in combination with another software I'm using:
[4t Tray Minimizer 6.07 (free version)](http://www.4t-niagara.com/tray.html)
The Software adds items to the window context menu and can also draw additional buttons on the toolbar, so it directly interacts with any windows.

If both are running, the described scenario happens, so my new description is:

**Steps to Reproduce the Issue**
- Install Notepad++ and [4t Tray Minimizer 6.07 (free version)](http://www.4t-niagara.com/tray.html)
- Configure 4t Tray Minimizer, so that it adds items to window context menu
- Associate txt files with Notepad++
- Create a bunch of little text files
- Make sure, Notepad++ is closed
- Make sure, 4t Tray Minimizer is running
- Select all the little text files in explorer and press enter

**Additional info**
- Adding an exception for Notepad++ to 4t Tray minimizer doesn't solve the problem
- As described above, there's no problem, if only a single file is opened
- As described above, there's no problem, if Notepad++ is already running

I'll report it also there and link to this thread.

**Comment by MetaChuh** [comment]
@Big--Mike 

we can not reproduce any issue, when opening multiple associated .txt files, directly from windows explorer, into notepad++ 7.6.6 and 7.7. on a clean system.

as your experience is not caused by notepad++ itself, we will not pursue this issue, nor attempt a fix to make it compatible with the issue causing application.

many thanks and best regards.
