### ISSUE TITLE
Website NpWiki++: allow new maintainers, or future plans for documentation?

### ISSUE THREAD

**Issue by pryrt** [notepad-plus-plus/notepad-plus-plus#5575]
I understand and agree with the reasons that Don closed down new-user registration for the NpWiki++ at http://docs.notepad-plus-plus.org/index.php/Main_Page .  

And I recognize that documentation is the least favorite activity of most software developers, and that Don shouldn't be expected to keep the documentation up to date all by himself.

But as the years have passed, the NpWiki++ documentation has fallen more and more out-of-date.  Some ask in places like the [Community Forum](https://notepad-plus-plus.org/community/), and we answer their questions or direct them to FAQ answers or other resources.  Others submit documentation bugs in the issue list ( #3572 ,  #3801, #3848 ) -- but those examples go unresponded and/or unfixed.  But for every post in the forum or the issues list (or presumably the [live support](https://gitter.im/notepad-plus-plus/notepad-plus-plus)), there are probably N>>1 other people who probably go away frustrated that the documentation is so out-of-date compared to the software, and switch editors.

It would be really nice if there was one official centralized (and collaboratively-based) documentation site.

I was wondering if it would be possible to add a few trusted people to be able to edit the [NpWiki++](http://docs.notepad-plus-plus.org/index.php/Main_Page) -- maybe privately asking some of the users who have contributed accepted pull-requests to the code-base, and maybe the top 20 [Community forum contributors](https://notepad-plus-plus.org/community/users/sort-reputation), and other trusted individuals you know of: ask whether they'd be willing to help with the documentation, and grant them an account for the NpWiki++ if they want it?  

If not that specific solution: are there any long term plans for updated documentation?  As alternatives to that NpWiki++, maybe use the [Github-based Wiki](https://github.com/notepad-plus-plus/notepad-plus-plus/wiki)? Or some other collaborative-documentation tool?  In any of these, Don could still restrict access to those he trusts.

I also understand that not all the codebase contributors and top Community Forum users would want to be responsible for documentation -- which is why I suggest asking them if they want to help.  I know if I were given edit permission there, I wouldn't suddenly re-write the whole docset... but I might occasionally tag a page as "this page is out of date; for now, you can see _such-and-such-post_ in the forum for updated instructions", or tweak phrasings as questions come up.  I often spend 10 minutes on an answer in the forums... I might start feeling like it's a more worthwhile use of my time to spend 10 minutes updating the collaborative docs instead, and try.  (Then again, like other documentation editors, I might eventually burn out on it.)  But I, at least, would want the opportunity to participate in improving the docs, even if I didn't make huge amounts of improvement at once.  (For those who haven't made the avatar connection, I am [PeterJones on the forum](https://notepad-plus-plus.org/community/user/peterjones))

**Comment by MetaChuh** [comment]
@pryrt

if this is considered to be done, i will give my vote for you as supervisor, based on your consistency and patience during the past years, as well as your ability to adapt guides to different capabilities, suiting professionals as well as casual notepad++ users.

i, and i guess all devs and community team regulars, would assist you with pleasure, providing small guides, which can then be adapted and categorised into a bigger, but still supervised and readable documentation.

many thanks and best regards.

**Comment by andrecool-68** [comment]
Well if you do help multilingual! Here is an example of Russian help localization: http://azjio.narod.ru/NppHelp

**Comment by sasumner** [comment]
I don't see this sort of documentation being multilingual, unless there are sufficient volunteers (e.g. one per language).  So I see Peter doing English (the "master" source), then @andrecool-68 porting that to Russian ...

**Comment by andrecool-68** [comment]
@sasumner 
I speak English only through a translator, but there is help.

**Comment by pryrt** [comment]
According to [this post](https://notepad-plus-plus.org/community/topic/17638/documentation-is-like-sex), @donho has decided on doing a GitHub repo of markdown files for the new documentation set.  Cool.  As soon as he announces where specifically where it is (I'm assuming [notepad-plus-plus/npp-usermanual](https://github.com/notepad-plus-plus/npp-usermanual)), we can close this issue.

**Comment by MetaChuh** [comment]
@pryrt 

the choice of markdown as base for the manual, will also allow us, to copy paste raw data parts from the manual to community requests (and vice versa) without having to reformat it again.
very cool.

**Comment by pryrt** [comment]
Since the new documentation project has started, I guess this issue is closed. :-)
