### ISSUE TITLE
Plugins Admin removes itself and all other plugins

### ISSUE THREAD

**Issue by rddim** [notepad-plus-plus/notepad-plus-plus#5576]
### Description of the Issue

Plugins Admin removes itself and all other plugins when removed manually installed plugins
### Steps to Reproduce the Issue

1. Manually install some plugin (for example [AutoSave_dll_1v60.zip](https://sites.google.com/site/fstellari/nppplugins/AutoSave_dll_1v60.zip?attredirects=0))
2. Go to `Plugins` > `Plugins Admin...` > `Installed`
3. Check the `AutoSave.dll` and click `Remove`

### Expected Behavior

To not remove Plugins Admin and other plugins
### Actual Behavior

After step `3` and N++ restart everything is removed
### Debug Information

Notepad++ v7.6.6   (64-bit)
Build time : Apr  3 2019 - 23:52:32
Path : D:\Install\Office Programs\Notepad++\notepad++.exe
Admin mode : ON
Local Conf mode : ON
OS : Windows 7 (64-bit)
Plugins : AutoSave.dll ComparePlugin.dll ShtirlitzNppPlugin.dll VisualStudioLineCopy.dll 

### Other Info
All the `7.6.x` versions are affected

**Comment by MetaChuh** [comment]
duplicate reference #5279

**Comment by SinghRajenM** [comment]
**Root Cause:**
For manually installed plugins, there is no value for `folder-name` in npp code. So `i->_folderName` is empty which could not make path as `C:\Program Files\Notepad++\plugins\AutoSave`. So the remove directory remains `C:\Program Files\Notepad++\plugins\` which does magic to remove complete plugin folder rather than `plugin\AutoSave`
```
else // op == pa_remove
{
	// add folder to operate
	updaterParams += TEXT(" \"");
	updaterParams += i->_folderName;
	updaterParams += TEXT("\"");
}
```


```
{
			"folder-name": "mimeTools",
			"display-name": "Mime tools",
			"version": "2.2",
			"id": "c89b2bb4ca3e8ae5e3f6d3169fcbe830165b330b1c4639ecb4149ed91fabba06",
			"repository": "https://github.com/npp-plugins/mimetools/releases/download/v2.2/mimetools.v2.2.zip",
			"description": "MIME plugin for Notepad++ implements several main functionalities defined in MIME (Multipurpose Internet Mail Extensions).",
			"author": "Don HO",
			"homepage": "https://github.com/npp-plugins/mimetools"
		},

```
