### ISSUE TITLE
No translation for Plugins menu

### ISSUE THREAD

**Issue by rddim** [notepad-plus-plus/notepad-plus-plus#5577]
### Description of the Issue

The `Plugins` menu is not translated when there is no plugins
### Steps to Reproduce the Issue

1. Go to `Plugins` > `Plugins Admin...` > `Installed` 
2. Remove all installed plugins

### Expected Behavior

To have translated `Plugins` menu
### Actual Behavior

After removing all plugins the `Plugins` menu is not translated
### Debug Information

Notepad++ v7.6.6   (64-bit)
Build time : Apr  3 2019 - 23:52:32
Path : D:\Install\Office Programs\Notepad++\notepad++.exe
Admin mode : ON
Local Conf mode : ON
OS : Windows 7 (64-bit)
Plugins : AutoSave.dll ComparePlugin.dll ShtirlitzNppPlugin.dll VisualStudioLineCopy.dll 

### Other Info
before
![npp_before](https://user-images.githubusercontent.com/8998791/56612308-b5fec180-661c-11e9-96ba-f2f33a21d2c5.png)

after
![npp_after](https://user-images.githubusercontent.com/8998791/56612319-be56fc80-661c-11e9-881e-994d0433036f.png)

All the `7.6.x` versions are affected

**Comment by MetaChuh** [comment]
@rddim 
if you haven't restored this test instance yet, could you please post a screenshot of the opened non translated plugins menu, to see all entries ?

many thanks

**Comment by rddim** [comment]
Yes, of course
![npp_after_opened](https://user-images.githubusercontent.com/8998791/56616689-a2f0ef00-6626-11e9-967d-3bedfb2c7fdb.png)

### Proper Debug Information
Notepad++ v7.6.6   (64-bit)
Build time : Apr  3 2019 - 23:52:32
Path : C:\Users\Home\Desktop\npp.7.6.6.bin.x64\notepad++.exe
Admin mode : ON
Local Conf mode : ON
OS : Windows 7 (64-bit)
Plugins : none

**Comment by andrecool-68** [comment]
@MetaChuh 
 @rddim 

Localization files are not to blame

![Безымянный](https://user-images.githubusercontent.com/3471892/56617069-902aea00-6627-11e9-9bef-c190e08e8deb.png)
