### ISSUE TITLE
Compare plugin started from CMD: comparison won't start automatically since N++ 7.6.6

### ISSUE THREAD

**Issue by Joey79100** [notepad-plus-plus/notepad-plus-plus#5579]
Hi there.
I don't know if this is the right place to ask, because it is about a plugin, but the issue appeared after the latest Notepad++ update so I thought it should be here. Plus the original author of the plugin left the project. Feel free to close this and tell me if this isn't the right place.

### Description of the Issue
I'm using the Compare plugin for Notepad++, and I have setup a commandline tool to launch Notepad++, open two files and automatically launch the comparison between them.
This has required me to download the `Compare.exe` file as explained in [this Stackoverflow answer](https://stackoverflow.com/a/41865459/8031843) and put it in the `Notepad++\plugins\ComparePlugin` folder.

Then, the files are called this way:
```
"C:\Program Files (x86)\Notepad++\plugins\ComparePlugin\compare.exe" "C:\file1.txt" "C:\file2.txt"
```

Now this used to work great, but yesterday there was a Notepad++ update (7.6.6), and since I installed it, the comparison doesn't start automatically anymore.

### Steps to Reproduce the Issue

1. Make sure you have the Compare plugin installed, and the `Compare.exe` file in your `Notepad++\plugins\ComparePlugin` folder.
2. Open a command line.
3. Run a comparison between two files by using a command like this one:
`"C:\Program Files (x86)\Notepad++\plugins\ComparePlugin\compare.exe" "C:\file1.txt" "C:\file2.txt"`

### Expected Behavior
Notepad++ opens the two files, and lauches comparison between them. 1st file (file1.txt) is on the left, 2nd file (file2.txt) is on the right.

### Actual Behavior
Notepad++ opens the two files (file1.txt in the first tab, file2.txt in the second tab), but it doesn't start the comparison. You have to manually launch the comparison, by clicking on the Compare button of the toolbar.

### Debug Information

Notepad++ v7.6.6   (32-bit)
Build time : Apr  3 2019 - 23:49:50
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10 (64-bit)
Plugins : ComparePlugin.dll mimeTools.dll NppConverter.dll NppExport.dll 

Thanks by advance to anyone who can help!

**Comment by MetaChuh** [comment]
@Joey79100 

thank you for asking, and providing all necessary, detailed information.

usually the right place for this would be our notepad++ community (link at the bottom),
as we have more space and man-power over there, but i hope i can give you enough info to get compare.exe running with this answer.

`compare.exe` from compare plugin 1.5.6.6 works on 7.6.6 32 bit, if using the matching old compare plugin 1.5.6.6, and the correct folder location, as seen at the screenast below.
(note: i haven't tried out, if compare.exe would also work with a newer `ComparePlugin.dll` yet)

the path of the executable should be at:
```
C:\Program Files (x86)\Notepad++\plugins\ComparePlugin\ComparePlugin\compare.exe
```
so basically it has to be moved another folder level, inside another `ComparePlugin` folder.
(the folder where e.g. sqlite3.dll should be)

the command line i used for this screencast is:
```
"c:\Program Files (x86)\Notepad++\plugins\ComparePlugin\ComparePlugin\compare.exe" "c:\Program Files (x86)\Notepad++\change.log" "c:\Program Files (x86)\Notepad++\change2.log"
```

screencast:
![compare exe](https://user-images.githubusercontent.com/45773305/56644361-d14ce980-667b-11e9-95c2-e5fcd00e88ed.gif)

if you can't get it to work, please visit us at the notepad++ community and we will try to help you on that as extensively as we can.

thank you for your help and best regards.

-----
```
general notes:

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
(no extra account is needed, just use your github account to sign in)
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)

**Comment by Joey79100** [comment]
Thank you for your answer! I'll open a thread on the forum ASAP.
