### ISSUE TITLE
Functions parameters hint on input suddenly missing

### ISSUE THREAD

**Issue by 1manfactory** [notepad-plus-plus/notepad-plus-plus#5584]
### Description of the Issue
Since the last update to 7.6.6 (32 Bit) I am desperatly missing the PHP function parameters hints. 

I did not change anything, just updated.

### Debug Information
Notepad++ v7.6.6   (32-bit)
Build time : Apr  3 2019 - 23:49:50
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 7 (64-bit)
Plugins : DSpellCheck.dll mimeTools.dll NppConverter.dll NppExport.dll

**Comment by MetaChuh** [comment]
@1manfactory 

thank you for your debug information.

please check if `C:\Program Files (x86)\Notepad++\autoCompletion\php.xml` exists.
it should be 418kb in size, and dated to 2016.12.26, on a stock notepad++ installation.

* if it does not exist, please download the 7.6.6. 32 bit installer from <kbd>[>>> here <<< ](https://notepad-plus-plus.org/repository/7.x/7.6.6/npp.7.6.6.Installer.exe)</kbd> and re-install it on top of your existing notepad++.
**important note:** make sure that `auto-completion files` is selected when re-installing.

* if it does exist, please go to `settings > preferences > auto-completion` and check that `function and word completion` and `function parameters hint on input` are activated, as seen at the screenshot below:

<img width="966" alt="Bildschirmfoto 2019-04-25 um 13 10 43" src="https://user-images.githubusercontent.com/45773305/56731782-98844180-675b-11e9-90fc-ad8a243aed8e.png">

thank you for your help and best regards.

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
(no extra account is needed, just use your github account to sign in)
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)

**Comment by 1manfactory** [comment]
Thank you very much for you fast support.

The php.xml file was indeed missing. The only files were: autoit, BaanC, batch, coffee and lua

This is a bit odd because I never used those languages nore have I ever knowingly activated them.

Indeed only those files are now pre chosen in the installation process. I have to chose PHP (and others I use) again.

Now everything is fine again.

Maybe someone should check on this because I have been using Notepadd++ now for 10+ years and I never encountered this before.

Thanks again

**Comment by MetaChuh** [comment]
@1manfactory 

you are welcome.

technical info:
this is a known one-time installer behaviour, due to the auto-completion folder structure changes.

the autocompletion files were located at `plugins\APIs` in older versions of notepad++.
now they are located at a more descriptive folder called `autoCompletion`.

once they are deployed to the `autoCompletion` folder, like on your system as of now, the next installer run will find them and automatically select them at a re-install or update.

many thanks and best regards.
