### ISSUE TITLE
Files saved in ANSI convert to UTF-8 when edited in GitHub

### ISSUE THREAD

**Issue by ChairmanMeowJP** [notepad-plus-plus/notepad-plus-plus#5585]
### Description of the Issue
I have a few dozen files that need to be saved in ANSI to show certain characters that UTF-8 does not like, the rest are fine as UTF-8. 

### Steps to Reproduce the Issue
1. Upload a file that is encoded in ANSI
2. Open in GitHub and edit
3. Save file, at top of file it says "We’ve detected the file encoding as ISO-8859-1. When you commit changes we will transcode it to UTF-8."

Is their a way to save in ANSI? If not it is a rather big issue. Thanks

**Comment by MetaChuh** [comment]
this is not the issue tracker for github.

please visit https://help.github.com/en for further information.

**Comment by ChairmanMeowJP** [comment]
Oh, oops. Fixed it anyway

**Comment by zaphida** [comment]
how?
