### ISSUE TITLE
Store recent files in own config file and optionally NOT store it in cloud folder

### ISSUE THREAD

**Issue by kintrupf** [notepad-plus-plus/notepad-plus-plus#5588]
Notepad++ saves the recent file list and window position in config.xml, which is synced to the cloud and then to other computers if the cloud feature is enabled in the settings of Notepad++.

This may be beneficial for some people, but I guess most are annoyed by seeing files in the recent list that do not even exist on the current computer.
It also leads to often updated and synced cloud config files, which in most cases would not be necessary because only the recent file list has changed.

My suggestion is to store these settings in a "local" configuration file and sync this to the cloud only if a new option is checked on the Cloud page in the settings.

This was already raised some years ago in issue #1121, but that issue was closed without action.

**Comment by MetaChuh** [comment]
many thanks for your cloud sync ideas.

please do the following, if you have 2 or more machines, where you would like to backup your settings e.g. to dropbox or onedrive, without syncing the recent file list or windows position to the other machine:

(note: we do not have any information about your setup, so we can only provide an example, using onedrive, one notebook and one stationary pc)

* open your `OneDrive` folder.
* create one folder called e.g. `Notepad++ PC` and one folder called e.g. `Notepad++ NoteBook`.
* go to both machines, open up notepad++ and go to `settings > preferences > cloud`.
* on the stationary pc set your cloud location path to `Notepad++ PC`.
* on the notebook set your cloud location path to `Notepad++ NoteBook`.
* close notepad++ on both machines for the changes to take effect.

after that, both notepad++ installs will not use the recent file list, or the last window position of the respective other install, but you will still have your settings backed up and reachable as files for comparison at both machines.

there is currently no need to change the behaviour of the cloud feature, as it works as designed.

thank you for your help and best regards.

-----
```
general notes:

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
(no extra account is needed, just use your github account to sign in)
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)

**Comment by sasumner** [comment]
@MetaChuh Doesn't the above technique create 2 copies of all the settings?  Thus, e.g., if you have never used Auto-indent and you turn it on while you are using "notebook" and you use only "notebook" for a week and decide OMG auto-indent is the best feature ever created by a man.  And then you have to switch to "PC" for some work and you find to your surprise that Auto-indent is not enabled (OMG, the Horror!). :)

**Comment by Korb** [comment]
@sasumner, it also seems to me that @metachuh is considering not the case of using cloud storage of settings that @kintrupf meant. The latter meant the use of two or more copies of N ++ with one (!) Set of settings. That is, if, for example, macro is added to the working computer, or the extension settings are changing, then these changes after auto-synchronization through one (!) Cloud folder will be conquered on the home computer. But the appearance on the home computer of dead links to recent documents from the working computer is undesirable. And vice versa.
