### ISSUE TITLE
Style Configurations Not Applied When Dragging Files to Another Instance

### ISSUE THREAD

**Issue by Cryptexx** [notepad-plus-plus/notepad-plus-plus#5589]
**Description of the Issue**

The style configuration for code is not being applied when drag/dropping subsequent files to a new window.

**Steps to Reproduce the Issue**

1. Open a file of any extension that Notepad++ has a style configuration for. 
2. Open up two more files.
3. Drag File #2 offscreen to open a new Notepad++ instance.
4. Drag File #3 to the new instance.

You'll notice that File #2 will have code highlighting. File #3 does not; neither will any subsequent file added to the new instance.

**Expected Behavior**

Code should be highlighted for any file when moving to new view.

**Actual Behavior**

Beyond the first file, any subsequent file will not have a code style markup applied.

**Debug Information**

Notepad++ v7.6.6   (64-bit)
Build time : Apr  3 2019 - 23:52:32
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10 (64-bit)
Plugins : mimeTools.dll NppConverter.dll

**Comment by sasumner** [comment]
Just a note on "nomenclature": This issue is meaning "another instance of Notepad++" even though the terminology used is all over the place:  

"...moving to another view"
"...to a new window"
"...when moving to a new view".  

This is not merely pedantic: the concept of a "view" in Notepad++ is something different than another "instance".

**Comment by MetaChuh** [comment]
@Cryptexx 

confirmed.
thank you for your debug information and details.

**verified issue:** tab to tab drag and drop, from one open notepad++ multi-instance window to another, breaks code highlighting on 7.6.6 x86 and x64.

* open two window instances of notepad++
* open e.g. config.xml in window 1
* drag the config.xml tab to window 2

the dragged and dropped config.xml is now shown as normal text at window 1.

**last version without this issue:** 7.6.3.

best regards

**Comment by SinghRajenM** [comment]
It seems to be duplicate of #4883, #4769, #3475, #3451 and may be few more.

@MetaChuh, are you sure about V7.6.3? I'm asking because similar defects were logged prior to V7.6.3 as well.

**Comment by MetaChuh** [comment]
@SinghRajenM 

you are correct, thanks and my apologies.
it only worked at the test, as my 7.6.3 had xml tools installed and i used xml files for testing.

i've re-checked now on w7 and w10 with clean test instances:
7.6.3 dnd also **not working** with highlighting on both window 7 & 10 (see screencast)

![7 6 3  w10 multiinst dnd not working](https://user-images.githubusercontent.com/45773305/56852625-c913d900-691d-11e9-930b-69ccec093060.gif)

<kbd>Notepad++ v7.6.3   (32-bit)
Build time : Jan 27 2019 - 17:20:30
Path : C:\Users\User\Desktop\npp.7.6.3.bin.multi\notepad++.exe
Admin mode : OFF
Local Conf mode : ON
OS : Windows 10 (64-bit)
Plugins : DSpellCheck.dll mimeTools.dll NppConverter.dll NppExport.dll<kbd>

**Comment by sasumner** [comment]
So what is really happening here is that the file that doesn't have the coloring is being loaded as type "Normal text file" for some reason. If you then go to the Language menu and select XML, then all is good (it gets colored and has a correct filetype on the status bar).

I noticed the same thing will happen if you use a right-click Explorer extension to send an XML file to a single instance of Notepad++.  It doesn't have to be Notepad++'s right-click association.  Note however that if you simply drag-n-drop from Explorer to N++, it works just fine.  (Not sure if that is or should be a separate "issue").

**Comment by AdamH12113** [comment]
This issue is still present in 7.7.1 (64-bit) under Windows 10.

**Comment by 5t9n3q7** [comment]
As above.

Additionally, (I use user xml defined highlighting for "golang"):
if you click on the file title bar and do - 'open in new window' or
if you click on the file title bar and do - 'move to new window'
then, in both cases the "defined by user" option is selected, with some default (none) colors.
Clone or move to second view - working well

**Comment by Cryptexx** [comment]
I just updated to the latest version (7.8.6) and noticed that this issue is no longer present. Not sure when it was fixed, but I verified that syntax highlighting is working as intended now. Closing.

**Comment by AdamH12113** [comment]
Confirmed; it's working for me in 7.8.5.

**Comment by Shizen** [comment]
For what it's worth, this is not working in 7.8.8.  I am still seeing the exact behavior described by `5t9n3q7`.
