### ISSUE TITLE
Notepad++ holds on to directories

### ISSUE THREAD

**Issue by ebonair** [notepad-plus-plus/notepad-plus-plus#5590]
### Description of the Issue
Notepad++ holds directories open when it doesn't need to.

### Steps to Reproduce the Issue
1. Create a directory testbug
2. Create a new file in notepad++ and save it to that directory.
3. Close the file in notepad++.
4. Try to delete the testbug directory. (You can't)

### Expected Behavior
Notepad++ should release directories when it no longer has any open files in them.

### Actual Behavior
Notepad++ kept the directory locked.

### Debug Information
N/A.

This occurred on Windows 10 Pro, notepad++ version 7.6.6 32-bit.

Currently there are two workarounds:
1) Close notepad++.
2) Create a new file and save it to a different directory. This will cause notepad++ to release the first directory.

**Comment by MetaChuh** [comment]
@ebonair 

your issue is not reproducible with the given information.
(see screencast below)

![7 6 6  file lock test](https://user-images.githubusercontent.com/45773305/56817881-bb3f5480-6846-11e9-83ed-bd3a037ec4a7.gif)

please check your plugins or external applications, like antivirus or file monitoring tools, for file locking behaviour.

thank you for your help and best regards.

-----
```
general notes:

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
(no extra account is needed, just use your github account to sign in)
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)

**Comment by ebonair** [comment]
Thank you for your quick reply. However, Process Explorer confirms that it is indeed notepad++ that is holding on to the directory.
http://www.junction404.com/bugtest.png

Meanwhile, I only have one instance of notepad++ running, and it has no files open: http://www.junction404.com/nothing_open.png

**Comment by ebonair** [comment]
I believe I have found the cause of the problem. It has to do with Notepad++'s most recent directory. If you go to File->Open, the dialog will start navigating from the most recently used directory. You will be unable to delete that directory while it is "most recent", even if you no longer have any open files there. Changing the most recent directory, say by opening a file somewhere else, will cause Notepad++ to release the original directory.

**Comment by ebonair** [comment]
The issue is in WinControls\OpenSaveFileDialog\FileDialog.cpp
There are calls to ::SetCurrentDirectory(dir), which I believe change the Notepad++'s working directory to the most recently used directory from the file selector dialog.
It seems that Windows will not allow you to delete a directory which has been claimed as a "working directory" by a program, and I can duplicate the directory-locking effect with the following C#:
```
		public static void Main(string[] args)
		{
			Environment.CurrentDirectory = @"c:\users\myname\testbugs";
			Console.WriteLine("Directory Locked.");
			Thread.Sleep(60000);
		}
```
When attempting to duplicate this bug, can you verify that the Open/Save file dialog initially points to the directory you are trying to delete?

An easy fix would be to cache the most recently used directory in a string instead of changing the working directory, unless there is some reason not to do that.

**Comment by sasumner** [comment]
FWIW, I can't duplicate @ebonair 's step-by-step results when running N++ 7.6.6 32-bit on Windows 7.  I can delete the folder with no problem.  Is this something specific to Windows 10? (or at least > Win7 ?)

**Comment by ebonair** [comment]
I tried and also can't duplicate this problem on Windows 7 Ultimate.
The bug doesn't happen on Windows Server 2019 or Windows Server 2012 either.
Unfortunately, I don't have Windows 8 available for testing.

-David
