### ISSUE TITLE
Re-loading the same text file over and over results in huge memory taken up

### ISSUE THREAD

**Issue by Morilli** [notepad-plus-plus/notepad-plus-plus#5595]
### Description of the Issue

I currently have a python program write to a text file. This text file gets saved every couple seconds and has a pretty large size; currently 60 MB with 800k lines. So when I try to view the file in notepad++, alt-tab, alt-tab back onto notepad++ it gives me a dialog asking to reload the file because another program has modified it. Doing this over and over results in notepad++ taking up more and more memory, about 110 MB per reload. This seems to stop when notepad++ is using 10 GB of RAM for that one single file. 

### Steps to Reproduce the Issue

1. Open a text file (potentially has to be large) that is constantly being modified by a different program.
2. Click away from the notepad++ window and back onto it to make the "reload file" dialog appear and click yes.
3. Repeat step 2.

### Expected Behavior

The file should get reloaded and notepad++ should use about as much RAM as before.

### Actual Behavior

Notepad++ takes up more and more RAM, seemingly adding up as much RAM as it initially used over and over again.

### Debug Information

```
Notepad++ v7.6.6   (64-bit)
Build time : Apr  3 2019 - 23:52:32
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10 (64-bit)
Plugins : JSMinNPP.dll mimeTools.dll NppConverter.dll NppSaveAsAdmin.dll 
```

**Comment by Ekopalypse** [comment]
Just to be sure that no plugin has caused this behavior, did you test this by running npp with the -noPlugin command line switch?

**Comment by Morilli** [comment]
No, but I just did and got the same behavior. It seems that notepad++ takes up about twice the opened file's size more in memory each time the file is reloaded.

**Comment by MetaChuh** [comment]
@Morilli 

reloading without monitoring will populate your undo buffer, which requires additional memory.

please restart notepad++ and activate `view > monitoring (tail -f)` for this file.
(alternatively press the eye icon at the toolbar.)
you will see an eye icon, instead of a disk icon, at the tab of this file, as soon as monitoring is enabled.

recheck if less memory is consumed as soon as monitoring is enabled.

thank you for your help and best regards.

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
(no extra account is needed, just use your github account to sign in)
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)

**Comment by SinghRajenM** [comment]
> populate your undo buffer

This is cause huge performance hit. Analysis is below (using 32 bit) - 
Opening a plain approx 30MB file consumes around 90MB RAM. Now 
1. Reloading this file 15 times, brings RAM utilize to 1.2 GB. And reloading around 23~25 times causes "File is too large to open" error.
2. When Auto detect is enabled along with "Update silently", then same file (30MB) after 23~25 will complain about "File is too large to open" error.

@donho this is really a performance hit which needs attention and MUST be fixed.

**Comment by dinkumoil** [comment]
As I already wrote at the community forum: 

Seems like the "Allow undo on reload"  feature has to be reverted or buffering of the old file content has to be moved over to the hard disk. But that would mean it would nearly double the automatic backup feature.

**Comment by MetaChuh** [comment]
verified bug.

when reloading an unchanged file, the memory consumption rises on each reload on 7.6.6.
when reloading a monitoring a file, the memory consumption also rises more than needed for the changes on 7.6.6, even if the undo buffer should not be populated.

@SinghRajenM & @dinkumoil 
thank you both for your testing and your patience.

-----

@SinghRajenM 
i like your concept of discussing and pre-discussing issues at the [community](https://notepad-plus-plus.org/community/topic/17530/performance-hit-due-to-allow-undo-on-reload/6) more extensively. 👍

this allows us to communicate and test in more details, as well as as with a wider helping audience, and still have an easy to read, short issue at the tracker, showing only the results.

i believe your concept is something we should extend, as it is a very logical approach.

many thanks and best regards.

**Comment by wqweto** [comment]
@polluks Don't revert a useful commit as the simplest fix for the issue at hand but think of a reasonable solution please.

How hard would it be to implement undo history limiter? Something like undo buffer being twice the file size? Or keep undo history back to previous reload only?

I can fix 90% of the issue in the tracker by reverting commits. . . and in the process leaving millions in tears of missing useful features.

**Comment by Davidebyzero** [comment]
@donho It was a very nasty surprise for me after I upgraded to a version that had this fix reverted. I lost work because of this.

This is the most important feature for me, and I have reverted to Notepad++ v7.6.6 because of it. Please bring this back and make it optional; until then I will not be able to upgrade.

**Comment by wqweto** [comment]
https://github.com/pnedev/compare-plugin/blob/master/src/Engine/diff.h

**Comment by Davidebyzero** [comment]
> https://github.com/pnedev/compare-plugin/blob/master/src/Engine/diff.h

@wqweto  So basically, Notepad++ already did this diffing for saving Reloads into the Undo buffer in your patch, but people complained about the memory usage anyway?
