### ISSUE TITLE
notepad-plus-plus.org should be in the HSTS Preload list

### ISSUE THREAD

**Issue by ilhansubasi** [notepad-plus-plus/notepad-plus-plus#5596]
https://hstspreload.org

**Comment by MetaChuh** [comment]
@ilhansubasi 

notepad-plus-plus.org has HSTS with long duration deployed, as seen at the screenshot below.
notepad-plus-plus.org has a qualys ssl ranking of a+ (highest ranking available).

**qualys ssl test result for notepad-plus-plus.org:**
<img width="1101" alt="Bildschirmfoto 2019-04-28 um 09 51 47" src="https://user-images.githubusercontent.com/45773305/56860894-b7711680-699b-11e9-98d8-9fafd715c853.png">

note: the hstspreload.org test you provided is **not an official google product**.
it is not even able to correctly detect the HSTS settings of microsoft.com, apple.com, google.com and all other major sites i've tested, including google.

**failed hstspreload.org test for microsoft.com**
<img width="821" alt="Bildschirmfoto 2019-04-28 um 09 57 21" src="https://user-images.githubusercontent.com/45773305/56860996-eb007080-699c-11e9-9672-cd6bb4730f3e.png">

**failed hstspreload.org test for apple.com**
<img width="821" alt="Bildschirmfoto 2019-04-28 um 09 57 42" src="https://user-images.githubusercontent.com/45773305/56861000-f358ab80-699c-11e9-8095-cb028c600db2.png">

**failed hstspreload.org test for google.com**
<img width="820" alt="Bildschirmfoto 2019-04-28 um 10 10 32" src="https://user-images.githubusercontent.com/45773305/56861078-e8eae180-699d-11e9-8284-f712b5b09c84.png">

thank you for your help and best regards.

-----
```
general notes:

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
(no extra account is needed, just use your github account to sign in)
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)

**Comment by ilhansubasi** [comment]
You are mistaken. HSTS Preload List is supported by all the biggest browsers.

https://www.chromium.org/hsts

> If you own a site that you would like to see included in the preloaded HSTS list you can submit it at https://hstspreload.org.

[Here](https://cs.chromium.org/chromium/src/net/http/transport_security_state_static.json?g=0&maxsize=15440050 it includes almost 70 000 domain names that were submitted through https://hstspreload.org) is the source code of Gogole Chrome.

Moreover [here](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Strict-Transport-Security#Preloading_Strict_Transport_Security) you can read: "Google maintains [an HSTS preload service](https://hstspreload.org/)". And this is [a source code file](https://hg.mozilla.org/mozilla-central/raw-file/tip/security/manager/ssl/nsSTSPreloadList.inc) of Firefox. These domains were submitted through hstspreload.org too.

Furthermore these domains are included in the HSTS Preload list:
* https://hstspreload.org/?domain=twitter.com
* https://hstspreload.org/?domain=whitehouse.gov
* https://hstspreload.org/?domain=torproject.org
* https://hstspreload.org/?domain=www.amazon.com
* https://hstspreload.org/?domain=teams.microsoft.com
* https://hstspreload.org/?domain=accounts.google.com
* https://hstspreload.org/?domain=gmail.com
* https://hstspreload.org/?domain=youtube.com
* Actually google.com is already in the list, on line [464](https://cs.chromium.org/chromium/src/net/http/transport_security_state_static.json?g=0&maxsize=15440050&l=464)
* https://hstspreload.org/?domain=facebook.com
* https://hstspreload.org/?domain=paypal.com


SSL Labs Test says that notepad-plus-plus.org is not in the list.
![not in the list](https://user-images.githubusercontent.com/762377/56864133-7f7fc880-69c7-11e9-8c3e-cd36b4ac3b2c.png)

**Comment by sasumner** [comment]
WTF...who cares?!!

**Comment by ilhansubasi** [comment]
@sasumner  because not being in the preload lists is a vulnerability for man-in-the-middle attack. Attackers care.

**Comment by nanderson11** [comment]
@MetaChuh It wasn't explained in the initial request, but HSTS preload is an additional step to HSTS. HSTS protects after the first request to the server, but being on the HSTS preload list also protects the first request. You can read more about it on the wiki page for HSTS, specifically it's limitations: https://en.wikipedia.org/wiki/HTTP_Strict_Transport_Security#Limitations.

As @ilhansubasi said, that IS the official site for the Chrome preload list. Microsoft.com isn't on the HSTS preload list and actually doesn't even have HSTS according to ssllabs. Www.microsoft.com has HSTS enabled but isn't on the preload list. Twitter.com however, has HSTS and is on the preload list.

HSTS preload has some strict requirements that probably make it difficult for really big sites to be on the preload list. If notepad-plus-plus.org meets the requirements to be on the preload list, though, it would definitely be a nice thing for security.
