### ISSUE TITLE
Comment/Uncomment is not working on Ubuntu..

### ISSUE THREAD

**Issue by erikdemarco** [notepad-plus-plus/notepad-plus-plus#5599]
Comment/Uncomment function is not working in Ubuntu OS.

Its really really simple to reproduce:
1. Just install notepad++ via ubuntu app store
2. open notepad++
3. type anything you like
4. try Comment/Uncomment function from the MENU BAR (it will not work)

note: it works just fine in Windows OS

**Comment by MetaChuh** [comment]
@erikdemarco 

we can not reproduce this on ubuntu 18.04.2 with notepad++ 7.6.6. installed from the ubuntu software center.

please update to ubuntu 18.04.2 and update or reinstall notepad++ 7.6.6. using the ubuntu software center or snap install.

**important notes:**
* you can not comment or uncomment normal text.
only programming language files, like .php, which have a specified comment style can be commented or uncommented.
* you first have to mark the section to be commented, or put your cursor at a line to be commented, but this also requires the file to be a programming language source code file, which has a commenting syntax.

thank you for your help and best regards.

-----
```
general notes:

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
(no extra account is needed, just use your github account to sign in)
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)
