### ISSUE TITLE
Fullwidth (CJK) characters aren't displayed correctly

### ISSUE THREAD

**Issue by bakatrouble** [notepad-plus-plus/notepad-plus-plus#560]
These are being displayed cropped:
![2015-07-24_13-08-52](https://cloud.githubusercontent.com/assets/7340354/8871287/2e9b1e2c-3205-11e5-8991-3663d348d0da.png)
and following halfwidth (non-CJK) ones are displayed on wrong positions:
![2015-07-24_13-10-05](https://cloud.githubusercontent.com/assets/7340354/8871311/728328e6-3205-11e5-893f-5b1e80f79245.png)

**Comment by donho** [comment]
On which zone? Could you elaborate?

**Comment by bakatrouble** [comment]
When I put fullwidth symbols (ie: 日) in text editing area (either pasting or typing them in) these aren't displayed correctly with default font (maybe, because these are wider than any alphanumeric symbol).
When I change font to one that supports CJK characters (ie: MS Gothic, it works weird for Hangul - Korean characters though) display becomes relatively correct
![2015-07-24_14-38-58](https://cloud.githubusercontent.com/assets/7340354/8872842/ee1d6690-3211-11e5-9a68-b5685436b240.png)
![2015-07-24_14-39-41](https://cloud.githubusercontent.com/assets/7340354/8872843/ee1d73c4-3211-11e5-9d08-062882975a85.png)

**Comment by donho** [comment]
I did some changes for this issue but I'm not sure if it is fixed since I cannot reproduce it.
Could you download this file:
https://notepad-plus-plus.org/temp/npp.7z
unzip it into a new created folder, then launch notepad++.exe.
Please let me know the result.

**Comment by bakatrouble** [comment]
![ss](http://i.imgur.com/3dVJIAZ.png)
The same

**Comment by donho** [comment]
@bakatrouble Could you reboot your system before testing?

**Comment by donho** [comment]
@bakatrouble I am sure, from the picture you provided, it's not the instance of what I just compiled for test. The red underline shouldn't be there because it comes from DSpellCheck plugin; whereas there's no plugins included in 
https://notepad-plus-plus.org/temp/npp.7z

**Comment by bakatrouble** [comment]
...Sorry, the problems were caused by the [MacType](https://code.google.com/p/mactype/) application ._.
Issue could be closed
