### ISSUE TITLE
Regex "(something)?a*anything" will match the whole file if there's a string of at least 9998 a's in the file

### ISSUE THREAD

**Issue by Runemoro** [notepad-plus-plus/notepad-plus-plus#5601]
### Description of the Issue

In regex search mode, the regex `(something)?a*anything`, where `something` and `anything` can be anything that's not inside the file, will match the whole file if the file contains a string of 9998 a's. If `a` is replaced with something else, such as `ab`, the match will only need 4999 repetitions of `ab` (so still 9998 total characters). In fact, `a*` can be replaced with any regex that can match a sequence of at least 9998 characters.

The `(something)?` can't be removed, but the `?` can be replaced with `*` or even `{0}`.

### Steps to Reproduce the Issue

1. Download test file here: http://pastebin.com/raw/J91rH8sG
2. Ctrl-F and enable Regular expressions
3. Enter "(something)?a*anything" in the box and click find next

### Expected Behavior

The match shouldn't return any result since "anything" is not in the file

### Actual Behavior

The whole file gets selected

### Debug Information

Notepad++ v7.6.6 (64-bit)
Build time : Apr 3 2019 - 23:52:32
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10 (64-bit)
Plugins : ComparePlugin.dll DSpellCheck.dll mimeTools.dll NppConverter.dll

**Comment by MetaChuh** [comment]
@Runemoro 

unfortunately this regex issue, when exceeding a certain repetitive string size, is still an issue of the latest boost regex engine, which is an external project, so there's currently not much we can do about it at the notepad++ part.

many thanks for your understanding and best regards.
