### ISSUE TITLE
Notepad++ Overwrites Folder Shorcuts Instead of Following Them

### ISSUE THREAD

**Issue by ChaosFreak** [notepad-plus-plus/notepad-plus-plus#5603]
### Description of the Issue
When saving a file while running under Windows 10, in the "Save As" dialog box, when you type the name of a folder shortcut, choose it from the autocomplete candidates, then press "Enter" to select it, instead of following the folder shortcut and opening that folder, Notepad++ tries to save the current file using the name of the folder shortcut, thereby overwriting the shortcut with the file.

### Steps to Reproduce the Issue

1. Choose "File -> Save As" (or "File -> Save" on a new file that hasn't been saved yet)
2. Begin typing the name of a folder shortcut in the "File name" field. (For example "Google Dr")
3. When the full name of the folder shortcut appears in the autocomplete list, press the down arrow until the folder shortcut is highlighted. (For example "Google Drive - Shortcut")
4. Press "Enter" to select the folder shortcut
5. Notepad++ responds with a dialog "Google Drive - Shortcut already exists. Do you want to replace it?"

### Expected Behavior
When you press enter to select a folder shortcut in an autocomplete list in a Save As dialog, the dialog should follow the shortcut and open the destination folder. This is how all Windows file picker dialogs work.

### Actual Behavior
Notepad++ doesn't follow the shortcut and instead tries to overwrite the shortcut with your text file.

### Debug Information
Notepad++ v7.6.6   (32-bit)
Build time : Apr  3 2019 - 23:49:50
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10 (64-bit)
Plugins : DSpellCheck.dll mimeTools.dll NppConverter.dll NppExport.dll 

![Notepad++ Bug Report SaveAs Shortcuts Screenshot](https://user-images.githubusercontent.com/4978796/56968826-dacdca00-6b31-11e9-80ef-58a1838d0be6.png)

**Comment by sasumner** [comment]
Check this setting, reasonable(!) people want it ticked.  :)
![image](https://user-images.githubusercontent.com/30118311/56970224-ab6c8c80-6b34-11e9-96fe-8248ad558e1e.png)

**Comment by ChaosFreak** [comment]
@sasumner  Brilliant!! This worked perfectly.
