### ISSUE TITLE
Right-to-left arrows horizontal navigation is reversed (BUG)

### ISSUE THREAD

**Issue by badryasuo** [notepad-plus-plus/notepad-plus-plus#5605]
Hey, devs... When I make Notepad++ Right-to-left by Ctrl+Alt+R; I've noticed that when I navigate through the LEFT && RIGHT arrows, they're reversed in direction. p.s I've got the latest version of Notepad++ as of the date of this post, to be precise, it is 7.6.6.

**Comment by MetaChuh** [comment]
@badryasuo 

unfortunately rtl is depending on the scintilla component, which is an external project.
even if the newest scintilla release would be implemented in notepad++, many rtl issues would still remain.

it is currently best to use notepad++ for ltr content only.

thank you for your understanding and best regards.

-----
```
general notes:

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
(no extra account is needed, just use your github account to sign in)
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)
