### ISSUE TITLE
v:6.8: Error in menu using Norwegian language

### ISSUE THREAD

**Issue by TorOle** [notepad-plus-plus/notepad-plus-plus#561]
Special characters in menu eg. Ø shows with other signs. 
![2015-07-24_111301](https://cloud.githubusercontent.com/assets/8268702/8871482/e6814738-31f5-11e5-91f0-bb7944873561.jpg)

**Comment by The2rB** [comment]
Bug seen here as well with "ø" (lower case) and "å" in the menu, and "ø", "å" and "Å" wrongly displayedin the drop down menus.

**Comment by The2rB** [comment]
The menu items are displayed correctly in the "Nynorsk" language, containing the same letters (æøåÆØÅ).

**Comment by TorOle** [comment]
I have solved the problem, but can't upload the file. 
The file norwegian.xml is rewritten and has been changed to UTF-8. 
You may download the file here: http://firmawebben.no/files/norwegian.xml
This should replace the old file at your notepad++ installation path, eg. c:\programfiles(x86)\Notepad++\localization\
