### ISSUE TITLE
[Feature Request] Improve usability in Shortcut mapper: Don't change the view when clicking in a Shortcut cell

### ISSUE THREAD

**Issue by rillig** [notepad-plus-plus/notepad-plus-plus#5612]
Extracted from #2563:

## Don't change the view when clicking in a Shortcut cell

When I click in a Shortcut cell, the list scrolls to the right, so that the Name of the command disappears. This leaves me in question which command I am actually editing.

**Comment by sasumner** [comment]
I have noticed this as well.  It doesn't happen if the window is first made bigger by dragging one of its corners.

**Comment by MetaChuh** [comment]
@rillig 

i can not reproduce this in notepad++ 7.6.6 x64 on windows 10 when clicking on a shortcut cell.

thank you for your help and best regards.
