### ISSUE TITLE
[Feature Request] Improve usability in Shortcut mapper: Rearrange the Shortcut editing controls

### ISSUE THREAD

**Issue by rillig** [notepad-plus-plus/notepad-plus-plus#5614]
Extracted from #2563:

## Rearrange the Shortcut editing controls

When editing a shortcut, a small dialog is shown.

The name field should not be a text box, but a label, since it is not editable anyway. For the purpose of copying the command name, the label text could be selectable.

The checkboxes should be arranged in a single row instead of a triangle, since the triangle arrangement doesn't have any meaning and deviates from common layout conventions.

The checkbox labels should be renamed so that they correspond to the names in the shortcuts, i.e. `Ctrl` instead of `CTRL`.

**Comment by sasumner** [comment]
>The name field should not be a text box, but a label, since it is not editable anyway
Meh... :)

>checkboxes should be arranged in a single row instead of a triangle
Agree.

>Ctrl instead of CTRL
My ctrl key also says "Ctrl" on it, so AGREE.  But, really, meh... :)

**Comment by MetaChuh** [comment]
many thanks for your feature request.

as millions of users are used to the current triangle checkbox design, implementing such feature would cause confusion, so for supportive reasons, we will leave it the way it is.

as many keyboards have a different design, having ctrl, Ctrl and CTRL, or Strg as in your case, it is not possible to choose a wording, without causing case sensitive conflicts with the variety of keyboards.

thank you for your help and best regards.

**Comment by sasumner** [comment]
>as many keyboards have a different design, having ctrl, Ctrl and CTRL, or Strg as in your case, it is not possible to choose a wording, without causing case sensitive conflicts with the variety of keyboards.

Well, that way _my_ point about the keyboard silkscreen, not the OP's...
