### ISSUE TITLE
Shortcut mapper: Support filtering by keyboard keys

### ISSUE THREAD

**Issue by rillig** [notepad-plus-plus/notepad-plus-plus#5616]
In the Shortcut mapper dialog, type `Ctrl` in the filter field:

![image](https://user-images.githubusercontent.com/3233724/57160360-d979f700-6de8-11e9-870b-552ffe4a7a44.png)

Expected: all entries from the table that use the Ctrl key are still shown.
Actual: all lines are hidden.

**Comment by sasumner** [comment]
Not a bad idea. Currently the Filter only applies to the "Name" column content.  Maybe it should be specifiable via checkboxes just what is being filtered?
