### ISSUE TITLE
Shortcut mapper: Support filtering by category

### ISSUE THREAD

**Issue by rillig** [notepad-plus-plus/notepad-plus-plus#5617]
![image](https://user-images.githubusercontent.com/3233724/57160576-6b81ff80-6de9-11e9-8487-1f991543e5cd.png)

I have entered `view` in the filter field at the bottom.
Expected: all entries from the View category were shown.
Actual: only commands that contain `view` in their name are shown.

**Comment by MetaChuh** [comment]
> Expected: all entries from the View category were shown.

i don't know much about expectations in germany, but if you get a christmas present for free in your country, do you also complain to the person, or family member, who gave it to you, that it does not meet your expectations ?

many thanks for your help and understanding.
best regards.

**Comment by sasumner** [comment]
Christmas present? LOL
I think you forgot the REJECT label. :)

**Comment by dinkumoil** [comment]
@MetaChuh 

Why do you attack @rillig in that personal way? If he would have used the issue report template you could read:

> **Expected Behavior**
> All entries from the View category were shown.
> 
> **Actual Behavior**
> Only commands that contain view in their name are shown.

I can't see a relevant difference to what he actually wrote. There is no reason to treat him like that. Moreover, you implicitly assume that all people in Germany are acting like him (in a way you don't like). Prejudices are always a bad basis for human interaction.

Both that's far beyond what one should write on an international project's issue tracker. Instead you should have explained to him his wrong expectations and how the search function in the shortcut mapper really works.

**Comment by MetaChuh** [comment]
@dinkumoil 

you are absolutely correct, my sincere apologies.
many thanks for your reminder and help.
best regards.
