### ISSUE TITLE
Font size of UI elements

### ISSUE THREAD

**Issue by h-h-h-h** [notepad-plus-plus/notepad-plus-plus#562]
Notepad++ doesn't go along with an increased font size of Windows 8.1, although it scales correctly. Especially important in the search-and-replace dialog.

**Comment by milipili** [comment]
Need an adaptive ui. Same as #568

**Comment by Rikk** [comment]
Not even Explorer goes well with just Font Size changes. People should go with changing DPI.

**Comment by h-h-h-h** [comment]
It's not a good image for these parts of Windows, and its annoying. But I strongly disagree in saying the existing font size option of Windows is not so important! It's something to pay attention to as a UI.

**Comment by Rikk** [comment]
Sure, it is another thing that can be improved, but nevertheless user must be aware some visual glitches happens here and there. Anyway, I feel it must not be hard to fix (for those familiar with UI things).

**Comment by h-h-h-h** [comment]
It has to be said that for some it makes a UI much more usable in the long run. You just prefer 200 % scaling over 240 % or similar. But reading is another thing than recognizing common UI elements like the X in the caption bar of a window. If it wouldn't be that important ClearType would not have been invented, e.g., which is appreciated by many.
