### ISSUE TITLE
"Folder as Workspace" doesn't deference Shortcut (.lnk) files, treats them as text files.

### ISSUE THREAD

**Issue by Donaldpherman** [notepad-plus-plus/notepad-plus-plus#5623]
When I'm using a "Folder as Workspace" and have a Shortcut (.lnk) file pointing to a folder I excepted Notepad++ to open the folder or show the folder in the "Folder as Workspace" project panel when I double click.  Instead notepad++ just open the shortcut file as a text or binary file.  This is not the desired results.  

![image](https://user-images.githubusercontent.com/3155787/57256168-c7779e80-700a-11e9-9718-5430bcf0215f.png)

### Debug Information
Notepad++ v7.6.6   (32-bit)
Build time : Apr  3 2019 - 23:49:50
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10 (64-bit)
Plugins : DSpellCheck.dll Explorer.dll MarkdownViewerPlusPlus.dll mimeTools.dll NppConverter.dll NppExec.dll NppExport.dll NppMenuSearch.dll VisualStudioLineCopy.Unicode.dll

**Comment by MetaChuh** [comment]
@Donaldpherman 

as notepad++ is a file editor and .lnk shortcuts are files, this behaviour is as designed and expected.
please use mklink to create symlinks or hardlinks, if you want to use external locations within a workspace folder.

thank you for your help and best regards.
