### ISSUE TITLE
One instance could contain multiple separate windows

### ISSUE THREAD

**Issue by sorein** [notepad-plus-plus/notepad-plus-plus#5627]
### Description of the Issue

This is a helpful app, but is it so hard to generate a new "window" (with multiple tabs) inside the same "instance"? Just like the "commonplace" Chrome or any other browser?

### Steps to Reproduce the Issue

1.  Open one window with 3 tabs.
2. Open another window with 2 tabs.
3. Windows 8/10 crashes.
4. Windows 8/10 opens.
5. Try to recover the work in Notepad++, but only one window is recovered.

### Expected Behavior

Both windows/instances should reopen.

### Actual Behavior

Only one window/instance reopens

### Debug Information

vers 7.6.6 (32-bit)

**Comment by MetaChuh** [comment]
@sorein 

many thanks for your questions.

> One instance could contain multiple separate windows

if you use one instance, please move your desired documents to the second view, as seen at the screenshot below, which is the recommended usage:

<img width="1027" alt="" src="https://user-images.githubusercontent.com/45773305/57289410-9a36f900-70bb-11e9-8fea-8b4512d6ade5.png">

> Windows 8/10 crashes.

if your system crashes frequently, it is recommended to check your hardware and/or reinstall your operating system.
it is not recommended to use unstable machines for productive tasks.

it is also recommended to save your files as often as you can, and do not use unsaved tabs, if their content might be of relevance.

you can also go to `file > save session` to save your favourite file lists for individual instances, and reopen them as you need them.
important note: please keep in mind, that the saved session will only contain your file locations amongst other parameters, but it will not contain your data.
you have to save your files as often as you can, or install the autosave plugin at the menu `plugins > plugins admin`.

for more questions about usage, please visit us at our notepad++ community.

many thanks and best regards.

-----
```
general notes:

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
(no extra account is needed, just use your github account to sign in)
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)

**Comment by sorein** [comment]
You have no idea what this is about. Please refrain from replying again.

**Comment by sasumner** [comment]
@sorein 

>You have no idea what this is about. Please refrain from replying again.

THAT'S the way to reply to one of the Notepad++ team members in order to get them to move your reported issue forward !
