### ISSUE TITLE
Multiline find-and-replace

### ISSUE THREAD

**Issue by h-h-h-h** [notepad-plus-plus/notepad-plus-plus#563]
Hello,

please enable multiline textboxes in the find-and-replace dialog.

With this feature enabled working with regular expressions could become more easy when putting `(?x)` at the beginning and thus making Notepad++ _very much more usable with respect to more complex regular expressions_ (examples: https://github.com/notepad-plus-plus/notepad-plus-plus/issues/778#user-content-multiline-regular-expression, https://github.com/notepad-plus-plus/notepad-plus-plus/issues/683#issue-99749202, https://github.com/notepad-plus-plus/notepad-plus-plus/issues/452#issuecomment-128483383). Get information about this modifier [here](http://perldoc.perl.org/perlre.html#/x).

It's also useful to be able to find text with line breaks without regular expressions (should depend on document's line break type).

There should be a setting for the meaning of some keys and key combinations:
- Either:
  - Use <kbd>Tab</kbd> to type tab character
  - Use <kbd>Enter</kbd> to type line break
  - Use <kbd>Ctrl</kbd>+<kbd>Tab</kbd> to advance control focus
  - Use <kbd>Ctrl</kbd>+<kbd>Enter</kbd> to find next occurence
- Or:
  - Use <kbd>Ctrl</kbd>+<kbd>Tab</kbd> to type tab character
  - Use <kbd>Ctrl</kbd>+<kbd>Enter</kbd> to type line break
  - Use <kbd>Tab</kbd> to advance control focus
  - Use <kbd>Enter</kbd> to find next occurence

The action of <kbd>Ctrl</kbd>+<kbd>Tab</kbd> would supersede switching the GUI tab when issue https://github.com/notepad-plus-plus/notepad-plus-plus/issues/777 is implemented.

Details:
- This feature would require the dialog to be resizable (and remember its size).
- The font of the textboxes should default to a monospace font that you can change, ideally with a light gray text background to identify spaces ([there are approvals](https://github.com/notepad-plus-plus/notepad-plus-plus/issues/449))
- There should be a draggable line for a proportion adjustment to change the heights of the find and replace textboxes, but not the sum these heights (hence being in between of these textboxes). This is because the replacement string might often be much shorter when using regular expressions.
- There should be a checkbox to let the replacement text get wrapped. This is because it can't be made more readable with a kind of `(?x)` modifier as with the find string so that it might have to be kept on one line.
- There should be no low size limit for the contents of the multiline textboxes (<q>Replace this big bunch of lines with that big bunch of lines</q> should always have success without silently truncating data).

See issue https://github.com/notepad-plus-plus/notepad-plus-plus/issues/452#issuecomment-128483383 for GUI design.

**Comment by MetaChuh** [comment]
we are closing this issue due to its age and multiple newer notepad++ versions since it was filed.

please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html).
if your issue persists, and it is still of relevance to you, please feel free to file a new issue.

thank you for your help and best regards.

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
```
[<kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd>](https://notepad-plus-plus.org/community/)
