### ISSUE TITLE
Add toml-lang syntax highlighting support

### ISSUE THREAD

**Issue by davidwed** [notepad-plus-plus/notepad-plus-plus#5631]
### Description of the Issue
https://github.com/toml-lang/toml

**Comment by MetaChuh** [comment]
please import one of the available user defined language modules for toml into notepad++.

for example: https://github.com/Theodor-Lindberg/NPP-TOML-Syntax
or: https://github.com/Fireforge/toml-notepadplusplus

both toml udl projects also have an installation guide and an issue tracker for support.

many thanks and best regards.

**Comment by ArkadiuszMichalski** [comment]
Was implemented:
https://github.com/ScintillaOrg/lexilla/commit/053e02a81864b810a8b523494e2e7b4b4a170cdd
