### ISSUE TITLE
Can't find text in python file

### ISSUE THREAD

**Issue by rolivav** [notepad-plus-plus/notepad-plus-plus#5633]
### Description of the Issue

I tried searching for the word "running" in a python file where there are at least a few occurrences of it, specifically in strings. To my surprise, it failed to find any of them.

It works if I only put "run". It does not work with "runn" or with any more characters though.

### Steps to Reproduce the Issue

1. CTRL+F
2. Write "running" in python file with several occurrences of running
3. Can't find the word at all.

### Expected Behavior

Should find the word and take me to it.

### Actual Behavior

Couldn't find the word at all.

### Debug Information

Notepad++ v7.6.6   (32-bit)
Build time : Apr  3 2019 - 23:49:50
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10 (64-bit)
Plugins : DSpellCheck.dll mimeTools.dll NppConverter.dll NppExport.dll 

![image](https://user-images.githubusercontent.com/1664301/57365667-d171dc80-7185-11e9-92cb-affe54697078.png)

**Comment by rolivav** [comment]
I attached an image where you can see one of the ocurrences highlighted in green. It was not found by the Find dialog, I found it manually.

**Comment by MetaChuh** [comment]
@rolivav 

i can not reproduce this, can you share this specific file ?
what file encoding does it show at the penultimate field on the right of the status bar ?

**Comment by ablebodied** [comment]
![image](https://user-images.githubusercontent.com/24402121/57443759-60afea80-7281-11e9-9242-309565837258.png)

I have the same problem ,there are many "epics" in the doc ,but if i use Ctrl + F ,only one is found. 
version : 7.6.6 (64 bit)

**Comment by MetaChuh** [comment]
@ablebodied 

thank you for your screenshot.

you have to disable `match whole word only` for your specific file (epics base), as seen at the screenshot below.

this file only contains one instance of the word `EPICS` as a whole word.
whole words always have to be surrounded by white spaces or line feeds.

<img width="1023" alt="" src="https://user-images.githubusercontent.com/45773305/57444938-90df9500-7251-11e9-841d-973e9cdf00ef.png">

best regards.

**Comment by sasumner** [comment]
Sigh.  Someday people will actually doubt their find-setup when the search they are performing doesn't match the text that they can plainly see is there.  Oh, wait, that would require noticing these options, perhaps for the first time.  READ THE UI.  In some cases it is not the greatest, but...

**Comment by ablebodied** [comment]
@MetaChuh  Thank you very much, it works
