### ISSUE TITLE
Is it possible to have a dark theme?

### ISSUE THREAD

**Issue by Wagnerp** [notepad-plus-plus/notepad-plus-plus#5637]
Just a question, is it possible to have a light/dark theme option, or is it already available?

**Comment by darkrain-nl** [comment]
Perhaps you can try Obsidian?

Settings-> Style configurator -> Theme "Obsidian"

**Comment by Wagnerp** [comment]
Thanks, personally I like to read code on a dark background, as it's easier on the eyes!
