### ISSUE TITLE
Named search-and-replace pairs

### ISSUE THREAD

**Issue by h-h-h-h** [notepad-plus-plus/notepad-plus-plus#564]
Please enable to save the text of the search and replace textboxes of the search-and-replace dialog as named pairs that you can view and select again at a later time. The options of check boxes and radio buttons should also be saved for a named pair. (A pair would be usable for search-only, too.)

This feature would make Notepad++ much more useful with regard to developing a chain of regular expressions that you have to apply, especially in combination with this feature: https://github.com/notepad-plus-plus/notepad-plus-plus/issues/563 .

**Comment by aaaxx** [comment]
Duplicate https://github.com/notepad-plus-plus/notepad-plus-plus/issues/452
