### ISSUE TITLE
Notepad ++ Becomes unresponsive when it can not find Files

### ISSUE THREAD

**Issue by bpersonick** [notepad-plus-plus/notepad-plus-plus#5641]
### Description of the Issue
Specifically for me, I have storage which is removable (through a junction to a Symlink to my Laptop)  When the laptop is removed from the network, NP++ will not notice immediately, but once it does (After any period of working with NotePad++ it seems to, be explicitly after clicking one file on the remote system) the whole thing freezes up and will not come back.  I have had it come back after an hour when I had clicked on one, and I select "no don't keep it in NP++) but it DOES keep it in NP+_+< which I only figured out after I waited for it another half hour and saw it now had a red con for that file, and then it went back to freezing again.

Previously NP++ didn't react this way when remote files were not accessible, it seems like it started happening after an update in Jan or Feb. (if my recollection is correct) as I have used NP++ this way for years.

### Steps to Reproduce the Issue

1. Create a Symlink to a remote location
1b) --Optional-- Create a junction to the symlink to get directory info reporting from Windows.
2. Open files form that location
3. Disconnect that remote location from being reachable.

### Expected Behavior
I expect Notepad++ to give up after checking files for a few seconds and make them all with a Red icon like it used to (Although I suggest a different color might be useful if you guys can have us designate some as being "remote")  When clicking on the individual files give us the option to close the file or leave it open until connection returns like it used to

### Actual Behavior
NP++ Hangs usually does not ask if you want to keep any files at all unless you click one, but it takes approximately 30 to 60 minutes for that come up so in all cases it's not very usable.

### Debug Information
Debug Information
Notepad++ v7.6.6 (32-bit)
Build time : Apr 3 2019 - 23:49:50
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : ON
Local Conf mode : OFF
OS : Windows 8.1 (64-bit)
Plugins : mimeTools.dll NppConverter.dll NppExport.dll

![2019-05-10 15_15_28-10 0 0 216 - Remote Desktop Connection](https://user-images.githubusercontent.com/41927875/57551480-20ab3f00-7337-11e9-856d-3214034f4313.png)
![2019-05-10 15_31_26-10 0 0 216 - Remote Desktop Connection](https://user-images.githubusercontent.com/41927875/57564575-2c6d2480-737c-11e9-94c2-2451cae320e6.png)

**Comment by MetaChuh** [comment]
@bpersonick 

i can not reproduce a hang on network symlinks, when disconnected while a file is open in notepad++, with 7.6.6. x86 on windows 10 and windows 7.



i've tested following symlinks to unc paths:
`mklink /D "C:\Users\User\Desktop\npp.test.files\mklink-unc-data-0918" "\\10.10.10.118\data-0918"`
and mapped drives to the same unc path:
`mklink /D "C:\Users\User\Desktop\npp test files\mklink-drive-z" "Z:\"`

i've opened the symlinks both ways, using `open` from within notepad++ and `edit with notepad++ from the explorer context menu.


is there something you have done differently, or can it be that windows 8.1 behaves different to 7 and 10 ?

<img width="1217" alt="" src="https://user-images.githubusercontent.com/45773305/57579344-fb374600-749a-11e9-9f08-3aaec9dc2d37.png">
<img width="1031" alt="" src="https://user-images.githubusercontent.com/45773305/57579345-fb374600-749a-11e9-83cc-3f4a82c56999.png">
<img width="1024" alt="" src="https://user-images.githubusercontent.com/45773305/57579346-fbcfdc80-749a-11e9-9337-f8924a1cc181.png">

<kbd>Notepad++ v7.6.6   (32-bit)
Build time : Apr  3 2019 - 23:49:50
Path : c:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10 (64-bit)
Plugins : ComparePlugin.dll DSpellCheck.dll HexEditor.dll mimeTools.dll NppConverter.dll NppExport.dll NppJumpList.dll</kbd>

<kbd>Notepad++ v7.6.6   (32-bit)
Build time : Apr  3 2019 - 23:49:50
Path : C:\Users\User\Desktop\npp.7.6.6.bin\notepad++.exe
Admin mode : OFF
Local Conf mode : ON
OS : Windows 7 (64-bit)
Plugins : ComparePlugin.dll mimeTools.dll nppcrypt.dll NppTextViz.dll _CustomizeToolbar.dll</kbd>

many thanks and best regards.

**Comment by bpersonick** [comment]
Hello Metah,

  Its actually Windows 2012 R2, NP++ just IDs it as 8.1.

I do most of my work on Windows 2012 R2.

Issue did not exist in past, I think 7.5.6 was fine.

Are you removing the device from the network so it is not reachable at all?

I am mapping to a junction to a symlink here is a generic example:

MKLINK /D "D:\Remote_Symlink\Laptop_C_Root"
 "\\Laptop\C$\Root\"

MKLINK /J "C:\Remote_Junction\Laptop_C_Root"
"D:\Remote_Symlink\Laptop_C_Root"

Half the time windows/notepad++ resolves this to, and displays the full UNC
path of the file even though I went through the link:

ie:  "\\Laptop\C$\Root\Some\folder\Path\File name.extention"

instead of:

ie:  "C:\Remote_Junction\Laptop_C_Root\Some\folder\Path\File
name.extention"

(Especially when the file is unreachable and NP++ is freezing I notice it
shows the UNC paths as being the unreachable file.)

We use junctions to Sym Links because of improved performance and reporting
when done that way.

In any case, if I return the laptop to the network position before rhe
issue occurs things are fine, if I don't ensure connectivity
sometimes adding the laptop resolves things quickly.

Ben
