### ISSUE TITLE
Feature Request: live and multiple search highlighting

### ISSUE THREAD

**Issue by Philosoph228** [notepad-plus-plus/notepad-plus-plus#5642]
It would be nice if there will be more advanced highlighting features for found matches in text, for example: highlighting **all** visible search matches on the screen, as it did when we double-clicking on some word. But out of search box, with e.g. functionality as regular expression match highlighting , different color highlights for regex capture groups, or other search matches (maybe previous or pinned). Or highlight match instantly when user typing a text.
What do you think about that?

**Comment by sasumner** [comment]
>highlighting all visible search matches on the screen

See the Mark feature.

>highlight match instantly when user typing a text.

See Incremental Search feature.

**Comment by Philosoph228** [comment]
Haha, sorry me. I've only now discovered mark tab for myself. Thank you for incremental search advice.
