### ISSUE TITLE
I just need notepad's text editing function

### ISSUE THREAD

**Issue by fanrongqitiancai** [notepad-plus-plus/notepad-plus-plus#5643]
I just need notepad's text editing function. Can I make it stand alone? How do I interact with it through a program? For example, read the selected text.

**Comment by MetaChuh** [comment]
@fanrongqitiancai 

> I just need notepad's text editing function. Can I make it stand alone? How do I interact with it through a program? For example, read the selected text.

unfortunately i can not understand your question.

please note, that the issue tracker is for source code related issues only.
please visit us at our [notepad++ community forum](https://notepad-plus-plus.org/community/) if you have general usage questions.

many thanks and best regards.

-----
```
general notes:

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
```
[<kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd>](https://notepad-plus-plus.org/community/)

**Comment by xylographe** [comment]
Without plugin you can select text and copy to clipboard in NPP. In the external program you read the clipboard (for example, `Clipboard.GetText()` in C#).
Small pieces of selected text can be passed using `"$(CURRENT_WORD)"` as command line argument .
