### ISSUE TITLE
Unable to install NppFTP

### ISSUE THREAD

**Issue by mknambiar** [notepad-plus-plus/notepad-plus-plus#5646]
### Description of the Issue

I am a Windows 10 64 bit user. I have the 64bit version of Notepad++ installed. I updated to version 7.6.6 today to realize that my previously installed FTP plugin for 64 bit Notepad++ was missing after to the update. I tried installing using the plug-in administrator - but it does not work.

### Steps to Reproduce the Issue

1.  Start Notepad++
2. Click Plugins
3. Click "Plugins Admin ..."
4. In the "Available" tab select NppFTP version 0.28.3
5. Click Install

### Expected Behavior

I expected the NppFTP plugin to be installed

### Actual Behavior

I got the pop-up error message saying something like the hash of the package is not correct and the package will not be installed. Detailed information is there in the attached file
![Notepad++ error](https://user-images.githubusercontent.com/17425637/57595781-b841a500-7564-11e9-869e-d67b37d30f94.png)

I am not sure if this problem is because of the earlier NppFTP package which I had manually installed.

**Comment by MetaChuh** [comment]
@mknambiar 

i can not reproduce this on notepad++ 7.6.6 x64 (w10 x64)
nppftp 0.28.3 should install corectly, as seen at the screenshot below.

the original `NppFTP-x64.zip` file, when downloaded from https://github.com/ashkulz/NppFTP/releases/download/v0.28.3/NppFTP-x64.zip , also has the correct hash `147ceab402952a5ebfc2f27efb7b820a1485b9eabf5e3f3901067e038387329c`,
(not `6a2c21f1ee0de1670a00ca3444a41f194432fbf36d7abd33788fda4c8b2f644e`)

<img width="993" alt="" src="https://user-images.githubusercontent.com/45773305/57605831-d3fa7a80-7567-11e9-9311-5a3867fb2314.png">

are you able to install other plugins using `plugins admin` ?
do you have any software installed on your system, that could modify the contents of downloaded files ?
please also try to delete your temporary files (delete the contents of your `%TEMP%` folder) and retry downloading nppftp.

thank you for your help and best regards.

-----
```
general notes:

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).
please file an issue as easy to understand and reproducible as possible.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
(no extra account is needed, just use your github account to sign in)
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)
