### ISSUE TITLE
Pin most recently used

### ISSUE THREAD

**Issue by messengert** [notepad-plus-plus/notepad-plus-plus#5649]
It would be nice to be able to "Pin" a file from the most recently used list. I open quite a few files, and this would be a nice feature to quickly get back to a file. A "Favorites List", if you will.

**Comment by sasumner** [comment]
Explorer plugin offers a favorites list.  Maybe 32-bit only plugin.  Maybe some other plugins as well do this?

**Comment by bpersonick** [comment]
I use the Projects feature to keep a list of frequently used files as well as grouping other files I am working on. 

I do wish it was a little more drag and drop or that we could multi-select and add open docs to, but even as it is it works well for keeping frequently used files.
![image](https://user-images.githubusercontent.com/41927875/58130008-14519c80-7be9-11e9-83db-24e63b23cbac.png)

**Comment by dail8859** [comment]
Closing as this is a duplicate of #3362 which has now also been closed.

**Comment by alankilborn** [comment]
Sort of a related Community request:  https://community.notepad-plus-plus.org/topic/24195
