### ISSUE TITLE
Tell regular expression engine (either in find-and-replace or about dialog)

### ISSUE THREAD

**Issue by h-h-h-h** [notepad-plus-plus/notepad-plus-plus#565]
Hello, <sup><sup><sup><sup><sup><sup><sup><sup><sup><sup>[ ](https://cloud.githubusercontent.com/assets/13482553/9612621/f12060c4-50e6-11e5-8566-57e798463806.png)[ ](https://cloud.githubusercontent.com/assets/13482553/9636603/a2ad91a8-519c-11e5-9fca-6f70bdabbb57.png)</sup></sup></sup></sup></sup></sup></sup></sup></sup></sup>

it would be useful if Notepad++ would have _the regular expression engine and its version_ written somewhere in the find-and-replace dialog (in a gray font if possible). This way, you won't be unsure which rules apply and you could easily go to the right reference for more information.

I think this is better than forcing users to research and remember for every tool which engine it uses. Notepad++ would be appreciated even more.

Possible location (if achievable, gray):

<pre>
+-Search mode--------------------------+
| ( ) Normal                           |
| ( ) Extended (\r, \n, \t, \x..., \0) |
| (*) Regular expression <a href="https://github.com/notepad-plus-plus/notepad-plus-plus/issues/816">(PCRE2 10.20)</a> |
|     [ ] . matches newline            |
+--------------------------------------+
</pre>

**Comment by GitMensch** [comment]
This sounds both useful and relatively simple to implement.

**Comment by MAPJe71** [comment]
IMO the About box (F1) is a more appropriate location for this kind of info.

**Comment by GitMensch** [comment]
Yes, that's correct. I suggest to do it the way Hackedit does it and list everything used and the versions of these libraries:
![hackedit](https://cloud.githubusercontent.com/assets/6699539/13016121/424524ba-d1bd-11e5-85a1-7a3ba0daed53.png)

Can I request a change of the issue tilte to "Show versions of all external libraries used in About Window"?

BTW: I really like the tabs in the about window and the information they show, to have this in NPP would be cool :-)

**Comment by h-h-h-h** [comment]
If there are others also wanting to see the information in the find-and-replace dialog, I would leave this option as something to seriously consider. Otherwise it would be okay for me to have it in the about dialog.

**Comment by MetaChuh** [comment]
we are closing this issue due to its age and multiple newer notepad++ versions since it was filed.

please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html).
if your issue persists, and it is still of relevance to you, please feel free to file a new issue.

thank you for your help and best regards.

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
```
[<kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd>](https://notepad-plus-plus.org/community/)

**Comment by GitMensch** [comment]
This issue persists completely, neither the Find&Replace nor the about dialog has any information about this (we got the debug Info in the meantime, but as it is no plugin it isn't listed there).

I reconsider it better to have the engine and its version as a tooltip in the find&replace dialog for "regular expression" and think this should be quite easy to implement, too.
