### ISSUE TITLE
Annoying language change after mouse block selection

### ISSUE THREAD

**Issue by andry81** [notepad-plus-plus/notepad-plus-plus#5650]
### Description of the Issue
Ctrl+Alt+mouse selection triggers input language to change after each Ctrl+Alt release.

### Steps to Reproduce the Issue
1. Set input language change on Ctrl+Alt combination
2. Open multiline text file
3. Click-set mouse for start caret position
4. Press Ctrl+Alt
5. Click-select for end caret position to initiate a multiline input
6. Release Ctrl+Alt (the input language will change)
7. press a printable localized character key
8. Repeat from (3)

The input language would change after each release of Ctrl+Alt in the above.

### Expected Behavior
Block change the input language on multiline mouse selection.

### Actual Behavior
The input language changes accidentally.

**Comment by Ekopalypse** [comment]
If there is a global hotkey set, then you cannot argue that npp behaves annoying.
Btw. on my system I have to press SHIFT+ALT to create a multiline caret

**Comment by MetaChuh** [comment]
@andry81 

please do not set ctrl+alt or shift+alt at your windows settings as hotkeys to change your keyboard layout or input language, if you need ctrl+alt or shift+alt in other applications.

many thanks and best regards.
