### ISSUE TITLE
Feature Request: F # (F sharp) Syntax highlighting

### ISSUE THREAD

**Issue by jamesmcguirepro** [notepad-plus-plus/notepad-plus-plus#5654]
### Description of the Issue
Add support for the F# language

### Steps to Reproduce the Issue
1. Open a .fsx or .fs file in Notepad++

### Expected Behavior
File is opened and syntax highlighted

### Actual Behavior
File is opened, but not syntax is highlighted

### Debug Information
N/A

**Comment by Ekopalypse** [comment]
There is no F# lexer support in scintilla, neither in the current not in the newest version.
You might use [ScintilluaPlusPlus](https://github.com/dail8859/ScintilluaPlusPlus)

**Comment by MetaChuh** [comment]
@jamesmcguirepro 

many thanks for your feature request.

we usually do not integrate languages at the notepad++ core, if they do not exist at the main scintilla editor component, which it is an external project.
but to suite your needs, you can install one of the available user defined languages for f#, and/or the associated ScintilluaPlusPlus plugin mentioned above.

please also see [>>> here <<<](https://www.google.com/search?q=notepad%2B%2B+f%23) for more f# integration possibilities.

-----
```
general notes:

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
```
[<kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd>](https://notepad-plus-plus.org/community/)

**Comment by rdipardo** [comment]
## Update (12/08/2020)

@jamesmcguirepro, you may want to try one of these UDLs:

- [default theme](https://gist.github.com/rdipardo/ede4aed93542286f36d21051b8b51238)
- [Obsidian theme](https://gist.github.com/rdipardo/e500e0e9053e8556350802cf8ab06583)

### [F# UDL][]

![FSarp_default_style](https://user-images.githubusercontent.com/59004801/101554851-6f8edf80-3985-11eb-80c6-7de89bce9dff.png)

### [F# UDL (Obsidian)][]
![FSarp_obsidian](https://user-images.githubusercontent.com/59004801/101555029-cac0d200-3985-11eb-865e-c9badab12a91.png)


[F# UDL]: https://gist.github.com/rdipardo/ede4aed93542286f36d21051b8b51238
[F# UDL (Obsidian)]: https://gist.github.com/rdipardo/e500e0e9053e8556350802cf8ab06583

**Comment by ArkadiuszMichalski** [comment]
Scintilla bug: https://sourceforge.net/p/scintilla/feature-requests/1287/

**Comment by jamesmcguirepro** [comment]
Added to Lexilla 5.0.0:

https://github.com/ScintillaOrg/lexilla/commit/de9c4f42b8a43aaaca8bfbac64af54cb6cfb1368

**Comment by rdipardo** [comment]
If anyone is still interested in this thread, there's [a plugin] that enables Lexilla's F# lexer based on file type [^1].

[^1]: *Requires N++ 8.4.3 or newer*

[a plugin]: https://github.com/rdipardo/NPPFSIPlugin#readme
