### ISSUE TITLE
Autocompletion - Brackets still broken

### ISSUE THREAD

**Issue by ganego** [notepad-plus-plus/notepad-plus-plus#5660]
### Description of the Issue
Auto-completion for brackets does not work in all cases.

### Steps to Reproduce the Issue
1) Enable autocompletion for brackets.
2) Type: (a(

### Expected Behavior
What I expect: (a())  
Obviously I want to create a matching closing bracket when typing an opening bracket.

### Actual Behavior
What I get: (a()  
No closing bracket at all.

### Debug Information
With 6.8.3 I get what I would expect.
See this old report where I showed which code lines are the problem: https://github.com/notepad-plus-plus/notepad-plus-plus/issues/1038#issuecomment-269977584

Just don't try to be smart or introduce any logic or anything - open bracket -> make closing bracket. Simple. No problems.  
Thank you.

**Comment by eight04** [comment]
This is annoying when writing JavaScript tests. What I type:
```js
it("some test", ([RightArrow] => {
```
Expected result:
```js
it("some test", () => {|})
```
Actual result:
```js
it("some test", () => {|}
```
And I have to type `[RightArrow])[LeftArrow][LeftArrow]` before adding the content.

**Comment by ArkadiuszMichalski** [comment]
@donho This was not fixed in https://github.com/notepad-plus-plus/notepad-plus-plus/issues/6078 (PR https://github.com/notepad-plus-plus/notepad-plus-plus/pull/7742)?
