### ISSUE TITLE
[Regression] 'Save As' on a file with version #.#, reverts to .txt.

### ISSUE THREAD

**Issue by AM-Valkyrie** [notepad-plus-plus/notepad-plus-plus#5667]
### Description of the Issue
[Regression]
When using 'Save As' on a file with a version #.#, the file type reverts to .txt.

### Steps to Reproduce the Issue

1. Create file named 'Test 1.0.py'
2. 'Save As', change name from 'Test 1.0' to 'Test 1.1' , hit 'Save' button

### Expected Behavior
File should be saved as Test 1.1.py

### Actual Behavior
File is saved as Test 1.1.txt

### Debug Information

I first noticed this bug in N++ 7.6.6.

Thanks,
Doug

Notepad++ v7.6.6   (64-bit)
Build time : Apr  3 2019 - 23:52:32
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10 (64-bit)
Plugins : mimeTools.dll NppConverter.dll

**Comment by MetaChuh** [comment]
@AM-Valkyrie 

please go to the notepad++ menu `settings > preferences > default directory` and activate `use new style dialog` as seen at the screenshot below.

![Imgur](https://i.imgur.com/fibS0kv.png)

then a save as with a `Test #.#.py` version change should work, regardless of your windows explorer extension settings.
note: it is recommended, that you disable the option `hide extensions for known file types` at your windows explorer settings, to be able to see your file extensions in an explorer window.

best regards.

-----
```
general notes:

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
(no extra account is needed, just use your github account to sign in)
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)
