### ISSUE TITLE
[Feature request] Dark UI

### ISSUE THREAD

**Issue by Steve505** [notepad-plus-plus/notepad-plus-plus#5669]
Hey there!
I was wondering if there will be an "dark mode" feature, which changes the appearance of the UI itself, as i think it looks awful when I'm using dark theme, and all around the code is bright, white interface.

Thanks,
Steve505

**Comment by Ekopalypse** [comment]
I don't assume that npp will ever introduce a feature,
which would allow to configure the UI based on the scintilla theme, 
as it, afaik, relies on the windows themes.
Windows 10 was the first version which introduced a real dark mode, so this would be a requirement.
Unfortunately I don't have Windows 10 so I can't say for sure that it is working like expected.

**Comment by MetaChuh** [comment]
@Steve505 

this request was rejected so many times, that i don't believe it will help to open it again and again.
if we change our minds about that, and we find an easy way to do it, or any contributor manages to do so, we will consider implementing it, but not before that.

many thanks and best regards.
