### ISSUE TITLE
Regex error

### ISSUE THREAD

**Issue by ventaquil** [notepad-plus-plus/notepad-plus-plus#567]
Hello, I have next part of code to analyze:

```php
    case 4:
        if($activity_count == 0){
            $mailing_type = 'new_follower_one';
        }
        else{
            $mailing_type = 'new_follower_many';
        }
        break;	
    case 2:
        if($activity_count == 0){
            $mailing_type = 'new_displayer_one';
        }
        else{
            $mailing_type = 'new_displayer_many';
        }
        break;	
    case 3:
        if($activity_count == 0){
            $mailing_type = 'new_commenter_one';
        }
        else{
            $mailing_type = 'new_commenter_many';
        }
        break;	
    case 1:
        if($activity_count == 0){
            $mailing_type = 'new_liker_one';
        }
        else{
            $mailing_type = 'new_liker_many';
        }
        break;
```

When I run next regex `(?:[\s]*.*?)*\$mailing_type = '([a-z_]+)';` and analyze the last part of code:

```php

        }
        else{
            $mailing_type = 'new_liker_many';
```

and press "Search" program hangs and after few seconds selects all text. This is my fault in regex logic? Or not?

Version: 6.7.9.2

**Comment by h-h-h-h** [comment]
I don't see why *all* text should be selected. I had similar issues with Notepad++ selecting all text when searching for a regular expression that was not supposed to select all text.

**Comment by ventaquil** [comment]
I don't see why N++ select everything too. :<

**Comment by milipili** [comment]
´.*´ is often a problem when dealing with regex. Perhaps you should try with a more restrictive one.

**Comment by ventaquil** [comment]
But there is not `.*` - I'm using `.*?`. However yes - problem is in this part of regex. So thank you, in future I will try build better expressions. :smile:
