### ISSUE TITLE
[Feature Request] Add a setting for choosing a custom width for the Line Number Margin, to avoid the annoyance of seeing the resizing process after line 999.

### ISSUE THREAD

**Issue by ancient-animal** [notepad-plus-plus/notepad-plus-plus#5670]
### Description of the Issue
From line 1 to 999 of a file, the space for the Line Number Margin is the same width. When it reaches 1000, the width increases, which causes my text to be shifted slightly. This is very annoying. Imagine scrolling up and down repeatedly near that point and seeing the shift multiple times. I assume that reaching the "10,000" point will cause another resize.

### Steps to Reproduce the Issue
1. Scroll past line number 999.
2. The width of the line number will increase, causing text to shift rightward.

### Desired Behavior
1. An option called "Constant Line-Number Width".
2. If my custom length is "5", the width of the margin will be the same size from line number 1 to 99,999. It won't cause a resize until it reaches line number 100,000.
3. The lowest number that people are allowed to choose should not be lower than "3", because Notepad++ already shows lines "1 to 999" without resizing.

If the creators of this program know the absolute limit of the size of a text file that this program can process, then set that as the maximum width that can be chosen.
Example:
If the creators know that current computers cannot open a text file that has 10 million lines, they should set the limit of the "Custom Length" setting to 7, so it can show "9,999,999" lines without the width of the line-number margin resizing.

Putting millions of lines in one file may be ridiculous, even if computers can handle it, but putting 10,000 lines in one program is not too strange, so the "Constant Line-Number Width" should definitely be allowed to be set to "5".

**Comment by pnedev** [comment]
That would be very much appreciated.

**Comment by sasumner** [comment]
+1.  Trying to set this via Pythonscript's editor.setMarginWidthN(0, ...) doesn't seem to visually change anything, or "stick".  Immediately after, a editor.getMarginWidthN(0) yields 29 which seems to be the original.

**Comment by pnedev** [comment]
@sasumner ,

True, I tried doing that from Compare plugin with no success and then checked Notepad++ code to see why. Notepad++ resets the margin width very often (at every SCN_PAINTED notification AFAIR).

**Comment by xylographe** [comment]
Perhaps, an option to use a fixed width, based on the number of lines (LineCount), might be more user friendly. For example, if there are less than 900 lines, set MarginWidth[0] to TextWidth("999"), if the number of lines is in [900..9900), use TextWidth("9999"), for [9900..99900) use TextWidth("99999"), etc.

**Comment by xylographe** [comment]
With unchecked "Display line number" in Settings > Preferences > Editing, Notepad++ seems to leave the line number margin unchanged. In LuaScript console,
```lua
editor.MarginWidthN[0] = editor:TextWidth(STYLE_LINENUMBER, "_999999")
```
With the `OnSwitchFile` and  `OnModification` events it might be possible to implement a custom scheme.

**Comment by sasumner** [comment]
@xylographe , ah, thanks for the hint about unchecking the preference setting!  After doing that I found that I could widen the margin width and have it stick with this line of Pythonscript code:

    editor.setMarginWidthN(0, editor.textWidth(STYLESCOMMON.LINENUMBER, "_999999"))

**Comment by awychong** [comment]
Would like to add that for me, the refresh on passing line 999 can take several seconds before I can continue editing on some files, particularly if the number of lines is very large (over 100,000).

**Comment by sasumner** [comment]
Valuable discussion of this issue is continued in the comments of the (now-closed) PR 8222

**Comment by Yaron10** [comment]
@donho,

https://github.com/notepad-plus-plus/notepad-plus-plus/commit/c9c2d1e3761154a3024d80dd3bd22db446987a0b is a nice and useful addition. 
Thank you for your work. :+1:

**Comment by rdipardo** [comment]
*F.Y.I.* There's a feature proposal on Scintilla's [mailing list](https://groups.google.com/g/scintilla-interest) that could mitigate this issue in the future:

> Applications may have a line number margin that widens or narrows depending on the number of digits needed to display all line numbers. A SC_UPDATE_LINE_COUNT flag for SCN_UPDATEUI can improve performance for this feature.
>
> <https://groups.google.com/g/scintilla-interest/c/O4R6zOtmO_M>
