### ISSUE TITLE
In the menu "File" localization disappears "Recent Files" and "Restore Recent Closed File"

### ISSUE THREAD

**Issue by andrecool-68** [notepad-plus-plus/notepad-plus-plus#5672]
![ce](https://user-images.githubusercontent.com/3471892/57989201-16f4aa80-7aa0-11e9-92fc-7089a8defc2f.png)

![ru](https://user-images.githubusercontent.com/3471892/57989202-16f4aa80-7aa0-11e9-833a-1ffac067582c.png)

![rus](https://user-images.githubusercontent.com/3471892/57989204-16f4aa80-7aa0-11e9-8021-087f4013df87.png)

**Comment by rddim** [comment]
I think it is fixed in #5557
