### ISSUE TITLE
Can't open files with certain file names

### ISSUE THREAD

**Issue by Fabian42** [notepad-plus-plus/notepad-plus-plus#5674]
### Description of the Issue
This report is just here to document that this behaviour exists, I don't really expect it to be fixed.
**Files with crazy Unicode mess in the file name can't be opened by Notepad++**, neither from Windows Explorer, not from the "open" dialogue.
Example:
t0rn글‮𝗑​👩‍👩‍👧‍👧 💣⇝🀟௵ ͬͦͬͬͤͬͦͬͬͤ ͤͬͦͬͬͤͬͦͬͬͤ ͬͦͬͬͤͬͦͬ🇩🇪ͬͤ,0 0 0﷽​​ţ̴̨̡̡̡̡̨̛̙̻͍̬̺͚͈̬̳͔̺͉̙̩̮̘̼̰̦͚̤̜̝̜̦̙͙̠̳̩̬͙̞̮̹͙̩̼̤̠̭̙̲̱̝̰͉͙̝̣̲̗͇͖̻͉͖͇̗̮̜̲̻̫̟͇̙̰̙̩͇͙̘͇̱͍̜̥̰̔̆̈́̓́̽͂̋̀̀̓̎̄̈́̈͌̉̈́͆̀̊̑̿̔̽̌͊͗͂̇̽̐̏͑͗́̉̄̋̏̈͑̇̈͛̓̑̐̃͋̎͘͘͘̕̕͝ͅͅ.txt
I don't know which part of this file name messes up Notepad++, I'm scared to edit anything in case it breaks more. :D
I created that file by pasting the content of another file, which contained a flag emoji, a family emoji, an RTL character, "\t\0\r\n" (Windows Explorer removed the backslashes from it), "glitch text" from [here](https://lingojam.com/GlitchTextGenerator), a character that appears wider even in monospace, text that is somehow stacked vertically by the power of Unicode magic, etc.

### Steps to Reproduce the Issue
1. Download file: 
[t0rn글‮𝗑​👩‍👩‍👧‍👧 💣⇝🀟௵ ͬͦͬͬͤͬͦͬͬͤ ͤͬͦͬͬͤͬͦͬͬͤ ͬͦͬͬͤͬͦͬ🇩🇪ͬͤ,0 0 0﷽​​ţ̴̨̡̡̡̡̨̛̙̻͍̬̺͚͈̬̳͔̺͉̙̩̮̘̼̰̦͚̤̜̝̜̦̙͙̠̳̩̬͙̞̮̹͙̩̼̤̠̭̙̲̱̝̰͉͙̝̣̲̗͇͖̻͉͖͇̗̮̜̲̻̫̟͇̙̰̙̩͇͙̘͇̱͍̜̥̰̔̆̈́̓́̽͂̋̀̀̓̎̄̈́̈͌̉̈́͆̀̊̑̿̔̽̌͊͗͂̇̽̐̏͑͗́̉̄̋̏̈͑̇̈͛̓̑̐̃͋̎͘͘͘̕̕͝ͅͅ.txt](https://github.com/notepad-plus-plus/notepad-plus-plus/files/3202068/t0rn.0.0.0.t.txt)

2. Try to open it.

I hope Github gives a proper download for this file. If not: It's just a regular text file with the content "a" and the above mentioned file name.

### Expected Behavior
Honestly, I expected this. But I guess there could at least be an error message.

### Actual Behavior
Can't open file. No error message, Notepad++ just does nothing (or closes the "open" dialogue).

### Debug Information
Notepad++ v7.6.6   (32-bit)
Build time : Apr  3 2019 - 23:49:50
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 7 (64-bit)
Plugins : ComparePlugin.dll DSpellCheck.dll mimeTools.dll NppConverter.dll NppExport.dll

**Comment by Fabian42** [comment]
Oh wow, Github actually deals surprisingly well with all of this. The RTL character of course makes everything look even worse than it already does, but at least it doesn't magically increase the height of every single line on this page, like it does in the Eclipse console. It even displays the emoji!
The only problem that I can see is that the file gets a normal name ("t0rn.0.0.0.t.txt") when downloaded, but you can just rename it by copy-pasting the name from the report, it should still have most of the crazy Unicode characters in it.

**Comment by sasumner** [comment]
@Fabian42 said:

>neither from Windows Explorer,

Sure seems like you should figure out that aspect FIRST, then take what you learn from that and then see if you think Notepad++ still has an issue...before creating an issue here.  My 2c.

**Comment by andrecool-68** [comment]
**What does this code mean on this page, is everyone seeing this or just me?**


![Безымянный](https://user-images.githubusercontent.com/3471892/58093612-8620ea80-7bd7-11e9-8fb8-992586e1b007.png)

**Comment by Fabian42** [comment]
> @Fabian42 said:
> 
> > neither from Windows Explorer,
> 
> Sure seems like you should figure out that aspect FIRST, then take what you learn from that and then see if you think Notepad++ still has an issue...before creating an issue here. My 2c.

Figure out what? It's not a Windows Explorer issues, I can open the file just fine in notepad.exe.

**Comment by Fabian42** [comment]
@andrecool-68 Yes, that is the crazy Unicode stuff.

**Comment by sasumner** [comment]
@Fabian42, ah...from the way you said it, it seemed like Explorer was having trouble with such filenames as well...

I may retire from computing if typical filenames start looking like this.  :)

**Comment by sasumner** [comment]
@andrecool-68 Maybe as a group we can designate such filenames as too ridiculous to consider? :)

**Comment by andrecool-68** [comment]
@sasumner What is the connection with my question?

**Comment by MetaChuh** [comment]
@Fabian42 

i can not reproduce this on notepad++ 7.7, with `use new style dialog` enabled, on windows 10, as seen at the screenshot below.
are you still using wine on debian ?

<img width="938" alt="Bildschirmfoto 2019-05-21 um 14 08 14" src="https://user-images.githubusercontent.com/45773305/58094916-0f352300-7bd2-11e9-89fa-47fa96d99061.png">

but even if it would be reproducible, as you correctly expect, we would not pursue fixing it, due to the unlikely matter of having such file names on purpose.

Notepad++ v7.7   (32-bit)
Build time : May 19 2019 - 13:08:20
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10 (64-bit)
Plugins : mimeTools.dll NppConverter.dll NppExport.dll NppJumpList.dll

**Comment by Fabian42** [comment]
This one was on a regular Windows 7 laptop.

**Comment by MetaChuh** [comment]
@Fabian42 

if you like to share and work out such things extensively, with a wider audience of internal and external devs, as well as power users, you are very welcome to visit us at our notepad++ community forum. (link at the bottom)

best regards.

-----
```
general notes:

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
(no extra account is needed, just use your github account to sign in)
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)
