### ISSUE TITLE
Word wrap shortcut

### ISSUE THREAD

**Issue by shwetazilpe** [notepad-plus-plus/notepad-plus-plus#5675]
Hi,
I am an extensive user of Notepad++ and really like the product. I don't have any issue with the product but its actually a feature request. I always need to go to menus for switching between word wrap and no word wrap. It would be really helpful if you can add a keyboard shortcut for this functionality.
Thanks in advance!

**Comment by MetaChuh** [comment]
@shwetazilpe 

please go to the notepad++ menu `settings > shortcut mapper` search for `wrap` and set e.g. `ctrl+alt+w` or any other not yet used shortcut for `word wrap`

best regards.

-----
```
general notes:

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
(no extra account is needed, just use your github account to sign in)
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)

**Comment by sasumner** [comment]
@shwetazilpe I question how much of an "extensive user" you are if you don't know that command keycombos can be remapped.
