### ISSUE TITLE
JSP syntax highlighting broke

### ISSUE THREAD

**Issue by jonahgreenthal** [notepad-plus-plus/notepad-plus-plus#5677]
### Description of the Issue
In the latest release, JSP syntax highlighting changed.

Code blocks between `<%` and `%>`, and `<%=` and `%>`, used to be light blue. Now they are white, the same as everything else, so they are much less distinguished.

I am not entirely sure I'm describing _what_ used to be light blue correctly. I just know there's no light blue anymore, and I'm very used to it.

I don't see any mention of syntax highlighting changes in the changelog, so this must be inadvertent. Maybe it's a side effect of the Scintilla upgrade? Either way, I'd really appreciate getting the old syntax highlighting (or some similar visual distinction for `<%…%>` and `<%= … %>` code blocks) back.

If it would help, I can provide screenshots of the new behavior, and if really necessary I can also try installing an old version and showing how that looked.

### Steps to Reproduce the Issue
1. Open a JSP file (with JSP syntax highlighting enabled)

### Expected Behavior
Code blocks would be highlighted in light blue.

### Actual Behavior
Code blocks have no background or other visual distinction throughout them (just a yellow background on the `<%`, `<%=`, and `%>` tags themselves).

### Debug Information
```
Notepad++ v7.7   (64-bit)
Build time : May 19 2019 - 13:05:35
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10 (64-bit)
Plugins : mimeTools.dll NppConverter.dll NppFTP.dll 
```

**Comment by dail8859** [comment]
Please post a code snippet. A screen shot would also be helpful. Believe it or not, most people dont have a JSP file readily available.l to test this with.

**Comment by jonahgreenthal** [comment]
Here's Notepad++ 7.6.6 Portable:
![image](https://user-images.githubusercontent.com/737172/58381638-e8397100-7f84-11e9-9ce9-cb8a251366ca.png)

Here's the same file in 7.7 (non-Portable):
![image](https://user-images.githubusercontent.com/737172/58381645-0010f500-7f85-11e9-9844-4383cfd002e1.png)

Here's the file contents:
```
This text isn't in a tag.
<%  scriptlet tag %>
<%@ directive tag %>
<%= expression tag %>
<%! declaration tag %>
<%/ comment %>
<jsp:x tag />
```
```

**Comment by donho** [comment]
@jonahgreenthal 
Could you use the following binary instead of your original one:
https://notepad-plus-plus.org/temp/SciLexer.dll
And confirm me if this regression is fixed ?

**Comment by jonahgreenthal** [comment]
Yes, that fixes it; thanks. Will it be in the next version?

**Comment by fenisteel** [comment]
The same in PHP:

![npp_bug](https://user-images.githubusercontent.com/8095121/58566145-56559080-8230-11e9-8462-83436cb450b6.png)

If I replace the DLL, Notepad++ won's start: 

![npp_error](https://user-images.githubusercontent.com/8095121/58566220-7dac5d80-8230-11e9-9025-4f66eee23f3d.png)

I'm using the 32bit version.

**Comment by MetaChuh** [comment]
@fenisteel 
this is a 64 bit SciLexer.dll build, for the author of this issue, matching his debug information.
best regards

**Comment by donho** [comment]
Forget about the Scilexer.dll I've provided.
@dail8859 has done a much better fix for it:
https://github.com/notepad-plus-plus/notepad-plus-plus/pull/5708
The fix will be in the next version.

**Comment by jonahgreenthal** [comment]
Cool, thanks! Did you check that the fix works for JSP in addition to ASP?

**Comment by dail8859** [comment]
@jonahgreenthal 

Yes JSP is fixed as well.
