### ISSUE TITLE
。。。。。。

### ISSUE THREAD

**Issue by woooO0ngqi-v** [notepad-plus-plus/notepad-plus-plus#5678]
I support the LGBT，but taiwan is not a country，taiwan is part of China.
![image](https://user-images.githubusercontent.com/30854389/58146412-980e9600-7c88-11e9-9c67-7b2cecbe2c9c.png)

**Comment by woooO0ngqi-v** [comment]
I'm a user of Notepad++,it's a really perfect  software.But someone's political tendency is really ridiculous!

**Comment by MetaChuh** [comment]
@woooO0ngqi-v 

for general questions, which are not directly related to the notepad++ source code,
please visit us at the notepad++ community forum.
you are welcome to create a new topic at General Discussion, or Boycott Notepad++.
(no extra account is needed, just use your github account to sign in)

many thanks and best regards.

[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)

**Comment by sasumner** [comment]
Maybe I am behind the times, although I do understand the rainbow colors, I don't understand what that 3rd thing is.  I see a rainbow chameleon, a red heart, and then a rainbow WHAT-IS-THAT??

**Comment by DavidHansen-0x454d43** [comment]
@sasumner that's the island of Taiwan. 
I read it as: "N++ loves Taiwan, R.O.C."

**Comment by sasumner** [comment]
@DavidHansen-0x454d43 Right you are.  I totally see it now.  I think all the colors on it actually hurt my recognition. :P

**Comment by donho** [comment]
@sasumner FYI:
https://www.washingtonpost.com/opinions/2019/05/20/taiwans-same-sex-marriage-law-could-change-debate-asia-forever/?noredirect=on&utm_term=.2df67a837bbe

**Comment by donho** [comment]
@woooO0ngqi-v 
> taiwan is not a country，taiwan is part of China.

I don't think so. We have our own government.
I have never considered myself Chinese, so why do you bother?

**Comment by woooO0ngqi-v** [comment]
@donho You have your right to think so.I have the right to say "taiwan is not a country,taiwan is part of China".

**Comment by sasumner** [comment]
@donho I'm totally up to speed on current events...just apparently the shape of Taiwan is nothing I see on a daily basis.  :)

**Comment by iridiumcao** [comment]
Taiwan became a country when PRC founded in 1949 in Beijing.
PRC wants Taiwan to be a province of its country, but that is just an image not the fact. PRC's propaganda tell his people lies, but they have to believe it. 
China PRC never governed Taiwan, nor Taiwan did. They are both countries.

**Comment by lulz6** [comment]
Well,

According to the Chinese government, any electronic communication leaving or entering China must pass through a "an electronic border". 

This border is made of Lying DNS Resolver, transparent proxies capable of SNI filtering and routers capable of forging TCP replies.

**Given that internet traffic going from China to Taiwan has to go through this electronic border, Taiwan is technically a foreign country.** Case closed.

(For those who ask : This border is only a small part of  "The great firewall of china". The main part is made of routers/IPS capable of QoS based on traffic behavior)

**Comment by donho** [comment]
@lulz6 The border of the Great Fire Wall is a good argument !
It'll be perfect if the word "technically" is replaced by "in reality" :)

**Comment by PauloFrancaLacerda** [comment]
É muita boiolagem pra pouca sacanagem!  :D

**Comment by github-young** [comment]
> @woooO0ngqi-v
> 
> > taiwan is not a country，taiwan is part of China.
> 
> I don't think so. We have our own government.
> I have never considered myself Chinese, so why do you bother?

Yes. We do not need your agreement or you. We just need that island.

**Comment by sasumner** [comment]
>We just need that island.

LOL. +10. :)

**Comment by donho** [comment]
@github-young 
> Yes. We do not need your agreement or you. We just need that island.

For what? To replay [64 event](https://en.wikipedia.org/wiki/1989_Tiananmen_Square_protests) ?

**Comment by github-young** [comment]
> For what? To procast your [64 event](https://en.wikipedia.org/wiki/1989_Tiananmen_Square_protests) in Taiwan?
No. (Well, it is OK for tw people)
For the island itself. The natrual resources, strategic value, ocean areas etc.

**Comment by MetaChuh** [comment]
i hope that one day, we will all just make a big global group hug, with mutual respect and understanding for each other, appreciating what we have, without longing for things we don't. 😉
peace ✌️
