### ISSUE TITLE
Notepad++ UI intermittently freezes when saving new file.

### ISSUE THREAD

**Issue by pressacco** [notepad-plus-plus/notepad-plus-plus#5679]
As a software developer, I have been using _Notepad++_ on a daily basis for years.  Unfortunately I have noticed an intermittent bug whereby the application would become unresponsive. Roughly speaking, I have seen this bug...
- over the past ~2ish years
- every 3 - 4 months

### Steps to Reproduce the Issue
1. Using the _Windows Explorer_ create a new **local** text file (e.g. `NewFile.txt`).
2. Double-click the text file to open it in _NotePad++_
   - _NotePad++_ is my default text editor for _Windows 10_.
3. Add text to the file.
4. Save the file (using the `Ctrl+S` shortcut)

### Expected Behavior
- The text file should save & I should be able to continue working.

### Actual Behavior
- The _NotePad++_ user interface becomes unresponsive
   - the application's title bar says: "Not Responding"
   - if you click on the _NotePad++_ window... the window will become slightly opaque
- To continue working I have to terminate the application using the _Windows Task Manager_
  - Termining _NotePad++_ does **not** resolve the problem.

### Additional Context

- When this problem occurs, it is reproducible
   1. Double-click text file (e.g. `NewFile.txt`), _NotePad++_ opens, edit text file, save, _Notepad++_ **freezes**.
   2. Terminate the application using _Windows Task Manager_
   3. Double-click `NewFile.txt`, _NotePad++_ opens, edit text file, save, _Notepad++_ **freezes**.
   4. Terminate the application using _Windows Task Manager_
   5. repeat
- When this problem occurs, I can open another text file (e.g. `FileFromYesterday.txt`) and edit it without issue.
   1. Double-click `FileFromYesterday.txt`, _NotePad++_ opens, edit text file, **save works**.
   2. Double-click `NewFile.txt`, _NotePad++_ opens, edit text file, save, _Notepad++_ **freezes**.
- I recently discovered that if I edit the file using _Windows Notepad_... the problem goes away.
  1. Open `NewFile.txt`, using _Windows Notepad_, edit text file, _file saves_ without issue.
  2. Close _Windows Notepad_.
  3. Open `NewFile.txt`, using _Notepad++_, edit text file, _file saves_ without issue!
- In the past, I would resolve the issue by:
  1. uninstalling _Notepad++
  2. reboot computer
  3. install _Notepad++
     - no idea if it was the same version, or a new version of _Notepad++_
  4. Open `NewFile.txt`, using _NotePad++, edit text file, _file saves_ without issue.

### System Information
- Notepad++ v7.6.6 64-bit 
   - I have not installed _any_ plugins.
- Windows 10 Pro (version: 1803)
- Intel i7-4790 3.6GHz
- 16 GB RAM (10GB free when incident occurred)

### Debug Information
Notepad++ v7.6.6   (64-bit)
Build time : Apr  3 2019 - 23:52:32
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10 (64-bit)
Plugins : mimeTools.dll NppConverter.dll 

### Related Bugs

This may be related to:
1. [Notepad++ Freezing](https://github.com/notepad-plus-plus/notepad-plus-plus/issues/973)
   - I have not tried the proposed solution: "Eventually I found a folder `%LOCALAPPDATA%/Temp/N++RECOV`. When I emptied the contents of this folder, things started working again."

**Comment by MetaChuh** [comment]
@pressacco 

many thanks for your complete and detailed issue report.
unfortunately i can not reproduce this issue on 7.6.6 and 7.7.

please test the following, to verify, if a clean notepad++ would work on your system.

* download the notepad++ 7.7 64 bit portable version from [>>> here <<<](https://notepad-plus-plus.org/repository/7.x/7.7/npp.7.7.bin.x64.zip).
(the portable version does not require any installation and runs completely independent and isolated from your installed version. all custom settings, as well as any stuff you might want to try at the portable version, will not modify your installed version)

* extract `npp.7.7.bin.x64.zip` to your desktop.
(copy `npp.7.7.bin.x64.zip` from your download folder to your desktop, right-click on it, select `extract all` from the explorer context menu, and press `extract` to extract it to a folder called `npp.7.7.bin.x64`)

* **important note:** make sure to close all instances of notepad++ that might be running, before starting the portable version at the next step, to be sure you are using the portable version for this test.

* open the extracted `npp.7.7.bin.x64` folder and start this portable version by double-clicking on `notepad++.exe` inside this folder.
(note: notepad++.exe will just be seen as notepad++, if you have enabled to hide all known file extensions at your explorer settings)

* retry to reproduce this, and eventually repeat with older portable versions (zip releases) of notepad++, to see if any specific version works better or worse.

you might also want to visit our notepad++ community (link at the bottom) to ask our users, if anyone else has experienced the same, and eventually knows what the culprit could be.

many thanks and best regards.

-----
```
general notes:

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
(no extra account is needed, just use your github account to sign in)
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)
