### ISSUE TITLE
Minimize to system tray is broken

### ISSUE THREAD

**Issue by smaragdus** [notepad-plus-plus/notepad-plus-plus#5682]
I updated [Notepad++](https://notepad-plus-plus.org/) from a very old version to the latest version (**7.7**) and noticed that the option `Minimize to system tray` (**Preferences - Settings - MISC. - Minimize to system tray**) does not work. I checked old versions and it turned out that `Minimize to system tray` is broken since version **6.8.4**- the last version in which `Minimize to system tray` works fine is **6.8.3**. I checked the configuration file (**config.xml**) and no matter that `Minimize to system tray` is on:

`<GUIConfig name="TrayIcon">yes</GUIConfig>`

**Notepad++** does not minimize to system tray but to task bar. I am surprised that no one has reported this issue.

**Comment by SinghRajenM** [comment]
Not able to reproduce.. With latest v7.7.

**Comment by smaragdus** [comment]
@SinghRajenM 

I experienced the problem under Windows 8 x64 using portable version (**npp.7.7.bin.x64.7z**). I wonder- could this be system issue?

**Comment by MetaChuh** [comment]
@smaragdus 

we can not reproduce minimize to system tray not working (see screencast below)
tested on windows 10 x64 and windows 7 x64, using npp.7.7.bin.x64.

![7 7 minimise to tray](https://user-images.githubusercontent.com/45773305/58233780-407e3200-7d3d-11e9-85f7-63df4232c998.gif)

<kbd>Notepad++ v7.7   (64-bit)
Build time : May 19 2019 - 13:05:35
Path : C:\Users\User\Desktop\npp.7.7.bin.x64\notepad++.exe
Admin mode : OFF
Local Conf mode : ON
OS : Windows 10 (64-bit)
Plugins : mimeTools.dll NppConverter.dll PythonScript.dll</kbd>

unfortunately we don't have a windows 8 system to test on, but if one of the windows 8 updates, or any additionally installed software causes this, you could try to ask at our notepad++ community (link at the bottom), if someone else has experienced this on windows 8 and can be of help.

many thanks and best regards.

-----
```
general notes:

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).
please file an issue as easy to understand and reproducible as possible.

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
(no extra account is needed, just use your github account to sign in)
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)
