### ISSUE TITLE
SCI_POSITIONAFTER returns the wrong offset in Notepad++ 7.7 X64 when fetching the position after offset -1

### ISSUE THREAD

**Issue by leonardder** [notepad-plus-plus/notepad-plus-plus#5683]
### Description of the Issue
In the [NVDA screen reader](https://www.nvaccess.org/) we're sending the SCI_POSITIONAFTER window message in order to calculate the offsets for a single character. Up to now, in some cases such as at the start of the document, we could try to fetch the position after a negative offset, e.g. -1.
This properly returned 0 in the case of Notepad+= 7.6.x X86 and X64. It also does this on Notepad++ 7.7 X86. On the X64 build however, it returns the length of the document instead.

### Steps to Reproduce the Issue
1. From a python interpreter, execute the following:

```
import ctypes
hwnd = xxxx # Set this to the window handle of the scintilla control inside the Notepad++
ctypes.windll.user32.SendMessageW(hwnd, 2418, -1, None)
```

### Expected Behavior
The returned result is 0

### Actual Behavior
In the X64 version of NP++, the returned result is the last offset of the document.

### Additional details
* NVDA Issue: https://github.com/nvaccess/nvda/issues/9609
* NVDA pull request: https://github.com/nvaccess/nvda/pull/9612

**Comment by donho** [comment]
@leonardder 
In v7.7, Scintilla is upgraded from v3.56 to v4.14. 
However, I just checked the Scintilla document, I didn't see that we can use -1 as position:
https://www.scintilla.org/ScintillaDoc.html#SCI_POSITIONAFTER
In any way, it's rather an issue in Scintilla than in Notepad++. 
I suggest you create an issue in Scintilla project.

**Comment by leonardder** [comment]
Thanks for pointing me at that documentation.

It actually contains the following information:

> The INVALID_POSITION constant (-1) represents an invalid position within the document.

So, our use of -1 can be considered invalid.
