### ISSUE TITLE
What is block selection supposed to be doing in wrapped lines?

### ISSUE THREAD

**Issue by bersbersbers** [notepad-plus-plus/notepad-plus-plus#5684]
### Description of the Issue
Block selection, when started in the second line of a wrapped line, seems to always consider the first line only.

### Steps to Reproduce the Issue
1. Open empty file
2. Enter `Y Y Y Y Y Y Y Y Y Y Y Y Y Y Y Y Y Y Y Y Y Y Y Y Y Y Y Y Y Y Y Y Y Y Y Y Y Y Y Y Y Y Y Y Y Y Y Y Y Y Y Y Y Y Y Y Y Y Y Y Y Y Y Y Y Y Y Y Y Y Y Y Y Y Y Y Y Y Y Y Y Y Y Y Y Y Y Y Y Y Y Y Y Y Y Y Y Y Y Y Y Y Y Y Y Y Y Y Y Y Y Y Y Y Y Y Y Y Y Y Y Y Y Y Y Y Y Y Y Y Y Y Y Z`
3. Make sure line wrapping is on and the line is long enough to be wrapped.
4. Place cursor at end of line (after `Z`).
5. Press Alt-Shift-Left to start a block selection.

### Expected Behavior
`Z` is selected.

### Actual Behavior
Some other `Y` is selected.

### Variant
If you have a long first line before the YZ line, also try this:
4. Place cursor at end of YZ line.
5. Press Alt-Shift-Left to start a block selection.
6. Press Alt-Shift-Up to extend the block selection to the first line.

Note that you actually have to press Alt-Shift-Up *twice*, this is certainly unexpected.

### Debug Information
```
Notepad++ v7.7   (64-bit)
Build time : May 19 2019 - 13:05:35
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10 (64-bit)
Plugins : DSpellCheck.dll mimeTools.dll NppConverter.dll 
```

**Comment by MetaChuh** [comment]
@bersbersbers 

this seems to be the same behaviour with scite 4.1.4, which uses the same scintilla engine as notepad++ 7.7, as well as with scintilla 4.1.5.

unfortunately the scintilla editor component is an external project, so we can't do much about it at the notepad++ part.
if you can't work out any workaround with the help of [our notepad++ community](https://notepad-plus-plus.org/community/), please file an issue at the [scintilla project](https://sourceforge.net/p/scintilla/bugs/).

many thanks for your understanding, our apologies, and best regards.

**Comment by bersbersbers** [comment]
Thanks - I reported https://sourceforge.net/p/scintilla/bugs/2105/
