### ISSUE TITLE
Duplicate Current Line shortcut suddenly stopped working

### ISSUE THREAD

**Issue by brennanyoung** [notepad-plus-plus/notepad-plus-plus#5692]
### Description of the Issue
Ctrl+D no longer invokes Duplicate current line. This seems to have happened very, very recently.

### Steps to Reproduce the Issue
Open a document. Type "Lorem Ipsum" Press Ctrl+D

### Expected Behavior
Lorem Ipsum should be duplicated - exactly as if "Duplicate Current Line" were selected from Edit->Line Operations.

### Actual Behavior
Nothing

### Debug Information
Notepad++ v7.6.6   (32-bit)
Build time : Apr  3 2019 - 23:49:50
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 8.1 (64-bit)
Plugins : Linter.dll mimeTools.dll NppConverter.dll NppExport.dll NppMarkdownPanel.dll NppTextFX.dll Tidy2.dll XMLTools.dll 

"Duplicate Current Line" is missing entirely from "Main Menu" under Shortcut Mapper, but SCI_SELECTIONDUPLICATE is present, under "Scintilla commands", mapped to Ctrl+D, and is **not** marked as a conflicting shortcut.

Edit->Line Operations->Duplicate Current Line works as expected. It's only this one shortcut that is failing. I have not observed any problems with other shortcuts from the same sub menu (such as Ctrl-J for "Join Lines") which work just fine.

Regarding the plugins mentioned in Debug Information, I first observed this issue after most of my installed plugins (and plugin manager) disappeared. I have since added a few plugins, but the issue was there with the default installed (mininum) set.

**Comment by sasumner** [comment]
It works okay for me with the ctrl+d shortcut in 7.6.6 (32) and 7.7 (32).  I see the same mappings as you in Shortcut Mapper.  Maybe make one more test without the plugins again?

**Comment by Ekopalypse** [comment]
I would bet that one of the plugins silently stolen the shortcut.

**Comment by brennanyoung** [comment]
Ok, removed all plugins with Plugins Admin, and running without any plugins at all still have the problem. Could it be a hangover from the old plugin manager?

**Comment by brennanyoung** [comment]
BTW I also tried renaming (i.e. "deleting") the %APPDATA% Notepad++ folder (A new default one gets created). The problem remains.

**Comment by brennanyoung** [comment]
Uninstalled the x86 version. Installed the 64bit version without keeping previous config. Fresh install. 
Ctrl-D still does nothing.

**Comment by brennanyoung** [comment]
OK, I've now remapped the shortcut to something else and it works fine. Something is stealing my Ctrl-D, but I'm now assuming it's not Notepad++ thanks for your help everyone!

**Comment by brennanyoung** [comment]
Final follow up to this. I found the culprit. Screenshot utility "tiny take" uses Ctrl-D for "Stop Recording" Be careful out there, friends.
