### ISSUE TITLE
save the file and rename with （:;<>'"）as （0:.txt），but it will not remind "invalid file name"！

### ISSUE THREAD

**Issue by aslen168** [notepad-plus-plus/notepad-plus-plus#5695]
### Steps to Reproduce the Issue

1. creat new file
2. save the file and rename with （:;<>'"）as （0:.txt），but it will not remind "invalid file name"！
3. the file successfully saved，but the File only zero bytes！

**Comment by MetaChuh** [comment]
@aslen168 

please go to `settings > preferences > default directory` and activate `use new style dialog` as seen at the screenshot below.

![Imgur](https://i.imgur.com/fibS0kv.png)

best regards.

-----
```
general notes:

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).
please file an issue as easy to understand and reproducible as possible.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
(no extra account is needed, just use your github account to sign in)
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)

**Comment by aslen168** [comment]
Although there will be prompts, you cannot save the txt file by default.

**Comment by MetaChuh** [comment]
as notepad++ is an editor for code, it is required by design, that users have full control over the file extensions.
when you use the new style dialog, you have to specify the extension manually, like `.txt`.

best regards.

**Comment by aslen168** [comment]
This is a bug.
Rename with English punctuation（:;<>'"）as （0:.txt），but it will not remind "invalid file name"！
I tested all versions and found that this problem occurred after **npp.7.5.4.Installer.x64**!
You can follow my steps to test.
