### ISSUE TITLE
Hotkey for "Replace in Files" does not work

### ISSUE THREAD

**Issue by hailongnk** [notepad-plus-plus/notepad-plus-plus#57]
In the window "Find in Files", the hot key Alt+R for button "Replace in Files" does not work

**Comment by cmeriaux** [comment]
Hello,
Sorry it's working on my config. I have the latest official verions 6.7.7.
Try to remove your plugin.

**Comment by hailongnk** [comment]
I tried the same version as yours in both Win 8.1, and Win 7. I also do the fresh install with default plugin but it does not work.
I have a workaround for this, first I open the *Find in FIles* window, then I have to focus to *Transparency* by pressing Alt+Y, then Alt+R to *Replace*
