### ISSUE TITLE
[Feature Request] Find in Files: Pinned Directories or Directory History

### ISSUE THREAD

**Issue by Amoo0001** [notepad-plus-plus/notepad-plus-plus#5700]
It would be nice to have a way to remember long paths to directories in the Find in Files feature.

I currently have two long paths that I frequently search in: one is my project directory and the other is a source code repo for a library I am using in my project.  Both paths are deeply nested and not related to one another, and it is very tedious to switch between them.  It would be very helpful to have one or both of the following:

- A list of recently searched directories in the Find in Files dialog.
- A customizable list of "pinned" or "favorited" directories in the Find in Files dialog.

Clicking one of the listed directories would fill the "Directory" field of the dialog with the path to that directory.

**Comment by sasumner** [comment]
@Amoo0001 A quick way to switch between to directories might be to keep them both open in the "Folder As Workspace" panel.  Then a right-click on either and a choice of "find in files" will correctly populate the directory search box.  May be quicker than trying to find what you need in the dropdown history, plus if the paths are really long, the dropdown history might not show you the rightmost part of it?

**Comment by Amoo0001** [comment]
@sasumner Thank you so much, that is very helpful!
