### ISSUE TITLE
Style configuration not working properly - Notepad++ 7.7

### ISSUE THREAD

**Issue by macmessa** [notepad-plus-plus/notepad-plus-plus#5702]
### Style configuration not working for ASP files

I've just updated to **7.7** version and some custom styles that I defined to ASP/VBScript language aren't working anymore. I reverted to **7.6.6** and everything works just fine.

### Reproducing the Issue
Using the version **7.7**, set your custom style to **ASP** extension:
![image](https://user-images.githubusercontent.com/13797580/58422671-8acb2000-8069-11e9-8cc8-4f891950b229.png)

### Expected Behavior
It should use your defined styles.

### Actual Behavior
It just ignores everything I have set in styles.

### Debug Information
Notepad++ v7.7   (32-bit)
Build time : May 19 2019 - 13:08:20
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10 (64-bit)
Plugins : DSpellCheck.dll LuaScript.dll mimeTools.dll NppConverter.dll NppExport.dll

**Comment by dail8859** [comment]
The new version of Notepad++ updated Scintilla and it looks like it changed the way it handles ASP and some other embedded languages within HTML.

Since you have LuaScript installed, try this temporary fix to verify the problem. Open your ASP file, then in the LuaScript console execute:

```lua
editor.Property['asp.default.language'] = 2
editor:Colourise(0, -1)
```

Related to #5677

**Comment by macmessa** [comment]
Hi @dail8859 , first of all thanks for the answer.
The fix you suggested worked when I execute in the ASP file using Lua console, but I've tried to add to the Startup Script and it didn't work.

**Comment by dail8859** [comment]
You would have to add that to the `"OnSwitchFile"` callback and check to see if the file is ASP, then run that code.

Untested example:

```lua
npp.AddEventHandler("OnSwitchFile", function(filename, bufferid)
    if npp.BufferLangType[bufferid] == L_ASP then
        editor.Property['asp.default.language'] = 2
        editor:Colourise(0, -1)
    end
    return false
end)
```

**Comment by macmessa** [comment]
Thanks, it worked. Sorry for the delay to anwser.
