### ISSUE TITLE
Compare Plugin scrolling not locked

### ISSUE THREAD

**Issue by Ravenheart** [notepad-plus-plus/notepad-plus-plus#5703]
### Description of the Issue
When comparing two files in the old version the two compared halves used to scroll in sync, with the new version they no longer scroll together.

### Steps to Reproduce the Issue
1.  Load two long (more than one screen height) files
2. Plugins -> Compare -> Compare
3. Scroll down

### Expected Behavior
The two compared halves scroll in sync.

### Actual Behavior
The two compared halves scroll independent of each other.

### Debug Information
Notepad++ v7.7   (64-bit)
Build time : May 19 2019 - 13:05:35
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10 (64-bit)
Plugins : ComparePlugin.dll mimeTools.dll NppConverter.dll NPPJSONViewer.dll XMLTools.dll 

![scroll](https://user-images.githubusercontent.com/853378/58465286-07c8c900-8140-11e9-8e22-414234eed6ad.png)

**Comment by MetaChuh** [comment]
this is a known issue of the compare plugin on 64 bit notepad++ 7.7 releases.

please visit the compare plugin issue tracker:
https://github.com/pnedev/compare-plugin/issues/201
