### ISSUE TITLE
Shortcuts stopped working after upgrade

### ISSUE THREAD

**Issue by stAn47** [notepad-plus-plus/notepad-plus-plus#5704]
after the last update of notepad++ 32bit version, configured short cuts stopped working, example: 

left ctrl+ left shift + o 

gives a SI character instead of opening a window to search for opened files. 

any ideas how to fix this ? 

i do not need those special characters completely (coming from ctrl shirt ) - is there any way how to completely suppress them in notepad plus plus?

than you, best regards, stan

**Comment by stAn47** [comment]
system info: 
Windows 10 x64 + slovak language + keyboard English USA
Notepad++ 7.7 (32bit version - on 64bit version i just couldn't make this work on any version of notepad plus plus)
Installed plugins: 
```
27. 05. 2019  13:10    <DIR>          .
27. 05. 2019  13:10    <DIR>          ..
27. 05. 2019  13:10    <DIR>          APIs
26. 11. 2018  16:45    <DIR>          ComparePlugin
26. 11. 2018  16:27           213 504 ComparePlugin.dll
27. 05. 2019  13:10    <DIR>          Config
10. 09. 2018  12:21    <DIR>          disabled
26. 11. 2018  16:45    <DIR>          doc
26. 11. 2018  16:45    <DIR>          DSpellCheck
27. 12. 2018  13:17         2 211 840 DSpellCheck.dll
19. 11. 2013  16:19           110 592 FileSwitcher.dll
12. 01. 2017  18:28           271 360 JSMinNPP.dll
27. 05. 2019  13:10    <DIR>          mimeTools
27. 05. 2019  13:10    <DIR>          NppConverter
27. 05. 2019  13:10    <DIR>          NppExport
27. 12. 2018  13:18         2 728 960 NppFTP.dll
10. 06. 2013  18:11           229 376 NppTextFX.dll
11. 10. 2018  10:25           497 152 PluginManager.dll
18. 07. 2011  23:07            81 920 SpellChecker.dll
27. 12. 2018  13:18         2 131 968 XMLTools.dll
               9 File(s)      8 476 672 bytes
              11 Dir(s)  129 676 242 944 bytes free
```

**Comment by stAn47** [comment]
code page: Windows-1250 (slovak)

**Comment by MetaChuh** [comment]
@stAn47 

i can correctly map <kbd>ctrl</kbd> + <kbd>shift</kbd> + <kbd>o</kbd> without any problems on windows 10 english, spanish and german.
also if it is not mapped, it does not create any characters at the editor field.
maybe it might be another software or keyboard helper tools that might cause this.

**please test the following, to verify, if a clean notepad++ (without any plugins that could cause this) would work on your system.**

* download the notepad++ 7.7 portable version from [>>> here <<<](https://notepad-plus-plus.org/repository/7.x/7.7/npp.7.7.bin.zip).
(the portable version does not require any installation and runs completely independent and isolated from your installed version. all custom settings, as well as any stuff you might want to try at the portable version, will not modify your installed version)

* extract `npp.7.7.bin.zip` to your desktop.

* **important note:** make sure to close all instances of notepad++ that might be running, before starting the portable version at the next step, to make sure you are using this portable version.

* open the extracted `npp.7.7.bin` folder and start this portable version by double-clicking on `notepad++.exe` inside this folder.
(note: notepad++.exe will just be seen as notepad++, if you have enabled to hide all known file extensions at your explorer settings)

* try to type <kbd>ctrl</kbd> + <kbd>shift</kbd> + <kbd>o</kbd> without mapping it as a shortcut, then try to map it do anything you like.

**Comment by rddim** [comment]
Tested on VM because another soft stole `ctrl+shift+o`. Nothing mapped

![npp_ctrl_shft_o](https://user-images.githubusercontent.com/8998791/58510236-fb288d00-81a0-11e9-8c37-ce05afed6ecb.gif)

### Debug Info
Notepad++ v7.7   (32-bit)
Build time : May 19 2019 - 13:08:20
Path : C:\Users\User\Desktop\npp.7.7.bin\notepad++.exe
Admin mode : OFF
Local Conf mode : ON
OS : Windows 7 (64-bit)
Plugins : mimeTools.dll NppConverter.dll NppExport.dll

**Comment by stAn47** [comment]
hello, thank you for the guide, 

my problem with "ctrl shift o" (file switcher) seems to be resolved:
- after upgrading to the latest notepad++ 7.7
- it seems i need to download/install File Switcher plugin from the plugin manager
- to be able to use "ctrl shift o" 

is it possible that this plugin was a default plugin on some previous notepad versions ? and after an upgrade it needs to be reinstalled or installed generally?

thank you again, 
notepad++ is the best, 
best regards, stan

**Comment by MetaChuh** [comment]
@stAn47 

splendid, thanks for reporting this back.
yes, on the new versions you have to reinstall your plugins, due to a folder structure change.

**important note**: please use the new, built in menu `plugins > plugins admin` to install the file switcher plugin.
(the old plugin manager does not work on newer versions of notepad++)

many thanks and best regards.
