### ISSUE TITLE
n++ 7.7 : file change are no more automatically detected 

### ISSUE THREAD

**Issue by SuperUserNameMan** [notepad-plus-plus/notepad-plus-plus#5705]
about  n++ 7.7, 32bits, windows 8.1

some version before 7.7, when several files were displayed in the editor, and when the content of one of this file was changed on disk, the user was **immediately** warned and prompted about reloading or keeping.

in 7.7, user is warned and prompted only when the tab of the modified file is active.

**Comment by MetaChuh** [comment]
@SuperUserNameMan 

yes, you are correct.
this is a new preference feature of newer notepad++ versions, where user can choose to have an update notification for the active file tab only, or for all files.

please go to the notepad++ menu `settings > preferences > misc` and set the `file status auto-detection` from `enable` to `enable for all files`.

many thanks and best regards.

-----
```
general notes:

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
(no extra account is needed, just use your github account to sign in)
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)
