### ISSUE TITLE
Accessibility problem with NVDA

### ISSUE THREAD

**Issue by shadow2560** [notepad-plus-plus/notepad-plus-plus#5707]
### Description of the Issue
On version 7.7, the screen reader make an long load when we can't do anything each time the Windows is focused, the bug is not present in 7.6.6.

### Steps to Reproduce the Issue
1. Install the last version of NVDA and the version 7.6.6 of Notepad++.
2. Open a simple file (a batch file for example) and try to move in the document with the arrows, the screen reader will work normaly.
3. Update to version 7.7 of Notepad++ and try the step 2, the screen reader will be very slow during a long loading.

### Expected Behavior
The System mustn't lag at this point eatch time the document is focused with the screen reader.

### Actual Behavior
The system lag whe focusing the Windows with the screen reader.

### System infos:
Windows 7 X64with the lasts updates, notepad++ X64 7.6.6 for functional version and 7.7 for bugged version (bug not tested with the X86 version), visualc++ and .net framework fully instaled with the lasts versions, last version of NVDA.

**Comment by MetaChuh** [comment]
@shadow2560 

i can not reproduce a speed difference on notepad++ 7.7 x86 and x64, using the latest nvda 2019.1.1.
you might want to visit our notepad++ community (link at the bottom), maybe another nvda user knows what could trigger this on your system.

many thanks and best regards.

-----
```
general notes:

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
(no extra account is needed, just use your github account to sign in)
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)
