### ISSUE TITLE
Wrong display of Chinese character with font of "Courier New"

### ISSUE THREAD

**Issue by BlownSnail** [notepad-plus-plus/notepad-plus-plus#5709]
### Description of the Issue
The Chinese character with "Courier New" are not at same size and weight

### Steps to Reproduce the Issue
1. Open Notepad++ and create blank file
2. Type or paste "啊发额去"

### Expected Behavior
The four character should be at same size and weight

### Actual Behavior
"啊去" is more bigger and bold
![image](https://user-images.githubusercontent.com/47628315/58563431-adbe2580-825d-11e9-9b71-e67197157f97.png)

### Debug Information
Notepad++ v7.7   (32-bit)
Build time : May 19 2019 - 13:08:20
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : ON
Local Conf mode : OFF
OS : Windows 7 (64-bit)
Plugins : ComparePlugin.dll DSpellCheck.dll mimeTools.dll NppConverter.dll NppExport.dll NPPJSONViewer.dll NppTextFX.dll 

It was normal before, but I cannot figure out when this issue occur.
以前是正常的，不知道什么时候开始这样的
Some of computers reproduce this issue, others not.
有的电脑也可以复现这个问题，有的正常
I have delete the user data in %APPDATA%/Notepad++ and reinstall the 32bit notepad++ of 7.3.3, 7.5.9, 7.7, problem remain.
删掉用户的配置，再重装三个32bit版本，问题依旧
I have clear the font cache in C:\Windows\ServiceProfiles\LocalService\AppData\Local, problem remain.
清空字库缓存，问题依旧
I have copy the "Courier New" from normal computer to my computer and restart, problem remain. (font version 5.11)
从正常的电脑复制字体过来并重启，问题依旧

**Comment by MetaChuh** [comment]
@BlownSnail 

this seem to happen on all updated windows 10 and 7.
it is system wide and the same, if you type it into windows notepad.exe, and enlarge the font to the same size, as seen at the screenshot below.

<img width="887" alt="" src="https://user-images.githubusercontent.com/45773305/58588072-1ce84980-825f-11e9-881b-f3ff756f7364.png">

this is something we will not be able to fix at notepad++.
 
many thanks for your understanding and best regards.
