### ISSUE TITLE
Look of Ctrl+Tab window

### ISSUE THREAD

**Issue by h-h-h-h** [notepad-plus-plus/notepad-plus-plus#571]
Hello,

the captionless window that appears when you navigate with <kbd>Ctrl</kbd>+<kbd>Tab</kbd> has a resize border. When you resize it, it looks like it's not supposed to look. Besides it's not very pretty with it's background color, no line-wise vertical centering, missing top margin and the lines going wide to a large extent and being cut off. A line break and/or ellipsis would help. The background color could be as in the <kbd>Alt</kbd>+<kbd>Tab</kbd> window, or the default control or window background could be used.

Seen on Windows 8.1 with scaling of 200 % and increased font size.

With regard to scaling and the increase of the font size, the window has a too small font!

See yourself:
![ctrl tab dialog](https://cloud.githubusercontent.com/assets/13482553/9647846/ab8fcefe-51e1-11e5-8d6b-2378c40c32d5.png)

Related issue: https://github.com/notepad-plus-plus/notepad-plus-plus/issues/859

**Comment by donho** [comment]
I believe this issue has been fixed since long time ago.
Update your Notepad++ to the latest version (v7.6.6).
If the issue persists, please create a new issue for it.
Thank you.
