### ISSUE TITLE
https://notepad-plus-plus.org/repository/7.x/7.7/npp.7.7.Installer.exe is offline

### ISSUE THREAD

**Issue by Xorima** [notepad-plus-plus/notepad-plus-plus#5710]
Hi,

https://notepad-plus-plus.org/repository/7.x/7.7/npp.7.7.Installer.exe is returning a 503 error.

**Comment by mwpowellhtx** [comment]
I second the motion. I was just there and can confirm the same.

```
Error 503 Backend fetch failed
Backend fetch failed
Guru Meditation:
XID: 189534075
Varnish cache server
```

**Comment by marcabrus** [comment]
same for me

**Comment by MetaChuh** [comment]
same for everyone.

while the web server seems to be up and ok, there seems some problem with the repository folder structure.
(temp seems ok, except missing icons)

@milipili or @donho
do you know what could have caused this ?

**Comment by XclusivVv** [comment]
I picked the worst day for a re-install I suppose. For anybody else needed a mirror download in the meantime:
[https://www.softpedia.com/get/Office-tools/Text-editors/Notepad-plus-plus.shtml](url)

**Comment by mwpowellhtx** [comment]
I've got an archive of previous version installers. Ping me offline if you need one, I'll share it with you.

**Comment by majorb84** [comment]
Seems to be back up now!

**Comment by Xorima** [comment]
Re-opening as seems to have gone offline again @MetaChuh @milipili or @donho 
https://notepad-plus-plus.org/update/getDownloadUrl.php

**Comment by Xorima** [comment]
And working again

**Comment by MetaChuh** [comment]
@Xorima 

the web server seems magically attached to this issue.
if we close it, the backend will go offline again 😉

just kidding, let's hope it stays stable now.
greetings.
