### ISSUE TITLE
CylanceProtect reports StackPivot in notepad++.exe

### ISSUE THREAD

**Issue by spixi** [notepad-plus-plus/notepad-plus-plus#5711]
### Description of the Issue
CylancePROTECT reports StackPivot in notepad++.exe

### Steps to Reproduce the Issue
1. Start Notepad++

### Expected Behavior
Notepad++ runs as usual.

### Actual Behavior
The following message appears:
![1](https://user-images.githubusercontent.com/3192596/58574381-257d5780-8240-11e9-9a2e-d7f80212cb86.PNG)

Dialog boxes contain no text:
![2](https://user-images.githubusercontent.com/3192596/58574384-257d5780-8240-11e9-8401-d80fb991a9d0.PNG)

This issue is not always reproducible. I cannot find out, when it is exactly happening, but it seems to be a security issue.

### Debug Information
Notepad++ v6.7.8 on Windows 7

### Installed Plugins
Compare 1.5.6
DSpellCheck 1.2.14
NppFTP 0.26.3
Plugin Manager 1.3.5
Converter 3.0
MIME Tools 1.9
NppExport 0.2.8

**Comment by Ekopalypse** [comment]
@spixi - really, npp from Release Date: ### **2015**-05-16 ??

**Comment by MetaChuh** [comment]
@spixi

cylance should not detect a false positive on notepad++.exe 6.7.8.
see the [virustotal report](https://www.virustotal.com/#/file/14d35baaaf7d4750e4e85e669fbba1d2b56a0d868e47728dee85018cb39f37b5/detection).

please upload your own notepad++.exe to virustotal, to make sure it is not affected.
(note: you can ignore the jiangmin false positive on this old version)

it is also recommended to update your notepad++ to a newer, or the the latest version [<kbd>Notepad++ 7.7</kbd>](https://notepad-plus-plus.org/download/v7.7.html) (reinstall of your plugins is needed, if you update from version 6.7.8). 

many thanks and best regards.

-----
```
general notes:

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
(no extra account is needed, just use your github account to sign in)
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)
