### ISSUE TITLE
L10n: the last components options are not localized in Japanese installer

### ISSUE THREAD

**Issue by Phroneris** [notepad-plus-plus/notepad-plus-plus#5713]
(rewritten from #4728)

### Description of the Issue

I use the installer of Notepad++ in Japanese.
Its most words and sentences are localized very well (thanks!), but for a long while the last few options have been not.
![nppupdater](https://user-images.githubusercontent.com/9891867/58600295-02de5380-82bf-11e9-921f-12d48213c73a.png)

### Steps to Reproduce the Issue

1. Just run the installer and see its last page before install.

### Expected Behavior

The display is localized as well as the other pages.

### Actual Behavior

The display is English.

### Debug Information

Notepad++ v7.7   (64-bit)
Build time : May 19 2019 - 13:05:35
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 7 (64-bit)
Plugins : CustomLineNumbers.dll mimeTools.dll NppConverter.dll zoomdisabler_x64.dll

**Comment by donho** [comment]
These customized settings are not translatable.
