### ISSUE TITLE
Cannot download NotePad++

### ISSUE THREAD

**Issue by mic006** [notepad-plus-plus/notepad-plus-plus#5714]
I cannot download any release from the website (https://notepad-plus-plus.org/repository/7.x/7.7/npp.7.7.Installer.exe), I am still getting the 503 Error:

Error 503 Backend fetch failed
Backend fetch failed

Guru Meditation:
XID: 283479807

**Comment by andrecool-68** [comment]
There are problems with the server, it is temporary!

**Comment by milipili** [comment]
Sorry, our backend got screwedd. Situation is resolved :)
