### ISSUE TITLE
Encoding Ansi Problem

### ISSUE THREAD

**Issue by datakent** [notepad-plus-plus/notepad-plus-plus#5715]
### Description of the Issue
Windows 10 Pro English
Region format: Turkish
Language for non-Unicode programs: Turkish
Notepad++: v7.7

When I select "Ansi" from the encoding menu;

When I press the letter "ğ" on the keyboard, the letter "g" appears in notepad ++.

ı -> i
ğ -> g
ş -> s
Ğ -> G
Ş -> S
İ -> I

Note: Notepad ++ v7.5.9 does not have this problem. There are problems with the higher versions.

**Comment by zufuliu** [comment]
This is same bug as issue #5671

**Comment by donho** [comment]
@datakent 
Could you test the following binaries and confirm me the bug is fixed and without regression please?
32 bits:
https://notepad-plus-plus.org/temp/cyrillacPb/npp.7.7.bin.zip
64 bits:
https://notepad-plus-plus.org/temp/cyrillacPb/npp.7.7.bin.x64.zip

**Comment by datakent** [comment]
The character issue is fixed. Thanks for your interest.

**Comment by donho** [comment]
https://github.com/notepad-plus-plus/notepad-plus-plus/commit/cc2d246ae23bc85fdccb5797a03fc08e512bec48
