### ISSUE TITLE
MIME Quoted-printable Decode fails to decode pattern just encoded by the Encode plugin

### ISSUE THREAD

**Issue by ggodhner** [notepad-plus-plus/notepad-plus-plus#5717]
### Description of the Issue

The MIME Quoted-printable Decode fails to decode a pattern that was just encoded by the Encode 

### Steps to Reproduce the Issue

1. I have taken the following three URLs as an example, and encoded them:

https://www.automationdirect.com/adc/shopping/catalog/enclosures_-z-_subpanels_-z-_thermal_management_-z-_lighting/enclosures/junction_boxes/jic040403

https://www.automationdirect.com/adc/shopping/catalog/enclosures_-z-_subpanels_-z-_thermal_management_-z-_lighting/enclosures/junction_boxes/jic0403025

https://www.automationdirect.com/adc/shopping/catalog/enclosures_-z-_subpanels_-z-_thermal_management_-z-_lighting/enclosures/junction_boxes/jic040202

2.  When I encode them I get the following result:

https://www.automationdirect.com/adc/shopping/catalog/enclosures_-z-_subpa=
nels_-z-_thermal_management_-z-_lighting/enclosures/junction_boxes/jic04040=
3

https://www.automationdirect.com/adc/shopping/catalog/enclosures_-z-_subpa=
nels_-z-_thermal_management_-z-_lighting/enclosures/junction_boxes/jic04030=
25

https://www.automationdirect.com/adc/shopping/catalog/enclosures_-z-_subpa=
nels_-z-_thermal_management_-z-_lighting/enclosures/junction_boxes/jic04020=
2

### Expected Behavior

When I select this text again and run the MIME Quoted-printable Decode routine I expect to get the original URLs replacing the encoded text.

### Actual Behavior

Instead I get a popup message with the title "Quoted-printable decode error" and the text "It's not a valid Quoted-printable text" and an "OK" button to dismiss the popup message.

### Debug Information

Notepad++ v7.7   (32-bit)
Build time : May 19 2019 - 13:08:20
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 7 (64-bit)
Plugins : ComparePlugin.dll DSpellCheck.dll mimeTools.dll NppConverter.dll NppExport.dll 

The file is UTF-8 encoded with Unix line endings.  I would expect the plugin to recognize the line endings in the file and adapt to them.  It appears to handle them well on encoding, but on decoding it chokes.  It does not encode them differently so as to recognize them when decoding them, which it should if it needs to in order to recognize the difference.  MIME encoding is meant to work with Unix encoded files just as well as Windows encoded files.

**Comment by MetaChuh** [comment]
@ggodhner 

many thanks for your detailed and complete mime tools plugin issue report, including all necessary steps to reproduce.

i can reproduce, that selecting all urls you have provided, in a linux (lf) line ending file, will cause mixed line endings, when using `plugins > mime tools > quoted printable encode`.
this in return can also not be decoded again, apart from breaking the line endings.

however, the mime tools plugin, albeit being an associated plugin, resides at a different repo, and you will have to file this issue at the [>>> mime tools plugin issue tracker <<<](https://github.com/npp-plugins/mimetools/issues).

our apologies for your inconvenience, and many thanks for your understanding.

best regards.

**Comment by ggodhner** [comment]
Thank you.  I have submitted a report to that issue tracker at [MIME Tools Plugin Issue Tracker #11](https://github.com/npp-plugins/mimetools/issues/11).
