### ISSUE TITLE
"Delete to start/end of line" shortcuts only change last line selected in multi-line editing 

### ISSUE THREAD

**Issue by Bartimaeus-** [notepad-plus-plus/notepad-plus-plus#5719]
### Description of the Issue

Using the [keyboard shortcuts](http://docs.notepad-plus-plus.org/index.php/Keyboard_And_Mouse_Shortcuts) for "Delete to start of line" or "Delete to end of line" (Ctrl-Shift-BackSpace or Ctrl-Shift-Delete)  during multi-line editing will only delete to the start/end for the last line that had a cursor added to it instead of applying the commands to all of the selected lines.

![image](https://user-images.githubusercontent.com/2954254/58672095-2d99cd80-82fa-11e9-8124-0b38ba3f4e3c.png)

Note that this behavior also applies to delete to start/end of word as well, although this seems like a less likely usecase.

### Steps to Reproduce the Issue

1. Open/create a file for editing with several lines of text
2. Use Ctrl-Click or Alt-Shift-Up/Down Arrow keys to add cursors to multiple lines of text
3. Use Ctrl-Shift-BackSpace or Ctrl-Shift-Delete

### Expected Behavior

Delete to the start or end of line applied to the selected lines.
### Actual Behavior

Only the line that was last selected will be changed.

### Debug Information

Notepad++ v7.6.6   (32-bit)
Build time : Apr  3 2019 - 23:49:50
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10 (64-bit)
Plugins : ComparePlugin.dll DoxyIt.dll mimeTools.dll NppConverter.dll NppExport.dll

**Comment by sasumner** [comment]
@Bartimaeus

You really should test this in Notepad++ 7.7 as the Scintilla editing component used has had a huge update between 7.6.6 and 7.7.  My testing shows NO ISSUE exists for your complaint.

> ... last selected will be changed

I'll point out that this is a common Notepad++ behavior for most operations that work upon a selection.  The "last" selection is what Scintilla terms the "main" selection, and the Notepad++ code typically works upon only this selection.  For a (non-Scintilla) example, if you set up a Replace-All-in-Selection scenario and then set up multiple selections before pressing the button, you'll notice that only the text in the "last"/main selection gets modified.

**Comment by Bartimaeus-** [comment]
@sasumner 

You are totally right, I just updated to version 7.7 and the behavior is no longer present, much appreciated. I definitely should have checked that I had the latest version before submitting the issue.

That extra background information is good to know, I hadn't considered multi-line editing to be as similar to operations that work upon a selection. I will definitely keep that behavior in mind in the future.
