### ISSUE TITLE
Remember language selection during update

### ISSUE THREAD

**Issue by BitPatty** [notepad-plus-plus/notepad-plus-plus#5722]
### Description of the Issue
It's a minor issue, but it would be great if this could be addressed at some point.
During an application update you have to choose the language from the dropdown menu. The dropdown defaults to the OS' display language instead of remembering the selection from the previously installed version.

### Steps to Reproduce the Issue
1. Install N++ in language X on a machine with language Y
2. Run the updater

### Expected Behavior
The installer should automatically choose language X from the dropdown.

### Actual Behavior
Installer defaults to language Y.

### Debug Information
_omitted_

**Comment by MetaChuh** [comment]
@BitPatty 

we are using the nsis installer, and we haven't found a way to remember the last selected installer language, only the contents of the program to be installed can be analysed and set easily, but not the installer itself.

many thanks and best regards.
