### ISSUE TITLE
Notepad++ freezes when Ctrl+End is pressed

### ISSUE THREAD

**Issue by mladenb** [notepad-plus-plus/notepad-plus-plus#5723]
### Description of the Issue
Opening an .sql file, 6.8 MB in size, with 10K lines, causes Notepad++ to freeze when the file is open and a user presses Ctrl+End to scroll to the bottom of that file.

### Steps to Reproduce the Issue
1. Open an .sql file with 10K INSERT lines, with approx. file size of 7 MB
2. Once the file is open, press Ctrl+End

### Expected Behavior
The view scrolls to the bottom of the file (eventually).

### Actual Behavior
Notepad++ freezes (for at least 20 minutes, after which I just terminated the task).

### Debug Information
Renaming a file to a non-standard extension (like ".mld") resolved the issue and it seems Notepad++ worked quite fast with such a file. The assumption is that something is wrong with the .sql syntax highlighter or something similar.

**Comment by MetaChuh** [comment]
@mladenb 

i can not reproduce a freeze with a [sample sql file](https://sample-videos.com/download-sample-sql.php) of 8,6mb and 87mb, using notepad++ 7.7 64 bit.
only the inevitable scintilla lag is noticeable, if word wrap is enabled.

note: if your sql file has many long lines, you have to deactivate `view > word wrap`.
we can not speed up word wrap at the notepad++ part, as it is handled by the implemented scintilla editor component, which is an external project.
you can always check the latest [scite](https://www.scintilla.org/SciTEDownload.html) editor, to see if anything would be improved at the newest scintilla engine.

many thanks for your understanding and best regards.

-----
```
general notes:

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).
please file an issue as easy to understand and reproducible as possible.

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
(no extra account is needed, just use your github account to sign in)
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)
