### ISSUE TITLE
Hotkeys file with default falues shouldn't be present in portable package

### ISSUE THREAD

**Issue by mzso** [notepad-plus-plus/notepad-plus-plus#5724]
### Description of the Issue
All other config files seem to be created on-demand or are present as a .model file.
But apparently the hotkeys file was forgotten about. Which is sad because because these might be the most personal settings.

### Steps to Reproduce the Issue
1.  Take new version of NPP portable
2.  Overwrite the files in the portable version to be updated
3.  Observe loss of hotkey customizations, but other settings remaining.

**Comment by MetaChuh** [comment]
@mzso 

please skip overwriting the files you want to keep, when updating your portable versions.

many thanks and best regards.

-----
```
general notes:

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).
please file an issue as easy to understand and reproducible as possible.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
(no extra account is needed, just use your github account to sign in)
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)

**Comment by mzso** [comment]
So essentially there's no issue tracker anymore because everything's brushed off as "find you own workaround", or "don't do that".

**Comment by sasumner** [comment]
Just start over and remap all your keys.  Oh, and learn to be grateful for what you DO get.  Sheesh.

**Comment by mzso** [comment]
> 
> 
> Just start over and remap all your keys. Oh, and learn to be grateful for what you DO get. Sheesh.

You mean be grateful for ignoring bug reports of simply fixed, yet fundamental issues?

**Comment by MetaChuh** [comment]
@mzso 

don't get me wrong, but you are about the only portable user, that has hastily overwritten his settings without having any backup of it, and is still keen enough to admit it in public 😉

greetings.

**Comment by mzso** [comment]
[**@MetaChuh**](https://github.com/MetaChuh) commented on [2019. jún. 6. 22:45 CEST](https://github.com/notepad-plus-plus/notepad-plus-plus/issues/5724#issuecomment-499660769 "2019-06-06T20:45:13Z - Replied by Github Reply Comments"):
> [@mzso](https://github.com/mzso)
> 
> don't get me wrong, but you are about the only portable user, that has hastily overwritten his settings without having any backup of it, and is still keen enough to admit it in public ![wink](https://github.githubassets.com/images/icons/emoji/unicode/1f609.png)
> 
> greetings.

I don't get you wrong. You're more inclined to mock people and brush over bugs instead of assisting in fixing bugs.
Configuration files with default values should not exist in portable packages. Fact.

**Comment by sasumner** [comment]
"Configuration files with default values should not exist in portable packages"  INCORRECT.

**Comment by mzso** [comment]
[**@sasumner**](https://github.com/sasumner) commented on [2019. jún. 6. 23:08 CEST](https://github.com/notepad-plus-plus/notepad-plus-plus/issues/5724#issuecomment-499668128 "2019-06-06T21:08:00Z - Replied by Github Reply Comments"):
> "Configuration files with default values should not exist in portable packages" INCORRECT. Users that are (or think they are) savvy enough to use portable packages should know what they are doing.

Because obviously one should be aware of nonsensical bugged way of stuff being handled in the app for files that the user never touches in normal circumstances.

Gotta love this new development model of pretend all serious issues are not issues at all.
