### ISSUE TITLE
Incorrect syntax highlight for SQL "system objects" style

### ISSUE THREAD

**Issue by arfmach** [notepad-plus-plus/notepad-plus-plus#5725]
I've updated to N++ v7.7 and it still has the same problem.

![NotepadPlusPlus-V7 7-SQL-Syntax-Highlight](https://user-images.githubusercontent.com/7331118/58716010-8327b600-839e-11e9-8dd9-55edc0c906af.png)

_Originally posted by @arfmach in https://github.com/notepad-plus-plus/notepad-plus-plus/issues/1424#issuecomment-497748764_

**Comment by dail8859** [comment]
Pleas follow the provided template to reproduce your issue. Also please include a small code snippet.

**Comment by arfmach** [comment]
Where is "the provided template"???

**Comment by dail8859** [comment]
It is there when you created the issue. However, it should be noted that most likely you have custom edits to your `stylers.xml` file because `SYSTEM OBJECTS` and `SYMBOLS` do not come from Notepad++ at all.

**Comment by arfmach** [comment]
No, it wasn't there when I created the issue, since I referenced a message in a previous issue to open this new one. 
![image](https://user-images.githubusercontent.com/7331118/58841499-8641d100-8640-11e9-917d-9dca39664b0e.png)


And IMHO N++ should work accordingly in that case regardless of being custom edits to stylers.xml and/or langs.xml, since it is a completely normal usage.

**Comment by dail8859** [comment]
> No, it wasn't there when I created the issue, since I referenced a message in a previous issue to open this new one.

Fair enough. Didn't even know that was an option :) The template can be found [here](https://github.com/notepad-plus-plus/notepad-plus-plus/blob/master/ISSUE_TEMPLATE.md)

> And IMHO N++ should work accordingly in that case regardless of being custom edits to stylers.xml and/or langs.xml, since it is a completely normal usage and the edits didn't invalidate the files.

While the file is valid XML it does not mean you can just add anything in there and it magically works. They have to match up to the styles defined by Scintilla's lexer and how it parses the file. The current stylers.xml for SQL is show here:

https://github.com/notepad-plus-plus/notepad-plus-plus/blob/d14cb43e9d3c58d02af97149cd573c81bd862c47/PowerEditor/src/stylers.model.xml#L1113-L1123

**Comment by CurbedLarry** [comment]
Also tried to make edits to stylers.xml to split SQL keywords into categories (to assign multiple colours).  Was confused why it didn't just work.

So adding new SQL syntax categories is a feature request for Scintilla?

**Comment by dail8859** [comment]
@CurbedLarry The styles recognized by the Scintilla SQL Lexer are defined [here](https://github.com/notepad-plus-plus/notepad-plus-plus/blob/34cd6db3be589ae96588c287d821081ffa3c18b4/scintilla/include/SciLexer.h#L1286-L1308). It looks like there is support for more wordlists, however I think to support that it would need some [code changes here](https://github.com/notepad-plus-plus/notepad-plus-plus/blob/17628b7dd9ebd432d38d3fcb809e694d71ad6889/PowerEditor/src/ScitillaComponent/ScintillaEditView.h#L734) along with XML changes

**Comment by CurbedLarry** [comment]
> some [code changes here](https://github.com/notepad-plus-plus/notepad-plus-plus/blob/17628b7dd9ebd432d38d3fcb809e694d71ad6889/PowerEditor/src/ScitillaComponent/ScintillaEditView.h#L734) along with XML changes

Hi @dail8859 , checking **LexSQL.cxx** it does support multiple keyword lists, even if the 3rd/4th are intended to be Oracle specific.  It certainly appears the below would be enough to enable a second list in the XML files (for say data types):

> setLexer(SCLEX_SQL, L_SQL, LIST_0 **| LIST_1);**

What's the best way to request this change?
