### ISSUE TITLE
'Save as...' Error: Can't overwrite file already opened in NPP

### ISSUE THREAD

**Issue by paronos** [notepad-plus-plus/notepad-plus-plus#5726]
### Description of the Issue
Unlike other [text editors](https://en.wikipedia.org/wiki/List_of_text_editors#Graphical_user_interface), NPP's _Save As..._ dialog prevents overwriting file already opened in NPP? 
Seems to affects both styles of [Open/Save dialog](https://notepad-plus-plus.org/community/topic/15743): New & Old

![NPP Save as Error](https://user-images.githubusercontent.com/23290139/58725806-9c952600-83cf-11e9-8694-c9edaf9d9d95.png)

Found some NPP Community forum posts on this issue:
[16343](https://notepad-plus-plus.org/community/topic/16343)
[15798](https://notepad-plus-plus.org/community/topic/15798)
But I wonder is this a deliberate restriction, and if so, why? :thinking:

### Steps to Reproduce the Issue
Apparently, this restriction also lead to another issue:
1. Use NPP to open 2 files with the same filename and file extension, but each reside in a separate folder
2. Edit contents of 1 file (Active tab) and save changes to the other file (on Background tab).

Now, imagine there are currently multiple tabs (30+ files) opened in NPP, having to close the other tab (on Background tab) before the current file (Active tab) is allowed to overwrite that closed file can be counter-productive and tedious :anguished::weary:

![NPP Save as Error](https://user-images.githubusercontent.com/23290139/58725877-c2bac600-83cf-11e9-9d01-a4b7d856bd66.jpg)

### Debug Information
Notepad++ v7.7   (64-bit)
Build time : May 19 2019 - 13:05:35
Path : C:\Users\timd\Desktop\npp.7.7.bin.x64\notepad++.exe
Admin mode : OFF
Local Conf mode : ON
OS : Windows 7 (64-bit)
Plugins : mimeTools.dll NppConverter.dll

**Comment by MetaChuh** [comment]
@paronos 
not permitting to "save as" with a filename of a file that is still opened in notepad++ is by design.
please just save it normally, if you don't want to save it with a different file name.

many thanks and best regards.

**Comment by sasumner** [comment]
Or just close the file tab you intend to use as the target for a future SaveAs...not too hard...not too burdensome.  

A lot of typing up of an issue, screenshotting, even linking to the definition of a text editor(!) for us--thanks!...for such a non-issue.
