### ISSUE TITLE
Highlight .R files like R language, not REBOL

### ISSUE THREAD

**Issue by Fifis** [notepad-plus-plus/notepad-plus-plus#5727]
### Description of the Issue
By default, N++ highlights the syntax of all .R files as REBOL.  Given the fact that its last stable version was released in 2011 and R is roughly 100 times more popular (compare around 2000 StackOverflow questions on Rebol and around 290,000 on R), we are robbing users by assuming that they are using a more obscure and much less popular language by default.

### Steps to Reproduce the Issue
Try to open a valid R script with N++, and one will get REBOL syntax highlighting.

### Expected Behavior
R highlighting.

### Actual Behavior
REBOL highlighting.

**Comment by dail8859** [comment]
Already reported and fixed. See #3650

**Comment by MetaChuh** [comment]
@Fifis 

on recent versions, r files should be recognised as r, and not as rebol, as seen at the default extensions screenshots below.

<img width="806" alt="" src="https://user-images.githubusercontent.com/45773305/58759240-1a1f7a00-8527-11e9-8d19-1ecb2d0c32d8.png">
<img width="807" alt="" src="https://user-images.githubusercontent.com/45773305/58759241-1a1f7a00-8527-11e9-97e9-8233d03c7425.png">

unfortunately you did not provide us with your debug information, so we don't know which version you have, or how it was installed.

**but if you already are on a default install of a newer version, like 7.7. or 7.6.6, and your .r files still open as rebol, please do the following:**
* close notepad++ if it is running
* open `%AppData%\Notepad++\` in windows explorer and delete `langs.xml`.
* start notepad++ (`%AppData%\Notepad++\langs.xml` will be created using the latest `langs.model.xml` of the currently installed version).
* retry opening an .r file and it will be recognised as r.

many thanks and best regards.

-----
```
general notes:

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).
please file an issue as easy to understand and reproducible as possible.

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
(no extra account is needed, just use your github account to sign in)
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)

**Comment by FVFaleiro** [comment]
This error persist in the Notepad ++ version 7.7.1.
I tried the @MetaChuh solution without success.

Debug information:
Notepad++ v7.7.1 (32-bit)
Build time : Jun 16 2019 - 21:14:50
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10 (64-bit)
Plugins : DSpellCheck.dll mimeTools.dll NppConverter.dll NppExport.dll
