### ISSUE TITLE
Error on right click

### ISSUE THREAD

**Issue by begem** [notepad-plus-plus/notepad-plus-plus#5728]
When in settings active "hide main menu (alt or f10)",  right click on anywhere frozen npp

**Comment by sasumner** [comment]
@begem Follow the issue template for reporting an issue to be taken seriously.

**Comment by MetaChuh** [comment]
@begem 

not reproducible on notepad++ 7.7 using the given information.

many thanks and best regards.

-----
```
important notes:

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).
please file an issue as easy to understand and reproducible as possible.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
(no extra account is needed, just use your github account to sign in)
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)
