### ISSUE TITLE
Wbudowany Tlumacz

### ISSUE THREAD

**Issue by danielc30** [notepad-plus-plus/notepad-plus-plus#5729]
przydał by sie  wbudowany Tłumacz który działa na zasadzie poprawnej pisowni
czyli klik prawym na wyraz /menu kontekstowe/ język  ustawiony w opcjach programu / i tłumaczenie na ten język

### Steps to Reproduce the Issue

1. 
2. 
3.

**Comment by MetaChuh** [comment]
@danielc30 

we will not integrate a human language translatio engines into the notepad++ core.
maybe one day someone continues developing the work on, for example, the npptranslate plugin, to suit your wishes.

best regards.

-----
```
general notes:

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).
please file an issue in english and as easy to understand as possible.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
(no extra account is needed, just use your github account to sign in)
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)
