### ISSUE TITLE
Customizable toolbar

### ISSUE THREAD

**Issue by h-h-h-h** [notepad-plus-plus/notepad-plus-plus#573]
It would be appreciated if the toolbar would be customizable, that is, reordering the icons and removing/readding icons would be possible.

In combination with issue https://github.com/notepad-plus-plus/notepad-plus-plus/issues/629 the toolbar would not be overwhelming and/or more intuitively to use.

**Comment by Rikk** [comment]
+1
Even the tasteless Notepad2 has this feature...

**Comment by Rikk** [comment]
Hey, for those who don't know, there is a plugin called "Customize Toolbar" that does indeed add the dialog we are looking for.
It doesn't, however, add a context menu.

**Comment by milipili** [comment]
http://sourceforge.net/projects/npp-customize/

**Comment by h-h-h-h** [comment]
I wish that the plug-in functionality is either available out of the box with proper integration or that the plug-in ships with Notepad++ and gets an integration with context menu and such that doesn't make it distinguishable from program functionality.

Can a plug-in be as trouble free as program functionality in the future?

**Comment by milipili** [comment]
If not, this issue would have been closed :)
