### ISSUE TITLE
Plugin Admin n++ 7.7 notepad++ closes to install checked plugins but doesn't install nothing and doesn't restart automactically

### ISSUE THREAD

**Issue by wonkawilly** [notepad-plus-plus/notepad-plus-plus#5730]
### Description of the Issue

Plugin Admin n++ 7.7 notepad++ closes to install checked plugins but doesn't install nothing and doesn't restart automactically

### Steps to Reproduce the Issue

1. Just downloaded the 32 bit zip file from the official website
2. Unzipped in the desktop (Win7)
3. Launch n++
4. Go into Plugins menu > click on Plugins Admin
5. Check plugins I want to install
6. Click on Install
7. Notepad++ shows a message to advise me that is going to close, install plugins and restart
8. I click on OK button
9. Notepad++ closes but it doesn't install any plugin and it doesn't restart
10. I've to restart it manually and nothing new in plugins menu have been installed 

Procedure tested in both modes: normal and admin mode (see debug info)

### Expected Behavior

I expected n++ to install plugins I checked and restart notepad to complete installation

### Actual Behavior

Notepad++ closes but it doesn't install any plugin and it doesn't restart without my manual intervention

### Debug Information

Admin mode off:
Notepad++ v7.7   (32-bit)
Build time : May 19 2019 - 13:08:20
Path : C:\Users\username\Desktop\npp.7.7.bin\notepad++.exe
Admin mode : OFF
Local Conf mode : ON
OS : Windows 7 (32-bit)
Plugins : mimeTools.dll NppConverter.dll NppExport.dll 

----
Admin mode on:
Notepad++ v7.7   (32-bit)
Build time : May 19 2019 - 13:08:20
Path : C:\Users\Montaggio Video\Desktop\npp.7.7.bin\notepad++.exe
Admin mode : ON
Local Conf mode : ON
OS : Windows 7 (32-bit)
Plugins : mimeTools.dll NppConverter.dll NppExport.dll

**Comment by MetaChuh** [comment]
@wonkawilly 

many thanks for your detailed debug info.
i can not reproduce this behaviour.
is this machine behind a proxy server or corporate firewall ?

**Comment by wonkawilly** [comment]
@MetaChuh
> @wonkawilly
> 
> many thanks for your detailed debug info.
You are welcome and thank you for your response.

> i can not reproduce this behaviour.
> is this machine behind a proxy server or corporate firewall ?

I'm almost sure (99%) that my internet service provider has kinda of proxy server or firewall or NAT. My computer is behind one or more of that services. I deduce that because my router ip isn't the same of my public ip address. Also p2p and dyn-dns don't work either. This is something recent. Few months ago I had a different provider, a "normal" one, with a dynamic and public ip address directly on my modem router. But Plugin Admin was giving me problems at that time too, I couldn't never use it.

One more thing I forgot to say: Plugin Admin doesn't work as I said before. So I had to install the old Bruderstein Plugin Manager in its place. This still works and at the moment is the only alternative I have left to manual installation of plugins. I deduce these tools work in a complete different way. I would like to use the Plugin Admin plugin because it is provided with an useful search feature that allows to search for a plugin instead of scrolling the whole list, that is pretty useful feature.

Thanks in advance

**Comment by MetaChuh** [comment]
@wonkawilly 

if you can find out your provider's proxy settings, please try to start notepad++ as administrator and set your proxy at the notepad++ menu `? > set updater proxy...`

the difference to the way plugin manager works, is that plugins admin requires manual proxy settings per design, to avoid unwanted automatically set proxy settings to try to avoid re-routing security concerns, caused by user unaware automatic proxy settings.

many thanks and best regards.

**Comment by wonkawilly** [comment]
Thanks for the answer.

Well the **notepad++ menu ? > set updater proxy** is not present in n++ v 758 (I still have in use a 758 portable version), while in v 7.7 is present that menu item.

OK that said, in v 7.7, I set more or less 10 different proxy IPs, and the relative port in that dialog, but n++ behaves in the same manner as I pointed out in my OP: it closes and doesn't install anything, nor automatically restarts.

Sorry no offence but IMHO Don Ho has to set Plugin Admin to work as Plugin Manager. I never had the need to modify any proxy settings with or anything else. In fact for me it still works pretty, never a problem of proxies or anything under any internet service provider not even my current one. I think that simpler is better, even for newbies. So please don't complicate things that really don't need to.

So I'm still looking forward for a solution for this issue.

Thanks for comprehension.
