### ISSUE TITLE
Fake new line when using indent before long line without spaces in wrap mode

### ISSUE THREAD

**Issue by anki-code** [notepad-plus-plus/notepad-plus-plus#5734]
### Description of the Issue
Notepad++ shows fake new line when using indent (spaces or tabs) before long line without spaces and wrap mode ON.

### Steps to Reproduce the Issue, Actual and Expected Behavior
![image](https://user-images.githubusercontent.com/1708680/58792450-dd25b700-85fc-11e9-8815-170f1df3e57a.png)

### Debug Information
Notepad++ v7.7   (64-bit)
Build time : May 19 2019 - 13:05:35
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10 (64-bit)

**Comment by sasumner** [comment]
I believe this has come up before.  The problem is the L-O-N-G third line with no whitespace in the part before it hits the right edge of the window.  Thus Scintilla (not Notepad++) is treating the whole thing as second and succeeding lines of a wrapping.  Sure, it's a bug.  I'd check the Scintilla issues list and see if there are plans for addressing it.

Nice upvote of your own issue, BTW....maybe you were upvoting the title change, also yours.  :)

**Comment by anki-code** [comment]
Ticket for Scintilla — https://sourceforge.net/p/scintilla/bugs/2107/

**Comment by MetaChuh** [comment]
@anki-code 

as this fake line experience is the behaviour of the scintilla component, we can't do much about it at the notepad++ part.

note: you can always check the latest [scite](https://www.scintilla.org/SciTEDownload.html) editor, to see if anything has been fixed at the scintilla engine.

many thanks for your understanding and best regards.

**Comment by sasumner** [comment]
>you can always check the latest scite editor, to see if anything has been fixed at the scintilla engine

Truth.  I tried in Sc415 and it has same behavior as N++ 7.7 (where the 4.14 version of Scintilla is used).

**Comment by anki-code** [comment]
@sasumner @MetaChuh Zufu Liu from Scintilla talks about settings — https://sourceforge.net/p/scintilla/bugs/2107/#aefc/2697/5170 — but it looks like there no this settings in Notepad++:

![image](https://user-images.githubusercontent.com/1708680/58870247-82f22800-86c8-11e9-9518-13a4d7b13798.png)

**Comment by sasumner** [comment]
>Zufu Liu from Scintilla

I think Zufu is just the author of Notepad2 and has no affiliation with the Scintilla project personnel (could be wrong).

>but it looks like there no this settings in Notepad++

True, it appears Notepad2 (which is shown in your screenshot and also uses Scintilla) has more options concerning wrapping than does Notepad++.  A lot of what is shown is possible to control in Notepad++ via scripting.  

BUT...I'm unclear as to which of the settings shown for Notepad2 avoid the wrapping problem that THIS issue describes?

**Comment by anki-code** [comment]
@sasumner thank you for explanation. It looks like I should wait the fix from Scintilla
