### ISSUE TITLE
[Feature Request] Websocket support

### ISSUE THREAD

**Issue by Burkino** [notepad-plus-plus/notepad-plus-plus#5736]
I was wondering if there was a websocket feature.
For example to use ws://localhost:PORT/command to be able to communicate to another app without needing to copy the text, paste it into the app.
Websockets could also be used to read data, for example a custom function in a modified language.
The port and commands should be changeable and hotkey support (like Ctrl+Enter) would be great.

**Comment by dail8859** [comment]
This would be much more appropriate if handled by a plugin. For the small percentage of users that would use it, doesn't justify natively developing it and supporting it.

If you are interested in developing it I'd reccomend looking into the PythonScript plugin.
