### ISSUE TITLE
nodepad++ change file permission when edit samba shared files on windows

### ISSUE THREAD

**Issue by yuanjianpeng** [notepad-plus-plus/notepad-plus-plus#5738]
### Description of the Issue
Using nodepad++ edit a file on windows 10, the file is shared by samba from a Linux server. When save it, the file permission changed.

### Steps to Reproduce the Issue

1. touch a file "s" in linux command line, see its permission
$ touch s
$ ls -l s
-rw-rw-r-- 1 yuanjianpeng yuanjianpeng 0 Jun  4 03:30 s
2. edit it with nodepad++ on windows, then save it.
3. see file permission again, a user execute permission is added
$ ls -l s
-rwxrw-r-- 1 yuanjianpeng yuanjianpeng 3 Jun  4 03:32 s

### Expected Behavior

File permission is not changed, when edit then save

### Debug Information

If I edit it using windows shipped editor, the file permission is not changed.

**Comment by yuanjianpeng** [comment]
my nodepad++ is 64bit v7.7

**Comment by MetaChuh** [comment]
@yuanjianpeng 

i can not reproduce this on a mac share and as well as a synology nas.
all permissions are kept as they are with the stock settings of those systems.

many thanks and best regards.
