### ISSUE TITLE
notepad++ 7.6 Portable - Update in Windows is wrong

### ISSUE THREAD

**Issue by volker001** [notepad-plus-plus/notepad-plus-plus#5739]
### notepad++ 7.6 - Portable - Update in Windows is wrong
- Windows 8.1 - 64 bit

Notepad++ shows me, there is an update.
i take the update, but then notepad installs lokal
and not in the portable directory.

### Steps to Reproduce the Issue

- my current user-account is not admin
- during the update the uac prompts and i give an admin-account.
- then notepad++ installs in ...\Program Files\... and not in the portable dir.

**Comment by donho** [comment]
@volker001 Could you provide me the URL where you download your 7.6 ?

**Comment by volker001** [comment]
downloaded from the offical site:
https://notepad-plus-plus.org/

**Comment by donho** [comment]
This problem is fixed in v7.7 - the auto-updater is disabled but you can still trigger it manually via menu.
Please reopen it if 7.7 triggers updater automatically.

**Comment by volker001** [comment]
thank you for the information.
