### ISSUE TITLE
Plugins Admin: add plugin release date

### ISSUE THREAD

**Issue by cmeriaux** [notepad-plus-plus/notepad-plus-plus#5742]
### Description of the Issue
Add in the plugin admin UI the plugins release date

**Comment by donho** [comment]
IMO, users don't care to learn a new released plugins, they need to find the ones they need. Or if users want to know the new update, they can go to Update tab to install them.
So "release date" is not even NTH, it's just useless.

**Comment by cmeriaux** [comment]
It can be useful to find recent new plugin that is not already install. Once a month, or once a year, you'dd like to see what's news.
Sometimes you are not looking for a particular plugin, you are looking for a plugin that can be useful for you. Searching for a new plugin can be exhausting.
so sad ............

**Comment by pnedev** [comment]
That would have been really nice feature @donho
