### ISSUE TITLE
Automatic tab-to-space conversion does not work.

### ISSUE THREAD

**Issue by rovf** [notepad-plus-plus/notepad-plus-plus#5745]
### Description of the Issue
I have checked in Preferences/Language on Tab Settings "Replace Tab by Spaces".
But when I open a document, which contains a tab, it is not automatically converted to spaces.

Notepad++ 7.5.9 (64 Bit)

**Comment by sasumner** [comment]
This behavior is by-design.  It is working correctly.  Please use _Edit (menu) -> Blank Operations -> TAB to Space_ to effect your desired conversion.

**Comment by MetaChuh** [comment]
@rovf 

replace tab by spaces only replaces newly typed <kbd>tab</kbd> characters with the amount of spaces at this setting.

to convert tabs in an existing document, please follow @sasumner 's guide from above.

best regards.
