### ISSUE TITLE
HEX viewer is completely broken now

### ISSUE THREAD

**Issue by pps83** [notepad-plus-plus/notepad-plus-plus#5747]
I was checking binary output that my code produces and it totally didn't make sense, everything seemed to be wrong. After digging and wasting time, it appears that HEX viewer is now completely broken.

here's what I see in notepad++:
![image](https://user-images.githubusercontent.com/1614246/58980254-bd20ff80-8784-11e9-9ee3-32669312201b.png)

and here's what online hex viewer shows (as you can see data is completely different):

![image](https://user-images.githubusercontent.com/1614246/58980285-cad68500-8784-11e9-9fa9-fc23d133951b.png)

**Comment by sasumner** [comment]
Notepad++ doesn't have a "hex viewer".

**Comment by chcg** [comment]
@pps83 See https://github.com/chcg/NPP_HexEdit/issues/16, seems you found a similar issue. Please contribute to that issue or create a new one at the ticket queue of the plugin itself. Add some infos which version of the plugin you use, which version of n++, windows and the bitness.
