### ISSUE TITLE
PHP code embedded in JavaScript quotes not styled as PHP

### ISSUE THREAD

**Issue by brandpeter** [notepad-plus-plus/notepad-plus-plus#5750]
### Description of the Issue
In JavaScript block, embedded PHP script is not recognized when inside single or double quotes.

### Steps to Reproduce the Issue
Enter code in a JavaScript block which is a mixture of JS and PHP code where the PHP code is inside a JS string (double or single quotes).

### Expected Behavior
code inside the PHP tags to be colored as per style for PHP

### Actual Behavior
PHP code appears as plain string according to JS style

### Debug Information
Notepad++ v7.7   (64-bit)
Build time : May 19 2019 - 13:05:35
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10 (64-bit)
Plugins : ComparePlugin.dll Explorer.dll mimeTools.dll NppConverter.dll NppFTP.dll NppSaveAsAdmin.dll _CustomizeToolbar.dll

**Comment by brandpeter** [comment]
The code above should be 
`var xyz = {value : '123', valueFrom : '<?php echo $dateFrom; ?>', valueTo : '<?php echo $dateTo; ?>'}`

**Comment by MetaChuh** [comment]
@brandpeter 

this is the designed behaviour of the scintilla lexer, which is an external project, as all code parts within quotes will be interpreted as standard text.

you can try to file a feature request at the scintilla project about that, but i have doubts that it would be accepted.

many thanks and best regards.

**Comment by ArkadiuszMichalski** [comment]
Fixed by https://github.com/ScintillaOrg/lexilla/commit/622d3b726fd85b1b09ff5f95bb5f3027d3107b12.

**Comment by ArkadiuszMichalski** [comment]
Fixed by https://github.com/notepad-plus-plus/notepad-plus-plus/commit/a61b03ea8887e21c6e1b7374068962f635b79b80.
