### ISSUE TITLE
NPP "loses" mouse pointer

### ISSUE THREAD

**Issue by zb-z** [notepad-plus-plus/notepad-plus-plus#5752]
There's no deterministic repro and it could be partially Windoze's "fault" (happens to VS sometimes as well). You'll need to walk through the code that changes mouse pointer when mouse enters your window's area and which signal gets sent when user changes the pointer (in control panel) even just temporarily (cancels afterwards => "recovery signal" comes from the temp change "event").

I don't claim to know exactly what happens - my best guess is that some pointer or handle becomes "null" or pointing to "null image" (Windoze is prob tolerant when it sees bull or invalid handle so it just gives you "nothing picture" for "nothing handle" :-)

Could be milti-threading problem - if handle is closeable and a smart pointer protects it and at some point it "thinks" that there are no more references or it leaves the scope if shouldn't have left. This is probably too low-level since VS is all C# these days and it still happens => GC doesn't help. If there's COM in-between, that thing trips on "reference not asked enough times" all the time.

For recovery, I just open mouse control panel and fake change of the pointer image for "Normal Select" and at that very instant NPP recovers pointer images => there is a signal to which it reacts and "redos" something - like asking for new handles for example.
 
There could be other "angles" - like maybe you are supposed to ask for new handles all the time (or after certain period) and you are "caching" instead to save time.

It could be correlated to "too many things open" (I had "new language defining") and "style Configurator" open at the same time. Come to think of it, there's always implicit race condition between these two. But it could also be that you have the limit on "handles" and these two are particularly demanding.

That "Debug Info" won't tell you much. Even if it is correlated to x86 binary running under x64 OS that's waaaay too far fetched and doesn't help at all.

"Debug Info"
Notepad++ v7.7   (32-bit)
Build time : May 19 2019 - 13:08:20
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10 (64-bit)
Plugins : mimeTools.dll NppConverter.dll NppExport.dll

**Comment by Ekopalypse** [comment]
Sounds more like a "additional mouse driver software installed" or some kind of "automate my mouse clicks software installation" problem rather than a npp problem.

**Comment by zb-z** [comment]
No no no - it's a long standing/known problem with Visual studio that they refuse to tackle since you can't have deterministic repro and to some degree it is Windoze's fault :-)) Till I saw HPP and latter one other well known app :-) I was sure it was just "a VS mess up".
Windoze's problem is probably to a degree that it closes some handles when and where it shouldn't but the fact is that it doesn't affect Desktop (which is also just a UI program) and probably no other MS software but VS.
It could also be that a number of people "don't exactly follow the protocol" and those doing desktop have tough code reviews (since they ship with OS) and VS doesn't.
I'm not a UI guy so I'm guessing posible semi-root causes, fully aware that part of the blame might be Windoze itself but also that there is a code path along which that doesn't happen.
The mouse pointer functionality doesn't suffer - it's just the image for that pointer that becomes "empty" - until the app that "got lost" receives "strong enough" signal that "pointers have changed" an dat point it does something to "refetch" (which could mean asking for handles to GDI objects again for example).
If you locate that piece of code then the "solution" is to make it run all the time - kind of :-)  "All the time" would mean "after some period expired" - more or less treating them like untrusted cache but still not re-fetching every microsecond.
The are also 2 "signals" - determined empirically :-) and HPP is actually more responsive - reacts to "weak signal" (image changes in Mouse control panel but still not confirmed). The reason I know is that I also caught Chrome in the same kind of trouble and it was tone death :-)) I reacted only to "string signal" (you confirmed the change of the picture for mouse pointer). 
So, whoever knows actual details and has full debug build with source need to see it in debugger what actually happens (signal/event wise) in the app when you change the image for arrow in controller panel and then follow it from there (see all references etc.). 
The addition of Chrome to the list is what leads me to believe that it's partially Windoze's problem but that doesn't help at all - Windoze is a given :-) 
Remember that GDI handle exhaustion was huge problem for like 2 decades? It's easy to imagine that something is too eager to close/recycle, stemming from that past scare. So it could also be that there's a way for an app to "hard lock" it's handles or it has to do something periodically to make big daddy register that "it's still actively using them" vs leaking or being stuck.
Just hyper guessing but it all leads to - you have to know what's actually happening in greater detail and you have to do something more often.
It could also be that GDI handle exhaustion is still happening or that kernel thinks that's it's happening with particular process tree under some circumstances and does a lil preemptive strike :-) And it doesn't touch those that look like they are "behaving well" :-) 
BTW mouse drivers don't handle images for mouse pointer. When I use the term "signal" I use it in a very generic way. Many libraries invent names to make the kind of signaling they are dealing with sound "oh so special" :-) but they are all signals - by nature :-) 


    On Friday, June 7, 2019, 8:19:18 AM PDT, Ekopalypse <notifications@github.com> wrote:  
 
 
Sounds more like a "additional mouse driver software installed" or some kind of "automate my mouse clicks software installation" problem rather than a npp problem.

**Comment by sasumner** [comment]
@zb-z What the heck is "HPP" you refer to several times??  You have a lot of "great advice" for other people to dive in and solve this problem, but probably the only person that will be able to do that is you, since apparently it happens on your system.  I have used Notepad++ for 4+ years under Win7 and Win10 and have never seen such an issue.  Get the source and dive in.  Good luck.  Please report back your (tangible) findings.

**Comment by Ekopalypse** [comment]
@zb-z to be honest, I don't understand what you are talking about - my translator seems to have a problem generating something understandable. From my limited English knowledge I get that you are sure, that this is something known to windows operating systems and everyone should be aware of. 
If this is the case, then I can only agree to what @sasumner  already posted - never occurred to me but what happened to me was something different but somehow similar. I bought a new logitech mouse which installed some additional software used for _better gaming experience_ but what actually happened was that moving windows was now very slow, means the mouse already pointed to the new location but the window was still moving. Once I removed that additional software everything was working again.
Btw. 2 decades ago I was at the age of 12, so no, I don't know about that GDI issue :-D
I was more interested in playing football (the REAL football not the american one) :-D
Sorry, seems I can't be of any help in this case.

**Comment by dail8859** [comment]
I agree with @sasumner. Since there are no known steps to reproduce the issue it will be nearly impossible for someone to fix. So either more details are needed (e.g. some other software causing it or exact steps) or you would have to debug it yourself (which it sounds like you have some very good experience to try to find the issue).
