### ISSUE TITLE
paste into 'Replace' after 'Replace' is already open finds 0 occurrences

### ISSUE THREAD

**Issue by joeinsweden** [notepad-plus-plus/notepad-plus-plus#5755]
### Description of the Issue

If you open the Replace diaglog box, then go back to the editor and copy text from a file you already have open and paste it into the Replace 'Find what:' field, the text is not found and the message '0 occurrences were replaced' appears.

### Steps to Reproduce the Issue

1. Open a file
2. Choose 'Search' then 'Replace'
3. Copy some text from the open file
4. Paste the text in the 'Find what:' field in the Replace window
5. Enter som test in 'Replace with:'
6. Click Replace All

### Expected Behavior

Text should be replaced in the open file

### Actual Behavior

No text is replaced in the open file

### Debug Information
Notepad++ v7.5.9   (32-bit)
Build time : Oct 14 2018 - 15:02:52
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10 (64-bit)
Plugins : DSpellCheck.dll mimeTools.dll NppConverter.dll NppExport.dll ComparePlugin.dll XMLTools.dll

**Comment by MetaChuh** [comment]
@joeinsweden 

many thanks for your debug information.

unfortunately i can not reproduce an issue with replace all, when copying a text section of an opened document to the already previously opened replace > find what field, using notepad++ 7.5.9 and 7.7, as seen at the screenshot below.

<img width="807" alt="" src="https://user-images.githubusercontent.com/45773305/59089948-ace75c80-890b-11e9-927a-c7bca4fc9c00.png">

**please test the following, to verify, if a clean notepad++ would work on your system.**

* download the notepad++ 7.7 portable version from [>>> here <<<](https://notepad-plus-plus.org/repository/7.x/7.7/npp.7.7.bin.zip).
(the portable version does not require any installation and runs completely independent and isolated from your installed version. all custom settings, as well as any stuff you might want to try at the portable version, will not modify your installed version)

* extract `npp.7.7.bin.zip` to your desktop.

* **important note:** make sure to close all instances of notepad++ that might be running, before starting the portable version at the next step, to make sure you are using this portable version.

* open the extracted `npp.7.7.bin` folder and start this portable version by double-clicking on `notepad++.exe` inside this folder.
(note: notepad++.exe will just be seen as notepad++, if you have enabled to hide all known file extensions at your explorer settings)

* try to perform a replace all with a copied text part, at a document of your choice.

many thanks and best regards.

-----
```
general notes:

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
(no extra account is needed, just use your github account to sign in)
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)

**Comment by sasumner** [comment]
@joeinsweden If you still think this is a valid issue, reproduce it and then copy and paste a screenshot of your Replace window in here.

**Comment by astrohart** [comment]
Me too.  This happens in v7.9.1 (32-bit) and is taking place in the **Find in Files** box.

**Comment by sasumner** [comment]
@astrohart / @joeinsweden 
You may be a victim of this phenomenon:  https://community.notepad-plus-plus.org/topic/20626/invisible-characters-make-difficulties-when-searching/
