### ISSUE TITLE
renaming .ffs_batch files breaks syntax highlighting

### ISSUE THREAD

**Issue by patrickdrd** [notepad-plus-plus/notepad-plus-plus#5756]
when opening .ffs_batch (freefilesync application) files,
they are detected as .xml files, which is correct,
but renaming (i.e. changing file name only of course) breaks syntax highlighting

I'm attaching a sample file (please rename to template.ffs_batch):
[template.ffs_batch.txt](https://github.com/notepad-plus-plus/notepad-plus-plus/files/3264977/template.ffs_batch.txt)

open it in npp,
you should see it detected as xml file, 
rename its file name and you'll see syntax highlighting is gone

the issue happens on both 7.6.6 and 7.7.0

debug info:
Notepad++ v7.7   (32-bit)
Build time : May 19 2019 - 13:08:20
Path : D:\Utilities\PortableApps\Notepad++\notepad++.exe
Admin mode : ON
Local Conf mode : ON
OS : Windows 7 (64-bit)
Plugins : AutoSave.dll BracketsCheck.dll combine.dll ComparePlugin.dll DSpellCheck.dll LuaScript.dll mimeTools.dll NppConverter.dll nppcrypt.dll NppExport.dll NPPTextFX.dll PluginManager.dll PythonScript.dll

**Comment by MetaChuh** [comment]
@patrickdrd 

many thanks for your debug information and sample 👍
this happens as a rename procedure will select the lexer based on the file extension only, and ffs_batch is not set as a default file extension for xml.

please open `settings > style configurator > xml` and add `ffs_batch` to the user extensions.
after that you can rename this file, without losing the syntax highlighting.

many thanks and best regards.
