### ISSUE TITLE
Bug: Syntax hihlighting does not work for Lua language

### ISSUE THREAD

**Issue by dvdvideo1234** [notepad-plus-plus/notepad-plus-plus#5757]
### Description of the Issue

Install or update Notepad++ to version 7.7

### Steps to Reproduce the Issue

1. Open notepad
2. Open a Lua file ( for example )
3. Language -> "L" -> Lua ( for example )

### Expected Behavior

NPP to highlight the file

### Actual Behavior

NPP does not highlight the file

### Debug Information

Notepad++ v7.7   (32-bit)
Build time : May 19 2019 - 13:08:20
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : ON
Local Conf mode : OFF
OS : Windows 7 (64-bit)
Plugins : DSpellCheck.dll GmodLua.dll HexEditor.dll HTMLTag_unicode.dll LuaScript.dll MarkdownViewerPlusPlus.dll mimeTools.dll NewFileBrowser.dll NppConverter.dll nppcrypt.dll NppExport.dll NppFTP.dll NppQrCode32.dll NppTextFX.dll SpellChecker.dll 

![image](https://user-images.githubusercontent.com/9112662/59099309-6e619a00-892b-11e9-8acf-999902c5ec1a.png)

**Comment by Ekopalypse** [comment]
Does work here as well, seems something went wrong with your installation.
Maybe the config.xml test from your [other issue](https://github.com/notepad-plus-plus/notepad-plus-plus/issues/5758) solves this issue as well.

**Comment by MetaChuh** [comment]
@dvdvideo1234 

we can not reproduce lua highlighting not working on 7.7.

**please test the following, to verify, if a clean notepad++ (without any plugins that could cause this) would work on your system.**

* download the notepad++ 7.7 portable version from [>>> here <<<](https://notepad-plus-plus.org/repository/7.x/7.7/npp.7.7.bin.zip).
(the portable version does not require any installation and runs completely independent and isolated from your installed version. all custom settings, as well as any stuff you might want to try at the portable version, will not modify your installed version)

* extract `npp.7.7.bin.zip` to your desktop.

* **important note:** make sure to close all instances of notepad++ that might be running, before starting the portable version at the next step, to make sure you are using this portable version.

* open the extracted `npp.7.7.bin` folder and start this portable version by double-clicking on `notepad++.exe` inside this folder.
(note: notepad++.exe will just be seen as notepad++, if you have enabled to hide all known file extensions at your explorer settings)

* open any lua file to see whether it highlights as expected.

-----

if it does work on the clean portable version, you will have to find out, whether a plugin is causing this, or perform a clean install:

* make sure you have saved all documents, closed notepad++, and you don't need any specific settings or customisations you have made at your currently installed notepad++.
* uninstall your existing notepad++ from the windows `control panel > programs and features` or the windows `settings > apps > apps & features` list.

* open `%ProgramFiles%` in windows explorer, and delete the folder `Notepad++`, if it still exists from an older 64 bit version.
* open `%ProgramFiles(x86)%` in windows explorer, and delete the folder  `Notepad++`, if it exists from an older 32 bit version.
* open `%AppData%` in windows explorer, and delete the folder `Notepad++`, if it still exists.
* open `%LocalAppData%` in windows explorer, and delete the folder `Don_HO_don.h@free.fr`, if it exists.
* open `%ProgramData%` in windows explorer, and delete the folder `Notepad++`, if it exists.

* download the npp.7.7.Installer.exe from [>>> here <<<](https://notepad-plus-plus.org/repository/7.x/7.7/npp.7.7.Installer.exe) and install it.
make sure you select all your desired options when installing.

best regards.

-----
```
general notes:

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
(no extra account is needed, just use your github account to sign in)
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)
