### ISSUE TITLE
Page scrolling very slow when hyperlinks are in the text

### ISSUE THREAD

**Issue by Bananeweizen** [notepad-plus-plus/notepad-plus-plus#5761]
### Description of the Issue
Page scrolling has delays of up to 2 seconds if the text contains many hyperlinks.

### Steps to Reproduce the Issue
1.  Open a typical continuous integration server log in Notepad++.
2. Scroll down by holding the PageDown key pressed

### Expected Behavior
Scolling should happen with multiple pages per second, independent of the content of the text.

### Actual Behavior
Scrolling _is_ fast as long as the text does not contain hyperlinks.
Scrolling stops for 1 to 2 seconds if a page contains several _different_ hyperlinks (which I often have in my Maven build logs, when the log shows which components where downloaded from the Internet).
The issue cannot be reproduced when writing the same hyperlink 100 times.

### Debug Information

Notepad++ v7.7   (64-bit)
Build time : May 19 2019 - 13:05:35
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10 (64-bit)
Plugins : DSpellCheck.dll mimeTools.dll NppConverter.dll

**Comment by Ekopalypse** [comment]
I create 10000 lines with 
_this http://www.google.de is a link_
and I see the link and scrolling is no problem.
But, could it be that DSpellCheck is set to automatically check for errors, this might explain it.
Could you give it a try without using DSpellCheck plugin?

**Comment by MetaChuh** [comment]
@Bananeweizen 

i can not reproduce a lag when scrolling through a list of 100 **unique, non identical hyperlinks**, with a length of 130 characters or more per url ([#5761 100 url list.txt](https://github.com/notepad-plus-plus/notepad-plus-plus/files/3270222/5761.100.url.list.txt)) on notepad++ 7.7 x86 and x64.
regardless of scrolling with a mouse wheel, cursor down, or page down.

you didn't respond yet, but did you try to disable or remove dspellcheck as suggested by @Ekopalypse ?

if you still see this behaviour with your log, but not with the url list from above, please provide us with a sample log of yours, that causes this.

many thanks and best regards.

-----
```
general notes:

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
(no extra account is needed, just use your github account to sign in)
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)
