### ISSUE TITLE
.BAT start multiple files with n++ Parallel

### ISSUE THREAD

**Issue by effect0** [notepad-plus-plus/notepad-plus-plus#5764]
### Description of the Issue
:: Notepad++ v7.7 May 19 2019
:: i am opening a work envirnonment from BATCH in Windows with .BAT FILE, 
:: multiple files with 6 multiple programms (explorer, pdfviewer, notepad++, ... , 6 programms)
:: even multiple FILES in one NOTEPAD++ window PARALLEL,
:: it saves me a lot of time when starting work.

:: with all my other programs  TRY1 and TRY2 are working... whats wrong with n++ ?
:: its nice if you could get TRY1 and TRY2 working|implemented...

### Steps to Reproduce the Issue
:: TRY2 : works sometimes, and sometimes not, only opening "new 1" . dependencies?
cd /d "C\FILE PATH\"
start "C:\Program Files\Notepad++\notepad++.exe" "a.V" "b.V" "c.V"

:: TRY1 : DOESNT WORK only opening "new 1"
cd /d "C\FILE PATH\"
start "C:\Program Files\Notepad++\notepad++.exe" "a.V"
start "C:\Program Files\Notepad++\notepad++.exe" "b.V"
start "C:\Program Files\Notepad++\notepad++.exe" "c.V"

### Expected Behavior
n++ opens from .bat the files in one window.

**Comment by Ekopalypse** [comment]
Not sure what you are talking about.
If a. b. ... refers to different files then yes, npp does open those files in a single instance if single instance is set in configuration. If it refers to something else, please clarify.
Btw. What is the **Actual behavior**?

**Comment by MetaChuh** [comment]
@effect0 

your batch file has the following errors:

> cd /d "C\FILE PATH"

you are missing the `:`, correct: `"C:\FILE PATH"`

> start "C:\Program Files\Notepad++\notepad++.exe" "a.V" "b.V" "c.V"

the first `start` argv is the title field, not to be used for the executable image name, so you basically start "a.V" as a file association, which will not open the follow up argvs.
correct: `start "Notepad++" "C:\Program Files\Notepad++\notepad++.exe" "1.txt" "2.txt" "3.txt"`

here is a working batch example:

```batch
:: works:
cd /d "H:\public-0918\Coding\Notepad++\npp test files"
start "Notepad++" "C:\Program Files (x86)\Notepad++\notepad++.exe" "1.txt" "2.txt" "3.txt"

:: works:
cd /d "H:\public-0918\Coding\Notepad++\npp test files"
start "Notepad++" "C:\Program Files (x86)\Notepad++\notepad++.exe" "4.txt"
start "Notepad++" "C:\Program Files (x86)\Notepad++\notepad++.exe" "5.txt"
start "Notepad++" "C:\Program Files (x86)\Notepad++\notepad++.exe" "6.txt"
```

screenshot of the result:
<img width="1015" alt="" src="https://user-images.githubusercontent.com/45773305/59192552-158c3e80-8b83-11e9-89bb-b733c59130e7.png">

note: for general usage questions and if you need help with windows batch, please visit our community forum, as this issue tracker is notepad++ source code related only (link at the bottom)

many thanks and best regards.

-----
```
general notes:

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
(no extra account is needed, just use your github account to sign in)
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)
