### ISSUE TITLE
An exception occurred: read access violation. this was nullptr.

### ISSUE THREAD

**Issue by Jorny83** [notepad-plus-plus/notepad-plus-plus#5767]
### Description of the Issue
I downloaded the source code and tried to open with Visual Studio 2019 with C ++ support for Windows XP, the project loads correctly but when I try to run it, I get the error "An exception occurred: read access violation. this was nullptr." on line 251 of the file "Notepad_plus.h" Help how I solve this problem.
### Steps to Reproduce the Issue

1.  When i run the application after load project, without modify the code.

### Debug Information
>	notepad++.exe!Notepad_plus::getCurrentBuffer() Line 251
An exception occurred: read access violation. this was nullptr.

**Comment by efkaxlog** [comment]
I have the exact same problem. Running Visual Studio Community 2017 on Windows 10. 
Target Platform Version 10.0.17134.0 and Platform Toolset Visual Studio 2015 (v140).

**Comment by mag92** [comment]
Same issue here. But I'm on Visual Studio Community 2015 so I had to change target platform and toolset (to v140 instead of v141). 

Line 517 Buffer.cpp
`		Buffer* buffer = _pNotepadPlus->getCurrentBuffer();
`

**Comment by donho** [comment]
Could you try https://github.com/notepad-plus-plus/notepad-plus-plus/archive/v7.7.1.zip to see if it's due to the recent modification ?

**Comment by mag92** [comment]
@donho I tried the version you linked to, on VS19 with v142 toolset and got the same result. 

![image](https://user-images.githubusercontent.com/1712511/64276255-c8342900-cf47-11e9-9ea2-958aaac1ddbf.png)

**Comment by Jorny83** [comment]
> Could you try https://github.com/notepad-plus-plus/notepad-plus-plus/archive/v7.7.1.zip to see if it's due to the recent modification ?


I have downloaded the tablet from the link you suggested, I modified the toolset to v140, but the problem persists.
Is it necessary some previous steps ?, I would appreciate illustrating the steps to achieve it.

![v140xp](https://user-images.githubusercontent.com/45632483/64278412-4c6bb980-cf12-11e9-8935-e11992640d59.PNG)

**Comment by aplocher** [comment]
Hi did anyone ever figure this out?  I've tried in VS2017 and 2019 with no luck

**Comment by monichoza** [comment]
The problem is that the SciLexer.dll file cannot be found when compiling notepad ++. exe, you must compile the SciLexer.dll first and copy it to the folder where the notepad ++. exe is generated.

**Comment by sebastiencozzi** [comment]
> The problem is that the SciLexer.dll file cannot be found when compiling notepad ++. exe, you must compile the SciLexer.dll first and copy it to the folder where the notepad ++. exe is generated.

This error can happen also if your SciLexer.dll and notepad++.exe are not both in 32 or 64 bits.

A small modification like below  (in yellow) in ScintillaEditView.cpp could help future contributor:
![correction_dll](https://user-images.githubusercontent.com/26365866/87173994-d1fc8a80-c2d6-11ea-869b-9add47a8109b.PNG)

**Comment by downthecrop** [comment]
> The problem is that the SciLexer.dll file cannot be found when compiling notepad ++. exe, you must compile the SciLexer.dll first and copy it to the folder where the notepad ++. exe is generated.

Solve my issue thanks!
