### ISSUE TITLE
The Speech plugin can't accurate reading Chinese, NO option for Select TTS engine,Hope to update and fix that

### ISSUE THREAD

**Issue by Leroy-X** [notepad-plus-plus/notepad-plus-plus#577]
the Speech Plugin can't accurate reading Chinese, all Chinese character are read as "yuan yuan yuan yuan...." like garbled code, but English can reading right, I'm sure the system have Chinese TTS in windows 7, and others software can work right, but Speech plugin not work for Chinese :(

and this plugin no choice option for select which tts for speech, If possible, Hope to add this function. just one select option for select TTS.

I have used the notepad++ for three days, and I'm not used it for write cod, just edit for simple text, it's great and amazing, very light and useful, free and powerful, VERY THANKS FOR Notepad++ TEAM, I like this software after I try it, very cool, and I don't want used others software just for reading, I'm very hope for somebody can fix this. and this plugin have long time no update, hope to update again, Very Thanks for this :D

windows 7 SP1 64 bit
notepad ++ 6.8 release
Speech version 0.21 and Source: http://sourceforge.net/projects/npp-plugins/files/SpeechPlugin/SpeechPlugin_0_2_1_src.zip/download

I'm sorry for my bad English, Hope for you can understand :)

**Comment by monkeyfuckeddog** [comment]
I agree with you. This function is really need for every chinese users. All chinese people 1300000000 need this. Also some Editable Options like speed, volume, tone are baddly need. Wow~~~ that will be very cool. I can't wait.

**Comment by Leroy-X** [comment]
If possible, I hope can add one "setting" option for speech plugins, e.g. you can set the volume, speed, tone, and can select different TTS engine for reading, more option and more power:D

**Comment by donho** [comment]
This is an plugin issue andI saw you have posted on community:
https://notepad-plus-plus.org/community/category/5/plugin-development

**Comment by Leroy-X** [comment]
first use this ,and don't know where to post ,so I post twice, sorry for this
