### ISSUE TITLE
Is Taiwan a country?

### ISSUE THREAD

**Issue by Timynore** [notepad-plus-plus/notepad-plus-plus#5770]
![image](https://user-images.githubusercontent.com/6006218/59250162-0b3c7400-8c59-11e9-86cc-1931ddd7a5d1.png)

**Comment by donho** [comment]
Yes, Taiwan is a country.

**Comment by sasumner** [comment]
Is this an "issue" against software? NO.  So please don't create frivolous issues that have to be managed by someone.

**Comment by yzy26353520** [comment]
No. Taiwan is a province which belongs to China
