### ISSUE TITLE
comparing two files when notepad is opened with administrative rights

### ISSUE THREAD

**Issue by ranjan-ranjan** [notepad-plus-plus/notepad-plus-plus#5771]
I have opened Notepad++ using administrative rights and added two files to compare using the inbuilt compare plugin. While comparing the files, the two scrolls are not synchronized.

**Comment by xylographe** [comment]
Should be fixed in [Compare v2.0.0 for Notepad++ 7.7](https://github.com/pnedev/compare-plugin/releases/tag/v2.0.0_npp7.7)

**Comment by ranjan-ranjan** [comment]
yes, its fixed
there should be communication so that all the bugs that are fixed in this released will be available to everyone

**Comment by sasumner** [comment]
For future reference, there is no built-in compare in Notepad++.  If you have issues with plugins, please take them to the appropriate place for issues, in other words: not here.
