### ISSUE TITLE
[BUG] Column mode typing might get garbled characters in non-general encoding

### ISSUE THREAD

**Issue by ahdung** [notepad-plus-plus/notepad-plus-plus#5772]
### Description of the Issue
If encoding is GB2312, column mode typing chinese characters will get error, if encoding is UTF-8, no problem. actually this issue already exists long time, not only this version.

### Steps to Reproduce the Issue
1. make sure current encoding is not utf-8, like gb2312
2. begin column mode typing in some chinese characters. note carets right side must have some words, I mean don't typing at the end of line

### Expected Behavior
type in correct characters

### Actual Behavior
incorrect characters

### Debug Information
Notepad++ v7.5.9   (32-bit)
Build time : Oct 14 2018 - 15:02:52
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : ON
Local Conf mode : OFF
OS : Windows 7 (64-bit), ACTUAL IS: Windows server 2008 R2 simplified chinese with SP1, ANSI = GB2312(CP936)
Plugins : DSpellCheck.dll HexEditor.dll mimeTools.dll NppConverter.dll _CustomizeToolbar.dll NppExport.dll NppTextFX.dll pluginmanager.dll 

![GIF](https://user-images.githubusercontent.com/12094247/59252261-4b522580-8c5e-11e9-9856-73a29f20d9a1.gif)

**Comment by MetaChuh** [comment]
@ahdung 

i'm not able to reproduce this on notepad++ 7.7 as seen at the screenshot below.
gb2312 encoding, column mode, simplified using ms pinyin abc.
(on a real w7 pro x64, no 2k8 for testing available)

<img width="910" alt="" src="https://user-images.githubusercontent.com/45773305/59290387-ba3c7800-8c78-11e9-9a0a-d2f3581b9a3e.png">

if you like, you can try the portable 7.7 version for quick testing, if it works on your 2k8r2:

* download the notepad++ 7.7 portable version from [>>> here <<<](https://notepad-plus-plus.org/repository/7.x/7.7/npp.7.7.bin.zip).
(the portable version does not require any installation and runs completely independent and isolated from your installed version. all custom settings, as well as any stuff you might want to try at the portable version, will not modify your installed version)

* extract `npp.7.7.bin.zip` to your desktop.

* **important note:** make sure to close all instances of notepad++ that might be running, before starting the portable version at the next step, to make sure you are using this portable version.

* open the extracted `npp.7.7.bin` folder and start this portable version by double-clicking on `notepad++.exe` inside this folder.
(note: notepad++.exe will just be seen as notepad++, if you have enabled to hide all known file extensions at your explorer settings)

please also try the same column mode editing on a w10 and/or normal w7 machine using 7.7.

many thanks and best regards.

**Comment by dail8859** [comment]
@ahdung 

> make sure current encoding is not utf-8, like gb2312

Why does your screenshot show ANSI in the bottom right corner?

**Comment by ahdung** [comment]
@MetaChuh Thank you, i tried 7.7, it seems fixed it, everything ok.

**Comment by ahdung** [comment]
@dail8859 Because in win2k8r2 chs version, ANSI = gb2312(cp936)
