### ISSUE TITLE
Spellcheck not working as expected in version 7.7 (bug?)

### ISSUE THREAD

**Issue by B3ginnersMind** [notepad-plus-plus/notepad-plus-plus#5776]
### Description of the Issue

With Notepad++ 7.7 x64 the automatic DSpellCheck feature won't process the whole file. It seems to check only the text in the visible window. It is also possible that everything is checked but only the mistakes in the visible window are marked.

I use Hunspell and the dictionary "German".

Updating the DSpellCheck plugin didn't change this behavior. Downgrading to N++ 7.6.6 fixed the problem for me. I am glad that a downgrade is possible without any problems.

Had this behavior on two different clients with Win10 1809. Installing was done with chocolatey.

### Expected Behavior

If automatic mode is selected, spellcheck should mark the spelling mistakes in the whole file. The corresponding markup should be visible when scrolling up and down.

### Actual Behavior

On clicking "automatic" only the spelling mistakes in the visible window are marked . If one scrolls down, nothing is marked.

**Comment by B3ginnersMind** [comment]
Sorry for the above post. This bug is due to a disruptive change in the N++ API which broke the spell check feature. 

See https://github.com/Predelnik/DSpellCheck/issues/179

But my post might be useful for other users to get the hint of downgrading.

By the way, this is the second time, that DSpellCheck broke due to a N++ update. I recommend to be very careful with updates as long as spell checking is important.

But: Notepad++ is great!

**Comment by sasumner** [comment]
>disruptive change in the N++ API

If you mean the advancement of Scintilla from 3.56 to 4.14 (which is the only "disruptive change" in 7.7 that I can think of), then I say "too bad, but it is called 'growth' of Notepad++" and plugins just have to deal with it (their authors need to update them).  What I don't think should be done is to log issues against Notepad++ (like THIS issue) -- log issues at the appropriate places (not here) for the plugins.

**Comment by B3ginnersMind** [comment]
Yes, it's the advancement of Scintilla. Thanks for your efforts. But I already apologized and closed the issue. One workaround for avoiding such problems is to freeze the N++-Version and update only after a careful research. Users without installed contibuted plugins are not affected. Regards

**Comment by sasumner** [comment]
Certainly no apology was needed. :)

I think perhaps several different things *could* be done, but I also think that the development team has limited time/resources, so the approach is, "core product moves forward at will, plugins will need to follow or get left behind".  Certainly it is *nice* if some advance warning is given when "disruptive" changes are known (to be coming) ahead of time, but the core product is the master!

**Comment by B3ginnersMind** [comment]
Of course I agree that the core product is the master. And the limited time/resource problem is acknowledged, too. Regards
