### ISSUE TITLE
"non-breaking spaces" are invisible even with "Show All Characters"

### ISSUE THREAD

**Issue by daveloyall** [notepad-plus-plus/notepad-plus-plus#5783]
### Description of the Issue
Notepad++ does not render "non-breaking spaces", even when "Show All Characters" mode is active.  Here's a picture of some non-breaking spaces next to some spaces with "Show All Characters" mode turned on.
![image](https://user-images.githubusercontent.com/1524866/59443441-98024180-8dc1-11e9-815f-abdf77ef8f60.png)

### Steps to Reproduce the Issue
1. Somehow get a copy of this character: https://www.fileformat.info/info/unicode/char/00a0/index.htm
2. Insert it into a Notepad++ document.
3. Toggle "Show All Characters" on and off.

### Expected Behavior
Notepad++ should reveal the character. 

### Actual Behavior
It's invisible.  Well, it takes up space..

### Debug Information
Notepad++ v7.7   (64-bit)
Build time : May 19 2019 - 13:05:35
Path : D:\downloads\npp.7.7.bin.minimalist.x64\notepad++.exe
Admin mode : ON
Local Conf mode : ON
OS : Windows 7 (64-bit)
Plugins : none

This is probably related to #827.

**Comment by MetaChuh** [comment]
@daveloyall 

this is the way scintilla renders the no break space (00a0) in whitespace view.
same for all scintilla based editors, like the latest scintilla demo editor [scite 4.1.7](https://www.scintilla.org/wscite417.zip)

while in theory a plugin or scripting language could set the scintilla [character representation](https://www.scintilla.org/ScintillaDoc.html#CharacterRepresentations) to something else, we will currently not integrate this customisation to the notepad++ core.

many thanks and best regards.

**Comment by daveloyall** [comment]
Ok.  I opened https://sourceforge.net/p/scintilla/bugs/2109/.

**Comment by MetaChuh** [comment]
@daveloyal

this is not a bug, this behaviour works as intended by neil.
see https://sourceforge.net/p/scintilla/feature-requests/974/

please also search at the scintilla issue tracker, before filing a feature request or bug issue, to prevent cross project re-bounces of requests, which have unisonous evaluation results from both project's point of views.

many thanks and best regards.

**Comment by daveloyall** [comment]
Oh, I see now, the `character representation` link you provided describes how to make the nbsp gain the same visual appearance as the null byte (inverted text in a rounded rectangle).  Yes, that would work.

And you indicate that a plugin could do this, ok.  And maybe an existing scripting plugin could invoke something like `editor.Representation["\194\160"] = "NBSP"`.

Meanwhile, my team used a different tool to hunt down and remove all the nbsp from our code.  So we're OK for now.

Thank you for Notepad++.  I use it almost every day.  Cheers!

**Comment by alankilborn** [comment]
>Notepad++ does not render "non-breaking spaces",

They will have a visual component with this change: https://github.com/notepad-plus-plus/notepad-plus-plus/commit/aaab190763b720e2eed6495d8508b970d09ad39c

This issue may be CLOSED.
