### ISSUE TITLE
Feature request: pin tab

### ISSUE THREAD

**Issue by scottmckenzie** [notepad-plus-plus/notepad-plus-plus#5786]
I have a problem with tabs in NPP - I usually have too many open!  Some files I have open all the time.  It would be great if NPP had a pin tab feature.  This would work the same way as the major browsers - the pinned tab would shrink in size and always be visible, to the left of all other tabs.

**Comment by sasumner** [comment]
Just a FYI, the Explorer plugin has a "favorites" tab with which allows me to do basically what you are talking about (sure, it's not *exactly* what you describe).

**Comment by tobizviz** [comment]
I've been hoping for this feature for years. I usually have lots of files open and one for notes which tends to get lost amongst the rest. It would be great if I could just pin that tab and have it locked, as OP describes, as in major browsers.

**Comment by Marvinoo** [comment]
Please implement it, I also need that

**Comment by ryehamstrawberry** [comment]
I would also like to see a simple "pin tab" feature implemented, with the same simple functionality as is found in various browsers (i.e. pins remain a permanent fixture until unpinned, cannot be accidentally closed, located in front of all other tabs, etc.).

**Comment by MrShmiTT** [comment]
Thank you for the solution with Explorer plugin, and anyway it's not the same what users want. A more convenient way to keep a few of the most popular tabs in front of the eyes is pinning without any additional bar. It would be much easier and user-friendly, just pin tab on the tabs line (like in Chrome). Thank you in advance.

**Comment by mpatca** [comment]
I have read posts about this feature. So there are several alternative solutions, on the other hand most programs with tabs also have a lock function. Anyway, I am among those who would be very happy to have such a feature.

**Comment by dylanh724** [comment]
The suggestions are workarounds, not solutions: Not looking for third party / extra toolbars. For the same reason Chrome, Firefox and Brave added pinning to browsers, elegant pinning just makes sense and would be intuitive:

1. Right click tab
2. Pin
3. Tab moves to the far-most-left next to other pins
4. If I close all tabs, pins are ignored

There are numerous devs here that have all kinds of tabs open and moving about. To clear clutter, this native pinning would do your users justice for the same reason AAA browsers implemented this, and the same reason you can pin tabs even in Jetbrain IDEs like Rider:

![image](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/8840024/da04b961-3572-4244-a8de-03edf6052fb8)

Everyone is doing it but NP++

**Comment by ryehamstrawberry** [comment]
Amen @dylanh724, well said!

**Comment by IsItSnowingInSpace** [comment]
Upvote, please implement ASAP!

**Comment by carco5a** [comment]
Still surprised this hasn't been implemented. I feel like since we can mark a tab "read-only" that this falls into that same logic. Many times I open files for reference in R-O to avoid accidental edits. Pinning the tab as well would be nice.

**Comment by ryehamstrawberry** [comment]
> ![image](https://private-user-images.githubusercontent.com/8840024/270530574-da04b961-3572-4244-a8de-03edf6052fb8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ0NzkxMjcsIm5iZiI6MTcwNDQ3ODgyNywicGF0aCI6Ii84ODQwMDI0LzI3MDUzMDU3NC1kYTA0Yjk2MS0zNTcyLTQyNDQtYThkZS0wM2VkZjYwNTJmYjgucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDEwNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMDVUMTgyMDI3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NWMyYzZiMDkzMDg3NjJlZGQxYTg3ODZkOTBkZWJiNTU1MGY2NzVmMzYzODU1ZTRiNzVmM2E1NzYyYzcyMDQ5OCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.hf-weQgZQsQKd-WOqUHM3faR9wNrSUQP8WBls7FrUgU)
> 
> Everyone is doing it but NP++

VSCode/Codium enters chat:
![VSCodium_vgsACItGAT](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/110439000/1691d471-db7b-4cbd-8534-99f6e3daaf1f)

**Comment by dylanh724** [comment]
Any consideration for this in 2024?

**Comment by carco5a** [comment]
> Any consideration for this in 2024?

I certainly hope so. One of those small QoL features to align with other tools would be great.

**Comment by ryehamstrawberry** [comment]
Tab pinning must be the most requested issue on this repo, just search for "pin" and you'll find pages worth of user requests ...

If the developer is opposed to implementing this as an inherent feature, would they consider writing a plugin for those of us who would use this?

I think introducing a 4x4 pane mode and tab pinning would elevate NPP above all the other competing text editors.
The absence of these QoL features is really felt after using any of the competing text editors, which I hope to stop using altogether if NPP would graciously add them themselves.

**Comment by mvandersteen** [comment]
Been using Notepad++ for about 8 or 9 years now and must say is the only thing that lets it down.
Its an up vote from me.
SSMS or Visual Studio use this as well and allow you to have pinned tabs on a separate row, which i find is gold.

![image](https://github.com/user-attachments/assets/4cf6600f-1391-4a1c-80e0-5720abc62cfd)

**Comment by Argos1024** [comment]
Well, that is an unexpected and welcomed late night commit!
