### ISSUE TITLE
Bug: 7.5.9 Bad allocation exception after opening text file

### ISSUE THREAD

**Issue by barkov00** [notepad-plus-plus/notepad-plus-plus#5788]
### Description of the Issue

Crash after opening a file with 0xFF character at the end
### Steps to Reproduce the Issue

1. Install NPP 7.5.9
2. Open decrypted.txt (download fron attachments)
3. Look at "Bad allocation exception"

### Actual Behavior

NPP tries to allocate over 500 MBytes of RAM and throws exception

### Debug Information

![version](https://user-images.githubusercontent.com/4291653/59496308-cd7a5e00-8e99-11e9-89aa-d603aa2c21a9.png)
![bug](https://user-images.githubusercontent.com/4291653/59496310-ce12f480-8e99-11e9-91e6-431ea8980c1c.png)
File:
[decrypted.txt](https://github.com/notepad-plus-plus/notepad-plus-plus/files/3289797/decrypted.txt)

**Comment by MetaChuh** [comment]
@barkov00 

i can not reproduce a bad allocation exception, when opening your sample file on notepad++ 7.7 and 7.5.9.

**please test the following, to verify, if a clean, new notepad++ (without any plugins that could cause this) would work on your system.**

* download the notepad++ 7.7 portable version from [>>> here <<<](https://notepad-plus-plus.org/repository/7.x/7.7/npp.7.7.bin.zip).
(the portable version does not require any installation and runs completely independent and isolated from your installed version. all custom settings, as well as any stuff you might want to try at the portable version, will not modify your installed version)

* extract `npp.7.7.bin.zip` to your desktop.

* **important note:** make sure to close all instances of notepad++ that might be running, before starting the portable version at the next step, to make sure you are using this portable version.

* open the extracted `npp.7.7.bin` folder and start this portable version by double-clicking on `notepad++.exe` inside this folder.
(note: notepad++.exe will just be seen as notepad++, if you have enabled to hide all known file extensions at your explorer settings)

* try to open your file on this portable version.

many thanks and best regards.

-----
```
general notes:

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
(no extra account is needed, just use your github account to sign in)
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)
