### ISSUE TITLE
Library Verification Failed

### ISSUE THREAD

**Issue by LainUser** [notepad-plus-plus/notepad-plus-plus#5789]
### Description of the Issue
Version installed V7.6.6 (32 bit) on Win10 (1709). On some machines the and error message is issued on launch relating to this Library Verification check. Uninstall and reinstall seemed to have resolved this but again on some machines the issue reappears after some period of time(not specified but likely weeks). 

### Steps to Reproduce the Issue
1. Launch Notepad++
2. Error occurs immediately 
3. Not consistent across all installations but only on some.
4. Error message: Dialog - Heading "Library Verification Failed". Body of Dialog - "Authentication check failed: signing certificate or hash is not recognised"

### Expected Behaviour
Notepad++ opens

### Actual Behaviour
Notepad++ does not open but displays following message then closes
![Error](https://user-images.githubusercontent.com/51828781/59518389-725a6280-8ebd-11e9-9814-ba48769909f2.jpg)

**Comment by Ekopalypse** [comment]
That basically means, that the SciLexer.dll has been replaced with a different version as expected.
See [here](https://github.com/notepad-plus-plus/notepad-plus-plus/blob/155c93d3b0aacf00247710eb7ab3094143168dd4/PowerEditor/src/ScitillaComponent/ScintillaEditView.cpp#L215).

**Comment by donho** [comment]
Use the installer to install whole package will solve your problem.
