### ISSUE TITLE
Imported custom user language string is too long

### ISSUE THREAD

**Issue by dvdvideo1234** [notepad-plus-plus/notepad-plus-plus#5796]
### Steps to Reproduce the Issue

1.  Import [this as user-language](https://raw.githubusercontent.com/dvdvideo1234/ProgramSettings/master/Notepad%2B%2B/GLua/GLuaPro.xml)
2. `Language` -> `Define your language` 
3. Select Glua PRO
4. `imported string too long, needs to be < max_char(30720)`

### Expected Behavior
The second keyword list to be imported

### Actual Behavior
The second keyword list is not imported

### Debug Information
Notepad++ v7.7   (64-bit)
Build time : May 19 2019 - 13:05:35
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : ON
Local Conf mode : OFF
OS : Windows 7 (64-bit)
Plugins : DSpellCheck.dll MarkdownViewerPlusPlus.dll mimeTools.dll NppConverter.dll NPPJSONViewer.dll NppQrCode64.dll NppRegExTractorPlugin.dll NppTextViz.dll

**Comment by MetaChuh** [comment]
@dvdvideo1234 

please copy `GLuaPro.xml` to `%AppData%\Notepad++\userDefineLangs\` and restart notepad++.

many thanks and best regards.
