### ISSUE TITLE
Markdown highlight in Monokai theme

### ISSUE THREAD

**Issue by da411d** [notepad-plus-plus/notepad-plus-plus#5799]
Markdown highlight in Monokai theme glitch.

### Description of the Issue
Highlights colors for md are incorrect in Monokai theme. 

### Steps to Reproduce the Issue
1. Create md file
2. Switch theme to Monokai

### Expected Behavior
Highlight colors correctly

### Actual Behavior
Highlight colors incorectly

### Debug Information
![image](https://user-images.githubusercontent.com/12462454/59609599-61f5f200-9120-11e9-9529-f835aaaf52e9.png)

**Comment by andrecool-68** [comment]
Open the file "Monokai.hml" ... there are no styles for "* .md" at all!
Notepad ++ has nothing to do with it at all))

**Comment by buenalabs** [comment]
This looks like an issue with the markdown theme that you downloaded from a third party. My suggestion is to find a theme that is designed for, or at least goes well with, Monokai. Notepad++ doesn't currently support Markdown out of the box.

**Comment by ArkadiuszMichalski** [comment]
@sasumner This should be close, `Monokai` included with NPP has no styles for markdown.
