### ISSUE TITLE
Inconsistent visual styles for controls

### ISSUE THREAD

**Issue by milipili** [notepad-plus-plus/notepad-plus-plus#58]
Notepad++ uses the visual styles (to ensure that common controls are displayed in the user's preferred visual style). The main window, the about box or the plugins manager are using them for example. However some other dialogs don't, like the updater proxy dialog and the update dialog.

**Comment by SinghRajenM** [comment]
Updater proxy and update dialogs are part of an another application (gup.exe) which is maintained separately. To handle it, project WinGUp has to be updated.

However, originally WinGUp was made for the need of Notepad++. But later, it was opened for all the windows program by keeping in mind: if it can fit Notepad++, it can fit for any Windows program.

So personally, I feel that it is bit hard to meet UI requirement for all the projects, but not impossible.

**Comment by donho** [comment]
<troll>Diversity is our strength.</troll>
:P
