### ISSUE TITLE
Can't copy formated to Microsoft Word anymore

### ISSUE THREAD

**Issue by EngRenanBW** [notepad-plus-plus/notepad-plus-plus#5801]
### Description of the Issue

The plugin NppExport don't work in notepad++ version 7.7 like it do in version 6.9.2. With the previous one I was able to copy with formating to Microsoft Word 2010.
### Steps to Reproduce the Issue

1. Open Notepadd ++ version 7.7;
2. Write a Matlab code and select Matlab language;
3. Select Plugins>NppExport>Copy RTF to clipboard;
4. Open Microsoft Word 2010;
5. Paste maintaining the original format.

### Expected Behavior

The writen Matlab code appears with the notepad++ formating (eg: the commentaries are green and ifs are blue)
### Actual Behavior

The writen Matlab code appears all in black collor.
### Debug Information

As I said, it was working properly in version 6.9.2. 
Copy to html doesn't work in version 7.7 too.

**Comment by Ekopalypse** [comment]
Is a known issue and [already addressed](https://github.com/chcg/NPP_ExportPlugin/pull/8) but just for information, this is not a npp issue.
