### ISSUE TITLE
Allow extra plugin DLL files to be loaded automatically

### ISSUE THREAD

**Issue by dail8859** [notepad-plus-plus/notepad-plus-plus#5802]
### Description of the Issue
Many plugins come with their own DLL files needed for the plugin to operate correctly. 

Normally [Run-Time Dynamic Linking](https://docs.microsoft.com/en-us/windows/desktop/dlls/using-run-time-dynamic-linking) would be required by the plugin to use local DLL files within the plugin's folder. However, in cases where it is not possible to do Run-Time Dynamic (due to a large number of exported functions, such as PythonScript), the extra DLL files must be located in the same directory as `notepad++.exe` (**note** that the Plugin Admin does not support copying DLL files to the root installation directory).

### Proposed Feature
Enable [Load-Time Dynamic Linking](https://docs.microsoft.com/en-us/windows/desktop/dlls/using-load-time-dynamic-linking) (required DLLs are found and loaded by the OS) when loading plugins. Notepad++ would have to slightly change the way it loads plugins so that any required DLL files are allowed to be loaded from the plugins folder. 

---

CC @ClaudiaFrank @xylographe

**Comment by Ekopalypse** [comment]
I offer my help in testing all the existing plugins supported by plugins admin once a "testable" npp version is available.

**Comment by dail8859** [comment]
@Ekopalypse Thanks for the offer of help!

The code changes are minimal but of course we want to make sure it doesn't break any existing plugins or introduce any new problems. I am wanting to test out the changes with one of my plugins (LuaScript) first and then I'll create a PR.

**Comment by chcg** [comment]
Affected plugins from https://github.com/bruderstein/npp-plugins-x64/blob/master/plugins/plugins_win32.xml ( with to="$NPPDIR$\"): 
- NamedBookmarks http://www.dbaileyconsultancy.co.uk/npp_plugins/namedbookmarks.zip
- Python Script https://github.com/bruderstein/PythonScript/releases/download/v1.3.0/PythonScript_Full_1.3.0.0.zip
- Snip2Code https://www.snip2code.com/Downloads/S2CNotepadppPlugin.zip
- UniversalIndentGUI https://downloads.sourceforge.net/project/universalindent/uigui/UniversalIndentGUI_1.0.2/UniversalIndentGUI_1.0.2_NotepadPPplugin.zip

-

**Comment by dail8859** [comment]
All those would be affected, also any of the current plugins in the pluginlist that come with extra DLLs would also potentially gain benefit from this (because they have to do run-time linking themselves). I know the compare plugin does this and I'm sure many others.

**Comment by xylographe** [comment]
Tested with [this NPP](https://github.com/xylographe/notepad-plus-plus/tree/llex) and [this LuaScript](https://github.com/xylographe/LuaScript/tree/l535).

**Comment by dail8859** [comment]
@xylographe If you have got it working and tested sufficiently you are welcome to create a pull request. I've just been *way* to busy lately to get around to it and create a PR myself. :)

**Comment by Ekopalypse** [comment]
@dail8859 and @xylographe 
So, once the PR is done I can start testing the rest of the plugins offered by plugins admin !?

**Comment by xylographe** [comment]
@dail8859 

I do not have access to a Windows XP host. I posted the two links to the branches with _preliminary_ modifications hoping someone might be willing to test under XP and/or Vista. Obviously, the modified LuaScript will fail to load under XP, but other plug-ins using explicit linking (e.g. ComparePlugin) or no dynamic linking at all are expected to function as usual.

Under Win7SP1 load-time dynamic linking with the modified LuaScript plug-in and two lua modules ([LuaSocket](https://github.com/diegonehab/luasocket) and [LuaSec](https://github.com/brunoos/luasec)) works fine. As one would expect, other plug-ins are not affected — ComparePlugin, DSpellCheck, MultiClipboard, NotepadStarterPlugin, NppSaveAsAdmin, and XMLTools are the ones I use (almost) every day.

**Comment by dail8859** [comment]
> As one would expect, other plug-ins are not affected

@xylographe Correct. The only "loss of functionality" would be *if* a plugin uses the new linking mechanism. It is up to the plugin authors anyways whether they want to support XP or not. So in the end the changes to Notepad++ wouldn't not be responsible if a plugin didn't load under XP anymore.

**Comment by Ekopalypse** [comment]
As promised, I'm going to test the plugins offered by plugin admin.
Depending on some private decisions I'm going to start either tomorrow or on Monday (1st of July).

**Comment by xylographe** [comment]
Sorry, @Ekopalypse. Original commit replaced (i.e. new Artifacts).

**Comment by Ekopalypse** [comment]
No, problem :-D - thanks for your work.

**Comment by donho** [comment]
@dail8859 
>  However, in cases where it is not possible to do Run-Time Dynamic (due to a large number of exported functions, such as PythonScript),

Do you mean those dll needed by python script, and their export functions are call by Python script ?

> the extra DLL files must be located in the same directory as notepad++.exe

I don't get your point: what's the purpose that dlls are beside of notepad++.exe ?

> note that the Plugin Admin does not support copying DLL files to the root installation directory

The files should be copied directly on the right place (ie. plugin's own directory) via the plugins installation. So if the needed extra dlls are in the plugin package, they should be copied into plugins' own directories, but not in the directory where notepad++.exe is.

All your points are not clear to me. Could you elaborate them please?

**Comment by xylographe** [comment]
The problem is the way Windows searches for dynamically linked DLLs ([Dynamic-Link Library Search Order](https://docs.microsoft.com/en-us/windows/win32/dlls/dynamic-link-library-search-order#search-order-for-desktop-applications)).

For example, `LuaScript.dll` is the plug-in DLL, loaded by `Notepad++.exe`, and `lua53.dll` is the auxiliary DLL, required by `LuaScript.dll` and also by user-installed Lua modules. Both DLLs should be located in `\plugins\LuaScript`. But, when Notepad++ calls `LoadLibrary` to load `LuaScript.dll`, Windows will not find the dynamically linked `lua53.dll`, hence the `LoadLibrary` call fails. This happens, because Windows will look in the application directory (which is the location of `Notepad++.exe`), and _not_ in the `LuaScript.dll` directory.

To make Windows search in the `LuaScript.dll` directory, Notepad++ needs to call `LoadLibraryEx` with the `LOAD_LIBRARY_SEARCH_DLL_LOAD_DIR` flag.

**Comment by dail8859** [comment]
@donho 

I see this has been accepted/closed, but just wanted to make sure your questions were answered. (Was busy yesterday with the US holiday). @xylographe explained the situation very well. Was there anything else you had questions regarding or needed more clarification on?
