### ISSUE TITLE
Feature Request: Add the Darcula theme

### ISSUE THREAD

**Issue by Ant0n777** [notepad-plus-plus/notepad-plus-plus#5803]
Add the 'Darcula' theme with the same colors as in the Itellij IDEA.

Itellij IDEA with it dark theme is very popular within developers world. 
There is Github project with that theme for Nodepad++:
https://github.com/gogo2/npp-darcula

![image](https://user-images.githubusercontent.com/15654484/59735271-e335ad80-9222-11e9-9d95-9be15b8a1cb4.png)

**Comment by MetaChuh** [comment]
@Ant0n777 

while darkula is a nice theme, we will not consider shipping it packaged with notepad++.

themes have to be constantly maintained to stay functional throughout newer versions of notepad++, and we already have enough highlighting issues with outdated themes currently shipped together with notepad++.

users who also like this theme, can install it the same way you did, without any need of shipping it directly with the notepad++ core.

many thanks for your understanding and best regards.
