### ISSUE TITLE
Handle PHP code embedded inside a JavaScript string

### ISSUE THREAD

**Issue by ivotheb** [notepad-plus-plus/notepad-plus-plus#5805]
### Description of the Issue

Php code in javascript string not be colored as before
![issue](https://user-images.githubusercontent.com/20459265/59764927-216fb300-929d-11e9-8e16-1f21e5240d19.PNG)

**Comment by Ekopalypse** [comment]
Would you mind checking the upcoming version
https://notepad-plus-plus.org/repository/7.x/771RC/
which addressed this issue to see if you case is solved as well?

**Comment by ivotheb** [comment]
![Cattura](https://user-images.githubusercontent.com/20459265/59768533-d194ea00-92a4-11e9-8076-bd9f0ae4bce9.PNG)
same

**Comment by Ekopalypse** [comment]
okay, found the culprit [here](https://github.com/notepad-plus-plus/notepad-plus-plus/blob/master/scintilla/lexers/LexHTML.cxx#L1216), previously this was [!isPHPStringState](https://github.com/notepad-plus-plus/notepad-plus-plus/blob/c0cd924c1ebb9dc0daccf4f28f5c305ac65a2b4a/scintilla/lexers/LexHTML.cxx#L901). Reverting it would return coloring BUT this was [introduced on purpose](https://sourceforge.net/p/scintilla/bugs/767/#a1ed), so ... (!?)

**Comment by ivotheb** [comment]
Great, php work in this case of code no need to be gray!!

Il giorno mer 19 giu 2019 alle 20:18 Ekopalypse <notifications@github.com>
ha scritto:

**Comment by ivotheb** [comment]
Great find, in this case php work, better have a coloring or
<html>
	<script>
		a: ' LOOK LIKE THIS 7.7'
	</script>
</html>

**Comment by abydahana** [comment]
Hello there!

Is someone have to solve this problem? I updated to newest Notepad++ (v7.8.4) 64bit but the problem's still persist.

**Comment by belutz** [comment]
> Hello there!
> 
> Is someone have to solve this problem? I updated to newest Notepad++ (v7.8.4) 64bit but the problem's still persist.

and now 2021 and new update v7.91 still have this problem

**Comment by ArkadiuszMichalski** [comment]
https://github.com/ScintillaOrg/lexilla/commit/622d3b726fd85b1b09ff5f95bb5f3027d3107b12

**Comment by ArkadiuszMichalski** [comment]
Fixed by https://github.com/notepad-plus-plus/notepad-plus-plus/commit/a61b03ea8887e21c6e1b7374068962f635b79b80.

**Comment by rimrul** [comment]
> > Fixed by [a61b03e](https://github.com/notepad-plus-plus/notepad-plus-plus/commit/a61b03ea8887e21c6e1b7374068962f635b79b80).
> 
> No, you don't. I updated to recent updates and I didn't get changes:

I don't think a61b03e is in any published release yet.

**Comment by abydahana** [comment]
> > > Fixed by [a61b03e](https://github.com/notepad-plus-plus/notepad-plus-plus/commit/a61b03ea8887e21c6e1b7374068962f635b79b80).
> > 
> > 
> > No, you don't. I updated to recent updates and I didn't get changes:
> 
> I don't think [a61b03e](https://github.com/notepad-plus-plus/notepad-plus-plus/commit/a61b03ea8887e21c6e1b7374068962f635b79b80) is in any published release yet.

Oh sorry. So this commit will implemented for future update, right?

**Comment by rimrul** [comment]
Yes, the next release should have that commit.
