### ISSUE TITLE
AndroidLogger

### ISSUE THREAD

**Issue by ShengjieGeng** [notepad-plus-plus/notepad-plus-plus#5812]
![image](https://user-images.githubusercontent.com/18364968/59900705-9e309780-942b-11e9-9a1a-ab10a2c72eb2.png)
something bother me, Version 7.7.1 ,64bit,no AndroidLogger plugin.  thanks anyway.

**Comment by MetaChuh** [comment]
@ShengjieGeng 

AndroidLogger is currently only available for 32 bit as a manual install.
please contact the plugin developer to compile AndroidLogger plugin for 64 bit and to submit it to the plugins admin list, if he likes to do so.

many thanks and best regards.
