### ISSUE TITLE
Do something about legacy plugin folder structures?

### ISSUE THREAD

**Issue by nmlgc** [notepad-plus-plus/notepad-plus-plus#5814]
### Description of the Issue

As of 7e555b67fca6347c1e09e491c7465f76c6d8ae6c, shipped in Notepad++ v7.6, plugin DLLs must be put into a separate subdirectory inside `plugins\`, and the old way of placing DLLs right into `plugins\` is no longer supported. However, old installations still might have some private plugins there, which never were part of the public registry.

### Steps to Reproduce the Issue

1. Place a plugin DLL right into `plugins\`, without creating a separate subdirectory for it, as it was the default for Notepad++ versions prior to v7.6.

### Expected Behavior

Something like a MessageBox, telling me that this way of placing plugin DLLs has been removed in v7.6 and that subdirectories are now required, or any other kind of error message. I'd go ahead and implement that if that's OK?

### Actual Behavior

The plugin is ignored without any user feedback. (Interestingly, `PluginsManager::loadPluginsV2(const TCHAR* dir)` currently even interprets regular, existing, non-directory files as directories, and then tries to load `plugins\plugin.dll\plugin.dll.dll`.)

**Comment by ArkadiuszMichalski** [comment]
It's been a while since this folder path change, @donho do you planning any other changes here, or this bug can be closed?

**Comment by donho** [comment]
Sorry for the inconvenience of plugin not loading.
No message for the plugin loading error is intentional for the fluent UX. 
The forum is available and User Manual site is updated for such information.
OTOH situation should happen very rarely since Plugin Admin deploys plugins correctely.
So no dialog will be implemented for this purpose.
