### ISSUE TITLE
Trailing indent indicators continue to following code blocks even if there is no indent

### ISSUE THREAD

**Issue by zefaxet** [notepad-plus-plus/notepad-plus-plus#5815]
When indentation is more than one level deep, the vertical dotted indentation markers appear. This is nice, but it does not accurately reflect the actual indentation.

This issue is of particular interest when using python, but it is probably valid for other language with syntactical whitespace like YAML perhaps.

Consider the following python snippet, for example,
```
if example:
	if nest:
		do_stuff()
#
# The indents are removed here and there are two newlines
if example2:
	if nest:
		do_stuff()
#
# same here, two newlines then EOF, no actual indent
```
The result looks like:
![image](https://user-images.githubusercontent.com/35270292/59945067-0d0df080-942c-11e9-9675-f208bba10e34.png)

As you can see in the image, even though there isn't actually any indentation, the vertical indicator remains until the next line of code or EOF.

As much as I hate using VSCode, I believe they did it right:
![image](https://user-images.githubusercontent.com/35270292/59944732-28c4c700-942b-11e9-8656-c8c0eae0d2f5.png)

I personally have admittedly odd spacing habits, but the way indentation indicators inexorably trail blocks of code makes reading larger files a bit more difficult, and gets ~~exponentially, in my opinion,~~ more difficult with each level of indentation a block of code contains.

**Comment by sasumner** [comment]
Interesting. I've never noticed that type of thing before and I do 97% of my work in Python.  Thanks, NOW it is all I'll see.  I can't "unsee" it.  Ok, I'm joking, it has never before bothered me and won't bother me in the future.  :)

However, this is going to be a Scintilla issue, not a Notepad++ issue.  Meaning, if Scintilla doesn't have a provision for changing it, Notepad++ can't.  Probably best to open a Scintilla issue (if one isn't already open).

**Comment by zufuliu** [comment]
Use SC_IV_LOOKFORWARD
https://www.scintilla.org/ScintillaDoc.html#SCI_SETINDENTATIONGUIDES

**Comment by zufuliu** [comment]
isFoldIndentationBased() added by PR #1898 can be used to fix this.

**Comment by sasumner** [comment]
Thanks to @zufuliu 's comment about "look forward", I added this to my Pythonscript startup script and now I always have the "desired" behavior.  Suggest same as good workaround for the original poster.

`editor.setIndentationGuides(INDENTVIEW.LOOKFORWARD)`

**Comment by dinkumoil** [comment]
I wrote a plugin that that can be used to configure indentation guide lines style. Its name is _ExtSettings_. You can download it [>>> here <<<](https://sourceforge.net/projects/extsettings/). It will also be available soon via _PluginsAdmin_.

Under `(group box) Editor -> Indentation guide style` select `Python style`. That activates `SC_IV_LOOKFORWARD` indentation guide lines style.
