### ISSUE TITLE
Change tabulation size crash

### ISSUE THREAD

**Issue by SuperAntoine** [notepad-plus-plus/notepad-plus-plus#5816]
### Description of the Issue

I'm trying to change the tabulation size for javascript from 4 to 2 but it crashes when I hit enter.
### Steps to Reproduce the Issue

1. Go to preferences -> language
2.  Change javascript tabulation size to 2
3.  Hit enter

### Expected Behavior

The tabluation size changes.
### Actual Behavior

It crashes

**Comment by SinghRajenM** [comment]
I'm unable to reproduce. Please paste 'debug info' (it can be found "Menu-> ? -> Debug Info").

If you are not using latest npp, please upgrade your npp version with V7.7.1 and share the result. Thank you!

**Comment by SuperAntoine** [comment]
Last version, I only have the bug on one of my computers.
Debug infos :
Notepad++ v7.7.1   (64-bit)
Build time : Jun 16 2019 - 21:24:47
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10 (64-bit)
Plugins : DSpellCheck.dll mimeTools.dll NppConverter.dll

**Comment by Ekopalypse** [comment]
What if you run npp without using plugins? Temporarily rename plugin directory or start npp with
-noPlugin switch

**Comment by ArkadiuszMichalski** [comment]
@SuperAntoine can you check if problem still exist? Please download .zip or .7z folder http://download.notepad-plus-plus.org/repository/7.x/7.9.RC/, unpack to some folder (not Program files), run (as portable, just run `notepad++.exe`, but close all other notepad++ instance if you have any open) and check once again.
