### ISSUE TITLE
Find only finds forwards and ignores setting of find backwards

### ISSUE THREAD

**Issue by MatthewDwyer** [notepad-plus-plus/notepad-plus-plus#5819]
### Description of the Issue
Find no longer works backwards.  Only forwards.

### Steps to Reproduce the Issue
Select some search text and tick the box to find in backwards direction then click next. 

### Expected Behavior
Editor moves to a previous line in the text.

### Actual Behavior
Editor stops at a line further down the text.  Repeating the find keeps going down not up.

### Debug Information
Using version 7.7 on Windows 10 64bit but Notepad++ is 32bit version.

**Comment by sasumner** [comment]
The backward direction checkbox works fine for me for controlling the direction of the search.  Notepad++ 7.7.1 32-bit on Windows 10 64-bit.

**Comment by sasumner** [comment]
Closing due to lack of any follow-up information from issue creator.
