### ISSUE TITLE
find in files does not find nor display Umlauts

### ISSUE THREAD

**Issue by ungesundes-halbwissen** [notepad-plus-plus/notepad-plus-plus#5825]
### Description of the Issue

I upgraded to 7.7.1 from 7.6.6 and noticed, that "find in files" did not find words containing Umlauts anymore. The files, encoded in ANSI, remained unchanged. When searching for "Gr" (instead of "Grüße") the instances were found but the Umlaut characters were displayed as empty, rectangular box in the "found results" box at the bottom.
Whatsmore: opening a file, adding a blank and saving it again made the Umlauts in this file search and displayable. (I have some 900 textfiles I work on for a project, all encoded the same way and only the most recent ones displayed the Umlaut characters ok, all older files did not.)
Please note: OPENING a file with a mistyped Umlaut in the result window in the editor itself displays all characters fine.

Uninstalling 7.7.1 and re-installing 7.6.6. stopped this erratic behaviour again: all files (including the most recent ones) were searchable for Umlauts and displayed them ok in the results window.

**Comment by ungesundes-halbwissen** [comment]
Elaborating on the issue a bit more...

Prerequisites:
- running Windows 10, 64bit, Build 1803
- testing on Notepad++ 7.6.6, 64bit and 7.7.1, 64bit

Procedures:
- the main working directory I use to search in files contains +700 ANSI coded plain textfiles
- all files remained unchanged during the searches
- I have been working on 5 files since upgrading to 7.7.1 before noticing this behaviour

Searching for "Gr" (as in Grüße):
1. Version 7.6.6 returns 2184 Hits in 254 files and displays all Umlauts ok (see Screenshot 766-gr.png)
2. Version 7.7.1 returns 2184 Hits in 254 files but displays all Umlauts as retangular boxes (see Screenshot 771-gr.png)

Searching for "ü" (Umlaut for "ue"):
1. Version 7.6.6 returns 40998 Hits in 260 files and displays all Umlauts ok (see Screenshot 766.png)
2. Version 7.7.1 returns 80 Hits in 5 files, displays all Umlauts ok but only for files that have been modified using 7.7.1 before (see Screenshot 771.png)

Sidenote: Umlauts in files modified with 7.7.1 display ok in 7.6.6. as well AND vice versa. It is only the results window that does not work. Also searching for Umlauts in 7.7.1 does not work for "old" files.

As it is now, I would need to open all existing files and force a save in 7.7.1 to make them searchable.

If I can help you with any more details or if I didn't manage to make the problem clear, please do not hesitate to ask. I will be happy to help.

![771](https://user-images.githubusercontent.com/20168451/60239611-98fd9d80-98ae-11e9-90c7-a92097c74e66.png)
![766](https://user-images.githubusercontent.com/20168451/60239612-99963400-98ae-11e9-8ad6-627efa27ea55.png)
![771-gr](https://user-images.githubusercontent.com/20168451/60239613-99963400-98ae-11e9-85d6-d8e68bef64f6.png)
![766-gr](https://user-images.githubusercontent.com/20168451/60239614-99963400-98ae-11e9-86be-bf11a60b3ea9.png)

**Comment by ungesundes-halbwissen** [comment]
As this is a MASSIVE "game-breaking" problem for international users: Can anyone confirm this behavior? (Sorry, I'm a bit desperate)

**Comment by Ekopalypse** [comment]
Maybe related to #5830

**Comment by ungesundes-halbwissen** [comment]
As this bug was introduced after upgrading Scintilla from 3.56 to 4.14 and a similiar sounding bug was fixed in Scintilla 4.15 I just tested N++ 7.8.2 (with underlying Scintilla version 4.20) just to make sure.

Sadly, the bug still remains as described above.

**Comment by sasumner** [comment]
@ungesundes-halbwissen said:

>a similiar sounding bug was fixed in Scintilla 4.15

Do you have a link to that you can provide?

**Comment by ungesundes-halbwissen** [comment]
@sasumner I'm not entirely sure anymore, but I'm quite certain it was this one: https://github.com/notepad-plus-plus/notepad-plus-plus/issues/5671

**Comment by donho** [comment]
> As this bug was introduced after upgrading Scintilla from 3.56 to 4.14 and a similiar sounding bug was fixed in Scintilla 4.15 I just tested N++ 7.8.2 (with underlying Scintilla version 4.20) just to make sure.

Tested, I confirm this bug is due to upgrading Scintilla from 3.56 to 4.14.
