### ISSUE TITLE
Notepad++ crashing on open of INI files

### ISSUE THREAD

**Issue by pcmacpherson** [notepad-plus-plus/notepad-plus-plus#5826]
### Description of the Issue
Program is crashing when I try to open .INI files.  Any other file seems to be fine.

### Steps to Reproduce the Issue

1. Open NP++
2. File > Open
3. Select an .INI
4. Crash

** Also fails when .ini is set to default to NP++ and you double click to open 

### Expected Behavior
File to open

### Actual Behavior
Program crashes, cant recover after 3 trys

### Other 
Works fine on 7.6.6 install.  7.7+ versions are failing.  Uninstalled and reinstalled multiple times and seems to be 7.7.

**Comment by SinghRajenM** [comment]
I'm unable to reproduce. Do you have multiple npp versions in your system (e.g. one portable and one 32/64 bit installed version).

Also please paste 'debug info' (it can be found "Menu-> ? -> Debug Info").

**Comment by donho** [comment]
Please provide Debug Info then reopen this issue.
