### ISSUE TITLE
Add "No to all" option on close dialogue

### ISSUE THREAD

**Issue by willygeerts** [notepad-plus-plus/notepad-plus-plus#5835]
### Description of the Issue
When using Notepad++ as a scrapbook, creating a lot of tabs to work in, I don't want to save those tabs when I close Notepad++.
Having to click No on every question per tab 'do you want to save?' is illogical.
I know that the session behaviour remembers all those tabs, but I do not want to have those tabs, they are just scrapbooks.

### Steps to Reproduce the Issue
1. Disable the session saving behaviour
2. Create 20+ tabs with text you DO NOT want to keep (scrapbook)
3. Close Notepad++

### Expected Behavior
I would like a 'No to All' when closing Notepad++ on more than 1 tab to answer the question 'Save?'.

### Actual Behavior
I have to click on a No per tab.

**Comment by sasumner** [comment]
This is a long standing issue.  For myself, I just hold down the N key. :)

**Comment by Xiad32** [comment]
I would double that.

**Comment by donho** [comment]
Hey guys, here is the binary with implemented feature. Please confirm me it's what you want:
https://notepad-plus-plus.org/temp/npp32.saveYesNoToAll.zip

**Comment by willygeerts** [comment]
Tested, seems to work fine!
Exactly what I want.

**Comment by willygeerts** [comment]
CASE 1 : 1 file open (changed), close application, dialog box
Save? 'Yes' works, 'No' works, 'Cancel' works, 'Yes to All' works, 'No to All' works.

CASE 2 : multiple fiels open (changed), close application, dialog box
Save? 'Yes' works, 'No' works, 'Cancel' works, 'Yes to All' works, 'No to All' works.

CASE 3 : 1 file open (new), close application, dialog box
Save? 'Yes' works (asks for filename), 'No' works, 'Cancel' works, 'Yes to All' works (asks for filename), 'No to All' works.

CASE 4 : multiple files open (new), close application, dialog box
Save? 'Yes' works (asks for filenames), 'No' works, 'Cancel' works, 'Yes to All' works (asks all filenames one by one), 'No to All' works.

**Comment by Dypsis** [comment]
> Hey guys, here is the binary with implemented feature. Please confirm me it's what you want:
> https://notepad-plus-plus.org/temp/npp32.saveYesNoToAll.zip

The zip file is no longer available.
I would also like "No To All".

AkelPad is where I first noticed "No To All". Once you've had it, it's hard to live without.

**Comment by sasumner** [comment]
@Dypsis This is already implemented in Notepad++ 7.8.

**Comment by Dypsis** [comment]
Ah, it's in an RC.
Thank you for your reply, sasumner. :)
