### ISSUE TITLE
Save loop with XML Tools plugin

### ISSUE THREAD

**Issue by Gido73** [notepad-plus-plus/notepad-plus-plus#5836]
### Description of the Issue
When the encoding of an xml file does not match the encoding set in the first line, and you try to save the file using Save As..., the XML Tools plugin creates a save loop.

### Steps to Reproduce the Issue
[Test.zip](https://github.com/notepad-plus-plus/notepad-plus-plus/files/3329751/Test.zip)
1. Open an xml file with encoding set to UTF-8 (see Notepad++ menu Encoding), but having encoding="utf-16" in the xml prolog of the file.
2. File > Save As...
3. Now there is a loop. If you click Cancel the Save As Dialog will come back with the Save As Dialog. If you click Save then there is an error message ("XML Parsing error at line 1: Document labelled UTF-16 but has UTF-8 content"), and then the Save As Dialog is show again.

Note: File > Save only gives the error message. File > Save As... gives the error message and then gets into a save loop.

### Expected Behavior
Cancel should quit the loop. Now the only solution is to kill the Notepad++ process using Task Manager. Save should give the error message and then hide the Save Dialog.

### Actual Behavior
Both Cancel and Save lead back to the Save Dialog.

### Debug Information
Notepad++ v7.7   (64-bit)
Build time : May 19 2019 - 13:05:35
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10 (64-bit)
Plugins : mimeTools.dll NppConverter.dll XMLTools.dll 

### Test File
Attached a zip file with an xml file to reproduce the issue.

**Comment by sasumner** [comment]
Who's to blame here? N++ or the XML Tools plugin?

**Comment by Gido73** [comment]
Hi sasumner,

I just removed all plugins and the issue still exists, so it must be in Notepad++. 

I also did a new test: I tried to save it as a regular text file (Language > Normal Text) but even then there is a save loop. Very strange. Please let me know if I can assist you in any way,

**Comment by Ekopalypse** [comment]
@Gido73 - I only get the message when using xml tools plugin, NOT when using npp without this plugin.
**BUT** in both cases I'm able to save the file. Might it be that you have an outdated xml tools version?

**Comment by sasumner** [comment]
> I only get the message when using xml tools plugin, NOT when using npp without this plugin

In light of that, perhaps closure of this and take it to the XML Tools plugin issues list?

**Comment by ArkadiuszMichalski** [comment]
I can't reproduce this in Notepad++ 8.1.2 (without plugins). If you still have this error with XML plugin please report it in the appropriate place: https://github.com/morbac/xmltools.
