### ISSUE TITLE
IPv4 CIDR sort 'broken' by npp 7.7.1 update

### ISSUE THREAD

**Issue by piranpiran** [notepad-plus-plus/notepad-plus-plus#5839]
### Description of the Issue
7.7.1 breaks Edit > Line Operations > Sort Lines As Integers Ascending for CIDR IPv4

### Steps to Reproduce the Issue

1. Sort a raw ASN data listing.

### Expected Behavior
All NPP versions prior to 7.7.1 sorted the multiple lines of IPv4 CIDR elements perfectly and blindingly quickly.

### Actual Behavior
I think the 7.7.1 sorting is only happening for the first iteration of the decimal dot in each line and ignores the remaining valid dots within each octet throughout the multiple lines.

### Debug Information
Notepad++ v7.7.1   (64-bit)
Build time : Jun 16 2019 - 21:24:47
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10 (64-bit)
Plugins : DSpellCheck.dll Explorer.dll mimeTools.dll NppConverter.dll 

Maybe I was inappropriately utilising an apparently successful sorting process but using a prior bug. After the 7.7.1 update the IPv4 CIDR sort then no longer worked in the same way. Hard to tell:-)

**Comment by SinghRajenM** [comment]
@piranpiran, I think you need to re-look into this again, there are four different options available…

    sort with choreographically
    Sort with integer
    Sort with decimal (,)
    Sort with decimal (.)

In your case may be 1st option is more suitable.

**Comment by piranpiran** [comment]
Am I actually allowed to say anything without some timeout dragon cutting in...?

**Comment by piranpiran** [comment]
Apparently so. Only the Sort With Integer option delivers the octets out of the morass of comments and other data. Even running the Sort With Decimal option that you suggest does not properly sort - as you can see by the provided output on the forum. As Alan points out it still doesn't do the job properly.

**Comment by piranpiran** [comment]
As requested... Link to forum thread
<https://notepad-plus-plus.org/community/topic/17875/7-7-1-breaks-edit-line-operations-sort-lines-as-integers-ascending-for-cidr-ipv4/8>

**Comment by piranpiran** [comment]
[ for example 205.251.196.0/22 ]
Do you need to test for or escape the '/' in this area?

	bool considerStringEmpty(const generic_string& input)
	{
		// String has something else than just whitespace.
		return input.find_first_not_of(TEXT(" \t\r\n")) == std::string::npos;
	}

**Comment by piranpiran** [comment]
[ WORKAROUND workflow :: 7.7.1 ]

1) Highlight/Select dataset as previously done in nnp versions prior to 7.7.1
Edit > Line Operations > Sort Lines As Integers Ascending
(resulting CIDR elements' sort order -> slightly weird)

2) Highlight/Select *ONLY* the required CIDR lines (they appear topmost)
Edit > Line Operations > Sort Lines Lexicographically Ascending
(resulting CIDR elements' sort order -> now correct)

**Comment by sasumner** [comment]
@AngryGamer I thought the way it works is an issue has to be "Accepted" before a (non-DonHo) PR can be done on it?  (Well, technically you can do a PR anytime, but without an issue being accepted it could be a complete waste of your time).  @MetaChuh, comment on policy regarding this?

As to the issue, I'm lost.  We are talking about an "integer" sort, and by that I presume the way it works is the lines are sorted according to an integer at the beginning of the selected lines (or starting at the column of a column-caret/block).  The first non-integer, specific: 0123456789, past this point on a line terminates the sort key.

Why is something that never should have worked a certain way in the first place called a regression?

Can't the desired behavior be relegated to a scripting plugin?

**Comment by AngryGamer** [comment]
@sasumner This is a regression no matter how you look at it. The behavior in v7.7.1 is inconsistent. The old behavior is exhibited on strings <18 characters in length and the new behavior is exhibited on >18 character strings. Also, I relied on the old behavior for similar reasons as @piranpiran and this is an undesired behavior change.

**Comment by sasumner** [comment]
@AngryGamer Can you elaborate on this?: "The old behavior is exhibited on <18 string lengths and the new behavior is exhibited on >18 string lengths."

If there is a wide-enough need to sort octets in IP addresses (in core Notepad++), shouldn't it be given its own menu item, and not rely on some "hidden" feature of another type of sort?

**Comment by piranpiran** [comment]
@AngryGamer I experienced no crashes despite long term intensive daily use. The causal fix citing 20 digit numbers seems flawed making <>18 moot?

@sasumner I seem to have made a feature of the pre-7.7.1 behaviour. npp could do with a dedicated CIDR sort option - accidental or otherwise:-)

Had to slay another dragon (in my own house) as my own server had automatically implemented a blackhole (for unusual activity) - now removed - and thanks for the 'pull'.

**Comment by AngryGamer** [comment]
@sasumner I've updated [PR#5555](https://github.com/notepad-plus-plus/notepad-plus-plus/pull/5555) with more information.

**Comment by AngryGamer** [comment]
@sasumner I've updated [PR#5843](https://github.com/notepad-plus-plus/notepad-plus-plus/pull/5843) with more information.

**Comment by AngryGamer** [comment]
@sasumner The issue isn't exactly about "octets in IP addresses". I consider the old behavior much more useful. Let me give you an example. In any case, the current behavior is **completely broken** because it's inconsistent depending on line lengths.

Example of old behavior being useful:
```
13165@5009#1
13165@1256#
13165@8765#
13165@5009#2
```

Sorted
```
13165@5009#1
13165@1256#
13165@8765#
13165@5009#2
```
