### ISSUE TITLE
Close button on internal windows is too far right

### ISSUE THREAD

**Issue by chrisB28** [notepad-plus-plus/notepad-plus-plus#5847]
### Description of the Issue
As above.

### Steps to Reproduce the Issue

1. Open Find Window
>

### Debug Information

Notepad++ v7.7   (32-bit)
Build time : May 19 2019 - 13:08:20
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : ON
Local Conf mode : OFF
OS : Windows 10 (64-bit)
Plugins : ComparePlugin.dll mimeTools.dll NppConverter.dll NppExport.dll 

![findclose](https://user-images.githubusercontent.com/6062601/60276396-717cf400-98f3-11e9-913d-3d03dbc8ee9d.png)

**Comment by chrisB28** [comment]
Update: it's in every internal window

**Comment by sasumner** [comment]
The Find window is especially egregious !!  Because it is different than the other internal windows with Close buttons:  It has more empty space at the top:

![image](https://user-images.githubusercontent.com/30118311/60276990-b04a8400-98ca-11e9-8798-7038935507bc.png)

This needs to be fixed ASAP.

**Comment by ozone10** [comment]
@sasumner 
Find window has style `WS_THICKFRAME` style which allow resizing, but will make titlebar bigger.

**Comment by alankilborn** [comment]
Tested in N++ 8.4.4 (current version as of this writing) and could not repro.

Placement seems ok now for the window:

![image](https://user-images.githubusercontent.com/77065706/182947854-b2d36f06-fd0d-439a-816c-85c553c600f6.png)

Recommend CLOSURE of this item.
