### ISSUE TITLE
Suddenly clear all tab when next start

### ISSUE THREAD

**Issue by LetMeDecay** [notepad-plus-plus/notepad-plus-plus#5850]
Already enabled save session and backup
Win10 1903, don't have any cleaning software
It just clears all tab, but file still in the backup folder

**Comment by Ekopalypse** [comment]
This is a known issue when you have configured npp to be used as an external editor for another program.
Is this your case as well?

**Comment by DkWyatt** [comment]
yep, I set it as the editor for 7z, but hardly using it.
In this case, last time I open it by shortcut

**Comment by kaiof** [comment]
Could this be related to #5831 (which I opened), i.e., could the fix be to track a master status on whether or not the session should be wiped?

**Comment by Paebbels** [comment]
Maybe related to #4311

**Comment by donho** [comment]
Fix by https://github.com/notepad-plus-plus/notepad-plus-plus/commit/6000f3bb21a42a4d28d068617e0dc642ef739b26
