### ISSUE TITLE
Function list Javascript not working 7.5.4

### ISSUE THREAD

**Issue by Am-per-Sand** [notepad-plus-plus/notepad-plus-plus#5858]
Despite #4697, #3984 and others similar function list for a Javascript function in *.js is still blank

The parser in `appdata/Notepad++/Roaming` is the same as in the programme folder:

```
			<parser
				displayName="JavaScript"
				id         ="javascript_function"
				commentExpr="(?s:/\*.*?\*/)|(?m-s://.*?$)"
			>
				<function
					mainExpr="((^|\s+|[;\}\.])([A-Za-z_$][\w$]*\.)*[A-Za-z_$][\w$]*\s*[=:]|^|[\s;\}]+)\s*function(\s+[A-Za-z_$][\w$]*)?\s*\([^\)\(]*\)[\n\s]*\{"
				>
					<functionName>
						<nameExpr expr="[A-Za-z_$][\w$]*\s*[=:]|[A-Za-z_$][\w$]*\s*\(" />
						<nameExpr expr="[A-Za-z_$][\w$]*" />
					</functionName>
					<className>
						<nameExpr expr="([A-Za-z_$][\w$]*\.)*[A-Za-z_$][\w$]*\." />
						<nameExpr expr="([A-Za-z_$][\w$]*\.)*[A-Za-z_$][\w$]*" />
					</className>
				</function>
			</parser>
```

I appreciate anyone submitting correct parsing expressions if it is still a problem :anguished:

**Comment by aaafgcfg** [comment]
on npp6.4.5 it was working, on npp7.7.1 it is not working

**Comment by aaafgcfg** [comment]
i set syntax c++ and list of function working for javascript code.
sorry for my good english again

**Comment by ArkadiuszMichalski** [comment]
@aaafgcfg do you still have this problem in latest Notepad++ version?

**Comment by donho** [comment]
Outdated.
