### ISSUE TITLE
Ctrl + A not working inside search window (Ubuntu)

### ISSUE THREAD

**Issue by erikdemarco** [notepad-plus-plus/notepad-plus-plus#5859]
1. open search window (Ctrl + F)
2. then type any text inside 'Find what' field.
3. Try select that text using Ctrl + A. (its impossible)

**Comment by sasumner** [comment]
Works fine for me in latest version as of this writing, 7.7.1.  We can't tell what version you are using because you didn't follow directions and use the issue-reporting template.

**Comment by dail8859** [comment]
If you still have the issue, please reopen with more details.
