### ISSUE TITLE
Undo action for auto-inserted characters

### ISSUE THREAD

**Issue by dail8859** [notepad-plus-plus/notepad-plus-plus#586]
When characters are inserted due to the auto-insert feature, undoing the action causes the inserted text, **and the text that triggered it** to also get removed. I'm proposing the behavior should be similar to how MSVC handles it. For example in MSVC, typing a double quote inserts the closing double quote, and undoing the action only removes the second double quote.

This is also very obvious when auto-inserting the tags in HTML or XML. Typing `<temp>` auto inserts `</temp>`, and undoing the action removes both the opening and closing tag.

**Comment by aaaxx** [comment]
+1

**Comment by donho** [comment]
Just checked some text editor (Atom and Sublime), this behaviour  (undo remove all) is the same in these editors. 
@milipili How is it in vim?

**Comment by donho** [comment]
I think we keep this behaviour since it's a standard behaviour to me.
