### ISSUE TITLE
Double Click in Windows opens the wrong file 

### ISSUE THREAD

**Issue by sydnet** [notepad-plus-plus/notepad-plus-plus#5861]
In Windows Explorer I have a folder with two files in a new folder:

new 2.txt     (this has one space in the filename)
new  2.txt    (this has two spaces in the filename)

When I double-click on the filename with two spaces, Notepad++ (v7.7.1) loads the one with the single space in the filename.

My system:  Win8.1, Notepad++ 7.7.1, Disk is an SSD with NTFS filesystem.
My test folder is in the Documents folder.

I was comparing these two text files and was about to delete one of them because they appear to contain the same contents, however I noticed that one was 1kB and the other 5kB so I looked into it more and found this bug.

**Comment by CookiePLMonster** [comment]
Couldn't reproduce. Could this be a wrong file association registration again, where path is not quoted?

**Comment by sydnet** [comment]
I have been doing some tests.
If I right-click click "OpenWith" in Windows Explorer, the correct file loads into Notepad++.

OpenWith Notepad passes off to Notepad++ and has the problem.
OpenWith Notepad++ opens the correct file.

Recently I wanted Notepad++ to be the default text editor (replacing Notepad.exe).
I followed these instructions that I found (but I do not fully understand).
------------------------------------------------------------------
To replace Notepad with Notepad++
32-bit Notepad++

reg add "HKLM\Software\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\notepad.exe" /v "Debugger" /t REG_SZ /d "\"%ProgramFiles(x86)%\Notepad++\notepad++.exe\" -notepadStyleCmdline -z" /f

64-bit Notepad++

reg add "HKLM\Software\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\notepad.exe" /v "Debugger" /t REG_SZ /d "\"%ProgramFiles%\Notepad++\notepad++.exe\" -notepadStyleCmdline -z" /f

To UNDO
reg delete "HKLM\Software\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\notepad.exe" /v "Debugger" /f
------------------------------------------------------------------

**Comment by CookiePLMonster** [comment]
So yes that's related to paths not being quoted. I'm not sure if adding `"%1" at the end of this registry entry will work, I guess you can try.

**Comment by sydnet** [comment]
I think I'll use the UNDO option.
What is a better way to make Windows use Notepad++ when double-clicking a .txt file?

**Comment by CookiePLMonster** [comment]
Just associate it with .txt files from any .txt file's Properties. Also, didn't the installer give an option to do that?

**Comment by sydnet** [comment]
Ok, done that now. The simple things... :-)

I would still like to load Notepad++ when I click Start-Run and I type in Notepad.exe (it's such a habit)

**Comment by xylographe** [comment]
@sydnet 
NodepadStarterPlugin perhaps?

**Comment by sydnet** [comment]
I was feeling bad about finding this registry hack somewhere on the internet, but I notice that it is actually a suggested change on the Notepad++ website:
https://notepad-plus-plus.org/features/replace-notepad.html

So the issue is open again.

Summary: 
Opening a text file (by double-clicking in Windows Explorer) will open the wrong file if there are two consecutive spaces.

Example:
new[space]2.txt (this has one space in the filename)
new[space][space]2.txt (this has two spaces in the filename)

When I double-click on the filename with two spaces, Notepad++ (v7.7.1) loads the one with the single space in the filename IF I HAVE THE REGISTRY MODIFICATION ABOVE.

**Comment by xylographe** [comment]
@sydnet 

As @CookiePLMonster said before, the problem is not that registry modification. The problem is with other registry entries that use `%1`  instead of `"%1"`. To fix the problem:

1. Press **Win+R** to open the Run dialog. Type **`regedit`**. Click **OK**.
2. When **regedit** has started, select **HKEY_CURRENT_USER** in the left panel.
3. Press **Ctrl+F** to open the Find dialog.
4. Type **`notepad.exe`**, in the **Find what** text box.
5. Check **Data**. Uncheck **Keys**, **Values**, and **Match whole string**.
6. Click the **Find Next** button.
7. If the data field of the found entry looks like **`%SystemRoot%\system32\NOTEPAD.EXE %1`** (the actual path doesn't matter, any path that ends with **`notepad.exe`** is a match) , then change the **`%1`** to **`"%1"`**.
8. Press **F3** to search for the next occurrence, and repeat until all matches in **HKEY_CURRENT_USER** have been corrected.
9. Repeat to correct similar entries in the **HKEY_LOCAL_MACHINE** registry hive.

**Comment by CookiePLMonster** [comment]
I feel that's partially on me. While I personally consider this behaviour pretty silly, if stock notepad.exe can handle a non-quoted filename, we should too.

I specifically remember adding support for this by forming a filename from tokenized arguments (argc/argv) - but indeed, this way all whitespaces are being collapsed! I'll look into it soon.

**Comment by CookiePLMonster** [comment]
Now I remember how it was. `-notepadStyleCmdline` was added to mimick notepad's behaviour, so you should use that if you want to replace notepad.

Although, it still merges multiple spaces into one and thus opens a wrong file when your repro steps are followed! Looking into it right now.

**Comment by CookiePLMonster** [comment]
See #5883! Should work fine now.
