### ISSUE TITLE
Removing trailing tabs and spaces doesn't work by hot key

### ISSUE THREAD

**Issue by NotepadUser** [notepad-plus-plus/notepad-plus-plus#5862]
### Description of the Issue
By selecting the menu Edit --> Blank Operations --> Trim Trailing Space it is possible to remove all trailing spaces and tabs in the current document. This function should be also available by pressing Ctrl+Shift+Spacebar. But this hot key does not work any more.

### Steps to Reproduce the Issue

1. Open a document with spaces and/or tabs at the end of some lines.
2. Press the hot key Ctrl+Shift+Spacebar.

### Expected Behavior
Trailing blanks such as spaces and tab signs are deleted.

### Actual Behavior
Nothing happens, trailing spaces and tabs remain in the document.

### Debug Information
Notepad++ v7.7.1   (32-bit)
Build time : Jun 16 2019 - 21:14:50
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 7 (64-bit)
Plugins : ccc.dll ComparePlugin.dll mimeTools.dll NppConverter.dll NppExport.dll NppFTP.dll PluginManager.dll

**Comment by sasumner** [comment]
>This function should be also available by pressing Ctrl+Shift+Spacebar. But this hot key does not work any more.

When was this ever the default?  As far as I can remember, this function has had no default keycombo.  BUT...just assign ctrl+shift+spacebar (or whatever you like) with the Shortcut Mapper.

There is no reason this issue should remain open.

**Comment by NotepadUser** [comment]
It has actually been default function about two years ago. If it is now no wanted function any more, then the hot key should not be mentioned in the menu selection for Blank Operations. Or – and that’s the issue – the hot key combination has to be reestablished as shown in the menu.

**Comment by sasumner** [comment]
>the hot key should not be mentioned in the menu selection for Blank Operations

It isn't.  I'm confused.

**Comment by NotepadUser** [comment]
There it is:
![grafik](https://user-images.githubusercontent.com/52373485/60586409-4cc0ca80-9d92-11e9-946d-7f9f2819c051.png)

**Comment by Ekopalypse** [comment]
Does not seem to be set for me
![image](https://user-images.githubusercontent.com/47723516/60587565-504d5500-9d84-11e9-86d5-7eb9f4fe37fe.png)

**Comment by NotepadUser** [comment]
Obviously there exist different versions of Notepad++, some having the short keys mentioned in the submenu by default and some not. Though I never customized Notepad++ in that way...

**Nevertheless the problem has been solved:** It was a double shortcut entry in the Shortcut Mapper, that’s why it did not work. Now it’s okay.
Thank you for your contribution.
