### ISSUE TITLE
Sorting by decimal numbers when there are empty lines in column selecting causes the program to EXPLODE

### ISSUE THREAD

**Issue by GhbSmwc** [notepad-plus-plus/notepad-plus-plus#5865]
Suppose you make a text, like this:

```
100/20 = 5

1/3    = 0.333

22/7   = 3.14285714286
```
Please note that empty lines between the numbers are intentional.

Now column-select the numbers to the right of the equals sign, then go to the menu bar -> Edit -> Line Operations -> Sort Lines as Decimals (dot) Ascending or Descending. This happens:
![image](https://user-images.githubusercontent.com/13095760/60476587-2abc3080-9c4a-11e9-8bc4-489037e12128.png)
![image](https://user-images.githubusercontent.com/13095760/60476602-3871b600-9c4a-11e9-862e-115c479e9a4f.png)
![image](https://user-images.githubusercontent.com/13095760/60476633-5212fd80-9c4a-11e9-9faf-fa8079e434a0.png)
![image](https://user-images.githubusercontent.com/13095760/60476673-740c8000-9c4a-11e9-9205-a7de27dec93b.png)
https://www.youtube.com/watch?v=jEexefuB62c

I have Compare, DSpellCheck, MIME Tools, Converter, and NPP Export

**Comment by GhbSmwc** [comment]
It also happens with integers (sort integers ascending/descending) as well:

```
730458670237845678

239845760983426503
```

**Comment by sasumner** [comment]
Duplicate: #3391
