### ISSUE TITLE
npp version support clarification needed

### ISSUE THREAD

**Issue by TekBear** [notepad-plus-plus/notepad-plus-plus#5867]
This issue is for documentation update.

The term " MS Windows environment" needs some clarification. 99% of sites offering software downloads have an explicit statement about which version of Windows are supported. I visited https://notepad-plus-plus.org/ about page, looked in release notes on under https://notepad-plus-plus.org/download/all-versions.html and searched several other pages and there is no easy way to find the answer. Is it documented somewhere else?

I would suggest putting a more exact statement in https://github.com/notepad-plus-plus/npp-usermanual/blob/master/content/getting-started/_index.en.md, "about" and download pages. The Download page is the first page I check for this information.

Does "MS Windows environment" mean:
Support for Windows 10 or higher?
Support for Windows 7 or higher?
Support for Windows XP or higher?
Support for Windows 9x or higher?

From what I have read in an issue https://github.com/notepad-plus-plus/notepad-plus-plus/issues/4823#issuecomment-489410403 XP is unofficial, reduced functionality but usable is that correct?

What is the last supported version of npp suitable for windows XP?
What is the last supported version of npp suitable for windows 9X?

If someone can tell me correct answers I am happy to update https://github.com/notepad-plus-plus/npp-usermanual/blob/master/content/getting-started/_index.en.md and the othe 2 pages can be linked to that page.

**Comment by Ekopalypse** [comment]
The toolset set is [v140_xp](https://github.com/notepad-plus-plus/notepad-plus-plus/blob/master/PowerEditor/visual.net/notepadPlus.vcxproj#L30), so no win9 support anymore. But I'm unser if some of the older versions available support win9 or not.

**Comment by tabarnakos** [comment]
Related to #5566

**Comment by TekBear** [comment]
@Ekopalypse  "The toolset set is v140_xp,"

I don't know how to interpret that file. Most of the original links I cited no longer exist. I still don't know which is the last working version recommened for XP, Vista, Win 7.

**Comment by TekBear** [comment]
@Ekopalypse "The toolset set is v140_xp,":

I don't know how to interpret that file. Most of the original links I cited no longer exist. I still don't know which is the last working version recommended for XP, Vista, Win 7.

**Comment by donho** [comment]
By "support" does it mean that Notepad++ can be run under such environment or Notepad++ team (and me) will take effort to make Notepad++ compatible to such environment? On both we don't have the resource to provide such list.

**Comment by sasumner** [comment]
> I still don't know which is the last working version recommended for XP, Vista, Win 7.

There is no "recommendation".  You can try any version of Notepad++ on any platform, and if it works, then GREAT.
