### ISSUE TITLE
Create file confirmation modal has incorrect file name

### ISSUE THREAD

**Issue by barisdemiray** [notepad-plus-plus/notepad-plus-plus#5868]
### Description of the Issue
When we enter in `Open` dialog a file name that doesn't point to an existing file, Notepad++ asks if we would like to create it, with wrong file name in the confirmation question.

### Steps to Reproduce the Issue
1. Do Ctrl+O
2. Enter a filename that doesn't exist in currently selected folder, e.g. missing.txt
3. Observe Notepad++ asking if it should create file `0`.

### Expected Behavior
Having the name we entered before.

### Actual Behavior
Just `0` as the filename.

### Debug Information
![image](https://user-images.githubusercontent.com/2464842/60516465-188bd200-9cde-11e9-9c1e-47c4363d995f.png)

Version 7.7.1 32-bit on Windows 10.

**Comment by sasumner** [comment]
Doesn't work that way for me.  It says:

    missing.txt
    File not found.
    Check the file name and try again.

>Version 7.7.1 32-bit on Windows 10.

I'm using same.

**Comment by barisdemiray** [comment]
Hi @sasumner, thanks for the response. To be sure we're following the same steps to reproduce, here is a gif that demonstrates what's happening on my computer.

![notepad++ missing file](https://user-images.githubusercontent.com/2464842/60578329-4c6c0380-9d81-11e9-953f-f9a51cbbd1de.gif)

**Comment by Ekopalypse** [comment]
@barisdemiray - I don't have that issue either. Could it be that 0 is part of your path?

**Comment by xylographe** [comment]
@barisdemiray 
This is a bug in `PowerEditor\installer\nativeLang\french.xml`,
```xml
<CreateNewFileOrNot title="Create new file" message="&quot;$INT_REPLACE$&quot; doesn't exist. Create it?."/>
```
should read,
```xml
<CreateNewFileOrNot title="Create new file" message="&quot;$STR_REPLACE$&quot; doesn't exist. Create it?."/>
```
The same problem occurs in some other tags too.

**Comment by barisdemiray** [comment]
Thanks @xylographe for getting to the bottom of this!
