### ISSUE TITLE
Object count issue

### ISSUE THREAD

**Issue by thomasrodriguezv** [notepad-plus-plus/notepad-plus-plus#5874]
### Description of the Issue
In the new version (7.7.1) when clicking the Count button on the search tab the result is always 1

### Steps to Reproduce the Issue
1. Select a word repeated more than one time
2. Press Ctrl + F
3. Click the "Count" button, on the bottom part of the tab the result will always be 1

### Expected Behavior
It has to appear the number of repeated words.

### Actual Behavior
It always appear 1 as a result

### Debug Information
None

In Spanish:
![image](https://user-images.githubusercontent.com/46304934/60635568-e01cee80-9dd8-11e9-8a54-31c7083a7073.png)

The "td" word is repeated more than 1 time, but, in the Buscar (Search) bar the counting is 1 (Contar: 1 coincidencia (Count: 1 coincidence)).

**Comment by xylographe** [comment]
Perhaps you should uncheck "**En la selección**"?
