### ISSUE TITLE
Remember the session location and name

### ISSUE THREAD

**Issue by Hans-van-B** [notepad-plus-plus/notepad-plus-plus#5878]
### Description of the Issue
When saving a session, the editor is not aware of the location of the current session. Especially when working with multiple sessions this is confusing and one runs the risk of saving towards a different session, overwriting another session.

### Steps to Reproduce the Issue
Open a session
Open a file from another location
Then save the session. Now the default folder is not correct and also no default name is given.

### Expected Behavior
I would like to have both the directory and name correspond to the session that was opened earlier.

### Actual Behavior
 the default folder is not correct and also no default name is given

**Comment by victorel-petrovich** [comment]
> When saving a session, the editor is not aware of the location of the current session.

But how can it keep track of _current_ session, if you may close any or all of the files in that "session"? 

> I would like to have both the directory and name correspond to the session that was opened earlier. 

👍  , I second that, except in a more general formulation: not only when saving, but also when loading a session. And correspond not only to earlier opened session, but, more generally, to last loaded(opened) _or_ saved session.

**Comment by donho** [comment]
That makes "Default save/open directory" even more complex. 
This feature won't be implemented.
