### ISSUE TITLE
Enable vertical scroll with mouse wheel when notepad++ is not the active window

### ISSUE THREAD

**Issue by crisrover** [notepad-plus-plus/notepad-plus-plus#588]
Hi, 
It would be really helpful if this feature is implemented.
Thank you

**Comment by dail8859** [comment]
I'm not completely sure but I think this mostly just due to how Windows works. You can install MouseWiz and it will give you this capability for *all* applications. It comes in quite handy!

**Comment by crisrover** [comment]
Thank you for the quick reply, I was thinking of something like treating the: WM_MOUSEMOVE or WM_MOUSEHOVER messages, the window will receive these messages even if it's not the active window. ( Just tested this quickly and it works ).
Firefox for example is doing this - if the active window is not "eating" the messages. ( I'm running Firefox 39.0 )

**Comment by GitMensch** [comment]
I don't think it's a good idea to implement this and always listen to these messages as it's not a common feature (checked some apps on Windows 7 including apps Firefox v44, Windows Explorer, and other editors - no one has it) and will destroy the common feature that the active window always gets access to these messages.
I vote for "close" - if someone wants to change the Windows standard behaviour and installs an external software he knows about the change.

**Comment by arfyness** [comment]
This is finally a mouse setting now, in Win10 at least.  Search for "change mouse settings" or something like that.  Prior to Win10, (back to XP) I've long been using [AltDrag](https://stefansundin.github.io/altdrag/) (also here on gitub) primarily to provide XWindows style moving & sizing of windows in Windows, but also it has that neat feature "scroll inactive windows" and a few other nifty tricks.

(What I'm actually doing here is looking for a way to get scroll-up to work immediately after scroll-down and vice-versa, when scrolling with a mouse wheel there's a dead bump when switching directions.  I'll keep looking)

**Comment by MetaChuh** [comment]
we are closing this issue due to its age and multiple newer notepad++ versions since it was filed.

please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html).
if your issue persists, and it is still of relevance to you, please feel free to file a new issue.

thank you for your help and best regards.

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
```
[<kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd>](https://notepad-plus-plus.org/community/)

**Comment by GitMensch** [comment]
Closing it is fine, as @arfyness already said: scroll events now are normally passed to windows that are currently not active in Windows 10 (the ["modern ui"] mouse settings can be used to disable this behavior or to re-enable it).
