### ISSUE TITLE
nppexport plugin exports plain text without syntax coloring

### ISSUE THREAD

**Issue by mfinky** [notepad-plus-plus/notepad-plus-plus#5880]
### Description of the Issue

NppExport plugin does not export colors and fonts.
nppexport version:  0.2.8
notepad++ version: v7.7.1 32 bit

### Steps to Reproduce the Issue

1. Edit a file with a known extension.  e.g. .SQL, .XML,  .CS, .VB.
2. Highlight a portion of text that contains bold, colors, and other syntax enhanced formatting
3. use either copy export to rtf or copy rtf to clipboard functionality
4.  Paste clipboard content into MS-Word, or open the exported file and review it.
### Expected Behavior

Expected: content shoudl contain syntax formatting.  Colors, Bold, etc.

### Actual Behavior

Actual: the plugin seems to have copied only plain text.  wihtout colors etc.

### Debug Information

Notepad++ v7.7.1   (32-bit)
Build time : Jun 16 2019 - 21:14:50
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : ON
Local Conf mode : OFF
OS : Windows 7 (64-bit)
Plugins : ComparePlugin.dll HTMLTag_unicode.dll mimeTools.dll NppConverter.dll NppExport.dll NppFTP.dll NppTextFX.dll PoorMansTSqlFormatterNppPlugin.dll XMLTools.dll

**Comment by pkabal** [comment]
Have the same problem, but it does not seem to be in nppexport. I have the same version of nppexport (0.2.8) on two systems, one running notepad++ 7.5.9 (export works as expected), and notepad++ 7.7.1 (no syntax colouoring). Hope this comment helps in tracking down the problem.

**Comment by mfinky** [comment]
Thanks pkabal for the feedback.

If I really, really, really need to use coloring, I will consider downloading the old version of notepad++, but … honestly, I will try not to.

Kind Regards.
Marcelo Finkielsztein

**Comment by Ekopalypse** [comment]
There is a fix already available, see https://github.com/chcg/NPP_ExportPlugin/releases/tag/0.2.9.21

**Comment by mfinky** [comment]
Nicely Done.  Thanks!

**Comment by Ekopalypse** [comment]
So you might close this issue? Strictly speaking, it is not a npp issue at all.

**Comment by mfinky** [comment]
Thanks Very Much
