### ISSUE TITLE
Switching between tabs looses custom language selection

### ISSUE THREAD

**Issue by eht-coder** [notepad-plus-plus/notepad-plus-plus#5881]
### Description of the Issue
When opening multiple files in tabs, one of them being an XML file.
For the XML file i choose a Javascript as custom language because the XML file contains Javascript snippets.
When switching to another tab and back again the selected language is automatically switched back to XML.

The selected language selection should be keept until tab/file is closed.

Version 7.7.1 32bit

**Comment by sasumner** [comment]
The issue template was there for you to fill in, not to leave blank.

**Comment by eht-coder** [comment]
@sasumner, I would never have guessed, thanks for telling.
 Unfortunatly i hit the wrong button.

**Comment by eht-coder** [comment]
This is no bug.
The thing that is going on is that i use the plugin "XML Tools", and after i upgraded Notepad++ the
the option "**Plugins**" -> "**XML Tools**" -> "**Set XML type automatically**" was set.
Exactly how it got set i am unsure of, but disabling this option solves my issue. 

Sorry for the inconvenience.
