### ISSUE TITLE
Update overwrites clipboard with the "what's new" text

### ISSUE THREAD

**Issue by NancyFolsom** [notepad-plus-plus/notepad-plus-plus#5885]
### Description of the Issue
Updates to Notepad++ overwrite text in the clipboard with "what's new" text, 

### Steps to Reproduce the Issue

1. Highlight some text in some program, it doesn't matter what.
2. CTRL-C to copy
3. Open Notepad++ when there's a pending update
4. Agree to the update

### Expected Behavior
I expected to be able to paste the text I'd copied in the first place.

### Actual Behavior
Ctrl-V pasted the Notepad++ update "what's new" text, not the text I'd copied. 

### Debug Information
Notepad++ v7.7   (32-bit)
Build time : May 19 2019 - 13:08:20
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10 (64-bit)
Plugins : DSpellCheck.dll mimeTools.dll NppConverter.dll NppExport.dll

**Comment by CennoxX** [comment]
The bug is no longer reproduced in version 8.4.1 on Windows 10.
