### ISSUE TITLE
Feature request: use explorer.exe or better file navigation tool

### ISSUE THREAD

**Issue by GhbSmwc** [notepad-plus-plus/notepad-plus-plus#5889]
When navigating the files, most programs uses “explorer.exe” (not to be confused with internet explorer). However, I don't like that programs force you to use their own file navagation tool that doesn't let you enter the file path directly:
![image](https://user-images.githubusercontent.com/13095760/60737299-45cbc080-9f28-11e9-9c44-7b1770fc5e4c.png)

I had to input multiple times to get into each subdirectory, I often rather just copy the address and paste it and hit enter and it automatically jumps to that area.

I mean, even GIMP, despite  not using explorer.exe, at least lets you enter the path:
![image](https://user-images.githubusercontent.com/13095760/60737449-d4404200-9f28-11e9-99f1-534271fdb4f4.png)

**Comment by Ekopalypse** [comment]
goto **Settings->Preferences->Default Directory** and check **use new style dialog... **

**Comment by GhbSmwc** [comment]
Thanks!

**Comment by Ekopalypse** [comment]
If it is what you are looking for, can you close the issue please?

**Comment by GhbSmwc** [comment]
okay. Sorry
