### ISSUE TITLE
plugin shortcut configuration lost with option -noPlugin

### ISSUE THREAD

**Issue by cmeriaux** [notepad-plus-plus/notepad-plus-plus#589]
plugin shortcut configuration is lost when you start notepad++ with -noPlugin option
shortcut.xml should be saved on shortcut modification or macro modification instead of on exit.

procedure to reproduce this bug :

Consider that you have some plugins with marco shortcut configured. Then :

Start Notepad++ with the option -noPlugin
Stop Notepad++. During the close, it rewrites the shortcut.xml. As there is no plugin loaded, the plugin section of shortcut.xml is empty.
start Notepad++ again. All plugin shortcut have been loosed.

**Comment by sanastasiou** [comment]
@cmeriaux  Does your fix, also fixes the issue where shortcut.xml is not being updated during runtime?

**Comment by cmeriaux** [comment]
@sanastasiou yes my PR fixes the issue when shortcut.xml is not being updated during runtime.
