### ISSUE TITLE
Python builtins highlight

### ISSUE THREAD

**Issue by PavelBlend** [notepad-plus-plus/notepad-plus-plus#5895]
### Description of the Issue
You need to make a highlight of the built-in functions, exceptions, constants (from the `__builtins__` module). Do the same as in Python IDLE.

### Expected Behavior
![builtins_highlight](https://user-images.githubusercontent.com/7983249/60758283-4a72a080-a01e-11e9-8820-250ead7e773b.jpg)
![builtins_highlight_notepad](https://user-images.githubusercontent.com/7983249/60758285-4e062780-a01e-11e9-83b6-744423f04e05.jpg)

### Actual Behavior
There is no highlight `__builtins__` in version 7.7.1

**Comment by Ekopalypse** [comment]
It seems you already added it as user defined keywords, in order to have it included as default keywords for upcoming npp releases fork the repo, make the necessary changes to langs.xml and create PR.

**Comment by PavelBlend** [comment]
I'm not sure about the changes I made. And I do not remember which files changed. I read a lesson on the Internet. And repeated all the steps in the lesson. I would like a knowledgeable person to do this.

**Comment by PavelBlend** [comment]
Pull Request: #7613

**Comment by dail8859** [comment]
Closed by 6f56b441188a114488a655c9faac9f07629da5e4
