### ISSUE TITLE
`View current file in ...` for more file types

### ISSUE THREAD

**Issue by pryrt** [notepad-plus-plus/notepad-plus-plus#5903]
### Description of the Issue
(inspired by https://notepad-plus-plus.org/community/topic/17913/how-do-i-add-the-launch-in-chrome-in-version-7-7-1)

Currently (v7.7.1), `View current file in ...` menu-actions are active for `.html` and `.js` and `.xml`.  However, there are many types (like `.txt`, `.php`, `.asp`) which a user might reasonably (or unreasonably) want to view in the browser, for which those options are greyed out

### Steps to Reproduce the Issue

Save file as `blah.txt`, `blah.php`, `blah.asp`, menu greyed out.

### Expected Behavior

Save file as `blah.txt`, `blah.php`, `blah.asp`, menu enabled.

### Actual Behavior

Save file as `blah.txt`, `blah.php`, `blah.asp`, menu greyed out.

### Debug Information

v7.7.1 64-bit

* Simplest and best fix: always have those options available for saved files, regardless of extension / file-type
* Alternate: at least add `.php` and `.asp` to the list of extensions that enable those menu options
* Better Alternate: make the list of extensions that enable `view current file in...` to be user-configurable, so that a user could add more extensions that will be able to preview in browser

**Comment by hopalongrock** [comment]
See my post in
https://notepad-plus-plus.org/community/topic/18255/can-t-run-the-browser-for-all-file-types-from-the-view-menu

Can't run the browser for all file types from the View menu

I do not think that the file type (extension) should be examined here, all existing files should be shown.

**Comment by pryrt** [comment]
Per [this sub-post](https://notepad-plus-plus.org/community/topic/18255/can-t-run-the-browser-for-all-file-types-from-the-view-menu/8), Ekopalypse identified https://github.com/notepad-plus-plus/notepad-plus-plus/blob/581aff630af9b12b85b52c3673d15d8f6fde8031/PowerEditor/src/Notepad_plus.cpp#L2008-L2011 and following as the four lines that are disabling those commands: basically, if they are files whose file-association would run Notepad++, those four lines disable those four open-in-browser commands.  But in that thread, we can see no good reasons for that restriction -- a user might want XML files associated with Notepad++, but still want to be able to open them in their browser from Notepad++.  For us, it makes more sense to let the user open any file with the browser, so change those four lines to:

	enableCommand(IDM_VIEW_IN_FIREFOX, true, MENU);
	enableCommand(IDM_VIEW_IN_CHROME, true, MENU);
	enableCommand(IDM_VIEW_IN_IE, true, MENU);
	enableCommand(IDM_VIEW_IN_EDGE, true), MENU);

(I don't know the codebase enough to know whether it's required to set them to true, or whether you can just get rid of those four lines and have them be enabled by default.)

**Comment by sasumner** [comment]
I will look into creating a PR for this.

**Comment by donho** [comment]
menu greyed out only on blah.php, blah.asp, but not on blah.txt.
