### ISSUE TITLE
Hunspell: exception on Add to Dictionary when Hunspell folder missing

### ISSUE THREAD

**Issue by JHammler** [notepad-plus-plus/notepad-plus-plus#5911]
### Description of the Issue
Notepad++ crashed when trying to add a word to dictionary through the right-click context menu.

My (default) Hunspell Dictionaries Path in DSpellCheck settings referred to a non-existent folder (a UNC path, if it matters).
\\<server>\<username>\application_data\Notepad++\plugins\Config\Hunspell

I created the Hunspell folder and the expected behaviour was achieved. en_GB.usr was created and populated with the word.

### Debug Information
Notepad++ v7.7.1   (32-bit)
Build time : Jun 16 2019 - 21:14:50
Path : C:\Notepad++\notepad++.exe
Admin mode : ON
Local Conf mode : OFF
OS : Windows 7 (64-bit)
Plugins : DSpellCheck.dll mimeTools.dll NppConverter.dll NppExport.dll 

### Expected fix
When checking for the existence of a dictionary file files and the file is created, existence of the folder should be checked and created if not. If folder creation fails the exception should be caught and a write permissions error displayed.

**Comment by Ekopalypse** [comment]
Make sure you use the latest version of DSpellCheck plugin. If this still doesn't solve your problem,
open an issue [here](https://github.com/Predelnik/DSpellCheck).
Close this issue.

**Comment by JHammler** [comment]
I can't recreate the problem on my home PC (DSpellCheck 1.4.6.0), which doesn't use a UNC file path for configuration files, and will confirm/recheck & update the version installed on my work PC on Monday.

### Debug info
Notepad++ v7.7.1   (32-bit)
Build time : Jun 16 2019 - 21:14:50
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : ON
Local Conf mode : OFF
OS : Windows 7 (64-bit)
Plugins : DSpellCheck.dll mimeTools.dll NppConverter.dll NppExport.dll
