### ISSUE TITLE
Document List Panel: File names with multiple periods are improperly displayed

### ISSUE THREAD

**Issue by AndrewBS42** [notepad-plus-plus/notepad-plus-plus#5912]
### Description of the Issue

The System is behaving as it should.  The file name display is actually correct.
I couldn't find a way to remove this post.

I discovered that I had stretched the "Name" column so wide that the "Ext" column was out of sight to the right.

I apologize for bothering people.

Andrew

**Comment by Ekopalypse** [comment]
Close issue - done.

**Comment by SinghRajenM** [comment]
@MetaChuh

**Comment by sasumner** [comment]
@AndrewBS42 For such a case, just CLOSE the issue.  There is no way to "remove the post".  I will go ahead and close it, so you need take no further action.
