### ISSUE TITLE
` is improperly shown when \ is used

### ISSUE THREAD

**Issue by MistakingManx** [notepad-plus-plus/notepad-plus-plus#5913]
### Description of the Issue
When you use \` it acts as if \ wasn't there, which leads to some
annoy things, like the screenshot for example.

### Steps to Reproduce the Issue
1. Write a line of code similar to this:
`console.log(`This is a nice item '\`' `);
console.log("As you can see ` is messed up.");`

### Expected Behavior
It should make it not cover everything after it in a gray line.

### Actual Behavior
IT COVERED IT ALL IN A GRAY LINE.

### Debug Information
I dont really know what to show here, it doesnt cause any errors at all because the code works like it should, the visual part just doesnt.

### Screenshot
![image](https://user-images.githubusercontent.com/28667267/61149352-ed0fa100-a4ae-11e9-97f4-ab3a5f999f2c.png)

**Comment by Ekopalypse** [comment]
Debug info from the ? menu (last item).
In addition, which language/lexer is used?

**Comment by dail8859** [comment]
Please provide more details and reopen.
