### ISSUE TITLE
Typing Cursor Changed.

### ISSUE THREAD

**Issue by vizthex123** [notepad-plus-plus/notepad-plus-plus#5914]
I don't know what caused it, but the typing cursor changed from the default vertical line cursor to a programming-type one. (where the blinking line is instead a bar below text and it acts weird)

I would screenshot them but I can't.....

**Comment by Ekopalypse** [comment]
I assume that in the statusbar on the bootom right you see a field called OVR. Click into it and it should change to INS, as well as your caret. Alternativ, press INS key on keyboard.
Close issue afterwards.
