### ISSUE TITLE
Msg 'No update available.' not translated

### ISSUE THREAD

**Issue by bovirus** [notepad-plus-plus/notepad-plus-plus#5916]
@donho 

Checking the update from inside Notepad++ appear a wind

Title = Notepad++ update
Text = No update is available.

that are not translated.
Please if you can to add them to translation strings.

Thanks.

**Comment by donho** [comment]
It's a message box from WinGUp, not from Notepad++

**Comment by bovirus** [comment]
@donho

And is not possible to translate it?
