### ISSUE TITLE
Default new document is UTF8 without BOM + apply to opened ANSI files

### ISSUE THREAD

**Issue by jdenijs** [notepad-plus-plus/notepad-plus-plus#592]
Hello all,

When I openend my Notepad++ I noticed that the default setting for a new document was set to UTF8 without BOM + apply to opened ANSI files.
Probably a choice I don't understand, but why not....

I tried changing the setting in config.model.xml and that is the location that I have an error:
In the information you state:

My settings were set as follows:
<GUIConfig name="NewDocDefaultSettings" format="0" encoding="4" lang="0" codepage="-1" openAnsiAsUTF8="yes" />

I didn't want this so I changed it to encoding="3" (should be UTF8 right?). But then my Notepad++ showed the encoding of UCS-2 Little Endian.

Guess something goes wrong there. Perhaps it's an idea to correct this?

Kind regards,

Jos de Nijs

**Comment by donho** [comment]
I could be wrong, but actually UTF-8 is heavily used in (almost) every application, and it became a standard.

config.xml is not supposed to be modified manually. 
Please use Preferences dialog for such job.

**Comment by jdenijs** [comment]
I Agree on the UTF-8 explanation (in fact: totally), but can you explain me why does Notepad++ have a default voor UTF-8 without BOM + apply to opened ANSI files. Surely that is NOT the standard, or am I wrong?
