### ISSUE TITLE
Monospace font on  Find/Replace

### ISSUE THREAD

**Issue by SapadorCastelo** [notepad-plus-plus/notepad-plus-plus#5920]
### Description of the Issue
I didn't quite understood why this issue was closed:
https://github.com/notepad-plus-plus/notepad-plus-plus/issues/449
As I'm using a N++ v.7.7.1 and it's very hard to read/edit the "Find what" and "Replace with" fields. Typing any RegEx with a non-monospcaced font is terrible.

### Expected Behavior
Have a monospaced font as the mentioned fields default font.

### Actual Behavior
I can't even click between narrow characters like "i", "l" and vertical bars.

**Comment by sasumner** [comment]
A good suggestion.  While you are waiting for it, you could consider a implementing a similar technique to that described here: https://notepad-plus-plus.org/community/topic/16743/find-window-font-size .

**Comment by xylographe** [comment]
Alternatively, you could modify `PowerEditor/src/ScitillaComponent/FindReplaceDlg.cpp`,
```
void FindReplaceDlg::create(int dialogID, bool isRTL, bool msgDestParent)
{
	StaticDialog::create(dialogID, isRTL, msgDestParent);

	static HFONT cbFont;
	if (!cbFont)
	{
		LOGFONT lf;
		memset(&lf, 0, sizeof(LOGFONT));
		_tcsncpy_s(lf.lfFaceName, LF_FACESIZE, TEXT("Consolas"), 8);
		lf.lfHeight = 13;
		cbFont = ::CreateFontIndirect(&lf);
	}
	::SendDlgItemMessage(_hSelf, IDFINDWHAT, WM_SETFONT, (WPARAM)cbFont, (LPARAM)TRUE);
	::SendDlgItemMessage(_hSelf, IDREPLACEWITH, WM_SETFONT, (WPARAM)cbFont, (LPARAM)TRUE);

	fillFindHistory();
```
For the Consolas font family 12, 13, and 14 seem to be reasonable font heights.
The font weight can also be set — see [the LOGFONT structure.](https://docs.microsoft.com/en-us/windows/win32/api/wingdi/ns-wingdi-logfontw)

**Comment by sasumner** [comment]
@SapadorCastelo 

>I didn't quite understood why this issue was closed: #449

I will make the educated guess that the author doesn't like the idea of a monospaced font for these fields.  Just because people open issues (sometimes repeatedly) doesn't mean that the author agrees and will change his product.

**Comment by donho** [comment]
@xylographe  Make a PR. I will accept it.

**Comment by Ekopalypse** [comment]
I don't want to be the spoilsport, but are we sure that Consolas is the right choice?
It might not be available on XP systems and more important it isn't [listed](https://en.wikipedia.org/wiki/Unicode_font) as a unicode font. Does find/replace, visually, still work if using Consolas?

**Comment by xylographe** [comment]
@Ekopalypse
I completely agree. The modification above (with hard-coded font and font size) was meant as a _temporary_ solution. I believe, a real solution must be configurable (User Preferences). I don't think any font will be adequate in _every_ language,

**Comment by Ekopalypse** [comment]
@xylographe - if there is anything I can do to assist or test, let me know.

**Comment by Ekopalypse** [comment]
@sasumner - why are you confused?
Does my offer to help make no sense, grammatically?
Or do you think there is nothing I can do to support @xylographe?

**Comment by sasumner** [comment]
@Ekopalypse Not much to do, probably, unless and until @donho makes a decision on direction for this.  At least that was my first thought.  I meant to say something in addition to the "confused" but got distracted away from doing so. :)

**Comment by ScienceDiscoverer** [comment]
The monospaced font used is very hard to read. Almost as bad as default font. Why there is no option to select the font the user wants for find & replace?
