### ISSUE TITLE
* in file open or save dialog does not filter files

### ISSUE THREAD

**Issue by drayna5** [notepad-plus-plus/notepad-plus-plus#5924]
### Description of the Issue

On a large directory, *.txt or etc does not filter the list of files to choose from -- Open loads them all and Save just fails.
I think the behavior changed in Notepad a little while ago.

### Steps to Reproduce the Issue

1. Open a large directory and enter a pattern like g*.txt to find what files like that are present.

### Expected Behavior

The list of files is now filtered by your input.

### Actual Behavior

An Open dialog will load every file matching the pattern.
A Save dialog will fail.

**Comment by sasumner** [comment]
Tick the box, like this:

![image](https://user-images.githubusercontent.com/30118311/61398802-cbd9f680-a89a-11e9-932d-04aa5b59af14.png)

**Comment by drayna5** [comment]
Works. Thank you.
I will have to checkmark that on all the machines I use;
I assume a previous update caused the change.

A few times I did want to load multiple files, but it is safer to filter the list then multi-select from the list and see what you are getting before you have a hundred tabs...

**Comment by sasumner** [comment]
>see what you are getting before you have a hundred tabs.

yes, absolutely!

**Comment by Ekopalypse** [comment]
@drayna5  - if this is solved for you, can you close the issue?
