### ISSUE TITLE
[Feature Request] Highlight changes made in a file.

### ISSUE THREAD

**Issue by joseramirezrk** [notepad-plus-plus/notepad-plus-plus#5926]
Description of the Issue:

Hello! This is not an issue, is just a feature request that might be useful for beginners: Highlight the modified lines (in some way, of course...).

Steps to Reproduce the Issue:

Just open a file and check where was your last change made.

Expected Behavior:

Have something like the bug or github syntax, adding something like -- to deleted lines and ++ to new lines. Something like that, not exactly like that. 

Actual Behavior:

Everything works great, it's just that, as a noob, I found quite difficult to remember which lines I've just modified, since my coding profile is completely random (or non existent), so, hints of the lines I've changed or added (or even deleted) would be great, at least as I'm getting more experience documenting my wall of text of code.

Thanks!!!!

**Comment by sasumner** [comment]
>not an issue, is just a feature request

feature requests ARE issues...you are in the right place!

> I found quite difficult to remember which lines I've just modified

So true, so true!

>Highlight the modified lines (in some way

The LocationNavigate plugin (for 32-bit Notepad++ only as it appears the plugin is no longer maintained) does this by adding a margin and putting a big colored circle on a line, orange to indicate unsaved change to a line, green to indicate a change but has been saved:

![image](https://user-images.githubusercontent.com/30118311/61483703-67d33300-a96b-11e9-9622-4b3e5de62e6a.png)

Maybe the orange/green colors are something I configured in the plugin's setup, but you get the idea I'm sure.

As the plugin as mentioned is not maintained, I for one would love to see this capability in Notepad++ itself.  However, I suspect it would be something Scintilla would need to do, and I don't know if there is Scintilla support for this concept.

However, I can't "upvote" this feature request enough!  Bravo! :)

**Comment by Ekopalypse** [comment]
But how exactly should such a functionality work?
I mean, from what I read and understood it should be available even after npp restarts. 
When is it going to be reset? On save? What if one saved the file and then does an undo action?
What if a file has been changed outside from npp while npp was not running at that time. ...

**Comment by sasumner** [comment]
> it should be available even after npp restarts.

No (at least that's my opinion).  Likely this is too hard of an implementation.  I presume you mean for "unsaved" tabs is where this would be desired.

>When is it going to be reset? On save?

Depends upon what "reset" means. :)  "on save" just turns any "orange" (unsaved changes on a line) markers to "green" (saved changes on a line).

>What if one saved the file and then does an undo action?

Well, in this case one presumes that any "orange" markers that turned "green" would revert to orange. :)

"Undo" (and "redo") is problematic for this kind of feature.  Not logically, but rather the implementation.

>What if a file has been changed outside from npp

This kind of thing would clear all change markers.

**Comment by Ekopalypse** [comment]
@sasumner - thx for clarification. 

Not only. From the OP I understand that you might open a document and see where the last change was, so it cab be a saved document as well. This reminds me about git, svn, mercurial ... - that's there domain I guess. If npp should have such a functionality it must, somehow, do what those do.
If it is all about the current session and the information which line has changed, then a simple script
could even do it but as soon as information like which line has changed how then we are back in file versioning territory. To be honest, I'm surprised that you don't have a python script on hand doing what you want. ;-) But maybe as long an LocNav is working for you, you don't need to have PS solution :-)

**Comment by sasumner** [comment]
@Ekopalypse 

>From the OP I understand that you might open a document and see where the last change was

I would leave this to version control. :)

>as long an LocNav is working for you

LocNav plugin mostly works, but it is not 100% perfect.  And at only 32-bits and no active maintainer, its future life is a problem.  

> I'm surprised that you don't have a python script

I have often thought about a PS to do it, but when one considers how to handle undo/redo it rather falls apart (too tough).  

I suppose the true answer is the Scintilla folks considering such a feature important enough to add.  The editor I used for 15 years before Notepad++ had change-marks built-in (well, you had to turn it on via a preference), so I definitely like the feature and really don't understand why there isn't a larger push for it among the user-base of Scintilla / Notepad++.  

A challenge:  Try using LocNav with that feature turned on for one month and see if it doesn't become invaluable to you as well. :)

**Comment by Ekopalypse** [comment]
>A challenge: Try using LocNav with that feature turned on for one month and see if it doesn't become invaluable to you as well. :)

I'm a 64bit user :-), no LocNav but I guess I give it another try to implement it with PS.
I once started but then forgot about it.

**Comment by sasumner** [comment]
>I'm a 64bit user 

At the moment, with Notepad++ being 64-bit-incompatible with Pythonscript (we discussed this somewhere else...), why not be a 32-bit user?

**Comment by Ekopalypse** [comment]
Because I'm using still 7.6.6 :-)

**Comment by weirdalsuperfan** [comment]
(I'm also still using 7.6.6)

The advantage of this idea over version control is that version control is not granular enough for minor changes. Nobody commits every single time they write one line or edit one word.

I think having the option to either show all changes, version control style, or to else to just mark lines that have been changed since notepad was last opened, would be good. Since it's very similar, I'm also just going to plug that I'd like this feature to not conflict with the functionality in #5813 (which I would choose over this feature if I had to).

This kind of feature would be really powerful for everybody!

**Comment by sasumner** [comment]
@weirdalsuperfan said

> lines that have been changed since notepad was last opened,

Not 100%, but I think the Compare plugin has a compare-current-buffer-with-file-on-disk option? It seems like that would meet this need.

**Comment by sasumner** [comment]
Personally I'd like to see this functionality in Notepad++, but it is going to require support from Scintilla first.  Closing for now with the possibility to reconsider if such Scintilla support appears.

**Comment by weirdalsuperfan** [comment]
Did support from Scintilla ever come?

**Comment by rdipardo** [comment]
> Did support from Scintilla ever come?

https://scintilla.org/ChangeHistory.html

**Comment by alankilborn** [comment]
>>Did support from Scintilla ever come?

>https://scintilla.org/ChangeHistory.html

Yea, but that looks like it is just talk, and fairly old talk at that.

For now I use the "Changed Lines" plugin; it does a workable job.  I'd be lost without the ability to see where I've made changes -- LOST!  In other words, I probably wouldn't be able to use Notepad++ and would have to see out a different editor.

**Comment by rdipardo** [comment]
@weirdalsuperfan, @alankilborn

This was [just announced](https://groups.google.com/g/scintilla-interest/c/IOozI1Jooic#:~:text=Added%20change%20history):

> • Scintilla 5.3.0
> • Added change history which can display document changes (modified, saved, ...) in the margin or in the text.

**Comment by joseramirezrk** [comment]
omg thank you so much

sorry for the delay in the answer, lately, everything takes longer than expected.

thanks!

**Comment by weirdalsuperfan** [comment]
Oh wait, so this has been added to Notepad++ as well, not just to Scintilla??

**Comment by pryrt** [comment]
> Oh wait, so this has been added to Notepad++ as well, not just to Scintilla??

Yes.  In [v8.4.6](https://github.com/notepad-plus-plus/notepad-plus-plus/wiki/Changes#846) in September 2022, just a few months after it was added to Scintilla.
