### ISSUE TITLE
Prevent the cursor from jumping into next line when marking whole line via line numbers

### ISSUE THREAD

**Issue by mfitzen** [notepad-plus-plus/notepad-plus-plus#593]
For example: I have a txt file with 3 lines. If i mark line 2 by
clicking the line number the cursor jumps into line 3. When i press
ctrl+c it will copy the newline character in line 3. When i paste the
copied line 2 into a plain file this files has 2 lines. The one with the
content of line 2 and a blank one (line 3). 

I would prefer if n++ could handle this like every other editor does. Mark the line via linenumbers and set the cursor at the end of this line

**Comment by Eldaw** [comment]
I agree

**Comment by Rikk** [comment]
Imo, you are wrong. It is default behavior even in MS Word since stone age.
If you want only the content of the line (without EOF characters), go to the desired line, press Home once, and then Shift+End. Btw, it doesn't work in Word, where it does the same as selecting entire line with click on left margin.

**Comment by mfitzen** [comment]
> What editor happens to do like you said?

This is handled well by the most editors i tried so far. You can try it yourself in ultraedit, pspad or gedit or emacs on linux for example.

**Comment by aaaxx** [comment]
Huh, Word has left stone age?;-)

**Comment by Rikk** [comment]
What about people using emacs, vim etc? Yea, stone age. Operating systems relying exclusively on command lines? Yea, stone age.
I say thanks for Windows trying to spread visual computing.
(even though it started doing some sh*t after Windows 7)

**Comment by Rikk** [comment]
@mfitzen 
PSPad looks a good editor, and its line selection behavior is interesting, but what advantage you see in not selecting EOL automatically vs. selecting?

**Comment by mfitzen** [comment]
@Rikk 
Well i often have to copy single lines and overwrite single lines in existing docs. And it sucks always to delete blank lines after pasting the content.

**Comment by Rikk** [comment]
> And it sucks always to delete blank lines after pasting the content.

Why it happens? Doesn't happen with me:
![593](https://cloud.githubusercontent.com/assets/2916485/9015712/2a6f86ca-37a1-11e5-883c-b7d69dde4bdc.gif)

**Comment by mfitzen** [comment]
Ok, i can reproduce that. Maybe i made a wrong example. Please try the following: 

Create a txt file with 3 lines. Click on line number 2 to mark the whole line. Press Ctrl+C to copy, place the cursor at the end of line 2 and press enter for a new line. After that press ctrl+v to paste the copied line. You`ll get the copied line in line 3 and a blank one in line 4.

BTW: What software do you use to generate those gifs?

**Comment by Rikk** [comment]
Yes, this should happen, but in your case, the correct way is placing the cursor at start of line 3 and paste, this way you don't even need to manually press enter.
Used Photoshop for the gif.

**Comment by mfitzen** [comment]
yes it is always a mater of practice, but as already said the most editors i tried so far handled it "like the way i do"

**Comment by Rikk** [comment]
Ok, let's wait to see what devs think, then...

**Comment by milipili** [comment]
AFAIK, when clicking on the gutter, the whole line (with line feed) is selected (thus copied). The cursor is often moved to the next line to indicate this fact (or maybe for code simplicity for copying the selected text).
So for me it is standard behavior if I am not wrong (but I have to admit its annoys me most of the time).

Anyway, if this behavior is annoying for some users, an option may probably be added.

**Comment by aaaxx** [comment]
Yes, please.

**Comment by mfitzen** [comment]
Yes, an option to prevent the cursor moving to the next line would be great!

**Comment by mfitzen** [comment]
>Anyway, if this behavior is annoying for some users, an option may probably be added.

Is there any hope to get this option soon?

Regards
Michael

**Comment by mfitzen** [comment]
Any news on this?

**Comment by MetaChuh** [comment]
we are closing this issue due to its age and multiple newer notepad++ versions since it was filed.

please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html).
if your issue persists, and it is still of relevance to you, please feel free to file a new issue.

thank you for your help and best regards.

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
```
[<kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd>](https://notepad-plus-plus.org/community/)

**Comment by Kornej** [comment]
[mfitzen](https://github.com/mfitzen) 
Thank you for told about the editors who do not capture a new string. It is a pity that NotePad ++ has not yet made a very necessary option.
