### ISSUE TITLE
The tab character displayed width is different with others

### ISSUE THREAD

**Issue by ChenYouRen** [notepad-plus-plus/notepad-plus-plus#5932]
### Description of the Issue

<pre>「&		邏輯運算子」</pre><p> The 2 tab characters showed blank width is shorter than Notepad(Windows) and Google drive preview.  (Now I founded)</p>
On Notepad++:
![OnNotepad++](https://user-images.githubusercontent.com/26375712/61573271-2f079b00-aade-11e9-90fa-56d3e0c43874.png)
![OnNotepad++2](https://user-images.githubusercontent.com/26375712/61573273-329b2200-aade-11e9-9e09-9debf6b6d5c0.png)

On Notepad(Windows):
![OnNotepad(Windows)](https://user-images.githubusercontent.com/26375712/61573266-1ac39e00-aade-11e9-8604-24d12a6ed522.png)

On Google Drive preview the .txt file:
![OnGoogleDrive](https://user-images.githubusercontent.com/26375712/61573290-7e4dcb80-aade-11e9-8521-b7d70cfa936e.png)

### Steps to Reproduce the Issue

Try to type or copy the words.

### Expected Behavior

As Notepad(Windows) and Google Drive preview show.

### Actual Behavior

Notepad++ show..

### Debug Information

Notepad++ v7.7.1 (64-bit)
Notepad(Windows) v6.1 (build 7601: SP1)

Windows 7 SP1 x64

**Comment by Ekopalypse** [comment]
But on notepad aand google it looks like the tab width is set to 4.
Did you try to set the same tab width on npp?

**Comment by dail8859** [comment]
As @Ekopalypse suggested you can modify the width of tab characters in Notepad++. I believe the built in Windows Notepad uses 8 for the width so try setting it to 8.
