### ISSUE TITLE
Add Apex language support

### ISSUE THREAD

**Issue by Varun200864** [notepad-plus-plus/notepad-plus-plus#5933]
### Description of the Issue
Request to add Apex language support

### Expected Behavior
Language should contain Apex in the list

### Actual Behavior
Does not have Apex in the Language menu

**Comment by Ekopalypse** [comment]
Is Apex supported by [scintilla](https://scintilla.org/)?

**Comment by donho** [comment]
@Varun200864  
> Is Apex supported by scintilla?

Please check it. If yes, please reopen this issue. Otherwise it won't be implemented.
