### ISSUE TITLE
[Feature Request] Enable second SQL keyword list

### ISSUE THREAD

**Issue by CurbedLarry** [notepad-plus-plus/notepad-plus-plus#5937]
### Description
Scintilla supports multiple keyword lists in its SQL lexer, however Notepad++ only passes one list. This means all SQL keywords have the same style. Ideally data types would be highlighted in a different style.

### Changes
I believe the changes required **might** be as simple as follow:

**stylers.model.xml**
Add:
`<WordsStyle name="KEYWORD2" styleID="16" fgColor="8000FF" bgColor="FFFFFF" fontName="" fontStyle="1" fontSize="" keywordClass="instre2" />`

**langs.model.xml**
Move data type keywords to a second keyword row:
`<Keywords name="instre2">bigint binary bit ... varchar xml</Keywords>`

**ScintillaEditView.h**
Edit: `setLexer(SCLEX_SQL, L_SQL, LIST_0);`
To: `setLexer(SCLEX_SQL, L_SQL, LIST_0 | LIST_1);`

### Debug Information
Notepad++ v7.7.1 (32-bit)
OS : Windows 10 (64-bit)

**Comment by xylographe** [comment]
Perhaps, the themes (`PowerEditor\installer\themes\*.xml`) should be adjusted too?

**Comment by Ekopalypse** [comment]
The lexer, currently, supports up to [8 wordlist](https://github.com/notepad-plus-plus/notepad-plus-plus/blob/master/scintilla/lexers/LexSQL.cxx#L263), why restricting to two?

**Comment by CurbedLarry** [comment]
> Perhaps, the themes (`PowerEditor\installer\themes\*.xml`) should be adjusted too?

Agree, all those theme files could be updated too.

> The lexer, currently, supports up to [8 wordlist](https://github.com/notepad-plus-plus/notepad-plus-plus/blob/master/scintilla/lexers/LexSQL.cxx#L263), why restricting to two?

The 3rd and 4th keyword lists are aimed at Oracle syntax. I don't know if they could be skipped? I would just be happy give data types a different colour.  Another colour for functions would be nice but trying to limit scope of the change.

**Comment by Ekopalypse** [comment]
I don't think that it must be skipped. If the 3rd + 4th list doesn't contain any words it doesn't trigger anything. Would you mind giving a short example and explanation which parts should be colored how then I would give it a try. I don't have any SQL skills. But if you say you want to keep your changes as you've posted, I'm fine with it as well :-)

**Comment by CurbedLarry** [comment]
Hi,

Attaching my new **langs** file, expanded with more keywords and data types split into second keyword list:

[langs.model-TwoKeywordListSQL.xml.txt](https://github.com/notepad-plus-plus/notepad-plus-plus/files/3417769/langs.model-TwoKeywordListSQL.xml.txt)

Also a sample SQL script. the data types (INT, VARCHAR, DATETIME, etc...) would be a different colour to (CREATE, TABLE, IDENTITY, GO, etc...):

[Sample-SQL-Script.sql.txt](https://github.com/notepad-plus-plus/notepad-plus-plus/files/3417768/Sample-SQL-Script.sql.txt)

Not sure what colour would work best with each theme, maybe red (FF0000) for the default?

Thanks!

**Comment by Ekopalypse** [comment]
Thanks - gimme 1 or days 2 for testing, I will report back to this thread.

**Comment by xylographe** [comment]
Theme **Deep Black**, `fgColor="66FF00"`?
```
            <WordsStyle name="KEYWORD" styleID="5" fgColor="00FFFF" bgColor="000000" fontName="" fontStyle="1" fontSize="" keywordClass="instre1" />
            <WordsStyle name="KEYWORD2" styleID="16" fgColor="66FF00" bgColor="000000" fontName="" fontStyle="1" fontSize="" keywordClass="instre2" />
```

**Comment by xylographe** [comment]
@CurbedLarry 
It would seem that **`structured`** and **`varchar2`** are missing from the data type (`instre2`) list in `langs.model-TwoKeywordListSQL.xml`?

**Comment by CurbedLarry** [comment]
> Theme **Deep Black**, `fgColor="66FF00"`?

Personaly I use **Plastic Code Wrap** and haven't really thought about colours for other themes!

> It would seem that **`structured`** and **`varchar2`** are missing from the data type (`instre2`) list in `langs.model-TwoKeywordListSQL.xml`?

Oh I missed that STRUCTURE is an Oracle data type and not sure where VARCHAR2 went... I'll double check the list in the next hour or two and see if any for SQL Server, Oracle or MySQL are missing.

**Comment by xylographe** [comment]
A picture is worth a thousand words, :)

![Sample-SQL-Script sql](https://user-images.githubusercontent.com/8535293/61695352-a2eeb100-ad33-11e9-976b-f09dca32f829.png)

**Comment by Ekopalypse** [comment]
I see, @xylographe did it also - nice :-)
From first test it doesn't seem to be a problem defining PLDOC and SQL*PLUS without having keywords set. USER4 keywords seems to need further investigation. Npp defines only instre1, instre2 and type1 to type5.

![image](https://user-images.githubusercontent.com/47723516/61696061-2a342880-ad24-11e9-906d-34bf2868953b.png)

**Comment by CurbedLarry** [comment]
Thanks, not sure about that purple colour but maybe looks better with a dark theme?

I can't actually find the usage of STRUCTURE or STRUCTURED in SQL.

For now here's a vastly improved **langs** file.  I've moved a lot of Oracle data types out of the main keyword list and added many more from MySQL.  Also move TABLE back to a regular keyword from the data type list.

[langs.model-TwoKeywordListSQL-v2.xml.txt](https://github.com/notepad-plus-plus/notepad-plus-plus/files/3420994/langs.model-TwoKeywordListSQL-v2.xml.txt)

The total number of keywords is 763 versus 577 in the current Notepad++ release.

**Comment by xylographe** [comment]
Ty, @CurbedLarry 

Just to be absolutely sure, the words **`udt`** and **`variant`** are neither keywords nor data types?

The purple colour is `fgColor="8000FF"` from above. I agree that the colour from @Ekopalypse is looking better.

**Comment by CurbedLarry** [comment]
> Just to be absolutely sure, the words **`udt`** and **`variant`** are neither keywords nor data types?

A quick bit of research says no, where have you found those?
 
> The word **`precision`** is in both lists, I assume it is a keyword (first list)?

It's used by Oracle in data type definition so I would go with data type list.  Spotted a couple of other mistakes so here's version 3.  The lists should be pretty accurate now for 99.9% of SQL in use :-)

[langs.model.xml-TwoKeywordListSQL-v3.txt](https://github.com/notepad-plus-plus/notepad-plus-plus/files/3421701/langs.model.xml-TwoKeywordListSQL-v3.txt)

**Comment by Ekopalypse** [comment]
@CurbedLarry - the sql lexer expects this order of provided wordlists
`	case 0:
		wordListN = &keywords1;
		break;
	case 1:
		wordListN = &keywords2;
		break;
	case 2:
		wordListN = &kw_pldoc;
		break;
	case 3:
		wordListN = &kw_sqlplus;
		break;
	case 4:
		wordListN = &kw_user1;
		break;
	case 5:
		wordListN = &kw_user2;
		break;
	case 6:
		wordListN = &kw_user3;
		break;
	case 7:
		wordListN = &kw_user4;`

and those are described as
`	"Keywords",
	"Database Objects",
	"PLDoc",
	"SQL*Plus",
	"User Keywords 1",
	"User Keywords 2",
	"User Keywords 3",
	"User Keywords 4",
	0`

So if User Keywords are desired, my understanding is that PLDoc and SQL*Plus needs to be, at least, defined/configured but could be empty.
Concerning the additional colors I would say as you are the FR author it is your choice to define them 
if you like.
Btw. the lexer supports 23 different styles (id 12 and 14 are missing !?), something more to do?
`#define SCE_SQL_DEFAULT 0
#define SCE_SQL_COMMENT 1
#define SCE_SQL_COMMENTLINE 2
#define SCE_SQL_COMMENTDOC 3
#define SCE_SQL_NUMBER 4
#define SCE_SQL_WORD 5
#define SCE_SQL_STRING 6
#define SCE_SQL_CHARACTER 7
#define SCE_SQL_SQLPLUS 8
#define SCE_SQL_SQLPLUS_PROMPT 9
#define SCE_SQL_OPERATOR 10
#define SCE_SQL_IDENTIFIER 11
#define SCE_SQL_SQLPLUS_COMMENT 13
#define SCE_SQL_COMMENTLINEDOC 15
#define SCE_SQL_WORD2 16
#define SCE_SQL_COMMENTDOCKEYWORD 17
#define SCE_SQL_COMMENTDOCKEYWORDERROR 18
#define SCE_SQL_USER1 19
#define SCE_SQL_USER2 20
#define SCE_SQL_USER3 21
#define SCE_SQL_USER4 22
#define SCE_SQL_QUOTEDIDENTIFIER 23
#define SCE_SQL_QOPERATOR 24`

**Comment by xylographe** [comment]
@CurbedLarry 
Both **`udt`** and **`variant`** were in `langs.xml`, but not in `langs.model.xml`. Obviously, I need to update `langs.xml` more frequently. :)

**Comment by CurbedLarry** [comment]
@Ekopalypse You were saying NP++ only supports 7 keyword classes so I think it would be far more work to implement all options in the lexer.

How is this for a simple-but-flexible compromise that skips the Oracle lists:

- KEYWORD - instre1 (Non-data type list)
- KEYWORD2 - type1 (Data type list)
- USER1 - instre2 (Blank list by default, user can define)

Still lots of work to select 2 new colours for 20 standard themes, but 7x20 would be worse!

**Comment by CurbedLarry** [comment]
In addition to above I would propose these colours for KEYWORD2, with USER1 being the same colour as KEYWORD1:

stylers.xml	FF0000
Bespin.xml	FF8080
Black board.xml	FF8080
Choco.xml	FF8080
Deep Black.xml	FF8080
Hello Kitty.xml	FF0000
HotFudgeSundae.xml	FF8080
khaki.xml	FF0000
Mono Industrial.xml	C0C0C0
Monokai.xml	FF8080
MossyLawn.xml	FF8080
Navajo.xml	FF0000
Obsidian.xml	FF0000
Plastic Code Wrap.xml	FF8080
Ruby Blue.xml	FF8080
Solarized-light.xml	FF8080
Solarized.xml	FF8080
Twilight.xml	FF8080
Vibrant Ink.xml	FF8080
vim Dark Blue.xml	FF8080
Zenburn.xml	FF8080

**Comment by Ekopalypse** [comment]
@CurbedLarry, yes, npp, currently, defines a max of seven keywordlists, the lexer has 8 defined.
Adding an additional keywordlist to npp is as easy as adding, as far as I remember, another variable to 3 different places.
There was a misunderstanding about the preferred colors. What I tried to say is that you might chose the colors you want in your preferred style and I would have adapted it to the other styles. If you work in more then one style you can, of course, define them their as well but this is not what I expected.
The additional styles I posted are already in the lexer and we can at least define them in the same color as the default color, then those are available for one who wants to have it. What do you think?

**Comment by CurbedLarry** [comment]
@Ekopalypse OK, I think FF8080 is my option for the theme I use (**Plastic Code Wrap**) and works with most other themes.

Enabling all lexer options would be nice but if the Oracle styles are visible then users will expect them to work "out of the box".  So it would make sense to define the PLDoc/SQL*Plus keywords... Not sure how much work that is? I can attempt but I'm a SQL Server guy :-)

PLDoc: [http://pldoc.sourceforge.net/maven-site/docs/Users_Guide/index.html](url)
SQL*Plus: [https://docs.oracle.com/cd/B28359_01/server.111/b28285/sqlqraa.htm#i634619](url)

No idea what you would even pass into the lexer for PLDoc!  Don't think there has ever been a request for special Oracle highlighting so I say skip them.

**Comment by Ekopalypse** [comment]
@CurbedLarry - thank you for the links. As I'm currently not at home I have some time to read and try to understand what it is all about. I will prepare the changes and will test it next week.
I will keep you updated.

**Comment by xylographe** [comment]
I tried, (`langs.xml`)
```xml
        <Language name="sql" ext="sql" commentStart="/*" commentEnd="*/" commentLine="--">
            <Keywords name="instre1">abs absolute access acos add add_months adddate admin after aggregate all allocate alter and any app_name applock_mode applock_test are array as asc ascii asin assemblyproperty assertion asymkey_id at atan atn2 audit authid authorization autonomous_transaction avg backup before begin benchmark between bfilename bin binary_checksum bit_and bit_count bit_or body both breadth break browse bulk by call cascade cascaded case cast catalog catch ceil ceiling cert_id certproperty character charindex chartorowid check checkpoint checksum checksum_agg chr class clause close cluster clustered coalesce col_length col_name collate collation collect column columnproperty columns_updated comment commit completion compress compute concat concat_ws connect connection connectionproperty constant constraint constraints constructorcreate contains containsable containstable context_info continue conv convert corr corresponding cos cot count count_big covar_pop covar_samp create cross cube cume_dist current current_date current_path current_request_id current_role current_time current_timestamp current_user currval cursor_status cycle data database database_principal_id databasepropertyex datalength date_add date_format date_sub dateadd datediff datefirst dateformat datename datepart db_id db_name dbcc deallocate declare decode decryptbyasmkey decryptbycert decryptbykey decryptbykeyautocert decryptbypassphrase default deferrable deferred degrees delete dense_rank deny depth deref desc describe descriptor destroy destructor deterministic diagnostics dictionary difference disconnect disk distinct distributed do domain drop dump dynamic each else elsif empth encode encrypt encryptbyasmkey encryptbycert encryptbykey encryptbypassphrase end end-exec equals errlvl error_line error_message error_number error_procedure error_severity error_state escape eventdata every except exception exclusive exec execute exists exit exp export_set extends external extract false fetch file file_id file_idex file_name filegroup_id filegroup_name filegroupproperty fileproperty fillfactor first first_value floor fn_virtualfilestats for forall foreign format formatmessage found freetext freetexttable from from_days full fulltextcatalog fulltextcatalogproperty fulltextservice fulltextserviceproperty function general get get_filestream_transaction_context get_lock getansinull getdate getutcdate global go goto grant greatest group grouping grouping_id has_perms_by_name hashbytes having heap hex hextoraw holdlock host host_id host_name hour ident_current ident_incr ident_seed identified identity identity_insert identitycol if ifnull ignore immediate in include increment index index_col indexkey_property indexproperty indicator initcap initial initialize initially inner inout input insert instr instrb interface intersect into is is_member is_null is_numeric is_srvrolemember isdate isnull isnumeric isolation iterate java join key key_guid key_id kill lag language large last last_day last_value lateral lcase lead leading least left len length lengthb less level like limit limited lineno ln load local localtime localtimestamp locator lock log log10 loop lower lpad ltrim make_ref map match max maxextents merge mid min min_active_rowversion minus minute mlslabel mod mode modifies modify module month months_between names national natural naturaln new new_time newid newsequentialid next next_day nextval no noaudit nocheck nocompress nocopy nonclustered none not nowait ntile null nullif number_base nvl nvl2 object object_definition object_id object_name object_property object_schema_name objectproperty objectpropertyex ocirowid oct of off offline offsets old on online only opaque open opendatasource openquery openrowset openxml operation operator option or ord order ordinalityorganization original_db_name original_login others out outer output over package pad parameter parameters parsename partial partition path pathname patindex pctfree percent percent_rank permissions pi pivot plan pls_integer positive positiven postfix pow power pragma prefix preorder prepare preserve primary print prior private privileges proc procedure public publishingservername pwdcompare pwdencrypt quotename radians raise raiserror rand range rank ratio_to_export rawtohex read reads readtext reconfigure record recursive ref references referencing reftohex relative release release_lock rename repeat replace replicate replication resource restore restrict result return returns reverse revert revoke right rollback rollup round routine row row_number rowcount rowcount_big rowguidcol rowidtochar rowlabel rownum rows rowtype rpad rtrim rule save savepoint schema schema_id schema_name scope scope_identity scroll search second section securityaudit seddev_samp select separate sequence serverproperty session session_user set sets setuser share shutdown sign signbyasymkey signbycert sin sinh size some soundex sp_helplanguage space specific specifictype sql sql_variant_property sqlcode sqlerrm sqlexception sqlstate sqlwarning sqrt square start state statement static statistics stats_date std stddev stdev stdev_pop stdevp str strcmp structure stuff subdate substr substrb substring substring_index subtype successful sum suser_id suser_name suser_sid suser_sname switchoffset synonym sys_context sys_guid sysdate sysdatetime sysdatetimeoffset system_user sysutcdatetime table tablesample tan tanh temporary terminate textptr textsize textvalid than then timezone_abbr timezone_hour timezone_minute timezone_region to to_char to_date to_days to_number to_single_byte todatetimeoffset top trailing tran transaction translate translation treat trigger trigger_nestlevel trim true trunc truncate try tsequal type type_id type_name typeproperty ucase uid under unicode union unique unknown unnest unpivot update updatetext upper usage use user user_id user_name userenv using validate value values var var_pop var_samp variable variance varp varying verifysignedbyasmkey verifysignedbycert view vsize waitfor when whenever where while with without work write writetext xact_state zone</Keywords>
            <Keywords name="instre2" />
            <Keywords name="type1">bfile bigint binary binary_integer bit blob bool boolean char char_base clob cursor date datetime datetime2 datetimeoffset day dec decimal double enum float hierarchyid image int integer interval long longblob longtext mediumblob mediumint mediumtext money nchar nclob ntext number numeric nvarchar precision raw real rowid smalldatetime smallint smallmoney sql_variant text time timestamp tinyblob tinyint tinytext uniqueidentifier urowid varbinary varchar varchar2 xml year</Keywords>
        </Language>
```
and, (`stylers.xml`)
```xml
        <LexerType name="sql" desc="SQL" ext="">
            <WordsStyle name="KEYWORD" styleID="5" fgColor="0000FF" bgColor="FFFFFF" fontName="" fontStyle="1" fontSize="" keywordClass="instre1" />
            <WordsStyle name="USER1" styleID="19" fgColor="0000FF" bgColor="FFFFFF" fontName="" fontStyle="1" fontSize="" keywordClass="instre2" />
            <WordsStyle name="KEYWORD2" styleID="16" fgColor="FF0000" bgColor="FFFFFF" fontName="" fontStyle="0" fontSize="" keywordClass="type1" />
            <WordsStyle name="NUMBER" styleID="4" fgColor="FF8000" bgColor="FFFFFF" fontName="" fontStyle="0" fontSize="" />
            <WordsStyle name="STRING" styleID="6" fgColor="808080" bgColor="FFFFFF" fontName="" fontStyle="0" fontSize="" />
            <WordsStyle name="STRING2" styleID="7" fgColor="808080" bgColor="FFFFFF" fontName="" fontStyle="0" fontSize="" />
            <WordsStyle name="OPERATOR" styleID="10" fgColor="000080" bgColor="FFFFFF" fontName="" fontStyle="1" fontSize="" />
            <WordsStyle name="COMMENT" styleID="1" fgColor="008000" bgColor="FFFFFF" fontName="" fontStyle="0" fontSize="" />
            <WordsStyle name="COMMENT LINE" styleID="2" fgColor="008000" bgColor="FFFFFF" fontName="" fontStyle="0" fontSize="" />
            <WordsStyle name="COMMENT DOC" styleID="3" fgColor="008000" bgColor="FFFFFF" fontName="" fontStyle="0" fontSize="" />
            <WordsStyle name="Q OPERATOR" styleID="24" fgColor="808080" bgColor="FFFFFF" fontName="" fontStyle="0" fontSize="" />
        </LexerType>
```
Unfortunately, the result is not as expected,

![Sample-SQL-Script sql](https://user-images.githubusercontent.com/8535293/61971704-fedd6200-afdf-11e9-960d-1c6d635ebf3c.png)

What am I missing?

**Comment by Ekopalypse** [comment]
Did you [add another list to the lexer](https://github.com/notepad-plus-plus/notepad-plus-plus/blob/master/PowerEditor/src/ScitillaComponent/ScintillaEditView.h#L734)?

**Comment by xylographe** [comment]
Yes, I did,
```c++
setLexer(SCLEX_SQL, L_SQL, LIST_0 | LIST_1 | LIST_2);
```
Full changes in [branch sql2](https://github.com/xylographe/notepad-plus-plus/tree/sql2) ([diffs against master](https://github.com/notepad-plus-plus/notepad-plus-plus/compare/master...xylographe:sql2)).

**Comment by Ekopalypse** [comment]
Ahh, yes, I see, I guess :-)
This 3rd and 4th are the mysterious oracle ones which have additional lexing requirements.
See [here](https://github.com/notepad-plus-plus/notepad-plus-plus/blob/master/scintilla/lexers/LexSQL.cxx#L459). From my understanding you would need to define 
`setLexer(SCLEX_SQL, L_SQL, LIST_0 | LIST_1 | LIST_2 | LIST_3 | LIST_4);`
where LIST_4 would be the first user list.

**Comment by xylographe** [comment]
I tried
 `setLexer(SCLEX_SQL, L_SQL, LIST_0 | LIST_1 | LIST_2 | LIST_3 | LIST_4)`, and
 `setLexer(SCLEX_SQL, L_SQL, LIST_0 | LIST_1 | LIST_2 | LIST_3 | LIST_4 | LIST_5 | LIST_6)`.
No luck. :(

After adding the word `patientid` to USER1 in `stylers.xml`,
```xml
<WordsStyle name="USER1" styleID="19" fgColor="0000FF" bgColor="FFFFFF" fontName="" fontStyle="1" fontSize="" keywordClass="instre2">patientid</WordsStyle>
```
I get the following (unexpected) result,

![Sample-SQL-Script sql](https://user-images.githubusercontent.com/8535293/61997975-70cdae00-b0a9-11e9-9671-6bec082d9dee.png)

Note that **`PatientID`** is red, not blue.

**Comment by Ekopalypse** [comment]
I would expect a configuration like this, if I can remember correctly what I've done

```
 <Language name="sql" ext="sql" commentStart="/*" commentEnd="*/" commentLine="--">
            <Keywords name="instre1">abs absolute ... </Keywords>
            <Keywords name="instre2" />
            <Keywords name="type1" /<   <--- first oracle ...
            <Keywords name="type2" /<   <--- second oracle ...
            <Keywords name="type3" /<   <--- first user ...
</Language>
```

```
<WordsStyle name="USER1" styleID="19" fgColor="0000FF" bgColor="FFFFFF" fontName="" fontStyle="1" fontSize="" keywordClass="type3">patientid</WordsStyle>
```

**Comment by xylographe** [comment]
Thank you, @Ekopalypse !

`langs.xml` (`type3` i/o `type1`)
```xml
<Keywords name="instre1">abs absolute access acos add add_months adddate admin after aggregate all allocate alter and any app_name applock_mode applock_test are array as asc ascii asin assemblyproperty assertion asymkey_id at atan atn2 audit authid authorization autonomous_transaction avg backup before begin benchmark between bfilename bin binary_checksum bit_and bit_count bit_or body both breadth break browse bulk by call cascade cascaded case cast catalog catch ceil ceiling cert_id certproperty character charindex chartorowid check checkpoint checksum checksum_agg chr class clause close cluster clustered coalesce col_length col_name collate collation collect column columnproperty columns_updated comment commit completion compress compute concat concat_ws connect connection connectionproperty constant constraint constraints constructorcreate contains containsable containstable context_info continue conv convert corr corresponding cos cot count count_big covar_pop covar_samp create cross cube cume_dist current current_date current_path current_request_id current_role current_time current_timestamp current_user currval cursor_status cycle data database database_principal_id databasepropertyex datalength date_add date_format date_sub dateadd datediff datefirst dateformat datename datepart db_id db_name dbcc deallocate declare decode decryptbyasmkey decryptbycert decryptbykey decryptbykeyautocert decryptbypassphrase default deferrable deferred degrees delete dense_rank deny depth deref desc describe descriptor destroy destructor deterministic diagnostics dictionary difference disconnect disk distinct distributed do domain drop dump dynamic each else elsif empth encode encrypt encryptbyasmkey encryptbycert encryptbykey encryptbypassphrase end end-exec equals errlvl error_line error_message error_number error_procedure error_severity error_state escape eventdata every except exception exclusive exec execute exists exit exp export_set extends external extract false fetch file file_id file_idex file_name filegroup_id filegroup_name filegroupproperty fileproperty fillfactor first first_value floor fn_virtualfilestats for forall foreign format formatmessage found freetext freetexttable from from_days full fulltextcatalog fulltextcatalogproperty fulltextservice fulltextserviceproperty function general get get_filestream_transaction_context get_lock getansinull getdate getutcdate global go goto grant greatest group grouping grouping_id has_perms_by_name hashbytes having heap hex hextoraw holdlock host host_id host_name hour ident_current ident_incr ident_seed identified identity identity_insert identitycol if ifnull ignore immediate in include increment index index_col indexkey_property indexproperty indicator initcap initial initialize initially inner inout input insert instr instrb interface intersect into is is_member is_null is_numeric is_srvrolemember isdate isnull isnumeric isolation iterate java join key key_guid key_id kill lag language large last last_day last_value lateral lcase lead leading least left len length lengthb less level like limit limited lineno ln load local localtime localtimestamp locator lock log log10 loop lower lpad ltrim make_ref map match max maxextents merge mid min min_active_rowversion minus minute mlslabel mod mode modifies modify module month months_between names national natural naturaln new new_time newid newsequentialid next next_day nextval no noaudit nocheck nocompress nocopy nonclustered none not nowait ntile null nullif number_base nvl nvl2 object object_definition object_id object_name object_property object_schema_name objectproperty objectpropertyex ocirowid oct of off offline offsets old on online only opaque open opendatasource openquery openrowset openxml operation operator option or ord order ordinalityorganization original_db_name original_login others out outer output over package pad parameter parameters parsename partial partition path pathname patindex pctfree percent percent_rank permissions pi pivot plan pls_integer positive positiven postfix pow power pragma prefix preorder prepare preserve primary print prior private privileges proc procedure public publishingservername pwdcompare pwdencrypt quotename radians raise raiserror rand range rank ratio_to_export rawtohex read reads readtext reconfigure record recursive ref references referencing reftohex relative release release_lock rename repeat replace replicate replication resource restore restrict result return returns reverse revert revoke right rollback rollup round routine row row_number rowcount rowcount_big rowguidcol rowidtochar rowlabel rownum rows rowtype rpad rtrim rule save savepoint schema schema_id schema_name scope scope_identity scroll search second section securityaudit seddev_samp select separate sequence serverproperty session session_user set sets setuser share shutdown sign signbyasymkey signbycert sin sinh size some soundex sp_helplanguage space specific specifictype sql sql_variant_property sqlcode sqlerrm sqlexception sqlstate sqlwarning sqrt square start state statement static statistics stats_date std stddev stdev stdev_pop stdevp str strcmp structure stuff subdate substr substrb substring substring_index subtype successful sum suser_id suser_name suser_sid suser_sname switchoffset synonym sys_context sys_guid sysdate sysdatetime sysdatetimeoffset system_user sysutcdatetime table tablesample tan tanh temporary terminate textptr textsize textvalid than then timezone_abbr timezone_hour timezone_minute timezone_region to to_char to_date to_days to_number to_single_byte todatetimeoffset top trailing tran transaction translate translation treat trigger trigger_nestlevel trim true trunc truncate try tsequal type type_id type_name typeproperty ucase uid under unicode union unique unknown unnest unpivot update updatetext upper usage use user user_id user_name userenv using validate value values var var_pop var_samp variable variance varp varying verifysignedbyasmkey verifysignedbycert view vsize waitfor when whenever where while with without work write writetext xact_state zone</Keywords>
<Keywords name="instre2" />
<Keywords name="type3">bfile bigint binary binary_integer bit blob bool boolean char char_base clob cursor date datetime datetime2 datetimeoffset day dec decimal double enum float hierarchyid image int integer interval long longblob longtext mediumblob mediumint mediumtext money nchar nclob ntext number numeric nvarchar precision raw real rowid smalldatetime smallint smallmoney sql_variant text time timestamp tinyblob tinyint tinytext uniqueidentifier urowid varbinary varchar varchar2 xml year</Keywords>
```
`stylers.xml` (USER1: `styleID="16"` i/o `styleID="19"`; KEYWORD2: `styleID="19"` i/o `styleID="16"`)
```xml
<WordsStyle name="KEYWORD" styleID="5" fgColor="0000FF" bgColor="FFFFFF" fontName="" fontStyle="1" fontSize="" keywordClass="instre1" />
<WordsStyle name="USER1" styleID="16" fgColor="0000FF" bgColor="FFFFFF" fontName="" fontStyle="1" fontSize="" keywordClass="instre2">patientid</WordsStyle>
<WordsStyle name="KEYWORD2" styleID="19" fgColor="FF0000" bgColor="FFFFFF" fontName="" fontStyle="0" fontSize="" keywordClass="type3" />
```
Result,

![Sample-SQL-Script sql](https://user-images.githubusercontent.com/8535293/61999764-5820c080-b0c8-11e9-96ef-be700f4995e2.png)

:1st_place_medal:

**Comment by Ekopalypse** [comment]
Ok, so does that mean that by skipping type1 and 2 we get rid of those oracle ...?

**Comment by xylographe** [comment]
Apparently, yes,
```
setLexer(SCLEX_SQL, L_SQL, LIST_0 | LIST_1 | LIST_4);
```
in combination with `keywordClass="type3"` leads to the desired result.

I also tried,
```
setLexer(SCLEX_SQL, L_SQL, LIST_0 | LIST_1 | LIST_2 | LIST_3 | LIST_4 | LIST_5 | LIST_6);
```
in combination with `keywordClass="type[12345]"`.
`keywordClass="type3"` is OK,`keywordClass="type[1245]"` are not.

**Comment by CurbedLarry** [comment]
Interesting, digging into the code this is how **keywordClass** gets assigned to the **LIST_*** variables passed to the lexer:

instre1 --> LIST_0
instre2 --> LIST_1
type1 ---> LIST_2
type2 ---> LIST_3
type3 ---> LIST_4
type4 ---> LIST_5
type5 ---> LIST_6

No difference between **instre*** and **type***, they're handled exactly the same way.

**Comment by Ekopalypse** [comment]
@donho - as far as I understood the contributing guidelines you want to label a feature request as accepted before a PR should be made, which is ok for me but on the other side we don't know what the status is when leaving such a FR unlabeled. May I kindly ask your opinion on this and whether this FR gets accepted? 

One other thing, while working on this I discovered that the default styler and the themes are out of sync and the default styles are out of sync with the current scintilla version.
I would like to offer to bring it in sync again.
I would prefer to have three different PRs, 
The first one which updates the default styler to the state of the current scintilla version
the second one for this FR doing the setLexer specific changes and
the third one which updates the themes accordingly.
What do you think?

**Comment by sasumner** [comment]
Well, *I* think:

>understood the contributing guidelines you want to label a feature request as accepted before a PR

This is ideal as it indicates agreement that feature is valuable and belongs in N++ and that effort put into PR will likely not be wasted.  But...in practice this does not often happen.  

When I create an issue myself, I mark it accepted...cuz I can. :)

>I would prefer to have three different PRs

I love it.  In general it probably improves likelihood of PR acceptance.  Smaller changes are always better.  Of course the waters get muddy if the things are somewhat interdependent...

**Comment by Ekopalypse** [comment]
>But...in practice this does not often happen.
You just have to live it :-), FRs could be marked as **accepted but won't work myself on it** as well to make clear someone else needs to jump in and Don isn't the one to blame when it doesn't get done.

**Comment by xylographe** [comment]
Perhaps, if an FR isn't closed within 7‒10 days, you may assume that a corresponding PR has a reasonable chance of being accepted?

**Comment by sasumner** [comment]
>marked as accepted but won't work myself on it as well to make clear someone else needs to jump in

There is also an "assigned to" thing; again rarely used.  We're trying to be more rigorous here, but...  I'd say things are getting better, though.

Anyway, currently if someone wants to jump in and work on something, the can certainly say so in a comment.  :)

>Don isn't the one to blame

Don is always blameless...haven't you heard of "Teflon Don"? :)  Note, not comparing our Don to american mafia, just referencing this part: "The American media dubbed Gotti "The Teflon Don" in reference to the failure of any charges to 'stick.'"

**Comment by sasumner** [comment]
>Perhaps, if an FR isn't closed within 7‒10 days, you may assume that a corresponding PR has a reasonable chance of being accepted?

I don't know that I would operate under that assumption.  It is going to depend greatly upon what it is, how much risk there is to it, and Don's whim. :)

**Comment by Ekopalypse** [comment]
Just a reminder that some theme files do have additional useless content or content
where it shouldn't be, for example HotFudgeSundae.xml has this 
<WordsStyle name="INSTRUCTION WORD" ... keywordClass="instre1">ooooo</WordsStyle>
and that
<WordsStyle name="COMMENT DOC KEYWORD" ... fontSize="">param @projectDescription projectDescription @param</WordsStyle>
and a few others.

**Comment by krptodr** [comment]
> @Ekopalypse OK, I think FF8080 is my option for the theme I use (**Plastic Code Wrap**) and works with most other themes.
> 
> Enabling all lexer options would be nice but if the Oracle styles are visible then users will expect them to work "out of the box". So it would make sense to define the PLDoc/SQL*Plus keywords... Not sure how much work that is? I can attempt but I'm a SQL Server guy :-)
> 
> PLDoc: [http://pldoc.sourceforge.net/maven-site/docs/Users_Guide/index.html](url)
> SQL*Plus: [https://docs.oracle.com/cd/B28359_01/server.111/b28285/sqlqraa.htm#i634619](url)
> 
> **No idea what you would even pass into the lexer for PLDoc! Don't think there has ever been a request for special Oracle highlighting so I say skip them.**

Consider the request being made...... Now! :grin:
