### ISSUE TITLE
I can't download N++

### ISSUE THREAD

**Issue by NanhuGITHUB** [notepad-plus-plus/notepad-plus-plus#5939]
### Description of the Issue
It won't download. It just shows a  error message

### Steps to Reproduce the Issue
1. Go onto the download section of the website
2. Try to download any package

### Expected Behavior
It should download

### Actual Behavior
There was a error

**Comment by NanhuGITHUB** [comment]
More info:
Guru Meditation: XID: 147885416
Error: 503

**Comment by shameerkc** [comment]
Facing the same issue... The issue is present not only for the latest version, but also old versions as well...

**Comment by RichieRich023** [comment]
Same here, i get the error page as well.

**Comment by sasumner** [comment]
You guys ever hear of a server being down?  I don't think it qualifies as a "software issue", which is what this list is for.

**Comment by DeltaFiredash** [comment]
The error is a 503, which indicates "Service Unavailable", hope this issue gets fixed soon.

**Comment by HXHL** [comment]
Me too : (

**Comment by NanhuGITHUB** [comment]
ill check if it's fixed

**Comment by NanhuGITHUB** [comment]
:cry:

**Comment by donho** [comment]
https://github.com/notepad-plus-plus/notepad-plus-plus/issues/5942

**Comment by donho** [comment]
Notepad++ website is restored now.
