### ISSUE TITLE
SQL Language Colorizing Display Issue

### ISSUE THREAD

**Issue by puffgroovy** [notepad-plus-plus/notepad-plus-plus#5940]
### Description of the Issue

When using a single quote within an AS bracket, 

SELECT FIELD1 AS [FIELD'1]

The colorization is thrown off and turns grey. Some queries contain single quotes such as [Child's Name] for report display purposes in SSRS.

### Steps to Reproduce the Issue

1. Simply copy and paste this code into the editor and change the language indicator to SQL if needed and notice the color display. Once the single quote is removed, the color returns to normal for SQL syntax

SELECT FIELD1 AS [FIELD1]
            ,FIELD2 AS [FIELD2]
	    ,CHILD1_NAME AS [Child1 Name]
	    ,CHILD2_NAME AS [Child's Name]
	    ,FIELD3 AS [FIELD3]
FROM TABLE1
;

### Expected Behavior

Color should be normal SQL color when single quotes exist inside of AS brackets.
### Actual Behavior

All text after the single quote turned grey.

### Debug Information

![SQLDisplayIssue](https://user-images.githubusercontent.com/11427861/61653907-58185f00-ac89-11e9-8f42-f5d374f6ce90.JPG)

**Comment by ArkadiuszMichalski** [comment]
@puffgroovy What database you used? There were no errors / warnings after executing the code? I can't find infos if all chars can be put inside `[]`. You can temporarily use "" instead of [].
https://docs.microsoft.com/en-us/sql/relational-databases/databases/database-identifiers?redirectedfrom=MSDN&view=sql-server-ver15

**Comment by puffgroovy** [comment]
There is no error executing the code. Only the display in the editor. Notice how the text turns grey after the single quote in [Child's Name]. The text should not grey, it should stay the same. That is the only issue. No database or code issues, just a display issue within Notepad ++

**Comment by vinsworldcom** [comment]
@sasumner

I can confirm this is NOT fixed in Notepad++ 7.9.3 Unicode Debug using the latest Scintilla 4.4.6 DLL.

Cheers.
