### ISSUE TITLE
Notepad++ download site is not reachable 

### ISSUE THREAD

**Issue by donho** [notepad-plus-plus/notepad-plus-plus#5942]
Notepad++ download site is not reachable due to a technical problem of one of our servers. We are working on it and will restore it ASAP. Sorry for the inconvenience.

**Comment by donho** [comment]
https://twitter.com/Notepad_plus/status/1153651104674209792

**Comment by shameerkc** [comment]
How about uploading the binaries as part of the releases from now on at [https://github.com/notepad-plus-plus/notepad-plus-plus/releases](https://github.com/notepad-plus-plus/notepad-plus-plus/releases)

Even if the site goes down, this provides people with an alternate option this way... :)

**Comment by NanhuGITHUB** [comment]
but once yesterday the repo itself went down for some time

but still i support that

**Comment by sasumner** [comment]
>How about uploading the binaries as part of the releases from now on at https://github.com/notepad-plus-plus/notepad-plus-plus/releases

It was stated before that this would cause too much bandwidth on github...and that would translate into too much money for the developer to have to shell out.  There's much less interest in the Notepad++ source code, so only it is on github.

**Comment by MegaMech** [comment]
Could you temporarily put the x64 binary of 7.1.1 on github or email it to me?

**Comment by xylographe** [comment]
Notepad++ 7.1.1 is available for download on [FossHub.](https://www.fosshub.com/Notepad-Plus-Plus.html)

**Comment by Brassfield** [comment]
> 
> 
> Notepad++ 7.1.1 is available for download on [FossHub.](https://www.fosshub.com/Notepad-Plus-Plus.html)

* 7.7.1 (the latest release)

**Comment by michal037** [comment]
download link is broken
![2019-07-24_19-19-30](https://user-images.githubusercontent.com/7441419/61814267-fc480480-ae47-11e9-8932-a57888903ff3.gif)

**Comment by donho** [comment]
Restored:
https://twitter.com/Notepad_plus/status/1154154853943435264

**Comment by donho** [comment]
@michal037 Please use the download button at the bottom of page.

**Comment by michal037** [comment]
@donho This is not a problem for me, I just report that it occurs.

**Comment by donho** [comment]
We are working on download link issue.

**Comment by donho** [comment]
Download link issue has been fixed.
