### ISSUE TITLE
N++ crashes when right-clicked in "Document List Panel"

### ISSUE THREAD

**Issue by outOfBoxTester** [notepad-plus-plus/notepad-plus-plus#5943]
### Description of the Issue
Upon right clicking on column "Name" in Document Panel List, notepad++ crashes

### Steps to Reproduce the Issue

1. Open Notepad++
2. Enable the Document Panel List view from Settings-->General-->Document Panel List
3. Once enabled right click on the column named "Name" in Doc Switcher
4. You will observe that notepad++ is crashing

### Expected Behavior
It should not crash atleast when right clicked on column name

### Actual Behavior
It crashed when right clicked on column name

### Debug Information
Notepad++ v7.5.9   (64-bit)
Build time : Oct 14 2018 - 15:19:55
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10 (64-bit)
Plugins : DSpellCheck.dll mimeTools.dll NppConverter.dll 

![notepad++bug](https://user-images.githubusercontent.com/53222357/61712836-d56cce00-ad74-11e9-8016-e457f227a92d.png)

**Comment by sasumner** [comment]
Retest on v.7.7.1.

**Comment by donho** [comment]
I cannot reproduce it on my latest version.
Please update your Notepad++ to v7.7.1.
If the problem persist, open a new issue with the new debug info.
