### ISSUE TITLE
Binary files is missing in Releases section

### ISSUE THREAD

**Issue by Neustradamus** [notepad-plus-plus/notepad-plus-plus#5946]
Only sourcecode in Releases section, can you add all binaries?
- https://github.com/notepad-plus-plus/notepad-plus-plus/releases

**Comment by sasumner** [comment]
No, see https://github.com/notepad-plus-plus/notepad-plus-plus/issues/5942#issuecomment-514245590

**Comment by ArkadiuszMichalski** [comment]
@donho Maybe close if you don't plan it?

**Comment by Neustradamus** [comment]
Note: It has been done a long time ago, after my request, there was a Notepad++ server problem and added after 7.7 release date:
- https://github.com/notepad-plus-plus/notepad-plus-plus/releases/tag/v7.7
- https://github.com/notepad-plus-plus/notepad-plus-plus/releases/tag/v7.6.6
- https://twitter.com/Notepad_plus/status/1154154853943435264

Linked to:
- https://github.com/notepad-plus-plus/notepad-plus-plus/issues/5939
- https://github.com/notepad-plus-plus/notepad-plus-plus/issues/5942

cc: @donho.
