### ISSUE TITLE
Problem with buttons in search dialog window

### ISSUE THREAD

**Issue by Neustradamus** [notepad-plus-plus/notepad-plus-plus#5947]
1/ In "Mark" tab, unfortunately I do not see "Find All in All Opened Documents", is it possible to add this missing part?
And rename "Find All" to "Find All in Current Opened Document"?

2/ Inversion of buttons between the part "Find" and "Replace" tabs: "Current Opened Document" and "All Opened Documents".
It is better to have "Current Document" in first and after "All Opened Documents"
It would also be good to specify "Replace All in Current Document" instead of "Replace All"

"Current search dialog window":

Find tab:
- Find Next
- Count
- Find All in All Opened Documents
- Find All in Current Document
- Close

Replace tab:
- Find Next
- Replace
- Replace All
- Replace All in All Opened Documents
- Close

Find in Files tab:
- Find All
- Replace in Files
- Close

Mark tab:
- Find All
- Clear
- Close

**Comment by sasumner** [comment]
> In "Mark" tab, unfortunately I do not see "Find All in All Opened Documents", is it possible to add this missing part

By design marking only is done in the currently active document.  It is doubtful that this will ever be expanded to do all open docs with one button press.

> And rename "Find All" to "Find All in Current Opened Document"?

Well, you as an end user can change the text that appears by editing the appropriate language XML file.  In this case, the button is small, though, and your longer text isn't going to fit.

>Inversion of buttons...It is better to have...

I'm sure many people like it the way it is...how to please everyone...hmmmm....

**Comment by Neustradamus** [comment]
@sasumner: It is not logic to have not in the same order and the same text name...

It is possible to change in the code directly?
Change position and text name?

**Comment by sasumner** [comment]
>It is possible to change in the code directly?

Notepad++ is open source, so yes, you can change it in the code to be how you want it...for yourself.  Otherwise, too many users are used to and comfortable with the way it currently is implemented for it to be changed.

Thanks for your comments, and best regards.

**Comment by Neustradamus** [comment]
I can create a PR? ^^

**Comment by sasumner** [comment]
You can create a PR but in this case it won't be accepted, for reasons already cited.  I mean to change your copy/fork of the code to be what you like, and then use it!

**Comment by Neustradamus** [comment]
It is not for me, it is for all users, because it is an interface problem :)

**Comment by Neustradamus** [comment]
@donho: About the email that I have done a long time ago.
Can you realize this change?

**Comment by sasumner** [comment]
>2/ Inversion of buttons between the part "Find" and "Replace" tabs: "Current Opened Document" and "All Opened Documents".  It is better to have "Current Document" in first and after "All Opened Documents"

#8413 makes this a reality

**Comment by Neustradamus** [comment]
@sasumner: Thanks!

It is possible to change "Replace All" by "Replace All in Current Document"?

**Comment by sasumner** [comment]
@Neustradamus 
This won't be changed for N++ as shipped.
But, you can change it for your copy via the language translation capability.
If you want to do this but don't know how, post again.
