### ISSUE TITLE
[Feature Request] Disable File Status Autodetect when using monitoring

### ISSUE THREAD

**Issue by WizADSL** [notepad-plus-plus/notepad-plus-plus#5952]
I think it would be useful to disable the "File status autodetect" feature automatically for a file while the "monitoring (tail -f)" option is enabled for the file and return to the previous setting for "File status autodetect" when monitoring is disabled.  Currently, if you have change detection enabled and are using the monitor/tail option then both will trigger when a change occurs.

**Comment by luckydonald** [comment]
For me only the first triggers...

**Comment by donho** [comment]
@WizADSL 
> then both will trigger when a change occurs.

So what's the symptom ?

**Comment by luckydonald** [comment]
@donho 
The one is the tail system.
Just reloads the file in the editor.

The other is the one where the editor opens a dialog box asking

> Do you wanna
> reload da file?
>     **<kbd>Yes</kbd> <kbd>No</kbd>**

Obviously, if I already use the tail mode, I don't wanna have to click that <kbd>Yes</kbd> one, that's what tail should do for me anyway.
