### ISSUE TITLE
[Feature improvement]Fast files' search

### ISSUE THREAD

**Issue by rafi-d** [notepad-plus-plus/notepad-plus-plus#5953]
Hi,
Here is a suggestion for improving search speed for multiple (hundreds/thousands) files:
This will apply to normal/string searches (not regex). The "engine will be the Windows FAST findstr command.

1. Provide an option in the files' search - under  "Normal" - "Fast search"
2. This might be limited to only *one* file filter (cmd - compatible, not sure)
3. Execute findstr /s <path> <files-filter>
4. Parse the result output-files-list and show in the NP++ output search pane
5. Done... 

From experience this can be x10-50 faster then today's search, and very useful as an option for simple searches.

Can you be open to implement it?

Thanks

Rafi

**Comment by sasumner** [comment]
It likely won't be implemented as developer's tend to focus on core text-editing features.  Other tools concentrate on search and can usually be bridged with Notepad++.  Have you considered scripting your desired feature?

**Comment by rafi-d** [comment]
No, since I though this would be easy for the devs. And I haven't done it before... 
Can you achieve good integration with NP++? Any good example that I can follow?

Thanks

**Comment by sasumner** [comment]
>I though this would be easy for the devs

Not sure why you'd think this.

**Comment by rafi-d** [comment]
We'll, calling a cmd script from your own UI code (minimal mods) should be pretty strait forward.... Parsing the output into the search tab/pane might be in line with what they are already doing with the existing search. . 
Or maybe not....

**Comment by sasumner** [comment]
It's naive thinking.  No offense.  But this is an open source project so you can make a PR for it if you'd like.

**Comment by sasumner** [comment]
@rafi-d Some possible options for you presented as workarounds in this issue thread: #5966

**Comment by dinkumoil** [comment]
@rafi-d 

Despite the arguments already provided, the whole approach is a bad idea because it would only work properly on systems with english locale.

Languages of other countries use special characters (like äöüß in german, or think about greek, cyrillic scripts, scandinavic languages, arabic, ...). The _findstr_ command operates with the old DOS codepage specific for the respective country but Windows GUI programs work with the respective ANSI codepage. Character codes for special characters are different in these encoding schemas, thus the searchterms wouldn't be found if they contain special characters.

**Comment by rafi-d** [comment]
@dinkumoil 
I agree, but as far as coding (.c.,h files) - English is good enough.

My only goal - is sped.  Let me give you an example:
For 5200 files, filter - *.c, searched: 2417 files (SSD):
findstr: 7 seconds
grepWin - 24 sec  (good NP++ integration!)
NP++ -     90 seconds

And I am doing this at least 50 times a day ... I rest my case.

Any other tool that can reach 10 sec will be welcomed... :)

**Comment by dinkumoil** [comment]
@rafi-d 

Have a look at [this](https://notepad-plus-plus.org/community/topic/16846/how-to-specify-codepage-when-searching-via-find-in-files/2) thread in the community forum. There I provided a solution for integrating _FindStr_ and its search results into Notepad++ _Macros_ menu.

**Comment by rafi-d** [comment]
Thanks
