### ISSUE TITLE
Cannot save a file in a mapped directory

### ISSUE THREAD

**Issue by colinsutton** [notepad-plus-plus/notepad-plus-plus#5954]
### Steps to Reproduce the Issue
1. right click on a file in explorer in a windows 10 mapped directory
2. Select open with Notepad++
3. edit the file
4. select save

A pop-up appears "The file cannot be saved and it may be protected. Do you want to launch Notepad++ in Administrator mode?"

Administrator mode makes no difference. I can save the file with another name, or if I delete the file in explorer it can then be saved. I

Note: the mapped directory e.g M:  is a folder on on my C: drive.
The problem only appeared when I updated to version 7.7.1.

### Debug Information

Notepad++ v7.7.1   (64-bit)
Build time : Jun 16 2019 - 21:24:47
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10 (64-bit)
Plugins : DSpellCheck.dll mimeTools.dll NppConverter.dll

**Comment by sasumner** [comment]
I had no trouble doing steps 1-4 successfully.

Notepad++ v7.7.1   (32-bit)
Build time : Jun 16 2019 - 21:14:50
Path : C:\GM\Utilities\npp.7.7.1.bin\notepad++.exe
Admin mode : OFF
Local Conf mode : ON
OS : Windows 10 (64-bit)
Plugins : ColumnTools.dll Explorer.dll LocationNavigate.dll MarkdownViewerPlusPlus.dll mimeTools.dll NppConverter.dll NppExec.dll NppExport.dll PythonScript.dll

**Comment by colinsutton** [comment]
It does not happen if I open file D:/dirname/filename.txt, where D: is a physical drive,
but select  ‘This PC’
map network location localhost\D$\dirname to T:
and right click on T:/filename.txt to open it.
edit it, can’t save it.
I have been opening mapped directories with Notepad++ for years ( usually to map down several subdirectories)

**Comment by sasumner** [comment]
>map network location localhost\D$\dirname to T:

I did it basically the same for my test, using `net use`

**Comment by colinsutton** [comment]
I just discovered it is not a problem with Notepad++ at all, as Notepad has the same problem.
I don’t know the cause, maybe a policy or microsoft update has changed the behaviour.
The issue can be closed.
