### ISSUE TITLE
searchResult cannot change font&color

### ISSUE THREAD

**Issue by xgale** [notepad-plus-plus/notepad-plus-plus#5955]
### Description of the Issue
searchResult like this:
Line 33:       this is the line in file,this is **hitword**

in Style Configurator, I can change the font&color with linenumber&hitword,
but cannot change style of the rest words in the line.

### Steps to Reproduce the Issue
1. Search -> fine in files -> check the result window -> try to change font&color in 'Style Configurator'

### Actual Behavior
1. cannot change font&size&color
2. I try to add the following in style.xml line 1335

> `<WordsStyle` name="Search Default" styleID="0" fgColor="FFFF80" bgColor="FF8040" fontName="Courier New" fontStyle="0" fontSize="9" />

and now I can change font&size,but the new color still did not work. 

### Debug Information
Notepad++ v7.7.1   (32-bit)
Build time : Jun 16 2019 - 21:14:50
Path : D:\Pubsoft\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : ON
OS : Windows 10 (64-bit)
Plugins : JSMinNPP.dll LightExplorer.dll mimeTools.dll NppConverter.dll NppExport.dll NPPJSONViewer.dll XMLTools.dll

**Comment by xgale** [comment]
a easyer way to show the bug:

1. ‘find in files’, find anything just to show the Find result window
2. in ‘Global Styles’ , check the option 'Enable Global Font Size', choose a very very small Font size such as 5
3. now you can see something in Find result window was never changed

**Comment by sasumner** [comment]
It isn't a bug; it's just that these things were not envisioned as needing to be user settable.  Certainly you can (and you are) asking for a change to be made to enable this.

"Global" styles pertain to the view0 and view1 normal editing windows.

**Comment by donho** [comment]
@sasumner  
Thank you for your contribution by replying people.
I just invited you to be part of team for your good knowledge about Notepad++, for your pertinent viewpoint of product and features and of course for you're already working on the replying to users. Could you please write to don.h@free.fr if you accept the invitation?
We will talk in detail via email.

This comment will be removed.
