### ISSUE TITLE
Build instructions outdated

### ISSUE THREAD

**Issue by Omcsesz** [notepad-plus-plus/notepad-plus-plus#5956]
Build instructions in Readme.md are outdated

Hello, Team!

The second pooint under "To build notepad++.exe" (Build Notepad++ like a normal Visual Studio project.) contains a link which is not found (HTTP 404).

Can you please fix this?

**Comment by donho** [comment]
https://github.com/notepad-plus-plus/notepad-plus-plus/commit/89c23183fdafa87c597be34c04417539e15458f6
