### ISSUE TITLE
Error when building SciLexer.dll with boost

### ISSUE THREAD

**Issue by Omcsesz** [notepad-plus-plus/notepad-plus-plus#5958]
Hello, Team!

When I try to build SciLexer.dll with Boost 1.70.0 using the following command:

`nmake BOOSTPATH=C:\github\boost\boost_1_70_0\ BOOSTREGEXLIBPATH=C:\tmp`

the build fails with the following error:

```
Microsoft (R) Program Maintenance Utility Version 14.16.27032.1
Copyright (C) Microsoft Corporation.  All rights reserved.

        cl -Zi -TP -MP -W4 -EHsc -std:c++17 -D_CRT_SECURE_CPP_OVERLOAD_STANDARD_NAMES=1 -D_CRT_SECURE_NO_DEPRECATE=1 -D_SC_SECURE_NO_WARNINGS=1  -O1 -MT -DNDEBUG -GL -I../include -I../src -I../lexlib -IC:\github\boost\boost_1_70_0\ -DSCI_OWNREGEX -D_SILENCE_ALL_CXX17_DEPRECATION_WARNINGS -c ../boostregex/BoostRegexSerch.cxx
Microsoft (R) C/C++ Optimizing Compiler Version 19.16.27032.1 for x64
Copyright (C) Microsoft Corporation.  All rights reserved.

BoostRegexSearch.cxx
../boostregex/BoostRegexSearch.cxx(12): fatal error C1083: Cannot open include file: 'stdlib.h': No such file or directory
NMAKE : fatal error U1077: '"c:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\bin\Hostx64\x64\cl.EXE"' : return code '0x2
'
Stop.
```
Can you help me in this?

**Comment by Ekopalypse** [comment]
Do you know this?
https://github.com/bfridkis/Building-Notepad-Plus-Plus-from-Source-A-Beginners-Guide

**Comment by Omcsesz** [comment]
No, not yet.
This seems promising, thanks!

**Comment by donho** [comment]
Non related with Notepad++ project - PBKAC.
Suggestion; Search before asking. Google is your good friend.

**Comment by Omcsesz** [comment]
I thought the readme.md is up-to-date in this regard.

**Comment by sasumner** [comment]
> I thought the readme.md is up-to-date in this regard.

I guess when you find the solution, if `readme.md` is not accurate in that regard, submit a pull-request to make it right!

**Comment by Omcsesz** [comment]
That's true!
