### ISSUE TITLE
Change middle-click behavior in Notepad++?

### ISSUE THREAD

**Issue by brianjbowers** [notepad-plus-plus/notepad-plus-plus#5960]
My laptop's touchpad has three buttons. In Notepad++, the middle one closes open file tabs. I find this behavior frustrating and I'm wondering if I can change it. Thanks in advance for any suggestions!

**Comment by sasumner** [comment]
There is no dedicated "mouse setup" in Notepad++ that would allow you to change this functionality, nor is there any planned at this time for the future.  

Barring suggestions/workarounds from any others that care to comment, I would say just don't press the middle button while using Notepad++.  :)

BTW, questions are better directed here in the future:  https://notepad-plus-plus.org/community

Best regards.

**Comment by xylographe** [comment]
@brianjbowers 
Of course, you can change this behaviour: comment out lines 844‒847 in [`PowerEditor\src\WinControls\TabBar\TabBar.cpp`. ](https://github.com/notepad-plus-plus/notepad-plus-plus/blob/master/PowerEditor/src/WinControls/TabBar/TabBar.cpp#L842)
