### ISSUE TITLE
New entries  of 7.7.2 localization

### ISSUE THREAD

**Issue by donho** [notepad-plus-plus/notepad-plus-plus#5962]
Here are new entries  of 7.7.2 localization (comparing with 7.7.1:

[772.vs.771.html.zip](https://github.com/notepad-plus-plus/notepad-plus-plus/files/3439611/772.vs.771.html.zip)

**Comment by bovirus** [comment]
@donho 

Thanks for the info about the changes.

If you can when you use WinMerge please enable WinMerge to show only the differences and then  you will reduce the number of lines showed and the translator can concentrate only about the changes.

**Comment by popcorner** [comment]
@bovirus If you need to see the differences, you can see this picture (generated by sourcetree).
A GUI client for git is very helpful when comparing across commits.
![image](https://user-images.githubusercontent.com/6312791/62033225-1570fc80-b21e-11e9-8d72-debf12d3894a.png)

**Comment by bovirus** [comment]
@popcorner 

Of course I know that I can use also other way then WinMerge to show the differences.

I wrote my post because donho used WinMerge and if he want to sue this system it's better to mask in WinMerge the strings equal to have only showed the differences.
