### ISSUE TITLE
Feature Request: Web.config 

### ISSUE THREAD

**Issue by fwd079** [notepad-plus-plus/notepad-plus-plus#5964]
Good morning,

The file `web.config` is essentially an XML file, please can this be incorporated so [this step](http://www.secretgeek.net/notepad_plus_plus_config) be avoided please?

Kind Regards.

**Comment by xylographe** [comment]
Not every file with `.config` extension is an XML file.

**Comment by fwd079** [comment]
Yes indeed, as stated **web.config** not config.

Anyway app.config/web.config are the two most popular configs in windows environment. So can we not look at `<?xml>` and the full name to at least guess the language?

Kind Regards.

**Comment by xylographe** [comment]
@fwd079 
Notepad++ opens **`App.config`** as XML because these config files start with **`<?xml`**.
See [`PowerEditor\src\ScitillaComponent\Buffer.cpp`.](https://github.com/notepad-plus-plus/notepad-plus-plus/blob/3282e5f4a487105d6af7baa945994d5d6a6adec7/PowerEditor/src/ScitillaComponent/Buffer.cpp#L1246)

**Comment by fwd079** [comment]
> @fwd079
> Notepad++ opens **`App.config`** as XML because these config files start with **`<?xml`**.
> See [`PowerEditor\src\ScitillaComponent\Buffer.cpp`.](https://github.com/notepad-plus-plus/notepad-plus-plus/blob/3282e5f4a487105d6af7baa945994d5d6a6adec7/PowerEditor/src/ScitillaComponent/Buffer.cpp#L1246)

Brilliant, thank you, didn't know that. So can the same be done on web.config at all?

Kind Regards.

**Comment by fwd079** [comment]
> Any file that starts with **`<?xml`** will be opened as XML syntax. Even if the file has a known extension. For example if you copy the file **`langs.xml`** (in the **`%APPDATA%\Notepad++`** folder) to **`langs.ps1`**, and then open **`langs.ps1`** in Notepad++ the syntax will be set to XML, not PowerShell — the **`<?xml`** at the start of the **`langs.ps1`** file overrules the **`.ps1`** extension.

Indeed, after removing the ext from `Settings > Style Configurator` closed all instances and reopened, `web.config` is still highlighted as XML now. Perhaps that one particular file had some incorrect formatting etc. But its all okay now. 

Thank you for explanation. Appreciated. 😃 

Kind Regards.
