### ISSUE TITLE
Notepad++ should do global file search parallel on multiple cores

### ISSUE THREAD

**Issue by CodingSpiderFox** [notepad-plus-plus/notepad-plus-plus#5968]
### Description of the Issue
Notepad++ not using available CPU capacity during search in all files of subfolder.

### Steps to Reproduce the Issue
Open a file in a subfolder with lots of files (Java source + binaries)
Search for an identifier over all those files including all subfolders (CTRL+Shift+F-> 3rd register in the popup)

### Expected Behavior
Notepad ++ using should use multiple cores (searching different subtrees simultaneously) so I get my final search results faster.

### Actual Behavior
Notepad++ only used about 5% CPU capacity.

**Comment by sasumner** [comment]
Notepad++ attempts to concentrate on core text editing features.  While basic searching is a necessary function of a good text editor, really powerful searching is best left to other tools that specialize.  Thank you for your suggestion and best regards.
