### ISSUE TITLE
I want to be able to access preliminary search results earlier when doing global file search

### ISSUE THREAD

**Issue by CodingSpiderFox** [notepad-plus-plus/notepad-plus-plus#5969]
### Description of the Issue
Search results only accessible after global file search completed.

### Steps to Reproduce the Issue
Open a file in a subfolder with lots of files (Java source + binaries)
Search for an identifier over all those files including all subfolders (CTRL+Shift+F-> 3rd register in the popup)

### Expected Behavior
Search results should appear as soon as they were found, one after another.
The search progress bar window does not "block" me from double clicking the results that were found so far, and I want to be taken to the place of discovery immediately after double clicking the result.

### Actual Behavior
Search progress bar stays on top very long time when searching many files. Cannot continue my work while search is not fully complete.

**Comment by sasumner** [comment]
Notepad++ attempts to concentrate on core text editing features.  While basic searching is a necessary function of a good text editor, really powerful searching is best left to other tools that specialize.  So you might consider starting your searches in another tool, and then switch back to your text editing tasks in Notepad++ while the other tool is running.  Thank you for your suggestion and best regards.
