### ISSUE TITLE
Javascript language, identification strings multiline

### ISSUE THREAD

**Issue by JAITAN** [notepad-plus-plus/notepad-plus-plus#597]
In the JavaScript language, the editor does not recognize multi-line strings, when using backticks (`) to delimitation.

**Comment by donho** [comment]
http://stackoverflow.com/questions/805107/creating-multiline-strings-in-javascript
Such multi-lines string feature is supported in Notepad++.

**Comment by 18763C27** [comment]
he means template strings

those just happen to support multi line strings

https://stackoverflow.com/a/27242507

https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/template_strings#Syntax

```javascript
let who = "world";
console.log(`hello ${who}`);
```

it would be nice to have syntax highlighting for them
