### ISSUE TITLE
Fix mutli-language installer window - Open a temporary branch (after release 7.7.2) 

### ISSUE THREAD

**Issue by bovirus** [notepad-plus-plus/notepad-plus-plus#5978]
@donho 

After you will release NPP 7.7.2 could be possible to open a temporary branch where can I make all changes to localize all screen currently untranslated in the installer?

**Comment by donho** [comment]
@bovirus 
I was clear about this point:
Some untranslated strings in Notepad++ installer won't be translatable, because 
1. Rare translator will use NSIS compiler to verify the result of translation.
2. The translation could corrupt NSIS script that makes compiling fail or installer not running or buggy.

**Comment by bovirus** [comment]
Please consider that currently Notepad++ installer is a mix of translated and untranslated text strings.

In a first strep you close the previous ticket for the same request.

After a short discusison you accepted that could eb done with external files and re.opened the ticket.

Of course the translator shouldn't modify the main body of your script (only you can do it).

My request as you know is to point to external file for missng translations (module names and portabnle instalaltion window)..

Then you maintain the main body and the translator didn't modify the basic scripts.

The translatros are in charge only about the strings in teh separate file (one for each language) where there are only the striongs of the installer currently untranslated.

I hope that you reconsider that.

I already done this job for QEMU Windows installer.
