### ISSUE TITLE
notepad++ It is not compatible with Arabic texts

### ISSUE THREAD

**Issue by tersnetwork** [notepad-plus-plus/notepad-plus-plus#598]
hello, first i want thx for hard work, and i'm user using notepad++ long time but after ever update i'm waiting if the Developers fix and Improvement Arabic texts (RTL) i just want write and edit text same notepad in windows and i found some bugs in notepad++ Specifically in view and edit Arabic texts.

example:

- when i try change to RTL, and using arrow to move right or left the Buttons reversed also
- when i want edit Arabic text in "LTR" i don't know where place the cursor. (But when i change to RTL i can edit There are no problems)

and i hope my questions is clear to understand.

**Comment by donho** [comment]
It's a default behaviour of Scintilla for RTL languages, and unfortunately it doesn't work well for supporting such languages.
