### ISSUE TITLE
[BUG] Folder as workspace gackground glitch after Windows lock

### ISSUE THREAD

**Issue by da411d** [notepad-plus-plus/notepad-plus-plus#5980]
When i lock my laptop (Win + L) and unlock again, there is a glitch with gackground, see video below. To fix it i need resize window to smal and back.

![bandicam 2019-07-31 00-27-42-741](https://user-images.githubusercontent.com/12462454/62166671-11320580-b32a-11e9-9548-2ec4132406d4.gif)

```
Notepad++ v7.7.1   (32-bit)
Build time : Jun 16 2019 - 21:14:50
Path : D:\_APPS\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : ON
OS : Windows 10 (64-bit)
Plugins : AnalysePlugin.dll mimeTools.dll NppConverter.dll NppExport.dll NppFTP.dll 
```

**Comment by ArkadiuszMichalski** [comment]
Same or similar to https://github.com/notepad-plus-plus/notepad-plus-plus/issues/2937.
