### ISSUE TITLE
Broken link on the Notepad++ website

### ISSUE THREAD

**Issue by xylographe** [notepad-plus-plus/notepad-plus-plus#5984]
On web page [**`https://notepad-plus-plus.org/resources.html`**](https://notepad-plus-plus.org/resources.html) the 
“_Plugins HOWTO_” link ([**`http://docs.notepad-plus-plus.org/index.php?title=Plugin_Development`**)](http://docs.notepad-plus-plus.org/index.php?title=Plugin_Development) appears to be broken, and should probably be replaced by 
[**`https://notepad-plus-plus.org/contribute/plugin-howto.html`**](https://notepad-plus-plus.org/contribute/plugin-howto.html).

**Comment by ghoulsblade** [comment]
not quite, that plugin-howto also contains the broken link as 
"However, the knowledge of Notepad++ plugin system is required"
i would have expected a kind of api reference or similar rather than just that quick howto, seems something was genuinely lost.

**Comment by chcg** [comment]
http://docs.notepad-plus-plus.org/index.php is not accessible. Maybe a side effect of the broken N++ website 1-2 weeks ago.

**Comment by DavidHansen-0x454d43** [comment]
@ghoulsblade, [here](https://web.archive.org/web/20190325050752/http://docs.notepad-plus-plus.org/index.php/Plugin_Development) is the latest archived version of that page. 

The wiki was made read only and there was no way for people to keep it up to date. My understanding is that [this](https://github.com/notepad-plus-plus/npp-usermanual) github repo is going to be used for documentation going forward.

**Comment by donho** [comment]
Notepad++ website has been restored on a new server due to an unpaid bill problem ( https://twitter.com/Notepad_plus/status/1154154853943435264 ).
As a result, some services are not restored yet.
We are working on tese issues. Sorry for the inconvenience.

**Comment by donho** [comment]
OTOH http://docs.notepad-plus-plus.org/ is outdated.
We're redoing a new Notepad++ User Manual here:
https://notepad-plus-plus.org/community/topic/17968/if-documentation-is-like-sex-you-can-have-some-sex-now
Your contribution is welcome.

**Comment by donho** [comment]
https://npp-user-manual.org/
