### ISSUE TITLE
"About Notepad++" dialog gets cut off

### ISSUE THREAD

**Issue by thenlich** [notepad-plus-plus/notepad-plus-plus#5987]
### Description of the Issue

Depending on main window position, the "About Notepad++" (F1) dialog is not always fully positioned inside the desktop screen boundaries. Some content and UI elements (e.g. OK button) can be cut off. Also, the dialog prevents manual repositioning if the user wants to read the content or interact with the OK button to dismiss the dialog.

### Steps to Reproduce the Issue

1.  Start Notepad++ v7.7.1 (32-bit) on Windows 10
2.  Move main window to lower part of desktop, partially outside lower screen boundary.
3.  Press F1.

### Expected Behavior

All content and UI elements should be positioned inside screen boundaries. Alternatively, the window should be movable by the user.

### Actual Behavior

Only the top part of "About" box is visible. Since no "OK" button is visible, it is not apparent how to dismiss the dialog in this case.

### Debug Information

![np](https://user-images.githubusercontent.com/13075200/62219520-cad2ba00-b3ae-11e9-81e2-7f5b6c9a4306.png)

**Comment by sasumner** [comment]
Mostly true...and good points.

>the dialog prevents manual repositioning

Mostly false...If you press Alt+spacebar and then choose Move, the window can be manually positioned at-will.  :)

**Comment by thenlich** [comment]
> 
> 
> Mostly true...and good points.
> 
> > the dialog prevents manual repositioning
> 
> Mostly false...If you press Alt+spacebar and then choose Move, the window can be manually positioned at-will. :)

I stand corrected - it should read: "Unlike many other Notepad++ dialogs, the About... dialog does not exhibit a title bar by which it could be dragged by the user via the pointing device."

**Comment by donho** [comment]
It's a feature.
