### ISSUE TITLE
Feature request: Remember results panel state across sessions

### ISSUE THREAD

**Issue by MarkMaldaba** [notepad-plus-plus/notepad-plus-plus#6003]
### Description of the Issue

Notepad++ has a brilliant feature whereby if you close the program (or it crashes) then when you reopen it, all files are open in the same state as they were before, even if they had unsaved changes.

However, one thing that doesn't get restored is the contents of the results panel, which is often an important piece of the 'work in progress'.  For example, I often have workflows which involve performing a search and then working through the results one by one, so losing the search results in a crash or at the end of the day can result in work having to be repeated. 

It would be great if the search results could be saved as part of the session file, and restored when Notepad++ restarts.

**Comment by Ekopalypse** [comment]
First one thing to clarify - npp stores the session info on exit. 
On a crash it doesn't store anything, what you've discovered is that it was loaded with the same session information as before the crash happens.
But can you elaborate on your feature a little bit more?
Why is there a need to repeat the work if it was already done?
I can see that it is convenient to have the search result panel coming up with the results from the last search(es?), but I also see the disadvantages of storing this, like slows down startup and exit,
depending on the results it must store, maybe, a huge amount of data, stored data might be inconsistent to what is on disk ...

For me it would make more sense if the feature request would be 
"redo the last searches on startup".
But then it should be defined clearly what it does and preferable it is a customizable setting, meaning, on and off checkbox.

**Comment by sasumner** [comment]
I don't see enough value in it for a large number of users.  The last searches are in the find-history, making re-running them not terribly painful.

**Comment by MarkMaldaba** [comment]
This is not about saving the searches, but about saving the search *results*.

My use-case: I often have to work through relatively large refactorings of code.  My process is to search for the term that is being renamed/moved/modified and systematically work through the results.  Sometimes several hundred of them, on a large code-base.

In order to keep track progress, I delete entries from the results window as I go.  In fact, often I do a first pass, to quickly delete all the results that are clearly false-positives before going back and looking into the remainder in more detail.

Quite often, this can be interrupted, either by a more urgent task or by the end of the day.  In both cases, I want my search results to persist so that I can continue where I left off.  When I lose my search results, I lose state information about the current task and so it would be very useful if this were to persist.

Therefore, it would definitely not be helpful for me to have a 'redo last searches on startup' option, as that (as you say) is fairly trivial to do - it is about the actual state of the search panel, itself.

I don't buy the argument that this would slow down load times - it could be done asynchronously in the background after the rest of the UI has been loaded, for example.   I would be happy for it to be a customisable setting, which defaults to off.

I didn't realise NPP didn't store state on crash - I thought it maintained the session file as it went rather than just writing it on close.  However, I stand corrected (and that is an issue for another ticket).  Even just storing it on close would be useful, so the data could persist overnight.

Given the more detailed use-case, would you consider re-opening this ticket?
