### ISSUE TITLE
Modern menu in Windows 10 like in PyCharm

### ISSUE THREAD

**Issue by anki-code** [notepad-plus-plus/notepad-plus-plus#6004]
How it looks in N++:
![image](https://user-images.githubusercontent.com/1708680/62455238-95e3b000-b77e-11e9-9402-49873500d2da.png)

How it looks in PyCharm 2019.2:
![image](https://user-images.githubusercontent.com/1708680/62455066-40a79e80-b77e-11e9-91c8-74d2159d3565.png)

**Comment by donho** [comment]
The 2nd case can never show the whole file path.
For me it's not a feature but a bug.

**Comment by anki-code** [comment]
>In Notepad++ there's a real feature that hide menu bar from Preferences dialog.
>When you need to access to Menu, type ALT.

Yep, it's a good feature. 
What do you think about Firefox UI in Notepad++? 
1. All tabs are in the title
2. Menu by ALT

If you need fullpath it could be shown as tooltip for tab or shown in short of tab name. For example PyCharm shows difference between paths of tabs and shows "../folder1/file.txt" and "../folder2/file.txt" for the same filename "file.txt".

So as result we've remove unuseful title line.
