### ISSUE TITLE
[BUG] Notepad ++ 771 Plugin Admin Doesn't work properly

### ISSUE THREAD

**Issue by wonkawilly** [notepad-plus-plus/notepad-plus-plus#6008]
### Description of the Issue
Notepad++ 771 Plugin Admin Doesn't work properly in fact when I check one or more plugin(s) it doesn't install anything but just closes notepad++. I tested notepad++ in both Admin Mode Off and On: see Debug Infos.

### Steps to Reproduce the Issue

1. Open Plugin Admin
2. Check a Plugin to install
3. Click on Install button

### Expected Behavior
I expect to see Notepad++ closed, than the plugin I checked downloaded and installed and Notepad++ restarted with the new installed plugin into it.

### Actual Behavior
Notepad++ just closes.

### Debug Information
**With admin mode On:**
Notepad++ v7.7.1   (32-bit)
Build time : Jun 16 2019 - 21:14:50
Path : C:\Users\Montaggio Video\Desktop\npp.7.7.1.bin\notepad++.exe
Admin mode : ON
Local Conf mode : ON
OS : Windows 7 (32-bit)
Plugins : mimeTools.dll NppConverter.dll NppExport.dll 

**With admin mode Off:**
Notepad++ v7.7.1   (32-bit)
Build time : Jun 16 2019 - 21:14:50
Path : C:\Users\username\Desktop\Portable npp.7.7.1.bin\notepad++.exe
Admin mode : OFF
Local Conf mode : ON
OS : Windows 7 (32-bit)
Plugins : mimeTools.dll NppConverter.dll NppExport.dll 

### Other Informations

I have already notified in this bug tracker this issue for a previous version of Notepad: unfortunately the problem is still present.
For comparison please notice that the old Plugin Manager still works on an old version of notepad I'm still using: so it isn't a problem of internet or network connection.

Anyone else is getting this issue?
Thanks in advance.

**Comment by KnightDanila** [comment]
Same problem...
I use a portable version of Notepad++ v7.7.1 x32 (I use x32 on x64 computer, but I do not think that the problem in this)
Included plugins:
1.  NppExport v0.2.8 (32-bit x86 only)
2.  Converter 4.2.1
3.  Mime Tool 2.5
Updater (Installer only):
* WinGup (for Notepad++) v5.1

**Comment by dinkumoil** [comment]
@wonkawilly , @KnightDanila 

Are you behind a proxy server? Maybe one which requires authentication?

**Comment by wonkawilly** [comment]
@dinkumoil 

> @wonkawilly , @KnightDanila
> 
> Are you behind a proxy server? Maybe one which requires authentication?

I don't know, maybe a NAT. But Plugin Manager works well: I don't understand why Plugin Admin doesn't works the same way.

**Comment by chcg** [comment]
@wonkawilly PluginManager uses the windows\internet explorer configuration for the download. PluginAdmin used WinGUP, which uses Curl inside for the download. So there is quite a difference between the two solutions.

**Comment by wonkawilly** [comment]
> @wonkawilly PluginManager uses the windows\internet explorer configuration for the download. PluginAdmin used WinGUP, which uses Curl inside for the download. So there is quite a difference between the two solutions.

OK I suppose that this means that in my Computer WinGUP or Curl or both aren't installed or don't work properly. If this is the problem, maybe would be a good thing that PluginAdmin implements even windows internet explorer configuration for the download and automatically chooses the method that is present into the user system, In this way there won't be anymore issues in future. Also this proble would be a problem every time a user clean up the system by formatting it. IMHO it is a issue too and has to be solved in the way the user receive a n++ that does the job in a more straight way to keep it simple so every one can use P.A. without having to face this issue on its own

Please @donho: keep it simple even for those that aren't experts. Thank you so much.
