### ISSUE TITLE
64 bit version and windows integration

### ISSUE THREAD

**Issue by Nova900** [notepad-plus-plus/notepad-plus-plus#6011]
### Description of the Issue
The 64 bit version of notepad++ doesn't really work well together with my Windows 7. I can't chose the program as standard for opening files. Chosing the exe in the "Open with..." dialogue doesn't work, after selecting the exe in the file dialogue and pressing Ok, it just selects normal notepad (first program in the list). Opening for example lua files with notepad++ 64 bit installed still asks me with what program I want to open it, Chosing notepad++ still doesn't work then.
Deleting the 64 bit version and Installing the 32 bit one solves all these problems. 

### Debug Information
Notepad++ v7.7.1   (32-bit)
Build time : Jun 16 2019 - 21:14:50
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 7 (64-bit)
Plugins : mimeTools.dll NppConverter.dll NppExport.dll

**Comment by chcg** [comment]
Seems to be a duplicate to https://github.com/notepad-plus-plus/notepad-plus-plus/issues/2454.

**Comment by donho** [comment]
Your Debug Information shows an old version Notepad++ v7.7.1 .
Please update it with installer of 7.8.5
It should work.
