### ISSUE TITLE
Notepad++ window permanently disappears after Windows "minimize all windows" clicked

### ISSUE THREAD

**Issue by charltoncr** [notepad-plus-plus/notepad-plus-plus#6012]
### Description of the Issue
When I minimize all windows on my screen with the Windows "Minimize All Windows" button at the right end of the taskbar while Notepad++ is running, Notepad++ won't restore its window when I then click on its (Notepad++'s) taskbar button. Nothing that I know about will restore the invisible Notepad++ window. I must end the Notepad++ process to start all over with Notepad++.

### Steps to Reproduce the Issue

1. Click the Windows "Minimize all button"
2. Click the Notepad++ taskbar button 
3. 

### Expected Behavior

I expect the Notepad++ window to be restored to view.

### Actual Behavior

The Notepad++ window remains minimized and invisible no matter what I do.

### Debug Information

Notepad++ v7.7.1   (64-bit)
Build time : Jun 16 2019 - 21:24:47
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 7 (64-bit)
Plugins : DSpellCheck.dll mimeTools.dll NppConverter.dll 

None.

**Comment by sasumner** [comment]
You could be more specific when you say "click the windows minimize all button".  I had to research how to do that. :)  The method I found was to press this keycombo:  windows+m.  Trying that method with the following setup, I had no problem restoring the Notepad++ window by clicking on its taskbar icon.

Closing (for now) as not reproducible.  I'm open to reopening if others can reproduce, especially on Win 7.

Notepad++ v7.7.1   (32-bit)
Build time : Jun 16 2019 - 21:14:50
Path : C:\...........\npp.7.7.1.bin\notepad++.exe
Admin mode : OFF
Local Conf mode : ON
OS : Windows 10 (64-bit)
Plugins : ColumnTools.dll Explorer.dll LocationNavigate.dll MarkdownViewerPlusPlus.dll mimeTools.dll NppConverter.dll NppExec.dll NppExport.dll PythonScript.dll

**Comment by ollieV** [comment]
Hi, I just wanted to say I had the same problem and in my case here is what happened: 
I use two screens (one portrait and one landscape) and the notepad++ window seems to have been located in a hidden part of the screen area. Fiddling with the screen setting allowed me to locate it. The plugin suggestion window was open, which means that the window cannot be moved before you close the warning. That also means that it could not be stacked nor would appear if I tried to use cascade (both from right clicking windows toolbar).
Hope this helps.

**Comment by charltoncr** [comment]
Thanks for the tip. I only use one screen so I don't think that was a factor. The problem hasn’t happened again since I posted the report.

 

Again, thanks.

ron

**Comment by serajshaikh** [comment]
Step to reduce issue
1. Open Notepad++ application
2. Click setting on menubar
3. Then select preferences option 
4. Then select MISC and uncheck the"Minimize to system tray" box

**Comment by demoprazol** [comment]
> Step to reduce issue
> 
> 1. Open Notepad++ application
> 2. Click setting on menubar
> 3. Then select preferences option
> 4. Then select MISC and uncheck the"Minimize to system tray" box

Solved my problem thank you

**Comment by YuvalCohen** [comment]
> Step to reduce issue
> 
> 1. Open Notepad++ application
> 2. Click setting on menubar
> 3. Then select preferences option
> 4. Then select MISC and uncheck the"Minimize to system tray" box

Excellent! thanks.
