### ISSUE TITLE
'Bookmark line' Marking doesn't bookmark all lines of a multi-line match

### ISSUE THREAD

**Issue by sasumner** [notepad-plus-plus/notepad-plus-plus#6018]
### Description of the Issue
When a `Mark`ing search with the `Bookmark line` option enabled finds a match that span lines, EVERY line that is part of the match should receive a bookmark; in reality only the FIRST line of the match gets bookmarked.

### Steps to Reproduce the Issue
1. Paste this text into a new Notepad++ editing tab:

    Once upon a midnight dreary, while I pondered, weak and weary,
    Over many a quaint and curious volume of forgotten lore-
    While I nodded, nearly napping, suddenly there came a tapping,
    As of some one gently rapping, rapping at my chamber door.
    "'Tis some visitor," I muttered, "tapping at my chamber door-
    Only this and nothing more."

2. Invoke the Mark dialog via `Search` menu -> `Mark...`
3. Search for the `Find what` expression `(?s)lore.*?tor` as follows:

![image](https://user-images.githubusercontent.com/30118311/62644775-e0009900-b918-11e9-852d-a32b94693411.png)

4. Press the `Mark All` button.

### Expected Behavior
Bookmarks should be placed as the following shows:

![image](https://user-images.githubusercontent.com/30118311/62644829-0292b200-b919-11e9-9607-287453d20b56.png)

### Actual Behavior
A single bookmark is placed for this multiline match:

![image](https://user-images.githubusercontent.com/30118311/62644809-f1e23c00-b918-11e9-9cfc-d3e62e8fb58e.png)

### Debug Information
Notepad++ v7.7.1   (32-bit)
Build time : Jun 16 2019 - 21:14:50
Path : C:\......\npp.7.7.1.bin\notepad++.exe
Admin mode : OFF
Local Conf mode : ON
OS : Windows 10 (64-bit)
Plugins : ColumnTools.dll Explorer.dll LocationNavigate.dll MarkdownViewerPlusPlus.dll mimeTools.dll NppConverter.dll NppExec.dll NppExport.dll PythonScript.dll 

### Additional Information
This is likely the same issue as #3541.  However, since that issue is now closed and the example provided didn't reproduce, presumably because the poster didn't express it correctly rather than the issue not being present, this current issue was opened (with hopefully a better, more correct example).

The usefulness of this desired bookmarking behavior is mostly in the ability to `Copy Bookmarked Lines` and get ALL lines containing the match.  Copying the first line only of a multiline match is of dubious value.

If one is purely using `Next Bookmark` of `Previous Bookmark` to move around between matches, perhaps this proposed behavior change "gets in the way" by producing too many bookmarks.  For that case, one could replicate the first-line-only bookmarking behavior by a slight regex change in the `Find what`, e.g. `(?s)lore(?=.*?tor)` (note positive-lookahead), for the above example.  Or, even better, simply use `Search` -> `Jump Up` (or `Jump Down`) -> `Find Style` instead of going to the next/previous bookmark!

**Comment by donho** [comment]
1 match with 4 bookmarks ?

**Comment by sasumner** [comment]
>1 match with 4 bookmarks ?

Many users wanting to use regex to find data that spans multiple lines have complained that they have no way to copy these lines.  This type of bookmarking would allow that copy via `Search` -> `Bookmarks` -> `Copy Bookmarked Lines`.
