### ISSUE TITLE
focus moves when switching back to n++ in find/replace

### ISSUE THREAD

**Issue by glebsts** [notepad-plus-plus/notepad-plus-plus#6021]
Hello, thank you for awesome tool.
Did not find similar issue here, so reporting.
v7.7.1
1. Open find/replace dialog, put smth in "find", move to "replace", put smth there
2. Switch to some other window with Alt-Tab (that's important)
3. Switch back to N++ with Alt-Tab (that's important)

### Expected Behavior
Focus should stay in "Replace" field, I can continue typing

### Actual Behavior
Focus moves back to "Find" field, and field text is selected (typing will replace entered text)

### Debug Information
Win10 1809 17763.557
N++ with administrator privileges.

**Comment by Ekopalypse** [comment]
Strange, I don't see your reported behavior. 
If I switch from npp to another one and back to npp the caret is in the current document
but not within the replace dialog.

**Comment by glebsts** [comment]
"Caret is in the current document" happens if I switch i.e. with mouse using taskbar window buttons. Reported behavior with focus moving happens on Alt+Tab switching.

**Comment by sasumner** [comment]
Verified OP's reported behavior with the following:

Notepad++ v7.7.1   (64-bit)
Build time : Jun 16 2019 - 21:24:47
Path : C:\........\npp.7.7.1.bin.x64\notepad++.exe
Admin mode : OFF
Local Conf mode : ON
OS : Windows 10 (64-bit)
Plugins : mimeTools.dll NppConverter.dll

**Comment by Ekopalypse** [comment]
I'm using alt+tab, tested on 7.6.6 and 7.7.1 both 64bit BUT on windows 7.
Opening the replace dialog, alt+tab to browser, don't do anything within browser but immediately do alt+tab to return to npp. Focus is on document.

**Comment by sasumner** [comment]
OP did not specify OS; if they would have followed instructions about creating an issue (fully), the actual `Debug Info` output would be there and we would know their OS...

**Comment by glebsts** [comment]
sorry, will add more info to the original post. Win10 1809 17763.557

**Comment by Ekopalypse** [comment]
Fired up win10 in VirtualBox and yes, I can see it there which raises the question if a 
possible future change affects different windows version differently?

**Comment by sasumner** [comment]
@Ekopalypse A solution should be derived that works on Win7 and Win10.  Or do I miss your point?

**Comment by glebsts** [comment]
Thank you for confirmation.
As an enduser, I don't like behavior of focus going into document, when I had Find/Replace active. My usecase was that I wanted to paste value copied from other window, into 'replace' box right after smth that I've already entered there. Focus in document with no obvious keyboard way to focus on F/R dialog is not very pleasant UX for me. So window-level everything works fine, but why focus moves to first textbox?

Hope you'll figure out best solution :)

**Comment by Ekopalypse** [comment]
@sasumner 
> Or do I miss your point?

No, not really, my statement was more like a hint that tests should be done against different versions to see if the expected behavior is available on all of them. I can offer windows 7 64bit testing :-)

**Comment by Coises** [comment]
This also causes problems with clipboard manager use. See:
https://community.notepad-plus-plus.org/topic/26274

**Comment by Chealer** [comment]
This is mostly solved in 8.7.2 and ulterior. Thank you @Coises and @donho 
As @Coises wrote there, the remaining behavior of selecting the whole combo box when gaining focus is the standard on Windows, as can be seen in Run and the file picker. [It is documented for Windows Forms](https://learn.microsoft.com/en-us/dotnet/api/system.windows.forms.combobox.selectedtext#:~:text=When%20the%20combo%20box%20gains%20focus%2C%20the%20full%20text%20in%20the%20control%20is%20automatically%20selected%2E), which explains that the selection point and selected text change as soon as a combo box loses focus. LibreOffice does not behave that way, but Eclipse 2025-06 does.

[_License_](https://www.philippecloutier.com/Common+infrastructure+licensing#its)
