### ISSUE TITLE
Unassigned ctrl+m keycombo inserts wrong line-ending

### ISSUE THREAD

**Issue by sasumner** [notepad-plus-plus/notepad-plus-plus#6022]
### Description of the Issue
Currently, ctrl+m is an unassigned shortcut in the *Shortcut Mapper*.  Unfortunately, if user is using Windows or Linux line-endings (which is 99.9% of the time?), an inadvertent ctrl+m keypress will insert a Mac-style (carriage-return only) line-ending into the current document.  Unless the user has visible-line-ends turned on, this might go unnoticed initially, possibly "corrupting" the user's file by preventing other programs from processing the file correctly.

### Steps to Reproduce the Issue
1. Run Notepad++ and create a new empty tab.
2. Make sure ctrl+m is not mapped to anything in *Shortcut Mapper*.
3. Turn visible line-endings on via activating `View` (menu) -> `Show Symbol` -> `Show End of Line`.
4. Make sure the file type is `Windows (CR LF)` or `Unix (LF)` on the status bar; double click this section of the status bar and select one of those, if needed.
4. Paste the following text into the editing view:

    Jack and Jill
    Went up the hill
    To fetch a pail of water
    Jack fell down
    And broke his crown,
    And Jill came tumbling after.

5. Put caret at end of the word `water` on line 3.
6. Press ctrl+m.

### Expected Behavior

I expect nothing to happen as ctrl+m is an unassigned shortcut.

### Actual Behavior

An inconsistent line-ending (a CR) is added to the document at the end of line 3:

![image](https://user-images.githubusercontent.com/30118311/62708231-f3ffd580-b9c0-11e9-830c-e56e3e2b7e5d.png)

### Debug Information
Notepad++ v7.7.1   (32-bit)
Build time : Jun 16 2019 - 21:14:50
Path : C:\...........\npp.7.7.1.bin\notepad++.exe
Admin mode : OFF
Local Conf mode : ON
OS : Windows 10 (64-bit)
Plugins : ColumnTools.dll Explorer.dll LocationNavigate.dll MarkdownViewerPlusPlus.dll mimeTools.dll NppConverter.dll NppExec.dll NppExport.dll PythonScript.dll 

### Suggested Resolution

The `Mark...` command is the only Find-window-family command that does not have a default shortcut assigned.  Defaulting ctrl+m to invoke `Mark...` would be a simple and easy resolution to this issue.  Of course, this is not ideal if the user would unmap ctrl+m from `Mark...` and then leave it unmapped, but is that likely? Wouldn't they be much more likely to unmap that so that they can assign ctrl+m to something else?

### Additional Info

I didn't think of this at first:  ctrl+j suffers from a similar problem, inserting a LF line-ending if it is unmapped in *Shortcut Mapper*.  But ctrl+j is at least assigned a default function (to join lines).

**Comment by dinkumoil** [comment]
@sasumner 

Why do you suggest to cure a symptom instead of the cause? This is already an often used approach in this project, we don't need more of that.

**Comment by sasumner** [comment]
@dinkumoil Actually, it was my hidden/secondary motive to get ctrl+m assigned as the default keycombo for `Mark...` !  Haha!  Read below for first motive.

If you think about it harder, to be like other unassigned ctrl+whatever keys, it is fully allowed to use them to input control-characters in your document.  Try ctrl+e, for example, which is another unassigned-by-default key.  You'll get an "ENQ" inserted in your doc.  ctrl+r is another one (inserts DC2).  So really, ctrl+m is perfectly valid, in theory, because it is just another control character.  But I don't like it, because it is invisible (unlike the others, unless one works with visible-line-ends on), can happen by accident, and can screw up your document.  The creation of this issue was spurred on by helping a coworker who had done just that.

In the end we will see what Don says...  I'm good with rejection. :)

> suggest to cure a symptom instead of the cause? This is already an often used approach in this project

Can you cite some examples of that?

**Comment by dinkumoil** [comment]
@sasumner 

Indeed, I've never noticed that it's possible to input control-characters. Might be caused by the fact that I've massivly increased the number of Notepad++ features assigned to keycombos, thus I'm not able to accidently input control-characters. When I install Notepad++ on a new machine I usually copy the files under `%Appdata%\Notepad++` from my work machine to the new machine. 

> Can you cite some examples of that?

In Notepad++ version prior to v7.7, when double-clicking an URL it had been opened in the standard browser **and** the URL text had been selected. But this behaviour caused Notepad++ v7.6.6 to crash. The bug has been fixed by disabling selection of the URL text, a feature which had worked flawlessly for years. I'm sure there have been other cases like that in the past.

**Comment by sasumner** [comment]
Scintilla's demo editor (not sure if it is calling itself `Sc1` or `SciTE` these days) seems to have the same ctrl+m CR-insertion "feature" for "Windows" files:

![image](https://user-images.githubusercontent.com/30118311/62789893-e9fcd600-ba97-11e9-8ad5-2525ba33b301.png)

**Comment by sasumner** [comment]
@dinkumoil Do you still have objection to this, given the new information?

**Comment by dinkumoil** [comment]
@sasumner

 I somehow missed your info from August last year, sorry for that. Of course, if this strange `Ctrl+M` behaviour derives from _Scintilla_ itself, there is nothing to fix in Npp code. Your suggested workaround might be the best solution.

**Comment by sasumner** [comment]
@dinkumoil Thank you; I will prepare a PR for it.  I hadn't done anything in the intervening time because I had concerns about upsetting you.  I think it is a good solution to protect users from the mixed-line-ending potential problem, plus fills the gap of all-except-Mark tabs in the *Find* window having a direct shortcut.

**Comment by mrprunen** [comment]
big problem for me
https://github.com/notepad-plus-plus/notepad-plus-plus/issues/8735

**Comment by sasumner** [comment]
Closing...not sure why this has remained open with the merging of #8218 ...
