### ISSUE TITLE
Notes in 'draft' state not cached/saved 100% of the time

### ISSUE THREAD

**Issue by sayboltm** [notepad-plus-plus/notepad-plus-plus#6025]
### Description of the Issue

In my experience, Notepad++ works great for making a new note, scratching something down, and being a temporary file, not needing to save it even when you restart your computer since npp must cache this note in progress somewhere.

### Steps to Reproduce the Issue

1. Have a set of normally opened/saved tabs, and a set of 'new n' tabs of 'queue'/todo notes
2. move the 'new n' tabs to a new window, I clicked and dragged one outside of the npp window, it created a new window (which I cannot seem to do now), and then dragged the others over individually since I could not shift+click multiple tabs like in chrome/firefox.
3. Restart computer because security update or something

Unlike 99% of the time where my temporary notes come back, I lost one of the windows, and coincidentally perhaps, it was the unsaved ones. I also lost some updates in the saved notes window, there were some unsaved changes, but I figured hey npp is so good at remembering these temporary notes, I'm not going to save until I finish my thought. Perhaps this is untested/non-intended/risky behaviour and practice, but I thought I should at least document it. I am having trouble dragging/creating new window like how I did before.

### Expected Behavior

All of my unsaved tabs, both unsaved changes to previously created files, and temporary notes that have never been saved, to be there after a sudden npp exit, including in a separate window

### Actual Behavior

One of the windows was not there when opened, unsaved changes to previously created/written files in window that was there were not existent. like the temporary cache that saves unsaved changes in npp got wiped out or something.

### Debug Information

v7.7.1 win32 

Thanks to devs for making this free piece of software my much preferred text editor over notepad.exe, even poorly written commercial IDE text editors.

**Comment by xylographe** [comment]
Looks like you started a new instance of NPP. IIRC that new instance will not have snapshots enabled.

**Comment by sayboltm** [comment]
Thank you for your understanding of this project and your 

So only one instance of npp has 'snapshots' enabled, but for that one instance (potentially unknown which one) snapshots can be counted on being there?

**Comment by Ekopalypse** [comment]
As of npp7.7.1, yes, only the first instance started has the session snapshot feature.

>can be counted on

No, because humans are not perfect and as long humans writing code it can't be perfect either.
If you rely on those files, save it and make backups. Btw. see what can be configured via settings->preferences->backup.

**Comment by sayboltm** [comment]
Understood. Thanks for all the info y'all!
