### ISSUE TITLE
[Feature Request] Give option to NOT skip paste replacement text during Replace All operation

### ISSUE THREAD

**Issue by Razor68** [notepad-plus-plus/notepad-plus-plus#6026]
### Description of the Issue

The Find/Replace algorithm skips over elements put in as replacement when performing a Replace All. This is of course by design, but the option to NOT have it skip over this way would be nice to have as there are occasions where this doesn't produce the desired results.

I suspect the only way to offer this (as having it work this way universally wouldn't be a good idea) would to add a checkbox to optionally have the search algorithm search within the replacement string for more replacements being needed (that is, don't move the search start point past the replacement string, but keep it where it was before the replacement).

### Steps to Reproduce the Issue
1.  Create a file consisting of lines containing "110,0,0,0,0,0,0,0,0,255" 
2. Move the cursor to the first character of the first line of the file.
3. Open the Find/Replace dialog and set "Find" to ",0," and "Replace" to ",," and click "Replace All".
4. Desired result is "110,,,,,,,,,255", but actual result is "110,,0,,0,,0,,0,255"
5. Repeat "Replace All", and desired result is achieved.
6. Now set the "Find" to ",," and the "Replace" to ",0," and click "Replace All"
7. Expected result is "110,0,0,0,0,0,0,0,0,255" but actual result is "110,0,,0,,0,,0,,255"
8. Repeating "Replace All" results in the desired result.

### Debug Information
Notepad++ v7.7.1   (64-bit)
Build time : Jun 16 2019 - 21:24:47
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 7 (64-bit)
Plugins : mimeTools.dll NppConverter.dll

**Comment by xylographe** [comment]
Try "Find what" `,0(?=,)`, "Replace with" `,`, and select "Regular expression".

**Comment by sasumner** [comment]
@xylographe Yes, but this will not be what they want to hear. ;)

**Comment by xylographe** [comment]
I don't think I've ever found a program, supporting plain (non-regex) text substitution, to behave this way. Perhaps, because it could easily lead to infinite loops?

**Comment by sasumner** [comment]
Closing as support is already there via regular expressions, as noted.
