### ISSUE TITLE
[Issue] Some mistranslated parts in italian.xml

### ISSUE THREAD

**Issue by wonkawilly** [notepad-plus-plus/notepad-plus-plus#6029]
### Description of the Issue
I've found some mistranslated parts and words in italian.xml. I don't know where to post the version I've corrected: so I post it here:

I have just renamed it as txt file to allow uploading. Rename it back as xml to use it.

[italian.txt](https://github.com/notepad-plus-plus/notepad-plus-plus/files/3484062/italian.txt)

**Comment by xylographe** [comment]
@wonkawilly 
Your modifications are based on an old version of `italian.xml`. Many items are missing.

Download the [latest version of `italian.xml`,](https://github.com/notepad-plus-plus/notepad-plus-plus/blob/master/PowerEditor/installer/nativeLang/italian.xml) and apply your corrections to that file.

**Comment by dail8859** [comment]
Please make your modifications to a recent version if there are any issues. Also creating a pull request is the best way to submit updates.

**Comment by wonkawilly** [comment]
@xylographe Thank you for you suggestion, but I'm sorry I'm relatively new on Github and I'm not completely familiar to all procedures in it. Not yet at least. So at the moment I am not able to accomplish what you asked in the right way, I hope in the future I will.
