### ISSUE TITLE
A small typo

### ISSUE THREAD

**Issue by Gorbeh** [notepad-plus-plus/notepad-plus-plus#603]
Under "?/Command Line Arguments...", for the option "-qn", the word "display" appears as "disply".

**Comment by Rikk** [comment]
As @donho didn't merge PR itself, I'm asking here to close this Issue, cause it's already fixed in https://github.com/notepad-plus-plus/notepad-plus-plus/commit/9b4e8888b0a7741c0dbba975dc4a58a8c4ca2cc5
