### ISSUE TITLE
Notepad++ should not assume file extension when loading file from command line

### ISSUE THREAD

**Issue by MikeChristensen** [notepad-plus-plus/notepad-plus-plus#6030]
### Description of the Issue
When the name of an existing file with no extension is passed into Notepad++ on the command line, Notepad++ assumes a default extension of .txt.

### Steps to Reproduce the Issue

1.  Create a file called `Dockerfile`
2.  Attempt to load that file into Notepad++ from command line: `notepad Dockerfile`

### Expected Behavior
If a file called `Dockerfile` exists, that file should be loaded.

### Actual Behavior
Notepad++ asks you if you wish to create a file called `Dockerfile.txt`

### Debug Information
Notepad++ v7.7.1   (64-bit)
Build time : Jun 16 2019 - 21:24:47
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10 (64-bit)
Plugins : mimeTools.dll NppConverter.dll 

### Work Arounds
The correct file can be loaded by typing `notepad Dockerfile.` (not the trailing dot at the end), however for us old people who have been doing this for 800 years, it's a tough change to get used to.  I passed in the name of an existing file, Notepad++ should load it.  Also related, if I type `notepad Dockerfile` and the file does _not_ exist, it should create `Dockerfile` and not `Dockerfile.txt`.

If the default behavior shouldn't be changed, at least make it an option in the langs.xml file.

**Comment by xylographe** [comment]
Cannot reproduce. Existing file `Dockerfile` is opened as expected,

Notepad++ v7.7.1   (32-bit)
OS Name : Windows 7 Ultimate (64-bit)

**Comment by xylographe** [comment]
@MikeChristensen 
The problem is that you invoke NPP as `notepad` instead of `notepad++`. If invoked as `notepad`, NPP will try to be compatible with Microsoft Notepad, meaning it will add `.txt` to a file name that has no extension (see [PowerEditor/src/winmain.cpp:121](https://github.com/notepad-plus-plus/notepad-plus-plus/blob/ab4cf883367eb3818fc0e6dea57d39d21f9ec618/PowerEditor/src/winmain.cpp#L119)).

**Comment by sasumner** [comment]
>Microsoft Notepad ... will add .txt to a file name that has no extension

Not in my trials from a CMD window on Win10; it opens extension-less:

![image](https://user-images.githubusercontent.com/30118311/62781845-d9902f80-ba86-11e9-97f0-9dae8d57a920.png)

**Comment by sasumner** [comment]
> ...Microsoft Notepad...will add .txt to a file name that has no extension

Not on my Win10 system. `notepad.exe` opens an *existing* extensionless file without changing the name:

![image](https://user-images.githubusercontent.com/30118311/62782071-718e1900-ba87-11e9-84a4-95a53a95d147.png)

A file that doesn't exist first is a different story:

![image](https://user-images.githubusercontent.com/30118311/62782298-f5480580-ba87-11e9-8c2c-5c1152df3c8e.png)

These statements aren't N++ related, though. :)

**Comment by sasumner** [comment]
If OP's step 2 is changed to:  Attempt to load that file into Notepad++ from command line: `notepad++ Dockerfile`

Then the extensionless file is loaded into Notepad++ just fine, without any extension being appended to its name.

Recommend that N++ be invoked like this for future needs.

**Comment by MikeChristensen** [comment]
Yup @xylographe is spot on.  There's code in the `convertParamsToNotepadStyle` function that mimics notepad.exe if Notepad++ is called in that way.  If I invoke Notepad++ using notepad++.exe directly, it works as expected.  I never figured that would make any difference!  So, perhaps a better way to rename notepad++ to notepad would be through a Powershell alias or something.  Agreed this appears to be by design, though it would be cool if you could "disable" this behavior somehow (registry key, .xml setting, etc).  More of a feature request at this point then..

**Comment by MikeChristensen** [comment]
Ok, since I can't leave well enough alone, I dug through the source code a bit more.  The thing that makes it behave this way isn't simply being run as `notepad.exe`, it's being run with the `-notepadStyleCmdline` parameter.  The [docs on how to replace notepad.exe](https://notepad-plus-plus.org/features/replace-notepad.html) include this parameter.  Instead, you can override notepad.exe without the parameter:

```
reg add "HKLM\Software\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\notepad.exe" /v "Debugger" /t REG_SZ /d "\"%ProgramFiles%\Notepad++\notepad++.exe\" -z" /f
```

And then Notepad++ will behave like Notepad++ and not like Notepad.exe.

**Comment by sasumner** [comment]
>...Notepad++ will behave like Notepad++ and not like Notepad.exe.

Hard to get one's head around a statement like that! :)

**Comment by kapsiR** [comment]
@MikeChristensen Thanks! With an update to Notepad++ v7.8 there is much more unintended behavior when using `-notepadStyleCmdline`. 
Removed it too to get it working again.

Example for an unintended behavior:

1. Win+R
2. Type `notepad`
3. Press Enter

Result:
![grafik](https://user-images.githubusercontent.com/7165033/66652693-942ee080-ec36-11e9-91e1-5621a40defcb.png)
![grafik](https://user-images.githubusercontent.com/7165033/66652700-9bee8500-ec36-11e9-8c2f-caa3666e1ef2.png)
![grafik](https://user-images.githubusercontent.com/7165033/66652724-b32d7280-ec36-11e9-9adc-97d7efc2c766.png)
