### ISSUE TITLE
Build of Scilexer w/Boost fails

### ISSUE THREAD

**Issue by jlpoolen** [notepad-plus-plus/notepad-plus-plus#6039]
### Description of the Issue
My attempt to build the SciLever.dll ends up with errors.  The build log is at: https://pastebin.com/wm5C1uK0 and ends with:
`../boostregex/BoostRegexSearch.cxx(37): fatal error C1083: Cannot open include file: 'boost/regex.hpp': No such file or directory
NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.12.25827\bin\HostX86\x86\cl.EXE"' : return code '0x2'`

The current instructions for building Scintilla are:

> To build SciLexer.dll with boost:

Here are the instructions to build SciLexer.dll (for both 32-bit & 64-bit) for Notepad++:

    Download the Boost source code.

    Unzip boost. In my case, It's unzipped in C:\sources\boost_1_70_0

    Build regex of boost. With the version 1.70, launch bootstrap.bat under the boost root, b2.exe will be generated beside of bootstrap.bat. For building boost PCRE lib, go into regex build directory by typing cd C:\sources\boost_1_70_0\libs\regex\build then launch C:\sources\boost_1_70_0\b2.exe toolset=msvc link=static threading=multi runtime-link=static address-model=64 release stage. Note that address-model=64 is optional if you want to build lib in 64 bits. For 32 bits build, just remove address-model=64 frome the command line.

    Copy generated message from C:\sources\boost_1_70_0\bin.v2\libs\regex\build\msvc-14.1\release\address-model-64\link-static\runtime-link-static\threading-multi\libboost_regex-vc141-mt-s-x64-1_70.lib to C:\tmp\boostregexLib\x64\

    Go in scintilla\win32\ then run nmake BOOSTPATH=your_boost_root_path BOOSTREGEXLIBPATH=your_built_lib_path -f scintilla.mak. For example nmake BOOSTPATH=C:\sources\boost_1_70_0\ BOOSTREGEXLIBPATH=C:\tmp\boostregexLib\x64\ -f scintilla.mak

### Steps to Reproduce the Issue

1. Download and unzip Boost: boost_1_70_0.7z from https://www.boost.org/users/download/
2. unzip to F:\Downloads\Boost.org\boost_1_70_0_VS2017
3. Open Microsoft Visual Studio 2017 "Open Visual Studio 2017 Tools Command Prompt" located at %comspec% /k "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\Tools\VsDevCmd.bat"
4. Change Drive and directory to F:\Downloads\Boost.org\boost_1_70_0_VS2017\boost_1_70_0
5. execute: boostrap.bat
6. cd F:\Downloads\Boost.org\boost_1_70_0_VS2017\boost_1_70_0\libs\regex\build
7. execute: F:\Downloads\Boost.org\boost_1_70_0_VS2017\boost_1_70_0\b2.exe toolset=msvc link=static threading=multi runtime-link=static address-model=64 release stage
8. make directory: D:\Temp\boost_stage
9. execute: copy F:\Downloads\Boost.org\boost_1_70_0_VS2017\boost_1_70_0\bin.v2\libs\regex\build\msvc-14.2\release\link-static\threading-multi\libboost_regex-vc142-mt-x32-1_70.lib D:\Temp\boost_stage

10. "D:"

11. "cd D:\work\Notepad++\project\tags\v7.7.1\scintilla\win32"

12. (cleaned as I had tried some other shells): nmake /f scintilla.mak clean
13. nmake BOOSTPATH=F:\Downloads\Boost.org\boost_1_70_0_VS2017 BOOSTREGEXLIBPATH=D:\Temp\boost_stage\libboost_regex-vc142-mt-x32-1_70.lib -f scintilla.mak

### Expected Behavior
Successfull Build

### Actual Behavior
Lots of errors: see https://pastebin.com/wm5C1uK0

Note: I had earlier tried the above sequence using a MS Visual Studio 2019 shell.  I then tried a MS Visual Studio 2018 x64 shell and figured I had mixed up MS Visual Studios and/or 32  bit vs. 64 bit.  So I started all anew with a 2017 x32 bit shell.

**Comment by Ekopalypse** [comment]
@jlpoolen, sorry, but did you even try to find something in the issues?
Some filter like is:issue boost ?

**Comment by jlpoolen** [comment]
I tried searches using SciLever and did not find anything on point.  Given the number of errors, I figured I was missing something very fundamental, e.g. compiling Boos with 64x and then trying to compile SciLever with a 32 bit compiler referencing the Boost regex lib in 64.

**Comment by jlpoolen** [comment]
I just realized I had pointed to a specific "lib" file when I should have pointed to the directory.  I therefore tried:

`nmake BOOSTPATH=F:\Downloads\Boost.org\boost_1_70_0_VS2017 BOOSTREGEXLIBPATH=D:\Temp\boost_stage -f scintilla.mak`

and received errors as well:


```
D:\work\Notepad++\project\tags\v7.7.1\scintilla\win32>nmake BOOSTPATH=F:\Downloads\Boost.org\boost_1_70_0_VS2017 BOOSTREGEXLIBPATH=D:\Temp\boost_stage -f scintilla.mak

Microsoft (R) Program Maintenance Utility Version 14.12.25834.0
Copyright (C) Microsoft Corporation.  All rights reserved.

        cl -Zi -TP -MP -W4 -EHsc -std:c++latest -D_CRT_SECURE_CPP_OVERLOAD_STANDARD_NAMES=1 -D_CRT_SECURE_NO_DEPRECATE=1 -D_SCL_SECURE_NO_WARNINGS=1  -O1 -MT -DNDEBUG -GL -I../include -I../src -I../lexlib -IF:\Downloads\Boost.org\boost_1_70_0_VS2017 -DSCI_OWNREGEX -D_SILENCE_ALL_CXX17_DEPRECATION_WARNINGS -c ../boostregex/BoostRegexSearch.cxx
Microsoft (R) C/C++ Optimizing Compiler Version 19.12.25834 for x86
Copyright (C) Microsoft Corporation.  All rights reserved.

BoostRegexSearch.cxx
D:\work\Notepad++\project\tags\v7.7.1\scintilla\include\Platform.h(389): error C2039: 'unique_ptr': is not a member of 'std'
C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.12.25827\include\vector(15): note: see declaration of 'std'
D:\work\Notepad++\project\tags\v7.7.1\scintilla\include\Platform.h(389): error C2143: syntax error: missing ';' before '<'
D:\work\Notepad++\project\tags\v7.7.1\scintilla\include\Platform.h(389): error C2433: 'Scintilla::Surface::unique_ptr': 'virtual' not permitted on data declarations
D:\work\Notepad++\project\tags\v7.7.1\scintilla\include\Platform.h(389): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
D:\work\Notepad++\project\tags\v7.7.1\scintilla\include\Platform.h(389): error C2238: unexpected token(s) preceding ';'
D:\work\Notepad++\project\tags\v7.7.1\scintilla\src\UniqueString.h(14): error C2039: 'unique_ptr': is not a member of 'std'
C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.12.25827\include\vector(15): note: see declaration of 'std'
D:\work\Notepad++\project\tags\v7.7.1\scintilla\src\UniqueString.h(14): error C2061: syntax error: identifier 'unique_ptr'
D:\work\Notepad++\project\tags\v7.7.1\scintilla\src\UniqueString.h(18): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
D:\work\Notepad++\project\tags\v7.7.1\scintilla\src\UniqueString.h(18): error C2146: syntax error: missing ';' before identifier 'UniqueStringCopy'
D:\work\Notepad++\project\tags\v7.7.1\scintilla\src\UniqueString.h(20): error C2064: term does not evaluate to a function taking 0 arguments
D:\work\Notepad++\project\tags\v7.7.1\scintilla\src\UniqueString.h(20): warning C4508: 'Scintilla::UniqueStringCopy': function should return a value; 'void' return type assumed
D:\work\Notepad++\project\tags\v7.7.1\scintilla\src\UniqueString.h(25): error C2064: term does not evaluate to a function taking 1 arguments
D:\work\Notepad++\project\tags\v7.7.1\scintilla\src\UniqueString.h(25): error C2617: 'Scintilla::UniqueStringCopy': inconsistent return statement
D:\work\Notepad++\project\tags\v7.7.1\scintilla\src\UniqueString.h(18): note: see declaration of 'Scintilla::UniqueStringCopy'
D:\work\Notepad++\project\tags\v7.7.1\scintilla\src\UniqueString.h(26): error C2617: 'Scintilla::UniqueStringCopy': inconsistent return statement
D:\work\Notepad++\project\tags\v7.7.1\scintilla\src\UniqueString.h(18): note: see declaration of 'Scintilla::UniqueStringCopy'
D:\work\Notepad++\project\tags\v7.7.1\scintilla\src\Partitioning.h(65): error C2143: syntax error: missing ';' before '<'
D:\work\Notepad++\project\tags\v7.7.1\scintilla\src\Partitioning.h(199): note: see reference to class template instantiation 'Scintilla::Partitioning<T>' being compiled
D:\work\Notepad++\project\tags\v7.7.1\scintilla\src\Partitioning.h(65): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
D:\work\Notepad++\project\tags\v7.7.1\scintilla\src\Partitioning.h(65): error C2238: unexpected token(s) preceding ';'
D:\work\Notepad++\project\tags\v7.7.1\scintilla\src\RunStyles.h(28): error C2143: syntax error: missing ';' before '<'
D:\work\Notepad++\project\tags\v7.7.1\scintilla\src\RunStyles.h(60): note: see reference to class template instantiation 'Scintilla::RunStyles<DISTANCE,STYLE>' being compiled
D:\work\Notepad++\project\tags\v7.7.1\scintilla\src\RunStyles.h(28): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
D:\work\Notepad++\project\tags\v7.7.1\scintilla\src\RunStyles.h(28): error C2238: unexpected token(s) preceding ';'
D:\work\Notepad++\project\tags\v7.7.1\scintilla\src\RunStyles.h(29): error C2143: syntax error: missing ';' before '<'
D:\work\Notepad++\project\tags\v7.7.1\scintilla\src\RunStyles.h(29): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
D:\work\Notepad++\project\tags\v7.7.1\scintilla\src\RunStyles.h(29): error C2238: unexpected token(s) preceding ';'
D:\work\Notepad++\project\tags\v7.7.1\scintilla\src\ContractionState.h(48): error C2039: 'unique_ptr': is not a member of 'std'
C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.12.25827\include\vector(15): note: see declaration of 'std'
D:\work\Notepad++\project\tags\v7.7.1\scintilla\src\ContractionState.h(48): error C2143: syntax error: missing ';' before '<'
D:\work\Notepad++\project\tags\v7.7.1\scintilla\src\ContractionState.h(48): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
D:\work\Notepad++\project\tags\v7.7.1\scintilla\src\CellBuffer.h(36): error C2039: 'unique_ptr': is not a member of 'std'
C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.12.25827\include\vector(15): note: see declaration of 'std'
D:\work\Notepad++\project\tags\v7.7.1\scintilla\src\CellBuffer.h(36): error C2143: syntax error: missing ';' before '<'
D:\work\Notepad++\project\tags\v7.7.1\scintilla\src\CellBuffer.h(36): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
D:\work\Notepad++\project\tags\v7.7.1\scintilla\src\CellBuffer.h(36): error C2238: unexpected token(s) preceding ';'
D:\work\Notepad++\project\tags\v7.7.1\scintilla\src\CellBuffer.h(122): error C2039: 'unique_ptr': is not a member of 'std'
C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.12.25827\include\vector(15): note: see declaration of 'std'
D:\work\Notepad++\project\tags\v7.7.1\scintilla\src\CellBuffer.h(122): error C2143: syntax error: missing ';' before '<'
D:\work\Notepad++\project\tags\v7.7.1\scintilla\src\CellBuffer.h(122): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
D:\work\Notepad++\project\tags\v7.7.1\scintilla\src\CellBuffer.h(122): error C2238: unexpected token(s) preceding ';'
D:\work\Notepad++\project\tags\v7.7.1\scintilla\src\Decoration.h(53): error C2039: 'unique_ptr': is not a member of 'std'
C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.12.25827\include\vector(15): note: see declaration of 'std'
D:\work\Notepad++\project\tags\v7.7.1\scintilla\src\Decoration.h(53): error C2143: syntax error: missing ';' before '<'
D:\work\Notepad++\project\tags\v7.7.1\scintilla\src\Decoration.h(53): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
D:\work\Notepad++\project\tags\v7.7.1\scintilla\src\Decoration.h(53): error C2086: 'int Scintilla::unique_ptr': redefinition
D:\work\Notepad++\project\tags\v7.7.1\scintilla\src\ContractionState.h(48): note: see declaration of 'Scintilla::unique_ptr'
D:\work\Notepad++\project\tags\v7.7.1\scintilla\src\Decoration.h(55): error C2039: 'unique_ptr': is not a member of 'std'
C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.12.25827\include\vector(15): note: see declaration of 'std'
D:\work\Notepad++\project\tags\v7.7.1\scintilla\src\Decoration.h(55): error C2143: syntax error: missing ';' before '<'
D:\work\Notepad++\project\tags\v7.7.1\scintilla\src\Decoration.h(55): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
D:\work\Notepad++\project\tags\v7.7.1\scintilla\src\Decoration.h(55): error C2086: 'int Scintilla::unique_ptr': redefinition
D:\work\Notepad++\project\tags\v7.7.1\scintilla\src\ContractionState.h(48): note: see declaration of 'Scintilla::unique_ptr'
D:\work\Notepad++\project\tags\v7.7.1\scintilla\src\Document.h(233): error C2039: 'unique_ptr': is not a member of 'std'
C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.12.25827\include\vector(15): note: see declaration of 'std'
D:\work\Notepad++\project\tags\v7.7.1\scintilla\src\Document.h(233): error C2143: syntax error: missing ';' before '<'
D:\work\Notepad++\project\tags\v7.7.1\scintilla\src\Document.h(233): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
D:\work\Notepad++\project\tags\v7.7.1\scintilla\src\Document.h(233): error C2238: unexpected token(s) preceding ';'
D:\work\Notepad++\project\tags\v7.7.1\scintilla\src\Document.h(247): error C2039: 'unique_ptr': is not a member of 'std'
C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.12.25827\include\vector(15): note: see declaration of 'std'
D:\work\Notepad++\project\tags\v7.7.1\scintilla\src\Document.h(247): error C2143: syntax error: missing ';' before '<'
D:\work\Notepad++\project\tags\v7.7.1\scintilla\src\Document.h(247): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
D:\work\Notepad++\project\tags\v7.7.1\scintilla\src\Document.h(247): error C2238: unexpected token(s) preceding ';'
D:\work\Notepad++\project\tags\v7.7.1\scintilla\src\Document.h(255): error C2039: 'unique_ptr': is not a member of 'std'
C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.12.25827\include\vector(15): note: see declaration of 'std'
D:\work\Notepad++\project\tags\v7.7.1\scintilla\src\Document.h(255): error C2143: syntax error: missing ';' before '<'
D:\work\Notepad++\project\tags\v7.7.1\scintilla\src\Document.h(255): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
D:\work\Notepad++\project\tags\v7.7.1\scintilla\src\Document.h(255): error C2238: unexpected token(s) preceding ';'
D:\work\Notepad++\project\tags\v7.7.1\scintilla\src\Document.h(256): error C2039: 'unique_ptr': is not a member of 'std'
C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.12.25827\include\vector(15): note: see declaration of 'std'
D:\work\Notepad++\project\tags\v7.7.1\scintilla\src\Document.h(256): error C2143: syntax error: missing ';' before '<'
D:\work\Notepad++\project\tags\v7.7.1\scintilla\src\Document.h(256): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
D:\work\Notepad++\project\tags\v7.7.1\scintilla\src\Document.h(256): error C2238: unexpected token(s) preceding ';'
D:\work\Notepad++\project\tags\v7.7.1\scintilla\src\Document.h(284): error C2039: 'unique_ptr': is not a member of 'std'
C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.12.25827\include\vector(15): note: see declaration of 'std'
D:\work\Notepad++\project\tags\v7.7.1\scintilla\src\Document.h(284): error C2143: syntax error: missing ';' before '<'
D:\work\Notepad++\project\tags\v7.7.1\scintilla\src\Document.h(284): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
D:\work\Notepad++\project\tags\v7.7.1\scintilla\src\Document.h(284): error C2238: unexpected token(s) preceding ';'
D:\work\Notepad++\project\tags\v7.7.1\scintilla\src\Document.h(562): error C2039: 'data': is not a member of 'Scintilla::Action'
D:\work\Notepad++\project\tags\v7.7.1\scintilla\src\CellBuffer.h(32): note: see declaration of 'Scintilla::Action'
D:\work\Notepad++\project\tags\v7.7.1\scintilla\src\Document.h(562): error C2228: left of '.get' must have class/struct/union
../boostregex/BoostRegexSearch.cxx(37): fatal error C1083: Cannot open include file: 'boost/regex.hpp': No such file or directory
NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.12.25827\bin\HostX86\x86\cl.EXE"' : return code '0x2'
Stop.

D:\work\Notepad++\project\tags\v7.7.1\scintilla\win32>

```

One difference may be that my MS Visual Studio is at 142 where I think the instructions suggest a compile with 140.

**Comment by sasumner** [comment]
@jlpoolen 

It doesn't help you, except maybe to encourage you, but I can successfully build Boost 1.70, and Scintilla and Notepad++ from 7.7.1 sources, following the instructions in the README.md file, except those instructions use VS2017 and I am using VS2019Enterprise (so I tweak the instructions, but only for that).

>MS Visual Studio is at 142

Yes, that is something that requires a project settings adjustment during build of Notepad++, but this shouldn't really affect you at the point you are in the full build process (Boost is first, N++ is third).

>compiling Boost with 64x and then trying to compile SciLever (_sic_) with a 32 bit compiler referencing the Boost regex lib in 64

I don't really understand this, the selection of compiler shouldn't be yours to make, directly.  But if there is some way that you are "mixing and matching 32 bits and 64 bits" in what you are doing, this is (fairly obviously) a bad idea.

**Comment by jlpoolen** [comment]
@sasumner  Thank you.  Yes, it is very helpful to have confirmation of a successful build for 7.7.1.  Your comment gives me a green light to keep trying.

**Comment by jlpoolen** [comment]
If I leave out the references to the Boost library and Boost home, compilation appears to be working.

https://pastebin.com/p1j05xmj

I went back to a previous version, 7.7, and tried and got the same result.  I'm concluding that there is something that is preventing the Boost Root to be seen.  For example, I threw a curve ball at the nmake command by specifying a non-existent dirctory and the results were the same:

**Comment by jlpoolen** [comment]
The problem looks to be that I was using an X64 command console.  I switched to an x86 command console (MS Visual Studio 2017) and looks like compiling worked.  I ran into the library not being found, but that missing library is something I think can easily be fixed by recreating it in a 32 bit environment.
Log showing compile up to linking failure: https://pastebin.com/pDjJCtKP

**Comment by sasumner** [comment]
@jlpoolen Would this have been avoided by this step from the README.md file?:

`From the IDE, you can do this by right clicking on a file in Solution Explorer, and clicking "Open Command Prompt". This will open up a command prompt with all the proper environment variables`

BTW pastebin may not be the best thing to use to get your point across; for me at least it gives the following, which is then followed up with my I.T. dept. not allowing me access:

![image](https://user-images.githubusercontent.com/30118311/63042715-9b38ad00-be98-11e9-863e-e9c2b25333ed.png)

**Comment by jlpoolen** [comment]
@sasumner 
 Yes, I had read the instructions.  But, I tend to avoid using contextual instructions where ambiguities may exists.  For my Microsfot Visual Studio 2019, there is no contextual command prompt when right clicking.  Here's a screenshot where I have selected a "file", AboutDlg.cpp, and the instruction would not apply.
![2019-08-14_11-14-25](https://user-images.githubusercontent.com/227313/63045525-6707c100-be85-11e9-9ddb-1bb049822e45.png)

I have had the experience in some other open source projects where defining which environment at the outset is an important specification, e.g. use an X86 command, or X64, or a Cross Compile x86_x64.  With all the choices, I prefer to take the harder approach so that it is clearly documented which environment is selected.  With all the changes products undergo with revisions, contextual instructions can become obsolete.

Also, thank you for the heads up re: Pastebin.  I've contacted the principal, but I suspect the issue has to do with self-signed certificates and will not change.  What a pity the Internet has become so locked down that companies/people will only visit sites that are duly certified.

Although I have not successfully built a working set, I'm satisfied that the problem starting this issue has been resolved with this caveat: be very mindful of what environment you are building within.  I moved forward in this matter by using an x86 shell instead of the x64 shell.

**Comment by sasumner** [comment]
@jlpoolen Oops, I had meant to copy this instead of what I did copy out of the instructions:

`From the Windows Start screen/menu, type Developer Command Prompt for VS2017, and click/select the result.`

That's what I did to build on VS2019.  Of course in my brain I changed 2017 to 2019.  Otherwise it wouldn't have been found on my system.  I guess I'm not as rigid as you, plus we've probably no right to expect any part of the instructions to work at all on VS2019.

**Comment by jlpoolen** [comment]
Yeah... I've seen the "Windows Start" approach, but the problem with that is I do not know which of the four environments disclosed at the lowest menu choice the generically named one is above them is.  I've been bitten too many times, as I have here, by not being meticulous about which environment of four should be used.  I'm a big fan of Gentoo (done lots of cross compiling and distributed compiling) and I've never experienced the confusion I do with Windows in selecting environments.   I tend to think when UI/interface designer try to help, they actually make things worse.

![2019-08-14_11-34-35](https://user-images.githubusercontent.com/227313/63046617-b5b65a80-be87-11e9-9970-cd9bbeedc4d5.png)

**Comment by sasumner** [comment]
Ah...well, when I started typing "deve(loper)" per the README.md file, it became pretty obvious what the choice should be:

![image](https://user-images.githubusercontent.com/30118311/63047114-c5429d00-bea1-11e9-9dce-6de4515a3ae7.png)
