### ISSUE TITLE
Right click copy always copies whole line in find results

### ISSUE THREAD

**Issue by Couchy** [notepad-plus-plus/notepad-plus-plus#6041]
Windows 10/Notepad++ 7.7.1

### Steps to Reproduce the Issue
1. Ctrl-F -> Find All in Current Document, search something
2. Highlight a section of a line in find results
3. Right click -> Copy

### Expected Behavior
Only the selected text should be copied.

### Actual Behavior
Right-click -> Copy always copies the whole line, not just the selection. Ctrl+C works as expected.

**Comment by sasumner** [comment]
Current behavior is by-design:

* Ctrl+c gets you a copy of exactly what you've selected (including line number or file info or search info)

* Right-click menu's copy gets you entire lines of only text from the original document (no line number info, etc).  Note that you don't have to have full lines selected, your first and/or last line can be partially selected.

**Comment by sasumner** [comment]
Actually, the `Find result` window right-click -> `Copy` is more powerful than I indicated earlier (note, the following isn't an exhaustive explanation, but just some quick observations):

* Right click copy without a selection on a `Search "...." (... hits in ... files)` line:  Will copy the search result text (no metadata) of all hit lines in all files under that search

* Right click copy without a selection on a `pathname (...hits)` line:  Will copy the search result text (no metadata) of all hit lines under that single file

* Right click copy without a selection on an individual `Line ... :` line: Will copy the search result text (no metadata) of only that line

Really, when you think about it, the lowly "Copy" text in the menu:

![image](https://user-images.githubusercontent.com/30118311/63048744-24ee7780-bea5-11e9-9ae7-f1e4ced602f3.png)

really should be more like `Copy SPECIAL!` :)
