### ISSUE TITLE
Build failure: error C4596 in ShortcutMapper.h

### ISSUE THREAD

**Issue by nkolotov** [notepad-plus-plus/notepad-plus-plus#6045]
Some member declarations in ShortcutMapper.h have extra `ShortcutMapper::` qualification causing standard conformant compilers to reject the code.

https://github.com/notepad-plus-plus/notepad-plus-plus/blob/ef13902206f80e00dcfd7d85b342066ed6f86d66/PowerEditor/src/WinControls/Grid/ShortcutMapper.h#L68

**Comment by sasumner** [comment]
Might have been reasonable to provide a link to the offending items.

**Comment by sasumner** [comment]
I guess a PR is an effective link. :)
