### ISSUE TITLE
Use of deprecated function std::bind2nd in WindowsDlg.cpp

### ISSUE THREAD

**Issue by nkolotov** [notepad-plus-plus/notepad-plus-plus#6049]
Function `std::bind2nd` has been deprecated in C++11 and then removed in C++17. [Use of this function  in WindowsDlg.cpp](https://github.com/notepad-plus-plus/notepad-plus-plus/blob/06db9ee338ac9659b01b960325486a1791b249b0/PowerEditor/src/WinControls/WindowsDlg/WindowsDlg.cpp#L783) is causing standard conformant compilers either to emit a warning or to reject the code.

**Comment by donho** [comment]
https://github.com/notepad-plus-plus/notepad-plus-plus/commit/e74cb34e22323b255ee9fc7603eb82f90cd60d28
