### ISSUE TITLE
Build failure: error C3861 in Sorters.h

### ISSUE THREAD

**Issue by nkolotov** [notepad-plus-plus/notepad-plus-plus#6051]
[Function `std::make_pair` is used without qualificator](https://github.com/notepad-plus-plus/notepad-plus-plus/blob/8b151ac991478a90d5064966f710ed566982c47e/PowerEditor/src/MISC/Common/Sorters.h#L292) and can not be found with argument-dependent lookup causing standard conformant compilers to reject the code.

**Comment by donho** [comment]
Please clarify your "Build failure" context.

**Comment by nkolotov** [comment]
So I have hard time trying to build notepad++. All the compilers that I've tried (vc++14.16, vc++14.22, clang5, clang7) will reject this code unless I switch to permissive mode. See [example](https://godbolt.org/z/g7ZxhS).

**Comment by donho** [comment]
The project file of Notepad++ is VC 2017 (Mine is 15.8.9) and the warning level is set the most strict & treat warning as error. I have no problem of compiling.
What do you mean by "permissive mode" ?

**Comment by nkolotov** [comment]
I've already answered the same question at [#6054
](https://github.com/notepad-plus-plus/notepad-plus-plus/pull/6054#issuecomment-521965028), but here is recap:

The project from the repo uses VS2015 (XP) toolset (vc++14.0 compiler). Perhaps project indeed builds fine with that compiler, but I haven't tried it. https://github.com/notepad-plus-plus/notepad-plus-plus/issues/6047, https://github.com/notepad-plus-plus/notepad-plus-plus/issues/6049, https://github.com/notepad-plus-plus/notepad-plus-plus/issues/6051, https://github.com/notepad-plus-plus/notepad-plus-plus/issues/6043 issues that I've reported describe problems when building using "standard conformant compilers". And by "standard conformant compilers" I mean compilers that claim to follow ISO C++ standard such as gcc and clang. Visual C++ has been notorious for doing things its own way, but recently MS [made a considerable efforts](https://devblogs.microsoft.com/cppblog/announcing-msvc-conforms-to-the-c-standard/) to [improve standard conformance](https://docs.microsoft.com/en-us/cpp/overview/cpp-conformance-improvements?view=vs-2019). As a result newer vc++ compilers have conformance mode that can be enabled with [`/permissive-` switch](https://docs.microsoft.com/en-us/cpp/build/reference/permissive-standards-conformance?view=vs-2019) (btw it is ON by default for new projects). While permissive mode still allows them to build most of invalid c++ code that was accepted by older vc++ compilers.

So in order to reproduce described build failures you need to (1) switch to newer toolset and corresponding Windows SDK, at least to 14.16 (2) disable permissive mode by toggling Project properties → C/C++ → Language → Conformance mode (3) optionally set target c++ standard on the same property page to c++14 or even to c++17. If you go further and enable [built-in static analysis](https://docs.microsoft.com/en-us/visualstudio/code-quality/code-analysis-for-c-cpp-overview?view=vs-2019) there additionally will be ~400 warnings reported. It may also be beneficial to set up clang build as well because clang offers better conformance and issues clearer diagnostics.

Btw why does the project use VS2015 (XP) toolset instead of VS2017 (XP) toolset even though you use VS2017? Even if there is a particular reason to still use legacy VS2015 tools making code standard conformant will keep it future proof and will certainly make life of the developers using up-to-date tools easier.

**Comment by donho** [comment]
I tried to enable "/permissive-" in Notepad++ project but in vain:
![image](https://user-images.githubusercontent.com/90293/63197980-a5fe6800-c079-11e9-9d6a-00f6624dcd2f.png)

Adding `<ConformanceMode>true</ConformanceMode>` in `<ClCompile>` node into `notepadPlus.vcxproj` doesn't enable the option as well.

Could you send me your `notepadPlus.vcxproj` so I can add this option into the project please?

**Comment by nkolotov** [comment]
[notepadPlus.vcxproj](https://gist.github.com/nkolotov/fafcebf940d10d6c441666afe0102fa0#file-notepadplus-vcxproj)

Hmm, this is strange. Have you switched to newer toolset? when I open property editor it shows considerably more options:
![npppprops](https://user-images.githubusercontent.com/50573584/63200257-4019dc80-c089-11e9-8d77-fe6392290075.png)

**Comment by donho** [comment]
@nkolotov  Thank you for your help.
Using toolset v141 does the trick (to make appear Conformance Mode option), but it's necessary to change Windows SDK 8.1 to 10 to make project compile.
toolset v140 xp is for the retro-compability - Thanks it Notepad++ latest version is working under XP. 
I will set the project with "/permissive-" for dev, but on release machine will be 
```
Windows SDK Version: 8.1
Platform Toolset: Visual Studio 2015 (v140_xp)
Conformance Mode: Yes
```
Have you a better suggestion?

**Comment by nkolotov** [comment]
The frustrating thing about npp repo is that there are too many differently executed parts in it: there is VS solution, nmake file for scintilla, (abondoned?) make file, cmake file, some batch files for installer, powershell file tests. I feel like it would be much better to bring all components under one hood by making full-fledged VS solution that would contain a project hierarchy that looks something like this:

`┌  NppInstaller`
`├ NppTests ───────────────────────────────────────────────────────┐`
`├ NppExecutable (v140 xp toolset) ────────────────────────────────┼─ Scintilla dll`
`└ NppExecutable (v141 toolset, conformance mode, static analysis) ┘`

This way executable to be published will be still compatible with XP, however building installer will require that project based on modern toolset and tests are successfully built as well. Developers could easily switch between projects using older and newer toolsets without switching git branches. It seems that most of the settings for NppExecutable projects could be shared so keeping both projects synchronized shouldn't be that troublesome.

**Comment by donho** [comment]
> The frustrating thing about npp repo is that there are too many differently executed parts in it:

https://github.com/notepad-plus-plus/notepad-plus-plus#to-build-notepadexe

>  Developers could easily switch between projects using older and newer toolsets without switching git branches.

To be clear: Dev (the contributors include me) and release (only me currentely) will use only master branch. However, on the release machine SDK and toolset will be remained the old settings for the sake of retro-compatibility. and these settings won't be committed into master.

**Comment by xylographe** [comment]
@donho 
I think, this means that some PR might work fine if applied to the master branch, but not when build with the v140_xp toolset on the release machine. Perhaps, you might make the release machine settings available in a separate branch, to enable contributors to test before submitting PR?

**Comment by sasumner** [comment]
I would like to see one "solution" that would allow one to easily build their choice of Boost, Scintilla, and Notepad++.   This would include the capability to use interactive debugging on each component.  

When looking into regular expression issues, I often start out single-step debugging in Notepad++ sources, then get into Scintilla, and finally into Boost.  While I don't think I could seamlessly do all of this at one time, with an easy way to build and prepare for debug each component separately, I could better track something from the top (Notepad++ code) to the bottom (Boost code).
