### ISSUE TITLE
Auto completion suggest-dialog-box overlapping the current-writing-text

### ISSUE THREAD

**Issue by shekharrai** [notepad-plus-plus/notepad-plus-plus#6057]
It's a low priority issue as it depends on the individuals and their preferences. But i'm feeling quite annoying so i had to disable this feature on my installed-notepad ++ to make life easier.

On Ubuntu 18 (Not sure on other OSs though :)), the auto-completion suggest box is overlapping the current content and not able to track the characters what i'm writing.

### Steps to Reproduce the Issue
1. You can simply enable the auto-configuration through settings -> preferences
2. Now type the same word that you're using repeatedly
3. There you go -> the auto-suggestion box

![overlapping](https://user-images.githubusercontent.com/20252648/63086545-d659df80-bf6f-11e9-92b4-37a2d60d5522.png)

### Auto suggestion box should be under that text
I'm expecting the suggest box should appear a little bit below-coordinate from the text that you're writing. So that it makes easier to type and track what you're writing so far.

**Comment by Ekopalypse** [comment]
It looks like on Ubuntu it renders the window with the border which it shouldn't in this case. 
This doesn't happen on windows, and as this is a windows project it is not likely that there is
something  going to chance in this area, sorry.

![image](https://user-images.githubusercontent.com/47723516/63093536-30997700-bf55-11e9-982f-ef025d4f272e.png)
