### ISSUE TITLE
Custom Language: Block Comment / Line Comment conflict

### ISSUE THREAD

**Issue by katzenpapst** [notepad-plus-plus/notepad-plus-plus#6061]
### Description of the Issue
If you define a custom language, where the block comment start marker begins with the symbol which is also the line comment marker, the line comment takes precedence.

My use-case is Bethesda's script language Papyrus, where line comments begin with `;`, and multiline comments begin with `;/` and end with `/;`

### Steps to Reproduce the Issue
1. Open the "User Defined Language" dialog, set the language of current document to "User Defined"
2. Put `;/` and `/;` as block comment markers, give it an easy-to-see color
3. Write some multiline text, use `;/` and `/;` to comment out some of them
4. In the "User Defined Language" window, put in `;` as "Comment start" under "Line Comments"

### Expected Behavior
The commented-out part of the text staying as is. The longer sequence taking precedence over the shorter.

### Actual Behavior
Syntax highlighting changes, the line containing the `;/` taking on the color set up for line comments

### Debug Information
Notepad++ v7.7.1   (64-bit)
Build time : Jun 16 2019 - 21:24:47
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 7 (64-bit)
Plugins : ComparePlugin.dll mimeTools.dll NppConverter.dll NppExec.dll

**Comment by Ekopalypse** [comment]
In such a case where one starting token is the same as part of another token use delimiters.
Define the comment line  start=; and end=((EOL)) as a delimiter and the ;/ and /; as multiline comment.

**Comment by katzenpapst** [comment]
Either am I not getting it, or it isn't working.
This is what I tried doing. Sorry for my german:

https://i.imgur.com/wI0DV5l.png

**Comment by Ekopalypse** [comment]
Delete the line comment setting and define an delimiter instead
Den Zeilenkommentar löschen und stattdessen einen Delimiter definieren
![image](https://user-images.githubusercontent.com/47723516/63212495-dfc08480-c0f4-11e9-86b4-9d3338680b31.png)

**Comment by katzenpapst** [comment]
Works. Thank you!

**Comment by Ekopalypse** [comment]
@katzenpapst - would you mind closing this issue?
