### ISSUE TITLE
Incorrect font used to draw captions of document tabs when non-reduced.

### ISSUE THREAD

**Issue by nkolotov** [notepad-plus-plus/notepad-plus-plus#6069]
When "Reduced" option for tab bar is disabled in settings "system" font will be used for tab captions. This font lacks cleartype antialiasing, moreover, it has reduced set of symbols so most of Unicode file names will be displayed using symbols from some other font (that may or may not have cleartype antialiasing) causing captions to be rather messed up.
![tab bar problem](https://user-images.githubusercontent.com/50573584/63210939-64150680-c0f9-11e9-8c5c-798719c49c94.png)

**Comment by donho** [comment]
https://github.com/notepad-plus-plus/notepad-plus-plus/pull/6070#issuecomment-524455571
