### ISSUE TITLE
Option to revert to old session behavour

### ISSUE THREAD

**Issue by TheDeadFish** [notepad-plus-plus/notepad-plus-plus#6073]
Quite some time ago (several years) the session behavior was changed such that modified files are saved on exit without any prompt and reloaded on next startup. This behavior is very unhelpful, I have no idea what to do with such modified files as I can't remember what I changed, and in some cases have lost work because of this due to the lack of undo history.

It would be nice if it were possible to return to the old behavior where a prompt asks to save files on exit. I have not upgraded for years because of this and several other issues related to adding new features which could not be turned off.

**Comment by Ekopalypse** [comment]
Isn't Settings->Preferences->Backup and **uncheck** _Enable session snapshot and periodic update_
what you are looking for?

**Comment by TheDeadFish** [comment]
Ok now I feel like a retard.
At one point there was not way to disable this without turning off session support but it seems it is possible now.
