### ISSUE TITLE
Find-All-in-All-Opened-Documents searches cloned document two times

### ISSUE THREAD

**Issue by sasumner** [notepad-plus-plus/notepad-plus-plus#6074]
### Description of the Issue
If I have a cloned document open in both views, a `Find All in All Opened Documents` search that has hits in the document will report each and every hit two times in the `Find result` window.

### Steps to Reproduce the Issue

1. Open the `change.log` file.
2. Right-click its tab and choose `Clone to Other View`.
3. Invoke `Find` (ctrl+f).
4. Put `enhancements` into `Find what`, all other options unticked.
5. Press `Find All in All Opened Documents` button.

### Expected Behavior
I expect, since it is the same document in both views (because it is cloned), that I would only get unique hits in `Find result`, i.e., a second, unnecessary search of the file would not be conducted.  For the example given I would expect to see `1 hit in 1 file`.

### Actual Behavior
The same hits are reported twice in `Find result`, see screenshot below; for the example provided I see `2 hits in 2 files`.

### Debug Information
Notepad++ v7.7.1   (64-bit)
Build time : Jun 16 2019 - 21:24:47
Path : C:\........\notepad++.exe
Admin mode : OFF
Local Conf mode : ON
OS : Windows 10 (64-bit)
Plugins : mimeTools.dll NppConverter.dll 

![image](https://user-images.githubusercontent.com/30118311/63273378-ddcd0180-c26b-11e9-8d82-872cc254ea60.png)

**Comment by SinghRajenM** [comment]
@sasumner , this is fixed. So good to close defect, right?

**Comment by sasumner** [comment]
@SinghRajenM Odd that @donho didn't close it when he committed the PR to N++ master.  Regardless, yes this feature is in Notepad++ 7.8 and this can be closed, which I will now do. :-)
