### ISSUE TITLE
Feature Request Cascading Mark/Hi-lite colour option

### ISSUE THREAD

**Issue by Montgomeryz** [notepad-plus-plus/notepad-plus-plus#6076]
Hello. Would you please consider adding a feature in the Mark dialog box so that each search expression can be marked a different colour? For example 'Fred' is hi-lighted pink and 'Jane' is hi-lighted green.. Thanks :)

**Comment by sasumner** [comment]
If your `Search mode` is `Normal` (meaning your search text is constant), have you tried selecting your constant text and then using `Search` (menu) -> `Mark All` -> `Using` xxx `Style` ?  Maybe that satisfies?

Of course if your search text is a regular expression, the "Style" suggestion doesn't work at all...  But it could work for up to 5 constant expressions and one regular expression (the regex one using the `Mark...` dialog.

**Comment by Montgomeryz** [comment]
^ that's a good workaround, thanks.
