### ISSUE TITLE
A bug for Notepad++

### ISSUE THREAD

**Issue by yunfan188** [notepad-plus-plus/notepad-plus-plus#6078]
I found a bug about auto-input. 
On the setting->Preference->auto-complete->auto-input, I select the (), [], {}, "", ''.
When I edit code, () -->(())，it can auto input, that`s OK, however, (1) --> (1())，it can`t work, rather then it becomes (1(), even if I press the “shift+( + )” keys, it still becomes (1(), and then I press "ctrl+z" keys, it can become the normal format (1()). The issuse has same behavior on other symbols, like [].

**Comment by bib12ag** [comment]
I fixed that bug.
In the 'insertMatchedChars()' of 'Autocompletion.cpp', several lines have been commented out so that they can be completed in parentheses and brackets.
Just comment out only `if (isCharNextBlank || isInSandwich)` for each switch case ( '(', '[', '{' ).

**Comment by ganego** [comment]
See also: https://github.com/notepad-plus-plus/notepad-plus-plus/issues/1038

**Comment by ganego** [comment]
Holy crap, after four years you finally fixed it and I no longer have to compile Npp myself.
Thank you @donho
