### ISSUE TITLE
Dragging open file tab sometime crashes

### ISSUE THREAD

**Issue by ashter01d** [notepad-plus-plus/notepad-plus-plus#6082]
### Description of the Issue

When trying to drag the open file tab to reorder and change its position among other tabs
sometimes NPP clones the dragged tab with weird name in chinese symbols.
The original tab stays in the same place.
After that happens, it's impossible to close NPP.
File->Exit doesn't work.
Closing window with X in top right corner doesn't work.
The cloned tab with weird name doesn't display tooltip with full path.
It's impossible to close the cloned tab, trying to close it closes the adjacent tab and only 1 time.

### Steps to Reproduce the Issue

*** 1. I'm working with NppFTP on php, css and js files.
*** 2. Usually have 10 or more open tabs.
*** 3. Can be working for 2 days before crash. (Computer is turned ON always).
*** I open and close tabs alot, editing different files on 2-3 ftps, switching between them.
*** after trying to reproduce the bug, these steps are not necessary.

1. Just open Notepad with a previous session, having many tabs open.
2. Drag any open file tab or try closing some tabs first, and then drag.
3. Also sometime tabs move erroneously, unpredictable. Hard to move the tab into correct place.
### Expected Behavior

The tab should just move to new position

### Actual Behavior

The tab cloned itself, the original tab stayed in same place.

### Debug Information

Notepad++ v7.7.1   (32-bit)
Build time : Jun 16 2019 - 21:14:50
Path : F:\Soft\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : ON
OS : Windows 7 (64-bit)
Plugins : JSMinNPP.dll mimeTools.dll NppConverter.dll NppExport.dll NppFTP.dll 

![nppbug](https://user-images.githubusercontent.com/54375099/63461932-64e3ca80-c462-11e9-8d34-cf23a5120afd.jpg)
![nppbug_should_be_this](https://user-images.githubusercontent.com/54375099/63461940-67debb00-c462-11e9-976d-d295decb9be0.jpg)

**Comment by ashter01d** [comment]
![npp_tab_again](https://user-images.githubusercontent.com/54375099/63465230-7f6d7200-c469-11e9-9527-3eb8661f506f.jpg)
I managed to catch this bug again in under 30 minutes.

Just opened 10-20 files, closed, open closed.
Tried to drag tab and here we go...

**Comment by ashter01d** [comment]
![nppcloness](https://user-images.githubusercontent.com/54375099/63465433-f145bb80-c469-11e9-972b-90bcdfc73135.jpg)
Tried dragging the weird tab and now it cloned itself

**Comment by ashter01d** [comment]
![noftp](https://user-images.githubusercontent.com/54375099/63465580-39fd7480-c46a-11e9-83c5-5e7a59ade03f.jpg)
After restarting Npp, I didn't even use the FTP plugin,
i just closed a couple of tabs - and then started dragging one tab - bug again.
So no need to open files with FTP.

**Comment by ashter01d** [comment]
Another bug with dragging tabs.
1. Open notepad++
2. Select last tab on the right ('test.txt')
![drag1](https://user-images.githubusercontent.com/54375099/63466540-205d2c80-c46c-11e9-90d5-0da656795dd8.jpg)

3. Press and just hold left mouse button on the 2nd tab from the right ('style.css')
![drag2](https://user-images.githubusercontent.com/54375099/63466543-22bf8680-c46c-11e9-8f58-b9a66bb648f6.jpg)
![drag3](https://user-images.githubusercontent.com/54375099/63466545-24894a00-c46c-11e9-8db1-2648ad3614b5.jpg)
4. Last tab('test.txt') jumps in place of 2nd tab ('style.css') from the right.
5. Now you are dragging last tab('test.txt')

**Comment by ArkadiuszMichalski** [comment]
@ashter01d Still having this problem in the current version of Notepad ++? Also check without external plugins.

**Comment by ashter01d** [comment]
I think it wasn't Notepad++ fault, just incorrect RAM timing settings in BIOS.
