### ISSUE TITLE
Dragging tabs after starting Notepad++ with a previous session

### ISSUE THREAD

**Issue by ashter01d** [notepad-plus-plus/notepad-plus-plus#6084]
### Description of the Issue

After opening Notepad++ with a previous session, and trying to drag a tab that is not currently selected results in currently selected tab jumping into its place.
### Steps to Reproduce the Issue

1. Open notepad++ (with a session saved before), having many tabs open (7-11 tabs is not enough, but 12 or more triggers the glitch)
![drag1](https://user-images.githubusercontent.com/54375099/63466540-205d2c80-c46c-11e9-90d5-0da656795dd8.jpg)
2. Press and just hold left mouse button on any other tab, excluding already selected one
here i try dragging ('style.css')
![drag2](https://user-images.githubusercontent.com/54375099/63466543-22bf8680-c46c-11e9-8f58-b9a66bb648f6.jpg)
3. Originally selected tab('test.txt') jumps in place of newly selected tab ('style.css') after 1-2 seconds
![drag3](https://user-images.githubusercontent.com/54375099/63466545-24894a00-c46c-11e9-8db1-2648ad3614b5.jpg)
4. Now you are dragging initially selected tab('test.txt')

OR
1a Drag some tabs
2a Select and hold LMB on another tab - sometimes it will be replaced by previous tab.
So this bug can appear many times during lifetime of Notepad++ process.
Close Npp, open and repeat, to get the bug again.
### Expected Behavior

Newly selected tab should stay selected and in same place.
I didn't even move the cursor while holding LMB.
I just waited 2 seconds while pressing the button.

### Actual Behavior

Initially selected tab jumped in place of my newly selected tab and now I'm dragging it without releasing the mouse button.
### Debug Information

Notepad++ v7.7.1   (32-bit)
Build time : Jun 16 2019 - 21:14:50
Path : F:\Soft\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : ON
OS : Windows 7 (64-bit)
Plugins : JSMinNPP.dll mimeTools.dll NppConverter.dll NppExport.dll NppFTP.dll

**Comment by ArkadiuszMichalski** [comment]
Anyone can reproduce this?

**Comment by ashter01d** [comment]
There is no problem when using same version (7.7.1) of notepad++ with Windows 10 x64 on my notebook.
Probably should close the issue?

**Comment by ArkadiuszMichalski** [comment]
Version 7.7.1 is obsolete. But if a similar problem occurs in the current version, please let us know.
