### ISSUE TITLE
Regression: Dragging and dropping a tab prevents clicking on other tabs

### ISSUE THREAD

**Issue by ismael-miguel** [notepad-plus-plus/notepad-plus-plus#6085]
### Description of the Issue
On previous version, there was a bug where having the option "General" > "Tab Bar" > "Lock" disabled, and then dragging and dropping a tab (to re-order) would make it so you couldn't click on other tabs.

To fix this, you could need to restart Notepad++ or return the tab to the original position.

On version 7.7.1 x32, on wine-4.0.1 (obtained from `wine --version`) on Linux Mint 19.1, the issue is back.

### Steps to Reproduce the Issue

1. Make sure that "General" > "Tab Bar" > "Lock" is disabled
2. Drag a tab (1 position should be enough)
3. Click on another tab

### Expected Behavior
Expected to switch to the other tab.

### Actual Behavior
The tabs flash and won't switch. Re-ordering the tab to the older position fixes this.

### Debug Information
Notepad++ v7.7.1   (32-bit)
Build time : Jun 16 2019 - 21:14:50
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : ON
Local Conf mode : OFF
OS : Windows 7 (64-bit)
Plugins : ComparePlugin.dll DSpellCheck.dll mimeTools.dll NppConverter.dll NppExport.dll NppFTP.dll

**Comment by ArkadiuszMichalski** [comment]
@ismael-miguel You still have this problem in latest Notepad++ verison?

**Comment by donho** [comment]
It could be outdated. This issue will be reopened if there's a positive answer from issue author.
