### ISSUE TITLE
Automatic Windows 10 update closes all tabs

### ISSUE THREAD

**Issue by NicolasGoeddel** [notepad-plus-plus/notepad-plus-plus#6086]
### Description of the Issue
If Windows 10 decides to restart itself to make updates over night and I come back to my computer the next day all tabs in Notepad++ are gone. I had over 30 unsaved tabs open because I use it for notes, code fragments, logs and all these things.
I am using Notepad++ 7.7.1 without any additional third party extensions.

### Steps to Reproduce the Issue
1. Open some new tabs.
2. Wait until Windows decides to automatically update and restart your system.
3. Notepad++ seems to restart but all tabs are gone.

### Expected Behavior
After a Windows update with restarting the system I want to see all the tabs that were open before. I want to see the same behaviour as when I close Notepad++ and start it again.

### Actual Behavior
When Windows decides to update and restart all tabs are gone.

### Backup
It seems I can use the backup files located in %APPDATA%\Notepad++\backup but that is not the same as unsaved tabs. Would be better if there were a button to just restore all the unsaved tabs from the backup directory.

**Comment by xylographe** [comment]
The NPP session is only saved on a **clean** exit. If Windows crashes, or forces a restart, nothing will be saved.

**Comment by NicolasGoeddel** [comment]
I am not very experienced with that but there is a mechanism to save the application and data state when it is being closed due to a software update. You can read more about that here: https://docs.microsoft.com/de-de/windows/win32/recovery/registering-for-application-recovery#update
Maybe this helps also: https://code.msdn.microsoft.com/windowsdesktop/Windows-Restart-and-cc461aa9

**Comment by DavidHansen-0x454d43** [comment]
Nice find @NicolasGoeddel! 

I think it would be really great if NPP preserved unsaved tabs on a Windows update initiated restart.

**Comment by jmacgowa-ks** [comment]
I also experienced this same session (tabs) loss when Windows 10 forced an update a few days ago. Then it happened again a few days later when I went to properly shutdown Windows and the shutdown was delayed due to NPP. I cancelled the shutdown and went back to the desktop. NPP had a popup open about a file that had been modified, outside of the app. Once I clicked deny, to reloading the file, all of my tabs disappeared and NPP remained open. The session.xml file is now empty, but all of the backed up unsaved files remain.

If this was a problem with NPP not being able to save the session.xml file, I should only be missing recent tabs. Instead it has time to overwrite the session.xml file with a clean slate.

This appears to be a recently introduced bug in Windows 10 or NPP 7.7.1. I have never had a problem with my tabs (session) disappearing before and I have done plenty of dirty resets.

**Comment by webketje** [comment]
@NicolasGoeddel @jmacgowa-ks Have you installed Notepad++ under `%programFiles%`? In that case, the data in `%appdata%\Notepad++\config` may have been wiped. To avoid this in the future, install Notepad++ *outside* of `%programFiles%`

**Comment by NicolasGoeddel** [comment]
@webketje Of course I installed it there. That's the correct folder for installing applications. I don't want to populate any other folder with applications. I know that applications have to write their user data to %appdata% but this has nothing to do with this issue. The folder didn't get wiped. The backups were still there. That's how I retrieved all the unsaved tabs I thought I had lost.

**Comment by kaiof** [comment]
This just happened to me again last night (lost open tabs with Windows update, npp v7.7.1) and I checked Settings to find the "autosave" checkbox inexplicably off again. I've opened a previous issue #5831 on this (linked for cross reference / reproduction).

**Comment by NicolasGoeddel** [comment]
It happened again to me last night. Fucking Windows decides to restart my computer over night and now Notepad++ has lost all its tabs. However they are still in the backup folder but I don't know to open them as not-saved-files again. If there is a backup folder why is there no restore button?

**Comment by xylographe** [comment]
Unfortunately, the session file, which contains all information about open tabs, is only saved when NPP terminates normally — **File > Exit** or Close box.

**Comment by sasumner** [comment]
A *possible* answer might be to not work with unnamed files, and don't leave named-but-unsaved files in the unsaved state for too long.  Not what you want to hear, I'm sure, but I've read too many stories of data loss to personally work in a way different from what I described.

**Comment by NicolasGoeddel** [comment]
What does `accepted` mean? Will it get fixed? Is it already fixed? Or do I have to save all my small notes to single text files now?

**Comment by webketje** [comment]
@NicolasGoeddel Judging from the code changes, comments in the linked commit (62efa46) & a cursory look at MS docs, it should.

As soon as this ships in a release (or is shipped), you should be able to test it by simply logging off as behind the scenes the procedure is the same.

**Comment by donho** [comment]
Fix by https://github.com/notepad-plus-plus/notepad-plus-plus/commit/6000f3bb21a42a4d28d068617e0dc642ef739b26
