### ISSUE TITLE
in disassembly "RtlDispatchException:"

### ISSUE THREAD

**Issue by furkankartt** [notepad-plus-plus/notepad-plus-plus#6088]
00007FFAA80EA15A  mov         r8,rax  
00007FFAA80EA15D  lea         rdx,[rbp+18h]  
00007FFAA80EA161  mov         rcx,r15  
00007FFAA80EA164  call        RtlLookupFunctionEntry (07FFAA809E2A0h)  
00007FFAA80EA169  mov         r13,rax  
00007FFAA80EA16C  test        rax,rax  
00007FFAA80EA16F  je          memset+1CA0Dh (07FFAA813F98Dh)  
00007FFAA80EA175  mov         rdx,qword ptr [rbp+18h]  
00007FFAA80EA179  lea         rax,[rbp+10h]  
00007FFAA80EA17D  mov         qword ptr [rsp+38h],rbx  
00007FFAA80EA182  mov         r9,r13  
00007FFAA80EA185  mov         qword ptr [rsp+30h],rax  
00007FFAA80EA18A  mov         r8,r15  
00007FFAA80EA18D  lea         rax,[rbp+20h]  
00007FFAA80EA191  mov         ecx,1  
00007FFAA80EA196  mov         qword ptr [rsp+28h],rax  
00007FFAA80EA19B  mov         qword ptr [rsp+20h],r14  
00007FFAA80EA1A0  call        RtlVirtualUnwind (07FFAA809CC60h)  
00007FFAA80EA1A5  mov         rdx,qword ptr [rbp+10h]  
00007FFAA80EA1A9  lea         r8,[rbp+30h]  
00007FFAA80EA1AD  lea         rcx,[rbp+38h]  
00007FFAA80EA1B1  mov         r12,rax  
00007FFAA80EA1B4  call        RtlpIsFrameInBounds (07FFAA80EA37Ch)  
00007FFAA80EA1B9  test        al,al  
00007FFAA80EA1BB  je          memset+1CA59h (07FFAA813F9D9h)  
00007FFAA80EA1C1  test        r12,r12  
00007FFAA80EA1C4  je          RtlDispatchException+247h (07FFAA80EA257h)  
00007FFAA80EA1CA  mov         rcx,qword ptr [rbp+20h]  
00007FFAA80EA1CE  mov         eax,ebx  
00007FFAA80EA1D0  mov         r8,qword ptr [rbp+18h]  
00007FFAA80EA1D4  mov         qword ptr [rbp+88h],rcx  
00007FFAA80EA1DB  mov         rcx,qword ptr [rbp+8]  
00007FFAA80EA1DF  mov         qword ptr [rbp+90h],rcx  
00007FFAA80EA1E6  mov         dword ptr [rsi+4],edi  
00007FFAA80EA1E9  mov         qword ptr [rbp+50h],r15  
00007FFAA80EA1ED  mov         qword ptr [rbp+58h],r8  
00007FFAA80EA1F1  mov         qword ptr [rbp+60h],r13  
00007FFAA80EA1F5  mov         qword ptr [rbp+68h],rdx  
00007FFAA80EA1F9  mov         qword ptr [rbp+78h],r14  
00007FFAA80EA1FD  mov         qword ptr [rbp+80h],r12  
00007FFAA80EA204  mov         dword ptr [rbp+98h],eax  
00007FFAA80EA20A  cmp         byte ptr [rbp],bl  
00007FFAA80EA20D  jne         memset+1C947h (07FFAA813F8C7h)  
00007FFAA80EA213  mov         r15,rbx  
00007FFAA80EA216  mov         r13,qword ptr [rbp+40h]  
00007FFAA80EA21A  lea         r9,[rbp+50h]  
00007FFAA80EA21E  mov         r8,r13  
00007FFAA80EA221  mov         rcx,rsi  
00007FFAA80EA224  call        RtlpExecuteHandlerForException (07FFAA8121190h)  
00007FFAA80EA229  mov         edx,eax  
00007FFAA80EA22B  test        r15,r15  
00007FFAA80EA22E  jne         memset+1C964h (07FFAA813F8E4h)  
00007FFAA80EA234  mov         ecx,dword ptr [rsi+4]  
00007FFAA80EA237  mov         r12,qword ptr [rbp+28h]  
00007FFAA80EA23B  and         ecx,1  
00007FFAA80EA23E  or          edi,ecx  
00007FFAA80EA240  cmp         r12,qword ptr [rbp+10h]  
00007FFAA80EA244  je          memset+1C970h (07FFAA813F8F0h)  
00007FFAA80EA24A  test        edx,edx  
00007FFAA80EA24C  je          RtlDispatchException+31Ch (07FFAA80EA32Ch)  
00007FFAA80EA252  sub         edx,1  
00007FFAA80EA255  jne         RtlDispatchException+273h (07FFAA80EA283h)  
00007FFAA80EA257  mov         rdx,qword ptr [r14+98h]  
00007FFAA80EA25E  lea         r8,[rbp+30h]  
00007FFAA80EA262  mov         r15,qword ptr [r14+0F8h]  
00007FFAA80EA269  lea         rcx,[rbp+38h]  
00007FFAA80EA26D  call        RtlpIsFrameInBounds (07FFAA80EA37Ch)  
00007FFAA80EA272  test        al,al  
00007FFAA80EA274  je          memset+1CA5Ch (07FFAA813F9DCh)  
00007FFAA80EA27A  mov         rax,qword ptr [rbp+8]  
00007FFAA80EA27E  jmp         RtlDispatchException+14Ah (07FFAA80EA15Ah)  
00007FFAA80EA283  sub         edx,1  
00007FFAA80EA286  je          memset+1C9F3h (07FFAA813F973h)  
00007FFAA80EA28C  cmp         edx,1  
00007FFAA80EA28F  jne         memset+1CA43h (07FFAA813F9C3h)  
00007FFAA80EA295  mov         r12,qword ptr [rbp+58h]  
00007FFAA80EA299  mov         rcx,r14  
00007FFAA80EA29C  mov         rdx,qword ptr [rbp+78h]  
00007FFAA80EA2A0  mov         r15,qword ptr [rbp+50h]  
00007FFAA80EA2A4  mov         r13,qword ptr [rbp+60h]  
00007FFAA80EA2A8  mov         qword ptr [rbp+18h],r12  
00007FFAA80EA2AC  call        RtlpCopyContext (07FFAA809E090h)  
00007FFAA80EA2B1  mov         qword ptr [rsp+38h],rbx  
00007FFAA80EA2B6  lea         rax,[rbp+10h]  
00007FFAA80EA2BA  mov         qword ptr [rsp+30h],rax  
00007FFAA80EA2BF  mov         r9,r13

**Comment by sasumner** [comment]
You need to follow the issue template.  If you do so and it is coherent and understandable, will consider reopening.

**Comment by furkankartt** [comment]
No problem in template.
