### ISSUE TITLE
Red underline doesn't go away even after user correct wrong spelling

### ISSUE THREAD

**Issue by Laxitas** [notepad-plus-plus/notepad-plus-plus#6089]
### Steps to Reproduce the Issue

1. Add any wrong spelling in notepad++ editor and make sure underline shows
2. Correct that spelling 
3. 

### Expected Behavior
It should remove underline after correcting spelling

### Actual Behavior
It isn't removing underline after correcting spelling

**Comment by sasumner** [comment]
Spell-checking plugins aren't part of Notepad++ core.  This "issues" list and code site is for Notepad++ core.  Please find a correct site (hint: find the home of the spell-check plugin you are using) for reporting your problem.
