### ISSUE TITLE
Notepad++ scrolls to top when switching tabs with word wrap

### ISSUE THREAD

**Issue by Kiriot22** [notepad-plus-plus/notepad-plus-plus#6090]
### Description of the Issue

When notepad++ word wrap wraps a very long line of text, after switching tabs it will scroll to few lines before the long line, or to the top.
### Steps to Reproduce the Issue

1. Enable word wrap under View > Word wrap
2. Put a lot of text into a single line, so that it doesn't fit on the screen
3. Scroll down, click a spot in the text
4. Switch to another tab and then back

### Expected Behavior

The view stays the same as before switching tabs, the scrollbar stays in place
### Actual Behavior

The view gets scrolled a few lines before the long line or to the top
### Debug Information

Notepad++ v7.7.1   (32-bit)
Build time : Jun 16 2019 - 21:14:50
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10 (64-bit)
Plugins : mimeTools.dll NppConverter.dll NppExport.dll 

![40DDVehfnu](https://user-images.githubusercontent.com/9750071/63620881-d8b4dd00-c5f2-11e9-83ec-fd36a9480f0d.gif)

**Comment by sasumner** [comment]
Related to #4825 ?

**Comment by Kiriot22** [comment]
> Related to #4825 ? ...among others...

Oh, I didn't see that when searching, thanks
