### ISSUE TITLE
Deleting a link while hovering it causes a visual bug

### ISSUE THREAD

**Issue by AbrahamBrookes** [notepad-plus-plus/notepad-plus-plus#6091]
This is an odd bug, I hope I'm not the only one getting it.

### Description of the Issue
When hovering the mouse over a url in a php document, the cursor changes to a pointer, and the link becomes underlined, and changes color (depending on your color theme). If you delete a link while hovering it, the next batch of text left after the deleted text retains the link styling.

### Steps to Reproduce the Issue
1. Select a text block containing a link by clicking and dragging to highlight
2. Press delete
3. Press ctrl+z to undelete
4. Hover the link and confirm the syling changes to underline and color change
5. Press ctrl+y to re-delete

### Expected Behavior
Normal deleting behaviour

### Actual Behavior
The text gets deleted, but the styling is re-applied to nearby text, and cannot be removed

cheers

**Comment by Ekopalypse** [comment]
I can, somehow, replicate it with the following scenario.
Having a text like
`https://github.com/notepad-plus-plus/notepad-plus-plus/issues/6091 other text`
Now when doing what has been described, the **other text** does get underlines BUT it disapears
as soon as you move the mouse cursor, at least it does for me using

Notepad++ v7.7.1   (64-bit)
Build time : Jun 16 2019 - 21:24:47
Path : D:\Tests\npp\771\x64\notepad++.exe
Admin mode : OFF
Local Conf mode : ON
OS : Windows 7 (64-bit)
Plugins : DSpellCheck.dll mimeTools.dll NppConverter.dll

**Comment by ArkadiuszMichalski** [comment]
@Ekopalypse Can you still reproduce this bug in the latest version of Notepad ++?

**Comment by Ekopalypse** [comment]
@ArkadiuszMichalski Nope - seems to be fixed, at least for me.
