### ISSUE TITLE
[Feature request] Auto hide tab bar

### ISSUE THREAD

**Issue by jairocontreras** [notepad-plus-plus/notepad-plus-plus#6098]
I would like to automatically hide the tab bar when there is only one file open. Thanks!

**Comment by YakovL** [comment]
@sasumner thanks for providing a possible solution. Could you explain where such script should be added (or give a link to the corresponding docs)?

**Comment by sasumner** [comment]
@YakovL 

Here are some nice instructions:
https://community.notepad-plus-plus.org/post/57653
which I will repeat here:

1. Install PythonScript using Plugins > Plugins Admin
2. Plugins > Python Script > New Script
3. Paste the contents of the script above and save under someName (whatever name you want)
4. Run the script by: Plugins > Python Script > Scripts > someName
5. To add a keyboard shortcut for the script:
6. Plugins > Python Script > Configuration,
7. select the someName script and Add to the menu
8. Restart Notepad++
9. someName will now be in the main Plugins > Python Script menu, not just in the Scripts submenu
10. Settings > Shortcut Mapper > Plugin Commands will see the script, and you can assign a keyboard shortcut

It is also possible to run it automatically when Notepad++ starts up, but see if you can get it going as described above first (simpler).

**Comment by jairocontreras** [comment]
cool thanks! i named the file `startup.py`, placed it in `%appdata%\Notepad++\plugins\config\PythonScript\scripts`, and set `initialisation` setting to `atstartup`. works beautifully
