### ISSUE TITLE
Unoptimal performance of string ↔ wstring conversion.

### ISSUE THREAD

**Issue by nkolotov** [notepad-plus-plus/notepad-plus-plus#6101]
[`string2wstring`](https://github.com/SinghRajenM/notepad-plus-plus/blob/fb78d366d6b60827ef7c3af7374744084ad91420/PowerEditor/src/MISC/Common/Common.cpp#L545) and [`wstring2string`](https://github.com/SinghRajenM/notepad-plus-plus/blob/fb78d366d6b60827ef7c3af7374744084ad91420/PowerEditor/src/MISC/Common/Common.cpp#L559) functions allocate unnecessary temporary buffer vector and then copy its content into output string. Length of the input string will be recalculated twice by `MultiByteToWideChar` even though it is known at advance, length of the output string will be calculated once (during construction of the string returned) even though it is also known. Moreover, most of `wstring2string` invocations involve construction of unnecessary temporary string objects ( [example](https://github.com/SinghRajenM/notepad-plus-plus/blob/fb78d366d6b60827ef7c3af7374744084ad91420/PowerEditor/src/ScitillaComponent/ScintillaEditView.cpp#L683) ) wasting even more time on memory reallocation.

**Comment by chcg** [comment]
@nkolotov Did you do any measurements on this changes? Are the performance gains significant?

**Comment by nkolotov** [comment]
@chcg No, but the functions changed don't seem to be used on hot paths anyway.

**Comment by donho** [comment]
We need the measurement to prove there's need to take the regression risk to change. Otherwise, the current code works fine without any performance issue. I don't consider it as bug.
