### ISSUE TITLE
Left margin width incorrect

### ISSUE THREAD

**Issue by koernertim** [notepad-plus-plus/notepad-plus-plus#6105]
### Description of the Issue
When you open an blank Notepat++ file, the width of the line number margin is configured to display up to 3-digit numbers (so up to line 999). In conclusion the margin shoud get wider when you reach line 1000. However, this is not the case. The margin already gets wider once you reach line 999. The same thing applies to all other potencies of 10. The margin gets wider on the line before you reach 1000/10000/etc...

### Steps to Reproduce the Issue

1.  Open an blank Notepad++ file
2.  Paste 999 new lines
3.  Look at the number line margin width

### Expected Behavior
Margin gets wider once you reach line 1000

### Actual Behavior
Margin gets wider once you reach line 999

![image](https://user-images.githubusercontent.com/48256264/63914167-a6601100-ca32-11e9-9d12-fc82e934badf.png)

![image](https://user-images.githubusercontent.com/48256264/63914188-b37d0000-ca32-11e9-8b96-177949d9059e.png)

**Comment by sasumner** [comment]
Closing due to trivial nature of the complaint.  (Sorry)
