### ISSUE TITLE
Bug: Kurdish  and Persian characters as blank character

### ISSUE THREAD

**Issue by barzan-hayati** [notepad-plus-plus/notepad-plus-plus#6106]
### Description of the Issue

Hello.
I have installed v7.7 of notepad++. Before than this version all thing was right and good. But now I have this problem in showing Kurdish or Persian characters. I Upload a picture for example. Whats happens for this version? I want to report this bug and wish to be solved it asap.

### Actual Behavior

![image](https://user-images.githubusercontent.com/7418329/63932671-e80dad80-ca6c-11e9-846e-cc3d56e5dab8.png)

**Comment by chcg** [comment]
@barzan-hayati 
I didn't observe that issue with:

 ش ص ض ط ظ ع غ ف ق ک گ ل م 

But it is helpful to add also a snippet of the problematic text here +
the N++ debug infos.

Which coding does your text file use? UTF-8?

**Comment by barzan-hayati** [comment]
@chcg Thanks. It was resolved.
