### ISSUE TITLE
[Feature Request] Expose 'Convert To UTF-8' function  to cmd.

### ISSUE THREAD

**Issue by sihunqu123** [notepad-plus-plus/notepad-plus-plus#6108]
I have tried lots of tools to do this, and NPP works are the best.  But unfortunately, it cannot be done via CLI, so that I can change the encoding of a whole project recursively.

So could you please expose the function in `Encoding` -> `Convert To UTF-80` to commandLine? e.g. 
To convert a file(d:\\gbk.txt) to a UTF-8 encoded file:
```terminal
d:> notepad++ convert -targetencode "utf-8" d:\\gbk.txt
```

**Comment by sasumner** [comment]
Have you considered using a scripting plugin as a solution?

**Comment by nkolotov** [comment]
Encoding conversion of text files is supported out of box, you can do something like this:

    Get-Content -Encoding ascii "input.txt" | Out-File -Encoding utf8 "output.txt"

**Comment by sasumner** [comment]
>you can do something like this

>Get-Content -Encoding ascii "input.txt" | Out-File -Encoding utf8 "output.txt"

You can??  Somehow with Notepad++ you can do this?  I think you mean with some other tool, and you want to be able to do this kind of command-line thing with Notepad++ itself.

What I meant was Have you considered scripting using a Notepad++ plugin (thought I already said that) to call the out-of-box conversions on, say a list of files, rather than some sort of command-line-based call (that doesn't currently exist; scripting exists and could likely do what you want, today).

**Comment by nkolotov** [comment]
You don't even need Notepad++, shell supports it out of box.

**Comment by sasumner** [comment]
>You don't even need Notepad++, shell supports it out of box.

Super.  Closing.

**Comment by sasumner** [comment]
Oops.  Closed by mistake.  I thought I was back-and-forthing with the original poster, @sihunqu123 .

**Comment by sihunqu123** [comment]
Hi @nkolotov 152305, Thanks for your reply. Use other Command line tool are not powerful enough, and they only work for some easy case,  they work for a complicated case. For example, if you use them to convert below file to UTF-8, the result would be messed up.
[japBefore.txt](https://github.com/notepad-plus-plus/notepad-plus-plus/files/3563198/japBefore.txt)
As I said, I've tried lots of tools, and npp is the most powerful one.

Hi @sasumner sasumner, thank you for your plugin suggestion and reopening this `Feature Request` for me. Yes, I've tried the plugin way to **workaround** this need, But it would be much more graceful if you expose it via command line, Thanks!

**Comment by nkolotov** [comment]
@sihunqu123 If you have a file with fancy non-Unicode encoding then you should just explicitly specify concrete input encoding. Starting with v6.2 powershell supports broad range of encodings. So it seems that this file can be properly converted like this:

    Get-Content -Encoding shift_jis "japBefore.txt" | Out-File -Encoding utf8 "japAfter.txt"

**Comment by sasumner** [comment]
@sihunqu123 

It isn't within Notepad++'s mission to be a command-line filter type program.  This falls into a "special needs" category that is right for (scripting) plugins to support.  When you say you've "tried" that "workaround"...were you successful?

**Comment by sihunqu123** [comment]
Hi @nkolotov 152305, yeah, as you see, you'll need to figure out the encoding of the original file to convert it to UTF-8, which is cumbersome.

Hi @sasumner, yes, this workaround does work.

 Actually, The reason, I reason I wish this feature is that:
1. the encoding-convert function of npp is most powerful.
2. it is possible to combine npp with my project(nodejs/java/..., but no c/c++, I am bad at c/c++) via command line easily, instead of JNI.
3. We can dockerize npp if some useful functions are exposed via command line. Then we don't need to worry about encoding in the rest of our life.

But, as you said, `command-line filter type program`. It's OK. I'll continue searching for a way to do it programmatically.

Thanks for your kindly help!

**Comment by Ekopalypse** [comment]
@sihunqu123 - npp uses mozillas chardet library to guess the encodings.
If you use a tool which also uses this library, then you should get the same results as npp reports.
For example, python does have the chardet library as well.

**Comment by sihunqu123** [comment]
@Ekopalypse good suggestion. Will try it and tell u the result.
