### ISSUE TITLE
behavior as if control key is being held down

### ISSUE THREAD

**Issue by bholtemeyer** [notepad-plus-plus/notepad-plus-plus#6109]
### Description of the Issue
I find that frequently when using Notepadd++ (with Stata), that the program behaves as if the control key is being held down. For example, if I try to scroll with my mouse, instead of going up or down the page, it zooms in or out. If I press the letter "s", a save box pops up. This is resolved by saving the file. But sometimes I need to do this every 5-10 minutes. 

### Steps to Reproduce the Issue

I haven't yet figured this out.

**Comment by sasumner** [comment]
I have never seen or heard of this issue, and since you have no method of repro'ing it, I'm closing for now.  Will reopen if you can produce some steps or if others chime in that they see similar behavior.
