### ISSUE TITLE
Feature Request: Detect shell scripts for files without extensions, and select the 'Shell' language for syntax highlighting

### ISSUE THREAD

**Issue by DanStevens** [notepad-plus-plus/notepad-plus-plus#611]
When opening a file without a file extension, Notepad++ doesn't currently attempt to select a language for the file (thus no syntax highlighting). An example of text files that commonly don't have an extension are shell scripts for Unix-like environments. It would be great if Notepad++ could detect shell scripts in the same way that Linux and similar environments defect shell scripts: By looking for `#!/bin/sh`, `#!/bin/bash` or similar at the first line of the file. If Notepad++ sees this as the first line of a file, it automatically selects the 'Shell' language.

While Notepad++ is probably not used much within Unix-like environments, I use it to edit Cygwin scripts. I imagine people also use Notepad++ to view and edit shell scripts on a remote servers from Windows, in which case I would see this feature being useful to them also.

**Comment by dail8859** [comment]
Related: #17

**Comment by donho** [comment]
Done
