### ISSUE TITLE
Get back Windows XP Support

### ISSUE THREAD

**Issue by Hollowman1701** [notepad-plus-plus/notepad-plus-plus#6112]
I found this version of libcurl.dll.
with this GUP.exe works fine.
update will be downloaded and installed.
i also used a tool to fake XP is 7 when starting Notepad++
and Plugin Admin works too.
Testet with Windows XP SP3 and Notepad++ 7.7.1 (32-Bit) 
maybe with this we can get the Plugin Admin back in business.
[libcurl.zip](https://github.com/notepad-plus-plus/notepad-plus-plus/files/3557146/libcurl.zip)

**Comment by sasumner** [comment]
Let's just let XP go.  People shouldn't be using it anymore, for their own safety.
