### ISSUE TITLE
Tab bar's text does not respect system colors

### ISSUE THREAD

**Issue by Fierelier** [notepad-plus-plus/notepad-plus-plus#6113]
### Description of the Issue
The tab bar's text does not adapt the user's Windows theme colors. This is especially noticeable when using a dark theme.

### Steps to Reproduce the Issue
1. In Windows 7, right click the desktop and select "Personalize"
2. Apply the Windows Classic theme
3. Hit "Window Color" at the bottom
4. Apply a striking color to all text-related items and hit OK
5. Observe how none of the colors apply to the tab bar's text
The same can be achieved in Windows 8 and 10 with third party tools.

### Expected Behavior
The tab bar text adapts the "3D Objects" text-color.

### Actual Behavior
The tab bar text is always black.

### Debug Information
Notepad++ v7.7.1   (32-bit)
Build time : Jun 16 2019 - 21:14:50
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 7 (32-bit)
Plugins : mimeTools.dll NppConverter.dll NppExport.dll 

### Screenshot
![image](https://user-images.githubusercontent.com/22013816/64030732-6fc7ea80-cb47-11e9-9ebd-981457e5804d.png)

**Comment by antoniovazquezblanco** [comment]
### Description of the Issue

The issue also affects to me. Just wanted to clarify some details below.

 ### Steps to Reproduce the Issue

1. In Windows 10, right click the desktop and select "Personalize"
2. Go to the "Color" section.
3. Select "Dark" in windows theme and apply.
4. Observe how other windows apply the theme (Firefox, File explorer...) and Notepad++ stays in the light theme.

### Expected Behavior

The window frame and components respect windows theming.

### Actual Behavior

The tab bar text is always white.

### Debug Information

Notepad++ v7.7.1   (64-bit)
Build time : Jun 16 2019 - 21:24:47
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10 (64-bit)
Plugins : mimeTools.dll NppConverter.dll 

### Screenshot

![imagen](https://user-images.githubusercontent.com/304193/66388433-693e5580-e9c6-11e9-8388-f651d06c5f92.png)

**Comment by EthanR** [comment]
I would also appreciate this change, seems related to this other issue:
https://github.com/notepad-plus-plus/notepad-plus-plus/issues/4463


@Fierelier how did you manage to change the colors the Notepad++ window, menu, tool, and tab bars? Did you edit registry values or set Windows theme colors manually?
I am using the Dark Theme option in Windows 10 and my experience matches @antoniovazquezblanco

**Comment by ShubhamBelwal** [comment]
@Fierelier Can you share your theme? Looks great with a complete dark theme.

**Comment by Fierelier** [comment]
@antoniovazquezblanco Will not apply because Notepad++, and many other applications, sources its colors from the system color scheme, which Windows 10 does not change when you activate the dark mode.

@EthanR To achieve what I did on Windows 7, you need to use the classic theme, which is no longer available in Windows 10. However, you can use a high contrast theme to achieve a similar, though less appealing result. Another method is to use the classic theme unofficially (have a look at the winclassic boards, this thread in particular), but this is increasingly breaking due to Microsoft's deprecation of it, I'm afraid. There's a lot that goes into using classic theme properly on Windows 10 now.

@ShubhamBelwal Sure! Here it is in two different options: [.theme](https://fier.me/publicShare/Incognito.theme) (Windows 7), [.reg](https://fier.me/publicShare/Incognito.reg) (requires relog, don't apply to Windows 10, choose a new theme if you do)

In case the .theme does not work, the .reg option is non-destructive, user-wide and should work on Windows 95 - Windows 7, though make sure to save your current theme beforehand!

**Comment by Fierelier** [comment]
Strangely, this theme uses the correct color after a program restart: https://draculatheme.com/notepad-plus-plus
![Capture](https://user-images.githubusercontent.com/22013816/102963106-9a7e4500-44e8-11eb-9bfd-620aaa5eb017.PNG)

**I removed `<WidgetStyle name="Active tab text" styleID="0" fgColor="000000" />`** from Obsidian, my preferred theme, as it's also not in Dracula, and that resulted in the same, correct, behavior:
![Capture2](https://user-images.githubusercontent.com/22013816/102963634-e7aee680-44e9-11eb-9505-7d4341dd63b8.PNG)

As a test, choosing a light system theme, and restarting Np++, the text color changes to black, as it should:
![Capture3](https://user-images.githubusercontent.com/22013816/102963823-686de280-44ea-11eb-9818-3794ca1b7b34.PNG)

I think this line should be removed from every theme. I will push something soon.

**Comment by sasumner** [comment]
>I removed <WidgetStyle name="Active tab text" styleID="0" fgColor="000000" /> from Obsidian...program restart...

I tried the same thing, which resulted in no changes to tabs for me under Win10:

![image](https://user-images.githubusercontent.com/30118311/103136193-457b3400-468c-11eb-95b3-85a948cf05eb.png)

Was there something more I needed to do to see this effect?

**Comment by Fierelier** [comment]
@sasumner

**Notepad++ will not be dark for you on Windows 10, this is not a bug.** Np++, like many other programs, sources its colors from the system scheme. It is not enough to enable dark mode, the "oldschool", non-UWP color scheme will stay as-is. To experience the same issue (see my first post, **dark text on dark background is what we are trying to fix**), try using a dark high contrast Windows theme, those themes actually do change the system scheme. This should hopefully make the issue apparent.

**Comment by JamesO2x** [comment]
> 
> 
> Strangely, this theme uses the correct color after a program restart: https://draculatheme.com/notepad-plus-plus
> ![Capture](https://user-images.githubusercontent.com/22013816/102963106-9a7e4500-44e8-11eb-9bfd-620aaa5eb017.PNG)
> 
> **I removed `<WidgetStyle name="Active tab text" styleID="0" fgColor="000000" />`** from Obsidian, my preferred theme, as it's also not in Dracula, and that resulted in the same, correct, behavior:
> ![Capture2](https://user-images.githubusercontent.com/22013816/102963634-e7aee680-44e9-11eb-9505-7d4341dd63b8.PNG)
> 
> As a test, choosing a light system theme, and restarting Np++, the text color changes to black, as it should:
> ![Capture3](https://user-images.githubusercontent.com/22013816/102963823-686de280-44ea-11eb-9818-3794ca1b7b34.PNG)
> 
> I think this line should be removed from every theme. I will push something soon.

Just wanted to confirm. I'm using high-contrast theme on Windows 10 and had this same issue. I use the NP++ "Bespin" theme, and removed the line you suggested from the Bespin XML. This instantly fixed the tab color issue. 

So it seems that line is definitely the culprit. It doesn't seem necessary, and breaks windows color theming.

**Comment by donho** [comment]
The dark mode's text color is fine for me.

**Comment by Fierelier** [comment]
@donho It's about **system colors**, not the dark mode...
