### ISSUE TITLE
Command line to install Notepad++ 32bit and 64bit side by side

### ISSUE THREAD

**Issue by Youness123321** [notepad-plus-plus/notepad-plus-plus#6122]
Hello, anyone knows the command line to install notepad++ 64 bit on system where a 32 bit is already there , and keep them both , i'm using a powershell script for the install, thanks in advance

**Comment by webketje** [comment]
If you install in `Program Files` or `Program Files (x86)` there will be **conflicts** for plugins & config as both will store data in `%appdata%\Notepad++`. If you install at least 1 *outside* of Program Files, there should be no problem as Notepad++ will store its config inside its own installation folder.

As for the command-line install you can use a utility like [7zip](https://www.7-zip.org/). It comes with a very capable command-line with [documentation](https://sevenzip.osdn.jp/chm/cmdline/) available. 
Use the `.zip` or `.7z` Notepad++ archive (not the .exe), install 7zip first, then execute something like:

```
"C:\Program Files\7-Zip\7z" x -aoa -oInstallDirName npp.7.7.1.bin.x64.7z
```
* `x` is *Extract with full file path* (keeps archive folder structure)
* `-aoa` instructs 7zip to overwrite existing files without asking confirmation
* `-o`  specifies output directory (will be created if doesn't exist)

**Comment by xylographe** [comment]
Extracting the portable archive will overwrite existing `config.xml` and `shortcuts.xml`. Both `langs.xml` and `stylers.xml` need to be updated from `langs.model.xml` and `stylers.model.xml` respectively.
