### ISSUE TITLE
Notepad++ freezes and eating RAM if I open this file

### ISSUE THREAD

**Issue by TuTAH1** [notepad-plus-plus/notepad-plus-plus#6123]
If I open this file (16kb) with newest version of Notepad++, notepad freezes and eating more and more memory until eats all of it. I can open it with usual notepad and it’s ok.
The others files is ok. Even the file that have nearly the same filling (18kb)
I also attached the video, if you need
https://cloud.mail.ru/public/4a1Z/2eogy3Bd6

**Comment by zufuliu** [comment]
It's better to attach you file (zipped), so others can verify it.

**Comment by TuTAH1** [comment]
I wasn't found an attach function there, that's why I add this file in the cloud. I don't think that it's a problem to download it

**Comment by TuTAH1** [comment]
I find it. Video still in the link (1st massage)
[notepad++.zip](https://github.com/notepad-plus-plus/notepad-plus-plus/files/3586385/notepad%2B%2B.zip)

**Comment by zufuliu** [comment]
Not reproducible with N++ 7.7.1,  your second file (the 16 KiB one) is Windows-1251 (ANSI Cyrillic), but has UTF-8 BOM.

**Comment by TuTAH1** [comment]
I have 7.7.1 (64 bit) too, but I have this problem
