### ISSUE TITLE
App crash in Windows 10 file browse dialog in folder with .TS (or video) files

### ISSUE THREAD

**Issue by jsim5446** [notepad-plus-plus/notepad-plus-plus#6124]
Operating system: Windows 10 Pro Version 1809 build 17763.678
Notepad++ version 7.7.1 (64-bit)

I was learning the TypeScript programming language and stumbled on some strange crash behavior in Notepad++.   Before describing the issue any further, I should clarify that it seems likely that the root of the issue is a Microsoft bug and Notepad++ is probably just the unlucky victim in this scenario.  In the process of tracking down the issue, I achieved a work-around that is satisfactory in my workflow, and I understand that OS-specific bugs like this might not be practical to fix, so I'm not holding my breath for a bug-fix.  The main goal of opening this issue is to hopefully save a few other users who may be unlucky enough to encounter the same confluence of mystical forces from spending as much time as I did to solve the mystery.

Apparently, although I never asked for it, the .TS extension was associated with a program I've never used called "Movies & TV".   At some point after creating a few files with .TS extension, the folder I was using (located in a sub-folder under the "Documents" library folder in my user profile, which might be a relevant detail) magically changed to be "optimized" for "Videos", although I didn't ask for this to happen either.   I didn't realize this was occurring at the time, at first I just noticed that for some unknown reason it automatically changed the folder view to the horrible "Large icons" view instead of my preferred "Details" view.  So I changed the view back to the more reasonable "Details" view, and for a short while, I thought that life was good again, until I needed to save the contents of a new window in Notepad++ as a file in this folder.  Then I discovered that Notepad++ would usually crash when the Save As or Open File dialog navigated to the folder in question (including immediately on opening the dialog if it was the last folder navigated).  Occasionally it would work fine the first time, then crash the second time, but failure seemed inevitable.

After the initial panic subsided, I managed to deduce that the folder optimization setting was contributing to the problem, which led to a relatively simple work-around of changing the folder optimization to "Documents" or "General Items" which seems to eliminate the problem.

It might be relevant to point out that the following steps were performed automatically by the OS without my knowledge or consent in my scenario, but here are the steps to manually configure a folder to be "optimized" for "Videos" in Windows 10:
1. Open File Explorer
2. Right-click on the folder, select _Properties_ menu item
3. Select the _Customize_ tab
4. In the _Optimize this folder for_ combo box, select **Videos**

See the following screenshot for an example:

<img src="https://user-images.githubusercontent.com/34869561/64282892-37d7f300-cf0b-11e9-8d4d-7c6185e2a026.png" alt="folder properties dialog" width="320" height="402" />

However, this step alone does not reproduce the bug, which was initially puzzling when I tried it on another random folder with no crash.   Using process of elimination, I discovered the second factor is that the crash only occurs if the folder contains **2 or more** files with .TS file extension (or possibly any file associated with the "Movies & TV" program, I did not get a chance to test this).   It is also likely (although unconfirmed) that the crash will only occur if the folder is set to display the Details view.  Most likely the automatic change to folder optimization setting occurred once there were more files that looked like video files than any other specific type.  This screenshot shows the file Properties dialog indicating that the .TS extension is associated with Movies & TV:

<img src="https://user-images.githubusercontent.com/34869561/64283843-1b3cba80-cf0d-11e9-946b-f846078132a9.png" alt="file properties dialog" width="320" height="402" />

This discovery suggested a second part of the work-around that is probably a good idea for folks using the .TS extension for TypeScript files.  One might consider changing the association for .TS files with an appropriate text editing program, such as Notepad++ or an IDE.   Interestingly, once I completed this change after setting the folder optimization back to Video, at first it magically changed the folder optimization setting to "Pictures" (reverting my Details view back to the annoying Large Icons view), probably because I had two PNG files in the same folder, and it did not seem to fix the problem... at least at first.  Later after closing and reopening Notepad++, the crash was gone, and I could not replicate the crashing behavior even after changing the file association back to Movies & TV and changing the folder optimization back to Video.  So I'm not optimistic about the chances of reproducing this issue intentionally, but I'm proceeding with submitting this bug report just in case it is useful.

**Comment by sasumner** [comment]
WTF does it even mean to "optimize a folder for video"?

**Comment by jsim5446** [comment]
As far as I can tell, all it does (other than causing instability of course) is change the default folder view from my preferred Details view to something less useful for me, along with adding a "Video Tools" contextual tab in the ribbon in File Explorer and a "Cast to Device" context menu item on the folder.  I have never used either of these features, but I imagine they might be useful for other people.  These context items are also available when a .TS file is selected, regardless of the application associated with the file extension and even when the folder is not "optimized for video".

**Comment by ismael-miguel** [comment]
The extension .ts is usually used for a video format, automatically associated with the "Movies & TV" app.

Windows automatically sets the view (the "Optimize" thingy) to whatever media you have.
This happens since Windows XP (maybe Windows 2000? Millenium?), so, nothing new.

My guess is that the crash is caused by the dialog trying to present a preview, but failing miserably because your .ts file is not a valid .ts video file.

**Comment by mere-human** [comment]
@jsim5446 is it still reproducible?
I cannot reproduce it neither in 7.9.2 nor in 7.9.3.

**Debug info:**
Notepad++ v7.9.3   (64-bit)
Build time : Feb 22 2021 - 22:47:45
Path : E:\Development\notepad-plus-plus\PowerEditor\visual.net\x64\Unicode Debug\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS Name : Windows 10 Enterprise (64-bit) 
OS Version : 2009
OS Build : 19042.804
Current ANSI codepage : 1252
Plugins : none

**Comment by donho** [comment]
Outdated.
