### ISSUE TITLE
Search text on files in the Workspace.

### ISSUE THREAD

**Issue by vionixt** [notepad-plus-plus/notepad-plus-plus#6125]
### Description of the Issue
Not an issue but a new feature requests.
Currently in search in file, we need to browse the file location to search some text.
There should be an additional feature to make it possible to search text in the files currently in my Workspace.

### Steps to Reproduce the Issue
1. Issue description is self explanatory. 

### Expected Behavior
We should be able to search text in file currently in my Workspace.

### Actual Behavior
No feature to search text in files from Workspace.

![Untitled](https://user-images.githubusercontent.com/4313328/64314512-d710ef00-cfcc-11e9-8f21-60bbe30c9c7c.png)

**Comment by sasumner** [comment]
Since it is "Folder as workspace", can't you just do a "Find in Files" and specify the top-level folder (of your workspace) as the "Directory" to search, and then tick the "subfolders" option?

**Comment by vionixt** [comment]
Right click and then putting the search text is 2-3 clicks, 
Is it possible to have just a 'check box', for search to include files in 'Workspace'?

**Comment by sasumner** [comment]
>Right click

??  What "right click"?

Actually, I gave bad advice last time.  But your "right click" thing jogged my memory:  What you really want to do is to right-click the appropriate folder for your search _in the Folder-As-Workspace panel_.  Then you will get a _Find in Files_ choice.  If you choose that, the _Directory_ box (in the _Find in Files_ window that opens) becomes pre-populated with the current folder's path.

I think that solves the issue for you.

**Comment by vionixt** [comment]
I was expecting something similar to Eclipse.
![Search](https://user-images.githubusercontent.com/4313328/64427289-81247000-d0ce-11e9-87d5-63d5f1184191.png)

**Comment by sasumner** [comment]
Really, I fail to see any qualitative difference.

Suggest:  Use Eclipse ?

**Comment by vionixt** [comment]
No problem Sasumner, it's just a 'good to have' feature.
I will live with 'right click' approach peacefully. 

Regards.
