### ISSUE TITLE
Bad printer driver pulls Notepad++ down

### ISSUE THREAD

**Issue by Peter0** [notepad-plus-plus/notepad-plus-plus#6126]
### Description of the Issue
We have a problem with our network printing driver. Under Win 10, it let some applications crash, when they want to open printer properties requester. Notepad++ belongs to them. Notepad++ seems to recover documents after restart, therefore this behaviour isn't critical.

### Steps to Reproduce the Issue
1. Choose menu "Datei", "Drucken ..." (probably "File", "Print ..." in english version)
2. In the just appeared printer requester choose "MINOLTA C220 at net.work.path.local"
3. Below the list, press right handed button "Einstellungen" (probably "adjustments" or "properties")

### Expected Behavior
Printer properties requester should open or an error message should appear if the printer driver's properties requester is faulty.

### Actual Behavior
Notepad++ silently closes, no further enquiry whether unsaved changes should be saved. Labelled as "crash" above.

### Debug Information
Probably this isn't easy to reenact if one hasn't this odd behaving printer. Maybe it is just an encouragement to be more fussy on return values or to better encapsulate somehow the execution environment where printer driver lives.

Notepad++ v7.7.1 (64-bit), built Jun 16 2019 - 21:24:47

**Comment by sasumner** [comment]
Since this happens for multiple applications for you, isn't the better focus of your complaint the actual "network printer driver"?

**Comment by Peter0** [comment]
Ok. Because there are more than one program behaving bad, it's better to ignore it. Feels a little bit like to shoot the messenger for bringing bad news.

May it indeed also possible that the printer dialogue behaves correctly, but just uses some odd feature?

As soon as the printer requester behaves amicable, probably I can't give any more input to this then hidden issue.
