### ISSUE TITLE
[Feature request] Monitoring (tail -f) from the command line and editor

### ISSUE THREAD

**Issue by Aleksandra14368** [notepad-plus-plus/notepad-plus-plus#6129]
I made a python3 GUI that opens .txt log files in text editor and monitors them. 
The thing is, currently Notepad++ supports automatic real time monitoring of files only if option _Monitoring (tail -f)_ is manually activated from the View tab. Upon closing and reopening Notepad++, that option unchecks until you manually check it. 
I would like to send a feature request for you to consider for a future release, such as _Monitoring (tail -f)_ from the command line that would enable automatic real time file monitoring upon reopening Notepad++ from the command line.

**Comment by sasumner** [comment]
Suggest you try a plugin that can automatically do things (like selecting a menu option) upon Notepad++ startup.  Examples might include NppExec or Pythonscript.  Realistically, I can't see the "monitoring" feature being controlled from the command line.
