### ISSUE TITLE
New files saved to folder in Folder as Workspace are not shown.

### ISSUE THREAD

**Issue by dpaterson** [notepad-plus-plus/notepad-plus-plus#6131]
### Description of the Issue
New files saved to folder I am using in Folder as Workspace are not shown in Folder as Workspace.

### Steps to Reproduce the Issue

1.  In Folder as Workspace window open a file.
2.  File -> Save as -> [new_file_name_in_same_folder]
3.  Look for file in Folder as Workspace window.

### Expected Behavior
See my newly create file in Folder as Workspace

### Actual Behavior
File is not visible

### Debug Information
Notepad++ v7.7.1   (64-bit)
Build time : Jun 16 2019 - 21:24:47
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10 (64-bit)
Plugins : DSpellCheck.dll mimeTools.dll NppConverter.dll

**Comment by sasumner** [comment]
Similar to #4379 except this one is for _files_ and that one is for _folders_.

**Comment by sasumner** [comment]
If I try creating a new folder in a folder in _Folder as Workspace_, I see the folder created.  N++ 7.7.1.

**Comment by webketje** [comment]
@sasumner In Folder as workspace this works, but Project Panel workspace is not updated automatically (reporting with the same specs as given in OP)

**Comment by donho** [comment]
Cannot reproducible with 7.8.2
