### ISSUE TITLE
file extensions aren't added to file when saving, have to be input manually

### ISSUE THREAD

**Issue by komaedalove** [notepad-plus-plus/notepad-plus-plus#6132]
### Description of the Issue

When making a new file and saving it, the chosen "save as" extension is not added to the file and is instead left blank.

### Steps to Reproduce the Issue

1. Make New Document
2. Choose "Save As"
3. Choose a document type and save

### Expected Behavior

The chosen file extension to be added to the file.

### Actual Behavior

The file extension is left blank.

### Debug Information

Notepad++ v7.7.1   (64-bit)
Build time : Jun 16 2019 - 21:24:47
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : ON
Local Conf mode : OFF
OS : Windows 7 (64-bit)
Plugins : mimeTools.dll NppConverter.dll 

I tried a fresh install of the newest release in x64 and x86, older versions. None of it worked.
Video:
https://youtu.be/b9weuUYWbnA

**Comment by sasumner** [comment]
The action of step 3 is just a filter for existing files in the folder, so you can see what files of that type already exist.  The document type extension isn't supposed to be added to the filename you type.  If you want an extension added, type a `.` and then the desired extension.
