### ISSUE TITLE
What is the purpose of NPPM_ALLOCATECMDID message?

### ISSUE THREAD

**Issue by Ekopalypse** [notepad-plus-plus/notepad-plus-plus#6136]
From what I've found out so far it seem to be related if one creates a submenu within its 
plugin menu but I have no idea how to use it. In addition, it should be send back wihtin
WM_COMMAND message but I don't see/receive it. 
Do I need to request a cmdid for each submenu? Or an id for each menuitem wihtin the submenu?

**Comment by sasumner** [comment]
Did you get your answer(s)?  Why not elaborate on those answers here, to the benefit of all who might be interested?

**Comment by Ekopalypse** [comment]
>Did you get your answer(s)? 
:-D No :-D

>Why not elaborate on those answers here, to the benefit of all who might be interested?
Which basically can be answered with no info -> nothing to discuss :-D

At the end I think this is some kind of question, which does not get some attention at all 
and isn't of interest to most of the npp users.
