### ISSUE TITLE
Feature Request: Reopen closed tab

### ISSUE THREAD

**Issue by lonely188** [notepad-plus-plus/notepad-plus-plus#6138]
Modern web browsers have the ability to reopen closed tabs.  This feature would be useful in Notepad++ when you close a file tab. The user would right click a present tab and the context menu would include a "Reopen closed tab/file", which would reopen the last file that was closed.

**Comment by Ekopalypse** [comment]
Imho, can be closed as it already exist. Check the file menu. Restore ...

**Comment by sasumner** [comment]
`File` menu > `Recent Files` > etc.
