### ISSUE TITLE
Hang when opening with buffer in write protected folder

### ISSUE THREAD

**Issue by walker-ix** [notepad-plus-plus/notepad-plus-plus#6139]
### Description of the Issue
Notepad__ v7.5.9 hangs indefinitely on launch, unless launched with Admin privilege

### Steps to Reproduce the Issue
1. Using a previous version of NPP, open a file that requires Admin privilege to write
2. Edit the file, but do not save it - leave it as WIP
3. update to NPP 7.5.9
4. Try to launch NPP - it hangs indefinitely

If you launch NPP with 'run as Admin', it will launch/load

### Expected Behavior
Notepad++ would open, and display the work-in-process buffer. It would require changing to Admin privelege in order to save the WIP

### Actual Behavior
Notepad++ hangs on launch. Outer window is displayed, but nothing else shows. This can be 'fixed' by launching 'run as Administrator'

### Debug Information
Notepad++ v7.5.9   (32-bit)
Build time : Oct 14 2018 - 15:02:52
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10 (64-bit)
Plugins : DSpellCheck.dll mimeTools.dll NppConverter.dll NppExport.dll

**Comment by Ekopalypse** [comment]
As the current version is 7.7.1 would you give it a try to see if it still happens?
You can download a portable aka zip or 7z version and run it in parallel to your current used version.

**Comment by walker-ix** [comment]
Nope! It looks like the problem was fixed along the way to 7.7.1. I just
verified it does not exists for....

Notepad++ v7.7.1   (32-bit)
Build time : Jun 16 2019 - 21:14:50
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10 (64-bit)
Plugins : DSpellCheck.dll mimeTools.dll NppConverter.dll NppExport.dll

Sorry for being behind - I thought I was testing the latest.
