### ISSUE TITLE
Notepad++ running under Linux/Wine: Main window looses focus after Search in Files...

### ISSUE THREAD

**Issue by hartmut27** [notepad-plus-plus/notepad-plus-plus#6147]
### Description of the Issue
Notepad++ running under Linux/Wine: Main window looses focus after Search in Files...
Ubuntu: 18.04
wine-stable: 3.0-1ubuntu1
Notepad++: 7.7.1 / npp.7.7.1.installer.exe

### Steps to Reproduce the Issue
Menu Search -> Find in Files (Ctrl-Shift-F) ... -> find anything...

### Expected Behavior
After displaying "Find Result" window, Notepad++ should react on keyboard entries (as usual)

### Actual Behavior
Notepad++ has lost focus (not active for user entries). 
To work-around:: I need press Alt-Tab (once) to regain focus

**Comment by hartmut27** [comment]
..... could be a problem of wine only.

**Comment by KOLANICH** [comment]
I use wine-staging 4.16 and don't understand what you mean. I remember that there were some issues with search dialog in past though, but not with find in files. Try to upgrade wine.

**Comment by hartmut27** [comment]
the problem disappeared after upgrade on Ubuntu 19.04 disco including "wine 4.0-1".

$ apt show wine
Package: wine
Version: 4.0-1
Built-Using: khronos-api (= 4.6+git20180514-1), unicode-data (= 11.0.0-1)

**Comment by KOLANICH** [comment]
Though I strongly recommend to use Wine from WineHQ deb repo, not from Ubuntu universe.
