### ISSUE TITLE
Windows installer - some text not translated

### ISSUE THREAD

**Issue by scootergrisen** [notepad-plus-plus/notepad-plus-plus#615]
I select my language in Windows installer, but during installation i get this dialog:

    Notepad++ v6.8 Installation
    Due to the stability issue,
    HexEditor.dll will be moved to the directory "disabled"

I would like this to be translateable so everything is in my language.

**Comment by donho** [comment]
In NSIS installer all added texts are not translatable. I can do nothing about it.
