### ISSUE TITLE
why Notepad++ is not available for linux(ubuntu)?

### ISSUE THREAD

**Issue by amrithmmh** [notepad-plus-plus/notepad-plus-plus#6151]
I am a fan of Npp but i cannot find a native application in ubuntu 
please release it for ubuntu too or make it opensource so it can be compiled

**Comment by Xiad32** [comment]
There is a snap version of NPP on Ubuntu. I dont if it is official or if it is part of this project. I have faced a few bugs with it though. 
You can install it from Ubuntu by going to ubuntu software center search for "notepad-plue-plus" then click install.

**Comment by Ekopalypse** [comment]
Npp depends on win32 calls which are not available on other platform natively,
so no, no native npp for ubuntu

**Comment by KOLANICH** [comment]
Works quite fine in Wine, but with large issues, like inability to use DirectWrite (it draws text, but damn slow (so I guess without any hardware acceleratiin) and without ligatures, that defeats the purpose of using DirectDraw).
