### ISSUE TITLE
Notepad RTF export

### ISSUE THREAD

**Issue by udrzbar** [notepad-plus-plus/notepad-plus-plus#6152]
Notepad 7.6.6 export to RTF works ok and it copies syntax colouring.
Notepad 7.7.1 export to RTF does not copy syntax colouring.

### Steps to Reproduce the Issue

1.  Plugins->NPP Export->Copy RTF to clipboard
2.  Copy clipboard to Word - no syntax colouring

**Comment by Ekopalypse** [comment]
see [here](https://github.com/chcg/NPP_ExportPlugin/releases/tag/0.2.9.21)

**Comment by sasumner** [comment]
Closing (presuming OP just needs to upgrade their plugin per Ekopalypse's pointer).
