### ISSUE TITLE
hyperlinks don't recognise international characters in URLs

### ISSUE THREAD

**Issue by HairyPhil** [notepad-plus-plus/notepad-plus-plus#6155]
### Description of the Issue

Conversion of URLs to hyperlinks stops when it encounters an international character.

### Steps to Reproduce the Issue

Copy and paste the following example URL to a blank txt document:
https://www.amazon.fr/GRÜNTEK-Ebrancheur-Cisailles-crémaillère-SATISFAIT/dp/B01COZUA4E/

(Alternative example:)
https://www.amazon.fr/Gardena-coupe-branches-TeleCut-520-670-télescopiques/dp/B07JLJ4N44/

### Expected Behavior

The whole URL should be rendered as a hyperlink.

### Actual Behavior

The hyperlink incorrectly ends after the R in GRÜNTEK because of the umlaut.

### Debug Information
Notepad++ v7.7.1   (64-bit)
Build time : Jun 16 2019 - 21:24:47
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10 (64-bit)
Plugins : DSpellCheck.dll mimeTools.dll NppConverter.dll

**Comment by HairyPhil** [comment]
Note that GitHub renders the hyperlinks correctly.

**Comment by ArkadiuszMichalski** [comment]
@sasumner 
https://github.com/notepad-plus-plus/notepad-plus-plus/issues/8634 is not the same? The title suggest to Cyrillic, but the new regex probably cover a wider range of characters (including those here). Maybe close this bug?
