### ISSUE TITLE
Login to new community site not possible

### ISSUE THREAD

**Issue by Ekopalypse** [notepad-plus-plus/notepad-plus-plus#6158]
When trying to login to new community site, using the same github account as currently used,
I received the following error

_An error occurred during a connection to community.notepad-plus-plus.org:4567. 
SSL received a record that exceeded the maximum permissible length. 
Error code: SSL_ERROR_RX_RECORD_TOO_LONG_

Btw. just a note, I can see that the most recent posts haven't been migrated yet.

**Comment by dinkumoil** [comment]
When I ty to open https://community.notepad-plus-plus.org/ I get a `Page not found` error. What's wrong?

**Comment by Ekopalypse** [comment]
@dinkumoil - that worked in the past. I always log in at github and then when login at npp community site it uses the create _what_ever_the_name_is_ token for authentication. As said, never had a problem before. Can you login to the new forum using your github account?

**Comment by dinkumoil** [comment]
@Ekopalypse - Normally I use my GitHub account for logging in, too. Currently it's not possible, as you said.

But I might have been wrong, `SSL_ERROR_RX_RECORD_TOO_LONG` seems to be related with wrong server configuration. I guess we have to be patient...

**Comment by cmeriaux** [comment]
@donho is migrating the community forum on a new hosting plateform. This is a work in progress

**Comment by Ekopalypse** [comment]
@cmeriaux - thx - :-D 
Please don't get me wrong, but I guess that part is known :-D

**Comment by sasumner** [comment]
Sure it's work-in-progress, but I noticed new site is at least partially up, but only offers Twitter and Github logins.  What happened to the others (I think gmail and Facebook)?  Or maybe this is a part of the "in progress"?  It might be better to see NOTHING until it is all finished.  :)

**Comment by Ekopalypse** [comment]
login possible again :-)
