### ISSUE TITLE
Notepad ++ Auto Updater Broken

### ISSUE THREAD

**Issue by Xorima** [notepad-plus-plus/notepad-plus-plus#6160]
Hi,

Since the move to the new website i am getting the error:
![image](https://user-images.githubusercontent.com/4923914/65156486-19074f80-da27-11e9-9ab7-c04d63794dd9.png)
I also find the URL is now failing: https://notepad-plus-plus.org/update/getDownloadUrl.php

Where is the auto update meant to be pointing to now?

**Comment by donho** [comment]
Fixed now.

**Comment by KenMiller** [comment]
Yep, Woks now.
