### ISSUE TITLE
Nessus reports vulnerability "Microsoft Windows Unquoted Service Path Enumeration"

### ISSUE THREAD

**Issue by Ekopalypse** [notepad-plus-plus/notepad-plus-plus#6165]
Opened on behalf of [this forum post](https://community.notepad-plus-plus.org/topic/18279/nessus-reports-vulnerability-microsoft-windows-unquoted-service-path-enumeration)

The installer doesn’t quote the uninstall string appropriately.
HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\Notepad++\UninstallString is

C:\Program Files\Notepad++\uninstall.exe

when it should be

“C:\Program Files\Notepad++\uninstall.exe”

And similarly in wow64node for 32-bit version.
Can you please tweak the installer to quote this so that people don’t have to waste time “remediating” this?

**Comment by VectorBCO** [comment]
as a workaround could be used script from this project https://github.com/VectorBCO/windows-path-enumerate
