### ISSUE TITLE
CTRL-M is not aware of EOL-format

### ISSUE THREAD

**Issue by tm8544** [notepad-plus-plus/notepad-plus-plus#6166]
In preferences I have Line-ending format set to Windows (CRLF).

Despite of that, Ctrl-M produces CR instead of CRLF.

Ctrl-M should be aware of EOL-format.

Notepad++ version v7.7.1

**Comment by Ekopalypse** [comment]
run shortcut mapper, goto scintilla commands and **add** ctrl+m as an additional shortcut key to
SCI_NEWLINE

**Comment by sasumner** [comment]
See #6022 

>Despite of that, Ctrl-M produces CR instead of CRLF

Why do you think this?  ctrl+m is the ASCII code for CR, so it is plausible that it could insert CR only.  But, I don't think it is desirable.  BUT, I don't think it should insert CRLF, or anything else either.  It is just a shame that by default, ctrl+m can do such a thing (insert CR into CRLF files).

**Comment by Ekopalypse** [comment]
Having an additional row (e.g. SCI_NULL) containing a blacklist of shortcut keys inserting non-text
might solve the issue. 
Those which do need the special chars could release this via shortcut mapper.

**Comment by tm8544** [comment]
> run shortcut mapper, goto scintilla commands and **add** ctrl+m as an additional shortcut key to
> SCI_NEWLINE

This is good for me, closing this issue
