### ISSUE TITLE
pt-PT translation error in search box "Wrap around"

### ISSUE THREAD

**Issue by ludwig801** [notepad-plus-plus/notepad-plus-plus#6167]
### Description of the Issue
The portguese (pt-PT) translation translates the search box's "Wrap Around" to "Moldar Texto", which is not an accurate translation. Ideally, it would be something like "Pesquisa circular", which means "circular search". "Moldar texto" means "Wrap text" and does not represent the actual behaviour.

**Comment by ismael-miguel** [comment]
I don't now if a better translation would be "Voltar ao ínicio". which is basically the message that "Wrap Around" is trying to send.

Also "Moldar texto" is used for "Word wrap" (splits long lines of text to fit within a certain "margin"), which is nowhere near the intended meaning.

**Comment by sasumner** [comment]
"Translation" problems don't get assigned to "issues".  Otherwise I'm sure there would be hundreds if not thousands of extra "issues" to deal with.  That being said, I'm not sure I fully understand _what_ the process is for translation problems.  @donho?

**Comment by ismael-miguel** [comment]
@sasumner There's the `label:translation`.

Maybe it should be moved there, instead of being just closed?

Try a search with `is:open is:issue label:translation`.

**Comment by sasumner** [comment]
There is no "movement"; certainly it can be labelled.  I will do that.  Thanks for pointing that out.
