### ISSUE TITLE
Translate context menu "Edit with Notepad++"

### ISSUE THREAD

**Issue by openforu** [notepad-plus-plus/notepad-plus-plus#6169]
Can context menu be translated somehow?
I know context menu is programed in:  **NppShell_06.dll**
![translation](https://user-images.githubusercontent.com/27965903/65516110-b0b1e580-dee0-11e9-91e3-e87afd208c00.png)

**Comment by Ekopalypse** [comment]
Yes, the value is stored in the registry. Search for it and replace it with your content.

**Comment by rddim** [comment]
Open `regedit` and navigate to`HKEY_CLASSES_ROOT\CLSID\{B298D29A-A6ED-11DE-BA8C-A68E55D89593}\Settings` then double click on `Title` and change the text to what you want. No need to restart the PC.

**Comment by donho** [comment]
Done in #13170 (Windows 11 only)

**Comment by CennoxX** [comment]
@donho Could this be opened, as this is not done for pre Windows 11?

**Comment by CennoxX** [comment]
@donho This is now closed with https://github.com/notepad-plus-plus/nppShell/commit/ca0dcca105c97f643bcaec07011cccbad6a13e27
