### ISSUE TITLE
OpenFileDialog.Multiselect

### ISSUE THREAD

**Issue by EbATpy** [notepad-plus-plus/notepad-plus-plus#6170]
V7.7.1

Menue -> Open ->Select more then 10 files!
No one file is open!

Notepad++ v7.7.1   (32-bit)
Build time : Jun 16 2019 - 21:14:50
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : ON
Local Conf mode : OFF
OS : Windows 7 (64-bit)
Plugins : mimeTools.dll NppConverter.dll NppExport.dll

**Comment by rddim** [comment]
Can not reproduce. 10+ are opened without problems.

**Comment by sasumner** [comment]
Cannot reproduce with 20 files, with or without "new style dialog" preference.  Notepad++ v7.7.1 (32-bit)

**Comment by EbATpy** [comment]
1.) 10 or more files  already open in Notpadd++
2.)  Menue -> Open ->Select more then 10 files!
3.) No one file is open!

This Happend some times
When you have already Open Files in Notpad++
Try to add new files gaian and agin!

**Comment by sasumner** [comment]
200 files, loaded 10 or 20 at a time, no problems:

![image](https://user-images.githubusercontent.com/30118311/65535118-ccac8b80-dece-11e9-903a-fc4e2661e6ec.png)

**Comment by Ekopalypse** [comment]
Actually it looks like it depends whether new style dialog is used or not.
If I uncheck **Settings->Preferences->Default Directory->use new style dialog...** then I can replicate
@EbATpy issue. If checked, I wasn't able to recreate the issue.

**Comment by sasumner** [comment]
@Ekopalypse Can you provide exact set of replication steps?

**Comment by Ekopalypse** [comment]
Gimme a sec

**Comment by Ekopalypse** [comment]
Downloaded a fresh portable 771 zip.
Unpacked, started
Uncheck Settings->Preferences->Default Directory->use new style dialog (without ...
Close settings window
File->Open and chose multiple files. (in my case I was able to open 13 files, the 14th did break it.

It looks like this issue is MAX_PATH here because my 13 files where 230 chars in total and with the 14th
it would 267.

**Comment by sasumner** [comment]
Perhaps the resolution to this issue is : "use new style dialog"

**Comment by Ekopalypse** [comment]
I guess so, because, afaik, these are windows provided dialogs anyway.

**Comment by EbATpy** [comment]
with the new style Dialog seems to work
