### ISSUE TITLE
'Find in files' doesn't search file contents correctly if file has unsaved changes in editor

### ISSUE THREAD

**Issue by jsmars** [notepad-plus-plus/notepad-plus-plus#6172]
### Description of the Issue

If you have a file open in the editor with unsaved changes, when using "find in files" it will not look in the contents of the file, but rather the file you have in the editor. This literally gave me 2 hours of debugging headaches.

### Steps to Reproduce the Issue

1. Create a test.txt in a test folder containing QQQ, save it, 
2. Use Find in files and search for QQQ to confirm it is working.
3. Now edit away the QQQ from the test.txt without saving.
4. Repeate the search for QQQ and observe that no results can be found, even though the file in the folder contains that text.

### Expected Behavior

Find in files should search actual file contents and not open unsaved changes in the editor. Or even better, provide both the unsaved file and actual file in the results.

### Actual Behavior

Find in files searches searches unsaved changes for files opened in the editor,

**Comment by sasumner** [comment]
The existing behavior is by design.

**Comment by jsmars** [comment]
If that is the case I believe some sort of information should be added that this includes local changes in open files, or have an option to choose, since "find in files" seems to refer to the file contents rather than any local changes not yet saved.

**Comment by sasumner** [comment]
@jsmars We will consider adding this to appropriate area of the Notepad++ documentation site:  https://npp-user-manual.org/
