### ISSUE TITLE
Feature request: `Compare Selection with Clipboard`

### ISSUE THREAD

**Issue by Petewg** [notepad-plus-plus/notepad-plus-plus#6177]
Hi,
the feature I would like to see implemented is the ability to **compare** selected text with **clipboard** contents. I don't know if this is already implemented, if yes, I'd be delighted to let me know where do I find it, (in some menu, any plugin or wherever).
I can imagine it as:  `'Compare Selection with Clipboard'`, preferably available as an option in the popup menu shown when right-click the selected text; of course, when no selection or no clipboard data available, the option should stay disabled, just like `Cut` or `Copy`, for example.

**Comment by sasumner** [comment]
Notepad++ itself doesn't do compares, and it won't because there is already a "Compare" plugin.  Maybe your request is appropriate for the Compare plugin authors to consider?  If you think so, please find where the Compare plugin is supported and make your request there.

**Comment by Petewg** [comment]
Sorry, but the fact of the existence of  a «"Compare" plugin»  isn't quite a strong argument to reject
the integration of such (or a similar or any other) functionality into the editor.   
Now, if you think the proposed feature isn't useful, I can't but respect your opinion, even though I disagree with it!
In my humble opinion, `selected text` and `clipboard` are fundamental (and related) concepts of text editing, so any functionality regarding them (including `comparison`) should be considered as an significant and wanted feature of any decent text editor itself. On the other hand, while plugins are absolutely useful and always welcome, no serious application could rely exclusively on them to enrich and expand its functionality.
 
just my 2 cents and regards.

**Comment by DavidHansen-0x454d43** [comment]
> while plugins are absolutely useful and always welcome, no serious application could rely exclusively on them to enrich and expand its functionality.
_Laughs in Jira_

In all seriousness though @Petewg, 'Compare Selection with Clipboard' is not a feature I can recall coming across in any other editor or IDE... which leads me to agree with @sasumner that this feature would best be implemented as a plugin or script. 

What you are describing could probably be implemented in less than one page of pythonscript. 

If you ask really nicely, sasumner might even help you with that.

**Comment by Petewg** [comment]
Motivation for my initial post was a real necessity: some times there's a need to compare portions of code, in order, for example,  to decide whether is 'Ok' to paste it over in place of the selected text.
The fact that such a feature isn't currently present on existing editors/IDEs while it's mostly true, does not constitutes any "rule" against implementing this functionality, ever. 
Npp++ could be pioneering (also) on this... ;-) 
but as said "Npp++ doesn't do compares" and such functionality is left to plugins to implement it. The answer is always respectable, but discussing the reasoning (or even disagreed with it) is a basic element of any conversation. I think.
On the other hand, the existing "Compare" plugin, unfortunately, does not do this kind of comparison; but I must admit it'd be better if I had proposed directly to the author(s) of the plugin to apply this feature in their plugin. Doing so, we would perhaps had saved time and some annoyance! seemingly it was my fault, for I have thought to post firstly here.

P.S.: @DavidHansen-0x454d43
`Laughs`, (in Jira (?) or not) against one's opinion for a matter, is not that bad as a reaction, although people can certainly do better than that (and worst also). Nevertheless, what I can't discern into my phrase you quoted, is the cause of such an unexpected hilarity. ;-)

**Comment by sasumner** [comment]
So a lot of people are all about "my desired functionality is awesome and it must be in Notepad++ core".  I got this vibe from the OP of this issue.  Sure, there are ways to achieve what the OP wants, but none involve Notepad++ core.  But, reinforcing the earlier "vibe", the OP ignored the last 2 sentences of David's comments.

[David, your suggestion makes a lot of sense, but what rather kills it these days is the state Pythonscript is currently in.  It isn't currently just plug-n-play, and that effectively kills it for new users, especially non-programmers that will use it for only one tiny thing.  Sure it works great for my purposes, and probably yours as well.]

Re Jira:  I suppose it is a matter of context in order to get the joke.  Jira is notorious for so much functionality in plugins, that one wonders if there actually is a "core". And that emphasizes one of my main points:  You have to be around it for a long time to understand the "architecture" of something.  99% of readers of this issue that have been around Notepad++'s architecture will agree with what I've said in my replies to this issue.

**Comment by Petewg** [comment]
Well, "the OP" says 'hi and thanks for clarifying that ambiguous `Laughs-in-Jira`'. Knowing very few things (nothing, that is) about Jira architecture, was hard to understand the intended parody of the phrase but now it makes much better sense (and fun, as well). 
I agree, not all desired functionalities are awesome but some certainly are; (don't know whether  'Compare Selection with Clipboard' falls into this class or not but could be a candidate,  if not for anything else, just only for the reason that has pointed out by @DavidHansen-0x454d43 : 'it is a feature not found in any editor!' --frankly, a bit surprising thing but seems to be true..)
...
and then history might be written like this:
```
John Doe: «My `PadNote--` editor is freaking good! I can do everything with it.»
Dohn Joe: «Umm, maybe, but my `Notepad++` editor can do something that no other 
           editor could do, yours included!»
John Doe: «Huh? realy? and whatsit, please?»
Dohn Joe: «Can `Compare Selection with Clipboard`!» :-)
```
ok, enough with joking: I do not expect nor ask this functionality to be injected in "core" Np++,  it's enough for me to have this feature somehow available and working. Any suggestion on how to achieve this  would be highly appreciated.

**Comment by sasumner** [comment]
So a very simplistic version of how to meet the goal would be a Pythonscript that runs a compare utility.  I use BeyondCompare which is not a zero-cost option, but something open source like perhaps WinMerge will likely perform equally well.

One would run the following script, which BTW can be made into a right-click context menu item, and the desired compare will be done; here's an example result from my system:

![image](https://user-images.githubusercontent.com/30118311/65794500-47c3ab00-e136-11e9-88ee-019683204711.png)

One can see the selected text on the left, compared to the clipboard text on the right.

Here's the script:

    # -*- coding: utf-8 -*-

    from Npp import editor, notepad
    import subprocess
    import os

    try:
        editor_hidden
    except NameError:
        editor_hidden = notepad.createScintilla()

    def clipboard_get_text():

        editor_hidden.setText('')
        editor_hidden.paste()
        paste_buffer_text = editor_hidden.getText()
        return editor_hidden.getText()

    def main():

        compare_prog_path = r'C:\Program Files\Beyond Compare 4\BCompare.exe'
        selected_text_file_path = os.environ['TEMP'] + os.sep + 'npp_sel_text.txt'
        clipboard_text_file_path = os.environ['TEMP'] + os.sep + 'npp_cb_text.txt'

        sel_text = editor.getSelText()
        if len(sel_text) == 0: return  # no selected text to compare to
        clipboard_text = clipboard_get_text()
        if len(clipboard_text) == 0: return  # nothing to compare to in the clipboard

        with open(selected_text_file_path, 'w') as sf: sf.write(sel_text)
        with open(clipboard_text_file_path, 'w') as cf: cf.write(clipboard_text)

        subprocess.Popen([compare_prog_path, selected_text_file_path, clipboard_text_file_path])

    main()

Which brings us back to the difficulties of the current state of the Pythonscript plugin.  Not much to say (because it gets old), but some recent instructions for getting it installed appear in this otherwise unrelated support forum thread: https://community.notepad-plus-plus.org/topic/18297/mass-editing-g-code

**Comment by sasumner** [comment]
JohnDoe:   My Padnote-- editor is freaking good! I can do everything with it.
    Doh!John:  Umm, maybe, but my Notepad++ editor can do some things that no other editor can do, yours included!
    JohnDoe:   Huh? Really? And what is it, please?
    Doh!John:  Well, you name the functionality, and I can pretty much do it with my scripting plugin! :-)

**Comment by Ekopalypse** [comment]
@sasumner - what's up, don't you trust the python difflib library?? :-D

~~~
import ctypes
import difflib

user32 = ctypes.WinDLL('user32', use_last_error=True)
kernel32 = ctypes.WinDLL('kernel32', use_last_error=True)
CF_TEXT = 1

def get_clipboard_data():
    try:
        if user32.OpenClipboard(None):
            clipboard_handle = user32.GetClipboardData(CF_TEXT)
            if clipboard_handle:
                pointer_to_content = kernel32.GlobalLock(clipboard_handle)
                clipboard_data = ctypes.c_char_p(pointer_to_content).value
                kernel32.GlobalUnlock(clipboard_handle)
                return clipboard_data
            else:
                return None
        else:
            return None
    finally:
        if not user32.CloseClipboard():
            print(kernel32.GetLastError())
        
a = editor.getSelText()
if a:
    b = get_clipboard_data()
    if b:
        matcher = difflib.SequenceMatcher(None, a, b)
        for tag, i1, i2, j1, j2 in matcher.get_opcodes():
            print('{:7}   a[{}:{}] --> b[{}:{}] {!r:>8} --> {!r}'.format(
                tag, i1, i2, j1, j2, a[i1:i2], b[j1:j2]))

~~~

**Comment by Petewg** [comment]
I think we've got some hopefully `VFI`[*] outcomes, earned by this "vibrant" thread. 
I'm going to (try to) put the suggested scripts to work and see how it'll go; I've never used pythonscript and very rarely python itself, to say the truth.

thanks all participants for the time and understanding; 
special thanks to @sasumner  for the 'good will' and his readiness to offer help, 
as well as, @Ekopalypse for the code.
\______________________________________________________________
[*] `V`(alue) `F`(or) the `I`(nk) spent so far in this discussion!

**Comment by Ekopalypse** [comment]
@Petewg - just to make sure, my code might not be very useful as it just prints out the differences.
It was just a hint about the builtin difflib :-)
I think this would be best solved by [compare plugin](https://github.com/pnedev/compare-plugin/issues), maybe @pnedev will pick it up?

**Comment by sasumner** [comment]
@Ekopalypse said:

>don't you trust the python difflib library

It is not a matter of trust, it is a matter of "visual niceness".  Sure, it would be great (as in great for the OP) if it could be done in the Compare plugin, but I think my solution of spawning an external diff utility (that brings visualization) was an effective approach.  :)
