### ISSUE TITLE
[Feature Request] When using 'Find', don't highlight word that insertion cursor is at.

### ISSUE THREAD

**Issue by LAPIII** [notepad-plus-plus/notepad-plus-plus#6179]
That word automatically highlighting is annoying when switching tabs to copy something, especially with the Multiclipboard plugin which automatically copies upon highlight.

**Comment by sasumner** [comment]
With the "Find" window, it is a feature that many users like.  I don't think Notepad++ itself should be modified to work better with the way plugins do their thing; it should be the other way around.

**Comment by LAPIII** [comment]
There just should be an option to disable this though.

**Comment by donho** [comment]
Done in commit `Make filling find field of Find dialog with selected word(s) optional`:
https://github.com/notepad-plus-plus/notepad-plus-plus/commit/7a1096de5b3618bc3e6611e6c25caac952d41ae2

It will come with v7.8.3
