### ISSUE TITLE
Menu item name "Restore Recent Closed File" (id: 41021) is not translated

### ISSUE THREAD

**Issue by dg-wfk** [notepad-plus-plus/notepad-plus-plus#6180]
### Description of the Issue
Menu item name "Restore Recent Closed File" (id: 41021) is not translated although a language.xml file is present and contains the translation

### Steps to Reproduce the Issue
1. Open notepad++ in any language except English.
2. Click on first menu in menu bar (i.e. "Datei" in German).
3. Read 4th menu item from bottom.

### Expected Behavior
The menu item name should be translated (i.e. "Zuletzt geschlossene Datei wieder öffnen" in German).

### Actual Behavior
The menu item name is "Restore Recent Closed File" (tested with german.xml and dutch.xml).

### Debug Information
Notepad++ v7.7.1   (32-bit)
Build time : Jun 16 2019 - 21:14:50
Path : c:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 7 (64-bit)
Plugins : CodeAlignmentNpp.dll ComparePlugin.dll EmmetNPP.dll HexEditor.dll JsMapParser.NppPlugin.dll JSMinNPP.dll MarkdownViewerPlusPlus.dll mimeTools.dll NppConverter.dll NppExport.dll NppFTP.dll NppTextFX.dll PythonScript.dll Tidy2.dll 

![Untitled](https://user-images.githubusercontent.com/10115038/65767756-1dbaba80-e12f-11e9-8905-b4b55105896a.png)

**Comment by xylographe** [comment]
Presumably fixed in commit e9277deaa6853161514cc789edb2a083a516406b.

**Comment by SinghRajenM** [comment]
This seems to be working fine for me.. Am I missing something?

![image](https://user-images.githubusercontent.com/14791461/66015964-4c9bac80-e4f2-11e9-8c5b-b425feb21a35.png)

**Comment by xylographe** [comment]
@SinghRajenM 
According to the **Debug Information** the OP is using v7.7.1, which does not include your fix.
After the release of v7.7.2 this issue will/should be resolved.

**Comment by ArkadiuszMichalski** [comment]
@donho This can be close, was fixed.
