### ISSUE TITLE
Do not autocomplete the word I am editing with itselfself [sic]

### ISSUE THREAD

**Issue by 3ICE** [notepad-plus-plus/notepad-plus-plus#6182]
Hi,

I love everything about Notepad++. It is my main productivity tool and text editor. There's just this one issue that bothers me, happens around once a week...

While proofreading or editing text I often notice a mistyped word and navigate to it using UP/DOWN arrows. I fix the (usually) single letter typo in the middle and autocomplete instantly pops up, steals focus, suggesting the same word I just fixed. If I press enter it mangles my wordrd [sic]. Up/Down input focus are stolen from me forever and I find myself locked in a dropdown menu with one item. I eventually realize why my cursor isn't continuing to move up/down, sigh, and close the popup with ESC, but now ever so slightly more frustrated than I was by the typo itself.
The first few times this happened I tried to accept the pointless suggestion with enter, but that always lead to catastrophictrophic resultsults [sic]. (See Steps 7-8 below.)

Repro steps:

1. Configure autocomplete. (offer after each input, n=3, function and word completion both)
2. Type `mispell` on line 1 in an empty document, and hit enter.
3. Go back up, fix the typo by adding an "s" after "s": `misspell` - do not close the pointless popup
4. Try to go down to the next line with down arrow on your keyboard. Try again.
5. It does not work. You are stuck inside an infinitely edge-scrolling, 1 item dropdown.
6. Try to hit enter to accept / dismiss the nonsense recommendation
7. (Autocompleting `misspell` to `misspell`? Sure why not...)
8. Get `misspellpell` instead - oh no!

Workarounds:
Have to close it with ESC, not enter. (I can't reach ESC with my pinky finger.)
Or hold down left arrow until you get your cursor out of the word. (Takes too long...)
Or grope for your mouse in the dark so you can click out of it.

Expected behavior and recommended fix:
Don't offer to complete words while I am editing inside them / changing their middle.
Or if you do, overwrite everything with the correction until the next space.
Only if cursor is at EOF or before a space/dot/comma/dash/slash, should you offer to autocomplete.
If I need it I can still manually invoke with CTRL+space anywhere.
**Suggest any other word except the one I am working on right now. It is pointless to autocomplete a word into itself.**
If the user presses down while at the end of the dropdown, close it.
Up arrow pressed while already at the top of the list? Close it. Again.
The user is trying to escape, not scroll through the suggestion(s) infinitely. (Probably...)

Sincerely,
Daniel "3ICE" Berezvai

**Comment by Ekopalypse** [comment]
This is one trap I occasionally fall into as well. 
Another key combo which seems to work to close the autocomeplete feature is CTRL+SPACEBAR,
but it would be nice if it could be solved to replace the current word instead of inserting into the current position.

**Comment by sasumner** [comment]
@3ICE I like the title you gave this issue.  :)

**Comment by 3ICE** [comment]
I am glad :)
And how about that "catastrophictrophic resultsults" bit?

**Comment by jedio60** [comment]
Same issue here.

Hint: found two other key combo's to end the autocomplete:
1. Type Ctrl+ArrowUp or Ctrl+ArrowDown. Result: the autocomplete dialog disappears, the cursor remains where it was.
2. Type Ctrl+ArrowLeft or Ctrl+ArrowRight. Result: same but the cursor goes to beginning of current / next word.

Not working for me is Ctrl+Space like Ekopalypse suggested.

Still, it would be nice if the 'trap' wasn't there.
(Using Npp V7.8.6 64-bit)

**Comment by sasumner** [comment]
This is fixed in v. 7.8.7 so I'm going to close this issue.

**Comment by jedio60** [comment]
@sasumner, for my information, is there any way I could have seen (from the issue page) that this issue was already being worked on? On this page, the 'Assignees', 'Projects' and 'Milestone' sections are empty...

**Comment by sasumner** [comment]
@jedio60 I'm pretty sure that this issue here was an "orphan" (forgotten about) and that the person that worked on changing the behavior for 7.8.7 ( @Uhf7 I believe ) did so via another similar/duplicate issue.  So, if this indeed was an orphan, then No, there would have been no way for you to tell. :-)

**Comment by jedio60** [comment]
Thanks for the explanation, @sasumner. Hope that was the case (an accidental orphan) :-)
