### ISSUE TITLE
7.7.1 crash on start

### ISSUE THREAD

**Issue by wilkowy** [notepad-plus-plus/notepad-plus-plus#6185]
NPP crashes on start with error:

Title: "Exception On WM_CREATE"
Message: "Unlisted exception"

OS: WinXP 32b

**Comment by donho** [comment]
Please reopen it with whole debug info

**Comment by wilkowy** [comment]
@donho What whole debug info? There is none as NPP crashes on execution. I can only give you debug info from 7.6.6.
```
Notepad++ v7.6.6   (32-bit)
Build time : Apr  3 2019 - 23:49:50
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows XP (32-bit)
Plugins : AnalysePlugin.dll ComparePlugin.dll CustomizeToolbar.dll DSpellCheck2.dll mimeTools.dll MultiClipboard.dll NppBookmarkManager.dll NppConverter.dll NppExport.dll NppHasher.dll NppTextFX.dll PluginManager.dll 
```

**Comment by sasumner** [comment]
@donho How long do we go on caring about XP?

**Comment by wilkowy** [comment]
@donho How badly do you love sharing all your private files with foreign corporation?

**Comment by wilkowy** [comment]
@donho I'm sorry, it was supposed to be addressed to @sasumner

**Comment by sasumner** [comment]
@wilkowy said, apparently to me:

>How badly do you love sharing all your private files with foreign corporation?

What does that even mean, in general, but especially in the context of the current conversation?

**Comment by wilkowy** [comment]
@sasumner obviously you've suggested to upgrade OS.

**Comment by sasumner** [comment]
@wilkowy You might have paranoia problems.

**Comment by wilkowy** [comment]
@sasumner I will just ignore your rudeness. If you agree to use unblockable telemetry, online account and instant reboots - fine, that's your choice I'm not insulting you. I don't see in changelog any change referring to XP support drop so here I'm reporting this as a bug.
