### ISSUE TITLE
text is selected, when undo after paste something the text is not selected again

### ISSUE THREAD

**Issue by pexlechris** [notepad-plus-plus/notepad-plus-plus#6189]
### Description of the Issue

Hi. Because I use Ditto, I often do Ctrl+Z(undo) and then again Ctrl+V(Paste). The text that I had selected isn't now selected.

### Steps to Reproduce the Issue
 Set of steps to reproduce this issue 
1.  Select a text
2.  Paste something
3.  Undo 
The text that I had selected is not now selected so I need to selected again.

Is there a way to fix it?

Thanks

**Comment by sasumner** [comment]
Text selection isn't a change to textual content.  Only content changes are part of the Undo history.
