### ISSUE TITLE
Text area has a border even when "Border Width" option is set to 0

### ISSUE THREAD

**Issue by Rikk** [notepad-plus-plus/notepad-plus-plus#619]
"Border Width" value 0 is not truly 0.
So, what's up?
In Notepad++ we cannot:

- Directly select entire line when mouse is at leftmost pixel of the window.
- Use scrollbar when mouse is at rightmost pixel of the window.

While in every web browser, and Windows Explorer it is possible and very useful.

Npp (False 0) | Firefox (True 0)
--- | ---
![borderwidthnpp](https://cloud.githubusercontent.com/assets/2916485/9020388/3d0ab438-37df-11e5-80ca-fefb222cb81e.gif) | ![borderwidthfirefox](https://cloud.githubusercontent.com/assets/2916485/9020389/3d0cc23c-37df-11e5-8174-e04f4a7ef509.gif)

The Bad Border | Border Width = 0
--- | ---
![falseborder0](https://cloud.githubusercontent.com/assets/2916485/9235516/8df06cd2-4115-11e5-9e0b-48aa256a4d5e.png) | ![border0](https://cloud.githubusercontent.com/assets/2916485/9235520/911f9ee6-4115-11e5-9ffe-c367cdd79143.png)

**Comment by donho** [comment]
> "Border Width" value 0 is not truly 0.
> So, what's up? In Npp you can't use scrollbar when mouse it at rightmost pixel of the window

Are you sure about it?
I cannot reproduce what you describe while "Border Width" value is 0.

**Comment by Rikk** [comment]
I can reproduce everywhere, it has a window border remaining in all sides, which is created by `WS_EX_CLIENTEDGE` which is an extended style of windows.

**Comment by Rikk** [comment]
Uploaded sample image to pull request.

**Comment by Rikk** [comment]
Just found a nice discussion about tab styles:
https://sourceforge.net/p/scintilla/feature-requests/1058/
Npp would look better with flat tabs.

**Comment by dail8859** [comment]
+1 I like in alot of programs how the mouse can be directly against the right of the screen and still use the scrollbar.

**Comment by dail8859** [comment]
Plus it is [good GUI design](https://www.youtube.com/watch?feature=player_detailpage&v=E3gS9tjACwU#t=323) :)

**Comment by Rikk** [comment]
Reworded initial post to make this long-standing problem clearer. No excuses not to acknowledge the obvious existence of this.

**Comment by h-h-h-h** [comment]
@dail8859:
> +1 I like in alot of programs how the mouse can be directly against the right of the screen and still use the scrollbar.

:+1:

**Comment by donho** [comment]
https://github.com/notepad-plus-plus/notepad-plus-plus/commit/6c7ca02fea4aa64710c2eae1ab5192c49866dc6d
Thank you @dail8859 for the ref.
