### ISSUE TITLE
Proposing syntax highlighting for Q# language

### ISSUE THREAD

**Issue by FiorixF1** [notepad-plus-plus/notepad-plus-plus#6190]
Hi folks,

I recently learnt the Q# programming language by Microsoft for quantum computing and I thought a syntax highlighting feature for this language could be useful. I created one and I'm sharing it with you, if you think it is useful and well done you could add it officially to Notepad++.

[qs.txt](https://github.com/notepad-plus-plus/notepad-plus-plus/files/3680595/qs.txt)

**Comment by chcg** [comment]
@donho Would you accept a PR for it? Under https://github.com/notepad-plus-plus/notepad-plus-plus/tree/master/PowerEditor/bin/userDefineLangs or do you have other plans how to distribute UDLs?

**Comment by ArkadiuszMichalski** [comment]
@FiorixF1 you can share it on https://github.com/notepad-plus-plus/userDefinedLanguages. @donho this bug still necessary?

**Comment by donho** [comment]
@chcg 
> Would you accept a PR for it? Under https://github.com/notepad-plus-plus/notepad-plus-plus/tree/master/PowerEditor/bin/userDefineLangs 

Oups, sorry. I didn't see your ping. Yes sure, please check if it's in it (if not, include it), and close this issue.

@ArkadiuszMichalski Thank you for the heads up.

**Comment by chcg** [comment]
@donho I think this is not one you want to bundle with N++ delivery, but it should be part of the UDL repo. I created https://github.com/notepad-plus-plus/userDefinedLanguages/pull/37 for it
