### ISSUE TITLE
[security] Download package served under HTTP

### ISSUE THREAD

**Issue by yehgdotnet** [notepad-plus-plus/notepad-plus-plus#6192]
### Description of the Issue
It's always been a while that installer link is served over HTTP
http://download.notepad-plus-plus.org/repository/7.x/7.7.1/npp.7.7.1.Installer.exe

### Steps to Reproduce the Issue
1. Go to https://notepad-plus-plus.org/downloads/v7.7.1/
2. Notice the download link

### Actual Behavior
Serve under HTTPS

**Comment by dinkumoil** [comment]
When trying to download v7.7.1 via HTTPS (https://download.notepad-plus-plus.org/repository/7.x/7.7.1/npp.7.7.1.Installer.exe), the browser shows an `SSL_ERROR_BAD_CERT_DOMAIN`. The reason is that the certificate is only valid for `npp-user-manual.org`.

**Comment by beerisgood** [comment]
Problem is:
**Certificate name mismatch**
https://www.ssllabs.com/ssltest/analyze.html?d=download.notepad-plus-plus.org

Mozilla's Overvatory give rating "F": https://observatory.mozilla.org/analyze/download.notepad-plus-plus.org

@donho : please fix it

**Comment by KOLANICH** [comment]
@donho

**Comment by donho** [comment]
Thank you @beerisgood @KOLANICH 
I'm working on it.

**Comment by KOLANICH** [comment]
In fact not yet anymore, since the downloads are served from GitHub directly now, and it is available by https.

**Comment by donho** [comment]
all the unsecured "http://..." links are removed from https://notepad-plus-plus.org / site.

**Comment by donho** [comment]
@KOLANICH 
> In fact not yet anymore, since the downloads are served from GitHub directly now, and it is available by https.

The old download for v7.8, v7.7.1 & v7.7 pointed still to http://download.notepad-plus-plus.org/. I just fixed them.

**Comment by KOLANICH** [comment]
Thank you.
