### ISSUE TITLE
N++ 7.7.1 64bit incorrectly colors the string in backticks

### ISSUE THREAD

**Issue by quantuumsnot** [notepad-plus-plus/notepad-plus-plus#6193]
![npp_v771_64bit](https://user-images.githubusercontent.com/12394810/66143203-6c74c280-e60f-11e9-901e-fba245ab52a7.png)

File is an inline Javascript in .html

**Comment by DavidHansen-0x454d43** [comment]
What kind of file is this? Or in other words, which language is it coloring?
(All I can see from your screenshot is 'up language')

This looks like a Scintilla issue to me... not much we can do until they patch first. 
Is this already being [tracked there](https://sourceforge.net/p/scintilla/bugs/)?

**Comment by quantuumsnot** [comment]
Sorry, thought it was clear it's a Javascript

**Comment by DavidHansen-0x454d43** [comment]
This issue is being tracked here: [#1112 JS: lexer support for template strings](https://sourceforge.net/p/scintilla/feature-requests/1112/).

**Comment by donho** [comment]
https://github.com/notepad-plus-plus/notepad-plus-plus/issues/3822#issuecomment-697275450
