### ISSUE TITLE
Need some basic guidance for a simple timestamp script

### ISSUE THREAD

**Issue by mwpowellhtx** [notepad-plus-plus/notepad-plus-plus#6195]
Hello, I need some guidance for a simple timestamp script. It seems like the avenues I am considering are all met with one hang up or another, and I wonder what others have been able to do there. Once I have a working scripting environment, maybe there is a viable path forward. Also following up through the individual plugin authors' sites, rest assured. The purpose of this post is to gain insights from the holistic *Npp* perspective.

* First consideration, [*PythonScript*](https://github.com/bruderstein/PythonScript). I'd used this approach for awhile, until recently. I've found there have been a couple of issues with it. First, the *Npp* plugin architecture changed? Not sure *PS* has caught up there. Second, I'm fuzzy on the nature of *PS* 64-bit versus 32-bit support. If memory serves the support there has been sketchy at best.

* Second, I learned about [*CS-Script IntelliSense*](https://github.com/oleg-shilo/cs-script.npp). This one shows promise, but it is a bit undone, I think. I've followed up with the author on this one, and a viable path forward, including requisite interop plugins in order to engage properly with the *Npp* environment, is perhaps a month or so out. I wondered if others' experience here was similar, whether it was just me, I was missing something, etc.

* Third, [*LuaScript*](https://github.com/dail8859/LuaScript), but the documentation seems somewhat sparse. I just want to print a simple time stamp, for starters, but I'm not sure quite where to get started with that.

**Comment by sasumner** [comment]
The place for questions is here:  https://community.notepad-plus-plus.org/

In fact, that place is absolutely perfect for your question.

**Comment by mwpowellhtx** [comment]
Turns out I was able to do what I wanted to do pretty simply using *LuaScript*, but I will check out the forums for the broader question, thank you.
