### ISSUE TITLE
[Request] Slight reordering of save, close, and print buttons.

### ISSUE THREAD

**Issue by JonRurka** [notepad-plus-plus/notepad-plus-plus#6199]
There have been a number of times I have gone to press the 'Save All' button on the top left, but have miss clicked and hit the button to close the document. Most of the time, this doesn't affect anything because I press 'Cancel' on the following prompt, however a few times I have mistakenly pressed 'No' and frustratingly lost changes. I feel like placing the Print button between the save buttons and the document close buttons instead of after would make a much safer choice and completely overt the risk of loosing work from such miss-clicks.

**Comment by Ekopalypse** [comment]
Install customize toolbar plugin and reconfigure the layout like you want.

**Comment by sasumner** [comment]
@JonRurka

>I have mistakenly pressed 'No' and frustratingly lost changes.

Read what the user interface is asking you.  Then there should be no "mistakenly pressed..." answer to a dialog box question.

Accidentally pressing the wrong toolbar button I fully understand.  They are small, but you can make them bigger if you want.

>I feel like placing the Print button between the save buttons and the document close buttons ... would make a much safer choice

Yea, but think of the paper you would waste when you "mistakenly press" the Print button in the dialog that comes up when you press the toolbar's Print button.  :-)
