### ISSUE TITLE
Update HTML lexer/ styling: TAGUNKNOWN / ATTRIBUTEUNKNOWN

### ISSUE THREAD

**Issue by webketje** [notepad-plus-plus/notepad-plus-plus#6200]
### Description of the Issue
The HTML syntax highlighting doesn't do justice to HTML5 data-attributes, custom elements & custom attributes. Below is a screenshot of the Zenburn theme on a .html file:

![Imgur](https://i.imgur.com/78yDQtk.png)

* `data-`prefixed attributes are styled as ATTRIBUTEUNKNOWN.
* TAGUNKNOWN styling overwrites ATTRIBUTE/ ATTRIBUTEUNKNOWN styling. (might also be the case for XML)

### Steps to Reproduce the Issue
Load any HTML file with custom elements, and custom or data-attributes

### Expected Behavior
* `data-`prefixed attributes shouldn't be styled as ATTRIBUTEUNKNOWN: they have been part of the standard for ages and have a corresponding DOM API, see https://developer.mozilla.org/en-US/docs/Learn/HTML/Howto/Use_data_attributes.
* TAGUNKNOWN styling shouldn't overwrite the styling for  ATTRIBUTE/ ATTRIBUTEUNKNOWN. In the example above I'd expect only the `<custom-element ></custom-element>` to be colored rose, and the attributes to be maroon/white just like in the known tag.

### Debug Information
Notepad++ v7.7.1   (64-bit)
Build time : Jun 16 2019 - 21:24:47
Path : C:\Workdir\MyApps\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : ON
OS : Windows 10 (64-bit)
Plugins : BetterMultiSelection.dll JSMinNPP.dll MenuIcons.dll mimeTools.dll NppConverter.dll NppEventExec.dll NppExec.dll NppFTP.dll NppSaveAsAdmin.dll NppSnippets.dll NppTaskList.dll OpenSelection.dll PythonScript.dll SessionMgr.dll SurroundSelection.dll XMLTools.dll _CustomizeToolbar.dll

**Comment by zufuliu** [comment]
For HTML5 custom element, see https://sourceforge.net/p/scintilla/feature-requests/1299/

**Comment by ArkadiuszMichalski** [comment]
Above bug was fixed in Scintilla. Backing to `data-`, there also was bug https://sourceforge.net/p/scintilla/feature-requests/1278/, but closed because:  "Isn't this handled by using a prefix keyword ^data- as is done in SciTE?".

**Comment by ArkadiuszMichalski** [comment]
@donho Looks like adding `^data-` to `langs.model.xml` for HTML also work in Notepad++.

Before:
![b](https://user-images.githubusercontent.com/2730894/94036541-b4fb3200-fdc4-11ea-9937-06f75b8b7a8e.gif)

After:
![a](https://user-images.githubusercontent.com/2730894/94036574-ba587c80-fdc4-11ea-9726-6f589ee61fff.gif)

Custom elements need a newer version of Scintilla.

**Comment by donho** [comment]
@ArkadiuszMichalski 
Could you create a PR for that please?
