### ISSUE TITLE
[bug] Inserting date and time by using TextFX Insert menu gives incorrect results

### ISSUE THREAD

**Issue by wonkawilly** [notepad-plus-plus/notepad-plus-plus#6204]
### Description of the Issue

When I try to insert date and time in long format I have issues on accented chars as shown in the image bellow instead of the "ì" char (the accented "i") the function returns the equivalent Unicode Hex Character Code "xEC".
So the date appears as:
"16:02 mercoled**xEC** ottobre 2019"
So I have to correct it manually every time I use that function menu loosing time

Notice that the bold part has a black background I can't reproduce in this comment as text so I'm going to attach an image at the end of this comment.

### Steps to Reproduce the Issue

1. Go to the n++ menu TextFX > TextFX Insert > Date & Time Long Format (or press the short cut from the keyboard: in my installation of n++ is "Shift +F10")

### Expected Behavior

To have the correct date and time inserted

### Actual Behavior

the accented "i" char is replaced by the xEC symbol with black background

### Debug Information

Notepad++ v7.5.8   (32-bit)
Build time : Jul 23 2018 - 02:03:53
Path : E:\Software\npp.7.5.8.bin\notepad++.exe
Admin mode : OFF
Local Conf mode : ON
OS : Windows 7 (32-bit)
Plugins : AutoSave.dll CodeAlignmentNpp.dll combine.dll ComparePlugin.dll DSpellCheck.dll ElasticTabstops.dll EmmetNPP.dll Explorer.dll gtagfornplus.dll HexEditor.dll HTMLTag_unicode.dll ImgTag.dll IndentByFold.dll JSLintNpp.dll JsMapParser.NppPlugin.dll JSMinNPP.dll linefilter2.dll LocationNavigate.dll mimeTools.dll MultiClipboard.dll NamedBookmarks.dll NppAutoIndent.dll NppBookmarkManager.dll NppCCompletionPlugin.dll NppColumnSort.dll NppConverter.dll NppExport.dll NppFTP.dll NPPJSONViewer.dll NppQCP.dll NppSnippets.dll NppTaskList.dll NppTextFX.dll NppToolBucket.dll PluginManager.dll PreviewHTML.dll PythonScript.dll QuickOpenPlugin.dll RunMe.dll SnippetPlus.dll SourceCookifier.dll sql.dll SQLinFormNpp.dll Tidy2.dll WebEdit.dll XMLTools.dll ZenCoding-Python.dll _CustomizeToolbar.dll 

### Question
Is there anyone else that actually has the same issue or it is just me?

### Attached screenshot of the issue:
![n++xec](https://user-images.githubusercontent.com/34818345/66488877-fa88f700-eaae-11e9-89d0-e1f639c2b688.png)

**Comment by sasumner** [comment]
TextFX is not part of Notepad++.  This is the (core) Notepad++ issues list.  Please find an appropriate place (elsewhere) to report problems with TextFX.  Thank you.

**Comment by wonkawilly** [comment]
> TextFX is not part of Notepad++. This is the (core) Notepad++ issues list. Please find an appropriate place (elsewhere) to report problems with TextFX. Thank you.

Unfortunately I can't reach the web site http://textfx.no-ip.com/textfx
