### ISSUE TITLE
Crash when pasting anything into the find or replace dialog

### ISSUE THREAD

**Issue by Wegerich** [notepad-plus-plus/notepad-plus-plus#6205]
### Description of the Issue
NP++ crashes when anything is _pasted_ into the ctrl+f dialog

### Steps to Reproduce the Issue

1. Open NP++
2.  Ctrl+f
3. paste from clipboard

### Expected Behavior

Not crash

### Actual Behavior

Software hangs then crashes

### Debug Information

Pressing ctrl+v when the text entry boxes in the find & replace screen are not active does not cause the crash. 

Notepad++ v7.7.1   (32-bit)
Build time : Jun 16 2019 - 21:14:50
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10 (64-bit)
Plugins : DSpellCheck.dll mimeTools.dll NppConverter.dll NppExport.dll

**Comment by sasumner** [comment]
Works for me:

![image](https://user-images.githubusercontent.com/30118311/66517277-d9290a80-eab0-11e9-817f-389ccb7edaac.png)

Clearly I can paste "anything".

**Comment by DavidHansen-0x454d43** [comment]
@Wegerich are you pasting strange unicode characters or something? 

It would really help if you could include a failing string so others can reproduce the problem.

**Comment by Wegerich** [comment]
It started when I tried to paste the string `order_notes`.

Now any regular text causes a 100% reproducible crash.

**Comment by Ekopalypse** [comment]
@Wegerich - give it a try to rename the notepad++ directory under %APPDATA% and then start npp
and retest. The directory and the default config files do get recreated upon npp startup.

**Comment by Wegerich** [comment]
It's still happening after doing that. 

I haven't restarted the computer yet because I wanted to preserve the bug in case you all wanted to try and debug it thoroughly. 

If that isn't necessary then I can reboot and it will probably fix, as these things go.

**Comment by Ekopalypse** [comment]
No need to reboot if the directory has been recreated but obviously it has otherwise I would have expected npp to complain about missing configs.
Do you use some unusual software like screen readers, auto-mouse,  voice guided ... ?

**Comment by Wegerich** [comment]
I  don't use any accessibility software. I tried killing all the processes running in my tray (autohotkey, Transmission, skype and others) and I could still reproduce the error. 

Before re-enabling anything I tried the portable NPP version and I can also reproduce the issue with that.

**Comment by Ekopalypse** [comment]
When you go to eventviewer, do you see any logged error message from npp and if yes,
what does it report?

**Comment by Wegerich** [comment]
```
Faulting application name: OUTLOOK.EXE, version: 16.0.12026.20264, time stamp: 0x5d8be281
Faulting module name: Comctl32.dll, version: 6.10.17134.1038, time stamp: 0x21d6fad8
Exception code: 0xc0000005
Fault offset: 0x00090678
Faulting process ID: 0x2f4d0
Faulting application start time: 0x01d57ee56b11ee74
Faulting application path: C:\Program Files (x86)\Microsoft Office\root\Office16\OUTLOOK.EXE
Faulting module path: C:\WINDOWS\WinSxS\x86_microsoft.windows.common-controls_6595b64144ccf1df_6.0.17134.1038_none_1babc31c910db48c\Comctl32.dll
Report ID: 6faa27a5-c25f-4326-b965-879e55f90904
Faulting package full name: 
Faulting package-relative application ID: 

Faulting application name: notepad++.exe, version: 7.7.1.0, time stamp: 0x5d0695c2
Faulting module name: COMCTL32.dll, version: 6.10.17134.1038, time stamp: 0x21d6fad8
Exception code: 0xc000041d
Fault offset: 0x000fc301
Faulting process ID: 0x2e10c
Faulting application start time: 0x01d57edcb34d486c
Faulting application path: C:\Program Files (x86)\Notepad++\notepad++.exe
Faulting module path: C:\WINDOWS\WinSxS\x86_microsoft.windows.common-controls_6595b64144ccf1df_6.0.17134.1038_none_1babc31c910db48c\COMCTL32.dll
Report ID: d5669a03-720b-4758-81ee-0e73a710f2d0
Faulting package full name: 
Faulting package-relative application ID: 

Faulting application name: notepad++.exe, version: 7.7.1.0, time stamp: 0x5d0695c2
Faulting module name: COMCTL32.dll, version: 6.10.17134.1038, time stamp: 0x21d6fad8
Exception code: 0xc000041d
Fault offset: 0x000fc301
Faulting process ID: 0x2aa70
Faulting application start time: 0x01d57ee93ce87e25
Faulting application path: C:\Users\Username\Desktop\npp.7.7.1.bin\notepad++.exe
Faulting module path: C:\WINDOWS\WinSxS\x86_microsoft.windows.common-controls_6595b64144ccf1df_6.0.17134.1038_none_1babc31c910db48c\COMCTL32.dll
Report ID: 8228d5d4-1f01-4d33-88dd-c16746493c58
Faulting package full name: 
Faulting package-relative application ID: 
```

**Comment by Ekopalypse** [comment]
Your COMCTL32.dll seems to be corrupted

**Comment by Wegerich** [comment]
OK, let me try rebooting and see if that heals it

**Comment by Wegerich** [comment]
This is a poorly computer after years of daily use. Bug seems like it's not contagious to other NPP installs though.

Thanks for your patience and assistance, I have some healing to do

**Comment by Ekopalypse** [comment]
>This is a poorly computer after years of daily use

Sounds like hdd issue? Good luck.

**Comment by Wegerich** [comment]
We may never know the root cause but fortunately running SFC /scannow fixed the problem

**Comment by Ekopalypse** [comment]
No problem :-)
If I were you I would run a harddisc diagnostic. 
SFC /scannow can replace bad sectors as long as there are spare ones, once those are gone ...
