### ISSUE TITLE
Context menu Edit with Notepad++

### ISSUE THREAD

**Issue by mansao** [notepad-plus-plus/notepad-plus-plus#6206]
Context menu
Edit with Notepad++
Using to open a file with extension .nfo.
The Notepad++ closes without warning.

Notepad++ v7.7.1   (32-bit)
Build time : Jun 16 2019 - 21:14:50
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : ON or OFF
Local Conf mode : OFF
OS : Windows 10 (64-bit)
Plugins : ComparePlugin.dll HexEditor.dll mimeTools.dll NppConverter.dll NppExport.dll NppFTP.dll

**Comment by Ekopalypse** [comment]
I tried it and it seems to work for me.
Can you provide a file in question?

**Comment by mansao** [comment]
Hi,
From what I saw you did not take into consideration the plugins I have installed.
This HexEditor.dll plugin that is generating the problem.

**Comment by mansao** [comment]
> I tried it and it seems to work for me.
> Can you provide a file in question?
> 
> Update: It has been reported [here](https://github.com/notepad-plus-plus/notepad-plus-plus/issues/924) that the hexeditor seems to be involved in this. Could you test without
> having hexeditor installed?

You can create an empty file or put anything in the file. And yes I discovered the bug because I removed the plugin and it worked.

**Comment by Ekopalypse** [comment]
>From what I saw you did not take into consideration the plugins I have installed.

If I didn't, why did I ask you to give it a try without having hexeditor plugin installed? :-)

>... I removed the plugin and it worked.

So you can close this issue, can't you?

**Comment by sasumner** [comment]
Ugh, I'll close it.

**Comment by mansao** [comment]
Real patience comes from wisdom.

**Comment by mansao** [comment]
> Ugh, I'll close it.

Real patience comes from wisdom.
