### ISSUE TITLE
Upload GPG key to keys.openpgp.org

### ISSUE THREAD

**Issue by beerisgood** [notepad-plus-plus/notepad-plus-plus#6207]
Please upload your GPG key to new, secure GPG server:
https://keys.openpgp.org

Then users can use that for verifying your key against the fingerprint on [Github](https://github.com/notepad-plus-plus/notepad-plus-plus#notepad-release-key) which increase your key security against manipulation / unwanted changes on Github.

**Comment by donho** [comment]
Done

**Comment by beerisgood** [comment]
Thanks.
Maybe add the [link](https://keys.openpgp.org/search?q=14BC+E436+2749+B2B5+1F8C+7122+6C42+9F1D+8D84+F46E) to https://github.com/notepad-plus-plus/notepad-plus-plus#notepad-release-key

Maybe make the key ID or Fingerprint clickable with that link
