### ISSUE TITLE
Open one instance per virtual desktop

### ISSUE THREAD

**Issue by diemmarkus** [notepad-plus-plus/notepad-plus-plus#621]
If I double click a text file on Windows 10 in the first virtual desktop and I have a running notepad++ instance on e.g. desktop 3, windows switches to this desktop. I have just learned how to open files in new windows (http://superuser.com/questions/202399/how-to-make-notepad-open-each-file-in-new-window) which will do the trick for the moment. However, it would be nice to open text files in the same instance on each virtual desktop.

thanks,
markus

**Comment by justanotheranonymoususer** [comment]
I second this request.

**Comment by bquistorff** [comment]
In a subset of cases, there might be a easier solution. If there is an NPP instance in my current virtual desktop, but the most recently used instance (to had window focus) is on a different virtual desktop, then opening a file will currently switch to that other virtual desktop. In mono-instance mode, could files be opened in (a) the most recently used instance in this desktop, and if there are none, then (b) the most recently used instance anywhere?

**Comment by diemmarkus** [comment]
Apps can be made 'sticky' since the last Windows update which does the trick for me (so I guess this request can be closed).

**Comment by dobos** [comment]
The explorer context menu could also be extended with some options such as
* edit with notepad++
* more options
    * edit in available instance
    * edit on same destop
    * edit in new instance
Any of the could be made default or clicking shift/ctrl when clicking on the main option could also alter the default behavior, just to make the menu simpler (if that's supported by the windows shell). Taking things even further: allow naming instances and add menu items dynamically to open files in XX instance.

**Comment by dobos** [comment]
Here's some info on how to access virtual desktop with the win 10 api

https://social.msdn.microsoft.com/Forums/windowsdesktop/en-US/fd52fc39-d1f3-4da8-8b68-debceab75ffd/requesting-api-calls-for-windows-10s-virtual-desktops?forum=windowsgeneraldevelopmentissues

**Comment by arsou33** [comment]
Open in instance on current desktop seems the good way. May be add that option to multiple instance management option.

**Comment by Error-101** [comment]
Is there any progress on this?

**Comment by MetaChuh** [comment]
we are closing this issue due to its age and multiple newer notepad++ versions since it was filed.

please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html).
if your issue persists, and it is still of relevance to you, please feel free to file a new issue.

thank you for your help and best regards.

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
```
[<kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd>](https://notepad-plus-plus.org/community/)

**Comment by Nu11u5** [comment]
I worked around this by adding the -multiInst parameter to a shortcut in the Start Menu. Using this shortcut allows starting a new instance that appears on the active virtual desktop without switching over to an existing instance on a different virtual desktop.

Using "Open with Notepad++" will cause the file to open in the most recent active instance between all virtual desktops.
