### ISSUE TITLE
Read Only option doesn't set Read Only flag 

### ISSUE THREAD

**Issue by KulaGGin** [notepad-plus-plus/notepad-plus-plus#6216]
### Description of the Issue
Read Only option doesn't actually set file to read only.

### Expected Behavior
When I press read only, I expect it to set Read Only flag in properties of the file.

### Actual Behavior
Sets file to read only mode only in Notepad++ editor.

### Steps to Reproduce the Issue
Video: https://youtu.be/0GLjCSH5y_k

I think it would be better to make Notepad++ switch "Clear Read-Only Flag" option to "Set Read-Only Flag" option when Read-Only Flag isn't set in the properties of the file. And change "Read Only" option to "Read Only mode" to indicate that it doesn't actually set Read-Only Flag respectively. From what I understand at the moment there is no way to set Read-Only flag from inside of Notepad++, only clear it, right?

### Debug Information
Notepad++ v7.7.1   (32-bit)
Build time : Jun 16 2019 - 21:14:50
Path : D:\Programs\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10 (64-bit)
Plugins : ComparePlugin.dll mimeTools.dll NppConverter.dll NppExport.dll NppTextFX.dll

**Comment by Ekopalypse** [comment]
You can, in run menu put the following to set the read only flag
`cmd /C attrib +R  "$(FULL_CURRENT_PATH)"`
save it and, if you like, assign a shortcut.

**Comment by sasumner** [comment]
>Read Only option doesn't actually set file to read only.

This behavior is "by design".
