### ISSUE TITLE
Implement a modern skin

### ISSUE THREAD

**Issue by chilli2** [notepad-plus-plus/notepad-plus-plus#622]
For the love of god could you please make the app look like something that wasn't designed a decade ago. I love Notepad++ but my eyes bleed whenever I look at anything but the actual text and code. The tabs, the frame around the editor, the icons ... they could all use some love. When will the design get some attention?
I mean this is just bad: http://i.imgur.com/CxsPdop.jpg

I'm not expecting something fancy like: http://rdtsod.deviantart.com/art/Notepad-HTML-Editing-mode-CONCEPT-446762450
but still, something that looks ok. I'm sure there are plenty of fans who could help with this and I'd be one of them. You're at version 6.8, and yet this looks like 1.0 (the 2003 release)

**Comment by milipili** [comment]
Already planned :)

**Comment by Rikk** [comment]
>Already planned :)

@milipili how will the interface be rendered? What I see programs doing and I think allows powerful customization is using an engine capable of rendering HTML/XML, [Firefox uses XUL](https://developer.mozilla.org/en-US/docs/Mozilla/Tech/XUL/Introduction_to_XUL), for example.

**Comment by chilli2** [comment]
cool, thanks

**Comment by milipili** [comment]
@rikk One thing at a time :)

**Comment by milipili** [comment]
Discussion on nodebb: https://notepad-plus-plus.org/community/topic/250/it-s-time-for-ui-update

**Comment by chilli2** [comment]
@milipili I can't seem to post there on either firefox or chrome (logged in; hitting reply does nothing). The console throws
Uncaught ReferenceError: module is not defined nodebb.min.js?b86e96eb:12 
though I'm not sure if it has anything to do with it

**Comment by milipili** [comment]
@chilli2 Sorry nodebb update. Could you try again ?

**Comment by milipili** [comment]
A bug report to nodebb has been issued

**Comment by milipili** [comment]
Theme: personna

**Comment by milipili** [comment]
@chilli2 Your problem should be solved (see https://github.com/NodeBB/NodeBB/issues/3378)
