### ISSUE TITLE
Syntax highlighting broken when moving to another instance

### ISSUE THREAD

**Issue by cronoxyd** [notepad-plus-plus/notepad-plus-plus#6221]
### Description of the Issue

When dragging & dropping a NPP tab from one window to another, the syntax highlighting is broken.

### Steps to Reproduce the Issue

1. Open three documents with syntax highlighting in NPP 
2. Drag & Drop one of the tabs onto a free space of the desktop to create a new window (instance)
3. Drag & Drop another document from the original instance onto the new instance

### Expected Behavior
The document opens in the new instance and syntax highlighting works as normal.

### Actual Behavior
The document opens in the new instance and syntax highlighting does not work

#### Inital state
![npp_syntaxissue1](https://user-images.githubusercontent.com/45272659/66820106-5be21780-ef40-11e9-8d1e-fff9a66cb6f1.png)
#### New instance created by Drag & Drop (Syntax highlighting works)
![npp_syntaxissue2](https://user-images.githubusercontent.com/45272659/66820114-5e447180-ef40-11e9-9650-a4d5eed41263.png)
#### Moving another document to new instance breaks the syntax highlighting
![npp_syntaxissue3](https://user-images.githubusercontent.com/45272659/66820313-b54a4680-ef40-11e9-9e27-51f9b3baa032.png)

### Debug Information
Notepad++ v7.7.1   (64-bit)
Build time : Jun 16 2019 - 21:24:47
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10 (64-bit)
Plugins : mimeTools.dll NppConverter.dll NppFTP.dll

**Comment by PalashBansal** [comment]
Not able to reproduce the issue :(
Please try in latest version as of date- v7.8 and report back if issue persists.
