### ISSUE TITLE
New feature-> Rename file shortcut button- F2

### ISSUE THREAD

**Issue by PalashBansal** [notepad-plus-plus/notepad-plus-plus#6235]
Notepad++ is meant for being the fastest. Can we have a rename shortcut button, "**F2**" as a standard(as even windows OS gives F2). So no need to click on tab and select "rename"

I can see F2 button is not reserved for any other functionality as well in npp

### Steps to Reproduce the Issue
1. Press F2
2. Nothing will happen.

To rename file, either go to File menu > "Rename..." or right click a tab and select "Rename"

### Expected Behavior
Pressing F2 should open Rename dialog(windows "save as" dialog for saved file while npp's own dialog "rename current tab" for new file)

### Actual Behavior
F2 doesn't work.

### Debug Information
Not a bug

Please let me know the feedback in comments or if problem is non understandable, i will create some screenshots.

**Comment by xylographe** [comment]
Item 12 in **Settings > Shortcut Mapper... > Main menu** is called "Rename"!
By default,  F2 is associated with "Next Bookmark".

**Comment by PalashBansal** [comment]
Thanks a lot xylographe. This clears up. Closing this issue.
