### ISSUE TITLE
[bug report - textfx plugin] sorting lines “uniquely” deletes a line that isn't a duplicate.

### ISSUE THREAD

**Issue by GhbSmwc** [notepad-plus-plus/notepad-plus-plus#6238]
(I apologize if this is the wrong place to post here)

I'm using:

- Notepad++ v 7.7.1 (32-bit)
- TextFX version 0.26

Create this text (verbatim):
```
a/b/c/d
a/b/c
```
Make sure there is no linebreak after “a/b/c”. Now make sure you have the textFX setting set to this:
![image](https://user-images.githubusercontent.com/13095760/67160394-3e38f780-f31e-11e9-8688-ecb16196a45d.png)
Now select all, and then “Sort lines case sensitive (at column)”. Instead of having the lines resulting this:
```
a/b/c
a/b/c/d
```
It resulted this:
```
a/b/c/d
```
This will not happen if you have a linebreak after “a/b/c”.

**Comment by sasumner** [comment]
Wrong place.  Apology accepted.
