### ISSUE TITLE
[Feature Request] Join sets of lines.

### ISSUE THREAD

**Issue by LAPIII** [notepad-plus-plus/notepad-plus-plus#6241]
### Steps to Reproduce the Issue

1.  Select group of lines
2.  Hold Left Alt and select another group of lines
3.  Hold Left Alt and select another group of lines

### Expected Behavior
The groups of lines to join into separate lines.

### Actual Behavior
Only the last group of lines joined together

**Comment by sasumner** [comment]
Doing step 2 will cancel the selection made in step 1.  Thus there really aren't multiple selections to join together here.  Can you clarify what you are asking for?

**Comment by Ekopalypse** [comment]
I assume @LAPIII meant CTRL but even if this is the case, it is, for me, not 100% clear what is expected.

An example might clarify the situation.
Currently I'm thinking OP want to have something like this

Given a text like this

```
Line1
Line2 
Line3 
Line4 
Line5 
Line6 
Line7 
Line8 
Line9 
Line10
```

Assuming Line1 and 2 are selected, Line4 and 5 and Line7 and 8
Result after joining should be

```
Line1Line2 
Line3 
Line4 Line5 
Line6 
Line7 Line8 
Line9 
Line10
```

**Comment by sasumner** [comment]
Note:  Relies on "multi-editing" being enabled in order to make more than one selection.

Why not simply use one selection, then join lines, then do another selection, then join those lines, etc.?

Closing; will consider reopening if more info supplied.
