### ISSUE TITLE
Alt+Tab doesn't show NPP

### ISSUE THREAD

**Issue by PalashBansal** [notepad-plus-plus/notepad-plus-plus#6244]
### Description of the Issue
When a subwindow is opened inside NPP, and we press windows provided shortcut Alt+Tab to switch to other opened application, NPP doesn't come up in options.
This happens only for some subwindows like "Rename Current Tab" or "Close All > Save dialog" opened. If "Preference" dialog is opened, issue doesn't occur.

### Steps to Reproduce the Issue
1. Open either "Rename current tab" by right clicking on new tab(doesn't exist in file system) followed by "Rename" option. OR Keep 2 or more files unsaved and click "Close All" option to get "Save" dialog.
2. Keep "Alt+Tab" shortcut pressed and see NPP missing.
3. Switch to some other application.
4. Again try above step 2. And switching to NPP is not possible.
**Workaround-**
To switch to NPP from taskbar only.

### Expected Behavior
"Alt+Tab" should show NPP application always(if NPP is in launched state)

### Actual Behavior
NPP doesn't appear in application options from "Alt+Tab"

### Debug Information
Seems like issue is easily reproducible for every user, still enjoy-
Notepad++ v7.8   (64-bit)
Build time : Oct  7 2019 - 00:55:55
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS Name : Windows 7 Professional (64-bit) 
OS Build : 7601.23833
Plugins : mimeTools.dll NppConverter.dll NppExport.dll

**Comment by sasumner** [comment]
>Seems like issue is easily reproducible for every user

Not for me.  I can successfully alt+tab back to Notepad++ in any of the above scenarios.  Maybe the difference is one of Win7 versus Win10?

Me:

Notepad++ v7.8   (64-bit)
Build time : Oct  7 2019 - 00:55:55
Path : C:\.........\Releases\npp.7.8\npp.7.8.bin.x64\notepad++.exe
Admin mode : OFF
Local Conf mode : ON
OS Name : Windows 10 Enterprise (64-bit) 
OS Version : 1709
OS Build : 16299.1387
Plugins : mimeTools.dll NppConverter.dll NppExport.dll

**Comment by Ekopalypse** [comment]
It works for me on Windows 7 x64 BUT only one time.
Follow the steps as described, 
- switch to another running application by using alt+tab
- switch back to npp using alt+tab
- press alt+tab again -> Npp icon is gone.

**Comment by PalashBansal** [comment]
@sasumner
I just checked in my office system(win 10 enterprise), it's working perfectly.
So it's a **compatibility issue** with Win7 then.
Raised a PR(fix for Win7)- https://github.com/notepad-plus-plus/notepad-plus-plus/pull/6252

**Comment by donho** [comment]
I cannot reproduce it at all.
Any stable way to make it happen?

**Comment by Ekopalypse** [comment]
It looks to me that it only affects the rename current tab dialog

To reproduce
1. open npp and another application ( I used firefox)
2. open a new tab
3. right-click on tab and chose Rename

![image](https://user-images.githubusercontent.com/47723516/67385779-434ab080-f583-11e9-8d82-f469e1c13bc7.png)

keep this dialog open
4. press alt+tab and switch to firefox
5. press alt+tab and switch to npp
6. press alt+tab again -> npp icon is gone.

All other dialogs I tested seem to be ok.
open/save file dialog
shortcut mapper dialog
goto dialog
udl dialog
find dialog
preferences dialog
style configurator dialog
windows dialog
summary dialog
commandline dialog
debug info dialog
about dialog

**Comment by PalashBansal** [comment]
> I cannot reproduce it at all.
> Any stable way to make it happen?

Hi @donho ,
Can you please try to simulate steps in similar configuration mentioned below in bold (latest NPP in Win7)-
**Notepad++ v7.8 (64-bit)
Build time : Oct 7 2019 - 00:55:55**
Path : C:\Program Files\Notepad++\notepad++.exe
**Admin mode : OFF
Local Conf mode : OFF
OS Name : Windows 7** Professional **(64-bit)**
OS Build : 7601.23833
Plugins : mimeTools.dll NppConverter.dll NppExport.dll **(No extra plugins)**

Steps to reproduce-
1. Start NPP and double click to create new tab (automatically named by NPP as "new 1")
2. Right click this tab and select option "rename", to open NPP's rename floating dialog, as shown in image attached-
![image](https://user-images.githubusercontent.com/6822117/67385736-46f52c00-f5b1-11e9-9dfb-edee2cd60104.png)
3. Press shortcut Alt+Tab to find NPP icon missing.
4. If upto step 3 doesn't reproduce the issue, as Ekopalypse mentioned in above comment-
switch to another running application by using alt+tab
switch back to npp using alt+tab
press alt+tab again -> Npp icon is gone.

@Ekopalypse Can you please mention Debug info from your end, as its sporadically reproducible at your side.
@ashleedawg
https://github.com/notepad-plus-plus/notepad-plus-plus/issues/6223#issuecomment-543391685
As this issue first seen by you, would you like to add something, like steps followed or Debug info., to help reproducing this issue.
I don't have access to my win7 system right now. Will add more details in few hours.

**Comment by PalashBansal** [comment]
> It looks to me that it only affects the rename current tab dialog
> 
> To reproduce
> 
> 1. open npp and another application ( I used firefox)
> 2. open a new tab
> 3. right-click on tab and chose Rename
> 
> ![image](https://user-images.githubusercontent.com/47723516/67385779-434ab080-f583-11e9-8d82-f469e1c13bc7.png)
> 
> keep this dialog open
> 4. press alt+tab and switch to firefox
> 5. press alt+tab and switch to npp
> 6. press alt+tab again -> npp icon is gone.
> 
> All other dialogs I tested seem to be ok.
> open/save file dialog
> shortcut mapper dialog
> goto dialog
> udl dialog
> find dialog
> preferences dialog
> style configurator dialog
> windows dialog
> summary dialog
> commandline dialog
> debug info dialog
> about dialog
> 
> UPDATE:
> when there are two instances of npp running, then it happens even after pressing alt+tab twice.
> 
> DEBUG INFO:
> Notepad++ v7.8.1 (64-bit)
> Build time : Oct 19 2019 - 14:31:15
> Path : D:\PortableApps\Npp\notepad++.exe
> Admin mode : OFF
> Local Conf mode : ON
> OS Name : Windows 7 Professional (64-bit)
> OS Build : 7601.23934
> Plugins : ...



@Ekopalypse 
Can you try the same in this "Close All" dialog-
![image](https://user-images.githubusercontent.com/6822117/67386906-72791600-f5b3-11e9-96d6-257c187d40b6.png)

**Comment by Ekopalypse** [comment]
Yes, this dialog has the same issue as the rename dialog.

**Comment by donho** [comment]
@Ekopalypse @PalashBansal 
So only on Windows 7 ?

**Comment by PalashBansal** [comment]
> @Ekopalypse @PalashBansal
> So only on Windows 7 ?

Yes, till now, it looks like only in Win7
sasumner and I tried in Win10 but works fine.
But I am not able to find any documentation from microsoft reporting the same.
https://docs.microsoft.com/en-us/windows/win32/winmsg/extended-window-styles
In this link too, they mention the issue, but not saying that its specific to Win7
