### ISSUE TITLE
Contributors link in readme is broken.

### ISSUE THREAD

**Issue by Mithil467** [notepad-plus-plus/notepad-plus-plus#6246]
The link at the bottom of readme is broken. I have created a PR with fixed readme. https://github.com/notepad-plus-plus/notepad-plus-plus/pull/6245

Is it okay?

**Comment by Mithil467** [comment]
The pull request was merged. Thanks!

**Comment by sasumner** [comment]
@Mithil467 Technically, the developer merging the PR will also close the issue.

**Comment by Mithil467** [comment]
Oh! Sorry I didn't know that.
