### ISSUE TITLE
Notepad++ 7.8 regression - Issue when used as Notepad replacement

### ISSUE THREAD

**Issue by smz** [notepad-plus-plus/notepad-plus-plus#6253]
### Description of the Issue

Under Windows 10, having Notepad++ 7.8 configured as a replacement for Notepad (as suggested in https://npp-user-manual.org/docs/other-resources/#notepad-replacement), when double-clicking on a file in Windows Explorer, all files in the folder are opened, not just the double-clicked one.

Besides, any file in the folder having a blank-separated name is "exploded" in each of its blank-separated name components and Notepad++ tries to open those too (_which do not exists..._).

Everything is OK when reverting to version 7.7.1 (_and the problem appears again if upgrading again to 7.8_)

### Steps to Reproduce the Issue

1. Under Windows 10, install Notepad++ 7.8
2. Configure it as Notepad replacement as suggested in https://npp-user-manual.org/docs/other-resources/#notepad-replacement
3. Use Windows Explorer to navigate to a directory containing a couple of file (of which at least one with .txt extension)
4. Double click on a .txt file
5. See which files are opened

Note: be sure that .txt files are associated to Notepad (_as by default_) and not to Notepad++ as the problem seems to be related to the usage of Notepad++ as a Notepad replacement.

### Expected Behavior

Just open the "double-clicked" file
### Actual Behavior

All files in the folder are opened
### Debug Information

n/a

**Comment by xylographe** [comment]
Supposedly fixed in commit c16f7bbc1e59e86b4d7650f63a10b8fe47fdaac0.

**Comment by smz** [comment]
Thank-you @xylographe , I'm sorry, I missed #6211 and #6215 ...

Any idea about when a Windows 64bit binary comprising this fix will be available?

Closing this as a duplicate of #6211

**Comment by xylographe** [comment]
The latest build is available from [appveyor](https://ci.appveyor.com/project/donho/notepad-plus-plus). Select _Release/x64_ , followed by _artifacts_.  Replace `Notepad++.exe` only (not `SciLexer.dll`).

**Comment by smz** [comment]
Thanks again @xylographe !
