### ISSUE TITLE
There is a typo in README

### ISSUE THREAD

**Issue by Mithil467** [notepad-plus-plus/notepad-plus-plus#6255]
I have submitted a fix in https://github.com/notepad-plus-plus/notepad-plus-plus/pull/6254

**Comment by rddim** [comment]
Could you add `../../releases/latest` to the `[![GitHub release](https://img.shields.io/github/release/notepad-plus-plus/notepad-plus-plus.svg)]()` i.e. it must be `[![GitHub release](https://img.shields.io/github/release/notepad-plus-plus/notepad-plus-plus.svg)](../../releases/latest)`? This is needed when you click on the `release vX.X` badge - now it's open a `404` error page. With this fix it will open the latest release page.

**Comment by Mithil467** [comment]
Yeah sure, I can do that! So should I create a new PR?

**Comment by rddim** [comment]
Well, in this case, yes, you should close the previous one. In the future there is no need to create separate PR for the same file. Just edit it and it will be automatically updated.

**Comment by Mithil467** [comment]
Oh! But won't that make it 2 commits for this PR? Is it allowed as per the rules? I am very new here.

**Comment by sasumner** [comment]
@Mithil467 For help with that, maybe see https://github.com/todotxt/todo.txt-android/wiki/Squash-All-Commits-Related-to-a-Single-Issue-into-a-Single-Commit

**Comment by Mithil467** [comment]
Oh! @sasumner Thank you! I will follow that from next time.

**Comment by rddim** [comment]
Yes, it will, it is not elegant but I think there is no problem to have 2 commits in one PR. Another way is to `force push` it and check what @sasumner suggest :)

**Comment by rddim** [comment]
@Mithil467 if you are ready to apply the new knowledge you can change the `https://notepad-plus-plus.org/community/` to `https://community.notepad-plus-plus.org/` at line 6 :)

**Comment by Mithil467** [comment]
Okay I will do that too! Thanks

**Comment by Mithil467** [comment]
I think I have managed to do it! Is it okay?
