### ISSUE TITLE
Enhancement Request: syntax higlighting in heredoc for bash

### ISSUE THREAD

**Issue by Eccenux** [notepad-plus-plus/notepad-plus-plus#6266]
### Description of the Issue

Hi. Would it be possible to enable bash syntax highlighting inside heredoc (inside HERE DELIM)?

### Actual Behavior

Currently NPP seem to treat the whole string-script like a big blob of text.

### Expected Behavior

I tend to write dynamic scripts like the one below. And so I would like to have bash syntax highlighting inside the heredoc as well.

```bash
# init
echo "" > maintanance.sh
# settings
echo "dbName=$dbNameParam" >> maintanance.sh
# heredoc:
cat >>maintanance.sh <<'EOC'
    serverName=`hostname`
    echo "Starting maintenance for ${dbname}@${serverName}"
EOC
```

This is something that works in Jenkins syntax highlighter for shell steps. Not sure what they use. Example of how it look below.

![obraz](https://user-images.githubusercontent.com/1045235/67487729-bc730200-f66e-11e9-8588-537a388d7ac4.png)

**Comment by ArkadiuszMichalski** [comment]
@Eccenux Such requirements you should addressed to https://sourceforge.net/p/scintilla/bugs/ for bash lexer.

**Comment by Eccenux** [comment]
OK -> https://sourceforge.net/p/scintilla/feature-requests/1376/
