### ISSUE TITLE
How Can I ReCompile NPP with Other Name to Be Two NPP in My System

### ISSUE THREAD

**Issue by mostafamoeini** [notepad-plus-plus/notepad-plus-plus#6267]
In my system I have one NPP , I need another instance of NPP with other name , other history , other .... and Other Identity ,<br> How Can I do This?

**Comment by ArkadiuszMichalski** [comment]
@mostafamoeini 
You can donwload zip version, unpacked, put empty `doLocalConf.xml` file (if not exist) to unpacked folder and you have portable version. If necessary run notepad++.exe file with `-multiInst` argument. You can have as many different versions as you need, each with its own settings.
If this answer is sufficient, please close the bug.

**Comment by mostafamoeini** [comment]
It works
Thanks.
