### ISSUE TITLE
Bug Report: The Find result window left margin contains characters instead of margin style

### ISSUE THREAD

**Issue by KantorZsolt** [notepad-plus-plus/notepad-plus-plus#6268]
### Description of the Issue
If in the Preferences of Notepad++ you select _None_ for **Folder Margin Style** then in the Find result window (when you do a Find All in Current Document) the left margin contains uppercase characters.

### Steps to Reproduce the Issue
1.  Open any text file or source file with Notepad++
2.  Go to Settings -> Preferences -> Editing
3.  Select None for the Folder Margin Style.
4.  Open the Find dialog.
5.  Do a Find All in Current Document with some characters that can be found in the opened file

### Expected Behavior
The left margin of the Find result window should NOT contain some strange uppercase letters.
It should contain a default margin style even if Folder Margin Style is disabled in the Preferences.

### Actual Behavior
After executing a  (or multiple) "Find All in Current Document" the Find result window left margin contains uppercase characters instead of a default margin style.

### Debug Information
Notepad++ v7.8.1   (64-bit)
Build time : Oct 19 2019 - 14:31:15
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS Name : Windows 7 Home Premium (64-bit) 
OS Build : 7601.24519
Plugins : DSpellCheck.dll NppConverter.dll NppExport.dll 

Check the screenshot below:

![1571665847813-untitled](https://user-images.githubusercontent.com/35799289/67528765-e9e99b00-f6c2-11e9-881f-0821cf5ac9eb.png)

**Comment by sasumner** [comment]
This was also referenced in these threads on the Community: 

- https://community.notepad-plus-plus.org/topic/18589/notepad-v7-8-2-free-uyghur-edition

- https://community.notepad-plus-plus.org/topic/18389/notepad-7-8-1-release-candidate

**Comment by sasumner** [comment]
So when _None_ is selected in the Preferences, the primary and secondary editor windows hide the margin where the fold stuff is displayed.  No such hiding occurs in the `Find result` window; the previous setting in effect when the prior "Find All..." was run remains.  However, after changing to _None_ and running a new "Find All...", now the garbage characters appear.

Perhaps the best thing to do to fix this is to not have this setting affect the `Find result` window.  One of the choices (box?) should just always be in effect for this window.

BTW, in the code I'm not sure how changing the setting affects the `Find result` window anyway; it seems like it should only affect the primary and secondary editor windows.  Anyone else have any ideas on the why/how of this?

**Comment by sasumner** [comment]
A better solution than that posed above may be to follow the user's choice for the fold style characters, but when the user's choice is _None_ then the `Find result` window should use the box style (the normal default fold style).

Hiding the fold margin for the `Find result` window (when _None_ is the user's selection) as is done for normal editor windows is not a great solution because of the auto-collapsing nature of the window when subsequent searches are run.  It is nice to see the search/results hierarchy, and to be able to individually expand/contract the subtrees.
