### ISSUE TITLE
Simple UX Improvement - Recent Files Vertical Alignment

### ISSUE THREAD

**Issue by dsnvwlmnt** [notepad-plus-plus/notepad-plus-plus#6272]
Users who use Recent files extensively will know this pain very well, especially if they have a deep nested structure of folders.

In a long list of recent files, finding the one you want is a giant pain, because the most important part - the filename itself - is not in vertical alignment. Your eyes have to zig-zag instead of quickly scan straight down a list.

Three possible solutions:

1) Put the filename on the left side of the menu, with the folder in brackets (this method is preferred as the folder names align more logically than in 2):
```
1: filename.xyz (C:\foo\bar)
2: filename.123 (D:\bar\foo\bar)
```

2) Right-align the files/folder list instead of the current left-alignment. This way the filenames are all aligned:
```
1: --- C:\foo\bar\filename.xyz
2: D:\bar\foo\bar\filename.123
```

(late edit option # 3) Don't list the containing folder, and put the full path+file in a tooltip (LibreOffice-style):
```
1: filename.xyz
2: filename.123
```

Below is what I'm looking at right now. It's extremely cumbersome and easily improved:

![Untitled](https://user-images.githubusercontent.com/14173022/67607831-b8141b00-f73a-11e9-9b6d-d0fae0c23a9e.png)

**Comment by sasumner** [comment]
I have always simply been glad that I can find a file on the Recent Files list.  

But with the goal of making things better: I rather like the idea advanced by option 1.

**Comment by MAPJe71** [comment]
However, there will always be combinations that have your eyes go zig-zag i.e. it will never be ideal for everyone.

Option 1
```
1: otherfilename.xyz (C:\foo\bar)
2: filename.otherextension (D:\bar\foo\bar)
```
Option 2:
```
1: --------- C:\foo\bar\otherfilename.xyz
2: D:\bar\foo\bar\filename.otherextension
```
Option 3:
```
1: otherfilename.xyz
2: filename.otherextension
```

**Comment by dsnvwlmnt** [comment]
> However, there will always be combinations that have your eyes go zig-zag i.e. it will never be ideal for everyone.

It's a matter of aligning to what 99% of users care about. I suppose there are 3 ways to align things:

1. drive name (current behavior)
2. file name (suggested behavior)
3. file extension (right-aligned)

1. I can't imagine many people primarily care about aligning to drive name, but correct me if I'm wrong. It's the current behavior in np++, but I imagine it was developed this way as an afterthought and never looked at again.

2. File name is the most salient descriptor when you are scanning a list for... a file name.

3. I can't imagine a use case for file extension alignment. And even if there were, it would surely be an extreme minority.

**Comment by sasumner** [comment]
I reiterate:  Option 1 is the best option. :-)

**Comment by acsanyi** [comment]
How would this work when the user chooses a custom maximum length? Would that max length apply to just the path, or the full string (path + filename)?

BTW Option 3 already exists by changing a setting: Settings > Preferences, Recent Files History, "Only File Name".

**Comment by dsnvwlmnt** [comment]
> How would this work when the user chooses a custom maximum length? Would that max length apply to just the path, or the full string (path + filename)?

Presumably full string as usual.

> BTW Option 3 already exists by changing a setting: Settings > Preferences, Recent Files History, "Only File Name". (Edit: except for the tooltip part.)

Oh neat. Not useful in my case though, as files can have the same name but be in different folders. Tooltip would solve that.

**Comment by donho** [comment]
Find files in the recent opened files list is not an operation that user executes all the time, and I don't have any problem to find what I need.
Anyway, the recent opened files should contains its full path, and even option 1 makes string length longer.
This feature won't be implemented, sorry.

**Comment by dsnvwlmnt** [comment]
Why close this issue? The issue isn't resolved. The PR that someone helpfully provided might not have been the optimal solution, but that's unrelated to this issue. A short cleaner version than what exists was already proposed in the OP. LibreOffice style.

**Comment by sasumner** [comment]
>Why close this issue? The issue isn't resolved

Not all "improvement" issues are deemed appropriate changes for the software.
Opening an issue is not a guarantee that something in the software will change.

I don't like the "wontfix" label.
It implies that something was wrong to start with.
Something like "will not be implemented" would be better.

**Comment by sasumner** [comment]
@dsnvwlmnt Also see my comment here: https://github.com/notepad-plus-plus/notepad-plus-plus/pull/8136#issuecomment-646281344
