### ISSUE TITLE
Plugin causes notepad++.exe process remains  NPPN_SHUTDOWN aka `DLL_PROCESS_DETACH` is culprit here

### ISSUE THREAD

**Issue by gurikbal** [notepad-plus-plus/notepad-plus-plus#6275]
Plugin causes notepad++.exe process remains  NPPN_SHUTDOWN aka `DLL_PROCESS_DETACH` is culprit here

[`https://github.com/sieukrem/jn-npp-plugin/pull/80`](https://github.com/sieukrem/jn-npp-plugin/pull/80)

[`https://github.com/notepad-plus-plus/notepad-plus-plus/issues/4062`](https://github.com/notepad-plus-plus/notepad-plus-plus/issues/4062)

[`https://github.com/peter-frentrup/NppMenuSearch/issues/13`](https://github.com/peter-frentrup/NppMenuSearch/issues/13)

[`https://github.com/skycc86/npp_binhex_plugin/issues/5`](https://github.com/skycc86/npp_binhex_plugin/issues/5)

**Comment by sasumner** [comment]
Make your issue make sense.  And follow the template for issue submission.
