### ISSUE TITLE
Multi line edit and Multi point edit Doesn't allow to edit new lines characters (no deletion and nor insertion)

### ISSUE THREAD

**Issue by wonkawilly** [notepad-plus-plus/notepad-plus-plus#6276]
Hi @donho 

Version 758, 32bit
### Description of the Issue
As known sometimes using notepad++ there is the need to edit a file in multiple points simultaneously with the Multi line edit or Column edit (with the use of Alt +Shift + up arrow / down arrow) and / or the Multi point edit (using Ctrl + left mouse click) in multiple points of the text. This feature is awesome and really useful. Unfortunately it seems kinda of "incomplete".

In fact the issue in these situations is that you cannot insert nor delete new line  / new paragraph chars simultaneously in all caret / insertion points.
(No problems for tabulations that work great)

See the following animated png file for clarifications:

![animated](https://user-images.githubusercontent.com/34818345/67625880-6e175c00-f844-11e9-9cff-87b0d73fb844.png)

I don't know if it is an unwanted bug, or just a wanted limitation of notepad++.
###Question:
Anyway is there any possibility to implement such a function to achieve the possibility to edit multiple new line chars in the same time as any other char?

Thanks in advance.

**Comment by sasumner** [comment]
The Scintilla component demo editor works the same way Notepad++ does in this regard.  I'd say unless someone wants to pursue Scintilla changes for this functionality, for Notepad++ it is a dead issue.

**Comment by wonkawilly** [comment]
> The Scintilla component demo editor works the same way Notepad++ does in this regard. I'd say unless someone wants to pursue Scintilla changes for this functionality, for Notepad++ it is a dead issue.

Is there any possibility to update the scintilla component?

**Comment by sasumner** [comment]
>Is there any possibility to update the scintilla component?

Yes, you can open a Scintilla issue if you'd like.  See https://sourceforge.net/p/scintilla/feature-requests/
