### ISSUE TITLE
Politics should not invade the technology world.

### ISSUE THREAD

**Issue by alexinea** [notepad-plus-plus/notepad-plus-plus#6288]
Https://notepad-plus-plus.org/news/v781-free-uyghur-edition/ Is this a fake news?

The news about China’s persecution of Uighurs is a lie fabricated by news media organizations such as the BBC and CNN. If you have not gone to China to experience it yourself, you will use the hearsay as a conclusion. This is a paralysis of human freedom and democracy. Xinjiang is facing the threat of terrorism. Is it your support for these terrorism? Xinjiang has made a lot of efforts to protect people from terrorism. Do you not support the people to stay away from the threat of life-threatening? Combating terrorism means safeguarding human rights.

As an excellent software in the technical field, you should not touch topics that are politically incorrect. Can you publish racist remarks in the United States? Can you praise the Nazis in Germany?

Politics should not invade the technology world.

I am very disappointed that you take false things as facts.

**Comment by xingwen1987** [comment]
f you do this, you will only get one result, that is, it will be disabled. Just like the one in the glory of the king said: You are broken!

**Comment by fengmiaosen** [comment]
If you don't know the facts yourself, it's best to concentrate on technology development, don't bother yourself.

**Comment by GirlKiller512** [comment]
Do not play with fire.

**Comment by the-f-word-to-you** [comment]
Don't we remember the CIA had hacked this shitty software?

TYI: https://notepad-plus-plus.org/downloads/v7.3.3/

**Comment by 0xNi** [comment]
Well, the authour has done things like this many times. However he didn't keep the opinion in his website all the time, otherwise we will see and don't use this software, then we won't feel like eating shit at this time.

**Comment by dartraiden** [comment]
Well, what about other similar releases?
https://notepad-plus-plus.org/downloads/v6.7.4/
https://notepad-plus-plus.org/downloads/v7.6.2/

**Comment by OmgImAlexis** [comment]
If you don’t like it then good bye. You won’t be missed. 👋

**Comment by alexinea** [comment]
> 
> 
> If you don’t like it then good bye. You won’t be missed. 👋

Freedom of speech is based on political correctness and democratic morality. Contamination and defamation are against human fairness and justice. This has nothing to do with likes or dislikes.

Freedom of speech does not mean anything can be said.

**Comment by alexinea** [comment]
Hey, you still have a lot to learn. Staying away from the BBC and CNN is good for maintaining ethical quality and wisdom.

**Comment by OmgImAlexis** [comment]
I don't need to watch either of those to know what's happening over there. It's kinda sad that you're trying to spread false information when the rest of the world already knows what's going on.

**Comment by alexinea** [comment]
Your passage is really interesting. When you treat false things as real, you will treat the real things as jokes.

People living in Xinjiang personally experience that human rights are protected and their personality is respected, but there are always people who think they are God messengers, destroy the peace of Xinjiang, and spread the rumors of Xinjiang.

Have you been to Xinjiang? Have you been to China? I tell you, I have been there. So what you can see is fake. The news you see is fake news made by humans. The photos you see are all posing by models.

**Comment by alexinea** [comment]
The most important thing is that notepad++ is not easy to use. ╮(￣▽￣")╭

The author of Notepad++ should read more books, work hard, and don't participate in political topics, especially the intrigues that attempt to split Taiwan from China.

Uninstall Notepad++ and use editplus, makes your work more efficient.

**Comment by aihacker** [comment]
洪水攻击这个站点，制造虚假消息，引起群愤
>ping notepad-plus-plus.org
正在 Ping notepad-plus-plus.org [2.57.89.199] 具有 32 字节的数据:
来自 2.57.89.199 的回复: 字节=32 时间=233ms TTL=49
来自 2.57.89.199 的回复: 字节=32 时间=232ms TTL=49
来自 2.57.89.199 的回复: 字节=32 时间=234ms TTL=49
来自 2.57.89.199 的回复: 字节=32 时间=233ms TTL=49

**Comment by aihacker** [comment]
ping -l 1000 -t notepad-plus-plus.org

**Comment by aihacker** [comment]
![image](https://user-images.githubusercontent.com/9352084/67848059-f0529980-fb3e-11e9-9b42-6661e3c50bd6.png)

**Comment by alexinea** [comment]
> 
> 
> Your passage is really interesting. When you treat false things as real, you will treat the real things as jokes.
> 
> People living in Xinjiang personally experience that human rights are protected and their personality is respected, but there are always people who think they are God messengers, destroy the peace of Xinjiang, and spread the rumors of Xinjiang.
> 
> Have you been to Xinjiang? Have you been to China? I tell you, I have been there. So what you see is fake. The news you see is fake news made by humans. The photos you see are all posing by models.

We should fight for freedom. So what is freedom? That is to freely make our lives better. So we should do something practical, not too much opposition or criticism. The purpose of opposition and criticism is to let everyone sit down to negotiate or discuss and solve the problem. The problem is that everyone has no idea to solve the problem now. Do you think that "opposing" or "criticizing" is equivalent to "participating in politics"?

There is nothing to discuss, many people's eyes are too short, so that they do not know what happened in this world. Both naively believe that the BBC and CNN report the news objectively and neutrally... In fact, most of the BBC and CNN news is more objective, but not all... especially about China.

I will close this issue and I look forward to world peace.

**Comment by alexinea** [comment]
When people believe that the news of the BBC and CNN is absolutely objective and neutral, they may not know that the BBC and CNN (and other news companies) reports on China's Xinjiang are falsely fabricated. The makers of these fake news have never been to Xinjiang. The fact that people living and working in Xinjiang say about Xinjiang is not believed by these Westerners. Why is this happening?

When we discuss freedom of speech, many people do not allow us to tell the truth. Facebook forbids the Hong Kong police to tell the truth through facebook. They have deleted the accounts of thousands of people who tell the truth because they want everyone to take fake news seriously. Because many people have not been to Hong Kong, they do not know what happened in Hong Kong. They have no way to verify whether the things in the news are true or not. Hong Kong is too far away from them, and Xinjiang is too far away from them. The chaos in Hong Kong and Xinjiang will not affect their tea time, because for them, the chaos that happened in Xinjiang and Hong Kong is just one news.

But for the Chinese, Xinjiang and Hong Kong are their hometowns and their homeland. It is the place where their brothers or sisters lived and where they worked. They don't want to see fake news. They want to tell everyone what is happening there.

So do you believe in the BBC’s news reports, or do you believe in the people living and working in Xinjiang?

What are you afraid of those who give me "👎"? What are you worried about? What do you want to happen in Xinjiang? What can you bring to the Uighurs in Xinjiang? The friends in Xinjiang around me told me that I saw what I said in the issue. They said that "the Xinjiang Uygur people live better than the Han people." This is the truth.

This is the truth.

This is the last time I replied to this issue.

After the WWII, the German people discovered that the Nazi Party, which was blindly trusted, was so evil. I believe that after a few years, everyone will see a real Xinjiang.

**Comment by va1erian** [comment]
shut the fuck up already, you have the balls to lecture us about the state of western media and "fake news" when literally all of your news, social media and your whole internet access are directly vetted and controlled by the CCP with zero accountability. Remember when github was blocked in  china? Wasn't that cool?

**Comment by alexinea** [comment]
Every country has a regulation of the Internet. Remember the Prism Project and Snowden?

So...

When I saw you saying "shut the fuck up already", I thought of a joke: "We are discussing freedom of speech, please shut up."

**Comment by Loys** [comment]
Dear @alexinea i invite you to read more books, because "reading 100+ books per year for fun" is obviously not enough, or instead of "reading for fun", try to read them like "more seriously".
You are not talking about "China", you are talking about People's republic of China.
Be honest, and stop calling PRC "China" !
China belongs to Chinese people and their ancestry, China doesn't belong to a corrupt communist party led by a fat buffoon ! 
Open an history book for a change, and find out about what you are calling "China".

**Comment by alexinea** [comment]
Obviously, Western countries and interest groups have made great achievements in public opinion and psychological warfare.

So many people are blinded by rumors. Obviously, at this moment, they don't understand what happened in the real world. The church burned Copernicus. And today there are still so many people who don't understand why human beings exist. This is the failure of democracy.

**Comment by hollerith** [comment]
六四天安門事件

**Comment by Loys** [comment]
![30D69500-4219-4CA4-A133-1C3190763D4A](https://user-images.githubusercontent.com/243663/68130926-82321c00-ff1c-11e9-9bce-2a85f81ee3eb.jpg)

This person on the right, is the award-winning photojournalist Lu Guang 卢广 and he is gone missing since Nov. 3 2018, he was traveling and doing his work (photo reporter) in Xinjiang province.
More on this here : https://www.voanews.com/east-asia-pacific/chinese-photographer-missing-trip-xinjiang
https://en.wikipedia.org/wiki/Lu_Guang_(photographer)
So, everything sounds just fine in Xinjiang !

**Comment by alexinea** [comment]
First of all, I have to warn @hollerith, don't confuse politics and technology. Don't try to mix political things into the technology world. Whether you are from mainland China, Hong Kong, China or Taiwan, China, please don't discuss politics in the technical community.

---

The Tiananmen incident was planned by the US Central Intelligence Agency through NED and aims to undermine peace and stability in Chinese society.

It is the same as the "disintegration of the Soviet Union, the drastic changes in Eastern Europe" that occurred in the early twentieth century, and the "color revolution" and "Arab Spring" that occurred in the 21st century. It is the US government's attempt to destroy a country to satisfy the interests of the United States itself. .

Up to now, no matter whether it is an Eastern European country split from the Soviet Union or a country with a color revolution or the "Arab Spring", without exception, it has become a failed country. The living standards and quality of the people in these countries are much lower than those in the West.

Fortunately, these huge changes have not taken place in China. This is the luck of those Chinese people. God is with the Chinese people.

**Comment by jianxuanbing** [comment]
老汪也过来A一下

**Comment by Loys** [comment]
@alexinea So how if we want to mix politics and technology? We must ask your permission? 😂
When you are saying "The Tiananmen incident was planned by the CIA" are you not mixing politics and technology? You are just repeating the great Chinese Communist gospel.
Anyway, we get it, now you just became an annoying loser :  Repeating the same conspiracy stuff without listening. You should read more books !  😂

**Comment by alexinea** [comment]
Hi, @Loys 

The best way is to not challenge GitHub's community rules. Isn't it?

What I want to emphasize is (and you should also notice), not to mix politics and technology. You should not ask if I should get my permission, but should follow the freedom of speech while complying with the GitHub community rules.

The author of Notepad++ has the freedom to make political speech, but he should not express his opinion on the official Notepad++ website because the website involves the technical field.

I am telling a history that has already happened, not a political party or a country.

I found that you are trying to confuse my point of view and forcibly associate me with the CCP.

As for what you said, "Read more books," I think that a knowledgeable person will not say such things.

**Comment by Loys** [comment]
Hello @alexinea 😄

> The best way is to not challenge GitHub's community rules. Isn't it?

Sure !

> What I want to emphasize is (and you should also notice), not to mix politics and technology. 

Yeah, we get that, it applies for us, but not for you, hey? 

> You should not ask if I should get my permission, but should follow the freedom of speech while complying with the GitHub community rules.

I didn't ask if you should get your permission, but why not ! 
Please acknowledge us why you should get your permission before commenting on CIA and Tiananmen ? Who are "you"? Are you several persons?

> The author of Notepad++ has the freedom to make political speech, but he should not express his opinion on the official Notepad++ website because the website involves the technical field.

Yeah, we get that : You are not amused by this. Alright then !

> I am telling a history that has already happened, not the praise of a political party or country.

Ah yes? Just by quoting "The friends in Xinjiang around" ? Who are those "friends"? and why they are telling you that "the Xinjiang Uygur people live better than the Han people."? Are they really friends of yours?

> I found that you are trying to confuse my point of view and forcibly associate me with the CCP.

Yep you are right ! And it is very obvious.

> As for what you said, "Read more books," I think that a knowledgeable person will not say such things.

An knowledgeable person won't brag about "reading 100+" books a year ! 😂

**Comment by alexinea** [comment]
Well, @Loys 😋

I am very glad that we can discuss this topic calmly.

“Reading more than 100 books a year” has nothing to do with this discussion. I think this is a personal attack. In fact, there are still many people who can do "read more than 100 books a year."

The "friends in Xinjiang" I am talking about are friends living in Xinjiang, including friends of the Han nationality and friends of the Uyghurs. In fact, I have also been to Xinjiang (tourism). What happened in Xinjiang is totally different from what is reported in the news report.

I don't want to praise anything, I just want to say that some things are totally different from the news. This is my own comparison. No one has given me the benefit to let me say this. I also believe that your thinking is independent. This is a good discussion, but obviously, we can go to twitter to discuss this, not on GitHub.

As for what you said "need to obtain permission", did you find that you made a mistake in understanding my point of view? I am talking about "Politics should not invade the technology world.", not "need to get my permission."

We should discuss "political can not invade the technological world", not "need to obtain permission." We should keep the technical community pure, do you think the chaotic technology community is better?

**Comment by Loys** [comment]
> I am very glad that we can discuss this topic calmly.

Sure thing @alexinea ! Me either 😄

> “Reading more than 100 books a year” has nothing to do with this discussion. 

Alright ! You closed it, then.

> The "friends in Xinjiang" I am talking about are friends living in Xinjiang, including friends of the Han nationality and friends of the Uyghurs. Of course, they are all my friends, not just working relationships. In fact, I have also been to Xinjiang (tourism). What happened in Xinjiang is totally different from what is reported in the news report.

Ok, so now, you do have friends in the Uyghurs and the Han community, living in Xinjiang.
I am guessing, when you've been to Xinjiang for tourism, you visited them, because they are real friend and not working relationships. If it is true, it is an interesting fact. May i ask : 
- When did you enter Xinjiang territory, last time? 
- How did you get there? 
- Also, are you in mainland China right now? 
- If so, how can you be able to read GitHub and Twitter?
Please, don't worry, our discussion will be back on the technology track really soon.

> As for what you said "need to obtain permission", did you find that you made a mistake in understanding my point of view? I am talking about "Politics should not invade the technology world.", not "need to get my permission."

When you are saying that "The news about China’s persecution of Uighurs is a lie fabricated by news media organizations such as the BBC and CNN. " you are making a political statement, because you are not proving anything : It is just related on what you are declaring ("persecutions = fake news"). And what is funny is, after (and before) this statement, you are saying that "Politics should not invade the technology world". Can't you spot the paradox? 

> We should discuss "political can not invade the technological world", not "need to obtain permission." We should keep the technical community pure, do you think the chaotic technology community is better?

So, you are assuming that making political statements in the 'technical community" can be "chaotic" but, again, how is your "persecutions = fake news" statements? Is it not political? Because of your friends you visited, during holidays in Xinjiang? It is quite confusing : Please explain your point.

**Comment by Glandos** [comment]
@alexinea Good news. It's also the statement from everyone now: https://www.icij.org/investigations/china-cables/exposed-chinas-operating-manuals-for-mass-internment-and-arrest-by-algorithm/

**Comment by alexinea** [comment]
@Glandos So, I am very curious that the author of this news report has been to Xinjiang? How to prove that this article does not have political bias itself? When we are not sure whether the author of the article has some prejudice to please some readers, then we need to keep a distance from these news reports. They cannot be easily believed or easily denied.

I don't believe it easily with state-controlled media and capital-controlled media. In the eyes of many people, India is a backward country. They do not know that India is the most populous democracy in the world. There are also many people who cannot tell you the names of at least five Indian states (they can't tell you the names of at least five Chinese provinces), including those reporters.

By the way, will you write and speak Chinese? Can you read the Chinese in that document yourself? I heard that the British occupied the Chagos Islands in Mauritius. I wonder if you heard about this news?

**Comment by Loys** [comment]
> I don't believe it easily with state-controlled media and capital-controlled media. 
Hi @alexinea ! I am still hoping you respond (in good faith) to my previous message 😉.

For your acknowledgment :
@Glandos was referring to a article written by a reporter member of a non profit organization (ICIJ) so that's not a state-controlled or capital-controlled media. 

If you are interesting on what's going on lately in the Chinese world, can do a search on using the words : "China Cables".
Also, you may read some encouraging news from Hong-Kong, and a interesting story about a defected mainland spy in Canberra (please read the part about Taiwan elections).

**Comment by Glandos** [comment]
This will be my final statement here.

I'm sorry for you @alexinea but you don't get my point. Everyone knows that we can't exactly know what's happening in this area, but everyone knows that something is wrong. You are free to say otherwise.

Political and technical/technological/software can be mixed. That is exactly the point of the GPL, which give back some rights to users, that were otherwise denied to them by the political power. Mixing them has been extensively discussed, from one's point of view to the others, but nonetheless, it happens everywhere. And the least we can do, is asking the question whether there is any valid reason to avoid mixing them.

If you want to convince someone, don't talk about India, Mauritius, or faith in the media we are all using. You should provide personal stories or written stories (whatever the language) about this area and these people.

In the end, ICIJ is well known organization, that did many useful reports in the past that helped every citizens to be aware of what their governments or some companies did to them.

And, by the way, have a nice day :)

**Comment by frankli0324** [comment]
ironic.

**Comment by duangsuse** [comment]
https://github.com/notepad-plus-plus/notepad-plus-plus/pull/8104

**Comment by Hanzalah-Adalan** [comment]
@alexinea you might be a very technical person and I respect you for that.. but as a human you are still very pathetic, still blind, still associating Islam with terrorism directly.. there are 2+ billion muslim all over the globe.. terrorism has nothing to do with religion.. don't be arrogat, no one can escape death.. you will face the judgement of Allah (The One and only true God) in the hereafter.. I see you read a lot every year, please read books about Islam by muslim writers or at least by natural writters, not by evil orientalist

**Comment by mominbin** [comment]
很奇怪那些玩git的美国傻佬这么没逻辑, 圣母心还是留给自己的国家吧, 和弗洛伊德同在!

**Comment by Loys** [comment]
![EfisYEPWAAk0FH5](https://user-images.githubusercontent.com/243663/90512466-80a9ab80-e15e-11ea-86d1-66ce2b603fe9.png)

LOL 😂 such a great party, such a great leader ! 🤣
