### ISSUE TITLE
I guess the author hasn't been to Xinjiang, even China. Why don't you help the countries persecuted by western world like Syria, Afghanistan, Iran? Hilarious.

### ISSUE THREAD

**Issue by 0xNi** [notepad-plus-plus/notepad-plus-plus#6291]
We live good, however the western media always tell to the world that chinese live in hell. 

`demoncracy from west = joke`

**Comment by OkazakiNagisa** [comment]
Exactly.

**Comment by mp5088643** [comment]
As a Chinese living in Xinjiang, I think the author is stupid. Prepare to uninstall Notepad + +. The so-called human rights of Uighurs are basically the same as those of Tibet, which are privately funded by the CIA. It is suggested to read the historical documents of the CIA.

**Comment by cnkei** [comment]
"This is extremely dangerous to our democracy."

**Comment by GTOL** [comment]
"This is extremely dangerous to our democracy."
