### ISSUE TITLE
好好讨论，理性分析，不吵架不骂人

### ISSUE THREAD

**Issue by ccdarkness** [notepad-plus-plus/notepad-plus-plus#6298]
作者文章里说的数十万人被关押什么的，请拿出证据来

我不要你以为，也不要我以为，拿出证据说清楚

你有你的言论自由，但是不应该散播谣言或者未经证实的事情

**Comment by 0xNi** [comment]
我猜是NED NDI给他们拿钱了

**Comment by ccdarkness** [comment]
作者是有正义感的人，看了这么多人被迫害觉得需要人站出来，但他可能是假新闻的受害者，国外各社媒平台fake news那么多不能辨别也是正常的，而且是从小熏陶长大的，说我们被洗脑，他们又何尝不是呢。只是请要学会独立思考，辨证的看问题，或者自己来一趟中国看看吧

**Comment by Niinor** [comment]
没有调查，就没有发言权。还请作者发起众筹，我们可以集资给他，让他来中国，去新疆看看。另外，要评价一件事情，需要从多方面了解，兼听则明，偏信则暗。
强烈要求作者撤回这个版本。

**Comment by ftfuntjh** [comment]
弯弯要征服世界了，笑死我了。

**Comment by LongQue** [comment]
忘了说，作者是台独

**Comment by ccdarkness** [comment]
现在真正被迫害的是叙利亚、伊朗、阿富汗等国家地区，看看哪些照片和视频吧，西方媒体又是怎么样宣传的呢？恐怖组织吗？到底谁才是恐怖组织呢？谁发起的战争，谁发射的导弹，谁派的部队，主持正义就是要去打那些不听话的人？

**Comment by ftfuntjh** [comment]
理性分析，请作者post照片，视频证据。

**Comment by 0xNi** [comment]
建议楼主网上搜一下侯今吾，看看他多次发表的言论是不是针对中国。他的正义感怎么不关注越南战争、伊拉克战争、叙利亚战争？怎么不关注被美国民主洗礼的阿拉伯之春，乌克兰，阿根廷？甚至连乌干达儿童也不关心

**Comment by penghubingzhou** [comment]
> 作者是有正义感的人，看了这么多人被迫害觉得需要人站出来，但他可能是假新闻的受害者，国外各社媒平台fake news那么多不能辨别也是正常的，而且是从小熏陶长大的，说我们被洗脑，他们又何尝不是呢。只是请要学会独立思考，辨证的看问题，或者自己来一趟中国看看吧

放他妈的屁，他就是个彻头彻尾的台独分子，跟他商量个屁！！！

**Comment by iamtangxin** [comment]
作者的思想有点极端，2008 年还有个版本扬言要抵制北京奥运会，大家可能忘记了。

**Comment by Flyinbird** [comment]
看到咱中国人能够理性看待问题，深感欣慰。我发现咱们要跟墙外那些讲汉文的人讲道理时根本讲不通，我们说以理服人，拿事实说话，他们似乎完全不知道我们在说什么。。

**Comment by oTMaN-chengQ-G** [comment]
作者写的软件真的不错.
可惜太仇共仇中,而我又是个中国人,无奈弃之.

**Comment by ckhung** [comment]
[新疆受害者资料库](https://shahit.biz/cmn/)
