### ISSUE TITLE
Batch syntax highlighting doesn't work properly with modifiers

### ISSUE THREAD

**Issue by riQQ** [notepad-plus-plus/notepad-plus-plus#63]
Example: Only %~dp0 should be highlighted instead of %~dp09
![Bash syntax highlighting](https://cloud.githubusercontent.com/assets/3404787/7617791/e01caa48-f9ad-11e4-8097-fc51693ea7fb.png)

**Comment by MAPJe71** [comment]
I guess this is an issue of the lexer i.e. Scintilla.

**Comment by ogerovich** [comment]
Another example is string replacement:
%test/path:/=\%

I would expect the whole thing to be highlighted. Special characters between %% seem to be causing the problem.

**Comment by MetaChuh** [comment]
verified but closed due to inactivity

**Comment by ogerovich** [comment]
This is still an issue in N++ 7.5.9. Both of these do not highlight (seems like due to /):
%test/path:/=%
%test/%

**Comment by ArkadiuszMichalski** [comment]
Fixed by https://github.com/notepad-plus-plus/notepad-plus-plus/commit/a61b03ea8887e21c6e1b7374068962f635b79b80.
