### ISSUE TITLE
Active tab selection

### ISSUE THREAD

**Issue by oop** [notepad-plus-plus/notepad-plus-plus#630]
Hi!

I'm scrolling but it is not working and crashing. Please watch this GIF for understand issue.

![Image of Issue](http://i.gyazo.com/2cdf3b5ee96a4164feac69c75346e451.gif)

**Comment by donho** [comment]
Your Notepad++ version please?

**Comment by RuMad1** [comment]
Last version.

**Comment by donho** [comment]
Version number please?

**Comment by RuMad1** [comment]
Sorry for late reply. I'm using Windows 10 and this is my notepad++ version:
![Image of NP++ Version](http://i.gyazo.com/6233647c8676de1d8cb7dc420dba30e7.png)

**Comment by donho** [comment]
I believe this issue has been fixed since long time ago.
Update your Notepad++ to the latest version (v7.6.6).
If the issue persists, please create a new issue for it.
Thank you.
