### ISSUE TITLE
刚刚卸载了，言论是你的自由，但是是绝不允许你胡说八道，麻烦请举证，没证据就别瞎BB

### ISSUE THREAD

**Issue by assad2008** [notepad-plus-plus/notepad-plus-plus#6303]
刚刚卸载了！！
言论是你的自由，但是是绝不允许你胡说八道，麻烦请举证，没证据就别瞎BB。

**Comment by michaellee8** [comment]
https://www.bbc.com/news/topics/cpz1y9ney3mt/uighurs

**Comment by TheWaWaR** [comment]
> https://www.bbc.com/news/topics/cpz1y9ney3mt/uighurs

你不会也信 CNN 吧，笑死了
