### ISSUE TITLE
The Uyghurs are Chinese. Taiwan & Hongkong are also part of China

### ISSUE THREAD

**Issue by AlliamChang** [notepad-plus-plus/notepad-plus-plus#6308]
The Uyghurs are Chinese. Taiwan & Hongkong are also part of China.

**Comment by mp5088643** [comment]
Taiwan writer of mental retardation, frog at the bottom of the well

**Comment by CannibalKush** [comment]
The Tiananmen Square protests, commonly known in mainland China as the June Fourth Incident (Chinese: 六四事件, liùsì shìjiàn, literally six-four incident), were student-led demonstrations held in Tiananmen Square in Beijing during 1989. The popular national movement inspired by the Beijing protests is sometimes called the '89 Democracy Movement (Chinese: 八九民运, bājiǔ mínyùn). The protests started on April 15 and were forcibly suppressed on June 4 when the government declared martial law and sent the military to occupy central parts of Beijing. In what became known as the Tiananmen Square Massacre (Chinese: 天安门大屠杀), troops with assault rifles and tanks fired at the demonstrators and those trying to block the military's advance into Tiananmen Square. Estimates of the death toll vary from several hundred to several thousand, with thousands more wounded.
