### ISSUE TITLE
America is Indians, white people get out of America.

### ISSUE THREAD

**Issue by linchong** [notepad-plus-plus/notepad-plus-plus#6309]
The Uyghurs are Chinese. Taiwan & Hongkong are also part of China.

**Comment by greatbody** [comment]
Free the North America for Indians who is the owner of that land.

**Comment by Kanuveezero** [comment]
why do you think everyone is American, dumbbbbbb

**Comment by DiemenDesign** [comment]
Exactly, you are annoying users in other countries that having nothing to do with your arguments.
