### ISSUE TITLE
已在12377.cn上举报，等着被墙吧

### ISSUE THREAD

**Issue by AriaLyy** [notepad-plus-plus/notepad-plus-plus#6312]
vscode 那么香，我非得要用你？？？？
等着被墙吧，sb玩意

**Comment by nxSlow** [comment]
我都弃用几年了  看群里发的消息才知道这个b卖国

**Comment by AriaLyy** [comment]
这个b本来就是台独，做梦都想着中国分裂出去

**Comment by zj299792458** [comment]
支持GitHub 被墙

**Comment by nxSlow** [comment]
从微软手里收购github才是关键

**Comment by greatbody** [comment]
github不应该墙，不过notepad++怕是要死掉了。毕竟vscode这么好用，而且微软还指望大陆挣钱呢，八成不会在vscode里面做这么2的事情。

**Comment by lhprojects** [comment]
> github不应该墙，不过notepad++怕是要死掉了。毕竟vscode这么好用，而且微软还指望大陆挣钱呢，八成不会在vscode里面做这么2的事情。

有一点专业精神都不会干这么sb的事情。
