### ISSUE TITLE
Find in Project Files

### ISSUE THREAD

**Issue by Cyberchicken** [notepad-plus-plus/notepad-plus-plus#632]
Hello everybody,
this is basically a bump for this last year topic:
https://sourceforge.net/p/notepad-plus/discussion/331753/thread/d5203ff1/

I’m coming from PsPad and I’m missing “find in project” function (while in Pspad I’m missing regex in find in files)

Is there a plan or plugin or workaround for this function in Notepad++?

Thank you very much

**Comment by cmeriaux** [comment]
Hello,
I'm using nppExec plugin with my own script called gitGrep that uses git grep (it's very fast and powerfull). 

* get the selected text in npp
* go in the current directory of the file
* move to the top directory of the repository
* do a git grep with some option

```bash
// process the selected text...
SCI_SENDMSG SCI_GETSELTEXT 0 @""
set local strToGrep = $(MSG_LPARAM)



// Go in top of the current repository using git rev-parse function with option --show-cdup :
// When the command is invoked from a subdirectory,
// show the path of the top-level directory relative to the current directory (typically a sequence of "../", or an empty string).
NPE_CONSOLE v+ --

cd $(CURRENT_DIRECTORY)

git rev-parse --show-cdup

set local currentRepository = $(OUTPUTL)

cd $(currentRepository)

git grep --full-name --line-number --word-regexp -C 2 -- '$(strToGrep)'

NPE_CONSOLE v- --

echo script gitGrep.sh
echo command is :
echo git grep --full-name --line-number --word-regexp -- '$(strToGrep)'

```

**Comment by cmeriaux** [comment]
I also mapped the script on a F11

```xml
<!--moduleName=NppExec.dll command=gitGrep - F11 -->
<PluginCommand moduleName="NppExec.dll" internalID="31" Ctrl="no" Alt="no" Shift="no" Key="122" />
```

**Comment by Cyberchicken** [comment]
Thank you cmeriaux!
Sorry, that doesn't fi my need. I was talking about Notepad++ projects, not git nor the filesystem. Just and addition to the "find in files": "search current project".
Strange npp still doesn't have it, I use it every day in psp.

**Comment by MetaChuh** [comment]
we are closing this issue due to its age and multiple newer notepad++ versions since it was filed.

please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html).
if your issue persists, and it is still of relevance to you, please feel free to file a new issue.

thank you for your help and best regards.

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
```
[<kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd>](https://notepad-plus-plus.org/community/)
