### ISSUE TITLE
我觉得自由软件不应当泛政治化

### ISSUE THREAD

**Issue by HarukaFuture** [notepad-plus-plus/notepad-plus-plus#6329]
无他，十一年前就已经了。

另外作者你15年默哀[被穆斯林恐怖袭击的报社](https://zh.wikipedia.org/zh-hans/%E6%9F%A5%E7%90%86%E9%80%B1%E5%88%8A%E7%B8%BD%E9%83%A8%E6%A7%8D%E6%93%8A%E6%A1%88)，
今年你又去支持这些穆斯林。

另外谁推荐一个可以替代NPP的高性能编辑器(

**Comment by KL3Answer** [comment]
sublime vim emacs 哪个不必 notepad 这玩意儿强啊

**Comment by KL3Answer** [comment]
还有 vscoce atom mousepad

**Comment by infinitysky** [comment]
Use alternative applications then.
For me, sports to sports, Politics to Politics, and techniques to techniques.
And I don't understand why the team does this. 

@HarukaFuture, you could use **MS VSCode**, sublime and atom.
The MS VScode could be an excellent alternative application, but it could take more RAM than others.

**Comment by postbird** [comment]
> 无他，十一年前就已经了。
> 
> 另外作者你15年默哀[被穆斯林恐怖袭击的报社](https://zh.wikipedia.org/zh-hans/%E6%9F%A5%E7%90%86%E9%80%B1%E5%88%8A%E7%B8%BD%E9%83%A8%E6%A7%8D%E6%93%8A%E6%A1%88)，
> 今年你又去支持这些穆斯林。
> 
> 另外谁推荐一个可以替代NPP的高性能编辑器(

vscode is the best。

这垃圾玩意儿不是十年前的东西了么  都 2019 年了。。。
