### ISSUE TITLE
如果你还是一个中国人，请卸载，nodepad 

### ISSUE THREAD

**Issue by 1032231418** [notepad-plus-plus/notepad-plus-plus#6334]
如果你还是一个中国人，请卸载，nodepad 如果你还是一个中国人，请卸载，nodepad 如果你还是一个中国人，请卸载，nodepad 如果你还是一个中国人，请卸载，nodepad 如果你还是一个中国人，请卸载，nodepad 如果你还是一个中国人，请卸载，nodepad 如果你还是一个中国人，请卸载，nodepad 如果你还是一个中国人，请卸载，nodepad 如果你还是一个中国人，请卸载，nodepad 如果你还是一个中国人，请卸载，nodepad 如果你还是一个中国人，请卸载，nodepad 如果你还是一个中国人，请卸载，nodepad 如果你还是一个中国人，请卸载，nodepad 如果你还是一个中国人，请卸载，nodepad 如果你还是一个中国人，请卸载，nodepad 如果你还是一个中国人，请卸载，nodepad 如果你还是一个中国人，请卸载，nodepad 如果你还是一个中国人，请卸载，nodepad 如果你还是一个中国人，请卸载，nodepad 如果你还是一个中国人，请卸载，nodepad 如果你还是一个中国人，请卸载，nodepad 如果你还是一个中国人，请卸载，nodepad 如果你还是一个中国人，请卸载，nodepad 如果你还是一个中国人，请卸载，nodepad 如果你还是一个中国人，请卸载，nodepad 如果你还是一个中国人，请卸载，nodepad 如果你还是一个中国人，请卸载，nodepad 如果你还是一个中国人，请卸载，nodepad 如果你还是一个中国人，请卸载，nodepad 如果你还是一个中国人，请卸载，nodepad 如果你还是一个中国人，请卸载，nodepad 如果你还是一个中国人，请卸载，nodepad 如果你还是一个中国人，请卸载，nodepad 如果你还是一个中国人，请卸载，nodepad 如果你还是一个中国人，请卸载，nodepad 如果你还是一个中国人，请卸载，nodepad 如果你还是一个中国人，请卸载，nodepad

**Comment by ajinwu** [comment]
我为你这种人是同胞而丢人

**Comment by 1032231418** [comment]
@ajinwu 你可以回炉重造，去美帝那

**Comment by lebowsk1s** [comment]
notepad++是个很好很轻便的软件，我会向身边更多的人推荐他
