### ISSUE TITLE
作了个硬分叉notepad-final，用来代替notepad++

### ISSUE THREAD

**Issue by drinkjava2** [notepad-plus-plus/notepad-plus-plus#6335]
我作了个硬分叉notepad-final，用来代替notepad++。区别是:  
1) 去除所有政治相关的内容  
2) notepad-final作为notepad++的替代品，除非以后发现大的入侵漏洞或无法忍受的Bug，原则上不作更新，毕竟只是一个无足轻重的的notepad工具而已。   
详见[notepad-final](https://github.com/drinkjava2/notepad-final)

**Comment by ma-kai-yiming** [comment]
只是一个文本编辑器，有什么大不了的

**Comment by CPythoner** [comment]
不用它就完事了
