### ISSUE TITLE
Source Code Pro font installed with Notepad++ does not have bold "&" character

### ISSUE THREAD

**Issue by Seally** [notepad-plus-plus/notepad-plus-plus#634]
The Source Code Pro font installed with Notepad++ 6.8 is buggy. It seems the glyph for the "bold" version of ampersand (&) is missing, and sometimes causes things like:
![bug0](https://cloud.githubusercontent.com/assets/507710/9034959/debc03de-39fd-11e5-82e5-030fb4d1ae60.PNG)
There should be an ampersand after `std::vector<int>` (yes, I missed the include for `vector` here and the return type is wrong, don't worry about it) and this should be `std::vector<int>&`. I've checked the style (the style used for C++ OPERATOR sets the weight to bold) and verified the issue in a third party rich text editor. The bold ampersand produces a space instead. 

Reinstalling the font from https://github.com/adobe-fonts/source-code-pro fixes the issue.

**Comment by dail8859** [comment]
See #547

**Comment by h-h-h-h** [comment]
Reference: issue https://github.com/notepad-plus-plus/notepad-plus-plus/issues/729
