### ISSUE TITLE
你到过中国吗？你到过新疆吗？当你没有验证过这些事情的时候，仅仅通过道听途说的消息就来指责中国的人权，这就是你们所谓的言论自由吗？

### ISSUE THREAD

**Issue by daominwang** [notepad-plus-plus/notepad-plus-plus#6345]
你到过中国吗？你到过新疆吗？当你没有验证过这些事情的时候，仅仅通过道听途说的消息就来指责中国的人权，这就是你们所谓的言论自由吗？

**Comment by lebowsk1s** [comment]
你的意思是你去过？你给讲讲？

**Comment by michaellee8** [comment]
你媽的人家外國記者就是去了，不給採訪，還是偷拍到證據呢。

**Comment by Morse1113** [comment]
> 你媽的人家外國記者就是去了，不給採訪，還是偷拍到證據呢。

我去过乌鲁木齐，我也有很多新疆的朋友，有汉族的也有维族的，还有哈萨克族的。我认为新疆和内地其他省市没有什么区别，生活水平，人民幸福程度，等等。甚至因为政策的原因，当地很多人的生活要比其他省市人民还要好，我不觉得有任何问题。我建议你不要只看外国的新闻就下结论了，你自己过来看看嘛，不光是新疆，其他省市你都可以去看看，亲身体会下再评价也不迟。
