### ISSUE TITLE
Don't say in here, don't lose face

### ISSUE THREAD

**Issue by ajinwu** [notepad-plus-plus/notepad-plus-plus#6354]
as a chinese, tools not has any mistake,or people has a mistake, but this is not weibo,so do not say it,github is a code trusteeship platform, is not a  place full of abuse, as a confidence chinese,please do not abuse something

**Comment by zhangwukong** [comment]
https://notepad-plus-plus.org/news/v781-free-uyghur-edition/ , what do you say about this , a no mistake article on a no mistake tools web site?

**Comment by ajinwu** [comment]
I  know, but github is not a place to abuse others,so you should to their company to say,do not speak in the internet,to real world

**Comment by zhangwukong** [comment]
so, you suggest the author to say https://notepad-plus-plus.org/news/v781-free-uyghur-edition/ this to the chinese government or the xinjiang government in the real world ?

**Comment by ajinwu** [comment]
no,I only do not like yours abuse others attitude, not has culture

**Comment by ajinwu** [comment]
[say this](https://zhuanlan.zhihu.com/p/86153650) 
you hope become this?

**Comment by Kanuveezero** [comment]
Don't get arrest or disappear, bro, hope you and family are safe
