### ISSUE TITLE
Printing Suggestion

### ISSUE THREAD

**Issue by okonomiyaki3000** [notepad-plus-plus/notepad-plus-plus#636]
Even though I use a dark theme when coding, maybe it would be a good idea to automatically switch to a light one when printing. Now, if you'll excuse me, I need to go buy some more toner.

**Comment by aaaxx** [comment]
A good way to do it would probably be to put "Select theme" dropdown box in "Preferences > Print"

**Comment by vlakoff** [comment]
You can configure it in "Preferences > Print > Colour Options".

Also, the default setting has been changed to "No background colour" (commit https://github.com/notepad-plus-plus/notepad-plus-plus/commit/d1ed7683f4ed8aed04008df4a814946e37e41fd7).

**Comment by vlakoff** [comment]
Considering the default setting is now "sane", shall this issue be closed?
