### ISSUE TITLE
支那人，东亚病夫

### ISSUE THREAD

**Issue by freeHKfreechina** [notepad-plus-plus/notepad-plus-plus#6367]
当今支那人走出国门第一步，就是高呼一句CNMB，不论什么情况，这是在全世界丢人
这是没有被现代文明教育过的结果，永远吠，永远没有道理可讲。
“东亚病夫” 这四个字还是刻在你们脑门上了

你们享受别人成果之时还来压制言论自由，无视台湾人民的生命喊杀喊打，冷血至极。
以及自己被奴役，还来骂自由世界的人，愚蠢可悲。
你们的同胞被残害不曾发声，你们的财产被掠夺不曾发声，来到美国人的网站上突然感觉自己拥有了权力乱吠。全世界看到的你们- 东亚病夫

你们继续爱你们的国，过着996的生活，你们和你们的祖国，一刻也不能分隔
### Steps to Reproduce the Issue

1. 
2. 
3.

**Comment by iotang** [comment]
你们说什么都是言论自由
我们说什么都是被洗脑
双标玩得 6 啊你个小比崽子

**Comment by ritaswc** [comment]
你们说什么都是言论自由
我们说什么都是被洗脑
双标玩得 6 啊你个小比崽子

**Comment by freeHKfreechina** [comment]
> 你们说什么都是言论自由
> 我们说什么都是被洗脑
> 双标玩得 6 啊你个小比崽子

我说支那人会吠，果然是张口就来

**Comment by tangzhangming** [comment]
老公压老婆还是老婆压老公都是自己家的事，我即使不想被压，想做压人的那一个，那也不需要你们帮忙，不需要你们在这儿龇牙咧嘴，张牙舞爪。

还有，我们一起教育逆子就更轮不到你们来管了

**Comment by 4332weizi** [comment]
厉害厉害，跟香港废青一样，永远蒙着脸，连发个issue都要新注册帐号

**Comment by 0x112** [comment]
光復香港 時代革命
五大訴求 缺一不可

**Comment by Jerry007s** [comment]
NMSL

**Comment by iotang** [comment]
> > 你们说什么都是言论自由
> > 我们说什么都是被洗脑
> > 双标玩得 6 啊你个小比崽子
> 
> 我说支那人会吠，果然是张口就来

你也就只能扣个字眼了

**Comment by skindowSyc** [comment]
撤了撤了，没有一句有实质性证据的话，满口喷粪，名字还取得人模狗样的

**Comment by freeHKfreechina** [comment]
> > > 你们说什么都是言论自由
> > > 我们说什么都是被洗脑
> > > 双标玩得 6 啊你个小比崽子
> > 
> > 
> > 我说支那人会吠，果然是张口就来
> 
> 你也就只能扣个字眼了

不，我还能看你们被CCP玩弄

**Comment by freeHKfreechina** [comment]
> 撤了撤了，没有一句有实质性证据的话，满口喷粪，名字还取得人模狗样的

不要这样说自己

**Comment by freeHKfreechina** [comment]
> NMSL

复合国人素质

**Comment by 4332weizi** [comment]
见不了光的垃圾

**Comment by zhangwukong** [comment]
> > 你们说什么都是言论自由
> > 我们说什么都是被洗脑
> > 双标玩得 6 啊你个小比崽子
> 
> 我说支那人会吠，果然是张口就来

因为实在是不想跟你们BB，浪费口舌。
by the way
NMSL WSND.

**Comment by iotang** [comment]
> > > > 你们说什么都是言论自由
> > > > 我们说什么都是被洗脑
> > > > 双标玩得 6 啊你个小比崽子
> > > 
> > > 
> > > 我说支那人会吠，果然是张口就来
> > 
> > 
> > 你也就只能扣个字眼了
> 
> 不，我还能看你们被CCP玩弄

你要不举点例子吧。看看你被那些媒体灌输了多少错误信息。

**Comment by shimachao** [comment]
当初日本人用刺刀指着你们父辈骂他们为支那人，如今你也学会用这支那骂同胞

**Comment by owen800q** [comment]
支那人，东亚病夫

**Comment by LY16JAVA-zhangzhiyuan** [comment]
哦，我应该言论自由对吧，那我告诉你：“你妈死了”，你不应该反驳吧，毕竟我自由啊，我不用管这句话是真的是假的。
我们虽然在进步的路上有一定的不足，但自认还是有一些膝盖和脊梁的，似你这般美国养出的狗说出“支那人，东亚病夫”，不觉得很讽刺吗？我们有脊梁，而你没有。
至于你说“人权”，我寻思着：“一部分想作乱的人的人权是人权，其他人的人权就权当放屁了呗.”还是说在你眼里，在台湾不想台毒的人在你眼里就不是人了？
来嘛，别说什么吠不吠的，讲道理反驳我啊！

**Comment by zhangwukong** [comment]
> 支那人，东亚病夫

废材们  有能力独立出去再骂   你现在骂你自己干啥呢？

**Comment by tangzhangming** [comment]
> 当初日本人用刺刀指着你们父辈骂他们为支那人，如今你也学会用这支那骂同胞

日军侵华时，台湾以及被占领了，10个关东军就有一个朝鲜士兵，一个台湾士兵，你和人家讲这个估计人家没啥体会，他父亲可能就是帮关东军提刀的那个

**Comment by Little55555** [comment]
讲道理, 你又讲不过, 却说我们不讲道理.  只会出口一句怎么样怎么样, 咪当你傻嗨.

**Comment by penghubingzhou** [comment]
你这种双标狗也就配在这叫两声了

**Comment by Neilsons** [comment]
> 当今支那人走出国门第一步，就是高呼一句CNMB，不论什么情况，这是在全世界丢人
> 这是没有被现代文明教育过的结果，永远吠，永远没有道理可讲。
> “东亚病夫” 这四个字还是刻在你们脑门上了
> 
> 你们享受别人成果之时还来压制言论自由，无视台湾人民的生命喊杀喊打，冷血至极。
> 以及自己被奴役，还来骂自由世界的人，愚蠢可悲。
> 你们的同胞被残害不曾发声，你们的财产被掠夺不曾发声，来到美国人的网站上突然感觉自己拥有了权力乱吠。全世界看到的你们- 东亚病夫
> 
> 你们继续爱你们的国，过着996的生活，你们和你们的祖国，一刻也不能分隔
> 
> ### Description of the Issue
> ### Steps to Reproduce the Issue
> 
> ### Expected Behavior
> ### Actual Behavior
> ### Debug Information
请用你的母语。沙雕，狗鸡儿给你阔掉，能听懂吗，不懂我给你细讲。

**Comment by lwgithub12** [comment]
你骂别人 ，别人还击，你就说别人素质低，那你的素质呢？

**Comment by LY16JAVA-zhangzhiyuan** [comment]
> 哦，我应该言论自由对吧，那我告诉你：“你妈死了”，你不应该反驳吧，毕竟我自由啊，我不用管这句话是真的是假的。
> 我们虽然在进步的路上有一定的不足，但自认还是有一些膝盖和脊梁的，似你这般美国养出的狗说出“支那人，东亚病夫”，不觉得很讽刺吗？我们有脊梁，而你没有。
> 至于你说“人权”，我寻思着：“一部分想作乱的人的人权是人权，其他人的人权就权当放屁了呗.”还是说在你眼里，在台湾不想台毒的人在你眼里就不是人了？
> 来嘛，别说什么吠不吠的，讲道理反驳我啊！

不是喜欢讲道理嘛，我道理讲出来了，你呢？说话啊！还是说，你嘴上说着别人只会狗吠，其实自己才是那条会叫的狗啊。那确实，让你这条未开化的狗出来讲道理，难为你了。倒是我的不对了。

**Comment by liJasper** [comment]
不给你们这些废青点颜色看看，你们就不知道中国文化博大精深，SB孤儿，去跟美国人当狗啊

**Comment by freeHKfreechina** [comment]
> 你骂别人 ，别人还击，你就说别人素质低，那你的素质呢？

说出了事实的人

**Comment by freeHKfreechina** [comment]
> 不给你们这些废青点颜色看看，你们就不知道中华文化博大精深，SB孤儿，去跟美国人当狗啊

复合国人素质

**Comment by freeHKfreechina** [comment]
> > 哦，我应该言论自由对吧，那我告诉你：“你妈死了”，你不应该反驳吧，毕竟我自由啊，我不用管这句话是真的是假的。
> > 我们虽然在进步的路上有一定的不足，但自认还是有一些膝盖和脊梁的，似你这般美国养出的狗说出“支那人，东亚病夫”，不觉得很讽刺吗？我们有脊梁，而你没有。
> > 至于你说“人权”，我寻思着：“一部分想作乱的人的人权是人权，其他人的人权就权当放屁了呗.”还是说在你眼里，在台湾不想台毒的人在你眼里就不是人了？
> > 来嘛，别说什么吠不吠的，讲道理反驳我啊！
> 
> 不是喜欢讲道理嘛，我道理讲出来了，你呢？说话啊！还是说，你嘴上说着别人只会狗吠，其实自己才是那条会叫的狗啊。那确实，让你这条未开化的狗出来讲道理，难为你了。倒是我的不对了。

你看你，又吠了，你的道理就是脏话嘛

**Comment by freeHKfreechina** [comment]
> 当初日本人用刺刀指着你们父辈骂他们为支那人，如今你也学会用这支那骂同胞

我不是你的同胞，你的同胞被你的同胞炸死了

**Comment by ReasonDuan** [comment]
> > 当初日本人用刺刀指着你们父辈骂他们为支那人，如今你也学会用这支那骂同胞
> 
> 我不是你的同胞，你的同胞被你的同胞炸死了

美国走狗，鉴定完毕，撤了！

**Comment by lwgithub12** [comment]
> > 你骂别人 ，别人还击，你就说别人素质低，那你的素质呢？
> 
> 说出了事实的人

我问你呢 ，请回答你的素质呢

**Comment by freeHKfreechina** [comment]
> > > 当初日本人用刺刀指着你们父辈骂他们为支那人，如今你也学会用这支那骂同胞
> > 
> > 
> > 我不是你的同胞，你的同胞被你的同胞炸死了
> 
> 美国走狗，鉴定完毕，撤了！

敌人的网站你也敢上，你反共啊

**Comment by Twoearle** [comment]
动态网自由门 天安門 天安门 法輪功 李洪志 Free Tibet 六四天安門事件 The Tiananmen Square protests of 1989 天安門大屠殺 The Tiananmen Square Massacre 反右派鬥爭 The Anti-Rightist Struggle 大躍進政策 The Great Leap Forward 文化大革命 The Great Proletarian Cultural Revolution 人權 Human Rights 民運 Democratization 自由 Freedom 獨立 Independence 多黨制 Multi-party system 台灣 臺灣 Taiwan Formosa 中華民國 Republic of China 西藏 土伯特 唐古特 Tibet 達賴喇嘛 Dalai Lama 法輪功 Falun Dafa 新疆維吾爾自治區 The Xinjiang Uyghur Autonomous Region 諾貝爾和平獎 Nobel Peace Prize 劉暁波 Liu Xiaobo 民主 言論 思想 反共 反革命 抗議 運動 騷亂 暴亂 騷擾 擾亂 抗暴 平反 維權 示威游行 李洪志 法輪大法 大法弟子 強制斷種 強制堕胎 民族淨化 人體實驗 肅清 胡耀邦 趙紫陽 魏京生 王丹 還政於民 和平演變 激流中國 北京之春 大紀元時報 九評論共産黨 獨裁 專制 壓制 統一 監視 鎮壓 迫害 侵略 掠奪 破壞 拷問 屠殺 活摘器官 誘拐 買賣人口 遊進 走私 毒品 賣淫 春畫 賭博 六合彩 天安門 天安门 法輪功 李洪志 Winnie the Pooh 劉曉波动态网自由门

**Comment by freeHKfreechina** [comment]
> > > 你骂别人 ，别人还击，你就说别人素质低，那你的素质呢？
> > 
> > 
> > 说出了事实的人
> 
> 我问你呢 ，请回答你的素质呢

您好，我的素质应该有他人评价，自我评价是中华名族的美德

**Comment by liJasper** [comment]
都别理这个沙雕，让他自己嗨去吧，有些人跪着跪着就趴下了

**Comment by LY16JAVA-zhangzhiyuan** [comment]
> > > 哦，我应该言论自由对吧，那我告诉你：“你妈死了”，你不应该反驳吧，毕竟我自由啊，我不用管这句话是真的是假的。
> > > 我们虽然在进步的路上有一定的不足，但自认还是有一些膝盖和脊梁的，似你这般美国养出的狗说出“支那人，东亚病夫”，不觉得很讽刺吗？我们有脊梁，而你没有。
> > > 至于你说“人权”，我寻思着：“一部分想作乱的人的人权是人权，其他人的人权就权当放屁了呗.”还是说在你眼里，在台湾不想台毒的人在你眼里就不是人了？
> > > 来嘛，别说什么吠不吠的，讲道理反驳我啊！
> > 
> > 
> > 不是喜欢讲道理嘛，我道理讲出来了，你呢？说话啊！还是说，你嘴上说着别人只会狗吠，其实自己才是那条会叫的狗啊。那确实，让你这条未开化的狗出来讲道理，难为你了。倒是我的不对了。
> 
> 你看你，又吠了，你的道理就是脏话嘛

哦，那你讲讲看嘛，你的道理呢？只会说别人吠，你自己呢？道理也不会讲？让我怀疑你是否有受过教育了。你又不讲道理，那说你不是野人大伙也不信啊。我是实话实说怎么能算吠呢

**Comment by hwt83525055** [comment]
why not reply?
我第一个留言的，结果没有回复我，其实很多问题你们自己想想也能想通，每个国家和地区都有国骂，USA只会骂的更夸张，所以看评论我都是忽略这些无用的信息，但是看了一圈下来，你似乎还是停留在简单的素质攻击和小学生对骂的环节上，我希望能看到你提供有用的信息，最好不是媒体的信息，不论是usa的，还是墙内的信息，都只是片面的。 ok？ 回复我

**Comment by lwgithub12** [comment]
> > > > 你骂别人 ，别人还击，你就说别人素质低，那你的素质呢？
> > > 
> > > 
> > > 说出了事实的人
> > 
> > 
> > 我问你呢 ，请回答你的素质呢
> 
> 您好，我的素质应该有他人评价，自我评价是中华名族的美德

你辱骂别人是东亚病夫，这就你的素质？那我是不是也可以骂你全家？

**Comment by iotang** [comment]
> > > > > 你们说什么都是言论自由
> > > > > 我们说什么都是被洗脑
> > > > > 双标玩得 6 啊你个小比崽子
> > > > 
> > > > 
> > > > 我说支那人会吠，果然是张口就来
> > > 
> > > 
> > > 你也就只能扣个字眼了
> > 
> > 
> > 不，我还能看你们被CCP玩弄
> 
> 你要不举点例子吧。看看你被那些媒体灌输了多少错误信息。

你就这么忽略这条回复了？看来你们只会意淫啊。

**Comment by freeHKfreechina** [comment]
> > > > > > 你们说什么都是言论自由
> > > > > > 我们说什么都是被洗脑
> > > > > > 双标玩得 6 啊你个小比崽子
> > > > > 
> > > > > 
> > > > > 我说支那人会吠，果然是张口就来
> > > > 
> > > > 
> > > > 你也就只能扣个字眼了
> > > 
> > > 
> > > 不，我还能看你们被CCP玩弄
> > 
> > 
> > 你要不举点例子吧。看看你被那些媒体灌输了多少错误信息。
> 
> 你就这么忽略这条回复了？看来你们只会意淫啊。

这就是最好例子啊，你国的网站你能讨论这些吗

**Comment by chenheng1998** [comment]
> > > 你们说什么都是言论自由
> > > 我们说什么都是被洗脑
> > > 双标玩得 6 啊你个小比崽子
> > 
> > 
> > 我说支那人会吠，果然是张口就来
> 
> 因为实在是不想跟你们BB，浪费口舌。
> by the way
> NMSL WSND.
老哥，当这人的爹可不是好事。

**Comment by freeHKfreechina** [comment]
> why not reply?
> 我第一个留言的，结果没有回复我，其实很多问题你们自己想想也能想通，每个国家和地区都有国骂，USA只会骂的更夸张，所以看评论我都是忽略这些无用的信息，但是看了一圈下来，你似乎还是停留在简单的素质攻击和小学生对骂的环节上，我希望能看到你提供有用的信息，最好不是媒体的信息，不论是usa的，还是墙内的信息，都只是片面的。 ok？ 回复我

我看到最有用的信息，就是中国人自己蒙上了自己的眼睛

**Comment by freeHKfreechina** [comment]
> > > > 你们说什么都是言论自由
> > > > 我们说什么都是被洗脑
> > > > 双标玩得 6 啊你个小比崽子
> > > 
> > > 
> > > 我说支那人会吠，果然是张口就来
> > 
> > 
> > 因为实在是不想跟你们BB，浪费口舌。
> > by the way
> > NMSL WSND.
> > 老哥，当这人的爹可不是好事。

你们的母亲不是党吗？怎么能这么说你们的母亲

**Comment by freeHKfreechina** [comment]
> why not reply?
> 我第一个留言的，结果没有回复我，其实很多问题你们自己想想也能想通，每个国家和地区都有国骂，USA只会骂的更夸张，所以看评论我都是忽略这些无用的信息，但是看了一圈下来，你似乎还是停留在简单的素质攻击和小学生对骂的环节上，我希望能看到你提供有用的信息，最好不是媒体的信息，不论是usa的，还是墙内的信息，都只是片面的。 ok？ 回复我

如果绝的信息是片面的，主观的，就去证实理解，让自己信服。你又凭什么说我是被无用信息骗了呢

**Comment by freeHKfreechina** [comment]
> > > > > 你骂别人 ，别人还击，你就说别人素质低，那你的素质呢？
> > > > 
> > > > 
> > > > 说出了事实的人
> > > 
> > > 
> > > 我问你呢 ，请回答你的素质呢
> > 
> > 
> > 您好，我的素质应该有他人评价，自我评价是中华名族的美德
> 
> 你辱骂别人是东亚病夫，这就你的素质？那我是不是也可以骂你全家？

你要是自信为什么觉得别人骂你呢

**Comment by hwt83525055** [comment]
> > why not reply?
> > 我第一个留言的，结果没有回复我，其实很多问题你们自己想想也能想通，每个国家和地区都有国骂，USA只会骂的更夸张，所以看评论我都是忽略这些无用的信息，但是看了一圈下来，你似乎还是停留在简单的素质攻击和小学生对骂的环节上，我希望能看到你提供有用的信息，最好不是媒体的信息，不论是usa的，还是墙内的信息，都只是片面的。 ok？ 回复我
> 
> 如果绝的信息是片面的，主观的，就去证实理解，让自己信服。你又凭什么说我是被无用信息骗了呢

抱歉，你好像没看明白我的意思，结论是你提出的，论据理应由你出具，就好比我认定A是责任承担者，也就是犯人，理应由我出具证明他是犯人的证据，而非他出具他不是犯人的证据，在你我两者都是当局者的情况下，也应当由你先提出你的证据，如果你觉得我的信息是片面主观的，你可以提供自己的论据，但绝对不是【带有政治背景】的媒体文章，tks

**Comment by shimachao** [comment]
> > 当初日本人用刺刀指着你们父辈骂他们为支那人，如今你也学会用这支那骂同胞
> 
> 我不是你的同胞，你的同胞被你的同胞炸死了

能不能自信的说出你是哪国人

**Comment by iotang** [comment]
> > > > > > > 你们说什么都是言论自由
> > > > > > > 我们说什么都是被洗脑
> > > > > > > 双标玩得 6 啊你个小比崽子
> > > > > > 
> > > > > > 
> > > > > > 我说支那人会吠，果然是张口就来
> > > > > 
> > > > > 
> > > > > 你也就只能扣个字眼了
> > > > 
> > > > 
> > > > 不，我还能看你们被CCP玩弄
> > > 
> > > 
> > > 你要不举点例子吧。看看你被那些媒体灌输了多少错误信息。
> > 
> > 
> > 你就这么忽略这条回复了？看来你们只会意淫啊。
> 
> 这就是最好例子啊，你国的网站你能讨论这些吗

你来过大陆吗？

**Comment by Little55555** [comment]
和你在这争执,就是浪费时间. 你觉得你在这说几句话, 就是在为某件煞笔事发声, 然而却不知道自己的行为是多么煞笔... 总搞这些没用的, 还伤天害理的事.  你要有用, 你可以把hk拿下来吗,,   你不行就是废物, 别在这整些没用的.    你以为自己有很多人都像你这么想的; 然而,也就那几个老鼠屎,

**Comment by lwgithub12** [comment]
> > > > > > 你骂别人 ，别人还击，你就说别人素质低，那你的素质呢？
> > > > > 
> > > > > 
> > > > > 说出了事实的人
> > > > 
> > > > 
> > > > 我问你呢 ，请回答你的素质呢
> > > 
> > > 
> > > 您好，我的素质应该有他人评价，自我评价是中华名族的美德
> > 
> > 
> > 你辱骂别人是东亚病夫，这就你的素质？那我是不是也可以骂你全家？
> 
> 你要是自信为什么觉得别人骂你呢

你这真是神逻辑啊，“支那人，东亚病夫” 谁看不出来这是在辱骂中国人？这真的和自信没有关系。按照你的逻辑，我可以骂你全家，然后你敢反击我，我就会说你不自信，如果你自信 怎么会觉得我在骂你呢。

**Comment by ritaswc** [comment]
要脸？？？？
两个小时之前加入github？？？？？？？？？？？
![TIM截图20191030163207](https://user-images.githubusercontent.com/15887140/67841384-eaef5200-fb32-11e9-99d3-e7a886715302.png)

**Comment by iotang** [comment]
用户 freeHKfreechina 的表演秀上线啦！
逻辑带师，精神胜利
颅内出国，在线高潮
选择失明，狺狺狂吠
更多精彩，在线放送
详情请访问：>> https://github·com/notepad-plus-plus/notepad-plus-plus/issues/6367 <<

**Comment by freeHKfreechina** [comment]
> 要脸？？？？
> 两个小时之前加入github？？？？？？？？？？？
> ![TIM截图20191030163207](https://user-images.githubusercontent.com/15887140/67841384-eaef5200-fb32-11e9-99d3-e7a886715302.png)

有什么问题吗？

**Comment by freeHKfreechina** [comment]
> 用户 freeHKfreechina 的表演秀上线啦！
> 逻辑带师，精神胜利
> 颅内出国，在线高潮
> 选择失明，狺狺狂吠
> 更多精彩，在线放送
> 详情请访问：>> [https://github·com/notepad-plus-plus/notepad-plus-plus/issues/6367](https://github%C2%B7com/notepad-plus-plus/notepad-plus-plus/issues/6367) <<

看来你是澳门出来的

**Comment by freeHKfreechina** [comment]
> > > > > > > 你骂别人 ，别人还击，你就说别人素质低，那你的素质呢？
> > > > > > 
> > > > > > 
> > > > > > 说出了事实的人
> > > > > 
> > > > > 
> > > > > 我问你呢 ，请回答你的素质呢
> > > > 
> > > > 
> > > > 您好，我的素质应该有他人评价，自我评价是中华名族的美德
> > > 
> > > 
> > > 你辱骂别人是东亚病夫，这就你的素质？那我是不是也可以骂你全家？
> > 
> > 
> > 你要是自信为什么觉得别人骂你呢
> 
> 你这真是神逻辑啊，“支那人，东亚病夫” 谁看不出来这是在辱骂中国人？这真的和自信没有关系。按照你的逻辑，我可以骂你全家，然后你敢反击我，我就会说你不自信，如果你自信 怎么会觉得我在骂你呢。

你为什么觉得支那人，东亚病夫 就是骂你呢

**Comment by freeHKfreechina** [comment]
> 和你在这争执,就是浪费时间. 你觉得你在这说几句话, 就是在为某件煞笔事发声, 然而却不知道自己的行为是多么煞笔... 总搞这些没用的, 还伤天害理的事. 你要有用, 你可以把hk拿下来吗,, 你不行就是废物, 别在这整些没用的. 你以为自己有很多人都像你这么想的; 然而,也就那几个老鼠屎,

没用你们激动什么，爱国去呀

**Comment by freeHKfreechina** [comment]
> > > why not reply?
> > > 我第一个留言的，结果没有回复我，其实很多问题你们自己想想也能想通，每个国家和地区都有国骂，USA只会骂的更夸张，所以看评论我都是忽略这些无用的信息，但是看了一圈下来，你似乎还是停留在简单的素质攻击和小学生对骂的环节上，我希望能看到你提供有用的信息，最好不是媒体的信息，不论是usa的，还是墙内的信息，都只是片面的。 ok？ 回复我
> > 
> > 
> > 如果绝的信息是片面的，主观的，就去证实理解，让自己信服。你又凭什么说我是被无用信息骗了呢
> 
> 抱歉，你好像没看明白我的意思，结论是你提出的，论据理应由你出具，就好比我认定A是责任承担者，也就是犯人，理应由我出具证明他是犯人的证据，而非他出具他不是犯人的证据，在你我两者都是当局者的情况下，也应当由你先提出你的证据，如果你觉得我的信息是片面主观的，你可以提供自己的论据，但绝对不是【带有政治背景】的媒体文章，tks

你有能力总结下我的结论是什么呢？

**Comment by lwgithub12** [comment]
> > > > > > > > 你骂别人 ，别人还击，你就说别人素质低，那你的素质呢？
> > > > > > > 
> > > > > > > 
> > > > > > > 说出了事实的人
> > > > > > 
> > > > > > 
> > > > > > 我问你呢 ，请回答你的素质呢
> > > > > 
> > > > > 
> > > > > 您好，我的素质应该有他人评价，自我评价是中华名族的美德
> > > > 
> > > > 
> > > > 你辱骂别人是东亚病夫，这就你的素质？那我是不是也可以骂你全家？
> > > 
> > > 
> > > 你要是自信为什么觉得别人骂你呢
> > 
> > 
> > 你这真是神逻辑啊，“支那人，东亚病夫” 谁看不出来这是在辱骂中国人？这真的和自信没有关系。按照你的逻辑，我可以骂你全家，然后你敢反击我，我就会说你不自信，如果你自信 怎么会觉得我在骂你呢。
> 
> 你为什么觉得支那人，东亚病夫 就是骂你呢

这不和我骂完你全家后 ，你为什么觉得我在骂你全家一个道理嘛 指桑骂槐

**Comment by Mr-LCH** [comment]
dad告诉你：你就是个满嘴喷粪的小朋友，屎给你喂多了怪我，不跟你一般见识，毕竟童言无忌嘛

**Comment by andy1ee11o2** [comment]
傻吊一个，用着中国字还不当中国人。我怕你家祖宗要被你气活过来！

**Comment by luozhangs** [comment]
这种台独分子大家对付他的最好办法就是无视他

**Comment by infoabcd** [comment]
emmm，林子大了，啥鸟都有

**Comment by cuixiaoao** [comment]
滚你妈逼

**Comment by HippoFly** [comment]
点艹支那猪8964次
