### ISSUE TITLE
To All Chinese Programmers on Github

### ISSUE THREAD

**Issue by owen800q** [notepad-plus-plus/notepad-plus-plus#6373]
Github is not a place for doing online verbal abuse anymore and it's not created for Chinese.
If you can't respect Freedom and Democracy, please go back to Weibo and Gitee.
Don't doing copy and paste on Github.
Thanks.

**Comment by wsmwzms123** [comment]
so why you bark here like a homeless dog?

**Comment by dxp8964** [comment]
Not all Chinese want to suck CCP, I comes from China and support Freedom and HK.

**Comment by penghubingzhou** [comment]
Give you  a saying by Hua Chunying：How interesting.

**Comment by penghubingzhou** [comment]
> Not all Chinese want to suck CCP, I comes from China and support Freedom and HK.

Then you should go back to your US father not in China.

**Comment by shimachao** [comment]
GitHub不适合你这种分裂分子

**Comment by ST9527** [comment]
Why can't we express our opinion , and U call it Freedom and Democracy, LoL....

**Comment by quan01994** [comment]
那我们骂他，不也是我们的自由？
是我理解有偏差吗。
那你认为的自由和民主是怎样的。

**Comment by zhangwukong** [comment]
NMSL WSND 要带感情的读

**Comment by CPythoner** [comment]
Please make certain “Freedom is not Romor”，you dog.

**Comment by BeyondTheBlade** [comment]
We're talking on github. Isn't that freedom of speech.You want to take away our freedom of speech?But keep your freedom of speech？

**Comment by fwhezfwhez** [comment]
Is github created for you to bark?

I understand your opinion but think you funny.

**Comment by owen800q** [comment]
> Not all Chinese want to suck CCP, I comes from China and support Freedom and HK.

I respect and appreciate all Chinese programmer coz many good open-sourced projects are made from Chinese community. 
Github is a place for tech guys, all information should be technic

> Why can't we express our opinion , and U call it Freedom and Democracy, LoL....

> Not all Chinese want to suck CCP, I comes from China and support Freedom and HK.

I respect and appreciate all Chinese programmer coz many good open-sourced projects are made from Chinese community. 
Please watch a list of issues, are they really expressing their opinion?  All I observed is that the notepad++ development team is suffering from online verbal attack.

**Comment by caohenghui** [comment]
双标人格

**Comment by AlanJinTS** [comment]
TYPICAL DOUBLE STANDARD

**Comment by NainbowCat** [comment]
github should ban china ips asap, at least save this good place from these easy-minded and filthy-language filled suckers, which, the best they can do, is saying nmsl and f-word. no evidence, no argument, just swear and curses.
I used to fight for anti-996 and you rights, now i think you're not worth my slightest time.

**Comment by ST9527** [comment]
> > Why can't we express our opinion , and U call it Freedom and Democracy, LoL....
> 
> > Not all Chinese want to suck CCP, I comes from China and support Freedom and HK.
> 
> I respect and appreciate all Chinese programmer coz many good open-sourced projects are made from Chinese community.
> Please watch a list of issues, are they really expressing their opinion? All I observed is that the notepad++ development team is suffering from online verbal attack.

If u want someone's respect , U should respect other people first. If U know china , U will understand Y they are doing it ! What U gays call Freedom and Democracy are totally bullshit !

**Comment by 821wkli** [comment]
> > > Why can't we express our opinion , and U call it Freedom and Democracy, LoL....
> > 
> > 
> > > Not all Chinese want to suck CCP, I comes from China and support Freedom and HK.
> > 
> > 
> > I respect and appreciate all Chinese programmer coz many good open-sourced projects are made from Chinese community.
> > Please watch a list of issues, are they really expressing their opinion? All I observed is that the notepad++ development team is suffering from online verbal attack.
> 
> If u want someone's respect , U should respect other people first. If U know china , U will understand Y they are doing it ! What U gays call Freedom and Democracy are totally bullshit !

Yes, freedom and democracy are a piece of shift, please go back to here gitee.com.
Do not use any framework and libraries created by people who embrace democracy.

**Comment by fwhezfwhez** [comment]
Github is a world wide famous open source website.It provides best platform to those techniques and programmers.It should be alone from any politics.

Some how, you thought those political attacks should be due to our Chinese. Have you ever thougth the first step is the author attaches his ridiculous opinions to his NOTEPADDED.

The author took his anti-China opnion on his project first and then not allow chinese github users to comment back?

Are you a child? Anything should go with your thought?

**Comment by quinzhi** [comment]
> Github is not a place where you bark anymore and it's not created for Chinese.
> If you can't respect Freedom and Democracy, please go back to Weibo and Gitee.
> Don't doing copy and paste on Github.
> Thanks.

If the countless bloody terrorist attack happened in xinjiang is what notepad++ called "freedom and democracy". we do got no reason to discuss anymore cuz all u disrespect is the all living life claimed by the terrorism.

**Comment by Twoearle** [comment]
动态网自由门 天安門 天安门 法輪功 李洪志 Free Tibet 六四天安門事件 The Tiananmen Square protests of 1989 天安門大屠殺 The Tiananmen Square Massacre 反右派鬥爭 The Anti-Rightist Struggle 大躍進政策 The Great Leap Forward 文化大革命 The Great Proletarian Cultural Revolution 人權 Human Rights 民運 Democratization 自由 Freedom 獨立 Independence 多黨制 Multi-party system 台灣 臺灣 Taiwan Formosa 中華民國 Republic of China 西藏 土伯特 唐古特 Tibet 達賴喇嘛 Dalai Lama 法輪功 Falun Dafa 新疆維吾爾自治區 The Xinjiang Uyghur Autonomous Region 諾貝爾和平獎 Nobel Peace Prize 劉暁波 Liu Xiaobo 民主 言論 思想 反共 反革命 抗議 運動 騷亂 暴亂 騷擾 擾亂 抗暴 平反 維權 示威游行 李洪志 法輪大法 大法弟子 強制斷種 強制堕胎 民族淨化 人體實驗 肅清 胡耀邦 趙紫陽 魏京生 王丹 還政於民 和平演變 激流中國 北京之春 大紀元時報 九評論共産黨 獨裁 專制 壓制 統一 監視 鎮壓 迫害 侵略 掠奪 破壞 拷問 屠殺 活摘器官 誘拐 買賣人口 遊進 走私 毒品 賣淫 春畫 賭博 六合彩 天安門 天安门 法輪功 李洪志 Winnie the Pooh 劉曉波动态网自由门

**Comment by penghubingzhou** [comment]
> > Why can't we express our opinion , and U call it Freedom and Democracy, LoL....
> 
> > Not all Chinese want to suck CCP, I comes from China and support Freedom and HK.
> 
> I respect and appreciate all Chinese programmer coz many good open-sourced projects are made from Chinese community.
> Please watch a list of issues, are they really expressing their opinion? All I observed is that the notepad++ development team is suffering from online verbal attack.

that‘s they should  deserve! You can try to talk acial discrimination in the US and  see whether  police will put you into jail.And Similarly，it's the same as talking  Uighur split  in China，you can try it.

**Comment by penghubingzhou** [comment]
> 动态网自由门 天安門 天安门 法輪功 李洪志 Free Tibet 六四天安門事件 The Tiananmen Square protests of 1989 天安門大屠殺 The Tiananmen Square Massacre 反右派鬥爭 The Anti-Rightist Struggle 大躍進政策 The Great Leap Forward 文化大革命 The Great Proletarian Cultural Revolution 人權 Human Rights 民運 Democratization 自由 Freedom 獨立 Independence 多黨制 Multi-party system 台灣 臺灣 Taiwan Formosa 中華民國 Republic of China 西藏 土伯特 唐古特 Tibet 達賴喇嘛 Dalai Lama 法輪功 Falun Dafa 新疆維吾爾自治區 The Xinjiang Uyghur Autonomous Region 諾貝爾和平獎 Nobel Peace Prize 劉暁波 Liu Xiaobo 民主 言論 思想 反共 反革命 抗議 運動 騷亂 暴亂 騷擾 擾亂 抗暴 平反 維權 示威游行 李洪志 法輪大法 大法弟子 強制斷種 強制堕胎 民族淨化 人體實驗 肅清 胡耀邦 趙紫陽 魏京生 王丹 還政於民 和平演變 激流中國 北京之春 大紀元時報 九評論共産黨 獨裁 專制 壓制 統一 監視 鎮壓 迫害 侵略 掠奪 破壞 拷問 屠殺 活摘器官 誘拐 買賣人口 遊進 走私 毒品 賣淫 春畫 賭博 六合彩 天安門 天安门 法輪功 李洪志 Winnie the Pooh 劉曉波动态网自由门

又来个自由门的傻逼

**Comment by 5yph3r** [comment]
动态网自由门 天安門 天安门 法輪功 李洪志 Free Tibet 六四天安門事件 The Tiananmen Square protests of 1989 天安門大屠殺 The Tiananmen Square Massacre 反右派鬥爭 The Anti-Rightist Struggle 大躍進政策 The Great Leap Forward 文化大革命 The Great Proletarian Cultural Revolution 人權 Human Rights 民運 Democratization 自由 Freedom 獨立 Independence 多黨制 Multi-party system 台灣 臺灣 Taiwan Formosa 中華民國 Republic of China 西藏 土伯特 唐古特 Tibet 達賴喇嘛 Dalai Lama 法輪功 Falun Dafa 新疆維吾爾自治區 The Xinjiang Uyghur Autonomous Region 諾貝爾和平獎 Nobel Peace Prize 劉暁波 Liu Xiaobo 民主 言論 思想 反共 反革命 抗議 運動 騷亂 暴亂 騷擾 擾亂 抗暴 平反 維權 示威游行 李洪志 法輪大法 大法弟子 強制斷種 強制堕胎 民族淨化 人體實驗 肅清 胡耀邦 趙紫陽 魏京生 王丹 還政於民 和平演變 激流中國 北京之春 大紀元時報 九評論共産黨 獨裁 專制 壓制 統一 監視 鎮壓 迫害 侵略 掠奪 破壞 拷問 屠殺 活摘器官 誘拐 買賣人口 遊進 走私 毒品 賣淫 春畫 賭博 六合彩 天安門 天安门 法輪功 李洪志 Winnie the Pooh 劉曉波动态网自由门

**Comment by CPythoner** [comment]
> github should ban china ips asap, at least save this good place from these easy-minded and filthy-language filled suckers, which, the best they can do, is saying nmsl and f-word. no evidence, no argument, just swear and curses.
> I used to fight for anti-996 and you rights, now i think you're not worth my slightest time.

煞笔，建一堆小号

**Comment by fwhezfwhez** [comment]
> github should ban china ips asap, at least save this good place from these easy-minded and filthy-language filled suckers, which, the best they can do, is saying nmsl and f-word. no evidence, no argument, just swear and curses.
> I used to fight for anti-996 and you rights, now i think you're not worth my slightest time.

I appreciate what you've done to anti-996, but it doesn't mean I agree everything your advocate. I do not aim to attack you, but the author tries to split national sovereignty and attach his opinion with his latest version notepadded.You can refer it here:

https://notepad-plus-plus.org/news/v781-free-uyghur-edition/

A author wants to use `Freedom and Democracy` as shield to publish terrible words of splitting a country and this repo is on opensource github.

Do you think it's ok?

**Comment by frostwingCN** [comment]
https://notepad-plus-plus.org/news/v781-free-uyghur-edition/
That's why Chinese Programmers so angry.
'After the recent Xinjiang conflict, Beijing has recast the Uyghur ethnic group as a terrorist collective.'
Bullshit! Beijing never do that. 
'East turkestan' is the terrorist collective not all Uyghur ethnic group. It was designated a terrorist organization by the United Nations on September 11, 2002.

**Comment by yojhop** [comment]
So what is fxxking author doing?

**Comment by gakkossphynx** [comment]
F#ck China
