### ISSUE TITLE
不用搞阴谋,不就是想挑起我们民族之间的斗争,但我们不吃你的那一套挑拨离间，我们56个民族永远是一家！

### ISSUE THREAD

**Issue by yan-qiang** [notepad-plus-plus/notepad-plus-plus#6376]
不用搞阴谋,不就是想挑起我们民族之间的斗争,但我们不吃你的那一套挑拨离间，我们56个民族永远是一家！我们永远不欢迎民族分裂者和国家分裂者

**Comment by penghubingzhou** [comment]
别说这话了，看看GitHub吧，有多少废青站了出来，为他们的美爹说话，说起来真是寒心，袁老爷子这辈子烦的最大的错误就是让这些癌症晚期患者吃的太饱
