### ISSUE TITLE
拿个小本本记下来，武统之后拉清单

### ISSUE THREAD

**Issue by tangzhangming** [notepad-plus-plus/notepad-plus-plus#6378]

**Comment by dxp8964** [comment]
吃得起猪肉吗，怕不怕毒疫苗？可怜的工具人

**Comment by tangzhangming** [comment]
> 吃得起猪肉吗，怕不怕毒疫苗？可怜的工具人

吃不起换个党就吃得起了？换个党你们就要把全部资产送给我们，提高我们的生活水平吗？

**Comment by tangzhangming** [comment]
> 吃得起猪肉吗，怕不怕毒疫苗？可怜的工具人

你们要愿意把每年上缴50%财政收入给我国，用来提高我国人民生活水平，我们马上自己动手换个党。

**Comment by vicnoah** [comment]
> 吃得起猪肉吗，怕不怕毒疫苗？可怜的工具人

本不想回答这些言论的，奈何看不下去了，你是傻逼吧。我们是吃不起猪肉，我甚至吃不起泡菜。我们国家的事情不需要你们来评价。陈然我们的一些同胞反映比较激烈，但我认为这是没问题的在这种事情上骂你们咋啦，况且是你们先挑事。啥都不知道就在网上发布无知的言论，在中国少数名族一直都是被照顾的知道吗？完全都没来过中国，就我们吃不起泡菜我们穷得叮当响了是吧？最后我还是忍不住骂你一句傻逼。

**Comment by tangzhangming** [comment]
> 吃得起猪肉吗，怕不怕毒疫苗？可怜的工具人

换个党，你能保证我们全国人民收入水平马上翻10倍，我们也愿意换，你行吗？你那个逼样子行吗？
