### ISSUE TITLE
大陸豬不喜歡可以不用 chinese Pig get out .

### ISSUE THREAD

**Issue by jackycms** [notepad-plus-plus/notepad-plus-plus#6381]
支持notepad ++ support Notepad ++ 
你做得很對 You are doing the right thing , 
**大陸豬**不喜歡可以不用 chinese Pig get out .

**Comment by penghubingzhou** [comment]
So what？ I see a US dog  barking here. How interesting.

**Comment by lwgithub12** [comment]
滚你妈的白痴，你们倒是独立啊 你们的军队呢？

**Comment by penghubingzhou** [comment]
> 支持notepad ++ support Notepad ++
> 你做得很對 You are doing the right thing ,
> **大陸豬**不喜歡可以不用 chinese Pig get out .

and pls remember that Chinese people can't be bullied  by  anyone  or  any  country！

**Comment by pyifei** [comment]
香港狗 ，你喜欢 大陆不要依靠你的爸爸，吃你们爸爸的 喝你们爸爸的 现在还来看不起的爸爸 ，早知道这样 还不如当年把你甩到 墙上

**Comment by zhangwukong** [comment]
每天在香港小打小闹祸害自己  何必呢。求求你们闹的再大点吧，不然没没理由动手。

**Comment by LY16JAVA-zhangzhiyuan** [comment]
别搞错了，我喷你是我的言论自由啊。为什么不让我喷？我们不配感受一下言论自由吗？

**Comment by Twoearle** [comment]
动态网自由门 天安門 天安门 法輪功 李洪志 Free Tibet 六四天安門事件 The Tiananmen Square protests of 1989 天安門大屠殺 The Tiananmen Square Massacre 反右派鬥爭 The Anti-Rightist Struggle 大躍進政策 The Great Leap Forward 文化大革命 The Great Proletarian Cultural Revolution 人權 Human Rights 民運 Democratization 自由 Freedom 獨立 Independence 多黨制 Multi-party system 台灣 臺灣 Taiwan Formosa 中華民國 Republic of China 西藏 土伯特 唐古特 Tibet 達賴喇嘛 Dalai Lama 法輪功 Falun Dafa 新疆維吾爾自治區 The Xinjiang Uyghur Autonomous Region 諾貝爾和平獎 Nobel Peace Prize 劉暁波 Liu Xiaobo 民主 言論 思想 反共 反革命 抗議 運動 騷亂 暴亂 騷擾 擾亂 抗暴 平反 維權 示威游行 李洪志 法輪大法 大法弟子 強制斷種 強制堕胎 民族淨化 人體實驗 肅清 胡耀邦 趙紫陽 魏京生 王丹 還政於民 和平演變 激流中國 北京之春 大紀元時報 九評論共産黨 獨裁 專制 壓制 統一 監視 鎮壓 迫害 侵略 掠奪 破壞 拷問 屠殺 活摘器官 誘拐 買賣人口 遊進 走私 毒品 賣淫 春畫 賭博 六合彩 天安門 天安门 法輪功 李洪志 Winnie the Pooh 劉曉波动态网自由门

**Comment by ittsuu** [comment]
Yes, I know. I won't use it anymore.

But **why are you barking here?**

**Comment by austin-chang** [comment]
> 滚你妈的白痴，你们倒是独立啊 你们的军队呢？

台灣軍力全球22不用操心喔

**Comment by CPythoner** [comment]
傻狗一条，有种别用我们汉字啊，滚出中国土地！！！

**Comment by xiaolongjuan** [comment]
草泥马 赶紧滚吧你 傻逼玩意

**Comment by chnape** [comment]
用英文骂人？知道拼音shabi怎么读吗？

**Comment by Neilsons** [comment]
> > 滚你妈的白痴，你们倒是独立啊你们的军队呢？
> 
> 台湾军力全球22
你敢说你们22我就敢说我们第一

**Comment by dev8gaby9fan** [comment]
mother fucker?

**Comment by delayAdderGain** [comment]
> 别搞错了，我喷你是我的言论自由啊。为什么不让我喷？我们不配感受一下言论自由吗？

中國人連言論自由的定義都不知道喔 ? 也對, 可能你們知道的都是你們的party deluded的那套吧
freedom of speech : 
Freedom of speech is a principle that supports the freedom of an individual or a community to articulate their opinions and ideas without fear of **retaliation**, **censorship**, or **legal sanction**。(from Wikipedia)
"everyone shall have the right to freedom of expression; this right shall include freedom to seek, receive and impart information and ideas of all kinds, regardless of frontiers, either orally, in writing or in print, in the form of art, or through any other media of his choice"(UDHR)
以上是言論自由的主體喔, 也就是言論自由主要是保護公民免受其政府的迫害的喔.
但是你們翻牆中國人的**仇視/歧視/納粹言論**不在保護範圍内呢, 嘻嘻
The version of Article 19 in the ICCPR later amends this by stating that the exercise of these rights carries "special duties and responsibilities" and may "therefore be subject to certain restrictions" when necessary "[f]or respect of the rights or reputation of others" or "[f]or the protection of national security or of public order (order public), or of public health or morals"

**Comment by AnswerNo2** [comment]
杂种后代， 鬼子生的杂种后代，杂种两边不是人，就是杂种，天生的杂种

**Comment by LY16JAVA-zhangzhiyuan** [comment]
> > 别搞错了，我喷你是我的言论自由啊。为什么不让我喷？我们不配感受一下言论自由吗？
> 
> 中國人連言論自由的定義都不知道喔 ? 也對, 可能你們知道的都是你們的party deluded的那套吧
> freedom of speech :
> Freedom of speech is a principle that supports the freedom of an individual or a community to articulate their opinions and ideas without fear of **retaliation**, **censorship**, or **legal sanction**。(from Wikipedia)
> "everyone shall have the right to freedom of expression; this right shall include freedom to seek, receive and impart information and ideas of all kinds, regardless of frontiers, either orally, in writing or in print, in the form of art, or through any other media of his choice"(UDHR)
> 以上是言論自由的主體喔, 也就是言論自由主要是保護公民免受其政府的迫害的喔.
> 但是你們翻牆中國人的**仇視/歧視/納粹言論**不在保護範圍内呢, 嘻嘻
> The version of Article 19 in the ICCPR later amends this by stating that the exercise of these rights carries "special duties and responsibilities" and may "therefore be subject to certain restrictions" when necessary "[f]or respect of the rights or reputation of others" or "[f]or the protection of national security or of public order (order public), or of public health or morals"

搞了半天你也知道这些不在范围内啊，那你们这些污蔑言论也完全不在保护范围里啊

**Comment by l1712115388** [comment]
你妈妈很不错

**Comment by frostwingCN** [comment]
Go fuck yourself.

**Comment by kilimater** [comment]
你妈的香港的大傻逼

**Comment by AnswerNo2** [comment]
> 你妈的香港的大傻逼

别抬举这个越南猴子了，我们没有给他基因，他是山里的猴子，跳跳而已

**Comment by liyipenggithub** [comment]
fuck your morther's pussy in blooding,凭实力说话，傻吊，看大陆这么厉害，你酸了吧

**Comment by chnape** [comment]
社会有你这种bai lei

**Comment by chnape** [comment]
🐶Zazhong还中英文结合，以为你的大陆die们看不懂

**Comment by chnape** [comment]
Shehuidebaulei

**Comment by chenheng1998** [comment]
> > 滚你妈的白痴，你们倒是独立啊 你们的军队呢？
> 
> 台灣軍力全球22不用操心喔

哦😯？是么，那么可以扛住几轮炮火轰炸呢？？台湾海峡里狗着的美爹好像给你很大的信心？

**Comment by fsdstar** [comment]
> 支持notepad ++ support Notepad ++
> 你做得很對 You are doing the right thing ,
> **大陸豬**不喜歡可以不用 chinese Pig get out .
还用中文，当你中国爹看不懂英文？fuck get out ， go to doing the us dog in shit

**Comment by BiJim** [comment]
台湾，香港都是中国的领土，让你们这些走狗呆着就算给你们脸了，还出来哔哔？

**Comment by xxzrua** [comment]
你妈妈活不错，真棒

**Comment by lixiangzan** [comment]
> > 滚你妈的白痴，你们倒是独立啊 你们的军队呢？
> 
> 台灣軍力全球22不用操心喔

你也是真好意思说

**Comment by liyipenggithub** [comment]
> > 滚你妈的白痴，你们倒是独立啊 你们的军队呢？
> 
> 台灣軍力全球22不用操心喔

你这个傻吊，如果你不是中国人，你早特么收到东风快递了，脑子瓦特了你是
