### ISSUE TITLE
傻逼作者收了不少好处吧

### ISSUE THREAD

**Issue by daizhichao** [notepad-plus-plus/notepad-plus-plus#6382]
### Steps to Reproduce the Issue

1. 
2. 
3.

**Comment by dxp8964** [comment]
吃吧，我看着呢

**Comment by dxp8964** [comment]
到时候说一下是维尼的屎好吃还是普京的屎好吃，我好给你爹送去

**Comment by NainbowCat** [comment]
那我可以告诉你, 你吃定了.

**Comment by retmania** [comment]
又一个骗吃骗喝的

**Comment by KL3Answer** [comment]
修改记录是公开的，我们都看见了😏

**Comment by CysRoad** [comment]
有可能，之前人家美国主子发布了一个关于新疆人权的东西，呵呵。可能是收了人家经费吧

**Comment by xiaowanyingxiong** [comment]
您可真是有点智障呢

**Comment by daizhichao** [comment]
> 修改记录是公开的，我们都看见了😏

有些人理解能力有问题，或者选择性忽略一部分，没办法，只能改一下，让那些智障好理解一点
