### ISSUE TITLE
我们指望这样的作者道歉吗?

### ISSUE THREAD

**Issue by oliverchu** [notepad-plus-plus/notepad-plus-plus#6385]
正如作者 @don_ho 的Twitter所说：
1、 我從來沒喜歡過『台獨』，但我熱愛嘲弄大陸愚蠢的愛國份子。
2、中國只有一個。
台灣也只有一個。
我也許不喜歡當台灣人，但可確信的是，
我不是中國人。
3、電腦壓縮與解壓演算法套用於中文的最好例子:
咬月工交
口交肛交
4、東南亞人應是在台灣最多的外國人，但台灣人從不稱他們是『外國人』。這是理所當然的，因為大多數台灣人從不把他們當人看。
5、BTW, I'm no Chinese.

我们指望这样的作者道歉吗?

**Comment by vicnoah** [comment]
> 正如作者 @don_ho 的Twitter所说：
> 1、 我從來沒喜歡過『台獨』，但我熱愛嘲弄大陸愚蠢的愛國份子。
> 2、中國只有一個。
> 台灣也只有一個。
> 我也許不喜歡當台灣人，但可確信的是，
> 我不是中國人。
> 3、電腦壓縮與解壓演算法套用於中文的最好例子:
> 咬月工交
> 口交肛交
> 4、東南亞人應是在台灣最多的外國人，但台灣人從不稱他們是『外國人』。這是理所當然的，因為大多數台灣人從不把他們當人看。
> 5、BTW, I'm no Chinese.
> 
> 我们指望这样的作者道歉吗?

或许说这句话不合适，但我就是这么说你们回不回来跟我没关系，但你们首先挑事刻意抹黑就是不行，我就是看不惯，我就是要骂你，傻逼。
