### ISSUE TITLE
我一直很好奇你关于维族同胞那些数据是从哪里获取到的，你是否实地考察过统计过

### ISSUE THREAD

**Issue by CysRoad** [notepad-plus-plus/notepad-plus-plus#6389]
我一直很好奇你关于维族同胞那些数据是从哪里获取到的，你是否到实地考察过
还是根据别人一家之言，而在那大放厥词

你们所谓的言论自由，双标已经不是一两次了。打着言论自由的旗号做对自己有利的事，屡见不鲜

whatever，既然你们想与大陆脱钩，那就付出实际行动
和一切大陆有关的事物都断绝关系，不要用任何assembled in China，made in China的东西

**Comment by 5yph3r** [comment]
动态网自由门 天安門 天安门 法輪功 李洪志 Free Tibet 六四天安門事件 The Tiananmen Square protests of 1989 天安門大屠殺 The Tiananmen Square Massacre 反右派鬥爭 The Anti-Rightist Struggle 大躍進政策 The Great Leap Forward 文化大革命 The Great Proletarian Cultural Revolution 人權 Human Rights 民運 Democratization 自由 Freedom 獨立 Independence 多黨制 Multi-party system 台灣 臺灣 Taiwan Formosa 中華民國 Republic of China 西藏 土伯特 唐古特 Tibet 達賴喇嘛 Dalai Lama 法輪功 Falun Dafa 新疆維吾爾自治區 The Xinjiang Uyghur Autonomous Region 諾貝爾和平獎 Nobel Peace Prize 劉暁波 Liu Xiaobo 民主 言論 思想 反共 反革命 抗議 運動 騷亂 暴亂 騷擾 擾亂 抗暴 平反 維權 示威游行 李洪志 法輪大法 大法弟子 強制斷種 強制堕胎 民族淨化 人體實驗 肅清 胡耀邦 趙紫陽 魏京生 王丹 還政於民 和平演變 激流中國 北京之春 大紀元時報 九評論共産黨 獨裁 專制 壓制 統一 監視 鎮壓 迫害 侵略 掠奪 破壞 拷問 屠殺 活摘器官 誘拐 買賣人口 遊進 走私 毒品 賣淫 春畫 賭博 六合彩 天安門 天安门 法輪功 李洪志 Winnie the Pooh 劉曉波动态网自由门

**Comment by dxp8964** [comment]
三年大饥荒是不是真的？
文革是不是真的？
六四屠杀是不是真的？

强制堕胎是不是真的？
巴拿马文件是不是真的？

江苏毒疫苗事件是不是真的？
三鹿毒奶粉是不是真的？

防火墙是不是存在？
言论审查是不是存在？

共产党做的恶还不多吗？当事实不完全暴露的时候，你认为谁说的话更加可靠？

**Comment by KaitoYZ** [comment]
https://zh.wikipedia.org/wiki/新疆再教育营

> 我一直很好奇你关于维族同胞那些数据是从哪里获取到的，你是否到实地考察过
> 还是根据别人一家之言，而在那大放厥词
> 
> 你们所谓的言论自由，双标已经不是一两次了。打着言论自由的旗号做对自己有利的事，屡见不鲜
> 
> whatever，既然你们想与大陆脱钩，那就付出实际行动
> 和一切大陆有关的事物都断绝关系，不要用任何assembled in China，made in China的东西

https://en.wikipedia.org/wiki/Xinjiang_re-education_camps

**Comment by CysRoad** [comment]
> 三年大饥荒是不是真的？
> 文革是不是真的？
> 六四屠杀是不是真的？
> 
> 强制堕胎是不是真的？
> 巴拿马文件是不是真的？
> 
> 江苏毒疫苗事件是不是真的？
> 三鹿毒奶粉是不是真的？
> 
> 防火墙是不是存在？
> 言论审查是不是存在？
> 
> 共产党做的恶还不多吗？当事实不完全暴露的时候，你认为谁说的话更加可靠？

这些东西我都看过，很多政府都已经承认错误，并且处理相关人等，然后呢？
你们打着言论自由的旗号说了些啥呢？
facebook、youtube和你们意见相悖的就说被洗脑然后封杀，这就是你们的言论自由？

**Comment by BeyondTheBlade** [comment]
@dxp8964 你只挑阴暗面讲，那哪个国家没有一些黑料？

**Comment by HossainAdnan** [comment]
动态网自由门 天安門 天安门 法輪功 李洪志 Free Tibet 六四天安門事件 The Tiananmen Square protests of 1989 天安門大屠殺 The Tiananmen Square Massacre 反右派鬥爭 The Anti-Rightist Struggle 大躍進政策 The Great Leap Forward 文化大革命 The Great Proletarian Cultural Revolution 人權 Human Rights 民運 Democratization 自由 Freedom 獨立 Independence 多黨制 Multi-party system 台灣 臺灣 Taiwan Formosa 中華民國 Republic of China 西藏 土伯特 唐古特 Tibet 達賴喇嘛 Dalai Lama 法輪功 Falun Dafa 新疆維吾爾自治區 The Xinjiang Uyghur Autonomous Region 諾貝爾和平獎 Nobel Peace Prize 劉暁波 Liu Xiaobo 民主 言論 思想 反共 反革命 抗議 運動 騷亂 暴亂 騷擾 擾亂 抗暴 平反 維權 示威游行 李洪志 法輪大法 大法弟子 強制斷種 強制堕胎 民族淨化 人體實驗 肅清 胡耀邦 趙紫陽 魏京生 王丹 還政於民 和平演變 激流中國 北京之春 大紀元時報 九評論共産黨 獨裁 專制 壓制 統一 監視 鎮壓 迫害 侵略 掠奪 破壞 拷問 屠殺 活摘器官 誘拐 買賣人口 遊進 走私 毒品 賣淫 春畫 賭博 六合彩 天安門 天安门 法輪功 李洪志 Winnie the Pooh 劉曉波动态网自由门
![winnie the pooh](https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcTp7Cr_RswpP2DeITrK5gX5MBZ0QLWuMYxeg8nW0enFXWJP4hOy)

**Comment by WLyKan** [comment]
> 说维吾尔人被压迫，可能么，这些人一定没在中国大陆呆过，殊不知有句顺口溜写的“一等洋人二等官，三等少民四等汉” 谁才是被压迫的对象，恐怕不见得有，这些个狺狺狂吠之人是以何依据发表的言论，难不成让新疆地区发展成如今叙利亚的那般模样方能让你们称心如意？

**Comment by nopsg** [comment]
我来回答一下@dxp8964提出的：
三年大饥荒是不是真的？->这个是真的，政府有责任
文革是不是真的？->这个是真的，政府有责任
六四屠杀是不是真的？->有士兵牺牲，应该也有学生死亡，但不能定性为屠杀，具体内容youtube上有抹黑也有澄清

强制堕胎是不是真的？->这个是真的，计划生育
巴拿马文件是不是真的？->不清楚，无法表态

江苏毒疫苗事件是不是真的？->这个是真的，但企业问题，你故意归到政府头上
三鹿毒奶粉是不是真的？->这个是真的，同上，台湾香港欧美哪个地方没假产品？

防火墙是不是存在？->这个是真的，还好有墙，否则国内更乱。
言论审查是不是存在？->这个是真的，所以像台湾宋七力这种骗子才无法在国内生根。

共产党做的恶还不多吗？当事实不完全暴露的时候，你认为谁说的话更加可靠？->凡事看两面，回头这几10年取得的成绩还少吗？有错肯定有错，但也有功，人民有没有得到好处是最重要的。

引用一位新加坡议员的话：
“35 年来，它协助超过 5 至 6 亿人口脱离贫困。历史上没有任何一个国家做到这
点。没有任何国家能够在 35 年内做到。
这是一个巨大的成就，却没得到应有的认可。
这样的成就能在其他任何制度下实现吗？中国领导人还会提到中国
人民的福祉。世上是否有另一个政治制度，能够比现有的制度更好
地造福中国人民？
有哪一个制度能够做到？
你能举出一个例子吗？
”
引用出处：新加坡政府网站https://app.mlaw.gov.sg/news/others/minister-for-law-and-minister-for-home-affairs-k-shanmugam-response-to-questions-from-scmp-and-zb-on-his-views-on-the-situation-in-hk，新闻下边有中英文稿。
