### ISSUE TITLE
https://zh.wikipedia.org/wiki/新疆再教育营

### ISSUE THREAD

**Issue by CysRoad** [notepad-plus-plus/notepad-plus-plus#6399]
https://zh.wikipedia.org/wiki/新疆再教育营

> 我一直很好奇你关于维族同胞那些数据是从哪里获取到的，你是否到实地考察过
> 还是根据别人一家之言，而在那大放厥词
> 
> 你们所谓的言论自由，双标已经不是一两次了。打着言论自由的旗号做对自己有利的事，屡见不鲜
> 
> whatever，既然你们想与大陆脱钩，那就付出实际行动
> 和一切大陆有关的事物都断绝关系，不要用任何assembled in China，made in China的东西

https://en.wikipedia.org/wiki/Xinjiang_re-education_camps

_Originally posted by @KaitoYZ in https://github.com/notepad-plus-plus/notepad-plus-plus/issues/6389#issuecomment-547777002_

你发的这个网站我早看过了，有什么可以考证的呢？要不我给你开发一个关于蔡English各种内幕的网站，你相信么

**Comment by assad2008** [comment]
相信维基这些，鬼才信呢，一群被假新闻蒙蔽的人编写的维基，你也信？

**Comment by KaitoYZ** [comment]
下方的參考文獻也都看完了？
不信的話換個例子，你信不信北韓存在集中營？

**Comment by iamtangxin** [comment]
极端宗教思想带来的危害，台湾没有切身体会，所以你们无法理解。如果类似的事件有一起发生在台湾，你们会作何感想？
https://zh.wikipedia.org/wiki/%E4%B9%8C%E9%B2%81%E6%9C%A8%E9%BD%90%E4%B8%83%E4%BA%94%E4%BA%8B%E4%BB%B6
https://zh.wikipedia.org/wiki/2014%E5%B9%B4%E6%98%86%E6%98%8E%E7%81%AB%E8%BD%A6%E7%AB%99%E6%9A%B4%E5%8A%9B%E6%81%90%E6%80%96%E8%A2%AD%E5%87%BB%E4%BA%8B%E4%BB%B6

**Comment by RuiCMU** [comment]
某些人就别再闹了吧，闹得上个github挂梯子上传代码都不稳定
