### ISSUE TITLE
x64 Build

### ISSUE THREAD

**Issue by NN---** [notepad-plus-plus/notepad-plus-plus#64]
I have started porting Notepad++ to 64-bit.
If you have any comments I would like to hear.

The repository is located here
https://github.com/NN---/notepad-plus-plus

Thanks.

**Comment by ariccio** [comment]
Why are you maintaining a separate repo? It's going to get out of sync pretty quickly, thus, any PRs that you may want to open will be very *large*, and therefore less likely to be merged!

**Comment by NN---** [comment]
I just don't know how to make it simpler.
If I get commit access to this repository , I can commit directly here.

**Comment by MAPJe71** [comment]
1. create your fork of Don Ho's Notepad-plus-plus repository;
2. apply changes to a working copy of your fork;
3. commit those changes to your fork;
4. create a pull-request for Don Ho's Notepad-plus-plus repository;
5. wait for Don Ho to pull i.e. merge your proposed changes into his repository;

**Comment by NN---** [comment]
@MAPJe71 This what I am doing right now :)
I am going to create small pull requests to have changes iteratively.

**Comment by bviktor** [comment]
I've published some barebone builds here:

https://github.com/bviktor/npp64

Hopefully you'll provide official 64 bit builds eventually. Thanks for the patches so far.

**Comment by donho** [comment]
@bviktor have you build Scitilla x64 with boost?

**Comment by bviktor** [comment]
Haven't looked into that yet, would that be useful for you? I could try sometime.

**Comment by donho** [comment]
@bviktor Thank you. It's not necessary now.
I managed to make Scintilla 64 bit compile with boost.
I'll commit the fix and instruction (readme.md) this evening.

**Comment by bviktor** [comment]
That's pretty sweet, thanks! Does this mean we'll have an x64 build with the next release? Then it may be a good time to call it 7.0.0 :)
