### ISSUE TITLE
'View -> Summary' doesn't count words correctly

### ISSUE THREAD

**Issue by Eldaw** [notepad-plus-plus/notepad-plus-plus#640]
If I type these 2 lines of text:

one two
three

and then go to 'View -> Summary...' it tells me there are 2 lines and 2 words. Surely it should say 2 lines and 3 words.

By comparison, the Word Count feature in the TextFX plugin correctly identifies 2 lines and 3 words.

**Comment by dail8859** [comment]
Further info: looks like the regex to find words doesn't pick up on words with a newline after them.
