### ISSUE TITLE
我已向工信部举报github.com支持新疆！抵制辱华企业，抵制辱华软件从我做起！

### ISSUE THREAD

**Issue by throwaway199** [notepad-plus-plus/notepad-plus-plus#6400]
虽然咱治不了nba,还治不了你一个破免费软件吗？

不止notepad++支持新疆,还有go语言主要开发者支持港独！而go语言明目张胆放在github上，说明github已沦为cia的政治工具，我已向工信部提交投诉举报，同时我已举报：
csdn.com 罪状：明目张胆发布go教程
stackoverflow 罪状：竟然不删除go和notepad相关问题
leetcode.com 罪状：敢支持使用go语言，该杀

这些可恶的美国人以为用免费软件就可以控制中国，谁能想到，没有google我们有百度，没有go我们有e语言，没有github我们有gitee，没有chrome我们有360，坚定支持政府打压境外发动势力，谁敢反对我举报非法境外网站，送你一句：你们这些牧羊犬，不上美国网站你会死？不爱用别用，用你美国爹的东西去！

**Comment by Twoearle** [comment]
动态网自由门 天安門 天安门 法輪功 李洪志 Free Tibet 六四天安門事件 The Tiananmen Square protests of 1989 天安門大屠殺 The Tiananmen Square Massacre 反右派鬥爭 The Anti-Rightist Struggle 大躍進政策 The Great Leap Forward 文化大革命 The Great Proletarian Cultural Revolution 人權 Human Rights 民運 Democratization 自由 Freedom 獨立 Independence 多黨制 Multi-party system 台灣 臺灣 Taiwan Formosa 中華民國 Republic of China 西藏 土伯特 唐古特 Tibet 達賴喇嘛 Dalai Lama 法輪功 Falun Dafa 新疆維吾爾自治區 The Xinjiang Uyghur Autonomous Region 諾貝爾和平獎 Nobel Peace Prize 劉暁波 Liu Xiaobo 民主 言論 思想 反共 反革命 抗議 運動 騷亂 暴亂 騷擾 擾亂 抗暴 平反 維權 示威游行 李洪志 法輪大法 大法弟子 強制斷種 強制堕胎 民族淨化 人體實驗 肅清 胡耀邦 趙紫陽 魏京生 王丹 還政於民 和平演變 激流中國 北京之春 大紀元時報 九評論共産黨 獨裁 專制 壓制 統一 監視 鎮壓 迫害 侵略 掠奪 破壞 拷問 屠殺 活摘器官 誘拐 買賣人口 遊進 走私 毒品 賣淫 春畫 賭博 六合彩 天安門 天安门 法輪功 李洪志 Winnie the Pooh 劉曉波动态网自由门

**Comment by seamounts** [comment]
> 动态网自由门 天安門 天安门 法輪功 李洪志 Free Tibet 六四天安門事件 The Tiananmen Square protests of 1989 天安門大屠殺 The Tiananmen Square Massacre 反右派鬥爭 The Anti-Rightist Struggle 大躍進政策 The Great Leap Forward 文化大革命 The Great Proletarian Cultural Revolution 人權 Human Rights 民運 Democratization 自由 Freedom 獨立 Independence 多黨制 Multi-party system 台灣 臺灣 Taiwan Formosa 中華民國 Republic of China 西藏 土伯特 唐古特 Tibet 達賴喇嘛 Dalai Lama 法輪功 Falun Dafa 新疆維吾爾自治區 The Xinjiang Uyghur Autonomous Region 諾貝爾和平獎 Nobel Peace Prize 劉暁波 Liu Xiaobo 民主 言論 思想 反共 反革命 抗議 運動 騷亂 暴亂 騷擾 擾亂 抗暴 平反 維權 示威游行 李洪志 法輪大法 大法弟子 強制斷種 強制堕胎 民族淨化 人體實驗 肅清 胡耀邦 趙紫陽 魏京生 王丹 還政於民 和平演變 激流中國 北京之春 大紀元時報 九評論共産黨 獨裁 專制 壓制 統一 監視 鎮壓 迫害 侵略 掠奪 破壞 拷問 屠殺 活摘器官 誘拐 買賣人口 遊進 走私 毒品 賣淫 春畫 賭博 六合彩 天安門 天安门 法輪功 李洪志 Winnie the Pooh 劉曉波动态网自由门

去你妈的邪教组织

**Comment by vicnoah** [comment]
哪来的吃里扒外的东西

**Comment by lonelyparasol** [comment]
傻逼，作者的错怪github，脑子有坑？

**Comment by c88tm** [comment]
沒有言論自由我們有自我審查！

**Comment by throwaway199** [comment]
@lonelyparasol 你这个境外美分狗，竟然给github说好话，等于你也是cia间谍吧？

**Comment by fwhezfwhez** [comment]
如果github没有足够好的审查机制，可能真的会把github墙掉。

**Comment by NainbowCat** [comment]
支持! github这些港独台独分子不堪入目, 为了不让我国人民的纯洁心灵遭到污染, 请求屏蔽全部境外网站. 我们有微博微信, 没有这些垃圾东西会更开心!

**Comment by anziguoer** [comment]
傻x， 在中国做软件开发本就就不是一件容易的事情，╮(╯▽╰)╭

**Comment by lonelyparasol** [comment]
@throwaway199 你用的东西有多少是外国的？包括你现在用的电脑手机，基带芯片全是外国的，错的是人，不是工具，按你说，刀杀了人，你拿刀问罪有屁用

**Comment by throwaway199** [comment]
@lonelyparasol

**Comment by delayAdderGain** [comment]
好支持威武! 反賊, 美分,粉紅罕見一致達成共識全票通過 ! 鼓掌 ！

**Comment by NainbowCat** [comment]
> @throwaway199 你用的东西有多少是外国的？包括你现在用的电脑手机，基带芯片全是外国的，错的是人，不是工具，按你说，刀杀了人，你拿刀问罪有屁用

github、微软、美国包庇犯罪分子 应该按照共犯处理

**Comment by caoler** [comment]
哈哈哈哈，好钓

**Comment by delayAdderGain** [comment]
> 傻逼，作者的错怪github，脑子有坑？

**你妈死了**, github让这种作者堂而皇之在自己的平臺上乳华, 明显就是github自己有问题, 就像地图事件我们中国人抵制的是迪奥不是它的员工一样阿

**Comment by KaitoYZ** [comment]
我大天朝终会彻底独立于世界，成为二十一世纪最成功的锁国国家！
Make China Great Again!!

**Comment by dxp8964** [comment]
> > 傻逼，作者的错怪github，脑子有坑？
> 
> **你妈死了**, github让这种作者堂而皇之在自己的平臺上乳华, 明显就是github自己有问题, 就像地图事件我们中国人抵制的是迪奥不是它的员工一样阿

美国众议院前几天无异议的通过了《香港人权与民主法案》，建议你抵制整个美国哦。

**Comment by ShawnJim** [comment]
少发表这些nc言论，言论自由观点自由但是不代表能随意抹黑

**Comment by xiaolf** [comment]
坚决支持 赶紧把github封了 猴子奸笑

**Comment by michaellee8** [comment]
強烈呼籲偉光正的 gfw 趕快封掉 github，保護自由世界網絡環境
I would like to hereby urge the GFW to ban GitHub immediately to protect the free Internet.

**Comment by fwhezfwhez** [comment]
我也感觉是反串，并且这两个人也特别有意思。
你们看看这个链接：
https://github.com/notepad-plus-plus/notepad-plus-plus/issues/6430

然后再看看最近的几个issue，这几个人是一个团体，在抱团反串呢。

**Comment by 971389117** [comment]
不用怀疑，这几个人就是反串，正常有脑子的人都不会这么说话。

**Comment by zj299792458** [comment]
> 不用怀疑，这几个人就是反串，正常有脑子的人都不会这么说话。

外面不都是这么说话的人么😂

**Comment by Rinacm** [comment]
激寒反串博眼球打咩得死，，，github上也无多少人会关注激寒反串啊

**Comment by infoabcd** [comment]
emmmm

**Comment by weihe0** [comment]
GitHub现在是微软旗下的网站，微软必须就此道歉，并封杀软件作者，不然就等着被工信部封杀吧！微软在中国赚的钱，比NBA在中国赚的钱多得多，治不了NBA还治不了微软么？

**Comment by lolideshita** [comment]
楼主好好看文章内容了吗？如果看了，那楼主看来没有否认文中的事实。所以在这个前提下，楼主难道认为新疆人不是中国人？新疆人均暴徒？他们就该进集中营？如果这样，楼主就是活脱脱的汉族种族极端主义人士，和迫害犹太人的纳粹份子毫无区别！
这段时间，你们这些被洗脑、没有自己思想的人，说香港游行民众是港独，说新疆人均暴徒，你们清楚他们的境遇吗？香港游行民众的五大诉求中没有独立，你们知道吗？新疆大部分只是正常生活的平民，你们知道吗？不！你们只会人云亦云！而且你们是可悲的，因为你们所处的环境让你们无法接受不同意见，只能乖乖接受你的主子们允许的言论，导致你们被彻底洗脑成一个看见敏感词就开启无脑战狼的奴隶！

**Comment by MidoriG** [comment]
在Github还能看到这么爱国的同胞，真的不容易！我观察很久了，国人毫无在反动网站的自觉，对如此多辱华的信息视若无睹，国家早该整治这帮卖国贼了！
