### ISSUE TITLE
台湾人民被洗脑了，好可怜

### ISSUE THREAD

**Issue by seamounts** [notepad-plus-plus/notepad-plus-plus#6401]
### Steps to Reproduce the Issue

1. 
2. 
3.

**Comment by AnswerNo2** [comment]
很多弯弯的祖宗都是小日本，是杂种，鬼子的后代，你不知道吗

**Comment by AnswerNo2** [comment]
跟香港那帮废物一样，只不过香港那帮废物是越南猴子罢了

**Comment by chingchong2** [comment]
动态网自由门 天安門 天安门 法輪功 李洪志 Free Tibet 六四天安門事件 The Tiananmen Square protests of 1989 天安門大屠殺 The Tiananmen Square Massacre 反右派鬥爭 The Anti-Rightist Struggle 大躍進政策 The Great Leap Forward 文化大革命 The Great Proletarian Cultural Revolution 人權 Human Rights 民運 Democratization 自由 Freedom 獨立 Independence 多黨制 Multi-party system 台灣 臺灣 Taiwan Formosa 中華民國 Republic of China 西藏 土伯特 唐古特 Tibet 達賴喇嘛 Dalai Lama 法輪功 Falun Dafa 新疆維吾爾自治區 The Xinjiang Uyghur Autonomous Region 諾貝爾和平獎 Nobel Peace Prize 劉暁波 Liu Xiaobo 民主 言論 思想 反共 反革命 抗議 運動 騷亂 暴亂 騷擾 擾亂 抗暴 平反 維權 示威游行 李洪志 法輪大法 大法弟子 強制斷種 強制堕胎 民族淨化 人體實驗 肅清 胡耀邦 趙紫陽 魏京生 王丹 還政於民 和平演變 激流中國 北京之春 大紀元時報 九評論共産黨 獨裁 專制 壓制 統一 監視 鎮壓 迫害 侵略 掠奪 破壞 拷問 屠殺 活摘器官 誘拐 買賣人口 遊進 走私 毒品 賣淫 春畫 賭博 六合彩 天安門 天安门 法輪功 李洪志 Winnie the Pooh 劉曉波动态网自由门

**Comment by BeyondTheBlade** [comment]
呆湾自以为还能和我们平等对话，其实靠的都是美国爹。没美国撑腰，早就没了，还在那装呢。

**Comment by AnswerNo2** [comment]
> 呆湾自以为还能和我们平等对话，其实靠的都是美国爹。没美国撑腰，早就没了，还在那装呢。

你别闹，美国给呆湾弯撑腰？  你认为可能吗?  弯弯现在本来就是一个孤儿存在，只不过我们现在还有很多事要做罢了，还没到时间赶走这帮杂种到鬼子那里去

**Comment by chentotal** [comment]
中國人民好可憐,沒有腦可以被洗

**Comment by BeyondTheBlade** [comment]
@AnswerNo2 保护条约，要武统美国航母就过来了，第三次世界大战就打了。呆湾现在就是一个棋子，他们民众却不自知，自以为地位很高。中美博弈的一个棋子，哪天战争爆发就会变成弃子。

**Comment by seamounts** [comment]
> 中國人民好可憐,沒有腦可以被洗

其实没什么好吵的，骂来骂去有啥意思。

**Comment by AnswerNo2** [comment]
> @AnswerNo2 保护条约，要武统美国航母就过来了，第三次世界大战就打了。呆湾现在就是一个棋子，他们民众却不自知，自以为地位很高。中美博弈的一个棋子，哪天战争爆发就会变成弃子。

你以为美国真的会来？？你别逗了，菜狗如果跑到没过去，美国都不一定会收留这条狗

**Comment by CysRoad** [comment]
> 中國人民好可憐,沒有腦可以被洗

灣灣現在跟戰前的敘利亞沒什麽兩樣，如果中國和美國開戰，那棋盤就是灣灣呵呵

**Comment by daizhichao** [comment]
> 中國人民好可憐,沒有腦可以被洗

哟，不错，还知道我们是中国人啊，蒋介石虽然跟我们党派不同，但是也算是中国的革命家，他要是知道你们这群子孙搞台独，不知道会不会被气死

**Comment by teacherzack** [comment]
台湾人和香港人，来大陆生活一段时间，刷新一下认知。真的，只要是媒体，报道就是有倾向性的。不要相信任何媒体，亲自来感受一下才是王道。

**Comment by xjy12345654** [comment]
我也搞不懂台湾反大陆咋想的？面对恐怖暴力分子的时候还在谈人权？ 恐怖袭击的视频只是太玻璃血腥就被禁了.你伤害了别人，危害了社会就别再谈什么人权了要付出代价的。台湾整天被打砸抢烧会不管吗？叙利亚，伊拉克，利比亚现在的满目疮痍，难民谁造成的？可笑的台湾啊！ 给美国当马前卒，中国变虚弱，东南亚会变成另一个中东而已！ 利比亚，伊拉克 ，日本都是美国盟友，看看都对盟友做了啥？轰炸，胁迫签广场协议。与虎谋皮渣渣都不剩

**Comment by liuem** [comment]
我清楚弯的事由后也觉得有点可怜，他们变成这样几乎是注定的，因为教科书的历史就被修改了。要将人聚集在一起必定是要有交集的，小聚是家/村/县(老乡)，大聚就是国家/民族(国人)，要想将更多的人聚集在一起就要靠文化和宗教了(华人)。他们从小就被教育和我们不同，现在的巨大分歧在既得利益者改写教科书的时候就已经注定。说什么要用英语的也没必要，软件作者是台湾的，交流也就国人和对岸之间就可以了。
他们现在也很难受，个别人知道自己是个棋子又能怎么办，从小被教育的思想是很难改变的，要闹独立又没资本，只能整天打嘴炮了。
