### ISSUE TITLE
Not sure why my fellow westerners are hating on China so much.

### ISSUE THREAD

**Issue by toneillAU** [notepad-plus-plus/notepad-plus-plus#6419]
Taiwan, the Republic of China, is a great place!

**Comment by liuen12** [comment]
You're looking for a sense of being here.

**Comment by w33b** [comment]
"my fellow westerners"
Either your autistic, or a foreign shill.
Im going to bet the latter. 
Go fucking die stupid chink (no offense to any of the HKers out there, fuck china)

**Comment by penghubingzhou** [comment]
Not hating, but division

**Comment by penghubingzhou** [comment]
> "my fellow westerners"
> Either your autistic, or a foreign shill.
> Im going to bet the latter.
> Go fucking die stupid chink (no offense to any of the HKers out there, fuck china)

if you are a madman，then go home; if you are a normal man, pls shut up your sheep fucked mouth.

**Comment by w33b** [comment]
> > "my fellow westerners"
> > Either your autistic, or a foreign shill.
> > Im going to bet the latter.
> > Go fucking die stupid chink (no offense to any of the HKers out there, fuck china)
> 
> if you are a madman，then go home; if you are a normal man, pls close your sheep fucked mouth.

What? That was a nonsense phrase

**Comment by toneillAU** [comment]
> 
> 
> "my fellow westerners"
> Either your autistic, or a foreign shill.
> Im going to bet the latter.
> Go fucking die stupid chink (no offense to any of the HKers out there)

Retard alert
How do you miss a joke so simple

**Comment by dongyingt** [comment]
一个家庭和睦，团结一致，你们会变得强大，没人敢欺负你们。但是有人害怕这样的你们，想把你的孩子洗脑，让你的家庭分裂，他们才能乘虚而入，搞你们。想想这个坏蛋到底是谁？

**Comment by w33b** [comment]
> > "my fellow westerners"
> > Either your autistic, or a foreign shill.
> > Im going to bet the latter.
> > Go fucking die stupid chink (no offense to any of the HKers out there)
> 
> Retard alert
> How do you miss a joke so simple
 cause ive been spammed by google translate Chinese shills all day that sound like that lol.

**Comment by michaellee8** [comment]
@toneillAU i guess you understand it now. Sigh

**Comment by Paraesthetic** [comment]
> > "my fellow westerners"
> > Either your autistic, or a foreign shill.
> > Im going to bet the latter.
> > Go fucking die stupid chink (no offense to any of the HKers out there, fuck china)
> 
> if you are a madman，then go home; if you are a normal man, pls close your sheep fucked mouth.

You can't even speak english you worthless piece of human garbage

**Comment by Mysakura** [comment]
是中国人吗？是的话请说中文。既然你的西方同胞都讨厌中国，那么中国大地上这么多的外国人哪里来的？还有，既然讨厌中国，那就退出中国国籍，看有没有洋大人收留你这个汉奸叛徒。最后，敢做不敢当就是你吧，把你的真实身份亮出来，让我们看看你是什么品种的狗杂种

**Comment by toneillAU** [comment]
> > > "my fellow westerners"
> > > Either your autistic, or a foreign shill.
> > > Im going to bet the latter.
> > > Go fucking die stupid chink (no offense to any of the HKers out there)
> > 
> > 
> > Retard alert
> > How do you miss a joke so simple
> 
> cause ive been spammed by google translate Chinese shills on twitter all day that sound like that lol.

Pro-tip: Real Chinese people won't ever mention Taiwan as the Republic of China.
