### ISSUE TITLE
Implement ANTLR syntax highlight

### ISSUE THREAD

**Issue by KvanTTT** [notepad-plus-plus/notepad-plus-plus#642]
Should be like this (from ANTLR Idea plugin):

![antlr syntax highlight](https://cloud.githubusercontent.com/assets/1150330/9064293/8475bae6-3ad4-11e5-8b52-84d74dfe2b80.png)

**Comment by Skyost** [comment]
:+1:

**Comment by donho** [comment]
If it's been added in Scintilla, then it'll be in Notepad++.
Otherwise you can use UDL system.
