### ISSUE TITLE
SciLexer.dll blocked by antivirus

### ISSUE THREAD

**Issue by nanakiwurtz** [notepad-plus-plus/notepad-plus-plus#643]
I used BitDefender as my anti virus program and it detects SciLexer.dll as `Gen:Variant.Adware.Kazy.444386`
(NPP v6.8.1)

**Comment by ariccio** [comment]
Upload it to [VirusTotal](https://www.virustotal.com/)?

**Comment by nanakiwurtz** [comment]
@ariccio The result is clean, but I wonder why my AV blocked that file anyway...

**Comment by ariccio** [comment]
Eh, well that's kooky. Close this issue? Open a false positive with BitDefender?
