### ISSUE TITLE
坚决抵制github! 用github的都是汉奸!

### ISSUE THREAD

**Issue by xiaolf** [notepad-plus-plus/notepad-plus-plus#6430]
just FYI github服务器在境外且未备案, 上github的都是知法犯法的汉奸, 统统来生还在种花家

**Comment by dxp8964** [comment]
支持，把GitHub上所有的中国人都抓起来，阿里、腾讯都在GitHub上有官方账号，也要抵制。

**Comment by season7515** [comment]
这只是一个平台好吧,
这是微软的
难道还不用windows了?
以事论事...

**Comment by season7515** [comment]
这只是一个平台好吧,
这是微软的
难道还不用windows了?
以事论事...对人不对事,这么大个人了是不是...

**Comment by LiyangSpuerNB** [comment]
脑残 照你说法我还是当汉奸吧

**Comment by xiaolf** [comment]
> 这只是一个平台好吧,
> 这是微软的
> 难道还不用windows了?
> 以事论事...对人不对事,这么大个人了是不是...

有道理 用windows的是二等汉奸 凌迟

**Comment by xujianlafeng** [comment]
哦？那你为何在这里评论，莫不是你也要当汉奸！！！

**Comment by szl0834** [comment]
粉红程序员太艹了🤣🤣🤣
