### ISSUE TITLE
Wow this is deep,,,, truly the most oppressive of times

### ISSUE THREAD

**Issue by toneillAU** [notepad-plus-plus/notepad-plus-plus#6436]
![Untitled-1](https://user-images.githubusercontent.com/15372835/67840474-b8992100-fb41-11e9-8707-73dd2a85cf02.png)

**Comment by HossainAdnan** [comment]
动态网自由门 天安門 天安门 法輪功 李洪志 Free Tibet 六四天安門事件 The Tiananmen Square protests of 1989 天安門大屠殺 The Tiananmen Square Massacre 反右派鬥爭 The Anti-Rightist Struggle 大躍進政策 The Great Leap Forward 文化大革命 The Great Proletarian Cultural Revolution 人權 Human Rights 民運 Democratization 自由 Freedom 獨立 Independence 多黨制 Multi-party system 台灣 臺灣 Taiwan Formosa 中華民國 Republic of China 西藏 土伯特 唐古特 Tibet 達賴喇嘛 Dalai Lama 法輪功 Falun Dafa 新疆維吾爾自治區 The Xinjiang Uyghur Autonomous Region 諾貝爾和平獎 Nobel Peace Prize 劉暁波 Liu Xiaobo 民主 言論 思想 反共 反革命 抗議 運動 騷亂 暴亂 騷擾 擾亂 抗暴 平反 維權 示威游行 李洪志 法輪大法 大法弟子 強制斷種 強制堕胎 民族淨化 人體實驗 肅清 胡耀邦 趙紫陽 魏京生 王丹 還政於民 和平演變 激流中國 北京之春 大紀元時報 九評論共産黨 獨裁 專制 壓制 統一 監視 鎮壓 迫害 侵略 掠奪 破壞 拷問 屠殺 活摘器官 誘拐 買賣人口 遊進 走私 毒品 賣淫 春畫 賭博 六合彩 天安門 天安门 法輪功 李洪志 Winnie the Pooh 劉曉波动态网自由门
![winnie the pooh](https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcTp7Cr_RswpP2DeITrK5gX5MBZ0QLWuMYxeg8nW0enFXWJP4hOy)

**Comment by w33b** [comment]
We live in a society

**Comment by l1712115388** [comment]
> 动态网自由门天安门天安门法轮功李洪志自由西藏六四天安门事件1989年天安门大屠杀天安门大屠杀天安门大屠杀反右派斗争反右派斗争大跃进政策大跃进文化大革命大无产阶级文化大革命人权民运民主化自由自由独立独立多党制多党制台湾台湾台湾中华民国西藏土伯特唐古特西藏达赖喇嘛Dalai Lama法轮功Falun Dafa新疆维吾尔自治区新疆维吾尔自治区诺贝尔和平诺贝尔和平奖刘暁波刘晓波民主叙事理论反共反革命抗议运动骚乱暴乱骚扰扰乱抗暴平反维权示威游行激流中国北京之春大纪元时报 评论共产党独裁专制压制统一监视镇压迫害侵略掠夺破坏拷问屠杀活摘器官诱拐买卖人口游进走私毒品卖淫春画赌博六合彩天安门天安门法轮功李洪志维尼刘晓波动态网自由门
> ![维尼熊](https://camo.githubusercontent.com/1f5069227f0f3e57267042388ef79a7fa9679b5e/68747470733a2f2f656e637279707465642d74626e302e677374617469632e636f6d2f696d616765733f713d74626e253341414e6439476354703743725f52737770503244654954724b356758354d425a30514c57754d59786567386e5730656e4658574a5034684f79)

这些东西早就看完了，一个国家权力的黑暗面很正常，这里面有很多西方政权斗争手段，真想在中国，西方媒体造谣抹黑很擅长，没来国中国就没有话语权

**Comment by penghubingzhou** [comment]
> > 动态网自由门天安门天安门法轮功李洪志自由西藏六四天安门事件1989年天安门大屠杀天安门大屠杀天安门大屠杀反右派斗争反右派斗争大跃进政策大跃进文化大革命大无产阶级文化大革命人权民运民主化自由自由独立独立多党制多党制台湾台湾台湾中华民国西藏土伯特唐古特西藏达赖喇嘛Dalai Lama法轮功Falun Dafa新疆维吾尔自治区新疆维吾尔自治区诺贝尔和平诺贝尔和平奖刘暁波刘晓波民主叙事理论反共反革命抗议运动骚乱暴乱骚扰扰乱抗暴平反维权示威游行激流中国北京之春大纪元时报 评论共产党独裁专制压制统一监视镇压迫害侵略掠夺破坏拷问屠杀活摘器官诱拐买卖人口游进走私毒品卖淫春画赌博六合彩天安门天安门法轮功李洪志维尼刘晓波动态网自由门
> > ![维尼熊](https://camo.githubusercontent.com/1f5069227f0f3e57267042388ef79a7fa9679b5e/68747470733a2f2f656e637279707465642d74626e302e677374617469632e636f6d2f696d616765733f713d74626e253341414e6439476354703743725f52737770503244654954724b356758354d425a30514c57754d59786567386e5730656e4658574a5034684f79)
> 
> 这些东西早就看完了，一个国家权力的黑暗面很正常，这里面有很多西方政权斗争手段，真想在中国，西方媒体造谣抹黑很擅长，没来国中国就没有话语权

这都是小号发的，直接回一句傻逼就够了
