### ISSUE TITLE
在反华的人眼里，发现一件事能祸乱中国时，它们举起了人权的幌子。

### ISSUE THREAD

**Issue by eoser** [notepad-plus-plus/notepad-plus-plus#6438]

**Comment by howawong** [comment]
5 demands, not one less.

**Comment by HossainAdnan** [comment]
https://ching.chong/GayChina.png&size=动态网自由门天安門天安门法輪功李洪志FreeTibet六四天安門事件TheTiananmenSquareprotestsof1989天安門大屠殺TheTiananmenSquareMassacre反右派鬥爭TheAnti-RightistStruggle大躍進政策TheGreatLeapForward文化大革命TheGreatProletarianCulturalRevolution人權HumanRights民運Democratization自由Freedom獨立Independence多黨制Multi-partysystem台灣臺灣TaiwanFormosa中華民國RepublicofChina西藏土伯特唐古特Tibet達賴喇嘛DalaiLama法輪功FalunDafa新疆維吾爾自治區TheXinjiangUyghurAutonomousRegion諾貝爾和平獎NobelPeacePrize劉暁波LiuXiaobo民主言論思想反共反革命抗議運動騷亂暴亂騷擾擾亂抗暴平反維權示威游行李洪志法輪大法大法弟子強制斷種強制堕胎民族淨化人體實驗肅清胡耀邦趙紫陽魏京生王丹還政於民和平演變激流中國北京之春大紀元時報九評論共産黨獨裁專制壓制統一監視鎮壓迫害侵略掠奪破壞拷問屠殺活摘器官誘拐買賣人口遊進走私毒品賣淫春畫賭博六合彩天安門天安门法輪功李洪志WinniethePooh劉曉波动态网自由门
