### ISSUE TITLE
为了中国的领土完整，打击反华势力，请和我一起投诉全球最大反华网站github.com!

### ISSUE THREAD

**Issue by throwaway199** [notepad-plus-plus/notepad-plus-plus#6442]
github赚中国人的钱还敢骂中国，现在我会一一点评它的罪状
九评github:
1. 允许反华势力上传最大反动仓库zhao
2. 默许保留造谣repo Xin-Yue
3. 保留996 repo,通过造谣中国劳动现状负面影响中国经济，用心险恶
4. 保留辱华语言golang
5. 保留gfw list,允许网民对伟大防火墙的元勋恶语相对
6. 通过垄断恶意打击中国自主网站gitee
7. 保留诸多外国势力的免费开源软件，和cia和ned串通打压中国自主科技创新
8. 允许go语言repo删除中国用户评论，打击中国言论自由
9. 给中国大陆穿小鞋，间歇性不让中国人登陆

**Comment by penghubingzhou** [comment]
你投诉它是不可能的，人家服务器在国外，又不可能服从你中国法律

**Comment by chenheng1998** [comment]
我觉得你是故意挑起矛盾。炮火转移到GitHub？

**Comment by NainbowCat** [comment]
白宫请愿, 10w人白宫就必须回应. 以咱们爱国群众的力量100w人不都是小事一桩么
哦, 对了, 那个情愿的网站被gfw ban了, 记得自备梯子哦

**Comment by xiaolf** [comment]
坚决支持, 上github的都是汉奸

**Comment by michaellee8** [comment]
坚决支持

Fully supported

**Comment by GuDuYing** [comment]
> 我觉得你是故意挑起矛盾。炮火转移到GitHub？

同意你的看法。太多反串黑了。

**Comment by dxp8964** [comment]
赶紧ban了吧，这样小粉红就少了很多

**Comment by NainbowCat** [comment]
> 我觉得你是故意挑起矛盾。炮火转移到GitHub？

github包庇台独港独分子, 国内任何一个网站敢这样活不到今天晚上, 你现在跟我说github跟着没关系? 是时候让美国人尝尝社会主义的力量了!

**Comment by wotupset** [comment]
中華民國才是唯一正統中國

![1570674718332](https://user-images.githubusercontent.com/4385327/67841478-21c56800-fb33-11e9-8f52-2d24e32c2ff7.jpg)

**Comment by nxSlow** [comment]
你反串黑nm呢？脑残傻逼

**Comment by HossainAdnan** [comment]
https://ching.chong/GayChina.png&size=动态网自由门天安門天安门法輪功李洪志FreeTibet六四天安門事件TheTiananmenSquareprotestsof1989天安門大屠殺TheTiananmenSquareMassacre反右派鬥爭TheAnti-RightistStruggle大躍進政策TheGreatLeapForward文化大革命TheGreatProletarianCulturalRevolution人權HumanRights民運Democratization自由Freedom獨立Independence多黨制Multi-partysystem台灣臺灣TaiwanFormosa中華民國RepublicofChina西藏土伯特唐古特Tibet達賴喇嘛DalaiLama法輪功FalunDafa新疆維吾爾自治區TheXinjiangUyghurAutonomousRegion諾貝爾和平獎NobelPeacePrize劉暁波LiuXiaobo民主言論思想反共反革命抗議運動騷亂暴亂騷擾擾亂抗暴平反維權示威游行李洪志法輪大法大法弟子強制斷種強制堕胎民族淨化人體實驗肅清胡耀邦趙紫陽魏京生王丹還政於民和平演變激流中國北京之春大紀元時報九評論共産黨獨裁專制壓制統一監視鎮壓迫害侵略掠奪破壞拷問屠殺活摘器官誘拐買賣人口遊進走私毒品賣淫春畫賭博六合彩天安門天安门法輪功李洪志WinniethePooh劉曉波动态网自由门
动态网自由门 天安門 天安门 法輪功 李洪志 Free Tibet 六四天安門事件 The Tiananmen Square protests of 1989 天安門大屠殺 The Tiananmen Square Massacre 反右派鬥爭 The Anti-Rightist Struggle 大躍進政策 The Great Leap Forward 文化大革命 The Great Proletarian Cultural Revolution 人權 Human Rights 民運 Democratization 自由 Freedom 獨立 Independence 多黨制 Multi-party system 台灣 臺灣 Taiwan Formosa 中華民國 Republic of China 西藏 土伯特 唐古特 Tibet 達賴喇嘛 Dalai Lama 法輪功 Falun Dafa 新疆維吾爾自治區 The Xinjiang Uyghur Autonomous Region 諾貝爾和平獎 Nobel Peace Prize 劉暁波 Liu Xiaobo 民主 言論 思想 反共 反革命 抗議 運動 騷亂 暴亂 騷擾 擾亂 抗暴 平反 維權 示威游行 李洪志 法輪大法 大法弟子 強制斷種 強制堕胎 民族淨化 人體實驗 肅清 胡耀邦 趙紫陽 魏京生 王丹 還政於民 和平演變 激流中國 北京之春 大紀元時報 九評論共産黨 獨裁 專制 壓制 統一 監視 鎮壓 迫害 侵略 掠奪 破壞 拷問 屠殺 活摘器官 誘拐 買賣人口 遊進 走私 毒品 賣淫 春畫 賭博 六合彩 天安門 天安门 法輪功 李洪志 Winnie the Pooh 劉曉波动态网自由门
![winnie the pooh](https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcR8lMNrkkIsnQdgh0iEZDVOvabcYBhuuopyPRxClM7sp2QrFZFg)

**Comment by ailewl** [comment]
![image](https://user-images.githubusercontent.com/31687234/67841546-4d485280-fb33-11e9-8bf1-296d07c89d26.png)

**Comment by FarStady** [comment]
> 我觉得你是故意挑起矛盾。炮火转移到GitHub？
笑死爷了，触及到自己利益了人家就是故意挑起矛盾了？多少居心叵测的反华势力因为GitHub不被墙趁机趁机辱华？你就视而不见？你的利益高于国家利益？
