### ISSUE TITLE
112 Victoria Park, 5 demands, not one less

### ISSUE THREAD

**Issue by howawong** [notepad-plus-plus/notepad-plus-plus#6444]
![image](https://user-images.githubusercontent.com/760880/67840924-eaa28700-fb31-11e9-8e28-9396cd94be91.png)

**Comment by michaellee8** [comment]
#FiveDemands #NoOneLess
#StandWithHongKong #FightForFreedom

**Comment by season7515** [comment]
所以要在这里借题发挥?
嗯...

**Comment by penghubingzhou** [comment]
继续编，看你能遍到什么时候

**Comment by ailewl** [comment]
![image](https://user-images.githubusercontent.com/31687234/67841546-4d485280-fb33-11e9-8bf1-296d07c89d26.png)

**Comment by khmak3** [comment]
#FiveDemands #NoOneLess
#StandWithHongKong #FightForFreedom

**Comment by nopsg** [comment]
> #FiveDemands #NoOneLess
> #StandWithHongKong #FightForFreedom

No one less典型的香港口水话，学学李哥哥的not one can be compromised：
https://www.scmp.com/week-asia/politics/article/3033441/singapores-lee-hsien-loong-social-media-hero-china-hong-kong

**Comment by michaellee8** [comment]
Hey guys pls help with this one https://github.com/notepad-plus-plus/notepad-plus-plus/issues/6408

**Comment by mujun0312** [comment]
@michaellee8 弄则港比样子，看了真的觉得可笑。

**Comment by mujun0312** [comment]
@michaellee8 please look at #6504 lol

**Comment by pcchou** [comment]
#FiveDemands #NoOneLess
#StandWithHongKong #FightForFreedom
