### ISSUE TITLE
许多中国人支持强奸犯和凶手。为什么？

### ISSUE THREAD

**Issue by etopian** [notepad-plus-plus/notepad-plus-plus#6447]
中国崛起的途径很多。强奸维吾尔人是没有必要的。大多数维吾尔族人对中国无所作为，但中国已强奸，监禁并杀死了许多人。许多中国人支持强奸犯和凶手。为什么？

**Comment by elinxer** [comment]
没证据你说个鸡儿，你他么去过当地吗

**Comment by Rojackse** [comment]
请把证据提交到法院

**Comment by xiaolongjuan** [comment]
你丫从哪看来的假新闻

**Comment by dxp8964** [comment]
因为在他们眼里，CCP比自由和人权更加重要‘

Because in their eyes, CCP is more important than freedom and human rights.

**Comment by dongyingt** [comment]
来来来，先把你拉过去亲自看看，如果你是乱说话，那就把屎吃下去

**Comment by penghubingzhou** [comment]
有证据请放出来，别以为这是GitHub网警就拿你没办法。

**Comment by NicePc** [comment]
有病吧这人！你觉得在这里乱咬就查不到你？

**Comment by CysRoad** [comment]
> 中国崛起的途径很多。强奸维吾尔人是没有必要的。大多数维吾尔族人对中国无所作为，但中国已强奸，监禁并杀死了许多人。许多中国人支持强奸犯和凶手。为什么？

证据呢，是想和美国一样用洗衣粉就把伊拉克打了
还是和白头盔一样自导自演说有化武呢

**Comment by ailewl** [comment]
![image](https://user-images.githubusercontent.com/31687234/67841546-4d485280-fb33-11e9-8bf1-296d07c89d26.png)

**Comment by SingleRela** [comment]
有脑子吗？？你脑子被美国佬用电击了吗？说吧收了美国间谍多少钱？？？

**Comment by xmge** [comment]
少数民族高考加分，，，额，啥时候强奸了。。。。

**Comment by hklcf** [comment]
#SupportHongKong #FightForFreedom

**Comment by B612-Prince** [comment]
> 中国崛起的途径很多。强奸维吾尔人是没有必要的。大多数维吾尔族人对中国无所作为，但中国已强奸，监禁并杀死了许多人。许多中国人支持强奸犯和凶手。为什么？

你又知道了？口说无凭，不要整天意淫。

**Comment by LY16JAVA-zhangzhiyuan** [comment]
？？？哈哈哈，终于连这种造谣都来了，脑子被驴踢了吧。这都信，让我怀疑我是在和什么智商的人在对话。

**Comment by dackon** [comment]
因为它们根本不是中国人，是五毛狗，是畜生

**Comment by gitors** [comment]
先问是不是，再问为什么？
比如： 你为什么强奸了你妈妈？

**Comment by SingleRela** [comment]
这一看就是沙雕用Google 机翻，一看就是没怎么受过教育的弱智~~~你爸妈都拿钱去赌博吸毒了吧？没钱供你上学，可怜

**Comment by SingleRela** [comment]
基本分辨是非，了解事实的能力都没有，可能连Google都不会吧~~哈哈，想学吗？我教你啊~
