### ISSUE TITLE
Notepad++ has too few icons in its UI

### ISSUE THREAD

**Issue by h-h-h-h** [notepad-plus-plus/notepad-plus-plus#645]
There are many menu items that don't have an icon. Having more icons would make it more hassle-free to find something.

It seems that finding many free colored icons that you can choose from is hard. They would need to be vector images so that any needed sizes can be created. The source site has to be serious.

What about flat icons? They would be much better than too few icons. See this examples:
- Edit > Indent: http://www.flaticon.com/free-icon/indent-interface-symbol_37095
- Edit > Convert Case to: http://www.flaticon.com/free-icon/uppercase-or-lowercase-button_51563
- View > Hide Line Number Margin: http://www.flaticon.com/free-icon/list-button_7501

They can be changed later, if someone finds icons that are better suited. I think I could help finding the icons, if a platform is provided for putting the SVG files and the attribution text in and associate it with a menu item. I think Inkscape can automatically convert the files to PNG images via command line.

**Comment by Yaron10** [comment]
http://sourceforge.net/p/notepad-plus/discussion/482781/thread/dbea5d02/#47d8
http://sourceforge.net/p/notepad-plus/discussion/482781/thread/db6db280/

**Comment by h-h-h-h** [comment]
Thanks for the information. It's strange to have menu items as a plug-in. Unfortunately, it doesn't work with the German translation. I think, it should be implemented as program functionality. But you have provided colored icons that could be used for that. For people reading this topic: download the extended icon set from https://sites.google.com/site/fstellari/nppplugins ("MenuIcons").

**Comment by Yaron10** [comment]
My pleasure.

It should work with German localization.
You need to translate the folders and files under the MenuIcons folder into German.
Alternatively, you can check "Command ID Match" and name the files accordingly. 

![menuicons](https://cloud.githubusercontent.com/assets/10229320/9076609/6a4047a0-3b2d-11e5-8586-b79cab7ac06f.PNG)

Best regards.

**Comment by Yaron10** [comment]
A few more icons [here](http://sourceforge.net/p/notepad-plus/discussion/482781/thread/db6db280/#0859).

**Comment by Rikk** [comment]
@Yaron10 
The work Franco and you done is excellent!
I see you got improved icons, improving Franco's work, they look great!

May I give a suggestion? Yes! So, here is:
Make a copy of the 3 icons related to Recent Files, in a subfolder called "Recent Files", because that feature can also be displayed in a submenu.

**Comment by Yaron10** [comment]
@Rikk,

Franco's plugin is indeed great. I'm glad you like my icons set. :)
Thanks for your improvements. 
I've added and modified a few icons. Download [here](http://www40.zippyshare.com/v/rGAcMraC/file.html).

Some Python Scripts and images for the Customize Toolbar plugin [here](http://www40.zippyshare.com/v/X38KuFBt/file.html).

Best regards.


@h-h-h-h,

For customizing the *toolbar icons*, use the [Customize Toolbar](http://sourceforge.net/p/notepad-plus/discussion/482781/thread/535ad817/) plugin.
For adding icons to menus, use the [MenuIcons](http://www40.zippyshare.com/v/rGAcMraC/file.html) plugin.

If you need some more help, don't hesitate. :)

Best regards.

**Comment by h-h-h-h** [comment]
Yeah, I got most menu item icons to work for the German translation. Unfortunately, they are too small on a high-dpi monitor whereas the toolbar icons are scaled properly. If you could get in contact with Franco according to this bug, I would appreciate that. His e-mail address isn't complete and an extrapolated one doesn't work.

Still this remains a feature request to add menu icons for all languages out of the box.

**Comment by Yaron10** [comment]
@h-h-h-h,

I've also extrapolated and finally cracked it. :)
fstellari.public @ gmail .com (remove the spaces).

Please update here.

**Comment by h-h-h-h** [comment]
Franco Stellari gave me some information for increasing the icon size. One has to make a change in the file: "C:\Users\???\AppData\Roaming\Notepad++\plugins\config\MenuIcons.ini". Set "IconSize" to "48" or "32". Let me add: 'Cause the file may be reset, make it write-protected, at least until the value is "established".

**Comment by Rikk** [comment]
(haha can't believe github allows that)

**Comment by Yaron10** [comment]
@h-h-h-h,

Thanks for updating.

What do you mean "Some things remained English because of an imperfect process."?
- The strings should be compatible with those in German.xml.

If you're going to create a new icons set, please upload and update.

Is the download link you provided valid? :)

@Rikk,

What do you mean "(haha can't believe github allows that)"? :)

**Comment by Rikk** [comment]
That we can send binary files and github thinks they are images... hope they don't fix it. You need Save As to download that broken image that's not an image...

**Comment by Yaron10** [comment]
Thanks Rikk. Nice! :)

**Comment by h-h-h-h** [comment]
@Yaron10,
I can't work with these XML files for this purpose. I use MenuIcons option "Generate list...". See my edit.

@Rikk,
Yeah, it's a great workaround!

**Comment by h-h-h-h** [comment]
Here are more 16x16px icons: http://www.famfamfam.com/lab/icons/.

**Comment by Yaron10** [comment]
@h-h-h-h,

Thank you. I appreciate it.
I think some professional designers might do the gob voluntarily if Don posted it in a prominent place.

**Comment by Yaron10** [comment]
@Rikk,

Fast and Furious. And Clever. :) 
Thanks for all your great work (seen several of your posts). Good to have you aboard.

**Comment by milipili** [comment]
Could you propose a mockup with all those icons ?

**Comment by h-h-h-h** [comment]
What type of mockup? A screenshot containing menu icons?

**Comment by milipili** [comment]
For example

**Comment by Rikk** [comment]
@milipili you can install [MenuIcons](http://portfolio.ricardo.solutions/etc/NppMenuIcons.1.10++.zip) plugin to see it in action, ya?

**Comment by milipili** [comment]
Yeah I could.

**Comment by Rikk** [comment]
MenuIcons is making Npp crash very often on exit. It needs to be fixed.

**Comment by Yaron10** [comment]
@Rikk,

Never had a problem on Win 7.
Could you contact Franco? - Please update.

Best regards.

**Comment by h-h-h-h** [comment]
<sub>@milipili:</sub>
> <sub>Could you propose a mockup with all those icons ?</sub>

There should definitely be the possibility to let the icons be as big as you want. To be helpful, the icons have to be this big here (48 x 48 px):
![menu with big icons](https://cloud.githubusercontent.com/assets/13482553/9551014/e93b4e90-4dae-11e5-952f-fc07cb33a891.png)

**Comment by Yaron10** [comment]
[NppMenuIcons.1.10++.zip](https://github.com/notepad-plus-plus/notepad-plus-plus/files/124122/NppMenuIcons.1.10.zip)
[Customize Toolbar Images + Some Python Scripts.zip](https://github.com/notepad-plus-plus/notepad-plus-plus/files/124123/Customize.Toolbar.Images.Some.Python.Scripts.zip)

Just uploading to GitHub.

**Comment by donho** [comment]
No... Let's keep menu clean without icon.
