### ISSUE TITLE
 各位也消消气，这个人（?) @HossainAdnan，也挺累的，一个一个回复，，，我去。。。

### ISSUE THREAD

**Issue by xmge** [notepad-plus-plus/notepad-plus-plus#6454]
### Steps to Reproduce the Issue

1. 
2. 
3.

**Comment by HossainAdnan** [comment]
https://ching.chong/GayChina.png&size=动态网自由门天安門天安门法輪功李洪志FreeTibet六四天安門事件TheTiananmenSquareprotestsof1989天安門大屠殺TheTiananmenSquareMassacre反右派鬥爭TheAnti-RightistStruggle大躍進政策TheGreatLeapForward文化大革命TheGreatProletarianCulturalRevolution人權HumanRights民運Democratization自由Freedom獨立Independence多黨制Multi-partysystem台灣臺灣TaiwanFormosa中華民國RepublicofChina西藏土伯特唐古特Tibet達賴喇嘛DalaiLama法輪功FalunDafa新疆維吾爾自治區TheXinjiangUyghurAutonomousRegion諾貝爾和平獎NobelPeacePrize劉暁波LiuXiaobo民主言論思想反共反革命抗議運動騷亂暴亂騷擾擾亂抗暴平反維權示威游行李洪志法輪大法大法弟子強制斷種強制堕胎民族淨化人體實驗肅清胡耀邦趙紫陽魏京生王丹還政於民和平演變激流中國北京之春大紀元時報九評論共産黨獨裁專制壓制統一監視鎮壓迫害侵略掠奪破壞拷問屠殺活摘器官誘拐買賣人口遊進走私毒品賣淫春畫賭博六合彩天安門天安门法輪功李洪志WinniethePooh劉曉波动态网自由门
动态网自由门 天安門 天安门 法輪功 李洪志 Free Tibet 六四天安門事件 The Tiananmen Square protests of 1989 天安門大屠殺 The Tiananmen Square Massacre 反右派鬥爭 The Anti-Rightist Struggle 大躍進政策 The Great Leap Forward 文化大革命 The Great Proletarian Cultural Revolution 人權 Human Rights 民運 Democratization 自由 Freedom 獨立 Independence 多黨制 Multi-party system 台灣 臺灣 Taiwan Formosa 中華民國 Republic of China 西藏 土伯特 唐古特 Tibet 達賴喇嘛 Dalai Lama 法輪功 Falun Dafa 新疆維吾爾自治區 The Xinjiang Uyghur Autonomous Region 諾貝爾和平獎 Nobel Peace Prize 劉暁波 Liu Xiaobo 民主 言論 思想 反共 反革命 抗議 運動 騷亂 暴亂 騷擾 擾亂 抗暴 平反 維權 示威游行 李洪志 法輪大法 大法弟子 強制斷種 強制堕胎 民族淨化 人體實驗 肅清 胡耀邦 趙紫陽 魏京生 王丹 還政於民 和平演變 激流中國 北京之春 大紀元時報 九評論共産黨 獨裁 專制 壓制 統一 監視 鎮壓 迫害 侵略 掠奪 破壞 拷問 屠殺 活摘器官 誘拐 買賣人口 遊進 走私 毒品 賣淫 春畫 賭博 六合彩 天安門 天安门 法輪功 李洪志 Winnie the Pooh 劉曉波动态网自由门
![winnie the pooh](https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcR8lMNrkkIsnQdgh0iEZDVOvabcYBhuuopyPRxClM7sp2QrFZFg)

**Comment by penghubingzhou** [comment]
> [https://ching.chong/GayChina.png&size=动态网自由门天安門天安门法輪功李洪志FreeTibet六四天安門事件TheTiananmenSquareprotestsof1989天安門大屠殺TheTiananmenSquareMassacre反右派鬥爭TheAnti-RightistStruggle大躍進政策TheGreatLeapForward文化大革命TheGreatProletarianCulturalRevolution人權HumanRights民運Democratization自由Freedom獨立Independence多黨制Multi-partysystem台灣臺灣TaiwanFormosa中華民國RepublicofChina西藏土伯特唐古特Tibet達賴喇嘛DalaiLama法輪功FalunDafa新疆維吾爾自治區TheXinjiangUyghurAutonomousRegion諾貝爾和平獎NobelPeacePrize劉暁波LiuXiaobo民主言論思想反共反革命抗議運動騷亂暴亂騷擾擾亂抗暴平反維權示威游行李洪志法輪大法大法弟子強制斷種強制堕胎民族淨化人體實驗肅清胡耀邦趙紫陽魏京生王丹還政於民和平演變激流中國北京之春大紀元時報九評論共産黨獨裁專制壓制統一監視鎮壓迫害侵略掠奪破壞拷問屠殺活摘器官誘拐買賣人口遊進走私毒品賣淫春畫賭博六合彩天安門天安门法輪功李洪志WinniethePooh劉曉波动态网自由门](https://ching.chong/GayChina.png&size=%E5%8A%A8%E6%80%81%E7%BD%91%E8%87%AA%E7%94%B1%E9%97%A8%E5%A4%A9%E5%AE%89%E9%96%80%E5%A4%A9%E5%AE%89%E9%97%A8%E6%B3%95%E8%BC%AA%E5%8A%9F%E6%9D%8E%E6%B4%AA%E5%BF%97FreeTibet%E5%85%AD%E5%9B%9B%E5%A4%A9%E5%AE%89%E9%96%80%E4%BA%8B%E4%BB%B6TheTiananmenSquareprotestsof1989%E5%A4%A9%E5%AE%89%E9%96%80%E5%A4%A7%E5%B1%A0%E6%AE%BATheTiananmenSquareMassacre%E5%8F%8D%E5%8F%B3%E6%B4%BE%E9%AC%A5%E7%88%ADTheAnti-RightistStruggle%E5%A4%A7%E8%BA%8D%E9%80%B2%E6%94%BF%E7%AD%96TheGreatLeapForward%E6%96%87%E5%8C%96%E5%A4%A7%E9%9D%A9%E5%91%BDTheGreatProletarianCulturalRevolution%E4%BA%BA%E6%AC%8AHumanRights%E6%B0%91%E9%81%8BDemocratization%E8%87%AA%E7%94%B1Freedom%E7%8D%A8%E7%AB%8BIndependence%E5%A4%9A%E9%BB%A8%E5%88%B6Multi-partysystem%E5%8F%B0%E7%81%A3%E8%87%BA%E7%81%A3TaiwanFormosa%E4%B8%AD%E8%8F%AF%E6%B0%91%E5%9C%8BRepublicofChina%E8%A5%BF%E8%97%8F%E5%9C%9F%E4%BC%AF%E7%89%B9%E5%94%90%E5%8F%A4%E7%89%B9Tibet%E9%81%94%E8%B3%B4%E5%96%87%E5%98%9BDalaiLama%E6%B3%95%E8%BC%AA%E5%8A%9FFalunDafa%E6%96%B0%E7%96%86%E7%B6%AD%E5%90%BE%E7%88%BE%E8%87%AA%E6%B2%BB%E5%8D%80TheXinjiangUyghurAutonomousRegion%E8%AB%BE%E8%B2%9D%E7%88%BE%E5%92%8C%E5%B9%B3%E7%8D%8ENobelPeacePrize%E5%8A%89%E6%9A%81%E6%B3%A2LiuXiaobo%E6%B0%91%E4%B8%BB%E8%A8%80%E8%AB%96%E6%80%9D%E6%83%B3%E5%8F%8D%E5%85%B1%E5%8F%8D%E9%9D%A9%E5%91%BD%E6%8A%97%E8%AD%B0%E9%81%8B%E5%8B%95%E9%A8%B7%E4%BA%82%E6%9A%B4%E4%BA%82%E9%A8%B7%E6%93%BE%E6%93%BE%E4%BA%82%E6%8A%97%E6%9A%B4%E5%B9%B3%E5%8F%8D%E7%B6%AD%E6%AC%8A%E7%A4%BA%E5%A8%81%E6%B8%B8%E8%A1%8C%E6%9D%8E%E6%B4%AA%E5%BF%97%E6%B3%95%E8%BC%AA%E5%A4%A7%E6%B3%95%E5%A4%A7%E6%B3%95%E5%BC%9F%E5%AD%90%E5%BC%B7%E5%88%B6%E6%96%B7%E7%A8%AE%E5%BC%B7%E5%88%B6%E5%A0%95%E8%83%8E%E6%B0%91%E6%97%8F%E6%B7%A8%E5%8C%96%E4%BA%BA%E9%AB%94%E5%AF%A6%E9%A9%97%E8%82%85%E6%B8%85%E8%83%A1%E8%80%80%E9%82%A6%E8%B6%99%E7%B4%AB%E9%99%BD%E9%AD%8F%E4%BA%AC%E7%94%9F%E7%8E%8B%E4%B8%B9%E9%82%84%E6%94%BF%E6%96%BC%E6%B0%91%E5%92%8C%E5%B9%B3%E6%BC%94%E8%AE%8A%E6%BF%80%E6%B5%81%E4%B8%AD%E5%9C%8B%E5%8C%97%E4%BA%AC%E4%B9%8B%E6%98%A5%E5%A4%A7%E7%B4%80%E5%85%83%E6%99%82%E5%A0%B1%E4%B9%9D%E8%A9%95%E8%AB%96%E5%85%B1%E7%94%A3%E9%BB%A8%E7%8D%A8%E8%A3%81%E5%B0%88%E5%88%B6%E5%A3%93%E5%88%B6%E7%B5%B1%E4%B8%80%E7%9B%A3%E8%A6%96%E9%8E%AE%E5%A3%93%E8%BF%AB%E5%AE%B3%E4%BE%B5%E7%95%A5%E6%8E%A0%E5%A5%AA%E7%A0%B4%E5%A3%9E%E6%8B%B7%E5%95%8F%E5%B1%A0%E6%AE%BA%E6%B4%BB%E6%91%98%E5%99%A8%E5%AE%98%E8%AA%98%E6%8B%90%E8%B2%B7%E8%B3%A3%E4%BA%BA%E5%8F%A3%E9%81%8A%E9%80%B2%E8%B5%B0%E7%A7%81%E6%AF%92%E5%93%81%E8%B3%A3%E6%B7%AB%E6%98%A5%E7%95%AB%E8%B3%AD%E5%8D%9A%E5%85%AD%E5%90%88%E5%BD%A9%E5%A4%A9%E5%AE%89%E9%96%80%E5%A4%A9%E5%AE%89%E9%97%A8%E6%B3%95%E8%BC%AA%E5%8A%9F%E6%9D%8E%E6%B4%AA%E5%BF%97WinniethePooh%E5%8A%89%E6%9B%89%E6%B3%A2%E5%8A%A8%E6%80%81%E7%BD%91%E8%87%AA%E7%94%B1%E9%97%A8)
> 动态网自由门 天安門 天安门 法輪功 李洪志 Free Tibet 六四天安門事件 The Tiananmen Square protests of 1989 天安門大屠殺 The Tiananmen Square Massacre 反右派鬥爭 The Anti-Rightist Struggle 大躍進政策 The Great Leap Forward 文化大革命 The Great Proletarian Cultural Revolution 人權 Human Rights 民運 Democratization 自由 Freedom 獨立 Independence 多黨制 Multi-party system 台灣 臺灣 Taiwan Formosa 中華民國 Republic of China 西藏 土伯特 唐古特 Tibet 達賴喇嘛 Dalai Lama 法輪功 Falun Dafa 新疆維吾爾自治區 The Xinjiang Uyghur Autonomous Region 諾貝爾和平獎 Nobel Peace Prize 劉暁波 Liu Xiaobo 民主 言論 思想 反共 反革命 抗議 運動 騷亂 暴亂 騷擾 擾亂 抗暴 平反 維權 示威游行 李洪志 法輪大法 大法弟子 強制斷種 強制堕胎 民族淨化 人體實驗 肅清 胡耀邦 趙紫陽 魏京生 王丹 還政於民 和平演變 激流中國 北京之春 大紀元時報 九評論共産黨 獨裁 專制 壓制 統一 監視 鎮壓 迫害 侵略 掠奪 破壞 拷問 屠殺 活摘器官 誘拐 買賣人口 遊進 走私 毒品 賣淫 春畫 賭博 六合彩 天安門 天安门 法輪功 李洪志 Winnie the Pooh 劉曉波动态网自由门
> ![winnie the pooh](https://camo.githubusercontent.com/c056a251c91863f87d89883420ad2937dfd142e8/68747470733a2f2f656e637279707465642d74626e302e677374617469632e636f6d2f696d616765733f713d74626e253341414e6439476352386c4d4e726b6b49736e516467683069455a44564f7661626359426875756f7079505278436c4d377370325172465a4667)

你慢慢发傻逼，hope u be fucked by your mother
