### ISSUE TITLE
Notepad++ v7.8.1 : Free Uyghur

### ISSUE THREAD

**Issue by ahmed-tea** [notepad-plus-plus/notepad-plus-plus#6458]
I know here is not a place to post that but

### **Thank You For Supporting Uyghur people**

[Notepad++ v7.8.1 : Free Uyghur](https://notepad-plus-plus.org/news/v781-free-uyghur-edition/)

![freeUyghur](https://user-images.githubusercontent.com/32733104/67848716-dea4ce00-fb0d-11e9-9974-c16bfff4b5e0.png)

**Comment by dackon** [comment]
Free Hongkong, Free mainland, FUCK CCP

**Comment by Rojackse** [comment]
FUCK Facebook

**Comment by penghubingzhou** [comment]
tell me how much your dad trump paid for you?

**Comment by penghubingzhou** [comment]
> Free Hongkong, Free mainland, FUCK CCP

Go back to your mom's Vagina white pig

**Comment by caoler** [comment]
@Rojackse 你fuck人家Facebook干啥？Facebook招你惹你了，别整天fuck这个fuck那个的了

**Comment by JLPathos** [comment]
> tell me how much your dad trump paid for you?

Tell me how much your dad Winnie the Pooh paid for you?

**Comment by ahmed-tea** [comment]
> 
> 
> tell me how much your dad trump paid for you?

Stupid you must think befor you comment
I'm a Muslim, It is clear from my name
When a Muslim comments, say "ISIS paid for you"
When a Non-Muslim comments, say "trump paid for you"
Your supervisior must be punished for that 

**All Dictators supporters are the same**
