### ISSUE TITLE
它就是个狒狒

### ISSUE THREAD

**Issue by markkr133** [notepad-plus-plus/notepad-plus-plus#6468]
### Steps to Reproduce the Issue

1. 
2. 
3.

**Comment by HossainAdnan** [comment]
TheGreatLeapForward文化大革命TheGreatProletarianCulturalRevolution人權HumanRights民運Democratization自由Freedom獨立Independence多黨制Multi-partysystem台灣臺灣TaiwanFormosa中華民國RepublicofChina
