### ISSUE TITLE
刷你妹的政治事件,怎么不刷刷南京大屠杀?美国狗,日本狗

### ISSUE THREAD

**Issue by Rojackse** [notepad-plus-plus/notepad-plus-plus#6470]
### Steps to Reproduce the Issue

1. 
2. 
3.

**Comment by dxp8964** [comment]
长春围城死了多少人？
反右死了多少人？
大饥荒死了多少人？
文革死了多少人？
六四死了多少人？
毒奶粉死了多少人？

**Comment by mt-os** [comment]
> 长春围城死了多少人？
> 反右死了多少人？
> 大饥荒死了多少人？
> 文革死了多少人？
> 六四死了多少人？
> 毒奶粉死了多少人？

没你家死的多

**Comment by eoser** [comment]
> 长春围城死了多少人？
> 反右死了多少人？
> 大饥荒死了多少人？
> 文革死了多少人？
> 六四死了多少人？
> 毒奶粉死了多少人？

你可以去查一查各个国家的黑历史，重点美国！你会震惊的！
