### ISSUE TITLE
垃圾中國人吃屎吧

### ISSUE THREAD

**Issue by KuKuO** [notepad-plus-plus/notepad-plus-plus#6475]
### Steps to Reproduce the Issue

1. 
2. 
3.

**Comment by assad2008** [comment]
恐怕你连吃屎的资格都没

**Comment by dtwen-mk** [comment]
你tm用的中国话 狗比玩意

**Comment by chnape** [comment]
fuck you mother,

**Comment by wangzezz** [comment]
你tm用的中国话 狗比玩意

**Comment by SingleRela** [comment]
真尼玛的有趣，写着中国的汉字，来骂中国人，是真尼玛的弱智，英文都不会说，恐怕是你爸妈没钱供你上学学英文吧？要想讨好你美国爹，还是学学英文吧

**Comment by dongyingt** [comment]
你为什么要用汉字，不觉着打脸吗？

**Comment by chnape** [comment]
cnm,d

**Comment by chnape** [comment]
NMSL

**Comment by FightCounterfeits** [comment]
中国人给你饭不吃，你TMD要去吃屎，还说香，贱骨头

**Comment by penghubingzhou** [comment]
我看你連吃屎的資格都沒有哈比

**Comment by chnape** [comment]
cn的败类

**Comment by chnape** [comment]
怎么不bb了？

**Comment by fsdstar** [comment]
用英文吧，你中国爹看得懂。

**Comment by KuKuO** [comment]
中國人是垃圾全世界都知道啦
不服來戰

**Comment by pjt57364413** [comment]
fuck you monter

**Comment by KuKuO** [comment]
一堆用殘體字的智障
習近平敢不敢講阿
臭小熊維尼

**Comment by fsdstar** [comment]
> 一堆用殘體字的智障
> 習近平敢不敢講阿
> 臭小熊維尼

有本事上大号，废青

**Comment by Rojackse** [comment]
抱歉,我们读懂繁体,你TM读懂简体吗?

**Comment by MrStrangeBao** [comment]
不喜欢中国就滚出中国,别说中国话,别用中国制造得东西,别在中国土地上嘚瑟.

**Comment by KuKuO** [comment]
> 抱歉,我们读懂繁体,你TM读懂简体吗?

殘體有啥好讀不懂
文化大革命的可憐蟲
看到殘體就覺得噁心 嘔嘔嘔嘔嘔嘔嘔嘔
只敢欺負香港 新疆 西藏
真D垃圾

**Comment by LY16JAVA-zhangzhiyuan** [comment]
哈哈，台独分子终于脱下了所谓的“素质”外衣，自己狂吠了起来。

**Comment by fsdstar** [comment]
> > 抱歉,我们读懂繁体,你TM读懂简体吗?
> 
> 殘體有啥好讀不懂
> 文化大革命的可憐蟲
> 看到殘體就覺得噁心 嘔嘔嘔嘔嘔嘔嘔嘔
> 只敢欺負香港 新疆 西藏
> 真D垃圾

那你是台湾县的了？一个小县城BB啥

**Comment by SingleRela** [comment]
你怕不是没吃过美帝自由民主的枪子儿哦~~

**Comment by KuKuO** [comment]
一群支那狗崩潰啦
玻璃心碎滿地
笑死

**Comment by zsamakamadob** [comment]
用英文怕你們支那狗看不懂，學位都係付錢買回來的

**Comment by WPTomo** [comment]
你妈肯定拉完你就直接冲了
不对，你这种应该没有母亲

**Comment by fsdstar** [comment]
> 一群支那狗崩潰啦
> 玻璃心碎滿地
> 笑死

叫了半天上大号啊，一直开小号钓鱼有啥意思

**Comment by WPTomo** [comment]
@

> 用英文怕你們支那狗看不懂，學位都係付錢買回來的

先把你那搅屎棍一样的舌头缕过来再说话吧，还都系，系 nmb

**Comment by fsdstar** [comment]
> 用英文怕你們支那狗看不懂，學位都係付錢買回來的

读音都不会还好意思打字，你们老师看到怕不是要一枪蹦了你

**Comment by LY16JAVA-zhangzhiyuan** [comment]
> 用英文怕你們支那狗看不懂，學位都係付錢買回來的

你们台湾人都这么幽默的吗，喜欢说一些井底之蛙的片面言论来自黑，还有什么说的，说我们“吃不起榨菜”？笑死我了。

**Comment by dxixzl** [comment]
# 现实里你畏畏缩缩，网络上你重拳出击，垃圾废物台毒，离了中国你屎都吃不上

**Comment by coffee1998** [comment]
我就想问问你，你现在是哪个国家的狗？请正面回答我的问题。

**Comment by KuKuO** [comment]
一群可憐狗
說要抵制NBA結果表演賽直接爆滿
中國人不意外

**Comment by penghubingzhou** [comment]
> 一堆用殘體字的智障
> 習近平敢不敢講阿
> 臭小熊維尼

你阿蔡九合一敗選真光彩啊

**Comment by l1712115388** [comment]
日本人米国人让他吃屎，你们你美国爸爸屎都不让你吃，伤不伤心，【哭兮兮】

**Comment by penghubingzhou** [comment]
> 一群可憐狗
> 說要抵制NBA結果表演賽直接爆滿
> 中國人不意外

你蔡英文只會用愛發電

**Comment by l1712115388** [comment]
> 一群可怜狗
> 说要抵制NBA结果表演赛直接爆满
> 中国人不意外

说抵制的人不在这里，这里都是更高一层的人，渣渣，你这么喜欢你美国爸爸么？

**Comment by l1712115388** [comment]
> 一群可怜狗
> 说要抵制NBA结果表演赛直接爆满
> 中国人不意外

一群伤心的台湾垃圾哦，美国爸爸连屎都不让你吃，去找小日本学习，想去吃美国爸爸的屎

**Comment by KuKuO** [comment]
> > 一群可怜狗
> > 说要抵制NBA结果表演赛直接爆满
> > 中国人不意外
> 
> 说抵制的人不在这里，这里都是更高一层的人，渣渣，你这么喜欢你美国爸爸么？

別自我安慰啦 可憐蟲
都只是一堆翻牆的狗
我看沒幾個是程序員吧
還不吃屎去

**Comment by l1712115388** [comment]
> 一群支那狗崩溃啦
> 玻璃心碎满地
> 笑死

哎呀，你爸爸的爸爸的爸爸就是支那，不过他确实心碎了，因为他嗝屁拉？你爸爸也是支那，你难道不是支那？那你就是小日本生的台湾那30W遗留的杂种，没爸爸

**Comment by l1712115388** [comment]
> > > 一群可怜狗
> > > 说要抵制NBA结果表演赛直接爆满
> > > 中国人不意外
> > 
> > 
> > 说抵制的人不在这里，这里都是更高一层的人，渣渣，你这么喜欢你美国爸爸么？
> 
> 别自我安慰啦可怜虫
> 都只是一堆翻墙的狗
> 我看没几个是程序员吧
> 还不吃屎去

不是程序员逛你妈呢？脑子不好要多补补

**Comment by xmtggh** [comment]
一群被洗脑的狗，没有墙还去舔你美国爹的屁眼，有没有读过历史啊，没墙还不如我们这些有墙的，脑子能不能补一补？多读读书拉 垃圾！滚出中国拉！

**Comment by l1712115388** [comment]
> > > 一群可怜狗
> > > 说要抵制NBA结果表演赛直接爆满
> > > 中国人不意外
> > 
> > 
> > 说抵制的人不在这里，这里都是更高一层的人，渣渣，你这么喜欢你美国爸爸么？
> 
> 别自我安慰啦可怜虫
> 都只是一堆翻墙的狗
> 我看没几个是程序员吧
> 还不吃屎去

逛这个网站不用翻墙，懂么，台湾小绿

**Comment by l1712115388** [comment]
> > > 一群可怜狗
> > > 说要抵制NBA结果表演赛直接爆满
> > > 中国人不意外
> > 
> > 
> > 说抵制的人不在这里，这里都是更高一层的人，渣渣，你这么喜欢你美国爸爸么？
> 
> 别自我安慰啦可怜虫
> 都只是一堆翻墙的狗
> 我看没几个是程序员吧
> 还不吃屎去

小绿呀，你蔡阿姨舔的几个岛国怎么断交了呀

**Comment by penghubingzhou** [comment]
> > > 一群可怜狗
> > > 说要抵制NBA结果表演赛直接爆满
> > > 中国人不意外
> > 
> > 
> > 说抵制的人不在这里，这里都是更高一层的人，渣渣，你这么喜欢你美国爸爸么？
> 
> 別自我安慰啦 可憐蟲
> 都只是一堆翻牆的狗
> 我看沒幾個是程序員吧
> 還不吃屎去

是喔，照你這麼說，我們似乎pei陵榨菜都吃不起了喔

**Comment by l1712115388** [comment]
> > > 一群可怜狗
> > > 说要抵制NBA结果表演赛直接爆满
> > > 中国人不意外
> > 
> > 
> > 说抵制的人不在这里，这里都是更高一层的人，渣渣，你这么喜欢你美国爸爸么？
> 
> 别自我安慰啦可怜虫
> 都只是一堆翻墙的狗
> 我看没几个是程序员吧
> 还不吃屎去
我们吃不起茶叶蛋，所以我们只能吃得起烤面包，茶叶蛋太便宜了，哈哈哈，居然自闭到这种程度，还敢再网上发表评论，知识储备都不在一个平面上

**Comment by l1712115388** [comment]
> > > 一群可怜狗
> > > 说要抵制NBA结果表演赛直接爆满
> > > 中国人不意外
> > 
> > 
> > 说抵制的人不在这里，这里都是更高一层的人，渣渣，你这么喜欢你美国爸爸么？
> 
> 别自我安慰啦可怜虫
> 都只是一堆翻墙的狗
> 我看没几个是程序员吧
> 还不吃屎去

我们吃不起茶叶蛋，所以我们只能吃得起烤面包，茶叶蛋太便宜了，哈哈哈，居然自闭到这种程度，还敢再网上发表评论，知识储备都不在一个平面上

**Comment by MrStrangeBao** [comment]
不喜欢中国就滚出中国,别说中国话,别用中国制造得东西,别在中国土地上嘚瑟.

**Comment by KuKuO** [comment]
到底是多閒才上來Github欠嘴阿
可悲 小熊維尼沒蜂蜜吃阿

**Comment by fuckingbitch** [comment]
屌你老母臭嗨，你全家户口本同时升天哦，臭傻逼，你老母用仙人球操自己的血逼生下你个杂种？你是野爹多是吗，亲妈原地爆炸也不闻不问？

**Comment by X-Crack** [comment]
你不喜欢中国，你别打中国字好吗？
你爸妈生你，教你中文，你就是用中文来骂人的？

**Comment by RedmapleSokasne** [comment]
憨憨东西？
离开中国找你美国爹啊爬
去美国吃三文鱼不行吗？
吃里扒外的狗东西

**Comment by RedmapleSokasne** [comment]
> > 抱歉，我们读懂繁体，你TM读懂简体吗？
> 
> 残体有啥好读不懂
> 文化大革命的可怜虫看到
> 残体就觉得恶心被丢弃拒绝丢弃拒绝丢弃丢弃的赔付只是
> 敢欺负香港新疆西藏
> 真D垃圾

哟 拿着GoogleChrome翻译充胖子？
哥哥别用脚打字了 上手吧
哥哥三文鱼还没吃够？
要是爹吧你们弄走了你们就个个变成杂交仔了
上Github口嗨也不见得有什么用
最后还不是被骂的死妈？

**Comment by RedmapleSokasne** [comment]
> > 抱歉，我们读懂繁体，你TM读懂简体吗？
> 
> 残体有啥好读不懂
> 文化大革命的可怜虫看到
> 残体就觉得恶心被丢弃拒绝丢弃拒绝丢弃丢弃的赔付只是
> 敢欺负香港新疆西藏
> 真D垃圾

上次喷死了一个as 现在又来一个台美杂交？
