### ISSUE TITLE
gkd,赶紧上github热搜,这样凉的快

### ISSUE THREAD

**Issue by Rojackse** [notepad-plus-plus/notepad-plus-plus#6480]
### Steps to Reproduce the Issue

1. 
2. 
3.

**Comment by CannibalKush** [comment]
The Tiananmen Square protests, commonly known in mainland China as the June Fourth Incident (Chinese: 六四事件, liùsì shìjiàn, literally six-four incident), were student-led demonstrations held in Tiananmen Square in Beijing during 1989. The popular national movement inspired by the Beijing protests is sometimes called the '89 Democracy Movement (Chinese: 八九民运, bājiǔ mínyùn). The protests started on April 15 and were forcibly suppressed on June 4 when the government declared martial law and sent the military to occupy central parts of Beijing. In what became known as the Tiananmen Square Massacre (Chinese: 天安门大屠杀), troops with assault rifles and tanks fired at the demonstrators and those trying to block the military's advance into Tiananmen Square. Estimates of the death toll vary from several hundred to several thousand, with thousands more wounded.

**Comment by penghubingzhou** [comment]
> The Tiananmen Square protests, commonly known in mainland China as the June Fourth Incident (Chinese: 六四事件, liùsì shìjiàn, literally six-four incident), were student-led demonstrations held in Tiananmen Square in Beijing during 1989. The popular national movement inspired by the Beijing protests is sometimes called the '89 Democracy Movement (Chinese: 八九民运, bājiǔ mínyùn). The protests started on April 15 and were forcibly suppressed on June 4 when the government declared martial law and sent the military to occupy central parts of Beijing. In what became known as the Tiananmen Square Massacre (Chinese: 天安门大屠杀), troops with assault rifles and tanks fired at the demonstrators and those trying to block the military's advance into Tiananmen Square. Estimates of the death toll vary from several hundred to several thousand, with thousands more wounded.

go die  robot

**Comment by penghubingzhou** [comment]
> 动态网自由门 天安門 天安门 法輪功 李洪志 Free Tibet 六四天安門事件 The Tiananmen Square protests of 1989 天安門大屠殺 The Tiananmen Square Massacre 反右派鬥爭 The Anti-Rightist Struggle 大躍進政策 The Great Leap Forward 文化大革命 The Great Proletarian Cultural Revolution 人權 Human Rights 民運 Democratization 自由 Freedom 獨立 Independence 多黨制 Multi-party system 台灣 臺灣 Taiwan Formosa
> ![winnie the pooh](https://camo.githubusercontent.com/1f5069227f0f3e57267042388ef79a7fa9679b5e/68747470733a2f2f656e637279707465642d74626e302e677374617469632e636f6d2f696d616765733f713d74626e253341414e6439476354703743725f52737770503244654954724b356758354d425a30514c57754d59786567386e5730656e4658574a5034684f79)
> ![kek](动态网自由门 天安門 天安门 法輪功 李洪志 Free Tibet 六四天安門事件 The Tiananmen Square protests of 1989 天安門大屠殺 The Tiananmen Square Massacre 反右派鬥爭 The Anti-Rightist Struggle 大躍進政策 The Great Leap Forward 文化大革命 The Great Proletarian Cultural Revolution 人權 Human Rights 民運 Democratization 自由 Freedom 獨立 Independence 多黨制 Multi-party system 台灣 臺灣 Taiwan Formosa 中華民國 Republic of China 西藏 土伯特 唐古特 Tibet 達賴喇嘛 Dalai Lama 法輪功 Falun Dafa 新疆維吾爾自治區 The Xinjiang Uyghur Autonomous Region 諾貝爾和平獎 Nobel Peace Prize 劉暁波 Liu Xiaobo 民主 言論 思想 反共 反革命 抗議 運動 騷亂 暴亂 騷擾 擾亂 抗暴 平反 維權 示威游行 李洪志 法輪大法 大法弟子 強制斷種 強制堕胎 民族淨化 人體實驗 肅清 胡耀邦 趙紫陽 魏京生 王丹 還政於民 和平演變 激流中國 北京之春 大紀元時報 九評論共産黨 獨裁 專制 壓制 統一 監視 鎮壓 迫害 侵略 掠奪 破壞 拷問 屠殺 活摘器官 誘拐 買賣人口 遊進 走私 毒品 賣淫 春畫 賭博 六合彩 天安門 天安门 法輪功 李洪志 Winnie the Pooh 劉曉波动态网自由门
> ![winnie the pooh](https://camo.githubusercontent.com/1f5069227f0f3e57267042388ef79a7fa9679b5e/68747470733a2f2f656e637279707465642d74626e302e677374617469632e636f6d2f696d616765733f713d74626e253341414e6439476354703743725f52737770503244654954724b356758354d425a30514c57754d59786567386e5730656e4658574a5034684f79))

go die robot

**Comment by etopian** [comment]
Gleichschaltung (German pronunciation: [ˈɡlaɪçʃaltʊŋ]), or in English co-ordination, was in Nazi terminology the process of Nazification by which Adolf Hitler and the Nazi Party successively established a system of totalitarian control and coordination over all aspects of German society and societies occupied by Nazi Germany "from the economy and trade associations to the media, culture and education".

When the blatant emphasis of racial hatred of others seemed to reach an impasse in the school system, through radio broadcasts, or on film reels, the overseers of Nazi Gleichschaltung propaganda switched to strategies that focused more on togetherness and the "we-consciousness" of the collective Volk, but the mandates of Nazi "coordination" remained: pay homage to the Führer, expel all foreigners, sacrifice for the German people, and welcome future challenges.[36] While greater German social and economic unity was produced through the Gleichschaltung initiatives of the regime, it was at the expense of individuality and to the social detriment of any nonconformist;[37] and worse—it contributed to and reinforced the social and racial exclusion of anyone deemed an enemy by National Socialist doctrine

https://en.wikipedia.org/wiki/Gleichschaltung
