### ISSUE TITLE
Mr. Ho, please don't be scared by these chinese robot spammers, you have our full support 請不要被這些五毛打手嚇到，我們對你有無限的支持！

### ISSUE THREAD

**Issue by michaellee8** [notepad-plus-plus/notepad-plus-plus#6482]
Please look at https://github.com/notepad-plus-plus/notepad-plus-plus/issues/6408

**Comment by dtwen-mk** [comment]
你算个JB

**Comment by CannibalKush** [comment]
The Tiananmen Square protests, commonly known in mainland China as the June Fourth Incident (Chinese: 六四事件, liùsì shìjiàn, literally six-four incident), were student-led demonstrations held in Tiananmen Square in Beijing during 1989. The popular national movement inspired by the Beijing protests is sometimes called the '89 Democracy Movement (Chinese: 八九民运, bājiǔ mínyùn). The protests started on April 15 and were forcibly suppressed on June 4 when the government declared martial law and sent the military to occupy central parts of Beijing. In what became known as the Tiananmen Square Massacre (Chinese: 天安门大屠杀), troops with assault rifles and tanks fired at the demonstrators and those trying to block the military's advance into Tiananmen Square. Estimates of the death toll vary from several hundred to several thousand, with thousands more wounded.

**Comment by penghubingzhou** [comment]
你說的這些五毛錢打手，可沒要國家一分錢喔

**Comment by penghubingzhou** [comment]
> 抱歉喔，你說的這些五毛錢打手，可沒要國家一分錢喔，倒是你們，你們的川普給你們發薪水了麼兒

**Comment by l1712115388** [comment]
不好意思我是1块，我没收任何钱而且我生活在中国，倒是你们这群渣渣没钱来大陆就在这里酸酸，美国爹给你们多少钱？

**Comment by BR-Liu** [comment]
什么时候你能代表香港了？港英废物？

**Comment by mujun0312** [comment]
@michaellee8 please look at #6504 lol
