### ISSUE TITLE
兄弟们小心 小熊维尼头像的这个比HossainAdnan  他在往我们留言里挂关键词 想搞我们

### ISSUE THREAD

**Issue by dtwen-mk** [notepad-plus-plus/notepad-plus-plus#6483]
兄弟们小心 小熊维尼头像的这个比HossainAdnan  他在往我们留言里挂关键词 想搞我们

**Comment by penghubingzhou** [comment]
怎么说

**Comment by space5566** [comment]
> 兄弟们小心 小熊维尼头像的这个比HossainAdnan 他在往我们留言里挂关键词 想搞我们

兄弟我是挂vpn上的设计师，我想知道他能怎么搞？
