### ISSUE TITLE
Those rubbish Chinese can't even write in English. What's the point of insulting someone using a language that the victim can't read?

### ISSUE THREAD

**Issue by WWWWNAM** [notepad-plus-plus/notepad-plus-plus#6486]
### Steps to Reproduce the Issue

1. 
2. 
3.

**Comment by dtwen-mk** [comment]
你tm还中文都不会说呢 废物

**Comment by assad2008** [comment]
鸟语不会也罢，你什么玩意，不也不会中文么
再是，你又是哪家的狗？

**Comment by wormlam** [comment]
你們才是廢物，誰不會看中文了。

**Comment by SayHelloBriggs** [comment]
哈哈哈哈 xswl 狗儿子急了 会打中文了

**Comment by wormlam** [comment]
你那種亂七八糟連漢字的結構都不跟從的中文也能算中文?

**Comment by BeyondTheBlade** [comment]
Joined GitHub this month，hahaha，grandson

**Comment by nushadadi** [comment]
@wormlam 你妈病房K歌，坟头蹦迪，灵堂酒会，丧宴烤尸，送葬摇滚，灵车漂移，骨灰拌饭，祖坟歌会，宗庙拍片，尸块养猪，脑浆浇花，灵堂派对，葬礼庆典，骨髓煮汤，螺旋爆炸

**Comment by dongyingt** [comment]
连中文都不会，弱智

**Comment by mujun0312** [comment]
@wormlam 真是laugh死我了，哈哈

**Comment by KuKuO** [comment]
中國人英文程度有夠差  有夠低能
只會吠

**Comment by penghubingzhou** [comment]
u can't also say chinese bitch,

**Comment by fwhezfwhez** [comment]
Did english make you priviledge?
Do you want our praise?

Funny boy.

**Comment by l1712115388** [comment]
受害人是何东，说中国话的 ,傻逼儿子

**Comment by penghubingzhou** [comment]
> 中國人英文程度有夠差 有夠低能
> 只會吠

說的好像你多高能似的，有本事買點涪陵榨菜啊廢青

**Comment by space5566** [comment]
兄弟们散了吧，来来去去就那么两个人，没意思

**Comment by l1712115388** [comment]
> > 中國人英文程度有夠差 有夠低能
> > 只會吠
> 
> 說的好像你多高能似的，有本事買點涪陵榨菜啊廢青

阿狗没有拳头就只能在网上BB，连导弹都造不出来

**Comment by Rojackse** [comment]
英语好还骄傲了?你TM能说好普通话吗?能写好中文吗?还知道自己妈是哪国的吗?

**Comment by BR-Liu** [comment]
Motherfucker

**Comment by l1712115388** [comment]
你祖宗是中国人，你却以英语为骄傲你是香蕉人

> 中國人英文程度有夠差 有夠低能
> 只會吠

你爸爸的爸爸是中国人，你却以英语为骄傲所以你是香蕉人

**Comment by linweishuai** [comment]
爸爸不教育你 你还真翻天了?!!!!!

**Comment by xmtggh** [comment]
傻逼玩意，中文是你鸟语能比的？你们猜几年历史啊，草你妈了个比
