### ISSUE TITLE
打倒美日主义  打倒特朗普 打倒臭傻逼 

### ISSUE THREAD

**Issue by pjt57364413** [notepad-plus-plus/notepad-plus-plus#6487]
恕我直言 github就是垃圾

**Comment by scorpioLh** [comment]
打嗝。特朗普是我i们中国自己人啊。。别这样。。别让他暴露了

**Comment by MAFA2** [comment]
习近平周五在圣彼得堡参加国际经济论坛时又提到了“我的朋友”特朗普。他说：“我们和美国虽然现在有一些贸易摩擦，但中国和美国现在已经是‘你中有我，我中有你'。我也很难设想中美全部割裂开。我想，那种情况不仅我不愿意看到的，我们的美国朋友也不会希望看到。我的朋友特朗普总统，我相信他也不愿意看到。”
虽然美中之间贸易战正酣，但特朗普总统也一再对习近平主席以“朋友”相称。
反党暴徒！企图离间中美关系！
