### ISSUE TITLE
N M S L --献给开发 HO don 和那些港独废青以及 逼逼看不懂中文的 外国佬

### ISSUE THREAD

**Issue by dtwen-mk** [notepad-plus-plus/notepad-plus-plus#6488]
N M S L --献给开发 HO don 和那些港独废青以及 逼逼看不懂中文的 外国佬

**Comment by NainbowCat** [comment]
are you a trash man

**Comment by whinamax** [comment]
> are you a trash man

someone who try split other countries are trash man
