### ISSUE TITLE
建议早一天统一台湾，别拖了

### ISSUE THREAD

**Issue by fengssboy** [notepad-plus-plus/notepad-plus-plus#6489]
祖国统一，收复台湾！本来好好的一个编辑器，非要公开侮辱自己的祖先。新疆是什么样子，你们来看看啊，又没有阻拦不让看。说话讲实证，别听到就信，统一后不指望你们能带来多少繁荣，只要不成为中国复兴路上拖后腿的一代人就好。

**Comment by GuDuYing** [comment]
支持你  兄弟！

**Comment by zsamakamadob** [comment]
台灣是獨立國家

**Comment by SingleRela** [comment]
因为他们弱智，所以肯定连出台湾省的钱都没有，更别说去新疆看看了，都是群嘴炮键盘侠，搞的GitHub社区乌烟瘴气

**Comment by CannibalKush** [comment]
The Tiananmen Square protests, commonly known in mainland China as the June Fourth Incident (Chinese: 六四事件, liùsì shìjiàn, literally six-four incident), were student-led demonstrations held in Tiananmen Square in Beijing during 1989. The popular national movement inspired by the Beijing protests is sometimes called the '89 Democracy Movement (Chinese: 八九民运, bājiǔ mínyùn). The protests started on April 15 and were forcibly suppressed on June 4 when the government declared martial law and sent the military to occupy central parts of Beijing. In what became known as the Tiananmen Square Massacre (Chinese: 天安门大屠杀), troops with assault rifles and tanks fired at the demonstrators and those trying to block the military's advance into Tiananmen Square. Estimates of the death toll vary from several hundred to several thousand, with thousands more wounded.

**Comment by fengssboy** [comment]
> 台灣是獨立國家
不管是中华人民共和国，还是中华民国，都是中国，只是还存在两个政权。政权并不是国家。只有统一，才是两个政权必然要进行的事。国之强大，远比你在岛上看到的要强要大，如果不信服，可以来大陆，只要不搞阴谋恶计，大陆人民必欢迎。

**Comment by fengssboy** [comment]
动不动就 六四，你们说这有用吗？你们再清楚，有北京的老年人更清楚吗？你们看到的，是选择性反华的内容，能看全文不？你们看到的东西，我们也能看到，现在是你们闭上眼不看我们能看到的，当盲人，无视中国正在强盛，无视政府正在不断调整纠正，无视过度期各种艰险，还怪这怪那，有意思？
