### ISSUE TITLE
震惊！六四天安门版本！

### ISSUE THREAD

**Issue by ghost** [notepad-plus-plus/notepad-plus-plus#6490]
![image](https://user-images.githubusercontent.com/57173703/67843776-9c908200-fb37-11e9-89e1-6f3211cbe3c7.png)

竟然拿党的历史事件来离间党和人民群众！罪大恶极！扩散！扩散！让全中国人民知道他们做了什么恶！

**Comment by brillli** [comment]
？？？  孤儿操作？

**Comment by dtwen-mk** [comment]
你是你妈一个阴阳人吗 憨批

**Comment by dtwen-mk** [comment]
说些话跟你妈阁 阴阳人一样

**Comment by michaellee8** [comment]
必須擴散

this must be widely spreaded

**Comment by CannibalKush** [comment]
The Tiananmen Square protests, commonly known in mainland China as the June Fourth Incident (Chinese: 六四事件, liùsì shìjiàn, literally six-four incident), were student-led demonstrations held in Tiananmen Square in Beijing during 1989. The popular national movement inspired by the Beijing protests is sometimes called the '89 Democracy Movement (Chinese: 八九民运, bājiǔ mínyùn). The protests started on April 15 and were forcibly suppressed on June 4 when the government declared martial law and sent the military to occupy central parts of Beijing. In what became known as the Tiananmen Square Massacre (Chinese: 天安门大屠杀), troops with assault rifles and tanks fired at the demonstrators and those trying to block the military's advance into Tiananmen Square. Estimates of the death toll vary from several hundred to several thousand, with thousands more wounded.

**Comment by penghubingzhou** [comment]
> 必須擴散
> 
> this must be widely spreaded

擴散？然後讓世界知道你的孤兒行為？

**Comment by MAFA2** [comment]
> 说些话跟你妈阁 阴阳人一样

你们这些反党份子，企图抹灭国家的伟大历史作为。人民不会答应，历史不会答应！正义必胜！举头三尺有神明！你爸今晚必种枇杷树！

**Comment by MAFA2** [comment]
扩散！让中国人民知道Notepad++的所作所为！让中国人民知道他们做了什么恶！

**Comment by moonAndWind** [comment]
每个政体都有一些不适合公布出来的事情,不要抓抓着这些不放,这是我们的伤疤.我最初了解到64的时候也是很震惊的.然而随着阅历的增长,慢慢也理解了苦衷...历经了十年文革,那个时候再也经不起一丝一毫的动荡了.别拿这说事,真要说什么言论自由,FBI,CIA也有太多不能公布的事情.
