### ISSUE TITLE
一口支那人支那人的，我真的笑了，不认你中国爹就算了，何必连自己都骂？还带上你父母祖宗？不知他们在天之灵看到你如此忤逆会作何感想呢？ 你尽管放心，我们不生气。你们想更换自己血统和基因，用“支那”来意淫自己不是炎黄子孙。无所谓的，你们爱骂自己我们也就笑笑，你们想当美国日本的舔🐶我们也只能笑笑，想着可能在你们眼里，美日的🌼更有味道吧。 台湾省本就没想着能和平回归，也就二三十年后吧，武力夺回。希望到时候你们舔了百来年的美日能保你一命。

### ISSUE THREAD

**Issue by chentaishan1105** [notepad-plus-plus/notepad-plus-plus#6491]
湾湾弟弟，我来教你阅读理解。少年强则国强。这里的强可不是指的嘴哦。

**Comment by dtwen-mk** [comment]
一句话 送给废青们 NMSL

**Comment by CannibalKush** [comment]
The Tiananmen Square protests, commonly known in mainland China as the June Fourth Incident (Chinese: 六四事件, liùsì shìjiàn, literally six-four incident), were student-led demonstrations held in Tiananmen Square in Beijing during 1989. The popular national movement inspired by the Beijing protests is sometimes called the '89 Democracy Movement (Chinese: 八九民运, bājiǔ mínyùn). The protests started on April 15 and were forcibly suppressed on June 4 when the government declared martial law and sent the military to occupy central parts of Beijing. In what became known as the Tiananmen Square Massacre (Chinese: 天安门大屠杀), troops with assault rifles and tanks fired at the demonstrators and those trying to block the military's advance into Tiananmen Square. Estimates of the death toll vary from several hundred to several thousand, with thousands more wounded.

**Comment by dongyingt** [comment]
一般都是日本杂种说的话，认狗做父的，能觉着丢人吗？

**Comment by NainbowCat** [comment]
不好意思 真打的话 你们主子就算是寿终正寝了

**Comment by loveyanbei** [comment]
屠杀一批，拉拢一批，教育一批。
死硬的杀光，懂事的拉拢，不懂事的教育。
