### ISSUE TITLE
大伙都散了吧，没必要跟他们扯淡，到时候领土一收，人该去哪就让他们去哪

### ISSUE THREAD

**Issue by lixiangzan** [notepad-plus-plus/notepad-plus-plus#6492]
大伙都该工作的都工作吧，没必要跟他们这么吵，当个乐呵看就得了。这些年这种事经历的还少吗？看一看，笑一笑就得了。

**Comment by WPTomo** [comment]
到时候领土一收就又该添个逼脸说自己是中国人了

**Comment by CannibalKush** [comment]
The Tiananmen Square protests, commonly known in mainland China as the June Fourth Incident (Chinese: 六四事件, liùsì shìjiàn, literally six-four incident), were student-led demonstrations held in Tiananmen Square in Beijing during 1989. The popular national movement inspired by the Beijing protests is sometimes called the '89 Democracy Movement (Chinese: 八九民运, bājiǔ mínyùn). The protests started on April 15 and were forcibly suppressed on June 4 when the government declared martial law and sent the military to occupy central parts of Beijing. In what became known as the Tiananmen Square Massacre (Chinese: 天安门大屠杀), troops with assault rifles and tanks fired at the demonstrators and those trying to block the military's advance into Tiananmen Square. Estimates of the death toll vary from several hundred to several thousand, with thousands more wounded.

**Comment by zj299792458** [comment]
领土不收，又该哭唧唧找妈妈啦😂
