### ISSUE TITLE
大伙都散了吧，没必要跟他们扯淡，到时候领土一收，人该去哪就让他们去哪

### ISSUE THREAD

**Issue by momoxiaoming** [notepad-plus-plus/notepad-plus-plus#6494]
### Steps to Reproduce the Issue

1. 
2. 
3.

**Comment by MAFA2** [comment]
你这个反党反华暴徒！中国人民热爱和平，中国恪守在任何时候、任何情况下不首先使用核武器和无条件不对无核武器国家和无核武器区使用或威胁使用核武器的承诺。国家主席习近平在海南召开的博鳌论坛上表示，任何一个暴徒都不能破坏世界和平，“不能为一己之私把一个地区乃至世界搞乱”。
