### ISSUE TITLE
Ban China from Github

### ISSUE THREAD

**Issue by CannibalKush** [notepad-plus-plus/notepad-plus-plus#6496]
### Description of the Issue
Boards where legitimate discussion should take place are being overrun by Chinese nationalist spammers.

### Steps to Reproduce the Issue
1. Try to spread awareness of a critical human rights issue where the CCP is the perpetrator.

### Expected Behavior
Civil discussion and reasonable discourse

### Actual Behavior
Overrun by brainwashed Chinese.

### Steps to fix
Blanket ban the entire country of China from Github.

**Comment by SingleRela** [comment]
港独栽种，拿着你的横幅到内地来，敢么？

**Comment by SingleRela** [comment]
打爆你的狗头

**Comment by CannibalKush** [comment]
The Tiananmen Square protests, commonly known in mainland China as the June Fourth Incident (Chinese: 六四事件, liùsì shìjiàn, literally six-four incident), were student-led demonstrations held in Tiananmen Square in Beijing during 1989. The popular national movement inspired by the Beijing protests is sometimes called the '89 Democracy Movement (Chinese: 八九民运, bājiǔ mínyùn). The protests started on April 15 and were forcibly suppressed on June 4 when the government declared martial law and sent the military to occupy central parts of Beijing. In what became known as the Tiananmen Square Massacre (Chinese: 天安门大屠杀), troops with assault rifles and tanks fired at the demonstrators and those trying to block the military's advance into Tiananmen Square. Estimates of the death toll vary from several hundred to several thousand, with thousands more wounded.[2][3][4][5][6][7]

**Comment by Rojackse** [comment]
看把你牛逼的?微软敢禁中国?美国贸易战都不打了

**Comment by CannibalKush** [comment]
Set off by the death of pro-reform Communist general secretary Hu Yaobang in April 1989, amid the backdrop of rapid economic development and social changes in post-Mao China, the protests reflected anxieties about the country's future in the popular consciousness and among the political elite. The reforms of the 1980s had led to a nascent market economy which benefited some people but seriously disaffected others, and the one-party political system also faced a challenge of legitimacy. Common grievances at the time included inflation, corruption, limited preparedness of graduates for the new economy,[8] and restrictions on political participation. The students called for greater accountability, constitutional due process, democracy, freedom of the press, and freedom of speech, although they were highly disorganized and their goals varied.[9][10] At the height of the protests, about 1 million people assembled in the Square.[11]

**Comment by CannibalKush** [comment]
As the protests developed, the authorities responded with both conciliatory and hardline tactics, exposing deep divisions within the party leadership.[12] By May, a student-led hunger strike galvanized support for the demonstrators around the country, and the protests spread to some 400 cities.[13] Ultimately, China's paramount leader Deng Xiaoping and other Communist Party elders believed the protests to be a political threat and resolved to use force.[14][15] The State Council declared martial law on May 20 and mobilized as many as 300,000 troops to Beijing.[13] The troops advanced into central parts of Beijing on the city's major thoroughfares in the early morning hours of June 4, killing both demonstrators and bystanders in the process.

**Comment by CannibalKush** [comment]
The international community, human rights organizations, and political analysts condemned the Chinese government for the massacre. Western countries imposed arms embargoes on China.[16] The Chinese government made widespread arrests of protesters and their supporters, suppressed other protests around China, expelled foreign journalists, strictly controlled coverage of the events in the domestic press, strengthened the police and internal security forces, and demoted or purged officials it deemed sympathetic to the protests.[17] More broadly, the suppression halted the policies of liberalization in the 1980s. Considered a watershed event, the protests set the limits on political expression in China up to the present day.[18] Its memory is widely associated with questioning the legitimacy of Communist Party rule and remains one of the most sensitive and most widely censored topics in China.[19][20]

**Comment by space5566** [comment]
Tremble before us

**Comment by CannibalKush** [comment]
> Tremble before us

lol ok

**Comment by OrionsCore** [comment]
I've advocated for years for the surrounding countries of China to disconnect China from the internet. Cutting fibre cables, taking down satellites etc.

China is extremely hostile to our internet.

("our" meaning, everyone except China, as China is irresponsible, wreckless, and are proving themselves again today as being hostile shitheads with no intention to talk decently with others)

If China gets mad about their ability to perform many many scans on many many IP blocks, the ability to perform BGP leaks time and time again, and their ability to spew shit about their own country (while eating food tainted with gutter oil), being destroyed, then I fully advocate and endorse China being bombed or fully nuked. They've proven they cannot understand that actions have consequences, getting angry would reinforce that. I personally don't want to see a Chinese username in auth.log ever again.

Disconnect or nuke China.

**Comment by linweishuai** [comment]
Ban Ban  Ban你妈逼

**Comment by Glitchraptor** [comment]
isnt github already blocked in china or am i misremembering something

**Comment by CannibalKush** [comment]
> isnt github already blocked in china or am i misremembering something

Nope, it's one of the few things the CCP allows as it's indespensible to their software community (as it is everywhere)

**Comment by Hosou** [comment]
请问您有什么证据可以证明issuse中的骚动是中国共产党牵头的呢？
What's your proof that you said this chaos is lead by CCP?

请证明你自己并不是这场骚动的策划者、参与者和偏见者！认清现实，认清真相！
PLEASE PROOF YOURSELF！DON‘T LET OTHERS LEAD YOU!
