### ISSUE TITLE
Menu  _File  in Slovenian translation  _Datoteka  conflicts with Plugin Compare

### ISSUE THREAD

**Issue by msavli** [notepad-plus-plus/notepad-plus-plus#650]
In Slovenian translation is conflict with Compare Plugin.

If I want to pull down File menu, I press   <ALT>+<d> 
But this brings me up Compare dialog error which uses the same letters. 

But If I press <ALT>+<SHIFT>+<d> then it works. File menu is open in my Slovenian user interface.

![n _datoteka](https://cloud.githubusercontent.com/assets/13658822/9084920/8ad4b456-3b78-11e5-899c-c9d97b87c30a.PNG)

I see also, that this is case sensitive. 
I suggest a minor change to Plugin Compare as on the picture.
Alt+D   to be changed in   Alt+d

![n _comapre](https://cloud.githubusercontent.com/assets/13658822/9085067/d7fa22a6-3b79-11e5-82cc-c281f9bb124b.jpg)

Version: Notepad++ v.6.8.1
OS: Win XP SP2

**Comment by aaaxx** [comment]
You can change the Compare shortcut yourself here:
Nastavitve > Bližnjice... > Plugin commands > "Compare"

It would be near impossible to find a default shortcut that wouldn't cause a conflict in any language.

PS: the letters used in shortcuts aren't case-sensitive.
