### ISSUE TITLE
一口支那人支那人的，我真的笑了，不认你中国爹就算了，何必连自己都骂？还带上你父母祖宗？不知他们在天之灵看到你如此忤逆会作何感想呢？ 你尽管放心，我们不生气。你们想更换自己血统和基因，用“支那”来意淫自己不是炎黄子孙。无所谓的，你们爱骂自己我们也就笑笑，你们想当美国日本的舔🐶我们也只能笑笑，想着可能在你们眼里，美日的🌼更有味道吧。 台湾省本就没想着能和平回归，也就二三十年后吧，武力夺回。希望到时候你们舔了百来年的美日能保你一命。

### ISSUE THREAD

**Issue by softarts** [notepad-plus-plus/notepad-plus-plus#6500]
### Steps to Reproduce the Issue

1. 
2. 
3.

**Comment by delayAdderGain** [comment]
支那賤畜趕快叫你爹開坦克去香港阿? 不敢?

**Comment by chinyichun** [comment]
你主子共产党高官把自己的家人和他们从你口袋里搜刮的民脂民膏一并转移欧美。你主子共产党高官当美国日本的舔🐶比我们还起劲，美日的🌼在你主子共产党高官那儿更有味道吧！

**Comment by shanghaiexpress** [comment]
天天喝美式咖啡，依然不是美国人；在Costco商场摆拍“假装在洛杉矶”，实际上还是在支那；追赶西方潮流去关心环境变化和动物权益装的像西方左派知识分子似的，但对魔幻支那里关于自由人权的议题屁都不敢放一个。

铁拳砸下来才知道，平常看起来的国际化现代化文明化，装出来的和发达国家城市平起平坐，都是假的

支多玛就是支多玛，它或许能在某些地方装成和世界一样，但骨子里还是支那的唯上不唯下，从未在心里尊重别人的权益，从未在心里尊重过民主和法制。所以我在这里劝大家，能跑的就跑，即使是支那的所谓一线城市，和文明世界也是云泥之别。
