### ISSUE TITLE
台湾领土是中国不可分割的一部分，坚持一个中国原则，Taiwan is an inalienable part of the Chinese territory.Adhere to the one-China principle.

### ISSUE THREAD

**Issue by Untable** [notepad-plus-plus/notepad-plus-plus#6501]
### Steps to Reproduce the Issue

1. 
2. 
3.

**Comment by pjt57364413** [comment]
中国台湾省

**Comment by etopian** [comment]
Gleichschaltung (German pronunciation: [ˈɡlaɪçʃaltʊŋ]), or in English co-ordination, was in Nazi terminology the process of Nazification by which Adolf Hitler and the Nazi Party successively established a system of totalitarian control and coordination over all aspects of German society and societies occupied by Nazi Germany "from the economy and trade associations to the media, culture and education".

When the blatant emphasis of racial hatred of others seemed to reach an impasse in the school system, through radio broadcasts, or on film reels, the overseers of Nazi Gleichschaltung propaganda switched to strategies that focused more on togetherness and the "we-consciousness" of the collective Volk, but the mandates of Nazi "coordination" remained: pay homage to the Führer, expel all foreigners, sacrifice for the German people, and welcome future challenges.[36] While greater German social and economic unity was produced through the Gleichschaltung initiatives of the regime, it was at the expense of individuality and to the social detriment of any nonconformist;[37] and worse—it contributed to and reinforced the social and racial exclusion of anyone deemed an enemy by National Socialist doctrine

https://en.wikipedia.org/wiki/Gleichschaltung

**Comment by Mikotochan** [comment]
@Untable @pjt57364413 Hi! Taiwan is an independent country which has no land claims against the PRC, just like the PRC has no valid claims against the republic of Taiwan :3
