### ISSUE TITLE
早则建党一百年，迟则建国一百年，和则相安无事，独则武力统台。

### ISSUE THREAD

**Issue by K-ream** [notepad-plus-plus/notepad-plus-plus#6510]
早则建党一百年，迟则建国一百年，和则相安无事，独则武力统台。

**Comment by zrzjohn** [comment]
有一说一嗷 一边骂作者 一边继续用作者费劲肝脏写的程序 他 不香吗 软件是好软件 功能是好功能 作者辱华也没碍着我们继续用他的肝脏结晶啊...我们又不为他创造收益
