### ISSUE TITLE
Please let them taste the power of free speech! No more censorship to erase dissenting opinions 

### ISSUE THREAD

**Issue by zj299792458** [notepad-plus-plus/notepad-plus-plus#6517]
I'm from mainland China, and I choose to stand with human rights.

**Comment by lixiangzan** [comment]
> I'm from mainland China, and I choose to stand with human rights.

You're talking about something else. I also stand on the rights of the people, but this problem can only be solved by ourselves, not by the United States. I firmly oppose the split of the motherland.

**Comment by zj299792458** [comment]
> > I'm from mainland China, and I choose to stand with human rights.
> 
> You're talking about something else. I also stand on the rights of the people, but this problem can only be solved by ourselves, not by the United States. I firmly oppose the split of the motherland.

What the author said has nothing to do about splitting lands, not a single word. What will splitting benefit him? Try not to drown in your imagination.

**Comment by lixiangzan** [comment]
> > > I'm from mainland China, and I choose to stand with human rights.
> > 
> > 
> > You're talking about something else. I also stand on the rights of the people, but this problem can only be solved by ourselves, not by the United States. I firmly oppose the split of the motherland.
> 
> What the author said has nothing to do about splitting lands, not a single word. What will splitting benefit him? Try not to drown in your imagination.

I'm not in favor of splitting the motherland. Please don't over think.And do you know the author？Try not to drown in your imagination.

**Comment by zj299792458** [comment]
> > > > I'm from mainland China, and I choose to stand with human rights.
> > > 
> > > 
> > > You're talking about something else. I also stand on the rights of the people, but this problem can only be solved by ourselves, not by the United States. I firmly oppose the split of the motherland.
> > 
> > 
> > What the author said has nothing to do about splitting lands, not a single word. What will splitting benefit him? Try not to drown in your imagination.
> 
> I'm not in favor of splitting the motherland. Please don't over think.And do you know the author？Try not to drown in your imagination.

I don't need to "know" the author, I choose to "see" what he wrote.

**Comment by zsynacl** [comment]
> > > > > I'm from mainland China, and I choose to stand with human rights.
> > > > 
> > > > 
> > > > You're talking about something else. I also stand on the rights of the people, but this problem can only be solved by ourselves, not by the United States. I firmly oppose the split of the motherland.
> > > 
> > > 
> > > What the author said has nothing to do about splitting lands, not a single word. What will splitting benefit him? Try not to drown in your imagination.
> > 
> > 
> > I'm not in favor of splitting the motherland. Please don't over think.And do you know the author？Try not to drown in your imagination.
> 
> I don't need to "know" the author, I choose to "see" what he wrote.

you should believe what you SEE not something 'saw' in other people's words.
Believe in something wrote in 'words'? Just think about twitter from some president.

**Comment by lixiangzan** [comment]
> > > > > I'm from mainland China, and I choose to stand with human rights.
> > > > 
> > > > 
> > > > You're talking about something else. I also stand on the rights of the people, but this problem can only be solved by ourselves, not by the United States. I firmly oppose the split of the motherland.
> > > 
> > > 
> > > What the author said has nothing to do about splitting lands, not a single word. What will splitting benefit him? Try not to drown in your imagination.
> > 
> > 
> > I'm not in favor of splitting the motherland. Please don't over think.And do you know the author？Try not to drown in your imagination.
> 
> I don't need to "know" the author, I choose to "see" what he wrote.

新疆存不存在人权问题？存在，不只新疆存在，全中国都存在。新疆确实存在作者说的这些问题吗？什么再教育营、维吾尔族是恐怖组织等等，这些事情明显都是捏造的事情。包括维吾尔族在内的少数民族在中国都是受到优待政策的，不知道你小时候有没有见到过新疆人卖切糕。对于新疆有极端思想的人进行打压也是存在的，我支持这种打压难道你想让几年前的恐怖事件继续发生吗？本人因为母亲从事的行业能够接触到新疆，能够了解到一些。我认为现在的新疆政策是合理的。像你所说的，多看看，有时间去新疆看看，不要只看反华势力怎么写。
