### ISSUE TITLE
Uninstalled

### ISSUE THREAD

**Issue by yojhop** [notepad-plus-plus/notepad-plus-plus#6518]
The tool is just ok, but the author make me feel sick.

**Comment by proteriax** [comment]
Literally nobody cares.

**Comment by CannibalKush** [comment]
Thank you, don't come back.

**Comment by yojhop** [comment]
thanks for letting me know sublime text, a much better tool!

**Comment by clavinet** [comment]
> The tool is just ok, but the author make me feel sick.

how does that boot taste?

**Comment by collinoswalt** [comment]
> The 1989 Tiananmen Square protests, commonly known in mainland China as the June Fourth Incident (Chinese: 六四事件, liùsì shìjiàn), were student-led demonstrations in Beijing (the capital of the People's Republic of China) for the establishment of basic human and press rights and against the Communist-led Chinese government in mid-1989. More broadly, it refers to the popular national movement inspired by the Beijing protests during that period, sometimes called the '89 Democracy Movement (Chinese: 八九民运, bājiǔ mínyùn). The protests were forcibly suppressed after Chinese Premier Li Pengdeclared martial law. In what became known as the Tiananmen Square Massacre, troops with assault rifles and tanks fired at the demonstrators trying to block the military's advance towards Tiananmen Square. The number of civilian deaths was internally estimated by the Chinese government to be near or above 10,000.

![](https://www.abc.net.au/news/image/7935078-3x2-700x467.jpg)

![](http://www.visiontimes.com/uploads/2016/06/20160601082332180.jpg)

![](https://www.liberationnews.org/wp-content/uploads/2014/06/698a2900-9371-11e6-a1dc-bdf38d484582.jpeg)

![](https://i.redd.it/ltfzkhk07ff21.png)

![](https://www.dailydot.com/wp-content/uploads/2019/08/tiananmen-square-1989-massacre-aftermath.jpg)

![](https://www.nationalgeographic.com/content/dam/news/photos/000/803/80352.jpg)

**Comment by Mikotochan** [comment]
> thanks for letting me know sublime text, a much better tool!

Sublime is non-free software. You are only harming yourself by using it.
