### ISSUE TITLE
Saving settings to OneDrive on Windows 10

### ISSUE THREAD

**Issue by stevenmulgrew** [notepad-plus-plus/notepad-plus-plus#652]
After upgrading to Windows 10 I notice that in Preferences > Cloud the option for OneDrive is disabled.
I've had a similar issue on a project of my own.
I used to look in these keys for a UserFolder value
HKEY_CURRENT_USER\Software\Microsoft\SkyDrive
HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\SkyDrive

These now have gone and you have to look in the 64bit registry for
HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\SyncRootManager\OneDrive!S-1-5-21-2282142480-1655623660-775239353-1001!Personal\UserSyncRoots
where S-1-5-21-2282142480-1655623660-775239353-1001 is the security identifier of the currently logged on Windows user

![image](https://cloud.githubusercontent.com/assets/955118/9098764/b1e3238e-3bc3-11e5-8fb1-1aac4904a09c.png)

**Comment by Croydon** [comment]
If you upgrade to the latest Notepad++ version you don't have options for specific cloud solutions anymore, but you can set a path to a (cloud-)folder (which can be ofc also OneDrive). 
Thanks to this change Notepad++ is now supporting basically any cloud solution and doesn't need to keep track of all of this API changes, which could break compatibility.

**Comment by milipili** [comment]
Indeed check the latest version  :)
