### ISSUE TITLE
屌你老母,杏+橙.就中意睇你尼地废材天天意淫,却对我地中华复兴无可奈何噶样子.屌你老母臭嗨.China No.1!!!

### ISSUE THREAD

**Issue by qianyedoufulao** [notepad-plus-plus/notepad-plus-plus#6521]
屌你老母,杏+橙.就中意睇你尼地废材天天意淫,却对我地中华复兴无可奈何噶样子.屌你老母臭嗨.China No.1!!!

**Comment by JLPathos** [comment]
cool story bro

**Comment by NainbowCat** [comment]
is this the best you can do? then you are really trash people. at least the author can reasoning and arguing, but all you do all day long is f && f.

**Comment by AlexVincent525** [comment]
@NainbowCat Step out with your tiny thought and brain, cause your contribution is as small as your D.

**Comment by qianyedoufulao** [comment]
> is this the best you can do? then you are really trash people. at least the author can reasoning and arguing, but all you do all day long is f && f.

This kind of behavior is exactly the best U can do. China will revive sooner or later.What Taiwanese can do is sew the Chinese flag on the night before liberation
