### ISSUE TITLE
其实维吾尔族在国内地位不比你们台湾省人低,所以不要瞎意淫了

### ISSUE THREAD

**Issue by Rojackse** [notepad-plus-plus/notepad-plus-plus#6522]
### Steps to Reproduce the Issue

1. 
2. 
3.

**Comment by ailewl** [comment]
![image](https://user-images.githubusercontent.com/31687234/67841546-4d485280-fb33-11e9-8bf1-296d07c89d26.png)
![image](https://user-images.githubusercontent.com/31687234/67841546-4d485280-fb33-11e9-8bf1-296d07c89d26.png)
![image](https://user-images.githubusercontent.com/31687234/67841546-4d485280-fb33-11e9-8bf1-296d07c89d26.png)
![image](https://user-images.githubusercontent.com/31687234/67841546-4d485280-fb33-11e9-8bf1-296d07c89d26.png)
![image](https://user-images.githubusercontent.com/31687234/67841546-4d485280-fb33-11e9-8bf1-296d07c89d26.png)
![image](https://user-images.githubusercontent.com/31687234/67841546-4d485280-fb33-11e9-8bf1-296d07c89d26.png)
![image](https://user-images.githubusercontent.com/31687234/67841546-4d485280-fb33-11e9-8bf1-296d07c89d26.png)
![image](https://user-images.githubusercontent.com/31687234/67841546-4d485280-fb33-11e9-8bf1-296d07c89d26.png)
![image](https://user-images.githubusercontent.com/31687234/67841546-4d485280-fb33-11e9-8bf1-296d07c89d26.png)
![image](https://user-images.githubusercontent.com/31687234/67841546-4d485280-fb33-11e9-8bf1-296d07c89d26.png)
![image](https://user-images.githubusercontent.com/31687234/67841546-4d485280-fb33-11e9-8bf1-296d07c89d26.png)
