### ISSUE TITLE
中國人再一次讓世界看笑話了

### ISSUE THREAD

**Issue by Nkeys** [notepad-plus-plus/notepad-plus-plus#6524]
中國人 丟臉 難看

醒醒吧

還不知道你們在台灣 日本 美國 德國....等西方國家的眼中就是是世界毒瘤

來看看中國人有多丟臉：
https://www.youtube.com/watch?v=qPjdom1ZT6o

**Comment by assad2008** [comment]
> 中國人 丟臉 難看
> 
> 醒醒吧
> 
> 還不知道你們在台灣 日本 美國 德國....等西方國家的眼中就是是世界毒瘤
> 
> 來看看中國人有多丟臉：
> https://www.youtube.com/watch?v=qPjdom1ZT6o

啥SB视频，你才真正丢中国人的脸！！！

**Comment by GHYOWEE** [comment]
十個灣灣九個騙，還剩一個在訓練

**Comment by Nkeys** [comment]
哈哈哈 你開心就好
你們中國人就躲在自己的小圈圈意淫吧

改變不了你們中國人在世界其他文明國家眼中很可笑的事實

**Comment by saberChen** [comment]
目前台湾政府才是世界范围内的笑话，舔日本舔美国，人家都不鸟你们，外交国都没了，笑屁啊，哈哈哈哈

**Comment by mh1995** [comment]
哈哈 美国养的狗还想当个人  还想平起平坐

**Comment by dongyingt** [comment]
然而并没有，看的都是日杂种，英杂种，美杂种的笑话

**Comment by Nkeys** [comment]
當美國狗不錯啊 至少你還是狗
當中國人的話 狗都瞧不起你

**Comment by yinTang** [comment]
什么时候狗也会打繁体中文了，很神奇！！！

**Comment by MountainLovers** [comment]
看看阿拉伯之春，给人民带来了什么？饭都吃不上还谈民主？看看这几天智利的游行，警察也没那么民主自由的看着嘛，那不是该拘留拘留该驱逐驱逐？你看到了这些垃圾媒体的报导，你认为我们的媒体是假的，那我们为什么认为你们的媒体是公平正义的象征？最后说一句，GitHub是全世界的代码爱好者交流的社区，不是给你们来发表偏见的。我们中国人正在一点点走出去，从未固步自封，如果你想知道更多的真相，就请你来中国大陆来看看吧，别做一只井底之蛙。

**Comment by Morse1113** [comment]
哎，真无语。
你来过中国大陆吗，你来看过吗，你了解人们的普通生活吗。不要只是在你们那个岛内，看看西方媒体的新闻就下这种结论。中国有14亿人，960万平方公里的土地，不管西方或者是岛内媒体渲染成什么样，你可以来看看嘛，如果你去过大陆10个以上的城市待过半年以上还是有这种想法，那你随便黑。多去几个国家，对比下人民的生活，别老是张口就来。
中国人可不是自己的小圈圈，很多人出去走遍世界各地，还是觉得祖国好，这是有原因的。

**Comment by a12305100** [comment]
反正臺灣從來不屬於中華人民共和國，
你們就繼續吸維尼吧～
