### ISSUE TITLE
How much did the arms dealer give you

### ISSUE THREAD

**Issue by BigRamean** [notepad-plus-plus/notepad-plus-plus#6529]
Freedom of speech does not equate to irresponsibility.
Please take a long view, fallen angel.

**Comment by ailewl** [comment]
![image](https://user-images.githubusercontent.com/31687234/67841546-4d485280-fb33-11e9-8bf1-296d07c89d26.png)

**Comment by OrionsCore** [comment]
![image](https://user-images.githubusercontent.com/56843849/67846832-c2973180-faf9-11e9-8334-daa8cda9d776.png)

You guys are all shitheads.

Reported to GitHub for threatening people. Third time now.

**Comment by BigRamean** [comment]
Urinate and look in the mirror,please.

**Comment by OrionsCore** [comment]
> Urinate and look in the mirror,please.

Thanks, I laughed. Where did you find this "insult"? hahaha

Work on your insults on your new account.

**Comment by BigRamean** [comment]
thanks, you too.

**Comment by OrionsCore** [comment]
Mine at least make sense.

Unrelated:
https://www.youtube.com/watch?v=zrv78nG9R04

**Comment by BigRamean** [comment]
???I've already seen it, my friend. Why don't you talk about India

**Comment by collinoswalt** [comment]
> The 1989 Tiananmen Square protests, commonly known in mainland China as the June Fourth Incident (Chinese: 六四事件, liùsì shìjiàn), were student-led demonstrations in Beijing (the capital of the People's Republic of China) for the establishment of basic human and press rights and against the Communist-led Chinese government in mid-1989. More broadly, it refers to the popular national movement inspired by the Beijing protests during that period, sometimes called the '89 Democracy Movement (Chinese: 八九民运, bājiǔ mínyùn). The protests were forcibly suppressed after Chinese Premier Li Pengdeclared martial law. In what became known as the Tiananmen Square Massacre, troops with assault rifles and tanks fired at the demonstrators trying to block the military's advance towards Tiananmen Square. The number of civilian deaths was internally estimated by the Chinese government to be near or above 10,000.

![](https://www.abc.net.au/news/image/7935078-3x2-700x467.jpg)

![](http://www.visiontimes.com/uploads/2016/06/20160601082332180.jpg)

![](https://www.liberationnews.org/wp-content/uploads/2014/06/698a2900-9371-11e6-a1dc-bdf38d484582.jpeg)

![](https://i.redd.it/ltfzkhk07ff21.png)

![](https://www.dailydot.com/wp-content/uploads/2019/08/tiananmen-square-1989-massacre-aftermath.jpg)

![](https://www.nationalgeographic.com/content/dam/news/photos/000/803/80352.jpg)

**Comment by BigRamean** [comment]
Are you an artificial intelligence robot?

**Comment by collinoswalt** [comment]
no

**Comment by BigRamean** [comment]
Can you tell me what happened this year?

**Comment by collinoswalt** [comment]
@BigRamean in 1989, Students in Beijing protested against the communist government for human rights. In response, PRC murdered 10,000 people

**Comment by BigRamean** [comment]
You're going around, OK

**Comment by collinoswalt** [comment]
@BigRamean You asked what happened in 1989, so I told you what happened in 1989. What else do you want?

**Comment by BigRamean** [comment]
This year is 2019.

**Comment by Mikotochan** [comment]
> Freedom of speech does not equate to irresponsibility.

Are you claiming that the notepad++ developer was being irresponsible? If so, how so?

**Comment by Mikotochan** [comment]
@SayHelloBriggs please reply to my question :(
