### ISSUE TITLE
双标不要太过分了😂

### ISSUE THREAD

**Issue by bckps7336** [notepad-plus-plus/notepad-plus-plus#6530]
不止notepad++支持新疆,还有go语言主要开发者支持港独！而go语言明目张胆放在github上，说明github已沦为cia的政治工具，我已向工信部提交投诉举报，同时我已举报：
csdn.com 罪状：明目张胆发布go教程
stackoverflow 罪状：竟然不删除go和notepad相关问题
leetcode.com 罪状：敢支持使用go语言，该杀

这些可恶的美国人以为用免费软件就可以控制中国，谁能想到，没有google我们有百度，没有go我们有e语言，没有github我们有gitee，没有chrome我们有360，坚定支持政府打压境外发动势力，谁敢反对我举报非法境外网站，送你一句：你们这些牧羊犬，不上美国网站你会死？不爱用别用，用你美国爹的东西去！
#6400

**Comment by ailewl** [comment]
![image](https://user-images.githubusercontent.com/31687234/67841546-4d485280-fb33-11e9-8bf1-296d07c89d26.png)

**Comment by buffge** [comment]
你他娘的真是个呆逼

**Comment by mis101247** [comment]
慢走不送 乖乖去用您們的gitee

**Comment by imgradeone** [comment]
白癡，大陆人看了都觉得恶心。
