### ISSUE TITLE
stop joking

### ISSUE THREAD

**Issue by tichstar** [notepad-plus-plus/notepad-plus-plus#6532]
Taiwan is an inalienable part of Chinese territory !!!

**Comment by ailewl** [comment]
![image](https://user-images.githubusercontent.com/31687234/67841546-4d485280-fb33-11e9-8bf1-296d07c89d26.png)

**Comment by fuzxxl** [comment]
It is!  Of the Republic of China!

**Comment by collinoswalt** [comment]
Taiwan \#1

![](https://i.imgur.com/xxFUNLF.jpg)

> The 1989 Tiananmen Square protests, commonly known in mainland China as the June Fourth Incident (Chinese: 六四事件, liùsì shìjiàn), were student-led demonstrations in Beijing (the capital of the People's Republic of China) for the establishment of basic human and press rights and against the Communist-led Chinese government in mid-1989. More broadly, it refers to the popular national movement inspired by the Beijing protests during that period, sometimes called the '89 Democracy Movement (Chinese: 八九民运, bājiǔ mínyùn). The protests were forcibly suppressed after Chinese Premier Li Pengdeclared martial law. In what became known as the Tiananmen Square Massacre, troops with assault rifles and tanks fired at the demonstrators trying to block the military's advance towards Tiananmen Square. The number of civilian deaths was internally estimated by the Chinese government to be near or above 10,000.

**Comment by collinoswalt** [comment]
![](https://www.abc.net.au/news/image/7935078-3x2-700x467.jpg)

![](http://www.visiontimes.com/uploads/2016/06/20160601082332180.jpg)

![](https://www.liberationnews.org/wp-content/uploads/2014/06/698a2900-9371-11e6-a1dc-bdf38d484582.jpeg)

![](https://i.redd.it/ltfzkhk07ff21.png)

![](https://www.dailydot.com/wp-content/uploads/2019/08/tiananmen-square-1989-massacre-aftermath.jpg)

![](http://www.cnd.org/June4th/photos/mascr002.gif)
