### ISSUE TITLE
这个作者只是为了炒作而已

### ISSUE THREAD

**Issue by apktocoder** [notepad-plus-plus/notepad-plus-plus#6534]
### Steps to Reproduce the Issue

1. 
2. 
3.

**Comment by ailewl** [comment]
![image](https://user-images.githubusercontent.com/31687234/67841546-4d485280-fb33-11e9-8bf1-296d07c89d26.png)

**Comment by Rojackse** [comment]
所以帮他一把啊,最好请去喝茶

**Comment by Rojackse** [comment]
真当管不了他了还

**Comment by saberChen** [comment]
所以怼的时候带上作者一起，不作为，不管不顾，辣鸡项目
