### ISSUE TITLE
This is not USA vs China. This is China vs the world. You are making a fool of yourself.

### ISSUE THREAD

**Issue by CannibalKush** [notepad-plus-plus/notepad-plus-plus#6538]
You should know that you're really just embarassing China right now.

**Comment by eavictor** [comment]
Can't agree anymore.

GitHub issues is the place to report issue related to the project itself,
not the place for spamming meaningless Simplified Chinese.

**Comment by yinTang** [comment]
Do you think that a normal Chinese is willing to come here to make some boring political problems? Are some insurgents.....

**Comment by ranetpgit** [comment]
> 
> 
> Do you think that a normal Chinese is willing to come here to make some boring political problems? Are some insurgents.....

https://github.com/notepad-plus-plus/notepad-plus-plus/issues/6705

Really makes you think
