### ISSUE TITLE
西方圣母婊真多.我们过得好不好是你嘴说出来的?天天黑,马上 GDP要世界第一啦

### ISSUE THREAD

**Issue by buffge** [notepad-plus-plus/notepad-plus-plus#6539]
没出墙前 以为墙外有真相 后来发现国内的才是真相. 每次看见那群轮子就烦
不过我也体谅你们外国人,毕竟你们发展比不过我们,要想办法抹黑我们.以为可以分裂中国.问过解放军了吗

En:
There are so many Notre Dame bitches in the West. How are we doing? You said it. It's dark every day, and GDP will be the first in the world

Before I left the wall, I thought there was truth outside the wall, and then I found out that the truth was the truth in China. I was annoyed every time I saw those wheels.

But I also understand you foreigners. After all, you can't compete with us in development. We need to find a way to smear us. We think we can split China. Have you asked the PLA?

**Comment by Glitchraptor** [comment]
lmfao what
