### ISSUE TITLE
Stop sending meaningless political-related issues, it just makes you look like an idiot

### ISSUE THREAD

**Issue by Rinacm** [notepad-plus-plus/notepad-plus-plus#6540]
No matter you are nationalism, anti-Chinese or a HK-democracy-supporter or someone else, github issue's for communication problems, it's not a political debate or a place to throw rubbishes, if you are unsatisfied with the author of this repo, you can try _**CONTACT HIM PERSONALLY**_ or express your opinion in other appropriate platform instead of sending meaningless issues which makes you like a ugly monkey

不管是港独小粉红还是 _**激寒反串人**_ ，不要在github上发表无关的政治言论，github的issue功能是用来交流问题和bug的，而不是拿来作为政治辩论和让你倾倒垃圾的场合，如果你对于repo的作者有 _**极大的不满**_ ，你可以尝试找到手段私信作者或者去发在合适的平台上(比如微博贴吧推特fb)，而不是在这里发表谩骂或者政治言论，只会让你看上去像个跳梁小丑。

**Comment by buffge** [comment]
他能恶心我们,我们为什么不能恶心他?

He can disgust us. Why can't we disgust him?

**Comment by flyer88** [comment]
so，why the author can say this ?
Come On! Notepad++ just a tool !!
why he can do this ?
![image](https://user-images.githubusercontent.com/7564330/67847156-550cf480-fb3d-11e9-9608-557e4223332c.png)

**Comment by neodreamtale** [comment]
> 他能恶心我们,我们为什么不能恶心他?
> 
> He can disgust us. Why can't we disgust him?

郭德纲说：“比如我和火箭专家说，你那火箭不行，燃料不好，我认为得烧柴，最好是烧煤，煤还得精选煤，水洗煤不行。如果那科学家拿正眼看我一眼，那他就输了”

**Comment by Rinacm** [comment]
> 他能恶心我们,我们为什么不能恶心他?
> 
> He can disgust us. Why can't we disgust him?

恶心不恶心他们随你自由，只是在github的issue板块发类似言论会严重影响到正常用户，比如我，我上面说了，你在推特fb微博贴吧哪里发表都行，但是不要在github上发表

disgust them or not is you freedom, but if you talk about this on github will affect other normal users, I've mentioned that you could say "npp's author is piece of shit" on other appropriate platform, but not on github

**Comment by Rinacm** [comment]
> > 他能恶心我们,我们为什么不能恶心他?
> > He can disgust us. Why can't we disgust him?
> 
> 郭德纲说：“比如我和火箭专家说，你那火箭不行，燃料不好，我认为得烧柴，最好是烧煤，煤还得精选煤，水洗煤不行。如果那科学家拿正眼看我一眼，那他就输了”

精辟的回答

brilliant answer

**Comment by JLPathos** [comment]
> 他能恶心我们,我们为什么不能恶心他?
> 
> He can disgust us. Why can't we disgust him?

Then send him an email instead of using the issues section you moron

**Comment by buffge** [comment]
> > 他能恶心我们,我们为什么不能恶心他?
> > He can disgust us. Why can't we disgust him?
> 
> Then send him an email instead of using the issues section you moron

You're smart enough to catch up with the maggots in my bathroom.

**Comment by x-t** [comment]
It's beyond fucked man, this issues section is a messier trainwreck than Gare de Lyon.

**Comment by Korb** [comment]
This is a duplicate of #6288 (disrespect for other members of the FOSS community by posting political propaganda spam in text editor resources).
