### ISSUE TITLE
请问哪里可以举报，涉政软件应该不符合一些规则吧。一个记事本很容易被替代的。

### ISSUE THREAD

**Issue by liuem** [notepad-plus-plus/notepad-plus-plus#6542]
请问哪里可以举报，涉政软件应该不符合一些规则吧。一个记事本很容易被替代的，此消彼长，给替代者一些机会。

**Comment by liuem** [comment]
作者就是台独分子，然而人家又删除评论的权限，这就会导致他不想让人看到的全部删除，只留下片面的有误导性的词语。

**Comment by delayAdderGain** [comment]
中國人的腦子是不是哪里有問題?
舉報 ? 涉政 ? 不好意思喔, 在中國以外的其他國家, 政治就像空氣, 是生活的一部分

**Comment by CSW416** [comment]
> 中國人的腦子是不是哪里有問題?
> 舉報 ? 涉政 ? 不好意思喔, 在中國以外的其他國家, 政治就像空氣, 是生活的一部分

跪求台湾公投，宣布独立

**Comment by WaveBird** [comment]
剛來吃瓜，哪位可以解釋一下？

**Comment by liuem** [comment]
> 中國人的腦子是不是哪里有問題?
> 舉報 ? 涉政 ? 不好意思喔, 在中國以外的其他國家, 政治就像空氣, 是生活的一部分

那真的是太悲哀了，我爱中国。这里我过得无忧无虑。

**Comment by liuem** [comment]
> 中國人的腦子是不是哪里有問題?
> 舉報 ? 涉政 ? 不好意思喔, 在中國以外的其他國家, 政治就像空氣, 是生活的一部分

另外我不赞同你的话，日本也是美国的走狗，就没你所说的就像空气，政治事件就应该让搞政治的人去处理，在一个软件开源平台扯什么政治。

**Comment by woshifengzhao** [comment]
这位江西的刘先生真是可爱，github是你家的么，是不是还成涉政暴恐网站了？
www.12377.cn 请去举报吧
顺便把 https://github.com/gfwlist/gfwlist 也举报了吧，里面一大堆涉黄涉政的网站地址
