### ISSUE TITLE
CPP 可以黑的东西可多了，非要挑这种无脑黑，整的跟个脑残一样。台湾人真的是眼界越来越狭隘了

### ISSUE THREAD

**Issue by shesl-meow** [notepad-plus-plus/notepad-plus-plus#6545]

**Comment by Masterbaiter** [comment]
支共对维吾尔人进行的种族灭绝就是目前人类文明面临的最大危机，当然不是无脑黑。只有支共的走狗们面对证据的无脑否认。

**Comment by shesl-meow** [comment]
> 支共对维吾尔人进行的种族灭绝就是目前人类文明面临的最大危机，当然不是无脑黑。只有支共的走狗们面对证据的无脑否认。

证据？

**Comment by disc9562** [comment]
證據就在你眼前，你根本不願去相信，說什麼呢

**Comment by shesl-meow** [comment]
> 證據就在你眼前，你根本不願去相信，說什麼呢

证据不在我眼前，我并没有生活在一个有维吾尔族的地方。我也没有不愿相信。

现代法律讲究疑罪从无，你不要不举证，就给所有大陆人套上一个偏见的帽子。
