### ISSUE TITLE
Light Explorer "Synchronize tree with current document" broken?

### ISSUE THREAD

**Issue by vlakoff** [notepad-plus-plus/notepad-plus-plus#655]
It seems the "Synchronize tree with current document" right-click command of Light Explorer plugin doesn't work anymore (nothing happens).

I tried with Notepad++ 6.7.9.2 and 6.8.1.
Windows 7 64-bit.

Do other people encounter the same issue?

**Comment by vlakoff** [comment]
I think you can tag it as bug/plugin, though confirmation of the issue by other users would be welcome.

**Comment by cmeriaux** [comment]
Hello,
I confirm the problem. I reproduce this problem with npp 6.8.2 
compiled with :
Revision: 091082c31ca52e0053b6af8aef73fcc224a2eddc
Author: Don HO <don.h@free.fr>
Date: 22/08/2015 19:27:10
Message:
[REMOVE] Remove unpopular file extensions

**Comment by vlakoff** [comment]
Now it works again, though I didn't update Notepad++ nor the Light Explorer plugin…
Probably some [mandelbug](https://en.wikipedia.org/wiki/Heisenbug#Related_terms)… :-\

**Comment by vlakoff** [comment]
Closing, as it does work almost all the time.

**Comment by vlakoff** [comment]
Hint: when Light Explorer fails to expand the folders, you can "help" it by manually expanding a few of the folders. This works most of the time.
