### ISSUE TITLE
Setup starts notepad++ as administrator

### ISSUE THREAD

**Issue by Dorus** [notepad-plus-plus/notepad-plus-plus#656]
When updating Notepad++, the setup ask if you want to start Notepad++. Doing so starts notepad++ as administrator.

This cause all kind of problems for me, for example you can't drag files onto notepadd+ to open them when notepad++ is running as administrator. I have some files open on a network share, somehow it cannot access these files in administrator mode, as a result the files are closed, and no longer opened by session-restore on the next start-up.

**Comment by milipili** [comment]
See #159
