### ISSUE TITLE
拙见

### ISSUE THREAD

**Issue by 382615666** [notepad-plus-plus/notepad-plus-plus#6565]
### Steps to Reproduce the Issue

1. 
2. 
3. 

### Debug Information

1. 我从来都热爱我生活的这块土地

2. 我从来都热爱的祖国

3. 从不否认任何一个地方有黑暗地带

4. 相信你看的懂简体中文

每个人都有自己的想法，存在即为合理，我可以理解，但是不予支持

或许台湾在你的心中是独立的，可是国际上的地位为什么不予承认

不要总是拿内陆体质的缺点去跟欧美体质的长处进行比较，好比拿着一个人的缺点跟另外一个人的优点进行比较

任何东西都有两面性，有所得必有所牺牲，大陆是不是比欧美更安定？欧美或许更自由，枪机事件是不是比内陆更多

同样痛恨现在某些公务员的腐败，那么欧美，台湾难道没有？其实这是人性，跟国家和历史无关

任何事件的发生，不要总是站在一个角度来看待，也不要急着发表观点。如果内陆真的如你所说，如你所想，镇压10多亿的人，你觉得哪个国家能做到？

任何一个人都会犯错，任何一个国家都有黑历史，这个是必然。历史的真正用处是用来总结，吸取经验教训和反省，而不是一直用来做破坏，一段历史或许影响一代，两代，甚至三代人，但是不能一直影响后代，否则这是罪过。

任何地方，国家都有自己的历史和文化，现在拥有的都是留下来精华和正在产生和淘汰的新生文化。辩证的看待新生文化，谦虚的学习传承文化。台湾有自己的文化，大陆也有自己的文化，请谦虚的学习，不高看别人，不低看别人，不高看自己，不低看自己

会英文是一种能力，而不是必须，没必要拿出来炫耀，各有所长而已。

最后，既然台湾用的是繁体中文，大陆用的是简体中文，那说明文字的演变是来自同一时期。文字的统一源于书同文，车同轨，建议去了解下文字的历史。

**Comment by K-ream** [comment]
台湾没有历史啦
它要搞自己的孤岛历史
