### ISSUE TITLE
nage nage nage nage

### ISSUE THREAD

**Issue by Rojackse** [notepad-plus-plus/notepad-plus-plus#6566]
### Steps to Reproduce the Issue

1. 
2. 
3.

**Comment by Glitchraptor** [comment]
j'aime la nage aussi

![](https://images.unsplash.com/photo-1530549387789-4c1017266635?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&w=1000&q=80)
