### ISSUE TITLE
thread moving so fast no one will notice this

### ISSUE THREAD

**Issue by Glitchraptor** [notepad-plus-plus/notepad-plus-plus#6569]
post cats with bowties lmao
dogs with bowties fine too

![](https://i.redd.it/oc17ch8tukpy.jpg)

**Comment by NotAWorkAccount** [comment]
![catbowtie](https://user-images.githubusercontent.com/57175593/67847901-a7183080-fad1-11e9-92c7-8faa11aefd54.jpg)

**Comment by zj299792458** [comment]
gotcha!

**Comment by michalgritzbach** [comment]
![malá kočka s motýlkem](https://user-images.githubusercontent.com/352464/67850850-81a71900-fb09-11e9-93f9-c4b79bdcd9ca.jpg)

**Comment by dangbee** [comment]
They look so cute.

**Comment by AlexGalays** [comment]
![image](https://user-images.githubusercontent.com/1375586/67851911-bc11b580-fb0b-11e9-9eaf-17e540a47e3c.png)

**Comment by doublah** [comment]
good thread

**Comment by AngryGamer** [comment]
![bowtie](https://user-images.githubusercontent.com/4331362/67857554-56560700-fad4-11e9-8f06-7f20cdefb568.jpg)

**Comment by AngryGamer** [comment]
![bowtie](https://user-images.githubusercontent.com/4331362/67857751-cc5a6e00-fad4-11e9-8dc5-9140affb4b1f.jpg)

**Comment by illusion98** [comment]
Let me join in the fun.
![ ](https://cdn.discordapp.com/attachments/228914494569578496/638980116571095051/D2zCjynWoAATEoA.png)

**Comment by illusion98** [comment]
Let me join in the fun.
![ ](https://www.my3littlekittens.com/wp-content/uploads/2016/11/Pigs.jpg)

**Comment by Willt125** [comment]
I noticed. Now leave.

**Comment by fr3fou** [comment]
![image](https://user-images.githubusercontent.com/1344906/67861470-f473bc80-fb28-11e9-8c43-f1dce6e5f622.png)
![image](https://user-images.githubusercontent.com/1344906/67861477-f9387080-fb28-11e9-9f10-a0781b5e613c.png)

**Comment by dps910** [comment]
![image](https://user-images.githubusercontent.com/42849369/67861625-7c9d9600-fb18-11e9-85ad-e32cee152b51.png)

**Comment by dps910** [comment]
:3

**Comment by dps910** [comment]
> _insert kitty_

:3

**Comment by illusion98** [comment]
:3

**Comment by Sewer56** [comment]
:3

**Comment by fr3fou** [comment]
:3

**Comment by CitrusGender** [comment]
:3

**Comment by 81Denton** [comment]
:3

**Comment by Mikotochan** [comment]
:3

**Comment by donho** [comment]
I can't remove this spam, I just can't!!!

**Comment by Div-VT** [comment]
**Let me teach you how to program (press with hand**

![codingCat](https://user-images.githubusercontent.com/29190181/68200562-1d012800-fffb-11e9-9aac-4b99e9a7260e.jpg)

**Comment by donho** [comment]
My pussy.
I ensure you that she was wearing a bowty, we cannot see it because she was licking stuff.

![13640913_903734849737024_8889688567239181055_o](https://user-images.githubusercontent.com/90293/68337634-35e40900-00e1-11ea-8747-3d52e123b833.jpg)
