### ISSUE TITLE
etc.

### ISSUE THREAD

**Issue by rjbcollege** [notepad-plus-plus/notepad-plus-plus#657]
When typing etc the correct form to use is etc..  That is to say always with a full stop as it is an abbreviation.  However, notepad++ always detects this as a misspelling and even offers etc. as a correction to etc which having chosen this, notepad++ then detects as incorrectly spelled.
In other words it the dictionary check is never using the full stop as part of the spelling check, even though it knows this inclusion as a correct spelling.

**Comment by Rikk** [comment]
This is not related to Npp, but a problem with your spell check plugin (DSpellCheck?) or maybe with the dictionary you use for your language.
Better you report it to them?

**Comment by rjbcollege** [comment]
OK will do, thanks for that Rikk.

**Comment by Rikk** [comment]
You could try a post here:
https://notepad-plus-plus.org/community/category/5/plugin-development
