### ISSUE TITLE
Cannot access files on virtual drives

### ISSUE THREAD

**Issue by kotkaste** [notepad-plus-plus/notepad-plus-plus#658]
Notepad++ v6.8.1 does not support virtual drives (e.g. drives obtained using SUBST command). My OS is Windows7.

**Comment by jonandr** [comment]
You have probably created the SUBST drives as user X but are running N++ as user Y.

See e.g http://superuser.com/questions/614721/subst-drive-invisible-in-non-admin-processes

**Comment by kotkaste** [comment]
I create the virtual drive using  SUBST command in a .bat file that is stored under \Users\All Users\Microsoft\Windows\Start Menu\Programs\Startup. With this setup, Notepad++ does not see the virtual drive (even though many other applications can see it, e.g. Notepad, Eclipse etc.).
After moving the .bat file creating virtual drive under C:\Users\<user>\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup Notepad++ started seeing it also.
To me it still looks as a problem why Notepad++ could not see it if other applications were able to, however based on your information jonandr, I can now use Notepad++ for files from virtual drive.
Thank you!
