### ISSUE TITLE
大家進來看看 垃圾中國政府有多愛迫害新疆西藏

### ISSUE THREAD

**Issue by Nkeys** [notepad-plus-plus/notepad-plus-plus#6581]
中國的程序猿們 不要當中國之恥

自己國家有人被迫害還無視

愛國不是盲目的

程序猿們都能翻牆 自己google一下就能知道真相

美國紐約時報
https://tinyurl.com/y8pjfcnr

英國BBC當然也有，不然不會被點名
https://www.bbc.co.uk/news/resources/idt-sh/China_hidden_camps

英國衛報
https://tinyurl.com/ybvtdm7g
「若你進了集中營，就再也出不來了」

英國路透社
https://www.reuters.com/investigates/special-report/muslims-camps-china/

英文單字小教室：
gulag(n.)
a system of labour camps maintained in the Soviet Union from 1930 to 1955 in
which many people died.

倫敦金融時報/日本經濟新聞，嚴肅報紙
https://www.nikkei.com/article/DGXMZO34407450R20C18A8000000/
https://www.nikkei.com/article/DGXMZO36410950S8A011C1FF8000/
https://www.nikkei.com/article/DGXMZO36421640S8A011C1000000/
https://www.nikkei.com/article/DGXMZO38506360U8A201C1000000/
https://www.nikkei.com/article/DGXMZO39069750Y8A211C1000000/
https://www.nikkei.com/article/DGXMZO41497150Q9A220C1000000/

DLF，德國的公共媒體，Deutschlandradio=德國廣播電台旗下
https://tinyurl.com/y5b2g8zl

南德日報，位於慕尼黑，剛好是德國第一大報
https://tinyurl.com/y43yolza

法蘭克福匯報=FAZ，德國重要的嚴肅報
https://tinyurl.com/y6fb7kmw

瑞士新蘇黎世報=NZZ，瑞士最古老的報紙
https://tinyurl.com/y9d4s9dv

華爾街日報=WSJ，美國讀者水準最高的報紙，第一個報導內有新疆影片
https://tinyurl.com/y9l7lr2k
https://tinyurl.com/y7gj2g5q

RFI法國國家廣播電台，是法國外交部支持的電台
https://tinyurl.com/yc3bxeh2

産経新聞，日本保守主義報紙
https://www.sankei.com/economy/news/181106/prl1811060405-n1.html

毎日新聞，日本左翼報紙
https://mainichi.jp/articles/20181105/ddn/041/030/013000c

美國洛杉磯時報=LA Times
https://tinyurl.com/yxvyfaf9

新加坡海峽時報
https://tinyurl.com/yygjdqhl

芬蘭赫爾辛基日報
https://www.hs.fi/ulkomaat/art-2000005862913.html

丹麥日德蘭西海岸報
https://tinyurl.com/y5cd8xlm

丹麥貝林時報
https://tinyurl.com/y5mowclt

以上是造假的邪惡西方媒體

我也有準備環球時報

http://opinion.huanqiu.com/editorial/2018-08/12702719.html?agt=84
社评：捍卫新疆和平稳定，就是最大的人权

http://opinion.huanqiu.com/editorial/2018-10/13288619.html?agt=84
社评：新疆治理的目标和实践都是正义的

**Comment by mh1995** [comment]
国外垃圾媒体 还真有人信？

**Comment by Rojackse** [comment]
真相?NM的日本侵华的有吗?

**Comment by Rojackse** [comment]
日本侵华的呢,来个谷歌的真相啊

**Comment by Rojackse** [comment]
NM的要不是中国,您可真就是亡国奴了,沙雕

**Comment by Nkeys** [comment]
@mh1995 
別丟資訊人的臉
我相信你可以用google

中國政府的人權紀錄非常糟糕全世界都知道
自己google吧

**Comment by c-jf** [comment]
你觉得垃圾的台湾绿党还能蹦跶多久？笑死爹了

**Comment by NainbowCat** [comment]
> 日本侵华的呢,来个谷歌的真相啊

自己不会谷歌还要别人教你?
自己去搜搜 只会喷

**Comment by wimhu** [comment]
别BB了，美国的信誉早已被特朗普消耗败光了，还好意思说，现在的美国跟流氓有什么区别？作为程序员，写好你们的程序是第一的，不要扯政治。

**Comment by monoglo** [comment]
死者不会开口说话，因为他们已经死了。而活人，想怎么说就怎么说

**Comment by wimhu** [comment]
> 中國的程序猿們 不要當中國之恥
> 
> 自己國家有人被迫害還無視
> 
> 愛國不是盲目的
> 
> 程序猿們都能翻牆 自己google一下就能知道真相
> 
> 美國紐約時報
> https://tinyurl.com/y8pjfcnr
> 
> 英國BBC當然也有，不然不會被點名
> https://www.bbc.co.uk/news/resources/idt-sh/China_hidden_camps
> 
> 英國衛報
> https://tinyurl.com/ybvtdm7g
> 「若你進了集中營，就再也出不來了」
> 
> 英國路透社
> https://www.reuters.com/investigates/special-report/muslims-camps-china/
> 
> 英文單字小教室：
> gulag(n.)
> a system of labour camps maintained in the Soviet Union from 1930 to 1955 in
> which many people died.
> 
> 倫敦金融時報/日本經濟新聞，嚴肅報紙
> https://www.nikkei.com/article/DGXMZO34407450R20C18A8000000/
> https://www.nikkei.com/article/DGXMZO36410950S8A011C1FF8000/
> https://www.nikkei.com/article/DGXMZO36421640S8A011C1000000/
> https://www.nikkei.com/article/DGXMZO38506360U8A201C1000000/
> https://www.nikkei.com/article/DGXMZO39069750Y8A211C1000000/
> https://www.nikkei.com/article/DGXMZO41497150Q9A220C1000000/
> 
> DLF，德國的公共媒體，Deutschlandradio=德國廣播電台旗下
> https://tinyurl.com/y5b2g8zl
> 
> 南德日報，位於慕尼黑，剛好是德國第一大報
> https://tinyurl.com/y43yolza
> 
> 法蘭克福匯報=FAZ，德國重要的嚴肅報
> https://tinyurl.com/y6fb7kmw
> 
> 瑞士新蘇黎世報=NZZ，瑞士最古老的報紙
> https://tinyurl.com/y9d4s9dv
> 
> 華爾街日報=WSJ，美國讀者水準最高的報紙，第一個報導內有新疆影片
> https://tinyurl.com/y9l7lr2k
> https://tinyurl.com/y7gj2g5q
> 
> RFI法國國家廣播電台，是法國外交部支持的電台
> https://tinyurl.com/yc3bxeh2
> 
> 産経新聞，日本保守主義報紙
> https://www.sankei.com/economy/news/181106/prl1811060405-n1.html
> 
> 毎日新聞，日本左翼報紙
> https://mainichi.jp/articles/20181105/ddn/041/030/013000c
> 
> 美國洛杉磯時報=LA Times
> https://tinyurl.com/yxvyfaf9
> 
> 新加坡海峽時報
> https://tinyurl.com/yygjdqhl
> 
> 芬蘭赫爾辛基日報
> https://www.hs.fi/ulkomaat/art-2000005862913.html
> 
> 丹麥日德蘭西海岸報
> https://tinyurl.com/y5cd8xlm
> 
> 丹麥貝林時報
> https://tinyurl.com/y5mowclt
> 
> 以上是造假的邪惡西方媒體
> 
> 我也有準備環球時報
> 
> http://opinion.huanqiu.com/editorial/2018-08/12702719.html?agt=84
> 社评：捍卫新疆和平稳定，就是最大的人权
> 
> http://opinion.huanqiu.com/editorial/2018-10/13288619.html?agt=84
> 社评：新疆治理的目标和实践都是正义的

你是美国派来的吗，新疆和西藏 比以前好不知道多少倍，你去过吗？就在这里瞎比比，境外势力一直支持喇嘛搞乱新疆和西藏，世人皆知，还发这些垃圾报有什么意思，你看利比亚，叙利亚，有几个有好下场的，就连土耳其也差点被颠覆，那些所谓的报道，但凡是一个正常的理智的人都不会认同的。
一个贫穷落后的国家，在快速发展的过程中，肯定会存在这样或那样的问题，但是问题并不可怕，要敢于面对和改革，纵观中国多年以来的改革成效，足以说明问题，对世界的经济贡献，哪一国能匹敌？使得无数的人脱贫致富，国外又有几个报道的，如果你只盯着别人的缺点，那么你看到的永远只有不好的也一面，美国这几年对其他国家的污蔑和诽谤还少吗？

**Comment by qq1554135900** [comment]
呆湾解放的时候你可千万别挥舞五星红旗第一个冲在前面啊

**Comment by sylvanas0907** [comment]
香港的三姓家奴，先搞清楚自己姓什么
