### ISSUE TITLE
MINOR: syntax highlighting php - stripos is not recognised as a function

### ISSUE THREAD

**Issue by m-overlund** [notepad-plus-plus/notepad-plus-plus#659]
the php function stripos is not recognised as a php function in syntax highlightning.

![stripos](https://cloud.githubusercontent.com/assets/504236/9109350/449540a6-3c35-11e5-8fd2-add07e7b3712.png)

**Comment by milipili** [comment]
cf #459

**Comment by milipili** [comment]
The fix is available in the latest version :)

**Comment by Rikk** [comment]
@milipili Could you please ask Donho to add a note somewhere saying that people need to update `langs.xml` manually?
