### ISSUE TITLE
Add syntax highlighting for ECMAScript 2016 (and fix ES5 syntax highlighting too)

### ISSUE THREAD

**Issue by KOLANICH** [notepad-plus-plus/notepad-plus-plus#661]
For example, some keywords (let, yield, await, set get, ) are not highlighted.
Neither are template strings (also it'd be good to highlight templates in them).

**Comment by monk-time** [comment]
Keywords: `let` and `of` were added in #165 (although I had to remove my langs.xml for it to update, thereby losing my customized tab settings), and according to [the MDN doc](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Lexical_grammar#Keywords) only `yeild` (ES5),`await` (ES6) and `async` (ES7) remain. [`set`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/set) and [`get`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/get) (ES5) aren't reserved words in a strict sense as you can use them as an identifier, but imo they should also be highlighted.

Template strings (also #597): I have tried to raise this issue [on Scintilla tracker](https://sourceforge.net/p/scintilla/feature-requests/1112/), it may be not as easy as new keywords, but I agree it's a must-have functionality for modern JS.

**Comment by monk-time** [comment]
The fix in v6.8.7 only adds basic highlighting for backquoted strings (full string itself), but not for templates inside them.

**Comment by donho** [comment]
Unfortunately, that's all I can do with the current JavaScript lexer.

**Comment by vitaliylag** [comment]
@donho, Why text in `` has #fff background color and #000 text color? It is string and should have the same colors like in other strings ('' and ""). There is even no ability to configure it.

**Comment by sourcesupportteam** [comment]
I would say that lack of template support in backtick-quoted strings is rather a BUG than enhancement request.  Could you bump up the priority of this issue?

**Comment by 1ctinus** [comment]
> The fix in v6.8.7 only adds basic highlighting for backquoted strings (full string itself), but not for templates inside them.

This has not been fixed over six years later

**Comment by marcusparsons** [comment]
In v8.5.4, this has yet to be fixed.
