### ISSUE TITLE
Make Notepad++ more compatible with Wine

### ISSUE THREAD

**Issue by KOLANICH** [notepad-plus-plus/notepad-plus-plus#662]
Here is the [list of issues](https://appdb.winehq.org/objectManager.php?sClass=version&iId=25722&sAllBugs). The most annoing (for me) are the ones related to search and search window focus (and sometimes I get similar even in Windows).

**Comment by Croydon** [comment]
This might be redundant in the long run because of #332.

@milipili:
> From now on, cross-platform is required in any new code.

**Comment by KOLANICH** [comment]
In any case, it can take far less time to fix wine-related issues then to make NPP truly cross-platform.

**Comment by milipili** [comment]
@Croydon You're right. However it can be sometimes useful to test on another platform.
12799 seems not interresting ("auto-completion window appears with a title bar which is not the case under windows", more likely a wine issue) but the 37814 may reveal real problems.
@KOLANICH (or anyone) If you have time to test it, a debug version can be provided (for backtraces) (but please use the latest version from master).

**Comment by KOLANICH** [comment]
>if you have timeto test it

Sorry, i'm now on Windows, but I'm going to move to linux in the future (because of malware in windows 10), but that future is not very close.

**Comment by ariccio** [comment]
> because of malware in windows 10

What? Did you mean "in Windows XP"?

**Comment by ariccio** [comment]
@Croydon as a side note, I still find it hilarious that someone thought that "debugging speed is the reciprocal of the number of teams involved which is derived from the number of platforms involved". Yup, more complexity multiplied by people grouped differently equals easier debugging. That makes *complete and total * sense.

**Comment by Croydon** [comment]
@ariccio Yeah :laughing:

**Comment by donho** [comment]
I use v7.6.6 by using WINE under UBUNTU, everything goes smoothly.
