### ISSUE TITLE
File Status Auto-Detect

### ISSUE THREAD

**Issue by WizADSL** [notepad-plus-plus/notepad-plus-plus#664]
I would like an additional option added to the "File Status Auto-Detect" feature.  Currently (if the feature is enabled) it seems that the status of a file is checked at some interval and when Notepad++ receives focus.  I frequently work on files that are open over a slow VPN and it can take some time for the check to be preformed before the program becomes responsive.  I would like a setting that would allow the status of a file to be checked when the tab for that file becomes active.  If the assumptions I have made about how this feature works are incorrect please let me know.

**Comment by blind-acrobat** [comment]
I have exactly the same problem. The program takes ages to become responsive trying to update all the network files I have opened in tabs. It would be amazing to implement that fix that WizADSL suggests!! Many thanks guys. NPP is awesome

**Comment by SinghRajenM** [comment]
This has been fixed in ba60fbdd715d647aa5ce7be5b6b75182b4a52951.
@donho , I feel this ticket can be closed.

**Comment by MetaChuh** [comment]
many thanks @SinghRajenM 👍

closed with https://github.com/notepad-plus-plus/notepad-plus-plus/commit/ba60fbdd715d647aa5ce7be5b6b75182b4a52951
