### ISSUE TITLE
(By Cioss, Keep this on top of the page) : If you see this, you are immunited from the word that looks like "nigeria"

### ISSUE THREAD

**Issue by ItsCioss** [notepad-plus-plus/notepad-plus-plus#6656]
Here's a cheeseburger in case you're hungry 
![burglar](https://user-images.githubusercontent.com/56771507/67848764-9386bd00-fb05-11e9-9554-d06cfc7a8507.png)

**Comment by mis101247** [comment]
How about soup dumplings :))!!

![](http://i.epochtimes.com/assets/uploads/2019/05/goldenchopsticks-digital-wide-768x365-600x285.jpg)
