### ISSUE TITLE
Remove unused font file; update copyleft year

### ISSUE THREAD

**Issue by Rikk** [notepad-plus-plus/notepad-plus-plus#666]
This is just a pointer to https://github.com/notepad-plus-plus/notepad-plus-plus/pull/638, for bureaucratic purposes.

**Comment by Rikk** [comment]
#666 - This is Donho's favorite issue.

**Comment by ariccio** [comment]
> for bureaucratic purposes.

That is hilariously accurate.

**Comment by milipili** [comment]
Nop ! Just to create a ticket with the mark of the daemon 666 !

**Comment by Rikk** [comment]
[As wished](https://github.com/notepad-plus-plus/notepad-plus-plus/pull/638#issuecomment-128182620).
:japanese_ogre: :japanese_goblin: :smiling_imp: :feelsgood:
