### ISSUE TITLE
Assertion in ScintillaWin::DirectFunction failed!

### ISSUE THREAD

**Issue by ariccio** [notepad-plus-plus/notepad-plus-plus#669]
The [assertion at line 3240 failed](https://github.com/notepad-plus-plus/notepad-plus-plus/blob/master/scintilla/win32/ScintillaWin.cxx#L3240) for me:
![failedscintillaassert](https://cloud.githubusercontent.com/assets/2142308/9129088/d19ab77c-3ca0-11e5-92b4-cd1ac59f8e30.PNG)

It happened after Notepad++ was open for a minute or two (modified, unsaved, file), hence I'll guess it's something to do with backup.

**Comment by milipili** [comment]
Sorry but I can not reproduce the issue. Any backtrace ?

**Comment by ariccio** [comment]
Sadly, not yet. This *did*, however, fire... so it's not theoretical.

**Comment by donho** [comment]
This is rather a Scintilla issue than Notepad++ one, isn't it?

**Comment by milipili** [comment]
I close this ticket. If you have any backtrace to analyze, please re-open it.
