### ISSUE TITLE
Settings not save for User ext. :

### ISSUE THREAD

**Issue by rhyous** [notepad-plus-plus/notepad-plus-plus#67]
# Use Case

Web.config files are Xml.
Visual Studio Snippet files are Xml.
# Steps to duplicate
- Install Notepad++.
- Go to Settings | Style Configurator.
- Change theme to Deep Black.
- Under Language select XML.
- Add the following to user ext. :
  snippet config
- Save and exit Style Configurator.
- Close Notepad++ and reopen.
# Result

Settings are not saved and do not take effect.
# Expected Result

Settings to be saved and immediately take effect.
# Cause

User doesn't have write permissions to any files in C:\Program Files (x86)\Notepad++\themes
# Workarounds

**Workaround 1**
- Add write permission to C:\Program Files (x86)\Notepad++\themes folder (rights are inherited by files).
- Make change
- Close already open files as changes don't take immediate effect
- Re-open files

**Workaround 2**
- Run Notepad++ as administrator and make change.
- Close already open files as changes don't take immediate effect
- Re-open files
# Possible fixes
- Add write permissions during install (using NSIS's AccessConrol plugin)
- Save the style to %appdata%\Notepad++\themes and let styles in that folder override files in C:\Program Files (x86)\Notepad++\themes

**Comment by techolik** [comment]
Just met this, had to manually edit the style file under C:\Program Files (x86)\Notepad++\themes for it to work.

**Comment by loginetsolutions** [comment]
Workaround 2 fixed my same problem. Thanks.

**Comment by MetaChuh** [comment]
closed due to:
* outdated fixed issue.
* works on 7.6.6, theme customisations are stored at `%AppData%\Notepad++\themes`

**Comment by gt7zdd5cm5-ops** [comment]
> Web.config metadata
