### ISSUE TITLE
Compare plugin forgets word wrap

### ISSUE THREAD

**Issue by vgezer** [notepad-plus-plus/notepad-plus-plus#670]
Hi,

With Notepad++ 6.7.9.2 and Compare Plugin 1.5.6, after clearing results, if wordwrap was enabled before, it is forgotten.

**Comment by Yaron10** [comment]
@vgezer,

I can not reproduce it in NP++ v6.8.
Try Compare [v1.5.6.7](http://www47.zippyshare.com/v/OjNihpth/file.html). I've slightly modified UFO's code some time ago.

Regards.

**Comment by donho** [comment]
It's rather Compare Plugin's issue than Notepad++'s one.
Please report the bug to Compare Plugin's author.
