### ISSUE TITLE
Mouse wheel just don't work in the preferences dialog

### ISSUE THREAD

**Issue by milipili** [notepad-plus-plus/notepad-plus-plus#672]
In all listboxs in the preferences dialog, it is impossible to use the mouse wheel, we have to use the scrollbar.
![mouse-wheel](https://cloud.githubusercontent.com/assets/5516919/9137959/702c2b34-3d21-11e5-96af-fcb7df775a7c.png)

**Comment by milipili** [comment]
Not all controls actually, but nearly all of them

**Comment by donho** [comment]
I believe this issue has been fixed since long time ago.
Update your Notepad++ to the latest version (v7.6.6).
If the issue persists, please create a new issue for it.
Thank you.
