### ISSUE TITLE
Revert to a system monospace font instead of "Source Code Pro"

### ISSUE THREAD

**Issue by milipili** [notepad-plus-plus/notepad-plus-plus#676]
I like `Source Code Pro` but this font is not really complete and leads to numerous issues (#671, #675, and probably others...).
Thus a system font should be used instead for the default font.

(note: snif, I really like source-code-pro...)

**Comment by Rikk** [comment]
Imo, Lucida Console is the best font.

**Comment by aaaxx** [comment]
It lacks bold and italic though, so you get ugly computer generated ones (there was already an issue here about Source Code bold and italic not being included with N++).

For my money, Consolas is one of the best monospaced fonts out there, and not just on Windows.

But, in the end, anything is better than Courier.

**Comment by Rikk** [comment]
Except that Consolas will cause displeasure for those with Cleartype disabled.
https://en.wikipedia.org/wiki/Consolas

Lucida Console looks good for every anti-alias configuration here, and is not too small in default Npp size.

I think a good open-source alternative is [DejaVu](http://dejavu-fonts.org/wiki/Main_Page) which, perhaps, is already used in some themes. It is also in active development, but looks more mature than Adobe's Source Code Pro.

**Comment by aaaxx** [comment]
Oops, didn't know that; I have ClearType turned on.

**Comment by slitazcn** [comment]
Liberatio Mono is pretty good

**Comment by milipili** [comment]
This must be a typeface included with Windows

**Comment by Croydon** [comment]
Isn't that exactly the opposite of everything from now on must be cross platform? :)

**Comment by Rikk** [comment]
> This must be a typeface included with Windows

[Lucida Console](https://www.microsoft.com/typography/fonts/font.aspx?FMID=1262)

**Comment by milipili** [comment]
This kind of settings can not have the same default value on all platforms.
It is a matter of taste but I am not really fond of Lucida Console :)

**Comment by Rikk** [comment]
Why not include another, the way Donho did with Adobe's one?

**Comment by h-h-h-h** [comment]
Reference: issue https://github.com/notepad-plus-plus/notepad-plus-plus/issues/729

**Comment by donho** [comment]
It is done in the v6.8.2 release.
