### ISSUE TITLE
Dragging search progress window during a Find in Files causes NP++ to freeze

### ISSUE THREAD

**Issue by cartpauj** [notepad-plus-plus/notepad-plus-plus#682]
When doing a find in files, if you drag the search's progress window which pops up during the searches with your mouse and the search finishes at the same time, NP++ freezes and must be force closed. Further NP++ will not re-open until the PC has been restarted.

Have verified this multiple times, and am running Win7 Pro x64 on a Dell Optiplex 755.

**Comment by pnedev** [comment]
That is fixed by #1187 (already merged in v6.8.7).
The issue can be closed.

**Comment by CookiePLMonster** [comment]
Still open, still fixed 😆 Anyone to close it?
