### ISSUE TITLE
Invalidity of regular expression ignored?

### ISSUE THREAD

**Issue by h-h-h-h** [notepad-plus-plus/notepad-plus-plus#684]
Hello,

search for the regular expression `\d{` and the dialog states: "Can't find the text ..." Search for `\d[` and it states: "Invalid regular expression".

I can't imagine that a half construct with only `{` is allowed. So, can others confirm this is a bug?

**Comment by R2-Dequeue** [comment]
I can confirm I have the same behavior.

I'm actually surprised `\d[` doesn't work, in my experience regular expression implementations tend to (ironically) be context sensitive; if there's no closing pair, they treat the opening token as just another character.

**Comment by GitMensch** [comment]
Vote for closing this issue as something like wont-fix.

**Comment by sasumner** [comment]
There is nothing to "fix" here.  Boost regex will treat `\d{` as a search for a digit plus a literal `{`.  On the contrary Boost regex will treat `\d[` as an error.  There is nothing to be done for this in Notepad++ as it turns over regex searching to Boost.
