### ISSUE TITLE
Non-blocking find/replace actions

### ISSUE THREAD

**Issue by h-h-h-h** [notepad-plus-plus/notepad-plus-plus#685]
Hello,

the work Notepad++ does triggered by the find-and-replace dialog should be done in a worker thread and should be cancelable.

This is because such actions can sometimes last very long and can even cause you to think the GUI will never respond again and to force-terminate the program. This is especially true for large files.

If there's a way to get this information, there should even be a progress bar. Alternatively, the information of the last processing time would be valuable, if it's a long one.

An optional sound after long operations would also be appreciated.

---

Related issue: https://github.com/notepad-plus-plus/notepad-plus-plus/issues/365

---

Because the find-and-replace dialog already has many buttons, probably there shouldn't be added an additional <q>Cancel</q> button. Because it makes sense to cancel a running action before closing the dialog, the <q>Close</q> button could turn into a <q>Cancel</q> button while an action is running.

The following image is an illustration of how the progress could be indicated. It shows the bottom of the find-and-replace dialog.

![gui](https://cloud.githubusercontent.com/assets/13482553/9569523/7f443238-4f6e-11e5-9543-c2d313780c8f.png)

The remaining time should appear as soon as enough data was gathered for a non-jumping presentation (short fixed amount of time?) and only if it's greater than or equal to 2 seconds at this point.

---

The developer of the PCRE2 library told me via e-mail that he is implementing an end offset feature for the functions `pcre2_match()` and `pcre2_substitute()` that would allow progress features (see issue https://github.com/notepad-plus-plus/notepad-plus-plus/issues/816). Because it would be a huge performance hit to do additional progress-related processing on every character position of the subject string, one should let the library process the string repeatedly from a start offset to an end offset and do progress-related processing between those calls. (Example: Try to match starting from offsets 0 to 100, update progress controls, try to match starting from offsets 101 to 200, and so on.)

Because the processing time of different regular expressions can differ very much, the application should first process a short range of the subject string and see whether the PCRE2 function returns quickly. If it returned quickly, the length of the ranges processed at once can be increased. This way, the length can be leveled out at a frequency of, say, 20 Hz (50 ms between GUI updates).

<sup>_Old text about conversation with the developer:_
When having [switched to the PCRE2 library](https://github.com/notepad-plus-plus/notepad-plus-plus/issues/816), the functions `pcre2_match()` and `pcre2_substitute()` are able to provide progress information by means of callouts. At the time of this writing (2015-09-17), it is already possible with the `pcre2_match()` function, and the PCRE2 developer told me via e-mail that he <q>is considering a new callout that would perhaps make global substitution progress easier to implement when `pcre2_substitute()` is used.</q></sup>

<sup>Of course, a worker thread is still necessary, because single matches between the callouts can still last very long. (For your information: The PCRE2 developer also mentioned <q>the <q>match limit</q> feature to limit the amount of work done.</q> But I think a worker thread is the only opinion for Notepad++.)</sup>

**Comment by milipili** [comment]
It is already planned.

**Comment by h-h-h-h** [comment]
Great!

**Comment by ariccio** [comment]
> Great!

...close this issue? Or say that you will when it's implemented?

**Comment by h-h-h-h** [comment]
There's information in this issue that is still relevant. Surely not every detail was planned as I described it. It wasn't said *where* it is planned. Not in an issue? Then we would see a reference here. I expect something like that.
