### ISSUE TITLE
Not-so-pretty toolbar icons

### ISSUE THREAD

**Issue by h-h-h-h** [notepad-plus-plus/notepad-plus-plus#686]
Hello,

see this option:
![Image](https://cloud.githubusercontent.com/assets/5516919/9138053/faeaeabc-3d21-11e5-8d81-33e6cda8c97d.png)
Only the option "Standard icons" has pretty icons. Unfortunately, they don't exist as big ones. I strongly prefer small icons over these ones:
![Image](https://cloud.githubusercontent.com/assets/2916485/9147211/771f9c5a-3d3a-11e5-8597-02b7dd5ee5e3.gif)
Could we get rid of the not-so-pretty icons and be able to choose resized pretty ones (even pixelated) until someone has found pretty vector images or pretty icons at different sizes?

See also issue https://github.com/notepad-plus-plus/notepad-plus-plus/issues/629.

**Comment by milipili** [comment]
:+1:

**Comment by donho** [comment]
I wanted remove them until I realize there are people with bad sight to use Notepad++.
The big icons help them for using Notepad++.
So let's keep them - they don't really bother you, do they?
