### ISSUE TITLE
港独狗台狗，出门被车碾狗头。母为妓来姐为娼，狗爹龟公天天当。阿母阿姊万人骑，不要钱来白送逼。独狗含住干爹吊，赔笑毒精溢嘴角。

### ISSUE THREAD

**Issue by xiangjihan** [notepad-plus-plus/notepad-plus-plus#6945]
1、肛毒狗起源于英国殖民港督滚回英国前养的一群走狗。
2、肛毒狗天天叫嚣着人权、自由，但是英殖港督时期，所有香港同胞活的不如狗，还要被走狗压迫，各种镇压实践敢不敢读一下历史。
3、肛毒狗天天叫嚣的人权、自由，乃至选举权，直到人民政府接受香港之后才获得的。
4、肛毒狗的野爹英国，对于苏格兰、北爱尔兰的独立运动一直持打压态势，死的人，海了去了。
5、肛毒狗的干爹美国，对于德州，加州的独立运动，以及其他各州的独立势力一直持打压态势。
6、肛毒狗的主子，港督杨慕琦，在1941年12月只坚持了18天就投降了，是地下党组织和大陆人民群众一直支持香港的反抗运动。
7、胎毒狗就不用说，日本人干杀你们爷爷，干你们奶奶的时候，你们这群孤儿还没出生呢。
8、胎毒狗的存在就是想证明，低能人到底有多下贱，大陆对你越好越跳腾，日本人杀的越厉害越跪舔。
9、大陆崛起在即，历史总归要回到中原王朝的主线上来，毒狗末日就要来临，中华民族复兴浩浩荡荡，正正堂堂，顺之者昌逆之者亡。这次是我们和平崛起，肯定不会变成刀兵相见，不过杀几只不识时务的蠢狗不算在内。
最后，愿世界和平、愿世界人民生活幸福美满，愿所有肛毒狗、胎毒狗过年期间被车碾压死：农历新年是中国人辞旧迎新，祭祀祖先，告慰上苍的佳节，在这种时刻，中华民族的文明师祖都会祝福天下华人，诅咒民族叛徒、二五仔。所以春节时期，死几个独狗，是天下太平、国家昌盛的象征，福泽天下、恩批八荒的大好事。

叮叮当叮叮当，死个毒狗听个响，今年几声铃铛脆，几个毒狗火葬场。
叮叮当叮叮当，骨灰和尿筑洋厕，一生忠心为干爹，干爹杀狗没商量。

**Comment by zrzjohn** [comment]
有一说一嗷 一边骂作者 一边继续用作者费劲肝脏写的程序 他 不香吗 软件是好软件 功能是好功能 作者辱华也没碍着我们继续用他的肝脏结晶啊...我们又不为他创造收益
