### ISSUE TITLE
Manually selected language not persistant when moving file to a different window

### ISSUE THREAD

**Issue by Teslafly** [notepad-plus-plus/notepad-plus-plus#696]
If you manually select a language (say "properties") and then drag the tab to a different / new window, if np++ can't automatically detect the language it defaults to "normal text fle" instead of retaining the manually selected language.

I an using np++ v6.8.1 on windows 7

**Comment by Rikk** [comment]
Would you like it to remember also the current line and caret position?

**Comment by Teslafly** [comment]
That would probably be a good idea. Basically moving the view, any settings, location, etc should remain the same if possible.

**Comment by Rikk** [comment]
Yes, I did that in the referenced request above.
The mechanism Npp uses for doing that is too basic, it simply makes use of some command-line parameters to launch a new process and open the file.

**Comment by donho** [comment]
Fixed by #709
