### ISSUE TITLE
Include example plugins in repository

### ISSUE THREAD

**Issue by dail8859** [notepad-plus-plus/notepad-plus-plus#697]
Many open-source projects that allow plugins to be written for them, also include an example plugin(s) in the main code repository. That way the example code is better maintained and developers can easily find the example code to start developing their own plugin.

There is the C++ plugin demo and template hanging round that is _very_ outdated. I'm suggesting these be updated, pulled into this main repository, and maintained. This will probably require a bit of moving code around since the plugin demo shares code with the main N++ core (few header files, StaticDialog.cpp, etc), but these could be moved into some common directory.

This is not only limited to the MSVC compiler, or even C++. We can include a couple of major languages (I think C# is used a good bit for plugin development?) and include a couple of major build systems (MSVC, mingw, etc (or cmake whenenver N++ officially moves to that)). 

Plugins are what make N++ great, let's make it easier for developers to get started! :)

**Comment by MetaChuh** [comment]
@dail8859 
i leave this one up to you 😉

**Comment by dail8859** [comment]
Never went anywhere even though it was accepted. Nobody seems interested and I dont have time myself unfortunately. So I'm fine closing it.

**Comment by chcg** [comment]
@dail8859 
I was at least slightly interested and created some PRs:
https://github.com/npp-plugins/plugindemo/pull/1
https://github.com/npp-plugins/plugintemplate/pull/1
https://github.com/npp-plugins/plugintemplate/pull/2

, but they were never merged :-(

And for C# there is also a demo:
https://github.com/kbilsted/NotepadPlusPlusPluginPack.Net/tree/master/Demo%20Plugin
