### ISSUE TITLE
Multiline replace

### ISSUE THREAD

**Issue by sushant7190** [notepad-plus-plus/notepad-plus-plus#698]
Previously, I was able to replace one character with multi line content, but since last 2-3 months, I am not able to do same. Please look into it.

**Comment by Rikk** [comment]
Give example of what exactly you are trying to do, please?

**Comment by h-h-h-h** [comment]
You can look forward to and up-vote for issue https://github.com/notepad-plus-plus/notepad-plus-plus/issues/563 if that's allowed. :blush:

**Comment by sushant7190** [comment]
Example,
I have a list of fruits and I need to create XML document.
Mango
Kiwi
Apple
Banana
Strawberry 
And I want to assign some XML tags to each of them, like below
<fruits>
	<fruitname>Mango
<fruits>
	<fruitname>Kiwi
<fruits> 
	<fruitname>Apple
<fruits>
	<fruitname>Banana
<fruits>
	<fruitname>Strawberry

for that, I get the list of all items, then "ctrl + H" 
Find what : ^ (with regular expression mode ON)
Replace with :  <fruits>
				<fruitname>
					this multi line tags.

Previously, I was able to do that , now not.

**Comment by h-h-h-h** [comment]
I'm not able to follow.
- "for that, I get the list of all items"?
- And are you trying to replace the zero-width match of `^` with nothing?
- "this multi line tags"?

**Comment by sushant7190** [comment]
@h-h-h-h sorry for inconvenience. I have updated my comment.

**Comment by h-h-h-h** [comment]
Are you sure you have used the native find-and-replace dialog? You can't enter linebeaks there! Maybe you used a plug-in capable of typing in text with multiple lines.

**Comment by Rikk** [comment]
You can actually search text with line breaks (end-of-line characters), just select the text then press Ctrl+F or Ctrl+H (it will display then in same line eol will be invisible). For typing them manually consider using Extended mode, then type \r, \n etc.

But... I don't understand the regex you tried to use... was it just `^`? It just represents the start of the text, but shouldn't match anything alone.

**Comment by donho** [comment]
I believe this issue has been fixed since long time ago.
Update your Notepad++ to the latest version (v7.6.6).
If the issue persists, please create a new issue for it.
Thank you.
