### ISSUE TITLE
VC2012 build error on v6.8.1 source

### ISSUE THREAD

**Issue by ltqsoft** [notepad-plus-plus/notepad-plus-plus#699]
I use Visual C++ 2012 to compile notepad++.exe. At the 1st build I got the compatibility issuse, thus I folow the article in the URL

http://stackoverflow.com/questions/20886391/vs-2012-project-failed-to-build-because-of-missing-toolset

Then comes a bunch of errors, here are some of them:

1>------ Rebuild All started: Project: Notepad++, Configuration: Unicode Debug Win32 ------
1>  LongRunningOperation.cpp
1>  mutex.cpp
1>..\src\MISC\Common\mutex.cpp : error C2220: warning treated as error - no 'object' file generated
1>..\src\MISC\Common\mutex.cpp : warning C4819: The file contains a character that cannot be represented in the current code page (932). Save the file in Unicode format to prevent data loss
1>\notepad-plus-plus-master\powereditor\src\misc\common\mutex.h : warning C4819: The file contains a character that cannot be represented in the current code page (932). Save the file in Unicode format to prevent data loss (..\src\MISC\Common\mutex.cpp)
1>\notepad-plus-plus-master\powereditor\src\misc\common\mutex.h : error C2220: warning treated as error - no 'object' file generated (..\src\MISC\Common\LongRunningOperation.cpp)
1>\notepad-plus-plus-master\powereditor\src\misc\common\mutex.h : warning C4819: The file contains a character that cannot be represented in the current code page (932). Save the file in Unicode format to prevent data loss (..\src\MISC\Common\LongRunningOperation.cpp)
1>\notepad-plus-plus-master\powereditor\src\misc\common\mutex.h(94): error C2059: syntax error : ';' (..\src\MISC\Common\mutex.cpp)
1>\notepad-plus-plus-master\powereditor\src\misc\common\mutex.h(94): error C2238: unexpected token(s) preceding ';' (..\src\MISC\Common\mutex.cpp)
1>\notepad-plus-plus-master\powereditor\src\misc\common\mutex.h(142): error C2059: syntax error : ';' (..\src\MISC\Common\mutex.cpp)

Did I miss something? Does my VS configuration have problems?

**Comment by Rikk** [comment]
I guess you need at least VS 2013 (ie. 2013 or 2015).

**Comment by milipili** [comment]
VS2013 is the minimal required version.

__side note__: my two previous companies had unsolved issues (and which won't be solved) with VS2012 (especially with template and code generation) only fixed in VS2013. So if you can, I would recommend you to upgrade your VS.
