### ISSUE TITLE
Spell-Checker 1.3.3 default searchpath is wrong for windows 7

### ISSUE THREAD

**Issue by cdwijs** [notepad-plus-plus/notepad-plus-plus#701]
Hi All,

I have installed the plugin "Spell-Checker 1.3.3", and installed Aspell and a dictionary from here:
http://ftp.gnu.org/gnu/aspell/w32/Aspell-0-50-3-3-Setup.exe
http://ftp.gnu.org/gnu/aspell/w32/Aspell-nl-0.50-2-3.exe

Spell-Checker cannot find Aspell, as it looks in the wrong place:
..\Aspell\bin <this is incorrect
..\..\Aspell\bin <this is correct

My version of notepad++ is 6.8.1 on windows 7 64 bit pro
Kind regards,
Cedric

**Comment by donho** [comment]
It's rather a Spell-Checker's issue than Notepad++'s one.
Please contact the author for the fix.
