### ISSUE TITLE
Better document map

### ISSUE THREAD

**Issue by h-h-h-h** [notepad-plus-plus/notepad-plus-plus#702]
Hello,

the look and behavior of the document map (View > Document Map) is not as good as in other editors. Please compare it with the one visible by default in [Sublime Text](http://www.sublimetext.com/) (including behavior).
- The scrolling behavior is kind of uncontrollable when you reach the top or bottom
- I didn't find a font setting
- With wrapped lines there can be situations when it flickers while scrolling by dragging

**Comment by aaaxx** [comment]
Also this bug: https://github.com/notepad-plus-plus/notepad-plus-plus/issues/440

**Comment by cwacha** [comment]
the scrolling behavior of the document map is indeed very annoying in notepad++. I also vote for the sublime text behavior!
