### ISSUE TITLE
SQL colorization changed in error by code.

### ISSUE THREAD

**Issue by samspade4321** [notepad-plus-plus/notepad-plus-plus#704]
Viewing this snippet as Language=SQL makes the code following ['\'] into text-colorized (red).  If the code is written ['\--'], i.e. the line is commented out following the [\], then everything colorizes normally.  The [] are used as delimiters above.

![clipboard01](https://cloud.githubusercontent.com/assets/10429657/9208166/dd141b32-4026-11e5-947c-59acf843b0ac.jpg)
![clipboard02](https://cloud.githubusercontent.com/assets/10429657/9208203/fec69db8-4026-11e5-8029-0ba8cf2e1c3c.jpg)

		IF @char = space(1)  or @char =  '_' or @char = ','  or @char = '.' or @char = '\' or @char = '/' or @char = '(' or @char =')'
		begin
			set @textnew = left(@text, @counter)  + upper(substring(@text, 
				@counter+1, 1)) + right(@text, (@length - @counter) - 1)
			set @text	 = @textnew
		end

**Comment by dail8859** [comment]
What version are you using exactly? I can't reproduce this in v6.8. Try changing your setting in `Settings -> Preferences -> MISC` and change `Treat backslash a escape characters for SQL` and see if that helps.
