### ISSUE TITLE
Commenting out code

### ISSUE THREAD

**Issue by h-h-h-h** [notepad-plus-plus/notepad-plus-plus#706]
Hello,

how do I comment out code so that the comment initiation string is put at the very start of the lines?

_Update:_ Not possible? It's a widespread type of commenting out. See my next comment.

**Comment by dail8859** [comment]
`Ctrl+K`. Also see the menu commands under `Edit -> Line operations -> Comment/Uncomment`

**Comment by Croydon** [comment]
Please use https://notepad-plus-plus.org/community/ for all kind of how-to-do-it questions to keep the GitHub issues clean :)

**Comment by dail8859** [comment]
@Croydon Not currently possible. See [here](https://notepad-plus-plus.org/community/topic/4276/sso-login-services-github-fb-twitter-g-stopped-temporarily)

**Comment by h-h-h-h** [comment]
@dail8859: It's the same as Ctrl+Q. I already discovered that. I want the comment initiation string at *the very start* of the line. I also expect the option not to be "intelligent"; it should just add one layer of comment initiation strings, e.g. `//` or `#`, and remove one layer of it on every line that starts with one.

@Croydon: As I already guessed, the issue is becoming a feature request.

**Comment by dail8859** [comment]
Maybe be a bit more clear in the initial comment then :)

**Comment by Croydon** [comment]
@h-h-h-h @dail8859 Alright, wasn't aware for that :)

**Comment by milipili** [comment]
I have activated the manual login for the community. Please let me know on gitter if there are any problems.
