### ISSUE TITLE
Dim the lights for visible whitespace

### ISSUE THREAD

**Issue by teknopaul** [notepad-plus-plus/notepad-plus-plus#712]
Having visible whitespace on, with current colours is not really comfortable for everyday use.

The same colour as the vertical lines draw for block indentation would be good.  Or compare np++ to eclipse with alpha set at 40%

**Comment by Rikk** [comment]
Default theme or what?

**Comment by teknopaul** [comment]
you can only change the tab ans space chars, You can't change the [LF] markers these share the same font as the main text, so its not possible to change with the current code base.  this are kind of big and ugly glyphs too compared to other editors, but that would not matter if they were dimmed.

**Comment by aaaxx** [comment]
You can show just whitespace, without EOL markers. It's under “Show White Space and TAB” in Shortcut Mapper.

**Comment by teknopaul** [comment]
I've been running as suggested for a few days and I don't really miss line endings marks so I'll close this issue.  Thanks for the advince, aaaxx and Rikk
