### ISSUE TITLE
Function List: Highlight the current function based on cursor position

### ISSUE THREAD

**Issue by artemisnix** [notepad-plus-plus/notepad-plus-plus#715]
Feature Request: Having the Function List highlight the current function (cursor's current position) would be a great feature, especially for large functions.
Thx

**Comment by Rikk** [comment]
+1

**Comment by yidc** [comment]
+1

**Comment by kolaumes** [comment]
+1

**Comment by jcrmatos** [comment]
+1

**Comment by sabeti05** [comment]
+1

**Comment by milipili** [comment]
Please guys, there is an emoticon for that now, no need to pollute.

**Comment by KptainBiwouak** [comment]
Thanks!

**Comment by gitmiluser27** [comment]
+1  need this important feature urgant

**Comment by KlausiD** [comment]
I have change the attach File which offers this functionality.
the current function is highlighting until the cursor reach the next function in the source-File.
I mean that this is enough.
One problem is open:
The highlight Line in the functionlist is bad to see if the functionlist has no focus.
Unfortunately I do not know how to change that.
Please test it!

[divFiles.zip](https://github.com/notepad-plus-plus/notepad-plus-plus/files/1191312/divFiles.zip)

**Comment by GaryBloom** [comment]
I tested npp7.5.4 and KlausiD's enhancements were not implemented. Assuming that KlausiD modified the 7.4.2 sources, I went through the process of integrating those changes into the 7.5.4 source files and tested. The changes seem to work, at least for my Python and C++ test cases.  As a side note, all but one of the differences between KlausiD's Notepad_plus.cpp and the 7.4.2 version were in the 7.5.4 version.  I didn't look at any other versions besides 7.4.2 and 7.5.4.
What's the best way to proceed?  I've attached my little dev environment.
[div2Files.zip](https://github.com/notepad-plus-plus/notepad-plus-plus/files/1649589/div2Files.zip)

**Comment by KlausiD** [comment]
I attached my changes here in the hope that they will be adopted. I think that not everyone can simply deliver their changes.

**Comment by GaryBloom** [comment]
Is there anything else I can do to help? I would love to see this functionality rolled into the project. 
I'm not sure what the formal process is, but I did comment each new line or block with "NEW" to make review easier.
As for testing, I don't use all (or most) of NPP's features, but I did drop the new executable into the installation directory of each of my machines, so whenever I use NPP, I am testing these changes.

**Comment by MAPJe71** [comment]
The proper way is to create PR (Pull Request), see also the [contributing guideline](https://github.com/notepad-plus-plus/notepad-plus-plus/blob/master/CONTRIBUTING.md#contributing).

**Comment by GaryBloom** [comment]
Thanks, Menno.
K, did you ever create a PR for this? If not, then that's the next step.  If for some reason you want me to do it, I'm happy to do so.  Let's get your functionality into NPP!

**Comment by MAPJe71** [comment]
@GaryBloom no-one gets assigned issues other then the owner and maybe the collaborators.
Create a pull-request and wait for it to get excepted and merged.

**Comment by GaryBloom** [comment]
Okay, not the cleanest PR, but it's my first and hopefully will get the job done.

**Comment by GaryBloom** [comment]
@KlausiD - PR has build errors with x64.  x32 builds fine.  Can you have a look?

**Comment by GaryBloom** [comment]
@KlausiD - Never mind. Think I figured it out...

**Comment by GaryBloom** [comment]
@KlausiD - The changes built successfully in the GitHub system under x86 and x64. Nothing to do now but wait and see what happens. Thanks for the code and the chance to get involved!

**Comment by artemisnix** [comment]
Great to see some traction on this. Thank you to everyone for your efforts. Exciting.
