### ISSUE TITLE
Count only in selection

### ISSUE THREAD

**Issue by h-h-h-h** [notepad-plus-plus/notepad-plus-plus#722]
Hello,

in the find dialog you are able to count the occurences of the string entered. When replacing you have the checkbox "In selection". However, I'm missing the ability to _count_ the occurences of the string to find _only in the selection._ Because finding only in the selection is not implemented, the find buttons should be grayed out when the checkbox is selected.

It would be great if this could be accomplished. Thanks!

**Comment by carlodri** [comment]
This would be a very useful feature!

**Comment by FredGandt** [comment]
Yes please :)
If I were more familiar with the code, I'd happily do the work, but by the time I figure out where to start, someone else could easily have finished.
I am frequently frustrated by the lack of this functionality, and workaround it by replacing the string I want to count in the selection (to get the count of replacements) then ctrl+z - which is not hard, but isn't nice either.
I'm slightly amazed that this open request from more than 3 years ago hasn't got more attention.
/me pokes NP++ ;p

**Comment by sasumner** [comment]
@FredGandt said:

>I am frequently frustrated by the lack of this functionality...If I were more familiar with the code, I'd happily do the work...amazed that this open request from more than 3 years ago hasn't got...attention

Think about how this frustration level would go up if you "did the work" and then that work got the same amount of attention as this open issue.

**Comment by sasumner** [comment]
@FredGandt 
You totally missed my point.  You assume your work would be integrated.  My point was it could sit here ignored and unintegrated, potentially forever...just like this issue that you pointed out has been here 3 years.

**Comment by FredGandt** [comment]
> @FredGandt
> You totally missed my point. You assume your work would be integrated. My point was it could sit here ignored and unintegrated, potentially forever...just like this issue that you pointed out has been here 3 years.

 ¯\_(ツ)_/¯

**Comment by donho** [comment]
> You totally missed my point. You assume your work would be integrated. My point was it could sit here ignored and unintegrated, potentially forever...just like this issue that you pointed out has been here 3 years.

It depends... If there's a good PR with a consistent UI, I will consider it.
The thing is UI part is the most difficult part, and ppl could want everything "In the selection", I prefer to keep the current state as clean as possible.

**Comment by donho** [comment]
@sasumner 
By "ppl could want everything \"In the selection\"", I mean it's hard for making a consistent UI if we want "in selection" for every find command. 
After checking it, only "Count" can be applied and  it makes sense, and it's not hard to implement it. So why not?

Thank you for the (others) comments pertinent on GitHub, which helps me to take the decision.
