### ISSUE TITLE
Turn off URL highlighting for large files

### ISSUE THREAD

**Issue by h-h-h-h** [notepad-plus-plus/notepad-plus-plus#723]
Hello,

I think you are aware of the fact that URL highlighting can significantly slow down the handling of large files. Instead of having to alter this option repeatedly, it could be turned off automatically for large files. I guess one would want to make this an option of this form (defaulting to the checkbox state shown):

```
┌─ Clickable-Link Settings ─────────────────────────────────────────┐
│ ☑ Enable
│ ☐ No underline                                  ┌────────────┐
│ ☑ Turn off for file as large as or larger than: │       1024 │ kB
│                                                 └────────────┘
└───────────────────────────────────────────────────────────────────┘
```

**Comment by milipili** [comment]
I am not sure that disabling it would be better. However I am sure that it could be handled better.

**Comment by h-h-h-h** [comment]
As a reference, please take a look of the bottom of this page: http://docs.notepad-plus-plus.org/index.php/Large_Text_Files.

**Comment by VVelda** [comment]
+1 Notepad++ have not problem with opening large files, but syntax highlighting yes. In my opinion, user should be warned when opens large file, with second chance prevent shot Notepad++ down (open without syntax highlighting or not open at all).

**Comment by donho** [comment]
I believe this issue has been implemented since long time ago.
Update your Notepad++ to the latest version (v7.6.6).
If the issue persists, please create a new issue for it.
Thank you.
