### ISSUE TITLE
Going past end of line

### ISSUE THREAD

**Issue by h-h-h-h** [notepad-plus-plus/notepad-plus-plus#724]
Hello,

as part of the column mode functionality (see Edit menu), I wish to be able to go past the end of a line. <kbd>Alt</kbd>+<kbd>Left mouse click</kbd> already allows this by means of the mouse. You could assign the shortcuts <kbd>Alt</kbd>+<kbd>Left</kbd>/<kbd>Alt</kbd>+<kbd>Right</kbd>, e.g., to do the same with the keyboard.

As it is when using the mouse, spaces should be added accordingly when you begin to type.

**Comment by Rikk** [comment]
Isn't it already Alt+Shift+Left/Right?

**Comment by h-h-h-h** [comment]
With this shortcuts you go past the end of the line, but you're also selecting. Then you overwrite the selection of no data as if you were beginning to type at the end of the line.

Because selection works with just Shift+Left/Right after you used Alt+Left mouse click, these shortcut are rather pointless for this purpose. You can use them to block-select text.
