### ISSUE TITLE
Cannot open files that contain ASCII NUL(0x00) correctly

### ISSUE THREAD

**Issue by prclx323800** [notepad-plus-plus/notepad-plus-plus#725]
Hi there. Today I wrote a c++ program:
```cpp
#include <cstdio>
int main() {
	freopen("test.out", "w", stdout);
	putchar('a'); putchar(0); putchar('b');
	return 0;
}
```
And then I try to open "test.out" with different applications.
Here is what Windows **Notepad** shows:
![image](https://cloud.githubusercontent.com/assets/10348653/9288789/4dbf143c-438c-11e5-8150-846451d5d63f.png)
And then Windows **Wordpad**:
![image](https://cloud.githubusercontent.com/assets/10348653/9288791/6d29ca92-438c-11e5-831e-feea2583329c.png)
Next comes **Emacs** (for Windows):
![image](https://cloud.githubusercontent.com/assets/10348653/9288793/7f1b43ca-438c-11e5-8335-e9de40e055e8.png)
However, **Notepad++** 6.8.1 performs this:
![image](https://cloud.githubusercontent.com/assets/10348653/9288797/bdd14f56-438c-11e5-997d-145c286698fa.png)
I don't know what's wrong here. Hope it can be fixed.

**Comment by donho** [comment]
@prclx323800 Could you provide your file so I can reproduce the bug?

**Comment by h-h-h-h** [comment]
Here's a test file: [File_with_binary_zero.png](https://cloud.githubusercontent.com/assets/13482553/9321456/0fe4490c-4567-11e5-94fd-e7462afda8b4.png). It has only 3 bytes (`a\0b` as spoken of before).

**Comment by dail8859** [comment]
I'm curious if there just isn't enough bytes there for N++ to detect the encoding correctly, thus throwing away the last two bytes (using the HEX-Editor plugin only shows 1 byte after opening). Also, it looks like adding another byte (e.g. "a\0bc") will cause N++ to correctly open a file.

**Comment by Hero2006** [comment]
File notepad-plus-plus\PowerEditor\src\Utf8_16.cpp
Line 208. Problem on detecting encoding. N++ trying to work with UTF-16 little-endian without BOM on this file.
