### ISSUE TITLE
兄弟们，毒狗也就会刷刷屏，真辩论，讲道理的时候，你就会发现毒狗一点墨水都没有，是狗屁不通。奉劝所有的毒狗，好好读书，好好读历史。就这点水平还想搞事，怕最后都不知自己怎么死的。

### ISSUE THREAD

**Issue by xiangjihan** [notepad-plus-plus/notepad-plus-plus#7257]
毒狗轮子不得好死

**Comment by collinoswalt** [comment]
> The 1989 Tiananmen Square protests, commonly known in mainland China as the June Fourth Incident (Chinese: 六四事件, liùsì shìjiàn), were student-led demonstrations in Beijing (the capital of the People's Republic of China) for the establishment of basic human and press rights and against the Communist-led Chinese government in mid-1989. More broadly, it refers to the popular national movement inspired by the Beijing protests during that period, sometimes called the '89 Democracy Movement (Chinese: 八九民运, bājiǔ mínyùn). The protests were forcibly suppressed after Chinese Premier Li Pengdeclared martial law. In what became known as the Tiananmen Square Massacre, troops with assault rifles and tanks fired at the demonstrators trying to block the military's advance towards Tiananmen Square. The number of civilian deaths was internally estimated by the Chinese government to be near or above 10,000.

![](https://www.abc.net.au/news/image/7935078-3x2-700x467.jpg)

![](http://www.visiontimes.com/uploads/2016/06/20160601082332180.jpg)

![](https://www.liberationnews.org/wp-content/uploads/2014/06/698a2900-9371-11e6-a1dc-bdf38d484582.jpeg)

![](https://i.redd.it/ltfzkhk07ff21.png)

![](https://www.dailydot.com/wp-content/uploads/2019/08/tiananmen-square-1989-massacre-aftermath.jpg)

![](https://www.nationalgeographic.com/content/dam/news/photos/000/803/80352.jpg)
