### ISSUE TITLE
Explorer.dll prevents Notepad++ from shuting down

### ISSUE THREAD

**Issue by sanastasiou** [notepad-plus-plus/notepad-plus-plus#727]
Hi,

I've just experienced the following issue. I am developing some plugin, and I've noticed I couldn't copy my .dll to the plugins directory. 

I've recently moved to windows 10, so I thought the issue has to do with that. However after a bit searching, I noticed that the Notepad++ process would never exit. It just hangs forever.

At first I thought that my plugin had something to do with it, so I removed it. Problem persisted.. Then I removed all the plugins and problem was gone. I started adding them back one by one until the problem reappeared.

Notepad++ 6.8.1, Windows 10 Pro

Plugins I'm using

`CodeAlignmentNpp`, `mimeTools`, `NppConverter`, `NppExport`, `NppFTP`, `PluginManager`, `SpellChecker`

and 

`Explorer.dll`

Note, that the problem first appeared after I changed some shortcuts, regarding line comments. This seems to be completely irrelevant to explorer.dll but this is when the problem appeared.

**Comment by sanastasiou** [comment]
I can actually verify this error, by trying to "remove" the Explored.dll via the plugin manager. Plugin manager hangs indefinitely when the "Plugin Update" window is open with message "Waiting for Notepad++ to close".

**Comment by donho** [comment]
It's a plugin issue and it's out of scope of Notepad++. Please report it to the Explorer plugin author.

**Comment by sanastasiou** [comment]
At the timer of the report, this plugin was bundled with Npp. Therefore I thought it was helpful to post this here. I'll try to find the plugin author..

**Comment by Ben749** [comment]
Hello, had this problem occuring, recently, since my laptop crashed .. 
Any fresh or portable instance of Notepad++ shipping explorer.dll freezes process before lauching main window .. 
Anyways same installation launched on another computer or VM does work .. don't know if some System dll or some file went corrupted on my laptop .. :(

That's my top usefull plugin this far, particulary for the favorite list
