### ISSUE TITLE
只会大喊大叫，是弱者的表现

### ISSUE THREAD

**Issue by jober2014** [notepad-plus-plus/notepad-plus-plus#7272]
只会大喊大叫，是弱者的表现
只会大喊大叫，是弱者的表现
只会大喊大叫，是弱者的表现
只会大喊大叫，是弱者的表现
只会大喊大叫，是弱者的表现
只会大喊大叫，是弱者的表现
只会大喊大叫，是弱者的表现
只会大喊大叫，是弱者的表现
只会大喊大叫，是弱者的表现
只会大喊大叫，是弱者的表现

**Comment by neilogd** [comment]
Please stop harvesting organs from political prisoners eh?

**Comment by jober2014** [comment]
Who cut your organs? &nbsp; &nbsp; &nbsp; &nbsp;
In this world, there are good people and bad people in any party or political camp, everywhere at any time.

 



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Neil Forbes-Richardson"<notifications@github.com&gt;; 
发送时间: 2019年10月30日(星期三) 晚上7:02
收件人: "notepad-plus-plus/notepad-plus-plus"<notepad-plus-plus@noreply.github.com&gt;; 
抄送: "修仙者"<1746505121@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [notepad-plus-plus/notepad-plus-plus] 只会大喊大叫，是弱者的表现 (#7272)




Please stop harvesting organs from political prisoners eh?
