### ISSUE TITLE
Please read / 請閱讀

### ISSUE THREAD

**Issue by ItsCioss** [notepad-plus-plus/notepad-plus-plus#7278]
**(PLEASE PUT REACTION TO APPEAR ON TOP)** I _**don't fully know what happened**_. But seriously though, we know shit happened in china (I think it's about that). But now people are vandalizing the internet about it and it's really not good. We know you're struggling with this but you can talk about it calmly. It's no cause for fucking jews and "niggers".
And plus, we don't want to make the internet political, It's a thing used to share stuff we do and make friends. It's really not worth destroying our stuff even if it's not fair.
So please don't vandalize the internet, this really won't help you to justice. Hopefully everything turns out good. Have a good day.
/////////////////////////////////////////////////////////////////////////////////
**（請做出反應以顯示在頂部）** _**我不完全知道發生了什麼**_ 。但儘管如此，我們還是很認真地知道在中國發生了狗屎事件（我認為是這樣）。但是現在人們正在破壞互聯網，這確實不好。我們知道您正在為此而苦苦掙扎，但是您可以冷靜地談論它。這不是他媽的猶太人和“黑人”的原因。
另外，我們不想使互聯網成為政治話題，這是用來分享我們所做的事情並結交朋友的東西。即使不公平，也確實不值得破壞我們的東西。
因此，請不要破壞互聯網，這確實不會助您伸張正義。希望一切都好。祝你有美好的一天。

**Comment by neilogd** [comment]
Please stop harvesting organs from political prisoners eh?

**Comment by datae-git** [comment]
> Please stop harvesting organs from political prisoners eh?

Organs are expensive, not harvesting them would be a waste

**Comment by neilogd** [comment]
Give away your own organs then you disgusting fuck.

**Comment by liuem** [comment]
Agree!,but this software violates the rules

**Comment by datae-git** [comment]
> Give away your own organs then you disgusting fuck.

I think you're just jealous I have more organs than them

**Comment by ItsCioss** [comment]
> Give away your own organs then you disgusting fuck.

Why ? @neilogd 
Remember I don't really get it, can you tell me what's happening ?

**Comment by FlyEmojiStudiooo** [comment]
uhhh，idk wtf is fucking happed
can some one tell me wtf is happed about these zhina
Why they so angry on Notepad++ issue wtf???

**Comment by Jnchi** [comment]
> no cause for fucking jews and "niggers".

See also: https://www.youtube.com/watch?v=pAaXzHJhA18
