### ISSUE TITLE
就你知道六四？就你知道文革？开了眼就为了骂国家，开的怕不是腚眼哦？

### ISSUE THREAD

**Issue by maozhengmingx** [notepad-plus-plus/notepad-plus-plus#7280]
### Steps to Reproduce the Issue

1. 
2. 
3.

**Comment by neilogd** [comment]
Please stop harvesting organs from political prisoners eh?

**Comment by maozhengmingx** [comment]
I just want to make it clear that for China, territorial and ethnic relations are no joke

**Comment by neilogd** [comment]
Indeed they are no joke, they are oppression.

**Comment by CodeAunt** [comment]
> Indeed they are no joke, they are oppression.

I wonder how you people get educated and believe in such fake news talking shit
