### ISSUE TITLE
洗版是不良行為

### ISSUE THREAD

**Issue by y2mk1ng** [notepad-plus-plus/notepad-plus-plus#7286]
洗版是不良行為，而 GitHub 是個就事論事的地方，code 與功能沒有問題，沒有 bug 、沒有 weakness 或 vulnerability 的話，就請不要再洗版了，以免影響其他人發 issue 的權利，謝謝。

GitHub is a place where everyone can discuss on issues of repositories and codes. In case there is any bug, weakness or vulnerability, issues unrelated should be closed. Thank you for your cooperation.

**Comment by 2498981627** [comment]
话是这么说，洗版也确实不对，但是Notepad++自己作。当然，我没有发表任何评论。

**Comment by FlyEmojiStudiooo** [comment]
我就真的看不懂了，为什么一群支那玻璃心小粉红冲来Github的notepad++ issues页面暴力洗板，一群群人为了”保护/爱”自己的国家结果整的自己脑子都烧了？
