### ISSUE TITLE
New <Source code Pro> font don't show amp. character for some languages.

### ISSUE THREAD

**Issue by Reidid92** [notepad-plus-plus/notepad-plus-plus#729]
The & char. is not shown (like a space) with the <Source code Pro> font, when language is set
to (Shell or C++, ...) , it's OK with some others (Normal text, Batch, ...)
seen on 6.8.1.
Example text; "1&2" appears as "1 2"

**Comment by Rikk** [comment]
That bad font is already removed and will not be in next version. #close

**Comment by milipili** [comment]
#676

**Comment by donho** [comment]
FYI:
https://notepad-plus-plus.org/community/topic/8202/notepad-new-release-6-8-2-updated
