### ISSUE TITLE
Why do you like discuss politics in other countries？

### ISSUE THREAD

**Issue by hucstar** [notepad-plus-plus/notepad-plus-plus#7295]
You are a geeker，but you discuss the politics in other countries. Is this your power？ Whether a country has human right or not the people of this nation will say.  Who do you think you are？World police dog dog dog？

**Comment by Logiar** [comment]
You are chineser, but you discuss the opinions of other people outside china. Did you ask your government for permission before doing this?

**Comment by notepadgodie** [comment]
> You are chineser, but you discuss the opinions of other people outside china. Did you ask your government for permission before doing this?

you are changing changing concepts, human rights can not equal with one preson.

**Comment by llacb47** [comment]
>dog dog dog
lol

**Comment by hucstar** [comment]
The opinions of other people？Your opinions are discuss others‘ things？Are you kitting me？ This is our cultute differents？Manage your wife’s derailment, don’t care about other people’s affairs. Whatever do you know China？ Are people in your country so rigorous in doing things? Under the conclusion and gibberish?

**Comment by hucstar** [comment]
https://github.com/notepad-plus-plus/notepad-plus-plus/issues/7295#issuecomment-547856995 
The opinions of other people？Your opinions are discuss others‘ things？Are you kitting me？ This is our cultute differents？Manage your wife’s derailment, don’t care about other people’s affairs. Whatever do you know China？ Are people in your country so rigorous in doing things? Under the conclusion and gibberish?

**Comment by rulssi** [comment]
> [#7295 (comment)](https://github.com/notepad-plus-plus/notepad-plus-plus/issues/7295#issuecomment-547856995)
> The opinions of other people？Your opinions are discuss others‘ things？Are you kitting me？ This is our cultute differents？Manage your wife’s derailment, don’t care about other people’s affairs. Whatever do you know China？ Are people in your country so rigorous in doing things? Under the conclusion and gibberish?

Why don't you manage your wife instead of opening issues here? We actually have to boycott real companies and products for being controlled by your corrupted government. And here you are making a issue because of a free software you use.. if you don't like this developers message then change software and developer like civilized people. Man you must have easy life is this is a problem for you..

**Comment by hucstar** [comment]
https://github.com/notepad-plus-plus/notepad-plus-plus/issues/7295#issuecomment-547867495
Free software we advocate. But Stupid remarks we can't stand. If The country has issue there will be a lot of national people dislike the government like you. But Why do so many people oppose you？ Please Move your pig brain to think about it.

**Comment by Logiar** [comment]
> The opinions of other people？Your opinions are discuss others‘ things？Are you kitting me？ This is our cultute differents？Manage your wife’s derailment, don’t care about other people’s affairs. Whatever do you know China？ Are people in your country so rigorous in doing things? Under the conclusion and gibberish?

The point I was making is that you're stating your opinion, much the same way some else did which caused your outrage. Are we now supposed to be outraged at you stating your opinion or should we start discussing the content of both opinions?

**Comment by hucstar** [comment]
>https://github.com/notepad-plus-plus/notepad-plus-plus/issues/7295#issuecomment-547872122The point I was making is that you're stating your opinion, much the same way some else did which caused your outrage. Are we now supposed to be outraged at you stating your opinion or should we start discussing the content of both opinions?
I don't want to talk about things with people who know one-sided things any more.

**Comment by Logiar** [comment]
> > [#7295 (comment)](https://github.com/notepad-plus-plus/notepad-plus-plus/issues/7295#issuecomment-547872122)
> > The point I was making is that you're stating your opinion, much the same way some else did which caused your outrage. Are we now supposed to be outraged at you stating your opinion or should we start discussing the content of both opinions?
> 
> I don't want to talk about things with people who know one-sided things any more.

If you're not willing to talk about it then you shouldn't be upset that they only know one side as you put it.

**Comment by Willt125** [comment]
Or you can all GET IT OUT OF THE REPO AND TAKE IT TO TWITTER
Anywhere but the repos

**Comment by StuartFarmer** [comment]
> You are a geeker，but you discuss the politics in other countries. Is this your power？ Whether a country has human right or not the people of this nation will say. Who do you think you are？World police dog dog dog？

It's called freedom of speech and expression, which is a concept you don't seem to understand. Sticks and stones will break my bones but words will never hurt me.

Also: Free Hong Kong. Save the Uigurs. Taiwan #1.

**Comment by issiki** [comment]
> > You are a geeker，but you discuss the politics in other countries. Is this your power？ Whether a country has human right or not the people of this nation will say. Who do you think you are？World police dog dog dog？
> 
> It's called freedom of speech and expression, which is a concept you don't seem to understand. Sticks and stones will break my bones but words will never hurt me.
> 
> Also: Free Hong Kong. Save the Uigurs. Taiwan #1.

Save hk from the hk thugs. Meet the Uigurs in Xinjiang with your eyes. Taiwa🐸 #1.

**Comment by Korb** [comment]
This is a duplicate of #6288 (disrespect for other members of the FOSS community by posting political propaganda spam in text editor resources).
