### ISSUE TITLE
我和我的祖国，一刻也不能分割

### ISSUE THREAD

**Issue by FunkyPantss** [notepad-plus-plus/notepad-plus-plus#7296]
Me and my country can't be separated for a moment.

**Comment by FunkyPantss** [comment]
犯我中华者，虽远必诛!
Even though a thousand miles away, the man who affront China will pay!

**Comment by Adorable-Catgirl** [comment]
free hong kong

**Comment by someja** [comment]
> free hong kong

free yourself, spirit, thought!
