### ISSUE TITLE
怎麽都在罵啦，這個bug怎麼解決

### ISSUE THREAD

**Issue by tbzmasile** [notepad-plus-plus/notepad-plus-plus#7299]
嘻嘻嘻，乡民们的历史学的挺好嗷，你们的妈辛苦卖批赚来的钱没有白花，她们死前唯一的遗憾是没有找到你们的亲爹，只知道他是个日本人，嘻嘻嘻嘻嘻

**Comment by liuem** [comment]
这个bug无解啊，只能等他们的日本亲爹去认了。

**Comment by tbzmasile** [comment]
加油嗷，岛狗刷屏不要停嗷

**Comment by KalChn** [comment]
哈哈哈，这些乡民还要反攻大陆咧，笑死老子了
