### ISSUE TITLE
CMake syntax highlighting severely out of date

### ISSUE THREAD

**Issue by rcdailey** [notepad-plus-plus/notepad-plus-plus#732]
What's the procedure for updating the syntax highlighter with the latest list of keywords? I'm happy to help with this, but it hasn't been updated in YEARS.

**Comment by dail8859** [comment]
I think it should be as simple as adding the new keywords to the langs.model.xml file. I think there is a recent pull request that adds some keywords to the PHP language so you can see how that was done.

**Comment by rcdailey** [comment]
@dail8859 My understanding years ago is that Don is phasing out this method of syntax highlighting for a more GUI-driven system in Notepad++ (Define Custom Language option, I think).

I wanted to wait for @donho's feedback.

Thanks for the info though.

**Comment by donho** [comment]
@rcdailey User Defined Language System is for non-buildin language.
I'll be glad to accept your pr regarding the updated keyword list of CMake.

**Comment by rcdailey** [comment]
@donho You probably don't remember, but a few years ago I contacted you about this. At the time I *did* provide an updated XML file, but you instead preferred setting up CMake in UDL. I'm not sure if you are still using that system. Personally I found it rather over engineered and complex for the task.

Another issue is that functions (`function`, `macro`: red by default), conditionals (`if`, `endif`: purple by default), and looping constructs (`foreach`, `endforeach`: teal by default) are hard-coded in C++ I believe. If not all of them, I know some of them are. I can't remember exactly.

So this change isn't completely tied to just the XML implementation. Any thoughts on this? Going forward do you truly expect people to modify XML and/or C++ code to extend the syntax highlighting capabilities of a language?

I will get started on the work and have a PR up. But I just wanted to remind you about UDL and see if that's still a "thing".

**Comment by donho** [comment]
@rcdailey Sorry I cannot recall it but it should be before including CMake lexer in Notepad++.

Regarding the hard coding things in lexer, it's for the code fording. I don't thing it will impact CMake syntax highlighting. Add the new keywords in langs.xml (adding in langs.model.xml and removing your langs.xml then launch Notepad++).
The CMake lexer is not maintained by me, so I prefer to not modify it.

**Comment by rcdailey** [comment]
I am modifying the lexer for function/endfunction keywords. Need code folding support for these as well. How do you prefer to make this change?

**Comment by donho** [comment]
The patch of LexCmake.cxx : 
https://github.com/notepad-plus-plus/notepad-plus-plus/blob/master/scintilla/lexers/LexCmake.cxx
should be submited to Scintilla project:
http://www.scintilla.org/

or you can contact the maintainer of CMaker lexer Cristian Adam <cristian [dot] adam [at] gmx [dot] net> to submit your patch.

**Comment by dail8859** [comment]
So just keep in mind that means it will be a while before those changes propagate into the N++ repository since Scintilla [isn't updated that often](https://github.com/notepad-plus-plus/notepad-plus-plus/commits/master/scintilla/version.txt).

**Comment by rcdailey** [comment]
So an interim change directly to the checked in source code makes more
sense then.

**Comment by rcdailey** [comment]
I contacted Cristian Adam, he says he's willing to submit the code for me. He said it's been a while since it has been updated, so he may scrub it over real good.

In the meantime, I'm having some trouble getting the new words style to work. I was hoping @donho could help.

I have added a new `WordsStyle` element under the `cmake` lexer type in my `stylers.xml` in my AppData/Roaming directory:

    <WordsStyle name="FUNCTIONDEF" styleID="15" fgColor="FF0000" bgColor="FFFFFF" fontName="" fontStyle="1" fontSize="" />

However, even with the code changed in scintilla to support `styleID` `15`, I do not see `FUNCTIONDEF` in the Styler Configurator. So something isn't registering right.

How can I test changes to languages and such?

**Comment by donho** [comment]
@rcdailey Sorry for the late reply.
It works to me:
![cmake](https://cloud.githubusercontent.com/assets/90293/10249493/e9cfef2c-6925-11e5-888c-926b476b0c71.png)

I guess you modified the wrong stylers.xml.
Please check if "doLocalConf.xml" is present in your notepad++.exe directory. If yes, then you should modify stylers.xml of the same directory. Otherwise, in %APPDATA%\Notepad++\ folder.

**Comment by Flamefire** [comment]
@donho Would it be acceptable if add at least the function/endfunction manually to scintilla in this repo?

They haven't updated their CMake support at all and are now on version 4.1.0 and 3.7.6. The 4.x series uses C++17 so this might not be a good idea yet, but I could also update to the latests (and possibly last) 3.x version.

**Comment by MetaChuh** [comment]
we are closing this issue due to its age and multiple newer notepad++ versions since it was filed.

please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html).
if your issue persists, and it is still of relevance to you, please feel free to file a new issue.

thank you for your help and best regards.

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
```
[<kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd>](https://notepad-plus-plus.org/community/)
