### ISSUE TITLE
Function List issues

### ISSUE THREAD

**Issue by Rikk** [notepad-plus-plus/notepad-plus-plus#733]
I'm preparing a pull to fix some (if not all) of these issues:
- ~~When search field is not empty, Function List's background color does not follow Npp theme:~~
:white_check_mark: Fixed in https://github.com/notepad-plus-plus/notepad-plus-plus/pull/739
![fu-list-issue-background](https://cloud.githubusercontent.com/assets/2916485/9301632/3bd058b0-44a6-11e5-8acd-081e60e38441.gif)

- ~~Icons' image not centered in icons rectangle:~~
:white_check_mark: Fixed in https://github.com/notepad-plus-plus/notepad-plus-plus/pull/739
![fu-list-issue-icon](https://cloud.githubusercontent.com/assets/2916485/9301623/2f72c652-44a6-11e5-8d84-b93f6783c71a.png)

- ~~When double-clicking the panel's toolbar, it briefly displayed a dialog to customize icons, but we can't use it there.~~
:white_check_mark: Fixed in https://github.com/notepad-plus-plus/notepad-plus-plus/pull/739

-  Icons (mini toolbar and in TreeView), ~~close button and textual search box~~ do not scale in high-dpi:
:ballot_box_with_check: Partially-fixed in https://github.com/notepad-plus-plus/notepad-plus-plus/pull/739
![fu-list-issue-scale](https://cloud.githubusercontent.com/assets/2916485/9301904/835b64b6-44a8-11e5-94d8-2972f7353ca7.png)

- :bug: It would be better to wrap icons when they don't fit in panel's width, instead of cutting them.

**Comment by milipili** [comment]
These are separate matters. If possible avoid a big commit.

**Comment by Rikk** [comment]
Will be small, I'm trying to figure out how to resize refresh and sort icons, having no luck, probably will let them as is.
