### ISSUE TITLE
Copy or Paste through Context Menu causes N++ window to change size

### ISSUE THREAD

**Issue by tmcqueen** [notepad-plus-plus/notepad-plus-plus#734]
When I copy or paste using the context menu, the window size changes to the minimum amount.  All that shows is the icon, part of the filename and the control box.  Windows 7 Pro SP1 64 Bit.

![npp_problem](https://cloud.githubusercontent.com/assets/18832/9306342/4eaaadb6-44bd-11e5-8f54-e3ce1b141e79.PNG)

**Comment by milipili** [comment]
Oo Can anyone be able to reproduce that ?

**Comment by tmcqueen** [comment]
Looks like I wasn't on the latest version :/

I updated to 6.8.1 and the issue went away
