### ISSUE TITLE
Dspell Comment

### ISSUE THREAD

**Issue by jasonnicholson** [notepad-plus-plus/notepad-plus-plus#735]
DSpellCheck.dll was disabled with the install of v6.8.1. Ironically, the change log shown below has 4 spelling errors in 10 lines of text. I think this supports the idea that the Dspell plugin is very useful and I hope to see it enabled by default in future versions of notepad++.

![image](https://cloud.githubusercontent.com/assets/1058191/9314380/1776176e-44ee-11e5-97d4-b65fc9c80f74.png)

Thanks for the great tool that Notepad++ is!

**Comment by donho** [comment]
I like DSpellCheck as well. However, DSpellCheck plugin has some stability issues and make Notepad++ hanging on exit for some configurations. That's the reason to remove it from release.

Fix in : https://github.com/notepad-plus-plus/notepad-plus-plus/commit/7b352fb43899c916fe1b4251f6bca384a380d276
