### ISSUE TITLE
More consistent overwrite mode

### ISSUE THREAD

**Issue by h-h-h-h** [notepad-plus-plus/notepad-plus-plus#736]
Hello,

there's some behavior in overwrite mode (press insert key <kbd>Ins</kbd>) that's good to improve in my opinion:
- When pasting text from the clipboard, it is inserted instead of overwriting text of the same width and height. I think overwriting should take place line-wise, i.e., the line breaks of the text to get replaced and of the replacement text should match.
- When you delete or cut text, this changes the length of the lines involved. The text should be replaced with the same amount of spaces. However, I think users would expect not to get spaces at the end of a line.

The suggestions also apply to the column mode (see Edit menu).

**Comment by donho** [comment]
Let's keep current behaviour.
