### ISSUE TITLE
Ability to measure selection

### ISSUE THREAD

**Issue by h-h-h-h** [notepad-plus-plus/notepad-plus-plus#737]
Hello,

I would like to get information about the width and height of the selection. When there is more than one selection, maybe the measurements of the overall area that has selected text should be told. It should be handled correctly in column mode (see Edit menu).

The information of the width and height of the selection should be told by the status bar.

I'm unsure which format is the best:
- Width, height:
  - `Selection: 80 x 5 ch.`
  - `Selection: 80 · 5 ch.`
  - `80 · 5 ch. selected`
- Height, width:
  - `Selection: 5 ln., 80 col.` (preferred)
  - `Selection: 5 ln. · 80 col.`
  - `5 ln., 80 col. selected` (preferred)

**Comment by h-h-h-h** [comment]
I realized there is a feature like this, but it not visible due to Windows DPI scaling:
![status bar](https://cloud.githubusercontent.com/assets/13482553/9539058/342983a8-4d4c-11e5-9b45-642f67598c39.png)

However, I don't like the inconsistency and other things:
- "length", "lines" don't have a capital letter
- "Ln", "Col", "Sel" have a capital letter, but to my information an abbreviation should end with a dot when there are characters following
- Why is there a space before the colon? Is this derived from french? It's not typical for English
- Ideally, every piece of information would be aligned independently to not be shifted around by other pieces of information
- I think one of the texts above or a similar one suits better for the information about the selection

**Comment by Rikk** [comment]
https://github.com/notepad-plus-plus/notepad-plus-plus/issues/539
https://github.com/notepad-plus-plus/notepad-plus-plus/issues/629

**Comment by donho** [comment]
Outdated.
