### ISSUE TITLE
Padding for tab captions in find-and-replace dialog

### ISSUE THREAD

**Issue by h-h-h-h** [notepad-plus-plus/notepad-plus-plus#738]
Hello,

in my opinion a little padding is appropriate for the tab captions in the find-and-replace dialog. Take a look at the padding of the buttons on the same dialog. This looks a little bit better and provides more space for a tab to get clicked.

**Comment by Rikk** [comment]
Something like this?
![find-dialog](https://cloud.githubusercontent.com/assets/2916485/9323578/685d2536-4558-11e5-9f44-351e678c578b.gif)

**Comment by h-h-h-h** [comment]
Thanks for the picture.

- The picture shows a *window padding* that should be accomplished. ✓
- The picture shows the *"Transparency" checkbox* corrected in its *position*. ✓
- The picture doesn't show what I originally meant. So to illustrate it, not:
```
+----+
|Find|
+----+
```
But:
```
+----------------+
|                |
|      Find      | ✓
|                |
+----------------+
```

**Comment by Rikk** [comment]
Wanna give it a try? [notepad++.exe.7z](http://portfolio.ricardo.solutions/etc/notepad++.exe.7z)

**Comment by h-h-h-h** [comment]
Thanks for the help. That's a great improvement!
Before:
![Before](https://cloud.githubusercontent.com/assets/13482553/9344832/e0f73a1e-460b-11e5-846a-db88e74ca960.png)
After:
![After](https://cloud.githubusercontent.com/assets/13482553/9344831/e0f3e896-460b-11e5-938e-0109c0b33a91.png)
However, as you can see, there are still issues. Some of them come from the the change that just happened.

**Comment by Rikk** [comment]
Yes, it created the need to adjust a lot of elements. Dunno if I'll have inspiration for that.
These things are super boring to do for win32 interfaces -- c++ and windows interfaces looks so odd to implement I don't believe how devs still do it.
The blank space after "transparency" can't be fixed if that space is needed for translations -- but the way it was implemented, it will always be a label on top of that line.

**Comment by h-h-h-h** [comment]
I didn't know Notepad++ was GUI-wise implemented this way. Wasn't there some discussion to use a proper GUI toolkit?

**Comment by Rikk** [comment]
I know @milipili is saying things about a new interface and blabla, but afaik I still haven't seem any real work about that. Maybe they are hiding things in private repositories -- in a open-source hurting way, who knows? Or maybe just nothing done yet...
Anyway, I'm sure it will take long time for any stable result. Even more because Don Ho seems to be a very silent person, and he takes to himself all the responsibilities regarding the future of Notepad++. If you ask me, it is like a freeware, with source available. There are a few people doing patches, but not a development community with people devoted to make it evolve.

**Comment by h-h-h-h** [comment]
Anyhow, I don't understand how one main developer can work on so many different issues at "the same time" or mixing work on different issues frequently.

**Comment by Rikk** [comment]
Just some parenthesis:
(1. He is not working on anything related to Npp)
(2. He works on the same french company with milipili)
(2b. But he is Made in China)
(3. I think he doesn't care for something that don't give him money)
(4. I'm sure he doesn't care for being [dirty in public](https://github.com/notepad-plus-plus/notepad-plus-plus/pull/543))

This is a good example of a real open-source project:
https://github.com/WordPress/WordPress/commits/master

**Comment by milipili** [comment]
@Rikk Could you stop saying stupid things ?

**Comment by milipili** [comment]
@rikk @h-h-h-h I like those changes. Could you create a PR for this ?

**Comment by donho** [comment]
@Rikk 
> If you ask me, it is like a freeware, with source available. There are a few people doing patches, but not a development community with people devoted to make it evolve.

Then why are you still here? If I were you and I feel the same thing, I will go away.

**Comment by Rikk** [comment]
Someone needs to pressure.

**Comment by donho** [comment]
@Rikk For accepting your buggy PR?

**Comment by Rikk** [comment]
It wasn't my plan to do a PR for that. Problably should not do.

And look mr Donho: the buggy code writer is yourself.

**Comment by Rikk** [comment]
Way to be hostil. Let's say we both born in shit countries.

**Comment by Rikk** [comment]
>non-tested PR
Oh fuck, you still with that idea? I test ALL my current PR. Perhaps you don't. You can't spend 1.5 minute for compiling Notepad++.

**Comment by Rikk** [comment]
@h-h-h-h tell me if the new Go To dialog in the build I provided is working or not.

**Comment by donho** [comment]
There are a big amout of contributors of Notepad++ here (without mentioning before the migration to git) : 
https://github.com/notepad-plus-plus/notepad-plus-plus/commits/master 

and if your PR is not accepted, there must be a reason. 

Keep a common sense for the feature and do a quality PR then I will accept it. 
But if you don't even test your submitted code, don't expect people accept it.

**Comment by Rikk** [comment]
How many times should I say: I HAVE TESTED IT.

**Comment by Rikk** [comment]
Good try trying to say the contrary. You lier.

**Comment by Rikk** [comment]
![kkkk](https://cloud.githubusercontent.com/assets/2916485/9369218/212fdc48-469e-11e5-96ce-a42d96155ecf.png)
rofl

**Comment by milipili** [comment]
Please github is not the place for that.

**Comment by milipili** [comment]
@Rikk I completely agree with @h-h-h-h

**Comment by Rikk** [comment]
No, I won't do a PR for this issue. Maybe won't do any more PR. Because my PRs are crap. Even if they are much better tested than any commit coming from donho, they are still shit.

**Comment by h-h-h-h** [comment]
> @h-h-h-h please tell us if the new Go To dialog in the build I provided is working or not.
(@Rikk)

The "Go To..." dialog is working fine with all the improvements. It just shouldn't say, "window on top", but "active" (in my understanding "focused" is wrong, too).

**Comment by Rikk** [comment]
[npp.Rikk.7z](http://portfolio.ricardo.solutions/etc/npp.Rikk.7z)

**Comment by h-h-h-h** [comment]
@Rikk: The remaining paddings of the find-and-replace dialog are corrected. It looks very good.

**Comment by Rikk** [comment]
Btw, if someone want to merge this, it can be found [**here**](https://github.com/Rikk/notepad-plus-plus/commits/FindReplaceDialog-fixes). As said already, I won't make a PR, because all I would receive is zero feedback and lots of \<fill-here>.
