### ISSUE TITLE
ALOO GITHUB POLICE, PLES DEAL WITH SPAMMERS!! 

### ISSUE THREAD

**Issue by dixman69** [notepad-plus-plus/notepad-plus-plus#7381]
Also subcirbe to utube thank

**Comment by notepadgodie** [comment]
guess what？ somebody don't apologise for he said for one day, this attack won't be stop for one day.

**Comment by notepadgodie** [comment]
BTW, this attack is written by different person, not only one.

**Comment by dixman69** [comment]
ok soo subscribe to my youtube ??

**Comment by y2mk1ng** [comment]
What I want to do now is to crack into their bots ...
