### ISSUE TITLE
这就是台独狗吗，真是有够好笑呢

### ISSUE THREAD

**Issue by zombie12138** [notepad-plus-plus/notepad-plus-plus#7394]
# 这就是台独狗吗，真是有够好笑呢

**Comment by tbzmasile** [comment]
毕竟亲妈死了还没找到亲爹

**Comment by dxp8964** [comment]
<a src="https://www.youtube.com/watch?v=FhXdLIBVCMQ"><img width="948" alt="hello 2019-10-30 at 7 16 18 PM" src="https://user-images.githubusercontent.com/56756710/67853580-d36f9380-fb49-11e9-97e2-a4fa507f4375.png"></a>

https://www.youtube.com/watch?v=FhXdLIBVCMQ

同志们加油，听取习近平同志讲话，有组织的战斗！

**Comment by droidb0t** [comment]
动态网自由门 天安門 天安门 法輪功 李洪志 Free Tibet 六四天安門事件 The Tiananmen Square protests of 1989 天安門大屠殺 The Tiananmen Square Massacre 反右派鬥爭 The Anti-Rightist Struggle 大躍進政策 The Great Leap Forward 文化大革命 The Great Proletarian Cultural Revolution 人權 Human Rights 民運 Democratization 自由 Freedom 獨立 Independence 多黨制 Multi-party system 台灣 臺灣 Taiwan Formosa 中華民國 Republic of China 西藏 土伯特 唐古特 Tibet 達賴喇嘛 Dalai Lama 法輪功 Falun Dafa 新疆維吾爾自治區 The Xinjiang Uyghur Autonomous Region 諾貝爾和平獎 Nobel Peace Prize 劉暁波 Liu Xiaobo 民主 言論 思想 反共 反革命 抗議 運動 騷亂 暴亂 騷擾 擾亂 抗暴 平反 維權 示威游行 李洪志 法輪大法 大法弟子 強制斷種 強制堕胎 民族淨化 人體實驗 肅清 胡耀邦 趙紫陽 魏京生 王丹 還政於民 和平演變 激流中國 北京之春 大紀元時報 九評論共産黨 獨裁 專制 壓制 統一 監視 鎮壓 迫害 侵略 掠奪 破壞 拷問 屠殺 活摘器官 誘拐 買賣人口 遊進 走私 毒品 賣淫 春畫 賭博 六合彩 天安門 天安门 法輪功 李洪志 Winnie the Pooh 劉曉波动态网自由门

**Comment by tbzmasile** [comment]
嘻嘻嘻，乡民们的历史学的挺好嗷，你们的妈辛苦卖批赚来的钱没有白花，她们死前唯一的遗憾是没有找到你们的亲爹，只知道他是个日本人，嘻嘻嘻嘻嘻

**Comment by sqluxy** [comment]
> 
> 
> <img alt="hello 2019-10-30 at 7 16 18 PM" width="948" src="https://user-images.githubusercontent.com/56756710/67853580-d36f9380-fb49-11e9-97e2-a4fa507f4375.png">
> 
> https://www.youtube.com/watch?v=FhXdLIBVCMQ
> 
> 同志们加油，听取习近平同志讲话，有组织的战斗！

omg this is amazing, [Eminem, Kendrick Lamar, Nicki Minaj, Jay-Z and 69 others] are crying in the club :')
