### ISSUE TITLE
花样作死

### ISSUE THREAD

**Issue by Wang-Yang** [notepad-plus-plus/notepad-plus-plus#7395]

**Comment by dxp8964** [comment]
<a src="https://www.youtube.com/watch?v=FhXdLIBVCMQ"><img width="948" alt="hello 2019-10-30 at 7 16 18 PM" src="https://user-images.githubusercontent.com/56756710/67853580-d36f9380-fb49-11e9-97e2-a4fa507f4375.png"></a>

https://www.youtube.com/watch?v=FhXdLIBVCMQ

同志们加油，听取习近平同志讲话，有组织的战斗！
