### ISSUE TITLE
Special characters not shown in list of recent files

### ISSUE THREAD

**Issue by thomasatwork** [notepad-plus-plus/notepad-plus-plus#740]
Since notepad++ 6.8.1 special characters like the german "umlauts" ä, ü, Ä, Ü are not shown in the list of recent files.
![special_characters_not_shown](https://cloud.githubusercontent.com/assets/13848867/9326993/2680cd66-459e-11e5-9f9f-4e46f9542880.png)

**Comment by Rikk** [comment]
Seems to be ok here. Could you paste here the name of a file that is not displayed?

**Comment by thomasatwork** [comment]
Interesting. I have tested the issue again. When I create a file like C:\Übung\Änderung\test_ÄÜäüÖö.conf or C:\Übung\Änderung\test_ÄÜäüÖö.test every thing seems to be okay and in the recent file list both files will be displayed with all special characters.

But files I have opened before the update (older entries) are not displayed within the recent file list correctly.

**Comment by Rikk** [comment]
Maybe it wrote filenames wrongly into *config.xml*... if they are still listed or if you've got a backup of that file you could compare the entries...

**Comment by thomasatwork** [comment]
I think so too, sorry. Within the config.xml it seemed that the special character "ü" has been encoded two times different:
        <File filename="C:\workspace\W&#xFFFC;ste....\conf\acme.txt" />
compared to
        <File filename="C:\workspace\W&#x00FC;ste....\conf\conf\acme.xml" />
Friendly regards,

Thomas
