### ISSUE TITLE
中国人通过狂暴的评论显示出自己的真心，这种毒药怎么能产生美丽？

### ISSUE THREAD

**Issue by StewAlexanderACC** [notepad-plus-plus/notepad-plus-plus#7400]
...

**Comment by notepadgodie** [comment]
你要知道的是，这次的狂暴是真的在玩火，而且是点燃火药桶，你想让中国人理性都不可能。

**Comment by c0rpse** [comment]
狂暴的评论？毒药？
狗子们说话好有艺术啊！
牛逼！

**Comment by mengxz0203** [comment]
NMSL

**Comment by Yuri0314** [comment]
我的父母告诉我，对不了解真相的事物不要妄加评论，因为可能会伤害到无辜的人。看起来你似乎是孤儿。

**Comment by CodeAunt** [comment]
I wonder what are you talking about through google translate?

**Comment by mengxz0203** [comment]
知道我在说什么吗，也不要妄加评论我，孤儿。




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "xtl4350"<notifications@github.com&gt;; 
发送时间: 2019年10月30日(星期三) 晚上8:23
收件人: "notepad-plus-plus/notepad-plus-plus"<notepad-plus-plus@noreply.github.com&gt;; 
抄送: "峡谷臻臻"<1196797300@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [notepad-plus-plus/notepad-plus-plus] 中国人通过狂暴的评论显示出自己的真心，这种毒药怎么能产生美丽？ (#7400)




我的父母告诉我，对不了解真相的事物不要妄加评论，因为可能会伤害到无辜的人。看起来你似乎是孤儿。

**Comment by zhangwukong** [comment]
> 我的父母告诉我，对不了解真相的事物不要妄加评论，因为可能会伤害到无辜的人。看起来你似乎是孤儿。



> ...

NMSL WSND, can u translate this through google translate ？

**Comment by zhangwukong** [comment]
NMSL WSND, can u translate this through google translate?

**Comment by KalChn** [comment]
嘻嘻嘻，婊子养出来的狗还知道美感嗷，快带着你妈的骨灰去日本跟你亲爹团聚嗷，嘻嘻嘻嘻嘻

**Comment by StewAlexanderACC** [comment]
Silly humans

Only interested in fighting over scraps, when it is the meal that counts.

Our earth is dying, this is so much more important than any silly words I write.

**Comment by c0rpse** [comment]
NMSL WCNM.Now Use google ,idot!

**Comment by CodeAunt** [comment]
> NMSL WSND, can u translate this through google translate?

WSND是啥啊老铁

**Comment by StewAlexanderACC** [comment]
傻人

**Comment by zhangwukong** [comment]
NMSL WSND, can u translate this through google translate?

> > NMSL WSND, can u translate this through google translate?
> 
> WSND是啥啊老铁

厂长的名言都不知道啊   baidu啊

**Comment by CodeAunt** [comment]
> NMSL WSND, can u translate this through google translate?
> 
> > > NMSL WSND, can u translate this through google translate?
> > 
> > 
> > WSND是啥啊老铁
> 
> 厂长的名言都不知道啊 baidu啊

晓得了，牛批

**Comment by Willt125** [comment]
除非存在實際問題，否則請離開。存儲庫不是放置政治評論的地方。
