### ISSUE TITLE
中國人通過暴力言論表達了自己的真心。 這種毒藥怎麼能產生美感？

### ISSUE THREAD

**Issue by StewAlexanderACC** [notepad-plus-plus/notepad-plus-plus#7402]
...

**Comment by notepadgodie** [comment]
哦

**Comment by dxp8964** [comment]
[![](https://user-images.githubusercontent.com/56756710/67853580-d36f9380-fb49-11e9-97e2-a4fa507f4375.png)同志们加油，听取习近平同志讲话，有组织的战斗！](https://www.youtube.com/watch?v=FhXdLIBVCMQ)

**Comment by KalChn** [comment]
嘻嘻嘻，婊子养出来的狗还知道美感嗷，快带着你妈的骨灰去日本跟你亲爹团聚嗷，嘻嘻嘻嘻嘻

**Comment by dongyingt** [comment]
说了多少遍了，别用汉字骂自己
