### ISSUE TITLE
爱国体现了人们对自己祖国的深厚感情，反映了个人对祖国的依存关系，是人们对自己故土家园、民族和文化的归属感、认同感、尊严感与荣誉感的统一。它是调节个人与祖国之间关系的道德要求、政治原则和法律规范，也是民族精神的核心。每个人来到这个世界，都要在社会中生存，都要获取生存发展的物质条件，都要寻求慰藉心灵的精神家园，这一切首先得之于祖国。没有国哪有家，没有家哪有我——这看似平常的话语，道出了最深刻的爱国理由：国家是小家的寄托，更是个人的寄托；国家是物质利益的寄托，更是精神家园的寄托。失去祖国母亲的保护，个人就是无家可归的流浪儿。爱国是每个人都应当自觉履行的责任或义务。履行爱国的责任或义务，是对祖国母亲的报答。

### ISSUE THREAD

**Issue by ghost** [notepad-plus-plus/notepad-plus-plus#7403]
爱国体现了人们对自己祖国的深厚感情，反映了个人对祖国的依存关系，是人们对自己故土家园、民族和文化的归属感、认同感、尊严感与荣誉感的统一。它是调节个人与祖国之间关系的道德要求、政治原则和法律规范，也是民族精神的核心。每个人来到这个世界，都要在社会中生存，都要获取生存发展的物质条件，都要寻求慰藉心灵的精神家园，这一切首先得之于祖国。没有国哪有家，没有家哪有我——这看似平常的话语，道出了最深刻的爱国理由：国家是小家的寄托，更是个人的寄托；国家是物质利益的寄托，更是精神家园的寄托。失去祖国母亲的保护，个人就是无家可归的流浪儿。爱国是每个人都应当自觉履行的责任或义务。履行爱国的责任或义务，是对祖国母亲的报答。

**Comment by dxp8964** [comment]
[![](https://user-images.githubusercontent.com/56756710/67853580-d36f9380-fb49-11e9-97e2-a4fa507f4375.png)同志们加油，听取习近平同志讲话，有组织的战斗！](https://www.youtube.com/watch?v=FhXdLIBVCMQ)

**Comment by rrttyyu** [comment]
爱你妈逼的国，打贸易战你跑来敌国网站上？傻逼支那猪

**Comment by a2902793** [comment]
這麼愛國請用碼雲別來這裡啊、這麼愛國別用台灣人開發的notepad++或是美國人開發的vscode阿，不要愛國是工作、用洋貨是生活啊，真香阿玻璃仔！

**Comment by xizhouhezai** [comment]
qaasdsads

**Comment by xizhouhezai** [comment]
> 這麼愛國請用碼雲別來這裡啊、這麼愛國別用台灣人開發的notepad++或是美國人開發的vscode阿，不要愛國是工作、用洋貨是生活啊，真香阿玻璃仔！



> 這麼愛國請用碼雲別來這裡啊、這麼愛國別用台灣人開發的notepad++或是美國人開發的vscode阿，不要愛國是工作、用洋貨是生活啊，真香阿玻璃仔！

看到挺多人好像没什么理性可言，满嘴脏话，只想看看，不想掺和，不过看到你这个回复，我就想说说了，把爱国等同于不用外国产品，这是什么样的逻辑？如果按照你的逻辑，美国人会没有衣服穿，会连手机都用不了，电视看不了，水喝不了，世界上会有很多人裸奔的，搞意识形态对立，在如今全球化的背景下，没有任何好处，大家不能放下偏见，那么就求同存异，何必口嗨，口嗨过后你们能得到什么？世界照样超前发展，你们口嗨就能阻止的了？

**Comment by hilari0n** [comment]
Would anyone care to translate this to English?
Using auto-translators seems to be pointless, as the result is gibberish. Unless this was gibberish in the first place.
As far, as I understood, there's nothing in this thread/issue, regarding the actual Notepad++ functionality. Am I correct?

**Comment by a2902793** [comment]
> Would anyone care to translate this to English?
> Using auto-translators seems to be pointless, as the result is gibberish. Unless this was gibberish in the first place.
> As far, as I understood, there's nothing in this thread/issue, regarding the actual Notepad++ functionality. Am I correct?

nothing important, just some chink talking patriotic shit
