### ISSUE TITLE
shame of you, shame of taiwan

### ISSUE THREAD

**Issue by oriso** [notepad-plus-plus/notepad-plus-plus#7405]
shame of you, shame of taiwan

**Comment by y2mk1ng** [comment]
I'm Taiwanese and I honor your right to speak if it's not spam, although I totally disagree with you in this aspect.

**Comment by oriso** [comment]
> I'm Taiwanese and I honor your right to speak if it's not spam, although I totally disagree with you in this aspect.

你们先搞事情的好吗？你们在自己twitter、facebook怎么说都可以，天天喊台独建国也无所谓，notepad plus plus作为一个知名软件，整天不好好改bug，一会抵制奥运会，一会又解放维吾尔人，你们怎么这么厉害，怎么不去救救库尔德人，怎么不去解放叙利亚？

你去过新疆吗？新疆真实情况你们知道吗？台湾去新疆也不麻烦，留下联系方式，我送你往返机票，去看看真实的新疆，ok？

**Comment by Loys** [comment]
> 你们先搞事情的好吗？你们在自己twitter、facebook怎么说都可以，天天喊台独建国也无所谓，notepad plus plus作为一个知名软件，整天不好好改bug，一会抵制奥运会，一会又解放维吾尔人，你们怎么这么厉害，怎么不去救救库尔德人，怎么不去解放叙利亚？
> 
> 你去过新疆吗？新疆真实情况你们知道吗？台湾去新疆也不麻烦，留下联系方式，我送你往返机票，去看看真实的新疆，ok？

Hey, get out of here oriso, you don't belong here. It is a place for programmers, not for Facebook-人人网 so-called shitty "conversations"

**Comment by y2mk1ng** [comment]
> 
> 
> > I'm Taiwanese and I honor your right to speak if it's not spam, although I totally disagree with you in this aspect.
> 
> 你们先搞事情的好吗？你们在自己twitter、facebook怎么说都可以，天天喊台独建国也无所谓，notepad plus plus作为一个知名软件，整天不好好改bug，一会抵制奥运会，一会又解放维吾尔人，你们怎么这么厉害，怎么不去救救库尔德人，怎么不去解放叙利亚？
> 
> 你去过新疆吗？新疆真实情况你们知道吗？台湾去新疆也不麻烦，留下联系方式，我送你往返机票，去看看真实的新疆，ok？

額 有 bug 請好好通報
都說了，請直接就事論事，有什麼 bug 儘管寫
至於庫德族還有敘利亞的事大家也都很關心好嗎
新疆的事也不是只有你們知道
台灣這邊的消息遠比你們想像中靈通
And still, go back and work on your bug report. It would be nice to the developers of Notepad++.

**Comment by oriso** [comment]
> > 你们先搞事情的好吗？你们在自己twitter、facebook怎么说都可以，天天喊台独建国也无所谓，notepad plus plus作为一个知名软件，整天不好好改bug，一会抵制奥运会，一会又解放维吾尔人，你们怎么这么厉害，怎么不去救救库尔德人，怎么不去解放叙利亚？
> > 你去过新疆吗？新疆真实情况你们知道吗？台湾去新疆也不麻烦，留下联系方式，我送你往返机票，去看看真实的新疆，ok？
> 
> Hey, get out of here oriso, you don't belong here. It is a place for programmers, not for Facebook-人人网 so-called shitty "chats"

you get out first.

**Comment by Loys** [comment]
oriso You are so funny 😂

**Comment by oriso** [comment]
> > > I'm Taiwanese and I honor your right to speak if it's not spam, although I totally disagree with you in this aspect.
> > 
> > 
> > 你们先搞事情的好吗？你们在自己twitter、facebook怎么说都可以，天天喊台独建国也无所谓，notepad plus plus作为一个知名软件，整天不好好改bug，一会抵制奥运会，一会又解放维吾尔人，你们怎么这么厉害，怎么不去救救库尔德人，怎么不去解放叙利亚？
> > 你去过新疆吗？新疆真实情况你们知道吗？台湾去新疆也不麻烦，留下联系方式，我送你往返机票，去看看真实的新疆，ok？
> 
> 額 有 bug 請好好通報
> 都說了，請直接就事論事，有什麼 bug 儘管寫
> 至於庫德族還有敘利亞的事大家也都很關心好嗎
> 新疆的事也不是只有你們知道
> 台灣這邊的消息遠比你們想像中靈通
> And still, go back and work on your bug report. It would be nice to the developers of Notepad++.

兼听则明，偏信则暗。Good Luck for you.

**Comment by oriso** [comment]
> oriso You are so funny 😂
> You're only contribution to Github is : "shame of you, shame of taiwan"
> Do you want to see a psychiatrist?
> Did you ever go to Taiwan?
> It is a wonderful country, and the people there, are really nice :
> Please, stop listening to so-called "communists of China", go to Taiwan and start making real friends !

I went to taiwan this year early. Thank you. Have you ever being to taiwan? Do you ever know why i shame on taiwan?

**Comment by Jan200101** [comment]
who cares this is the wrong place to tell us

**Comment by Loys** [comment]
OK, so, oriso, you've been to Taiwan, early this year ! Wonderful ! 
What did you do, there?
Did you behave well? 
Or did you explain to all the Taiwanese you encountered why you "shame of Taiwan"?

**Comment by oriso** [comment]
> OK, so, oriso, you've been to Taiwan, early this year ! Wonderful !
> What did you do, there?
> Did you behave well?
> Or did you explain to all the Taiwanese you encountered why you "shame of Taiwan"?

Please explain "free-uyghur-edition" first. Thank you.

**Comment by Loys** [comment]
"free-uyghur-edition" is the name of the new version of Notepad++

**Comment by oriso** [comment]
> "free-uyghur-edition" is the name of the new version of Notepad++

shame of taiwan is my attitude to this.

**Comment by Jan200101** [comment]
what?
you are ashamed of taiwan because of the opinion from someone else?

**Comment by Loys** [comment]
yes, oriso, is a kind of a special guy, who understands perfectly Taiwan (he went there this year!) and approximately the Uyghur community 😂 That is why he shamed Taiwan, but not the Uyghur (or any other random people/communities)

**Comment by Jan200101** [comment]
if china is so great go to china and use a chinese text editor

**Comment by oriso** [comment]
> "free-uyghur-edition" is the name of the new version of Notepad++

Please come and visit XiJiang before you publish so called "free-uyghur-edition". XiJiang is beautiful place. My sister is a student at Karamay. I know exactly what happened in XinJiang. But you only know what the news tell you. Buy a plane ticket when next spring. It's beautiful i promise.

**Comment by oriso** [comment]
> if china is so great go to china and use a chinese text editor

If china is bad please do not use anything made in china.

**Comment by cckuailong** [comment]
> if china is so great go to china and use a chinese text editor

little dog, you are great??? I read your code. Wow, how rubbish they are, please enhance your code level please.

**Comment by oriso** [comment]
> > if china is so great go to china and use a chinese text editor
> 
> little dog, you are great??? I read your code. Wow, how rubbish they are, please enhance your code level please.

挫

**Comment by Loys** [comment]
> 
> 
> > "free-uyghur-edition" is the name of the new version of Notepad++
> 
> Please come and visit XiJiang before you publish so called "free-uyghur-edition". XiJiang is beautiful place. My sister is a student at Karamay. I know exactly what happened in XinJiang. But you only know what the news tell you. Buy a plane ticket when next spring. It's beautiful i promise.

So, i do not understand : Why XinJiang is such a beautiful place, but its people can't be free?
Please xplain what is wrong with "free-uyghur-edition"

**Comment by oriso** [comment]
> > > "free-uyghur-edition" is the name of the new version of Notepad++
> > 
> > 
> > Please come and visit XiJiang before you publish so called "free-uyghur-edition". XiJiang is beautiful place. My sister is a student at Karamay. I know exactly what happened in XinJiang. But you only know what the news tell you. Buy a plane ticket when next spring. It's beautiful i promise.
> 
> So, i do not understand : Why XinJiang is such a beautiful place, but its people can't be free?
> Please xplain what is wrong with "free-uyghur-edition"

Come to XinJiang and see the truth. If you interesting I can ask my sister for some recently photo.

**Comment by Jan200101** [comment]
> 
> little dog, you are great??? I read your code. Wow, how rubbish they are, please enhance your code level please.
please try again with proper english before you try insulting me
 
> Come to XinJiang and see the truth. If you interesting I can ask my sister for some recently photos tomorrow.
looks do not matter, actions do
and hell why would anyone here now go to china, we'd be held captive for the things we say

**Comment by Loys** [comment]
> > if china is so great go to china and use a chinese text editor
> 
> If china is bad please do not use anything made in china.

Yes, it is actually what most countries (including Africa) are intending to do now : Don't want spying, Don't want (more) corruption, Don't want cheating. Please search about 華為 and 5G contracts.

**Comment by oriso** [comment]
> > > if china is so great go to china and use a chinese text editor
> > 
> > 
> > If china is bad please do not use anything made in china.
> 
> Yes, it is actually what most countries (including countries in Africa) are intending to do now : Don't want spying, Don't want (more) corruption, Don't want cheating. Please search about 華為 and 5G contracts.

so why don’t publish a free edward snowden edition?

**Comment by y2mk1ng** [comment]
> 
> 
> > > > if china is so great go to china and use a chinese text editor
> > > 
> > > 
> > > If china is bad please do not use anything made in china.
> > 
> > 
> > Yes, it is actually what most countries (including countries in Africa) are intending to do now : Don't want spying, Don't want (more) corruption, Don't want cheating. Please search about 華為 and 5G contracts.
> 
> so why don’t publish a free edward snowden edition?

You can if you want.

**Comment by Jan200101** [comment]
hell the Notepad++ dev being against china is nothing new
in 2008 he put the Boycott Beijing banner on the Notepad++ Sourceforge page

**Comment by Loys** [comment]
I guess, he is not "against China", he is just against the brutality of so-called "communists" from mainland China : See how the mainlanders are insulting everyone for no reason.

**Comment by Loys** [comment]
> Just do it. Some other good names recommend for you, free Catalonia edition, free North Island edition, free Scotland edition, free Quebec edition. Show me your brave, or you're just a coward.

"Show me your brave" 😂
oriso, i wonder how old are you? 
You must be tired, i suggest you go to bed, and tomorrow, get back here and before writing anything, read carefully what you wrote today 😂
It is hilarious believe me !

**Comment by oriso** [comment]
> > > > > if china is so great go to china and use a chinese text editor
> > > > 
> > > > 
> > > > If china is bad please do not use anything made in china.
> > > 
> > > 
> > > Yes, it is actually what most countries (including countries in Africa) are intending to do now : Don't want spying, Don't want (more) corruption, Don't want cheating. Please search about 華為 and 5G contracts.
> > 
> > 
> > so why don’t publish a free edward snowden edition?
> 
> we could at any point
> we could also release the europe edition or africa edition

Just do it.

**Comment by Loys** [comment]
> Talk is cheap. I can't change your prejudice. Good luck for you.

yep, absolutely. Good night ! 
And remember : Get back here tomorrow, reading your entries, you won't be disappointed ! 😂

**Comment by oriso** [comment]
> > Just do it. Some other good names recommend for you, free Catalonia edition, free North Island edition, free Scotland edition, free Quebec edition. Show me your brave, or you're just a coward.
> 
> "Show me your brave" 😂
> oriso, i wonder how old are you?
> You must be tired, i suggest you go to bed, and tomorrow, get back here and before writing anything, read carefully what you wrote today 😂
> It is hilarious believe me !

I will apologize to everyone in this issue if you publish any of free Catalonia edition, free North Island edition, free Scotland edition, free Quebec edition. Just do it.

**Comment by oriso** [comment]
> > Talk is cheap. I can't change your prejudice. Good luck for you.
> 
> yep, absolutely. Good night !
> And remember : Get back here tomorrow, reading your entries, you won't be disappointed ! 😂

Don't be a coward.

**Comment by Loys** [comment]
> I will apologize to everyone in this issue if you publish any of free Catalonia edition, free North Island edition, free Scotland edition, free Quebec edition. Just do it.

Why apologizing? 😂 Are you a real man? 
Real man don't apologize : Real man fight !

**Comment by oriso** [comment]
> > Don't be a coward.
> 
> Ahahah You are so funny ! 😂

coward.

**Comment by Loys** [comment]
> coward.

Must be 11:11 PM now in Beijing, are you not tired? 
You just repeated yourself 😂

**Comment by Willt125** [comment]
@Jan
Inb4 Vim release-Ughyurs edition

**Comment by y2mk1ng** [comment]
> 
> 
> > > coward.
> > 
> > 
> > Must be 11:11 PM now in Beijing, are you not tired?
> > You just repeated yourself 😂
> 
> Final reply. You don't dare because you know Github will ban you. Politically correct. What a funny. Good luck for you.

Really? If so, it is a problem. You know it worth a try...

**Comment by Loys** [comment]
> You don't dare because you know Github will ban you. Politically correct. 

This is actually interesting, oriso thinks it is forbidden to publish a (i quote) "free Catalonia edition", "free North Island edition", "free Scotland edition", "free Quebec edition". Because (i quote) "Github will ban you." (it is not) "Politically correct".
So if oriso is in mainland China (what i believe), he/she must use a VPN to access to this current page (GitHub is censored in Mainland China, see : https://en.wikipedia.org/wiki/Censorship_of_GitHub).
My understanding at this point is :  oriso lives in a wonderful country, but it is required to bypass the law (censorship of GitHub) in order to shame another country (Taiwan), that oriso visited early this year.
oriso didn't explains clearly why he/she said "shame of you, shame of taiwan" and when people asking, before going to bed (tough day, i presume), oriso explains that it is forbidden to provide a software called "free Catalonia edition" etc... on GitHub. 
So oriso must believe everybody lives in a country that's is just like Mainland China, (me, you everyone!) and we all use a VPN to bypass our respective country laws in order to read/write this, on GitHub. Oriso must believe that having different political ideas about regionalism is completely forbidden by our own countries, unless it is against the XinJiang region, and China. So we can write "free-uyghur-edition" but "free-quebec-edition" (as a French man, i would say "Vive le Quebec libre ! ") is completely forbidden by Microsoft (the company that owns GitHub).

So, i understand now, where the problem is in this release : It should be called "free-chinese-edition" !

Good night you all,

Loys

**Comment by xerial817** [comment]
Greetings from Hong Kong. It seems to be a funny thread that oriso shows no respect on the community. And clearly don't know how the world works. 😂

**Comment by johnhamelink** [comment]
> > > Just do it. Some other good names recommend for you, free Catalonia edition, free North Island edition, free Scotland edition, free Quebec edition. Show me your brave, or you're just a coward.
> > 
> > 
> > "Show me your brave" joy
> > oriso, i wonder how old are you?
> > You must be tired, i suggest you go to bed, and tomorrow, get back here and before writing anything, read carefully what you wrote today joy
> > It is hilarious believe me !
> 
> I will apologize to everyone in this issue if you publish any of free Catalonia edition, free North Island edition, free Scotland edition, free Quebec edition. Just do it.

I've just forked notepad-plus-plus and made a new version called "FREE SCOTLAND". Here's proof: https://github.com/johnhamelink/notepad-plus-plus/blob/master/PowerEditor/src/Notepad_plus.rc#L1016

Maybe you can apologise now?

**Comment by xerial817** [comment]
> 
> 
> > > > Just do it. Some other good names recommend for you, free Catalonia edition, free North Island edition, free Scotland edition, free Quebec edition. Show me your brave, or you're just a coward.
> > > 
> > > 
> > > "Show me your brave" joy
> > > oriso, i wonder how old are you?
> > > You must be tired, i suggest you go to bed, and tomorrow, get back here and before writing anything, read carefully what you wrote today joy
> > > It is hilarious believe me !
> > 
> > 
> > I will apologize to everyone in this issue if you publish any of free Catalonia edition, free North Island edition, free Scotland edition, free Quebec edition. Just do it.
> 
> I've just forked notepad-plus-plus and made a new version called "FREE SCOTLAND". Here's proof: https://github.com/johnhamelink/notepad-plus-plus/blob/master/PowerEditor/src/Notepad_plus.rc#L1016
> 
> Maybe you can apologise now?

I bet my $0.02, he is not going to apologize.
Quoting his favorite word: coward, is a nice fit for him.

**Comment by Loys** [comment]
> I've just forked notepad-plus-plus and made a new version called "FREE SCOTLAND". Here's proof: https://github.com/johnhamelink/notepad-plus-plus/blob/master/PowerEditor/src/Notepad_plus.rc#L1016

Brilliant ! 
No fear of BoJo's terrible wrath ! 😂

**Comment by oriso** [comment]
> > I've just forked notepad-plus-plus and made a new version called "FREE SCOTLAND". Here's proof: https://github.com/johnhamelink/notepad-plus-plus/blob/master/PowerEditor/src/Notepad_plus.rc#L1016
> 
> Brilliant !
> No fear of BoJo's terrible wrath ! 😂

make a pull request, ask @donho publish an official release.

**Comment by vulkan-volcano** [comment]
Supporting Taiwan's independence is like supporting Israel - both of them are equivalent to supporting the United States
