### ISSUE TITLE
Lmao, take a look at how media brain wash educated coder to Democratic Party supporters with fake news.

### ISSUE THREAD

**Issue by CodeAunt** [notepad-plus-plus/notepad-plus-plus#7406]
Take a look at how media brain wash educated coder to Democratic Party supporters with fake news. 
How CNN BBC WSJ Times taught you to hate and fear China? 
Trick from the pentagon XD
# Love & Peace
# Fight the extreme religious terrorism.

**Comment by mkeen** [comment]
🇺🇸🇺🇸🇺🇸🇺🇸🇺🇸

**Comment by CodeAunt** [comment]
MAGA

**Comment by Joseph-zheng** [comment]
how many people died form Hillary Clinton running for office?  How long have J. Epstein been killed?
