### ISSUE TITLE
There should be a botnet here. Changing a place to release this is recommended.

### ISSUE THREAD

**Issue by y2mk1ng** [notepad-plus-plus/notepad-plus-plus#7407]
It is likely that there is a botnet that is now interrupting the repo and the network. In case that every user can see the source code, maybe you should have one more site to release your project.

**Comment by Willt125** [comment]
I'll fork, but holy hell I was not wanting to wake up to 5500 unreads

**Comment by y2mk1ng** [comment]
Okay thanks, I think I will fork too.

**Comment by michaellee8** [comment]
I already email the author to suggest him run a auto removal to spammers using github APIs as well as contacting GitHub support for a temporary China IP lockdown for this repo (I know that they have done this to the zhao repo as per China Government request).

**Comment by Willt125** [comment]
Yeah, they'll definitely need the help
But why npp? What did they do?

**Comment by mwsht** [comment]
they are not bot in fact, they are just Chinese from P.R.C. .

**Comment by y2mk1ng** [comment]
> 
> 
> I already emaild the author to suggest him run a auto removal script to spammers using github APIs as well as contacting GitHub support for a temporary China IP lockdown for this repo (I know that they have done this to the zhao repo as per China Government request).

What if the IP is not from China?
Thank you for reminding me to take a deeper look.

**Comment by y2mk1ng** [comment]
> 
> 
> they are not bot in fact, they are just Chinese from P.R.C. .

Uh... I know there are many people from PRC that opened these issues. However, I also suspect that some might have written bots to deliver their messages multiple times in a very short period, and maybe there are some that just carry different messages and have different accounts but are actually from the same author.
Need fact check...

**Comment by y2mk1ng** [comment]
> 
> 
> > > they are not bot in fact, they are just Chinese from P.R.C. .
> > 
> > 
> > Uh... I know there are many people from PRC that opened these issues. However, I also suspect that some might have written bots to deliver their messages multiple times in a very short period, and maybe there are some that just carry different messages and have different accounts but are actually from the same author.
> > Need fact check...
> 
> Just a VPN ban would be enough a good portion of real Chinese spammers since ur average chinese dev don't know how to use a vpn (they will at least know some real information on these political things if they ever have a vpn). Bots are nasty to deal with through, I would suggest do a language detetcion based auto-close script, Chinese character should never exist in GitHub anyway. The identical issues can be detected using hash check as well.

Uh... yes, there can be an auto-close script. But I think there should be a better solution than language-based methods, since we Taiwanese sometimes write readme or commit message in Chinese, particularly among young people. But yes, I'm thinking about trying to hash check.
Thank you.
