### ISSUE TITLE
爱你妈逼的支那国 Fuck you Chinazi, Fuck you CCP

### ISSUE THREAD

**Issue by rrttyyu** [notepad-plus-plus/notepad-plus-plus#7408]
一群支那猪靠着美国人的网站才有口饭吃，现在贸易战还哪来的逼脸在这里叫嚣爱你妈逼的支那国呢，Chinazi的杂种。看不起香港“废青”，你们tmd连996都被当成福报，连自己的公寓都保不住暴雷，你们口里的”废青“把送中法案打到撤回，谁是”废青“？废青站着声讨，你们大陆支那跪着维权，谁是卢瑟？

不是喜欢人肉吗？ 查老子啊？查得出来老子姓你妈逼的姓，老子外籍，你们四等汉抓个屌呢？

**Comment by notepadgodie** [comment]
你也就敢这玩了，去舔你美爹吧，没人拦你

**Comment by Chinazi1989** [comment]
> 你也就敢这玩了，去舔你美爹吧，没人拦你

你去大街上喊一句习近平万岁，你敢吗？

**Comment by Chinazi1989** [comment]
> 你也就敢这玩了，去舔你美爹吧，没人拦你

你看看你身份证后面第一个字念什么？不好意思你是中华人民共和国的居民，仅此而已，你长这么大你有投票权？你只是居住在粪坑里的一条蛆。你有言论自由？你长得那张嘴除了吃饭喊说习近平万岁吗？所以说你们支那猪不是白叫的

**Comment by greatChina1234** [comment]
你敢喊一句中华人民共和国万岁吗？

**Comment by greatChina1234** [comment]
你敢喊一句你是从你妈逼里钻出来的吗？

**Comment by mdesi** [comment]
也就敢拿小号在这瞎BB

**Comment by dongyingt** [comment]
这是日杂

**Comment by notepadgodie** [comment]
> > 你也就敢这玩了，去舔你美爹吧，没人拦你
> 
> 你去大街上喊一句习近平万岁，你敢吗？

刚喊完，怎么了？有意见？我就是爱我习大大怎么了舔狗？

**Comment by wy1456642569** [comment]
> > 你也就敢这玩了，去舔你美爹吧，没人拦你
> 
> 你看看你身份证后面第一个字念什么？不好意思你是中华人民共和国的居民，仅此而已，你长这么大你有投票权？你只是居住在粪坑里的一条蛆。你有言论自由？你长得那张嘴除了吃饭喊说习近平万岁吗？所以说你们支那猪不是白叫的

fuck your mother!    you  go home look?

**Comment by CodeAunt** [comment]
> 一群支那猪靠着美国人的网站才有口饭吃，现在贸易战还哪来的逼脸在这里叫嚣爱你妈逼的支那国呢，Chinazi的杂种。看不起香港“废青”，你们tmd连996都被当成福报，连自己的公寓都保不住暴雷，你们口里的”废青“把送中法案打到撤回，谁是”废青“？废青站着声讨，你们大陆支那跪着维权，谁是卢瑟？
> 
> 不是喜欢人肉吗？ 查老子啊？查得出来老子姓你妈逼的姓，老子外籍，你们四等汉抓个屌呢？

大家可怜可怜这个人吧，说不定幼年丧*母，现在悲痛欲绝精神分裂呢。
小伙子，亮出你的收款码，我们给你打点钱买棺

**Comment by notepadgodie** [comment]
> > 你也就敢这玩了，去舔你美爹吧，没人拦你
> 
> 你看看你身份证后面第一个字念什么？不好意思你是中华人民共和国的居民，仅此而已，你长这么大你有投票权？你只是居住在粪坑里的一条蛆。你有言论自由？你长得那张嘴除了吃饭喊说习近平万岁吗？所以说你们支那猪不是白叫的

你长这么大顶着一张中国人的皮去给外国人做事，说你是人皮禽兽都抬举你了，所以说你们舔狗不是白叫的

**Comment by Willt125** [comment]
除非存在實際問題，否則請離開。存儲庫不是放置政治評論的地方。

**Comment by wy1456642569** [comment]
> 一群支那猪靠着美国人的网站才有口饭吃，现在贸易战还哪来的逼脸在这里叫嚣爱你妈逼的支那国呢，Chinazi的杂种。看不起香港“废青”，你们tmd连996都被当成福报，连自己的公寓都保不住暴雷，你们口里的”废青“把送中法案打到撤回，谁是”废青“？废青站着声讨，你们大陆支那跪着维权，谁是卢瑟？
> 
> 不是喜欢人肉吗？ 查老子啊？查得出来老子姓你妈逼的姓，老子外籍，你们四等汉抓个屌呢？

fuck  your mother

**Comment by notepadgodie** [comment]
> 除非存在實際問題，否則請離開。存儲庫不是放置政治評論的地方。

你根本就无法理解什么是愤怒

**Comment by CodeAunt** [comment]
> 除非存在實際問題，否則請離開。存儲庫不是放置政治評論的地方。

開源軟體頁不是放置政治主張的地方。

**Comment by Loys** [comment]
> 
> 
> > 一群支那猪靠着美国人的网站才有口饭吃，现在贸易战还哪来的逼脸在这里叫嚣爱你妈逼的支那国呢，Chinazi的杂种。看不起香港“废青”，你们tmd连996都被当成福报，连自己的公寓都保不住暴雷，你们口里的”废青“把送中法案打到撤回，谁是”废青“？废青站着声讨，你们大陆支那跪着维权，谁是卢瑟？
> > 不是喜欢人肉吗？ 查老子啊？查得出来老子姓你妈逼的姓，老子外籍，你们四等汉抓个屌呢？
> 
> fuck your mother

LOL were is China?

**Comment by notepadgodie** [comment]
> > > 一群支那猪靠着美国人的网站才有口饭吃，现在贸易战还哪来的逼脸在这里叫嚣爱你妈逼的支那国呢，Chinazi的杂种。看不起香港“废青”，你们tmd连996都被当成福报，连自己的公寓都保不住暴雷，你们口里的”废青“把送中法案打到撤回，谁是”废青“？废青站着声讨，你们大陆支那跪着维权，谁是卢瑟？
> > > 不是喜欢人肉吗？ 查老子啊？查得出来老子姓你妈逼的姓，老子外籍，你们四等汉抓个屌呢？
> > 
> > 
> > fuck your mother
> 
> LOL were is China?
His angrily is reasonable.

**Comment by BrownFly** [comment]
Joined 41 minutes ago

**Comment by assad2008** [comment]
这货完全是得了狂犬病，八成是个香蕉人，一副汉奸样。狂犬吠日！

**Comment by michaeldai7** [comment]
> > 一群支那猪靠着美国人的网站才有口饭吃，现在贸易战还哪来的逼脸在这里叫嚣爱你妈逼的支那国呢，Chinazi的杂种。看不起香港“废青”，你们tmd连996都被当成福报，连自己的公寓都保不住暴雷，你们口里的”废青“把送中法案打到撤回，谁是”废青“？废青站着声讨，你们大陆支那跪着维权，谁是卢瑟？
> > 不是喜欢人肉吗？ 查老子啊？查得出来老子姓你妈逼的姓，老子外籍，你们四等汉抓个屌呢？
> 
> 大家可怜可怜这个人吧，说不定幼年丧*母，现在悲痛欲绝精神分裂呢。
> 小伙子，亮出你的收款码，我们给你打点钱买棺

你怎么知道你爹就是你亲爹

**Comment by rrttyyu** [comment]
> 
> 
> > 你也就敢这玩了，去舔你美爹吧，没人拦你
> 
> 你看看你身份证后面第一个字念什么？不好意思你是中华人民共和国的居民，仅此而已，你长这么大你有投票权？你只是居住在粪坑里的一条蛆。你有言论自由？你长得那张嘴除了吃饭喊说习近平万岁吗？所以说你们支那猪不是白叫的

支那猪，外籍懂吗？ 傻逼

**Comment by rrttyyu** [comment]
> 
> 
> 缩头乌龟？不敢说话了？自己就个废青还有理？

缩头乌龟？你支那猪连自己的肉价，公寓都保不住，还不敢反抗，说谁缩头乌龟呢？Chinazi

**Comment by rrttyyu** [comment]
> 
> 
> > 一群支那猪靠着美国人的网站才有口饭吃，现在贸易战还哪来的逼脸在这里叫嚣爱你妈逼的支那国呢，Chinazi的杂种。看不起香港“废青”，你们tmd连996都被当成福报，连自己的公寓都保不住暴雷，你们口里的”废青“把送中法案打到撤回，谁是”废青“？废青站着声讨，你们大陆支那跪着维权，谁是卢瑟？
> > 不是喜欢人肉吗？ 查老子啊？查得出来老子姓你妈逼的姓，老子外籍，你们四等汉抓个屌呢？
> 
> fuck your mother

Fuck you all Cina.

**Comment by rrttyyu** [comment]
> 
> 
> > 你也就敢这玩了，去舔你美爹吧，没人拦你
> 
> 你去大街上喊一句习近平万岁，你敢吗？

我在国外，我有压力么？倒是你支杂在国内敢喊吗？

**Comment by woshifengzhao** [comment]
一说到996，python创始人站出来出来支持了，微软员工也站出来出来支持了，你们口中的爱国企业开发的浏览器墙掉了996仓库，你们说了什么呢？做了什么呢？star一下仓库？clone 下仓库？你觉得不公平，你站出来发声了吗？你国没有合法游行，你只是敢微博上发两句闹骚
现在到了新疆问题，np++开发者站出来发声了，粉蛆们颅内高潮了，笑死👴了，双标玩的挺6

**Comment by woshifengzhao** [comment]
> > > 你也就敢这玩了，去舔你美爹吧，没人拦你
> > 
> > 
> > 你看看你身份证后面第一个字念什么？不好意思你是中华人民共和国的居民，仅此而已，你长这么大你有投票权？你只是居住在粪坑里的一条蛆。你有言论自由？你长得那张嘴除了吃饭喊说习近平万岁吗？所以说你们支那猪不是白叫的
> 
> fuck your mother! you go home look?

这位山西的王先生，建议您回炉重造英语

https://github.com/wy1456642569/hello-word

**Comment by zhangzhibogithub** [comment]
被门夹了的核桃还能补脑嘛，可怜的外籍人士，多吃点猪脑补一补，乘早放弃使用中华的文字和语言，你都做了一条狗，用着不合适

**Comment by gaoe6661** [comment]
中华人民共和国万岁！世界人民大团结万岁！
https://github.com/gaoe6661/anti-America-hegemony
