### ISSUE TITLE
对作者表示支持，你们可以不用Notepad++，或者呼吁墙掉Github，

### ISSUE THREAD

**Issue by duozhanggithub** [notepad-plus-plus/notepad-plus-plus#7415]
攻击一个将软件免费给你们用并开源代码给你们的人，你们也好意思?
996的命，操中南海的心

**Comment by dxp8964** [comment]
[![](https://user-images.githubusercontent.com/56756710/67853580-d36f9380-fb49-11e9-97e2-a4fa507f4375.png)同志们加油，听取习近平同志重要讲话，有组织的战斗！](https://www.youtube.com/watch?v=FhXdLIBVCMQ)

**Comment by duozhanggithub** [comment]
> 说话是要负责任的，放屁是要有限度的，不是什么人我们都会感激。

那么Github要不要负责任啊，请从自身做起，抵制Github，并呼吁墙掉Github

**Comment by chengfangpeng** [comment]
因为他声援的那些人，09年七五事件中杀害了几百条无辜的生命。按你这逻辑，我也可以支持911那些基地组织的人。

**Comment by KalChn** [comment]
不好意思，谁用了？

**Comment by duozhanggithub** [comment]
> 对于这种问题，github应主动屏蔽此软件及作者。

可以呼吁屏蔽Github

**Comment by chengfangpeng** [comment]
> > 对于这种问题，github应主动屏蔽此软件及作者。
> 
> 可以呼吁屏蔽Github

我们不是不能接受批评，但是你批评的有依据，他支持的人在七五事件中少了多少无辜的平民，他们有汉人，有维吾尔人

**Comment by dongyingt** [comment]
> > > 对于这种问题，github应主动屏蔽此软件及作者。
> > 
> > 
> > 可以呼吁屏蔽Github
> 
> 我们不是不能接受批评，但是你批评的有依据，他支持的人在七五事件中杀了多少无辜的平民，他们有汉人，有维吾尔人

说白了就是我们的强大他们害怕了，怕我们找他们算账，捏造任何理由诋毁我们，煽动民族仇恨，其用心之险恶，不言而喻。公道自在人心，正义终将到来。

**Comment by cckuailong** [comment]
1. 这软件这么难用，你说个锤子呢
2. 他开源软件和分裂祖国能放一起看？
3. 跪久了真舒服啊，人家外国可看不起你这舔狗

**Comment by cheetosysst** [comment]
@cckuailong 分裂你的祖國跟指出正在分裂的事實還是有差別的

**Comment by wkz2003** [comment]
我杀你妈收集你全家骨灰还把骨灰扬喽

**Comment by a2902793** [comment]
這麼愛國請用碼雲別來這裡啊、這麼愛國別用台灣人開發的notepad++或是美國人開發的vscode阿，不要愛國是工作、用洋貨是生活啊，真香阿玻璃仔！

**Comment by wkz2003** [comment]
> 這麼愛國請用碼雲別來這裡啊、這麼愛國別用台灣人開發的notepad++或是美國人開發的vscode阿，不要愛國是工作、用洋貨是生活啊，真香阿玻璃仔！

你这么想独立你用你妈的软件我操你妈的。你妈今晚必死，你爸在劫难逃，你奶奶被我用双截棍捅逼。我拿你妈骨灰去放烟花让你看看你妈炸了的美色

**Comment by a2902793** [comment]
> 我想著是你媽骨灰炒飯不夠有營養還是怎麼樣。你媽的灣灣自己邏輯都有問題，你他媽用的就是台灣省自己做的？我讓你媽骨灰回鍋重炒，加點你媽的姨媽血勾芡，增你媽的智商我操你媽。不服繼續對罵不好好利用你媽骨灰我就不舒服

我看大概是文革抄掉了太多知識分子，只留下那些像你爸一樣貪生怕死只好吹黨的老二的賤畜爸媽，然後生下你這個偷用洋貨的漢奸 XD

**Comment by wkz2003** [comment]
> > 我想著是你媽骨灰炒飯不夠有營養還是怎麼樣。你媽的灣灣自己邏輯都有問題，你他媽用的就是台灣省自己做的？我讓你媽骨灰回鍋重炒，加點你媽的姨媽血勾芡，增你媽的智商我操你媽。不服繼續對罵不好好利用你媽骨灰我就不舒服
> 
> 我看大概是文革抄掉了太多知識分子，只留下那些像你爸一樣貪生怕死只好吹黨的老二的賤畜爸媽，然後生下你這個偷用洋貨的漢奸 XD

我破你妈的🐔八，我坦白我当年逼迫你妈和你野爹美国本地品种🐶杂交才生了你。你不感谢一下那条高级品种狗真的是不行。瞎鸡巴去youtube看点历史还鸡巴有优越感。我真他妈想把你塞回你妈逼里再给你妈阴蒂上把🔒

**Comment by a2902793** [comment]
> 我破你媽的🐔八，我坦白我當年逼迫你媽和你野爹美國本地品種🐶雜交才生了你。你不感謝一下那條高級品種狗真的是不行。瞎雞巴去youtube看點歷史還雞巴有優越感。我真他媽想把你塞回你媽逼裡再給你媽陰蒂上把🔒

真慘，黨國交出了一個滿腦子交配的支那狗。原來你也知道youtube是甚麼阿~看來果不其然私下還是會翻牆出來看看外面的美好。全世界也只有你們品種的會巴不得逃出來，然後享受著自由的美好時還不忘稱讚中國的好、共產黨的好。大概是怕被消失吧 XD

**Comment by wkz2003** [comment]
> > 我破你媽的chicken八，我坦白我當年逼迫你媽和你野爹美國本地品種dog雜交才生了你。你不感謝一下那條高級品種狗真的是不行。瞎雞巴去youtube看點歷史還雞巴有優越感。我真他媽想把你塞回你媽逼裡再給你媽陰蒂上把lock
> 
> 不像你只會看黨給你的歷史，然後就來美帝用發明的github亂叫囂，好讓你回去跟黨邀功 XD

我看你🐴的美好世界。赶紧带你🐶爹和你妈仅剩的骨灰以及你野妈蔡英文赶紧跑去你的自由美利坚。你再敢再用中文我直接把你妈骨灰拿去灌到你肛门里面再让你🐶爹表演一个真空吸

**Comment by a2902793** [comment]
> 我看你🐴的美好世界。趕緊帶你🐶爹和你媽僅剩的骨灰以及你野媽蔡英文趕緊跑去你的自由美利堅。你再敢再用中文我直接把你媽骨灰拿去灌到你肛門裡面再讓你🐶爹表演一個真空吸

虧你講說用中文，看看誰還在用正統繁體中文，誰在用那又破又殘的簡體中文啊 XD 被文革的很爽喔？自己用殘體還覺得中文你的，那馬來西亞是不是也你大中國的？這麼愛用github秀一波英文啊，Chinazi XD

**Comment by a2902793** [comment]
> 给爷爬，爷不跟🐶杂种bb

是這樣嗎？還是你只有那麼一點本事😂你也知道用洋貨很香啊～沒辦法中國貨殘破不堪都沒辦法用對吧，看很多網站還要翻牆，真是同情你 🥺 看來黨幹完你媽還得幹你老婆跟女兒，讓你這精神永存於你子子孫孫呢！

**Comment by wkz2003** [comment]
> > 给爷爬，爷不跟dog杂种bb
> 
> 是這樣嗎？還是你只有那麼一點本事你也知道用洋貨很香啊～沒辦法中國貨殘破不堪都沒辦法用對吧，看很多網站還要翻牆，真是同情你 🥺 看來黨幹完你媽還得幹你老婆跟女兒，讓你這精神永存於你子子孫孫呢！

🐶杂种 哪只🐶眼看见爷爷我说外国货好了？你妈的逼最好，顶级货，骨灰也很好吃

**Comment by wkz2003** [comment]
> > dog杂种 哪只dog眼看见爷爷我说外国货好了？你妈的逼最好，顶级货，骨灰也很好吃
> 
> 講到爺爺啊，中共建國剛70週年，我們也剛109年了，誰才是真正的爺爺大家都曉得呢！

你他妈逼的不也在用吗？我寻思你你这种🐶杂种的爱国就是杜绝外国一切东西？你妈死几十回都挽救不了你。狗逼玩意给爷爬越远越好我日你妈了个臭逼东西。我他妈是你爷爷

**Comment by a2902793** [comment]
> 你他媽逼的不也在用嗎？我尋思你你這種🐶雜種的愛國就是杜絕外國一切東西？你媽死幾十回都挽救不了你。狗逼玩意給爺爬越遠越好我日你媽了個臭逼東西。我他媽是你爺爺

我用所以我不會像你一樣覺得別人美國爸爸、日奴甚麼的啊，只有你們舔著習近平的雞巴子還覺得中國最棒不是嗎？瞧你為了新疆就忿忿不平，如此愛國又愛用外國貨...挺矛盾的啊 XD 你是我爺爺？那你早該死了，趕緊爬回你墳裡去！

**Comment by wy193777** [comment]
@a2902793 大哥你可真有耐心啊，陪着骂了几个小时。

**Comment by a2902793** [comment]
> @a2902793大哥你可真有耐心啊，陪著罵了幾個小時。

沒辦法，今年亡國感太重了。

**Comment by excitingduckduckgo** [comment]
支持！

**Comment by oTMaN-chengQ-G** [comment]
对嘛~我不喜欢作者立场,我自己不用就行咯.没必要再把事情升级.

**Comment by yinzixie** [comment]
我就不喜欢咋了？笑死人了。分裂国家的沙雕，还不能说了？

**Comment by lunzima** [comment]
Notepad++作者，你可以给我强奸你女儿么

**Comment by zhenghao991213** [comment]
> > > 你这么想独立你用你妈的软件我操你妈的。你妈今晚必死，你爸在劫难逃，你奶奶被我用双截棍捅逼。我拿你妈骨灰去放烟花让你看看你妈炸了的美色
> > 
> > 
> > 激動甚麼啊玻璃仔，怎麼啦，說到你痛處所以唉唉叫是嘛？我半字偷沒提到獨立啊支支，叫你別用啊~是沒這勇氣抵制嗎？還是因為沒有國產編輯器？看看你們玻璃仔水準啊，講不贏就只好拿別人祖輩出來侮辱，真像你們當初文革會做的事 XD
> 
> 我想着是你妈骨灰炒饭不够有营养还是怎么样。你妈的湾湾自己逻辑都有问题，你他妈用的就是台湾省自己做的？我让你妈骨灰回锅重炒，加点你妈的姨妈血勾芡，增你妈的智商我操你妈。不服继续对骂 不好好利用你妈骨灰我就不舒服

骂的好，这种4V人就是欠。
