### ISSUE TITLE
我和我的祖国，一刻也不能分割.Me and my country can't be separated for a moment

### ISSUE THREAD

**Issue by mchgood** [notepad-plus-plus/notepad-plus-plus#7422]
# 我和我的祖国，一刻也不能分割.
# Me and my country can't be separated for a moment

**Comment by mdesi** [comment]
Me and my country can't be separated for a moment

**Comment by michaeldai7** [comment]
你的祖国在杀人，他们杀完了就该轮到你被杀了

**Comment by dylan-xie** [comment]
> 這麼愛國請用碼雲別來這裡啊，不要愛國是工作、用洋貨是生活啊，真香阿玻璃仔！

不用github的程序员不是好程序员～～在大陆it界也会被歧视的～～

**Comment by dylan-xie** [comment]
最讨厌定性xxx是xxx的劣根性～～ 你看到也只是14亿人里面的个别人里的个别事件（往往你们的媒体也喜欢报道这些，追根究底还是你们乐于看到这些，所以她们报道这些才能挣钱）

**Comment by a2902793** [comment]
> 最討厭定性xxx是xxx的劣根性～～ 你看到也只是14億人裡面的個別人裡的個別事件（往往你們的媒體也喜歡報導這些，追根究底還是你們樂於看到這些，所以她們報導這些才能掙錢）

我可不是看媒體喔~我住在上海兩年過這是我的結論，抱歉。

**Comment by dylan-xie** [comment]
> > 最討厭定性xxx是xxx的劣根性～～ 你看到也只是14億人裡面的個別人裡的個別事件（往往你們的媒體也喜歡報導這些，追根究底還是你們樂於看到這些，所以她們報導這些才能掙錢）
> 
> 我可不是看媒體喔~我住在上海兩年過這是我的結論，抱歉。

你住在上海得出这个结论，那太遗憾了～

**Comment by a2902793** [comment]
> 你住在上海得出這個結論，那太遺憾了～

哈！小的不才，去你們1a大學過過水後得出來的結論，真是遺憾沒錯啊 XD

**Comment by dylan-xie** [comment]
> > HK事件一樣， 你們看到的和我們看到的完全不一樣，你們看到的和能接受的都是她們是fighter，是革命鬥士， 我看到的信息（包括youtube上的一些公開渠道），大多數都是打砸燒，強烈擾亂社會秩序，說實話到現在也沒完全明白他們的訴求～～
> 
> 可不喔，你也可以看看香港人自己錄的畫面、參與香港人的群組看看裡面講什麼。你看得我也有看到啊，我更是看到了很多從高樓往下拍拍到港警換成示威者的衣服、投擲汽油彈的人身上有配警棍、在警局牌子塗鴉的噴完馬上跑進去警局、港警把磚頭運上警車隔天就有「示威者」對警車丟磚頭...
> 
> 這些例子多的事，然而你們看的到嗎？I guess not. 因為這就是黨想要你們做的，透過他們營造的樣子讓你們覺得他們是暴民。

也许是吧，世界太复杂，不过话说回来跟我有啥关心呢～～还是在家安安静静敲代码最舒服

**Comment by a2902793** [comment]
@dylan-xie 坦白說啦，我欣賞你的理性比起跟你同國來的卻滿嘴只有「別人媽媽骨灰經血」、「爸媽美國雜交狗」例如這樣

![Chinazi](https://i.imgur.com/pTf5uWl.png)

但當全世界都有抵制中國的聲浪時、連你自己做作品都還需要註釋「需要用VPN」、「大家低調使用」時、連你也知道你們媒體只會播特定影像給你時，你是否曾考慮自己去查明真相？是否自己去了解看看反對言論的立場？我去中國就是去了解，然而並沒有讓我失望。

**Comment by a2902793** [comment]
> 也許是吧，世界太複雜，不過話說回來跟我有啥關心呢～～還是在家安安靜靜敲代碼最舒服

Indeed 跟你現在可能沒什麼關係，不過等跟你有關係時你也沒有機會可以為你自己發聲了。<b>

------
First they came for the socialists, and I did not speak out—
Because I was not a socialist.

Then they came for the trade unionists, and I did not speak out—
Because I was not a trade unionist.

Then they came for the Jews, and I did not speak out—
Because I was not a Jew.

Then they came for me—and there was no one left to speak for me.

* Martin Niemöller-
------
再說，跟你沒關係不代表像我們這些處於恐慌支中的台灣人跟香港人就不能為自己發聲。在你安安靜靜的在家裡敲鍵盤時，每一天都有港人為他們的自由民主喪命，甚至有15歲少女被姦殺丟棄在海裡。這次notepad++為新疆人發聲也是一樣，我自己就有認識新疆的朋友親口證實了集中營的事，中國人如何凌虐強姦迫害維吾爾族人。然而，你們中國人卻選擇這般洗版，怪不得會被世界討厭。正是所謂「五毛出征、寸草不生」

**Comment by dylan-xie** [comment]
> > HK事件一樣， 你們看到的和我們看到的完全不一樣，你們看到的和能接受的都是她們是fighter，是革命鬥士， 我看到的信息（包括youtube上的一些公開渠道），大多數都是打砸燒，強烈擾亂社會秩序，說實話到現在也沒完全明白他們的訴求～～
> 
> 可不喔，你也可以看看香港人自己錄的畫面、參與香港人的群組看看裡面講什麼。你看得我也有看到啊，我更是看到了很多從高樓往下拍拍到港警換成示威者的衣服、投擲汽油彈的人身上有配警棍、在警局牌子塗鴉的噴完馬上跑進去警局、港警把磚頭運上警車隔天就有「示威者」對警車丟磚頭...
> 
> 這些例子多的事，然而你們看的到嗎？I guess not. 因為這就是黨想要你們做的，透過他們營造的樣子讓你們覺得他們是暴民。

> > 你住在上海得出這個結論，那太遺憾了～
> 
> 哈！小的不才，去你們1a大學過過水後得出來的結論，真是遺憾沒錯啊 XD



> @dylan-xie 坦白說啦，我欣賞你的理性比起跟你同國來的卻滿嘴只有「別人媽媽骨灰經血」、「爸媽美國雜交狗」例如這樣
> 
> ![Chinazi](https://camo.githubusercontent.com/9b470ad382e5b90054ce0eaaa8f260e8752eb42d/68747470733a2f2f692e696d6775722e636f6d2f7054663575576c2e706e67)
> 
> 但當全世界都有抵制中國的聲浪時、連你自己做作品都還需要註釋「需要用VPN」、「大家低調使用」時、連你也知道你們媒體只會播特定影像給你時，你是否曾考慮自己去查明真相？是否自己去了解看看反對言論的立場？我去中國就是去了解，然而並沒有讓我失望。



> > 也許是吧，世界太複雜，不過話說回來跟我有啥關心呢～～還是在家安安靜靜敲代碼最舒服
> 
> Indeed 跟你現在可能沒什麼關係，不過等跟你有關係時你也沒有機會可以為你自己發聲了。
> 
> First they came for the socialists, and I did not speak out—
> Because I was not a socialist.
> 
> Then they came for the trade unionists, and I did not speak out—
> Because I was not a trade unionist.
> 
> Then they came for the Jews, and I did not speak out—
> Because I was not a Jew.
> 
> Then they came for me—and there was no one left to speak for me.
> 
> * Martin Niemöller-
> 
> 再說，跟你沒關係不代表像我們這些處於恐慌支中的台灣人跟香港人就不能為自己發聲。在你安安靜靜的在家裡敲鍵盤時，每一天都有港人為他們的自由民主喪命，甚至有15歲少女被姦殺丟棄在海裡。這次notepad++為新疆人發聲也是一樣，我自己就有認識新疆的朋友親口證實了集中營的事，中國人如何凌虐強姦迫害維吾爾族人。然而，你們中國人卻選擇這般洗版，怪不得會被世界討厭。正是所謂「五毛出征、寸草不生」

其一、咱们看到的新闻不一样哈， 以我对共产党的理解，他们是不可能搞你们所谓“集中营”的事的，他们对舆论的敏感性比你想象中高多了，这么大规模的再教育，出一点问题都有可能被无限放大，何况是你口中所谓的“集中营”，而且我也有不少新疆的朋友和同学
其二、你获得的媒体和信息里强调的“奸"杀有点过分了，杀可能会在政治行动中出现， “奸”只跟执行者品行有关系，赖不在共党手上
其三、部分中国人喜欢洗版，这我很能理解，每个国家都有些喜欢跟风，没素质，没太多独立思考的人，中国人口基数大，自然多点。  每个国家的民众都容易被煽动，包括所谓的自由民主国家，信息都是能被操控的。
其四、大陆政治部分的言论自由确实缺失，每个知道墙的人都反对墙，反对各类信息审查（包括我自己搞了个社区生活app，各种敏感信息屏蔽烦不胜烦），这确实是大陆的问题。 but反过来说，中国容易被煽动的人太多，外部信息大量涌进来，确实容易出乱子。
现在的社会是信息社会，也是fake信息社会

**Comment by a2902793** [comment]
@dylan-xie 倘若今天不是因為中共，香港也不會出來示威。若不是怕被莫須有的罪名就能移送中國，誰會放棄繁榮的經濟跟生活走上街頭挨子彈？怎樣都跟中共有關係，只是你們覺得沒有而已。為甚麼我覺得姦會有關係呢？因為受中聯辦影響的香港，現在給予黑警無限大的職權，即便人被強姦了也沒辦法再以過去的法律去告警察，因為在中共的洗鬧下他們是暴民，他們被殺被姦應該的。只有中共統治的香港，發生了這麼多性暴力、強姦棄屍之下，卻沒有任何警察受到法律制裁。林鄭的政府，就是中共的。

**Comment by someja** [comment]
思想已经严重不同了！

**Comment by someja** [comment]
> @dylan-xie 倘若今天不是因為中共，香港也不會出來示威。若不是怕被莫須有的罪名就能移送中國，誰會放棄繁榮的經濟跟生活走上街頭挨子彈？怎樣都跟中共有關係，只是你們覺得沒有而已。為甚麼我覺得姦會有關係呢？因為受中聯辦影響的香港，現在給予黑警無限大的職權，即便人被強姦了也沒辦法再以過去的法律去告警察，因為在中共的洗鬧下他們是暴民，他們被殺被姦應該的。只有中共統治的香港，發生了這麼多性暴力、強姦棄屍之下，卻沒有任何警察受到法律制裁。林鄭的政府，就是中共的。

你怎么知道强奸不是有人借此机会故意给中共抹黑的呢

**Comment by someja** [comment]
> > 其一、咱們看到的新聞不一樣哈，以我對共產黨的理解，他們是不可能搞你們所謂“集中營”的事的，他們對輿論的敏感性比你想像中高多了，這麼大規模的再教育，出一點問題都有可能被無限放大，何況是你口中所謂的“集中營”，而且我也有不少新疆的朋友和同學
> > 其二、你獲得的媒體和信息裡強調的“姦"殺有點過分了，殺可能會在政治行動中出現， “姦”只跟執行者品行有關係，賴不在共黨手上
> > 其三、部分中國人喜歡洗版，這我很能理解，每個國家都有些喜歡跟風，沒素質，沒太多獨立思考的人，中國人口基數大，自然多點。每個國家的民眾都容易被煽動，包括所謂的自由民主國家，信息都是能被操控的。
> > 其四、大陸政治部分的言論自由確實缺失，每個知道牆的人都反對牆，反對各類信息審查（包括我自己搞了個社區生活app，各種敏感信息屏蔽煩不勝煩），這確實是大陸的問題。but反過來說，中國容易被煽動的人太多，外部信息大量湧進來，確實容易出亂子。
> > 現在的社會是信息社會，也是fake信息社會
> 
> 好吧，既然你查不到消息我就幫你吧。首先，新疆如果沒有集中營也不會有新疆人到處求助，部論是來台灣求助或是去美國求助，tbh胡亂講被再教育對他們也沒好處。光是release notes裡面就有提到，如果你想了解更多的話你可以參考：https://chinese.uhrp.org/
> 隨便找兩個你可以去看看的線索 (我是不太想貼新聞報導因為你也可以說那是假的)：
> 
> * [空拍新疆區域大型建築大量興建](https://pgw.udn.com.tw/gw/photo.php?u=https://uc.udn.com.tw/photo/2019/09/23/99/6855799.jpg)
>   或是自己google "uyghur concentration camp satellite"
> * [押送新疆人前往再教育營](https://www.youtube.com/watch?v=gGYoeJ5U7cQ)
>   坦白說啦，與其相信你說外面的世界fake news，不如想想中共對於資訊封閉、捏造是不是聞名全世界，是不是你的資訊有可能不足？我光簡單講啦，你現在去一趟新疆，多的是你不能進去的然後入口有武警甚至有道路是直接封閉不能駛入的。
> 
> 姦殺不是我捏造的啊，香港少女陳彥霖可是「全裸」的浮屍啊 (你們當然可以說沒有因為在可以驗屍之前港警就火速火化了)！多名港中大女學生出面指控強暴啊！香港已經有很多浮屍了，新疆也有很多人在集中營被虐死了...香港因為反送中、因為中聯辦、因為福建派來的黑社會，新疆亦是被中國再教育...與共產黨無關？你是不是太天真了？當全世界都抵制communism時，只有你們還認為這些都不是真的，這些都不是共產黨做出來的只是政治的言語而已？
> 
> 人多不表示可以言論控制啊...那剩下的世界怎麼辦？美國、俄羅斯、印度的人怎麼沒有因為自由言論就出亂子了？唯有思想控制，才能讓你們安於共產黨的統治啊哥們。

非洲还言论自由呢。永远没有最完美的答案，只有最适合的方法。
