### ISSUE TITLE
The README file should briefly mention that v7.8.1 is the Free Uyghur edition

### ISSUE THREAD

**Issue by AustinConlon** [notepad-plus-plus/notepad-plus-plus#7423]
Why not put it front and center?

**Comment by Willt125** [comment]
Love the thought, but please no politics in the repo

**Comment by AustinConlon** [comment]
The political statement was made loud and clear in the [v.7.8.1. announcement](https://notepad-plus-plus.org/news/v781-free-uyghur-edition/) though, so why not?

**Comment by MattWindsor91** [comment]
> Love the thought, but please no politics in the repo

The repo already has at least [one (fairly hidden) reference](https://github.com/notepad-plus-plus/notepad-plus-plus/commit/3ee5615c5f3d584c97a33cd649d17894747c58b0#diff-4746d666f80a6d419243fb42318e30c4R1016) to it already.

**Comment by a2902793** [comment]
> Love the thought, but please no politics in the repo

As the author mentioned, "Don’t mix politics with software? You might not. But when Chinese governmen succeeds to impose their politics on software domain, it will be too late to stop it."

You might not know what the prc is doing to the world, but we do. We constantly live in horror and is constantly threatened with thousands of missiles aiming at us. Our daily lives have been infiltrated by the prc including softwares, so my friend, there shall be no politics when china stops trying to infiltrate every part of the world.

**Comment by msrn1975** [comment]
> Love the thought, but please no politics in the repo

First they came for the socialists, and I did not speak out—
     Because I was not a socialist.

Then they came for the trade unionists, and I did not speak out—
     Because I was not a trade unionist.

Then they came for the Jews, and I did not speak out—
     Because I was not a Jew.

Then they came for me—and there was no one left to speak for me.
- Martin Niemöller-

**Comment by anselme16** [comment]
"No politics" Is a pro-status quo political opinion.

There is no such thing as no politics.

Also it's not new that notepad++ has references to political issues, last yeah there was a yellow vest version, remember ?
