### ISSUE TITLE
Please stay out of politics

### ISSUE THREAD

**Issue by StewAlexanderACC** [notepad-plus-plus/notepad-plus-plus#7426]
@donho  please, stay out of politics

Stick with keeping this app great, thanks

**Comment by dartraiden** [comment]
> People will tell me again to not mix politics with software/business

https://notepad-plus-plus.org/news/v781-free-uyghur-edition/

**Comment by petrroll** [comment]
"Bad men need nothing more to compass heir ends, than that good men should look on and do nothing."

**Comment by notepadgodie** [comment]
> @donho please, stay out of politics
> 
> Stick with keeping this app great, thanks

Go see 2nd first, then try to understand why Chinese people are so angry pls.

**Comment by StewAlexanderACC** [comment]
I understand the situation, and there is truth to the phrase that "evil exists because good men do nothing", but I also know it's almost  a fools errand to try and change people's beliefs.

Usually it take something very dramatic to do so...

So many people don't care about the righteousness of a belief, they see things a specific way, a "zeitgeist", and that perception drives their mentality. 

This is what I mean, its not that I don't care, just code is so much easier to make great than people. 😄 

Please don't read me wrong, thank you

**Comment by StewAlexanderACC** [comment]
I mean the **fact** that the earth is dying, 

- Soil will be depleted soon
- Fresh water will be gone soon
- Oil will be gone soon
- Bees will be gone soon

These facts are argued as if they are beliefs, we argue over dust mots, while everything crumbles.

So yes, I understand the situation, but sticking to making something great, is to - my opinion with which you are welcome to disagree.

**Comment by petrroll** [comment]
Sure, I don't think anyone here things notepad++'s statement will single-handedly change China's policy. That's obviously not gonna happen.

But exposing atrocities and making them publicly known fact can - step by step - make them less tenable in the long run. A million paper cuts kind of situation.

And as @yousefamar is saying, the fact that there're more pressing issues doesn't mean this one isn't worth raising awareness about.

**Comment by Korb** [comment]
This is a duplicate of #6288 (disrespect for other members of the FOSS community by posting political propaganda spam in text editor resources).
