### ISSUE TITLE
Disable Clickable Link Setting does NOT disable links in current document.

### ISSUE THREAD

**Issue by drankinatty** [notepad-plus-plus/notepad-plus-plus#743]
There are several bugs in **Settings->Preferences->Clickable Link Settings** seen in `npp.6.8.1` on Win7. Specifically, the default in the current version is:

```
Clickable Link Settings

[x] Enable
[ ] No underline
```

Issue 1: **disabling (removing selection) does not disable links** in the current document.

Issue 2: **disabling leaves links underlined with no way to turn off**. The `No underline` option needs to remain active (or default to off) when not enabled. Currently, the only way I found to get rid of the underline was to re-`Enable`, then choose `No underline` and then finally disable.

I don't know if it may not be smarter to have this option disabled. Note issue `#723` discussing that having this enabled considerably slows npp down on large documents. It may make more sense to disable this option by default.

Finally, good job on npp. However, be vigilant to keep npp a fast/clean/editor -- period. A programming editor should not be a partial rendering engine or bookmark substitute. It should have solid editing, indention, syntax highlighting (and if you want to provide additional tools like a console window (I guess it's a command prompt on windows), make/cmake interface, and projects that preserve a collection of files, that's great). But many a project have suffered significantly by trying to be too many things to too many people. npp is a great project and will continue to be as long as it sticks to being a programming editor. Let everything else be implemented as a plugin, so the editor itself isn't burdened with _fluff_ that takes away from its appeal or performance.

The easy way to never go astray is simply to remember "The latest greatest new feature to some is a bug to another -- if it cannot be turned off." Keep up the good work.

**Comment by Rikk** [comment]
You can workaround this problem just by changing from one tab to other, it will then clear the underline and link.

**Comment by Rikk** [comment]
What I'm seeing is that whoever invented this function, created only the `addHotSpot()` function, but forgot to create a reverse `removeHotSpot()`.
Anyway, it should be removed when changing tabs.

**Comment by drankinatty** [comment]
Thanks Rikk, that workaround will work for now. It sounds like somebody wanted a Clickable Link plugin, but happened to slip it in the editor by mistake ;-). I haven't looked at the code as I have no MinGW install and have played with the cross-compile libraries. It's not a bad feature, but definitely one that should have a sensible implementation. Thanks for letting me know about the workaround. Hopefully it's implementation can get a bit of TLC in the near future or be stripped and moved to a plugin.

**Comment by MetaChuh** [comment]
we are closing this issue due to its age and multiple newer notepad++ versions since it was filed.

please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html).
if your issue persists, and it is still of relevance to you, please feel free to file a new issue.

thank you for your help and best regards.

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
```
[<kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd>](https://notepad-plus-plus.org/community/)

**Comment by drankinatty** [comment]
Closing is fine, but it was not closed before as no Fix was ever posted. All that was posted was a workaround.
