### ISSUE TITLE
China's sovereignty and territorial integrity must not be infringed.

### ISSUE THREAD

**Issue by Joseph-zheng** [notepad-plus-plus/notepad-plus-plus#7430]
### Steps to Reproduce the Issue

1. 
2. 
3.

**Comment by stefan-schweiger** [comment]
Murder is still murder

**Comment by veryunderstated** [comment]
Taiwan, Tibet, and Hong Kong should be free of the disgusting oppressive regime of the Chinese government. China is a shitty place and they shouldn't be allowed to destroy other countries too. Fuck the evil Chinese government. Fucking Winnie the Pooh

**Comment by lazycrypt** [comment]
@veryunderstated They might be demanding that sovereignity of the Republic of China be respected and that the Chinese Communist Party stops their illegitimate occupation of the Chinese territories? 🤔
