### ISSUE TITLE
台独分子你妈妈买菜必涨价，你爸爸坐公交必刚好赶不上，你爷爷公园下棋必被人指指点点，你奶奶跳广场舞必站不到C位

### ISSUE THREAD

**Issue by Constantine3** [notepad-plus-plus/notepad-plus-plus#7433]
### Steps to Reproduce the Issue

1. 
2. 
3.

**Comment by Noiwex** [comment]
动态网自由门 天安門 天安门 法輪功 李洪志 Free Tibet 六四天安門事件 The Tiananmen Square protests of 1989 天安門大屠殺 The Tiananmen Square Massacre 反右派鬥爭 The Anti-Rightist Struggle 大躍進政策 The Great Leap Forward 文化大革命 The Great Proletarian Cultural Revolution 人權 Human Rights 民運 Democratization 自由 Freedom 獨立 Independence 多黨制 Multi-party system 台灣 臺灣 Taiwan Formosa 中華民國 Republic of China 西藏 土伯特 唐古特 Tibet 達賴喇嘛 Dalai Lama 法輪功 Falun Dafa 新疆維吾爾自治區 The Xinjiang Uyghur Autonomous Region 諾貝爾和平獎 Nobel Peace Prize 劉暁波 Liu Xiaobo 民主 言論 思想 反共 反革命 抗議 運動 騷亂 暴亂 騷擾 擾亂 抗暴 平反 維權 示威游行 李洪志 法輪大法 大法弟子 強制斷種 強制堕胎 民族淨化 人體實驗 肅清 胡耀邦 趙紫陽 魏京生 王丹 還政於民 和平演變 激流中國 北京之春 大紀元時報 九評論共産黨 獨裁 專制 壓制 統一 監視 鎮壓 迫害 侵略 掠奪 破壞 拷問 屠殺 活摘器官 誘拐 買賣人口 遊進 走私 毒品 賣淫 春畫 賭博 六合彩 天安門 天安门 法輪功 李洪志 Winnie the Pooh 劉曉波动态网自由门

**Comment by SgtPoopTicklerSr** [comment]
![un I 999f9cknown](https://user-images.githubusercontent.com/48660003/67878731-33e2de80-fb12-11e9-88b8-a603eba3dd64.png)

**Comment by a2902793** [comment]
> 我操你媽SB

玻璃仔，只剩髒話能講了嗎？真是讓大家見識中國人的水準啊！

**Comment by michaeldai7** [comment]
![IMG_20191019_032243](https://user-images.githubusercontent.com/43862422/67894031-220f3480-fb2e-11e9-8097-627448ccded8.jpg)
![IMG_20191019_032249](https://user-images.githubusercontent.com/43862422/67894032-22a7cb00-fb2e-11e9-8691-12ff352e0649.jpg)

**Comment by joseph1106** [comment]
![Uploading E5gOUM3UUAkORzC.jpg…]()

**Comment by joseph1106** [comment]
![Uploading E5Mi3zyVcAAqSLr.jpg…]()
