### ISSUE TITLE
任何试图分裂中国的企图都是痴心妄想

### ISSUE THREAD

**Issue by wjq990112** [notepad-plus-plus/notepad-plus-plus#7440]
### Steps to Reproduce the Issue

1. 
2. 
3.

**Comment by Adorable-Catgirl** [comment]
FREE HONG KONG

**Comment by aiguozeiguncu** [comment]
光复香港，时代革命

**Comment by wjq990112** [comment]
> 光复香港，时代革命

回去问一下你妈是怎么把你生出来的狗杂种，香港独立？你们在想屁吃呢？独立了你还能在GitHub哔哔？建议狗杂种回去复习一下历史，建议狗杂种去看看美国所谓的民主自由，像你们这样的狗杂种，早就被一枪崩了。光复香港还用什么中文？你们不配！

**Comment by wjq990112** [comment]
> FREE HONG KONG

回去问一下你妈是怎么把你生出来的狗杂种，香港独立？你们在想屁吃呢？独立了你还能在GitHub哔哔？建议狗杂种回去复习一下历史，建议狗杂种去看看美国所谓的民主自由，像你们这样的狗杂种，早就被一枪崩了。

**Comment by proteriax** [comment]
@wjq990112 Where were you when the Russians could take your northern territories for free and split Mongolia? Where were you when your government falsified the lie that the Hong Kong protests have anything to do with independence?

**Comment by wjq990112** [comment]
> @wjq990112 Where were you when the Russians could take your northern territories for free and split Mongolia? Where were you when your government falsified the lie that the Hong Kong protests have anything to do with independence?

I'm in you mother fucking bed, understand?

**Comment by proteriax** [comment]
@wjq990112 what is that even supposed to mean? and who wants to be in the same country with uncivilized people like you?

**Comment by aiguozeiguncu** [comment]
@wjq990112 关你屁事呀，你去过香港吗你有证件吗你有签注吗哈哈哈哈

**Comment by kittenswolf** [comment]
The 1989 Tiananmen Square protests, commonly known in mainland China as the June Fourth Incident (Chinese: 六四事件, liùsì shìjiàn), were student-led demonstrations in Beijing (the capital of the People's Republic of China) for the establishment of basic human and press rights and against the Communist-led Chinese government in mid-1989. More broadly, it refers to the popular national movement inspired by the Beijing protests during that period, sometimes called the '89 Democracy Movement (Chinese: 八九民运, bājiǔ mínyùn). The protests were forcibly suppressed after Chinese Premier Li Pengdeclared martial law. In what became known as the Tiananmen Square Massacre, troops with assault rifles and tanks fired at the demonstrators trying to block the military's advance towards Tiananmen Square. The number of civilian deaths was internally estimated by the Chinese government to be near or above 10,000.

![image](https://user-images.githubusercontent.com/26834699/67863618-8927eb80-fb24-11e9-8fa1-35ad32287613.jpg)

**Comment by michaeldai7** [comment]
![Xinjiang_Re-education_Camp_Lop_County](https://user-images.githubusercontent.com/43862422/67864321-d2b01080-fafb-11e9-92e4-e1db9c143927.jpg)

**Comment by chinadogchinadog** [comment]
台灣獨立不容侵犯

**Comment by michaeldai7** [comment]
![IMG_20191019_032243](https://user-images.githubusercontent.com/43862422/67891967-0e61cf00-fb2a-11e9-9c16-5fb0fc231961.jpg)
![IMG_20191019_032249](https://user-images.githubusercontent.com/43862422/67891968-0efa6580-fb2a-11e9-949c-aa5a3be4ce20.jpg)

**Comment by zhangxuewu666** [comment]
> FREE HONG KONG

杀你全家
