### ISSUE TITLE
请不要在Notepad++乱洗板影响其他正常用户的issue发布。

### ISSUE THREAD

**Issue by FlyEmojiStudiooo** [notepad-plus-plus/notepad-plus-plus#7449]
各位来自中华人民共和国的Github用户们你们好。
首先，请你们查看Github用户准则后再来进行issue提交。
不要做任何的无脑洗板/刷屏行为。
你们这样的行为并不会让他人受到影响。反而会二度恶化您国的印象。停止xxs行为。谢谢茄子。
https://github.com/notepad-plus-plus/notepad-plus-plus/issues/7462 有关本内容的相关issues Page。
btw don't delete this issue cus I want Chinese know don't say shit to break the GitHub rules.
(Hope Microsoft and GitHub will fix this "problem")

**Comment by mxhyeon** [comment]
你妈被强奸了你就眼睁睁看着吗？

**Comment by mxhyeon** [comment]
你国？？你是哪国人？

**Comment by kittenswolf** [comment]
@mxhyeon 

动态网自由门 天安門 天安门 法輪功 李洪志 Free Tibet 六四天安門事件 The Tiananmen Square protests of 1989 天安門大屠殺 The Tiananmen Square Massacre 反右派鬥爭 The Anti-Rightist Struggle 大躍進政策 The Great Leap Forward 文化大革命 The Great Proletarian Cultural Revolution 人權 Human Rights 民運 Democratization 自由 Freedom 獨立 Independence 多黨制 Multi-party system 台灣 臺灣 Taiwan Formosa 中華民國 Republic of China 西藏 土伯特 唐古特 Tibet 達賴喇嘛 Dalai Lama 法輪功 Falun Dafa 新疆維吾爾自治區 The Xinjiang Uyghur Autonomous Region 諾貝爾和平獎 Nobel Peace Prize 劉暁波 Liu Xiaobo 民主 言論 思想 反共 反革命 抗議 運動 騷亂 暴亂 騷擾 擾亂 抗暴 平反 維權 示威游行 李洪志 法輪大法 大法弟子 強制斷種 強制堕胎 民族淨化 人體實驗 肅清 胡耀邦 趙紫陽 魏京生 王丹 還政於民 和平演變 激流中國 北京之春 大紀元時報 九評論共産黨 獨裁 專制 壓制 統一 監視 鎮壓 迫害 侵略 掠奪 破壞 拷問 屠殺 活摘器官 誘拐 買賣人口 遊進 走私 毒品 賣淫 春畫 賭博 六合彩 天安門 天安门 法輪功 李洪志 Winnie the Pooh 劉曉波动态网自由门

**Comment by MyAngelXiaoYing** [comment]
@mxhyeon 

动态网自由门 天安門 天安门 法輪功 李洪志 Free Tibet 六四天安門事件 The Tiananmen Square protests of 1989 天安門大屠殺 The Tiananmen Square Massacre 反右派鬥爭 The Anti-Rightist Struggle 大躍進政策 The Great Leap Forward 文化大革命 The Great Proletarian Cultural Revolution 人權 Human Rights 民運 Democratization 自由 Freedom 獨立 Independence 多黨制 Multi-party system 台灣 臺灣 Taiwan Formosa 中華民國 Republic of China 西藏 土伯特 唐古特 Tibet 達賴喇嘛 Dalai Lama 法輪功 Falun Dafa 新疆維吾爾自治區 The Xinjiang Uyghur Autonomous Region 諾貝爾和平獎 Nobel Peace Prize 劉暁波 Liu Xiaobo 民主 言論 思想 反共 反革命 抗議 運動 騷亂 暴亂 騷擾 擾亂 抗暴 平反 維權 示威游行 李洪志 法輪大法 大法弟子 強制斷種 強制堕胎 民族淨化 人體實驗 肅清 胡耀邦 趙紫陽 魏京生 王丹 還政於民 和平演變 激流中國 北京之春 大紀元時報 九評論共産黨 獨裁 專制 壓制 統一 監視 鎮壓 迫害 侵略 掠奪 破壞 拷問 屠殺 活摘器官 誘拐 買賣人口 遊進 走私 毒品 賣淫 春畫 賭博 六合彩 天安門 天安门 法輪功 李洪志 Winnie the Pooh 劉曉波动态网自由门

**Comment by FlyEmojiStudiooo** [comment]
@Himself65
Nah,they r not trolls 
They just don't know HOW TO be a "human"
(And writing email to GitHub official)

**Comment by mxhyeon** [comment]
@FlyEmojiStudiooo 既然你不承认中国，为什么还要使用中文？你妈被强奸才会生下你这么个废物

**Comment by KalChn** [comment]
不知道是谁的小号洗版哦，屁股歪的眼睛也是瞎的

**Comment by FlyEmojiStudiooo** [comment]
@mxhyeon 我看您在无中生有呢。我哪里否定了中华人民共和国。请在我发出的issue内找出我否定了中华人民共和国的内容。否则您就是在气急败坏。

**Comment by FlyEmojiStudiooo** [comment]
@KalChn Github和Notepad++官方真的应该做点什么让这群无脑洗板玻璃心人gck

**Comment by Albirew** [comment]
most people don't understand runes and will see all these "issues" only as "*more chinese spam, fuck that shit*", effectively making more people against you than doing any good. Well, if that was your aim, then you're doing it right tho...

**Comment by Orlys** [comment]
@FlyEmojiStudiooo 兄弟，省省打字的力氣，別勸了，大家都知道那根本沒用。

**Comment by FlyEmojiStudiooo** [comment]
@Orlys 假如你不做点什么，Github的Rules何成体统？且我写的内容只要有脑子就能看懂。就得看他们有没有这个脑子了。

**Comment by FlyEmojiStudiooo** [comment]
@unixzii 感谢，您说出了我一直在构思的内容。（

**Comment by TaiWanDOG** [comment]
> 你妈被强奸了你就眼睁睁看着吗？

你妈妈被日本人操了

**Comment by FlyEmojiStudiooo** [comment]
> most people don't understand runes and will see all these "issues" only as "_more chinese spam, fuck that shit_", effectively making more people against you than doing any good. Well, if that was your aim, then you're doing it right tho...

Yea, I want Chinese keep the rules.
So I'm sened this issue (sry about my bad eng)

**Comment by FlyEmojiStudiooo** [comment]
> > 你妈被强奸了你就眼睁睁看着吗？
> 
> 你妈妈被日本人操了

过于xxs无脑，请先看完我发的issue再讨论本内容

**Comment by FlyEmojiStudiooo** [comment]
> > > 这个双标可以啊，github应封禁此开源软件，及作者主页，故意扰乱github秩序，严重影响用户体验，我们对此类作者做法感到悲哀，我们相信github是正义的。
> > 
> > 
> > 首先，您应该没有了解我说的意思。
> > 且二，您不应该在Github上发布过于政治内容。
> > 且三，在外网逼逼赖赖的时候，多去搜索，不要无脑狂吠（毕竟您都上得了Github，为什么不去谷歌一下呢？）
> 
> 此作者不应该在Github上发布过于政治内容的应用更新，其外链中存在不可容忍的内容，github应该处理一下。

同意此内容。但是否移除。选择权在开发者和各用户手里。

**Comment by michaellee8** [comment]
@dongyint 人家是軟件的作者，發布什麼有他的自由，沒聽過言論自由嗎（牆國沒有的）

As the author of the software, he has the freedom to publish whatever he want, an example of freedom of speech which the wall country don't have.

**Comment by dongyingt** [comment]
> @dongyint 人家是軟件的作者，發布什麼有他的自由，沒聽過言論自由嗎（牆國沒有的）
> 
> As the author of the software, he has the freedom to publish whatever he want, an example of freedom of speech which the wall country don't have.

听过言论自由，我们说的话也是言论自由，所以，别说废话。

**Comment by michaellee8** [comment]
@kmayyg LOL what did these guys done in golang repo, can u give me a link xd, wanna look at it for some fun

**Comment by dylan-xie** [comment]
> > > 这个双标可以啊，github应封禁此开源软件，及作者主页，故意扰乱github秩序，严重影响用户体验，我们对此类作者做法感到悲哀，我们相信github是正义的。
> > 
> > 
> > 首先，您应该没有了解我说的意思。
> > 且二，您不应该在Github上发布过于政治内容。
> > 且三，在外网逼逼赖赖的时候，多去搜索，不要无脑狂吠（毕竟您都上得了Github，为什么不去谷歌一下呢？）
> 
> 此作者不应该在Github上发布过于政治内容的应用更新，其外链中存在不可容忍的内容，github应该处理一下。

同意加10086

**Comment by someja** [comment]
are u chinese or korea, @FlyEmojiStudiooo

**Comment by C4o** [comment]
我寻思着您他妈也是网络喷子啊 本来以为是个爱学习的开发者 看你主页 star7个项目 超过一半是ss和博客主题 刚学会翻墙和搭个博客就觉得世界是你的了？

**Comment by FlyEmojiStudiooo** [comment]
> 我寻思着您他妈也是网络喷子啊 本来以为是个爱学习的开发者 看你主页 star7个项目 超过一半是ss和博客主题 刚学会翻墙和搭个博客就觉得世界是你的了？

是么，那我寻思着您也差不多啊 张口就是喷子喷子
我寻思着您的本质也差不多么 m8?
非要找这个issue来喷我 您是怎么了 就觉得国家利益比自身利益高呗 非要让那些人“成功维权呗”
是的，我可能并不是一个开发者。
可是我思路可是比您好的多呢。
也并不会像您这样随便找issue进来bbll的呢。

**Comment by C4o** [comment]
> > 我寻思着您他妈也是网络喷子啊 本来以为是个爱学习的开发者 看你主页 star7个项目 超过一半是ss和博客主题 刚学会翻墙和搭个博客就觉得世界是你的了？
> 
> 是么，那我寻思着您也差不多啊 张口就是喷子喷子
> 我寻思着您的本质也差不多么 m8?
> 非要找这个issue来喷我 您是怎么了 就觉得国家利益比自身利益高呗 非要让那些人“成功维权呗”
> 是的，我可能并不是一个开发者。
> 可是我思路可是比您好的多呢。
> 也并不会像您这样随便找issue进来bbll的呢。

没人反驳就真当自己想的都对的？issue里喷子多了，就你他妈装逼，又github用户规则，又影响正常用户提issue，合着您是提了正常的issue才来打抱不平，还是来开个issue刷存在感？多学点东西，少他妈装逼，既然翻了墙就多看点代码。

**Comment by FlyEmojiStudiooo** [comment]
> > > 我寻思着您他妈也是网络喷子啊 本来以为是个爱学习的开发者 看你主页 star7个项目 超过一半是ss和博客主题 刚学会翻墙和搭个博客就觉得世界是你的了？
> > 
> > 
> > 是么，那我寻思着您也差不多啊 张口就是喷子喷子
> > 我寻思着您的本质也差不多么 m8?
> > 非要找这个issue来喷我 您是怎么了 就觉得国家利益比自身利益高呗 非要让那些人“成功维权呗”
> > 是的，我可能并不是一个开发者。
> > 可是我思路可是比您好的多呢。
> > 也并不会像您这样随便找issue进来bbll的呢。
> 
> 没人反驳就真当自己想的都对的？issue里喷子多了，就你他妈装逼，又github用户规则，又影响正常用户提issue，合着您是提了正常的issue才来打抱不平，还是来开个issue刷存在感？多学点东西，少他妈装逼，既然翻了墙就多看点代码。

lmao
为什么我感觉您在无脑狂怒啊。

**Comment by FlyEmojiStudiooo** [comment]
> > > 我寻思着您他妈也是网络喷子啊 本来以为是个爱学习的开发者 看你主页 star7个项目 超过一半是ss和博客主题 刚学会翻墙和搭个博客就觉得世界是你的了？
> > 
> > 
> > 是么，那我寻思着您也差不多啊 张口就是喷子喷子
> > 我寻思着您的本质也差不多么 m8?
> > 非要找这个issue来喷我 您是怎么了 就觉得国家利益比自身利益高呗 非要让那些人“成功维权呗”
> > 是的，我可能并不是一个开发者。
> > 可是我思路可是比您好的多呢。
> > 也并不会像您这样随便找issue进来bbll的呢。
> 
> 没人反驳就真当自己想的都对的？issue里喷子多了，就你他妈装逼，又github用户规则，又影响正常用户提issue，合着您是提了正常的issue才来打抱不平，还是来开个issue刷存在感？多学点东西，少他妈装逼，既然翻了墙就多看点代码。

是。我不是Developer。
但起码有脑子。
不是那种无脑狂喷的人。
好么。

**Comment by C4o** [comment]
> > > > 我寻思着您他妈也是网络喷子啊 本来以为是个爱学习的开发者 看你主页 star7个项目 超过一半是ss和博客主题 刚学会翻墙和搭个博客就觉得世界是你的了？
> > > 
> > > 
> > > 是么，那我寻思着您也差不多啊 张口就是喷子喷子
> > > 我寻思着您的本质也差不多么 m8?
> > > 非要找这个issue来喷我 您是怎么了 就觉得国家利益比自身利益高呗 非要让那些人“成功维权呗”
> > > 是的，我可能并不是一个开发者。
> > > 可是我思路可是比您好的多呢。
> > > 也并不会像您这样随便找issue进来bbll的呢。
> > 
> > 
> > 没人反驳就真当自己想的都对的？issue里喷子多了，就你他妈装逼，又github用户规则，又影响正常用户提issue，合着您是提了正常的issue才来打抱不平，还是来开个issue刷存在感？多学点东西，少他妈装逼，既然翻了墙就多看点代码。
> 
> 是。我不是Developer。
> 但起码有脑子。
> 不是那种无脑狂喷的人。
> 好么。

别拽你仅有的词汇了，真他妈搞笑。别说废话了，就事论事，懂？

**Comment by michaellee8** [comment]
> > > > > 我寻思着您他妈也是网络喷子啊 本来以为是个爱学习的开发者 看你主页 star7个项目 超过一半是ss和博客主题 刚学会翻墙和搭个博客就觉得世界是你的了？
> > > > 
> > > > 
> > > > 是么，那我寻思着您也差不多啊 张口就是喷子喷子
> > > > 我寻思着您的本质也差不多么 m8?
> > > > 非要找这个issue来喷我 您是怎么了 就觉得国家利益比自身利益高呗 非要让那些人“成功维权呗”
> > > > 是的，我可能并不是一个开发者。
> > > > 可是我思路可是比您好的多呢。
> > > > 也并不会像您这样随便找issue进来bbll的呢。
> > > 
> > > 
> > > 没人反驳就真当自己想的都对的？issue里喷子多了，就你他妈装逼，又github用户规则，又影响正常用户提issue，合着您是提了正常的issue才来打抱不平，还是来开个issue刷存在感？多学点东西，少他妈装逼，既然翻了墙就多看点代码。
> > 
> > 
> > 是。我不是Developer。
> > 但起码有脑子。
> > 不是那种无脑狂喷的人。
> > 好么。
> 
> 别拽你仅有的词汇了，真他妈搞笑。别说废话了，就事论事，懂？

就事論事就是你快點收聲，不要在牆外網站丟中國人的臉，要亂噴會你那少少的牆國內網去。

另外多謝你為自由論壇 https://pincong.rocks 捐贈一百刀作為營運經費，為中國民主運動事業出一分力。

Thank you for your generous donation to https://pincong.rocks, your assistance will be highly appreciated.

**Comment by C4o** [comment]
> > > > > > 我寻思着您他妈也是网络喷子啊 本来以为是个爱学习的开发者 看你主页 star7个项目 超过一半是ss和博客主题 刚学会翻墙和搭个博客就觉得世界是你的了？
> > > > > 
> > > > > 
> > > > > 是么，那我寻思着您也差不多啊 张口就是喷子喷子
> > > > > 我寻思着您的本质也差不多么 m8?
> > > > > 非要找这个issue来喷我 您是怎么了 就觉得国家利益比自身利益高呗 非要让那些人“成功维权呗”
> > > > > 是的，我可能并不是一个开发者。
> > > > > 可是我思路可是比您好的多呢。
> > > > > 也并不会像您这样随便找issue进来bbll的呢。
> > > > 
> > > > 
> > > > 没人反驳就真当自己想的都对的？issue里喷子多了，就你他妈装逼，又github用户规则，又影响正常用户提issue，合着您是提了正常的issue才来打抱不平，还是来开个issue刷存在感？多学点东西，少他妈装逼，既然翻了墙就多看点代码。
> > > 
> > > 
> > > 是。我不是Developer。
> > > 但起码有脑子。
> > > 不是那种无脑狂喷的人。
> > > 好么。
> > 
> > 
> > 别拽你仅有的词汇了，真他妈搞笑。别说废话了，就事论事，懂？
> 
> 就事論事就是你快點收聲，不要在牆外網站丟中國人的臉，要亂吠回你那小小的牆國內網去。
> 
> 另外多謝你為自由論壇 https://pincong.rocks 捐贈一百刀作為營運經費，為中國民主運動事業出一分力。
> 
> Thank you for your generous donation to https://pincong.rocks, your assistance will be highly appreciated.

有墙关你吊事？不做中国人就别用中文。另外，捐你妈，这么牛逼哄哄，连100刀都要乞讨？

**Comment by FlyEmojiStudiooo** [comment]
> > > > > > > 我寻思着您他妈也是网络喷子啊 本来以为是个爱学习的开发者 看你主页 star7个项目 超过一半是ss和博客主题 刚学会翻墙和搭个博客就觉得世界是你的了？
> > > > > > 
> > > > > > 
> > > > > > 是么，那我寻思着您也差不多啊 张口就是喷子喷子
> > > > > > 我寻思着您的本质也差不多么 m8?
> > > > > > 非要找这个issue来喷我 您是怎么了 就觉得国家利益比自身利益高呗 非要让那些人“成功维权呗”
> > > > > > 是的，我可能并不是一个开发者。
> > > > > > 可是我思路可是比您好的多呢。
> > > > > > 也并不会像您这样随便找issue进来bbll的呢。
> > > > > 
> > > > > 
> > > > > 没人反驳就真当自己想的都对的？issue里喷子多了，就你他妈装逼，又github用户规则，又影响正常用户提issue，合着您是提了正常的issue才来打抱不平，还是来开个issue刷存在感？多学点东西，少他妈装逼，既然翻了墙就多看点代码。
> > > > 
> > > > 
> > > > 是。我不是Developer。
> > > > 但起码有脑子。
> > > > 不是那种无脑狂喷的人。
> > > > 好么。
> > > 
> > > 
> > > 别拽你仅有的词汇了，真他妈搞笑。别说废话了，就事论事，懂？
> > 
> > 
> > 就事論事就是你快點收聲，不要在牆外網站丟中國人的臉，要亂吠回你那小小的牆國內網去。
> > 另外多謝你為自由論壇 https://pincong.rocks 捐贈一百刀作為營運經費，為中國民主運動事業出一分力。
> > Thank you for your generous donation to https://pincong.rocks, your assistance will be highly appreciated.
> 
> 有墙关你吊事？不做中国人就别用中文。另外，捐你妈，这么牛逼哄哄，连100刀都要乞讨？

lmao 无脑乱喷了 戳到G点了
太有意思了
墙内Developer真有意思 加速迫害 请

**Comment by C4o** [comment]
> > > > > > > > 我寻思着您他妈也是网络喷子啊 本来以为是个爱学习的开发者 看你主页 star7个项目 超过一半是ss和博客主题 刚学会翻墙和搭个博客就觉得世界是你的了？
> > > > > > > 
> > > > > > > 
> > > > > > > 是么，那我寻思着您也差不多啊 张口就是喷子喷子
> > > > > > > 我寻思着您的本质也差不多么 m8?
> > > > > > > 非要找这个issue来喷我 您是怎么了 就觉得国家利益比自身利益高呗 非要让那些人“成功维权呗”
> > > > > > > 是的，我可能并不是一个开发者。
> > > > > > > 可是我思路可是比您好的多呢。
> > > > > > > 也并不会像您这样随便找issue进来bbll的呢。
> > > > > > 
> > > > > > 
> > > > > > 没人反驳就真当自己想的都对的？issue里喷子多了，就你他妈装逼，又github用户规则，又影响正常用户提issue，合着您是提了正常的issue才来打抱不平，还是来开个issue刷存在感？多学点东西，少他妈装逼，既然翻了墙就多看点代码。
> > > > > 
> > > > > 
> > > > > 是。我不是Developer。
> > > > > 但起码有脑子。
> > > > > 不是那种无脑狂喷的人。
> > > > > 好么。
> > > > 
> > > > 
> > > > 别拽你仅有的词汇了，真他妈搞笑。别说废话了，就事论事，懂？
> > > 
> > > 
> > > 就事論事就是你快點收聲，不要在牆外網站丟中國人的臉，要亂吠回你那小小的牆國內網去。
> > > 另外多謝你為自由論壇 https://pincong.rocks 捐贈一百刀作為營運經費，為中國民主運動事業出一分力。
> > > Thank you for your generous donation to https://pincong.rocks, your assistance will be highly appreciated.
> > 
> > 
> > 有墙关你吊事？不做中国人就别用中文。另外，捐你妈，这么牛逼哄哄，连100刀都要乞讨？
> 
> lmao 无脑乱喷了 戳到G点了
> 太有意思了
> 墙内Developer真有意思 加速迫害 请

没文化还真可怕，咬着一个无关紧要的点不放。没事多看看书比什么都好，别老秀你那几个词汇，你哪怕能翻译一段话给我看，我都能稍微高看你一点。别回了，废物，没空回你了。多看看书，多看看代码，生而为人，做点有意义的事，不要听风就是雨。

**Comment by FlyEmojiStudiooo** [comment]
> > > > > > > > > 我寻思着您他妈也是网络喷子啊 本来以为是个爱学习的开发者 看你主页 star7个项目 超过一半是ss和博客主题 刚学会翻墙和搭个博客就觉得世界是你的了？
> > > > > > > > 
> > > > > > > > 
> > > > > > > > 是么，那我寻思着您也差不多啊 张口就是喷子喷子
> > > > > > > > 我寻思着您的本质也差不多么 m8?
> > > > > > > > 非要找这个issue来喷我 您是怎么了 就觉得国家利益比自身利益高呗 非要让那些人“成功维权呗”
> > > > > > > > 是的，我可能并不是一个开发者。
> > > > > > > > 可是我思路可是比您好的多呢。
> > > > > > > > 也并不会像您这样随便找issue进来bbll的呢。
> > > > > > > 
> > > > > > > 
> > > > > > > 没人反驳就真当自己想的都对的？issue里喷子多了，就你他妈装逼，又github用户规则，又影响正常用户提issue，合着您是提了正常的issue才来打抱不平，还是来开个issue刷存在感？多学点东西，少他妈装逼，既然翻了墙就多看点代码。
> > > > > > 
> > > > > > 
> > > > > > 是。我不是Developer。
> > > > > > 但起码有脑子。
> > > > > > 不是那种无脑狂喷的人。
> > > > > > 好么。
> > > > > 
> > > > > 
> > > > > 别拽你仅有的词汇了，真他妈搞笑。别说废话了，就事论事，懂？
> > > > 
> > > > 
> > > > 就事論事就是你快點收聲，不要在牆外網站丟中國人的臉，要亂吠回你那小小的牆國內網去。
> > > > 另外多謝你為自由論壇 https://pincong.rocks 捐贈一百刀作為營運經費，為中國民主運動事業出一分力。
> > > > Thank you for your generous donation to https://pincong.rocks, your assistance will be highly appreciated.
> > > 
> > > 
> > > 有墙关你吊事？不做中国人就别用中文。另外，捐你妈，这么牛逼哄哄，连100刀都要乞讨？
> > 
> > 
> > lmao 无脑乱喷了 戳到G点了
> > 太有意思了
> > 墙内Developer真有意思 加速迫害 请
> 
> 没文化还真可怕，咬着一个无关紧要的点不放。没事多看看书比什么都好，别老秀你那几个词汇，你哪怕能翻译一段话给我看，我都能稍微高看你一点。别回了，废物，没空回你了。多看看书，多看看代码，生而为人，做点有意义的事，不要听风就是雨。

咋了，骂我还能脏您嘴了？
您的嘴也挺高贵的哈。
继续迫害 请。

**Comment by aoJavaSto** [comment]
> @dongyint 人家是軟件的作者，發布什麼有他的自由，沒聽過言論自由嗎（牆國沒有的）
> 
> As the author of the software, he has the freedom to publish whatever he want, an example of freedom of speech which the wall country don't have.

你知道开源的定义是什么吗，你就在这bb？
No Discrimination Against Persons or Groups.
作者先搞事情的  怪谁？？
