### ISSUE TITLE
I don't get it

### ISSUE THREAD

**Issue by vonkk** [notepad-plus-plus/notepad-plus-plus#7452]
So the author made an anti-China edition, then his issue channel got flowed with anti-China botnets. Why?

**Comment by rizic** [comment]
the blind chinese nationalist get very butthurt know that the entire world knows how shit there country is including there goverment. Theres a reason why chinese tourist are regarded as the rudest and the most uneducated people that travel abroad. I guess that tends to happen when a retard like Mao kills all the smart people in china;

**Comment by vonkk** [comment]
@rizic What do you mean, read those issues, use Google Translate, these threads are clearly ANTI-China.

**Comment by loveyanbei** [comment]
@Pakbon They're real, go home and fuck youself.
