### ISSUE TITLE
Don't trust China.  China is ass ho.  https://media.phoneboy.com/najingles/ChinaIsAssho.mp3

### ISSUE THREAD

**Issue by czervika** [notepad-plus-plus/notepad-plus-plus#7453]
### Steps to Reproduce the Issue

1. 
2. 
3.

**Comment by FlyEmojiStudiooo** [comment]
mah, don't be that so toxic
Delete this issue and send email to GitHub to fix this problem and shouldn't break the GitHub rules.
(And I'm already Send a issue to make Chinese don't be that toxic(should be))

**Comment by TaiWanDOG** [comment]
Don't trust Taiwan. Taiwan is ass ho.

**Comment by loveyanbei** [comment]
Do not trust Shepherd, I repeat, Do not trust Shepherd.
