### ISSUE TITLE
Taiwan #1!!!!

### ISSUE THREAD

**Issue by CaderHancock** [notepad-plus-plus/notepad-plus-plus#7455]
### Steps to Reproduce the Issue

1. 
2. 
3.

**Comment by mxhyeon** [comment]
什么也不说了，自己一事无成，埋怨世道的不公平来这里撒气的

**Comment by FlyEmojiStudiooo** [comment]
？这不是您自己么
好好反省，不要做无脑行为，在网络上逼逼赖赖要动脑子的

**Comment by FlyEmojiStudiooo** [comment]
Don't say other shit
Just delete this issue and go email to github and report them

**Comment by mxhyeon** [comment]
@FlyEmojiStudiooo 不是你一直在bb吗？讲着中文却在骂发明这种语言的人，，你作为废青的样子真滑稽，

**Comment by owoooooooo** [comment]
臺湾好好的，为何要跟中国吃瓜群众同流合污？

**Comment by FlyEmojiStudiooo** [comment]
@mxhyeon 讲道理讲不过来只能无能狂怒乱咬了？不愧是您。

**Comment by michaeldai7** [comment]
> @FlyEmojiStudiooo 不是你一直在bb吗？讲着中文却在骂发明这种语言的人，，你作为废青的样子真滑稽，

众所周知，中文是马克思发明的

**Comment by fuckkina** [comment]
笑看支那贱畜们在github现场送亲妈！！
