### ISSUE TITLE
Can't we all just get along?

### ISSUE THREAD

**Issue by ghost** [notepad-plus-plus/notepad-plus-plus#7458]
Apparently not

**Comment by cliffordjames84** [comment]
Ask the Chinese government lovers their the ones trying to silence everyone.

**Comment by michaeldai7** [comment]
共产党biss

**Comment by TaiWanDOG** [comment]
国民党biss

**Comment by xezno** [comment]
Unfortunately, politics are a little more complicated than that, so it'll take more than a simple "can't we get along" to silence people.

Best solution is just to close issues off for now, and use something with better moderation tools (than GitHub's issues).

**Comment by cliffordjames84** [comment]
China #4

**Comment by MasterFunction** [comment]
Apparently the only way to ensure that is the obliteration of the instigators - in this case, the PRC.

**Comment by J0s3f** [comment]
Only solution is destruction of the chinese regime

**Comment by MasterFunction** [comment]
> > Apparently the only way to ensure that is the obliteration of the instigators - in this case, the PRC.
> 
> Yeah, let's nuke China because of some GitHub issues!

Not *solely* because of these GH Issues, of course, PRC bootlickers have a long streak of reasons deserving death.

**Comment by cliffordjames84** [comment]
Theyre quite literally conducting a WWII holocaust style genocide right now.  But lets all be friends amirite.

**Comment by LukasRutar** [comment]
Get along with totalitarian regime massively violating humans rights? That has to be joke. Inaction is action, and silence is approval.

**Comment by michaeldai7** [comment]
Get along with government doing genocide, is that what you want?
