### ISSUE TITLE
台灣是獨立國家不容極權大陸侵犯

### ISSUE THREAD

**Issue by applecatapplecat** [notepad-plus-plus/notepad-plus-plus#7459]
台灣是獨立國家不容極權大陸侵犯

**Comment by FlyEmojiStudiooo** [comment]
https://github.com/notepad-plus-plus/notepad-plus-plus/issues/7449
希望各位用户可以去看一下。不要给自己国家丢脸。

**Comment by dongyingt** [comment]
唯一的途径就是武力解决，说这么多是没有用的，赢了你们想怎么样都行，输了，乖乖坐好，所有的优惠政策统统没有，试试吧

**Comment by FlyEmojiStudiooo** [comment]
> > 唯一的途径就是武力解决，说这么多是没有用的，赢了你们想怎么样都行，输了，乖乖坐好，所有的优惠政策统统没有，试试吧
> 
> 快來啦，你們喊幾十年了，快笑死我。

草，无话反击，等会上面那个人肯定变成疯狗无脑狂咬

**Comment by Cnotech** [comment]
试试就试试，你到时候可不要跑哦，保卫好你的“祖国”

**Comment by applecatapplecat** [comment]
> 
> 
> > > > 唯一的途径就是武力解决，说这么多是没有用的，赢了你们想怎么样都行，输了，乖乖坐好，所有的优惠政策统统没有，试试吧
> > > 
> > > 
> > > 快來啦，你們喊幾十年了，快笑死我。
> > 
> > 
> > 草，无话反击，等会上面那个人肯定变成疯狗无脑狂咬
> 
> 当爹的怎么舍得打儿子呢？先给你画根线，踩踩试试吧。

我們獨立好幾十年了，快來啦拜託～難道中共教育出來的都只剩下一張嘴跟玻璃心模板。

**Comment by applecatapplecat** [comment]
> 
> 
> 试试就试试，你到时候可不要跑哦，保卫好你的“祖国”

**Comment by FlyEmojiStudiooo** [comment]
不行了，笑死我了，一群粉红支那人都觉得自己能控制国家导弹系统，都以为自己是军官长，让我先笑一会@applecatapplecat 扶我一下我笑的走不动了哈哈哈哈哈哈哈哈哈哈哈哈哈哈

**Comment by dongyingt** [comment]
> > > > > > > 唯一的途径就是武力解决，说这么多是没有用的，赢了你们想怎么样都行，输了，乖乖坐好，所有的优惠政策统统没有，试试吧
> > > > > > 
> > > > > > 
> > > > > > 快來啦，你們喊幾十年了，快笑死我。
> > > > > 
> > > > > 
> > > > > 草，无话反击，等会上面那个人肯定变成疯狗无脑狂咬
> > > > 
> > > > 
> > > > 当爹的怎么舍得打儿子呢？先给你画根线，踩踩试试吧。
> > > 
> > > 
> > > 我們獨立好幾十年了，快來啦拜託～難道中共教育出來的都只剩下一張嘴跟玻璃心模板。
> > 
> > 
> > 没有吧，啥时候独立的？全世界也没听到哪几个国家敢承认的吧。当年把这些人赶到岛上，没一举歼灭，已经是很给面子了，咋不知道感恩呢。
> 
> 哎喲好棒喔，不要只會打字喔，快點來。我們何必需要帝制中共的承認呢？哈哈

我代表不了国家，我只代表我的态度。谁说要承认你们什么了，这块地是我们的，脸面留得足足的，不急不躁，就看着使劲折腾，该拿回来的时候，是一定要拿的，谁也拿不走，它就在那里。这一帮子什么时候出，也不是我说了算。

**Comment by applecatapplecat** [comment]
> 
> 
> > > > > > > > 唯一的途径就是武力解决，说这么多是没有用的，赢了你们想怎么样都行，输了，乖乖坐好，所有的优惠政策统统没有，试试吧
> > > > > > > 
> > > > > > > 
> > > > > > > 快來啦，你們喊幾十年了，快笑死我。
> > > > > > 
> > > > > > 
> > > > > > 草，无话反击，等会上面那个人肯定变成疯狗无脑狂咬
> > > > > 
> > > > > 
> > > > > 当爹的怎么舍得打儿子呢？先给你画根线，踩踩试试吧。
> > > > 
> > > > 
> > > > 我們獨立好幾十年了，快來啦拜託～難道中共教育出來的都只剩下一張嘴跟玻璃心模板。
> > > 
> > > 
> > > 没有吧，啥时候独立的？全世界也没听到哪几个国家敢承认的吧。当年把这些人赶到岛上，没一举歼灭，已经是很给面子了，咋不知道感恩呢。
> > 
> > 
> > 哎喲好棒喔，不要只會打字喔，快點來。我們何必需要帝制中共的承認呢？哈哈
> 
> 我代表不了国家，我只代表我的态度。谁说要承认你们什么了，这块地是我们的，脸面留得足足的，不急不躁，就看着使劲折腾，该拿回来的时候，是一定要拿的，谁也拿不走，它就在那里。这一棒子什么时候出，也不是我说了算。

哈哈台灣有人在乎你們嗎？繼續離線跟維尼皇帝開趴吧～

**Comment by dongyingt** [comment]
> > > > > > > > > 唯一的途径就是武力解决，说这么多是没有用的，赢了你们想怎么样都行，输了，乖乖坐好，所有的优惠政策统统没有，试试吧
> > > > > > > > 
> > > > > > > > 
> > > > > > > > 快來啦，你們喊幾十年了，快笑死我。
> > > > > > > 
> > > > > > > 
> > > > > > > 草，无话反击，等会上面那个人肯定变成疯狗无脑狂咬
> > > > > > 
> > > > > > 
> > > > > > 当爹的怎么舍得打儿子呢？先给你画根线，踩踩试试吧。
> > > > > 
> > > > > 
> > > > > 我們獨立好幾十年了，快來啦拜託～難道中共教育出來的都只剩下一張嘴跟玻璃心模板。
> > > > 
> > > > 
> > > > 没有吧，啥时候独立的？全世界也没听到哪几个国家敢承认的吧。当年把这些人赶到岛上，没一举歼灭，已经是很给面子了，咋不知道感恩呢。
> > > 
> > > 
> > > 哎喲好棒喔，不要只會打字喔，快點來。我們何必需要帝制中共的承認呢？哈哈
> > 
> > 
> > 我代表不了国家，我只代表我的态度。谁说要承认你们什么了，这块地是我们的，脸面留得足足的，不急不躁，就看着使劲折腾，该拿回来的时候，是一定要拿的，谁也拿不走，它就在那里。这一棒子什么时候出，也不是我说了算。
> 
> 哈哈台灣有人在乎你們嗎？繼續離線跟維尼皇帝開趴吧～

应该不会在乎吧，毕竟是叫不醒装睡的人

**Comment by dongyingt** [comment]
> > 应该不会在乎吧，毕竟是叫不醒装睡的人
> 
> 你們睡著還醒著有差嗎？反正都只能被維尼，中共洗腦教育出來的還真的都是一個模子，哈哈。

为什么不想想，你们是不是被洗脑了，那肯定说：没有

**Comment by applecatapplecat** [comment]
> 
> 
> > > 应该不会在乎吧，毕竟是叫不醒装睡的人
> > 
> > 
> > 你們睡著還醒著有差嗎？反正都只能被維尼，中共洗腦教育出來的還真的都是一個模子，哈哈。
> 
> 为什么不想想，你们是不是被洗脑了，那肯定说：没有

哈哈，被洗腦的一邊還跑來拯救清醒的一邊，噗ㄘ～

[https://news.ltn.com.tw/news/politics/breakingnews/2929242](url)

**Comment by VitaminV9** [comment]
> 不行了，笑死我了，一群粉红支那人都觉得自己能控制国家导弹系统，都以为自己是军官长，让我先笑一会@applecatapplecat 扶我一下我笑的走不动了哈哈哈哈哈哈哈哈哈哈哈哈哈哈

被中共洗脑严重的人，总有种幻像，以为自己姓赵。
