### ISSUE TITLE
Stand with notepad plus plus developer

### ISSUE THREAD

**Issue by hkcharles** [notepad-plus-plus/notepad-plus-plus#7461]
### Description of the Issue
The developer is harassed by Chinese "developer" as he exercise his freedom of speech and stand with Uyghurs people. This is not uncommon, and have been happening for years almost everywhere in both physical or cyber world. 

### Steps to Reproduce the Issue
1. You have different opinion with "Chinese official political stances"
2. You voice it out, peacefully and logically, based on fact.
3. swarm of Chinese netizens, or even state media will start attacking you, putting pressure from both legal and illegal, political and peer pressure to force you to shut up

### Expected Behavior
Having different opinion, discuss and debate logically and peacefully
Try to understand each other POV, based on fact.

### Actual Behavior
1. Chinese people claims that you are "not respecting their country"
2. Chinese people demonstrate a logic fallacy by counter arguing "Your country killed a lot of people too"
3. Chinese people misunderstand freedom of speech and believe it is their "freedom" to force you to shut up 

### Debug Information
As a Hong Konger, we've been seeing all these crap for decades. Same situation applies to Taiwan, Uyghurs, Tibet, whatever place that the Chinese people wanted to conquer. 

Stay strong, don't compromise. Notepad++ is a great software and let Chinese people boycott it.

**Comment by Musketmarine** [comment]
Anyone got a quickfix for this? It's an issue that's been plaguing specific clients, and i'm curious as to whether I will start having this issue!
