### ISSUE TITLE
[DevOps] Request for enhancement of issue tracker

### ISSUE THREAD

**Issue by xtlsoft** [notepad-plus-plus/notepad-plus-plus#7462]
It seems that the issue tracker has been used as a political forum, and that's against the rule.

I suggest to disable GitHub issues and open another self-hosted bug tracker, which has functionalities to detect spam information.

-------------------------

For the users who are abusing the issue tracker, I advise you to stop this meaningless act. The `Piwiki` project is an example. Open-source has nothing to do with politics. No matter which country you support, or even you are in prison, you should be treated the same in the open-source community, as it is a place for everyone to develop and discuss software.

对于正在滥用问题追踪器的用户，我建议你停止这个无意义的行为。`Piwiki` 项目是一个前车之鉴。开源与政治无关。无论你支持哪个国家，甚至你是一名罪犯，你在开源社区都应被平等对待，因为这是一个给任何人讨论和开发软件的场所。

Remember, here, in the open-source community, no politics.

**Comment by rogersachan** [comment]
![image](https://user-images.githubusercontent.com/7173984/67869268-94b6ea80-fb03-11e9-8d16-8d81f9788b9a.png)
I think interaction limits should be turned on ASAP so the current bad issues can be dealt with

**Comment by marekr** [comment]
> . Open-source has nothing to do with politics. No matter which country you support, or even you are in prison, you should be treated the same in the open-source community, as it is a place for everyone to develop and discuss software.

Nope. Open source is about sharing code so others may reuse it. NOTHING restricts an author from voicing his own personal beliefs. The author is putting in their personal time to work on code, many times most users are even leeching off their work and never even contributing back. The author more than earns the right.
