### ISSUE TITLE
“台独”运动是台湾社会的一个毒瘤。所谓“台湾独立”，就是主张把台湾从中国分裂出去。主张“台湾独立”的分裂运动是从抗日战争胜利后、台湾回归中国版图后开始的，并一直延续到今天。

### ISSUE THREAD

**Issue by ghost** [notepad-plus-plus/notepad-plus-plus#7463]
“台独”运动是台湾社会的一个毒瘤。所谓“台湾独立”，就是主张把台湾从中国分裂出去。主张“台湾独立”的分裂运动是从抗日战争胜利后、台湾回归中国版图后开始的，并一直延续到今天。

**Comment by TaiWanDOG** [comment]
> “台独”运动是台湾社会的一个毒瘤。所谓“台湾独立”，就是主张把台湾从中国分裂出去。主张“台湾独立”的分裂运动是从抗日战争胜利后、台湾回归中国版图后开始的，并一直延续到今天。
> 
> 滾回去用碼雲

滾到你的棺材離去

**Comment by applecatapplecat** [comment]
> 
> 
> ![IMG_20191019_032249](https://user-images.githubusercontent.com/43862422/67868633-9e8c1e00-fb02-11e9-8eaf-32d069449e69.jpg)
> ![IMG_20191019_032243](https://user-images.githubusercontent.com/43862422/67868634-9e8c1e00-fb02-11e9-8d95-c4ae1333840e.jpg)


玻璃心只是忌妒別人民主哈哈。

**Comment by michael34435** [comment]
> “台独”运动是台湾社会的一个毒瘤。所谓“台湾独立”，就是主张把台湾从中国分裂出去。主张“台湾独立”的分裂运动是从抗日战争胜利后、台湾回归中国版图后开始的，并一直延续到今天。

您好，可能貴國的網路比較慢，沒有接收到最新資訊
現在台灣是由一個叫做中華民國的國家所統治，中華民國自1912年成立，在1945年的時候控制台灣至今

**Comment by Noiwex** [comment]
动态网自由门 天安門 天安门 法輪功 李洪志 Free Tibet 六四天安門事件 The Tiananmen Square protests of 1989 天安門大屠殺 The Tiananmen Square Massacre 反右派鬥爭 The Anti-Rightist Struggle 大躍進政策 The Great Leap Forward 文化大革命 The Great Proletarian Cultural Revolution 人權 Human Rights 民運 Democratization 自由 Freedom 獨立 Independence 多黨制 Multi-party system 台灣 臺灣 Taiwan Formosa 中華民國 Republic of China 西藏 土伯特 唐古特 Tibet 達賴喇嘛 Dalai Lama 法輪功 Falun Dafa 新疆維吾爾自治區 The Xinjiang Uyghur Autonomous Region 諾貝爾和平獎 Nobel Peace Prize 劉暁波 Liu Xiaobo 民主 言論 思想 反共 反革命 抗議 運動 騷亂 暴亂 騷擾 擾亂 抗暴 平反 維權 示威游行 李洪志 法輪大法 大法弟子 強制斷種 強制堕胎 民族淨化 人體實驗 肅清 胡耀邦 趙紫陽 魏京生 王丹 還政於民 和平演變 激流中國 北京之春 大紀元時報 九評論共産黨 獨裁 專制 壓制 統一 監視 鎮壓 迫害 侵略 掠奪 破壞 拷問 屠殺 活摘器官 誘拐 買賣人口 遊進 走私 毒品 賣淫 春畫 賭博 六合彩 天安門 天安门 法輪功 李洪志 Winnie the Pooh 劉曉波动态网自由门

**Comment by dongyingt** [comment]
> > ![IMG_20191019_032249](https://user-images.githubusercontent.com/43862422/67868633-9e8c1e00-fb02-11e9-8eaf-32d069449e69.jpg)
> > ![IMG_20191019_032243](https://user-images.githubusercontent.com/43862422/67868634-9e8c1e00-fb02-11e9-8d95-c4ae1333840e.jpg)
> 
> 玻璃心只是忌妒別人民主哈哈。

民主是可以游行，可以对立，可以爆发冲突的，我觉着西方的民主挺好的，没事就来一波暴力活动，人民生活挺闲的，美国还能拥枪，多自由，没事就来个团灭，这种美丽风景线应该多些。还有这些图片需要得到世界公认才行，自己在网上找个图，或者P一下，是意淫行为。

**Comment by dongyingt** [comment]
> > > > “台独”运动是台湾社会的一个毒瘤。所谓“台湾独立”，就是主张把台湾从中国分裂出去。主张“台湾独立”的分裂运动是从抗日战争胜利后、台湾回归中国版图后开始的，并一直延续到今天。
> > > 
> > > 
> > > 您好，可能貴國的網路比較慢，沒有接收到最新資訊
> > > 現在台灣是由一個叫做中華民國的國家所統治，中華民國自1912年成立，在1945年的時候控制台灣至今
> > 
> > 
> > 行啦，和清朝末期太监说的话一样
> 
> 你說的話跟習維尼皇朝太監差不多，哈。

没听懂算了

**Comment by VitaminV9** [comment]
> > > ![IMG_20191019_032249](https://user-images.githubusercontent.com/43862422/67868633-9e8c1e00-fb02-11e9-8eaf-32d069449e69.jpg)
> > > ![IMG_20191019_032243](https://user-images.githubusercontent.com/43862422/67868634-9e8c1e00-fb02-11e9-8d95-c4ae1333840e.jpg)
> > 
> > 
> > 玻璃心只是忌妒別人民主哈哈。
> 
> 民主是可以游行，可以对立，可以爆发冲突的，我觉着西方的民主挺好的，没事就来一波暴力活动，人民生活挺闲的，美国还能拥枪，多自由，没事就来个团灭，这种美丽风景线应该多些。还有这些图片需要得到世界公认才行，自己在网上找个图，或者P一下，是意淫行为。

美国拥枪为啥政府还没被推翻呀，中国买个菜刀还要实名制？

**Comment by LiuXin9527** [comment]
10年過後再來驗證真理
