### ISSUE TITLE
O macaco cantador (重要訊息)!!!!!

### ISSUE THREAD

**Issue by wakroa** [notepad-plus-plus/notepad-plus-plus#7467]
嘿，太酷了。 所有人都告訴我，當我留鬍子時，我讓它太寬了。 你有適合他們的美容指南嗎

同志，問題是您可能沒有看到所有帖子。 如果您僅通過問題跟踪器查看github，則看不到綠色的帖子，ID中帶有字母的帖子或無數的內容。 視日期而定，它們合起來佔github的40-70％。 因此，對話將顯得不連貫和痙攣，因為您將無法獲得完整的畫面。

(永恒的生命)
陰謀

**Comment by wakroa** [comment]
@Noiwex 

嘿，太酷了。 所有人都告訴我，當我留鬍子時，我讓它太寬了。 你有適合他們的美容指南嗎

同志，問題是您可能沒有看到所有帖子。 如果您僅通過問題跟踪器查看github，則看不到綠色的帖子，ID中帶有字母的帖子或無數的內容。 視日期而定，它們合起來佔github的40-70％。 因此，對話將顯得不連貫和痙攣，因為您將無法獲得完整的畫面。

[重要訊息 o macaco cantador](https://youtu.be/jjbZ3R3Sp-E)

(永恒的生命)
陰謀

**Comment by Noiwex** [comment]
[![AVGN: A herd of fucking ugly reds](https://img.youtube.com/vi/HetM_Xw47IA/0.jpg)](https://www.youtube.com/watch?v=HetM_Xw47IA)

**Comment by Noiwex** [comment]
https://www.youtube.com/watch?v=M_aXcH1zDEE

**Comment by Mikotochan** [comment]
@AlexVincent525
Free hong kong
