### ISSUE TITLE
南草榴，北杏吧，中文色情网站十五年风云录

### ISSUE THREAD

**Issue by ncbx002** [notepad-plus-plus/notepad-plus-plus#7468]
谈谈风月，何必争吵？
“1024，节日快乐！”
杏吧有你，春暖花开！

01

色情经济的原罪

人性如同弹簧，压得越紧，弹力越大。
根据以色列一家市场调研公司Similar Web的报告显示，保守国家在对色情网站的人均访问数据要远高于开放国家，科威特、沙特阿拉伯、埃及等国家均名列前茅，美国、加拿大、荷兰等国家反而拖了后腿。
这份榜单里并无中国的踪影，不过并不是中国足够“洁身自好”，而是统计样本皆为英文语种的色情网站，由于语言隔阂和教育程度，这些网站很难获得规模化的中国用户的访问。不过，如果将英文水准普遍较高的香港单独拿出来就会发现，这个弹丸之城在色情网站的人均浏览时长上在全球排到了第6位。
360公司老大周鸿祎曾经说过这么个故事，他说成人网站里潜藏着木马，360 浏览器尝试弹出风险警告。但是想不到的是，99% 的用户都会直接关掉弹窗，还有不少人反馈："如果 360 再弹，就把 360 彻底的卸掉！"
什么是刚需？这就是。
就像上文所言，改革开放以来，色情之于中国社会，有着解冻和非罪化的趋势，情趣用品等敏感产业也从遮掩走向坦然。但是，由于“扫黄打非”始终占据着行政意义上的制高点，“可以做爱，但是不许了解做爱”也成为了某种悖论。
以现行法律而言，购买、下载和观看色情影片并不违法，但是只要涉及制作、运输、传播和租售行为，就属于触犯法律了，且量刑尺度极大。
两个实际的案例，可以形象说明中国法律为色情所设立的边界：
2002年，延安一对夫妻因在家里看“黄碟”而被当地警察刑拘一事，曾在社会舆论上引起极大争议，最后，公安机关正式道歉，并做出了赔偿。当时就有媒体称，如果按照是否观赏色情影片作为抓人的标准，恐怕中国剩不了多少清白之身的人口了。
2013年，广州一名李姓男子在电脑摊位上以1元1部的价格售卖他个人收藏的色情影片，在刚刚获得5元“非法收益”之后就被警方抓获，最终法院以“复制、贩卖淫秽物品牟利罪、情节特别严重”将其判刑5年。
因此，在尚未脱离原罪的色情领域，中国市场兼具高风险和低回报的不对等特性，以致于供需失衡，时至今日，各大门户点击最高的链接，仍是那些带有色情意味的擦边球标题及图片。
在一个将色情视为洪水猛兽的国家兜售相关内容，如同于沙漠中心贩卖水源，丝毫毋需担忧客群。饭岛爱、武藤兰、苍井空分别代表了碟片、ADSL和宽带三个时代，而P2P技术的空前发达，则使中国成为全球最大的色情影片消费国。
早期的中文色情网站鱼龙混杂，挂羊头卖狗肉的采集模式层出不穷，用户点击一张又一张的图片，在一个又一个垃圾站之间来回跳转，就是无法抵达想要下载的文件，已是寻常之事。此时，只要小心不让Google Adsense等广告联盟“K站”，操控流量的站长利用色情内容日赚过万美金，并不算难。
而在这样一个用户体验为负值、全赖原始荷尔蒙驱动的行业里，一旦出现超出及格线的行为，很快就会形成标杆效应。

02

风云激荡2004

2004 注定是大风大浪，不平凡的一年。
那是非典肆虐的最后一年，果子狸作为传染源被疯狂捕杀；那一年刘翔奥运会冲金，被称为亚洲飞人；当然还有正值事业巅峰的苍井空，刚刚换了新公司准备大展一番拳脚 ...
因为非典，那一年人人自危📷
那年的刘翔还不懂，水能载舟亦能覆舟📷
那一年，苍老师还自称 " 处女 " 。📷
此时的国内，有一批制作粗糙的网络论坛如雨后春笋一般生长出来，草榴社区、情色六月天、爱城、色中色、18P2P、九九情色先后成立。迄今，谁也无法解释为什么这些制定了“行业标准”的色情网站品牌为何集中于2004年爆发诞生，而它们的迥异命运，亦令人不胜唏嘘。
换句话说，草榴社区的幸存和独大，恐怕也有着时运成分。
当时这个领域正是一片空白，各家网站都在各显神通，争夺这块处女地的红利期。
草榴也不例外，但是实力孱弱的它非常清楚，它没有逐鹿中原的资本，它所做的，只能是等。韬光养晦，等一个机会，不是为了证明自己有多了不起，而是要证明是我的永远都是我的！
两年后，作为 " 行业标杆 " 的六月天，被太原警方一举捣毁，树倒猢狲散，六十万粉丝一夜之间灰飞烟灭。
与此同时，另一位大佬、九九的创始人“戏子”真实身份曝光，被中美两国联手抓获，引渡回国。
色中色的管理团队分家，拷贝代码另起炉灶，争抢用户相互攻击，一度引发混乱。
行业迎来了大洗牌。
草榴知道，自己的时代到来了。
那年它正式更名 " 草榴社区 "，史称草榴元年。
📷

03

草榴的崛起

因为隐忍，草榴迎来了第一个春天。
但如果你以为，它只有隐忍的本事，那你可就大错特错了。他们有非常独特的发家思路，并在龙盘虎踞的情色产业屹立不倒。
首先，他们承诺绝不向用户收费，所有内容取之于用户，用之于用户。
其次，他们没有任何弹窗广告、也不限定用户购买 VIP，界面清清爽爽、十年如一。
网站写给访客的前言 所以比起那些收费明显、或者挂满博彩广告的同行，他们一直是吃相最好，也是用户体验最好的一个。
其他网站上的博彩广告，令人反感 如果你以为这个论坛里都是不上台面的东西，那你又错了。
有很多老用户这样评价：1024 的价值在于其兼容并蓄的平等氛围，草榴社区的用户之间没有阶级，聊的话题也是包罗万象。一个朋友甚至信誓旦旦地告诉我，他在考四级的前一天，居然在草榴社区里做到了考试的真题。论坛里的很多话题，更是营造了乌托邦式的场景社区里有女性情感话题，也有文学历史题材，甚至还有股市最新行情。
不仅如此，这个不入流的网站还发明了一套新玩法：每个社区成员都会以 "1024" 回复主贴，特别是新来的，必须隔 1024 秒才可以发贴或者回复一次，以显得慎重。
因为 "1024" 有 "1GB" 的意思，谐音 " 一级棒 "，是对道中人最好的赞许。
网友回帖 1024 后来，这种回帖方式，开始在各大主流论坛里疯传，不管是天涯、猫扑、贴吧，或者是微博，只要看到 1024 四个数字，就知道是 " 上榴人士 "。
当年草榴社区占领微博，甚至有不少粉丝把10月24日当做一个节日来过。这种新奇的方式，像指数爆炸一样，为这个地下论坛集合了无数的拥趸，在扩张中，甚至打了不少硬仗、恶仗。
其中一场发生在 2009 年，那年 4 月，法院一纸文书，审判了 1024 的恶行，不少核心成员被判处有期徒刑 3 年，缓刑 3 年，并处罚金 5000 元。但是打击，这并没有要了这个网站的命，相反，还有不少人慕名而来。
而360安全屏蔽这些网站时想不到，多年之后他们监控泄露的视频，将会在这些网站上疯传。做黄网做到这个程度，夫复何求。
但是有波峰就有波谷，在运营了几个年头后，论坛弊端已经开始逐渐出现，消息闭塞，视觉陈旧，管理落后。2011 年之后，许多老成员相继隐退，不再出山。另一方面，后起之秀"杏吧"打着"春暖花开"的口号，异军突起，成为网民心中新的圣地。
📷

04

杏吧的野望

2008年，杏吧论坛正式成立。
与其他传统大站明显区别的是，杏吧拥有极强的互联网进化意识，凭借技术创新，多次引领着行业风潮。
脱胎于传统论坛模式，"杏吧"对标中文乃至世界互联网产业的发展趋势。先后研发了图书、杂志、音频、视频、脱口秀、喊麦、直播、配音、短视频、移花接木、人工智能换脸等新鲜的玩法，推出多个主题视频站及APP产品，粉丝暴涨，号称全国粉丝最多的地下论坛。
其中女主播大尺度直播非常受欢迎，多次成为国内新闻的关注焦点。而今年大热的AI换脸，则可以在杏吧找到大量的相关资源。
“春暖花开”也逐渐成为与“1024”齐名的接头暗号，“草榴社区”与“杏吧论坛”南北双雄的格局正式奠定。
📷

05

南草北杏保卫战

英雄人物出我辈，一入江湖岁月催。
“南草北杏”的壮大，伴随着许许多多的风风雨雨，也见证很多人的青春和回忆。
这样的地下网站，在网民中有什么样的地位，也许从四年前的某场危机窥见一斑。
2015年5月，草榴论坛主业发了一个简单的声明，公开宣称：网站遭到黑客攻击，网站处于瘫痪状态，数据几近丢失，恢复的可能性很小，网站将暂时关闭，亦或永久关闭。
这则消息对于当时的网民的震惊程度不亚于晴天霹雳，" 这么大的家业，说没就没了？" 一度，很多人自发团结起来，打着保护 1024 的口号，出现在各大社交网络。人们像被化学反应点燃，争先恐后地祭奠，除了这个网站本站，更多的还有终于将要失去它的恐慌。
此后，类似杏吧、草榴也有多次遭到攻击关闭传言在社交网络蔓延。尽管流量倾灌式的攻击仅会造成带宽上的压力，而不太可能直接摧毁物理层面的数据储存，但是显然，常识在刻奇面前不堪一击。在“1024”“春暖花开”早已成为一个流行性的网络符号的时代，网民们觉得，保护草榴其实就是保护每个小人物的尊严，就是保护自己。
十几年来，在这个严厉管制色情产业、并推行强烈的道德意志的国家，草榴杏吧的崛起和兴盛，及其大隐隐于市的经营模式，无不堪称奇迹。
📷

06

浪花淘尽英雄

明代文学家杨慎写过这么一首词：" 滚滚长江东逝水，浪花淘尽英雄，是非成败转头空。古今多少事，都付笑谈中。"
2006年，拥有60万余注册用户的情色六月天被太原警方捣毁，由于使用境内银行卡收款，其站长坑了整个版主团队，案件也一度被广为宣传，体现扫黄成绩。
在查处情色六月天的过程中，九九情色的“色情网站矩阵”被首度曝光，当时的资料显示，网名为“戏子”的一名华人以半投资半收购的方式，控制了高达48个中文色情站点。由于“戏子”身在美国，所以相当安全，但是用现在的话来讲，他是“不作就不会死”，躺着挣钱之余，竟然涉足儿童色情的内容，这在美国也属于犯罪范畴。2011年，中国公安部与美国警方协作，将“戏子”抓捕并引渡回国。
2011年，色中色产生内部分裂，技术负责人与网站经营者“理念不合”，前者利用技术权限将网站数据拷贝另建新站，而后者在联合其他知名色情网站，对“叛徒”进行通缉，直到现在，若是下载当年的色情影片资源，仍然能够看到被装入文件中的控诉信件。
2012年，新兴色情论坛MM公寓被定性为“特大淫秽色情网站”，超过两千名用户遭到抓捕，这种夸张的执法尺度一度遭到质疑，由于站长依然身在海外，办案人员甚至向其亲属施加压力，迫使关闭服务器。
面对既是竞争对手又是同行伙伴的纷纷倒下，草榴社区和杏吧论坛的稳如磐石，更显珍贵。其中草榴社区明哲保身的一条重要原则是坚决不碰面向用户的经济账，据称业内有着“公开的秘密”，即监管部门会特别注意有着明显收费行为的色情网站，若是避开这道把柄，安全性会相对高很多。
另外，草榴社区和杏吧论坛也拒绝身在中国境内的用户担任版主等职位，防止留下牵一发而动全身的创口。
📷

07

并不复杂的产业

尽管南草榴北杏吧有很大影响力，但是从中国色情内容的产业链而言，它们处在相当下游的位置。
位于最上游的，是色情电影的购买者。一部新问世的日本AV，在DMM上通常会以1000-4000日元不等的价格售卖，就像任何盗版电影的流出过程一样，必须要有人掏出真金白银，购买获得影片文件。
由于日本对于数字资产的保护措施十分严格，其AV生产商可以放心在DMM这样的线上渠道发行数字版的AV影片，日本国内也少有复刻行为。但是，这个规矩在中国人看来，并不值得遵守。
DMM使用微软媒体文件WMV格式的DRM版权手段防止购买者进行复制，但是，由于微软的更新漏洞，导致目前仍然有一些老旧电脑能够运行未更新DRM保护的WMV文件，完成破解。所以，中国的这批购买者通常会与色情网站合作，将购买所得的影片内销回来。
很遗憾，松散管理的草榴杏吧并无力竞价这些稀缺资源，诸如上文提及的色中色以及从里面分裂出来的第一会所才是最大的买单者。这些网站设有发片员的角色，主要用于完成色情影片的压制、封装（通常会植入网站的推广文件）、发布和做种流程。
接下来，是相当于义务工作者的转帖者，这些用户出于在其他网站赚取积分等动机，会迅速激活P2P所需要的各处网络节点，用互联网的术语来讲，就是“分发”，草榴杏吧就是一个举重若轻的分发渠道。
最尾端的，也是最为大众的消费者，尽管他们（我们）没有付出任何钱物，但是就如互联网的经典商业模式一样，一切生产及流通成本最终都会转嫁到用户身上。
2010年之后，许多“老资格”的发片员相继隐退，新一批发片员开始以团队组织运作，比较典型的是ID为“第六天魔王”的团队，他垄断了大量的热门片源——一般而言，如果某片源已被购买，其他发片员不会重复购买以避免浪费——进而在影片画面中加入网络赌场的水印广告，尽管引起用户的强烈抗议，却也取得了商业上的奇效。有消息称，由于影片传播人群足够广泛，“第六天魔王”所代理的网络赌场分账不菲，已让发片成为一门生意。同时，利用色情影片建立于刚性需求之上的特点，在用户与内容中间人为设置障碍、然后进行雁过拔毛式的碎片变现，也是当前色情内容产业链里的重要营生。
比如，故意将帖子里的预览图片的尺寸缩小，引导用户“点击观看大图”，进而进入充满各种弹窗广告的图片托管代理站点，用户的每一次点击都会给作者增加CPC收入。
比如，将种子上传到需要多次跳转的网盘里，并限制用户的下载间隔，无论用户是误点广告，还是在该网盘开通VIP账户，作者也都能够拿到佣金分成；再比如，伪造某些断档的番号，故意传播错误的种子，在里面留下付费购买的信息，借此点对点的吸引对该资源有着特定需求的少数用户。
包括草榴和杏吧在内的色情网站，对于这些产业链上游的单位急于变现的行为保持既不鼓励亦不反对的态度。毕竟，没有核心内容的持续供给，网站只是一个空空如也的坛子。某色情论坛曾经透露，一名发片员在一年时间里赚了数十万的美金，这位老兄感激网站对他的支持，转手给站方捐赠了五万美金，以示“君以国士待我，我必国士报之”的情谊。
📷

08

杯弓蛇影的情绪

快播的覆灭，是对中国网络色情文化的一次重大打击。
快播在实质上并不主动提供色情内容，但是站长和用户的默契使用，使得快播被赋予了那些特殊情绪凝结而成的共性，当一个以快播播放器窗口为主体的网页被打开时，它也就象征了某种似由窃取而来的快感。
草榴和杏吧的现实处境，或与快播不可同日而语，但是就其文化的传承性而言，它们具有惊人的一致性。
这次，人们之所以忧心忡忡的分享关于草榴、杏吧可能永久关闭的伪劣传闻，委实是恐慌世间再无第二个1024或春暖花开。我在微博上吐槽，称南草榴北杏吧的民间地位有点虚高，因为从功能性出发，只要掌握种子搜索引擎和番号索引数据库两类工具就能完全摆脱对于这些网站的内容依赖，但是很多慕名前来反驳我的“榴友”“杏友”说得也理直气壮：在他们看来，草榴和杏吧的价值在于其兼容并蓄的平等氛围。
以草榴为例，除了注册与非注册的区别，用户之间没有阶级，访问权限也趋于扁平化，近年以来，专注于自拍的版块“达盖尔的旗帜”和崇尚信息自由的“技术讨论区”起色极快，更是营造了乌托邦式的场景。
谁也不曾料到，仅是因为站方心猿意马不太注重管理，这些色情BBS竟然在无意中承载了人们对于粗放型田园平台的全部要求：没有莫名其妙的删帖、没有脸红脖子粗的骂架、没有逼人弃坑的戾气、也没有阿谀奉承的水军。
饱暖方思淫欲，而在淫欲之上，草榴和杏吧偶然融合了关于表达、审美和避世等诉求，进而在中文互联网里树立出了自己的独立品牌，如此究竟福兮祸兮，还很难说。但是，就像俄罗斯诗人马雅可夫斯基所说的那样——“我们感激灯塔，因为它为夜里难以出航的人，用火光照亮前路”——“南草榴北杏吧”的面前，注定泥泞坎坷，而在它的身后，是整整一代受到启蒙的互联网原住民。
祝福草榴，祝福杏吧，祝福我们自己。

**Comment by Noiwex** [comment]
https://www.youtube.com/watch?v=8rsMfZ0DZIc

**Comment by Noiwex** [comment]
> 西方境外势力或脑子不灵的人，想蛊惑青年学生发动民主运动，来获得本国或个人的利益。这种事情可能已在过去发生过，现在也正在发生。西方民主的邪恶已在世人面前展现的淋漓尽致，自食其果的民主国家，在本国定义他们为暴力活动，派警察镇压，死伤惨重。同时把恶果丢向了我们，双标言论下，并说其不民主。其用心之险恶，众人皆知。能蛊惑的只能是正在发生的某些地区，无法扩散，他们现在想发起更深入的进攻，我想，这都是徒劳的。已经受过恶魔的摧残，我们不会再轻信恶魔的话。

lmao you're deluded as hell
get help

**Comment by derekslenk** [comment]
> 
> 
> 西方境外势力或脑子不灵的人，想蛊惑青年学生发动民主运动，来获得本国或个人的利益。这种事情可能已在过去发生过，现在也正在发生。西方民主的邪恶已在世人面前展现的淋漓尽致，自食其果的民主国家，在本国定义他们为暴力活动，派警察镇压，死伤惨重。同时把恶果丢向了我们，双标言论下，并说其不民主。其用心之险恶，众人皆知。能蛊惑的只能是正在发生的某些地区，无法扩散，他们现在想发起更深入的进攻，我想，这都是徒劳的。已经受过恶魔的摧残，我们不会再轻信恶魔的话。

Except how you live does end up mattering to use when you take the stupidest stance against free speech

**Comment by jdgrcom** [comment]
论坛
https://www.hmg520.cc 红玫瑰社区 
视频站
https://www.tyjr.info 童颜巨乳  
https://www.zguifldh.com 醉鬼福利
http://www.fltv.buzz/  福利TV
https://www.mhnvl.com 梦幻女郎   
https://www.hmglt.pw 黑玫瑰影院

**Comment by tyjr520** [comment]
论坛
https://www.hmg520.cc 红玫瑰社区
视频站
https://www.tyjr.info 童颜巨乳
https://www.zguifldh.com 醉鬼福利
http://www.fltv.buzz/ 福利TV
https://www.mhnvl.com 梦幻女郎
https://www.hmglt.pw 黑玫瑰影院

**Comment by khoirulo** [comment]
草榴社区1024邀请码，2026获取地址，保真包成功：https://t.me/xiaocao_1024_bot
