### ISSUE TITLE
language syntax highlighting lost after compare files

### ISSUE THREAD

**Issue by Yann82** [notepad-plus-plus/notepad-plus-plus#747]
1 - create 2 tabs with, for example, the word 'select' in each of them
2 - select the menu 'Language/S/SQL' for each of them, syntax highlighting is ok
3 - compare the 2 files (Alt + D)
4 - clear the results (Ctrl + Alt + D)
=> no more syntax highlighting, you need to recreate new tabs to get it

**Comment by Yann82** [comment]
Notepad ++ 6.8.1 but same behaviour in olders versions

**Comment by dail8859** [comment]
You'll want to report it over [here](http://sourceforge.net/p/npp-compare/bugs/) since it is an issue with the plugin itself. And also make sure you are using the latest version of the plugin.

**Comment by Yann82** [comment]
Sorry, I did not see the page about the compare plugin...

**Comment by informatorius** [comment]
Try with latest ComparePlugin from
https://bitbucket.org/uph0/compare/downloads
ComparePlugin.v1.5.6.6.bin.zip
