### ISSUE TITLE
A perfect demonstration of free speech

### ISSUE THREAD

**Issue by andoryu-** [notepad-plus-plus/notepad-plus-plus#7471]
Please keep the issues open as a perfect demonstration of free speech

**Comment by wakroa** [comment]
陰謀
[重要訊息 o macaco cantador](https://youtu.be/jjbZ3R3Sp-E)
永恒的生命

**Comment by Nic8895** [comment]
Agreed. 

They can't shut us up. 

Closing the "Issues" just tells them they've won.
