### ISSUE TITLE
Not a real issue, just a message for Donho

### ISSUE THREAD

**Issue by Faunsce** [notepad-plus-plus/notepad-plus-plus#7473]
Basically not a code issue but @donho if you really want to help talk about china. there already exists a large repository here on github all about the hongkong incident and the promotion of awareness around it. if you could give that repo a shoutout in order to help its campaign to boost awareness on the aggressiveness and wrongdoings of china it would be greatly appreciated. heres the repo, https://github.com/caffeine-overload/bandinchina

**Comment by Faunsce** [comment]
it also has a website thats a bit messy after a recent 32 commit PR o-o https://caffeine-overload.github.io/bandinchina/

**Comment by MeiWithHongKong** [comment]
I'm also running https://github.com/taibangle/awesome-china

The repo also features a "Wall of Shame", along with information about the Hong Kong protests, Xinjiang Concentration Camps, Organ Harvesting, as well as the horrific history of the CCP that has been censored in China. The repo is primarily intended to be shared with those living in China so it's not 100% English.
