### ISSUE TITLE
别给他增热度了

### ISSUE THREAD

**Issue by loveyanbei** [notepad-plus-plus/notepad-plus-plus#7474]
既然人家支持新疆维吾尔独立，
那只要是个支持统一的中国人就别用这死妈玩意的软件就好了。
人家又不欠你的，你们再骂他与他何干？
当然，我认为这作者妈妈死了。

**Comment by dongyingt** [comment]
主要是蛊惑人心，废青那帮傻子这么容易被蛊惑。还好国家教育到位，我相信平安无事，不会影响到我们的生活。看评论就能看出来，里面有西方境外势力，台独等在里面。把github当政治工具了，那不封他还了得。

**Comment by VitaminV9** [comment]
I'm so sorry!
This man can't represent Chinese!
Just the government’s brainwashing is not easy to resist!

**Comment by wakroa** [comment]
陰謀
[重要訊息 o macaco cantador](https://youtu.be/jjbZ3R3Sp-E)
永恒的生命

**Comment by VitaminV9** [comment]
And we don't have right to talk about any negative thing about Chinese government. I even need to sign up for a new account, to leave comments here.
I believe most of Chinese programer support you @donho !
Thanks for speaking for Chinese people!

**Comment by tkmmot321** [comment]
> 
> 
> 主要是蛊惑人心，废青那帮傻子这么容易被蛊惑。还好国家教育到位，我相信平安无事，不会影响到我们的生活。看评论就能看出来，里面有西方境外势力，台独等在里面。把github当政治工具了，那不封他还了得。

建議你先把身邊的程序員帶離github吧，自己不爽的就叫西方勢力。身邊的程序員不肯回來麻煩往死裏打吧。國家不允許技術外流

**Comment by fuckkina** [comment]
支那贱畜们有本事别上GitHub啊，贱不贱！
