### ISSUE TITLE
Message to brainwashed western people living under evil capitalism regime

### ISSUE THREAD

**Issue by cszongyang** [notepad-plus-plus/notepad-plus-plus#7476]
Michael Parenti, in his book “The Assassination of Julius Caesar”, utterly destroyed the Western idealism in Democracy by pointing out the utter restrictive constructs the wealthy imposed on the masses to have their voices heard. Julius was assassinated due to his land reforms, debt forgiveness, and overall advocation of the masses. Their history was narrated by elites, and their system of government is only a reflection of their oligarchical powers portrayed as “freedom.” We seen it in the founding of the United States, where the slave-owning founding fathers did not allow anyone except land owning white men to vote, while capitalizing on populist rhetoric of freedom, liberty, and democracy. And yet still today, votes are being repressed, gerrymandered, and corrupted. Lobbyists are a legal venue to corrupt “elected” politicians while the masses suffer from horrendous debt, healthcare, income inequality, and education. Millions homeless and go hungry in the wealthiest nation in the world. To epitomize these contradictions, they want people to believe China is a failure for lifting 800 million from poverty in a span of a generation. The Soviet Union, from feudal beginnings to space-exploring superpower, failed. Burkina Faso and their vaccination of millions of children and deforestation, women’s liberation efforts failed. Cuba’s medical/scientific accomplishments and standard of living increase while having a trillion dollar blockade failed. The list can go on. Western democracy is an illusion for the masses to promote and sustain the power of the rich. I'd rather have a dictatorship of the proletariat, one party, one body, putting the people first.

**Comment by Stb-Lex** [comment]
Congratulation, 100 points have been added to your social credit score. You now can:
- Take the plane
- Take the train
- Have a 5% discount on gasoline

**Comment by cszongyang** [comment]
> Congratulation, 100 points have been added to your social credit score. You now can:
> 
> * Take the plane
> * Take the train
> * Have a 5% discount on gasoline

the social score thing is simply a propaganda, western people are brainwashed by media backed by oligarchy capitalists.

**Comment by VitaminV9** [comment]
> > Congratulation, 100 points have been added to your social credit score. You now can:
> > 
> > * Take the plane
> > * Take the train
> > * Have a 5% discount on gasoline
> 
> the social score thing is simply a propaganda, western people are brainwashed by media backed by oligarchy capitalists.

I just want to know, why your government blocking so many websites, and the Western government has not.

**Comment by VitaminV9** [comment]
> You are on an U.S/western platform. If you hate us so much why are you on GitHub? Go bother someone else.

Don't say that, that violates freedom.

**Comment by cszongyang** [comment]
> Can't reproduce. Please close.

the bug is so obvious, you are just pretending to be blind. that doesn't solve any problem, you will the see the production break every few years.

**Comment by clavinet** [comment]
> > Congratulation, 100 points have been added to your social credit score. You now can:
> > 
> > * Take the plane
> > * Take the train
> > * Have a 5% discount on gasoline
> 
> the social score thing is simply a propaganda, western people are brainwashed by media backed by oligarchy capitalists.

you won't liberate anyone by spouting lies

**Comment by NotAWorkAccount** [comment]
Yeah the western world isn't perfect, we've had our fair share of disappointing times in history. But at least I won't be killed for mentioning Vietnam, unlike a particular Square...

**Comment by cszongyang** [comment]
> I find it hilarious that you're calling Western Democracy a dictatorship of the rich, when the people are allowed to vote for who they want to be Prime Minister, President, etc. And by people, I mean everyone, the rich, the poor, the proletariat, etc; they're all allowed to vote for whomever they please. Democracy as a form of government is not a dictatorship in any shape or form.
> 
> AND SPOILER ALERT, THE UNITED STATES ARE A FEDERAL REPUBLIC AS OF MARCH 4TH OF 1789.
> Which is also not a dictatorship of the rich!
> 
> Also wouldn't it be better for the Chinese if America was truly a dictatorship of the rich since globalism already has so many former American companies in China? It's ironic how you call yourselves communist when you are more capitalist than the United States.
> 
> It's hilarious that a 'communist' country is allowing American companies in. So now if anything the People's Republic of China is now accelerationist as opposed to Communist.
> 
> On another note, the only thing being 'liberated' by China is American Jobs, because Capitalists don't like Taxes, and the PRC, ironically does not tax the 'rich' enough.
> 
> Also why is a political issue, an issue with notepad++? Did everyone get super petty suddenly?
> 
> Also do you even know what happened at Tianamen Square on that fateful day in June of 1989? Please inform me, because I could swear my 'dictatorship of the rich' could be telling me otherwise!

The key to the problem is the commonality nature of the authority. just need to ensure that the recruitment of members of this group is not exclusive to the masses of the people, equal opportunities for selection and promotion, and absolute control over capital and other forces to ensure that policies are not affected.

that brought you Chinese communist party. At this point I doubt the Chinese communist party is still a "party" in western sense, just imagine this, the name CCP is gone, and changed to another structure recognized by constitution. What's the difference? its membership is not exclusive to any PRC citizen.

Voting democracy has shown its deficiency in recent years and has become religious -- an ideology needs to be protected. I don't even think the concept of party itself should exist in the future. the Party thing, whether you let it exist or not, it will exist anyway. The real parties of China are the factions within the CCP itself. But Western politics has turned party competition, which should have been suppressed, into institutional explicit competition, which is not wise to me as ideally all people should united working together towards a common goal. The voting democracy is a very premature politics. In history, the nomadic tribes in the grasslands of Inner Asia had voting politics. There was a parliamentary organization, major tribe leaders will vote for what should be decided. If China abandons the complicated technocratic system that has been developed for thousands of years, in my opinion it will be retrogressive to use this premature voting democracy political system.

Some people say that parties are there to ensure that the issues is objectively reflected, and that a full debate can be guaranteed to ensure that all interests are not infringed. I don't find it to be correct. CCP has intense internal debate with major decisions. In the west, The seats in the parliament can be bought with various forces such as capital. The existence of the party cannot guarantee the commonality feature of the authority.

For the tiananmen square thing, if I say there is no one died INSIDE Tiananmen square, do you believe it? obviously no because you are so brainwashed by media. check this https://www.telegraph.co.uk/news/worldnews/wikileaks/8555142/Wikileaks-no-bloodshed-inside-Tiananmen-Square-cables-claim.html
see the protests going on worldwide now? they are not different from Tiananmen incident. but western media describe it as massacre.

**Comment by Musketmarine** [comment]
> > I find it hilarious that you're calling Western Democracy a dictatorship of the rich, when the people are allowed to vote for who they want to be Prime Minister, President, etc. And by people, I mean everyone, the rich, the poor, the proletariat, etc; they're all allowed to vote for whomever they please. Democracy as a form of government is not a dictatorship in any shape or form.
> > AND SPOILER ALERT, THE UNITED STATES ARE A FEDERAL REPUBLIC AS OF MARCH 4TH OF 1789.
> > Which is also not a dictatorship of the rich!
> > Also wouldn't it be better for the Chinese if America was truly a dictatorship of the rich since globalism already has so many former American companies in China? It's ironic how you call yourselves communist when you are more capitalist than the United States.
> > It's hilarious that a 'communist' country is allowing American companies in. So now if anything the People's Republic of China is now accelerationist as opposed to Communist.
> > On another note, the only thing being 'liberated' by China is American Jobs, because Capitalists don't like Taxes, and the PRC, ironically does not tax the 'rich' enough.
> > Also why is a political issue, an issue with notepad++? Did everyone get super petty suddenly?
> > Also do you even know what happened at Tianamen Square on that fateful day in June of 1989? Please inform me, because I could swear my 'dictatorship of the rich' could be telling me otherwise!
> 
> The key to the problem is the commonality nature of the authority. just need to ensure that the recruitment of members of this group is not exclusive to the masses of the people, equal opportunities for selection and promotion, and absolute control over capital and other forces to ensure that policies are not affected.
> 
> that brought you Chinese communist party. At this point I doubt the Chinese communist party is still a "party" in western sense, just imagine this, the name CCP is gone, and changed to another structure recognized by constitution. What's the difference? its membership is not exclusive to any PRC citizen.
> 
> Voting democracy has shown its deficiency in recent years and has become religious -- an ideology needs to be protected. I don't even think the concept of party itself should exist in the future. the Party thing, whether you let it exist or not, it will exist anyway. The real parties of China are the factions within the CCP itself. But Western politics has turned party competition, which should have been suppressed, into institutional explicit competition, which is not wise to me as ideally all people should united working together towards a common goal. The voting democracy is a very premature politics. In history, the nomadic tribes in the grasslands of Inner Asia had voting politics. There was a parliamentary organization, major tribe leaders will vote for what should be decided. If China abandons the complicated technocratic system that has been developed for thousands of years, in my opinion it will be retrogressive to use this premature voting democracy political system.
> 
> Some people say that parties are there to ensure that the issues is objectively reflected, and that a full debate can be guaranteed to ensure that all interests are not infringed. I don't find it to be correct. CCP has intense internal debate with major decisions. In the west, The seats in the parliament can be bought with various forces such as capital. The existence of the party cannot guarantee the commonality feature of the authority.
> 
> For the tiananmen square thing, if I say there is no one died INSIDE Tiananmen square, do you believe it? obviously no because you are so brainwashed by media. check this https://www.telegraph.co.uk/news/worldnews/wikileaks/8555142/Wikileaks-no-bloodshed-inside-Tiananmen-Square-cables-claim.html
> see the protests going on worldwide now? they are not different from Tiananmen incident. but western media describe it as massacre.

Do you have any further sources on the Tianamen Square incident?

Also who's paying Wikileaks?

**Comment by WyattAutomation** [comment]
Hey look, the Triads are on GitHub comments now.  Who'd have thought a country that calls themselves "Communist" but has an open door to companies like Walmart would have a propaganda machine fueled by organized crime?

**Comment by marekr** [comment]
> You are on an U.S/western platform. If you hate us so much why are you on GitHub? Go bother someone else.

The joke is, there are basically Chinese GitHub clones but yet they don't use it for some reason. Maybe not enough freedoms?

**Comment by rkram5424** [comment]
> Can't reproduce. Please close.

I think they did away with that law. But you just need a certain social score to have kids now.

**Comment by atlc** [comment]
MIcHaEl⚡pARenTi,🍎In⛲HIS🌽BoOk🌠“THE🌎ASSASsINATion🔬of🛤️JuLIuS🍿caEsAR”,♦️UTTERlY✖️deSTroYEd🖋️the🐨weSTern😘IDEALISm⤵️iN🛌DemOcRacy📘By💁‍♀️poiNTinG📕oUT😊THE3️⃣UTter🏡rEstRictIVe🉑coNSTRuCts🛳️tHe🥫wealTHY🤥impoSEd3️⃣oN🏠tHe⚪mAssES🐷tO👨‍👧‍👦HAvE🥙ThEiR🤷‍♀️vOiCES💣heard.👩‍🚀juLIuS🗳️wAS❔aSSAssINaTEd🤷‍♀️dUE🛩️TO👩‍❤️‍💋‍👩hIs👨‍👨‍👧‍👧lAnd👩‍🏫refoRMs,🥘dEBT🌅FORGIVENesS,🌘And🏺overAlL🐗AdvOcAtIoN🖲️oF👩‍🎨The🆙maSSeS.🔗tHeir🏃‍♂️HIStOry🎳WAS⚖️NaRrATeD🥋by👒ELItES,🌰aND🌛THeir🐈systeM🦐oF😇GOverNMENT🏣is🕠oNly💦A👩‍🏫ReFLecTiOn😭Of🤫ThEIr🚶‍♀️OlIGArChiCAl🕍poweRS🌵PoRTrayEd🚆as🌹“FREEDOM.”📶wE🙃SEen🕯️iT🎦In🧘‍♀️the💞FounDIng🎵Of🤕THE🍒United🍗sTAtES,🔮WHerE🗼tHE🕊️SlAvE-oWnING🕛FoUNDINg🤣fATHErS😭diD🚢NOt🔱aLlOw😧aNYOne🔐exCePT🥔LAND📁Owning📗whitE💩Men🐮to🕠VOTE,🛒wHIlE🙇‍♂️CapITaLizINg🐲On🕕poPUlist💰RhEToRiC🚈of💘frEedOm,🦄lIBerTy,🦗aND📪DeMoCracY.🚈aNd🏯yEt👓STIlL👨‍👧‍👦TODAY,🔃votes📰Are🍁BeINg💣repreSSED,📭GeRrymANderED,🏢aND🚜CoRRUptED.♦️LOBbyISts☕arE#️⃣a🐘legAl🔑vENuE🚐to👩‍👧‍👧cORRUPt🌖“elEcted”🍎PoLItIcIanS💟wHIle👩‍👩‍👦thE⬜MaSSEs💃SuFfeR☘️FRom💇‍♂️HORRendoUS🗂️Debt,😔HeaLTHcAre,🙉iNCoME🍪INeqUaLITy,👜aND👯‍♀️edUCation.👫MiLLIonS🖤HoMElESs👨‍👩‍👧ANd🍾go🐵HungRy🎬In🛤️tHe🎱WeaLthIest🧜‍♂️NAtiON🐐IN☕THe📒worLd.🛎️To🈚EpITomIZe🔥tHesE👨‍👩‍👧‍👧ConTraDICtIoNs,🗒️thEY🥄WANt👌peOPle😒TO♐BeLiEVe🤣cHina🆗IS🚉A🥌FaIlURe🕒fOR🕸️lifTInG™️800📪MiLLiOn😬froM📛poVeRTY🐎IN🍵A🚯SpaN🍵oF🤾‍♀️a🥡generatioN.🌩️THe🈶sOVIeT👨‍👧‍👦uNIoN,📧frOM👴feudAl👨BeGInNIngS🏄‍♀️TO⤵️spACe-exPlOrING💵sUPerpOwEr,🚊faIled.🧘‍♀️buRKinA🤹fASo🏏aNd❕THEIr🌁vaccinaTioN🚏Of🍘MiLliONS🏩of👳‍♀️ChILdrEn🐚anD⚙️dEFoREsTAtioN,🚍wOMeN’s⚓lIberAtiON✒️EFfoRTs🏾fAilEd.🌖cuba’s⚛️meDIcaL/scIEnTiFiC▫️AcComplishmENtS🌪️and🆓STanDard🆑oF👩‍👦livINg🛅InCreaSe☺️wHIle💐haviNG🔥A🛰️trIlLion😌DolLaR🥟bLoCkAde🤴fAIleD.🍺tHe👩‍🚒liST🧘‍♀️CAn🥛GO🎻On.👐WESTErN🥘DEmocrACy👓IS🗾AN🙏illusiON😲FoR🗝️thE🔛MasseS🏌️‍♂️tO👨‍🎤prOMOtE🗂️And🔊SUStAiN🐘The👆pOWER👋of🌵thE🆕RIch.☔I'd✡️raThEr🌪️hAve♍A🎏DICtaTORShip🛢️OF✝️The🌄PRolEtaRIat,🕦onE🦅PartY,🎱oNe🍄bodY,🗒️PUTtiNg🐙THe2️⃣PEOPlE💻First.👩‍⚖️🚺👍🔪1🈴👎🤸31⛷️😄⛺6🤽😕👰2

**Comment by ajloveslily14** [comment]
动态网自由门天安門天安门法輪功李洪志FreeTibet六四天安門事件TheTiananmenSquareprotestsof1989天安門大屠殺TheTiananmenSquareMassacre反右派鬥爭TheAnti-RightistStruggle大躍進政策TheGreatLeapForward文化大革命TheGreatProletarianCulturalRevolution人權HumanRights民運Democratization自由Freedom獨立Independence多黨制Multi-partysystem台灣臺灣TaiwanFormosa中華民國RepublicofChina西藏土伯特唐古特Tibet達賴喇嘛DalaiLama法輪功FalunDafa新疆維吾爾自治區TheXinjiangUyghurAutonomousRegion諾貝爾和平獎NobelPeacePrize劉暁波LiuXiaobo民主言論思想反共反革命抗議運動騷亂暴亂騷擾擾亂抗暴平反維權示威游行李洪志法輪大法大法弟子強制斷種強制堕胎民族淨化人體實驗肅清胡耀邦趙紫陽魏京生王丹還政於民和平演變激流中國北京之春大紀元時報九評論共産黨獨裁專制壓制統一監視鎮壓迫害侵略掠奪破壞拷問屠殺活摘器官誘拐買賣人口遊進走私毒品賣淫春畫賭博六合彩天安門天安门法輪功李洪志WinniethePooh劉曉波动态网自由门

**Comment by gsarpy** [comment]
> the bug is so obvious, you are just pretending to be blind. that doesn't solve any problem, you will the see the production break every few years.

Thanks for coming here and _freely_ expressing your opinion. Don't worry, we might disagree entirely but nobody is going to sentence you to hard labor for the rest of your life over your freedom of expression. Sleep peacefully, my friend.

**Comment by spookyUnknownUser** [comment]
> For the tiananmen square thing, if I say there is no one died INSIDE Tiananmen square, do you believe it? obviously no because you are so brainwashed by media. check this https://www.telegraph.co.uk/news/worldnews/wikileaks/8555142/Wikileaks-no-bloodshed-inside-Tiananmen-Square-cables-claim.html
> see the protests going on worldwide now? they are not different from Tiananmen incident. but western media describe it as massacre.

Yup its because nothing happened June 4th that everyone is super chill talking about June 4th right?

https://vimeo.com/44078865

**Comment by shadow7483147** [comment]
Congratulations, you’ve found out that the world has problems all over the place. 

That does not invalidate movements to correct such problems, however. We need to simply take this one step at a time.

**Comment by Probe1** [comment]
Finally we have defeated the CEO of Capitalism by shitposting in a n++ issue.

**Comment by WyattAutomation** [comment]
I consider myself fairly left leaning and supportive of candidates and politicians in the US that identify as "Democratic Socialists"; I'm a big time Bernie and AOC supporter etc so I don't at all disagree that yes, America has terrible flaws and massive problems with corruption.  Our Government has done some very shameful things, this is undeniable.

To those from China, defending the Chinese government here:

Let's float a hypothetical idea and assume you are all 100% correct about everything that you've said here.  Let's assume that we in the US are in fact being brainwashed and everything that we have heard that we are complaining about is all lies.

Is China actually a perfect Utopia?  If it is not, (which no country in the world is perfect) and there are some problems that you think China needs to work on, that we as Americans may not be aware of, what are those problems?

I suppose my question is, are you capable of criticising the Chinese government at all?  If you are not, and you can't out of fear or whatever other reason, then how do you expect any of us to believe anything you are saying?  Why would we believe the words of someone who is incapable of any inward criticism at all?  

The inability to self-criticize exposes an immense flaw, and a gaping weakness in the integrity of any of the counter-information that has been shared.  Nearly all of the Americans here are well aware and quite vocal and critical of the wrongdoings of the US.  If we are to believe you, then please, share with us some of the flaws that actually DO exist with the Chinese government.  

It's foolish to think that we are actually going to believe that there isn't *something* that you feel could be improved regarding the Chinese government.  If it isn't as horrible as we claim it is, please feel free to prove that via some form of inward criticism.  Freedom of expression is something we value quite dearly in the US.  If you do not have that I have trouble believing anything you tell us "isn't true".

**Comment by crispinb** [comment]
1. Don't confuse "The West" with the US. Most of us in the former fear & dislike the latter, although we have a grudging regard for some of its entertainment (music, films, politics).
2. Please submit a PR to fix any specific issues you ascertain.

**Comment by eioo** [comment]
Just came by to say hi. Hi! :-)

**Comment by Usama-Tahir** [comment]
> Can't reproduce. Please close.

works fine on my machine.

**Comment by WyattAutomation** [comment]
I think the silence speaks volumes here, per what I said in my original comment.  If we are to believe you (that we are being lied to about China), then say something critical of the Chinese government.  It doesn't have to be one of the things that we are critical of; just say literally *anything* critical about the Chinese government.  If we are to assume YOU aren't brainwashed--be that due to fear or fanaticism--then prove it.
