### ISSUE TITLE
R.I.P. Mods who have to clean this up.

### ISSUE THREAD

**Issue by sntrenter** [notepad-plus-plus/notepad-plus-plus#7479]
### Description of the Issue
Spam

### Steps to Reproduce the Issue
1. go to issues

### Expected Behavior
actual issues

### Actual Behavior
Spam from Chinese nationalists

**Comment by Z-Y00** [comment]
hi, I guess someone could write  @donho donho a script,  something automatically filters out the issues that does not fill in the issue template, I guess a simple thing like this would works great

**Comment by rubyFeedback** [comment]
No, don't do that. This is not solely about "chinese nationalists".

I read on reddit that Donho was also abusing downstream user and auto-filling stuff on their computer after charlie hebdo.

He is using notepad++ as political platform. It should be an editor, not a political tool no matter what opinion anyone has. And that has nothing to do with political stuff per se.

By the way on that note - while the chinese mono party is cowardly and idiotic, the uighurs in particular resorted to violence too including killing people. So you can not have a "clean" stance in this debate when you pick a side, even less so via a FUCKING EDITOR.

**Comment by Z-Y00** [comment]
> He is using notepad++ as political platform. It should be an editor. not a political tool no matter what opinion anyone has
If you do believe so, then just filter out the issues and close them would help the issue function return back to normal.

**Comment by sntrenter** [comment]
could someone provide a source for the hebdo stuff? All I'm seeing is Hearsay.

**Comment by frankuyan** [comment]
most of comments came from  chinese bots instead of actual users.  Most accounts were created fairly recently with zero commit history
