### ISSUE TITLE
Add Winnie the pooh to the logo

### ISSUE THREAD

**Issue by GjeloshajAntoine** [notepad-plus-plus/notepad-plus-plus#7480]
Hey I love what you do!
Go on!!!
And having a Winnie-the-Pooh customized logo would be the ice on the cake hihi

**Comment by pinobatch** [comment]
To keep Notepad++ free software, this issue will probably have to be put on hold until December 31, 2046. (This is the end of the 70th Gregorian calendar year after the death of illustrator E. H. Shepard in 1976.)

**Comment by jhpratt** [comment]
@pinobatch It _may_ be possible to get explicit permission, though I suspect it would be denied.

**Comment by marekr** [comment]
Maybe Southpark would be more open to collaborating.
