### ISSUE TITLE
Reputation of Notepad++

### ISSUE THREAD

**Issue by rubyFeedback** [notepad-plus-plus/notepad-plus-plus#7482]
In the past this was an editor.

Since some years it has turned into a political meme part.

I suggest to drop the political agenda and focus on the editor; or alternatively, if you don't want to work on notepad++ anymore, to officially hand it over to other people who can handle the project better than you can. I recently read on reddit that you controlled remote computers after charlie hebdo. This is by definition a trojan.

Something has to change. Notepad++ deserves a new main developer.

**Comment by Loys** [comment]
> Something has to change. Notepad++ deserves a new main developer.

Thank you for your opinion, i am thinking exactly the opposite !
I loved the "gilets jaunes" edition ! 
And i guess, the free-Uyghur edition will be another great vintage 😄
People need to think more about their political environment, this we can overcome "brexit" and "trump" issues !

**Comment by botto** [comment]
Sorry @rubyFeedback but I disagree, it's important to high light issues that impact people wherever it is happening in the world.  
Because we can't rely on people in power to raise their voice and do the right thing, as developers this is our last resort.

**Comment by sproket** [comment]
Found the member of the CCP. Go climb back under your rock.

**Comment by dudalev** [comment]
To me, the reputation of Notepad++ has skyrocketed today

**Comment by Raymonf** [comment]
>I recently read on reddit that you controlled remote computers after charlie hebdo

Never happened. Please cite your sources.

>I suggest to drop the political agenda

They're a few political easter eggs. Fork the project if you want to take be the new "main developer".

>if you don't want to work on notepad++ anymore

The author literally released a new version 2 days ago. What are you even talking about?

**Comment by Donavan** [comment]
You couldn't be more wrong.  Feel free to fork and release your own "yay oppression" version

**Comment by britmob** [comment]
LOL. Their reputation has only increased in my eyes! I love seeing winnie the pooh fire up all his spambots. Really shows how scared of criticism he is. 

PUT AN END TO CHINESE RE-EDUCATION CAMPS! FREE TIBET!

**Comment by clavinet** [comment]
> In the past this was an editor.
> 
> Since some years it has turned into a political meme part.
> 
> I suggest to drop the political agenda and focus on the editor; or alternatively, if you don't want to work on notepad++ anymore, to officially hand it over to other people who can handle the project better than you can. I recently read on reddit that you controlled remote computers after charlie hebdo. This is by definition a trojan.
> 
> Something has to change. Notepad++ deserves a new main developer.

If you don't like the author voicing his opinions, you can stop using Notepad++ anytime, nobody's forcing you to use it.

**Comment by jflycn** [comment]
I have a great idea for CCP: tell Huawei to form a team of coders, make a better text editor, wait it gets popular, and then, boom! Make a pro-concentration-camp release. And then, boom! Make a pro-massacre release. 

This will definitely cancel out all the negative impact from Notepad++.

**Comment by i509VCB** [comment]
> Something has to change. Notepad++ deserves a new main developer.

Notepad++ is GPL, if you dislike the current developer, fork it and continue yourself or with a new team.

**Comment by Jan200101** [comment]
While I also don't want politics in my software it has slowly injected itself in like a cancer
N++ is one of those projects that actually does it right

**Comment by marekr** [comment]
> I recently read on reddit that you controlled remote computers after charlie hebdo.

Uh, the fact you say it this way with a complete lack of understanding does not bold well for your intelligence.

**Comment by Kefta** [comment]
In a free market of software (and business in general), people can use their product to advance whatever political stance they please. Users of their product indirectly contribute to that agenda by either continuing to use the product or switching to another if they don't agree. The maintainer has no obligation to keep their product politically neutral.

At the same time, everyone on here dunking on the OP for "supporting oppression" because he wants a politically uninvolved product should probably stop patting themselves on the back for turning a code repository into an ideological echo chamber. It's really immature and unproductive.

**Comment by marekr** [comment]
>At the same time, everyone on here dunking on the OP for "supporting oppression" because he wants a politically uninvolved product should probably stop patting themselves on the back for turning a code repository into an ideological echo chamber. It's really immature and unproductive.

Welcome to the angry internet mob, please take a pitchfork and join in.

**Comment by prodigic** [comment]
too much gatekeeping from the ccp knobends. great job. looking forward to the Epstein homicide edition

**Comment by michaellee8** [comment]
If you don't like this edition, you may easily start your own fork on GitHub or on your illegal and unethical GitHub clone called Gitee (if you can write proper C++) and see if your Chinese friends who cannot even write proper English would like to contribute to it. The author is writing and publishing software for FREE here, you didn't even pay him any money, why would you have a say on what he does on his software.

You can just uninstall your apps and leave this project as you like, you are not even a customer, you are just taking advantage things created and shared by others like those Chinese who watch pirated NBA live streams and says that you would like to boycott it, what a joke.
