### ISSUE TITLE
The Tiananmen Square protests of 1989

### ISSUE THREAD

**Issue by Nic8895** [notepad-plus-plus/notepad-plus-plus#7486]
### Description of the Issue
China thinks it can do whatever the hell it wants, and the rest of the world should just shut the fuck up about it. 

### Steps to Reproduce the Issue
动态网自由门 天安門 天安门 法輪功 李洪志 Free Tibet 六四天安門事件 The Tiananmen Square protests of 1989 天安門大屠殺 The Tiananmen Square Massacre 反右派鬥爭 The Anti-Rightist Struggle 大躍進政策 The Great Leap Forward 文化大革命 The Great Proletarian Cultural Revolution 人權 Human Rights 民運 Democratization 自由 Freedom 獨立 Independence 多黨制 Multi-party system 台灣 臺灣 Taiwan Formosa 中華民國 Republic of China 西藏 土伯特 唐古特 Tibet 達賴喇嘛 Dalai Lama 法輪功 Falun Dafa 新疆維吾爾自治區 The Xinjiang Uyghur Autonomous Region 諾貝爾和平獎 Nobel Peace Prize 劉暁波 Liu Xiaobo 民主 言論 思想 反共 反革命 抗議 運動 騷亂 暴亂 騷擾 擾亂 抗暴 平反 維權 示威游行 李洪志 法輪大法 大法弟子 強制斷種 強制堕胎 民族淨化 人體實驗 肅清 胡耀邦 趙紫陽 魏京生 王丹 還政於民 和平演變 激流中國 北京之春 大紀元時報 九評論共産黨 獨裁 專制 壓制 統一 監視 鎮壓 迫害 侵略 掠奪 破壞 拷問 屠殺 活摘器官 誘拐 買賣人口 遊進 走私 毒品 賣淫 春畫 賭博 六合彩 天安門 天安门 法輪功 李洪志 Winnie the Pooh 劉曉波动态网自由门

### Expected Behavior
1. Vehement Denial
2. "Western Pigs!"
3. "Capitalist Dogs!"
4. "You know nothing, you aren't here!"

### Actual Behavior
1. Vehement Denial
2. "Western Pigs!"
3. "Capitalist Dogs!"
4. "You know nothing, you aren't here!"
5. American and European companies caving to China's demands

### Debug Information
1. Realize China controls China, that's it.
2. Realize the rest of the world doesn't give a fuck if you think you own HK
3. Realize Winnie the Pooh is just a cartoon character, and your president's reaction to the comparison shows just how insecure he really is. 
4. Get your shit together.

**Comment by DundarGoc** [comment]
![tian](https://user-images.githubusercontent.com/33953936/67896673-21da5d80-fb5d-11e9-9556-45f7383e88fe.jpg)

**Comment by feihongmeilian** [comment]
一群傻逼东西，写不好程序蹦跶出来搞你妈的政治，弱智

**Comment by leo19941227** [comment]
別生氣，別生氣，生氣給魔鬼留地步

**Comment by woann** [comment]
写程序就好好写程序，喜欢参与政治就去选举，去上街，不要写个程序还想着政治。

你真以为你看到了什么不得了的真相？就你们西方媒体还没高清事实就开始抹黑的那套，在37个越南人身上不是已经用过了？你眼瞎没看到吗？虽然逝者已矣，但是你们的媒体真的恶心人，你知道不？

**Comment by woann** [comment]
看看现在的乌克兰，就是你台湾未来的下场

**Comment by xtsm** [comment]
写程序就好好写程序，喜欢参与政治就去选举，去上街，不要写个程序还想着政治。

你真以为你看到了什么不得了的真相？就你们西方媒体还没高清事实就开始抹黑的那套，在37个越南人身上不是已经用过了？你眼瞎没看到吗？虽然逝者已矣，但是你们的媒体真的恶心人，你知道不？

**Comment by xtsm** [comment]
诅咒，我搞砸了，我怎么能删除消息？
请习领导不要拿走我宝贵的社会信用分，这不会再发生了

**Comment by UjuiUjuMandan** [comment]
写程序就好好写程序，喜欢参与政治就去选举，去上街，不要写个程序还想着政治。

你真以为你看到了什么不得了的真相？就你们西方媒体还没高清事实就开始抹黑的那套，在37个越南人身上不是已经用过了？你眼瞎没看到吗？虽然逝者已矣，但是你们的媒体真的恶心人，你知道不？

**Comment by UjuiUjuMandan** [comment]
朋友是一个坚韧不拔的纪录片，在香港这座城市的设置。
