### ISSUE TITLE
 cannot download notepad++

### ISSUE THREAD

**Issue by radische** [notepad-plus-plus/notepad-plus-plus#7488]
### Steps to Reproduce the Issue

1. 
2. 
3.

**Comment by malytomas** [comment]
For example: download.notepad-plus-plus.org/repository/7.x/7.8.1/npp.7.8.1.Installer.x64.exe this url does not work for me either.

**Comment by dartraiden** [comment]
Apparently, this is somehow related with the fact that the site is under Cloudflare DDpS protection.

**Comment by CounterPillow** [comment]
You've got the butthurt Chinese bots to thank for that one.

**Comment by luisgbm** [comment]
I can confirm this issue as well. Download from Softpedia, for now

**Comment by AyrA** [comment]
May I suggest to the dev to add the binaries to Github releases in the future?
Doesn't costs anything and hotlinking is possible.
Could turn the current download server into a backup repository.

**Comment by donho** [comment]
Due to the latest release our server has reached the bandwidth limit.
I just upgraded the server and the bandwidth is also increased.
It should be OK now.

**Comment by Neurotoxin001** [comment]
download.notepad-plus-plus.org is still down.

**Comment by xylographe** [comment]
@Neurotoxin001 
I downloaded `http://download.notepad-plus-plus.org/repository/7.x/7.8.1/npp.7.8.1.bin.zip` without any problem, less than 5 minutes ago. Perhaps, your company's servers are blocking the site?

**Comment by Neurotoxin001** [comment]
https://www.uptrends.com/tools/uptime

![image](https://user-images.githubusercontent.com/39812401/69011729-b119aa80-097e-11ea-95df-49e4ab1437ab.png)
![image](https://user-images.githubusercontent.com/39812401/69011738-b70f8b80-097e-11ea-8255-55b2e003d0df.png)

Seems like ddos.

**Comment by milankragujevic** [comment]
![image](https://user-images.githubusercontent.com/7611163/69041816-73ee0080-09f0-11ea-9a76-08549071dc68.png)
![image](https://user-images.githubusercontent.com/7611163/69041825-76e8f100-09f0-11ea-9f57-47458d931b9b.png)

Tried it from my work Internet (AS49402 - Comtrade programske rešitve d.o.o.), it doesn't let me connect to port 80. Traceroute attached, ping works.

![image](https://user-images.githubusercontent.com/7611163/69042036-ce875c80-09f0-11ea-8405-f6dd1d996bd2.png)

Tried it from my home Internet (AS31042 - Serbia BroadBand-Srpske Kablovske mreže d.o.o.), same situation.

**Comment by Neurotoxin001** [comment]
Now it's **ERR_NAME_NOT_RESOLVED**

**Comment by SerErris** [comment]
Same here

**Comment by milankragujevic** [comment]
I have mirrors if anyone needs them, installer for v7.8.1 (64bit and 32bit).

https://projects.milankragujevic.com/notepadplusplus/

They are signed by Notepad++ so you can be sure they haven't been modified by me or anyone else. 

To verify, right click the EXE, select Properties, Digital Signatures, Notepad++, click Details, and verify it is signed by "DigiCert SHA2 Assured ID Code Signing CA".

**Comment by donho** [comment]
https://twitter.com/Notepad_plus/status/1199352636027346944
It should be OK now
