### ISSUE TITLE
Change release name to "Yellow Vests" or "Free Barcelona" 

### ISSUE THREAD

**Issue by MarkoCen** [notepad-plus-plus/notepad-plus-plus#7489]
### Description of the Issue
Since the author is from Europe, it is better to have a more European style release name, such as "Yellow Vests" or "Free Barcelona"

**Comment by MoochMcGee** [comment]
That's stupid. Europeans aren't being mass-detained and mass-brainwashed like the Uyghurs are in China.

**Comment by Hamuko** [comment]
https://notepad-plus-plus.org/downloads/v7.6.2/

Also, since you are from the US, who are you to say what is "European style"? Europe isn't even a country.

**Comment by CounterPillow** [comment]
<img width="304" alt="image" src="https://user-images.githubusercontent.com/308818/67902079-a088c800-fb68-11e9-9c5c-6fae9cbb8a7d.png">

lol

**Comment by MoochMcGee** [comment]
OOOOOF. GET CUCKED, CHINESE SHILLLLLLLLLL

**Comment by Cathbhadh** [comment]
+50c

**Comment by Seedarchangel** [comment]
Which, he already did. 


https://notepad-plus-plus.org/downloads/v7.6.2/

**Comment by marekr** [comment]
> https://notepad-plus-plus.org/downloads/v7.6.2/
> 
> Also, since you are from the US, who are you to say what is "European style"? Europe isn't even a country.

Bwahahaha. Do you think he knows that Gilet Jaune is the correct name for the yellow vest movement?

**Comment by MoochMcGee** [comment]
@MarkoCen Yo, if you mad about this, you gonna be even more ANGERY at this https://notepad-plus-plus.org/news/v664-tiananmen-64-edition/

**Comment by rrttyyu** [comment]
OP gets 50 points in China Social Credit System from posting this.

**Comment by MoochMcGee** [comment]
And -infinity points in my Being a Decent Human Being Credit System

**Comment by CounterPillow** [comment]
And also -50 points for using a site censored in mainland China. [Maybe he should reflect on why the Chinese government wouldn't want its citizens to access Twitter.](https://youtu.be/rWvpvlT9pJU)

**Comment by Mikotochan** [comment]
@MarkoCen Doesn't it feel great that you can live in a country where you can at least speak what's on your mind freely?

> Since the author is from Europe, it is better to have a more European style release name, such as "Yellow Vests" or "Free Barcelona"

Since the author of this issue is from China, it is better to have a more Chinese style name, such as "Shi Jiao" rather than "MarkoCen".

@CounterPillow

I thought that genocide denial was not allowed by twitter's ToS, weird how they selectively apply it.
