### ISSUE TITLE
Comments for asm/Assembly language cannot be customized in langs.xml

### ISSUE THREAD

**Issue by DeyanVasilev** [notepad-plus-plus/notepad-plus-plus#7490]
### Description of the Issue

Line and block comments for Assembly language cannot be changed to anything else but ';'. Actually ';' seems to be a hardcoded comment character no matter what's defined in commentLine, commentStart and commentEnd.

### Steps to Reproduce the Issue

1. In langs.xml set commentLine="//"
2. In NP++ set Comment color to gray for Assembly
3. 

### Expected Behavior

Comment // some comment to be colored gray

### Actual Behavior

Comment // some comment is not colored gray
Instead ; some comment gets colored gray

**Comment by ArkadiuszMichalski** [comment]
@DeyanVasilev Settings in `langs.model.xml` are only for add/remove/toggle comments, does not affect comments handled by the asm lexer. Fortunately this lexer has setting for your own comment:
https://sourceforge.net/p/scintilla/code/ci/default/tree/lexers/LexAsm.cxx#l139
```cpp
DefineProperty("lexer.as.comment.character", &OptionsAsm::commentChar,
	"Overrides the default comment character (which is ';' for asm and '#' for as).");
```
This is new for asm lexer and will be added in Notepad++ after update Scintilla to new version. But setting this option requires an additional plug-in, such as PythonScript.
