### ISSUE TITLE
When 2 lines of code are copied and pasted into the search box, skip the second line.

### ISSUE THREAD

**Issue by AbeAlpha** [notepad-plus-plus/notepad-plus-plus#7491]
### Description of the Issue
When 2 lines of code are copied and pasted into the search box, skip the second line.

The program should paste the two lines into one using the extended search mode (\ n \ r \ t ....).
So if we copy these lines to the clipboard:

>       <DisplayName>AbeAlpha</DisplayName>
>       <CubeGrids>

When you paste them in the search box we would have to paste this:

>       <DisplayName>AbeAlpha</DisplayName>\n      <CubeGrids>

Another way to solve it would be to allow more than one line in the search box, but I would prefer the first solution, since this is how extended expressions are understood when pasting from the clipboard

### Steps to Reproduce the Issue
1. Copy 2 lines of any text
2. Paste on the search box (Control + F)
3. Onli 1 line apers

### Expected Behavior
Paste everything is copied

### Actual Behavior
Only lines :_

### Debug Information
Is just an improvement

**Comment by sasumner** [comment]
Not sure I fully understand.  If you paste multiple line data into the Find-what box, it appears as one line but it is still multi-line.  So is the issue here just one of appearance?

**Comment by sasumner** [comment]
Closing due to lack of interest.
