### ISSUE TITLE
Occupy Wallstreet & Save Afghan

### ISSUE THREAD

**Issue by lushuyu** [notepad-plus-plus/notepad-plus-plus#7496]

**Comment by Yihao-G** [comment]
Now the US troop has left Afghanistan without a single shame and Taliban retakes the country.

The US-led western world eventually didn't eliminate Taliban, brought nothing to the country and the Afghanistan people, but years of wars and chaos.

The female rights in this country has been severely threatened once again and the Uyghur-and-HK-freedom-supportive Notepad++ said literally nothing. What a good play of double standard!
