### ISSUE TITLE
'Move to Recycle Bin' > select 'No' -- "Delete Fail" dialog seems unnecessary

### ISSUE THREAD

**Issue by PalashBansal** [notepad-plus-plus/notepad-plus-plus#7499]
### Description of the Issue
**On selecting 'No' option in 'Move to Recycle Bin' confirmation dialog, user can see that file is still there. So, "Delete file failed" dialog seems redundant.**
Moreover, its a move operation. Also, 'fail' signifies failing to do the intended operation. If a message is meant to be there- Better msg would be "Move file aborted".
Another issue is NPP going to background because of "Delete file failed" dialog. See gif-
![gif](https://user-images.githubusercontent.com/6822117/68085918-2dcf6380-fe6c-11e9-9c77-2c2594d248e3.gif)

### Steps to Reproduce the Issue
1. Keep a file opened in NPP. Open 'File' menu
2. Select 'Move to recycle bin'
3. Select 'No' in the confirmation dialog

### Debug Information
Debug info.-
Notepad++ v7.8.1   (64-bit)
Build time : Oct 27 2019 - 22:57:19
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS Name : **Windows 7** Professional (64-bit) 
OS Build : 7601.23833
Plugins : mimeTools.dll NppConverter.dll NppExport.dll

**Note** that NPP going to background problem is reproducible only in Win7(not Win10)

**Comment by sasumner** [comment]
Your example shows this action being done on file "new 5".  Since it isn't possible to move an "unsaved" file to the recycle bin, probably that action should be disabled in the menus.

**Comment by PalashBansal** [comment]
> Your example shows this action being done on file "new 5".

Actually i saved the file as "new 5"(default NPP given name itself). If you observe, file is saved and tabbar is not highlighted.
Sorry for misleading info, from now on i will raise issues with example having non default filenames.

> Since it isn't possible to move an "unsaved" file to the recycle bin, probably that action should be disabled in the menus.

With unsaved file, 'move to recycle bin' option is already disabled.

**Comment by sasumner** [comment]
@PalashBansal Ah, okay...I definitely think that your example was "tricky". :-)

**Comment by donho** [comment]
I cannot reproduce it on my windows 10.
I suppose it's the OS behaviour, therefore it's not bug in Notepad++

**Comment by PalashBansal** [comment]
> I cannot reproduce it on my windows 10.
> I suppose it's the OS behaviour, therefore it's not bug in Notepad++

I can reproduce the issue in Win10 too.
In Win10, NPP shows **additional confirmation window** (NPP created). I believe you selected 'No' of this window-
![image](https://user-images.githubusercontent.com/6822117/68270275-d0612f80-0082-11ea-87c1-644bff32fe5e.png)
Please select 'Yes' here.
You will get dialog(by windows)-
![image](https://user-images.githubusercontent.com/6822117/68270302-e5d65980-0082-11ea-94e6-1821121cc754.png)
Select 'No' here.
And 'Delete Fail' dialog will appear.
If you look into my code changes, its a straight away message box code removed from NPP code-
https://github.com/notepad-plus-plus/notepad-plus-plus/pull/7500
Please get back to me if still not able to produce the issue.

**Comment by PalashBansal** [comment]
@sasumner I am talking about additional NPP created window(appears in Win10, but not in Win7) in my previous comment. Putting screenshot again here-
![image](https://user-images.githubusercontent.com/6822117/68270767-7fead180-0084-11ea-976b-13b68c188a48.png)
It seems like an overkill to me. 2 confirmation dialogs(1st by NPP, 2nd by Windows).
**I think 1st one(NPP created) should be removed. Suggestions?**

**Why I think not to remove windows' one-**
It shows more intelligent dialog based on file location.
If file is in your system(file test1 in screenshot)-
![image](https://user-images.githubusercontent.com/6822117/68270907-f7206580-0084-11ea-95b5-278d76ffe5ad.png)
If file is in network directory(file test2 in screenshot)-
![image](https://user-images.githubusercontent.com/6822117/68270945-14553400-0085-11ea-8ff8-3083a500c3b6.png)

**Comment by sasumner** [comment]
I could not reproduce (under Windows 10).

**Comment by PalashBansal** [comment]
> I could not reproduce (under Windows 10).

@sasumner 
Can you please specify which issue you were not able to reproduce?
**Please ignore my uploaded GIF(only applies to Win7) but look into attached screenshots closely.**
Refer my comments for steps to reproduce the issue-
_1st one-_ unnecessary "Delete Fail" dialog(main issue) ----- https://github.com/notepad-plus-plus/notepad-plus-plus/issues/7499#issuecomment-550149390
_2nd one-_ Two confirmation dialogs. ----- https://github.com/notepad-plus-plus/notepad-plus-plus/issues/7499#issuecomment-550152213

**Talking about main issue here("delete fail" dialog)-**
After clicking 'Move to recycle bin'
On 1st dialog appearing- press "Yes"
On 2nd dialog appearing- press "No"
and 'Delete file fail' box will appear.
Unfortunately, I don't have the means to create GIF in my win10 office system.

Feel free to get back to me if still not able to produce.. Also, please help me help you in repro. the issue. :)

**Comment by sasumner** [comment]
@PalashBansal said:

>Can you please specify which issue you were not able to reproduce?

There is only ONE issue here. Or there should only be one issue here.

What I meant was that when I execute your three steps to reproduce, I don't receive a "Delete file failed" dialog.  So, to me, I can't reproduce your result and everything seems to be working fine.

**Comment by PalashBansal** [comment]
> @PalashBansal said:
> 
> > Can you please specify which issue you were not able to reproduce?
> 
> There is only ONE issue here. Or there should only be one issue here.
> 
> What I meant was that when I execute your three steps to reproduce, I don't receive a "Delete file failed" dialog. So, to me, I can't reproduce your result and everything seems to be working fine.

I am talking about the message box invoked from- 						https://github.com/notepad-plus-plus/notepad-plus-plus/blob/1377cc6c0495f4d7790f7fa2b6f3d990f652a80a/PowerEditor/src/NppIO.cpp#L1632
I will try to create a GIF in Win10 and post it tomorrow.

**Comment by sasumner** [comment]
Can anyone else duplicate the behavior @PalashBansal is seeing on this?

**Comment by PalashBansal** [comment]
> > @PalashBansal said:
> > > Can you please specify which issue you were not able to reproduce?
> > 
> > 
> > There is only ONE issue here. Or there should only be one issue here.
> > What I meant was that when I execute your three steps to reproduce, I don't receive a "Delete file failed" dialog. So, to me, I can't reproduce your result and everything seems to be working fine.
> 
> I am talking about the message box invoked from-
> 
> https://github.com/notepad-plus-plus/notepad-plus-plus/blob/1377cc6c0495f4d7790f7fa2b6f3d990f652a80a/PowerEditor/src/NppIO.cpp#L1632
> 
> 
> I will try to create a GIF in Win10 and post it tomorrow.

@sasumner 
**Please look into this GIF for steps to reproduce in Win10-**
![win10nppIssue1](https://user-images.githubusercontent.com/6822117/68362786-7ded4500-014e-11ea-8dd3-bd87f1c18d18.gif)

**Comment by sasumner** [comment]
@PalashBansal Your animated GIF with the little swirly motions with the mouse doesn't change things for me.  When I say Yes to the Delete File popup, I don't get an "Are you sure?" popup.  That was what I meant earlier, but I didn't express that well (sorry).  However, still I can't reproduce the sequence that gets to the root of your complaint with this issue.  Maybe I have some Windows or Notepad++ setting configured different than you do?

**Comment by PalashBansal** [comment]
@sasumner
Can you please send your debug info.? I will compare with mine.
I don't think which windows setting can make the difference.

**Comment by sasumner** [comment]
@PalashBansal My debug info:

Notepad++ v7.8.1   (64-bit)
Build time : Oct 27 2019 - 22:57:19
Path : C:\........\npp.7.8.1.bin.x64\notepad++.exe
Admin mode : OFF
Local Conf mode : ON
OS Name : Windows 10 Enterprise (64-bit) 
OS Version : 1709
OS Build : 16299.1451
Plugins : mimeTools.dll NppConverter.dll NppExport.dll

**Comment by PalashBansal** [comment]
_Finding a software bug and explaining how to reproduce it is like seeing a ghost no one is believing into.._
@donho @sasumner 
I found that my both win7 and office win10 systems had **"Display delete confirmation dialog" property of recycle bin enabled.** See the page on how to enable it on your system(just to reproduce this issue)- https://www.maketecheasier.com/enable-delete-confirmation-dialog-box-windows8/
After enabling, try the steps I previously gave in the comment- https://github.com/notepad-plus-plus/notepad-plus-plus/issues/7499#issuecomment-550809489

On this property enabled, https://github.com/notepad-plus-plus/notepad-plus-plus/blob/cf7e373dca890d65ecc86489fe9cce1bcc7597f7/PowerEditor/src/ScitillaComponent/Buffer.cpp#L742 will trigger confirmation dialog(selecting no on this makes code execution to go inside https://github.com/notepad-plus-plus/notepad-plus-plus/blob/cf7e373dca890d65ecc86489fe9cce1bcc7597f7/PowerEditor/src/NppIO.cpp#L1630 if statement atlast triggering 'delete fail' messaebox)

**Comment by sasumner** [comment]
@PalashBansal Ah, OK. We are getting somewhere.  How can the Notepad++ code be changed so that it doesn't display the "unnecessary" message box, but still retain the ability to check and notify the user of a real error if one happens?

**Comment by PalashBansal** [comment]
That's a really nice doubt, make my mind boggled..
As NPP has nothing to do if user selects 'no' in last dialog, it is surely
a non error condition in which "error message" is not meant to be
displayed. But if selects yes and somehow moving file operation fails, then
"error message" makes sense.
I will dig into what all this SHFileOperation provides other than a
true/false return value. False without error code set being 'No'
False with error code set being 'actual error'
Something like that. I will look into it and update my PR with a better fix
:)

**Comment by PalashBansal** [comment]
> @PalashBansal Ah, OK. We are getting somewhere. How can the Notepad++ code be changed so that it doesn't display the "unnecessary" message box, but still retain the ability to check and notify the user of a real error if one happens?

That's a really nice doubt, make my mind boggled..
As NPP has nothing to do if user selects 'no' in last dialog, it is surely
a non error condition in which "error message" is not meant to be
displayed. But if selects yes and somehow moving file operation fails, then
"error message" makes sense.
I will dig into what all this SHFileOperation provides other than a
true/false return value. False without error code set being 'No'
False with error code set being 'actual error'
Something like that. I will look into it and update my PR with a better fix
:)
