### ISSUE TITLE
弱智玩意，是不是不玩政治在台湾体现不出你的价值？

### ISSUE THREAD

**Issue by feihongmeilian** [notepad-plus-plus/notepad-plus-plus#7504]
写的你妈的冠冕堂皇，不过是为了在岛内附和某党的操作罢了，既要当婊子又要立牌坊，你还是个写程序的不？为什么不去学那个人妖去接受民进党的狗粮？还是你的名气太小？只能在网上犬吠？

**Comment by feihongmeilian** [comment]
写程序就好好写程序，这么喜欢玩政治，就蹦跶出来到省内去上街，省内不是给了你很多可以忽悠弱智的渠道吗？不行你也可以把自己搞成同性恋，也是一个不错的发声渠道。把自己整得像朵白莲花来恶心人，小心秋后算账

**Comment by leo19941227** [comment]
有能力就自己寫個repo自己宣揚國威阿，沒能力就只能像狗來這邊叫囂，結果落得人家根本懶得理你。沒影響力只會叫的人太多，不缺你一個

**Comment by Lin-Buo-Ren** [comment]
![image](http://i.imgur.com/E5Q3vIb.png)

**Comment by chih-yuan** [comment]
我是台灣人 我是認為政治很重要 但台灣政治界就像兩團馬戲團在搞笑一樣 選哪邊都不優 唉

**Comment by ylshore** [comment]
珍惜你手中的那张票吧

**Comment by feihongmeilian** [comment]
@chih-yuan 政治的事，都是人的事，只要是人的事，脱了裤子都一样。“开口绅士风度，闭口自由民主，说来说去就是为了骗钱骗得好看一点。”只有屁民才相信那一套口号，也只有屁民才相信制度能约束人的行为。

**Comment by feihongmeilian** [comment]
@ylshore 杀人放火金腰带，修桥补路无尸骸。你的票顶个屁用，选来选去不都是那几家的代理人，年轻

**Comment by ylshore** [comment]
我不跟你分辩，价值观扭曲的鸿沟，不是三言两语能填平的。

**Comment by feihongmeilian** [comment]
@ylshore 在我看来把一个由统治者指定的规则当教条来膜拜的人，已经不是价值观扭曲这么简单的问题了，可能智商有缺陷。

**Comment by a510431599** [comment]
> @ylshore 在我看来把一个由统治者指定的规则当教条来膜拜的人，已经不是价值观扭曲这么简单的问题了，可能智商有缺陷。


> @ylshore 杀人放火金腰带，修桥补路无尸骸。你的票顶个屁用，选来选去不都是那几家的代理人，年轻

这两条放在一起看，真的让人发笑，不知道你几岁，如果只二三十岁，情有可原，这个世界所有的政治都是人的政治，中国统治者是那几家的代理人，美国就不是，英国就不是，发达国家哪个不是？只不过是中国背后的是政治家，发达国家背后的是资本而已。 有区别吗？  你同样也是把民主自由那一套当成教条来膜拜而已，既不懂民主自由的起源，更不懂起深层含义。
