### ISSUE TITLE
Error while accessing Notepad++ via web client (and sometimes via browser)

### ISSUE THREAD

**Issue by nikable** [notepad-plus-plus/notepad-plus-plus#7506]
This issue might be related to #5939 and #1600
### Description of the Issue

**The homepage , download page, RSS feed etc. from Notepad++ are not accessible via a web client.**

Error "The remote server returned an error: (503) Server Unavailable" is thrown while accessing the URLs from the client. Accessing URLs from the browser is not a piece of cake either. 
It (browser) either randomly throws "503" error or prepares browser to wait for few seconds and forwards (or redirects) the request.   
My guess would  be, it is somehow related to the timeout and URL redirection issue (CloudFlare) or DDOS mitigation backed check. 

Due to the inconsistent behaviour, it is difficult for me to perform the Root Cause Analysis of this issue. And unfortunately, I am blocked because,  I need to access these URLs (provided below) from the web client.

P.S. - This functionality was perfectly fine until last week.  I was able to access homepage and download page.

### Steps to Reproduce the Issue

1.  Start a web client (for e.g. Postman ,PowerShell etc.)
2.  Invoke the web request and try to access either of the following URL.
- https://notepad-plus-plus.org/index.xml
- https://notepad-plus-plus.org/
- https://notepad-plus-plus.org/downloads/
3.  Repeat steps 1 and 2 with each link.

### Expected Behaviour
HTTP Response with code 200

### Actual Behaviour

HTTP Response with error - "The remote server returned an error: (503) Server Unavailable"

### Debug Information

Tried changing configration paramaters in web client such as Allow Redirection, Increased timeout etc. but receiving the same error.

**Comment by donho** [comment]
It's due to CloudFlare's anti-DDoS service is in "Under Attack" mode. 
The latest release caused the DDoS attack from Chinese netizens (or government ?) , sorry for the inconvenience. 
I'll check with CloudFlare team to know if we can change the mode.

**Comment by nikable** [comment]
@donho it would be really nice to hear again from you :)

thanks in advance !

**Comment by sasumner** [comment]
>donho it would be really nice to hear again from you 

I guess you got heard from. :-)
