### ISSUE TITLE
New Save Prompt Locks Minimized Window

### ISSUE THREAD

**Issue by RealityRipple** [notepad-plus-plus/notepad-plus-plus#7508]
### New Save Prompt Locks Minimized Window
If you have a minimized Notepad++ window open with unsaved changes, the new prompt behaves incorrectly. Tested on Windows 7 and Windows 10 - it's worse on 10.

### Steps to Reproduce the Issue
1. Open a new window
2. Type text into the new window
3. Minimize the new window
4. Close the new window through the taskbar

### Expected Behavior
The window should restore itself and the prompt should show as a standard Modal prompt for the window.

### Actual Behavior
Nothing happens.
On Windows 7: You can click on the taskbar icon or preview and the window pops up, but is in Modal mode, and nothing can be clicked until you hit Escape.
On Windows 10: The window becomes locked in a minimized state. The only way to get it to pop up again is through the "Bring to front" feature in the Task Manager. Then, like Windows 7, it's in Modal mode and nothing can be clicked until you hit Escape.

PS: I'd also like to suggest hiding the "All" buttons for windows that have only one tab open, but that's sort of a separate issue.

**Comment by sasumner** [comment]
@RealityRipple Why didn't you include your version info?

This is reproducible on Windows 10.  Step 4 caused nothing to happen (visually) for me.  After that I was able to unminimize (aka restore) the Notepad++ main window, but it would respond to input of any type.  It's like the Save dialog is somewhat active (but unseen) and there is no way to give it input to cancel it.  End result was having to use Task Manager to kill Notepad++.

@RealityRipple said:

>...suggest hiding the "All" buttons for windows that have only one tab open, but that's sort of a separate issue.

Yes, please open separate issue.

Notepad++ v7.8   (32-bit)
Build time : Oct  7 2019 - 00:58:16
Path : C:\..........\npp.7.8.bin\notepad++.exe
Admin mode : OFF
Local Conf mode : ON
OS Name : Windows 10 Enterprise (64-bit) 
OS Version : 1709
OS Build : 16299.1451
Plugins : ColumnTools.dll Explorer.dll LocationNavigate.dll MarkdownViewerPlusPlus.dll mimeTools.dll NppConverter.dll NppExec.dll NppExport.dll PythonScript.dll

**Comment by RealityRipple** [comment]
Last night I also noticed that if a Notepad++ window is off to one side or another of the screen (meaning partially or mostly hidden), the prompt shows up in the center of the window, also partially (or potentially even fully) off the screen, rather than showing up fully within the bounding rectangle of the screen as is standard for such prompts.
