### ISSUE TITLE
你封你爹？？

### ISSUE THREAD

**Issue by aichiyudeniu** [notepad-plus-plus/notepad-plus-plus#7511]
你封你爹？？你来过中国？？？官网不让中国大陆访问  真是掩耳盗铃？？ 你说尼玛呢？？？你能看懂吗？？FUCK YOU 看懂了吗？？？

**Comment by leo19941227** [comment]
哪來的弱智不會講話

**Comment by Lin-Buo-Ren** [comment]
![image](http://i.imgur.com/E5Q3vIb.png)
