### ISSUE TITLE
Technology should not be mixed with politics

### ISSUE THREAD

**Issue by sizzlecar** [notepad-plus-plus/notepad-plus-plus#7512]

**Comment by Lin-Buo-Ren** [comment]
政治就是眾人之事，包含碼農  
Politics is every citizens' issue, including coders.
![image](http://i.imgur.com/E5Q3vIb.png)

**Comment by Korb** [comment]
This is a duplicate of #6288 (disrespect for other members of the FOSS community by posting political propaganda spam in text editor resources).
