### ISSUE TITLE
Command "Wikipedia Search" not considering the current user language

### ISSUE THREAD

**Issue by marcoM32** [notepad-plus-plus/notepad-plus-plus#7513]
### Description of the Issue
The italian language is set in notepad++ but when the user activate the command "Wikipedia Search" in the browser is open the Wikipedia english domain (https://**en**.wikipedia.org/wiki/...)

### Steps to Reproduce the Issue

1. Set the Italian language
2. Activate the "Wikipedia Search" command

### Expected Behavior
In the browser opens url: https://**it**.wikipedia.org/wiki/

### Actual Behavior
In the browser opens url: https://**en**.wikipedia.org/wiki/

### Debug Information
Notepad++ v7.8.1   (64-bit)
Build time : Oct 27 2019 - 22:57:19
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS Name : Windows 10 Pro (64-bit) 
OS Version : 1903
OS Build : 18362.418
Plugins : DSpellCheck.dll JSMinNPP.dll mimeTools.dll NppConverter.dll NppExport.dll NPPJSONViewer.dll XMLTools.dll

**Comment by donho** [comment]
It's an customizable action of "run" command. 
Please remove this command and do your own one.

**Comment by sasumner** [comment]
@marcoM32 @donho means for you to edit shortcuts.xml and change the `en` text to `it` in the UserDefinedCommands section.
