### ISSUE TITLE
Why delete China-related issues?

### ISSUE THREAD

**Issue by 53caiyu** [notepad-plus-plus/notepad-plus-plus#7514]
Are you also preventing freedom of speech?
If you think the related issues should not appear here?
Should it also be considered that China’s problems should not appear in software?

Can you join the political issue in technology? Then why do you want to delete others to talk about?
You use your rights to stop freedom of speech
You use the open source feature to grow your influence and make comments, but prevent others from talking.
You don't want others to talk about it in your project, please close the source~~

Please don't hurt the open source community

---------------------------
你是否也在阻止言论自由？
如果你认为相关的问题不应当出现在这里？
那是否也应当认为中国的问题不应当出现在软件之中？

你可以在技术加入政治问题？ 那为何又要删除别人谈论
你利用你的权利阻止言论自由
你利用开源特性壮大自己影响后发表言论却阻止别人谈论
您不想别人在你的项目谈论那么请闭源~~

请不要伤害开源社群

谷歌翻译的也不知道对不对，同胞指正一下

**Comment by feihongmeilian** [comment]
把他当个屁放了好了，现在小英正在选举呢，难道拿钱了不应该帮小英办点事？以后还想不想在岛内混了

**Comment by Lin-Buo-Ren** [comment]
言論自由不保障洗 issues 不會被刪
![image](http://i.imgur.com/E5Q3vIb.png)

**Comment by feihongmeilian** [comment]
@Lin-Buo-Ren you look like your mother‘s SB，you know what I meaning？

**Comment by topazand** [comment]
It is us today. It will be you tomorrow.

**Comment by a2902793** [comment]
> 把他当个屁放了好了，现在小英正在选举呢，难道拿钱了不应该帮小英办点事？以后还想不想在岛内混了

這都能牽扯到小英，支那豬還真他媽的被洗腦洗得很厲害呢！
