### ISSUE TITLE
sb

### ISSUE THREAD

**Issue by zhxh24** [notepad-plus-plus/notepad-plus-plus#7515]
SB看得懂吗？没来过china就在那里BB，mouse吃过便便么。沙雕一枚，鉴定完毕。过两天再来看看封没有，看看美帝的freedom是什么JJ。

**Comment by Lin-Buo-Ren** [comment]
# 光復香港，時代革命！ #

**Comment by a2902793** [comment]
> SB看得懂吗？没来过china就在那里BB，mouse吃过便便么。沙雕一枚，鉴定完毕。过两天再来看看封没有，看看美帝的freedom是什么JJ。

說個笑話，支那畜說freedom 😁 言論自由給你這樣亂噴、亂洗是嗎？牆待慣了以為外面自由是給你們支那畜撒野的阿？
