### ISSUE TITLE
Replace All not working correctly when Find What value can "overlap" itself

### ISSUE THREAD

**Issue by BdR76** [notepad-plus-plus/notepad-plus-plus#7517]
### Description of the Issue
Using search and replace (CTRL+H) and the button "Replace all" does not replace all values when the Find What value can overlap with itself. I ran into this issue while working on a textfile with lots of rows containing NULL values and wanting to replace it all with an empty string. I figure searching for `;NULL;` instead of just `NULL` to avoid accidentally replacing partical NULL texts in string columns, like `LAB RESULT WAS NULLIFIED`.

### Steps to Reproduce the Issue
1. click New and paste the following text `12345;33445566;NULL;NULL;NULL;NULL;Male;NULL;NULL;NULL;NULL;NULL;NULL;NULL;NULL;NULL;15-11-2016;NULL;NULL;NULL;NULL;NULL;Living donor;22-8-1988;64;NULL;NULLIFIED;`
2. Press CTRL+H and enter Find What `;NULL;` and replace with `;;`
3. Then click button "Replace all"

### Expected Behavior
Expected all `;NULL;` to be replaced, so:

`12345;33445566;;;;;Male;;;;;;;;;;15-11-2016;;;;;;Living donor;22-8-1988;64;;NULLIFIED;`

### Actual Behavior
It still contains some `;NULL;` values, even though I clicked Replace All, this is the result:

`12345;33445566;;NULL;;NULL;Male;;NULL;;NULL;;NULL;;NULL;;15-11-2016;;NULL;;NULL;;Living donor;22-8-1988;64;;NULLIFIED;`

I understand that technically this is probably caused by the fact that the search value can overlap with itself or something like that. But in any case, from the viewpoint of the user it seems like a bug IMHO.

### Debug Information
The same happens when you search for `' abc '` and replace with `' XXX '` in the text below
```
test abc def ghi jkl abc abc abc def ghi jkl abc abc def ghi jkl
test XXX def ghi jkl XXX abc XXX def ghi jkl XXX abc def ghi jkl
                        ^^^^^                   ^^^^^
```

**Comment by sasumner** [comment]
The correct way to do this is with a regular expression replacement:

Find: `;NULL(?=;)`
Replace: `;`

seems to work.  Other variants may be possible.

**Comment by sasumner** [comment]
Correct behavior for a find action immediately following a replace action is to begin the search AFTER the text of the replacement.  Thus, the "overlap" condition desired for the example provided is not valid.
