### ISSUE TITLE
Cloned and usaved file will trigger save dialog twice on close

### ISSUE THREAD

**Issue by frank-freihube-rmcan-com** [notepad-plus-plus/notepad-plus-plus#7523]
### Description of the Issue
When trying to close Notepad++ while having an unsaved file cloned to two both views the `Save file "..."?` dialog will show up twice.

### Steps to Reproduce the Issue

1. open any file (may be empty) and change it without saving
2. clone file into second view
3. close Notepad++

### Expected Behavior
`Save file "..."?` dialog should only show up once as it is in fact only one file.

### Debug Information

Notepad++ v7.8.1   (64-bit)
Build time : Oct 27 2019 - 22:57:19
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS Name : Windows 7 Professional (64-bit) 
OS Build : 7601.24534
Plugins : mimeTools.dll NppConverter.dll NppExport.dll 

Also tried with:
Notepad++ v7.7.1   (32-bit)
Build time : Jun 16 2019 - 21:14:50
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 7 (64-bit)
Plugins : mimeTools.dll NppConverter.dll NppExport.dll NppFTP.dll

**Comment by sasumner** [comment]
Reproducible.  

Simplest case (maybe):  

1. Have Preference set/ticked to "Remember current session for next launch".
2. Have only ONE file open in a Notepad++ tab.  The file can be either a disk file or a "new _" file.  
3. Make a change to the file so it is "dirty" and has a red disk icon.  
4. Execute "Clone to Other View".
5. Press `X` on title bar to quit Notepad++.
6. In Save dialog that pops up, click No.
7. At this point, Save dialog will reappear, asking about the same file.  <--This should not occur.

**Comment by sasumner** [comment]
A fix for this could likely use similar logic as the fix to #6074

**Comment by frank-freihube-rmcan-com** [comment]
@sasumner One does not even have to check "Remember current session for next launch". It is also occuring without saving the session

**Comment by donho** [comment]
I have tried to reproduce the "so called bug".
If the answer is YES (for save) on the first one, the file is saved, both documents are closed. So the behaviour is correct.
If the answer is Cancel (for save) on the first one, the the operation is stopped, the behaviour is also correct.
The unexpected behaviour is when user answers No (for save) on the first one, then the 2nd dialog appears.
For me it's unexpected but there's no critical incoherence here.
I will see what I can do about it.
