### ISSUE TITLE
Scintilla announcement: Future changes to external lexers

### ISSUE THREAD

**Issue by Ekopalypse** [notepad-plus-plus/notepad-plus-plus#7525]
Scintilla announced the following [here](https://groups.google.com/forum/#!topic/scintilla-interest/uIeIzVV_QEg)
Is this something which would affect npp?

**Comment by Ekopalypse** [comment]
[Upcoming 4.4](https://groups.google.com/forum/#!topic/scintilla-interest/QVvtulSTHBk) prepares for lexer separation
Fixes which could address open issues:
-   On Win32, changing display scale and moving windows between monitors with different scales works much better.
- Implement per-monitor DPI Awareness on Win32 so both Scintilla and SciTE will adapt to the display scale when moved between monitors. Applications should forward WM_DPICHANGED to Scintilla. Bug #2171, Bug #2063.

**Comment by donho** [comment]
@Ekopalypse 
Scintilla is upgraded to 4.4.6 in Notepad++ master now: 
https://github.com/notepad-plus-plus/notepad-plus-plus/commit/d7819cf601051510b7fa1640ca17fedad297e1f8

And this change will be in Notepad++ 7.9.4 release. Did you observe any regression regarding external lexers with the current (in master) Scintilla?

**Comment by Ekopalypse** [comment]
@donho, I will download it, test it and report back here.

**Comment by Ekopalypse** [comment]
Regarding the external lexers, I see no difference in behavior to the previous Scintilla version 4.2.0.

I have tested
- create new documents
- open existing documents
- restart Npp with already opened documents
- folding
- move buffers from one view to the other
- assign different colors to external lexers (at runtime and when Npp is restarted)
- using standard, obsidian and custom themes

And all my Python scripts responding to Notepad and Scintilla callbacks seem to work as expected.

So, from my point of view, this looks good.

From now on, I will use this updated Scintilla library for my daily work,
and if something is strange, I would report an isue if it is different in the 4.2.0 version.

**Comment by donho** [comment]
Thank you @Ekopalypse for testing.
Feel free to close this issue when you think it's time.

**Comment by donho** [comment]
> First version that separates Lexilla from Scintilla. Each of the 3 projects now has a separate history page but history before 5.0.0 remains combined.

ref: https://www.scintilla.org/ScintillaHistory.html

So it'll be the issue when Notepad++ upgrad Scintilla next time.

**Comment by Ekopalypse** [comment]
@donho 
I will keep an eye on it. 
I'm closing this issue because after ~7 days of using the new Scintilla exclusively, I haven't had any problems in this regard.
