### ISSUE TITLE
Navigation with up/down keys let editor hang

### ISSUE THREAD

**Issue by Big--Mike** [notepad-plus-plus/notepad-plus-plus#7542]
### Description of the Issue
After upgrading Notepad++ (x86) from 7.7.1 to 8.1 navigating with up/down keys in a lengthy document leads to hanging in the editor window (while the status bar line counter still increases). The scrolling instead isn't "smooth" anymore, but the test position "jumps"

### Steps to Reproduce the Issue

1. Install NPP and DSpellCheck plugin
2. Open a lengthy document
3. Press the down key and hold it

### Expected Behavior
The text flows smooth through the window and the cursor position is in the line, the status bar shows.

### Actual Behavior
The display is hanging and the status bar line counter increases, while the cursor stays in the same line

### Debug Information
Notepad++ v7.8.1   (32-bit)
Build time : Oct 27 2019 - 22:46:07
Path : C:\Program Files (x86)\Office\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS Name : Windows 10 (64-bit) 
OS Version : 1903
OS Build : 18362.418
Plugins : DSpellCheck.dll 

DSpellCheck version is 1.4.14.0
- This didn't happen in NPP 7.7.1
- This doesn't happen if I remove DSpellCheck

So some change from NPP 7.7.1 to 8.1 is causing the problem :(
I've also reported the issue at the DSpellCheck repository:
https://github.com/Predelnik/DSpellCheck/issues/196#issue-520636362

**Comment by sasumner** [comment]
>This doesn't happen if I remove DSpellCheck

Suggest not using DSpellCheck... ?

**Comment by Big--Mike** [comment]
@sasummer 
Is there a working alternative for DSpellCheck, that you could recommend?

**Comment by Big--Mike** [comment]
Thanks are going to @Predelnik, who found a workaround for the problem, the code change in Notepad++ caused.
