### ISSUE TITLE
Losing file changes on 'move to recycle bin'

### ISSUE THREAD

**Issue by PalashBansal** [notepad-plus-plus/notepad-plus-plus#7543]
### Description of the Issue
Condition1(Good): For a saved file on disk -> 'Move to Recycle Bin' button is enabled.
Condition2(Good): For a new document(not on disk) ->'Move to Recycle Bin' button is disabled(dimmed)

But, **Condition3(Erroneous):** For a document saved in disk but content is modified without saving changes -> 'Move to Recycle Bin' button is enabled. Clicking on 'Move to Recycle Bin' button **ignores all changes** and moves file from disk to recycle bin.

### Steps to Reproduce the Issue
1. Open a file from disk to NPP
2. Make some changes(but don't save)
3. 'Move to Recycle Bin' button is unfortunately enabled. Click it!
4. File moves to Recycle bin and gets closed from NPP.
5. Go to recycle bin and Restore file.
6. Open the file and observe that changes are lost.

### Expected Behavior
'Move to Recycle Bin' button should be disabled like Condition2

### Actual Behavior
'Move to Recycle Bin' button is enabled(allowed to click)

**Comment by PalashBansal** [comment]
Fix is in PR https://github.com/notepad-plus-plus/notepad-plus-plus/pull/7544

**Comment by Ekopalypse** [comment]
I don't think this is expected behavior, at least not for me. If I want to delete a file, aka move to recycle bin, then I expect it to be deleted regardless if there are changes or not open and it is obvious that
if I delete a file which has "open changes" that I don't care about it, otherwise I wouldn't have deleted the file in first place and if it is by accident, there is still the confirmation dialog which need to be answered.

**Comment by PalashBansal** [comment]
> I don't think this is expected behavior, at least not for me. If I want to delete a file, aka move to recycle bin, then I expect it to be deleted regardless if there are changes or not open and it is obvious that
> if I delete a file which has "open changes" that I don't care about it, otherwise I wouldn't have deleted the file in first place and if it is by accident, there is still the confirmation dialog which need to be answered.

Thats a good point. But what if user forgets to save file moving it to recycle bin to be restored later. Btw, confirmation dialog doesn't tell about unsaved changes, but only message about moving/closing file.

**Comment by Ekopalypse** [comment]
Maybe I do have a totally different workflow then you do but for me this sounds strange.
Of course I could have, accidentally, hit the delete button but then I get the confirmation dialog and at
that point one should be aware that this is deleting the file and I should know if I have to press yes or no/cancel.
And if I press yes to delete a file, then I expect the tab to be closed silently, I would be surprised to see
a dialog that there are unsaved changes which get deleted anyway.
If it is all about - shit happens - then come on, at one point one must take responsibility when doing something wrong. Npp cannot be designed to be the rescue place for every possible mistake one makes. Npp should be a fast reliable editor and not a nanny. ;-) My two cents :-)

**Comment by bahusoid** [comment]
Very strange expected behavior. +1 It's not an issue - delete button shouldn't be disabled for modified file.

**Comment by sasumner** [comment]
I'll agree with both sides somewhat on this issue; but I'll also say that it doesn't need "fixing" and current behavior can stand as it is.
