### ISSUE TITLE
"View Current File in...[->browser list]" doesn't work with SVG

### ISSUE THREAD

**Issue by brennanyoung** [notepad-plus-plus/notepad-plus-plus#7546]
### Steps to Reproduce the Issue
1. Open or create an SVG file in n++
2. Go to View->View Current File in...

### Expected Behavior
I expected to be able to choose a browser and view the rendered file there, because browsers can display SVG, even without a HTML wrapper. I would expect that notepad++ could be perfectly viable as a SVG authoring tool, so this workflow pathway should not be disabled.

![svgnpp](https://user-images.githubusercontent.com/1430985/68600499-ed429c00-04a2-11ea-81be-ac665c5b2f1c.PNG)

### Actual Behavior
All menu items in the browser submenu are greyed-out/disabled.

Oddly enough, files with the .xml file extension are 'allowed' to go the browser via the view menu.

Workaround for today is to re-enable the 'dangerous' shortcuts from `AppData/Roaming/Notepad++/shortcuts.xml`

**Comment by xylographe** [comment]
Solved in commit f477c095aa6ec219edf44fc51b293b8d478c8cab.
Will become available in next release, or download the `Notepad++.Win32.Unicode Release.exe` file from [AppVeyor Artifacts](https://ci.appveyor.com/project/donho/notepad-plus-plus/history).

**Comment by ArkadiuszMichalski** [comment]
This can be closed, as mention above.
