### ISSUE TITLE
I am a Chinese, and I love my country!

### ISSUE THREAD

**Issue by YoungYo** [notepad-plus-plus/notepad-plus-plus#7547]
### Steps to Reproduce the Issue

1. 
2. 
3.

**Comment by BarneyCan** [comment]
Who cares

**Comment by BarneyCan** [comment]
You leave Notepad++ alone, it's a wonderful thing. Silly brainwashed children

**Comment by itsang** [comment]
> You leave Notepad++ alone, it's a wonderful thing. Silly brainwashed children

You think we Chinese were brainwashed by our gov while we Chinese think you were brainwashed by western medias :)

The most ironic thing is that you still think your medias are justify.

**Comment by rtransformation** [comment]
no need to say anything here. they just don't want to know the real thing. they support terrorism in xinjiang, they support terrorism in hongkong, it will be funny what will be in their face when the terrible things happen to to their head.
