### ISSUE TITLE
EOL conversion - inconsistency in naming between menu and statusbar text

### ISSUE THREAD

**Issue by Eldaw** [notepad-plus-plus/notepad-plus-plus#755]
The names of entries for doing EOL conversion differ between the menus (menubar and context menu for statusbar) and what is shown on the statusbar.

This is the current situation:

EOL Conversion (menu & context menu) | Statusbar text
------------ | -------------
Windows Format | Dos\Windows
UNIX/OSX Format | UNIX
Old Mac Format | Macintosh

I propose, for improving consistency, that the items be renamed to this:

EOL Conversion (menu & context menu) | Statusbar text
------------ | -------------
Windows (CRLF)  | Windows (CRLF)
UNIX (LF) | UNIX (LF)
Classic Mac (CR) | Classic Mac (CR)

**Comment by donho** [comment]
I don't think there's any inconsistency between menu and status bar for eol.
However, I'll think about CRLF, LF and CR on menu.
