### ISSUE TITLE
Feature request: 'Undo' checkpoints

### ISSUE THREAD

**Issue by JohnPool** [notepad-plus-plus/notepad-plus-plus#7550]
Sometimes its happens during an edit session that you want to undo your modifications up to a certain point where you were, say, 10 minutes ago. In my experience it is sometimes difficult to recover the exact position: in applying repeated Undo’s it is easy to ‘overshoot’ this point.

Therefore it would be nice to be able to set a ‘checkpoint’ during an edit session to which you can revert later on, simply by clicking its name somewhere in an _Edit | Undo_ submenu.

I would not even know how to begin implementing this, but would this be an idea?

John Pool

**Comment by sasumner** [comment]
Here's a way to do a checkpoint that already works:

1. Go to the `File` menu.
2. Choose `Reload from Disk`.
3. Make a lot of further edits.
4. Oops, don't want those further edits.
5. Hold down the `Undo` key (ctrl+z) until nothing more to undo.
6. You've reached your "checkpoint".

**Comment by JohnPool** [comment]
Yes, that works too, thanks (must remember to save of course, but that is similar to setting a checkpoint). Slightly less flexible: you have one 'checkpoint' only.

**Comment by sasumner** [comment]
>you have one 'checkpoint' only

Having used such systems before, my experience is if you have more than one checkpoint, you can't remember what the "older" one(s) are!  :-)

It is better to use Windows Explorer and drag-and-drop-copy to a new name where you can add a bit of text:

`mycoolprogram.c` gets copied to `mycoolprogram_phase1completeandworking.c`

Or, even better...use some sort of version control.

Checkpoints are *okay*...I don't want to pooh-pooh your idea, but there are other options available so for now I'm going to close this out.
