### ISSUE TITLE
Download Progress dialog title shows bad number

### ISSUE THREAD

**Issue by TheRealAyCe** [notepad-plus-plus/notepad-plus-plus#7555]
### Description of the Issue

The dialog for downloading a new version seems to be initialized with a bad progress value.

### Steps to Reproduce the Issue

1. Have a version that wants to update.
2. Have stuff going on so that the actual starting of the download is delayed. (I don't know what exactly causes a delayed download start).

### Expected Behavior

Start with 0%.

### Actual Behavior

![nppbug](https://user-images.githubusercontent.com/11407231/68701238-9f06c900-0586-11ea-9a15-644053d3f164.png)

**Comment by boppy** [comment]
You call it "bad number" - I would be rather glad to have a drive this huuuuge (quick math: The download would have 320 ZB)! ;-)

But back to topic: Does your download start anyways? For me it doesn't. I see the exact same window as in your report, it disappears after ~15 sec, but no download is done...

**Comment by TheRealAyCe** [comment]
After a while (some minutes I think, the computer was busy, possibly also downloading other stuff) it started normally from 0% and finished.

**Comment by milankragujevic** [comment]
![image](https://user-images.githubusercontent.com/7611163/69041197-62582900-09ef-11ea-9442-015b0d85c2a4.png)

Can confirm, same problem happens.

Unfortunately, it never downloads for me. What happens instead is the upgrade window goes pale, shows (Not Responding), and then crashes and promts Windows to report the error. Which amusingly causes the Error reporting dialog to go pale and show (Not Responding) too, after which the whole UI shell (explorer.exe) crashes and I am logged out.

Quite a bug indeed 😃 

(I'm only complaining about the progress + no update being downloaded, to be clear)

**Comment by andrelundin** [comment]
Same issue here

**Comment by donho** [comment]
This issue has been fixed in v7.8.2
