### ISSUE TITLE
Add a "Close all" option

### ISSUE THREAD

**Issue by tutoref** [notepad-plus-plus/notepad-plus-plus#7556]
### Description of the Issue

Sometimes you just need to close all the open tabs. Currently the only available options when you right-clic on a tab are : 

1. Close
2. Close all but This
3. Close all to the left
4. Close all to the right

### Steps to Reproduce the Issue

1. Open 2 files or more
2. Right-Clic on one of the tabs

### Expected Behavior

Having a "Close all" option

### Actual Behavior

No "Close all" option available.

### Debug Information

N.A

**Comment by sasumner** [comment]
`File` menu > `Close All`

**Comment by tutoref** [comment]
@sasumner . I know, but since np++ has some options on the tab itself when you right click, a "close-all" option has more priority than "close on the left " or "close on the right" .  Why not to add it and add those less priority options ?

**Comment by sasumner** [comment]
@tutoref Probably because "Close All" is not related to the tab right-clicked.  "Close All to the Left" and others need a reference point: the current tab.  Close All needs no further info.  

Yes, I realize "Close All Unchanged" also does not really belong.  :-)

**Comment by xylographe** [comment]
I think, the "Close All Unchanged" item ought to be removed from the tab menu, and "Close More" in the "File" menu should be replaced by "Close All Unchanged".

File menu:
- Close
- Close All
- Close All Unchanged

Tab menu:
- Close All BUT This
- Close All to the Left
- Close All to the Right

**Comment by sasumner** [comment]
@xylographe Your suggestion does make sense, however, there are probably people that don't know about a tab's right-click context menu and thus would only know to find such things (well, mainly "Close All") on the File menu.
