### ISSUE TITLE
如果失去理智，就只能成为别人的笑柄。

### ISSUE THREAD

**Issue by treeke** [notepad-plus-plus/notepad-plus-plus#7560]
我们看到的可能是政府想让我们看到的，你们看到的或许也可能只是别人想让你们看到的，就像历史一样，你无法亲身经历，只能通过各种渠道了解。人心往往具有欺骗性，希望你不要觉得在网上发表两句评论就能改变什么，毕竟你我都只是普通人。

**Comment by JieshuaiCui** [comment]
作者是个废物
