### ISSUE TITLE
Remove "Yes to all" and "No to all" buttons when you want to close just one tab

### ISSUE THREAD

**Issue by Avaray** [notepad-plus-plus/notepad-plus-plus#7563]
Video: https://youtu.be/Rrp67M4JO9o

If you want to close just one unsaved tab, you will get dialog to save it or not. Yes, that's good. But two of five options are useless. "Yes to all" and "No to all". It wasn't like that in previous versions of notepad++ 🤔 These buttons are just useless in this case.

Steps to Reproduce the Issue:
1. create new tab
2. write something
3. try to close it

**Comment by sasumner** [comment]
The `Yes to All` and `No to All` buttons are disabled/greyed in your video.  This is visual indication to the user that there will be certain circumstances where these buttons will be enabled and to be mentally prepared to see that.

The best suggestion I can offer _you_ is to simply ignore these buttons in this case.

**Comment by Gitoffthelawn** [comment]
Request to Re-open.

When closing the individual tab, the 'Yes to All' and 'No to All' buttons are dimmed, but when closing NPP with only the current tab changed, the 'Yes to All' and 'No to All' buttons are not dimmed.  This makes it look like more than one tab has changed content.

Tested with v7.8.2

**Comment by sasumner** [comment]
@Gitoffthelawn Author's opinion on this matter was expressed in #7518

**Comment by sasumner** [comment]
Author has new opinion.  See #7762 and the commit mentioned there.
