### ISSUE TITLE
坚决反对开源软件政治化

### ISSUE THREAD

**Issue by openstack-test** [notepad-plus-plus/notepad-plus-plus#7575]
作者的聪明才华应该用于正确的途径，而非助纣为虐，是非不分，颠倒黑白。

**Comment by JieshuaiCui** [comment]
废物作者

**Comment by openstack-test** [comment]
谁是废物一目了然，可耻、枉为人！

在 2019-11-20 18:06:10，"anko" <notifications@github.com> 写道：


废物作者
