### ISSUE TITLE
[Feature request]: File change notification only when I really need it

### ISSUE THREAD

**Issue by eblanca** [notepad-plus-plus/notepad-plus-plus#7576]
### Description of the Issue
Currently Notepad++ pops up a dialog whenever it receive focus AND some of the open files have been updated. The issue is, at that point there is no much I can do apart from clicking "Yes" or "No".

### Steps to Reproduce the Issue

1. Open some files into Notepad++
2. Iconize it (or set focus on a different application)
3.  Modify one of the files and then bring back Notepad++ in foreground

### Expected Behavior
I would like to see the notification ONLY when I select the tab of the updated file, that is, if I'm using Notepad++ for modifications on file A, then I don't need to know NOW file B has been modified. I don't want to choose RIGHT NOW to update it or not.
Simply look at Geany behaviour, it notifies the user only when they look at the modified file AND allows them to postpone the decision.

**Comment by sasumner** [comment]
All you need to do is set the following Preference in the following way:

![image](https://user-images.githubusercontent.com/30118311/68886971-27e84680-06e6-11ea-9244-6ace5517b60b.png)
