### ISSUE TITLE
Save dialog box with 5 buttons controls enhancement

### ISSUE THREAD

**Issue by tanastasiadis** [notepad-plus-plus/notepad-plus-plus#7582]
### Description of the Issue
This is a feature enhancement about the controls of the save dialog box. 

From an aesthetics perspective, the dialog box now has 5 buttons so it looks a bit "scary".
From the order perspective, the "Cancel" button seems ok to be next to "No", however being in the middle doesn't seem to be well placed. While the user feels confident with his selection over and over for each file, it is expecting to move the cursor from "Yes" to "Yes to all" and from "No" to "No to all". However crossing over the "Cancel" button and other irrelevant options seems not that good from a UX point of view.

### Steps to Reproduce the Issue
1. Open two files in notepad++ 
2. Edit both files
3. Click exit
4. Check how the dialox box looks like

### Expected Behavior
Since the functionality of all 5 is legit, I would suggest to adopt what windows 10 have for the deletion of multiple files where the controls are:

label   ->  how the user feels
-----------------------------------
- Yes  -> I need this
- No    ->  I don't need this
- Cancel    ->  I need to go
- Check box "Apply to all" which is false by default"    -> I am confident to apply to all

### Actual Behavior
The new Save dialog box got the 5th button and now has the following:

button label   ->  how the user feels
-----------------------------------
- Yes    ->  I need this
- No     ->    I don't need thos
- Cancel    ->   My entire idea was bad, I need to leave
- Yes to all     ->   I am confident I need all
- No to all     ->    I am confident I don't need anything

### Debug Information
OS: windows 10
Notepad++ version: 7.8.1

**Comment by xylographe** [comment]
Some users (see #6223 and duplicates) want to control the Save dialogue with the keyboard. They want a key to be bound to a button (or rather the action represented by that button), like "y" for Yes, "n" for "No", etc. With a check box the "Yes to All" and "No to All" actions would require two keys: the first to enable the checkbox (e.g. "a"), and the second to select Yes ("y") or No ("n").

Not claiming this is a bad proposal, just pointing out the above is something to keep in mind.

**Comment by tanastasiadis** [comment]
_"... like "y" for Yes, "n" for "No", etc"_

Expanding the "etc", seems not easy to find convenient shortcuts keys for the "Yes to All" and "No to All" commands. I guess a keyboard user would prefer a rather memorable combination such as ctrl+Y and ctrl + N instead of an arbitrary single key assignment.

**Comment by chojrak11** [comment]
It is **crucial** that pressing "n" key on the keyboard selects "No". It worked for many years and stopped after the update.

**Comment by donho** [comment]
https://github.com/notepad-plus-plus/notepad-plus-plus/commit/cf7e373dca890d65ecc86489fe9cce1bcc7597f7
