### ISSUE TITLE
Cannot add new keywords in Lua

### ISSUE THREAD

**Issue by PavelBlend** [notepad-plus-plus/notepad-plus-plus#7615]
I am working with an application that adds functions to the Lua core library.
I need to highlight these functions in a different color.
I am editing the langs.xml file, but Notepad ignores the new keywords.
How do I add syntax highlighting for new keywords in lua?

**Comment by sasumner** [comment]
@PavelBlend This is a great question to ask on the Community ( https://community.notepad-plus-plus.org/ ) rather than here as an issue.  See .  But, to answer the question, I'd suggest doing what you need here:

![image](https://user-images.githubusercontent.com/30118311/69094636-c514e900-0a1e-11ea-9d24-bea2344b597f.png)

**Comment by PavelBlend** [comment]
I need the color of the new keywords to be different from the color of the standard functions.
To do this, I created a new tag in the langs.xml file named type3. And created a new style in the stylers.xml file. But notepad ignores him.

**Comment by Ekopalypse** [comment]
The reason you can't add your own group of words to the lua lexer is that npp [restricts the number of
possible groups to be four](https://github.com/notepad-plus-plus/notepad-plus-plus/blob/master/PowerEditor/src/ScitillaComponent/ScintillaEditView.h#L709) and those are already in use.
Lua lexer itself would be able to handle up to [8 different groups](https://github.com/notepad-plus-plus/notepad-plus-plus/blob/master/scintilla/lexers/LexLua.cxx#L52).

**Comment by PavelBlend** [comment]
And can this restriction be removed so that it is not in the next version of Notepad?

**Comment by Ekopalypse** [comment]
In theory, yes and there was already some similar discussion [here](https://github.com/notepad-plus-plus/notepad-plus-plus/issues/5937), but there was no outcome, so I assume this kind of feature request is not that attractive. :-(

**Comment by ArkadiuszMichalski** [comment]
@PavelBlend 
Do you still need more keywords list? If yes then how many? Lua support 8 keywords  list, actually we use only 4. If necessary we can add more.
https://github.com/ScintillaOrg/lexilla/blob/master/lexers/LexLua.cxx#L50
https://github.com/ScintillaOrg/lexilla/blob/master/lexers/LexLua.cxx#L446

**Comment by PavelBlend** [comment]
@ArkadiuszMichalski I apologize for the long absence.

I would like to have as many keywords as possible. That is, it is desirable to have 8 keywords.
