### ISSUE TITLE
Simple exclude files in Find in Files filter

### ISSUE THREAD

**Issue by alef162** [notepad-plus-plus/notepad-plus-plus#7618]
### Exclude files in Find in Files filter

When searching for a text in multiple files, would be useful to exclude some file types, like binary files, or not relevant files.

For example using this filter: 
\*.\* -\*.exe -\*.obj -\*.log

This should be a simple implementation, as noted in issue #2453

**Comment by donho** [comment]
Is such notation standard?

**Comment by sasumner** [comment]
I've seen it used with command-line tools.

No way to use it with filespecs where you need to use a space, but this is also a limitation of the existing syntax. :-)

**Comment by alef162** [comment]
The current syntax uses space as a separator.  So this is a current limitation I didn't want to fix in this pull request.
I've seen the "-" syntax in other editors.

**Comment by sasumner** [comment]
>The current syntax uses space as a separator.

I implied that rather than saying it.  Thanks for filling in the gap.

>I've seen the "-" syntax in other editors

Good to cite specific examples if you've got them.  I didn't cite specific command-line tools because I couldn't think of any that I've used recently that support it.

**Comment by alef162** [comment]
Sublime uses similar syntax: 
https://forum.sublimetext.com/t/exclude-files-directories-from-find-in-files/825

**Comment by xylographe** [comment]
Git uses `!` before a glob pattern in `.gitignore`.

**Comment by donho** [comment]
Why not 2 fields for filter : include & exclude ?
What do you guys think?

**Comment by xylographe** [comment]
One field might sometimes be easier to comprehend, for example,
```
*.abc !x*.abc
```
Reading from left to right: include files with extension _abc_, unless the file name starts with an _x_.

Or, more realistic:
```
*.cs !*.Designer.cs
```
Include C# source files, unless auto-generated by VS.

**Comment by donho** [comment]
Humm...
Between `*.* -*.exe -*.obj -*.log` and `*.* !*.exe !*.obj !*.log`, I prefer the 2nd.

**Comment by alef162** [comment]
I created a new pull request with your recommendation.
 #7625 
You can decide what to merge.

**Comment by bahusoid** [comment]
Both `-` and `!` are valid in filenames. Ideally it should be something not allowed like `|`.

**Comment by sasumner** [comment]
@bahusoid Ideally, yes, but `!` (or `-`) is rarely seen (at least in my experience) as the first character of a filename.  It seems the goal here is to have something mnemonic, and `!` (or `-`) achieves that.

**Comment by alef162** [comment]
@bahusoid 
Space is also valid in filenames, and the current implementation uses it as a separator.
The idea is to use something meaningful, like '!' (not operator), or '-' used in other applications.
Looking a the invalid characters  `\ / : * ? " < > |  `  I don't see a better option.

Ideally we should use `,` and `;` as separator and `-` as exclude. Use some escape character, or using the same character twice as escape character. 

But this is out of scope of this change (sadly) as mentioned in #2453 by @MetaChuh:

> the find in files function serves its basic purposes, for being a small goodie inside notepad++.

I can make a change to support escaping two "!!" or two "--", to include searching filenames starting with one "!" or "-" if this is really required.

**Comment by xylographe** [comment]
If anything, I think, space in filenames could be more of a problem than `!` (or `-`) as first character.
This could be solved by escaping space if it's not a separator, and escaping `!` if it's the first character of a glob pattern and not meant to indicate exclusion. The escape character should be the backslash, e.g. `\!*.c !!*\ ref.c` (include C source files if filename starts with `!`, unless the name ends with ` ref.c`). However, I don't believe an escape mechanism is really necessary.
