### ISSUE TITLE
这么喜欢政治，就搞到底啊，close干嘛？

### ISSUE THREAD

**Issue by JieshuaiCui** [notepad-plus-plus/notepad-plus-plus#7627]
### 评头论足谁都会，但是能给出确凿的证据的没几个，如果以你的头脑去思考这个世界，恐怕这个世界已经在1000年前的时候已经灭亡了！没几个人愿意承认自己的无知，他们以为他们是完完全全的正确者！他们以为是世界的公正派，他们以为自己多了解这个世界，他们以为他们的浑浑噩噩不足以表达他们的存在感，他们以为他们的一页网页就能“拯救”别人，有句话说得好，“越帮越忙”，说的就是一些无关人士发起一些无关痛痒的东西，他们戴着领带，高举自己的观点，好让媒体发现他们的存在感和正义感，孔子曰：勿以恶小而为之，勿以善小而不为而不为！希望作者善始善终，莫给自己后世子孙留下遗臭万年的唾骂，犹如出卖岳飞的秦桧一样，历史会对你做出评判，可能你连岳飞是谁都不知道，对中国知之甚少，井底之蛙之人居然敢对中国评头论足，以秦桧之智尚不能与整个国家和人民对抗，试问，汝算老几？！！

**Comment by Windowsredstone** [comment]
我操你妈的notepad++，卸了卸了
