### ISSUE TITLE
Incorrect version detection

### ISSUE THREAD

**Issue by NN---** [notepad-plus-plus/notepad-plus-plus#763]
GetVersionEx doesn't work without a proper manifest
https://github.com/notepad-plus-plus/notepad-plus-plus/blob/master/PowerEditor/src/Parameters.cpp#L735

See MSDN: https://msdn.microsoft.com/en-us/library/windows/desktop/ms724451%28v=vs.85%29.aspx

Notepad++ must either add a [manifest](https://msdn.microsoft.com/en-us/library/windows/desktop/dn481241%28v=vs.85%29.aspx) or to use [Version Helpers](https://msdn.microsoft.com/en-us/library/windows/desktop/dn424972%28v=vs.85%29.aspx)

**Comment by chcg** [comment]
See also #762 on this. Win8.1 and WIn10 are still detected as win8.

**Comment by dail8859** [comment]
Closed by 48e9b84b
