### ISSUE TITLE
Notepad++ v7.8.1 - unwanted control symbols now inserted on macro execution

### ISSUE THREAD

**Issue by OasisInDesert** [notepad-plus-plus/notepad-plus-plus#7642]
### Description of the Issue

Greetings,
I use the following macro to insert a tree-point (tri-dot) character ‘…’ in text

**Config file:**
`%UserProfile%\AppData\Roaming\Notepad++\shortcuts.xml`

**Macro code:**
```
<Macro name="CharTridot" Ctrl="yes" Alt="yes" Shift="no" Key="190">
    <Action type="1" message="2170" wParam="0" lParam="0" sParam="&#x2026;" />
</Macro>
```
Beginning from a new version (new v7.8.1, former v7.7.1), Notepad++  additionally inserts a special character, such as “EOT”, "STX", etc.

Related link - the beginning of the investigation
[https://community.notepad-plus-plus.org/topic/18525/control-symbols-now-inserted-on-macro](https://community.notepad-plus-plus.org/topic/18525/control-symbols-now-inserted-on-macro)

### Steps to Reproduce the Issue

1. Close Notepad++, and open its config file "%UserProfile%\AppData\Roaming\Notepad++ \shortcuts.xml" using standard text editor (Notepad.exe).
2. Add the above macro code to the next XML node "NotepadPlus - Macros".
3. Save and close config file.
4. Open Notepad++ and assign a hotkey to the added macro, or you can use menu to execute the macro.
5. Execute the macro.

### Expected Behavior

The result must be an inserted three-point character only.

### Actual Behavior

But the the result will be a three-point character plus some special character, for example "…STX".

### Debug Information

Notepad++ v7.8.1   (64-bit)
Build time : Oct 27 2019 - 22:57:19
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : ON
Local Conf mode : OFF
OS Name : Windows 7 Ultimate (64-bit) 
OS Build : 7601.24468
Plugins : AutoSave.dll mimeTools.dll NppConverter.dll NppCrypt.dll NppExport.dll 

Thanks in advance.

**Comment by xylographe** [comment]
Reproducible with NPP 7.8.1 (64-bit): result is U+2026 (Horizontal Ellipsis), followed by U+0002 (STX).
Not reproducible with NPP 7.8.1 (32-bit): result is U+2026 (Horizontal Ellipsis) only.
Not reproducible with NPP 7.7.1 (64-bit): result is U+2026 (Horizontal Ellipsis) only.

**Comment by rddim** [comment]
Interesting, I can _not_ reproduce it with NPP 7.8.1 (64-bit): result is U+2026 (Horizontal Ellipsis) only.

### Debug Info
Notepad++ v7.8.1   (64-bit)
Build time : Oct 27 2019 - 22:57:19
Path : D:\Install\Office Programs\Notepad++\notepad++.exe
Admin mode : ON
Local Conf mode : ON
OS Name : Windows 7 Professional (64-bit) 
OS Build : 7601.0
Plugins : AutoSave.dll ComparePlugin.dll ShtirlitzNppPlugin.dll TakeNotes.dll VisualStudioLineCopy.dll

**Comment by pryrt** [comment]
@rddim, 

Like @OasisInDesert , I _do_ see it on 7.8.1-64bit, with Win10

![](https://i.imgur.com/7QtIJgM.gif)

Like @xylographe , if I switch to 7.8.1-32bit or 7.7.1-64bit, I do not see the problem

**Comment by pryrt** [comment]
Additional information: took the 7.8.1-32bit that wasn't showing the problem, with the macro already recorded.  Created a new file, set **Encoding > ANSI**, and ran the macro: just inserts the ellipsis.  Close that file, create a new file, set **Encoding > UTF-8**, and ran the macro: inserts the ellipsis with the extra characters.  Close the 32-bit Notepad++ instance.

Run 64-bit v7.8.1 notepad++.exe, with same `shortcuts.xml` file.  New file, set **Encoding > UTF-8**, run macro: shows extra control characters.  Close file.  New file, set **Encoding > ANSI**, and the macro now inserts just the correct ellipsis character.

it appears to be an ANSI-encoding (ok) vs UTF-8-encoding (bad) issue, not 32-bit vs 64-bit or Win7-vs-Win10.

(Thanks @ekopalypse, who [suggested](https://community.notepad-plus-plus.org/post/48786) that idea in the Community Forum thread.)

**Comment by rddim** [comment]
@pryrt 
Yes, with **UTF-8** I see `ETX`

**Comment by OasisInDesert** [comment]
@pryrt Thanks for the confirmation with visual presentation, and for the followed clarifications.
I hope  it'll help to developers.

**Comment by pryrt** [comment]
@OasisInDesert ,

I use [ScreenToGif](https://www.screentogif.com/), which will record the screen (an area, a window, or the whole monitor), allow you to edit and add progress bars and pause frames, and even upload the animated gif directly to imgur.

Here's a screenshot of the bug in action in NPP-32bit on Win10-64bit, showing encoding-dependency:

![](https://i.imgur.com/XD1BvHb.gif)

Based on various experiments in the [forum](https://community.notepad-plus-plus.org/topic/18525/):

* @PeterJones = @pryrt: With both 7.8.1-64bit and 7.8.1-32bit on 64bit Win10 Home 1903 18362.476, 
   * Shows with **Encoding > UTF-8** but not with **Encoding > ANSI**
* @guy038: In WinXP 32bit (@guy038), 7.8.1-32bit, it appears to _not_ show the bug
* @Ekopalypse: In Linux WINE 3.0.4 with Guest=Win7-64bit 7601.0, NPP 7.8.1-64bit, the bug does not show in either UTF-8 or ANSI

Strange bug.

**Comment by sasumner** [comment]
I'll take care of fixing this, but what type of solution do we think is best?  On the Community (see link at very top of this issue) someone identified the source of the problem and a possible solution using a fixed-size buffer.  Then @pryrt came along and suggested getting the size needed first and then allocating and freeing a buffer of the exact size.  Which should we go with to fix this?  If "fixed size", then what size should be used?

**Comment by xylographe** [comment]
"Get needed size, then allocate" is always better than fixed-size buffer.

**Comment by sasumner** [comment]
>"Get needed size, then allocate" is always better...

Since that is an upvote for that method, I'll approach a change in that way.

But, as an aside, my roots are in small(ish) embedded systems, where it ISN'T always better than a fixed-size buffer.  :-)

**Comment by sasumner** [comment]
@xylographe , care to comment on the following?  My roots are causing me full-on painful feelings.

Proposed new code:

```
int ansiBufferLength = ::WideCharToMultiByte(static_cast<UINT>(pEditView->execute(SCI_GETCODEPAGE)), 0, _sParameter.c_str(), -1, NULL, 0, NULL, NULL);
auto ansiBuffer = std::make_unique< char[] >(ansiBufferLength);
::WideCharToMultiByte(static_cast<UINT>(pEditView->execute(SCI_GETCODEPAGE)), 0, _sParameter.c_str(), -1, ansiBuffer.get(), ansiBufferLength, NULL, NULL);
auto lParam = reinterpret_cast<LPARAM>(ansiBuffer.get());
```

Existing code:

```
char ansiBuffer[3];
::WideCharToMultiByte(static_cast<UINT>(pEditView->execute(SCI_GETCODEPAGE)), 0, _sParameter.c_str(), -1, ansiBuffer, 3, NULL, NULL);
auto lParam = reinterpret_cast<LPARAM>(ansiBuffer);
```

**Comment by xylographe** [comment]
@sasumner 
The new code uses `WideCharToMultiByte` as intended. It is guaranteed to work correctly for any code page, including code pages that haven't been invented yet. :)

The current code should at least check for return value 0 and ERROR_INSUFFICIENT_BUFFER. Size 3 might be too small anyway: when the converted wide char yields a 3-byte result there is no room left for the terminating null character.
