### ISSUE TITLE
Notepad++ gets UTF-8 file characters wrong

### ISSUE THREAD

**Issue by Code4SAFrankie** [notepad-plus-plus/notepad-plus-plus#7655]
### Description of the Issue
I created a UTF-8 file using Python (`with open('D:\\Files\\name.txt', 'w', encoding='utf-8') as f:`). The text in the file contains the word `Só`. When I load the file with Notepad++ the text appears as `Sรณ`. It also does not allow me to change the Encoding to Encode in UTF-8. When I load the file in Visual Studio Code the text appears correctly as `Só`.

### Steps to Reproduce the Issue
1. Write a UTF-8 file with python containing the text `Só`.
2. Load in Notepad++ 

### Expected Behavior
For the text to be correctly displayed as `Só`

### Actual Behavior
The text displayed incorrectly as `Sรณ`.

### Debug Information
Notepad++ v7.7.1   (64-bit)
Build time : Jun 16 2019 - 21:24:47
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10 (64-bit)
Plugins : ComparePlugin.dll mimeTools.dll NppConverter.dll XMLTools.dll

**Comment by Code4SAFrankie** [comment]
Updated to:

Notepad++ v7.8.1   (64-bit)
Build time : Oct 27 2019 - 22:57:19
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS Name : Windows 10 Home (64-bit) 
OS Version : 1903
OS Build : 18362.476
Plugins : ComparePlugin.dll mimeTools.dll NppConverter.dll NppExport.dll XMLTools.dll 


Issue still exists.

**Comment by rddim** [comment]
Check if `Settings > Preferences... > MISC. > Autodetect character encoding` is enabled. If yes, disable it and try again.

**Comment by Code4SAFrankie** [comment]
Thanks! That sorted it.
