### ISSUE TITLE
Binary Translations page link is broken

### ISSUE THREAD

**Issue by CorentinKirchnerSperi** [notepad-plus-plus/notepad-plus-plus#7657]
### Description of the Issue
The "Binary Translations" page link is broken:
https://npp-user-manual.org/docs/binary-translation/
System: Windows 10 Pro, Firefox 70.0.1 (64-bit)
Country: Germany

### Steps to Reproduce the Issue
1. Go to https://notepad-plus-plus.org/resources/
2. In the paragraph "Binary Translations", click on the link "Binary Translations page"

### Expected Behavior
Open and display the "Binary Translations" page.

### Actual Behavior
Get a nice 404 error: "Oops, looks like the page is lost."

Thanks for fixing.

**Comment by donho** [comment]
It's OK now.
However, feel free to reopen this ticket if the incident happens again.
