### ISSUE TITLE
"Purge for each search" option for "Mark All" action should respect "In selection" option

### ISSUE THREAD

**Issue by sasumner** [notepad-plus-plus/notepad-plus-plus#7663]
### Description of the Issue

As hinted at in a comment to #6271...

The `Purge for each search` option, when selected, will cause all marks in a document to be removed when a new `Mark All` operation is performed.  Normally this is the desired behavior.  However, if the `In Selection` option is also chosen, the marking operation should respect that and only purge the marks in the selection before marking the newly-specified text (also limited to the current selection).

### Steps to Reproduce the Issue

1. Copy the following text into a new Notepad++ tab:

```
Jack and Jill
Went up the hill
To fetch a pail of water
Jack fell down
And broke his crown,
And Jill came tumbling after.

Up Jack got
And home did trot,
As fast as he could caper;
And went to bed
And plastered his head
With vinegar and brown paper.

When Jill came in
How she did grin
To see Jack's paper plaster;
Mother vexed
Did whip her next
For causing Jack's disaster.

```
2. Invoke the Mark dialog.
3. Untick all checkboxes; tick Wrap around checkbox.
4. Put `Jack` in Find what box.
5. Press Mark All button.  Note the marking that occurs throughout the document.
6. Select the entire first "paragraph" aka the first 6 lines.
7. Tick the `In selection` checkbox in the Mark dialog.
8. Tick the `Purge for each search` checkbox in the Mark dialog.
9. Put `Jill` in Find what box.
10. Press the `Mark All` button.

### Expected Behavior
Because `In selection` and `Purge for each search` are ticked, I expect the `Mark All` button to only clear marking in the selected text before running the new mark operation.

This should be what it looks like after Step 10:

![image](https://user-images.githubusercontent.com/30118311/69551344-8923db80-0f6a-11ea-8358-3503b0c04cae.png)

### Actual Behavior
All marking in the document is cleared before running the new marking operation.

This is what it currently looks like after Step 10:

![image](https://user-images.githubusercontent.com/30118311/69551167-419d4f80-0f6a-11ea-98fb-e5fa23448028.png)

### Debug Information
Notepad++ v7.8   (32-bit)
Build time : Oct  7 2019 - 00:58:16
Path : C:\............\npp.7.8.bin\notepad++.exe
Admin mode : OFF
Local Conf mode : ON
OS Name : Windows 10 Enterprise (64-bit) 
OS Version : 1709
OS Build : 16299.1451
Plugins : ColumnTools.dll Explorer.dll LocationNavigate.dll MarkdownViewerPlusPlus.dll mimeTools.dll NppConverter.dll NppExec.dll NppExport.dll PythonScript.dll 

### Other Notes:

(Red)marking shown in the above.  Bookmarking behavior, if enabled via the `Bookmark line` option, would be treated similarly.

### Other Screenshots

After Step 5:

![image](https://user-images.githubusercontent.com/30118311/69551015-000ca480-0f6a-11ea-8609-fbf9b559ad8d.png)

After Step 6:

![image](https://user-images.githubusercontent.com/30118311/69551648-08191400-0f6b-11ea-8629-23dfd8445032.png)

**Comment by lovachittumuri** [comment]
Many Thanks Bro
