### ISSUE TITLE
minimize to system tray option does nothing after update

### ISSUE THREAD

**Issue by gendalv** [notepad-plus-plus/notepad-plus-plus#7667]
### Description/steps of the Issue
using portable on windows 10(1709)
worked fine in 7.4.2
downloaded 7.8.1 placed old 'config.xml, config.model.xml, plugins' into the new folder
noticing that it is broken
deleting 'config.xml, config.model.xml, plugins' and setting the option doesn't fix it

### Expected Behavior
working minimize to system tray

**Comment by ArkadiuszMichalski** [comment]
@donho This also can be close. Fix by https://github.com/notepad-plus-plus/notepad-plus-plus/pull/8944.
