### ISSUE TITLE
Website is down

### ISSUE THREAD

**Issue by feikname** [notepad-plus-plus/notepad-plus-plus#7669]
Just so you know it in case there's anything that should be fixed for it to be running again.

**Comment by favorini** [comment]
Links to docs (https://npp-user-manual.org/) and forums (https://community.notepad-plus-plus.org/) do not work. Main site (https://notepad-plus-plus.org/) is there.

**Comment by favorini** [comment]
Docs is working again for me. Note, you may have to flush your DNS cache (At Command Prompt: ipconfig /flushdns).

**Comment by favorini** [comment]
It looks like their DNS was hijacked or misconfigured (or maybe in the process of switching ISPs?). According to (https://who.is/dns/notepad-plus-plus.org) currently, notepad-plus-plus.org is pointing to 31.220.49.230, which is associated with dns-parking.com and hostinger.com, whereas www.notepad-plus-plus.org is pointing to 104.31.89.28, which is associated with cloudflare.net.

This seems suspicious. Maybe it was always that way, but I wouldn't trust any downloads until someone official comments here.

**Comment by donho** [comment]
https://twitter.com/Notepad_plus/status/1199352636027346944
