### ISSUE TITLE
[Feature request] I would like to have an option in config to force focus on editor window instead of doc switcher when having doc switcher enabled.

### ISSUE THREAD

**Issue by Spearfield** [notepad-plus-plus/notepad-plus-plus#7672]
I would like to have an option in config to force focus on editor window instead of doc switcher when having doc switcher enabled and starting Notepad++..

**Comment by Spearfield** [comment]
And "CTRL-TAB" does not go to editor window/pane from doc switcher if there is only one open editor tab.

**Comment by sasumner** [comment]
>And "CTRL-TAB" does not go to editor window/pane from doc switcher if there is only one open editor tab.

Why do you think it _should_ do that when that keycombo is pressed?

**Comment by Spearfield** [comment]
> Why do you think it _should_ do that when that keycombo is pressed?

After a little research (which I SHOULD have done BEFORE writing my comment) I found that the F8 does what I want.
But I still do like if there was an option to force focus on editor pane/window on startup instead of doc switcher.

**Comment by xylographe** [comment]
If you install the LuaScript plug-in, the following code in `startup.lua` might do the trick.
```lua
npp.AddEventHandler("OnReady", function()
  npp:MenuCommand(IDM_VIEW_SWITCHTO_OTHER_VIEW)
  return false
end)
```

**Comment by sasumner** [comment]
It seem the LuaScript option for this is a reasonable one, so I'm going to close this for now.  If there is a strong objection to this, will consider reopening.
