### ISSUE TITLE
Y and N keys no longer default to Yes and No in Save prompt after closing unsaved document

### ISSUE THREAD

**Issue by bassmanjase** [notepad-plus-plus/notepad-plus-plus#7673]
### Description of the Issue
IIRC, when the close-tab prompt was displayed, you used to be able to press Y or N as a shortcut to clicking the Yes or No buttons (to save or close the document). However, this feature recently went away - around the same time as the "Yes to all" and "No to all" options appeared.

### Steps to Reproduce the Issue
1. Create new document and enter some text
2. Close tab / press Ctrl+w
3. When the save prompt is displayed press the Y or N key

### Expected Behavior
When Y or N is pressed, this should have the same effect as clicking the Yes or No buttons

### Actual Behavior
The save prompt remains displayed and the new document is not saved or closed

### Debug Information
Notepad++ v7.8.1   (32-bit)
Build time : Oct 27 2019 - 22:46:07
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : ON
Local Conf mode : OFF
OS Name : Windows 10 Enterprise (64-bit) 
OS Version : 1909
OS Build : 18363.476
Plugins : ComparePlugin.dll mimeTools.dll NppConverter.dll NppExport.dll 

![image](https://user-images.githubusercontent.com/473329/69776122-af55af80-11e6-11ea-8646-ffdaae7a6f20.png)

**Comment by xylographe** [comment]
See https://github.com/notepad-plus-plus/notepad-plus-plus/issues/7670#issuecomment-558861519

**Comment by bassmanjase** [comment]
Thanks for referencing that comment, I didn't see the other issues when I initially searched. 

I don't have another language option to choose from in Preferences, I only installed English - are there instructions for how to fix it in this situation?

**Comment by xylographe** [comment]
I'm not sure, but I think, the following might work: (after updating `english.xml`)
- terminate NPP
- press **Win+R** to open the Windows Run dialogue
- enter `%APPDATA%\Notepad++` and click **OK** to open Windows Explorer
- delete `nativeLang.xml`
- start NPP

**Comment by donho** [comment]
It'll be in the next release:
cf7e373dca890d65ecc86489fe9cce1bcc7597f7
