### ISSUE TITLE
Notepad++ v7.8.1 - The power switch is not in the corner. There's a pixel error.

### ISSUE THREAD

**Issue by gecimli** [notepad-plus-plus/notepad-plus-plus#7674]
I'm using 2 screens. Laptop and monitor. The resolution of the two screens are 1920x1080 pixels.

There is a pixel error in one of the 2 pictures I added below.

When I take my mouse to the corner and close the screen, I press the close button of the different application because of the pixel error.

![1](https://user-images.githubusercontent.com/1707525/69789131-fa64c800-11d0-11ea-80e4-019fe5b3b482.png)

![2](https://user-images.githubusercontent.com/1707525/69789137-fdf84f00-11d0-11ea-88d0-2c3df3866811.png)

**Comment by tab328** [comment]
The workaround I use is right click the notepadd++.exe>properties>compatibility>change high DPI settings>Override...>change to "system"

I no longer have any issues with closing the wrong windows on any of my 3 extended monitors, and I have not noticed any issues resulting from this workaround. Please test this yourself and let us know if the workaround causes something else.

**Comment by sasumner** [comment]
Closing; let's make #8660 the controlling issue on this.
