### ISSUE TITLE
想对作者说的几点话

### ISSUE THREAD

**Issue by liyonghuan** [notepad-plus-plus/notepad-plus-plus#7676]
1.强烈反对开源软件政治化；
2.将整个民族归结为恐怖组织属于你自己错误的解读，请不要随意误导大众；
3.一直很喜欢Notepad++这款软件，但对作者这种根据花边新闻下定论的行为倍感失望；
4.听我一句劝：先把自己家庭关系处理好再考虑其他问题好吗？

**Comment by cathaychen** [comment]
他的家庭关系怎么了？能否贴出来让我笑两声
