### ISSUE TITLE
Column editor  in binary does not print a single-digit 0 when leading zeroes is unchecked

### ISSUE THREAD

**Issue by GhbSmwc** [notepad-plus-plus/notepad-plus-plus#7681]
Perhaps I want to print this:
```
0  
1  
10 
11 
100
```
So on the column editor, I did this:
![image](https://user-images.githubusercontent.com/13095760/69919959-7fa9e000-1450-11ea-8f51-4eeea971d520.png)
After pressing OK, the first in the column does not print a single-digit 0:
```
   
1  
10 
11 
100
```
This does not happen on other radixes.

**Comment by sasumner** [comment]
In this function in `ScintillaEditView.cpp`:

`TCHAR * int2str(TCHAR *str, int strLen, int number, int base, int nbChiffre, bool isZeroLeading)`

we could add the following "hacky fix" to the existing lines, but...it's rather "hacky" :-) :

```
if (!isZeroLeading)
{
    if (base == 2)
    {
        TCHAR *j = str;
        for ( ; *j != '\0' ; ++j)
            if (*j == '1')
                break;
        wcscpy_s(str, strLen, j);
        // add these next lines for a rather hacky fix:
        if (number == 0)
        {
            str[1] = '\0';
            str[0] = '0';
        }
    }
```

**Comment by donho** [comment]
It's been fixed since long time ago

**Comment by alankilborn** [comment]
> It's been fixed since long time ago

I don't think so.
In v8.4.6 here's what happens:

![image](https://user-images.githubusercontent.com/77065706/197518680-5db95498-1b10-475a-b379-9be7b9df8762.png)

![image](https://user-images.githubusercontent.com/77065706/197518732-cc2e7f08-005c-44a3-8edf-866921e67b17.png)

which is EXACTLY as the OP describes.
