### ISSUE TITLE
Highlight doesnt expand to duplicate view

### ISSUE THREAD

**Issue by KaptainBarn** [notepad-plus-plus/notepad-plus-plus#7684]
Hello,
Just noticed this minor bug today : highlighting an expression only works in one window. In the duplicate window the expression doesnt get highlighted.
Best,
Jules

**Comment by sasumner** [comment]
Please provide an example.  Screenshots welcome.

Note, we'd have these already if you'd have followed the template for issue reporting.

**Comment by sasumner** [comment]
Closing due to lack of response.
