### ISSUE TITLE
Plugin Admin does not uninstall plugins npp x86 on x64 machine

### ISSUE THREAD

**Issue by einst3** [notepad-plus-plus/notepad-plus-plus#7685]
### Issue
Plugin Admin does not uninstall plugins on x86 version of npp 7.8.1 on x64 windows 7.
will not even if npp is running as admin.

### Steps
1. try to uninstall any plugin (plugin admin, install tab, check any plugin (not installed by npp), click remove button).
2. restarts normally
3. plugin is still there

### Expected Behavior
plugin should no longer be in plugins menu and in x86 plugins folder.

### Actual Behavior
plugin is still there and also still in x86 plugins folder

### Debug Information
Notepad++ v7.8.1   (32-bit)
Build time : Oct 27 2019 - 22:46:07
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS Name : Windows 7 Professional (64-bit) 
OS Build : 7601.0
Plugins : ComparePlugin.dll DSpellCheck.dll HexEditor.dll HTMLTag_unicode.dll JSLintNpp.dll JSMinNPP.dll mimeTools.dll NppConverter.dll NppExport.dll NPPJSONViewer.dll NppSaveAsAdmin.dll NppTextFX.dll NppToolBucket.dll PoorMansTSqlFormatterNppPlugin.dll XMLTools.dll

**Comment by harecu** [comment]
Still an issue on v8.1.9.3 (64 bit)

**Comment by einst3** [comment]
no longer issue on newer version.

**Comment by tomm174** [comment]
Same happening with version 8.4.6,
Go to Plugin admin, find the plugin, click remove, NPP restarts, plugin folder is removed but it's effect is not.
The plugin in question is the Compare plugin.  
Before removal all changes were highlighted.
After removal all changes were highlighted.

Is it the case that plugins are compiled somehow, so removing the plugin folder doesn't remove their effect

I'm reluctant to completely re-install, as I've customised NPP a bit, but not sure what else to do

**Comment by alankilborn** [comment]
>I'm reluctant to completely re-install,

Yea, don't do that, it rarely changes anything (i.e., rarely solves a problem).
