### ISSUE TITLE
slow exit/close in winxp

### ISSUE THREAD

**Issue by geki007** [notepad-plus-plus/notepad-plus-plus#769]
Hi,

since 6.8.2 if i close notepad++ on winxp the program in the taskbar closes fast but i still see (~2-5 sec) the notepad++ window!

does not happen with 6.8.1 or with win7

could "Fix a visual glitch on starup and on exit." have caused a regression?!

**Comment by dail8859** [comment]
First I'd suggest trying it with all plugins disabled. Move or rename your plugins directory and restart N++ and see if the issue is still there. That way you can make sure it is not a plugin first.

**Comment by geki007** [comment]
oh yes, compare plugin is the problem (but there is/was no update)
but the plugin worked with 6.8.1

**Comment by milipili** [comment]
The plugin probably needs to be rebuilt.
