### ISSUE TITLE
Save dialog missing keyboard shortcuts

### ISSUE THREAD

**Issue by ozolins** [notepad-plus-plus/notepad-plus-plus#7694]
When closing modified file save dialog is displayed.
Currently it displays Yes, No, Cancel
But it should be &Yes, &No, &Cancel, so it would be possible to use keyboard.

This is actually regression, as it was working fine before upgrade.

**Comment by ikkentim** [comment]
Duplicate of #6223 which has already been fixed

**Comment by sasumner** [comment]
Closing as duplicate of the indicated issue.
