### ISSUE TITLE
Error the find dialog box

### ISSUE THREAD

**Issue by isDevNP** [notepad-plus-plus/notepad-plus-plus#7697]
I do not know what happened but I stopped working search box controls plugins and save files.

tried reinstalling.
after reinstalling fixed saving.

![image](https://user-images.githubusercontent.com/32579421/70224963-b9485700-1780-11ea-9aa8-2873e6774ccf.png)

[NppDump.zip](https://github.com/notepad-plus-plus/notepad-plus-plus/files/3926183/NppDump.zip)

> ОС Microsoft Windows 7 Максимальная "6.1.7601.24524"
> CPU Intel Core i7-6700K 4.00GHz 
> RAM	32,0 ГБ
> npp version 7.8.1 x64

**Comment by sasumner** [comment]
Please follow the template for submitting an issue.
