### ISSUE TITLE
The Save Menu buttons have no underscores for direct use with the keyboard

### ISSUE THREAD

**Issue by curpin** [notepad-plus-plus/notepad-plus-plus#7698]
### Description of the Issue

This is the version 7.8.1
When saving a new file, the Save popup menu asks if you want to Save, you have the options:
Yes, No, Cancel, Yes to all, No to all.
In the past, when getting this popup menu, there was an underline or underscore in the buttons, so the Yes button, for example had an underline under the Y (of the Yes), so in the keyboard you could just press Y and it would save, or N keystroke for not saving... now you have to either use tab key and then press enter or just use the mouse...
This was working in earlier versions, I guess before the new buttons "Yes to all" and "No to all" were introduced.

### Steps to Reproduce the Issue

1. create a new tab
2. type anything...
3. close the window (with ctrl+w, or simply close it with the mouse)
4. You will see the "Save" popup Window
5. The buttons do not appear with shortcuts Yes, with the "Y" underline, No with the "N" underlined...

### Debug Information

This is the current version of 7.8.1
![image](https://user-images.githubusercontent.com/11449241/70226960-0eb93f80-1752-11ea-9a33-9e18737e417b.png)

This is the old version where you see the Yes, No are underlined and work as shortcuts:
![image](https://user-images.githubusercontent.com/11449241/70227115-5344db00-1752-11ea-9622-8c0072d37d77.png)

**Comment by xylographe** [comment]
See https://github.com/notepad-plus-plus/notepad-plus-plus/issues/6223#issuecomment-561552991.

**Comment by curpin** [comment]
Thank you.  I have solved it this way, save the english.xml as english_customizable.xml modify the content to match the file name and add modify the "save" options and that did the trick. Thanks
