### ISSUE TITLE
Block cursor no longer wraps on whole line selection incl. newline in v7.8.1 x64

### ISSUE THREAD

**Issue by estockwell** [notepad-plus-plus/notepad-plus-plus#7699]
### Description of the Issue

I’m not sure when this first appeared, but in previous versions, with a block cursor, if you selected a whole line by clicking the line number on the left, the cursor would wrap to the next line, indicating a newline at the end of the current line. The block cursor no longer does this, and stays at the end of the currently selected line.

### Steps to Reproduce the Issue

1. Start with fresh (or portable) install of notepad++ v7.8.1 x64
2. In Settings, change cursor to "Block"
3. Write a few lines
4. Select an entire line by clicking the line number

### Expected Behavior

The whole line is selected and the cursor wraps to the beginning of the next line. Cursor widths 0, 1, 2, 3 all behave correctly here, but Block does not.

### Actual Behavior

The whole line is selected but the block cursor remains at the end of the current line.

**Comment by sasumner** [comment]
Does this have any other detrimental effects, besides bothering you visually?  I didn't note any in my testing of it.  It correctly includes the line-ending in the selection (provable by copy/paste).

**Comment by estockwell** [comment]
The selected text per copy/paste test is correct. The issue is with the inconsistency with the correct behavior of the other cursors, as this is a regression from its correct behavior in previous versions.

**Comment by estockwell** [comment]
To clarify further, this is more than just a visual nuisance, it is actually incorrect behavior. Selection to the end of the line not including the newline will look exactly the same as selecting the newline as well. Other cursors behave correctly when indicating selection of the newline and the block cursor does not.

**Comment by sasumner** [comment]
Additionally, for settings where the caret is set to blink, when the caret is in the position being discussed, it is non-blinking.

**Comment by Ekopalypse** [comment]
Just tested with SciTE 4.2.1 - behaves the same - looks like an scintilla issue.

**Comment by estockwell** [comment]
I've also noticed that block cursor position and carat position do not align when any text is selected from left to right. When text is highlighted from left to right, the cursor is -1 from where the carat is, but when selected from right to left, the carat is in the correct position. I guess that's the more general issue that's causing the behavior I saw.

**Comment by sasumner** [comment]
>Selection to the end of the line not including the newline will look exactly the same as selecting the newline as well.

I think I disagree with this.

Here's a result of "clicking the line number":

![image](https://user-images.githubusercontent.com/30118311/70260829-1af7c980-175f-11ea-9567-7d5bdabf779b.png)

And here is the result of selecting all four characters of `test` without the line-ending:

![image](https://user-images.githubusercontent.com/30118311/70260978-732ecb80-175f-11ea-9ea7-f006a7d44b8a.png)

Note that with the block caret, the block'd position is part of the selection.  It is odd but I'm not sure it is wrong.  Try this: Have no selection, caret in column 1, press Shift+right ---> caret doesn't move but one-character selection (hidden under caret) gets created.  Now continuing to press Shift+right works more naturally to extend the selection.

**Comment by sasumner** [comment]
>looks like an scintilla issue

Agree.  If fixing is going to get done, Scintilla would be the project that has to do it.

**Comment by estockwell** [comment]
The behavior you described is what it's doing, I was mistaken about that. I will edit my comment accordingly. So I think the bigger issue is that the block cursor is off by one from the carat when text is selected from left to right (but not right to left), and 1/2/3 pixel cursors are correctly aligned with the carat for the same highlighting.

**Comment by estockwell** [comment]
Should I change the title of this issue?

**Comment by sasumner** [comment]
>Should I change the title of this issue?

Nah, it's okay as is.

**Comment by zufuliu** [comment]
https://www.scintilla.org/ScintillaDoc.html#SCI_SETCARETSTYLE
Include CARETSTYLE_BLOCK_AFTER to draw block caret outside of selection, the default is inside. But it seems will conflict with other issues about block caret like #5716 and #5833, etc.

**Comment by zufuliu** [comment]
A ticket is added at https://sourceforge.net/p/scintilla/bugs/2145/

**Comment by alankilborn** [comment]
Since #11944 has been fixed with the addition of a new "Block After" choice in the Preferences, this issue can be CLOSED as well.

**Comment by donho** [comment]
https://github.com/notepad-plus-plus/notepad-plus-plus/commit/70660eb608eea7a9c85a4bfb08761ffd6bfbc887
