### ISSUE TITLE
Font size/color lost when upgrading

### ISSUE THREAD

**Issue by griggs01** [notepad-plus-plus/notepad-plus-plus#77]
PortableApps version 6.7.5 and later (current 6.7.7). When upgrading to a new version of Notepad++, the user-modified font size and style are overwritten. Request these files not be installed by default unless they do not exist. Installation by user selection (radio button plus restart?) would allow users to  deal with more extensive user errors.

**Comment by MetaChuh** [comment]
closed due to:
* inactivity.
* stylers.xml is not distributed in portable versions, and copying stylers.model.xml, themes, config.xml and/or other customised files, can be skipped by choice, when upgrading a portable version.
