### ISSUE TITLE
Patch notes only say that you hate china?

### ISSUE THREAD

**Issue by Chaython** [notepad-plus-plus/notepad-plus-plus#7703]
Patch notes only say that you hate china?

**Comment by lidskialf** [comment]
> Notepad++ v7.8.2 enhancements and bug-fixes:
> 
> 1.  Add key shortcuts in Save or not dialog.
> 2.  Add find in files filter excluding ability.
> 3.  Add "Open UDL folder" command.
> 4.  Fix issue of showing save dialog twice while cloned file is dirty.
> 5.  Enhance "Open Explorer" command in Folder as workspace with expected path.
> 6.  Fix tab dragging issues.
> 7.  Enhance "Close all but This" and "Close all to the left/right" commands while files are dirty.
> 8.  Enhance "In Selection" option in Find dialog.
> 9.  Fix Notepad++ blocked in notification zone issue.
> 10. Make end-of-line conversion operations macroable.
> 11. Fix "View Current File In" commands disabled problem in some situations.

[Notepad++ v7.8.2 Changelog](https://community.notepad-plus-plus.org/topic/18589/notepad-v7-8-2-free-uyghur-edition)

**Comment by Chaython** [comment]
Thanks, when I clicked changelog from the one page it just directed me to a rant about DDOS attacks and how he woun't be silenced.
