### ISSUE TITLE
Mapping Select and Find Previous to CTRL+SHIFT+ALT+F does not work

### ISSUE THREAD

**Issue by peteralieber** [notepad-plus-plus/notepad-plus-plus#7706]
### Description of the Issue
I have mapped Select and Find to CTRL+SHIFT+F and CTRL+SHIFT+ALT+F (Previous).  However, on the Next works. Nothing appears to happen when I hit CTRL+SHIFT+ALT+F.  There are no conflicts, and it used to work in previous versions of Notepad++ (not work when it broke). 

### Steps to Reproduce the Issue

1.  Map Select and Find Next to CTRL+SHIFT+F
2.  Map Select and Find Previous to CTRL+SHIFT+ALT+F
3.  Hit  CTRL+SHIFT+ALT+F and observe that nothing happens

### Expected Behavior
I expect it to find the previous occurrence of the selected text

### Actual Behavior
Noting

### Debug Information
Notepad++ v7.8.1   (32-bit)
Build time : Oct 27 2019 - 22:46:07
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS Name : Windows 10 Enterprise (64-bit) 
OS Version : 1903
OS Build : 18362.476
Plugins : ComparePlugin.dll DSpellCheck.dll mimeTools.dll NppConverter.dll NppExport.dll 

![image](https://user-images.githubusercontent.com/41489571/70347300-e0a52f80-1825-11ea-9628-34b402b6db45.png)

**Comment by alankilborn** [comment]
Tested in N++ 8.4.4 (current version as of this writing) and could not repro.
Recommend CLOSURE of this item.
