### ISSUE TITLE
Close all Unchanged doesn't work for "Other View"

### ISSUE THREAD

**Issue by bahusoid** [notepad-plus-plus/notepad-plus-plus#7708]
Steps to reproduce: 
1) Open Notepad++;
2) Open 2 documents;
3) Move one to Other View (righ click on tab -> Move To Other View);
4) Create 2 new documents in Other View and add some text in it;
5) Right click on  new modified doc -> Close All Unchanged:
![image](https://user-images.githubusercontent.com/22025304/70374383-2b907700-18fa-11ea-93b0-e8d48b43aa7a.png)

6) Exception is thrown:
![image](https://user-images.githubusercontent.com/22025304/70374348-e4a28180-18f9-11ea-883a-17cbd3d1ab80.png)

Notepad++ v7.8.2   (32-bit)
Build time : Dec  4 2019 - 01:36:59
Path : C:\Programs\npp.7.8.2.bin.minimalist\notepad++.exe
Admin mode : OFF
Local Conf mode : ON
OS Name : Windows 10 Enterprise (64-bit) 
OS Version : 1903
OS Build : 18362.476
Plugins : none

Dump file created after exception:
[NppDump.zip](https://github.com/notepad-plus-plus/notepad-plus-plus/files/3935035/NppDump.zip)

**Comment by bahusoid** [comment]
Ping @jmbockhorst  (author of feature imlemented in #5185)

**Comment by xylographe** [comment]
@bahusoid
You can test by replacing `notepad++.exe` with `Notepad++.Win32.Unicode Release.exe`  from [AppVeyor Artifacts](https://ci.appveyor.com/project/donho/notepad-plus-plus/builds/29382819/job/20mt1hsfo4yrr2nf/artifacts). Do NOT replace `SciLexer.dll`.

**Comment by bahusoid** [comment]
@xylographe It works, thanks
