### ISSUE TITLE
download progress bar percentage is not initialized

### ISSUE THREAD

**Issue by jpvanleeuwen** [notepad-plus-plus/notepad-plus-plus#7722]
### Description of the Issue
When a new package is available and starts to download, the progress percentage starts at a very large number in stead of 0%

### Steps to Reproduce the Issue
1.  If a new package is available, get it and look at the progress bar
See also comment under extra info. It may be that this can not be initialised on all systems.

### Expected Behavior
Download starts at 0 %
### Actual Behavior
See above

### Debug Information
Notepad++ v7.8.1   (64-bit)
Build time : Oct 27 2019 - 22:57:19
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS Name : Windows 10 Home (64-bit) 
OS Version : 1903
OS Build : 18362.476
Plugins : DSpellCheck.dll mimeTools.dll NppConverter.dll NppExport.dll 

Suspected cause: the download progress percentage variable is not initialised.
!!!
This also means that on some systems the percentage may start at 0, because the memory location of the uninitialised variable may be zero by chance.

**Comment by donho** [comment]
You were using v7.8 or upper version to download v7.8.1.
This issue has been fixed in 7.8.1
