### ISSUE TITLE
Disable buttons when "In selection" checked (find-replace dialog)

### ISSUE THREAD

**Issue by h-h-h-h** [notepad-plus-plus/notepad-plus-plus#773]
Hello,

instead of having a box around the "In selection" checkbox and the "Replace All" button, checking "In selection" could disable the buttons not applicable, as "Find Next".

For an issue taking this a step further see: https://github.com/notepad-plus-plus/notepad-plus-plus/issues/776.

**Comment by donho** [comment]
Outdated
