### ISSUE TITLE
[Feature Request] N++ skins

### ISSUE THREAD

**Issue by LAPIII** [notepad-plus-plus/notepad-plus-plus#7732]
A dark skin would be great to go with a dark theme, to darken the title bar, menu toolbar, tabs, and status bar. I don't use Windows 10 High Contrast Theme because it interferes with an app, Windows Dark Mode doesn't darken N++.

**Comment by LAPIII** [comment]
Is there a way that I can darken these things?

**Comment by webfischi** [comment]
I really hope that there wil be a UI rework for Version 8, that allows a real dark mode. I can't remember one still maintained open source software that looked the same for 16 years and 1 month. You can also still activate the original large toolbar items from 2003. Even the website got a dark mode recently.

**Comment by ArkadiuszMichalski** [comment]
@sasumner 
This can be close, a lot of other bugs was open for the same (https://github.com/notepad-plus-plus/notepad-plus-plus/issues/7692, https://github.com/notepad-plus-plus/notepad-plus-plus/issues/8190, https://github.com/notepad-plus-plus/notepad-plus-plus/issues/5852).
