### ISSUE TITLE
User-configurable command line interpreter

### ISSUE THREAD

**Issue by xylographe** [notepad-plus-plus/notepad-plus-plus#7737]
It would be nice if it would be possible to replace the invoked command line interpreter with something more user-friendly than the archaic `cmd.exe` without having to modify the source code. For example, by adding a _CommandLineInterpreter_ setting in `config.xml`.

**Comment by donho** [comment]
What interpreter can user set other than cmd?

**Comment by sasumner** [comment]
I might guess "Powershell"...?

**Comment by donho** [comment]
Why not? But such request has never made (except this one). I wonder if it's needed such feature.

**Comment by xylographe** [comment]
> What interpreter can user set other than cmd?

I have been happily using powershell for several years. At first, I replaced `TEXT("cmd")` with `TEXT("powershell")`, but later on I decided to make it more flexible with a configurable setting.

Other interpreters, better than cmd, would be zsh, bash, tcsh, or fish.

> But such request has never made

Perhaps, I'm the last surviving shell aficionado? :wink:

**Comment by sasumner** [comment]
@donho My feeling this is a reasonable change.  Unless you want an explicit "Open...Powershell" to sit alongside "Open...CMD".

@xylographe said "I'm the last surviving shell aficionado?"  For me, my user base is still most-familiar with CMD, but it seems that Micro$oft is finally promoting something else (Powershell) with Windows 10, so it may change.
