### ISSUE TITLE
Find Dialog have resize corner but it's actually not working (Win 8)

### ISSUE THREAD

**Issue by KvanTTT** [notepad-plus-plus/notepad-plus-plus#774]
I am trying to resize this dialog but can not do it

![find dialog resize](https://cloud.githubusercontent.com/assets/1150330/9409506/c9eaa29c-4823-11e5-9240-0dc98fc65526.png)

**Comment by Rikk** [comment]
It was always a false resize mark...

**Comment by h-h-h-h** [comment]
It would be possible to remove the corner. But this feature would require it again to be resizable: https://github.com/notepad-plus-plus/notepad-plus-plus/issues/563. So it's not a problem to make it resizable while the other feature not implemented.

**Comment by dg9ngf** [comment]
I don't see how #563 is related to this issue.

IMO the resize grip simply needs to be removed. Should be a simple flag or option to set correctly to reflect the window's actual properties. #563 could add this grip again, but until then it's irritating.

**Comment by dg9ngf** [comment]
Oh, and the browse for folder dialog is actually a pretty ancient one. Windows Vista introduced new file dialogs that are much easier to use. They can also be used to select folders now, replacing that ugly and unfriendly folder browse dialog from the older days. NPP already makes use of the latest file dialog version in open/save, so it should also do so in the find dialog.

**Comment by h-h-h-h** [comment]
Because issue #563 contains a greater number of sub-issues, I meant it wouldn't hurt to make the dialog resizable separately. Let us see how the developer decides.
