### ISSUE TITLE
Publish MinGW Build Instructions

### ISSUE THREAD

**Issue by sasumner** [notepad-plus-plus/notepad-plus-plus#7743]
@donho to publish MinGW build instructions for Notepad++, Scintilla, Boost

Also, perhaps the contributing guidelines should be updated so that contributors know that they should check their PR for build problems with MinGW before submitting.

Reference link: https://github.com/notepad-plus-plus/notepad-plus-plus/commit/53452d96e0bf17f9f5eaaeec9c6beb2424f6d8cd#r36432951

**Comment by sasumner** [comment]
I've noticed in the Visual Studio project settings, the setting to treat warnings as errors is turned on.  

* Is this same option turned on in the VS appveyor builds?

* Is an equivalent option turned on in the MinGW appveyor builds?  (I can answer this one and say "no" because I was browsing some of the MinGW appveyor build output and saw warning output although the overall build was successful; here's what I was browsing: https://ci.appveyor.com/project/donho/notepad-plus-plus/builds/29761761/job/3urhas35fcxeg3oh )

**Comment by xylographe** [comment]
Yes in the VS appveyor builds,
- `/W4`  show severe, significant, production quality and informational warnings.
- `/WX`  treat all compiler warnings as errors.

The g++ equivalent of `/WX` is `-Werror`.

**Comment by sasumner** [comment]
Begs the question, why isn't it turned on in the MinGW builds?

**Comment by xylographe** [comment]
Because the MinGW build would fail with `-Werror`. First all the warnings would need to be resolved.

**Comment by sasumner** [comment]
I'll revise the question:  Why isn't it turned on in the MinGW builds and the warnings resolved? :-)

**Comment by donho** [comment]
@sasumner 
The aim of mingw build is for providing more options to build Notepad++ but since the official release  is not built by it, the project won't be aligned with it.

**Comment by sasumner** [comment]
@donho said:

>The aim of mingw build is for providing more options to build Notepad++ but since the official release is not built by it, the project won't be aligned with it

Does that mean we won't be getting build instructions for mingw?
If so we can Close this issue.
But I have further questions/comments:

- I would like to build my PRs with mingw before submitting so that I know appveyor builds won't fail on mingw build.  This has happened to me two times previously.

- Rare discussion of mingw builds seem involve Linux.  I would like to do mingw builds on Windows machine as I currently have no Linux.  Is this reasonable?

- If mingw build is to remain "secret", can we stop appveyor building it?

- Maybe build instructions for mingw are "simple" and I just don't realize it.  I have thought about getting mingw tools and just trying to build, but I don't even know what version to get.  Looking at appveyor output it has some info on what it is using, but I can't find the exact thing when I search.

**Comment by donho** [comment]
@chcg  Could you take care of this issue please ?

**Comment by sasumner** [comment]
@donho @chcg 

I can take this on if someone can help me get started.
Where do I get the "correct" toolchain for this?

**Comment by donho** [comment]
@sasumner @chcg 
I have tried to install MinGW on my PC then launched `makefile`, but without success.
If you guys can make it and document it and I can validate with the practice, it will be great.

**Comment by chcg** [comment]
See https://github.com/notepad-plus-plus/notepad-plus-plus/blob/master/appveyor.yml and there the parts with mingw-w64_810_X64:

- set PATH=C:\mingw-w64\x86_64-8.1.0-posix-seh-rt_v6-rev0\mingw64\bin;%PATH:C:\Program Files\Git\usr\bin;=%
- cd <N++_git_dir>\scintilla\win32
- mingw32-make -j%NUMBER_OF_PROCESSORS%
- cd  <N++_git_dir>\PowerEditor\gcc\ & mingw32-make -j%NUMBER_OF_PROCESSORS%

For linux see #7900

**Comment by sasumner** [comment]
Where to get toolchain for "mingw-w64_810_X64"?  
Link?

>For linux see # 7900

I can't say I care too much for building under Linux at the current time.

**Comment by donho** [comment]
@chcg  Could you point out the download url to me please? I believe that I have download the wrong package, that made my build failed.

**Comment by chcg** [comment]
See https://www.appveyor.com/docs/windows-images-software/#mingw-msys-cygwin, so
C:\mingw-w64\x86_64-8.1.0-posix-seh-rt_v6-rev0 is installed already on the build machines.
This could be downloaded from https://sourceforge.net/projects/mingw-w64/files/ -> https://sourceforge.net/projects/mingw-w64/files/Toolchains%20targetting%20Win64/Personal%20Builds/mingw-builds/8.1.0/threads-posix/seh/x86_64-8.1.0-release-posix-seh-rt_v6-rev0.7z

Website: https://mingw-w64.org/doku.php/start

Another option would be the usage of msys2 (https://www.msys2.org/) as it could contain also mingw-w64 even with a newer GCC version.

**Comment by donho** [comment]
Thank you very much @chcg 
I compiled `NotepadPP.exe` with success in `PowerEditor\bin` directory!
However, I ran the generated executable binary (with the signed ScinLexer.dll generated by MS VS), but nothing happen.
What do I miss?

**Comment by donho** [comment]
@chcg 
Can we run mingw-w64_810_X64 Unicode Release build from artifact?
https://ci.appveyor.com/project/donho/notepad-plus-plus/builds/36191732/job/s71ou5g6tg2h1wtj/artifacts ?
If we can, how?

**Comment by donho** [comment]
Can anyone run mingw-w64_810_X64 Unicode Release build from artifact?
https://ci.appveyor.com/project/donho/notepad-plus-plus/builds/36264360/job/h2j1rqm2wr2e98bq/artifacts

I cannot make it run (it crashes) in my Windows XP. I wonder if we should remove minGW's build since it is not useful.

**Comment by ArkadiuszMichalski** [comment]
Works for me in Windows7.

Notepad++ v7.9.1   (64-bit)
Build time : Nov 12 2020 - 01:55:14
Path : C:\Users\Arek\Desktop\npp.7.9.1.portable.x64\notepad++.exe
Admin mode : ON
Local Conf mode : ON
OS Name : Windows 7 Ultimate (64-bit) 
OS Build : 7601.24136
Current ANSI codepage : 1250
Plugins : mimeTools.dll NppConverter.dll NppExport.dll

**Comment by chcg** [comment]
The artifact https://ci.appveyor.com/api/buildjobs/s71ou5g6tg2h1wtj/artifacts/Notepad%2B%2B.mingw.Unicode%20Release.exe needs to be combined with a signed scilexer.dll + the necessary N++ config files. So it is easiest to use a portable setup e.g. https://github.com/notepad-plus-plus/notepad-plus-plus/releases/download/v7.9.1/npp.7.9.1.portable.x64.7z as startnig point.

**Comment by ArkadiuszMichalski** [comment]
@chcg first step in https://github.com/notepad-plus-plus/notepad-plus-plus/issues/7743#issuecomment-673097080 is correct? I mean:
`set PATH=C:\mingw-w64\x86_64-8.1.0-posix-seh-rt_v6-rev0\mingw64\bin;%PATH:C:\Program Files\Git\usr\bin;=%`
I see such line in https://github.com/notepad-plus-plus/notepad-plus-plus/blob/master/appveyor.yml#L23.

Should not be:
`set PATH=C:\mingw-w64\x86_64-8.1.0-posix-seh-rt_v6-rev0\mingw64\bin;C:\Program Files\Git\usr\bin;%PATH%`
?

**Comment by chcg** [comment]
See https://stackoverflow.com/questions/21289762/remove-unwanted-path-name-from-path-variable-via-batch, with the command `C:\Program Files\Git\usr\bin` is removed from the path variable as the shell command coming with the git blocked the usage of mingw counterparts.
