### ISSUE TITLE
notepad++ crashes when opening a file whose path containing folder beginning with "#"

### ISSUE THREAD

**Issue by smalldust** [notepad-plus-plus/notepad-plus-plus#7744]
### Description of the Issue

In Windows 10, if there is a text file under a folder whose name begins with "#", such as "#test", and leave that file open in notepad++, notepad++ will stop to respond during next start.

### Steps to Reproduce the Issue

1. In Windows 10, creat a folder and name it "#test" (without quotations)
2. Under this folder, create a text file a.txt
3. Open a.txt with notepad++, write something and save.
4. Leave a.txt open in notepad++, and close notepad++
5. Re-start notepad++
6. Notepad++ stops to respond while trying to re-open "#test\a.txt"
7. Pleas note: directly open a.txt from notepad++ menu/context menu does NOT reproduce this problem.

### Expected Behavior

Notepad++ is supposed to reload files that are left open.

### Actual Behavior

However it stops to respond.

### Debug Information

Because the program stops to respond, I was not able to get any debug info.

**Comment by sasumner** [comment]
No problems occurred for me when trying to reproduce.

Notepad++ v7.8.2   (32-bit)
Build time : Dec  4 2019 - 01:36:59
Path : C:\........\npp.7.8.2.bin\notepad++.exe
Admin mode : OFF
Local Conf mode : ON
OS Name : Windows 10 Enterprise (64-bit) 
OS Version : 1709
OS Build : 16299.1508
Plugins : mimeTools.dll NppConverter.dll NppExport.dll

**Comment by xylographe** [comment]
Cannot reproduce. Perhaps, you can to start NPP from the command line with the noPlugin option:
`notepad++.exe -noPlugin`
```
Notepad++ v7.8.2  (32-bit)
Build time : Dec 16 2019 - 03:37:15
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS Name : Windows 7 Ultimate (64-bit) 
OS Build : 7601.0
```

**Comment by smalldust** [comment]
This problem did not happen again after I restart my PC.
Not sure why but might be a Windows OS problem.
Neither can I reproduce it on my other laptops.

Therefore I will hereby close this issue.
