### ISSUE TITLE
Wrong behavior of "Find in Files"

### ISSUE THREAD

**Issue by Antonytm** [notepad-plus-plus/notepad-plus-plus#7745]
### Description of the Issue
Notepad++ is not able to find in files some string.

### Steps to Reproduce the Issue
1. Open file 1.txt from c:\test directory with content "original"
2. Edit this file in Notepad++, set content "notepad"
3. Open this file in any other editor, revert content back to "original"
4. Notepad++ will ask you to reload file, select NO. Don't reload file
5. Open "Find in Filese" dialog
6. Search for "Find what":"original", "Directory": "c:\test"

### Expected Behavior
1 hit in 1 file, 1.txt

### Actual Behavior
0 hits in 0 files

### P.S.
I assume that there is some optimization for search, it looks not in file content, but in open files. It causes this unexpected behavior.

**Comment by sasumner** [comment]
> it looks not in file content, but in open files

This behavior is by-design.  If a file is open in the editor, the (potentially modified) content will be searched rather than the file on disk.

**Comment by Antonytm** [comment]
That is confusing.

"(potentially modified) content will be searched" 
It can make sense, when you modified file in Notepad++, but file wasn't modified in Notepad++. It was modified outside.

To search in opened files, there is another button "Find all in all opened documents". 
File is file. It is data on disk. Data in memory on Notepad++ is not file.
