### ISSUE TITLE
Move 'Normal Text' to top in Languages Menu

### ISSUE THREAD

**Issue by rhaokiel** [notepad-plus-plus/notepad-plus-plus#7746]
I'm rather surprised that I've found no requests for this as of yet. [But I know I'm not the only one who finds the current setup unintuitive.](https://stackoverflow.com/questions/40636584/how-do-i-turn-off-syntax-highlighting-for-txt-files-in-notepad)

'Normal Text' is the language highlighter that essentially removes all code/keyword highlighting. This makes 'Normal Text' act like a kind of zero or origin on this menu.

Because 'Normal Text' could have been represented by other words, what makes the general user think that they should look under the 'N' flyout to clear the highlighting?

My suggestion is to move it to its own grouping above the alphabetically listed languages with a menu separator between.

**Comment by andrecool-68** [comment]
Go into the settings and clear this flag, and you can hide the syntax of languages that you do not use. After that, it will become much more convenient for you!
![Безымянный](https://user-images.githubusercontent.com/3471892/71305351-33144d80-23db-11ea-8edd-819096007c0f.png)

**Comment by rhaokiel** [comment]
@andrecool-68 I am familiar with the ability to compact the language menu. However, I am a developer. I have a wide range of languages that I use. Your suggested workaround doesn't solve the issue that I presented.
