### ISSUE TITLE
Not localized context menu entry "Edit with Notepad++"

### ISSUE THREAD

**Issue by gmikhail** [notepad-plus-plus/notepad-plus-plus#7747]
### Description of the Issue

Regardless of the language selected during installation, the context menu is always "Edit with Notepad++"

![Аннотация 2019-12-16 195538](https://user-images.githubusercontent.com/4838367/70930539-217b2080-203e-11ea-880c-cbb01b972a2f.png)

### Steps to Reproduce the Issue

1. Run installer in non-english language (eg russian)
2. Install Notepad++ (eg x64) with context menu entry and non-english localization file (eg russian)
3. You will see in the context menu (RMB on a text file) "Edit with Notepad++"

### Expected Behavior

When I choose Russian localization I want get "Изменить в Notepad++" in context menu entry

### Actual Behavior

I always get "Edit with Notepad++" in context menu entry

### Debug Information

Notepad++ v7.8.2   (64-bit)
Build time : Dec  4 2019 - 01:39:49
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS Name : Windows 10 (64-bit) 
OS Version : 1909
OS Build : 18363.535
Plugins : mimeTools.dll NppConverter.dll NppExport.dll

**Comment by andrecool-68** [comment]
1) Открой каталог где находиться файл notepad++.exe
2) Запусти командную строку из этого каталога с этим кодом:
`regsvr32 /s /i NppShell_06.dll`

Перед вами появиться данное окно ...там и делайте свою локализацию!
![Безымянный](https://user-images.githubusercontent.com/3471892/70997435-c436ac00-20dd-11ea-9dc3-3930240b763d.png)

Чтобы удалить запись из контекстного меню, запустите из каталога где находиться файл notepad++.exe следующий код:
`regsvr32 /s /u NppShell_06.dll`

**Comment by andrecool-68** [comment]
Второй вариант это редактировать файл shortcuts.xml

			<Command name="Add Notepad++ to the context menu" Ctrl="no" Alt="no" Shift="no" Key="0">regsvr32 /s /i NppShell_06.dll</Command>
			<Command name="Remove Notepad++ from the context menu" Ctrl="no" Alt="no" Shift="no" Key="0">regsvr32 /s /u NppShell_06.dll</Command>
		</UserDefinedCommands>
И теперь все эти операции можно делать из меню RUN

![Безымянный](https://user-images.githubusercontent.com/3471892/70998156-4ffd0800-20df-11ea-8f99-fc3ab29a10d6.png)

**Comment by andrecool-68** [comment]
Третий вариант это открыть редактор реестра и найти фразу `Edit with &Notepad++` и отредактировать ее!
![Безымянный](https://user-images.githubusercontent.com/3471892/70999149-80de3c80-20e1-11ea-8ab8-3430056ca1cc.png)

**Comment by gmikhail** [comment]
@andrecool-68 спасибо, использовал первый вариант!

Только саму проблему это не решает. Проблема либо в локализации (нет перевода), либо в инсталляторе (игнорирует выбранный язык).

---

@andrecool-68 thanks, used the first option!

But this does not solve the problem. The problem is either in localization (no translation), or in the installer (ignores the selected language).

**Comment by andrecool-68** [comment]
@gmikhail В файле `NppShell_06.dll` только английский язык! Его можно сделать и многоязычным, но будет ли подхватываться эта локализация при установке я не знаю. Честного говоря эта опция для меня вообще не актуальная так как я всегда использую портативную версию. А запись в контекстное меню добавляю ...вторым способом

**Comment by xylographe** [comment]
Here is an example of a localized entry in the Registry,
```
value name:  FriendlyAppName
value type:  REG_SZ
value data:  @C:\Program Files\Subtitle Edit\SubtitleEdit.resources.dll,-10000
```
The number (10000) identifies the resource (STRINGTABLE) in the DLL. The table contains a string for each supported language.

**Comment by donho** [comment]
There's no way to localize context menu grammatically.

**Comment by xylographe** [comment]
@donho 
There is! The context menu entry can be created dynamically (as opposed to a static Registry entry).
_Hash Check Shell Extension_, for example, [works this way](https://github.com/gurnec/HashCheck/blob/master/CHashCheck.cpp#L95) (`IDS_HS_MENUTEXT` is the StringTable identifier for the localized "Create Checksum File..." string).

**Comment by gmikhail** [comment]
I propose to reopen this issue as a bug because after each update the context menu translation is reset. The proposed solution does not solve the problem itself.

**Proposal for fix**: add localization strings of context menu to the installer and apply it during installation or add localization to Notepad++ with the ability to disable/enable the context menu.

Right now "Edit with Notepad++" is hardcoded in `PowerEditor\src\tools\NppShell\src\NppShell.cpp`

```
//Menu
TCHAR szNppName[] = TEXT("notepad++.exe");
TCHAR szDefaultMenutext[] = TEXT("Edit with &Notepad++");
```

**Comment by Hexaae** [comment]
I agree, and I opened a similar thread BTW (didn't know this one): 
https://community.notepad-plus-plus.org/topic/18709/localize-notepad-context-menu-items/4

**Comment by andrecool-68** [comment]
Read and don't fool eggs:
https://github.com/notepad-plus-plus/notepad-plus-plus/issues/7741

**Comment by donho** [comment]
It's possible to localize explorer context menu entry under Windows 11 - implemented in #13170
