### ISSUE TITLE
Underlined access keys missing from Save modal, ALT+N does nothing

### ISSUE THREAD

**Issue by sparrowt** [notepad-plus-plus/notepad-plus-plus#7748]
### Description of the Issue
I recently upgraded to Notepad++ v7.8.1 (64-bit) and found that keyboard shortcuts on the 'Save' dialog no longer work.

### Steps to Reproduce the Issue

1. Enter some text in a new unsaved document
2. Try to close Notepad++ and the 'Save' dialog appears:
![image](https://user-images.githubusercontent.com/793763/70986132-38a92500-20b5-11ea-88e5-92c81369e2d7.png)
3. Press `Alt`+`N` to choose the 'No' option - nothing happens

### Expected Behavior

The 'No' option should have the `N` underlined so it can be selected using `Alt`+`N` as previously worked in Notepad++ and is common to many programs. I can work around this by pressing `TAB` and then `ENTER` but muscle memory is stubborn, plus it's a shame to lose this standard functionality and require a slower alternative to be used.

### Actual Behavior

Nothing happens - I have to find a new way to choose the 'No' button.

### Debug Information
Windows 10 1809 (17763.864)

![image](https://user-images.githubusercontent.com/793763/70986306-8cb40980-20b5-11ea-9dac-5034a2ea8fbb.png)

**Comment by xylographe** [comment]
Update to v7.8.2

**Comment by sparrowt** [comment]
Many thanks, looks like cf7e373dca890d65ecc86489fe9cce1bcc7597f7 was the ticket 👍
