### ISSUE TITLE
Focusing and hovering the [×] button on a tab

### ISSUE THREAD

**Issue by AldoThaler** [notepad-plus-plus/notepad-plus-plus#7750]
### Description of the Issue
The [×] button on a tab is displayed incorrectly when focusing it and hovering over it again.

### Steps to Reproduce the Issue
1. Hover over the [×] button next to the name of a tab
2. Press and hold the left mouse button (focus) and leave the [×] button
3. Release the left mouse button and hover over the [×] again

### Expected Behavior
Display the actual mouse-over version of the [×] button:
![mouse-over](https://user-images.githubusercontent.com/20143085/70934351-06101580-203e-11ea-9bd2-bfbfa657a3dd.png)

### Actual Behavior
The mouse-down version was displayed.
![mouse-down](https://user-images.githubusercontent.com/20143085/70934370-0dcfba00-203e-11ea-8595-8307d1961777.png)

Clicking the tab or any other tab fixes this behavior.

### Debug Information
Notepad++ v7.8.2   (32-bit)
Build time : Dec  4 2019 - 01:36:59
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS Name : Windows 10 Home (64-bit) 
OS Version : 1909
OS Build : 18363.535
Plugins : DSpellCheck.dll mimeTools.dll NppConverter.dll NppExport.dll

**Comment by Ekopalypse** [comment]
Does not happen to me. Regardless if npp is the active window or not,
or if the tab is the active one, I always see the [x] highlighted when hovering over it.

Notepad++ v7.8.2   (64-bit)
Build time : Dec  4 2019 - 01:39:49
Path : D:\...\notepad++.exe
Admin mode : OFF
Local Conf mode : ON
OS Name : Windows 7 Professional (64-bit) 
OS Build : 7601.23934
Plugins : ...

**Comment by ArkadiuszMichalski** [comment]
@AldoThaler Do you still have this problem in latest Notepad++ version? I also can't reproduce with above steps.

**Comment by ErwanDelhoveUCL** [comment]
I found a way to remove such a behavior but the actual code doesn't help to remove it in every case.
There is a part of code which should be call in order to remove this behavior but is in fact never use (I guess).

```c++
		....
		bool isFromTabToTab = false;

		int iTabNow = getTabIndexAt(p.x, p.y); // _currentHoverTabItem keeps previous value, and it need to be updated

		if (_currentHoverTabItem == iTabNow && _currentHoverTabItem != -1) // mouse moves arround in the same tab
		{
			// do nothing
		}
		else if (iTabNow == -1 && _currentHoverTabItem != -1) // mouse is no more on any tab, set hover -1
		{
			 // NEVER ENTER HERE
			// NEEDED IN ORDER TO REMOVE BEHAVIOR WHEN LEAVING TAB
			_currentHoverTabItem = -1; 

			// send mouse leave notif
			notify(TCN_MOUSELEAVING, -1);
		}
		else if (iTabNow != -1 && _currentHoverTabItem == -1) // mouse is just entered in a tab zone
		{
			_currentHoverTabItem = iTabNow;

			notify(TCN_MOUSEHOVERING, _currentHoverTabItem);
		}
		else if (iTabNow != -1 && _currentHoverTabItem != -1 && _currentHoverTabItem != iTabNow) // mouse is being moved from a tab and entering into another tab
		{
			isFromTabToTab = true;
			// THIS PART WORKS
			// set current hovered
			_currentHoverTabItem = iTabNow;

			// send mouse enter notif
			notify(TCN_MOUSEHOVERSWITCHING, _currentHoverTabItem);
			}
			else if (iTabNow == -1 && _currentHoverTabItem == -1) // mouse is already outside
			{
				// do nothing // ALSO NEVER ENTER HERE
			}
```

This code is in the [TabBar.cpp file](https://github.com/notepad-plus-plus/notepad-plus-plus/blob/master/PowerEditor/src/WinControls/TabBar/TabBar.cpp#L688).
[Here](https://github.com/notepad-plus-plus/notepad-plus-plus/blob/0689a9445343a6c99f11959d8b4a91d598bc8495/PowerEditor/src/WinControls/TabBar/TabBar.cpp#L688)
