### ISSUE TITLE
Incremental Search: remember selected options

### ISSUE THREAD

**Issue by cmeriaux** [notepad-plus-plus/notepad-plus-plus#7753]
### Description of the Issue
On Increment search bard, remember state of "Highlight all"

### Steps to Reproduce the Issue

1. open incremental bar
2. enable 'highlight all' option and 'match case' option
3. close the bar
4. open the bar
5. selected options has been lost

### Expected Behavior
1. open incremental bar
2. enable 'highlight all' option and 'match case' option
3. close the bar
4. open the bar
5. options are still selected

### Actual Behavior

1. open incremental bar
2. enable 'highlight all' option and 'match case' option
3. close the bar
4. open the bar
5. options are lost

### Debug Information

	Notepad++ v7.8.2   (32-bit)
	Build time : Dec  4 2019 - 01:36:59
	Path : D:\download\npp.7.8.2.bin\notepad++.exe
	Admin mode : OFF
	Local Conf mode : ON
	OS Name : Windows 10 Home (64-bit) 
	OS Version : 1809
	OS Build : 17763.914
	Plugins : mimeTools.dll NppConverter.dll NppExport.dll

**Comment by ScienceDiscoverer** [comment]
Why this issue is closed? The bar still never remembers position in 2023.
