### ISSUE TITLE
Functions List flashes when saving file

### ISSUE THREAD

**Issue by jlinBE** [notepad-plus-plus/notepad-plus-plus#7755]
### Steps to Reproduce the Issue

1. Open a source code file with several functions
2. Open the Functions List as a sidebar
3. Make a change in the file, save by pressing ctrl-s.

The functions list flashes as it updates.  It is distracting as I use ctrl-s a lot.

### Expected Behavior
Functions list should update without flashing.  Probably just need to add double buffering at the appropriate place.

### Debug Information
version: 7.8.2, x64 on Windows 10

**Comment by jlinBE** [comment]
There is a similar problem with 'Folder as Workspace' and updating files.  Maybe this should be a feature request like 'add double-buffering to all the sidebar windows'.

**Comment by sasumner** [comment]
>source code file with several functions

"Several" is very indefinite.  Can you provide a sample file that exhibits the behavior you are describing?

**Comment by jlinBE** [comment]
Sure.  Here's a copy of python37/lib/pydoc_data/topics.py, chosen for length.  Even though it's one giant comment, there are ~30 lines that functions list recognize as functions.

If you modify the file then save while functions list is visible, it will flash.

[topics.zip](https://github.com/notepad-plus-plus/notepad-plus-plus/files/3983644/topics.zip)

**Comment by sasumner** [comment]
So one presumes that a window repaints itself by clearing itself first and then repopulating.  I'm not sure what you want in this instance.  Well, except I understand that you want it not to "flash".  But I want a lot of things too...searches of millions of files should be instantaneous is a list-topper.  But I'm not going to get that.

**Comment by jlinBE** [comment]
plenty of applications do this and it doesn't flash.  in fact npp does this elsewhere - for example, whenever I load a new file in the main window - and it doesn't flash.

As I said, it just needs double buffering.  See:
https://en.wikipedia.org/wiki/Multiple_buffering

**Comment by sasumner** [comment]
I encourage you to develop the code and submit a PR.

**Comment by jlinBE** [comment]
I have no plans to do so.  While it may be a ten minute job for somebody who's got it all set up and is familiar with the code base, for me to get to the point where the code compiles and I can figure out exactly where to make the change would take at least a week.

I'm willing to take the time to report the bug but that's about it.  If it is not fixed I'll just use the function list less or maybe look for alternatives.

**Comment by sasumner** [comment]
Sadly, there are very few "10 minute" jobs for those doing software development.
