### ISSUE TITLE
[Bug]or not, document map shouldn't need scroll

### ISSUE THREAD

**Issue by kaulctin** [notepad-plus-plus/notepad-plus-plus#7756]
When using document map, I want to jump to specific location quickly in the document. Thus it's vital that all the contents is included in a one-page miniature, needless to scroll.

I've found this feedback in the community of npp
[Better document map](https://community.notepad-plus-plus.org/topic/17354/better-document-map)

I've searched the issues related to document map and haven't found similar issues, so I'm submitting one.

By the way, thanks for providing this excellent free editor!

**Comment by xylographe** [comment]
How would that one-page miniature look if the document is a large (100.000+ lines) log file?

**Comment by kaulctin** [comment]
Maybe leave some lines behind? Say, we could set up two parameters N and X, to choose 1 line every N lines when the file is over X lines.

**Comment by donho** [comment]
It's a limit for the component (Scintilla) used by Notepad++.
