### ISSUE TITLE
fold comment C code shows wrong.

### ISSUE THREAD

**Issue by tommymaple** [notepad-plus-plus/notepad-plus-plus#7759]
### Description of the Issue

fold comment C code  shows wrong.
### Steps to Reproduce the Issue

1. edit *.c file
2. paste below
{
//}
}

3. and u will see wrong folds up
日   {
 L    //}
　}

BUT!!
if comment with space the folds is right!  // }  (<-with space)

### Expected Behavior

日  {
 |    //}
 L   }
### Actual Behavior

日  {
 L   //}
　 }
### Debug Information

Notepad++ v7.8.1   (64-bit)
Build time : Oct 27 2019 - 22:57:19
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS Name : Windows 10 Enterprise (64-bit) 
OS Version : 1903
OS Build : 18362.535
Plugins : AutoEolFormat.dll HTMLTag.dll mimeTools.dll NppConverter.dll NppExport.dll XMLTools.dll

**Comment by sasumner** [comment]
Can you provide more clarity by putting your code samples inside code blocks so that they look like this when rendered here?:

```
one
two
three
```

**Comment by mshingote** [comment]
![image](https://user-images.githubusercontent.com/8279344/71191870-40331e80-22ad-11ea-85b2-9d6247725cde.png)

**Comment by donho** [comment]
It's rather a bug in Scintilla

**Comment by tommymaple** [comment]
sorry about relaying you so late.

if what i report its not an issue please ignore it.



Rosh

Don HO <notifications@github.com> 於 2019年12月20日 週五 下午6:27寫道：
