### ISSUE TITLE
Radio buttons for find-and-replace scope

### ISSUE THREAD

**Issue by h-h-h-h** [notepad-plus-plus/notepad-plus-plus#776]
Hello,

I would appreciate radio buttons in the find-and-replace dialog for the scope the action is applied upon.
- The "In selection" checkbox would become a radio button
- The radio button "Document" would be required
- The button "Replace All in All Opened Documents" would become a radio button

```
+-Scope-------------+
| ( ) Selection     |
| (*) Document      |
| ( ) All documents |
+-------------------+
```

In my opinion it's not necessary to ever disable the "Selection" radio button. This is because you may want to check the radio button in preperation to selecting text. But the buttons that perform the actions could be enabled/disabled _while_ you change or clear the selection. This way you are able to select text and press the "Replace All" button without having to activate the dialog first. (It also doesn't make sense to be able to click "Find Next" for an empty string.)

---

_Note:_ Issue https://github.com/notepad-plus-plus/notepad-plus-plus/issues/449#issuecomment-120668700 might remove the "Direction" radio buttons, so there would be space available for the "Scope" radio buttons.

Related issues: https://github.com/notepad-plus-plus/notepad-plus-plus/issues/773, https://github.com/notepad-plus-plus/notepad-plus-plus/issues/722

**Comment by donho** [comment]
It needs a lot of coding effort, therefore it won't be implemented.
