### ISSUE TITLE
Copy Format is not coming properly

### ISSUE THREAD

**Issue by 8460756536** [notepad-plus-plus/notepad-plus-plus#7760]
### Description of the Issue

While coping the output of Linux commands from putty terminal.
the copied text is not coming proper format while if we copy the same thing on windows notepad. it is coming properly formatted.

### Steps to Reproduce the Issue

Run commands as per below and try to copy that output in notepad++ and windows default notepad
1. top
2. ls -lrth

### Expected Behavior

Format same as the terminal output (refer the attached images)

### Actual Behavior

It is coming unformatted as below. (refer the attached images)

### Debug Information

**view of windows notepad**
![image](https://user-images.githubusercontent.com/46392495/71164334-d860e180-2274-11ea-9a08-b6115bffa626.png)

**view of notepad++**
![image](https://user-images.githubusercontent.com/46392495/71164386-f1699280-2274-11ea-9cc8-47d66b7c4992.png)

**Comment by 8460756536** [comment]
Thanks..

It got resolved after changing **stylers.xml**.

**Comment by sasumner** [comment]
It's got nothing to do with the Dracula theme.  It's got nothing to do with formatting of data.  Notepad.exe uses a monospaced font, which means that every character takes up the same amount of horizontal space (width).  In the above screenshot of Notepad++, you clearly have a non-monospaced font selected, where characters take up horizontal space based upon which characters they are ("i" takes up much less horizontal space than "w").  All you had to do to make the data "look good" was to select a different font in Notepad++, not change an entire theme.
