### ISSUE TITLE
Feature request. Allow end-user to change the document icon when Notepad++ is the default editor for text files on Windows 10.

### ISSUE THREAD

**Issue by egkareem** [notepad-plus-plus/notepad-plus-plus#7761]
### Suggested feature:

Hello, you have a great software. When Notepad++ is selected as the default editor in Windows, and since users of text documents normally have a ton of such documents, your current icon is all over the place. You may agree that your icon may not be liked by every user. 
###Suggestion:
I suggest you provide an easy way to replace the document icon (resulting from Notepad++) with an user selected/defined icon file of user's choice. Currently this is only possible using registry edit (as far as I know).

Thanks.

**Comment by sasumner** [comment]
This is outside the scope of what Notepad++ endeavors to do.  If you don't like the icon, you can edit the Windows registry and put a new icon in place.

**Comment by xylographe** [comment]
@egkareem Have a look at [Resource Hacker](http://www.angusj.com/resourcehacker/).

**Comment by egkareem** [comment]
Thanks xyLographe.
