### ISSUE TITLE
Feature: no need to NO TO ALL when closing one file

### ISSUE THREAD

**Issue by batata004** [notepad-plus-plus/notepad-plus-plus#7762]
When I open only one file, modify it and then try to close notepad++ without saving, it displays a message asking me if I want to save with options like: YES, NO, NO TO ALL, YES TO ALL...

However I have only one single file opened. So it should not display NO TO ALL nor YES TO ALL.

Also, if I have 10 files opened on Notepad++ and all of them are already saved except one of those files. If I try to close the software it shoudl first close all the saved windows and then ask me if I want to save or not the last one without showing the * TO ALL option if only one file was not saved.

This looks a stupid request, but I am moving from dreamweaver to notepad++ and the behaviour I described above, is exactly the one that happens on dreamweaver. It's much cleaner and easier to understand cause sometimes when I close the only one single file I was editing and the program asks me to save or not ALL I have to waste a few seconds checking if there was indeed another file already opened that was not saved that could make me lose something important.

**Comment by sasumner** [comment]
@batata004 said:

>if I have 10 files opened ... and all of them are already saved except one. If I try to close the software it should first close all the saved windows and then ask me if I want to save or not the last one...

When I looked at the code changed by the commit, I don't think that THIS part of your request was implemented.

**Comment by batata004** [comment]
So is this feature implemented on latest version of notepad++? Or I need to wait the next release? I dont know well how github works, sorry!

**Comment by sasumner** [comment]
>need to wait the next release?

Yes, whatever comes after 7.8.2 (presumably 7.8.3 but one never knows...)
