### ISSUE TITLE
Add keybinding to close Results window

### ISSUE THREAD

**Issue by dangibson** [notepad-plus-plus/notepad-plus-plus#7766]
If you open the results window, you can only close it by clicking on the X with the mouse. When working on a laptop with a small screen, you want to close the window.

It would be nice if you could either:

> Press F7 to toggle the window (pressing once opens it, pressing again focuses to it, pressing again closes it), or

> Focus to the results window and press Esc or Ctrl-W to close it

ie some way to close the results window without requiring the use of the mouse,

**Comment by dangibson** [comment]
Looks like the code would need to be added in FindReplaceDlg.cpp. It has a _canBeVolatiled member but I'm not sure what that means? It seems to prevent a closeThis entry from being added to the results context menu, but I'm not sure why? Perhaps _canBeVolatiled could be renamed and/or its purpose explained?

**Comment by andrecool-68** [comment]
All hot keys work this way, they only open their windows but do not close)))

**Comment by sasumner** [comment]
>All hot keys work this way, they only open their windows but do not close

Not true, a counter example is `Function List`.  If you bind it to a keystroke and then press the keystroke repeatedly, it opens/closes/opens/closes...

**Comment by sasumner** [comment]
@dangibson You might be interested in having a read of this:  https://community.notepad-plus-plus.org/topic/14130/hide-or-toggle-find-results-panel-with-keyboard-command

**Comment by vinsworldcom** [comment]
@donho recommends using the Escape key as the "close active Search Results Window keyboard binding".  I agree - tried, but failed.  See #2946.

**Comment by sasumner** [comment]
@dangibson __canBeVolatiled_ isn't related to this discussion.

**Comment by donho** [comment]
@vinsworldcom 
> @donho recommends using the Escape key as the "close active Search Results Window keyboard binding". I agree - tried, but failed. See #2946.

I've even tried to implement it... without success :(

@sasumner Do you wanna try?

**Comment by sasumner** [comment]
@donho said:

>sasumner Do you wanna try?

I'm out.  If I did it, a bell would ring somewhere.  :-)

**Comment by JJT319** [comment]
Fix delivered to #2946 
This thread can now be closed?

**Comment by jairocontreras** [comment]
going all the way back to issue #61 can we make F7 toggle the search results window!? there should be an option for that

**Comment by jairocontreras** [comment]
this issue should be closed (although i still want f7 to toggle/hide the search results window!)
