### ISSUE TITLE
Use Ctrl+Tab to change tab in find-and-replace dialog

### ISSUE THREAD

**Issue by h-h-h-h** [notepad-plus-plus/notepad-plus-plus#777]
Hello,

(<kbd>Shift</kbd>+)<kbd>Ctrl</kbd>+<kbd>Tab</kbd> is a common key combination to change the tab. The find-and-replace dialog should implement that. The current behavior is to change the control focus. This can still be done with (<kbd>Shift</kbd>+)<kbd>Tab</kbd>.

In a multiline textbox this meaning of <kbd>Ctrl</kbd>+<kbd>Tab</kbd> would be superseded. See issue https://github.com/notepad-plus-plus/notepad-plus-plus/issues/563.

**Comment by NN---** [comment]
+1

**Comment by donho** [comment]
There's no multiline textbox.

**Comment by sasumner** [comment]
>There's no multiline textbox.

That was an ancillary comment, not the main thrust.  The OP wanted a way, with focus in a Find family window to change tabs (e.g. Find to Replace) with a keyboard action.  This ability is still sorely missing. :(

**Comment by h-h-h-h** [comment]
@donho: You totally missed the point! Please re-read the first paragraph of my initial comment; forget the second paragraph.
