### ISSUE TITLE
Bug Report: Replaced content wrong when replace in files

### ISSUE THREAD

**Issue by springsin0** [notepad-plus-plus/notepad-plus-plus#7773]
### Description of the Issue
If I open these files(attached files) in Notepad++ one by one and use "Replace All"(in "Replace") to replace, it is normal.
But if I don't open these files and use "Replace in Files"(in "Find in Files") to replace, the function ends smoothly but it has content errors.
This is critical because you even don't know there are mistakes until game loading error. Fortunately these are the game using xml files, if these are common txt files I don't have a chance to notice these mistakes.

### Steps to Reproduce the Issue
1. Decompress and put the four xml files in a folder. 
[civ4modxml.zip](https://github.com/notepad-plus-plus/notepad-plus-plus/files/3996642/civ4modxml.zip)
```
CIV4GameText_AIAutoPlay.xml
CIV4GameText_BetterBTSAI.xml
CIV4GameText_Events_BTS.xml
CIV4GameText_UnofficialPatch.xml
```
2. Run Notepad++ without open any files.
3. Replace using "Replace in Files"(in "Find in Files")
replace regular expression is here
Find what: `(<English>(.*?)</English>[\w\W]*?</Spanish>\r\n)`
Replace with: `\1\t\t<Chinese>\2</Chinese>\r\n`
![replace dialogue window](https://user-images.githubusercontent.com/4582696/71385513-1ff3be80-2623-11ea-995a-bbbcb139469c.png)

### Expected Behavior & Actual Behavior
1.CIV4GameText_AIAutoPlay.xml: new file line 22, original file line 21
Characters garbled, finally I found the file encoding was changed from original ANSI to UTF-8. It should remain original ANSI encoding.
after replaced, should be like this
```
		<Spanish>Elige una civilizaci髇</Spanish>
```
but
```
		<Spanish>Elige una civilizacin</Spanish>
```
2.CIV4GameText_Events_BTS.xml: new file line 7547, original file line 6710
after replaced, should be like this
```
	<TEXT>
		<Tag>TXT_KEY_EVENT_EARTHDAY_HELP_2</Tag>
		<English>[ICON_BULLET]Persuade other nations to convert to [COLOR_HIGHLIGHT_TEXT]Environmentalism[COLOR_REVERT] (at least one civilization must have the ability to do so).</English>
		<French>[ICON_BULLET]Persuader d'autres nations de se convertir à l'[COLOR_HIGHLIGHT_TEXT]écologie[COLOR_REVERT] (au moins une civilisation doit posséder cette capacité).</French>
		<German>[ICON_BULLET]&#220;berzeugt andere Nationen, zum [COLOR_HIGHLIGHT_TEXT]Umweltschutz[COLOR_REVERT] zu wechseln (mindestens eine Zivilisation muss dazu f&#228;hig sein).</German>
		<Italian>[ICON_BULLET]Persuadi altre nazioni a convertirsi all'[COLOR_HIGHLIGHT_TEXT]Ambientalismo[COLOR_REVERT] (almeno una delle altre civilt&#224; deve essere in grado di farlo).</Italian>
		<Spanish>[ICON_BULLET]Convence a otras naciones de que se conviertan al [COLOR_HIGHLIGHT_TEXT]Ecologismo[COLOR_REVERT] (al menos una civilizaci&#243;n debe poseer la capacidad de hacerlo).</Spanish>
		<Chinese>[ICON_BULLET]Persuade other nations to convert to [COLOR_HIGHLIGHT_TEXT]Environmentalism[COLOR_REVERT] (at least one civilization must have the ability to do so).</Chinese>
	</TEXT>
```
but
```
	<TEXT>
		<Tag>TXT_KEY_EVENT_EARTHDAY_HELP_2</Tag>
		<English>[ICON_BULLET]Persuade other nations to convert to [COLOR_HIGHLIGHT_TEXT]Environmentalism[COLOR_REVERT] (at least one civilization must have the ability to do so).</English>
		<French>[ICON_BULLET]Persuader d'autres nations de se convertir 	</TEXT>
```
new file line 7551 is also wrong, should be
```
		<French>Salpêtre découvert.</French>
```
but
```
		<French>Salp
tre d	couvert.</French>
```
Maybe still other errors I didn't find.

### Debug Information
Notepad++ v7.8.2   (64-bit)
Build time : Dec  4 2019 - 01:39:49
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : ON
Local Conf mode : OFF
OS Name : Windows 7 Home Premium (64-bit) 
OS Build : 7601.23833
Plugins : ComparePlugin.dll HexEditor.dll MarkdownViewerPlusPlus.dll mimeTools.dll NppConverter.dll NppExport.dll NppMarkdownPanel.dll NppPluginDemo.dll

**Comment by ungesundes-halbwissen** [comment]
may be related to #5825 and #5830
