### ISSUE TITLE
Button size

### ISSUE THREAD

**Issue by vitalii2011** [notepad-plus-plus/notepad-plus-plus#7775]
Search box in Russian localization – Button size. Broken a few updates ago
https://i.imgur.com/YeYjZGo.png

Notepad++ v7.8.2   (32-bit)
Build time : Dec  4 2019 - 01:36:59
Path : D:\Portable\PortableApps\Notepad++Portable\App\Notepad++\notepad++.exe
Admin mode : ON
Local Conf mode : ON
OS Name : Windows 7 Ultimate (64-bit) 
OS Build : 7601.0
Plugins : DSpellCheck.dll mimeTools.dll NppConverter.dll NppExport.dll

**Comment by xylographe** [comment]
From `russian.xml`,
```
    <Item id="1721" name="▲"/> 
    <Item id="1723" name="▼"/> 
```
Try changing the language in **Settings > Preferences** to a different language, then change it back to Russian.

**Comment by vitalii2011** [comment]
> Try changing the language

Thanks, it turned out!
