### ISSUE TITLE
Inconsisten colour-coding of comments in .h file

### ISSUE THREAD

**Issue by DanielTheGreat** [notepad-plus-plus/notepad-plus-plus#7777]
### Description of the Issue
A multi-line /* */ comment, commencing after a #define statement, is coloured black instead of green

### Steps to Reproduce the Issue
1.  In a .h file, insert lines like the following:
#define TxBufLen (400)	/* size (bytes) of LCD Tx buffer (works with a 16x2 display,
							but can work with bigger displays - see below). */

### Expected Behavior
The comment text should be green, like for most other C and H program comments.

### Actual Behavior
On my system, the comment is displayed coloured black.

### Debug Information
Notepad++ v7.8.2   (64-bit)
Build time : Dec  4 2019 - 01:39:49
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : ON
Local Conf mode : OFF
OS Name : Windows 7 Professional (64-bit) 
OS Build : 7601.24540
Plugins : DSpellCheck.dll mimeTools.dll NppConverter.dll NppExport.dll 

![Npp_wrong_colourV](https://user-images.githubusercontent.com/17305139/71400124-e5694080-2679-11ea-9af9-b50cd8ea24d1.png)

**Comment by An1onS** [comment]
Could not reproduce.
![изображение](https://user-images.githubusercontent.com/26001123/71556190-e2de6080-2a56-11ea-82e7-f6d06bfedca5.png)
**Debug Info:**
Notepad++ v7.8.2   (64-bit)
Build time : Dec  4 2019 - 01:39:49
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : ON
Local Conf mode : OFF
OS Name : Windows 10 Education (64-bit) 
OS Version : 1903
OS Build : 18362.535
Plugins : DSpellCheck.dll mimeTools.dll NppConverter.dll NppExport.dll

**Comment by donho** [comment]
Cannot reproduce either.
Could you attach your file please (Or copy paste your whole code).

**Comment by DanielTheGreat** [comment]
Sure, here's the offending file.

[DF_I2C_LCD.zip](https://github.com/notepad-plus-plus/notepad-plus-plus/files/4012055/DF_I2C_LCD.zip)
