### ISSUE TITLE
[BUG] Notepad ++ 7.8.2 "help?->Set Updater Proxy..." doesn't work for plugin admin

### ISSUE THREAD

**Issue by xiaoguazh** [notepad-plus-plus/notepad-plus-plus#7779]
### Description of the Issue
Two issues:

1.The proxy setting is NOT kept after NPP every restart
2.The proxy doesn't work for Plugin admin. 
  I suspect the logic of using proxy may have bug. because when clicking "install" at "Plugins Admin..." dialogue, it will shows the NPP to be closed first, I guess at this moment the proxy setting is gone, then the plugin download progress is started, actually without proxy.
 
 Shall the NPP close should be happened after the download progress finished?

### Steps to Reproduce the Issue

1. Config the proxy (include host and port) via ?->"Set Updater Proxy..." 
2. "Plugins Admin..." select plugin and click "install"
3. It shows first "NPP will be closed", then shows a download progress bar which never goes  any progress
4. Few seconds later the NPP is restarted with NONE-plugin is installed 

### Expected Behavior
1. The proxy setting could be  reserved after restart, and better to have option I can enable or disable the proxy
2. The "Plugins Admin..." could work with proxy and download can be proceed successfully.

### Actual Behavior
1.The given proxy is cleaned after every restart
2.None of plugin can be successfully downloaded with proxy, ZERO progress on the download progress bar.

### Debug Information

Notepad++ v7.8.2   (64-bit)
Build time : Dec  4 2019 - 01:39:49
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS Name : Windows 10 Enterprise (64-bit) 
OS Version : 1809
OS Build : 17763.864
Plugins : mimeTools.dll NppConverter.dll nppcrypt.dll NppDocShare.dll NppEventExec.dll NppExport.dll NppFTP.dll NppXmlTreeviewPlugin.dll PythonScript.dll RunMe.dll SecurePad.dll XMLTools.dll

**Comment by xylographe** [comment]
To change the proxy setting you need Administrator privileges.

- Exit NPP
- Start NPP as Admin
- Change proxy setting
- Select **Plugins > Open Plugins Folder**
- Navigate to parent folder in explorer, then to the **`updater`** folder
- Check out the **`gupOptions.xml`** file

**Comment by xiaoguazh** [comment]
@xylographe , thanks a lot!!! 

Yes to run NPP as Administrator does resolve this issue. 

Better if NPP can prompt more friendly message when the given setting cannot be stored into gupOptions.xml successfully, so that user could know easily what is happening and how I can fix it.

anyway, if you tend to close this ticket, it 's fine for me.

I really hope if there is a way to prompt a clear message when settings are not saved with non-administrators.

**Comment by xiaoguazh** [comment]
With starting NPP "as Administrator", this function works as expected.

**Comment by xylographe** [comment]
> Better if NPP can prompt more friendly message when the given setting cannot be stored into gupOptions.xml successfully, so that user could know easily what is happening and how I can fix it.

Agreed, that would be the user-friendly thing to do, but it's not that simple. Admin privileges are 
only necessary if NPP has been installed, not when running NPP portable. Ideally the exit code of `GUP.exe` would tell if `gupOptions.xml` has been created/modified successfully. Unfortunately, `GUP.exe` always exits with exit code zero.
