### ISSUE TITLE
Undo-ing "Remove Bookmarked Lines" also removes Bookmarks

### ISSUE THREAD

**Issue by klou** [notepad-plus-plus/notepad-plus-plus#7788]
### Description of the Issue
Undo-ing (Ctrl+Z) a "Remove Bookmarked Lines" action restores the deleted lines, but none of the Bookmarks are also restored.

Minor issue, but thought I'd log it.

### Steps to Reproduce the Issue
1. Ctrl+F -> Mark tab -> Find + Mark (Bookmark line)
2. Search -> Bookmarks -> Remove Bookmarked Lines
3. Ctrl+Z (or Undo)

### Expected Behavior
I would like to see the Bookmarks on the lines

### Actual Behavior
Lines are restored, but without Bookmarks at the Line Numbers.

### Debug Information
Notepad++ v7.8.2   (64-bit)
Build time : Dec  4 2019 - 01:39:49
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS Name : Windows 10 Pro (64-bit) 
OS Version : 1709
OS Build : 16299.1087
Plugins : ComparePlugin.dll HTMLTag.dll mimeTools.dll NppConverter.dll NppExport.dll NPPJSONViewer.dll XMLTools.dll

**Comment by sasumner** [comment]
This has come up before.  In general, currently only text change actions are undoable.
