### ISSUE TITLE
Line sort lexicographically Broken

### ISSUE THREAD

**Issue by Pabsb** [notepad-plus-plus/notepad-plus-plus#7793]
### Description of the Issue

Sort lines lexicographically not sorting properly
### Steps to Reproduce the Issue

1.  Paste in a list like this: https://pastebin.com/2ikDGzQi
2.  Highlight everything
3.  Sort as lexicographically
4.  See that several name's aren't sorted correctly 

### Expected Behavior

Names should be sorted correctly
### Actual Behavior

Name's aren't sorted correctly

**Comment by xylographe** [comment]
Your example file is already sorted. After a descending sort followed by an ascending sort the result equals the original.

**Comment by sasumner** [comment]
Closing based upon @xylographe 's analysis.

And in the future, don't use pastebin, simply attach a file directly (some users are blocked from accessing pastebin).

**Comment by Pabsb** [comment]
> Your example file is already sorted. After a descending sort followed by an ascending sort the result equals the original.



> Closing based upon @xylographe 's analysis.
> 
> And in the future, don't use pastebin, simply attach a file directly (some users are blocked from accessing pastebin).

If you guys took a closer look and saw the lines after they were sorted more specifically the bottom lines they are not sorted properly even when selected. Either doing ascending or descending sorts.

**Comment by sasumner** [comment]
>If you guys took a closer look

1. You didn't address the "pastebin" problem.

2. If you are going to provide a file that when someone sorts it they say:

>Your example file is already sorted

then you should have pointed out which lines did not sort correctly.

**Comment by xylographe** [comment]
@Pabsb Why do you think the lines are not sorted?
```powershell
PS> $lines = Get-Content -LiteralPath lines.txt
PS> $list = New-Object 'System.Collections.Generic.List[string]' ($lines.Count)
PS> $lines.ForEach({$null = $list.Add($_)})
PS> $list
9yearoldboy (Impact)
Agnd
AltheaPanic
Buscrafter (Impact)
Bwad (Impact)
Cattt
Cloudiness
Conceits
CoolThingys
CoolioIsh
CottonCandy_Girl
Crazyjay5
CrimsonFaty
DanielB00m
Doopm (Glass pack)
Dpunch26
Gabeh_Phobia (Impact)
GalaApple (Impact)
Glasspack (Impact)
Hannugh
HearthStone (Impact)
Juelani (Impact)
Justugh
Kattybnaps/OBVbetterthanFS
Kay05 (Ray)
Kelvin0000
LumpierLumpy (Impact)
LumpyPotato (Impact)
Modpenguin
NathyyBoi420 (impact)
NinetailsPlays
NintenFan
Ollevele (impact)
OmgItsBellaaa
PointlessLife
Springtime (Impact)
T4PS
TravisXThomson (Impact)
UnanimousMVP
WhatDeathFears
Yittt (impact)
Zythers
elbatsnu
iiFluffeh (impact)
pointlesslife
vetemnts
PS> $list.Sort([System.StringComparer]::Ordinal)
PS> $list
9yearoldboy (Impact)
Agnd
AltheaPanic
Buscrafter (Impact)
Bwad (Impact)
Cattt
Cloudiness
Conceits
CoolThingys
CoolioIsh
CottonCandy_Girl
Crazyjay5
CrimsonFaty
DanielB00m
Doopm (Glass pack)
Dpunch26
Gabeh_Phobia (Impact)
GalaApple (Impact)
Glasspack (Impact)
Hannugh
HearthStone (Impact)
Juelani (Impact)
Justugh
Kattybnaps/OBVbetterthanFS
Kay05 (Ray)
Kelvin0000
LumpierLumpy (Impact)
LumpyPotato (Impact)
Modpenguin
NathyyBoi420 (impact)
NinetailsPlays
NintenFan
Ollevele (impact)
OmgItsBellaaa
PointlessLife
Springtime (Impact)
T4PS
TravisXThomson (Impact)
UnanimousMVP
WhatDeathFears
Yittt (impact)
Zythers
elbatsnu
iiFluffeh (impact)
pointlesslife
vetemnts
PS>
```

**Comment by Pabsb** [comment]
> @Pabsb Why do you think the lines are not sorted?
> 
> ```powershell
> PS> $lines = Get-Content -LiteralPath lines.txt
> PS> $list = New-Object 'System.Collections.Generic.List[string]' ($lines.Count)
> PS> $lines.ForEach({$null = $list.Add($_)})
> PS> $list | Set-Content -Encoding UTF8 -LiteralPath lines-original.txt
> PS> $list
> 9yearoldboy (Impact)
> Agnd
> AltheaPanic
> Buscrafter (Impact)
> Bwad (Impact)
> Cattt
> Cloudiness
> Conceits
> CoolThingys
> CoolioIsh
> CottonCandy_Girl
> Crazyjay5
> CrimsonFaty
> DanielB00m
> Doopm (Glass pack)
> Dpunch26
> Gabeh_Phobia (Impact)
> GalaApple (Impact)
> Glasspack (Impact)
> Hannugh
> HearthStone (Impact)
> Juelani (Impact)
> Justugh
> Kattybnaps/OBVbetterthanFS
> Kay05 (Ray)
> Kelvin0000
> LumpierLumpy (Impact)
> LumpyPotato (Impact)
> Modpenguin
> NathyyBoi420 (impact)
> NinetailsPlays
> NintenFan
> Ollevele (impact)
> OmgItsBellaaa
> PointlessLife
> Springtime (Impact)
> T4PS
> TravisXThomson (Impact)
> UnanimousMVP
> WhatDeathFears
> Yittt (impact)
> Zythers
> elbatsnu
> iiFluffeh (impact)
> pointlesslife
> vetemnts
> PS> $list.Sort([System.StringComparer]::Ordinal)
> PS> $list | Set-Content -Encoding UTF8 -LiteralPath lines-sorted.txt
> PS> $list
> 9yearoldboy (Impact)
> Agnd
> AltheaPanic
> Buscrafter (Impact)
> Bwad (Impact)
> Cattt
> Cloudiness
> Conceits
> CoolThingys
> CoolioIsh
> CottonCandy_Girl
> Crazyjay5
> CrimsonFaty
> DanielB00m
> Doopm (Glass pack)
> Dpunch26
> Gabeh_Phobia (Impact)
> GalaApple (Impact)
> Glasspack (Impact)
> Hannugh
> HearthStone (Impact)
> Juelani (Impact)
> Justugh
> Kattybnaps/OBVbetterthanFS
> Kay05 (Ray)
> Kelvin0000
> LumpierLumpy (Impact)
> LumpyPotato (Impact)
> Modpenguin
> NathyyBoi420 (impact)
> NinetailsPlays
> NintenFan
> Ollevele (impact)
> OmgItsBellaaa
> PointlessLife
> Springtime (Impact)
> T4PS
> TravisXThomson (Impact)
> UnanimousMVP
> WhatDeathFears
> Yittt (impact)
> Zythers
> elbatsnu
> iiFluffeh (impact)
> pointlesslife
> vetemnts
> PS> diff lines-original.txt lines-sorted.txt
> PS>
> ```

The bottom 4 lines are never sorted properly if you try to sort them either descending or ascending. Notepad++ isn’t sorting the names and just leaves those 4 at the end.

**Comment by xylographe** [comment]
The bottom 4 lines are sorted properly: `e` before `i`, `i` before `p`, `p` before `v`.
Can you, please, show us the result you expect?

**Comment by vertigo220** [comment]
This is because the file is being sorted lexicographically but NOT ignoring case. Those lines begin with lower-cased letters and so are sorted amongst themselves _after_ the lines starting with capital letters. You have to use the option to ignore case.
