### ISSUE TITLE
Does not always save changes

### ISSUE THREAD

**Issue by theREALdebater** [notepad-plus-plus/notepad-plus-plus#7794]
### Description

I believe that sometimes Notepad++ fails to save changes I have made. 

I suspect what is happening is that, on occasion, N++ thinks that a document/buffer which has had edits made to it is already saved/up-to-date/clean, and so clicking on the Save toolbar button or pressing Ctrl+S does not actually save (the buffer back into the file) when it should. 

I have experienced this behaviour for several recent versions of N++ and on two different machines, both running Windows 10 (up-to-date). 

When it happens is rather random, and so very difficult to reproduce.

I'm happy to answer questions and add any more information that I can.

It is a bit of a gotcha, because the Save toolbar button goes grey, indicating my changes have been saved when they actually haven't If I close N++, I just silently lose the changes. It therefore seems like a rather serious problem, since it is fundamental to be able to rely on an editor to actually save the changes you have made. 

### Debug Info

This is for N++ just recently updated running on my home computer.

Notepad++ v7.8.2   (64-bit)
Build time : Dec  4 2019 - 01:39:49
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS Name : Windows 10 Pro (64-bit) 
OS Version : 1903
OS Build : 18362.535
Plugins : MarkdownViewerPlusPlus.dll mimeTools.dll npp.connections.dll NppConverter.dll NppExec.dll NppExport.dll NPPJSONViewer.dll NppRegExTractorPlugin.dll NppSaveAsAdmin.dll NppToolBucket.dll NppXmlTreeviewPlugin.dll PluginManager.dll pork2sausage.dll SessionMgr.dll SQLinFormNpp64.dll XMLTools.dll

**Comment by theREALdebater** [comment]
I think it happens soon after I have created the file. I hit the New button on the toolbar, type or paste in some text, and then save as normal. Then I type in some more text and hit Save. It seems like it has saved properly - the Save button goes grey - but the latest changes are not actually in the file. If I close the file now, I will have silently lost my changes.

**Comment by donho** [comment]
I cannot reproduce it. It's likely a bug from plugins.
Remove all your plugins to make sure it's Notepad++ bug.
