### ISSUE TITLE
reStructuredText highlighting

### ISSUE THREAD

**Issue by cup** [notepad-plus-plus/notepad-plus-plus#7802]
https://docutils.sourceforge.io/docs/user/rst/quickref.html

**Comment by cup** [comment]
@sasumner why close?

**Comment by DavidHansen-0x454d43** [comment]
@cup, I can't speak for @sasumner, but I see a couple of problems with your request:
 
1. Your feature request is about as low effort as you can get. In the future it would be better to include a little more information in your request, like "What is reStructuredText? Why is it useful? Why should N++ add it" 

2. It might be possible that you can implement reStructured highlighting using N++'s User Defined Language (UDL) functionality. You can ask for help doing this on the [community forum](https://community.notepad-plus-plus.org/)

2. N++ is based on the Scintilla component, which handles most of the syntax highlighting i.e.everything listed in the Language menu above "Define your language...". If you want RST to be included in Scintalla, then the appropriate place for your request is the on {their tracker](https://sourceforge.net/p/scintilla/feature-requests/).

I hope this helps!

**Comment by cup** [comment]
Workaround:

https://github.com/steenhulthin/reStructuredText_NPP

**Comment by DavidHansen-0x454d43** [comment]
Nice work @cup!

**Comment by cup** [comment]
https://github.com/notepad-plus-plus/userDefinedLanguages/issues/5
