### ISSUE TITLE
[Feature Request] Windows Dark Mode compatibility.

### ISSUE THREAD

**Issue by LAPIII** [notepad-plus-plus/notepad-plus-plus#7805]
N++ is the only app I have that doesn't use Dark Mode. What I specifically need darkened are:

1. The title bar,
2. Menu
3. Active tab
4. Find & Replace
5. The "Open" and "Save" File Explorer Windows

**Comment by Shakil-Shahadat** [comment]
Duplicate #7692

**Comment by sasumner** [comment]
Closing because of duplication.
