### ISSUE TITLE
User Defined Language repo

### ISSUE THREAD

**Issue by cup** [notepad-plus-plus/notepad-plus-plus#7807]
I see this UDLs are documented here:

https://npp-user-manual.org/docs/user-defined-language-system

and an example is here:

https://github.com/notepad-plus-plus/notepad-plus-plus/blob/master/PowerEditor/bin/userDefineLangs/userDefinedLang-markdown.default.modern.xml

Given that members have been strongly against any changes to Scintilla, I think
it would be helpful if further UDLs could be added to that folder. This could be
done by members or by people outside the project via pull request.

Another option would be a new repo for just UDL, something like

https://github.com/notepad-plus-plus/UDLs

are either of these options something that would be acceptable?

**Comment by rddim** [comment]
https://github.com/notepad-plus-plus/npp-usermanual/issues/61
