### ISSUE TITLE
Make Plugins Admin dialog resizable.

### ISSUE THREAD

**Issue by garydgregory** [notepad-plus-plus/notepad-plus-plus#7810]
Please make the Plugins Admin dialog resizable.

```
Notepad++ v7.8.2   (64-bit)
Build time : Dec  4 2019 - 01:39:49
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS Name : Windows 10 Enterprise (64-bit) 
OS Version : 1709
OS Build : 16299.1451
Plugins : DSpellCheck.dll JSMinNPP.dll mimeTools.dll NppConverter.dll NppExport.dll XMLTools.dll 

```

**Comment by xylographe** [comment]
PR #5785

**Comment by andrecool-68** [comment]
How many such requests have already been ... but for some reason the author does not want such changes)))

**Comment by sasumner** [comment]
> but for some reason the author does not want such changes

There are often deeper reasons...

**Comment by ArkadiuszMichalski** [comment]
@sasumner Duplicate of https://github.com/notepad-plus-plus/notepad-plus-plus/issues/5680..

**Comment by sasumner** [comment]
Closing as duplicate
