### ISSUE TITLE
Sort shortcut

### ISSUE THREAD

**Issue by cup** [notepad-plus-plus/notepad-plus-plus#7811]
I have previously used these editors:

- https://github.com/zufuliu/notepad2
- https://github.com/ProgerXP/Notepad2e
- https://github.com/rizonesoft/Notepad3

and they all offer the `Alt + O` shortcut for sorting the selected lines. It seems NPP does not have this or any shortcut for sorting lines?

Is that the case? This is a feature I use quite often.

**Comment by xylographe** [comment]
Select **Settings > Shortcut Mapper > Main menu**.
Type `sort` in the **Filter** input field.

**Comment by cup** [comment]
@xylographe thanks
