### ISSUE TITLE
Column wrap

### ISSUE THREAD

**Issue by cup** [notepad-plus-plus/notepad-plus-plus#7813]
I have used these editors:

- https://github.com/zufuliu/notepad2
- https://github.com/ProgerXP/Notepad2e
- https://github.com/rizonesoft/Notepad3

Like NPP, they are all based on Scintilla. They have a feature called
"Column Wrap", which soft wraps the selected lines to a particular length. That
is to say it replaces spaces with newlines. The default being "vertical edge",
typically 80 columns.

It seems NPP is missing this functionality, is that the case?

**Comment by cup** [comment]
Ok I see that `Edit`, `Line Operations`, `Split Lines` (Ctrl + I) does this,
splitting on the current Vertical Edge.

It seems the only thing missing is being able to set the boundary. For example,
if you wanted to split on 40, you would need to go into the settings, change the
Vertical Edge, Split Lines, then change Vertical Edge back.

**Comment by sasumner** [comment]
>t seems the only thing missing is being able to set the boundary. For example,
if you wanted to split on 40, you would need to go into the settings, change the
Vertical Edge, Split Lines, then change Vertical Edge back.

Yep, that's exactly how you do it.

**Comment by cup** [comment]
https://github.com/notepad-plus-plus/notepad-plus-plus/issues/7814

**Comment by cup** [comment]
https://github.com/notepad-plus-plus/notepad-plus-plus/issues/482
