### ISSUE TITLE
Cannot edit binary file with HEX-Editor plugin !

### ISSUE THREAD

**Issue by churuxu** [notepad-plus-plus/notepad-plus-plus#7818]
#### 1.  I created a binary file use this C code
```
    uint32_t d = 0xf1f2f3f4;
    FILE* f = fopen("t.bin","wb");    
    fwrite(&d,1,4,f);
    fclose(f);
```
#### 3. The status bar does not display correctly
- Expected: `length:4 lines:1`
- Actual: `length:8 lines:1` 

#### 4. click plugin menu of `HEX-Editor -> View in Hex`, it's also incorrect,
- Expected: `f1 f2 f3 f4`
- Actual: `d1 84 d1 83 d1 82 d1 81`

![1](https://user-images.githubusercontent.com/15341919/71807808-219f9680-30a7-11ea-88af-5c59ebcc785a.png)

### Debug Information
Notepad++ v7.8.2   (32-bit)
Build time : Dec  4 2019 - 01:36:59
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS Name : Windows 10 Home China (64-bit) 
OS Version : 1903
OS Build : 18362.535
Plugins : DSpellCheck.dll HexEditor.dll mimeTools.dll NppConverter.dll NppExport.dll NppMarkdownPanel.dll 

HEX-Editor version : 0.9.5

**Comment by sasumner** [comment]
Please direct plugin issues to the site where the plugin is supported.

**Comment by xylographe** [comment]
Not so sure this is a plugin issue. Could be an encoding mix-up,
- open new file
- hex-edit on
- enter **`F4 F3 F2 F1`**
- hex-edit off
- displays **`ôóòñ`** in ANSI (Windows-1252)
- use "convert to UTF-8"
- hex-edit on
- displays **`C3 B4 C3 B3 C3 B2 C3 B1`**

**Comment by chcg** [comment]
Maybe something similar as https://github.com/chcg/NPP_HexEdit/issues/8 and https://github.com/chcg/NPP_HexEdit/issues/22

**Comment by xylographe** [comment]
Exactly,

> [the F6 was "replaced" with C3 B6](https://github.com/chcg/NPP_HexEdit/issues/8#issuecomment-479865410)

This commenter may also have Windows-1252 default encoding.

The OP OTOH might have GB2312 default encoding.
