### ISSUE TITLE
Auto-update is insecure again (no https)

### ISSUE THREAD

**Issue by philippelaulheret** [notepad-plus-plus/notepad-plus-plus#7821]
### Description of the Issue
When visiting  https://notepad-plus-plus.org/update/getDownloadUrl.php?version=7.58 and similar, the download link offered is over http not https. The certificate used for https is not covering notepad-plus-plus.org subdomains so that might be a silent fix for that problem; for more details see the last two comments on issue #4071. 
I'm opening a new issue as it seems comments on the previous issue are not reaching the dev team.

**Comment by eldstal** [comment]
Indeed, the HTTPS certificate is still misconfigured. 

The download link provided is HTTP. Attempting to use HTTPS instead delivers an **expired** certificate which is not valid for `download.notepad-plus-plus.org`.

It appears that this server is configured differently from notepad-plus-plus.org, which *does* have a valid certificate (though not for the `download` subdomain).

**Comment by vkhramtsov** [comment]
Currently it looks like https://download.notepad-plus-plus.org/ is using certificate issued for domain `notepad-plus-plus.org` and alt names `notepad-plus-plus.org` and `www.notepad-plus-plus.org`. Also certificate is valid only in time period after `11/24/2019` and `2/22/2020` so it is expired. 
It looks like adding `download.notepad-plus-plus.org` to alt names and issuing new certificate will fix problem.

@donho  Would you be so kind to fix this issue? 

Thank you in advance.

P.S. http://download.notepad-plus-plus.org/ shows apache on Debian welcome page.

**Comment by donho** [comment]
Fix in the update to v7.8.7
