### ISSUE TITLE
Please consider adding new ext to XML lexer

### ISSUE THREAD

**Issue by dshuman52** [notepad-plus-plus/notepad-plus-plus#7822]
Please add vcxproj and props to the ext list for the XML parser.  I have added them to the user version in portable notepad but that means I must re-enter them after an update.

**Comment by donho** [comment]
I do remember that I've already added it.
Obviously it was removed without my attention.
@sasumner I think it's quite legit and not harmful to add it.
What's your opinion?

**Comment by xylographe** [comment]
The current list of extensions is
`xml xaml xsl xslt xsd xul kml svg mxml xsml wsdl xlf xliff xbl sxbl sitemap gml gpx plist`

If you decide to add `vcxproj`, could you, please, add `csproj` too.

**Comment by sasumner** [comment]
@donho said:

>What's your opinion?

If it conveniences you, then of course add it.  

My thoughts were:

* it is not hard for a user to manually add what they need, even after an update it only needs to be done once (no big deal)

* the request list might never end, evidence:

>If you decide to add vcxproj, could you, please, add csproj too.

:-)

**Comment by donho** [comment]
@sasumner Yes, agree with your point.
About the file extension, the criteria to me is the popularity, and Visual Studio to me is legit for this criteria.

**Comment by dshuman52** [comment]
Thanks for accepting.  I can and did add them to the user option.  The negative being every update of the portable version requires me to perform the same update again.
