### ISSUE TITLE
SQL highlighting corrupted  by Slash in Strings

### ISSUE THREAD

**Issue by bummiw** [notepad-plus-plus/notepad-plus-plus#7825]
SQL highlighting corrupted  by Slash in Strings

e.g.

Select a,b,c, d + '\' + e 
from Table
where x=1

![NotePad_And_SQL](https://user-images.githubusercontent.com/10092321/71910783-d9e64100-3172-11ea-8a69-28515b144d45.png)

**Comment by Ekopalypse** [comment]
Settings.>Preferences->Language
uncheck **Treat backslash as escape character for SQL**
