### ISSUE TITLE
Link in last release (7.8.2) of Notepad++ is wrong

### ISSUE THREAD

**Issue by Smile4ever** [notepad-plus-plus/notepad-plus-plus#7830]
### Description of the Issue
Clicking the release note link goes to https://notepad-plus-plus.org/news/v781-free-uyghur-edition/ instead of https://notepad-plus-plus.org/news/v782-free-uyghur-edition/
![afbeelding](https://user-images.githubusercontent.com/544411/71983782-d496fe00-3227-11ea-8d79-22f2ecf319a0.png)

### Steps to Reproduce the Issue

1. Go to Help -> About. 
2. Click the release link.

### Expected Behavior
https://notepad-plus-plus.org/news/v782-free-uyghur-edition/ opens

### Actual Behavior
https://notepad-plus-plus.org/news/v781-free-uyghur-edition/ opens

### Debug Information
Notepad 7.8.2

**Comment by donho** [comment]
The link contains the information more complete about this edition.
It's not a bug but a feature.
