### ISSUE TITLE
请看到国人将官网举报至国家网信办举报中心www.12377.cn

### ISSUE THREAD

**Issue by emovlee** [notepad-plus-plus/notepad-plus-plus#7832]
# 中央网信办（国家互联网信息办公室）违法和不良信息举报中心
# 网址 www.12377.cn
[http://www.12377.cn/](url)
# 类别可以选择 政治类 暴恐类 谣言类
# 可以实名举报也可以匿名举报，有条件的尽量实名举报
# 举报时务必完整截图，尤其是该页面👇
[https://notepad-plus-plus.org/news/v781-free-uyghur-edition/](url)
# 看到的人一定记得复制防删，删掉继续发，举报到全面封禁为止，团结就是力量
:hearts::cn::hearts::cn::hearts::cn::hearts::cn::hearts::cn::hearts::cn::hearts::cn::hearts::cn::hearts::cn:

**Comment by wujianqi** [comment]
赞

**Comment by qwq233** [comment]
已实名举报

**Comment by lzr2006** [comment]
赞！

**Comment by Nemo2011** [comment]
墙了
