### ISSUE TITLE
sftp username Issue

### ISSUE THREAD

**Issue by justinvalceanu** [notepad-plus-plus/notepad-plus-plus#7833]
[NppFTP] Everything initialized
Connecting
[SFTP] Host key accepted
[SFTP] Invalid private key file or incorrect passphrase
[SFTP] Error during authentication: Access denied for 'none'. Authentication that can continue: publickey,gssapi-keyex,gssapi-with-mic
Unable to connect
Disconnected
======================
- Connection details are coreect;
- Host is Up
- NppFTP not sending the correct username -> always sends "none"

in %APPDATA%\Notepad++\plugins\config\NppFTP\NppFTP.xml the username is saved but still on each connection retry the same username is send: "none"

**Comment by chcg** [comment]
@justinvalceanu https://github.com/ashkulz/NppFTP/issues would be the correct issue queue, if this issue is still present. The plugin and N++ versions are also needed.

**Comment by justinvalceanu** [comment]
The issue is only present when you use a PPK key instead of an OpenSSH key. 
The plugin reads the keyfile and allows the user to decrypt the key file using the password in either format, but if the key is not in OpenSSH format then it will send "none" as the user, no matter what username was set. My simple fix was tho convert the key in openSSH.

**Comment by sasumner** [comment]
@justinvalceanu If this is a real problem for you, you need to follow @chcg 's advice and take it up on the plugin's issues list.

**Comment by chcg** [comment]
@justinvalceanu This is a requirement of the underlying libssh component, see also https://github.com/ashkulz/NppFTP/issues/270 and https://github.com/ashkulz/NppFTP/issues/22 is still open to add the expected format to the GUI.
