### ISSUE TITLE
Regex search in look behind is case-insensitive

### ISSUE THREAD

**Issue by firehorseuk** [notepad-plus-plus/notepad-plus-plus#7835]
### Description of the Issue
Regex not recognizing upper case in look behind as expected.

I'm using regex to find the end of one sentence and the start of next but also looking to see if the next sentence starts with a capital letter.

### Steps to Reproduce the Issue
1.  Put this into Notepad "Property Inc. is a company. This is a sentence."
2.  Find "(?<=[\.!\?])\s(?=[A-Z])" as a regular expression

### Expected Behavior
It should only find the space between ". T".

### Actual Behavior
It also finds the space between ". i".

### Debug Information
When I put the same information into regex101.com, it regex behaves as expected.

Also, when I do "(?<=[\.!\?])\s(?=[a-z])" as a regular expression, it also picks up both spaces when it should only pick up the first space.

Thanks
![Notepad Regex Bug](https://user-images.githubusercontent.com/10263623/72088634-7ee35400-3302-11ea-87d9-3fb971d462c6.jpg)

**Comment by Ekopalypse** [comment]
If you check match case checkbox you do get the expected result.
I haven't checked the source but I ASSUME that this checkbox sets the case flag explicitly.

**Comment by xylographe** [comment]
Enable the "Match case" option.

**Comment by firehorseuk** [comment]
Thanks. I didn't know the match case applied to regex as well. Thanks.

**Comment by sasumner** [comment]
If an option doesn't apply to regular expression search mode it will get disabled when that search mode is selected.  Evidence:  `Backward direction` and `Match whole word only`.  Notice that `Match case` remains enabled, so it applies.

That being said, a lot of people ignore that checkbox and use `(?i)` at the start of their regex to "ignore case" or `(?-i)` to "not ignore case".
