### ISSUE TITLE
Word repetition in ISSUE_TEMPLATE.md

### ISSUE THREAD

**Issue by FabienLaunay** [notepad-plus-plus/notepad-plus-plus#7843]
### Description of the Issue
Word **under** is unexpectedly repeated in _ISSUE_TEMPLATE.md_, _### Debug information_ section

### Steps to Reproduce the Issue
1. Open [ISSUE_TEMPLATE.md](https://raw.githubusercontent.com/notepad-plus-plus/notepad-plus-plus/master/ISSUE_TEMPLATE.md)
2. Scroll to row 22
3. Note that the word 'under' is unexpectedly repeated.

### Expected Behavior
Comment with following contents:
Debug Info can be found under the "?" menu

### Actual Behavior
Comment with following contents:
Debug Info can be found under **under** the "?" menu

### Debug Information
Not applicable.

**Comment by dail8859** [comment]
Seems to have been fixed.
