### ISSUE TITLE
link stops at curly brace

### ISSUE THREAD

**Issue by ranjan-2209** [notepad-plus-plus/notepad-plus-plus#7845]
I have a link like this in notepad: `https://www.instagram.com/graphql/query/?query_hash=c76146de99bb02f6447853be841dd25a&variables={"id":"0123456789","first":100}`

This stops at `{`

![bug](https://user-images.githubusercontent.com/16834561/72214465-8dab5000-3528-11ea-9812-88b4ff6f51ff.png)

**Comment by l7ucian** [comment]
Which version of notepad are you using ? It works fine for me with v7.8.3 .
![proof](https://user-images.githubusercontent.com/9266082/73157421-98014880-40e9-11ea-8fc6-3e7e4d715391.PNG)

**Comment by ranjan-ranjan** [comment]
Both v7.8.3 and now v7.8.4
Kindly don't decode HTML URL
Keep it as it is

**Comment by ArkadiuszMichalski** [comment]
@Uhf7 Your last path https://github.com/notepad-plus-plus/notepad-plus-plus/pull/8921 will fix this? @Yaron10 can you check?

**Comment by Uhf7** [comment]
No, this one I kept until the decision for or against a parser solution is made. Perhaps, it can be included too, by handling the curly braces like quotes, but it requires to make the parser more complicated and needs more testing. And, since it's no regression, I left it out. I tried to cover the most cases, not the last single one.

**Comment by Yaron10** [comment]
@ArkadiuszMichalski,

https://www.instagram.com/graphql/query/?query_hash=c76146de99bb02f6447853be841dd25a&variables={"id":"0123456789","first":100}  is not parsed as a link with 8921.
(It's parsed as a link here).

**Comment by ArkadiuszMichalski** [comment]
Fixed by https://github.com/notepad-plus-plus/notepad-plus-plus/commit/e32462188da8819db584272c76994a44cd61885e.

**Comment by ranjan-2209** [comment]
Thanks
