### ISSUE TITLE
View Current File In ____ not macro-recordable

### ISSUE THREAD

**Issue by pryrt** [notepad-plus-plus/notepad-plus-plus#7851]
### Description of the Issue
Similar to #6258, the **View > View Current File In > ____** are not macro-recordable, though they are macro-playable.  (Discovered this in [this community post](https://community.notepad-plus-plus.org/post/49839).)

### Steps to Reproduce the Issue

1. Record macro: **File > Save** then **View > View Current File In > Chrome**
2. Save macro to `SaveAndLaunchInChrome`
3. Edit the example file, so that there's something to save.  
3. Playback the macro: it saves, but doesn't launch.
4. Look at `shortcuts.xml`: the **save** id="41006" is listed, but the [`44101` for IDM_VIEW_IN_CHROME](https://github.com/notepad-plus-plus/notepad-plus-plus/blob/master/PowerEditor/src/menuCmdID.h#L354-L357) is not shown.

### Expected Behavior
File gets saved, then launched in browser.  `shortcuts.xml` contains:
```
        <Macro name="SaveFileLaunchInChrome" Ctrl="no" Alt="no" Shift="no" Key="0">
            <Action type="2" message="0" wParam="41006" lParam="0" sParam="" />
            <Action type="2" message="0" wParam="44101" lParam="0" sParam="" />
        </Macro>
```
If I manually create this _expected_ macro, it properly saves and launches in Chrome.

### Actual Behavior
File gets saved, but not launched in browser.  `shortcuts.xml` contains:
```
        <Macro name="SaveFileLaunchInChrome" Ctrl="no" Alt="no" Shift="no" Key="0">
            <Action type="2" message="0" wParam="41006" lParam="0" sParam="" />
        </Macro>
```

### Debug Information

```
Notepad++ v7.8.2   (64-bit)
Build time : Dec  4 2019 - 01:39:49
Path : C:\usr\local\apps\notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : ON
OS Name : Windows 10 Enterprise (64-bit) 
OS Version : 1903
OS Build : 18362.535
Plugins : ComparePlugin.dll LuaScript.dll MarkdownViewerPlusPlus.dll mimeTools.dll NppConverter.dll NppExec.dll NppFTP.dll PreviewHTML.dll PythonScript.dll 
```

**Comment by victorel-petrovich** [comment]
Why aren't all menu commands macro-recordable by default?

**Comment by pryrt** [comment]
> Why aren't all menu commands macro-recordable by default?

Macros obviously cannot record a user interaction (like File > Save As), so any that require such interaction are out (well, they do record the end-state of a Search-and-Replace interaction, but that's the exception; a save-as with a fixed filename wouldn't be overly useful, for example).  And EU-FOSSA security improvements a few years ago disabled other commands.  And there may be other technical reasons for some, which I don't know the details of.  All of these reasons are explained in the [FAQ](https://community.notepad-plus-plus.org/topic/25400/faq-automating-notepad) which you already know about, so I'm not sure why you're asking something you should already know the answer to.

**Comment by victorel-petrovich** [comment]
@pryrt , you're right I read that FAQ and I was just going to edit my question to replace that "all" with "most". 

So, first, if there are commands that fall out of the scope of the exceptions you mention, then why not enable all of those? 

EU-FOSSA is understandable as in "not allowed, that's it". 

> Macros obviously cannot record a user interaction (like File > Save As), 

not obvious at all to me. So what if, during macro playback, it asks user to input something? Why not let the user decide what's useful and what not for him ? 

P.S. I realize that it's not really up to you (the author of Npp decides ), so this is just another user's feedback, not necessarily addressed to you.

**Comment by pryrt** [comment]
> So, first, if there are commands that fall out of the scope of the exceptions you mention, then why not enable all of those?

Do you have any examples of commands that fall out of the scope of the exceptions that are not enabled for macro recording?  (_Edit_: The non-static menu entries, like Run menu commands, other Macros, and plugin commands, should have been in my original exception list, so do not count as "out of the scope".)

> So what if, during macro playback, it asks user to input something? 

The macro system has no way to _wait_.  It runs command 1, then command 2, ....  It has no way to "wait until user input is done".  Without a rewrite of the system, macros cannot ask users for information, because that involves waiting.  (And the s+r mentioned above is _not_ an exception to that rule; while the macro is being _recorded_, the recorder just looks for certain command messages and records them; when playing back, it just plays back a specific command, without having to wait for user input.)

**Comment by victorel-petrovich** [comment]
> Do you have any examples of commands that fall out of the scope of the exceptions that are not enabled for macro recording? 

like the very one for which you opened the Issue here? that's what triggered my initial question. There may be other similar feature-requests on the site. 

> Without a rewrite of the system, macros cannot ask users for information, because that involves waiting. 

I see. Reminds me of this https://github.com/notepad-plus-plus/notepad-plus-plus/issues/8037

**Comment by pryrt** [comment]
> like the very one for which you opened the Issue here?

How is something that was fixed 5 years ago a reasonable example to use for an overlooked command _now_?

**Comment by victorel-petrovich** [comment]
You can interpret my question as: if there are any left out commands that _could_ be enabled, then why not enable them all?

**Comment by pryrt** [comment]
> if there are any left out commands that _could_ be enabled, then why not enable them all?

If you (or anyone else) finds any commands that are left out, and can make a list of them, and make the argument for each of them for why they don't fall under the known exceptions, then you (or they) can feel free to make an issue listing them.  As far as I know, no one is aware of any more _actual_ overlooked commands, so this hypothetical is pointless to discuss.

**Comment by victorel-petrovich** [comment]
> no one is aware of any more actual overlooked commands, 

OK if so. 
Let it be as info for future readers. 

EDIT: 
@pryrt  check out this one: 
https://github.com/notepad-plus-plus/notepad-plus-plus/issues/12282 

it doesn't seem so hypothetical, does it? (or more exactly: it was/seemed hypothetical a few minutes ago, but not anymore)

**Comment by victorel-petrovich** [comment]
> > So what if, during macro playback, it asks user to input something?

> The macro system has no way to wait. It runs command 1, then command 2, .... It has no way to "wait until user input is done". Without a rewrite of the system, macros cannot ask users for information, because that involves waiting. 

Sorry, why does a macro have to have ability to _wait_ as a condition to be allowed to record such actions that popup a window for user interaction? The macro could trigger the popup, then, without waiting anything, go ahead with executing the other actions in the queue - IF there are other actions there. The user will interact with the popup when they want, if they want. 
Even less reason to not allow if the interacting-action is the last one recorded.

Or take the command File > open containing folder > explorer . It just opens the containing folder; I don't see any required user interaction at all. Maybe it's just another overlooked command.

**Comment by pryrt** [comment]
> he macro could trigger the popup, then, without waiting anything, go ahead with executing the other actions in the queue - IF there are other actions there. The user will interact with the popup when they want, if they want.

Really?  Macro = `make changes A, B, C; Save As; make changes X, Y, Z; Save As`.  If it doesn't wait, then X, Y, Z will likely be saved both times, rather than just the second.  There's good reason, even if you aren't able to see it.

> ... open containing folder ...

Not sure how useful that would be in a macro, especially one that cannot have other user interaction.  But if you think that's an oversight, open an issue, with an explanation of how it would be useful in an automated macro sequence, and see what happens.  I'm obviously not the decision maker, so the worst that would happen to you if you open a reasonable feature request would be that it would be ignored or closed -- but please don't open a separate issue for each menu command.  And don't worry, I won't come argue with you there.

**Comment by victorel-petrovich** [comment]
> Really? Macro = `make changes A, B, C; Save As; make changes X, Y, Z; Save As`. If it doesn't wait, then X, Y, Z will likely be saved both times, rather than just the second. There's good reason, even if you aren't able to see it.

I am able to see it just fine. 
The user, per doc, will simply have to know that Macros (in N++), don't wait, thus the user will not create such a macro as you show. 
Instead, they can create macro =`make changes A, B, C; Save As` which should work. Or other macros where the subsequent actions do not invalidate the actions before "Save As". 

> > ... open containing folder ...

>Not sure how useful that would be in a macro

You never know... The more is available, the more you'll be able to accomplish. Instead of being sad one day that it's not recordable (and have to go the scripting way)

> And don't worry, I won't come argue with you there. 

:) it's okay. By the way, I appreciate the answers, but never feel obliged to come answer to my questions if you're busy.

**Comment by victorel-petrovich** [comment]
@pryrt 
There are already some commands that require user input, and they are recordable, AND  the macro does wait for user to give the input and then it continues the rest of the actions!

One is "Save All".
Test:
1. start with 2 files, one preexisting, one new ; change both in a random way and don't save yet
2. copy a random word in one file ("word") 
3. Start recording: 
   1. File > Save All
   2.  (you confirm yes ,then you see it asks you to save the new file; you can choose to save or cancel)
   3. File > New
   4. Paste the "word"
4. Stop recording
5. do steps 1 and 2 and play the macro

Another "Close" or  "Close all"  when there are some unsaved files;  I just tried another macro involving this and "Save all" and also followed by typing a letter etc.

**Comment by victorel-petrovich** [comment]
@pryrt  I just did Macro = `make changes A, B, C; Save All; make changes X, Y, Z; Save All.` 
Works as desired (waits for user input , THEN continues)
Which gives?...

**Comment by pryrt** [comment]
Okay, apparently I was wrong, and thought there was a technical reason for not recording actions like Save As.  Apparently the macro system _can_ wait for a command like that before moving on to the next.  

So my next guess is that Save As is one of the ones that was deemed a security risk during the EU-FOSSA evaluation, and thus not recordable.  But, at this point, I honestly don't care anymore.

As a word of caution, there was a user a few years back who started spamming tons of Community Forum topics and Issues here (both issues of his own creation and comments on as many related, semi-related, and unrelated issues as he could justify to himself), to the point that he was banned from commenting or making feature requests at the Notepad++ project.  If you don't want that to happen to you, I suggest you just stick with the feature requests you've already made regarding the Macro system, and see what develops, rather than trying to search out and evangelize your idea on every related or semi-related issue or topic you can find.  

Good luck with your crusade.

**Comment by victorel-petrovich** [comment]
@pryrt 
> rather than trying to search out and evangelize your idea on every related or semi-related issue or topic you can find.

I suggest you keep your pointless tips to yourself. I haven't spammed anywhere and there is no "crusade".

**Comment by donho** [comment]
@victorel-petrovich 
All contributors are welcome here, as long as they make meaningful contribution.
However, we don't want people here to push their feature requests by posting everywhere and wasting our time.
Thank you for your understanding.

**Comment by victorel-petrovich** [comment]
@donho 
> All contributors are welcome here, as long as they make meaningful contribution.
However, we don't want people here to push their feature requests by posting everywhere and wasting our time.
Thank you for your understanding.

Except that I have not posted "everywhere" . My contributions are meaningful, to those who are able to understand. 
Keep wasting your time by closing all my feature requests and bug reports.

**Comment by pryrt** [comment]
> keep your pointless tips to yourself.

Sorry that it was pointless to you.  I was hoping to prevent you from creating _more_ issues and thus getting _officially_ censured.  But, given your reaction was to go delete your forum account and to start throwing insults around here, it's obvious it didn't help, so in that regard, hindsight has proven it pointless, no matter my original motives.

> there is no "crusade"

A bit of hyperbole on my part, based on the culturally-engraved line from A New Hope, where Obi-Wan explained Uncle Owen's refusal to let Kenobi give Luke the lightsaber earlier ("Your father wanted you to have this when you were old enough, but your uncle wouldn't allow it. He feared you might follow old Obi-Wan on some damned-fool idealistic crusade like your father did").  

Though I would argue, my word selection seems rather appropriate to this situation, given the different points of view involved.  While Uncle Owen might have felt it was foolish, participating in the Clone Wars didn't seem foolish to Obi-Wan and Anakin at the time; who was right is a matter of their point of view.

But yes, "crusade" has some other connotations, and is loaded enough that I should have chosen a different phrasing.

> Except that I have not posted "everywhere" . 

Creating three separate Issues, commenting in a fourth, and creating 3 separate topics in the Community forum.  

- Aug 25: https://community.notepad-plus-plus.org/topic/27104/macro-does-not-record-my-run-action
- Aug 30: https://github.com/notepad-plus-plus/notepad-plus-plus/issues/16960
- Aug 31: https://community.notepad-plus-plus.org/topic/27110/how-dynamic-id-menu-commands-are-executed-and-relation-to-macros
- Sep 01: https://community.notepad-plus-plus.org/topic/27114/next-generation-macro-system
- Sep 01: https://github.com/notepad-plus-plus/notepad-plus-plus/issues/16963
- Sep 01: https://github.com/notepad-plus-plus/notepad-plus-plus/issues/16966
- Sep 01: https://github.com/notepad-plus-plus/notepad-plus-plus/issues/7851#issuecomment-3243108443

"Everywhere" is, obviously, hyperbole -- but since you are not innocent of hyperbole, it's hardly a valid complaint from you.  One Topic and one or two Issues would have been sufficient.  Personally, I was just starting to feel you were probably being too "shotgun" with your approach, hence my "pointless" warning, to help you avoid unintended consequences.

> My contributions are meaningful, 

Some were; I even learned more about Notepad++'s macros in this discussion.  Though some appeared to me to just be trying to argue your position in as many places as possible.

> to those who are able to understand. 

So now you resort to hurtling insults at people who disagree with you, which is what nearly got you [banned from the project](https://github.com/notepad-plus-plus/notepad-plus-plus/issues/14022#issuecomment-1685087371) in 2023.  Doesn't seem a wise choice, to me.  

But since you already deleted your account of the Forum (hence the reason why the posts I linked say "A Former User" as the author), I am guessing you no longer really want to truly participate, and this was probably just a parting shot -- in which case, maybe you don't care if you are banned.

> Keep wasting your time by closing all my feature requests and bug reports.

Where by "all" you mean a hyperbole for "around 40% of my recent reports or issue-activity".  Don't believe me?  Let's look at the [facts](https://github.com/notepad-plus-plus/notepad-plus-plus/issues?q=is%3Aissue%20author%3Avictorel-petrovich):

<img width="1263" height="763" alt="Image" src="https://github.com/user-attachments/assets/0f6e3a23-b0e5-493b-ab5e-fa7553fce33b" />

I based the screenshot on the ones with activity in 2025.  I then looked at each one, to see who closed it.  Of the 10 with activity this year, 3 were closed by you, 3 are still open, and 4 were closed by @donho.  Of the 4 that @donho closed, three were your macro-related ones, and one was one where you didn't provide enough information for @donho to replicate the problem.  Honestly, 40% closure-for-reject rate (or 57% if you disregard the three you closed yourself) is reasonably common here.  Some ideas, Don just knows right away that he doesn't want, so they get closed, though those are rare; some, the poster just never explains them with the right steps to reproduce; and then there are a very few that get closed because the person who posted them gets too ... aggressive.  (That I've paid attention, the latter has only happened a few times, though I haven't spent as much time in the Issues as the Forum, so I may have missed some.  It's a bummer for you that you fell into that rare category; I was hoping that my warning would come in time that it wouldn't affect your Issues, but it's too late for that.)

And honestly, when I first read Don's [response here](https://github.com/notepad-plus-plus/notepad-plus-plus/issues/7851#issuecomment-3258040609), I actually thought he was cautioning me to _not_ be so harsh in my replies; especially since my "crusade" comment apparently triggered you to close your Forum account (looking at the timing, you deleted your Community account 10 hours ago, and the three "macro" Issue closings were 6 hours ago, so it couldn't've been the issue-closing that triggered that).  So, I will apologize for poor word choice; I will not apologize for "pointlessly" cautioning you from going too far.

**Comment by victorel-petrovich** [comment]
@pryrt sorry, I don't have time for this. Conclude what you wish.
This is my last reply here.
