### ISSUE TITLE
Closing unsaved file - no keyboard shortcuts

### ISSUE THREAD

**Issue by pgorka86** [notepad-plus-plus/notepad-plus-plus#7853]
During closing unsaved document an new popup shows up.

**Currently:**
Buttons does not support keyboard shortcuts.

**Expected:**
Buttons should support choosing option with shortcuts like:

- Yes (y)
- No (n) 
- Cancel (c)
- etc...

**Comment by xylographe** [comment]
Not all translations have been updated yet. Which localization do you use?

**Comment by pgorka86** [comment]
Polish translations

![obraz](https://user-images.githubusercontent.com/59871451/72345630-8b85f480-36d4-11ea-9e61-19c362363969.png)

**Comment by xylographe** [comment]
@pgorka86  You can download [the updated polish.xml](https://github.com/notepad-plus-plus/notepad-plus-plus/blob/master/PowerEditor/installer/nativeLang/polish.xml) or wait for the next NPP release (v7.8.3).

**Comment by pgorka86** [comment]
@xylographe - it does not seems to work. 
I have checked it with two NPP on two different machines (Win10 with NPP v7.8.2) - one x86 and one x64. 

Maybe `&amp;` is not respected at popups? I gazed at application and I do not see any other "popup" form that supports shortcuts.

**Comment by sasumner** [comment]
@pgorka86 There are more details on making it work in the comments of #6223

**Comment by xylographe** [comment]
@pgorka86 Did you remember to refresh the localization? After updating `polish.xml` you need to open the _Preferences_ dialogue, and switch to another language, then immediately switch back to Polish.

**Comment by pgorka86** [comment]
Now it works great! Thank You!

For all other readers - as one wrote in mentioned #6223 issue 

> Thanks @xylographe, so the steps are  
> * opening your localization file set an & before the letter you want to press 
> * save file 
> * opening notepad++ 
> * settings -> preferences -> change to some different language -> ok 
> * settings -> preferences - your language you want to choose -> ok  
> 
> Changing the language did the trick, not restarting notepad++ or  something else. I did it the first time the way you suggested, so it was  all right. Changing the language in Notepad++ was ultimately what was  missing.

the thing to note, that two first bulletpoints can be replaced with replacing a language file provided by @xylographe
