### ISSUE TITLE
Unsaved file error handling during Windows shutdown results in all open tabs closed

### ISSUE THREAD

**Issue by jmbox80hcl** [notepad-plus-plus/notepad-plus-plus#7854]
### Description of the Issue
When I'm shutting down windows and some file open in Notepad++ needs to be saved (in my particular instance it was a file no longer on the file system) all tabs were closed except for that file and I was presented with an option to save.  Once I saved and allowed the shutdown to continue, upon restart and reopening ++, all my previously opened tabs were still closed.   

### Steps to Reproduce the Issue
1. Open some on-disk text file
2. Delete the text file.
3. Shut down/Reboot Windows.
4. Windows indicates that Notepad++ is preventing the shutdown
5. Cancel the shutdown and switch to Notepad++.
6. Note that all tabs have already been closed despite the "Remember current session for next launch" option having been toggled on.

### Expected Behavior
Save all my session's open tabs INCLUDING the tab that I was forced to save during shutdown.

### Actual Behavior
All tabs were closed.  Notepad++ stared up as a blank slate with only a "New" tab.

### Debug Information
don't have any

**Comment by donho** [comment]
@jmbox80hcl 
Debug Information is on menu `?->Debug Info`.
Please fulfill it.

**Comment by jmbox80hcl** [comment]
Why did you close this?  You can't reproduce it yourself?  The scenario is quite easy.  😞

**Comment by sasumner** [comment]
@jmbox80hcl 

Learn how to read what github is telling you.
Click the blue `62efa46` above in the closure notice.

**Comment by jmbox80hcl** [comment]
@sasumner Thank you so much for your patience and polite explanation.

**Comment by donho** [comment]
Fix by https://github.com/notepad-plus-plus/notepad-plus-plus/commit/6000f3bb21a42a4d28d068617e0dc642ef739b26
