### ISSUE TITLE
Feature Request for Find Results Window

### ISSUE THREAD

**Issue by CXTjuan** [notepad-plus-plus/notepad-plus-plus#7855]
### Description of the Feature Request
When you do a search all files, the Find Results window shows you a list of all files that contain the text you were looking for.  It would be awesome if there was a menu item in the right click menu that would copy all of the file paths to the clipboard.

### Steps to Reproduce the Issue

N/A

### Expected Behavior
N/A

### Actual Behavior
N/A

### Debug Information
N/A

**Comment by sasumner** [comment]
It's definitely a nice-to-have list candidate.  Meanwhile, can be approximated with a copy of the find-result text into a new Notepad++ and then running two regex replace-alls (for anyone reading that might be interested in workarounds):

First, search for `(?-is)^(S|\t).+\R` and replace with *nothing*. Second, search for `^\h\h(.+?)\h\(\d+\hhits?\)` and replace with `\1`.  Can be recorded as a macro to ease pain of execution.

**Comment by CXTjuan** [comment]
Thank you for the quick reply to my inquiry.  I found that your tip works if you do a "Select All" in the result window and then drag and drop from the result window to the main window.  Thanks for the tip.

**Comment by wonkawilly** [comment]
Sorry for the OT, I'm also really sorry if I'm bothering you all, but maybe the participants to this thread would want to give their opinion about this new and rich proposal about the improvement of the Find and Replace dialog at this link: #9627. Which will be a great improvement and perhaps even a real game changer for all of us that use N++ for more advanced uses than just editing the shopping list.
Please partecipate and spread the word asking others to partecipate as well. More opinions are welcome. Thank you all.

**Comment by alankilborn** [comment]
Implemented in N++ 8.0.
See #9821
Recommend CLOSURE of this item.
