### ISSUE TITLE
At least one special CHAR (º) incorrectly saved/loaded

### ISSUE THREAD

**Issue by mcvendrell** [notepad-plus-plus/notepad-plus-plus#7858]
### Description of the Issue
The special char **º** is incorrectly saved

### Steps to Reproduce the Issue
1. Open a new file
2. Select UTF or ANSI codification
3. Write º char (can be alone or with more text)
4. Save and close
5. Open the file: codification is lost and you will see this char **ยบ** instead **º**

### Expected Behavior
File must continue to have the selected codification and the char **º** should appear.

### Actual Behavior
Codification is lost and you will see this char **ยบ** instead **º**

### Debug Information
Notepad++ v7.8.2   (64-bit)
Build time : Dec  4 2019 - 01:39:49
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS Name : Windows 10 Pro (64-bit) 
OS Version : 1903
OS Build : 18362.535
Plugins : ComparePlugin.dll mimeTools.dll NppConverter.dll NppExport.dll SQLinFormNpp64.dll XMLTools.dll

**Comment by alankilborn** [comment]
Tested in N++ 8.4.4 (current version as of this writing) and could not repro.
Recommend CLOSURE of this item.
