### ISSUE TITLE
Syntax highlighting inactive for documents opened during startup

### ISSUE THREAD

**Issue by ToniSimi** [notepad-plus-plus/notepad-plus-plus#7860]
### Description of the Issue
When documents opened during startup of Notepad++ either via command line or because they are restored from a previous session, syntax highlighting is inactive for some documents. This happens at least for .nsi and .nsh files (NSIS) and in versions 7.8.2 and 7.8.3.

### Steps to Reproduce the Issue
1. open some .nsi file
2. close Notepad++
3. open Notepad++ (.nsi file reopens automatically)

### Expected Behavior
syntax highlighting is active, text is colored

### Actual Behavior
syntax highlighting is inactive, text is gray

**Comment by ArkadiuszMichalski** [comment]
@ToniSimi Do you still have this problem in latest Notepad++ verison? If yes then put Debug Info and add some code/file example.

**Comment by donho** [comment]
Please reopen it if it happens still with 7.9 - and please provide your debug info.
