### ISSUE TITLE
Enhancement: Auto-fill "Replace with" input box

### ISSUE THREAD

**Issue by boredazfcuk** [notepad-plus-plus/notepad-plus-plus#7862]
Hi,

Just a little tweak, but I think it could add value.

Whenever I have text selected and I open the Find window, it automatically populates the "Find what" input box with the selected text.

I believe it would be beneficial for the Replace window to autofill the "Replace with" input box with whatever is stored in the clipboard too... Provided it's a single line of text.

Usually when I'm doing a find/replace, I already have my replacement text copied to the clipboard and, more often than not, just paste it in. I presume I'm not the only one.

Any thoughts?

Thanks.

**Comment by sasumner** [comment]
It's subjective, I guess.  I would much rather have *Replace with* autopopulated with the *same* text as the *Find what*.  The reasoning behind that is that a lot of the time I want to replace with something very close to what is already there, so I just need to do a slight tweak to it.  Think about giving a program variable a similar name, but making the name better with the replacement.  See, it's subjective.

**Comment by boredazfcuk** [comment]
That would be an improvement too. Definitely better than how it currently works.

It would have the added bonus that it safeguards against an accidental 'replace all' too.

**Comment by sasumner** [comment]
So here's a Pythonscript that will autopopulate *Replace with* with whatever is in *Find what* when the script is run.  Maybe it is of some value to someone.  Note that this script was pulled from something larger, so there's a few bits that don't make direct sense for this script (but it does work for the intended purpose):

```
# -*- coding: utf-8 -*-

from Npp import editor, notepad
import ctypes
from ctypes.wintypes import BOOL, HWND, LPARAM
WNDENUMPROC = ctypes.WINFUNCTYPE(BOOL, HWND, LPARAM)
u32 = ctypes.windll.user32

RWFFW__find_what_is_next = False
RWFFW__replace_with_is_next = False
RWFFW__find_what_hwnd = None
RWFFW__replace_with_hwnd = None

def RWFFW__foreach_window(hwnd, lParam):
    global RWFFW__find_what_is_next, RWFFW__replace_with_is_next, RWFFW__find_what_hwnd, RWFFW__replace_with_hwnd
    if RWFFW__find_what_is_next:
        RWFFW__find_what_hwnd = hwnd
        RWFFW__find_what_is_next = False
        return True  # continue enumeration
    if RWFFW__replace_with_is_next:
        RWFFW__replace_with_hwnd = hwnd
        RWFFW__replace_with_is_next = False
        return True  # continue enumeration
    curr_class = ctypes.create_unicode_buffer(256)
    cc = curr_class[:u32.GetClassNameW(hwnd, curr_class, 256)]
    length = u32.GetWindowTextLengthW(hwnd)
    if length > 0:
        buff = ctypes.create_unicode_buffer(length + 1)
        u32.GetWindowTextW(hwnd, buff, length + 1)
        wt = buff.value
        if u'FIND' in wt and not u'in' in wt: RWFFW__find_what_is_next = True
        if u'ind what' in wt: RWFFW__find_what_is_next = True
        if u'REPLACE' in wt: RWFFW__replace_with_is_next = True
        if u'ace with' in wt: RWFFW__replace_with_is_next = True
    return True if (RWFFW__find_what_hwnd == None or RWFFW__replace_with_hwnd == None) else False  # True continues enumeration; False stops it

notepad.menuCommand(MENUCOMMAND.SEARCH_REPLACE)
u32.EnumChildWindows(u32.FindWindowW(None, u'Replace'), WNDENUMPROC(RWFFW__foreach_window), 0)
u32.EnumChildWindows(u32.FindWindowW(None, u'Find in Files'), WNDENUMPROC(RWFFW__foreach_window), 0)
u32.EnumChildWindows(u32.FindWindowW(None, u'F/R in *FILES*'), WNDENUMPROC(RWFFW__foreach_window), 0)

if RWFFW__find_what_hwnd and RWFFW__replace_with_hwnd:
    length = u32.GetWindowTextLengthW(RWFFW__find_what_hwnd)
    if length > 0:
        buff = ctypes.create_unicode_buffer(length + 1)
        u32.GetWindowTextW(RWFFW__find_what_hwnd, buff, length + 1)
        find_what_text = buff.value
        if len(find_what_text) > 0: u32.SetWindowTextW(RWFFW__replace_with_hwnd, find_what_text)
```

I could also write the "clipboard" version of the script if there is any interest.

**Comment by boredazfcuk** [comment]
That's great, thanks.

I think your version is probably the better idea to be honest. A lot of my find/replace are changing variable names to something more appropriate as the code matures. I reckon this should save a fair bit of time.
