### ISSUE TITLE
Shortcut keys available on Close Dialog

### ISSUE THREAD

**Issue by dbmcdonald** [notepad-plus-plus/notepad-plus-plus#7864]
### Steps to Reproduce the Issue
1. Open new document
2. type gibberish
3. Ctrl-w

### Expected Behavior
4. key press of "n" for No or "y" for Yes

### Actual Behavior
Not available

**Comment by rddim** [comment]
From v7.8.2 it is available. Please re-set your language from `Settings > Preferences... > General > Localization`. Also try to follow the complete issue template!
