### ISSUE TITLE
Regression in 7.8.3: double-clicking a found-result does not work properly if Word-Wrap is ON

### ISSUE THREAD

**Issue by Yaron10** [notepad-plus-plus/notepad-plus-plus#7865]
**Steps to reproduce:**

Check `View -> Word Wrap`.
Search for a word in the current document (file A).
Switch to another tab.
Double-click a line in the Find Results window.

**Result:**
File A is activated, the search-term is selected *but the relevant line may not be visible.*
IOW, the visible lines do not change.

Probably related to https://github.com/notepad-plus-plus/notepad-plus-plus/commit/9387dcdaef19289af87f24639bf7336526d027f5 (which is a major improvement in general).

Thank you.

**Comment by Yaron10** [comment]
@cmeriaux,

Thank you for https://github.com/notepad-plus-plus/notepad-plus-plus/commit/9387dcdaef19289af87f24639bf7336526d027f5. :+1: 

Adding 
`(*_ppEditView)->_positionRestoreNeeded = false;` 
before 
`Searching::displaySectionCentered(fInfo._start, fInfo._end, *_ppEditView);` 
in `FindReplaceDlg.cpp` seems to solve the problem.

What do you think?

**Comment by cmeriaux** [comment]
@Yaron10 Thank you for the encouragements
It seems the issue was already existing in the previous release (7.8.2): the displayed section is not centered in case of word wrap. Can you confirm ?
Could you also do a screencast please ?

**Comment by Yaron10** [comment]
@cmeriaux,

Prior to 7.8.3 the line containing the search term is indeed not centered.
This should be investigated but it's relatively a minor issue.

In 7.8.3 the line containing the search term is not visible at all.

Open `Notepad_plus.cpp` (position 0, 0).
Search for `pBuf->setUserReadOnly(isStarting);`.
Switch to another tab.
Double-click `pBuf->setUserReadOnly(isStarting);` in the Find Results window.

This is prior to 7.8.3.
![תמונה](https://user-images.githubusercontent.com/10229320/72728081-372bba80-3b95-11ea-9859-dd24f991f969.png)

And this is 7.8.3.
![תמונה](https://user-images.githubusercontent.com/10229320/72728629-7c9cb780-3b96-11ea-9f26-609455c7fa51.png)

**Comment by cmeriaux** [comment]
Thanks @Yaron10 I was able to reproduce and to test with the fix you've give. Thanks
Sorry for the regression

**Comment by Yaron10** [comment]
@cmeriaux,

Thank you for testing it and submitting the PR.
And thanks again for https://github.com/notepad-plus-plus/notepad-plus-plus/commit/9387dcdaef19289af87f24639bf7336526d027f5. I think it's important and useful.
