### ISSUE TITLE
Ability to close without losing unsaved documents lost with the new save screen

### ISSUE THREAD

**Issue by FrankSalmick** [notepad-plus-plus/notepad-plus-plus#7866]
### Description of the Issue
With the old save menu, closing notepad++ through alt+f4 or the close button would save unsaved files until the next time notepad++ was opened. The "save" icon would remain red when notepad++ re-opened. With the new save menu, you only have the option to save or discard your changes.

### Steps to Reproduce the Issue
1. Create a new file in notepad++ with ctrl+n (it will be called something like "new 1")
2. Write something to the new file
3. Close notepad++ with alt+f4

### Expected Behavior
If you have other unsaved files, the "would you like to save your changes" dialogue would show for these files, but not for the "new 1" file. Notepad++ will close, and next time you open notepad++ all the files you previously had opened - including "new 1", and its unsaved contents - are visible.

### Actual Behavior
The "would you like to save your changes" dialogue shows for every file, including "new 1". The user must select yes (and save the file), no (and lose all changes), or cancel (abort closing). As far as I can tell, there is no way to have "new 1" open when notepad++ is launched next. 

### Debug Information
Killing the program through task manager also loses the "new 1" file. I'm not sure about the behaviour of this prior to the save dialogue change. Here is the debug info menu:

```
Notepad++ v7.8.2   (32-bit)  
Build time : Dec  4 2019 - 01:36:59  
Path : C:\Program Files (x86)\Notepad++\Notepad++.exe  
Admin mode : OFF  
Local Conf mode : OFF
OS Name : Windows 10 Enterprise (64-bit)   
OS Version : 1909  
OS Build : 18363.592  
Plugins : mimeTools.dll NppConverter.dll NppExport.dll   
```

**Comment by sasumner** [comment]
Can you check your setting in `Settings` > `Preferences` > `Backup` to see if `Enable session snapshot and periodic backup` is ticked or not?

I can't tell 100% yet, but it sounds like the behavior you want comes from having this box *ticked*, and I'm guessing that yours probably isn't ticked?

**Comment by FrankSalmick** [comment]
Thanks, that fixed it.
