### ISSUE TITLE
Extra buttons

### ISSUE THREAD

**Issue by tfield98** [notepad-plus-plus/notepad-plus-plus#7874]
### Description of the Issue
The Save File Dialog box shows "Yes to all" and "No to all" options even though there is only one file open when using File, Exit to close.

### Steps to Reproduce the Issue

1. Start Notepad++
2. Type something into something to a new file
3. Close the program using File, Ext

### Expected Behavior

A Save Dialog box with three buttons: Yes, No, and Cancel

### Actual Behavior

A Save Dialog box with two additional buttons Yes to all and No to all

### Debug Information

Notepad++ v7.8.2   (32-bit)
Build time : Dec  4 2019 - 01:36:59
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS Name : Windows 10 Enterprise (64-bit) 
OS Version : 1903
OS Build : 18362.535
Plugins : DSpellCheck.dll mimeTools.dll NppConverter.dll NppExport.dll 

This is a confusing design. When the user has just one file open, showing them the "Yes to All" and "No to all" buttons implies they have more than one file open and causes surprise, cuasing them to have to move their eyes up to the tab bar to see what other files are open. Of course, in this scenario there are none.

**Comment by xylographe** [comment]
Update to v7.8.3.

**Comment by tfield98** [comment]
That fixed it.  THANKS.

Before logging this issue I had tried the "Update NotePad++" menu option and had been told there were no updates available. 

Perhaps minor version fixes aren't included on that option...

**Comment by sasumner** [comment]
@tfield98 
As of this writing, 7.8.3 is "too new". 
If it proves stable enough after a bit of time, that option will be "enabled".
