### ISSUE TITLE
Allow keyboard shortcut for yes / no on confirm close window screen

### ISSUE THREAD

**Issue by whishkid** [notepad-plus-plus/notepad-plus-plus#7875]
### Description of the Issue
When you close a document that has not been saved, a confirmation screen appears with option yes/ no/ yes to all/ no to all

### Steps to Reproduce the Issue
1. Open Notepad++ 
2. Create a new document
3. Make a change to the document eg type helllo
4. click on the x next to the tab  header to close the document
5. Notice you cannot close the dialog using y for yes and n for no

### Expected Behavior
Short cut keys to access the buttons

### Actual Behavior
A click is needed

### Debug Information
Notepad++ v7.8.1   (64-bit)
Build time : Oct 27 2019 - 22:57:19
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS Name : Windows 10 Enterprise (64-bit) 
OS Version : 1809
OS Build : 17763.914
Plugins : mimeTools.dll NppConverter.dll NppExport.dll

**Comment by xylographe** [comment]
Which NPP version? Which localisation (language)?

**Comment by whishkid** [comment]
v 7.8.1
English (probably US)

**Comment by whishkid** [comment]
I have updated the debug information thank you for noticing
