### ISSUE TITLE
Feature Suggestion: Find window directional count.

### ISSUE THREAD

**Issue by jeremydrahos** [notepad-plus-plus/notepad-plus-plus#7876]
### Description of the Issue
In the Find window, when you click Count, it would be cool if the count would be accompanied by a directional count.  Let's say you're in the middle of the document and you click Count in the Find window, it gives the count as it does now, and beside it it gives the count backwards and beside that the count forwards (or vice versa).
Example:
Count: 100 matches.  Backwards: 43 matches.  Forwards: 57 matches.

**Comment by sasumner** [comment]
Really, *Count* should respect the *Backward direction* and *Wrap around* options.  It currently doesn't and is really a "Count All" function.

There are some comments about *Count* relating to this in #7838

**Comment by sasumner** [comment]
>Count: 100 matches. Backwards: 43 matches. Forwards: 57 matches.

Regarding what is presented in the user interface, nothing needs to change.  The user needs to be aware if they are doing an entire-document count, a forward-caret-to-end count, or a backward-caret-to-start count.  Thus for all cases the output is: `Count: ___ matches`

**Comment by donho** [comment]
I'm not sure it's a good thing to change the old behaviour - to count all occurrence in the document. Maybe it's better to change the button name as "Count All".

**Comment by jeremydrahos** [comment]
I meant it as an added function, not a replacement. Sometimes while you’re working in a document and you’re trying to find every occurrence of something so you can add or modify something around it, it would be helpful to know how many more occurrences you have to go, or the caret’s position in relation to all of them.  The Find window appears to have enough space to afford it as a checkbox option so it could be enabled/disabled.
It was really just an idea that may have had little application in reality.  I had found myself in the position of wondering how many occurrences there were in each direction in relation to the caret.

**Comment by sasumner** [comment]
>I meant it as an added function, not a replacement.

The way I've done PR #7917, it **IS** an additional functionality, **NOT** a replacement.

>The Find window appears to have enough space to afford it as a checkbox option so it could be enabled/disabled.

Nothing additional is needed in the user interface.  Everything is already there.  To wit:  The `Backward direction` and `Wrap around` checkbox settings just need to be taken into account when running a count.  Isn't this already described above?  Do people read these things?

>It was really just an idea that may have had little application in reality. 

False.  See immediately below.

>found myself in the position of wondering how many occurrences there were in each direction in relation to the caret.

There's your REALITY!
Plus, I have often wanted this new capability as well.

**Comment by sasumner** [comment]
@donho

>I'm not sure it's a good thing to change the old behaviour 

Is there a good argument for "not changing behavior" except that it has always been a certain way, so now that way is the only way? If we keep the old behavior we prevent new functionality from being achieved.  With the new behavior, we turn one feature into THREE. 

> Maybe it's better to change the button name as "Count All".

Well, we already have `Replace All` which does NOT really replace "all" UNLESS the `Wrap around` box is ticked.  Additionally, `Replace All` with `Backward direction` ticked replaces from caret to beginning of document, and that is also not an "all" function, no matter what the button text is.

We already have `Mark All` which does not really mark "all" UNLESS the `Wrap around` box is ticked. Additionally, `Mark All` with `Backward direction` ticked marks from caret to beginning of document, and that is also not an "all" function, no matter what the button text is.

So I would suggest that the text `Replace All` and `Mark All` is what is misleading.  BUT, they are established and I would not recommend changing those.  But I think the name `Count` is fine, and we let the `Wrap around` box indicate the "all" part.

I was suggesting an implementation that does not change the UI text at all, because UI text changes cause a ripple effect, requiring all of the language translation files to be "fixed".  It is nice when changes can avoid this.

Anyway, I feel good about whatever is decided.  It isn't like I put a lot of time into coding the change to support this.

**Comment by sasumner** [comment]
@jeremydrahos 

>It was really just an idea that may have had little application 

So, WTF, you make a feature request, and then at the first sign of balking by the developers, you back  off on it?  After I went to the trouble of coding the change and then submitting it for inclusion?  Well, I guess all I can say is (one more time) WTF, and additionally: "Thanks for your support!"  :-)

@jeremydrahos and other future readers, if the PR for this change does not get adopted, then please use the following (lame) WORKAROUND:

* To count textual occurrences from caret to end of document, follow the following steps:  (a) Invoke `Begin / End Select` from Edit menu to begin a selection, (b) Press Ctrl+End to move to end of document, (c)  Invoke `Begin / End Select` from Edit menu a second time, creating a selection, (d) Tick the `In selection` box in the `Find` window, (e) Press the `Count` button, (f) Observe the status bar of the `Find` window to see how many matches of the `Find what` box text occur from caret to end-of-file.

* To count textual occurrences from start of document to caret possition, follow the following steps:  (a) Invoke `Begin / End Select` from Edit menu to begin a selection, (b) Press Ctrl+Home to move to start of document, (c)  Invoke `Begin / End Select` from Edit menu a second time, creating a selection, (d) Tick the `In selection` box in the `Find` window, (e) Press the `Count` button, (f) Observe the status bar of the `Find` window to see how many matches of the `Find what` box text occur from beginning-of-file to caret.

**Comment by jeremydrahos** [comment]
@sasumner, I didn't realize you had gone through the trouble to make it happen.  I'm sorry.  I had just read the replies in the notification email and not in the context of the thread where I could see that you had taken it to task.  I didn't want my suggestion to cause issues between others, so I timidly tried to play it down.  I appreciate your work.  Thank you.

**Comment by sasumner** [comment]
Another possible WORKAROUND is a Pythonscript posted (by me!) on 24 Nov 2017 at 10:42p on the Community site in this thread: https://community.notepad-plus-plus.org/topic/14320/make-find-next-find-prev-buttons-an-option/

**Comment by sasumner** [comment]
>So, WTF, you make a feature request, and then at the first sign of balking by the developers, you back off on it? After I went to the trouble of coding the change and then submitting it for inclusion? Well, I guess all I can say is (one more time) WTF, and additionally: "Thanks for your support!" :-)

@jeremydrahos , just so you know, that entire comment was made in jest.

**Comment by donho** [comment]
@sasumner 
It makes sens your arguments.

**Comment by sasumner** [comment]
@donho No laugh about when I said "...I put a lot of time into coding the change" ?? :-)

**Comment by donho** [comment]
@sasumner 
I know it could be true to take (a lot of) time to realize there's one line to fix it.
It's the f**king life of all devs :)

**Comment by sasumner** [comment]
@donho 

Well, this time, it was the _FIRST_ thing I tried.  
So basically _ZERO_ time spent on it!
Sometimes even developers are blessed.
