### ISSUE TITLE
JavaScript Formatting Issue/Error

### ISSUE THREAD

**Issue by MistakingManx** [notepad-plus-plus/notepad-plus-plus#7879]
### Description of the Issue
When coding in JavaScript, using \\` doesn't format properly.
Instead of canceling out like it would with \\" or \\', it just keeps going and makes it hard to read,
even though it runs perfectly fine when executed.

### Expected Behavior
Keep it in.. quotes? I think that's what you'd call these too.

### Actual Behavior
It doesn't cancel out the format like it would with " " and ' ' resulting in a messed up enviorment, even though it works fine when executed.

### Example Screenshot
![image](https://user-images.githubusercontent.com/28667267/72863459-a5a86f80-3c9e-11ea-9c96-9b5b37ebf12f.png)

_**Sorry for being so petty about it, it's just been an issue that's bothered me for a few years now**_

**Comment by donho** [comment]
https://github.com/notepad-plus-plus/notepad-plus-plus/issues/3822#issuecomment-697275450
