### ISSUE TITLE
Replacing character as newline character (\n) results in LF character instead of set EOL character for document

### ISSUE THREAD

**Issue by Wojciech-Kopec** [notepad-plus-plus/notepad-plus-plus#7889]
**Description of the Issue**
When spliting values as separate lines, that is f.e. replacing comma (",") for newline character (Search mode set as Extended or Regular Expression) replacing character results in LF new-line character instead of EOL settings set for document (Windows CR LF or Macintosh CR EOL setting). Saving/realoding document do not change the issue

**Steps to Reproduce the Issue**
1. Create/open document with EOL set to Windows CR LF or Macintosh CR.
2. Write in document list of values separated by comma character f.e. "banana,apple,onion,peanuts"
3. Change document setting to show all character - View -> Show Symbol -> check All characters.
4. Replace comma character (",") by newline ("\n") - Search -> Find -> Replace -> 
Find what : , 
Replace with : \n
Search mode set to Extended or Regular Expression
-> Replace all

**Expected Behavior**
EOL character is identical to EOL setting for document

**Actual Behavior**
replacing EOL character is always LF character

**Debug Information**
Notepad++ v7.8.1   (32-bit)
Build time : Oct 27 2019 - 22:46:07
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS Name : Windows 10 Enterprise (64-bit) 
OS Version : 1903
OS Build : 18362.592
Plugins : ComparePlugin.dll JSMinNPP.dll mimeTools.dll NppConverter.dll NppExport.dll XMLTools.dll 

![image](https://user-images.githubusercontent.com/24297270/73060999-701ba600-3e99-11ea-8297-d8b0a531489e.png)

**Comment by sasumner** [comment]
I follow what you are saying but the Notepad++ design is such that when using regular expressions there is no awareness of the document's line-ending characters.  You must use `\n` for linefeed line-endings and `\r\n` for carriagereturn+linefeed line-endings.

This is unlike, say, C, where `\n` used in a printf-format string when writing to files will result in `\n` being written on Linux systems and `\r\n` being written on Windows systems.

Thank you for your thoughts but this behavior of Notepad++ won't be changed.
