### ISSUE TITLE
Sorting lines do not work with different EOL character than document's

### ISSUE THREAD

**Issue by Wojciech-Kopec** [notepad-plus-plus/notepad-plus-plus#7890]
**Description of the Issue**
Somehow followup issue to https://github.com/notepad-plus-plus/notepad-plus-plus/issues/7889
Sort Lines operations do not work properly when lines have different EOL character than document's.
**Lines with different EOL are treated as one single line until document's valid EOL appears or EOF.**
Tested with document having its EOL set to Windows/Macintosh with LF characters resulting from Replace action as in above issue Somehow followup issue to https://github.com/notepad-plus-plus/notepad-plus-plus/issues/7889

**Steps to Reproduce the Issue**

**Steps 1-4 are copied from https://github.com/notepad-plus-plus/notepad-plus-plus/issues/7889
 issue:**
1. Create/open document with EOL set to Windows CR LF or Macintosh CR.
2. Write in document list of values separated by comma character f.e. "banana,apple,onion,peanuts"
3. Change document setting to show all character - View -> Show Symbol -> check All characters.
4. Replace comma character (",") by newline ("\n") - Search -> Find -> Replace ->
Find what : ,
Replace with : \n
Search mode set to Extended or Regular Expression
-> Replace all

5. Sort lines - Edit -> Line Operations -> any of "Sort lines..." operations
 
**Expected Behavior**
Lines are sorted by desired way

**Actual Behavior**
Lines with different EOL than document's are not sorted 

**Debug Information**
Notepad++ v7.8.1   (32-bit)
Build time : Oct 27 2019 - 22:46:07
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS Name : Windows 10 Enterprise (64-bit) 
OS Version : 1903
OS Build : 18362.592
Plugins : ComparePlugin.dll JSMinNPP.dll mimeTools.dll NppConverter.dll NppExport.dll XMLTools.dll 

**Pre-sort:**
Lines with CRLF were added manually, lines with LF are results of Replace operation
![image](https://user-images.githubusercontent.com/24297270/73061545-ba515700-3e9a-11ea-9602-fb6a241c5372.png)

**Post-sort (lexicographically ascending):**
![image](https://user-images.githubusercontent.com/24297270/73061584-c9d0a000-3e9a-11ea-8fff-a275eb5d62b0.png)

**Comment by sasumner** [comment]
Very similar to #7735

**Comment by aetonsi** [comment]
Can confirm that mixed line endings completely mess up line sorting.

Here's another example:
![image](https://user-images.githubusercontent.com/18366087/80206252-4acf3d00-862c-11ea-98a8-0f1d0c30e884.png)

**Comment by sasumner** [comment]
Closing as this is being worked via #7735
