### ISSUE TITLE
Wrong JSON syntax highlighting

### ISSUE THREAD

**Issue by aslze** [notepad-plus-plus/notepad-plus-plus#7892]
JSON syntax highlighting is incomplete and does not follow Style Configurator settings.

This is N++ 7.8.3.

The only highlighting seen is in property names, but not in values. That is, in this code:

```json
{"x": "hello", "y": 3.5, "z": true}
```

Only "x", "y" and "z" are specially colored. And the color used for them is the one configured for **NUMBER** in Style Configurator.

In fact, Style Configurator only shows settings for DEFAULT, NUMBER, STRING, CHARACTER and OPERATOR. Not sure what CHARACTER means, as there are no character literals in JSON (maybe embedded escapes). There should probably be a specific setting for **property names** (what is currently highlighted) and one for the special values `true`, `false` and `null`.

Scintilla seems to support JSON:

https://sourceforge.net/p/scintilla/feature-requests/1140/

**Comment by donho** [comment]
Yes, it does work.
You have to remove your langs.xml then relaunch your Notepad++ if you upgraded it from an old version.
