### ISSUE TITLE
Code folding, C language, preprocessor commands - #else not a fold point

### ISSUE THREAD

**Issue by griggs01** [notepad-plus-plus/notepad-plus-plus#79]
PortableApps version 6.7.7, win 7 enterprise OS. Minor code folding issue - 
# ifdef _DEBUG                              // this is recognized as a fold point
# define new DEBUG_NEW
# else                                              // this is NOT recognized as a fold point
# define new DEBUG_OLD
# endif                                             // this is recognized as a fold termination

**Comment by NN---** [comment]
Confirm this bug.

**Comment by MetaChuh** [comment]
closed due to inactivity
