### ISSUE TITLE
Cross build this notepad++ on linux cross compile

### ISSUE THREAD

**Issue by abdulbadii** [notepad-plus-plus/notepad-plus-plus#7900]
How can we build this notepad++ on linux cross compile?
I have ready arch or ubuntu/mint dual boot menu with Windows, whichever would be the best way to implement and realize the complete build, and what are the definitive step by step to achieve this goal?
Thanks!

**Comment by sasumner** [comment]
What is the value in doing this?  Assuming there is some value, nobody is going to provide you a "step by step". Sorry.

**Comment by chcg** [comment]
@abdulbadii I started some testbuild on ubuntu via CI appveyor, see https://github.com/chcg/notepad-plus-plus/blob/appveyor_ubuntu/appveyor.yml . The relevant parts are the one with sh:

```
    - sh: sudo apt-get -qq update
    - sh: sudo apt-get -qq install -y mingw-w64-i686-dev
    - sh: sudo apt-get -qq install -y g++-mingw-w64-i686
    - sh: sudo apt-get -qq install -y gcc-mingw-w64-i686
    - sh: sudo update-alternatives --set i686-w64-mingw32-g++ /usr/bin/i686-w64-mingw32-g++-posix
    - sh: sudo update-alternatives --set i686-w64-mingw32-gcc /usr/bin/i686-w64-mingw32-gcc-posix
```
to get mingw and build via:

```
   - sh: cd "$APPVEYOR_BUILD_FOLDER"/scintilla/win32/
    - sh: export PATH=/usr/bin/i686-w64-mingw32-gcc/bin:/usr/bin/i686-w64-mingw32-g++/bin:$PATH
 
   - sh: make -j CXX=i686-w64-mingw32-g++ WINDRES=i686-w64-mingw32-windres
```

```
  - sh: cd "$APPVEYOR_BUILD_FOLDER"/PowerEditor/gcc/
  - sh: make
```

, but there are a link issue for npp, see https://ci.appveyor.com/project/chcg/notepad-plus-plus/builds/30220336#L1289

> /usr/bin/i686-w64-mingw32-ld: cannot find -lsensapi
> collect2: error: ld returned 1 exit status
> makefile:269: recipe for target '../bin/NotepadPP.exe' failed
> make: *** [../bin/NotepadPP.exe] Error 1
> Command exited with code 2
> Build failed

**Comment by sasumner** [comment]
@chcg Should this be reopened?

**Comment by chcg** [comment]
I think that is not necessary. My starting point was #7743 and I just wanted to countercheck the compiler warnings on linux and fix the compiler warnings based on that issue.

**Comment by minnyres** [comment]
v8.6.7 can be cross compiled by
`make CXX=x86_64-w64-mingw32-g++ RC="x86_64-w64-mingw32-windres -c 65001"    `
