### ISSUE TITLE
Context menu button is not Turkish.

### ISSUE THREAD

**Issue by DrakeMcCain** [notepad-plus-plus/notepad-plus-plus#7904]
Would you fix this string like this: "&Notepad++ ile düzenle"

<a href="https://hizliresim.com/zGWvzg"><img src="https://i.hizliresim.com/zGWvzg.png"></a>

**Comment by sasumner** [comment]
This type of thing has been declined before.
Suggest you edit your registry to replace *Edit with Notepad++* with an appropriate translated string.

**Comment by xylographe** [comment]
@sasumner 
Unfortunately, that translated string will be overwritten at the next NPP update.

**Comment by DrakeMcCain** [comment]
@xylographe 
Exactly! Translating that regedit key for every update is boring.

Why don't they just add that translated string to updates? I think doing this should not be hard.

**Comment by sasumner** [comment]
@xylographe said:

> that translated string will be overwritten at the next NPP update

I'm well aware of that for previous readings on this topic.  Solution to that is to keep a .reg file on hand; not that big of a deal to re-punch the registry.

@DrakeMcCain said:

>Translating that regedit key for every update is boring.

.reg file

>...I think doing this should not be hard

My standard response:  Notepad++ is open source and is "donationware"; please make the change yourself, submit it as a PR, and in my mind, you have then "donated" -- not money, but a "donation" nonetheless.  Money is good, too.  :-)

I usually make also make a comment about how, until you get into the bowels of doing something, you really don't know how "easy" or "hard" something is, so it is best not to make comments of that nature, in general.  Not judging the difficulty of this one, just making a blanket comment.  Another way of saying it is here: https://quoteinvestigator.com/2010/05/17/remain-silent/

**Comment by xylographe** [comment]
A ‘how’ has been mentioned in https://github.com/notepad-plus-plus/notepad-plus-plus/issues/7747#issuecomment-568120088.

**Comment by sasumner** [comment]
@xylographe Thanks for that link.  I will now close this issue based on the decision made in #7747 .

**Comment by krystian3w** [comment]
In theory, you could uncheck the creation of a context menu once in the past and it would not be overwritten.

I assume that someone has checked how the menu works, from the 8.4.x line with the 8.5 installer when the box is further unchecked when the new library the old registry does not bother.
