### ISSUE TITLE
Control over "Find" dialogue box behaviour.

### ISSUE THREAD

**Issue by vikrant123pundir** [notepad-plus-plus/notepad-plus-plus#7908]
### Expected Behavior
I want "Find" dialogue box to not to get closed untill I hit "escape" key or "close" button.

### Actual Behavior
Find dialogue box closes by itself after "Find All in All Documents" & "Find All in Current Document" commands.

### My Solution
I know that for programmers, the present scenario is ideal. But I use notepad++ for research purposes & it is one of the core application of my workflow.
I would be really happy if there was a checkbox under "Settings"--->"Preferences..."--->"MISC." for controlling "Find" dialogue box behaviour.
That will not upset the programmers either.

**Comment by sasumner** [comment]
Quit Notepad++, open config.xml in notepad.exe, change the value of the existing parameter:

`dlgAlwaysVisible="no"`

to 

`dlgAlwaysVisible="yes"`

I believe this is in the new help documentation.

**Comment by sasumner** [comment]
Reopening -- I will make this behavior controllable via a _Preference_ setting on the newly-created _Searching_ subpage (from issue 8131).

**Comment by sasumner** [comment]
Changes from this issue released in Notepad++ version 7.9
