### ISSUE TITLE
Can anyone add a priority encoding when opening a file in the settings?

### ISSUE THREAD

**Issue by fengchen-github** [notepad-plus-plus/notepad-plus-plus#7918]
### Description of the Issue

Sometimes when opening an ansi-encoded file, garbled characters appear

### Steps to Reproduce the Issue

1. Select "Encoding-> Encode in ANSI" in the menu and it will be OK.
2. 
3. 

### Expected Behavior

Add preference encoding when opening files in settings

### Actual Behavior

There is currently no place to set

**Comment by alankilborn** [comment]
Since this item lacks sufficient detail for replication, recommend CLOSURE.

**Comment by ArkadiuszMichalski** [comment]
Close due to lack of information. If problem still exist then please provide more detailed information (in accordance with the issue template).
