### ISSUE TITLE
On VS 2015, in 5th step cannot compile

### ISSUE THREAD

**Issue by abdulbadii** [notepad-plus-plus/notepad-plus-plus#7920]
### Description of the Issue
On VS 2015, cannot compile after reaching at 5th step of  `To build SciLexer.dll with boost:` instruction

### Steps to Reproduce the Issue
Normal process went through (use build lib in 64 bit) as instructed within which `C:\sources` is substituted with `D:\MSYS\usr\src\` and `C:\tmp\boostregexLib\x64` is substituted with `X:\T\boostregexLib\x64`

 1. Download the [Boost source code](https://www.boost.org/users/history/version_1_70_0.html).
 2. Unzip boost. In my case, It's unzipped in `C:\sources\boost_1_70_0`
 3. Build regex of boost. With the version 1.70, launch `bootstrap.bat` under the boost root, `b2.exe` will be generated beside of `bootstrap.bat`. For building boost PCRE lib, go into regex build directory by typing `cd C:\sources\boost_1_70_0\libs\regex\build` then launch `C:\sources\boost_1_70_0\b2.exe toolset=msvc link=static threading=multi runtime-link=static address-model=64 release stage`.
 Note that **address-model=64** is optional if you want to build lib in 64 bits. For 32 bits build, just remove **address-model=64** frome the command line.
 4. Copy generated message from  `C:\sources\boost_1_70_0\bin.v2\libs\regex\build\msvc-14.1\release\address-model-64\link-static\runtime-link-static\threading-multi\libboost_regex-vc141-mt-s-x64-1_70.lib` to `C:\tmp\boostregexLib\x64\`

### Expected Behavior
On 5th step then the build process should generate SciLexer.dll

### Actual Behavior
Compile interrupt with at least 19 errors, see below

### Debug Information
```
D:\MSYS\usr\src\notepad-plus-plus-master\scintilla\win32>
nmake BOOSTPATH=D:\MSYS\usr\src\boost_1_70_0\ BOOSTREGEXLIBPATH=X:\T\boostregexLib\x64\ -f scintilla.mak

Microsoft (R) Program Maintenance Utility Version 14.00.23506.0
Copyright (C) Microsoft Corporation.  All rights reserved.

        cl -Zi -TP -MP -W4 -EHsc -std:c++17 -D_CRT_SECURE_CPP_OVERLOAD_STANDARD_NAMES=1 -D_CRT_SECURE_NO_DEPRECATE=1 -D_SCL_SECURE_NO_WARNINGS=1  -O1 -MT -DNDEBUG -GL -I../include -I../src -I../lexlib -ID:\MSYS\usr\src\boost_1_70_0\ -DSCI_OWNREGEX -D_SILENCE_ALL_CXX17_DEPRECATION_WARNINGS -c ../boostregex/BoostRegexSearch.cxx
Microsoft (R) C/C++ Optimizing Compiler Version 19.00.23506 for x64
Copyright (C) Microsoft Corporation.  All rights reserved.

cl : Command line warning D9002 : ignoring unknown option '-std:c++17'
BoostRegexSearch.cxx
D:\MSYS\usr\src\notepad-plus-plus-master\scintilla\include\Platform.h(339): error C2039: 'string_view': is not a member of 'std'
D:\APP\VS2015\VC\INCLUDE\vector(17): note: see declaration of 'std'
D:\MSYS\usr\src\notepad-plus-plus-master\scintilla\include\Platform.h(339): error C3646: 'Text': unknown override specifier
D:\MSYS\usr\src\notepad-plus-plus-master\scintilla\include\Platform.h(339): error C2059: syntax error: ')'
D:\MSYS\usr\src\notepad-plus-plus-master\scintilla\include\Platform.h(339): error C2238: unexpected token(s) preceding ';'
D:\MSYS\usr\src\notepad-plus-plus-master\scintilla\include\Platform.h(401): error C2039: 'unique_ptr': is not a member of 'std'
D:\APP\VS2015\VC\INCLUDE\vector(17): note: see declaration of 'std
...
```
What should be the mistaken configuration ?
Useful help will be verily thanked

**Comment by red-angel** [comment]
I have the same issue, how can i fix it?
`D:\src\notepad-plus-plus\scintilla\win32>nmake BOOSTPATH=D:\src\notepad-plus-plus\boost_1_70_0 BOOSTREGEXLIBPATH=D:\src\notepad-plus-plus\tmp\boostregexLib\x64 -f scintilla.mak
Microsoft (R) Program Maintenance Utility Version 14.00.24234.1
Copyright (C) Microsoft Corporation.  All rights reserved.
        cl -Zi -TP -MP -W4 -EHsc -std:c++17 -D_CRT_SECURE_CPP_OVERLOAD_STANDARD_NAMES=1 -D_CRT_SECURE_NO_DEPRECATE=1 -D_SCL_SECURE_NO_WARNINGS=1  -O1 -MT -DNDEBUG -GL -I../include -I../src -I../lexlib -ID:\src\notepad-plus-plus\boost_1_70_0 -DSCI_OWNREGEX -D_SILENCE_ALL_CXX17_DEPRECATION_WARNINGS -c ../boostregex/BoostRegexSearch.cxx
Microsoft (R) C/C++ Optimizing Compiler Version 19.00.24234.1 for x86
Copyright (C) Microsoft Corporation.  All rights reserved.
cl : Command line warning D9002 : ignoring unknown option '-std:c++17'
BoostRegexSearch.cxx
D:\src\notepad-plus-plus\scintilla\include\Platform.h(339): error C2039: 'string_view': is not a member of 'std'`
