### ISSUE TITLE
Fail on "To build SciLexer.dll with boost"

### ISSUE THREAD

**Issue by abdulbadii** [notepad-plus-plus/notepad-plus-plus#7922]
Apologize in advance but I do need guidance and help on this
After install VS 2017 with CLI, and fulfill all steps up to the fifth of
`To build SciLexer.dll with boost`
...
...
 5. Go in scintilla\win32\ and run
nmake BOOSTPATH=your_boost_root_path BOOSTREGEXLIBPATH=your_built_lib_path -f scintilla.mak

On me this is:
`nmake BOOSTPATH=D:\MSYS\usr\src\boost_1_70_0\ BOOSTREGEXLIBPATH=X:\T\boostregexLib\x64\ -f scintilla.mak`
but it interrupted such:
```
cl -Zi -TP -MP -W4 -EHsc -std:c++latest -D_CRT_SECURE_CPP_OVERLOAD_STANDARD_NAMES=1 -D_CRT_SECURE_NO_DEPRECATE=1 -D_SCL_SECURE_NO_WARNINGS=1  -O1 -MT -DNDEBUG -GL -I../include -I../src -I../lexlib -ID:\MSYS\usr\src\boost_1_70_0\ -DSCI_OWNREGEX -D_SILENCE_ALL_CXX17_DEPRECATION_WARNINGS -c ../boostregex/BoostRegexSearch.cxx

Microsoft (R) C/C++ Optimizing Compiler Version 19.10.25017 for x64
Copyright (C) Microsoft Co

BoostRegexSearch.cxx
D:\MSYS\usr\src\notepad-plus-plus-master\scintilla\include\Platform.h(401): error C2039: 'unique_ptr': is not a member of 'std'
D:\APP\VS2017\VC\Tools\MSVC\14.10.25017\include\vector(15): note: see declaration of 'std'
D:\MSYS\usr\src\notepad-plus-plus-master\scintilla\include\Platform.h(401): error C2143: syntax error: missing ';' before '<'
```
...
For Platform.h line 401 :
```
400	virtual void Copy(PRectangle rc, Point from, Surface &surfaceSource)=0;
401	virtual std::unique_ptr<IScreenLineLayout> Layout(const IScreenLine *screenLine) = 0;
```
### Debug Information
complete MSVC error messages:

> D:\MSYS\usr\src\notepad-plus-plus-master\scintilla\include\Platform.h(401): error C2039: 'unique_ptr': is not a member of 'std'
> D:\APP\VS2017\VC\Tools\MSVC\14.10.25017\include\vector(15): note: see declaration of 'std'
> D:\MSYS\usr\src\notepad-plus-plus-master\scintilla\include\Platform.h(401): error C2143: syntax error: missing ';' before '<'
> D:\MSYS\usr\src\notepad-plus-plus-master\scintilla\include\Platform.h(401): error C2433: 'Scintilla::Surface::unique_ptr': 'virtual' not permitted on data declarations
> D:\MSYS\usr\src\notepad-plus-plus-master\scintilla\include\Platform.h(401): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
> D:\MSYS\usr\src\notepad-plus-plus-master\scintilla\include\Platform.h(401): error C2238: unexpected token(s) preceding ';'
> D:\MSYS\usr\src\notepad-plus-plus-master\scintilla\src\UniqueString.h(20): error C2039: 'unique_ptr': is not a member of 'std'
> D:\APP\VS2017\VC\Tools\MSVC\14.10.25017\include\vector(15): note: see declaration of 'std'
> D:\MSYS\usr\src\notepad-plus-plus-master\scintilla\src\UniqueString.h(20): error C2061: syntax error: identifier 'unique_ptr'
> D:\MSYS\usr\src\notepad-plus-plus-master\scintilla\src\UniqueString.h(24): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
> D:\MSYS\usr\src\notepad-plus-plus-master\scintilla\src\UniqueString.h(24): error C2146: syntax error: missing ';' before identifier 'UniqueStringCopy'
> D:\MSYS\usr\src\notepad-plus-plus-master\scintilla\src\UniqueString.h(30): error C2923: 'std::vector': 'Scintilla::UniqueString' is not a valid template type argument for parameter '_Ty'
> D:\MSYS\usr\src\notepad-plus-plus-master\scintilla\src\UniqueString.h(24): note: see declaration of 'Scintilla::UniqueString'
> D:\MSYS\usr\src\notepad-plus-plus-master\scintilla\src\UniqueString.h(30): error C3203: 'allocator': unspecialized class template can't be used as a template argument for template parameter '_Alloc', expected a real type
> D:\MSYS\usr\src\notepad-plus-plus-master\scintilla\src\Partitioning.h(65): error C2143: syntax error: missing ';' before '<'
> D:\MSYS\usr\src\notepad-plus-plus-master\scintilla\src\Partitioning.h(199): note: see reference to class template instantiation 'Scintilla::Partitioning<T>' being compiled
> D:\MSYS\usr\src\notepad-plus-plus-master\scintilla\src\Partitioning.h(65): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
> D:\MSYS\usr\src\notepad-plus-plus-master\scintilla\src\Partitioning.h(65): error C2238: unexpected token(s) preceding ';'
> D:\MSYS\usr\src\notepad-plus-plus-master\scintilla\src\RunStyles.h(28): error C2143: syntax error: missing ';' before '<'
> D:\MSYS\usr\src\notepad-plus-plus-master\scintilla\src\RunStyles.h(60): note: see reference to class template instantiation 'Scintilla::RunStyles<DISTANCE,STYLE>' being compiled
> D:\MSYS\usr\src\notepad-plus-plus-master\scintilla\src\RunStyles.h(28): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
> D:\MSYS\usr\src\notepad-plus-plus-master\scintilla\src\RunStyles.h(28): error C2238: unexpected token(s) preceding ';'
> D:\MSYS\usr\src\notepad-plus-plus-master\scintilla\src\RunStyles.h(29): error C2143: syntax error: missing ';' before '<'
> D:\MSYS\usr\src\notepad-plus-plus-master\scintilla\src\RunStyles.h(29): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
> D:\MSYS\usr\src\notepad-plus-plus-master\scintilla\src\RunStyles.h(29): error C2238: unexpected token(s) preceding ';'
> D:\MSYS\usr\src\notepad-plus-plus-master\scintilla\src\ContractionState.h(47): error C2039: 'unique_ptr': is not a member of 'std'
> D:\APP\VS2017\VC\Tools\MSVC\14.10.25017\include\vector(15): note: see declaration of 'std'
> D:\MSYS\usr\src\notepad-plus-plus-master\scintilla\src\ContractionState.h(47): error C2143: syntax error: missing ';' before '<'
> D:\MSYS\usr\src\notepad-plus-plus-master\scintilla\src\ContractionState.h(47): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
> D:\MSYS\usr\src\notepad-plus-plus-master\scintilla\src\CellBuffer.h(36): error C2039: 'unique_ptr': is not a member of 'std'
> D:\APP\VS2017\VC\Tools\MSVC\14.10.25017\include\vector(15): note: see declaration of 'std'
> D:\MSYS\usr\src\notepad-plus-plus-master\scintilla\src\CellBuffer.h(36): error C2143: syntax error: missing ';' before '<'
> D:\MSYS\usr\src\notepad-plus-plus-master\scintilla\src\CellBuffer.h(36): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
> D:\MSYS\usr\src\notepad-plus-plus-master\scintilla\src\CellBuffer.h(36): error C2238: unexpected token(s) preceding ';'
> D:\MSYS\usr\src\notepad-plus-plus-master\scintilla\src\CellBuffer.h(122): error C2039: 'unique_ptr': is not a member of 'std'
> D:\APP\VS2017\VC\Tools\MSVC\14.10.25017\include\vector(15): note: see declaration of 'std'
> D:\MSYS\usr\src\notepad-plus-plus-master\scintilla\src\CellBuffer.h(122): error C2143: syntax error: missing ';' before '<'
> D:\MSYS\usr\src\notepad-plus-plus-master\scintilla\src\CellBuffer.h(122): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
> D:\MSYS\usr\src\notepad-plus-plus-master\scintilla\src\CellBuffer.h(122): error C2238: unexpected token(s) preceding ';'
> D:\MSYS\usr\src\notepad-plus-plus-master\scintilla\src\Decoration.h(53): error C2039: 'unique_ptr': is not a member of 'std'
> D:\APP\VS2017\VC\Tools\MSVC\14.10.25017\include\vector(15): note: see declaration of 'std'
> D:\MSYS\usr\src\notepad-plus-plus-master\scintilla\src\Decoration.h(53): error C2143: syntax error: missing ';' before '<'
> D:\MSYS\usr\src\notepad-plus-plus-master\scintilla\src\Decoration.h(53): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
> D:\MSYS\usr\src\notepad-plus-plus-master\scintilla\src\Decoration.h(53): error C2086: 'int Scintilla::unique_ptr': redefinition
> D:\MSYS\usr\src\notepad-plus-plus-master\scintilla\src\ContractionState.h(47): note: see declaration of 'Scintilla::unique_ptr'
> D:\MSYS\usr\src\notepad-plus-plus-master\scintilla\src\Decoration.h(55): error C2039: 'unique_ptr': is not a member of 'std'
> D:\APP\VS2017\VC\Tools\MSVC\14.10.25017\include\vector(15): note: see declaration of 'std'
> D:\MSYS\usr\src\notepad-plus-plus-master\scintilla\src\Decoration.h(55): error C2143: syntax error: missing ';' before '<'
> D:\MSYS\usr\src\notepad-plus-plus-master\scintilla\src\Decoration.h(55): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
> D:\MSYS\usr\src\notepad-plus-plus-master\scintilla\src\Decoration.h(55): error C2086: 'int Scintilla::unique_ptr': redefinition
> D:\MSYS\usr\src\notepad-plus-plus-master\scintilla\src\ContractionState.h(47): note: see declaration of 'Scintilla::unique_ptr'
> D:\MSYS\usr\src\notepad-plus-plus-master\scintilla\src\Document.h(234): error C2039: 'unique_ptr': is not a member of 'std'
> D:\APP\VS2017\VC\Tools\MSVC\14.10.25017\include\vector(15): note: see declaration of 'std'
> D:\MSYS\usr\src\notepad-plus-plus-master\scintilla\src\Document.h(234): error C2143: syntax error: missing ';' before '<'
> D:\MSYS\usr\src\notepad-plus-plus-master\scintilla\src\Document.h(234): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
> D:\MSYS\usr\src\notepad-plus-plus-master\scintilla\src\Document.h(234): error C2238: unexpected token(s) preceding ';'
> D:\MSYS\usr\src\notepad-plus-plus-master\scintilla\src\Document.h(248): error C2039: 'unique_ptr': is not a member of 'std'
> D:\APP\VS2017\VC\Tools\MSVC\14.10.25017\include\vector(15): note: see declaration of 'std'
> D:\MSYS\usr\src\notepad-plus-plus-master\scintilla\src\Document.h(248): error C2143: syntax error: missing ';' before '<'
> D:\MSYS\usr\src\notepad-plus-plus-master\scintilla\src\Document.h(248): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
> D:\MSYS\usr\src\notepad-plus-plus-master\scintilla\src\Document.h(248): error C2238: unexpected token(s) preceding ';'
> D:\MSYS\usr\src\notepad-plus-plus-master\scintilla\src\Document.h(256): error C2039: 'unique_ptr': is not a member of 'std'
> D:\APP\VS2017\VC\Tools\MSVC\14.10.25017\include\vector(15): note: see declaration of 'std'
> D:\MSYS\usr\src\notepad-plus-plus-master\scintilla\src\Document.h(256): error C2143: syntax error: missing ';' before '<'
> D:\MSYS\usr\src\notepad-plus-plus-master\scintilla\src\Document.h(256): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
> D:\MSYS\usr\src\notepad-plus-plus-master\scintilla\src\Document.h(256): error C2238: unexpected token(s) preceding ';'
> D:\MSYS\usr\src\notepad-plus-plus-master\scintilla\src\Document.h(257): error C2039: 'unique_ptr': is not a member of 'std'
> D:\APP\VS2017\VC\Tools\MSVC\14.10.25017\include\vector(15): note: see declaration of 'std'
> D:\MSYS\usr\src\notepad-plus-plus-master\scintilla\src\Document.h(257): error C2143: syntax error: missing ';' before '<'
> D:\MSYS\usr\src\notepad-plus-plus-master\scintilla\src\Document.h(257): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
> D:\MSYS\usr\src\notepad-plus-plus-master\scintilla\src\Document.h(257): error C2238: unexpected token(s) preceding ';'
> D:\MSYS\usr\src\notepad-plus-plus-master\scintilla\src\Document.h(285): error C2039: 'unique_ptr': is not a member of 'std'
> D:\APP\VS2017\VC\Tools\MSVC\14.10.25017\include\vector(15): note: see declaration of 'std'
> D:\MSYS\usr\src\notepad-plus-plus-master\scintilla\src\Document.h(285): error C2143: syntax error: missing ';' before '<'
> D:\MSYS\usr\src\notepad-plus-plus-master\scintilla\src\Document.h(285): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
> D:\MSYS\usr\src\notepad-plus-plus-master\scintilla\src\Document.h(285): error C2238: unexpected token(s) preceding ';'
> D:\MSYS\usr\src\notepad-plus-plus-master\scintilla\src\Document.h(565): error C2039: 'data': is not a member of 'Scintilla::Action'
> D:\MSYS\usr\src\notepad-plus-plus-master\scintilla\src\CellBuffer.h(32): note: see declaration of 'Scintilla::Action'
> D:\MSYS\usr\src\notepad-plus-plus-master\scintilla\src\Document.h(565): error C2228: left of '.get' must have class/struct/union
> NMAKE : fatal error U1077: 'D:\APP\VS2017\VC\Tools\MSVC\14.10.25017\bin\HostX64\x64\cl.EXE' : return code '0x2'
> Stop

Anyone kind enough guide me clarifying what actually caused this build failure and how to solve?

**Comment by xylographe** [comment]
> **`cl -Zi -TP -MP -W4 -EHsc -std:c++latest`**

Should be,
```
cl -Zi -TP -MP -W4 -EHsc -std:c++17
```

**Comment by abdulbadii** [comment]
of course i did
otherwise worst

**Comment by ArkadiuszMichalski** [comment]
Is this still actual problem?

**Comment by mere-human** [comment]
Now SciLexer is no longer built as a DLL but as a LIB. Moreover, now it's not needed to build it separately and there's no need to specify a path to Boost. Everything is built as a part of notepadPlus.sln: https://github.com/notepad-plus-plus/notepad-plus-plus/blob/master/BUILD.md
So, if one uses a right version of MSVC, there shouldn't be any problem.

**Comment by chcg** [comment]
@abdulbadii As @mere-human stated that issue should no be one any longer as the build since version 8.0 doesn't require external sources.
