### ISSUE TITLE
Read Access Violation

### ISSUE THREAD

**Issue by mikrokode** [notepad-plus-plus/notepad-plus-plus#7924]
![image](https://user-images.githubusercontent.com/26881536/74024998-f7126780-49dd-11ea-9fa9-c40e28105d56.png)

I facing this error when I building it in VS 2017 in window 10? can you help me?

**Comment by sasumner** [comment]
Maybe take this type of question to here?:
https://community.notepad-plus-plus.org/

Where you are (github issues for Notepad++) is specifically for bug reports and feature requests.
