### ISSUE TITLE
DSpellCheck.dll plugin exception when opening XML files

### ISSUE THREAD

**Issue by zachattack05** [notepad-plus-plus/notepad-plus-plus#7925]
### DSpellCheck.dll plugin exception when opening XML files

NP++ Version: 7.8.4 (64bit)
Debug Info:
Notepad++ v7.8.4   (64-bit)
Build time : Jan 29 2020 - 01:31:03
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS Name : Windows 10 Pro (64-bit) 
OS Version : 1809
OS Build : 17763.914
Plugins : DSpellCheck.dll mimeTools.dll NppConverter.dll NppExport.dll XMLTools.dll 

When opening NP++, if the last unsaved document is an XML file, I receive an immediate error that states:

Plugin Exception
An exception occurred due to plugin: DSpellCheck.dll
Exception reason: Vector<T> too long

I don't install plugins on my own, so unless it was installed when I installed NP++, I didn't add it. I did see that an old issue was closed regarding this library and it was cited as closed because DSpellCheck.dll isn't included in the installer anymore.

I've had NP++ installed for a while, and keep it updated, but I imagine that the error might be occurring because the library is still around from when it was included in the installer and it's causing errors now.

I can still use NP++, it doesn't hang, or do anything that prevents me from using it, but the error dialog appears occasionally and simply clicking "OK" just makes it go away as if nothing happened.

Attached is a screenshot of the error. The XML is blurred because it happens to contain confidential information.

If this issue is already resolved, could someone kindly tell me how I may be able to fix this?

![Notepad++Exception](https://user-images.githubusercontent.com/26329763/74062558-1e543f00-49b4-11ea-912f-814779bf36c3.png)

**Comment by sasumner** [comment]
Perhaps ask on the site that supports the DSpellCheck plugin?

**Comment by zachattack05** [comment]
> Perhaps ask on the site that supports the DSpellCheck plugin?

I didn't install the plugin, I assumed it was installed when I installed NP++.

The error seems to be occurring in NP++. If NP++ is supposed to be using a plugin that was shipped with the installer, I don't think contacting whoever created that plugin would be much help. Since I didn't install the plugin separately, on my own, I wouldn't even know what version of the plugin it is, where it's even located at, if it's important for NP++ to run, or where the plugin is even distributed from.

**Comment by sasumner** [comment]
Notepad++ doesn't ship with DSpellCheck plugin.  Suggestion to "solve" the problem:  Find the `DSpellCheck.DLL` file and delete it (Notepad++ must not be running when you do this).

**Comment by chcg** [comment]
You could create a ticket here: https://github.com/Predelnik/DSpellCheck/issues, in any case the version of the plugin for your installation is needed. Could be checked at:

![grafik](https://user-images.githubusercontent.com/12630740/74167807-13561480-4c29-11ea-8112-1efe5746b308.png)

**Comment by zachattack05** [comment]
> @zachattack05 Could you please create a ticket here: https://github.com/Predelnik/DSpellCheck/issues, if you are using the latest version of the plugin and add the version of the plugin for your installation. Could be checked at Plugins -> Plugins Admin... :
> 
> ![grafik](https://user-images.githubusercontent.com/12630740/74167807-13561480-4c29-11ea-8112-1efe5746b308.png)

I didn't even know this existed. I removed it using the Plugins Admin dialog and it appears to have fixed the problem. Thanks!
