### ISSUE TITLE
Exception thrown: read access violation. this was nullptr.

### ISSUE THREAD

**Issue by mikrokode** [notepad-plus-plus/notepad-plus-plus#7926]
HACCEL getAccTable() const{
		return _accelerator.getAccTable();
	};

	bool emergency(const generic_string& emergencySavedDir);

	Buffer* getCurrentBuffer()	{
		return _pEditView->getCurrentBuffer();
	};

	void launchDocumentBackupTask();
	int getQuoteIndexFrom(const wchar_t* quoter) const;
	void showQuoteFromIndex(int index) const;
	void showQuote(const QuoteParams* quote) const;

========================================

Above code when running notepad++, the error appeared in the Buffer* getCurrentBuffer() which shown Exception thrown: read access violation. this was nullptr. May I know how to solve?

**Comment by mikrokode** [comment]
I using Window 7 and VS 2017 Community

**Comment by abdulbadii** [comment]
Clarify and show actual sequence

**Comment by sk-zk** [comment]
See here: https://github.com/notepad-plus-plus/notepad-plus-plus/issues/5767#issuecomment-553169492
