### ISSUE TITLE
Grouping box wrapping 'In-Selection' and 'Count' is misplaced

### ISSUE THREAD

**Issue by sasumner** [notepad-plus-plus/notepad-plus-plus#7927]
### Steps to Reproduce the Issue

0. (Added post-issue creation).  Start Windows with your primary display one that is greater than 96 d.p.i.  I started mine with my laptop's screen (120 d.p.i) as my primary (and only) display.

1.  Invoke `Replace` window; note positioning of grouping box around `In selection` and `Replace All` controls:  

![image](https://user-images.githubusercontent.com/30118311/74109966-26e47b00-4b56-11ea-8de4-b534d344a6c9.png)

2.  Invoke `Find` window; note positioning of grouping box around `In selection` and `Count` controls:

![image](https://user-images.githubusercontent.com/30118311/74109967-2c41c580-4b56-11ea-8f97-37c3369ddf6c.png)

3.  Compare the results of 1 and 2 and notice that while 1 looks nice and is well-placed; 2 looks bad and is mis-aligned.  For 2, the grouping box needs to be repositioned "upward" a few pixels.

### Expected Behavior
I expect the UI to look nice in this regard. :-)

### Actual Behavior
The UI does not look nice in this regard. :-( 

### Debug Information
Notepad++ v7.8.4   (32-bit)
Build time : Jan 29 2020 - 01:33:47
Path : C:\.........\npp.7.8.4.bin\notepad++.exe
Admin mode : OFF
Local Conf mode : ON
OS Name : Windows 10 Enterprise (64-bit) 
OS Version : 1709
OS Build : 16299.1565
Plugins : mimeTools.dll NppConverter.dll NppEditorConfig.dll NppExport.dll

**Comment by donho** [comment]
Is there someone who's got the correct display on "Count" ?
If yes, what's your screen resolution?

**Comment by sasumner** [comment]
@donho Do _YOU_ have the correct display?

**Comment by donho** [comment]
I have had, but not now.
That's why I ask.

**Comment by sasumner** [comment]
I restarted my PC with my primary display at boot time set to one that is 96 d.p.i.  That results in it looking as it should:

![image](https://user-images.githubusercontent.com/30118311/74112054-839c6180-4b67-11ea-9991-9e2a7ea68d80.png)

At the time of issue creation, I had last rebooted on my laptop without any external displays attached, and my laptop screen is 120 d.p.i.

So it appears to be a d.p.i. issue?  It seems like if that group box is badly positioned due to d.p.i., then there would be more things poorly located.

Please advise, ANYONE! :-)

(Note, I revised my issue-creation entry with a "Step 0")

**Comment by sasumner** [comment]
Closing for now as it is a small thing which does no harm anyway...

**Comment by donho** [comment]
Yes, it could be DPI issue.
Let's wait & see if there are more reports about this issue.

**Comment by Uhf7** [comment]
It is an DPI issue. Around line 885 in **FindReplaceDlg.cpp**:
    `_countInSelFramePos.top = countP.y - 9;`
Working better:
    `_countInSelFramePos.top = countP.y - 10 * Dpi / 96;`
Where `Dpi = GetDeviceCaps(hdc, LOGPIXELSY);`
