### ISSUE TITLE
Change the font color of status bar message on "Find" dialog

### ISSUE THREAD

**Issue by abdulbadii** [notepad-plus-plus/notepad-plus-plus#7929]
I can hardly figure out how to change the status bar message/font color of find dialog window.
All I found was
```
void FindReplaceDlg::setStatusbarMessage(const generic_string & msg, FindStatus staus) {
 //... 
	if (isVisible()) {
		_statusbarFindStatus = staus;
		_statusBar.setOwnerDrawText(msg.c_str());
	}
     //..
```
and the above invocation leads:

```
bool StatusBar::setOwnerDrawText(const TCHAR* str)
{
	if (str != nullptr)
		_lastSetText = str;
	else
		_lastSetText.clear();

	return (::SendMessage(_hSelf, SB_SETTEXT, SBT_OWNERDRAW, reinterpret_cast<LPARAM>(_lastSetText.c_str())) == TRUE);
}

```
and honestly I barely have knowledge on `SendMessage()` usage even this give good information:
 
https://docs.microsoft.com/en-us/windows/win32/winmsg/about-messages-and-message-queues

How is actually to change the Find dialog status bar message color?
Any helpful guidance is gratified. Thanks in advance

**Comment by sasumner** [comment]
This places is for "issues", not really for "questions".
Perhaps you will have better luck if you ask here:
https://community.notepad-plus-plus.org/
