### ISSUE TITLE
Ctrl+Tab doesn't switch tabs in dialogs

### ISSUE THREAD

**Issue by phuclv90** [notepad-plus-plus/notepad-plus-plus#7932]
### Description of the Issue

In dialogs like Find/Replace, Shortcut mapper, Plugins admin, User Defined Language... when I press <kbd>Ctrl</kbd>+<kbd>Tab</kbd> then the focus just moves to the next tab stop instead of moving to the next tab in the dialog

### Steps to Reproduce the Issue

1. Open any dialogs with tabs
2. Press <kbd>Ctrl</kbd>+<kbd>Tab</kbd> or <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>Tab</kbd>

### Expected Behavior

Tabs should be switched instead of changing focus

**Comment by sasumner** [comment]
Ctrl+Tab and Ctrl+Shift+Tab seem like the appropriate keys for this behavior, given this evidence in other areas of Notepad++:

* `Preferences` > `MISC.` > `Document Switcher` actually hard-code identifies Ctrl+Tab in its groupbox caption:  `Document Switcher (Ctrl+TAB)`

* The default keycombo for `(Main menu 169) Switch to next document` is Ctrl+Tab, setting somewhat of a standard for tab navigation.  Same for `(Main menu 168) Switch to previous document` being Ctrl+Shift+Tab.

**Comment by alankilborn** [comment]
>In dialogs like Find/Replace

As of N++ 8.1.3, tabs may be switched in the Find family of windows by shortcut press for a different tab.
Reference #10019

**Comment by EinmalIM** [comment]
I would like to see the standard behavior for changing tabs by keyboard with Ctrl+Tab and Ctrl+Shift+Tab as well

**Comment by alankilborn** [comment]
>I would like to see the standard behavior for changing tabs by keyboard with Ctrl+Tab and Ctrl+Shift+Tab as well

It is a good idea, but with the implementation noted above for the Find family of windows (which works a different way), it probably makes it LESS likely that this will ever be implemented.  Plus, Ctrl+Tab is already a bit confusing, what with the "Doc Switcher" use noted above (and giving it yet another function might increase the confusion).

**Comment by EinmalIM** [comment]
I don't see increased confusion: if the main window has focus you use ctrl+(shift+)tab to switch between your open editor windows and if a tabbed dialog has focus that key combination is working on the tabs of the dialog. If the code base makes it hard to implement without breaking other stuff, OK, but I would not count user confusion as a reason to not implement the standard Windows behavior for tab switching with ctrl+tab and ctrl+shift+tab. I was confused when I realized those short cuts are not working ;-)

**Comment by alankilborn** [comment]
>If the code base makes it hard to implement without breaking other stuff, OK

I know that when I was following development of the feature to allow keyboard tab-changing in the Find window, a Ctrl+Tab implementation was rejected due to code complexity and an alternate solution was done.  For other areas (_Shortcut Mapper_, _Plugins Admin_, etc.) I don't have a feel for the difficulty.

Ctrl+Tab DOES switch editor tabs, but by default it does so in a different way than a simple switch of tab.  It does so with a yellow backgrounded popup window.  If that yellow-background window feature is disabled, THEN it works more traditionally.

Don't get me wrong, I'm agreeing with you that this functionality would be nice to have.

**Comment by CennoxX** [comment]
> In dialogs like Find/Replace, Shortcut mapper, Plugins admin, User Defined Language... when I press Ctrl+Tab then the focus just moves to the next tab stop instead of moving to the next tab in the dialog

Is it possible that this is just an undesired side effect of using tab to move the focus? So that the modifier is being ignored in this case?
