### ISSUE TITLE
charactor & disappears v7.7.1

### ISSUE THREAD

**Issue by Junyan-Wang912** [notepad-plus-plus/notepad-plus-plus#7933]
### Description of the Issue

The first & disappears when using windows automation tools like inspect.exe to get the text, other & stay visible. If using notepad to open the same file, the result is fine.
### Steps to Reproduce the Issue

1. open any .txt with notepad++
2. add & into any position
3. open inspect.exe(probably available on your machine), click on the cursor icon and the yellow rectangle icon, and move your cursor to the opened notepad++ window. you'll see the leftside of inspect.exe changed. 
4. quick move back to the cursor icon and click to stop detecting, the rightside shows the information of the notepad++ edit control， the value attritube is the text， you'll see the first '&' disappear.
5. note that this situation does not appear in other applications, is there any special handling to '&' in your realization?

**Comment by sasumner** [comment]
Your issue is not very understandable.  Can you create a screencast (e.g. animated GIF) of your sequence and post it here?

**Comment by alankilborn** [comment]
This doesn't seem like a complaint against the Notepad++ software?
Recommend CLOSURE of this item.

**Comment by ArkadiuszMichalski** [comment]
It works fine with WinSpy, that's more of a case of inspect.exe.
