### ISSUE TITLE
Json is not highlighting any color

### ISSUE THREAD

**Issue by dylanh724** [notepad-plus-plus/notepad-plus-plus#7936]
### Description of the Issue
Although represented 100x more clear here: https://github.com/notepad-plus-plus/notepad-plus-plus/issues/7934 ,

The is an ongoing, pressing issue that N++ Json "Language" color schema was left out for markdown highlighting. Color is a property of light as seen by people. "Primary colors" can be mixed to make the other colors for markdown languages, in this case. Red, yellow and blue are the three traditional primary colors used to mix to create other forms of markdown colors. The primary colors for television screens and computer monitors are red, green and blue - although other sources of color sources use magenta, yellow and cyan as their primary colors, I believe N++ uses RGB; markdown colors have a large variety of combinations that appear for other markdown colors, but not json:

![image](https://user-images.githubusercontent.com/8840024/74239314-91dab100-4d12-11ea-8f62-81d93188bd90.png)

When something has no color, it is transparent. An example is air. Such as in this case, where "Json" highlight colors are like air: They cannot be seen. All we see is black-and-white, regardless of theme: A singularity of color (or the lack of).

### Steps to Reproduce the Issue
1. Select "Json" (JavaScript Object Notation) as the code type. 
2. Use your eye's light receptors within the eye transmit messages to the brain, which produces the familiar sensations of color to perceive only the reflected colors. If you only see black and white, please forward this issue.
3. Notice a lack of color produced by both your optics and N++ markdown color.

### Expected Behavior
When light hits a json object, the object was expected to absorb some of the light and reflect the rest of it. Which wavelengths are reflected or absorbed depends on the properties of the object, but there should have been at least some splash of color that your rods and cones should have received and at least offered an illusion of color, depending on how such is perceived by the individual.

![image](https://user-images.githubusercontent.com/8840024/74239919-d1ee6380-4d13-11ea-8e4f-4513b11b7eb1.png)

### Actual Behavior
The difference in how one or more of the light-sensitive cells found in the retina of the eye respond to certain colors. In this case, either no colors in the markdown were applied or the cells (cones) lacked sensing such wavelengths of light, disabling the retina to distinguish between colors. However, there is a greater chance that the markdown dev simply did not add color options compared to others.

![image](https://user-images.githubusercontent.com/8840024/74239437-cbabb780-4d12-11ea-99be-b26570bac029.png)

### Debug Information
Notepad++ v7.8.4   (32-bit)
Build time : Jan 29 2020 - 01:33:47
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OCD Dev: [True](https://github.com/notepad-plus-plus/notepad-plus-plus/issues/7934)
OS Name : Windows 10 Enterprise (64-bit) 
OS Version : 1909
OS Build : 18363.592
Plugins : mimeTools.dll NppConverter.dll NppExport.dll

**Comment by Ekopalypse** [comment]
Can you try a [zipped version](https://github.com/notepad-plus-plus/notepad-plus-plus/releases/download/v7.8.4/npp.7.8.4.bin.x64.zip) to see if this is some kind of corrupted configuration issue?

![image](https://user-images.githubusercontent.com/47723516/74240279-e7469c00-4cd9-11ea-8ca1-134b79fe480e.png)

**Comment by dylanh724** [comment]
The zip one worked fine -- Can you tell me if your installed version has the same issue? Then try swapping predefined themes and see if it works?

Here is back to my installed version with the theme returned (minus background/foreground, unless foreground swap messed up highlighting?):

![image](https://user-images.githubusercontent.com/8840024/74240865-c0a65680-4d15-11ea-9233-b9e290fa4b66.png)

**Comment by Ekopalypse** [comment]
Yes, an installed version work as well, switching to another theme and back didn't affect functionality.

![image](https://user-images.githubusercontent.com/47723516/74245863-fa5e6980-4ce3-11ea-8594-9551149fb4bc.png)

As you see, even errors are highlighted.
I **ASSUME** that your configuration file got corrupted.
What you could try, close npp, goto %APPDATA% and rename, temporarily notepad++ directory.
Start npp and a new notepad++ directory should be created. Depending on your customization
you might copy over the different xml files from the renamed directory.

**Comment by dylanh724** [comment]
> I ASSUME that your configuration file got corrupted.
Yep, seems to have been `stylers.xml` causing corruption.

For anyone curious: https://pastebin.com/mCLhL3Wr

**Comment by sasumner** [comment]
Unless I'm missing something, I'm not sure how the description of how color is perceived is all that important to the issue of color being absent from the JSON data.  

When reporting bugs it is best to distill the issue down to only the subset of information needed to look into the issue; adding extra info probably just slows down the analysis.

**Comment by dylanh724** [comment]
> Unless I'm missing something, I'm not sure how the description of how color is perceived is all that important to the issue of color being absent from the JSON data.
You are absolutely right, you conflicting fellow.

**Comment by sasumner** [comment]
Confused.  :-(

**Comment by dylanh724** [comment]
> Confused. :-(

Just referencing inconsistency (or hypocrisy, depending on perspective), @sasumner : https://github.com/notepad-plus-plus/notepad-plus-plus/issues/7934

**Comment by lokpro** [comment]
This is an old issues. Google took me here.

Many of the styles do not contain definition for JSON.
Only the default stylers.model.xml and, count from search, four other styles has JSON.
https://github.com/notepad-plus-plus/notepad-plus-plus/search?q=%3CLexerType+name%3D%22json%22

There are a _Default_ and a _DarkModeDefault_ styles. Can we make the missing Langauges fallback to the default?
