### ISSUE TITLE
All text removed automatically after PC shutdown

### ISSUE THREAD

**Issue by Abraham313** [notepad-plus-plus/notepad-plus-plus#7940]
I have installed windows 7(ultimate 64-bit) in VMWare and installed notepad++ and  sublime text also But when I shutdown my Vmare installed windows 7 after my works.It removed all my unsaved text also close saved data But in my Real machine in windows 10 it's Ok.On the other hand sublime text never remove or close any of my saved or unsaved  data.
Please fix this I love Notepad++ and want to use this forever
thanks

**Comment by donho** [comment]
Please post your Debug Info. Otherwise, it'll be closed.

**Comment by naveento** [comment]
![image](https://user-images.githubusercontent.com/30177043/75476837-505c2e00-59c1-11ea-8555-abac9c5755fc.png)

Verify your settings from preferences>backup as shown in attached

**Comment by sasumner** [comment]
Closing as promised 2 weeks ago.
