### ISSUE TITLE
Unclear search dialog (forward/backwards navigation in results)

### ISSUE THREAD

**Issue by Chealer** [notepad-plus-plus/notepad-plus-plus#7941]
# Description of the Issue
The Search dialog is quite unclear for the navigation in results zone. At the top right is a "Next" button, but I had difficulty finding a way to go back to the previous result. Looking carefully at the fields, I wondered if the display was broken in my environment. Eventually, I noticed that an unlabelled checkbox to the right of the Next button (which can be seen in the screenshot below) causes a second navigation button to appear. This second button appears to the left of Next and has no label, but allows to go back to the previous result.

![Notepad++ search](https://user-images.githubusercontent.com/486141/74464106-f572f480-4e60-11ea-8a06-57b44150e13c.PNG)

The checkbox has a "2 button Search" tooltip, but even that is not clear ("Display button for previous" would be clearer).

I may not understand the current design's philosophy, but from what I can see, this could be solved by simply displaying the button for previous unconditionally, since at least in French, the word "Suivant" easily fits the button's width even at reduced size, so that displaying both buttons does not require extra space. In fact, in French, the checkbox makes the dialog wider than it needs to be.

This affects Notepad 7.8.4 (on Windows 8).

**Comment by sasumner** [comment]
So, one answer to this is that software (including Notepad++) is somewhat bound to its history.  The "2 button mode" is rather new; before we only had "1 button mode" (although it wasn't called that) and its single button was the "Find Next" one.  To do a "find previous", one had to tick the "Backward direction" checkbox -- it is there in your screenshot -- before pressing "Find Next".  Thus, the "next" search would be in the backward direction (i.e. the previous match).

>This second button appears to the left of Next and has no label

Doesn't it have an upward triangle in it, implying that by pressing it something would happen "upward" ("previous") in a document?

>the checkbox makes the dialog wider than it needs to be.

Not following what this means...

As an aside, the dialog is realizable to be wider, but it has a minimum width (which you are probably at if you haven't altered it wider).

So I'm closing this issue, but we can continue discussing it here if you'd like further clarification.

**Comment by xylographe** [comment]
I prefer the slightly older version, where forward/backward search/replace buttons have the same size, but no text:
![NppFindReplace](https://user-images.githubusercontent.com/8535293/74494952-b97a7680-4ed6-11ea-958b-0f0fcbce37e5.png)

**Comment by sasumner** [comment]
Nobody liked my "friends" version :-(
https://community.notepad-plus-plus.org/topic/14372/the-find-button-has-returned-sort-of-and-has-brought-friends

![image](https://user-images.githubusercontent.com/30118311/74496033-7fde4700-4ea7-11ea-9077-13a7ece914ce.png)

It has seemed to go thru a few iterations; even the direction as a discrete control: began as a radio button, switched to checkbox, then somewhat neutered by 2 button find mode...

**Comment by Chealer** [comment]
Hi @sasumner, 

> So, one answer to this is that software (including Notepad++) is somewhat bound to its history. The "2 button mode" is rather new; before we only had "1 button mode" (although it wasn't called that) and its single button was the "Find Next" one. To do a "find previous", one had to tick the "Backward direction" checkbox -- it is there in your screenshot -- before pressing "Find Next". Thus, the "next" search would be in the backward direction (i.e. the previous match).

Thank you very much for this detailed explanation and for your other comment. However, I do not understand what you mean by Notepad++ being bound to its history. In fact, one alternative design which would address this was already used in Notepad++'s _Replace_ tab according to your last comment.
 
> > This second button appears to the left of Next and has no label
> 
> Doesn't it have an upward triangle in it, implying that by pressing it something would happen "upward" ("previous") in a document?

Yes. Sorry, English is not my native language, I did not think an image could be considered as a label.

> > the checkbox makes the dialog wider than it needs to be.
> 
> Not following what this means...

I mean that often, a checkbox can control whether advanced form elements display or not, in order to make the form appear simpler or more compact by default. At first sight this checkbox may seem designed to keep the dialog more compact, but in reality, as it is alone in its (otherwise empty) "column", it increases the dialog's width by the checkbox's width, so the effect is opposite.

> [...]
> 
> So I'm closing this issue, but we can continue discussing it here if you'd like further clarification.

Why? I certainly would (like - I guess - anyone who hasn't used a Notepad++ version featuring the current design before).

**Comment by sasumner** [comment]
>....Notepad++ being bound to its history

This means that tens of thousands (hundreds of thousands?) of users are used to the way Notepad++ 's user interface currently is, and to ask them to adapt to something redesigned, even if the redesign is arguably better, is not reasonable.

**Comment by Chealer** [comment]
> > ....Notepad++ being bound to its history
> 
> This means that tens of thousands (hundreds of thousands?) of users are used to the way Notepad++ 's user interface currently is, and to ask them to adapt to something redesigned, even if the redesign is arguably better, is not reasonable.

What makes adaptation difficult is when the new situation is nonintuitive. There will be no problem changing to an intuitive design, in particular if a less clear version of that design was already used, as long as this is done at a proper time (i.e. not in a minor release). If you are really concerned about transition, nothing prevents from providing a preference.

Sorry to insist @sasumner but why did you close this ticket?

**Comment by sasumner** [comment]
>Sorry to insist ... but why did you close this ticket?

I closed it because nothing is going to be changed in the Notepad++ software because of it.

**Comment by Chealer** [comment]
@sasumner you are free to think so, but one's failure to see a solution does not solve an issue.

**Comment by Chealer** [comment]
This persists in 7.9.1. Please reopen this ticket @sasumner ; I cannot do that myself.

**Comment by sasumner** [comment]
It's not going to be reopened; sorry.
See https://github.com/notepad-plus-plus/notepad-plus-plus/issues/7941#issuecomment-673534958

**Comment by Chealer** [comment]
> 
> 
> It's not going to be reopened; sorry.
> See [#7941 (comment)](https://github.com/notepad-plus-plus/notepad-plus-plus/issues/7941#issuecomment-673534958)

I already saw that comment @sasumner . In fact, I already [replied to it](https://github.com/notepad-plus-plus/notepad-plus-plus/issues/7941#issuecomment-673698059). Closing a ticket means that the reported issue is solved; it does not merely express that someone chose not to fix it.

**Comment by sasumner** [comment]
> In fact, I already "replied to it."

Ha.  Good one.  Not very original, but good nonetheless.  :-)

>Closing a ticket means that the reported issue is solved

People sometimes get the idea that just because they think something is an "issue", that developers are under some obligation to "fix" it.
Some people go as far as to open new issues when their old ones get closed, on the same exact topic.  But please don't do that. 

That's the end, there will be no more responses by the Notepad++ development team in this thread.

**Comment by donho** [comment]
@Chealer 
Do you understand now for what the checkbox and 2 buttons are there?

**Comment by Chealer** [comment]
> 
> 
> > In fact, I already "replied to it."
> 
> Ha. Good one. Not very original, but good nonetheless. :-)

Thanks
 
> > Closing a ticket means that the reported issue is solved
> 
> People sometimes get the idea that just because they think something is an "issue", that developers are under some obligation to "fix" it.

I would appreciate if we could stick to the topic.

> Some people go as far as to open new issues when their old ones get closed, on the same exact topic. But please don't do that.
> 
> That's the end, there will be no more responses by the Notepad++ development team in this thread.

Nobody is asking for a "response" in this thread. It might help to understand even better the changes which occurred, but you already explained a lot. All I asked is to set this ticket back to open status (until the issue is addressed).

**Comment by Chealer** [comment]
Hi @donho ,

> 
> @Chealer
> Do you understand now for what the checkbox and 2 buttons are there?

Thank you. I do understand their usage.

Now if you mean **why** the current design is in place, I had understood a good part of what @sasumner wrote but I must admit I had not fully studied the matter. 

When sasumner wrote...

> Nobody liked my "friends" version :-(

...I thought he meant that his proposal was rejected. But now that you make me revisit it with more attention, I think what he meant is just nobody (or very few people) expressed appreciation for the version he proposed. As his proposal was not fully implemented, that did not encourage him to finish the job.

**Comment by Chealer** [comment]
So to recap, I think we can say the Find/Replace dialog had several versions:

1. Some where backwards search is enabled by a dedicated "<< Find" (Find previous) button which always displays
    1. One variant where the only button for backwards is for searching
    1. And one variant with 3 buttons for backwards (Find, Replace and Replace all)
1. And one version where the "<< Find" button's display is controlled by the funny checkbox which is the topic of this report

I am not very knowledgeable about Notepad++ and I did not try previous versions, but my understanding based on above discussion is that:

1. Notepad++ currently uses version 2.
2. At some point in its history, it went from version 2 to 1.i.
3. This was reverted in version 7.5 (2017).
4. @sasumner mostly implemented 1.ii in 2017 and requested feedback, but the change was never finished nor integrated.

Now, I meant to reply in sasumner's thread about his proposal, but as it was locked, I am providing my feedback here.

I do not know if 1.ii was actually disliked, but if so, one reason may have been the 2 "Replace all" buttons. I did not test the build, but **I assume** that "<< Repl All" meant "Replace all previous" and that "Repl All >>" meant "Replace all following". I see 3 issues with that:

- Splitting this button means adding yet another button to that dialog. I did not fully study the Find/Replace dialog, and suppose it must be particularly powerful, but one sure thing is the number of elements is large. Adding more elements makes it even more confusing or time-consuming to learn.
- While the effect of "<< Find" and "Find >>" may not be perfectly clear, the effect of "<< Repl All" is at the very least less clear (and - quite arguably - misleading). Even if the context makes each button's role quite clear, if analyzed independently, one would surely think that a button labelled "Replace all" would replace _all_ occurrences.
- This removes the possibility of doing a real (full) Replace all with a single step.

...which is why I think a variant which would be a compromise between 1.i and 1.ii (let's call it 1.iii) may get a better reception. I recommend to try with "<< Find" and "Find >>" buttons as well as "<< Replace" and "Replace >>" buttons, **but a single "Replace all"** button.

I should note that this does not prevent offering the functionalities of "<<Repl All" and "Repl All >>" if some people truly see a use for them. I am not the heaviest user of text editors, but I have been using them for more than a decade, and I do not **remember** ever missing such functions. But depending of the graphical toolkit Notepad++ uses, it is probably possible to use advanced buttons with alternative behaviors. There could be a single "Replace all" button, but which would optionally offer _Replace all previous_ and _Replace all following_. If you don't have in mind what I mean, you can see examples of such advanced buttons in WinSCP's Login dialog (the _Login_ button) and TortoiseGit's commit dialog (the _Commit_ button).
