### ISSUE TITLE
New "Save changes" dialog doesn't accept key inputs

### ISSUE THREAD

**Issue by ygoe** [notepad-plus-plus/notepad-plus-plus#7942]
### Description of the Issue
The new "Save changes?" confirmation dialog that appears when closing a document with unsaved changes has more and custom buttons than the usual Windows MessageBox or TaskDialog. MessageBoxes can be operated by pressing the accelerator key, like simply pressing <kbd>N</kbd> to answer "No". This doesn't work with this rebuilt custom dialog (that also looks like from the 90s but that's the spirit of NPP I guess; at least it still works on Windows 2000 without changes, that's important).

### Steps to Reproduce the Issue
1. Create a new text document
2. Enter some text
3. Close the document (e.g. by pressing Ctrl+W)
4. Press the <kbd>N</kbd> key on the keyboard

### Expected Behavior
Document closes without saving

### Actual Behavior
Nothing, the dialog remains open

### Debug Information
Notepad++ v7.8.1   (32-bit)
Build time : Oct 27 2019 - 22:46:07
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS Name : Windows 10 Enterprise (64-bit) 
OS Version : 1803
OS Build : 17134.1246
Plugins : CustomizeToolbar.dll mimeTools.dll NppConverter.dll NppExport.dll NppSaveAsAdmin.dll

**Comment by sasumner** [comment]
Update your Notepad++ version (7.8.4 current as of this writing) or follow the advice in #6223 comment section to make things work for your earlier version (if you have some reason for wanting to stick with the version you cited).
