### ISSUE TITLE
Build fails with Visual Studio 2019

### ISSUE THREAD

**Issue by Margen67** [notepad-plus-plus/notepad-plus-plus#7944]
### Description of the Issue
Build fails due to a warning being treated as an error.
```
1>C:\Users\Margen67\Documents\GitHub\notepad-plus-plus\PowerEditor\src\NppCommands.cpp(465,5): error C2220: the following warning is treated as an error
1>C:\Users\Margen67\Documents\GitHub\notepad-plus-plus\PowerEditor\src\NppCommands.cpp(465,5): warning C4834: discarding return value of function with 'nodiscard' attribute
```
Line it's referencing: https://github.com/notepad-plus-plus/notepad-plus-plus/blob/master/PowerEditor/src/NppCommands.cpp#L465

Disabling `Treat Warnings As Errors` produces a seemingly functional build, but obviously is a workaround.

### Steps to Reproduce the Issue
1. Open [PowerEditor\visual.net\notepadPlus.vcxproj](https://github.com/notepad-plus-plus/notepad-plus-plus/blob/master/BUILD.md#to-build-notepadexe)
2. Build
3. Error

### Expected Behavior
Build completes successfuly.

### Actual Behavior
Build fails due to a warning being treated as an error.

### Debug Information
N/A

**Comment by sasumner** [comment]
`Debug Information` IS important; in this case it should be what version of Notepad++ you are attempting to build.  Moving ahead with assumption it is 7.8.4 which is current as of this writing.

Current Build instruction as of this writing references VS2017 not 2019.  The reference is rather obscure but it is there; it could be made more prominent.  If/when VS2019 becomes the standard tool for building, the build instruction will be changed and the warnings fixed so that a clean build results.

**Comment by Margen67** [comment]
@sasumner I was using latest master.
Why not fix it so VS2017 doesn't have to be used?

**Comment by CookiePLMonster** [comment]
This is a perfectly valid warning to display, so I don't understand why (as always) it has to wait until things break for real instead of fixing it pre-emptively. But whatever floats your boat, I guess.

**Comment by sasumner** [comment]
>latest master

which doesn't mean a whole lot if someone reads this at some future point, without some legwork to figure out what it means; just sayin.

>why (as always) it has to wait

Perhaps the answer is primary-dev @donho, who would be the one to fix it, has limited time?
Don't know; I'm not privy to all of the thought-processes...

If primary-dev wants to reopen this, he will.

**Comment by CookiePLMonster** [comment]
> Perhaps the answer is primary-dev @donho, who would be the one to fix it, has limited time?

Who doesn't? That is exactly the reason not to ignore such issues now and jump on them ahead of the curve when there is an opportunity.

**Comment by AngryGamer** [comment]
This is issue is ironic due to #7565

**Comment by AngryGamer** [comment]
It's all the more ironic due to #7565

**Comment by AngryGamer** [comment]
This is all the more ironic due to #7565

**Comment by CookiePLMonster** [comment]
> This is all the more ironic due to #7565

It's okay, consistency is overrated ¯\\\_(ツ)\_/¯

**Comment by sasumner** [comment]
I don't understand the "irony".

**Comment by Margen67** [comment]
@sasumner This is a valid issue. Can you reopen it?
