### ISSUE TITLE
Feature Request: Diff edit buffer with file

### ISSUE THREAD

**Issue by ronww** [notepad-plus-plus/notepad-plus-plus#7945]
### Description of the Issue
Feature Request: In the File menu, there is already a "Reload from disk". Please add a "Diff with disk" operation. When selected, it would display the differences between what's currently loaded in Notepad++ with the corresponding file on disk.

### Steps to Reproduce the Issue
n/a

### Expected Behavior
When selected, it would display the differences between what's currently loaded in Notepad++ with the corresponding file on disk.

### Actual Behavior
n/a

### Debug Information
n/a

**Comment by sasumner** [comment]
The `Compare` plugin has such a feature.
