### ISSUE TITLE
Sound after an unsuccessful search cannot be disabled

### ISSUE THREAD

**Issue by jpvanleeuwen** [notepad-plus-plus/notepad-plus-plus#7950]
### Description of the Issue
After doing an unsuccessful search, the system 'wrong!' error bell is played which I find very annoying but I cannot find a way to disable it. Disabling all sounds or the system error sound in the OS is not a solution because in other cases I do want to hear the error bell, just not after an unsuccessful search  (why would it be an error anyway?)

### Steps to Reproduce the Issue
Search for word that is not in a text file

### Expected Behavior
I would expect to be able to disable the system error bell after an unsuccessful search somewhere in the settings

### Actual Behavior
The system error bell after an unsuccessful search cannot be disabled.

The help file says:
https://npp-user-manual.org/docs/searching/
In addition, the system error bell will sound if a Find Next or Replace action results in the Find what text not being encountered; the bell cannot be disabled.

A similar issue is #2049
where MetaChuh commented on Apr 24, 2019
"please update your notepad++ to the latest version Notepad++ 7.6.6 and migrate or reinstall your plugins if you update from version 7.5.9 or below.
if your issue still persists, and it is still of relevance to you, please feel free to file a new issue as easy to understand and reproducible as possible.
thank you for your help and best regards."

But I have a even newer version and I cannot disable the annoying error bell.

### Debug Information
Notepad++ v7.8.4   (64-bit)
Build time : Jan 29 2020 - 01:31:03
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS Name : Windows 10 Home (64-bit) 
OS Version : 1903
OS Build : 18362.657
Plugins : DSpellCheck.dll mimeTools.dll NppConverter.dll NppExport.dll

**Comment by sasumner** [comment]
This seems a reasonable request to me; I will look into it...

**Comment by sasumner** [comment]
>I would expect to be able to disable the system error bell after an unsuccessful search somewhere in the settings

After a code change, it can be done in the Windows 10 "Volume Mixer" by muting the app:

![image](https://user-images.githubusercontent.com/30118311/74597885-a382c800-5034-11ea-857a-ba3c8bb17138.png)

To get to the "Volume Mixer", right-click on the "speaker" icon in the system try, and choose "Open Volume Mixer":

![image](https://user-images.githubusercontent.com/30118311/74597907-07a58c00-5035-11ea-9dea-dfb1e541e807.png)


Using this method to disable and enable Notepad++ sounds eliminates the need to have a specific preference setting in Notepad++.  Windows itself will remember the setting last used.

**Comment by sasumner** [comment]
Created PR for documentation update for this:  https://github.com/notepad-plus-plus/npp-usermanual/pull/75

**Comment by jpvanleeuwen** [comment]
Just installed v7.8.5 and it works like a charm. Thank you for the quick and effective response! Donated $5 for your trouble.

**Comment by sasumner** [comment]
>Donated $5 for your trouble.

@dohno Please forward the $5.  LOL.

**Comment by powertrio77** [comment]
Can you explain how to fix this again? I have the blip-poke noise, every time I Find Next, unsuccessfully. I have never seen it appear in my Windows Volume mixer, like your screen shot, even if I force it, CTRL F jhskjnlcjdnscnn. I am running 7.8.5. Thanks. Currently I disabled Applications,System Sounds, and the blip-pop sound is muted/gone. But I think now all other windows sounds are gone too.

**Comment by jpvanleeuwen** [comment]
Well that is strange.... 
On my system Notepad also does not appear in the volume mixer anymore.
I do not hear the error sound on unsuccessful search anymore since I had muted notepad in the volume mixer when it was still visible and I guess that setting is saved somewhere but after I got an email with your question I opened the volume mixer again and the notepad app is not to be found there anymore.  That is strange since I have not updated Notepad or anything..

Notepad++ v7.8.5   (64-bit)
Build time : Mar  4 2020 - 11:08:34
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS Name : Windows 10 Home (64-bit) 
OS Version : 1903
OS Build : 18362.778
Plugins : DSpellCheck.dll mimeTools.dll NppConverter.dll NppExport.dll

**Comment by jpvanleeuwen** [comment]
After updating tot 7.8.6 still no Notepad in volume mixer..

Notepad++ v7.8.6   (64-bit)
Build time : Apr 21 2020 - 15:23:03
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS Name : Windows 10 Home (64-bit) 
OS Version : 1903
OS Build : 18362.778
Plugins : DSpellCheck.dll mimeTools.dll NppConverter.dll NppExport.dll

**Comment by jpvanleeuwen** [comment]
This is a knows issue, see https://github.com/notepad-plus-plus/npp-usermanual/pull/75

**Comment by jpvanleeuwen** [comment]
> Can you explain how to fix this again? I have the blip-poke noise, every time I Find Next, unsuccessfully. I have never seen it appear in my Windows Volume mixer, like your screen shot, even if I force it, CTRL F jhskjnlcjdnscnn. I am running 7.8.5. Thanks. Currently I disabled Applications,System Sounds, and the blip-pop sound is muted/gone. But I think now all other windows sounds are gone too.

On my system the notepad app still appears in the volume mixer after an unsuccessful search. I cannot explain why on your system it does not. That the Notepad app only appears in the volume mixer after an unsuccessful search is imho questionable, as debated in https://github.com/notepad-plus-plus/npp-usermanual/pull/75

**Comment by Rimhollow** [comment]
I've just started having this problem after a recent update. I've never gotten "find-failed" beeps from Notepad++ before.

It never appears in the volume mixer, even during/after Notepad++'s beep. In any case I have all Windows sounds disabled already except for mail notifications (which play a different beep), so it shouldn't be playing anything at all.

**Comment by tanyapeters** [comment]
The problem is if you have the "Asterisk" sound in Windows Sound set to **None**, Notepad++ plays this awful short beep - which isn't long enough for NPP to register in the volume mixer.  

If you change the sound so it long enough to show up in the Volume Mixer - great, NPP is muted, but then any other Windows Applications that use that sound are now squawking.  Mute NPP, change 'Asterisk' back to **None**, and then next time NPP goes to beep... it comes through again, because volume mixer has apparently de-registered NPP.  

I'll be rolling back to 7.8.4 because this isn't a solution, and the beep drives me nuts - seems like you should either have your own setting in either NPP or Windows Sounds, or actually honor the users 'Asterisk' setting, including if it is set to **NONE**.

**Comment by menees** [comment]
I 100% agree with @tanyapeters. I have all my system sounds set to None, but NPP still beeps and never shows up in the Volume Mixer. I'm running the 32-bit build of 7.8.6 on Windows 10 1909. I'm going back to 7.8.4 now.

**Comment by Tapter** [comment]
This does not work! I've also disabled **all** sounds in the system settings (Asterisk and all are set to none) and Notepad still beeps. Also it doesn't show in the mixer (probably because the beep is too short??), so all these workarounds do not work and NP is really doing something wrong. It's the only app I have that actually beeps even though all system sounds are disabled!
Please reopen and fix

**Comment by msdrigg** [comment]
I also agree with @tanyapeters. I have the same issue. I would consider the problem fixed if Notepad++ added a "Mute all" button in settings, or just honored any windows sounds that were set to "None" if windows users go to the trouble of turning these sounds off, then they probably know what theyre doing.

**Comment by ahahu** [comment]
Same issue here, there is no Notepad++ in the sound mixer.
But especially odd is, that on the unsuccessful search suddenly the main volume control pops up and the volume is increased to 100. That's the volume control, which is also shown when you use the hardware volume +/- buttons of your notebook. What's going on there?

**Comment by dev-101** [comment]
I also noticed this, running latest 7.8.7 (32-bit) and app is not showing in the mixer. It should be reopened for additional investigation. Thanks.

**Comment by inmotion-it-support** [comment]
Still getting beep on unsuccessful search. Still no Notepad++ in the volume mixer. Even after beep still not in the volume mixer. Even ran as administrator and still not in the volume mixer.

**Comment by DougMelvin** [comment]
There recommended fix does not work. There is no N++ in the volume mixer. 
Why so much resistance to just allowing a disable option? 
I have all system sounds turned off. I should not have to deal with BEEPs when I have turned BEEPs off in windows directly. It is jarring, disruptive and unnecessary.  
Please allow us to turn the BEEPs off. 
Thank you.

**Comment by jpvanleeuwen** [comment]
@DoubMelvin
I agree with your wish for a disable option in some settings screen but for
your problem now: could it be that since you disabled the system sounds
that N++ does not show up in de volume mixer?
Could you try to enable the system sounds again and then do an
unsuccessful search in N++ and then check if N++ shows up in the volume
mixer? As a workaround for now that is.
regards

**Comment by schittli** [comment]
Why is this issue closed?
Must we create a new Issue, so that npp allows us to enable / disable playing sounds in its settings?

As others have noted, the Windows Volume Mixer does not always allow to mute Notepad++ :-(

Thanks a lot, kind regards,
Thomas

**Comment by hahoyer** [comment]
What about just removing that "feature" completely?

**Comment by donho** [comment]
@sasumner 
> @dohno Please forward the $5. LOL.

Oups! just read it. :D 
Pass your paypal email please. Or let me know while you passing in Paris - I will buy you 1 glasses of beer (or wine if you prefer). :)

**Comment by sasumner** [comment]
@donho (+@guy038) Getting a vision of 3 old men in a Paris cafe , struggling to puzzle out how regular expressions really work in Notepad++, while drinking...  It would be good, but I am currently (and usually) 7300km away.  Guy, however, is reasonably close to Paris, so please buy him MY beer, but be sure to let him know he is drinking MY beer.

**Comment by donho** [comment]
@guy038
So let's drink Scott's beer together after this f**king epidemic!

**Comment by Codingale** [comment]
So I really do not like this change I just updated today and it is so annoying.
![Sounds image](https://i.imgur.com/Csf5SfD.png)

I have ALL sounds disable except one for Visual Studio when a breakpoint is hit so a few things to note. 

- All sounds being disabled should be respected; it is not.
- Default device /w volume should be respected for some ungodly reason it's 20x times the sound of the normal system sounds.
- Responding with "just use windows to mute it" isn't a solution when the sound playing hangs the tread until it completes (from what I can tell)

All of the "cheers" for something like using the Windows Volume mixer is confusing; and and adding a setting into NP++ shouldn't be hard to implement.

![Image showing that there's a settings page in the preferences already.](https://i.imgur.com/OrcL674.png)
There's already a `Searching` settings after all.

**Comment by dashesy** [comment]
> All sounds being disabled should be respected; it is not.

The beep is extra annoying if you have a headset!

**Comment by MaedhrosTheTall** [comment]
Why this carbage thing still exists after 1 year of complaints. I cannot even mute notepad in volume mixer. I changed asterisk sound, who knows where other places this now starts playing asterisk sound.
Looks like some alpha version 0.1 stuff to me.

**Comment by ArkadiuszMichalski** [comment]
>dashesy 
>The beep is extra annoying if you have a headset!

Indeed, more and more often I have to work remotely in a headset.

**Comment by dashesy** [comment]
> I changed asterisk sound

That does not help either. I have set it to (None) and still hear the beep

![image](https://user-images.githubusercontent.com/873905/108122391-10220f80-7059-11eb-99d0-83b0c73d57dc.png)

**Comment by dev-101** [comment]
I don't have this issue anymore, think it was fixed long time ago. If it helps, here's my sound setup, Apps are set to 0 in Mixer (this doesn't affect Notepad++ apparently), and Windows sounds are disabled. Tested on multiple Win 10 machines and all is good. Not sure why some still have this issue, though.

![Notepad++ Sound](https://user-images.githubusercontent.com/5383059/108123631-741ef500-70a6-11eb-94d2-e707ca3ec10e.png)

**Comment by dashesy** [comment]
> Apps are set to 0 in Mixer (this doesn't affect Notepad++ apparently)

Actually that helped muting the annoying noise! I have latest Windows version (may be related)
![image](https://user-images.githubusercontent.com/873905/108127237-d274b500-705f-11eb-9b5d-07e33cc8d355.png)

Muting all apps in Mixer is like a big hammer! Notepad++ should respect setting of "Asterisk"

**Comment by dev-101** [comment]
~~Hmm, I raised volume of System / Applications in Mixer to 15 as a quick test before posting above, and didn't hear any sound after search, that's why I concluded it does not affect it, but still posted it as a possible workaround. It will not mute all apps, just generic ones and system apps in my opinion, all regular apps create their own mixer instance, so that's generally not a problem at all. I am annoyed by Win sounds, anyway, so this is first thing I do on a fresh system.~~

(I was about to post above, but decided to perform some additional tests - read below)

Ok, I reproduced it! Yes, the problem is still present! But, over the past year I switched from "Find / Find next" search mode to "Find All In Current Document" mode, which is not affected by the sound issue. And, yes, muting Sys / Apps Mixer or setting slider to 0 will solve this problem, too. Sorry about false claim that this is fixed.

**Comment by dev-101** [comment]
Anyway, muting Sys / Apps in Mixer will not affect apps that create new Mixer channel instance, but it will affect those who use System Sounds API.

**Comment by MaedhrosTheTall** [comment]
I just changed Asterisk sound to something more tolerable. Setting it to None, makes this bad beep. Notepad++ does not appear in my mixer (does mixer even remember volume after restart?)
One solution could be to have .wav faile with silence or something :) and changing Asterisk sound to it. 
Setting Asterisk from 'none' to 'some mild sound' makes it start to appear elsewhere in windows aswell.

**Comment by mere-human** [comment]
> Notepad++ does not appear in my mixer (does mixer even remember volume after restart?)

For me, it had appeared in mixer after it made a sound.
Lets hope #9507 gets approved.

**Comment by dev-101** [comment]
Got it to appear in the Mixer!

You must choose **Windows Default** scheme in the Sounds option, then try to trigger sound in Notepad++ (unsuccessful search) and N++ will appear in Mixer! Then you may lower the slider or mute it in the Mixer.

Strange, it won't appear if you use No sounds scheme (or 'modified' version of it. Yes, Windows Mixer remembers values even after restart or fresh boot.

![Notepad++ Search Sound Issue - Mixer](https://user-images.githubusercontent.com/5383059/108190529-55564800-7112-11eb-9b3b-db661f4ebb82.png)

**Comment by Codingale** [comment]
> > Notepad++ does not appear in my mixer (does mixer even remember volume after restart?)
> 
> For me, it had appeared in mixer after it made a sound.
> Lets hope #9507 gets approved.

Indeed these "fixes" aren't fixes and for me it still doesn't obey the Asterisk sound. I'm on the pre-beta test flight for `21H1` and it's not working.

**Comment by zahra21** [comment]
hello.
today, i discovered this issue and wanted to mentioned my attitude.
i know when i search for some words, i hear a sound which i did not know what is this sound before i discover this issue on notepad++ news page!
i believe that on the contrary, its very great and helpful for blind and screen reader user like myself.
what is the first version that notepad++ has sound for the first time?
i love it and i appreciate it.
the sound is beautiful and i like it really!

**Comment by Codingale** [comment]
> i discover this issue on notepad++ news page!
> i believe that on the contrary, its very great and helpful for blind and screen reader user like myself.

Hi, the option is ON by default. This allows users to disable it if they don't want to hear it.

**Comment by misternopps** [comment]
Just a note that you can just mute all n++ sounds under settings menu->preferences->misc
![image](https://user-images.githubusercontent.com/6700523/135546156-a095b278-e44d-453e-bfc9-4aec5a28c592.png)

**Comment by Codingale** [comment]
You can now do this yes, that's what https://github.com/notepad-plus-plus/notepad-plus-plus/pull/9507 was for. All good now :) it's even documented now too: [npp-usermanual#161](https://github.com/notepad-plus-plus/npp-usermanual/pull/161)
