### ISSUE TITLE
automatically adjust indention

### ISSUE THREAD

**Issue by calioptrix** [notepad-plus-plus/notepad-plus-plus#796]
when pasting an entire line or lines of code, it would be nice to have the indent spacing automatically adjusted. For example, if I copy lines that are indented eight spaces, then paste them into an area that is only indented two spaces, it should remove six spaces from the beginning of each of the lines. If I do a copy/paste in the opposite direction, it would add six spaces to the lines.

**Comment by VVelda** [comment]
I think it's impossible. How would you determine indentation size? It is 1×8, 2×4, 4×2, or even 8×1? You should indent with tabs – that will fix your problems.

**Comment by calioptrix** [comment]
If I copy line 1, 2, and 3 from function a (indented once) to the if statement in function b (which would be indented three times), there's no reason it can't add two extra levels of indentation, regardless of using spaces or tabs. To determine the level should be, just look at the code above the cursor.

```javascript
function a
{
  line 1
  line 2
  line 3
}

function b
{
  for
  {
    if ()
    {
      paste here
    }
  }

}

`

**Comment by VVelda** [comment]
Sorry, I haven't undestood what you mean. Agree.

**Comment by MetaChuh** [comment]
we are closing this issue due to its age and multiple newer notepad++ versions since it was filed.

please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html).
if your issue persists, and it is still of relevance to you, please feel free to file a new issue.

thank you for your help and best regards.

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
```
[<kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd>](https://notepad-plus-plus.org/community/)

**Comment by Storms-Engineering** [comment]
I actually have this issue still in Notepad

I have this empty function:
```
	public function area_report()
	{
		throw new Exception("Area report currently doesn't work");
		
	}
```
and I paste this code into it below the ```throw new exception``` line:
```
if (isset($_GET['area']) && $_GET["area"] == "") {
	$query .= $GLOBALS['srbc_camps'] . ".area LIKE '%' ";
}
else {
	$values = array($_GET['area']);
	$query .= $GLOBALS['srbc_camps'] . ".area='%s' ";
}
```
I expect to see this:
```
public function area_report()
	{
		throw new Exception("Area report currently doesn't work");
		if (isset($_GET['area']) && $_GET["area"] == "") {
		$query .= $GLOBALS['srbc_camps'] . ".area LIKE '%' ";
		}
		else {
			$values = array($_GET['area']);
			$query .= $GLOBALS['srbc_camps'] . ".area='%s' ";
		}
	}
````
But instead I see this:
```
	public function area_report()
	{
		throw new Exception("Area report currently doesn't work");
		if (isset($_GET['area']) && $_GET["area"] == "") {
	$query .= $GLOBALS['srbc_camps'] . ".area LIKE '%' ";
}
else {
	$values = array($_GET['area']);
	$query .= $GLOBALS['srbc_camps'] . ".area='%s' ";
}
	}
```
