### ISSUE TITLE
Highlight another view doesn't work by large file after saving

### ISSUE THREAD

**Issue by Ilja07** [notepad-plus-plus/notepad-plus-plus#7960]
### Description of the Issue
Highlight another view doesn't work by large file after saving

### Steps to Reproduce the Issue

1.  activate Smart Highlighting -> enable Highlight another view 
2.  open a large File length: 60000 Lines: 1500
3. then clone to other view
4. save the file or reopen the npp
5. the highlighting will not work any more in other view

### Debug Information

Notepad++ v7.8.4   (64-bit)
Build time : Jan 29 2020 - 01:31:03
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : ON
Local Conf mode : OFF
OS Name : Windows 7 Professional (64-bit) 
OS Build : 7601.0
Plugins : mimeTools.dll NppConverter.dll NppExport.dll

**Comment by Ilja07** [comment]
the version 7.7.1. 64Bit works with no issue

**Comment by sasumner** [comment]
Is it possible to post the file you described, for ease of attempted reproduction?

**Comment by Ilja07** [comment]
Unfortunately not its a *.c file but you can try with stylers.xml

**Comment by Ilja07** [comment]
Hi

I had same problem with 7.7.1 64 bit

To make it work again i had to close the clone view and reopen it again.

Thank you for create tool anyway

**Comment by ArkadiuszMichalski** [comment]
@Ilja07 Do you still have this problem in latest Notepad++ 7.9 verison? In step 3. you mean clone or copy/paste?  For both casees I can't reproduce when use `stylers.xml`.

**Comment by alankilborn** [comment]
Same/similar to #6176 ?
