### ISSUE TITLE
Function list won't detect zero-arg function defs followed by comment

### ISSUE THREAD

**Issue by ArdNut** [notepad-plus-plus/notepad-plus-plus#7963]
### Description of the Issue
A function definition with no args is not picked up and shown in the function list if it is followed by a comment on the same line.

Example:

    bool USBIface::USBOpenOutput()       // [PRIVATE]
    {
    ... code and stuff
    }

will not appear in the function list, but

    bool USBIface::USBOpenOutput()
    {
    ... code and stuff
    }

will appear.

**Comment by MAPJe71** [comment]
Duplicate of #344

**Comment by dail8859** [comment]
Closing as duplicate
