### ISSUE TITLE
Notepad++ crash with specific conditions

### ISSUE THREAD

**Issue by YKProg** [notepad-plus-plus/notepad-plus-plus#7964]
### Description of the Issue

Notepad crash while running.
### Steps to Reproduce the Issue

1. Use plugin:  3p 
2. Use plugin:  BookmarksDook 
3. Use plugin:  jN 
4. Use Delete Key to erase the next line

### Expected Behavior

Erase the next line, and keep running normaly
### Actual Behavior

Crash in the middle of codeing
### Debug Information

Using notepad++ v7.8.4  64 bit ,  with Windows 10 pro

Notepadd++ do not crash , while using only two of these plugins

**Comment by donho** [comment]
It's plugin issue but not Notepad++ one.
