### ISSUE TITLE
Duplicate names for 3 languages, in stylers.model.xml

### ISSUE THREAD

**Issue by guy038** [notepad-plus-plus/notepad-plus-plus#7965]
### Description of the Issue :

In the **`stylers.model.xml`** configuration file, the **`3`** languages **`BaanC`**, **`OScript`** and **`txt2tags`** have **`<WordsStyle>`** tags with **duplicate** names :

- For the **`BaanC`** language : **two** names **`DEFAULT`**

- For the **`OScript`** language : **two** names **`KEYWORDS`**

- For the **`TXT2TAGS`** language : **two** names **`LIST`**

Because of these **duplicate** names, the different attributes **cannot** be handled **properly**, particularly after modifications and a **restart** of Notepad++ !

### Obvious solution to fix that Issue :

In the **`stylers.model.xml`** configuration file :

- Change the *two* names **`DEFAULT`** ( *styleId="32"* and *styleId="8"* ) as **`DEFAULT1`** and **`DEFAULT2`**, for language **`BaanC`**

- Change the *two* names **`KEYWORDS`** ( *styleId="14"* and *styleId="15"* ) as **`KEYWORDS1`** and **`KEYWORDS2`**, for language **`OScript`**

- Change the *two* names **`LIST`** ( *styleId="13"* and *styleId="14"* ) as **`LIST1`** and **`LIST2`**, for language **`txt2tags`**

To this matter, refer to the **discussion** :

https://community.notepad-plus-plus.org/post/50854

See also this post, below, from @pryrt ( **PeterCJ** ) which, BTW, gave me the **initial** explanation about this **issue** !

https://community.notepad-plus-plus.org/post/50765

**Comment by pryrt** [comment]
As [mentioned in the thread](https://community.notepad-plus-plus.org/post/50854), I think the names should be
* baanc #32 = `DEFAULT`
baanc #8 = `IDENTIFIERS`
* txt2tags #13 = `LIST`
txt2tags #14 = `LIST2`
* oscript #14 = `TYPE`
oscript #15 = `GLOBAL FUNCTION`

(based on the scintilla/scite config files for each of those languages)

**Comment by donho** [comment]
@guy038 
Bien vu !

The fix will be based on :
https://github.com/notepad-plus-plus/notepad-plus-plus/blob/master/scintilla/include/SciLexer.h
