### ISSUE TITLE
all files removed, totally messed me up.

### ISSUE THREAD

**Issue by Fohsap** [notepad-plus-plus/notepad-plus-plus#7967]
### Description of the Issue
All files closed between sessions, all unsaved files lost!  Possibly tied to a recent update or 'opening project folders'?

### Steps to Reproduce the Issue
This is a persistent error: I am not sure if it can be easily reproduced.
1. Install npp, open a lot of documents, end the task and restart npp.  This should verify that npp reloads all the unsaved documents between sessions.  If it does not, maybe it's a version issue.
2. If all documents are reloaded, try opening a workspace (open a folder as a workspace).  Then, end the npp process and restart npp.  See if all the unsaved documents are re-loaded.
3. Ensure that "Settings->Backup->Remember current session for next launch" is enabled.  You should get this problem even if this setting is enabled.

### Expected Behavior
Keep all documents, even unsaved docs, as open tabs.

### Actual Behavior
Only my startup files are loaded (none of the files from the previous session).

### Debug Information
Notepad++ v7.7.1   (64-bit)
Build time : Jun 16 2019 - 21:24:47
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10 (64-bit)
Plugins : mimeTools.dll NppConverter.dll 

I looked in the backup locations in my user directory and stuff: all the unsaved files are lost, and my positions are lost. :/

**Comment by donho** [comment]
> Notepad++ v7.7.1 (64-bit)

Obviously your Notepad++ version is obsolete.

I tried to create the new unsaved docs in my Notepad++ v7.8.4 and end Notepad++ process under Task Manager. All the unsaved docs are restored after relaunching Notepad++.
