### ISSUE TITLE
copy > paste into find/replace is getting cutoff

### ISSUE THREAD

**Issue by klepp0906** [notepad-plus-plus/notepad-plus-plus#7977]
### Description of the Issue
Trying to paste some hex into the Find what box under the replace tab.

Here is the text
@=hex(2):22,00,43,00,3a,00,5c,00,50,00,72,00,6f,00,67,00,72,00,61,00,6d,00,20,\
  00,46,00,69,00,6c,00,65,00,73,00,20,00,28,00,78,00,38,00,36,00,29,00,5c,00,\
  4e,00,6f,00,74,00,65,00,70,00,61,00,64,00,2b,00,2b,00,5c,00,6e,00,6f,00,74,\
  00,65,00,70,00,61,00,64,00,2b,00,2b,00,2e,00,65,00,78,00,65,00,22,00,20,00,\
  22,00,25,00,31,00,22,00,00,00

This is all that goes into the box
@=hex(2):22,00,43,00,3a,00,5c,00,50,00,72,00,6f,00,67,00,72,00,61,00,6d,00,20,\

as such, when I did my replace, it only replaced the first line.  This used to not be the case.

Seems to be a line issue, not a character issue as I did 5 lines with letters and it again only picked up the first line.

I did consider something with the install, or version. so i downloaded two other versions (i use portables) and launched em clean and tried with the same result. 

### Steps to Reproduce the Issue

1.  Copy multiple lines of text
2.  Paste into the find what box under the replace tab
3.  notice you only get the first line

### Expected Behavior
All lines to copy/paste just as it had in the past

### Actual Behavior
Even if its short, or just pure characters - I only get the first line when pasting.  If i paste outside of notepad++ they all paste so its not the copy half, its the paste half.

### Debug Information
Notepad++ v7.8.4   (64-bit)
Build time : Jan 29 2020 - 01:31:03
Path : C:\Users\klepp\Dropbox\Downloads\Windows\Development\Text Editors\Notepad++\notepad++.exe
Admin mode : ON
Local Conf mode : ON
OS Name : Windows 10 Pro (64-bit) 
OS Version : 1909
OS Build : 18363.657
Plugins : mimeTools.dll NppConverter.dll NppExport.dll

**Comment by sasumner** [comment]
@klepp0906 

If I highlight your five lines above and copy and paste them into an editor tab in Notepad++, and then reselect then in Notepad++ and press ctrl+f, I see all five lines worth of data in my `Find what` box.  So I guess my response is "It works for me".  Barring more info, I'm not sure how to further debug why it doesn't work for you.

**Comment by klepp0906** [comment]
weird part is if i copy and paste into the find what box, it stops at the end of the first line, yet i can type whatever I want after that no problem.  So its not hitting an invisible wall persay, it just wont paste more text from a second line.   Like theres no wrap being applied to the paste.

**Comment by klepp0906** [comment]
so just tried on a completely different pc, result was the same.

**Comment by klepp0906** [comment]
after an absurd amount of digging - turns out its how it functions.

you cannot copy/paste multi line into the find/replace.   You have to copy from the editor, and it automatically populates the find/replace box.

if used in that fashion, it works.   Musta been how i had it working before.

**Comment by sasumner** [comment]
Ah, yes, OK.  I understand now.

You cannot paste multiline data into either the `Find what` or `Replace with` boxes.  If you select multiline data in the editor and then invoke `Find` via ctrl+f, THEN the multiline data will be transferred to the `Find what` box.  No easy way to get multiline data into the `Replace with` box, however.
