### ISSUE TITLE
Is right click > print not possible w/ notepad++?

### ISSUE THREAD

**Issue by klepp0906** [notepad-plus-plus/notepad-plus-plus#7987]
Going to skip the template as this is more of an inquiry as to the functionality of notepad++ and whether its something lacking, or an error on my part.

I edited the registry to allow for notepad++ to handle the editing of pretty much anything text related.  I also changed the print and printto where relevant from notepad to notepad++ ala 

`[HKEY_CLASSES_ROOT\txtfile\shell\print\command]
@="\"C:\\Users\\path\\pointing\\to\\my\\notepad++.exe\" /p \"%1\""`

it appears that for txt files, the print option isnt even present in the context menu.  for items where it is present (.reg files for example) a right click > print, results in 
![image](https://user-images.githubusercontent.com/10392920/75582339-5a217800-5a39-11ea-9b58-a1c5498ec1f8.png)

I assume one of two things is going on here.  Somehow ive botched the command and its different for notepad++ or notepad++ doesnt allow for this.

Either way i'd like to know so i can get it fixed, or revert it and clean up what is undoubtedly the universal inability to right click > print atm regardless of extension :p 

Thanks!

**Comment by sasumner** [comment]
`/p` isn't a valid command-line argument for Notepad++; see `?` menu > `Command Line Arguments...` where you'll see `-quickPrint` is.

**Comment by klepp0906** [comment]
ok thank you for that. 

So would replacing the /p in the registry string with -quickPrint afford me a right click > print option then?
