### ISSUE TITLE
T-SQL missing keywords 

### ISSUE THREAD

**Issue by conky77** [notepad-plus-plus/notepad-plus-plus#7988]
### Description of the Issue
some T-SQL keywords and function are not highlithed:

APPROX_COUNT_DISTINCT
STRING_AGG
string_split
PARSE
TRY_CAST
TRY_CONVERT
TRY_PARSE
choose
iif
DATEDIFF_BIG 
DATEFROMPARTS 
DATETIME2FROMPARTS 
DATETIMEFROMPARTS 
DATETIMEOFFSETFROMPARTS 
EOMONTH 
SMALLDATETIMEFROMPARTS 
TIMEFROMPARTS 
openjson

### Steps to Reproduce the Issue

.1 open a new windows
.2 select SQL language
.3 Copy and past the previous lists in Notepad++

### Expected Behavior

When the selected language is SQL, the keywords should become highlited.

### Actual Behavior

When the selected language is sql, the text are not highlited.

### Debug Information

Notepad++ v7.8.4   (32-bit)
Build time : Jan 29 2020 - 01:33:47
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS Name : Windows 10 Enterprise (64-bit) 
OS Version : 1903
OS Build : 18362.657
Plugins : ComparePlugin.dll mimeTools.dll NppConverter.dll NppExport.dll Translate.dll XMLTools.dll

**Comment by CurbedLarry** [comment]
The default generic SQL language highlighting will never be up date with recent additions to all databases.

I contributed new keywords last year (as part of a change to highlight data types in a different colour) and this added a number of missing T-SQL keywords up to version 2016 I think.  Previously it was about 10 years out of date.

You can simply add those as "User-defined" keywords in the **Style Configurator** dialog box.
