### ISSUE TITLE
Ctrl+Alt+Shift+F is now a reserved shortcut and no longer works for Uncollapse Current Level

### ISSUE THREAD

**Issue by fernandreu** [notepad-plus-plus/notepad-plus-plus#7989]
### Description of the Issue
It seems that, since Windows 10 version 1903, the `Ctrl+Alt+Shift+F` shortcut is reserved by Windows, even if it does not do anything yet; see [this](https://superuser.com/questions/1445551/what-does-ctrlaltshiftf-key-combination-in-windows-10-pro-version-1903-do).

This is currently the shortcut used for `Uncollapse Current Level`, which no longer works due to this. Therefore, I would suggest replacing it with something else.

### Steps to Reproduce the Issue

1. Open a file with levels that can be folded
2. Put the cursor in a collapsed level
3. Press `Ctrl+Alt+Shift+F`

### Expected Behavior
The collapsed level should unfold.

### Actual Behavior
Nothing.

### Debug Information
Notepad++ v7.8.4   (64-bit)
Build time : Jan 29 2020 - 01:31:03
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS Name : Windows 10 Home (64-bit) 
OS Version : 1909
OS Build : 18363.657
Plugins : mimeTools.dll NppConverter.dll NppExport.dll

**Comment by sasumner** [comment]
>since Windows 10 version 1903, the Ctrl+Alt+Shift+F shortcut is reserved by Windows, even if it does not do anything yet;

Yuck!  Blech!

**Comment by alankilborn** [comment]
Tested in N++ 8.4.4 (current version as of this writing) and could not repro any sort of problem with Ctrl+Alt+Shift+f.
Its default functionality works, and a remapping of its functionality to something else also works.
Recommend CLOSURE of this item.

**Comment by ArkadiuszMichalski** [comment]
@alankilborn What system you used?

**Comment by alankilborn** [comment]
Notepad++ v8.4.4   (64-bit)
Build time : Jul 15 2022 - 17:54:42
Path : C:\...\npp.8.4.4\npp.8.4.4.portable.x64\notepad++.exe
Command Line : -titleAdd="8.4.4 64-bit" -multiInst "C:\...\npp.8.4.4\npp.8.4.4.portable.x64\license.txt"
Admin mode : OFF
Local Conf mode : ON
Cloud Config : OFF
OS Name : Windows 10 Enterprise (64-bit) 
OS Version : 21H2
OS Build : 19044.1826
Current ANSI codepage : 1252
Plugins : 
    mimeTools (2.8)
    NppConverter (4.4)
    NppExport (0.4)
