### ISSUE TITLE
Highlighting Different languages in same text file or php file.

### ISSUE THREAD

**Issue by kpkdhar22** [notepad-plus-plus/notepad-plus-plus#799]
If there is a file with different languages in a single text file (php, html, css, js). Provide a switch to enable detect multiple language highlight. it may be .php or .txt file. some times I extract code of repeated functionality into a text file. Or if any special code tags are provided like.

in settings a switch like use multi-language mode
(php)
       Highlight php code...
(/php) 
(html)
       Highlight html code..
(/html)
(css)
       Highlight css code..
(/css)
(sql)
       Highlight sql code..
(/sql)
(js)
       Highlight java script..
(/js)

or a plugin extension is also good.

**Comment by cmeriaux** [comment]
:+1: 
I'm also interested in that feature.

**Comment by Rikk** [comment]
I don't understand... Isn't it what happens with .php files?
If you have the php open tag `<?php` it will highlight as PHP; if you remove the open tag, it will highlight as HTML; if you have JS open tag `<script>` in any part of HTML, it will highlight as Javascript.
CSS highlight only works in .css files, however.

**Comment by donho** [comment]
Currently all the embedded languages (except css) can be detected a in a html file and highlighted correctly, if all the syntax is correct.
