### ISSUE TITLE
File extension .txt no longer default

### ISSUE THREAD

**Issue by Surisnek** [notepad-plus-plus/notepad-plus-plus#7990]
### Description of the Issue
On saving a generic text file, the file extension in the Windows Explorer file dialog is no longer .txt as was the case in previous versions of Npp. The file extension is empty.
### Steps to Reproduce the Issue

Write something in an empty file window. Don't choose a "Language".
OR: Open an existing .txt file.
Save the file to disk with Save (case 1) or Save as (case2).

### Expected Behavior
The file should register on disk as a txt file, with Windows file extension .txt.

### Actual Behavior
The file is saved on disk without any Windows file extension.

### Debug Information
Notepad++ v7.8.4   (32-bit)
Build time : Jan 29 2020 - 01:33:47
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS Name : Windows 10 Home (64-bit) 
OS Version : 1903
OS Build : 18362.657
Plugins : DSpellCheck.dll mimeTools.dll NppConverter.dll NppExport.dll

**Comment by sasumner** [comment]
To get the behavior desired by the author of this issue, you need to NOT have _Use new style dialog_ selected; in other words, you need to have this Preference choice set as shown here:

![image](https://user-images.githubusercontent.com/30118311/75624110-41bb7580-5b7f-11ea-9727-e33d0b3bd841.png)

**Comment by Surisnek** [comment]
I would like to note that I do in fact have that unchecked and the issue still stands. I read the previous issue reports and tried that already, and since it hadn't been MY problem I put in a new report: [http://prntscr.com/r9z6ew](url)

**Comment by sasumner** [comment]
Let's try this series of reproduction steps:

- Open an existing .txt file, say `D:\test.txt`
- Make some changes to it in Notepad++'s editing window (so that its icon becomes red, meaning that the file is "saveable".
- Save the file via ctrl+s.

At this point you see a file `D:\test` on disk when viewing with Windows Explorer, and not `D:\test.txt` ?

**Comment by Surisnek** [comment]
@sasumner Yes, the save file that was previously .txt reverted to a file without an extension at the end. I apologize for the delay, I had to go out of town unexpectedly. However I would also like to note that this is not _always_ the case when I save a previously saved text file. In some cases it leaves the extension just fine and it saves as it was. When I save a brand new, previously unsaved file, the extension is not ever added any longer.
