### ISSUE TITLE
Obtaining `english.xml` when build using Visual Studio

### ISSUE THREAD

**Issue by abdulbadii** [notepad-plus-plus/notepad-plus-plus#7992]
How to obtain `english.xml` when build by Visual Studio .vcxproj
Tried to build using Visual Studio .vcxproj  resulted in executable file only... please help on this.
Thanks in advance

**Comment by sasumner** [comment]
@abdulbadii 

>Tried to build using Visual Studio .vcxproj resulted in executable file only.

You can unzip a portable package of Notepad++ into the folder where your newly built notepad++.exe lives.  Just remember to decline overwriting of notepad++.exe.

Please take further **QUESTIONS** to the following forum; ISSUES are for bug reports and feature requests.

https://community.notepad-plus-plus.org/
