### ISSUE TITLE
Application crash on replace in files

### ISSUE THREAD

**Issue by Llewyllen** [notepad-plus-plus/notepad-plus-plus#7995]
### Description of the Issue
Application crash

### Steps to Reproduce the Issue
1. Open the "Find in files..." window
2. Click on "Replace in files"
3. Click on "Replace in files"

### Expected Behavior
None, as the "Are you sure" window should be modal but is not

### Actual Behavior
Application crash

### Debug Information
Notepad++ v7.8.4 (32-bit)
Windows 8.1

**Comment by sasumner** [comment]
@Llewyllen said:

>the "Are you sure" window should be modal but is not

It is harder than it seems it should be to be to make this API call result in a truly modal window:

int res = ::MessageBox(_hParent, msg.c_str(), TEXT("Are you sure?"), MB_OKCANCEL | MB_DEFBUTTON2);

This seems to do it:

int res = ::MessageBox(**NULL**, msg.c_str(), TEXT("Are you sure?"), MB_OKCANCEL | MB_DEFBUTTON2 **| MB_TASKMODAL**);

The docs ( https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-messagebox )
start out by saying `Displays a modal dialog box that contains...` but unless I'm confused about what _modal_ means, it clearly is modeless in the form in which Notepad++ is currently using it.

Anybody have some thoughts on this?

**Comment by xomx** [comment]
I can reproduce this crash.

MB_TASKMODAL should do it.

NULL HWND means the Desktop here, using combination of MB_TASKMODAL with _hParent does not work?

**Comment by xomx** [comment]
So I have refreshed my knowledge of the MessageBox API and the combination of NULL and MB_TASKMODAL is ok too.
