### ISSUE TITLE
Notepad Replacement - N++ opens Notepad.exe as Text File

### ISSUE THREAD

**Issue by Unknow0059** [notepad-plus-plus/notepad-plus-plus#7996]
### Description of the Issue
After following the steps in this [official Notepad++ guide](http://web.archive.org/web/20190826024434/https://notepad-plus-plus.org/features/replace-notepad.html), typing 'notepad' in Windows' Run opens Notepad++, who in turn opens notepad.exe as a text file, and prompts whether to create a  '-z' file that does not currently exist.

### Steps to Reproduce the Issue
1. Follow official guide
2. Type 'notepad' in Windows' Run

### Expected Behavior

I expected Notepad++ to open as if I had opened it manually, without opening any extra files.

### Actual Behavior

An extra file was opened: notepad.exe (as text).
A prompt asking whether to create a new file named '-z' popped up.

### Debug Information
Notepad++ v7.5.1 (64-bit)
Build time : Aug 29 2017 - 02:38:44
Path : G:\Software\Notepad++\notepad++.exe
Admin mode : ON
Local Conf mode : ON
OS : Windows 10 (64-bit) Pro 1903 10.0.18362.239
Plugins : ComparePlugin.dll mimeTools.dll NppConverter.dll

**Comment by sasumner** [comment]
Just a comment to say that current documentation on this feature is found here:
https://npp-user-manual.org/docs/other-resources/

**Comment by rddim** [comment]
@Unknow0059 
`...From the version 7.5.9...`

Your debug info says that you use v7.5.1

**Comment by Unknow0059** [comment]
@rddim I noticed that as I made this issue and I updated Notepad++ immediately. 
Doing so had no effect.
