### ISSUE TITLE
"New" blank document with undo history closes without warning

### ISSUE THREAD

**Issue by mrandreastoth** [notepad-plus-plus/notepad-plus-plus#7997]
### Description of the Issue
Closing a new blank document that has undo history closes without warning which can potentially lead to loss of work.

### Steps to Reproduce the Issue
1. Create a new blank document.

2. Work on the document performing various edit operations but don't save.

3. Clear the document. (Note that this could happen accidentally, e.g., one clears the wrong document, etc.)

4. Close the document.

### Expected Behavior
A dialog pops up warning the user that there is undo history associated with the blank document and if they would like to close it anyway. (There could be a setting to enable/disable this dialog.)

### Actual Behavior
Document closes without any warning.

**Comment by sasumner** [comment]
@mrandreastoth 

>Clear the document. (Note that this could happen accidentally, e.g., one clears the wrong document, etc.)

For 100% clarification purposes, what is meant by "clear the document"?
Would an example of it be "ctrl+a followed by a press of the delete key"?
I just want to make sure I understand fully, because there is no "clear document" command or function.

**Comment by sasumner** [comment]
An analogous scenario for "non-blank" documents could be stated thusly:

* open an existing file on disk
* make changes to file
* "undo" the changes such that file in editor buffer is at the same "level" as the disk file -- the "disk" icon on the tab is blue, not red
* close the document

In this case, the file closes without warning that there is "redo" history available.

**Comment by sasumner** [comment]
@mrandreastoth Thank you for your suggestion, but we are declining to implement it in Notepad++.
