### ISSUE TITLE
Scintilla update

### ISSUE THREAD

**Issue by NN---** [notepad-plus-plus/notepad-plus-plus#80]
Please update to the latest Scintilla.
They fixed many bugs and the annoying one with WM_GETTEXT ( http://sourceforge.net/p/scintilla/code/ci/d2579847448f4e59145b0892bed20247d4e8a781/ ) . .

Thanks,

**Comment by ariccio** [comment]
I tried this, somewhere else (I can't find it - grr!). Good luck getting this merged.

**Comment by NN---** [comment]
I compiled Scintilla from latest revision source without any change and everything is working.

**Comment by ariccio** [comment]
I know, it did for me to.

Same thing [with SQLite](https://github.com/donho/notepad-plus-plus/pull/14).

**Comment by cmeriaux** [comment]
:+1:

**Comment by crayxt** [comment]
+1

**Comment by NN---** [comment]
Another reasons for update.
The latest Scintilla doesn't have dependency on boost anymore ( #118 )
And it has a vcxproj file for easier compiling ( https://sourceforge.net/p/scintilla/code/ci/default/tree/win32/ ) making it possible to have a solution with project reference.

**Comment by NN---** [comment]
And it is x64 build ready.
Actually Scintilla must be updated for 64-bit build.

**Comment by MAPJe71** [comment]
Be aware that Notepad++ uses an adapted Scintilla (indicated by 'for Notepad++' in the file version).
Some of the changes are:
 - Added the 'Search Result'-, 'Objective-C'- and 'User Defined Language'-lexers.
 - Adapted HTML lexer to default to Visual Basic Script i.s.o. JavaScript for ASP embedded script.
 - Added possibility for PCRE search which depends on Boost::RegEx.

So simply compiling the latest Scintilla revision source without any change might work but it probably won't give you back all of Notepad++'s functionality.

**Comment by NN---** [comment]
I see. So basically Notepad++ has an unmaintained fork of Scintiilla. Very sad:(
This issue blocks #64

**Comment by don4d** [comment]
@NN--- Scintilla will be updated in 6.8 release.

**Comment by donho** [comment]
@NN--- Scintilla will be updated in 6.8 release.

**Comment by NN---** [comment]
@donho Glad to hear!
Maybe you should propose pull requests to the main repository ?
Also it will be good to have a normal fork in sorceforge.
It is going to be easier maintaining and updating.
And since it has a project file you should really make a simple solution with both projects and reference.
Add sln file to repo back.

Not sure, I think if you ignore it then file will be tere but nobody will commit any changes

**Comment by NN---** [comment]
@donho What about making Scintilla extendable and remove the need of modifying sources ?
I see that you changed CreateRegexSearch function to return BoostRegex matcher.
If Scintilla had an extendibility point such as:

```cpp
typedef function<RegexSearchBase *(CreateRegexSearch(CharClassify* charClassTable)> RegexSearchFactory;

RegexSearchBase *CreateRegexSearch(CharClassify *charClassTable) {
	return new BuiltinRegex(charClassTable);
}

// Default value
RegexSearchFactory globaRegexSearchFactory = CreateRegexSearch(;

SetRegexSearchFactory(RegexSearchFactory factory)
{
  globaRegexSearchFactory = factory;
}

RegexSearchBase *CreateRegexSearch(CharClassify* charClassTable)
{
	return globalRegexSearchFactory(charClassTable);
}
```
Then in Notepad++ you could just call SetRegexSearchFactory(BoostRegexSearch) .

Another possibility is to split Scintilla into two libs one with external implementation of CreateRegexSearch and the second includes the first with the implementation.
Notepad++ could provide its own implementation.
I think it is even easier to do then changing the code.

It makes easier updates of Scintilla.

**Comment by ariccio** [comment]
> Maybe you should propose pull requests to the main repository ?

We absolutely should do this.

> And since it has a project file you should really make a simple solution with both projects and reference.
> Add sln file to repo back.



Xref: #87
Xref: #90 
Xref: https://github.com/donho/notepad-plus-plus/commit/ec105d7b5f354aabe9906de74d0eaa00a42a9647
Xref: https://github.com/donho/notepad-plus-plus/commit/0628508ef0dbdda9955134920b9331adb7bf02ca

**Comment by ariccio** [comment]
Updated in commit: 4ac665d
