### ISSUE TITLE
Display refresh missing in exit

### ISSUE THREAD

**Issue by VolkerWippel** [notepad-plus-plus/notepad-plus-plus#800]
Win7 x64, NPP.6.8.2

Exit NPP -> on my screen the NPP window is still visible, in the taskbar no instance anymore.
When moving other windows over this zombie-window, it is by and by overwritten.

A refresh seems missing. NPP.6.8.1 works OK.

![npp_err](https://cloud.githubusercontent.com/assets/13960839/9464024/f73bc92e-4b20-11e5-907a-ae0af29a1913.png)

**Comment by cmeriaux** [comment]
:+1: 
I have the same problem

**Comment by milipili** [comment]
Hum that's probably my mistake.

**Comment by donho** [comment]
Hi @VolkerWippel & @cmeriaux 
It’s fixed here:
https://notepad-plus-plus.org/temp/npp.deadLockFixed.zip

Could you test it and confirm me if this bug is fixed in the binary mentioned above?

**Comment by VolkerWippel** [comment]
Cannot test.

Regards, Volker

**Comment by cmeriaux** [comment]
@donho Hello, I'm sorry but the bug isn't fix.
Here is the screenshot of the version

![nppversion](https://cloud.githubusercontent.com/assets/12024941/9514954/67828e92-4c9e-11e5-9bc9-79296dc8f3f8.png)

I'm on Windows 7 entreprise 64

**Comment by cmeriaux** [comment]
@donho @VolkerWippel after some test, the problem is due to compare plugin (v 1.5.6.0)
Can yon confirm it @VolkerWippel ?

**Comment by donho** [comment]
@cmeriaux  Thank you for the info. I did another fix here:
https://notepad-plus-plus.org/temp/npp_deadLockFix2.zip

Could you try it with compare plugin please?

**Comment by cmeriaux** [comment]
@donho it's working now. Thank you.
By the way, could you have a look to my PR (#70)

**Comment by donho** [comment]
@cmeriaux Thank you for testing!
I will check the PR and give you feedback soon.

**Comment by nemgh** [comment]
@donho your https://notepad-plus-plus.org/temp/npp_deadLockFix2.zip update fixed this issue for me too. I replied it was fixed in the Announcements community page too. Thanks again.
