### ISSUE TITLE
Add Support for Windows 10 Dark Mode (Suggestion)

### ISSUE THREAD

**Issue by SyndiShanX** [notepad-plus-plus/notepad-plus-plus#8002]
As of the time of Submitting this ticket Notepad++ doesn't support the Dark Mode feature introduced in Windows 10.

I would like to see support added as there isn't a way that I've been able to find to change the window color, and white is blinding when going from dark mode apps to Notepad++.

**Comment by wolfgrrl** [comment]
Agreed. Would love to see this. Thank you!

**Comment by hellon8** [comment]
Duplicate #7692

**Comment by dail8859** [comment]
Closing in favor of #7692
