### ISSUE TITLE
Folder as Workspace panel opened even with "-nosession"

### ISSUE THREAD

**Issue by mwerle** [notepad-plus-plus/notepad-plus-plus#8005]
### Description of the Issue

I expected the "Folder as Workspace" panel to be part of a session, rather than as part of the global Notepad++ state.

This feature is *very* useful when actually working on many files within a directory tree, but IMHO completely useless when just wanting to edit a random file somewhere (usually via a "Edit With" right-click).

As such, when starting Notepad++ with the "-nosession" switch, I would expect the panel to be closed and empty.

### Steps to Reproduce the Issue

1. Open Notepad++ and open the "FaW" panel with some folder.
2. Open another instance of Notepad++ with the "-nosession" switch
3. 

### Expected Behavior

"Nosession" instance to be opened with the "FaW" panel to be empty and closed.

### Actual Behavior

Second instance opens the selected file(s), but also the "FaW" panel with the current "Workspace" loaded.

### Debug Information

Notepad++ v7.8.1   (64-bit)
Build time : Oct 27 2019 - 22:57:19
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS Name : Windows 10 Enterprise (64-bit) 
OS Version : 1803
OS Build : 17134.1304
Plugins : MarkdownViewerPlusPlus.dll mimeTools.dll NppConverter.dll NppEditorConfig.dll NppExport.dll NPPJSONViewer.dll

**Comment by ArkadiuszMichalski** [comment]
Good question. Even if FAW still will be remembered in `config.xml` (not `session.xml`), it may worth modify the argument `-openFoldersAsWorkspace` a bit so that for an empty value the FAW panel will be inactive.
