### ISSUE TITLE
When launched with any of the "jump to certain line or position" arguments, the cursor is correctly positioned, but the viewport is not scrolled to the cursor position when word wrap is enabled.

### ISSUE THREAD

**Issue by rwasef1830** [notepad-plus-plus/notepad-plus-plus#8007]
### Steps to Reproduce the Issue

1. Execute the following command in cmd or Start > Run
```"C:\Program Files (x86)\Notepad++\notepad++.exe" -n500 "C:\Windows\setupact.log"```

### Expected Behavior
Cursor positioned on line number 500 and viewport scrolled to center line 500 in the middle of the viewer.

### Actual Behavior
Cursor is positioned on the correct line, but the viewport is not scrolled there. If you move the cursor arrow keys, the viewport will jump to the correct location.

### Debug Information
Notepad++ 7.8.4 (32-bit)

**Comment by roelschroeven** [comment]
I have the same issue, but only when word-wrap is on. With word-wrap off, '-n' works as expected.

It looks like https://github.com/notepad-plus-plus/notepad-plus-plus/commit/5d1dcc125328f8e8309f456fb86cf66e7e959c6b should be a fix for this. I'm not sure if that commit is in 7.8.4. If it is, it didn't work.

**Comment by rwasef1830** [comment]
Can confirm. The bug happens only when word wrap is enabled. With word wrap disabled, it functions correctly.

**Comment by leitwolf7** [comment]
Same problem here after update to 7.8.5

**Comment by ziggurat29** [comment]
I would like to add the following details:
* with word wrap on,
* when the document in question must be loaded into a running editor, the command line option '-n' fails to scroll to the designated line
* also, if the specified document is already loaded in a session that will be restored when the editor launches, the scrolling problem will still occur
* however, if the document is already loaded in a currently running editor (even with word wrap on), the scrolling problem does _not_ occur

it feels like a race of some sort exists between having to process the word-wrapping and getting around to scrolling -- if the word-wrapping has already been done (in an already-loaded document), then the scrolling happens as expected.

**Comment by AakaFosfor** [comment]
The problem is sill in 7.8.6

Notepad++ v7.8.6   (64-bit)
Build time : Apr 21 2020 - 15:23:03
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS Name : Windows 10 Enterprise (64-bit) 
OS Version : 1709
OS Build : 16299.1806
Plugins : none

**Comment by foreachthing** [comment]
The problem remains in 7.8.7.

```
Notepad++ v7.8.7   (64-bit)
Build time : Jun  5 2020 - 02:38:56
Path : C:\Users\USER\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS Name : Windows 10 Enterprise (64-bit) 
OS Version : 1809
OS Build : 17763.1282
Current ANSI codepage : 1252
Plugins : BetterMultiSelection.dll 
          BigFiles.dll 
          CodeAlignmentNpp.dll 
          Explorer.dll 
          mimeTools.dll 
          NppConverter.dll 
          NppExport.dll 
          NppFavorites.dll 
          NppSaveAsAdmin.dll 
          Python Indent.dll 
          XMLTools.dll
          CustomizeToolbar.dll 
```

As well as `Plugins: NONE`

**Comment by ArkadiuszMichalski** [comment]
Probalby fixed in 7.8.9.
https://community.notepad-plus-plus.org/topic/19715/notepad-v7-8-9-released.
Can someone confirm?

**Comment by leitwolf7** [comment]
Just tested using 7.9 and the problem is gone for me! I hope others see the same result.
Thank you!!

**Comment by roelschroeven** [comment]
Same as leitwolf7: tested with 7.9 and it works fine now, as far as I can see. Thanks!

**Comment by rwasef1830** [comment]
Confirmed. This issue is now fixed.
