### ISSUE TITLE
Certain regex search in files behaves erroneously if an ansi file contains special chars

### ISSUE THREAD

**Issue by ddBenny** [notepad-plus-plus/notepad-plus-plus#8008]
### Description of the Issue

Certain regex search in files takes unexpectedly long and returns full file as result, if that file contains special chars and is saved as ANSI.

The regexes in question contains certain zero length parts. An example is to search for a word with an optional first letter like: \bT?MyClass\b

Now, if a file in the searched directory contains a special char. e.g. "some “text” in fancy quotes" (note the opening and closing quotes) and is stored as ANSI (i.e. contains the bytes 0x93 and 0x94 for the quotes), the above mentioned behaviour occurs.

### Steps to Reproduce the Issue

1. create an ANSI file containing e.g. "some “text” in fancy quotes"
2. if file is opened in np++, now close that file (tab)
3. put that file into a folder on its own
4. do a regex file search in np++ from the folder of the file just created using search term "\bT?MyClass\b"

### Expected Behavior

- search terminates quickly
- no search results

### Actual Behavior

- search takes a while (app freezes)
- returns one search result consisting of full file
- in "Find result" window, the special chars are shown as boxes

### Debug Information
[nppp_test_ansi.txt](https://github.com/notepad-plus-plus/notepad-plus-plus/files/4287481/nppp_test_ansi.txt)

Notepad++ v7.8.4   (32-bit)
Build time : Jan 29 2020 - 01:33:47
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS Name : Windows 10 Enterprise (64-bit) 
OS Version : 1903
OS Build : 18362.657
Plugins : ComparePlugin.dll DSpellCheck.dll JSLintNpp.dll JSMinNPP.dll LocationNavigate.dll mimeTools.dll NppConverter.dll NppExec.dll NppExport.dll PyNPP.dll XMLTools.dll 

- does not occur, if file is UTF8
- does not occur, if the file is opened in np++
- does not occur, if normal (ASCII) quotes are used
- does not occur without the \b in the regex
- does not occur without the T? in the regex

**Comment by alankilborn** [comment]
Tested in N++ 8.4.4 (current version as of this writing) and could not repro.
I get exactly the "Expected Behavior" as detailed above.
Recommend CLOSURE of this item.

![image](https://user-images.githubusercontent.com/77065706/183098748-fd519f7f-94e2-4e13-a520-a12068f43895.png)

**Comment by ddBenny** [comment]
confirmed, cannot reproduce myself anymore
