### ISSUE TITLE
Bug? XP, 2003 - File association settings are blocked even under Admin

### ISSUE THREAD

**Issue by bnote** [notepad-plus-plus/notepad-plus-plus#8010]
ALL mentioned below are 32-bit

XP SP3, 2003 SP2

Introduced in 7.8.3 "enhancement" as:
"9.  Disable file association settings when Notepad++'s no admin right"
leaves unreachable "Setting - Prefernces - File association" 
even for root admin under RID 500 account.

----------------------
In XP - user is member of Administartors group:
1. Regular NPP start - blocked
2. RMB "Run as .." 
2.1 ".. Current user" w cleared checkbox "Protect my comp..." - blocked
2.2 ".. The following user:" --> Administrator (built-in account) - blocked

----------------------
In 2003 - user is real Administartor (built-in 500)
This account is the only among HKU

1. Regular NPP start - blocked
2. RMB "Run as .." 
2.1 ".. Current user" w cleared checkbox "Protect my comp..." - blocked
2.2 ".. The following user:" --> Administrator (built-in 500) - blocked

![IHKU](http://s1.bild.me/bilder/221219/46247570304_180148.png)

----------------------
However in W7 under user, is member of Administartors group,
NPP show in caption "new 1 - Notepad++ [Administartor]" 
and file association settings are unblocked.
.

**Comment by dail8859** [comment]
Unfortunately due to the age and lack of support for XP and 2003 it is not reasonable to expect bugs to be fixed that are specific to these versions. If Notepad++ works to some extent on XP and/or 2003 still then great...but beyond that either live with the flaws or stay on older versions of the software.
