### ISSUE TITLE
python console exit()

### ISSUE THREAD

**Issue by kokare-darshan** [notepad-plus-plus/notepad-plus-plus#8012]
### Description of the Issue
Notepad++ closes when we enter exit() in python console

### Steps to Reproduce the Issue

1.  close the plugin when python console return with exit code
2. 
3. 

### Expected Behavior

notepad++ should not close
 
### Actual Behavior

notepadd++ exits with python console

### Debug Information

Notepad++ v7.8.4   (64-bit)
Build time : Jan 29 2020 - 01:31:03
Path : D:\Program Files\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS Name : Windows 10 Home Single Language (64-bit) 
OS Version : 1909
OS Build : 18363.657
Plugins : DSpellCheck.dll mimeTools.dll NppConverter.dll NppExport.dll Python Indent.dll PythonScript.dll

**Comment by sasumner** [comment]
Please take such an issue to the Pythonscript issue reporting site.
