### ISSUE TITLE
NTFS alternate data streams are lost

### ISSUE THREAD

**Issue by vefatica** [notepad-plus-plus/notepad-plus-plus#8013]
If a file with NTFS alternate data streams is opened and saved in notepad++, the alternative data streams are lost.  This is unfortunate.  I use alternate data streams to store data sets and helper scripts to batch files and other scripts.  I noticed reports of this from 4 years ago.  Will it ever be fixed?  Thanks!

**Comment by sasumner** [comment]
>I noticed reports of this from 4 years ago.

And you commented in #1498 right before opening this issue.  Please don't open new duplicate issues when you clearly have seen an already existing open one.  Add any commentary to the existing one.
