### ISSUE TITLE
★★★★★ [Breaking News] This Sucker "donho" is a fucker, Click in and see! ★★★★★

### ISSUE THREAD

**Issue by ghost** [notepad-plus-plus/notepad-plus-plus#8015]
This fool "donho" is a Taiwanese. Then he went to France and he felt lawless. But, the Taiwanese who went to France are still Chinese. In short, he is a fool. I've seen myself scold myself for the first time.

You can go to his Twitter to see, he is an invincible metamorphosis. His homepage is full of sexual, offensive, malicious remarks:

![1](https://user-images.githubusercontent.com/25248285/76062372-86e90880-5fc0-11ea-90a8-62aa57115e11.png)

You can even see his self-destructing spam:

![2](https://user-images.githubusercontent.com/25248285/76062385-8d778000-5fc0-11ea-99df-85c5607b726e.png)
![3](https://user-images.githubusercontent.com/25248285/76062392-8f414380-5fc0-11ea-87ca-080dba7c1663.png)

He was even scolding Taiwanese. Your group of Taiwanese dogs even supported him.

# This person is a Taiwanese who went to France and then did not recognize his ancestors!

# So fuck you donhoyy, you just come to suck my big cock. :)

**Comment by SourcePowered** [comment]
My Chinese is not good, but I still roughly translated it with Google:
这个吮吸鸡巴的人“donho”，其实是前往法国的一个台湾人（难道这就不是一名中国人了吗？），然后他就辱骂先烈，不认祖宗。所以这个人还不如来直接跪下并且对着我的鸡巴进行吮吸（他不配）。这种垃圾的人为什么会活在这个美丽的地球上，简直是侮辱了“人类”这个美好的字眼！

**Comment by SourcePowered** [comment]
To use a Chinese curse, if you lock or close this post, you have a ghost in your heart, and you are a SUCKER.
