### ISSUE TITLE
Official site redirecting to tech support scam site

### ISSUE THREAD

**Issue by nickpage221** [notepad-plus-plus/notepad-plus-plus#8019]
Went to official site to download the current release but, I haven't been able to get it yet because before I can select a download link it redirects to a tech support scam site

DONOTCLICKLINKhttp://ldshea.store/ln/heUVmOCso_RAvGi8AsDOoIY3chKwHZNmWobYDAOCdJblVHTJ1saskbToDOm3klhB_VR0meXYwXHSThSSsVdALJQrqLTDHpRgoXirVo.bt6cGaYSENKaqSC4Vfa2v7z6kFwdFtcegUAdrkTP2ein9NvxsL_nr0KA83BmAzncVsb7pvr2EIeydCTY2ZXj6aKJyvuTOeaW4luTYAoo84iBZM782tKD9gBvtlVe0l36kvgyMA.GGw_aDz5Lxkr7fvi2jqsdxpTG9s3pjnlj5cbwZqeRtTqlMhIVQjBcUVzJCPO3O7uIDbza7_HTb7h5hhCaVi2Kal_EI5V7eSWyS4c6mMS6YDcuH17PQjpQNr9eL4Kul.Gl7QwV6yV7j7Nzbuc_SCoryXXOJ33q3APZn1MCkTpGrC2kdIt4TQjlV89K72NB_pMakBBCclrt2DoquJebb

**Comment by sasumner** [comment]
A search for "Notepad++ download" leads me on a journey that takes me thru the official site and to a download of the proper 7.8.5 installer.  Maybe it is just you having the above problem?

**Comment by nickpage221** [comment]
I was on the official site at "https://notepad-plus-plus.org/downloads/v7.8.5/", the page would load for a moment then re-direct to the malware link given above. It was 100% repeatable last night but, it looks like the host has resolved this, it's not re-directing now, and the malware host is now down, 404 in Chrome and filtered as 'unsafe' by Defender SmartScreen in Edge. So thank you to everyone who reported this to the host as it has been resolved.
