### ISSUE TITLE
Bug and Translation: untranslated labels in User-defined form (Undock and sometimes Dock label) and scrollbar missing

### ISSUE THREAD

**Issue by conky77** [notepad-plus-plus/notepad-plus-plus#8020]
### Description of the Issue

Language-->User defined language-->define your language
1-the label for button "Undock" is not possible to translate (it is not present in the master English.xml)
2- the label of button "dock" is translated only when you get into the form the first time; if you press "dock" and "undock", the label "Dock" appears untranslated
3-in the form user-defined, in undock-mode, there is not any scrollbars

### Steps to Reproduce the Issue

1. Language-->User defined language-->define your language (the first time the label "Dock"  is translated)
![image](https://user-images.githubusercontent.com/59116246/76161216-6db39980-6131-11ea-996a-a938002e902f.png)

2.  press "Dock": the button "Undock" appears untranslated  
![image](https://user-images.githubusercontent.com/59116246/76161168-e49c6280-6130-11ea-8be0-b4337328bf9e.png)

3.  Press "undock": the button "Dock" appears untranslated

![image](https://user-images.githubusercontent.com/59116246/76161333-ba4ba480-6132-11ea-8053-083fb459cb88.png)

4. when the form is Undocked, there is not any scrollbars

![image](https://user-images.githubusercontent.com/59116246/76161222-8328c380-6131-11ea-9c21-6d0404c916a7.png)

### Expected Behavior

1. Include the label "undock" in the master English.xml
2. refresh the buttons Dock/Undock with the right translation
3. insert a scrollbar in the form in "undock-MODE"

### Actual Behavior

Labels not translated for "undock", the translation for "Dock" appears only the first time, scrollbar missing in "undock-mode"

### Debug Information

Notepad++ v7.8.5   (32-bit)
Build time : Mar  4 2020 - 11:04:20
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS Name : Windows 10 Enterprise (64-bit) 
OS Version : 1903
OS Build : 18362.657
Plugins : ComparePlugin.dll mimeTools.dll NppConverter.dll NppExport.dll Translate.dll XMLTools.dll

**Comment by ArkadiuszMichalski** [comment]
>3-in the form user-defined, in undock-mode, there is not any scrollbars

This dialog is not resizable so scrollbars are unnecessary.
