### ISSUE TITLE
Search/Replace remove character when adding newline in replace

### ISSUE THREAD

**Issue by zargblatt** [notepad-plus-plus/notepad-plus-plus#8023]
### Description of the Issue
If you have a long XML without newline after a <tag>. I would like to replace the > caracter with a >/n
When i do this, some, but not all ">" is missing.

### Steps to Reproduce the Issue
Gotoo Replace
Find what = ">"
Replace with ">\n"
Toggle search mode Extended

some of the ">" characters are now missing....

**Comment by sasumner** [comment]
You didn't follow the issue template.

"Debug Information" in the template requires Notepad++ version information; please provide or your issue will be closed.

Also, you're going to have to provide some sample data that this manifests on.

**Comment by dail8859** [comment]
Closing due to no response
