### ISSUE TITLE
Tilde key overlaps subsequent key entries for some reason.

### ISSUE THREAD

**Issue by Tenome** [notepad-plus-plus/notepad-plus-plus#8027]
### Steps to Reproduce the Issue

Using the ~` key will cause it to overlap over itself and other keys that are entered.

### Expected Behavior
abc~~~~~~~```````

### Actual Behavior
abc~` (<-- overlaps on itself)

### Debug Information
Notepad++ v7.8.5   (64-bit)
Build time : Mar  4 2020 - 11:08:34
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : ON
Local Conf mode : OFF
OS Name : Windows 7 Professional (64-bit) 
OS Build : 7601.24289
Plugins : DSpellCheck.dll mimeTools.dll NppConverter.dll NppExport.dll 

Video demonstration:
https://streamable.com/1chnv

Windows 7, 64-bit

**Comment by sasumner** [comment]
What kind of monitor do you have?  (Specs, not brand)

**Comment by nashv** [comment]
Cannot reproduce on US / EU International, Notepad 7.8.5, Windows 10 x64.

This seems more related to the keyboard type being used by the OP and the keyboard settings.

**Comment by Tenome** [comment]
> What kind of monitor do you have? (Specs, not brand)

amazon.com/dp/B005BZNDOO/

**Comment by alankilborn** [comment]
Tested in N++ 8.4.4 (current version as of this writing) and could not repro.
Recommend CLOSURE of this item.
