### ISSUE TITLE
Combination of hash ( # ) and C comment ( /* */ ) breaks syntax highlighting

### ISSUE THREAD

**Issue by jgeudens** [notepad-plus-plus/notepad-plus-plus#803]
Comments are highlighted in green as you can see in the image. The syntax highlighting of C comments ( `/* */` ) doesn't work after a preprocessor define. C++ comment ( `//` ) are recognized fine.

![image001](https://cloud.githubusercontent.com/assets/9089936/9474993/2f01681c-4b64-11e5-8213-814ee4378b11.png)

**Comment by sergiorighi** [comment]
In some CSS files I'm having the same problem, with complex comments. I changed the highligth to another language like C, and then went back to CSS to fix it.
