### ISSUE TITLE
Working Copy text from context menu in result window

### ISSUE THREAD

**Issue by amoibos** [notepad-plus-plus/notepad-plus-plus#8030]
### Description of the Issue
I'm using Notepad++ 7.8.5 in Windows 10 for searching & filtering of logging data. Unfortunately copying a part of a result leads to coping the full line. Ctrl+C and Ctrl+V works.

### Steps to Reproduce the Issue
1.  Search for a word
2.  Use context menu for copying a part of the result

### Expected Behavior
Only the selected part of the result line is in the clipboard.

### Actual Behavior
The full line is in the clipboard.

**Comment by sasumner** [comment]
Copying using the right-click context menu is by-design different from a ctrl+c copy.
