### ISSUE TITLE
Right click to open file : event if not containing folder

### ISSUE THREAD

**Issue by coucout** [notepad-plus-plus/notepad-plus-plus#8032]
### Description of the Issue
Right-click : open File do not work if no folder is selected.
Example: 

- select "myFile.txt". You cannot open file, even if the file is in the current directory. Sad
- select ".\myFile.txt"

### Expected Behavior
Open the file, event if no folder is specified

**Comment by sasumner** [comment]
Your issue really can't be taken seriously because you didn't include version information (you didn't follow the issue template).

However, it works for me:

* select "myFile.txt"
* Edit menu > On Selection > Open File
* file opens in Notepad++
