### ISSUE TITLE
Tabs are always inserted as spaces, regardless of settings

### ISSUE THREAD

**Issue by Youda008** [notepad-plus-plus/notepad-plus-plus#8033]
### Description of the Issue

Tabs are always inserted as spaces, regardless of settings.

When i configure my settings like this

![bug1](https://user-images.githubusercontent.com/20306543/76513301-643e7000-6456-11ea-8251-89e2263e8fda.png)
and then press a tab, 4 spaces are inserted

![bug2](https://user-images.githubusercontent.com/20306543/76513657-e9298980-6456-11ea-841d-c66d9c1cb8b8.png)

### Expected Behavior

When the checkbox is unchecked, i expect it to insert tab and not spaces.

### Debug Information

Notepad++ v7.8.4   (64-bit)
Build time : Jan 29 2020 - 01:31:03
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS Name : Windows 10 Enterprise (64-bit) 
OS Version : 1903
OS Build : 18362.657
Plugins : JSMinNPP.dll LanguageHelp.dll mimeTools.dll NppConverter.dll NppExport.dll XMLTools.dll

**Comment by sasumner** [comment]
Scroll down the "Tab Settings" box and check your setting for Python files.  What do you see there? (provide screenshot of that)

**Comment by Youda008** [comment]
I'm sorry that i'm responding so late, completely forgot about it.

Yes, the Python indeeded has its own overriden settings.
![python-indentation](https://user-images.githubusercontent.com/20306543/77456376-6cee5900-6dfb-11ea-90a8-c02282403326.png)
My fault, i did not realize that each language has its own settings.
Not a bug.
