### ISSUE TITLE
When disable JSON language files with .json ext still parsed as JSON

### ISSUE THREAD

**Issue by skironDotNet** [notepad-plus-plus/notepad-plus-plus#8035]
I wanted to configure npp to use JavaScript language for JSON because it has better styling, I guess I could copy styles from JS to JSON via style configurator, but I still think this is a bug.

Put JOSN into disabled
![image](https://user-images.githubusercontent.com/2981715/76556409-770d7080-6467-11ea-8a5e-0694fffcac0b.png)

Menu does not have the item, this is ok
![image](https://user-images.githubusercontent.com/2981715/76556425-82f93280-6467-11ea-9905-f06e863ae66a.png)

but still styling from JSON
![image](https://user-images.githubusercontent.com/2981715/76556781-32cea000-6468-11ea-9e4e-5360a51dc54e.png)

And even if I add json extension to JavaScript still defaults to JSON

![image](https://user-images.githubusercontent.com/2981715/76556856-572a7c80-6468-11ea-8ce9-e08a59fe9c7f.png)

**Comment by ArkadiuszMichalski** [comment]
Similar to https://github.com/notepad-plus-plus/notepad-plus-plus/issues/8035. To change it you have to edit the `langs.xml` file and remove / change the extension for JSON to another.
