### ISSUE TITLE
BUG: Find in files directory resets

### ISSUE THREAD

**Issue by LolHacksRule** [notepad-plus-plus/notepad-plus-plus#8036]
### Description of the Issue

When searching in a directory, finishing/cancelling and going back to find in files resets the past directory I searched in to the one that happened before.

### Steps to Reproduce the Issue

1. Delete AppData/Roaming/Notepad++
2. Delete all plugins

### Expected Behavior

The current directory to still be present when going back to find in files.

### Actual Behavior

Example: Searching in MyDir2 resets it to MyDir1

### Debug Information

Notepad++ v7.8.4   (32-bit)
Build time : Jan 29 2020 - 01:33:47
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS Name : Windows 10 Home (64-bit) 
OS Version : 1607
OS Build : 14393.447
Plugins : ActiveX.dll ComparePlugin.dll CSScriptNpp.dll CsvQuery.dll DSpellCheck.dll HexEditor.dll JSMinNPP.dll LuaScript.dll mimeTools.dll NppAutoIndent.dll NppConverter.dll NppExport.dll NPPJSONViewer.dll nppplugin_ofis2.dll nppplugin_solutiontools.dll Translate.dll XMLTools.dll

**Comment by sasumner** [comment]
>Delete AppData/Roaming/Notepad++

>Expected : The current directory to still be present when going back to find in files.

Roughly translates to:
* Remove Notepad++'s memory of its settings
* Expect Notepad++ to remember its settings

Please, be serious.
