### ISSUE TITLE
[Improvement request]  Completely Replace Scintilla based macro system with pyton or js or vbs or other programming language

### ISSUE THREAD

**Issue by wonkawilly** [notepad-plus-plus/notepad-plus-plus#8037]
Hi @donho and all n++ devs
What about to completely replace the integrated macro system in notepad++ with something more elastic as pyton or vbs or js or other programming language?
For example ms office uses vba for macros that can be recorder and modified in the vba editor.

Notepad saves recorded macros in shortcut.xml file that is good. But the problem is that macros aren't very elastic... for example it is not possible to do a for loop into them or a do while or to use if statements or switch case... etc... For complex things those macros aren't good enough and also their "language" is really cryptic to understand, too far form other standard programming or scripting languages.

Pyton or js or vba or vbs or else are good at doing things (pyton has  some plugins and a console in notepad++) but the problem with them is that we cannot just push a button to "record" some actions done in n++ with keyboard and mouse, save the record and modify the pyton / js / or other code that recording generates. So the ideal solution IMHO would be to have the best of the two worlds: a macro system/framework that allows to record operations done in pyton/js/vbs/or else/ so modifying that automatically and powerful and intuitive code will give a new level of power to all users that use n++.
For example would be great to start with a registration of a macro and then implement some variation by hands coding to add complex behaviors.
I think it would be a game changer for all users abandoning the current macro system that is "archaic" and extremely limited and counter intuitive and not only.
I know it is a big step but I think it worth it.
Thank you in advance for reading and supporting this.

**Comment by sasumner** [comment]
>I know it is a big step but I think it worth it.

Feel free to implement and submit as a PR.  Thanks.

**Comment by wonkawilly** [comment]
> > I know it is a big step but I think it worth it.
> 
> Feel free to implement and submit as a PR. Thanks.

what is the PR?

**Comment by sasumner** [comment]
>what is the PR?

So what you do is fork the codebase (which means basically you get a local copy of the source code).  Then you make the changes to implement the feature you propose (in that local copy).  Then you test the changes and when you're happy it works as intended, you submit a PR (Pull Request) back to Notepad++ to bring your changes into the official codebase, so that, if accepted by the Notepad++ authors, after the next release, ALL Notepad++ users can use your implemented feature.

**Comment by wonkawilly** [comment]
> > what is the PR?
> 
> So what you do is fork the codebase (which means basically you get a local copy of the source code). Then you make the changes to implement the feature you propose (in that local copy). Then you test the changes and when you're happy it works as intended, you submit a PR (Pull Request) back to Notepad++ to bring your changes into the official codebase, so that, if accepted by the Notepad++ authors, after the next release, ALL Notepad++ users can use your implemented feature.

Ok so PR is pull request... thanks... unfortunately I don't have advanced programming skills in general and in particular in c++. 
In fact I can do only simple things, any way not in c++ unfortunately.

**Comment by sasumner** [comment]
Without sufficient resources to complete such a thing, the Notepad++ team is going to have to decline to implement this for now.  However, we thank you for your suggestion.

**Comment by victorel-petrovich** [comment]
@sasumner , could you reopen? other volunteers may one day try to implement such a thing, instead of concluding that the Npp authors are against it.

**Comment by victorel-petrovich** [comment]
could go hand in hand with the ideas here, for a more powerful & general macro system: https://github.com/notepad-plus-plus/notepad-plus-plus/issues/4809#issuecomment-3239606439
