### ISSUE TITLE
Becomes unresponsive at exit

### ISSUE THREAD

**Issue by maemmott** [notepad-plus-plus/notepad-plus-plus#8038]
### Description of the Issue
I've reached the point where notepad++ can't be closed, and won't "get out of the way" except by shutting down Windows.

Today, I got a hint as to why.  I tried to close notepad++ from its taskbar icon > right-click > close.  Instead of closing, it leapt to the top, and a recently edited, unsaved tab became the topmost tab.

What didn't happen, was a little message window didn't open saying, 'would you like to save this unsaved document?'

So I did the usual: hunt in the alt-tab sequence for that message box.  But ... it wasn't anywhere in the alt-tab sequence.

I tried it again, while trying to fill in this report.  As one last try, I tried setting the cursor in the open document and typing.  The cursor didn't flash, but the new typing 'forced' a 'Save As' dialog to show itself.  The typing I had already done, appeared in its 'File name:' field.

### Steps to Reproduce the Issue

1.   Have several unsaved documents open in different tabs
2.   Open a new one.  Write some text into it.  DO NOT SAVE IT.
3.   Let notepad++ lose the focus.  Work in Visual Studio for some hours.
4.   in the taskbar, right-click notepad++'s icon > choose 'Close window' --> notepad++ gets the focus; there are no clickable buttons, and no message window can be found in the alt-tab sequence
5.   if you start typing, after a moment or two, a 'Save As' dialog shows itself, with your typing in the 'File name' field.

### Expected Behavior

notepad++ closes

### Actual Behavior

notepad++ sits 'in the way' and 'unresponsive', but can be forced to reveal an otherwise un-find-able 'Save As' box by the user 'typing at the keyboard'.

### Debug Information

Notepad++ v7.8.5   (32-bit)
Build time : Mar  4 2020 - 11:04:20
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS Name : Windows 10 Enterprise (64-bit) 
OS Version : 1909
OS Build : 18363.657
Plugins : CSScriptNpp.dll HTMLTag_unicode.dll ImgTag.dll JSLintNpp.dll JsMapParser.NppPlugin.dll JSMinNPP.dll mimeTools.dll NppConverter.dll NppExport.dll NPPJSONViewer.dll NppTextFX.dll XMLTools.dll

**Comment by dail8859** [comment]
Unfortunately leaving it for "some hours" is not a reasonable way to reproduce the issue. To many other factors could affect it...network connections, file updates, plugin interactions, etc. 

I would recommend disabling your plugins and try to find a clear and easy way to reproduce the issue.
