### ISSUE TITLE
Find-in-Files "Follow current doc" not working when absolute Default Directory set

### ISSUE THREAD

**Issue by sasumner** [notepad-plus-plus/notepad-plus-plus#8045]
### Description of the Issue
When a *Default Directory (Open/Save)* setting is set to be an absolute folder path (the 3rd of 3 radio buttons) in *Preferences* > *Default Directory* > *Default Directory (Open/Save)*, the *Follow current doc.* checkbox on the *Find in Files* tab of the *Find* window DOES NOT work to change the *Directory:* box value for *Find in Files*.  The *Directory:* box value is always set to the chosen absolute path in the *Preferences*.

### Steps to Reproduce the Issue

1. Open *Preferences* > *Default Directory* and tick the 3rd (lowest) of 3 radio buttons, and provide an absolute path, for example: `W:\`
2. Open a file on C: drive, for example, `readme.txt` that comes with Notepad++
3. Invoke *Find in Files* by pressing Ctrl+Shift+f
4. Tick the *Follow current doc.* checkbox on the *Find in Files* tab.  Or, tick and untick it  a few times, and observe that the C: drive folder path of `readme.txt` _NEVER_ appears in the *Directory:* box, as it should.

### Expected Behavior
The folder path of the active file in the editor should appear in the *Directory:* box after an untick/tick cycle of *Follow current doc.*

### Actual Behavior
The correct folder path never appears in *Directory:*.

### Debug Information
Notepad++ v7.8.5   (32-bit)
Build time : Mar  4 2020 - 11:04:20
Path : C:\.......\npp.7.8.5.bin\notepad++.exe
Admin mode : OFF
Local Conf mode : ON
OS Name : Windows 10 Enterprise (64-bit) 
OS Version : 1809
OS Build : 17763.973
Plugins : mimeTools.dll NppConverter.dll NppExport.dll 

### Relevant Screenshots

![image](https://user-images.githubusercontent.com/30118311/76798363-d2ac6680-67a5-11ea-8479-57d6697be522.png)

![image](https://user-images.githubusercontent.com/30118311/76798371-d6d88400-67a5-11ea-8730-56e7c399a1a2.png)

### Additional information
Even if the *Preference* settings is moved away from the 3rd (bottommost) absolute path setting for *Default Directory (Open/Save)*, if there is **ANY TEXT** at all in the box to the right of this bullet, then the *Follow current doc.* checkbox on the *Find in Files* tab of the *Find* window DOES NOT work to change the *Directory:* box value for *Find in Files*.

**Comment by missionfloyd** [comment]
It seems to use the open/save dialog folder. If you open a file with the Open dialog It'll work (unless you open another file in a different folder afterwards), but not if you open a file by right clicking it or dropping it on the window.

**Comment by abdulbadii** [comment]
this notepad++ fixed: https://github.com/abdulbadii/notepad-plus-minus
we try to improve

**Comment by sasumner** [comment]
@abdulbadii Please don't post links to forked versions here.

**Comment by mere-human** [comment]
A similar problem was reported on the forum:
https://community.notepad-plus-plus.org/topic/21670/bug-form-find-in-files-checkbox-folder-of-current-doc-set-invalid-path
