### ISSUE TITLE
Find in Files Search Results Copy broken

### ISSUE THREAD

**Issue by SteveB360** [notepad-plus-plus/notepad-plus-plus#8047]
### Steps to Reproduce the Issue

1. perform Search\Find in Files
2. in results window select all\copy
3. paste excludes the file path

### Expected Behavior

expected select all/ccopy to include the file path and the hits within the file

### Actual Behavior

Select all/Copy is not including the file paths

### Debug Information

Notepad++ v7.8.4   (32-bit)
Build time : Jan 29 2020 - 01:33:47
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS Name : Windows 7 Enterprise (64-bit) 
OS Build : 7601.0
Plugins : CodeAlignmentNpp.dll ComparePlugin.dll DSpellCheck.dll mimeTools.dll NppCalc.dll NppConverter.dll NppExport.dll

**Comment by sasumner** [comment]
Left click in "Find result" window.
Press ctrl+a.
Press ctrl+c.

**Comment by SteveB360** [comment]
Are you saying behavior is different with short cut keys than right click
context menu?

**Comment by sasumner** [comment]
> behavior is different with short cut keys than right click
context menu?

Yes.
