### ISSUE TITLE
Autocompletion dropdown covers the written text

### ISSUE THREAD

**Issue by paweku123** [notepad-plus-plus/notepad-plus-plus#8048]
### Description of the Issue

I am running Notepad++ on Ubuntu 18.04 lts.
When I write something I encounter strange autocompletion issues.
The appearing dropdown has a dark box above suggestions that covers the text that I write.
You can see that in the image below.

![image](https://user-images.githubusercontent.com/61761088/76886128-9e59a880-6880-11ea-9fe0-fd336eaa8619.png)

### Debug Information

Notepad++ v7.8.5   (64-bit)
Build time : Mar  4 2020 - 11:08:34
Path : Z:\home\pawel\snap\notepad-plus-plus\227\notepad-plus-plus\notepad-plus-plus.exe
Admin mode : ON
Local Conf mode : OFF
OS Name : Microsoft Windows 7 (64-bit) 
OS Build : 7601.0
WINE : 3.0.4
Plugins : mimeTools.dll NppConverter.dll NppExport.dll NppTextViz.dll 

"Notepad-Plus-Plus (WINE)" application installed from Ubuntu Software

Possibly same issue found here: https://askubuntu.com/questions/1051017/notepad-has-problems-with-text-autocompletion-under-wine

edit
installing with `snap` gives the same result

**Comment by sasumner** [comment]
We really can't spare the cycles to support Notepad++ running on non-Windows platforms, but this issue can remain here and anyone that sees it and has any workarounds can comment.
