### ISSUE TITLE
Language Style Colour are not respected since NP++ Version 7.8.3 (64bit)

### ISSUE THREAD

**Issue by Raventara** [notepad-plus-plus/notepad-plus-plus#8049]
### Description of the Issue
All language styles are no longer correct. In 7.8.2 they are working but in 7.8.3,4,5 they are incorrect.
Rolling back to 7.8.2 sees them be correct again.
I am using the 64 bit packages from the installer.

### Steps to Reproduce the Issue
Update NP++ beyond 7.8.2 and look at a file with default formatting eg. *.json

### Expected Behavior
The colour highlighting should match the colours seen in the style configurator.
![2020-03-18 12_56_19-C____Style Config](https://user-images.githubusercontent.com/3972144/76919266-54240600-6918-11ea-983a-365c74bd3337.png)

### Actual Behavior
Other colours are selected and the highlighting is all incorrect.
![2020-03-18 12_46_46-Style Configurator](https://user-images.githubusercontent.com/3972144/76919279-5dad6e00-6918-11ea-9c7a-dfbe2ffa9699.png)

### Debug Information
Notepad++ v7.8.5   (64-bit)
Build time : Mar  4 2020 - 11:08:34
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS Name : Windows 10 Pro (64-bit) 
OS Version : 1909
OS Build : 18363.720
Plugins : mimeTools.dll NppConverter.dll NppExport.dll NPPJSONViewer.dll XMLTools.dll

**Comment by fmigneault** [comment]
I'm seeing the exact same behaviour. 
Notepad++ v7.8.5   (64-bit)
Build time : Mar  4 2020 - 11:08:34
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS Name : Windows 10 Pro (64-bit) 
OS Version : 1809
OS Build : 17763.805
Plugins : ComparePlugin.dll MenuIcons.dll mimeTools.dll NppConverter.dll NppExport.dll NPPJSONViewer.dll NppMarkdownPanel.dll XMLTools.dll

**Comment by sasumner** [comment]
This may be of some help:  https://community.notepad-plus-plus.org/topic/19152/recent-update-changes-language-colors/

**Comment by fmigneault** [comment]
Works for me but I had to edit my theme instead of language/style.

**Comment by sasumner** [comment]
@fmigneault 

>but I had to edit my theme

That makes sense.

**Comment by sasumner** [comment]
I'm going to close this issue now.  It's just one of those things where some part of the software was enhanced, with no automatic smooth path for old customizations.
