### ISSUE TITLE
Right hand end of the edit window appears misaligned with outer frame

### ISSUE THREAD

**Issue by 3DWORX-SA** [notepad-plus-plus/notepad-plus-plus#8053]
### Description of the Issue
The right hand end of the edit window appears misaligned with the outer frame of the app due to the border shadow.

### Steps to Reproduce the Issue
1. Open Notepad++ and view the right hand edge of the app where the tab row and the edit window meet, and where the edit window and the status bar at the bottom meet.

### Expected Behavior
The right hand edge should not appear to have a "step" in it.

![Notepad++ bug](https://user-images.githubusercontent.com/32925097/77094461-3092b580-6a15-11ea-88a6-bd3914105f06.jpg)

**Comment by sasumner** [comment]
Minor UI issue; noted.
