### ISSUE TITLE
Clarify "Other View" rotation actions

### ISSUE THREAD

**Issue by MortenBroerup** [notepad-plus-plus/notepad-plus-plus#8058]
### Description of the Issue

When using two views, "Clone to Other View" or "Move to Other View", a bar separates the two views. Right-clicking the separation bar brings up a menu with two options: "Rotate to right", "Rotate to left".

I often get it wrong, so I suggest changing the two options to "Rotate clockwise" and "Rotate counter-clockwise".

**Comment by alankilborn** [comment]
To me, "Rotate to right" implies this:

![image](https://user-images.githubusercontent.com/77065706/183100613-6e468a1f-d4bb-4101-ad7e-52e634680b4b.png)

and that's exactly what will happen when the action occurs.
This is consistent in all window arrangements.
Similar for "Rotate to left".

So I think the existing notation is good enough.

Recommend CLOSURE of this item.

**Comment by alankilborn** [comment]
@pryrt
Do you think the manual is adequate for this, or some buffing up there would help ease the OP's (and other) mind here?

**Comment by pryrt** [comment]
It currently only says,
> To change the arrangement of the Views, right-click on the dotted bar between the two Views, and **Rotate Right** or **Rotate Left**, which will change the orientation from side-to-side to above-and-below.

So that does leave some room for adding clarification, since it doesn't explain the sequence.  I'll work on that.
