### ISSUE TITLE
To allow click in right click context menu with right click & XCV shortcuts

### ISSUE THREAD

**Issue by ahhmedbilal** [notepad-plus-plus/notepad-plus-plus#8060]
Like Chrome allow to click with right click in "right click context menu", notepad++ should also allow the same. e.g in chrome when i right click, then i can also click on "open in new tab" with right click. this is very convenient and produce less strain on finger. 

Ctrl + XCV are universal short cut for cut, copy paste. in same way the key X and C and V should be the shortcut key in right click context menu for cut, copy and paste. e.g when i select a text and right click, then i should be allowed to press C to copy the text. in same way when i right click, then on pressing V, i should be able to paste the text. this is also very convenient and speed up the work.

Thanks

**Comment by ahhmedbilal** [comment]
will create new one

**Comment by sasumner** [comment]
Why did you close this only to open an identical one ( #8061 ) ?
