### ISSUE TITLE
Hangs for few minutes when changing line ending

### ISSUE THREAD

**Issue by Hoween** [notepad-plus-plus/notepad-plus-plus#8062]
### Description of the Issue
When changing line ending, NPP become unresponsible for few minutes. Then it recovers and works normally.

### Steps to Reproduce the Issue
1. Open a file with CRLF line ending (e.g. film subtitles).
2. Through Edit - EOL conversion change line ending to LF.
3. NPP freezes for few minutes, then it unfreezes and encoding is changed.

### Expected Behavior
Should works immediatelly.

### Actual Behavior
Freezes for few minutes. Previous versions works like a charm.

### Debug Information
Notepad++ v7.8.5   (32-bit)
Build time : Mar  4 2020 - 11:04:20
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS Name : Windows 10 Enterprise (64-bit) 
OS Version : 1909
OS Build : 18363.720
Plugins : ccc.dll DSpellCheck.dll JSLintNpp.dll JSMinNPP.dll mimeTools.dll NppConverter.dll NppExport.dll NPPJSONViewer.dll NppXmlTreeviewPlugin.dll XMLTools.dll

**Comment by sasumner** [comment]
Can you upload a file that produces this behavior?

**Comment by Hoween** [comment]
Sure.
[Better-Call-Saul-S05E04(0000327350).zip](https://github.com/notepad-plus-plus/notepad-plus-plus/files/4362841/Better-Call-Saul-S05E04.0000327350.zip)

**Comment by sasumner** [comment]
Converting line endings on that .srt runs reasonably (noticeable delay but under 1 second) for me.
Perhaps you could try it without the plugins being installed?

**Comment by Hoween** [comment]
Yes, without plugins it works great. After few tries it seems problem is in XMLTools plugin. Thanks, I'm closing this issue.
Saul? Don't know, I'm currently in the middle of season four, but coronavirus situation will greatly accelerate my watching :)
