### ISSUE TITLE
Auto Insert Bug

### ISSUE THREAD

**Issue by kingphantom** [notepad-plus-plus/notepad-plus-plus#8063]
### Description of the Issue

The user defined auto insert settings do not save.
### Steps to Reproduce the Issue

1. Create a user defined auto insert.
2. Close notepad++ one or more times and the setting you made is eventually wiped.
3. 
### Expected Behavior

Notepad++ to save the custom auto insert I made.
### Actual Behavior

The auto insert I created is not saved properly and eventually gets deleted.

### Debug Information

I checked the config.xml for notepad++. I see the auto inserts and anything a user adds. The user auto inserts eventually are removed from the config though.

**Comment by dail8859** [comment]
Can you provide a "user defined auto insert"? I'm not sure I understand exactly.


Also, please provide your Notepad++ debug information under the `?` menu.

**Comment by kingphantom** [comment]
Notepad++ v7.8.5   (32-bit)
Build time : Mar  4 2020 - 11:04:20
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : ON
Local Conf mode : OFF
OS Name : Windows 7 Home Premium (64-bit) 
OS Build : 7601.0
Plugins : combine.dll ComparePlugin.dll DSpellCheck.dll JSMinNPP.dll mimeTools.dll NppBplistPlugin.dll NppConverter.dll NppExec.dll NppExport.dll NPPJSONViewer.dll NppSnippets.dll NppTextFX.dll RunMe.dll

The issue is in "Auto-Insert". "Settings->Preferences->Auto Completion->Auto-Insert".

The auto insert section has 3 "Matched Pairs" which are custom auto inserts defined by the user. 

These do not permanently save after being set. After opening the app once or twice, the matched pairs are deleted.

**Comment by dail8859** [comment]
This is how I was able to reproduce the issue.

1. Set custom matched pairs (see image at end). I picked very unique characters
1. Close settings menu.
1. Verify auto-insert works.
1. Close Notepad++
1. Open Notepad++
1. Auto-insert *does not* work.
1. Open settings menu.
1. Verify custom matched pairs are still set
1. Close settings menu
1. Auto-insert now works again.

I could not get it to actually loose the custom settings.

---

![image](https://user-images.githubusercontent.com/3694843/78454538-96627c80-7666-11ea-988a-c16a03bd9c83.png)

**Comment by Ekopalypse** [comment]
I have also tested this and can agree with what @dail8859 has written, with one exception.
When I set the mappings the very first time, tested it, worked and then restarted Npp
they were no longer there. 
Setting it again saved it to config.xml and now shows the same behavior as described by @dail8859,
works only after settings dialog has been started.
