### ISSUE TITLE
A text file shows empty, while it has regular content

### ISSUE THREAD

**Issue by lmatteini-sb** [notepad-plus-plus/notepad-plus-plus#8066]
### Description of the Issue
There's an issue with text files with some special characters, showing as completely empty.
I thought I'd reported it already, as my text examples dates back to 2014, but evidently I didn't.
[error-loading.zip](https://github.com/notepad-plus-plus/notepad-plus-plus/files/4379784/error-loading.zip)

### Steps to Reproduce the Issue
Just open the file "error-loading.c", it will appear as empty. With any other text editor you can see the actual content.

### Expected Behavior
See and edit the actual content

### Actual Behavior
File is shown as empty

### Debug Information
Notepad++ v7.8.5   (32-bit)
Build time : Mar  4 2020 - 11:04:20
Path : C:\Programmi\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS Name : Microsoft Windows XP (32-bit) 
OS Build : 2600.0
Plugins : mimeTools.dll NppConverter.dll NppExport.dll

**Comment by sasumner** [comment]
Here's what the file shows for me:

![image](https://user-images.githubusercontent.com/30118311/77533328-0efa5980-6e6d-11ea-9632-e2fa2b48027c.png)

Clearly not showing as empty...

**Comment by lmatteini-sb** [comment]
> Clearly not showing as empty...

Thanks, then it could just be OS/language related.
The test PC is very old and still running Windows XP, so maybe not worth a bug hunt.
