### ISSUE TITLE
Doc switcher "dirty" icon state does not stay in sync when documents are cloned

### ISSUE THREAD

**Issue by tomlove** [notepad-plus-plus/notepad-plus-plus#8067]
### Description of the Issue
Doc switcher "dirty" icon state does not stay in sync when documents are cloned (split view). 

### Steps to Reproduce the Issue

1. Enable doc switcher (Preferences -> Document List Panel -> Show)
2. Create new document, then right-click and Clone to Other View
3. Start typing. 

### Expected Behavior
Both blue icons in the Doc Switcher panel  should go red

### Actual Behavior
Only one blue icon goes red. 

### Debug Information
Notepad++ v7.8.5   (64-bit)
Build time : Mar  4 2020 - 11:08:34
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS Name : Windows 10 Pro (64-bit) 
OS Version : 1903
OS Build : 18362.592
Plugins : HexEditor.dll mimeTools.dll NppConverter.dll NppExport.dll 

![doc switcher bug](https://user-images.githubusercontent.com/1110275/77538098-d4fa7900-6ea7-11ea-81b9-74ab9e378704.png)

**Comment by sasumner** [comment]
Note: Step 2 in the reproduction leads one to believe that this might happen only for an unnamed/unsaved "new" file, but it will also happen with a saved-to-disk file.

**Comment by Uhf7** [comment]
Remove the `break;` from the **for** loop in `VerticalFileSwitcherListView::setItemIconStatus` to fix it.

**Comment by sasumner** [comment]
@Uhf7 

>Remove the break; from the for loop in VerticalFileSwitcherListView::setItemIconStatus to fix it.

PR?
