### ISSUE TITLE
Accessibility: tabbar saved vs edited vs readonly

### ISSUE THREAD

**Issue by pryrt** [notepad-plus-plus/notepad-plus-plus#8068]
### Description of the Issue

Please: the icons and/or the names on the tabbar need to better indicate saved vs edited vs readonly state.  

Please do **not** reject this out-of-hand.  It's not just aesthetics (though that could be improved) or personal preference; it **needs** to be done.  As mentioned in https://community.notepad-plus-plus.org/topic/19110/different-indicator-for-unsaved-tabs, certain varieties of color blindness make the saved/blue vs unsaved/red icon indistinguishable.  

At the very minimum, the tabbar needs to use the *, just like the title bar use.  But that's the least preferred.  The best solution would be changing the icon on each, to three distinct and easily-recognizable icons.  

I know there's #5666 still open, but this takes it farther.
I know PR #5890 was rejected because the orange color looked weird.
I know PR #5097 was rejected because "it looked different"

Instead of rejecting outright, please work with the Community to find an acceptable solution, because this is an issue of accessibility.

The point is to make them all look as different as possible, to make it easy for everyone (colorblind or not) to quickly recognize the difference between saved, edited, and readonly.  Combing different icons with different colors is the best combination, which is better for everyone.

Doing something like Blue Disk (or Green Disk, or Green Checkmark if you are bold enough for not making tradition dictate an out-of-date icon -- who uses 3.5" floppies?!) for saved, Red Lock (or yellow or orange or whatever color doesn't look weird) for readonly, and Red Pencil for edited.

This would make it easier to distinguish, at a glance, for everyone.

If you don't like the exact suggestions, work with us to find alternatives that _do_ work.  I bet @SinghRajenM  would be willing to implement whichever suggestion gets consensus and do a new PR, or someone could at least start from those PRs as a basis, and tweak it to match what's agreed upon.

If changing the icon is absolutely unacceptable (which seems strange, since the icon changes to a creepy eyeball when the file is in "monitoring (tail -f)" mode), then at the very minimum, implement three different states in the text of the  tabbar: maybe `*` or `(*)` for edited and `(x)` or `(ro)` for readonly; or, if Unicode characters are allowed, 🔒 U+1F512 LOCK for readonly and ✎ U+270E LOWER RIGHT PENCIL (or one of the other pencil characters) for edited.  But really, icons with different shapes is the best solution for everyone.

**Comment by sasumner** [comment]
Upon first read, I have to give this a +1 ... or a +10, +100, ...  

I also have to give a nod to "creepy eyeball".  Personally, I don't think it is overly "creepy", but just someone calling it that is LOL funny.

My only truly valuable contribution might be to say:  It surely seems like the contents of the window entitled "Doc Switcher" need to lockstep-follow any changes made to the "tab bar" in this regard. 

In the existing implementation there are a few discrepancies; perhaps the most notable is that when a tab in the tab bar gets the "creepy eyeball" icon, in the "Doc Switcher" it gets the grey/readonly icon -- which makes sense I suppose -- but why not the "creepy eyeball" there too?

**Comment by sasumner** [comment]
Closing this "master" issue after splitting into three separate issues, so they can be accepted or rejected on an individual basis.

Not as much detail as above was put into the individual issues; one can always refer back to this issue as the most complete reference.

**Comment by sasumner** [comment]
An additional negative aspect of all 3 existing icons is that they overlap the "active tab indicator" which is by default orange in color but has been made red for additional clarity here in a blow-up screenshot:

![image](https://user-images.githubusercontent.com/30118311/77653367-f27e2000-6f45-11ea-832f-d2d6b90b25eb.png)

A bit of space between the colored indicator and the icon itself might be more attractive looking.

**Comment by SinghRajenM** [comment]
> I bet @SinghRajenM would be willing to implement whichever suggestion gets consensus and do a new PR

@pryrt my gratitude, I have stopped looking into Notepad++ repo long back. But yes, it is good to see if anyone's solution is accepted.

**Comment by sasumner** [comment]
>A bit of space between the colored indicator and the icon itself might be more attractive looking

I tried a solution where there was a bit of such space.  It looked good!

Unfortunately, if I unticked *Reduce* in the Preferences, with the larger tabs and icons the overlap  returned. :-(

**Comment by sasumner** [comment]
So this is actually kind of a difficult thing to "solve" acceptably.  When adding in end-user personal preference, it is probably impossible to make everyone happy. :)

Some of the challenges; one needs to consider, simultaneously, the impact of any new icons to:

* active versus inactive tab
* _Reduce_ 'd versus non-reduced tab choice
* _Darken_ 'ed versus non-darkened tab choice
* _Doc Switcher_ (because it uses the same icons as the tab bar)
* theme selection (needs to be workable in the spectrum from the brightest theme [e.g., the default theme] to the really dark themes)

After putting some amount of time in, I've arrived at a suggestion for three new icons for this purpose.

If "product continuity" is a strong factor, perhaps the existing "saved" icon (blue floppy disk) can be retained, and only the other two adopted.

Or perhaps everything is rejected, as too radical of a change; although this course of action would do nothing to help color-impaired persons, obviously.

In the case of rejection, I will present a method for scripting installation of new icons using "Resource Hacker" ( http://www.angusj.com/resourcehacker/ ).  This will allow anyone to easily enable their Notepad++ to use the proposed icons (or any appropriately sized icons of their choice) on a "patch-the-exe" basis.

Further individualized comments (and especially screenshots) are found in the PRs (or issues) for the three daughter issues.

**Comment by sasumner** [comment]
I'll be submitting the 3 PRs for the daughter issues soon, but here's a preview of what I came up with, first non-Reduce'd:

![image](https://user-images.githubusercontent.com/30118311/77974467-3ca82e00-72c5-11ea-8f46-6a47e02b678a.png)

and then Reduce'd:

![image](https://user-images.githubusercontent.com/30118311/77974481-4a5db380-72c5-11ea-8a85-e198e7d47695.png)

**Comment by sasumner** [comment]
Sorry for the schizophrenia with the daughter/parent issues; the thinking was it might be easier to judge each proposed icon on its own merits individually; thus the reason for the 3 daughter issues to THIS main issue.

Now that @donho has weighed in and requested a "color blind" "icon set" preference (not that we'll call it that), I think this is better as a SINGLE issue, so I'm closing the "daughters" and reopening THIS one, the parent.

**Comment by sasumner** [comment]
@pryrt What do you think of the looks of the icon set presented above?  In particular, what about the green-check-mark (for a saved file)?  I was wondering if it would be better to keep the diskette icon for that one, possibly making it green instead of blue?  I just like green for saved; blue infers, well, nothing.  If we only have ONE diskette icon in the group, we still get the non-color differentiation with the different shapes.

**Comment by pryrt** [comment]
I think yellow/red/green makes more sense than yellow/red/blue, and I think the checkmark makes more sense.  Since this is now supposed to be just an alternate icon set, rather than the only icon set, I don't think we need to be as tied to the historical diskette icon, so I'd vote for checkmark, not disk.

**Comment by donho** [comment]
@sasumner Hmm... Strangely, not on my PC (I don't deliver my PC  though, I know)

![image](https://user-images.githubusercontent.com/90293/78194751-4d4fd400-747e-11ea-8ade-7ed0200dc432.png)

**Comment by sasumner** [comment]
@donho Interesting.  It actually seems to come and go for me; sometimes I see it, sometimes I don't.  Strangel

**Comment by donho** [comment]
Greek check, red pencil and lock are OK for the optional  new set icons. However this set look quit terrible. I will check and try to find another ones.
The option is not necessarily named "Color blind", if you find a better term.

**Comment by donho** [comment]
Here are 4 icons from the same style set of icons used by Notepad++:
http://www.famfamfam.com/

![lock](https://user-images.githubusercontent.com/90293/78197680-58a6fd80-7486-11ea-9678-875dcfed98f5.png)
![pencil](https://user-images.githubusercontent.com/90293/78197682-59d82a80-7486-11ea-95df-5b84959d1381.png)
![check1](https://user-images.githubusercontent.com/90293/78197683-59d82a80-7486-11ea-8e3b-95fdc9b86344.png)
![check2](https://user-images.githubusercontent.com/90293/78197684-5a70c100-7486-11ea-8e1f-7adf1dde4f7d.png)

I provide 2 Check icons so we can check which one have the better visual experience.
The pencil will be red - I'll work on it.

**Comment by sasumner** [comment]
@donho said:

>this set look quit terrible

:-(

I didn't think they were _THAT_ bad.  :-)
But the icons are subjective, and as long as they provide the visual differentiation, the exact ones don't matter.
However, I do think the green checkmark without the circle is more visually defining.

I'll assign myself to work on the code itself.

**Comment by sasumner** [comment]
@donho said:

>Hmm... Strangely, not on my PC (I don't deliver my PC though, I know)

I think I tracked down why **_sometimes_** the icon is so large that it touches the active tab indicator, like this here (and as shown previously above):

![image](https://user-images.githubusercontent.com/30118311/78400060-03710600-75c4-11ea-8cf3-ada39b35f584.png)

The difference is if you start N++ while *Reduce* is not active (in which case you will get the situation of the screenshot ABOVE), versus changing the setting while it is running.  If you are starting N++ with *Reduce* unticked from the last run, things are too big and you get the overlap.  

From an already running Notepad++, going to Prefs and ticking-and-unticking *Reduce* will provide a much better look for the (un-Reduce'd) icon (i.e., no overlap):

![image](https://user-images.githubusercontent.com/30118311/78400446-bb061800-75c4-11ea-8f6d-60dbc997265b.png)

We can fix this by running the code consistent code at startup and when user alters preferences.

**Comment by sasumner** [comment]
It is probably best to implement a fix for #8109 before attempting a fix of this issue.

**Comment by dyura** [comment]
I would like to add something to PeterCJ suggestions. I agree that different pictures on tab icons will be the best solution. However, the implementation may take some time. Just the design of the new icons will take a lot of time, given the attention to the graphic style. Implementing three different states in the text of the tabbar can be an immediate solution, For example, Scite editor adds "*" on the tab when the buffer is dirty  and the pipe-sign "|"  when the buffer is read-only. Scite indication works fine. Then, people can stop recompiling the editor using their icons every time a new version is released, as indicated in  #5666 . After creating a new set of icons, the code can be reverted or left  as an additional indication. I don't see any harm in this.

**Comment by sasumner** [comment]
>the design of the new icons will take a lot of time

Not really.  That part is currently done; the remainder is still in-progress.

>Scite editor adds ... the pipe-sign "|" when the buffer is read-only
>After creating ... new ... icons, ...can be left as an additional indication.

It's an OK idea.
I would think, if it is done, it would remain, even after new icons are added.

>people can stop recompiling the editor using their icons every time a new version is released

People really do this, currently?

**Comment by dyura** [comment]
some people do.

**Comment by sasumner** [comment]
>some people do.

Thank you for that information and your comments.
You interest helps prioritize unfinished tasks.

**Comment by pryrt** [comment]
@sasumner ,

It's not technically a "recompile", but with a recent [forum post](https://community.notepad-plus-plus.org/topic/19983) asking about better icons for the tabs, it was suggested to use a resource hacker to replace icons, and a detailed enough procedure that it's probably feasible for many users to implement.  That means the number of people "in the wild" who are actively changing those icons is likely to increase, and since the number of requests to the forum is a tiny fraction of the people "in the wild" who would like such a thing...

All this to say, I felt it was time to "bump" this issue again. :-)

**Comment by sasumner** [comment]
@pryrt

>I'd prefer for the good icons to come with Notepad++ by default

Yea, me too.
I have worked on this one sporadically, but because of another bug (8109), and the fact that these icons are tied into a few places (not just the tab bar, but in Document List Panel, as well as the Ctrl+Tab Doc Switcher), it has proved an involved task, with a fair amount of code.
I could probably do it in a cheezy way, by having the Preference setting for it be one of those `(must restart N++)` ones, but I was hoping to avoid it.  Maybe it wouldn't be that bad that way...  Hmmm...

**Comment by donho** [comment]
@sasumner 
> The difference is if you start N++ while Reduce is not active (in which case you will get the situation of the screenshot ABOVE), versus changing the setting while it is running. If you are starting N++ with Reduce unticked from the last run, things are too big and you get the overlap.

It's a bug - What You See Should Be What you Get After Restart.

**Comment by sasumner** [comment]
@donho 

>It's a bug 

Is it worth creating an issue for, or maybe one already exists?

**Comment by donho** [comment]
@sasumner 
Just created:
https://github.com/notepad-plus-plus/notepad-plus-plus/issues/8929
