### ISSUE TITLE
Open File doesn't use current directory

### ISSUE THREAD

**Issue by DougALug** [notepad-plus-plus/notepad-plus-plus#8069]
### Description of the Issue

When pressing Ctrl-O to open a new file. N++ no longer goes to the current directory, but some other directory when Visual Studio 2019 is opened as well.

### Steps to Reproduce the Issue

1. Open VS2019, and N++
2.  Have 3 or 4 tabs open in N++. For instance, have a file named C:\Example\foo.txt opened
3. In Settings->Preferences->Default Directory, set to 'follow current document'
4. Press Ctrl-O and it won't open to the directory that the file is in (In this case C:\Example)

### Expected Behavior

I would expect the file open to go to the directory that the file originated in .. i.e. C:\Example

### Actual Behavior

It opened to another file that was opened earlier by Visual Studio, but not even what was currently in VS 2019. Super strange. I also have VS 2010 on my machine, and I think the folder is the last one I opened is VS 2010.  BTW this doesn't happen when using VS 2010 or VS 2016. 

### Debug Information

INotepad++ v7.8.5   (32-bit)
Build time : Mar  4 2020 - 11:04:20
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : ON
Local Conf mode : OFF
OS Name : Windows 7 Professional (32-bit) 
OS Build : 7601.24546
Plugins : AutoCodepage.dll ComparePlugin.dll DSpellCheck.dll HexEditor.dll mimeTools.dll NppConverter.dll NppExport.dll NppMarkdownPanel.dll NppTextViz.dll ScrollPastEOFUni.dll SessionMgr.dll SourceCookifier.dll VisualStudioLineCopy.dll

**Comment by sasumner** [comment]
Can you humor me and post a screenshot of what your version of this looks like?:

![image](https://user-images.githubusercontent.com/30118311/77581510-34f71c80-6eb4-11ea-94d4-68cdf948c80c.png)

**Comment by DougALug** [comment]
![Screenshot 2020-03-25 17 28 31](https://user-images.githubusercontent.com/62670538/77587372-2150b380-6ebe-11ea-9049-ba85ea90ac0c.png)

**Comment by sasumner** [comment]
Ok, well that shoots my theory to pieces.  Sometimes when you have text in the third bullet's box, Notepad++ can use that data even if the *Follow current document* radio button is active.

**Comment by DougALug** [comment]
Yeah: this one is strange. It is like there is some quirky interaction between VS2019 and N++.

**Comment by sasumner** [comment]
Any additional information or examples you could provide would likely be helpful.  I have access to VS2019, but have been unable to reproduce anything like what you are seeing so far...

**Comment by DougALug** [comment]
Okay.... so I went to reproduce it... and it has gone away. Now it is working normally. I guess close it. But I promise for the past 2 days it has been wonky.

**Comment by sasumner** [comment]
If and when it recurs, you can always come back to this issue.  :-)
