### ISSUE TITLE
Macro does not update screen

### ISSUE THREAD

**Issue by foreachthing** [notepad-plus-plus/notepad-plus-plus#8073]
### Description of the Issue
After playing the macro (below) it does not go to end of document.
If I key in this macro manually, it does what it should.

It becomes quite obvious, if the macro is mapped to a key combination. It then jumps to the _first_ line of the document!

### Steps to Reproduce the Issue
Record this macro:
1. Reload document (my key: F2)
1. go to end of doc (CTRL+END)
Stop recording - edit doc in other program - press play.

### Expected Behavior
Reload doc, then go to last line.

### Actual Behavior
Reloads doc, does not go to last line (or screen is not updated).
Cursor is at the correct position - screen's not.

### Debug Information
Notepad++ v7.8.4   (32-bit)
Build time : Jan 29 2020 - 01:33:47
Path : C:\Users\USERNAME\MyProgramme\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS Name : Windows 10 Enterprise (64-bit) 
OS Version : 1809
OS Build : 17763.914
Plugins : BetterMultiSelection.dll CodeAlignmentNpp.dll ComparePlugin.dll docMonitor.unicode.dll DSpellCheck.dll Explorer.dll MenuIcons.dll mimeTools.dll MultiClipboard.dll NppCalc.dll NppConverter.dll nppcrypt.dll NppExport.dll NppFavorites.dll NppQCP.dll NppQrCode32.dll NppTextFX.dll OpenSelection.dll Python Indent.dll XBrackets.dll XMLTools.dll

**Comment by sasumner** [comment]
Could not reproduce with same base setup, but with only default plugins.

Can you remove all plugins except the ones that ship with Notepad++ and then try again?

**Comment by foreachthing** [comment]
Hi!
Unfortunately no different behavior!

### Debug Info
Notepad++ v7.8.4   (32-bit)
Build time : Jan 29 2020 - 01:33:47
Path : C:\Users\USENAME\Desktop\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS Name : Windows 10 Enterprise (64-bit) 
OS Version : 1809
OS Build : 17763.914
Plugins : none

**Comment by sasumner** [comment]
Do you have "word wrap" turned on?
View menu -> Word wrap

**Comment by foreachthing** [comment]
> Do you have "word wrap" turned on?

You bet!
[please wait] ... dang it! That's it!
But ... I _need_ word wrap! :-\

**Comment by sasumner** [comment]
I think the problem you are seeing has the same root cause as this known issue:  #8007

**Comment by foreachthing** [comment]
Jup, that sounds right. Thanks!
Closing here.
