### ISSUE TITLE
[Feature Request] Line Numbering

### ISSUE THREAD

**Issue by rjh6v** [notepad-plus-plus/notepad-plus-plus#8075]
Request the option of starting line numbering at 0 (instead of 1).  

I use Notepad++ to edit memory maps that start a address 0.  With line numbers starting at 1, I'm always having to subtract 1 to determine the actual memory address.

**Comment by sasumner** [comment]
There is already an existing plugin that can do this, but since I can't remember the name of it, I'm not going to close this issue until someone provides the name. :-)

**Comment by rjh6v** [comment]
Thanks

**Comment by rjh6v** [comment]
Found it.  Plugin Custom Line Numbers lets you set a starting line number and display them in Hex.  Exactly what I needed.
