### ISSUE TITLE
Enhancement request - additional font sizes please.

### ISSUE THREAD

**Issue by ineuw** [notepad-plus-plus/notepad-plus-plus#8079]
### Description of the Issue
Missing font sizes like 12.5, 13, etc. 
Allow users to set their own font sizes. Or, add the missing sizes, If so, I hope that half sizes like 12.5, 13.5, .... etc. will also be included.

1. Cannot set mono fonts like Courier New to 13 pts.
2. Cannot set proportional font sizes like 12.5 pts.

**Comment by Docteh** [comment]
Hi, I'm just poking through all of the issues on here.

Is there anything particularly wrong with the zoom functionality? It does increase the size of the line numbers, but that side effect should be fine if you're just trying to get something smaller than 14 and larger that 11

View -> Zoom
Or hold control and use the vertical scroll on your mouse/touchpad.
