### ISSUE TITLE
Typing character in long file is nightmare

### ISSUE THREAD

**Issue by netbeansuser2019** [notepad-plus-plus/notepad-plus-plus#8080]
### Description of the Issue
I have to rollback to 7.8.1 version from last 7.8.5. If I have big file about 20000 lines about 712 704 bytes and I have tried to type it seems that by each type of character it tries to do some work even I have turn off autocomple from settings. Simply said if you type characters it is shown with delay. If I return to prior version 7.8.1 I cannot see any issue. Seems that even from user interface is not possible to set setting "triggering from x character" as not accept any character in such input box.

### Steps to Reproduce the Issue
1. big file about 20000 lines and about 712 704 bytes
2. type any character

### Expected Behavior
At least no delays between typing and no such long delay even for open "autocomple list".

### Actual Behavior
delay like to say word "one" so typing like o"one"n"one"e"one" and similarly delay even when you remove character "backspace".

### Debug Information
nothing

**Comment by momala454** [comment]
i have also problems with a file 252kb large and 5243 lines
i dont know if previous version works better

**Comment by momala454** [comment]
@netbeansuser2019 i reinstalled the x64 version and it told me i had 32bits version, i thought i had the 64 bits, and now it seems to be fluid again, try that ?

**Comment by netbeansuser2019** [comment]
I do not install anything I have just unpacked as usually. BTW: it is even pure txt file so it is question if it could be in any XML plugin.

**Comment by momala454** [comment]
even in non xml files the plugin is causing slowdown

**Comment by alankilborn** [comment]
Recommend CLOSURE of this item.

**Comment by ArkadiuszMichalski** [comment]
If the problem still exist I will reopen it.
