### ISSUE TITLE
Feature request: Markdown support

### ISSUE THREAD

**Issue by buenalabs** [notepad-plus-plus/notepad-plus-plus#8083]
### Feature Request
Please add markdown to the list of files supported when saving files.

### Steps to Reproduce the Issue

1. Create a new file (*Ctrl+N* or **File** > **New**)
2. Type something
3. Save the file (*Ctrl+S* or **File** > **Save**)
4. Click on the **Save as type:** dropdown (or *Alt+T*)

### Actual Behavior
![the dark ages](https://i.imgur.com/FOQjZqh.jpg)
No markdown option available.

### Expected Behavior
![the future is now](https://i.imgur.com/KkOm2zz.jpg)
There's a markdown option available.

**Comment by Donaldpherman** [comment]
I believe this is scintilla dependent.

**Comment by dogancelik** [comment]
I see #7792 is rejected. It looks like Scintilla [supports Markdown](https://sourceforge.net/p/scintilla/code/ci/default/tree/lexers/LexMarkdown.cxx).
