### ISSUE TITLE
DSpellCheck does not check new text

### ISSUE THREAD

**Issue by lucatrv** [notepad-plus-plus/notepad-plus-plus#8084]
I have Notepad++ v7.8.5 on Windows 7, but this has been happening for a while already (maybe for about 1 year or more, while previously I did not have this issue).

Although I keep "Spell Check Document Automatically" enabled, when I write new text it is not checked. To check all text I need to disable and then re-enable it. When I open a file all text is spell checked.

I have configured multiple languages for DSpellCheck (English USA and Italian), but I do not think this affects the issue because it happens no matter which language I select.

**Comment by sasumner** [comment]
Please locate the issue tracker for the DSpellCheck plugin.  This tracker is for core Notepad++ issues only.

**Comment by chcg** [comment]
@lucatrv DSpell issue queue is at https://github.com/Predelnik/DSpellCheck/issues.

**Comment by lucatrv** [comment]
OK thanks, I opened issue [#208](https://github.com/Predelnik/DSpellCheck/issues/208)

**Comment by lucatrv** [comment]
@chcg it turned out that this issue was due to an old version of DSpellCheck that I had installed, so I had to update it manually. However since DSpellCheck is installed by default by Notepad++, I would have expected with each Notepad++ update to also get an updated version of DSpellCheck (if not the latest one, at least one compatible with the updated version of Notepad++).

**Comment by sasumner** [comment]
>since DSpellCheck is installed by default by Notepad++

DSpellCheck is **NOT** installed by default by Notepad++; 
Here is what is installed with Notepad++ 7.8.6:

![image](https://user-images.githubusercontent.com/30118311/80039708-6a4c5580-84c6-11ea-84de-198b6683bd01.png)

**Comment by lucatrv** [comment]
OK, this was clarified [here](https://github.com/Predelnik/DSpellCheck/issues/208#issuecomment-618549750) finally. As a matter of fact I first installed Notepad++ years ago when DSpellCheck was still installed by default, so now I understand that it was upgraded only until it remained a default plugin. I totally agree with @Predelnik though.
