### ISSUE TITLE
Irish language binary translation

### ISSUE THREAD

**Issue by libCap** [notepad-plus-plus/notepad-plus-plus#8086]
Hello,
Greetings of the day!!
@chcg , @donho 

We have submitted Irish language binary translation on 30th January 2020 and we got a reply from @donho  on 31st January 2020 as don said "Your Irish localization file will be included in the next release. Thank you for your contribution."

Here is a screenshot of email reply 
https://prnt.sc/rqbeg4

We have seen Irish language binary translation which is already added in notepad++ directory, here is the screenshot
https://prnt.sc/rqbnrr

Also, we have checked binary translation page on notepad++ site (https://npp-user-manual.org/docs/binary-translation/) but not found Irish translation file on this page.

we are looking forward to hearing back from you

Thank you

**Comment by chcg** [comment]
@libCap Irish should be available with N++ 7.8.5 release. The input for the website is under https://github.com/notepad-plus-plus/npp-usermanual/blob/master/content/docs/binary-translation.md. So maybe you want to provide a PR also therefore.

**Comment by ArkadiuszMichalski** [comment]
@donho This can be close, you add Irish some time ago.
