### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by FickoDeLux** [notepad-plus-plus/notepad-plus-plus#8088]
Prg crashes by loading any txt file with ".nfo" extention.
[NppDump.zip](https://github.com/notepad-plus-plus/notepad-plus-plus/files/4421218/NppDump.zip)

Windows 10

**Comment by Ekopalypse** [comment]
From the dump it seems that you have the HexEditor plugin installed, give it a try without this plugin.

**Comment by chcg** [comment]
So probably related to https://github.com/chcg/NPP_HexEdit/issues/13.
@FickoDeLux Which version of of HexEdit and N++ do you used? 32 or 64 bit version of N++?

**Comment by FickoDeLux** [comment]
That's right, uninstalling Hex-Editor plug-in did the trick. (32-bit, Hex-Editor.0.9.5)
