### ISSUE TITLE
Feature-Request: extended Reload from disk

### ISSUE THREAD

**Issue by AlBundy33** [notepad-plus-plus/notepad-plus-plus#809]
A Menu-Entry with a shortcut that reloads the file from disk and goes immediately to the end of file would be nice.
--> This would help for watching logfiles.

Alt+R would be a nice shortcut. ;-)

**Comment by NN---** [comment]
Same as #20

**Comment by AlBundy33** [comment]
Not really the same but I added my requests to the issue.

**Comment by dail8859** [comment]
Couldn't you just record a macro that reloads the file then does `Ctrl + End`?

**Comment by AlBundy33** [comment]
Macro works of course but the goal is to have the shortcut and functionality out-of-the-box. 

Auto reload is disabled by default in my installations because it's to annoying when switching between logfiles.

**Comment by dail8859** [comment]
The whole point of having the ability to record macros is to make as much as possible *not built in* and just allow the user to extend the functionality to meet their needs.

**Comment by AlBundy33** [comment]
Another solution would be to have a special config-folder where you can store different xml files with different settings. 

E.g. one file with the macro defnition and the assigned shortcut. Antother file with the setting to disable autoreload. And another file to set german as default language. 

With such a structure setting up a new installation would be very easy and because of the standalone files sharing with others would be easy too.
