### ISSUE TITLE
unix EOL not generated properly for md5sum

### ISSUE THREAD

**Issue by superbonaci** [notepad-plus-plus/notepad-plus-plus#8091]
### Description of the Issue

I've created a md5 file with Windows, then I try to convert it to unix end of line, because md5sum only works that way. The problem is, the conversion done by Notepad++ is not accepted by md5sum, says:
````
md5sum: testing.md5: no properly formatted MD5 checksum lines found
````

### Steps to Reproduce the Issue

1. Create the `testing.md5` file under Windows with any native software. Example provided below.
2. Open the file with Notepad++
3. Edit ->EOL Conversion -> Unix (LF)
4. Save
5. Run `md5sum -c testing.md5`, it should display
`md5sum: testing.md5: no properly formatted MD5 checksum lines found`
6. Now run `dos2unix testing.md5` (overwrites same file) and now md5sum works:
`md5sum.exe  -c testing.md5`
`testing.txt: OK`

### Expected Behavior

Convert file to format readable by md5sum

### Actual Behavior

md5sum does not notice the difference.

### Debug Information

````
Notepad++ v7.8.5   (64-bit)
Build time : Mar  4 2020 - 11:08:34
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS Name : Windows 10 Pro (64-bit) 
OS Version : 1909
OS Build : 18363.752
Plugins : DSpellCheck.dll mimeTools.dll NppConverter.dll NppExport.dll 
````

#### How to generate the files for testing:
File to generate checksum from:
````
echo -n '74657374696E670A' | xxd -r -p > testing.txt
````

Checksum file generated by Windows native program, EOL Windows (CR LF):
````
echo -n 'EFBBBF6562316133323237636463336665646261656332666533386266366330343461202A74657374696E672E7478740D0A' | xxd -r -p > testing.md5
````

Now convert to unix EOL (LF) with Notepad++, resulting file is this:
````
echo -n 'EFBBBF6562316133323237636463336665646261656332666533386266366330343461202A74657374696E672E7478740A' | xxd -r -p > testing.md5
````

Now convert the testing.md5 from Notepad++ with dos2unix. This works with `md5sum`. Resulting file is this:
````
echo -n '6562316133323237636463336665646261656332666533386266366330343461202A74657374696E672E7478740A' | xxd -r -p > testing.md5
````

**Comment by sasumner** [comment]
Notepad++'s end-of-line conversion functions are working properly in 7.8.5.

**Comment by superbonaci** [comment]
Thanks that's right. dos2unix performs end-of-line conversions and also encoding conversion to UTF no BOM.
