### ISSUE TITLE
Syntax highlighting lost when exiting compare display

### ISSUE THREAD

**Issue by tppc** [notepad-plus-plus/notepad-plus-plus#810]
I frequently use the compare pluging to compare C source files.
But each time I exit the compare display using 'Clear results', syntax highlight is lost on both compared files. I need to select another language and then switch back to C.

I don't know if the bug is actually in the editor or in the plugin side.
Sorry for my poor English.
Thanks for this great tool.

**Comment by cmeriaux** [comment]
Hello, do you have the issue #800 that might be related to compare plugin ?

**Comment by tppc** [comment]
Hi,
No, I don't have this #800 display refresh issue.
Regards

**Comment by tppc** [comment]
sorry, I didn't mean to close.

**Comment by dail8859** [comment]
It is a bug in the plugin. See #747, plus it looks like on the sourceforge page for the plugin it has been reported.

**Comment by tppc** [comment]
Thanks for this information.
IThanks  was using version 1.5.6.0 of the compare plugin.
This issue was fixed with version 1.5.6.2 
  "  2. FIXED: Syntax highlighting broken after 'Compare' and 'Clear Results' (since N++ 6.2.1) "
Thanks again, sorry for the inconvenience
