### ISSUE TITLE
Word count is double counting words with apostrophes

### ISSUE THREAD

**Issue by nickwerline** [notepad-plus-plus/notepad-plus-plus#8100]
### Description of the Issue
The summary word count is not handling apostrophes (U+0027) correctly. The encoding used is UTF-8. 

### Steps to Reproduce the Issue
1. Type "Adam's" into a blank text document
2. Click "View"
3. Click "Summary..."

### Expected Behavior
Words: 1

### Actual Behavior
Words: 2

### Debug Information
Notepad++ v7.8.5   (32-bit)
Build time : Mar  4 2020 - 11:04:20
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS Name : Windows 10 Home (64-bit) 
OS Version : 1903
OS Build : 18362.535
Plugins : none

**Comment by sasumner** [comment]
In computer terms, words are defined as contiguous runs of A thru Z, a thru z, 0-9, and `_`.  And of course the unicode variants of those.  Apostrophes of any type fall into the non-word bin.  Thus, with `Adam's` we have a run of 4 word characters followed by a non-word character followed by a word character.  Thus two words.
