### ISSUE TITLE
regular expression bug with nth subexpression

### ISSUE THREAD

**Issue by GhbSmwc** [notepad-plus-plus/notepad-plus-plus#8102]
Suppose I have the document only contain these characters:
```
a b
```
With:

- Wrap around checked
- Search mode set to regular expression

I want to swap the two characters, so this works:

Find what: `^(.*) (.*)`
Replace with: `\2 \1`

However, this doesn't work:
Find what: `^(.*) (.*)`
Replace with: `\g{2} \g{1}`
Which that will replace it with literal `\g{2} \g{1}`

Which means if you have more than 9 subgroups and you want to invert each item between spaces, won't work.

The document mentions it here: https://npp-user-manual.org/docs/searching/

**Comment by xylographe** [comment]
See [Perl Format String Syntax · Boost 1.70.0]( https://www.boost.org/doc/libs/1_70_0/libs/regex/doc/html/boost_regex/format/perl_format.html ).

For example (assuming 13 or more sub-expressions), Replace with: `${13} ${9} ${12} $(5}`

**Comment by sasumner** [comment]
@GhbSmwc 

The syntax you are showing is not legal in the *Replace with* box.  Your syntax is only for the *Find with* box where you will refer later to an earlier capture group.  And used this way, it will have no problems with more than 9.

@xylographe is completely right in showing how to do what you are wanting to do.  

His link is relevant to the *Replace with* box.  Here's the companion link for the *Find what* box (which is where you'll find the `\g{` syntax:  [Perl Regular Expression Syntax Boost 1.70.0](https://www.boost.org/doc/libs/1_70_0/libs/regex/doc/html/boost_regex/syntax/perl_syntax.html)

**Comment by GhbSmwc** [comment]
Looks like https://npp-user-manual.org/docs/searching/ is pretty much outdated and forgot to mention which of these meaningful symbols can be used on find what and replace with.

**Comment by sasumner** [comment]
>pretty much outdated 

I wouldn't say it is "outdated".  If you are trying to say it could be improved, then yes, I suppose so. 
 Of course _ALL_ documentation can always be made better.  This can certainly be said of the originating Boost documentation as well.

>forgot to mention which ... used on find what and replace with.

If you go here: https://npp-user-manual.org/docs/searching/#regular-expressions and search for `\g` you will find that notation in `\gℕ, \g{ℕ}, \g<ℕ>`.  Two bullet points below that is `\ℕ ⇒ Backreference: `.  These describe **_Find what_** items we've discussed above.

The substitutions section ( https://npp-user-manual.org/docs/searching/#substitutions ) discusses the valid **_Replace with_** items such as `$ℕ, ${ℕ}, \ℕ`
