### ISSUE TITLE
Unique EOL sequence used by NWS.

### ISSUE THREAD

**Issue by jake9wi** [notepad-plus-plus/notepad-plus-plus#8105]
### Description of the Issue

The United States National Weather Service provides zip files of their text based products (found [here](https://tgftp.nws.noaa.gov/SL.us008001/CU.EMWIN/DF.xt/DC.gsatR/OPS/)). These text files use a unique EOL sequence ('CR CR LF'). This sequence is specified in [NWS Instruction 10-1701](https://www.nws.noaa.gov/directives/sym/pd01017001curr.pdf).

While viewing such a text file NPP interprets the EOL sequence as mac style. As a result extra blank lines are inserted due to the double 'CR CR'.

### Expected Behavior

NPP should not add extra blank lines.

### Actual Behavior

NPP inserts a blank line between lines of text.

### Screenshot
![Annotation 2020-04-11 200242](https://user-images.githubusercontent.com/1775323/79053877-2d63a180-7c30-11ea-9552-929a79bf0ead.png)

**Comment by sasumner** [comment]
The "unique EOL sequence ('CR CR LF')" will not be supported by Notepad++.
