### ISSUE TITLE
Cannot drag and drop files onto tab

### ISSUE THREAD

**Issue by quantuumsnot** [notepad-plus-plus/notepad-plus-plus#8106]
Notepad++ 7.8.5
Windows 8.1 x64

No errors or crashes, just trying to drop the file directly from a dir to the tab-bar and nothing happens

**Comment by sasumner** [comment]
Does the mouse pointer change?

It SHOULD look like 2 small boxes with one having a + sign in it, not exactly but similar to this:

![image](https://user-images.githubusercontent.com/30118311/79078636-b08c0280-7cd7-11ea-9196-d10481b07e8a.png)

But it could look like a small version of this:

![image](https://user-images.githubusercontent.com/30118311/79078594-5ab75a80-7cd7-11ea-88b1-48050bbe2428.png)

Which, if either, do you see when attempting your operation?

**Comment by quantuumsnot** [comment]
> Does the mouse pointer change?
> 
> It SHOULD look like 2 small boxes with one having a + sign in it, not exactly but similar to this:
> 
> ![image](https://user-images.githubusercontent.com/30118311/79078636-b08c0280-7cd7-11ea-9196-d10481b07e8a.png)
> 

Cursor changes to this like in 7.7.1 where d'n'd worked

**Comment by quantuumsnot** [comment]
The bug is still here in 7.8.6

**Comment by quantuumsnot** [comment]
The bug is still here in 7.8.8 and 7.8.9

**Comment by quantuumsnot** [comment]
Debug info for 7.8.8

```
Notepad++ v7.8.8   (64-bit)
Build time : Jun 23 2020 - 23:59:56
Path : D:\scoop\apps\notepadplusplus\current\notepad++.exe
Admin mode : ON
Local Conf mode : ON
OS Name : Windows 8.1 Enterprise (64-bit) 
OS Build : 9600.19431
Current ANSI codepage : 1252
Plugins : mimeTools.dll NppConverter.dll 
```

**Comment by ArkadiuszMichalski** [comment]
@quantuumsnot 
Can you download last 7.9 RC zip version (32- and 64-bit) http://download.notepad-plus-plus.org/repository/7.x/7.9.RC/, and check if problem still exist in both version?

**Comment by quantuumsnot** [comment]
Drag and drop works in 7.9 RC x64
