### ISSUE TITLE
Compile Notepad++ with /guard:cf

### ISSUE THREAD

**Issue by savchenko** [notepad-plus-plus/notepad-plus-plus#8108]
### Description of the Issue
Control Flow Guard is not enabled for `notepad++.exe`

### Steps to Reproduce the Issue
1.  Install latest release (v7.8.5.0 at the time of writing)
2. Check running process with the Process Explorer or use [NetSPI/PESecurity](https://github.com/NetSPI/PESecurity) as following:
```powershell
Get-PESecurity -File 'C:\Program Files\Notepad++\notepad++.exe'

FileName         : C:\Program Files\Notepad++\notepad++.exe
ARCH             : AMD64
DotNET           : False
ASLR             : True
DEP              : True
Authenticode     : True
StrongNaming     : N/A
SafeSEH          : N/A
ControlFlowGuard : False
HighentropyVA    : True
```

### Expected Behavior
`ControlFlowGuard : True`

### Actual Behavior
`ControlFlowGuard : False`

### Debug Information
```
Notepad++ v7.8.5   (64-bit)
Build time : Mar  4 2020 - 11:08:34
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS Name : Windows 10 Pro (64-bit) 
OS Version : 1909
OS Build : 18363.720
Plugins : mimeTools.dll NppConverter.dll NppExport.dll 
```

**Comment by Ekopalypse** [comment]
@asvc - am I right to assume that activating this feature will kick out earlier windows versions than Windows 8.1? By that I mean, once compiled with this flag npp doesn't run on, let's say, on Windows7?

**Comment by asvc** [comment]
Not sure, but I am happy to spin-up Windows 7 VM and try a binary with CFG enabled if that is of a concern.

**Comment by asvc** [comment]
Not sure, but I am happy to spin-up Windows 7 VM and try a binary with CFG enabled if that is a concern.

**Comment by Ekopalypse** [comment]
Maybe to confirm what MS states from [here](https://docs.microsoft.com/en-us/windows/win32/secbp/control-flow-guard)
_We strongly encourage developers to enable CFG for their applications. You don't have to enable CFG for every part of your code, as a mixture of CFG enabled and non-CFG enabled code will execute fine. But failing to enable CFG for all code can open gaps in the protection. **Furthermore, CFG enabled code works fine on "CFG-Unaware" versions of Windows and is therefore fully compatible with them.**_

**Comment by chcg** [comment]
Maybe needs to be checked if this is also necessary to be set for the scintilla dll in https://github.com/notepad-plus-plus/notepad-plus-plus/blob/master/scintilla/win32/scintilla.mak

**Comment by sasumner** [comment]
I'll ask the obvious, but what no one has brought up yet:  What are the potential downsides to turning this on?

**Comment by asvc** [comment]
Apologies for being quiet. I will endeavour to test under Windows 7 by the end of this weekend.

The only .DLL from the application directory I see loaded:
```powershell
FileName         : SciLexer.dll
ARCH             : AMD64
DotNET           : False
ASLR             : True
DEP              : True
Authenticode     : True
StrongNaming     : N/A
SafeSEH          : N/A
ControlFlowGuard : False
HighentropyVA    : True
```

Next, plugins:
```powershell
FileName         : mimeTools.dll
ARCH             : AMD64
DotNET           : False
ASLR             : True
DEP              : True
Authenticode     : True
StrongNaming     : N/A
SafeSEH          : N/A
ControlFlowGuard : False
HighentropyVA    : True
```

Output for `NppExport.dll` and `NppConvert.dll` is the same.

> I'll ask the obvious, but what no one has brought up yet: What are the potential downsides to turning this on?

Should not be any... Until the beta-test proves otherwise ;) Yet to see (or read about) CFG stopping application prematurely.

**Comment by asvc** [comment]
I have tried latest [Electron-based Signal client](https://www.electronjs.org/apps/signal) which in turn uses Chromium on _unpatched_ Windows 7 SP1 x64. It does work.

On Windows 10 the same build successfully utilizes CFG:
![image](https://user-images.githubusercontent.com/300146/79680501-7f6b7f00-824f-11ea-8656-835058ea6957.png)

**Comment by chcg** [comment]
Tests might be done with the artifacts from the corresponding appveyor build. Didn't see any problems so far. Also not regarding performance.

**Comment by xomx** [comment]
It is known that the CFG can cause performance problems (e.g. when some more affected Win32 API functions like GetPixel are used). Some references:

https://winbuzzer.com/2019/05/01/windows-10-control-flow-guard-causes-chromium-performance-issues-xcxwbn/

https://www.tenforums.com/performance-maintenance/96792-fall-creators-update-poor-performance-lagginess-fix.html

So watch for any significant performance drop.

**Comment by asvc** [comment]
> significant performance drop

In the text-editor?.. I have read about applications relying on DX experiencing performance penalty from CFG, however these reports are mostly from 2019 and tend to begin with _"my FPS have dropped by a whopping 15%!"_

Is there a test script / etc. that is being used to eyeball performance of a certain build?
Similar to VIM's `+profile` feature.

**Comment by sasumner** [comment]
Maybe some performance areas to check; just some SWAG ideas:

* navigating around in a large XML file
* find-in-files on large tree

**Comment by asvc** [comment]
@sasumner , there seems to be "Windows Performance Toolkit" which is part of "Windows Hardware Kit Lab". That is, however, a _massive_ package with 2(3)-step download process... Unlikely to happen unless absolutely necessary.

We can probably do the following:
1. Use Sysinternals "process monitors" to capture specific events and their timestamps
2. Dump data out
3. Parse using _your_favourite_scripting_language_ and check results before/after CFG

What do you think? Somewhat relevant screen-grab:
![image](https://user-images.githubusercontent.com/300146/80212340-74ad5180-8676-11ea-9377-40fb7ba400c4.png)

**Comment by asvc** [comment]
Any updates on this one? v7.8.7.0 is still built with CFG disabled:

![image](https://user-images.githubusercontent.com/300146/85863391-3fea8180-b802-11ea-9108-0ac622f5a1a6.png)
