### ISSUE TITLE
Doc Switcher window icons have problems when Tab Bar 'Reduce' setting changed

### ISSUE THREAD

**Issue by sasumner** [notepad-plus-plus/notepad-plus-plus#8109]
### Description of the Issue

When the _Preferences_ > _General_ > _Tab Bar_ > _Reduce_ setting is changed, the icons in the window with title _Doc Switcher_ have display issues, until a Notepad++ restart is done.

### Steps to Reproduce the Issue
1) In _Preferences_ > _General_, tick the _Show_ box for _Document List Panel_
2) Restart Notepad++, observe window called _Doc Switcher_ on lefthand side
Observe the icons for "new 1" in both the tab bar and the _Doc Switcher_ window
3) In _Preferences_ > _General_ > _Tab Bar_, untick the _Reduce_ box
Observe that tab bar icon for "new 1" tab has increased in size
Observe that icon for "new 1" in _Doc Switcher_ window has **NOT** increased in size
4) Click on the "new 1" text in the _Doc Switcher_ window
Observe that the available space for the icon has **NOT** increased, but the icon image HAS increased in side so it is now **ILL-FITTING!**:
![image](https://user-images.githubusercontent.com/30118311/79118184-208f9c80-7d5b-11ea-9872-b06004bdbd3b.png)
5) In _Preferences_ > _General_ > _Tab Bar_, tick the _Reduce_ box
Observe that tab bar icon for "new 1" tab has decreased in size
Observe that icon for "new 1" in _Doc Switcher_ window has **NOT** changed
6) Click on the "new 1" text in the _Doc Switcher_ window
Observe that the icon has now **DISAPPEARED!**:
![image](https://user-images.githubusercontent.com/30118311/79118168-1077bd00-7d5b-11ea-8c3e-262a34f32d92.png)

### Expected Behavior

- After step 4, the available space for the icon becomes enlarged so that the entire non-Reduce'd icon fits.
- After step 6, the icon doesn't disappear but rather appears and is sized correctly to a Reduce'd icon size.
- In general, icons to change size in synchrony, and to not disappear of be poorly fit to the available space.

### Actual Behavior
See most of the "Observe" comments in the "Steps to Repro" above, especially ones with ALL CAPS and **BOLD**.

### Additional Information
After a restart of Notepad++, all is fine with _Reduce_ 'd icons, if _Reduce_ was ticked at the prior exiting of Notepad++:
![image](https://user-images.githubusercontent.com/30118311/79118303-8ed45f00-7d5b-11ea-88c7-55db0d5b52d7.png)

After a restart of Notepad++, all is fine with non- _Reduce_ 'd icons, if _Reduce_ was unticked at the prior exiting of Notepad++:
![image](https://user-images.githubusercontent.com/30118311/79118370-c17e5780-7d5b-11ea-9f8c-49b8fc821282.png)

### Debug Information
Notepad++ v7.8.5   (64-bit)
Build time : Mar  4 2020 - 11:08:34
Path : C:\.......\npp.7.8.5.bin.x64\notepad++.exe
Admin mode : OFF
Local Conf mode : ON
OS Name : Windows 10 Enterprise (64-bit) 
OS Version : 1809
OS Build : 17763.1039
Plugins : mimeTools.dll NppConverter.dll NppExport.dll

**Comment by ArkadiuszMichalski** [comment]
Same for me (looks like step 2. is unnecessary):

Notepad++ v7.9   (32-bit)
Build time : Sep 22 2020 - 03:24:22
Path : D:\_test\NPPClean\notepad++.exe
Admin mode : ON
Local Conf mode : ON
OS Name : Windows 7 Ultimate (64-bit) 
OS Build : 7601.0
Current ANSI codepage : 1250
Plugins : none

Another STR (all action in Prefs window, witohut click on Document List Panel):
1. Turn on Document List Panel.
2. Turn of Reduce.
3.  Turn off and on Document List Panel.
4. Trun on Reduce
5. Turn off and on Document List Panel.

and repeat 2-5.

By the way I also checked Window manager plugin and problem not exist (i.e. resizing the tabs doesn't work in panel, but the icon does not disappear). Additional info for those who still use this plugin.
