### ISSUE TITLE
Ability to drag selected text to area currently off screen

### ISSUE THREAD

**Issue by herohog** [notepad-plus-plus/notepad-plus-plus#8110]
### Description of the Issue
Add ability to drag and drop selected text to an area above or below the currently viewed screen by simply moving the mouse to/past the screen border to cause the screen to scroll to the desired new area.

### Describe alternatives you've considered
Current workarounds require either keyboard input or “extra” mouse clicks instead of a simple drag and drop. This is something I do often so it popped up on my radar when I switched to Notepad++. Using Keyboard commands or right-click commands will work but find the method I described faster/easier.

### Steps to Reproduce the Issue
1. Select a few lines of text.
2. Left-Click highlighted text and attempt to drag above or below the current visible page.

### Expected Behavior
For example in Wordpad or Word, the selection remains active and the screen scrolls towards the selected direction. As soon as you reach the desired location, just release the left mouse button and the selected text is dropped there.

### Actual Behavior
You can't drag anything beyond the visible area.

### Debug Information
Notepad++ v7.8.5   (64-bit)
Build time : Mar  4 2020 - 11:08:34
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS Name : Windows 10 Home (64-bit) 
OS Version : 1909
OS Build : 18363.752
Plugins : mimeTools.dll NppConverter.dll NppExport.dll

**Comment by Ekopalypse** [comment]
Just for reference, is part of scintilla version 4.3.1 onwards.
See https://sourceforge.net/p/scintilla/feature-requests/497/

**Comment by herohog** [comment]
> 
> 
> Just for reference, is part of scintilla version 4.3.1 onwards.
> See https://sourceforge.net/p/scintilla/feature-requests/497/

When does that get incorporated into Notepad++? Sorry if this is a "stupid question" but I am a Notepad++ Newbie.

**Comment by sasumner** [comment]
>When does that get incorporated

Probably at the next update of Notepad++'s embedded Scintilla component.
I don't believe there is any known timetable for that.

**Comment by herohog** [comment]
Thanks for the info. At least I can hope to see it "sometime" in the future, I guess!

**Comment by sasumner** [comment]
Maybe best to be left "open" to serve as a reminder that it should be verified as working when Scintilla in Notepad++ is updated to a Scintilla version >= the one that supports it.

**Comment by herohog** [comment]
> 
> 
> Maybe best to be left "open" to serve as a reminder that it should be verified as working when Scintilla in Notepad++ is updated to a Scintilla version >= the one that supports it.

Thanks!

**Comment by sasumner** [comment]
I build the Scintilla 4.44 source code appropriate for Notepad++ and tried this issue with that.
I'm pleased to say that this issue was successfully resolved after doing that.  :-)
So the upside is that it is confirmed to work, with Scintilla upgrade.
The downside is that a real Scintilla upgrade date for current (7.8.9) Notepad++ isn't known.

**Comment by herohog** [comment]
> I built the Scintilla 4.44 source code appropriate for Notepad++ and tried this issue with that.
> I'm pleased to say that this issue was successfully resolved after doing that. :-)
> So the upside is that it is confirmed to work, with Scintilla upgrade.
> The downside is that a real Scintilla upgrade date for current (7.8.9) Notepad++ isn't known.

Thanks so much, I guess, now we wait.

**Comment by donho** [comment]
@herohog  @sasumner 
Scintilla update would be in 7.9.2 if it doesn't happen in 7.9.1 - I'll try anyway.

**Comment by GiftWolf** [comment]
Being able to use the mouse wheel or Page up and down keys to scroll would also be a nice feature.

**Comment by sasumner** [comment]
>Being able to use the mouse wheel or Page up and down keys to scroll would also be a nice feature.

Please explain how that is related/relevant to the issue being discussed.

**Comment by GiftWolf** [comment]
At the moment you cant't scroll with the mouse wheel or Page up and down keys when you drag selected text. They just stop functioning when dragging. Making them work would be an alternative to moving the cursor close to the window border. It may be even faster or more precise.

**Comment by sasumner** [comment]
@GiftWolf Thanks for that explanation; understood now.  
But, again, this isn't something Notepad++ has control over; Scintilla would have to support it.
I did check Scintilla 4.44 and neither dragging+mousewheel nor dragging+pgup/down works.

**Comment by vinsworldcom** [comment]
@donho 
@sasumner 

I can confirm this is fixed in Notepad++ 7.9.3 Unicode Debug using the latest Scintilla 4.4.6 DLL.

Cheers.

**Comment by sasumner** [comment]
Closing based upon @vinsworldcom confirmation.
