### ISSUE TITLE
External display, blurry display

### ISSUE THREAD

**Issue by xianyun666** [notepad-plus-plus/notepad-plus-plus#8115]
External display, blurry display.
I have two monitors,The second monitor does not display properly

1.The first display shows normal
![1](https://user-images.githubusercontent.com/22339210/79323290-96089200-7f40-11ea-87fd-0256de2a3a63.png)
2.The second monitor does not display properly.The menu bar is obviously blurred, and there is a key dislocation in the upper right corner.Text editing area, I also feel blurred
![2](https://user-images.githubusercontent.com/22339210/79323667-16c78e00-7f41-11ea-86e2-dec3607bb806.png)

**Comment by sasumner** [comment]
It sounds like a high-dpi issue.  
Can you report dpi information on the two monitors?

**Comment by xianyun666** [comment]
> It sounds like a high-dpi issue.
> Can you report dpi information on the two monitors?

The first display，125% zoom，1920*1080 resolution.
The second display，100% zoom，1920*1080 resolution

**Comment by sasumner** [comment]
That may be helpful as well, but it's not the dpi information I was looking for.
Try this site: https://www.infobyip.com/detectmonitordpi.php
Just going there should get you a "Your monitor DPI" reading for the current monitor.  Report that for your "first display".
Then move the browser window to your "second display" and refresh/reload the site.  Get a new value to report for this second display.

**Comment by xianyun666** [comment]
> That may be helpful as well, but it's not the dpi information I was looking for.
> Try this site: https://www.infobyip.com/detectmonitordpi.php
> Just going there should get you a "Your monitor DPI" reading for the current monitor. Report that for your "first display".
> Then move the browser window to your "second display" and refresh/reload the site. Get a new value to report for this second display.

The monitor DPI unimportance,I'm a developer too.
My suggestion ,Edit the app.manifest file, as follows：
```
<application xmlns="urn:schemas-microsoft-com:asm.v3">
  <windowsSettings>
    <!-- The combination of below two tags have the following effect : 
         1. Per-Monitor for >= Windows 10 Anniversary Update
         2. System < Windows 10 Anniversary Update -->
    <dpiAwareness xmlns="http://schemas.microsoft.com/SMI/2016/WindowsSettings">PerMonitorV2</dpiAwareness>
    <dpiAware xmlns="http://schemas.microsoft.com/SMI/2005/WindowsSettings">true</dpiAware>
  </windowsSettings>
</application>
```

Reference blog:https://blog.walterlv.com/post/windows-high-dpi-development-for-wpf.html#

**Comment by sasumner** [comment]
I'm not sure why you think monitor DPI is unimportant.  On my system, I can create a blurry Notepad++, but only when I boot with primary display being 120dpi, and other displays being 96dpi; Notepad++ is blurry on the 96dpi screens then.  If I boot with 96dpi screen being primary monitor, then nothing about Notepad++ is blurry.

In trying to compare your situation to my experience to perhaps gain some insight into the problem, I was requesting information for that compare.

I fail to see how your manifest file can truly help.  I tried building Notepad++ with it, and it removes the blurry text/menus, but it creates other issues.  For example, the Replace window will look like this:

![image](https://user-images.githubusercontent.com/30118311/79677415-045a8800-81bf-11ea-8f97-c589acb051ba.png)

This is just one example of many UI problems.  Another problem is the main editor window tab (i.e., the text you are editing with Notepad++) font size is huge, even when a small size is chosen in the Style Configurator:

![image](https://user-images.githubusercontent.com/30118311/79677504-230d4e80-81c0-11ea-8b21-713bf950fa90.png)

While I'm sure these could one-by-one be addressed to resolve them, what I'm less confident in is the ability to obtain a single, unified, non-blurry look from this on all of the platforms that Notepad++ supports:  WinXP (lesser importance to me personally), Win7, Win8, and Win10.

By "single" I mean no platform-specific code to support a "good look".

Continued dialogue is welcome on this issue.

**Comment by xianyun666** [comment]
I tried it, also 120dpi and 96dpi.

I will not be c ++ desktop development.

You can refer to this project: https://github.com/rizonesoft/Notepad3.
He displays normally on multiple monitors and at different dpi.
But the latest release is a bit flawed

**Comment by xianyun666** [comment]
@sasumner 
The first-generation PerMonitor can be set up. I have tested it and found no problems.
			`<dpiAwareness>PerMonitor</dpiAwareness>`

**Comment by sasumner** [comment]
@xianyun666 said:

><dpiAwareness>PerMonitor</dpiAwareness>

Adding that in, in various ways, always resulted in this for me, upon run:

![image](https://user-images.githubusercontent.com/30118311/85167747-4b084500-b237-11ea-9d59-18ba74327b86.png)

If you can provide more specifics about how to make this work, I'm open to trying things.

**Comment by xianyun666** [comment]
[dpi.txt](https://github.com/notepad-plus-plus/notepad-plus-plus/files/4810949/dpi.txt)

@sasumner，
This is my modified configuration file, I have recompiled and tested it, no problem.

**Comment by krislabs** [comment]
Using v7.8.8. I have a Win 10 Pro laptop with external display connected. Both displays are 1920x1080px and set to 100% scaling. Laptop's display is the main display set. Starting Notepad and it shows on the main screen. Moving it between displays changes nothing. When laptop's display is set to 125% scaling however, Notepad's window moved to external display appears blurry.

**Comment by 7Z0t99** [comment]
To fix this issue (at least partially), scintilla probably needs to be upgraded to release 4.4.0 or newer, which implements per-monitor DPI awareness. Additionally WM_DPICHANGED needs to be forwarded, see also #5873

**Comment by xianyun666** [comment]
@sasumner Please pay attention to this issue

```
   <asmv3:application xmlns:asmv3="urn:schemas-microsoft-com:asm.v3">
        <asmv3:windowsSettings>
            <dpiAware xmlns="http://schemas.microsoft.com/SMI/2005/WindowsSettings">true</dpiAware>
            <dpiAwareness xmlns="http://schemas.microsoft.com/SMI/2016/WindowsSettings">PerMonitor</dpiAwareness>
        </asmv3:windowsSettings>
    </asmv3:application>
```

I have tested it, replace this code, it runs and shows perfectly.


Note: The original code `<asmv3:windowsSettings xmlns="http://schemas.microsoft.com/SMI/2005/WindowsSettings"> `needs to be changed to` <asmv3:windowsSettings>`

The attachment is the file after I modified and packaged it
[notepad++.zip](https://github.com/notepad-plus-plus/notepad-plus-plus/files/5774150/notepad%2B%2B.zip)

**Comment by okansahan** [comment]
After update, my second monitor does not display normal.
Why did you make this enhancement?
![image](https://user-images.githubusercontent.com/57413993/110446623-720dec00-80d0-11eb-988f-7b8c8fdbd4c9.png)

**Comment by nickprys** [comment]
I have the same issue 
if the laptop scale is set to 125% and external mon to 100% issue with blurring will exist.
if you change the laptop scale to 100% the issue will fix but you will have very small icons and text on the laptop.
