### ISSUE TITLE
Error in the C syntax autocomplete data

### ISSUE THREAD

**Issue by blinkenlight** [notepad-plus-plus/notepad-plus-plus#8117]
In the file notepad-plus-plus/PowerEditor/installer/APIs/c.xml, "strncmp()" is declared to be returning a "char *". It's actually supposed to return an "int".

**Comment by sasumner** [comment]
Same problem exists with `cpp.xml`

**Comment by sasumner** [comment]
Also, the first parameter should be `const`.

Reference:  http://www.cplusplus.com/reference/cstring/strncmp/
