### ISSUE TITLE
Can't close Notepad++

### ISSUE THREAD

**Issue by klav11** [notepad-plus-plus/notepad-plus-plus#8123]
### Description of the Issue
Notepad++ contains unsaved files. 
I shutdown windows. 
A warning message comes up from Windows about the files
I cancel the shutdown
I close every notepad++ tab
The notepad++ window cannot be closed

### Steps to Reproduce the Issue
1 Notepad++ contains unsaved files. 
2 I shutdown windows. 
3 A warning message comes up from Windows about the files
4 I cancel the shutdown
5 I close every notepad++ tab
6 The notepad++ window cannot be closed

### Debug Information
Windows10 and notepad++ 7.8.1

**Comment by MauriceKayser** [comment]
Seems to be a duplicate of #8095

**Comment by dail8859** [comment]
Please update Notepad++. If the issue still occurs please post your debug information that is available under the `?` menu

**Comment by klav11** [comment]
Closed as duplicate of #8095

**Comment by sasumner** [comment]
I'm fairly certain that when I "mentioned this issue on June 14" in 8413, it was a mistake; nothing about that is related. :-(
