### ISSUE TITLE
[Bug] Workspace object handle is leaked

### ISSUE THREAD

**Issue by MauriceKayser** [notepad-plus-plus/notepad-plus-plus#8124]
### Description of the Issue

When opening a directory as a workspace, an object handle to that directory is created with the permissions `FILE_LIST_DIRECTORY | FILE_READ_ATTRIBUTES | SYNCHRONIZE`. This object handle is never closed (which indicates a leak), even if the workspace sub window is closed and another workspace is opened. This causes the user not being able to manipulate (for example delete) this directory until Notepad++ is closed completely.

### Steps to Reproduce the Issue

1. Create an empty directory
2. Open Notepad++
3. Open the created directory as a workspace in Notepad++
4. Close the workspace in Notepad++
5. Try to delete the created directory in Windows Explorer -> The created directory disappears
6. Refresh the view in Windows Explorer -> The created directory reappears
7. Try to delete the created directory in Windows Explorer -> Access denied
8. (Optional) Open another directory as a workspace in Notepad++
9. (Optional) Close the workspace in Notepad++
10. Refresh the view in Windows Explorer -> The created directory is still there
10. Close Notepad++
11. The created directory disappears in Windows Explorer

### Expected Behavior

The object handle should have been closed either:
- After enumeration of all sub directories and files is finished
- When the workspace was closed, in case Notepad++ still uses the handle to get notified about updates in the workspace from outside of Notepad++

And thus the directory must not reappear in step 6.

### Actual Behavior

The directory reappears in step 6 because there is still an open object handle pointing at it.

### Debug Information

```
Notepad++ v7.8.5   (64-bit)
Build time : Mar  4 2020 - 11:08:34
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS Name : Windows 10 Pro (64-bit)
OS Version : 1909
OS Build : 18363.720
Plugins : DSpellCheck.dll mimeTools.dll NppConverter.dll NppExport.dll NPPJSONViewer.dll
```

**Comment by ArkadiuszMichalski** [comment]
I can't reproduce this in:
```
Notepad++ v7.9   (32-bit)
Build time : Sep 22 2020 - 03:24:22
Path : D:\_test\NPPClean\notepad++.exe
Admin mode : ON
Local Conf mode : ON
OS Name : Windows 7 Ultimate (64-bit) 
OS Build : 7601.0
Current ANSI codepage : 1250
Plugins : none
```

@MauriceKayser Do you still have this problem in latest Notepad++ version? By workspace you mean `Folder as Workspace` or `Project1/2/3` panel? And in step 6. refresh by F5 or kill/run explorer process once again? Maybe related to Win10 or admin mode. If anyone reproduce, let us know.

**Comment by MauriceKayser** [comment]
```
Notepad++ v7.9   (64-bit)
Build time : Sep 22 2020 - 03:19:04
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS Name : Windows 10 Pro (64-bit) 
OS Version : 1909
OS Build : 18363.836
Plugins : DSpellCheck.dll mimeTools.dll NppConverter.dll NppExport.dll NPPJSONViewer.dll 
```

1. Yes the problem still persists, the handle is still open after closing the workspace, you can verify this by looking up all handles to the empty directory with a tool like `Sysinternals Process Explorer` and Notepad++ is the only owner of a handle to it, even after closing the workspace view by clicking on the `x` button.
2. `Folder as Workspace`, simply drag&drop the empty directory onto the editor textbox of Notepad++.
3. Killing the explorer does not help, since that does not close the handle inside Notepad++.

**Comment by MauriceKayser** [comment]
I traced the creation of the handle which is never closed:

```
ntdll.KiUserApcDispatcher ->
notepad++.exe:$150948 ->
notepad++.exe:$1514AA ->
kernel32.CreateFileW(
    "PathToDirectory",
    FILE_LIST_DIRECTORY,
    FILE_SHARE_READ | FILE_SHARE_WRITE | FILE_SHARE_DELETE,
    nullptr,
    OPEN_EXISTING,
    FILE_FLAG_BACKUP_SEMANTICS | FILE_FLAG_OVERLAPPED,
    nullptr
)
```

After `notepad++.exe:$150948` the handle is used in a call to `ReadDirectoryChangesW`.

This corresponds to `CReadChangesRequest::OpenDirectory` and `CReadChangesRequest::BeginRead` in [ReadDirectoryChangesPrivate.cpp](https://github.com/notepad-plus-plus/notepad-plus-plus/blob/master/PowerEditor/src/WinControls/ReadDirectoryChanges/ReadDirectoryChangesPrivate.cpp#L69-L109).

They are executed by [CReadChangesServer::AddDirectory](https://github.com/notepad-plus-plus/notepad-plus-plus/blob/master/PowerEditor/src/WinControls/ReadDirectoryChanges/ReadDirectoryChangesPrivate.h#L147) which is executed by [CReadChangesServer::AddDirectoryProc](https://github.com/notepad-plus-plus/notepad-plus-plus/blob/8c1e15377fec12133374fffde9f775484c798e6e/PowerEditor/src/WinControls/ReadDirectoryChanges/ReadDirectoryChangesPrivate.h#L127), which is queued as an APC by [CReadDirectoryChanges::AddDirectory](https://github.com/notepad-plus-plus/notepad-plus-plus/blob/master/PowerEditor/src/WinControls/ReadDirectoryChanges/ReadDirectoryChanges.cpp#L86).

This is the handle that is never closed.

```
Notepad++ v7.9.1   (64-bit)
Build time : Nov  2 2020 - 01:07:46
```

**Comment by donho** [comment]
Cannot reproduce it.
