### ISSUE TITLE
[Feature request] Make project files searchable by file list (not by directory).

### ISSUE THREAD

**Issue by Uhf7** [notepad-plus-plus/notepad-plus-plus#8125]
I use the "View->Project->Project Panel 1" command to open a project panel. Then I pick my project
files from various different directories. Then I save the workspace file with the self-choosen extension ".npj".

I set Preferences->MISC->"Workspace file ext." to ".npj". Now I can open Npp with my Workspace file as first parameter, and I'm back in my project. So far, so good.

My problem is, that the "Find in files" function of Npp cannot search through Project file sets. It can only search directories. This is bad for me, because my project files are kind of scattered around different places.

I miss the option "search all files in project", which most Compiler IDEs have. Now I could use a Compiler IDE, MS VC++ for instance, but the start up time of those IDE's is simply too long.

What I ended up with, was building an own version of Npp, which has additional check marks in the "Find in Files" dialog, Looks like this:

![FindInFiles](https://user-images.githubusercontent.com/40629737/79457986-6e253700-7ff1-11ea-9014-ab1dbf2cf02c.png)

Selecting one of the Project check marks tells Npp, that it should search all files listed in this Project panel.

This extension has the following impact:

- Modificatition of the Find in files dialog: 3 new check marks in FindReplaceDlg.rc, some shifting of existing controls, and 6 lines FindReplaceDlg_rc.h.

- Modificatition of the Find in files dialog: 3 new check marks in FindReplaceDlg.rc, some shifting of existing controls, and 6 lines FindReplaceDlg_rc.h.

- Changes to handle the new check marks (on/off/mutual exclusion against other check marks), ca. 110 Lines in FindReplaceDlg.cpp, 7 lines in FindReplaceDlg.h, 13 new lines in Parameters.cpp to
  save/load the state of the new checkboxes, 3 new lines in Parameters.h

- A new function ProjectPanel::enumWorkSpaceFiles(...),  ca. 30 new lines in ProjectPanl.cpp, 1 line in ProjectPanel.h

- Modification of the find function itself,  ca. 50 lines new or changed in Notepad_plus::findInFiles(...).

**The benefit is, that Notepad++ can now search through all files of a project, like the most Compiler IDEs can do.**

If you like this new feature, I would be happy to create a pull request, including only the modifications listed above, for reviewing.

**Comment by sasumner** [comment]
Just kind of throwing this out there, without much thought, but why not just invoke this special functionality if the _Directory_ box is set to `Project1` for example?  Less impact to the existing UI.

Also, does the _Filters_ box mean anything when searching a project, or are all files that are part of the project searched?

**Comment by Uhf7** [comment]
Because I expect the directory input field to contain a directory, not a hidden function-changing keyword. There could even a directory named Project1. But I'm open to this, generally. Perhaps the "directory" should start with some escape-character at start which markes it as "I'm not a directory". Perhaps even a prefix.

But if I go this way, I need an easy way to put "Project1" in the directory field. This could be reached by adding a context menu entry to the menu that appears if you right-click the root entry of the Project panel. There I could add a menu entry "Find in Project files...". This would open the Find in Files dialog and fill "Project<n>" into the directory field. 

The impact on the code in FindReplaceDlg.cpp is similar, because the checkmarks "Follow current doc.", "In all subfolders" and "In hidden folders" are not compatible with the search through project files, and should be automatically turned off, if "Project1" is in the directory field. And "Project1" must be removed from the directory field, if one of those checkmarks turns on.

The advantage of this way would be, that people who don't use Project panels, will not notice the feature and will not hate the additional check marks.

The Filters box is to select the file types to be searched, this works too when searching in project files, it narrows the selection further. But it cannot compensate the missing search for project files by file list.

**Comment by sasumner** [comment]
>There could even a directory named Project1. 

`Project1` would have to be a directory under the notepad++.exe folder for this to matter.  Anyway, the idea was that "Project1" could be noticed in the box before any possible interpretation of it being a directory was possible.  It was just an idea.

>I need an easy way to put "Project1" in the directory field

The idea was that you'd type it once, then later it would be available as a remembered item in the history of that box.

>Perhaps the "directory" should start with some escape-character at start which markes it as "I'm not a directory". Perhaps even a prefix.

Doesn't seem necessary.

>The advantage of this way would be, that people who don't use Project panels, will not notice the feature and will not hate the additional check marks.

Plus, there's always resistance to changes in the UI, especially the Find UI.

Anyway, just some random thoughts. :-)

**Comment by sasumner** [comment]
>...right-click the root entry of the Project panel. There I could add a menu entry "Find in Project files...". This would open the Find in Files dialog and fill "Project" into the directory field.

Yes, this is VERY similar to how it works currently when using *Folder As Workspace*

**Comment by ArkadiuszMichalski** [comment]
@Uhf7 
This make some regression:
https://community.notepad-plus-plus.org/topic/20854/notepad-7-9-4-rc/4?_=1615677205902
