### ISSUE TITLE
[Bug] Wrong Project Panel at Start

### ISSUE THREAD

**Issue by Uhf7** [notepad-plus-plus/notepad-plus-plus#8126]
### Description of the Issue
The intended switch to Project panel 1 after starting Npp with a Workspace file name as parameter 1 doesn't work.

### Steps to Reproduce the Issue
1. Configure *Settings->Preferences->MISC->WorkspaceFileExtension* with a valid workspace extension.
2. Start Npp with the name of a valid workspace file as first parameter.
3. Open at least one more Project panel with *View->Project->Project panel 2*
There have to be at least two Project panels open to see the effect. If already are at least two Project  panels open, you can omit this step.
4. End Npp.
5. Start Npp with the name of a valid workspace file as first parameter again.

### Expected Behavior
Npp should show the first Project panel, wich should show the project described in the workspace file.

### Actual Behavior
Npp shows the Project panel with the highest number. If I switch to the first Project panel, then this shows the correct content.

### Debug Information
Notepad++ v7.8.5   (32-bit)
Build time : Apr 16 2020 - 11:48:34
Path : C:\isys-vision\Tools\Npp\notepad++.exe
Admin mode : OFF
Local Conf mode : ON
OS Name : Windows 10 Pro (64-bit) 
OS Version : 1607
OS Build : 14393.576
Plugins : none

### My workaround
The intended switch is programmed in **NppIO.cpp**, near line 211 as follows:

    if (isFileWorkspace(longFileName) && PathFileExists(longFileName))
    {
        nppParam.setWorkSpaceFilePath(0, longFileName);
        command(IDM_VIEW_PROJECT_PANEL_1);
        return BUFFER_INVALID;
    }
The `command(IDM_VIEW_PROJECT_PANEL_1)` call shows no effect, since the Project panels are loaded later in the startup process. This load ends always with the last Project panel being the current Project panel.

In **NppIO.cpp**, instead of calling `command(IDM_VIEW_PROJECT_PANEL_1)`, I set a variable, `__WorkspaceFileLoadedFromCommandLine`, to `true`.

Then, later in the startup process, in **Notepad_plus_Window.cpp**, around line 242:

    // Launch folder as workspace after all this dockable panel being restored from the last session
    // To avoid dockable panel toggle problem.
    if (cmdLineParams->_openFoldersAsWorkspace)
    {
        _notepad_plus_plus_core.launchFileBrowser(fns, true);
    }
    else if (_notepad_plus_plus_core._WorkspaceFileLoadedFromCommandLine)
    {
        ::SendMessage(_hSelf, WM_COMMAND, IDM_VIEW_PROJECT_PANEL_1, 0);
    }
At this stage, `IDM_VIEW_PROJECT_PANEL_1` works.

It is my work-around only. There might be a better way to solve this.

This issue seems to be related to #3519, but can be solved without remembering the last open Project panel.

**Comment by dail8859** [comment]
Please open a pull request with the code changes so it can be reviewed easily.

**Comment by Uhf7** [comment]
Pull resuest #8161 opened.

**Comment by sasumner** [comment]
>Pull resuest #8161 opened.

The proper way to do it is to put "Fixes #xxxx" or "Implements #xxxx" as the first line of your comments in the PR when you submitit.  This has two benefits (at least):

* You don't have to come back here to the issue and comment "Pull request #xxxx opened" as github will link the PR to the issue automatically.

* If your PR is accepted, the committer of your PR into "master" has an easy way to find the originating issue so that it can be closed.

**Comment by Uhf7** [comment]
Thank You, I'll do this next time.
