### ISSUE TITLE
[Bug] Crashing on exit

### ISSUE THREAD

**Issue by ragues** [notepad-plus-plus/notepad-plus-plus#8127]
### Description of the Issue
Since updating to the latest version (7.8.5.0, Windows 8.1), Notepad++ reliably generates a crash on closing.

### Steps to Reproduce the Issue

1. Open Notepad++
2. Exit using the file menu or the close button
3. Wait for crash message

### Expected Behavior
Quits without error message

### Actual Behavior
Windows crash message appears with the following content:

Problem signature:
  Problem Event Name:	APPCRASH
  Application Name:	notepad++.exe
  Application Version:	7.8.5.0
  Application Timestamp:	5e5f7e0a
  Fault Module Name:	notepad++.exe
  Fault Module Version:	7.8.5.0
  Fault Module Timestamp:	5e5f7e0a
  Exception Code:	c0000005
  Exception Offset:	00069dfc
  OS Version:	6.3.9600.2.0.0.768.101
  Locale ID:	2057
  Additional Information 1:	5861
  Additional Information 2:	5861822e1919d7c014bbb064c64908b2
  Additional Information 3:	6fbe
  Additional Information 4:	6fbe6bde2701766d81cbca0597a5fa35

### Debug Information
Notepad++ v7.8.5   (32-bit)
Build time : Mar  4 2020 - 11:04:20
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS Name : Windows 8.1 (64-bit) 
OS Build : 9600.0
Plugins : DSpellCheck.dll HTMLColor.dll HTMLTag_unicode.dll mimeTools.dll NppConverter.dll NppExport.dll PreviewHTML.dll

**Comment by dail8859** [comment]
Try to reproduce it with no plugins installed.
