### ISSUE TITLE
"Find All in All Opened Documents" closes the Find dialog

### ISSUE THREAD

**Issue by LaraSQP** [notepad-plus-plus/notepad-plus-plus#8130]
Running the latest version of npp.

I use the `Find All in All Opened Documents` feature often. **Very often**.

For some reason it closes the `Find dialog` and I need to bring it up again every time.

Also, there is no shortcut to it.

Feature request (?): Grab the selected text and press whatever key combo to fire the search.

Thank you all for this fantastic program.

**Comment by xylographe** [comment]
Quoting from the [Notepad++ User Manual](https://npp-user-manual.org/docs/searching/):
```
Note: Use of some “Find” family features can cause the window to close. Some users
dislike this and wish for the “Find” window to always remain open. This may be achieved
by editing config.xml and looking for the dlgAlwaysVisible= parameter. It defaults to
dlgAlwaysVisible="no" but may be set to dlgAlwaysVisible="yes" to keep the “Find”
window open and always available for user interaction.
```

**Comment by sasumner** [comment]
>Also, there is no shortcut to it.
>Feature request (?): Grab the selected text and press whatever key combo to fire the search.

You are correct in that there is no direct shortcut to run this type of search.  However, you can do it in TWO sequential keycombo presses:

* put your caret on the desired word, or make a short selection of text
* press ctrl+f (this will open the Find window, put the text in the _Find what_ box, and leave input focus in that field/window)
* press alt+o (this will run the _Find All in All Opened Documents_ search)

Closing due to workarounds provided.

**Comment by LaraSQP** [comment]
> > Also, there is no shortcut to it.
> > Feature request (?): Grab the selected text and press whatever key combo to fire the search.
> 
> You are correct in that there is no direct shortcut to run this type of search. However, you can do it in TWO sequential keycombo presses:
> 
> * put your caret on the desired word, or make a short selection of text
> * press ctrl+f (this will open the Find window, put the text in the _Find what_ box, and leave input focus in that field/window)
> * press alt+o (this will run the _Find All in All Opened Documents_ search)
> 
> Closing due to workarounds provided.

Thank you. Was aware of `Ctrl+f` then `Alt+o`



> Quoting from the [Notepad++ User Manual](https://npp-user-manual.org/docs/searching/):
> 
> ```
> Note: Use of some “Find” family features can cause the window to close. Some users
> dislike this and wish for the “Find” window to always remain open. This may be achieved
> by editing config.xml and looking for the dlgAlwaysVisible= parameter. It defaults to
> dlgAlwaysVisible="no" but may be set to dlgAlwaysVisible="yes" to keep the “Find”
> window open and always available for user interaction.
> ```

That's quite useful. Thank you very much. Good karma to you.

**Comment by sasumner** [comment]
Related to #7908
