### ISSUE TITLE
"Find" settings need their own sub-page in Settings -> Preferences

### ISSUE THREAD

**Issue by sasumner** [notepad-plus-plus/notepad-plus-plus#8131]
There are getting to be a few setting related entirely to _Find_ on the _MISC._ page in the _Preferences_ :

![image](https://user-images.githubusercontent.com/30118311/79641410-73a38e00-8165-11ea-9be6-8d59c550ec36.png)

These should be broken out into their own sub-page in the box on the left:

![image](https://user-images.githubusercontent.com/30118311/79641400-553d9280-8165-11ea-9498-69971f35ac43.png)

This also makes room for new "Find" related settings, and frees up space on the `MISC.` subpage for new items there, too.

One new setting could be added as well:

`Keep find window open after search that outputs to Find-result window`

which would control the existing `config.xml` entry:

`<FindHistory ... dlgAlwaysVisible="no/yes" ... />`

**Comment by sasumner** [comment]
Related to #8130

**Comment by sasumner** [comment]
Of course, I have some ideas about new features for "Find" that will necessitate some new Preference settings, so that has something to do with opening this issue.  :-)

**Comment by donho** [comment]
> One new setting could be added as well:
> Keep find window open after search that outputs to Find-result window

This hidden option can be made visible in this panel as well:
https://npp-user-manual.org/docs/preferences/#preferences-for-advanced-users

**Comment by sasumner** [comment]
>Keep find window open after search that outputs to Find-result window

Yes, this was actually in my plan.  :-)

>The hidden option Allow regex backward search can be made visible in this panel as well

Yes, OK.

**Comment by sasumner** [comment]
I will make separate PR for these, after this current PR is accepted:

* Keep find window open after search that outputs to Find-result window
* Allow regex backward search

**Comment by sasumner** [comment]
Changes from this issue released in Notepad++ version 7.9
