### ISSUE TITLE
Add checkbox to force open each document in separate process of np++

### ISSUE THREAD

**Issue by AlexanderVoid45** [notepad-plus-plus/notepad-plus-plus#8137]
### Description of the Issue
Bad realisation of setting  that forces notepad++ to open every document in new instance of notepad++
There are some tips how to do that like add "asNotepad.xml" to the application folder of notepad++
this solution forces notepad++ to open each document in separate process. This is useful for people with 2-3 lcd - where u need to compare some documents or get information from them in 1 time without switching tabs.

it would be great to have !well named! checkbox (for example: open each document in new instance of notepad++). I think it must be placed in "general" or "load history" or in miscellaneous section.

**Comment by sasumner** [comment]
Thank you for your suggestion but at this time we don't believe it would be a generally useful enhancement for Notepad++
