### ISSUE TITLE
Notepad++ mistakes level when there's a commented line in a 2d array in c/c++

### ISSUE THREAD

**Issue by alaa137** [notepad-plus-plus/notepad-plus-plus#8141]
When there's a **2d array** (it doesn't happen with 1d arrays) initialized on declaration, like this (notice the commented line):
```
int arr[][2] = {
	{1, 2},
	//{1, 2},
	{3, 4}
};

void foo()
{
}
```
Then Notepad++ thinks everything after the closing bracket of the array still belongs to the array.
This is conveyed in several ways. For example:

- Stand with the mouse on the opening bracket of the array, and see how Notepad++ draws the level red line all the way to the bottom:
![image](https://user-images.githubusercontent.com/11571579/79722781-5994b780-82ed-11ea-943f-110c3c99a973.png)

- Or click View > Collapse current level (while the mouse is in the array's level, and see how everything below the array is collapsed inside it, as it was part of the array:
![image](https://user-images.githubusercontent.com/11571579/79722478-cd829000-82ec-11ea-89ad-105183829b7c.png)

Note that this behavior **does not** happen if the comment is of type `/**/` instead of `//`:
![image](https://user-images.githubusercontent.com/11571579/79722877-85b03880-82ed-11ea-9a9c-526d3228ed14.png)

And of course if there's no comment at all, the problem doesn't happen either:
![image](https://user-images.githubusercontent.com/11571579/79722900-8c3eb000-82ed-11ea-800c-1801692942d1.png)

I tried this in C and C++ sources, and the problem happens in both.

_Notepad++ v7.7.1 64-bit, on Windows 10_

**Comment by Ekopalypse** [comment]
Scintilla lexer dependent issue.

![image](https://user-images.githubusercontent.com/47723516/79750998-63281a80-8301-11ea-9e3c-b5e16b6bb19b.png)

**Comment by sasumner** [comment]
For the sake of completeness:

![image](https://user-images.githubusercontent.com/30118311/79752733-c6ef1b00-82e2-11ea-84e3-4dd937bd6e5a.png)

Closing for now as Scintilla dependent.

**Comment by alaa137** [comment]
@sasumner 

> For the sake of completeness:
> 
> ![image](https://user-images.githubusercontent.com/30118311/79752733-c6ef1b00-82e2-11ea-84e3-4dd937bd6e5a.png)
> 
> Closing for now as Scintilla dependent.
The issue is only with a double slash comment (//), not slash asterisk (/*) as your snapshot.

**Comment by sasumner** [comment]
>The issue is only with a double slash comment (//), not slash asterisk (/*) as your snapshot.

Correct.
The Scintilla editor doesn't draw the vertical lines in like Notepad++ does, so showing only the problem version with it was  a bit lacking.
That's the only reason I added the screenshot that I did -- pretend that it has the `//` comment in it -- and the fold indicators should be as shown.

**Comment by dail8859** [comment]
@sasumner This "feature" is a property of the lexer. Would you agree having this on by default causes more confusion than being helpful? I know I've seen numerous reports over the years.

**Comment by sasumner** [comment]
>having this on by default causes more confusion than being helpful?

Not sure what you are proposing.  Off by default?  Meaning that someone loads a file for a programming language that is "folding aware" and sees no folding "brackets" unless they turn it on?

**Comment by dail8859** [comment]
Just the Cpp lexer. It has an option to handle `//{` as a user defined folding point.

**Comment by dail8859** [comment]
https://github.com/notepad-plus-plus/notepad-plus-plus/blob/92bad0a60ad606b30df9ed97aecf4ff27bb6e967/scintilla/lexers/LexCPP.cxx#L438-L445

**Comment by Ekopalypse** [comment]
@dail8859 - I guess I see what you mean

![image](https://user-images.githubusercontent.com/47723516/79761653-41369400-8311-11ea-87c4-9e9291d3bd3a.png)

**Comment by sasumner** [comment]
>It has an option to handle //{ as a user defined folding point.

If I'm agreeing to the correct thing, then yes, I'd think that should be off by default.

**Comment by Ekopalypse** [comment]
Btw., I think it would be good if these properties could be set by the users.
Maybe as an additional tag within the langs.xml file?
Something like 
`
<Language name="c" ...
    <Keywords ...
    <properties>
        <property name="fold.cpp.comment.explicit" value="0" />
    </properties>
`

**Comment by sasumner** [comment]
>I think it would be good if these properties could be set by the users.

Agree; actually I didn't know it wasn't something the user could change.
