### ISSUE TITLE
Find command not working properly.

### ISSUE THREAD

**Issue by nichter** [notepad-plus-plus/notepad-plus-plus#8143]
### Description of the Issue

in order to check a html code in PHP i count the occurrence of certain tag
i was checking the occurrence of *div* elements in a code and results are not as spected
Manually checking brackets, the highlight of code is working properly

using the find command in order to count the occurrence of **div** commands is working weird.

### Steps to Reproduce the Issue

1. open the attached txt file
2. use find command (ctrlf +f) with option whole document and 
3. Search for **div** you will find 12 items
4. Seach for **</div** you will find 5 items
5. Seach for **<div** you will find 6 items

[error_test.txt](https://github.com/notepad-plus-plus/notepad-plus-plus/files/4503342/error_test.txt)

### Expected Behavior

the sum of **<div** (6) + **</div**(5) should be the same as **div** (12)

### Actual Behavior

count of certain items is incorrect
### Debug Information

Notepad++ v7.8.5   (32-bit)
Build time : Mar  4 2020 - 11:04:20
Path : F:\Progs\Editors\Notepad_32++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS Name : Windows 10 Enterprise (64-bit) 
OS Version : 2004
OS Build : 19041.207
Plugins : ccc.dll ComparePlugin.dll DSpellCheck.dll HTMLTag_unicode.dll JSLintNpp.dll JSMinNPP.dll Linter.dll mimeTools.dll NavigateTo.dll NewFileBrowser.dll NppCCompletionPlugin.dll NppConverter.dll NppExport.dll NPPJSONViewer.dll NppMarkdownPanel.dll NppPluginDemo.dll NppPluginTemplate.dll NppToolBucket.dll PreviewHTML.dll XBrackets.dll XMLTools.dll

**Comment by Ekopalypse** [comment]
What do you mean by _with option whole document_? Wrap around?
If so, then no, I don't see this issue. With your test file I get 12, 6, 6.
Notepad++ v7.8.6   (64-bit)
Build time : Apr 14 2020 - 22:37:54
Path : D:\...\_latest\x64\notepad++.exe
Admin mode : OFF
Local Conf mode : ON
OS Name : Windows 7 Professional (64-bit) 
OS Build : 7601.24544
Plugins : mimeTools.dll NppConverter.dll NppExport.dll PySnack.dll

**Comment by nichter** [comment]
Hi
This is an option for seach

See attached file

(sorry is in spanish but i guess the position is the same in other languages)

**Comment by sasumner** [comment]
> I don't see this issue. With your test file I get 12, 6, 6.

I agree with these findings; no problem here.

If the OP is talking about using the _Count_ button, then be aware of the following:

* If the _Wrap around_ checkbox is NOT ticked, the count shown will be affected by caret position and the _Backward direction_ checkbox setting.  Also, if the _In selection_ checkbox is ticked, that will be the overriding factor if a selection is active.

**Comment by nichter** [comment]
you have richt the code has a a tab/space mess (it was a copyed, pasted and edited piece of code) ... but does this matter for find a continous sting (i mean the influence of spaces doesnt exist on searched character.
I find this is an excelent program but sometimes i have weird results. If i play arround the options of the command Find i can get somehow the desired 6+6=12 but not always...ot at the first time.
only for your information .. see the image. in order to avoid the influences of former selection options i closed notepad++, opened it, paste the same code and search **/div..... ** and got "0"
i changed the option from "normal" to "regular expression" and got "6" 
I am not an expert in regular expressions, it seems to me that "/" is not a regular expression but somehow for notepad ++ it is like that.
Anyway, thank you very much for the help, I think that the explanation or scope of options should be improved, but believe me, this program is the best of windows for texts. Although I use codelobster as IDE to program my website.
![search1](https://user-images.githubusercontent.com/30216755/79759331-2994e680-82e4-11ea-954d-25f48d7a4ba5.png)
![search2](https://user-images.githubusercontent.com/30216755/79759341-2d286d80-82e4-11ea-9224-b88555e0d773.png)

**Comment by nichter** [comment]
i meant right ...

**Comment by sasumner** [comment]
To use the "whole word" option, the first and last characters of the text you are searching for must be "word" characters.  You have `/` as the first character, which causes no match to occur.

**Comment by nichter** [comment]
Thank you I will take it in consideration
