### ISSUE TITLE
Blue link-type number input boxes in Preferences appear strange (on Win10 only?)

### ISSUE THREAD

**Issue by sasumner** [notepad-plus-plus/notepad-plus-plus#8144]
### Description of the Issue
Several UI elements used in the Preferences appear strangely; suspect it is something that only occurs on Windows 10 (but have no evidence of that).  See examples below.  There are other occurrences of this throughout the Preferences.

NOTE: This is a VISUAL issue only; it doesn't interfere functionally.

This was called to attention after I was experimenting with the settings in regard to this PR:  #8136

### Steps to Reproduce the Issue
1. Invoke _Settings_ menu, select _Preferences_..., select _Recent Files History_, click on the blue underlined number to the right of _Max. number of entries_ and/or _Customize Maximum Length_
2. Observe popup window for editing said number appears truncated.

### Expected Behavior
Windows not to be malformed.

### Actual Behavior
Odd-looking windows, from the example provided above:
![image](https://user-images.githubusercontent.com/30118311/79751196-2f88c880-82e0-11ea-860e-b64a07ca0fec.png)

![image](https://user-images.githubusercontent.com/30118311/79751254-4e875a80-82e0-11ea-9750-f9e9a9f51a7b.png)

### Debug Information
Notepad++ v7.8.4   (32-bit)
Build time : Jan 29 2020 - 01:33:47
Path : C:\........\npp.7.8.4.bin\notepad++.exe
Admin mode : OFF
Local Conf mode : ON
OS Name : Windows 10 Enterprise (64-bit) 
OS Version : 1809
OS Build : 17763.1039
Plugins : BetterMultiSelection.dll DSpellCheck.dll linefilter2.dll mimeTools.dll NppConverter.dll NppExec.dll NppExport.dll NppMenuSearch.dll NppToolBucket.dll PythonScript.dll qkNppReverseLines.dll XMLTools.dll

**Comment by Ekopalypse** [comment]
I can confirm, that I do NOT see this behavior on Windows7 x64

![image](https://user-images.githubusercontent.com/47723516/79752288-9b305d00-8303-11ea-8e3d-79c8052a7546.png)

**Comment by Ekopalypse** [comment]
BUT I don't see it on Windows10 either - maybe another dpi issue?

![image](https://user-images.githubusercontent.com/47723516/79753246-20684180-8305-11ea-863a-e273a8f3cf6d.png)

**Comment by sasumner** [comment]
>maybe another dpi issue?

Does THAT pain ever stop? :-(
