### ISSUE TITLE
hide-markers disappear when two subsequent lines are hidden separately

### ISSUE THREAD

**Issue by sskras** [notepad-plus-plus/notepad-plus-plus#8149]
### Description of the Issue
When two subsequent lines are hidden one by one, hide-markers seemingly combine into one block, that's OK:

![image](https://user-images.githubusercontent.com/7887758/79848282-90d89680-83c9-11ea-8d8b-4a77d03ae8e0.png)

But when I try to expand it, the first line remains hidden:

![image](https://user-images.githubusercontent.com/7887758/79848469-c8dfd980-83c9-11ea-8d81-77d97f5036c9.png)

And its hide-markers disappears. Line 2 got lost behind the scene. 
You don't see it in the tab and can damage it accidentally.

### Steps to Reproduce the Issue
1. Enter five lines into a new tab.
2. Go to line no. 2 and hide it (Alt-H).
3. See green hide-markers appearing on lines 1 and 3.
4. Go to line no. 3 and hide it too.
5. See closing hide-markers now jumping onto line 4.
6. Click the a hide-marker (any of the two).

### Expected Behavior
I expected both lines to be revealed.

### Actual Behavior
Only line no. 3 got revealed. Line no. 2 got visually lost.

### Debug Information
```
Notepad++ v7.8.5   (64-bit)
Build time : Mar  4 2020 - 11:08:34
Path : C:\Users\saukrs\_\bin\npp.7.8.5.bin.x64\notepad++.exe
Admin mode : OFF
Local Conf mode : ON
OS Name : Windows 10 Enterprise (64-bit) 
OS Version : 1803
OS Build : 17134.1365
Plugins : DSpellCheck.dll mimeTools.dll NppConverter.dll NppExport.dll
```
### Real time video:

![2020 04 21-11_55_19-notepad-_v7 8](https://user-images.githubusercontent.com/7887758/79849692-7a333f00-83cb-11ea-8ae0-3044c3059b52.gif)

### Workaround

If this is an unsaved file, you can't just reload the content without losing part of it.
I worked around this by doing:
* Select All
* Cut
* Undo

Line no. 2 got back.

**Comment by sskras** [comment]
This might be a continuation (an unfixed / corner case of) of bug #1112.

**Comment by nCubed** [comment]
In addition to this issue with Hide Lines as well as bug #1112, there is no way to unhide lines if "bookmarks" are not enabled. Was going to open a new issue, but figured I'd piggy-back on this open issue and let the devs decide if they want to create a new issue.

**Comment by alankilborn** [comment]
Tested in N++ 8.4.4 (current version as of this writing) and still a problem, exactly as described above.

**Comment by sskras** [comment]
Does anybody from the developers cares about the issues:)?

**Comment by alankilborn** [comment]
> Does anybody from the developers cares about the issues:)?

I certainly think the developers care...but there are a lot of open issues.
