### ISSUE TITLE
Find direction reversed with Enter or Shift+Enter

### ISSUE THREAD

**Issue by tosione** [notepad-plus-plus/notepad-plus-plus#8156]
### Find direction reversed with Enter or Shift+Enter

In the find window, when hitting Enter, or Shitft+Enter, the find directions are reversed.
This happened in v7.8.5 and remains in v7.8.6.

### Steps to Reproduce the Issue

1. Press Ctrl+F to open find window
2. Write text to find
3. Press Enter or Shift+Enter

### Expected Behavior

- Enter: search forward
- Shift+Enter: search backward 

### Actual Behavior

- Enter: searches backward
- Shift+Enter: searches forward

### Debug Information

Notepad++ v7.8.6   (32-bit)
Build time : Apr 21 2020 - 15:17:06
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS Name : Windows 10 Home (64-bit) 
OS Version : 1909
OS Build : 18363.778
Plugins : HexEditor.dll mimeTools.dll NppConverter.dll NppExport.dll _CustomizeToolbar.dll

**Comment by sasumner** [comment]
What is your setting for the _Backward direction_ checkbox when doing this?

Proper behavior is:

* With _Backward direction_ **ticked**, _Enter_ alone searches from caret toward top of document; _Shift+Enter_ searches from caret towards end of document

* With _Backward direction_ **unticked**, _Shift+Enter_ searches from caret toward top of document; _Enter_ alone searches from caret towards end of document

**Comment by tosione** [comment]
Auch, 
Never noticed this setting: The backward direction was set, which explains everything. 
So this is not a bug.
Thanks for the help.
