### ISSUE TITLE
2nd last update is detected and downloaded when checked for N++ update in Linux

### ISSUE THREAD

**Issue by nikunjbhatt** [notepad-plus-plus/notepad-plus-plus#8166]
### Description of the Issue
I am running N++ with PayOnLinux in Fedora 30 x64. Just now I opened Notepad++ v7.8.4 and it prompted me to update. I allowed to download and update, but it downloaded and installed the v7.8.5 however the latest released version, as of writing this issue, is v7.8.6. I tried closing and reopening N++ and checking for update from '?' (Help) menu from N++ multiple times but it is showing message "No update is available". So, it seems it is checking 2nd last update in Linux.

### Steps to Reproduce the Issue
1. Click on '?' (Help) menu in N++
2. Click on 'Update Notepad++' option from the menu

### Expected Behavior
After updating today to v7.8.5, the 'Update Notepad++' should inform that new version 7.8.6 is available and ask to update. And upon allowing to download, the N++ should update to the latest version 7.8.6.

### Actual Behavior
On clicking the 'Update Notepad++' option, a message box is showing saying "No update is available".

### Debug Information
Notepad++ v7.8.5   (64-bit)
Build time : Mar  4 2020 - 11:08:34
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : ON
Local Conf mode : OFF
OS Name : Microsoft Windows 7 (64-bit) 
OS Build : 7601.0
WINE : 5.0
Plugins : ComparePlugin.dll DSpellCheck.dll Explorer.dll MarkdownViewerPlusPlus.dll mimeTools.dll NppConverter.dll NppExport.dll NPPJSONViewer.dll XMLTools.dll zoomdisabler_x64.dll

**Comment by dail8859** [comment]
The auto updater is usually not triggered right away incase there is some critical issue found. Usually within a week of release (it's been ~2 days currently) the the update will be made available for the auto updater.
