### ISSUE TITLE
Support for background saving of file.

### ISSUE THREAD

**Issue by sanastasiou** [notepad-plus-plus/notepad-plus-plus#817]
Hi,

as a plugin developer, I'm missing a feature which is present on other IDEs. That is, the ability to save any opened file in the background.

The use case is normal if you add support for any language that you have to either compile, or a DSL for example where you have to check if you have some errors in your files. By saving all files in a project the plugin can check if the new files contain errors etc.

Example : Visual Studio saves all files before build. 
To do this currently, I need to activate every file I want to save, save it and then return to the original.

While this works, it seems clumsy at a user level.
So the feature would be e.g. a message SAVE_FILE, taking the parameter of a currently opened file and it should not trigger the "File changed in background event" since the user explicitly selected the behavior.

Is this possible to implement this at some point in the future? I could also offer implementation support if you tell me where to look :)

Best Regards

**Comment by cmeriaux** [comment]
Hello,
python script plugin can activate any opened buffer ([help link] ( http://npppythonscript.sourceforge.net/docs/latest/notepad.html#Notepad.activateBufferID)) and save it ([help link](http://npppythonscript.sourceforge.net/docs/latest/notepad.html#Notepad.save))
It also can register a callback to execute a fonction when a file is saved ([help link](http://npppythonscript.sourceforge.net/docs/latest/notepad.html#Notepad.callback))
My point is python script may be a good inspiration for you ([repository link](https://github.com/bruderstein/PythonScript))

**Comment by dail8859** [comment]
@cmeriaux Any other plugin written in any language can do the exact same thing, because they all must use the underlying [messages and notifications](http://docs.notepad-plus-plus.org/index.php/Messages_And_Notifications).

**Comment by dail8859** [comment]
Just from a quick glance at the code it looks like it may not be too hard. If you look at how [`NPPM_SAVEALLFILES`](https://github.com/notepad-plus-plus/notepad-plus-plus/blob/d7ca1eaaf682fcb2c81305e4fa87ee6e0a327521/PowerEditor/src/NppBigSwitch.cpp#L400) is handled, it just calls [`fileSaveAll()`](https://github.com/notepad-plus-plus/notepad-plus-plus/blob/dc4897c8f293d769b2d9e7d168dd47fb9c9d2d05/PowerEditor/src/NppIO.cpp#L1121) which loops through the buffer ids and saves them. In *theory* it should be fairly straight forward to add what you are proposing.

**Comment by sanastasiou** [comment]
OK, I'll try implementing this and to a pull request :)

**Comment by sanastasiou** [comment]
Please review this and let me know if it can be merged.

**Comment by sanastasiou** [comment]
Pull request now properly done.
