### ISSUE TITLE
notepad search does not work

### ISSUE THREAD

**Issue by atthetop0** [notepad-plus-plus/notepad-plus-plus#8172]
### Description of the Issue

when search for a known string in a file notepad++ says not found
### Steps to Reproduce the Issue

1. open file
2. search for string
3. not found

### Expected Behavior

to find the string. notepad finds it instantly
### Actual Behavior

text not found
### Debug Information

notepad++ v7.8.5 (64bit)
![notepad_issue](https://user-images.githubusercontent.com/64311001/80278622-fcdc3700-8708-11ea-90f2-394aa367dc0b.png)

**Comment by sasumner** [comment]
Can you attach the file?  Or a part of the file that this problem manifests on?

**Comment by atthetop0** [comment]
https://we.tl/t-D8x0SN3dAs

**Comment by sasumner** [comment]
Just attach the file here.

**Comment by atthetop0** [comment]
says file format not supported

**Comment by sasumner** [comment]
Zip it?

**Comment by atthetop0** [comment]
[cleaned_data.zip](https://github.com/notepad-plus-plus/notepad-plus-plus/files/4532916/cleaned_data.zip)

**Comment by atthetop0** [comment]
turnsout i copy pasted the text from excel and when pasted in notepad++ the string in not found. when i copy and pasted the string here: https://onlineutf8tools.com/convert-utf8-to-bytes the string 9116119 its byte equiv is ef bb bf 39 31 31 36 31 31 39 and if i type 9116119 in the tool its byte equivalent is 39 31 31 36 31 31 39. the ef bb bf is causing the issue i guess. not sure what that is. it's invisible everywhere...

**Comment by atthetop0** [comment]
actually the excel file i copy/pasted the text from has a small space before it, just realized. if i move the cursor to the absolute left and delete it goes back 1 character. so there is the ef bb bf 39 character there. but if u copy/paste from excel to notepad++ it doesn't strip/ignore it but notepad does.

**Comment by xylographe** [comment]
0xEF, 0xBB, 0xBF is the UTF-8 representation of the BOM (U+FEFF BYTE ORDER MARK).

**Comment by atthetop0** [comment]
here's the excel file
[excel.zip](https://github.com/notepad-plus-plus/notepad-plus-plus/files/4532945/excel.zip)

**Comment by sasumner** [comment]
Regardless, it doesn't seem like an issue with the Notepad++ searching functions....

**Comment by atthetop0** [comment]
is should show the charter even as whitespace. it doesn't but uses it in the search? seems like a clear issue here. it's very misleading. i've been scratching my head for hours until i opened it in notepad.

**Comment by xylographe** [comment]
Ideally, control characters would be displayed the way they are displayed in the editor. For example:

![ControlCharDisplay](https://user-images.githubusercontent.com/8535293/80280921-a91d1e00-8707-11ea-9b04-7f454e5f27bb.png)

However, I think, technically this might not be possible.

**Comment by dail8859** [comment]
@xylographe One could create a new Scintilla instance and tweak it a a good bit. That's what I do for the LuaScript console input.

**Comment by atthetop0** [comment]
if it can't be displayed strip it. at least the search is accurate to what is displayed then.
