### ISSUE TITLE
"Default directory" setting breaks "Follow current doc" functionality

### ISSUE THREAD

**Issue by vlakoff** [notepad-plus-plus/notepad-plus-plus#8175]
Having a document open,
* Go to "Preferences > Default Directory" and make sure "Follow current document" is choosed
* Go to "Find in Files" and check "Follow current doc."
* As expected, the Directory is updated to the path of the currently open document.

Then,
* Go to "Preferences > Default Directory" again, and choose the 3rd item (enter a custom directory)
* Go to "Find in Files" and check "Follow current doc."
* The Directory is not updated to the path of the currently open document, but to the directory you have entered in the settings.

Tested on Notepad 7.8.6 and several previous versions

**Comment by vlakoff** [comment]
Just noticed it is a duplicate of #8045.

**Comment by sasumner** [comment]
Closing because of the duplication.
