### ISSUE TITLE
Add "community" link to the N++ homepage

### ISSUE THREAD

**Issue by asvc** [notepad-plus-plus/notepad-plus-plus#8179]
### Description of the Issue
Link to the [Community](https://community.notepad-plus-plus.org/) is present at the GitHub repository, but not at the project's homepage.

### Steps to Reproduce the Issue
1. Take a stopwatch
1. Open the homepage, start the stopwatch
2. Try to find a link to discussion forums
1. Maybe open "Resources" link
3. Give up

### Expected Behavior
It takes <2 seconds to find the link from the frontpage.

### Actual Behavior
![image](https://user-images.githubusercontent.com/300146/80366534-94d44f00-88c8-11ea-9f62-749fa48f5ec1.png)

### Debug Information
https://notepad-plus-plus.org/

**Comment by sasumner** [comment]
Agree.

As an aside that may not be well-known, there's a link to the main forum site from the `?` menu in the software itself:

![image](https://user-images.githubusercontent.com/30118311/80367838-c530d480-8859-11ea-9dee-7063ea4874c5.png)

**Comment by donho** [comment]
Does the `Online Help` not ring the bell?

**Comment by sasumner** [comment]
I retract my "Agree".
`Online Help` link is sufficient.

**Comment by donho** [comment]
So I think this issue can be closed.

**Comment by asvc** [comment]
I was naively expecting to see "Community", "Forum" or something along these lines.
"Online help" in my mind translates to "Online manual is here".

Maybe that's just me.

**Comment by sasumner** [comment]
>"Online help" in my mind translates to "Online manual is here".

Nicely, the online manual is linked from there as well.  :-)

**Comment by asvc** [comment]
> Nicely, the online manual is linked from there as well. :-)

Touché!
