### ISSUE TITLE
Unable to load custom plugin

### ISSUE THREAD

**Issue by AntonioCS** [notepad-plus-plus/notepad-plus-plus#8187]
### Description of the Issue

I have followed the plugin template provided here https://github.com/npp-plugins/plugindemo
I go to Settings > Import > Import plugin(s)...
I select my dll.
Nothing happens....
No error, nothing.

I restart and go to the Plugins menu, there is nothing there.

### Debug Information

Notepad++ v7.8.1   (64-bit)
Build time : Oct 27 2019 - 22:57:19
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS Name : Windows 10 Pro (64-bit) 
OS Version : 1909
OS Build : 18363.778
Plugins : mimeTools.dll NppConverter.dll NppExport.dll

**Comment by dail8859** [comment]
That template is kind of old and I'm not sure how maintained it is.

Have you tried just putting the plugin in the appropriate folder instead of importing it through the menu?

**Comment by sasumner** [comment]
@AntonioCS , dail's suggestion should work to make sure your plugin is valid.  Please let us know if that works or not.

**Comment by AntonioCS** [comment]
@dail8859 is there another template? One more recent?
@sasumner is there any logs that notepad++ writes to? Something that will show me if something is wrong.

**Comment by AntonioCS** [comment]
I copied the dll `NppPluginMine.dll` to `C:\Program Files\Notepad++\plugins`
Should I see it appear somewhere?
It's not in the `Plugins Admin` nor is it in the `Plugins` menu

**Comment by sasumner** [comment]
> is there any logs that notepad++ writes to?

I don't believe so, for this.
The best way to debug would be to step through Notepad++ source code as it tries to load your plugin, if you are capable of doing that.  (Not that you aren't a programmer with skills, just don't know if you'd have the setup for singlestep debug of N++)

You'd want your plugin here:
`C:\Program Files\Notepad++\plugins\NppPluginMine\NppPluginMine.dll`

**Comment by AntonioCS** [comment]
@sasumner well.. that seems to have worked.
Are there any resources for plugin development?
I followed the example and I am able to put text in a open document but it seems to clear everything instead of appending.

Any examples/guides out there? Thanks again for helping me. (also would like to know if the template I used has any issues with the `Import` system, will try to see if I can step through the code, are there any guides on how the code is structured?)

Thanks again

**Comment by sasumner** [comment]
>I followed the example and I am able to put text in a open document but it seems to clear everything instead of appending.

I'm not familiar with the example.  (I suppose I could go and look at what it does; lazy though).
I'll just guess that it uses SCI_SETTEXT ?  That sets the text for the entire document, erasing anything that was there before.

I'm not a plugin developer, I guess just never got into it.  @dail8859 is a C++ plugin developer however, so his plugins might be good to look at (the source).  https://github.com/dail8859

> are there any guides on how the code is structured?

Not that I know of.

**Comment by dail8859** [comment]
I'd recommend using this to start with. 

https://github.com/dail8859/cookiecutter-npp-cpp-plugin

It is a template tolhat requires python to generate it but it should give you a working example from the very start.

**Comment by AntonioCS** [comment]
@sasumner thanks

@dail8859 
Looking at the example code in the old template stuff I can see this piece:

```
    // Open a new document
    ::SendMessage(nppData._nppHandle, NPPM_MENUCOMMAND, 0, IDM_FILE_NEW);

    // Get the current scintilla
    int which = -1;
    ::SendMessage(nppData._nppHandle, NPPM_GETCURRENTSCINTILLA, 0, (LPARAM)&which);
    if (which == -1)
        return;
    HWND curScintilla = (which == 0)?nppData._scintillaMainHandle:nppData._scintillaSecondHandle;

    // Say hello now :
    // Scintilla control has no Unicode mode, so we use (char *) here
    ::SendMessage(curScintilla, SCI_SETTEXT, 0, (LPARAM)"Hello, Notepad++!");
```

There seem to be a lot of `SendMessage` commands. Is there a place where I can see what this is or at least get a better understanding of what is going on?

Thanks again

**Comment by dail8859** [comment]
There are two main components to communicate with.

The main Notepad++ application: https://npp-user-manual.org/docs/plugin-communication/

The Scintilla editor: https://www.scintilla.org/ScintillaDoc.html

**Comment by AntonioCS** [comment]
Thanks!
