### ISSUE TITLE
After a file search, the folder where to search changes always to default value

### ISSUE THREAD

**Issue by Bernhardino** [notepad-plus-plus/notepad-plus-plus#8188]
### Description of the Issue

If I do a text search in all files of a folder, the folder is reset after every search to "C:\Program Files (x86)\Notepad++" (instead remaining unchanged).

### Steps to Reproduce the Issue

1.  Menu "Search" -> "File Search" (probably, I've got the german version...)   OR   Ctrl+Shift+F
2.  Do a specific search
3.  The next time I do a file search, the searched text and the filter remain unchanged, but the folder name chanches to the default "C:\Program Files (x86)\Notepad++".

### Expected Behavior

It would be clearly better if the name of the folder remains unchanged. Nobody will search in "C:\Program Files (x86)\Notepad++".

### Actual Behavior

The folder chanches to the default value "C:\Program Files (x86)\Notepad++"

**Comment by sasumner** [comment]
@Bernhardino 

What is your setting in the Preferences here?:

![image](https://user-images.githubusercontent.com/30118311/80626062-f48f3f00-8a1b-11ea-8e24-8b0e28bee7fa.png)

I suspect you might have the bottom radiobutton selected but an empty box to the right of it?

**Comment by Bernhardino** [comment]
@sasumner 

Hi, both assumptions are wrong: I DO have selected the first radiobutton "Follow current document" (by the way, I think, this relates only to open/save), and the red checkbox IS ticked. BUT: If I DESELECT the red checkbox, I obtain the desired behaviour. The german translation of "Follow current doc." is rather poor, so I didn't imagine what this checkbox will do. Anyway, problem solved - thank you. As it isn't a bug, can you delete my post?

**Comment by sasumner** [comment]
>both assumptions are wrong

Not my day for being right :-)

>the first radiobutton "Follow current document" (by the way, I think, this relates only to open/save)

Not only to open/save...  The logic for the starting-directory-of-a-search is somewhat bound up together with it; that's why I mentioned it.  I'm currently trying to sort it out in the context of the other issue I mentioned ( #8045 ).

>problem solved ... can you delete my post?

Nothing here gets deleted but I will close it for you (which you as the originator could have done as well).
