### ISSUE TITLE
parenthesis and brackets highlighting bug when jumbled with links when set to be clickable

### ISSUE THREAD

**Issue by GhbSmwc** [notepad-plus-plus/notepad-plus-plus#8189]
I balanced the parenthesis right when testing out the regular expression:
![image](https://user-images.githubusercontent.com/13095760/80663350-b6b50980-8a61-11ea-8fb9-92ae51e39671.png)
Try having your cursor on the parenthesis and brackets highlighting bug to see for yourself:
```
[^(?'URL'https://([^[:s:]]+))\R\g'URL' success]
```
It appears to be caused by this:
![image](https://user-images.githubusercontent.com/13095760/80663546-4bb80280-8a62-11ea-918a-db0f7dae1f52.png)

Because when disabling that, the red highlighting of grouping symbols then works properly.

**Comment by Uhf7** [comment]
It works correctly in 7.8.7.

I could verify the described effect in 7.8.6, but it is gone in 7.8.7.
