### ISSUE TITLE
Multiple instances of NP++ result in session auto-backup failures

### ISSUE THREAD

**Issue by MarkMaldaba** [notepad-plus-plus/notepad-plus-plus#819]
If you have a single instance of NP++ running, then the automatic session backup feature works like a charm.

However, I opened a second instance to work on a separate set of files without losing my current tabs or having them get in the way (as I often do) and then closed that second instance.

When I then closed the first instance, which contained some unsaved files, I got the following message:

```
Your backup file cannot be found (deleted from outside).
Save it otherwise your data will be lost
Do you want to save file "new 1"?

    [Yes] [No] [Cancel]
```

The expected behaviour is that NP++ works as it normally does - it closes without a prompt, saving my in-progress session, and when I re-open NP++ everything restored as I left it.

The specific bug being reported here is, I guess, that if no backup file for the current session is found when NP++ is closed, that it is automatically created without requiring user intevention at the point NP++ is closed (and at the next auto-backup interval too - as I expect there is no background backup taking place either).

There is probably also a more general issue to do with smoother handling of the session auto-backup when there are multiple NP++ instances open, as I suspect that having two sessions open results in each one overwriting the other one's backup file every time the auto-backup is triggered.  It would be better if each instance had its own backup store, but I am aware there are probably some complexities involved in making that work sensibly.

**Comment by sanastasiou** [comment]
There are also other problems being looked at regarding sessions right now. e.g. If you close Npp while a file is edited without saving, it correctly reopens as "not saved", but then, even if you do save it the dirty flag remains red "not saved".

**Comment by oliezekat** [comment]
I submit you to install "Explorer" plugin which purpose a "Favorites" panel where we can save fastl current tabs as a session and switch fast between saved sessions.

Nb: I don't use "Explorer" main panel, I prefer "Light Explorer". No conflict :)

**Comment by MarkMaldaba** [comment]
That doesn't help with the fact that auto-backup and auto-save-on-close are broken once a second NP++ instance has been opened.

(Also, I haven't tested it, but how does "Explorer" cope with multiple NP++ instances being open at the same time?  Do sessions saved in one instance show up in the other, or do they wipe each other's configuration as per the problem described here?)

**Comment by oliezekat** [comment]
My tip not solve multi-instance problem. Npp don't support this. Sessions feature is a way to not need multi-instance.
"Explorer" use Npp's sessions feature. I doubt you can save and share sessions in both instance.

**Comment by MarkMaldaba** [comment]
> My tip not solve multi-instance problem. Npp don't support this. Sessions feature
> is a way to not need multi-instance.

So long as NP++ supports both sessions and multi-instance, then they should work nicely together.  Using one NP++ feature should not break another!

**Comment by MetaChuh** [comment]
we are closing this issue due to its age and multiple newer notepad++ versions since it was filed.

please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html).
if your issue persists, and it is still of relevance to you, please feel free to file a new issue.

thank you for your help and best regards.

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
```
[<kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd>](https://notepad-plus-plus.org/community/)
