### ISSUE TITLE
no dark title bar in windows 10

### ISSUE THREAD

**Issue by kikloo** [notepad-plus-plus/notepad-plus-plus#8190]
### Description of the Issue
I am using dark more in Windows 10, all other apps title bar etc becomes dark, but notepad stays white. Can you please make it so that notepad uses system's default colors ? Thanks.

### Steps to Reproduce the Issue

1. 
2. 
3.

**Comment by ozone10** [comment]
You can try [DarkNpp](https://github.com/ozone10/Npp-DarkNpp) plugin. Unfortunately it does not change title bar based on system default colors, but it can make it dark.

Also I am not coder, so there might be some issues.

**Comment by chcg** [comment]
@ozone10 Maybe you want to add your plugin to https://github.com/notepad-plus-plus/nppPluginList, so it is available for more users.

**Comment by ozone10** [comment]
@chcg I will look into it.

**Comment by sbuckridge** [comment]
So me and some friends looked into this a while ago and it seems that the title bar and window itself is hard coded using really old methods from like 2001. Unless someone knows how to operate those or are willing to learn how to use it, the color of the title bar isn't easily changeable. Someone feel free to correct me if I'm wrong.

**Comment by ozone10** [comment]
> 
> 
> So me and some friends looked into this a while ago and it seems that the title bar and window itself is hard coded using really old methods from like 2001. Unless someone knows how to operate those or are willing to learn how to use it, the color of the title bar isn't easily changeable. Someone feel free to correct me if I'm wrong.

Using undocumented winapi you can make it dark.

**Comment by Sporking** [comment]
I recently upgraded to Windows 10, and moved my system to dark mode. Everything worked fine except for Notepad, which blasts my eyes with blinding light. I therefore started looking for a Notepad alternative. Notepad++ seemed like an obvious choice. However, I was disappointed to discover that there seems to be no way to make the entire application dark (using dark themes help, but that just means that the title bar, etc. are blinding as compared to a dark-themed editor window and to the rest of my Windows desktop.)

Unfortunately, this is a dealbreaker for me. I will have to uninstall Notepad++ for now, and will be investigating other text editors (Sublime, etc.) instead. (Unfortunately, once I have paid for a commercial app like Sublime, etc., it's unlikely that I will use Notepad++ again.)

Sorry. This seems like a nice app in general, and I usually prefer to support Open Source when possible (and I do my part by submitting bug reports, etc.), but as I said, true dark mode (not just a dark theme) is a dealbreaker for me, and I'm sure many other people.

In general, I think the interface should default to being light if Windows is set to light, and dark if Windows is set to dark. It should still be possible, however, to override the Windows settings and force light mode or dark mode.

Here are some issues in the issue database that are asking for the same feature. I'm posting this comment to each of them to raise awareness of the others. It would probably be good for someone with the ability to do so to mark two of these as duplicates of a third, to consolidate discussion:

[Enhancement : Dark theme/ Dark mode Adaption #5852](https://github.com/notepad-plus-plus/notepad-plus-plus/issues/5852)

[[Feature request] Interface - Dark theme](https://github.com/notepad-plus-plus/notepad-plus-plus/issues/7692)

[no dark title bar in windows 10 #8190](https://github.com/notepad-plus-plus/notepad-plus-plus/issues/8190)

**Comment by kaaax0815** [comment]
+1 would be amazing

**Comment by Heislitz** [comment]
+1

**Comment by CommanderPirx** [comment]
+1

**Comment by ozone10** [comment]
you can now choose dark mode, which will make title bar dark

**Comment by ArkadiuszMichalski** [comment]
Please use Dark Mode:
![image](https://user-images.githubusercontent.com/2730894/130226481-bd0f44d0-28c8-4a22-b5da-d2dfa1f06066.png)
