### ISSUE TITLE
[Plugin request] indent-rainbow

### ISSUE THREAD

**Issue by zoulja** [notepad-plus-plus/notepad-plus-plus#8193]
VS Code has really nice extension ‘indent-rainbow’(**~800k installations**)
“This extension colorizes the indentation in front of your text alternating four different colors on each step”. Really helps to improve readability.
![изображение](https://user-images.githubusercontent.com/10187203/80750377-a28c0d80-8b30-11ea-9903-983aebe98e1c.png)
It would be nice if Notepad++ could support such function also

Link to Scintilla discussion https://sourceforge.net/p/scintilla/feature-requests/1348/

**Comment by dail8859** [comment]
This repository is for core Notepad++ functionality. It would be better to post a request on the community forum or look into writing the plugin yourself.

https://community.notepad-plus-plus.org/

**Comment by sasumner** [comment]
Already discussed on the Community:
https://community.notepad-plus-plus.org/topic/19300/plugin-request-indent-rainbow

**Comment by zoulja** [comment]
> This repository is for core Notepad++ functionality. It would be better to post a request on the community forum or look into writing the plugin yourself.
> 
> https://community.notepad-plus-plus.org/

So from community forum you sent me to github and from github to community forum.
Really cool solution to avoid requests, I like it

**Comment by zoulja** [comment]
> Already discussed on the Community:
> https://community.notepad-plus-plus.org/topic/19300/plugin-request-indent-rainbow

Yes, dear, already discussed that need to submit FR here. And what are you doing? Cycle reference. You're my here, dear sir, keep going

**Comment by dail8859** [comment]
You asked for someone to write a plugin (which is what this request is). This is not the place for that.

If you are asking for a core Notepad++ feature, then yes this is the appropriate place.

The functionality you described would be best created as a plugin.

**Comment by zoulja** [comment]
Please try to think as end user, not as developer. Users and community are the heart of any software project. 

I'm asking for a function.

For me as Notepad++ end user(more than 15 years) it's not a question of "I want plugin" or "I want core".
Please rephrase this request if you think it doesn't  reflect idea properly and reopen

**Comment by dail8859** [comment]
> I'm asking for a function.

Correct, and there are several ways to implement it. Some users want as much functionality in the core application, while others want everything to be a stand alone plugin. Since this was a request for a plugin...and this repository does not create/maintain any plugins...I've closed the issue.

I can certainly understand why the functionality itself would be useful, and it would be best if it was written as a plugin.

**Comment by sasumner** [comment]
As far as I know, ALL Notepad++ developers are also heavy Notepad++ end users, so there's no "disconnect" on that point.

It's not going to be reopened as an issue for Notepad++ core; sorry.

>Users and community are the heart of any software project.

And this is a prime example where a member of the user community could jump in and provide this plugin.

**Comment by zoulja** [comment]
Let's think together.
How someone can jump in and provide it if you just close it? 
How some new enthusiast who could help can know what project and community need in such approach?
To me this is really confusing

**Comment by dail8859** [comment]
This functionality will not be added to this repository.

Since you posted a request on the forum for someone to create a plugin, some new enthusiast will see your forum post there.
