### ISSUE TITLE
[Feature Suggestion] Have the installer autodetect a portable installation

### ISSUE THREAD

**Issue by timint** [notepad-plus-plus/notepad-plus-plus#8196]
I have a portable Notepad++ installation. And every now and then the autoupdater kicks in but installs it to C:\Programs Files\Notepad++ instead.

This is getting annoying. So a feature suggestion that the installer autodetects a portable installation and auto check the "Don't use %appdata" option.

**Comment by dzek69** [comment]
+1 and this also happens for non-portable installs, but also for "global" installs in non-default directory.

This should be easier to add as there is no need to modify much about the update process for portable installs, just add some values to the registry - I don't know if I should open separate issue for that.

**Comment by sXNA** [comment]
Fixed by https://github.com/notepad-plus-plus/notepad-plus-plus/commit/a6a1442babea25e52feedf34c707cf8d72266c2e

**Comment by timint** [comment]
👍
