### ISSUE TITLE
Feature Request: Add top/bottom document splitter control.

### ISSUE THREAD

**Issue by warvair** [notepad-plus-plus/notepad-plus-plus#8197]
The Visual Studio IDE has a document splitter control that you can pull down which splits the current document/tab into 2 panes (top/bottom) so you can easily view or edit 2 sections of the same file at the same time. Pulling it back up to the top restores the original view.

You already have the clone view and rotate, but having a simple control that does this is much more  user friendly and intuitive. Also, you could remove the tab/filename on the lower pane making the interface a bit cleaner.

I don't use this control that often, but when I need it, I miss it in Notepad++.
 
![image](https://user-images.githubusercontent.com/3371879/80833240-22ab8500-8bbc-11ea-8d34-0056911c7ee1.png)

**Comment by sasumner** [comment]
Thanks for your suggestion, but we're going to keep Notepad++ the way it is in this regard.
