### ISSUE TITLE
[Feature] Show git status in the sidebar

### ISSUE THREAD

**Issue by asvc** [notepad-plus-plus/notepad-plus-plus#8204]
### Description of the Issue
Status of the file that is tracked by `git` isn't displayed in the editor

### Steps to Reproduce the Issue
1. Open any file that is tracked by git
2. Change some lines
3. No visual indication happens

### Expected Behavior
Gutter has <kbd>+</kbd>, <kbd>-</kbd> or <kbd>/</kbd> signs to indicate lines that are added, removed or changed respectively.

### Actual Behavior
Please refer to the reproduction steps.

### Debug Information
```
Notepad++ v7.8.6   (64-bit)
Build time : Apr 21 2020 - 15:23:03
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS Name : Windows 10 Pro (64-bit) 
OS Version : 1909
OS Build : 18363.778
Plugins : BetterMultiSelection.dll DSpellCheck.dll ElasticTabstops.dll mimeTools.dll NppConverter.dll NppExport.dll SurroundSelection.dll 
```

Visual explanation:
![Visual explanation](https://changelog.com/wp-content/uploads/git-gutter-screenshot.png)

Related discussion in community forums: https://community.notepad-plus-plus.org/topic/19302/show-git-status-in-the-sidebar

**Comment by sasumner** [comment]
Thank you for your suggestion but at the current time we don't believe this is something that belongs in Notepad++ core.  Perhaps a plugin?
