### ISSUE TITLE
Confirmation Dialog hotkeys wiped out

### ISSUE THREAD

**Issue by bsanders1979** [notepad-plus-plus/notepad-plus-plus#8208]
Since the last update, the confirmation dialog has some new buttons (ie. Yes/No to all). For whatever reason, the hotkeys for Yes/No/Cancel seem to have been wiped out. Maybe I'm imagining things, but I seem to remember to be able to press N when it pops up.

### Steps to Reproduce the Issue
1. Ctrl-N
2. Press any key
3. Ctrl-W
4. Pressing N does nothing

### Expected Behavior
"No" button should be clicked/selected

### Actual Behavior
Nothing

**Comment by xylographe** [comment]
Update to **Notepad++ v7.8.6**.
Delete file **`%APPDATA%\Notepad++\nativeLang.xml`** (if exists).
Start Notepad++.

**Comment by sasumner** [comment]
@bsanders1979 
Take @xylographe 's advice or provide your version info if that doesn't seem to work.
