### ISSUE TITLE
XML section collapsed

### ISSUE THREAD

**Issue by NicoFC34** [notepad-plus-plus/notepad-plus-plus#8209]
### Description of the Issue
When you delete a XML section that is collapsed, it doesn't work well every time.

### Steps to Reproduce the Issue
1. Load a big and complex XML file,
2. Collapse some XML section,
3. Try to delete some collapsed section

### Expected Behavior
The section should be removed correctly by keeping the XML integrity.

### Actual Behavior
The XML file is corrupted with missing nodes.

### Debug Information
N/A

**Comment by sasumner** [comment]
Can you show a short example of what you mean?

**Comment by NicoFC34** [comment]
Hi,

Yes, that's possible:

- Collapse a XML section like this and press del button.

[image: image.png]

Instead of deleting the entier section collapsed, only the first row has
been removed.

[image: image.png]

Have a nice day.

Nicolas

**Comment by sasumner** [comment]
@NicoFC34 , I see no images; this is what I see:

![image](https://user-images.githubusercontent.com/30118311/80966919-777d1480-8de3-11ea-8b44-22439ef36d09.png)

**Comment by NicoFC34** [comment]
With images attached to this email.
Hope this helps you.

**Comment by NicoFC34** [comment]
![Sans titre](https://user-images.githubusercontent.com/51700300/80967237-4b2ebb80-8e16-11ea-8ebb-91e3df2f61d0.png)
![Sans titre2](https://user-images.githubusercontent.com/51700300/80967239-4bc75200-8e16-11ea-8dd5-e5ce0866fa4c.png)

Sorry, I just understand that you repplied to me on the website and not by email.
Here are the righ screenshots.

**Comment by sasumner** [comment]
@NicoFC34 Here's an example of how it works.

Start with:
![image](https://user-images.githubusercontent.com/30118311/80967414-5668f380-8de4-11ea-82bb-d0dee3e3eeeb.png)

Decide you want to delete all in the `<Entries>` section, lines 7-20.  Collapse that section to make it easier:
![image](https://user-images.githubusercontent.com/30118311/80967558-8dd7a000-8de4-11ea-94b1-ee2d7dea6ee3.png)

Select the entire line 7 and the collapsed block beyond it (easiest way might be to double-click to the LEFT of the line number (on line 7), then press Shift+rightarrow to move the caret to the first column on line 21), it will look like this:
![image](https://user-images.githubusercontent.com/30118311/80968005-41d92b00-8de5-11ea-8340-c1cfac019924.png)

Press the Delete key.  The result will be:
![image](https://user-images.githubusercontent.com/30118311/80968085-5ddccc80-8de5-11ea-8688-b340aa946568.png)

**Comment by NicoFC34** [comment]
Excuse me @sasumner but it should work also in my usecase?
I agree, it works with your usecase, but I think I'm not the only guy to use Notepad++ like this...

**Comment by sasumner** [comment]
>but it should work also in my usecase?

No, because I can see your selection falls short of including the collapsed block:

![image](https://user-images.githubusercontent.com/30118311/80969253-53233700-8de7-11ea-88f7-ed2d985dd76c.png)

> I think I'm not the only guy to use Notepad++ like this...

I believe it has come up before, yes.
Scintilla is the editing component that Notepad++ uses, and it behaves the way I described.
As it is a Scintilla editing characteristic, there is nothing that can be reasonably done about it on the Notepad++ side.
If Scintilla functionality ever changes in this regard, Notepad++ will automatically pick up the change as well.
We can apply the "Scintilla dependent" label to this issue, but that's about all that can be done.

**Comment by NicoFC34** [comment]
Ok thanks for your explanation.

That's very sade because I think that all famous IDE like VS or Eclipse works like that.
And in fact, I select the entire section from the end to the beginning, but finaly, I select the entire section... so, it's "normal" to delete it entirely. 

Hope this will be fixed one day in the module that you use.
Notepad++ is a great text editor, that I used every day, it's the only "bug" I met during those few last years.

Have a nice day.

**Comment by sasumner** [comment]
>I select the entire section from the end to the beginning, but finaly, I select the entire section... so, it's "normal" to delete it entirely.

I have no idea what the above means.

>Notepad++ is a great ...  it's the only "bug" I met ...

Maybe you missed the point, but it isn't a bug in Notepad++.
It is the way it works, in Scintilla.
If anything, it is a bug in Scintilla.
But, again, I don't think so; I think it is just how it works.

**Comment by NicoFC34** [comment]
Sorry for my english, I would like to say that: if I select the XML section that is collapsed from the end to the beginning OR from the begginning to the end, it's the same thing => the entire section is selected.

So, if I delete this selection, it's "normal" to delete in this two usecases the entire XML section.

It was my opinion. :-)

Thanks, bye!
