### ISSUE TITLE
Add TeraTerm Language (TTL) support

### ISSUE THREAD

**Issue by el-coder-sb** [notepad-plus-plus/notepad-plus-plus#8216]
### Description of the Issue
Add TeraTerm Language (TTL) support for syntax highlighting

### Details
TeraTerm is a free software terminal emulator with support for a macro language called TTL.

Comments are started with ';' (semicolon). For commands see below 'Keywords1'. 

When using UDL-Editor I get the following entries in userDefineLang.xml

        <UserLang name="TTL" ext="ttl" udlVersion="2.1">
        <Settings>
            <Global caseIgnored="no" allowFoldOfComments="no" foldCompact="no" forcePureLC="0" decimalSeparator="0" />
            <Prefix Keywords1="no" Keywords2="no" Keywords3="no" Keywords4="no" Keywords5="no" Keywords6="no" Keywords7="no" Keywords8="no" />
        </Settings>
        <KeywordLists>
            <Keywords name="Comments">00; 01 02 03 04</Keywords>
            <Keywords name="Keywords1">break call continue do loop end execcmnd exit for next goto if then elseif else endif include mpause pause return until enduntil while endwhile</Keywords>
            <Keywords name="Delimiters">00&apos; 01 02&apos; 03 04 05 06 07 08 09 10 11 12 13 14 15 16 17 18 19 20 21 22 23</Keywords>
        </KeywordLists>
        <Styles>
            <WordsStyle name="DEFAULT" fgColor="000000" bgColor="FFFFFF" fontName="" fontStyle="0" fontSize="" nesting="0" />
            <WordsStyle name="COMMENTS" fgColor="008000" bgColor="FFFFFF" fontName="" fontStyle="0" fontSize="" nesting="0" />
            <WordsStyle name="LINE COMMENTS" fgColor="008040" bgColor="FFFFFF" fontName="" fontStyle="0" nesting="0" />
            <WordsStyle name="NUMBERS" fgColor="FF8000" bgColor="FFFFFF" fontName="" fontStyle="0" nesting="0" />
            <WordsStyle name="KEYWORDS1" fgColor="0000FF" bgColor="FFFFFF" fontName="" fontStyle="1" nesting="0" />
            <WordsStyle name="DELIMITERS1" fgColor="FF8000" bgColor="FFFFFF" fontName="" fontStyle="0" nesting="0" />
        </Styles>
    </UserLang>

As I do not know how to add a completely new language, I would appreciate if someone could do so or tell me how to do (just copying the lines to stylers.xml and langs.xml respectively does not work...)

**Comment by chcg** [comment]
Seems https://github.com/notepad-plus-plus/userDefinedLanguages/blob/master/UDLs/TeradataTools-v13_byTrevorOGrady.xml might be the UDL you are looking for. Or at least a starting point.

**Comment by el-coder-sb** [comment]
Thanks, I was not aware of that collection of UDLs. Good starting point!
As the example has very few highlighting rules (only operators and comments) I created a new one.
I´m not sure whether this language should be added to the UDLs repo or to notepad-plus-plus. 
So I did a pull request on the UDL repo  (https://github.com/notepad-plus-plus/userDefinedLanguages/pulls).

When notepad-plus-plus is supposed to add further languages, I can do a pull request. Just let me know what you prefer.

**Comment by sasumner** [comment]
@el-coder-sb said:

>When notepad-plus-plus is supposed to add further languages...

I'm not very close to this kind of thing, but wouldn't this type of support have to originate in *Scintilla* ?  Maybe @chcg can answer this?

**Comment by dail8859** [comment]
Can this be closed now that https://github.com/notepad-plus-plus/userDefinedLanguages/pull/29 is merged?

**Comment by chcg** [comment]
@el-coder-sb The UDL repo is the right place to add it. So this issue could be closed.
@sasumner If native support within N++ is required than a scintilla lexer is required first. For languages not supported by scintilla much of the functionality of a lexer written in c++ could also be achieved by an UDL. Currently UDLs need to be downloaded and installed by the user.
At some point there was the idea to extend the PluginAdmin with a section for UDLs so to say a UDLAdmin, but I wouldn't expect that in the near future.
