### ISSUE TITLE
Links with special characters are broken

### ISSUE THREAD

**Issue by crisc82** [notepad-plus-plus/notepad-plus-plus#8223]
### Description of the Issue
Broken links with special chars in documents

### Steps to Reproduce the Issue

1. Go to settings->preferences->MISC->Clickable links->Enable
2. Copy/Paste following link in document: https://www.amazon.com/Portable-BlitzWolf-Computer-1920×1080-Consoles/dp/B086PWM4TY

### Actual Behavior
The link is broken to "×" character and you will only see https://www.amazon.com/Portable-BlitzWolf-Computer-1920 as a clickable link.

**Comment by ArkadiuszMichalski** [comment]
This was fixed with new URL parser https://github.com/notepad-plus-plus/notepad-plus-plus/pull/8921.

**Comment by crisc82** [comment]
I just installed Notepad++ v7.9.1 and I confirm this is fixed.
