### ISSUE TITLE
Missing styles in 7.8.6

### ISSUE THREAD

**Issue by quantuumsnot** [notepad-plus-plus/notepad-plus-plus#8224]
Updated to 7.8.6 64bit version and styles are gone - only default xml style is here. GGWP to my favorite Solarized theme :(
The idea of ditching themes and adding them manually is so anti-UX

**Comment by rain0r** [comment]
Hi there,

just download an archive (*not* an installer), for example [npp.7.8.7.bin.x64](https://github.com/notepad-plus-plus/notepad-plus-plus/releases/download/v7.8.7/npp.7.8.7.bin.x64.7z), and extract it.

You'll find a folder called "themes" which contains all themes shipped with notepad++. Just copy them in your personal notepad++ dir oder the installation dir.

Hope that helps.

**Comment by quantuumsnot** [comment]
Already did this workaround, thumbs-up for the solution posted here so the users can use it

**Comment by alankilborn** [comment]
Recommend CLOSURE.
