### ISSUE TITLE
Styling issue

### ISSUE THREAD

**Issue by BacheyG** [notepad-plus-plus/notepad-plus-plus#8225]
### Description of the Issue
I created a custom stlyle with some colored delimeters, and sometimes they override the comment blocks, ruining the styling when editing a file. In these cases, when I select the SAME Language again in the Language dropdown, it gets fixed. It is quite unpleasant this way, would be nice if green commented out parts would always remain green.

**Comment by alankilborn** [comment]
Recommend CLOSURE unless more detail can be provided.

**Comment by ArkadiuszMichalski** [comment]
Close due to lack of details.
