### ISSUE TITLE
"ContextMenu.xml" contains an invalid document url "http://docs.notepad-plus-plus.org/index.php/Context_Menu"

### ISSUE THREAD

**Issue by dbareis** [notepad-plus-plus/notepad-plus-plus#8229]
I was trying to extend the context menu but the URL in the file is invalid.

[BUG] "ContextMenu.xml" contains an invalid document url "http://docs.notepad-plus-plus.org/index.php/Context_Menu".  I suspect this is the case in a lot of similar files (assuming it was ever correct).

```
This site can’t be reached
docs.notepad-plus-plus.org’s server IP address could not be found
```

**Comment by ArkadiuszMichalski** [comment]
@sasumner Can be close, was fixed https://github.com/notepad-plus-plus/notepad-plus-plus/blob/master/PowerEditor/src/contextMenu.xml.
