### ISSUE TITLE
INI file styler ignoring keys (with solution)

### ISSUE THREAD

**Issue by aslze** [notepad-plus-plus/notepad-plus-plus#8230]
INI files (configuration files) only highlight section names and the equals sign between keys and values. But keys and values keep the same default color, as in:

```
[section]
key = value
```

But I found that Scintilla (the Props lexer) also identifies the keys but this is not considered by Notepad++ styler. Keys are identified by **styleID** **5**, named "KEY" (Notepad++ was only using styleID up to 4.

The solution is to add a line to "lexer.model.xml" (and "lexer.xml" in the user's configuration) for name="KEY and styleID="5":

```xml
<LexerType name="ini" desc="ini file" ext="">
	<WordsStyle name="DEFAULT" styleID="0" fgColor="000000" bgColor="FFFFFF" fontName="" fontStyle="0" fontSize="" />
	<WordsStyle name="COMMENT" styleID="1" fgColor="008000" bgColor="FFFFFF" fontName="" fontStyle="0" fontSize="" />
	<WordsStyle name="SECTION" styleID="2" fgColor="8000FF" bgColor="F2F4FF" fontName="" fontStyle="1" fontSize="" />
	<WordsStyle name="ASSIGNMENT" styleID="3" fgColor="FF0000" bgColor="FFFFFF" fontName="" fontStyle="1" fontSize="" />
	<WordsStyle name="DEFVAL" styleID="4" fgColor="FF0000" bgColor="FFFFFF" fontName="" fontStyle="0" fontSize="" />
+++	<WordsStyle name="KEY" styleID="5" fgColor="0000FF" bgColor="FFFFFF" fontName="" fontStyle="2" fontSize="" />            
</LexerType>
```

**Comment by f6fvy** [comment]
I guess you meant "stylers.model.xml" and "stylers.xml" files, right ?

**Comment by aslze** [comment]
I'm sorry. Yes, I meant "stylers.xml" and "stylers.model.xml"

Thanks.
