### ISSUE TITLE
Saving files with ":" gets rid of them

### ISSUE THREAD

**Issue by djixas** [notepad-plus-plus/notepad-plus-plus#8232]
### Description of the Issue
Notepad++ saves files but they don't appear anywhere.

File name "Server List: USA" disappears or appears as "Server List" with 0 KB contents and no .txt extension.

### Steps to Reproduce the Issue

1. Save text file with "Server List: USA" or something else with : 
2. It will "save" and you can open it via "Recent menu" but it won't show in file explorer
3. If you clean the recent file history, the file is lost forever

### Expected Behavior

It should warn that you can't use : in file name or not save at all.
Windows 10

### Actual Behavior

Broken saving

**Comment by sasumner** [comment]
Potential Workaround:  Use "new style" dialog setting:

![image](https://user-images.githubusercontent.com/30118311/81294991-b73f3880-903d-11ea-8683-5e4e043418d7.png)

Which results in:

![image](https://user-images.githubusercontent.com/30118311/81295092-de960580-903d-11ea-8ee6-f77839810cd4.png)

Perhaps non-"new style" should be retired?

**Comment by djixas** [comment]
> Potential Workaround: Use "new style" dialog setting:
> 

That works! Didn't even know about the new style dialog.

**Comment by sasumner** [comment]
@djixas A potential "gotcha" with "new style":  If you create a new file and want it to be named `test.txt` when you save it, you must type `test.txt`; you can't type only `test` and hit Save, because then it will save to an extensionless `test` file.  This does not bother me in the least, but there seems to be a legion of Notepad++ users that are driven up the wall by this behavior.

**Comment by djixas** [comment]
> 

I'm still confused on where these files are saved or how to access them, they open in Notead++ recent list but Windows can't find them, even with hidden files and extensions showing.

**Comment by sasumner** [comment]
>I'm still confused ...
Yes, it is an interesting thing.  Does something like _Process Monitor_ provide any clues, while this save is taking place (this is just a guess, no real idea if it helps or not).

**Comment by alankilborn** [comment]
Recommend CLOSURE of this item as "new"/"old" style no longer exists in 8.4.4 (current version as of this writing) and we are permanently in "new" style mode where this problem does not occur.
