### ISSUE TITLE
Markdown documents ignore all themes

### ISSUE THREAD

**Issue by kphillisjr** [notepad-plus-plus/notepad-plus-plus#8239]
### Description of the Issue
Whenever I open up a Markdown document using Notepad++ the document does not properly format to the current theme.

### Steps to Reproduce the Issue
1. Open any markdown document. An example effected document is this document here:
https://github.com/notepad-plus-plus/notepad-plus-plus/blob/master/ISSUE_TEMPLATE.md
2. open up the "Style Configurator". This is on the menu bar under "Settings" -> "Style Configurator".
3. On the "Style Configurator" Dialog, change the theme to"Default (Styles.xml)". This will result in the following screenshot.
<img width="953" alt="MarkDown_Default" src="https://user-images.githubusercontent.com/1205559/81425273-e1b3f300-911c-11ea-87d3-989ff46827ff.png">
4. Change the currently selected theme to  "Bespin". The theme is not correctly followed resulting in the following screenshot.
<img width="958" alt="MarkDown_Bespin" src="https://user-images.githubusercontent.com/1205559/81425529-5edf6800-911d-11ea-83c8-f9ea79456091.png">
5. Change to any of the other themes. The results will still be the same. 

### Expected Behavior
For markdown documents to properly follow theming rules. This is especially important since some documents could potentially turn unreadable.

### Actual Behavior
Themes are not correctly being applied.

### Debug Information
Notepad++ v7.8.6   (64-bit)
Build time : Apr 21 2020 - 15:23:03
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS Name : Windows 10 Pro (64-bit) 
OS Version : 1909
OS Build : 18363.778
Plugins : mimeTools.dll NppConverter.dll NppExport.dll

**Comment by ArkadiuszMichalski** [comment]
Similar to https://github.com/notepad-plus-plus/notepad-plus-plus/issues/5799.
