### ISSUE TITLE
Feature Request: Simplify Building of Notepad++

### ISSUE THREAD

**Issue by kphillisjr** [notepad-plus-plus/notepad-plus-plus#8240]
This is mostly a simple feature request to make simplify the experience for new users wishing to develop for Notepad++. 

- [ ] Update documentation to clearly state what software is required to build Notepad++. Currently all that is mentioned is Visual Studio.
- [ ] Verify boostregex dependency is still required. From what I have read, the code depends on C++11 features (auto, constexpr, noexcept, etc) , and this means that C++11 regular expressions are supported.
  - ECMAScript by passing```std::regex::ECMAScript```.
  - Basic Posix Regular expressions. ```std::regex::basic```.
  - Extended Posix Regular expressions. ```std::regex::extended```.
- [ ] Update scintilla to version 4.33 or newer.
- [ ] add a single solution file that will automatically build both Notepad++ and Scintilla with a single build command. The Scintilla version 4.33 includes visual studio project files.

**Comment by sasumner** [comment]
@kphillisjr 

>Verify boostregex dependency is still required

Verified.

>C++11 regular expressions are supported

Supported in the toolchains; not used for anything in Notepad++

>Update scintilla to version 4.33 or newer.

Are you looking for specific functionality from this version of Scintilla?

Only Notepad++ developers are allowed to update Scintilla, so please don't submit PR that you author for this.

>add a single solution file that will automatically build both Notepad++ and Scintilla with a single build command

Sure; how about Boost as well?

---------

Closing this request for now as "vague" / "too multifaceted" / "not a feature-request in the sense of an end-user feature".

If you want to work on the "single solution file" part, I encourage you to do so and to submit your work for consideration in the form of a PR.  But I'm thinking that maybe you don't want to work on it, at least until Notepad++ moves its Scintilla to >= 4.33 (to give you the advantage of the project files you have indicated it includes.
