### ISSUE TITLE
File tabs widths when multi-line is enabled

### ISSUE THREAD

**Issue by f6fvy** [notepad-plus-plus/notepad-plus-plus#8242]
The multi-line tabs options is enabled in my preferences.

But, when there are a lot of open file tabs, a second line of tabs appears (so far, so good), but it takes the whole width of the window. It means that if there are only two or three tabs in this second line, their widths are equal to the half or the third of the width of the Notepad++ window. It's not the case at all for the first line, if there are only a few tabs.

Is it normal, or is it a bug ?

NPP 7.8.6 / Win32

**Comment by sasumner** [comment]
It is a bit of an inconsistency, but I'd call it a known and long-accepted normal and not a bug.

If you want to poll a larger number users on the topic of "is/isn't this a bug", a good place to do it would be the Community support forum ( https://community.notepad-plus-plus.org/ )

Aside: A nice feature of the empty space to the right of tabs on a first and only line is that if you double-click it, a new tab will open up.
