### ISSUE TITLE
Mutli File Open

### ISSUE THREAD

**Issue by wipsjack** [notepad-plus-plus/notepad-plus-plus#8243]
### Description of the Issue
I opening 2000+ file (maybe total 100mb) and notepad++ is stopped working or  waiting. I think its need have a files loading dialog. Its files in SSD disc.

### Steps to Reproduce the Issue
1.  Search your files in your disc
2. Select every file
3. Right click and "Edit with notepad++"

### Expected Behavior
Its a very easyable dialog.

### Actual Behavior
Its stopped working on opening all files

### Debug Information
Notepad++ v7.8.5   (32-bit)
Build time : Mar  4 2020 - 11:04:20
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS Name : Windows 10 Enterprise (64-bit) 
OS Version : 1903
OS Build : 18362.778
Plugins : mimeTools.dll NppConverter.dll NppExport.dll

**Comment by dail8859** [comment]
I don't think it is reasonable to expect 2000+ files to be opened. Honestly if you are needing to open that many text files, then Notepad++ isn't the right tool for the job.
