### ISSUE TITLE
incremental find dialog: add support of regexp and extended search mode

### ISSUE THREAD

**Issue by cmeriaux** [notepad-plus-plus/notepad-plus-plus#8247]
### Description of the Issue

The incremental find dialog only support a normal search. Add the support of extended mode (\r \n \t ....), regexp mode, regexp mode with dot that match new line. 
In another world, add support of every mode that classical find supports.

Also increase the width of the serach field cause it's frequently asked by the community

### Expected Behavior
Add a dropdown menu to select the desired mode.
![image](https://user-images.githubusercontent.com/12024941/81503937-c98fcf80-92e6-11ea-9cd2-78d525a7d3a6.png)

### Actual Behavior
No mode is configurable today
![image](https://user-images.githubusercontent.com/12024941/81503962-e88e6180-92e6-11ea-9b32-70d077697596.png)

### Debug Information

Notepad++ v7.8.5   (32-bit)
Build time : Mar  4 2020 - 11:04:20
Path : C:\notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : ON
OS Name : Windows 10 Home (64-bit) 
OS Version : 1909
OS Build : 18363.778
Plugins : AutoEolFormat.dll CodeAlignmentNpp.dll Explorer.dll ExtSettings.dll FileSwitcher.dll HexEditor.dll LightExplorer.dll LightExplorer2.dll mimeTools.dll NavigateTo.dll NppConverter.dll NppExport.dll NppFTP.dll NppJumpList.dll NppMenuSearch.dll NppPluginTemplate.dll nppplugin_svn.dll NppSaveAsAdmin.dll NppTextFX.dll PythonScript.dll SherloXplorer.dll WindowManager.dll

**Comment by donho** [comment]
If user wants regexpr, they can use Find dialog.
The incremental search is aimed for a minimal interface to provide a quick search. So this feature is pointless to me.

**Comment by sasumner** [comment]
@donho

There is discussion about this proposed feature on the Community site:
https://community.notepad-plus-plus.org/topic/12722/survey-incremental-search-usefulness

It seems to be a split.  Some users like the concept, some agree with you about it being "pointless".

**Comment by donho** [comment]
@sasumner I see. However, the regexpr "doesn't work" on "up" direction (I do remember that we have had a talk about that). By adding regexpr will insert a "bug" or have to manage to disable up direction search. In my viewpoint it's better to keep it as-it: simple and working well.

**Comment by cmeriaux** [comment]
@donho  I'll handle the bug. It shouldn't be hard to fix because the incremental dialog and the find dialog shares the same code

**Comment by sasumner** [comment]
@donho said:

> regexpr "doesn't work" on up direction search (I do remember that we have had a talk about that).

Correct.  We had more than a talk: there is an open PR ( #8128 ) for it. :-)

**Comment by sasumner** [comment]
@cmeriaux If you want to "share the same code" then I guess you have to wait until the PR ( #8128 ) is evaluated and accepted/rejected.

**Comment by donho** [comment]
@sasumner  Sorry I didn't see this PR (or I wanted check it but I forgot to do it).
However, I've just done a PR to fix upward search.
I'll check your PR anyway.

**Comment by donho** [comment]
@cmeriaux From my viewpoint, I think it's important to keep incremental search as simple as it is.

**Comment by cmeriaux** [comment]
@donho  I understand your viewpoint but try to open your mind to other users who want's this update.

**Comment by sasumner** [comment]
@donho said: "I didn't see this PR"
Going forward, how do we assure that you see them?
Assign them to you?

**Comment by donho** [comment]
@sasumner My apology. But it's not necessary for the PR.

**Comment by donho** [comment]
@cmeriaux 
The other users don't present to all users and my viewpoint is for the UX is good for the most of Notepad++ users. Of course I could be wrong. But when a feature requests come over and over again, then I think it's important - it's not the case of this feature.

**Comment by cmeriaux** [comment]
> But when a feature requests come over and over again,

what does it means ? how many users ?
Here is a list a user that may be interested 
- MojaveWastelander (in 2016 did something similar : https://github.com/notepad-plus-plus/notepad-plus-plus/pull/2383 )
- asvc (from community)
- guy038  (from community)
- Alan Kilborn  (from community)
- Alex m  (from community)
- Ekopalypse  (from community)
- me

so what now ? do you ignore all that users, even if they are on the top most active user of the community ? Don't you want to listen to them for once ? do you want to ignore them and see them leave the community like the famous SinghRajenM and may others....

**Comment by Ekopalypse** [comment]
@donho 
> my viewpoint is for the UX is good for the most of Notepad++ users.

I do not believe that this is an argument that can be examined at the moment. 
Neither you nor we have any conclusive data on this, or do you have any?
But if we consider the functionality of current editors, like sublime, atom, VSCode .., we see that this is happening, even exclusively, which means that there is no kind of find dialog in VSCode, for example.

I mostly believe in the KISS strategy (keep it short and simple), but sometimes the benefits might outweigh the simplicity. Just my two cents.

**Comment by donho** [comment]
@cmeriaux 
I told you, if there are other people post the same request on issue tracker, then I will consider it. For the moment I don't see the need.
My role is not make contributors happy but make all Notepad++ users happy, so only the pertinent feature and good (judged by me) PR are included. It doesn't mean that you cannot modify Notepad++ for your need. Fork project and do any modification you want - that's the nature of the open source.

**Comment by Ekopalypse** [comment]
@donho 
Just to get this right, you want to have multiple threads with the same issue/feature request
instead of a thread where several/all express their opinion, either with a post or by using the like-function icons?

**Comment by sasumner** [comment]
>multiple threads with the same issue/feature request

To be clear, maybe you mean "multiple issues with the same feature request"?

To me this would be undesirable.
I tend to close clearly duplicate issues, of course with a "pointer" back to the existing issue, or the issue that does the best job of explaining (which could be through extensive commenting by others).

**Comment by Ekopalypse** [comment]
@sasumner - well, that's what I'm trying to find out.
@donho 's statement suggests that if multiple feature requests are opened with the same feature
then it would increase his attention and motivation to implement it.
This led to the assumption and thus to the question whether this is also true for issues?
