### ISSUE TITLE
"Do you want to reload?" dialog pops up endlessly not allowing any interaction.

### ISSUE THREAD

**Issue by BorisKozo** [notepad-plus-plus/notepad-plus-plus#8249]
### Description of the Issue
"Do you want to reload?" dialog pops up endlessly not allowing any interaction.

### Steps to Reproduce the Issue
1.  Open a file that is written every second by an external 
2.  A dialog will pop up asking if you want to reload the file
3.  Doesn't matter what you click the dialog will popup again

Doesn't matter where you click within the UI, the dialog will popup ignoring what you clicked.
Nothing to do except close the notepad++ process from task manager.

### Expected Behavior
Pressing No will allow this message not to appear for some time, at least let me interact with the UI between messages. Maybe don't ask again checkbox. I don't know.

### Actual Behavior
No more interaction possible

### Debug Information
I think it is easy enough to reproduce.

**Comment by sasumner** [comment]
>I think it is easy enough to reproduce.

Why did you ignore the instructions for submitting an issue?????

Repeat:

```
### Debug Information
<!--- In your Notepad++, click on the "?" menu (found to the right of "Window" in the menu bar) -->
<!--- In the menu that drops down, choose "Debug Info..." -->
<!--- A message box will open detailing specifics about your Notepad++ version, plugins, etc. -->
<!--- CLICK ON THE BLUE LINK with the text "Copy debug info into clipboard" -->
<!--- Do a PASTE HERE -->
```

**Comment by sasumner** [comment]
>Maybe don't ask again checkbox.

Choose the option to `Update silently` in the _Preferences_.

**Comment by BorisKozo** [comment]
I didn't want to close the process yet in the hopes I missed something. I can't click anything at the moment as the UI is stuck.

I will close the process if this info is absolutely needed.

**Comment by BorisKozo** [comment]
Wow, it seems the update process didn't work because some issue with libcurl. I will update now manually.

**Comment by BorisKozo** [comment]
OK looks like this was already fixed and the update process didn't work automatically. My bad. Sorry.
