### ISSUE TITLE
[v.7.8.6 regression] Vertical Edge Settings no longer works with Split Lines (Ctrl-I)

### ISSUE THREAD

**Issue by mhya2020** [notepad-plus-plus/notepad-plus-plus#8262]
### Description of the Issue

v.7.8.6 introduced the ability to have multiple Vertical Edges, but it breaks an existing
feature, i.e. Split Lines (Ctrl-I) no longer works with single Vertical Edge.

### Steps to Reproduce the Issue

1. Settings/Preferences/Editing/Vertical Edge Settings: enter a single number, e.g. 80, into the text box.
2. Leave "Background mode" unchecked.
3. Enter text with more than 80 characters in a single line
4. press Ctrl-I (Split Lines)

### Expected Behavior

The single line is expected to split into multiple lines, where each line is less than 80 characters long.

### Actual Behavior

Nothing happened after pressing Ctrl-I.

### Debug Information

Notepad++ v7.8.6   (32-bit)
Build time : Apr 21 2020 - 15:17:06
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS Name : Windows 10 Home (64-bit) 
OS Version : 1909
OS Build : 18363.778
Plugins : mimeTools.dll NppConverter.dll NppExport.dll 

![image](https://user-images.githubusercontent.com/65295136/81827341-429f5900-956b-11ea-88cb-ef7f483b45f1.png)

**Comment by mhya2020** [comment]
N++ Community discussion thread [here](https://community.notepad-plus-plus.org/topic/19395/v-7-8-6-vertical-edge-settings-no-longer-works-with-split-lines-ctrl-i/7?_=1589381124313)

**Comment by mhya2020** [comment]
Workaround: Settings/Preferences/Editing/Vertical Edge Settings: tick the "Background mode" box.

This will bring back the "Split Lines (Ctril-I)" function. Thereafter, you can uncheck "Background mode" box and Split Lines will continue to work.

**Comment by rickd67** [comment]
I have a similar issue.. But doesn't involve "Split Lines" at all:
I used 80 for "Vertical Edge" in past.
When I encountered "You can define Several Column Markers..." I thought great now I can do 132 also for "comments edge"...
At first it seemed to work perfectly.
Later I noticed that the "Vertical Edge" was in the wrong place: 89! (See attached screen capture).
When I tried to reset to old way (Single Column Marker):
a) found previously mentioned extra space after 80 (removing it=no help)
b) cannot put Vertical Edge in correct position, Unless I use 71!
c) out of curiosity, I tried putting back the 132 edge, but as I types 1, 3, 2... I noticed:
  i) after I had typed "80 1": the "2nd line" appeared in the correct position (between 1st & 2nd char.)
  ii) after I had typed "80 13": the "2nd line" moved to an incorrect position (right in the middle of the 15th char.)
  iii) after I had typed "80 132": the "2nd line" moved to an incorrect position (between 147th & 148th char.)

![Capture](https://user-images.githubusercontent.com/68038770/86988284-e4a38200-c165-11ea-9f3b-2641c66e9906.PNG)

I know, I know, this is a bit off-topic. But this multi-line feature is causing other issues...
As a programmer myself, I always like as much info as possible when talking bugs... Nough said!

**Comment by rd4gh** [comment]
Hi,
I just want to add my support to have the prior function of Ctrl-I in 7.8.5 restored as an option -- Split lines at the Vertical Edge, no matter what the width of the window is.  I use Notepad++ with wide windows a lot and often split only certain lines at 80 characters.

Thanks,
Ross

**Comment by sasumner** [comment]
Additional Community link: https://community.notepad-plus-plus.org/topic/20581/restore-right-margin-word-wrap-as-in-7-8-5
