### ISSUE TITLE
Notepad++ crashes when using a User Defined Language in certain cases

### ISSUE THREAD

**Issue by jabal1** [notepad-plus-plus/notepad-plus-plus#8265]
### Description of the Issue
Notepad++ is crashing when using a User Defined Language

When applied manually on some files with a different (or not existing) extension than those defined in the UDL.

### Steps to Reproduce the Issue

1. Import the User Defined Language
2. Open the sample file provided (named sotpbi.y)
3. Apply manually the User Defined Language to this file

### Expected Behavior

The files should show proper syntax highlighting according to the User Defined Language.

### Actual Behavior

Notepad++ crashes !

### Debug Information

Notepad++ v7.8.6   (64-bit)
Build time : Apr 21 2020 - 15:23:03
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS Name : Windows 10 Enterprise (64-bit) 
OS Version : 1909
OS Build : 18363.778
Plugins : DSpellCheck.dll mimeTools.dll NppConverter.dll NppExec.dll NppExport.dll NppHorizontalRuler.dll 

If you rename the sample file from sotpbi.y to sotpbi.p it works !
Summary :
sotpbi.p (higlighting works)
sotpbi.y (applying UDL manually makes notepad crash)
sotpbi   (applying UDL manually makes notepad crash)

Depending on the extension the same file will work or crash.
In fact applying manually the UDL to a file with a non-defined extension causes often notepad to crash whereas applying automatically the UDL to a file with a predefined extension (i.e defined in the UDL) will always work !

As attachment the UDL export file and the sample file.

[notepad++_crash_case.zip](https://github.com/notepad-plus-plus/notepad-plus-plus/files/4627285/notepad%2B%2B_crash_case.zip)

**Comment by chcg** [comment]
@jabal1 Can't reproduce you issue with the provided data with:

Notepad++ v7.8.6   (64-bit)
Build time : Apr 21 2020 - 15:23:03
Path : C:\Users\...\npp.7.8.6.bin.x64\notepad++.exe
Admin mode : OFF
Local Conf mode : ON
OS Name : Windows 10 Home (64-bit) 
OS Version : 1909
OS Build : 18363.836
Plugins : mimeTools.dll NppConverter.dll NppExport.dll PythonScript.dll 

Maybe a plugin is causing trouble. See https://npp-user-manual.org/docs/command-prompt/ and there option:
-noPlugin
to start N++ without plugins to check if a plugin might be the problem.

**Comment by jabal1** [comment]
Tried to launch notepad++ -noPlugin and indeed it dit NOT crash.
I suspect either NppExec.dll or NppHorizontalRuler.dll.
But what to do now ? Even If I identify the culprit it is not sure the pluggin would be corrected...

**Comment by jabal1** [comment]
I have meticulously checked by systematically removing all plugins and tested the syntax highlightning, and by removing DSpellCheck.dll it worked again without crashing.
I had DSpellCheck 1.4.6 installed and I updated it to DSpellCheck 1.4.15 and now it seems that notepad++ is not crashing anymore.
Updating DSpellCheck solved the problem !

Thanks for the support.

Regards
