### ISSUE TITLE
Files Opened On a Non Existing Location Vanishes Without Confirmation

### ISSUE THREAD

**Issue by PRinceBhai** [notepad-plus-plus/notepad-plus-plus#8266]
So i found this quite irritating that if some files were to left open on a Location which might not be available the next time we run NP++ then those files would just disappear without any notification and Confirmation.

This happens when i leave some files open on my removable storage and then after removing the drive the files would not be there when i relaunch NP++.

**Comment by sasumner** [comment]
Any particular reason you deleted out the required issue template as you were composing?

**Comment by sasumner** [comment]
Seems to share some commonality of result with #7931
