### ISSUE TITLE
Feature request: fast scroll like in browser with mouse middle-click-and-drag

### ISSUE THREAD

**Issue by da411d** [notepad-plus-plus/notepad-plus-plus#8275]
fast scroll like in browser with mouse middle-click-and-drag:

![bandicam 2020-05-17 00-46-54-939](https://user-images.githubusercontent.com/12462454/82130889-248a6080-97d8-11ea-858e-cd1955942b88.gif)

**Comment by sasumner** [comment]
Scrolling is already at maximum speed; a lot of factors contribute to what this max. speed is.
So, request denied--or--already fulfilled.

**Comment by da411d** [comment]
What means "Scrolling is already at maximum speed"?

**Comment by julealgon** [comment]
The justification for closing this makes zero sense to me. There is more to the feature than just scrolling speed.

I'd like to vote to reopen this to support middle-mouse-button-click-and-drag scrolling in general.
