### ISSUE TITLE
Suggestion : Add a "None" language

### ISSUE THREAD

**Issue by f6fvy** [notepad-plus-plus/notepad-plus-plus#8277]
Add a  "None" language as the first item in the Language menu (with a separator) that mimics "Normal Text".

```
    Language
==============
  None
--------------
  A         >
  B         >
  etc.
  YAML
---------------
  User defined
```

This will be much easier to find when the user wants to disable a language that is in action without his/her consent, because the edited file has an obscure file extension ;-)

**Comment by ArkadiuszMichalski** [comment]
Same problem as https://github.com/notepad-plus-plus/notepad-plus-plus/issues/7746.
