### ISSUE TITLE
Deleting bookmarked lines very slow

### ISSUE THREAD

**Issue by lecramm** [notepad-plus-plus/notepad-plus-plus#8279]
### Description of the Issue
Deleting bookmarked lines very slow

### Steps to Reproduce the Issue
Create a document with a +/- 300000 lines
containing +/- 200000 lines having the same word

step 1) Find->Mark->Select bookmark lines

step 2) Search->Bookmark->Removed booked marked lines

### Expected Behavior
Finding and bookmarking is pretty fast.
Deleting booked marked lines should be completed within reasonable time.
But removing bookmarked lines is very, very slow

### Actual Behavior
Deleting booked marked lines seems to be never be completed, notepad++ becomes unresponsive, needs to be killed after 10min.

### Debug Information
Notepad++ v7.8.6   (64-bit)
Build time : Apr 21 2020 - 15:23:03
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : ON
Local Conf mode : OFF
OS Name : Windows 10 Pro (64-bit) 
OS Version : 1909
OS Build : 18363.836
Plugins : DSpellCheck.dll HexEditor.dll mimeTools.dll MyNppPlugin1.dll NppConverter.dll NppExport.dll NPPJSONViewer.dll PythonScript.dll XMLTools.dll

**Comment by sasumner** [comment]
Possibly related additional info:

- https://github.com/notepad-plus-plus/notepad-plus-plus/pull/4967
- https://community.notepad-plus-plus.org/topic/15159/bookmark-multiple-lines
- https://community.notepad-plus-plus.org/topic/18900/persistent-highlight-of-characters-e-g-no-break-space

**Comment by sasumner** [comment]
@lecramm 

What do you think reasonable time is for such an operation?
I created a file matching the criterion you gave and bookmarked lines containing `NotepadPP`.
I then started a delete-bookmarked-lines operation.
It finished in 4 minutes or so -- I don't find that unreasonable.

I've attached the data file I used.
I used Notepad++ 7.9.1 64-bits.

[data8279.zip](https://github.com/notepad-plus-plus/notepad-plus-plus/files/5682455/data8279.zip)

**Comment by lecramm** [comment]
Hi,

 

Compare it with this:

-start a command prompt

-type “find /V /I "NotepadPP" data8279.txt>test.txt”

 

This completes in less than 3 seconds.

 

I don’t know how NPP works under water, but I think It could definitely be faster.

 

If a background task processes the delete command in a more straight forward, direct way into a temp document (or file), after completion paste it into the active one.

 

 

regards

**Comment by felix-22** [comment]
See here: https://github.com/notepad-plus-plus/notepad-plus-plus/issues/10301#issuecomment-895237160
- I couldn' t reproduce the issue as it took 35s on my PC
- still 35s is too slow compared to other text editors/tools

**Comment by felix-22** [comment]
@donho  I tested both 7.x & 8.x on Win7 64 & Win10 64 with a clean N++ install, and can't reproduce the issue, it takes 22 s, can we close this?

**Comment by rruizGit** [comment]
Exact same issue with v8.1.3 (32-bit). Document is 4MB in size. Includes about 28K lines. If I bookmark a good number of lines and tell it to delete them Notepad++ will hang. I had to kill it after about 20 minutes.

**Comment by felix-22** [comment]
Do you use any additional plugins? Also you guys should provide a file to reproduce, as it might hang only when lines contain particular characters.

**Comment by lecramm** [comment]
> @rruizGit @lecramm In v8.1.4 one performance issue has been fixed, could you try this version? https://notepad-plus-plus.org/news/v814-released/

tested with v8.1.9.3 and that performs better
(sorry for the late response)

**Comment by afg-thierry-duval** [comment]
Hi Team

i am having a large file with 7 203 278 lines
i use the mark to mark all line I want to remove --> about 3022033 lines containing a word
marks works fine and it marked 

![2023-01-11 09 39 20](https://user-images.githubusercontent.com/68956675/211758484-a564b984-bafe-4977-a870-82310134eefc.png)

then i used remove bookmarked lines and notepad failed removing the lines ?????
notepad++ processed the command but stopped after a certain time
![image](https://user-images.githubusercontent.com/68956675/211759946-6927e132-01dd-4650-8838-860aa45f5e6b.png)

we can see that it deleted some lines but stopped in the middle of its process and removed the bookmark??


does anyone have a clue?

the file containing some confidential data i cannot share :(

**Comment by low-neotran** [comment]
This issue is still a thing as v.8.5.1

**Comment by freezer2022** [comment]
> low-neotran: This issue is still a thing as v.8.5.1

It completes for me, however it's slow like a shiit (v8.8.1).

> sasumner (https://github.com/notepad-plus-plus/notepad-plus-plus/issues/8279#issuecomment-743696790) : It finished in 4 minutes or so -- I don't find that unreasonable.

A good joke. Just comparing it to all the other common operations like: Find, Replace, Sort, Remove duplicate lines, of which each takes just at most several secs, proves the opposite: deleting / copying bookmarked lines is super slow.

**Comment by JDBC-0** [comment]
The main problem is not the duration, but the "freezing" nature: the window turns white after a while and even after 5 minutes you have no glue if it's still progressing or not. => a prograss bar would come in handy.

**Comment by freezer2022** [comment]
> JDBC-0: The main problem is not the duration

Like I already said - a good joke. The very long time it takes to complete is as much big problem.

**Comment by Piterskuy** [comment]
8.7.4 same problem
Is that possible to improve the usability when working with bookmarked lines on relative large files, maybe temporarily shut down the UI update?
7 Mln lines, less than 1k hits, 10 minutes just hanging while deleting non-marked lines
