### ISSUE TITLE
Feature Request : Add a "Copy Matches" in the Find Result window

### ISSUE THREAD

**Issue by f6fvy** [notepad-plus-plus/notepad-plus-plus#8288]
Although there are convoluted ways to do it, having a "Copy Matches" (only the matches, not the matching lines) in the Find Result window would be very useful in some occasions.

**Comment by sasumner** [comment]
@f6fvy You probably are talking about matches made with a regular-expression search, correct?  (Other types of searches would not be interesting as there would be simply **_M_** (M=number of matches) copies of the same piece of data.)

Probably better would be a mechanism for copying marked matches, see #6095

**Comment by f6fvy** [comment]
I didn't know #6095 and it certainly is even better ;-)

**Comment by sasumner** [comment]
@f6fvy I thought of some ways 6095 is NOT better:  If you wanted to copy the matches from multiple files/searches at once.

**Comment by alankilborn** [comment]
From @f6fvy 's comment above, seems they are satisfied with the suggestions.
Recommend CLOSURE.
