### ISSUE TITLE
.bat files saving too slow Windows 10

### ISSUE THREAD

**Issue by Planutim** [notepad-plus-plus/notepad-plus-plus#8289]
### Description of the Issue

File saves too slow when its extension is .bat. Bug Happened on windows 10 distro. 
### Steps to Reproduce the Issue

1.  Save any text as somename.bat file
2. Open it again
3. Try to change it and save it. You get some delay and seemingly some CPU usage

### Expected Behavior

To save a .bat file like any other file
### Actual Behavior

Get some huge delays, 1 to 10 seconds on saving file
### Debug Information

Notepad++ v7.8.6   (32-bit)
Build time : Apr 21 2020 - 15:17:06
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS Name : Windows 10 Enterprise (64-bit) 
OS Version : 1909
OS Build : 18363.592
Plugins : mimeTools.dll NppConverter.dll NppExport.dll

**Comment by sasumner** [comment]
Same behavior with `.cmd` as extension?

**Comment by Planutim** [comment]
> Same behavior with `.cmd` as extension?

Do you have the same bug? Yes .cmd extension also struggles to save quickly

**Comment by xylographe** [comment]
Just guessing: could be the _real-time_ anti-virus protection software.

**Comment by Planutim** [comment]
> Just guessing: could be the _real-time_ anti-virus protection software.

Thank you! It has nothing to do with npp, other text editors  behave same way. Turned off real-time protection, light instant file save!
