### ISSUE TITLE
Feature Request: Choose whether or not Notepad++ should add spaces when commenting.

### ISSUE THREAD

**Issue by curiosport** [notepad-plus-plus/notepad-plus-plus#8290]
I don't know if there is a way to configure this or not, but I already went to some forums and in one of them I was recommended to come here...

No matter which language I work in, whenever I comment on Notepad++ it adds a space:
```
# instructionsRuby
; instructionsFASM
// instructionsC
```

I'd love to be able to comment without the space at the beginning, not that I mind Notepad++ adding spaces but I already have several third-party codes with commented lines without space and I want to follow the same style.

In **langs.xml** I found this:
`<Language name="ruby" ext="rb rbw" commentLine="#">`

Which means I don't have any options for removing the space.

**Comment by ArkadiuszMichalski** [comment]
@curiosport Can you add more infos, like from `? >> Debug Infos`, I don't see that Notepad++ automatically add any space before comments start char.

**Comment by curiosport** [comment]
Just in case I didn't say it was a bug, but if you interpreted it that way it means that I didn't explain myself well so I'll explain it another way.

This is a normal text:

```
any text
any text
```

After pressing Ctrl+Q, I have the following:

```
# any text
# any text
```

But what I really want is this:

```
#any text
#any text
```

Obviously, it must be configurable, I'm not saying it's mandatory, just one more option.

**Comment by ArkadiuszMichalski** [comment]
Now understend, it happend when we use command like `Toggle Single Line Comment`, ` Single Line Comment` and `Block comment`.
