### ISSUE TITLE
Windows System Directory is the Default Directory even during editing

### ISSUE THREAD

**Issue by adel314** [notepad-plus-plus/notepad-plus-plus#8291]
Okay, after nearly 10 years I have to have a gripe.  

Why on earth in the name of all things sane, does Notepad revert to the Windows system directory for saving files.  When you are editing a file and want to save it as another name, so you click Save As and off you go to the Windows Directory - and there I have to spend another few minutes navigating back to the source directory so I can save and update the file.   

Is there any good reason for this odd and illogical behaviour?

**Comment by sasumner** [comment]
Perhaps?:

![image](https://user-images.githubusercontent.com/30118311/82440462-54e92d80-9a6a-11ea-8963-910e52c75187.png)

**Comment by adel314** [comment]
oops - thankyou.  I had no idea - although this should be, of course, the default behaviour.

**Comment by sasumner** [comment]
>although this should be, of course, the default behaviour.

Well, my testing shows that it **_IS_** the default behavior.

**Comment by adel314** [comment]
Now that is interesting - because when I went to my settings that is the setting it was on - but as I said the behaviour was as if it was on the other setting.   I remember being a bit surprised and clicked on the other setting and then back.  After closing the option worked.

**Comment by sasumner** [comment]
Interesting things abound. :-)
