### ISSUE TITLE
Opening files simultaneously displays side by side windows

### ISSUE THREAD

**Issue by Harvey13** [notepad-plus-plus/notepad-plus-plus#8292]
### Description of the Issue

I usually open multiple files that appear in the usual tabs.
With this version they are displayed side by side and I cannot open them unless I move them in a new window one by one
Correction : **In fact the window is full with tabs**

### Steps to Reproduce the Issue

1. Select multiple files
2. Open them with Notepad++
3. They are all reduced in a side by side view

### Expected Behavior

Like before, I prefer they open normally

### Debug Information

Notepad++ v7.8.6   (32-bit)
Build time : Apr 21 2020 - 15:17:06
Path : G:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS Name : Windows 10 Enterprise (64-bit) 
OS Version : 1803
OS Build : 17134.1425
Plugins : mimeTools.dll NppConverter.dll NppExport.dll NppTextFX.dll 

![pb notepad](https://user-images.githubusercontent.com/2869765/82420633-4ad22980-9a80-11ea-87e0-9895707ee1b1.JPG)

**Comment by Montclair** [comment]
Are you sure you have Preferences -> Tab Bar -> Multi-line unchecked?

**Comment by Harvey13** [comment]
You are right : Preferences -> Tab Bar -> Multi-line  was checked.
I checked by mistake when I wanted to test the multi-column marker feature, and forgot to unchecked it .

Thanks for your help
