### ISSUE TITLE
Session snapshot/periodic backup doesnt seem to be working

### ISSUE THREAD

**Issue by klepp0906** [notepad-plus-plus/notepad-plus-plus#8298]
### Description of the Issue
so im a bit shakey on how this is supposed to function as ive always had it disabled, however upon enabling it, it seems absolutely nothing is written to the folder designated by default.

### Steps to Reproduce the Issue

1.   Download a portable version of notepad++ and ensure default settings and directory are set under backup.
2.  Do things for substantially longer than the 7 second timer which is set.
3. Open and close a few instances of notepad++ to be certain.
4. inspect the notepad++\backup folder and note no backups are present.

### Expected Behavior
I assumed it would be backing up "something" (not sure what exactly it backs up) to the folder designated in the preferences.

### Actual Behavior
I have an empty backup folder.

### Debug Information
Notepad++ v7.8.6   (32-bit)
Build time : Apr 21 2020 - 15:17:06
Path : C:\Users\klepp\Dropbox\Downloads\Windows\Development\Text Editors\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : ON
OS Name : Windows 10 Enterprise (64-bit) 
OS Version : 2004
OS Build : 19041.264
Plugins : mimeTools.dll NppConverter.dll NppExport.dll

**Comment by sasumner** [comment]
> im a bit shakey on how this is supposed to function

Docs are here:
https://npp-user-manual.org/docs/preferences/#backup
Maybe it doesn't make it ultra-clear.
Docs can always be better.

Regardless, my tests with 7.8.6 show that it is working for me.

I'm certainly willing to discuss further if you can be more specific than "do things".
Start by creating a new tab (with an auto-name such as "new 2").
Modify new2 such that its tab turns red.
Have an open Explorer window on the backup folder and see if a file such as `new 2@2020-05-20_131658` pops in after some seconds.
I'm doing this myself right now as I type this stuff.

**Comment by klepp0906** [comment]
I think I see where the misunderstanding arose.

Seems to be user error.  I googled surrounding its functionality and the results returned were unsatisfactory.   The docs however seem to make it much more clear.

I shouldnt expect anything to be there if I am saving my changes beforehand.  it seems to be a protection against unsaved changes.   

Would explain why im not seeing anything in that folder.   

Gonna go give it a test run and should all be well, i'll post back/close the issue.

Thank you

**Comment by klepp0906** [comment]
works spectacularly.  apologies for wasting your time!

**Comment by sasumner** [comment]
Good that it is cleared up!

> I shouldnt expect anything to be there if I am saving my changes beforehand. it seems to be a protection against unsaved changes.

Yes, the lower part of the Preferences window is called "Backup on Save", so that should have been a hint! :-)
