### ISSUE TITLE
Find/replace dialog's transparency slider behaves as opacity

### ISSUE THREAD

**Issue by mattbaker-digital** [notepad-plus-plus/notepad-plus-plus#8299]
### Description of the Issue
Find and replace transparency slider is actually opacity. Moving slider to the right **decreases** transparency (therefore increasing opacity) so should be renamed opacity to match behaviour.

### Steps to Reproduce the Issue
1. Open find dialog.
2. Set transparency to always.
3. Move slider to fully left and gradually move to the right.

### Expected Behavior
Transparency to increase with slider moving to the right.

### Actual Behavior
Transparency decreases moving slider to the right.
https://i.imgur.com/mmJFnfh.gifv

**Comment by sasumner** [comment]
Right or wrong, this feature has too much history behind it to be changed now.

If you'd like to change it for yourself, you can edit `english_customizable.xml` and look for `Transparency` and change the correct occurrence(s) to whatever text you'd like.  After that is accomplished, go to _Preferences_ > _General_ > _Localization_ and set that to `English (customizable)`.
