### ISSUE TITLE
unable to save a macro 

### ISSUE THREAD

**Issue by cmeriaux** [notepad-plus-plus/notepad-plus-plus#830]
Unable to save a macro on the shortcuts.xml file.

Regression due to 4fc06e2bc196da8f1d2ee056e422d80d3744c2c2

Procedure : 
* open NPP
* create a macro
* save macro as temp_macro
* close NPP
* open shortcuts.xml, temp_macro doesn't exist !

**Comment by gforman44** [comment]
I look forward to this fix being released.  Thank you for fixing this.
