### ISSUE TITLE
[feature request] date/time stamp

### ISSUE THREAD

**Issue by PaltryProgrammer** [notepad-plus-plus/notepad-plus-plus#8302]
Please provide the ability for the current date and/or time to be inserted at the cursor position Thank You Kindly Cheerios

**Comment by sasumner** [comment]
Please see [HERE](https://github.com/notepad-plus-plus/notepad-plus-plus/issues/8184#issuecomment-620900126)

**Comment by MMitsialis** [comment]
This is a welcome addition to NPP. 

The addition of these addition menu action items would make this new feature even more useful:
- Add Date (Short)
- Add Date (Long)
- Add Time ( 12 Hour)
- Add Time (24 Hour)
