### ISSUE TITLE
Include current ANSI code page into debug information

### ISSUE THREAD

**Issue by Uhf7** [notepad-plus-plus/notepad-plus-plus#8303]
I'm currently trying to solve some encoding issues, and for this I'm reading a lot of comments posted here about it. What strikes me first is the missing debug information about the current ANSI code page, because without this information, any effects regarding the ANSI encoding are not interpretable without guessing. Take #2812 as an example. I assume, the default ANSI code page was 1251 (Cyrillic) here, but in the debug information provided, this detail is missing. So there should be some lines included into `DebugInfoDlg::run_dlgProc`, like this:

`			{`
`				TCHAR szACP[32];`
`				generic_sprintf(szACP, TEXT("%u"), ::GetACP());`
`				_debugInfoStr += TEXT("Current ANSI codepage : ");`
` 				_debugInfoStr += szACP;`
`				_debugInfoStr += TEXT("\r\n");`
`			}`

Does anyone else find the default ANSI code page information useful?

**Comment by sasumner** [comment]
I suppose it could be useful.
But wouldn't it be document/tab specific?
Which is not a problem, except current debug info doesn't report anything about documents/tabs (how many are open, what are their "names", _what is their encoding_, ...) -- maybe it should.

**Comment by Uhf7** [comment]
No, this is not document specific. It's a system information, which says, how the ANSI encoding should be handled. If the encoding of a document is set to ANSI, this means to use the default ANSI code page of the system for this document. It's an information about a system setting. If I read something like "I used ANSI encoding", then this actually means "I used the default ANSI code page of my system". So it would be interesting to know, which it was.

To gather information about all documents seems too much to me for the following reasons:
- Unpredictable amount of data.
- Users may not want to deliver detailed information about all their opened documents.
- The information about what has been done with what files, and what the status line said, this is all part of the reports anyway. But I never read about the current system setting regarding the default ANSI code page.

**Comment by sasumner** [comment]
>If I read something like "I used ANSI encoding", then this actually means "I used the default ANSI code page of my system". So it would be interesting to know, which it was.

Ah, okay, now I understand.
It seems like it would be fine to include this in the debug info.

>( a bunch of stuff) is all part of the reports anyway

Oftentimes users don't report needed info or don't know how to.
I was just thinking of more ways to automate.
But yes, it does feel like a lot of tab-specific info could be considered "too much".

**Comment by sasumner** [comment]
So a good example where this suggestion may help is in "issue part 2" of #3222 ?

**Comment by Uhf7** [comment]
Exactly. The name of the Windows setting for it is something like "Language for non-Unicode programs". It is usually not changed after the installation of Windows. An I would not dare to change it on my system. 

If I read issue #2812 about an edit buffer set to ANSI and then written "тест" into it, I know, it is certainly not Windows-1252. And now look under "Character Sets", "Cyrillic". There are multiple different ways to encode "тест" using a code page instead of UTF-8. Which code page has been used  here as default ANSI code page? The one delivered by the `GetACP()` system call.

**Comment by Uhf7** [comment]
Ok, I dared to change the setting on my system now (after trying it on another). Cyrillic seems not to be the best example, the different single byte character sets (SBCS) used in Central Europa are much harder to identify at first glance. Here, for instance, the standard 1252

![SBCS-1252](https://user-images.githubusercontent.com/40629737/82733693-db756780-9d15-11ea-8f84-f5478e2b3dd9.png)

against 1250 used in the Latin-Serbian locale

![SBCS-1250](https://user-images.githubusercontent.com/40629737/82733724-2d1df200-9d16-11ea-9dc6-aa3360cd4bfc.png)

Can't tell which is which, without an information about the current ANSI codepage.

[SBCS.zip](https://github.com/notepad-plus-plus/notepad-plus-plus/files/4671993/SBCS.zip)

**Comment by sasumner** [comment]
So just do PR to add it to the _Debug Info_ ?
