### ISSUE TITLE
Strange issue with ∈ symbol because of bracket highlighting

### ISSUE THREAD

**Issue by ValZapod** [notepad-plus-plus/notepad-plus-plus#8305]
### Description of the Issue

U+2208 is very buggy, somehow.
### Steps to Reproduce the Issue

1. Copy paste the follows in notepad x′2(t) + y′2(t).  x(t), y(t) ∈ C1[t1, t2], то |¯v(t)| ∈ C[t1, t2] ⇒
|¯v(t)| ∈ R[t1, t2].
2. Observe the third ∈ (and only third) is corrupted
3. You can just copy paste one ∈. It will also be corrupted.
4. You can also delete symbols starting in first string; this will make the symbol corrupted and not again.
### Expected Behavior

Well, it should render correctly. It is not font problem obviously. P.S. It is((
### Debug Information

Notepad++ v7.8.6   (64-bit)
Build time : Apr 21 2020 - 15:23:03
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS Name : Windows 10 Enterprise (64-bit) 
OS Version : 1909
OS Build : 18363.836
Plugins : mimeTools.dll NppConverter.dll NppExport.dll 

IMHO this happens because of bracket highlighting, see gif!
![notepadcorruption](https://user-images.githubusercontent.com/31514790/82732777-006ada00-9d18-11ea-9538-699374bc1958.gif)

**Comment by Uhf7** [comment]
Seems to be a font-dependent rendering issue. 

The (_Courier New?_) font used here has no Unicode 2208 "Element Of" character in it. So this character is rendered by rather complicated font substitution mechanisms. And this seems to fail when highlighting brackets. 

What works for me here is to use a font which has all characters needed.  Whether a font has all characters needed, can be checked with the Windows Character Map program _charmap.exe_.

My favorite font is _DejaVu Sans Mono_, which can be downloaded from the Internet. With this font, the example above displays correctly. With _Courier New_, I see the same problem.

**Comment by ValZapod** [comment]
> And this seems to fail when highlighting brackets

Not necessary! 

> You can just copy paste one ∈.

 It will also be corrupted. But yes, with DejaVu Sans Mono it is normal (and yes, it is Courier New, you guessed it). Looks like font substitution here fails(( Can you fix it?

**Comment by ValZapod** [comment]
Well this is just continuation of https://github.com/notepad-plus-plus/notepad-plus-plus/issues/3747 and many others(( I think no point in keeping it open((

**Comment by Uhf7** [comment]
> Can you fix it?

No. Not in short term. Seems to be in Scintilla itself.

And it was already answered in #3747 in the same way. Would be cool if we had a "merge issue" feature on this site.

One point in #3747 seems incorrect for my system: The U+23B7 character is not in my _DejaVu Sans Mono_. There is U+23AE, followed by U+23CE.

**Comment by ValZapod** [comment]
This was fixed in Notepad v8. INCLUDING bracket highlighting! bravo everybody!
