### ISSUE TITLE
Is notepad++ website down ?

### ISSUE THREAD

**Issue by n1k3sh** [notepad-plus-plus/notepad-plus-plus#8307]
I am neither able to access the notepad++ site https://notepad-plus-plus.org/ . Is there any problem ? Neither i am able to update or access any other plugins ? This is happening since last month . Can anyone help understanding what is going on ?

**Comment by sasumner** [comment]
>Is there any problem ?

There doesn't currently seem to be.
Probably best to work thru any problems YOU may be having by posting on one of the support sites, for example, [HERE](https://community.notepad-plus-plus.org/) , rather than creating an "issue".
