### ISSUE TITLE
[Feature Request] Show (number of) selected characters in Hex value also

### ISSUE THREAD

**Issue by rubal19** [notepad-plus-plus/notepad-plus-plus#8308]
### Description of the Issue
The status bar of the notepad++ shows the following information particularly for selected text: -

- Selected number of characters (in decimal), e.g. for a text of "112233445566", it shows "Sel: 12 | 1".

Request is to also include the value of selected characters in Hexadecimal, when counted as a byte stream.

e.g. For text of "112233445566", it can show "Sel: 12 | 1 | **6**" (where **6** is number of selected characters in hex if the selected string is byte array). Following are some examples, how status bar area for information should look.

For "9988552266" - "Sel: 10 | 1 | 5" (10 - decimal, 5 hexadecimal byte stream).
For "998855226" - "Sel: 9 | 1" (10 - decimal, /no - hex byte steam because 9 characters/).

This will be very beneficial for developers who work with hexadecimal data.

**Comment by sasumner** [comment]
Not generally useful.
Suggest scripting plugin to provide needed data.
