### ISSUE TITLE
Custom shortcut for "Open Containing Folder in Explorer" doesn't work as expected

### ISSUE THREAD

**Issue by voidray** [notepad-plus-plus/notepad-plus-plus#8309]
### Description of the Issue
Right-clicking on a tab and clicking "Open Containing Folder in Explorer" does what it says. When a shortcut is assigned to this action however, not always the correct folder is opened.

### Steps to Reproduce the Issue
1. Assign a shortcut using Settings -> Shortcut Mapper (e.g. CTRL+SHIFT+O) to the action "Open Containing Folder in Explorer" 
2. Open a file
3. Press the shortcut keys

### Expected Behavior
Containing folder is opened.

### Actual Behavior
Sometimes the folder one level above is opened. Most of the time a normal explorer window is opened with the top level showing the drives. I couldn't reproduce a specific behavior. I tested  file without spaces and special characters (c:\temp\test.txt) and it opened a normal explorer window (like pressing WINDOWS+E).

### Debug Info
Notepad++ v7.8.6   (32-bit)
Build time : Apr 21 2020 - 15:17:06
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS Name : Windows 10 Enterprise (64-bit) 
OS Version : 2004 (also tested on 1909, 18363.418)
OS Build : 19041.208
Plugins : JSMinNPP.dll mimeTools.dll NppConverter.dll NppExport.dll XMLTools.dll

**Comment by sasumner** [comment]
#7895 might be relevant.

**Comment by voidray** [comment]
The Shortcut Mapper entry for "Open Containing Folder in Explorer" seems to mean something different than what it says. It opens the parent folder of the path that is currently selected. I couldn't find that action anywhere in the menu. It should be name something like "Open Containt Folder of Selection". The "Open Containing Folder in Explorer" entry should to the exact same thing that the context menu does (or File > Containing Folder > Explorer).

**Comment by sasumner** [comment]
@voidray said:

>...Shortcut Mapper entry for "Open Containing Folder in Explorer" ... opens the parent folder of the path that is currently selected

I cannot duplicate this experience.
For me it opens the folder of the whatever file is in the selection.
Is there any more information you can provide to aid me in replicating?

**Comment by voidray** [comment]
I created a short video that demonstrates the behavior. It's a new Windows 10 installation with a fresh notepad++ installation. The only thing done before the video was to assign the F10 shortcut to "Open Containing Folder in Explorer". I also recorded the keys I pressed.

Things to note: It matters where the cursor is. If it is on an empty line is different from when the cursor at the end of a line.

[npp_shortcuttest.zip](https://github.com/notepad-plus-plus/notepad-plus-plus/files/4678033/npp_shortcuttest.zip)

**Comment by Uhf7** [comment]
I see two shortcuts in the Shortcut mapper: 

1.  "Explorer", which is of category "File"
2. "Open Containing Folder in Explorer", which is of category "Edit"

The first one is the command, which is executed if you right-click at a file tab. And perhaps that one you are searching for. Despite the context menu of the file tab says "Open containing folder in Explorer" here, the shortcut command for this one would be "Explorer".

The second one is the command, which uses the words around the cursor to determine where to go. This one It is in the _Edit-->On Selection_ menu too.

**Comment by voidray** [comment]
Thanks a lot, that clarifies it. I think renaming those two entries (at least the one named "Explorer") would be helpful, because I wouldn't have looked for "Explorer".

**Comment by sasumner** [comment]
Thanks to @Uhf7 for the clarification, but @voidray wasn't basically the same info in #7895 clear enough?  Or maybe you didn't look at it from my earlier link?
Specifically [HERE](https://github.com/notepad-plus-plus/notepad-plus-plus/issues/7895#issuecomment-590018966).

>renaming those two entries

That can't be done.  The reasoning is explained also in the link.

> I wouldn't have looked for "Explorer".

Think in terms of looking for the "complete command" instead of just the "ending part" (only the ending part appears in the _Shortcut Mapper_).  Another way to resolve it is to look at where a command is in the _Shortcut Mapper_ list; it will parallel where it is in the menus.

**Comment by Uhf7** [comment]
@sasumner,

you are right, I didn't read the other issue carefully enough. Your comment "#7895 might be relevant" didn't indicate to me, that #7895 contains the solution already. Sorry for that, I'll try to improve.

Duplicates seem to be a major problem here, it is very hard to read and memorize all the 8000 open and closed issues before posting something.

**Comment by sasumner** [comment]
@Uhf7 No worries, I wasn't expecting you to read the linked-to item as you didn't create this issue.

However, I fully did expect @voidray to have read it (as part of trying to find a solution or workaround to the problem).

>very hard to read and memorize all the 8000 open and closed issues before posting something.

Yes, indeed, but the search function is fairly good.  Nobody can remember them all.
But...this only really matters when you are creating a new issue (really want to keep duplicates away there).
Unknowingly duplicating something that was said in a comment somewhere else:  "Meh!" (no big deal).

**Comment by voidray** [comment]
@sasumner yes, sorry, I somehow missed your comment in that issue. I wouldn't have opened a ticket if it would be obvious what "Explorer" does. Yes, it is the same name as in the menu, but it's a submenu, the menu above "Open Containing Folder", which should some be part of the shortcut name (something like "Open Containing Folder > Explorer"). It sounds strange to me that this isn't possible to change, but anyway, thanks a lot for clearing it up.
