### ISSUE TITLE
Regular expressions case sensitivity

### ISSUE THREAD

**Issue by f6fvy** [notepad-plus-plus/notepad-plus-plus#8310]
Why are the regular expressions used in the Search dialog case-insensitive, while regex are case-sensitive by default ? The "Match case" checkbox should be disabled when using regex, and the regex adapted by the user only for case-dependency if needed.

If I enter [A-Z]+, I clearly want to match upper-cased strings. If I wanted case-independency, I would enter [a-zA-Z]+.

If, for some reason, this must be kept insensitive for history/compatibility, please offer an option in the preference settings to force case-sensitivity.

**Comment by sasumner** [comment]
@F6fvy said:

>Why are the regular expressions used in the Search dialog case-insensitive, while regex are case-sensitive by default ?

It's probably just a parallel from how normal mode searches work in conjunction with the _Match case_ checkbox.  Normal mode came first, and had the checkbox, then with Regular expression mode was added (in v.6.0) it was adapted to what was already there.

>The "Match case" checkbox should be disabled when using regex, and the regex adapted by the user only for case-dependency if needed.

Well, that would be *one* way of doing it, but as I said it was an adaptation to "what was already in place" when Regex mode was added.  It works.

>If I wanted case-independency, I would enter [a-zA-Z]+.

Or, more conveniently, you would just make sure that _Match case_ is unticked when you enter `[A-Z]+`. :-)

But truly, the capability to totally ignore the _Match case_ box already exists for Regular expression searches.  Just lead off your regex with `(?-i)` to match exactly or `(?i)` to match insensitively; this overrides _Match case_.  This is similar to the way the `. matches newline` checkbox can be totally ignored (overridden) by leading off your regex with `(?s)` or `(?-s)`.

> please offer an option in the preference settings to force case-sensitivity.

This will not be offered, but thank you for your suggestion.

**Comment by f6fvy** [comment]
I understand you clearly don't give a sh*t, but this totally breaks compatibility with other regex tools or copying/pasting regex from other tools. So be it :-(

**Comment by sasumner** [comment]
If your goal is "compatibility with other regex tools" and "pasting regex from other tools" (which you neglected to mention in your first posting), then tick Notepad++'s _Match case_ checkbox and you should be fine.

A word of caution with "other regex tools" -- unless these tools directly support the Boost flavor of regex, you are likely to run into situations where the tool and Notepad++ yield different results, making a "match/not-match case" thing seem trivial.  Other cautions include considerations for how Notepad++ conducts non-global (i.e., non-Find-All, non-Replace-All) searches/replacements -- often going to be different than "other tools" and in this case, even if these other tools do support Boost regex.

**Comment by f6fvy** [comment]
> you are likely to run into situations where the tool and Notepad++ yield different results, making a "match/not-match case" thing seem trivial.

One additional reason to get rid of this incompatibility, at least. Honestly, I don't understand this will that only annoys the user. But as the author of Notepad (I think), you probably have your own reasons.

**Comment by sasumner** [comment]
>But as the author of Notepad (I think)

Nope! Not me! :-)

>I don't understand this will that only annoys the user

Reported user count that this has bothered since version 6.0 introduced regex:  1.
We'll keep tabs on that count, moving forward.

**Comment by dayvan** [comment]
>Reported user count that this has bothered since version 6.0 introduced regex: 1.

Add me to that count ;-)
I also find it annoying and confusing because it seems counter intuitive to need to select Match Case since you're specifying the pattern as either lower case or upper case character range .
In the wikipedia article about regex, all the mentions of [a-z] and [A-Z] explain them as applying to lower case and upper case characters (respectively)
https://en.wikipedia.org/wiki/Regular_expression

All regex implementations that I've encountered on different apps, seem to be case-sensitive by default.

**Comment by sasumner** [comment]
Just for the heck of it, I'll mention that Visual Studio 2019 's editor has the same interface and behavior as Notepad++ in this regard:

![image](https://user-images.githubusercontent.com/30118311/84780167-3f0c5100-afb3-11ea-90fe-ff43ede9346e.png)
