### ISSUE TITLE
Backing up and restoring the style configurator settings

### ISSUE THREAD

**Issue by rovf** [notepad-plus-plus/notepad-plus-plus#8313]
### Description of the Issue
I have made changes using the style configurator to theme ("Mono Industrial"), because the original settings made the code hard to read (several syntax elements for the Ruby language were defined as "black on black") and I would like to backup the modified settings, so that I can restore them in case I have to reinstall the editor.

Since I did not find any menu item for "saving and restoring" the style settings, I was searching my disk for files, which possibly could hold such a setting. I found indeed a suspicious file below %APPDATA%/Notepad++, with the path ' themes\Mono Industrial.xml', but it did not have the current date and hence can't be the correct file holding my changes.

Where are these changes stored?
### Debug Information
Notepad++ v7.7.1   (64-bit)
Build time : Jun 16 2019 - 21:24:47
Path : C:\p\nppp64bit\notepad++.exe
Admin mode : OFF
Local Conf mode : ON
OS : Windows 10 (64-bit)
Plugins : AnalysePlugin.dll AutoEolFormat.dll Comment Wrap.dll ComparePlugin.dll CustomLineNumbers.dll MenuIcons.dll mimeTools.dll NppConverter.dll NppFavorites.dll NppXmlTreeviewPlugin.dll SelectQuotedText.dll SurroundSelection.dll XBrackets.dll _CustomizeToolbar.dll

**Comment by sasumner** [comment]
>Local Conf mode : ON
>Path : C:\p\nppp64bit\notepad++.exe

When "Local Conf mode" is "ON" Notepad++ doesn't use "appdata".

You are running with your configuration stored at below the folder level of your notepad++.exe file.

Check files in your `C:\p\nppp64bit\themes` for changes.

**Comment by rovf** [comment]
Thanks! That's is it.
