### ISSUE TITLE
Display file name as root of workspace instead of "Workspace"

### ISSUE THREAD

**Issue by Uhf7** [notepad-plus-plus/notepad-plus-plus#8314]
If I open a new workspace, no file is associated to it, so it looks like this:

![Ws_New](https://user-images.githubusercontent.com/40629737/82841360-0efef000-9ed6-11ea-9912-e38cb6e94990.png)

After I open a workspace file, it looks like this:

![Ws_File_Ws](https://user-images.githubusercontent.com/40629737/82841396-2e961880-9ed6-11ea-8f48-aefee2890b78.png)

Wouldn't it be nice to display the workspace file name instead of "Workspace"? Like this:

![Ws_File_Fn](https://user-images.githubusercontent.com/40629737/82841446-5e452080-9ed6-11ea-9803-b7088e862036.png)

It's only a very small code modification, if you would consider this to be good too. As long as there is no file associated, it remains "Workspace". As soon as a file is associated, the filename is displayed.

**Comment by sasumner** [comment]
Is it best to keep the extension on it, or only show `ws1` ?
Would it be good to show its complete path as a tooltip for mouse hover?

**Comment by Uhf7** [comment]
The complete path is already shown as tool tip.

I find, if the extension is omitted, then it is not so easy to identify it being a file name. It looks then like an editable title, same as "Project1" is.

**Comment by sasumner** [comment]
>I find, if the extension is omitted, then it is not so easy to identify it being a file name. It looks then like an editable title, same as "Project1" is.

Seems reasonable; keep the extension.
