### ISSUE TITLE
[Folder as Workspace] Label (tooltip) for buttons

### ISSUE THREAD

**Issue by ArkadiuszMichalski** [notepad-plus-plus/notepad-plus-plus#8325]
Please add some label (as tooltip) for this three buttons: 

![image](https://user-images.githubusercontent.com/2730894/83016004-960caf00-a021-11ea-9975-b9e962c3d35a.png)

Maybe "Unfold all folders", "Fold all folders", "Select in list active file (if exist)" or something similar. At first time I could not determine what 3rd button do, especially  when active file in tab bar is not part of the project panel.

**Comment by donho** [comment]
How about (from left to right): "Expand all folders", "Collapse all folders" and "Locate current file" ?

**Comment by ArkadiuszMichalski** [comment]
Looks good to me.
