### ISSUE TITLE
Document Map regression under Windows 7

### ISSUE THREAD

**Issue by Uhf7** [notepad-plus-plus/notepad-plus-plus#8335]
I recently created some PR's which fixed some issues with the Document Map, in which the transparent window marking the current text range within the document has been detached from the rest of Npp and was displayed then on another virtual desktop or another physical desktop than Npp itself. This modifications, however, only work under Windows 10. They destroyed the Document Map under Windows 7 and Windows Vista. I realized this only now while testing another issue, see #3747. I feel guilty. I want to send my apologies to all Windows 7 users with the upcoming PR, which keeps all advantages of the new behavior under Windows 10, but reverts them for Windows 7. The technical reason for it is, that Windows 7 does not support layered style for child windows.

**Comment by donho** [comment]
@Uhf7 
Could you provide the screenshot of bug please?

**Comment by Uhf7** [comment]
Under Windows 7, without PR #8336, it looks like this:
![DocMap-W7-New](https://user-images.githubusercontent.com/40629737/83247103-5cfc4800-a1a3-11ea-8ceb-542c87eb8be2.png)
Imagine a flickering, not-transparent, dark-orange rectangle above it while scrolling. Couldn't catch this.
But, for testing, you can make it behave like this under Windows 10, if you comment out the line
`(NppParameters::getInstance()).SetTransparent(_vzDlg.getHSelf(), 50);`
in
`DocumentMap::run_dlgProc`.

The problem is, that Windows 7 is simply incapable to add the `WS_EX_LAYERED` style to child windows, which I had not in mind while creating the PR.


With PR #8336, the Document Map under Windows 7 will look like this again:
![DocMap-W7-PR](https://user-images.githubusercontent.com/40629737/83248026-b7e26f00-a1a4-11ea-9b5f-8a6d0a343f57.png)


With PR #8336, the improved behavior under Windows 10 remains untouched, but the old behavior under Windows 7 is restored. This old behavior includes the following effect, observed here with the original 7.8.5 release (it is the same in the 7.8.6 original release):
![DocMap-W7-Old-785](https://user-images.githubusercontent.com/40629737/83248509-73a39e80-a1a5-11ea-9820-8ac2d8c0ed31.png)
I cannot remove this effect under Windows 7. It comes from the transparent window being actually a top level window instead of a child window of Npp, and so it doesn't know it's correct place in the z-order. As soon as you click it, it comes to top and says: Hi', I'm the most important window of Npp, above all others. And if you then press Win+Ctrl+Left/Right, it even jumps to another monitor without Npp.

So what I go for here: Fix it in Windows 10 (already done with PR #8280), but leave it in Windows 7 as it is (with PR #8336). The effects cannot be fixed in Windows 7 easily.
