### ISSUE TITLE
 [Feature Request] Add tabs counter in visible place

### ISSUE THREAD

**Issue by ArkadiuszMichalski** [notepad-plus-plus/notepad-plus-plus#8338]
Please consider adding a tabs counter in somewhere in a visible place, for example:
1. Before `X` button in Menu bar.
2. Or somewhere in Status bar.
3. Or any other better visible place.

This is a very convenient improvement for people who work on a large number of tabs, and sometimes by mistake we close some tab/tabs. With tabs counter we can easy control if our sets of tabs is complete.

Format for tabs counter can be just `Number` or `Number/Number` (for two views), or more obvious like `Tabs: Number` or `Tabs: Number/Number` in Status bar. This can also be optional for people who don't need it (some checkbox in Preferences).  In detail, this can be done in different ways, it is more important to accept this future.

**Comment by ArkadiuszMichalski** [comment]
We have information about: numbers of chars, numbers of lines, numbers of words, numbers of chars in selections, etc., but not how many files we have opened. At least in this window, which is dedicated for tabs.
![image](https://user-images.githubusercontent.com/2730894/83683092-1fede680-a5e5-11ea-9044-8a3665768409.png)
Let it be so, I will look for a solution through a plugin.

**Comment by sasumner** [comment]
>I will look for a solution through a plugin.

A scripting plugin could easily do it; example with Pythonscript, with 4 open tabs in Notepad++:

![image](https://user-images.githubusercontent.com/30118311/83684372-eb623680-a5b4-11ea-98cd-6b4586bbc7c0.png)

**Comment by sasumner** [comment]
Another method is to do a _Find All in All Opened Documents_ with a _Find what_ of `\z` in _Regular expression_ search mode.  This will give you something like `...(4 hits in 4 files)` which would indicate that 4 total tabs are open.

**Comment by ArkadiuszMichalski** [comment]
When I doing the translation I just noticed this information in the search result window, but with usability it has little to do, it will come across in a different direction. But I still think it could be added at least here:
![image](https://user-images.githubusercontent.com/2730894/83743544-261eaa00-a65b-11ea-8c26-5cb18ea28fa1.png)
In fact, thanks to the OK button we have free space for additional info. But from my perspective, I still need a real preview, not hidden somewhere, so look around for something else.

**Comment by sasumner** [comment]
Adding it in the box that appears when one chooses _Window_ menu and selects _Windows..._ as shown immediately above seems a reasonable way to do it.  Reopening.

**Comment by donho** [comment]
@ArkadiuszMichalski 
> With tabs counter we can easy control if our sets of tabs is complete.

So you mean the total number of opened documents in Notepad++.
What's the concrete example that you need this feature?

**Comment by sasumner** [comment]
I'm not sure that knowing the count of tabs open is really a valuable thing, but I suppose I can see some use for it.
It might be nice to know how many are open in each "view" if both views are currently open, as well.

**Comment by ArkadiuszMichalski** [comment]
@donho 
I mostly works on a lot/tons of tabs. With such a number, there is often a risk of closing one by mistake, for example, by clicking on the red icon, the middle mouse, etc. My hands are not that precise anymore, and sometimes I will click something right on the tab and I don't know if the tab has closed or not. Sometimes my mouse get lags (or other strange things) and I don't know if any tabs was closed by this.
With many open tabs this is a problem, because if I have to change something in all tabs, I am not sure if all tabs are open. For this, I need some indicator of how many tabs are actively open so that I know that I have not closed any by mistake. For example, if at a given moment I work with 100 tabs and I have a counter that shows me that there is 100, I know that any changes will be made in all of them.

Currently, I use sessions to prevent this, but that requires some extra work, periodic saving of the current state, and controlling the number of entries per session (with funap plugin https://github.com/funap/npp-explorer-plugin/issues/27#issuecomment-737173852), which is not as convenient as live information.

But personally, I'm looking for something that is visible right in the main window, even by a plugin. Looking into the Window window is not very convenient because it is modal, but as a last rescue it can be (if that's the only acceptable option).

**Comment by sasumner** [comment]
@ArkadiuszMichalski Your rationale makes sense.

>I'm looking for something that is visible right in the main window

I don't know that I see a great place for that.
It might help, if you, as a big proponent of this feature, would suggest a location.  :-)
Don't say "status bar".  :-)

What about adding information to the title bar as follows:

Existing:  `C:\mypath\myfile.txt - Notepad++`
Possible:  `C:\mypath\myfile.txt (34/100) - Notepad++`

Thus showing both the active tab's current position (in the active view), e.g. 34th, and the total number of tabs in the active view, e.g. 100.

The "current position" of the tab wasn't requested, but since the titlebar text is related to the currently active file, it doesn't make sense without it.

**Comment by sasumner** [comment]
BTW, it is a shame that someone had to spend time to create a PR for this issue to get us all talking about it again.  :-(

**Comment by donho** [comment]
> What about adding information to the title bar as follows:

I don't think it's a good place for such info.

> But personally, I'm looking for something that is visible right in the main window, even by a plugin.

I agree with that this feature should be in a plugin rather than in Notepad++ : such information is not pertinent for the most of users.

> BTW, it is a shame that someone had to spend time to create a PR for this issue to get us all talking about it again. :-(

Yes, I know. But I need to have fun (coding) me too rather than watching all the issues...

**Comment by donho** [comment]
>> What about adding information to the title bar as follows:

> I don't think it's a good place for such info.

OTOH, it's OK to me to add this info on the title of Window dialog:
`Window - 45 documents opened`

@ArkadiuszMichalski 
Do you think it's worth to you or you prefer to find another solution (a plugin, a script...) ?

**Comment by sasumner** [comment]
>I need to have fun (coding) me too rather than watching only all the issues...

Absolutely true!

>OTOH, it's OK to me to add this info on...

Why not have a look at the PR for this issue that has already had some code written for it?
If the solution there is acceptable, you (or someone else) doesn't have to come up with an alternate solution...and do more coding.
Thus, you will have time to read more issues.  :-)
Even if the PR is not acceptable, why not coach the person that submitted it, into changing it how you want it?
Then you still save time; maybe you don't code, but this one isn't very interesting anyway! :-)

I haven't really looked at the code for that PR, other than to make one small comment on it, but the concept of adding a status bar to the window to provide the requested data seems reasonable.

**Comment by sasumner** [comment]
@ArkadiuszMichalski Even if this information is not provided in the main window, but rather in the "Windows" window, all you have to do to show it is `Alt+w` then `w` then after you see the count do a `o` or an Esc.  (You may have to adjust that if your keyboard is non-English).  It is a FAST thing to do.

**Comment by sasumner** [comment]
@ArkadiuszMichalski 

Basing the following on what I started talking about here: https://github.com/notepad-plus-plus/notepad-plus-plus/issues/8338#issuecomment-638436125 ...

Here's a script that will put the info you want into the status bar.
You just have to tie the script to a keycombo to run it on-demand:

```
# -*- coding: utf-8 -*-
from Npp import notepad, STATUSBARSECTION
total_tab_count_in_both_views = len(notepad.getFiles())
notepad.setStatusBar(STATUSBARSECTION.DOCTYPE, 'tab count: ' + str(total_tab_count_in_both_views))
```

**Comment by ArkadiuszMichalski** [comment]
>@@donho
OTOH, it's OK to me to add this info on the title of Window dialog (rather than adding a status bar for it):
Window - 45 documents opened
Do you think it's worth to you or you prefer to find another solution (a plugin, a script...) ?
Edit: or a static control on the bottom of Window dialog to display this info

The title can also be good if we assume that nothing else will be added in the future here. Well, the extra space at the bottom can be more futurable, if someone would like, for example, total file sizes or other things (like how many files was select).

>@sasumner 
I don't know that I see a great place for that.
It might help, if you, as a big proponent of this feature, would suggest a location. :-)
Don't say "status bar". :-)
What about adding information to the title bar as follows:
Existing: C:\mypath\myfile.txt - Notepad++
Possible: C:\mypath\myfile.txt (34/100) - Notepad++

If this were the only option a title could be, but mixing long path names with other numbers can make them difficult to read quickly. I also wonder where it could be added, and the only sensible options are the status bar or an additional control before by the `[X]` that closes the current tab (top-right on the menu bar, we have some space here, even for large number). For people who don't need it, I would just give a option `General> Tabs bar> [] Show tabs counter`.
From a plugin's perspective, I'd expect same as above, or some wider button/other control to display this infos, something similar to what [NppMenuSearch]( https://github.com/peter-frentrup/NppMenuSearch) does. 

>@sasumner
@ArkadiuszMichalski Even if this information is not provided in the main window, but rather in the "Windows" window, all you have to do to show it is Alt+w then w then after you see the count do a o or an Esc. (You may have to adjust that if your keyboard is non-English). It is a FAST thing to do.

I am aware of this, and unless I can do it more conveniently in other ways, this one will be basic, if it passes. **Only note that the Window window displays information only for one view, so if you want to have for two you have to do it separately.**

>@sasumner
Here's a Pythonscript that will put the info you want into the status bar.
You just have to tie the script to a keycombo to run it on-demand:

I just browsed the API of this plugin to solve it and it could be, I just don't know how it modifies the status bar, adds a new entry or changes an existing one? I would prefer not to modify the basic information of the program. The basic problem with this plugins  is that we can't create the status bar information in a specific place, such as at the beginning, end, or before specific 
 built-in items, unless I'm wrong, I haven't tested it yet.

Basically I will still be trying to have this counter  in the main window because for me it is more convenient and means less work, I can control this state directly without any additional actions. Probably writing such a plugin takes a few minutes of work (reading tabs + some events for closing / opening tabs and updating values), but you need skills for that. Anyway, the information about the number of open files in the Window window seems rational, now we can only determine it with Search window or count manually.

A few more thoughts:
- for accidentally closing tabs (if there are many), the Lock / Unlock Tab bar (or tabs) option would be the solution. If enabled, tabs cannot be closed (opening still works). Then we could switch it quickly and be sure that something will not disappear by accident. To inform that this option is enabled, you can give the [X] button (top-right on menu bar)  some style, eg. red color (plus aditional tooltip, or dissabled it). But this idea could be discussed in a separate bug.
- we can also control the Recent Closed Files list and if something appears there, it means we closed something by accident. But this requires keeping the list empty, so if we open and close any extra file / files for a short while we need to clear this list.

**Comment by sasumner** [comment]
@ArkadiuszMichalski 

Please, **_TRY_** the Pythonscript.
It could make you forget you even asked for anything more. :-)

The script just temporarily overrides what is shown on the leftmost part of the status bar with the info you desire.
The leftmost part of the status bar normally shows the tab's "Language" which is rarely useful -- you already know what type of file you are editing.

Example, normally the status bar shows something like this:

![image](https://user-images.githubusercontent.com/30118311/101984250-1c02e700-3c4e-11eb-98b3-c2ffcb9861b2.png)

When you run the script you get, instead:

![image](https://user-images.githubusercontent.com/30118311/101984292-65ebcd00-3c4e-11eb-969a-99526b5af9b5.png)

It is not permanent; if you switch to a different tab, the `tab count` data is overwritten with the usual "Language" data.  It only reappears when you invoke the script again the next time you need to check/verify the count.

**Comment by sasumner** [comment]
@ArkadiuszMichalski Here's a "fun" way to get the tab count:

Do a _Find All in All Opened Documents_ with a _Find what_ field that has nothing in it.
You will get something like this in the _Search results_ window; here I had 38 open tabs:

![image](https://user-images.githubusercontent.com/30118311/101985504-756f1400-3c56-11eb-9f36-0cc27ac05a3d.png)

**Comment by ArkadiuszMichalski** [comment]
@sasumner 
Yes, you mention about it as second suggestion: https://github.com/notepad-plus-plus/notepad-plus-plus/issues/8338#issuecomment-638454698.

In the first step, I'll try with Pythonscript, but it's a pity that it doesn't have a separate item on status bar to output  it's own information ([only override exist](http://npppythonscript.sourceforge.net/docs/latest/enums.html#STATUSBARSECTION)). With the [NOTIFICATION](http://npppythonscript.sourceforge.net/docs/latest/enums.html#NOTIFICATION) this can be update dynamically (when open/close tabs), but because of this overwriting the built-in position, I will have to sacrifice something. Sooner or later I'll probably write some plugin for this, but first I have to finally start learning how to do it.

**Comment by sasumner** [comment]
@ArkadiuszMichalski 

>Yes, you mention about it as second suggestion

Ah, yes, time fades the memories. :-)
I also just noticed that you can search for empty text in _Find what_, which surprised me, so I used my comment of an hour ago as an opportunity to mention that.

**Comment by sasumner** [comment]
>it's a pity that it doesn't have a separate item on status bar to output it's own information

Status bar only can hold so much; I think Don is probably very protective of it (and would not be in favor of adding anything substantially new to it).

I use a status-bar overwrite like I described in many many of my scripts.
It is not a big deal -- as I described, how much value is looking at "Normal text file" or "Python file" all the time, when you ALREADY know the file's type/Language?

But, the script is just a suggestion.
I think it is fine to have the requested information somewhere on the UI of Notepad++ (meaning a real code change).
However, the trouble continues to be, to decide exactly where on the UI it should be.
I think that decision is up to @donho now.

**Comment by ArkadiuszMichalski** [comment]
>@sasumner 
Status bar only can hold so much; I think Don is probably very protective of it (and would not be in favor of adding anything substantially new to it).

But there's no way to add own item, even with a plugin? I have seen  in the past that some plugins return something to the status bar, but I don't remember exactly how they did it (add own entry or change in-build), I will try check them later.

You know, I will not insist on adding this counter to the main window, because if nobody has written anything here so far, maybe not many people need it. So this looks like a perfect job for plugins. The main problem for me is accidentally closing tabs if we have many open tabs, so I realize that the option to block closing tabs (check last thoughts https://github.com/notepad-plus-plus/notepad-plus-plus/issues/8338#issuecomment-743729230) fits better here, and the tab counter for main window can be covered with plugins (existing or own).

**Comment by sasumner** [comment]
>But there's no way to add own item, even with a plugin?

Not sure.  I would think the only reasonable way for a plugin to do it would be to do it on the far right, because Notepad++ itself is always going to keep updating the existing ones, and something external would have to modify the width of the existing ones to fit something additional, and then if the main window is resized after that, Notepad++ would restore the original widths of the existing sections...and it just sounds so complicated that it makes the "temporary override" thing that I mentioned seem like an even better answer.

>The main problem for me is accidentally closing tabs...

How does this happen, typically?

- If double-click-to-close option -> disable it
- If accidental hit on close-button-on-each-tab -> disable it
- If accidental press of Ctrl+w (default File>Close combo) -> remove it
- This probably leaves the tab-right-click menu, which I don't know of a way to disable/remove that

**Comment by ArkadiuszMichalski** [comment]
>How does this happen, typically?

- left click on red [x] -> yes, can be disabled in Pref
- ctrl+w ->yes, can be removed in Shortcut
- middle mouse button -> can be disabled?

Another important thing, all of the above can be done in one action? I mean, with a single command, turn off the above and then restore default behavior if necessary. Do they have their ID to cover it with some plugin? I don't always have multi-tab NPP running, and in this case the default behavior is acceptable. It would be a pain to switch these three settings over and over again.

**Comment by sasumner** [comment]
@ArkadiuszMichalski 

I don't really understand your workflow.  We all have our own workflows so I suppose that is not too unusual that I don't understand yours.

If I were doing it, in other words, my hypothetical workflow, I'd disable all except one way of closing a tab.
For me it would be the right-click-tab menu that would be the only way to close (because I can't think of an easy way to disable it).

I've never understood the middle-mouse-button thing and how one would accidentally do it.
For all the mice I've ever used, pushing the middle-mouse-button (tied to the mouse-wheel) has always been such an awkward action, I've never done it, on purpose (except to try it and decide "this is awful") or accidentally.

**Comment by sasumner** [comment]
@ArkadiuszMichalski 

If I had your workflow, what I might do to "protect" myself is to write a Pythonscript that will constantly monitor the number of open tabs, and if that changes, present a popup window to alert me.

So, during some critical editing session, if I'm supposed to be working with 37 files, I run my script and tell it I have 37 files.  Then I start working...  When done with the critical actions, I run the script again and tell it to stop monitoring.  If any time during the "critical" time, the script sees less than 37 files (or potentially, more) it pops up the warning box and then I can decide what I need to do to fix the problem situation I've gotten into.

**Comment by ArkadiuszMichalski** [comment]
@sasumner 
Yes, I realize that with Pythonscript and [NOTIFICATION](http://npppythonscript.sourceforge.net/docs/latest/enums.html#NOTIFICATION) I can detect close action and react. If aborting the closing is not possible then I can probably find the name / position of the closed file and then try reopen it again. I can also display some dialog to inform about closing (or put big info to status bar), so after that I can reopen file with Recent Closed Files list (but this not remember orginal position, always restore file as last in tab bar).
If it is possible to detect which key is pressed in Pytonscript, then the shutdown could be continued, e.g. after pressing Ctrl or Shift, or other key. This will make closing possible, but in a more complex way.
If [canceling callback](http://npppythonscript.sourceforge.net/docs/latest/intro.html#cancelling-callbacks) is possible from the next script execution, then I can do it as on / off when I need it.
Thanks for the tips, I'll play with it and see what I can fry.

**Comment by ArkadiuszMichalski** [comment]
Finally someone ask:
https://community.notepad-plus-plus.org/topic/20589/how-many-files-are-opened-show-number
