### ISSUE TITLE
Bug with macro in large files

### ISSUE THREAD

**Issue by hholler** [notepad-plus-plus/notepad-plus-plus#834]
I think I found a bug in NPP (possibly windows version only, didn't try others) when executing a macro that simply puts commas in fixed width data to be able to save it as CSV, so I can analyze it with R. The data files I've used are freely available from NOAA (example: ftp://ftp.ncdc.noaa.gov/pub/data/noaa/2014/873440-99999-2014.gz ; the explanation for the format used is at http://www1.ncdc.noaa.gov/pub/data/ish/ish-format-document.pdf) and in the video below I block-copied a subset of the file to a new document for the comma-treatment. The outcome would be similar with the whole file, though.

Here's a video that shows what I did: https://youtu.be/0EZ4VBLm6JQ

In it, I create the macro and it works great for a number of lines, so I had it repeat 100 lines at a time (it's 12.000+ in the file). After a couple repetitions, all of a sudden some character in the middle of a line gets deleted and a CR LF appears at the end of all remaining lines, while the first character of all following lines becomes invisible. I can delete the CR LF - and the first character appears again, but the one deleted is still gone. Also I'd still have 10.000 lines or so to go, so I won't do that manually for every following line. 

Instead I undid (CTRL-Z) the last batch of 100, thinking that that would repair my file as well. But it doesn't. The commas disappear but the CR LF stays and the deleted part of the line also does not reappear. I've tried that several times, the error reappears at different lines in different tries, but it always does (yay: a reproduceable bug!), essentially corrupting the file I'm working with. 

I've since found a way around NPP for MY needs, but still wanted to point this out as it might make use of macros in NPP risky.

**Comment by dail8859** [comment]
Do you have backups enabled? If so I'd try turning those off and see if it happens again.

**Comment by hholler** [comment]
No backups, but auto-save every 7 sec (!) (is that a default? I don't remember setting it up like this). When switching that off, the macro does indeed run without problems for the first time. I'd have to try a few more files to see whether this is really the problem, but it looks promising.

**Comment by dail8859** [comment]
Yes that is default. There were similar issues in the past that have been addressed. This shows up more with large files (since it takes longer to save them) which is exactly what you are seeing.

**Comment by hholler** [comment]
Interesting. Indeed the macro does run correctly with all files I've tried now that I've switched auto-save off. I don't know if you want to consider this issue "resolved", though, because it's going to pop up again eventually. 
Maybe there should generally be a check whether a macro is currently running before trying to save a file, if that 7 seconds rule is a default setting. Just a thought.

**Comment by dail8859** [comment]
Definitely still a bug that needs fixed.
