### ISSUE TITLE
Support for more programming languages

### ISSUE THREAD

**Issue by zrzjohn** [notepad-plus-plus/notepad-plus-plus#8341]
### Description of the Issue
Excuse me, can Notepad++ support for more programming languages?

### Steps to Reproduce the Issue
1. I want to write lex, yacc and go;
2. I don't want to write user defined format;
3. Can Notepad++  support for more programming languages?

**Comment by zrzjohn** [comment]
@notepad-plus-plus
Can you do it?

**Comment by chcg** [comment]
You can have a look at https://github.com/notepad-plus-plus/userDefinedLanguages/tree/master/UDLs if already an approriate UDL exists. Apart from that first a scintilla lexer is needed to be able to add the N++ support for it. See:

- https://sourceforge.net/p/scintilla/feature-requests/99/
- https://sourceforge.net/p/scintilla/bugs/2036/

for the mixing lexers from scintilla side.

**Comment by sasumner** [comment]
Let's close for now, and will reopen if Scintilla provides support for these languages.
