### ISSUE TITLE
Missing language code for several localization in the -L argument

### ISSUE THREAD

**Issue by ArkadiuszMichalski** [notepad-plus-plus/notepad-plus-plus#8347]
Hi, I check all current localizations in the `-L` argument and actually the following are not support (missing condition in the [Parameters.cpp](https://github.com/notepad-plus-plus/notepad-plus-plus/blob/master/PowerEditor/src/Parameters.cpp#L3784) file):
1. aranese.xml - from [Wiki](https://en.wikipedia.org/wiki/Aranese_dialect) there is no ISO code but is IETF `oc-aranes`
2. english.xml - please make support this variant by some value (even the name of the localization file)
3. english_customizable.xml - please make support this variant by some value (even the name of the localization file)
4. extremaduran.xml - from [Wiki](https://en.wikipedia.org/wiki/Extremaduran_language) this can be `ext`
5. kabyle.xml - from [Wiki](https://en.wikipedia.org/wiki/Kabyle_language) this can be `kab`
6. ligurian.xml - from [Wiki](https://en.wikipedia.org/wiki/Ligurian_(Romance_language)) this can be `lij`
7. piglatin.xml - from [Wiki](https://en.wikipedia.org/wiki/Pig_Latin) there is no code (maybe use file name?)
8. samogitian.xml - from [Wiki](https://en.wikipedia.org/wiki/Samogitian_dialect) this can be `sgs`

It would be good to always defined language code when adding new localizations.

**Comment by ArkadiuszMichalski** [comment]
After https://github.com/notepad-plus-plus/notepad-plus-plus/commit/47bb08ee6c3bd18171585e095229a71d9b71e08b also missing code for `irish.xml` - from [Wiki](https://en.wikipedia.org/wiki/Irish_language) this can be `ga`.

**Comment by donho** [comment]
irish.xml, aranese.xml, extremaduran.xml, kabyle.xml, ligurian.xml and samogitian.xml are added for -L flag.
english.xml and english_customizable.xml  are not necessary since by default it's in English.
piglatin is kind of joke so it's not added neither - who wanna use it ?

**Comment by ArkadiuszMichalski** [comment]
@donho 
Piglatin it's a small thing, but missing `english.xml` for -L flag is problem, in normal case I use my native lang but sometimes I have to switch to English (to check sth or explaining in team) and I can't use -L flag (via scripts) because lack of code for these language, using UI to sweet lang need much more work and it's remember in config file so I must remember back to previouse language, again more work. No chance to set anything for the -L argument for english.xml?
