### ISSUE TITLE
Impossible to register an account in the Forum

### ISSUE THREAD

**Issue by Neustradamus** [notepad-plus-plus/notepad-plus-plus#8348]
Currently, it is impossible to register an account in the Forum, can you look?

Thanks in advance.

**Comment by sasumner** [comment]
Regardless, it isn't the type of "issue" to be dealt with here, so closing.

**Comment by Neustradamus** [comment]
@ArkadiuszMichalski, @sasumner: I confirm, the problem is always here:
- https://community.notepad-plus-plus.org/login

Not possibility to registrer on the NodeBB.

Can you reopen it?

There is not a place to inform about this problem except here.

**Comment by sasumner** [comment]
This is probably not much we can do for you because the forum isn't something we have a lot of control over (we just use it).
But...to get anywhere, you're going to have to supply more than "Not possibility to registrer on the NodeBB."

What happens when you try?
Screenshots?

**Comment by Neustradamus** [comment]
@sasumner: There is only connection but not possibilty to create an account.
- https://community.notepad-plus-plus.org/register

For example:

No problem here: https://community.nodebb.org/
- https://community.nodebb.org/register

**Comment by sasumner** [comment]
Those aren't screenshots.

**Comment by ArkadiuszMichalski** [comment]
Looks like standard register is off. Why you don't use login from Facebook, Twitter, Google or GitHub?
https://community.notepad-plus-plus.org/login

**Comment by sasumner** [comment]
Oh, that's the problem.
Well, since the Community has been in use, it has always forced Facebook etc login.
That isn't going to change.

**Comment by Neustradamus** [comment]
@sasumner: It is a big security problem.
It is better to have internal account.

**Comment by ArkadiuszMichalski** [comment]
Maybe beter for other, but for @donho it would probably mean tons of spam. If you are concerned about security can't create a second account in these services?

**Comment by donho** [comment]
@Neustradamus 
You can use your current Github account - we don't keep users' login & password for the sake of security (no responsibility for us)

**Comment by Neustradamus** [comment]
@donho: The problem is to use external companies.
