### ISSUE TITLE
[feature request or fix] Find in directory not great

### ISSUE THREAD

**Issue by batata004** [notepad-plus-plus/notepad-plus-plus#8349]
I've been using Dreamweaver for a long time and the #1 thing that I really love in it is the search string inside directories or files. BUT I love more notepad++ and I've been using it as much as I can but everytime I have to perform a search in directories I still have to use dreamweaver.

Let me start talking about search inside files: when I search some string inside a file, dreamweaver starts searching the string starting from the caret/cursor position and keeps going and pointing me the occurrences. When it reaches the end of the file it just stars from the beginning of the file and keeps searching UNTIL it reaches caret - then it stops searching and warns the user.

Notepad++ on the other hand, when using the default "Find next" button it only searchs ahead of the caret/cursor and if it reaches the and of the file it does not start from the beginning. This annoys me so much cause I have to click the checkbox on the right of the FIND NEXT button and then I have to click the arrow up button so notepad++ searches all the way up, starting from the bottom. 

It would be much nicer that the DEFAULT behaviour of the FIND NEXT should search the first occurrence after the caret position and keeps searching, if it reaches the end of the file it should then start from the beginning till reach the caret position and alert the user it already scanned all the document.

One more feature request: when searching on directories using Dreamweaver I can just go clicking next and it performs the seearch each file and when it finds a occurrence, it stops, opens the file and places the pointer on the ocurrence inside the file. If I click NEXT if keeps searching inside other files and everytime it finds a occurrence, it OPENS the file which the occurence highlighted and the cursor in the right position.

I have no idea why notepad++ does not do that, instead it shows a list of all occurences at the bottom and I have to manually click each one to open the files and if the file was changed after the search, the caret position will probably be in the wrong position!

I love notepad++ and this is the only thing so far that I dislike in it and the only reason why I still have dreamweaver installed on my machine.

**Comment by Ekopalypse** [comment]
I assume your first feature request is already implemented by the wrap around checkbox
![image](https://user-images.githubusercontent.com/47723516/83360418-c1b8cd80-a370-11ea-95e2-ebcbaee7feb8.png)

Your second feature request seems to be covered by the "open all" feature of the context menu
in the find result window.

**Comment by sasumner** [comment]
I think @Ekopalypse addressed the points well, so I'm going to go ahead and close this issue.

**Comment by batata004** [comment]
WOW GREAT!! I was not aware of those 2 features already implemented! You guys are awesome!
