### ISSUE TITLE
How to exclude one or more subfolders from folder opening in command line?

### ISSUE THREAD

**Issue by Neustradamus** [notepad-plus-plus/notepad-plus-plus#8350]
How to exclude one or more subfolders from folder opening in command line?

It is possible to open a folder:
- notepad++.exe "base"

- base
-- subfolder1
--- sub-subfolder1-1
--- sub-subfolder1-2
---- sub-sub-subfolder1-2-1
---- sub-sub-subfolder1-2-2
-- subfolder2
--- sub-subfolder2-1
-- subfolder3
--- sub-subfolder3-1

How to open:
- base without subfolder1
- base without sub-subfolder1-2
- base without sub-sub-subfolder1-2-2

Thanks in advance.

**Comment by ArkadiuszMichalski** [comment]
Probably there is no way to exclude some folders/files (either by negation or by some other argument), but in fact it would be useful.

**Comment by sasumner** [comment]
Is this referring to what gets opened into the _Folder as Workspace_ panel?
Otherwise, I'm confused.

**Comment by Neustradamus** [comment]
Same for "Normal mode" and "Wokspace mode", command lines:
- "C:\Notepad++\notepad++.exe" "%1"
- "C:\Notepad++\notepad++.exe" -multiInst "%1"
- "C:\Notepad++\notepad++.exe" -openFoldersAsWorkspace "%1"
- "C:\Notepad++\notepad++.exe" -multiInst "%V"
- "C:\Notepad++\notepad++.exe" -openFoldersAsWorkspace "%V"

How to exclude "one file", "two files", "*.ext", "subfolder1", "sub-subfolder1-2"?

**Comment by Neustradamus** [comment]
It is included in Notepad++ 8.2.0:
- https://notepad-plus-plus.org/news/v82-released/
- https://github.com/notepad-plus-plus/notepad-plus-plus/releases/tag/v8.2
