### ISSUE TITLE
Indent/unindent is taking long time (may be relative to the selected lines/characters) in Linux

### ISSUE THREAD

**Issue by nikunjbhatt** [notepad-plus-plus/notepad-plus-plus#8351]
### Description of the Issue
When indenting or unindenting, NPP is taking very long time. I have NPP v7.8.6, this problem was not occurring in previous version 7.8.5 / 7.8.4.

### Steps to Reproduce the Issue
1. Add 10, 20 or more lines (regardless of line length)
2. Select the lines
3. Press tab key to indent OR Shift+Tab to unindent the already indented lines

### Expected Behavior
In the previous version of NPP, the indenting or unindenting of 20-50 lines was taking almost no time, hardly a second, mostly in blink of eye.

### Actual Behavior
Now NPP is taking approx 4-5 seconds to indent-unindent approx 20 lines; and the time increases in proportion to the selected lines; more the lines, NPP is taking more time to indent/unindent.

### Debug Information
Notepad++ v7.8.6   (64-bit)
Build time : Apr 21 2020 - 15:23:03
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : ON
Local Conf mode : OFF
OS Name : Microsoft Windows 7 (64-bit) 
OS Build : 7601.0
WINE : 5.0
Plugins : ComparePlugin.dll DSpellCheck.dll Explorer.dll MarkdownViewerPlusPlus.dll mimeTools.dll NppConverter.dll NppExport.dll NPPJSONViewer.dll XMLTools.dll zoomdisabler_x64.dll
OS : Fedora 30 with KDE Plasma

**Comment by Ekopalypse** [comment]
Just to be sure that this is not plugin related, can you start npp without plugins loaded and do a retest?

**Comment by nikunjbhatt** [comment]
@Ekopalypse 
I tried disabling all plugins, then enabling all and then removing only XML Tools plugin; and presently I think the problem was because of the XML Tools plugin. There was an update available to the plugin so I updated it and now indentation/unindation is working fast.

I am closing the issue. Thank you.
