### ISSUE TITLE
Dedicated GPU memory for NPP?

### ISSUE THREAD

**Issue by teebu** [notepad-plus-plus/notepad-plus-plus#8352]
### Description of the Issue

I'm seeing dedicated GPU memory for notepad++.exe but I don't think it should have any, if it does, why is it so high?

### Steps to Reproduce the Issue

1. Run NPP for a few weeks.
2. 
3. 

### Debug Information

Notepad++ v7.8.6   (64-bit)
Build time : Apr 21 2020 - 15:23:03
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS Name : Windows 10 Pro (64-bit) 
OS Version : 1909
OS Build : 18363.836
Plugins : AutoSave.dll ComparePlugin.dll JSMinNPP.dll LuaScript.dll mimeTools.dll NppConverter.dll NppExport.dll 

![image](https://user-images.githubusercontent.com/5531844/83365524-7ea12f00-a35d-11ea-9962-932d810fe12b.png)

**Comment by donho** [comment]
It could be the issue of one of the following plugins you're using:
AutoSave.dll ComparePlugin.dll JSMinNPP.dll LuaScript.dll 

Remove them one by one to find the culprit.

**Comment by teebu** [comment]
Apart from autosave (which runs automatically), I don't use these plugins actively.

**Comment by teebu** [comment]
So far I disabled  ComparePlugin.dll JSMinNPP.dll and still... 

![image](https://user-images.githubusercontent.com/5531844/83842089-06b56a80-a6b7-11ea-8247-77e899983a75.png)

I'll disable the other two and see what happens.

**Comment by teebu** [comment]
By process of elimination, im fairly confident that the LuaScript.dll was the culprit.

**Comment by teebu** [comment]
It was because of this startup script in the LUA plugin:

```
-- Startup script
-- Changes will take effect once Notepad++ is restarted

editor1.Technology = SC_TECHNOLOGY_DIRECTWRITE
editor2.Technology = SC_TECHNOLOGY_DIRECTWRITE
```
