### ISSUE TITLE
[Folder as Workspace] latestSelectedItem argument is not used after running NPP

### ISSUE THREAD

**Issue by ArkadiuszMichalski** [notepad-plus-plus/notepad-plus-plus#8353]
State of Folder as Workspace is is saved in the `config.xml` file in `<FileBrowser>` tag. This tag has `latestSelectedItem` argument which represents the last selected item. The problem is that after restarting NPP, the item pointed to by the `latestSelectedItem` argument is not automatically selected in Folder as Workspace. Can anyone tell me why this attribute exists, if not for that?

**Comment by sasumner** [comment]
Maybe better as a question on the [Community](https://community.notepad-plus-plus.org/)?

**Comment by ArkadiuszMichalski** [comment]
But it's looks like as dead code ([search latestSelectedItem ](https://github.com/notepad-plus-plus/notepad-plus-plus/search?q=latestSelectedItem&type=Code)), so asking the question here seemed most reasonable. Why this arguments is remember in config.xml if it's never used.

**Comment by ArkadiuszMichalski** [comment]
Same question:
https://community.notepad-plus-plus.org/topic/19715/notepad-v7-8-9-released/6#5
Vitaliy Dovgan:
"Is it only me - or the “Folder as Workspace” in Notepad++ 7.8.9 (32-bit) does not restore the last selected item in its TreeView correctly?
And I can see that the value of ‘latestSelectedItem’ is correct in the “config.xml” after Notepad++ exits. But then I restart Notepad++ and it does not select the item according to the ‘latestSelectedItem’ value."

**Comment by donho** [comment]
@ArkadiuszMichalski 
Could you point to me on which version Notepad++ restores selection in “Folder as Workspace” ?

**Comment by ArkadiuszMichalski** [comment]
@donho Probably never, as I wrote in above comments, just name of this attribute suggest it should be use for this, and it's saved in the `config.xml` file.
