### ISSUE TITLE
Clickable link regression

### ISSUE THREAD

**Issue by Uhf7** [notepad-plus-plus/notepad-plus-plus#8354]
There is a small regression left over from my recent PR #8263. 

There were this mysterious lines in the original:
`// remove the flickering: it seems a mouse left button up is missing after SCN_HOTSPOTDOUBLECLICK`
`::PostMessage(notifyView->getHSelf(), WM_LBUTTONUP, 0, 0);`
Since I could see no flicker, when I created the PR, I left this lines out.

Now I can explain why this lines where there. The effect starts with Scintillas double click handling. In most cases, Scintilla captures the mouse (`SetCapture` windows API call) when the left mouse button is pressed and releases the capture, when the mouse button is released. This can be observed by wrapping some `OutputDebugMessage` calls around `_callWindowProc(_scintillaDefaultProc, hwnd, Message, wParam, lParam);` in `ScintillaEditView.cpp`. But, for unknown reasons, the mouse is not captured after the second mouse button down in the double click to the hyperlink. The chain reaction starts now, the `::ShellExecute` opens the internet browser before the the left mouse button is lifted again, and indeed, Scintilla never sees its `WM_LBUTTONUP` message.

So, the `PostMessage` call should be re-inserted, before the `ShellExecute` call, with a little more leading comment:

`// WM_LBUTTONUP goes to opening browser instead of Scintilla here, because the mouse is not captured.`
`// The missing message causes mouse cursor flicker, as soon as the mouse cursor is moved to a position outside the text editing area`
`::PostMessage(notifyView->getHSelf(), WM_LBUTTONUP, 0, 0);`

With such a comment, I would have seen the effect too.

One mystery is left here: The `PostMessage (WM_LBUTTONUP)` works only when it's done before the `ShellExecute` call, not after. I wish I could understand this too.

**Comment by donho** [comment]
@Uhf7 
Could you provide the instructions (step by step) to reproduce this regression?

**Comment by donho** [comment]
Never mind. I can reproduce it now
