### ISSUE TITLE
Delimiters with closing HTML comment inside JS string will start a comment

### ISSUE THREAD

**Issue by gianbp** [notepad-plus-plus/notepad-plus-plus#8359]
#### snippet

<!DOCTYPE html>
<html lang="it-IT">
<head>
   <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
   <title>  index </title>
   <link href="../css_files/stdstyle.css" type="text/css" rel="stylesheet">
<script type="text/javascript">
const AAAA = 2020;
const ksp=''; // error: colour of '-->' should be green
// other data
</script>
</head>
<body>
   <div style="font-size:8pt;position:absolute;left:927px;top:572px">.</div>
</body>
</html>

### Description of the Issue

in the above snippet
the colour of closing html comment seems wrong.

### Expected Behavior

the closing comment colour should be green

### Debug Information

Notepad++ v.7.8.6 -->

**Comment by ArkadiuszMichalski** [comment]
@gianbp What language did you use (or file extension)?

**Comment by gianbp** [comment]
The file contains javascript embedded in html. The file exetension is htm. 
The snippet should have been:
<!DOCTYPE html>
<html lang="it-IT">
<head>
   <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
   <title>
      default
   </title>
<script>
// style configuration: html comment gray
// js single/double string green
const AAAA = 2020; 
const ksp=""; // error: color of "" gray, should be green 
const ksp=''; // error: colour of '-->' green, colour of '-->' gray, should be green

// other js ....
}
</script>
.... html ....

**Comment by ArkadiuszMichalski** [comment]
@gianbp Can you put printscreen from your Notepad++ and mark on in were problem exist?

**Comment by donho** [comment]
Works for me in v7.8.9:

![image](https://user-images.githubusercontent.com/90293/94269442-f31c6100-ff3e-11ea-899e-cfe83415ecfe.png)

**Comment by ArkadiuszMichalski** [comment]
@donho Same for me, so ask OP for image with the bug marked:)

**Comment by gianbp** [comment]
![image](https://user-images.githubusercontent.com/66299876/94359035-01848d00-00a5-11eb-954f-7dcd89901cd9.png)

**Comment by ArkadiuszMichalski** [comment]
@gianbp Now it's clear.

**Comment by ArkadiuszMichalski** [comment]
@donho This can be reopen and mark as "scintilla dependent".

**Comment by ArkadiuszMichalski** [comment]
@sasumner Can you also change title to "Delimiters with closing HTML comment inside JS string will start a comment"? "colour" is not clear.

**Comment by rdipardo** [comment]
Fixed upstream by https://github.com/ScintillaOrg/lexilla/commit/d387a7516a115bfc7d7b7bceeae59689359bc0bd
Underlying issued marked "fixed" at https://sourceforge.net/p/scintilla/bugs/2207/#165d

**Comment by ArkadiuszMichalski** [comment]
Fixed by https://github.com/notepad-plus-plus/notepad-plus-plus/commit/a61b03ea8887e21c6e1b7374068962f635b79b80.
