### ISSUE TITLE
Unnecessary border around document view

### ISSUE THREAD

**Issue by scootergrisen** [notepad-plus-plus/notepad-plus-plus#836]
If tabs bar is enabled the document view gets a border around it.
Its only a few pixels but it seems unnecessary.

Also even when tabs bar is disabled and window maximized there are still 2 pixels to the right and left of the document view. I would prefer the scrollbar to be at the very edge of the screen.

I include an image.
The left one is with tabs bar, middle one is without tabs bars, and right one is how i would like it.
![border_around_document_view](https://cloud.githubusercontent.com/assets/1836590/9615958/c8022276-50fb-11e5-961e-088b6d6765b0.png)

**Comment by Rikk** [comment]
The official author is neglecting the [already done fix](https://github.com/notepad-plus-plus/notepad-plus-plus/pull/707) for that old and important issue.
You can use, however, my [Plus edition](https://github.com/Rikk/notepad-plus-plus) if you need a fixed version.

**Comment by dail8859** [comment]
Closed by 6c7ca02fe
