### ISSUE TITLE
[bug report] Focus on Doc Switcher instead of file content when opening

### ISSUE THREAD

**Issue by arfmach** [notepad-plus-plus/notepad-plus-plus#8364]
### Description of the Issue
I use the Document Switcher instead of tabs, to organize the list of open files to the left of the content instead of on the top. But when I open N++, after closing it with some files open, it comes with the list of open files and the focus on Doc Switcher, instead of on file content. I didn't find any hotkey to switch the focus to the file content, so I have to click with the mouse inside the content to start typing.

### Steps to Reproduce the Issue
1. Activate Document Switcher
2. Hide file tabs
3. Have one or more files open
4. Close Notepad++ with files still open
5. Open Notepad++ again (files will be brought again)
6. The focus will be on Doc Switcher instead of on file content

### Expected Behavior
When using Document Switcher to manage open files and opening Notepad++ with a bunch of previously open files, the focus should be set initially to the file content area, and not to Document Switcher.

### Actual Behavior
When using Document Switcher to manage open files and opening Notepad++ with a bunch of previously open files, the focus is set initially to Document Switcher, and not to the file content area.

### Debug Information
Notepad++ v7.8.6   (32-bit)
Build time : Apr 21 2020 - 15:17:06
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS Name : Windows 10 Enterprise (64-bit) 
OS Version : 1909
OS Build : 18363.836
Plugins : HexEditor.dll mimeTools.dll NppConverter.dll NppExport.dll NppTextFX.dll XMLTools.dll

**Comment by ArkadiuszMichalski** [comment]
F8 dosen't move focus to edit area?

**Comment by arfmach** [comment]
> 
> 
> F8 dosen't move focus to edit area?

Oh, yes, the hotkey I was looking for! Thank you very much! But it would also be useful if the focus could begin in the file content area…

**Comment by xylographe** [comment]
@arfmach 

I believe, this should be possible with the _LuaScript_ plug-in:
- Select **Plugins > Plugins Admin…**.
- Install _LuaScript_ plug-in.
- Select **Plugins > LuaScript > Edit Startup Script**.
- Add the lines below to the Startup Script, and save it.
- Restart Notepad++.

```lua
npp.AddEventHandler("OnReady", function()
  npp:MenuCommand(IDM_VIEW_FILESWITCHER_PANEL)
  npp:MenuCommand(IDM_VIEW_SWITCHTO_OTHER_VIEW)
  return false
end)
```

**Comment by arfmach** [comment]
@xylographe

Yes, it worked!

Thank you very much!

**Comment by sasumner** [comment]
@arfmach 

@xylographe provided you a workaround, but wouldn't you much rather see this solved in Notepad++ itself?  If so, consider reopening...

**Comment by arfmach** [comment]
@sasumner

I thought that the current N++ behavior was intended… After all, not all people use Doc switcher, and AFAIK, without it the focus is set to the editing area.

**Comment by sasumner** [comment]
@arfmach Ah, okay, there are some other focus-setting issues currently being worked, I didn't want this one to get lost by the person working on those...
