### ISSUE TITLE
When switching documents in Notepad++ (using the tabs) the cursor position gets lost (v6.8.1)

### ISSUE THREAD

**Issue by JohanVanSoest** [notepad-plus-plus/notepad-plus-plus#837]
Seems that bug "http://osdir.com/ml/editors.notepad++/2007-05/msg00286.html" has returned a few releases ago.

When multiple documents are opened in NPP the cursor position in File B gets lost when switching to File A and next back to File B.

This hinders multiple document editing as, after switching, one has to find the previous cursor position again. This hidden feature was not present in previous versions. I have checked all the options in Settings|Preferences but could not locate an option to turn it off or on.

Most of the files edited are asp(x) and html with syntax highlighting (Language) on.

**Comment by h-h-h-h** [comment]
I can't reproduce it in 6.8.2.

**Comment by JohanVanSoest** [comment]
Hi h-h-h-h,
Thanks for your quick reply,
Just upgraded manually to 6.8.2, hoping to get this resolved. Sadly the hidden feature is still present. See the attached animated gif for the proof of the bug.
![notepadplusplusbug](https://cloud.githubusercontent.com/assets/14082254/9647617/5efdc34a-51df-11e5-9164-752d0068e6ce.gif)

I used LiceCap to create this bug-report-movie

**Comment by h-h-h-h** [comment]
- Might it be related to a plug-in? Disabling the plug-ins could clear up the matter.
- I tested it with a simple ASP file, but could not reproduce the bug
- Does the bug show up in every environment for you? New document, text file, only "a"s in one row ...

**Comment by JohanVanSoest** [comment]
Removing plugins (all are "Stability Good" in the plugin manager):

Installed plugin | Version | Problem exists after restarting NPP?
-------------------- | ---------- | ----------------------
Code alignment | 12.0 | Yes
Compare | 1.5.6 | Yes
Converter | 3.0 | Yes
Don Rowlett Color Picker | 2.3 |  Yes
HTML Tag | 0.5 | Yes
ImgTag | 0.1 | Yes
JSON Viewer | 1.21 | Yes
MIME Tools | 1.9 | Yes
NppExport | 0.2.8 | Yes
NppFTP | 0.26.3 | Yes
Poor Man's T-Sql Formatter | 1.5.1.30381 |  Yes
Spell-Checker | 1.3.3 | Yes
Tidy 2 | 0.2 | Yes
XML Tools | 2.4.6 | No

Bad luck, The last plugin must contain the bug.

Re-installing other plugins.
*Cursor position is remembered every document switch.*

h-h-h-h Thanks for your support. Perhaps you can change the Stability status of the XML Tools plugin.

**Comment by h-h-h-h** [comment]
Fine that the issue is resolved.

But I have no access to do these things. I don't even know where this plug-in resides.

I guess if we leave the issue open someone will help bring this plug-in issue on its way.
--

**Comment by dail8859** [comment]
It is a known issue with XML tools that has been reported numerous times. I think there is an update to the plug in (not available through the plugin manager yet) you can install manually.

**Comment by h-h-h-h** [comment]
So you just have to know that? Then the issue could be closed.

**Comment by JohanVanSoest** [comment]
@dail8859 Thank you for your answer. If this "**XML Tools**" plugin has known issues, it should *not* have the status **Good** in the plugin manager, or it should be removed or upgraded as you suggest. For example the "**HTML preview**" plugin gets removed every upgrade of NPP, although it currently works great.

@h-h-h-h We can close this ticket because *my* problem is solved. However this "**XML Tools**" plugin can create these problems for others to, because the functionality provided by this plugin (a tree overview of a XML file) can be a positive reason to install it. Somehow we should be able to find out who makes the release packages, with the plugins statistics.

@donho Is it possible for you to update the NPP package list regarding the "**XML Tools**" plugin? This plugin has an impact on the status of the great Notepad++ program.
