### ISSUE TITLE
Support Cascadia Code font

### ISSUE THREAD

**Issue by xmha97** [notepad-plus-plus/notepad-plus-plus#8373]
### Description of the Issue
Hello, Notepad++ doesn't support the Cascadia Code font but Notepad support!
![Notepad++](https://user-images.githubusercontent.com/23485114/83747436-dd281f00-a675-11ea-8cc2-54bdc6a05210.png)
![Cascadia Code](https://winaero.com/blog/wp-content/uploads/2019/09/programming-ligatures.gif)
Also see: https://github.com/microsoft/cascadia-code/issues/289
Please add support for the Cascadia Code font.
Thanks.

### Steps to Reproduce the Issue
1. 
2. 
3.

**Comment by xmha97** [comment]
Duplicate: #2287

**Comment by sasumner** [comment]
Closing as issue author declared it a duplicate.
