### ISSUE TITLE
LaTeX syntax highlighting: \href{}{} will be shown with faulty links

### ISSUE THREAD

**Issue by tstone-1** [notepad-plus-plus/notepad-plus-plus#8376]
### Description of the Issue

When editing a LaTeX document and using `\href{}{}` (provided by the `hyperref` package) to include clickable hyperlinks within the `pdflatex`-generated PDF, Notepad++ will highlight & make clickable not only the URL within the first set of curly braces, but also `}{` as well as the next word.

### Steps to Reproduce the Issue

Put `\href{https://thisisaweblink.com/}{click me}` into a .tex document.

### Expected Behavior

If there's (at all) generation of clickable hyperlinks, they should include the part between `{` and `}` only.

### Actual Behavior

![Screenshot 2020-06-05 03 08 54](https://user-images.githubusercontent.com/48162401/83825883-d7185980-a6da-11ea-8587-217dec6598fd.png)
The syntax highlighting will include the curly braces to generate a clickable link for `https://thisisaweblink.com/}{click`. This generates defective links and makes the code very confusing.

### Debug Information

Notepad++ v7.8.6   (64-bit)
Build time : Apr 21 2020 - 15:23:03
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS Name : Windows 10 Pro (64-bit) 
OS Version : 2004
OS Build : 19041.264
Plugins : mimeTools.dll NppConverter.dll NppExport.dll XMLTools.dll

**Comment by ArkadiuszMichalski** [comment]
@Uhf7 Your last path will fix this?

**Comment by Yaron10** [comment]
I won't be by my PC in the coming days.

I'll test it next week.

בתאריך יום ה׳, 1 באוק׳ 2020, 18:42, מאת ArkadiuszMichalski ‏<
notifications@github.com>:

**Comment by Yaron10** [comment]
@ArkadiuszMichalski,

\href{https://thisisaweblink.com/}{click me} is not parsed as a link with 8921.
(It's not parsed as a link here either).

**Comment by ArkadiuszMichalski** [comment]
Fixed by https://github.com/notepad-plus-plus/notepad-plus-plus/commit/e32462188da8819db584272c76994a44cd61885e.
