### ISSUE TITLE
1 Rockstar feature - holding the alt key to select a column, nothing on a Mac does this to my knowledge

### ISSUE THREAD

**Issue by StewAlexanderACC** [notepad-plus-plus/notepad-plus-plus#8379]
Oh how I wish Notepad++ worked on a Mac (yeah silly me), I have to resort to Geany to have anything close to this unbelievably awesome tool.

Why are you the only editor that can select a column of text, everyone does rows, but columns, just you? Total awesomeness 👍 

If you ever make something for the Mac there'd be a throng of very very happy people.

**Comment by sasumner** [comment]
>Mac...Mac...

If this is a feature-request for a Mac version, this is a duplicate request.
It is not reasonably possible to do a Mac version out of this codebase, so this issue will be closed on that basis.

>Why are you the only editor that can select a column of text, everyone does rows, but columns, just you?

Far from accurate; many many text editors support column/rectangular selection.

But.. thanks for the thumbs up and the other kind words.
