### ISSUE TITLE
Remove "Notepad++" from the about menu

### ISSUE THREAD

**Issue by gemal** [notepad-plus-plus/notepad-plus-plus#8391]
I think the about menu has a few too many mentions of Notepad++. When going to a about dialog I know that it's a about Notepad++, so I think the "Notepad++" should be removed.

![image](https://user-images.githubusercontent.com/69105/84115422-5a64e280-aa2e-11ea-959a-54cbf8560a1b.png)

So change:
- "Notepad++ Home" => "Homepage"
- "Notepad++ Project Page" => "Project Page"
- "About Notepad++" => "About"
etc...

**Comment by sasumner** [comment]
Sorry, won't be changed.
