### ISSUE TITLE
Find direction (only forwards, not backwards) is huge UX flaw.

### ISSUE THREAD

**Issue by josefsabl** [notepad-plus-plus/notepad-plus-plus#8392]
### Description of the Issue
The use case where user wants to find text occurences in only direction from the current position of carret is IMHO negligible compared to case where you want to find the string anywhere.

I was working on some document right now and was searching for some text and I had to click the "Backward direction" literally like 10 times. And I made few mistakes where I didn't realize I have the wrong direction and assumed the string is not present in the document.

This is User Experience hell!

### Steps to Reproduce the Issue
1. Ctrl+F
2. Type what you want to look for
3. Nothing is found although the string is present in the document.

### Expected Behavior
The search will reach the end of document and then starts from the beginning.

### Actual Behavior
The search stops at the end and tells me that the string was not found.

**Comment by ArkadiuszMichalski** [comment]
Check `Wrap around` in the Find window.
![image](https://user-images.githubusercontent.com/2730894/84156224-89e51080-aa69-11ea-9ef5-bd68f1aa0c28.png)
