### ISSUE TITLE
file with charset win1251 incorrectly autodetects as MAC

### ISSUE THREAD

**Issue by shredder2003** [notepad-plus-plus/notepad-plus-plus#8395]
### Description of the Issue

Very simple file with two sentences only without any special characters in win1251 codepage.
Notepad++ opens it as MAC codepage.
This issue has appeared few months ago.
Before it all was ok.

### Steps to Reproduce the Issue

1.  create file
2. set file codepage win1251
3. insert into file this content:
> сменить кодировку в конце файла install.sh для компиляции форм на ту, которая в 
> в файле проставить корректные наборы значений для КГП
4. save & close file
5. open file, you see it opens with MAC codepage, but really file in win1251

### Expected Behavior

Notepad++ have to open it with win1251 codepage

**Comment by Ekopalypse** [comment]
I assume you have Settings->Preferences->MISC.->Autodetect character encoding active.
If so, "untick" this option. 
Detecting an encoding 100% correctly cannot be achieved, especially when there is little amount of text an no "special chars" for that encoding are used.

**Comment by KnIfER** [comment]
Wow a new encryption method !  No need to install secure pad. lol.  

but what is MAC encoding? never see one.
