### ISSUE TITLE
Autocompletion interprets backslashes as escape sequences

### ISSUE THREAD

**Issue by git-afsantos** [notepad-plus-plus/notepad-plus-plus#8397]
### Description of the Issue

This happens to me a lot when writing LaTeX files. On Windows, I tend to use the Ctrl+Enter feature to autocomplete words. If the word has a `\r` or `\n` in it, it gets replaced with a carriage return or a line feed.
For instance, writing `Listing~\ref{fig:fig1}` and later on writing `List` to autocomplete, gets me `Listing~` on the current line, and `ef` on the next (new) line.

The issue happens when there is only a single choice for autocompletion and the choice box is not displayed. If it is selected from the choice box, it seems to work fine.
It happens with all sorts of escape characters, not just new line characters, e.g., `\a` gets replaced with a bell character.

### Steps to Reproduce the Issue

1. Open a new document.
2. Write `Listing~\ref`.
3. Somewhere else in the document (e.g., a new line), write `List`.
4. Press Ctrl+Enter (or the equivalent hotkey) to autocomplete.

### Expected Behavior

I expected the autocompletion to insert the text verbatim, not treating backslashes as escape sequences, e.g., `Listing~\ref`.

### Actual Behavior

Notepad++ treats backslashes as escape sequences, for instance replacing `\r` and `\n` in autocompletion with new line characters.

### Debug Information

Notepad++ v7.8.6   (64-bit)
Build time : Apr 21 2020 - 15:23:03
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS Name : Windows 7 Home Premium (64-bit) 
OS Build : 7601.0
Plugins : mimeTools.dll NppConverter.dll NppExport.dll 

### Screenshot

![Capture](https://user-images.githubusercontent.com/5166824/84244850-1d672180-aafc-11ea-9d14-eb24b37b1eb4.PNG)

**Comment by Ekopalypse** [comment]
Can confirm this happens with 7.8.7 as well.
Side note, when having enabled "autocompletion on each input" it does NOT happen if using
TAB or ENTER key to auto complete the word.

**Comment by donho** [comment]
I cannot reproduce it.
With `Listing~\ref` and `Something\new`, I can both on auto-completion.
Am I missing somethings?

**Comment by sasumner** [comment]
@donho 
Very reproducible on a fresh extract of 7.8.7 portable.
Following @git-afsantos 's steps # 1 to # 4 yields:
![image](https://user-images.githubusercontent.com/30118311/85317440-615b0e80-b48c-11ea-816d-5e999e9f12f3.png)
Not only a bad completion but a file with mismatching line-endings!

**Comment by donho** [comment]
@sasumner here my screenshot:
![image](https://user-images.githubusercontent.com/90293/85318441-4a361400-b4c0-11ea-8edb-13cc61107a79.png)

**Comment by Ekopalypse** [comment]
@donho, disable auto completion, then type _**so**_ and press CTRL+ENTER

**Comment by sasumner** [comment]
@donho My Preferences for this test are set the same as yours.
@Ekopalypse It manifests for me without disabling auto completion

@donho Are you missing the Ctrl+Enter step?

**Comment by Ekopalypse** [comment]
@sasumner, yes happens with auto completion enabled as well but as you wrote and OP, CTRL+ENTER is the crucial step.

**Comment by donho** [comment]
> @donho Are you missing the Ctrl+Enter step?

Yes. I didn't hit `Ctrl+Enter` for triggering auto-completion.
Now I can reproduce it. Thank you.

**Comment by sasumner** [comment]
Released in N++ version 7.8.8
