### ISSUE TITLE
7.8.7 new "Save As" feature **always** adds selected extension

### ISSUE THREAD

**Issue by vinsworldcom** [notepad-plus-plus/notepad-plus-plus#8398]
The new "Save As" feature of always adding the language extension (or default to "Normal text file (.txt)" to the "File name" in the "Save As" is great, but it may be too aggressive?  If I change the "File name" in the "Save As" to a different "unknown" extension (one not in the "Save As Type" list), the name in the "File name" should be saved, the "Save As Type" extension should **not** be added *back* onto the file when saved.

**Workaround**
When saving a file type that does not have an extension in the "Save As Type" box of the "Save As" dialogue, one has to manually either:

- select "All types (*.*)" in the "Save As Type" drop down

or 

- put the "File name" text in double quotes

in order for the "File name" with non-available extension to be saved as filename.non-available-ext.

**Description of the Issue**
Open a new file in Notepad++ and type some text.  File=>Save As..., the "File name" in the "Save As" dialogue shows as "new 1.txt" and the "Save As Type" is "Normal text file (.txt)".  Rename in the "File name" text box of the "Save As" dialogue to "mygedcomfile.ged" and press "Save" button.  File is saved as "mygedcomfile.ged.txt".  It should be "mygedcomfile.ged" without the additional ".txt" extension.

**Steps to Reproduce the Issue**
1. Open a new file in Notepad++ and type some text. 
2. File=>Save As...
3. Change the "File name" in the "Save As" dialogue to "mygedcomfile.ged"
4. Press "Save" button
5. File is actually saved as "mygedcomfile.ged.txt"

**Expected Behavior**
File is save only as "mygedcomfile.ged"

**Actual Behavior**
File is actually save as "mygedcomfile.ged.txt"

Notepad++ v7.8.7   (64-bit)
Build time : Jun  5 2020 - 02:38:56
Path : C:\usr\bin\npp64\notepad++.exe
Admin mode : OFF
Local Conf mode : ON
OS Name : Windows 10 Enterprise (64-bit) 
OS Version : 1809
OS Build : 17763.1217
Current ANSI codepage : 1252
Plugins : AnalysePlugin.dll AutoSave.dll BetterMultiSelection.dll ChangedLines.dll CodeAlignmentNpp.dll ColumnTools.dll ComparePlugin.dll CsvQuery.dll CustomizeToolbar.dll DoxyIt.dll DSpellCheck.dll Explorer.dll GitSCM.dll JSMinNPP.dll NppConsole.dll NppConverter.dll NppEventExec.dll NppExec.dll NppExport.dll NppFTP.dll NppMarkdownPanel.dll NppMenuSearch.dll Python Indent.dll QuickText.dll SpeechPlugin.dll SurroundSelection.dll TagLEET.dll XMLTools.dll ZoomDisabler.dll

**Comment by sasumner** [comment]
@Uhf7 As the change that brought about this situation was yours (of course, no "blame" is meant; overall this is a great change which will end the # 1 most-asked FAQ about N++), what do you think about it?  

Do you think @Ekopalypse 's suggestion of "check for a file extension" added as additional logic would help ease the situation?

**Comment by donho** [comment]
> Maybe the easiest would be to [check for a file extension](https://docs.microsoft.com/en-us/windows/win32/api/shlwapi/nf-shlwapi-pathfindextensionw)?

It's not that simple.
In the old style save dialog, it was easier to implement a "hooked" function to do all such hack. But in the new style one there's no easy way to change MS modern dialog default behaviour.
So to solve this "problem", I don't see other solution except removing the new adding file ext feature (which is needed by a lot of users AFAIK).
 
@Uhf7 have you any idea (no COM OBJECT solution please) about it ?

**Comment by Uhf7** [comment]
Personally, I agree with @vinsworldcom. It's a Windows dialog box, featuring Windows behavior. Peter Jones described it already, and the Windows Notepad behaves the same way.

There are different ways to go here. Some of them are:
- We could accept the Windows behavior and those, who cannot live with it, can use the old style file dialog box
- We could restore the old behavior of **Save As** for editor files, then no extension would be added automatically in the new style save dialogue. This can be done without impact to the extension added automatically to Session and Workspace files.
- We could set the `*.*` filter as default, which is in the end as good as restoring the old behavior.
- We could try to override the Windows behavior by detecting the file extensions outside the `GetSaveFileName` function, but we have suffer some consequences.

Overriding the Windows behavior of the `GetSaveFileName` dialogue includes the following:
- Tell `GetSaveFileName` not to append any extension.
- Tell `GetSaveFileName` not to confirm overwriting of an existing file.
- Then, after `GetSaveFileName` returns, we can check, if the user provided an extension. If not, we check which extension was selected in the _File extensions_ selection box (it is in the `_ofn` structure after the  `GetSaveFileName` call), and if an extension is selected, then we append this extension.
- Then, we check if the file already exists and mimic the **Confirm Save As** message box, if necessary. If the user says **No** (don't overwrite), we have to call `GetSaveFileName` again.

PRO's
- As long as there is no overwrite confirmation, it works as smooth as the original.
- We can use unregistered file extensions.

CON's
- No "integrated" overwrite confirmation, the **Save As** dialogue box closes before confirmation and re-opens after, keeping the _File name_,  the selected entry in the _File extensions_ selection box and the current directory in the right area of the new style dialogue, but loosing its browsing position in the left area.
- The confirmation box can look quite exactly as the original, but the text language  localization is now done by Npp and not by Windows.

The new loop around `::GetSaveFileName` in `FileDialog::doSaveDlg()` would look like this:

		while(TRUE)
		{
			fn = ::GetSaveFileName(&_ofn) ? _fileName : NULL;
			if (!fn)
				break;
			_fn = fn;
			TCHAR * pExt = PathFindExtension(_fileName);
			if ((*pExt == 0) && (_ofn.nFilterIndex > 1))
				_fn += getExtFromFilter(_ofn);
			HANDLE H = CreateFile (_fn.c_str(), GENERIC_READ, 0, NULL, OPEN_EXISTING, 0, NULL);
			if (H == INVALID_HANDLE_VALUE)
				break;
			CloseHandle(H);
			TCHAR Msg [512];
			wsprintf(Msg, L"%s already exists.\nDo you want to replace it?", PathFindFileName(_fn.c_str()));
			int result = MessageBox(_ofn.hwndOwner, Msg, L"Save As Confirmation", MB_YESNO | MB_ICONWARNING);
			if (result == IDYES)
				break;
		}

Imagine additional 35 lines for `getExtFromFilter` and some text localization stuff, that's it. Tested it briefly, it works as good (or bad) as described. If you want to try this way, I can provide it as PR.

**Comment by sasumner** [comment]
Probably best to leave it alone for now.  :-)

**Comment by vinsworldcom** [comment]
Can you set "All files (*.*)" as default **_ONLY IF_** the current file buffer is a "new #" - as in a new document not yet saved - it has no "path"?  Horrible pseudo-code follows:

```
if ( NOT currentFIlePathExists() )
{
    // it must be a "new #" buffer with no file name so
    // default type is "Normal text file", so let's "override" that
    setSaveAsType( "*.*" );
}
else
{
    // keep current new and improved 7.8.7 behavior
}
```

I hope that makes sense?

Cheers.

**Comment by Big--Mike** [comment]
I like the old behavior, but I understand, that there's also a need to add a default extension for some users. So could you add an option to setup the default extension?

- Users needing a default extension are good with a default of "*.txt"
- Users like me could set it to "*.*" and get the old behavior back.
- Users which use Notepad to create typically files with another extension may want to set it to "*.java" for example

I guess anything trying to detect the file extension leads to unexpected behavior in some situations, as any filename containing a dot has (technically) a file extension, but not any dot in a filename is meant as file extension. For example: "Daily Report 11.06.2020" has technically the file extension "2020".

**Comment by sasumner** [comment]
My natural instinct on creating a new file (say it is going to be a `.cpp` file) is _not_ to "waste time" selecting a choice from a _Save as type_ dropdown, but rather to type `*.cpp` in the _File name_ box and press Enter.  This is a very fast method to see which current `.cpp` files I have so I don't reuse a name.  In 7.8.6 and earlier, with the "new style" open/save, this works fine.

However, in 7.8.7 when I type `*.cpp` in the _File name_ box and press Enter, I get this, which is unexpected and unhelpful:

![image](https://user-images.githubusercontent.com/30118311/84398377-dcd7d880-abcd-11ea-9c5a-c1a7acc118fe.png)

**Comment by Uhf7** [comment]
@sasumner, I cannot reproduce it with the new style **Save As** dialog on my system (original 7.8.7 version), but with the old style **Save As** dialog. And with the old style dialog, this effect happens with 7.8.5 too, so I believe, this is an older problem. The old style dialog simply ends with wildcard file names, and `MainFileManager.saveBuffer` cannot save `*.cpp`.

**Comment by sasumner** [comment]
@Uhf7 Ach, my bad.  I'm a victim of "too much experimentation".  I _did_ have it set to "old style".  Sorry for the noise.

**Comment by Uhf7** [comment]
@vinsworldcom, @Big--Mike These are two "sub ways" of setting the default extension to `*.*` conditionally, both seem possible. 

The "Daily Report 11.06.2020" is a great example for the Windows natural solution to allow registered file extensions only. But I think, everyone working with such file names has to fight with .2020 as file extension here or there, and this should be within the expectations when using such file names.

Regarding users want to set their file name to .java: On my system, .java is a registered file extension, and one could argue, that users, who work with such files, have the file extension registered too.

The actual problem are the unregistered file extensions. In so far, the title of this issue is wrong. It's not _always_, it's if the extension is entered is not a registered extension and a file type other than `*.*` is selected.

**Comment by Big--Mike** [comment]
@uhf7:
- I guess, not anyone working with this kind of file names, is aware of the problem. I guess, Microsoft is doing it's best to promote this unawareness by hiding known file extensions by default. You have "Daily Report 11.06.2020" and "Daily Report 11.06.2020.txt" and maybe "Daily Report 11.06.2020.pdf" in the same directory. All three display "Daily Report 11.06.2020" with the default Windows settings, just the icons differ.
- With the Java example I meant, people could change the default from "*.txt" to "*.java". So saving a file in Notepad++ named "Example" would create "Example.java" instead of "Example.txt" (But you're probably right, this kind of people would directly type "Example.java" and be fine...)

**Comment by donho** [comment]
Just checked the behaviour of Notepad.exe, it's the same behaviour as the current one of save file dialog in Notepad++. So let's keep it as it is.

**Comment by sasumner** [comment]
@Uhf7 said:

>Personally, I agree with @vinsworldcom. It's a Windows dialog box, featuring Windows behavior. Peter Jones described it already, and the Windows Notepad behaves the same way.

Yes, but I am somewhat reconsidering my position on this. :-)
Obviously Notepad++ tries to do things better than Windows Notepad, so perhaps we could deviate from the Windows norm to create a better solution for users?

**Comment by Uhf7** [comment]
OK, I looked into it again. The choices we have I already stated above: https://github.com/notepad-plus-plus/notepad-plus-plus/issues/8398#issuecomment-642639813. After this, I created PR #8404, to show, how overriding Windows behavior would look like. PR #8404 has not been integrated for two reasons:
- Notepad++ behaves like MS Notepad, which is Windows conform, so why change something.
- The PR #8404 dialog box could not respond to modifications in the file types (filter) drop down box.

I voted myself not to integrate it, mainly for reason one and for too much code.

So, as long as no one decides to choose another of the alternatives I suggested in my previous comment (or suggests a new alternative), this looks like the end of the road for me here.

What I just tested out, is to use the new `IFileSaveDialog` recommended by Windows. Using this, PR #8404 could be made responding to modifications in the file types (filter) drop down box. 

PRO's:
- No new behavior, the current `GetSaveFileName` Windows function is probably only a wrapper around the `IFileSaveDialog` anyway.
- It is detectable, which content the edit box with the file name had, when the user clicked _Save_.

CON's:
- _WIN32_WINNT=0x0600 necessary (say goodbye to Windows XP, welcome to Windows Vista),
- Hard (but possible) still to support the 'old style' dialog,
- The overwrite safety message box must still be programmed in Notepad++, exactly like in PR #8404,
- Even more code.

**Comment by dodmi** [comment]
I'm using Notepad++ as a complete Notepad replacement, because it does not behave like MS Notepad ;-)
Actually, I vote for "Add an option to let the user decide, which should be the default save extension (including *.*)".
So users liking the old behavior could select "*.*" to restore it and users liking the new behavior could select their preferred extension (*.txt, *.java, *.ps1...)

**Comment by sasumner** [comment]
@Uhf7 said:

>this looks like the end of the road for me here.

So be it. :-)

**Comment by Uhf7** [comment]
@sasumner,

What @dodmi suggests here seems to me to be a practicable solution over all. Both positions satisfied with relatively low coding effort. We would need a new option of course. Seen a new page in settings recently, there is much empty space in it? :-)

**Comment by sasumner** [comment]
@Uhf7 

If a new Preference setting is required, then so be it.  I don't like the idea of a setting; the last time a setting relating to the _Save_ box was introduced, it caused hundreds (that's a reasonable estimate) of tech support questions.  I'm talking about the _Use new style Save dialog..._ setting, of course.  Soooo annoying from a support standpoint.

It's kind of ironic, when you first introduced this new behavior, the thinking was that all the new-style/old-style controversy was going to go away, and old-style would just fade away.  Little was it known that a new controversy would erupt.  Such is the way with change, I suppose. :-)

**Comment by vinsworldcom** [comment]
How about just allowing default UDL as an option in the Default Language
type combo box in the existing preferences setting?  Manually selecting UDL
as the language type and then saving auto selects *.* File type in the Save
As dialogue - this would just automate that selection as an option.

**Comment by vinsworldcom** [comment]
My last comment was from my mobile without access to a nice desktop to switch windows and find this link.  See the following [discussion at the Notepad++ Community](https://community.notepad-plus-plus.org/topic/19790/how-can-you-make-all-types-the-default-when-saving/5) for a better explanation of what I'm proposing.

Not a new setting, just adding the default "User Defined" language to the pull down:

![image](https://user-images.githubusercontent.com/9657169/89908230-9eee3500-dbbb-11ea-9cd5-9d1850da73aa.png)

Not that when a new document "new 1" is opened and the Language is manually set to "User Defined" and then one does a "Save As...", the "Save as type" is set to "All types (`*.`*)".  This would allow a user to set the default type to `*.*` if they wish and by proxy, the `*.*` type allows saving of unknown file types with whatever extension you want _without_ adding the ".txt" extension as it happens now (since "Normal Text" is the Default language type).

Cheers.

**Comment by Uhf7** [comment]
I did a little experimenting about what would happen if the _User Defined Language_ would be allowed in Settings. It is correct, that the first _Save As_ operation of a new file then defaults to `*.*` as selection in the file type list, and that I can save the new file now as `New 1.abcdef`. After this _Save As_ operation, Notepad++ tries to detect a language, and defaults to _Normal text_ for the following reasons:
- `.abcdef` is no known file extension
- the file content does not start with `#!sh` or `<?xml` or something else recognizable by examining the 1st line.
- the _User Defined Language_ has not been selected from the menu by the user to this time, it simply came as default.

If we would go this way, then I think, the language detection after _Save As_ would have be made more tolerant too, like don't changing the language if there is nothing to detect (no known ending and no content in the buffer). And, after the user has selected a language for the buffer, the default selection in the file type list still defaults to the corresponding file type.

In the moment, I see only two ways
- A new option, letting the user set the `*.*` filter in the file type list as default instead of the language specific filter
- Use the new `IFileSaveDialog` recommended by Windows.

The _User Defined Langue_ way seems to have too many side effects.
