### ISSUE TITLE
Current occurrence number when pressing Find Next

### ISSUE THREAD

**Issue by emilh91** [notepad-plus-plus/notepad-plus-plus#84]
When I search for text in a file, in the Find dialog I usually do a Count first to see how many occurrences I am working with. I revise my regex to narrow down my search if necessary. I find the Count feature very helpful.

It would be helpful to know what occurrence number is highlighted currently when looking for text when pressing Find Next (e.g. occurrence 23 of 30).

**Comment by donho** [comment]
It will need not only a lot of coding effort but also a lot of effort to maintain this feature since it'll be make more complex in the current code. Therefore this feature won't be implemented. Hope you understand.
