### ISSUE TITLE
Browse for Folder window cannot be resized

### ISSUE THREAD

**Issue by squalou** [notepad-plus-plus/notepad-plus-plus#840]
Hi,

this is a very minor UX issue.

Some dialog boxes/windows should be resizable, but are not.
Especially when trying to deal with operations like 'search & replace" in directories, browsing the whole tree in a small window is tedious.

Using : windows7 version, wityh latest np++ as of today.

"Find in Files" window itself displays the 'resize' widget, but resize do not work

"Directory" option can be filled by clicking on the 'three dots' button, that opens a "browse for folder" window whose size is fixed. (maybe it's related to windows itself unfortunately)

cheers, and thanks for the work !

**Comment by h-h-h-h** [comment]
> "Find in Files" window itself displays the 'resize' widget, but resize do not work

See also issue https://github.com/notepad-plus-plus/notepad-plus-plus/issues/774.

> "Directory" option can be filled by clicking on the 'three dots' button, that opens a "browse for folder" window whose size is fixed. (maybe it's related to windows itself unfortunately)

It's good to have such a window resizable. Further, there should be a textbox to paste a directory path as in other software, even though you can paste the *final* directory in the find-and-replace dialog directly. This is because you might want to start to browse from the pasted directory for another directory.

**Comment by dg9ngf** [comment]
The browse for folder dialog is actually a pretty ancient one. Windows Vista introduced new file dialogs that are much easier to use. They can also be used to select folders now, replacing that ugly and unfriendly folder browse dialog from the older days. NPP already makes use of the latest file dialog version in open/save, so it should also do so in the find dialog.

**Comment by dail8859** [comment]
Closed by b3be0b448bc883f61b8e6d0fb190b1dd8c4e139f

**Comment by ajr360** [comment]
The Windows BrowseForFolder dialog was an abomination from its inception.  Attempts have been made to improve it over the years but a better solution has always been to adapt the open file dialog to allow you to select a folder.
