### ISSUE TITLE
Rectangular selection does not move when inserting new chars.

### ISSUE THREAD

**Issue by Ekopalypse** [notepad-plus-plus/notepad-plus-plus#8400]
### Description of the Issue

When creating a rectangular selection and adding new chars the selection does
not move to its new positions

### Steps to Reproduce the Issue
1. Create a few lines
2. Put the cursor to column 0 and create a rectangular selection
3. press tab key

### Expected Behavior
The rectangular selection has been placed after the inserted tab characters

### Actual Behavior
The rectangular selection is before the inserted tab characters

### Debug Information
Notepad++ v7.8.7   (64-bit)
Build time : Jun  5 2020 - 02:38:56
Path : D:\...\notepad++.exe
Admin mode : OFF
Local Conf mode : ON
OS Name : Windows 7 Professional (64-bit) 
OS Build : 7601.24544
Current ANSI codepage : 1252
Plugins : mimeTools.dll NppConverter.dll NppExport.dll 

Example 
npp 7.8.7:
![image](https://user-images.githubusercontent.com/47723516/84299892-c9872780-ab51-11ea-850c-0adc1891876a.png)

npp 7.8.6:
![image](https://user-images.githubusercontent.com/47723516/84299832-ad838600-ab51-11ea-98d4-9a4365c395fc.png)

**Comment by Uhf7** [comment]
What happens here: Scintilla doesn't like `SCI_INDICSETSTYLE` or `SCI_INDICSETHOVERSTYLE` commands while editing. Whenever such a command occurs, it calls a kind of internal reset/redraw function, which wrecks the cursor position of block selection.

There is nothing in their documentation saying don't change indicator styles while rectangular selection is active, so nobody saw it coming. 

It occurs in other situations too, for example, when changing zoom while the rectangular selection is active, but that is far less disturbing.

Fortunately, there is an easy way to fix it, I will create a PR showing this way.

**Comment by sasumner** [comment]
@Uhf7 Is it worth putting a bug report in on the Scintilla site?  If so I will ask you to please do it.

**Comment by Uhf7** [comment]
Actually, I don't know if they would see it as a bug. They could see it as "normal" behavior, which is not described in the `ScintillaDoc.html`.

And it's hard to file an example of the effect, which they can reproduce, but I think about it.

**Comment by donho** [comment]
@Uhf7  There was an Windows update waiting - after updating and restarting my laptop, the PR is working. Thank you for the fix.
