### ISSUE TITLE
Set tab-width to 4 for Find-result window output

### ISSUE THREAD

**Issue by sasumner** [notepad-plus-plus/notepad-plus-plus#8406]
### Description of the Issue

The `Line` lines in the _Find result_ window are led off with a tab character.  The display width of this tab character follows the tab width _Preference_ setting for _normal_ for the editor views, but, oddly, not the user preference for _Replace by space_.  Example (with visible whitespace turned on, via Pythonscript plugin):

![image](https://user-images.githubusercontent.com/30118311/84452150-fe16e400-ac22-11ea-841e-be4d8f61a2b6.png)

I propose hard-setting this tab character in the output to have a width of 4.  This will form a nice balance/symmetry with the filename line just above the `Line` lines, which is led off with two space characters, and will end the variability based upon user preference for the editor views.

### Debug Information
Notepad++ v7.8.7   (32-bit)
Build time : Jun  5 2020 - 02:34:28
Path : C:\............\npp.7.8.7.bin\notepad++.exe
Admin mode : OFF
Local Conf mode : ON
OS Name : Windows 10 Enterprise (64-bit) 
OS Version : 1809
OS Build : 17763.1039
Current ANSI codepage : 1252
Plugins : mimeTools.dll NppConverter.dll NppExport.dll 

Here's an extreme example, just for fun?:

![image](https://user-images.githubusercontent.com/30118311/84451855-3538c580-ac22-11ea-8d3f-2cde7cd63cca.png)

![image](https://user-images.githubusercontent.com/30118311/84451866-3bc73d00-ac22-11ea-975e-a865348e5408.png)

**Comment by sasumner** [comment]
It appears that the tab character before `Line ` in the output is important to the lexer. :-(

**Comment by xylographe** [comment]
A real bummer. :-(

**Comment by sasumner** [comment]
@xylographe Well, I'm not quite giving up yet. :-)

**Comment by xylographe** [comment]
Perhaps, ignore the tab width _Preference_, and choose a constant value instead?
A fixed tab width of 4 would seem reasonable?

**Comment by sasumner** [comment]
Edited the title of the issue, and the initial issue comment to reflect a slightly different direction since originally composed.
