### ISSUE TITLE
[Feature] Shortcut Keys on Save popup

### ISSUE THREAD

**Issue by LukeHartcher** [notepad-plus-plus/notepad-plus-plus#8407]
### Description of the Issue
Feature Request to add Shortcut Keys to the Save popup.
For example I press Ctrl+W to close a file, with keyboard, but then I need to Tab or grab mouse to select the appropriate button.
A shortcut key would make this much simpler (and is a common standard)

### Steps to Reproduce the Issue
Press Ctrl+W (to close a document)

### Expected Behavior
Be able to press a letter shortcut key to continue 
e.g. 'Y' for Yes and 'N' for No, 'C' for Cancel etc

### Actual Behavior
I need to TAB and ENTER or use MOUSE/CLICK

![image](https://user-images.githubusercontent.com/1154551/84465299-066e2e00-acba-11ea-8c0c-8c0a739d330f.png)

**Comment by sasumner** [comment]
This is an invalid issue as you ignored the instructions in the issue template for supplying your _Debug Information_.

If you _had_ supplied the proper information, you'd probably be told that this is supported in current (7.8.7) software; note the underlined characters in this screenshot:

![image](https://user-images.githubusercontent.com/30118311/84499854-64caea80-ac81-11ea-948f-9f70679c0a75.png)
