### ISSUE TITLE
The file cannot be saved if the name is the same as the subdirectory

### ISSUE THREAD

**Issue by RafaelXI** [notepad-plus-plus/notepad-plus-plus#8408]
### Description of the Issue
The file cannot be saved if the name is the same as the subdirectory which is also in the save directory.

### Steps to Reproduce the Issue

1.  I create the "ABC" subdirectory in the "Test" directory
2.  In Notepad++, New (file)
3.  Save, I enter the file name: ABC. Save directory: Test
4. Warning! "The ABC file already exists. Do you want to replace it?"

### Expected Behavior
The file should save under the same name as the subdirectory.

### Debug Information
Notepad++ v7.8.7   (32-bit)
Build time : Jun  5 2020 - 02:34:28
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS Name : Windows 10 Enterprise (64-bit) 
OS Version : 1803
OS Build : 17134.472
Current ANSI codepage : 1250
Plugins : DSpellCheck.dll mimeTools.dll NppConverter.dll NppExport.dll XMLTools.dll

**Comment by sasumner** [comment]
Only happens with "old style" dialog, which is becoming deprecated.  Switch to "new style" by ticking this setting in the _Preferences_:

![image](https://user-images.githubusercontent.com/30118311/84500436-89739200-ac82-11ea-8b1c-7bb0a9e4e2dd.png)

**Comment by RafaelXI** [comment]
I checked the "Use new style dialog" option but that didn't solve the problem. Now, after entering a file name such as directory names, this directory opens. This should not happen. The file should be saved.

**Comment by sasumner** [comment]
@RafaelXI Try it in Windows' notepad.exe or wordpad.exe or any of a number of other programs.  It is just how Windows savings works.

**Comment by RafaelXI** [comment]
Yes it's true. I don't know why I didn't notice it before. Thx.
