### ISSUE TITLE
PHP Language missing functions

### ISSUE THREAD

**Issue by bedak** [notepad-plus-plus/notepad-plus-plus#8410]
### Description of the Issue
Function `array_key_first()` not recognized (not in php.xml ...)
and probably other new PHP-functions(?)

### Context
Notepad++: v7.8.7 (64-bit), Win 10, english, german,...
PHP: 7.4+

**Comment by ArkadiuszMichalski** [comment]
@bedak Would be nice if you listed all missing function.
[array_key_first()](https://www.php.net/manual/en/function.array-key-first.php)

**Comment by CmsWares** [comment]
Just for reference, I'm compiling a complete modern list to replace the outdated definitions. The current manual has been mostly scraped. Some decisions to be made on what all to include, with more detail discussed here: https://community.notepad-plus-plus.org/topic/22418/updating-autocomplete-definitions-best-practices/
