### ISSUE TITLE
7.8.7: Two regressions in URL behavior 

### ISSUE THREAD

**Issue by Yaron10** [notepad-plus-plus/notepad-plus-plus#8412]
**STR:**
Paste a link in a C++ file.

**Result:**
The part of the URL after `//` is interpreted and highlighted as Comment.

![תמונה](https://user-images.githubusercontent.com/10229320/84583220-0d528900-adff-11ea-8da3-f29f543edc69.png)
***
**STR:**
Hover over a URL and slowly move from left to right.

**Result:**
The "edit" cursor is shown (intensively flickering) along with the "hand" cursor.
***
**Debug Information:**

Notepad++ v7.8.7   (32-bit)
Build time : Jun  5 2020 - 02:34:28
Path : C:\Users\---\Downloads\npp.7.8.7.bin.minimalist\notepad++.exe
Admin mode : ON
Local Conf mode : ON
OS Name : Windows 7 Enterprise (32-bit) 
OS Build : 7601.23964
Current ANSI codepage : 1255
Plugins : none

**Comment by donho** [comment]
> The part of the URL after // is interpreted and highlighted as Comment.

In a c++ (or in other languages) file, an url is in quotes as string or in a comment, otherwise it's just meaningless. 

> The "edit" cursor is shown (intensively flickering) along with the "hand" cursor.

It's a glitch indeed. But the gain of the current implementation makes such glitch bearable.
