### ISSUE TITLE
[Feature Request] Regex Substitutions using Named Capturing Group

### ISSUE THREAD

**Issue by aradani3** [notepad-plus-plus/notepad-plus-plus#8417]
As a Notepadd++ user, I want to be able to combine Notepad++ find and replace using Regex capability with Regex's Named Capturing Group capability

Today the find and replace capability supports regular expression. 
However, if the regular expression contains a Named Capturing Group [f.e. (?<name>...)], you cannot use the groups that were captured by the Regex in the Replace section [f.e. ${name}] 

[https://regex101.com/r/MBiIMu/1](url)

Example:
```
<div class="category_name">Castle</div>
<div class="category_name">Pool</div>
<div class="category_name">House</div>
```
Find what: ```<div class="category_name">(?<name>.*)/div>```
Replace with: ```${name}```

Actual Result:
${name}
${name}
${name}

Expected result:
Castle
Pool
House

**Comment by sasumner** [comment]
>Replace with: ${name}

The proper _Replace with_ syntax for your example is: `$+{name}`

Be careful when using regex101.  It's a useful tool, but Notepad++ uses a different regular expression engine than it does.

**Comment by xylographe** [comment]
The _Boost_ regular expression syntax is documented [here](https://www.boost.org/doc/libs/1_70_0/libs/regex/doc/html/boost_regex/syntax/perl_syntax.html) and [here](https://www.boost.org/doc/libs/1_70_0/libs/regex/doc/html/boost_regex/format/perl_format.html).
