### ISSUE TITLE
Regression at 7.8.3: Command line option -n shows the top of the file if the file is not already open

### ISSUE THREAD

**Issue by mrdiskodave** [notepad-plus-plus/notepad-plus-plus#8418]
### Description of the Issue

Starting at 7.8.3 '-n<linenumber>' shows the top of the file if the file is not already open.
If you press cursor-down or something then the screen will then scroll to the line number
so it has done the right thing ... just except for the scrolling.

### Expected Behavior

1.  Close all the files so notepad++ is sitting empty.
2.  Run notepad++ from cmd.exe with line number and a filename.
(it will need to be a long file and a big line number so that the screen would have to scroll).
3. You see the file open and the cursor is placed on the specified line and the line is scrolled into view.

### Actual Behavior

1.  Close all the files so notepad++ is sitting empty.
2.  Run notepad++ from cmd.exe with line number and a filename.
3.  You see the file open but you cannot see the cursor is placed on the specified line and because the line is not scrolled into view. 
4. Repeat step 2. (now that the file is open)
5. Now the screen scrolls.

### Debug Information

Notepad++ v7.8.4   (64-bit)
Build time : Jan 29 2020 - 01:31:03
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS Name : Windows 10 Enterprise (64-bit) 
OS Version : 1803
OS Build : 17134.1550
Plugins : mimeTools.dll NppConverter.dll NppExport.dll

**Comment by sasumner** [comment]
What's your word-wrap setting?
Reference #8007

**Comment by mrdiskodave** [comment]
Yes, this is a duplicate of #8007 
Turning off word-wrap is a work around.
