### ISSUE TITLE
Improve three small focus issues

### ISSUE THREAD

**Issue by Uhf7** [notepad-plus-plus/notepad-plus-plus#8419]
This is a continuation of #8369 and #8370, brought up by @Yaron10 in #8370.

Two improvements were requested:
- Focus goes not back to edit window if Function List has focus and and the Function list is closed by the menu command **View -> Function List**.
- Focus goes not back to edit window if **Folder as Workspace** has focus and and the **Folder as Workspace** is closed by the menu command **View->Folder as Workspace**.

The third would be:
- Switch focus to edit window after loading a Workspace file from command line.

**Comment by donho** [comment]
@Uhf7 Could you describe the bug(s) and  how to reproduce it (them)?

**Comment by Uhf7** [comment]
To reproduce one and two, you have to open a **Function List** window or a **Folder as Workspace** window in a way, that they are the a single docked window, not sharing the space with any other docking window, which means, with no tabs at the bottom. This can be achieved by closing all docked windows at the start of the experiment.

Then, open **Function List** and make sure, it has the keyboard focus. Now, use the mouse to execute the menu command **View -> Function List**. This command closes the function list and leaves Npp in a state in which keyboard inputs going to nowhere.

Since I debugged it again while writing this, I have an even better solution and I will revise PR #8420 soon.

The third one is easier. Open Npp with a valid workspace file name as command line parameter (workspace file extension specified in Preferences), and it shows the correct workspace with the keyboard focus in the Project panel. It would be much better, if the keyboard focus would be in the edit window.
