### ISSUE TITLE
Javascript template literal string syntax highlighting is not escaped when using a backslash.

### ISSUE THREAD

**Issue by 99banana** [notepad-plus-plus/notepad-plus-plus#8421]
### Description of the Issue
In javascript files, template literal strings (with the "\`" character) are not escaped when typing "\\`"

### Expected Behavior
Template strings and backticks should be escaped with backslash "\\"
If possible, it would also be nice if code in between ${ and } would be highlighted as code.

### Actual Behavior
![image](https://user-images.githubusercontent.com/51007423/84822187-49960d00-afea-11ea-9eb1-d912ec169f22.png)

### Debug Information
Notepad++ v7.8.7   (32-bit)
Build time : Jun  5 2020 - 02:34:28
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS Name : Windows 10 Enterprise (64-bit)
OS Version : 1909
OS Build : 18363.900
Current ANSI codepage : 1252
Plugins : ComparePlugin.dll JSLintNpp.dll Linter.dll mimeTools.dll NppConverter.dll NppExport.dll

**Comment by donho** [comment]
https://github.com/notepad-plus-plus/notepad-plus-plus/issues/3822#issuecomment-697275450
