### ISSUE TITLE
[Feature Request] Add an option to NOT remember current session if I saved it

### ISSUE THREAD

**Issue by Cyberavater** [notepad-plus-plus/notepad-plus-plus#8423]
Remembering the current session for the next launch is pretty handy but there is no use for it if I already saved the file. So, there should be an option so that it doesn't remember the session if it's saved.

**Comment by sasumner** [comment]
Sorry; won't be implemented.

**Comment by Cyberavater** [comment]
> Sorry; won't be implemented.

Well, at least say why, so I can better understand your policies before requesting any more feature issues.
