### ISSUE TITLE
Always move focus to editor on opening a new file 

### ISSUE THREAD

**Issue by Yaron10** [notepad-plus-plus/notepad-plus-plus#8426]
**STR:**
Give keyboard focus to the Incremental Search Bar (or any other "not-editor" element).
Open a new file via `File -> New File`.

**Result:**
The editor does not get the focus.

**Expected Result:** 
The editor should get the focus as is the case on opening a recently closed file.

**Comment by Uhf7** [comment]
Interesting, but I cannot include it in #8420. "Three at One Blow" must be enough here, I don't extent it to seven, I'm no tailor.

**Comment by Yaron10** [comment]
Not a tailor but certainly little.
