### ISSUE TITLE
Html file content is hidden while doing undo redo.

### ISSUE THREAD

**Issue by GirishNama** [notepad-plus-plus/notepad-plus-plus#8430]
### Description of the Issue
I was working on an html file. I did some undo and redo to get the required content stage. I saved the file and refresh  the browser to see the updates. browser was displaying the code that was not visible in my html file. then I copy some part of the content from the browser and searched in notepad file , Search dialog box displayed the message that content found at some position and scrolled to that position. but the content was not there. Then I copied the whole html file content from the notepad ++ and pasted into MS Notepad. I found the missing content.
### Steps to Reproduce the Issue

1. do undo and redu more then 7-8 times save the file and refresh the browser to see the updated page.
2. 
3. 

### Expected Behavior
Notepad should display all the content according to undo and redo in my html file.

### Actual Behavior
Notepad ++ was hiding my some part of my content.

### Debug Information  
Notepad++ v7.8.7   (32-bit)
Build time : Jun  5 2020 - 02:34:28
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS Name : Windows 8.1 Enterprise (64-bit) 
OS Build : 9600.0
Current ANSI codepage : 1252
Plugins : DSpellCheck.dll mimeTools.dll NppConverter.dll NppExport.dll SpellChecker.dll

**Comment by ArkadiuszMichalski** [comment]
@GirishNama Can you add some example code (file) to reproduce this? What browser are you using?

**Comment by donho** [comment]
No reply... this bug will be closed until there's a reply.
