### ISSUE TITLE
Remove the "Replace All in All Opened Documents" 'feature'

### ISSUE THREAD

**Issue by Gewath** [notepad-plus-plus/notepad-plus-plus#8432]
### Description of the Issue
Problem: accidentally clicking "Replace All in All Opened Documents" ruins potentially all your text files, causing you to have to go through potentially hundreds of thousands of open text files and fix them one by one, and ruins them all permanently if you've closed Notepad++ in-between (#2855 #5253 #5260).

Previous topics on this feature were closed because "you can just fix them by going through them one by one, and clicking undo". This is akin to saying "you can just replace all in all opened documents, by going through them one by one and clicking replace all".

As the function is now admitted to be completely pointless, remove it entirely, it clutters the "replace" tool in Notepad++.

### Steps to Reproduce the Issue
1. Open every file you've ever edited in Notepad++.
2. Delete original save files, keep files in editor. (This is how most people use Notepad++)
3. Ctrl+F.
4. Replace.
5. Check tickbox 'regular expression'.
6. Find what: [A-Za-z0-9]
7. Replace with: I shall not add one-click global file corrupting buttons to my program.
8. Hover mouse over 'replace all'.
9. Move mouse 1cm down.
10. Left click.
11. Close Notepad++.

![notepad++ replace all in all](https://user-images.githubusercontent.com/27696856/85042820-f360cf80-b18b-11ea-9772-60754ed8605d.png)

### Debug Information
Notepad++ v7.8.5   (32-bit)
Build time : Mar  4 2020 - 11:04:20
Path : E:\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : ON
OS Name : Windows 10 Home (64-bit) 

OS Version : 1703
OS Build : 15063.674
Plugins : mimeTools.dll NppConverter.dll NppExport.dll 

Screenshot has been modified.

**Comment by sasumner** [comment]
Here's a nice little Pythonscript to remove the feature.  
Move the key-binding of Ctrl+h from the default over to running this script.  
Note that the _Replace All in All Opened Documents_ button is now gone!:

![image](https://user-images.githubusercontent.com/30118311/85062664-de2d7600-b176-11ea-859b-b9675072353f.png)

The script:
```
# -*- coding: utf-8 -*-

from Npp import editor, notepad, MENUCOMMAND
import ctypes
from ctypes.wintypes import BOOL, HWND, LPARAM

try:

    REPLACE_DIALOG().show()

except NameError:

    class REPLACE_DIALOG_SINGLETON(type):
        _instance = None
        def __call__(cls, *args, **kwargs):
            if cls._instance is None:
                cls._instance = super(REPLACE_DIALOG_SINGLETON, cls).__call__(*args, **kwargs)
            return cls._instance

    class REPLACE_DIALOG(object):
        __metaclass__ = REPLACE_DIALOG_SINGLETON

        def __init__(self):
            self.raiaod_button_handle = None
            self.WNDENUMPROC = ctypes.WINFUNCTYPE(BOOL, HWND, LPARAM)
            self.FindWindow = ctypes.windll.user32.FindWindowW
            self.EnumChildWindows = ctypes.windll.user32.EnumChildWindows
            self.GetClassName = ctypes.windll.user32.GetClassNameW
            self.GetWindowText = ctypes.windll.user32.GetWindowTextW
            self.GetWindowTextLength = ctypes.windll.user32.GetWindowTextLengthW
            self.ShowWindow = ctypes.windll.user32.ShowWindow
            self.create_unicode_buffer = ctypes.create_unicode_buffer

        def enum_callback(self, hwnd, lparam):
            curr_class = self.create_unicode_buffer(256)
            self.GetClassName(hwnd, curr_class, 256)
            length = self.GetWindowTextLength(hwnd)
            buff = self.create_unicode_buffer(length + 1)
            self.GetWindowText(hwnd, buff, length + 1)
            if curr_class.value.lower() == u'button':
                if buff.value == u'Replace All in All Opened Doc&uments':
                    self.raiaod_button_handle = hwnd
                    return False
            return True

        def find_controls(self):
            find_dialog_hwnd = self.FindWindow(None, u'Replace')
            if find_dialog_hwnd:
                self.EnumChildWindows(find_dialog_hwnd, self.WNDENUMPROC(self.enum_callback), 0)
            else:
                notepad.messageBox('Error: Bad value for find_dialog_hwnd')

        def show(self):
            notepad.menuCommand(MENUCOMMAND.SEARCH_REPLACE)
            if self.raiaod_button_handle is None: self.find_controls()
            if self.raiaod_button_handle is not None: self.ShowWindow(self.raiaod_button_handle, 0)

    REPLACE_DIALOG().show()
```

**Comment by xylographe** [comment]
@Gewath 
I would recommend the use of a version control system — like git or svn. From experience, I can guarantee, once you have got used to it, you will never want to miss it again.

**Comment by sasumner** [comment]
@xylographe While VCS's are great, I don't know that it solves the problem the OP has here.  Typically (well, at least for me) a VCS serves as a "checkpoint".  It could be after many minutes/hours/weeks of work I want to "checkpoint" my code.  Meaning, it is a "logical" archival, not a "protect me" archival.  I need something else for that.

**Comment by sasumner** [comment]
I think the real intent of this issue is a duplicate of #5253 and a few others...

**Comment by mustafayanci** [comment]
I don't know the solution but if you pressed this button mistakenly, and if you haven't closed notepad++ yet, to undo this fast, do this; 
ctrl + page up  or page up : switches between the tabs
ctrl + z : undo 


press and hold ctrl then  page up - z - page up - z .... page up - z 

go on fast and undo all mistaken replaces..

**Comment by rujiel** [comment]
> 
> 
> Here's a nice little Pythonscript to remove the feature.

That's nice but who all exactly uses this feature? It seems like there are more voices complaining about it than there are ones vouching for it.
