### ISSUE TITLE
(Eyes, my bad)

### ISSUE THREAD

**Issue by Kdmeizk** [notepad-plus-plus/notepad-plus-plus#844]
Line 105, the end :
... dotMatchesNewline="no">

The fix assumed :
... dotMatchesNewline="no" />

**Comment by Rikk** [comment]
You mean in `<FindHistory ...` tag?
In this case, it should not end with `/>` because it is not a self-closing tag; its block is closed with `</FindHistory>` that is after its contents. When it has no sub-items, it will have the `/>` and no `</FindHistory>`.

**Comment by Kdmeizk** [comment]
I think I saw bad because I checked again and finally, there isn't problem. Sorry.
