### ISSUE TITLE
Please do not combine personal political positions with software!-请不要把个人政治立场和软件结合!

### ISSUE THREAD

**Issue by DoraemonMiku** [notepad-plus-plus/notepad-plus-plus#8444]
Dear author, have you been to China? Have you been to Xinjiang? Do you understand Uyghurs? Do you understand the real China? Or do you think "No body know China Better that me?" What you know is just the illusion of media making. You will know the real China only when you come to China to experience it for yourself. Please do not combine your personal political views with computer software.
Judging from the experience of the predecessors, if you have no real reason to defame China and fight against China, you will ultimately suffer.
The world tends to be multipolar, which is the general trend and an objective law. The brutal and unreasonable suppression of China will be counterproductive. If they do not develop in accordance with the objective laws, they will inevitably be punished by the objective laws.
敬爱的作者，你来过中国吗？你来过新疆吗？你了解维吾尔族吗？你了解真正的中国吗？还是说你觉得"No body know China Better that me?" 您所了解的只是媒体制造的假象，你来一趟中国亲身体会才知道真正的中国。请不要把你的个人政治观点和计算机软件结合。
从前辈的经验来看,若你无真实理由诋毁中国和反中,最终受害的还是你。
世界趋于多极化,这是大势所趋也是客观规律。野蛮无理打压中国势必得其反。若不按照客观规律发展必然会受到客观规律的惩戒。

**Comment by imgradeone** [comment]
he don't care.

and also, issue only.

作者不会在乎的，顺便，这里是提 bug 的地方。

**Comment by FranciscoPombal** [comment]
动态网自由门 天安門 天安门 法輪功 李洪志 Free Tibet 六四天安門事件 The Tiananmen Square protests of 1989 天安門大屠殺 The Tiananmen Square Massacre 反右派鬥爭 The Anti-Rightist Struggle 大躍進政策 The Great Leap Forward 文化大革命 The Great Proletarian Cultural Revolution 人權 Human Rights 民運 Democratization 自由 Freedom 獨立 Independence 多黨制 Multi-party system 台灣 臺灣 Taiwan Formosa 中華民國 Republic of China 西藏 土伯特 唐古特 Tibet 達賴喇嘛 Dalai Lama 法輪功 Falun Dafa 新疆維吾爾自治區 The Xinjiang Uyghur Autonomous Region 諾貝爾和平獎 Nobel Peace Prize 劉暁波 Liu Xiaobo 民主 言論 思想 反共 反革命 抗議 運動 騷亂 暴亂 騷擾 擾亂 抗暴 平反 維權 示威游行 李洪志 法輪大法 大法弟子 強制斷種 強制堕胎 民族淨化 人體實驗 肅清 胡耀邦 趙紫陽 魏京生 王丹 還政於民 和平演變 激流中國 北京之春 大紀元時報 九評論共産黨 獨裁 專制 壓制 統一 監視 鎮壓 迫害 侵略 掠奪 破壞 拷問 屠殺 活摘器官 誘拐 買賣人口 遊進 走私 毒品 賣淫 春畫 賭博 六合彩 天安門 天安门 法輪功 李洪志 Winnie the Pooh 劉曉波动态网自由门

Listen to me carefully, paid PRC shills: Emperor Winnie the Pooh and your army of mindless drones will never win as long as there are people like me who do this for free.

In the Free West, despite its many flaws, we can say whatever the fuck we want.

**Comment by Korb** [comment]
This is a duplicate of #6288 (disrespect for other members of the FOSS community by posting political propaganda spam in text editor resources).
