### ISSUE TITLE
Move focus to editor on left-clicking a tab

### ISSUE THREAD

**Issue by Yaron10** [notepad-plus-plus/notepad-plus-plus#8446]
**STR:**
Give keyboard focus to a "not-editor" element (e.g. the Incremental Search Bar). 
Left-click the current document's tab.

**Result:**
The editor does not get the focus.

**Expected Result:** 
The expected behavior is that the editor should get the focus.
Also, practically it can be useful in many cases (e.g. if you want to move focus to the editor without changing the caret position or if you want to keep a selection). 

***
Notepad++ v7.8.3   (32-bit)
Build time : Jan 17 2020 - 18:20:02
Path : C:\---\notepad++.exe
Admin mode : ON
Local Conf mode : ON
OS Name : Windows 7 Enterprise (32-bit) 
OS Build : 7601.23964
Plugins : ComparePlus.dll HTMLTag_unicode.dll MenuIcons.dll PythonScript.dll _CustomizeToolbar.dll

**Comment by Uhf7** [comment]
What you mean here is that the input focus does not switch to the edit window, if the tab of the current document is clicked, right? If the tab of another document than the current one is clicked (and the document switches), then the input focus goes to the edit window already.

**Comment by Yaron10** [comment]
Correct. I've edited my Post.

**Comment by notdodgeball** [comment]
That would be very useful, specially the "not changing the caret position" thing.

**Comment by alankilborn** [comment]
Really cheesy way to do it:

When input focus isn't in editor, right-click the tab and then immediately press Esc (to cancel the tab context menu).  At this point, input focus is in the editor of the chosen tab.

**Comment by alankilborn** [comment]
The original posting here is actually a pretty good idea.
I will prepare a PR implementing the behavior (since there has been no other action on this is over 2 years).
