### ISSUE TITLE
Sorting of stream selection can do one too many lines

### ISSUE THREAD

**Issue by sasumner** [notepad-plus-plus/notepad-plus-plus#8447]
### Description of the Issue
When using the _Edit_ menu > _Line Operations_ > _Sort_ > ... operations on a stream selection, the line at the bottom end (at the higher position) can be unintentionally included in the sort.

### Steps to Reproduce the Issue
1. Create some text in a new N++ tab:
```
Jack and Jill
Went up the hill
To fetch a pail of water
Jack fell down
And broke his crown,
And Jill came tumbling after.
```
2. Select the lines I wish to sort via a single stream selection, by clicking in the line number margin starting in line 1 and dragging down to cover the lines I want to operate on:
![image](https://user-images.githubusercontent.com/30118311/85214274-b08f2b00-b336-11ea-841a-29dd982fb8e3.png)

3. Invoke the _Edit_ menu > _Line Operations_ > _Sort_ > _Sort Lines Lexographically Ascending_ command.

### Expected Behavior
I expected line 6 `And Jill came tumbling after.` to **_NOT_** be included in the lines to be sorted.

### Actual Behavior
Line 6 `And Jill came tumbling after.` **_IS_** included in the lines sorted:

![image](https://user-images.githubusercontent.com/30118311/85214304-f77d2080-b336-11ea-9703-8681ecd79e6d.png)

### Other

I do realize that if I don't include the line ending of line 5 in the stream selection, line 6 will not be included in the group of lines to be sorted.  However, this feels unnatural and is hard to remember to do before conducting the sort.

### Debug Information
Notepad++ v7.8.7   (32-bit)
Build time : Jun  5 2020 - 02:34:28
Path : C:\\..............\npp.7.8.7.bin\notepad++.exe
Admin mode : OFF
Local Conf mode : ON
OS Name : Windows 10 Enterprise (64-bit) 
OS Version : 1809
OS Build : 17763.1039
Current ANSI codepage : 1252
Plugins : mimeTools.dll NppConverter.dll NppExport.dll

**Comment by Yaron10** [comment]
NPP would show **6** selected lines in the status bar.

IMO it's wrong and I've changed `bool getSelectedCount(int & selByte, int & selLine) const` in `ScintillaEditView.h` to:
```
	bool getSelectedCount(int & selByte, int & selLine) const
	{
		// return false if it's multi-selection or rectangle selection
		if ((execute(SCI_GETSELECTIONS) > 1) || execute(SCI_SELECTIONISRECTANGLE))
			return false;
		long pStart = long(execute(SCI_GETSELECTIONSTART));
		long pEnd = long(execute(SCI_GETSELECTIONEND));
		selByte = pEnd - pStart;

		if (selByte)
		{
			long lStart = long(execute(SCI_LINEFROMPOSITION, pStart));
			long lEnd = long(execute(SCI_LINEFROMPOSITION, pEnd));
			selLine = lEnd - lStart;

			CHAR selEndChar = (CHAR)execute(SCI_GETCHARAT, pEnd - 1);
			if (selEndChar != '\n' && selEndChar != '\r')
				++selLine;
		}

		return true;
	};
```
But with the current selected lines count, the Sorting operation is correct.

https://community.notepad-plus-plus.org/topic/13087/sel-in-status-bar-is-off-by-1-on-line-count

**Comment by sasumner** [comment]
Okay, I will look at that as well.  If warranted I will open a separate issue on it.  TBH, I was thinking about a "improve-the-status-bar" issue as well. :-)

>But with the current selected lines count, the Sorting operation is correct.

I would not want to look at the status bar for this operation (which would only be viable for a small, countable number of lines anyway).  But I know this isn't what you are meaning. :-)

**Comment by Yaron10** [comment]
> Okay, I will look at that as well. If warranted I will open a separate issue on it. TBH, I was thinking about a "improve-the-status-bar" issue as well. :-)

Implementing "selected lines count" as we both consider correct would be great.
:+1: 

One point if you do:
If you `Select All`, the total lines would be **7** and the selected lines would be **6**.
It might seem odd at first, but it's actually OK as an empty line can not be selected.

**Comment by sasumner** [comment]
@Yaron10 For your eyes only :)
[Temp.zip](https://github.com/notepad-plus-plus/notepad-plus-plus/files/4815566/Temp.zip)

**Comment by Yaron10** [comment]
@sasumner,

I won't be by my PC today. I'll try it tomorrow.

Thank you. :+1: 

James. James Bond. :)

**Comment by sasumner** [comment]
@Yaron10 I think that a better issue to discuss the "side issue" of the "selected lines in the status bar" is #7716
If we have more to say, let's take it to _that_ issue and not do it here.
