### ISSUE TITLE
Line Operations shouldn't require CR+LF line endings

### ISSUE THREAD

**Issue by blackboxlogic** [notepad-plus-plus/notepad-plus-plus#8448]
### Description of the Issue
When using `Edit -> Line Operators`, the result may not be what the user expects, depending on the line endings.

### Steps to Reproduce the Issue
1. Have your editor set to us CR+LF line endings (shown in the bottom right)
2. In a new file, type `1;3;2`
3. Find-and-Replace all (using `Search Mode: Extended`) `;` with `\n` (this adds `line feed` endings, and shows each number on its own line)
4. Use: `Edit -> Line Operators -> Sort Lines as Integers Ascending`

### Expected Behavior
I expect the file to have lines ordered: 1, 2, 3

This result should be consistent for all files, regardless of line endings (LF, CR, or CR+LF), or the user should be warned the the file has line endings which are not compatible with `Line Operations`, maybe asked if they want that automatically corrected first.

### Actual Behavior
File lines are out of order: 1, 3, 2

These lines were treated as one line by the line operation, because they aren't CR+LF terminated. The bottom right of the toolbar specifies that the editor is currently using `Windows (CR LF)` for line endings. Perhaps, if the lines aren't going to be _treated_ as separate lines (because they do not match the current line-ending setting), then they should not be _shown_ as separate lines. I realize this could be seen as user error, but the mistake was easy to make and easy to miss.

### Debug Information
Notepad++ v7.8.6   (64-bit)
Build time : Apr 21 2020 - 15:23:03
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS Name : Windows 10 Home (64-bit) 
OS Version : 1909
OS Build : 18363.900
Plugins : DSpellCheck.dll JSMinNPP.dll mimeTools.dll NppConverter.dll NppExport.dll XMLTools.dll

**Comment by sasumner** [comment]
Closing as "duplicate" of #7735.
I've kind of dubbed that issue number as the governing one for all "lines with mismatched endings to the ending type for the file are not sorted correctly".
Rest assured that if that issue is dealt with, this one will automatically be as well.

**Comment by sasumner** [comment]
Actually, when I try your example on a debug build, I get the following:

![image](https://user-images.githubusercontent.com/30118311/85231551-fa732200-b3c5-11ea-882d-fac6ef4a9b78.png)

This should be looked into...
