### ISSUE TITLE
Error while build with file NppCommands.cpp

### ISSUE THREAD

**Issue by ayushsinha-13** [notepad-plus-plus/notepad-plus-plus#8449]
#7944 
I'm getting this error when trying to build from VS2019 Community:

It's showing an **error** (warning treated as an error) and **warning** (**C4834**: discarding return value of function with **'nodiscard'** attribute) in file NppCommands.cpp **(line 465)** 

How to fix?

**Comment by ArkadiuszMichalski** [comment]
This still valid?

**Comment by donho** [comment]
I think it's outdated and safe to close it.
