### ISSUE TITLE
Bug to (open) Windows dialog -- Save button doesn't work

### ISSUE THREAD

**Issue by HerbM** [notepad-plus-plus/notepad-plus-plus#8455]
### Description of the Issue
Bug to (open) Windows dialog -- Save button doesn't work

### Steps to Reproduce the Issue

1. Alt-w-w open the Windows dialog:  
2. Select changed file
3. Press Save
 
### Expected Behavior
File should be saved and closed

### Actual Behavior
Nothing

### Debug Information  
[Note: this behavior is long standing and not version dependent]

Notepad++ v7.8.5   (64-bit)
Build time : Mar  4 2020 - 11:08:34
Path : C:\Util\notepad++.exe
Admin mode : ON
Local Conf mode : OFF
OS Name : Windows 10 Pro (64-bit) 
OS Version : 2004
OS Build : 19035.1000
Plugins : BetterMultiSelection.dll ComparePlugin.dll CSScriptNpp.dll CsvQuery.dll DSpellCheck.dll JSMinNPP.dll LuaScript.dll MarkdownViewerPlusPlus.dll mimeTools.dll NppConverter.dll nppcrypt.dll NppEventExec.dll NppExec.dll NppExport.dll NppRegExTractorPlugin.dll NppSnippets.dll NppTaskList.dll NppToolBucket.dll pork2sausage.dll SecurePad.dll SelectQuotedText.dll SurroundSelection.dll XBrackets.dll XMLTools.dll _CustomizeToolbar.dll

**Comment by Uhf7** [comment]
If the file(s) has/have been modified in the editor, then it/they are saved when pressing the **Save** button in this window.

I don't think that closing the window(s) is an intended function of the **Save** button. That's what the **Close window(s)** button is for.

**Comment by sasumner** [comment]
I think there is some weirdness here.

Set up this tab scenario (in 7.8.7) and open the _Window_ > _Windows..._ box :
![image](https://user-images.githubusercontent.com/30118311/85719797-c6497b00-b6bd-11ea-9ffa-162866b6588a.png)

With `readme.txt` highlighted per the screenshot, press the _Save_ button.

A _Save As_ box pops up with this showing :
![image](https://user-images.githubusercontent.com/30118311/85720004-ff81eb00-b6bd-11ea-970e-a3eeb5c96d6d.png)

Shouldn't `readme.txt` just simply be quietly saved in this situation?

**Comment by HerbM** [comment]
@Uhf7 You are correct that it should not be Closed, I wrote that in error.

However, on every version of NP++ I have used it doesn't do the following:

- The asterisk indicating a changed file is not removed
- The file is still marked as changed after dismissing the Windows dialog
- The file is still different from the version on disk (per Compare).

As to the "Save as" dialog that should really only show if the file has not been previously save (I think).
- 

-

**Comment by Uhf7** [comment]
@HerbM, @sasumner 
Now I see it too. There are indeed strange things happening. If the first file in the list is modified and selected while clicking **Save**, it is saved. If the second file in the list is modified and selected while clicking **Save**, it is not saved. Something seems to be wrong with the selection. And I can verify the strange effect with the new file being in the list above the selected file too.

**Comment by sasumner** [comment]
@Uhf7 Did you want to pursue the problem, to the point of a PR for it?  Otherwise I will go down that road.

**Comment by Uhf7** [comment]
Just found it. It's in Big Switch, 
`fileSave(_pDocTab->getBufferByIndex(i))`
 instead of 
`fileSave(_pDocTab->getBufferByIndex(nmdlg->Items[i])) `

I'm currently worrying about the `WDT_SORT` function a view lines below, it seems to have the same problem.

**Comment by Uhf7** [comment]
The Sort function works correctly, it is using the same parameters in a different way. Creating a PR for the modification mentioned.

**Comment by shimscharf** [comment]
I think this may also be related:

Save sometimes does not work (file changes are not detected) #4949

https://github.com/notepad-plus-plus/notepad-plus-plus/issues/4949

Hopefully fixed it too
