### ISSUE TITLE
CTRL+Q Toggle Single Line Comment Ignored for .xml Files

### ISSUE THREAD

**Issue by imallett** [notepad-plus-plus/notepad-plus-plus#846]
CTRL+Q doesn't not work for .xml files. The CTRL+[SHIFT+]K works fine.

I suspect this is a minor bug.

**Comment by dogancelik** [comment]
I can confirm this ("toggle single line comment" doesn't work on XML files), it doesn't work even when you change keyboard shortcut to something else.

Notepad++ 6.9.2, Windows 8 (64-bit)

**Comment by dail8859** [comment]
Closed by 166cb3f
