### ISSUE TITLE
Plugin [DSpellCheck.dll] Exception when using horizontal slide bar on Collapsed File

### ISSUE THREAD

**Issue by Tequiller** [notepad-plus-plus/notepad-plus-plus#8462]
### Description of the Issue
When we try using the Horizontal Slide Bar and the file code is Collapsed, a plugin Exception appear. Message of the pop-up is copied in comments below.

### Steps to Reproduce the Issue
1. Have code lines that are wider than the panel width and that it could be collapsed (this code could be in C++ language)
2. Fold All (the cold have to permit a collapse for this test)
3. 2 alternatives:
> Alternative 1. Slide the horizontal bar to the right.
> Alternative 2. Go to the right of a long line with arrows key

### Expected Behavior
Panel go to the right without error.

### Actual Behavior
Panel go to the right but a pop-up open immediately twice time, and spam all the time we try to slide the text.
Only go to the Column 1 stop the pop-up spam.

### Debug Information
Notepad++ v7.8.6   (32-bit)
Build time : Apr 21 2020 - 15:17:06
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : ON
Local Conf mode : OFF
OS Name : Windows 8 (64-bit) 
OS Build : 9200.0
Plugins : DSpellCheck.dll mimeTools.dll NppConverter.dll NppExport.dll 

### Additional Comments
I supposed this bug appearing from last update.

Message is :

> Plugin Exception
> An exception occured due to plugin: DSpellCheck.dll
> Exception reason: vector<T> too long

![image](https://user-images.githubusercontent.com/46250710/85494809-b7899800-b5d9-11ea-9ca0-8df654b1c77b.png)

**Comment by sasumner** [comment]
Please report this wherever the DSpellCheck plugin is supported.

**Comment by Tequiller** [comment]
It isn't automaticaly integrated with NPP?
Don't remember to have add it manualy...
I'll search their github.

**Comment by sasumner** [comment]
>It isn't automaticaly integrated with NPP?

No.

**Comment by chcg** [comment]
Current version is https://github.com/Predelnik/DSpellCheck/releases/tag/v1.4.16 . Previous versions of N++ were bundled with DSpellCheck.
