### ISSUE TITLE
Use # as comment character in properties files

### ISSUE THREAD

**Issue by mach900** [notepad-plus-plus/notepad-plus-plus#8464]
Currently Notepad++ uses incorrectly semicolon as comment character in Edit->Comment/Uncomment operations when editing *.properties files.
Please change it to hash.

I tried to change langs.model.xml, but no effect:
<Language name="props" ext="properties" commentLine="#"/>

**Comment by ArkadiuszMichalski** [comment]
Base on https://docs.oracle.com/cd/E23095_01/Platform.93/ATGProgGuide/html/s0204propertiesfileformat01.html and https://en.wikipedia.org/wiki/.properties it should be `#` or `!`.  @mach900 you should also change/remove your `lang.xml` file.

**Comment by donho** [comment]
PBEBKC

**Comment by ArkadiuszMichalski** [comment]
@donho But actually it's:
`<Language name="props" ext="properties" commentLine=";"/>`
What the author did not mention explicity.

**Comment by ArkadiuszMichalski** [comment]
Yes, I noticed that lexer recognize 3 char as comments, so I deduced that everyone can choose one :). Don't know frome what spec this `;` came, but if `#` or `!` is more standard then may be change.
