### ISSUE TITLE
Horizontal scrollbar position is reset on minimise - restore of window

### ISSUE THREAD

**Issue by alex-code** [notepad-plus-plus/notepad-plus-plus#8466]
### Description of the Issue

If you have an open tab with a horizontal scrollbar that's been scrolled to the right.
Minimising then restoring the Notepad++ window resets the scrollbar position back to the left even though the content is still scrolled.

Clip below shows content is scrolled but scrollbar has been reset after minimise/restore.

![image](https://user-images.githubusercontent.com/1797626/85582584-758e3f80-b635-11ea-93e2-8d7940df7ed9.png)

### Steps to Reproduce the Issue

1. Open any file that would cause the horizontal scrollbar to show
2. Scroll to the right
3. Minimise the Notepad++ window
4. Restore the Notepad++ window

### Expected Behavior

Horizontal scrollbar to keep scroll position

### Actual Behavior

Horizontal scrollbar position is reset

### Debug Information

Notepad++ v7.8.6   (64-bit)
Build time : Apr 21 2020 - 15:23:03
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS Name : Windows 10 Pro (64-bit) 
OS Version : 1909
OS Build : 18363.900
Plugins : ComparePlugin.dll DSpellCheck.dll mimeTools.dll NppConverter.dll NppExport.dll

**Comment by sasumner** [comment]
Verified on 7.8.7.
