### ISSUE TITLE
Toggle Panel on/off

### ISSUE THREAD

**Issue by davidbrigden** [notepad-plus-plus/notepad-plus-plus#8471]
### Some panels can be toggled on/off from menu entries.  Others can not.  Have all toggle

In Notepad ++ there are a number of panels supplementing the editor itself.  All can be opened by selecting in the menu.  Some can be closed again from the menu  
* Project as Workspace
* Document Map
* Function List.  

Others can only be closed by closing the panel directly
* Character Panel
* Clipboard History
* Project Panel (1, 2, 3)
* Search Results

This seems inconsistent.  I think that all panels should toggle on/off.   I say this because we can have multiple panels in a stack docked to the side or bottom of N++.  If you close a docked panel, you close the entire stack. 

I would rather not close an entire stack just to close a single panel.  I also would rather not drag a panel off the stack to close it.  It seems the best way is having the menu entry (or toolbar entry or shortcut) toggle the panel

**Comment by ArkadiuszMichalski** [comment]
@Uhf7  Is there any way to close all panels in stock with one action? When I have a lot of them in one stock now I must click [x] or middle mouse button on each panel. Overall this solution with [x] is better than previouse, but now there is no option to close all :) Maybe with Ctrl + [X] or other key can do it?
