### ISSUE TITLE
did not auto scroll to last line after update

### ISSUE THREAD

**Issue by johnw2018** [notepad-plus-plus/notepad-plus-plus#8477]
i found a bug .
Settings > Preferences > MISC -> File Status Auto-Detection
‘Update Silently’ and ‘Scroll to last line after update’
but did not auto scroll to the last line after update

i used 
notepad++ v7.8.7 
windows 7 64bit

**Comment by Yaron10** [comment]
It only occurs if Word-Wrap is ON, and it's a regression in 7.8.3.

**Comment by Yaron10** [comment]
The issue is not fixed with https://github.com/notepad-plus-plus/notepad-plus-plus/commit/4b8d83a8f882e6cd7c0acb570f871a519104e691.

**Comment by donho** [comment]
Thank you @Yaron10 for checking it.
I'll take a look on this issue.
