### ISSUE TITLE
[Improvement] Switch Save As/Save All shortcuts to abide by conventions

### ISSUE THREAD

**Issue by theFireProjet** [notepad-plus-plus/notepad-plus-plus#8482]
### Description of the Issue / Actual behaviour

Every program on windows that allows file editing has at least two options to save the current file: _save_ and _save as_. Usually `Ctrl` + `S` is the shortcut for _save_ and `Ctrl` + `Shift` + `S` for _save as_.
<details><summary>Examples</summary>
* Windows Notepad
* Adobe Acrobat Reader DC
* paint.net
* GIMP
</details>

However, it's different in _Notepad++_: `Ctrl` + `Shift` + `S` is the shortcut for "_Save All_" while "_Save as..._" has the shortcut `Ctrl` + `Alt` + `S`.

### Expected Behavior

Notepad++ is supposed to stick to the conventions and user `Ctrl` + `Shift` + `S` as the shortcut to use the _save as_ option. In order to make this possible, `Ctrl` + `Alt` + `S` should be the new shortcut for the _save all_ option, so both shortcuts are switched.

### Why is this important?

`Ctrl` + `Shift` + `S` is the most common shortcut to use the save as option. The users know this key combination and expect it to work in the way they are used to from other programs.

### User benefit

Switching the shortcuts in Notepad++ as described above make the user experience simpler because the behaviour is more consistent on the computer. Users do not have to remember that in Notepad++ they have to be careful because here, it's not the usual shortcut, it's a different one. Also the amount of effort is high that it takes to undo accidentally pressing `Ctrl` + `Shift` + `S` to save the current file. Dependent on how many unsaved files are open in Notepad++, this can result in a lot of save as windows opening at the same time.
There is a reason that most shortcuts work in the same way across a variety of programs: The user doesn't have to remember a lot of basic shortcuts for many programs, while they are different in every single program. It's a lot more convenient and easier to use if common shortcuts stick to some rules.

**Comment by sasumner** [comment]
Map the keys as you like them in _Settings_ menu > _Shortcut Mapper..._ :

![image](https://user-images.githubusercontent.com/30118311/85890326-2114cc80-b7bb-11ea-8a52-4c66264bb89b.png)

**Comment by theFireProjet** [comment]
I know this is possible but for the reasons explained above, it would still be better to stick to common shortcuts by default.

**Comment by sasumner** [comment]
Defaults are long-established the way they are in Notepad++.
They aren't going to be changed now.

**Comment by reddtoric** [comment]
Seriously. Although the shortcut can be changed, I didn't know Ctrl + Shift + S was save all. And there is no obvious difference between saving just one file versus all the files aside from multiple save menu popping up (Not sure if it switches to that file that it's currently saving but when the program keeps popping up the save menu, you don't notice that, at least not always.) When Notepad++ kept popping the save menu, I thought it was out of whack and not that it's saving all the opened files. I overwritten and lost a few files.

**Comment by sasumner** [comment]
@reddtoric 

Please provide official references that these are established norms.

Counter-example:
In Microsoft Office products, SaveAs is F12

**Comment by reddtoric** [comment]
@sasumner 

Alright, I did used the word "convention" but initial issue opener used "common", which was what I was going for. My point still stands, is it common? Seems like Ctrl + Shift + S is a common shortcut for save as rather than save all.

And since you asked, here are 14 programs that use Ctrl + Shift + S for save as:
Blender, Adobe Photoshop/Illustrator/Premiere, Notepad, Arduino IDE, PrusaSlicer, VS Code, Foxit PDF, Brackets, Bluefish, GIMP, Autodesk Maya, Atom
*6 of which are text editors and/or source code editors.

*I found out that VS uses Ctrl + Shift + S for save all while VS Code uses for save as... that's just ridiculous.

Anyway, I'll stop here since it can be changed to user's preferences.

**Comment by sasumner** [comment]
>Anyway, I'll stop here since it can be changed to user's preferences.

+1

Plus, could you imagine the reaction of a decades-long Notepad++ user, after a new install, trying for a SaveAs and obtaining a SaveAll ?

**Comment by FlashlightET** [comment]
> > Anyway, I'll stop here since it can be changed to user's preferences.
> 
> +1
> 
> Plus, could you imagine the reaction of a decades-long Notepad++ user, after a new install, trying for a SaveAs and obtaining a SaveAll ?

sucks to be them i guess

**Comment by alankilborn** [comment]
>sucks to be them i guess

Probably sucks to be someone that is complaining about this (original concept of this issue), or agreeing with the complaint -- just change to whatever you like, in _Shortcut Mapper_, and it is over and done with, nothing to complain about any longer.
