### ISSUE TITLE
Find Results: Flickering cursor after double-clicking a found line

### ISSUE THREAD

**Issue by Yaron10** [notepad-plus-plus/notepad-plus-plus#8487]
**STR:**
Open file `A`.
Select a word.
Open the Find dialog.
Find.
Close file `A`.
Delete file `A` in Windows Explorer.
In the `Find Results` window double-click a found line under file `A`.

**Result:**
The `File No Longer Exists` message is displayed (correct).
The cursor is intensely flickering. You'd have to exit NPP.
***
Notepad++ v7.8.3   (32-bit)
Build time : Jan 17 2020 - 18:20:02
Path : C:\---\notepad++.exe
Admin mode : ON
Local Conf mode : ON
OS Name : Windows 7 Enterprise (32-bit) 
OS Build : 7601.23964
Plugins : ComparePlus.dll HTMLTag_unicode.dll MenuIcons.dll PythonScript.dll _CustomizeToolbar.dll

**Comment by Uhf7** [comment]
> The File No Longer Exists message is displayed (correct).

Not true in 7.8.7and 7.8.8. The message box says "_File_ doesn't exist. Create it? [Yes] [No]". Which is quite useless at this point, because we will never find the old search result in the newly created file. Unless it is an empty string at position 0.
