### ISSUE TITLE
[small request/bug] column editor's radio button not responding to keyboard input

### ISSUE THREAD

**Issue by GhbSmwc** [notepad-plus-plus/notepad-plus-plus#8488]
I noticed that the two radio buttons which determines the mode of what to insert cannot be highlighted via keyboard input (tab/ SHIFT+Tab)
![image](https://user-images.githubusercontent.com/13095760/85926202-c9826980-b86b-11ea-81cf-98b483a873bb.png)

This is annoying if users mainly use the keyboard for faster focus on the GUI elements.

**Comment by donho** [comment]
@GhbSmwc 
Is it better if the default selection is put on `Number to Insert`, then you can use TAB key to navigate ?

**Comment by GhbSmwc** [comment]
I think it is better to have arrow keys to trigger the radio buttons instead of TAB, much like the `find and replace`.

**Comment by sasumner** [comment]
I think TAB key navigation is a little awkward in most cases, and especially this one because it may jump to where user doesn't expect.  Why not just go with a press of the Alt key and then it shows you what key to add to go exactly where you want to?

**Comment by sasumner** [comment]
Changes from this issue released in Notepad++ version 7.9
