### ISSUE TITLE
LICENSE has duplicated interpretation clauses

### ISSUE THREAD

**Issue by kroeschl** [notepad-plus-plus/notepad-plus-plus#8494]
### Description of the Issue

When the LICENSE was rearranged somewhat in 9636431f9467, one clause was duplicated--excerpt here:
```
...
Note that we consider an application to constitute a "derivative work" for the purpose of this license if it integrates/includes/aggregates Notepad++ into a proprietary executable installer, such as those produced by InstallShield. Our interpretation applies only to Notepad++ - we don't speak for other people's GPL works.

Our interpretation applies only to Notepad++ - we don't speak for other people's GPL works.
...
```
[Linked here](https://github.com/notepad-plus-plus/notepad-plus-plus/blob/master/LICENSE#L10).

### Steps to Reproduce the Issue

1. View the LICENSE file, either in the source repo or the installation directory.
2. Notice the duplicated lines.

### Expected Behavior

The LICENSE does not contain duplicated information.

### Actual Behavior

Oops.

---

I'd just create a PR, but per the contributing guidelines there must be an open issue first.

**Comment by donho** [comment]
https://github.com/notepad-plus-plus/notepad-plus-plus/commit/0488e92e9f61d63a7ba25b5eefb362b557756ecc
