### ISSUE TITLE
'Save All' button doesn't become greyed out when it should

### ISSUE THREAD

**Issue by Eldaw** [notepad-plus-plus/notepad-plus-plus#850]
Start a fresh instance of Notepad++ with just a single, new document.

Type anything in the new document (so that the 'Save' and 'Save All' buttons become active).

Close the tab without saving.

Notice that the 'Save' button becomes greyed out, but the 'Save All' does not.

**Comment by AdrianHHH** [comment]
Is this a variation of what is reported here: https://github.com/notepad-plus-plus/notepad-plus-plus/issues/529 ?

**Comment by Eldaw** [comment]
> Is this a variation of what is reported here: #529 ?

No, I don't think so.

**Comment by Yaron10** [comment]
Interestingly, if you press "Close All" - the 'Save All' button IS greyed out.
