### ISSUE TITLE
Session lost when cancelling windows shutdown

### ISSUE THREAD

**Issue by momala454** [notepad-plus-plus/notepad-plus-plus#8508]
### Description of the Issue

When we cancel (echap) the shutdown of windows with notepad++ and files open, the session is cleared, it contains no files.
This happened multiple times to me.

### Steps to Reproduce the Issue

1. open multiple files or create temporary files
2. click on windows, shutdown
3. press escape (don't know if the timing is important) while you see the shutdown animation
4. the shutdown will be cancelled and you will be in front of an empty session of notepad++, without your opened files

### Expected Behavior

the session is kept

### Actual Behavior

the session is lost

### Debug Information

Notepad++ v7.8.7   (64-bit)
Build time : Jun  5 2020 - 02:38:56
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS Name : Windows 10 Pro (64-bit) 
OS Version : 1909
OS Build : 18363.900
Current ANSI codepage : 1252
Plugins : ComparePlugin.dll mimeTools.dll NppConverter.dll NppExport.dll NPPJSONViewer.dll XMLTools.dll

**Comment by KnIfER** [comment]
what is echap ?

**Comment by momala454** [comment]
> 
> 
> what is echap ?

sorry, escape key

**Comment by donho** [comment]
Fix by https://github.com/notepad-plus-plus/notepad-plus-plus/commit/6000f3bb21a42a4d28d068617e0dc642ef739b26
