### ISSUE TITLE
Performance in Wine is damn damn damn inacceptible

### ISSUE THREAD

**Issue by KOLANICH** [notepad-plus-plus/notepad-plus-plus#8510]
### Description of the Issue
[npp_slowdown.mp4.zip](https://github.com/notepad-plus-plus/notepad-plus-plus/files/4864433/npp_slowdown.mp4.zip) (i'm not mad, it's github doesn't accept mp4)

### Steps to Reproduce the Issue
1. open any file in NPP in Wine
2. try to input text

### Expected Behavior
Must be blazing fast

### Actual Behavior
Damn slow.

### Debug Information
```
Notepad++ v7.8.8   (64-bit)
Build time : Jun 23 2020 - 23:59:56
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : ON
Local Conf mode : OFF
OS Name : Microsoft Windows 10 (64-bit) 
OS Build : 17134.0
Current ANSI codepage : 1251
WINE : 5.11
Plugins : ComparePlugin.dll DoxyIt.dll DSpellCheck.dll JSMinNPP.dll mimeTools.dll NppConverter.dll nppcrypt.dll NppEditorConfig.dll NppExport.dll NppQrCode64.dll XMLTools.dll 
```

DirectWrite is disabled.

**Comment by sasumner** [comment]
Nobody ever made any Wine guarantees...

**Comment by KOLANICH** [comment]
in fact, [**any** guarantees](https://github.com/notepad-plus-plus/notepad-plus-plus/blob/3de506bf48c53c424ef1e52d623f1d949465102b/LICENSE#L100)

So, if "no guarantees" fact is a reason to close this issue, it is also a reason to close all other issues, and maybe even close the whole project and delete its source code - noone has guaranteed its persistence, right?

**Comment by sasumner** [comment]
Notepad++ is a Win32 project.
Running under other operating systems is always going to be "suspect".
It's an "if it works, great...if it doesn't, ummm, well,...meh..."

**Comment by KOLANICH** [comment]
https://bugs.winehq.org/show_bug.cgi?id=46787

**Comment by ceisserer** [comment]
really sad to read how this report was shut down.
