### ISSUE TITLE
Feature request: silent update

### ISSUE THREAD

**Issue by PGNetHun** [notepad-plus-plus/notepad-plus-plus#8514]
### Feature request: silent update
Whenever there is a new update for Notepad++, it shows a popup window, and then the setup application starts with UI, in which we usually hit Next-Next-Finish... that's total waste of time.
It would be better to update Notepad++ silently, like Visual Studio Code does: it shows just a small bubble, that there is an update, you hit Update button, and it automatically updates application in the background, all you have to do is to restart VS Code, and that's it.

Notepad++ should update similarly:
- either update automatically in the background (if it is enabled in settings), and restart if done
- or when you close Notepad++, and there is an update (actual flow), then provide a button to update silently: no Next-Next-Finish UI, just update silently with default options.

**Comment by gnodarse** [comment]
Just offering a perspective:

I like the way notepad++ updates. It makes updates more of an "event". The concrete benefit of that is that I am cognizant of every update that occurs I read the changes in every update. Automatic updates are good for applications that want to sneak in features that users don't want.

**Comment by Blightbuster** [comment]
The problem for me is, that I dont want to install a update (which takes about a minute) before being able to quickly view or edit a text / config file. The way it currently updates makes me not update it for atleast a week until it gets to anoying to always have the pop up when im just trying to use np++ for 30 seconds.

**Comment by JonathanLydall** [comment]
> Just offering a perspective:
> 
> I like the way notepad++ updates. It makes updates more of an "event". The concrete benefit of that is that I am cognizant of every update that occurs I read the changes in every update. Automatic updates are good for applications that want to sneak in features that users don't want.

Clearly it needs to be a user option because while you may not want software updating itself, I on the other hand find the current way that Notepad++ does updates very disruptive and distracting, it actively annoys me every single time that I have to do 10 clicks to update the app.

Filezilla is similarly annoying, but overall less so as updating it is a two click process, however, it is worse than Notepad++ in that the installer is left lying around in my downloads folder.

I would love to have the option for updates to happen automatically and silently in the background and when I re-open the application it shows the changelog.

**Comment by aarner42** [comment]
My team uses Notepad++ on 40+ virtual machines for editing config files, viewing logs, other quick tasks.  Every time an update is deployed for NPP, that's going to be ten (I counted) clicks to get through the update process, close the change.log file, and get back to what I was doing.  Multiply by the number of VMs, that's over 400 clicks.  Not once on any of these VMs have I ever wanted to change the install options once NPP was originally installed - In every case I'm just clicking next/finish as fast as possible to get through the process.

A proposed option in Settings->Preferences: [x] Apply updates automatically/silently on app close.

This would seem to preserve the behavior for users that want to observe or be aware of updates, and remove a huge annoyance for the rest of us just using NPP with the default options on multiple systems.  Notepad++ is an awesome editor and I've enjoyed using it for years.  The update process on the client end is very irritating though, I've believe there has to be a better way of dealing with this.  (Yes, I'm aware I could leverage WSUS to get this done but I don't have the level of access required to make that happen and the organization I work for lacks the resources to have someone else put this kind of thing together)

**Comment by mjmatthiesen** [comment]
I understand not everyone wants silent/background/automated updates. But I think the majority of us do. I turn it on in all the software that supports it is. Is quickly becoming a standard process.

I basically don't update for several versions because I don't want to specifically take out time to do it.

**Comment by brz** [comment]
I'm getting pretty tired of the periodic update nag screens on all of the (virtual) machines I'm using. I will probably disable the update warning altogether and keep using an outdated NP++ until a VS-Code-like update mechanism exists.

**Comment by WoLpH** [comment]
I'm in the same boat with multiple machines and only needing to use Notepad++ once every few weeks/months for most machines. For now I've resorted to disabling auto-update on all machines but that's obviously not a great solution for anyone.

**Comment by RandomEngy** [comment]
Using an installer technology like [Squirrel](https://github.com/clowd/Clowd.Squirrel) could help here. The philosophy is you install to `%localappdata%` so you don't need a UAC prompt, with no install wizard, and updates act like Chrome: it downloads and installs the next version silently in the background and takes effect the next time you launch. Or you can click a button to restart with the new version right away.

[It does support native apps](https://github.com/clowd/Clowd.Squirrel/blob/develop/docs/using/custom-squirrel-events-non-cs.md) like Notepad++.

It also automatically creates delta packages so you don't need to download the full installer on every update; just the changed parts.

I'm similarly annoyed by Notepad++'s laborious update process so I was considering attempting a pull request to modernize it.

**Comment by davidschwegler** [comment]
The current update system forces you to choose between skipping security/etc updates and being punched in the face.

Please change it.

**Comment by MarceloLaser** [comment]
Allow me to add my voice to this feature request. As @JonathanLydall stated, I too recognize that a small minority of people enjoy being made aware of every tiny change to the system, but for the majority of us who do not care, please include a silent updater, or at the very least, an auto-updater that runs automatically without prompting me through an entire install wizard. I am happy to have the system update every single time I open it, so long as it is done in a way that is not disruptive. As it stands, I essentially never update notepad++, which is less than ideal considering that if the system has been updated, I must assume the developers had a good reason to do so.

**Comment by systemmonkey42** [comment]
I suggest updates need to be (a) seamless, (b) non-intrusive.

Chrome for example installs a service which ensures chrome is always up to date.

All you would need to do is, on launch, check if there is an update, download it and leave it somewhere.

Then when exiting, perform a silent install of the update.

This is clearly not a technical issue, it appears users are broken into two camps,
those that want updates to be an experience (which was how I felt when updates were monthly on a single install), and those who want to be updated without being told about it (especially for security fixes).  A simple configuration switch would handle this.

**Comment by Crostiphex** [comment]
I ended up here after feeling similar to a lot of people on the silent updates. I see this thread is almost 3 years old at this point. I'm hoping to bump this thread to get eyes on it, but realistically I'm hoping a member of the team can comment on if this is feasible or not.

Right now looks like this has fallen on deaf ears.

**Comment by dannongruver** [comment]
sure. thank you for that.

**Comment by softyoda** [comment]
Anyone could please make an Auto Hotkey Script that detect every time notepad++ ask me to download the update, just to automatically click next->next->next->next->next->ok

**Comment by davidschwegler** [comment]
I like the way this guy thinks ;)

**Comment by systemmonkey42** [comment]
> I like the way this guy thinks ;)

I have so many autohotkey hacks to get around bad software, nag screens, popups etc.

I was really hoping Notepad++ would be better than that.  Its like a sports car with an ugly spare tyre bolted to the back..

Ironically my deploy script uses
```
.\npp.Installer.x64.exe /S
```
on initial deployment, and is completely silent.  Only the updates are ugly..

I'm thinking a better solution is to completely turn off update checking in NPP, and use a SEPARATE script which checks for updates, downloads them and performs a silent install behind the scenes (much like chrome's update service does).

**Comment by systemmonkey42** [comment]
> Here is another person who would like to see such a feature. But, I still think, it should be disabled by default.

... but put an checkbox in the update notification dialog labelled 'update silently from now on'..

**Comment by mike-loux-planview** [comment]
Is it me, or do the more recent versions of NPP (Jan 2023 ish) now make the "you have an update" dialog modal?

Used to be I could click away from it and deal with it after I was done with the file I opened NPP for the sole purpose of viewing/editing. 

Now I have to either update (and then re-open the file I was working on), or click Cancel (and forget to do the update altogether).

So...an annoying process just got even more annoying.

**Comment by systemmonkey42** [comment]
Yeah, I noticed that too.   I have an 8.4.2.0 install, and the update dialog can be ignored until I finish what I'm doing, while the 8.4.7.0 installed version is angrily flashing the update dialog at me as we speak.

Once you can the download button, you can ignore the installer until you are ready.

**Comment by rbuzzell** [comment]
I'll chime in requesting the silent/automatic updates as well. Looks like I'm responsible for 244 installs of NPP (as of today's software inventory), 183 of which are some outdated version. I know if I only open NPP once in awhile, I'll go 12-18 months without an update because I'm just trying to look at a file in the moment, not have an update experience that's disrupting my workflow.

I suspect most of my users aren't even administrators so they **can't** do it themselves even if they wanted to. Right now I will package a new update for deployment a few times a year, but I'd greatly prefer to offload that process to the software itself and not have to care about it beyond "I'm just going to update our base version once in a while".

**Comment by mike-loux-planview** [comment]
I'm tempted to try disabling auto-update and just go back to using the [Chocolatey version](https://community.chocolatey.org/packages/notepadplusplus) instead (that way I can just do `choco update --all` every so often and update everything in one fell swoop).  Although I am not sure if that installs with the auto-updater enabled or not - been a while since I used it and I stopped using it because I would inevitably update it through the UI when prompted anyway.

**Comment by lightingman117** [comment]
Please add checkbox in settings for silent update
Been 2 years mang.
Everyone else is on the silent update bandwagon.
I would understand not enabling it by default.

**Comment by davidschwegler** [comment]
I think someone will have to take the time to write a PR, or this won't ever get implemented.

I simply have no time to do so. Which is probably one reason why I hate the NPP installer so much...it just wastes time I already don't have.

**Comment by Crostiphex** [comment]
Right, I sorta feel we’ve been talking to ourselves, there’s no acknowledgment of any kind for dropping or pursuing the feature.

**Comment by rbuzzell** [comment]
> I think someone will have to take the time to write a PR, or this won't ever get implemented.

The problem is that I'm betting that a bunch of us asking for this or that desire this are systems administrators or end-users and not C++ developers.

If I got angry enough at it I could probably write it. It would be absolutely abysmal, meet zero code quality standards, and probably reek of someone whose only exposure to C++ was learning inheritance 10 years ago before using just Bash, Python, and PowerShell for writing run-once scripts.

**Comment by mike-loux-planview** [comment]
Heh.  Sounds familiar.  I AM a software developer, BUT...I learned C++ in college, about 30 years ago, and then didn't touch it for 10 because I pivoted into network admin.  By the time I went back into development, it was on languages like Java, Perl, and the .NET family.  
If this were written in C#, I could probably bang something out, but the last time I did any C++ work was 7 or so years ago, and then it was debugging an embedded hardware driver for about 2 hours before changing a + to a - in the code.  Not exactly conversant with the language any longer.  So, my PR would be, if anything, even worse.
And, yeah, PowerShell is the shiznit.

**Comment by andremalenfant** [comment]
Same here. We have many VMs that are scanned periodically for vulnerabilities and I wish NPP would update automatically. We get hits all the time and that requires opening NPP on every single VM to update.

**Comment by xomx** [comment]
https://community.notepad-plus-plus.org/topic/24884/winget-real-autoupdater-finally

**Comment by schenardie** [comment]
Hey @xomx is this (adding /closeRunningNppAutomatically) in the making?? If not all good its just more informational :)

**Comment by xomx** [comment]
@schenardie 
Not yet, but it is on my TODO.
My spare time is limited and I am currently working on another N++ issue.

**Comment by schenardie** [comment]
Cool, thanks for the quick update. Hopefully you get some time in the future. Cheers

**Comment by recolic** [comment]
or we can solve this problem in a much easier way:
provide a installer without annoying auto-updater.

**Comment by xomx** [comment]
@recolic 
[/noUpdater](https://npp-user-manual.org/docs/command-prompt/#installer-options)

**Comment by recolic** [comment]
> @recolic [/noUpdater](https://npp-user-manual.org/docs/command-prompt/#installer-options)

I know this option, but it's not convenient for windows user to launch command line & typing for each installation. Windows user doesn't do that.

I'm trying to remove (or intentionally break) updater from the installer, to solve the problem once forever.

**Comment by xomx** [comment]
Just a general note: currently the winget has been updated (N++ v8.6.5) to reflect my last patch for the silent installations, so now it can handle the possible N++ installer `ERROR_ACCESS_DENIED` error return in case of an already running previous N++:
https://github.com/microsoft/winget-pkgs/pull/147716/commits/ac8eeae18b7d4bdeddf4c97fd636df125b35d403

**Comment by uma201** [comment]
Pffft, the NP++ update process on Windows is so annoying, I startet to search the options and then the internet, and found this 4 yr old thread. I really love NP++, it is a great great editor, and I use it a lot. But the permanent, lengthy (no, my language didnt change, no, this is the same, etc) update annoys me. Today I switched off "automatic updates", maybe I do a manual update once or twice a year.
If automatic, silent updates are available I probably will enable the automatic updates again.
:-|

**Comment by xomx** [comment]
@uma201 

If you do not mind to use the N++ PythonScript plugin, you can use this partial workaround (now it can upgrade even the portable N++ setups!):
https://community.notepad-plus-plus.org/topic/25817/upgrading-notepad-with-one-click

Here is the direct link to the latest script version with explanations:
https://community.notepad-plus-plus.org/post/95098

**Comment by xomx** [comment]
@schenardie 
> is this (adding /closeRunningNppAutomatically) in the making?

The next upcoming N++ installer version (probably v8.6.9) will contain `/closeRunningNpp` optional cmdline switch.

If specified on the cmdline, it first tries to use the usual app-closing by sending the [WM_CLOSE](https://learn.microsoft.com/en-us/windows/win32/winmsg/wm-close) message to the running N++ (it will wait max 5 seconds for this N++ usual exit). If that standard closing fails, it uses consequently the forceful [TerminateProcess](https://learn.microsoft.com/en-us/windows/win32/api/processthreadsapi/nf-processthreadsapi-terminateprocess) WINAPI way. It also handles the possible N++ multi-instance mode (it will close all the running N++ instances).

**Comment by donho** [comment]
The behaviour of this feature will be the following:

![image](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/90293/fe52c3ab-9256-4b44-91b9-6e06f933d682)

* Choose **Yes** will trigger the classic update with GUI (with NEXT, NEXT...).
* Choose **Yes (Silent)** will download the package, close your Notepad++, then install new version of Notepad++ silently (without NEXT, NEXT...). After the installation, new version of Notepad++ will be launched.

**Comment by donho** [comment]
Fix: https://github.com/notepad-plus-plus/wingup/commit/069edc21e28db01b13f88ac451aa71aea4889dfe

**Comment by mike-loux-planview** [comment]
Even better if it would silently download, then wait until we closed Notepad++, and THEN initiate the install.

**Comment by JonathanLydall** [comment]
> Even better if it would silently download, then wait until we closed Notepad++, and THEN initiate the install.

Definitely would be nicer, but to give credit where credit is due, this one-click upgrade process will likely be a significant quality-of-life improvement.

Based on my experience with FileZilla, which is also 1-click to upgrade, and this seems like it will feel the same, it's merely a single click and then at most a few seconds waiting to be able to continue working, I have not really found it be disruptive to my workflow. My only real gripe with FileZilla's upgrade process is that it doesn't clean up its installer from the downloads folder once it's done.

**Comment by CennoxX** [comment]
@mike-loux-planview there is another issue about updating on exit, which is at least already assigned to donho: #3755

**Comment by Tabiskabis** [comment]
Suggested improvement: **Yes (Silent)** could be even more silent by not opening change.log when it's done.
