### ISSUE TITLE
NPP fails to properly display certain Unicode characters unless other Unicode characters are on the same line

### ISSUE THREAD

**Issue by eisnerw** [notepad-plus-plus/notepad-plus-plus#8518]
### Description of the Issue
Many Unicode characters, such as “↵”, the "Downwards Arrow with Corner Leftwards" (U+21B5), will display as a white square “□”  UNLESS specific other Unicode characters are on the same line.  For example, if the line that contains the downwards arrow with corner leftwards also contains the 'UPWARDS ARROW' (U+2191), it will be properly displayed.  Although there are certainly others, the following characters when included on the same line will correct the issue: ↑←→↓➾➔﹐﹘﹫.  Included in that list is the "zero width no-break space" ﻿(U+FEFF).  Oddly, if a tab character appears between the improperly displayed character and the character that corrects the issue, the correction will not occur.

### Steps to Reproduce the Issue
1.  Open Notepad++ on a new blank document
2.  Copy the following from this document in the blank document: Unicode Character “↵”   
3.  Note that the arrow is displayed as a white square.
4.  Add text followed by an upwards arrow (U+2191): text ↑
5. Note that the downwards arrow is now displayed correctly.
6. insert a tab anywhere between the two arrows.
7. Note that the downwards arrow is no longer correctly displayed.

### Expected Behavior
Unicode Character “↵” 

### Actual Behavior
Unicode Character “□” 

### Debug Information
Notepad++ v7.8.7   (64-bit)
Build time : Jun  5 2020 - 02:38:56
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS Name : Windows 10 Pro (64-bit) 
OS Version : 1903
OS Build : 18362.900
Current ANSI codepage : 1252
Plugins : mimeTools.dll NppConverter.dll NppExport.dll

**Comment by dudz1978** [comment]
Same with "∃∄∈∉". Adding "↑" or "∀" (U+2200) it will display correctly.

**Comment by sasumner** [comment]
@eisnerw / @dudz1978 

Have you tried turning this on and restarting Notepad++ after you do so?:

![image](https://user-images.githubusercontent.com/30118311/110340821-abbef400-7ff7-11eb-9c5f-c7d1c43c245c.png)

**Comment by eisnerw** [comment]
That seems to fix the issue.  Seems odd that it is required in order to deal with Unicode, but so be it.  I'll close the issue

**Comment by eisnerw** [comment]
Resolved by checking "DirectWrite" in settings/preferences
