### ISSUE TITLE
Total Found and Other Counts

### ISSUE THREAD

**Issue by ghhh257** [notepad-plus-plus/notepad-plus-plus#8519]
![Display_Found_Counts](https://user-images.githubusercontent.com/67800455/86490414-38296080-bd5f-11ea-9d33-761aeedc34fb.jpg)

I recently Updated NP++ to v7.8.7 32bit
&
discovered that 
Count 
was no longer displaying the TOTAL
number of matches in the File.

To get the TOTAL I had to position the Cursor at the start of the file or Select Wrap.

I never use Wrap so this is very Cumbersome.

Please AUTOMATICALLY display the Following Counts:
Eg.
Forwards: 7 Backwards: 3 TOTAL: 10   In_Selection: 1
in
Both the Find AND the Replace Dialog boxes.
See attached IMAGE.

These counts can be done when any button is clicked on.
BUT
As soon as any Character is typed in the Find String 
or
any CheckBox is changed they will be INVALID
SO
Make the numbers RED & Label them OLD Counts.

For VERY VERY Large Files Count may be SLOW
SO
Have a CheckBox to turn Auto Counting OFF.

See attached IMAGE.

Show the Counts on a White Background 
because
BLUE & RED Text Both stand out on White.

A very elegant solution because then all users can have the count that they want.

-------------------------------------------
Also
I have to use 32bit versions because I need
HEXEDIT & ColumnSORT Plugins
is there 
any way that 64bit NotePad can use 32bit DLLs?

**Comment by sasumner** [comment]
Thanks for your input but a design decision was made to integrate the _Count_ functionality with the _Wrap around_ option.  For this case _Wrap around_ may be thought of as "Entire document".

**Comment by sasumner** [comment]
>...Count was no longer displaying the TOTAL number of matches in the File

A workaround might be to press the _Find All in Current Document_ button on the _Find_ tab (not sure why your request shows the _Replace_ tab when _Count_ is a _Find_ function, but...) with the _In Selection_ checkbox unticked.  This will show you the count of the total number of hits in the current file.
