### ISSUE TITLE
Wish: "ignore first item" command line argument (for replacing Notepad)

### ISSUE THREAD

**Issue by maphew** [notepad-plus-plus/notepad-plus-plus#852]
Please consider adding a new command line argument to NPP which says "discard the first item in the command line arguments list"

Example invocation: `notepad++.exe --isDebugger arg1 arg2 arg3`

Turns into: `notepad++.exe arg2 arg3`
# Why?

To allow replacing Notepad with Notepad++ without laboriously taking over all relevant file associations or touching system files. 
## Reasoning

The least intrusive and most light weight method to use NPP as the default text file application across the board is to use _Image File Execution Options_. This tell Windows to use notepad++.exe instead of notepad.exe any place notepad is the default action -- double clicking on _something.txt_, _foobaz.log_ for example.

Using image execution means a person can ignore [taking over file associations](http://superuser.com/a/474081/16966) (which is straightforward but involves _n_-dozen distinct changes to system and/or user defaults), and not dive into the dubious act of bypassing system files and their protective shield (rename notepad++.exe to notepad.exe and [replace all copies of notepad.exe](https://gist.github.com/amarraja/3938304) on C:).

It would also allow streamlining the thousand word explanation [Replacing Notepad](http://docs.notepad-plus-plus.org/index.php?title=Replacing_Notepad) wiki page down to 2 or three sentences and a single command

```
reg add "HKLM\Software\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\notepad.exe" /v "Debugger" /t REG_SZ /d "\"%ProgramFiles(x86)%\Notepad++\notepad++.exe\" --isDebugger" /f
```

(Even better, this single command could be added under _Settings > Preferences_ for an even smoother user experience and less documentation.)

---

Now this already works! You can use image execution right now. Try it without the made up `--isDebugger` parameter:

```
reg add "HKLM\Software\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\notepad.exe" /v "Debugger" /t REG_SZ /d "\"%ProgramFiles(x86)%\Notepad++\notepad++.exe\"" /f
```

...but it has the unfortunate side effect of opening the binary notepad.exe as a document in NPP everytime it's used.

![npp-opens-exe](https://cloud.githubusercontent.com/assets/486200/9667760/91d28956-5232-11e5-8f82-5a3f9e21a394.png)

To undo the change simply:

```
reg delete "HKLM\Software\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\notepad.exe" /f
```
### Image Execution Details

> The purpose of the "debugger" key is to automatically launch a debugger and pass the original commandline to the desired debugger. It also sets a flag on the win32 function CreateProcess that indicates this is a debugging session.
> 
> It is implied that the debugger will then call CreateProcess after modifying the arguments appropriately.
> 
>    `notepad.exe "\document1.txt"`
> 
> turns into
> 
>    `mydebugger.exe notepad.exe "\document1.txt"`

Source: http://stackoverflow.com/a/11866479/14420
## Why in core?

As is explained in the linked references, it is straightforward to create a launcher batch file or wscript which handles the discarding portion, it's even documented on the Replaceing Notepad wiki page. So why put this function in core?

Well, it's something that is wanted and used by a lot of people, and has been for a long time. Search for "[replace notepad.exe with notepad++](https://www.google.ca/webhp?hl=en#hl=en&q=replace+notepad.exe+with+notepad%2B%2B)" and see articles and forum threads going back a decade and still being talked about now. It takes something all dedicated users have to do every time they go to a new system or profile and makes it dead simple. That's worth something.

Thanks for reading this far and, I hope, considering the idea.

**Comment by maphew** [comment]
Curious, winmain.cpp contains a comment already that's about discarding the first element. Did someone already try and implement this? 

https://github.com/notepad-plus-plus/notepad-plus-plus/blame/07ce6c2516bf1fb8cc14d3bee897b39953382466/PowerEditor/src/winmain.cpp#L59

**Comment by koteq** [comment]
Some other editors implements `-z` switch to ignore next argument on CLI. I would like to get something similar in NPP too.

**Comment by dizlexik** [comment]
+1
I would very much love for this feature to be implemented so I can easily replace notepad.exe with notepad++.exe

**Comment by CookiePLMonster** [comment]
I have implemented this as a `-z` command line argument in #4620!

**Comment by donho** [comment]
@CookiePLMonster So the following command:
`notepad++.exe -z arg1 arg2 arg3`

Turns into: `notepad++.exe arg2 arg3`

Do you confirm it?

**Comment by CookiePLMonster** [comment]
Yes, that is the intent. If it does not work like this (unlikely), it's a bug.
