### ISSUE TITLE
NPP RTL: wrong path in tabs tooltip

### ISSUE THREAD

**Issue by Yaron10** [notepad-plus-plus/notepad-plus-plus#8520]
**STR:**
`Settings -> Preferences -> General -> Localization`: select a RTL language (e.g. Hebrew).
Restart NPP.
Open files `A` and `B`.
Move `A` to other view.
Hover over `A`'s tab.

**Result:**
`B`'s path is displayed in the tooltip.
***
Two more glitches in NPP RTL.

**1.**
Open one file.
Open a panel (e.g. Function List).
Hover over the file's tab.

Result:
No tooltip.

**2.**
The tabs Close button is cut off by 1px.
***
Notepad++ v7.8.8   (32-bit)
Build time : Jun 24 2020 - 00:15:36
Path : C:\---\npp.7.8.8.bin.minimalist\notepad++.exe
Admin mode : ON
Local Conf mode : ON
OS Name : Windows 7 Enterprise (32-bit) 
OS Build : 7601.23964
Current ANSI codepage : 1255
Plugins : none

**Comment by donho** [comment]
@Yaron10 
Here the test I have in **v7.9.1**:
STR:
Settings -> Preferences -> General -> Localization: select a RTL language (e.g. Hebrew).
Restart NPP.
Open files A and B.
Move A to other view.
Hover over A's tab.

Result:
B's path is displayed correctly, but there's no tooltip for A

Could you confirm it ?

**Comment by Yaron10** [comment]
@donho,

Thank you for looking into it. :+1: 
(I've been using a very non-elegant workaround).

I'm getting different results.

**STR:**
`Settings -> Preferences -> General -> Localization`: select a RTL language (e.g. Hebrew).
Restart NPP.
Open files `A` and `B`.
Move `A` to other view.
Hover over `A`'s tab.

**Result:**
Both tooltips are displayed but inverted: `B`'s path is displayed on hovering over `A` and vice-versa.

If I open the "Function List" panel (on the *left* by default in RTL), `A`'s path is displayed correctly but there's no tooltip on hovering over `B`. 
If I open the "FAW" panel (on the *right* by default in RTL), both tooltips are displayed but inverted. 

> when windows is maximized...

If you mean that NPP window is maximized, I'm getting the same results I mentioned above.
IOW: there's no difference between a maximized window and a not-maximized window.

**Comment by donho** [comment]
Thank you for your check @Yaron10 
I'll continue investigating this issue.

**Comment by Yaron10** [comment]
@donho,

Great. I appreciate it.

**Comment by donho** [comment]
```
If hWndFrom or hWndTo (or both) are mirrored windows (that is, have WS_EX_LAYOUTRTL extended style) and precisely two points are passed in lpPoints, MapWindowPoints will interpret those two points as a RECT and possibly automatically swap the left and right fields of that rectangle to ensure that left is not greater than right....
```
(ref: https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-mapwindowpoints)
I used 
`MapWindowPoints(NULL, _pPublicInterface->getHSelf(), &p, 1);`
instead of 
`::ScreenToClient(_pPublicInterface->getHSelf(), &p);` in https://github.com/notepad-plus-plus/notepad-plus-plus/blob/master/PowerEditor/src/NppNotification.cpp#L920

But result is the same. 
If anyone have the solution, please let me know.

**Comment by Yaron10** [comment]
@donho,

Thank you for trying to fix it. :+1: 
So we have a "known-issue". The best applications do. :)
