### ISSUE TITLE
[Feature Request] Enhance usefulness of status bar's "Sel :" area

### ISSUE THREAD

**Issue by sasumner** [notepad-plus-plus/notepad-plus-plus#8524]
### Description of the Feature Request

The `Sel :` area of the status bar is currently only useful in one situation:  

When I have a single stream selection it will show me the number of characters in my selection and the number of lines that my selection touches.  

**_Example 0_**: `Sel : 25 | 2` for 25 characters selected on two lines.
This is a good feature.

But what about when I have other types of selection situations?

**_Example 1_**: 
Multiple selections (after enabling _Multi-Edit Settings_ in the _Preferences_).

Result 1: 
In the status bar I see `Sel : N/A`
Not terribly useful.

**_Example 2_**:
Rectangular selections after selecting a column-block via Shift+Alt+arrows or Alt+LClick+drag.

Result 2:
In the status bar I see `Sel : N/A`
Not terribly useful.

**_Example 3_**:
One selection of zero characters; the normal single-carat situation.

Result 3:
In the status bar I see `Sel : 0 | 0`
Not terribly useful.

Wouldn't it be super if Notepad++ could display useful information for these situations?

Additionally, there is an off-by-1 error in the current output of the number of lines touched by a single selection; this should be corrected during any revamping of `Sel :` status bar functionality; for reference see https://community.notepad-plus-plus.org/topic/13087/sel-in-status-bar-is-off-by-1-on-line-count

### Expected Behavior

I expect to be shown some useful information in all types of selection situations.

### Actual Behavior

Described above.

### Debug Information

Reference version:

Notepad++ v7.8.8   (32-bit)
Build time : Jun 24 2020 - 00:15:36
Path : C:\\...............\npp.7.8.8.bin\notepad++.exe
Admin mode : OFF
Local Conf mode : ON
OS Name : Windows 10 Enterprise (64-bit)
OS Version : 1809
OS Build : 17763.1039
Current ANSI codepage : 1252
Plugins : mimeTools.dll NppConverter.dll NppExport.dll

### Other

I decided to create a new and very specific issue for this based upon prior discussion in other issues:

* https://github.com/notepad-plus-plus/notepad-plus-plus/issues/8447#issuecomment-647110458
* #7716

**Comment by Yaron10** [comment]
@sasumner,

:+1: :+1: :+1: 
Please share anyway. :)

**Comment by sasumner** [comment]
@donho 
Is there a reason for "suspended" label?
Has this sort of thing been implemented before and caused performance problems? (That's the only thing I can think of, for not implementing something here).
I'll go ahead with a PR anyway so that those interested can patch their buildable copies.

**Comment by donho** [comment]
@sasumner Just want to make sure the behaviour before you implement it.
So what do you suggest as display for the following selection :
![image](https://user-images.githubusercontent.com/90293/86515548-f4dff800-be19-11ea-84d5-7f89c5e52414.png)

**Comment by sasumner** [comment]
@donho 

Here would be the plan:

For **_Example 0_**:  No change to existing behavior

For **_Example 1_**: From the @donho example above, display: `Sel (3) : 25 | 4` (3 selections covering 25 characters on 4 lines)

For **_Example 2_**:

![image](https://user-images.githubusercontent.com/30118311/86517804-b8040900-bdf9-11ea-8d17-5cea6796a7ea.png)

Would show `Sel : 4 x 3 = 12`.
Separate display of lines like Example 0 and 1 is not necessary because this is expressed by the `4` here.

![image](https://user-images.githubusercontent.com/30118311/86517845-1cbf6380-bdfa-11ea-9e25-57384a99932f.png)

Would show `Sel : 4 x 3? = 9`

This is because line 9 is empty and thus in the column block that part contributes 0 characters.
Overall in the selection there is 9 characters, not 12.
The `?` would be shown if there are any "virtual space" in the selection.
I could not think of a better way to express this; open to suggestion.

For **_Example 3_**:

With no selection active, just a single caret, instead of showing `Sel : 0 | 0` which the user already knows, change to showing current position, like this: `Pos : 1,234`.
This is SCI_GETCURRENTPOS plus 1.

**Comment by donho** [comment]
`Sel 3 : 25 | 4` instead of `Sel (3) : 25 | 4` will save more room.
`Sel : 4 x 3 = 12.` is quite easy to understand. but `Sel : 4 x 3? = 9` will be confusing.
Is it possible to create a tooltip for the explanation?

**Comment by sasumner** [comment]
@donho said:

>Sel 3 : 25 | 4 instead of Sel (3) : 25 | 4 will save more room.

OK, I will implement that.

>but Sel : 4 x 3? = 9 will be confusing.

"Virtual space" **_IS_** confusing. :-)
I agree it isn't the best notation.
Let's try to find something better, rather than trying to do a tooltip.
How about removing the "math" look of it, and do this?:

`Sel 4x3 : 12` 
(no virtual space in block)

`Sel 4x3 : 9`
(some virtual space in block)

**Comment by Yaron10** [comment]
> For Example 1: From the @donho example above, display: Sel (3) : 25 | 4 (3 selections covering 25 characters on 4 lines)

Was `Sel (3)` a typo? - There are 4 selections there.

My personal opinion on the format:
The user is used to seeing `Chars | Lines`. It would be less confusing if you retain this and add `(x)` at the end.

`Sel : 4 x 3? = 9` would be highly confusing even with a tooltip.

How about `Sel : Chars | lines | Columns (R)`? (`R` = Rect). 

Ctrl/Alt + left-single-click would display Pos, correct?

**Comment by sasumner** [comment]
@Yaron10 

>Was Sel (3) a typo? - There are 4 selections there.

No, only 3 selections in the donho example.  The `ago. Beat` selection is ONE selection, starting on line 1 and continuing onto line 2.

>The user is used to seeing Chars | Lines

Yes, but that is _after_ the `:`.
Putting the number of selections before the `:` allows a more natural, left-to-right reading (sorry RTL people):
`Sel 3 : 25 | 4`
"There are 3 selections containing 25 characters and touching 4 lines"

>Sel : 4 x 3? = 9 would be highly confusing even with a tooltip.

Agreed.  Already abandoned. :-)

>Ctrl/Alt + left-single-click would display Pos, correct?

I would like Alt+Lclick to show me that I am in column mode even though I have no selected characters.  I like this simply because it **_IS_** different from stream selection mode with a single caret (Scintilla recognizes it) and I'd like to know this (as a PythonScript programmer).  Visually, these situations appear the same to the user, caret-wise.  In current 7.8.8 N++, these two situations cause one of them to display `Sel : 0 | 0` and the other `Sel : N/A`.

Regarding Ctrl+Lclick, for multiple carets, for example:

![image](https://user-images.githubusercontent.com/30118311/86531447-4bd3e480-be8f-11ea-924d-9e6cb8da44d0.png)

we would see `Sel 3 : 0 | 0` because there is 3 selections.  Scintilla says so.  :-)
Actually maybe that should be `Sel 3 : 0 | 2` because there are 3 carets on TWO different lines.  Hmm.

**Comment by Yaron10** [comment]
> No, only 3 selections in the donho example. The ago. Beat selection is ONE selection, starting on line 1 and continuing onto line 2.

My bad. :)

> Yes, but that is after the :.
Putting the number of selections before the : allows a more natural, left-to-right reading (sorry RTL people):
Sel 3 : 25 | 4
"There are 3 selections containing 25 characters and touching 4 lines"

Nothing to do with LTR/RTL.
`:` is not just a separator. 
It should be **next to** the "title" `Sel`.
It's like putting `:` in the middle of an article instead of at the end of the title.

`Sel 4x3 : 12` is still confusing IMO.

> I would like Alt+Lclick to show me that I am in column mode...

OK.

> Actually maybe that should be Sel 3 : 0 | 2 because there are 3 carets on TWO different lines. Hmm.

Yea. :)

**Comment by sasumner** [comment]
@Yaron10 said

>Nothing to do with LTR/RTL.

Correct, I was making a joke.  Sorry.

The number of selections to the left of the colon makes sense if it is parenthetical.
It makes less sense when parens are removed, except it makes total sense because donho liked it that way. :-)
I can live with it.

**Comment by Yaron10** [comment]
> Correct, I was making a joke. Sorry.

No problem at all.

> The number of selections to the left of the colon makes sense if it is parenthetical.
It makes less sense when parens are removed, except it makes total sense because donho liked it that way.

There's a rumor that even Don might change his mind. :)

**Comment by sasumner** [comment]
@donho 
@Yaron10 

Perhaps the best thing now is to jump to a PR where it can actually be run and tried.
From there we either make changes, or we kill it.

**Comment by donho** [comment]
@sasumner 
> "Virtual space" IS confusing. :-)
I agree it isn't the best notation.
Let's try to find something better, rather than trying to do a tooltip.
How about removing the "math" look of it, and do this?:

We can invent all the the symbols, it'll always be confusing.
But let's do it without tooltip firstly. 
For the multi-column selection, I prefer:
`Sel : 4 x 3 = 12`
`Sel : 4 x 3 = 9`

`?` for me makes more confusion, so make it simplest then users may figure it out.

**Comment by donho** [comment]
> Perhaps the best thing now is to jump to a PR where it can actually be run and tried.
From there we either make changes, or we kill it.

Are there a lot of codes for this implementation?

**Comment by sasumner** [comment]
>Are there a lot of codes for this implementation?

No.

**Comment by sasumner** [comment]
I encountered a problem not easily solved:

Create this situation:

![image](https://user-images.githubusercontent.com/30118311/86607639-831dc080-bf77-11ea-9a6f-bc3bccc6e760.png)

by making the selections in the following order (IMPORTANT!):

- abcde
- bcdef
- cdefg
- defgh

This should report 4 selections of 20 characters on 2 lines : `Sel 4 : 20 | 2`

Instead, due to the order of selection by the user, it reports `Sel 4 : 20 | 4`

For this situation, I propose dropping the line data part and reporting only: `Sel 4 : 20`

If user makes selections in this order:

- abcde
- cdefg
- bcdef
- defgh

Then `Sel 4 : 20 | 2` could be shown.

What's the feeling about this?

**Comment by Yaron10** [comment]
@sasumner,

I think this PR is important and was hoping your work here should be resumed.

> What's the feeling about this?

I assumed you were addressing Don.

How about `Sel 4 : 20 | ?`?

**Comment by sasumner** [comment]
>your work here should be resumed

Yea.  :-)
It hit some implementation snags.
Some parts of it may be "computationally intensive" on large files.
I haven't forgotten about it, just set it aside for a time, as it didn't turn out to be simple and easy to submit like I first thought.

**Comment by Yaron10** [comment]
:+1: 

> I think this PR is important and was hoping your work here should be resumed.

I didn't mean to push you.
I just wanted to emphasize it was important IMO and did not reply to your last question because I assumed you were addressing Don.

Anyway, good luck with your work on it and thank you.

**Comment by Yaron10** [comment]
@sasumner,

Thanks again for your great work.

Don would probably still approve some parts of it: the correct number of selected lines and displaying "Pos".
What do you think?

**Comment by sasumner** [comment]
@Yaron10 

First, I'm going to work on it so that no existing features of it have to be "dropped".
Let's not think beyond that...yet.
But yes, I agree that even if it were only the `Pos` part that we can get adopted, that would still be great.

**Comment by Yaron10** [comment]
@sasumner,

I appreciate the perseverance. :)

Thank you and best of luck.

**Comment by sasumner** [comment]
@Yaron10 @Ekopalypse and any other interested parties:

When reworking this, I discovered some interesting things.
For one thing, selecting certain characters into a rectangular block can cause, for example, 2 characters to be selected on one line and only one character on another line:

![image](https://user-images.githubusercontent.com/30118311/92786300-1f988080-f376-11ea-97ce-3146e32c77d6.png)

In the block shown above there are 2 characters selected on line 8 and only one selected on line 10; line 9 is empty so only virtual space is "selected" there.

So this raises some interesting questions about how that should be represented in any enhanced status bar output.  In my early thinking I am leaning towards:  `Sel : 3x? 🡢 3` where the `?` is basically saying "I don't know what to say, I've got 2 chars on one line of the block, 1 character on another, so, how wide is this block?"

Tab characters provide a challenge as well.
Start with caret at start of line 3.
Press Shift+Alt+down once and then Shift+Alt+right twice to get 0 chars selected on line 3, 2 sel. on line 4:
![image](https://user-images.githubusercontent.com/30118311/92787405-122fc600-f377-11ea-8193-ad62425d457e.png)

Press Shift+Alt+right once more to obtain (for tab=4spaces setting) 1 char selected on line 3, 3 sel. on line 4:
![image](https://user-images.githubusercontent.com/30118311/92787613-40150a80-f377-11ea-97c8-cc6b6ddab06e.png)

Again, what is the width of these blocks with inconsistent widths?

I'm looking for suggestions to modify the already Don-approved output format as little as possible to fit these situations, not a whole-scale rework of the output format.

Here's the actual data file I used for the above, for anyone that wants to experiment:
[u.txt](https://github.com/notepad-plus-plus/notepad-plus-plus/files/5204097/u.txt)

**Comment by sasumner** [comment]
Some situations seem a bit odd, too, for example:

![image](https://user-images.githubusercontent.com/30118311/92801197-66d93e00-f383-11ea-877b-fff438cc10d8.png)

To me this is clearly a 3-line selection of zero columns, but putting the info gleaned from Scintilla back together shows a 3-line selection of ONE column.  Blame is placed upon line 10 for this, as having the same basic selection only touch lines 8 and 9 yields a zero-width column selection.

I'm at a loss as to what to do with such a situation.

**Comment by Yaron10** [comment]
@sasumner,

A busy day. I'll try it tomorrow.

**Comment by Yaron10** [comment]
@sasumner,

> For one thing, selecting certain characters into a rectangular block can cause, for example, 2 characters to be selected on one line and only one character on another line:

Testing it the other day, I happened to select the following block:

![תמונה](https://user-images.githubusercontent.com/10229320/92919735-b1b58d00-f439-11ea-8e9c-d7ad56ed2b44.png)

![תמונה](https://user-images.githubusercontent.com/10229320/92920063-52a44800-f43a-11ea-9c87-2bf856f621b3.png)

I interpreted it as follows: `4 (vertical) x 8 (max-horizontal) [] 30`.
I thought it was clever because the "block width" should indeed be determined by max-horizontal.
And you do indicate the selected columns number is not the same in all lines by using `[]` (the rectangle).
(Think about the "`Lines Margin` width" set according to the largest number).

Testing your examples (and other cases) now, I realize this was NOT the poet's intention.
But I think it should be. :)

*Drawing a block would result in most cases in a not-even width.*
Unless you draw it in a block like:

```
#include
#include
#include
#include
#include
#include
#include
#include
#include
#include
#include
#include
#include
#include
#include
```

> line 9 is empty so only virtual space is "selected" there.

I don't quite understand it. Why shouldn't the EOL character(s) be included in the selection?
If the rect is drawn *beyond* the EOL, you have 2 (or 1) legit character(s) and the rest is "virtual".

> To me this is clearly a 3-line selection of zero columns
...
Blame is placed upon line 10 for this, as having the same basic selection only touch lines 8 and 9 yields a zero-width column selection.

I get a different result.
Selecting only 8 and 9:

![תמונה](https://user-images.githubusercontent.com/10229320/92923261-d44aa480-f43f-11ea-993c-0a38fe3589fa.png)
(Note the one char selected in line 9).

![תמונה](https://user-images.githubusercontent.com/10229320/92923310-f04e4600-f43f-11ea-8e2b-2fc0aa94885b.png)

**Comment by sasumner** [comment]
>Why shouldn't the EOL character(s) be included in the selection?

I'll answer this one quickly and separately, because it isn't related to the rest of the discussion.

In a column block, EOL characters are NEVER included in the block.
Turn on the "Show end of line" feature.
Try selecting various column blocks.
Note that the visible line-endings will always move to be outside of your intended block.

Now, if your "why" question is one with deeper roots, I don't have all the answers.
Maybe: Scintilla folks decided that this was how it should work.
It seems to make sense to me as well, although I haven't thought very deeply about it to convince myself.

**Comment by sasumner** [comment]
@Yaron10 

So this is how it appears for you?:

![image](https://user-images.githubusercontent.com/30118311/92927275-5b315a00-f40b-11ea-95d6-09cb6125ffdb.png)

With a "box" instead of a right-pointing arrow?
So I used a "Unicode" right arrow character for this, but if it isn't going to work for everyone and show as a right-arrow, then I suppose I need to "back off" and do it the old ASCII way, with `->`

**Comment by sasumner** [comment]
@Yaron10 

What font are you using here, so that I can test the same way?:

![image](https://user-images.githubusercontent.com/30118311/92927606-e874ae80-f40b-11ea-929f-bd2ec59cfe98.png)

>Drawing a block would result in most cases in a not-even width.

Don't most people use a monospaced font while text editing?
I'm not sure if column-blocking mode is useful (or makes sense) when a non-monospaced font is used.

**Comment by Yaron10** [comment]
> In a column block, EOL characters are NEVER included in the block.
Turn on the "Show end of line" feature.
Try selecting various column blocks.
Note that the visible line-endings will always move to be outside of your intended block.

I've noticed that too.
But if you copy and paste it in a new document, you do get an empty line (with EOL).
And therefore it should be included in the selection IMO.

> So this is how it appears for you?

Yes.
This is funny. I complimented you on this idea (and you wrote it was Don's) thinking that was the poet's intention. :)
The box is actually great: I interpreted it as a "block".

> What font are you using here?

Tahoma.

> I'm not sure if column-blocking mode is useful (or makes sense) when a non-monospaced font is used.

I've actually never used it in "real life". Only for testing. :)

**Comment by sasumner** [comment]
>But if you copy and paste it (a column-block) in a new document, you do get an empty line (with EOL).

Yes, but this is because the paste is a bit special.
If you're curious about the details, look in Scintilla code for `MSDEVColumnSelect` and/or `Borland IDE Block Type`

>block

I don't know that a block makes much sense.
Since Don came up with the arrow idea, as I said, I will change it to `->` so it should appear the same on all systems.

>non-monospaced

I was ignoring non-monospaced fonts intentionally for this effort (the column block part), figuring that it would be a "whatever effect you get from Scintilla when you dare to use such a font".

But the "Unicode" characters used in my earlier example (along with a monospaced font) seem to yield effects that are similar (yet worse) than when using a non-monospaced font.  As was said before, not sure how to proceed.  Do we just ignore these effects?

**Comment by Yaron10** [comment]
> I was ignoring non-monospaced fonts intentionally for this effort (the column block part), figuring that it would be a "whatever effect you get from Scintilla when you dare to use such a font".

I think it's important to remember and mention it when you re-submit the PR. I suppose I'm not the only one who doesn't like "Courier New".

> As was said before, not sure how to proceed. Do we just ignore these effects?

"max-horizontal"?

**Comment by sasumner** [comment]
>"max-horizontal"?

Maybe.
Maybe just to get this feature "done" and over with.
It started out as a desire to make something useful, and has turned out, well, to have "interesting" aspects. :-)

>Courier New

_Nobody_ really likes Courier New. :-)
I used Consolas for a long time, my latest choice is Fira Code

**Comment by Yaron10** [comment]
>    "max-horizontal"?
...
Maybe.

If you do implement it that way, would it work with non-monospaced fonts too?

> It started out as a desire to make something useful, and has turned out, well, to have "interesting" aspects.

It's still nice and useful. Just another hurdle. :)

I don't have "Fira Code" installed. I've gotten used to "Tahoma".

**Comment by sasumner** [comment]
>If you do implement it that way, would it work with non-monospaced fonts too?

Well, it is all about what Scintilla gives the N++ coder, isn't it?
Meaning, the code on the N++ side doesn't know if the selected font is mono/non-mono.
So the selection in column block mode is all about what Scintilla decides it should be.
If, for the normal "a to z", mono case, we get an N x M block, where M is the same on every line, then I say that is great, and yes, it is super useful, hooray!
But, for other cases, if we get, something where M varies per line, then I'm not sure of the value in trying to present N x M, if M is some sort of "maximum"...I just think it could be confusing rather than useful.

**Comment by Yaron10** [comment]
But if you use `->`, the user would get it. Eventually.

**Comment by sasumner** [comment]
So I've decided that in "normal" column blocking situations, Scintilla gives you perfectly expected and normal results for the width of a column block.
In other situations, some discussed above, but some others, not mentioned, e.g. something created with Pythonscript:

`editor.setRepresentation('z','absurdlyLongThingRepresentingZ')

The results just aren't really sensical.
At least to be useful for the application this issue is discussing.

So, I'm going to take the suggestion to get the "maximum" column width (on a line in the block) reported by Scintilla and report that out, using the `->` syntax.
We'll see how that goes...

**Comment by Yaron10** [comment]
@sasumner,

> If you do implement it that way, would it work with non-monospaced fonts too?
...
Well, it is all about what Scintilla gives the N++ coder

I've just tested PR 8876 with a non-monospaced font, and the "max ->" solution seems to work as expected. Is that correct?

Good luck with the second try. :)

**Comment by Yaron10** [comment]
I've noticed an interesting phenomenon:

Select a rect and keep both Alt and the mouse-left-button pressed for a few seconds.
-- Without PR 8876: the Ln/Col/Sel section is constantly being updated and flickering but the length/lines section is "stable".
 -- With PR 8876: the Ln/Col/Sel is "stable" (:+1:) but the length/lines section is constantly being updated and flickering.

**Comment by sasumner** [comment]
>I've noticed an interesting phenomenon

I see no flickering for EITHER case.
Indeed, it makes no sense because the logic fires based upon an update-ui notification from Scintilla.
If there is "nothing happening" (as implied by your description--just a "holding"), I see no reason for this notification to be sent.
But now I will go and look further... :-)

**Comment by sasumner** [comment]
>But now I will go and look further... 

Well, in this case Scintilla keeps sending the notifications even though nothing is changing.
That seems like a bug on the Scintilla side, although I haven't seen what actual harm it could do.

**Comment by Yaron10** [comment]
The flickering on my machine is quite noticeable.

> although I haven't seen what actual harm it could do.

Possibly Improve performance.

Your following code does that for the Sel segment.
```
		       bool selectionIsChanged = (notification->updated & SC_UPDATE_SELECTION) != 0;
			// note: changing insert/overwrite mode will cause Scintilla to notify with SC_UPDATE_SELECTION
			bool contentIsChanged = (notification->updated & SC_UPDATE_CONTENT) != 0;
			if (selectionIsChanged || contentIsChanged)
			{
				updateStatusBar();
			} 
```

How about checking if `updateStatusBar();` should be called for the length/lines segment?
(Add a `whichPart` parameter to `updateStatusBar();`?).

**Comment by sasumner** [comment]
>Your following code does that for the Sel segment.

Not for the `Sel` segment only, but rather the whole status bar.

The code you cited removes from consideration the other 2 types of updated notifications: horizontal or vertical scrolling after a selection(s) is made.  There is no point in updating the status bar if the user is purely scrolling, as nothing on it needs to be updated.  That's all this code is doing.

>How about checking...

Well, there are probably still performance gains to be made (or lost :-) ) here.
The PR, as submitted, I thought addressed the performance complaint with the earlier PR, and that was my goal here -- to get something acceptable, meaning to provide the new information without a noticeable performance impact.

I'm not sure how far I'm willing to go with it.
Example:  Who's performance problem is it when "fast" careting through an xml document?  Just because this code is new, is it the culprit for all performance problems?  Maybe the lexing is slow and eats up the performance budget.  If this code came first, then maybe other code is blamed for being slow. :-)

**Comment by Yaron10** [comment]
> Not for the Sel segment only, but rather the whole status bar.

You're right.

> The code you cited removes from consideration the other 2 types of updated notifications: horizontal or vertical scrolling after a selection(s) is made. There is no point in updating the status bar if the user is purely scrolling, as nothing on it needs to be updated. That's all this code is doing.

And it also makes the Ln/Col/Sel segment "stable" in the case I mentioned above (keep both Alt and the mouse-left-button pressed for a few seconds).

I still don't understand why the flickering segment changes with and without your PR. Well.

> I'm not sure how far I'm willing to go with it.

:+1:

Thank you.

**Comment by sasumner** [comment]
>I still don't understand why the flickering segment changes with and without your PR.

I'm with you.
Since it is just one function that updates both sections, you'd think either they would both flicker, or neither would.
But since I see no flickering in either case...I can't comment more with much certainty.

**Comment by Yaron10** [comment]
FWIW:
Moving the length/lines segment to the beginning of `updateStatusBar();`, that section is flickering.
IOW: the *first* segment  in the function is flickering.
(Without your PR).
