### ISSUE TITLE
'Find in Files': Not possible to jump to every single hit in certain cases

### ISSUE THREAD

**Issue by tstone-1** [notepad-plus-plus/notepad-plus-plus#8525]
### Description of the Issue

When using 'Find in Files', Notepad++ will find all occurrences of the string of interest. However, it is not possible to open the respective files from the list of hits, jumping to the particular occurrence.

### Steps to Reproduce the Issue

1. Within a folder `mwe`, create a file `mwe.tex` containing
```
Aryl-Aryl

Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Aryl-Aryl.

Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Seit dem ersten Bericht über Nickel-katalysierte \ac{SMC}-Reaktionen 1995 von Percec \textit{et al.}\supercite{Percec1995} hat sich diese Reaktion durch stetige Fortentwicklung für viele Anwendungen zu einer effizienten Alternative zur klassischen Palladium-katalysierten Aryl-Aryl-Kreuzkupplung entwickelt.\supercite{Han2013,Tasker2014} Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet.
```

2. Use 'Search' -> 'Find in Files' to search for 'aryl-aryl' with filter `*.tex` within the folder `mwe`. Three occurrences will be found. Double-clicking the three occurrences will highlight the corresponding 'Aryl-Aryl' string.

3. Another
```
Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet.
```
is appended to line 5 and the file is saved. Now, 'Search' -> 'Find in Files' is run again using the same settings as before. Again, there will be three hits. The first two can be double-clicked, causing Notepad++ to jump to the respective occurrences.

### Expected Behavior
When the third line is double-clicked, 'Aryl-Aryl' within line 5 is expected to be highlighted. 

### Actual Behavior
However, double-clicking the third hit will not highlight the occurrence of 'Aryl-Aryl' within line 5.

### Debug Information

Notepad++ v7.8.8   (64-bit)
Build time : Jun 23 2020 - 23:59:56
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS Name : Windows 10 Pro (64-bit) 
OS Version : 2004
OS Build : 19041.329
Current ANSI codepage : 1252
Plugins : mimeTools.dll NppConverter.dll NppExport.dll XMLTools.dll 

I made a video of what I've been doing here, see: http://yeticave.de/2020-07-0413-48-54.xxx ; replace xxx with mkv to download the file. I've tried to track this down to the most minimal example I'm able to produce right now. I've been observing this issue for quite a long time now - I'm writing on a LaTeX document with multiple inputs and use the 'find in files' method quite often to find a particular part of the code. However, in many cases, I can't open a file containing a specific occurrence from Notepad++ and have to open the file manually from explorer, using CTLR + F afterwards.

**Comment by sasumner** [comment]
When I do step 2, for me, double-clicking the Line 5 result doesn't cause Notepad++ to move the editor window to the correct place.  I don't need to move on to step 3 for any reason to see it.  Not sure if this is what you were trying to say or not...

**Comment by tstone-1** [comment]
As you can see in the video, the editor window can be moved to the hit within line 5 in step 2 - at least for my part. Tried to track this down and had a look at lines of differing length, possible influences of umlaut characters as well as \ and { - but didn't succeed yet.

Yes, this is about Notepad++ not moving the editor window to hits under certain circumstances. It will then not open the corresponding file (if it's not open already), not jump to the line of occurrence and also not highlight the corresponding string.

**Comment by sasumner** [comment]
>As you can see in the video

For me, I can't see the video, as I'm blocked from certain sites.  It's the way of things now, I suppose.
But, since I can replicate the issue, I don't think the video matters much.

**Comment by sasumner** [comment]
Here's a weirdness:

![image](https://user-images.githubusercontent.com/30118311/86523129-cb34ca00-be35-11ea-81f0-abce5e74574d.png)

So if you run this search once after you start up Notepad++, all works good (bottom results in the above).  However, running it again once or twice results in the problem described by OP.  I think it has something to do with the fold lines, see the highlight in yellow.

Also, when running the second search, the results from the first search should collapse, and that is no longer happening.  Same for the third search (the results from the second should collapse, and the first result should also remain collapsed).

**Comment by sasumner** [comment]
This is a long-standing problem.  I tried back to N++ 6.7.5 and the same issue exists there.

**Comment by sasumner** [comment]
>possible influences of umlaut characters 

I definitely see different behavior if I remove the two occurrences of `ü` from the data.

**Comment by tstone-1** [comment]
I'm also working on UTF-8 encoded files here.
Thanks for looking into this... I guess I can't assist you here. Let me know if there's anything I can contribute.

Another observation/opinion: While the 'Find in Files' functionality is really useful - though, slightly defective at present for me - occurrences of the search term within longer lines are not conveniently represented. As you can see from your screenshot above, the occurrences of 'Aryl-Aryl' within lines 8 and 10 are way outside of the text that's shown at the beginning of the lines. The highlighted parts in orange colour are simply not shown as it is the case for the hit in line 6. It would be very helpful (for me, maybe also for others?) to have the displayed part active here. Usually, when I search for 'Aryl-Aryl', I want to see what precedes 'Aryl-Aryl' and what trails 'Aryl-Aryl'. To do so, one has to double-click the line 8 and 10 matches, respectively.

**Comment by sasumner** [comment]
>occurrences of the search term within longer lines are not conveniently represented.

I agree...it's a tough design goal, though.
It could be done as:
`... some-text-before-hit THE-HIGHLIGHTED-HIT some-text-after-hit ...`
where `...` are really just that, 3 dots.
But then you get into, well _how_ much text before and after the HIT, and if the hit text is "long", well..., and then you have to take into account user's window width potentially...
I'm not saying it is impossible, it's just I've yet to see an all-encompassing design that makes awesome sense.  :-)

**Comment by sasumner** [comment]
>occurrences of the search term within longer lines are not conveniently represented.

Another possibility (with its own drawback of potentially consuming a lot of vertical space) would be to allow results to be "word-wrapped" in the _Find result_ area, e.g.:

![image](https://user-images.githubusercontent.com/30118311/86599384-911a1400-bf6c-11ea-8a0e-0653e985dbc3.png)

**Comment by guy038** [comment]
Hi, all,

Concerning the **issue**, see my post on **N++ Community** :

https://community.notepad-plus-plus.org/post/58596

Hope that helps a bit !

BR

guy038
