### ISSUE TITLE
Folder as workspace does not accept drag-drop folders

### ISSUE THREAD

**Issue by dvdvideo1234** [notepad-plus-plus/notepad-plus-plus#8531]
### Description of the Issue
I am dragging a folder over the `Folder as workspace` ( `FaW` ) window, but the folder structure is not added in the window

### Steps to Reproduce the Issue
1. Install the latest version of NPP on `D:\`
2. Check `Don't use %AppData%`
3. Run NPP and open `View` `>>` `FaW`
4. Drag and drop [the cloned repository][1] in the `FaW` window
5. The folder is not added

### Expected Behavior
The folder should be added to `FaW` including its subfolders and files

### Actual Behavior
The folder is not added to `FaW` including its subfolders and files. Nothing happens when the folder is dragged then dropped.

### Debug Information
Notepad++ v7.8.8   (64-bit)
Build time : Jun 23 2020 - 23:59:56
Path : D:\Notepad++\notepad++.exe
Admin mode : ON
Local Conf mode : ON
OS Name : Windows 7 Ultimate (64-bit) 
OS Build : 7601.24546
Current ANSI codepage : 1251
Plugins : mimeTools.dll NppConverter.dll NppExport.dll 

![image][3]

![image][2]

[1]: https://github.com/dvdvideo1234/WindowsBatches
[2]: https://user-images.githubusercontent.com/9112662/86579104-83bd5380-bf85-11ea-82ee-921ea1b6f22d.png
[3]: https://user-images.githubusercontent.com/9112662/86579606-37bede80-bf86-11ea-9613-82ed2b21a2c6.png

**Comment by dvdvideo1234** [comment]
`Right click` and `Open with NPP` is not working too. I have to browse yo the file and open it with `File` > `Open`

**Comment by sasumner** [comment]
>Right click and Open with NPP is not working too. I have to browse yo the file and open it with File > Open

Is that related to the Faw thing reported above?

**Comment by dvdvideo1234** [comment]
@sasumner Nope. The error is present when you do:
1. Right click
2. `Edit with NPP`

**Comment by sasumner** [comment]
@dvdvideo1234 

>Right click and Open with NPP

We don't get too worked up about weirdness with that anymore.
M$ keeps messing with how it works in Windows.
Hard to keep up.

> I just thought I should let you know.

Best to do unrelated things in separate issues.
But...for that one there are I'm sure already multiple existing issues for it.

**Comment by dvdvideo1234** [comment]
@sasumner. I am pretty sure that Windows 7 taha is outdated this 14-th of january will be not changed that much :D

**Comment by dvdvideo1234** [comment]
@sasumner

The feature `Folder as workspace` `DOES NOT` work when the folder is dragged and then dropped on `FaW` rectangle. However it `DOES` work when you click `Add`, browse for a solder, in the folder section paste the path to your folder ( I pasted `E:\GIT\WindowsBatches` ) and appears to be displayed correctly. 

Why does the folder is not added with `drag-drop`, but it works with `right-click` and then context menu `add` ?

**Comment by sasumner** [comment]
@dvdvideo1234 
Ummm, I'm guessing (I haven't checked) that it is because no code was written to support drag-and-drop opening here?

**Comment by dvdvideo1234** [comment]
@sasumner

It appear so, but it works on the x86 version. That's why it looks weird to me as this feature must not got lost when you increase CPU registers size.

I maj be mistaken though, may be it is not implemented in the x64 version.

**Comment by sasumner** [comment]
@dvdvideo1234 
I think I see your problem.
You are running Notepad++ in administrator mode; I can sort of see it in your screenshot:
![image](https://user-images.githubusercontent.com/30118311/87259737-76b7cd00-c47b-11ea-8aae-c6397a555f60.png)
Your Explorer that you are dragging from is likely not in admin mode, thus for security reasons this type of drag-n-drop operation is not permitted.
Regardless, I tried drag-n-drop to FAW in 7.8.8 in both 32 and 64 bit versions and it worked fine; I'm going to go ahead and close this, but if you want or need to add any further comments, feel free.

**Comment by dvdvideo1234** [comment]
I have right-clicked on the `exe` ( Not the shortcut, It is different ) and selected `Run as Administrator`. I already stated that I am running NPP with the [described settings](https://github.com/notepad-plus-plus/notepad-plus-plus/issues/8531#issue-651396642)  ( Local configuration not using `%Appdata%` noted ). To me running a program in general with administrator rights means that you are granting all kinds of access to it including directory browsing. Correct me if I am wrong, but should it be the default for this to just add the folder to the `FaW` being the same as clicking `Add`. I am assuming these two call different parts of the code and if so, can one be reused will result in less floppy behavior like this.

**Comment by sasumner** [comment]
> I already stated that I am running NPP with the described settings 

Ah, yes, sorry I missed that your Debug Info shows N++ in Admin mode.

>To me running a program ... with administrator rights means that you are granting all kinds of access to it 

I look at it this way:

A program with few rights (a non-elevated Explorer) is trying to tell a program with many rights (an elevated N++) to do something.  N++ says "No, I'm not doing it, because I don't respect you" although it refuses very quietly by just not doing the action instead of putting up an error message.

If you try the same type of thing with Windows' own `Notepad.exe` (an elevated instance) you will see the same behavior when trying to drag-and-drop open a file from a non-elevated Explorer.

**Comment by dvdvideo1234** [comment]
Ah... Thank you. That makes sense. Although I can use the `ADD` option provided, I can also remove the admin rights from NPP, start it, drag-drop the folder into `FaW`, collapse all folders and hit `File` > `Exit`. Run NPP in Admin mode and the folders stay added.
