### ISSUE TITLE
Save the attributes in "Column Editor" (Alt+C) options and hold resetted every relaunch

### ISSUE THREAD

**Issue by mlatushko** [notepad-plus-plus/notepad-plus-plus#8549]
### Steps to Reproduce the Issue
1. Use a "Column Editor"
2. Relaunch the program
3. Use a "Column Editor" again

### Expected Behavior
Start with simple default parameters:

| ☑ Number to Insert
| Initial number : 1
| Increase by : 1
| Repeat : ☑ Lead zeros

### Actual Behavior
Requires to activate/fill options again.
![2020-07-10_015742](https://user-images.githubusercontent.com/23335312/87098809-daaa7d80-c250-11ea-9a64-188219c734e0.png)

**Comment by sasumner** [comment]
Thank you for your suggestion but it is something we've decided isn't worth remembering from run to run.
