### ISSUE TITLE
Compare with empty document crashes

### ISSUE THREAD

**Issue by juef17** [notepad-plus-plus/notepad-plus-plus#855]
Greetings,

Under certain conditions, NPP crashes quite badly (and doesn't succeed in dumping pertinent info). The crash can be reproduced by following these steps:

1) Open a NPP instance, with only an empty document window.
2) Write some stuff in that document (anything, really).
3) CTRL+N for a new empty document.
4) Switch back to the original document in which something was written.
5) Plugins -> Compare -> Compare

I have tested this on NPP v6.8.2, but it also happens with v6.7.7 and perhaps earlier. I'm on Win7 x64.

Thank you ahd have a nice day!

**Comment by Yaron10** [comment]
@juef17,

I can not reproduce it with [Compare v1.5.6.6](https://bitbucket.org/uph0/compare/downloads).

Regards.

**Comment by juef17** [comment]
I was indeed on an older version of the plugin, but I updated it and the issue is still there. I also was able to reproduce the bug with v.6.8.3 on two different computers. 

I was able to get a dump, though: https://dl.dropboxusercontent.com/u/19680817/Misc/NppDump.dmp

**Comment by dail8859** [comment]
Would probably make more sense to report this to the actual plugin developer on sourceforge.

**Comment by Yaron10** [comment]
@juef17,

I'm still using NP v6.8.
I'm on Win7 32-bit.

Did you remove all the older version's files before installing the new one? 
Try [Compare v1.5.6.7](http://www47.zippyshare.com/v/OjNihpth/file.html). I've slightly modified UFO's code some time ago.

**Comment by juef17** [comment]
@dail8859 Indeed, I hadn't realized the plugins had their own pages. My mistake, sorry.

@Yaron10 I didn't remove the older version's files, but v1.5.6.7 does not seem to crash when following the same steps.

**Comment by Yaron10** [comment]
@juef17,

Great. Please check again and confirm.

Following your STR, there's a problem (not a crash though);
The new empty file displays "NUL" at the beginning. I reported it to UFO about a year ago.
Unfortunately, it seems that UFO has abandon the project.

**Comment by juef17** [comment]
@Yaron10 , checked again. I thought the new empty file's NUL was cause by my default encoding (UTF-8), but changing to UTF-8 w/o BOM didn't seem to change anything.

Thank you for your time!

**Comment by Yaron10** [comment]
My pleasure.

**Comment by Eldaw** [comment]
All of these versions past 1.5.6.2  -- are they now developed by somebody other than the original developer? The main (old?) website only refers to v1.5.6.2.  Apart from the Bitbucket repository linked to in this discussion, is there a web site associated with the newer versions of the Compare plugin?

**Comment by Yaron10** [comment]
@Eldaw,

The original developer abandoned the project a long time ago.
UFO has done a great job.

As far as I know, there isn't a site for the recent versions (apart from the Bitbucket repository). 
You might want to check the following threads:
http://sourceforge.net/p/notepad-plus/discussion/482781/thread/1ed3f576/
http://sourceforge.net/p/notepad-plus/discussion/482781/thread/f035f7b6/
http://sourceforge.net/p/notepad-plus/discussion/482781/thread/30c87332/?page=0

**Comment by Eldaw** [comment]
Thanks Yaron10, I'll check those threads out. It's good to know that further work has been done on the Compare plugin.

**Comment by Yaron10** [comment]
You're welcome.

**Comment by dail8859** [comment]
3rd party plugin. Closing.
