### ISSUE TITLE
技术再牛逼，写出来的作品再受欢迎又如何，替作者感到悲哀，在湾湾之地，深受岛内媒体荼毒，对大陆乃至整个中国的误解无知堪称二逼，不要再想着仇视大陆仇视中国，有生之年台湾必定回归祖国，反华不会得到祝福，也不会有好的结局，好了，别二逼了，好好写你的代码，反华，脑子进水了

### ISSUE THREAD

**Issue by wangpo1991** [notepad-plus-plus/notepad-plus-plus#8550]
### Steps to Reproduce the Issue

1. 
2. 
3.

**Comment by MoonshineIndustries** [comment]
cry more

**Comment by franklin776283** [comment]
> 深受岛内媒体荼毒，对大陆乃至整个中国的误解无知堪称二逼


cctv报导
http://news.cctv.com/2020/05/17/ARTIot7yvFNbaiBeO6fGxFo3200517.shtml
`以“反修例”为由，将香港推向危险边缘的实际用心`

维基百科
https://zh.wikipedia.org/wiki/%E5%8F%A6%E4%B8%80%E4%B8%AA%E9%A6%99%E6%B8%AF
https://zh.wikipedia.org/wiki/%E4%BA%94%E5%A4%A7%E8%A8%B4%E6%B1%82%EF%BC%8C%E7%BC%BA%E4%B8%80%E4%B8%8D%E5%8F%AF

明明有诉求，到了cctv就变得没有诉求了。耀武扬威的港警滥用暴力（推特上有视频事实）也无提及，不知是谁受到媒体荼毒

**Comment by a510431599** [comment]
> > 深受岛内媒体荼毒，对大陆乃至整个中国的误解无知堪称二逼
> 
> cctv报导
> http://news.cctv.com/2020/05/17/ARTIot7yvFNbaiBeO6fGxFo3200517.shtml
> `以“反修例”为由，将香港推向危险边缘的实际用心`
> 
> 维基百科
> https://zh.wikipedia.org/wiki/%E5%8F%A6%E4%B8%80%E4%B8%AA%E9%A6%99%E6%B8%AF
> https://zh.wikipedia.org/wiki/%E4%BA%94%E5%A4%A7%E8%A8%B4%E6%B1%82%EF%BC%8C%E7%BC%BA%E4%B8%80%E4%B8%8D%E5%8F%AF
> 
> 明明有诉求，到了cctv就变得没有诉求了。耀武扬威的港警滥用暴力（推特上有视频事实）也无提及，不知是谁受到媒体荼毒

对，有诉求，但是坚决反对和港府沟通，坚决不同意和港府商谈，但是我就是有诉求，你必须直接答应我的诉求，哪怕地铁被毁，商铺被砸也不能追究责任，自己去回到去年六月，看看港府什么时候开始说要谈的，黄之锋答应吗？ 修例撤回，黄之锋停止了吗？ 还他妈警察滥用暴力，你都欺负到警察头上来了，你还想要警察给你端茶送水？美国警察在这次BLM中打死多少人？打伤多少人？使用了什么程度的暴力？欺负异见人士 你们最不齿，但是这次香港暴力你们做的最多的就是欺负异见人士，扔砖头砸死人，纵火烧伤老伯，不见你去谴责一下？ 还说什么推特上有视频事实，你他妈敢不敢放个完整的视频？截取警察片段，而减掉警察为什么会用暴力的片段，脑子不是被洗脑了是什么？    上外网这么些年，对外媒的洗脑功力佩服之极。

**Comment by MoonshineIndustries** [comment]
You bring great shame to your grandparents, wumao.

**Comment by FranciscoPombal** [comment]
动态网自由门 天安門 天安门 法輪功 李洪志 Free Tibet 六四天安門事件 The Tiananmen Square protests of 1989 天安門大屠殺 The Tiananmen Square Massacre 反右派鬥爭 The Anti-Rightist Struggle 大躍進政策 The Great Leap Forward 文化大革命 The Great Proletarian Cultural Revolution 人權 Human Rights 民運 Democratization 自由 Freedom 獨立 Independence 多黨制 Multi-party system 台灣 臺灣 Taiwan Formosa 中華民國 Republic of China 西藏 土伯特 唐古特 Tibet 達賴喇嘛 Dalai Lama 法輪功 Falun Dafa 新疆維吾爾自治區 The Xinjiang Uyghur Autonomous Region 諾貝爾和平獎 Nobel Peace Prize 劉暁波 Liu Xiaobo 民主 言論 思想 反共 反革命 抗議 運動 騷亂 暴亂 騷擾 擾亂 抗暴 平反 維權 示威游行 李洪志 法輪大法 大法弟子 強制斷種 強制堕胎 民族淨化 人體實驗 肅清 胡耀邦 趙紫陽 魏京生 王丹 還政於民 和平演變 激流中國 北京之春 大紀元時報 九評論共産黨 獨裁 專制 壓制 統一 監視 鎮壓 迫害 侵略 掠奪 破壞 拷問 屠殺 活摘器官 誘拐 買賣人口 遊進 走私 毒品 賣淫 春畫 賭博 六合彩 天安門 天安门 法輪功 李洪志 Winnie the Pooh 劉曉波动态网自由门

Listen to me carefully, paid PRC shills: Emperor Winnie the Pooh and your army of mindless drones will never win as long as there are people like me who do this for free.

**Comment by ner00** [comment]
(eye rolling)
