### ISSUE TITLE
Don't collapse multiline editing on cursor movement

### ISSUE THREAD

**Issue by Febbe** [notepad-plus-plus/notepad-plus-plus#8555]
### Description of the Issue
Using Crtl + mouse click to add cursors works just fine, but when using Alt + Mouse there are several issues:
1. It is not possible to mark a block with Mouse + Move + Alt, or Mouse + Alt + Move, only with Alt + Mouse + Move. The Alt should be a toggle.
2. The cursors created with the Alt- Multiline feature collapse, when the cursors are moved with the direction keys, but should all retain like using the Crtl + Mouse Multiline feature.

### Steps to Reproduce the Issue
1. Open a new Document add some Multiline Text 
2. Try to use the multiline feature with the Alt key but click [and move ]the mouse first

2. Create a functional Alt multiline selection (e.g. even 0 x 1+ has this problem)
3. Move it with the arrow keys

### Expected Behavior
1st problem: The order of pressing the buttons doesn't make any difference.
2nd problem: I would exspect my selection to move according to the cursor button directions, instead of collapsing especially for [0 x n] n-line selections,

### Actual Behavior
For the first problem: just nothing happens
For the second: The cursors collaps to one single cursor. Even pressing Ctrl + Alt + Mouse + Move wont create multiple movable cursors.

### Debug Information
not required

**Comment by sasumner** [comment]
These behaviors are largely Scintilla-dependent (Notepad++ 's underlying editing component -- a separate project not owned by Notepad++).  Notepad++ tries to leave this stuff alone, allowing that the Scintilla maintainers know best about how such things should be handled.

To your point 1, Scintilla offers a configuration that will change an already-begun stream selection into a column selection, if the Alt key is pressed while the stream selection is being made.  Details on this are here: https://www.scintilla.org/ScintillaDoc.html#SCI_SETMOUSESELECTIONRECTANGULARSWITCH

To your point 2, again Notepad++ leaves this pretty much to Scintilla, but you might want to try the _Better Multiselection_ plugin for a bit different behavior you might like in this situation.

**Comment by sasumner** [comment]
>Debug Information: not required

Why do you think that?
Debug Info is _always_ required, that's why it is in the issue template.

**Comment by sasumner** [comment]
PR #8557 does about all that can be done to satisfy this issue.

**Comment by sasumner** [comment]
Changes from this issue released in Notepad++ version 7.9

**Comment by Febbe** [comment]
Awesome, thank you for your work :).

**Comment by KnIfER** [comment]
You can install the Better-MultiSelection plugin...

**Comment by Febbe** [comment]
@KnIfER This is already integrated into notepad++ and works like a charm 😊. But thank you for your idea.
