### ISSUE TITLE
Unchanged files are marked as changed after "Sort Lines"

### ISSUE THREAD

**Issue by bersbersbers** [notepad-plus-plus/notepad-plus-plus#8558]
### Steps to Reproduce the Issue

1. Create and save a simple file (line 1: A, line 2: B)
2. Edit - Line Operations - Sort Lines (pick any method)

### Expected Behavior
File remains unchanged, is not marked as changed

### Actual Behavior
File remains unchanged, *is* marked as changed

This does not happen for other Line Operations such as "Remove Empty Lines".

### Debug Information
```
Notepad++ v7.8.8   (64-bit)
Build time : Jun 23 2020 - 23:59:56
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS Name : Windows 10 Pro (64-bit) 
OS Version : 2004
OS Build : 19041.329
Current ANSI codepage : 1252
Plugins : DSpellCheck.dll mimeTools.dll NppConverter.dll NppExport.dll XMLTools.dll 
```

**Comment by sasumner** [comment]
Changes from this issue released in Notepad++ version 7.9
