### ISSUE TITLE
Ctrl-Shift-Z and Ctrl-Y should both REDO by default.

### ISSUE THREAD

**Issue by BobStein** [notepad-plus-plus/notepad-plus-plus#856]
The Ctrl-Shift-Z keystroke combination currently (v6.8.1) inserts a SUB control character (ASCII control-Z, MS-DOS end-of-file).  

![How SUB looks in Notepad++](http://i.imgur.com/QxU3MZh.png)

This is a UX crime.  It [destroys work](http://stackoverflow.com/q/6297923/673991) after a long series of Ctrl-Z undos, if one had intended to restore all those revisions with redo, and inadvertently types the wrong key.

## Editors that support both:

 * [Visual Studio](http://visualstudioshortcuts.com/2013/)
 * Chrome
 * Firefox
 * LibreOffice (only Ctrl-Y is [documented](https://help.libreoffice.org/Writer/Shortcut_Keys_for_Writer), but both work)
 * [Atom](https://github.com/atom/atom/issues/2988#issuecomment-49217126)
 * [Gliffy](https://www.gliffy.com/)

## Editors that support only Ctrl-Shift-Z:

 * [JetBrains](https://www.jetbrains.com/idea/help/undoing-and-redoing-changes.html) editors, including PyCharm, WebStorm, IntelliJ. (Ctrl-Y deletes a line, also a dumb choice with similar consequences.)
 * [AdWords](https://support.google.com/adwords/editor/answer/54654?hl=en)
 * Mac [TextEdit](http://cdn.osxdaily.com/wp-content/uploads/2014/04/turn-off-autocorrect-textedit.jpg), [Finder](https://books.google.com/books?id=MN81gC_jRRYC&pg=PA144&lpg=PA144) and [others](https://documentation.apple.com/en/soundtrackpro/usermanual/index.html#chapter=3%26section=4%26tasks=true)
 * Notepad (Ctrl-Y does nothing)

## Editors that support only Ctrl-Y:

 * Notepad++
 * Internet Explorer (which at least mercifully ignores Ctrl-Shift-Z)
 * Open Office (also ignores Ctrl-Shift-Z)
 * [Microsoft Word](http://www.joyedaniels.com/keys_word.htm) (where Ctrl-Shift-Z removes character formats, punishingly)

## Editors that support neither:

 * [nano](http://askubuntu.com/a/672091/215820) uses Alt-U for undo, Alt-E for redo

### Conclusion 

There is a lot of mainstream support for Ctrl-Shift-Z as redo.  Ctrl-Y is receding into legacy.  This punishes Notepad++ users who often switch applications.

**Notepad++ should support both Ctrl-Shift-Z and Ctrl-Y for REDO by default.**  Currently the setting can be [changed](http://stackoverflow.com/q/6297923/673991) to one or the other but not both.  Worse, the default redo key is Ctrl-Y.  Much worse, Ctrl-Shift-Z defaults to an action that disrupts the redo chain.

**Comment by dail8859** [comment]
I don't know how many times I've hit `Ctrl+Shift+Z` and screwed myself. I would be perfectly fine if they both worked. At least make it so `Ctrl+Shift+Z` doesn't insert the control character!

:+1:

**Comment by h-h-h-h** [comment]
:+1:

**Comment by dg9ngf** [comment]
Fortunately not ran into this yet in the last few days, but it's good to be warned!

:+1:

**Comment by NN---** [comment]
:+1:

**Comment by zumoshi** [comment]
:+1:

**Comment by zman0900** [comment]
:+1:

**Comment by Keavon** [comment]
This REALLY needs to be fixed. The destruction of work is a HUGE problem. And who the heck uses the sub character? 99% of people don't even know what it *is*. Ctrl Y is the past... Ctrl Shift Z is the present. Please fix this!

**Comment by h-h-h-h** [comment]
> @Keavon:
> Ctrl Y is the past... Ctrl Shift Z is the present.

That's a little bit to much of it. Ctrl+X/Y are still my favorites.

**Comment by BobStein** [comment]
@h-h-h-h you mean Ctrl+Z/Y don't you? 

Anyway I agree, both should be supported by default.

**Comment by donho** [comment]
@BobStein So you put Notepad++ and IE together for devaluing this current behaviour ? I see what are you doing here ;)

**Comment by Keavon** [comment]
Well, both are stupidly designed in this regard! But only one is stupidly designed in every other regard.

**Comment by BobStein** [comment]
@donho :innocent:

Actually my theory is that MSWord is the common ancestor of this Ctrl+Y mutant strain. From there it can be traced to a cave in southern France dated circa 40 kya.

**Comment by h-h-h-h** [comment]
> @BobStein:
> you mean Ctrl+Z/Y don't you?

Yes.

**Comment by Deliganli** [comment]
I have screwed up many times for using Ctrl + Shift + Z. Freedom at last!

**Comment by dg9ngf** [comment]
That looks easy. Can you please do the same for #879?

**Comment by Keavon** [comment]
Thank you @donho! Looking forward to 6.9.1 so I can clear my preferences and try it out.

**Comment by BobStein** [comment]
:clap: @donho Thank you!!

**Comment by durtto** [comment]
Thanks

**Comment by nacesprin** [comment]
I'm using ubuntu 14.04. Why `Ctrl+Shift+Z` doesn't work for me? `Ctrl+Y` works.

**Comment by SteveAldrich** [comment]
I use both German and US keyboards. The y and z are transposed between the 2 layouts. I lost a bunch of work when trying to undo, but the pycharm thought I wanted to delete a line. I support the windows compatability idea. It would be great to be able to set your own keyboard mappings in pycharm for anything you want. That's, of course, a tall order.

**Comment by sasumner** [comment]
@SteveAldrich What does pycharm have to do with Notepad++ ?

**Comment by SteveAldrich** [comment]
> 
> 
> @SteveAldrich What does pycharm have to do with Notepad++ ?

Thought this was referring to the pycharm ctrl-y = delete issue. Deleted my comment.
