### ISSUE TITLE
Search is broken in normal mode when double quotes are used.

### ISSUE THREAD

**Issue by nine9999** [notepad-plus-plus/notepad-plus-plus#8566]
### Description of the Issue
Search is broken in normal mode when paired double quotes are searched for.

### Steps to Reproduce the Issue
Simple example;
1. Open search dialog (ctrl+f).
2. Type style="" into the Find what: textbox.
3. Select Match whole word only option.
3. Select Normal in search mode.
4. Click Find Next.

Notepad attempts to search for style="", with red text: Find: Can't find the text "style=""" even though there are multiple instances of it in the document body.

### Expected Behavior
I expected the next instance of the text to be found.

### Actual Behavior
Search fails.

### Debug Information
Notepad++ v7.8.7   (64-bit)
Build time : Jun  5 2020 - 02:38:56
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS Name : Windows 10 Pro (64-bit) 
OS Version : 1903
OS Build : 18362.900
Current ANSI codepage : 1252
Plugins : JSMinNPP.dll mimeTools.dll NppConverter.dll NppExport.dll

**Comment by sasumner** [comment]
@nine9999 
Can you upload a file that has the data that this search fails on?

**Comment by nine9999** [comment]
Here is a sample.

I just realised this issue is also directly died to the option "Match whole word only".  The search succeeds when the option is disabled, but not when it is enabled.


<html>
	<head>
		<title>x</title>
	</head>
	
	<style type="text/css">
	</style>
<body>
	<div style=""></div>
</body>

**Comment by sasumner** [comment]
If you are using the _Match whole word only_ option then by design the first and the last characters of the search term must be "word" characters, defined as A-Z, a-z, 0-9 or `_`.

Here your last character is not one of these.
