### ISSUE TITLE
After update to v7.8.7, noticing high cpu usage on big files above 13mb.

### ISSUE THREAD

**Issue by premson** [notepad-plus-plus/notepad-plus-plus#8567]
### Description of the Issue

After update to v7.8.7, noticing high cpu usage on big files above 13mb.

### Steps to Reproduce the Issue

1. Open a big text file greater than 13mb
2. cpu consumption spikes to 35%
3. 

### Expected Behavior

Normal cpu usage

### Actual Behavior

Normal cpu usage

### Debug Information

Notepad++ v7.8.7   (64-bit)
Build time : Jun  5 2020 - 02:38:56
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS Name : Windows 10 Pro (64-bit) 
OS Version : 1903
OS Build : 18362.904
Current ANSI codepage : 1252
Plugins : DSpellCheck.dll JSMinNPP.dll mimeTools.dll NppConverter.dll NppExport.dll NPPJSONViewer.dll XMLTools.dll

**Comment by dail8859** [comment]
Try disabling your plugins to see if one of those are causing the high CPU usage.

**Comment by premson** [comment]
Removed all plugins, still CPU hovers around 32%, when trying to read a big file, the programs becomes unreadable, creates a hung like state when trying to scroll.

--
Notepad++ v7.8.7   (64-bit)
Build time : Jun  5 2020 - 02:38:56
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS Name : Windows 10 Pro (64-bit) 
OS Version : 1903
OS Build : 18362.904
Current ANSI codepage : 1252
Plugins : none

**Comment by dail8859** [comment]
Does your file have long lines? There are known performances issues when files have incredibly long lines.

**Comment by sasumner** [comment]
Uploading a sample file where this occurs may help others in an attempt to reproduce, but of course this may not be possible if the data is sensitive.

**Comment by premson** [comment]
Yes, there are long files and sorry the data is sensitive for upload, but the question is why the performance issue post update to v7.8.7 ?

**Comment by premson** [comment]
v7.8.9 seems to have fixed it.
