### ISSUE TITLE
Allow re-ordering of files in Doc Switcher by selecting files and dragging them

### ISSUE THREAD

**Issue by HizzyHaz** [notepad-plus-plus/notepad-plus-plus#8568]
### Description of the Issue
Doc Switcher does not allow user control of the file list.  Multiple files _can_ be selected in Doc Switcher, but cannot be drag-moved. 

I often work with many dozens, if not hundreds of files at any given time, and I use the doc switcher to quickly go to another file.  This is made difficult by the inability to rearrange the file list in the doc panel by dragging files around. Newly opened files always go to the the bottom of the doc panel (or the right end of the tab bar), which necessitates manual re-ordering because having the file list organized to my own preference is crucial for productivity.  

Afaik the only way to re-order files currently is to move a single file in the tab bar either with the mouse, or Ctrl+Shift+ Pg Dn/Up, which is extremely inefficient because it requires an insane amount of dragging in a long tab list, and I don't like to use the tab bar in the first place, given the more compact doc switcher.  

I think it is important to give the user more control of the file list in the doc switcher.  Even single-file dragging in the doc switcher would be leaps and bounds better than the tab dragging in the tab bar.  Ideally the user would be able to select multiple files and move them.  

Thank you for your consideration!

### Steps to Reproduce the Issue
1. Select one or more files inside doc switcher
2. Drag them up/down with the mouse

### Expected Behavior
Files should be able to be moved inside doc switcher. 

### Actual Behavior
Files do not move.

### Debug Information
Notepad++ v7.8.7   (64-bit)
Build time : Jun  5 2020 - 02:38:56
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS Name : Windows 10 Education (64-bit) 
OS Version : 1909
OS Build : 18363.900
Current ANSI codepage : 1252
Plugins : CodeAlignmentNpp.dll ComparePlugin.dll Explorer.dll mimeTools.dll NavigateTo.dll nppAutoDetectIndent.dll NppConverter.dll NppExport.dll _CustomizeToolbar.dll

**Comment by ArkadiuszMichalski** [comment]
Duplicate for https://github.com/notepad-plus-plus/notepad-plus-plus/issues/2221 and https://github.com/notepad-plus-plus/notepad-plus-plus/issues/7690.

**Comment by docsparks** [comment]
Jesus christ I goto find a quick how to 'alpha-sort docswitcher' and find a unimplemented request from 2015+ 

plus this guy above me.. fuck
