### ISSUE TITLE
Multi line <Tab> not working

### ISSUE THREAD

**Issue by dgghun** [notepad-plus-plus/notepad-plus-plus#8570]
### Description of the Issue

When the cursor is in multiple line mode (ie SHIFT + ALT + ArrowUp or ArrowDown) the TAB button is not working or works incorrectly. Weird things happen where it actually goes backwards or it doesn't tab all lines forward flush-ly. Was working fine until last update.
### Steps to Reproduce the Issue

1. 
Select multiple lines using SHIFT + ALT + ArrowUp or SHIFT + ALT + ArrowDown
2. 
Press the TAB key
3. 
Watch the weridness happen
### Expected Behavior

All lines should tab over in a uniform flush manner
### Actual Behavior

Does different things depending on how much text there is on the line
### Debug Information

Notepad++ v7.8.7   (32-bit)
Build time : Jun  5 2020 - 02:34:28
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS Name : Windows 8.1 Pro (64-bit) 
OS Build : 9600.0
Current ANSI codepage : 1252
Plugins : ComparePlugin.dll DSpellCheck.dll Explorer.dll FallingBricks.dll LightExplorer.dll mimeTools.dll MultiClipboard.dll NppCCompletionPlugin.dll NppConverter.dll NppExec.dll NppExport.dll

**Comment by dail8859** [comment]
Cannot reproduce this using v7.8.8 with no plugins installed.

Please define or add a screenshot of "weirdness".

Also disable plugins as that could be a cause if the problem.

**Comment by sasumner** [comment]
Known issue in 7.8.7.
7.8.8 fixes this, see its change.log entry: `Fix block selection cursor wrong positions after typing TAB.`
See #8400 and https://github.com/notepad-plus-plus/notepad-plus-plus/commit/660284011776830a4f483ceeadf244dd5522d7f9

**Comment by dgghun** [comment]
Thanks for looking into this. Ill try updating.
