### ISSUE TITLE
Add themes to change Taskbar and Ribbon color

### ISSUE THREAD

**Issue by faisalasghar** [notepad-plus-plus/notepad-plus-plus#8571]
The "style configurator" only changes the theme of the Editor Screen . The borders and the taskbar remain white , which becomes quite disturbing when in Dark Mode. Please add "themes" to the software , so that we can change the overall look and feel of the app.

**Comment by kaaax0815** [comment]
Yes please add this!!

**Comment by Heislitz** [comment]
+1 Would be really great to customize the UI itself!

**Comment by cdalexndr** [comment]
Note that Win10 dark theme has no effect on Notepad++ window even if regular win10 windows are black.
It would be nice if it integrated nicely with win10 theme, or at least notepad++ themes support for whole window.

I'm using auto-switch to dark theme (at sunset) for win10, firefox, ide, but Notepad++ lacks this feature and _destroys_ my eyes at night...

**Comment by ozone10** [comment]
implemented, can be closed

**Comment by ArkadiuszMichalski** [comment]
Please use Dark Mode:
![image](https://user-images.githubusercontent.com/2730894/130226654-040b212b-b3ba-45f2-8e51-f3103d77df7d.png)
