### ISSUE TITLE
Can't delete search history items.

### ISSUE THREAD

**Issue by drumrock** [notepad-plus-plus/notepad-plus-plus#8572]
History in search window seems to be stored forever.
A lot of garbage from different files and projects can be there, so it would be nice to have some option to delete these old search items.

It could be somewhere in Configuration menu. Or better - button "Clear search history" in search window itself.

![image](https://user-images.githubusercontent.com/10419376/87624181-c45c6000-c72f-11ea-8ba3-dfba5106b059.png)

**Comment by sasumner** [comment]
Old searches will "fall off" naturally as new searches are conducted; the history lists have a default size of 10.
