### ISSUE TITLE
驳斥“Notepad++ v7.8.1 : Free Uyghur(免费维吾尔族)”一文

### ISSUE THREAD

**Issue by zrzjohn** [notepad-plus-plus/notepad-plus-plus#8576]
看到伙伴发过来的信息，我很惊讶于一款软件的作者怎么会热衷于捏造虚假言论，并且是很有政治目的的污蔑和诬陷，出于实事求是的精神，对于网上以讹传讹的信息我都要去证实一下，所以就找到Notepad的官方网站查看，果然在其官方网站看到了这篇发布于2019年10月29日的文章，文章标题是“Notepad++ v7.8.1 : Free Uyghur”，文中内容充满了臆测和可笑的逻辑错误，真不敢想象这篇文章是出自一位软件工程师之手，出于工作的原因，一般情况下从事软件工作的人至少思维应该是比较严谨的，也不至于犯严重的逻辑错误。但Notepad软件的作者却颠覆了我以往的一切认知。

现将可笑逻辑错误罗列如下：

1. 文中对被拘留在“再教育营”中的人数前后不一致，一会儿说数十万人，然后又说100万人，到底是多少人呢？数十万又是多少呢？二十万、三十万……九十万都是数十万，那么究竟具体是多少呢？你获得这个数据的依据又是什么呢？是你凭空臆测还是道听途说？数十万怎么又能跟一百万划等号？不知道侯先生的数学课是哪位老师教的，这么简单的错误难道没有发现？科学讲究实证，软件讲究逻辑，侯先生是高材生，又是从事的软体工作，我怎么想也想不通这么简单的数学计算侯先生怎么会出错？

2. 维吾尔族人口目前大概在一千万左右，按侯先生说的一百万计算，就是有十分之一的人都被拘留了，这很明显是不可能的事情。再请侯先生用充满混乱逻辑思维的大脑想一想，如果要拘留一百万人口，那么要多大面积的拘留所，这个偌大的拘留所又在哪里？如果侯先生不是凭空想象出来的，并且有事实依据的话，那么请侯先生指出这个能够容纳一百万人口的大拘留所具体在哪个位置。

3. 文中说维吾尔族不是华裔，这点更是可笑之极。试问世界上有几个国家是单一民族的？即便是台湾省的人口结构也是多民族组成的，是不是华裔跟哪个民族又有什么关系？难道侯先生想用同样的逻辑分解台湾或者按你的逻辑世界上每个国家都该分裂？而自治是为了让自治区的人们享有更多的权利，自主管理，这不正是充分人权的表现吗？自治是建立在国家对地区的充分信任和尊重基础上的政策，但不是用来搞分裂的由头，更不是用于搞暴力恐怖的理由。举个简单的例子，侯先生放权让你的孩子自己管理自己，那么按侯先生的逻辑，你的孩子是否就可以跟你断绝父子关系，并且对你实行暴力？

4. 文中说北京将维吾尔族定性为恐怖组织，这个更是逻辑混乱到可以笑喷的地步。我们可以查到，维吾尔族人口数量大概在一千万人左右，如果北京将维吾尔族定性为恐怖组织，那么应该把这一千万人都抓起来啊，怎么侯先生说的却是数十万人？估计侯先生事先没有了解过维吾尔族的人口数量，如果了解过，那么我猜侯先生肯定会把一百万改成一千万来说事。这种凭空随意乱说的技能估计也只有侯先生这样的充满混乱逻辑思维的高材生才具备的。

5. 文中提到的人权问题。我想请教一下侯先生，你的人权是怎么定义的？是不是就等同于随心所欲，胡作非为，暴力恐怖，不守法律，扰民乱民，随意侵害他人权益。如果是这样的话，那么你还遵守你所在地区的法律干啥？你完全可以去干些违法犯罪的事情，然后再以人权为由躲避法律的制裁。这种逻辑和认知简直无知之极，我想这样的人权是世界上任何哪个国家和地区都不允许的，否则要司法干嘛？台湾方面以行政手段强制灌输民众和学生台独思想，这种改变政治思想的反人权行为侯先生怎么不去声讨一下？

侯文的每一个地方都充满着臆测和严重的逻辑错误，我建议侯先生应该把自己的软件工作做好，不要把你除软件以外的无知和混乱思维展示出来，贻笑大方。

注：据网上信息显示，Notepad作者侯今吾，中国台湾人。

**Comment by imgradeone** [comment]
不建议发到 issue 区，这里是提 bug 的，建议发个人博客。（虽然 donho 是白癡）

I don't think it is polite to send this article to the Issues place.

**Comment by FranciscoPombal** [comment]
动态网自由门 天安門 天安门 法輪功 李洪志 Free Tibet 六四天安門事件 The Tiananmen Square protests of 1989 天安門大屠殺 The Tiananmen Square Massacre 反右派鬥爭 The Anti-Rightist Struggle 大躍進政策 The Great Leap Forward 文化大革命 The Great Proletarian Cultural Revolution 人權 Human Rights 民運 Democratization 自由 Freedom 獨立 Independence 多黨制 Multi-party system 台灣 臺灣 Taiwan Formosa 中華民國 Republic of China 西藏 土伯特 唐古特 Tibet 達賴喇嘛 Dalai Lama 法輪功 Falun Dafa 新疆維吾爾自治區 The Xinjiang Uyghur Autonomous Region 諾貝爾和平獎 Nobel Peace Prize 劉暁波 Liu Xiaobo 民主 言論 思想 反共 反革命 抗議 運動 騷亂 暴亂 騷擾 擾亂 抗暴 平反 維權 示威游行 李洪志 法輪大法 大法弟子 強制斷種 強制堕胎 民族淨化 人體實驗 肅清 胡耀邦 趙紫陽 魏京生 王丹 還政於民 和平演變 激流中國 北京之春 大紀元時報 九評論共産黨 獨裁 專制 壓制 統一 監視 鎮壓 迫害 侵略 掠奪 破壞 拷問 屠殺 活摘器官 誘拐 買賣人口 遊進 走私 毒品 賣淫 春畫 賭博 六合彩 天安門 天安门 法輪功 李洪志 Winnie the Pooh 劉曉波动态网自由门

Listen to me carefully, paid PRC shills: Emperor Winnie the Pooh and your army of mindless drones will never win as long as there are people like me who do this for free.

**Comment by ner00** [comment]
(eye rolling)

**Comment by BruceLiang123** [comment]
> 看到伙伴发过来的信息，我很惊讶于一款软件的作者怎么会热衷于捏造虚假言论，并且是很有政治目的的污蔑和诬陷，出于实事求是的精神，对于网上以讹传讹的信息我都要去证实一下，所以就找到Notepad的官方网站查看，果然在其官方网站看到了这篇发布于2019年10月29日的文章，文章标题是“Notepad++ v7.8.1 : Free Uyghur”，文中内容充满了臆测和可笑的逻辑错误，真不敢想象这篇文章是出自一位软件工程师之手，出于工作的原因，一般情况下从事软件工作的人至少思维应该是比较严谨的，也不至于犯严重的逻辑错误。但Notepad软件的作者却颠覆了我以往的一切认知。
> 
> 现将可笑逻辑错误罗列如下：
> 
> 1. 文中对被拘留在“再教育营”中的人数前后不一致，一会儿说数十万人，然后又说100万人，到底是多少人呢？数十万又是多少呢？二十万、三十万……九十万都是数十万，那么究竟具体是多少呢？你获得这个数据的依据又是什么呢？是你凭空臆测还是道听途说？数十万怎么又能跟一百万划等号？不知道侯先生的数学课是哪位老师教的，这么简单的错误难道没有发现？科学讲究实证，软件讲究逻辑，侯先生是高材生，又是从事的软体工作，我怎么想也想不通这么简单的数学计算侯先生怎么会出错？
> 2. 维吾尔族人口目前大概在一千万左右，按侯先生说的一百万计算，就是有十分之一的人都被拘留了，这很明显是不可能的事情。再请侯先生用充满混乱逻辑思维的大脑想一想，如果要拘留一百万人口，那么要多大面积的拘留所，这个偌大的拘留所又在哪里？如果侯先生不是凭空想象出来的，并且有事实依据的话，那么请侯先生指出这个能够容纳一百万人口的大拘留所具体在哪个位置。
> 3. 文中说维吾尔族不是华裔，这点更是可笑之极。试问世界上有几个国家是单一民族的？即便是台湾省的人口结构也是多民族组成的，是不是华裔跟哪个民族又有什么关系？难道侯先生想用同样的逻辑分解台湾或者按你的逻辑世界上每个国家都该分裂？而自治是为了让自治区的人们享有更多的权利，自主管理，这不正是充分人权的表现吗？自治是建立在国家对地区的充分信任和尊重基础上的政策，但不是用来搞分裂的由头，更不是用于搞暴力恐怖的理由。举个简单的例子，侯先生放权让你的孩子自己管理自己，那么按侯先生的逻辑，你的孩子是否就可以跟你断绝父子关系，并且对你实行暴力？
> 4. 文中说北京将维吾尔族定性为恐怖组织，这个更是逻辑混乱到可以笑喷的地步。我们可以查到，维吾尔族人口数量大概在一千万人左右，如果北京将维吾尔族定性为恐怖组织，那么应该把这一千万人都抓起来啊，怎么侯先生说的却是数十万人？估计侯先生事先没有了解过维吾尔族的人口数量，如果了解过，那么我猜侯先生肯定会把一百万改成一千万来说事。这种凭空随意乱说的技能估计也只有侯先生这样的充满混乱逻辑思维的高材生才具备的。
> 5. 文中提到的人权问题。我想请教一下侯先生，你的人权是怎么定义的？是不是就等同于随心所欲，胡作非为，暴力恐怖，不守法律，扰民乱民，随意侵害他人权益。如果是这样的话，那么你还遵守你所在地区的法律干啥？你完全可以去干些违法犯罪的事情，然后再以人权为由躲避法律的制裁。这种逻辑和认知简直无知之极，我想这样的人权是世界上任何哪个国家和地区都不允许的，否则要司法干嘛？台湾方面以行政手段强制灌输民众和学生台独思想，这种改变政治思想的反人权行为侯先生怎么不去声讨一下？
> 
> 侯文的每一个地方都充满着臆测和严重的逻辑错误，我建议侯先生应该把自己的软件工作做好，不要把你除软件以外的无知和混乱思维展示出来，贻笑大方。
> 
> 注：据网上信息显示，Notepad作者侯今吾，中国台湾人。

侯先生是位法轮功成员就一切都合理了
