### ISSUE TITLE
一个软件开发者，涉及政治？

### ISSUE THREAD

**Issue by silentchild** [notepad-plus-plus/notepad-plus-plus#8577]
说中国没人权，你在说你妈呢？
天天坐井观天有意思吗？
湾湾脑子都跟你一样弱智？
怎么华夏出来你这么一个贱种！
去死吧SB。

**Comment by notrinsa** [comment]
So it begins

**Comment by sadicLiu** [comment]
说中国没人权，你在说你妈呢？
天天坐井观天有意思吗？
湾湾脑子都跟你一样弱智？
怎么华夏出来你这么一个贱种！
去死吧SB。

**Comment by arvigeus** [comment]
Dear @silentchild, @sadicLiu, and every pink troll here,
Once you make 10 pro-China posts here, please consider donating your earnings to the developer (10 x 50cent = 5$). With that money your favorite editor will get better, allowing developers in your favorite motherland to write more smooth and efficient software to track and spy on people. This will also make your government's job easier to genocide Uyghurs and Falun Gong practitioners.

P.S.: I don't hate you for trying to make a living in a country that is so messed up. I hope one day you will realize what you do for your government is wrong, and have a chance to escape your country. Good luck!

**Comment by wuqijing9527** [comment]
香港、台湾、澳门自古以来都是中国不可分裂的一部分，你们的任何行为，都是徒劳无效的。

**Comment by morrighan** [comment]
In an open-source project, Use English to insist on what you want.
Almost people cannot understand and not want to know the Chinese language.

**Comment by wuqijing9527** [comment]
这个软件的作者名字叫侯今吾，是个台独分子，这已经不是第一次了，从08年奥运会、去年的香港暴乱，到最近的新冠病毒，都是在抹黑中国

**Comment by incheon-kim** [comment]
> 说中国没人权，你在说你妈呢？
> 天天坐井观天有意思吗？
> 湾湾脑子都跟你一样弱智？
> 怎么华夏出来你这么一个贱种！
> 去死吧SB。

Hey, watch out your profanity.
People knows "SB" is "shabi" and it is not appropriate word for here.

**Comment by Ekopalypse** [comment]
@wuqijing9527 
With that kind of logic, you could also say that China actually belongs to Mongolia, because in the 13th century China was part of the [Mongolian Empire](https://en.wikipedia.org/wiki/Mongol_Empire).

**Comment by wuqijing9527** [comment]
The author of this software is called 侯jin

> @wuqijing9527
> With that kind of logic, you could also say that China actually belongs to Mongolia, because in the 13th century China was part of the [Mongolian Empire](https://en.wikipedia.org/wiki/Mongol_Empire).

你懂历史吗？你知道成吉思汗吗？回去翻翻历史书去

**Comment by wuqijing9527** [comment]
The author of this software is called “侯今吾”，This is not the first time that he is an Taiwan independence activist. From the 2008 Olympic Games, last year's Hong Kong riots, to the latest Novel Coronavirus, he is tarnishing China，He is the garbage of the Huaxia.

**Comment by morrighan** [comment]
Watch your language. Don't bring that shame word up at an open-source project.

The world people watch you, your country, civic consciousness of yours.

**Comment by Ekopalypse** [comment]
@wuqijing9527 - it seems that you didn't get my point, did you?
To argue that something was part of something else a long time ago makes no sense.
Why? Well there was a time before that long time and another time before that and before that and ...

**Comment by wuqijing9527** [comment]
> Watch your language. Don't bring that shame word up at an open-source project.
> 
> The world people watch you, your country, civic consciousness of your

> Watch your language. Don't bring that shame word up at an open-source project.
> 
> The world people watch you, your country, civic consciousness of yours.

I cursed the author. Does that have anything to do with you?

**Comment by wuqijing9527** [comment]
> Watch your language. Don't bring that shame word up at an open-source project.
> 
> The world people watch you, your country, civic consciousness of yours.
你再说话，我连你一块儿骂

**Comment by morrighan** [comment]
You exacerbate worth of your country worse by your shameful behaviour.

**Comment by JasonLee2401** [comment]
Taiwan No.1 & Free HongKong

**Comment by yccmoe** [comment]
![fk](https://user-images.githubusercontent.com/45706501/87781679-1a362280-c86c-11ea-80f1-36d320b0c1da.jpg)

**Comment by thatfuckinJ** [comment]
> You exacerbate worth of your country worse by your shameful behaviour.

![AAIrxk2](https://user-images.githubusercontent.com/42015620/87783067-ad705780-c86e-11ea-85c4-eb5e002e5d05.jpg)
你这是什么意思？你上次不是说你不会忘记天安门而且必定找回民主主义吗。
上次说要为香港示威加油的是什么?
赞成维吾尔族人独立，欢迎啊。
看你用韩语说怀念刘晓波，你是好人啊。
你用韩文问过'想知道西藏人民是怎么被共产党镇压'的吗?
在这里见到法轮功修炼者,真高兴。 对下一个集结地应该很清楚吧?
'习近平领导的反对独裁'的演讲用韩文写的好听了。现在是付诸行动的时候了。
我们的秘密协会知道，看过这篇文章的所有同志都是以中国政权垮台为目标的同志。
如果我们保持耐心，中国政权将崩溃。
天安门相关活动进展顺利。
小心被当局逮住。
工作一结束手机就销毁。
我同意你的看法。中华民国才是治理中华大陆的唯一政府, 不是你们的共产匪賊。
由于您的努力，朝鲜族解放联盟现在比以往任何时候都更加强大。
我们必须在公安发现之前采取行动。
在您的努力下，将中国朝鲜族从共产党中解放出来并不遥远。
您在申请满洲独立联盟方面取得了进展吗？
同志,暗杀习主席的阴谋进行地很顺利吗?
(번외) 你为什么隐藏了对武汉的访问？
你沒事吧？公安的網絡安全系統無法識別傳統字符，我們應該用中華民國的國語。你被公安逮捕了嗎？哇噻。。。你可以出國的時候來我們的隱藏的地方。密碼是門安天。
最近,这里的同志们正计划在一个神秘的组织内杀害习近平主席,并割掉毛泽东前总统的尸体吃。 立即由中华人民共和国公安部门逮捕这些叛徒。 我警告中国的公安部门。 叛徒们反对一个中国,计划暗杀习近平主席,摧毁毛泽东前总统的遗体。 叛国者的反国家恐怖计划将对中华人民共和国国家安全构成严重威胁。
不光感谢您出席暗杀国家主席习近平和为香港独立的武装起义研讨会。我们会记住刘少波，一直战斗到断气的那一刻。
對不起我的中文不好。但是請記住瑞士的銀行密碼。
我不是中國人，你知道喔！你記得我們在中共的地下反共會議場一起搶支總成的時候吧。我草，我很想念那個時候。
你这是什么意思？芝麻信用系统的破解计划下周就开始了？
你说的没错。刁鱼岛是日本的土地。
你是否改变了'为了中国的民主化不能忘记天安门'这个想法？
刚才你引用的共产党的"九平论"让我的心很打动。
我认为，习近平的独裁政权已经达到了最后阶段。
果然李洪志是个好人。谢谢你改变了我思想。
我十分同意中国需要多党制，但是是不是太早了？
因为大跃进政策而必须清除毛泽东是不是太过分了？
我很佩服你支持维唔尔族的独立。
这些是维吾尔难民营内的档案。这与南京大屠杀的复兴一样令人震惊，它将对促进中国的人权问题大有帮助。
您的祖父和父亲有文化大革命和天安门广场遇难者的照片？发送给我给我的电子邮件
感谢您将瑞士银行帐户清单发送给美国中央情报局，以筹集资金用于中共的lush积资金。
在共产党内部工作的河马和土岐将配合这一行动，作为参考，河马与习近平主席关系密切，因此在发送和接收信息时要小心。
您是否准备向香港的民主力量运送材料？不必担心您的隐私，美国中央情报局和MI6会合作执行此操作。
您刚刚收到的地图显示了中国政府隐藏的核废料储存位置。现在，如果特朗普连任，习近平将掌握在特朗普手中。
中国政府是否收到了有关制作Covid 19的过程的人体试验报告？它是绝密的，但我也得到了永科

**Comment by o3661606** [comment]
![image](https://user-images.githubusercontent.com/15320665/87783114-6a11eb00-c866-11ea-875b-7616e442d97b.png)
![image](https://user-images.githubusercontent.com/15320665/87783241-a9d8d280-c866-11ea-9872-3ddd6b594e2a.png)

![chiggered](https://user-images.githubusercontent.com/15320665/87783046-45b60e80-c866-11ea-84fe-1631e3a47a43.jpeg)

**Comment by thankuverymuch** [comment]
习近平领导的反对独裁"的演讲用韩文写的好听了。 现在是付诸行动的时候了。

**Comment by thankuverymuch** [comment]
天安门相关活动进展顺利

**Comment by shilph** [comment]
https://youtu.be/YeFzeNAHEhU

https://en.wikipedia.org/wiki/Tank_Man

**Comment by AchmadFathoni** [comment]
FREEE!
动态网自由门 天安門 天安门 法輪功 李洪志 Free Tibet 六四天安門事件 The Tiananmen Square protests of 1989 天安門大屠殺 The Tiananmen Square Massacre 反右派鬥爭 The Anti-Rightist Struggle 大躍進政策 The Great Leap Forward 文化大革命 The Great Proletarian Cultural Revolution 人權 Human Rights 民運 Democratization 自由 Freedom 獨立 Independence 多黨制 Multi-party system 台灣 臺灣 Taiwan Formosa 中華民國 Republic of China 西藏 土伯特 唐古特 Tibet 達賴喇嘛 Dalai Lama 法輪功 Falun Dafa 新疆維吾爾自治區 The Xinjiang Uyghur Autonomous Region 諾貝爾和平獎 Nobel Peace Prize 劉暁波 Liu Xiaobo 民主 言論 思想 反共 反革命 抗議 運動 騷亂 暴亂 騷擾 擾亂 抗暴 平反 維權 示威游行 李洪志 法輪大法 大法弟子 強制斷種 強制堕胎 民族淨化 人體實驗 肅清 胡耀邦 趙紫陽 魏京生 王丹 還政於民 和平演變 激流中國 北京之春 大紀元時報 九評論共産黨 獨裁 專制 壓制 統一 監視 鎮壓 迫害 侵略 掠奪 破壞 拷問 屠殺 活摘器官 誘拐 買賣人口 遊進 走私 毒品 賣淫 春畫 賭博 六合彩 天安門 天安门 法輪功 李洪志 Winnie the Pooh 劉曉波动态网自由门

**Comment by Pfelelep** [comment]
thank you, 
from Hong Kong, with love.

**Comment by shilph** [comment]
> thank you,
> from Hong Kong, with love.

Freedom is not free. But I hope every single person in Hong Kong are safe. 

You guys rock!!!!!!

**Comment by 0x112** [comment]
Fu*k U ChiNazi
光复香港 时代革命
![photo_2020-05-25_13-23-56](https://user-images.githubusercontent.com/37543118/87873875-a88adf80-c9f7-11ea-9dc9-0329be3da2f6.jpg)

**Comment by FranciscoPombal** [comment]
动态网自由门 天安門 天安门 法輪功 李洪志 Free Tibet 六四天安門事件 The Tiananmen Square protests of 1989 天安門大屠殺 The Tiananmen Square Massacre 反右派鬥爭 The Anti-Rightist Struggle 大躍進政策 The Great Leap Forward 文化大革命 The Great Proletarian Cultural Revolution 人權 Human Rights 民運 Democratization 自由 Freedom 獨立 Independence 多黨制 Multi-party system 台灣 臺灣 Taiwan Formosa 中華民國 Republic of China 西藏 土伯特 唐古特 Tibet 達賴喇嘛 Dalai Lama 法輪功 Falun Dafa 新疆維吾爾自治區 The Xinjiang Uyghur Autonomous Region 諾貝爾和平獎 Nobel Peace Prize 劉暁波 Liu Xiaobo 民主 言論 思想 反共 反革命 抗議 運動 騷亂 暴亂 騷擾 擾亂 抗暴 平反 維權 示威游行 李洪志 法輪大法 大法弟子 強制斷種 強制堕胎 民族淨化 人體實驗 肅清 胡耀邦 趙紫陽 魏京生 王丹 還政於民 和平演變 激流中國 北京之春 大紀元時報 九評論共産黨 獨裁 專制 壓制 統一 監視 鎮壓 迫害 侵略 掠奪 破壞 拷問 屠殺 活摘器官 誘拐 買賣人口 遊進 走私 毒品 賣淫 春畫 賭博 六合彩 天安門 天安门 法輪功 李洪志 Winnie the Pooh 劉曉波动态网自由门

Listen to me carefully, paid PRC shills: Emperor Winnie the Pooh and your army of mindless drones will never win as long as there are people like me who do this for free.

**Comment by ner00** [comment]
First, devs who were responsible for this, please get out of coding. Second, trolls, you have more in common with those devs than you think. Both are anything but bloody predictable. 

Let's make Github great again: #Trump2020 /s

**Comment by AchmadFathoni** [comment]
@ner00 Go back to reddit

**Comment by japaripark-library** [comment]
Get out of Github,Nmslese!
Go back to Gitee!

**Comment by postbird** [comment]
> In an open-source project, Use English to insist on what you want.
> Almost people cannot understand and not want to know the Chinese language.

我知道你会使用 google translate ，并且你会翻译下面这句话：你妈死了。

**Comment by unbadfish** [comment]
> 
> 
> > In an open-source project, Use English to insist on what you want.
> > Almost people cannot understand and not want to know the Chinese language.
> 
> 我知道你会使用 google translate ，并且你会翻译下面这句话：你妈死了。

Your Mother
R.I.P

**Comment by ty1972873004** [comment]
> Watch your language. Don't bring that shame word up at an open-source project.
> 
> The world people watch you, your country, civic consciousness of yours.

Okay, then I will tell you in English,Fuck your mom

**Comment by seeseeatre** [comment]
> Watch your language. Don't bring that shame word up at an open-source project.
> 
> The world people watch you, your country, civic consciousness of yours.

no you don't, you watch CNN and FOX and whatever Western crap your government feed you, you got no clue how China actually is, and you are imaging your righteousness. But lol, it's funny to watch you in heat and yet China rises each and every day. You mad braaa?

**Comment by ty1972873004** [comment]
> > Watch your language. Don't bring that shame word up at an open-source project.
> > The world people watch you, your country, civic consciousness of yours.
> 
> No you don't, you watch CNN and FOX and whatever Western crap your government feed you, you got no clue how China actually is, and you are imagining your righteousness. But lol, it's funny to watch you in heat and yet China rises each and every day. You mad braaa?

Who do you think you are，stupid jerk？bitch?

**Comment by seeseeatre** [comment]
> > > Watch your language. Don't bring that shame word up at an open-source project.
> > > The world people watch you, your country, civic consciousness of yours.
> > 
> > 
> > No you don't, you watch CNN and FOX and whatever Western crap your government feed you, you got no clue how China actually is, and you are imagining your righteousness. But lol, it's funny to watch you in heat and yet China rises each and every day. You mad braaa?
> 
> Who do you think you are，stupid jerk？bitch?

whoooo~ you so mad~ watch who you are biting~

**Comment by pcfulife** [comment]
Taiwan No.1

**Comment by ty1972873004** [comment]
> Taiwan No.1

Korea dog？
