### ISSUE TITLE
See which language is selected

### ISSUE THREAD

**Issue by vierlijner** [notepad-plus-plus/notepad-plus-plus#8578]
### Description of the Issue
When a (default) language is selected which belongs to a "container" like "C", than this one isn't highlighted.

### Steps to Reproduce the Issue
1. Open a file with the extension "*.cs" (or make one yourself)
2. Go to the menu and open the language tab/ menu (or press in windows Alt + L).
3. Now you don't see which language is used.
4. Go to C and you see another menu (the children) and now you see a blue dot before C# and you know this one is used.

### Expected Behavior
I want to know that I have to look in the C menu from Language which one is used. Or make an actual which you highlight at the top of the language menu.

### Actual Behavior
I have to go throw all menu's to find which language is selected/ used.

### Debug Information
Notepad++ v7.8.6   (32-bit)
Build time : Apr 21 2020 - 15:17:06
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : ON
Local Conf mode : OFF
OS Name : Windows 7 Professional (64-bit) 
OS Build : 7601.0
Plugins : ComparePlugin.dll mimeTools.dll NppConverter.dll NppExport.dll XMLTools.dll

**Comment by Ekopalypse** [comment]
Can be closed as this has been introduced in [7.8.7](https://notepad-plus-plus.org/downloads/v7.8.7/)
