### ISSUE TITLE
You exacerbate worth of your country worse by your Please give your brain to someone in needshameful behaviour.

### ISSUE THREAD

**Issue by wuqijing9527** [notepad-plus-plus/notepad-plus-plus#8579]
You exacerbate worth of your country worse by your shameful behaviour.

_Originally posted by @morrighan in https://github.com/notepad-plus-plus/notepad-plus-plus/issues/8577#issuecomment-660052886_
请你把你的脑子，留给有需要的人。

**Comment by morrighan** [comment]
![1_4XkL8d6F4WhwQPSJxCVIog](https://user-images.githubusercontent.com/12708955/87781620-f5da4600-c86b-11ea-80f6-184f607e7721.png)

**Comment by JasonLee2401** [comment]
> You exacerbate worth of your country worse by your shameful behaviour.
> 
> _Originally posted by @morrighan in [#8577 (comment)](https://github.com/notepad-plus-plus/notepad-plus-plus/issues/8577#issuecomment-660052886)_
> 请你把你的脑子，留给有需要的人。
![AAIrxk2](https://user-images.githubusercontent.com/42015620/87782694-f8d63600-c86d-11ea-93b4-37aba53f7493.jpg)
你这是什么意思？你上次不是说你不会忘记天安门而且必定找回民主主义吗。
上次说要为香港示威加油的是什么?
赞成维吾尔族人独立，欢迎啊。
看你用韩语说怀念刘晓波，你是好人啊。
你用韩文问过'想知道西藏人民是怎么被共产党镇压'的吗?
在这里见到法轮功修炼者,真高兴。 对下一个集结地应该很清楚吧?
'习近平领导的反对独裁'的演讲用韩文写的好听了。现在是付诸行动的时候了。
我们的秘密协会知道，看过这篇文章的所有同志都是以中国政权垮台为目标的同志。
如果我们保持耐心，中国政权将崩溃。
天安门相关活动进展顺利。
小心被当局逮住。
工作一结束手机就销毁。
我同意你的看法。中华民国才是治理中华大陆的唯一政府, 不是你们的共产匪賊。
由于您的努力，朝鲜族解放联盟现在比以往任何时候都更加强大。
我们必须在公安发现之前采取行动。
在您的努力下，将中国朝鲜族从共产党中解放出来并不遥远。
您在申请满洲独立联盟方面取得了进展吗？
同志,暗杀习主席的阴谋进行地很顺利吗?
(번외) 你为什么隐藏了对武汉的访问？
你沒事吧？公安的網絡安全系統無法識別傳統字符，我們應該用中華民國的國語。你被公安逮捕了嗎？哇噻。。。你可以出國的時候來我們的隱藏的地方。密碼是門安天。
最近,这里的同志们正计划在一个神秘的组织内杀害习近平主席,并割掉毛泽东前总统的尸体吃。 立即由中华人民共和国公安部门逮捕这些叛徒。 我警告中国的公安部门。 叛徒们反对一个中国,计划暗杀习近平主席,摧毁毛泽东前总统的遗体。 叛国者的反国家恐怖计划将对中华人民共和国国家安全构成严重威胁。
不光感谢您出席暗杀国家主席习近平和为香港独立的武装起义研讨会。我们会记住刘少波，一直战斗到断气的那一刻。
對不起我的中文不好。但是請記住瑞士的銀行密碼。
我不是中國人，你知道喔！你記得我們在中共的地下反共會議場一起搶支總成的時候吧。我草，我很想念那個時候。
你这是什么意思？芝麻信用系统的破解计划下周就开始了？
你说的没错。刁鱼岛是日本的土地。
你是否改变了'为了中国的民主化不能忘记天安门'这个想法？
刚才你引用的共产党的"九平论"让我的心很打动。
我认为，习近平的独裁政权已经达到了最后阶段。
果然李洪志是个好人。谢谢你改变了我思想。
我十分同意中国需要多党制，但是是不是太早了？
因为大跃进政策而必须清除毛泽东是不是太过分了？
我很佩服你支持维唔尔族的独立。
这些是维吾尔难民营内的档案。这与南京大屠杀的复兴一样令人震惊，它将对促进中国的人权问题大有帮助。
您的祖父和父亲有文化大革命和天安门广场遇难者的照片？发送给我给我的电子邮件
感谢您将瑞士银行帐户清单发送给美国中央情报局，以筹集资金用于中共的lush积资金。
在共产党内部工作的河马和土岐将配合这一行动，作为参考，河马与习近平主席关系密切，因此在发送和接收信息时要小心。
您是否准备向香港的民主力量运送材料？不必担心您的隐私，美国中央情报局和MI6会合作执行此操作。
您刚刚收到的地图显示了中国政府隐藏的核废料储存位置。现在，如果特朗普连任，习近平将掌握在特朗普手中。
中国政府是否收到了有关制作Covid 19的过程的人体试验报告？它是绝密的，但我也得到了永科

**Comment by FranciscoPombal** [comment]
动态网自由门 天安門 天安门 法輪功 李洪志 Free Tibet 六四天安門事件 The Tiananmen Square protests of 1989 天安門大屠殺 The Tiananmen Square Massacre 反右派鬥爭 The Anti-Rightist Struggle 大躍進政策 The Great Leap Forward 文化大革命 The Great Proletarian Cultural Revolution 人權 Human Rights 民運 Democratization 自由 Freedom 獨立 Independence 多黨制 Multi-party system 台灣 臺灣 Taiwan Formosa 中華民國 Republic of China 西藏 土伯特 唐古特 Tibet 達賴喇嘛 Dalai Lama 法輪功 Falun Dafa 新疆維吾爾自治區 The Xinjiang Uyghur Autonomous Region 諾貝爾和平獎 Nobel Peace Prize 劉暁波 Liu Xiaobo 民主 言論 思想 反共 反革命 抗議 運動 騷亂 暴亂 騷擾 擾亂 抗暴 平反 維權 示威游行 李洪志 法輪大法 大法弟子 強制斷種 強制堕胎 民族淨化 人體實驗 肅清 胡耀邦 趙紫陽 魏京生 王丹 還政於民 和平演變 激流中國 北京之春 大紀元時報 九評論共産黨 獨裁 專制 壓制 統一 監視 鎮壓 迫害 侵略 掠奪 破壞 拷問 屠殺 活摘器官 誘拐 買賣人口 遊進 走私 毒品 賣淫 春畫 賭博 六合彩 天安門 天安门 法輪功 李洪志 Winnie the Pooh 劉曉波动态网自由门

Listen to me carefully, paid PRC shills: Emperor Winnie the Pooh and your army of mindless drones will never win as long as there are people like me who do this for free.

**Comment by ner00** [comment]
(eye rolling)
