### ISSUE TITLE
Right-click Copy in Find-result window can source redundant data

### ISSUE THREAD

**Issue by sasumner** [notepad-plus-plus/notepad-plus-plus#8580]
### Steps to Reproduce (STR) the Issue
1. Create a new document tab and add the text `aaaaaaaaaa` to it
2. Do a simple _Find All in Current Document_ search on `a`
3. Observe the (correct) output in the _Find result_ window:
![image](https://user-images.githubusercontent.com/30118311/87820598-5b164300-c83c-11ea-9557-20f0e4e7d059.png)
4. Right-click inside the _Find result_ window, choose _Select all_ from the popup menu; observe:
![image](https://user-images.githubusercontent.com/30118311/87821932-a29dce80-c83e-11ea-86d4-eceed55a850d.png)
5. Right-click the selected text inside the _Find result_ window, choose _Copy_ from the popup menu:
![image](https://user-images.githubusercontent.com/30118311/87822045-d5e05d80-c83e-11ea-8071-18a8650cfe1c.png)
6. Create a new document tab and Ctrl+v paste the clipboard contents into it; observe:
![image](https://user-images.githubusercontent.com/30118311/87820849-d37d0400-c83c-11ea-8b9f-69e1b7d405bb.png)

### Expected Behavior
I expect only unique line data to be copied with the _Find result_ window's right-click _Copy_ option, since it really is a Copy-Special type command.  I would probably feel differently if the hit-styling (red text on yellow background) came along with the copy, but since it is pure text data, there's no point in a single line occurring more than one time.

### Actual Behavior
Above, in STR.

### Debug Information
Notepad++ v7.8.9   (32-bit)
Build time : Jul 15 2020 - 20:26:50
Path : C:\\....................\npp.7.8.9.bin\notepad++.exe
Admin mode : OFF
Local Conf mode : ON
OS Name : Windows 10 Enterprise (64-bit) 
OS Version : 1809
OS Build : 17763.1039
Current ANSI codepage : 1252
Plugins : mimeTools.dll NppConverter.dll NppExport.dll

**Comment by sasumner** [comment]
Do others have a different feeling about this than I do?
I certainly welcome being shown the utility of something that I consider a defect. :-)

**Comment by Ekopalypse** [comment]
I agree with you, I would also expect only one line to be copied.

**Comment by sasumner** [comment]
Changes from this issue released in Notepad++ version 7.9
