### ISSUE TITLE
去死吧，垃圾

### ISSUE THREAD

**Issue by hjli1988** [notepad-plus-plus/notepad-plus-plus#8583]
如题，去死吧，

**Comment by hjli1988** [comment]
希望你的英美爹能在你这么努力的舔他后多给你点屎吃，
另外希望你去你美爹那感受 群体免疫 及由此带来的美式民主自由的香甜

**Comment by ruantu** [comment]
粉蛆乘早洗洗睡吧, 坐等习包子发布新的speed++编程语言

**Comment by mraandtux** [comment]
Shut this down boys, the OP deserves to see [the whole picture](https://en.wikipedia.org/wiki/2019%E2%80%9320_Hong_Kong_protests)!

（楼主是时候[看看这个了](https://zh.wikipedia.org/wiki/%E5%8F%8D%E5%B0%8D%E9%80%83%E7%8A%AF%E6%A2%9D%E4%BE%8B%E4%BF%AE%E8%A8%82%E8%8D%89%E6%A1%88%E9%81%8B%E5%8B%95)）

**Comment by franklin776283** [comment]
https://preview.redd.it/ercvmtkil6b51.jpg?width=1080&format=pjpg&auto=webp&s=b820965ee35ee08a15791ea161f006716c6cd0ab

https://preview.redd.it/j2z7noy2n6b51.jpg?width=1080&format=pjpg&auto=webp&s=3af6830d2dba2c2432b5477dc16c5c411f9c53fe

your loved 胡锡进

**Comment by hjatime** [comment]
I have already reported your abuse behavior

**Comment by dakemalone** [comment]
坐等github被墙，粉蛆准备一下用中莽，易语言，丙正正编程，光我中华。

**Comment by Hickoo** [comment]
傻逼粉红真可怜，看看点赞的和点踩的，心里没点逼数？

**Comment by Hickoo** [comment]
> 坐等github被墙，粉蛆准备一下用中莽，易语言，丙正正编程，光我中华。

易语言我在用呢，风评被害
