### ISSUE TITLE
Newbie here - end user

### ISSUE THREAD

**Issue by janderson835** [notepad-plus-plus/notepad-plus-plus#8586]
I discovered this wonderful gift from Heaven after much frustration with Windows Notepad.  I was using W-NP gathering info for my research for a final result into Microsoft Word.  Figuring there HAS to be something better out there than W-NP, one of my searches was Notepad ++ and I stopped looking for anything else.
NP-++ saves name of previous docs that I can open, no more now Where is my last file and where did I save it to?
There are a couple items that I could use, but they are probably already in NP++

I want to be able to click on the path of a file on my computer and go right to that folder/file.  Some google searches show I can go to web pages, but I think the coding is different for going to my own computer.

If a graphic file then can NP++ call up a graphic viewer like Xnview to show the graphic?  Xnview closes by the escape key, very handy.

The 2nd item I would like and I am an end user - can the shaded lines be hidden?  Or something like the document names that can be moved way over to the left to practically hide the doc names when not needed right away.

My last question, I love Microsoft Onenote desktop, so that's why I appreciated the Doc Switcher so much.  I don't understand however, why the files are both at the left and also on the top?  I know the Switcher can be closed, but it can also be dragged over to the left to hide. And now that I closed the Doc Switcher, there is nothing to show how to get it back.  

A suggestion - I am seeing "Fold" and "Fold/Unfold All" - what is that and what is it used for?  Same thing for collapse, and project.  Is there a Help place new users can visit?  Love the program, and I did some Basic decades ago.  Dabbled in Html just enough to decide to let others do it.  But I do want to get the most out of Notepad++

**Comment by Ekopalypse** [comment]
>  Is there a Help place new users can visit?

https://community.notepad-plus-plus.org

**Comment by sasumner** [comment]
Closing because this is more a bunch of questions rather than issues, and @Ekopalypse has redirected to correct place.
