### ISSUE TITLE
Bug when indent 'folded code' in python language

### ISSUE THREAD

**Issue by Makysdd** [notepad-plus-plus/notepad-plus-plus#8587]
### Steps to Reproduce the Issue

1. Switch language to python
2. Write a line of text
3. Write another line below
4. Press tab to indent the last line
5. Click '-' on the left of the upper line
6. The last line disappeared

### Expected Behavior

The last line should not disappear
because it is python so the folded lines and be indent too

### Actual Behavior

The last line disappeared

### Debug Information

Notepad++ v7.8.7   (64-bit)
Build time : Jun  5 2020 - 02:38:56
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS Name : Windows 10 Pro (64-bit) 
OS Version : 1909
OS Build : 18363.900
Current ANSI codepage : 936
Plugins : mimeTools.dll NppConverter.dll NppExport.dll

**Comment by Ekopalypse** [comment]
If I understand correctly, then this is exactly what I would expect it to happen.
