### ISSUE TITLE
on clickable links - mouse cursor is flickering

### ISSUE THREAD

**Issue by jablka** [notepad-plus-plus/notepad-plus-plus#8588]
I have "clickable links" enabled,

and have noticed significant mouse cursor flickering when mouse is over the link
in Notepad++

It hasn't been before, I suspect some new version of Notepad++ started this...

Anybody experience the same? :-( 
Please fix this...

**Comment by jablka** [comment]
I just found out that the last stable version (without mouse cursor flickering while sliding over links) was Notepad++ 7.8.6
Onwards versions are flickering...

**Comment by Ekopalypse** [comment]
I don't have it on Windows 7 but can see it on Windows 10 as well.

**Comment by Yaron10** [comment]
@Ekopalypse,

> I don't have it on Windows 7

On my Windows 7 the flickering is intense and extremely annoying.
It's possible that some *system-setting* makes the difference rather than the OS.
Can you compare your system-settings and think of a potential culprit?

Thank you.

**Comment by Yaron10** [comment]
`Control Panel -> Mouse -> Pointers -> Theme`.

Changing the theme from `Windows Aero` to `None` or `Windows Regular` - there's no flickering in NPP.

@Uhf7,
I don't want to change the theme system-wide.
Would it be possible to set a non-flickering hand-cursor for hovering over links in NPP?

**Comment by Ekopalypse** [comment]
@Yaron10 - yes, changing from None to the aero theme results in the same flickering

**Comment by Yaron10** [comment]
@Ekopalypse,

Thank you.

**Comment by Uhf7** [comment]
I cannot confirm that the flickering problem can be solved on Windows 7 by changing the `Control Panel -> Mouse -> Pointers -> Theme` option. On my Windows 7 system, the flicker continues in all tested settings: `Aero`, `(none)` and `Windows Regular`.

I observed also, that the flicker is sometimes strong and annoying, and sometimes barely visible. And that on Windows 10. Until now, I'm unable to reproduce, when it is strong, and when it is barely visible. I assume, it is a timing/refresh/monitor problem, which makes the flicker sometimes more visible and sometimes less.

The reason for the flicker seems to be Scintilla itself, as I explained in the PR above. I tested the described solution on Windows 10 and Windows 7. Today, I had a strong flicker on both systems with the original `SciLexer.dll`, which I could remove with the `SciLexer.dll` from the PR.

**Comment by Yaron10** [comment]
@Uhf7,

Thank you for https://github.com/notepad-plus-plus/notepad-plus-plus/pull/8641.
Can you upload your modified `SciLexer.dll`?

**Comment by sasumner** [comment]
>Can you upload your modified SciLexer.dll?

Can't you grab it here for example:
https://ci.appveyor.com/project/donho/notepad-plus-plus/builds/34393201/job/09wvpbt49qlnwls9/artifacts

Will you run into non-signed issues with this?  I'm uncertain as we usually don't muck with Scintilla DLL this way. :-)

**Comment by Yaron10** [comment]
@sasumner,

Thank you.

I can not run the unsigned DLL with the original EXE.
I can remove the unsigned-check but I've reverted to the old `addHotSpot` because of the flickering (I have some files with a lot of links), and re-changing that code might take some time. :)
I'll wait for the time being.

**Comment by Yaron10** [comment]
I've removed the unsigned-check, changed to the new `addHotSpot` and used the DLL from https://ci.appveyor.com/project/donho/notepad-plus-plus/builds/34393201/job/09wvpbt49qlnwls9/artifacts.

Links are not underlined and there's no change on hover.
With the original DLL, I get the new `addHotSpot` behavior.

**Comment by Yaron10** [comment]
Well, it works with *no flickering* if I use the original `#define URL_REG_EXPR "[A-Za-z]+://[A-Za-z0-9_\\-\\+~.:?&@=/%#,;\\{\\}\\(\\)\\[\\]\\|\\*\\!\\\\]+"`.

Changing to `#define URL_REG_EXPR "(http|ftp|https)://([\\w-]+(?:(?:\\.[\\w-]+)+))([\\w.,@?^=%&:/~+#-]*[\\w@?^=%&/~+#-])?"`, links are not underlined and there's no change on hover.

But why should the EXE with `#define URL_REG_EXPR "(http|ftp|https)://([\\w-]+(?:(?:\\.[\\w-]+)+))([\\w.,@?^=%&:/~+#-]*[\\w@?^=%&/~+#-])?"` work with the original DLL and not with the modified one?

**Comment by Uhf7** [comment]
You can use the debug version of the `Notepad++.exe` artifact, then you don't run into signing problems. Best to use with a `SciLexer.dll` artifact of the same architecture. The simplest way is to use the debug version of the `SciLexer.dll` too.  Both can be found here:

- Debug 32 Bit: https://ci.appveyor.com/project/donho/notepad-plus-plus/builds/34393201/job/uwxyk57pg30bcfc9/artifacts
- Debug 64 Bit: https://ci.appveyor.com/project/donho/notepad-plus-plus/builds/34393201/job/w7r1i38kkr7ab50t/artifacts

**Comment by Yaron10** [comment]
@sasumner,

Can you please replace

`#define URL_REG_EXPR "[A-Za-z]+://[A-Za-z0-9_\\-\\+~.:?&@=/%#,;\\{\\}\\(\\)\\[\\]\\|\\*\\!\\\\]+"`
with
`#define URL_REG_EXPR "(http|ftp|https)://([\\w-]+(?:(?:\\.[\\w-]+)+))([\\w.,@?^=%&:/~+#-]*[\\w@?^=%&/~+#-])?"`

and then use the original DLL and the latest unsigned one?
Are links clickable?

I suppose your build is Debug and you wouldn't have to comment the following block in ScintillaEditView.cpp.

```
#ifndef _DEBUG
	SecurityGard securityGard;
	bool isOK = securityGard.checkModule(sciLexerPath, nm_scilexer);

	if (!isOK)
	{
		::MessageBox(NULL,
			TEXT("Authenticode check failed:\rsigning certificate or hash is not recognized"),
			TEXT("Library verification failed"),
			MB_OK | MB_ICONERROR);
		return nullptr;
	}
#endif // !_DEBUG
```

Thank you.

**Comment by sasumner** [comment]
>Are links clickable?

Which links?  ANY links?
I'm not opposed to trying things, but I like a bit of a roadmap to know where I'm going and why. :-)

**Comment by Yaron10** [comment]
This: https://github.com/notepad-plus-plus/notepad-plus-plus

Thanks.
