### ISSUE TITLE
Crash when open .nfo file

### ISSUE THREAD

**Issue by byzod** [notepad-plus-plus/notepad-plus-plus#8589]
### Description of the Issue
Crash

### Steps to Reproduce the Issue

1. Create any text file and rename to 1.nfo
2. Open with npp

### Actual Behavior
![A1](https://user-images.githubusercontent.com/848607/87873824-3dd9a400-c9f7-11ea-8cb0-a62ac6037356.gif)

### Debug Information
Notepad++ v7.8.6   (64-bit)
Build time : Apr 21 2020 - 15:23:03
Path : K:\App\Something\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : ON
OS Name : Windows 10 Pro (64-bit) 
OS Version : 1703
OS Build : 15063.850
Plugins : ComparePlugin.dll CSharpRegexTools4Npp.dll EmmetNPP.dll HexEditor.dll JSMinNPP.dll mimeTools.dll NppConverter.dll NppExport.dll NppTextViz.dll PythonScript.dll

**Comment by donho** [comment]
Cannot be reproduced.
Could you remove all the plugins then try again?
If it doesn't crash without plugins. Please add back 1 by 1 to know which plugin is culprit. And please let us know.

**Comment by Ekopalypse** [comment]
I would start with the HexEditor plugin.

**Comment by donho** [comment]
@byzod  I close this issue for the missing information.
You can open it again by providing the info.

**Comment by PeterCodar** [comment]
In my case it is definitely the manually installed HexEditor plugin. 
Source: https://github.com/chcg/NPP_HexEdit/releases

As soon I remove the HexExitor plugin, the *.NFO can be opened without crash.

**Comment by KnIfER** [comment]
A fresh openning of nfo file will trigger the IDM_FILE_RELOAD message. Other formats won't.

**Comment by KnIfER** [comment]
New issue : When nfo files get activated, it will be reloaded automatically if it's charset is not OEM-US.
