### ISSUE TITLE
Tab switcher doesn't respect system DPI

### ISSUE THREAD

**Issue by chashitsu** [notepad-plus-plus/notepad-plus-plus#859]
I have notebook with high display resolution so I have to use "size of text" setting in windows 10 with value 200%. Notepad++ looks OK but tab switcher (Ctrl+Tab) doesn't respect the DPI. It's very small like many other old non DPI compatible programs.
![notepadbug](https://cloud.githubusercontent.com/assets/3748222/9701014/c0b51daa-5418-11e5-90a9-68caa4f817f8.png)

**Comment by h-h-h-h** [comment]
Please merge your issue into issue https://github.com/notepad-plus-plus/notepad-plus-plus/issues/571 and close this one.

**Comment by chashitsu** [comment]
I don't know the best practice for "merge issue". I suppose that link from #571 to this is sufficient. So I am closing this.
