### ISSUE TITLE
Stand with Your Mom

### ISSUE THREAD

**Issue by KinglittleQ** [notepad-plus-plus/notepad-plus-plus#8592]
### Description of the Issue

Stand with your mom.

### Steps to Reproduce the Issue

1.  Open the door
2.  Put your mom in
3.  Close the door

### Expected Behavior

Boom boom boom

### Actual Behavior

Guess?

**Comment by hjatime** [comment]
I have reported your abuse behavior: Threat the author's family member with violence in this page.

You may be a terrorist in mainland China, and every user in GitHub has the responsibility to report your abusive behavior.

**Comment by hjatime** [comment]
I have reported your abuse behavior: Threat the author's family member with violence on this page.

You may be a terrorist FROM mainland China, and every user in GitHub has the responsibility to report your abusive behavior.

**Comment by japaripark-library** [comment]
People should not be afraid of their governments, governments should be afraid of their people.——V for Vendetta
So,I want to notice some PRC troll,when you hear some sound is different from your government.Please hear them first,instead of attack who call the sound.
