### ISSUE TITLE
Evidance! Please show us the evidance about human rights in China!

### ISSUE THREAD

**Issue by SipengWang** [notepad-plus-plus/notepad-plus-plus#8594]
### Please show us the evidance that there is no Human Right in China. If you can't, please DO NOT say anything!
Hi all,
I'm just an everyman from China. I'm sure most people here have received or are receiving higher education. So do I. I think one of the most import things people with higher education is **evidance**. I know you westeners always think that we Chinese don't have human rights, so show me the evidance, the evidance that I totally **haven't felt** during my last 20s years.
<br/>
I know some of you may say what you westen medias reported about Xinjiang, about Tibet. If I guess right, most of the news and impression you get is from your local medias. But please take a while and have a double thinking: 
<br/>
**Does your media worth your trust?**
<br/>
Media said COVID-19 is just an ordinary flu -- Thousands of people died from it.
Media said all people are equal -- **Black lives matters. I can't breath**
Media said people's privacy is protected in USA -- See PRISM
<br/>
You westerners, just open your eyes and watch China today. It is not the China tens of years ago. What your leaders scared is not the human rights in China, but the raising CHINA! 
<br/>
I sincerely invite you to come to China and have a look at this great country. Chairmen Mao Zedong said that without investigation there is no right to speak. In China, at least I'm not afraid of being shooted in street, I'm not afraid of starving and I'm not afraid of falling ill. What about you Americans?
<br/>
**Taiwan is always a province of China**

**Comment by franklin776283** [comment]
**Does your offical China media worth your trust?**
**Have you ever really see US media or just hear what your offical media say?**
Do you have links for your 3 examples?

You esterners, just open your eyes and watch US today. It is not the US tens of years ago. What your leaders scared is not the human rights in US, but the strong UNTIED STATES!

Not only US bus also almost all nations dont like ccp.

**Comment by FranciscoPombal** [comment]
动态网自由门 天安門 天安门 法輪功 李洪志 Free Tibet 六四天安門事件 The Tiananmen Square protests of 1989 天安門大屠殺 The Tiananmen Square Massacre 反右派鬥爭 The Anti-Rightist Struggle 大躍進政策 The Great Leap Forward 文化大革命 The Great Proletarian Cultural Revolution 人權 Human Rights 民運 Democratization 自由 Freedom 獨立 Independence 多黨制 Multi-party system 台灣 臺灣 Taiwan Formosa 中華民國 Republic of China 西藏 土伯特 唐古特 Tibet 達賴喇嘛 Dalai Lama 法輪功 Falun Dafa 新疆維吾爾自治區 The Xinjiang Uyghur Autonomous Region 諾貝爾和平獎 Nobel Peace Prize 劉暁波 Liu Xiaobo 民主 言論 思想 反共 反革命 抗議 運動 騷亂 暴亂 騷擾 擾亂 抗暴 平反 維權 示威游行 李洪志 法輪大法 大法弟子 強制斷種 強制堕胎 民族淨化 人體實驗 肅清 胡耀邦 趙紫陽 魏京生 王丹 還政於民 和平演變 激流中國 北京之春 大紀元時報 九評論共産黨 獨裁 專制 壓制 統一 監視 鎮壓 迫害 侵略 掠奪 破壞 拷問 屠殺 活摘器官 誘拐 買賣人口 遊進 走私 毒品 賣淫 春畫 賭博 六合彩 天安門 天安门 法輪功 李洪志 Winnie the Pooh 劉曉波动态网自由门

Listen to me carefully, paid PRC shills: Emperor Winnie the Pooh and your army of mindless drones will never win as long as there are people like me who do this for free.

**Comment by ner00** [comment]
I believe western democratic regimes are overall better than China's. That being said, I don't feel comfortable when I see westerners talking down to Chinese based on their ignorance of the country and culture. When y'all stop pretending and acknowledge that you live in luxury because China and its citizens makes it affordable to you, especially in the tech sector, we can skip past all the hypocrisy and take the subject seriously, until then go do some introspection.

**Comment by FranciscoPombal** [comment]
> That being said, I don't feel comfortable when I see westerners talking down to Chinese based on their ignorance of the country and culture.

The only one here being ignorant is you.

> When y'all stop pretending and acknowledge that you live in luxury because China and its citizens makes it affordable to you, especially in the tech sector, we can skip past all the hypocrisy and take the subject seriously, until then go do some introspection.

This is such a retarded smoothbrain way of looking at things and justifying the actions of the Chinese oppressive government I'm not even going to dignify it by addressing it. Figure it out for yourself, honestly. Go away, you sad little pro-Chinese government troll.

**Comment by ner00** [comment]
It's inconsequential whether you address it or not, the whole modern western civilization has essentially been riding the PRC wave for decades, and now you play the shining white knight without acknowledging your substantial role in making it what it is and what you've set out to despise... just pathetic.

**Comment by FranciscoPombal** [comment]
> It's inconsequential whether you address it or not,

Not everyone is a loser like you that just admits defeat like that.

> the whole modern western civilization has essentially been riding the PRC wave for decades, and now you play the shining white knight without acknowledging your substantial role in making it what it is and what you've set out to despise... just pathetic.

Sure the West has had its fair share of bad/corrupt leaders who chose the easy way of taking advantage of the PRC's (essentially) slave labor. But their are at least 2 parties in every transaction. The PRC was 100% complicit and took advantage of every shady deal the West threw their way, gladly. Everything that benefited their elites was/is fair game, even at the cost of their own people. . But poor little PRC, they were abused!!! LOL, you are such a tool.

If it were up to me, the West would cut ties with China completely tomorrow. The interesting thing is, that China would most likely collapse as a result. Despite what you might think, China needs the West to buy its products much more than the West needs China.

**Comment by LegoLivesMatter** [comment]
@ner00 @SipengWang 

How many good boy points is Xinnie the Pooh paying you for this?

**Comment by cirosantilli** [comment]
Look at those Xinjiang people, they're having the time of their lives!!!

American Imperialist Lies!!!!

Heil Xi.

https://github.com/cirosantilli/china-dictatorship/tree/e4dc8335e89b49b34fc086980c13d48fe805c184#xinjiang

<img src="https://web.archive.org/web/20200518075230im_/https://ichef.bbci.co.uk/news/320/cpsprodpb/1FAB/production/_107470180_dsc05820.jpg" height=500 />
