### ISSUE TITLE
Win 10 Friendly Name keeps changing back to long title

### ISSUE THREAD

**Issue by GWdd** [notepad-plus-plus/notepad-plus-plus#8596]
### Description of the Issue
Context menu clutter in Windows (7 & 10)

### Steps to Reproduce the Issue
1. Right click any file meeting context criteria (.txt,) or select Open with ...
2. Context menu shows  "Notepad++: a free (GNU) source code editor" 
3. Edit registry to change friendly name to "Notepad++" 
4. Wait a few days and Friendly name reverts to "Notepad++: a free (GNU) source code editor"

### Expected Behavior
After changing the long name to something reasonable in a pull  down menu, I expect the change to stick. I think the app monitors the Friendly name and changes it back to the long version.

### Actual Behavior
Friendly name is not sticky, as it should be.

### Debug Information

Notepad++ v7.8.8   (64-bit)
Build time : Jun 23 2020 - 23:59:56
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS Name : Windows 10 Pro (64-bit) 
OS Version : 2004
OS Build : 19041.388
Current ANSI codepage : 1252
Plugins : mimeTools.dll NppConverter.dll NppExport.dll

**Comment by Uhf7** [comment]
Where did you enter your preferred name in the registry?

Here?
`[HKEY_CURRENT_USER\SOFTWARE\Classes\Local Settings\Software\Microsoft\Windows\Shell\MuiCache]`
`"C:\Program Files\Notepad++\notepad++.exe.FriendlyAppName"="Notepad++"`

Or here?
`[HKEY_CLASSES_ROOT\Applications\notepad++.exe]`
`"FriendlyAppName"="Notepad++"`

Or here?
`[HKEY_CLASSES_ROOT\Applications\notepad++.exe\shell\open]`
`"FriendlyAppName"="Notepad++"`

The 1st one seems to be overwritten by Windows with the file description field of the version info in the `Notepad++.exe`, every time Windows reads this info for whatever reason.

The last two ones work on my system (Windows 10 Pro (64-bit) 1607 14393.576). If I specify both, the 3rd one is preferred in the "Open With" context menu. The string values are not there by default, you will have to create them. I don't know, whether they survive the installation of a new Notepad++ version, but I'm quite sure, that `Notepad++.exe` itself doesn't touch them.

**Comment by GWdd** [comment]
The only entry I have changed, the only place the entire GNU reference is found within the registry, and keeps reverting back, is changing :
`Computer\HKEY_CLASSES_ROOT\Local Settings\Software\Microsoft\Windows\Shell\MuiCache\`
`C:\Program Files\Notepad++\notepad++.exe.FriendlyAppName` to `Notepad++`

**Comment by GWdd** [comment]
Adding a new string key to here, works.

[HKEY_CLASSES_ROOT\Applications\notepad++.exe\shell\open]
FriendlyAppName=Notepad++
