### ISSUE TITLE
uninstall

### ISSUE THREAD

**Issue by helloHupc** [notepad-plus-plus/notepad-plus-plus#8599]
![image](https://user-images.githubusercontent.com/40000021/88032330-620cc080-cb70-11ea-9d99-d32fb417636a.png)

**Comment by FranciscoPombal** [comment]
动态网自由门 天安門 天安门 法輪功 李洪志 Free Tibet 六四天安門事件 The Tiananmen Square protests of 1989 天安門大屠殺 The Tiananmen Square Massacre 反右派鬥爭 The Anti-Rightist Struggle 大躍進政策 The Great Leap Forward 文化大革命 The Great Proletarian Cultural Revolution 人權 Human Rights 民運 Democratization 自由 Freedom 獨立 Independence 多黨制 Multi-party system 台灣 臺灣 Taiwan Formosa 中華民國 Republic of China 西藏 土伯特 唐古特 Tibet 達賴喇嘛 Dalai Lama 法輪功 Falun Dafa 新疆維吾爾自治區 The Xinjiang Uyghur Autonomous Region 諾貝爾和平獎 Nobel Peace Prize 劉暁波 Liu Xiaobo 民主 言論 思想 反共 反革命 抗議 運動 騷亂 暴亂 騷擾 擾亂 抗暴 平反 維權 示威游行 李洪志 法輪大法 大法弟子 強制斷種 強制堕胎 民族淨化 人體實驗 肅清 胡耀邦 趙紫陽 魏京生 王丹 還政於民 和平演變 激流中國 北京之春 大紀元時報 九評論共産黨 獨裁 專制 壓制 統一 監視 鎮壓 迫害 侵略 掠奪 破壞 拷問 屠殺 活摘器官 誘拐 買賣人口 遊進 走私 毒品 賣淫 春畫 賭博 六合彩 天安門 天安门 法輪功 李洪志 Winnie the Pooh 劉曉波动态网自由门

Listen to me carefully, paid PRC shills: Emperor Winnie the Pooh and your army of mindless drones will never win as long as there are people like me who do this for free.

**Comment by franklin776283** [comment]
just do it

**Comment by ner00** [comment]
As much as I think some Npp "devs" are being douche with this political BS, the software itself is still great; so no, I don't stand with anything or anyone besides my computer and Npp, issue resolved, Honk Kong could be hit by a tsunami right-now and it wouldn't affect me in any way (not nearly as much as COVID-19, I mean).

**Comment by ner00** [comment]
@FranciscoPombal Open-source software is still freely available regardless of the color of my skin, political affiliation, ideology or gender? In that case, nobody cares about you or your convictions. There are hundreds of thousands of programmers who contribute and keep contributing to projects like this, and for the most part refraining from childish behaviors like these, copy/pasting political statements in a programming-focused platform as if you're on Facebook or some other social networking platform. Just cut the act, pledges of solidarity only get you so far.

**Comment by FranciscoPombal** [comment]
@ner00 

Not all political topics are appropriate to mix with FOSS (namely bullshit identity politics), but everything pertaining to Freedom absolutely is.

This is not an "act". It is absolutely the duty of every Freedom-defending human to stand up against Winnie the Pooh's anti-Freedom hordes. It is our duty to show that as long as they behave like they do, they are NOT welcome. Attackers of Freedom are NOT welcome.

> Open-source software is still freely available regardless of the color of my skin, political affiliation, ideology or gender? In that case, nobody cares about you or your convictions.

Perhaps you should take your own advice and stop being so butthurt about simple statements about Freedom. Are you some kind of PRC shill? If you stand for FOSS and the GPL, you must also stand for Freedom in general, and this means, among other things, standing up against the current anti-Freedom Chinese government. Otherwise you're just an amoral weakling poseur, just like all the BSD/MIT license cucks and bootlickers and "OSS" (without the "F") crowd.

I would wish for nothing more than for the Chinese people to rebel, overthrow their tyrannical government, and free themselves. Until then, we must fight PRC attacks on our Freedom.

**Comment by ner00** [comment]
There's nothing simple about it. You are trying to hijack FOSS to suit an agenda, I'm not okay with that. I couldn't care less about your morals, or anyone's morals for that matter. I care about FOSS, and I can see that some blood-sucking insects have gotten hold of FOSS to virtue signal the hell out of each other in some awkward popularity contest. For you to come to your senses, and realize that FOSS is no places for your BS, that's what I wish for.

**Comment by FranciscoPombal** [comment]
@ner00 

> I care about FOSS, and I can see that some blood-sucking insects have gotten hold of FOSS to virtue signal the hell out of each other in some awkward popularity contest. 

Don't mistake me for some identity politics/cancel culture pusher. Those will get what's coming to them someday as well.

> There's nothing simple about it. You are trying to hijack FOSS to suit an agenda, I'm not okay with that. I couldn't care less about your morals, or anyone's morals for that matter.

No one is "hijacking" anything. FOSS is all about a very specific agenda at its core, or have you forgotten? https://www.gnu.org/philosophy/free-sw.html.

> For you to come to your senses, and realize that FOSS is no places for your BS, that's what I wish for.

FOSS doesn't have time for people like you, who don't know what the "F" stands for, apparently.

**Comment by ner00** [comment]
> 
> 
> @ner00
> 
> > I care about FOSS, and I can see that some blood-sucking insects have gotten hold of FOSS to virtue signal the hell out of each other in some awkward popularity contest.
> 
> Don't mistake me for some identity politics/cancel culture pusher. Those will get what's coming to them someday as well.
> 
> > There's nothing simple about it. You are trying to hijack FOSS to suit an agenda, I'm not okay with that. I couldn't care less about your morals, or anyone's morals for that matter.
> 
> No one is "hijacking" anything. FOSS is all about a very specific agenda at its core, or have you forgotten? https://www.gnu.org/philosophy/free-sw.html.
> 
> > For you to come to your senses, and realize that FOSS is no places for your BS, that's what I wish for.
> 
> FOSS doesn't have time for people like you, who don't know what the "F" stands for, apparently.

There is no mistaking, the same utterances are almost carbon copies. 

You are clearly a very confused person, there was little point in our discussion, and there is clearly none now.

**Comment by FranciscoPombal** [comment]
You are clearly a sad little shill/troll, just go away, you'll never win.
