### ISSUE TITLE
Most recent version of Notepad++ has a big issue

### ISSUE THREAD

**Issue by ner00** [notepad-plus-plus/notepad-plus-plus#8603]
Just like Notepad++, seems like we need to turn Github into a political discourse platform. Who comes up with the names for releases and why are those people incapable of separating the open source world from political idiology?

The issue is that Npp introduces politics with the release names, that's a bad move no matter how good the intentions behind it are. It is very inappropriate to be virtue signaling using an open source piece of software that has been created by hundreds of people, whom had the common sense to put their political ideologies aside when contributing to this great software.

That being said, where is the _Stand with Yemen_ release? I've been waiting on it for a while... I mean, you get the point, these political release names are self-serving adulation. At which point do you decide to make open source a political token that reflects your political statements?

Sorry for being that guy. I also don't feel the need to state my political ideologies to get some validation about the point I'm making. The attitude behind the political release names is childish, period.

**Comment by FranciscoPombal** [comment]
@ner00 

There is absolutely no problem.

As a reminder, _not all political topics are appropriate to mix with FOSS (namely bullshit identity politics), but everything pertaining to Freedom absolutely is._

And also, the "F" in FOSS stands for Freedom, in case you haven't noticed.

> The attitude behind the political release names is childish, period.

The attitude behind not standing up for Freedom in a FOSS project, and pretending that, at least in matters related to Freedom, FOSS is not inherently political, is childish, period. If you're too much of a "muh no politics in software!!1!" snowflake to live with- and understand that, go find another job/hobby, or limit yourself to contributing to non-GPL projects.
