### ISSUE TITLE
No polity! Stop stupid behavior!!!

### ISSUE THREAD

**Issue by stekovinbranturry** [notepad-plus-plus/notepad-plus-plus#8605]
![image](https://user-images.githubusercontent.com/33021960/88247944-1c680900-ccd2-11ea-8854-3f27d3a055e3.png)
![image](https://user-images.githubusercontent.com/33021960/88247957-22f68080-ccd2-11ea-94f1-c0324c624eba.png)
![image](https://user-images.githubusercontent.com/33021960/88247965-2a1d8e80-ccd2-11ea-8ade-7d53de3eea6a.png)

WHAT THE FUCK ARE THESE?

JUST DO YOUR CODING THING!

JUST STOP THESE NAIVE THING!!!

**Comment by zaghost** [comment]
The maintainer even don't know what he is doing. He is doing code everyday and have no time to figure out the real truth.
