### ISSUE TITLE
Possible grammatical error in the Notepad++ title

### ISSUE THREAD

**Issue by aklingam7** [notepad-plus-plus/notepad-plus-plus#8606]
### Possible grammatical error in the Notepad++ title in Windows 10
A possible grammatical error in the Notepad++ title which shows up in the windows "open with" menu.

### Steps to Reproduce the Issue
1. Right-click any text document in windows
2. Go to the open with menu and select choose another app
3. If Notepad++ isn't an option add it by selecting look for another app on this PC

### Expected Behavior
I probably should say "Notepad++: a free (GNU) source code editor"

### Actual Behavior
It says "Notepad++ : a free (GNU) source code editor"
![](https://i.imgur.com/lxtulYi.png)
![Uploading Screenshot (16).png…]()

### Debug Information
Notepad++ v7.8.9   (32-bit)
Build time : Jul 15 2020 - 20:26:50
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS Name : Windows 10 Home (64-bit) 
OS Version : 1903
OS Build : 18362.959
Current ANSI codepage : 1252
Plugins : mimeTools.dll NppConverter.dll NppExport.dll

**Comment by donho** [comment]
It could be a minor grammatical error, but I prefer to separate + and : with a space.

**Comment by sasumner** [comment]
I can't believe that this was even logged as an issue...
