### ISSUE TITLE
[Feature Request] Use Notepad++ to Create a Dated Log or Journal File

### ISSUE THREAD

**Issue by xmha97** [notepad-plus-plus/notepad-plus-plus#8610]
Hi,
Please implement this feature:
https://www.howtogeek.com/258545/how-to-use-notepad-to-create-a-dated-log-or-journal-file/
![Notepad](https://www.howtogeek.com/wp-content/uploads/2016/06/00_lead_image_sample_log_file.png)
Thanks

**Comment by Ekopalypse** [comment]
If you use one of the scripting plugins like python script you can do it already. Has the advantage that you can format it like you want to have it.

**Comment by sasumner** [comment]
@xmha97 I found an example of how to Pythonscript this functionality, here:  https://community.notepad-plus-plus.org/topic/17738/textfx-customizing-the-date-time-format
