### ISSUE TITLE
[Feature Request] Duplicate Kate editor's document map.  Also create edit markers on edited lines

### ISSUE THREAD

**Issue by MarkGibb** [notepad-plus-plus/notepad-plus-plus#8611]
I use the Kate editor on my Linux desktop.  I have come to depend on two features that are missing/incomplete in my other favorite editor, Notepad++.  Thanks in advance for reading this.

Document map:  basically, I want the exact functionality that Kate has.  It shows the whole document.  It also seems more visible.

Line edited marks:  Kate has a feature that shows all the lines that have been edited since the document was opened.  I have grown to depend on this to know what I have done in the code.  The marks also show up in the document map so it's super easy to go back and forth between areas that are under edit.  Green marks are changes that have been saved, red are unsaved edits.

Notepad++ has a plugin that kind of shows editing marks, but it's old and only works in the 32-bit version.

I've included a screen shot of Kate running in Windows with these features.

![kate_screenshot](https://user-images.githubusercontent.com/68756736/88435902-caee7580-cdc8-11ea-9aab-9c7a2f3082a9.png)

**Comment by sasumner** [comment]
Edit markers:  Have a look at the _Changed Lines_ plugin, for both 32 and 64 bit Notepad++.  Found here:  https://github.com/vinsworldcom/nppChangedLines
It works quite well.

Document map:  Notepad++ has a document map function, but there are no current plans to add change marks to it, as change marks aren't native, making it difficult.
