### ISSUE TITLE
No support for files encoded in UTF-16

### ISSUE THREAD

**Issue by Chealer** [notepad-plus-plus/notepad-plus-plus#8612]
### Description of the Issue
It appears Notepad++ (as of version 7.8.6) does not support [the UTF-16 encoding](https://en.wikipedia.org/wiki/UTF-16). It does support the similar UCS-2 encoding, which is partially compatible with UTF-16, but as UTF-16 was widely used, it would be best (as well as simpler for user) to support exact UTF-16.

### Steps to Reproduce the Issue
This is not a bug to my knowledge. I do not see UTF-16 in any of the encoding menus, and [this post](https://superuser.com/questions/1513821/notepad-save-as-utf-16-file-without-byte-order-mark#:~:text=First%2C%20Notepad%2B%2B%20doesn't,(CodePoints)%20within%202%20bytes.) suggests support is simply missing.

### Debug Information
Notepad++ v7.8.6   (64-bit)
Build time : Apr 21 2020 - 15:23:03
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS Name : Windows 8.1 Enterprise (64-bit) 
OS Build : 9600.19629
Plugins : ComparePlugin.dll mimeTools.dll NppConverter.dll NppExport.dll

**Comment by Cyrillev91** [comment]
I think it is necessary to update [PowerEditor/src/Utf8_16.cpp](https://github.com/notepad-plus-plus/notepad-plus-plus/blob/master/PowerEditor/src/Utf8_16.cpp) file with [scintilla/scite/Utf8_16.cxx](https://sourceforge.net/p/scintilla/scite/ci/default/tree/src/Utf8_16.cxx) file

**Comment by ArkadiuszMichalski** [comment]
Same/simillar to https://github.com/notepad-plus-plus/notepad-plus-plus/issues/3301.

**Comment by ArkadiuszMichalski** [comment]
@donho 
This thread and the above may already be closed?

**Comment by donho** [comment]
@ArkadiuszMichalski Yes, please close the issues that you judge can be closed.

**Comment by ArkadiuszMichalski** [comment]
Fixed by https://github.com/notepad-plus-plus/notepad-plus-plus/commit/38bf76e84312db8e60d51126acf4853201470663.

**Comment by Chealer** [comment]
Thank you @ArkadiuszMichalski 
I guess this will be solved in Notepad++ 7.10 (if not earlier).

**Comment by ArkadiuszMichalski** [comment]
Thanks should go to @Uhf7  https://github.com/notepad-plus-plus/notepad-plus-plus/pull/9599.
>I guess this will be solved in Notepad++ 7.10 (if not earlier).

Yes, but you can always test faster in the portable version:
https://github.com/notepad-plus-plus/notepad-plus-plus/wiki/Testing#using-the-current-build-version-of-notepad
or
https://github.com/notepad-plus-plus/notepad-plus-plus/wiki/Testing#using-a-pull-request-pr-build-version-of-notepad
