### ISSUE TITLE
Incorrect Cursor Direction with Adobe Activ Grotesk

### ISSUE THREAD

**Issue by wwwprof** [notepad-plus-plus/notepad-plus-plus#8613]
### Description of the Issue
The cursor is moving one character left after typing the characters "fi".

### Steps to Reproduce the Issue
1. Set typeface to Adobe Aktiv Grotesk
2. Type a lowercase f
3. Type a lowercase i

### Expected Behavior
Cursor should move to the right of the i character

### Actual Behavior
Cursor moves between f and i characters

### Debug Information
Notepad++ v7.8.9   (32-bit)
Build time : Jul 15 2020 - 20:26:50
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS Name : Windows 10 Enterprise (64-bit) 
OS Version : 1903
OS Build : 18362.959
Current ANSI codepage : 1252
Plugins : Explorer.dll LightExplorer.dll mimeTools.dll NppConverter.dll NppExport.dll

**Comment by Ekopalypse** [comment]
Did you test the new directwrite setting? It is in Settings->preferences->MISC.

**Comment by wwwprof** [comment]
That solved the problem. Thank you!
