### ISSUE TITLE
Can no longer apply alpha to current line background color.

### ISSUE THREAD

**Issue by deedub-hub** [notepad-plus-plus/notepad-plus-plus#8614]
### Description of the Issue

Even though someone reported this bug about a year ago, it still isn't resolved:
[https://github.com/notepad-plus-plus/notepad-plus-plus/issues/5619](https://github.com/notepad-plus-plus/notepad-plus-plus/issues/5619)

I wanted to file my own report so I could include a useful screen capture to illustrate how it's supposed to look when it works. It used to work in my old version 7.5.7 of Notepad++, but does not work in the latest version.

Setting a background color for the current line is a great way to help the eye quickly find that line, but by default that color will mask out all of the other colors used for syntax highlighting on that same line. The solution is to create a macro that assigns an alpha value to the current line's background color, which will allow all the syntax highlighting to show through from behind.

The macro is as follows:
`<Macro name="Caret Line Translucency" Ctrl="no" Alt="yes" Shift="no" Key="188">`
`<Action type="0" message="2470" wParam="25" lParam="0" sParam="" />`
`</Macro>`

Note that the Scintilla message number 2470 is for SCI_SETCARETLINEBACKALPHA.
The value for the wParam is the amount of opacity. 256 is fully opaque, so 25 is about 10% alpha.
Key 188 is the Comma key, but can be any desired key.

### Steps to Reproduce the Issue

In the latest version of Notepad++...
1. Add the above macro to shortcuts.xml
2. Start Notepad++
3. In Settings > Style Configurator > Global Styles > Current Line Background Color, set the background color to black.
4. Return to editing mode
5. Press Alt+[Comma key]

This screen capture is from version 7.5.7 of Notepad++, which I am still using, but I would love it if someone could fix the bug so I can use the latest version.

![image](https://user-images.githubusercontent.com/68796514/88470801-031fb200-ceb6-11ea-87bb-0481e4621214.png)

### Expected Behavior

The background color of the current line should become translucent.
### Actual Behavior

The background color of the current line remains fully opaque.
### Debug Information

Notepad++ v7.8.9   (64-bit)
Build time : Jul 15 2020 - 20:31:49
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS Name : Windows 7 Professional (64-bit) 
OS Build : 7601.0
Current ANSI codepage : 1252
Plugins : mimeTools.dll NppConverter.dll NppExport.dll

**Comment by deedub-hub** [comment]
When I was composing the text for this issue, and I included the link that points to the year-old bug report, I didn't paste the link properly, and so that link is broken. I shall re-paste it properly here.
[https://github.com/notepad-plus-plus/notepad-plus-plus/issues/5619](https://github.com/notepad-plus-plus/notepad-plus-plus/issues/5619)

**Comment by sasumner** [comment]
@deedub-hub 

>Setting a background color for the current line...by default that color will mask out all of the other colors used for syntax highlighting on that same line.

Can you help me to better understand this?

I can see other colors come through the background color on the current line with a fresh N++ 7.8.9.

Indeed, even in your "current line to black" screenshot above, I see the colors through the background color ("someVariable" is greenish, "someString" is reddish).

So I'm confused by the statement "...that color will mask out all of the other colors".

**Comment by sasumner** [comment]
Changes from this issue released in Notepad++ version 7.9
