### ISSUE TITLE
Setting to get back old save behavior without adding the selected extension

### ISSUE THREAD

**Issue by dodmi** [notepad-plus-plus/notepad-plus-plus#8615]
Hi,

this is an issue about the changed "save behavior" of Notepad++, which adds a default extension to the file name. There's already https://github.com/notepad-plus-plus/notepad-plus-plus/issues/8398, which was closed as Notepad behaves the same and will add ".txt" to the filename on saving, if you're not using a known extension. 
This seems to be reasonable on the first glance, that a user might save a file with the default extension of the program. And it seems to work in general, as it's the default Windows behavior and I didn't  have any problems with it.

But Notepad++ isn't Notepad, so I regularly fail to get the filename, I intended to get.
The behavior is depending on the extension filter, which Notepad++ preselects. I wish an option, that allows the user to define if Notepad++ should decide which filter to use (which leads to the new behavior) or to predefine an own filter (*.* would restore the old behavior)

My use cases are done with Notepad++ 7.8.9 (x86):

**Use case**: Use the "Save as" function to create a file:
Steps: File name example **.md**; Save as *[Notepad++ selects \*.txt filter]*-> Select the folder -> type filename example.md -> Hit Save
Old: Saved file example **.md**
New: Saved file example **.md.txt**
*Notepad++ provides syntax highlighting for Markdown files, but doesn't "know" the file extension*

**Use case**: Use the "Save copy as" function to create a backup:
Generally used file extensions for backup files on Windows are .bak or .old.

Steps: File name example **.ps1**; Save copy as *[Notepad++ selects \*.ps1;\*.psm filter]*-> Add extension .bak to file name -> Hit Save
Old: Saved file example **.ps1.bak**
New: Saved file example **.ps1.bak.ps1**
*Notepad++ does "know" the file extension and selects it again*

Steps: File name example **.md**; Save copy as *[Notepad++ selects \*.\* filter]*-> Add extension .bak to file name -> Hit Save
Old: Saved file example **.md.bak**
New: Saved file example **.md.bak**
*Notepad++ does not "know" the file extension, the behavior is the old*

**Comment by sasumner** [comment]
Closing this as it appears the governing of the behavior is going to be dealt with as part of 8616
