### ISSUE TITLE
Find Results: Some Improvements.

### ISSUE THREAD

**Issue by Yaron10** [notepad-plus-plus/notepad-plus-plus#8621]
**1.** Update the window title after `Clear All` in the context menu.
**2.** Add an option to word-wrap (toggle state in the context menu).
**3.** Add an option to change text direction (toggle default LTR in the context menu).  

Thank you.

**Comment by sasumner** [comment]
In the future, please ONE item per per _issue_...you have THREE here...it makes it far easier for a developer to deal with (a sing PR containing the code for all of them at once would surely be rejected).  I realize it is easier for _you_ to enter a single issue, but...

Number 1 might be considered related to #8228

Number 2 is on the "mental" list to implement after #8131 is finished; it was hinted at via a preview screenshot here: https://github.com/notepad-plus-plus/notepad-plus-plus/issues/8525#issuecomment-654244664

**Comment by Yaron10** [comment]
I thought it would be easier for you too.

Tabula Rasa.

**Comment by sasumner** [comment]
Broken down into separate issues for better handling:

* Number 1 -> #8626 
* Number 2 -> #8624 
* Number 3 -> #8625
