### ISSUE TITLE
Vertical edge in wrong position after changing the default font

### ISSUE THREAD

**Issue by Yaron10** [notepad-plus-plus/notepad-plus-plus#8622]
**STR:**
`Preferences -> Edit -> Vertical Edge`: enter `30`.
`Style Configurator -> Font Name`: change to `Tahoma`.
Check `Enable Global Font`.

**Result:**
The vertical edge is in a wrong position.

(BTW, wouldn't it be better if the position was "one-based" as it is in the status bar?).

***
Notepad++ v7.8.9   (32-bit)
Build time : Jul 23 2020 - 22:44:42
Path : C:\---\notepad++.exe
Admin mode : ON
Local Conf mode : ON
OS Name : Windows 7 Enterprise (32-bit) 
OS Build : 7601.23964
Current ANSI codepage : 1255
Plugins : ComparePlus.dll HTMLTag_unicode.dll MenuIcons.dll PythonScript.dll _CustomizeToolbar.dll

**Comment by Ekopalypse** [comment]
@Yaron10 - you may be interested in reading [this](https://www.scintilla.org/ScintillaDoc.html#SCI_SETEDGEMODE) about
monospaced and proportional fonts.

**Comment by sasumner** [comment]
If @Ekopalypse 's information satisfies @Yaron10 we could close.
EXCEPT, I like the point about being "one-based".

**Comment by Yaron10** [comment]
@Ekopalypse, @sasumner,

:+1: 

https://github.com/notepad-plus-plus/notepad-plus-plus/issues/8629
