### ISSUE TITLE
Find Results: Add a word-wrap option

### ISSUE THREAD

**Issue by Yaron10** [notepad-plus-plus/notepad-plus-plus#8624]
Add an option to word-wrap (toggle state in the context menu).

Thank you.

**Comment by donho** [comment]
Not sure it's nice visually. I'll check it anyway.

**Comment by sasumner** [comment]
@donho said

>Not sure it's nice visually. 

I think it is nice visually.
See a sample screenshot [HERE](https://github.com/notepad-plus-plus/notepad-plus-plus/issues/8525#issuecomment-654244664)
The screenshot also has visible whitespace turned on.

**Comment by Yaron10** [comment]
Seems nice to me too.

**Comment by sasumner** [comment]
Perhaps it could be a _Preference_ setting--for how you usually want it--and then a _Find result_ window right-click context menu option as a temporary (until you restart N++) override?

**Comment by Yaron10** [comment]
You did a great job with the new Searching page and you want to fill it up now. :)

On a serious note: your proposed structure can be helpful in some cases to some users.
But, all in all, allow me to disagree: I think that one permanent context-menu setting would be more convenient and less confusing.

Thank you for working on that too.

**Comment by sasumner** [comment]
>You did a great job with the new Searching page and you want to fill it up now.

Thanks.
Yes, I have "big plans" for it.
It seems like search/replace/etc. is a big area for me, where a lot of the work I've done has been concentrated.

>one permanent context-menu setting

Perhaps you are right.
And it would leave more room in the _Preferences_ 's _Searching_ page for other things!!

**Comment by Yaron10** [comment]
> It seems like search/replace/etc. is a big area for me, where a lot of the work I've done has been concentrated.

I'm glad it is. Thanks again for your work.
I've also made a lot of changes in this area for my personal use.

The Incremental Search Bar is my main search tool.
![תמונה](https://user-images.githubusercontent.com/10229320/89132236-701cf280-d51b-11ea-81da-8eb7c8010115.png)

I've replaced the EditBox with a ComboBox.
Find First/Prev/Next.
Display All in Current Document (Ctrl -> in All Open Documents).
Whole-Word. 
Case.
Mark.

I've also made the default size of the Find dialog much smaller. 
![תמונה](https://user-images.githubusercontent.com/10229320/89132356-3d272e80-d51c-11ea-8aa6-a16e74e91671.png)

Double-clicking the title toggles "More/Less".
![תמונה](https://user-images.githubusercontent.com/10229320/89132410-89726e80-d51c-11ea-905a-ed0aecff8c1c.png)

And more. :)

**Comment by sasumner** [comment]
Changes from this issue released in Notepad++ version 7.9
