### ISSUE TITLE
Find Results: Add an option to change text direction

### ISSUE THREAD

**Issue by Yaron10** [notepad-plus-plus/notepad-plus-plus#8625]
Add an option to change text direction (toggle default LTR in the context menu).

Thank you.

**Comment by sasumner** [comment]
Perhaps it should be a _Preference_ setting and not a _Find result_ window right-click context menu setting?

**Comment by Yaron10** [comment]
https://github.com/notepad-plus-plus/notepad-plus-plus/issues/8624#issuecomment-667585821.

**Comment by Yaron10** [comment]
Actually, this context-menu setting would not be useful to most users.
How about `Display "Toggle Text Direction" in the Find Results context-menu` in `Preferences -> Searching`?

IMO this is not necessary either but...

**Comment by sasumner** [comment]
Yea, I don't think we need a _Preference_ setting just to control whether or not it is visible in a context-menu.

I don't have a great understanding of RTL issues, because I'm a permanent LTR kind of person. :-)
But...it seems like this would be something a user changes one time only, and thus maybe belongs only in the _Preferences_ and not in the context-menu.  So, that would be okay? Or is it your strong feeling that it should definitely be in the context-menu?

**Comment by Yaron10** [comment]
> it seems like this would be something a user changes one time only

Unfortunately that's not the case. RTL people use both RTL and LTR. :)

But it can be done without a setting at all: before displaying the results, check the direction of the current view and apply it to `_scintView`.

```
long exStyle = static_cast<long>(::GetWindowLongPtr(_hSelf, GWL_EXSTYLE));
exStyle = (*_ppEditView)->isTextDirectionRTL() ? exStyle | WS_EX_LAYOUTRTL : exStyle&(~WS_EX_LAYOUTRTL);
::SetWindowLongPtr(_hSelf, GWL_EXSTYLE, exStyle);
```

I can think of two possible enhancements but they are probably not worth it.

If word-wrap is ON (in `_scintView` when implemented) and you change direction, there might be a mirroring problem.
This is how it's fixed in `NppCommands.cpp`:
```
// Wrap then !wrap to fix problem of mirror characters
bool isWraped = _pEditView->isWrap();
_pEditView->wrap(!isWraped);
_pEditView->wrap(isWraped);
```

Thanks again.

**Comment by sasumner** [comment]
@Yaron10 

>RTL people use both RTL and LTR

Struggling to understand this fully.
I notice that on the _View_ menu we have:
* _Text Direction RTL_
* _Text Direction LTR_
But if I select RTL, it doesn't persist after I quit and restart N++ -- is that correct behavior?
Or is this a function of me having "English" set as my *Localization* setting?

**Comment by Yaron10** [comment]
> Struggling to understand this fully.

I can imagine it's not easy to comprehend the concept.

When you started learning how to write, your teacher instructed you to write the first letter on the **left** side of the page and continue with the other letters from there. 

Now that I know you're a native English speaker, I'll assume you're from the UK. :)

Imagine that kids in the USA are taught to write the first letter on the **right** side of the page.
And this is how they write "Hello Scott":
![תמונה](https://user-images.githubusercontent.com/10229320/90292917-8d42b100-de8b-11ea-8d37-dbecc3f4caca.png)

This is a completely opposite world of writing, typing and reading. An opposite layout, text direction and more.

Now, think that you use both UK English and USA English in NPP - you would surely want the "Find Results" window to use the UK/USA way of writing (**Text Direction**) that you're currently using in the document.

A couple of years ago I asked Claudia (bless her :) ) to set the layout and text direction in Python console to LTR even if NPP layout is RTL.

That is because in Python *you only use* UK English (LTR).  

***

> But if I select RTL, it doesn't persist after I quit and restart N++ -- is that correct behavior?

That is a very good question.

Is it a bug? - Certainly not.
Is it the ideal behavior? - No.

I use NPP in a RTL layout, but most of my documents are UK English (LTR).
So whenever I restart (the original) NPP, I need to use the "Change Text Direction" command ("it doesn't persist").

I've solved this problem by adding the following line in `void ScintillaEditView::init(HINSTANCE hInst, HWND hPere)`.
`::SetWindowLongPtr(_hSelf, GWL_EXSTYLE, WS_EX_CLIENTEDGE & (~WS_EX_LAYOUTRTL));`

```
	if (!_hSelf)
	{
		throw std::runtime_error("ScintillaEditView::init : CreateWindowEx() function return null");
	}

	// Change to LTR. "WS_EX_CLIENTEDGE & (~WS_EX_LAYOUTRTL)" above won't work. I think that _hParent overrides it.
	::SetWindowLongPtr(_hSelf, GWL_EXSTYLE, WS_EX_CLIENTEDGE & (~WS_EX_LAYOUTRTL));
```

NOTE: I prefer to have the same text direction in both views. Other users might prefer the original behavior of an independent direction in each view. 

Remembering the views' direction (i.e. saving it to config.xml) can be a major improvement to RTL users (and possibly to some LTR users as well).

Is it worth it? Or is it just a bloat for most users?
That's for you (and obviously Don) to decide.

Thank you.

**Comment by sasumner** [comment]
>I can imagine it's not easy to comprehend the concept

Well...you didn't have to take me back to kindergarten...but in the end I'm glad you did. :-)
Thank you for taking the time and keystrokes for a detailed explanation.

So currently RTL in the editor tabs applies to all editor tabs, if enabled via the View menu.  But if I'm understanding you correctly, some should be allowed to be LTR and some RTL, if the user desires.  This is like the current deficiency in "Word wrap" -- users have complained that that wrapping should be a "per tab" option.  Is this correct thinking for RTL / LTR ?

So ideally, it should persist across N++ restarts, AND also be remembered on a per-tab basis.

> I'll assume you're from the UK.

Wrong again. U.S.  :-)

**Comment by Yaron10** [comment]
> So currently RTL in the editor tabs applies to all editor tabs, if enabled via the View menu.

If you use a RTL NPP, the views inherit the `WS_EX_LAYOUTRTL` and on starting NPP *all tabs in both views* are RTL.
`View -> Text Direction LTR` changes the direction of all tabs *but only in the current view*.
And as you've stated: "It doesn't persist".

My suggestion was to remember/save the direction of each view (only two more entries in `config.xml`).
And this is probably easy to implement.

Direction "per tab" has been requested a few times, and someone even wrote a plugin implementing "per *file* direction" (including sessions and Recently Closed Files). Unfortunately it wasn't perfect.

I suppose that implementing it ("per tab direction") should be more complex.
But if "per tab wrap" is implemented, "per tab direction" can apparently be added to that new structure.

BTW, if you add `RTL="yes"` to `english.xml` and restart NPP, you'll have a RTL NPP in English.
`<Native-Langue name="English" RTL="yes" filename="english.xml" version="7.8.7">`

***

Regarding the original request here: I've added it and there's no need to "Wrap then !wrap to fix problem of mirror characters".

So it's just
```
		long exStyle = static_cast<long>(::GetWindowLongPtr(_pFinder->_scintView.getHSelf(), GWL_EXSTYLE));
		exStyle = (*_ppEditView)->isTextDirectionRTL() ? exStyle | WS_EX_LAYOUTRTL : exStyle & (~WS_EX_LAYOUTRTL);
		::SetWindowLongPtr(_pFinder->_scintView.getHSelf(), GWL_EXSTYLE, exStyle);
```
in `void FindReplaceDlg::findAllIn(InWhat op)`

and
```
	long exStyle = static_cast<long>(::GetWindowLongPtr(_pFinder->_scintView.getHSelf(), GWL_EXSTYLE));
	exStyle = (exStyle & WS_EX_LAYOUTRTL) != 0 ? exStyle | WS_EX_LAYOUTRTL : exStyle & (~WS_EX_LAYOUTRTL);
	::SetWindowLongPtr(pFinder->_scintView.getHSelf(), GWL_EXSTYLE, exStyle);
```
in `Finder * FindReplaceDlg::createFinder()`.
(As you beautifully implemented it with Wrap).  

***
> Wrong again. U.S. :-)

I'm not trying to guess the state! :)

Thank you for your time and work. I appreciate it.

**Comment by sasumner** [comment]
@Yaron10 said

>BTW, if you add RTL="yes" to english.xml and restart NPP, you'll have a RTL NPP in English.

I tried this.
I have a "mostly" RTL view:

![image](https://user-images.githubusercontent.com/30118311/101685733-1d59c700-3a36-11eb-9180-1b4363b95bc1.png)

But I expected to see a "Hello Scott" more of what you showed above, specifically:

![image](https://user-images.githubusercontent.com/30118311/101685814-3498b480-3a36-11eb-8f97-44331908b008.png)
 
Do I need to do more, or do I misunderstand something fundamental?

**Comment by Yaron10** [comment]
@sasumner,

Fortunately - typing "Hello Scott" in a RTL layout (or just `View -> Text Direction RTL`), you get the result in your screenshot.
My screenshot is the result of manually mirroring the text as an illustration to RTL languages. :)

**Comment by Yaron10** [comment]
Anther point:

With the code above - in some encodings (e.g. ANSI), selecting a line *with the EOL* the highlighting in the "Search Results" window may not be correct.

**Comment by donho** [comment]
@Yaron10 
Can I close this issue with https://github.com/notepad-plus-plus/notepad-plus-plus/commit/db4a6f5ec6834c4513d650053e46aea2eaa4b5e7 ?

**Comment by Yaron10** [comment]
@donho,

Thanks again for your work. I appreciate it.
The first point in https://github.com/notepad-plus-plus/notepad-plus-plus/commit/db4a6f5ec6834c4513d650053e46aea2eaa4b5e7#commitcomment-45041162 is highly important.

**Comment by donho** [comment]
https://github.com/notepad-plus-plus/notepad-plus-plus/commit/edaa67db28d4c4158b9c0b3406138d56b2c1b4be and https://github.com/notepad-plus-plus/notepad-plus-plus/commit/5e96dd01664d8e7bf00bf2748862ffa68a575b4a
