### ISSUE TITLE
Synchronized Horizontal and Vertical disabled.

### ISSUE THREAD

**Issue by BNGI** [notepad-plus-plus/notepad-plus-plus#8635]
### Description of the Issue
When you open NP++ in two panes mode the buttons to enable synchronized horizontal and vertical scrolling are disabled. Even the menu entries show disabled.

### Steps to Reproduce the Issue
1. Set NP++ in two-pane mode by having at least one file on the left and one file on the right.
2. Close NP++.
3. Open NP++

### Expected Behavior
Buttons to enable synchronized scrolling should be functional.

### Actual Behavior
Buttons to enable synchronized scrolling are disabled and so are the related menu entries.
IMO this is related to #5250

### Debug Information
The fix for this is actually very simple: move at least one file to the other pane (move a file on the right, to the left and vice versa).
The buttons to enable synchronized scrolling activate in the icon bar and related menu entries are operational.

This the status of the buttons when NP++ is launched in two-pane mode:
![NP++ Scroll Buttons Disabled](https://user-images.githubusercontent.com/55240829/88813266-b6bec580-d186-11ea-9f3f-4b8b7ed49eee.PNG)

This is the status of the menu entries:
![NP++ Scroll Menu Disabled](https://user-images.githubusercontent.com/55240829/88812768-1b2d5500-d186-11ea-92be-15b8d1d76c77.PNG)

However, after moving at least one of the files from the left to the right or vice versa, this is the result;
Status buttons:
![NP++ Scroll Buttons Enabled](https://user-images.githubusercontent.com/55240829/88812995-62b3e100-d186-11ea-8dde-c8a2bf85d195.PNG)

Menu entries:
![NP++ Scroll Menu Enabled](https://user-images.githubusercontent.com/55240829/88813121-86772700-d186-11ea-9aab-5a16ba695261.PNG)

I have the ComparePlugin installed (among others), but I've tried removing it and the result is the same. I'm on V7.8.9 x64

Thank you and sorry if this is a known issue already discussed.

**Comment by sasumner** [comment]
Please provide _Debug Information_ following the instructions in the issue template, not your own interpretation of what _Debug Information_ means.

**Comment by sasumner** [comment]
>IMO this is related to #5250

It doesn't just seem related, it seems a pure duplicate.
Any additional input you had could have been added to 5250.

**Comment by sasumner** [comment]
Closing as duplicate; any new information, please add in 5250
