### ISSUE TITLE
Naming a file with a colon character causes file tab display, file rename issues

### ISSUE THREAD

**Issue by unclesamkent** [notepad-plus-plus/notepad-plus-plus#8637]
### Description of the Issue

If you name a text file with a colon character, for example "1:1 with boss.txt", only the portion of the filename after the colon displays in the file tab.  In addition, you cannot rename this file.

### Steps to Reproduce the Issue

1. Create a new file
2. save file with a colon in the name

### Expected Behavior

1. file name would display in file tab.
2. file could be renamed.

### Actual Behavior

1. only partial file name displayed in file tab.
2. file could not be renamed.

### Debug Information

Notepad++ v7.8.7   (32-bit)
Build time : Jun  5 2020 - 02:34:28
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS Name : Windows 10 Enterprise (64-bit) 
OS Version : 1809
OS Build : 17763.1282
Current ANSI codepage : 1252
Plugins : mimeTools.dll NppConverter.dll NppExport.dll

**Comment by unclesamkent** [comment]
Verified in v7.8.9.

**Comment by sasumner** [comment]
In 7.8.9 I get this, which I expected:

![image](https://user-images.githubusercontent.com/30118311/88848828-fdc4af00-d1b6-11ea-810e-6b919969bdae.png)

So I'm confused when you say "only the portion of the filename after the colon displays in the file tab" because I can't get that far with it.

Anyway, on Windows a `:` character is not allowed in filenames, as since time began (for MS-DOS), a colon is a separator between a drive letter and the rest of the path, e.g. `C:\path\file.txt`.  In your example case, since `1` is not a valid drive letter, you've got a problem.

I hope your one-on-one went well. :-)

**Comment by unclesamkent** [comment]
That's interesting... I don't get that same dialogue.

When I try to "save as", what I see being created on my file system after (for the given example "1:1 with boss.txt"). is a file with the name "1", of no type:

![notepad++ 8637](https://user-images.githubusercontent.com/68444837/88851158-f8189a80-d1b1-11ea-9ecd-b44c8e9e6c8e.png)

**Comment by unclesamkent** [comment]
Ans I'll let you know how the 1:1 goes.  It's next Tuesday.  Unfortunately when renaming, I lost my file and my notes.

**Comment by sasumner** [comment]
Perhaps someone else can try reproducing it.  For the record, my setup is very close to yours, as far as info in the _Debug Info_:

Notepad++ v7.8.9   (32-bit)
Build time : Jul 15 2020 - 20:26:50
Path : C:\\...........\npp.7.8.9.bin\notepad++.exe
Admin mode : OFF
Local Conf mode : ON
OS Name : Windows 10 Enterprise (64-bit) 
OS Version : 1809
OS Build : 17763.1039
Current ANSI codepage : 1252
Plugins : mimeTools.dll NppConverter.dll NppExport.dll PythonScript.dll 

>Unfortunately when renaming, I lost my file and my notes.

Not good. :-(

**Comment by Yaron10** [comment]
@sasumner,

You're using the NEW Save dialog.

@unclesamkent,

You're using the OLD Save dialog.

**Comment by sasumner** [comment]
So this issue is one more reason the OLD should just...go...away...  :-)

**Comment by sasumner** [comment]
So, @unclesamkent , I would suggest ticking this option in the _Preferences_ :

![image](https://user-images.githubusercontent.com/30118311/88921390-73269300-d23c-11ea-92b1-94a356185c79.png)

It ***IS*** an issue, but it may never get addressed.
