### ISSUE TITLE
Feature request: some tab improvements

### ISSUE THREAD

**Issue by marcosjose** [notepad-plus-plus/notepad-plus-plus#8642]
My English isn’t so good, so sorry about any mistakes.

The ideia for this feature request it’s because I have a “compulsive hoardering” for multiple opened tabs! LOL!! :P

I use to leave huge amounts of opened tabs, and oftentimes this mess hinders the exchange between them.

Sometimes, when I close the last tab, for example, tab titled “new 189”, then notepad++ moves the focus to the tab “new 8” (but that is NOT the first opened tab!). So, a don’t know why it goes to some random tab near (but not) the first tabs. Doubt: is there a defined order of the focus changing when you close the last tabs?

In that context, I would like to make a ideia for “simple” (I think so) features improvements:

1. When closing the last tab, then the focus go to the previous tab. Example: if I close the tab “new 189”, then notepad++ open the tab on the left (“new 188”), and so on, while I continue to close the tab “new 188”, “new 187”…

2. Maybe, another solution it’s to create a shortcut for “Last tab”, like this:

![Last-Tab](https://user-images.githubusercontent.com/43652418/88955985-12667d00-d273-11ea-8eed-744248ee7332.png)

3. And, finally, another third option, would be adding two icons for “First Tab” and “Last Tab”, here:

![First-Last-Tab](https://user-images.githubusercontent.com/43652418/88956017-1f836c00-d273-11ea-921b-8c8185d2ffa7.png)

That’s it!
Thank you very much for the attention!!
I hope that the my idea was made clear here.
And I look forward to the implementation of such suggestions! :)
Best regards,
Marcos (from Brazil).

**Comment by sasumner** [comment]
@marcosjose 

> I close the last tab, for example, ... then notepad++ moves the focus to ... some random tab

It is NOT random.
It moves the focus to the tab that you visited most-recently.

You can alter this behavior via this _Preference_ setting:
![image](https://user-images.githubusercontent.com/30118311/88961254-bc91d500-d272-11ea-9eb4-7b06c1235fbf.png)

`MRU` = "Most Recently Used" (better might be most-recently-visited).

>When closing the last tab, then the focus (should) go to the previous tab

This may make sense for you, but for most people they want to be where they were working previously.

>another solution it’s to create a shortcut for “Last tab”
>another third option, would be adding two icons for “First Tab” and “Last Tab”

At this point I just don't think it is warranted to do this.

>I ... leave huge amounts of opened tabs

This always confuses me; I see your tabs are all "new" tabs.  If you have "huge amounts" how do you keep track of what is in which one?
