### ISSUE TITLE
EOL Conversion Greyed out for Current EOL Mode (While File Contains Mixed EOLs)

### ISSUE THREAD

**Issue by minig0d** [notepad-plus-plus/notepad-plus-plus#8644]
### Description of the Issue
When opening a file, it seems that NPP assumes all line endings are in one or the other EOL format and greys out the menu option to convert to that line ending that it believes the file is in.

Would think the easiest route to remedy is just to not conditionally grey the current mode out, but suppose an alternative would be conditionally checking if mixed EOL's existed (which I saw there were some other options open regarding).  But simple'est option seems to be make it available all the time.  Right clicking on the status bar does seem to exhibit the same behavior.

A workaround of switching to a different mode and switching back does work as intended but just adds clicks.

### Steps to Reproduce the Issue

1. Open a text-based file with mixed EOL's (some windows and some unix at least) (have not tested Mac but assume it's affected the same)
2. Go in Edit menu to EOL Conversion

### Expected Behavior
Menu option be available for selection

### Actual Behavior
Whatever mode the document is currently in appears greyed out (ex. if File is set to Windows (CR LF) as reflected in the lower right corner, this mode appears to be greyed out in the menu.

### Debug Information
Notepad++ v7.8.9   (64-bit)
Build time : Jul 15 2020 - 20:31:49
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS Name : Windows 10 Pro (64-bit) 
OS Version : 1909
OS Build : 18363.900
Current ANSI codepage : 1252
Plugins : BetterMultiSelection.dll ComparePlugin.dll DSpellCheck.dll HTMLTag.dll JSMinNPP.dll mimeTools.dll NppConverter.dll NppExport.dll NppSaveAsAdmin.dll NppSnippets.dll NppTaskList.dll RunMe.dll XMLTools.dll _CustomizeToolbar.dll 

![image](https://user-images.githubusercontent.com/54046315/88983709-5bc5c500-d291-11ea-839d-a9477c75c147.png)

![image](https://user-images.githubusercontent.com/54046315/88984035-35545980-d292-11ea-9748-0ce6d9673ba2.png)

**Comment by sasumner** [comment]
Acknowledged, but current behavior is unlikely to be changed.
Workaround is to convert to an available line-ending type, then convert to the desired type.
