### ISSUE TITLE
Remove file size limit

### ISSUE THREAD

**Issue by klingchristoph** [notepad-plus-plus/notepad-plus-plus#865]
The file size limit is based on performance and memory and performance limits (according to http://docs.notepad-plus-plus.org/index.php/Large_Text_Files). Memory of normal computers has increased enormously in recent years. It should be left to the user to decide whether he wants to open a big file with bad performance. At least a configuration option should be provided to disable the hard limit.

**Comment by informatorius** [comment]
same as https://github.com/notepad-plus-plus/notepad-plus-plus/issues/681

**Comment by dail8859** [comment]
Duplicate.
