### ISSUE TITLE
Feature Request: add ability to sort starting from specific column

### ISSUE THREAD

**Issue by rjsargent** [notepad-plus-plus/notepad-plus-plus#8652]
### Description of the Issue
I was trying to compare two tar files (with 100K+ files). I listed the contents of both, but they came out in different orders.

Sorting the two files lexicographically produced a nearly working result, because the  tarballs were intended/expected to be the same.

e.g.
-r--r----- gs/gs            15 2019-05-07 14:28 repos/Gofer/.git/objects/e6/9de29bb2d1d6434b8b29ae775ad8c2e48c5391
-r--r----- gs/gs            15 2019-12-09 19:27 repos/MetacelloPreview/.git/objects/e6/9de29bb2d1d6434b8b29ae775ad8c2e48c5391
-r--r----- gs/gs            20 2019-12-09 19:27 repos/MetacelloPreview/.git/objects/a0/97c6351df73116fdf5d8e18c545c23288aeef6
-r--r----- gs/gs            21 2019-05-07 14:28 repos/Gofer/.git/objects/f0/37444a7caa50a71595b61ace1fa91882512e9f
Sorted by access bits then file size worked surprisingly well for that particular scenario, but some files were touched without changing file size, so the sort wasn't perfect.

Being able to specify that the sort should work from column 49 instead of column 1 would have given a better result.

The difference in tar output order might have been an artefact of the different file systems holding the directories. e.g. ext4 vs nfs.

### Steps to Reproduce the Issue
1. Generate two tarballs of directory trees that ought to be the same ( tar cfz ...)
2. List the contents of the tarballs (tar -tvf ...)
3. Load and compare the two files (through e.g. the Compare Plugin V2.0.0)
4. Initially, there were huge differences, so sort the two files
5. Run the comparison again. Much faster since the two directories were meant to be the same, but not generally true.

### Expected Behavior
To have the files sorted by the file names presented so that real differences would be more easily detected and recognized.

### Actual Behavior
It sorted correctly, by definition, and worked to a degree to facilitate the comparison.

### Debug Information
Notepad++ v7.8.5   (32-bit)
Build time : Mar  4 2020 - 11:04:20
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS Name : Windows 10 Enterprise (64-bit) 
OS Version : 1909
OS Build : 18363.900
Plugins : ComparePlugin.dll mimeTools.dll NppConverter.dll NppExport.dll 

As indicated, this is a feature request. The current functionality is correct as designed, but insufficient.

PS. Thanks for creating and maintaining this tool. It's *excellent* and that's the opinion of one who has seen a lot of stuff over the last 47 years.

**Comment by sasumner** [comment]
To sort based upon columns, block those columns in with a rectangular (aka column block); example on your data:

![image](https://user-images.githubusercontent.com/30118311/89085420-34d5c480-d35f-11ea-9c64-7f29229e48d0.png)

**Comment by sasumner** [comment]
If the change put forth by #8675 is adopted, this sort could be done a bit easier by simply making this zero-width column block before invoking the sort:

![image](https://user-images.githubusercontent.com/30118311/89675112-5ed73b80-d8b7-11ea-8310-28e1ce09ee16.png)
