### ISSUE TITLE
Please don't put personal political bias in an open source code base.

### ISSUE THREAD

**Issue by snys98** [notepad-plus-plus/notepad-plus-plus#8659]
![image](https://user-images.githubusercontent.com/11873100/89141298-c66b4f00-d576-11ea-8917-bd003d5052af.png)

>开源项目不应该和任何政治狗屎扯上关系。 我不希望技术界被各种双标政治正确所污染。
烦请不要再对其他种族，尤其是中国人做出政治判断。 我们在做我们自己的事请，这和你没有任何关系。 脑子灵光一点，如果你不理解某个事情，那么你应该做的就是保持尊重。 你没有叼到可以对所有事情说长道短，尤其是一件14亿人正在做的事情。

Open source projects should not be related to any political shit. And I don’t want the programming world to be polluted by any kind of double standard political correctness.

Stop putting your political judgement on other races, e.g. Chinese. We are doing our own business, and it's none of your business. Be brilliant, if you don't understand something, all you should do is to keep respect. You are not great enough to judge everything, especially something that is doing by 1.4 billion people.

**Comment by roymok** [comment]
烦请不要再对其他种族，尤其是美国人做出政治判断。 他们在做他们自己的事请，这和你没有任何关系。

**Comment by snys98** [comment]
>我上面的内容在对美国人做出政治判断吗?

Is my content above making political judgments about Americans?

**Comment by roymok** [comment]
> > 我上面的内容在对美国人做出政治判断吗?
> 
> Is my content above making political judgments about Americans?

要求美國人不要對中國人作出政治判斷
不就是在對美國人作出政治判斷?

中國人, 好好地拿出你們的底氣, 杯葛NP++吧, 反正你們是強國, 有中國軟件不用, 走過來美國地方放狗屁

**Comment by snys98** [comment]
@roymok 你越界走了一步, 我让你退回去, 这也算是对你做出政治判断吗?

You crossed the line with a step, and I told you to go back. Is this also a political judgment for you?

**Comment by roymok** [comment]
> @roymok 你越界走了一步, 我让你退回去, 这也算是对你做出政治判断吗?
> 
> You crossed the line with a step, and I told you to go back. Is this also a political judgment for you?

那麼華春瑩又可以 I cant breath?

美國的政治就可以批判, 中國的政治就不可以批判
如果你有能力連接到國際網絡
勸你還是早日離開同溫層吧

另外, 不要再用np++啦, 再者windows也是美帝產物, 快去安裝這個吧 http://www.cs2c.com.cn/

**Comment by snys98** [comment]
@roymok 

>你在转移话题, 我在讲的是"不要在开源项目里面输出政治偏见", 你都说到哪里去了?

You're misleading the discussion. I'm talking about **_Don't export political bias in open source projects_**, where did you go?

**Comment by roymok** [comment]
> @roymok
> 
> > 你在转移话题, 我在讲的是"不要在开源项目里面输出个人政治偏见", 你都说到哪里去了?
> 
> You're misleading the discussion. I'm talking about **_Don't export personal political bias in open source projects_**, where did you go?

Who made the rules?

**Comment by roymok** [comment]
You just ignore my last sentence.
Just use http://www.cs2c.com.cn/. You life will be more easier!

**Comment by snys98** [comment]
> > @roymok
> > > 你在转移话题, 我在讲的是"不要在开源项目里面输出个人政治偏见", 你都说到哪里去了?
> > 
> > 
> > You're misleading the discussion. I'm talking about **_Don't export personal political bias in open source projects_**, where did you go?
> 
> Who made the rules?

Github made the [rule](https://docs.github.com/en/github/site-policy/github-event-code-of-conduct#code-of-conduct). Read it before you start to use Github.

**Comment by roymok** [comment]
> > > @roymok
> > > > 你在转移话题, 我在讲的是"不要在开源项目里面输出个人政治偏见", 你都说到哪里去了?
> > > 
> > > 
> > > You're misleading the discussion. I'm talking about **_Don't export personal political bias in open source projects_**, where did you go?
> > 
> > 
> > Who made the rules?
> 
> Github made the [rule](https://docs.github.com/en/github/site-policy/github-event-code-of-conduct#code-of-conduct). Read it before you start to use Github.

Did they political attack you? How come "Stand" with Hong Kong will offence the rule?

**Comment by snys98** [comment]
@roymok 

>Unacceptable behavior includes:
> - The use of sexualized language or imagery, or inappropriate physical contact, sexual attention, or advances
> - Trolling, insulting or derogatory comments, personal or political attacks, or **sustained disruption of talks** or other events
> - Deliberate intimidation, stalking, following, or harassing photography or recording
> - **Harassment of any kind, even in a joking or ironic manner**
> - Other conduct which could reasonably be considered inappropriate in a professional setting

你没有理解到我在说什么, 我说的"rule"是指"我们在讨论开源项目中的个人政治偏见问题, 如果你不想讨论这个话题, 请不要打扰", 你可以尝试理解一下自己有没有违反加粗字体的内容, 如果你还是不能理解, 我将🚫你, 谢谢:smile:.

You didn’t understand what I’m talking about. The _rule_ I said refers to **_We are discussing the issue of personal political bias in open source projects. If you don’t want to discuss this topic, please don’t bother_**, you can try to understand if you have violation of the content in bold font, if you still can’t understand, I will 🚫you, thank you:smile:.

**Comment by roymok** [comment]
You: Don't export personal political bias in open source projects
rule: ..."political attacks"...

bias == attacks?

**Comment by snys98** [comment]
@roymok 

>屁股决定脑袋
>Where one stands depends on where one sits.

政治观点都是偏见, 如果你想吵架, 那就去谈论政治吧. 现在我想说就是"咱们不要在写代码的地方谈政治", 这下你明白了吗?

Political opinions are all bias. If you want a fight, then talk about politics. Now I'm saying, "Let’s not talk about politics where we write code", you understand? :smile:

I'm trying to be polite but I'm losing patience. AGAIN, don't be off topic.

**Comment by roymok** [comment]
> @roymok
> 
> > 屁股决定脑袋
> > Where one stands depends on where one sits.
> 
> 政治观点都是偏见, 如果你想吵架, 那就去谈论政治吧. 现在我想说就是"咱们不要在写代码的地方谈政治", 这下你明白了吗? 😄
> Political opinions are all bias. If you want a fight, then talk about politics. Now I'm saying, "Let’s not talk about politics where we write code", now you understand? 😄
> 
> 我试图保持礼貌，但我快有点失去耐心了。 再次强调，不要转移话题。
> I'm trying to be polite but I'm losing patience. AGAIN, don't be off topic.

不要把自己家的界線畫到他人家去啦
github只說不能政治攻擊，沒有說不可有關政治立場的言論喔
你還沒說到為何stand with hong kong 是political attack呢
如言之成理，且不算干涉美國人權自由的保障，我相信dev team會很樂意發回重上

**Comment by AlphaWong** [comment]
I think it is exporting chinese censorship in Github. The main point is that in mainland china, visiting Github is already illegal.

I think u guya take advantage from freedom of speech and selling so cal chinese value ( censorship, monitoring  and hate speech )

It is shame, I remember those people from china are brave like https://github.com/sikaozhe1997/Xin-Yue

**Comment by snys98** [comment]
@roymok

> 不要把自己家的界線畫到他人家去啦

@donho 是香港居民还是什么人可以让他把香港视为"自己家"？ 他不正是在扩大界線吗？
Did @donho a Hong Kong resident or someone that could treat Hong Kong as his family? Is he expanding his borderline?

> github只說不能政治攻擊，沒有說不可有關政治立場的言論喔

如果你使利益相关的人感到不舒服, 那这就是一种政治攻击. 就像你说的, 有一些玻璃心的人. 为什么你热衷于嘲讽欺辱这些人? 整件事情和你没有关系, 你没有住在中国, 你不了解事情的全貌, 你不应该评判.
If you make stakeholders uncomfortable, then that would be a kind of political attack. Just like you said, there are some **_fragile heart of people_**. Why you're keen to bully them? It's none of your business, you're not living in China, you're not well informed with the whole situation and you should not judge.

> 你還沒說到為何stand with hong kong 是political attack呢

我没有说"stand with Hong Kong"是政治攻击, 我在说"开源项目不应该和任何政治狗屎扯上关系。", 但是它很明显会吸引出一大批像你这样热衷于政治攻击的人. 看看你言辞中的侮辱和嘲讽吧. https://github.com/notepad-plus-plus/notepad-plus-plus/issues/8659#issuecomment-667778028
I'm not saying **_stand with Hong Kong_** is a political attack. I'm saying _**Open source projects should not be related to any political shit**_. Cause it will obviously attract many people like you who are keen on political attacks. Look at the insults and ridicule in your words. https://github.com/notepad-plus-plus/notepad-plus-plus/issues/8659#issuecomment-667778028

> 如言之成理，且不算干涉美國人權自由的保障，我相信dev team會很樂意發回重上

希望如此, 但是这和美国人的人权自由又有什么关系?
I hope so. But it's nothing to do with Americans and their human rights and freedom.

**Comment by HappyAreaBean** [comment]
Easy triggered LOOOL

**Comment by roymok** [comment]
> @donho 是香港居民还是什么人可以让他把香港视为"自己家"？ 他不正是在扩大界線吗？

我說的是自由的界線吧，要支持哪一種理念也是自由的一種。香港在爭取寫在基本法上保障的權利，卻被ccp包裝成港獨之說。所以你們這群人一聽到stand with hong kong就跳了

> 如果你使利益相关的人感到不舒服, 那这就是一种政治攻击. 就像你说的, 有一些玻璃心的人. 为什么你热衷于嘲讽欺辱这些人? 整件事情和你没有关系, 你没有住在中国, 你不了解事情的全貌, 你不应该评判.

你沒有住在外國，你不了解自由的味道，這是行使freedom of speech的一種，不應把中國的束縛帶到自由的國度
你的國度可以上罵xi嗎？噢不，你們都有言論自由的，不過是一生人一次


> 我没有说"stand with Hong Kong"是政治攻击, 我在说"开源项目不应该和任何政治狗屎扯上关系。", 但是它很明显会吸引出一大批像你这样热衷于政治攻击的人. 看看你言辞中的侮辱和嘲讽吧. [#8659 (comment)](https://github.com/notepad-plus-plus/notepad-plus-plus/issues/8659#issuecomment-667778028)

狗屎vs狗屁，呵呵，笑了

> 希望如此, 但是这和美国人的人权自由又有什么关系?

看你提出的證明“如何不應在open source project上有政治”有沒有限制了@donho行使的自由呀，證據呢？不要只提出要求，把中國cencorship在全球實行呀

**Comment by snys98** [comment]
> I think it is exporting chinese censorship in Github. The main point is that in mainland china, visiting Github is already illegal.

Where and what legal terms you've seen? I'm living in China mainland and I've never heard of it. But now I'm not talking about this, why you guys always trying to expand the discussion?

> I think u guys are take advantage from freedom of speech and selling so call chinese value ( censorship, monitoring and hate speech )

I didn't get your words. Maybe it's nothing to do with **Open source projects should not be related to any political shit.**?

> It is shame, I remember those people from china are brave like https://github.com/sikaozhe1997/Xin-Yue

I know nothing about it, I'm not going to comment it.

**Comment by snys98** [comment]
> > @donho 是香港居民还是什么人可以让他把香港视为"自己家"？ 他不正是在扩大界線吗？
> 
> 我說的是自由的界線吧，要支持哪一種理念也是自由的一種。香港在爭取寫在基本法上保障的權利，卻被ccp包裝成港獨之說。所以你們這群人一聽到stand with hong kong就跳了
> 
> > 如果你使利益相关的人感到不舒服, 那这就是一种政治攻击. 就像你说的, 有一些玻璃心的人. 为什么你热衷于嘲讽欺辱这些人? 整件事情和你没有关系, 你没有住在中国, 你不了解事情的全貌, 你不应该评判.
> 
> 你沒有住在外國，你不了解自由的味道，這是行使freedom of speech的一種，不應把中國的束縛帶到自由的國度
> 你的國度可以上罵xi嗎？噢不，你們都有言論自由的，不過是一生人一次
> 
> > 我没有说"stand with Hong Kong"是政治攻击, 我在说"开源项目不应该和任何政治狗屎扯上关系。", 但是它很明显会吸引出一大批像你这样热衷于政治攻击的人. 看看你言辞中的侮辱和嘲讽吧. [#8659 (comment)](https://github.com/notepad-plus-plus/notepad-plus-plus/issues/8659#issuecomment-667778028)
> 
> 狗屎vs狗屁，呵呵，笑了
> 
> > 希望如此, 但是这和美国人的人权自由又有什么关系?
> 
> 看你提出的證明“如何不應在open source project上有政治”有沒有限制了@donho行使的自由呀，而且證據呢？不要只提出要求，把中國cencorship在全球實行呀

https://github.com/notepad-plus-plus/notepad-plus-plus/issues/8659#issuecomment-667796317

Read this again, please.

**Comment by Korb** [comment]
This is a duplicate of #6288 (disrespect for other members of the FOSS community by posting political propaganda spam in text editor resources).
