### ISSUE TITLE
Notepad++ 7.8.9: Stand with Hong Kong - Why a political name?

### ISSUE THREAD

**Issue by lenivo** [notepad-plus-plus/notepad-plus-plus#8662]
Please, no politics for programs.

**Comment by WololoJ** [comment]
Really stupid to involve the politics in and why you are thinking you get the whole picture to give the judgement, turn to VS code already.

**Comment by joe-zhang3** [comment]
Cannot imagine how stupid it is to combine a program with any politics. Never used this program before, and never will.

**Comment by yyyreal** [comment]
Never forever!

**Comment by nganbienPhuan** [comment]
Stand with Hong Kong!

**Comment by nganbienPhuan** [comment]
Stand with Hong Kong 👍👍👍

**Comment by Korb** [comment]
This is a duplicate of #6288 (disrespect for other members of the FOSS community by posting political propaganda spam in text editor resources).
