### ISSUE TITLE
[Feature Request] Function List tab stops

### ISSUE THREAD

**Issue by vinsworldcom** [notepad-plus-plus/notepad-plus-plus#8665]
### Description of the Issue
When using the built-in Function List (View menu => Function List), the Tab key does not seem to do anything.  One would normally use the Tab key to keyboard-navigate between the forms controls (tab stops).  The Function List form has controls:

- Search box
- Sort button
- Refresh button
- Tree view

Can we make the Tab key cycle between those elements?  It would make searching in the search box then Tab to the results in the tree view and press Enter to navigate to that section of the document.  Currently, after searching, one needs to mouse click into the tree view results.

### Steps to Reproduce the Issue
1. Open document that has a Function List parser (e.g., C, C++)
2. Open Function List .. View menu => Function List
3. Click in the Search text box at the top of Function List
4. Type the name of a function to narrow the tree view results
5. Press the Tab key
6. Nothing happens

### Expected Behavior
I expect the Tab key to activate the Tree view control - or at least navigate between the Search box, sort order button, refresh button and tree view control.

### Actual Behavior
Nothing happens when pressing Tab key in the Function List form.

### Debug Information
Notepad++ v7.8.9   (64-bit)
Build time : Aug  5 2020 - 03:12:03
Path : C:\usr\bin\npp64\notepad++.exe
Admin mode : OFF
Local Conf mode : ON
OS Name : Windows 10 Enterprise (64-bit) 
OS Version : 1809
OS Build : 17763.1339
Current ANSI codepage : 1252
Plugins : AnalysePlugin.dll AutoSave.dll BetterMultiSelection.dll ChangedLines.dll CodeAlignmentNpp.dll ColumnTools.dll ComparePlugin.dll CsvQuery.dll CustomizeToolbar.dll DoxyIt.dll DSpellCheck.dll Explorer.dll GitSCM.dll JSMinNPP.dll MarkdownTableGenerator.dll NppConsole.dll NppConverter.dll NppEventExec.dll NppExec.dll NppExport.dll NppFTP.dll NppMarkdownPanel.dll NppMenuSearch.dll Python Indent.dll QuickText.dll RelativeLineNumbers.dll SpeechPlugin.dll SurroundSelection.dll TagLEET.dll XMLTools.dll ZoomDisabler.dll

**Comment by vinsworldcom** [comment]
I've tried adding WS_TABSTOP [here](https://github.com/notepad-plus-plus/notepad-plus-plus/blob/5e76ba238e81f3918e9350bf046619980ac53ef9/PowerEditor/src/WinControls/FunctionList/functionListPanel.cpp#L785) to no avail and tried adding WS_EX_CONTROLPARENT [here](https://github.com/notepad-plus-plus/notepad-plus-plus/blob/5e76ba238e81f3918e9350bf046619980ac53ef9/PowerEditor/src/WinControls/FunctionList/functionListPanel.rc#L34) also with no effect.

See [community discussion](https://community.notepad-plus-plus.org/topic/19904/function-list-tab-stops).

Cheers.

**Comment by Ekopalypse** [comment]
+1

**Comment by vinsworldcom** [comment]
@sasumner said:

"I think tab could be made to switch focus back and forth between the edit box and the treeview control; wondering if that is sufficient in this application?"

YES - absolutely, perfectly reasonable to just tab between the search edit box control and the treeview.  After I looked at the code, it seemed that would be the more easy to implement - though as you can see, my weak C++ skills did not yield an easy pull request.  I like the idea of keyboard navigation and latest fixes to Function List are making this more possible - adding the tab stops between search edit box and list view would make this Function List much better!

Thanks for taking the time to comment.

Cheers.

**Comment by vinsworldcom** [comment]
I understand this a bit better now.  To Tab from Function List tree view to the search box, we add [here](https://github.com/notepad-plus-plus/notepad-plus-plus/blob/95dec01e27717028bf6f50491f28e4b031a5f6b1/PowerEditor/src/WinControls/FunctionList/functionListPanel.cpp#L578):
```
				else if (ptvkd->wVKey == VK_TAB)
				{
					::SetFocus(_hSearchEdit);
				}
```

and to Tab from search box to the Function List tree view, we add [here](https://github.com/notepad-plus-plus/notepad-plus-plus/blob/95dec01e27717028bf6f50491f28e4b031a5f6b1/PowerEditor/src/WinControls/FunctionList/functionListPanel.cpp#L695):

```
			else if (wParam == VK_TAB)
			{
				::SetFocus(_treeView.getHSelf());
			}
```

EXCEPT that `_treeView` is unknown in that context - since the `static LRESULT CALLBACK funclstSearchEditProc()` is not a member of `FunctionListPanel`.

How can we get the handle of the Function List tree view?

Cheers.

**Comment by vinsworldcom** [comment]
This works:

```
diff --git a/PowerEditor/src/WinControls/FunctionList/functionListPanel.cpp b/PowerEditor/src/WinControls/FunctionList/functionListPanel.cpp
index 1899963b..323bf157 100644
--- a/PowerEditor/src/WinControls/FunctionList/functionListPanel.cpp
+++ b/PowerEditor/src/WinControls/FunctionList/functionListPanel.cpp
@@ -575,6 +575,10 @@ void FunctionListPanel::notified(LPNMHDR notification)
                                        }
                                        PostMessage(_hParent, WM_COMMAND, SCEN_SETFOCUS << 16, reinterpret_cast<LPARAM>((*_ppEditView)->getHSelf()));
                                }
+                               else if (ptvkd->wVKey == VK_TAB)
+                               {
+                                       ::SetFocus(_hSearchEdit);
+                               }
                        }
                        break;
                }
@@ -692,6 +696,11 @@ static LRESULT CALLBACK funclstSearchEditProc(HWND hwnd, UINT message, WPARAM wP
                                ::SendMessage(hwnd, WM_SETTEXT, 0, reinterpret_cast<LPARAM>(TEXT("")));
                                return FALSE;
                        }
+                       else if (wParam == VK_TAB)
+                       {
+                               ::SendMessage(GetParent(hwnd), WM_COMMAND, VK_TAB, 0);
+                               return FALSE;
+                       }
                }
        }
        return oldFunclstSearchEditProc(hwnd, message, wParam, lParam);
@@ -838,6 +847,11 @@ INT_PTR CALLBACK FunctionListPanel::run_dlgProc(UINT message, WPARAM wParam, LPA
                                        }
                                }
                        }
+                       else if (wParam == VK_TAB)
+                       {
+                               ::SetFocus(_treeView.getHSelf());
+                               return TRUE;
+                       }

                        switch (LOWORD(wParam))
             {
```

BUT .. only if there is not text in the search Window.  When you start typing in the Function List edit box search window and the Function List tree view narrows to the typed text, the Tab press while in the search edit box to get back to the narrowed down Function List tree view does *not* work.  Tab does nothing.

Maybe some logic needs to be added [here](https://github.com/notepad-plus-plus/notepad-plus-plus/blob/95dec01e27717028bf6f50491f28e4b031a5f6b1/PowerEditor/src/WinControls/FunctionList/functionListPanel.cpp#L642)?

Cheers.

**Comment by ArkadiuszMichalski** [comment]
@vinsworldcom Not fixed by your PR https://github.com/notepad-plus-plus/notepad-plus-plus/pull/8924 or you still want jump to Sort/Refresh button?

**Comment by vinsworldcom** [comment]
@ArkadiuszMichalski from the conversation above, I agreed with @sasumner that tab between list view and search box was fine and not needed to tab between the sort and refresh buttons.  I'm happy to close this one.
