### ISSUE TITLE
[Feature Request] Function List clear Search Box

### ISSUE THREAD

**Issue by vinsworldcom** [notepad-plus-plus/notepad-plus-plus#8667]
### Description of the Issue
When using the built-in Function List (View menu => Function List), the Escape key does not seem to do anything. One would normally use the Escape key to perhaps clear the Search Box of any previously entered text.

### Steps to Reproduce the Issue
1. Open document that has a Function List parser (e.g., C, C++)
2. Open Function List .. View menu => Function List
3. Click in the Search text box at the top of Function List
4. Type the name of a function to narrow the tree view results
5. Press the Escape key
6. Nothing happens

### Expected Behavior
I expect the Escape key to clear any text in the Search text box control.

### Actual Behavior
Nothing happens when pressing the Escape key.

### Debug Information
Notepad++ v7.8.9   (64-bit)
Build time : Aug  5 2020 - 03:12:03
Path : C:\usr\bin\npp64\notepad++.exe
Admin mode : OFF
Local Conf mode : ON
OS Name : Windows 10 Enterprise (64-bit) 
OS Version : 1809
OS Build : 17763.1339
Current ANSI codepage : 1252
Plugins : AnalysePlugin.dll AutoSave.dll BetterMultiSelection.dll ChangedLines.dll CodeAlignmentNpp.dll ColumnTools.dll ComparePlugin.dll CsvQuery.dll CustomizeToolbar.dll DoxyIt.dll DSpellCheck.dll Explorer.dll GitSCM.dll JSMinNPP.dll MarkdownTableGenerator.dll NppConsole.dll NppConverter.dll NppEventExec.dll NppExec.dll NppExport.dll NppFTP.dll NppMarkdownPanel.dll NppMenuSearch.dll Python Indent.dll QuickText.dll RelativeLineNumbers.dll SpeechPlugin.dll SurroundSelection.dll TagLEET.dll XMLTools.dll ZoomDisabler.dll

**Comment by sasumner** [comment]
Changes from this issue released in Notepad++ version 7.9
