### ISSUE TITLE
Custom toolbar buttons problem

### ISSUE THREAD

**Issue by Petewg** [notepad-plus-plus/notepad-plus-plus#867]
When I change UI language from Englisdh to local language (Greek in my case) tool-bar custom buttons stop working. 
![error image](http://s23.postimg.org/ofrtjqwcb/buttons_error.jpg)

Changing back to English resolves the problem.
![error image](http://s23.postimg.org/wwrbuo117/buttons_ok.jpg)

Any hint?

**Comment by Yaron10** [comment]
@Petewg,

You need to change the commands in CustomizeToolbar.btn to Greek.

Regards.

**Comment by Petewg** [comment]
Yaron10,
thank you for your suggestion, it  works!
The only drawback is that it's an one-way workaround which means that if I need to use English UI, the problem pops up again. What I thought to do was to add two groups of buttons definitions one for each language. It's not an elegant 'solution' though, because i have, in either case, one group of working buttons and another one of useless/disabled buttons. 
The ideal would be if custom buttons was  independent from UI-language.

thanks again,
regards

**Comment by Yaron10** [comment]
@Petewg,

I'm glad I could help.

I keep two "CustomizeToolbar.btn" files: one in English and one in my local language.
Please see [this](http://sourceforge.net/p/notepad-plus/discussion/482781/thread/991cb806/#a85a/8cd2/3ddb) request.

Best regards.
