### ISSUE TITLE
你妈是不是被中国给炸了？

### ISSUE THREAD

**Issue by HarborZeng** [notepad-plus-plus/notepad-plus-plus#8672]
Are your mom exploaded by China?

**Comment by HarborZeng** [comment]
希望你下次去或者路过香港的时候，直接拿国安法把你给办了，办的就是你这种没
![image](https://user-images.githubusercontent.com/8568937/89533562-318e7d00-d826-11ea-8371-3216a6e9da57.png)的人

**Comment by postbird** [comment]
github is a pure technical community, and the author of this software is like a shit of a pure gold community.

**Comment by postbird** [comment]
By the way, anyone else is using nodepad++?

**Comment by postbird** [comment]
How backward the area still using this software？TAIWAN？

**Comment by cooperfrench95** [comment]
> How backward the area still using this software？TAIWAN？

Yes. Cry about it some more.
