### ISSUE TITLE
Sorting with column block selection uses incorrect key

### ISSUE THREAD

**Issue by sasumner** [notepad-plus-plus/notepad-plus-plus#8674]
### Steps to Reproduce the Issue
1. Consider this text in an editor tab:
```
abcdef
abcddef
```
2. Make this column block selection:
![image](https://user-images.githubusercontent.com/30118311/89571291-67ffd400-d7f5-11ea-8828-c80da896f919.png)

3. Execute _Edit_ > _Line Operations_ > _Sort Lines Lexicographically Ascending_.

### Expected Behavior
Since the selected column key contains the same characters for both lines, the lines should remain in the original order after the sort.

### Actual Behavior
The lines incorrectly change order.

### Additionally
A zero-width column-block selection should use as the sort key each line's content from the column of the selection out to the end of line.  Currently, this type of selection will cause the **_single character_** at the caret column to be used as the key.

So, using the same data as above, and this selection:

![image](https://user-images.githubusercontent.com/30118311/89571437-aac1ac00-d7f5-11ea-98cb-42d1e2077d88.png)

will result in no change in line order, when it should swap the lines.

### Debug Information
Notepad++ v7.8.9   (32-bit)
Build time : Jul 15 2020 - 20:26:50
Path : C:\\.............\npp.7.8.9.bin\notepad++.exe
Admin mode : OFF
Local Conf mode : ON
OS Name : Windows 10 Enterprise (64-bit) 
OS Version : 1809
OS Build : 17763.1039
Current ANSI codepage : 1252
Plugins : mimeTools.dll NppConverter.dll NppExport.dll PythonScript.dll

**Comment by donho** [comment]
Column selection should not be considered while sorting, otherwise there'll be a lot of cases (operations) should be taken into consideration.

**Comment by sasumner** [comment]
@donho said:

>Column selection should not be considered while sorting

I don't understand this.  Column selection currently (N++ 7.8.9) **_IS_** considered while sorting, the current code is just doing it **_WRONGLY_**.

>a lot of cases (operations) should take column and multi-selection into consideration.

I agree that currently these types of selection operation support is lacking in N++, but it doesn't relate to current issue where column selection is already supported.

**Comment by sasumner** [comment]
Changes from this issue released in Notepad++ version 7.9
