### ISSUE TITLE
Special character `\R` for new line is not working as expected

### ISSUE THREAD

**Issue by byzod** [notepad-plus-plus/notepad-plus-plus#8678]
### Description of the Issue
`\R` is not working when use as class member

### Steps to Reproduce the Issue

1. Type text `RandomText1\r\nRandomText2` (\r\n here means windows newline) in npp, it looks like
```
RandomText1
RandomText2
```
2. Search `\R` then `[\R]`

### Expected Behavior
Both search targets the (two) newline character(s)

According to [official wiki](https://npp-user-manual.org/docs/searching/):

> `\n` ⇒ The LF control character 0x0A (line feed). This is the regular end of line under Unix systems.

> `\r` ⇒ The CR control character 0x0D (carriage return). This is part of the DOS/Windows end of line sequence CR-LF, and was the EOL character on Mac 9 and earlier. OSX and later versions use `\n`.

> `\R` ⇒ Any newline sequence. Specifically, the atomic group `(?>\r\n|\n|\x0B|\f|\r|\x85|\x{2028}|\x{2029})`.

### Actual Behavior
`\R` targets the line break
`[\R]` targets the first letter of `RandomText1`

Another Demo: 
> ![A1](https://user-images.githubusercontent.com/848607/89644821-3e28d900-d8eb-11ea-9d68-e44b0edd950b.gif)

### Debug Information

Notepad++ v7.8.9   (64-bit)
Build time : Jul 15 2020 - 20:31:49
Path : K:\App\something\Notepad++\Notepad++.exe
Admin mode : OFF
Local Conf mode : ON
OS Name : Windows 10 Pro (64-bit) 
OS Version : 1703
OS Build : 15063.850
Current ANSI codepage : 936
Plugins : ComparePlugin.dll CSharpRegexTools4Npp.dll EmmetNPP.dll HexEditor.dll JSMinNPP.dll mimeTools.dll NppConverter.dll NppExport.dll NppTextViz.dll PythonScript.dll

**Comment by sasumner** [comment]
`\R` is not treated as a special sequence when inside `[` and `]`.
It is treated as, simply, `R`.
This is a function of the regular expression engine that Notepad++ uses, and is not something that Notepad++ has control over.
