### ISSUE TITLE
HTML Enclose Tag

### ISSUE THREAD

**Issue by johanessurya** [notepad-plus-plus/notepad-plus-plus#868]
When I comment an HTML tag it seems pairing with uncomment tag. For Example:
```
<div>
<!-- <div> -->
</div>
```
It should 1st div paring with 3rd div, but not. 2nd div pairing with 3rd div. 

Here my screenshot:
![npp-enclose-tag](https://cloud.githubusercontent.com/assets/2444537/9718302/ccde08e8-55a4-11e5-8b77-18ee57489a50.jpg)

**Comment by QxE6MqkpJFsZ** [comment]
My group and I (SEATURCH, Amy3618, QxE6MqkpJFsZ) would be happy to look into and fix this.
