### ISSUE TITLE
[Feature Request] Sort lines randomly (i.e., shuffle lines)

### ISSUE THREAD

**Issue by sasumner** [notepad-plus-plus/notepad-plus-plus#8682]
In Notepad++ 7.8.9, current as of this writing, there is an ability to sort lines in a variety of ways, but no choice to sort the lines randomly, that is, to shuffle them.  It would be nice to have this as a choice in addition to the existing sort types.

**Comment by donho** [comment]
Before saying why not, I would ask why firstly.
Why do users need such feature?

**Comment by sasumner** [comment]
>Why do users need such feature?

* As a user, I use N++ as a data generation tool for creating input to other things.  Being able to add some randomness to line-based data is often useful.

* We don't need to have any sorting features in N++; users could use CMD's `sort` (and others like it).  But `sort` can't do random.

* There once was a Pythonscript developed for it based on a Community posting and put on github as a gist, but it has since been removed.  It is easy to do as a script, but I thought it was more convenient as a N++ function.

* It can help to mix lines before N++ developers (as users during testing) test other sort functions.  :-)

* **BEST**:  Why do users need `ranDOm CasE` ? :-)
![image](https://user-images.githubusercontent.com/30118311/89708610-9fca6100-d946-11ea-8e97-8d2a686dbd8a.png)

I don't want to "over sell" the idea.
I just thought it was a nice addition.
Perhaps I was wrong and it is only useful to a very few.

**Comment by sasumner** [comment]
Changes from this issue released in Notepad++ version 7.9

**Comment by sasumner** [comment]
User endorsement for completed feature ! :

![image](https://user-images.githubusercontent.com/30118311/94444212-1419c780-0174-11eb-9de7-00fddaa0d50d.png)

**Comment by donho** [comment]
I have no doubt from the beginning! Oh wait... never mind :D
