### ISSUE TITLE
Cursor is blinking when is hovered on a URL

### ISSUE THREAD

**Issue by helperman** [notepad-plus-plus/notepad-plus-plus#8686]
### Description of the Issue
When I move cursor over any URL it blinks.
Eyes are tired of that.

### Steps to Reproduce the Issue

https://youtu.be/QlHCE0b9AHU

### Expected Behavior
No blinking. Healthy eyes.

### Actual Behavior
Blinking.

### Debug Information
Notepad++ v7.8.9   (64-bit)
Build time : Jul 15 2020 - 20:31:49
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS Name : Windows 8.1 Pro (64-bit) 
OS Build : 9600.0
Current ANSI codepage : 1251
Plugins : mimeTools.dll NppConverter.dll NppExport.dll

**Comment by sasumner** [comment]
URL stuff is being worked on and is evolving; thank you for your report.

**Comment by donho** [comment]
It's been fixed in https://github.com/notepad-plus-plus/notepad-plus-plus/commit/d55350b4b5db71889d0a92aabe5ae10d41c92507.
The fix will come with the next release.
