### ISSUE TITLE
[ctrl] - [tab] jump seems broken

### ISSUE THREAD

**Issue by ophian** [notepad-plus-plus/notepad-plus-plus#8687]
Notepad++ v7.8.9

Try to jump between open pages, back and forth.

**Comment by sasumner** [comment]
Works super for me.
Provide more information (see the issue template you deleted before submitting) for possible reopening.
Closing.

**Comment by ophian** [comment]
Yeoo sorry. 
A new day, issue is gone. Maybe it was too hot yesterday, but it really happend over some time.
