### ISSUE TITLE
Different shortcut names in Shortcut Mapper table and menu

### ISSUE THREAD

**Issue by Uhf7** [notepad-plus-plus/notepad-plus-plus#8689]
This is about the Shortcut Mapper, tab 1, _Main Menu_.

The shortcut names displayed in the first column are mostly derived from the names of the according menu entries. This is good for most of them, but some commands call for different names in the menu and in the shortcut table. Example:
Menu -> View -> Collapse Level -> 1
The menu entry is "1", and so is the name in the Shortcut Mapper. Not exactly intuitive.

All localized names in this page of the Shortcut Mapper come from the Menu/Main/Commands element of the Language.xml. This contains sub-elements, which have the attributes **id** and **name**. **id** contains the command number, **name** contains how to show it in the menu.

My proposal here is, to add another, optional attribute (I named it **shortcut**). It has not to be there at all, but if it is there, then it is used as display name in the Shortcut Mapper. If it is not there, then the attribute **name** is used for the Shortcut Mapper like before. Useful things can be done with it:

                    <Item id="44051" name="1" shortcut="Collapse Level 1"/>
                    <Item id="44052" name="2" shortcut="Collapse Level 2"/>
                    <Item id="44053" name="3" shortcut="Collapse Level 3"/>

or:

                    <Item id="44081" name="Project Panel 1" shortcut="Toggle Project Panel 1"/>
                    <Item id="44082" name="Project Panel 2" shortcut="Toggle Project Panel 2"/>
                    <Item id="44083" name="Project Panel 3" shortcut="Toggle Project Panel 3"/>
                    <Item id="44085" name="Folder as Workspace" shortcut="Toggle Folder as Workspace/>

In all examples, we want to keep the short name in menu, but need something more in the Shortcut Mapper. The names in the Shortcut Mapper could be updated step by step, there is no rush to change all language files at once. And, in the native English version, which works without language file, the Shortcut Mapper names come from the `winKeyDefs []` table in `Parameters.cpp`, and the menu names come from the menu resource in `notepad_plus.rc`.

This is also a preparation for some new commands, which I want to put into the command list of the Shortcut Mapper, but which I do not want to have in the menu:

                    <Item id="44xxx" name="Project Panel 1" shortcut="Launch Project Panel 1"/>
                    <Item id="44xxx" name="Project Panel 2" shortcut="Launch Project Panel 2"/>
                    <Item id="44xxx" name="Project Panel 3" shortcut="Launch Project Panel 3"/>
                    <Item id="44xxx" name="Folder as Workspace" shortcut="Launch Folder as Workspace"/>

For all of those commands it seems important, that they are labeled correctly in the Shortcut Mapper.

**Comment by donho** [comment]
The dependency of `nativeLang.xml` is not a solution for the problem to me, because the major Notepad++ users use English version of Notepad++.

**Comment by donho** [comment]
> . Useful things can be done with it:
                    <Item id="44051" name="1" shortcut="Collapse Level 1"/>
                    <Item id="44052" name="2" shortcut="Collapse Level 2"/>
                    <Item id="44053" name="3" shortcut="Collapse Level 3"/>

I don't want to add the above lines for just shortcut mapper. I don't want either change the <Commands> structure by adding "shortcut" attribute just for this feature. 
I would add a section named <Override> in <ShortcutMapper>:
```
            <ShortcutMapper title="Shortcut Mapper">
                <Item id="2602" name="Modify"/>
                <Item id="2603" name="Delete"/>
                <Item id="2606" name="Clear"/>
                <Item id="2607" name="Filter: "/>
                <Item id="1" name="Close"/>
                <ColumnName name="Name"/>
                <ColumnShortcut name="Shortcut"/>
                <ColumnCategory name="Category"/>
                <ColumnPlugin name="Plugin"/>
                <MainMenuTab name="Main menu"/>
                <MacrosTab name="Macros"/>
                <RunCommandsTab name="Run commands"/>
                <PluginCommandsTab name="Plugin commands"/>
                <ScintillaCommandsTab name="Scintilla commands"/>
                <ConflictInfoOk name="No shortcut conflicts for this item."/>
                <ConflictInfoEditing name="No conflicts . . ."/>
                <Override> <!-- can you find a better name than "Override"? -->
                    <Item id="44051" name="Collapse Level 1"/>
                    <Item id="44052" name="Collapse Level 2"/>
                    <Item id="44053" name="Collapse Level 3"/>
                    <!-- more items here -->
                </Override>
            </ShortcutMapper>
```

**Comment by Uhf7** [comment]
@donho,

since there is already a section `<ShortcutMapper>`,  and since all translated texts in the language.xmls are stored in the attribute `name`, your solution fits better than mine. Thank you for finding it.

Concerning `<Override>`: The table in the Shortcut Mapper is named `<MainMenuTab>` here. And the id's specified in there should belong to this table in the Shortcut Mapper. So I would suggest `<MainMenuNames>` or `<MainMenuShortcutNames>`. Alternatively, it could be `<CommandNames>`.

**Comment by KnIfER** [comment]
[A cheaper solution:](https://github.com/KnIfER/NotMad-Text-Editor/commit/c1a985ea0cd00950cdabace483d04f3b0799c30e)

Fetch sub-menu names dynamically from the menuhandle, and fill them into the Category column like below

![Screenshot (661)](https://user-images.githubusercontent.com/11593903/91652009-b424f800-eac5-11ea-975a-54a536b11d92.jpg)

However the category field is not searchable and therefore 'cheap'

**Comment by Uhf7** [comment]
> A cheaper solution:

I see two downsides of the cheaper solution:
- All keyboard shortcut commands have to be in the menu to fetch there category names from it, but I need some keyboard shortcuts not existing in the menu.
- The names in the menu should still be different to the names in the keyboard shortcut table in some cases, example:
  - Menu: "View -> Document Map"
  - Keyboard shortcut table: "Toggle Document Map" or "Switch to Document Map".
In the menu, the toggling behavior is expressed simply by the check mark left to the menu entry, but this cannot be expressed the same way in the keyboard shortcut table. An I don't want to have "Toggle Document Map" in the menu, that's too many words there, it doesn't look right.

**Comment by KnIfER** [comment]
> but I need some keyboard shortcuts not existing in the menu.

In my solution the 'category path' is packed into a number. if it is zero, then fallback to the orginal string `_category`, which is hard-coded and not localized, but can be any value. 

On the other hand,  keyboard shortcuts that do not exist in the menu are likely to have the same category as existing ones.

> "Toggle" or "Switch".

Just added a menu option `Switch To Instead Of Toggle Panels`

![Screenshot (664)](https://user-images.githubusercontent.com/11593903/91781781-c621aa80-ec2d-11ea-83db-a804e942b5e9.jpg)


Currently menu's "Toggle" or "Switch" behaviours are not very consistent, example: 

  * Menu: "Edit-> Clipboard History"、"Edit-> Character Panel" 
    * those are 'switch to'
  * Menu: "View-> Project Panels 1/2/3"、"View -> Document Map" 
    * those are 'toggle'

I think it's more important to keep them consistent rather than add new shortcuts

**Comment by Uhf7** [comment]
> Currently menu's "Toggle" or "Switch" behaviors are not very consistent, example

Yes, this inconsistencies have already been complained about in #8471, and although the Character Panel and the Clipboard History are not top priority on my list, they should be able to be toggled some day too.

> Just added a menu option Switch To Instead Of Toggle Panels

I wouldn't go this way. I expect menu commands and keyboard shortcuts to behave the same way every time, and I do not expect, that they behave depending on a current setting like your menu option.
