### ISSUE TITLE
Administrator mode bug

### ISSUE THREAD

**Issue by bakatrouble** [notepad-plus-plus/notepad-plus-plus#869]
After re-opening file in administrator mode changes can't be saved to file immediately.
Bug illustration: http://i.imgur.com/WUXfbfh.gifv

**Comment by donho** [comment]
Fixed.

**Comment by pgrat** [comment]
When Notepad++ is execited in the administror mode, the command in the contextual menu does not works. (last version 7.6.6).
![Pb n++](https://user-images.githubusercontent.com/9526045/57453957-ff2f5200-7267-11e9-813c-601e4dfb3c7b.jpg)
