### ISSUE TITLE
[Feature Request] Add number of hit lines to file-level search output

### ISSUE THREAD

**Issue by sasumner** [notepad-plus-plus/notepad-plus-plus#8692]
Much like #8154 augmented the file-level search output with additional helpful information, it would be nice to enhance it again in such a way as to see the number of lines having hits in each file.  A picture may describe the proposal best:

Current output from a file-level search (N++ 7.8.9):

![image](https://user-images.githubusercontent.com/30118311/89946781-71bc7980-dbf1-11ea-9513-7731803849e0.png)

Proposed improved output:

![image](https://user-images.githubusercontent.com/30118311/89946375-cf03fb00-dbf0-11ea-9bbb-70c8937ee904.png)

**Comment by Yaron10** [comment]
@sasumner,

This is a nice idea and would be a useful addition. :+1: 

I suppose the option to display only one line with multiple *clickable* occurrences has been suggested and discussed before.
Here is an illustration from EditPad.

![תמונה](https://user-images.githubusercontent.com/10229320/90056345-664b7a00-dce7-11ea-98ce-814fd1a90ed6.png)

**Comment by sasumner** [comment]
>I suppose the option to display only one line with multiple clickable occurrences has been suggested and discussed before.

So it is Off-Topic for the current issue, but:

Well... the "multiple-clickable-occurrences" part gets into touching the code for "Search result" lexing, which already has some bugs as discussed before (8525 and others), which is "part of" Scintilla and thus not updated frequently, and anyway quite frankly scares me.  :-)

This general idea is put forth, without the "multiple-clickable-occurrences" part, in #1499, and indeed I am considering implementing that (in a limited way, sorry, for now no multiple-clickables!).

I noticed [THIS](https://community.notepad-plus-plus.org/topic/19837/find-all-in-current-document-not-displaying-complete-lines) where someone wanted (or actually, didn't want) **_"...the cursor jumps to the main window but at the location of the characters that were found, not iat the position I was in the Find results window."_** and so that gave me the idea that double-clicking (probably with a modifier, e.g., Ctrl) could jump the user not to the hit, but to the position double-clicked at.  I mention it here because it is semi-related to what you were saying; perhaps it could become part of 1499 's implementation, or it could even stand alone as its own issue.

**Comment by sasumner** [comment]
ON-Topic:

>This is a nice idea and would be a useful addition. 

Thank you (for offering an opinion, the fact that it is a positive one is just a bonus :-) )
I do have an implementation for this queued up and ready to submit, was just hoping for some feedback first.

Do you think the `on XX lines` info would bother some users, so much so that it needs a "preference"? (to which I say "UGH!")

No one (that I'm aware of) has complained about 8154's `of YY searched` addition...

I briefly considered `(ZZ hits on XX lines in WW files of VV searched)`, but, hehehe, seems "heavy". :-)

**Comment by Yaron10** [comment]
> Well... the "multiple-clickable-occurrences" part gets into touching the code for "Search result" lexing, which already has some bugs as discussed before (8525 and others), and which is "part of" Scintilla and thus not updated frequently, and anyway quite frankly scares me. :-)

I see.

> This general idea is put forth, without the "multiple-clickable-occurrences" part, in #1499, and indeed I am considering implementing that (in a limited way, sorry, for now no multiple-clickables!).

:+1: 

> Do you think the on XX lines info would bother some users, so much so that it needs a "preference"? (to which I say "UGH!")

IMO it's useful and not confusing at all. No extra setting.

> I briefly considered (ZZ hits on XX lines in WW files of VV searched), but, hehehe, seems "heavy". :-)

I think that your original suggestion (lines per file) is better.

Thank you for your work.

**Comment by sasumner** [comment]
@Yaron10 

Does the following output (from a regex search) make sense to you?
(I'm asking for an evaluation of the the `on 5 lines` part)

![image](https://user-images.githubusercontent.com/30118311/90264891-cba28680-de1f-11ea-9fc6-df19b123cd9e.png)

**Comment by Yaron10** [comment]
@sasumner,

I'm afraid I don't understand the question. Why should it be `on 5 lines`?

BTW, should it be `on` or `in` (IMO `in`)? - We need a native English speaker here.

**Comment by sasumner** [comment]
>BTW, should it be on or in (IMO in)? - We need a native English speaker here.

No one is more of a native English speaker than I am. :-)
`on` is probably best but `in` is also fine...not sure which to actually choose now

>Why should it be "on 5 lines"?

So now we have trouble.
If you don't understand it, others won't as well. :-(

**Comment by Yaron10** [comment]
> No one is more of a native English speaker than I am.

Well, my observation is not as good as I thought it was.

> If you don't understand it, others won't as well.

It seems that my understanding is not as good either. :)

**Comment by sasumner** [comment]
The answer to "Why should it be on 5 lines?":

Two of the hits are multi-line. They start on one line and finish on the next.  So when counting up the lines, that counts for 2.  Other hits in this example are multiples per line (e.g. line 6 has 2 full `abacab` and one partial) and that kind of line is counted only 1 time.

**Comment by Yaron10** [comment]
It must have to do with RegEx about which I don't know anything.
(The RegEx I recently suggested for URLs detection was not mine and I mentioned the source).
Please explain it.

> Have I somehow tricked you into believing I am a non-English native?

Not at all. A fault in my observation.

**Comment by sasumner** [comment]
>Please explain it

Ah, I thought you were good with regex.  I guess just like my English-ness fooled you about me, the regex stuff had me fooled about you. :-)

Ok, so rather than explain it from a regex perspective, let me just show you the "marked lines" version of the same search, see if you now see why it is "on 5 lines":

![image](https://user-images.githubusercontent.com/30118311/90277982-9c4a4480-de34-11ea-96ba-4e6a5fe0d37c.png)

**Comment by Yaron10** [comment]
Thank you.

Well, at least my eyesight is still good. :)

So users with some RegEx knowledge should understand the `5 lines`, correct?

**Comment by sasumner** [comment]
I would think so.  The usual case for a search is just a literal word, and for that it is straightforward.  But, as is the case with other things, with regex things get more complicated.  I guess with stepped-up power comes a need to think a bit harder about some results you are seeing.  (Much like backward regex searching, but let's not get into that).

**Comment by Yaron10** [comment]
:+1: 
Thanks again for working on it.

**Comment by donho** [comment]
It's a "why not" feature to me, but it's not 2 lines implementation, so I have to reject this feature. Sorry about that.

**Comment by sasumner** [comment]
@donho 

>It's a "why not" feature to me, but it's not 2 lines implementation, so I have to reject this feature. Sorry about that.

Perhaps if I'd have said it was the "first part" of a larger feature I was working on, it would have won you over to my side.
Maybe I'll try the larger feature, and then this becomes a "why not" short modification to that?  :-)
