### ISSUE TITLE
Rename fails when relocating file to a different drive

### ISSUE THREAD

**Issue by southisup** [notepad-plus-plus/notepad-plus-plus#8694]
### Description of the Issue

_Rename…_ silently fails when its _Save As_ dialogue is used to navigate to a different drive, regardless of the source/destination local/network combination. Amending the file name is actually irrelevant, it's the drive change that causes the failure.

Possibly related to some of the factors discussed under issue #3615 _File rename fails when changing case_.

### Steps to Reproduce the Issue

1. Create test file on local or network drive
2. Use _Rename…_ from either the _File_ menu or tab context menu
3. In the resulting _Save As_ dialogue, change the filename and also browse to a different local or network drive
4. _Save_

### Expected Behavior

File is renamed and relocated, and tab name is revised, as happens when using same process to simultaneously rename and relocate on same drive.

### Actual Behavior

Nothing. File name, location, and tab name are all unchanged.

### Debug Information

Notepad++ v7.5.9   (64-bit)
Build time : Oct 23 2018 - 22:14:15
Path : C:\Program Files\WindowsApps\NightRise.NotepadWrapped_7.59.32.0_x64__bahp16nyyek9m\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10 (64-bit)
Plugins : DSpellCheck.dll mimeTools.dll NppConverter.dll ComparePlugin.dll MarkdownViewerPlusPlus.dll

**Comment by sasumner** [comment]
When submitting a bug report against software, it is customary to update to the newest version of that software available.  For Notepad++ that is currently 7.8.9, where there is no problem with renaming to a different drive.  This was addressed here:  #6111

**Comment by southisup** [comment]
Sorry! The app does not identify anywhere that it is a fork, and only on the Microsoft Store page does it even call itself ‘unofficial’, so because I installed it a long time ago and Windows has maintained it ever since, I forgot completely it's a fork. Apparently they're working to update it.

https://www.microsoft.com/store/productId/9PLHC123MQWT
https://github.com/WoofyIO/notepad-plus-plus
