### ISSUE TITLE
TYPO in CONTRIBUTING.md

### ISSUE THREAD

**Issue by southisup** [notepad-plus-plus/notepad-plus-plus#8695]
### Description of the Issue

_example_ misspelt _exemple_ in list item 2 at https://github.com/notepad-plus-plus/notepad-plus-plus/blob/master/CONTRIBUTING.md#guidelines-for-pull-requests

**Comment by shrisha-h** [comment]
@donho Mind if I take this up?

**Comment by sasumner** [comment]
@shrisha-h It's only a typo; Don will take care of it

**Comment by donho** [comment]
Typo fixing and code refactoring won't be accepted - please create issues with title started with TYPO to request the changing:
https://github.com/notepad-plus-plus/notepad-plus-plus/blob/master/CONTRIBUTING.md#guidelines-for-pull-requests

**Comment by sasumner** [comment]
>code refactoring won't be accepted

How about "code refactoring" from team members? :-)
There are some duplicated sections of code in FindReplaceDlg.cpp that really need to be combined into one, before further changes are made.
I would like to do this, but so far have been hesitant to do so.

**Comment by donho** [comment]
@sasumner 

If the refactoring makes sens, go ahead. Surly team members and some old contributors are trustful, but please test more still to avoid the regression.
