### ISSUE TITLE
DirectWrite poor performance (slow, choppy)

### ISSUE THREAD

**Issue by AlexBlandin** [notepad-plus-plus/notepad-plus-plus#8698]
### Description of the Issue
On my primary machine Scintilla's DirectWrite technology (`SC_TECHNOLOGY_DIRECTWRITE`) runs very slow and "choppy" (ie, a very low refresh rate and uncomfortably high latency).

This can be resolved by either disabling DW (but then you lose ligatures etc) or by using the DirectWrite variant that backs onto GDI Device Contexts (`SC_TECHNOLOGY_DIRECTWRITEDC`).
Having a selectable menu between "Default", "DirectWrite", "GDI DirectWrite" (or somesuch) may be a necessary workaround for people with this issue (if they're not using LuaScript or another plugin to control Scintilla).

Running latest NVidia drivers (451.67) etc and all options are set to prefer GPU for hw-accel (and it's certainly not the hardware that's an issue).
This resembles reports for people having similar issues with older games that use DirectWrite in Windows 10, which seems to be a spurious problem caused by a change specific to Win10 (I've seen this issue persist for 2~3 years now with the latest updates on Win10 and latest drivers so no idea what's the root cause).

### Steps to Reproduce the Issue
Select "Use DirectWrite" in Settings->Preferences->MISC. and restart. Not all machines exhibit this problem (even with matching OS versions and drivers, tested against a laptop with same OS version and drivers and also on a laptop with same OS version but integrated graphics, neither of which have had the issue).

### Expected Behavior
Notepad++ running smoothly.

### Actual Behavior
It didn't. If you're focused on the NP++ window mouse movement etc will be choppy, select away to another window or the desktop and there's no issue.

### Debug Information
Notepad++ v7.8.9   (32-bit)
Build time : Jul 15 2020 - 20:26:50
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS Name : Windows 10 Home (64-bit) 
OS Version : 1903
OS Build : 18362.959
Current ANSI codepage : 1252
Plugins : DSpellCheck.dll LuaScript.dll mimeTools.dll NppConverter.dll NppExport.dll SurroundSelection.dll 

Used LuaScript to set Scintilla technology to SC_TECHNOLOGY_DIRECTWRITEDC. Having LuaScript set it to SC_TECHNOLOGY_DIRECTWRITE has the same effect as using the built-in option in MISC. (and I made sure startup.lua didn't change the technology when testing the built-in option).

**Comment by ValZapod** [comment]
This can happen because of working G-sync (VRR API)? 
![image](https://user-images.githubusercontent.com/31514790/91717612-82319580-eb9a-11ea-8cca-cb68630a2c45.png)

**Comment by AlexBlandin** [comment]
That's a very good suggestion and also resolves. As an external solution this may work for anyone else with similar issues, though if the profile inspector doesn't work for them then this is a reasonable fallback (assuming they absolutely have to keep G-Sync enabled for windowed applications, which I didn't even realise was set in the Nvidia control panel for me so I've just disabled it outright -- I think I had been testing something at some point and never noticed that I'd left it enabled).

**Comment by ValZapod** [comment]
> assuming they absolutely have to keep G-Sync enabled for windowed applications

Now G-sync works everywhere, including Photoshop on OpenGL or Blender. Chrome is also introducing support soon. It is a must have feature, for example for video. I am afraid if it is choppy you have A VERY slow PC. It is not even OpenGL, it is just DirectWrite.

**Comment by AlexBlandin** [comment]
... I'm not quite sure you understand how G-Sync works given these statements.

It is most certainly not an issue with the performance of the hardware, thank you very much for the insinuation.
This is likely an "issue" in how Scintilla/NP++ is flushing DirectWrite and thus drawing to screen, causing G-Sync to believe the framerate is much lower than it should be and lowering the refresh rate of the monitor to match (it's likely not flushing "properly" as far as the Nvidia driver is concerned, which is really just Nvidia's fault for their low effort driver and not something I think that Scintilla or NP++ devs should be concerned with, though Nvidia has never bothered to fix these kinds of problems so it's up to them if they want to put the effort into a workaround or not).

GDI likely sidesteps the issue as it's "too old" so G-Sync doesn't bother to monitor for it. G-Sync's detection in windowed mode is based on "working with" DWM, of which it does a poor job so and likely just detects D3D usage (which D2D and thus DW back onto).

I am not quite sure what you are trying to say with the rest of your comment, since G-Sync is certainly not a "must have" feature in windowed applications as they all go through the compositor, DWM, which is double buffered and V-synced by default so has no tearing. I'm not quite sure why you'd run G-Sync in windowed applications anyway since all you're doing is asking for trouble with Nvidia's drivers (as this demonstrates). Oh, and I don't think it's worth it for video since even in exclusive fullscreen you can just use V-sync to avoid tearing as, unlike a game, it's not sensitive to input latency (_it's just video_ after all).

And, my apologies, but I have no idea what this fragment: "It is not even OpenGL, it is just DirectWrite" is supposed to mean or contribute in this context.

Regardless, as I am now aware that it was just G-Sync being enabled in windowed mode for some reason, I'm happy to close here.
I still think that having the option to select GDI in the menu would be beneficial, so feel free to re-open or link to this if you have a pull request for this or whatever, but I feel I can consider this closed with:

1. Disable G-Sync for windowed applications and only use it for exclusive fullscreen
2. _Unless_ you absolutely know you need it enabled for other windowed applications, then you can disable it in NP++ (and potentially other Scintilla-backed applications) using the Nvidia Control Panel or the Profile Inspector
3. _Unless_ that doesn't seem to work for you or you'd rather use LuaScript, then the outlined workaround with `SC_TECHNOLOGY_DIRECTWRITEDC` backing onto the GDI handle should work
4. Otherwise, if that doesn't work, then I've got nothing, sorry! Maybe you'll have more luck contacting Nvidia than I.

**Comment by ValZapod** [comment]
> Oh, and I don't think it's worth it for video since even in exclusive fullscreen

Oh, it is very worth it, as for example, 24.000 and 23.976 videos can the be presented in its real frame rate.

**Comment by ValZapod** [comment]
> flushing "properly" as far as the Nvidia driver is concerned

It cannot flush anything as only Vulkan and Directx 12 support such manipulations. 

> lowering the refresh rate of the monitor to match

Not less than its least VRR value, indeed on real G-sync it can be 1 fps, which can cause (but really should not) some issues.

**Comment by ValZapod** [comment]
> avoid tearing as, unlike a game, it's not sensitive to input latency

Of course it is sensetive to input latency. Are you joking))) Everything is sensetive, desktop and otherwise. That is why HDMI 2.1 ALLM was introduced! Activating G-sync in DWM (it is also a work in progress, Microsoft already did it for Xbox) will also be great! 

Also, it is not really only about tearing. For example Apple watch uses it to update display 1 time per second and thus use less energy, color e-ink displays use it to correctly show some animations, etc.

**Comment by AlexBlandin** [comment]
I really do not want to have this derail further, so I'll (try to) be brief.

> Oh, it is very worth it, as for example, 24.000 and 23.976 videos can then be presented in its real frame rate.

Go read up on the sampling theorem. Basically every panel supports 60Hz, if it doesn't then I think we can call that an edge case as far as most people are concerned. So video from 30Hz and below is a non-issue. "What about 60Hz video?" Well that's why people should be pushing for 120Hz monitors beyond just gaming (and besides the improved smoothness etc.). And, no, most people are unlikely to be watching video above 60Hz, don't bother bringing that up.

> It cannot flush anything as only Vulkan and Directx 12 support such manipulations. (OpenGL also have some magical things but it really cannot control VRR.)

Go read up on ID2D1RenderTarget::Flush and ID3D11DeviceContext::Flush. Oh, and DwmFlush. I'm not going to waste my time talking about the other things there and "controlling VRR" if you don't seem to understand what flushing actually means.

> Not less than its least VRR value, indeed on real G-sync it can be 1 fps, which can cause (but really should not) some issues.

Not important here, why would I bother?

> Of course it is sensetive to input latency. Are you joking))) Everything is sensetive, desktop and otherwise.

A continual video that is ideally just playing until it stops? Sensitive to latency? Surely you're the one joking here, there's no input unless you need it to pause, and if you do then a fractional-second delay is nothing since you can generally rewind at least 2s or so. If you need to do frame-by-frame checks, just extract the frames rather than using a video player, please.

The main reasons people care in games is 1) reducing simulation sickness, 2) they're under time pressure (multiplayer etc) and so want to reduce latencies they can control to reduce that pressure, or 3) they want to feel really good about the expensive setup and think they have a competitive edge when in reality they have much more important things to worry about than a couple milliseconds on top of what the monitor and application are already delaying by.

Clearly, those don't really apply to the _vast majority_ of windowed applications in normal use. Especially not video. Please stop joking. Many programs have built-in sleep and lag timers to keep from updating quicker, at most on a 60Hz monitor is 17ms delay from switching, for most people this is absolutely acceptable and well below the 100ms threshold for concern most devs I know operate at.

> That is why HDMI 2.1 ALLM was introduced

Just read what [HDMI has to say on it](https://www.hdmi.org/spec21Sub/AutoLowLatencyMode). I'll save you the click anyway:

> Auto Low Latency Mode enables the ideal latency setting to automatically be set allowing for smooth, lag-free and uninterrupted viewing and interactivity. In many cases this is referred to as game mode, and it usually has to be set manually which involves going through menus and settings and then switching back again for normal viewing.
> 
> ALLM lets a game console, PC or other device send a signal to the display which will cause it to automatically switch to a low-latency, low-lag mode for gaming. This could benefit other uses, such as karaoke and video conferencing too.
> 
> But a low latency setting may not be ideal for other types of viewing since some processing features on a TV may be stopped in order to reduce latency. So with ALLM when the source no longer requires this mode—for example, when switching to a movie stream—the source disables the signal and the display reverts back to its previous mode for optimal picture.

Carrying on...

> Activating G-sync in DWM (it is also a work in progress, Microsoft already did it for Xbox) will also be great!

Again, "for Xbox" shows what it's about: gaming. DWM is already tear free. And I'll continue this below because:

> Also, it is not really only about tearing. For example Apple watch uses it to update display 1 time per second and thus use less energy, color e-ink displays use it to correctly show some animations, etc.

Yeaaah... Look, there are low hanging fruit for power efficiency, turning the brightness down probably has a lot more of an effect than the refresh rate (certainly rates over 60Hz draw more but even then it'll be less than 200W in the worst case). Windows is a desktop/server OS so the monitor is probably plugged into the wall, not a battery. If you're using a laptop then turn the brightness down and be done with it, you could set the refresh rate to 60Hz if you really wanted but you're not gaining a huge amount in efficiency. If you're using an e-ink display for Notepad++... I'm afraid you're literally the definition of a corner case.

Please don't bother responding. Your optimism is appreciated, but also completely outside the scope of Notepad++'s issues. I'm only commenting in the hopes that with this it will stop and you won't bother anyone else about this.

May this issue lie dead and buried (closed) until such a time that it may be relevant or helpful to someone.

***Please DO NOT respond, ValZapod. I am not going to reply and am muting this issue.***
