### ISSUE TITLE
Existential Quantifier Symbol displayed incorrectly

### ISSUE THREAD

**Issue by sevi1603** [notepad-plus-plus/notepad-plus-plus#8702]
### Description of the Issue
Existential Quantifier Symbol (∃) sometimes not being displayed

### Steps to Reproduce the Issue

1. Create a new Tab
2. Copy the Symbol "∃" as the very first Symbol. It will be displayed as a square symbol
3. The symbol will display correctly if a different symbol follows. Pasting the string "∃∀" will display the existential quantifier correctly

### Expected Behavior
The Symbol "∃" will always display correctly

### Actual Behavior
The Existential Quantifier Symbol can only be pasted when it's part of a longer string.

### Debug Information
Notepad++ v7.8.9   (32-bit)
Build time : Jul 15 2020 - 20:26:50
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS Name : Windows 10 Enterprise (64-bit) 
OS Version : 2004
OS Build : 19041.388
Current ANSI codepage : 1252
Plugins : ComparePlugin.dll DSpellCheck.dll mimeTools.dll NppConverter.dll NppExport.dll

**Comment by sasumner** [comment]
Please paste a screenshot of your _Preferences_ > _MISC._ tab.

**Comment by sevi1603** [comment]
![grafik](https://user-images.githubusercontent.com/33391108/90115445-6897ed80-dd54-11ea-868d-6b1220bdea63.png)

**Comment by sasumner** [comment]
Try ticking the `Use DirectWrite...` box and see if that affects your issue.

**Comment by sevi1603** [comment]
Yes, after enabling DirectWrite and restarting NP++ the issue is gone. Thanks for the tip!
When I disable DirectWrite again, the issue comes back.

**Comment by sasumner** [comment]
>When I disable DirectWrite again, the issue comes back.

Well, don't do that! :-)
This is one of the things that DirectWrite is supposed to solve.
Reference the "may improve rendering of special characters" part.
