### ISSUE TITLE
你和香港暴徒站在一起（YOU STAND WITH Hong Kong MOB）

### ISSUE THREAD

**Issue by liuquanal** [notepad-plus-plus/notepad-plus-plus#8703]
你有你的立场，我也有我的立场，很好，我讨厌你，顺便讨厌你的项目。
You have your side, I have mine. Good. I hate you, and I hate your project.

**Comment by liuquanal** [comment]
我已经向中国国家网信部举报你了，你等着你的网站在中国关闭吧！你应该不需要中国市场，因为你和香港暴徒站在一起。

 
I have reported you to the Ministry of Cyberspace of China, you wait for your website to be closed in China! You probably don't need the Chinese market, because you're on the side of the Hong Kong mob.

**Comment by wenzhifeifeidetutu** [comment]
他妈今晚必死

**Comment by cirosantilli** [comment]
https://github.com/cirosantilli/china-dictatorship/tree/c0c41e7c55a7641fd00aad06beefa824e6f5b9c8#nazi

![](https://web.archive.org/web/20200109143505im_/http://www.xinhuanet.com/english/2019-06/01/XxjwshE007055_20190601_CBMFN1A006_11n.jpg)

**Comment by NeccoNeko** [comment]
Is Pooh about to smack that kid?

**Comment by Ayx03** [comment]
[Why you shouldn't use Notepad++ (reasons out of politics) | 为什么你不应该用Notepad++（政治之外的原因）](https://zhuanlan.zhihu.com/p/90102369)
There are also many Notepad++ replacements:
[Notepad2](https://notepad2.com/) | [Github Releases](https://github.com/zufuliu/notepad2/releases)
[Notepad3](https://www.rizonesoft.com/downloads/notepad3/) | [Github Releases](https://github.com/rizonesoft/Notepad3/releases)
[Visual Studio Code - Code Editing. Redefined](https://code.visualstudio.com/)
[Sublime Text - Text Editing, Done Right](http://www.sublimetext.com/)
[EmEditor (Text Editor) – Text Editor for Windows supporting large files and Unicode!](https://www.emeditor.com/)
[CP Editor](https://cpeditor.org/)
