### ISSUE TITLE
XLMTools.dll crashed loading a large .xml file

### ISSUE THREAD

**Issue by jonhp** [notepad-plus-plus/notepad-plus-plus#8704]
![2020-08-12](https://user-images.githubusercontent.com/2311501/90076728-17d9b380-dcc6-11ea-9e5b-169b7fd88d0a.png)

### Description of the Issue

XMLTools.dll crashed. see attached screengrab.
### Steps to Reproduce the Issue

1. load a large xml file like 440MB? not sure.
2. 
3. 

### Expected Behavior

well, not that.
### Actual Behavior

The file loaded into np++, but not sure I should trust it.

### Debug Information

Notepad++ v7.8.7   (32-bit)
Build time : Jun  5 2020 - 02:34:28
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS Name : Windows 10 Enterprise (64-bit) 
OS Version : 1909
OS Build : 18363.959
Current ANSI codepage : 1252
Plugins : mimeTools.dll NppConverter.dll NppExport.dll Python Indent.dll SpellChecker.dll XMLTools.dll

**Comment by sasumner** [comment]
XMLTools isn't a plugin distributed with Notepad++, thus it isn't supported here.  Please find wherever it is supported and report your issue there.

**Comment by jonhp** [comment]
wow, that is what i call caring about your user. i have NO idea who wrote it or how to contact them. nor do i care to become a detective. you can find the time to "educate" your users, but not to forward this problem to the author. so important to define your territory and defend it.
