### ISSUE TITLE
Misleading error message when saving a file with illegal characters

### ISSUE THREAD

**Issue by gaelhammer** [notepad-plus-plus/notepad-plus-plus#8707]
### Description of the Issue
When attempting to save a new file with a slash "/" in its name under Windows, I get the error message (loosely translated from German) "File could not be saved. Please check if it is open in another program." The first sentence is obvioulsy correct, but the second is misleading, and I would expect to get a hint on the illegal character.

### Steps to Reproduce the Issue

1. 
2. 
3. 

### Debug Information

Notepad++ v7.8.7   (32-bit)
Build time : Jun  5 2020 - 02:34:28
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : ON
Local Conf mode : OFF
OS Name : Windows 10 Enterprise (64-bit) 
OS Version : 1909
OS Build : 18363.1016
Current ANSI codepage : 1252
Plugins : ComparePlugin.dll HTMLTag_unicode.dll mimeTools.dll NppConverter.dll NppExport.dll

**Comment by sasumner** [comment]
When I attempt to add a `\` into a save path with 7.8.9, I see this error:

![image](https://user-images.githubusercontent.com/30118311/90137254-611c1880-dd43-11ea-8427-2d7b59117e24.png)

Please **_tick_** this checkbox in the _Preferences_ and try your error case again:

![image](https://user-images.githubusercontent.com/30118311/90137524-bf48fb80-dd43-11ea-8c98-98f061e4a5d1.png)

You clearly don't need `Unix style path capacity` so there is little advantage to operating with this checkbox unticked.

>I would expect to get a hint on the illegal character

I could be wrong, but I don't think Windows itself provides any "hints" for this.  Thus, nothing N++ can do for it.

**Comment by sasumner** [comment]
I think the "check if open in another program" is Windows not examining the error too deeply, but just prompting with the most obvious thing that could be wrong (in its opinion).

Closing due to lack of reaction from @gaelhammer after 24 days.
