### ISSUE TITLE
Reload externally changed file then Undo should prompt this menu

### ISSUE THREAD

**Issue by RefinedSoftwareLLC** [notepad-plus-plus/notepad-plus-plus#8709]
### Description of the Issue
Reloading an externally changed file then doing an Undo should prompt to:
Cancel
Undo Anyway
Undo in new tab. (this will have a new filename).

### Steps to Reproduce the Issue
Open a file in Notepad++, Make your 1st edit to the file but forget to Save.
With another program, Make your 2nd edit to the file and Save.
Click on Notepad++ and on the Reload popup click [Yes].
Do the Undo action and notice nothing happens, your 1st edit is lost.

### Expected Behavior
Option to recover your lost 1st edit via a Menu with the above options.

### Debug Information
Notepad++ v6.9
Build time : Feb 21 2016 - 21:27:55
Path : C:\portable\npp.6.9.bin\notepad++.exe
Admin mode : OFF
Local Conf mode : ON
OS : Windows 7
Plugins : ComparePlugin.dll DSpellCheck.dll ElasticTabstops.dll HexEditor.dll MarkdownViewerPlusPlus.dll MathPad.dll NppExport.dll NPPJSONViewer.dll PluginManager.dll zoomdisabler.dll

**Comment by RefinedSoftwareLLC** [comment]
https://github.com/notepad-plus-plus/notepad-plus-plus/issues/5626#issuecomment-499711875

**Comment by sasumner** [comment]
Reloading a file is not an undoable action.
It is not going to be made an undoable action.

**Comment by RefinedSoftwareLLC** [comment]
@sasumner To simplify a solution, would you consider?

Reload

        folder/filename.ext

        This file has been modified by another program.
        Do you want to reload it?

                [Yes] [No] [Compare]

**Comment by sasumner** [comment]
Isn't there already such a prompt?

"Compare" is a functionality relegated to a plugin; it won't be in Notepad++ core.
