### ISSUE TITLE
Stand with your mother!

### ISSUE THREAD

**Issue by Yiyang-Cai** [notepad-plus-plus/notepad-plus-plus#8710]
### Steps to Reproduce the Issue

1. 
2. 
3.

**Comment by wuyizhh** [comment]
agree!
your mother boom boom boom

**Comment by wuyizhh** [comment]
yeah ,developer mother was Boom Boom Boom !

**Comment by cirosantilli** [comment]
https://github.com/cirosantilli/china-dictatorship/tree/c0c41e7c55a7641fd00aad06beefa824e6f5b9c8#tiananmen

![](https://web.archive.org/web/20200421010417im_/https://cdn.theatlantic.com/thumbor/HIH46DVylDqlD1IufGoMFqpr-NQ=/1200x785/media/img/photo/2014/06/tiananmen-square-25-years-ago/t19_05310168/original.jpg)
