### ISSUE TITLE
Why introduce political to this software? Is it a big bussiness?

### ISSUE THREAD

**Issue by chjq68** [notepad-plus-plus/notepad-plus-plus#8711]
I'm so angry and disappointed.

**Comment by arvigeus** [comment]
@chjq68 Search for "Tiananmen Square Massacre" if you really want to get angry and disappointed.

**Comment by cirosantilli** [comment]
https://github.com/cirosantilli/china-dictatorship/tree/c0c41e7c55a7641fd00aad06beefa824e6f5b9c8#meant-to-be-used

**Comment by NeccoNeko** [comment]
> I'm so angry and disappointed.

You're directing your anger in the wrong direction.  You should look inwards, instead.

**Comment by Korb** [comment]
This is a duplicate of #6288 (disrespect for other members of the FOSS community by posting political propaganda spam in text editor resources).
