### ISSUE TITLE
Don't ask for reload when application is being closed

### ISSUE THREAD

**Issue by Somebodyisnobody** [notepad-plus-plus/notepad-plus-plus#8714]
### Description of the Issue

NP++ asks if it should reload the file when there changes have been made on the file externally. This also happens when the user wants to close the application.

### Steps to Reproduce the Issue

1. Disable "Remember current session for next launch" in Settings -> Backup
2. maybe restart?
3. Open two files
4. Edit the file which is not in foreground by an external editor
5. Switch back to NP++ and close the application

### Expected Behavior

NP++ should close without any popups

### Actual Behavior

NP++ asks if the file which was not in foreground and edited externally should be reloaded

### Debug Information
Current NP++ version 64 Bit

**Comment by donho** [comment]
Disable "File Status Auto-detection" in preferences dialog will prevent such problem.

**Comment by Somebodyisnobody** [comment]
But this will disable the check if changes have been made on the file externally completely. I like and want this feature but I fail to see how it helps when the user wants to close np++.
