### ISSUE TITLE
No fucking politic please, you know nothing about the world

### ISSUE THREAD

**Issue by cold-soda-jay** [notepad-plus-plus/notepad-plus-plus#8722]
### Steps to Reproduce the Issue

1. 
2. 
3.

**Comment by cirosantilli** [comment]
https://github.com/cirosantilli/china-dictatorship/tree/c0c41e7c55a7641fd00aad06beefa824e6f5b9c8#meant-to-be-used

https://github.com/cirosantilli/china-dictatorship/tree/c0c41e7c55a7641fd00aad06beefa824e6f5b9c8#not-chinese

**Comment by vadim-ktnkv** [comment]
Please stop mixing software development with politics. 
There are plenty of platforms out there where you can express your political views, collect likes or downvotes, receive all the support or hate you want. 
Injecting political statements into software is completely out of place and only breeds frustration.
