### ISSUE TITLE
Notepad++ freezes and goes into loop at callback focusWndProc() of DockManager

### ISSUE THREAD

**Issue by mahee96** [notepad-plus-plus/notepad-plus-plus#8723]
### Description of the Issue

We are trying to build a notepad++ plugin that uses .NET based docking panel(WinForms) (using Unmanaged Exports)
The problem has been discussed under:
https://github.com/kbilsted/NotepadPlusPlusPluginPack.Net/issues/17
https://community.notepad-plus-plus.org/topic/12519/net-plugin-dockable-dialog-freezes-notepad

I did some initial profiling and can see that the **Gripper::runProc()** on **WM_DESTROY** invokes SetWindowPos() and never returns back.
Also **DialogManager::focusWndProc()** gets invoked infinitely (causing loop) with **lParam->message = WM_GETDLGCODE(0x87)**
Since the focusWinProc() only handles only WM_SETFOCUS and WM_KILLFOCUS, so 0x87 is always ignored and just **consumes CPU 30% constant (HOT).**
I tried to pass _SWP_ASYNCWINDOWPOS_ flag for the SetWindowPos() to do an ASYNC post but the control still didn't return back to WM_DESTROY in Gripper::runProc() (Is the Message Queue processing busy? to acknowledge the post)
I wasn't able to pinpoint the issue, but at least **commenting out/removing SetWindowPos()** in the WM_DESTROY case and rebuilding Notepad++ seems like fixes the issue. 

### Steps to Reproduce the Issue

1. Create a new Plugin-Project in Visual Studio using the .NET plugin template
2. Place a GroupBox (or any other container control) on the “frmMyDlg” form
3. Place a button inside the GroupBox (so the button becomes a child of the groupbox)
4. Compile the plugin
5. In Notepad++, UNDOCK the dialog (dialog must be floating)
6. Click the button
7. Use the mouse to move the dialog window -> Notepad++ freezes

### Expected Behavior

Notepad++ Should not freeze and Plugin should work as expected.

### Actual Behavior

Notepad++ and Floating Dock panel(WinForms) both are frozen(NOT RESPONDING) since MAIN/UI THREAD is busy. 

### Debug Information
Notepad++ v7.8.9   (64-bit)
Build time : Aug 16 2020 - 21:48:08
Path : ..\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS Name : Windows 10 Enterprise (64-bit) 
OS Version : 1909
OS Build : 18363.959
Current ANSI codepage : 1252
Plugins : Test.dll

Some ScreenShots:
![Captur2e](https://user-images.githubusercontent.com/47920326/90339088-2ef10c00-e00c-11ea-8b6a-22c087c0b145.JPG)
![s18'](https://user-images.githubusercontent.com/47920326/90339091-32849300-e00c-11ea-864d-f07413c91b99.JPG)

**Comment by mahee96** [comment]
@donho is there any reason why this could be happening, its a breaking issue when using group containers in .NET WINFORMS world.

**Comment by mahee96** [comment]
Okay found something on this:

https://forums.codeguru.com/showthread.php?412421-endless-messages-WM_GETDLGCODE-when-focus-is-lost

Looks like it's a InterOp issue when using managed .NET group containers inside unmanaged Win32 based window.

**Comment by Fruchtzwerg94** [comment]
For all of you who are still facing the issue. Basically all .NET based plugins are affected of this behaviour. A workaround to fix it which I've implemented into my plugin can be found in [this commit](https://github.com/Fruchtzwerg94/PlantUmlViewer/commit/7a592fbcaffa88e0d7997a38aa7170a051002031).
