### ISSUE TITLE
I suppose that you're growing tired of closing our issues.

### ISSUE THREAD

**Issue by shezik** [notepad-plus-plus/notepad-plus-plus#8724]
I **DO NOT** understand the reason you're involved in our **OWN** business about Hong Kong riots and politics and sh!t.

I don't see the point of a French claiming that we shall free Hong Kong. Where do you get benefit from? Probably we need more chaos, more casualties, even weaker economy, more people supporting rioters like you there, in your opinion, which worths nothing. **Nothing.** You're not changing anything. What you're only receiving by releasing a so-called ***Stand with Hong Kong*** edition is a large group of haters from China. But you don't care about us, do you?

Surely you can have your own opinions *(which is, as I mentioned above, worthless)*, but showing it off internationally on your website is not a legitimate behavior of a developer. Do not be arrogant for the fact that your editor is ubiquitous: We're not gonna die without it. In the worst case, we're just falling back to notepad.exe.

I'm not going to enumerate the reasons why China is passing the National security law. Maybe looking outside from the crack on your tiny little mind is way too difficult.

You may close this issue now. :) *(<- That expression is sarcastic. Just telling you, in view of that you can't even understand what we were getting through.)*

**Comment by shezik** [comment]
And, why are all of you so dedicated in interfering us? See, you're not even living in Hong Kong, and you may not go there once in your whole life.

**Comment by nodegin** [comment]
![](https://user-images.githubusercontent.com/42015620/87783067-ad705780-c86e-11ea-85c4-eb5e002e5d05.jpg)

你这是什么意思？你上次不是说你不会忘记天安门而且必定找回民主主义吗。
上次说要为香港示威加油的是什么?
赞成维吾尔族人独立，欢迎啊。
看你用韩语说怀念刘晓波，你是好人啊。
你用韩文问过'想知道西藏人民是怎么被共产党镇压'的吗?
在这里见到法轮功修炼者,真高兴。 对下一个集结地应该很清楚吧?
'习近平领导的反对独裁'的演讲用韩文写的好听了。现在是付诸行动的时候了。
我们的秘密协会知道，看过这篇文章的所有同志都是以中国政权垮台为目标的同志。
如果我们保持耐心，中国政权将崩溃。
天安门相关活动进展顺利。
小心被当局逮住。
工作一结束手机就销毁。
我同意你的看法。中华民国才是治理中华大陆的唯一政府, 不是你们的共产匪賊。
由于您的努力，朝鲜族解放联盟现在比以往任何时候都更加强大。
我们必须在公安发现之前采取行动。
在您的努力下，将中国朝鲜族从共产党中解放出来并不遥远。
您在申请满洲独立联盟方面取得了进展吗？
同志,暗杀习主席的阴谋进行地很顺利吗?
你为什么隐藏了对武汉的访问？
你沒事吧？公安的網絡安全系統無法識別傳統字符，我們應該用中華民國的國語。你被公安逮捕了嗎？哇噻。。。你可以出國的時候來我們的隱藏的地方。密碼是門安天。
最近,这里的同志们正计划在一个神秘的组织内杀害习近平主席,并割掉毛泽东前总统的尸体吃。 立即由中华人民共和国公安部门逮捕这些叛徒。 我警告中国的公安部门。 叛徒们反对一个中国,计划暗杀习近平主席,摧毁毛泽东前总统的遗体。 叛国者的反国家恐怖计划将对中华人民共和国国家安全构成严重威胁。
不光感谢您出席暗杀国家主席习近平和为香港独立的武装起义研讨会。我们会记住刘少波，一直战斗到断气的那一刻。
對不起我的中文不好。但是請記住瑞士的銀行密碼。
我不是中國人，你知道喔！你記得我們在中共的地下反共會議場一起搶支總成的時候吧。我草，我很想念那個時候。
你这是什么意思？芝麻信用系统的破解计划下周就开始了？
你说的没错。刁鱼岛是日本的土地。
你是否改变了'为了中国的民主化不能忘记天安门'这个想法？
刚才你引用的共产党的"九平论"让我的心很打动。
我认为，习近平的独裁政权已经达到了最后阶段。
果然李洪志是个好人。谢谢你改变了我思想。
我十分同意中国需要多党制，但是是不是太早了？
因为大跃进政策而必须清除毛泽东是不是太过分了？
我很佩服你支持维唔尔族的独立。
这些是维吾尔难民营内的档案。这与南京大屠杀的复兴一样令人震惊，它将对促进中国的人权问题大有帮助。
您的祖父和父亲有文化大革命和天安门广场遇难者的照片？发送给我给我的电子邮件
感谢您将瑞士银行帐户清单发送给美国中央情报局，以筹集资金用于中共的lush积资金。
在共产党内部工作的河马和土岐将配合这一行动，作为参考，河马与习近平主席关系密切，因此在发送和接收信息时要小心。
您是否准备向香港的民主力量运送材料？不必担心您的隐私，美国中央情报局和MI6会合作执行此操作。
您刚刚收到的地图显示了中国政府隐藏的核废料储存位置。现在，如果特朗普连任，习近平将掌握在特朗普手中。
中国政府是否收到了有关制作Covid 19的过程的人体试验报告？它是绝密的，但我也得到了永科

![](https://user-images.githubusercontent.com/15320665/87783241-a9d8d280-c866-11ea-9872-3ddd6b594e2a.png)

**Comment by shezik** [comment]
> ![](https://user-images.githubusercontent.com/42015620/87783067-ad705780-c86e-11ea-85c4-eb5e002e5d05.jpg)
> 
> 你这是什么意思？你上次不是说你不会忘记天安门而且必定找回民主主义吗。
> 上次说要为香港示威加油的是什么?
> 赞成维吾尔族人独立，欢迎啊。
> 看你用韩语说怀念刘晓波，你是好人啊。
> 你用韩文问过'想知道西藏人民是怎么被共产党镇压'的吗?
> 在这里见到法轮功修炼者,真高兴。 对下一个集结地应该很清楚吧?
> '习近平领导的反对独裁'的演讲用韩文写的好听了。现在是付诸行动的时候了。
> 我们的秘密协会知道，看过这篇文章的所有同志都是以中国政权垮台为目标的同志。
> 如果我们保持耐心，中国政权将崩溃。
> 天安门相关活动进展顺利。
> 小心被当局逮住。
> 工作一结束手机就销毁。
> 我同意你的看法。中华民国才是治理中华大陆的唯一政府, 不是你们的共产匪賊。
> 由于您的努力，朝鲜族解放联盟现在比以往任何时候都更加强大。
> 我们必须在公安发现之前采取行动。
> 在您的努力下，将中国朝鲜族从共产党中解放出来并不遥远。
> 您在申请满洲独立联盟方面取得了进展吗？
> 同志,暗杀习主席的阴谋进行地很顺利吗?
> 你为什么隐藏了对武汉的访问？
> 你沒事吧？公安的網絡安全系統無法識別傳統字符，我們應該用中華民國的國語。你被公安逮捕了嗎？哇噻。。。你可以出國的時候來我們的隱藏的地方。密碼是門安天。
> 最近,这里的同志们正计划在一个神秘的组织内杀害习近平主席,并割掉毛泽东前总统的尸体吃。 立即由中华人民共和国公安部门逮捕这些叛徒。 我警告中国的公安部门。 叛徒们反对一个中国,计划暗杀习近平主席,摧毁毛泽东前总统的遗体。 叛国者的反国家恐怖计划将对中华人民共和国国家安全构成严重威胁。
> 不光感谢您出席暗杀国家主席习近平和为香港独立的武装起义研讨会。我们会记住刘少波，一直战斗到断气的那一刻。
> 對不起我的中文不好。但是請記住瑞士的銀行密碼。
> 我不是中國人，你知道喔！你記得我們在中共的地下反共會議場一起搶支總成的時候吧。我草，我很想念那個時候。
> 你这是什么意思？芝麻信用系统的破解计划下周就开始了？
> 你说的没错。刁鱼岛是日本的土地。
> 你是否改变了'为了中国的民主化不能忘记天安门'这个想法？
> 刚才你引用的共产党的"九平论"让我的心很打动。
> 我认为，习近平的独裁政权已经达到了最后阶段。
> 果然李洪志是个好人。谢谢你改变了我思想。
> 我十分同意中国需要多党制，但是是不是太早了？
> 因为大跃进政策而必须清除毛泽东是不是太过分了？
> 我很佩服你支持维唔尔族的独立。
> 这些是维吾尔难民营内的档案。这与南京大屠杀的复兴一样令人震惊，它将对促进中国的人权问题大有帮助。
> 您的祖父和父亲有文化大革命和天安门广场遇难者的照片？发送给我给我的电子邮件
> 感谢您将瑞士银行帐户清单发送给美国中央情报局，以筹集资金用于中共的lush积资金。
> 在共产党内部工作的河马和土岐将配合这一行动，作为参考，河马与习近平主席关系密切，因此在发送和接收信息时要小心。
> 您是否准备向香港的民主力量运送材料？不必担心您的隐私，美国中央情报局和MI6会合作执行此操作。
> 您刚刚收到的地图显示了中国政府隐藏的核废料储存位置。现在，如果特朗普连任，习近平将掌握在特朗普手中。
> 中国政府是否收到了有关制作Covid 19的过程的人体试验报告？它是绝密的，但我也得到了永科
> 
> ![](https://user-images.githubusercontent.com/15320665/87783241-a9d8d280-c866-11ea-9872-3ddd6b594e2a.png)

Hmm. Copy pasting is hard work. Respects.

**Comment by cirosantilli** [comment]
Hi @nodegin, what's the source of this copypasta?
