### ISSUE TITLE
Free Hongkong？

### ISSUE THREAD

**Issue by ecareyu** [notepad-plus-plus/notepad-plus-plus#8726]
What you call freedom is that people can ignore the law, beat and abuse them at will, or even throw gasoline like opponents? Is this a bit deformed? Are you sure this is the freedom you want? Free Hongkong seems to be a joke here.

**Comment by shmutalov** [comment]
I ask to developer to keep the politics far from development, to keep the safe space. I know, everybody have an opinion, and, of course can spread it through their own work, like an artist drawing their pictures etc. But some steps wordly "hurts" the innocent NPP (and other soft) users. I wish the author will understand me. I am the lover of the Notepad++. But I don't want to see that GOVs blocks my everyday tools. Thank you!

**Comment by Atulin** [comment]
> But I don't want to see that any government blocks my everyday tools.

Then I'd say your anger is misdirected.
