### ISSUE TITLE
This is a disgusting open source project that's involving politics

### ISSUE THREAD

**Issue by shook2012** [notepad-plus-plus/notepad-plus-plus#8727]

**Comment by cirosantilli** [comment]
https://github.com/cirosantilli/china-dictatorship/tree/c0c41e7c55a7641fd00aad06beefa824e6f5b9c8#meant-to-be-used

**Comment by Korb** [comment]
This is a duplicate of #6288 (disrespect for other members of the FOSS community by posting political propaganda spam in text editor resources).
