### ISSUE TITLE
Autosave modified documents when Notepad++ window loses focus

### ISSUE THREAD

**Issue by cosuwi** [notepad-plus-plus/notepad-plus-plus#8729]
Please add this feature to Notepad++. _Autosave_ plugin does this, but it switches all tabs, which takes much time on minimizing and restoring Notepad++ window.

**Comment by sasumner** [comment]
Duplicate of #8728.
Please don't duplicate issues.
Add any further comments you have to existing issues.

**Comment by cosuwi** [comment]
@sasumner May the issue #8728 be reopened?

**Comment by cosuwi** [comment]
@donho Please reply.
