### ISSUE TITLE
NPP RTL: Dragged & Dropped file opens in wrong view

### ISSUE THREAD

**Issue by Yaron10** [notepad-plus-plus/notepad-plus-plus#8730]
**STR:**
`Settings -> Preferences -> General -> Localization`: select a RTL language (e.g. Hebrew).
Restart NPP.
Open files `A` and `B`.
Move `A` to other view.
Drag & Drop a file into the current view in NPP.

**Result:**
The file is opened in the *other view*.
***
Notepad++ v7.8.9   (32-bit)
Build time : Jul 15 2020 - 20:26:50
Path : C:\---\Downloads\npp.7.8.9.bin\notepad++.exe
Admin mode : ON
Local Conf mode : ON
OS Name : Windows 7 Enterprise (32-bit) 
OS Build : 7601.23964
Current ANSI codepage : 1255
Plugins : mimeTools.dll NppConverter.dll NppExport.dll

**Comment by sasumner** [comment]
@Yaron10 
Maybe a dumb question from an English-speaking native, but which entry on the `Localization` menu is Hebrew?  I _think_ I know, but I don't want to polute this comment with a wrong guess, so I'll kindly ask you to tell/show me.

**Comment by Yaron10** [comment]
Not dumb at all.
Perhaps all languages should include their names in English too.
For example: `Italiano (Italian)`.


![תמונה](https://user-images.githubusercontent.com/10229320/90565851-33562a00-e1b0-11ea-8ef6-1d3b9ada9bce.png)

**If you add `RTL="yes"` to `english.xml` and restart NPP, you'll have a RTL NPP in English.**
`<Native-Langue name="English" RTL="yes" filename="english.xml" version="7.8.7">`

***
```
void Notepad_plus::dropFiles(HDROP hdrop)
{
	if (hdrop)
	{
		// Determinate in which view the file(s) is (are) dropped
		POINT p;
		::DragQueryPoint(hdrop, &p);
		HWND hWin = ::RealChildWindowFromPoint(_pPublicInterface->getHSelf(), p);
		if (!hWin) return;

		if ((_subEditView.getHSelf() == hWin) || (_subDocTab.getHSelf() == hWin))
			switchEditViewTo(SUB_VIEW);
		else
			switchEditViewTo(MAIN_VIEW);
```

It seems that `p.x` is wrong in RTL.
***
Related: https://github.com/notepad-plus-plus/notepad-plus-plus/issues/8520.

```
		case TTN_GETDISPINFO:
		{
			try
			{
				LPTOOLTIPTEXT lpttt = (LPTOOLTIPTEXT)notification;

				//Joce's fix
				lpttt->hinst = NULL;

				POINT p;
				::GetCursorPos(&p);
				::ScreenToClient(_pPublicInterface->getHSelf(), &p);
				HWND hWin = ::RealChildWindowFromPoint(_pPublicInterface->getHSelf(), p);
```
In `NppNotification.cpp`.

I can use later

```
				else if (hWin == _mainDocTab.getHSelf())
				{
					BufferID idd = bothActive() ? _subDocTab.getBufferByIndex(id) : _mainDocTab.getBufferByIndex(id);
```
and
```
				else if (hWin == _subDocTab.getHSelf())
				{
					BufferID idd = bothActive() ? _mainDocTab.getBufferByIndex(id) : _subDocTab.getBufferByIndex(id);
```

but, obviously, that's tricky and not ideal.
