### ISSUE TITLE
Double-click filename from Windows Explorer with spaces in path causes errors

### ISSUE THREAD

**Issue by appyface** [notepad-plus-plus/notepad-plus-plus#8731]
### Description of the Issue
(I searched for existing open or closed issue but missed finding, but it must be there? Apologies if this is a duplicate and please close it if so. Thank you.)

From Windows Explorer in Windows 10 1909, double-clicking a filename (with an extension that is associated with Notepad++) that has a path with spaces, causes Notepad++ to display error pop-ups and then fail to locate and load the file.

This happens for both 32 and 64 bit Notepad++.  It happens whether Notepad++ is already open, or not.
Notepad++ version 7.8.9, though happened with earlier versions.

### Steps to Reproduce the Issue
1.  I have filepath of C:\Temp\xml_from_P01 part 2\test.txt
2.  .txt is an extension that is registered with Notepad++, and it will launch when any file with .txt extension is double-clicked
3.  I double click file in #1 from Windows Explorer
4. Attached pop-ups occur and then file fails to load.

### Expected Behavior
No error pop-ups and file opens as usual.

### Actual Behavior
Error pop-ups and file did not open

### Debug Information
For 32-bit:
Notepad++ v7.8.9   (32-bit)
Build time : Jul 15 2020 - 20:26:50
Path : C:\program_files_NOINST\npp_x86\notepad++.exe
Admin mode : OFF
Local Conf mode : ON
OS Name : Windows 10 Enterprise (64-bit) 
OS Version : 1909
OS Build : 18363.959
Current ANSI codepage : 1252
Plugins : ComparePlugin.dll ElasticTabstops.dll HexEditor.dll mimeTools.dll NppConverter.dll NppExport.dll NppTextFX.dll 

For 64-bit:
Notepad++ v7.8.9   (64-bit)
Build time : Jul 15 2020 - 20:31:49
Path : C:\program_files_NOINST\npp_x64\notepad++.exe
Admin mode : OFF
Local Conf mode : ON
OS Name : Windows 10 Enterprise (64-bit) 
OS Version : 1909
OS Build : 18363.959
Current ANSI codepage : 1252
Plugins : CodeAlignmentNpp.dll ComparePlugin.dll CsvQuery.dll ElasticTabstops.dll HTMLTag.dll mimeTools.dll NppConverter.dll NppExport.dll XMLTools.dll 

Answered "no" to this first pop-up:
![image](https://user-images.githubusercontent.com/7108153/90459008-d0cc3380-e0b4-11ea-98c5-ddb391e3d6ff.png)
Answered "no" to this second pop-up
![image](https://user-images.githubusercontent.com/7108153/90459050-f0fbf280-e0b4-11ea-8117-4ca9877e0890.png)
Answered "ok" to this final pop-up
![image](https://user-images.githubusercontent.com/7108153/90459055-f6593d00-e0b4-11ea-959f-6d05a3c4c2b3.png)
File did not load

**Comment by jofon** [comment]
This has been reported multiple times (and related bugs have been fixed) and the proposed fixes should work for you:
https://github.com/notepad-plus-plus/notepad-plus-plus/issues/4981#issuecomment-483455692
https://community.notepad-plus-plus.org/topic/16687/build-7-6-open-with-association-does-not-open-files-with-spaces-in-filenames/5
https://npp-user-manual.org/docs/other-resources/

Maybe you've had the wrong command for a while now, since you mention this happened with earlier versions. Besides trying the above fixes, you can also try to associate the file type with notepad.exe, and then again with notepad++. This _might_ be a quick way to set the correct command.

Note: I could only reproduce the issue with v7.8.9 by using the wrong command on purpose (from the command line).

**Comment by appyface** [comment]
I will try to reassociate Notepad then Notepad++ again with .txt files and advise results.  Thank you for your suggestion.  Kind regards.

**Comment by appyface** [comment]
After reading #4981 I found two registry entries without "%1" in double quotes, and of course adding the quotes that fixed the issue.

I don't know what created the entries without the double quotes.  If it ever happens again I'll try to find out.

Thank you for pointing me in the right direction.  I don't know why I missed finding all the other reports.  So glad for your help on it.  
Kind regards.

**Comment by appyface** [comment]
Thanks, resolved.
