### ISSUE TITLE
 CTRL+M [Problematic hot key]

### ISSUE THREAD

**Issue by mrprunen** [notepad-plus-plus/notepad-plus-plus#8735]
From version 7.8.7 CTRL + M was used for the "mark" function.
This is a problem when using scanner readers that have a 0D (hex) or OD+0A string terminator.
Reading a barcode opens the "mark" window and shouldn't happen.

**Comment by sasumner** [comment]
Unmap default ctrl+m assignment in _Shortcut Mapper_

**Comment by mrprunen** [comment]
@sasumner thank you!!
