### ISSUE TITLE
It's dangerous to play political games!

### ISSUE THREAD

**Issue by gaojicainiao** [notepad-plus-plus/notepad-plus-plus#8736]
I am a Chinese user.
It seems that notepad++ hates China deeply, and eager to split China into pieces...
I am very sad about it.
I want to tell notepad++: Come to China then you can learn what the real China is. Know China clearly, please.

Thouth you think China is evil, has much dark history. But the same, I can tell you how bad your country is, with many facts, whatever which country you are from.

We built our country in battle, and keep our country and people in peace. You want to split us? That is just you want us to fall into civil war!
Fight for freedom? We prefer peace! We value people's lives first! Freedom second!
We limit people's freedom, to protect their freedom! For example, our people are not allowed to have guns or drug. We have 0 tolerance about guns and drug. By these way, we are living in a safe environment. We can walking alone outside at night without worring bad people.

**Comment by SkywalkerYuu** [comment]
查查wiki，劣迹斑斑

**Comment by gaojicainiao** [comment]
> 查查wiki，劣迹斑斑

这些我都看过！
但我仍然谴责notepad++的行为。

呃……你是哪国人？你更相信中国网内的知识信息还是外国网上的知识信息？

**Comment by ShileiMao** [comment]
> I am a Chinese user.
> It seems that notepad++ hates China deeply, and eager to split China into pieces...
> I am very sad about it.
> I want to tell notepad++: Come to China then you can learn what the real China is. Know China clearly, please.
> 
> Thouth you think China is evil, has much dark history. But the same, I can tell you how bad your country is, with many facts, whatever which country you are from.
> 
> We built our country in battle, and keep our country and people in peace. You want to split us? That is just you want us to fall into civil war!
> Fight for freedom? We prefer peace! We value people's lives first! Freedom second!
> We limit people's freedom, to protect their freedom! For example, our people are not allowed to have guns or drug. We have 0 tolerance about guns and drug. By these way, we are living in a safe environment. We can walking alone outside at night without worring bad people.

赞同，我极度反感那些以”人权“和”自由“为名拿别人生命作为棋子的可耻行为，那些人在乎的并不是所谓的”人权“，他们只想要看到他们不喜欢的东西消失，或者让他们不喜欢的人民生活在黑暗中，仅此而已。我看过那些在西方政权洗脑下的”自由革命“的国度，如今变成了什么样的人间地狱，那些装聋作哑当做什么都没有发生的人，我知道我不能改变你们的看法，我只有诅咒你们死后全部下地狱去。

**Comment by David-Tsui** [comment]
@ShileiMao 我看过那些在西方政权洗脑下的”自由革命“的国度 => 是你看過? 還是你們牆國餵給你的資訊?
不愧是籠的傳人，活在平行時空盡情自慰

**Comment by lindasczx** [comment]
别用这作者的软件就行了。替代品不要太多。

**Comment by Korb** [comment]
This is a duplicate of #6288 (disrespect for other members of the FOSS community by posting political propaganda spam in text editor resources).
