### ISSUE TITLE
[Feature request] Pin frequently accessed files in File menu recent files list

### ISSUE THREAD

**Issue by BarryTice** [notepad-plus-plus/notepad-plus-plus#8737]
This is a feature request, not a defect.

There are several reference files that I find I often need to access from Notepad++ on my computer. However if I have been using many other files recently, the reference files will age out of the recent files list in my File menu.

It would be helpful to me (and presumably to others) if I were able to select one of the entries in my recent files list and "pin" it to the top of the list so that it does not expire from the list as other files pass through it.

Thank you!

**Comment by sasumner** [comment]
The _Explorer_ plugin has a _Favorites_ feature that is often used to achieve this type of thing.

**Comment by BarryTice** [comment]
This is a nice consolation prize for me, sasumner. Thank you!

The Explorer plugin is far better than what I had, but I would still like to see pinned files, if it were possible.

**Comment by sasumner** [comment]
A lot of things are possible, but the limited development staff likes to concentrate on things that existing plugins aren't already covering. :-)

There are already several issues requesting "pinned" tabs (search the issues for `pinned`), so I'm going to close this one due to the feeling that we don't need another open one hanging around.

**Comment by jagganath69** [comment]
I also have need of maintaining a set of PINNED FILES that I can **open/close** conveniently. RECENT FILES LIST is a logical place to put this (via RIGHT-CLICK toggle)
I use SESSIONS extensively too, so this is a boon if ever becoming a reality.
