### ISSUE TITLE
Performance issue with typing in a block (alt+mouse drag)

### ISSUE THREAD

**Issue by jos-smit** [notepad-plus-plus/notepad-plus-plus#8746]
### Description of the Issue

When I select a block of text (or just a verical line) using alt+mouse drag. Then type text. This used to work fast but lately (last months or so) it has become slow. On big files it is slower.

### Steps to Reproduce the Issue

1. Open a dot-sql file of 90kB, 2224 lines, language SQL is automaticaly chosen
2. Select a block of text using alt+mouse drag, in this case I selected a square of 0 chars wide and 17 lines high
2. Type two dashes and a space
3. You can observe the characters appear after two seconds

### Expected Behavior

It used to be fast, just like regular typing of text.

### Actual Behavior

Lag.

### Debug Information

Notepad++ v7.8.7   (32-bit)
Build time : Jun  5 2020 - 02:34:28
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS Name : Windows 10 Enterprise (64-bit) 
OS Version : 1809
OS Build : 17763.253
Current ANSI codepage : 1252
Plugins : JSMinNPP.dll mimeTools.dll NppConverter.dll NppExport.dll XMLTools.dll 

Screenshot vertical line of 17 lines is selected
![afbeelding](https://user-images.githubusercontent.com/19187186/90859776-1d4f9180-e389-11ea-8454-0bd7adedd792.png)

Two dashes and a space are typed, it takes roughly two seconds for teh characters to appear
![afbeelding](https://user-images.githubusercontent.com/19187186/90859850-42dc9b00-e389-11ea-97e8-297cda896070.png)

**Comment by sasumner** [comment]
Provide the requested "Debug information".  Read the instructions on how to do so instead of ignoring them.

Specify how many lines you are trying to cover with the "vertical line" when you are doing this.
Also specify the file type/extension and the size of the file (number of lines in file; total size of the file)
