### ISSUE TITLE
[Feature Request] List all tabs button

### ISSUE THREAD

**Issue by GitClickOk** [notepad-plus-plus/notepad-plus-plus#8748]
### Description of the Issue
When with a lot of tabs opened can be hard select the correct tab. One nice addition will be a "List all tabs" button like in Firefox, and we can select a tab as a menu.

### Expected Behavior
![Capture 1827](https://user-images.githubusercontent.com/19438005/90810660-b636cc00-e2f9-11ea-8d5b-ec79f26bdfd4.png)

**Comment by sasumner** [comment]
From the _Window_ menu, choose _Windows..._ to get a very similar list.
