### ISSUE TITLE
(bug) Encoding change from UTF-8 to TIS-620 when saving and closing (2)

### ISSUE THREAD

**Issue by bbauer87** [notepad-plus-plus/notepad-plus-plus#8755]
### Description of the Issue
This bug is similar to the following issue:
https://github.com/notepad-plus-plus/notepad-plus-plus/issues/3588

I have a text file in UTF-8 containing lots of text and the portuguese word "dá". When the file is closed and opened again, the program change the encoding of the file to TIS-640, buggin the word to "dรก-".

Just want to give this feedback, since uncheking "Autodetect character encoding" solves the problem.

### Steps to Reproduce the Issue
1. Create a simple text file with UTF-8 encoding and the word "dá";
2. Save and close;
3. Reopen the file.

### Expected Behavior
That the file would still have UTF-8 encoding and the word as was written.

### Actual Behavior
The program changes the file encoding and bugs the word to "dรก-".

### Debug Information
Notepad++ v7.8.5   (32-bit)
Build time : Mar  4 2020 - 11:04:20
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS Name : Windows 7 Professional (32-bit) 
OS Build : 7601.0
Plugins : mimeTools.dll NppConverter.dll NppExport.dll

**Comment by Ekopalypse** [comment]
Well I guess this is the price to pay when using "autodetect encoding" feature.
It can only predict that the current encoding is X but it never knows for sure.

**Comment by Fly33** [comment]
But why I can't switch back to UTF-8 at least manually? It just remains as TIS-640. This issue almost forced me to use different editor.  But I found out that including BOM solved the issue.

**Comment by hyoretsu** [comment]
@Ekopalypse yes, but why not only leave a feature that's broken in the app, but also make it on by default?

**Comment by Ekopalypse** [comment]
@hyoretsu 
I don't think you can say that the feature doesn't work. It works most of the time, unfortunately not always and from my point of view it never can. This is, probably, also the reason why it is on by default.

**Comment by hyoretsu** [comment]
@Ekopalypse never said it didn't, just that it's broken. Which it is, since it doesn't work 100% of the time. And that's usually not something you send into a release, let alone leave it as default. I only found out a solution by chance, otherwise it'd be a bug I wouldn't know how to solve. And it's be Notepad++'s fault.

If a feature isn't 100% stable and may cause some failures, that's the type of thing you leave tucked away in settings as optional. Or in Beta. Not in a release, as a default.

**Comment by Ekopalypse** [comment]
@hyoretsu - the function itself is not broken, it works within its limits. It will NEVER be able to determine the correct coding 100% of the time and one must be aware of that. Whether or not this justifies that this function should not be on by default will probably remain a contentious issue, as some probably see the advantage and others the disadvantage.

**Comment by hyoretsu** [comment]
> It will NEVER be able to determine the correct coding 100% of the time and one must be aware of that.

Exactly. If, and only if, I want to take on that risk, I should be the one to activate that. Not Notepad++, making clueless users who maybe wouldn't scroll down to the bottom of an Issue on GitHub wonder what's broken with their notes app.

If it is prone to failures, it should be optional. If it isn't optional, it should work 100% of the time, as is expected from a stable release.

**Comment by Ekopalypse** [comment]
I see your point, but what do you say to someone who has been using this feature for years without a problem when it is suddenly disabled in the next release? There are always (ok, mostly) two sides.

**Comment by hyoretsu** [comment]
@Ekopalypse Yes, what is exactly me. I didn't even know it existed and I've been using Notepad++ for a few years now. But then my files were suddenly thrown into a bug pandemonium, with me having to manually fix them only to find out they were broken again after saving.

I don't even know what it's meant to do, and I have seen 0 changes so far. Besides, what kind of characters couldn't possibly fit in UTF-8 anyway, which is a standard? Even the 2k+ Japanese kanji are in it.

**Comment by Ekopalypse** [comment]
There are still those who refuse to use utf8 encoded files and prefer to create files in their 7/8-bit encoding.

**Comment by hyoretsu** [comment]
Which should be the exception, not the norm, with a solution that's prone to breaking.

Simply: use UTF-8 by default and don't change the encoding of a file open in Notepad++, unless checked on Settings to enforce UTF-8 encoding.

That way it doesn't break files every now and then with a feature that isn't perfected, which isn't a matter of it being rare rare, instead that it shouldn't happen on a release; nor messes up people who want to use other encodings.

**Comment by hyoretsu** [comment]
Never created a C++ project to know if it's doable/easy, but the fact still stands that this feature breaks files at times, which isn't something suitable for a release/default settings.

**Comment by infacto** [comment]
Can this be fixed when there is a priority order? I mean UTF-8 > TIS-620. I'm pretty sure that UTF-8 is more used as TIS-620.
The detection should be extended. UTF-8 is more likely than the other. The TIS-620 detection should check more to be more sure.

Just for interests: How does a TIS-620 file look like? I found that entry in menu "Encoding" > "Character sets" > "Thai". So I guess it's for thai characters only? Which can definitely also be displayed with UTF-8. I just want to say that TIS-620 is very rare today. Just a guessing but UTF-8 (without BOM) is standard today.

**Comment by hyoretsu** [comment]
UTF-8 is definitely the standard and infinitely more used nowadays. Don't see why saving the pain of very very few people would be worth creating hassles for tons more that are using UTF-8 by default.
