### ISSUE TITLE
Uni-tests for function-list

### ISSUE THREAD

**Issue by donho** [notepad-plus-plus/notepad-plus-plus#8757]
As mentioned in https://github.com/notepad-plus-plus/notepad-plus-plus/pull/3393, We need the uni-tests for function-list so users can enhance `functionList.xml` without regression.
 
Currently Notepad++ is capable to get input source file and output a result in JSON format:
Command:
```
notepad++.exe -export=functionList -lcpp c:\funcListTests\cppTest.cpp
```
the behaviour:

> Notepad++ will open "c:\funcListTests\cppTest.cpp" as C++ source file, and write result to `c:\funcListTests\cppTest.result.json` - the old `cppTest.result.json` will be erased by the new one.

All we need is have all input files in `A` folder and generate expected results in `B` folder, then in build system (AppVeyor) to integrate the ability to evoke notepad++ (in each build) to take files from A folder, and generate test files into A folder - this system should compare result files between `A` & `B` folder.

Any help for providing **input files** and for **AppVeyor** is welcome.

**Comment by GitMensch** [comment]
Nice one, so everything s setup to add new unit tests now.
The only thing is that there's so far only the possibility for one unitTest per language; is this the way to go (so always add to the existing unit test if it exists for the language) or should there be a wildcard (so generating `$testRoot$__\unitTest*` and later comparing it with the appropriate expected result)?

Just asking to be able to come up with a README for those unit tests later...

**Comment by donho** [comment]
@GitMensch Currently there's only way to run unit-tests - run them all. We can do however a generic script aside for running the test by passing directory name as argument. You can create a feature request in issue tracker if you think it's useful.

**Comment by GitMensch** [comment]
I see and that is good to remember. My question was: should it be possible to have more than one unittest for one language identifier?

**Comment by donho** [comment]
@GitMensch  2 or more unittests for one language? Currently no, and I don't see why we will need it in the future.
