### ISSUE TITLE
Shift+F3 ignored for regex

### ISSUE THREAD

**Issue by bxle** [notepad-plus-plus/notepad-plus-plus#8759]
### Description of the Issue
After using ctl+F to specify a regex find and closing the find pop-up, F3 searches forward correctly but shift+F3 does nothing.  I looked in the shortcut mapper and verified that shift+F3 was defined as search backwards.  It worked until the last few weeks.  I was probably on an earlier release of Notepad++ then.

Same failure when I redefine Find Previous as Alt+Shift+F3.

### Steps to Reproduce the Issue
1. Use ctl+F to define a regex search.
2. Close the search definition pop-up window.
3. Back in the regular file, press shift+F3.  Nothing happens.

### Expected Behavior
Expected either a search to occur or a message saying the search failed.

### Actual Behavior
Nothing.  No messages, signals, cursor movement.  Everything is unchanged.  Same failure after rebooting the OS and starting Notepad++.

### Debug Information
Notepad++ v7.8.9   (32-bit)
Build time : Jul 15 2020 - 20:26:50
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS Name : Windows 10 Enterprise (64-bit) 
OS Version : 1903
OS Build : 18362.418
Current ANSI codepage : 1252
Plugins : DSpellCheck.dll mimeTools.dll NppConverter.dll NppExport.dll

**Comment by sasumner** [comment]
Design change in Notepad++.
Backward regex search would sometimes give unexpected (to the user) results.
There's a hack to reinstate it somewhat.
Have a look in the documentation; look for `regexBackward4PowerUser`

**Comment by orgads** [comment]
At least show a popup message? Notice how many issues were reported on this!
