### ISSUE TITLE
please disAble autoUpdate while start notepad++

### ISSUE THREAD

**Issue by limaofu** [notepad-plus-plus/notepad-plus-plus#8763]
I have disable the auto detect update notpad++, but it pops a "an update xx is avaliablexxx" dialog.
could you disable this update func in certainly?
![closeUpdate](https://user-images.githubusercontent.com/54393027/91119429-b7834280-e6c5-11ea-8826-470ef6a2dc0b.png)

**Comment by limaofu** [comment]
Do not study from Microsoft

**Comment by limaofu** [comment]
please

**Comment by donho** [comment]
Obviously you've got a quite old version of Notepad++. The `GUP.exe` comes with the recent Notepad++ has 3 buttons: "Yes", "No" and "Never". 
You can just remove `GUP.exe` from the directory `updater` (where your Notepad++ installed) to stop being nagged.
