### ISSUE TITLE
Projet panels states are not saved though sessions

### ISSUE THREAD

**Issue by donho** [notepad-plus-plus/notepad-plus-plus#8767]
### Description of the Issue
While one of (or all) project panel(s) is (are) opened, if I close it (them), it (they) will be back in the next Notepad++ launch.

### Steps to Reproduce the Issue
1. Launch Notepad++, launch all project panels
2. Exit Notepad++ then relaunch it, make sure all panels are there.
3. Close panels one by one.
4. Relaunch Notepad++

### Expected Behavior
No project panels opened.

### Actual Behavior
3 project panels opened.

### Debug Information
It's only in master, so it's kind of regression

**Comment by donho** [comment]
@Uhf7 
Could you check this regression please?

**Comment by Uhf7** [comment]
I cannot reproduce it on my system with the current master 34357a46cf8f5a0a7e2897079355eeb1055ca9fb, but I have a strange guess what could have happened.

In the early versions of PR #8720, the Project Panels stored the wrong internal function id to the _config.xml_.  After testing this this version, you may have a 'polluted' _config.xml_.

So please check the `<GUIConfig name="DockingManager"/>` section of your _config.xml_. The Project Panels should have the id's 44081, 44082 and 44083. If the _config.xml_ contains the id's 44104, 44105 or 44106, then they come from an early version of PR #8720. After removing this id's manually from the _config.xml_, they should never be written again and the Project Panels should stay closed.

**Comment by donho** [comment]
@Uhf7 By removing 44104, 44105 or 44106, the problem is solved. Thank you.
