### ISSUE TITLE
Plug-in manager shuts down notepad, Document Spell Check-Gone, No Macro Save.

### ISSUE THREAD

**Issue by theoldman01** [notepad-plus-plus/notepad-plus-plus#877]
Hi.
New version 6.8.3 Bugs.
Plug-in Manager forces NotePad++ to completely exit to Windows System.
It does it while loading current plug-ins and if you try to find updates.

What happened to the great Spell Checker?
I can not find the 'Spell Check' on document, or while you type etc.
The great version that was with it has gone? If its still there I can Not find it.

The Macro Save works only if NotePad++ is being used. If I exit it, and then
re-load, the Macro has gone. Not saved on system. I have to re-do it all over
again.

All the best.

**Comment by dail8859** [comment]
As of Notepad++ v7.5 the Plugin Manager is no long being shipped with Notepad++. See https://notepad-plus-plus.org/news/notepad-7.5-released.html

All Plugin Manager related issues should be reported to https://github.com/bruderstein/nppPluginManager/issues
