### ISSUE TITLE
In fact, China is getting stronger.

### ISSUE THREAD

**Issue by YellowDoing** [notepad-plus-plus/notepad-plus-plus#8770]
You speak Chinese，

you write Chinese，

you have a China Face,

but you do not admit that you are a Chinese.

It's ridiculous.

You are bad and full of jealousy.

**Comment by David-Tsui** [comment]
@YellowDoing YellowShit

**Comment by cumbas12** [comment]
I agree, Yellow Dong. Your words are wise and yellow.
