### ISSUE TITLE
Feature request: Session as file type, associated with Notepad++

### ISSUE THREAD

**Issue by BacchusPS** [notepad-plus-plus/notepad-plus-plus#8773]
It would be nice if the session files had an extension that was then associated with notepad++.

The idea being that you could then right click on a session file and choose open to open the session. Thus providing a way to startup an instance of Notepad++ with all the files I want to work on (at least to begin with), such as a specific project. As opposed to having to start notepad+ first, and then open the session.

**Comment by dail8859** [comment]
This feature is already available. 

1. Open `Setting` > `Preferences` > `MISC.`
1. Set a session file extension.
1. `File` > `Save Session` and give it an appropriate name/location.
1. Close Notepad++
1. Open the new session file (e.g. right click, or better yet register that extension as a Notepad++ file)
1. Notepad++ will reload that session.

---

I use `nps` as the file extension.

![image](https://user-images.githubusercontent.com/3694843/91877615-3b9c7380-ec4c-11ea-89de-8458f7b712ba.png)
