### ISSUE TITLE
[regression]Pasting multi-line text in Find and Replace 

### ISSUE THREAD

**Issue by ooghry** [notepad-plus-plus/notepad-plus-plus#8784]
Previously we can paste multi-line/tabbed text in both Find and Replace field but after update to latest version I can't do that, actually only first line paste in fields.
I can't remember what is my previous version.

Notepad++ v7.8.9   (64-bit)
Build time : Jul 15 2020 - 20:31:49
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS Name : Windows 10 Pro (64-bit) 
OS Version : 1909
OS Build : 18363.1016
Current ANSI codepage : 1252
Plugins : mimeTools.dll NppConverter.dll NppExport.dll

**Comment by sasumner** [comment]
There has never been multiline data _paste_ into _Find what_ or _Replace with_ boxes.

What was (and still is) possible is to select multiline text and then invoke the _Find_ dialog with Ctrl+f, and have the multiline selection be conveyed to the _Find what_ box.
