### ISSUE TITLE
Function List: set default order to "Sorted by Name"

### ISSUE THREAD

**Issue by Yaron10** [notepad-plus-plus/notepad-plus-plus#8787]
**STR:**
Open a C++ file.
Open the `Function List` panel.

**Result:**
The functions are listed in the order of their appearance in the file.

**Expected:**
Displaying the functions "Sorted by Name" should be more convenient in most cases.
(MS VS and other editors list the functions "Sorted by Name").

**Suggested:**
In `functionListPanel.cpp`:

Replace
```
		if (!previousParams)
		{
			::SendMessage(_hSearchEdit, WM_SETTEXT, 0, reinterpret_cast<LPARAM>(TEXT("")));
			setSort(false);
			_treeView.expand(root);
		}
```
with
```
		if (!previousParams)
		{
			::SendMessage(_hSearchEdit, WM_SETTEXT, 0, reinterpret_cast<LPARAM>(TEXT("")));
			setSort(true);
			_pTreeView->sort(_pTreeView->getRoot(), true);
			_treeView.expand(root);
		}
```

**It only changes the *default order*. The user can still toggle `Sort` and the new order is saved for that tab.**

**Comment by sasumner** [comment]
@Yaron10 omitted _Debug Info_.  Let's presume the base version of complaint is 7.8.9.

**Comment by sasumner** [comment]
I didn't see any downside to the suggested code.

The only possibility might be users that would miss defaulting to occurrence order in their files, but that's a "we will see" I suppose.

**Comment by vinsworldcom** [comment]
I prefer the sorted by appearance as default.  Maybe an option to trigger what the default sort is?  If I need to find something by name, I don't scan alphabetically or even sort - I use the search edit box control (see my [Tab stop request](https://github.com/notepad-plus-plus/notepad-plus-plus/issues/8665)).

**Comment by Yaron10** [comment]
@sasumner,

Thank you for the PR.
The request for a preference came sooner than expected. :)

**Comment by sasumner** [comment]
Yes, and we already know I dislike adding preference settings. :-)

**Comment by Yaron10** [comment]
@sasumner,

Oh yeah. :)

The request is legit.

After another quick look at the code and *without testing it*:
I think there's no need to call `setSort(false);` in the `if (!previousParams)` block if the order of appearance is default.
The `::SendMessage(_hSearchEdit, WM_SETTEXT, 0, reinterpret_cast<LPARAM>(TEXT("")));` line in that block is not necessary regardless of the order.

Both commands are executed earlier.

***

Do you think Don would appreciate it if I opened an issue requesting some optimization of the functions-displaying code?
Optimizing it myself is above my level, but I think it's needed and possible. 

Thanks again.

**Comment by sasumner** [comment]
>...opened an issue requesting some optimization of the functions-displaying code?

Sure.  I presume you can provide some data on the need for it?
Providing that is more likely to give an issue "traction"

**Comment by Yaron10** [comment]
The "need" is obvious: it often takes too long to display the tree; especially with the new parser.

As to the "possibility": I still haven't used the Debugger but I inserted some MsgBoxes when I changed the default order for my personal use.
I remember that both `reload()` and `searchFuncAndSwitchView()` were called a few times on switching from one tab to another.
And I just had the impression that the process could be simplified.

I suppose there's not enough "meat" in that. :)

Thank you anyway.

**Comment by sasumner** [comment]
>I suppose there's not enough "meat" in that.

I don't know about that.
Showing that things (and especially things that could take a lot of time) are needlessly called multiple times is definitely relevant data! :-)

**Comment by Yaron10** [comment]
:+1: 

Thank you.
I'll open the issue tomorrow. I've had a busy day.

**Comment by sasumner** [comment]
>The "need" is obvious...

Be careful with such statements.
What is obvious to one user may not be obvious to someone else.
That's why data/facts/stats are so important.

Reference this [POSTING](https://community.notepad-plus-plus.org/topic/19911/sorting-broken-with-v7-8-9-update) where user said "sorting is broken" and when asked for some example data to support his claim he responded with:  "As for examples, I haven’t been able to sort any of dozens of files, including lists of only numbers, so take your pick."
Clearly no one is going to take that seriously, especially after doing a quick sort of their own to verify operation.

For example, you (@Yaron10) are clearly working with C++ files of some "large" size.
Someone looking at a "slowness" complaint with functionlist, without any data, might grab a small/medium size C++ file, look at how functionlist is working, and declare:  "no problem".

**Comment by Yaron10** [comment]
> The "need" is obvious...

You're right. 
I hope the issue I've opened is clear enough.

Thanks again.

**Comment by donho** [comment]
@Yaron10  Regarding this issue (request), what you want is your function list is always sorted, right?
@vinsworldcom has shown a good point: for some users, it's good to keep the current unsorted behaviour.
So I would say it should be unsorted by default, but if user clicks on the sort button, it will be remembered for all documents, and it will be remembered through the sessions.
What do you think?

**Comment by sasumner** [comment]
>What do you think?
Well, I think that means more work for my PR!  :-)

**Comment by Yaron10** [comment]
@donho,

>  Regarding this issue (request), what you want is your function list is always sorted, right?

Not necessarily. The order of appearance can be preferred in some cases.
How about a pref for the default state?

Thank you.

@sasumner,

Thank you in advance. :)

**Comment by Yaron10** [comment]
@donho,

If you don't want an extra setting, the question should be what default state would be preferred by most users.
IMO, it's the sorted display. 

Also, MS VS and other editors list the functions "Sorted by Name".

**Comment by vinsworldcom** [comment]
I like the idea of a preference setting, barring that my preferred state is
document order, not alphabetical.  But I am only one opinion.

Cheers.

**Comment by sasumner** [comment]
My view is always:  "A preference setting only when absolutely necessary"
I don't think it is necessary in this case.
I think, to conform to the norm (other editors) because that would be what users with familiarity would expect, that default should be sorted.
Current state would be retained for files in the session, per Don's suggestion.

**Comment by vinsworldcom** [comment]
If I have to unclick sorted button to get file appearance order but it
stays that way for all files in the current session, I can live with that.
Thanks

**Comment by Yaron10** [comment]
> Current state would be retained for files in the session

But then we would lose NPP's major advantage: per-tab display.

If an extra setting is too much, I think it's better not to change anything.

**Comment by donho** [comment]
@sasumner 
> My view is always: "A preference setting only when absolutely necessary"
I don't think it is necessary in this case.

Totally agree with you.
We don't need to have any option in Preferences dialog. All we need is remember the state of "sort" button.

**Comment by donho** [comment]
@Yaron10 
> But then we would lose NPP's major advantage: per-tab display.
> If an extra setting is too much, I think it's better not to change anything.

I think it's OK - function sorting it's rather a global preference - if you prefer function name sorting in your cpp files, you would like also name sorting in your c# files. In the worst case, you can click on the button when you switching files.

**Comment by vinsworldcom** [comment]
Agreed. I use functionlist.xml customized as table of contents for markdown
files and my Perl parser grabs POD which is at the end so I prefer file
appearance order and just stick with that for all files types and use the
function list search box to find a function.  As long as sorting or
unsorting applies globally to all files opened in a Notepad++ editing
session, that works for me.  Ideally Notepad++ remembers that preference in
config.xml, but beggars can't be choosers.

Thanks for hearing me out on this.

Cheers.

PS just saw the escape key clear text in function list search box code
push, thanks! Just need tab key between search box and treeview in function
list now and I'm a happy camper.

**Comment by Yaron10** [comment]
@donho,

> All we need is remember the state of "sort" button.

If I understand you correctly, you mean remembering the state for the session and NOT in `config.xml`.
Apart from losing the per-tab display, I think that some parts of the code would become irrelevant and have to be modified (e.g. `_doSort`).

How about saving the state of the "Sort" button when the "Function List" panel was last visible?
-- Add a setting to `config.xml` defaulted to "sort".
-- Save the state in the active tab to `config.xml` on exit.

- No explicit UI setting.
- Per-tab display is kept.

I'm not suggesting it for my personal use. I just believe that per-tab display is a useful feature.
As you understand.

Thank you.

**Comment by Yaron10** [comment]
> I think that some parts of the code would become irrelevant and have to be modified (e.g. _doSort).

Actually - if removing those parts could improve the display performance, a global state might be a good idea. :)

**Comment by donho** [comment]
@Yaron10 
> If I understand you correctly, you mean remembering the state for the session and NOT in config.xml.

I meant both: remembering the state for the session and THROUGH the session - so the state will be written in config.xml.

> How about saving the state of the "Sort" button when the "Function List" panel was last visible?

If you wanna keep per-tab sorting state, then I don't see the advantage of your initial feature request - you were asking sorting by default, then each opened tab will be sorting by default.

> -- Add a setting to config.xml defaulted to "sort".

I prefer to keep default value as it is now, so it'll be non-sorting. But once you click on sort, it will be sorted all the time during the session, and even on the next launch time, until you switch it to unsorting.

> -- Save the state in the active tab to config.xml on exit.

The current state of sort will be saved in config.xml on exit for the next launch.

**Comment by Yaron10** [comment]
@donho,

> If you wanna keep per-tab sorting state, then I don't see the advantage of your initial feature request - you were asking sorting by default, then each opened tab will be sorting by default.

Currently If tab `A` is "unsorted" and tab `B` is "sorted" (you manually changed it) and you switch between them, you have a different display for each tab.
I wanted the *default* display to be sorted: a new tab (with a tree) should be sorted.
But I still want to be able to change tab `A` to "unsorted" and on switching between the tabs have two *different* displays. 

I think that this point is key to the other points.

**Comment by donho** [comment]
@Yaron10 
I do understand your point. The thing is, some users (like @vinsworldcom) prefer the unsorting behaviour.
I would suggest to not change the default (unsort) behaviour, so we can keep per-tab sorting state. 
But to me it's not so bad my solution - sorting or not is a personal preference and it'll not be different because of different language or files. And you can change it easily and it'll be saved for the next session.

**Comment by Yaron10** [comment]
@donho,

> I would suggest to not change the default (unsort) behaviour, so we can keep per-tab sorting state.

We can have per-tab display even if the default is "sorted".
But I suppose you're thinking of performance too.

Anyway, a setting and per-tab display is great.

Thank you. I appreciate it. 
:+1:

**Comment by sasumner** [comment]
If the comments are all finished... :-)

I'll try to "sort" (sorry) it all out.
And determine what is agreed upon, and what @donho approved.

I'll close earlier PR associated with this issue.

**Comment by Yaron10** [comment]
@sasumner,

Thank you. Sorry for the extra work.

It's not quite sorted out yet. :)

Don has agreed to a new setting. I'm not sure if he prefers an explicit UI setting or a hidden one.
(IMO an explicit UI setting would be easier to implement and also better performance-wise).

It seems that Don prefers the default to be "unsorted".

**Comment by ArkadiuszMichalski** [comment]
@sasumner 
https://github.com/notepad-plus-plus/notepad-plus-plus/issues/1151 << same from 2015, maybe close this old and keept this bug?
