### ISSUE TITLE
Colorful Smilies

### ISSUE THREAD

**Issue by Laserlicht** [notepad-plus-plus/notepad-plus-plus#8793]
### Description of the Issue
(Option to) Render Unicode Smilies in color like modern browsers.

Helpful if you
- writing HTML-Pages with smilies
- writing long concept-text e.g. for Whatsapp-Pasting

### Expected Behavior
🙂

### Actual Behavior
Actually rendered with outlines (hard to recognize).
☻

**Comment by sasumner** [comment]
It's not something Notepad++ has control over.

**Comment by donho** [comment]
@sasumner 
> It's not something Notepad++ has control over.

In the recent version of Notepad++, it has control over :) 

@Laserlicht 
Enabling Direct Draw and restarting Notepad++ will do it:

![image](https://user-images.githubusercontent.com/90293/91914687-e64a7b80-ecb8-11ea-97d2-9128e8d7b03b.png)

**Comment by Laserlicht** [comment]
Oh, nice.

Thank you very much. 🙂

**Comment by sasumner** [comment]
>Render Unicode Smilies in color like modern browsers.

Well it doesn't render it the same way as my browser; that's what I was getting at.
So for someone wanting it _exactly_ the same...probably disappointment.
This smile always looks the same ----> :-)
