### ISSUE TITLE
Mouse horizontal scroll wheel not working

### ISSUE THREAD

**Issue by Jamalek** [notepad-plus-plus/notepad-plus-plus#8794]
### Description of the Issue

When using mouse that has a horizontal scroll wheel such as the Logitech MX master i can't use that scroll wheel to scroll horizontally in Notepad++

### Steps to Reproduce the Issue
When scrolling the scroll bar moves a bit, than stops along with the window content.
An old looking scrollbar appears and moves instead but the window content is not moving anymore

**Comment by sasumner** [comment]
Perhaps when it stops you've reached the widest point in your text?

**Comment by Jamalek** [comment]
https://youtu.be/LShRbJOSfqc
See the horizontal scrollbar movement

**Comment by sasumner** [comment]
I'm going to close this one as a duplicate of #2096
