### ISSUE TITLE
Wrong following a link on double click new line

### ISSUE THREAD

**Issue by Miroslav-a** [notepad-plus-plus/notepad-plus-plus#8795]
### Description of the Issue
When you double-click on a new line, a following a link specified at the beginning of the document is triggered.

### Steps to Reproduce the Issue

1. Paste link into first line of document 
2. Key Enter
3. Double click new line

### Expected Behavior

Text selection.

### Actual Behavior

Following a link.

### Screen capture
[See screen capture here](https://i.ibb.co/khfyN0b/notepadd-bug.gif)

### Debug Information

Notepad++ v7.8.7   (32-bit)
Build time : Jun  5 2020 - 02:34:28
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS Name : Windows 10 Enterprise (64-bit) 
OS Version : 1903
OS Build : 18362.1016
Current ANSI codepage : 1251
Plugins : DSpellCheck.dll mimeTools.dll NppConverter.dll NppExport.dll NppFTP.dll 

### Gratitudes
Thank you for the wonderful program and your work!

**Comment by Uhf7** [comment]
This has been fixed with PR #8584.

**Comment by Miroslav-a** [comment]
Great, thanks!
