### ISSUE TITLE
Links security issue

### ISSUE THREAD

**Issue by makemefeelgr8** [notepad-plus-plus/notepad-plus-plus#8798]
### Description of the Issue
There is a way to open any link that was typed in the txt file without interacting with the link directly.

### Steps to Reproduce the Issue
1. Create the new document.
2. Paste the following text:
```
https://www.google.com

test

https://stackoverflow.com

test
```
3. It should look like this:
![bug](https://user-images.githubusercontent.com/39099842/91986671-aa093080-ed35-11ea-9e9e-5900171fc240.png)

4. Double click the exact spot marked with (1) on the image. It is located to the right of the second link.

5. Bug: As you can see, the 1st link was opened, not the 2nd one.

6. Double click the exact spot marked with (2) on the image. It is located below the text.

7. Bug: For some reason, 1st link was opened in browser.

### Expected Behavior
In step 5 I expect it to either do nothing or open 2nd link.
In step 7 I expect it to do nothing.

### Actual Behavior
Notepad opens links in browser while double clicking on an empty space. I consider it to be a real security flaw, as it allows anyone to put some malicious links inside the document and make users open them by accident.

### Debug Information
Notepad++ v7.8.7   (32-bit)
Build time : Jun  5 2020 - 02:34:28
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS Name : Windows 10 Enterprise LTSC 2019 (64-bit) 
OS Version : 1809
OS Build : 17763.1397
Current ANSI codepage : 1251
Plugins : DSpellCheck.dll mimeTools.dll NppConverter.dll NppExport.dll NPPJSONViewer.dll

**Comment by sasumner** [comment]
Should be fixed by #8584
