### ISSUE TITLE
Opening 620 MB SQL file leaves it very slow

### ISSUE THREAD

**Issue by luapfr** [notepad-plus-plus/notepad-plus-plus#8802]
I’m trying to manipulate some SQL or XML files but they are large files and notepad ++ crashes.

My computer has a 
Windows 10 64 Bits
Core I7 8750h 32GB RAM
1TB SSD
I’m using Notepad ++ 7.8.8 64 Bits

I did the forum procedures where I ran the same without a plugin
https://community.notepad-plus-plus.org/topic/19939/opening-620-mb-sql-file-leaves-it-very-slow/6

Notepad++ v7.8.8   (64-bit)
Build time : Jun 23 2020 - 23:59:56
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : ON
Local Conf mode : OFF
OS Name : Windows 10 Pro (64-bit) 
OS Version : 2004
OS Build : 19041.450
Current ANSI codepage : 1252
Plugins : none

**Comment by dail8859** [comment]
Since renaming the file to txt solved the issue, this points the SQL Lexer which is part of the [Scintilla project](https://scintilla.org/). You will have to open an issue with that project for them to look into this.

**Comment by luapfr** [comment]
it is not just SQL if it is XML or any other file format that is large gives the same problem.

**Comment by dail8859** [comment]
Again if a regular text file works then it still indicates its whatever lexer is being used (SQL, XML, etc) so it is still part of the Scintilla project.

**Comment by luapfr** [comment]
Ok

https://sourceforge.net/p/scintilla/bugs/2200/

**Comment by linquize** [comment]
Are the lines too long?

**Comment by luapfr** [comment]
I tested
SQL
XML
JSON
CSV

They all give the same problem
in the case in XML the longest line is 200 characters

In SQL the longest line is 237 characters long

**Comment by luapfr** [comment]
Attached an XML file and a Video showing the Problem.

https://mega.nz/file/Buol0YyB#nHXTOSQFwI1LfmZLRfHJ3eL8L691Pkr21D89arbk81c

**Comment by luapfr** [comment]
`It appears to be slow or hanging rather than crashing. Notepad++ has some more features turned on which makes it less responsive in this case than SciTE which also uses Scintilla. Syntax styling takes time and memory as does line wrapping. A style byte is used for each text byte so the in-memory representation will be at least double the file size plus more memory for indexing line ends and remembering wrap state. Default SciTE turns off the styling for files larger than 10 MB. SciTE can be made more responsive for huge files by turning on idle styling with

idle.styling=1
UltraEdit appears to not be wrapping lines and I suspect it only supports monospaced fonts which simplifies line wrapping.

While there is potential for improving performance on large files, the design centre of Scintilla is programming language source code and handling huge data files is a secondary concern.`


The problem that this makes working with large files impossible, there should be a solution for that
because I only took the trial version of UltraEdit and I don’t consider buying it because NotePad ++ has everything I need and should have a fix for that.

I see that the solution for notepad ++ is also to disable the syntax by file size at least so it would be possible to work with large files.

**Comment by zufuliu** [comment]
[A workaround] Please try [Notepad2](https://github.com/zufuliu/notepad2/releases) 4.20.09 (will be released in next week), latest daily builds are available at https://github.com/zufuliu/notepad2/actions and https://ci.appveyor.com/project/zufuliu/notepad2, Note: file larger than 4 GiB is not yet implemented, see https://github.com/zufuliu/notepad2/issues/125.

For Notepad++, you can wait for Scintilla 5.0 or 5.1, see discussions for following issues:
https://sourceforge.net/p/scintilla/feature-requests/1373/
https://sourceforge.net/p/scintilla/feature-requests/1370/
https://sourceforge.net/p/scintilla/feature-requests/1347/
https://sourceforge.net/p/scintilla/feature-requests/1372/

For current Notepad++, with following changes Notepad++ should works better:
1. Use idle styling, see https://www.scintilla.org/ScintillaDoc.html#SCI_SETIDLESTYLING
2. To reduce memory usage by about half, use SCLEX_NULL + SC_DOCUMENTOPTION_STYLES_NONE  for large files, see https://www.scintilla.org/ScintillaDoc.html#SCI_CREATEDOCUMENT
3. change int to Sci_Position or similar to support file larger than 2 GiB in 64-bit Notepad++. 
4. apply changes from https://sourceforge.net/p/scintilla/bugs/2197/ (Scintilla 4.4.5, not yet released)

The remaining changes made in Notepad2 but not yet considered to be included in recent Scintilla are SSE2/AVX2 optimizations, see https://sourceforge.net/p/scintilla/feature-requests/1347/#e1cc.

**Comment by luapfr** [comment]
Notepad2 is not an option as it lacks many features that notepad ++ has.

Now on how to make Notepad ++ open large files it's very complicated the steps you went through I tried here but I couldn't.
   A correction for this is more interesting in the next version.

   Thankful.

**Comment by zufuliu** [comment]
I meant for larger files, use Notaped2 as a workaround, not for general use.

My fork of https://github.com/zufuliu/notepad2 is based on https://github.com/XhmikosR/notepad2-mod with many features and improvements, and is the only (at least before above mentioned issues fixed in Scintilla) public available, free and open source Scintilla-based editor that can handle large file (especially these with many long lines) smoothly.

I'm wondering what features you need to process large JSON, XML, SQL, CSV files. In Notepad2 syntax highlighting and code folding is supported and enabled for all files (Text File, 2nd Text File, ANSI Art don't have syntax highlighting them self, code folding for these files are indentation based like Python).

**Comment by luapfr** [comment]
> Isn't the workaround to just rename really large files to .txt before opening with N++?

Yes it is what I am doing until a correction for this problem.

**Comment by Lonzak** [comment]
I experience the same problem with a ~120MB SQL file already (using latest version which is currently 7.9.4). CPU spikes to 100% and the np++ app hangs for quite some time. After reading this I renamed the file .txt and disabled line wrapping. Then viewing the file becomes bearable again...
