### ISSUE TITLE
Vertical Edge Marker Disappears After Closing NPP

### ISSUE THREAD

**Issue by Dravok** [notepad-plus-plus/notepad-plus-plus#8805]
### Description of the Issue

The vertical column line becomes invisible after closing and reopening NPP.
The column number is still valued in the textbox under Preferences->Editing->Vertical Edge Settings, however, I have to edit the textbox to get the line to reappear (just adding or removing a space in the textbox is enough to get it to reappear).

### Steps to Reproduce the Issue

1.  Enter any column number in the Vertical Edge Settings textbox under Preferences->Editing. A vertical line will appear in the designated column.
2.  Close the Preference window.
3.  Close Notepad++
4.  Reopen Notepad++. Vertical line will be missing from files.

### Expected Behavior

For vertical line to remain visible.

### Actual Behavior

Vertical line disappears.

### Debug Information

Notepad++ v7.8.9   (64-bit)
Build time : Jul 15 2020 - 20:31:49
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : ON
Local Conf mode : OFF
OS Name : Windows 10 Enterprise (64-bit) 
OS Version : 1909
OS Build : 18363.1016
Current ANSI codepage : 1252
Plugins : AutoEolFormat.dll ComparePlugin.dll DSpellCheck.dll Explorer.dll ExtSettings.dll HexEditor.dll HTMLTag.dll mimeTools.dll NppConverter.dll nppcrypt.dll NppExec.dll NppExport.dll NppFTP.dll NPPJSONViewer.dll NppSaveAsAdmin.dll NppSnippets.dll NppXmlTreeviewPlugin.dll OpenSelection.dll SurroundSelection.dll XMLTools.dll

**Comment by vinsworldcom** [comment]
ExtSettings plugin can add multiple vertical edge lines.  Make sure this plugin is not interfering with Notepad++ vertical edge.

Cheers.

**Comment by Dravok** [comment]
You are right. I did not have any lines defined in the plugin so I added one and now the line stays after closing.

**Comment by sasumner** [comment]
@dravok / @vinsworldcom 

So was this just a "clash" between the native feature and the plugin's feature?
Or is this something wrong with the native feature?

**Comment by Dravok** [comment]
It was a clash. If I disabled the plugin, the line would remain visible after closing.
