### ISSUE TITLE
Prevent or Prompt Overwrite of Newer File

### ISSUE THREAD

**Issue by cawoodm** [notepad-plus-plus/notepad-plus-plus#8806]
I often run into the problem that I overwrite a file by mistake which has been changed by another program.
NPP offers some prompts that a file has changed but many users like myself disable or cancel these when busy.
I think NPP should always prompt to overwrite a file which has changed since it was last read in NPP.

```
if currentFileDate > dateFileWasRead then PROMPT "This file was changed since you began editing, do you really wish to save?"
```

**Comment by sasumner** [comment]
Behavior is already in Notepad++.

>NPP ... prompts that a file has changed but many users like myself disable or cancel these when busy.

If you value your data, don't ignore prompts.

**Comment by cawoodm** [comment]
Allow me to explain why I and many others disable the notifications. We have NPP open with various log files and code. The constant notifications of logfiles being updated are an annoyance so we switch them off. We also don't want silent updates as these would overwrite any code we have written. If you use NPP intensively you will see there is a use case for preventing a save to a file that has changed since it was loaded.

**Comment by sasumner** [comment]
Reopening as a feature request against current behavior in N++ 7.8.9.

Sorry, it didn't hit me that you were talking about the file at save time rather than just the buffer during normal use.

**Comment by Ekopalypse** [comment]
Does that make sense? It looks to me as if the workflow has to be changed rather than npp. From the given explanation there is no reason to assume that changes made to a file are persistent. What if the file is changed from the outside right after the user has saved it?

**Comment by sasumner** [comment]
>What if the file is changed from the outside right after the user has saved it?

I would presume that this event would be detected when the user saves again.
Or maybe I'm not understanding the implication of your comment?

**Comment by Ekopalypse** [comment]
> I would presume that this event would be detected when the user saves again.

but what if the user does something else instead:
- closes file
- stops editing
- closes npp
? 
The workflow is flawed. How can a user be sure that the changes exist if the file is permanently changed outside Npp?
For me this feature would make no sense at all unless I've missed something important.

**Comment by sasumner** [comment]
@Ekopalypse 

Perhaps in the "closes file" case the user is notified of the situation and can make a decision at that point on what to do; same for "closes npp".  Not sure what "stops editing" means. :-)

I don't know; I'm not necessarily an advocate of this feature request, just trying to be a good moderator and consider the positions of all.  :-)

**Comment by Ekopalypse** [comment]
stops editing = file still open in npp but user does not modify the content anymore.
I don't care if this feature is implemented or not - I just thought I shared my concerns about the rationale why it should be implemented. I think this will just be another area where users might get confused about what to do and what npp offers to do for them.

**Comment by sasumner** [comment]
I think for the "stops editing" case, nothing would happen; it is only when user initiates save or a N++ event that would initiate a save that something would happen.

It does seem like there is a lot of user confusion over the externally-changed file situation.

**Comment by Ekopalypse** [comment]
Maybe I'm missing something but my understanding of the FR is that a file will be modified and this file will be changed by an other source as well. Now the suggestion is that npp should inform the user that the file has been changed since the user has loaded it. For what purpose? If the user decides to ignore this information and save it anyway then it might be that the changes will be overwritten by the next "outside npp" saving. If the user reloads the document and does it changes again, then ... devils circle. This doesn't make sense, what am I missing?

**Comment by cawoodm** [comment]
`IF fileHasChangedSinceItWasLoaded THEN warnUserBeforeSave`

**Comment by Ekopalypse** [comment]
@cawoodm :-) - I think I got that :-D
But as it seems, I could not make myself understood. 
Doesn't matter, if it should be implemented, then hopefully with a way to turn it off and, most importantly, not set it as the default.

**Comment by donho** [comment]
If I do understand, the feature request of @cawoodm is an option to make a buffer independently without any system checking?

**Comment by Ekopalypse** [comment]
@donho, not sure I understand you correctly.
The feature should assume that a user has disabled automatic file status detection.
When the user tries to save a buffer, the feature should check whether the file has been modified outside npp in the meantime
and if it has, then alert the user.

**Comment by sasumner** [comment]
@donho said:

>If I do understand, the feature request of @cawoodm is an option to make a buffer independently without any system checking?

Not entirely.  The "check" would occur when user attempts the next save.

**Comment by donho** [comment]
OK thank you @Ekopalypse & @sasumner for your explanation.
It's not more complicated for the users to copy the data to a new document for modifying without being interrupted by popup message.
OTOH, this feature will make not only the coding logic more complex, but also the usage more confused.
Therefore it won't be implemented.
