### ISSUE TITLE
 file associations ICONS (WHY not ?)

### ISSUE THREAD

**Issue by Diaskhan** [notepad-plus-plus/notepad-plus-plus#8811]
Its passed a 5 yaears, when I start using NPP.
But a problem here, its very Annoing to use notepad without file associations ICONS.

In my desktop folder have a SQL files, js files, and C# files, and simple txt files.
**Guys we must draw Normal icons for source files!**
And Naturally make File associations fluent and easy to use. 

For each type( or category) there must be Good Colorize solution.

For exmple for SQL files must be Yellow.
For js for example blue!

When all source code files Have 1 icon, its goes messy, and chaotic to use NPP!

![image](https://user-images.githubusercontent.com/15046677/92212684-29bd0980-eeb4-11ea-828e-8763e5a85443.png)

Look at WPS Office file Icons. Easy to understnad which file and which type!

![image](https://user-images.githubusercontent.com/15046677/92215187-39d5e880-eeb6-11ea-89ea-9179b121705c.png)

**Comment by Diaskhan** [comment]
1.For a simple TXT file could deafult Icon.
2.But for other source files must be colorize Icons, To understand by color which file by type do U searching!

**Comment by sasumner** [comment]
I'm not really sure what you're driving at here.  But...  You're welcome to contribute to the project and create such icons and the respective code that will do what you want it to do...

But for the regular Notepad++ developers, this is a "not going to implement" kind of thing.  Sorry.
