### ISSUE TITLE
Yes-No-Cancel-Yes to all-No to all box visually truncates lengthy file paths

### ISSUE THREAD

**Issue by sasumner** [notepad-plus-plus/notepad-plus-plus#8812]
## Steps to Reproduce the Issue (STR)
1. Get a CMD prompt
2. Create a fairly lengthy directory path, e.g. 
```
md w:\a123456789\b123456789\c123456789\d123456789\e123456789\f123456789\g123456789
```
3. Create TWO files in this path:
```
echo ImFromTest1>w:\a123456789\b123456789\c123456789\d123456789\e123456789\f123456789\g123456789\test1.txt
echo ImFromTest2>w:\a123456789\b123456789\c123456789\d123456789\e123456789\f123456789\g123456789\test2.txt
``` 
4. Open `test1.txt` into N++ by using _File_ > _Open_ and then specifying in the _File name_ box:
```
w:\a123456789\b123456789\c123456789\d123456789\e123456789\f123456789\g123456789\test1.txt
```
5. Modify the file's tab content in some manner, so that its tab icons turn red.
6. Choose _File_ > _Close_ ; observe the appearance of this window :
![image](https://user-images.githubusercontent.com/30118311/92281170-0c466a80-eec9-11ea-84b9-5a8f9f2f8322.png)
7. Press the `Cancel` button so that `test1.txt` is not actually closed
8. Open `test2.txt` similarly to what was done for test1.txt in step 4, by specifying in the _File name_ box:
```
w:\a123456789\b123456789\c123456789\d123456789\e123456789\f123456789\g123456789\test2.txt
```
9. Modify `test2.txt`'s file's tab content in some manner, so that its tab icons turn red.
10. Choose _File_ > _Close All_ ; observe the appearance of this window :
![image](https://user-images.githubusercontent.com/30118311/92281387-7bbc5a00-eec9-11ea-802c-3869f546f56c.png)

### Expected Behavior

I expected to see the full file path of my file when I'm prompted to save it in step 10, so I can be sure that I'm saving the intended file.  I am shown the complete path in step 6; why not in step 10?

### Actual Behavior

The file path of my file is truncated in step 10, so much so that I can't see the rightmost part of the path, leaving me uncertain I am saving changes to the correct file.  The information should be presented more like in step 6.

### Debug Information
Notepad++ v7.8.9   (32-bit)
Build time : Jul 15 2020 - 20:26:50
Path : C:\\....................\npp.7.8.9.bin\notepad++.exe
Admin mode : OFF
Local Conf mode : ON
OS Name : Windows 10 Enterprise (64-bit) 
OS Version : 1809
OS Build : 17763.1339
Current ANSI codepage : 1252
Plugins : mimeTools.dll NppConverter.dll NppExport.dll PythonScript.dll

**Comment by eljefe7000** [comment]
Hi @sasumner , I have a fix for this issue.

The "Close All" menu item opens a dialog box template resource (IDD_DOSAVEORNOTBOX) via the StaticDialog class.  It has a static text control whose style does not match the static text control loaded by the "Close" menu item (via the ::MessageBox method).  Specifically, the latter control has the SS_EDITCONTROL style (shown below), which duplicates the style of a multi-line edit control and does not display a partially visible last line.  Applying the same style to the text control in IDD_DOSAVEORNOTBOX results in proper wrapping of text.

![image](https://user-images.githubusercontent.com/10099377/94994822-393d7a00-0568-11eb-8265-e7610b398e0a.png)
![image](https://user-images.githubusercontent.com/10099377/94994893-8cafc800-0568-11eb-8f49-210c9e1a8557.png)

**Comment by sasumner** [comment]
@eljefe7000 I haven't looked too deeply at it, but at first glimpse I have to say it looks good. :-)
