### ISSUE TITLE
Can  we have a plugin for auto code completion for javascript/JSX. 

### ISSUE THREAD

**Issue by Ats1999** [notepad-plus-plus/notepad-plus-plus#8815]
Thanks for giving such a lightweight editor. I recently switched from VS-CODE to `notepad++`. The region of switching is, VS-CODE is slow. It also makes other tasks slow as well. Notepad++ is much faster than VS-Code and it is lightweight. 

I am a *ReactJs* developer. I used to write `JSX` code on a daily basis.  I can't see any plugin for react js. 
<br>
### How the plugin works in VS-CODE
> Suppose I want to write an h1 tag
I will just write `h1` in VS-CODE and it suggests me `<h1> </h1>`.  I'll hit enter and there is an h1 tag in my file.
This is the feature i am requesting.

**Comment by dail8859** [comment]
This repository focuses on the core application itself and not plugins. Your question would be better on the forum https://community.notepad-plus-plus.org/

There may be some way to set up the auto-completetion or some other plugin not specifically for reactjs that might suit your need.
