### ISSUE TITLE
Support Hong Kong  And Fuck YOUR  MOTHER!!!

### ISSUE THREAD

**Issue by ty1972873004** [notepad-plus-plus/notepad-plus-plus#8820]
Say important things three times.

We want  Fuck YOUR  MOTHER!
We want  Fuck YOUR  MOTHER!
We want  Fuck YOUR  MOTHER!

**Comment by Lujiusi** [comment]
好美的文字🌹

**Comment by lindasczx** [comment]
好美的文字

**Comment by zhanghaiboshiwo** [comment]
好美的文字

**Comment by Jasonzyt** [comment]
好美的文字！
现在直接把抵制冬奥加进release-notes了
太恶劣了

**Comment by fengbenming** [comment]
这些老外真的是傻B，啥都不懂，就在那瞎bb

**Comment by Jasonzyt** [comment]
确实 所以我选择sublime

**Comment by BingYanchi** [comment]
好美的文字

**Comment by BingYanchi** [comment]
> 这些老外真的是傻B，啥都不懂，就在那瞎bb

作者是个台湾人，你懂的

**Comment by Young-Lord** [comment]
好美的文字
