### ISSUE TITLE
After activating the .nfo file, if the character set is not OEM-US, it will automatically reload.

### ISSUE THREAD

**Issue by KnIfER** [notepad-plus-plus/notepad-plus-plus#8823]
Found when dealing with #8589 :  

 Steps to Reproduce the Issue

1.  Open any nfo file. 
2.  Set it's charset to ANSI
3.  Switch to other doc and then switch back

### Expected Behavior
The editor is still in ascii mode as selected. 

### Actual Behavior
The editor automatically reload the nfo file,  and set encoding format to  OEM-US

### Debug Information
```
Notepad++ v7.8.9   (64-bit)
Build time : Jul 15 2020 - 20:31:49
Path : D:\Downloads\npp.7.8.9.bin.x64\notepad++.exe
Admin mode : OFF
Local Conf mode : ON
OS Name : Windows 10 Home (64-bit) 
OS Version : 1903
OS Build : 18362.1016
Current ANSI codepage : 65001
Plugins : removed
```

**Comment by northword** [comment]
An alternative solution: https://github.com/notepad-plus-plus/notepad-plus-plus/issues/9153#issuecomment-934260054
