### ISSUE TITLE
Dark theme

### ISSUE THREAD

**Issue by mmvanheusden** [notepad-plus-plus/notepad-plus-plus#8825]
Hello, is it possible to use a dark theme for notepad++?

**Comment by sasumner** [comment]
This is not a place for questions.
Please take questions to https://community.notepad-plus-plus.org/

**Comment by AntonioRedondo** [comment]
There is already an open issue requesting a dark theme: https://github.com/notepad-plus-plus/notepad-plus-plus/issues/8571
