### ISSUE TITLE
Icons on the menus how ?

### ISSUE THREAD

**Issue by luapfr** [notepad-plus-plus/notepad-plus-plus#8827]
There is a "Menu Icons version 1.22" plugin to place icons on the menus, but I've tried several times and I can't place them. I see that NotePad ++ should already have icons by default when installing.
   Because the icons gives a charm in addition to being more intuitive the location by icons.

I use NotePad ++ in the Portuguese Brazil version so I believe that this must be the problem of not being able to place the icons because it should rename the entire structure to Portuguese Brazil.

**Comment by sasumner** [comment]
Please ask these questions on the Community forum:  https://community.notepad-plus-plus.org/

**Comment by luapfr** [comment]
I understand that questions should be asked elsewhere but my question is in a next version Notepad ++ has the icons already native without having to use a plugin for this purpose.

**Comment by sasumner** [comment]
>the icons already native without having to use a plugin

Doubtful that it would be a high-priority feature for currently limited development resources to work on.
But Notepad++ accepts user contributions, if you are capable and would like to try adding it.
No guarantees about acceptance, however.
