### ISSUE TITLE
Off-selection right-click should not cancel selection in Find-result window

### ISSUE THREAD

**Issue by sasumner** [notepad-plus-plus/notepad-plus-plus#8828]
An off-selection right-click should not cancel selection in a _Find result_ (or derivative) window, when Notepad++ is so configured in the Preferences.

### Description of the Issue
Reference #8563 and associated PR #8564 which affected the main editing view(s).
The commit from the PR created the following Preference setting:
![image](https://user-images.githubusercontent.com/30118311/92496467-27b1be00-f1c6-11ea-8eac-62ce08906719.png)
The behaviour controlled by this setting should also occur in the _Find result_ window.

**Comment by donho** [comment]
@sasumner 
> The behaviour controlled by this setting should also occur in the Find result window.

Just tested, the behaviour controlled by this setting occurs also in the Find result window (without applying https://github.com/notepad-plus-plus/notepad-plus-plus/pull/8829).

**Comment by sasumner** [comment]
@donho 

>Isn't it the case for you ?

Hmm.  Well, testing now, it seems to work without applying the PR.
Not sure where I noticed it happen in order to create this issue + PR.
Since it is working, I'll close this issue and the PR.
