### ISSUE TITLE
Remove Alt+f accelerator in Column Editor window

### ISSUE THREAD

**Issue by sasumner** [notepad-plus-plus/notepad-plus-plus#8830]
A keyboard accelerator of Alt+f was wrongly assigned to the `Format` groupbox in the _Column Editor_ window due to the change introduced in issue #8580 and PR #8569 .

This assignment should be removed as Windows interprets it as a press of that window's OK button!

See this and surrounding discussion:

https://github.com/notepad-plus-plus/notepad-plus-plus/commit/7d289139e8d370da422bd4a74f8c878e537db172#commitcomment-42136176

This problem exists in post-7.8.9 software, not in a released version.

**Comment by donho** [comment]
I just discovered this issue and fixed while I was doing some localization: https://github.com/notepad-plus-plus/notepad-plus-plus/commit/55d671719c8f00f02ed32b15575bc2e6587a5e30
