### ISSUE TITLE
Add a separate style for Bookmarks Margin

### ISSUE THREAD

**Issue by Yaron10** [notepad-plus-plus/notepad-plus-plus#8833]
**STR:**
Enable `Lines Number Margin` and `Bookmarks Margin`.

**Result:**
There's no clear border between the two margins.
The user might want to add a bookmark but actually click in the `Lines Margin`. And vice-versa.

**Suggested:**
Add a separate style for `Bookmarks Margin`.

***
Notepad++ v7.8.9   (32-bit)
Build time : Sep  5 2020 - 02:32:39
Path : C:\---\notepad++.exe
Admin mode : ON
Local Conf mode : ON
OS Name : Windows 7 Enterprise (32-bit) 
OS Build : 7601.23964
Current ANSI codepage : 1255
Plugins : ComparePlus.dll HTMLTag_unicode.dll MenuIcons.dll PythonScript.dll _CustomizeToolbar.dll

**Comment by sasumner** [comment]
@Yaron10 

What I do, with Pythonscript, is colorize my bookmarks margin:

![image](https://user-images.githubusercontent.com/30118311/92593233-c42f9b00-f26e-11ea-8832-2b20c1db5d2e.png)

But, yes, you are right, and this has long bothered me, even before I colored it via script.

**Comment by Yaron10** [comment]
@sasumner,
:+1:

**Comment by Yaron10** [comment]
@sasumner,

When you find some time for this. :)

In `ScintillaEditView.cpp` before `COLORREF foldMarginColor = grey;`.

Add
```
	COLORREF bookmarksMarginBG = grey;
	i = stylers.getStylerIndexByName(TEXT("Bookmarks Margin"));
	if (i != -1)
	{
		Style & style = stylers.getStyler(i);
		bookmarksMarginBG = style._bgColor;
	}
	execute(SCI_SETMARGINTYPEN, _SC_MARGE_SYBOLE, SC_MARGIN_COLOUR);
	execute(SCI_SETMARGINBACKN, _SC_MARGE_SYBOLE, bookmarksMarginBG);
```

In `stylers` after `<WidgetStyle name="Line number margin"`.

Add
```
<WidgetStyle name="Bookmarks Margin" styleID="0" bgColor="EBEBEB" fontStyle="0" />
```

or one of the following.
```
        <!-- <WidgetStyle name="Bookmarks Margin" styleID="0" bgColor="E2E2EF" /> -->
        <!-- <WidgetStyle name="Bookmarks Margin" styleID="0" bgColor="D9EEFF" /> -->
```

Thank you.

**Comment by sasumner** [comment]
You should tackle all of my issues!
I will work on this one, but again, why don't you just do a PR ?
Is it a git factor? (git has a large learning hurdle)

**Comment by Yaron10** [comment]
> I will work on this one

Thank you.

> Is it a git factor? (git has a large learning hurdle)

That is one of the reasons.
Should I refrain from those short suggestions?

**Comment by donho** [comment]
@sasumner 
> I will work on this one

I let you assign this task to yourself.

**Comment by sasumner** [comment]
>Should I refrain from those short suggestions?

No, it's fine.
Gives a boost to getting started on things.

**Comment by Yaron10** [comment]
@sasumner and @donho,

:+1: 

Thank you both for the recent commits too.
