### ISSUE TITLE
Cannot restore window minimized to system tray when running in admin mode

### ISSUE THREAD

**Issue by kriegaex** [notepad-plus-plus/notepad-plus-plus#884]
This is an old issuse still present in npp 6.8.3:

When editing a protected file like c:\windows\system32\drivers\etc\hosts, I have to open npp as administrator. More recent versions even ask me whether I want to switch to admin mode (nice feature BTW, thanks). The problem is that when running in admin mode and minimizing the editor to system tray, it is impossible to reactivate the editor, probably due to a conceptual problem with user rights. This needs to be fixed because the only way to get npp working again is to kill the running process via task manager.

**Comment by donho** [comment]
Indeed. It's quite annoying. There are a lot of restrictions in Administrator mode. I will see what can I do about that.

**Comment by donho** [comment]
It seems the notification zone is locked (for the sake of security) while application is in Admin mode.
All I have to do is disable the tray icon mode while Notepad++ is in Admin mode.

**Comment by kriegaex** [comment]
Not nice but a pragmatic compromise. Thanks for the quick reaction, looking forward to the next release. :-)
