### ISSUE TITLE
Common open markup generates bug, closing Notepad ++

### ISSUE THREAD

**Issue by MarcieleRommel** [notepad-plus-plus/notepad-plus-plus#8840]
### Description of the Issue
Maintaining the common conversion function <! [CDATA []]> without the closing structure]]> generates a bug in Notepad, closing the software that was left unanswered.

### Steps to Reproduce the Issue
1. Open Notepad ++, put the language as XML
2. Insert the `<tag1><tag3></tag3> </tag1><! [CDATA [<xml><tag2/></xml>`
 and then linearize it (Ctrl + Alt + Shift + B)
3. Notepad ++ will no longer respond

### Expected Behavior
Detect that CDATA is missing the closing tags

### Actual Behavior
Did not detect that the tags were open and could confuse XML with CDATA, closing the application

### Debug Information
Notepad++ v7.8.4   (32-bit)
Build time : Jan 29 2020 - 01:33:47
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS Name : Windows 10 Enterprise (64-bit) 
OS Version : 1809
OS Build : 17763.107
Plugins : ccc.dll ComparePlugin.dll HTMLTag_unicode.dll JsMapParser.NppPlugin.dll JSMinNPP.dll mimeTools.dll NppConverter.dll NppExport.dll NppHasher.dll PoorMansTSqlFormatterNppPlugin.dll SQLinFormNpp.dll XMLTools.dll 

![no_response](https://user-images.githubusercontent.com/29377619/92777410-8f0e7000-f376-11ea-8541-3741afa443b2.png)
![fechando](https://user-images.githubusercontent.com/29377619/92777462-9f264f80-f376-11ea-88b1-0501f3a57bfd.png)

**Comment by sasumner** [comment]
>Ctrl + Alt + Shift + B

I don't know for sure, but I suspect this is an XMLTools plugin keycombination.
As such, this should be taken up where XMLTools is supported, as this current site is for issues relating to core Notepad++ and bundled plugins only.
Closing now, will reopen if I'm wrong...
