### ISSUE TITLE
add "Close File" option to reload file after external changes dialog

### ISSUE THREAD

**Issue by Sorontik** [notepad-plus-plus/notepad-plus-plus#8842]
### Description of the Issue
When a file is opened in NPP and then changed by another Program, NPP conveniently asks the user if they want to reload the file.
- "Yes" reloads the file (dropping all unsaved changes if there are any)
- "No" keeps the currently cached/displayed version (including unsaved changes) of the file and marks it unsaved

I'd find a third option quite useful here (both in the "unchanged file" and "unsaved changes" versions of the dialog):
- "Close File" closes the file immidiately without reloading it (and just like "Yes" drops all unsaved changes if there are any)

### Motivation
I often have to edit files in NPP, then go to another Program to see the effects of my changes.
When I'm satisfied with the results i want to close the files in NPP.
But since the other program marked the file as written, NPP asks me to reload so i have to either say "Yes" and wait for the unnecessary reload (which can take some time for large files) or i have to say "No", in which case NPP marks the file as unsaved, so when I then want to close the file, NPP asks me if i want to save my changes.

Either way, it takes time and is quite annoying if you face that situation frequently.

### Steps to Reproduce the Issue

1. open a file in NPP
2. modify it in another program
3. switch back to NPP

### Debug Information
Notepad++ v7.8.7   (32-bit)
Build time : Jun  5 2020 - 02:34:28
Path : C:\Programs\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS Name : Windows 10 Enterprise (64-bit) 
OS Version : 1909
OS Build : 18363.1016
Current ANSI codepage : 1252
Plugins : ccc.dll CodeAlignmentNpp.dll Comment Wrap.dll ComparePlugin.dll CSScriptNpp.dll HexEditor.dll MarkdownViewerPlusPlus.dll mimeTools.dll NativeLang.dll NppAutoIndent.dll NppBplistPlugin.dll NppCalc.dll NppConverter.dll nppcrypt.dll NppExport.dll NPPJSONViewer.dll NppMarkdownPanel.dll NppQrCode32.dll NppSaveAsAdmin.dll NppToolBucket.dll NppXmlTreeviewPlugin.dll PyNPP.dll Python Indent.dll PythonScript.dll ScrollPastEOFUni.dll XMLTools.dll ZenCoding-Python.dll

**Comment by sasumner** [comment]
>But since the other program marked the file as written

Have you asked the makers of that other program to NOT do that? :-)

**Comment by Sorontik** [comment]
well, since the program actually does write (and modify) the file, it's kinda the intended behavior.
It's just that once I'm satisfied with my manual changes i don't care about it anymore, i just want to close the File in NPP.
But anyway, thats just an example. The point i'm trying to make is that there are situations like this, during which it takes much longer than necessary to close the file.

And i reckon adding a third button to the dialogs (or even writing them from scratch, if you used default ones until now) shouldn't be too much of an effort

**Comment by sasumner** [comment]
>since the program actually does write (and modify) the file, it's kinda the intended behavior.

It's what I thought, I just wanted you to clarify.

> i reckon adding a third button to the dialogs ... shouldn't be too much of an effort

When people say this, I like to haul out the boilerplate response:
Notepad++ developers all donate their (limited) time to make the product better.
User-contributed code is welcomed, as long as it follows the contributing guidelines and is an appropriate modification.
Thus for the "easy ones", support from the user base is appreciated, to give the regular Notepad++ devs free cycles to work on the more difficult bug fixes and feature enhancements.

**Comment by Sorontik** [comment]
I thought about writing it myself, but since i have legit 0 experience with C++, i was hoping other people might also find this feature useful and someone amongst them would have the necessary knowlegde to prepare a pull request

**Comment by sasumner** [comment]
It main gain traction; it does seem useful.

**Comment by sasumner** [comment]
The idea from this issue is furthered a bit, here:  https://github.com/notepad-plus-plus/notepad-plus-plus/issues/8879#issuecomment-696694089

**Comment by iamjan95** [comment]
Hi @sasumner , 
This sounds like a very useful feature. Shall I work on this?

**Comment by sasumner** [comment]
@iamjan95 I can't stop you. :-)

**Comment by donho** [comment]
I prefer to keep a simplest logic: ie. Every stuff does only one thing, so there's no confusion.
It's not really complicated to answer YES, then close the document (total clicks: 2). So this request won't be implemented.

**Comment by Sorontik** [comment]
I can't see what "Stuff" would be doing more than "one thing" or where there would be room for confusion, so not sure what you mean by that first line.

Anyways, sure, it's not complicated, but as i explained in my original post, it can often take some time and be quite annoying.
(e.g. for larger files, that may even be accessed via network)

Also, allow me to quote your contributing guidelines: (Best Practises 8)
> ["Code legibility and length is less important than easy and fast end-user experience."](https://github.com/notepad-plus-plus/notepad-plus-plus/blob/master/CONTRIBUTING.md#code-legibility-and-length-is-less-important-than-easy-and-fast-end-user-experience)

Considering that I'm neither involved in the project nor providing a pull request, it's definitley not my decision to make, but according to my understanding, your contribution guidelines **call for** this feature and don't reject it.

**Comment by sasumner** [comment]
>your contribution guidelines call for this feature and don't reject it.

Dubious.
Author has the right to decide what features he wants in his product.
If he decides he doesn't want it, it doesn't get implemented.
That's his decision; end of story.
FWIW, for myself I liked the "close file" option.
