### ISSUE TITLE
Unicode character U+3009 (Right Angle Bracket) not displayed

### ISSUE THREAD

**Issue by Machinegon** [notepad-plus-plus/notepad-plus-plus#8843]
### Description of the Issue
Mathematical characters U+3009 and U+27E8 are not displayed properly using UTF-8 encoding.
I see the square box. Same character with windows notepad is working.

### Steps to Reproduce the Issue
1. Copy/Paste character ⟩ in notepad ++

### Expected Behavior
I expect to see the correct character

### Debug Information
Notepad++ v7.8.7   (64-bit)
Build time : Jun  5 2020 - 02:38:56
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS Name : Windows 10 Home (64-bit) 
OS Version : 1909
OS Build : 18363.1016
Current ANSI codepage : 1252
Plugins : mimeTools.dll NppConverter.dll NppExport.dll 

![image](https://user-images.githubusercontent.com/9700710/92849950-dc600100-f3b9-11ea-8e52-52a8cfd23093.png)

**Comment by KnIfER** [comment]
Just enable settings->misc->direct write

**Comment by sasumner** [comment]
Direct write fixes the issue, for me, so closing.
@Machinegon if it doesn't fix it for you, comment again here.

**Comment by Machinegon** [comment]
I don't see any direct write options under MISC. Is it available in 7.8.7?

**Comment by sasumner** [comment]
@Machinegon 7.8.8 and later:

![image](https://user-images.githubusercontent.com/30118311/93204261-c9d02980-f723-11ea-8ba1-1a1e46aabe9e.png)
