### ISSUE TITLE
Count function in Find tool dosen't have the best experience

### ISSUE THREAD

**Issue by CyberDracula** [notepad-plus-plus/notepad-plus-plus#8845]
The Count function should do the actual count on all the document, not only from the cursor position down (or up if Backward is active). Doing it like this it might give you the wrong expectation.
Or maybe to have a check to choose when you want to do it in all the document.

**Comment by sasumner** [comment]
>Or maybe to have a check to choose when you want to do it in all the document.

Tick _Wrap around_ to do the entire document.  

A new change that isn't released yet will provide more information about what kind of count was done.
You can see examples of what this will look like in the screenshots here: https://github.com/notepad-plus-plus/notepad-plus-plus/pull/8639
