### ISSUE TITLE
No "Reload-Prompt" if externally modified file is in Other-View 

### ISSUE THREAD

**Issue by Yaron10** [notepad-plus-plus/notepad-plus-plus#8846]
**STR:**

![תמונה](https://user-images.githubusercontent.com/10229320/92926477-bfbcdb00-f444-11ea-9b0b-c19efd13bd43.png)

Open files `A` and `B`.
Move `B` to the other view.
Activate `A`.
Modify `B` externally.
Return to NPP and activate `B`.

**Result:**
No "Reload-Prompt".
If you now manually reload the file, "Reload-Prompt" shows up.

**Works as expected if `Enable for all opened files` is selected.**

***

Notepad++ v7.8.9   (32-bit)
Build time : Jul 15 2020 - 20:26:50
Path : C:\Users\---\Downloads\npp.7.8.9.bin.minimalist\notepad++.exe
Admin mode : ON
Local Conf mode : ON
OS Name : Windows 7 Enterprise (32-bit) 
OS Build : 7601.23964
Current ANSI codepage : 1255
Plugins : none

**Comment by sasumner** [comment]
@Yaron10 

Enough commonality with #7581 to close this one?
Seems like it to me.
Is you agree, please close as a duplicate and 7581 can remain as the "master".

**Comment by Yaron10** [comment]
@sasumner,

Your comment there is detailed and very similar to mine here. :)
Closing.
