### ISSUE TITLE
Text Direction RTL does not work if DirectWrite is ON

### ISSUE THREAD

**Issue by Yaron10** [notepad-plus-plus/notepad-plus-plus#8847]
**STR:**
Check `Preferences -> MISC. -> Use DirectWrite`.
Restart NPP.
`View -> Text Direction RTL`.

**Result:**
Some elements change but the document remains LTR.

***

Notepad++ v7.8.9 (32-bit)
Build time : Jul 15 2020 - 20:26:50
Path : C:\Users---\Downloads\npp.7.8.9.bin.minimalist\notepad++.exe
Admin mode : ON
Local Conf mode : ON
OS Name : Windows 7 Enterprise (32-bit)
OS Build : 7601.23964
Current ANSI codepage : 1255
Plugins : none

**Comment by zufuliu** [comment]
This is a Scintilla limitation, when using DirectWrite, you can set bidirectional.
https://www.scintilla.org/ScintillaDoc.html#SCI_SETBIDIRECTIONAL

**Comment by Yaron10** [comment]
@zufuliu,

Thank you.
