### ISSUE TITLE
Monitoring not scrolling to the end of the file with Word wrap enabled

### ISSUE THREAD

**Issue by jofon** [notepad-plus-plus/notepad-plus-plus#8850]
### Description of the Issue
Monitoring (tail -f) doesn't scroll to the end of the file when Word wrap is enabled. With word wrap disabled, it correctly scrolls to the end.

### Steps to Reproduce the Issue
1. Open a file
2. Activate Word wrap and Monitoring
3. Open the same file in another editor
4. Edit and Save the file

### Expected Behavior
After saving the file, Notepad++ should reload the file and scroll to the last line.

### Actual Behavior
After saving the file, Notepad++ reloads the file and the scroll flickers to the end and back to the original position.

### Debug Information
Notepad++ v7.8.9   (32-bit)
Build time : Jul 15 2020 - 20:26:50
Path : C:\NPP\Releases\npp.7.8.9.bin\notepad++.exe
Admin mode : OFF
Local Conf mode : ON
OS Name : Windows 10 Enterprise (64-bit) 
OS Version : 1909
OS Build : 18363.1082
Current ANSI codepage : 1252
Plugins : mimeTools.dll NppConverter.dll NppExport.dll

**Comment by Yaron10** [comment]
@jofon,

Thank you for opening the issue and the PR.

In order to test this case, we need to *uncheck* `Update silently` and `Scroll to last line after update`.

If the monitored file is "current" (in either view), it *does* scroll but not always to the end.
If the monitored file is NOT "current", NPP doesn't even try to scroll (`if (buffer == _mainEditView.getCurrentBuffer())`).

So changing to `execute(SCI_DOCUMENTEND);` is good and solves the cases where it doesn't scroll to the end.
But `.setPositionRestoreNeeded(false);` doesn't change anything and is not needed.

Can you please test and confirm?

**Comment by jofon** [comment]
@Yaron10 

`.setPositionRestoreNeeded(false);` is required if you only have the file in one view. 


Here's the behaviour **without** the setPositionRestoreNeeded():
![withoutrestore](https://user-images.githubusercontent.com/70416966/92995977-e9870800-f4ff-11ea-9a48-4d4b1886ca53.gif)

And with the view cloned, without setPositionRestoreNeeded():
![clonned_without_restore](https://user-images.githubusercontent.com/70416966/92995980-ec81f880-f4ff-11ea-9ab0-78f6eeaed92b.gif)

And here's the behaviour **with** the setPositionRestoreNeeded():
![withrestore](https://user-images.githubusercontent.com/70416966/92995966-d83dfb80-f4ff-11ea-83b1-8c608be36897.gif)

**Comment by Yaron10** [comment]
@jofon,

Interesting.
It works for me without `.setPositionRestoreNeeded(false);`. Both one file in one view and clones in two views.
With a fresh portable NPP, it scrolls but not to the very end.

Anyway, it's been committed. Thank you.

**Comment by Yaron10** [comment]
@jofon,

When I tried it earlier, the external editor was maximized.
On returning to NPP, the file was scrolled.

I've tried it again with NPP and the external editor side by side, and noticed the scroll bar jumps up and down but at the it was down.
I thought `.setPositionRestoreNeeded(false);` would prevent the jumping but it does not.
Do you see jumping with `.setPositionRestoreNeeded(false);`?
And without it, do the visible lines not change at all?

**Comment by jofon** [comment]
@Yaron10 

The scroll bar jumps up and down whether or not you have the `.setPositionRestoreNeeded(false);`. You can actually see that happening in the gifs I posted (though NPP is a bit too small on them). 

I placed a breakpoint, and the whole callstack happens twice, which is probably the reason for the scroll bar jumping up and down.
```
Notepad_plus::notifyBufferChanged
FileManager::beNotifiedOfBufferChange
Buffer::doNotify
Buffer::reload
Notepad_plus::process
Notepad_plus_Window::runProc
Notepad_plus_Window::Notepad_plus_Proc
```

**Comment by Yaron10** [comment]
@jofon,

I couldn't and can't see anything in the gifs. :)

I'm curious and would like to figure out the different behavior we get *without* `.setPositionRestoreNeeded(false);`.
If you place the caret at the top of `stylers.model.xml`, monitor, modify externally, save and activate NPP - no scroll at all?

**Comment by jofon** [comment]
@Yaron10 

Without `.setPositionRestoreNeeded(false);`
- Scroll bar jumps to the end, back to the top, back again to the end, and then to the top and stops. 
- The view flickers between the end and the top as the scrolling happens.
- Caret is moved to the end of the last line.

With `.setPositionRestoreNeeded(false);`
- Scroll bar jumps to the end, and the view is changed accordingly.
- Scroll bar goes to the top, back again to the end and stops. There doesn't seem to be any flickering of the view.
- Caret is moved to the end of the last line.

**Comment by Yaron10** [comment]
@jofon,

Just tested again with a fresh portable NPP.
`.setPositionRestoreNeeded(false);` is not there: it scrolls to the end or almost to the end.

Thank you. :+1:
