### ISSUE TITLE
Corrupt Names in Function List

### ISSUE THREAD

**Issue by miqrogroove** [notepad-plus-plus/notepad-plus-plus#8855]
### Description of the Issue
I'm playing with the Function List sidebar for the first time today, and noticed with a PHP file some names are just wrong.

### Steps to Reproduce the Issue
1. Retrieve and open https://sourceforge.net/p/xmb-forum/code/2841/tree/xmb19x/trunk/source/include/validate.inc.php?format=raw
2. Click the Function List button on the toolbar.
3. Compare names in sidebar with names in source.

### Expected Behavior
The Function List sidebar should simply list the functions defined by the PHP source.

### Actual Behavior
Five of the functions near the end of the file are displayed with the wrong names (looks like some chars missing?) in the sidebar.

### Debug Information
Notepad++ v7.8.9   (32-bit)
Build time : Jul 15 2020 - 20:26:50
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS Name : Windows 10 Enterprise (64-bit) 
OS Version : 2004
OS Build : 19041.508
Current ANSI codepage : 1252
Plugins : none

**Comment by ArkadiuszMichalski** [comment]
I can confirm in 7.9 RC, missing first `f` char:

![a](https://user-images.githubusercontent.com/2730894/93818490-b7da1380-fc5a-11ea-99cf-104cdce0876d.gif)

**Comment by sasumner** [comment]
The missing "f" is a long-known issue.

**Comment by donho** [comment]
@sasumner 
> The missing "f" is a long-known issue.

Could you point the similar issues to me please?

**Comment by sasumner** [comment]
Here is one:  #4208

**Comment by sasumner** [comment]
Here is another: #4627

**Comment by ArkadiuszMichalski** [comment]
Just to add that there is a similar case with 'if' at the beginning https://github.com/notepad-plus-plus/notepad-plus-plus/issues/3321.
