### ISSUE TITLE
Find in Files: A suggestion for ignoring binary files

### ISSUE THREAD

**Issue by Cerno-b** [notepad-plus-plus/notepad-plus-plus#8857]
### Description of the Issue

_Disclaimer: If this is the wrong place for a feature request and corresponding discussion, I'd be happy to move the issue elsewhere if someone could point me in the right direction._

As has been noted [before](https://github.com/notepad-plus-plus/notepad-plus-plus/issues/232), the feature to search and replace within files can be dangerous, since Notepad++ will not distinguish between binary and non-binary files. Corrupted binary files may be the result. Also, searching (with or without replace) over a larger directory structure will take significantly longer if a lot of binary files are present, especially if they are large.

I understand that the previously discussed solutions have their issues:
* no clear-cut way for Notepad++ to decide what a binary file is (we don't want to miss files that look like binaries but aren't)
* assuming a file is binary by its extension is very error-prone, (it is not guaranteed that the extension points to a binary file)
* which file extensions should be considered binary in the first place? Different users will expect different behaviour and a dangerous functionality like search and replace without undo must be predictable.

I would suggest extending the filter functionality to give the users more options for excluding binary files, while keeping full control over what files will actually be part of the replacement operation. 

~~The first modification would be to allow for negative filters, e.g. by prepending a - before the filter term (similar to how Beyond Compare does it). This would allow for a more detailed search operation. The term "*.c*;-*.cmd" would find any file that has an extension starting with the letter c, except of files with the extension "cmd".~~ _Edit: Apparently negative filters exist since v7.8.2, so this point is moot_

Negative filters by themselves are useful but do not address the binary file problem yet as it would be very cumbersome to exclude a lot of different extensions one by one.

So, I am suggesting an extended filter dialogue accessible via a button next to the "Filters" field in the Find in Files dialog. This would allow to write more complex filters without being limited to a single text line.

The dialogue has a few options:
* A list of filters to include, and a second list of filters to exclude 
* Each list contains a single filter element per row. 
* Closing the dialogue will translate the elements into a space-separated string like is currently accepted by the "Filters" field.
* The include/exclude lists can be pre-populated using a hard-coded list of common binary and non-binary extensions
* The dialogue has the option to parse the directory tree from the Find in Files dialogue, collecting all actually occurring extensions. These can then be transferred to the include or exclude list, possibly with the help of the hard-coded list of common formats.
* Entries can be moved from the include to the exclude list and vice-versa using buttons or drag/drop
* The hard-coded list of common binary/non-binary formats is stored in one or multiple text-based config files which allows users to trade or extend commonly considered extensions for different use cases.

I believe this extension will be powerful enough to exclude binary files relatively safely and transparently while hiding complexity enough so more casual users will not be overwhelmed.

**Comment by sasumner** [comment]
>The first modification would be to allow for negative filters, e.g. by prepending a...

This already exists, I believe the prepend characters is a `!`

**Comment by Cerno-b** [comment]
> 
> 
> > The first modification would be to allow for negative filters, e.g. by prepending a...
> 
> This already exists, I believe the prepend characters is a `!`

Thanks, I should have RTFM. ;) 
Interestingly, the feature is fairly new (about 9 months), maybe that's why I missed it.

The way this works seems a bit clunky and non-intuitive to me (you have to have a negative and a positive filter separated by a blank), but it works. Having a dialog to help crafting positive and negative filters might be a good addition to make it more intuitive. 

Of course the main point of the ticket was a dialog to help exclude binary files. Negative filters are just a step along the way, and thankfully, they already work.

**Comment by sasumner** [comment]
>you have to have a negative and a positive filter separated by a blank

Why is that "bad"?
Command lines have been doing that for, what, 50 years?
Sure, I'm not saying that a full-blown GUI implementation wouldn't be better, but for getting your point across (to the program), the syntax seems pretty OK.

**Comment by Cerno-b** [comment]
> > you have to have a negative and a positive filter separated by a blank
> 
> Why is that "bad"?
> Command lines have been doing that for, what, 50 years?
> Sure, I'm not saying that a full-blown GUI implementation wouldn't be better, but for getting your point across (to the program), the syntax seems pretty OK.

It may be a matter of taste and I may be ignorant of some previous standard, but I expected the filtering to be a little more elegant.

I was sort of expecting that I could just filter like "!*.txt" and get everything except txt files. Having to explicitly add the positive catch-all "!*.txt *.*" seemed redundant to me. 

I was also expecting something like "*.t*;!*.tx;" where each positive and negative filter is separated by a semicolon. To me, that's a cleaner, more elegant approach, as having two different separators (blank and semicolon) seems unnecessary. Having just one would yield the same expressivity I think. Also the strict separation into a positive and negative group is less flexible than it could be.

Not sure if it's possible to filter like this at the moment: "t* files but no tx* files but txt files. Having a list of positives and negatives interpreted from left to right would allow for that: " *.t*;!*.tx*;*.txt". If I understood the current filtering correctly, you can have exactly one group of positive filters and one group of negative filters. So having alternating positive and negative filters may be more powerful.

Again, it's likely a matter of taste and I don't want to push the issue, as my main concern is improving the usability of filtering binary files. If these thoughts make sense I could open a new issue as I would like to stay on topic here.

**Comment by sasumner** [comment]
>may be ignorant of some previous standard

I'd say you are.

>filter like "!.txt" and get everything except txt files

Maybe try: `!*.txt`

>Having to explicitly add the positive catch-all

You don't have to.

>"!.txt ."

A strange filter-spec, indeed.
Does it even work? Hmmm.

>two different separators (blank and semicolon)

Not sure I understand where the semicolon stuff is coming from.
Space is the only separator here.

>the strict separation into a positive and negative group

There is no strict separation concept, AFAIK.

>you can have exactly one group of positive filters and one group of negative filters

Not true.

>it's likely a matter of taste

Well, it is more than taste.
Implementers went for a syntax that could be expressed with brevity and with a minimal GUI.
And also feel familiar to core programmers (those "last 50 year" people).
Does it hit the sweet spot for everyone? Nope.
Does it seem to have you mystified? Yes.
Is it fairly useful for a text editor that isn't an awesome searcher? Possibly. :-)

>my main concern is improving the usability of filtering binary files...I would like to stay on topic here.

Well, I don't think a little diversionary discussion in the comments about something related that is clearly causing some users an extreme amount of trouble is going to derail the main point.

**Comment by XCanG** [comment]
Can you just add button `Complex Filter` which will open new popup with a followed settings:

This window split into **"AND"** and **"OR"** rules:

- **"AND"** rules will require to match for every rule present to be able to interact with this file later, **"OR"** rules will add file if at least one rule will match.

- Each individual rule can be negative, as said earlier, e.g. you set `*.txt` as negative, so it would include any file which is not have txt extension.

- With this window you will have buttons: **Add, Remove, Edit**.

- - **Remove** simply remove selected rule and **edit** allowing to make changes to it.

- - **Add** will have more options and be more complex: you can select which check it would use: **file name, file size, file date, content** of the file
- - - **file name** will work as usual for now, but you can checkmark easely to use it as negative rule
- - - **file size** you may add check min/max (one of them or both), e.g. drop any file which is more, than 512KB
- - - **file date** allow to check date ranges before/after (again one date or both), so you may only check files after e.g. `22.09.2020 00:00:00` _(I suggest add some sort of datetime picker, so users wont mess with format)_
- - - for **content** of the file you may write an regex, but I will even say what simply adding checking for range of characters is enough, so that with this rule: `[\x00-\x1F]` I can detect binary files and exclude them.

**Comment by wonkawilly** [comment]
Sorry for the OT, I'm also really sorry if I'm bothering you all, but maybe the participants to this thread would want to give their opinion about this new and rich proposal about the improvement of the Find and Replace dialog at this link: #9627. Which will be a great improvement and perhaps even a real game changer for all of us that use N++ for more advanced uses than just editing the shopping list.
Please partecipate and spread the word asking others to partecipate as well. More opinions are welcome. Thank you all.

**Comment by Cerno-b** [comment]
Sorry for the apparent bone-headedness. I wrote the previous comment from work and we are using version 7.8 where apparently you cannot use a negative filter without a positive filter. I tried it again with 7.9.1 and it works like you describe. Sorry for the confusion.

Interestingly, [the manual](https://npp-user-manual.org/docs/searching/) still reflects the old behavior, even though the tool seems to have changed:

> if you have at least one exclusion in your filter, you need to have at least one inclusion in your filter, otherwise it excludes files from the 0 matched inclusion files, resulting in no files matched, which probably isn’t what you want

I like the new behavior better, as it seems much more intuitive (just say what you don't want and have the search assume that you want to exclude from everything instead of nothing). When defining multiple filters, it seems the current behaviour is to apply all positive filters, then apply all negative filters not matter the order given. 

A different approach could be to apply the filters in order, so that `*.txt !*log.txt important_log.txt` will get you all `*.txt` files except the ones that end in `log.txt`, but it does give you `important.log.txt`. It would be slightly more powerful without restricting the current behavior (you'd just have to mind the order of your filters if you want the old behavior).

> having two different separators (blank and semicolon) seems unnecessary.

About this part, I have no clue what I was thinking, probably a brain fart, sorry.

> you can have exactly one group of positive filters and one group of negative filters

You said this is not true. What did I miss? I tried it and it seems like I can have multiple positive filters (one group) and multiple negative filters (a second group). You can give the individual filters in any order you like but it is my understanding that the tool will group them into positives and negatives and apply the positives first, then the negatives. If that is not true, I'd be interested in how the mechanism really works.

**Comment by Cerno-b** [comment]
@XCanG I like the idea because it hides all this complexity behind a single button which does not bloat the current search dialog and everyone can keep using the current behavior without interference. 

What I woud also love within this complex filters dialog is a preview of files found. So you start designing your filter, hit a button and the tool will populate a list of files that match your current query. This will give you an idea of whether you are going in the right direction with your complex search. This pre-population step would not necessarily have to into the files in order to speed up the search process.

When I use Notepad++ to search for contents of a larger directory, it always takes a long time, especially if binary files are involved, since the tool has to scan all the files for the content I am looking for. If I could instead get a list of files that match my current file filter without looking into the files, it would be much faster, because I could restrict the files I'm interested in and then start the process of scanning the files for content.

To me that would be a fairly helpful increase in productivity.

**Comment by mere-human** [comment]
There is a related issue https://github.com/notepad-plus-plus/notepad-plus-plus/issues/9445

**Comment by sasumner** [comment]
@Cerno-b said:

>What I woud also love within this complex filters dialog is a preview of files found. So you start designing your filter, hit a button and the tool will populate a list of files that match your current query. This will give you an idea of whether you are going in the right direction with your complex search. This pre-population step would not necessarily have to look into the files, which would significantly speed up the search process.

>When I use Notepad++ to search for contents of a larger directory, it always takes a long time, especially if binary files are involved, since the tool has to scan all the files for the content I am looking for. If I could instead get a list of files that match my current file filter without looking into the files, it would be much faster, because I could restrict the files I'm interested in and then start the process of scanning the files for content.

I can make no guarantees about something like this becoming a reality, but it would have the best chance if you create a new issue with only the above ideas (the ones I've quoted here) in it.

**Comment by sasumner** [comment]
@Cerno-b said:

>Interestingly, the manual still reflects the old behavior, even though the tool seems to have changed:

>>if you have at least one exclusion in your filter, you need to have at least one inclusion in your filter, otherwise it excludes files from the 0 matched inclusion files, resulting in no files matched, which probably isn’t what you want

We'll fix this; see https://github.com/notepad-plus-plus/npp-usermanual/issues/217

**Comment by sasumner** [comment]
@Cerno-b said:

>>you can have exactly one group of positive filters and one group of negative filters

>You said this is not true. What did I miss? 

I think what **_I_** misunderstood was what you meant by the notion of grouping.

**Comment by Cerno-b** [comment]
> I can make no guarantees about something like this becoming a reality, but it would have the best chance if you create a new issue with only the above ideas (the ones I've quoted here) in it.

Since https://github.com/notepad-plus-plus/notepad-plus-plus/issues/9445 (which was opened after this one) seems to carry a more fruitful and concrete discussion that the topic here, I'm in favor of closing this one and waiting for what solution (if any) for binary suppression will make it in the end. After this is done, I think I can re-evaluate whether I can see any benefit in having some sort of pre-search dialog for speed gains. I suspect that with a decent binary-suppression this will not be necessary anymore since the normal recursive search will be fast enough.

Thanks for your input. 👍
