### ISSUE TITLE
"Find in All" doesn't adjust if you edit the document

### ISSUE THREAD

**Issue by pgdownload** [notepad-plus-plus/notepad-plus-plus#8859]
### Description of the Issue

Notepad++ has a FIND IN ALL OPENED DOCS option. When you run it a new window opens at the base and a list of lines containing a match for each file is provided. When you double click any of those lines you will be jumped to the actual tab and location of the match (nice functionality btw!). Unfortunately if you edit a line (add, remove, change it) then the list doesn't update to reflect the change so if you double click on another match it will highlight a seemingly random point in the document.

### Steps to Reproduce the Issue

1. This issue only affects edits within a single TAB
2. Get a long file. 
3. Search a common term (USE FIND ALL IN OPEN DOCUMENTS)
4. Edit out some lines or add some lines
5. Double click the another MATCH listed and note you don't jump to the correct line

### Expected Behavior
Double click should jump to the line the MATCH is actually on now. Not what it was on.

### Actual Behavior
Double Click just used to same line number reported in the initial FIND IN ALL OPEN DOCUMENTS. 

IMO the found list should at least update the matched line if lines are added or removed. 
Ideally the position along the line should also be updated but that might be more difficult.
Unrelated but if the user deletes the MATCH phrase then the line item should also disappear from the match list.

[Find.zip](https://github.com/notepad-plus-plus/notepad-plus-plus/files/5222363/Find.zip)

### Debug Information
Notepad++ v7.8.9   (64-bit)
Build time : Jul 15 2020 - 20:31:49
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS Name : Windows 10 Pro for Workstations (64-bit) 
OS Version : 1909
OS Build : 18363.1016
Current ANSI codepage : 1252
Plugins : CodeAlignmentNpp.dll mimeTools.dll NppConverter.dll NppExport.dll

**Comment by sasumner** [comment]
Long-known behavior.
Workaround: Re-run the search.

**Comment by pgdownload** [comment]
I must say that Notepad++ is starting to lose its gloss for me. Its not a professional development sure, but stuff like this is not a difficult fix. Programs exist to assist users, not the other way around.

**Comment by sasumner** [comment]
>but stuff like this is not a difficult fix

Notepad++ accepts user-contributed code; perhaps you'd like to try your hand at fixing an easy one? :-)

Actually, my reason for replying was to point out the more common workaround, probably for other readers that find this:
When using search results to make edits in the document, work in a bottom-up fashion; that way the previously found positions remain valid for matches earlier in the document.
