### ISSUE TITLE
UAC support for saving files

### ISSUE THREAD

**Issue by dg9ngf** [notepad-plus-plus/notepad-plus-plus#886]
Notepad++ should ask me for elevated privileges when I don't have access to save a file to the selected location. Currently it suggests writing the file to the desktop instead, which is not useful because the file usually needs to be stored right there where I say (or where it was opened from).

Maybe this UAC dialog also applies to opening a file when I don't even have read access to it. Never had that situation though. I'm mostly writing to system configuration files.

I noticed the plugin "Save as admin" that claims to do the job but it doesn't do anything at all. I still get the same message with it. That plugin should probably be removed from the plugin manager because it hasn't been updated for years.

**Comment by jonandr** [comment]
Discussed in #334

**Comment by GitMensch** [comment]
Just for reference: SaveAsAdmin works perfectly for me and adds an UAC window, for example when writing the hosts file. If I neglect current NPP shows


~~~~
---------------------------
Save failed
---------------------------
The file cannot be saved and it may be protected.
Do you want to launch Notepad++ in Administrator mode?
---------------------------
Yes   No   
---------------------------
~~~~
