### ISSUE TITLE
Lexicographical line sorting is broken by different line ending types

### ISSUE THREAD

**Issue by nebosite** [notepad-plus-plus/notepad-plus-plus#8868]
### Description of the Issue
I have a file lines that mixed carriage return types (\r\n vs \n).   I have discovered that lexical sorting doesn't work properly with mixed types, it appears to not count one of the types as a true line break. 

### Steps to Reproduce the Issue

1.   Add some sortable lines to a file that are in reverse sort order, using CR LF pattern for line endings
2.   Change the line break between two of the lines to just LF
3.   Sort the file

### Expected Behavior
FIle should appear sorted

### Actual Behavior
The LF-only break is not actually treated as a new line so that part of the file won't sort correctly.  As a developer on windows,  I've been bitten by this problem MANY TIMES.   The sorter could at least notice the presence of CR LF line endings and assume that all naked LF are line endings as well.

**Comment by sasumner** [comment]
Closing; #7735 is the "master" issue about this "oddity".
If you want to test a possible solution, grab the .exe from PR #8673
