### ISSUE TITLE
Open hyperlinks in text

### ISSUE THREAD

**Issue by ygoe** [notepad-plus-plus/notepad-plus-plus#887]
Hyperlinks are permanently formatted with underlining and always have a different (configurable) text colour and a hand mouse cursor when hovered. This implies that I can always click on them to open them. But that's not the case. When I click on the link the text cursor is placed there, even though the mouse cursor has indicated another action. Control+click (like in Microsoft Word) doesn't change this and there's no context menu command either (like in TextPad). I found out that double-clicking the link opens it, but it also selects the entire line. So this has two actions when I certainly only wanted one of them. (In case of double-clicking that would be a word selection, not even a line selection.)

So I'm suggesting that the link is not opened on a double click but instead on a Ctrl+click. And probably, it should also only be formatted differently when hovered while the Ctrl key is pressed (like in Microsoft Productivity Power Tools for Visual Studio). Maybe a context menu command at the top of the menu would also be helpful. This should obviously only appear if the menu was opened on a link.

Update: The line selection behaviour is not reproducible. The second time I tried double-clicking a link, I only got word selection as well. From the third time on, nothing was selected at all anymore. Is there a countdown in this?

Update 2: Of course I got line selection again after submitting this... No countdown.

**Comment by h-h-h-h** [comment]
> Hyperlinks ... always have ... a hand mouse cursor when hovered

I agree it should only be the normal text cursor by default, for you can normally select text while having a hand cursor.

> Hyperlinks are permanently formatted with underlining ... probably, it should also only be formatted differently when hovered while the Ctrl key is pressed

It's very positive for me to have links formatted the whole time (underlined). The additional formatting should only be applied when being able to open the link, that is, with <kbd>Ctrl</kbd>+<kbd>Click</kbd>.

---

Additionally, there could be a tooltip when hovering a link that says: "Open with Ctrl+Click".

Being able to open a link with the keyboard is also desirable. <kbd>Ctrl</kbd>+<kbd>Enter</kbd> already has a meaning. What's a better choice? <kbd>Ctrl</kbd>+<kbd>Space</kbd>?

**Comment by dg9ngf** [comment]
Correction: I have found the option to disable link underlining. It's in the last options page. Links appear as normal text now (black, not underlined) and always change to blue, underlines when hovering. When clicking once, the format is reset and the cursor is placed in the link. When moving the mouse cursor a single pixel in any direction, the link is formatted again (blue, underlined). A bit inconsistent and very unintuitive.

It's still not possible (or I haven't found out how) to make all hyperlinks blue without hovering them.

I'm fine with the tooltip, Microsoft Word has it, too. Helps the user immediately.

No idea about the keyboard shortcut. Maybe a Ctrl+letter hotkey would be okay? Like Ctrl+L or so.

**Comment by h-h-h-h** [comment]
> It's still not possible (or I haven't found out how) to make all hyperlinks blue without hovering them.

That's a reasonable formatting while not hovering a link, too.

**Comment by MetaChuh** [comment]
we are closing this issue due to its age and multiple newer notepad++ versions since it was filed.

please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html).
if your issue persists, and it is still of relevance to you, please feel free to file a new issue.

thank you for your help and best regards.

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
```
[<kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd>](https://notepad-plus-plus.org/community/)
