### ISSUE TITLE
"Windows" Dialog: ⇵ displayed incorrectly with some fonts

### ISSUE THREAD

**Issue by Yaron10** [notepad-plus-plus/notepad-plus-plus#8870]
**STR:**
Use the "Tahoma" font system-wide.
Open the "Windows" dialog.

**Result:**
![תמונה](https://user-images.githubusercontent.com/10229320/93668391-a3e4b500-fa94-11ea-972f-3b98f532de60.png)

The `▽` and `△` characters are displayed correctly.
***
Notepad++ v7.9   (32-bit)
Build time : Sep 14 2020 - 22:58:18
Path : C:\---\notepad++.exe
Admin mode : ON
Local Conf mode : ON
OS Name : Windows 7 Enterprise (32-bit) 
OS Build : 7601.23964
Current ANSI codepage : 1255
Plugins : ComparePlus.dll HTMLTag_unicode.dll MenuIcons.dll PythonScript.dll _CustomizeToolbar.dll

**Comment by sasumner** [comment]
Probably similar to the "right arrow" thing in 8524 , see here for reference: https://github.com/notepad-plus-plus/notepad-plus-plus/issues/8524#issuecomment-691074788
I'm thinking it's probably best to stick with "ASCII" characters in these areas of the UI
:-(

**Comment by Yaron10** [comment]
@sasumner,

Sure.
Without your comment there, I would still have believed the "square" was the intended character. :)

Can you think of some alternative "ASCII" characters?

Isn't there an API for those elements including the arrows?
![תמונה](https://user-images.githubusercontent.com/10229320/93669168-b530c000-fa9a-11ea-972f-c9bf8342bb1c.png)

Thank you.

**Comment by sasumner** [comment]
>Isn't there an API for those elements including the arrows?

Yes, and that's probably the better solution here.

**Comment by Yaron10** [comment]
Great. :+1:

**Comment by donho** [comment]
@Yaron10 
> https://user-images.githubusercontent.com/10229320/93668391-a3e4b500-fa94-11ea-972f-3b98f532de60.png

Are you still using Windows XP ?

**Comment by Yaron10** [comment]
@donho,

No. I'm using Windows 7 + Windows Classic Theme.

**Comment by mere-human** [comment]
"Windows" dialog uses _MS Shell Dlg_ (or _MS Shell Dlg 2_ in case of Windows classic theme) virtual font which is substituted by some real font (e.g. _Microsoft Sans Serif_).
See: [WindowsDlg.rc](https://github.com/notepad-plus-plus/notepad-plus-plus/blob/master/PowerEditor/src/WinControls/WindowsDlg/WindowsDlg.rc#L35)
But _Microsoft Sans Serif_ doesn't support the Unicode character that is used in the header (U+21F5).
So, then the font linking is used.
Windows looks at `HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion\FontLink\SystemLink` and chooses a font that can represent a character.
If you add more fonts to that registry value, the character will be shown.
Here is what I've got after modifying that:
![Screenshot 2020-12-01 112449](https://user-images.githubusercontent.com/9664141/100721344-e5181000-33c7-11eb-9151-d3b186927d00.png)
Read more about the font linking here: https://docs.microsoft.com/en-us/globalization/input/font-technology

As an alternative, we can use a Unicode character that is supported by a more wide range of fonts (e.g. ⇅ - U+21C5 - Unicode v.1.1 1993) or even use 2 Unicode characters (↓↑- U+2193, U+2191). 
Compare that to the currently used character (⇵ - U+21F5 - Unicode v.3.2 2002).

What it looks like (Path column - alternative arrow character, Type column - 2 arrow characters):
1. Windows 10
![Screenshot 2020-12-01 113255](https://user-images.githubusercontent.com/9664141/100722858-c31f8d00-33c9-11eb-91ba-d49456f88bb6.png)
2. Windows 7 (Basic theme)
![Screenshot 2020-12-01 113731](https://user-images.githubusercontent.com/9664141/100722978-e5b1a600-33c9-11eb-9c78-5bb9747108eb.png)
3. Windows 7 (Windows Classic theme)
![Screenshot 2020-12-01 113657](https://user-images.githubusercontent.com/9664141/100723039-f3672b80-33c9-11eb-97b5-fa706950c380.png)

@donho @Yaron10  What do you think?

**Comment by sasumner** [comment]
I wasn't asked, but I think that in the Win 7 screenshots about (meaning 2. and 3.), the down and up arrows give an awkward feeling about how far apart they are.  :-)

**Comment by mere-human** [comment]
> @mere-human
> 
> I wasn't asked, but I think that in the Win 7 screenshots about (meaning 2. and 3.), the down and up arrows give an awkward feeling about how far apart they are. :-)

That is true. And as for me U+21C5 looks less terrible but still worse than U+21F5 in Windows 10.
At least, it is not a blank square:)

**Comment by donho** [comment]
I know it's lazy and mean, but I am happy to find this:
https://support.microsoft.com/en-us/windows/windows-7-support-ended-on-january-14-2020-b75d4580-2cc7-895a-2c9c-1466d9a53962#:~:text=The%20specific%20end%20of%20support,longer%20available%20for%20the%20product.

TBH, I don't want to make a compromise for this minor bug to supporting an unsupported OS.
Thank you @Yaron10 for opening this issue and @mere-human for providing the solution anyway.

**Comment by Yaron10** [comment]
@mere-human,

Thank you for looking into it and for the fonts tip.

@donho,

A minor issue. No problem.
