### ISSUE TITLE
[Feature Request] Reload all files from disk

### ISSUE THREAD

**Issue by e2m32** [notepad-plus-plus/notepad-plus-plus#8879]
### Description of the Issue

Npp allows you to easily reload files from the disk using the keyboard shortcut `Ctrl+R` and it is also good as knowing when the file that is open has been updated from another program and prompts the user if they want to reload it. This is great, but annoying if you have 10+ files open. Would be awesome if `Ctrl+Shift+R` would reload all currently open files. Also, the popup window asking to reload could include an option to "Reload All Open Files" from disk.
![image](https://user-images.githubusercontent.com/10486510/93820364-112a4e80-fc2b-11ea-8918-6853570d99de.png)

**Comment by sasumner** [comment]
Going with your train of thought, the prompt box could have the following choices:

* Yes
* No
* Yes to All
* No to All
* Close
* Close All (detected as externally modified)

**Comment by e2m32** [comment]
That would work. 6 options are a bit much though. Probably don't need the close buttons, `Ctrl+Shift+W` already will allow you to close all. IMHO. My original thought was to just add `Yes to All`, but preventing that pop-up on other open files with `No to All` is a good idea.

**Comment by sasumner** [comment]
>Probably don't need the close buttons,

See the now-linked issue #8842

>Probably don't need the close buttons, Ctrl+Shift+W already will allow you to close all. 

I'm confused by this.
On one hand you are talking about "in dialog" behavior, and on the other (the keycombo) you are talking about "not in dialog" behavior.
You don't have both at the same time.
Here's an example to hopefully clarify:  Four files open, two get externally modified.  You want to close all of the externally modified.  Maybe you cancel all current prompt boxes.  Now you do your Ctrl+Shift+w but it closes all 4 files, not just the 2 modified ones whose editor content you now want to discard.

**Comment by e2m32** [comment]
> > Probably don't need the close buttons,
> 
> See the now-linked issue #8842

Ahh, I see. I'm not as annoyed by this, but can see the benefit. 

> > Probably don't need the close buttons, Ctrl+Shift+W already will allow you to close all.
> 
> I'm confused by this.
> On one hand you are talking about "in dialog" behavior, and on the other (the keycombo) you are talking about "not in dialog" behavior.
> You don't have both at the same time.
> Here's an example to hopefully clarify: Four files open, two get externally modified. You want to close all of the externally modified. Maybe you cancel all current prompt boxes. Now you do your Ctrl+Shift+w but it closes all 4 files, not just the 2 modified ones whose editor content you now want to discard.

I misunderstood the `Close' button behavior. I was thinking that with `Close All`, N++ would just blindly close out all files in the session regardless of the file being externally modified. So I just saw this as duplicate functionally as the key combo (or dropdown option).

**Comment by donho** [comment]
> Going with your train of thought, the prompt box could have the following choices:
Yes
No
Yes to All
No to All
Close
Close All (detected as externally modified)

I can see the logic behind... but no, it's just too much (too many buttons)

**Comment by donho** [comment]
> Npp allows you to easily reload files from the disk using the keyboard shortcut Ctrl+R and it is also good as knowing when the file that is open has been updated from another program and prompts the user if they want to reload it. This is great, but annoying if you have 10+ files open. Would be awesome if Ctrl+Shift+R would reload all currently open files. Also, the popup window asking to reload could include an option to "Reload All Open Files" from disk.

When I consider this feature request, I think it's just a redundant feature: by default "auto-detect file status" is enable, that means when you switch to a document which has been modified outside, you'll get alert. "Reload from disk" is only for the current working file which is not "aware" of the change from outside.
So we don't need at all "Reload all files from disk" feature.

**Comment by Sorontik** [comment]
To reduce the complexity (and button count), how about switching to a Radio-List for the general options combined either
- with a checkbox for the "for all"-choice and an "Apply" Button or
- with an "Apply" button and an "apply to all" button

like

```
What do you want to do?

O Reload the file (discarding unsaved changes)
O Keep the file
O Close the file (discarding unsaved changes)

[ ] Apply to all changed files

[Apply]
```
or
```
What do you want to do?

O Reload the file (discarding unsaved changes)
O Keep the file
O Close the file (discarding unsaved changes)

 [Apply to all changed files]       [Apply only to this file]
```

This solution is also quite common for similar problems/questions in other programs (like overwrite/rename/cancel for file copying conflicts and stuff like that) so i think most NPP users would already be familiar with the concept.
