### ISSUE TITLE
Loading of .NFO file causes Np++ to crash with installed NppHexEditor plugin

### ISSUE THREAD

**Issue by deus-e-x** [notepad-plus-plus/notepad-plus-plus#8884]
### Description of the Issue
With the plugin NppHexEditor installed, loading of any file with the file extension '.nfo' results in a crash of Np++. Removing the plugin NppHexEditor, files with a '.nfo' file extension load without any issue.

Note that the crash is not triggered due to any file content, but by the use of the file extension '.nfo' alone.

### Steps to Reproduce the Issue

1. Install the plugin NppHexEditor, available from: https://github.com/chcg/NPP_HexEdit/releases
2. Rename the file extension of any text file to '.nfo'
3. Trying to load the .nfo-file results in Np++ to crash

### Expected Behavior
Text files with the file extension '.nfo' should load in Np++ without causing a crash.

### Debug Information
Notepad++ v7.9 RC3 (32-bit)
Build time : Sep 22 2020 - 03:24:22
Path : C:\Program Files (x86)\Total Commander\util\notepad++\notepad++.exe
Admin mode : ON
Local Conf mode : ON
OS Name : Windows 10 Enterprise (64-bit) 
OS Version : 2004
OS Build : 19041.508
Current ANSI codepage : 1252
Plugins : ChangedLines.dll v0.2.3.2,  ColumnTools.dll v1.3.7.1,  HexEditor.dll v0.9.7, NppTextFX.dll v0.2.6

Related discussion on the Notepad++ forum: https://community.notepad-plus-plus.org/topic/20031/notepad-7-9-rc3/4?_=1600786273182#

**Comment by donho** [comment]
I have also installed HexEditor.dll v0.9.7. However, I cannot reproduce the crash.
Please provide more accurate instructions for reproducing it.

**Comment by donho** [comment]
Maybe your nppHexEdit.ini can help to reproduce it.

**Comment by ArkadiuszMichalski** [comment]
@deus-e-x  Also no crash for me, maybe can you check this in fresh portable 7.9 RC3 only with HexEditor.dll v0.9.7?

**Comment by vinsworldcom** [comment]
Also confirm no crash with Windows 10 64-bit, 7.9 RC3 and HexEdit 0.9.7.  Older versions of Hex Edit caused the crash when opened from command line.  This does not seem to be a Notepad++ bug, rather HexEdit plugin related.  Surely not a regression?

Cheers.

**Comment by donho** [comment]
@deus-e-x 
For me it crashes on the startup time.
I managed to prevent HexEdit from crashing, can you test the binary?
[HexEditor.zip](https://github.com/notepad-plus-plus/notepad-plus-plus/files/5263116/HexEditor.zip)

**Comment by deus-e-x** [comment]
Sorry to keep you guys waiting. Because of all your comments (A huge thank you for that!) I did some further tests with a fresh local install of Np++, no config.ini, and NppHexEdit being the only installed plugin:

- if you load an .nfo-file from within an already running Np++, no crash occurs
- if you startup Np++ with a .nfo-file as the command line argument, a crash occurs

**Comment by ArkadiuszMichalski** [comment]
@deus-e-x How exactly you run with command line? I still can't reproduce:)

**Comment by deus-e-x** [comment]
@donho

Hi Don. I can confirm, the binary you provided does not produce a crash. Great job!

**Comment by deus-e-x** [comment]
> @deus-e-x How exactly you run with command line? I still can't reproduce:)

<path>\Notepad++.exe <filename.nfo>

**Comment by ArkadiuszMichalski** [comment]
OK, I'm out, no problem for me, maybe related to Win10, but good that it was fixed, there were a few issues with this in the forum.

**Comment by deus-e-x** [comment]
@ArkadiuszMichalski

Usually, I start up Np++ from within a file manager with a file as a command-line argument. But the logic behind should be the same. Funny, that you cannot reproduce it on Windows 7?
