### ISSUE TITLE
[Feature Request] Function List Escape treeview to Notepad++ edit window

### ISSUE THREAD

**Issue by vinsworldcom** [notepad-plus-plus/notepad-plus-plus#8886]
### Description of the Issue

When using the built-in Function List (View menu => Function List), the Escape key in the Function List TreeView should leave Function List and return to the active Notepad++ Scintilla edit window.

Tested on the latest repo, add [here](https://github.com/notepad-plus-plus/notepad-plus-plus/blob/95dec01e27717028bf6f50491f28e4b031a5f6b1/PowerEditor/src/WinControls/FunctionList/functionListPanel.cpp#L578)

```
diff --git a/PowerEditor/src/WinControls/FunctionList/functionListPanel.cpp b/PowerEditor/src/WinControls/FunctionList/functionListPanel.cpp
index 1899963b..3879f572 100644
--- a/PowerEditor/src/WinControls/FunctionList/functionListPanel.cpp
+++ b/PowerEditor/src/WinControls/FunctionList/functionListPanel.cpp
@@ -575,6 +575,11 @@ void FunctionListPanel::notified(LPNMHDR notification)
                                        }
                                        PostMessage(_hParent, WM_COMMAND, SCEN_SETFOCUS << 16, reinterpret_cast<LPARAM>((*_ppEditView)->getHSelf()));
                                }
+
+                               else if (ptvkd->wVKey == VK_ESCAPE)
+                               {
+                                       PostMessage(_hParent, WM_COMMAND, SCEN_SETFOCUS << 16, 0);
+                               }
                        }
                        break;
                }
```

Cheers.

**Comment by sasumner** [comment]
How about doing a PR?

**Comment by vinsworldcom** [comment]
I'd like to, but it seems my troubleshooting of adding a MessageBox() before the PostMessage was making this work - without it, the pressing the Escape key just rings the default system bell sound and doesn't change focus.  Seems the PostMessage() may not be the best way to set focus to the Notepad++ current Scintilla edit window.  Don't know the code base well enough to change that command to the required SetFocus().

Cheers.

**Comment by vinsworldcom** [comment]
Ok - I think I got it .. standby for PR.

**Comment by MAPJe71** [comment]
There was already a [commit](https://github.com/notepad-plus-plus/notepad-plus-plus/commit/f3fce2de4a5bf17143af9df31e67f4162d215f70) to solve the "bell" sound issue.

**Comment by vinsworldcom** [comment]
This isn't about the bell. In fact there is still a bell when pressing
Enter on a Function List item.  This is about Escape key functionality in
the Function List treeview (the other dealt with Escape key in Function
List search edit box).

Cheers.

**Comment by sasumner** [comment]
@MAPJe71 The commit you referenced is for a different errant bell.  The one I introduced. :-)
