### ISSUE TITLE
A macro recorded with a "Find All in Current Document" has no effect

### ISSUE THREAD

**Issue by geodule** [notepad-plus-plus/notepad-plus-plus#8889]
### Description of the Issue
I can successfully playback a macro recording a simple "Find Next" search.
The playback of a macro recording a "Find All in Current Document" search has no effect.

### Steps to Reproduce the Issue
1. Open any text document.
2. In "Macro" menu, select "Start recording" item.
3. In "Search" menu, select "Find..." item to open the "Find" window.
4. In the "Find" window, type "test" in "Find what" text field and click "**Find All in Current Document**" button. **The search result is reported in the "Find result" panel .**
5. In "Macro" menu, select "Stop recording" item.
6. In "Macro" menu, select "Playback" item to **launch the recorded macro**.

### Expected Behavior
When I launch the recorded macro, I expect to have the search result reported in the "Find result" panel.

### Actual Behavior
When I launch the recorded macro nothing happens.

### Debug Information
Notepad++ v7.5.6   (64-bit)
Build time : Mar 19 2018 - 00:23:17
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10 (64-bit)
Plugins : ComparePlugin.dll DSpellCheck.dll mimeTools.dll NppConverter.dll

**Comment by sasumner** [comment]
@geodule 
Your N++ is over two years old.  Please update to latest s/w before reporting issues.
A fix for this issue was done based upon issue #5973 and PR #6006 and was released in Notepad++ 7.8.
