### ISSUE TITLE
[Enhancement] Search Results Window keyboard close

### ISSUE THREAD

**Issue by vinsworldcom** [notepad-plus-plus/notepad-plus-plus#8892]
### Description of the Issue

There is no way to close the Search => Search Results Window from the keyboard.  One must use the mouse to hit the red X button to close the window.

There is a right-click context menu to which "Close" could be added.  My preference is a keyboard stroke - the Escape key should close the window.

I've done some testing in the FindReplaceDlg.cpp file, but I don't understand the code well enough.

```
notepad-plus-plus\PowerEditor\src\ScitillaComponent\FindReplaceDlg.cpp
3192:	LRESULT FAR PASCAL FindReplaceDlg::finderProc(HWND hwnd, UINT message, WPARAM wParam, LPARAM lParam)
3193:	{
3194:		if (message == WM_KEYDOWN && (wParam == VK_DELETE || wParam == VK_RETURN || wParam == VK_ESCAPE))
3195:		{
3196:			ScintillaEditView *pScint = (ScintillaEditView *)(::GetWindowLongPtr(hwnd, GWLP_USERDATA));
3197:			Finder *pFinder = (Finder *)(::GetWindowLongPtr(pScint->getHParent(), GWLP_USERDATA));
3198:			if (wParam == VK_RETURN)
3199:				pFinder->gotoFoundLine();
     				else if (wParam == VK_ESCAPE)
     				{
     					pFinder->setClosed(TRUE);
     					pFinder->destroy();
     				}
3200:			else // VK_DELETE
3201:				pFinder->deleteResult();
3202:			return 0;
3203:		}
```

Does not work.

Cheers.

**Comment by ArkadiuszMichalski** [comment]
@vinsworldcom some discuss for this https://github.com/notepad-plus-plus/notepad-plus-plus/issues/2946.

**Comment by vinsworldcom** [comment]
Closing - duplicate of #2946 and I added my comments there.

**Comment by sasumner** [comment]
>There is a right-click context menu to which "Close" could be added. My preference is a keyboard stroke - the Escape key should close the window.

There is no _Close_ there by design.
If you open a _Find in these found results_ search, that _will_ have a _Close_ option on it.

This (the issue) is something that gets brought up often, and always seems to be declined, so I wouldn't have much hope for it.  Here's another one:  #7766

You can always script a solution, see here:  https://community.notepad-plus-plus.org/topic/14130/hide-or-toggle-find-results-panel-with-keyboard-command

**Comment by ArkadiuszMichalski** [comment]
But `Esc` has positive reactions https://github.com/notepad-plus-plus/notepad-plus-plus/issues/2946#issuecomment-645033294, which @vinsworldcom basically wants.

**Comment by sasumner** [comment]
>But Esc has positive reactions...

Ah, well apparently that had no follow-thru to it, by those discussing it...
