### ISSUE TITLE
Create new Margin/Border/Edge sub-page in Preferences

### ISSUE THREAD

**Issue by sasumner** [notepad-plus-plus/notepad-plus-plus#8896]
### Description of the Issue

The _Preferences_ sub-page labelled _Editing_ is getting a bit crowded.
Let's create a new sub-page and call it _Margin/Border/Edge_ and move the appropriate _Editing_ items there.
The gain will be that both sub-pages will then have a lot of room for future expansion.

For reference, see here: https://github.com/notepad-plus-plus/notepad-plus-plus/pull/8822#issuecomment-698473218
And here: https://github.com/notepad-plus-plus/notepad-plus-plus/pull/8822#issuecomment-698491562

The above is based upon _Preferences_ UI in Notepad++ version 7.8.9

**Comment by sasumner** [comment]
@donho 

To achieve this is it OK to reassign numbering in `preference_rc` and then `english.xml` ?
My thinking was to create this:

```
#define IDD_PREFERENCE_MARGINSBORDEREDGE_BOX 6950 //(IDD_PREFERENCE_BOX + 950)
```

and move the appropriate items under that (to create the new subpage item IDs).  They would obviously get new numbers starting at 950.  This would change numbering of existing items (that get moved to new subpage) in `english.xml`.

That would leave this in the old location:

```
#define	IDD_PREFERENCE_EDITING_BOX 6200 //(IDD_PREFERENCE_BOX + 200)
	#define	IDC_CHECK_CURRENTLINEHILITE (IDD_PREFERENCE_EDITING_BOX + 14)
	#define	IDC_CHECK_SMOOTHFONT (IDD_PREFERENCE_EDITING_BOX + 15)
	#define	IDC_CARETSETTING_STATIC (IDD_PREFERENCE_EDITING_BOX + 16)
	#define	IDC_WIDTH_STATIC (IDD_PREFERENCE_EDITING_BOX + 17)
	#define	IDC_WIDTH_COMBO (IDD_PREFERENCE_EDITING_BOX + 18)
        ...
```

Note: `IDD_PREFERENCE_EDITING_BOX` is a new name for an existing "box".  Changing this because the current name involves "margin".

Should those be left as they are (starting at 14, 15, ...) to minimize impact to `english.xml`?
I'm thinking the answer is YES.

**Comment by sasumner** [comment]
@donho "Assigned you" to get your attention.  I know you monitor PRs really well, but not sure about "issues".

**Comment by donho** [comment]
> I know you monitor PRs really well, but not sure about "issues".

You're right about my issue about "issues" :) 

> To achieve this is it OK to reassign numbering in preference_rc and then english.xml ?

We don't need to change `preference_rc.h` because all we need is a unique ID, and it's done.
And it will be simpler for the translators who maintain localization files - all they need to do is create a new node and cut/paste the items. As you can see in `english.xml` file, they all mix the different ID prefix.

**Comment by sasumner** [comment]
@donho 

>We don't need to change preference_rc.h

Here's a strong reason to change a small portion of `preference_rc.h`:

Currently the "Editing" category of the _Preferences_ is referenced with this tag:

```
IDD_PREFERENCE_MARGEIN_BOX
```

I propose renaming this to:

```
IDD_PREFERENCE_EDITING_BOX
```

Because with the _addition_ of a new page that involves margin, leaving the `IDD_PREFERENCE_MARGEIN_BOX` alone would leave things very confusing!

The new "box" that is going to be added will be called:

```
IDD_PREFERENCE_MARGINSBORDEREDGE_BOX
```

**Comment by donho** [comment]
OK, please change the symbol name only, don't touch the ID.

**Comment by donho** [comment]
@sasumner Have you already started this issue?
If you've not started it yet, I can take this issue.

**Comment by sasumner** [comment]
@donho Sorry, I have not started it yet.  You may take it.

**Comment by donho** [comment]
@sasumner Sorry for bothering. Could you remind me the decision of the addition option? Has this option been done?

**Comment by sasumner** [comment]
@donho Not sure I know what you mean.
Maybe this?:

In the code the current "Editing" subpage of "Preferences" is referred to with `IDD_PREFERENCE_MARGEIN_BOX`.
This is fine until this issue adds a new subpage called "Margins/Border/Edge".
It needs a IDD_ name as well, maybe `IDD_PREFERENCE_MARGINBORDEREDGE` ?
But that would mean we'd have `IDD_PREFERENCE_MARGEIN_BOX` and `IDD_PREFERENCE_MARGINBORDEREDGE`.
So it would be confusing as to which one involves "margins".
I was proposing renaming the existing one to `IDD_PREFERENCE_EDITING_BOX` to avoid that future confusion.

Hopefully that explanation helps?

**Comment by donho** [comment]
@sasumner 
I'm talking about "Line count based margin width" option:
https://github.com/notepad-plus-plus/notepad-plus-plus/pull/8822#issuecomment-697336479

Has this option been added into master?

**Comment by sasumner** [comment]
>Has this option been added into master?

No.
(It can be ignored for doing this current issue)

That one started out fairly simple, then all the discussion about it made it complicated.  :-(
I still consider it something that I have to work on.

**Comment by donho** [comment]
@sasumner 
In https://github.com/notepad-plus-plus/notepad-plus-plus/pull/8822, marked "Fixes #5670", so has #5670 been fixed? Can I close it?

**Comment by donho** [comment]
Never mind, I remember the context now - it's to be implemented.

**Comment by sasumner** [comment]
>In #8822, marked "Fixes #5670", so has #5670 been fixed? Can I close it?
>Never mind, I remember the context now - it's to be implemented.

This brings up an awkward moment for me.
I don't really have enthusiasm for finishing 5670 the way it was spec'd out by group effort in 8822.
This is mainly because I believe my original solution was the correct one (sorry).
Maybe you can take it over and finish it as you like?
Again, apologies for appearing to commit to it, and now backing down.

**Comment by donho** [comment]
@sasumner 
> I don't really have enthusiasm for finishing 5670 the way it was spec'd out by group effort in 8822.
This is mainly because I believe my original solution was the correct one (sorry).
Maybe you can take it over and finish it as you like?
Again, apologies for appearing to commit to it, and now backing down.

No problem at all. I will take this issue.
(Don't feel sorry about it - we are here for fun - at least I'm)

**Comment by sasumner** [comment]
>we are here for fun

Yes, it is nice to get to **_choose_** what to donate your time to work on.
This is much different than the "day job"; no choices (but no donation!) there!
