### ISSUE TITLE
autocomplete box steals cursor focus

### ISSUE THREAD

**Issue by linuxmasta** [notepad-plus-plus/notepad-plus-plus#890]
I'd like to retain autocomplete's auto-reveal, but perhaps it would be better to require me to press 'tab' to move focus into the listbox.

Currently any time autocomplete reveals, arrow keys are intercepted, preventing me from moving the cursor without pressing 'escape' or something after I've completed typing a, e.g., variable that it still thinks I'm not done typing.

'Activation to interact' instead of 'forced interaction requiring deactivation' [aka 'escape'] would be a wiser design decision.

**Comment by h-h-h-h** [comment]
> I'd like to retain autocomplete's auto-reveal, but perhaps it would be better to require me to press 'tab' to move focus into the listbox.

> Currently any time autocomplete reveals, arrow keys are intercepted, preventing me from moving the cursor without pressing 'escape'

This is normal for an IDE. Thus it's no wonder for such an IDE-like feature. But because Notepad++ is not so clever as IntelliSense and the like, maybe the arrow keys could be reserved for navigation while <kbd>Ctrl</kbd>+<kbd>Up</kbd>/<kbd>Down</kbd> is intercepted to navigate in the list.

**Comment by sanastasiou** [comment]
In Visual Studio up/down is used to navigate the list. Pressing left/right immediately closes the list.

**Comment by MetaChuh** [comment]
we are closing this issue due to its age and multiple newer notepad++ versions since it was filed.

please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html).
if your issue persists, and it is still of relevance to you, please feel free to file a new issue.

thank you for your help and best regards.

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
```
[<kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd>](https://notepad-plus-plus.org/community/)

**Comment by lmstearn** [comment]
Understand this is closed, just worth a mention for anyone experiencing up and down cursor "stuck" at EOL while editing language files (AHK here), it dawned on me that it occurred sometime after enabling autocomplete, or doing something to get it working properly. For some reason, some "artifact" of the autocomplete listbox may still be present when pressing the `END` key.. So not really a problem with N++ or the keyboard or the cursor interface.
