### ISSUE TITLE
Notes for updating N++'s Scintilla beyond 4.2.0

### ISSUE THREAD

**Issue by sasumner** [notepad-plus-plus/notepad-plus-plus#8900]
Notepad++ 7.8.9 (current version as of this writing) uses Scintilla version 4.2.0.

Yesterday, I build Scintilla 4.4.4 for Notepad++.
4.4.4 was chosen as it is one version behind current Scintilla release (as of this writing), to avoid possible unknown issues with the very latest release.

Also yesterday, @donho hinted that Scintilla might be updated (for real) in Notepad++ soon; see here:
https://github.com/notepad-plus-plus/notepad-plus-plus/issues/8110#issuecomment-698698135

This issue is being opened to document some discoveries I made in my trial migration of N++'s Scintilla from 4.2.0 to 4.4.4.  This info may be useful when the real migration is conducted, to whatever version of Scintilla is decided upon to move to.

------------------------------------------

In the `nppSpecifics.mak` file :

* Need to change `SOBJS` to `SRC_OBJS`
* Need to change `INCLUDEDIRS` to `INCLUDES`

**Comment by sasumner** [comment]
I was disappointed to learn recently that the appveyor build of SciLexer does not include the boost support.
I wonder if there is an easy way to add it in?
I don't suggest to build boost from source with each appveyor build, but perhaps a prebuilt constant version lib could be included.
This would also be a way of knowing which version of boost is used in a specific version of Notepad++.
Currently, I don't think there is any way to know which version of boost is used?

**Comment by sasumner** [comment]
N++ Scintilla-related code changes that may want to use in a N++ Scintilla update:

* https://github.com/notepad-plus-plus/notepad-plus-plus/pull/9030

**Comment by sasumner** [comment]
Partial list of things that may be fixed with a Scintilla upgrade:

* 4K monitor issue: https://community.notepad-plus-plus.org/topic/20174/problem-with-cursor-position/

**Comment by donho** [comment]
@sasumner 

> This would also be a way of knowing which version of boost is used in a specific version of Notepad++.
Currently, I don't think there is any way to know which version of boost is used?

Indeed, there's no way to know used boost version currently.


> I was disappointed to learn recently that the appveyor build of SciLexer does not include the boost support.
I wonder if there is an easy way to add it in?

It's a big question. It means we may include boost as sub-module in Notepad++ project, or include boost-regex static library in Notepad++ repository.

> I don't suggest to build boost from source with each appveyor build, but perhaps a prebuilt constant version lib could be included.

I think it's a good compromise. However, is there a way more elegant other than put compiled boost-regex static library in the repository ?

**Comment by ArkadiuszMichalski** [comment]
https://github.com/notepad-plus-plus/notepad-plus-plus/issues/7525 << another bug about changes in Scintilla.

**Comment by sasumner** [comment]
>include boost as sub-module in Notepad++ project

This means as a DLL file?

>a way more elegant other than put compiled boost-regex static library in the repository ?

I think that to do this the choices are a DLL in the repository or a LIB in the repository.
Would it be OK to Boost licensing to do that?

If that is done, it would be nice if the version number of the Boost could be attached to it in some meaningful way.

I don't have good answers here, just questions.

**Comment by chcg** [comment]
I would be possible to use the prebuild nuget boost packages from https://www.nuget.org/packages/boost_regex-vc141/. Previously the scintilla https://github.com/notepad-plus-plus/notepad-plus-plus/blob/master/scintilla/win32/SciLexer.vcxproj was changed to support that, see https://github.com/notepad-plus-plus/notepad-plus-plus/commit/fdd2dbc21fb0de8f1ed90cda11f5169d20258c81#diff-85b945d8756c8223885ade8c8ca88409d2eed9459504dc93eed690d65137ae6f

**Comment by sasumner** [comment]
>prebuild nuget boost packages

This sounds good.
Can you specify which version you want, or is it always a "you get the latest/current" type of thing?

Specifying the version would be best:
* more control
* easy to identify (thru how you specify) which Boost version is used in which version of Notepad++

**Comment by chcg** [comment]
The version could be specified, latest at nuget for the regex package is https://www.nuget.org/packages/boost_regex-vc141/1.72.0

The source code itself is also available at appveyor, see https://www.appveyor.com/docs/windows-images-software/#boost. But I'm not sure if building of just the regex package is also possible by boost bjam.

Another interesting option would be to build link scintilla libs statically on Appveyor with N++ to avoid the issues with the key signing.

**Comment by donho** [comment]
> Another interesting option would be to build link scintilla libs statically on Appveyor with N++ to avoid the issues with the key signing.

@chcg  Good point.

@sasumner Code signing indeed is a real problem. Even the boost issue is solved, Notepad++ cannot load compiled SciLexer.dll  once it's not signed.

I will try to make static link to Scintilla in the future.

**Comment by cesarmarcanove** [comment]
The Scintilla homepage says launched version 5.00 from: [https://www.scintilla.org/](https://www.scintilla.org/)

The new version 5.00 released 
`Version 5.0.0 is an unstable release with lexers unbundled.`

Confirmed compiled by VB2017 (or newer) and affected by new version Notepad++ v7.9.3, could be a 2020 version of Visual Basic (VB2020) and doesn't  suitable for a older Windows XP, says as:
`Current development occurs on the default branch as 5.* which requires a recent C++ compiler that supports C++17 .`

**Comment by sasumner** [comment]
>Version 5.0.0 is an unstable release with lexers unbundled.

So what @cesarmarcanove are you saying with your comment?
Notepad++ doesn't have interest in an "unstable release" of Scintilla.
