### ISSUE TITLE
Find All in All Opened Documents will not find all matches

### ISSUE THREAD

**Issue by vladob54** [notepad-plus-plus/notepad-plus-plus#8901]
### Description of the Issue

The issue seems to have been introduced by the version 7 of Notepad++.

If more than two files are open at once, and the "Find All in All Opened Documents " function is invoked, accented characters are not matched in some of the files.

The screenshot displays the result of looking for the "í" character (lowercase letter i with acute accent) in three small files, where all of them do contain at least one occurrence of that character. 

![image](https://user-images.githubusercontent.com/11799185/94311834-2f21e700-ff7c-11ea-8595-9459eb17144f.png)

### Steps to Reproduce the Issue

1. Open the three attached files. 
2. Try to find the "í" character in all of them by means of the Find All in All Opened Documents function.

### Expected Behavior

Matches in all three files should have been found.

### Actual Behavior

Only matches in the first and the third file have been found.

[o1.txt](https://github.com/notepad-plus-plus/notepad-plus-plus/files/5285141/o1.txt)
[o2.txt](https://github.com/notepad-plus-plus/notepad-plus-plus/files/5285142/o2.txt)
[o3.txt](https://github.com/notepad-plus-plus/notepad-plus-plus/files/5285143/o3.txt)

### Debug Information

Notepad++ v7.8.9   (64-bit)
Build time : Jul 15 2020 - 20:31:49
Path : C:\_bin\npp\notepad++.exe
Admin mode : OFF
Local Conf mode : ON
OS Name : Windows 10 Home (64-bit) 
OS Version : 1909
OS Build : 18363.1082
Current ANSI codepage : 1250
Plugins : mimeTools.dll NppConverter.dll NppExport.dll

**Comment by sasumner** [comment]
While attempting to reproduce, I obtain almost the same result.
I get `13 hits in 2 files of 3 searched`, not `12 hits`.

However, if I initiate the search with `o3.txt` as the current document, I obtain:

`15 hits in 3 files of 3 searched`

So, this is interesting...
It also feels familiar to another issue reported in that past...

**Comment by sasumner** [comment]
Perhaps it is worth noting that the detected encoding for all 3 of the OP's files, when these files get opened by Notepad++, is ANSI

Perhaps that has something to do with it; perhaps not...

**Comment by sasumner** [comment]
If I open all 3 of these files into Notepad++, but only "visit" `o1.txt`, the indicated search will only look at that one file.

If I then "visit" `o2.txt` and return to `o1.txt` and run the search, then it will see 2 of the 3 files.

If I "visit" `o3.txt` and return...then I will get 3 files with hits in the search.

**Comment by ArkadiuszMichalski** [comment]
I convert them to Unicode and works fine 15/3/3.

**Comment by sasumner** [comment]
>I convert them to UTF-8 and works fine

Umm, well, that's fine...except they aren't UTF-8 files, they are ANSI-encoded.

**Comment by ArkadiuszMichalski** [comment]
> Perhaps it is worth noting that the detected encoding for all 3 of the OP's files, when these files get opened by Notepad++, is ANSI
> 
> Perhaps that has something to do with it; perhaps not...
Now it's clear.

**Comment by sasumner** [comment]
I feel really strongly that this is going to be related:
https://github.com/notepad-plus-plus/notepad-plus-plus/commit/c5a0ed7c1aaac56dc96deabba8dd5e7cba261b2d

**Comment by vladob54** [comment]
Dear All,
    
    
    
      
      
        I convert them to UTF-8 and works fine
      
      Umm, well, that's fine...except they aren't UTF-8 files, they
        are ANSI-encoded.
    
    Yes, using UTF-8 encoding could solve the problem.  We use ANSI
      encoding partially for historical reasons (our project has started
      some 30 years ago) and also because some of the Windows command
      line tools, such as grep, are not compatible with UTF-8...
    Best,
    
    Vlado B, 19:30
    
    
    
    -- 
      Vladimír Benko
      
        Slovak Academy of Sciences
        Ľ. Štúr Institute of Linguistics
        Panská 26, SK-81101 Bratislava
      
        Tel +421-2-54431762 Fax -54431756
      
        http://aranea.juls.savba.sk/guest/
        https://www.facebook.com/araneawebcorpora/

**Comment by sasumner** [comment]
>using UTF-8 encoding could solve the problem

Well, it could solve the problem for you, potentially.
And if you aren't forced for some reason to stay with ANSI then yes 100% move to UTF-8.
But, it won't solve the problem for the next person that has to use ANSI and encounters the same issue.

**Comment by donho** [comment]
That's what I've got:
![image](https://user-images.githubusercontent.com/90293/94996112-e46b2500-05a2-11eb-81b6-e3b6427345e5.png)

Where is the bug?

**Comment by ArkadiuszMichalski** [comment]
You don't change tab? Try close all and open 3 in same time, or with session, like here https://github.com/notepad-plus-plus/notepad-plus-plus/issues/8901#issuecomment-699546186.

**Comment by donho** [comment]
@ArkadiuszMichalski Thank you - can reproduce now.
