### ISSUE TITLE
Disable the sound from the Search function

### ISSUE THREAD

**Issue by ygoe** [notepad-plus-plus/notepad-plus-plus#8903]
### Description of the Issue
When the text search doesn't find anything, it makes a beep sound. This can be annoying and I'd like to turn it off.

### Steps to Reproduce the Issue
1. Search for a text that doesn't exist

### Expected Behavior
Visual feedback, but otherwise silence

### Actual Behavior
Beep

### Debug Information
Notepad++ v7.8.9   (32-bit)
Build time : Jul 15 2020 - 20:26:50
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS Name : Windows 10 Enterprise (64-bit) 
OS Version : 2004
OS Build : 19041.508
Current ANSI codepage : 1252
Plugins : CustomizeToolbar.dll mimeTools.dll NppConverter.dll NppExport.dll NppSaveAsAdmin.dll

**Comment by sasumner** [comment]
This has been addressed by #7950 and #7951 and more info on it is in the official Notepad++ documentation.

**Comment by ygoe** [comment]
That's not a solution because it doesn't work (NPP is not in the mixer here) and it requires complex manual configuration on each single computer and user account. Actually it's just a work-around or hack because it relies on OS-level control over something that can't be set up satisfyingly in the application itself. No other application requires this workaround. A proper solution would be an option directly in NPP that can easily be deployed along with all other settings by copying the config file. And it's not like that would be hard, really. I still consider this issue open.

I'm wondering why this sound even exists? There's no sound on all sorts of other events like when I'm trying to move the cursor beyond a limit or pressing a hotkey of a disabled function. This is very illogical and strange. (More than anything else in NPP.)

PS: I did search for this before opening a new issue but didn't find it because it was closed. It's not relevant because the bug still exists, so a new issue was necessary anyway. And now you closed it again. :-(

**Comment by sasumner** [comment]
>I'm wondering why this sound even exists?

Original designers thought it was a good feature?

>I still consider this issue open

Ok, but the sign says:
![image](https://user-images.githubusercontent.com/30118311/94341504-ce27fc80-ffd7-11ea-975b-5aaad73ec89d.png)

**Comment by ygoe** [comment]
Yes, the sign says "closed" because you don't care for it. Thank you for ignoring your users. Again, this is not a welcoming community here.
