### ISSUE TITLE
Shortcut with only function key (F4) not working anymore

### ISSUE THREAD

**Issue by DUN-Cosmos** [notepad-plus-plus/notepad-plus-plus#8907]
### Description of the Issue
I had configured F4 in the shortcut mapper for "Toggle Single Line Comment" many year ago.
And at least sine version 6.8.8 this key doesn't work any more. Not sure which is the last working version since I don't remember from which version I updated to 6.8.8 and 6.8.9.

### Steps to Reproduce the Issue
Configure F4 key in the shortcut mapper for "Toggle Single Line Comment", with "No conflicts" indicated.

### Actual Behavior
No any reaction.

### Debug Information
Notepad++ v7.8.8   (32-bit)
Build time : Jun 24 2020 - 00:15:36
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : ON
Local Conf mode : OFF
OS Name : Windows 7 Ultimate (64-bit) 
OS Build : 7601.0
Current ANSI codepage : 950
Plugins : CodeAlignmentNpp.dll DSpellCheck.dll Explorer.dll LightExplorer.dll mimeTools.dll NppConverter.dll NppExport.dll NppQCP.dll NppTextFX.dll

**Comment by ArkadiuszMichalski** [comment]
@DUN-Cosmos Works for me in 7.9 RC. Maybe you have some problem with your `shortcuts.xml` file, or plugins, or... other aplications in Windows. To fast check this try download latest portable (.zip) version (from Notepad++ official page), unload somewhere, run with `notepad++.exe` (but before this close any othere Notepad++ windows), set this F4 shortcut and give the results. This will not break your original version of the program, after test you can delete portable version.

**Comment by DUN-Cosmos** [comment]
Just tested 7.8.8 portable and 7.9 RC portable.
Same result, no conflicts yet F4 don't work.

P.S. F6 work on all version I have tested.

**Comment by ArkadiuszMichalski** [comment]
Can you put debug info from portable?

**Comment by DUN-Cosmos** [comment]
Notepad++ v7.9   (32-bit)
Build time : Sep 22 2020 - 03:24:22
Path : A:\Temp\npp.7.9.portable\notepad++.exe
Admin mode : ON
Local Conf mode : ON
OS Name : Windows 7 Ultimate (64-bit)
OS Build : 7601.0
Current ANSI codepage : 950
Plugins : mimeTools.dll NppConverter.dll NppExport.dll



Notepad++ v7.8.8   (32-bit)
Build time : Jun 24 2020 - 00:15:36
Path : A:\Temp\npp.7.8.8.bin\notepad++.exe
Admin mode : ON
Local Conf mode : ON
OS Name : Windows 7 Ultimate (64-bit)
OS Build : 7601.0
Current ANSI codepage : 950
Plugins : mimeTools.dll NppConverter.dll NppExport.dll

**Comment by ArkadiuszMichalski** [comment]
Looks like the fault of the system (of another programs), worth checking on a different machine (if possible).

**Comment by ArkadiuszMichalski** [comment]
DUN-Cosmos Command `Next Search Result` doesn't have this shortcut?

**Comment by DUN-Cosmos** [comment]
on a different machine (if possible) >>> Not possible....
Command Next Search Result doesn't have this shortcut? >>> Yes, but I had
cleared it first.

**Comment by ArkadiuszMichalski** [comment]
I can't reproduce... maybe othere can help. You can also check some older (portable) version http://download.notepad-plus-plus.org/repository/. If it doesn't work in the old ones, it's not Notepad ++'s fault

**Comment by sasumner** [comment]
After exiting Notepad++, rename shortcuts.xml to something else.
Run Notepad++, try setting up F4 the way you want it.

**Comment by DUN-Cosmos** [comment]
Today I checkup each software running on my PC and finally found out who mess it up.
Luckily it's on top of my check list. And it come up capturing the F4 key and seems to do nothing....
