### ISSUE TITLE
replay colour #8359

### ISSUE THREAD

**Issue by gianbp** [notepad-plus-plus/notepad-plus-plus#8909]
sorry for the delay.
this is the screen shot you asked for.

![image](https://user-images.githubusercontent.com/66299876/94359151-a0a98480-00a5-11eb-987e-7b8d5e252549.png)

nothing really important.

**Comment by ArkadiuszMichalski** [comment]
@gianbp You can close this, previouse bug is enough (https://github.com/notepad-plus-plus/notepad-plus-plus/issues/8359).
