### ISSUE TITLE
Add plugin interface for renaming an unsaved tab

### ISSUE THREAD

**Issue by sasumner** [notepad-plus-plus/notepad-plus-plus#8916]
Notepad++ version 7.6.4 (I think) introduced the capability to rename an unsaved tab.

For example, a tab with the title "new 2" can be right-clicked upon, "Rename" chosen from the resulting popup menu, and the following box presents:

![image](https://user-images.githubusercontent.com/30118311/94431825-cf863000-0163-11eb-8562-5260062b3189.png)

What is needed is a way for a plugin to be able to effect this sort of rename, directly, without the popup input box shown above.

[ Comments above based upon features available current to Notepad++ 7.9 ]

**Comment by alankilborn** [comment]
There was a recent change to support longer "soft names" (up to 63 characters; see https://github.com/notepad-plus-plus/notepad-plus-plus/pull/10964 ).  How about showing this related feature request some love and implementing it?

**Comment by alankilborn** [comment]
This has been turned down, I think, by N++ author response here: https://github.com/notepad-plus-plus/notepad-plus-plus/pull/10964#issuecomment-1002642162

So I guess it is appropriate to close this.

**Comment by dail8859** [comment]
@alankilborn Indeed it seems that way. Closing.

**Comment by donho** [comment]
@alankilborn 
If you want to work on it, just let me know.

**Comment by alankilborn** [comment]
@donho Apparently it can be done from a plugin by sending an "internal" NPPM message, see [HERE](https://github.com/notepad-plus-plus/notepad-plus-plus/blob/4ad57c1dd1cc912cc100a86a1a9a4cc71bd9dff6/PowerEditor/src/resource.h#L687).

Should it be turned into a non-internal plugin message?

BTW, I learned about the internal message [HERE](https://community.notepad-plus-plus.org/post/94942); I didn't know about it previously.

**Comment by donho** [comment]
@alankilborn 
> Should it be turned into a non-internal plugin message?

Yes, please. Since the need is present.
Let's rename it to `NPPM_SETUNTITLEDNAME`.

> calling NPPM_INTERNAL_SETFILENAME does not automatically trigger the [NPPN_FILEBEFFORERENAME ](https://github.com/search?q=repo%3Anotepad-plus-plus%2Fnotepad-plus-plus+nppn_filebeforerename&type=code)and [NPPN_FILERENAMED ](https://github.com/search?q=repo%3Anotepad-plus-plus%2Fnotepad-plus-plus+nppn_filerenamed&type=code)notifications, which may cause strange behavior in plugins that respond to those notifications, and is therefore perhaps not a great idea. That said, [I do this myself ](https://github.com/search?q=repo%3Amolsonkiko%2FJsonToolsNppPlugin%20setcurrentbufferinternalname&type=code)in the JsonTools plugin and it seems to work fine.

Please add also the necessary notifications so it'll not break other plugins.

**Comment by alankilborn** [comment]
> If you want to work on it, just let me know.

OK, if you want to assign me, I'll see what I can do.

**Comment by alankilborn** [comment]
@donho Did you want to keep the existing "internal" message, for those already using that method?  Or delete it and have those developers conform to the new NPPM_SETUNTITLEDNAME ?

**Comment by donho** [comment]
Please use NPPM_SETUNTITLEDNAME  and remove the internal one (since it's not used internally). All the messages with infix "_INTERNAL_" are excluded from the contract with plugins.

**Comment by alankilborn** [comment]
@donho 

It seems that there is no plugin command for renaming a file, regardless of whether that file is "hardnamed" (i.e., saved into the file system) or "softnamed" (aka "internal", e.g. "new 2").

Sure, a plugin can use OS calls to rename a hardnamed file (the sequence would be: plugin closes N++ file tab, plugin calls OS to rename file, plugin opens file with new name into N++ file tab), but maybe this is awkward as it could change the tab ordering.

It should be fairly simple (famous last words) to make a plugin wrapper around `Notepad_plus::fileRename(BufferID id)` that would allow plugins to rename either hardnamed OR softnamed file tabs.

Would it be acceptable to create, e.g. `NPPM_TABRENAME` to handle renaming of either type?

**Comment by donho** [comment]
> Would it be acceptable to create, e.g. NPPM_TABRENAME to handle renaming of either type?

I would say no. The reason is NPPM_TABRENAME is not accurate command name because of 2 types of tab name: a. untitled b. real file path, and the different treating ways should not be mixed under a vague SETTABRENAME.

Let's just do https://github.com/notepad-plus-plus/notepad-plus-plus/issues/8916#issuecomment-2126180131, and if request we will consider adding another plugin command which could be NPPM_RENAMECURRENTPATHNAME.

**Comment by Diondam** [comment]
Do you have a solution for it?
