### ISSUE TITLE
Notepad++ error on close

### ISSUE THREAD

**Issue by terencemcdonnell** [notepad-plus-plus/notepad-plus-plus#8917]
### Description of the Issue

When closing the application by clicking in the standard windows close [x] in the upper right-hand corner, application closes - but error message box pops up saying:

"Notepad++ : a free (GNU) source code editor has stopped working
A problem caused the program to stop working correctly. Please close the program.

[Close the program] [Debug the program]"

### Steps to Reproduce the Issue

1.  Open the application
2.  Close the application

### Expected Behavior

Expected to close silently
### Debug Information

Notepad++ v7.9   (64-bit)
Build time : Sep 22 2020 - 03:19:04
Path : C:\Users\E022019\Documents\Apps\NPP\notepad++.exe
Admin mode : OFF
Local Conf mode : ON
OS Name : Windows 10 Enterprise (64-bit) 
OS Version : 1809
OS Build : 17763.1457
Current ANSI codepage : 1252
Plugins : BigFiles.dll CodeAlignmentNpp.dll ComparePlugin.dll DSpellCheck.dll mimeTools.dll NppConverter.dll NppExec.dll NppExport.dll NppFavorites.dll NPPJSONViewer.dll NppTextFX.dll NppXmlTreeviewPlugin.dll PoorMansTSqlFormatterNppPlugin.dll _CustomizeToolbar.dll

**Comment by sasumner** [comment]
@terencemcdonnell 

You might try without all those plugins.

**Comment by terencemcdonnell** [comment]
FYI - issue resolved - information for anyone that googled into this thread looking for info - by a process of elimination (disabling and enabling plugins), I determined that the culprit was the "BigFiles" plugin - doesn't seem to want to play nice with latest version (I just upgraded to 7.9.0)

Thanks

**Comment by ArkadiuszMichalski** [comment]
@terencemcdonnell You can report this in https://github.com/superolmo/BigFiles/issues.

**Comment by terencemcdonnell** [comment]
I have done so - thanks @ArkadiuszMichalski
