### ISSUE TITLE
SQL Language Colorizing Display Issue with \'

### ISSUE THREAD

**Issue by netsuvi** [notepad-plus-plus/notepad-plus-plus#8919]
### Description of the Issue

When I use 'String\' then the colorication fails.

### Steps to Reproduce the Issue

1. Example of sql Code that is worng colored

UPDATE sr_prg_par
   SET par_wert = 'C:\mylocaldrive\share\\'
 WHERE     PRG_ID = 'ODBM'
       AND PATH = 'IMAGEPFAD'
       AND KEY_ID = 11;

### Expected Behavior

Color should be normal SQL color 

### Actual Behavior

![SQL_wrong_colors](https://user-images.githubusercontent.com/38036597/94535504-ef8c2100-0241-11eb-9835-05a253bed65a.PNG)

All text after the \'  turned grey.

### Debug Information

Notepad++ v7.8.9   (32-bit)
Build time : Jul 15 2020 - 20:26:50
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS Name : Windows 10 Enterprise (64-bit) 
OS Version : 1909
OS Build : 18363.1082
Current ANSI codepage : 1252
Plugins : ComparePlugin.dll mimeTools.dll NppConverter.dll NppExport.dll

**Comment by ArkadiuszMichalski** [comment]
@netsuvi And where is debug info?

**Comment by netsuvi** [comment]
Hi @ArkadiuszMichalski 
Debug Info added. Cheers.

**Comment by netsuvi** [comment]
The bug is a bit ugly for me, because it turnes the next 200 lines that follow in my sql script also into grey.

**Comment by ArkadiuszMichalski** [comment]
For your code example it can't be reproduce, put some code that this bug can be reproducable.

**Comment by sasumner** [comment]
I can do it:

```
UPDATE sr_prg_par
SET par_wert = 'C:\mylocaldrive\share\'
WHERE PRG_ID = 'ODBM'
AND PATH = 'IMAGEPFAD'
AND KEY_ID = 11;
```

Renders in N++ 7.9 as:

![image](https://user-images.githubusercontent.com/30118311/94565799-a636d400-0237-11eb-868e-d30a7cf6de73.png)

Change the code to remove the `\` near the end of the second line :

```
UPDATE sr_prg_par
SET par_wert = 'C:\mylocaldrive\share'
WHERE PRG_ID = 'ODBM'
AND PATH = 'IMAGEPFAD'
AND KEY_ID = 11;
```

And it renders this way:

![image](https://user-images.githubusercontent.com/30118311/94565967-d4b4af00-0237-11eb-874a-c9e0bacb55e5.png)

**Comment by ArkadiuszMichalski** [comment]
OK, same here, in first post example was not same as picture:)

**Comment by sasumner** [comment]
>in first post example was not same as picture

Yes, probably because OP did not format the code text as code text so that the website would not touch it. :-)

**Comment by sasumner** [comment]
Here are my findings with 7.9 :

* After setting the _Treat backslash as escape character for SQL_ checkbox + restarting:  Renders wrongly

* After clearing the _Treat backslash as escape character for SQL_ checkbox + restarting:  Renders CORRECTLY

So perhaps the recommendation for the OP here is to clear the checkbox and restart, but the bigger picture fix is:
 add `Treat backslash as escape character for SQL (requires Notepad++ restart)` in the UI

**Comment by ArkadiuszMichalski** [comment]
Sorry for xxx edit, restart is not needed, only once again open file(s) - reload not work.

**Comment by sasumner** [comment]
Maybe this then:

`Treat backslash as escape character for SQL (requires file reload)`

**Comment by sasumner** [comment]
>reload not work

Reload works for me.

1. Change _Treat backslash as escape character for SQL_ checkbox 
2. _File_ > _Reload from Disk_

**Comment by ArkadiuszMichalski** [comment]
Better than now, the only question is whether this option should affect highlighting. 
Btw, for me reload not work, but change tab to other and  back to .sql works:)

**Comment by sasumner** [comment]
>the only question is whether this option should affect highlighting.

I don't understand this comment.
I don't use SQL files, but the `Treat...` option has been in Notepad++ for years.
My guess is that it is working correctly for the situation under discussion.

**Comment by ArkadiuszMichalski** [comment]
I'm wondering if changing this option should affect/break highlighting, I also don't use SQL so waiting that other persons confirm this.

**Comment by ArkadiuszMichalski** [comment]
https://dev.mysql.com/doc/refman/8.0/en/string-literals.html << ok, looks like it's correct, chars \\' means ' so command is not finished. Just proper use escaped sequence or disabled this function.

**Comment by sasumner** [comment]
>...chars \' means ' so command is not finished. 

>Just proper use escaped sequence

It seems like there must be more to the story.
I mean, using proper escape sequences is important in all languages that support them (and there are MANY of these).
So why does SQL (alone) get its own checkbox option for this in N++?
Was there a time in SQL where "improper" escape sequences were allowed?

**Comment by ArkadiuszMichalski** [comment]
SQL has more escape solution (https://www.databasestar.com/sql-escape-single-quote/) but `\` is optional (https://dev.mysql.com/doc/refman/8.0/en/sql-mode.html#sqlmode_no_backslash_escapes). Here using '\' in the wrong way brake highlighting (when this option is on).

**Comment by netsuvi** [comment]
> > in first post example was not same as picture
> 
> Yes, probably because OP did not format the code text as code text so that the website would not touch it. :-)

Sorry for the mess. I fixed it, so the code example is getting display correctly.
By the way, the code example works well on an oracle database and toad is showing this code example in nice colours.

**Comment by netsuvi** [comment]
I made a few more tries on the Oralce Database
SET par_wert = 'C:\mylocaldrive\share\\\\'
gives the wrong result, as it ends up in a double slash.
SET par_wert = 'C:\mylocaldrive\share\\''
gives ORA-01756 Error: Quoted String not properly endend.

**Comment by ArkadiuszMichalski** [comment]
@netsuvi You use char  '\` as escape character in your SQL code? If not the turn off option (as mention above) and that's it (and switch between tabs or run NPP again to apply this change).

**Comment by netsuvi** [comment]
@ArkadiuszMichalski 

Turning off the option fixes it. Thanks a lot!

**Comment by ArkadiuszMichalski** [comment]
@sasumner I think any additional words in pref is not necessary. Just after switch this option check also active files in both views, and if they use SQL then apply the SQL styles again. For others inactive tabs is not necessery because after switch to that tabs styles are automatically aply.
