### ISSUE TITLE
Markdown Content is not shown Properly

### ISSUE THREAD

**Issue by garvit-joshi** [notepad-plus-plus/notepad-plus-plus#8925]
Markdown Content Is Not Shown Properly when using Solarized Theme.
Here are some Screenshots:

![Notepad](https://user-images.githubusercontent.com/55401175/94606282-dfaf2400-02b7-11eb-91c8-59bba92cbab7.PNG)
![Notepad1](https://user-images.githubusercontent.com/55401175/94606285-e0e05100-02b7-11eb-9bb7-3bc3a5ff2358.PNG)

# These Happen with these settings:
![NotepadStyle](https://user-images.githubusercontent.com/55401175/94606325-ec337c80-02b7-11eb-8fd2-aede319cfbdd.PNG)

Solarized Light also can not show content in a great manner.

Notepad++ v7.9 64 bit
Windows 10

**Comment by ArkadiuszMichalski** [comment]
@garvit-joshi Read this bug https://github.com/notepad-plus-plus/notepad-plus-plus/issues/5799. You should find theme that support Markdown (Solarized doesn't).
