### ISSUE TITLE
Floating side windows don't minimize to system tray

### ISSUE THREAD

**Issue by Uhf7** [notepad-plus-plus/notepad-plus-plus#8928]
### Description of the Issue
Floating side windows doesn't minimize to system tray.

### Steps to Reproduce the Issue

1. Start Notepad++
2. Check `Settings` -> `Preferences` -> `MISC.` -> `Minimize to system tray`
3. Start Project Panel 1 and make it a floating window (Rip it out of it's docked position)
4. Click the minimize icon of Notepad++

### Expected Behavior
Notepad++ and all floating windows belonging to it disappear, like they do on "normal" minimize.

### Actual Behavior
Notepad++ disappears, the floating windows remain visible.

### Debug Information
	Notepad++ v7.9   (32-bit)
	Build time : Sep 22 2020 - 03:24:22
	Path : C:\Tools\Npp\notepad++.exe
	Admin mode : OFF
	Local Conf mode : ON
	OS Name : Windows 10 Pro (64-bit) 
	OS Version : 1607
	OS Build : 14393.576
	Current ANSI codepage : 1252
	Plugins : DSpellCheck.dll LuaScript.dll mimeTools.dll NppConverter.dll NppExport.dll

**Comment by ArkadiuszMichalski** [comment]
@Uhf7 Strange, for me it doesn't work at all, by "minimize icon"` you mean standard [-] on the top-right corner of the Notepad++ window? I see some other bugs about this:
https://github.com/notepad-plus-plus/notepad-plus-plus/issues/8528
https://github.com/notepad-plus-plus/notepad-plus-plus/issues/7667

I run NPP with `-multInst` and in admin mode (Win7), that's the reason?

**Comment by Uhf7** [comment]
Minimize to tray doesn't work in admin mode, that's stated in #8528. I already looked in the code, it is blocked by purpose, like this:
`if (nppgui._isMinimizedToTray && !_isAdministrator)`, only then minimize to tray.
I didn't know, why it is blocked, thank you for the research, #884 explains it.

**Comment by ArkadiuszMichalski** [comment]
Blocked this option in Prefs window when admin mode is ON would be more obvious.

**Comment by ArkadiuszMichalski** [comment]
Hmm any reproducable case when using Notepad++ (with admin) make problem when minimize to try? I try https://github.com/benbuck/rbtray and works fine for Notepad++.
