### ISSUE TITLE
[Translating] &amp; What is that for?

### ISSUE THREAD

**Issue by Arczi008TV** [notepad-plus-plus/notepad-plus-plus#8930]
What is role of that code "amp;" It is necessary?
![image](https://user-images.githubusercontent.com/49120706/94704093-d79ac700-033f-11eb-8e51-96ef8f5a2e21.png)

![image](https://user-images.githubusercontent.com/49120706/94704643-6d365680-0340-11eb-875e-b94887f11b35.png)

**Comment by sasumner** [comment]
For the last two your show, have a look here at the underlined letters -- that's what the `&amp;` does:

![image](https://user-images.githubusercontent.com/30118311/94717301-22a3e280-031e-11eb-8594-59dfb79fcae1.png)

**Comment by donho** [comment]
@sasumner 
Maybe we should provide 
https://community.notepad-plus-plus.org/
For the support request.

**Comment by sasumner** [comment]
@Arczi008TV 

If the above does not answer your question completely, please don't post here again as this is for "problems with the software" and not "questions about the software".

However, feel completely free to post where @donho provided a link.  
Questions there are totally welcomed.
