### ISSUE TITLE
Notepad++ updater check is bugged (not surfacing new versions)

### ISSUE THREAD

**Issue by Dutchman101** [notepad-plus-plus/notepad-plus-plus#8937]
### Description of the Issue
It's very simple: the Notepad++ integrated updater ('?' menu > click Update Notepad++) isn't working as expected.

For the past couple of released updates, it said "No update is available", forcing me to download and install the update from Notepad++ website instead.

### Steps to Reproduce the Issue

1. Wait for update to be released and announced on the Notepad++ site
2. Try the updater menu
3. Observe incorrect output (there being no update)

### Expected Behavior
Notepad++ servers should properly return the availability of an update to the application's updater.

### Actual Behavior
Notepad++ updater incorrectly determines there is no update, while there is.

In place of "Debug information", i would like to establish these facts:
- I have tried the built-in updater, under the same circumstances of an update being available in reality, from multiple PC's in multiple locations. The problem occured to all of them, and therefore it's clearly not related to environment or system factors.

- All my reproductions of this issue took place on PC's without any firewalls enabled, with full and unrestricted access to the internet (even tested with DMZ). Therefore, it cannot be that the client updater is being blocked, resulting in the unexpected return value of "No update". It must really be your back-end, update servers, or the bugged way Notepad++ application handles the return value.

- This issue occured for quite a period of time.. several Notepad++ versions went by, where the integrated updater returned "No update available" and where I resorted to downloading it from the main page instead. I cannot accurately pinpoint when the last time it was that the updater worked, but I do recall it working. It is very likely that it randomly worked, during a period that new versions had a high chance of not popping up in the updater check.

**Comment by sasumner** [comment]
If you had a step 1a as follows, I think there would be no issue (no step 3):

1a.  Wait for program author to "bless" the release and turn on the signal for the updater

Now, clearly you can't "wait" for that event, since you (and nobody) knows exactly when that will take place.

**Comment by ArkadiuszMichalski** [comment]
@sasumner But manually select `? >> Update Notepad++` should not always check for new version, regardless the auto check was on/off? Command `Update Notepad++` is also somehow delayed by author?

**Comment by sasumner** [comment]
Probably this is one that would need to be examined by @donho to really understand it.

**Comment by donho** [comment]
Auto-update, if it's ON, it will check (on startup) once per 14 days. If user doesn't want to wait for 2 weeks (or 1. auto-update is disable 2. his/her Notepad++ restarts rarely), he/she can  manually select `? >> Update Notepad++` to check if there's any update.

The update will be triggered by the website after 1 or 2 weeks of new release, to make sure there's no critical bugs.
Without being triggered, automatic or manual update have no effect.

> But manually select `? >> Update Notepad++` should not always check for new version, regardless the auto check was on/off? Command Update Notepad++ is also somehow delayed by author?

Indeed, it's quite confusing. I will see if I can do somethings about it.

**Comment by Dutchman101** [comment]
I didn't read that part of the documentation, my bad. Even though i seem to recall the updater saying there's no update after large amounts of time passed since update (definately more than 2 weeks).. which i realised by looking at the site and then release date. But it's possible that this is just in my mind.

Anyways, small suggestion: maybe keep the updater check in its current shape, but simply add a text below it: "New releases might exist, but will only show up here after a period of QA to ensure stability" or a hyperlink to "More information" which points to the relevant documentation page.
