### ISSUE TITLE
Annoying bell sound on keystroke ENTER in Function list & Folder as Workspace 

### ISSUE THREAD

**Issue by donho** [notepad-plus-plus/notepad-plus-plus#8938]
### Description of the Issue
In both Function list & Folder as Workspace, if select an item then type ENTER, it produce an annoying bell sound.

### Steps to Reproduce the Issue

1. In Function list or Folder as Workspace, select an item
2. Type ENTER

### Expected Behavior
No sound

### Actual Behavior
Bell sound

### Debug Information
Notepad++ v7.9   (32-bit)
Build time : Sep 22 2020 - 03:24:22
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS Name : Windows 10 Enterprise (64-bit) 
OS Version : 2004
OS Build : 19041.508
Current ANSI codepage : 1252
Plugins : mimeTools.dll NppConverter.dll NppExport.dll NppXmlTreeviewPlugin.dll

**Comment by donho** [comment]
@Uhf7 
Any idea to fix it ?

**Comment by Uhf7** [comment]
I cannot reproduce it on my system. So I would check the Sound Scheme Windows settings first, because:
- need to detect the source of the sound (if it goes away with the "No sounds" scheme, it comes from there). 
- with the Windows update to 2004, improvements may have been added to the sound schemes.

**Comment by ArkadiuszMichalski** [comment]
I also have this sound for:

Notepad++ v7.9   (32-bit)
Build time : Sep 22 2020 - 03:24:22
Path : D:\_test\NPPClean\notepad++.exe
Admin mode : ON
Local Conf mode : ON
OS Name : Windows 7 Ultimate (64-bit) 
OS Build : 7601.0
Current ANSI codepage : 1250
Plugins : HexEditor.dll

**Comment by Uhf7** [comment]
Ok, I can reproduce it under Windows 7 too now.

Notepad++ v7.9   (32-bit)
Build time : Sep 22 2020 - 03:24:22
Path : C:\Tools\Npp\notepad++.exe
Admin mode : OFF
Local Conf mode : ON
OS Name : Windows 7 Professional (64-bit) 
OS Build : 7601.0
Current ANSI codepage : 1252
Plugins : DSpellCheck.dll LuaScript.dll mimeTools.dll NppConverter.dll NppExport.dll 

It can be turned off by switching the Windows sound scheme to "No sounds", but more interesting is, why it happens at all. Investigating ...
