### ISSUE TITLE
Plugin Exception

### ISSUE THREAD

**Issue by twDavidFung** [notepad-plus-plus/notepad-plus-plus#8947]
### Steps to Reproduce the Issue

1. 
2. 
3. 

### Debug Information

Notepad++ v7.9   (64-bit)
Build time : Sep 22 2020 - 03:19:04
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS Name : Windows 10 Pro (64-bit) 
OS Version : 2004
OS Build : 19041.508
Current ANSI codepage : 1252
Plugins : HexEditor.dll mimeTools.dll NppConverter.dll NppExport.dll 

![2020-10-04_17-14-01](https://user-images.githubusercontent.com/72337506/95012091-2e6a0e80-0668-11eb-9338-45ec6d63c805.jpg)

**Comment by sasumner** [comment]
This site is for core Notepad++ issues only.
Please find the site for HexEditor support and pursue the problem there.

**Comment by ArkadiuszMichalski** [comment]
@twDavidFung Just update your HexEditor plugin to new version.

**Comment by twDavidFung** [comment]
> 
> 
> @twDavidFung Just update your HexEditor plugin to new version.

Noted with thanks.
