### ISSUE TITLE
Find/Replace dialogue changes Caret Policy

### ISSUE THREAD

**Issue by vinsworldcom** [notepad-plus-plus/notepad-plus-plus#8961]
### Description of the Issue
I apply a vertical (y) caret policy using [NppExec](https://github.com/d0vgan/nppexec) to keep the top and bottom 5 lines visible when scrolling.

```
SCI_SENDMSG SCI_SETYCARETPOLICY 13 5
```

When using the Find / Replace dialogue, the `Searching::displaySectionCentered` function replaces the Y Caret Policy in order to scroll the view.

The "problem" is here:

```
notepad-plus-plus\PowerEditor\src\ScitillaComponent\FindReplaceDlg.cpp
214:  void Searching::displaySectionCentered(int posStart, int posEnd, ScintillaEditView * pEditView, bool isDownwards) 
215:  {
216:  	// Make sure target lines are unfolded
217:  	pEditView->execute(SCI_ENSUREVISIBLE, pEditView->execute(SCI_LINEFROMPOSITION, posStart));
218:  	pEditView->execute(SCI_ENSUREVISIBLE, pEditView->execute(SCI_LINEFROMPOSITION, posEnd));
219:  
220:  	// Jump-scroll to center, if current position is out of view
221:  	pEditView->execute(SCI_SETYCARETPOLICY, CARET_JUMPS | CARET_EVEN);
222:  	// When searching up, the beginning of the (possible multiline) result is important, when scrolling down the end
223:  	pEditView->execute(SCI_GOTOPOS, isDownwards ? posEnd : posStart);
224:  	pEditView->execute(SCI_SETYCARETPOLICY, CARET_EVEN);
```

`SCI_SETYCARETPOLICY` is used twice to "center" the view.  Since there is no GET caret policy, we can't save and restore the previous state, so is there another way to scroll without resetting the SCI_SETYCARETPOLICY?  Maybe using [SCI_SCROLLCARET](https://www.scintilla.org/ScintillaDoc.html#SCI_SCROLLCARET) or using [SCI_GETFIRSTVISIBLELINE](https://www.scintilla.org/ScintillaDoc.html#SCI_GETFIRSTVISIBLELINE) after the SCI_GOTOPOS call and then [SCI_SCROLLRANGE](https://www.scintilla.org/ScintillaDoc.html#SCI_SCROLLRANGE)?

Or maybe calling [SCI_ENSUREVISIBLEENFORCEPOLICY](https://www.scintilla.org/ScintillaDoc.html#SCI_ENSUREVISIBLEENFORCEPOLICY) and setting [SCI_SETVISIBLEPOLICY](https://www.scintilla.org/ScintillaDoc.html#SCI_SETVISIBLEPOLICY) with the `CARET_JUMPS | CARET_EVEN` flags as in the original code?

### Steps to Reproduce the Issue
1 Using a document that has more lines than can be visible in the edit view (i.e., vertical scrollbar is required)
2. Use a scripting plugin to set a Y caret policy ([SCI_SETYCARETPOLICY](https://www.scintilla.org/ScintillaDoc.html#SCI_SETYCARETPOLICY)) of 13 with a slop of 5
3. Open Find / Replace dialogue (Search => Find...), enter some text in the document that will be found
4. Press the "Find Next" button on the "Find" dialogue so the cursor navigates to the text
5. Now try scrolling to the top or bottom with the arrow keys and the cursor should push right to the top or bottom of the edit window before initiating scrolling rather than leaving 5 visible lines

### Expected Behavior
I expect my ([SCI_SETYCARETPOLICY](https://www.scintilla.org/ScintillaDoc.html#SCI_SETYCARETPOLICY)) of 13 with a slop of 5 to be maintained after a Find dialogue usage.

### Actual Behavior
The ([SCI_SETYCARETPOLICY](https://www.scintilla.org/ScintillaDoc.html#SCI_SETYCARETPOLICY)) of 13 with a slop of 5 is changed by a Find dialogue usage.

### Debug Information
Notepad++ v7.9   (64-bit)
Build time : Oct  6 2020 - 02:10:12
Path : C:\usr\bin\npp64\notepad++.exe
Admin mode : OFF
Local Conf mode : ON
OS Name : Windows 10 Enterprise (64-bit) 
OS Version : 1909
OS Build : 18363.1082
Current ANSI codepage : 1252
Plugins :

**Comment by sasumner** [comment]
Whew...Interesting...Troubling... :-)

If it were me, I'd create and run a Pythonscript at startup with an "update ui" notification and do a `editor.setYCaretPolicy(13, 5)` in the callback.  :-)

**Comment by vinsworldcom** [comment]
Just tested this using SCI_SETVISIBLEPOLICY and SCI_ENSUREVISIBLEENFORCEPOLICY and it works:

```
PS VinsWorldcom ~\source\personal\notepad-plus-plus\PowerEditor\visual.net > git diff ..\src\ScitillaComponent/FindReplaceDlg.cpp
diff --git a/PowerEditor/src/ScitillaComponent/FindReplaceDlg.cpp b/PowerEditor/src/ScitillaComponent/FindReplaceDlg.cpp
index c1b905f6..88321380 100644
--- a/PowerEditor/src/ScitillaComponent/FindReplaceDlg.cpp
+++ b/PowerEditor/src/ScitillaComponent/FindReplaceDlg.cpp
@@ -218,10 +218,12 @@ void Searching::displaySectionCentered(int posStart, int posEnd, ScintillaEditVi
        pEditView->execute(SCI_ENSUREVISIBLE, pEditView->execute(SCI_LINEFROMPOSITION, posEnd));

        // Jump-scroll to center, if current position is out of view
-       pEditView->execute(SCI_SETYCARETPOLICY, CARET_JUMPS | CARET_EVEN);
+       pEditView->execute(SCI_SETVISIBLEPOLICY, CARET_JUMPS | CARET_EVEN);
+       pEditView->execute(SCI_ENSUREVISIBLEENFORCEPOLICY, pEditView->execute(SCI_LINEFROMPOSITION, isDownwards ? posEnd : posStart));
        // When searching up, the beginning of the (possible multiline) result is important, when scrolling down the end
        pEditView->execute(SCI_GOTOPOS, isDownwards ? posEnd : posStart);
-       pEditView->execute(SCI_SETYCARETPOLICY, CARET_EVEN);
+       pEditView->execute(SCI_SETVISIBLEPOLICY, CARET_EVEN);
+       pEditView->execute(SCI_ENSUREVISIBLEENFORCEPOLICY, pEditView->execute(SCI_LINEFROMPOSITION, isDownwards ? posEnd : posStart));

        // Adjust so that we see the entire match; primarily horizontally
        pEditView->execute(SCI_SCROLLRANGE, posStart, posEnd);
```

It seems to work fine finding /centering found text as before **_and_** keep the set Y Caret policy I've created.  BUT .. notice the path is 'src\ScitillaComponent' - what does that mean for a pull request and Scintilla updates and the like?  Keep in mind, I've been using Notepad++ for years, but only looking at the code for weeks.

Cheers.

**Comment by sasumner** [comment]
>BUT .. notice the path is 'src\ScitillaComponent' 

Anything under `PowerEditor` is Notepad++ code, not Scintilla.

**Comment by vinsworldcom** [comment]
So I take it a pull request to change this file would be rejected since it is Scintilla code?  Sorry for being pedantic, but I don't want to waste anyone's time.  But if this type of "fix" could be accepted I'll create the pull request.

Cheers.

**Comment by sasumner** [comment]
>So I take it...

Perhaps you misunderstood?

```
notepad-plus-plus\PowerEditor\* ---> NOT Scintilla

notepad-plus-plus\scintilla\* ---> Scintilla
```

As the file you show changes to is under PowerEditor, it is NOT Scintilla code.

**Comment by vinsworldcom** [comment]
DOH!!!  I was a directory or two too far down in the hierarchy - seeing "ScitillaComponent" and thinking it was Scintilla, not N++.  Sorry, thanks for setting me straight.  I'll create the pull request and see how it goes.

Cheers.

**Comment by donho** [comment]
@vinsworldcom 
So your problem is: Finder erase your SCI_SETYCARETPOLICY each time, right?

**Comment by vinsworldcom** [comment]
@donho yes.  There doesn't seem to be a GETYCARETPOLICY to store and restore the current value.  My thought is X and Y caret policy should be used configurable for document navigation and the VISIBLE / ENSUREVISIBLE could be used for application / auto navigation (like recentering a search result).

Cheers.
