### ISSUE TITLE
Opening File Failing (Buffer Boundary)

### ISSUE THREAD

**Issue by BiBi-Abc** [notepad-plus-plus/notepad-plus-plus#8966]
### Description of the Issue
When opening [TestFile (2).txt](https://github.com/notepad-plus-plus/notepad-plus-plus/files/5337475/TestFile.2.txt)
Notepad++ AND Sublime text both fail to display it correctly, while Notepad works.

Opening the file using NOTEPAD, NOT NOTEPAD++, you can see at the end of the file (CTRL + END), there is this random 4-byte UTF-16 Greek character I found. 
Apparently Notepad++ and Sublime text use the same buffer size, and when Notepad++ opens the file, instead of showing the Greek character, it shows 6 random characters.

Sublime text opts to just strip the character, but NOTEPAD opens it correctly.
The issue is here:
https://github.com/notepad-plus-plus/notepad-plus-plus/blob/a1031517742c7ef600b825bf9f193b3f2740dff6/PowerEditor/src/MISC/Common/Common.cpp#L431

where notepad++ removes 1 character from the end of the buffer and tries again.
This however doesn't work with UTF-16, as it requires an even number.

### Steps to Reproduce the Issue
1. Download the above file (at top of issue)
2. Open the file using Notepad++
3. Press CTRL + END
4. Observe the weird characters
5. Open the same file with NOTEPAD, NOT NOTEPAD++
6. CTRL + END
7. Observe the greek character

### Expected Behavior
I expected Notepad++ to show the greek character and the entire file contents correctly.

### Actual Behavior
Notepad++ shows 6 weird characters at the end of the file where the greek character should be.

### Debug Information
Notepad++ v7.8.9   (64-bit)
Build time : Jul 15 2020 - 20:31:49
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS Name : Windows 10 Pro (64-bit) 
OS Version : 2004
OS Build : 19041.508
Current ANSI codepage : 1252
Plugins : ComparePlugin.dll mimeTools.dll NppConverter.dll nppcrypt.dll NppExport.dll 

### Screenshots
![image](https://user-images.githubusercontent.com/71203524/95272511-589d0700-07f5-11eb-9589-075ac457684e.png)

**GOOD**:
![image](https://user-images.githubusercontent.com/71203524/95272559-766a6c00-07f5-11eb-93a7-260c46ad13f2.png)

**Comment by KnIfER** [comment]
> The issue is here: ...
If I delete the code indicated, the error still exists.

This BUG does not exist in v5.5, but since v6.2 or earlier it's there, and it's in SciLexer.dll.

**Comment by BiBi-Abc** [comment]
> 
> 
> > The issue is here: ...
> 
> If I delete the code, the error still exists. And whats is Buffer Boundary?
> 
> This BUG does not exist in v5.5, but since v6.2 or earlier it's there, and it's in SciLexer.dll.

No, this issue is not in SciLexer.dll, I'm sure.

The buffer boundary is when a multibyte-char is in between 2 buffers.
If you remove the code, Notepad++ probably won't work properly.
Also, sublime text has the exact same issue, and it doesn't use Scintilla.

**Comment by KnIfER** [comment]
Sure? 

But I copied the `SciLexer.dll` from v5.5 to v6.2, then v6.2 can handle the character correctly. 
Proof:
![20201009_175338_GifNo 1](https://user-images.githubusercontent.com/11593903/95569770-9baae480-0a58-11eb-9106-57ff3f2bd9d6.gif)

**Comment by ArkadiuszMichalski** [comment]
In SciTE this file works correct. Problem is in Notepad++ side.

**Comment by BiBi-Abc** [comment]
> 
> 
> Sure?
> 
> But I copied the `SciLexer.dll` from v5.5 to v6.2, then v6.2 can handle the character correctly.
> Proof:
> ![20201009_175338_GifNo 1](https://user-images.githubusercontent.com/11593903/95569770-9baae480-0a58-11eb-9106-57ff3f2bd9d6.gif)

I'm 100% sure this is Notepad++ issue. I was developing my own text editor, and I have to deal with this kind of stuff.

Basically Scintilla mostly only accepts `UTF-8`, so if the file you want to open is say `UTF-16`, Notepad++ has to convert it.

However, Notepad++ converts buffers at a time, so there might be a boundary, causing invalid characters within the function call.

Also, I'm not sure what you mean by earlier versions of SciLexer.dll. The lastest Scintilla version is 4.4.5.

**Comment by BiBi-Abc** [comment]
**OK, I am 100% sure what the issues are.**

Sublime text's issue is that it does not handle multibyte character boundaries correctly, as seen in the Text File (2).txt above. Shrinking that file size below it's blockSize FIXED IT, proving this issue.

Notepad++'s issue is that it uses **UCS-2 BOM, NOT NOT NOT NOT** UTF-16LE BOM. UCS-2 BOM can only handle some characters, but not the others. There is an issue of Notepad++ detecting a file saved in UTF-16LE BOM, and opening it in UCS-2 BOM, which is very similar to UTF-16LE.
I think Notepad++ ALSO has the buffer boundary issue.

**Comment by sasumner** [comment]
@BiBi-Abc So I'm pretty much a UTF-8 guy, out of need and desire, so I'm not too familiar with other encodings, but I'll try to play "catch up" here...

>it uses UCS-2 BOM, NOT NOT NOT NOT UTF-16LE BOM

Does Notepad++ claim (directly or indirectly) to support UTF-16?
I see only UCS-2 references in the encoding areas of the menus, nothing about UTF-16.
If there is no support, then perhaps what we have here is two separate issues:

* lack of UTF-16 support
* buffer boundary problem (which may still need an example where it manifests with a supported encoding)

**Comment by sasumner** [comment]
>buffer boundary problem (which may still need an example where it manifests with a supported encoding)

I can confirm this problem exists, for UTF-8 files where a multibyte character "straddles" the read buffer boundary.

The read buffer size is 131076 bytes (`blockSize` variable used [HERE](https://github.com/notepad-plus-plus/notepad-plus-plus/blob/a1031517742c7ef600b825bf9f193b3f2740dff6/PowerEditor/src/ScitillaComponent/Buffer.cpp#L1353) ).
The `incompleteMultibyteChar` never gets changed away from zero inside the containing do-while loop, thus when there is a file where the multi-byte character is partially read, it is not read correctly.

For looking at this, I used a file(s) with all single-byte UTF-8 characters except one four-byte character very near the end; the character: 𒊹 that is made up of hex bytes F0928AB9

Here are my files: [8966_buffer_boundary_problem.zip](https://github.com/notepad-plus-plus/notepad-plus-plus/files/5357448/8966_buffer_boundary_problem.zip)

In the "BAD" files, a four-byte character is fragmented into two different `fread`s and thus is not handled correctly.
In the "GOOD" files, the four-byte character is fully within either the first or the second `fread` and therefore no problem results.
The "number", e.g. 131078, in the filename is the total file size.

Here's what the data in a "GOOD" read should look like:
![image](https://user-images.githubusercontent.com/30118311/95630300-97c69480-0a4f-11eb-847d-64982319cc78.png)

Here's what the data in a "BAD" read should look like (the bad part is after the `x`):
![image](https://user-images.githubusercontent.com/30118311/95630364-b6c52680-0a4f-11eb-820f-1ced19347c22.png)

**Comment by BiBi-Abc** [comment]
I wonder what the fix is other than brute force.
I am also working on my own text editor, and have tried ICU, but's big. ICU works GREAT though.

I was trying to switch to MultibyteToWideChar, but Windows doesn't return the position of fail.

**Comment by BiBi-Abc** [comment]
Also, I can't believe this issue is in Notepad++ AND Sublime Text!!!

**Comment by sasumner** [comment]
>I wonder what the fix is

I can probably fix it for UTF-8.
As I said, I'm not great with other encodings besides UTF-8.
The code "looks" like it should work for non UTF-8 encodings, but that's about as far as I can go with that.

>have tried ICU, but's big. ICU works GREAT though.

No idea on what ICU is.

**Comment by BiBi-Abc** [comment]
> 
> 
> > I wonder what the fix is
> 
> I can probably fix it for UTF-8.
> As I said, I'm not great with other encodings besides UTF-8.
> The code "looks" like it should work for non UTF-8 encodings, but that's about as far as I can go with that.
> 
> > have tried ICU, but's big. ICU works GREAT though.
> 
> No idea on what ICU is.

I'm pretty sure that the reason why it isn't working is because NPP is detecting it as ANSI, NOT UTF-8. I looked at the NPP source code for UTF-8, and the code seems fine.

**Comment by sasumner** [comment]
>NPP handles UTF-8 as a special case, and it looks like it works.

I posted UTF-8 files where it clearly doesn't work.
For the files where it reads them in wrongly, yes, it appears to detect them as ANSI, but that is because it is doing it wrongly.

>I looked at the NPP source code for UTF-8, and the code seems fine.

For my "bad" files, the code makes 2 calls to Scintilla's SCI_APPENDTEXT.
The first call includes 1 (or 2, or 3) bytes of the 4-byte Unicode character at the end of the text buffer to append.
The second call includes 3 (or 2, or 1) bytes of the 4-byte Unicode char. at the start of the text buffer to append.
This doesn't seem like fine UTF-8 processing code to me.

**Comment by BiBi-Abc** [comment]
> 
> 
> > NPP handles UTF-8 as a special case, and it looks like it works.
> 
> I posted UTF-8 files where it clearly doesn't work.
> For the files where it reads them in wrongly, yes, it appears to detect them as ANSI, but that is because it is doing it wrongly.
> 
> > I looked at the NPP source code for UTF-8, and the code seems fine.
> 
> For my "bad" files, the code makes 2 calls to Scintilla's SCI_APPENDTEXT.
> The first call includes 1 (or 2, or 3) bytes of the 4-byte Unicode character at the end of the text buffer to append.
> The second call includes 3 (or 2, or 1) bytes of the 4-byte Unicode char. at the start of the text buffer to append.
> This doesn't seem like fine UTF-8 processing code to me.

Encoding detection without BOM can **NEVER** be 100% correct.

The UTF-8 processing code is here:
https://github.com/notepad-plus-plus/notepad-plus-plus/blob/a1031517742c7ef600b825bf9f193b3f2740dff6/PowerEditor/src/MISC/Common/Common.cpp#L416

**Comment by sasumner** [comment]
>Encoding detection without BOM can NEVER be 100% correct.

So it took me a while, but I think I've come around to believing this (I'm not thinking about the BOM part, because the vast majority of UTF-8 will not have any BOM).
With Notepad++ using a multi-part read to pull a file in, a multibyte UTF-8 character could occur on the boundary no matter what the size of the buffer.  So I think for UTF-8 this is just one of those undesirable situations that just "is", and must remain that way.

I originally added the "verified" and "bug" labels due to my earlier findings with (and only with) UTF-8 files.
I am removing those labels now due to these later "discoveries".
This issue can remain open for the "other encodings" aspects, in the hopes that someone else with more experience in those encodings can evaluate and if indeed necessary, fix.

>The UTF-8 processing code is here: Common.cpp Line 416

BTW, That is _some_ UTF-8 code, but it isn't involved in loading a UTF-8 file, whether that file is one of my "good" ones or one of my "bad" ones....unless you have some counter-evidence.  I set a breakpoint on it for the file loads I was doing, and it never hit it.

**Comment by BiBi-Abc** [comment]
> With Notepad++ using a multi-part read to pull a file in, a multibyte UTF-8 character could occur on the boundary no matter what the size of the buffer. So I think for UTF-8 this is just one of those undesirable situations that just "is", and must remain that way.

Well not really IMO. For UTF-8, you can just go to end of buffer and start scanning previous bytes until you find UTF-8 lead byte. Then, just use every full UTF-8 character. Then, copy the leftovers to the current buffer and repeat.

Also, I'm sure it's used in UTF-8 file processing because `loadFileData` method calls a function which should come to that.

**Comment by sasumner** [comment]
>Well not really IMO. For UTF-8, you can just go to end of buffer and start scanning previous bytes until you find UTF-8 lead byte. Then, just use every full UTF-8 character. Then, copy the leftovers to the current buffer and repeat.

That is a good idea!

**Comment by sasumner** [comment]
Original complaint seems to be solved by #9599 and/or #9797

End of the test file now shows the Greek character:

![image](https://user-images.githubusercontent.com/30118311/117079820-90781880-ad0a-11eb-9c15-6bab065593c9.png)

I'll continue to look into the discussion of tangential topics raised, potentially opening new issue(s) as necessary.

**Comment by ValZapod** [comment]
Still not fixed in those files. Seriously? 
[test_utf8__131080__BAD.txt](https://github.com/notepad-plus-plus/notepad-plus-plus/files/6836629/test_utf8__131080__BAD.txt)
[test_utf8__131079__BAD.txt](https://github.com/notepad-plus-plus/notepad-plus-plus/files/6836630/test_utf8__131079__BAD.txt)
[test_utf8__131081__BAD.txt](https://github.com/notepad-plus-plus/notepad-plus-plus/files/6836631/test_utf8__131081__BAD.txt)
