### ISSUE TITLE
Tray Icon: the 32x32 image is re-scaled to 16x16

### ISSUE THREAD

**Issue by Yaron10** [notepad-plus-plus/notepad-plus-plus#8971]
**STR:**
Check `Preferences -> MISC. -> Minimize to system tray`.
Minimize NPP.

**Result:** 
The 32x32 image is re-scaled to 16x16.

![תמונה](https://user-images.githubusercontent.com/10229320/95330338-13d6a600-08b1-11eb-9e7a-5ae9679b7790.png)

***
Notepad++ v7.9   (32-bit)
Build time : Oct  4 2020 - 23:15:47
Path : C:---\notepad++.exe
Admin mode : ON
Local Conf mode : ON
OS Name : Windows 7 Enterprise (32-bit) 
OS Build : 7601.23964
Current ANSI codepage : 1255
Plugins : ComparePlus.dll HTMLTag_unicode.dll MenuIcons.dll PythonScript.dll _CustomizeToolbar.dll

**Comment by Yaron10** [comment]
@ozone10,

Another GUI improvement. Could you please test it and submit a PR?

https://github.com/notepad-plus-plus/notepad-plus-plus/blob/9c15bdc236d5f62f4f418f26bee189638a380f86/PowerEditor/src/Notepad_plus.cpp#L440

https://github.com/notepad-plus-plus/notepad-plus-plus/blob/9c15bdc236d5f62f4f418f26bee189638a380f86/PowerEditor/src/NppBigSwitch.cpp#L2540

Replace with:
```
HICON icon;
::LoadIconMetric(_pPublicInterface->getHinst(), MAKEINTRESOURCE(IDI_M30ICON), LIM_SMALL, &icon);
_pTrayIco = new trayIconControler(hwnd, IDI_M30ICON, NPPM_INTERNAL_MINIMIZED_TRAY, icon, TEXT(""));
```

Thank you!

**Comment by ozone10** [comment]
@Yaron10 
sorry I am currently busy until end of march.
`LoadIconMetric` and `LoadIconWithScaleDown` sometimes don't work correctly,
but scale better than `LoadImage`.
Since both `LoadIconWithScaleDown` and `LoadImage` have some parameters same I would use
```
const int cx = ::GetSystemMetrics(SM_CXSMICON);
const int cy = ::GetSystemMetrics(SM_CYSMICON);
const auto lpbmp = MAKEINTRESOURCE(IDI_M30ICON);
HICON icon = nullptr;
if (::LoadIconWithScaleDown(_pPublicInterface->getHinst(), lpbmp, cx, cy, &icon) != S_OK)
{
	icon = static_cast<HICON>(::LoadImage(_pPublicInterface->getHinst(), lpbmp, IMAGE_ICON, cx, cy, LR_DEFAULTCOLOR));
}
_pTrayIco = new trayIconControler(hwnd, IDI_M30ICON, NPPM_INTERNAL_MINIMIZED_TRAY, icon, TEXT(""));
```

**Comment by Yaron10** [comment]
@ozone10,



> LoadIconMetric and LoadIconWithScaleDown sometimes don't work correctly,

Interesting.
Your code works like a charm.

Thank you for looking into it. I appreciate it. 👍
