### ISSUE TITLE
Network drives are not visible when I run as administrator

### ISSUE THREAD

**Issue by MayankHatsOff** [notepad-plus-plus/notepad-plus-plus#8976]
### Description of the Issue
This is extremely strange, if I run Notepad++ normally, I can see network drive in Open File Dialog, but if I run as administrator I don't.

### Steps to Reproduce the Issue

1. Run Notepad++ as administrator 
2. Click Ctrl + O for Open File
3. Check for Network Drive

### Expected Behavior

Network Drives should be there.

### Actual Behavior

I can't see network drives.

### Debug Information

**When I can see Network Drive**
Notepad++ v7.9   (64-bit)
Build time : Sep 22 2020 - 03:19:04
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS Name : Windows 10 Home (64-bit) 
OS Version : 2004
OS Build : 19041.508
Current ANSI codepage : 1252
Plugins : mimeTools.dll NppConverter.dll NppExport.dll 

**When I can't see Network Drive**
Notepad++ v7.9   (64-bit)
Build time : Sep 22 2020 - 03:19:04
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : ON
Local Conf mode : OFF
OS Name : Windows 10 Home (64-bit) 
OS Version : 2004
OS Build : 19041.508
Current ANSI codepage : 1252
Plugins : mimeTools.dll NppConverter.dll NppExport.dll

**Comment by ArkadiuszMichalski** [comment]
@MayankHatsOff Debug Information has been listed here not for fun.

**Comment by MayankHatsOff** [comment]
@ArkadiuszMichalski I didn't understood what you mean. I have no idea what to add in Debug Information

**Comment by ArkadiuszMichalski** [comment]
When you open bug you get instruction:
```
### Debug Information
<!--- In your Notepad++, click on the "?" menu (found to the right of "Window" in the menu bar) -->
<!--- In the menu that drops down, choose "Debug Info..." -->
<!--- A message box will open detailing specifics about your Notepad++ version, plugins, etc. -->
<!--- CLICK ON THE BLUE LINK with the text "Copy debug info into clipboard" -->
<!--- Do a PASTE HERE -->
```

**Comment by MayankHatsOff** [comment]
@ArkadiuszMichalski Oops. I missed it. Sorry for that, updated debug info. Thanks for pointing out.

**Comment by dodmi** [comment]
Actually, I think this is not a problem with Notepad, but default behavior from Windows.
[Enable linked connections](https://docs.microsoft.com/en-us/troubleshoot/windows-client/networking/mapped-drives-not-available-from-elevated-command).

**Comment by sasumner** [comment]
@MayankHatsOff In light of @dodmi 's comment, can you tell us how Windows' `Notepad.exe` performs in this situation?

**Comment by MayankHatsOff** [comment]
I tried both Updating both using "Local Group Policy Editor" & directly registry. Still not working ... Please find attached screen shots. I was already aware of these settings. I did some google for this issue & some users had suggested this solution, but it didn't work for.
![NPP](https://user-images.githubusercontent.com/72543399/95558950-a3f12880-0a34-11eb-9d4d-cea069230918.png)
![NPP 2](https://user-images.githubusercontent.com/72543399/95558955-a5225580-0a34-11eb-9fde-348e529a6b99.png)

**Comment by dodmi** [comment]
There's missing an S in EnableLinkedConnection**s**, but I can't get it to work in Windows 10 2004 anymore.

Anyway - it's a Windows thing, open plain Notepad and you'll see, there's also no network share...

Another workaround is mapping the drives as an admin:
* Open an elevated command prompt and type *net use*
* You'll get a list of all your mapped network drives.
* For each drive you need type *net use letter: \\\\server\\path  /persistent:yes*

This should make them available in the elevated session.

**Comment by MayankHatsOff** [comment]
So basically I need to map network drive 2 times. 1 using normal & second one while opening command prompt as administrator. 

And yes it is confirmed that this is not an issue with notepad++, it is general windows issue & happens with all other applications as well.

Thanks for all the help. 👍 

@ArkadiuszMichalski You may close this issue now.

**Comment by sasumner** [comment]
@MayankHatsOff As the issue creator, you should have a Close button and can close it.
But I will do it for you.
