### ISSUE TITLE
Search and Replace regular Expressions

### ISSUE THREAD

**Issue by cannothing** [notepad-plus-plus/notepad-plus-plus#8977]
### Description of the Issue
I am searching with regular expressions with this term:
`\-"([1-4]{1,4})([←↑→↓↔↕↖↗↘↙]{1,4})"`

If I am using the search, I get matches.

If I am using "Search and replace" I do not get matches.

Exampletext: `-"4↑"`
### Debug Information
Notepad++ v7.8.7   (32-bit)
Build time : Jun  5 2020 - 02:34:28
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS Name : Windows 10 Enterprise (64-bit) 
OS Version : 2004
OS Build : 19041.508
Current ANSI codepage : 1252
Plugins : ComparePlugin.dll mimeTools.dll NppConverter.dll NppExport.dll NppFTP.dll NppQrCode32.dll NppXmlTreeviewPlugin.dll XMLTools.dll

**Comment by ArkadiuszMichalski** [comment]
What do you mean "Search and replace", in `Replace` window you press `Replace` button, or `Find next` + `Replace`?

I get this result:
1. when press `Replace All` will find and replace all in one shot
2. when press `Replace` (without any selection)  will firstly find and select `-"4↑"`, second shot will replace.
3. when select only `-"4↑"` and press `Replace` then replace works.
4. when select more text (including `-"4↑"`) without checked `In selection`  get same as 2. 
5. when select more text (including `-"4↑"`) and checked `In selection` get same as 2. 

Above is standard behavior for this operation, even when `Find what` is `a`, `Replace with` is `b`, search mode is `Normal` or `Regex`.

Looks like `Replace` firstly need find text (or before press it must have selected text without any additional characters).

**Comment by cannothing** [comment]
For answering your question, I made screenshots.

Using the search term with search (Strg+F) there is no match
![Search](https://user-images.githubusercontent.com/8529094/95447315-d4b45d80-0961-11eb-992d-02ada527dded.PNG)

Using the search term with search and replace (Strg+H) there is no match

![Search and replace](https://user-images.githubusercontent.com/8529094/95447316-d4b45d80-0961-11eb-9166-0865d54d3aba.PNG) 

Using search (Strg+F) "Find all in active file" there is one match
![Search all in active file](https://user-images.githubusercontent.com/8529094/95447311-d3833080-0961-11eb-9dbe-e3a152b4082d.PNG)

**Comment by ArkadiuszMichalski** [comment]
For me works fine. You can try with last NPP version, and also without any pluging. Try download portable version and make test. After then you can remove it. Also what encoding you use for file?
https://notepad-plus-plus.org/downloads/v7.9/
And for easier discussion try not change English localization:)

**Comment by ArkadiuszMichalski** [comment]
Maybe your carret is  behind this string? Try select `Wrap around` option.

**Comment by sasumner** [comment]
I have no problems with this search, using 7.8.9.
The only thing I can think of as the problem is caret-positioning before initiating the search.
I would manually put the caret at top-of-file, rather than ticking _Wrap around_ (but that should work as well).

**Comment by cannothing** [comment]
> 
> 
> For me works fine. You can try with last NPP version, and also without any pluging. Try download portable version and make test. After then you can remove it. Also what encoding you use for file?
> https://notepad-plus-plus.org/downloads/v7.9/
Updating solved the issue. Thank you very much.
