### ISSUE TITLE
PHP language highlighting problem with non-English characters

### ISSUE THREAD

**Issue by igll** [notepad-plus-plus/notepad-plus-plus#8979]
Sometimes a whole word containing non-English characters is language-highlighted incorrecly

1. Save this code as Prueba.php:

`
	<?php
	define("Monos",1);
	define("Moñas",1);
	define("Moños",1);
	define("Tías",1);

	echo Monos;
	echo Moñas;
	echo Moños;
	echo Tías;
	?>
`

![example](https://user-images.githubusercontent.com/15997199/95478832-56b87c80-098a-11eb-8f82-398afd900ae9.png)

It is expected to show these 4 identifiers Monos, Moñas, Moños and Tías as 4 correct words.

But Moñas is shown as 2 separated words: "Moñ" and another "as". Same happens to "Tías".

It seems that "as" is detected as a "native identifier separated from previous letters".

Debug info:
Notepad++ v7.8.7   (32-bit)
Build time : Jun  5 2020 - 02:34:28
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS Name : Windows 10 Home (64-bit) 
OS Version : 2004
OS Build : 19041.546
Current ANSI codepage : 1252
Plugins : ComparePlugin.dll LuaScript.dll mimeTools.dll NppConverter.dll NppExport.dll NppFTP.dll Tidy2.dll

**Comment by ArkadiuszMichalski** [comment]
Interesting, not happend for other lexers, you can report this bug to Scintilla (for `LexHTML.cxx`): https://sourceforge.net/p/scintilla/bugs/.

**Comment by igll** [comment]
Thanks for the tip!
Done: https://sourceforge.net/p/scintilla/bugs/2216

**Comment by igll** [comment]
Solved at present version.
