### ISSUE TITLE
[Feature Request] style tokens: "in use" indicator; color preview; more style tokens

### ISSUE THREAD

**Issue by Archangel1C** [notepad-plus-plus/notepad-plus-plus#8983]
1) It would be nice, if the entries in the _style token_ menu had an indicator, if they are currently used, so you cannot use the same token for different markings by accident (assuming f.i., that you want to mark certain words, but in different colors).

2) While you are at it, you could add a box showing the color of the style to the menu entries

3) Is where a specific reason, why there are only 5 different styles available? Is this configurable? For certain tasks/workflows it would be useful to have more styles.

**Comment by sasumner** [comment]
For 1 : I suppose the user is supposed to remember which ones they have previously used.  In years of using Notepad++, this is not really a problem.

For 2 : Not a bad idea! :-)

For 3 : 5 was just chosen as a useful number for most people.  You can get one more by using the _Mark_ feature in the _Search_ menu.  Using a scripting plugin can also give you more if you want to do some programming to achieve it.

**Comment by sasumner** [comment]
Preview of a possible implementation for point 2 :

![image](https://user-images.githubusercontent.com/30118311/96123753-48ee8400-0ec1-11eb-858b-8a491d24e871.png)
