### ISSUE TITLE
Different sub system versions in developer builds and release builds

### ISSUE THREAD

**Issue by Uhf7** [notepad-plus-plus/notepad-plus-plus#8984]
### Description of the Issue
Windows dialog box functions behave different, depending on the sub system version in the `.exe` header. Because of this, the sub system versions in the `.exe` headers should be the same for developer builds made with the `notepadPlus.vcxproj` file from the repository and for release builds made by @donho. Unfortunately, this is currently not the case:

	Developer and AppVeyor builds, 32-Bit, wrong behavior:
		Required OS version           	6.00
		Image version                 	1.00
		Subsystem version             	6.00

	Release Builds, 32-Bit, correct behavior:
		Required OS version           	5.01
		Image version                 	1.00
		Subsystem version             	5.01

	Developer and Appveyor builds, 64-Bit, wrong behavior:
		Required OS version           	6.00
		Image version                 	1.00
		Subsystem version             	6.00

	Release Builds, 64-Bit, correct behavior:
		Required OS version           	5.02
		Image version                 	1.00
		Subsystem version             	5.02

### Steps to Reproduce the Issue

1.  Build Notepad++ on your own computer using the `notepadPlus.vcxproj` from the repository.
2.  Start it, open Settings -> Preferences -> Language -> Tab size

### Expected Behavior
![TabSize_501](https://user-images.githubusercontent.com/40629737/95600670-c98d2a80-0a52-11eb-8e6d-20ee1fdd2992.png)

### Actual Behavior
![TabSize_600](https://user-images.githubusercontent.com/40629737/95600739-da3da080-0a52-11eb-9067-a24d56030ed1.png)

----

This is not the only negative effect, but it is an easy-to-reproduce example. There is another example in #8144 too. The real downside here is, that any developer working on dialog box functions may create results that differ from the release build.

To overcome this, the following compiler setting has to be modified: `Linker -> System -> Minimum Required Version`.
For 32-Bit Versions, it has to be `5.01` instead of empty, for 64-bit versions, it has to be `5.02`.

### Debug Information
Notepad++ v7.9   (32-bit)
Build time : Sep 22 2020 - 03:24:22
Path : C:\Tools\Npp\notepad++.exe
Admin mode : OFF
Local Conf mode : ON
OS Name : Windows 10 Pro (64-bit)
OS Version : 1607
OS Build : 14393.576
Current ANSI codepage : 1252
Plugins : DSpellCheck.dll LuaScript.dll mimeTools.dll NppConverter.dll NppExport.dll

**Comment by sasumner** [comment]
@Uhf7 Nice find!

**Comment by Uhf7** [comment]
Experiment #8985 shows, that it works as expected for the AppVeyor artifacts.

**Comment by donho** [comment]
https://github.com/notepad-plus-plus/notepad-plus-plus/commit/e2a650ec1054610267ee49b0dea0b0c458bc19ad
