### ISSUE TITLE
[Feature Request] Allow Copy/Cut the whole current line when there is no text selected (like other IDEs)

### ISSUE THREAD

**Issue by LazaroOnline** [notepad-plus-plus/notepad-plus-plus#8989]
### Description of the Issue
Allow Copy/Cut the whole current line when there is no text selected

### Steps
Place the cursor in a line with some text and no text selected, then press `Control+C` or `Control+X`.

### Expected Behavior
The current line where the cursor is should get copied or cut depending on the command.

### Actual Behavior
Now it is doing nothing.

Other IDEs like Visual Studio, and Visual Studio Code does this ever since I can remember and it is very useful to move code around.

**Comment by sasumner** [comment]
Closing as duplicate of #18
