### ISSUE TITLE
Increase size of line count in status bar for big files

### ISSUE THREAD

**Issue by VictorRosenfeld** [notepad-plus-plus/notepad-plus-plus#8993]
![NotepadLineCount](https://user-images.githubusercontent.com/49409296/95707550-45fe5400-0c73-11eb-836d-289013524634.png)

### Steps to Reproduce the Issue

1. 
2. 
3.

**Comment by ArkadiuszMichalski** [comment]
Duplicate of https://github.com/notepad-plus-plus/notepad-plus-plus/issues/4157.
