### ISSUE TITLE
line number margin would have 1 digit more by default

### ISSUE THREAD

**Issue by rolfmeurer** [notepad-plus-plus/notepad-plus-plus#8996]
I wish the line number margin would have 1 digit more by default so if scrolling down and reaching line number 1000 the screen should not intend. Other editors doing well. Reason: remarks right near by the code should always stay in col, but by scolling, the screen intend @ line 1000 suggests a worng col where no wrong col is.ect.

**Comment by sasumner** [comment]
Closing as duplicate of #5670
