### ISSUE TITLE
Copy and Comment Bug

### ISSUE THREAD

**Issue by Jacxkass04** [notepad-plus-plus/notepad-plus-plus#8997]
### Description of the Issue

Pasting the copied text before commenting it is reflecting in copied text on the clipboard.

### Steps to Reproduce the Issue

1. Create 3 lines of codes in PHP file and drag them all
2. Ctrl + C for copy , After copy Keep the selected text and comment it all by using hotkey
3. Ctrl + V paste the  copied code/text and notice that the pasted code/text is also commented.

### Expected Behavior

It should paste the original state code/text

### Actual Behavior

It pasting the copied text but commented.

### Debug Information

Notepad++ v7.8.8   (32-bit)
Build time : Jun 24 2020 - 00:15:36
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS Name : Windows 10 Enterprise (64-bit) 
OS Version : 2004
OS Build : 19041.508
Current ANSI codepage : 1252
Plugins : mimeTools.dll NppConverter.dll NppExport.dll

**Comment by sasumner** [comment]
Please explain further:

* "drag them all" -- drag and drop move the lines?
* "by using hotkey" -- which keycombination?

**Comment by sasumner** [comment]
Closing due to lack of response.
If responses come and it is warranted, will reopen.
