### ISSUE TITLE
Exception at 0x0136C868 when change tabulations settings for javascript

### ISSUE THREAD

**Issue by SoftinHub** [notepad-plus-plus/notepad-plus-plus#8999]
### Description of the Issue

When I want to change the tabulation settings for a specific language, I have a exception when clicking on "Insert spaces"

Note that the error do not occurs for other languages, only javascript !

Can't generate dump file (even when starting NP++ as admin)

### Steps to Reproduce the Issue

1. Start Notepad++  (french)
2. Paramètres/Préférences/Langage
3. Tabulations/Javascript
4. uncheck "Valeur par défaut" (default value)
5. check "Insérer des espaces" (insert spaces)

### Expected Behavior
no error :-)

### Actual Behavior
Exception code 0xC0000005 @ 0x014AC868

### Debug Information
Notepad++ v7.9   (32-bit)
Build time : Sep 22 2020 - 03:24:22
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS Name : Windows 7 Professional (32-bit) 
OS Build : 7601.24544
Current ANSI codepage : 1252
Plugins : MarkdownViewerPlusPlus.dll mimeTools.dll NppConverter.dll NppExport.dll NppMarkdownPanel.dll XMLTools.dll 
![Presse-papiers-1](https://user-images.githubusercontent.com/55877430/95839883-cd1afd00-0d43-11eb-9b5b-c3219ec81e1a.png)
![Presse-papiers-2](https://user-images.githubusercontent.com/55877430/95839916-d73cfb80-0d43-11eb-87c9-2e4666ce9e06.png)

**Comment by ArkadiuszMichalski** [comment]
@SoftinHub without plugins you get same problem? Can you check this on new/fresh portable version? I see your languages list is different then my, maybe you have some out of date xml config files.

**Comment by Uhf7** [comment]
Qualified guess: The error does exist since 8e43715baf0ecc48acccc83883f66a5430ad8f20. It only occurs, if "javascript.js" (`L_JAVASCRIPT`) is not in the language list, like shown in the screenshot. So remove the `<Language name="javascript.js" ... />` element from the Langs.xml to reproduce the access violation.

**Comment by SoftinHub** [comment]
Hi, I don't have this error on an other PC with the same version & plugins, it is definitivly a config files pb, but I don't know where :)

**Comment by SoftinHub** [comment]
I do have this section in %appdata%\Notepad++\ langs.xml
```

        <Language name="javascript" ext="js" commentLine="//" commentStart="/*" commentEnd="*/">
            <Keywords name="instre1">abstract boolean break byte case catch char class const continue debugger default delete do double else enum export extends final finally float for function goto if implements import in instanceof int interface long native new package private protected public return short static super switch synchronized this throw throws transient try typeof var void volatile while with true false prototype</Keywords>
        </Language>
```

**Comment by ArkadiuszMichalski** [comment]
Your `langs.xml` is old, remove it (if you haven't changed it) and you will get a fresh version.

**Comment by SoftinHub** [comment]
yep the error is gone...but now I have "javascript" and "javascript.js" in the Tab list settings ... probably another old XML file...

**Comment by ArkadiuszMichalski** [comment]
No, `javascript` is embedded (for example in HTML) and `javascript.js` is external file, the names are quite clear, what was mentioned in bug https://github.com/notepad-plus-plus/notepad-plus-plus/issues/4521.

**Comment by MadManMoon** [comment]
Just for anyone that is as dumb as me and can't parse this thread properly, the workaround for this incident on Windows is to:
1. Close notepad++
2. Goto `%appdata%\Notepad++\`
3. Rename `langs.xml` to `langs.old`
4. Restart notepad++

I would have suggested this as an edit for any of the above comments, but it's not an option. Apologies if this re-opens the incident, that's not the intention, so please close, accordingly. ( _but it would be nice to leave this comment here for future dummies like me!_ )
