### ISSUE TITLE
Unmark is inoperational

### ISSUE THREAD

**Issue by dg9ngf** [notepad-plus-plus/notepad-plus-plus#900]
Steps to reproduce:
1. Select work that occurs a few times in the document
2. Select the menu command "Search; Mark..."
3. Click on "Fin all"
4. Now all ocurrences of the selected work have a red background colour.
5. Select any command from the menu "Search; Unmark all"

Actual result:
Nothing. Still red. It's impossible to get rid of that colour again, I need to close and re-open the document.

Expected result:
Remove that mark colour.

NPP version 6.8.3.

**Comment by cmeriaux** [comment]
Hello,
I dont reproduce this bug. (latest Version, Win 7 x64)
You may have a plugin issue or config issue

**Comment by dg9ngf** [comment]
I'm not aware of any. The only non-default plugin I have installed is ScrollPastEOF. What config options could affect this behaviour?

**Comment by dg9ngf** [comment]
I can reproduce this with factory defaults.

I'm still looking for a screen recorder, I need it for other bug reports as well. Any recommendations?

**Comment by cmeriaux** [comment]
Can you install from scratch ? You may have a old configuration file that cause some troubles

**Comment by dg9ngf** [comment]
I have now installed NPP 6.8.3 in a complete fresh environment, this is now Windows 8.1 x64. It's still the same thing. 100 % reproducible, everywhere.

**Comment by cmeriaux** [comment]
Do you have auto backup option activated ? I don't

**Comment by dg9ngf** [comment]
I can't find any or a single option for "auto backup". But I have everything in defaults now. This is a completely clean environment, a freshly installed Windows with only one other application installed. I use it as clean test environment and can revert it to a snapshot easily. So you should know what my configuration is on that machine. I didn't change it.

**Comment by dg9ngf** [comment]
Here's a [screen recording](http://unclassified.de/tmp/videos/npp-mark.mp4) (MP4 H.264, 950 kB) in a clean Windows 8.1 environment.

**Comment by cmeriaux** [comment]
To remove the mark set, open the mark menu and use the "clear" button.
Those type of mark is a "standard mark".

You also have special mark associated with style 1, style 2, style 3 .....
Use "Mark all / using 1st style" and "Unmark all/ clear 1st style"
Use "Mark all / using 2nd style" and "Unmark all/ clear 2nd style"
....

So you can decorate your code with different mark an navigate among them with "jump up/down 1st style" "jump up/down 2nd style" ......
This beautiful feature makes me preferate Notepad++ than Sublime Text or others.

++
![mark](https://cloud.githubusercontent.com/assets/12024941/9838746/213f04e0-5a65-11e5-893d-9a57221331e1.png)

**Comment by dg9ngf** [comment]
I don't understand anything of what you said. Is it even related to this issue? What is the "mark menu"? Where is the "clear" button? I have not associated anything, I have just installed NPP in a clean environment and used the mark command.

**Comment by h-h-h-h** [comment]
You have a "Clear all marks" button on the find-and-replace dialog. That clears this type of mark.

**Comment by cmeriaux** [comment]
It's a pleasure to help you.

**Comment by h-h-h-h** [comment]
> @cmeriaux:
It's a pleasure to help you.

Did you forget the `<irony>` tags?

**Comment by dg9ngf** [comment]
Ah, inside that dialog... The German translation sounds like "Reset" so I didn't know what you mean. In English the label is "Clear" which is something else maybe. Alright, so it's my fault and this issue can be closed.
