### ISSUE TITLE
Syntax Highlight PowerQuery and DAX

### ISSUE THREAD

**Issue by wanderleihuttel** [notepad-plus-plus/notepad-plus-plus#9002]
Hello

Would be interesting if would be included syntax highlight for PowerQuery and DAX from PowerBI.

**Comment by PBIQueryous** [comment]
YEs please. Need this for github markdown!

**Comment by rdipardo** [comment]
> DAX from PowerBI.

https://github.com/notepad-plus-plus/userDefinedLanguages/blob/master/UDLs/DAX_bySaschaKasper.xml

**Comment by ArkadiuszMichalski** [comment]
Please open one issue for each request. Note that the support for new languages (not via UDL) requires a dedicated lexer, which is provided by the [Lexilla ](https://github.com/ScintillaOrg/lexilla) project. So make a request here first.
