### ISSUE TITLE
Links (ads) on download page can be deceiving

### ISSUE THREAD

**Issue by sasumner** [notepad-plus-plus/notepad-plus-plus#9003]
I'm not sure what if anything can be done about this, but the ad placements on the download page could be confusing some novice users :

![image](https://user-images.githubusercontent.com/30118311/95857626-e2832d80-0d29-11eb-97c2-ab5ec795f753.png)

Something like this is what the user saw (except instead of a Winzip ad it was a "Web Navigator" ad) :

![image](https://user-images.githubusercontent.com/30118311/95857849-39890280-0d2a-11eb-8b07-01740e309f87.png)

**Comment by donho** [comment]
@sasumner 
I have blocked 10+ url and 50+ Ads so far. It will be better for the moment.
If you get some Ads contains "Download", please post url here. I can block these URLs at least.
