### ISSUE TITLE
Replace wont replace with regex lookbehind assertion

### ISSUE THREAD

**Issue by marko-savic** [notepad-plus-plus/notepad-plus-plus#9004]
### Description of the Issue
Replace will not actually replace the character.

### Steps to Reproduce the Issue
1. Open new txt file
2. Add two lines fo example: 
2020-08-31-09:24:26,5.23,4.22,3.64,26
2020-08-31-09:24:27,0.00,0.00,0.00,26
3. Open replace with regex search, try this assertion: Find What: "(?<=:..)," and Replace With: "-"

### Expected Behavior
Matched character ',' is replaced with the character '-'

### Actual Behavior
A match occurs but no actual replacing is done

### Debug Information

Notepad++ v7.9   (64-bit)
Build time : Sep 22 2020 - 03:19:04
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS Name : Windows 10 Pro (64-bit) 
OS Version : 1903
OS Build : 18362.1082
Current ANSI codepage : 1252
Plugins : mimeTools.dll NppConverter.dll NppExport.dll

**Comment by sasumner** [comment]
Some notes:

* The _Expected Behavior_ occurs if a _Replace All_ is done.
* The _Actual Behavior_ occurs if a step-by-step _Replace_ is attempted.

**Comment by sasumner** [comment]
Duplicates/similars:  #713 #1870 #2216 #2360 #5688
