### ISSUE TITLE
hexeditor acess violation

### ISSUE THREAD

**Issue by crogonint** [notepad-plus-plus/notepad-plus-plus#9006]
Not 100% sure this is a bug.. I just updated to current, and when Notepad++ started up it immediately threw an error, something to the effect of:

"There was an error due to hexeditor.dll. The error was access violation."

Um.. what should I do here?

**Comment by sasumner** [comment]
Get a newer HexEditor plugin?
I think from here:
https://github.com/chcg/NPP_HexEdit

**Comment by donho** [comment]
@crogonint Use Plugins Admin to get it - it will be the latest version (bug less).

**Comment by crogonint** [comment]
I could swear I alrady responded to this..  I completely forgot that Plugins Admin doesn't notify me of updates the way the old one did. Sorry to be a bother!!
