### ISSUE TITLE
Replace all locks up

### ISSUE THREAD

**Issue by PDub2020** [notepad-plus-plus/notepad-plus-plus#9007]
I have a file where lines are terminated with ' ~ '.

I tried to do a replace all, changing this to ' ~\n ' .

It locked up Notepad++ . I had to terminate it. 

This does work when I replace them one by one. But replace all is busted.

PLEASE fix this. I truly appreciate it.

I had upgraded Notepad++ to 7.9 . I even downgraded it to 7.8.8, and still had the issue. 

PW
pwolfe00@hotmail.com

P.S. I can't send you the file in question - as it's confidential info. I tried to recreate this by creating a test file. I have attached this. Search for character ' ~ ' doesn't even work?? It didn't freeze up. But perhaps this will help...

[notepadplustestfile.txt](https://github.com/notepad-plus-plus/notepad-plus-plus/files/5377948/notepadplustestfile.txt)

### Steps to Reproduce the Issue

1. 
2. 
3.

**Comment by sasumner** [comment]
>Search for character ' ~ ' doesn't even work??

Works for me, in same version.

>It locked up Notepad++ . I had to terminate it.

Without more to go on, this can't be pursued further.

If more information is provided, will consider reopening, but for now, Closing...
