### ISSUE TITLE
Often nothing happens when double clicking on find in files results

### ISSUE THREAD

**Issue by crystalfp** [notepad-plus-plus/notepad-plus-plus#9009]
### Description of the Issue

When I do a normal "find in files" search often in the results window clicking on a result line does nothing.

### Steps to Reproduce the Issue

1. Put the attached file in an empty directory
2. Load it
3. Open “Find in files”
4. Search for `stupiscono` in *.txt (“Normal” search in all subfolders, no other checked option)
5. In the search results window you have one result line from the file (see attached screenshot)
6. Double click on it. Nothing happens.

### Expected Behavior
The editor cursor goes to line containing `stupiscono`

### Actual Behavior
Nothing happens.
If you delete lines after the matching line suddenly the double click works again. Deleting lines before the matching line seems have no effect.
In the results window, if you collapse the Search "stupiscono" section, the matching line is not collapsed and remains visible, as if it is not part of this section.

### Debug Information
Notepad++ v7.9 (32-bit)
Build time : Sep 22 2020 - 03:24:22
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS Name : Windows 10 Enterprise (64-bit)
OS Version : 2004
OS Build : 19041.508
Current ANSI codepage : 1252
Plugins : ComparePlugin.dll DSpellCheck.dll HexEditor.dll HTMLTag_unicode.dll MarkdownViewerPlusPlus.dll mimeTools.dll NppConverter.dll NppExec.dll NppExport.dll NppFavorites.dll NppFTP.dll NPPJSONViewer.dll NppSaveAsAdmin.dll NppTextFX.dll XMLTools.dll _CustomizeToolbar.dll

The file to reproduce the problem: [bug.txt](https://github.com/notepad-plus-plus/notepad-plus-plus/files/5378450/bug.txt)

![image](https://user-images.githubusercontent.com/865866/95996819-62e18580-0e33-11eb-92aa-d7793451e21a.png)

**Comment by pryrt** [comment]
I could not reproduce -- [more details in the forum](https://community.notepad-plus-plus.org/post/58586)

![](https://i.imgur.com/EjxCyat.gif)

I get the same results in v7.9 64-bit (shown) or 32-bit (not shown).

**Comment by crystalfp** [comment]
It is utf8. In line 4 you can find the «» characters utf8 encoded.

**Comment by crystalfp** [comment]
Try to duplicate the file as bug2.txt and redo the search. You find a line in each file. One has the problem, the other not.

**Comment by ArkadiuszMichalski** [comment]
I can confirm, search works, but double click not, I haven't figured out why yet.

**Comment by Uhf7** [comment]
I can kind of reproduce it too. I can even do repeated searches for "stupiscono", which produce multiple result lines in the Find Results window. Some result lines work, some not. 

The visual difference between the result lines working and the result lines not working is: 
- Working results have a folding icon ([+]) in the line where the file name is displayed.
- "Broken" results have no icon in the line where the file name is displayed.

**Comment by sasumner** [comment]
Possibly related: #8525

**Comment by Uhf7** [comment]
@Yaron10, how did you get the find results wrapped?

**Comment by Yaron10** [comment]
@Uhf7,

Implemented by @sasumner and integrated in 7.9.

**Comment by Uhf7** [comment]
Cool new feature. Didn't see it until now. Now I want it in Preferences too, as default setting for the wrap ...

**Comment by Yaron10** [comment]
Yes, it's a useful feature.

> Now I want it in Preferences too

If you check it in the context-menu, it's saved to config.xml.

**Comment by Uhf7** [comment]
> If you check it in the context-menu, it's saved to config.xml.

OK, I just verified this too. I'm happy.

**Comment by Yaron10** [comment]
The flowers to @sasumner. :)

**Comment by guy038** [comment]
Hi, all,

Concerning the **issue**, see my post on **N++ Community** :

https://community.notepad-plus-plus.org/post/58596

Hope that helps a bit !

BR

guy038

**Comment by KnIfER** [comment]
![image](https://user-images.githubusercontent.com/11593903/110307978-e13cff00-8042-11eb-8175-9a6a03e86e2a.png)

**Comment by sasumner** [comment]
@KnIfER Are you saying this bug exists in current release (7.9.3) of Notepad++?  Or just what are you saying?

**Comment by KnIfER** [comment]
It's fixed. But My solution is very simple.

Let me tell how to reproduce this problem.

1. write a **long** line.  `aaaaaaaaaaaaaaaaaaaaa`  *  4096  chars
2. write a secone **long** line. `aaaaaaaaaaaaaaaaaaaaa` *  4096 chars
3. append a unique test search pattern **on or near the terminal** of each lines. so we have:
```
line 1: aaaaa……aaaaaa xtest
line 2:aaaaa……aaaaaa xtest
```

4. then, search  for xtest using "**Find all in current document**".

5. search again , remember to turn on "**Word wrap**" in the result window before you do.


Then you'll see someting similiar to the picture I provided above. It's just something wrong in scintilla, after syntax parsing, the second line is not included in the code folding, and is not "double-clickable". 


If you enable text editing for the result window, and delete one or two chars  on the second line, then the second line will be included in the folding, and become "double-clickable". very interesting.


So the fix provided on my branch is very simple : 

```
	-	str = str.substr(0, SC_SEARCHRESULT_LINEBUFFERMAXLENGTH - lstrlen(endOfLongLine) - 1);
	+	str = str.substr(0, SC_SEARCHRESULT_LINEBUFFERMAXLENGTH - lstrlen(endOfLongLine) - 4);

```

**Comment by sasumner** [comment]
@KnIfER 

>Let me tell how to reproduce this problem.

I could not reproduce this problem in 7.9.5, but it could be because your instructions are not precise enough.

**Comment by KnIfER** [comment]
It's fixed.

**Comment by sasumner** [comment]
Then why are you talking about it??
