### ISSUE TITLE
No menu entry and no ability to define a keyboard shortcut to toggle/switch to document list panel

### ISSUE THREAD

**Issue by dinkumoil** [notepad-plus-plus/notepad-plus-plus#9015]
### Description of the Issue
After getting the ability to toggle/switch to _Project Panel x_ and _Folder as Workspace_ panels in v7.9, the _Document List_ panel is the only sidebar panel which is not operable by keyboard shortcuts and it even has no menu entry to do so, too. The only place to toggle _Document List_ panel is the main preferences dialog. A means to set input focus on it doesn't exist.

### Steps to Reproduce the Issue
1. Open shortcut mapper and search for an entry of _Document List_ panel.
2. Dig into the main menu and try to find a menu entry to toggle/switch to _Docment List_ panel.

### Expected Behavior
At least it should be possible to define a keyboard shortcut to switch to (set input focus to) the _Document List_ panel. To be **consistent**, it would be nice to have the ability to define a keyboard shortcut to toggle _Document List_'s visibility as well. To be **complete**, a menu entry for toggling visibility of _Document List_ would be perfect.

### Actual Behavior
Nothing of the above is available.

### Debug Information
Notepad++ v7.9   (32-bit)
Build time : Sep 22 2020 - 03:24:22
Path : xxx\Notepad++Portable\npp.7.9.bin\notepad++.exe
Admin mode : OFF
Local Conf mode : ON
OS Name : Windows 7 Ultimate (64-bit) 
OS Build : 7601.0
Current ANSI codepage : 1252
Plugins : AutoCodepage.dll BetterMultiSelection.dll BracketsCheck.dll ChangedLines.dll CodeAlignmentNpp.dll ComparePlugin.dll Explorer.dll ExtSettings.dll LanguageHelp.dll LuaScript.dll mimeTools.dll NavigateTo.dll NppColumnSort.dll NppConverter.dll NppEventExec.dll NppExec.dll NppExport.dll NppFTP.dll NppGist.dll NppHasher.dll NppHorizontalRuler.dll NppMarkdownPanel.dll NppSaveAsAdmin.dll NppTextFX.dll NppToolBucket.dll NppUISpy.dll NppYEtc.dll OpenSelection.dll pork2sausage.dll ReloadFile.dll SelectQuotedText.dll SurroundSelection.dll XMLTools.dll _CustomizeToolbar.dll

**Comment by ArkadiuszMichalski** [comment]
Same as https://github.com/notepad-plus-plus/notepad-plus-plus/issues/3526.

**Comment by dinkumoil** [comment]
@ArkadiuszMichalski 

Not really the same. #3526 suggests a menu entry to toggle _Document List_ panel.

My suggestion is mainly to add the ability to create a keyboard shortcut for **switching/setting input focus to** the _Document List panel_. A keyboard shortcut for toggling its visibility or menu entries to achieve both of these functionalities I consider to be optional, especially because this would make the related setting in main preferences dialog obsolet.

**Comment by ArkadiuszMichalski** [comment]
This Document List Panel should be controled as any other similar panels, which means complete option from your proposition (I would also add an icon on the toolbar). But the current state for this panel has been going on for many years:
https://stackoverflow.com/questions/6108193/notepad-show-open-files-on-the-left/10348378
 
What's the point of putting on/off this panel in Preferences? Even the on/off state is not properly detected in the Preferences:
1. Open Preferences and check [x] Show for Docment List Panel.
2. Close Docment List Panel by press top-right [x] icon.

Preferences window still has checked [x] Show for Docment List Panel. Hiding this panel in the Preferences is extremely inconvenient. And yes, I know we can use plugin...

**Comment by sasumner** [comment]
>What's the point of putting on/off this panel in Preferences?

I must say that this location for on/off on has always seemed strange to me...

>Hiding this panel in the Preferences is extremely inconvenient

Agree

**Comment by dinkumoil** [comment]
@ArkadiuszMichalski 

Don't get me wrong, I prefer to have **all** the features I suggested. But since this would take much efford I suggested also a "light-wight" solution to get at least the strongly needed ability to **switch** to the _Document List_ panel by shortcut.

**Comment by ArkadiuszMichalski** [comment]
@dinkumoil I know, I just added a little bit of extra information for people who would possibly take this bug in future.

**Comment by dinkumoil** [comment]
@donho 

Thank you for adding a menu entry, toolbar button and keyboard shortcut for toggeling visibility of document list. These are useful extensions and make the UI more consistent.

But you did not implement the most important detail of this issue: a keyboard shortcut to activate (i.e. set input focus to) the document list panel to be able to navigate through opened documents. Would you mind to add this too?

**Comment by dinkumoil** [comment]
Thank you! Tested and works.

**Comment by donho** [comment]
@dinkumoil 
You're welcome :)

**Comment by ArkadiuszMichalski** [comment]
@donho 
Did you forget to add `"Switch to Document List"` to the `english.xml file`? 
https://github.com/notepad-plus-plus/notepad-plus-plus/blob/master/PowerEditor/installer/nativeLang/english.xml#L615

**Comment by donho** [comment]
@ArkadiuszMichalski 
Indeed. It'll be added in the next release.
