### ISSUE TITLE
[Feature Request] Manage tabs... menu feature extension

### ISSUE THREAD

**Issue by ghYura** [notepad-plus-plus/notepad-plus-plus#9016]
[Feature Request] Manage tabs... menu

### Steps to Reproduce the Issue
1. Launch Notepad ++
2. open some files
3. wait  some seconds
4. open other some files
5. Goto "File -> Manage Tabs..."

### Expected Behavior

New menu present:

[Close tabs, opened since ... to ...]
sub-menu appears for input timespan data 
[Ok] -> tabs with given timespan attributes closed

### Actual Behavior
NOT exists

**Comment by sasumner** [comment]
Sorry, IMO not a valuable feature with appeal to a large number of users.
I'm closing it, but it will remain here for possible future debate.
