### ISSUE TITLE
High Background Battery Usage

### ISSUE THREAD

**Issue by NathanDai5287** [notepad-plus-plus/notepad-plus-plus#9021]
#8926 # Description of the Issue
I left my computer on sleep overnight and the battery was at 0 the next morning. I checked the battery usage, but now there are three notepads. This happened after I downloaded Notepad++, so I assumed that was what was causing it. All of the battery usage was in the background. 

![image](https://user-images.githubusercontent.com/61402904/96261323-27e76b00-0f75-11eb-875c-46bffd26d441.png)
This shows whether it was in use or running in the background. I left my computer running overnight and this is the battery usage in the last 6 hours. 
![image](https://user-images.githubusercontent.com/61402904/96262038-1488cf80-0f76-11eb-9bbf-fbcacacbb2d8.png)

### Debug Information
Notepad++ v7.9   (64-bit)
Build time : Sep 22 2020 - 03:19:04
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS Name : Windows 10 Home (64-bit) 
OS Version : 1909
OS Build : 18363.1139
Current ANSI codepage : 1252
Plugins : mimeTools.dll NppConverter.dll NppExport.dll

**Comment by sasumner** [comment]
Sorry, what does issue 8926 have to do with this??

>This happened after I downloaded Notepad++, so I assumed that was what was causing it

Hmmm.

From the screenshot, you appear to be attributing Windows' `notepad.exe` data to Notepad++ ??

**Comment by NathanDai5287** [comment]
This issue began happening after I switched to Notepad++. The Notepad app without an icon appeared after I downloaded Notepad++.

**Comment by sasumner** [comment]
Hmmmmmmm

**Comment by NathanDai5287** [comment]
I left my computer on again, and checked the battery usage. I couldn't find the random Notepad app without an icon and the Notepad and Notepad++ apps both have 0% usage. iNteREsTiNg
