### ISSUE TITLE
Saving a new document only works the first time.

### ISSUE THREAD

**Issue by click0** [notepad-plus-plus/notepad-plus-plus#9023]
### Description of the Issue

Saving a new document only works the first time.

### Steps to Reproduce the Issue

1. Open a new document
2. Add a couple of lines of text there
3. Save to file (Ctrl + S)
4. Continue further typing
5. Forced saving of the file via Ctrl + S is not active and does not work.

### Expected Behavior

I expect that after step 4 in my tab menu, with the names of open files, the status of the current file has changed - it turns red if the file is not saved.
Saving via Save As (Ctrl + Alt + S) does not have such problems.

### Debug Information
Notepad++ v7.9   (64-bit)
Build time : Sep 22 2020 - 03:19:04
Path : H:\Program Files\Editor\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS Name : Windows 7 Ultimate (64-bit) 
OS Build : 7601.23710
Current ANSI codepage : 1251
Plugins : DSpellCheck.dll mimeTools.dll nppAutoDetectIndent.dll NppConverter.dll NppExport.dll NppJumpList.dll NppSnippets.dll SessionMgr.dll

**Comment by sasumner** [comment]
@click0 
It seems to have similarity to #8287 -- what do you think?

**Comment by click0** [comment]
Yes, this is my bug.

**Comment by sasumner** [comment]
Okay, so let's close yours as a duplicate and leave that other one open.

**Comment by donho** [comment]
@click0 It's bug of Session Manager plugin - remove SessionMgr.dll manually or uninstall it via Plugin Admin will solve your problem.
