### ISSUE TITLE
Open File at Line doesn't always jump to the line

### ISSUE THREAD

**Issue by jankrassnigg** [notepad-plus-plus/notepad-plus-plus#9041]
### Description of the Issue

When I use [grepWin](https://tools.stefankueng.com/grepWin.html) to open a text file at a specific line, Notepad++ won't always jump to the desired line. It will always open the correct file, but often it stays at the top of the file. However, if I open the file a second time from within grepWin, while np++ still has the file open, it will jump to the correct line.
If, however, I close the file in np++ before opening it again from grepWin, I will typically get the same incorrect behavior again.

Note that this doesn't happen always (but on my machine with a very high probability), so maybe it's a timing issue.

### Steps to Reproduce the Issue

See description above. I used grepWin when I noticed the issue, but you can probably reproduce this in any way that opens a file at a specific line.

### Expected Behavior

It should always jump to the specified line when opening a file.

### Actual Behavior

It sometimes stays at the top of the file.

### Debug Information

Notepad++ v7.8.8   (32-bit)
Build time : Jun 24 2020 - 00:15:36
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS Name : Windows 10 Enterprise (64-bit) 
OS Version : 2009
OS Build : 19042.572
Current ANSI codepage : 1252
Plugins : mimeTools.dll NppConverter.dll NppExport.dll NppFTP.dll

**Comment by Yaron10** [comment]
@jankrassnigg,

Fixed in 7.8.9.
https://community.notepad-plus-plus.org/topic/19715/notepad-v7-8-9-released.

**Comment by jankrassnigg** [comment]
Awesome! I'm surprised I wasn't on the latest version, I thought it had updated just a few days ago :-|

Thanks anyway!

**Comment by Yaron10** [comment]
You're welcome.

**Comment by ArkadiuszMichalski** [comment]
@Yaron10 this fix aply to https://github.com/notepad-plus-plus/notepad-plus-plus/issues/8007?

**Comment by Yaron10** [comment]
@ArkadiuszMichalski,

Yes, it should fix 8007.
Note: related https://github.com/notepad-plus-plus/notepad-plus-plus/issues/8679 is still valid.
