### ISSUE TITLE
Preferences window title bar not on-screen; hard to move window

### ISSUE THREAD

**Issue by sasumner** [notepad-plus-plus/notepad-plus-plus#9043]
### Description of the Issue
It is possible to get the _Preferences_ window to appear such that its title bar is off-screen (above the top of the monitor).  Because the title bar is not "grabbable" via the mouse, it is hard to reposition the _Preferences_ window in order to see all of its content.

### Steps to Reproduce the Issue

1. Make the Notepad++ main window small vertically, and put it near the top edge of your monitor
2. Go to the _Settings_ menu
3. Choose _Preferences..._

### Expected Behavior
_Preferences_ window fully on-screen when it appears (or at least its title bar is "mouse click-draggable").

### Actual Behavior

![image](https://user-images.githubusercontent.com/30118311/96757227-279b0580-13a3-11eb-9786-fa5b9cb34973.png)

### Debug Information
Notepad++ v7.9   (32-bit)
Build time : Sep 22 2020 - 03:24:22
Path : C:\.........\npp.7.9.portable\notepad++.exe
Admin mode : OFF
Local Conf mode : ON
OS Name : Windows 10 Enterprise (64-bit) 
OS Version : 1809
OS Build : 17763.1457
Current ANSI codepage : 1252
Plugins : mimeTools.dll NppConverter.dll NppExport.dll

**Comment by ArkadiuszMichalski** [comment]
Not duplicate of https://github.com/notepad-plus-plus/notepad-plus-plus/issues/8274?

**Comment by sasumner** [comment]
@ArkadiuszMichalski Nice catch; closing this as duplicate.
