### ISSUE TITLE
In user defined language escape is ignored

### ISSUE THREAD

**Issue by crystalfp** [notepad-plus-plus/notepad-plus-plus#9050]
### Description of the Issue

I have a User Defined Language definition for Markdown. Single asterisk normally delimit italic text. If I want to have a literal asterisk I escape it `\*` but the escape character seems ignored. 

In Delimiter 6 style there is: Open: `*` Escape: `\` Close: `*` (see below the`AppData\Roaming\Notepad++\userDefineLangs\userDefinedLang-markdown.default.modern.xml` file. Is it the right one?).

### Steps to Reproduce the Issue

1. Using the `userDefinedLang-markdown.default.modern.xml` language file.
2. Open a file and set its language to markdown.
3. Write in it: `war novel, M\*A\*S\*H. He had worked` on a single line followed by Enter.

### Expected Behavior
Asterisk is a normal character.

### Actual Behavior
`He had worked` is in italic. There are three asterisks, two cancel each other, but the last one is taken as the beginning of italic text.

### Debug Information
Notepad++ v7.9   (32-bit)
Build time : Sep 22 2020 - 03:24:22
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS Name : Windows 10 Enterprise (64-bit) 
OS Version : 2009
OS Build : 19042.572
Current ANSI codepage : 1252
Plugins : ComparePlugin.dll DSpellCheck.dll HexEditor.dll HTMLTag_unicode.dll MarkdownViewerPlusPlus.dll mimeTools.dll NppConverter.dll NppExec.dll NppExport.dll NppFavorites.dll NppFTP.dll NPPJSONViewer.dll NppSaveAsAdmin.dll NppTextFX.dll XMLTools.dll _CustomizeToolbar.dll 

### File userDefinedLang-markdown.default.modern.xml
```
<NotepadPlus>
    <UserLang name="Markdown (Default)" ext="md markdown" udlVersion="2.1">
        <Settings>
            <Global caseIgnored="yes" allowFoldOfComments="no" foldCompact="no" forcePureLC="2" decimalSeparator="0" />
            <Prefix Keywords1="yes" Keywords2="yes" Keywords3="yes" Keywords4="yes" Keywords5="yes" Keywords6="yes" Keywords7="yes" Keywords8="no" />
        </Settings>
        <KeywordLists>
            <Keywords name="Comments">00# 01 02((EOL)) 03&lt;!-- 04--&gt;</Keywords>
            <Keywords name="Numbers, prefix1"></Keywords>
            <Keywords name="Numbers, prefix2"></Keywords>
            <Keywords name="Numbers, extras1"></Keywords>
            <Keywords name="Numbers, extras2"></Keywords>
            <Keywords name="Numbers, suffix1">.</Keywords>
            <Keywords name="Numbers, suffix2">.</Keywords>
            <Keywords name="Numbers, range"></Keywords>
            <Keywords name="Operators1">@ &lt; &gt; \&lt; \&gt; \\ \` \* \_ \{ \} \[ \] \( \) \# \+ \- \. \! \~ :|: |: :| | \|</Keywords>
            <Keywords name="Operators2">- +</Keywords>
            <Keywords name="Folders in code1, open"></Keywords>
            <Keywords name="Folders in code1, middle"></Keywords>
            <Keywords name="Folders in code1, close"></Keywords>
            <Keywords name="Folders in code2, open"></Keywords>
            <Keywords name="Folders in code2, middle"></Keywords>
            <Keywords name="Folders in code2, close"></Keywords>
            <Keywords name="Folders in comment, open"></Keywords>
            <Keywords name="Folders in comment, middle"></Keywords>
            <Keywords name="Folders in comment, close"></Keywords>
            <Keywords name="Keywords1">http:// (http:// https:// (https:// mailto: (mailto: ftp:// (ftp:// ftps:// (ftps:// (/ /</Keywords>
            <Keywords name="Keywords2">==== ----</Keywords>
            <Keywords name="Keywords3">*** ___</Keywords>
            <Keywords name="Keywords4">** __</Keywords>
            <Keywords name="Keywords5">* _</Keywords>
            <Keywords name="Keywords6">** __</Keywords>
            <Keywords name="Keywords7">* _</Keywords>
            <Keywords name="Keywords8"></Keywords>
            <Keywords name="Delimiters">00![ 00[ 01\ 02] 02] 03``` 03` 03~~~ 04\ 05``` 05((EOL `)) 05~~~ 06*** 07\ 08((EOL ***)) 09** 10\ 11((EOL **)) 12* 13\ 14((EOL *)) 15** 16\ 17((EOL **)) 18* 19\ 20((EOL *)) 21 22 23</Keywords>
        </KeywordLists>
        <Styles>
            <WordsStyle name="DEFAULT" fgColor="333333" bgColor="FFFFFF" fontName="" fontStyle="0" nesting="0" />
            <WordsStyle name="COMMENTS" fgColor="808080" bgColor="FFFFFF" fontName="" fontStyle="2" nesting="0" />
            <WordsStyle name="LINE COMMENTS" fgColor="FF8000" bgColor="FFFFFF" fontName="" fontStyle="1" nesting="0" />
            <WordsStyle name="NUMBERS" fgColor="0080FF" bgColor="FFFFFF" fontName="" fontStyle="0" nesting="0" />
            <WordsStyle name="KEYWORDS1" fgColor="8000FF" bgColor="FFFFFF" fontName="" fontStyle="0" nesting="0" />
            <WordsStyle name="KEYWORDS2" fgColor="FF8000" bgColor="FFFFFF" fontName="" fontStyle="1" nesting="0" />
            <WordsStyle name="KEYWORDS3" fgColor="000080" bgColor="FFFFFF" fontName="" fontStyle="3" nesting="0" />
            <WordsStyle name="KEYWORDS4" fgColor="000080" bgColor="FFFFFF" fontName="" fontStyle="1" nesting="0" />
            <WordsStyle name="KEYWORDS5" fgColor="000080" bgColor="FFFFFF" fontName="" fontStyle="2" nesting="0" />
            <WordsStyle name="KEYWORDS6" fgColor="000080" bgColor="FFFFFF" fontName="" fontStyle="3" nesting="0" />
            <WordsStyle name="KEYWORDS7" fgColor="000080" bgColor="FFFFFF" fontName="" fontStyle="3" nesting="0" />
            <WordsStyle name="KEYWORDS8" fgColor="333333" bgColor="FFFFFF" fontName="" fontStyle="0" nesting="0" />
            <WordsStyle name="OPERATORS" fgColor="8080FF" bgColor="FFFFFF" fontName="" fontStyle="1" nesting="0" />
            <WordsStyle name="FOLDER IN CODE1" fgColor="333333" bgColor="FFFFFF" fontName="" fontStyle="0" nesting="0" />
            <WordsStyle name="FOLDER IN CODE2" fgColor="333333" bgColor="FFFFFF" fontName="" fontStyle="0" nesting="0" />
            <WordsStyle name="FOLDER IN COMMENT" fgColor="333333" bgColor="FFFFFF" fontName="" fontStyle="0" nesting="0" />
            <WordsStyle name="DELIMITERS1" fgColor="8000FF" bgColor="FFFFFF" fontName="" fontStyle="2" nesting="0" />
            <WordsStyle name="DELIMITERS2" fgColor="008000" bgColor="FFFFFF" fontName="" fontStyle="0" nesting="0" />
            <WordsStyle name="DELIMITERS3" fgColor="000080" bgColor="FFFFFF" fontName="" fontStyle="3" nesting="0" />
            <WordsStyle name="DELIMITERS4" fgColor="000080" bgColor="FFFFFF" fontName="" fontStyle="1" nesting="65600" />
            <WordsStyle name="DELIMITERS5" fgColor="000080" bgColor="FFFFFF" fontName="" fontStyle="2" nesting="32800" />
            <WordsStyle name="DELIMITERS6" fgColor="000080" bgColor="FFFFFF" fontName="" fontStyle="3" nesting="0" />
            <WordsStyle name="DELIMITERS7" fgColor="000080" bgColor="FFFFFF" fontName="" fontStyle="3" nesting="0" />
            <WordsStyle name="DELIMITERS8" fgColor="333333" bgColor="FFFFFF" fontName="" fontStyle="0" nesting="0" />
        </Styles>
    </UserLang>
</NotepadPlus>
```

**Comment by ArkadiuszMichalski** [comment]
@crystalfp 
> He had worked is in italic. There are three asterisks, two cancel each other, but the last one is taken as the beginning of italic text.

But where is italic? Add some print screen. It's not problem for MarkdownViewerPlusPlus plugin?

**Comment by crystalfp** [comment]
Here it is:
![image](https://user-images.githubusercontent.com/865866/97007378-9c0bab00-1541-11eb-82a5-e90c5cf22a08.png)

**Comment by ArkadiuszMichalski** [comment]
You use in-build UDL for markdown? What theme? I can't reproduce this. Maybe try without plugin? Run program with `-noPlugin` argument.

**Comment by crystalfp** [comment]
Yes, I use in-build UDL for markdown. Now I check without plugins.
There is a suspicious thing. Here:
![image](https://user-images.githubusercontent.com/865866/97008279-e5102f00-1542-11eb-9852-54ecd1fe8883.png)
if I push "open UDL folder" nothing happens.
Good suggestion to try the portable one. Asap I will try it.
Thanks for your support!

**Comment by ArkadiuszMichalski** [comment]
Problem with "Open UDL folder" was report here https://github.com/notepad-plus-plus/notepad-plus-plus/issues/8394.

**Comment by crystalfp** [comment]
You are right! With the portable version the problem does not appears anymore. Is it possible that with my installation it takes a definition file from a location that is not the one edited in UDL editor? My np++ is with me since may years and moved between various laptops so is possible that some detritus accumulated somewhere. Do you have any idea where to look? Thanks!

**Comment by ArkadiuszMichalski** [comment]
If it's not plugins problem then you can check this:
https://npp-user-manual.org/docs/user-defined-language-system/#udl-file-locations

**Comment by crystalfp** [comment]
Found. :-(
I had backup to the cloud. Removing it, the markdown definitions returns to the default ones.
So the backup location on the cloud is misleading. It is not a backup, it is an entirely new configuration location! Should I open an issue to clarify this?
Anyway, I close this issue
Thanks for your ideas that put me on the right path!
