### ISSUE TITLE
Applying color (style) to Search-result's Line-Number affects leading space in Find-result window

### ISSUE THREAD

**Issue by sasumner** [notepad-plus-plus/notepad-plus-plus#9052]
### Steps to Reproduce the Issue

1. Open _Settings_ menu, choose _Style Configurator..._
2. Scroll _Language_ down to locate and select _Search result_
3. In _Style_ column, select _Line Number_
4. Set _Background color_ to "black" (default is "white")
5. Set _Foreground color_ to "white" (default is "black")
6. Save and close the _Style Configurator_ window
6. Run any search with non-zero hits that adds output to the _Find result_ window

### Actual Behavior
Observe the new colors apply to the line numbers (good), but the space between `Line` and the number is also affected by the coloring (bad); example:

![image](https://user-images.githubusercontent.com/30118311/97024937-648f0580-1525-11eb-85f6-0ffd1290a7a1.png)

### Expected Behavior
I'd expect to NOT see that space affected by the _Line Number_ styling setting.

### Debug Information
Notepad++ v7.9   (64-bit)
Build time : Sep 22 2020 - 03:19:04
Path : C:\\...........\npp.7.9.portable.x64\notepad++.exe
Admin mode : OFF
Local Conf mode : ON
OS Name : Windows 10 Enterprise (64-bit) 
OS Version : 1809
OS Build : 17763.1457
Current ANSI codepage : 1252
Plugins : mimeTools.dll NppConverter.dll NppExport.dll

**Comment by alankilborn** [comment]
Since the fix of #11119 and its release in Notepad++ 8.4, this issue seems no longer relevant; testing in 8.4.4 (current version as of this writing) to get:

![image](https://user-images.githubusercontent.com/77065706/183131032-513da757-5e74-419f-9d9e-f484a0830c34.png)

Recommend CLOSURE of this item.
