### ISSUE TITLE
Provide a mechanism for plugins to get a Scintilla handle or Document pointer from BufferID.

### ISSUE THREAD

**Issue by Kered13** [notepad-plus-plus/notepad-plus-plus#9055]
The use case here is that you want to retrieve or manipulate text in a file that is not currently in view. For example, when handling a NPPN_FILEOPENED notification the new file is not the "current Scintilla" (unless it is the first file opened when starting NPP).

I can imagine a couple ways this could be accomplished:

* A new message that will create and return a new Scintilla handle for a given BufferID. This handle can be destroyed with NPPM_DESTROYSCINTILLAHANDLE when no longer needed.
* A new message that will return the Document pointer associated with a given BufferID. The plugin can use SCI_SETDOCPOINTER to attach this Document to a Scintilla handle that it has created with NPPM_CREATESCINTILLAHANDLE. This option requires more work from the plugin, but gives the plugin more flexibility. For example it could create a single long-lived Scintilla handle and associated it with multiple Documents in turn. A reverse function (Document pointer to BufferID) might have some utility as well.

I don't mind doing the work to implement this, but I'd like to get your feedback on how you think this should be implemented first.

**Comment by Kered13** [comment]
I would like to start working on this, can it be accepted and assigned to me?

My plan is to go with the second approach I described above, creating a new message:

Document NPPM_GETDOCUMENTFROMBUFFER(BufferID)

**Comment by donho** [comment]
`Document` object should not be used outside of Notepad++.
What do you try to do concretely?

**Comment by Kered13** [comment]
As I said before, I would like to be able to read and modify documents that are in the background. In particular, in response to NPPN_FILEOPENED and SCI_MODIFIED, and possibly other, notifications. As far as I am aware, this is not currently possible for a plugin. I have previously made [a thread](https://community.notepad-plus-plus.org/topic/20207/how-to-get-text-and-or-scintilla-handle-for-background-file) on the plugin development forum where you can see a bit more discussion, but no one came forward with a solution.

What is the security risk of exposing Document? Internally it is a pointer, but as far as the APIs exposed by Scintilla are concerned it is essentially an opaque identifier, so I don't see it how it is any worse than exposing the Scintilla handles.

I will also point out that Document is already indirectly exposed: Since plugins have access to Scintilla handles, they can call SCI_GETDOCPOINTER on them at any time to get a Document pointer. This will persist as a valid reference to the document even when the document is no longer attached to the active Scintilla, and the plugin can attach it to a new Scintilla that it has created with NPPM_CREATESCINTILLAHANDLE. This is a potential workaround for what I am trying to accomplish, but it is clunky and requires that I wait until a file is active before getting a Document pointer to it.

If you are adamant against exposing Document, what do you think about the first suggestion in the original post of providing a message that returns a new Scintilla handle to the requested buffer ID. Internally this would create a new Scintilla handle (as if NPPM_CREATESCINTILLAHANDLE was called) and attach it to the document corresponding to the given buffer ID (using SCI_SETDOCPOINTER).

I can also suggest a third option: A message that takes a Scintilla handle (which the caller must allocate with NPPM_CREATESCINTILLAHANDLE) and a buffer ID and attaches the Document for the buffer to the Scintilla handle.

**Comment by donho** [comment]
OK, from the link you provided I see why you need Document object. Unfortunately, the answer is still no, for the sake of stability and security - when the application is not stable, then crash, there'll be security issue. 
And indeed, if you have the scintilla handle, you can get Document pointer as well. However, we should expose the strictly necessary API but not everything. The fact you have an unclosed window at home, doesn't mean you should keep door widely open when you left your house. 
I don't see either any advantage of your other suggestions - the manipulation of Document outside of Notepad++ is not encouraged.

**Comment by Kered13** [comment]
Acknowledged.

What are you thoughts on plugins receiving Scintilla notification for files that are not the current Scintilla (and thus messages that they can't really do anything about). Likewise, what about receiving NPPN_FILEOPENED (and possibly other notification) for files that are not the current Scintilla? Do you consider this to be a bug? If so I'll open a new issue for it.

**Comment by donho** [comment]
>  Likewise, what about receiving NPPN_FILEOPENED (and possibly other notification) for files that are not the current Scintilla? Do you consider this to be a bug? If so I'll open a new issue for it.

I don't really follow you. Could provide the API you want ?

**Comment by Kered13** [comment]
This is not really about what API I want.

When the NPPN_FILEOPENED notification is sent, the file (as specified by the BufferID provided in the notification) is not usually the current Scintilla. The documentation actually says:

> NPPN_FILEOPENED

> To notify plugins that the current file is just opened

At a minimum this is probably poor documentation, since the file is not the "current file".

But the code could (probably) be changed so that the current scintilla is set to the new file before sending the notification. I'm asking if you consider the current behavior a flaw or something that should be fixed.

**Comment by donho** [comment]
>  I'm asking if you consider the current behavior a flaw or something that should be fixed.

OK, I see what you need:  you need to modify each opened file, but when there are 2 or more files opened, when you try to processing the current one, but it has been switched off, is that your problem? If it is, there's no bug from Notepad++. notification is always sent asyncronically. 
What you can do is collect the buffers via NPPN_FILEOPENED then use NPPM_SWITCHTOFILE to set buffer one by one so you can do whatever you want.
