### ISSUE TITLE
URLs not marked as links in unfocused view

### ISSUE THREAD

**Issue by Yaron10** [notepad-plus-plus/notepad-plus-plus#9056]
**STR:**
Open files `A` and `B` containing some 50 links.
(Do not scroll at this stage).
Move `B` to the other view.
Hover over the unfocused `A` and wheel-scroll down.

**Result:**
The lines revealed after scrolling down in `A` are not marked as links. 

![תמונה](https://user-images.githubusercontent.com/10229320/97081928-68e31d80-160e-11eb-8dc0-8037eae106e5.png)
***
Notepad++ v7.9   (32-bit)
Build time : Oct 23 2020 - 20:53:55
Path : C:\---\notepad++.exe
Admin mode : ON
Local Conf mode : ON
OS Name : Windows 7 Enterprise (32-bit) 
OS Build : 7601.23964
Current ANSI codepage : 1255
Plugins : ComparePlus.dll HTMLTag_unicode.dll MenuIcons.dll PythonScript.dll _CustomizeToolbar.dll

**Comment by Yaron10** [comment]
https://github.com/notepad-plus-plus/notepad-plus-plus/blob/b93f49a67791be6ed19c521b5e20bcb8efd375c2/PowerEditor/src/NppNotification.cpp#L855

Replacing that line with `addHotSpot(notifyView);` solves the issue.

***

Shouldn't we check if both views are visible on calling `addHotSpot(_pNonEditView);`?

**Comment by donho** [comment]
Fix in https://github.com/notepad-plus-plus/notepad-plus-plus/pull/9059

**Comment by Yaron10** [comment]
Thank you @Uhf7 and @donho.
