### ISSUE TITLE
Notepad++ crash (DSpellCheck )

### ISSUE THREAD

**Issue by VvladimirvV** [notepad-plus-plus/notepad-plus-plus#9067]
### Description of the Issue
If start downloading languages, the program closes without a message (windows7 and windows10)

### Steps to Reproduce the Issue
1. DSpellCheck Settings
2. Library Hunspell
3. Download
4. Choice of any language
5. Install Selected

### Expected Behavior
Download and install the language pack

### Actual Behavior
crash

### Debug Information
Notepad++ v7.9   (32-bit)
Build time : Sep 22 2020 - 03:24:22
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS Name : Windows 10 Enterprise (64-bit) 
OS Version : 2009
OS Build : 19042.572
Current ANSI codepage : 1251
Plugins : DSpellCheck.dll mimeTools.dll NppConverter.dll NppExport.dll

**Comment by ArkadiuszMichalski** [comment]
It's plugin problem, you can help its author in bug https://github.com/Predelnik/DSpellCheck/issues/229.

**Comment by VvladimirvV** [comment]
> It's plugin problem, you can help its author in bug [Predelnik/DSpellCheck#229](https://github.com/Predelnik/DSpellCheck/issues/229).

Thanks, waiting new version
