### ISSUE TITLE
Navigating in the "Save As" dialogue by entering 

### ISSUE THREAD

**Issue by mimmiechan** [notepad-plus-plus/notepad-plus-plus#9069]
### Description of the Issue

Not everyone may know this, it is sort of a hidden gem. But in "Save As" dialogues on Windows, if you enter a path to a folder in the "File name" filed and then hit Enter or clicking "Save", it navigates to that folder. I use this extensively. Use system variables to be more effective: e.g. %UserProfile%\Documents, %ProgramFiles%\Notepad++. I also use a "text expansion" free software program called espanso to write out the paths faster. Anyway, in Notepad++, this does not asways work in Notepad++. It seems to be a bug. I believe NPP used to be able to handle these correctly, around a year ago perhaps, but I am not sure. Also, it works in the "Open" dialogue.

I also wonder why NPP does not use the kind of "Save As" and "Open" dialogues that, for example, Notepad, VSCode, Firefox and VLC and uses. These windows have a search box, a Navigation pane on the left-hand side; and allows you to navigate to a folder directly by typing in a path manually in the top pane (the pane that shows which directory you are in, and if you click it, it will become a text field, also a kind of hidden feature.) I am pretty sure this issue is not present on other programs that use the same, simplified, dialogue that NPP currently uses. But I cannot think of any program that does at the moment, so I cannot check.

### Test 1

1. File>New.
2. File>Save As.
3. This PC.
4. In the "File name" text field: write `%UserProfile%\Documents`.
5. Press Enter or click Save.

### Test 1: Expected Behavior

That I would navigate into Documents.

### Test 1: Actual Behavior

File saved as Documents.txt in %UserProfile%.

### Test 2

1. File>New.
2. File>Save As.
3. This PC.
4. In the "File name" text field: write `C:\Users\[YOUR USER PROFILE]\Documents`.
5. Press Enter or click Save.

### Test 2: Expected Behavior

That I would navigate into Documents.

### Test 2: Actual Behavior

`Confirm Save As`

`Documents already exists`

Note: If you go to Libraries instead of This PC, it will say `::{[A very long string]} already exists`.
This also happens if you navigate to any folder, then write in the name of any existing subfolder and hit Enter.

### Test 3

1. File>New
2. File>Save As
3. Navigate to any folder outside C:\ or to another hard drive.
4. In the "File name" text field: write `C:\`.
5. Press Enter or click Save.

### Test 3: Expected Behavior

That I would navigate into C:\.

### Test 3: Actual Behavior
As expected.

### Test 4

1. File>New
2. File>Save As
3. This PC.
4. In the "File name" text field: write `%UserProfile%\Documents\` (with trailing backslash)
5. Press Enter or click Save.

### Test 4: Expected Behavior

That I would navigate into Documents.

### Test 4: Actual Behavior
File saved as `.txt` (nothing before ".txt").

### Test 5

1. File>New
2. File>Save As
3. This PC.
4. In the "File name" text field: write `C:\Users\[YOUR USER PROFILE]\Documents\` (with trailing backslash)
5. Press Enter or click Save.

### Test 5: Expected Behavior

That I would navigate into Documents.

### Test 5: Actual Behavior
As expected.
Also works if you navigate into any directory and write in the name of any subdirectory followed by a backslash.

### Test 6

1. File>New
2. File>Save As
4. This PC.
5. Save as type>Normal text file (*.txt)
6. In the "File name" text field: write `"C:\Users\[YOUR USER PROFILE]\Documents\"` or `"%UserProfile%\Documents\"` (with quotation marks and trailing backslash)
7. Press Enter or click Save.

### Test 6: Expected Behavior

Not sure what I expected.

### Test 6: Actual Behavior
`Save failed`

### Test 7

1. File>New
2. File>Save As
3. This PC.
4. Save as type>All file types (\*\.*)
5. In the "File name" text field: write `"C:\Users\[YOUR USER PROFILE]\Documents\"` or `"%UserProfile%\Documents\"` (with quotation marks and trailing backslash)
6. Press Enter or click Save.

### Test 7: Expected Behavior

Not sure what I expected.

### Test 7: Actual Behavior
Navigated into Documents.

### Test 8

1. File>New
2. File>Save As
3. This PC.
4. Save as type>All file types (\*\.*)
5. In the "File name" text field: write `"C:\Users\[YOUR USER PROFILE]\Documents"` or `"%UserProfile%\Documents"` (with quotation marks but without trailing backslash)
6. Press Enter or click Save.

### Test 8: Expected Behavior

Not sure what I expected.

### Test 8: Actual Behavior

`Confirm Save As`

`Documents already exists`

### Debug Information

Notepad++ v7.9   (64-bit)
Build time : Sep 22 2020 - 03:19:04
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS Name : Windows 10 Home (64-bit) 
OS Version : 2004
OS Build : 19041.572
Current ANSI codepage : 1252
Plugins : CodeAlignmentNpp.dll ComparePlugin.dll DSpellCheck.dll MarkdownViewerPlusPlus.dll mimeTools.dll NppConverter.dll NppExport.dll XBrackets.dll

**Comment by sasumner** [comment]
>why NPP does not use the kind of "Save As" and "Open" dialogues that, for example, Notepad, VSCode, Firefox and VLC and uses. These windows have a search box, a Navigation pane on the left-hand side; and allows you to navigate to a folder directly by typing in a path manually in the top pane (the pane that shows which directory you are in, and if you click it, it will become a text field,...)

Regarding these comments, what is your setting for this checkbox?:

![image](https://user-images.githubusercontent.com/30118311/97480697-2715e800-192a-11eb-8aad-77e90c2e7805.png)

**Comment by sasumner** [comment]
If the above Test 1 through 8 were NOT executed with the _Use new style dialog_ box ticked, please reevaluate all of them with the box ticked and post your revised comments here.

**Comment by mimmiechan** [comment]
> Regarding these comments, what is your setting for this checkbox?:

Oh, wow! That worked. Thanks. I don't know why I had that off.
