### ISSUE TITLE
Correct several language names

### ISSUE THREAD

**Issue by dg9ngf** [notepad-plus-plus/notepad-plus-plus#907]
The following content languages are not named as accurately as they could be:

* MS INI file – That format is used elsewhere, too, so the "MS" (Microsoft) prefix is probably not necessary. Also the "file" suffix is not used in other names. New name: **INI**
* VB – It's a shortcut for **Visual Basic**, which BTW is _not_ Visual Basic .NET (abbr. VB.NET)
* Javascript – is actually spelt **JavaScript** (with a capital S)
* INNO – You probably mean the script file for InnoSetup. I am using this tool but never saw it written all-capital and without the "Setup". New name: **Inno Setup**
* MS-DOS Style – Not sure if anybody still uses a genuine MS DOS. Did you mean something like the Windows command prompt? I agree that this would be a quite long name though...
* Flash actionscript – Again, this is officially **ActionScript**, maybe with a "(Flash)" for explanation, but it's also used elsewhere.
* Postscript – **PostScript**

**Comment by h-h-h-h** [comment]
:+1: You could edit the following file and create a pull request if you like: ["Notepad_plus.rc"](https://github.com/notepad-plus-plus/notepad-plus-plus/blob/master/PowerEditor/src/Notepad_plus.rc#L646). There you could ask for clarifying the unsure points. This way, the chances are better to get it resolved more quickly.

**Comment by dg9ngf** [comment]
I'm not sure anything is resolved quickly at all here. I'm observing quite a number of issues by now and there hasn't been anything but discussion. At least some of the discussion brought up some workarounds.
