### ISSUE TITLE
Intel hex not showing highlight colours

### ISSUE THREAD

**Issue by emmerik** [notepad-plus-plus/notepad-plus-plus#9072]
### Description of the Issue

When viewing a file in Intel Hex format (language set to Intel Hex), no highlighting is visible, in version 7.9 new install. Works in 7.8.9. The collapse thingy (+- to collapse a whole group of data related to a file entry with record type 04) does work, so it is doing something, Intel hex is missing from the Settings / Style Configurator / Language list box.

### Steps to Reproduce the Issue

1. Fresh install of npp 7.9
2. Open a hex file. Example data below.
3. Set language to Intel Hex.

Example data:
:02000004003DBD
:20800000B2BDFE082B422B432B442B452B462B479A00D5008F008FC09B64767E9896D5000B
:208010008F0090249A019B64767E9896761F023A8F0091C0A8282B1A8F009224A82A2B1B2E

### Expected Behavior

I should see highlighting, e,g, last 2 columns in every row of a valid hex file should be in green (indicating a valid checksum).

### Actual Behavior

I see the file in black and white, apart from red in the first column, for the collapsible segments.

### Debug Information

Sorry, uninstalled now. But it's a fresh install.

Sorry, uninstalled now.

**Comment by Ekopalypse** [comment]
@emmerik - could it be that you are using a theme that does not contain the intel hex lexer?

![image](https://user-images.githubusercontent.com/47723516/97578718-7b37cf80-19f1-11eb-8509-e4d4bbca1aff.png)

**Comment by emmerik** [comment]
I can't see how. I tried several themes, and something like "Intel hex" appeared at the bottom of the screen. Also, the red stuff in the first column was visible, and it had to understand the intel hex format to do that correctly (and it did).

I see that you have 7.9.1 above; maybe it's fixed now (I'm pretty sure I had 7.9, no third version digit).

**Comment by emmerik** [comment]
In fact I've just installed 7.9.1 (64 bit), and it works fine now.

**Comment by einsteiner900** [comment]
I am getting the same problem, initially with 7.9.1 32-bit, and also after updating to 7.9.4 64-bit.
<img width="669" alt="npp_7_9_1_x86 not highlighting intel hex" src="https://user-images.githubusercontent.com/54446024/111894190-194b2700-89df-11eb-816b-81dc0b4afd39.png">
<img width="690" alt="npp_7_9_4_x64 not highlighting intel hex" src="https://user-images.githubusercontent.com/54446024/111894191-194b2700-89df-11eb-877a-bf13f92db086.png">

**Comment by sasumner** [comment]
@einsteiner900 Works for me in a fresh portable 7.9.4 64-bit:

![image](https://user-images.githubusercontent.com/30118311/111901809-832ff480-8a10-11eb-8b1c-612bbb0a5fc6.png)
