### ISSUE TITLE
Keyboard close ASCII Character Panel

### ISSUE THREAD

**Issue by vinsworldcom** [notepad-plus-plus/notepad-plus-plus#9078]
### Description of the Issue
There is no way to keyboard close the ASCII Character Panel (Edit => Character Panel).  ESC key should be mapped to close the panel.

### Steps to Reproduce the Issue

1. Edit => Character Panel
2. Press ESCAPE key
3. Nothing happens

### Expected Behavior
Character Panel should close.

**Comment by donho** [comment]
I'm not sure ESC is a good way to close for ASCII Character Panel.

**Comment by vinsworldcom** [comment]
@donho 

I set a shortcut to Edit => Character Panel but that only opens and once it is open, it doesn't close it - so it's not like a toggle.  I was hoping for a keyboard shortcut to close the panel and since return or click add the item and return focus to the edit view, I thought ESCAPE to move focus to the edit view wasn't needed, so could use ESCAPE to close the panel.

Happy to change it if there's a better solution or you can just reject the PR if you don't think it's necessary.

Thanks for 7.9.1 - I see you're already adding in new PRs for the next release!

Cheers.

**Comment by sasumner** [comment]
Side note:  How useful is this panel anyway?
I've used it for getting a NUL character in a doc for testing, but other than that...nada.
Now, if it could hold the entire UTF-8 charset, with previewed samples...that would be something. :-)

**Comment by ArkadiuszMichalski** [comment]
What character set this panel dispaly? This is what we see in `? > Debug Info... > Current ANSI codepage` or some specific/concrete ANSI? ASCII is not complete information here because it is only the first 128 characters.

**Comment by donho** [comment]
@ArkadiuszMichalski  Menu `Edit > Character Panel`

@vinsworldcom @sasumner Both "Clipboard History" and "Character Panel" should have the same behaviour as "Folder as Workspace", "Project panels" & "Function List panel". "Find result" is different because users need release the room from it constantly.
I'll create an issue for it.

**Comment by donho** [comment]
Created:
https://github.com/notepad-plus-plus/notepad-plus-plus/issues/9094

**Comment by ArkadiuszMichalski** [comment]
@donho I know how open it, I ask what characters this panel display (beyond ASCII), this window's title `ASCII Character Panel` is not precise.

**Comment by dinkumoil** [comment]
@ArkadiuszMichalski 

> What character set this panel dispaly? 

It displays not simply the current system ANSI code page.

If an OEM code page is set as the character encoding schema for the active document, the panel displays the character set of that OEM code page.

If UTF-8 or another unicode encoding is set as the character encoding schema for the active document, the panel displays the character set of the current system ANSI code page.

Of course, it would be fine to see the whole unicode character set. But I guess that would eat up too much RAM and I'm in doubt that this disadvantage would be compensated by the benefit of having a complete unicode character set. However, generally I think the character set panel is useful and indeed I use it frequently to translate hex character codes to the related glyph.

**Comment by ArkadiuszMichalski** [comment]
If above it's correct would be nice to have such infos in the manual.

**Comment by sasumner** [comment]
>Of course, it would be fine to see the whole unicode character set. But I guess that would eat up too much RAM and I'm in doubt that this disadvantage would be compensated by the benefit of having a complete unicode character set.

Hence the `:-)` after my earlier comment concerning this.

**Comment by donho** [comment]
@vinsworldcom You can test the following PR:
https://github.com/notepad-plus-plus/notepad-plus-plus/pull/9096

**Comment by vinsworldcom** [comment]
@donho PR #9096 works as described - they are now toggle-able by the menu item or any shortcut assigned to that menu item.

Cheers.

**Comment by donho** [comment]
@ArkadiuszMichalski Oups, sorry for misunderstanding your question.

> What character set this panel display? This is what we see in ? ->Debug Info... ->Current ANSI codepage or some specific/concrete ANSI? 

It follow the code page of current document, then it change the display from 128-255 if need.

> ASCII is not complete information here because it is only the first 128 characters.

True. Have you a better naming?
