### ISSUE TITLE
[Feature Request] Add command to toggle block comments

### ISSUE THREAD

**Issue by Gitoffthelawn** [notepad-plus-plus/notepad-plus-plus#9086]
Notepad++ features a useful command to toggle line comments, but not one to toggle block comments.  Can such a feature be added?

**Comment by ArkadiuszMichalski** [comment]
Duplicate of https://github.com/notepad-plus-plus/notepad-plus-plus/issues/8300.

**Comment by sasumner** [comment]
Closing due to duplication; one is enough.
