### ISSUE TITLE
Shortcut mapper: Scrollbars are disconnected

### ISSUE THREAD

**Issue by ygoe** [notepad-plus-plus/notepad-plus-plus#909]
Steps to reproduce:
1. Open the Shortcut mapper from the settings menu
2. Scroll down a bit
3. Switch to another page
4. Switch back to the first page

Expected result:
Either the table view is scrolled up to the beginning and the scrollbar is at the beginning as well, or the table view remembers its last position and the scrollbar reflects that accordingly.

Actual result:
The table view is at the beginning (look at the line numbers) but the scrollbar is still far down.

As a side note, when double-clicking a table cell in the second column (where the keyboard shortcuts are), the table is scrolled to the right so much that the first column (where the command names are) is not visible anymore. It's not hard to click in the second column because when I want to change a hotkey, I'd first click on it directly, not on the name.

As another side note, the table scrolls back to the selected row when the window is deactivated and then activated again. Just select a row, scroll down with the scrollbar, click on the desktop and then activate the window again.

See also #429 and #878 for other issues with this dialog.

**Comment by dail8859** [comment]
Closed by 1abac157993685c4f6345443f6256403526858ad. Each tab view is scrolled to the beginning when switching to it.
