### ISSUE TITLE
save-as  not working 

### ISSUE THREAD

**Issue by carypt** [notepad-plus-plus/notepad-plus-plus#9091]
### Description of the Issue
if using "save-as" on under same name and folder as original file (,which is naturally opened in npp) , the file isnt saved (replaced/overwritten) 

### Steps to Reproduce the Issue
1. open existing file dir1/text.txt and make changes
2. using "save-as" under same name in same folder -> dir1/text.txt
3. replace window message agree , error message in npp -> ok . (file isnt written . error message does not inform about data loss.)

### Expected Behavior
1. file should be saved with changes under same name in same folder
2. the presence of a "save a copy as.."-operation availiable , should not lead to a malfunction of "save-as" , it should be fool-proof , but at least inform about the malfunction of the data-operation in general . ( that the file is already opened in npp might be the reason for the malfunction , but not the operational error .) 

### Actual Behavior
file isnt saved with changes , and more important user isnt informed about . anyway , both leads to data loss .
the error message of npp gives irrelevant information ( file is already opened in npp ) which is visible anyway .

### Debug Information
Notepad++ v7.9   (32-bit)
Build time : Sep 22 2020 - 03:24:22
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS Name : Windows 7 Professional (64-bit) 
OS Build : 7601.0
Current ANSI codepage : 1252
Plugins : mimeTools.dll NppConverter.dll NppExport.dll 

i made discuss about before , but seem to be not understood : https://community.notepad-plus-plus.org/topic/20249/save-as-failure-and-focus-is-where-now

**Comment by sasumner** [comment]
Closing as "too silly to consider".
