### ISSUE TITLE
failed to customize function list in npp 7.9.1,  but success in npp 7.9

### ISSUE THREAD

**Issue by linpengcheng** [notepad-plus-plus/notepad-plus-plus#9093]
failed to customize markdown & Clojure function list in npp 7.9.1,  but success in npp 7.9

[failed_fn_list.zip](https://github.com/notepad-plus-plus/notepad-plus-plus/files/5475943/failed_fn_list.zip)

**Comment by sasumner** [comment]
Please take questions about this to the Community site for support:
https://community.notepad-plus-plus.org/
