### ISSUE TITLE
Make "Clipboard History" and "Character Panel" togglable 

### ISSUE THREAD

**Issue by donho** [notepad-plus-plus/notepad-plus-plus#9094]
Both "Clipboard History" and "Character Panel" should have the same behaviour as "Folder as Workspace", "Project panels" & "Function List panel" are togglable. Currently it's not the case.

My debug info:

Notepad++ v7.9.1   (32-bit)
Build time : Nov  2 2020 - 15:17:20
Path : C:\xxx\Notepad++.exe
Admin mode : OFF
Local Conf mode : ON
OS Name : Windows 10 Enterprise (64-bit) 
OS Version : 2004
OS Build : 19041.572
Current ANSI codepage : 1252
Plugins : HexEditor.dll LuaScript.dll mimeTools.dll NppConverter.dll NppExport.dll XMLTools.dll

**Comment by dinkumoil** [comment]
Please also consider the document list panel, see #9015.
