### ISSUE TITLE
Update Save As dialog look and feel (also ignoring Windows colours)

### ISSUE THREAD

**Issue by AntonioCS** [notepad-plus-plus/notepad-plus-plus#9097]
Hey,
The current save dialog looks like this:
![image](https://user-images.githubusercontent.com/1086401/97960250-fe1da900-1da8-11eb-89ee-ffccdfd78348.png)

Would it be possible to change it to something like this:
![image](https://user-images.githubusercontent.com/1086401/97960310-1f7e9500-1da9-11eb-879c-2745957e20d1.png)

With this dialog I can quickly edit the path of where I want to save, I can literally just copy&paste a path on to the edit, something I can't do on notepad++.

NOTE: One thing I just noticed is that I have a black theme (on Windows and notepad++) but the "Save As" dialog is ignoring those settings.

**Comment by sasumner** [comment]
Try ticking this box in the _Preferences_ :

![image](https://user-images.githubusercontent.com/30118311/97986870-5dc78480-1da8-11eb-9208-38ee95f0bb47.png)

**Comment by AntonioCS** [comment]
Yeap, that works great! Thanks!
