### ISSUE TITLE
When the "Find result" panel refers to a search on the unsaved file "NEW 1", only, any further search, with the "Find in these found results..." option, does NOT match anything !

### ISSUE THREAD

**Issue by guy038** [notepad-plus-plus/notepad-plus-plus#9098]
### Description of the Issue

A search, using the **`Find in these found results...`** option, does **not** match anything if a **`Find All in Current Document`** was performed on the **non-saved** file **`new 1`**, **exclusively** !

### Steps to Reproduce the Issue

1. Start Notepad++

2. Click **`3`** times on the **`Ctrl + N`** shortcut  => The **`3`** tabs **`new 1`** , **`new 2`** and **`new 3`** appear

3. Open the well-known file **`License.txt`**

4. Copy all its contents and **paste** it into each **non-saved** file

5. Select the **`new 3`** file, first

7. Open the Find dialog ( **`Ctrl + F`** )

3. SEARCH **`your`**

4. **Tick** the **two** options **`Match whole word only`** and **`Wrap around`**, **only**

5. Select the **`Normal`** search mode

6. Click on the **`Find All in Current Document`** button

=> The **`Find result`** appears with the message *Search "your" (14 hits in 1 file of 1 searched)*

7. **Right**-click in the **`Find result`** panel

8. Select the **`Find in these found results...`** option

9. SEARCH **`that`**

10. **Tick** the **two** options **`Search only in found lines`** and **`Match whole word only`**

11. Select the **`Normal`** search mode

12. Click on the **`Find All`** button

=> A second **`Find result`** panel appears with  the message *Search "that" (6 hits in 1 file of 1 searched) - Line Filter Mode: only display the filtered results*  ( **OK** )

13. Click on the **`X`** button to close the second **Find result** panel

14. **Right**-click in the main **`Find result`** panel

15. Select the **`Clear All`** option to get an **empty** panel

---

16. Select the **`new 2`** file and **repeat** the steps **`7.`** to **`15.`**

 => Again, you **correctly** get the message *Search "that" (6 hits in 1 file of 1 searched) - Line Filter Mode: only display the filtered results*

17. Select the **`new 1`** file and **repeat** the steps **`7.`** to **`15.`**

### Actual Behavior

=> This time, the search in **`Find in these found results...`** panel does **not** match anything and you get the message *Search "that" (0 hits in 0 files of 1 searched) - Line Filter Mode: only display the filtered results*

**Any** other search, from the **main** **`Find result`** panel, relative to **`new 1`** file, **exclusively** , with the **`Find in these found results...`** option, wil **not** output any match, leading to the message *Search "....." (0 hits in 0 files of 1 searched) - Line Filter Mode: only display the filtered results*, **whatever** the string searched !

### Expected Behavior

The results, involving the **`new 1`** file, should be **identical** to the other **non-saved** files **`new 2`** and **`new 3`**, as these files contain, all, the **same** copy of the **`License.txt`** file !

### Debug Information

Notepad++ v7.9.1   (32-bit)
Build time : Oct 27 2020 - 16:07:12
Path : D:\@@\791\notepad++.exe
Admin mode : OFF
Local Conf mode : ON
OS Name : Microsoft Windows XP (32-bit) 
OS Build : 2600.0
Current ANSI codepage : 1252
Plugins : mimeTools.dll NppConverter.dll NppExport.dll 

Best Regards

guy038

**Comment by sasumner** [comment]
I skipped step 16 entirely, but I can reproduce this.

**Comment by guy038** [comment]
Hello @sasumner, and **All**,

**Scott**, pleased to chat with you ! I forgot to mention that this **issue** exists since **older** N++ versions ! For instance, it's also the case of the **`v7.8.5`** version !

Ah  ! I also noticed a **very minor** bug ! Usually, in the title of the **Find result** panel the **number** of the matches of the **last recent** search is added, according to the syntax **`Find result - (xxxx) hits)`**

However , when you hit the **Clear All** option of the **`Find result`** context menu, the **number** of hits of the **last search** remains displayed  in the **title bar** ! Not a big issue Indeed, as soon as you run an **other** search, you obviously get a **right** number, anyway !

Finally, it could also be an **advantage** : you would **always** know the hits of the **last previous** **`Find result`** search, even if the **`Find result`** panel is **empty** ?!

Cheers,

guy038

**Comment by sasumner** [comment]
@guy038 

> I also noticed a very minor bug ! Usually, in the title of the Find result panel the number of the matches of the last recent search is added, according to the syntax Find result - (xxxx) hits)

See #8626 and #8228

**Comment by sasumner** [comment]
I did some investigation on this and it turns out it is related to #8461
In particular, this bug ended up the same way the other one did, see https://github.com/notepad-plus-plus/notepad-plus-plus/issues/8461#issuecomment-650666675
