### ISSUE TITLE
Broken Search feature when search string has leading or trailing whitespaces

### ISSUE THREAD

**Issue by JulienPKFX** [notepad-plus-plus/notepad-plus-plus#9100]
The search in the latest Nodepad++ auto-update totally ignores any trailing or leading whitespaces (space, tabs), and worse: Doesn't just ignore them, but fails the entire search !
This is super, super annoying.

Repro:
* Create an empty buffer and enter this text: `asd asd asd asd asd asd ` (with trailing space)
* Select the first `asd ` (including the first space)
* Hit Ctrl+F3 to start a forward search
* Observe the Notepad++ UI flashing, indicating it found no match.

Searching `asd` without the space works fine.
Searching `asd asd` works fine and matches the other strings
Searching `asd asd ` (with trailing space) does not work, well works partially, directly matches the last string at the end of the buffer, without matching the intermediate one, then stops working, F3 or Shift+F3 do nothing once it has jumped to the end.

**Comment by sasumner** [comment]
On the _Find_ dialog window, you probably have the _Match whole word only_ checkbox ticked.
Untick it and it should work as you desire.

**Comment by JulienPKFX** [comment]
Okay indeed, my bad, I was convinced it didn't behave like that with "whole word" in earlier versions, but it does too :/
Apologies for the false-positive ticket. Still weird and a bit annoying but not a big deal if it's just a matter of not searching whole word.
Thank you, closing.

**Comment by sasumner** [comment]
A bit of a side note:

"whole word" searches will only work as people intend if the first character of the search string and the last character of the search string are "word" characters.  A space is not a word character.  Typically word characters are A-Z, a-z, 0-9, and `_`.  Maybe Notepad++ should ignore the checkbox if ticked when the user's search string does not conform, meaning its first or last character is NOT a word character...

**Comment by JulienPKFX** [comment]
Well, to put things simply, the way I initially expected it to work was for it to have the same behavior as the search in visual studio.
There, whole word does the whole-word match, but also includes the spaces in the characters it searches for.

So searching for "<tab>asd" in "<tab><tab>asd<tab>asdasd<tab>asd" will only match the first and last "<tab>asd", not the middle one, where whole word doesn't match.

**Comment by sasumner** [comment]
The way it works in Notepad++ is that the behavior isn't actually _IN_ Notepad++.
The behavior is in the Scintilla editing component that N++ uses.
When the user ticks the box for _Match whole word only_, Scintilla gets passed the search string and the flag `SCFIND_WHOLEWORD` (and a few other things), then Scintilla does the finding and returns a found/not-found result.
Thus there isn't much Notepad++ can do about tweaking this behavior.
