### ISSUE TITLE
Problems in new Find window (ver7.9.1)

### ISSUE THREAD

**Issue by softmgr** [notepad-plus-plus/notepad-plus-plus#9103]
### Description of the Issue
". matches newline" and "Match whole word only"  is enabled by error

### Steps to Reproduce the Issue

1.MainMenu->Find...->The option ". matches newline" is enabled by error when Notepad++ is first started!
2. MainMenu->Find...->Search mode set as "Regular expression"->Quit Notepad++.
3. Open Notepad++ again->MainMenu->Find...->The option "Match whole word only" is enabled by error.

### Expected Behavior
Please compare with version 7.9

### Actual Behavior
Please compare with version 7.9

**Comment by sasumner** [comment]
Here are the "fresh install" default settings for 7.9.1:

![image](https://user-images.githubusercontent.com/30118311/98237565-17eaf780-1f33-11eb-87f0-cb3945f0dc96.png)

**Comment by softmgr** [comment]
@sasumner 
The picture you sent is because it lost focus in the window, and then returned to the window to return to normal. 
However, if it is the case mentioned in step 2 and step 3, returning to the window again cannot be restored.

**Comment by sasumner** [comment]
@softmgr I can't make sense of anything you've said in this issue.  If you can explain better, and I can find a legitimate problem is uncovered, I can of course reopen this issue.
