### ISSUE TITLE
File Menu Issue

### ISSUE THREAD

**Issue by Docara** [notepad-plus-plus/notepad-plus-plus#9106]
When chosen, the File Menu appears _full_ screen, the only was to get rid of it is to hit the escape key.

If it makes any difference I have 13 tabs showing different C code routines.

Unable to do a screen grab as the task bar is also hidden- running Windows 10,

**Comment by sasumner** [comment]
>Unable to do a screen grab as the task bar is also hidden- running Windows 10

Press Win+Shift+s ?

**Comment by Docara** [comment]
![Capture](https://user-images.githubusercontent.com/70949806/98246327-12f56a80-1f6a-11eb-9ef4-57d0d797f753.PNG)

**Comment by sasumner** [comment]
Not sure that the two-part screenshot tells us much, conclusively.
Can't you get it all into a single screenshot?
I tried it with a maximized Notepad++ and the File menu dropped down, and it was easy to get a single screenshot to capture it all.

**Comment by Docara** [comment]
Hi
Other than identifiable names of the computer and files I am working on  which I do not want to make public. Other than a list of file names in the middle part of the File Menu - What I have sent is what I get. Look at the periphery of both screenshots  - on the lower one especially you can see the Windows Start logo partially hidden.

I do not expect you to 'fix' _my_ problem I was just trying to contribute to the project a little and help out by just letting you know what I am experiencing. 
NPP 7.6.4  (x64) did the same thing which is why I upgraded to (the latest ) hoping it was sorted out.

As some additional information I 'Restored' NPP to a window and hit >File again and the same thing happens. I have included the top half screenshot. Please bare in mind the File menu extends over the Task Menu and beyond the NPP window.

![Capture](https://user-images.githubusercontent.com/70949806/98251635-db3df100-1f70-11eb-9431-f89df634ad5d.PNG)

**Comment by sasumner** [comment]
>names of the computer and files I am working on which I do not want to make public

Understood.
I suspect one of your recent files is "really long" somehow.
Perhaps change this setting as indicated and see if it changes anything when you drop down the _File_ menu?:

![image](https://user-images.githubusercontent.com/30118311/98256835-09a9d500-1f4d-11eb-8fa6-e2b5e5770755.png)

>on the lower one especially you can see the Windows Start logo partially hidden.

That part I can reproduce; why do you think it is a problem?

>I do not expect you to 'fix' my problem I was just trying to contribute to the project a little and help out by just letting you know what I am experiencing.

I consider this a "good thing". :-)

**Comment by Docara** [comment]
Nailed it !!!!!

I had a stupidly long file name from an imported cut & paste file I was using as reference - it was me all me LOL

But thank you so much for your software - I have just started using it in 'anger' and very impressed. 

As I'm here I have a slight (and it is slight) annoyance. The way a (horizontal) split screen is implemented I find a bit of a PITA! 

Think of word and there is that small horizontal bar at the top of the vertical scroll bar on the right, it would be nice if that could be implemented somehow for partitioning the screen.

Do I close this open ''Issue' down now or leave it up for others for reference

Anyway thanks again.

**Comment by sasumner** [comment]
>I had a stupidly long file name from an imported cut & paste file I was using as reference - it was me all me 

That was why I wanted to see your true screenshot.

>Think of word and there is that small horizontal bar at the top of the vertical scroll bar on the right, it would be nice if that could be implemented somehow for partitioning the screen.

Yea, that _would_ be nice!

>Do I close this open ''Issue' down now

You _could_, but as an team member I have the power to as well, so I will do it.
