### ISSUE TITLE
Feature Request: Auto-numbering (No bug report here)

### ISSUE THREAD

**Issue by StoopidoMan** [notepad-plus-plus/notepad-plus-plus#9120]
### Description of the Issue

Auto numbering: or auto list numbering:
Meaning, if typed a number followed by dash (1-) and then typed some random words and then pressed enter it would add at the beginning of the new line (2-) 
**example:**
1-this
2-that
3- those
**why?** I use notepad++ for everything and having this tiny feature helps with lists, it seems there is no plugin that does that

StoopidoMan Thanks you for your hard work, love your personality and being yourself, cool cool cool

**Comment by sasumner** [comment]
It's really not something for Notepad++ core.
Perhaps someone will write a plugin; perhaps YOU? :-)

**Comment by StoopidoMan** [comment]
> It's really not something for Notepad++ core.

With all respect, I have to disagree with you, the core of Notepad++ is being a text editor and is defined by @donho  or what he feels most users need. It grew in functionality over the years. And adding an auto numbering by default is something I think everyone does on a text editor and it saves time.  Lastly, a core of a product is what the users and the creator ultimately decide.  


> Perhaps someone will write a plugin; perhaps YOU? :-)
No need to be sarcastic to user offering feedback, maybe I can't write the plugin.

**Comment by donho** [comment]
@StoopidoMan 
> Thanks you for your hard work, love your personality and being yourself, cool cool cool

If everyone had the same good taste as you have, then the world would be a better place ;)

About this feature request, I feel the same way as @sasumner. Indeed, it's cool to have such feature for some, but it could be brothering for the others. So a plugin is a perfect component for that. You can do a feature request here:
https://community.notepad-plus-plus.org/category/5/plugin-development

So your idea can be seem and discussed then maybe implemented by someone.

**Comment by sasumner** [comment]
@donho Someone is already working up a Pythonscript for it, see https://community.notepad-plus-plus.org/topic/20282/plugin-that-support-auto-numbering

>It's cool to have such feature for some, but it could be brothering for the others.

Plus it could be a performance drag, the code constantly having to check to see if it needed to trigger doing something relating to auto-numbering.
