### ISSUE TITLE
Scrolling view to the end by -n or-p argument doesn't work properly for resize main window

### ISSUE THREAD

**Issue by ArkadiuszMichalski** [notepad-plus-plus/notepad-plus-plus#9123]
### Description of the Issue
When we resize NPP main window then scrolling view to the end by `-n` or `-p` argument doesn't work properly.

### Steps to Reproduce the Issue

1. Open NPP and resize main window (for example to 1024x703).
2. Close NPP.
3. Make test for `stylers.model.xml` file (it has 1407 lines and 170624 length)
```
notepad++ -n1407 stylers.model.xml
notepad++ -n1500 stylers.model.xml

notepad++ -p170624 stylers.model.xml
notepad++ -p180000 stylers.model.xml
```

We get cursor in right place, but view stick on 1401 line (when mian window size is 1024x703).

![image](https://user-images.githubusercontent.com/2730894/98446922-6d84f700-2121-11eb-8249-a3dce3a2ab6a.png)

I don't know if it's a bug or intentional but if we want jump to last line/char (or we pass greater value than them) then NPP at least should force scrolling view to the end (as much as possible).

### Debug Information
Notepad++ v7.9.1 (32-bit)
Build time : Nov 2 2020 - 01:03:56
Path : D:_test\NPPClean\notepad++.exe
Admin mode : ON
Local Conf mode : ON
OS Name : Windows 7 Ultimate (64-bit)
OS Build : 7601.0
Current ANSI codepage : 1250
Plugins : none

**Comment by Yaron10** [comment]
@ArkadiuszMichalski,

I didn't have a problem with 1024x703 but I was able to reproduce it with a different window size: 909x608.

It only occurs if "Word wrap" is ON and `stylers.model.xml` is NOT the current file.

![תמונה](https://user-images.githubusercontent.com/10229320/98451309-2b71aa80-214d-11eb-9682-b398d4103fb8.png)

Can you please try the following case?
`Preferences -> MISC. > File Status Auto-Detection`.
Select `Enable for all opened files` and check `Update silently` and `Scroll to last line`.
Open `stylers.model.xml`.
Open another file.
Modify `stylers.model.xml` (and Save) with another editor.
Return to NPP and activate `stylers.model.xml`.

The result I get is not the best but better.

![תמונה](https://user-images.githubusercontent.com/10229320/98451380-bf437680-214d-11eb-95c4-1d8ed3ba5d8e.png)
***
https://github.com/notepad-plus-plus/notepad-plus-plus/blob/d80816f930c41d6dbb40a2ef689a071c38d025c2/PowerEditor/src/ScitillaComponent/ScintillaEditView.cpp#L3338-L3339

I've replaced those lines with
```
	int line = static_cast<int32_t>(execute(SCI_LINEFROMPOSITION, pos));
	execute(SCI_ENSUREVISIBLEENFORCEPOLICY, line);
	execute(SCI_GOTOPOS, pos);
```
and I now get the "better result" in your case as well.

**Comment by ArkadiuszMichalski** [comment]
@Yaron10 
I don't see problem with `File Status Auto-Detection` and `Scroll to last line`, always scroll to last line (and I see this line), even for  your window size example: `909x608`.

But what is the situation with the command line arguments -`n` and `-p` for you when you follow with my STR https://github.com/notepad-plus-plus/notepad-plus-plus/issues/9123#issue-738278065?

**Comment by Yaron10** [comment]
@ArkadiuszMichalski,

> I don't see problem with File Status Auto-Detection and Scroll to last line, always scroll to last line (and I see this line),

Interesting.

> But what is the situation with the command line arguments -n and -p for you when you follow with my STR #9123 (comment)?

As I wrote, I get the following result:

![תמונה](https://user-images.githubusercontent.com/10229320/98451309-2b71aa80-214d-11eb-9682-b398d4103fb8.png)

Can you try adding `execute(SCI_ENSUREVISIBLEENFORCEPOLICY, line);` at the end of `ScintillaEditView::scrollPosToCenter(size_t pos)` and re-test your case?

**Comment by ArkadiuszMichalski** [comment]
Not really, because I compiles with MinGW, and here the `.xml` files don't work properly https://github.com/notepad-plus-plus/notepad-plus-plus/issues/9139#issuecomment-726263422, so there's no way to enable word-wrap and remember it.

**Comment by Yaron10** [comment]
If you submit a PR, AppVeyor should generated EXE files in other platforms too. Isn't that correct?
If the PR fixes the issue, keep it open. :)

**Comment by ArkadiuszMichalski** [comment]
Ok. before running [MinGW] NPP I copy correct `config.xml` file  (with turn on word-wrap) and it works fine with your solution (last line is visible for -n argument).

**Comment by Yaron10** [comment]
:+1:

**Comment by ArkadiuszMichalski** [comment]
@sasumner Can you also fix this? Is related to `-n` and  `-p` args. It seems the solution proposed by @Yaron10 https://github.com/notepad-plus-plus/notepad-plus-plus/issues/9123#issuecomment-723496861  works fine (at least in my in my environment).
