### ISSUE TITLE
save icon not enabled after change involving search/replace

### ISSUE THREAD

**Issue by rs904c** [notepad-plus-plus/notepad-plus-plus#9130]
In NotePad++ 7.9.1 I opened a document and did a search/replace.   I replaced 2 things, however the document was not marked changed and the disk icon to save changes wasn't enabled.    I got around this by inserting a space then the save icon was enabled.

**Comment by sasumner** [comment]
We would need this part of the template filled out to look into this:

```
### Steps to Reproduce the Issue
<!--- Set of steps to reproduce this issue -->
1. 
2. 
3. 
```

**Comment by rs904c** [comment]
I seem to be having trouble replicating the problem.
