### ISSUE TITLE
Notepad++ 7.9.1 crashes when shut down

### ISSUE THREAD

**Issue by YouriAndropov** [notepad-plus-plus/notepad-plus-plus#9131]
### Description of the Issue
When shut down, notepad++ 7.9.1 crashes.
![image](https://user-images.githubusercontent.com/11030693/98692054-fe044700-236e-11eb-8f80-ee9e6c4f96e1.png)

### Steps to Reproduce the Issue
Open and close it

### Debug Information
Event log reports :
Faulting application name : notepad++.exe, version 7.9.1.0, time stamp: 0x5f9f4e46
Faulting module name : ntdll.dll, version 10.0.14393.3630, time stamp: 0x5e8d4386
Exception code: 0xc0000374
Fault offset: 0x0000000000f7a13

**Comment by sasumner** [comment]
Provide "Debug information".
Actually follow the instructions in the "issue template":

```
### Debug Information
<!--- In your Notepad++, click on the "?" menu (found to the right of "Window" in the menu bar) -->
<!--- In the menu that drops down, choose "Debug Info..." -->
<!--- A message box will open detailing specifics about your Notepad++ version, plugins, etc. -->
<!--- CLICK ON THE BLUE LINK with the text "Copy debug info into clipboard" -->
<!--- Do a PASTE HERE -->
```

**Comment by YouriAndropov** [comment]
Notepad++ v7.9.1  (64-bit)
Build time : Nov 2 2020 - 01:07:46
Path : D:\Admin\npp.7.9.1\notepad++.exe
Admin mode : ON
Local Conf mode : ON
OS Name : Windows Server 2016 Standard (64-bit)
OS Version : 1607
OS Build : 14393.3930
Current ANSI codepage : 1252
Plugins : BigFiles.dll ComparePlugin.dll HexEditor.dll HTMLTag.dll JSMinNPP.dll mimeTools.dll NppConverter.dll NppExport.dll XMLTools.dll

**Comment by sasumner** [comment]
>Plugins : BigFiles.dll ComparePlugin.dll HexEditor.dll HTMLTag.dll JSMinNPP.dll mimeTools.dll NppConverter.dll

I would suspect that the HexEditor plugin is causing this.
Try removing and see if the problem stops.

**Comment by YouriAndropov** [comment]
No it doesn't.

**Comment by dail8859** [comment]
Since this is due to a plugin it is best to contact the author of BigFiles.
