### ISSUE TITLE
Indent guidelines on non-brace control block languages

### ISSUE THREAD

**Issue by vinsworldcom** [notepad-plus-plus/notepad-plus-plus#9137]
### Description of the Issue
It's been discussed in the [Community forum](https://community.notepad-plus-plus.org/topic/20257/notepad-7-9-1-released/14) that in C/C++ - but we can probably extend that to any language that does **not** require braces `{}` for control blocks - the indentation guidelines are not quite accurate.

I'm creating this issue for discussion (the fix seems pretty easy), but I want other opinions before creating a PR - @donho said he would consider in the Community forum discussion referenced above.  Note this behavior has been the default for some time, the [Scintilla docs](https://www.scintilla.org/ScintillaDoc.html#SCI_SETINDENTATIONGUIDES) seem to indicate the "current way" is preferred ("`SC_IV_LOOKFORWARD` [...] This setting is good for Python., ``SC_IV_LOOKBOTH [...] This setting is good for most languages.").  Before we make a potentially noticeable-by-many-users-visual change, I thought some experienced users' discussion is warranted.

The following examples show C source file language with normal behavior:
![image](https://user-images.githubusercontent.com/9657169/98858120-17b89380-242e-11eb-9602-5fc45da0c0b4.png)

and then with the `SC_IV_LOOKFORWARD` setting as is used in [Python, Coffee script and Haskell 3](https://github.com/notepad-plus-plus/notepad-plus-plus/blob/0405e230ebe85e3f191672b57d0b55d32601a146/PowerEditor/src/ScitillaComponent/ScintillaEditView.cpp#L1786):
![image](https://user-images.githubusercontent.com/9657169/98858187-2e5eea80-242e-11eb-97bb-6c6e6ca36b77.png)

Note if braces `{}` are used, the guidelines start and end at the brace lines as expected with either setting.  There are more screenshots in the [Community forum](https://community.notepad-plus-plus.org/topic/20257/notepad-7-9-1-released/14) (same link as above).

### Steps to Reproduce the Issue

1. Set language to "C"
2. Ensure View => Show Symbol => Show Indent Guide is checked (enabled)
3. enter:
```
    if (condition)
        expression;


    return;
```
4. Observe the indent guides go from the `if` to the `return` but they should _probably_ stop at the `expression;` line.

### Expected Behavior
Indent should _probably_ stop at the `expression;` line.

### Actual Behavior
Observe the indent guides go from the `if` to the `return` but they should _probably_ stop at the `expression;` line.

### Debug Information
Notepad++ v7.9.1   (64-bit)
Build time : Nov 11 2020 - 02:47:59
Path : C:\usr\bin\npp64\notepad++.exe
Admin mode : OFF
Local Conf mode : ON
OS Name : Windows 10 Enterprise (64-bit) 
OS Version : 1909
OS Build : 18363.1139
Current ANSI codepage : 1252
Plugins

**Comment by donho** [comment]
@vinsworldcom  Thank you for opening this issue.
So I would say we should apply (besides Python, Coffee Script & Haskell) C/C++/C#/Java/PHP/JavaScript to `SC_IV_LOOKFORWARD`. What do you think? Other languages to add in the list?

**Comment by vinsworldcom** [comment]
@donho those languages seem reasonable to me - I believe they all have braces `{}` optional for single-line control blocks.  I don't know enough other language' syntax to comment if others should be added.

I know Perl, Rust and PowerShell **require** the braces even for single-line control blocks, so I would **not** include those languages.

Anyone else care to weigh in?

Cheers.

**Comment by donho** [comment]
+ Objective-C

**Comment by vinsworldcom** [comment]
This may be opening the proverbial can of worms.  What about Makefile for example, this is standard as-is today:

![image](https://user-images.githubusercontent.com/9657169/98883090-c4f5d080-245b-11eb-8e51-faca4da1e295.png)

This is what it would look like with `SC_IV_LOOKFORWARD`:
![image](https://user-images.githubusercontent.com/9657169/98883138-ebb40700-245b-11eb-91c6-40d04abb3020.png)

Arguably more "accurate" in the second using `SC_IV_LOOKFORWARD`.

I just don't know enough about the syntax of so many of the languages N++ supports (for example: BaanC, Blitzbasic, LISP, Lua, etc...).  I think Makefile (as shown above) and ASN.1 (I look at SNMP MIB files and they look "better" with `SC_IV_LOOKFORWARD` as tested) could benefit as well.

Cheers.

**Comment by donho** [comment]
@vinsworldcom Makes sense.
Plus Makefile

**Comment by donho** [comment]
C, C++, Objective-C, C#, Java, PHP, JavaScript and Makefile  will be applied to `SC_IV_LOOKFORWARD`.
If there are other languages suit better to `SC_IV_LOOKFORWARD`, please add blow.

**Comment by DarkNami** [comment]
### Description of the Issue

Not a big issue but when _SCI_SETINDENTATIONGUIDES SC_IV_LOOKBOTH_, indentation guides are interrupted.

Language: PHP

![圖片](https://user-images.githubusercontent.com/5100919/105170096-6b92d780-5b57-11eb-989a-b4e69d3873c6.png)
![圖片](https://user-images.githubusercontent.com/5100919/105170132-79485d00-5b57-11eb-82f1-dd089e7119e3.png)


### Debug Information
Notepad++ v7.9.2   (32-bit)
Build time : Dec 31 2020 - 03:58:36
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS Name : Windows 10 Enterprise (64-bit) 
OS Version : 2004
OS Build : 19041.746
Current ANSI codepage : 950
Plugins : DSpellCheck.dll Explorer.dll mimeTools.dll NppConverter.dll NppExec.dll NppExport.dll NppTextFX.dll

**Comment by sasumner** [comment]
I can reproduce this.
It's going to be rooted in Scintilla.

**Comment by vinsworldcom** [comment]
The easy fix is to remove PHP from the languages that use `SC_IV_LOOKFORWARD` and instead use `SC_IV_LOOKFORWARD`.

https://github.com/notepad-plus-plus/notepad-plus-plus/blob/b54b8ee54f085129a2c4e04f0887b74a6204af3d/PowerEditor/src/ScitillaComponent/ScintillaEditView.h#L600

Remove:
`typeDoc == L_PHP || `

**Comment by DarkNami** [comment]
Maybe need remove all C syntax likes languages: 
`(typeDoc == L_C || typeDoc == L_CPP || typeDoc == L_OBJC || typeDoc == L_CS || typeDoc == L_JAVA || typeDoc == L_PHP || typeDoc == L_JS || typeDoc == L_JAVASCRIPT)`

Not only `if/else` but also `for`, `foreach`, `do/loop`, `while`, `try/catch`...

I think this is a 'personally prefer' issue, maybe we need a **Global option for all languages** in **Settings / Preferences**, users can choose which one they likes.

![圖片](https://user-images.githubusercontent.com/5100919/105324760-ca635a00-5c06-11eb-8b80-2bcae99e5a08.png)
