### ISSUE TITLE
Incorrect Closure of Ticket 9040 -- SQL Syntax coloring

### ISSUE THREAD

**Issue by starryEXEL** [notepad-plus-plus/notepad-plus-plus#9138]
### Description of the Issue

As described in Ticket 9040, the coloring of SQL code is incorrect when the pattern '\\' is presented to the code.
There were two responses.  The first missed the point that what is happening in the attached code is that a Windows path is being constructed of the form A\B\C so that the SQL is A || '\\' || B || '\\' ||.  As such, A || B || C is not the same pattern.  The second thought that I was trying to change the ESCAPE character assigned, and that is not the case.  What was shown was placing an ESCAPE '?' in the code to resolve the syntactical highlighting.  This is incorrect for two reasons:
*  Placing the ESCAPE element in the WHERE clause does not affect any of the incorrectly highlighted code that precedes the introduction of the character
*  One should not have to change valid SQL code to obtain the correct highlighting.

In the attached example, I have incorporate the undesired ESCAPE '?" clause to show that, even with the clause included on Line 41, Lines 20 through 46 remain incorrectly highlighted.

I have also attached screen shots from Notepad++ and TOAD to compare the representations.  TOAD provides the highlighting that I would expect (but I like Notepad++ to review code).

### Steps to Reproduce the Issue

1.   Use the pattern '\\' in a SQL statement
2. 
3. 

### Expected Behavior

The string '\\' should be treated as a literal, not as an escaped apostrophe.  NOTE:  The escaping is happing in Notepad++, not in the SQL.
### Actual Behavior

Highlighting is incorrect.

### Debug Information

Notepad++ v7.9   (64-bit)
Build time : Sep 22 2020 - 03:19:04
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS Name : Windows 10 Enterprise (64-bit) 
OS Version : 1903
OS Build : 18362.1139
Current ANSI codepage : 1252
Plugins : mimeTools.dll NppConverter.dll NppExport.dll 

[sampleSQL_github.txt](https://github.com/notepad-plus-plus/notepad-plus-plus/files/5528167/sampleSQL_github.txt)
![notepadpp_escape](https://user-images.githubusercontent.com/73197444/98897295-f375aa80-245f-11eb-89cd-f85e31ffe2ed.png)
![TOAD_escape](https://user-images.githubusercontent.com/73197444/98897301-f5d80480-245f-11eb-9bb6-2e0a87ddc1a8.png)

**Comment by ArkadiuszMichalski** [comment]
@starryEXEL 
And solution what you got in bug https://github.com/notepad-plus-plus/notepad-plus-plus/issues/9040 did not solve your problem?

**Comment by sasumner** [comment]
@starryEXEL 

And you really had to open a brand-new issue, when you could have just kept commenting in 9040?

**Comment by starryEXEL** [comment]
Apologies.  The ticket was marked "closed" so that I presumed that additional comments could not be added.

Chalk this up to my ignorance of GitHub's capabilities.

Scott K. Starry
+1-650-837-7511

**Comment by dail8859** [comment]
@starryEXEL You've been pointed to the solution twice by @ArkadiuszMichalski and seem to have ignored it.

![sql](https://user-images.githubusercontent.com/3694843/99014913-bd98fa80-2521-11eb-8382-b587f6fa5751.gif)

**Comment by starryEXEL** [comment]
Thanks for the animated GIF.  I did miss the reference to Ticket 8919's solution in Ticket 9040 even though I did look at the ticket several times.  Apologies for the extra work.
