### ISSUE TITLE
Remove MinGW (Makefile) build due to its uselessness

### ISSUE THREAD

**Issue by donho** [notepad-plus-plus/notepad-plus-plus#9139]
mingw-w64_810_X64 Unicode Release build from artifact:
https://ci.appveyor.com/project/donho/notepad-plus-plus/builds/36264360/job/h2j1rqm2wr2e98bq/artifacts

cannot be run at all. 
It's pointless to maintain a build config which generates the binaries not executable (crashed).

If it works for you, please comment below. Otherwise mingw build will be removed from Notepad++ project.

**Comment by donho** [comment]
https://github.com/notepad-plus-plus/notepad-plus-plus/issues/7743

**Comment by sasumner** [comment]
>It's pointless to maintain a build config which generates the binaries not executable 

Maybe the point is that the gcc toolchain could point out warnings that the microsoft toolchain might not?

**Comment by ArkadiuszMichalski** [comment]
Works for me in Windows7. I download last 7.9.1 portable and change exe to "mingw-w64_810_X64 Unicode Release build from artifact" and don't get any crash. 

Notepad++ v7.9.1   (64-bit)
Build time : Nov 12 2020 - 01:55:14
Path : C:\Users\Arek\Desktop\npp.7.9.1.portable.x64\notepad++.exe
Admin mode : ON
Local Conf mode : ON
OS Name : Windows 7 Ultimate (64-bit) 
OS Build : 7601.24136
Current ANSI codepage : 1250
Plugins : mimeTools.dll NppConverter.dll NppExport.dll

**Comment by donho** [comment]
@ArkadiuszMichalski  It works like a charm! Thank you for your tip!

**Comment by sasumner** [comment]
It runs for me on Win10, but it doesn't look very nice.

Notepad++ v7.9.1   (64-bit)
Build time : Nov 12 2020 - 01:55:14
Path : C:\\........\Notepad++.mingw.Unicode Debug.exe
Admin mode : OFF
Local Conf mode : ON
OS Name : Windows 10 Enterprise (64-bit) 
OS Version : 1809
OS Build : 17763.1518
Current ANSI codepage : 1252
Plugins : mimeTools.dll NppConverter.dll NppExport.dll

**Comment by donho** [comment]
@sasumner 
> It runs for me on Win10, but it doesn't look very nice.

True. It uses the old theme.

It crashed on my dev env because `config.xml` contains the opened Folder as Workspace panel.
After few tests, I can see it crashes when I try to open Folder as Workspace panel or Function List panel.

**Comment by sasumner** [comment]
What are the expectations of it?
The most value in my mind is what I specified before, potentially different warnings.

**Comment by donho** [comment]
@sasumner 
> Maybe the point is that the gcc toolchain could point out warnings that the microsoft toolchain might not?

Sorry, I don't follow you. Could you elaborate it please?

**Comment by donho** [comment]
> After few tests, I can see it crashes when I try to open Folder as Workspace panel or Function List panel, but it doesn't crash on opening Document Map panel, neither doc switcher panel and Search result panel.

@sasumner & @ArkadiuszMichalski 
Could you confirm my tests please?

**Comment by ArkadiuszMichalski** [comment]
Hmm the look is slightly different but I don't get crash for mentioned panels.

**Comment by sasumner** [comment]
>>Maybe the point is that the gcc toolchain could point out warnings that the microsoft toolchain might not?

>Sorry, I don't follow you. Could you elaborate it please?

Years ago on a 68000 embedded platform our production release toolchain was expensive and made by "Microtek" (I think).  It was a solid toolchain as long as you coded correctly (it did not like to warn you even with warnings turned on fully).  We used a gcc build of the same code to give us good warnings.  We didn't release or run the version built with gcc.

**Comment by donho** [comment]
@sasumner OK, got you. 
In this case, we try to remove the warning of gcc as well.

**Comment by donho** [comment]
Since the build of MinGW works, let's keep it.

**Comment by ArkadiuszMichalski** [comment]
@donho Problem with `xml` files will be fixed?

**Comment by sasumner** [comment]
@donho 

>Since the build of MinGW works, let's keep it.

And have good build instructions for people that want to build it.

**Comment by donho** [comment]
@ArkadiuszMichalski 
> Problem with xml files will be fixed?

You can always report an issue for that. But since Notepad++ official releases are built under MSVS, it won't be the priority.

**Comment by chcg** [comment]
See https://github.com/notepad-plus-plus/notepad-plus-plus/pull/8201 on some of the additional findings by gcc.
Apart from what @sasumner already mentioned developers have the chance to build also on linux as the mingw toolchain is also available for linux.

I think it just makes sense if at least from time to time some attention is placed also on this build option.
