### ISSUE TITLE
Add `Open URL` to Edit > On selection

### ISSUE THREAD

**Issue by ArkadiuszMichalski** [notepad-plus-plus/notepad-plus-plus#9144]
### Description of the Issue

It would be nice to add a command `Open URL` to `Edit > On selection`. Sometimes I only need to open part of an address (not all of it), so selecting + a separate command would solve this problem. If there is no valid address in the selection, a window should appear with information about it, just like we have it for the command `Open file` and `Open Containing folder in Explorer`.

@Uhf7 Your new URL parser would be useful for detecting an URL in a selection.

### Debug Information
Notepad++ v7.9.1   (32-bit)
Build time : Nov  2 2020 - 01:03:56
Path : D:\_test\NPPClean\notepad++.exe
Admin mode : ON
Local Conf mode : ON
OS Name : Windows 7 Ultimate (64-bit) 
OS Build : 7601.0
Current ANSI codepage : 1250
Plugins : Explorer.dll

**Comment by Yaron10** [comment]
How about one command only: "Open Selection in Associated Program"?

**Comment by ArkadiuszMichalski** [comment]
Looks like it would work, even in the case:
```
C:\test\folderORfile
```
because we can't create file or folder with the same name on the same level.

Unless there are some cases that would require separate commnads, but I don't have any example at this point. One command would only take one hotkey, which is also a positive thing.

**Comment by sasumner** [comment]
>How about one command only: "Open Selection in Associated Program"?

This works as:

![image](https://user-images.githubusercontent.com/30118311/99135356-d7a10e80-25ef-11eb-8a43-9591d3773fea.png)

I feel like I already gave this method...hmmm...guess not. :-)

**Comment by ArkadiuszMichalski** [comment]
Hmm, in fact, this can be easy done with Run. This is enough for me, if the ready command is not needed by anyone, this bug can be closed.

**Comment by sasumner** [comment]
@ArkadiuszMichalski Close it at your discretion. :-)

**Comment by ArkadiuszMichalski** [comment]
OK, entries from Run can also be easy add to context menu. Additional command seem unnecessary.

**Comment by Yaron10** [comment]
@ArkadiuszMichalski,

I'm glad you've found @sasumner's suggestion satisfactory.

@sasumner,

Still, wouldn't one command only be better (using `:ShellExecute()`)?

**Comment by ArkadiuszMichalski** [comment]
But `Open Containing folder in Explorer` not open folder form selection but rather it opens the folder containing the folder in the selection (and select this folder). If folder not exist it alway open window user folder and select `My Document` folder.
Will `:ShellExecute()` do the same?

**Comment by Yaron10** [comment]
@ArkadiuszMichalski,

You're absolutely right. :+1: 

I changed those commands for my personal use and forgot the original had an `Open Containing folder in Explorer` command.
