### ISSUE TITLE
"Go to -> Offset": wrong value in empty files

### ISSUE THREAD

**Issue by Yaron10** [notepad-plus-plus/notepad-plus-plus#9145]
**STR:**
Open an empty file.
Open the "Go to" dialog and select "Offset". 

**Result:**

![תמונה](https://user-images.githubusercontent.com/10229320/99091891-27c0a680-25d9-11eb-9cce-7f5dbeb28a52.png)
***
Notepad++ v7.9.1 (32-bit)
Build time : Nov 2 2020 - 01:03:56
Path : C---\notepad++.exe
Admin mode : ON
Local Conf mode : ON
OS Name : Windows 7 Enterprise (32-bit)
OS Build : 7601.23964
Current ANSI codepage : 1255
Plugins : ComparePlus.dll HTMLTag_unicode.dll MenuIcons.dll PythonScript.dll _CustomizeToolbar.dll

**Comment by donho** [comment]
That's weird. My test result is:
 
![image](https://user-images.githubusercontent.com/90293/99145004-2fc92680-266b-11eb-85d9-6c10e5d8c062.png)
