### ISSUE TITLE
Save All Button is still enabled

### ISSUE THREAD

**Issue by CaptainCyril** [notepad-plus-plus/notepad-plus-plus#915]
Hi,

The Save All Button is still enabled when the only edited tab is closed.

1) Open a new tab
2) Type something
3) Close it

Save button is disabled. Save All button is enabled.

**Comment by linquize** [comment]
Are you sure all the tabs are saved? Especially if you have too many opened tabs that you need to navigate through `<` `>` buttons.

**Comment by CaptainCyril** [comment]
Yes. You can check it out by launching NP++ and open a new document "New2" while keeping "New1" untouched. Type in "New2" and close it. I tried it on two computers: Vista and 7 with different plugins and settings.

**Comment by linquize** [comment]
Unsaved new files are considered "modified", so `Save All` button is enabled. Isn't it?

**Comment by CaptainCyril** [comment]
The "New1" is empty and Save as well as SaveAs are disabled when you launch NP++.

Or even open a saved document and it will be disabled. Then follow the steps I mentioned.

**Comment by linquize** [comment]
What is your Notepad++ version?
How do you do `3) Close it`? Is there a dialog box that asks you to save file?

**Comment by CaptainCyril** [comment]
V 6.8.3.

Yes I get the prompt to save but I don't save the file.

**Comment by h-h-h-h** [comment]
Related issue: https://github.com/notepad-plus-plus/notepad-plus-plus/issues/850, https://github.com/notepad-plus-plus/notepad-plus-plus/issues/529, https://github.com/notepad-plus-plus/notepad-plus-plus/issues/853.

**Comment by CaptainCyril** [comment]
Thank you for fixing it. :)
