### ISSUE TITLE
Add "Copy selected text" and rename "Copy" cmd in Search Results Panel

### ISSUE THREAD

**Issue by donho** [notepad-plus-plus/notepad-plus-plus#9151]
Currently context menu "Copy" cmd in Search Results Panel copy always the whole line(s).
However, shortcut key "Ctrl+C" does the copy of (only) selected text.

So a new command `Copy selected text` (Ctrl+C) should added and "Copy" command should rename to `Copy Selected Line(s)`.

**Comment by donho** [comment]
I can implement it, but before doing it, what do you think @sasumner ?

**Comment by sasumner** [comment]
It would be a good change.

It is hard to have good menu text for these.
Yours are OK.

Other suggestions:
* `Copy Verbatim` or `Copy Exactly` for Ctrl+c
* `Copy Special` or `Copy without metadata` for rclick>Copy

"Verbatim" might be too much of an English word! :-)  But very good here.

"without metadata" means without carrying along information about the search (its "metadata") into what is copied.

Actually I think `Copy` alone is good enough for the Ctrl+c version.  
Users know precisely what this means.
They wouldn't be confused by this. (Only the introduction of a second type of copy confuses them)

---------------------------------------

I like the introduction of a Ctrl+c equivalent to the right-click menu for 2 reasons:

* it lets users know for sure that there are TWO different types of copy
* IMPORTANT: without it, if you select text in "Search results", the go somewhere else without doing the Ctrl+c, then try to return and do the Ctrl+c, it doesn't work

Reference for one possible origin of this issue:  
https://github.com/notepad-plus-plus/notepad-plus-plus/commit/070630a2436fe2cb735fdaaf28764023ab464840#r44035279

**Comment by donho** [comment]
> Actually I think Copy alone is good enough for the Ctrl+c version.
Users know precisely what this means.
They wouldn't be confused by this.
Having a second type of copy confuses them, but seeing the two right next to each other in the menu fixes this.

You're right about it - it's simple and efficient.

So it'll be:
`Copy` & `Copy Selected Line(s)` 

Thank you for your thoughts!

**Comment by GOLEM777** [comment]
Thanks for this! )) How about hotkeys, or is it too much?

**Comment by donho** [comment]
@GOLEM777 
You can use "Ctrl-C" directly for the command "Copy". But not for the command "Copy Selected Line(s)".
