### ISSUE TITLE
Version 7.9.1 without language python

### ISSUE THREAD

**Issue by cesarac1994** [notepad-plus-plus/notepad-plus-plus#9152]
In previous version did have python language in menu "Language > P > Python", but in this new version "7.9.1" don't have more.

### Description of the Issue

Today I updated the program with the latest updates available for my notepad++, and saw that the python language disappeared from the languages ​​menu.

### Steps to Reproduce the Issue

1. Menu "? > Update Notepad++"
2. Next > Next > Next > Open Notepad++
3. Don't have more python language in menu "Language > P > Python"

### Expected Behavior

I expected the python language to continue in the languages ​​menu (letter P).

### Actual Behavior

After the last update of notepad++ no longer has python language in the languages ​​menu (letter P).

### Debug Information

Notepad++ v7.9.1   (64-bit)
Build time : Nov  2 2020 - 01:07:46
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS Name : Windows 10 Pro (64-bit) 
OS Version : 1909
OS Build : 18363.1198
Current ANSI codepage : 1252
Plugins : mimeTools.dll NppConverter.dll NppExport.dll 

This print contains the menu "languages> P" from the last update 7.9.1 (without the python language):
https://prnt.sc/vj40hz

**Comment by ArkadiuszMichalski** [comment]
@cesarac1994 
You don't dissable this language in Prefs?

![image](https://user-images.githubusercontent.com/2730894/99150163-ee4c7180-2692-11eb-9d04-2353ac0c94e9.png)

**Comment by cesarac1994** [comment]
Omg, was this, thank you very much!
Sorry for my lack of attention!
