### ISSUE TITLE
Tab not treated as spaces for YAML files

### ISSUE THREAD

**Issue by nikita-leontiev** [notepad-plus-plus/notepad-plus-plus#9156]
### Description of the Issue
Tab not treated as spaces for YAML files even set in settings.

### Steps to Reproduce the Issue
1. Go Settings > Preferences > Language > Tab Settings.
2. Select yaml.
3. Uncheck "Use default value".
4. Check "Replace by space".
5. Create YAML file and try tab.

### Expected Behavior
4 spaces.

### Actual Behavior
Tab.

### Debug Information
Notepad++ v7.9   (32-bit)
Build time : Sep 22 2020 - 03:24:22
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : ON
Local Conf mode : OFF
OS Name : Windows 7 Home Premium (64-bit) 
OS Build : 7601.0
Current ANSI codepage : 1251
Plugins : DSpellCheck.dll mimeTools.dll NppConverter.dll NppExport.dll NPPJSONViewer.dll

**Comment by sasumner** [comment]
Works correctly for me.
You didn't say anything about turning on visible whitespace in your STR, so I'm wondering how you know you got a single tab character versus 4 spaces.

**Comment by nikita-leontiev** [comment]
It works for *.yml, not *.yaml

**Comment by ArkadiuszMichalski** [comment]
Works for me for both files. Maybe you have problem with `langs.xml` in your setting? You can also try with last portable NPP and check if this fresh version works. If it works then your instaled version has problem with some config files.

**Comment by nikita-leontiev** [comment]
My langs.xml included ext="yml". Restored default.
