### ISSUE TITLE
[MinGW] After closing Notepad++ some xml config files will be broken

### ISSUE THREAD

**Issue by ArkadiuszMichalski** [notepad-plus-plus/notepad-plus-plus#9163]
### Description of the Issue
After closing Notepad++ some xml config files will be broken. Just check `config.xml` or `session.xml`. Without a working configuration, some things cannot be tested.

![image](https://user-images.githubusercontent.com/2730894/99207114-64e58e00-27bd-11eb-8754-9aca4948c071.png)

### Debug Information
Notepad++ v7.9.1   (64-bit)
Build time : Nov 15 2020 - 18:37:13
Path : C:\Users\Arek\Desktop\npp.7.9.1.portable.x64\notepad++.exe
Admin mode : ON
Local Conf mode : ON
OS Name : Windows 7 Ultimate (64-bit) 
OS Build : 7601.24136
Current ANSI codepage : 1250
Plugins : mimeTools.dll NppConverter.dll NppExport.dll

**Comment by chcg** [comment]
Seems just the first character of each xml tag is written. Probably some conversion issue between windows multicharacter or utf16 string into utf8/ascii and therefore the null is interpreted as string end.
