### ISSUE TITLE
Change order of items in 'Folder as workspace'

### ISSUE THREAD

**Issue by nelisse** [notepad-plus-plus/notepad-plus-plus#9166]
### Change order of items in 'Folder as workspace'
It would be useful to change the ordering of the items in 'Folder as workspace'.
E.g. add an up and down button, to move the selected item up/down in the list

### Steps to Reproduce the Issue
1. Currently not available

**Comment by donho** [comment]
After checking the difficulty for implementing of this feature, this feature won't be implemented.
