### ISSUE TITLE
Plugins and Cloud storage

### ISSUE THREAD

**Issue by d0vgan** [notepad-plus-plus/notepad-plus-plus#9168]
Notepad++ allows to store its setting in the Cloud. I mean the Settings -> Preferences -> Cloud -> Set your cloud location path.
However, there is nothing related to Cloud in the “Notepad_plus_msgs.h” and, as far as I can see, Notepad++'s plugins are not aware of the Cloud path.

Suggestion 1:
Maybe let’s add a new check-box “Store plugin’s settings in the Cloud” and make NPPM_GETPLUGINSCONFIGDIR to return the Cloud path in this case? Thus, the plugins will be able to use the Cloud path automatically.

Suggestion 2:
Maybe let’s add a new message similar to NPPM_GETSETTINGSCLOUDPATH? In such case, Notepad++'s plugins will be able to retrieve the Cloud path manually and deal with this path.

### Steps to Reproduce the Issue
1. Specify some Cloud location in the Settings
2. Ensure that Notepad++ itself uses the Cloud location for its settings
3. What about Notepad++'s plugins?

### Expected Behavior
Notepad++'s plugins need to be aware of the Cloud location to be able to store their settings there - either explicitly or implicitly.

### Actual Behavior
Notepad++'s plugins are not aware of the Cloud location

### Debug Information
Notepad++ v7.9.1   (32-bit)
Build time : Nov  2 2020 - 01:03:56
Path : C:\Progs\Notepadpp\notepad++.exe
Admin mode : OFF
Local Conf mode : ON
OS Name : Windows 7 Professional (64-bit) 
OS Build : 7601.0
Current ANSI codepage : 1251
Plugins : mimeTools.dll NppConverter.dll NppExec.dll NppExecPluginMsgTester.dll NppExport.dll XBrackets.dll

**Comment by d0vgan** [comment]
Related issues:
#5317 
#4696

**Comment by donho** [comment]
@d0vgan Could you confirm me if the new API works as expected please?

**Comment by d0vgan** [comment]
Confirming, NPPM_GETSETTINGSONCLOUDPATH returns the Cloud path when it is set.

**Comment by afwn90cj93201nixr2e1re** [comment]
@d0vgan thx for time wasting.
