### ISSUE TITLE
Feature request: Add Ctrl+F4 shortcut to close a single tab \ file window

### ISSUE THREAD

**Issue by joshuapearsonnot** [notepad-plus-plus/notepad-plus-plus#9169]
This is a feature request, not a bug. I love Notepad++, good stuff, please keep it coming 👍 :shipit: 

I would like it if pressing Ctrl+F4 would close a single tab \ file window. Many programs which have tabs use this shortcut, for example browsers, VS Code, Visual Studio

So just to be clear I would like to be able to press the shortcut combination Ctrl+F4 to close just 1 tab. Notepad++ would remain open, just that tab would close (ask me if I want to save) etc.

**Comment by sasumner** [comment]
Keycombinations are fully remappable in Notepad++.
Use _Settings_ menu > _Shortcut mapper..._ and configure your copy of Notepad++ to your liking.

**Comment by joshuapearsonnot** [comment]
Brilliant, thanks!

Thanks,
GOD bless
Joshua Pearson
