### ISSUE TITLE
Multi-line Tab Bar - move a Tab 

### ISSUE THREAD

**Issue by Eld0r** [notepad-plus-plus/notepad-plus-plus#917]
Hi,

dragging the active Tab to another line causes the lines to swap places.
Dropping at a specific location is difficult cause this happens each time the mouse pointer moves.

Eld0r

**Comment by h-h-h-h** [comment]
I can reproduce this bug (v6.8.3). It looks like a kind of flicker.

**Comment by dail8859** [comment]
Closed by 9967c59912a05bfac57854e583d573877fdcb787
