### ISSUE TITLE
Find X number of files. (Add to "Find in Files")

### ISSUE THREAD

**Issue by svanteeeeeeeee** [notepad-plus-plus/notepad-plus-plus#9170]
I have a lot of files that I need to search through. (100.000+) If I need to find an example or 3 - 4 examples I still have to search through all files. It's takes along time. (It stills beat searching through it manually. :)

I would like to have a new button (like "Find All" but) "Find x nr of files" and a numeric input box where you type the number of files that you like to find.

When you click the button it will start to search through all files but stops when it have reach the number of files specified. It should cut down the search down to seconds instead of minutes. (20 min one search.)

**Comment by sasumner** [comment]
This is by no means a solution to this problem, but I'm curious what might happen timewise in your "20 min one search" case if you searched in _Regular expression Search mode_ for `\Qfoo\E(?s).*` where `foo` is really the text you are searching for?

If you are already using _Regular expression Search mode_ then simply try adding `(?s).*` at the end of your search term.

**Comment by sasumner** [comment]
Closing due to no further contact from @svanteeeeeeeee
