### ISSUE TITLE
custom urls no longer working with 7.9.1

### ISSUE THREAD

**Issue by FreeAndNil** [notepad-plus-plus/notepad-plus-plus#9172]
### Description of the Issue
when I use a custom url (e.g. foo://bar) the text is no longer underlined and i can't click it

### Steps to Reproduce the Issue
1. Open new document
2. Add foo://bar
3. no underline, no click possible

### Expected Behavior
underline, click should be possible

### Actual Behavior
no underline, no click possible

### Debug Information
Notepad++ v7.9.1   (64-bit)
Build time : Nov  2 2020 - 01:07:46
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS Name : Windows 10 Enterprise (64-bit)
OS Version : 1909
OS Build : 18363.1139
Current ANSI codepage : 1252
Plugins : mimeTools.dll NppConverter.dll NppExport.dll

**Comment by ArkadiuszMichalski** [comment]
Check this comment https://github.com/notepad-plus-plus/notepad-plus-plus/issues/9155#issuecomment-727287107.

**Comment by donho** [comment]
https://github.com/notepad-plus-plus/notepad-plus-plus/commit/5168bdb7c5395821e458aaf20297cb7e8c76ef02
