### ISSUE TITLE
NPP v7.9.1 and latest xmltools plugin doesn't pretty the code for Office VBA Code

### ISSUE THREAD

**Issue by swgmike** [notepad-plus-plus/notepad-plus-plus#9174]
I have npp v7.9.1 and the latest xmltools plugin.
I open a freebasic Office 2016/2019 VBA file in NPP.
I try to pretty the code using xmltools plugin, and with or without indenting.
The VBA code is then put on the same line as one continuous line since the CRLF's were stripped out.
Thus, the code isn't beatufied/prettied up!

Also the XMLtools validator states the first line of the VBA code is invalid. I.E
Attribute VB_Name = "Some VBA Module name here"
Sub Some VBA Module name here()
...
End Sub

**Comment by sasumner** [comment]
Third-party plugins (e.g. XMLTools) aren't supported here.
This site is for core Notepad++ issues only.
Please locate its home/support site for this type of issue, and post there.
