### ISSUE TITLE
problem with closing multiple files - not user friendly, time consuming and annoying clicking. Please offer some solution

### ISSUE THREAD

**Issue by lafar6502** [notepad-plus-plus/notepad-plus-plus#9177]
### Description of the Issue

Notepad++ remembers open files by default and shows them all in the editor when you restart it. This is OK. But if you want to clean up and close them all then Notepad++ runs a modification check and asks for confirmation in these situations:
- that the file has been modified and needs to be reloaded (in case the file has been modified or touched)
- or the file no longer exists on the disk and so if we should keep it open
When you have tens of open files and are asked the same questions for each single file it gets really frustrating trying to answer 'no, i just want to close this file and get rid of it from the editor'.

Additional problem: file modification is reported also when the file content does not change, but the modification date is different. This happens very often when working on git repos and switching the branch, for example. Since changing branches is a common routine it's even more frustrating if i have to answer all these 'file modified, reload?' questions for each single file in the editor.

### Expected Behavior

Suggestion - there should be a way to quickly close all open documents, regardless of whether they have been modified on the disk or not, or they no longer exist. Maybe just ask the confirmation question for first file and provide an option 'do the same for all other files with the same problem'.
and THANKS for this great editor, BTW.

**Comment by sasumner** [comment]
Same theme as #8714

**Comment by donho** [comment]
Currently Notepad++ provides a efficient way (periodic backup option) to exit Notepad++, users can use this option for not dealing without all modified file. However, if users want to close all opened files in Notepad++, it should be the users' responsibility  for it. Shifting such responsibility to Notepad++ is dangerous and might have unexpected effect. So this request won't be implemented.
