### ISSUE TITLE
Feature suggestion: Progress bar when opening Notepad++

### ISSUE THREAD

**Issue by astrohart** [notepad-plus-plus/notepad-plus-plus#9178]
Using Notepad++ v7.9.1 on Windows 10 Pro x64 Build 2204

I customized an installation of Notepad++ with approx. 10 plugins.

Obviously, there is a slight delay when loading the application since all the plugins have to also be loaded.

Suggest make a progress bar window appear during app loading if the user has installed > some number of plugins.  For example, anything more than 3 plugins.  Just to give some more user-friendliness to the Notepad++ loading procedure, so I, the user, know that the application is indeed loading when I click its icon. Otherwise, it can seem like I click the icon to launch it, and then nothing happens.

**Comment by donho** [comment]
> Suggest make a progress bar window appear during app loading if the user has installed > some number of plugins. For example, anything more than 3 plugins. Just to give some more user-friendliness to the Notepad++ loading procedure, so I, the user, know that the application is indeed loading when I click its icon.

If you have identified the plugin or other components which cause performance issue, you can report such issue. But it's surely not a solution to deal the performance issue with progress bar.

**Comment by sasumner** [comment]
With my setup, I routinely have a 10 second wait for Notepad++ and plugins to start up.
But, I don't consider it a "Bad thing", nor do I feel the need for a progress bar.
I just consider that all the power that is loading up is worth the wait. :-)

**Comment by astrohart** [comment]
I have approx 25-40 extensions.  I suspect there is a nonlinear relationship between the number of extensions in use and the startup time.

Needless to say, would be some nice UI/UX candy.  Perhaps, a threshold?  Say, if the user has greater than X extensions installed, then show a progress bar on startup.

It's not the wait I mind so much as my computer being non-responsive during the load -- Notepad++ seems to consume a large number of system resources while bringing up extensions.
