### ISSUE TITLE
Can't come back to the previous caret position

### ISSUE THREAD

**Issue by seoexplorers** [notepad-plus-plus/notepad-plus-plus#9179]
Using Notepad++ v7.9.1 on Windows 10 Pro x86

In version 7.9 the hotkeys 
   Ctrl -              moved the cursor to previous positions
   Ctrl Shift -      moved the cursor to the following positions

In the version 7.9.1 these behaviours don't work anymore.

### Steps to Reproduce the Issue

1.  Open a text file with many lines
2.  Click on the 4th line
3.  Click on the 10th line
4.  Click on the  12th line
5.  Press Ctrl -     The cursor should go back to the 10th line, but it doesn't
6.  Press Ctrl -     The cursor should go back to the 4th line, but it doesn't
7.  Presl  Ctrl Shift -   The cursor should go forward to the 10th line, but it doesn't

**Comment by sasumner** [comment]
No such feature in Notepad++ core.
Maybe you were using a plugin that is no longer working.

**Comment by seoexplorers** [comment]
Yes, you're right. The feature is given by the plugin "Location Navigate".
![LocationNavigate](https://user-images.githubusercontent.com/74671721/99568861-d133dd80-29c7-11eb-9cff-147a8b4d1140.png)

**Comment by sasumner** [comment]
Glad you found it.

**Comment by seoexplorers** [comment]
Yes, it works when I go back to the v7.9, but it doesn't work in v7.9.1
As you mention it could be no longer working.

**Comment by donho** [comment]
@seoexplorers It's a regression in v7.9.1. It will be fixed in v7.9.2

**Comment by seoexplorers** [comment]
Great! Thank you.

**Comment by donho** [comment]
Hold... I misread your bug report.
I just tested  "Ctrl+Shift+ArrowKey" in v7.9 has the same behaviour as in v7.9.1. So there's no regression.

**Comment by sasumner** [comment]
>Hold... I misread your bug report.

Yea, your earlier post blew my mind. :-)
