### ISSUE TITLE
PHP / HTML highlighting Issues

### ISSUE THREAD

**Issue by jabcreations** [notepad-plus-plus/notepad-plus-plus#9185]
----------------------------------------------------------------------
Coding highlight issue for a *.php file that occurs on lines 13, 15, 17, 20 and 21.
----------------------------------------------------------------------
Git is having an issue displaying the code, if you can edit this post you can get the code or if you can't I've posted on Paste Bin here: https://pastebin.com/iMtX49xq.

`<?php
header('Content-Type: application/xhtml+xml; charset=UTF-8');
echo '<?xml version="1.0" encoding="UTF-8"?>'."\n";
?>
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
<head>
<script type="application/javascript">
//<![CDATA[
if (typeof EventSource != 'function') {alert('Your browser is not supported.');}
else
{
 var es = new EventSource('mail_check.php');
 
 es.onerror = function(event) {es.close();}

 es.onmessage = function(event)
 {
  var s = event.data.split('/');
  if (s[1] == s[0]) {document.getElementById('mail_staging').value = document.getElementById('mail_staging').getAttribute('max');}
  else {document.getElementById('mail_staging').value = (100 / s[1]) * s[0];}
  console.log(event.data);
  document.getElementById('result').innerHTML += event.data + '<br />';
 }
}
//]]>
</script>
<style type="text/css">* {background-color: #000; color: #ccc;} progress {outline: #77c solid 1px;}</style>
</head>
<body>
   
<h1>Server updates</h1>
<div><progress id="mail_staging" max="100" value="0"></progress></div>
<div id="result"></div>

</body>
</html>`
----------------------------------------------------------------------
Notepad++ v7.9.1   (64-bit)
Build time : Nov  2 2020 - 01:07:46
Path : C:\MEDIA\OFFICE\Notepad++\notepad++.exe
Admin mode : ON
Local Conf mode : OFF
OS Name : Windows 10 Pro (64-bit) 
OS Version : 1909
OS Build : 18363.418
Current ANSI codepage : 1252
Plugins : DSpellCheck.dll mimeTools.dll NppConverter.dll NppExport.dll

**Comment by ArkadiuszMichalski** [comment]
@jabcreations 
1. Add debug info.
2. Add some screen and select where problem exist.
