### ISSUE TITLE
Double click on file doesnt pop up the app

### ISSUE THREAD

**Issue by foremtehan** [notepad-plus-plus/notepad-plus-plus#9188]
v7.9.1 64bit - Windows 10

When i click on file or "Edit with Notepad++" in windows the app doent pop up and i have to click on the icon

**Comment by donho** [comment]
Please open a new issue by using the template to provide the complete information.

**Comment by sasumner** [comment]
@donho @foremtehan How about keeping the clutter issues down and just add the requested info to this one, at which point it will be reopened?

**Comment by donho** [comment]
@foremtehan Please add the complete info in this issue then reopen it.
