### ISSUE TITLE
windows - weird error when saving file if name contains ">" string

### ISSUE THREAD

**Issue by vidgeus** [notepad-plus-plus/notepad-plus-plus#9189]
### Description of the Issue
I try to save a file with name "EUR->GBP.txt"

### Steps to Reproduce the Issue
1. Open Notepad++
2. create a new file by pressing CTRL+N
3. write enything in the file
4. press CTRL+S to save the file
5. choose filename to be "EUR->GBP.txt"
6. Save

### Expected Behavior
One of the 2 should be expected behaviour:
- error message should appear and say something like ">" is not an allowed character in windows filenames
- should not be able to enter ">" character in the first place when writing the filename

### Actual Behavior
Error appears on screen:
![image](https://user-images.githubusercontent.com/13273119/99879625-688a7200-2c0e-11eb-9493-0702f01663a2.png)

### Debug Information
Notepad++ v7.9   (64-bit)
Build time : Sep 22 2020 - 03:19:04
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : ON
Local Conf mode : OFF
OS Name : Windows 10 Enterprise (64-bit) 
OS Version : 1607
OS Build : 14393.2906
Current ANSI codepage : 1252
Plugins : ComparePlugin.dll DSpellCheck.dll mimeTools.dll NppConverter.dll NppExport.dll NPPJSONViewer.dll

**Comment by sasumner** [comment]
I get:

![image](https://user-images.githubusercontent.com/30118311/99879890-b63ab680-2bdd-11eb-9e85-0b510bac379f.png)

But I have this setting (_ticked_):

![image](https://user-images.githubusercontent.com/30118311/99879915-f00bbd00-2bdd-11eb-96bd-126303acf9ea.png)

You probably have it _unticked_.
As "old style" is somewhat deprecated, the error messages that you see that aren't ideal aren't going to be "fixed".

**Comment by sasumner** [comment]
>should not be able to enter ">" character in the first place when writing the filename

Note also that the above is not a reasonable expectation for Windows software.
