### ISSUE TITLE
Display problem in NP++ after large search/replace

### ISSUE THREAD

**Issue by jherod** [notepad-plus-plus/notepad-plus-plus#919]
NP++ (v6.6.8) manifests display problems after a large search/replace operation.  Specifically here, the carriage return/linefeed dipthong is split across two lines.  Here's a picture of the problem:

![np display](https://cloud.githubusercontent.com/assets/14005153/9884852/e29b2088-5b96-11e5-957b-faa297f154d8.png)

Note that word wrap is on here so you can see the entire line.  The problem exists when word wrap is off, as well.

**Comment by jherod** [comment]
The problem also exists in the latest NP++:

![np display 2](https://cloud.githubusercontent.com/assets/14005153/9885073/22ef093c-5b98-11e5-99de-1cbfc0e26bae.png)

**Comment by cmeriaux** [comment]
This is more than a display problem. This is a corruption of the buffer.

**Comment by sanastasiou** [comment]
Exactly what @cmeriaux said. I have observed this quite a lot of times, when writing text via the various Scintilla messages. It is not easily reproduced, but the bug is there, somewhere. Automated tests would easily reproduce this..

**Comment by dail8859** [comment]
It is due to Notepad++ creating backups while a long running operation is ongoing thus corrupting the file. Some cases have been fixed but others still remain.

**Comment by dail8859** [comment]
Related: #834

**Comment by sanastasiou** [comment]
Actually there's another bug with search and replace with files. Randomly files are not being "replaced".. I'll try to reproduced and post an example. Did the same search and replace with Npp and VS - VS got 66 more results than Npp..
