### ISSUE TITLE
makro

### ISSUE THREAD

**Issue by geotolek** [notepad-plus-plus/notepad-plus-plus#920]
Dzień dobry
Używam Waszego produktu i jestem bardzo zadowolony ale mam pomysł na dorobienie pewnych funkcji które ułatwiły by mi i innym pracę.
* Mam stworzone makra które w sposób automatyczny wykonują pewne czynności, brakuje mi funkcji która pozwalałaby na uruchomienie danego makra jednokrotnie ale na wielu plikach, teraz  muszę uruchamiać dane makro na każdym pliku osobno.
* Brak funkcji przetwarzania wsadowego wielu plików - np można byłoby zadać że na wielu plikach z danego katalogu (np 1000 sztuk) uruchamiamy jakąś funkcję i zapisujemy pliki do danego folderu.

mam nadzieję że opisane funkcje pomogłyby wielu użytkownikom
pozdrawiam
geotolek

**Comment by donho** [comment]
English, please?
