### ISSUE TITLE
Regex escape hypen doesn't seem to work

### ISSUE THREAD

**Issue by GhbSmwc** [notepad-plus-plus/notepad-plus-plus#9200]
Copy this text and paste it in NP++
```
Hyphen text test -----
```
Try using regex and search for ``-`` and ``\-``, for some reason it is matching every character with 0-length match.

Wait, what the? After toggling ``Match Case`` somehow fixes this. This bug cannot be reproduced. Can someone close this?

**Comment by sasumner** [comment]
@GhbSmwc 

You as the author of the issue have the right to close it yourself.

But...are you sure you want to?
Maybe dig in a bit more to try to make it happen again?

**Comment by GhbSmwc** [comment]
Oh, didn't realized the button exists for me.

I think these random bug could be that I left my PC on for too long.
