### ISSUE TITLE
Find dialog positioning should be alongside Notepad++

### ISSUE THREAD

**Issue by dfs-** [notepad-plus-plus/notepad-plus-plus#9201]
### Description of the Issue

The Find dialog saves it's last position, thus being sometimes far away from the main Notepad++ application. Especially in multi-monitor environments. I often have to move Notepad++ to different monitors for various reasons (i. e. other workspace or a RDP connection related to my work in Notepad++ is on the screen I used Notepad++ beforehand). The Find dialog then may be opened on the "wrong" screen.

### Steps to Reproduce the Issue

In a three-monitor setup, where the monitors rest aside
![image](https://user-images.githubusercontent.com/6563013/100206139-3e82c980-2f06-11eb-9a3f-e545bdc032ab.png)

1. Move Notepad++ to monitor 3 (leftmost)
2. Open the Find dialog -> will be also placed on monitor 3
3. Close the Find dialog
4. Move Notepad++ to monitor 1 (rightmost)
5. Open the Find dialog -> will still be placed on monitor 3, leaving you wondering if it has even opened

### Expected Behavior

The find dialog should always be placed on the same screen as Notepad++.

### Actual Behavior

The find dialog stores it's absolute position making it sometimes detach from Notepad++.

### Debug Information

Notepad++ v7.9.1   (64-bit)
Build time : Nov  2 2020 - 01:07:46
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS Name : Windows 10 Pro (64-bit) 
OS Version : 2009
OS Build : 19042.572
Current ANSI codepage : 1252
Plugins : ComparePlugin.dll mimeTools.dll NppConverter.dll NppExport.dll PythonScript.dll XMLTools.dll

**Comment by sasumner** [comment]
Sorry, no such changes to _Find_ window positioning will be implemented.

**Comment by dfs-** [comment]
Linked PR allows for CTRL+F, CTRL+F to center the Find and Replace dialog, this worked until v8.1.3, where it was lost.

**Comment by OzBob** [comment]
A great feature! thank you 

If I feel moved I will update 
https://github.com/notepad-plus-plus/npp-usermanual/blob/aaeb5a2de7e7ed5b06cf495a05885feecd5a15c2/content/docs/searching.md
with:

ctrl-f (all fingers up) then ctrl-f again
or
ctrl-f+f (2nd f pressed while Ctrl is still being pressed down)
will centre the find dialog
