### ISSUE TITLE
Feature request: An option to disable auto-line-break

### ISSUE THREAD

**Issue by GhbSmwc** [notepad-plus-plus/notepad-plus-plus#9205]
Create a blank document, then paste this:
```
word
word
word
word
```
Now CTRL+F and type ``word``, then select ``Find All in Current Document``, the find results should appear, rightclick the green “header” of the search result and “copy”:
![image](https://user-images.githubusercontent.com/13095760/100389878-a1568c80-2ffc-11eb-928c-c0eb2251ba24.png)
Create a new empty document and “paste” and you'll notice a linebreak is inserted after the last “word”:
![image](https://user-images.githubusercontent.com/13095760/100389918-cba84a00-2ffc-11eb-988a-fe3cdcbadb8c.png)

This auto-line-break also happens if you copy one line in the search result and paste it, not just the green header.

I tried looking at the settings in np++ and I didn't find the option to turn off auto-line-break.

**Comment by sasumner** [comment]
Not reproducible in 7.9.1.
Unknown what version @GhbSmwc was using, because the issue template was deleted out instead of being properly filled out.

**Comment by GhbSmwc** [comment]
I'm using version 7.9.1 (32-bit)
