### ISSUE TITLE
[BUG] Trying to update 64-bits version even if the newer version is 32-bits

### ISSUE THREAD

**Issue by dejudicibus** [notepad-plus-plus/notepad-plus-plus#9206]
When Notepad++ 64-bits version tries to automatically update, it does NOT sleect a 64-bits update but a 32-bits update, realizes the error, and asks user if he/she wants to install it OVER the previous version or IN PARRALEL. I think that each version should update ONLY IF a new version of the SAME type is available.

**Comment by donho** [comment]
Use bug report template to provide complete information.

**Comment by sasumner** [comment]
>Use bug report template to provide complete information.

In other words, @dejudicibus , when you press the "New issue" button, you are presented with a template.
Do NOT simply delete the template like you did before.
FILL OUT the template.
That is what the template is there for.
