### ISSUE TITLE
Custom function list for .txt no longer works

### ISSUE THREAD

**Issue by jontwo** [notepad-plus-plus/notepad-plus-plus#9211]
### Description of the Issue

I had a custom function list defined for .txt files, but after upgrading to v7.9.1 it is no longer working. Is it due to #4896?

### Steps to Reproduce the Issue

1. Previously, I had added this section to `functionList.xml` and it made any headings that were underlined with `=` appear in the Function List panel.

```
			<!-- ========================================= [ Text File ] -->
			<!-- File format used for: .txt                              -->

			<parser
				displayName="Text file"
				id         ="text_file"
			>
				<function
					mainExpr="(?m-s)^(.+?)[\r\n]{1,2}={1,}$"
				>
					<functionName>
						<nameExpr expr="(?m-s)^.*?$" />
					</functionName>
				</function>
			</parser>
```
2. After installing v7.9.1, the headings no longer appear. I tried copying the above content to functionList\txt.xml and restarting Notepad++, but that did not help. Is there somewhere else I need to specify special formatting for .txt files?

### Expected Behavior

Previous behaviour would continue to work - any text underlined with `=` would appear in Function List.

### Actual Behavior

Function list is blank for .txt files.

### Debug Information

Notepad++ v7.9.1   (32-bit)
Build time : Nov  2 2020 - 01:03:56
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS Name : Windows 10 Enterprise (64-bit) 
OS Version : 1909
OS Build : 18363.1139
Current ANSI codepage : 1252
Plugins : DSpellCheck.dll Explorer.dll JSMinNPP.dll mimeTools.dll NppConverter.dll NppExport.dll

**Comment by sasumner** [comment]
How _FunctionList_ works has been changed.
See documentation, or documentation-in-progress.

Also, here's someone else's experience with `.txt` files and _FunctionList_ that might be helpful: https://community.notepad-plus-plus.org/topic/20259/functionlist-in-7-9-1

**Comment by jontwo** [comment]
Unless I'm missing something, I've done exactly what is in that post, including this entry in `overrideMap.xml`.
```
			<association id= "txt.xml"			 langID= "0" />

```
Any idea what else I could try?

**Comment by sasumner** [comment]
Is this what it is supposed to look like?

![image](https://user-images.githubusercontent.com/30118311/100618071-546b0280-32e9-11eb-9ca2-bfcbf99d238f.png)

I just followed the directions in the Community posting I linked to, and subbed in your lines between `<function` and `</function>`.

**Comment by donho** [comment]
@jontwo here are some samples:
```
		<!--
			For User Defined Languages (UDL's) use:
			
			<association id="my_parser.xml" userDefinedLangName="My UDL Name" />
			
			If "My UDL Name" doesn't exist yet, you can create it via UDL dialog.
		-->
			<!-- ==================== User Defined Languages ============================ -->
			<association id= "krl.xml"				userDefinedLangName="KRL"/>
			<association id= "sinumerik.xml"		userDefinedLangName="Sinumerik"/>
			<association id= "universe_basic.xml"	userDefinedLangName="UniVerse BASIC"/>
			<!-- ======================================================================== -->
```

**Comment by sasumner** [comment]
@donho I don't think @jontwo is talking about a UDL, just "Normal Text".

**Comment by jontwo** [comment]
Did you save it in a new file in the functionList directory? I'm also doing that, so I've no idea if it isn't working. What if we're trying to add a new file type, can we just add a file into functionList, update overrideMap.xml and it should show up in the Language menu? Or are there other steps to make it appear here?

**Comment by jontwo** [comment]
@donho @sasumner I don't mind either way - I could edit the existing Normal Text or make a new UDL and map it to .txt files. I've tried both it doesn't seem to have any effect. I need to restart for updates, so maybe that will make a difference. I'll keep trying anyway, thanks for your help.

**Comment by sasumner** [comment]
>I could edit the existing Normal Text

Confused by this as there isn't a functionlist for "Normal Text" that ships with N++.

**Comment by jontwo** [comment]
I was thinking of the Language menu - .txt files are identified as Normal Text, so I thought this might link to the .txt definition in functionList. I've tried reinstalling Notepad++ but I still can't get it to work. I've no idea what the problem is, so I'll have to live without it.

**Comment by jontwo** [comment]
Figured it out - the answer is to save the functionList file as normal.xml. My headings are back. Thanks for all your help!

**Comment by sasumner** [comment]
>the answer is to save the functionList file as normal.xml

For any future readers: You can call the file anything you want; you just have to "point" it to the filename you provide for it in the overrideMap.xml file.  If you just call it "normal.xml" without the appropriate pointer, that will do nothing (contrary to what @jontwo 's previous post might lead one to believe).  Really, the encouragement is to follow exactly the Community posting I linked to [EARLIER](https://github.com/notepad-plus-plus/notepad-plus-plus/issues/9211#issuecomment-735766333) as it has been shown to work.

**Comment by jontwo** [comment]
I don't want to spam this thread any further, but I did follow the Community posting, including adding a pointer to overrideMap.xml, as I mentioned [above](https://github.com/notepad-plus-plus/notepad-plus-plus/issues/9211#issuecomment-735784007). I tried a number of different file names, and the only one that worked for me was normal.xml. This may not be the case for everyone, but I thought it was worth recording. YMMV

**Comment by sasumner** [comment]
>don't want to spam this thread

No worries about that.

>YMMV

My M did V.

I experimented some more with it, and got it to work easily with several different filenames, the latest of which was "normaltext.xml" and that one I'll add here as a zip just in case someone else wants/needs to try it.

[functionList.zip](https://github.com/notepad-plus-plus/notepad-plus-plus/files/5631996/functionList.zip)
