### ISSUE TITLE
Character Panel: menu-item remains "checked" after closing the panel

### ISSUE THREAD

**Issue by Yaron10** [notepad-plus-plus/notepad-plus-plus#9216]
Master with https://github.com/notepad-plus-plus/notepad-plus-plus/commit/cfe3f3b64c18b0e9d8c3c8efb6f31f27de33970b.
***
**STR:**
Open the Character Panel.
Close it by clicking its Close button.

**Result:**
The menu-item remains "checked".

![תמונה](https://user-images.githubusercontent.com/10229320/100788844-54b8ea00-341e-11eb-8d96-982ce0706b7d.png)

Relevant to Clipboard History as well.
The issue does NOT exist in other togglable panels.

**Comment by sasumner** [comment]
Good find.

Side note: I never noticed until now that the menu item only turns ON the character panel, and no menu checkmark appears (in 7.9.1).  Maybe I'm late to the party on that. :-)

**Comment by Yaron10** [comment]
> and no menu checkmark appears (in 7.9.1).

In 7.9.1 those panels are not togglable.
https://github.com/notepad-plus-plus/notepad-plus-plus/commit/cfe3f3b64c18b0e9d8c3c8efb6f31f27de33970b is a nice addition which requires some "fine-tuning".

**Comment by Yaron10** [comment]
@donho,

Great. :+1: 
Thank you for that too.
