### ISSUE TITLE
Use a modern Windows file picker UX

### ISSUE THREAD

**Issue by alexgoldsilver** [notepad-plus-plus/notepad-plus-plus#9217]
### Description of the Issue
The file picker design in N++ is dated. It uses the old buttons on the sidebar circa Windows XP.  Can we upgrade to a modern windows file picker that includes the new sidebar with cloud services, etc.  See an example here:  https://docs.microsoft.com/en-us/windows/uwp/files/quickstart-using-file-and-folder-pickers 

### Steps to Reproduce the Issue
1. Click Open/hit CTRL+O

### Expected Behavior
See the same file picker that most programs now use. For example, when adding an attachment in gmail or yahoo mail, or just want to open a local file so hit CTRL+O, Chrome uses the standard modern file picker. Firefox, too. Etc.

### Actual Behavior
Opens a much older design file picker.

**Comment by sasumner** [comment]
Tick this checkbox:

![image](https://user-images.githubusercontent.com/30118311/100797750-a0549f00-33f0-11eb-8557-7f3af9ae2af2.png)

**Comment by sasumner** [comment]
Closing for now; if something else was meant, will consider reopening.

**Comment by alexgoldsilver** [comment]
Thank you. Perfect. I had no idea.
