### ISSUE TITLE
Starts with Keyword in Folder & Default

### ISSUE THREAD

**Issue by ravindragullapalli** [notepad-plus-plus/notepad-plus-plus#9219]
I am looking for  a feature where in I would like to check for a Keyword in the beginning of the line.

Program is matching the keyword in between as well.

**Comment by sasumner** [comment]
@ravindragullapalli That doesn't make much sense.
Please follow the issue template instructions (instead of ignoring it), to create a valid issue.

**Comment by ravindragullapalli** [comment]
@sasumner Created a new issue #9222 with detail. Hope that suffice.
