### ISSUE TITLE
Official package not available on Windows "Microsoft Store"

### ISSUE THREAD

**Issue by zaheernathani** [notepad-plus-plus/notepad-plus-plus#9221]
### Description of the Issue
Official package not available on Windows "Microsoft Store"

### Steps to Reproduce the Issue

1. Go to Start
2.  Select "Microsoft Store"
3.  Search Notepad++

### Expected Behavior
Official package should be available on Windows "Microsoft Store"

**Comment by sasumner** [comment]
We don't really care about the "M$ Store" here.

**Comment by donho** [comment]
> We don't really care about the "M$ Store" here.

About 2 years ago, with help of some evangelists of Microsoft, I've built a package (non-official) for MS Store. However, the build procedure is painful and it needs the update on each time the core of build machine has been updated. 

So the official package on Windows "Microsoft Store", why not? As far as MS provides a solid procedure to build the package.

**Comment by sasumner** [comment]
:-)

I thought M$ had some requirements for features you would have to remove from N++ in order to put it on the Store.

I thought you would disagree with that.  Meaning "Who are they but some big corporate monolith, trying to tell the little guy with better ideas what to do?"

**Comment by sasumner** [comment]
I'd forgotten some details about the "store" crap last time it came up.  Here's some info: https://community.notepad-plus-plus.org/topic/14734/notepad-uwp-package-in-windows-store-almost-there/

@donho Of course, if I closed this issue wrongly, reopen.

**Comment by donho** [comment]
> I thought M$ had some requirements for features you would have to remove from N++ in order to put it on the Store.
I thought you would disagree with that. Meaning "Who are they but some big corporate monolith, trying to tell the little guy with better ideas what to do?"

There's no requirement from MS, the only limitation is the application "lives" in read only container, so there'll no possibility to install the  plugins.

> @donho Of course, if I closed this issue wrongly, reopen.

No. You were doing it right - I would do the same.

**Comment by MasonWilliamL** [comment]
> 
> 
> > I thought M$ had some requirements for features you would have to remove from N++ in order to put it on the Store.
> > I thought you would disagree with that. Meaning "Who are they but some big corporate monolith, trying to tell the little guy with better ideas what to do?"
> 
> There's no requirement from MS, the only limitation is the application "lives" in read only container, so there'll no possibility to install the plugins.

How do games like MS Flight Simulator allow mods/extensions then? Can't plugins be implemented in the same way?

Thanks for bringing this to the store! I much prefer the packaged install and update using the store (vs exe/msi download).

**Comment by sasumner** [comment]
>Thanks for bringing this to the store! 

I think you misunderstand.

**Comment by MasonWilliamL** [comment]
> 
> 
> > Thanks for bringing this to the store!
> 
> I think you misunderstand.

No, I was thanking @donho because he placed an unofficial version in the store which I currently use.

**Comment by sasumner** [comment]
>No, I was thanking @donho because he placed an unofficial version in the store which I currently use.

Now I think you not just misunderstand, but are totally confused.
@donho has NOT placed an unofficial version in the store.
If you use something from the store, you are NOT using Notepad++, you are using an imposter product (if it is representing itself as Notepad++).
If it intends to be a derivative product, it should call itself of "Banana" or "Crocodile" or literally anything that makes it clear it is NOT Notepad++.
My personal feeling is that it should not call itself "Unofficial Notepad++" (I don't know what it calls itself, as I'm not going to the store to find out) because that leads to confusion (such as yours).

**Comment by MasonWilliamL** [comment]
> 
> 
> > No, I was thanking @donho because he placed an unofficial version in the store which I currently use.
> 
> Now I think you not just misunderstand, but are totally confused.
> @donho has NOT placed an unofficial version in the store.
> If you use something from the store, you are NOT using Notepad++, you are using an imposter product (if it is representing itself as Notepad++).
> If it intends to be a derivative product, it should call itself of "Banana" or "Crocodile" or literally anything that makes it clear it is NOT Notepad++.
> My personal feeling is that it should not call itself "Unofficial Notepad++" (I don't know what it calls itself, as I'm not going to the store to find out) because that leads to confusion (such as yours).

I see.

> About 2 years ago, with help of some evangelists of Microsoft, I built a package (non-official) for MS Store

Based on his comment I thought it was uploaded by him.

It is currently available in the store as "Notepad++ (Unofficial)" by "Hauke Hasselberg" who submitted version 7.9.1 on November 2nd. Was no one involved in the official Notepad++ aware of this yet?

**Comment by sasumner** [comment]
>Was no one involved in the official Notepad++ aware of this yet?

Probably not.  I don't think anyone is assigned the duty of "minding the store".

>Based on his comment I thought it was uploaded by him.

Hmm, yea, I can see your thinking on that.  I think he just went through some "investigative" work on it, never got to the point of posting something.  If he did, I wouldn't think he'd call it "unofficial" (because I can think of no good reason for doing that).  Either go with a fully official version in the store, or don't go at all.

**Comment by pratikpc** [comment]
@donho now that the rules for inclusion to the store have changed, and so has the ways by which apps can be updated and both VS and VSCode have reached the store alongwith OBS Studio, WinZIP 25 etc. being among the few who have already joined, would it be correct to reopen this issue now?

**Comment by donho** [comment]
@pratikpc 
I will consider to move Notepad++ official release into MS Store if Microsoft change their policy:
https://github.com/notepad-plus-plus/notepad-plus-plus/commit/06657c82b3b9a1871c483982282f046b1ac7b3be

**Comment by charlesroddie** [comment]
> I will consider to move Notepad++ official release into MS Store if Microsoft changes their policy

Are you saying that removing bing as you did in that commit makes Notepad++ ineligible for the store? I can't find any rule like that.

Or are you saying that because Microsoft made Bing, you are punishing Microsoft by not supporting unrelated Microsoft products (Windows Store), and not Microsoft customers (Windows users) extra convenience?

Or, other?

**Comment by donho** [comment]
@charlesroddie 
I was saying that the profit is Microsoft's only goal, and that's why Bing did such censorship even outside of China.
Being a dev of free-software, I have the free choice to not play the game of For-profit corporation like Microsoft.

**Comment by chcg** [comment]
Chocolatey(https://community.chocolatey.org/packages/notepadplusplus) or winget(https://github.com/microsoft/winget-pkgs/pull/95168) could be used.

**Comment by treysis** [comment]
@chcg Unfortunately this requires administrator privileges, unlike the store version.

**Comment by rimrul** [comment]
> Also, why is "winget" acceptable, but MSStore is not? It's both offered by Microsoft?

Because Don didn't submit the winget package definition and thus had no control over that. He could probably try to get it removed, but IDK, how successful that would be.
