### ISSUE TITLE
Files in 2nd Notepad++ window aree not automatically backed up

### ISSUE THREAD

**Issue by RezaAmbler** [notepad-plus-plus/notepad-plus-plus#9225]
### Description of the Issue
I opened a second Notepad++ window (ALT+F6)_. I had a few open tabs in that window. When I rebooted my desktop and opened Notepad++ again it didn't restore the unsaved tabs. I checked the backup directory and only the tabs from the 1st Notepad++ window were saved to that directory.

### Steps to Reproduce the Issue

1.  Open new window (ALT+F6)
2.  Write some text in a tab
3.  Reboot / Re-Open Notepad++ and the files are missing

### Expected Behavior
I expected the tabs in the 2nd window to be restored, as they are restored in the 1st window.

### Actual Behavior
Data from tabs not saved.

### Debug Information
Notepad++ v7.8.9   (64-bit)
Build time : Jul 15 2020 - 20:31:49
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS Name : Windows 10 Pro (64-bit) 
OS Version : 2009
OS Build : 19042.630
Current ANSI codepage : 1252
Plugins : mimeTools.dll NppConverter.dll NppExport.dll 

Thanks,

**Comment by donho** [comment]
It's because of `-nosession` argument - the backup option is disabled when this argument is used.
You can remove this argument from "shorcuts.xml" if you don't care the files are opened in the new instance.

**Comment by Bibelo** [comment]
well, I had no clue about that parameter and lost my documents
