### ISSUE TITLE
[FR] Improve bad-directory user-awareness when using Find-in-Files

### ISSUE THREAD

**Issue by sasumner** [notepad-plus-plus/notepad-plus-plus#9226]
Buried in this other issue https://github.com/notepad-plus-plus/notepad-plus-plus/issues/9199#issuecomment-734600679 , I had said:

>A nice feature would be to somehow highlight invalid "Directory"s.

What I meant by this is that a user can specify an invalid `Directory:` when setting up a _Find in Files_ search, and yet they get no feedback that the directory path is bad until they do a `Find All` search.

Had they been aware that the `Directory:` setting was poor, they would not have pressed the button starting the search before fixing that problem.

So as a really obvious example, these TWO following scenarios would be "bad path" errors:

![image](https://user-images.githubusercontent.com/30118311/101076670-bc337e80-3571-11eb-86d8-cab19d7a3dc3.png)

![image](https://user-images.githubusercontent.com/30118311/101076686-c2c1f600-3571-11eb-89c5-dfc0c5f9eb3b.png)

Why is the SECOND example bad?
It appears to be fine.
Oh, wait, `DataFiles` does not exist as a folder on `C:\`
Maybe the user meant `C:\Data Files`, with a space.

It sure would be nice if, when you have something bad in the `Directory` box, that you definitively know it.

I also said:

>Maybe turn the "Directory" field pink/red like the incremental-find box when there is no match there?

Meaning this:

![image](https://user-images.githubusercontent.com/30118311/101076810-eedd7700-3571-11eb-969c-0f1184e97965.png)

That _could_ work, but I did some preliminary dabbling, and I couldn't get that kind of thing to work for a combobox like the `Directory:` box.  If someone could tell me how to do it, I'd appreciate it.

Also, sometimes colors aren't the best way, because it can cause difficulties for visually impaired users, and possibly doesn't work so well for dark-theme (Windows dark theme, NOT N++ dark theme) users.

So, I'm looking for suggestions on what to best implement, for an indication that there is a problem with `Directory:`

### Debug Information
Feature request above based upon behavior current in N++ as of version 7.9.1

**Comment by Yaron10** [comment]
@sasumner,

https://github.com/notepad-plus-plus/notepad-plus-plus/blob/fefdbc9cad7bbe4f505adf184147e7daae29a73f/PowerEditor/src/ScitillaComponent/FindReplaceDlg.cpp#L3965

Should work with a ComboBox too.
But wouldn't it be impractical to check if the folder exists on editing that field?

I think the simplest solution should be checking if the folder exists on `Find All`.
If it doesn't exist, show a MsgBox and abort the search.
(This could have been done in https://github.com/notepad-plus-plus/notepad-plus-plus/issues/9199, but you've already trimmed it :) ).

**Comment by sasumner** [comment]
>Should work with a ComboBox too.

Oh, yes, I'd think so, too.
Well, not exactly WM_CTLCOLOREDIT, because that one is strictly for edit controls, but there are similar ones.
And I couldn't make them work.
If you have some working code for that, please post it.

But, again, for the visually impaired and non-default-Win-theme users, color may not be the best thing (still searching for other good ideas).

>wouldn't it be impractical to check if the folder exists on editing that field?

I'm not sure why it would be "impractical" but maybe you can enlighten me?

>If it doesn't exist, show a MsgBox

I'd rather not if there is a clean UI way to inform the user BEFORE they initiate a search.

>could have been done in 9199

Yes, I could have waited on 9199, but I knew I didn't have that "great UI" idea yet, and I wanted to get some sort of fix in for 9199.  This current one may take a while to complete (it is part of something even bigger that I'm not revealing yet). :-)

**Comment by Yaron10** [comment]
> Oh, yes, I'd think so, too.
Well, not exactly WM_CTLCOLOREDIT, because that one is strictly for edit controls, but there are similar ones.
And I couldn't make them work.
If you have some working code for that, please post it.

A ComboBox has an Edit element. I may be wrong in using `WM_CTLCOLOREDIT` but it works for me.

![תמונה](https://user-images.githubusercontent.com/10229320/101107536-2b918880-35db-11eb-9148-84a88d41eaf7.png)

> I'm not sure why it would be "impractical"...

I just thought that calling `::PathIsDirectory()` on each and every keystroke would be too much.

**Comment by sasumner** [comment]
@Yaron10 

I can make `WM_CTLCOLOREDIT` work fully on a edit-only control (of type `EDITTEXT` in an .rc file).

If I try it on a `COMBOBOX` control, in, say, the _Find in Files_ window, I don't ever get the handle to the specific combobox I expect delivered in the message, so I can't do anything based off of it.

Unless I'm doing something really wrong ; you posted a "look at me, I can do it" result, rather than some code as I requested, so I can't tell how you achieved what you did.  :-(  
:-) :-)

Here's the code I'm fooling with (doesn't work; nothing colors):

```
case WM_CTLCOLOREDIT:
{
    static HBRUSH hBrushBackground = CreateSolidBrush(BCKGRD_COLOR);
    HDC hDC = (HDC)wParam;
    HWND hWndControl = (HWND)lParam;
    HWND hDirCombo = ::GetDlgItem(_hSelf, IDD_FINDINFILES_DIR_COMBO);
    if (hDirCombo == hWndControl)
    {
        SetTextColor(hDC, TXT_COLOR);
        SetBkColor(hDC, BCKGRD_COLOR);
        return (LRESULT)hBrushBackground;
    }
}
break;
```

If I comment out the `if` line, then ALL comboboxes in the _Find in Files_ window get color.

**Comment by Yaron10** [comment]
@sasumner,

I've used it in the *Incremental Search Bar*.

Can you try the following block?

```
	case WM_CTLCOLOREDIT:
	{
		if (::GetParent((HWND)lParam) != ::GetDlgItem(_hSelf, IDD_FINDINFILES_DIR_COMBO))
			return FALSE;

		static HBRUSH hBrushBackground = CreateSolidBrush(BCKGRD_COLOR);
		SetTextColor((HDC)wParam, TXT_COLOR);
		SetBkColor((HDC)wParam, BCKGRD_COLOR);

		return (LRESULT)hBrushBackground;
	}
```

**Comment by sasumner** [comment]
@Yaron10 The `::GetParent()` seems to be the key.  It doesn't make much sense, and it doesn't appear that way in the docs or any examples I found, but I can live with it.  :-)  Thank you for that.

**Comment by sasumner** [comment]
Barring other ideas for a UI indication of invalid directory entry, I think I'm going to go with the same "error coloring" used in the Incremental-Search box and the Function-List edit box.

Users haven't complained of those colors causing any issues, and at least it will have the virtue of consistency going that route.

**Comment by Yaron10** [comment]
@sasumner,

I'm glad I've been able to reciprocate. :)

The color is not the problem. On the contrary.
Isn't there a *major* difference between searching in a document and calling `::PathIsDirectory()` on each and every keystroke?

**Comment by sasumner** [comment]
>I just thought that calling ::PathIsDirectory() on each and every keystroke would be too much.

>Isn't there a major difference between searching in a document and calling ::PathIsDirectory() on each and every keystroke?

How many keystrokes are you making in this box? :-)

However, if you are really asking: "Couldn't this be a performance issue for network drives when the network drive isn't found (because you've got the path wrong)?"

Then, (a) I'd wish you'd just have asked it that way :-), and (b) yes. some goodpath/badpath testing with a UNC network path I have available to me showed that there is some performance issue.  Have to think about what that means for the future of this issue...

Local paths, however, are no performance issue, even if you have a really long (valid) path in the box, and you start with your caret to the far right of the text, and you hold down the Backspace key and watch how fast it moves (and the color show you get on the text as the path goes from valid to err to valid to err to valid to...well, you get the idea.

**Comment by Yaron10** [comment]
I actually did not think of network drives but local paths in a SSD. :)
And even this seems a bit "costly". But I assume you understand it better than I do.

**Comment by sasumner** [comment]
>How about coloring and beeping on Find All?

I'm not well-liked for my "beeping" efforts! :-)

We may not need the coloring as for a bad-path problem, input focus goes to the `Directory:` box and all of the text there is selected.  (Which is a kind of coloring)

**Comment by sasumner** [comment]
@Yaron10 

>I actually did not think of network drives but local paths in a SSD...

So I'm still not 100% sure of what your concern is here.
Wearing out the SSD??! with N++ doing an action on every change to the `Directory` box contents?

But, I'm still not happy with the delay that occurs when a bad network path is specified in the box.
My testing was with a UNC path; don't know if other types (e.g. mapped to drive letter) cause the same type of problem.  But...I suppose I don't care -- if I see one type of performance problem, that's good enough for me to abort this effort.

**Comment by Yaron10** [comment]
@sasumner,

You can still implement a simple MsgBox.
