### ISSUE TITLE
PHP syntax parsing including dots in constant names

### ISSUE THREAD

**Issue by asmian** [notepad-plus-plus/notepad-plus-plus#9229]
### Description of the Issue
I noticed strange behaviour of the PHP syntax highlighter on an internal PHP function after a dot concatenation with a constant. It didn't recognise the following function (substr() ) as internal, yet when I added a space between the dot and the function it highlighted correctly. Looking more closely, due to the theme I'd added it was clear that the dot was not being recognised as a PHP language concatenation operator (which my theme highlighted in bold), but had been included in the previous constant name, which is incorrect. This seems to happen for all possible constant names.

### Steps to Reproduce the Issue
Exact line typed:
header('Location: '.WWWBASE.substr($_SERVER['REQUEST_URI'], 1), TRUE, 301);

With no spacing or open bracket before "substr", this is not getting parsed correctly as an internal function. The reason is the preceding dot. Add a space on either side of that dot, and the following syntax highlighting is correct. This is because the dot is being included in the preceding constant name "WWWBASE" - with a space immediately after that the dot itself highlights correctly as a concatenation operator, which it should do without the space.

Obviously adding space is a workaround (and arguably better to read) but is not more correct syntax.

### Expected Behavior
Parsing of the constant name should stop at the dot, as it is a language operator not a valid name character.

### Actual Behavior
The dot is being parsed as a part of the constant name, not an operator, breaking following syntax parsing.

### Debug Information
Notepad++ v7.9.1   (64-bit)
Build time : Nov  2 2020 - 01:07:46
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : ON
Local Conf mode : OFF
OS Name : Windows 7 Professional (64-bit) 
OS Build : 7601.0
Current ANSI codepage : 1252
Plugins : mimeTools.dll NppConverter.dll NppExport.dll

**Comment by asmian** [comment]
Just want to add: commas and other punctuation after a constant name (or arbitrary text which PHP would try to interpret as one) are parsing fine as language syntax, not part of the name. It's just dots, in all cases where it occurs outside a quote.

**Comment by ArkadiuszMichalski** [comment]
@asmian
This is a problem with Scintilla, not Notepad++. You can report this bug to Scintilla (for `LexHTML.cxx`): https://sourceforge.net/p/scintilla/bugs/

**Comment by asmian** [comment]
Thanks Arkadisusz. But as a user, I shouldn't have to care in which sub-project the bug exists. I am not using Scintilla, whatever that is, I'm using Notepad++. Passing the buck onto a buggy include and making users report bugs elsewhere seems pretty lax.

Anyway, the bug is reported there also.

**Comment by ArkadiuszMichalski** [comment]
https://sourceforge.net/p/scintilla/bugs/2225/

**Comment by sasumner** [comment]
>as a user, I shouldn't have to care in which sub-project the bug exists. I am not using Scintilla, whatever that is, I'm using Notepad++. Passing the buck onto a buggy include and making users report bugs elsewhere seems pretty lax.

As "free" software, Notepad++ has a limited staff of developers that all donate their time.
As such, the concentration is on fixing bugs and implementing new features in the software that is under our control.
If we had to "jockey" bugs of this nature in subproject software, we'd never get anywhere.

**Comment by asmian** [comment]
I understand those time constraints. But you chose to write YOUR software on top of another programmer's module, instead of writing your own. As far as your end-user is concerned, you are taking responsibility for the failings of THAT module which makes yours break, or look bad. You see it as "jockeying bugs", I'd see it as making sure that module works as well as possible for the sake of YOUR software, if you take pride in it.

Since I don't know what externally written modules you're including and where their repositories are (and as a user, I really shouldn't care), it seems the least you can do is pass on bugs reported here that you KNOW are affecting your software. I shouldn't have to make another account on a site I don't use to do that. A don't-care, not-my-problem, won't-fix attitude looks really shoddy from here. :(

**Comment by sasumner** [comment]
@asmian 

Thank you for becoming a contributor to make Scintilla and Notepad++ better in the future (by jockeying the bug you reported).

**Comment by illuminantity** [comment]
I can see what @asmian i saying, and i can say from the perspective of a user that is the more common case. I like notepad++, at least on windows. I would be beneficial for both developers as well as users if included modules by outisde sources are listed and mentioned.

**Comment by ArkadiuszMichalski** [comment]
@RustyKeys The most important component, which we are talking about here, was mentioned on main page:
https://notepad-plus-plus.org/
Well, a list of all external dependencies would be indicated, e.g. here on github.

**Comment by ivan-u7n** [comment]
This was fixed in Scintilla/Lexilla by https://github.com/ScintillaOrg/lexilla/commit/ca4f0559ec6b9e554aa6bb864c3303125fd279dd.

**Comment by ArkadiuszMichalski** [comment]
Fixed by https://github.com/notepad-plus-plus/notepad-plus-plus/commit/a61b03ea8887e21c6e1b7374068962f635b79b80.
