### ISSUE TITLE
Desired line is often hidden with -n argument

### ISSUE THREAD

**Issue by asherber** [notepad-plus-plus/notepad-plus-plus#923]
When using the `-n` argument to specify a line number, the desired line usually appears at the very bottom of the window and is often partially hidden by the scrollbar or status bar. It would be nice if `-n` attempted to put the specified line more in the middle of the window.

Here's my target line, half hidden by the scrollbar:

![image](https://cloud.githubusercontent.com/assets/5248041/9917745/506bf6d2-5c91-11e5-8265-aef104aa7b49.png)

**Comment by dail8859** [comment]
:+1: I just used this recently and noticed it is in a very odd location. Would love to see the desired line be in a more natural location!
