### ISSUE TITLE
HexEditor doesn't work in NotePad++ v7.9.1

### ISSUE THREAD

**Issue by dfkettle** [notepad-plus-plus/notepad-plus-plus#9237]
### Description of the Issue
I've just updated NotePad++ to v7.9.1, but when I open it, I get a pop-up warning about HexEditor (see screen print), and when I try to run HexEditor from the Plugins menu, it just displays another pop-up about an access violation. I'm running NotePad++ under Windows 7, SP 1 (64-bit processor).

This used to work with the previously installed version of NotePad++ (sorry, I don't remember which version was installed).

![NotePad++](https://user-images.githubusercontent.com/8409615/101493068-8c9ac280-3933-11eb-9ec7-da981741f32b.jpg)

### Steps to Reproduce the Issue
1. Open NotePad++
2. Click on Plugins/Hex-Editor/View in HEX

### Expected Behavior
It should open in hex mode.

### Actual Behavior
It displays an error message about an access violation.

### Debug Information
Notepad++ v7.9.1   (32-bit)
Build time : Nov  2 2020 - 01:03:56
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS Name : Windows 7 Home Premium (64-bit) 
OS Build : 7601.0
Current ANSI codepage : 1252
Plugins : HexEditor.dll mimeTools.dll NppConverter.dll NppExport.dll

**Comment by sasumner** [comment]
Get latest version of HexEditor from PluginsAdmin?

**Comment by dfkettle** [comment]
Never mind. I uninstalled NotePad++, downloaded the installer, re-installed and installed Hex-Editor. It's working now.

I didn't realize you also had to re-install the plugin. That was probably the cause of the issue.

Thanks.
