### ISSUE TITLE
Quick Switch Feature

### ISSUE THREAD

**Issue by LupinTaiwan** [notepad-plus-plus/notepad-plus-plus#9239]
### Description of the Issue

It will be very helpful if user can switch between related files of the one editing quickly.

### Steps to Reproduce the Issue

Here is an example. I'm editing a mycode.cpp.

### Expected Behavior

When I press the keyboard shortcut of this feature (i.e. Ctrl+Q), Notepad++ open/switch to file:
-> mycode.cxx (if exists, else try next file) 
-> mycode.cc (if exists, else try next file) 
-> mycode.ino (if exists, else try next file) 
-> mycode.h (if exists, else try next file) 
-> mycode.hh (if exists, else try next file) 
-> mycode.hpp (if exists, else try next file) 
-> mycode.hxx (if exists, else try next file) 
 (cycle the list)
:
Where the list referred from the "ext=" of current language in langs.xml.

### Actual Behavior

This is a new feature of my idea. 

### Debug Information

Please consider. Many thanks.

**Comment by sasumner** [comment]
Visual Studio 2019 (and probably earlier versions as well) has a similar feature, shown here in its right-click context menu:

![image](https://user-images.githubusercontent.com/30118311/101630580-15c3ff00-39f1-11eb-8bcd-861ccc3cfa99.png)

**Comment by donho** [comment]
MSVS treats only few programming languages, and it keep the track of project files, so it's easier to manage for this feature.
It's not the case for a generic code editor like Notepad++.

**Comment by sasumner** [comment]
This probably isn't going to be the right kind of feature to belong in Notepad++ core code; sorry.

Here's a Pythonscript that (I think) will implement it, I call it `QuickSwitchCycleBasedUponExtension.py` :

```
# -*- coding: utf-8 -*-

from Npp import notepad
import os

list_of_ext_list = [
    [ 'cpp', 'cxx', 'cc', 'ino', 'h', 'hh', 'hpp', 'hxx' ],
    [ 'bat', 'cmd' ],
    # ...add more extension lists here...
]

p = notepad.getCurrentFilename()
f = p.split(os.sep)[-1]
f_and_e = f.rsplit('.', 1)
if len(f_and_e) >= 2:
    new_p = p.rsplit('.', 1)[0] + '.'
    old_e = f_and_e[1].lower()
    for ext_list in list_of_ext_list:
        try:
            i = ext_list.index(old_e)
        except ValueError:
            continue
        ext2_list = ext_list[i:] + ext_list[:i]
        ext2_list.pop(0)
        for new_e in ext2_list:
            if os.path.isfile(new_p + new_e):
                notepad.open(new_p + new_e)
                break
        break
```

**Comment by LupinTaiwan** [comment]
Please let me explain more detailly.

1.It is a feature for ALL Languages, no limited to any specified language.

2.It is totally a "Code Editor" feature, no related to MSVS, nor any other editor or IDE.

3.I designed it according the flexible design of Notepad++, therefore it refers "langs.model.xml" for file extensions of each language. (though it cares only the editing one)

4.It is designed for all user of any language that Notepad++ supports.

5.It cares only "the same main file name" under "the same folder" of the editing file.

6.A single function (with a shortcut) is needed to implement this powerful feature with few code.

Examples (Please refer "langs.model.xml"):

For "ada":
1.I'm editing file.ada,
2.Quick switch/open to "file.ads" if exists
3.Quick switch/open to "file.adb" if exists
4.Quick switch to "file.ada" again.

For "javascript.js":
1.I'm editing file.js,
2.Quick switch/open to "file.jsm" if exists
3.Quick switch/open to "file.jsx" if exists
4.Quick switch/open to "file.ts" if exists
5.Quick switch/open to "file.tsx" if exists
6.Quick switch to "file.js" again.

For "php":
1.I'm editing file.php4,
2.Quick switch/open to "file.php5" if exists
3.Quick switch/open to "file.phps" if exists
4.Quick switch/open to "file.phpt" if exists
5.Quick switch/open to "file.phtml" if exists
6.Quick switch/open to "file.php" if exists
7.Quick switch/open to "file.php3" if exists
8.Quick switch to "file.php4" again.

For "html":
1.I'm editing file.htm,
2.Quick switch/open to "file.shtml" if exists
3.Quick switch/open to "file.shtm" if exists
4.Quick switch/open to "file.xhtml" if exists
5.Quick switch/open to "file.xht" if exists
6.Quick switch/open to "file.hta" if exists
7.Quick switch/open to "file.html" if exists
8.Quick switch to "file.htm" again.

Related features:
1.The VS2019 one is only a subset of this.
2.Notepad++ plugin "File Switcher" by Dave Brotherstone, nice but only works for C/C++. Ans the development is stopped and no more support now.

Please kindly consider again. Thanks.

**Comment by sasumner** [comment]
>Please let me explain more detailly.

It was clear the first time.

>Please kindly consider again

Considered (again).  Declined (again).  Sorry.

>A single function (with a shortcut) is needed to implement this powerful feature with few code.

The "few code" is above in the form of a Pythonscript.
You have to build your own extension lists, but that isn't very hard to do.

**Comment by donho** [comment]
If it's binary for all languages, it'll be possible to implement... but hélas!

**Comment by LupinTaiwan** [comment]
> If it's binary for all languages, it'll be possible to implement... but hélas!

Extension of a binary is not included in the "ext=" list in langs.model.xml.

For example, .out, .exe, .lib, .obj of C/C++ is not listed in "cpp":
 <Language name="cpp" ext="cpp cxx cc h hh hpp hxx ino" ...

**Comment by sasumner** [comment]
I believe what @donho meant by "binary" was two choices, e.g., "c++" and "h", such that the cycle is:
c++ -> h -> c++ -> h -> ....

But, I don't think his heart is really behind this feature. :-)
So, let's leave it at "reject".
Or, better yet, go with the scripted solution that has already been provided.
That's what scripts are for (well, one purpose):  To fill in the gaps where developers don't agree that what you want belongs in the core product.

**Comment by LupinTaiwan** [comment]
> If it's binary for all languages, it'll be possible to implement... but hélas!

//Lupin: borrowed isInList() from AutoCompletion.cpp and modified
int indexInList(const generic_string& word, const std::vector<generic_string> & wordArray)
{
	int result = -1;
	for (int i = 0, len = (int)wordArray.size(); i < len; ++i)
	{
		if (!generic_stricmp(wordArray[i].c_str(), word.c_str()))
		{
			result = i;
			break;
		}
	}
	return result;
}

//Lupin: borrowed getWordArray() from AutoCompletion.cpp
bool getExtArray(std::vector<generic_string> & wordArray, const TCHAR *list)
{
	if (!list)
		return false;

	const size_t wordLen = 64;
	size_t listLen = lstrlen(list);

	TCHAR word[wordLen] = { 0 };
	size_t i = 0;
	size_t j = 0;

	for (; i <= listLen; ++i)
	{
		if ((list[i] == ' ') || (list[i] == '\0'))
		{
			if (j != 0)
			{
				word[j] = '\0';
				j = 0;

				if (0 > indexInList(word, wordArray))
				{
					wordArray.push_back(word);
				}
			}
		}
		else
		{
			word[j] = list[i];
			++j;

			if (j >= wordLen)
				return false;
		}
	}
	return true;
}

//fileSwitch(): switch files of the same filename of current language
bool Notepad_plus::fileSwitch(BufferID id)
{
	bool result = false;

	BufferID bufferID = id;
	if (id == BUFFER_INVALID)
		bufferID = _pEditView->getCurrentBufferID();

	Buffer* buf = MainFileManager.getBufferByID(bufferID);
	generic_string fileNamePath = buf->getFullPathName();

	// Make sure to form a string with double '\0' terminator.
	fileNamePath.append(1, '\0');

	BOOL bFoundExt = FALSE;
	TCHAR *ext = PathFindExtension(fileNamePath.c_str());
	if (*ext == '.')
	{
		bFoundExt = TRUE;// extension found
		ext += 1; //remove the leading '.' for searching
	}
	else
	{
		//No extension, eg.: "myfile"
		MessageBeep(MB_ICONWARNING);
		return result;//false
	}

	TCHAR* filename = PathFindFileName(fileNamePath.c_str());
	PathRemoveExtension(filename);
	if (NULL == filename || 0 >= lstrlen(filename))
	{
		//No filename, e.g.: ".gitignore"
		MessageBeep(MB_ICONWARNING);
		return result;//false
	}

	std::vector<generic_string> extList;
	Lang* l = buf->getCurrentLang();
	if (nullptr != l)
	{
		const TCHAR *defList = l->getDefaultExtList();
		getExtArray(extList, (LPCTSTR)defList);
	}

	const size_t nCount = extList.size();
	if (1 >= nCount)
	{
		//only 1 extension, e.g.: "txt", "cs"
		MessageBeep(MB_ICONWARNING);
		return result;//false
	}

	TCHAR fileNamePathNew[MAX_PATH] = { 0 };
	lstrcpy(fileNamePathNew, fileNamePath.c_str());
	//
	TCHAR szExtNew[64] = { 0 };
	size_t nIndex = indexInList(ext, extList);
	bool bFound = false;

	for (size_t i = 0; !bFound && i < (nCount - 1); i++)
	{
		const size_t n = (nIndex + 1 + i) % nCount;
		wsprintf(szExtNew, L".%s", extList[n].c_str());//Add the leading '.'
		::PathRenameExtension(fileNamePathNew, szExtNew);
		bFound = ::PathFileExists(fileNamePathNew);
	}
	if (bFound)
	{
		BufferID lastOne = doOpen(fileNamePathNew);
		if (lastOne != BUFFER_INVALID)
		{
			switchToFile(lastOne);
		}
		result = true;
	}
	else
	{
		//Beep if not found
		MessageBeep(MB_ICONWARNING);
	}
	return result;
}

**Comment by sasumner** [comment]
@LupinTaiwan 

If you want to put that in a pull-request, go ahead.
But don't be surprised if it is declined to be integrated.
