### ISSUE TITLE
I can not open the file *.nfo

### ISSUE THREAD

**Issue by mihey78** [notepad-plus-plus/notepad-plus-plus#924]
Win32Exception:
An exception occured. Notepad++ cannot recover and must be shut down.
The exception details are as follows:
Code: 0xc0000005
Type: Access violation
Exception address: 0x10007F6C

OS Windows8.1 x86

**Comment by h-h-h-h** [comment]
I can't reproduce this bug with a text file with NFO extension when opening the file with the context menu option "Edit with Notepad++".

I think your report lacks much information and can't be expected to be reproduced.

**Comment by NN---** [comment]
@mihey78 Provide a dump file.
Configure WER and upload the dump.
https://msdn.microsoft.com/en-us/library/windows/desktop/bb787181%28v=vs.85%29.aspx

**Comment by donho** [comment]
@mihey78  Have you tried to remove all plugins?

**Comment by mihey78** [comment]
message: failed tj create dumpfile C;\program files\notepad++\nppdump.dmp (error 5)

**Comment by mihey78** [comment]
uninstall + insall = ok'

**Comment by mihey78** [comment]
the problem is hexedit plugin

**Comment by Neroldy** [comment]
It seems that the problem is the Hex-Editor. Some days ago I also met this issue.

**Comment by donho** [comment]
@Neroldy  Thank you for the info!
