### ISSUE TITLE
A problem with search results in Arabic

### ISSUE THREAD

**Issue by alprinceahmed** [notepad-plus-plus/notepad-plus-plus#9241]
If you see image is good, the find result in English appear is harmonic , but in Arabic the speech appears inconsistent because the find result are from left to right, knowing that I use the program in Arabic. If you look at the line in which Arabic is good, you will find a big difference between the line above and the one in the find result, but in English it appears correct .

This is not a mixture between Arabic and English, but what is in the picture to clarify the difference between Arabic and English, nothing more. regex returns false results because it reads words in the wrong direction. It does not seem but this is what actually happens that the search result is in Arabic with wrong word order, in addition to that the sentence is nested then you write half in the correct direction (rtl).

I use Notepad to search files of 80,000 lines and more in Arabic. But the find result appear illegible because the line appears from left to right, not the other way around
I hope I clarified the problem well . 

![2](https://user-images.githubusercontent.com/75752869/101675707-d3d3a100-3a62-11eb-83cc-5c26f32175f4.jpg)

![1](https://user-images.githubusercontent.com/75752869/101675734-dafaaf00-3a62-11eb-967e-d6ae28524318.jpg)

**Comment by sasumner** [comment]
@Yaron10 Do you have any comment on this?
( I'm assuming it is very much similar to #8625 )

**Comment by Yaron10** [comment]
@sasumner,

>  I'm assuming it is very much similar to 8625

Yes, it is.

I suppose @alprinceahmed is referring to two related issues:
1. Paste `I'm assuming it is very much similar` in a RTL layout (or just `View -> Text Direction RTL`) and double-click `very`.
-- You get a wrong selection. The same happens on double-clicking `very` in the "Search Results" window.
This is, I think, a Scintilla issue which my suggestion in 8625 won't fix.

2. Using RTL text (e.g. `?שלום. מה שלומך`) in a RTL layout, double-clicking works correctly, but the "Search Results" window layout is confusing.

And if that's not enough, you can also have mixed LTR/RTL text. :)

**Comment by alprinceahmed** [comment]
This issue is not the same. I only ask you to make the find results from right to left in Arabic or to have a control button. So that the find result does not appear in Arabic in the wrong order of words, in addition to that the sentence is intertwined and then you write half of it in the correct direction .

![3](https://user-images.githubusercontent.com/75752869/101698349-fd4ff500-3a81-11eb-876c-b462cc011e96.jpg)

**Comment by Yaron10** [comment]
@alprinceahmed,

I can't read Arabic.
So you're only referring to https://github.com/notepad-plus-plus/notepad-plus-plus/issues/8625.

**Comment by carypt** [comment]
i have started a thread in community dealing with this matter . sure i have no answer . https://community.notepad-plus-plus.org/topic/20451/how-to-reverse-the-writing-wording-lining-direction-and-reading-working-direction-of-regex-search-engine

**Comment by sasumner** [comment]
@carypt Sadly, that Community posting is rather a mess...  Better to let the author continue to express himself here rather than pursuing it there.

**Comment by donho** [comment]
It will be fixed. However, double clicking some search results won't display correctly on the target RTL window - I won't fixed it (too much work).

**Comment by alprinceahmed** [comment]
What is the use of fixing a problem and another problem will appear ..
Hope all the problems associated with RTL will be solved .
I appreciate your effort and hard work very well .
Thank you for your efforts in this work .

**Comment by alprinceahmed** [comment]
@donho 
What is the use of fixing a problem and another problem will appear ..
Hope all the problems associated with RTL will be solved .
I appreciate your effort and hard work very well
Thank you for your efforts in this work
