### ISSUE TITLE
User Defined Keywords does not seem to function for VB keywords

### ISSUE THREAD

**Issue by excel1star** [notepad-plus-plus/notepad-plus-plus#9242]
![User Defined keywords for VB](https://user-images.githubusercontent.com/8950755/101678512-057d4580-3a2c-11eb-9250-df3447ea93f3.png)

### Steps to Reproduce the Issue

1. 
2. 
3.

**Comment by sasumner** [comment]
In version 7.9.1, if I define them like this it works:

![image](https://user-images.githubusercontent.com/30118311/101679177-f64ac780-3a2c-11eb-870a-c7e8f870d645.png)

`&` is going to fall in the "OPERATOR" category and can't be defined as a "User-defined keyword".

**Comment by excel1star** [comment]
thanks
will check my version #
Alfred

**Comment by excel1star** [comment]
is the | required to delimit the collection of keywords?
Alfred

**Comment by excel1star** [comment]
Ok! Need to enter keywords in lower case!
Alfred

**Comment by excel1star** [comment]
That's a great help!
I used my own color settings for VBA and I want to publish documents that
carry my settings.
I now can do this with ease with NotePad++.
Alfred

**Comment by sasumner** [comment]
>is the | required to delimit the collection of keywords?

Sorry the `|` was just where my editing caret/cursor was when I took the screenshot!

**Comment by excel1star** [comment]
Thanks for your help! Made my day!
Alfred
