### ISSUE TITLE
sorry,I pressed the wrong button

### ISSUE THREAD

**Issue by Mishastyle** [notepad-plus-plus/notepad-plus-plus#9246]
### Steps to Reproduce the Issue

1. 
2. 
3.

**Comment by sasumner** [comment]
Best issue, EVER!  LOL

**Comment by Mishastyle** [comment]
ну дат вот, выдели вы бы моё состояние
а всего лишь хочу звдонатить и спокойно изучать программу


чт, 10 дек. 2020 г. в 19:56, sasumner <notifications@github.com>:
