### ISSUE TITLE
Developers should not bring personal political stances into their work.

### ISSUE THREAD

**Issue by make17better** [notepad-plus-plus/notepad-plus-plus#9248]
Programistoj ne devas alporti personajn politikajn sintenojn al sia laboro.

軟體開發者不應該將個人政治立場帶到自己的作品中。

程序开发者不应该把自己的政治立场带到作品中去。

開発者は、個人的な政治的立場を仕事に取り入れるべきではありません。

개발자는 자신의 작업에 개인적인 정치적 입장을 가져서는 안됩니다.

Entwickler sollten keine persönlichen politischen Positionen in ihre Arbeit einbringen.

Разработчики не должны привносить в свою работу личные политические взгляды.

Les développeurs ne devraient pas introduire de positions politiques personnelles dans leur travail.

Gli sviluppatori non dovrebbero portare posizioni politiche personali nel loro lavoro.

Os desenvolvedores não devem incluir posições políticas pessoais em seu trabalho.

Los desarrolladores no deben incorporar posturas políticas personales en su trabajo.

يجب على المطورين عدم إدخال مواقف سياسية شخصية في عملهم.

**Comment by shit-cpu** [comment]
香港是中国的香港，维护国家安全、守护“一国两制”，夯实香港宪制秩序和法治秩序，保障香港同胞自由权益，没有妥协余地。任何人以任何名义践踏香港法治尊严、破坏社会安定、侵害公众利益，必将受到法律严惩。

**Comment by Korb** [comment]
This is a duplicate of #6288 (disrespect for other members of the FOSS community by posting political propaganda spam in text editor resources).
