### ISSUE TITLE
[Hong-Kong] You even don't know the fact.

### ISSUE THREAD

**Issue by FishHe** [notepad-plus-plus/notepad-plus-plus#9249]
The authors have no knowledge about China and its History, and spread rumors.
Though NPP may be a convenient software, I will firmly uninstall NPP forever.

反对国家分裂，维护祖国和平统一是每一个公民的责任和义务！在NPP正式道歉以前，如果你是一个有良知的中国人，请卸载NPP。

**Comment by shit-cpu** [comment]
Seeking stability and tranquility and punishing anti-China chaos in Hong Kong in accordance with the law is the mainstream public opinion in Hong Kong. The anti-China and Hong Kong forces manipulate public opinion for their own interests, instigate the illegal assembly of radical protesters, assist in abetting violence against law enforcement, wantonly destroying public facilities, madly attacking innocent citizens, and even blatantly insulting and defaceting the national flag and national emblem. These violent acts that severely undermine the rule of law, seriously endanger national sovereignty, security, and development interests have harmed Hong Kong. The 7.5 million Hong Kong people hate it. It is even more clear that "who is driving Hong Kong to a dead end" and "who really is Hong Kong" is even more obvious. Condensed a broad consensus of "stability not to be disturbed, and rule of law not to be disrupted."

**Comment by Ayx03** [comment]
[Why you shouldn't use Notepad++ (reasons out of politics) | 为什么你不应该用Notepad++（政治之外的原因）](https://zhuanlan.zhihu.com/p/90102369)
There are also many Notepad++ replacements:
[Notepad2](https://notepad2.com/) | [Github Releases](https://github.com/zufuliu/notepad2/releases)
[Notepad3](https://www.rizonesoft.com/downloads/notepad3/) | [Github Releases](https://github.com/rizonesoft/Notepad3/releases)
[Visual Studio Code - Code Editing. Redefined](https://code.visualstudio.com/)
[Sublime Text - Text Editing, Done Right](http://www.sublimetext.com/)
[EmEditor (Text Editor) – Text Editor for Windows supporting large files and Unicode!](https://www.emeditor.com/)
[CP Editor](https://cpeditor.org/)

**Comment by AFewMoon** [comment]
I hope china police will look to that stupid aggressive boy.
