### ISSUE TITLE
Compare plugin Next/Prev keyboard shortcut doesn't work anymore

### ISSUE THREAD

**Issue by SchulzeyBoy** [notepad-plus-plus/notepad-plus-plus#925]
After comparing two text files using the Compare plugin, Ctrl-PageUp/Dn (that used to go to the next/previous difference) doesn't work anymore in v6.8.3 of Notepad++. It is killing me, as I use it all the time. It seems to be a problem with Notepad++ itself rather than the plugin because if I install an old version of the Compare plugin that used to work it still has the problem. Is there a work-around?

**Comment by h-h-h-h** [comment]
As in other software, these shortcuts should be used for a similar purpose as <kbd>Ctrl</kbd>+<kbd>Up</kbd>/<kbd>Down</kbd>, but [without changing cursor position](https://github.com/notepad-plus-plus/notepad-plus-plus/issues/719).

Try editing the plug-in settings or write to the author of the plug-in.

**Comment by SchulzeyBoy** [comment]
It's not Ctrl-Up/Down, it's Ctrl-PageUp/Down

**Comment by h-h-h-h** [comment]
The shortcuts mentioned in the first comment should behave *similar* to the ones mentioned in the second comment, i.e., they should be used for scrolling. This means, you can't claim them to be held free for the use by a plug-in. Either the plug-in knows how to redefine existing shortcuts, or you're out of luck. This is why I told to talk to the author of the plug-in.

**Comment by stanmoore1** [comment]
+1, This issue is also killing me. I had to revert back to an older version of Notepad++ to get the Compare plugin to work correctly.

**Comment by dail8859** [comment]
Closing due to this being 3rd party plugin related. [Compare plugin repository](https://github.com/pnedev/compare-plugin)
