### ISSUE TITLE
Search in files does not search in a file when it is opened

### ISSUE THREAD

**Issue by EN20M** [notepad-plus-plus/notepad-plus-plus#9250]
### Description of the Issue
When a file is opened and you use the search in files funktionality on a folder with that file the file seams to not be searched through as is in the folder but instead the opened instance gets searched through. When for example you add "foo" to the file outside of notepad you are not able to get a match for searching for "foo" until you scope the changed file and allow notpad to reload its content.

### Steps to Reproduce the Issue
1. open 2 files that are in the same folder
2. have the scope on file B
3. add a string of your choise to file A outside of notepad and save the file
4. with file B still in scope use the search in files feature to search for your string in the folder that contains file A & B
5. scope file A and allow npp to reload the changed content
6. repeat step 4

### Expected Behavior
That the sring is found no matter if the opend instance is up to date ore not (step 4 AND 6). I expect notepad to search through the file and not the possibly opend instances that may or may not be up to date when they are not in scope.

### Actual Behavior
Only at step 6 the search will find a match for your sting.

### Debug Information
Notepad++ v7.9.1   (64-bit)
Build time : Nov  2 2020 - 01:07:46
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS Name : Windows 10 Pro (64-bit) 
OS Version : 2009
OS Build : 19042.685
Current ANSI codepage : 1252
Plugins : ComparePlugin.dll MarkdownViewerPlusPlus.dll mimeTools.dll NppConverter.dll NppExport.dll NppMarkdownPanel.dll zoomdisabler_x64.dll

**Comment by sasumner** [comment]
>but instead the opened instance gets searched through

Yes, this behavior is "by design" and isn't going to be changed.
