### ISSUE TITLE
Support syntax highlighting for Dart

### ISSUE THREAD

**Issue by czoins** [notepad-plus-plus/notepad-plus-plus#9252]
### Description of the Issue

Hey! It would be great if you can add syntax highlighting support for Dart(dartlang), as right now the closest you can get is by using Java/Smalltalk styles but they aren't accurate.

**Comment by chcg** [comment]
See https://github.com/notepad-plus-plus/notepad-plus-plus/tree/master/scintilla/lexers. There is np support from the underlying scintilla and therefore also no builtin support for N++. So this needs to go to https://sourceforge.net/p/scintilla/feature-requests/, before N++ could add the support.
