### ISSUE TITLE
PluginAdmin doesn't show Unicode texts

### ISSUE THREAD

**Issue by chcg** [notepad-plus-plus/notepad-plus-plus#9266]
### Description of the Issue
UTF8 json input from plugin list is not displayed properly in PluginAdmin

### Steps to Reproduce the Issue

Input from https://github.com/notepad-plus-plus/nppPluginList/blob/master/src/pl.x86.json#L833
			"author": "João Rosa",

is displayed as shown below.

### Expected Behavior
João  should be displayed as shown also here. 

### Actual Behavior
![grafik](https://user-images.githubusercontent.com/12630740/102131786-04e11680-3e53-11eb-81ba-cf0466368030.png)

### Debug Information
N++ 7.9.1

See
https://stackoverflow.com/questions/583562/json-character-encoding-is-utf-8-well-supported-by-browsers-or-should-i-use-nu
on utf8 support for json.

**Comment by dinkumoil** [comment]
Old story, still seems to be unfixed. Have a look at the following links:

https://community.notepad-plus-plus.org/topic/16566/support-for-plugins-admin-npppluginlist/2 (and 2 following comments)
https://github.com/notepad-plus-plus/nppPluginList/pull/11#issuecomment-435954300

**Comment by chcg** [comment]
Fix is available by PR #9267.
