### ISSUE TITLE
Add SPARQL syntax support

### ISSUE THREAD

**Issue by Codain** [notepad-plus-plus/notepad-plus-plus#9279]
### Description of the Issue
When looking into Language menu there is no SPARQL option.
When opening a SPARQL file (.sparql) syntax is not recognized.

### Enhancement
Add SPARQL as a syntax language.

It seems something already exists but have no idea if this would help or not (license, syntax coverage...), see https://xslt-tricks.blogspot.com/2014/03/sparql-highlighting-in-notepad.html

**Comment by chcg** [comment]
Available also from https://github.com/notepad-plus-plus/userDefinedLanguages/blob/master/UDLs/SPARQL-v1p1_byFranckMichel.xml.
See readme at https://github.com/notepad-plus-plus/userDefinedLanguages how to use that UserDefinedLanguage definition. This needs a manual installation step by you as also described in the original post.

There is and willnot be a builtin support for SPARQL.

**Comment by Codain** [comment]
Thanks @chcg for quick feedback,
