### ISSUE TITLE
Change "cloud" terminology

### ISSUE THREAD

**Issue by dail8859** [notepad-plus-plus/notepad-plus-plus#928]
Previously, the user was able to select a cloud location, like Google Drive, Dropbox, etc. However, now that this option has been changed to allow the user to select _any_ location, not just for a cloud service. Changing this to something more generic would make it so the user does not think they _must_ only use directory for a cloud service.

![capture](https://cloud.githubusercontent.com/assets/3694843/9935562/538a720a-5d25-11e5-8ec6-cc37f3dd8ead.PNG)

**Comment by sanastasiou** [comment]
Please also consider this https://github.com/notepad-plus-plus/notepad-plus-plus/issues/862 if you're fixing this cosmetic change :)

**Comment by dail8859** [comment]
#862 is completely unrelated. Yes it deals with settings but this is literally just changing words in the GUI

**Comment by donho** [comment]
@dail8859 What terminology are you suggesting to replace it?

**Comment by dail8859** [comment]
I can't say I've really come up with anything that great yet. I'll still give it some thought and see if any other people might have a better idea.

**Comment by dogancelik** [comment]
"Settings backup location"

**Comment by DarkNexusNR** [comment]
"Sync Location"

**Comment by MetaChuh** [comment]
@dail8859 
rejected, don't kill me now 😉

**Comment by dail8859** [comment]
@MetaChuh I'll let it pass. But just this one time. :) jk

**Comment by h-h-h-h** [comment]
> But just this one time.

Then, there's trouble on the horizon, because, currently, *all* issues are being closed.

**Comment by sasumner** [comment]
I've often thought the same as Dail about this naming "problem" but I've never noticed this issue having been created.  I guess if I was on a search-n-destroy mission like Meta and Don seem to be on I would have seen it...

BTW this whole "mission" would be much easier if github offered a "reject-and-close-all-issues" or maybe a "reject-and-close-all-issues-no-matter-how-relevant-they-still-are" or even a "reject-and-close-all-issues-with-some-lame-ass-comment-about-retesting-in-current-version-even-though-everybody-in-the-universe-knows-the-issues-are-still-there".

**Comment by donho** [comment]
@sasumner 

>  I guess if I was on a search-n-destroy mission like Meta and Don seem to be on I would have seen it...

It's not only about Meta's and my "mission", all team members @chcg & @dail8859 are encouraged for killing the old issues - it'll be great to make issue trackers as clean as possible so all the issues could be viewed and treated.

> reject-and-close-all-issues-with-some-lame-ass-comment-about-retesting-in-current-version-even-though-everybody-in-the-universe-knows-the-issues-are-still-there

Well, passing 2500 old issues and validating them one by one is not only just PITA, but impossible. My idea is close them all - 70% of them are outdated, and 30% will be brought back by users with the latest version. In this way you will talk with active users with the updated information.
