### ISSUE TITLE
Add a startup variable containing the disk on which the file is located, or add a startup option that runs in the directory with the file.

### ISSUE THREAD

**Issue by NewLife1324** [notepad-plus-plus/notepad-plus-plus#9280]
I have some script that needs to be run. To do this, I use F5. cmd /k python" $(FULL_CURRENT_PATH) " executes a file from the directory where notepad is installed. The file itself is located on another disk. It is not very convenient to specify the startup command, where you first need to go to a specific disk, and then also go to the desired directory

**Comment by sasumner** [comment]
Do it this way:

`cmd /k echo cd /d $(CURRENT_DIRECTORY) && python $(FULL_CURRENT_PATH)`
