### ISSUE TITLE
Translation - german

### ISSUE THREAD

**Issue by Henry2o1o** [notepad-plus-plus/notepad-plus-plus#9281]
![image](https://user-images.githubusercontent.com/6131799/102692135-9533a880-4211-11eb-834a-74d799331e78.png)
👇
![image](https://user-images.githubusercontent.com/6131799/102692155-c7dda100-4211-11eb-9846-1079a153a6e9.png)
👇
![image](https://user-images.githubusercontent.com/6131799/102692182-0ffcc380-4212-11eb-889d-8451ca697eff.png)

**Comment by Henry2o1o** [comment]
https://github.com/notepad-plus-plus/notepad-plus-plus/pull/9122#issuecomment-748621797

**Comment by schnurlos** [comment]
Fixed here https://github.com/notepad-plus-plus/notepad-plus-plus/pull/9122/commits/7846ac6ace9f7a5709cc22f51b453aaa4e878b83.
You always should make comments on the last commit - makes things easier.
