### ISSUE TITLE
Feature request: highlight selection - case sensitivity  

### ISSUE THREAD

**Issue by RobTillaart** [notepad-plus-plus/notepad-plus-plus#9282]
### Description of the Issue

When I have a text I can select a word and the same word will highlight in LIGHT GREEN.
This highlighting is case insensitive, which can cause missing a difference.

### Steps to Reproduce the Issue

1. make a document with **beer** **BEER** and **BeEr** on different lines
2. select one of the words and all three will highlight
3. 

### Expected Behavior

Preferably I would like to see the same words highlighted, however if the case is different, that the highlight is different.

Implementation can in at least two ways:
- whole word is LIGHT BLUE  instead of LIGHT GREEN if one or more characters differ. [ preferred imho ]
- only the characters that differ are LIGHT BLUE.
- it should be no obstacle for colorblind so differ in brightness.

### Debug Information
Version 7.9.1, windows 10 Pro, 64 bit

**Comment by sasumner** [comment]
Go to _Settings_ menu and choose _Preferences..._.
Select _Highlighting_ from the box on the left.

You will see:
![image](https://user-images.githubusercontent.com/30118311/102698425-19366200-420b-11eb-9f44-b569e76ddae7.png)

Toggle the circled setting (_Match case_) per your need at a given moment in time.
Also note _Match whole word only_ and _Use Find dialog settings_ which may be handy in other similar circumstances.

>...BLUE...GREEN...

The "indicators" which do the coloring are in short supply.
We don't choose to utilize one of the few remaining to add a second color to the "highlighting" feature at this time.
