### ISSUE TITLE
Feature Request: Official App in Microsoft Store

### ISSUE THREAD

**Issue by MasonWilliamL** [notepad-plus-plus/notepad-plus-plus#9283]
I found a version of Notepad++ in the Microsoft Store but it is labelled (Unofficial). Is there a plan to officially release and support Notepad++ as a UWP app on the Microsoft Store?

Thanks for all you do!

**Comment by ArkadiuszMichalski** [comment]
Has been asked recently https://github.com/notepad-plus-plus/notepad-plus-plus/issues/9221.

**Comment by MasonWilliamL** [comment]
> 
> 
> Has been asked recently #9221.

Thanks! I tried searching but it must not have come up because it was marked closed.
