### ISSUE TITLE
perl function list empty

### ISSUE THREAD

**Issue by JohnL22** [notepad-plus-plus/notepad-plus-plus#9285]
perl 5 with Notepad++ version 7.9.1  - the function list is empty

### Steps to Reproduce the Issue
Minimal perl program to illustrate behaviour

sub with_proto($parm){};
sub without_proto {};

### Expected Behavior
function list should have header and 2 entries namely
with_proto
without_proto

### Actual Behavior
EMPTY function list

### Debug Information
Notepad++ v7.9.1   (64-bit)
Build time : Nov  2 2020 - 01:07:46
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS Name : Windows 10 Pro (64-bit) 
OS Version : 2009
OS Build : 19042.685
Current ANSI codepage : 1252
Plugins : ComparePlugin.dll DSpellCheck.dll mimeTools.dll NppConverter.dll NppExport.dll 

Tested same minimal perl program with several versions of notepad++ (all 64-bit zip versions)
version 7 - produces CORRECT function list with program heading and 2 functions (subs) listed
version 7.3.3, 7.56, 7.64, 7.8 show a function list with header and ONE function (sub) namely "with_proto"
##
I assume the problem lies in FunctionList.xml around the lines introduced by 
 PERL - Practical Extraction and Reporting Language   
with
functionName
						nameExpr expr="(?:sub\s+)?\K[A-Za-z_]\w*" /

###NOTE angle brackets removed so the lines show here####
##
but I can not fix it

**Comment by sasumner** [comment]
I copied your sample lines into a .pl file and had zero problems with _Function List_ showing it:

![image](https://user-images.githubusercontent.com/30118311/102700072-17bf6680-4218-11eb-9dc0-19b521281532.png)

Without more info, I think we have to go with "not reproducible".

**Comment by JohnL22** [comment]
My machine produces this instead
![image](https://user-images.githubusercontent.com/76265468/102702444-a1902380-425a-11eb-9093-2f7c52fb025c.png)


I will download a new copy & try that...

**Comment by JohnL22** [comment]
Success - New, clean 7.91. 64-bit zip version works.

Found  - updating an already installed version produces the error. Perhaps the problem is in the update-install process.

I notice the NEW version has a directory "functionList" in place of the former FunctionList.xml in the updated version.

I will remove & install the application
