### ISSUE TITLE
NULL bytes in hex editor and hex conversion show as '20' (space).

### ISSUE THREAD

**Issue by r-hoogenboom** [notepad-plus-plus/notepad-plus-plus#9289]
### Description of the Issue

When selecting a piece from a binary file containing null bytes and converting to hex or when copying null bytes in the hex editor and pasting them, they turn up as 20 instead of 00 (space instead of null).

### Steps to Reproduce the Issue

1. open a binary file with null bytes
2. select a range including null bytes (they show as NUL in black rounded rectangle)
3. Plugins->Converter->ASCII --> HEX
4. The NUL bytes show as 20

OR

1. open a binary file with null bytes
2. Plugins->Hex-Editor->View in HEX
3. Null bytes show as 00
4. Copy a range in the hex part including some 00 bytes
5. Paste it somewhere else
6. The bytes that were shown 00 are now 20

### Expected Behavior

I expect null bytes to show as 00 in hex always.

### Actual Behavior

The null bytes turn to 20.

### Debug Information

Notepad++ v7.9.1   (64-bit)
Build time : Nov  2 2020 - 01:07:46
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS Name : Windows 10 Enterprise (64-bit) 
OS Version : 1909
OS Build : 18363.1256
Current ANSI codepage : 1252
Plugins : HexEditor.dll mimeTools.dll NppConverter.dll NppExport.dll

**Comment by sasumner** [comment]
Notepad++ and consequently plugins don't handle NUL bytes all that well.
I'm not sure when/if that situation will change, but if it happens, it will probably happen very slowly.
Probably the best suggestion for whatever you're doing currently is a true hex editor.

**Comment by r-hoogenboom** [comment]
Unfortunately. Back to my trusty vim + xxd then...

**Comment by chcg** [comment]
There are already issues at:
https://github.com/chcg/NPP_HexEdit/issues/22
https://github.com/chcg/NPP_HexEdit/issues/24
regarding this problem.

**Comment by r-hoogenboom** [comment]
Since it occurs both with the 'convert to hex' and the hexedit (while the hexedit itself shows it correctly), I expected the root cause to be more generic.

**Comment by sasumner** [comment]
It probably IS more generic, in that, as I said, Notepad++ doesn't do well with NUL bytes.
But it is likely that creating a (more generic) issue called "make N++ handle NUL bytes better" wouldn't gain much traction.

**Comment by r-hoogenboom** [comment]
So therefore you suggest the plugins to work around the fundamental problem that is most probably much easier solved in the place where it is created? This probably means that once the plugins have found a way to work around it, the fundamental problem can never be solved anymore because that will break the plugins again.
Anyway... It's your call. I'm not your project manager.

**Comment by sasumner** [comment]
NUL bytes aren't really text.  Notepad++ is a text editor.  Use a hex editor.

**Comment by r-hoogenboom** [comment]
OK this confirms NPP is not for me then. Sorry to have wasted your and my time to report this issue.

**Comment by sasumner** [comment]
Just to round out my previous answers:

Notepad++'s core editing component (Scintilla) seems to support NUL bytes well (at least I don't know of any deficiencies that lead back to Scintilla).  But as a long-time user/observer of Notepad++, I don't think someone with your need (and it is an "implied need", since I really don't know what your task is), is going to be 100% pleased with Notepad++'s other handling of NUL bytes.  I can't say "these are the problems" and then list them out 1,2,3, etc., but these are just my overall feelings about it.
