### ISSUE TITLE
english.xml 7.9.1 vs 7.9.2 for all localization files

### ISSUE THREAD

**Issue by donho** [notepad-plus-plus/notepad-plus-plus#9293]
For Notepad++ localization file maintainers, here's the diff of `english.xml` from 7.9.1 to 7.9.2:
[791vs792.zip](https://github.com/notepad-plus-plus/notepad-plus-plus/files/5727413/791vs792.zip)

**Comment by ArkadiuszMichalski** [comment]
@donho 
Missing this: `<Item id="6208" name="Show vertical edge"/>`. If I have some more values, I cannot turn it on / off without deleting all of them. Some switch would be advisable:
- show
- display
- or other name

![image](https://user-images.githubusercontent.com/2730894/102906200-944e8100-4474-11eb-8d22-7048804e8071.png)

**Comment by donho** [comment]
@ArkadiuszMichalski 
> Missing this: `<Item id="6208" name="Show vertical edge"/>`.

This control has been removed since the previous versions. 

>  If I have some more values, I cannot turn it on / off without deleting all of them. Some switch would be advisable.

Remove all the values will turn it off.
