### ISSUE TITLE
Exception vector<T> too long in DllSpellChecker plugin

### ISSUE THREAD

**Issue by harper23** [notepad-plus-plus/notepad-plus-plus#9299]
### Description of the Issue
When scrolling horizontally, a message pops up:
    PluginsManager::runPluginCOmmand Exception
    vector<T> too long
if the text contains this long line:

./configure --host='i686-w64-mingw32.static.posix' --build='x86_64-pc-linux-gnu' --prefix='/home/User/sr_msys2_release_64'  --enable-static --disable-shared  ac_cv_prog_HAVE_DOXYGEN="false" --enable-doc=no --enable-gtk-doc=no --enable-gtk-doc-html=no --enable-gtk-doc-pdf=no --{docdir,infodir,mandir,with-html-dir}='/home/Helge/mxe-git/tmp-libusb1-i686-w64-mingw32.static.posix/libusb-event-abstraction-v4.build_.sink' --disable-doxygen CFLAGS=-D_WIN32_WINNT=0x0500 | tee configure.log

### Steps to Reproduce the Issue
1.  Enter this long line.
2.  Scroll to right

### Expected Behavior
Scrolling the window.

### Actual Behavior
Exception.

### Debug Information
Notepad++ v7.9.1   (32-bit)
Build time : Nov  2 2020 - 01:03:56
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : ON
Local Conf mode : OFF
OS Name : Windows 10 Enterprise (64-bit) 
OS Version : 1909
OS Build : 18363.1256
Current ANSI codepage : 1252
Plugins : DSpellCheck.dll mimeTools.dll NppConverter.dll NppExport.dll

**Comment by sasumner** [comment]
Try removing the DSpellCheck plugin.
If the problem goes away, you may need to make sure you have the latest DSpellCheck.

**Comment by harper23** [comment]
I just installed the Notepad++ update. So the DllSpellChecker plugin is
(should be) up-to-date.

Regards,
Helge

sasumner <notifications@github.com> schrieb am Mi., 23. Dez. 2020, 13:58:

**Comment by sasumner** [comment]
>So the DllSpellChecker plugin is (should be) up-to-date.

Why do you think that a plugin that isn't shipped with Notepad++ would be affected by a Notepad++ update???
