### ISSUE TITLE
Crush after open files via context menu - "edit with notepad++" and close them on Windows 10

### ISSUE THREAD

**Issue by lychichem** [notepad-plus-plus/notepad-plus-plus#93]
If you open some special files on Windows 10 and close notepad++, the program will crash. The latest version of notepad++ and Windows 10 x64 version, special files include modified host file and some userscript for firefox. Hard to reproduce because I don't know which is the special file.

**Comment by lychichem** [comment]
Can confirm this issue. This happens when you right cilck a file in Windows 10 to "edit it with Notepad++" and close it. When closing the file Notepad++ will 100% crash.

**Comment by ariccio** [comment]
Can you open up the dump in `windbg` and run `!analyze -v`?

**Comment by lychichem** [comment]
Can you give me the file path? I don't know where the file is

发自我的 Windows Phone
________________________________
发件人: Alexander Riccio<mailto:notifications@github.com>
发送时间: ‎2015/‎5/‎28 11:12
收件人: donho/notepad-plus-plus<mailto:notepad-plus-plus@noreply.github.com>
抄送: Chi Lei<mailto:leichixian@outlook.com>
主题: Re: [notepad-plus-plus] Crush after open files via context menu - "edit with notepad++" and close them on Windows 10 (#93)

Can you open up the dump in `windbg` and run `!analyze -v`?

---

**Comment by ariccio** [comment]
Sorry about that. Notepad++ sometimes stores a dump of its own in the Notepad++ folder in `Program Files (x86)`. Windbg is installed with the Windows SDK.

**Comment by lychichem** [comment]
@ariccio Sorry to tell you that there is no dump file at all. I think it is because Notepad++ can't exit properly and is forced closed by windows so there is no dump file.

**Comment by donho** [comment]
@lychichem Could you provide your plugin list please? As well, your Windows 10 info (localisation).

**Comment by lychichem** [comment]
@donho Very Glad to give you all the info.  Hope they will help you find out the reason and solve the issue. Notepad++ is a great code editor.
![default](https://cloud.githubusercontent.com/assets/9316590/7862510/f33cae20-0588-11e5-906c-bd9573a62309.JPG)
![1](https://cloud.githubusercontent.com/assets/9316590/7862511/f3403b58-0588-11e5-9489-6783c4ab35b8.JPG)
![2](https://cloud.githubusercontent.com/assets/9316590/7862512/f3482836-0588-11e5-8351-fb329844cbf9.JPG)
![3](https://cloud.githubusercontent.com/assets/9316590/7862513/f34bfd30-0588-11e5-9e22-6613e7d9c2ec.JPG)

**Comment by skalldri** [comment]
I've been having this issue as well. As a workaround, it seems to be solved by enabling Windows 7 Compatibility Mode on the Notepad++ executable.

**Comment by ariccio** [comment]
Since `Notepad++` asks to save a dump file, can either of you do so?

**Comment by lychichem** [comment]
nope, because when it can,t close the program just have no response, and if you manually kill the process, no dump file will be given.

发自我的 Windows Phone
________________________________
发件人: Alexander Riccio<mailto:notifications@github.com>
发送时间: ‎2015/‎6/‎22 8:01
收件人: notepad-plus-plus/notepad-plus-plus<mailto:notepad-plus-plus@noreply.github.com>
抄送: Chi Lei<mailto:leichixian@outlook.com>
主题: Re: [notepad-plus-plus] Crush after open files via context menu - "edit with notepad++" and close them on Windows 10 (#93)

Since `Notepad++` asks to save a dump file, can either of you do so?

---

**Comment by ariccio** [comment]
Hmph. When it hangs, can you create a dump by right clicking on it in task manager?

**Comment by lychichem** [comment]
Thanks for your help, but I use visual studio code now😊

发自我的 Windows Phone
________________________________
发件人: Alexander Riccio<mailto:notifications@github.com>
发送时间: ‎2015/‎6/‎22 9:40
收件人: notepad-plus-plus/notepad-plus-plus<mailto:notepad-plus-plus@noreply.github.com>
抄送: Chi Lei<mailto:leichixian@outlook.com>
主题: Re: [notepad-plus-plus] Crush after open files via context menu - "edit with notepad++" and close them on Windows 10 (#93)

Hmph. When it hangs, can you create a dump by right clicking on it in task manager?

---

**Comment by skalldri** [comment]
@ariccio I'll try and reproduce the bug for you: I removed compatibility mode and now it's gone away... weird.

**Comment by donho** [comment]
@lychichem I believe your problem has been fixed in new release 6.7.9.1

**Comment by lychichem** [comment]
@donho Well, seems fixed. But now I prefer Visual Studio Code for its build-in git support. Thank you all the same.

**Comment by skalldri** [comment]
Well, I was finally able to get a dump of the problem in action. The dump is pretty big though: I can upload it to Dropbox or something and send you the link via email.

**Comment by milipili** [comment]
Please send it to me.

**Comment by skalldri** [comment]
Here's the dump file:

https://dl.dropboxusercontent.com/u/889011/notepad%2B%2B.DMP

I'm not exactly certain how to reproduce it consistently. It seems to occur when trying to close Notepad++ after opening files via the "Edit in Notepad++" option in Windows Explorer. However, it isn't consistent (at least from what I can find).

It seems to go away if you run Notepad++ in compatibility mode for Windows 7 or 8.

**Comment by QwisoDev** [comment]
Confirming this still happens with v6.8.1 -- Updated to v6.8.3 and will see if it continues

Windows 10 host file is the culprit
