### ISSUE TITLE
if - endif code folding

### ISSUE THREAD

**Issue by skeets23** [notepad-plus-plus/notepad-plus-plus#930]
Code folding for PHP is not working for alternative syntax such as 

if():

endif;

for():

endfor;

foreach():

endforeach;

I like to keep my code more clear than just a closing bracket. That way I know for certain that "endif;" will never close a for loop, etc. However, not having code folding is really a pain.

I am running notepad++ v.6.8.3 on windows 10.

**Comment by donho** [comment]
It's rather a feature request for Scintilla (the editor component used by Notepad++).
Please check:
http://www.scintilla.org/
