### ISSUE TITLE
Bug still not fixed

### ISSUE THREAD

**Issue by nichollsvi** [notepad-plus-plus/notepad-plus-plus#9312]
In https://github.com/notepad-plus-plus/notepad-plus-plus/issues/6133, it was described that since 2017, there was a bug saving items. Its still here, and I got a mess when I find out that the backups I thought were occuring weren't. Why is Notetab++ ignoring for years an issue that hasn't been fixed?

For years I used notetab++ but I'm moving to other software that is free and actually makes backups. I'm going to be loud in showing that I find out that years have gone on without anything being done to fix a problem that was known years ago. Backups are instrumental, fooling people into thinking they don't have one isn't a good thing. I was able to get back everything else - but notetab++ items.

**Comment by sasumner** [comment]
Closing because (a) template was not followed, esp. "Debug Information" not provided and (b) any discussion that starts out as "In # 6133..." should just be continued in 6133.

**Comment by nichollsvi** [comment]
You closed 6133! Why would I continue it when the bug closed is still there. I still have the same symptoms. I had a system blip that shut down the computer. When I came back, all the backup files were gone. I used a tool to get the files back and they were corrupted. 
So you refuse to address a known bug?

**Comment by sasumner** [comment]
Comments made in 6133 would be seen and, if warranted, it could be reopened.
Since you previously indicated that you would be "moving to other software" from "notetab++"(??), it seems that you hardly care if this is looked into or not.

**Comment by nichollsvi** [comment]
So that gives you the excuse to not fix a bug that has outstanding for years? I think this needs to be well publicized, the attitude to a bug that other software has fixed. Backups are important and if the ones doing NPP don't care, lets publicize that don't care to everyone. I'll keep putting my foot on it because your attitude is not a condusive one to a good customer product. Since you don't want to fix the bugs, lets make sure no one uses the product and you won't have that problem.
