### ISSUE TITLE
[SUGGESTION] Make word search (or expression) to contain a synonym in the dictionary

### ISSUE THREAD

**Issue by me-suzy** [notepad-plus-plus/notepad-plus-plus#9323]
### Description of the Issue
Too many search attempts

### Expected Behavior

Hello, I work in the field of applied informatics in applied physics. I want to search in notepad ++ the following expression **"on the same line"**, but it is the same expression as **"on the same row"** or as **"on the same segment"**. So, in order not to search 3 times, I would put in a personal dictionary these 3 expressions that would lead to the same result.

An hypothetical example, I want to make a search:  **"on the same line"** This will lead to:

I have two elements **on the same line** floated left and floated right.
If you're **on the same row** with an 'enemy', waiting for the green light to hunt for the passenger,
How does one prove that the angles **on the same segment** of a circle are equal?

**Comment by sasumner** [comment]
>So, in order not to search 3 times...

Search in "regular expression" search mode for `on the same (line|row|segment)`

**Comment by me-suzy** [comment]
thanks
