### ISSUE TITLE
Regression: Chinese Simplified localization doesn't work on v7.9.2

### ISSUE THREAD

**Issue by donho** [notepad-plus-plus/notepad-plus-plus#9329]
### Description of the Issue
Chinese Simplified localization doesn't work on v7.9.2 - it does work in v7.9.1

### Steps to Reproduce the Issue
Open Preference dialog and chose Chinese Simplified localization.

### Expected Behavior
The interface changes in Chinese.

### Actual Behavior
The interface remains in English.

### Debug Information
Notepad++ v7.9.2   (32-bit)
Build time : Dec 31 2020 - 03:58:36
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : ON
Local Conf mode : OFF
OS Name : Windows 10 Enterprise (64-bit) 
OS Version : 2004
OS Build : 19041.685
Current ANSI codepage : 1252
Plugins : DSpellCheck.dll HexEditor.dll mimeTools.dll NppConverter.dll NppExport.dll NppXmlTreeviewPlugin.dll 

Bug report from: [Notepad++ community forum](https://community.notepad-plus-plus.org/topic/20537/notepad-v7-9-2-released/2?_=1609512288682)

**Comment by donho** [comment]
It's due to a bad Copy/Paste in this commit:
https://github.com/notepad-plus-plus/notepad-plus-plus/commit/528712f050c2380ec84c9be0457d43eb9b9475fa#r45564456

**Comment by scmyyc** [comment]
I have the same problem

**Comment by popcorner** [comment]
@donho My fault, sorry.
I use Git to make a diff file to find out the changes in english.xml, and merge them **manually** with Chinese translation.
Maybe I forgot that line or something went wrong when merging that diff file. The changes at that line left unmerged.
Sorry about that.
I've checked the rest part of my translation again and no issue found.

I'll try to add an automatically workflow while merging new translations to avoid this kind of issue.

And is it possible to let the CI platform check if the translation files in PR are valid xml? Maybe it can avoid similar issues.

**Comment by donho** [comment]
@popcorner 
No problem - it's also my fault, because I've merged it without checking.

> And is it possible to let the CI platform check if the translation files in PR are valid xml?

Yes, indeed. It's the things to do to avoid such regression for any XML file in the future.
I've created an issue here and I'll work on it ASAP:
https://github.com/notepad-plus-plus/notepad-plus-plus/issues/9330

**Comment by sonichy** [comment]
Same problem, 24 days passed, why not fixed yet ?

**Comment by SirnoChan** [comment]
> 
> 
> Same problem, 24 days passed, why not fixed yet ?

The released binary version was built with that old wrong translation .xml file and the [source file](../blob/master/PowerEditor/installer/nativeLang/chineseSimplified.xml) has been corrected now.
