### ISSUE TITLE
Check XML validation in Notepad++ build system

### ISSUE THREAD

**Issue by donho** [notepad-plus-plus/notepad-plus-plus#9330]
An invalid xml could make disfunction in Notepad++ as problem in https://github.com/notepad-plus-plus/notepad-plus-plus/issues/9329 .

To avoid such problem, it's necessary to check the whole set of XML files in Notepad++'s AppVeyor settings to ensure the validity of these files.

**Comment by donho** [comment]
@chcg 
Could it be done by you?
Or I can plagiarize your script from here:
https://github.com/notepad-plus-plus/userDefinedLanguages/blob/master/validator_xml.py
?

**Comment by chcg** [comment]
@donho I could do the change. The validator script is a good starting point. Maybe also a schema could be added. What needs to be checked ?
- https://github.com/notepad-plus-plus/notepad-plus-plus/tree/master/PowerEditor/installer/APIs
- https://github.com/notepad-plus-plus/notepad-plus-plus/tree/master/PowerEditor/installer/functionList
- https://github.com/notepad-plus-plus/notepad-plus-plus/tree/master/PowerEditor/installer/nativeLang
- https://github.com/notepad-plus-plus/notepad-plus-plus/tree/master/PowerEditor/installer/themes

Did I miss further ones?

**Comment by chcg** [comment]
See also https://github.com/notepad-plus-plus/notepad-plus-plus/pull/5112 , so maybe also the N++ config files under
https://github.com/notepad-plus-plus/notepad-plus-plus/tree/master/PowerEditor/src
- https://github.com/notepad-plus-plus/notepad-plus-plus/blob/master/PowerEditor/src/config.4zipPackage.xml
- https://github.com/notepad-plus-plus/notepad-plus-plus/blob/master/PowerEditor/src/contextMenu.xml
- https://github.com/notepad-plus-plus/notepad-plus-plus/blob/master/PowerEditor/src/langs.model.xml
- https://github.com/notepad-plus-plus/notepad-plus-plus/blob/master/PowerEditor/src/shortcuts.xml
- https://github.com/notepad-plus-plus/notepad-plus-plus/blob/master/PowerEditor/src/stylers.model.xml
- https://github.com/notepad-plus-plus/notepad-plus-plus/blob/master/PowerEditor/src/toolbarIcons.xml
- https://github.com/notepad-plus-plus/notepad-plus-plus/blob/master/PowerEditor/src/userDefineLang.xml

**Comment by ArkadiuszMichalski** [comment]
For major changes (when it concerns manipulation of nodes), you can inform people that they can validate XML with some online tool before sending, I recommend:
https://codebeautify.org/xmlvalidator
