### ISSUE TITLE
Hong Kong has lost, this is merely a meme now

### ISSUE THREAD

**Issue by Chaython** [notepad-plus-plus/notepad-plus-plus#9335]
Your stand for Hong Kong free Hong Kong social justice BS is a failure. It's just an annoyance when someone is actually looking for patch notes.
Hong Kong separatists lost **Hong Kong is a city in China!** Nothing more!

**Comment by Hiimjustjames** [comment]
He lives in Hong Kong. He is probably not going to stop and he shouldn't.

**Comment by Gemorroj** [comment]
I hope china police will look to that stupid aggressive boy.

**Comment by Gemorroj** [comment]
I hope china police will look to that stupid aggressive boy.

**Comment by AFewMoon** [comment]
> I hope china police will look to that stupid aggressive boy.

So do I!
