### ISSUE TITLE
‘containing’ line numbers from Find result window not copied anymore

### ISSUE THREAD

**Issue by rhermsen** [notepad-plus-plus/notepad-plus-plus#934]
From version Notepad++ v6.7.9 (Jun 9 2015) (tested with v6.7.9.1 (Built time: Jun 20 2015 – 11:29:14)) Notepad++ doesn’t copy the ‘containing’ line number anymore from the Find results window. It still does show duplicate lines if there are multiple matches for the same line number.
Due to the missing (containing) line numbers it is difficult to determine which lines are duplicates after copying these lines.
In earlier version (e.g. with v6.7.8.2 (May 23 2015)) it did copy the containing line numbers from the Find results window.

Possible related to: 
https://notepad-plus-plus.org/community/topic/10423/copy-text-from-search-text-in-folders
(and maybe: https://github.com/notepad-plus-plus/notepad-plus-plus/pull/68 )

Question1: Is there a setting to get the old behavior back?
Question2: Is it possible to show only one line in the Find results window, even if there are multiple matches?
Answer2 (from 2010): Yes using regex: http://superuser.com/questions/181002/notepad-ignoring-search-results-on-same-line

Example:
This is just an line, with line number 1.
This line contains only one time the word apple, on line 2.
This is just an line, with line number 3.
This line contains the word apple two times, so one more apple in this line with line number 4.
This is just an line, with line number 5.
This is just an line, with line number 6.
This is just an line, with line number 7.

v6.7.8.2 behavior:
    Line 2: This line contains only one time the word apple, on line 2.
    Line 4: This line contains the word apple two times, so one more apple in this line with line number 4.
    Line 4: This line contains the word apple two times, so one more apple in this line with line number 4.

v6.7.9.1 behavior:
This line contains only one time the word apple, on line 2.
This line contains the word apple two times, so one more apple in this line with line number 4.
This line contains the word apple two times, so one more apple in this line with line number 4.

**Comment by rhermsen** [comment]
(also described here: https://notepad-plus-plus.org/community/topic/10436/containing-line-numbers-from-find-window-not-copied-anymore )

**Comment by jonandr** [comment]
Added options to copy with or without line numbers in #150 / #68, but it was decided that it should always be without numbers by @donho. Maybe this decision needs to be reconsidered.

**Comment by rhermsen** [comment]
Thanks for looking at this.
I do also think the new behavior not to copy the line numbers should be the default.
Thinking of it, what would be nice if you can copy the line numbers only in column-mode, in a WYSIWYG way (e.g. you highlight the line numbers > you will get the line numbers).

But having the line numbers also copied is a helpful feature (that I really miss).
If there was an option to only have one line in the Find results window, I probably just got used to the new behavior. Mostly for https://github.com/notepad-plus-plus/notepad-plus-plus/issues/933 (which I think is a bug), but also getting the line numbers back, I rolled back to v6.7.8.2 for the moment.

A remark regarding the current behavior: while highlighting the text to copy you see also the line numbers becoming highlighted. This also gives the expectation that it will be copied (a bit of WYSIWYG).
If the line numbers don't become highlighted than it will be clear it will not be copied.

**Comment by MetaChuh** [comment]
we are closing this issue due to its age and multiple newer notepad++ versions since it was filed.

please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html).
if your issue persists, and it is still of relevance to you, please feel free to file a new issue.

thank you for your help and best regards.

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
```
[<kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd>](https://notepad-plus-plus.org/community/)
