### ISSUE TITLE
Bug with field of Search Result (minimized window)

### ISSUE THREAD

**Issue by GOLEM777** [notepad-plus-plus/notepad-plus-plus#9341]
Problem:
When you open a new copy of NP++, the results window is minimized after searching.

Reproduction:
Open NP++
Open second copy NP++ or more
Open any file in second copy
Find -> Find all in all Opened... any text.

https://user-images.githubusercontent.com/13437340/103466180-bf2db480-4d53-11eb-9746-f91384d4a7b9.mp4

Notepad++ v7.9.2   (64-bit)
Build time : Dec 31 2020 - 04:01:34
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : ON
Local Conf mode : OFF
OS Name : Windows 10 Pro (64-bit) 
OS Version : 2004
OS Build : 19041.685
Current ANSI codepage : 1251
Plugins : ComparePlugin.dll DSpellCheck.dll NavigateTo.dll NppDocShare.dll NppQrCode64.dll NppSaveAsAdmin.dll zoomdisabler_x64.dll _CustomizeToolbar.dll

**Comment by sasumner** [comment]
I was able to reproduce this problem in 7.9.2.  The same test in 7.9.1 reveals it is not a problem there, so it appears to be a regression introduced into 7.9.2.

**Comment by GOLEM777** [comment]
Yes, I know, because it is important for me. ))

**Comment by donho** [comment]
It should be due to https://github.com/notepad-plus-plus/notepad-plus-plus/commit/7399257f56f6830f2952ea7a3a2a8733fb84df0e
