### ISSUE TITLE
Feature Request: Remember installation location

### ISSUE THREAD

**Issue by RockyMtnVideo** [notepad-plus-plus/notepad-plus-plus#9346]
### Description of the Issue
I try to install most software on the my D: drives, and most of them remember that, and (during updates) populate their "suggested" install directory with where the software was previously installed.  Put simply, NP++ doesn't do that, and always points to C:.  It is admittedly a "nit" problem, but I try to stay current with the releases, and (hence) install a lot of them, and if I am distracted, I occasionally dump them in the wrong place, and then have to undo-redo all of that.  As I use my own shortcut to execute NP++, that ends up being pointed to the older version (on D:), if I do forget to change it, which is also not ideal.

Anyway... I realize this might be WAY down on the "to do" list, but it would be "more convenient" if it adhered to that construct (which I do see in most of the other packages that I install).

### Steps to Reproduce the Issue
Just install it on another drive, and then do a subsequent install, which I would expect it to offer up the C: drive as the target.

### Expected Behavior
That the installer would query the OS to determine its current install drive/directory.

### Actual Behavior
It always tries to install to the standard 32/64-bit locations on C:

### Debug Information
I guess, if you tell me that it is already supposed to be doing this, then I'll gladly provide you with whatever you request.

Thanks for your time, and thanks for such a fantastic tool.

**Comment by pryrt** [comment]
Does  #11013 (9f08013d0811d8537628be0880f4bbb3f9eab9c7) close this issue as well?

**Comment by RockyMtnVideo** [comment]
When I downloaded that beta, and reviewed the changes, I was tickled to see it as one of the updates. And “yes”, it does work as intended. THANKS for that fix!

**Comment by pryrt** [comment]
closed by #1013 (9f08013)
