### ISSUE TITLE
Notepad++ crashes while searching a word recursively in a large directory. Loss of auto-saved open documents

### ISSUE THREAD

**Issue by dz15mlru** [notepad-plus-plus/notepad-plus-plus#9352]
My Notepad++ is set to continue each time the last working session.
I had some 150+ up to 200 open tabs in Notepad++. Many of them open for years.

Today searching recursively a in a large Wordpress installation caused Notepad++ to hang, crash and lose (destroy) most of auto-saved (unsaved) open documents. It managed to keep them for months and years, and now after this crash, all these open unsaved documents are gone!

The Session.xml it’s ok. Just the unsaved files from <%APPDATA%\Notepad++\backup> are lost, almost all of them.

Using immediately softwares like Recuva and Disk Drill to restore the lost files, was unsuccessful, only a few files there recovered from almost 200!

Is there any chance to recover the lost auto-saved documents? Or they are gone forever?

Some ~100 files (auto-saved) disappeared completely from the backup folder. 
While crashing, Notepad++ suggested that 'it will try to save the open documents, but there will be data loss', it generated some dump, I saw on screen all files open in Notepad++ being quickly renamed with .dmp extension.

The issue occured while searching in a ~5 GB directory with 3900 sub-folders and 23k files. 

Notepad++ v7.9.1   (32-bit)
Build time : Nov  2 2020 - 01:03:56
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : ON
Local Conf mode : OFF
OS Name : Windows 7 Ultimate (32-bit) 
OS Build : 7601.24263
Current ANSI codepage : 1251
Plugins : DSpellCheck.dll mimeTools.dll NppConverter.dll NppExport.dll

**Comment by sasumner** [comment]
>Latest Notepad++ version.

is...meaningless. 

The issue template (that you deleted out) is the proper way to file a bug report.
To be fair, you have a lot of good info in what you did submit.
Can you provide the "Debug Info" that was requested by the template?

**Comment by dz15mlru** [comment]
Updated post with Debug Info.

**Comment by dz15mlru** [comment]
Is there a way to recover those lost unsaved files of the backup folder?

**Comment by Suesskirsche** [comment]
Having started my IT experience way back in the 1970's with CP/M when computers usually hung up every half an hour or so has taught me one thing: Save a file latest after you have written the first word and then repeatedly after every other line. That keeps data loss to a minimum and has helped me in various situations where programs, disks, or operating systems caused trouble.

Working as backup operator has additionally taught me: No backup? No mercy! 

Why do you believe that Notepad++ is causing the trouble and not the disk, the filesystem, or Windows?

I know that this comment doesn't help the poor guy having data loss. But maybe help others NOT to rely on automatisms under all circumstances. If data is important, then take care of it! If you don't... well, then it's not important and the loss should be no tragedy, but only annoying.


Am 4. Januar 2021 15:06:49 MEZ schrieb dz15mlru <notifications@github.com>:

**Comment by alankilborn** [comment]
>Save a file latest after you have written the first word and then repeatedly after every other line. That keeps data loss to a minimum and has helped me in various situations where programs, disks, or operating systems caused trouble.

>Working as backup operator has additionally taught me: No backup? No mercy!

>If data is important, then take care of it! If you don't... well, then it's not important and the loss should be no tragedy, but only annoying.

There are wise words here, but perhaps only because I am from the same era.
People will argue: "Computers should not lose my data" and they are right.
But it reminds me of what my father told me when I was learning to drive an automobile:
"Always be prepared for someone to ignore the red/stop light and come through the intersection"
I would say "But it would be wrong for them to do that!"
My father would say "You are right, but you don't want to be 'dead right'"
The lesson: Protect your data.  You care most about it.

**Comment by zanud** [comment]
@Suesskirsche, @alankilborn
If a program destroys autosaved files due to errors in a corresponding part of its code, why do you think it can not contain errors in part of code responsible for a regular "Save"?

**Comment by dz15mlru** [comment]
@Suesskirsche
> Why do you believe that Notepad++ is causing the trouble and not the disk, the filesystem, or Windows? 

This crash was controlled by Notepad++. In fact there were a few interesing popups of N++ during the crash, informing me about what happens and to what I should prepare (I will lose data). The program was alive till the end, and it probably could save or at least not touch the saved backups, but for some reason, with this crash N++ burried alive some 150 backups... 
Originally the N++ just hanged at some point while working on this task, it stopped responding, and a bit later it was clear that it's point of no return.


I have had in past even unexpected N++ endings by power outages and machine failures (!), and the backups usually were ok even after such situations. But now, in a program-controlled crash, N++ somehow managed to destroy 90% of the backups and even kindly informed me about this (decision?), LOL. 

Most of these unsaved files were some type of notices, a few credentials, and many _to-do_s, and this is why I didn't saved them, relying on these wonderfull autosaves... 
This is not really a tragedy, but to be honest I am sad enough to lose instantly all this data, before I decide to wipe it myself...

**Comment by dz15mlru** [comment]
So I found the generated backups dumps ~~AppData\Local\Temp\N++RECOV~~. Finally recovered them.
