### ISSUE TITLE
Bug with -at least- one theme

### ISSUE THREAD

**Issue by coduh** [notepad-plus-plus/notepad-plus-plus#9353]
### Description of the Issue

Hi, v7.9.2 here, but I'm pretty sure this existed for a long time. The theme called _Bespin_ is my favorite, but it always behaved weirdly when I tried to edit it. I think I finally found why!

By the way, can you please change the default Inactive Tab colors? It has too little contrast for my eyes, very hard to read grey text on grey background..

### Steps to Reproduce the Issue

1. Choose _Bespin_ from _Style Configurator_
2. Try to edit _Inactive Tab_ colors (it doesn't even show in the menu, i always have to edit the .xml file)
3. Close and open the application, it's reverted to default!

### Possible Cause
I inspected `<GlobalStyles>` in **%AppData%\Roaming\Notepad++\themes\Bespin.xml** and noticed it had a duplicate entry for `<WidgetStyle name="Find Mark Style" styleID="31" ... `, I removed the first occurence and looks like it works now.

(If anyone is interested, I updated Inactive Tabs with `fgColor="2A211C" bgColor="BDAE9D"` uses theme colors and looks nice)

Did not check this file for any other duplicates, or any other files.. Wanted to let you know.

Thanks for everything!

**Comment by Docteh** [comment]
I think I've found the underlying cause, only the first 30 `WidgetStyle` entries in the xml show up in the UI

as a test I removed Mark Style 4 and 5 from my Bespin.xml and now both the `Inactivetabs` and `URL hovered` show up

```
$ grep -e WidgetStyle themes/*.xml   | cut -d : -f 1  | uniq -c | sort -n
     30 themes/Deep Black.xml
     30 themes/Hello Kitty.xml
     30 themes/HotFudgeSundae.xml
     30 themes/khaki.xml
     30 themes/MossyLawn.xml
     30 themes/Navajo.xml
     30 themes/Obsidian.xml
     30 themes/Solarized.xml
     30 themes/Solarized-light.xml
     30 themes/Zenburn.xml
     31 themes/DansLeRuSH-Dark.xml
     31 themes/DarkModeDefault.xml
     32 themes/Bespin.xml
     32 themes/Black board.xml
     32 themes/Choco.xml
     32 themes/Mono Industrial.xml
     32 themes/Monokai.xml
     32 themes/Plastic Code Wrap.xml
     32 themes/Ruby Blue.xml
     32 themes/Twilight.xml
     32 themes/Vibrant Ink.xml
     33 themes/vim Dark Blue.xml

```
I still have both `Find Mark Style` entries.
![image](https://user-images.githubusercontent.com/190571/134802397-c7077aa5-d609-48af-9c6e-344cb96c7aac.png)

**Comment by ozone10** [comment]
Should be fixed.

**Comment by ArkadiuszMichalski** [comment]
Fixed by https://github.com/notepad-plus-plus/notepad-plus-plus/commit/e45c1fc3222b2fe173360f54b02550152cb2cf90.
