### ISSUE TITLE
$(CURRENT_WORD) proplems  with & and +

### ISSUE THREAD

**Issue by drmusti** [notepad-plus-plus/notepad-plus-plus#9359]
example:
word1&word2
word1+word2
 <Command name="Google Search" Ctrl="no" Alt="yes" Shift="no" Key="113">http://www.google.com/search?q=$(CURRENT_WORD)</Command>
google search proplem....

example:
word1
word2
				<Command name="Google Translate" Ctrl="no" Alt="yes" Shift="no" Key="113">https://translate.google.com/?sl=auto&tl=tr&op=translate&text=$(CURRENT_WORD)</Command>

new line proplem.

Sincerely

**Comment by sasumner** [comment]
Can't tell what the issue here is.
If @drmusti can restate in a clear manner, will consider reopening.

**Comment by drmusti** [comment]
example: google search    content + or &    proplem result..
![Screenshot_3](https://user-images.githubusercontent.com/33732633/103770518-2e96f300-5037-11eb-8497-4b4c83893409.png)

example: google translate a text  result proplem.  because no line break.
![Screenshot_4](https://user-images.githubusercontent.com/33732633/103770662-70279e00-5037-11eb-9007-fbfd0dbe29e2.png)
Sincerely

**Comment by sasumner** [comment]
So this goes beyond what it is meant for the _Run_ > _Run..._ box to be able to perform with `$(CURRENT_WORD)`.

It is best-handled by a scripting plugin, e.g. Pythonscript; here's a sample script that can handle `word1+word2` if the script is run when that text has been selected:

```
from Npp import editor
import ctypes

search_term = editor.getSelText()
if len(search_term) > 0:
    search_terms_list = search_term.split('+')
    search_term_string_for_uri = '+AND+'.join(search_terms_list)
    uri_text = 'https://www.google.com/search?&q=' + search_term_string_for_uri
    SW_SHOW = 5
    ctypes.windll.Shell32.ShellExecuteA(None, 'open', uri_text, None, None, SW_SHOW)
```

The above shows an "and" search but the "or" search could easily be supported as well.
Probably the translation case is easily handled as well, but I didn't look into that.

**Comment by drmusti** [comment]
i fixed "x+t    x&y" Google Search Engine Proplem with  urlprotocol  . 

but i cant  find a solution for Google Translate Engine.
because no content <crlf > <br> etc chracter  at $(CURRENT_WORD)
example:
red
apple
get result   "redapple"    
if get result  "red<crlf>apple" ... etc   no proplem...
and sorry for my bad english.
Sincerely

**Comment by sasumner** [comment]
>i fixed "x+t x&y" Google Search Engine Proplem with urlprotocol .

No idea what this means.
If you found a solution without scripting, why don't you post the exact solution?

>but i cant find a solution for Google Translate Engine.
because no content {crlf} {br} {\n} {\r} etc chracter at $(CURRENT_WORD)
example:
red
apple
get result "redapple"
if get result "red{crlf}apple" ... etc no proplem...

And I've no idea what this is saying either.

>and sorry for my bad english.

Well, if you can't express yourself clearly, you can be sorry, but you aren't going to get good help.
Other non-English speakers use translation tools before posting.
You clearly know about those, so...

**Comment by drmusti** [comment]
i used auto it url protocol script. this solution.

`$arg=$CmdLineRaw
$arg=$arg
$arg = StringReplace($arg, "npp2gg://", "")
$arg = StringReplace($arg, "/", "")
$arg = StringReplace($arg, "%", "%25")
$arg = StringReplace($arg, "+", "%2B")
$arg = StringReplace($arg, "&", "%26")
ShellExecute("https://www.google.com/search?q="&$arg&"")`

but i cant use  for Google Translate.
because  get text  no  line break chracter.

example i selectet that....
"red
apple"
select text result  "redapple"

Sincerely

**Comment by sasumner** [comment]
>but i cant use for Google Translate. because get text no line break chracter.

True, perhaps move to something like Pythonscript where there is more power.

**Comment by drmusti** [comment]
I dont know it. so i can't.   thank you so much for your time.
Sibcerely
