### ISSUE TITLE
custom toolbar buttons with custom icons and custom commands.

### ISSUE THREAD

**Issue by drmusti** [notepad-plus-plus/notepad-plus-plus#9360]
custom toolbar buttons with custom icons and custom commands.
example

title:Google Search 
icon:/google.png
cmd:http://www.google.com/search?q=$(CURRENT_WORD)

Sincerely...

**Comment by ArkadiuszMichalski** [comment]
You can do this by Customize Toolbar plugin:
https://sourceforge.net/projects/npp-customize/

**Comment by chcg** [comment]
Plugin is also available via N++ builtin PluginAdmin.
