### ISSUE TITLE
if no selection disabled custom menu item

### ISSUE THREAD

**Issue by drmusti** [notepad-plus-plus/notepad-plus-plus#9361]
if no selection disabled custom menu item
![Screenshot_2](https://user-images.githubusercontent.com/33732633/103762901-1c628800-502a-11eb-9b15-6fa4c774f2e4.png)
Sincerely

**Comment by sasumner** [comment]
"Google Search" is not part of the default context menu:

![image](https://user-images.githubusercontent.com/30118311/103768072-ccff6600-4fef-11eb-97ce-c67078679218.png)

Therefore, it isn't "reasonable" for Notepad++ to know that it requires a selection to act upon.
