### ISSUE TITLE
A Project panel is too narrow in a second instance of Notepad++

### ISSUE THREAD

**Issue by zanud** [notepad-plus-plus/notepad-plus-plus#9363]
### Description of the Issue
When I open a second (third, fourth) instance of Notepad++ (for example, by click on the "Open in New Instance" tab menu item), and open a Project panel in that new instance then this panel is almost unnoticeable because it is only a few pixels wide.

### Steps to Reproduce the Issue
1. Open any document. (Optionally, click on "View" -> "Project panels" -> "Project Panel 1".)
2. Click on the "Open in New Instance" tab menu item.
3. In the new instance click on "View" -> "Project panels" -> "Project Panel 1".
4. Try to find the Project panel.

### Expected Behavior
The Project panel in the second instance should have the same width as in the first one.

### Actual Behavior
The Project panel in the second instance is only a few pixels wide as screenshots below demonstrate:

The first instance:
![instance1](https://user-images.githubusercontent.com/76625744/103799746-2dc08a00-5054-11eb-8f7e-51cd32a81bb5.png)
The second instance before the Project panel opening:
![instance2-projects](https://user-images.githubusercontent.com/76625744/103799891-5fd1ec00-5054-11eb-89e5-c9c38e0a8caa.png)
The second instance with the Project panel opened:
![instance2+projects](https://user-images.githubusercontent.com/76625744/103799843-4e88df80-5054-11eb-983b-d8748238b418.png)

Note a thin gap between a left window border and a left tab border on the last screenshot: this is not the gap, but the Project panel! And it can be expanded by mouse to a normal width! 

### Debug Information
Notepad++ v7.9.2   (32-bit)
Build time : Dec 31 2020 - 03:58:36
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS Name : Microsoft Windows XP (32-bit) 
OS Build : 2600.0
Current ANSI codepage : 1251
Plugins : none

**Comment by GOLEM777** [comment]
A similar problem
[9341](https://github.com/notepad-plus-plus/notepad-plus-plus/issues/9341)

**Comment by zanud** [comment]
@GOLEM777
I also think that it is the same problem (regression). At least, right now I tried a portable version 7.9.1, and it opens the Project panel correctly.

**Comment by mere-human** [comment]
I saw a similar problem but in scope of Folder as Workspace usage with multi-instance in scope of this PR #9286
