### ISSUE TITLE
Close tab via keyboard

### ISSUE THREAD

**Issue by toosten** [notepad-plus-plus/notepad-plus-plus#9365]
I would like to be able to close tabs in Windows using the keyboard (CTRL + F4).

This is a standard in the Windows world and is very useful for working quickly without a mouse.

Thank you.

**Comment by Schleifenkratzer** [comment]
i am pretty sure you mean alt + F4 
![Anmerkung 2021-01-07 115848](https://user-images.githubusercontent.com/22558578/103885103-cfd98400-50df-11eb-846d-1afe68a55531.jpg)(https://www.computerhope.com/jargon/c/ctrl-f4.htm)

**Comment by sasumner** [comment]
@Schleifenkratzer 
No, @toosten did indeed mean Ctrl+F4

@toosten Use the _Settings_ menu > _Shortcut mapper..._ > to assign your desired keycombinaton to the _Close_ function.
