### ISSUE TITLE
[Feature Request] Clear Directories In Find In Files

### ISSUE THREAD

**Issue by atherworld** [notepad-plus-plus/notepad-plus-plus#9366]
I'd likr a way to clear the directory listing in Find In Files.  I have a few I no longer need to search in (one directory has been deleted), and I'd like to see a way to delete individual directories in the pull down menu. Don't need a clear all, as some I still use.

**Comment by sasumner** [comment]
It is a reasonable request.
Before it is implemented, however, you can remove what you need to manually, when Notepad++ is NOT running, by editing `config.xml` and removing the desired `<Path>` subnodes from the `<FindHistory>` node.

**Comment by atherworld** [comment]
Removed them from the drop down list, but the main directory bar still has a deleted directory, Internet. And defaults to it instead of the last searched in directory. So every time I go to Find In Files, it defaults back to Internet.
![UNTITLED1](https://user-images.githubusercontent.com/56777784/103965952-af2b2180-5113-11eb-8daa-eb467ec3a5da.jpg)

**Comment by atherworld** [comment]
OH, OK. That'll help.

**Comment by mere-human** [comment]
I thought about that too. This feature would be nice to have.
At first, I hoped that _File > Empty Recent Files_ List would clear the list in _Find in Files_ as well, but no.

**Comment by allanwmacdonald** [comment]
This is still a problem - if there are unwanted entries in the list, it is too easy to select them when using the Find in Files feature and you end up editing the wrong file.

I need to be able to delete entries in the existing list that appears in the pulldown menu.

**Comment by alankilborn** [comment]
>I need to be able to delete entries in the existing list that appears in the pulldown menu.

If you have version >= 7.9.3, you can do this.  Drop the dropdown, caret to what you want to delete, press the Delete key.

**Comment by allanwmacdonald** [comment]
@alankilborn
Not working in V8.3.3 32bit (Win10-64)

**Comment by alankilborn** [comment]
> Not working in V8.3.3 32bit (Win10-64)

Works for me, in:

Notepad++ v8.3.3   (32-bit)
Build time : Mar 13 2022 - 17:11:10
Path : C:\...\Releases\npp.8.3.3\npp.8.3.3.portable\notepad++.exe
Command Line : -multiInst
Admin mode : OFF
Local Conf mode : ON
Cloud Config : OFF
OS Name : Windows 10 Enterprise (64-bit) 
OS Version : 2009
OS Build : 19042.1586
Current ANSI codepage : 1252
Plugins : mimeTools.dll NppConverter.dll NppExport.dll

**Comment by allanwmacdonald** [comment]
What I do:
1. Highlight a word in a text file
2. ctrl-shift-f
3. click on directory
4. type in a garbage string for the directory, such as "aaaaaaaa"
5. click Find All
6. Nothing happens (ok, I expected that)
8. click on down-arrow besides Directory edit box to show list.
9. aaaaaaaa appears in list among other items
10. delete the entry and the entry field becomes blank
11. Select another item in the directory list (a valid one) and click Find All
12. Results appear and dialog closes.  OK that's good.
13. Now highlight a word again and ctrl-shift-f
14. Pull down the directory list
15. aaaaaaaa appears.
16. Select aaaaaaaa and delete - it deletes from the entry field.
17. enter some other string.
18. Find All
19. dialog closes.
20. ctrl-shift-f again
21. pull down directory list
22. "aaaaaaaa" is still there.
I can't get rid of the entry "aaaaaaaa".

Yes I can delete the contents of the edit box but I can't delete the entries in the pulldown list!  They seem to be there forever.  That is the problem.

**Comment by allanwmacdonald** [comment]
Hey, I figured out what I was doing wrong!

When clicking on the list and moving the mouse pointer to the entry I wanted to remove, I was clicking on it before pressing the delete button.  (Notice in step 15 of my list of actions: I used the word "select" - that meant "click"!).

Instead, I was supposed to just hover the mouse pointer over the selection but NOT click on it!  If I press the delete key then, the entry is removed.

I think the reason I  had trouble with this is because executing a keyboard action while an item is highted by a mouse hover was not intuitive for me.  I only ever believed that the mouse hover highight prepares the item to be clicked by the mouse.  I never imagined that the keyboard delete button would work while the mouse hovered over the item.  I had to read and re-read your instructions and try to figure out what the extra or missing step was.

**Comment by allanwmacdonald** [comment]
I also found that if I scroll down the list using the keyboard arrow keys, and press delete, the entry is removed.  That is more intutitive but I never tried that way before.

I wonder if, in the future, a right-click option to remove the item might help dummies like me.  Anyway, at least I know what to do now!

Thanks for the help!

**Comment by alankilborn** [comment]
Ha. Nice solve!

For me, when trying to repro it, I was not so "mouse-centric".  I wasn't entirely "keyboard-centric" either -- I would "drop" the combobox with the mouse (also possible to do on the keyboard with Alt+downarrow), then use the arrow keys to head down to the `aaaaaaaa` entry, and finally press Delete.
