### ISSUE TITLE
Avoid bringing up "Are you sure?" Prompt when running a macro for multiple "Replace in Files" command

### ISSUE THREAD

**Issue by ZohaibIrfan** [notepad-plus-plus/notepad-plus-plus#9367]
I set up a macro where I have multiple Replace in Files command run through a set of files. I have over thousands of files to process this way and it takes time going through each command. I want to bypass the "Are you sure?" prompt when I run this macro, as the macro couldn't record those confirmation boxes. Because of the prompt, the macro stops each time another prompt comes up using "Replace in Files". It becomes tedious when dealing with a lot of files that takes time to process through, so you couldn't tell when it would exactly finish and run the next command.

### **Steps to Reproduce the Issue**
1. Start Macro Recording.
2. Open the find dialog box (Ctrl + F or Ctrl + H).
3. Head to "Find in Files" tab.
4. Specify the find and replace fields as well as the file type and directory.
5. Click on "Replace in Files".
6. Press yes on prompt.
7. Repeat steps 4 and 5 until all criteria are met.
8. Save Macro recording
9. Run macro for next set of files.

### Expected Behavior
The Macro should find the values and replace them in each iteration without a prompt.

### Actual Behavior
When running the macro, it gives prompt each time "Replace in Files" is used.

### Debug Information
Notepad++ v7.9.1   (64-bit)
Build time : Nov  2 2020 - 01:07:46
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS Name : Windows 10 Home (64-bit) 
OS Version : 2004
OS Build : 19041.685
Current ANSI codepage : 1252
Plugins : DSpellCheck.dll mimeTools.dll NppConverter.dll NppExport.dll

**Comment by sasumner** [comment]
Somewhat related: https://community.notepad-plus-plus.org/topic/19642/unwanted-multiple-confirmations-for-replace-in-all-files

**Comment by sasumner** [comment]
Recently I attempted to introduce a change into Notepad++ that would add the ability to enable/disable confirmations for the following situations:

* Replace in opened docs - interactive use
* Replace in opened docs - macro use
* Replace in files - interactive use
* Replace in files - macro use

The Notepad++ author declined to accept that, and would only accept a single enable/disable option that combined the functionality of the first two.  It is currently present in _Settings_ menu > _Preferences..._ > _Searching_ > _Confirm Replace All in All Opened Documents_

**Comment by ZohaibIrfan** [comment]
> Recently I attempted to introduce a change into Notepad++ that would add the ability to enable/disable confirmations for the following situations:
> 
> * Replace in opened docs - interactive use
> * Replace in opened docs - macro use
> * Replace in files - interactive use
> * Replace in files - macro use
> 
> The Notepad++ author declined to accept that, and would only accept a single enable/disable option that combined the functionality of the first two. It is currently present in _Settings_ menu > _Preferences..._ > _Searching_ > _Confirm Replace All in All Opened Documents_

I see. I did notice this option in the settings. But idk if my computer would handle over thousand opened files when running the macro this way. Each file is about 10mb average.

**Comment by sasumner** [comment]
>I did notice this option (_Confirm Replace All in All Opened Documents_) in the settings. But idk if my computer would handle over thousand opened files when running the macro this way. Each file is about 10mb average.

Probably not.  :-(
