### ISSUE TITLE
Session SaveAs dialog checkbox is not translatable

### ISSUE THREAD

**Issue by sasumner** [notepad-plus-plus/notepad-plus-plus#9375]
### Description of the Issue
Post-integration of PR #9286 , I noticed that the text _Save Folder as Workspace_ checkbox is not language translatable, i.e., it always appears in English no matter which non-English _Localization_ is set in the _Preferences..._

### Steps to Reproduce the Issue

1. Execute _File_ > _Save Session..._
2. Observe screenshot below

### Expected Behavior
Text to be translated per localization.

### Actual Behavior
Text always appears in English, like this:
![image](https://user-images.githubusercontent.com/30118311/104075043-af90ee80-51df-11eb-999e-34570dfcaee3.png)

### Debug Information
Notepad++ source after this commit: https://github.com/notepad-plus-plus/notepad-plus-plus/commit/b9f498f0412bc1806ee238627b6099d26e76e9cf

**Comment by sasumner** [comment]
@mere-human Would you like this one?

**Comment by mere-human** [comment]
Yes, I would like to work on this as well.
