### ISSUE TITLE
Incompatible plugin is not deleted when asked for in the warning message

### ISSUE THREAD

**Issue by vlakoff** [notepad-plus-plus/notepad-plus-plus#9377]
### Description of the Issue
Trying out an old ANSI plugin, when starting Notepad++ a warning message is displayed. This message says the plugin is incompatible, and offers to delete it. However, when choosing to delete the plugin, it is not deleted actually. I also tried by running Notepad++ as an administrator, the issue also occurs.

### Steps to Reproduce the Issue
1. Download an old ANSI plugin, for instance ConvertExt, here: http://notepad-plus.sourceforge.net/commun/pluginsBin/ConvertExt_v11RC1.zip
2. Manually install the DLL, e.g. to `C:\Program Files (x86)\Notepad++\plugins\ConvertExt\ConvertExt.dll`
3. Start Notepad++. The following warning message should be displayed:

![plugin incompatibility warning message](https://user-images.githubusercontent.com/544424/104090903-28dd1f80-527a-11eb-9141-eeae20322600.png)

### Expected Behavior
When clicking on "Yes", the plugin should be deleted (or maybe, rather just moved outside the plugin folder).

### Actual Behavior
When clicking on "Yes", the plugin isn't deleted actually. Thus, the warning message continues to appear at subsequent Notepad++ launches.

### Debug Information
Notepad++ v7.8.9   (32-bit)
Build time : Jul 15 2020 - 20:26:50
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS Name : Windows 10 Enterprise (64-bit) 
OS Version : 2004
OS Build : 19041.685
Current ANSI codepage : 1252
Plugins : LightExplorer.dll NppFTP.dll

**Comment by chcg** [comment]
Issue could be reproduced.
https://github.com/notepad-plus-plus/notepad-plus-plus/blob/8c1e15377fec12133374fffde9f775484c798e6e/PowerEditor/src/MISC/PluginsManager/PluginsManager.cpp#L278 is called with the correct filename, but the dll seems to be still loaded and therefore can't be deleted.

By adding `::FreeLibrary(pi->_hLib);` before `::DeleteFile(pluginFilePath);` is correcting this.
