### ISSUE TITLE
Wrong locale displayed when selecting zh-cn

### ISSUE THREAD

**Issue by mraandtux** [notepad-plus-plus/notepad-plus-plus#9390]
### Description of the Issue
wrong locale displayed (en) when selecting zh-cn

### Steps to Reproduce the Issue

1. Go to "Settings"
2. Select "Preferences"
3. Choose locale to "Chinese (Simplified)" (chineseSimplified.xml on the "localization" folder)

### Expected Behaviour

Correct Chinese (Simplified) locale appears as previous versions up to 7.9.1

### Actual Behaviour

Locale displays as English (see pic below) , other Traditional Chinese locales (zh-hk, zh-tw) appears correctly

### Debug Information

Notepad++ v7.9.2   (64-bit)
Build time : Dec 31 2020 - 04:01:34
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS Name : Windows 10 Enterprise (64-bit) 
OS Version : 1909
OS Build : 18363.1316
Current ANSI codepage : 936
Plugins : DSpellCheck.dll mimeTools.dll NppConverter.dll NppExport.dll 

![屏幕截图 2021-01-14 193259](https://user-images.githubusercontent.com/2002796/104585677-59b8bc80-569f-11eb-965f-5a4d7df81754.jpg)

By the way - keep up the good work and spirit, Don!

**Comment by sasumner** [comment]
I believe this has already been fixed, here: https://github.com/notepad-plus-plus/notepad-plus-plus/commit/3373756afbeb66cea8be36087538aab12a171491

**Comment by mraandtux** [comment]
> I believe this has already been fixed...

Whoops! Didn't find out this is a duplicate of #9329 at first.
