### ISSUE TITLE
Feature Request:  pasteboard function

### ISSUE THREAD

**Issue by whytte** [notepad-plus-plus/notepad-plus-plus#9398]
Feature Request:  pasteboard function
Please move this post to the related request area if this is the wrong spot

### Description of the Issue
keep the notepad-plus-plus open in task bar
whatever copied from web searches past onto a single text file

### Steps to Reproduce the Issue

1. 
2. 
3.

**Comment by sasumner** [comment]
Notepad++ already has a _Clipboard History_ feature, see _Edit_ menu.
Perhaps extending that feature to allow a bunch of individual clips to be pasted at once is a better approach than that described above.

[Referencing behavior current to N++ 7.9.2.]

**Comment by donho** [comment]
> Notepad++ already has a Clipboard History feature, see Edit menu.

So I think this issue can be closed.

**Comment by alankilborn** [comment]
This request is different from the _Clipboard History_ feature.
It is very much like the request in the discussion here: https://community.notepad-plus-plus.org/topic/11965/automatic-clipboard-paste

**Comment by kwhytte** [comment]
I do not agree with closing this request
[Kimberley Whytte](https://community.notepad-plus-plus.org/user/kimberley-whytte) [about 6 hours ago](https://community.notepad-plus-plus.org/post/88055)
Auto paste the selected text automatically into One File

Dear friends,

I have requested a feature few years ago and lots of excuses given not to implemented whereas many other plugins are given go ahead to be created

What I’d like to do is:
-open new file:
-keep it open
-copy text from different sources including web pages
-they go pasted automatically into one that specific file
-not as each copied part entered as a separate file
Example:
https://www.notetab.com/
-top menu
-document
-use as pasteboard ( ticked)

Earlier reason not to implement it was Notepad++ is not a clipboard program

by the same token, I can say Notepad++ is not a "such as such program to do so (backward & lazy excuse)

please DO Stop providing excuses

I’d like to see that function which will be a win-win situation for you as a developer and for us as a user with an important function

I appreciate very much if you could implement it directly or ask plugin creators to start developing one to be included within the notepad++

all the best

https://community.notepad-plus-plus.org/topic/24732/auto-paste-the-selected-text-automatically-into-one-file
