### ISSUE TITLE
Replace in selection doesn't work with column mode selection

### ISSUE THREAD

**Issue by crayxt** [notepad-plus-plus/notepad-plus-plus#94]
After I select a rectangular block of text while pressing Alt key, I wanted to replace some text with another in selected area, but it turns out, the checkbox "In selection" in the Replace (Ctrl+H) window is not active in this case. While selecting in regular mode, it works just fine.
Could it please be fixed?

Thanks,

**Comment by crayxt** [comment]
Ok, I see in https://github.com/donho/notepad-plus-plus/blob/master/PowerEditor/src/ScitillaComponent/FindReplaceDlg.cpp

```
				// Searching/replacing in column selection is not allowed 
				if ((*_ppEditView)->execute(SCI_GETSELECTIONMODE) == SC_SEL_RECTANGLE)
				{
					checkVal = BST_UNCHECKED;
					_options._isInSelection = false;
					nbSelected = 0;
				}
				::EnableWindow(::GetDlgItem(_hSelf, IDC_IN_SELECTION_CHECK), nbSelected);
```

Any reason to do that?

**Comment by h-h-h-h** [comment]
:+1:

**Comment by crayxt** [comment]
Close
