### ISSUE TITLE
Provide a key combination to see all entries in the Find History

### ISSUE THREAD

**Issue by fml2** [notepad-plus-plus/notepad-plus-plus#9404]
This is not en error, just a convenience related request.

### Description of the Issue
I like to use the keyboad as much as possible. When in the Find dialog, I often times want to display all the history entries to be able to quicly select the on I need. As of now, I have to do a mouse click on the "arrow down" near the input field. It would be cool if there were a key for this.

In other applications, `Ctrl+Down` is often used for that, but I don't think there is a "standard" for this.

While on it, the functionality could be added on other history dropdowns as well.

**Comment by sasumner** [comment]
>I don't think there is a "standard" for this.

The standard is _Alt_+_Down_ and indeed it works currently (7.9.2) in Notepad++.
All dropdowns in N++ have this functionality.
BTW, _Alt_+_Up_ closes up a dropped box.
