### ISSUE TITLE
The find dialog is not displayed when selecting from menu or via Ctrl+F

### ISSUE THREAD

**Issue by lnesnidal** [notepad-plus-plus/notepad-plus-plus#9410]
### Description of the Issue
It could be that I accidentally selected full transparency always. Not when I selecting Find from menu or by Ctrl+F the dialog does not show! I believe the setting for transparency is unfortunately located in same dialog. Once selected full transparency there is no way to set it back. 
 
### Steps to Reproduce the Issue

1. I cannot reproduce as I cannot revert the setting for full transparency of the find dialog.
2. 
3. 

### Expected Behavior

Move the find transparency settings into application preferences dialog.

### Actual Behavior

I believe I accidentally set full transparency of the dialog in same dialog somehow. Now I cannot invoke find dialog or revert the settings.

**Comment by lnesnidal** [comment]
As a workaround this issue I have to find config.xml and override the settings "dlgAlwaysVisible="yes" transparencyMode="1" transparency="0" using build in windows notepad.exe.
This resolved my issue with Find dialog not displaying. Still believe that putting transparency setting in same dialog is unacceptable UI design.

**Comment by dail8859** [comment]
Even setting full transparency, the dialog is barely visible. It could be the Find dialog is off the screen. If you press Ctrl+F twice it will re-center the dialog.

**Comment by lnesnidal** [comment]
> Even setting full transparency, the dialog is barely visible. It could be the Find dialog is off the screen. If you press Ctrl+F twice it will re-center the dialog.

No, I just replicate the same. The transparency checkbox was checked and  I check "always" (before I click this accidentally) and after the FIND dialog disappeared and cannot be displayed again (CTRL+F does not help).

**Comment by sasumner** [comment]
@lnesnidal 

Why didn't you provide the requested *Debug Information* ?

**Comment by lnesnidal** [comment]
> @lnesnidal
> 
> Why didn't you provide the requested _Debug Information_ ?

Sorry, I did not know there is menu for that:

Notepad++ v7.9.2   (64-bit)
Build time : Dec 31 2020 - 04:01:34
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS Name : Windows 7 Professional (64-bit) 
OS Build : 7601.24562
Current ANSI codepage : 1252
Plugins : DSpellCheck.dll MarkdownViewerPlusPlus.dll mimeTools.dll NppConverter.dll nppcrypt.dll NppExport.dll NPPJSONViewer.dll NppSaveAsAdmin.dll PreviewHTML.dll PythonScript.dll XMLTools.dll

**Comment by alankilborn** [comment]
See also #8388
