### ISSUE TITLE
Guidelines for supporting legacy systems.

### ISSUE THREAD

**Issue by ArkadiuszMichalski** [notepad-plus-plus/notepad-plus-plus#9423]
@donho 
There should be some official information about supporting for older systems. My point is whether the support for eg WinXP or Win7 has been completely abandoned, or is it still supported, for example, if the corrections do not require a lot of additional code.
This is important when responding to bugs, because some people report them from the older systems, and sometimes this bugs do not appear in the current Win10. What then, bugs should be closed?

If support for a given system has been completely dropped, you can add a short note as to which last version of NPP supported the given system. This information would then be good as ref links for future bugs. This can be given at https://github.com/notepad-plus-plus/notepad-plus-plus/blob/master/CONTRIBUTING.md or in a separate subpage.

**Comment by mere-human** [comment]
> whether the support for eg WinXP or Win7 has been completely abandoned, or is it still supported, for example,

With these changes, the Windows XP support has officially ended:
45912a3321877bc159ebffebf788dcbcc48c34ea
ca1bcb1ec0bedbb4aad227c369667aef30624618
The app just won't start on that OS.

> add a short note as to which last version of NPP supported the given system

This would be nice to have.

**Comment by donho** [comment]
I just opened a PR for this issue:
https://github.com/notepad-plus-plus/notepad-plus-plus/pull/9443

Not sure my way is clear enough. If not, please suggest your way.
Feel free to reword this PR.
