### ISSUE TITLE
Upgrade Notepad++ License

### ISSUE THREAD

**Issue by donho** [notepad-plus-plus/notepad-plus-plus#9425]
Upgrade Notepad++ License from GPL v2 to GPL v3

More (brief) info about v2 vs v3:
https://stackoverflow.com/questions/41460/what-are-the-differences-between-gpl-v2-and-gpl-v3-licenses

**Comment by donho** [comment]
I'll take in charge of this issue myself.

**Comment by mere-human** [comment]
Is there a particular reason for this change? Or is it more to keep things in order?
I am just curious.

**Comment by donho** [comment]
@mere-human 

An user emailed me for the reason of Notepad++ staying in GPLv2.
After checking the difference, it's interesting on 2 points: **internationalization** & **compatibility** (the 2nd reply of above link) for me. So why not.

**Comment by popcorner** [comment]
@donho The compatibility of this new license is worse than the previous one.
The comparison in that link shows the difference between GPL v2 and v3, but not "GPL v2 or any later version" and "GPL v3 or any later version".
"GPL v2 or any later version" is compatible with both GPL v2 and v3, but "GPL v3 or any later version" is not compatible with GPL v2, so this project can't use GPLv2-licensed code anymore, and those projects with GPL v2 license can't use your code too.

**Comment by mere-human** [comment]
> this project can't use GPLv2-licensed code anymore, and those projects with GPL v2 license can't use your code too

@popcorner  Do you have any particular examples?

**Comment by natewrench** [comment]
> > this project can't use GPLv2-licensed code anymore, and those projects with GPL v2 license can't use your code too
> 
> @popcorner Do you have any particular examples?

Linux kernel

**Comment by rimrul** [comment]
> Linux kernel

That doesn't seem like a particularly good example. Yes, the linux kernel is licensed under GPLv2, but what code would be shared between these two projects?

Much of the kernel code is fairly specific to kernel mode and running on the bare metal, whereas much of Notepad++ code is based on the Windows API and Scintilla. Where do you see a big overlap between these two projects?
