### ISSUE TITLE
[Bug report] Regex bug (feature?)

### ISSUE THREAD

**Issue by TAbdiukov** [notepad-plus-plus/notepad-plus-plus#9428]
### Description of the Issue

Find and replace of regex string that's specified to remove first N characters removes (almost) the whole line

I found this issue while reproducing [this answer](https://superuser.com/a/759765) 

### Steps to Reproduce the Issue

1. Get some multiline text (for example [here](https://www.lipsum.com/), generate 5 paragraphs. Paste the text into Notepad++
2. Go to Find and Replace menu. Which search mode to "Regular Expression" with ". matches newline" UNticked. The bug occurs regardless of the "Wrap around" being ticked and unticked
3. Enter parameters,
```
___Find: ^.{10}
Replace: 
```

### Expected Behavior
Notepad++ removes the first 10 characters given it starts from "^"

### Actual Behavior
Notepad++ removes all the characters within the line except from the last `n MOD 10` chatacters of the string

P.S. Amusingly, the bug does NOT occur if I try to find either:
> ^.{10}**?**

OR

> \n.{10}

(slightly different results but still)

### Debug Information
```
Notepad++ v7.9.2   (32-bit)
Build time : Dec 31 2020 - 03:58:36
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS Name : Microsoft Windows XP (32-bit) 
OS Build : 2600.0
Current ANSI codepage : 1252
Plugins : mimeTools.dll NppConverter.dll NppExport.dll 
```

P.S. In my experience, The bug also occurs on the non virtualised modern 64-bit OS

**Comment by sasumner** [comment]
Let's call it a feature and not a bug.

It happens because, after the first replacement, Notepad++ starts searching again, at the point of replacement.  Because the replacement operation removed the matched text, the new search point is at the start of the line and the regex matches that line again.

The method to do the desired operation is:

Find: `(?-s)^.{10}(.*?)`
Replace: `\1`

which, yes, is a bit more to type and to think about.

**Comment by TAbdiukov** [comment]
@sasumner The bug/feature, however, does not occur if one adds the "?". Are you sure that's really a feature

**Comment by sasumner** [comment]
@TAbdiukov 

>does not occur if one adds the "?" in the end (make it lazy-match)

I get the same result from Notepad++ when doing the replace-with-nothing to a search for `^.{10}` or `^.{10}?` , so I'm not following you.

**Comment by TAbdiukov** [comment]
@sasumner Hmm, I don't seem to be able to reproduce `^.{10}?` (with "?") removing the first 10 characters. I guess I misread the result? Hmm

`\n.{10}` seems to remove the first 10 characters everywhere, except from the first line (unlike `^.{10}` or `^.{10}?`

**Comment by sasumner** [comment]
>`\n.{10}` seems to remove the first 10 characters everywhere, except from the first line

Yes, because the `\n` at the start causes the search to skip past characters 11 and beyond, thus leaving them.
