### ISSUE TITLE
Sugestions of tools for Notepad++

### ISSUE THREAD

**Issue by jhonatan4878** [notepad-plus-plus/notepad-plus-plus#943]
I'd like to see and use a tool like this: A plugin or a Notepad++ feature to set many column markers and horizontal rule in the editor when the indent is required. Currently I'm using COBOL at work and column markers (more than one) helps to develop faster. Edit plus contains this feature, but the application is very limited.

Something like this:
![column lines cobol](https://cloud.githubusercontent.com/assets/8593768/9993964/3e0178c8-6051-11e5-9c46-d12c0cca6b93.png)

**Comment by donho** [comment]
Unfortunately, Scintilla (the edit component used by Notepad++) doesn't have such feature. If such feature is in the future release of Scintilla, I'll include it in Notepad++.

**Comment by h-h-h-h** [comment]
@jhonatan4878: You can request it for Scintilla [here](http://www.scintilla.org/ScintillaToDo.html).
