### ISSUE TITLE
Autocomplete makes notepad++ unable to keep up with typing.

### ISSUE THREAD

**Issue by bartwe** [notepad-plus-plus/notepad-plus-plus#9433]
### Description of the Issue

With 'Enable auto-completion on each input' enabled in settings, in a small (20 line, no line longer than 80 chars) textfile (.txt extension) the program doesn't keep up with my typing, instead blinking an empty context menu, catching up a second later.
(i9-9900K at 4% cpu usage, 20GB ram free)

### Steps to Reproduce the Issue

1. ensure 'Enable auto-completion on each input' and 'Function and word completion' are turned on in settings.
2. create a new text document.
3. type 'hello world' at at least 200 CPM

### Expected Behavior

To see the editor display the characters as i type them

### Actual Behavior

See the character H appear, have a an empty (context menu?) box flash for a second, then the rest of 'ello world' appears.

### Debug Information

Notepad++ v7.9.2   (64-bit)
Build time : Dec 31 2020 - 04:01:34
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS Name : Windows 10 Pro (64-bit) 
OS Version : 2004
OS Build : 19041.630
Current ANSI codepage : 1252
Plugins : mimeTools.dll NppConverter.dll NppExport.dll

**Comment by wqpalmer** [comment]
I just updated NP++ and am also experiencing this issue. It seems to be related to auto-complete, but also the speed at which I type. ~100 WPM, so I suspect I'm also at >= 200 CPM.

I had not updated NP++ in between you posting this and today, so I'm wondering if it may be related to one of their recent updates.
