### ISSUE TITLE
7.9.2切换中文界面没有反应

### ISSUE THREAD

**Issue by BoyceLig** [notepad-plus-plus/notepad-plus-plus#9438]
![image](https://user-images.githubusercontent.com/49801599/105477482-dde0f480-5cdc-11eb-876c-3440c0714a19.png)

**Comment by GSWXXN** [comment]
安装目录\localization\chineseSimplified.xml
852行，将`</Scintillas>`改为`</MarginsBorderEdge>`
然后重新设置语言

**Comment by sasumner** [comment]
Known issue; fix will come in 7.9.3

**Comment by BoyceLig** [comment]
> Known issue; fix will come in 7.9.3

谢谢
