### ISSUE TITLE
ꞩ and Ꞩ not displaying correctly by default

### ISSUE THREAD

**Issue by LawranceFung** [notepad-plus-plus/notepad-plus-plus#9440]
ꞩ (U+A7A9) and Ꞩ (U+A7A8) do not display correctly unless a character like ①②③④⑤⑥⑦ is on the same line.

**Comment by sasumner** [comment]
_Settings_ menu > _Preferences..._

![image](https://user-images.githubusercontent.com/30118311/105531250-06ee8e80-5cb7-11eb-9b12-f49bf4b4fac8.png)

**Comment by LawranceFung** [comment]
Is this feature missing in the preferences of the x86 version?
![image](https://user-images.githubusercontent.com/8716212/105565205-4b941d00-5ceb-11eb-8d22-981b2588facc.png)

**Comment by sasumner** [comment]
You're showing the "General" page of the _Preferences_ ; you need to switch to the "MISC." page as I show, using the box that appears on the left-hand side of the window.

**Comment by LawranceFung** [comment]
Thanks!  I had the window snapped to the upper left corner of my screen so when the window came up the general ... misc area was off the display.
