### ISSUE TITLE
Handle a large file with over million lines better

### ISSUE THREAD

**Issue by Toshiba1127** [notepad-plus-plus/notepad-plus-plus#9442]
### Description of the Issue
Notepad++ is very slow, takes very long time to open a large file with 1.3 million lines and slow when searching text. Other text editor like VS Code can handle large file very well without slowdown what so ever, like it still work fast as usual. And they open large file and search a text in just a second

But I still like to use Notepad++ better

Is it possible to improve performance so that Notepad++ can handle large file better at least?

I always work with very large dump files for use on my project. Here is the file if you want to try something
[dump.zip](https://github.com/notepad-plus-plus/notepad-plus-plus/files/5860490/dump.zip)

### Debug Information
Notepad++ v7.9.2   (64-bit)
Build time : Dec 31 2020 - 04:01:34
Path : F:\Program Files\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : ON
OS Name : Windows 10 Pro (64-bit) 
OS Version : 2004
OS Build : 19041.746
Current ANSI codepage : 1252
Plugins : ComparePlugin.dll DSpellCheck.dll mimeTools.dll NppConverter.dll NppExport.dll

**Comment by sasumner** [comment]
Change the _Language_ on such files to _None (Normal Text)_ and they will be much faster to manipulate.
Otherwise, you provided the solution yourself:  Use VS Code or some other editor.
