### ISSUE TITLE
[BUGs] Manual update functionality does not work or does not work as expected (v7.9.1 64 bits)

### ISSUE THREAD

**Issue by MAC-GH** [notepad-plus-plus/notepad-plus-plus#9444]
### Description of the Issue

1. Manual update from Help/Update Notepad++ does not find the currently available version 7.9.2

2. Manual update by launching <Notepad++ install dir>\updater\GUP.exe downloads the 32 bit version of Notepad++ v7.9.1 installer instead of the 64 bit version of the Notepad++ v7.9.2 installer

### Steps to Reproduce the Issue

1.  Launching the Help/Update Notepad++ returns "No update is available." (I have no proxy and also disabled the firewall).

2. Manually launching <My custom Notepad++ install dir>\updater\GUP.exe downloads and launches the npp.7.9.1.Installer.exe (32 bits) while my currently installed version is already 7.9.1 but 64 bits.

### Expected Behavior

1. Launching the Help/Update Notepad++ should find the currently available version 7.9.2 => As users informed (see the comments below), the v7.9.2 is not considered stable enough to be triggered by the update check so this is not an issue.

2. Manually launching <My custom Notepad++ install dir>\updater\GUP.exe should download (as of today, 2021 01 24) the 64 bits version (as my currently installed version) of the v7.9.2 installer

**Comment by sasumner** [comment]
1 is not an issue, due to the way the process works.

**Comment by MAC-GH** [comment]
Thank you for your reply but I'm not sure I understand. Wasn't the update check supposed to tell there is an update available ? There are 3 weeks now since v7.9.2 was released.

**Comment by sasumner** [comment]
The author has judged that 7.9.2 is too buggy to be triggered for auto-update.

**Comment by MAC-GH** [comment]
Ah, ok, thank you. I'll update the issue with this information.

**Comment by mere-human** [comment]
There is another related issue that tends to provide more info when checking for updates.
You can take a look: https://github.com/notepad-plus-plus/wingup/issues/13

**Comment by babenkovitaliy** [comment]
Today is March 14 (happy pi day). 

- My Notepad++ is still on 7.9.1 (released 11/02/2020)
- 7.9.2 was released on 01/01/2021, but never prompted me for an update (conversation here says that it was too buggy)
- 7.9.3 was released on 02/15/2021 (one day away from being a month old).
- Author says that "Auto-updater will be triggered in few days if there’s no critical issue found." Is there a critical issue that we do not know about? Or did the author forget to mark that the update is safe for release?

I can manually update if I really want to, but it seems to ruin the whole purpose of having an auto updater.
