### ISSUE TITLE
Mouse side scroll only moves the scroll bar not the actual page

### ISSUE THREAD

**Issue by Hounsvad** [notepad-plus-plus/notepad-plus-plus#9452]
### Description of the Issue

Using side scroll does not work.
### Steps to Reproduce the Issue

1. Have mouse with feature to scroll sideways
2. Use said feature

### Expected Behavior

It would be expected that the page scrolls sideways

### Actual Behavior

Only the scroll bar scrolls sideways, but the page itself does not scroll.
If the scroll bare is moved by clicking and dragging it works fine.

### Debug Information

Notepad++ v7.9.1   (32-bit)
Build time : Nov  2 2020 - 01:03:56
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS Name : Windows 10 Enterprise (64-bit) 
OS Version : 2009
OS Build : 19042.746
Current ANSI codepage : 65001
Plugins : mimeTools.dll NppConverter.dll NppExport.dll XMLTools.dll 

![GithubNotepad++Error](https://user-images.githubusercontent.com/36563020/105978653-13962c80-6093-11eb-9b5c-f9dce7852998.gif)

**Comment by sasumner** [comment]
Works fine for me.
You can provide details about your mouse if you'd like, but if it comes down to some problem that is very "mouse specific", it probably isn't going to be made to work.

**Comment by Hounsvad** [comment]
Hmm how odd I use an MX master 2

**Comment by Hounsvad** [comment]
A Re-install cleared the issue

**Comment by sasumner** [comment]
FYI, the "MX master 2" is long-known to have interaction issues with Notepad++, so don't be surprised if you uncover other problems.

Look at the results of this search: https://github.com/notepad-plus-plus/notepad-plus-plus/issues?q=is%3Aissue+MX+master+2
