### ISSUE TITLE
Document List Panel a.k.a. Doc Switcher disappears on minimize

### ISSUE THREAD

**Issue by wilkowy** [notepad-plus-plus/notepad-plus-plus#9454]
### Description of the Issue
Document List Panel a.k.a. Doc Switcher box disappears on minimizing and restoring pinned N++

### Steps to Reproduce the Issue
1. Pin N++ to taskbar
2. Settings->Preferences->General->Document List Panel - mark Show
3. Click N++ icon on taskbar to minimize window or minimize from minimize button
4. Restore N++ by clicking on taskbar

### Actual Behavior
![npp-docswitcher](https://user-images.githubusercontent.com/5204438/106015018-5c170f80-60be-11eb-8437-ce24c0de1402.jpg)

Important:
If restoring N++ from tray bar container (no matter if pinned or not) Doc Swicher box reappears.

### Debug Information
Notepad++ v7.9.2   (64-bit)
Build time : Dec 31 2020 - 04:01:34
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS Name : Windows 7 Ultimate (64-bit) 
OS Build : 7601.23964
Current ANSI codepage : 1250
Plugins : AnalysePlugin.dll ComparePlugin.dll DSpellCheck.dll JSMinNPP.dll mimeTools.dll NppConverter.dll nppcrypt.dll NppExport.dll NPPJSONViewer.dll NppQrCode64.dll SurroundSelection.dll XMLTools.dll _CustomizeToolbar.dll

**Comment by xaminmo** [comment]
Just to clarify, some version of this bug still exists in 8.4.4.

To clarify the trigger:
* Open NP++, docs, etc.
* Enable Document list if not already.
* Minimize NP++ window to tray.
* Open a new text file from windows context menu
* When NP++ window is restored, the document list is missing.
* The view menu still shows it's enabled.

Resolution is to disable then re-enable the document list from the View menu.

Notepad++ v8.4.4   (32-bit)
Build time : Jul 15 2022 - 17:56:38
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Command Line : "E:\GoogleDrive\Xaminmo\201x Money\ESS_Conflicts\2022-07_Meltdown_regarding_being_Excluded.txt"
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 10 Enterprise (64-bit) 
OS Version : 21H2
OS Build : 19044.1826
Current ANSI codepage : 1252
Plugins : 
    mimeTools (2.8)
    NppConverter (4.4)
    NppExport (0.4)
    SessionMgr (1.4.3)

**Comment by robotboy655** [comment]
Cannot confirm on 8.4.7

**Comment by xaminmo** [comment]
I installed 8.4.8 64-bit Windows edition, and the same issue happens:

If the doc list is open, and I minimize to tray, and then open another text file in notepad++, it will open the main window without the doc list.  I have to uncheck, then re-check.  

If NP++ is closed entirely, then opening a new document uses what setting was in place when I exited the application.


Notepad++ v8.4.8   (64-bit)
Build time : Dec 24 2022 - 19:40:27
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : "C:\Users\xaminmo\Desktop\GC_Complaint.txt"
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 10 Pro (64-bit) 
OS Version : 22H2
OS Build : 19045.2486
Current ANSI codepage : 1252
Plugins : 
    mimeTools (2.9)
    NppConverter (4.5)
    NppExport (0.4)

**Comment by Yaron10** [comment]
@alankilborn,

Can you reproduce this issue?

**Comment by robotboy655** [comment]
I was able to reproduce the issue and proposed a fix here: https://github.com/notepad-plus-plus/notepad-plus-plus/pull/12817

**Comment by Yaron10** [comment]
@robotboy655,

Thank you for replying.

> Open a new text file from windows context menu

I'm using the portable version, and I don't have Notepad++ in Windows context-menu.
Can you reproduce it without that step?

**Comment by robotboy655** [comment]
No, the issue cannot be reproduced without hiding NP++ to tray this setting:
![image](https://user-images.githubusercontent.com/3299036/213869710-9653d25f-be63-4aaa-ae70-9229337380ad.png)

**Comment by Yaron10** [comment]
@robotboy655,

I understand that.
My question was if you could reproduce it without:
> Open a new text file from windows context menu

**Comment by robotboy655** [comment]
Yes, the issue only happens if you open a second instance of notepad++ with "Mono instance" setting enabled and it being minimized to system tray. It doesn't matter how you open that second instance - "Edit with Notepad++" in context menu, manually opening the program, command line or whatever else.

**Comment by Yaron10** [comment]
Could you please post a screenshot of your "Multi-Instance & Date" settings page?

**Comment by robotboy655** [comment]
![image](https://user-images.githubusercontent.com/3299036/213882800-6e547c9a-9660-4909-a965-0739b2c9bc62.png)

**Comment by Yaron10** [comment]
@robotboy655,

👍 
Thank you.
