### ISSUE TITLE
Notepad++ 7.9.3 diff file (vs v7.9.2)

### ISSUE THREAD

**Issue by donho** [notepad-plus-plus/notepad-plus-plus#9455]
Here's the diff between v7.9.2 and v7.9.3 (in HTML format) for Notepad++ translators:
[792vs793.zip](https://github.com/notepad-plus-plus/notepad-plus-plus/files/5882244/792vs793.zip)

**Comment by ArkadiuszMichalski** [comment]
Only for me one space after `:` make this number more readable? 
`<NbDocsTotal name="total documents:"/>`

**Comment by sasumner** [comment]
@ArkadiuszMichalski 

To me, it should be defined this way:

`<NbDocsTotal name="total documents"/>`

and the code should add the `:` and a space, before the number.

**Comment by ArkadiuszMichalski** [comment]
It can also be that. It even works to add more spaces (in translation file) if someone really wants to.

**Comment by donho** [comment]
@ArkadiuszMichalski 
I'll add a space in english.xml

**Comment by donho** [comment]
or as @sasumner suggested, into the code.
