### ISSUE TITLE
Doc Switcher: drag&drop rearranging

### ISSUE THREAD

**Issue by ccompletion** [notepad-plus-plus/notepad-plus-plus#946]
Just like user can drag&drop tabs to rearrange them, so could Doc Switcher allow drag&drop to rearrange.
Doc switcher could remember document order, just like tabs remember the order.
Doc Switcher could be a decent alternative to tabs in this regard.

**Comment by h-h-h-h** [comment]
Related issue: https://github.com/notepad-plus-plus/notepad-plus-plus/issues/571

**Comment by cajuncool** [comment]
More closely related (duplicate): #1684

**Comment by tweedbeats** [comment]
Detailed feature request at: #2342

**Comment by tiomanisland** [comment]
What a shame. 4 years and still not done. Instead author is bothering with China he could have spent 15 minutes on this.

**Comment by pidgeon777** [comment]
I'm also interested.
