### ISSUE TITLE
View \ Hide Line Number Margin doesnt work in 7.9.2

### ISSUE THREAD

**Issue by wallobit** [notepad-plus-plus/notepad-plus-plus#9471]
In Version 7.9.1 it works

**Comment by sasumner** [comment]
Please write a coherent issue.

**Comment by sasumner** [comment]
I reopened because I thought the original poster would just open YET ANOTHER issue.
But since we got entirely no response at all, closing was the correct action.

**Comment by donho** [comment]
@sasumner 
I thought you reopened it by accident. OK just reopen it if you want. But I think @wallobit just doesn't care of adding the info.
I cannot reproduce it and I believe it's yet another PEBKAC.
