### ISSUE TITLE
Changes not saved for newly created *.R file!

### ISSUE THREAD

**Issue by tomastelensky** [notepad-plus-plus/notepad-plus-plus#9475]
### Description of the Issue
After creating and saving new *.R file, further modifications are not being saved! Neither in the c:\Users\Tomas\AppData\Roaming\Notepad++\backup\ directory, and not even when saved explicitly by Ctrl-S! Status of the file (the color of the disquette icon on the tab) is not updated.

### Steps to Reproduce the Issue

1. Open new tab by Ctrl-N
2. Write some R code, e.g. "a <- 1"
3. Save as "a.R".
4. Add another line of code, e.g. "b <- 2". 
5. Save by Ctrl-S.

### Expected Behavior
In step 4, status of the file should update (disquette icon on the tab should turn red). After few seconds, the modified file should be seen in c:\Users\Tomas\AppData\Roaming\Notepad++\backup\. 

In step 5, changes should be saved in the file "a.R".

### Actual Behavior
In step 3, first version of the file is saved successfully, which is allright.

But in step 4, status of the file doesn't update! (Disquette icon on the tab stays blue, doesn't turn red). No changes saved in the c:\Users\Tomas\AppData\Roaming\Notepad++\backup\ directory.

In step 5, no changes are saved in the file "a.R"!!

### Notes

- Doing the same process with "*.txt" file shows no such problems. 
- It is only problem for newly created files. If I close the file and open it again in NPP, the problem disappears.

### Debug Information

Notepad++ v7.9.1   (32-bit)
Build time : Nov  2 2020 - 01:03:56
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS Name : Windows 10 Enterprise (64-bit) 
OS Version : 1803
OS Build : 17134.1845
Current ANSI codepage : 1250
Plugins : mimeTools.dll NppAutoIndent.dll NppConverter.dll NppExport.dll NppTextFX.dll SessionMgr.dll 

There is 1.6 GB of free space on the disk.

**Comment by sasumner** [comment]
Unable to reproduce in 7.9.2.

**Comment by tomastelensky** [comment]
> Unable to reproduce in 7.9.2.

Ah! Why don't I have the newest version? I ran `? / Update Notepad++` and I got 7.9.1 installed instead of 7.9.2! Why?

**Comment by tomastelensky** [comment]
`? / Update Notepad++` now tells me "No update available".

**Comment by sasumner** [comment]
>I got 7.9.1 installed instead of 7.9.2! Why?

7.9.2 was judged to have too many small problems for you to get updated to that version.

Retested issue with 7.9.1:  Unable to reproduce in 7.9.1

**Comment by sasumner** [comment]
Retested issue with 7.9.1:  Unable to reproduce in 7.9.1

**Comment by mere-human** [comment]
Update dialog will be upgraded to provide more info as well as the download link in case auto-update isn't active at the moment:
https://github.com/notepad-plus-plus/wingup/issues/13

**Comment by tomastelensky** [comment]
Thanks for the info. I will keep testing under 7.9.1 then.

I tested this issue with new user with completely new NPP profile. Reproduced it again. The issue was present also in version 7.7.x (don't remember "x"), from which I upgraded.

I also tested it now on different machine, my old laptop with Windows XP, Notepad++ version 6.9.2 - and it is also present!! So I don't really know how can you _not_ reproduce the issue? :-)

How do we proceed now?

**Comment by sasumner** [comment]
>So I don't really know how can you not reproduce the issue? :-)
How do we proceed now? Shall I post more detailed setup? How?

Such problems can be "difficult".  :-)
I tried a freshly extracted "portable" version, perhaps trying the same on your end will reveal something?
Perhaps some sort of plugin interaction?

Here's what I tried:

Notepad++ v7.9.1   (32-bit)
Build time : Nov  2 2020 - 01:03:56
Path : C:\.......\npp.7.9.1.portable\notepad++.exe
Admin mode : OFF
Local Conf mode : ON
OS Name : Windows 10 Enterprise (64-bit) 
OS Version : 1909
OS Build : 18363.1256
Current ANSI codepage : 1252
Plugins : mimeTools.dll NppConverter.dll NppExport.dll

**Comment by Uhf7** [comment]
Please try this: https://github.com/notepad-plus-plus/notepad-plus-plus/issues/8287#issuecomment-711135440

**Comment by tomastelensky** [comment]
> Please try this: [#8287 (comment)](https://github.com/notepad-plus-plus/notepad-plus-plus/issues/8287#issuecomment-711135440)

I can confirm that removing the Session Manager does work around the issue, and I am looking forward for the update promissed in version 7.9.3 :-) 

Thank you for fixing this! :-)
