### ISSUE TITLE
Simplified Chinese translation cannot be loaded

### ISSUE THREAD

**Issue by ruantu** [notepad-plus-plus/notepad-plus-plus#9481]
### Description of the Issue
Unable to load Simplified Chinese translation, but can load Taiwanese and Hong Kong Cantonese.

### Expected Behavior
GUI displayed Simplified Chinese.

### Actual Behavior
GUI displayed English.

### Debug Information
Notepad++ v7.9.2   (64-bit)
Build time : Dec 31 2020 - 04:01:34
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS Name : Windows 7 Ultimate (64-bit) 
OS Build : 7601.24546
Current ANSI codepage : 936
Plugins : none

**Comment by sasumner** [comment]
Known issue, fixed with 7.9.3 release.
