### ISSUE TITLE
Change application file description?

### ISSUE THREAD

**Issue by sasumner** [notepad-plus-plus/notepad-plus-plus#9489]
Per the discussion [HERE](https://community.notepad-plus-plus.org/topic/20678/), is it reasonable and worth it to rework the application description a bit?

As the "objectionable" part appears to be mentioning "GNU", why not change:  `Notepad++ : a free (GNU) source code editor` to:

*  `Notepad++ : a text and source code editor` or
*  `Notepad++ : a better text / source code editor`

The app description would also be shown in right-click Open With, as shown in #8606

Info above pertains to app contents currently in version 7.9.2.

**Comment by sasumner** [comment]
Here would be the area of change, if change is desired:  https://github.com/notepad-plus-plus/notepad-plus-plus/blob/5155dfed9d01695525ac1ce1c97a0d72d6f8a261/PowerEditor/src/Notepad_plus.rc#L40

**Comment by donho** [comment]
It's the problem of the term and GNU is not a right term indeed.
I'll change it to: "Notepad++ : a free (GPL) source code editor"

**Comment by sasumner** [comment]
The problem is, users will be just as confused as to what GPL means as they were to GNU.

**Comment by donho** [comment]
GPL is license applied in Notepad++ project - this information is accurate, so I don't see any problem.

**Comment by sasumner** [comment]
I guess you really want to have the word "free" in there.
And you don't feel it is correct to just say "free" alone.
So...it's OK.

**Comment by donho** [comment]
> And you don't feel it is correct to just say "free" alone.

Yes, that's really my intention.

**Comment by Neustradamus** [comment]
@donho: It is possible to have only "Notepad++" in "FileDescription"?
It is currently big in crash window and in taskbar.
And have long part in "Comments"?
- https://docs.microsoft.com/en-us/windows/win32/menurc/stringfileinfo-block
