### ISSUE TITLE
Vertical tabs with horizontal text

### ISSUE THREAD

**Issue by ccompletion** [notepad-plus-plus/notepad-plus-plus#949]
Does anybody use current vertical tab implementation, leaning their head all the time?
Vertical tabs could have an option to display text horizontally.
Width could be settable and remembered by Notepad++.
Multiline settings makes no sense in this scenario, so ignore it.
There would be only one vertical line of tabs, with up/down scrolling when too many tabs.
Basically, just like Doc Switcher, but with tabs and no white background.
Or, Doc Switcher could be improved into a complete alternative to tabs.

**Comment by donho** [comment]
The current GUI doesn't allows Vertical tabs with horizontal text. If there's any way for it (win32 API), please let me know. I'll consider it then.

**Comment by ccompletion** [comment]
I understand. I thought that vertical tabs were already a custom solution (never saw it anywhere else), but if it isn't then it's completely understandible that this is not easy to implement.

The reason I submitted some suggestions is that the new tabs are very big. While high DPI fixes are most welcome, tabs were an exception - they were nice and compact at high DPI. I'm looking for alternatives now, so I guess I'll keep my hopes with Doc Switcher, then :)

**Comment by DavidFuchs42** [comment]
ccompletion, Have you tried a document list panel? 
- Settings  
- Preferences 
- General 
- (in document list panel) 
-- show (checked)
