### ISSUE TITLE
Ascending form

### ISSUE THREAD

**Issue by wernser412** [notepad-plus-plus/notepad-plus-plus#9490]
The numbers:
-1 , -1.275 , 0 ,0.95

When I put them with the option in an ascending way it gives me this result:
-1
-1.275
0
0.95

it should not be like that?
-1.275
-1
0
0.95

I am using the V.7.9.2

**Comment by sasumner** [comment]
![image](https://user-images.githubusercontent.com/30118311/107221931-47057f00-69e2-11eb-91d2-fd096a2eb005.png)
