### ISSUE TITLE
[Typo] Minor typo in French

### ISSUE THREAD

**Issue by pfrison** [notepad-plus-plus/notepad-plus-plus#9492]
As seen in `CONTRIBUTING.md`, I want to report a typo in french.

### Description of the Issue
There is a minor typo in French language. "**Ovrir**", the word for "Open", is spelled "**Ouvrir**"
In `/PowerEditor/installer/nativeLang/french.xml`, item id 46300, line 296 : https://github.com/notepad-plus-plus/notepad-plus-plus/blob/3419a749d9bb9fcd5dce1d98723dccb3170c3d0e/PowerEditor/installer/nativeLang/french.xml#L296

The correct sentence is `Ouvrir le dossier des Langages utilisateur...`

### Steps to Reproduce the Issue
1. Open notepad++
2. Select French as main language in global settings
3. Go to `Langage (toolbar) -->Langage utilisateur`
4. The second option is spelled : `Ovrir le dossier des Langages utilisateur...`

### Expected Behavior
We should read `Ouvrir le dossier des Langages utilisateur...`

### Actual Behavior
The text is `Ovrir le dossier des Langages utilisateur...`

### Debug Information
None.

PS : I've been using notepad++ for years, so allow me to thanks you all for this awesome project !

**Comment by thomassmith311** [comment]
I know French, and this is correct. The fix seems easy enough, so I did it... https://github.com/notepad-plus-plus/notepad-plus-plus/pull/9495
