### ISSUE TITLE
Add some instruction how to test latest NPP build.

### ISSUE THREAD

**Issue by ArkadiuszMichalski** [notepad-plus-plus/notepad-plus-plus#9493]
I often see people reporting something that has been fixed in last build version. Maybe they don't know how to check something in this version of the program without compiling it (via the last appveyor).

Some detailed step-by-step instructions on how to do it in the portable version (maybe with pics) would be recommended. And when opening new bugs, you should link to it somewhere at the very beginning.

**Comment by mere-human** [comment]
This seems like a good idea.
But where is this supposed to be?
Manual page? https://npp-user-manual.org/

**Comment by sasumner** [comment]
>I often see people reporting something that has been fixed in last build version.

They do that, often?

Actually, I didn't know about getting the last-build, myself, so I found out:

This link gets you to where you can download the "current build" version:  https://ci.appveyor.com/project/donho/notepad-plus-plus

At that, if you click on one of the debug jobs (non-ming) you will be taken to a screen where you can download an .exe by clicking on the "artifacts" link.

The .exe is 99% of the time the only thing you need.  You can paste that .exe alongside your (relatively) current notepad++.exe (it has a different name so it won't overwrite), and then to test it all you need to do is exit Notepad++ and restart it using that different exe.

**Comment by ArkadiuszMichalski** [comment]
> They do that, often?

Yes, at least I've seen a couple of them not so long ago. Additionally, some people don't realize that checking "some bug" in the last build is very easy as you described above, like here https://github.com/notepad-plus-plus/notepad-plus-plus/issues/9488#issuecomment-774554736. It would be good to have it described somewhere to just link how to do it, and not to duplicate this description every time.

**Comment by sasumner** [comment]
I'm not sure where it would go.
"Build instructions" would be a candidate location, but it isn't an exact fit there I guess.

**Comment by ArkadiuszMichalski** [comment]
I think separate subpage will be better, and put its link below "Build Notepad++" (https://github.com/notepad-plus-plus/notepad-plus-plus#build-notepad), as another header like ""How test different Notepad++ version". The description will take into account the build from appveyor", but also general notes how to use the portable version for test (because thanks to it we can test different version without mess up the current installation, if there is one). 

Also it makes no sense to repeating that someone should checks if the portable version also has some error, since we can just give him a link to the description. Many of the reported problems are due to outdated settings through the installation version (located in user folder), and such a thing can be determined immediately thanks to the testing in fresh portable version.

**Comment by sasumner** [comment]
>I think separate subpage will be better, and put its link below "Build Notepad++"

Obviously I defer such decisions and actions to @donho 

>it makes no sense to repeating that someone should checks if the portable version also has some error, since we can just give him a link to the description

I don't know what this means

**Comment by ArkadiuszMichalski** [comment]
> I don't know what this means

I mean to have a "ready to use"  description that we can simply link to it, and not to write it (or copy from our notes) again every time when someone doesn't know how to test program properly (you know: go to, download, copy, remove, e.t.c). 

If there is approval, at a free time I will create a initial description, and if necessary it can be correct or expanded.

**Comment by sasumner** [comment]
>I mean...

OK.  I thought you meant something else because you had said that previously.

**Comment by donho** [comment]
Build System is used for checking the devs' source code, not for such purpose in my opinion.
Even its generated binaries could be served for it, I think it won't really be useful - few of Notepad++ users come to report the bug, then they go away. They don't really stay for following the evolution of issues. 

But if you really think it'll help, I would suggest to put such information in issue template - so issue creators will read this info, if they do read. I don't think it's propriate in User Manual, and I would like to keep Github project home page as simple as possible.

**Comment by sakkamade** [comment]
If you are willing to do this, then I may as well give my suggesttion which is to add at the bottom of a main 'readme' a short entry consisting of link for [test builds page](https://ci.appveyor.com/project/donho/notepad-plus-plus) and a link to Wiki-page (or place it also on main) with a consimilar to a very clear, in my opinion, explanation that I have received from @sasumner earlier: 

> [HERE](https://ci.appveyor.com/project/donho/notepad-plus-plus) you may download the `.exe`. 
Put it in the same folder as your normal notepad++.exe and run it instead.

I don't think screenshots are necessary, for I guess the people who would want to report of an issue of `notepad++` has no need in more. 
With that said, time may prove me wrong.

**Comment by ArkadiuszMichalski** [comment]
>sakkamade 
>If you are willing to do this, then I may as well give my suggesttion which is to add at the bottom of a main 'readme' a short entry consisting of link for test builds page and a link to Wiki-page (or place it also on main) with a consimilar to a very clear...

That's what I was thinking about, just add one header to "readme" (How test), and put link to subpage in [Wiki](https://github.com/notepad-plus-plus/notepad-plus-plus/wiki), or add only a subpage to the wiki (for future reference).

>donho
>But if you really think it'll help, I would suggest to put such information in issue template - so issue creators will read this info, if they do read.

I'm not for it, because this template is already quite long. It would be better to mention about how testing the bug somewhere in the beginning the template (and add link to the wiki). But since most people are already struggling to come here and open a bug, the extra testing may not be encouraging for them. I close this thread, if someone has a different opinion and thinks it is worth it, then it can pick up the thread again.

**Comment by sasumner** [comment]
@ArkadiuszMichalski IMO it is worth it to compose something...the only unknown is where to put it when finished.

**Comment by donho** [comment]
@ArkadiuszMichalski 
It's OK for me in wiki.

**Comment by ArkadiuszMichalski** [comment]
Some initial version. Based on existing descriptions created by @MetaChuh and @sasumner (plus my thoughts).  Needs to be english corrected. Feel free to modify or extend.


# How to test different versions of Notepad++ #

Before you open a new bug, make sure it's also reproducible in the build version or at least in the last stable version of the program. If the problem is not strictly related to the Notepad ++ installation process (and in the installation version in general) then testing problem in the portable version is the best solution. Here are the reasons:

- The portable version does not require any installation and runs completely independent and isolated from your installed version. All custom settings, as well as any stuff you might want to try at the portable version, will not modify your installed version.
- The portable version allows you to quickly determine if the problem is due to incorrect / outdated configuration files (usually located in the user's system folders - [check manual](https://npp-user-manual.org/docs/config-files/)).
- The portable version allows you to quickly determine if the problem is due to your sets of plugins. 
- You can test same or different portable versions at the same time (just copy the current portable version to another folder or download another version). 
- After finishing the tests you can simply remove all unnecessary portable versions.

## Using the last portable version of Notepad++ ##

Please follow the steps below:
1. Download the latest portable version from the [official page](https://notepad-plus-plus.org/downloads/) (`.zip` or `.7z` package).
2. Extract the above package to some folder (for example `NPP`).
3. **Important note**: make sure to close all instances of notepad++ that might be running, before starting the portable version at the next step, to make sure you are using this portable version.
4. Open the extracted `NPP` folder and start this portable version by double-clicking on `notepad++.exe` inside this folder.
(note: `notepad++.exe` will just be seen as `notepad++`, if you have enabled to hide all known file extensions at your explorer settings)
5. Try to reproduce the problem in this portable version.

Tip: you can run different versions of Notepad ++ at the same time with the `-multiIns` argument (which allows you to skip step 3.):
```
notepad.exe -multiIns
```

## Using the current build version of Notepad++ ##

To make sure that the bug you are reporting has not been fixed in the current build version please follow the steps below:
1. Download and extract the latest portable version as descibed in "Using portable version of Notepad++" (**TODO**: link here).
2. Go to official current build page [https://ci.appveyor.com/project/donho/notepad-plus-plus](https://ci.appveyor.com/project/donho/notepad-plus-plus).
3. Click on the job (**TODO**: Debug or Release?) compatible with your version of Notepad ++ (`platform = Win32` or  `platform = x64`).
4. Click on the `artifacts` link located in the upper right corner.
5. Download the `.exe` file (depending on the step 3. will be `Notepad++.Win32.Unicode Release.exe` or `Notepad++.x64.Unicode Release.exe`).
6. Put this `.exe` file to your portable Notepad++ folder and start program with this `.exe`.
7. Try to reproduce the problem in this current build version.

If the problem still exists in the current build version of Notepad++ then please report it. In the report you can add a note that you have performed the test procedure in accordance with the official guidelines.

**Comment by sasumner** [comment]
@ArkadiuszMichalski 
Nice work. :-)

May I edit it, in place, above?
I have that power (to edit your posts), but don't want to do it without your permission, since it is your work.

**Comment by ArkadiuszMichalski** [comment]
Sure, it's best to do some Wiki subpage so that others can do PR if needed.

**Comment by sasumner** [comment]
Yes.  You and I can refine it, in the space above, but of course Don will have to create a final location for it.
But I'm sure Don doesn't want to do that until it is done.

**Comment by sasumner** [comment]
@ArkadiuszMichalski 

I think it best to not make it sound like it is mandatory to test "current build" version before submitting a bug.
It is probably "too much" for the typical user.
But it is great to have instructions for users that _want_ to do it.

It's probably best for "current build" to simply specify to use the "Debug" version.
Reasons:
- We don't want to go to the effort of discussing both
- Providing instructions for both also makes the user have to make a decision
- There is no advantage to one over the other
- If we add to the instructions later to discuss the SciLexer part (which is best to leave out for now) then the SciLexer DLL that is in the "Release" build won't run with Notepad++ (because release .exe expects a signed DLL and current-build SciLexer is not signed)

**Comment by ArkadiuszMichalski** [comment]
> I think it best to not make it sound like it is mandatory to test "current build" version before submitting a bug.

Sure, I meant to encourage for testing (nothing mandatory), and if someone do this would be nice to inform about it in a bug (to not check things in this way again). If it does not follow from the current description, then please make appropriate changes.

> It's probably best for "current build" to simply specify to use the "Debug" version.

Personally, I don't know how Debug is different from Relase (that's why I left it to your choice). 

> If we add to the instructions later to discuss the SciLexer part (which is best to leave out for now) then the SciLexer DLL that is in the "Release" build won't run with Notepad++ (because release .exe expects a signed DLL and current-build SciLexer is not signed)

Ahh, that's why I couldn't use it in my test setup (I always download relase version because it's smaller ). In general, I am finished here because I do not test it in any other way (I do not touch SciLexer and I do not use the standard NPP installation version). If any additional descriptions would be useful in their case, let a person make it who knows what he is writing about.

**Comment by sasumner** [comment]
@ArkadiuszMichalski Is it smart to mention multi-instance running with this?

If people have two Notepad++ exe in same folder (different names on the exe obviously), then having both running at the same time could be bad (in regards to when settings get written on exit).

Does bringing up multi-instance in these instructions provide a great benefit?  I'd like to remove.  What do you think?

**Comment by ArkadiuszMichalski** [comment]
It depends, if we have some versions always running and closing them would be a problem, `-multInst` for testing other versions is the solution (that's why I added it, also to not forget about it by myself). But in fact having two `.exe` in the same folder together and using `-multiInst` can overwrite each other's settings. Personally, I never keep more than one `.exe` in a given folder (if needed I copy the whole thing to a new place and overwrite the `.exe`).

Due to the fact that in step 3. for the build version it is mentioned about moving (not overwriting) the `.exe` this tip can be removed (or hidden behind a comment).

**Comment by donho** [comment]
@ArkadiuszMichalski 
Wiki is opened for everyone, so my permission is not needed. Just go ahead.

**Comment by ArkadiuszMichalski** [comment]
@sasumner 
Step 5. in your extension is necessary? In step 4. (where we have a list of all commits) we see small green-colored checkmarks for them, so we can click on one of them here and immediately click on `Detail`.

**Comment by sasumner** [comment]
>Step 5. in your extension is necessary? In step 4. (where we have a list of all commits) we see small green-colored checkmarks for them, so we can click on one of them here and immediately click on Detail.

It's true.  Actually, that checkmark is even smaller, and I've not even noticed it before.
I wish all of these green checkmarks were more noticeable.
Users will think they are playing "Where's Waldo".
I will amend the instructions with this new (to me!) information.

**Comment by sasumner** [comment]
@ArkadiuszMichalski Further feedback on my edits above?  I think I'm done.

**Comment by ArkadiuszMichalski** [comment]
@sasumner 
All this "current build version (see instructions below)." and simillar can be linked when this instruction will be published and headers gets it's own id.

How edit Wiki and add some page?  I don't see separte repo for it: https://github.com/notepad-plus-plus. Individual pages can be modified somehow through Web UI? Where is it best to put it, to the Wiki or to the User Manual?

**Comment by sasumner** [comment]
@ArkadiuszMichalski 

>How edit Wiki and add some page? I don't see separte repo for it: https://github.com/notepad-plus-plus. Individual pages can be modified somehow through Web UI? Where is it best to put it, to the Wiki or to the User Manual?

I think Don's suggestion of "wiki" meant to put it here?:

![image](https://user-images.githubusercontent.com/30118311/108718212-337f0b80-74ec-11eb-89d8-34c7d152c0b0.png)

I would rather see it in a more "mainstream" place, but it is not up to me.
I don't have further opinion on where it should go, so I'll leave it to you to figure that out.

**Comment by ArkadiuszMichalski** [comment]
@sasumner I know where it is, I even know how to get there :) 
![image](https://user-images.githubusercontent.com/2730894/108860901-f3ed1800-75ee-11eb-9293-4b12e72f8ad2.png)

But what next if it cannot be edited? This link works https://github.com/notepad-plus-plus/notepad-plus-plus.wiki.git for you? @donho how can we move forward with this instruction?

**Comment by donho** [comment]
@ArkadiuszMichalski 
I do have access to https://github.com/notepad-plus-plus/notepad-plus-plus/wiki

Don't you have New Page button?

![image](https://user-images.githubusercontent.com/90293/108879437-8eeeed80-7601-11eb-970e-be056483a12d.png)

**Comment by ArkadiuszMichalski** [comment]
@donho 
No, looks like only members have such power. Unless something is wrong with my site, someone else would have to confirm it. 

![image](https://user-images.githubusercontent.com/2730894/108881356-813a6780-7603-11eb-822c-0b1b6c1a6cd7.png)

**Comment by ArkadiuszMichalski** [comment]
Done:
https://github.com/notepad-plus-plus/notepad-plus-plus/wiki/Testing

I used simple name "Testing" (just like we have it for two other sites).  If you prefer another one, please change it. From now on, you can refer to the entire instruction or to its individual parts (headers have their own ID). They will remain valid until we change the page name or the text of the headers themselves. 

At this point I keept tip about `-multiInst` argument, but if that becomes a problem we can comment it out (HTML comment works in markdown file) or we can remove it completely. 

@sasumner Thanks for your help, corrects and extensions.

**Comment by ArkadiuszMichalski** [comment]
@sasumner 
Maybe mention something about this .dll because questions already arise. What do you think to add the following description at the end? In step 5 for current-build we can reffer to it:
`5. Note that although a .dll file is provided, it is typically not necessary to obtain this file (detail).`
Thanks to this, this instruction will not be extended and the details can be discussed below. 

I leave it here for now, if you have any comments or corrections then put it here. When it will be ready it can be added to Wiki. 

# Using a different version of SciLexer.dll file

Usually there is no need to change `SciLexer.dll` file to test out current-build or PR-build changes, because its code rarely changes from the last released version. It's only necessary when updating Scintilla or BOST library to newer versions. If this happens, pay attention to: 
- new `.dll` file can't be used with a "release" version of the `.exe` file (because the `.dll` is unsigned and the released `.exe` version expects to see a signed `.dll`). For this reason we recommend that you download the `Unicode Debug` version of `.exe` file in the above instructions.
- when you download new `.dll` file (in the same way as `.exe` file described above) you need to rename it to exactly `SciLexer.dll` and overwrite the previous file with it. Only one file `SciLexer.dll` can exist alongside the `.exe` file and that is the one that will be used. 
- Instead of deleting/overwriting the previous `SciLexer.dll` file, you can also rename it, e.g. to `_SciLexer.dll`. In this way you can switch between different .`dll` versions.

**Comment by sasumner** [comment]
> questions already arise

Questions arose because people tried to do their own thinking instead of just following the nice instructions.

In following instructions, don't do any more nor any less that what is specified.  If the instructions are inadequate that's a problem.  If the instructions are valid, but you go "off script" and encounter a problem, well, that's on you.

I've thought from the beginning that discussing the DLL is just "too much".  But if you think it is worth it, go ahead.  I made a tiny tweak to what you have above.

**Comment by sasumner** [comment]
@ArkadiuszMichalski 

Later thought:  Isn't it pointless to bring `SciLexer.DLL` into the instructions at all?  Reason:  I don't believe that the generated SciLexer.DLL` includes the Boost stuff at all.  :-(  So, okay, maybe user isn't testing any regular-expression-search thing, but some features besides pure searching are impacted by the regex engine used (e.g. function list).

It REALLY feels like it is "too much" to say anything at all about the Scintilla DLL, besides "ignore it".

**Comment by ArkadiuszMichalski** [comment]
@sasumner
Regarding to BOOST, I suggested the description from [BUILD.md](https://github.com/notepad-plus-plus/notepad-plus-plus/blob/master/BUILD.md), but if it's not true then I can delete it. 

Coming back to `SciLexer.DLL`, the purpose of mention about it was that when updating to the new version of Scintilla happend, then you could just write:
If anyone is interested in testing the new version, just follow the instructions:
[Using the current-build version of Notepad ++](https://github.com/notepad-plus-plus/notepad-plus-plus/wiki/Testing#using-the-current-build-version-of-notepad)
[Using a different version of SciLexer.dll file](https://github.com/notepad-plus-plus/notepad-plus-plus/wiki/Testing#using-a-different-version-of-scilexerdll-file)

If people know how to do it and will be a clear and simple description, then maybe bugs will be detected faster, before the relase version, such as this one https://github.com/notepad-plus-plus/notepad-plus-plus/issues/9555. See that these are just a few lines added at the end, and only those who are interested will read it. At least we know why we have two files in AppVeyor (`.exe` and `.dll`) and why `.dll` does not work in some cases.

**Comment by sasumner** [comment]
Regarding 9555 (which I suppose I had missed seeing until now), I made this comment: https://github.com/notepad-plus-plus/notepad-plus-plus/issues/9555#issuecomment-785187869

>Coming back to SciLexer.DLL, the purpose of mention about it was that when updating to the new version of Scintilla happend, then you could just write: If anyone is interested in testing the new version

Yes, but the key point is, if they test this way (without Boost as part of the mix), for certain things, they are going to put in bogus issues (a prime example being 9555).

My opinion is still to keep SciLexer out of it.

**Comment by ArkadiuszMichalski** [comment]
Yes, but the above problem  (if it's true) is rather because there is no information about what the AppVeyor build contains (there is no info anywhere that there is no BOOST and this may negatively affect some mechanisms). Or maybe it was mentioned about it somewhere, but nowhere in the official descriptions. I don't think @vinsworldcom would open a bug if he could read about it somewhere. But it is good that it happened so, at least in this topic we will be able to read about such things.

**Comment by mere-human** [comment]
AppVeyor uses a pre-built SciLexer.dll with Boost only in debug x86 build flavor.
It downloads the pre-bult dll from the site.
See: https://github.com/notepad-plus-plus/notepad-plus-plus/blob/master/appveyor.yml#L68

**Comment by ArkadiuszMichalski** [comment]
I think it was talked about somewhere, but I don't remember where. Thanks for the info.
