### ISSUE TITLE
Add (Remove) horizontal scrollbar automatically when it is (not) needed

### ISSUE THREAD

**Issue by mohammadrezasm** [notepad-plus-plus/notepad-plus-plus#9494]
Hi
Why down scrollbar isn't like the right scrollbar?
When I write a long line, it appears. but when I removing the line, it is still there and doesn't hide?

### Debug Information
Notepad++ v7.9.1   (64-bit)
Build time : Nov  2 2020 - 01:07:46
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS Name : Windows 10 Enterprise (64-bit) 
OS Version : 2009
OS Build : 19042.746
Current ANSI codepage : 1256
Plugins : DSpellCheck.dll mimeTools.dll NppConverter.dll NppExport.dll SpeechPlugin.dll

**Comment by sasumner** [comment]
Better stated as:
_Why doesn't the horizontal scrollbar disappear when there is no need to have it?_

**Comment by Uhf7** [comment]
> Why doesn't the horizontal scrollbar disappear when there is no need to have it?

I could imagine a large file with mostly short lines, let's say 40 characters for instance, and every 50th line is 200 characters long.  For the long lines, the horizontal scrollbar is needed, for the short lines not. Switching the horizontal scrollbar off whenever it is not needed would make the horizontal scrollbar constantly appearing and disappearing while scrolling vertically. And every time the horizontal scrollbar is switched, the number of lines in the edit window varies. One line more without horizontal scrollbar, one line less with horizontal scrollbar. 

A way out of this would be to know how long the longest line of the file is. I don't think, this information is available or easy to obtain. Except by iterating through all lines every time, which cannot be done for large files.

**Comment by sasumner** [comment]
IMO we don't need any changes regarding this.
I don't know why such a thing bothers people.

**Comment by donho** [comment]
> A way out of this would be to know how long the longest line of the file is. I don't think, this information is available or easy to obtain. Except by iterating through all lines every time, which cannot be done for large files.

True. A search for every single modification will make a performant issue for a large file. It's not worth to implement such feature.
