### ISSUE TITLE
The button order on Find dialog has been changed after update to 7.9.1

### ISSUE THREAD

**Issue by IceBeauty123** [notepad-plus-plus/notepad-plus-plus#9497]
### Description of the Issue

The button order on Find dialog has been changed after update to 7.9.1
From top to bottom it was Find Next, Count, Find All in All Opened Documents, Find All in Current Document, Close.
Now the order of Find All in All Opened Documents, Find All in Current Document has been changed, which is not convenient for old users like me.  I normally have many opened files, this change makes me click to the wrong button often.  

### Steps to Reproduce the Issue

1. 
2. 
3. 

### Expected Behavior

I don't wish the button layout order change.  Muscle has remembered where to click.
### Actual Behavior

The buttons order changed.  Since too many words on these 2 buttons, it is difficult to see clearly which is "current" and, which is "all opened".  I am thinking "Find All" may be not necessary in common sense.  "Document(s)" is replace with "File(s)" can make things simple.
"Find in all opened files"
"Find in current file"
### Debug Information

Notepad++ v7.9.1   (64-bit)
Build time : Nov  2 2020 - 01:07:46
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : ON
Local Conf mode : OFF
OS Name : Windows 10 Enterprise (64-bit) 
OS Version : 2009
OS Build : 19042.746
Current ANSI codepage : 1252
Plugins : AutoCodepage.dll AutoSave.dll ComparePlugin.dll CustomLineNumbers.dll DoxyIt.dll DSpellCheck.dll LuaScript.dll mimeTools.dll NotepadStarterPlugin.dll npp.connections.dll NppConverter.dll NppExport.dll NppFavorites.dll NppFTP.dll NPPJSONViewer.dll NppTaskList.dll NppXmlTreeviewPlugin.dll Python Indent.dll TakeNotes.dll 

![image](https://user-images.githubusercontent.com/78828860/107442593-5d582b80-6b05-11eb-94c5-555549fc3260.png)

**Comment by sasumner** [comment]
>I don't wish the button layout order change.

Sorry.  It isn't going to be changed back.
Suggest downgrade to make yourself happy?
