### ISSUE TITLE
Auto-indent in JSON file

### ISSUE THREAD

**Issue by vinsworldcom** [notepad-plus-plus/notepad-plus-plus#9499]
### Description of the Issue
I believe JSON does not allow single line control structures without braces.  In other words, if I specify and object:

```
"myobject": { "key": "value" }
```

I need to use the braces `{` and `}`.  I can put them on separate lines:

```
"myobject": { 
    "key": "value"
}
```

but they need to be there.  When I type the `{` brace and press enter, Notepad++ does not auto-indent a "tab" length for me like it does in other language where braces delimit control structures (e.g., Perl, Powershell).

**!!! PLEASE !!!** Someone else weigh in on this and let me know if that assumption is correct??

I think this can be easily fixed by editing [this](https://github.com/notepad-plus-plus/notepad-plus-plus/blob/3419a749d9bb9fcd5dce1d98723dccb3170c3d0e/PowerEditor/src/Notepad_plus.cpp#L3070) to this:

```
			else if (type == L_PERL || type == L_RUST || type == L_POWERSHELL || type == L_JSON)
```

### Steps to Reproduce the Issue

1. Set file type to JSON
2. Enter:
```
"myobject": { 
```

3.  Press "Enter" 

You get:

```
"myobject": { 
|
```

Where the pipe `|` is the cursor.

### Expected Behavior

```
"myobject": { 
    |
```

Where the pipe `|` is the cursor - indented by the language specific tab setting.

### Actual Behavior
No auto-indent.

### Debug Information
Notepad++ v7.9.3   (64-bit)
Build time : Feb  8 2021 - 18:16:35
Path : C:\usr\bin\npp64\notepad++.exe
Admin mode : OFF
Local Conf mode : ON
OS Name : Windows 10 Enterprise (64-bit) 
OS Version : 1909
OS Build : 18363.1316
Current ANSI codepage : 1252
Plugins :

**Comment by sasumner** [comment]
>!! PLEASE !!! Someone else weigh in on this and let me know if that assumption is correct??

I don't know about absolute correctness, but **_I_** like it. :-)

But I wouldn't limit it to `{` ... I think your desires apply equally well to `[`

**Comment by ArkadiuszMichalski** [comment]
Auto-ident for `{}` and `[]` after pressing enter would be nice. Note that in JavaScript (where object notation is very similar to JSON) this is true for `{}`, but not for `[]`. Generally I see that for C-like syntax lexer does not indent `[]`. 

I also check Visual Studio Code and we have auto-indent for `{}` and `[]` in C-like syntax.

**Comment by vinsworldcom** [comment]
@sasumner , @ArkadiuszMichalski 

Thanks for reply - I"m not a JSON expert, but have spent the last 2 days in a monster JSON file and this auto-indent would be very handy.

I just checked Perl, Javascript, PowerShell and C and **none** of those auto-indent for brackets `[`, only braces `{` so the same behavior would be find in JSON.

I think if we want to enable auto-indent for brackets `[`, maybe that's a separate discussion / issue since it doesn't seem enabled for any languages?

Cheers.




Cheers.

**Comment by ArkadiuszMichalski** [comment]
>I think if we want to enable auto-indent for brackets [, maybe that's a separate discussion / issue since it doesn't seem enabled for any languages?

Sure, I just checked what other programs were doing in this case.

**Comment by sasumner** [comment]
>>I think if we want to enable auto-indent for brackets [, maybe that's a separate discussion / issue since it doesn't seem enabled for any languages?

>Sure, I just checked what other programs were doing in this case.

And, I only brought up `[` because it is just as prevalent in JSON-formatted data structures as `{` is.

**Comment by vinsworldcom** [comment]
@ArkadiuszMichalski , @sasumner 

Agree with you both, I just never realized brackets `[` didn't work that way as I'm usually using them as an array index (e.g., $variable[2]) do never really pressing return after them.

Cheers.

**Comment by sasumner** [comment]
So as a simple example, perhaps you were hand-building up this structure, you can clearly see where autoindentation after `[` would be desired:

```
[
    "foo", 
    {
        "bar": [
            "baz", 
            null, 
            1.0, 
            2
        ]
    }
]
```

BTW, this is just a "pretty-printed" JSON string dump, so it is a quite-common format.
Not sure how often one would "hand-create" in this exact format, though.

**Comment by vinsworldcom** [comment]
> Not sure how often one would "hand-create" in this exact format, though.

I'm stuck creating a configuration file - in JSON, so I've been "hand-creating" for the past few days - hence this issue raised!

Thanks for the feedback - I'll submit the pull request.

Cheers.

**Comment by sasumner** [comment]
>Not sure how often one would "hand-create" in this exact format, though.

Well, actually... I do it, too! :-)
