### ISSUE TITLE
SCI_STUTTEREDPAGEUP and SCI_STUTTEREDPAGEDOWN not working anymore

### ISSUE THREAD

**Issue by ygoe** [notepad-plus-plus/notepad-plus-plus#9500]
### Description of the Issue
The scintilla commands SCI_STUTTEREDPAGEUP and SCI_STUTTEREDPAGEDOWN used to move the cursor to the first/last visible line in the current view. Repeated invocation did not move any further. That's what happens when pressing Ctrl+PgUp/PgDown in any recent version of Visual Studio. (Recommended in #1478) Today I discovered that the behaviour has changed.

### Steps to Reproduce the Issue
1. Assign keyboard shortcuts to use these scintilla commands:
2. SCI_STUTTEREDPAGEUP: Ctrl + Page up
3. SCI_STUTTEREDPAGEDOWN: Ctrl + Page down
4. Open a long document and use these hotkeys

### Expected Behavior
Cursor moves as described above. View does not scroll at all.

### Actual Behavior
Page up acts as if Ctrl was not pressed, i.e. a regular page up command. The view is scrolled (must not happen) and the same visual line is selected.

Page down works as expected the first time, but repeated uses also scroll down the view like a regular PageDown command.

### Debug Information
Notepad++ v7.9.1   (32-bit)
Build time : Nov  2 2020 - 01:03:56
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS Name : Windows 10 Enterprise (64-bit) 
OS Version : 2004
OS Build : 19041.746
Current ANSI codepage : 1252
Plugins : CustomizeToolbar.dll mimeTools.dll NppConverter.dll NppExport.dll NppSaveAsAdmin.dll

**Comment by sasumner** [comment]
>The scintilla commands SCI_STUTTEREDPAGEUP and SCI_STUTTEREDPAGEDOWN used to move the cursor to the first/last visible line in the current view

And they still do.

>Repeated invocation did not move any further. 
>Today I discovered that the behaviour has changed.

Can you cite a version of Notepad++ where repeated invocation did not move any further?

>That's what happens when pressing Ctrl+PgUp/PgDown in any recent version of Visual Studio.

Notepad++ behavior does not necessarily duplicate Visual Studio behavior.

Note:  This is purely Scintilla behavior -- Notepad++ itself does nothing with these commands.

**Comment by ygoe** [comment]
I'm not sure about the repeated invocation.

But the first invocation for SCI_STUTTEREDPAGEUP has certainly changed from a previous version. It no longer moves the cursor to the first visible line without scrolling. I don't have a release archive here, so I can just refer to when #1478 was current when I confirmed its behaviour. That must have been version 6.8. I would not confirm its function in its current state.

**Comment by sasumner** [comment]
> It no longer moves the cursor to the first visible line without scrolling

For me, if the caret is on any line except the first visible line, it never scrolls (or at least I haven't found a scenario where it will scroll).

**Comment by ygoe** [comment]
Hm, I cannot reproduce the issue anymore now. Something must have been in an inconsistent state yesterday. I did not restart Notepad++ since then but I have closed the document I observed this in.
