### ISSUE TITLE
[Release] Notepad++ 7.9.3 Release Uses MD5 SUM

### ISSUE THREAD

**Issue by aaronhatesregex** [notepad-plus-plus/notepad-plus-plus#9509]
[Latest release](https://github.com/notepad-plus-plus/notepad-plus-plus/releases/tag/v7.9.3) (7.9.3) should use sha256sum instead of md5, the PGP signature does match though.

**Comment by donho** [comment]
@aaronhatesregex 
Thank you for your heads up.

It's fixed now.
