### ISSUE TITLE
Move "Set Save dialog file extension filter to *.*" pref. setting to the SaveAs dialog

### ISSUE THREAD

**Issue by sasumner** [notepad-plus-plus/notepad-plus-plus#9515]
### Description of the Issue

Pursuant to the direction [HERE](https://github.com/notepad-plus-plus/notepad-plus-plus/pull/9328#issuecomment-757176413) and [HERE](https://github.com/notepad-plus-plus/notepad-plus-plus/pull/9328#issuecomment-761301587), let's move this Preference setting:

![image](https://user-images.githubusercontent.com/30118311/107959867-ed68fb80-6f71-11eb-97c4-1456accee8b9.png)

to be on the _SaveAs_ dialog itself, appearing in a similar manner as the _Save Folder as Workspace_ checkbox when one does a _File_ > _Save Session..._ :

![image](https://user-images.githubusercontent.com/30118311/107960126-3a4cd200-6f72-11eb-85e0-f0cee97a1719.png)

Exact text for this that should be shown for this on the _SaveAs_ dialog is TBD.  The existing text from the Preferences area is perhaps a bit too long to use.

### Debug Information
Notepad++ v7.9.3   (32-bit)
Build time : Feb 14 2021 - 03:12:31
Path : C:\.........\npp.portable\notepad++.exe
Admin mode : OFF
Local Conf mode : ON
OS Name : Windows 10 Enterprise (64-bit) 
OS Version : 1909
OS Build : 18363.1316
Current ANSI codepage : 1252

**Comment by sasumner** [comment]
@mere-human Still interested in being assigned this task?

**Comment by mere-human** [comment]
Sure, I can handle it.

**Comment by sasumner** [comment]
Oops, assigned myself. :-P

**Comment by mere-human** [comment]
How about something like this?
![image](https://user-images.githubusercontent.com/9664141/112138768-942c6180-8bda-11eb-9a41-83e7b8ff4692.png)

Video:
https://user-images.githubusercontent.com/9664141/112138360-18cab000-8bda-11eb-9123-1c49bfb12cd5.mp4

1. Should the last checked file type be remembered when toggling the checkbox off?
2. Should the value of the checkbox be saved? 
Now it is saved. I use `_setSaveDlgExtFiltToAllTypes`:
https://github.com/notepad-plus-plus/notepad-plus-plus/blob/master/PowerEditor/src/Parameters.h#L818
3. The text currently is `Always prompt with *.*`.

**Comment by sasumner** [comment]
>Should the last checked file type be remembered when toggling the checkbox off?

No.

>Should the value of the checkbox be saved?

Yes.  Definitely.

>The text currently is `Always prompt with *.*`

It's difficult to have great text here and keep it reasonably short.
Obviously it can be shorter than when it is in the _Preferences_ section, because here we have the benefit of context.

**Comment by mere-human** [comment]
> Only because the original extension remains on the _File name_ (.hs in the video).

I haven't fixed that yet.
But yes, if the last selected type is remembered, then the extension should be changed too.
When toggling the checkbox on, the extension shouldn't be removed, I suppose.

**Comment by sasumner** [comment]
What do you think about changing the text to `Remember Save-as-type as *.*` (or similar) and then have it be only an "on entry" thing?  Meaning nothing needs to happen to the current invocation of the dialog when user ticks it on or ticks it off.  It only does something when the dialog is being set up on the following invocation.

**Comment by mere-human** [comment]
> have it be only an "on entry" thing? Meaning nothing needs to happen to the current invocation of the dialog when user ticks it on or ticks it off. It only does something when the dialog is being set up on the following invocation.

Then I why should it be in the dialog itself if the checkbox doesn't affect the dialog?

**Comment by mere-human** [comment]
I had another option: name it "Add extension automatically" which is ON by default. If OFF, then it wouldn't add any extension and the user must add it manually and the file type is set to *.*.

**Comment by sasumner** [comment]
>Then why should it be in the dialog itself if the checkbox doesn't affect the dialog?

As stated, THIS makes perfect sense to me:  _...the text to 'Remember Save-as-type as \*.\*' (or similar) and then have it be only an "on entry" thing_.
But you've shown that you don't like my user interface design ideas, so...  :-)

So, go your own way; it's your issue and future PR.

**Comment by pryrt** [comment]
I see that you've got an implementation now... but with the most recent user-confused-by-automatic-extensions-or-not discussion in the Forum, Alan [proposed the idea](https://community.notepad-plus-plus.org/post/64685) of a three-way option.  Given that some users will always want full control of the extension, some will want a typed extension to override a default but want a default if they don't type one, and some want the default to always be appended no matter what, that might be the only way to make everybody happy.

**Comment by mere-human** [comment]
I'm duplicating the idea here just for the reference:

- never auto-add anything (I guess equivalent to the current “…filter to *.*” ticked)
- always add the “filter type” extension (AFAIK no current equivalent exists)
- do the “natural” thing (I guess equivalent to the current “…filter to *.*” unticked)

For me the current behavior (as well as the new one introduced in #9732) is fine.
But if it could help somebody, then let's see what can be done.
As I can see it:
1. A drop-down in preferences with options like this:
`Append file extension:`
`- default (get from file type)`
`- never`
`- always`
2. An equivalent but in the Save As dialog itself:
![image](https://user-images.githubusercontent.com/9664141/113766316-f1b9c580-9725-11eb-9edb-13202ac38df6.png)
I, personally, don't like it - too messy and the white text background. I've not figured out yet how to fix that background.
3. Append the file extension as it was in 7.9.1 like it is described [here](https://community.notepad-plus-plus.org/topic/20994/7-9-5-not-appending-extension-to-files-with-period-in-name/17?_=1617735974719)

**Comment by donho** [comment]
"Add extension automatically" is good. It could be:
"Add file ext. automatically"
to make it a little bit shorter and more clear.
Term as in Preferences:
![image](https://user-images.githubusercontent.com/90293/113867856-510fe800-97af-11eb-9bbc-9c9faa1e2114.png)

> I, personally, don't like it - too messy and the white text background. I've not figured out yet how to fix that background.

Agree. 
By reading the provided thread quickly,  the user wants `myFile.123` could be saved as `myFile.123.txt` (which is old behaviour). But the 3 options are not clear (to new users) at all. 
Let's keep the current implementation in v7.9.5 and add checkbox so if user choses `*.*` for adding what.extension.they.want. Life is already complicated, we won't make it more complicated with our save as dialog.

**Comment by sasumner** [comment]
>By reading the provided thread quickly

I don't think one can grasp the enormity of the problem by doing this.

>Life is already complicated, we won't make it more complicated with our save as dialog.

I think we are too late on that.  :-)

**Comment by donho** [comment]
@sasumner 
> I don't think one can grasp the enormity of the problem by doing this.

What's your opinion about this subject then?

**Comment by mere-human** [comment]
> Let's keep the current implementation in v7.9.5 and add checkbox so user can choose `*.*` for adding

Do you mean another checkbox in Preferences?

**Comment by sasumner** [comment]
>What's your opinion about this subject then?

Sadly, anymore this thing just confused me.

**Comment by donho** [comment]
@mere-human 
I mean let's keep working on your implementation:
https://user-images.githubusercontent.com/9664141/112138360-18cab000-8bda-11eb-9123-1c49bfb12cd5.mp4

**Comment by mere-human** [comment]
> By reading the provided thread quickly, the user wants `myFile.123` could be saved as `myFile.123.txt` (which is old behaviour). But the 3 options are not clear (to new users) at all.

What about this? Maybe, it's not related or should be implemented separately (should it?).
I have no idea (yet) how to make it better to make everyone happy.

**Comment by mere-human** [comment]
> and some want the default to always be appended no matter what

I think, this will not be fixed in #9732.
I don't have a clear vision as of how to implement it and make everyone happy.
I don't want to overcomplicate things and introduce even more bugs.

If the feature is really has significant value, we could reiterate on it later.
