### ISSUE TITLE
Lexer plugin is sorted unconventionally in language menu.

### ISSUE THREAD

**Issue by Ekopalypse** [notepad-plus-plus/notepad-plus-plus#9516]
Currently, a lexer from a plugin is added to the language menu in an unconventional way.
When the name of the lexer comes before the “normal text” lexer, from the alphabetical point of view, it appears before “normal text”, but when it comes after that, it appears below it, but inside the Builtin lexers. Example see nim and vlang lexer from the image below.

![image](https://user-images.githubusercontent.com/47723516/107979138-51191600-6fbe-11eb-90a2-d9ab5094aa19.png)

### Expected Behavior
Either external lexers should appear within the sorting of the null lexer or within the builtin lexers

### Actual Behavior
Some here some there

### Debug Information
Notepad++ v7.9.3   (64-bit)
Build time : Feb 14 2021 - 03:15:58
Path : D:\Tests\npp\_latest\x64_clean\notepad++.exe
Admin mode : OFF
Local Conf mode : ON
OS Name : Windows 7 Professional (64-bit) 
OS Build : 7601.24546
Current ANSI codepage : 1252
Plugins : BetterMultiSelection.dll mimeTools.dll NppConverter.dll NppExec.dll NppExport.dll nppnim.dll PythonScript.dll VLang.dll

**Comment by donho** [comment]
@Ekopalypse 
Could you indicate where can we download nppnim.dll & VLang.dll ?

**Comment by Ekopalypse** [comment]
@donho 
You can get the VLang lexer from [here](https://github.com/Ekopalypse/NppVLexer/releases)
and instead of using nppnim you can install the GEDCOM lexer via the plugin admin.

Notepad++ v8.5.3   (64-bit)
Build time : May 15 2023 - 06:09:36
Path : D:\Tests\npp\853\x64\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : ON
Cloud Config : OFF
OS Name : Windows 10 Pro (64-bit)
OS Version : 22H2
OS Build : 19045.2728
Current ANSI codepage : 1252
Plugins : 
    GedcomLexer (0.5.0.170)
    mimeTools (2.9)
    NppConverter (4.5)
    NppExport (0.4)
    PythonScript (3.0.16)
    VLang (0.3)


![image](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/47723516/8ba7eba2-2387-491a-9ad8-d3bdda277b41)

**Comment by donho** [comment]
Thank you @Ekopalypse !
