### ISSUE TITLE
Notepad++ 7.9.3.0 aborting on load with .NET clr.dll

### ISSUE THREAD

**Issue by allenatdecisiv** [notepad-plus-plus/notepad-plus-plus#9518]
### Description of the Issue
Notepad++ 7.9.3.0 doesn't run after an upgrade from 7.9.2.0.

### Steps to Reproduce the Issue
1.  Install Notepad++ 7.9.3.0
2.  Run/load Notepad++ 7.9.3.0

### Expected Behavior
To have Notepad++ load so I can use it.

### Actual Behavior
Nothing. Notepad++.exe shows up Task Manager then disappears quickly.

### Debug Information
I can't get any debug information from Notepad++.

Here's what's in my Application Event Log:
```
Faulting application name: notepad++.exe, version: 7.9.3.0, time stamp: 0x602887ca
Faulting module name: clr.dll, version: 4.8.4300.0, time stamp: 0x5f7e61bb
Exception code: 0xc0000005
Fault offset: 0x004d4e0a
Faulting process id: 0x5bcc
Faulting application start time: 0x01d703ca8c05f38f
Faulting application path: C:\Program Files (x86)\Notepad++\notepad++.exe
Faulting module path: C:\Windows\Microsoft.NET\Framework\v4.0.30319\clr.dll
Report Id: d9ad7c79-cf28-449d-a9c3-11af60f768d1
Faulting package full name: 
Faulting package-relative application ID: 
```

**Comment by mere-human** [comment]
What OS version are you using?

**Comment by sasumner** [comment]
@allenatdecisiv SessionManager plugin?

**Comment by allenatdecisiv** [comment]
Whoops, sorry 'bout that.
```
> ver
Microsoft Windows [Version 10.0.19042.804]
```

from Settings/About:
```
Edition	Windows 10 Pro
Version	20H2
Installed on	‎6/‎10/‎2020
OS build	19042.804
Experience	Windows Feature Experience Pack 120.2212.551.0
```

**Comment by allenatdecisiv** [comment]
@sasumner,

No. Here's my plugins:

AutoSave 1.6
Compare 2.0.1
DSpellCheck 1.4.20
Explorer 1.9.3
GitSCM 1.4.4.2
HEX-Editor 0.9.8
JSON Viewer 1.40
Light Explorer 2
MarkdownViewer++ 0.8.2
Mime tools 2.5
Npp Converter 4.2.1
NppExport 0.2.9
NppFTP 0.29.7
NppGist 1.4.0.27
NppJumpList 1.2.2
PythonScript 1.5.4
Save as admin 1.0.195
Spell-Checker 1.3.3
TakeNotes 1.2
TextFX Characters 0.2.6
ToolBucket 1.10.6622.41336


I'll check but once I determined it wasn't loading, I then fell back to running it from the Command Prompt with `notepad++.exe -Nosession -noplugins` and it still didn't load/run.

I've gone back to Notepad++ 7.9.2.0 (x86/32-bit installer).

**Comment by sasumner** [comment]
Damn, sorry.  I meant _Save as admin_ , not _Session Manager_ !
_Save as admin_ is very likely the problem.

**Comment by allenatdecisiv** [comment]
Yep, @sasumner. Thanks!

This is also a dupe of https://github.com/notepad-plus-plus/notepad-plus-plus/issues/9514

**Comment by donho** [comment]
User should be educated to provide Debug Info, if they don't read while creating the issue:
```
### Debug Information
<!--- In your Notepad++, click on the "?" menu (found to the right of "Window" in the menu bar) -->
<!--- In the menu that drops down, choose "Debug Info..." -->
<!--- A message box will open detailing specifics about your Notepad++ version, plugins, etc. -->
<!--- CLICK ON THE BLUE LINK with the text "Copy debug info into clipboard" -->
<!--- Do a PASTE HERE -->
```

**Comment by sasumner** [comment]
@donho said:

>User should be educated to provide Debug Info...

Normally I fully agree.
But, in this case perhaps we can be lenient, as user can't even start Notepad++ in order to get a copy of the debug info.
Maybe we need something that says if they can't start to get the debug info, they should start with no plugins.

**Comment by allenatdecisiv** [comment]
...and the user started Notepad++ via the Command Prompt with `-noplugins`, which would lead a user to assume that any and all plugins would not be loaded/used on boot up? Does `-noplugins` not do that?

If Notepad++ _had_ loaded with `-noplugins`, I would have known precisely what to debug and how to fix it. I wouldn't have bugged you fine folks with a high signal-to-noise ticket.

@donho, respectfully, I _did read_ the ticket template, but the directions assumed a state that wasn't possible (a point made by @sasumner). What's an end-user to do then?

**Comment by donho** [comment]
@allenatdecisiv 
Indeed, if your Notepad++  cannot be launched, you cannot provide the debug info - my bad. Sorry for this impertinent remark.
