### ISSUE TITLE
Tab Bar - Read-Only (show status)

### ISSUE THREAD

**Issue by Eld0r** [notepad-plus-plus/notepad-plus-plus#952]
A dark grey Symbol for inactive Read-Only Tabs would be nice

actual Symbols
- light grey, for active Read-Only Tabs
- light blue, for active Tabs
- dark blue, all inactive Tabs (no difference for Read-Only Tabs).

**Comment by donho** [comment]
Unfortunately, the color of icon for inactive bar is rendered by system, but Notepad++.
