### ISSUE TITLE
Printing without line numbers prints them anyways

### ISSUE THREAD

**Issue by odinian** [notepad-plus-plus/notepad-plus-plus#9521]
### Description of the Issue
When printing with the option is setting not to print line numbers, they are printed anyways

### Steps to Reproduce the Issue

1. open settings: preferences
2. Click Print on the left
3. Ensure "Print line number" is no checked
4. note: that should be "Print Line Numbers"  - minor typo
5. Close the settings
6. print a document

### Expected Behavior
No line numbers on the printed page when the settings for Print Line Number is not checked

### Actual Behavior
Line numbers are printed

### Debug Information
Notepad++ v7.9.2   (64-bit)
Build time : Dec 31 2020 - 04:01:34
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS Name : Windows 10 Pro (64-bit) 
OS Version : 2009
OS Build : 19042.804
Current ANSI codepage : 1252
Plugins : mimeTools.dll nppAutoDetectIndent.dll NppConverter.dll NppExport.dll Python Indent.dll PythonScript.dll Remove Duplicate Lines.dll _CustomizeToolbar.dll

**Comment by donho** [comment]
Fixed in v7.9.3

**Comment by odinian** [comment]
confirmed. thanks. The margins feature isn't working either. Should I open a new issue for that?
