### ISSUE TITLE
nppSaveAsAdmin prevents new portable 7.9.3 from opening.

### ISSUE THREAD

**Issue by DanaMW** [notepad-plus-plus/notepad-plus-plus#9522]
After I updated my NPP to the new Portable 7.9.3 it refused to open. Upon testing the culprit seems to be nppSaveAsAdmin plugin. After removing that plug in it worked again. Triple checked it was the bad actor and it was was was,. Thank you for your work and forgive me if this is not the place to make this claim.
In case anyone else has this problem I just deleted [nppsaveasadmin] folder in the plugin folder and it ran.

**Comment by allenatdecisiv** [comment]
Hi @DanaMW,

Your ticket is a dupe of:
https://github.com/notepad-plus-plus/notepad-plus-plus/issues/9514
https://github.com/notepad-plus-plus/notepad-plus-plus/issues/9518
(so maybe close yours?)

A ticket for upstream plugin author/project is here:
https://github.com/Hsilgos/nppsaveasadmin/issues/24
(in case you want to follow)

**Comment by DanaMW** [comment]
My apologizes. Backing out the door,
