### ISSUE TITLE
Demote the Notepad++ v7(.0.0) download links

### ISSUE THREAD

**Issue by bersbersbers** [notepad-plus-plus/notepad-plus-plus#9523]
It is great that Notepad++ offers an archive of old versions to download (especially for future XP users, I guess). But:

### Description of the Issue
I accidentally downloaded and installed v7.0.0 this morning because it the most prominently featured sub-link on Google.

### Steps to Reproduce the Issue
![image](https://user-images.githubusercontent.com/12128514/108019206-03ca9200-701a-11eb-88c5-d86beaf35f2c.png)

Link goes to https://notepad-plus-plus.org/downloads/v7.0/, which says "Notepad++ 7" without a subversion throughout. I believe it's not crazy to believe that you are getting an up-to-date version here. Yes, there's release date, but even if I notice it - how can I know this is the most current version? It may be obvious now, but maybe it won't for 8.0.1 after 8.0.0.

### Expected Behavior
- If you can, you might change what Google shows as the first sub-link.
- You might also rename the v7 page to v7.0.0 to show people is not the most current version.
- Maybe create a "latest" subpage which you link to throughout the page to increase its rank. 
- Maybe mark older download pages with visible notes such as "This is not the most current version - find it here instead."

**Comment by sasumner** [comment]
>I accidentally downloaded and installed v7.0.0 this morning because it the most prominently featured sub-link on Google.

Umm, don't use Google to find Notepad++ versions.  Go to the Notepad++ home page.

>you might change what Google shows as the first sub-link.

Do you have suggestions on how to do this?

**Comment by bersbersbers** [comment]
> > I accidentally downloaded and installed v7.0.0 this morning because it the most prominently featured sub-link on Google.
> 
> Umm, don't use Google to find Notepad++ versions. Go to the Notepad++ home page.

I will let you think a bit about this.

> > you might change what Google shows as the first sub-link.
> 
> Do you have suggestions on how to do this?

My bad - this used to be possible, but apparently that option is now gone:
https://searchengineland.com/google-search-console-removes-sitelinks-demotion-feature-261002

Do you have any reaction with regard to my other suggestions?

> > - You might also rename the v7 page to v7.0.0 to show people is not the most current version.
> > - Maybe create a "latest" subpage which you link to throughout the page to increase its rank.
> > - Maybe mark older download pages with visible notes such as "This is not the most current version - find it here instead."

**Comment by sasumner** [comment]
>I will let you think a bit about this.

I'm not sure what more there is to think about.
Sure, use google to find the Notepad++ home page.
But if you use google to do your thinking for you (to tell you what to download from the internet), you are going to be in a world of hurt.

>You might also rename the v7 page to v7.0.0 to show people is not the most current version.

>Maybe mark older download pages with visible notes such as "This is not the most current version - find it here instead."

I suppose this could be done to a previous version when a new version is released.
Going back now to do it on all previous versions would be a lot of work for someone.

>Maybe create a "latest" subpage which you link to throughout the page to increase its rank.

It could be done.
