### ISSUE TITLE
Feature Request: Move tab to 'end' of the tabs

### ISSUE THREAD

**Issue by ggnabasik** [notepad-plus-plus/notepad-plus-plus#9525]
Would like to have an option on the right/click on a tab to move the selected file to the 'end' of the tabs for easy access.  i often find myself having 100 files open and when I click on the file from the project folder view it jumps to the middle of the tabs where I last opened it.  i have to close it and then re-open it, losing my spot in the file, in order to group the 3 or 4 files I'm working with at that time so i can easily jump between them.

**Comment by sasumner** [comment]
So drag-and-drop of tabs is a bit "shaky", but it seems like it would work for such a need?

To each his own, but is it practical to have 100 files open? (no answer needed)

**Comment by wonkawilly** [comment]
I like the idea to have two right click commands one to move the tab to the end and one command to move it to the start in just a click

**Comment by sasumner** [comment]
Here's a PythonScript that, when run, will move the currently-active tab to the right-most position in the collection of tabs:

```
from Npp import notepad

curr_view = notepad.getCurrentView()
curr_index = notepad.getCurrentDocIndex(curr_view)
count = 0
for (filename, _, _, view) in notepad.getFiles():
    if view == curr_view: count += 1
for _ in range((count - 1) - curr_index):
    notepad.menuCommand(MENUCOMMAND.VIEW_TAB_MOVEFORWARD)
```

Obviously to use the script you'd have use the PythonScript plugin...

**Comment by KnIfER** [comment]
What about a quick access entry to the multiline mode? In multiline mode you can drag your tab anywhere and in my [implementation](https://github.com/KnIfER/Textrument/commit/f178cf8b0bf5784e7c5a555f690aece3b4ab288a), when you switch back to the single line mode, the current tab would be centered in the tabbar  automatically. 

Something like this : 

Use hot key (ctrl+shift+s) to open the settings menu, where resides some quick access entry.

![quick_settings_menu](https://user-images.githubusercontent.com/11593903/110232905-20e0e980-7f64-11eb-8144-deb1465532c4.png)

One good point of this ***quick settings menu*** is that it is invoked as a popup around the mouse cursor and you can still acess it in the fullscreen mode.

Here is it in action with 100 files opened : [---link---](https://drive.google.com/file/d/1M01Xg7_8Tt4RRCxlhalI5g2isCVAeKUR/view?usp=sharing)

**Comment by pchris7489** [comment]
> Here's a PythonScript that, when run, will move the currently-active tab to the right-most position in the collection of tabs:
> 
> ```
> from Npp import notepad
> 
> curr_view = notepad.getCurrentView()
> curr_index = notepad.getCurrentDocIndex(curr_view)
> count = 0
> for (filename, _, _, view) in notepad.getFiles():
>     if view == curr_view: count += 1
> for _ in range((count - 1) - curr_index):
>     notepad.menuCommand(MENUCOMMAND.VIEW_TAB_MOVEFORWARD)
> ```
> 
> Obviously to use the script you'd have use the PythonScript plugin...

Working, but it would be good to have the feature integrated in Npp. When using Npp to devellop its easy to have 100 tabs open and this feature would be useful.

**Comment by freezer2022** [comment]
> @ggnabasik : Move tab to 'end' of the tabs 

> https://github.com/notepad-plus-plus/notepad-plus-plus/issues/9525#issuecomment-780041923
> @wonkawilly :  I like the idea to have two right click commands one to move the tab to the end and one command to move it to the start in just a click

Basic features in all internet browsers...just like "Clone tab" : 
`https://github.com/notepad-plus-plus/notepad-plus-plus/issues/4858`

**Comment by pchris7489** [comment]
In the latest version of Notepad++ to this date, the v8.6.1, the "Move to start" and "Move to end" is broken while very much welcome. In fact when there are many tabs open, it will move the tab "one by one" until the start or until the end of the list, and while doing this operation the Notepad++ will lock it self  out completely. Works correctly for few tabs. 

> Here's a PythonScript that, when run, will move the currently-active tab to the right-most position in the collection of tabs:
> 
> ```
> from Npp import notepad
> 
> curr_view = notepad.getCurrentView()
> curr_index = notepad.getCurrentDocIndex(curr_view)
> count = 0
> for (filename, _, _, view) in notepad.getFiles():
>     if view == curr_view: count += 1
> for _ in range((count - 1) - curr_index):
>     notepad.menuCommand(MENUCOMMAND.VIEW_TAB_MOVEFORWARD)
> ```
> 
> Obviously to use the script you'd have use the PythonScript plugin...

This method is instanteneous irrelevant to the number or tabs open. There is a LUA version as well

**Comment by alankilborn** [comment]
> when there are many tabs open

>works correctly for few tabs

Quantify?
