### ISSUE TITLE
Opening files from UNC path using File Dialog fails - NPP 7.9.3

### ISSUE THREAD

**Issue by jonnyt1978** [notepad-plus-plus/notepad-plus-plus#9527]
### Description of the Issue
Error when trying to open a file from a network UNC. Entering full UNC path of file or folder in 'File name:' text box produces error:

Path does not exist.
Please check the path and try again.

It appears to 'trim' off the first backslash from the beginning of the path

### Steps to Reproduce the Issue

1. Use built-in NPP File Menu -> Open file dialog
2. Type - or copy/paste - UNC path of file/folder into 'File name:' text box
3. Error appears as a pop-up

### Expected Behavior
Able to open UNC folder paths and files using this method in previous versions.

**Comment by sasumner** [comment]
Verified, on:

Notepad++ v7.9.3   (64-bit)
Build time : Feb 14 2021 - 03:15:58
Path : C:\............\npp.7.9.3.portable.x64\notepad++.exe
Admin mode : OFF
Local Conf mode : ON
OS Name : Windows 10 Enterprise (64-bit) 
OS Version : 1909
OS Build : 18363.1316
Current ANSI codepage : 1252
Plugins : mimeTools.dll NppConverter.dll NppExport.dll 

Simplest (folder) test I could think of:

![image](https://user-images.githubusercontent.com/30118311/108103205-99d0dd80-7057-11eb-85ac-aa880d74dd4d.png)

Results in:

![image](https://user-images.githubusercontent.com/30118311/108103289-bb31c980-7057-11eb-8375-2f25e326ac8f.png)

Note that it has removed ONE of the leading `\` -- interesting!

Same test on 7.9.2 opens the folder:

![image](https://user-images.githubusercontent.com/30118311/108103724-562aa380-7058-11eb-9bf0-1fc558e33dad.png)

**Comment by sasumner** [comment]
Why is it so hard for issue creators to supply their own _Debug Information_ ???

**Comment by jonnyt1978** [comment]
I humbly apologies, I am a newbie at this. I thought I had provided enough information for a bug to be confirmed.

**Comment by sasumner** [comment]
@jonnyt1978 It's not just you, and there was enough info for it to be confirmed in this case.
But, sometimes things come back to developers wondering "which Windows was this on?" or "which plugins does user have?", etc.

**Comment by sasumner** [comment]
@mere-human Another one for you?

You are really getting a nice "contributor's-welcome" with the open/save dialogs change, eh?

**Comment by mere-human** [comment]
> Another one for you?

Yep, give it to me.

**Comment by donho** [comment]
@sasumner 
Should `\\127.0.0.1\c$` work on any computer without any web server running on the machine?

**Comment by sasumner** [comment]
>Should \\127.0.0.1\c$ work on any computer without any web server running on the machine?

Not sure.
It was just the quickest thing I could think of as a UNC test that I could post here (it would do little good to post as examples something other people could not try).

**Comment by jonnyt1978** [comment]
Hello @sasumner, @donho 

I've just tried on a atandalone (Workgroup not Domain) Windows 10 Pro 20H2 X64 PC.

On NPP++ 7.9.1 (X64) I can indeed put: \\127.0.0.1\c$ in the 'File name' text box of the Open file dialog, press Enter and it browse to the C$ share.

On NP++ 7.9.3 (X64 Build Time Feb 14 2021 - 03:15:58) it fails with the error described above.

**Comment by sasumner** [comment]
@jonnyt1978 If you have interest in seeing if it has been fixed now you can try following the "current build" testing instructions (beta) that are [HERE](https://github.com/notepad-plus-plus/notepad-plus-plus/issues/9493#issuecomment-781344297).

**Comment by jonnyt1978** [comment]
> @jonnyt1978 If you have interest in seeing if it has been fixed now you can try following the "current build" testing instructions (beta) that are [HERE](https://github.com/notepad-plus-plus/notepad-plus-plus/issues/9493#issuecomment-781344297).

Just tested NP++ 7.9.3 debug release (7.9.5246) frrom the link you kindly provided, and can confirm the issue is resolved - I was able to enter "\\127.0.0.1\c$" in the 'File name' text box of the Open file dialog, press Enter and it browse to the C$ share.

**Comment by sasumner** [comment]
@jonnyt1978 Thanks for testing!

**Comment by mere-human** [comment]
I see I'm a bit late here.
But just for the reference, here is a good explanation of supported path formats on Windows (including UNC) with examples:
https://docs.microsoft.com/en-us/windows/win32/fileio/naming-a-file
https://docs.microsoft.com/en-us/dotnet/standard/io/file-path-formats

**Comment by mere-human** [comment]
Thank you all for testing and reviewing!

**Comment by sasumner** [comment]
@mere-human 

Looking at this link you provided:
https://docs.microsoft.com/en-us/dotnet/standard/io/file-path-formats
I scroll down to where it says: "Example: Ways to refer to the same file"

So then I create a test file on W: drive:

![image](https://user-images.githubusercontent.com/30118311/108760533-c71c0080-751b-11eb-9ae4-635ed54ab271.png)

And using the exe built from this PR I try opening the following:

```
w:\temp\test-file.txt
\\127.0.0.1\w$\temp\test-file.txt
\\LOCALHOST\w$\temp\test-file.txt
\\.\w:\temp\test-file.txt
\\?\w:\temp\test-file.txt
\\.\UNC\LOCALHOST\w$\temp\test-file.txt
```

The first three work fine to open the file, but the last 3 give me errors:

![image](https://user-images.githubusercontent.com/30118311/108760817-21b55c80-751c-11eb-9262-25576f7d9d67.png)

![image](https://user-images.githubusercontent.com/30118311/108760855-2ed24b80-751c-11eb-97cb-73e2fa125ef0.png)

![image](https://user-images.githubusercontent.com/30118311/108760896-3bef3a80-751c-11eb-9f29-a5374cafae86.png)

Now, I would never open a file from my local W: drive like these examples, but as you provided the link, I wonder what you think about this?

**Comment by mere-human** [comment]
> ```
> w:\temp\test-file.txt
> \\127.0.0.1\w$\temp\test-file.txt
> \\LOCALHOST\w$\temp\test-file.txt
> \\.\w:\temp\test-file.txt
> \\?\w:\temp\test-file.txt
> \\.\UNC\LOCALHOST\w$\temp\test-file.txt
> ```
> 
> 
> The first three work fine to open the file, but the last 3 give me errors:

Probably this is a legacy DOS-style path that has a limited support despite being documented.
Or maybe, it has a different use case.
I checked it in Explorer and Microsoft Notepad. It doesn't work (all 3 cases):
![image](https://user-images.githubusercontent.com/9664141/108764724-a7a4c800-755b-11eb-81ec-f14dce1a0ff0.png)

**Comment by jonnyt1978** [comment]
Issue described in this ticket and #9582 remains

Steps to reproduce:
as described by @notYetLost in #9582 

Debug Information
Notepad++ v7.9.4   (64-bit)
Build time : Mar 15 2021 - 01:03:10
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS Name : Windows 10 Pro (64-bit) 
OS Version : 2009
OS Build : 19042.867
Current ANSI codepage : 1252
Plugins : mimeTools.dll NppConverter.dll NppExport.dll
