### ISSUE TITLE
Npp 793 Plugin admin doesn't work

### ISSUE THREAD

**Issue by wonkawilly** [notepad-plus-plus/notepad-plus-plus#9528]
Please have a look at the following video that shows what happens (or doesn't happens O_o) with **plugin admin**. The **old plugin manager** instead, still works great.

https://user-images.githubusercontent.com/34818345/108104697-e7673d80-708b-11eb-93d1-e0a538d55949.mp4

### Description of the Issue

Npp Plugin admin doesn't work properly: it doesn't allow to install new plugins and also it is not possibile to resize the dialog but its size is fixed.

### Steps to Reproduce the Issue

1. just downloaded from internet, started up and tried to install a bunch of plugins and it doesn't work: n++ closes and installation performed by plugin admin doesn't even start downloading plugin files

### Expected Behavior

To have plugin downloaded and installed

### Actual Behavior

Doesn't download and doesn't install any plugin

### Debug Information

n++793 just downloaded the zip file, 32bit from website and tested right away

**Comment by mere-human** [comment]
Please, provide the debug info of your install (Menu: _? > Debug_ info then copy and paste here).
Ensure you have enough privileges to save to the plugin directory.
Also, do you have the _Save As Admin_ plugin installed by any chance?

**Comment by wonkawilly** [comment]
> Please, provide the debug info of your install (Menu: _? > Debug_ info then copy and paste here).
> Ensure you have enough privileges to save to the plugin directory.
> Also, do you have the _Save As Admin_ plugin installed by any chance?

I had just downloaded n++: it has just the default plugins installed. I didn't do anything else: just downloaded the zip, decompressed, and run. Also I've signaled this issue a while ago even for previous n++ versions, practically since plugin admin came out... 

I've run it in both ways normal mode and as administrator. The result is the same: no downloads, no installation: just n++ closes and doesn't even reopen alone: I have to reopen it manually. Also I want to underline that the old Plugin Manager still works great for me: I still use it into n++ v758 with 0 problems.

Notepad++ v7.9.3   (32-bit)
Build time : Feb 14 2021 - 03:12:31
Path : C:\Users\myusername\Desktop\Download n++\npp.7.9.3.portable\notepad++.exe
Admin mode : OFF
Local Conf mode : ON
OS Name : Windows 7 Ultimate (32-bit) 
OS Build : 7601.0
Current ANSI codepage : 1252
Plugins : mimeTools.dll NppConverter.dll NppExport.dll 

Run as administrator dbg info:
Notepad++ v7.9.3   (32-bit)
Build time : Feb 14 2021 - 03:12:31
Path : C:\Users\myusername\Desktop\Download n++\npp.7.9.3.portable\notepad++.exe
Admin mode : ON
Local Conf mode : ON
OS Name : Windows 7 Ultimate (32-bit) 
OS Build : 7601.0
Current ANSI codepage : 1252
Plugins : mimeTools.dll NppConverter.dll NppExport.dll

**Comment by robross0606** [comment]
I found the same thing after upgrading from 7.9.1 to 7.9.3.  Not only did I have to remove all my plugins to get NPP to start, but there is no longer any "Plugin Manager" option:
![2021-02-24 10 28 29](https://user-images.githubusercontent.com/2965467/109023826-1f254500-768b-11eb-9e2e-37491a5fef6c.png)

**Comment by wonkawilly** [comment]
@mere-human 
I don't have NppSaveAsAdmin installed in N++, I don't need it at all

**Comment by ArkadiuszMichalski** [comment]
@wonkawilly What with previouse version, like 7.9.2?

**Comment by wonkawilly** [comment]
> @wonkawilly What with previouse version, like 7.9.2?
 
Same problem.  I suspect the problem is Plugin Admin itself in fact I'm still using Plugin Manager to download and update plugins  (or I do it by hands) and of course I won't upgrade to plugin admin if doesn't work for me.

**Comment by ArkadiuszMichalski** [comment]
Works for me:
```
Notepad++ v7.9.3   (32-bit)
Build time : Feb 14 2021 - 03:12:31
Path : C:\Users\Arek\Desktop\npp.7.9.3.portable\notepad++.exe
Admin mode : ON
Local Conf mode : ON
OS Name : Windows 7 Ultimate (64-bit) 
OS Build : 7601.0
Current ANSI codepage : 1250
Plugins : mimeTools.dll NppConverter.dll NppExport.dll 
```

Some antivirus is not blocking the operation?

**Comment by wonkawilly** [comment]
@ArkadiuszMichalski 
> Works for me:

Good. What can I do in order to make it work for me too?


@ArkadiuszMichalski 
> ```
> Notepad++ v7.9.3   (32-bit)
> Build time : Feb 14 2021 - 03:12:31
> Path : C:\Users\Arek\Desktop\npp.7.9.3.portable\notepad++.exe
> Admin mode : ON
> Local Conf mode : ON
> OS Name : Windows 7 Ultimate (64-bit) 
> OS Build : 7601.0
> Current ANSI codepage : 1250
> Plugins : mimeTools.dll NppConverter.dll NppExport.dll 
> ```
> 
> Some antivirus is not blocking the operation?

No, and also I don't get any notify at all from anything when it happens. Please have a look to the video I published into the opening post of this thread. Thanks.

**Comment by ArkadiuszMichalski** [comment]
It looks like a problem on your side, either system or internet. If you have options, you can:
- check another computer (system) on the same internet. You can also do it using a virtual machine or some live windows. 
- check your computer (where you have a problem) on another internet, even mobile.

Then you could narrow down the area of search that causes this problem.

**Comment by chcg** [comment]
The old pluginManager uses the windows component and settings to access the internet. So if e.g. a poxy is configured that will be used automatically.
For the pluginAdmin and N++ itself https://github.com/notepad-plus-plus/wingup is used which is curl based.

**Comment by wonkawilly** [comment]
---
@ArkadiuszMichalski 
> It looks like a problem on your side, either system or internet. If you have options, you can:
> 
> * check another computer (system) on the same internet. You can also do it using a virtual machine or some live windows.
> * check your computer (where you have a problem) on another internet, even mobile.
> 
> Then you could narrow down the area of search that causes this problem.

In this case my hopes to solve this issue are completely burnt because I don't have enough space on this computer (~ 1.5 GB free space and even less) to install and use a vm and unfortunately I don't have another computer either.
By the way thank you so much for the time you are spending for helping me to solve this issue.

---
@chcg 
> The old pluginManager uses the windows component and settings to access the internet. So if e.g. a proxy is configured that will be used automatically.

I don't have any proxy configured in my computer not in my LAN, but I don't know about my router (which self-configures it self and it is also locked and I can't do much within its firmware, at least not about proxies). I don't even know about my internet service provider: I just believe they have some kind of NAT (maybe?) with a shared IP which is the one all users use to "get out" on the internet,..

---
@chcg 
> For the pluginAdmin and N++ itself https://github.com/notepad-plus-plus/wingup is used which is curl based.

Thank you for the hint: I've read it and I don't know enough about wingup and curl and C/C++ in general to solve the issue: I usually just download N++ unzip it and use it and it just work or not... So why devs don't implement a software that simply works as Plugin Manager does? What is the issue about this way? In fact I'm still using Plugin Manager which never gives a problem not on my systems not on my internet link it just works.
By the way thank you too so much for the time you are spending for helping me to solve this issue.

**Comment by donho** [comment]
@wonkawilly 
Does it work in the v8;2 (the latest version of Notepad++)?

**Comment by alankilborn** [comment]
@donho Didn't you ban "wonkawilly" from here?  If so, I don't think he'll be responding.

**Comment by rimrul** [comment]
There is a comment where you claimed to have banned wonkawilly. https://github.com/notepad-plus-plus/notepad-plus-plus/issues/9627#issuecomment-801585664

**Comment by donho** [comment]
> Didn't you ban "wonkawilly" from here? If so, I don't think he'll be responding.

Trure! Isuue closed.

**Comment by rimrul** [comment]
There are a few more open issues by this user that likely also won't receive any more updates from them.

#5730 and #6008 about the plugin manager

#6010 about the search dialog
