### ISSUE TITLE
Feature enhancement request - Find - Replace dialog enhancement and simplification

### ISSUE THREAD

**Issue by wonkawilly** [notepad-plus-plus/notepad-plus-plus#9529]
If I may ask, I would like to advance to developers a proposal for  Find - Replace dialog enhancement and simplification at the same time. For this purpose please have a look at the image bellow for more clarifications. I tried to make the image self esplicative as I could when editing in a graphic editor.

![Notepad++ Enahanced Find and Replace Dlg](https://user-images.githubusercontent.com/34818345/108108040-5ba3e000-7090-11eb-9970-a6aa661820b1.png)

The image represents a potential final dialog (it is just photoshopped).
As you can see it, this will enhance the features that the dialog offers to users but at the same time it will get rid of the 4 tabs pages and more or less redundant buttons and other controls that are around allowing the final user to keep an eye at a glance on all the options at the same time. Also it is possible to notice a bigger flexibility to face and solve more complex tasks: in fact the basic idea IMHO would be able to handle more powerful find and replace jobs in a single layout. Just some examples:

1. It would allow to exchange **search for** text with **replace with** text content with just a single click on the double arrow button
2. It would allow to include in find (and replace) activities all the files in container directory (or filtered files and directories even with regexs)
3. it would allow to search up or down level and even in in both directions relatively to the indicated current file (or each of all opened files) or the targeted directory allowing to choose how deep the recursion algorithm will dig in the directory structure in up or down  or both directions simultaneously.
4. It would allow to include or exclude Hidden directories and files as well in the find and replace jobs

As highlighted before everything is kept under control in just one view instead of having 4  tab pages as it is now.

One more feature that would be IMHO great to see implemented when possibile, would be the possibility to set in advance multiple (unlimited) find and replace jobs to execute altogether once everything has been set so notepad will do the F&R activities one after the other all at once without further user intervention, kind of "batch or multiple finds and replaces".

Thanks in advance for reading and examining the feasibility of all that. 
Cheers.

**Comment by mere-human** [comment]
Good UI design work.
I personally would add a possibility to hide some of the advanced options not to scare users.
For example, Visual Studio does so:
1. basic UI, collapsed
![image](https://user-images.githubusercontent.com/9664141/108118679-61f18680-70a7-11eb-8092-685a6233e16a.png)
2. advanced options
![image](https://user-images.githubusercontent.com/9664141/108118692-661da400-70a7-11eb-8982-98a8734e926e.png)

**Comment by wonkawilly** [comment]
> Good UI design work.
> I personally would add a possibility to hide some of the advanced options not to scare users.
> For example, Visual Studio does so:
> 
> 1. basic UI, collapsed
>    ![image](https://user-images.githubusercontent.com/9664141/108118679-61f18680-70a7-11eb-8092-685a6233e16a.png)
> 2. advanced options
>    ![image](https://user-images.githubusercontent.com/9664141/108118692-661da400-70a7-11eb-8982-98a8734e926e.png)

I don't know if I like the idea. In first instance it might seem a good idea. But it has very dangerous contraindications: for example the find and replace algorithm can behave oddly because of options that are active/inactive and the user may get more scared about that than the amount of options itself or because of the same thing the user may perform unwanted operations and even dangerous ones: suppose that he performs a "replaces all" job because the option is active (and hidden) and he replaces every occurrence into a lot of files and even directories without truly wanting it.
Maybe it is better to have all options visible (and the dangerous ones even highlighted) so if something is set/not set accordingly with contingent needs can be spotted at a glance before effectively executing the command. This is the major motivation (and not the only one) I'm proposing the elimination of tab pages: to spot everything at a glance.
Also for dangerous operations (ie Replace All, in any of its incarnations) would be a good idea to add a confirmation msgbox before truly performing it, even summarizing in it the dangerous actions that are going to take place in case of confirmation to make aware the user that the algorithm is yes powerful but dangerous at the same time.

Also if you noticed, the UI presented in my op, is much more powerful than the actual one. If Donho and other n++ devs will decide to accept it, it will be able to be a great help for doing complex f/r tasks but at the same time it is very dangerous: the recursion capability to go from current files' directories to respective parent's is a huge enhancement but at the same time it is a huge risk. If set badly it may ruin files that are even in other projects or even in system dir. So that eventual choice must be wisely evaluated because of its power to make huge service to users runs together with a huge risk: With great power comes great responsibility and risks...

**Comment by sasumner** [comment]
@mere-human 

Off-topic, but did you see I sent you an email to the address github shows me for you?  Maybe not an often-checked (or even valid) address for you?  [ If you read it and respond, you'll see how it can also be on-topic to THIS issue. :-) ]

**Comment by mere-human** [comment]
> But it has very dangerous contraindications: for example the find and replace algorithm can behave oddly because of options that are active/inactive and the user may get more scared about that than the amount of options itself

It's worth to have safe defaults then.

> Also if you noticed, the UI presented in my op, is much more powerful than the actual one.

It could be a bit hard to comprehend when there are a lot of details.

**Comment by Uhf7** [comment]
I'm missing the possibility to search through all files contained in a project panel (#8125). Would be be another radio button in the set targets section. Actually, I nearly never search through directories.

**Comment by sasumner** [comment]
@Uhf7 As a contributor of some great things in the past, I'm surprised you haven't offered up your own solution for project-based search.  Is there anything stopping you from doing this (PR for 8125)?  Such as UI design for it (since you commented here about it)?

**Comment by sasumner** [comment]
>1 It would allow to exchange search for text with replace with text content with just a single click on the double arrow button

This individual item was first brought forth by OP in #6010

**Comment by wonkawilly** [comment]
> > 1 It would allow to exchange search for text with replace with text content with just a single click on the double arrow button
> 
> This individual item was first brought forth by OP in #6010

Exactly. Now I'm advancing a more "powerful proposal" incorporating the old one as well, hoping it is appreciated by the community.

**Comment by wonkawilly** [comment]
> > But it has very dangerous contraindications: for example the find and replace algorithm can behave oddly because of options that are active/inactive and the user may get more scared about that than the amount of options itself
> 
> It's worth to have safe defaults then.

Absolutely True.
But defaults are such until changed by the user, and he can forget about changes if not shown at a glance.

> > Also if you noticed, the UI presented in my op, is much more powerful than the actual one.
> 
> It could be a bit hard to comprehend when there are a lot of details.

  Also true. And if needed I can change the image to make the UI more understandable before programmers get in play.

**Comment by wonkawilly** [comment]
> I'm missing the possibility to search through all files contained in a project panel (#8125). Would be be another radio button in the set targets section. Actually, I nearly never search through directories.

Actually I forgot about that possibility: here's the updated version.

![Notepad++ Enahanced Find and Replace Dlg](https://user-images.githubusercontent.com/34818345/108240389-18f30e00-714b-11eb-905f-065fd79074dc.png)


I search through directories a lot and sometimes I miss the possibility to search up targeting parents dir.

**Comment by donho** [comment]
There are some good features in this dialog indeed.
But I'm too simple (not smart enough) to know how to use it.
So let's keep the current UI in Find dialog.

**Comment by wonkawilly** [comment]
@donho 
> There are some good features in this dialog indeed.
> But I'm too simple (not smart enough) to know how to use it.
> So let's keep the current UI in Find dialog.

You underestimate yourself

**Comment by sasumner** [comment]
>So let's keep the current UI in Find dialog.

I totally saw that coming.  :-)
@mere-human : related stuff in upcoming email

**Comment by wonkawilly** [comment]
> > So let's keep the current UI in Find dialog.
> 
> I totally saw that coming. :-)
> @mere-human : related stuff in upcoming email

May ask why?

**Comment by sasumner** [comment]
>May ask why? 

No, private email between devs that have never corresponded privately before.

>Am I doing something wrong?

No.  At least I don't think so.  The way I see it you're a user asking for features -- that's one of the things "issues" are for.

**Comment by wonkawilly** [comment]
> > May ask why?
> 
> No, private email between devs that have never corresponded privately before.
> 
> > Am I doing something wrong?
> 
> No. At least I don't think so. The way I see it you're a user asking for features -- that's one of the things "issues" are for.

Ah ok thank you for the clarification.

**Comment by Suesskirsche** [comment]
There are some good features in this dialog indeed.
   But I'm too simple (not smart enough) to know how to use it.
   So let's keep the current UI in Find dialog.

Sad, I would have preferred the suggested find & replace window instead of the existing one. 


Am 17. Februar 2021 19:52:28 MEZ schrieb Don HO <notifications@github.com>:

**Comment by sasumner** [comment]
>I would have preferred the suggested find & replace window instead of the existing one.

Fantasy is always better than reality.  :-)

**Comment by donho** [comment]
@sasumner 
> Fantasy is always better than reality. :-)

In sexuality yes, but not in computer science, imUo.

**Comment by wonkawilly** [comment]
@donho 
@mere-human 
@sasumner 
@Suesskirsche
@Uhf7 

And everyone else interested to read it, the updated version can be found at #9627.

@donho 
> There are some good features in this dialog indeed.
> **->But I'm too simple (not smart enough) to know how to use it.**
> So let's keep the current UI in Find dialog.

Ok now you know

Cheers

**Comment by wonkawilly** [comment]
I'm really sorry if I'm bothering you all, but maybe the participants to this thread would want to give their opinion about this new and rich proposal about the improvement of the Find and Replace dialog at this link: #9627. Which will be a great improvement and perhaps even a real game changer for all of us that use N++ for more advanced uses than just editing the shopping list.
Please partecipate and ask others to. More opinion are welcome. Thank you all.
