### ISSUE TITLE
Feature Request: Open new blank document AND remember current session

### ISSUE THREAD

**Issue by mja1962** [notepad-plus-plus/notepad-plus-plus#9535]
### Description of the Issue
I'd like the option to launch npp with the current session intact, but ALSO with a new (empty) tab upon launching the program. The new, blank tab should have the focus.

**Comment by sasumner** [comment]
It's a rather specialized need, especially when the solution is to simply press Ctrl+n.

If you feel it is really important, what about a script to do it?

**Comment by mere-human** [comment]
Consider doing the requested feature using a macro or a script (PythonScript) that runs on startup and creates an empty document.
You can go to the community if you need a help with creating such a script https://community.notepad-plus-plus.org/

Another option could be running a Notepad++ with an argument. 
For example, create a file "npp.bat" with a content like "C:\Program Files (x86)\Notepad++\notepad++.exe %AppData%\new.txt" save it and run. 
It will open a Notepad++ with that file and you can resave it with a different name.

**Comment by ony2020** [comment]
> It's a rather specialized need, especially when the solution is to simply press Ctrl+n.
> 
> If you feel it is really important, what about a script to do it?

I also look for this Feature, if I want to take a quick note it is not logical that everytime I open NPP I should click new tab. as for script I do believe @mja1962  already made one.

**Comment by sasumner** [comment]
>for script I do believe @mja1962 already made one

Why do you believe this?
I see no script.
It's traditional that if you script a solution to a problem such as this, that you also return here and post it.

Anyway, something to support this isn't going to be implemented in Notepad++ itself.  Sorry.

**Comment by ony2020** [comment]
> > for script I do believe @mja1962 already made one
> 
> Why do you believe this?
> I see no script.
> It's traditional that if you script a solution to a problem such as this, that you also return here and post it.
> 
> Anyway, something to support this isn't going to be implemented in Notepad++ itself. Sorry.

Sorry,I didn't knew the tradition, Frankly I did not mention it because I dont own it, anyway here it is: 
;=====================================================
;Here's my AHK script, in case anyone cares to use it:
; WIN + n
; Launch Notepad++ with a new tab:
;=====================================================
#n::
{
Run, notepad++
Sleep 200
Send, ^n
return
}
------------------------------------------------------------------------------------------------
another solution is to add notepad++.exe -qtnew to the target properties.

hope one day you implement such normal Feature

**Comment by sasumner** [comment]
>another solution is to add notepad++.exe -qtnew to the target properties.

`-qt` command line argument has to do with "ghost typing"
Not sure how that is relevant here.

**Comment by ony2020** [comment]
> >another solution is to add notepad++.exe -qtnew to the target properties.
> 
> `-qt` command line argument has to do with "ghost typing"
> Not sure how that is relevant here.

In windows when you right click on NPP icon and then you add "-qtnew" in the target properties, whenever you run NPP a new tab will open automatically with the word new in it

**Comment by sasumner** [comment]
>In Windows when you right click on NPP icon and then you add "-qtnew" in the target properties, whenever you run NPP a new tab will open automatically with the word new in it

I see!
That is a nice workaround!

**Comment by mja1962** [comment]
Here's an updated version of the AutoHotkey script I posted earlier; I discovered that depending on your machine, you may need to adjust the "Sleep" value in order to get consistent results:

;=====================================================
; WIN + n
; Launches Notepad++ with a new tab:
;
; AutoHotkey script to open a new tab whenever NPP opens. 
; By Michael Anzalone - Use and distribute freely.
; mja at michaelanzalone dot com
; This is useful when you are on the phone and need to 
; quickly take some notes.
; If NPP is configured to remember the current session, 
; you will also have a new, blank document available
; (with the focus) each time you launch NPP with WIN + n.
; Works whether NPP is already running or not, and 
; whether or not NPP has the focus.
;=====================================================
#n::
{
Run, notepad++
; Choose a "Sleep" value that works best with your machine:
; (A value that is too small can cause undesired results)
; Sleep 200
; Sleep 400
; Sleep 600
  Sleep 800

Send, ^n
return
}

**Comment by donho** [comment]
https://github.com/notepad-plus-plus/notepad-plus-plus/issues/11134#issuecomment-1575226268
