### ISSUE TITLE
Find dialog flickers when Select and Find Next (Ctrl+F3) is pressed first time

### ISSUE THREAD

**Issue by d0vgan** [notepad-plus-plus/notepad-plus-plus#9536]
### Description of the Issue
When Notepad++ is started and Select and Find Next (Ctrl+F3) is pressed for the first time, the Find dialog flickers.

### Steps to Reproduce the Issue
1. Start Notepad++
2. Press Ctrl+F3 - the Find dialog flickers
3. To reproduce it better, open the source file "PowerEditor\src\ScintillaComponent\FindReplaceDlg.cpp", find the method "FindReplaceDlg::create", add `::Sleep(1000);` right after the line `::SetWindowPos(_hSelf, HWND_TOP, rc.left, rc.top, rc.right - rc.left, rc.bottom - rc.top, SWP_SHOWWINDOW);` and rebuild Notepad++.

### Expected Behavior
As Ctrl+F3 performs a "silent search" for a given word, no flickering is expected.

### Actual Behavior
The Find dialogs flickers.

One of possible ways to fix this issue is to extract the 
```
NppParameters& nppParam = NppParameters::getInstance();
NppGUI& nppGUI = const_cast<NppGUI&>(nppParam.getNppGUI());
if (nppGUI._findWindowPos.bottom - nppGUI._findWindowPos.top != 0)  // check height against 0 as a test of valid data from config
{
    RECT rc = getViewablePositionRect(nppGUI._findWindowPos);
    ::SetWindowPos(_hSelf, HWND_TOP, rc.left, rc.top, rc.right - rc.left, rc.bottom - rc.top, SWP_SHOWWINDOW);
    //Sleep(1000);
}
else
{
    goToCenter();
}
```
into a separate method that is called only when `toShow` is `true`.
Such approach, however, adds another problem: the keyboard focus is for some reason "stolen" from Scintilla and does not return back to it. According to my investigations, the focus is "stolen" as the result of calling `_hSelf = ::CreateDialogParam(_hInst, MAKEINTRESOURCE(dialogID), _hParent, dlgProc, reinterpret_cast<LPARAM>(this));` within "StaticDialog::create" (this one is called from the "FindReplaceDlg::create").

**Comment by mere-human** [comment]
This is kind of expected behavior:
> Notepad++ uses a flashing of the Find dialog window and the main Notepad++ window itself (when the Find dialog is not open) to indicate that search text has not been found (or possibly that a Wrap around in the search has occurred).

https://npp-user-manual.org/docs/searching/

There is a related issue about the option to disable the flashing completely #9501

**Comment by sasumner** [comment]
@mere-human 

I think what OP is talking about is when the _Find_ window is created for the very first time.
If that very first time happens to be via a _Select and Find Next_ then the window will "flash up" before being hidden.
I consider this an extremely low-priority thing.

**Comment by d0vgan** [comment]
Exactly, it is about "flashing up" before being hidden.
I do agree it does not seem to be important in terms of functionality. In the same time, user interface is the first thing that users interact with, and it creates first impression and user experience. And a "flashing up" dialog window does not create an impression of a carefully designed program, despite all the years of its development.
