### ISSUE TITLE
Missing space character in string "total documents: "

### ISSUE THREAD

**Issue by RockyTDR** [notepad-plus-plus/notepad-plus-plus#9542]
The string "total documents: " is missing a space at the end of the English translation file (window title)

https://github.com/notepad-plus-plus/notepad-plus-plus/blob/35584b379f017402ab8e8244364400137bb500c0/PowerEditor/src/WinControls/WindowsDlg/WindowsDlg.cpp#L870
https://github.com/notepad-plus-plus/notepad-plus-plus/blob/35584b379f017402ab8e8244364400137bb500c0/PowerEditor/installer/nativeLang/english.xml#L1217

![afbeelding](https://user-images.githubusercontent.com/9828661/108524015-e1ad6a00-72ce-11eb-882d-7c80eb05042b.png)

**Comment by sasumner** [comment]
>missing a space at the end of the English translation file

The space is NOT missing from `english.xml`.
The space should be accounted for in the code itself (if someone bothers to change this).

**Comment by ArkadiuszMichalski** [comment]
I have already forgotten about it https://github.com/notepad-plus-plus/notepad-plus-plus/issues/9455#issuecomment-768574385.
