### ISSUE TITLE
TiXmlBase::StringEqual

### ISSUE THREAD

**Issue by QoL15155** [notepad-plus-plus/notepad-plus-plus#9545]
### Description of the Issue

The parameter's name is "ignoreCase", where in fact it does the opposite. when _ignoreCase_ is on, we don't ignore the case and vice versa. I

That means that in TiXmlNodeA::Identify for instance:
``` c++
const char* xmlHeader = { "<?xml" };
const char* commentHeader = { "<!--" };

if ( StringEqual( p, xmlHeader, true ) )
```
string '<?xml' would be compared as case sensitive, but for  _commentHeader_ on the other hand characters would be lower-cased. (performance)

There are others examples showing that suggest the parameter should be treated in reverse (and not just renamed)

### Steps to Reproduce the Issue

Edit an _xml_ file (langs.xml for example) and change `<?xml` to be `<?XML`. It would parse normally, even though it probably shouldn't.

###  Conclusion

To summerize, I think that either the name should be changed or the logic to avoid confusion. Tracking who calls _StringEqual_ function, suggest the logic is what should be changed in my opinion.

**Comment by donho** [comment]
The issue should be bug report, and the bug should be reproducible from `notepad++.exe`.
This issue didn't show any reproducible result. Please consider https://github.com/notepad-plus-plus/notepad-plus-plus/issues/9556 as an example.
