### ISSUE TITLE
Wrong rendering of characters in certain contexts

### ISSUE THREAD

**Issue by stefano-zanotti** [notepad-plus-plus/notepad-plus-plus#9548]
### Description of the Issue
Some characters are rendered wrong (as if the font had no glyph for them) in certain textual contexts.

### Steps to Reproduce the Issue
Copy these three lines of text in a blank tab:
a‿
a‿ː
a‿(ː

### Expected Behavior
All the characters should show correctly (as they are shown here on GitHub)

### Actual Behavior
This is what is shown (with different cursor positions):
![screenshot](https://user-images.githubusercontent.com/35330869/108609190-adb86e80-73cc-11eb-9000-6b30b31414d7.png)

### Debug Information
Some characters are rendered wrong (as if the font had no glyph for them) in certain textual contexts.
In the three lines of text provided above, the second character in each line is "U+203F : UNDERTIE {Greek enotikon}".
This is just one character that causes me problems, others are affected as well.
In the first line, it is never rendered correctly. It always shows as a black "?" enclosed in a square outline (white square with black border). Note that this glyph is not that of � "U+FFFD : REPLACEMENT CHARACTER", which is a black lozenge with a white "?" in it.
In the second line, the simple addition of a ː "U+02D0 : MODIFIER LETTER TRIANGULAR COLON" causes the undertie to be rendered correctly.
In the third line, the undertie is shown correctly; however, if the cursor is placed right before or right after the parenthesis, the undertie is once again rendered incorrectly.
If we add another character between the undertie and the parenthesis, the behavior is the similar as that of line 3: the problem is not that the parenthesis is next to the undertie, it's the fact that the cursor is next to the parenthesis (this is probably due to the fact that parens-matching causes a change in the foreground/background color of the parenthesis, as well as in its weight).

Note that the replacement character itself shows the same problem: when the undertie character is shown as a "?" in a square, the replacement character too is shown as a "?" in a square; when the undertie is shown correctly, the replacement character is shown correctly.

Other problematic characters:
∅ "U+2205 : EMPTY SET {null set}"
⟦ "U+27E6 : MATHEMATICAL LEFT WHITE SQUARE BRACKET {z notation left bag bracket}"
⟧ "U+27E7 : MATHEMATICAL RIGHT WHITE SQUARE BRACKET {z notation right bag bracket}"
‱ "U+2031 : PER TEN THOUSAND SIGN {permyriad}"
⁂ "U+2042 : ASTERISM"
℀ "U+2100 : ACCOUNT OF"
⋠ "U+22E0 : DOES NOT PRECEDE OR EQUAL"
▣ "U+25A3 : WHITE SQUARE CONTAINING BLACK SMALL SQUARE"

I wasn't able to determine whether the problems lies with specific Unicode planes. For some of the characters listed above, characters quite close to them are shown just fine.

The problem shows with both Arial and Consolas; I haven't tested other fonts, but I don't think it is font-related.

I'm on Notepad++ v7.9.1 (32-bit); Windows 8.1 version 6.3.9600 Build 9600.
I've had this issue for a while now, it's not specific to this version of Notepad.

**Comment by sasumner** [comment]
@stefano-zanotti 

Have you tried turning this on?

![image](https://user-images.githubusercontent.com/30118311/108611214-5c978300-73aa-11eb-9c53-058709f36d88.png)

**Comment by stefano-zanotti** [comment]
That did it, thanks!
Any reason why this option is not on by default?

**Comment by sasumner** [comment]
>Any reason why this option is not on by default?

Shrug.
I suggested that it be on by default.
Program author did not want that.
