### ISSUE TITLE
File with name containing " +" will split into two files when opening with notepad++ as default edit program

### ISSUE THREAD

**Issue by rappelr** [notepad-plus-plus/notepad-plus-plus#9549]
### Description of the Issue
In the windows registry I have the default program for editing batch files set to notepad++
when I open a file that contains " +" a whitespace followed by a plus it will try and open whatever is before and after it as individual files.  So the filename "a +b.bat" tries to open a file "a" and a file "b.bat". You can also add more files to this. Opening "a +b +c +d.bat" will try to open 4 files.

This might also occur with other filetypes but I haven't tried. I think it has to do with the launch arguments looking like the ones you use for opening two files? Also note it doesn't happen when opening the file from within notepad++ or when selecting "Edit with notepad++" in the right-click menu.

### Steps to Reproduce the Issue
1. Set notepad++ as default program for editing batch files in the windows registry.
2. Rename a file to [any prefix] +[any suffix].bat.
3. Right-click the file and select "Edit".
4. It will try and open two files.

### Expected Behavior
It should see this as a single file, as it does with "a+b.bat" or "a + b.bat".

### Actual Behavior
It thinks you're opening two files at once, splits the filename along the " +" and looks for two (probably) non-existent files.

**Comment by sasumner** [comment]
>In the windows registry I have the default program for editing batch files set to notepad++

What does your command in the registry look like, exactly?

**Comment by mere-human** [comment]
Add debug info, please (Menu: _? > Debug Info... > Copy..._)

**Comment by rappelr** [comment]
> What does your command in the registry look like, exactly?

Branch: Computer\HKEY_CLASSES_ROOT\batfile\shell\edit\command
Name: (Default)
Type: REG_EXPAND_SZ
Data: "C:\Program Files (x86)\Notepad++\notepad++.exe" %1


> Add debug info, please (Menu: _? > Debug Info... > Copy..._)

Notepad++ v7.9.1   (32-bit)
Build time : Nov  2 2020 - 01:03:56
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS Name : Windows 10 Home (64-bit) 
OS Version : 2004
OS Build : 19041.804
Current ANSI codepage : 1252
Plugins : mimeTools.dll NppConverter.dll NppExport.dll

**Comment by sasumner** [comment]
It needs to look like this:
`"C:\Program Files (x86)\Notepad++\notepad++.exe" "%1"`

Note the double quotes around the %1

**Comment by rappelr** [comment]
Oh wow, my bad. Thank you for your time!
