### ISSUE TITLE
[Scintilla 446 bug]: Function List not working

### ISSUE THREAD

**Issue by vinsworldcom** [notepad-plus-plus/notepad-plus-plus#9555]
### Description of the Issue

I can't seem to get function list to work in Notepad++ 7.9.3 Debug release with the new Scintilla 4.4.6 DLL.  Files load fine, but function list does not populate.  This is for the same files where function list does populate using the current Scintilla 4.2.0 DLL.

### Steps to Reproduce the Issue

1. Debug Notepad++ 7.9.3 and Scintilla 4.4.6 DLL from the AppVeyor artifacts.
2. Open a file

![image](https://user-images.githubusercontent.com/9657169/108639776-40f0b300-7464-11eb-9b3e-46b3b794af8d.png)

Change the Scintilla DLL back to the 4.2.0 version supplied with Notepad++ 7.9.3 and it works fine for the same files:

![image](https://user-images.githubusercontent.com/9657169/108639837-9af17880-7464-11eb-881a-cf68cb71c139.png)

Note, I tried with my existing plugins and then tried removing them all and still get the same results to I'm pretty sure it is not a plugin conflict.  I then deleted my existing config.xml, shortcuts.xml, nativeLang.xml and contextMenu.xml and relaunched and still no function list populate for Scintilla 4.4.6.

Notepad++ v7.9.3   (64-bit)
Build time : Feb 21 2021 - 18:44:57
Path : C:\usr\bin\npp64\notepad++.exe
Admin mode : OFF
Local Conf mode : ON
OS Name : Windows 10 Enterprise (64-bit) 
OS Version : 1909
OS Build : 18363.1377
Current ANSI codepage : 1252
Plugins : none

**Comment by ArkadiuszMichalski** [comment]
I can confirm this:

```Notepad++ v7.9.3   (32-bit)
Build time : Feb 22 2021 - 23:28:49
Path : D:\_test\NPPClean\notepad++.exe
Admin mode : ON
Local Conf mode : ON
OS Name : Windows 7 Ultimate (64-bit) 
OS Build : 7601.0
Current ANSI codepage : 1250
Plugins : none
```

**Comment by vinsworldcom** [comment]
@ArkadiuszMichalski 
Thanks - was hoping it wasn't something I did wrong.  Super excited to see another Scintilla upgrade, hope this function list integration is just something overlooked or an easy quick fix.  This is the only thing keeping me from using the Debug release / SciLexer 4.4.6 as my "daily driver" Notepad++ install. 

Cheers.

**Comment by ArkadiuszMichalski** [comment]
I also wait for this update due of this:
https://sourceforge.net/p/scintilla/bugs/2141/
This can be used to create better hints in our code.

**Comment by vinsworldcom** [comment]
@ArkadiuszMichalski 

I missed that in the change log - that's COOL!!

![image](https://user-images.githubusercontent.com/9657169/108875631-62b87a00-75cb-11eb-8757-4b3f54eab117.png)

**Comment by sasumner** [comment]
@vinsworldcom Isn't the function list not working because it uses Boost regular expressions to do its work, and the Scintilla DLL build from the appveyor build doesn't include Boost?

You could certainly get around this by building Boost yourself (I know you are capable of that) and then building Scintilla with that Boost you build included.
But...I don't know how much effort you want to go to in this regard.

But regardless, I don't think this is a valid issue, but I won't close it until I hear your opinion on it.

**Comment by vinsworldcom** [comment]
> Isn't the function list not working because it uses Boost regular expressions to do its work, and the Scintilla DLL build from the appveyor build doesn't include Boost?

Interesting - I did not know that, but certainly a possibility.  Let me read through the docs to see if I can find Boost / Scintilla build instructions (probably a bit more complex setup than just CTRL+Shift+B in Visual Studio which is how I build Notepad++ now for testing).

I'd be super happy if that's the problem - something I did wrong rather than an actual issue.

Cheers.

**Comment by sasumner** [comment]
@vinsworldcom Refer here: https://github.com/notepad-plus-plus/notepad-plus-plus/blob/master/BUILD.md

**Comment by vinsworldcom** [comment]
@sasumner 

I found that doc myself and was following it (glad I was i the right place).

I get a bunch of errors during the `nmake` for Scintilla.  Boost seems to build OK - I get the `libboost_regex-vc141-mt-s-x64-1_70.lib` file created.

Could be that I'm using Visual Studio 2019 and the v142 tools.  I tried bootstrapping Boost both with the vc141 and vc142 arguments; they both worked and both of the `b2.exe` builds generated the respective files:

```
bin.v2\libs\regex\build\
|-- msvc-14.1
|   `-- release
|       `-- address-model-64
|           `-- link-static
|               `-- runtime-link-static
|                   `-- threading-multi
|                       |-- libboost_regex-vc141-mt-s-x64-1_70.lib
[...]
`-- msvc-14.2
    `-- release
        `-- address-model-64
            `-- link-static
                `-- runtime-link-static
                    `-- threading-multi
                        |-- libboost_regex-vc142-mt-s-x64-1_70.lib
```

I then did the Scintilla `nmake` both ways and got the same errors for both:

```
PS VinsWorldcom ~\source\personal\notepad-plus-plus\scintilla\win32 > [master ≡ +1 ~1 -0 !] nmake BOOSTPATH=C:\Users\VinsWorldcom\source\personal\boost_1_70_0\ BOOSTREGEXLIBPATH=C:\Users\VinsWorldcom\source\personal\boost_1_70_0\bin.v2\libs\regex\build\msvc-14.2\release\address-model-64\link-static\runtime-link-static\threading-multi\ -f scintilla.mak

Microsoft (R) Program Maintenance Utility Version 14.28.29336.0
Copyright (C) Microsoft Corporation.  All rights reserved.

        cl -Zi -TP -MP -W4 -EHsc -std:c++17 -D_CRT_SECURE_CPP_OVERLOAD_STANDARD_NAMES=1 -D_CRT_SECURE_NO_DEPRECATE=1 -D_SCL_SECURE_NO_WARNINGS=1  -O1 -MT -DNDEBUG -GL -I../include -I../src -I../lexlib -IC:\Users\VinsWorldcom\source\personal\boost_1_70_0\ -DSCI_OWNREGEX -DSCI_LEXER -DSCI_EMPTYCATALOGUE -c -Fo.\Catalogue.obj ..\src\Catalogue.cxx
Microsoft (R) C/C++ Optimizing Compiler Version 19.28.29336 for x64
Copyright (C) Microsoft Corporation.  All rights reserved.

Catalogue.cxx
        cl -Zi -TP -MP -W4 -EHsc -std:c++17 -D_CRT_SECURE_CPP_OVERLOAD_STANDARD_NAMES=1 -D_CRT_SECURE_NO_DEPRECATE=1 -D_SCL_SECURE_NO_WARNINGS=1  -O1 -MT -DNDEBUG -GL -I../include -I../src -I../lexlib -IC:\Users\VinsWorldcom\source\personal\boost_1_70_0\ -DSCI_OWNREGEX -D_SILENCE_ALL_CXX17_DEPRECATION_WARNINGS -c ../boostregex/BoostRegexSearch.cxx
Microsoft (R) C/C++ Optimizing Compiler Version 19.28.29336 for x64
Copyright (C) Microsoft Corporation.  All rights reserved.

BoostRegexSearch.cxx
C:\Users\VinsWorldcom\source\personal\notepad-plus-plus\scintilla\include\Platform.h(339): error C2039: 'string_view': is not a member of 'std'
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29333\include\vector(24): note: see declaration of 'std'
C:\Users\VinsWorldcom\source\personal\notepad-plus-plus\scintilla\include\Platform.h(339): error C3646: 'Text': unknown override specifier
C:\Users\VinsWorldcom\source\personal\notepad-plus-plus\scintilla\include\Platform.h(339): error C2059: syntax error: ')'
C:\Users\VinsWorldcom\source\personal\notepad-plus-plus\scintilla\include\Platform.h(339): error C2238: unexpected token(s) preceding ';'
C:\Users\VinsWorldcom\source\personal\notepad-plus-plus\scintilla\include\Platform.h(401): error C2039: 'unique_ptr': is not a member of 'std'
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29333\include\vector(24): note: see declaration of 'std'
C:\Users\VinsWorldcom\source\personal\notepad-plus-plus\scintilla\include\Platform.h(401): error C2143: syntax error: missing ';' before '<'

[...]
```

**Comment by mere-human** [comment]
> Could be that I'm using Visual Studio 2019 and the v142 tools. I

Probably, this is the problem.
You have to use 2017 v141 and launch build from x64 Native Tools Command Prompt for VS 2017.

**Comment by vinsworldcom** [comment]
@mere-human 
Thanks - I was using the x64 Native Tools Command Prompt for VS (2019 in my case).  I'll have to see about downgrading ...

When is SciLexer.DLL build with Boost - only for the Notepad++ releases?  Never in AppVeyor?  Seeing some discussion [here](https://github.com/notepad-plus-plus/notepad-plus-plus/issues/9493#issuecomment-785147474) regarding my eagerness in testing an perhaps ignoring the shortcomings of the AppVeyor SciLexer.DLL builds.

I see @donho has taken ownership of this issue - hopefully he sees this chain and doesn't waste anytime trying to fix something that may well not be broken in the proper Boost-enhanced SciLexer.DLL?

Sorry for creating confusion - truly thought I could use the AppVeyor SciLexer.DLL the same way I just drop in the Notepad++.exe AppVeyor builds to immediately test new features.

Cheers.

**Comment by mere-human** [comment]
See my comment in another discussion regarding AppVeyor version of SciLexer.dll: https://github.com/notepad-plus-plus/notepad-plus-plus/issues/9493#issuecomment-785238119

**Comment by donho** [comment]
@vinsworldcom or people who wants to test Scintilla v4.4.6:

Signed sciLexer.dll 32 bits (release mode): https://github.com/notepad-plus-plus/notepad-plus-plus/pull/9550#issuecomment-782902066

Signed sciLexer.dll 64 bits (release mode): https://github.com/notepad-plus-plus/notepad-plus-plus/pull/9550#issuecomment-785241085

**Comment by ArkadiuszMichalski** [comment]
With  sciLexer.dll 32 bits function list works fine.

**Comment by vinsworldcom** [comment]
@sasumner 

Please accept my humble apology and close this ticket before anymore time is wasted :-( 

Thanks @donho for the Scintilla upgrade and the signed SciLexer.dll 64-bit.  Tested and working:

![image](https://user-images.githubusercontent.com/9657169/109041857-7e8c5080-769d-11eb-8cd6-79bfc20c7504.png)

Cheers.
