### ISSUE TITLE
Shortcut name more than 64 characters makes an empty name

### ISSUE THREAD

**Issue by donho** [notepad-plus-plus/notepad-plus-plus#9556]
### Description of the Issue
Shortcut name more than 64 characters makes an empty name

### Steps to Reproduce the Issue

1. Open shortcuts.xml by using notepad.exe
2. Add a command node in the file, save it and quit notepad.exe:
```
<Command name="noaksdlkasjdfsfsdfsdfsdfsdfsdfsdfsdgfsdffssdaqwekawkeawerjerwerjwerlaaskdjalsdjalskdjalsdjalskdjasld" Ctrl="no" Alt="yes" Shift="no" Key="111">http://www.php.net/$(CURRENT_WORD)</Command>
```
3. Open Notepad++, check the command in "Macro" menu

### Expected Behavior
a command with `noaksdlkasjdfsfsdfsdfsdfsdfsdfsdfsdgfsdffssdaqwekawkeawer` displayed.

### Actual Behavior
a command with empty name displayed.

### Debug Information
Notepad++ v7.9.3   (32-bit)
Build time : Feb 21 2021 - 19:47:38
Path : X:\notepad-plus-plus\PowerEditor\bin\notepad++.exe
Admin mode : OFF
Local Conf mode : ON
OS Name : Windows 10 Enterprise (64-bit) 
OS Version : 2004
OS Build : 19041.804
Current ANSI codepage : 1252
Plugins : DSpellCheck.dll HexEditor.dll LuaScript.dll mimeTools.dll NppConverter.dll NppExport.dll SessionMgr.dll XMLTools.dll

**Comment by sasumner** [comment]
Related:  It appears that the maximum length for a macro's name (or a Run menu entry's name) is 63 characters (based upon specifying more in the prompt box field, and observing what happens in the menus).  @pryrt I didn't see this in the user manual -- is that correct?  It probably should be in there.

**Comment by pryrt** [comment]
> @pryrt I didn't see this in the user manual -- is that correct? It probably should be in there.

The 63-character limitation is not mentioned.  It could naturally go as text at the end of the Macros#Save paragraph, or in the Meaning column of the Config-file#Macros attribute-for-\<Macro> table, or both.  Did you want to add that, or should I?

**Comment by sasumner** [comment]
@pyrt Does the manual talk about changing text via e.g. `english_customizable.xml`?  I'm always confused on whether such customization is supposed to be end-user, power-user, or translators only.  As one of the second group, I DO customize my UI text.  My point here is that if it is (or should be) in the manual, shall we hold off in updating manual for this 64-char thing until 9572 is decided, and then make a batch update?

**Comment by pryrt** [comment]
@sasumner , [binary-translation.md](/notepad-plus-plus/npp-usermanual/blob/master/content/docs/binary-translation.md) mentions how to edit the translations, but it doesn't specifically call out `english_customizable.xml`.  It could -- I don't think it's intentionally hidden from the normal user.

As far as changing the docs go, I don't really care whether changes are piecemeal with multiple pull requests, or in one big PR.  Since the changes only get released to the website when Don is ready for a new npp-user-manual release, it doesn't affect end users whether changes in GitHub are incremental or bulk.
