### ISSUE TITLE
Fix potential invalid access violation

### ISSUE THREAD

**Issue by QoL15155** [notepad-plus-plus/notepad-plus-plus#9557]
### Description of the Issue
Very hard to replicate, but its easy to see in the code that if `p==0` we dont' return. Then on condition `(*p=='>')` we try to dereference the address 0x00000000 and crash

``` c++
	if ( !p )
	{
		if ( document )	document->SetError( TIXMLA_ERROR_PARSING_UNKNOWN, 0, 0 );
	}
	if ( *p == '>' )
		return p+1;
```

### Steps to Reproduce the Issue
Very hard to reproduce
Functions: 
+ `TiXmlUnknown::Parse` 
+ `TiXmlUnknownA::Parse`

### Debug Information
Notepad++ v7.9.1   (64-bit)
Build time : Nov  2 2020 - 01:07:46
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS Name : Windows 10 Pro (64-bit) 
OS Version : 1909
OS Build : 18363.1379
Current ANSI codepage : 1252
Plugins : mimeTools.dll NppConverter.dll NppExport.dll XMLTools.dll

**Comment by QoL15155** [comment]
Pull request
https://github.com/notepad-plus-plus/notepad-plus-plus/pull/9558

**Comment by donho** [comment]
As I mentioned in https://github.com/notepad-plus-plus/notepad-plus-plus/issues/9545
The issue should be bug report, and the bug should be reproducible from notepad++.exe.
This issue didn't show any reproducible result. Please consider #9556 as an example.
