### ISSUE TITLE
Change End Of Line (EOL) by one click.

### ISSUE THREAD

**Issue by username1565** [notepad-plus-plus/notepad-plus-plus#9562]
Using Notepad++ to change end of line characters (CRLF to LF)
```
Click on Search > Replace (or Ctrl + H)
Find what: \r\n.
Replace with: \n.
Search Mode: select Extended.
Replace All.
```
5 steps.

Can it be changed by one click?
I think, there is possible to add context menu, there, where (Macintosh, Windows, and Unix)-label available,
here: 
![image](https://user-images.githubusercontent.com/39200328/108791149-4d653080-7576-11eb-8dfa-82c71cd56bde.png)

to change EOL for all file.
Also, will be better to add the option, to change EOL for the group of files in folder, including subfolders.

**Comment by sasumner** [comment]
Not sure what version of Notepad++ you're showing there.

But it can be TWO clicks in 7.9.3:

* right-click the area you show between the red arrows; a menu will pop up
* choose an entry from that menu

Done.

**Comment by username1565** [comment]
Thanks, I found it: 
![image](https://user-images.githubusercontent.com/39200328/109211453-29883180-77a6-11eb-850f-f5ea10835613.png)

**Comment by sasumner** [comment]
@username1565 

Yes, but that's the "slow" way.
Previously I had shown you the "fast" way via the status bar.
But...maybe the status bar way didn't work in version 5.9.*

Maybe consider an upgrade to a newer version??

I didn't notice you had said this earlier:

>will be better to add the option, to change EOL for the group of files in folder, including subfolders.

That (multiple files) you can only do in Notepad++ with a _Replace in Files_ operation.  BE CAREFUL with that.

**Comment by username1565** [comment]
>That (multiple files) you can only do in Notepad++ with a _REPLACE IN ALL FILES_ operation. BE CAREFUL with that.
Yeap, this is the best solution.
1. Just open new instance.
2. Then _drag and drop_ all files with invalid EOL,
for example, _drag and drop_ folder or diff, after [WinMerge](https://github.com/WinMerge/winmerge)-comparison. 
3. Replace EOL for all files in that instance, using Ctrl-F -> Replace.
Example:
LF -> CRLF: `\n` -> `\r\n`
LF -> CR: `\n` -> `\r`
CRLF -> LF: `\r\n` -> `\n`
CRLF-> CR: `\r\n` -> `\r`
CR -> LF: `\r` -> `\n`
CR -> CRLF: `\r` -> `\r\n`

But sometimes, there is mixed EOL, in files, for example:
```
line1CR
line2CRLF
line3LF
```
then, replace:
1. CR -> LF: `\r` -> `\n` -> all CR to LF, then LF and CRLF only.
2. LF -> CRLF: `\n` -> `\r\n` -> all LF to CRLF, then CRLF only.
3. CRLF -> target EOL (CR or LF): `\r\n` -> `\r` or `\n`.
Do this for all files in the instance.

**Comment by sasumner** [comment]
@username1565 

To simplify it, do this:

![image](https://user-images.githubusercontent.com/30118311/111828586-ebbc8b80-88c1-11eb-8f52-4051f89d6a46.png)

If you want Linux files, where the yellow is, substitute in `\n`.
Probably nobody wants Mac files, but for completeness, where the yellow is, substitute in `\r`.

Press the button indicated in the red circle.

Probably best to make a backup of your files first.

**Comment by username1565** [comment]
>Probably best to make a backup of your files first.

Yeap, [WinMerge](https://github.com/WinMerge/winmerge), allow to backup the different files, into zip-archive,
after comparison two folders, and only different files with differences, are added in that zip:

![image](https://user-images.githubusercontent.com/39200328/111852378-98245f00-890e-11eb-81b1-7a9ed1036c13.png)

Also, there is possible to see EOL, and enable the ignoring EOL differences, on compare the files:
https://github.com/WinMerge/winmerge/issues/643

**Comment by sasumner** [comment]
>Also, there is possible to see EOL

Of course, Notepad++ has this as well, see _View_ menu > _Show Symbol_ > _Show End of Line_ to see, for example:

![image](https://user-images.githubusercontent.com/30118311/111853207-67cdc800-88f0-11eb-8d2d-e8ab1b350eb3.png)

**Comment by username1565** [comment]
Yeap, and I just using this button:
![image](https://user-images.githubusercontent.com/39200328/111864607-ea3ea200-8959-11eb-9c66-d85d307caeb1.png)
