### ISSUE TITLE
Extension avsc

### ISSUE THREAD

**Issue by madvik** [notepad-plus-plus/notepad-plus-plus#9564]
### Description of the Issue
When I open a file with extension `avsc`, it is no recognize.

### Steps to Reproduce the Issue
1. Open a avro schema with np++

### Expected Behavior
Avro schema is a json notation

### Actual Behavior
nothing

It is possible to add a file with `avsc ` in extension as a `json` file ?

**Comment by mere-human** [comment]
You forgot to add debug info:
![image](https://user-images.githubusercontent.com/9664141/108848023-25fb7b80-75e9-11eb-8aa1-6705c715f9a0.png)

**Comment by sasumner** [comment]
Did you try adding `avsc` here?:

![image](https://user-images.githubusercontent.com/30118311/108851588-989d3480-75b2-11eb-82cc-f210ba1fa67b.png)

**Comment by madvik** [comment]
> 
> 
> You forgot to add debug info:
> ![image](https://user-images.githubusercontent.com/9664141/108848023-25fb7b80-75e9-11eb-8aa1-6705c715f9a0.png)

my issue is not a bug, it is feature request,

**Comment by madvik** [comment]
> 
> 
> Did you try adding `avsc` here?:
> 
> ![image](https://user-images.githubusercontent.com/30118311/108851588-989d3480-75b2-11eb-82cc-f210ba1fa67b.png)

Yes, but it is better ta add this extension to default

**Comment by sasumner** [comment]
>Yes

Presumed it worked then; it would have been nice if you'd said this (or the opposite) with certainty.

>but it is better ta add this extension to default

NOPE!

**Comment by madvik** [comment]
Why ?
