### ISSUE TITLE
Auto update message is very confusing

### ISSUE THREAD

**Issue by robross0606** [notepad-plus-plus/notepad-plus-plus#9573]
With the latest version of NPP, I saw this message when testing "Update Notepad++".
![image](https://user-images.githubusercontent.com/2965467/109024495-d621c080-768b-11eb-892e-c02ab69c7d41.png)
This was an extremely confusing message because it hints that the auto-update mechanism _itself_ is not "activated".  I started searching the web for ways to "activate" my auto-update mechanism before finding that this was related to there being no new "verified" updates available.

What I would recommend instead is:
- Add a page in the help section of the website explaining how your update lifecycle works and providing a link back to your regular downloads page if someone wants to download the absolute latest "not necessarily stable" version.
- Make the dialog message something like "No new verified stable updates are currently available".
- Put a link on the "verified stable" words in the dialog pointing back to the web page under Help.

Wireframe mockup:
![2021-02-24 10 54 18](https://user-images.githubusercontent.com/2965467/109027501-d96a7b80-768e-11eb-841f-e5b14d5666e9.png)

**Comment by robross0606** [comment]
Wow, I just found the page is _almost_ already there:
https://npp-user-manual.org/docs/upgrading/#new-version-available-but-auto-updater-find-nothing
Just add a little more content on this page, including a link back to Downloads, and then link to this anchor from the dialog.

**Comment by robross0606** [comment]
A couple other mockup options:
![image](https://user-images.githubusercontent.com/2965467/109028496-dae87380-768f-11eb-9941-03b05eded116.png)
![image](https://user-images.githubusercontent.com/2965467/109028526-e2a81800-768f-11eb-8102-d34d58a5272b.png)

**Comment by ArkadiuszMichalski** [comment]
I have seen several times asking why `Auto update` or  `? > Update Notepad++` not download new version. Maybe above solution would reduce such a question.

**Comment by mere-human** [comment]
@robross0606 What about this?
![image](https://user-images.githubusercontent.com/9664141/109057980-1cf2d300-76eb-11eb-92f5-da4acd6a2d80.png)

**Comment by mere-human** [comment]
> I have seen several times asking why `Auto update` or `? > Update Notepad++` not download new version.

That was exactly why I decided to change the "no update" dialog and add a link to it.
Turns out that the text still needs some polishing.

**Comment by mere-human** [comment]
Or even change `verified` to `stable`:
![image](https://user-images.githubusercontent.com/9664141/109058385-9d193880-76eb-11eb-82b0-de8d83f15473.png)

**Comment by robross0606** [comment]
I don't really this suggestion because it sheds no light on what "verified updated" means.  You have content on the site already which comes close.  If you simply link to that Help page instead of "Downloads", explain what it means and put the link to "Downloads" _there_, you get the best of both words.  The explanation is 1 click away and you can edit it without updating the application itself.  Downloads are 2 clicks away.

**Comment by robross0606** [comment]
I don't have any preference on "stable" versus "verified" as long as the link takes you to a page which _explains_ the meaning.

**Comment by mere-human** [comment]
> You have content on the site already which comes close, but this dialog doesn't even tell you that's available. I found it by accident.

I believe, the curious users will eventually find that page in user manual.
The rest of the users will just proceed to the download page. They'll hardly bother themselves reading the manual.

**Comment by mere-human** [comment]
Let's see what does @donho think about this.

**Comment by robross0606** [comment]
> curious users will eventually find that page

I don't agree with that reasoning at all, especially since two clicks to get to the downloads isn't at all problematic.  The dialog doesn't tell you why you would go to the downloads page if the dialog is already telling you there are no stable updates.  It is still confusing.

I'm not sure why 2 clicks to get to Downloads is a problem but, iif you absolutely positively MUST have the link to Downloads on the dialog, then why not offer both?

![image](https://user-images.githubusercontent.com/2965467/109059958-d2edfb00-76b2-11eb-94d0-e260d6cfc24c.png)

**Comment by mere-human** [comment]
> then why not offer both?

This looks better!

**Comment by robross0606** [comment]
Or this if you can swing the inline links:
![image](https://user-images.githubusercontent.com/2965467/109060397-5d365f00-76b3-11eb-9226-332f6a7d29f8.png)

**Comment by donho** [comment]
> I don't have any preference on "stable" versus "verified" as long as the link takes you to a page which explains the meaning.

I don't think it's necessary to provide a page whereas we can provide all the info on the message dialog.
But it's true that the message needs to be refined.

**Comment by sasumner** [comment]
I don't like the use of "unstable".  If I was just a casual Notepad++ users, there would be no way I'd be interested in unstable releases of it, and I'd really question the logic of developers that would be offering this to me.  This leads into a related but perhaps lesser dislike of the usage of "stable".

**Comment by robross0606** [comment]
> I don't like the use of "unstable". If I was just a casual Notepad++ users, there would be no way I'd be interested in unstable releases of it, and I'd really question the logic of developers that would be offering this to me. This leads into a related but perhaps lesser dislike of the usage of "stable".

I'm not married to the word "unstable".  Just hunting for a counter-term to the word "stable".  Really what this seems to be is a riff on the "LTS" concept but at much smaller scale.  I'll admit it is difficult to convey with one or 2 words.

**Comment by robross0606** [comment]
> I don't think it's necessary to provide a web page to explain whereas we can provide all the info on the message dialog.
> But it's true that the message needs to be refined.

The web page already exists:
https://npp-user-manual.org/docs/upgrading/#new-version-available-but-auto-updater-find-nothing

It could use a little refinement, but I'm trying to leverage what's already there while also preventing the need to release a whole new version of the software every time the message wants to be tweaked.

**Comment by ArkadiuszMichalski** [comment]
Giving a download link to manually install/update makes sense https://github.com/notepad-plus-plus/notepad-plus-plus/issues/9573#issuecomment-785346474? This entire update delay was probably introduced for some reason, why encourage "standard users" to update manually? More experienced users certainly know how to update NPP without waiting for the built-in mechanism. 

Of course, a short explanation of the reasons for the delay is highly recommended, with a possible link to the manual (more detailed description). I don't know if in this window it will be possible to describe everything concisely, without providing an additional link. 

@robross0606 
"You can check download..." in https://github.com/notepad-plus-plus/notepad-plus-plus/issues/9573#issuecomment-785346474, which page do you mean for unstable versions, this one here?

**Comment by robross0606** [comment]
@ArkadiuszMichalski, I was just trying to incorporate a link to the Downloads page because it seems like there is a strong desire to have that in the dialog.  I think the use of the word "unstable" is causing more confusion so that word can be removed.
![image](https://user-images.githubusercontent.com/2965467/109166377-a4236380-774a-11eb-96ce-066e80ee91a3.png)

**Comment by robross0606** [comment]
Here's another shot at it:
![image](https://user-images.githubusercontent.com/2965467/109167657-fdd85d80-774b-11eb-9039-f98722b7adb3.png)
This tries to include all suggestions.  

A question about how the "one week" limit is implemented:  Is that a sever-side thing or is that coded into the NPP executable itself?

I was trying to avoid specifically saying "one week" in here because I feel strongly that it would be better to leave this detail on the website in case the length of time wants to be changed.  However, that assumes the filter is server-side and not encoded in the client itself.  If it is in the client, seems like someone could just change their system time and get the latest release.

**Comment by sasumner** [comment]
>A question about how the "one week" limit is implemented: Is that a sever-side thing or is that coded into the NPP executable itself?

>I was trying to avoid specifically saying "one week" in here because I feel strongly that it would be better to leave this detail on the website in case the length of time wants to be changed

There is no fixed length of time.  It is not "coded" anywhere.
If the author feels a release has too many problems, which are often quite small in nature (thus to not demand some sort of emergency fix and rerelease), then he will NEVER trigger auto-update for the release.
Additionally, I have never heard of a "standard length of time" that even a release that has no discovered problems will wait before auto-update triggering.

So maybe if your "predetermined period" link is removed and replaced with static text of "period of time", then I can say that I (for one) like the verbage of your previous screenshot (in https://github.com/notepad-plus-plus/notepad-plus-plus/issues/9573#issuecomment-785937089)

**Comment by robross0606** [comment]
> Additionally, I have never heard of a "standard length of time" that even a release that has no discovered problems will wait before auto-update triggering.

This page specifically says "during one week":
https://npp-user-manual.org/docs/upgrading/#new-version-available-but-auto-updater-find-nothing

**Comment by sasumner** [comment]
>This page specifically says "during one week"

@pyrt In your observation, has this been true more often than not?

I'm somewhat limited in knowledge as I'm a user of strictly portable versions, because (for me) there is absolutely no value in using an "installed" version.

>...not based on some filter on the NPP client. Correct?

Correct.

**Comment by mere-human** [comment]
> I don't like the use of "unstable". If I was just a casual Notepad++ users, there would be no way I'd be interested in unstable releases of it, and I'd really question the logic of developers that would be offering this to me.

Stable, nightly and LTS are quite widespread terms as for me:
https://en.wikipedia.org/wiki/Software_release_life_cycle#STABLE-RELEASE



> Here's another shot at it:
> ![image](https://user-images.githubusercontent.com/2965467/109167657-fdd85d80-774b-11eb-9039-f98722b7adb3.png)
> This tries to include all suggestions.

This looks like to much for such a tiny dialog.

I think, if the text can be googled and the manual can be found why include the link?
If there is the exact same text with explanations in the manual then it seems like enough.

**Comment by robross0606** [comment]
> If there is the exact same text with explanations in the manual then it seems like enough.

Which is why I originally opted for just a link to the explanation that's already on the website.  What I _don't_ agree with is relying on people being confused and having to Google to figure out what your dialog means.  That's the opposite of intuitive.

**Comment by pryrt** [comment]
> _In your observation, has this been true more often than not?_

I don't always pay attention, but I have been notified by a forum user when the delay was more than 1 week -- and in those instances, it finally triggered up to 12 days after the initial release.  I don't think I've ever seen a trigger more than 2 weeks after the initial release.  I would probably suggest the manual be reworded to:

> In order to avoid to spreading a new version which contains regressions or critical bugs, we will generally wait for users’ feedback for one to two weeks before triggering the automatic update.

As far as the dialog goes, I agree that the most recent mockup carries too many words for a dialog box.  (Yes, I know I'm the pot calling the kettle black; I know how long my forum posts, and even comments here, can get.)

> No newer version is available that has been
> \_triggered\_for\_automatic\_update\_.
> 
> You can check the \_downloads\_ page
> for additional available releases to 
> install manually.
> 
> [OK]

(the first underline being the link to the upgrading page, and the second underline being the link to the downloads page)

**Comment by robross0606** [comment]
@pryrt 
![image](https://user-images.githubusercontent.com/2965467/109207813-8c160900-7777-11eb-8561-f17a0d1b92b6.png)

**Comment by donho** [comment]
This dialog is for notifying user "No update", so I would say let's not forgetting the essential information:
The idea is to let user know there's no update but a new version could be available, with less words, so here is my suggestion:

![image](https://user-images.githubusercontent.com/90293/109285835-d6ec5b00-7821-11eb-9d55-aaf17d09ff21.png)

**Comment by donho** [comment]
https://github.com/notepad-plus-plus/wingup/commit/8016e45eb48aabe03127fde56ecb1d440ac9e3be
