### ISSUE TITLE
Font display error on secondary menu window with a resolution of 3840 x 2160

### ISSUE THREAD

**Issue by ownia** [notepad-plus-plus/notepad-plus-plus#9577]
### Font display error on secondary menu window with a resolution of 2560 x 1600

1. the font of "Copy debug info to clipboard" has issues
2. the font of home hyperlink on "About Notepad++" has issues

### Steps to Reproduce the Issue

1. menu"?" -> Debug info
2. font display error with "Copy debug info to clipboard" hyperlink
3. menu"?" -> About Notapad++ (F1)
4. font display error with home hyperlink

### Expected Behavior

correct font display like old versions

### Actual Behavior

the font of hyperlink is too large to display, looks like it's setted a different font size from the label and exceed the layout widget.

![20210225154539](https://user-images.githubusercontent.com/16909431/109120190-9983c100-7780-11eb-9df5-a3cda5f57541.png)

![20210225153913](https://user-images.githubusercontent.com/16909431/109119548-cd121b80-777f-11eb-9c5f-3e5dd88f361d.png)

### Debug Information

Notepad++ v7.9.3   (64-bit)
Build time : Feb 14 2021 - 03:15:58
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS Name : Windows 10 Pro (64-bit) 
OS Version : 1909
OS Build : 18363.997
Current ANSI codepage : 936
Plugins : ComparePlugin.dll HexEditor.dll mimeTools.dll NppConverter.dll NppExport.dll

**Comment by sasumner** [comment]
DPI-related.
DPI issues and their resolution (sorry) are known, and ongoing...

**Comment by ownia** [comment]
waiting for the resolved version👏

**Comment by sasumner** [comment]
May be a long wait as this is not an easily-solved thing.
Of course if the 7.9.2 behavior is restored in the next version the wait is not so long, but that doesn't solve the larger problem of DPI.
Regardless, other open issues deal with it, so I'm going to close this one.
