### ISSUE TITLE
 install 7.9.3 64 bit,  Try to launch it. Fails

### ISSUE THREAD

**Issue by Im-Spartacus** [notepad-plus-plus/notepad-plus-plus#9578]
Hi there,

I have a problem now I updated to the latest 64 bit install v7.9.3 from v6.9 and now whenever I launch it, it fails to open.  Nothing happens.    So I tried the previous build v7.9.2 64 bit - works fine.
 ( I used notepad++ and happy with it for many years no problems normally).

I am on Windows 10 64bit pro. Fully up to date 20H2.  Any ideas?  Seems to be possibly related to the new restriction 
"Notepad++ drops (stops running under) Windows XP & Windows Server 2003 due to technical reasons. Notepad++ 7.9.2 is the last version to run on Windows XP & Windows Server 2003."   ??  Not sure how as I am on Windows 10 though but hey a thought I had..

Any help on this problem please gratefully received.

Thanks

### Steps to Reproduce the Issue

1. install 7.9.3 64 bit,  Try to launch it. Fails
2.  install 7.9.2 64bit . Try to launch it, runs and opens fine.
3. 
### Expected Behavior
Program should launch normally.

### Actual Behavior
Program does not launch.  Nothing happens.

### Debug Information
Can't get there in .7.93 due to not opening, but can supply from 7.9.2 which works if that helps.

**Comment by sasumner** [comment]
>, but can supply from 7.9.2 which works if that helps.

Yes, supply it.

**Comment by Im-Spartacus** [comment]
OK thanks

Notepad++ v7.9.2   (64-bit)
Build time : Dec 31 2020 - 04:01:34
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS Name : Windows 10 Pro (64-bit) 
OS Version : 2009
OS Build : 19042.844
Current ANSI codepage : 1252
Plugins : ComparePlugin.dll DSpellCheck.dll IndentByFold.dll mimeTools.dll NppConverter.dll NppExport.dll NppSaveAsAdmin.dll NppToolBucket.dll XMLTools.dll

**Comment by ArkadiuszMichalski** [comment]
It's probably because of plugin NppSaveAsAdmin.dll, try with last version:
https://github.com/Hsilgos/nppsaveasadmin/releases

**Comment by sasumner** [comment]
Yep, get rid of *SaveAsAdmin* for now if you want to run 7.9.3

**Comment by Im-Spartacus** [comment]
OK found that and deleted, works perfectly.  Many thanks for your fast and excellent support!
