### ISSUE TITLE
Notepad++ 7.9.3 unusable on 4k screens

### ISSUE THREAD

**Issue by CBTMike** [notepad-plus-plus/notepad-plus-plus#9579]
Hello, just registered to ask this question

Notepad 7.9.2 (and all previous versions) look fine on a 4K screen.  See image 1.

![Image 1](https://user-images.githubusercontent.com/79655563/109184297-d938b180-775c-11eb-83b1-6d7c92204718.jpg)

Notepad 7.9.3 appears to not be recognizing Windows scale settings, and as a result menus and fonts are completely unreadable.  See image 2.

![Image 2](https://user-images.githubusercontent.com/79655563/109184309-dd64cf00-775c-11eb-9ab2-52d1dd5ac69f.jpg)

Is there a software setting that can be changed for this?  Or just have to wait for Devs to fix?

**Comment by HBelusca** [comment]
```
> Makes XP not able to run Notepad++ 7.9.3. because "time to move on and use modern features of Windows".
> * Breaks said modern features on Windows *
```

**Comment by sasumner** [comment]
Just so nobody gets the wrong idea:

These were two separate and _totally unrelated changes_ between 7.9.2 and 7.9.3:

* a reworking of file/directory Open/Save/Browse dialog such that they were no longer compatible with XP

* a change regarding DPI handling

DPI handling will get further treatment in upcoming versions of Notepad++; XP is dropped forever.

**Comment by CBTMike** [comment]
@sasumner  - Hi!  Thanks for the reply.  It appears something in the DPI handling is broken.  I'm running the latest version of Windows 10 so comments about XP don't apply (at least in this particular situation).  😄

Do you have any suggestions or should I just wait for a future update to hopefully resolve the issue?

**Comment by sasumner** [comment]
@CBTMike - It's not exactly broken -- 7.9.3 actually works _better_ for me than previous versions -- it's just a different type of support.  :-)  Okay, yes, it's broken for some now. :-(

DPI support "for all" is being worked on for an upcoming release.

I'm not sure there's a master issue number for it that I can point you to, there seems to be a few open issues about it.
