### ISSUE TITLE
Please mark words on a SINGLE line in find results

### ISSUE THREAD

**Issue by a-einstein** [notepad-plus-plus/notepad-plus-plus#9580]
When I search for a word in file(s), let's say 'error' in a log-file,  I get every instance of the word in a line reported on a SEPARATE line, each one of them highlighted.

I would prefer to have all instances in a line reported on one SINGLE line, and of course all of them highlighted. 
That would create a more compact overview.
Maybe the number of instances in the line could be reported at the reporting line too.

So my request is to either implement it like that, or make it an option.

**Comment by sasumner** [comment]
Similar to #1499 
Ongoing work will proceed via that issue.
