### ISSUE TITLE
Remove the download last release part from Appveyor script and use the generated SciLexer.dll

### ISSUE THREAD

**Issue by donho** [notepad-plus-plus/notepad-plus-plus#9581]
Currently in Appveyor build, we download SciLixer.dll from the latest release for Unit tests (of function list especially). 
In PR https://github.com/notepad-plus-plus/notepad-plus-plus/pull/9574 the boost is included in Appveyor build.

We can remove the download last release part from Appveyor script and use the generated SciLexer.dll, since the [PR mentioned above has been committed in the branch master](https://github.com/notepad-plus-plus/notepad-plus-plus/commit/d6c6a49d1b2f763c13c77b865a9693e9d912cc37).

**Comment by donho** [comment]
@chcg 
Could you please remove `SUPPORT_XP` from the script as well ?

**Comment by chcg** [comment]
@ArkadiuszMichalski Your PR https://github.com/notepad-plus-plus/notepad-plus-plus/pull/9583 was already the correct fix for the change needed here. I created now #9581.
@donho Did the requested changes.
