### ISSUE TITLE
crashes on start, issue with clr.dll

### ISSUE THREAD

**Issue by petermaguire787** [notepad-plus-plus/notepad-plus-plus#9585]
### Description of the Issue
when attempting to start notepad++ it crashes with the following event log:

Faulting application name: notepad++.exe, version: 7.9.3.0, time stamp: 0x60288871
Faulting module name: clr.dll, version: 4.8.4300.0, time stamp: 0x5f7e616e
Exception code: 0xc0000005
Fault offset: 0x0000000000669f10
Faulting process ID: 0x65d8
Faulting application start time: 0x01d70bf884e1ed1f
Faulting application path: D:\Program Files\Notepad++\notepad++.exe
Faulting module path: C:\Windows\Microsoft.NET\Framework64\v4.0.30319\clr.dll
Report ID: effa88d5-295d-4881-a1dd-2c6795353db9
Faulting package full name: 
Faulting package-relative application ID: 

### Steps to Reproduce the Issue

1.  start attempt
2.  start attempt
3.  start attempt

### Actual Behavior
did not start

### Debug Information
not available, does not get that far.

1. have tried sfc and dism repair: no issues where found with windows files
2. reboot
3. reinstall of notepad++
Intel(R) Xeon(R) Silver 4210 CPU @ 2.20GHz   2.19 GHz
32.0 GB (31.6 GB usable)

Edition	Windows 10 Pro for Workstations
Version	20H2
Installed on	‎10/‎06/‎2020
OS build	19042.804

Experience	Windows Feature Experience Pack 120.2212.551.0

**Comment by mere-human** [comment]
Do you have NppSaveAsAdmin plugin installed by any chance?
You can check the plugins directory in the Notepad++ installation folder.
If so, then there is an existing bug: https://github.com/notepad-plus-plus/notepad-plus-plus/issues/9514

**Comment by petermaguire787** [comment]
I do have NppSaveAsAdmin, and I have removed it, and notepad++ now starts.
