### ISSUE TITLE
there is a "$INT_REPLACE3" in search overview when you npp is in Chinese(zh_CN) , but English won't

### ISSUE THREAD

**Issue by xiaopangju** [notepad-plus-plus/notepad-plus-plus#9588]
### Description of the Issue

when you are doing some searches , the search overview will show `搜索 "colour" （0个文件中匹配到0次，总计查找$INT_REPLACE3）` to you, the " `$INT_REPLACE3` " is a strange part in this sentence. But when you are using English as your interface language, the search overview will be " `Search "colour" (0 hits in 0 files of 1 searched)` ". I hope that who can fix this issue.
**NOTE:** "Colour" is a random word, this bug will reproduce when searching for any word.
### Steps to Reproduce the Issue

1. Set `Chinese Simplified` as your interface language.
2. Click `Ctrl+F`
3. Input a random word
4. Click `在当前文件中查找（Find All in current Document）` or `查找所有打开文件(Find All in Opened Documents)`

### Expected Behavior

The software will show me the sentence "0个文件中匹配到0次，总计查找了1次"
### Actual Behavior

The software shows me the sentence "0个文件中匹配到0次，总计查找$INT_REPLACE3"
### Debug Information

Notepad++ v7.9.3   (32-bit)
Build time : Feb 14 2021 - 03:12:31
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : ON
Local Conf mode : OFF
OS Name : Windows 7 Ultimate (32-bit) 
OS Build : 7600.0
Current ANSI codepage : 936
Plugins : mimeTools.dll NppConverter.dll NppExport.dll 

![图片](https://user-images.githubusercontent.com/56964531/109374312-67dd3800-78ef-11eb-8b15-c18265678df5.png)

**Comment by xiaopangju** [comment]
#9589 can fix this

**Comment by xiaopangju** [comment]
@donho Can you confirm whether this issue has been solved?

**Comment by donho** [comment]
Theatrically it's fixed by #9589
