### ISSUE TITLE
[Enhancement] Please add Rust's syntax highlighting to next release of Notepad++

### ISSUE THREAD

**Issue by skarsgal** [notepad-plus-plus/notepad-plus-plus#9592]
You can find syntax highlighting to https://github.com/pfalabella/Rust-notepadplusplus 

How to do:
in GitHub page **Rust-notepadplusplus**:
1. press 'userDefineLang_rust.xml' 
2. press 'Raw' for view ASCII code: link https://raw.githubusercontent.com/pfalabella/Rust-notepadplusplus/master/userDefineLang_rust.xml
3. select All (press Ctrl-A)
4. copy code (press Ctrl-C)
5. paste in Notepad++ (press Ctrl-V)
6. save code with name 'rust.xml'
7. put 'rust.xml' inside '\functionList' folder
8. restart Notepad++
9. done

Thanks

**Comment by chcg** [comment]
It seems this matches better to be published at https://github.com/notepad-plus-plus/userDefinedLanguages.

**Comment by ArkadiuszMichalski** [comment]
Where is your debug info? Rust was added long time ago:
![image](https://user-images.githubusercontent.com/2730894/109397592-bd3d3780-7937-11eb-9117-398cab66c5eb.png)

**Comment by skarsgal** [comment]
@ArkadiuszMichalski
Yes, Rust is present in language list (supported language).

@chcg 
in UDL there is no Rust.
I have'nt found Rust.xml inside \Notepad\functionList, so there is'nt syntax highlighting and and I thought it might be useful to others.
But this is not essential.
You can close this issue.
Thanks.

**Comment by chcg** [comment]
See
https://github.com/notepad-plus-plus/notepad-plus-plus/blob/52e8c68f901e1dadaeb342bf38940779448277ec/PowerEditor/src/langs.model.xml#L330-L337
for the keyword definition of the builtin scintilla lexer.

For autocompletion support a file rust.xml at https://github.com/notepad-plus-plus/notepad-plus-plus/tree/master/PowerEditor/installer/APIs is needed.
And for functionlist another one at https://github.com/notepad-plus-plus/notepad-plus-plus/tree/master/PowerEditor/installer/functionList

**Comment by skarsgal** [comment]
@chcg
this means:
1. that you have to make the changes on https://github.com/notepad-plus-plus/notepad-plus-plus/tree/master/PowerEditor/installer (API + functionList)
2. that the rust.xml file that I put in the '\ functionList' folder should work.
Quite right ?

**Comment by chcg** [comment]
@skarsgal 
ad 1. This is missing and someone with expertise in rust would be good to provide it. Additionally it then has to be added to the installer folders and the install script needs to be extended.
ad 2. Seems your description above at point 7. is not correct. The link provides just an UDL xml file which needs to be placed at \userDefineLangs. In the repo there is no xml with descriptions for functionlist parsing, see also https://github.com/notepad-plus-plus/notepad-plus-plus/issues/9698#issuecomment-806426838 about how the functionlist could look like.

**Comment by skarsgal** [comment]
**@chcg** 
I found online the source code of a simple Rust parser: 
• see https://adriann.github.io/rust_parser.html
• see https://github.com/adrianN/simple_rust_parser (press **↓ Code** then Download ZIP) 
downloaded archive contains the file 'main.rs'.
I have tried to compile it with an 'Online Rust Compiler', https://paiza.io/en/languages/rust and it seem ok.
I don't use rust but i would like to learn it.

**Comment by mere-human** [comment]
Scintill already does parsing for Rust.

**Comment by chcg** [comment]
As said above the original issue on syntax highlighting is not existing and for the remaining functionlist\autocompletion resources their exists already the issue #9698.
