### ISSUE TITLE
Notepad++ has problems with display of chars in UTF8 and UTF16-LE

### ISSUE THREAD

**Issue by HarKe298** [notepad-plus-plus/notepad-plus-plus#9597]
### Description of the Issue
I have export files which displayed as "UTF-16 LE" in Windows-Notepad.
This program show all chars correctly but I need the functionality of line sorting from Notepad++.
NPP show wrong sign for e.g.: "⁇�"
NPP show the file encoding "UCS-2 LE". This seams to be ok.

![npp-encoding-error](https://user-images.githubusercontent.com/79909084/109637855-9f492000-7b4d-11eb-9196-6e02d55dc872.jpg)

I canot use NPP for this file with this encoding.
What I have to do to work with my export files with this encoding?

### Steps to Reproduce the Issue

1. Open the file: 
[⁇🅟-Language.csv.txt](https://github.com/notepad-plus-plus/notepad-plus-plus/files/6068065/-Language.csv.txt)
with Notepad and with NPP and compare the content visually.

2. 
3. 

### Expected Behavior

The chars should show correctly and save with minimal changings should create a valid usable file with neccessary chars.

### Actual Behavior

Work with this file will destroy the content of this file.

### Debug Information

Notepad++ v7.9.1   (32-bit)
Build time : Nov  2 2020 - 01:03:56
Path : C:\@\PortableApps\Notepad++Portable\App\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS Name : Windows 10 Enterprise (64-bit) 
OS Version : 1909
OS Build : 18363.1379
Current ANSI codepage : 1252
Plugins : AutoSave.dll BigFiles.dll ComparePlugin.dll DSpellCheck.dll HexEditor.dll HTMLTag_unicode.dll JsMapParser.NppPlugin.dll linefilter2.dll Linefilter3.dll mimeTools.dll NppConverter.dll NppExport.dll NPPJSONViewer.dll nppplugin_svn.dll NppXmlTreeviewPlugin.dll urlPlugin.dll VisualStudioLineCopy.dll XMLTools.dll XPatherizerNPP.dll

**Comment by ArkadiuszMichalski** [comment]
@donho 
I get a crash when try open above `.txt` file and last NPP with new Scintilla:

![image](https://user-images.githubusercontent.com/2730894/109641422-f9e47b00-7b51-11eb-9adb-be75d92f77bd.png)

@HarKe298 

What if you try with this option?

![image](https://user-images.githubusercontent.com/2730894/109641836-75462c80-7b52-11eb-9972-bd9fc14e9667.png)

**Comment by GOLEM777** [comment]
Off Autodetect character encoding!

**Comment by HarKe298** [comment]
Coding detection is ok and if it wrong it is possible to change it manually.
I think it should work with and w.o. Autodetect.

**Comment by HarKe298** [comment]
Independend of the option DirectWrite. Same behavior.
New Workaround: 
 - open with notepad
 - "save as" with UTF8
 - open with NPP, change, store and back

**Comment by ArkadiuszMichalski** [comment]
Maybe because Notepad++ used UCS-2 not UTF-16?
https://github.com/notepad-plus-plus/notepad-plus-plus/issues/8612

**Comment by Uhf7** [comment]
Actually, there are two problems here. Both have nothing to do with the new SciLexer.dll.

Problem 1: The poor display of the text. This is, because the Utf-8 / Utf-16 converters in `Utf8_16.cpp` don't know Utf-16 surrogates. So all code points above U+10000 leading to wrong encoding. The character causing the problems in the example file is the "Negative Circled Latin Capital Letter P", `U+1F15F`, Utf-8-encoded `F0 9F 85 9F`, UTF-16-encoded `D83C DD5F`. Since the conversion functions can't handle 4-byte Utf-8 codes and 2-word Utf-16 codes, invalid encodings lead to invalid display results.

Problem 2: The assertion. This occurs in debug versions only and actually does no harm in this case. The assertion is raised in the `Notepad_plus::addHotSpot`, because a text which was converted from UTF-8 to WideChar with `MultiByteToWideChar` didn't convert back to it's original state with `WideCharToMultiByte`. After fixing the surrogate problem in the conversion routines, the assertion is not triggered anymore.

Preparing a PR for it...

**Comment by HarKe298** [comment]
Thanks for the explanation, but I wrote in the problem description problems with chars in UTF8 and UTF16.
Now I will show the problems with UTF8. I had created a file with all possible characters of UTF8 and a lot of chars will not displayed correctly. If I add a char left of the not displayed char(s) then its sometimes possible to see the character.
That means that the not displayed chars are exists and known but they will not show (see in screenshot line 0001C0). I have the line 2 times. First line without additional char and second line add a first additional char. Then I can see all chars in this line.
I suppose this is a wrong behavior. This behavior is the same since years. And the numbers of shown chars have not big values.
![UTF8-Errors](https://user-images.githubusercontent.com/79909084/109780260-21494f80-7c07-11eb-950b-78dc8a7a7226.jpg)

[GenUTF8-Select.txt](https://github.com/notepad-plus-plus/notepad-plus-plus/files/6074698/GenUTF8-Select.txt)

**Comment by Uhf7** [comment]
@HarKe298,

There are different problems here. The first one, which you described in the head of the issue, is an encoding problem. The Utf-16 input is not converted correctly into the edit buffer. This I can solve.

The second one is a display problem. Unfortunately, I cannot reproduce this on my system right now, but I've seen such things before...

**Comment by HarKe298** [comment]
@Uhf7 
Thanks for the answer. Do you saw the pending source text file below the screenshot for reproducing this visual appearence?

**Comment by Uhf7** [comment]
> Do you saw the pending source text file below the screenshot for reproducing this visual appearence?

Yes, I tried `GenUTF8-Select.txt`. On my system, both `0001C0` lines are displayed equally and I could not find any font or setting to reproduce the effect. Perhaps you could post what font you use.

Similar effects have been discussed already in #3747 and #5754.

**Comment by HarKe298** [comment]
@Uhf7 
Thanks. I currently use "Lucida Console", why this is a monospace font, efficient size on screen for programming and standard font.

**Comment by Uhf7** [comment]
@HarKe298, I cannot reproduce the display problem documented in your screen shot. Not with Lucida console. I tried on a Windows 7 system too, no success in reproducing it. Sorry for that, I see that the problem is there on your system, but I don't know why.

**Comment by HarKe298** [comment]
This problem is on c.a. 10 systems on various windows and NPP versions the same. How can I help to reproduce this behavior.

**Comment by ptr2null** [comment]
> @HarKe298, I cannot reproduce the display problem documented in your screen shot. Not with Lucida console. I tried on a Windows 7 system too, no success in reproducing it. Sorry for that, I see that the problem is there on your system, but I don't know why.

Stumbled upon this bug and I can reproduce the display problem with the GenUTF8 file with a vanilla npp setup on windows 10 (tested with german version and US english version; both same result)
![Confirm_File_Display](https://user-images.githubusercontent.com/25789839/110813705-0cb12b00-8289-11eb-8f40-c54b5fff64ad.png)

I use latest version of NPP and default font is Courier New.

**Comment by sasumner** [comment]
@ptr2null Courier New is not going to be able to show all of these characters correctly.  Your font mileage can and will vary.

Also, anyone commenting on "will display" or "won't display" should indicate what their "Direct Write" setting is, see redbox here: https://github.com/notepad-plus-plus/notepad-plus-plus/issues/9597#issuecomment-788837868

**Comment by ptr2null** [comment]
@sasumner Forget my post. It is indeed a font thing. I checked every possibility now and as you say the characters are shown correctly.
 
@HarKe298 It should be a font issue as far I've tested it. Make sure to change the style configuration accordingly. Just test it by switching the global font the to make sure you see most of the characters.

**Comment by Uhf7** [comment]
@HarKe298, @ptr2null,

I'm  interested here to know how the original test for the problem works on your system.

It's described here: https://github.com/notepad-plus-plus/notepad-plus-plus/issues/3747#issue-258378939. The question is, what happens, if you copy "☆◬⊗⊠⋆⧆⨂" into your new document and then you delete the "☆".  My system behaves as follows:
- If the "Use Direct Write" setting is on, everything is fine.
- If the "Use Direct Write" setting is off, then after deleting the "☆", all other characters are displayed as squares. The font I use for this test is "Courier New".

**Comment by donho** [comment]
@ArkadiuszMichalski 
> I get a crash when try open above .txt file and last NPP with new Scintilla:

Sorry for not reading you on time.
I just merge the fix of @Uhf7, could you please confirm me if the crash is fixed?

**Comment by ArkadiuszMichalski** [comment]
@donho 
Fixed, no assertion popup.

**Comment by ValZapod** [comment]
38bf76e does not actually fix #3747.
