### ISSUE TITLE
add to "Debug Info"

### ISSUE THREAD

**Issue by pryrt** [notepad-plus-plus/notepad-plus-plus#9598]
Would you be willing to add two lines to the Debug Info?
1. `Cloud Config: OFF` or `Cloud Config: "c:\path\to\cloud\folder"`, depending on the cloud settings
2. if `-settingsDir` is set, show `SettingsDir Option:` as either `OFF` or `"c:\path\to\settings.dir\"`

Similar to `Local Conf` and `Admin Mode`, those would help us recognize right away whether someone who has a problem with config settings is just not looking at the files in the right folder.

(While answering https://community.notepad-plus-plus.org/topic/20821, trying to figure out why settings weren't getting saved, I was about to ask whether the user had Cloud enabled... though I stopped, because it doesn't look like he's using cloud, and I didn't want to confuse him further.  But if Cloud and now `-settingsDir` information were always available in Debug Info, it would eliminate us having to ask that question. )

**Comment by mere-human** [comment]
This perfectly makes sense to me.

> 2\. if `-settingsDir` is set, show `SettingsDir Option:` as either `OFF` or `"c:\path\to\settings.dir\"`

Perhaps, it would be even better to add all the command line options that were specified?

**Comment by mere-human** [comment]
@sasumner Could you, please, assign it to me? I can do it in a few days.

**Comment by sasumner** [comment]
Please also proceed with your "add all the command line options" idea.
