### ISSUE TITLE
Bugs with section «periodic backup» and relative path in config.xml

### ISSUE THREAD

**Issue by Nick-1231** [notepad-plus-plus/notepad-plus-plus#9600]
### Description of the Issue

Hello!
I found some bugs in Notepad++ v7.9.3 x64 Portable (last stable):
1) Periodic backup doesn`t work without "Remember current session for next launch" option (look at the screenshot)
2) In file «config.xml»:
GUIConfig name="stylerTheme" path="D:\Folder1\Folder2\Notepad++\themes\Solarized.xml"
This is «absolute path». So **if I move the «Notepad++» folder** to a different location, the theme is reset to default! And **if I rename folder** with Notepad++ theme is reset to default too…
So in this section (in file «config.xml») must be a relative path!!!

### Steps to Reproduce the Issue

1. Open preferences --> Backup --> Remember current session for next launch --> uncheck
2. Section "enable periodic backup" is become inactive! (this is wrong).
--
Look at the file "config.xml". Pathes in it`s file are not relative... For example attribute "GUIConfig name=" stylerTheme"...

### Expected Behavior

A) Option "enable periodic backup" must be independent from option "Remember current session for next launch".
B) At least in portable version of Notepad++ in files (for example "config.xml") must be relative pathes!

### Actual Behavior

The periodic backup option is associated with saving sessions (it`s wrong).
In a section (in file «config.xml») absolute pathes (must be a relative pathes).

### Debug Information

Notepad++ v7.9.3   (64-bit)
Build time : Feb 14 2021 - 03:15:58
Path : D:\Folder1\Folder2\Notepad++\notepad++.exe
Admin mode : ON
Local Conf mode : ON
OS Name : Windows 10 Enterprise (64-bit) 
OS Version : 2009
OS Build : 19042.804
Current ANSI codepage : 1251
Plugins : mimeTools.dll NppConverter.dll NppExport.dll 

![Image](https://user-images.githubusercontent.com/58604650/109825570-013b7f80-7c4b-11eb-80b9-f9688c246261.png)

![Image2](https://user-images.githubusercontent.com/58604650/109827673-fda8f800-7c4c-11eb-85b6-24bb1af570b7.png)

**Comment by sasumner** [comment]
In the future, please make one issue per topic.  You had two topics.

Topic 1:  This behavior is "by design"

Topic 2:  Known issue; see #6092
