### ISSUE TITLE
"Show All Characters" display mode doesn't show all characters

### ISSUE THREAD

**Issue by mishka88ru** [notepad-plus-plus/notepad-plus-plus#9601]
Hello!

### Description of the Issue
"Show All Characters" display mode doesn't show all characters.

### Steps to Reproduce the Issue
Open the file attached below and enable "Show All Characters" mode.

[Carl orff -Carmina Burana  ⁄Koninklijke Chorale Cæcilia.txt](https://github.com/notepad-plus-plus/notepad-plus-plus/files/6078877/Carl.orff.-Carmina.Burana.Koninklijke.Chorale.Caecilia.txt)

### Expected Behavior
I want to see invisible characters in "Show All Characters" mode.

### Actual Behavior
It does not print those characters.

![изображение](https://user-images.githubusercontent.com/44462629/109865143-c2baba80-7c74-11eb-9065-2ab917ca9683.png)

### Debug Information
Notepad++ v7.9.3   (64-bit)
Build time : Feb 14 2021 - 03:15:58
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : ON
Local Conf mode : OFF
OS Name : Windows 7 Ultimate (64-bit) 
OS Build : 7601.23846
Current ANSI codepage : 1251
Plugins : DSpellCheck.dll mimeTools.dll NppConverter.dll NppExport.dll

**Comment by sasumner** [comment]
The character in your screenshot is U+200B, a UTF-8 "Zero Width Space".
"Show All Characters" currently means to show U+0020 (normal space) as an orange dot, U+0009 (tab) as an orange right-pointing arrow, and line-ending characters as inverse video `CR` and/or `LF`.
In the future, this will be extended to show characters like the one you show; the controlling issue for this is #8284
Closing as duplicate.
