### ISSUE TITLE
I don't understand how regex conditional expression works

### ISSUE THREAD

**Issue by GhbSmwc** [notepad-plus-plus/notepad-plus-plus#9602]
This: https://npp-user-manual.org/docs/searching/
![image](https://user-images.githubusercontent.com/13095760/110063764-c06e6400-7d39-11eb-8c20-46a8ac24a75d.png)
This following GIF shows that the _NoPattern_ expression is always used:
![ConditionalRegex](https://user-images.githubusercontent.com/13095760/110064022-47234100-7d3a-11eb-8840-9a27c39b62e3.gif)

**Comment by sasumner** [comment]
This is not an "issue", this is a "question".
Please take questions to https://community.notepad-plus-plus.org/

**Comment by GhbSmwc** [comment]
oh, ok.
