### ISSUE TITLE
[v793 all] FunctionList empty on Windows 1809

### ISSUE THREAD

**Issue by sky5walk** [notepad-plus-plus/notepad-plus-plus#9603]
### Description of the Issue
All attempts leave the Function List empty?
And there is no action if double clicking in the empty area.
Just in case it is a color issue.
I am using dark mode.

### Steps to Reproduce the Issue
Tried installer and portable versions.

### Expected Behavior
Function List viewable.

### Actual Behavior
Function List empty.

### Debug Information
Notepad++ v7.9.3   (64-bit)
Build time : Feb 14 2021 - 03:15:58
Path : C:\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : ON
OS Name : Windows 10 Enterprise LTSC 2019 (64-bit) 
OS Version : 1809
OS Build : 17763.1757
Current ANSI codepage : 1252
Plugins : mimeTools.dll NppConverter.dll NppExport.dll

**Comment by sasumner** [comment]
>All attempts leave the Function List empty?

Insufficient information to even attempt to look into this.
If additional valid information is provided, will consider reopening.

**Comment by sky5walk** [comment]
I have working settings for functionlist on several other PC's but they are running newer Windows 10.
The failing PC's all have Windows 10 v1809.
Is this a possible antivirus issue?

**Comment by sky5walk** [comment]
My user defined language lexer is working fine.
Only the functionlist fails.

**Comment by sky5walk** [comment]
What more information is required?

**Comment by sky5walk** [comment]
Ok, I see C++ functions listed.
Where is the delta configuration for functionlist best obtained?
The same settings copied from pc-pc don't work. :(

**Comment by sky5walk** [comment]
Ok, the error was in my overrideMap.xml. Wrong lang name.
Hope this helps someone in the future.
