### ISSUE TITLE
Basic FIND feature not working on .sql files

### ISSUE THREAD

**Issue by alexhentea** [notepad-plus-plus/notepad-plus-plus#9604]
### Description of the Issue
Basic text Find will return "can't find the text" even though the text is obviously in the file. Happens for .sql files, not reproducible on .txt files with same content.
This is happening on multiple .sql files. The files are ~300k lines each. The text is approx on line 50k. I typed the search content by hand, as well as copied it from the file itself, and it would still not find it. 
In testing I found that shis is happening on the file if the extension is .sql, but will not happen if I change the extension to .txt.
Changed the extension back to .sql and it happens again. I was able to reproduce this on a test file - at the bottom of this issue you can find a chunk of text that you can use to reproduce.
For other keywords, find would work just fine.

### Steps to Reproduce the Issue

1. Create a .sql file wit the content I included at the bottom
2. Press Ctrl + F then search for "networking_requests_bulk" (without quotes)
3. Change the file extension from .sql to .txt then attempt the same search

### Expected Behavior
Text to be found and for the cursor to jump to the respective position

### Actual Behavior
Find returns "Can't find the text "networking_requests_bulk"

### Debug Information
Notepad++ v7.7.1   (32-bit)
Build time : Jun 16 2019 - 21:14:50
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10 (64-bit)
Plugins : ComparePlugin.dll mimeTools.dll NppConverter.dll NppExport.dll 

Content used to create a test file:

> end;
/
prompt --application/shared_components/data_loading/tables/oci_networking_requests_bulk_input
begin

**Comment by sasumner** [comment]
Following the STR...

Works for me, in 7.9.3, successful hit:

![image](https://user-images.githubusercontent.com/30118311/110142043-c0a34980-7da3-11eb-9937-b9f95fccc4c3.png)

**Comment by ArkadiuszMichalski** [comment]
I can't reproduce. @alexhentea Try update to the latest Notepad++ 8.1.4 or make test on last portable ([read how](https://github.com/notepad-plus-plus/notepad-plus-plus/wiki/Testing#using-the-latest-release-portable-version-of-notepad)). If the problem still exists then let me know, I will reopen this issue.
