### ISSUE TITLE
Project workspace changes lost on save cancel

### ISSUE THREAD

**Issue by sasumner** [notepad-plus-plus/notepad-plus-plus#9605]
### Description of the Issue

When attempting to quit Notepad++ with a project workspace that has unsaved changes, a prompt appears to ask you if you want to save.  If you say Yes, you are presented with a FileSave dialog.  If you cancel this dialog you will lose the opportunity to save your changes, and Notepad++ exits (but it is nice in that it informs you).

### Steps to Reproduce the Issue
1. Start with no Project panels open and only a single `new 1` tab open that is blue (no mods).
2. Open a Project panel, e.g. `Project 2`, via `View` menu > `Project` > `Project Panel 2` to see:
![image](https://user-images.githubusercontent.com/30118311/110158830-dd497c80-7db7-11eb-94e8-54aec7b416d1.png)
3. Rightclick the word `Workspace` and choose `Add New Project` :
![image](https://user-images.githubusercontent.com/30118311/110158939-0407b300-7db8-11eb-90cb-ba1310c0a5bc.png)
4. Accept the default value of "Project Name" to see:
![image](https://user-images.githubusercontent.com/30118311/110159037-27caf900-7db8-11eb-87a1-32fbb7662bbb.png)
Note that the workspace icon has turned red, indicating unsaved changes.
5. Attempt to exit N++ by clicking the main window's `X` in the upper right corner.  N++ will prompt you:
![image](https://user-images.githubusercontent.com/30118311/110159181-5e087880-7db8-11eb-9f02-ef9340eba5fb.png)
6. Click `Yes`
7. A FileSave dialog appears and has two buttons `Save` and `Cancel`.
8. Press `Cancel`.
9. N++ displays:
![image](https://user-images.githubusercontent.com/30118311/110159363-9c059c80-7db8-11eb-8bd5-f418d1ac177c.png)
10. Press `OK`

### Actual Behavior
Notepad++ exits

### Expected Behavior
I expected Notepad++ to continue running, so that I could save my workspace changes at some future point in time, and not lose them.

For illustration of correct behavior, note what happens in a similar situation when you have a modified tab:
If your settings are such that if you have a red `new 1` file and you attempt to quit N++, you will see:
![image](https://user-images.githubusercontent.com/30118311/110159987-68774200-7db9-11eb-8e35-5d266f978f6e.png)
If you click `Yes` you are presented with a FileSave dialog appears and has two buttons `Save` and `Cancel`.
If you then press `Cancel` N++ does not exit, giving you the opportunity to still save the changes to this file.

### Debug Information
Notepad++ v7.9.3   (64-bit)
Build time : Feb 14 2021 - 03:15:58
Path : C:\...........\npp.7.9.3.portable.x64\notepad++.exe
Admin mode : OFF
Local Conf mode : ON
OS Name : Windows 10 Enterprise (64-bit) 
OS Version : 1909
OS Build : 18363.1316
Current ANSI codepage : 1252
Plugins : mimeTools.dll NppConverter.dll NppExport.dll

**Comment by Uhf7** [comment]
I can reproduce it. It's not nice. I'm investigating...
