### ISSUE TITLE
NPP ignores # (hash) part when opening/executing links

### ISSUE THREAD

**Issue by dogancelik** [notepad-plus-plus/notepad-plus-plus#961]
Mega.co.nz links use hash part to work but when I double click on the links NPP ignores hash part:

```
https://mega.co.nz/#!AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
```

It works if you remove `!` after `#`

**Comment by jannick0** [comment]
Appears to solved in NPP 7.5.9 (32bit).

**Comment by chcg** [comment]
@dogancelik Could you confirm that this issue is fixed?

**Comment by dogancelik** [comment]
Yes it's fixed, thanks. @chcg
