### ISSUE TITLE
English localization for v7.9.4

### ISSUE THREAD

**Issue by donho** [notepad-plus-plus/notepad-plus-plus#9613]
Here the diff of English localization for v7.9.4 (vs v7.9.3):

_[Edit] Sorry, the previous one is an incorrect file. this one is the correct diff file:_  
[fixed-793vs794.zip](https://github.com/notepad-plus-plus/notepad-plus-plus/files/6097727/fixed-793vs794.zip)

**Comment by GOLEM777** [comment]
**793vs794.zip** file contains original english.xml 7.9.3 without changes.

**Comment by ArkadiuszMichalski** [comment]
@donho 
7.9.3 should be change to 7.9..4

```<Native-Langue name="English" filename="english.xml" version="7.9.3">```

**Comment by RockyTDR** [comment]
> 
> 
> @donho
> 7.9.3 should be change to 7.9..4
> 
> `<Native-Langue name="English" filename="english.xml" version="7.9.3">`

@donho see comment of @GOLEM777

**Comment by donho** [comment]
Thank you guys for the heads up. It's fixed now.
