### ISSUE TITLE
Text completion is a problem on large files

### ISSUE THREAD

**Issue by kerosin75** [notepad-plus-plus/notepad-plus-plus#9620]
### Description of the Issue
While the text complition in notepad++ in itself is a very usefull feature, it makes notepad++ almost anusable for large files (50 - 500 MB).

### Steps to Reproduce the Issue
Open a text file with very many different words, try to type, wait for up to 15 s until notepad++ is responsive again.
I know I can globaly disable the text completion, but it would be great if we could have a setup option up to which file size text completion is activated.

**Comment by sasumner** [comment]
Closing as duplicate.
