### ISSUE TITLE
File Open/Save dialog is not displayed on Windows Server Core 2016

### ISSUE THREAD

**Issue by mere-human** [notepad-plus-plus/notepad-plus-plus#9621]
File dialogs are not shown at all. The issue wasn't present in v.7.9.2.
Originally, reported on Community Forum: https://community.notepad-plus-plus.org/post/63697

### Steps to Reproduce the Issue

1. File > New, Type some text
2. File > Save

### Expected Behavior

Save As dialog is shown.

### Actual Behavior

No dialog shown.

### Debug Information

Notepad++ v7.9.3   (64-bit)
Build time : Mar  6 2021 - 12:16:21
Path : Z:\Development\notepad-plus-plus\PowerEditor\visual.net\x64\Unicode Debug\notepad++.exe
Command Line : 
Admin mode : ON
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows Server 2016 Datacenter (64-bit) 
OS Version : 1607
OS Build : 14393.4169
Current ANSI codepage : 1252
Plugins : none

**Comment by mere-human** [comment]
When I debug it remotely on Windows Server Core VM, the `CoCreateInstance()` call [here](https://github.com/notepad-plus-plus/notepad-plus-plus/blob/master/PowerEditor/src/WinControls/OpenSaveFileDialog/CustomFileDialog.cpp#L530) returns `CLASS_E_CLASSNOTAVAILABLE` error.

**Comment by sasumner** [comment]
Upvoting "potential solution 2"

**Comment by donho** [comment]
Damn!

**Comment by donho** [comment]
@mere-human 
Is there a way to detect if Notepad++ is under `Windows Server Core 2016` ?

**Comment by mere-human** [comment]
> Is there a way to detect if Notepad++ is under `Windows Server Core 2016` ?

@donho 
Yes. There are different ways. A preferred way is to query a registry key:

> In Server Core for Windows Server 2012 and later, the recommended way to determine Server Core is configured is to check these registry values:
> ```
>   HKEY_LOCAL_MACHINE
>    Software
>       Microsoft
>          Windows NT
>             CurrentVersion
>                Server
>                   ServerLevels
>                      NanoServer = 1
>                      ServerCore = 1
>                      Server-Gui-Mgmt = 1
>                      Server-Gui-Shell = 1
> ```

https://docs.microsoft.com/en-us/previous-versions/windows/desktop/legacy/hh846315(v=vs.85)

**Comment by github-tomster** [comment]
@donho 
just a kind reminder. i always downgrade to the working version 🤷🏻‍♂️

**Comment by donho** [comment]
@mere-human 
Even Windows Server Core 2016 can be detected, what can we do to show the dialog?

**Comment by mere-human** [comment]
> @mere-human Even Windows Server Core 2016 can be detected, what can we do to show the dialog?

@donho Please, see my earlier comment
https://github.com/notepad-plus-plus/notepad-plus-plus/issues/9621#issuecomment-793048557
Besides using a legacy file dialog and doing nothing, maybe we can try to manually copy a comdlg32.dll on the Windows Core and see if it helps.

**Comment by donho** [comment]
OK, as the solution 2, so this issue can be closed.

**Comment by github-tomster** [comment]
i am confused 😕 
by accident i just installed N++ 8.3.3 on a server core2022 [10.0.20348.643]
typed text, clicked the disk icon to save and the dialog shows up 😸 

does:
> OK, as the solution 2, this issue can be closed.

mean, the N++ code was optimized with:
`... call ShowDialogEx() instead of ShowDialog().`
from [here](https://github.com/microsoft/dotnet-framework-early-access/issues/23#issuecomment-393134611) and this issue is solved ❔ 🤔 

or m$ changed core2022 [10.0.20348.643]
and it works now on core2022 only ❓  🤷🏻‍♂️

unfortunately m$ did 🙄 
i made a test and N++8.3.3 wont open the dialog on core2019 😿 

resume: 
- on server core <= 2019 last working N++ is version 7.9.2
- on server core >= 2022 latest N++ works

and wouldnt it be clever to add the **WONTFiX** label 😉
