### ISSUE TITLE
"..." button in "Find in Files" won't open dialog box to select a directory if current "Directory" path is bad

### ISSUE THREAD

**Issue by BLTSIZE** [notepad-plus-plus/notepad-plus-plus#9630]
### Description of the Issue

Clicking the "..." button near the "Directory" field in the "Find in Files" dialog box won't open the dialog box to select a folder if the current folder in the "Directory" field does not exist anymore.

### Steps to Reproduce the Issue

1. Using Notepad (and not Notepad++ !) open %APPDATA%\Notepad++\config.xml and remove every children from the FindHistory element. Save the file.
2. Create a directory "C:\Temp\NotepadPlusPlusIsSoGreat".
3. Launch Notepad++.
4. Select "Search" than "Find in files..." in the menu. This opens the "Find in files" dialog box.
5. Click on the "..." button near "Directory". This opens a dialog box to select a folder.
6. Navigate to "C:\Temp\NotepadPlusPlusIsSoGreat" and validate to select the folder. This closes the dialog box.
7. Press ESC to close the "Find in files" dialogbox.
8. Switch to Explorer and delete the "C:\Temp\NotepadPlusPlusIsSoGreat" directory.
9. Back in Notepad++, select "Search" than "Find in files..." in the menu. This opens the "Find in files" dialog box. Notice that the path "C:\Temp\NotepadPlusPlusIsSoGreat" appears in the "Directory" field.
10. Click on the "..." button near "Directory". The dialog box to select the folder won't open.

### Expected Behavior

The dialog box to select the folder should open, whatever is the path in the "Directory" field (deleted directory, bad path, and so on).

### Actual Behavior

The dialog box to select the folder did not open after the directory which path appears in the in the "Directory" field has been deleted.

### Debug Information

Notepad++ v7.9.3   (64-bit)
Build time : Feb 14 2021 - 03:15:58
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS Name : Windows 10 Pro (64-bit) 
OS Version : 1909
OS Build : 18363.1379
Current ANSI codepage : 1252
Plugins : mimeTools.dll NppConverter.dll NppExport.dll

**Comment by sasumner** [comment]
See [HERE](https://community.notepad-plus-plus.org/topic/20854/notepad-7-9-4-rc) where it says:

![image](https://user-images.githubusercontent.com/30118311/110627768-5c500380-8170-11eb-8e94-47c39f63144e.png)
