### ISSUE TITLE
save buffer disabled after new buffer created and "saved as" the first time

### ISSUE THREAD

**Issue by dwharton2016** [notepad-plus-plus/notepad-plus-plus#9634]
### Description of the Issue

Noticed that after creating a new buffer and using "save as" that any changes would not be detected and the CTRL-S had no effect.  I was using CTRL-S as an automatic keystroke and after loosing many changes after exiting N++ and re-entering I realized there was a case in which my buffers were not being saved.
### Steps to Reproduce the Issue

1. Create a new buffer
2. Place some text in the new buffer
3. Use "save" or "save as" to create the new file and save to disk
4. Keep editing the newly saved and named buffer in N++, no new changes will be detected as a change and you cannot save the buffer
5. if you close the buffer and re-open it, the only changes that are present are the first ones you saved using "save as"
6. If you close the buffer then reopen it, you can save changes as normal.

### Expected Behavior

I expected the buffer to detect new changes after saving it for the first time.  I have been losing changes over a period of months and didn't understand why - I had thought I was just being careless - until I found the way to recreate the issue.
### Actual Behavior

The changes were not detected, ever, as long as the buffer was open, it had to be closed then reopened for changes to be detected again.
### Debug Information

Notepad++ v7.9.3   (64-bit)
Build time : Feb 14 2021 - 03:15:58
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS Name : Windows 10 Enterprise (64-bit) 
OS Version : 1709
OS Build : 16299.2166
Current ANSI codepage : 1252
Plugins : BookmarksDook.dll mimeTools.dll NppConverter.dll NppExport.dll NppXmlTreeviewPlugin.dll SessionMgr.dll

**Comment by sasumner** [comment]
You use the SessonMgr plugin, so I think this is the same problem as #9475 deals with, which is fixed in 7.9.4 (the RC anyway), see [HERE](https://community.notepad-plus-plus.org/topic/20854/notepad-7-9-4-rc) and note point number 9.

**Comment by alankilborn** [comment]
This should have been fixed with the release of 7.9.4.
Suggest CLOSURE of this issue.
