### ISSUE TITLE
Manual refresh for "Folder as Workspaces" with network drives

### ISSUE THREAD

**Issue by timvdh** [notepad-plus-plus/notepad-plus-plus#9638]
### Description of the Issue
While the workspaces immediately pick up changes from local drives, at least some types of network drives will never trigger a refresh (I noticed this issue with DFS drives). This may be an OS or security issue. A manual refresh (e.g. button and/or context menu) would be of great help then.

### Steps to Reproduce the Issue
View -> Enable "Folder as Workspace" -> Right click into workspace pane -> Add network drive (e.g. \\share\folder) -> Add file or folder to network folder

### Expected Behavior
The new file or folder appears in the workspace folder OR it is possible to manually refresh selected / all folders without restarting Notepad++

### Actual Behavior
No refresh of the workspace folder, no way to manually refresh

### Debug Information
Notepad++ v7.9.3   (64-bit)
Build time : Feb 14 2021 - 03:15:58
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS Name : Windows 10 Enterprise (64-bit) 
OS Version : 1809
OS Build : 17763.1757
Current ANSI codepage : 1252
Plugins : ComparePlugin.dll mimeTools.dll NppConverter.dll NppExport.dll NPPJSONViewer.dll XMLTools.dll

**Comment by xaviermdq** [comment]
Equivalent to issue #9209. Perhaps it is a technical limitation of Windows: that there is no event that is triggered when there is a change in network folders. But, a manual update button or regular automatic update (every 5 seconds for example) would be a good solution.

**Comment by sasumner** [comment]
Closing as duplicate of 9209
