### ISSUE TITLE
Automatic clear or hide previouse search result in Search results window when we search again

### ISSUE THREAD

**Issue by ArkadiuszMichalski** [notepad-plus-plus/notepad-plus-plus#9641]
### Description of the Issue
When we search for something multiple times, the Search results window  also shows the previous results.  For me, these previous results are redundant and unnecessarily clutter my search results window. It would be nice if the previous results were automatically cleared or hidden on the next search. 

Enabling or disabling this behaviour can be given in `Preferences > Searching` or in the context menu in the search results window (as a toggle). 

### Steps to Reproduce the Issue

1. Open NPP and some file, like `license.txt`
2. Few time search something, like `IMPORTANT`.

We see below results:
![image](https://user-images.githubusercontent.com/2730894/110864750-d2fd1600-82c2-11eb-87b0-0706df59eb53.png)

### Expected Behavior
Option to clear or hide previous search results.  In the example above, the latter three collapsed results. 

### Actual Behavior
Such option does not exist. 

### Debug Information
```
Notepad++ v7.9.3   (32-bit)
Build time : Feb 22 2021 - 23:28:49
Path : D:\_test\NPPClean\notepad++.exe
Admin mode : ON
Local Conf mode : ON
OS Name : Windows 7 Ultimate (64-bit) 
OS Build : 7601.0
Current ANSI codepage : 1250
Plugins : none

```

**Comment by sasumner** [comment]
Ok, I'll do it for you. :-)

But...I feel this has been discussed before.  You are the expert of old issues--HAS it been?
How about a Community site reference?  It might give more weight to the request with @donho if some others have requested it as well.

**Comment by ArkadiuszMichalski** [comment]
Close as duplicate:
https://github.com/notepad-plus-plus/notepad-plus-plus/issues/8777
Further discussion can be conducted in the previous thread.
