### ISSUE TITLE
"Default Language" in Preferences is too narrow

### ISSUE THREAD

**Issue by sasumner** [notepad-plus-plus/notepad-plus-plus#9642]
### Description of the Issue

The UI element for _Default Language_ in the _Preferences_ > _New Document_ area is too narrow and "chops off" some of the longer content items.  There doesn't seem to be any reason why it can't be a bit wider.

![image](https://user-images.githubusercontent.com/30118311/110942187-753eed00-8307-11eb-8215-c9cb67596d60.png)

### Steps to Reproduce the Issue
1. Go to the _Settings_ menu
2. Choose _Preferences..._
3. In the box on the left, choose _New Document_
4. Drop down the _Default language_ box
5. Note that the longer entries are not fully or mostly visible

### Expected Behavior
Better visibility for longer items.

### Actual Behavior
Truncation for longer items.

### Debug Information
Notepad++ v7.9.3   (64-bit)
Build time : Feb 14 2021 - 03:15:58
Path : C:\\....\npp.7.9.3.portable.x64\notepad++.exe
Admin mode : OFF
Local Conf mode : ON
OS Name : Windows 10 Enterprise (64-bit) 
OS Version : 1909
OS Build : 18363.1316
Current ANSI codepage : 1252
Plugins : mimeTools.dll NppConverter.dll NppExport.dll

**Comment by sasumner** [comment]
Assigning myself, mainly so a tourist doesn't attempt to tackle this one. :-)

**Comment by ArkadiuszMichalski** [comment]
@sasumner This list can't be sorted? Wouldn't it be better if in the 1st position we have None (Normal), and next we have the sorted list?

**Comment by sasumner** [comment]
>This list can't be sorted? 

Not sure of the history of this...on why it isn't presented better.

>Wouldn't it be better if in the 1st position we have None (Normal), and next we have the sorted list?

Can't disagree...

>I can see that we can jump between different languages with the keys...

I never noticed that behavior, where, for example, pressing `a` repeatedly will jump between the entries that begin with "a".  Cool.

**Comment by ArkadiuszMichalski** [comment]
@sasumner
Still open?

**Comment by sasumner** [comment]
>Still open?

No, I guess Don forgot to close with acceptance of #9647 via this commit: https://github.com/notepad-plus-plus/notepad-plus-plus/commit/6bfe9d289c260498189c22b6d31a015e59abff85

Closing now...
