### ISSUE TITLE
[Regression Fix]  Make changes for Dynamic/Constant width line numbers in v7.9.2 backwards compatible with previous versions

### ISSUE THREAD

**Issue by dave-user** [notepad-plus-plus/notepad-plus-plus#9650]
### Description of the Issue

I am the developer of the Customize Toolbar plugin.   Customize Toolbar includes an additional toolbar button to toggle the display of the line number margin on or off.  This button no longer works due to changes in Notepad++ v7.9.2.

In Notepad++ 7.9.2, the operation of the IDM_VIEW_LINENUMBER message is not backwards compatible with previous versions.  It is no longer possible to toggle display of the line number margin by simply sending an IDM_VIEW_LINENUMBER message.  This is because of the changes made to support Dynamic/Constant width line numbers.

This means that Customize Toolbar can no longer toggle the display of the line number margin on or off.   This is causing inconvenience for users.

### Behaviour in Notepad++ v7.9.1 or earlier

The IDM_VIEW_LINENUMBER message simply toggled the display of the line number margin on or off.  Customize Toolbar could use this message to show or hide the line number margin.

### Behaviour in Notepad++ v7.9.2 or later

The IDM_VIEW_LINENUMBER message no longer toggles the display of the line number margin on or off.  This can only be done using the Display checkbox in the preferences dialog.  Customize Toolbar cannot show or hide the line number margin.

### Proposed changes to fix issue

By making the following changes, the original behaviour of IDM_VIEW_LINENUMBER could be maintained: 

#### PowerEditor/src/menuCmdID.h

Add:
  352    #define    IDM_VIEW_LINENUMBER_WIDTH          (IDM_VIEW + 109)

#### PowerEditor/src/NppBigSwitch.cpp

Replace:
2151            ::SendMessage(hwnd, WM_COMMAND, IDM_VIEW_LINENUMBER, 0);

With:
2151            ::SendMessage(hwnd, WM_COMMAND, IDM_VIEW_LINENUMBER_WIDTH, 0);

#### PowerEditor/src/NppCommands.cpp

Insert after 3431:
        case IDM_VIEW_LINENUMBER_WIDTH: 
        { 
            updateLineNumberWidth();
        } 
        break;

#### PowerEditor/src/WinControls/Preference/preferenceDlg.cpp

Replace:
  860                   ::SendMessage(_hParent, WM_COMMAND, IDM_VIEW_LINENUMBER, 0);
  864                   ::SendMessage(_hParent, WM_COMMAND, IDM_VIEW_LINENUMBER, 0);

With:
  860                   ::SendMessage(_hParent, WM_COMMAND, IDM_VIEW_LINENUMBER_WIDTH, 0);
  864                   ::SendMessage(_hParent, WM_COMMAND, IDM_VIEW_LINENUMBER_WIDTH, 0);

#### PowerEditor/src/ScintillaComponent/ScintillaEditView.h

Replace:
  461        else if (svp._lineNumberMarginShow)
  462        {
  463            updateLineNumberWidth();
  464        }
  465        else
  466        {
  467            execute(SCI_SETMARGINWIDTHN, _SC_MARGE_LINENUMBER, 0);
  468        }

With:
  461        else
  462        {
  463            updateLineNumberWidth();
  464        }

#### PowerEditor/src/ScintillaComponent/ScintillaEditView.cpp

Replace:
2742    if (svp._lineNumberMarginShow)

With:
2742    if (hasMarginShowed(_SC_MARGE_LINENUMBER))

**Comment by donho** [comment]
@dave-user 
The following ID should removed from `menuCmdID.h`
```
    #define    IDM_VIEW_LINENUMBER                (IDM_VIEW + 12)
    #define    IDM_VIEW_SYMBOLMARGIN              (IDM_VIEW + 13)
    #define    IDM_VIEW_FOLDERMAGIN               (IDM_VIEW + 14)
    #define    IDM_VIEW_FOLDERMAGIN_SIMPLE        (IDM_VIEW + 15)
    #define    IDM_VIEW_FOLDERMAGIN_ARROW         (IDM_VIEW + 16)
    #define    IDM_VIEW_FOLDERMAGIN_CIRCLE        (IDM_VIEW + 17)
    #define    IDM_VIEW_FOLDERMAGIN_BOX           (IDM_VIEW + 18)
```
since they are not part of menu.

**Comment by dave-user** [comment]
@donho

These ID's will need to be defined somewhere else, because they are used by some Notepad++ cpp modules.

Customize Toolbar adds "Hide Line Number Margin", "Hide Bookmark Margin" and "Hide Folder Margin" menu items to the Notepad++ "View" menu - and intercepts messages with these ID's to track the state of the margins. 

Because of the changes in Notepad++ 7.9.2, it is no longer possible to accurately track the state of the margins.

**Comment by donho** [comment]
These settings are already in Preferences dialog, so adding them back into menu will make incoherence in UI of preferences dialog.
