### ISSUE TITLE
Make the Search Results Window locked (grayed) until the first search

### ISSUE THREAD

**Issue by ArkadiuszMichalski** [notepad-plus-plus/notepad-plus-plus#9655]
### Description of the Issue
I can't open Search Results Window without making one search. It's intentional? Even when I delete all the results, I can open them and it is empty. So why it's blocked at first time? This causes that toggling options in context menu will require one dumy search. 

### Steps to Reproduce the Issue

1. Open NPP.
2. Press F7 or select from menu bar `Search > Search Results window` 
3. Nothing happen.

If this is intentional, and it must be so for some reason, then at least after start NPP let the `Search > Search Results window`  entry in menu bar will be blocked (greyed), until the first search.  So that I don't have to wonder why something is not working when it is visible in this menu. 

![image](https://user-images.githubusercontent.com/2730894/111074599-fbb02600-84e3-11eb-80c4-122066781b99.png)

### Debug Information
```
Notepad++ v7.9.3   (32-bit)
Build time : Mar 14 2021 - 00:16:00
Path : D:\_test\NPPClean\notepad++.exe
Admin mode : ON
Local Conf mode : ON
OS Name : Windows 7 Ultimate (64-bit) 
OS Build : 7601.0
Current ANSI codepage : 1250
Plugins : none
```

**Comment by sasumner** [comment]
>It's intentional?

It's probably "intentional by default".
In ancient time, dev of this feature is adding it (the entire results window concept).
He decides, I don't even need to create this window until the user runs a search.
Voila.  History is written.

>Even when I delete all the results, I can open them and it is empty.

The window is already created at that point.

**Comment by donho** [comment]
It's intentional.
User needs to toggle it if there are some searches in advance.
I don't see any point if user try to make it appear while he/she has never searched before.

**Comment by ArkadiuszMichalski** [comment]
@donho 
>I don't see any point if user try to make it appear while he/she has never searched before.

To toggle an option before I search for something? But if this is how it is supposed to be, so let it be. But why not make this entry locked (grayed) until the first search? I go to the menu `Search`, see that `Search Results Window` is unlocked and when click on it then nothing happens. Does this gray out until the first search require too many lines of code?

**Comment by mere-human** [comment]
I agree, it is strange that there is a menu item "Search Results Window" that does nothing.

**Comment by donho** [comment]
OK, I guess it doesn't require too many lines of code.
