### ISSUE TITLE
Functions list keeps scrolling to the top every time the current file is saved

### ISSUE THREAD

**Issue by jabcreations** [notepad-plus-plus/notepad-plus-plus#9659]
Simple bug: the functions list on the right side keeps scrolling back to the top every single time I save the current file. Because I work in technology I don't trust technology and I'm constantly pressing CTRL+S to negate someone else's irresponsibility from negating my progress. At 2560x1440 my functions list for many common files I edit is vertically longer than the available space and this is exceptionally obnoxious especially right now since I'm going back and forth between common functions and I have to stop my mind-flow and waste time thinking about having to scroll to get the functions back in to view to quickly switch over.

Here is the debug information:
---------------------------------------------------------------------

Notepad++ v7.9.1   (64-bit)
Build time : Nov  2 2020 - 01:07:46
Path : C:\MEDIA\OFFICE\Notepad++\notepad++.exe
Admin mode : ON
Local Conf mode : OFF
OS Name : Windows 10 Pro (64-bit) 
OS Version : 1909
OS Build : 18363.418
Current ANSI codepage : 1252
Plugins : DSpellCheck.dll mimeTools.dll NppConverter.dll NppExport.dll

**Comment by sasumner** [comment]
I like this part:  "Because I work in technology I don't trust technology and I'm constantly pressing CTRL+S to negate someone else's irresponsibility from negating my progress."
