### ISSUE TITLE
Scam website that pretend to be able to download Notepad++

### ISSUE THREAD

**Issue by Rin5743** [notepad-plus-plus/notepad-plus-plus#9662]
[https://note-pad.ccmmsl.com/](https://note-pad.ccmmsl.com/)
IDK what will happen if I download and open that "notepad.exe", but [virustotal.com said this is Trojan](https://www.virustotal.com/gui/file/0cbc7b65168c44983a4f6f7a4e324b9cff20f6c32cd9ae65473afc1c1a058444/detection?fbclid=IwAR0OEYzY-6pIOltHv_a6UCSngsa-G7QLBFcBFU13RqjFzHv8PSbpzu0a4Jk) and Chrome will not let me download because it detected virus.
![image](https://user-images.githubusercontent.com/30818360/111204354-4634af80-8583-11eb-902c-7cdbce3671a2.png)

Saw this website on Facebook AD: [https://www.facebook.com/permalink.php?story_fbid=256101506167730&id=101294838315065]( https://www.facebook.com/permalink.php?story_fbid=256101506167730&id=101294838315065)

**Comment by donho** [comment]
https://twitter.com/Notepad_plus/status/1371579205817864192

**Comment by donho** [comment]
The site is not available now.
