### ISSUE TITLE
Where is Plugin Admin?

### ISSUE THREAD

**Issue by thinkpad4** [notepad-plus-plus/notepad-plus-plus#9664]
![2021-03-16_015640](https://user-images.githubusercontent.com/6820014/111262597-e24dcd80-85fa-11eb-84a9-51889b8c4768.png)

### Description of the Issue
I updated to 7.9.4 and under plugins there is no Plugin Admin option anymore

### Steps to Reproduce the Issue

1. 
2. 
3. 

### Expected Behavior
I expect Plugin Admin to always be there

### Actual Behavior
Plugin Admin isn't showing up in the latest version or 7.9.3, it showed up once in 7.9.2 but after updating a plugin it is gone and won't come back

### Debug Information

Notepad++ v7.9.4   (32-bit)
Build time : Mar 15 2021 - 01:00:14
Path : F:\Notepad++Portable\App\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : ON
OS Name : Windows 7 Professional (64-bit) 
OS Build : 7601.0
Current ANSI codepage : 1252
Plugins : AutoSave.dll ComparePlugin.dll DSpellCheck.dll mimeTools.dll NppConverter.dll NppExport.dll

**Comment by chcg** [comment]
I don't have this issue with:

Notepad++ v7.9.4   (64-bit)
Build time : Mar 15 2021 - 01:03:10
Path : C:\Users\chcg\npp.7.9.4.portable.x64\notepad++.exe
Admin mode : OFF
Local Conf mode : ON
OS Name : Windows 10 Home (64-bit) 
OS Version : 2009
OS Build : 19042.867
Current ANSI codepage : 1252
Plugins : mimeTools.dll NppConverter.dll NppExport.dll 

which portable version of N++ did you install?

Portable (zip) | GPG Signature
Portable (7z) | GPG Signature
Mini-portable (7z) | GPG Signature

**Comment by thinkpad4** [comment]
This portable version https://portableapps.com/news/2021-03-15--notepadpp-portable-7.9.4-released

**Comment by chcg** [comment]
The dll which contains the information about the plugins is located under:

Notepad++Portable\Data\Config\plugins\Config\nppPluginList.dll
and not at:
Notepad++Portable\App\Notepad++\plugins\Config\nppPluginList.dll

after moving it to the place where it is available with normal N++ zip files/installations PA is working again.
So this seems to be a packaging issue of the portableapp provision. Maybe at https://portableapps.com/forums/support/development you can get support on that problem.

**Comment by sasumner** [comment]
>This portable version https://portableapps.com/news/2021-03-15--notepadpp-portable-7.9.4-released

Do NOT report any issues here when using Notepad++ this way, i.e., from "portableapps.com".
Notepad++ provides its own portable version, and if you choose to use something different, that's on you.
