### ISSUE TITLE
[Suggestion] Add remember Text Direction support

### ISSUE THREAD

**Issue by ghost** [notepad-plus-plus/notepad-plus-plus#9665]
Hello. I want to suggest adding support to remember the set option of "Text Direction RTL" or "Text Direction LTR" so it can be used on next launch just like Word Wrap is remembered. Also, if it is possible, it would be nice if Notepad++ could detect document languages and auto switch between RTL and LTR.

Thanks for your time.

**Comment by sasumner** [comment]
@Yaron10 Have you made a similar request in the past? If so, I'm having trouble locating it.

**Comment by sasumner** [comment]
This issue seems to have its roots in this Community thread:  https://community.notepad-plus-plus.org/topic/20872/shaking-effect-in-while-writing-in-arabic/

**Comment by Yaron10** [comment]
@sasumner,

> Have you made a similar request in the past?

Yes, I have.
I'm afraid I won't be able to further test it in the near future.

Thank you for your ongoing work.

**Comment by sasumner** [comment]
>I'm afraid I won't be able to further test it in the near future.

I hope that you are just otherwise busy, and are otherwise well and still using N++!

>Yes, I have.

If you know where, can you link it here?

**Comment by ArkadiuszMichalski** [comment]
Not for search result https://github.com/notepad-plus-plus/notepad-plus-plus/issues/8625? One more limitation https://github.com/notepad-plus-plus/notepad-plus-plus/issues/8847.

**Comment by Yaron10** [comment]
@sasumner,

Quite busy. :)
https://github.com/notepad-plus-plus/notepad-plus-plus/issues/8625#issuecomment-674394409.

Thank you @ArkadiuszMichalski.

**Comment by jacktoreno** [comment]
If there is any questions regarding my suggestions, please let me know. Thanks.

**Comment by maimonid** [comment]
I'm quite agree with this suggestion. There is a also a post at 
[](https://community.notepad-plus-plus.org/topic/24849/feature-request-right-to-left-editing-for-each-tab) which is even more important, but seems to be superseded by the suggestion in this thread.

**Comment by donho** [comment]
https://github.com/notepad-plus-plus/notepad-plus-plus/issues/14385#issuecomment-1837511573
